Azerotcore-wotlk: boss_patchwerk::boss_patchwerkAI Struct Reference
boss_patchwerk::boss_patchwerkAI Struct Reference
Public Member Functions
boss_patchwerkAI (Creature *c)
void Reset () override
void KilledUnit (Unit *who) override
void JustDied (Unit *killer) override
void EnterCombat (Unit *who) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
InstanceScript * pInstance
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 63 of file boss_patchwerk.cpp.
Constructor & Destructor Documentation
boss_patchwerkAI()
boss_patchwerk::boss_patchwerkAI::boss_patchwerkAI (Creature * c) inline explicit
Definition at line 65 of file boss_patchwerk.cpp.
                                                : BossAI(c, BOSS_PATCHWERK)
         {
             pInstance = me->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), ScriptedAI::me, and pInstance.
Member Function Documentation
EnterCombat()
void boss_patchwerk::boss_patchwerkAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from BossAI.
Definition at line 100 of file boss_patchwerk.cpp.
         {
             BossAI::EnterCombat(who);
             Talk(SAY_AGGRO);
             me->SetInCombatWithZone();
             events.ScheduleEvent(EVENT_HATEFUL_STRIKE, 1500);
             events.ScheduleEvent(EVENT_BERSERK, 360000);
             events.ScheduleEvent(EVENT_HEALTH_CHECK, 1000);
             if (pInstance)
             {
                 pInstance->DoStartTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, ACHIEV_TIMED_START_EVENT);
             }
         }
References ACHIEV_TIMED_START_EVENT, ACHIEVEMENT_TIMED_TYPE_EVENT, InstanceScript::DoStartTimedAchievement(), BossAI::EnterCombat(), EVENT_BERSERK, EVENT_HATEFUL_STRIKE, EVENT_HEALTH_CHECK, ScriptedAI::me, pInstance, SAY_AGGRO, Creature::SetInCombatWithZone(), and CreatureAI::Talk().
JustDied()
void boss_patchwerk::boss_patchwerkAI::JustDied (Unit * killer) inline override virtual
Reimplemented from BossAI.
Definition at line 94 of file boss_patchwerk.cpp.
         {
             BossAI::JustDied(killer);
             Talk(SAY_DEATH);
         }
References BossAI::JustDied(), SAY_DEATH, and CreatureAI::Talk().
KilledUnit()
void boss_patchwerk::boss_patchwerkAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 79 of file boss_patchwerk.cpp.
         {
             if (who->GetTypeId() != TYPEID_PLAYER)
                 return;
             if (!urand(0, 3))
             {
                 Talk(SAY_SLAY);
             }
             if (pInstance)
             {
                 pInstance->SetData(DATA_IMMORTAL_FAIL, 0);
             }
         }
References DATA_IMMORTAL_FAIL, Object::GetTypeId(), pInstance, SAY_SLAY, ZoneScript::SetData(), CreatureAI::Talk(), TYPEID_PLAYER, and urand().
Reset()
void boss_patchwerk::boss_patchwerkAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 73 of file boss_patchwerk.cpp.
         {
             BossAI::Reset();
             events.Reset();
         }
References BossAI::Reset().
UpdateAI()
void boss_patchwerk::boss_patchwerkAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 114 of file boss_patchwerk.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_HATEFUL_STRIKE:
                     {
                         // Cast Hateful strike on the player with the highest amount of HP within melee distance, and second threat amount
                         std::list<Unit*> meleeRangeTargets;
                         Unit* finalTarget = nullptr;
                         uint8 counter = 0;
                         auto i = me->getThreatMgr().getThreatList().begin();
                         for (; i != me->getThreatMgr().getThreatList().end(); ++i, ++counter)
{
                             // Gather all units with melee range
                             Unit* target = (*i)->getTarget();
                             if (me->IsWithinMeleeRange(target))
{
                                 meleeRangeTargets.push_back(target);
                             }
                             // and add threat to most hated
                             if (counter < RAID_MODE(2, 3))
{
                                 me->AddThreat(target, 500.0f);
                             }
                         }
                         counter = 0;
                         std::list<Unit*, std::allocator<Unit*>>::iterator itr;
                         for (itr = meleeRangeTargets.begin(); itr != meleeRangeTargets.end(); ++itr, ++counter)
{
                             // if there is only one target available
                             if (meleeRangeTargets.size() == 1)
{
                                 finalTarget = (*itr);
                             }
                             else if (counter > 0) // skip first target
{
                                 if (!finalTarget || (*itr)->GetHealth() > finalTarget->GetHealth())
{
                                     finalTarget = (*itr);
                                 }
                                 // third loop
                                 if (counter >= 2)
                                     break;
                             }
                         }
                         if (finalTarget)
{
                             me->CastSpell(finalTarget, RAID_MODE(SPELL_HATEFUL_STRIKE_10, SPELL_HATEFUL_STRIKE_25), false);
                         }
                         events.RepeatEvent(1000);
                         break;
                     }
                 case EVENT_BERSERK:
                     Talk(EMOTE_BERSERK);
                     me->CastSpell(me, SPELL_BERSERK, true);
                     events.ScheduleEvent(EVENT_SLIME_BOLT, 3000);
                     break;
                 case EVENT_SLIME_BOLT:
                     me->CastSpell(me, SPELL_SLIME_BOLT, false);
                     events.RepeatEvent(3000);
                     break;
                 case EVENT_HEALTH_CHECK:
                     if (me->GetHealthPct() <= 5)
                     {
                         Talk(EMOTE_ENRAGE);
                         me->CastSpell(me, SPELL_FRENZY, true);
                         break;
                     }
                     events.RepeatEvent(1000);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References Unit::AddThreat(), Unit::CastSpell(), diff(), UnitAI::DoMeleeAttackIfReady(), EMOTE_BERSERK, EMOTE_ENRAGE, EVENT_BERSERK, EVENT_HATEFUL_STRIKE, EVENT_HEALTH_CHECK, EVENT_SLIME_BOLT, Unit::GetHealth(), Unit::GetHealthPct(), ThreatMgr::getThreatList(), Unit::getThreatMgr(), Unit::HasUnitState(), Unit::IsWithinMeleeRange(), ScriptedAI::me, ScriptedAI::RAID_MODE(), SPELL_BERSERK, SPELL_FRENZY, SPELL_HATEFUL_STRIKE_10, SPELL_HATEFUL_STRIKE_25, SPELL_SLIME_BOLT, CreatureAI::Talk(), UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
events
EventMap boss_patchwerk::boss_patchwerkAI::events
Definition at line 70 of file boss_patchwerk.cpp.
pInstance
InstanceScript* boss_patchwerk::boss_patchwerkAI::pInstance
Definition at line 71 of file boss_patchwerk.cpp.
Referenced by boss_patchwerkAI(), EnterCombat(), and KilledUnit().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Naxxramas/boss_patchwerk.cpp