Azerotcore-wotlk: VileSpiritActivateEvent Class Reference
VileSpiritActivateEvent Class Reference
Public Member Functions
VileSpiritActivateEvent (Creature *owner)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()
virtual ~BasicEvent ()
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Creature * _owner
Detailed Description
Definition at line 516 of file boss_the_lich_king.cpp.
Constructor & Destructor Documentation
VileSpiritActivateEvent()
VileSpiritActivateEvent::VileSpiritActivateEvent (Creature * owner) inline explicit
Definition at line 519 of file boss_the_lich_king.cpp.
 : _owner(owner) {}
Member Function Documentation
Execute()
bool VileSpiritActivateEvent::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
Definition at line 521 of file boss_the_lich_king.cpp.
     {
         _owner->SetReactState(REACT_AGGRESSIVE);
         _owner->CastSpell(_owner, SPELL_VILE_SPIRIT_MOVE_SEARCH, true);
         _owner->CastSpell((Unit*)nullptr, SPELL_VILE_SPIRIT_DAMAGE_SEARCH, true);
         return true;
     }
References _owner, Unit::CastSpell(), REACT_AGGRESSIVE, Creature::SetReactState(), SPELL_VILE_SPIRIT_DAMAGE_SEARCH, and SPELL_VILE_SPIRIT_MOVE_SEARCH.
Referenced by spell_the_lich_king_trigger_vile_spirit::spell_the_lich_king_trigger_vile_spirit_SpellScript::ActivateSpirit().
Member Data Documentation
_owner
Creature* VileSpiritActivateEvent::_owner private
Definition at line 530 of file boss_the_lich_king.cpp.
Referenced by Execute().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp