Azerotcore-wotlk: npc_belnistrasz::npc_belnistraszAI Struct Reference
npc_belnistrasz::npc_belnistraszAI Struct Reference
Public Member Functions
npc_belnistraszAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *who) override
void JustDied (Unit *) override
void sQuestAccept (Player *, Quest const *quest) override
void MovementInform (uint32 type, uint32 id) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
InstanceScript * instance
EventMap events
bool eventInProgress
bool channeling
uint8 eventProgress
uint8 spawnerCount
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 74 of file razorfen_downs.cpp.
Constructor & Destructor Documentation
npc_belnistraszAI()
npc_belnistrasz::npc_belnistraszAI::npc_belnistraszAI (Creature * creature) inline
Definition at line 76 of file razorfen_downs.cpp.
                                               : ScriptedAI(creature)
         {
             instance = creature->GetInstanceScript();
             eventInProgress = false;
             spawnerCount = 0;
         }
References eventInProgress, WorldObject::GetInstanceScript(), instance, and spawnerCount.
Member Function Documentation
EnterCombat()
void npc_belnistrasz::npc_belnistraszAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 98 of file razorfen_downs.cpp.
         {
             if (channeling)
                 Talk(SAY_WATCH_OUT, who);
             else
             {
                 events.ScheduleEvent(EVENT_FIREBALL, 1000);
                 events.ScheduleEvent(EVENT_FROST_NOVA, urand(8000, 12000));
                 if (urand(0, 100) > 40)
                     Talk(SAY_AGGRO, who);
             }
         }
References channeling, EVENT_FIREBALL, EVENT_FROST_NOVA, SAY_AGGRO, SAY_WATCH_OUT, CreatureAI::Talk(), and urand().
JustDied()
void npc_belnistrasz::npc_belnistraszAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 111 of file razorfen_downs.cpp.
         {
             me->DespawnOrUnsummon(5000);
         }
References Creature::DespawnOrUnsummon(), and ScriptedAI::me.
MovementInform()
void npc_belnistrasz::npc_belnistraszAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 128 of file razorfen_downs.cpp.
         {
             if (type == WAYPOINT_MOTION_TYPE && id == POINT_REACH_IDOL)
             {
                 channeling = true;
                 events.ScheduleEvent(EVENT_CHANNEL, 2000);
             }
         }
References channeling, EVENT_CHANNEL, POINT_REACH_IDOL, and WAYPOINT_MOTION_TYPE.
Reset()
void npc_belnistrasz::npc_belnistraszAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 83 of file razorfen_downs.cpp.
         {
             if (!eventInProgress)
             {
                 if (!me->HasAura(SPELL_ARCANE_INTELLECT))
                     DoCast(me, SPELL_ARCANE_INTELLECT);
                 channeling = false;
                 eventProgress = 0;
                 spawnerCount  = 0;
                 me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_QUESTGIVER);
                 me->SetReactState(REACT_AGGRESSIVE);
             }
         }
References channeling, UnitAI::DoCast(), eventInProgress, eventProgress, Unit::HasAura(), ScriptedAI::me, REACT_AGGRESSIVE, Object::SetFlag(), Creature::SetReactState(), spawnerCount, SPELL_ARCANE_INTELLECT, UNIT_NPC_FLAG_QUESTGIVER, and UNIT_NPC_FLAGS.
sQuestAccept()
void npc_belnistrasz::npc_belnistraszAI::sQuestAccept (Player * , Quest const * quest) inline override virtual
Reimplemented from UnitAI.
Definition at line 116 of file razorfen_downs.cpp.
         {
             if (quest->GetQuestId() == QUEST_EXTINGUISHING_THE_IDOL)
             {
                 eventInProgress = true;
                 Talk(SAY_QUEST_ACCEPTED);
                 me->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_QUESTGIVER);
                 me->SetFaction(FACTION_ESCORTEE_N_NEUTRAL_ACTIVE);
                 me->GetMotionMaster()->MovePath(PATH_ESCORT, false);
             }
         }
References eventInProgress, FACTION_ESCORTEE_N_NEUTRAL_ACTIVE, Unit::GetMotionMaster(), Quest::GetQuestId(), ScriptedAI::me, MotionMaster::MovePath(), PATH_ESCORT, QUEST_EXTINGUISHING_THE_IDOL, Object::RemoveFlag(), SAY_QUEST_ACCEPTED, Unit::SetFaction(), CreatureAI::Talk(), UNIT_NPC_FLAG_QUESTGIVER, and UNIT_NPC_FLAGS.
UpdateAI()
void npc_belnistrasz::npc_belnistraszAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 137 of file razorfen_downs.cpp.
         {
             if (!eventInProgress)
                 return;
             events.Update(diff);
             while (uint32 eventId = events.ExecuteEvent())
             {
                 switch (eventId)
                 {
                     case EVENT_CHANNEL:
                         Talk(SAY_EVENT_START);
                         DoCast(me, SPELL_IDOL_SHUTDOWN_VISUAL);
                         events.ScheduleEvent(EVENT_IDOL_ROOM_SPAWNER, 100);
                         events.ScheduleEvent(EVENT_PROGRESS, 120000);
                         me->SetReactState(REACT_PASSIVE);
                         break;
                     case EVENT_IDOL_ROOM_SPAWNER:
                         if (Creature* creature = me->SummonCreature(NPC_IDOL_ROOM_SPAWNER, PosSummonSpawner[urand(0, 2)], TEMPSUMMON_TIMED_DESPAWN, 4000))
                             creature->AI()->SetData(0, spawnerCount);
                         if (++spawnerCount < 8)
                             events.ScheduleEvent(EVENT_IDOL_ROOM_SPAWNER, 35000);
                         break;
                     case EVENT_PROGRESS:
{
                             switch (eventProgress)
{
                                 case 0:
                                     Talk(SAY_EVENT_THREE_MIN_LEFT);
                                     ++eventProgress;
                                     events.ScheduleEvent(EVENT_PROGRESS, 60000);
                                     break;
                                 case 1:
                                     Talk(SAY_EVENT_TWO_MIN_LEFT);
                                     ++eventProgress;
                                     events.ScheduleEvent(EVENT_PROGRESS, 60000);
                                     break;
                                 case 2:
                                     Talk(SAY_EVENT_ONE_MIN_LEFT);
                                     ++eventProgress;
                                     events.ScheduleEvent(EVENT_PROGRESS, 60000);
                                     break;
                                 case 3:
                                     events.CancelEvent(EVENT_IDOL_ROOM_SPAWNER);
                                     me->InterruptSpell(CURRENT_CHANNELED_SPELL);
                                     Talk(SAY_EVENT_END);
                                     events.ScheduleEvent(EVENT_COMPLETE, 3000);
                                     break;
                             }
                             break;
                         }
                     case EVENT_COMPLETE:
{
                             DoCast(me, SPELL_IDOM_ROOM_CAMERA_SHAKE);
                             me->SummonGameObject(GO_BELNISTRASZS_BRAZIER, 2577.196f, 947.0781f, 53.16757f, 2.356195f, 0, 0, 0.9238796f, 0.3826832f, 3600);
                             std::list<WorldObject*> ClusterList;
                             Acore::AllWorldObjectsInRange objects(me, 50.0f);
                             Acore::WorldObjectListSearcher<Acore::AllWorldObjectsInRange> searcher(me, ClusterList, objects);
                             Cell::VisitAllObjects(me, searcher, 50.0f);
                             for (std::list<WorldObject*>::const_iterator itr = ClusterList.begin(); itr != ClusterList.end(); ++itr)
{
                                 if (Player* player = (*itr)->ToPlayer())
{
                                     if (player->GetQuestStatus(QUEST_EXTINGUISHING_THE_IDOL) == QUEST_STATUS_INCOMPLETE)
                                         player->CompleteQuest(QUEST_EXTINGUISHING_THE_IDOL);
                                 }
                                 else if (GameObject* go = (*itr)->ToGameObject())
{
                                     if (go->GetEntry() == GO_IDOL_OVEN_FIRE || go->GetEntry() == GO_IDOL_CUP_FIRE || go->GetEntry() == GO_IDOL_MOUTH_FIRE)
                                         go->Delete();
                                 }
                             }
                             instance->SetData(GO_BELNISTRASZS_BRAZIER, DONE);
                             me->DespawnOrUnsummon();
                             break;
                         }
                     case EVENT_FIREBALL:
                         if (me->HasUnitState(UNIT_STATE_CASTING) || !UpdateVictim())
                             return;
                         DoCastVictim(SPELL_FIREBALL);
                         events.ScheduleEvent(EVENT_FIREBALL, 8000);
                         break;
                     case EVENT_FROST_NOVA:
                         if (me->HasUnitState(UNIT_STATE_CASTING) || !UpdateVictim())
                             return;
                         DoCast(me, SPELL_FROST_NOVA);
                         events.ScheduleEvent(EVENT_FROST_NOVA, 15000);
                         break;
                 }
             }
             if (!channeling)
                 DoMeleeAttackIfReady();
         }
References channeling, CURRENT_CHANNELED_SPELL, Creature::DespawnOrUnsummon(), UnitAI::DoCast(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), DONE, EVENT_CHANNEL, EVENT_COMPLETE, EVENT_FIREBALL, EVENT_FROST_NOVA, EVENT_IDOL_ROOM_SPAWNER, EVENT_PROGRESS, eventInProgress, eventProgress, GO_BELNISTRASZS_BRAZIER, GO_IDOL_CUP_FIRE, GO_IDOL_MOUTH_FIRE, GO_IDOL_OVEN_FIRE, Unit::HasUnitState(), instance, Unit::InterruptSpell(), ScriptedAI::me, NPC_IDOL_ROOM_SPAWNER, PosSummonSpawner, QUEST_EXTINGUISHING_THE_IDOL, QUEST_STATUS_INCOMPLETE, REACT_PASSIVE, SAY_EVENT_END, SAY_EVENT_ONE_MIN_LEFT, SAY_EVENT_START, SAY_EVENT_THREE_MIN_LEFT, SAY_EVENT_TWO_MIN_LEFT, ZoneScript::SetData(), Creature::SetReactState(), spawnerCount, SPELL_FIREBALL, SPELL_FROST_NOVA, SPELL_IDOL_SHUTDOWN_VISUAL, SPELL_IDOM_ROOM_CAMERA_SHAKE, WorldObject::SummonCreature(), WorldObject::SummonGameObject(), CreatureAI::Talk(), TEMPSUMMON_TIMED_DESPAWN, Object::ToGameObject(), Object::ToPlayer(), UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), urand(), and Cell::VisitAllObjects().
Member Data Documentation
channeling
bool npc_belnistrasz::npc_belnistraszAI::channeling private
Definition at line 236 of file razorfen_downs.cpp.
Referenced by EnterCombat(), MovementInform(), Reset(), and UpdateAI().
eventInProgress
bool npc_belnistrasz::npc_belnistraszAI::eventInProgress private
Definition at line 235 of file razorfen_downs.cpp.
Referenced by npc_belnistraszAI(), Reset(), sQuestAccept(), and UpdateAI().
eventProgress
uint8 npc_belnistrasz::npc_belnistraszAI::eventProgress private
Definition at line 237 of file razorfen_downs.cpp.
Referenced by Reset(), and UpdateAI().
events
EventMap npc_belnistrasz::npc_belnistraszAI::events private
Definition at line 234 of file razorfen_downs.cpp.
instance
InstanceScript* npc_belnistrasz::npc_belnistraszAI::instance private
Definition at line 233 of file razorfen_downs.cpp.
Referenced by npc_belnistraszAI(), and UpdateAI().
spawnerCount
uint8 npc_belnistrasz::npc_belnistraszAI::spawnerCount private
Definition at line 238 of file razorfen_downs.cpp.
Referenced by npc_belnistraszAI(), Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/RazorfenDowns/razorfen_downs.cpp