Azerotcore-wotlk: npc_prospector_remtravel Class Reference
npc_prospector_remtravel Class Reference
Classes
struct npc_prospector_remtravelAI
Public Member Functions
npc_prospector_remtravel ()
bool OnQuestAccept (Player *player, Creature *creature, const Quest *quest) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 321 of file zone_darkshore.cpp.
Constructor & Destructor Documentation
npc_prospector_remtravel()
npc_prospector_remtravel::npc_prospector_remtravel () inline
Definition at line 324 of file zone_darkshore.cpp.
 : CreatureScript("npc_prospector_remtravel") {}
Member Function Documentation
GetAI()
CreatureAI* npc_prospector_remtravel::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 419 of file zone_darkshore.cpp.
     {
         return new npc_prospector_remtravelAI(creature);
     }
OnQuestAccept()
bool npc_prospector_remtravel::OnQuestAccept (Player * player, Creature * creature, const Quest * quest) inline override virtual
Reimplemented from CreatureScript.
Definition at line 406 of file zone_darkshore.cpp.
     {
         if (quest->GetQuestId() == QUEST_ABSENT_MINDED_PT2)
         {
             if (npc_escortAI* pEscortAI = CAST_AI(npc_prospector_remtravel::npc_prospector_remtravelAI, creature->AI()))
                 pEscortAI->Start(false, false, player->GetGUID());
             creature->SetFaction(FACTION_ESCORTEE_A_NEUTRAL_PASSIVE);
         }
         return true;
     }
References Creature::AI(), CAST_AI, FACTION_ESCORTEE_A_NEUTRAL_PASSIVE, Object::GetGUID(), Quest::GetQuestId(), QUEST_ABSENT_MINDED_PT2, and Unit::SetFaction().
The documentation for this class was generated from the following file:
src/server/scripts/Kalimdor/zone_darkshore.cpp