Azerotcore-wotlk: anonymous_namespace{Config.cpp} Namespace Reference
anonymous_namespace{Config.cpp} Namespace Reference
Functions
bool IsAppConfig (std::string_view fileName)
template<typename Format , typename... Args>
void PrintError (std::string_view filename, Format &&fmt, Args &&... args)
void AddKey (std::string const &optionName, std::string const &optionKey, bool replace=true)
void ParseFile (std::string const &file)
bool LoadFile (std::string const &file)
Variables
std::string _filename
std::vector< std::string > _additonalFiles
std::vector< std::string > _args
std::unordered_map< std::string, std::string > _configOptions
std::mutex _configLock
Function Documentation
AddKey()
void anonymous_namespace{Config.cpp}::AddKey (std::string const & optionName, std::string const & optionKey, bool replace = true)
Definition at line 68 of file Config.cpp.
     {
         auto const& itr = _configOptions.find(optionName);
         if (itr != _configOptions.end())
         {
             if (!replace)
             {
                 LOG_ERROR("server.loading", "> Config: Option '%s' is exist! Option key - '%s'", optionName.c_str(), itr->second.c_str());
                 return;
             }
             _configOptions.erase(optionName);
         }
         _configOptions.emplace(optionName, optionKey);
     }
References _configOptions, LOG_ERROR, and G3D::replace().
Referenced by ParseFile().
IsAppConfig()
bool anonymous_namespace{Config.cpp}::IsAppConfig (std::string_view fileName)
Definition at line 36 of file Config.cpp.
     {
         size_t found = fileName.find_first_of("authserver.conf");
         if (found != std::string::npos)
         {
             return true;
         }
         found = fileName.find_first_of("worldserver.conf");
         if (found != std::string::npos)
         {
             return true;
         }
         return false;
     }
Referenced by PrintError().
LoadFile()
bool anonymous_namespace{Config.cpp}::LoadFile (std::string const & file)
Definition at line 179 of file Config.cpp.
     {
         try
         {
             ParseFile(file);
             return true;
         }
         catch (const std::exception& e)
         {
             PrintError(file, "> %s", e.what());
         }
         return false;
     }
References mpq::file, ParseFile(), and PrintError().
Referenced by ConfigMgr::LoadAdditionalFile(), and ConfigMgr::LoadInitial().
ParseFile()
void anonymous_namespace{Config.cpp}::ParseFile (std::string const & file)
Definition at line 85 of file Config.cpp.
     {
         std::ifstream in(file);
         if (in.fail())
         {
             throw ConfigException(Acore::StringFormat("Config::LoadFile: Failed open file '%s'", file.c_str()));
         }
         uint32 count = 0;
         uint32 lineNumber = 0;
         std::unordered_map<std::string /*name*/, std::string /*value*/> fileConfigs;
         auto IsDuplicateOption = [&](std::string const& confOption)
         {
             auto const& itr = fileConfigs.find(confOption);
             if (itr != fileConfigs.end())
             {
                 PrintError(file, "> Config::LoadFile: Dublicate key name '%s' in config file '%s'", std::string(confOption).c_str(), file.c_str());
                 return true;
             }
             return false;
         };
         while (in.good())
         {
             lineNumber++;
             std::string line;
             std::getline(in, line);
             // read line error
             if (!in.good() && !in.eof())
             {
                 throw ConfigException(Acore::StringFormat("> Config::LoadFile: Failure to read line number %u in file '%s'", lineNumber, file.c_str()));
             }
             // remove whitespace in line
             line = Acore::String::Trim(line, in.getloc());
             if (line.empty())
             {
                 continue;
             }
             // comments
             if (line[0] == '#' || line[0] == '[')
             {
                 continue;
             }
             size_t found = line.find_first_of('#');
             if (found != std::string::npos)
             {
                 line = line.substr(0, found);
             }
             auto const equal_pos = line.find('=');
             if (equal_pos == std::string::npos || equal_pos == line.length())
             {
                 PrintError(file, "> Config::LoadFile: Failure to read line number %u in file '%s'. Skip this line", lineNumber, file.c_str());
                 continue;
             }
             auto entry = Acore::String::Trim(line.substr(0, equal_pos), in.getloc());
             auto value = Acore::String::Trim(line.substr(equal_pos + 1, std::string::npos), in.getloc());
             value.erase(std::remove(value.begin(), value.end(), '"'), value.end());
             // Skip if 2+ same options in one config file
             if (IsDuplicateOption(entry))
             {
                 continue;
             }
             // Add to temp container
             fileConfigs.emplace(entry, value);
             count++;
         }
         // No lines read
         if (!count)
         {
             throw ConfigException(Acore::StringFormat("Config::LoadFile: Empty file '%s'", file.c_str()));
         }
         // Add correct keys if file load without errors
         for (auto const& [entry, key] : fileConfigs)
         {
             AddKey(entry, key);
         }
     }
References AddKey(), count(), mpq::file, PrintError(), Acore::StringFormat(), and Acore::String::Trim().
Referenced by LoadFile().
PrintError()
template<typename Format , typename... Args> void anonymous_namespace{Config.cpp}::PrintError (std::string_view filename, Format && fmt, Args &&... args) inline
Definition at line 54 of file Config.cpp.
     {
         std::string message = Acore::StringFormat(std::forward<Format>(fmt), std::forward<Args>(args)...);
         if (IsAppConfig(filename))
         {
             printf("%s\n", message.c_str());
         }
         else
         {
             LOG_ERROR("server.loading", "%s", message.c_str());
         }
     }
References fmt, IsAppConfig(), LOG_ERROR, message(), printf(), and Acore::StringFormat().
Referenced by LoadFile(), and ParseFile().
Variable Documentation
_additonalFiles
std::vector<std::string> anonymous_namespace{Config.cpp}::_additonalFiles
Definition at line 30 of file Config.cpp.
Referenced by ConfigMgr::Configure(), and ConfigMgr::LoadModulesConfigs().
_args
std::vector<std::string> anonymous_namespace{Config.cpp}::_args
Definition at line 31 of file Config.cpp.
Referenced by ConfigMgr::Configure(), ConfigMgr::GetArguments(), and Acore::AcoreStringChatBuilder::operator()().
_configLock
std::mutex anonymous_namespace{Config.cpp}::_configLock
Definition at line 33 of file Config.cpp.
Referenced by ConfigMgr::GetConfigPath(), ConfigMgr::GetFilename(), ConfigMgr::GetKeysByString(), ConfigMgr::LoadAdditionalFile(), and ConfigMgr::LoadInitial().
_configOptions
std::unordered_map<std::string , std::string > anonymous_namespace{Config.cpp}::_configOptions
Definition at line 32 of file Config.cpp.
Referenced by AddKey(), ConfigMgr::GetValueDefault< std::string >(), ConfigMgr::GetKeysByString(), ConfigMgr::GetValueDefault(), and ConfigMgr::LoadInitial().
_filename
std::string anonymous_namespace{Config.cpp}::_filename
Definition at line 29 of file Config.cpp.
Referenced by G3D::FileSystem::_fopen(), G3D::FileSystem::_isDirectory(), G3D::FileSystem::_isZipfile(), G3D::FileSystem::_resolve(), G3D::FileSystem::_size(), ConfigMgr::Configure(), ConfigMgr::GetFilename(), and ConfigMgr::LoadAppConfigs().