Azerotcore-wotlk: go_wg_vehicle_teleporter::go_wg_vehicle_teleporterAI Struct Reference
go_wg_vehicle_teleporter::go_wg_vehicle_teleporterAI Struct Reference
Public Member Functions
go_wg_vehicle_teleporterAI (GameObject *gameObject)
bool IsFriendly (Unit *passenger)
Creature * IsValidVehicle (Creature *cVeh)
void UpdateAI (uint32 diff) override
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32)
virtual ObjectGuid GetGUID (int32) const
virtual bool GossipHello (Player *, bool)
virtual bool GossipSelect (Player *, uint32, uint32)
virtual bool GossipSelectCode (Player *, uint32, uint32, char const *)
virtual bool QuestAccept (Player *, Quest const *)
virtual bool QuestReward (Player *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *)
virtual void Destroyed (Player *, uint32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void OnGameEvent (bool, uint16)
virtual void OnStateChanged (uint32, Unit *)
virtual void EventInform (uint32)
virtual void SpellHit (Unit *, const SpellInfo *)
virtual bool CanBeSeen (Player const *)
Private Attributes
uint32 _checkTimer
Additional Inherited Members
Static Public Member Functions inherited from GameObjectAI
static int Permissible (GameObject const *go)
Protected Attributes inherited from GameObjectAI
GameObject *const me
Detailed Description
Definition at line 749 of file zone_wintergrasp.cpp.
Constructor & Destructor Documentation
go_wg_vehicle_teleporterAI()
go_wg_vehicle_teleporter::go_wg_vehicle_teleporterAI::go_wg_vehicle_teleporterAI (GameObject * gameObject) inline
Definition at line 751 of file zone_wintergrasp.cpp.
                                                            : GameObjectAI(gameObject),
             _checkTimer(0)
         {
         }
Member Function Documentation
IsFriendly()
bool go_wg_vehicle_teleporter::go_wg_vehicle_teleporterAI::IsFriendly (Unit * passenger) inline
Definition at line 756 of file zone_wintergrasp.cpp.
         {
             return ((me->GetUInt32Value(GAMEOBJECT_FACTION) == WintergraspFaction[TEAM_HORDE] && passenger->getRaceMask() & RACEMASK_HORDE) ||
                     (me->GetUInt32Value(GAMEOBJECT_FACTION) == WintergraspFaction[TEAM_ALLIANCE] && passenger->getRaceMask() & RACEMASK_ALLIANCE));
         }
References GAMEOBJECT_FACTION, Unit::getRaceMask(), Object::GetUInt32Value(), GameObjectAI::me, RACEMASK_ALLIANCE, RACEMASK_HORDE, TEAM_ALLIANCE, TEAM_HORDE, and WintergraspFaction.
Referenced by IsValidVehicle().
IsValidVehicle()
Creature* go_wg_vehicle_teleporter::go_wg_vehicle_teleporterAI::IsValidVehicle (Creature * cVeh) inline
Definition at line 762 of file zone_wintergrasp.cpp.
         {
             if (!cVeh->HasAura(SPELL_VEHICLE_TELEPORT))
                 if (Vehicle* vehicle = cVeh->GetVehicleKit())
                     if (Unit* passenger = vehicle->GetPassenger(0))
                         if (IsFriendly(passenger))
                             if (Creature* teleportTrigger = passenger->SummonTrigger(me->GetPositionX() - 60.0f, me->GetPositionY(), me->GetPositionZ() + 1.0f, cVeh->GetOrientation(), 1000))
                                 return teleportTrigger;
             return nullptr;
         }
References Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetVehicleKit(), Unit::HasAura(), IsFriendly(), GameObjectAI::me, SPELL_VEHICLE_TELEPORT, and WorldObject::SummonTrigger().
Referenced by UpdateAI().
UpdateAI()
void go_wg_vehicle_teleporter::go_wg_vehicle_teleporterAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from GameObjectAI.
Definition at line 774 of file zone_wintergrasp.cpp.
         {
             _checkTimer += diff;
             if (_checkTimer >= 1000)
             {
                 for (uint8 i = 0; i < MAX_WINTERGRASP_VEHICLES; i++)
                     if (Creature* vehicleCreature = me->FindNearestCreature(vehiclesList[i], 3.0f, true))
                         if (Creature* teleportTrigger = IsValidVehicle(vehicleCreature))
                             teleportTrigger->CastSpell(vehicleCreature, SPELL_VEHICLE_TELEPORT, true);
                 _checkTimer = 0;
             }
         }
References _checkTimer, WorldObject::FindNearestCreature(), IsValidVehicle(), MAX_WINTERGRASP_VEHICLES, GameObjectAI::me, SPELL_VEHICLE_TELEPORT, and vehiclesList.
Member Data Documentation
_checkTimer
uint32 go_wg_vehicle_teleporter::go_wg_vehicle_teleporterAI::_checkTimer private
Definition at line 788 of file zone_wintergrasp.cpp.
Referenced by UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/zone_wintergrasp.cpp