Azerotcore-wotlk: npc_essence_of_twin Class Reference
npc_essence_of_twin Class Reference
Public Member Functions
npc_essence_of_twin ()
bool OnGossipHello (Player *player, Creature *creature) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 571 of file boss_twin_valkyr.cpp.
Constructor & Destructor Documentation
npc_essence_of_twin()
npc_essence_of_twin::npc_essence_of_twin () inline
Definition at line 574 of file boss_twin_valkyr.cpp.
 : CreatureScript("npc_essence_of_twin") { }
Member Function Documentation
OnGossipHello()
bool npc_essence_of_twin::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 576 of file boss_twin_valkyr.cpp.
     {
         switch( creature->GetEntry() )
         {
             case NPC_LIGHT_ESSENCE:
                 {
                     uint32 essenceId = 0;
                     uint32 effect2Id = 0;
                     //uint32 empoweredId = 0;
                     uint32 touchId1 = 0;
                     //uint32 touchId2 = 0;
                     switch( creature->GetMap()->GetDifficulty() )
                     {
                         case 0:
                             essenceId = 65684;
                             //empoweredId = 65724;
                             touchId1 = 65950;
                             //touchId2 = 66001;
                             effect2Id = 65827;
                             break;
                         case 1:
                             essenceId = 67176;
                             //empoweredId = 67213;
                             touchId1 = 67296;
                             //touchId2 = 67281;
                             effect2Id = 67179;
                             break;
                         case 2:
                             essenceId = 67177;
                             //empoweredId = 67214;
                             touchId1 = 67297;
                             //touchId2 = 67282;
                             effect2Id = 67180;
                             break;
                         case 3:
                             essenceId = 67178;
                             //empoweredId = 67215;
                             touchId1 = 67298;
                             //touchId2 = 67283;
                             effect2Id = 67181;
                             break;
                     }
                     player->RemoveAura(essenceId);
                     player->RemoveAura(effect2Id);
                     player->RemoveAura(touchId1);
                     //player->RemoveAura(touchId2); // dont remove black touch here - only white can have black touch - so white changing to white - so no change of color
                     //player->RemoveAura(empoweredId); // apply new empowered?
                     player->CastSpell(player, SPELL_LIGHT_ESSENCE, true);
                 }
                 break;
             case NPC_DARK_ESSENCE:
                 {
                     uint32 essenceId = 0;
                     uint32 effect2Id = 0;
                     //uint32 empoweredId = 0;
                     //uint32 touchId1 = 0;
                     uint32 touchId2 = 0;
                     switch( creature->GetMap()->GetDifficulty() )
                     {
                         case 0:
                             essenceId = 65686;
                             //empoweredId = 65748;
                             //touchId1 = 65950;
                             touchId2 = 66001;
                             effect2Id = 65811;
                             break;
                         case 1:
                             essenceId = 67222;
                             //empoweredId = 67216;
                             //touchId1 = 67296;
                             touchId2 = 67281;
                             effect2Id = 67511;
                             break;
                         case 2:
                             essenceId = 67223;
                             //empoweredId = 67217;
                             //touchId1 = 67297;
                             touchId2 = 67282;
                             effect2Id = 67512;
                             break;
                         case 3:
                             essenceId = 67224;
                             //empoweredId = 67218;
                             //touchId1 = 67298;
                             touchId2 = 67283;
                             effect2Id = 67513;
                             break;
                     }
                     player->RemoveAura(essenceId);
                     player->RemoveAura(effect2Id);
                     //player->RemoveAura(touchId1); // dont remove white touch here - only black can have white touch - so black changing to black - so no change of color
                     player->RemoveAura(touchId2);
                     //player->RemoveAura(empoweredId); // apply new empowered?
                     player->CastSpell(player, SPELL_DARK_ESSENCE, true);
                 }
                 break;
             default:
                 break;
         }
         CloseGossipMenuFor(player);
         return true;
     }
References Unit::CastSpell(), CloseGossipMenuFor(), Map::GetDifficulty(), Object::GetEntry(), WorldObject::GetMap(), NPC_DARK_ESSENCE, NPC_LIGHT_ESSENCE, Unit::RemoveAura(), SPELL_DARK_ESSENCE, and SPELL_LIGHT_ESSENCE.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_twin_valkyr.cpp