Azerotcore-wotlk: SmartTrigger Class Reference
SmartTrigger Class Reference
Public Member Functions
SmartTrigger ()
bool OnTrigger (Player *player, AreaTrigger const *trigger) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 1181 of file SmartAI.cpp.
Constructor & Destructor Documentation
SmartTrigger()
SmartTrigger::SmartTrigger () inline
Definition at line 1184 of file SmartAI.cpp.
 : AreaTriggerScript("SmartTrigger") {}
Member Function Documentation
OnTrigger()
bool SmartTrigger::OnTrigger (Player * player, AreaTrigger const * trigger) inline override virtual
Reimplemented from AreaTriggerScript.
Definition at line 1186 of file SmartAI.cpp.
     {
         if (!player->IsAlive())
             return false;
         LOG_DEBUG("sql.sql", "AreaTrigger %u is using SmartTrigger script", trigger->entry);
         SmartScript script;
         script.OnInitialize(nullptr, trigger);
         script.ProcessEventsFor(SMART_EVENT_AREATRIGGER_ONTRIGGER, player, trigger->entry);
         return true;
     }
References AreaTrigger::entry, Unit::IsAlive(), LOG_DEBUG, SmartScript::OnInitialize(), SmartScript::ProcessEventsFor(), and SMART_EVENT_AREATRIGGER_ONTRIGGER.
The documentation for this class was generated from the following file:
src/server/game/AI/SmartScripts/SmartAI.cpp