Azerotcore-wotlk: deps/mysqllite/include/internal/my_handler.h File Reference
my_handler.h File Reference
#include "myisampack.h"
#include "m_ctype.h"
Classes
struct st_HA_KEYSEG
Macros
#define HA_MAX_POSSIBLE_KEY 255 /* For myisamchk */
#define HA_MAX_KEY_LENGTH 1000 /* Max length in bytes */
#define HA_MAX_KEY_SEG 16 /* Max segments for key */
#define HA_MAX_POSSIBLE_KEY_BUFF (HA_MAX_KEY_LENGTH + 24+ 6+6)
#define HA_MAX_KEY_BUFF (HA_MAX_KEY_LENGTH+HA_MAX_KEY_SEG*6+8+8)
#define get_key_length(length, key)
#define get_key_length_rdonly(length, key)
#define get_key_pack_length(length, length_pack, key)
#define store_key_length_inc(key, length)
#define size_to_store_key_length(length) ((length) < 255 ? 1 : 3)
#define get_rec_bits(bit_ptr, bit_ofs, bit_len)
#define set_rec_bits(bits, bit_ptr, bit_ofs, bit_len)
#define clr_rec_bits(bit_ptr, bit_ofs, bit_len) set_rec_bits(0, bit_ptr, bit_ofs, bit_len)
#define portable_sizeof_char_ptr 8
Typedefs
typedef struct st_HA_KEYSEG HA_KEYSEG
Functions
int ha_compare_text (CHARSET_INFO *, uchar *, uint, uchar *, uint, my_bool, my_bool)
int ha_key_cmp (register HA_KEYSEG *keyseg, register uchar *a, register uchar *b, uint key_length, uint nextflag, uint *diff_pos)
HA_KEYSEG * ha_find_null (HA_KEYSEG *keyseg, uchar *a)
void my_handler_error_register (void)
void my_handler_error_unregister (void)
Macro Definition Documentation
clr_rec_bits
#define clr_rec_bits (bit_ptr, bit_ofs, bit_len) set_rec_bits(0, bit_ptr, bit_ofs, bit_len)
Definition at line 108 of file my_handler.h.
get_key_length
#define get_key_length (length, key)
Value:
{ if (*(uchar*) (key) != 255) \
    length= (uint) *(uchar*) ((key)++); \
  else \
  { length= mi_uint2korr((key)+1); (key)+=3; } \
}
Definition at line 65 of file my_handler.h.
get_key_length_rdonly
#define get_key_length_rdonly (length, key)
Value:
{ if (*(uchar*) (key) != 255) \
    length= ((uint) *(uchar*) ((key))); \
  else \
  { length= mi_uint2korr((key)+1); } \
}
Definition at line 72 of file my_handler.h.
get_key_pack_length
#define get_key_pack_length (length, length_pack, key)
Value:
{ if (*(uchar*) (key) != 255) \
  { length= (uint) *(uchar*) ((key)++); length_pack= 1; }\
  else \
  { length=mi_uint2korr((key)+1); (key)+= 3; length_pack= 3; } \
}
Definition at line 79 of file my_handler.h.
get_rec_bits
#define get_rec_bits (bit_ptr, bit_ofs, bit_len)
Value:
  (((((uint16) (bit_ptr)[1] << 8) | (uint16) (bit_ptr)[0]) >> (bit_ofs)) & \
   ((1 << (bit_len)) - 1))
Definition at line 95 of file my_handler.h.
HA_MAX_KEY_BUFF
#define HA_MAX_KEY_BUFF (HA_MAX_KEY_LENGTH+HA_MAX_KEY_SEG*6+8+8)
Definition at line 48 of file my_handler.h.
HA_MAX_KEY_LENGTH
#define HA_MAX_KEY_LENGTH 1000 /* Max length in bytes */
Definition at line 44 of file my_handler.h.
HA_MAX_KEY_SEG
#define HA_MAX_KEY_SEG 16 /* Max segments for key */
Definition at line 45 of file my_handler.h.
HA_MAX_POSSIBLE_KEY
#define HA_MAX_POSSIBLE_KEY 255 /* For myisamchk */
Definition at line 38 of file my_handler.h.
HA_MAX_POSSIBLE_KEY_BUFF
#define HA_MAX_POSSIBLE_KEY_BUFF (HA_MAX_KEY_LENGTH + 24+ 6+6)
Definition at line 47 of file my_handler.h.
portable_sizeof_char_ptr
#define portable_sizeof_char_ptr 8
Definition at line 125 of file my_handler.h.
set_rec_bits
#define set_rec_bits (bits, bit_ptr, bit_ofs, bit_len)
Value:
{ \
  (bit_ptr)[0]= ((bit_ptr)[0] & ~(((1 << (bit_len)) - 1) << (bit_ofs))) | \
                ((bits) << (bit_ofs)); \
  if ((bit_ofs) + (bit_len) > 8) \
    (bit_ptr)[1]= ((bit_ptr)[1] & ~((1 << ((bit_len) - 8 + (bit_ofs))) - 1)) | \
                  ((bits) >> (8 - (bit_ofs))); \
}
Definition at line 99 of file my_handler.h.
size_to_store_key_length
#define size_to_store_key_length (length) ((length) < 255 ? 1 : 3)
Definition at line 93 of file my_handler.h.
store_key_length_inc
#define store_key_length_inc (key, length)
Value:
{ if ((length) < 255) \
  { *(key)++= (length); } \
  else \
  { *(key)=255; mi_int2store((key)+1,(length)); (key)+=3; } \
}
Definition at line 86 of file my_handler.h.
Typedef Documentation
HA_KEYSEG
typedef struct st_HA_KEYSEG HA_KEYSEG
Function Documentation
ha_compare_text()
int ha_compare_text (CHARSET_INFO * charset_info, uchar * a, uint a_length, uchar * b, uint b_length, my_bool part_key, my_bool skip_end_space)
Definition at line 28 of file my_handler.c.
 {
   if (!part_key)
     return charset_info->coll->strnncollsp(charset_info, a, a_length,
                                            b, b_length, (my_bool)!skip_end_space);
   return charset_info->coll->strnncoll(charset_info, a, a_length,
                                        b, b_length, part_key);
 }
References mpq::a, b, charset_info_st::coll, my_collation_handler_st::strnncoll, and my_collation_handler_st::strnncollsp.
Referenced by ha_key_cmp().
ha_find_null()
HA_KEYSEG* ha_find_null (HA_KEYSEG * keyseg, uchar * a)
Definition at line 502 of file my_handler.c.
 {
   for (; (enum ha_base_keytype) keyseg->type != HA_KEYTYPE_END; keyseg++)
   {
     uchar *end;
     if (keyseg->null_bit)
     {
       if (!*a++)
         return keyseg;
     }
     end= a+ keyseg->length;
     switch ((enum ha_base_keytype) keyseg->type) {
     case HA_KEYTYPE_TEXT:
     case HA_KEYTYPE_BINARY:
     case HA_KEYTYPE_BIT:
       if (keyseg->flag & HA_SPACE_PACK)
       {
         int a_length;
         get_key_length(a_length, a);
         a += a_length;
         break;
       }
       else
         a= end;
       break;
     case HA_KEYTYPE_VARTEXT1:
     case HA_KEYTYPE_VARTEXT2:
     case HA_KEYTYPE_VARBINARY1:
     case HA_KEYTYPE_VARBINARY2:
       {
         int a_length;
         get_key_length(a_length, a);
         a+= a_length;
         break;
       }
     case HA_KEYTYPE_NUM:
       if (keyseg->flag & HA_SPACE_PACK)
       {
         int alength= *a++;
         end= a+alength;
       }
       a= end;
       break;
     case HA_KEYTYPE_INT8:
     case HA_KEYTYPE_SHORT_INT:
     case HA_KEYTYPE_USHORT_INT:
     case HA_KEYTYPE_LONG_INT:
     case HA_KEYTYPE_ULONG_INT:
     case HA_KEYTYPE_INT24:
     case HA_KEYTYPE_UINT24:
 #ifdef HAVE_LONG_LONG
     case HA_KEYTYPE_LONGLONG:
     case HA_KEYTYPE_ULONGLONG:
 #endif
     case HA_KEYTYPE_FLOAT:
     case HA_KEYTYPE_DOUBLE:
       a= end;
       break;
     case HA_KEYTYPE_END:                        /* purecov: inspected */
       /* keep compiler happy */
       DBUG_ASSERT(0);
       break;
     }
   }
   return keyseg;
 }
References mpq::a, DBUG_ASSERT, st_HA_KEYSEG::flag, get_key_length, HA_KEYTYPE_BINARY, HA_KEYTYPE_BIT, HA_KEYTYPE_DOUBLE, HA_KEYTYPE_END, HA_KEYTYPE_FLOAT, HA_KEYTYPE_INT24, HA_KEYTYPE_INT8, HA_KEYTYPE_LONG_INT, HA_KEYTYPE_LONGLONG, HA_KEYTYPE_NUM, HA_KEYTYPE_SHORT_INT, HA_KEYTYPE_TEXT, HA_KEYTYPE_UINT24, HA_KEYTYPE_ULONG_INT, HA_KEYTYPE_ULONGLONG, HA_KEYTYPE_USHORT_INT, HA_KEYTYPE_VARBINARY1, HA_KEYTYPE_VARBINARY2, HA_KEYTYPE_VARTEXT1, HA_KEYTYPE_VARTEXT2, HA_SPACE_PACK, st_HA_KEYSEG::length, st_HA_KEYSEG::null_bit, and st_HA_KEYSEG::type.
ha_key_cmp()
int ha_key_cmp (register HA_KEYSEG * keyseg, register uchar * a, register uchar * b, uint key_length, uint nextflag, uint * diff_pos)
Definition at line 123 of file my_handler.c.
 {
   int flag;
   int16 s_1,s_2;
   int32 l_1,l_2;
   uint32 u_1,u_2;
   float f_1,f_2;
   double d_1,d_2;
   uint next_key_length;
   uchar *orig_b= b;
   *diff_pos=0;
   for ( ; (int) key_length >0 ; key_length=next_key_length, keyseg++)
   {
     uchar *end;
     uint piks=! (keyseg->flag & HA_NO_SORT);
     (*diff_pos)++;
     diff_pos[1]= (uint)(b - orig_b);
     /* Handle NULL part */
     if (keyseg->null_bit)
     {
       key_length--;
       if (*a != *b && piks)
       {
         flag = (int) *a - (int) *b;
         return ((keyseg->flag & HA_REVERSE_SORT) ? -flag : flag);
       }
       b++;
       if (!*a++)                                /* If key was NULL */
       {
         if (nextflag == (SEARCH_FIND | SEARCH_UPDATE))
           nextflag=SEARCH_SAME;                 /* Allow duplicate keys */
     else if (nextflag & SEARCH_NULL_ARE_NOT_EQUAL)
     {
       /*
         This is only used from mi_check() to calculate cardinality.
         It can't be used when searching for a key as this would cause
         compare of (a,b) and (b,a) to return the same value.
       */
       return -1;
     }
         next_key_length=key_length;
         continue;                               /* To next key part */
       }
     }
     end= a+ min(keyseg->length,key_length);
     next_key_length=key_length-keyseg->length;
     switch ((enum ha_base_keytype) keyseg->type) {
     case HA_KEYTYPE_TEXT:                       /* Ascii; Key is converted */
       if (keyseg->flag & HA_SPACE_PACK)
       {
         int a_length,b_length,pack_length;
         get_key_length(a_length,a);
         get_key_pack_length(b_length,pack_length,b);
         next_key_length=key_length-b_length-pack_length;
         if (piks &&
             (flag=ha_compare_text(keyseg->charset,a,a_length,b,b_length,
                   (my_bool) ((nextflag & SEARCH_PREFIX) &&
                          next_key_length <= 0),
                   (my_bool)!(nextflag & SEARCH_PREFIX))))
           return ((keyseg->flag & HA_REVERSE_SORT) ? -flag : flag);
         a+=a_length;
         b+=b_length;
         break;
       }
       else
       {
     uint length=(uint) (end-a), a_length=length, b_length=length;
         if (piks &&
             (flag= ha_compare_text(keyseg->charset, a, a_length, b, b_length,
                    (my_bool) ((nextflag & SEARCH_PREFIX) &&
                           next_key_length <= 0),
                    (my_bool)!(nextflag & SEARCH_PREFIX))))
           return ((keyseg->flag & HA_REVERSE_SORT) ? -flag : flag);
         a=end;
         b+=length;
       }
       break;
     case HA_KEYTYPE_BINARY:
     case HA_KEYTYPE_BIT:
       if (keyseg->flag & HA_SPACE_PACK)
       {
         int a_length,b_length,pack_length;
         get_key_length(a_length,a);
         get_key_pack_length(b_length,pack_length,b);
         next_key_length=key_length-b_length-pack_length;
         if (piks &&
         (flag=compare_bin(a,a_length,b,b_length,
                               (my_bool) ((nextflag & SEARCH_PREFIX) &&
                                          next_key_length <= 0),1)))
           return ((keyseg->flag & HA_REVERSE_SORT) ? -flag : flag);
         a+=a_length;
         b+=b_length;
         break;
       }
       else
       {
         uint length=keyseg->length;
         if (piks &&
         (flag=compare_bin(a,length,b,length,
                               (my_bool) ((nextflag & SEARCH_PREFIX) &&
                                          next_key_length <= 0),0)))
           return ((keyseg->flag & HA_REVERSE_SORT) ? -flag : flag);
         a+=length;
         b+=length;
       }
       break;
     case HA_KEYTYPE_VARTEXT1:
     case HA_KEYTYPE_VARTEXT2:
       {
         int a_length,b_length,pack_length;
         get_key_length(a_length,a);
         get_key_pack_length(b_length,pack_length,b);
         next_key_length=key_length-b_length-pack_length;
         if (piks &&
         (flag= ha_compare_text(keyseg->charset,a,a_length,b,b_length,
                                    (my_bool) ((nextflag & SEARCH_PREFIX) &&
                                               next_key_length <= 0),
                    (my_bool) ((nextflag & (SEARCH_FIND |
                                SEARCH_UPDATE)) ==
                           SEARCH_FIND &&
                                               ! (keyseg->flag &
                                                  HA_END_SPACE_ARE_EQUAL)))))
           return ((keyseg->flag & HA_REVERSE_SORT) ? -flag : flag);
         a+= a_length;
         b+= b_length;
         break;
       }
       break;
     case HA_KEYTYPE_VARBINARY1:
     case HA_KEYTYPE_VARBINARY2:
       {
         int a_length,b_length,pack_length;
         get_key_length(a_length,a);
         get_key_pack_length(b_length,pack_length,b);
         next_key_length=key_length-b_length-pack_length;
         if (piks &&
         (flag=compare_bin(a,a_length,b,b_length,
                               (my_bool) ((nextflag & SEARCH_PREFIX) &&
                                          next_key_length <= 0), 0)))
           return ((keyseg->flag & HA_REVERSE_SORT) ? -flag : flag);
         a+=a_length;
         b+=b_length;
       }
       break;
     case HA_KEYTYPE_INT8:
     {
       int i_1= (int) *((signed char*) a);
       int i_2= (int) *((signed char*) b);
       if (piks && (flag = CMP_NUM(i_1,i_2)))
         return ((keyseg->flag & HA_REVERSE_SORT) ? -flag : flag);
       a= end;
       b++;
       break;
     }
     case HA_KEYTYPE_SHORT_INT:
       s_1= mi_sint2korr(a);
       s_2= mi_sint2korr(b);
       if (piks && (flag = CMP_NUM(s_1,s_2)))
         return ((keyseg->flag & HA_REVERSE_SORT) ? -flag : flag);
       a=  end;
       b+= 2; /* sizeof(short int); */
       break;
     case HA_KEYTYPE_USHORT_INT:
       {
         uint16 us_1,us_2;
         us_1= mi_sint2korr(a);
         us_2= mi_sint2korr(b);
         if (piks && (flag = CMP_NUM(us_1,us_2)))
           return ((keyseg->flag & HA_REVERSE_SORT) ? -flag : flag);
         a=  end;
         b+=2; /* sizeof(short int); */
         break;
       }
     case HA_KEYTYPE_LONG_INT:
       l_1= mi_sint4korr(a);
       l_2= mi_sint4korr(b);
       if (piks && (flag = CMP_NUM(l_1,l_2)))
         return ((keyseg->flag & HA_REVERSE_SORT) ? -flag : flag);
       a=  end;
       b+= 4; /* sizeof(long int); */
       break;
     case HA_KEYTYPE_ULONG_INT:
       u_1= mi_sint4korr(a);
       u_2= mi_sint4korr(b);
       if (piks && (flag = CMP_NUM(u_1,u_2)))
         return ((keyseg->flag & HA_REVERSE_SORT) ? -flag : flag);
       a=  end;
       b+= 4; /* sizeof(long int); */
       break;
     case HA_KEYTYPE_INT24:
       l_1=mi_sint3korr(a);
       l_2=mi_sint3korr(b);
       if (piks && (flag = CMP_NUM(l_1,l_2)))
         return ((keyseg->flag & HA_REVERSE_SORT) ? -flag : flag);
       a=  end;
       b+= 3;
       break;
     case HA_KEYTYPE_UINT24:
       l_1=mi_uint3korr(a);
       l_2=mi_uint3korr(b);
       if (piks && (flag = CMP_NUM(l_1,l_2)))
         return ((keyseg->flag & HA_REVERSE_SORT) ? -flag : flag);
       a=  end;
       b+= 3;
       break;
     case HA_KEYTYPE_FLOAT:
       mi_float4get(f_1,a);
       mi_float4get(f_2,b);
       /*
         The following may give a compiler warning about floating point
         comparison not being safe, but this is ok in this context as
         we are bascily doing sorting
       */
       if (piks && (flag = CMP_NUM(f_1,f_2)))
         return ((keyseg->flag & HA_REVERSE_SORT) ? -flag : flag);
       a=  end;
       b+= 4; /* sizeof(float); */
       break;
     case HA_KEYTYPE_DOUBLE:
       mi_float8get(d_1,a);
       mi_float8get(d_2,b);
       /*
         The following may give a compiler warning about floating point
         comparison not being safe, but this is ok in this context as
         we are bascily doing sorting
       */
       if (piks && (flag = CMP_NUM(d_1,d_2)))
         return ((keyseg->flag & HA_REVERSE_SORT) ? -flag : flag);
       a=  end;
       b+= 8;  /* sizeof(double); */
       break;
     case HA_KEYTYPE_NUM:                                /* Numeric key */
     {
       int swap_flag= 0;
       int alength,blength;
       if (keyseg->flag & HA_REVERSE_SORT)
       {
         swap_variables(uchar*, a, b);
         swap_flag=1;                            /* Remember swap of a & b */
         end= a+ (int) (end-b);
       }
       if (keyseg->flag & HA_SPACE_PACK)
       {
         alength= *a++; blength= *b++;
         end=a+alength;
         next_key_length=key_length-blength-1;
       }
       else
       {
         alength= (int) (end-a);
         blength=keyseg->length;
         /* remove pre space from keys */
         for ( ; alength && *a == ' ' ; a++, alength--) ;
         for ( ; blength && *b == ' ' ; b++, blength--) ;
       }
       if (piks)
       {
     if (*a == '-')
     {
       if (*b != '-')
         return -1;
       a++; b++;
       swap_variables(uchar*, a, b);
       swap_variables(int, alength, blength);
       swap_flag=1-swap_flag;
       alength--; blength--;
       end=a+alength;
     }
     else if (*b == '-')
       return 1;
     while (alength && (*a == '+' || *a == '0'))
     {
       a++; alength--;
     }
     while (blength && (*b == '+' || *b == '0'))
     {
       b++; blength--;
     }
     if (alength != blength)
       return (alength < blength) ? -1 : 1;
     while (a < end)
       if (*a++ !=  *b++)
         return ((int) a[-1] - (int) b[-1]);
       }
       else
       {
         b+=(end-a);
         a=end;
       }
       if (swap_flag)                            /* Restore pointers */
         swap_variables(uchar*, a, b);
       break;
     }
 #ifdef HAVE_LONG_LONG
     case HA_KEYTYPE_LONGLONG:
     {
       longlong ll_a,ll_b;
       ll_a= mi_sint8korr(a);
       ll_b= mi_sint8korr(b);
       if (piks && (flag = CMP_NUM(ll_a,ll_b)))
         return ((keyseg->flag & HA_REVERSE_SORT) ? -flag : flag);
       a=  end;
       b+= 8;
       break;
     }
     case HA_KEYTYPE_ULONGLONG:
     {
       ulonglong ll_a,ll_b;
       ll_a= mi_uint8korr(a);
       ll_b= mi_uint8korr(b);
       if (piks && (flag = CMP_NUM(ll_a,ll_b)))
         return ((keyseg->flag & HA_REVERSE_SORT) ? -flag : flag);
       a=  end;
       b+= 8;
       break;
     }
 #endif
     case HA_KEYTYPE_END:                        /* Ready */
       goto end;                                 /* diff_pos is incremented */
     }
   }
   (*diff_pos)++;
 end:
   if (!(nextflag & SEARCH_FIND))
   {
     uint i;
     if (nextflag & (SEARCH_NO_FIND | SEARCH_LAST)) /* Find record after key */
       return (nextflag & (SEARCH_BIGGER | SEARCH_LAST)) ? -1 : 1;
     flag=0;
     for (i=keyseg->length ; i-- > 0 ; )
     {
       if (*a++ != *b++)
       {
         flag= FCMP(a[-1],b[-1]);
         break;
       }
     }
     if (nextflag & SEARCH_SAME)
       return (flag);                            /* read same */
     if (nextflag & SEARCH_BIGGER)
       return (flag <= 0 ? -1 : 1);              /* read next */
     return (flag < 0 ? -1 : 1);                 /* read previous */
   }
   return 0;
 } /* ha_key_cmp */
References mpq::a, b, st_HA_KEYSEG::charset, CMP_NUM, compare_bin(), FCMP, st_HA_KEYSEG::flag, get_key_length, get_key_pack_length, ha_compare_text(), HA_END_SPACE_ARE_EQUAL, HA_KEYTYPE_BINARY, HA_KEYTYPE_BIT, HA_KEYTYPE_DOUBLE, HA_KEYTYPE_END, HA_KEYTYPE_FLOAT, HA_KEYTYPE_INT24, HA_KEYTYPE_INT8, HA_KEYTYPE_LONG_INT, HA_KEYTYPE_LONGLONG, HA_KEYTYPE_NUM, HA_KEYTYPE_SHORT_INT, HA_KEYTYPE_TEXT, HA_KEYTYPE_UINT24, HA_KEYTYPE_ULONG_INT, HA_KEYTYPE_ULONGLONG, HA_KEYTYPE_USHORT_INT, HA_KEYTYPE_VARBINARY1, HA_KEYTYPE_VARBINARY2, HA_KEYTYPE_VARTEXT1, HA_KEYTYPE_VARTEXT2, HA_NO_SORT, HA_REVERSE_SORT, HA_SPACE_PACK, G3D::length(), st_HA_KEYSEG::length, mi_float4get, mi_float8get, mi_sint2korr, mi_sint3korr, mi_sint4korr, mi_sint8korr, mi_uint3korr, mi_uint8korr, min, st_HA_KEYSEG::null_bit, SEARCH_BIGGER, SEARCH_FIND, SEARCH_LAST, SEARCH_NO_FIND, SEARCH_NULL_ARE_NOT_EQUAL, SEARCH_PREFIX, SEARCH_SAME, SEARCH_UPDATE, swap_variables, and st_HA_KEYSEG::type.
my_handler_error_register()
void my_handler_error_register (void)
Definition at line 585 of file my_handler.c.
 {
   /*
     If you got compilation error here about compile_time_assert array, check
     that every HA_ERR_xxx constant has a corresponding error message in
     handler_error_messages[] list (check mysys/ma_handler_errors.h and
     include/my_base.h).
   */
   compile_time_assert(HA_ERR_FIRST + array_elements(handler_error_messages) ==
                       HA_ERR_LAST + 1);
   my_error_register(get_handler_error_messages, HA_ERR_FIRST,
                     HA_ERR_FIRST+ array_elements(handler_error_messages)-1);
 }
References array_elements, compile_time_assert, get_handler_error_messages(), HA_ERR_FIRST, HA_ERR_LAST, handler_error_messages, and my_error_register().
my_handler_error_unregister()
void my_handler_error_unregister (void)
Definition at line 600 of file my_handler.c.
 {
   my_error_unregister(HA_ERR_FIRST,
                       HA_ERR_FIRST+ array_elements(handler_error_messages)-1);
 }
References array_elements, HA_ERR_FIRST, handler_error_messages, and my_error_unregister().