Azerotcore-wotlk: achievement_save_the_day Class Reference
achievement_save_the_day Class Reference
Public Member Functions
achievement_save_the_day ()
bool OnCheck (Player *source, Unit *target, uint32) override
Public Member Functions inherited from AchievementCriteriaScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AchievementCriteriaScript
AchievementCriteriaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 52 of file achievement_scripts.cpp.
Constructor & Destructor Documentation
achievement_save_the_day()
achievement_save_the_day::achievement_save_the_day () inline
Definition at line 55 of file achievement_scripts.cpp.
 : AchievementCriteriaScript("achievement_save_the_day") { }
Member Function Documentation
OnCheck()
bool achievement_save_the_day::OnCheck (Player * source, Unit * target, uint32) inline override virtual
Reimplemented from AchievementCriteriaScript.
Definition at line 57 of file achievement_scripts.cpp.
     {
         if (!target)
             return false;
         if (Player const* player = target->ToPlayer())
         {
             Battleground* bg = source->GetBattleground();
             return bg && bg->GetBgTypeID(true) == BATTLEGROUND_WS && bg->ToBattlegroundWS()->GetFlagState(player->GetTeamId()) == BG_WS_FLAG_STATE_ON_BASE;
         }
         return false;
     }
References BATTLEGROUND_WS, BG_WS_FLAG_STATE_ON_BASE, Player::GetBattleground(), Battleground::GetBgTypeID(), BattlegroundWS::GetFlagState(), Battleground::ToBattlegroundWS(), and Object::ToPlayer().
The documentation for this class was generated from the following file:
src/server/scripts/World/achievement_scripts.cpp