Azerotcore-wotlk: achievement_mimiron_set_up_us_the_bomb_11 Class Reference
achievement_mimiron_set_up_us_the_bomb_11 Class Reference
Public Member Functions
achievement_mimiron_set_up_us_the_bomb_11 ()
bool OnCheck (Player *, Unit *target, uint32) override
Public Member Functions inherited from AchievementCriteriaScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AchievementCriteriaScript
AchievementCriteriaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 2533 of file boss_mimiron.cpp.
Constructor & Destructor Documentation
achievement_mimiron_set_up_us_the_bomb_11()
achievement_mimiron_set_up_us_the_bomb_11::achievement_mimiron_set_up_us_the_bomb_11 () inline
Definition at line 2536 of file boss_mimiron.cpp.
 : AchievementCriteriaScript("achievement_mimiron_set_up_us_the_bomb_11") {}
Member Function Documentation
OnCheck()
bool achievement_mimiron_set_up_us_the_bomb_11::OnCheck (Player * , Unit * target, uint32) inline override virtual
Reimplemented from AchievementCriteriaScript.
Definition at line 2538 of file boss_mimiron.cpp.
     {
         return target && target->GetEntry() == NPC_MIMIRON && target->GetTypeId() == TYPEID_UNIT && !target->ToCreature()->AI()->GetData(11);
     }
References Creature::AI(), UnitAI::GetData(), Object::GetEntry(), Object::GetTypeId(), NPC_MIMIRON, Object::ToCreature(), and TYPEID_UNIT.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_mimiron.cpp