Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/atomic_gcc_sync.h File Reference
atomic_gcc_sync.h File Reference
Macros
#define ATOMIC_INIT(...) {__VA_ARGS__}
#define JEMALLOC_GENERATE_ATOMICS(type, short_type, lg_size)
#define JEMALLOC_GENERATE_INT_ATOMICS(type, short_type, lg_size)
Enumerations
enum atomic_memory_order_t {
atomic_memory_order_relaxed , atomic_memory_order_acquire , atomic_memory_order_release , atomic_memory_order_acq_rel ,
atomic_memory_order_seq_cst , atomic_memory_order_relaxed , atomic_memory_order_acquire , atomic_memory_order_release ,
atomic_memory_order_acq_rel , atomic_memory_order_seq_cst , atomic_memory_order_relaxed , atomic_memory_order_acquire ,
atomic_memory_order_release , atomic_memory_order_acq_rel , atomic_memory_order_seq_cst
}
Functions
ATOMIC_INLINE void atomic_fence (atomic_memory_order_t mo)
ATOMIC_INLINE void atomic_pre_sc_load_fence ()
ATOMIC_INLINE void atomic_post_sc_store_fence ()
Macro Definition Documentation
ATOMIC_INIT
#define ATOMIC_INIT (...) {__VA_ARGS__}
Definition at line 4 of file atomic_gcc_sync.h.
JEMALLOC_GENERATE_ATOMICS
#define JEMALLOC_GENERATE_ATOMICS (type, short_type, lg_size)
Definition at line 86 of file atomic_gcc_sync.h.
JEMALLOC_GENERATE_INT_ATOMICS
#define JEMALLOC_GENERATE_INT_ATOMICS (type, short_type, lg_size)
Definition at line 158 of file atomic_gcc_sync.h.
Enumeration Type Documentation
atomic_memory_order_t
enum atomic_memory_order_t
Enumerator
atomic_memory_order_relaxed
atomic_memory_order_acquire
atomic_memory_order_release
atomic_memory_order_acq_rel
atomic_memory_order_seq_cst
atomic_memory_order_relaxed
atomic_memory_order_acquire
atomic_memory_order_release
atomic_memory_order_acq_rel
atomic_memory_order_seq_cst
atomic_memory_order_relaxed
atomic_memory_order_acquire
atomic_memory_order_release
atomic_memory_order_acq_rel
atomic_memory_order_seq_cst
Definition at line 6 of file atomic_gcc_sync.h.
              {
     atomic_memory_order_relaxed,
     atomic_memory_order_acquire,
     atomic_memory_order_release,
     atomic_memory_order_acq_rel,
     atomic_memory_order_seq_cst
 } atomic_memory_order_t;
Function Documentation
atomic_fence()
ATOMIC_INLINE void atomic_fence (atomic_memory_order_t mo)
Definition at line 15 of file atomic_gcc_sync.h.
{
     /* Easy cases first: no barrier, and full barrier. */
     if (mo == atomic_memory_order_relaxed) {
         asm volatile("" ::: "memory");
         return;
     }
     if (mo == atomic_memory_order_seq_cst) {
         asm volatile("" ::: "memory");
         __sync_synchronize();
         asm volatile("" ::: "memory");
         return;
     }
     asm volatile("" ::: "memory");
 #  if defined(__i386__) || defined(__x86_64__)
     /* This is implicit on x86. */
 #  elif defined(__ppc64__)
     asm volatile("lwsync");
 #  elif defined(__ppc__)
     asm volatile("sync");
 #  elif defined(__sparc__) && defined(__arch64__)
     if (mo == atomic_memory_order_acquire) {
         asm volatile("membar #LoadLoad | #LoadStore");
     } else if (mo == atomic_memory_order_release) {
         asm volatile("membar #LoadStore | #StoreStore");
     } else {
         asm volatile("membar #LoadLoad | #LoadStore | #StoreStore");
     }
 #  else
     __sync_synchronize();
 #  endif
     asm volatile("" ::: "memory");
 }
References atomic_memory_order_acquire, atomic_memory_order_relaxed, atomic_memory_order_release, and atomic_memory_order_seq_cst.
Referenced by atomic_post_sc_store_fence(), and atomic_pre_sc_load_fence().
atomic_post_sc_store_fence()
ATOMIC_INLINE void atomic_post_sc_store_fence ()
Definition at line 76 of file atomic_gcc_sync.h.
{
 #  if defined(__i386__) || defined(__x86_64__) ||           \
     (defined(__sparc__) && defined(__arch64__))
     atomic_fence(atomic_memory_order_seq_cst);
 #  else
     atomic_fence(atomic_memory_order_relaxed);
 #  endif
 }
References atomic_fence(), atomic_memory_order_relaxed, and atomic_memory_order_seq_cst.
atomic_pre_sc_load_fence()
ATOMIC_INLINE void atomic_pre_sc_load_fence ()
Definition at line 66 of file atomic_gcc_sync.h.
{
 #  if defined(__i386__) || defined(__x86_64__) ||           \
     (defined(__sparc__) && defined(__arch64__))
     atomic_fence(atomic_memory_order_relaxed);
 #  else
     atomic_fence(atomic_memory_order_seq_cst);
 #  endif
 }
References atomic_fence(), atomic_memory_order_relaxed, and atomic_memory_order_seq_cst.