Azerotcore-wotlk: npc_thrall_bfu::npc_thrall_bfuAI Struct Reference
npc_thrall_bfu::npc_thrall_bfuAI Struct Reference
Public Member Functions
npc_thrall_bfuAI (Creature *creature)
void EnterEvadeMode () override
void Reset () override
void JustSummoned (Creature *summoned) override
void SummonedCreatureDies (Creature *summon, Unit *) override
void UpdateWorldState (Map *map, uint32 id, uint32 state)
void SetHoldState (bool bOnHold)
void JumpToNextStep (uint32 uiTimer)
void FollowThrall ()
void ActivateValimathrasPortal ()
void SpawnWave (uint32 waveId)
void WaypointReached (uint32 waypointId) override
bool CanAIAttack (Unit const *victim) const override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from npc_escortAI
npc_escortAI (Creature *creature)
~npc_escortAI () override
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void JustDied (Unit *) override
void JustRespawned () override
void ReturnToLastPoint ()
virtual void UpdateEscortAI (uint32 diff)
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
virtual void WaypointStart (uint32)
void Start (bool isActiveAttacker=true, bool run=false, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetRun (bool on=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
bool bStepping
bool EnableAttack
uint32 step
uint32 phaseTimer
ObjectGuid sylvanasfollowGUID
ObjectGuid allianceForcesGUID [ALLIANCE_FORCE_MAXCOUNT]
ObjectGuid ValimathrasGUID
ObjectGuid ValimathrasPortalGUID
ObjectGuid WrynnGUID
ObjectGuid JainaGUID
ObjectGuid SaurfangGUID
GuidVector hordeGuardsGUID
EventMap _events
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from npc_escortAI
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 2328 of file zone_undercity.cpp.
Constructor & Destructor Documentation
npc_thrall_bfuAI()
npc_thrall_bfu::npc_thrall_bfuAI::npc_thrall_bfuAI (Creature * creature) inline
Definition at line 2330 of file zone_undercity.cpp.
                                              : npc_escortAI(creature)
         {
             hordeGuardsGUID.clear();
         }
References hordeGuardsGUID.
Member Function Documentation
ActivateValimathrasPortal()
void npc_thrall_bfu::npc_thrall_bfuAI::ActivateValimathrasPortal () inline
Definition at line 2570 of file zone_undercity.cpp.
         {
             if (Creature* portal = me->FindNearestCreature(NPC_VARIMATHRAS_PORTAL, 500.0f))
             {
                 portal->SummonCreature(NPC_LEGION_OVERLORD, ThrallSpawn[81].x + rand32() % 5, ThrallSpawn[81].y + rand32() % 5, ThrallSpawn[81].z, TEMPSUMMON_DEAD_DESPAWN);
                 portal->DespawnOrUnsummon();
             }
         }
References WorldObject::FindNearestCreature(), ScriptedAI::me, NPC_LEGION_OVERLORD, NPC_VARIMATHRAS_PORTAL, rand32(), TEMPSUMMON_DEAD_DESPAWN, ThrallSpawn, G3D::x, G3D::y, and G3D::z.
Referenced by UpdateAI().
CanAIAttack()
bool npc_thrall_bfu::npc_thrall_bfuAI::CanAIAttack (Unit const * victim) const inline override virtual
Reimplemented from UnitAI.
Definition at line 2947 of file zone_undercity.cpp.
         {
             return victim->GetEntry() != NPC_BLIGHT_SLINGER;
         }
References Object::GetEntry(), and NPC_BLIGHT_SLINGER.
EnterEvadeMode()
void npc_thrall_bfu::npc_thrall_bfuAI::EnterEvadeMode () inline override virtual
Reimplemented from npc_escortAI.
Definition at line 2352 of file zone_undercity.cpp.
         {
             me->RemoveAura(SPELL_HEROIC_VANGUARD);
             me->DeleteThreatList();
             me->CombatStop(true);
             me->SetLootRecipient(nullptr);
             if (HasEscortState(STATE_ESCORT_ESCORTING))
             {
                 AddEscortState(STATE_ESCORT_RETURNING);
                 ReturnToLastPoint();
             }
             else
             {
                 me->GetMotionMaster()->MoveTargetedHome();
                 Reset();
             }
         }
References npc_escortAI::AddEscortState(), Unit::CombatStop(), Unit::DeleteThreatList(), Unit::GetMotionMaster(), npc_escortAI::HasEscortState(), ScriptedAI::me, MotionMaster::MoveTargetedHome(), Unit::RemoveAura(), Reset(), npc_escortAI::ReturnToLastPoint(), Creature::SetLootRecipient(), SPELL_HEROIC_VANGUARD, STATE_ESCORT_ESCORTING, and STATE_ESCORT_RETURNING.
FollowThrall()
void npc_thrall_bfu::npc_thrall_bfuAI::FollowThrall () inline
Definition at line 2558 of file zone_undercity.cpp.
         {
             if (Creature* sylvanas = ObjectAccessor::GetCreature(*me, sylvanasfollowGUID))
             {
                 sylvanas->GetMotionMaster()->Clear();
                 sylvanas->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC | UNIT_FLAG_IMMUNE_TO_PC);
                 sylvanas->SetReactState(REACT_AGGRESSIVE);
                 sylvanas->SetFaction(FACTION_ESCORT_N_NEUTRAL_ACTIVE);
                 sylvanas->GetMotionMaster()->MoveFollow(me, 1, M_PI * 0.1f);
             }
         }
References FACTION_ESCORT_N_NEUTRAL_ACTIVE, ObjectAccessor::GetCreature(), M_PI, ScriptedAI::me, REACT_AGGRESSIVE, sylvanasfollowGUID, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, and UNIT_FLAG_IMMUNE_TO_PC.
Referenced by SummonedCreatureDies(), and UpdateAI().
JumpToNextStep()
void npc_thrall_bfu::npc_thrall_bfuAI::JumpToNextStep (uint32 uiTimer) inline
Definition at line 2552 of file zone_undercity.cpp.
         {
             phaseTimer = uiTimer;
             ++step;
         }
References phaseTimer, and step.
Referenced by UpdateAI().
JustSummoned()
void npc_thrall_bfu::npc_thrall_bfuAI::JustSummoned (Creature * summoned) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 2431 of file zone_undercity.cpp.
         {
             switch (summoned->GetEntry())
             {
                 case NPC_BLIGHT_ABBERATION:
                     summoned->AI()->AttackStart(me);
                     break;
                 case NPC_WARSONG_BATTLEGUARD:
                     summoned->ApplySpellImmune(0, IMMUNITY_ID, SPELL_SYLVANAS_BUFF, true);
                     summoned->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_READY2H);
                     break;
                 case NPC_VARIMATHRAS_PORTAL:
                     summoned->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                     summoned->ApplySpellImmune(0, IMMUNITY_ID, SPELL_THRALL_BUFF, true);
                     summoned->ApplySpellImmune(0, IMMUNITY_ID, SPELL_SYLVANAS_BUFF, true);
                     break;
                 case NPC_CAVE_DUMMY:
                     summoned->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                     summoned->ApplySpellImmune(0, IMMUNITY_ID, SPELL_THRALL_BUFF, true);
                     summoned->ApplySpellImmune(0, IMMUNITY_ID, SPELL_SYLVANAS_BUFF, true);
                     summoned->AddAura(SPELL_CYCLONE_FALL, summoned);
                     break;
                 case NPC_TREACHEROUS_GUARDIAN_H:
                 case NPC_DOCTOR_H:
                 case NPC_CHEMIST_H:
                     summoned->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_KNOCK_BACK, true);
                     summoned->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_KNOCK_BACK_DEST, true);
                     summoned->ApplySpellImmune(0, IMMUNITY_ID, SPELL_THRALL_BUFF, true);
                     summoned->ApplySpellImmune(0, IMMUNITY_ID, SPELL_SYLVANAS_BUFF, true);
                     if (!EnableAttack)
                         summoned->SetFaction(FACTION_FRIENDLY);
                     summoned->AddThreat(me, 100.0f);
                     me->AddThreat(summoned, 100.0f);
                     summoned->AI()->AttackStart(me);
                     break;
                 case NPC_LEGION_INVADER:
                 case NPC_LEGION_DREADWHISPER:
                 case NPC_FELGUARD_MORADEUR:
                 case NPC_DREADLORD:
                 case NPC_BETRAYER_H:
                 case NPC_FELBEAST_H:
                     summoned->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_KNOCK_BACK, true);
                     summoned->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_KNOCK_BACK_DEST, true);
                     summoned->AddThreat(me, 100.0f);
                     me->AddThreat(summoned, 100.0f);
                     summoned->AI()->AttackStart(me);
                     break;
                 default:
                     break;
             }
         }
References Unit::AddAura(), Unit::AddThreat(), Creature::AI(), Unit::ApplySpellImmune(), UnitAI::AttackStart(), EMOTE_STATE_READY2H, EnableAttack, FACTION_FRIENDLY, Object::GetEntry(), IMMUNITY_EFFECT, IMMUNITY_ID, ScriptedAI::me, NPC_BETRAYER_H, NPC_BLIGHT_ABBERATION, NPC_CAVE_DUMMY, NPC_CHEMIST_H, NPC_DOCTOR_H, NPC_DREADLORD, NPC_FELBEAST_H, NPC_FELGUARD_MORADEUR, NPC_LEGION_DREADWHISPER, NPC_LEGION_INVADER, NPC_TREACHEROUS_GUARDIAN_H, NPC_VARIMATHRAS_PORTAL, NPC_WARSONG_BATTLEGUARD, Unit::SetFaction(), Object::SetFlag(), Object::SetUInt32Value(), SPELL_CYCLONE_FALL, SPELL_EFFECT_KNOCK_BACK, SPELL_EFFECT_KNOCK_BACK_DEST, SPELL_SYLVANAS_BUFF, SPELL_THRALL_BUFF, UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE, and UNIT_NPC_EMOTESTATE.
Reset()
void npc_thrall_bfu::npc_thrall_bfuAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 2371 of file zone_undercity.cpp.
         {
             if (!HasEscortState(STATE_ESCORT_ESCORTING))
             {
                 me->SetStandState(UNIT_STAND_STATE_STAND);
                 me->Mount(MODEL_WHITE_WULF);
                 me->SetCorpseDelay(1);
                 me->SetRespawnTime(1);
                 me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
                 me->ApplySpellImmune(0, IMMUNITY_ID, SPELL_SYLVANAS_BUFF, true);
                 bStepping = false;
                 EnableAttack = false;
                 step = 0;
                 phaseTimer = 0;
                 sylvanasfollowGUID.Clear();
                 _events.ScheduleEvent(EVENT_CHAIN_LIGHTNING, 3 * IN_MILLISECONDS);
                 _events.ScheduleEvent(EVENT_LAVA_BURST, 5 * IN_MILLISECONDS);
                 _events.ScheduleEvent(EVENT_THUNDER, 8 * IN_MILLISECONDS);
                 _events.ScheduleEvent(EVENT_AGGRO_SYLVANAS, 2 * IN_MILLISECONDS);
                 _events.ScheduleEvent(EVENT_THRALL_BUFF, 2 * IN_MILLISECONDS);
                 if (Creature* valimathras = ObjectAccessor::GetCreature(*me, ValimathrasGUID))
                 {
                     valimathras->DespawnOrUnsummon();
                     ValimathrasGUID.Clear();
                 }
                 if (Creature* valimathrasportal = ObjectAccessor::GetCreature(*me, ValimathrasPortalGUID))
                 {
                     valimathrasportal->DespawnOrUnsummon();
                     ValimathrasPortalGUID.Clear();
                 }
                 if (Creature* wrynn = ObjectAccessor::GetCreature(*me, WrynnGUID))
                 {
                     wrynn->DespawnOrUnsummon();
                     WrynnGUID.Clear();
                 }
                 if (Creature* jaina = ObjectAccessor::GetCreature(*me, JainaGUID))
                 {
                     jaina->DespawnOrUnsummon();
                     JainaGUID.Clear();
                 }
                 if (Creature* saurfang = ObjectAccessor::GetCreature(*me, SaurfangGUID))
                 {
                     saurfang->DespawnOrUnsummon();
                     SaurfangGUID.Clear();
                 }
                 for (ObjectGuid const& guid : hordeGuardsGUID)
                     if (Creature* temp = ObjectAccessor::GetCreature(*me, guid))
                         temp->DespawnOrUnsummon();
                 hordeGuardsGUID.clear();
             }
         }
References _events, Unit::ApplySpellImmune(), bStepping, ObjectGuid::Clear(), EnableAttack, EVENT_AGGRO_SYLVANAS, EVENT_CHAIN_LIGHTNING, EVENT_LAVA_BURST, EVENT_THRALL_BUFF, EVENT_THUNDER, ObjectAccessor::GetCreature(), npc_escortAI::HasEscortState(), hordeGuardsGUID, IMMUNITY_ID, IN_MILLISECONDS, JainaGUID, ScriptedAI::me, MODEL_WHITE_WULF, Unit::Mount(), phaseTimer, SaurfangGUID, EventMap::ScheduleEvent(), Creature::SetCorpseDelay(), Object::SetFlag(), Creature::SetRespawnTime(), Unit::SetStandState(), SPELL_SYLVANAS_BUFF, STATE_ESCORT_ESCORTING, step, sylvanasfollowGUID, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAGS, UNIT_STAND_STATE_STAND, ValimathrasGUID, ValimathrasPortalGUID, and WrynnGUID.
Referenced by EnterEvadeMode().
SetHoldState()
void npc_thrall_bfu::npc_thrall_bfuAI::SetHoldState (bool bOnHold) inline
Definition at line 2547 of file zone_undercity.cpp.
         {
             SetEscortPaused(bOnHold);
         }
References npc_escortAI::SetEscortPaused().
Referenced by WaypointReached().
SpawnWave()
void npc_thrall_bfu::npc_thrall_bfuAI::SpawnWave (uint32 waveId) inline
Definition at line 2579 of file zone_undercity.cpp.
         {
             switch (waveId)
             {
                 case 0: // Vortex
                     if (Creature* whirlwind1 = me->SummonCreature(NPC_VORTEX, ThrallSpawn[0].x, ThrallSpawn[0].y, ThrallSpawn[0].z, ThrallSpawn[0].o, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 30 * IN_MILLISECONDS))
                         whirlwind1->GetMotionMaster()->MovePath(NPC_WHIRLWIND * 10, false);
                     if (Creature* whirlwind2 = me->SummonCreature(NPC_VORTEX, ThrallSpawn[0].x, ThrallSpawn[0].y, ThrallSpawn[0].z, ThrallSpawn[0].o, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 30 * IN_MILLISECONDS))
                         whirlwind2->GetMotionMaster()->MovePath(NPC_WHIRLWIND * 100, false);
                     break;
                 case 1:
                     // BATTLING_COURTYARD Initial Spawn
                     for (uint8 i = 0; i < 3; ++i)
                         me->SummonCreature(NPC_DOCTOR_H, ThrallSpawn[i + 1].x, ThrallSpawn[i + 1].y, ThrallSpawn[i + 1].z, ThrallSpawn[i + 1].o, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 300 * IN_MILLISECONDS);
                     for (uint8 i = 0; i < 9; ++i)
                         me->SummonCreature(NPC_CHEMIST_H, ThrallSpawn[i + 4].x, ThrallSpawn[i + 4].y, ThrallSpawn[i + 4].z, ThrallSpawn[i + 4].o, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 300 * IN_MILLISECONDS);
                     for (uint8 i = 0; i < 6; ++i)
                         me->SummonCreature(NPC_TREACHEROUS_GUARDIAN_H, ThrallSpawn[i + 13].x, ThrallSpawn[i + 13].y, ThrallSpawn[i + 14].z, ThrallSpawn[i + 14].o, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 300 * IN_MILLISECONDS);
                     for (uint8 i = 0; i < 4; ++i)
                         me->SummonCreature(NPC_BLIGHT_SLINGER, ThrallSpawn[i + 19].x, ThrallSpawn[i + 19].y, ThrallSpawn[i + 19].z, ThrallSpawn[i + 19].o, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 900 * IN_MILLISECONDS);
                     break;
                 case 2:
                     // Valimathras
                     if (Unit* temp = me->SummonCreature(NPC_VARIMATHRAS, ThrallSpawn[23].x, ThrallSpawn[23].y, ThrallSpawn[23].z, ThrallSpawn[23].o, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 900 * IN_MILLISECONDS))
                     {
                         ValimathrasGUID = temp->GetGUID();
                         temp->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC | UNIT_FLAG_IMMUNE_TO_PC);
                     }
                     break;
                 case 3:
                     if (Unit* temp = me->SummonCreature(NPC_VARIMATHRAS_PORTAL, ThrallSpawn[24].x, ThrallSpawn[24].y, ThrallSpawn[24].z, ThrallSpawn[24].o, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 900 * IN_MILLISECONDS))
                         ValimathrasPortalGUID = temp->GetGUID();
                     break;
                 case 4:
                     // COURTYARD_FIGHT Spawns
                     for (uint8 i = 0; i < WAVE_COURTYARD_FIGHT; ++i)
                     {
                         switch (urand(0, 2))
{
                             case 0:
                                 me->SummonCreature(NPC_TREACHEROUS_GUARDIAN_H, ThrallSpawn[25].x + rand32() % 5, ThrallSpawn[25].y + rand32() % 5, ThrallSpawn[25].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                             case 1:
                                 me->SummonCreature(NPC_DOCTOR_H, ThrallSpawn[26].x + rand32() % 5, ThrallSpawn[26].y + rand32() % 5, ThrallSpawn[26].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                             case 2:
                                 me->SummonCreature(NPC_CHEMIST_H, ThrallSpawn[27].x + rand32() % 5, ThrallSpawn[27].y + rand32() % 5, ThrallSpawn[27].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                         }
                     }
                     break;
                 case 5:
                     // Bossspawn 1
                     if (Creature* temp = me->SummonCreature(NPC_BLIGHT_ABBERATION, ThrallSpawn[28].x, ThrallSpawn[28].y, ThrallSpawn[28].z, ThrallSpawn[28].o, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 900 * IN_MILLISECONDS))
                     {
                         temp->GetMotionMaster()->MoveJump(ThrallSpawn[62].x, ThrallSpawn[62].y, ThrallSpawn[62].z, 10.0f, 20.0f, 0);
                         temp->AddThreat(me, 100.0f);
                         me->AddThreat(temp, 100.0f);
                         temp->AI()->AttackStart(me);
                     }
                     break;
                 case 6:
                     // COURTYARD_DONE Spawn
                     if (Unit* temp = me->SummonCreature(NPC_WARSONG_BATTLEGUARD, ThrallSpawn[29].x, ThrallSpawn[29].y, ThrallSpawn[29].z, ThrallSpawn[29].o, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 300 * IN_MILLISECONDS))
                     {
                         hordeGuardsGUID.push_back(temp->GetGUID());
                         temp->GetMotionMaster()->MovePoint(0, ThrallSpawn[30].x, ThrallSpawn[30].y, ThrallSpawn[30].z);
                     }
                     if (Unit* temp = me->SummonCreature(NPC_WARSONG_BATTLEGUARD, ThrallSpawn[31].x, ThrallSpawn[31].y, ThrallSpawn[31].z, ThrallSpawn[31].o, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 300 * IN_MILLISECONDS))
                     {
                         hordeGuardsGUID.push_back(temp->GetGUID());
                         temp->GetMotionMaster()->MovePoint(0, ThrallSpawn[32].x, ThrallSpawn[32].y, ThrallSpawn[32].z);
                     }
                     if (Unit* temp = me->SummonCreature(NPC_WARSONG_BATTLEGUARD, ThrallSpawn[33].x, ThrallSpawn[33].y, ThrallSpawn[33].z, ThrallSpawn[33].o, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 300 * IN_MILLISECONDS))
                     {
                         hordeGuardsGUID.push_back(temp->GetGUID());
                         temp->GetMotionMaster()->MovePoint(0, ThrallSpawn[34].x, ThrallSpawn[34].y, ThrallSpawn[34].z);
                     }
                     if (Unit* temp = me->SummonCreature(NPC_WARSONG_BATTLEGUARD, ThrallSpawn[35].x, ThrallSpawn[35].y, ThrallSpawn[35].z, ThrallSpawn[35].o, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 300 * IN_MILLISECONDS))
                     {
                         hordeGuardsGUID.push_back(temp->GetGUID());
                         temp->GetMotionMaster()->MovePoint(0, ThrallSpawn[36].x, ThrallSpawn[36].y, ThrallSpawn[36].z);
                     }
                     for (uint8 i = 0; i < 2; ++i)
                         if (Unit* temp = me->SummonCreature(NPC_WARSONG_BATTLEGUARD, ThrallSpawn[i + 44].x, ThrallSpawn[i + 44].y, ThrallSpawn[i + 44].z, ThrallSpawn[i + 44].o, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 300 * IN_MILLISECONDS))
                             hordeGuardsGUID.push_back(temp->GetGUID());
                     break;
                 case 7:
                     for (uint8 i = 0; i < 9; ++i)
                         me->SummonCreature(NPC_CAVE_DUMMY, ThrallSpawn[i + 46].x, ThrallSpawn[i + 46].y, ThrallSpawn[i + 46].z, ThrallSpawn[i + 46].o, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 600 * IN_MILLISECONDS);
                     break;
                 case 8:
                     for (uint8 i = 0; i < 2; ++i)
                         if (Unit* temp = me->SummonCreature(NPC_WARSONG_BATTLEGUARD, ThrallSpawn[i + 57].x, ThrallSpawn[i + 57].y, ThrallSpawn[i + 57].z, ThrallSpawn[i + 57].o, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 300 * IN_MILLISECONDS))
                             hordeGuardsGUID.push_back(temp->GetGUID());
                     break;
                 case 9:
                     // Top of Undercity - Attacktrashpack
                     for (uint8 i = 0; i < 3; ++i)
                     {
                         switch (urand(0, 2))
{
                             case 0:
                                 me->SummonCreature(NPC_TREACHEROUS_GUARDIAN_H, ThrallSpawn[59].x + rand32() % 2, ThrallSpawn[59].y + rand32() % 2, ThrallSpawn[59].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                             case 1:
                                 me->SummonCreature(NPC_DOCTOR_H, ThrallSpawn[59].x + rand32() % 2, ThrallSpawn[59].y + rand32() % 2, ThrallSpawn[59].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                             case 2:
                                 me->SummonCreature(NPC_CHEMIST_H, ThrallSpawn[59].x + rand32() % 2, ThrallSpawn[59].y + rand32() % 2, ThrallSpawn[59].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                         }
                     }
                     break;
                 case 10:
                     // Top of Undercity - Attacktrashpack
                     for (uint8 i = 0; i < 3; ++i)
                     {
                         switch (urand(0, 1))
{
                             case 0:
                                 me->SummonCreature(NPC_TREACHEROUS_GUARDIAN_H, ThrallSpawn[60].x + rand32() % 5, ThrallSpawn[60].y + rand32() % 5, ThrallSpawn[60].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                             case 1:
                                 me->SummonCreature(NPC_FELGUARD_MORADEUR, ThrallSpawn[60].x + rand32() % 5, ThrallSpawn[60].y + rand32() % 5, ThrallSpawn[60].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                         }
                     }
                     break;
                 case 11:
                     // Bottom of Undercity - Attacktrashpack
                     for (uint8 i = 0; i < 3; ++i)
                     {
                         switch (urand(0, 1))
{
                             case 0:
                                 me->SummonCreature(NPC_FELGUARD_MORADEUR, ThrallSpawn[61].x + rand32() % 5, ThrallSpawn[61].y + rand32() % 5, ThrallSpawn[61].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                             case 1:
                                 me->SummonCreature(NPC_DREADLORD, ThrallSpawn[61].x + rand32() % 5, ThrallSpawn[61].y + rand32() % 5, ThrallSpawn[61].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                         }
                     }
                     break;
                 case 12:
                     // Valimathras 2
                     if (Unit* temp = me->SummonCreature(NPC_VARIMATHRAS, ThrallSpawn[63].x, ThrallSpawn[63].y, ThrallSpawn[63].z, ThrallSpawn[63].o, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 300 * IN_MILLISECONDS))
                     {
                         ValimathrasGUID = temp->GetGUID();
                         temp->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC | UNIT_FLAG_IMMUNE_TO_PC);
                     }
                     break;
                 case 13:
                     if (Unit* temp = me->SummonCreature(NPC_VARIMATHRAS_PORTAL, ThrallSpawn[64].x, ThrallSpawn[64].y, ThrallSpawn[64].z, ThrallSpawn[64].o, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 900 * IN_MILLISECONDS))
                         ValimathrasPortalGUID = temp->GetGUID();
                     break;
                 // NPC_KHANOK - Inner Sunktum Spawn Left
                 case 14:
                     for (uint8 i = 0; i < 4; ++i)
                     {
                         switch (urand(0, 6))
{
                             case 0:
                                 me->SummonCreature(NPC_FELGUARD_MORADEUR, ThrallSpawn[65].x + rand32() % 5, ThrallSpawn[65].y + rand32() % 5, ThrallSpawn[65].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                             case 1:
                                 me->SummonCreature(NPC_DREADLORD, ThrallSpawn[65].x + rand32() % 5, ThrallSpawn[65].y + rand32() % 5, ThrallSpawn[65].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                             case 2:
                                 me->SummonCreature(NPC_TREACHEROUS_GUARDIAN_H, ThrallSpawn[65].x + rand32() % 5, ThrallSpawn[65].y + rand32() % 5, ThrallSpawn[65].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                             case 3:
                                 me->SummonCreature(NPC_DOCTOR_H, ThrallSpawn[65].x + rand32() % 5, ThrallSpawn[65].y + rand32() % 5, ThrallSpawn[65].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                             case 4:
                                 me->SummonCreature(NPC_CHEMIST_H, ThrallSpawn[65].x + rand32() % 5, ThrallSpawn[65].y + rand32() % 5, ThrallSpawn[65].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                             case 5:
                                 me->SummonCreature(NPC_BETRAYER_H, ThrallSpawn[65].x + rand32() % 5, ThrallSpawn[65].y + rand32() % 5, ThrallSpawn[65].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                             case 6:
                                 me->SummonCreature(NPC_FELBEAST_H, ThrallSpawn[65].x + rand32() % 5, ThrallSpawn[65].y + rand32() % 5, ThrallSpawn[65].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                         }
                     }
                     break;
                 // NPC_KHANOK - Inner Sunktum Spawn Right
                 case 15:
                     for (uint8 i = 0; i < 4; ++i)
                     {
                         switch (urand(0, 6))
{
                             case 0:
                                 me->SummonCreature(NPC_FELGUARD_MORADEUR, ThrallSpawn[66].x + rand32() % 5, ThrallSpawn[66].y + rand32() % 5, ThrallSpawn[66].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                             case 1:
                                 me->SummonCreature(NPC_DREADLORD, ThrallSpawn[66].x + rand32() % 5, ThrallSpawn[66].y + rand32() % 5, ThrallSpawn[66].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                             case 2:
                                 me->SummonCreature(NPC_TREACHEROUS_GUARDIAN_H, ThrallSpawn[66].x + rand32() % 5, ThrallSpawn[66].y + rand32() % 5, ThrallSpawn[66].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                             case 3:
                                 me->SummonCreature(NPC_DOCTOR_H, ThrallSpawn[66].x + rand32() % 5, ThrallSpawn[66].y + rand32() % 5, ThrallSpawn[66].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                             case 4:
                                 me->SummonCreature(NPC_CHEMIST_H, ThrallSpawn[66].x + rand32() % 5, ThrallSpawn[66].y + rand32() % 5, ThrallSpawn[66].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                             case 5:
                                 me->SummonCreature(NPC_BETRAYER_H, ThrallSpawn[66].x + rand32() % 5, ThrallSpawn[66].y + rand32() % 5, ThrallSpawn[66].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                             case 6:
                                 me->SummonCreature(NPC_FELBEAST_H, ThrallSpawn[66].x + rand32() % 5, ThrallSpawn[66].y + rand32() % 5, ThrallSpawn[66].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                         }
                     }
                     break;
                 // NPC_KHANOK - Inner Sunktum Spawn Top
                 case 16:
                     me->SummonCreature(NPC_DOOMGUARD_PILLARGER, ThrallSpawn[67].x + rand32() % 15, ThrallSpawn[67].y + rand32() % 15, ThrallSpawn[67].z + rand32() % 5, TEMPSUMMON_DEAD_DESPAWN);
                     break;
                 // NPC_KHANOK - Inner Sunktum Spawn Middle
                 case 17:
                     me->SummonCreature(NPC_KHANOK, ThrallSpawn[68].x, ThrallSpawn[68].y, ThrallSpawn[68].z, TEMPSUMMON_DEAD_DESPAWN);
                     break;
                 case 18:
                     if (Creature* temp = me->SummonCreature(NPC_WARSONG_BATTLEGUARD, ThrallSpawn[69].x, ThrallSpawn[69].y, ThrallSpawn[69].z, ThrallSpawn[69].o, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 240 * IN_MILLISECONDS))
                     {
                         hordeGuardsGUID.push_back(temp->GetGUID());
                         temp->AI()->Talk(SAY_FOR_THE_HORDE);
                         temp->GetMotionMaster()->MovePath(NPC_WARSONG_BATTLEGUARD * 100, false);
                     }
                     break;
                 // Valimathras Room Preparation
                 case 19:
                     for (uint8 i = 0; i < 3; ++i)
                         me->SummonGameObject(GO_BLOCKED_PASSAGE, ThrallSpawn[i + 70].x, ThrallSpawn[i + 70].y, ThrallSpawn[70].z, ThrallSpawn[i + 70].o, 0.0f, 0.0f, 0.0f, 0.0f, 120 * IN_MILLISECONDS);
                     // Valimathras BossSpawn
                     if (Creature* temp = me->SummonCreature(NPC_VARIMATHRAS, ThrallSpawn[73].x, ThrallSpawn[73].y, ThrallSpawn[73].z, ThrallSpawn[73].o, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 1200 * IN_MILLISECONDS))
                     {
                         ValimathrasGUID = temp->GetGUID();
                         temp->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC | UNIT_FLAG_IMMUNE_TO_PC);
                         temp->CastSpell(me, SPELL_AURA_OF_VARIMATHRAS);
                         temp->CastSpell(me, SPELL_OPENING_LEGION_PORTALS);
                         temp->AI()->Talk(SAY_CLOSE_DOOR);
                     }
                     for (uint8 i = 0; i < 6; ++i)
                     {
                         if (Unit* temp = me->SummonCreature(NPC_VARIMATHRAS_PORTAL, ThrallSpawn[i + 74].x, ThrallSpawn[i + 74].y, ThrallSpawn[i + 74].z, TEMPSUMMON_MANUAL_DESPAWN))
                             temp->CastSpell(me, SPELL_VALIMATHRAS_PORTAL);
                     }
                     break;
                 case 20:
                     for (uint8 i = 0; i < 3; ++i)
                     {
                         switch (urand(0, 1))
{
                             case 0:
                                 me->SummonCreature(NPC_LEGION_INVADER, ThrallSpawn[80].x + rand32() % 5, ThrallSpawn[80].y + rand32() % 5, ThrallSpawn[80].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                             case 1:
                                 me->SummonCreature(NPC_LEGION_DREADWHISPER, ThrallSpawn[81].x + rand32() % 5, ThrallSpawn[81].y + rand32() % 5, ThrallSpawn[81].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                         }
                     }
                     break;
                 case 21:
                     for (uint8 i = 0; i < 3; ++i)
                     {
                         switch (urand(0, 1))
{
                             case 0:
                                 me->SummonCreature(NPC_LEGION_INVADER, ThrallSpawn[81].x + rand32() % 5, ThrallSpawn[81].y + rand32() % 5, ThrallSpawn[81].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                             case 1:
                                 me->SummonCreature(NPC_LEGION_DREADWHISPER, ThrallSpawn[80].x + rand32() % 5, ThrallSpawn[80].y + rand32() % 5, ThrallSpawn[80].z, TEMPSUMMON_DEAD_DESPAWN);
                                 break;
                         }
                     }
                     break;
             }
         }
References Unit::AddThreat(), Unit::GetMotionMaster(), GO_BLOCKED_PASSAGE, hordeGuardsGUID, IN_MILLISECONDS, ScriptedAI::me, MotionMaster::MoveJump(), NPC_BETRAYER_H, NPC_BLIGHT_ABBERATION, NPC_BLIGHT_SLINGER, NPC_CAVE_DUMMY, NPC_CHEMIST_H, NPC_DOCTOR_H, NPC_DOOMGUARD_PILLARGER, NPC_DREADLORD, NPC_FELBEAST_H, NPC_FELGUARD_MORADEUR, NPC_KHANOK, NPC_LEGION_DREADWHISPER, NPC_LEGION_INVADER, NPC_TREACHEROUS_GUARDIAN_H, NPC_VARIMATHRAS, NPC_VARIMATHRAS_PORTAL, NPC_VORTEX, NPC_WARSONG_BATTLEGUARD, NPC_WHIRLWIND, Location::o, rand32(), SAY_CLOSE_DOOR, SAY_FOR_THE_HORDE, SPELL_AURA_OF_VARIMATHRAS, SPELL_OPENING_LEGION_PORTALS, SPELL_VALIMATHRAS_PORTAL, WorldObject::SummonCreature(), WorldObject::SummonGameObject(), TEMPSUMMON_DEAD_DESPAWN, TEMPSUMMON_MANUAL_DESPAWN, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, ThrallSpawn, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, urand(), ValimathrasGUID, ValimathrasPortalGUID, WAVE_COURTYARD_FIGHT, G3D::x, Location::x, G3D::y, Location::y, G3D::z, and Location::z.
Referenced by UpdateAI().
SummonedCreatureDies()
void npc_thrall_bfu::npc_thrall_bfuAI::SummonedCreatureDies (Creature * summon, Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 2483 of file zone_undercity.cpp.
         {
             switch (summon->GetEntry())
             {
                 case NPC_BLIGHT_ABBERATION:
                     UpdateWorldState(me->GetMap(), WORLD_STATE_COURTYARD_FIGHT_H, 0);
                     UpdateWorldState(me->GetMap(), WORLD_STATE_COURTYARD_DONE_H, 1);
                     bStepping = true;
                     break;
                 case NPC_KHANOK:
                     {
                         UpdateWorldState(me->GetMap(), WORLD_STATE_INNER_SANKTUM_FIGHT_H, 0);
                         UpdateWorldState(me->GetMap(), WORLD_STATE_INNER_SANKTUM_DONE_H, 1);
                         FollowThrall();
                         SetEscortPaused(false);
                         std::list<Creature*> SanktumList;
                         me->GetCreatureListWithEntryInGrid(SanktumList, NPC_FELGUARD_MORADEUR, 1000.0f);
                         me->GetCreatureListWithEntryInGrid(SanktumList, NPC_DREADLORD, 1000.0f);
                         me->GetCreatureListWithEntryInGrid(SanktumList, NPC_TREACHEROUS_GUARDIAN_H, 1000.0f);
                         me->GetCreatureListWithEntryInGrid(SanktumList, NPC_DOCTOR_H, 1000.0f);
                         me->GetCreatureListWithEntryInGrid(SanktumList, NPC_CHEMIST_H, 1000.0f);
                         me->GetCreatureListWithEntryInGrid(SanktumList, NPC_BETRAYER_H, 1000.0f);
                         me->GetCreatureListWithEntryInGrid(SanktumList, NPC_FELBEAST_H, 1000.0f);
                         me->GetCreatureListWithEntryInGrid(SanktumList, NPC_DOOMGUARD_PILLARGER, 1000.0f);
                         if (!SanktumList.empty())
                             for (std::list<Creature*>::iterator itr = SanktumList.begin(); itr != SanktumList.end(); itr++)
                                 (*itr)->DespawnOrUnsummon();
                         break;
                     }
                 case NPC_VARIMATHRAS:
                     {
                         UpdateWorldState(me->GetMap(), WORLD_STATE_ROYAL_QUARTER_FIGHT_H, 0);
                         UpdateWorldState(me->GetMap(), WORLD_STATE_ROYAL_QUARTER_DONE_H, 1);
                         std::list<Creature*> ThroneList;
                         me->GetCreatureListWithEntryInGrid(ThroneList, NPC_LEGION_OVERLORD, 1000.0f);
                         me->GetCreatureListWithEntryInGrid(ThroneList, NPC_LEGION_INVADER, 1000.0f);
                         me->GetCreatureListWithEntryInGrid(ThroneList, NPC_LEGION_DREADWHISPER, 1000.0f);
                         me->GetCreatureListWithEntryInGrid(ThroneList, NPC_VARIMATHRAS_PORTAL, 1000.0f);
                         if (!ThroneList.empty())
                             for (std::list<Creature*>::iterator itr = ThroneList.begin(); itr != ThroneList.end(); itr++)
                                 (*itr)->DespawnOrUnsummon();
                         SetEscortPaused(false);
                         SetRun(false);
                         break;
                     }
                 default:
                     break;
             }
         }
References bStepping, FollowThrall(), WorldObject::GetCreatureListWithEntryInGrid(), Object::GetEntry(), WorldObject::GetMap(), ScriptedAI::me, NPC_BETRAYER_H, NPC_BLIGHT_ABBERATION, NPC_CHEMIST_H, NPC_DOCTOR_H, NPC_DOOMGUARD_PILLARGER, NPC_DREADLORD, NPC_FELBEAST_H, NPC_FELGUARD_MORADEUR, NPC_KHANOK, NPC_LEGION_DREADWHISPER, NPC_LEGION_INVADER, NPC_LEGION_OVERLORD, NPC_TREACHEROUS_GUARDIAN_H, NPC_VARIMATHRAS, NPC_VARIMATHRAS_PORTAL, npc_escortAI::SetEscortPaused(), npc_escortAI::SetRun(), UpdateWorldState(), WORLD_STATE_COURTYARD_DONE_H, WORLD_STATE_COURTYARD_FIGHT_H, WORLD_STATE_INNER_SANKTUM_DONE_H, WORLD_STATE_INNER_SANKTUM_FIGHT_H, WORLD_STATE_ROYAL_QUARTER_DONE_H, and WORLD_STATE_ROYAL_QUARTER_FIGHT_H.
UpdateAI()
void npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 2952 of file zone_undercity.cpp.
         {
             npc_escortAI::UpdateAI(diff);
             if (bStepping)
             {
                 if (phaseTimer <= diff)
                 {
                     switch (step)
                     {
                         //Preparation
                         case 0:
                             me->setActive(true);
                             JumpToNextStep(3 * IN_MILLISECONDS);
                             break;
                         case 1:
                             UpdateWorldState(me->GetMap(), WORLD_STATE_BATTLE_COUNTDOWN_H, 1);
                             Talk(THRALL_SAY_PREP_1);
                             JumpToNextStep(6 * IN_MILLISECONDS);
                             break;
                         case 2:
                             Talk(THRALL_SAY_PREP_2);
                             JumpToNextStep(14 * IN_MILLISECONDS);
                             break;
                         case 3:
                             if (Creature* guard = me->FindNearestCreature(NPC_HORDE_GUARD, 100.0f))
                                 guard->AI()->Talk(SAY_BURN_UC);
                             JumpToNextStep(19 * IN_MILLISECONDS);
                             break;
                         case 4:
                             if (Creature* guard = me->FindNearestCreature(NPC_HORDE_GUARD, 100.0f))
                                 guard->AI()->Talk(SAY_PUTRESS_ANGER);
                             JumpToNextStep(25 * IN_MILLISECONDS);
                             break;
                         case 5:
                             Talk(THRALL_SAY_PREP_3);
                             JumpToNextStep(14 * IN_MILLISECONDS);
                             break;
                         case 6:
                             Talk(THRALL_SAY_PREP_4);
                             JumpToNextStep(14 * IN_MILLISECONDS);
                             break;
                         case 7:
                             Talk(THRALL_SAY_PREP_5);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 8:
                             Talk(THRALL_SAY_PREP_6);
                             JumpToNextStep(15 * IN_MILLISECONDS);
                             break;
                         case 9:
                             Talk(THRALL_SAY_PREP_7);
                             JumpToNextStep(6 * IN_MILLISECONDS);
                             break;
                         case 10:
                             DoCast(me, SPELL_THRALL_BUFF);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         // Start Event
                         case 11:
                             UpdateWorldState(me->GetMap(), WORLD_STATE_BATTLE_COUNTDOWN_H, 0);
                             UpdateWorldState(me->GetMap(), WORLD_STATE_BATTLE_START_H, 1);
                             Talk(THRALL_SAY_PREP_8);
                             SetEscortPaused(false);
                             bStepping = false;
                             JumpToNextStep(0);
                             SetRun(true);
                             if (Creature* sylvanas = ObjectAccessor::GetCreature(*me, sylvanasfollowGUID))
{
                                 sylvanas->GetMotionMaster()->MovePath(NPC_SYLVANAS * 100, false);
                                 sylvanas->setActive(true);
                             }
                             break;
                         case 12:
                             me->Dismount();
                             JumpToNextStep(1 * IN_MILLISECONDS);
                             break;
                         case 13:
                             if (Creature* sylvanas = ObjectAccessor::GetCreature(*me, sylvanasfollowGUID))
                                 sylvanas->Dismount();
                             JumpToNextStep(3 * IN_MILLISECONDS);
                             break;
                         case 14:
                             Talk(THRALL_SAY_COURTYARD_1);
                             JumpToNextStep(4 * IN_MILLISECONDS);
                             break;
                         case 15:
                             me->CastSpell(me, SPELL_CALL_OF_AIR);
                             SpawnWave(0);
                             JumpToNextStep(5 * IN_MILLISECONDS);
                             break;
                         case 16:
{
                                 std::list<Creature*> PlagueList;
                                 me->GetCreatureListWithEntryInGrid(PlagueList, NPC_PLAGUE_TRIGGER, 50.0f);
                                 if (!PlagueList.empty())
                                     for (std::list<Creature*>::iterator itr = PlagueList.begin(); itr != PlagueList.end(); itr++)
                                         (*itr)->DespawnOrUnsummon();
                                 SetEscortPaused(false);
                                 SetRun(false);
                                 if (Creature* sylvanas = ObjectAccessor::GetCreature(*me, sylvanasfollowGUID))
                                     sylvanas->GetMotionMaster()->MovePath(NPC_SYLVANAS * 1000, false);
                                 JumpToNextStep(3 * IN_MILLISECONDS);
                                 break;
                             }
                         case 17:
                             bStepping = false;
                             JumpToNextStep(0);
                             break;
                         case 18:
                             SpawnWave(1);
                             Talk(THRALL_SAY_COURTYARD_2);
                             JumpToNextStep(6 * IN_MILLISECONDS);
                             break;
                         case 19:
{
                                 SpawnWave(2);
                                 JumpToNextStep(3 * IN_MILLISECONDS);
                                 break;
                             }
                         case 20:
                             if (Creature* valimathras = ObjectAccessor::GetCreature(*me, ValimathrasGUID))
                                 valimathras->AI()->Talk(SAY_VALIMATHRAS_INTRO_0);
                             JumpToNextStep(5 * IN_MILLISECONDS);
                             break;
                         case 21:
                             if (Creature* valimathras = ObjectAccessor::GetCreature(*me, ValimathrasGUID))
                                 valimathras->AI()->Talk(SAY_VALIMATHRAS_INTRO_1);
                             JumpToNextStep(9 * IN_MILLISECONDS);
                             break;
                         case 22:
                             if (Creature* valimathras = ObjectAccessor::GetCreature(*me, ValimathrasGUID))
                                 valimathras->AI()->Talk(SAY_VALIMATHRAS_INTRO_2);
                             JumpToNextStep(7 * IN_MILLISECONDS);
                             break;
                         case 23:
                             SpawnWave(3);
                             JumpToNextStep(1 * IN_MILLISECONDS);
                             break;
                         case 24:
                             if (Creature* valimathrasportal = ObjectAccessor::GetCreature(*me, ValimathrasPortalGUID))
                                 valimathrasportal->CastSpell(valimathrasportal, SPELL_VALIMATHRAS_PORTAL);
                             JumpToNextStep(12 * IN_MILLISECONDS);
                             break;
                         case 25:
                             if (Creature* valimathras = ObjectAccessor::GetCreature(*me, ValimathrasGUID))
{
                                 valimathras->GetMotionMaster()->MovePoint(0, 1804.559f, 235.504f, 62.753f);
                                 valimathras->DespawnOrUnsummon(3 * IN_MILLISECONDS);
                             }
                             if (Creature* valimathrasportal = ObjectAccessor::GetCreature(*me, ValimathrasPortalGUID))
                                 valimathrasportal->DespawnOrUnsummon(6 * IN_MILLISECONDS);
                             JumpToNextStep(1 * IN_MILLISECONDS);
                             break;
                         case 26:
{
                                 Talk(THRALL_SAY_COURTYARD_3);
                                 me->CastSpell(me, SPELL_TIDAL_WAVE_SUMMON);
                                 std::list<Creature*> HelperList;
                                 me->GetCreatureListWithEntryInGrid(HelperList, NPC_SLINGER_TRIGGER, 1000.0f);
                                 if (!HelperList.empty())
                                     for (std::list<Creature*>::iterator itr = HelperList.begin(); itr != HelperList.end(); itr++)
                                         (*itr)->DespawnOrUnsummon();
                                 JumpToNextStep(5 * IN_MILLISECONDS);
                                 break;
                             }
                         // Start COURTYARD_FIGHT
                         case 27:
                             FollowThrall();
                             SetEscortPaused(false);
                             bStepping = false;
                             SetRun(true);
                             Talk(THRALL_SAY_COURTYARD_4);
                             UpdateWorldState(me->GetMap(), WORLD_STATE_BATTLE_START_H, 0);
                             UpdateWorldState(me->GetMap(), WORLD_STATE_COURTYARD_FIGHT_H, 1);
                             JumpToNextStep(0);
                             break;
                         case 28:
{
                                 EnableAttack = true;
                                 DoCast(me, SPELL_HEROIC_VANGUARD, true);
                                 std::list<Creature*> HostileEndList;
                                 me->GetCreatureListWithEntryInGrid(HostileEndList, NPC_TREACHEROUS_GUARDIAN_H, 1000.0f);
                                 me->GetCreatureListWithEntryInGrid(HostileEndList, NPC_DOCTOR_H, 1000.0f);
                                 me->GetCreatureListWithEntryInGrid(HostileEndList, NPC_CHEMIST_H, 1000.0f);
                                 if (!HostileEndList.empty())
                                     for (std::list<Creature*>::iterator itr = HostileEndList.begin(); itr != HostileEndList.end(); itr++) (*itr)->SetFaction(FACTION_MONSTER);
                                 SpawnWave(4);
                                 JumpToNextStep(10 * IN_MILLISECONDS);
                                 break;
                             }
                         case 29:
                             SpawnWave(4);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 30:
                             SpawnWave(4);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 31:
                             SpawnWave(4);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 32:
                             SpawnWave(4);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 33:
                             SpawnWave(4);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 34:
                             SpawnWave(4);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 35:
                             SpawnWave(4);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 36:
                             SpawnWave(4);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 37:
                             SpawnWave(4);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 38:
                             SpawnWave(4);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 39:
                             SpawnWave(4);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 40:
                             SpawnWave(4);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 41:
                             SpawnWave(4);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 42:
                             SpawnWave(4);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 43:
                             SpawnWave(4);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 44:
                             SpawnWave(4);
                             JumpToNextStep(2 * IN_MILLISECONDS);
                             break;
                         case 45:
                             SpawnWave(5);
                             bStepping = false;
                             JumpToNextStep(0 * IN_MILLISECONDS);
                             break;
                         // End COURTYARD_FIGHT
                         case 46:
{
                                 FollowThrall();
                                 std::list<Creature*> HostileList;
                                 me->GetCreatureListWithEntryInGrid(HostileList, NPC_TREACHEROUS_GUARDIAN_H, 1000.0f);
                                 me->GetCreatureListWithEntryInGrid(HostileList, NPC_DOCTOR_H, 1000.0f);
                                 me->GetCreatureListWithEntryInGrid(HostileList, NPC_CHEMIST_H, 1000.0f);
                                 me->GetCreatureListWithEntryInGrid(HostileList, NPC_BLIGHT_SLINGER, 1000.0f);
                                 if (!HostileList.empty())
                                     for (std::list<Creature*>::iterator itr = HostileList.begin(); itr != HostileList.end(); itr++)
                                         (*itr)->DespawnOrUnsummon();
                                 for (uint8 i = 0; i < 7; ++i)
                                     me->SummonGameObject(GO_HORDE_BANNER, ThrallSpawn[i + 37].x, ThrallSpawn[i + 37].y, ThrallSpawn[i + 37].z, ThrallSpawn[i + 37].o, 0.0f, 0.0f, 0.0f, 0.0f, 120 * IN_MILLISECONDS);
                                 SpawnWave(6);
                                 SetEscortPaused(false);
                                 bStepping = false;
                                 SetRun(false);
                                 JumpToNextStep(0 * IN_MILLISECONDS);
                                 break;
                             }
                         case 47:
                             Talk(THRALL_SAY_COURTYARD_5);
                             JumpToNextStep(5 * IN_MILLISECONDS);
                             break;
                         case 48:
                             SetEscortPaused(false);
                             bStepping = false;
                             JumpToNextStep(0 * IN_MILLISECONDS);
                             break;
                         // Elevator Event
                         case 49:
                             Talk(THRALL_SAY_ELEVATOR_1);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 50:
                             if (Creature* sylvanas = ObjectAccessor::GetCreature(*me, sylvanasfollowGUID))
                                 sylvanas->AI()->Talk(SYLVANAS_SAY_ELEVATOR_1);
                             JumpToNextStep(3 * IN_MILLISECONDS);
                             break;
                         case 51:
                             Talk(THRALL_SAY_ELEVATOR_2);
                             DoCast(me, SPELL_CALL_OF_AIR);
                             SpawnWave(7);
                             JumpToNextStep(16 * IN_MILLISECONDS);
                             break;
                         case 52:
                             Talk(THRALL_SAY_ELEVATOR_3);
                             JumpToNextStep(4 * IN_MILLISECONDS);
                             break;
                         case 53:
                             SpawnWave(8);
                             me->GetMotionMaster()->MoveJump(ThrallSpawn[55].x, ThrallSpawn[55].y, ThrallSpawn[55].z, 40.0f, 40.0f, 0);
                             if (Creature* sylvanas = ObjectAccessor::GetCreature(*me, sylvanasfollowGUID))
                                 sylvanas->GetMotionMaster()->MoveJump(ThrallSpawn[56].x, ThrallSpawn[56].y, ThrallSpawn[56].z, 40.0f, 40.0f, 0);
                             JumpToNextStep(4 * IN_MILLISECONDS);
                             break;
                         case 54:
                             FollowThrall();
                             SetEscortPaused(false);
                             bStepping = false;
                             SetRun(false);
                             JumpToNextStep(0 * IN_MILLISECONDS);
                             break;
                         // Top of Undercity Discussion
                         case 55:
                             if (Creature* sylvanas = ObjectAccessor::GetCreature(*me, sylvanasfollowGUID))
                                 sylvanas->AI()->Talk(SYLVANAS_SAY_SANCTUM_1);
                             JumpToNextStep(5 * IN_MILLISECONDS);
                             break;
                         case 56:
                             if (Creature* sylvanas = ObjectAccessor::GetCreature(*me, sylvanasfollowGUID))
                                 sylvanas->AI()->Talk(SYLVANAS_SAY_SANCTUM_2);
                             JumpToNextStep(8 * IN_MILLISECONDS);
                             break;
                         case 57:
                             Talk(THRALL_SAY_SANCTUM_2);
                             JumpToNextStep(5 * IN_MILLISECONDS);
                             break;
                         case 58:
                             if (Creature* sylvanas = ObjectAccessor::GetCreature(*me, sylvanasfollowGUID))
                                 sylvanas->AI()->Talk(SYLVANAS_SAY_SANCTUM_3);
                             JumpToNextStep(5 * IN_MILLISECONDS);
                             break;
                         // Top of Undercity - Fight
                         case 59:
                             SpawnWave(9);
                             JumpToNextStep(5 * IN_MILLISECONDS);
                             break;
                         case 60:
                             SpawnWave(9);
                             JumpToNextStep(5 * IN_MILLISECONDS);
                             break;
                         case 61:
                             SpawnWave(9);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 62:
                             FollowThrall();
                             SetEscortPaused(false);
                             bStepping = false;
                             SetRun(false);
                             JumpToNextStep(0 * IN_MILLISECONDS);
                             break;
                         case 63:
                             JumpToNextStep(3 * IN_MILLISECONDS);
                             break;
                         case 64:
                             SpawnWave(10);
                             JumpToNextStep(5 * IN_MILLISECONDS);
                             break;
                         case 65:
                             SpawnWave(10);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 66:
                             FollowThrall();
                             SetEscortPaused(false);
                             bStepping = false;
                             SetRun(false);
                             JumpToNextStep(0 * IN_MILLISECONDS);
                             break;
                         case 67:
                             SpawnWave(11);
                             JumpToNextStep(6 * IN_MILLISECONDS);
                             break;
                         case 68:
                             SpawnWave(11);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 69:
                             FollowThrall();
                             SetEscortPaused(false);
                             bStepping = false;
                             SetRun(false);
                             JumpToNextStep(0 * IN_MILLISECONDS);
                             break;
                         // KHANOK - Valimathtas Intro
                         case 70:
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 71:
                             if (Creature* sylvanas = ObjectAccessor::GetCreature(*me, sylvanasfollowGUID))
                                 sylvanas->AI()->Talk(SYLVANAS_SAY_SANCTUM_4);
                             SpawnWave(12);
                             JumpToNextStep(5 * IN_MILLISECONDS);
                             break;
                         case 72:
                             if (Creature* valimathras = ObjectAccessor::GetCreature(*me, ValimathrasGUID))
                                 valimathras->AI()->Talk(SAY_VALIMATHRAS_INNER_SANKTUM_0);
                             JumpToNextStep(5 * IN_MILLISECONDS);
                             break;
                         case 73:
                             if (Creature* valimathras = ObjectAccessor::GetCreature(*me, ValimathrasGUID))
                                 valimathras->AI()->Talk(SAY_VALIMATHRAS_INNER_SANKTUM_1);
                             SpawnWave(13);
                             JumpToNextStep(2 * IN_MILLISECONDS);
                             break;
                         case 74:
                             if (Creature* valimathrasportal = ObjectAccessor::GetCreature(*me, ValimathrasPortalGUID))
                                 valimathrasportal->CastSpell(valimathrasportal, SPELL_VALIMATHRAS_PORTAL);
                             JumpToNextStep(4 * IN_MILLISECONDS);
                             break;
                         case 75:
                             if (Creature* valimathras = ObjectAccessor::GetCreature(*me, ValimathrasGUID))
{
                                 valimathras->GetMotionMaster()->MovePoint(0, 1596.642f, 429.811f, -46.3429f);
                                 valimathras->DespawnOrUnsummon(3 * IN_MILLISECONDS);
                             }
                             if (Creature* valimathrasportal = ObjectAccessor::GetCreature(*me, ValimathrasPortalGUID))
                                 valimathrasportal->DespawnOrUnsummon(3 * IN_MILLISECONDS);
                             JumpToNextStep(2 * IN_MILLISECONDS);
                             break;
                         // KHANOK - Trashspawn
                         case 76:
                             SpawnWave(14);
                             JumpToNextStep(8 * IN_MILLISECONDS);
                             break;
                         case 77:
                             SpawnWave(15);
                             JumpToNextStep(8 * IN_MILLISECONDS);
                             break;
                         case 78:
                             SpawnWave(16);
                             JumpToNextStep(8 * IN_MILLISECONDS);
                             break;
                         case 79:
                             SpawnWave(14);
                             JumpToNextStep(8 * IN_MILLISECONDS);
                             break;
                         case 80:
                             SpawnWave(15);
                             JumpToNextStep(8 * IN_MILLISECONDS);
                             break;
                         case 81:
                             SpawnWave(16);
                             JumpToNextStep(8 * IN_MILLISECONDS);
                             break;
                         case 82:
                             SpawnWave(14);
                             JumpToNextStep(8 * IN_MILLISECONDS);
                             break;
                         case 83:
                             SpawnWave(15);
                             JumpToNextStep(8 * IN_MILLISECONDS);
                             break;
                         case 84:
                             SpawnWave(16);
                             JumpToNextStep(8 * IN_MILLISECONDS);
                             break;
                         case 85:
                             SpawnWave(14);
                             JumpToNextStep(8 * IN_MILLISECONDS);
                             break;
                         case 86:
                             SpawnWave(15);
                             JumpToNextStep(8 * IN_MILLISECONDS);
                             break;
                         case 87:
                             SpawnWave(16);
                             JumpToNextStep(8 * IN_MILLISECONDS);
                             break;
                         case 88:
                             SpawnWave(14);
                             JumpToNextStep(8 * IN_MILLISECONDS);
                             break;
                         case 89:
                             SpawnWave(15);
                             JumpToNextStep(8 * IN_MILLISECONDS);
                             break;
                         case 90:
                             SpawnWave(16);
                             JumpToNextStep(8 * IN_MILLISECONDS);
                             break;
                         case 91:
                             SpawnWave(14);
                             JumpToNextStep(8 * IN_MILLISECONDS);
                             break;
                         case 92:
                             SpawnWave(15);
                             JumpToNextStep(8 * IN_MILLISECONDS);
                             break;
                         case 93:
                             SpawnWave(16);
                             JumpToNextStep(8 * IN_MILLISECONDS);
                             break;
                         case 94:
                             // Spawn Boss 2 KHANOK
                             SpawnWave(17);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 95:
                             SpawnWave(14);
                             JumpToNextStep(5 * IN_MILLISECONDS);
                             break;
                         case 96:
                             SpawnWave(15);
                             JumpToNextStep(5 * IN_MILLISECONDS);
                             break;
                         case 97:
                             SpawnWave(16);
                             JumpToNextStep(0 * IN_MILLISECONDS);
                             bStepping = false;
                             break;
                         case 98:
                             // KHANOK - Won
                             Talk(THRALL_SAY_SANCTUM_3);
                             JumpToNextStep(7 * IN_MILLISECONDS);
                             break;
                         case 99:
                             SpawnWave(18);
                             JumpToNextStep(0.35 * IN_MILLISECONDS);
                             break;
                         case 100:
                             SpawnWave(18);
                             JumpToNextStep(0.35 * IN_MILLISECONDS);
                             break;
                         case 101:
                             SpawnWave(18);
                             JumpToNextStep(0.35 * IN_MILLISECONDS);
                             break;
                         case 102:
                             SpawnWave(18);
                             JumpToNextStep(0.35 * IN_MILLISECONDS);
                             break;
                         case 103:
                             SpawnWave(18);
                             JumpToNextStep(0.35 * IN_MILLISECONDS);
                             break;
                         case 104:
                             SpawnWave(18);
                             JumpToNextStep(0.35 * IN_MILLISECONDS);
                             break;
                         case 105:
                             SpawnWave(18);
                             JumpToNextStep(0.35 * IN_MILLISECONDS);
                             break;
                         case 106:
                             SpawnWave(18);
                             JumpToNextStep(0.35 * IN_MILLISECONDS);
                             break;
                         case 107:
                             SpawnWave(18);
                             JumpToNextStep(3 * IN_MILLISECONDS);
                             break;
                         case 108:
                             Talk(THRALL_SAY_SANCTUM_4);
                             FollowThrall();
                             SetEscortPaused(false);
                             bStepping = false;
                             SetRun(false);
                             JumpToNextStep(0 * IN_MILLISECONDS);
                             break;
                         case 109:
                             if (Creature* sylvanas = ObjectAccessor::GetCreature(*me, sylvanasfollowGUID))
                                 sylvanas->AI()->Talk(SYLVANAS_SAY_SANCTUM_5);
                             JumpToNextStep(8 * IN_MILLISECONDS);
                             break;
                         case 110:
                             SpawnWave(19);
                             JumpToNextStep(5 * IN_MILLISECONDS);
                             break;
                         case 111:
                             FollowThrall();
                             SetEscortPaused(false);
                             bStepping = false;
                             SetRun(true);
                             JumpToNextStep(0 * IN_MILLISECONDS);
                             break;
                         case 112:
                             JumpToNextStep(3 * IN_MILLISECONDS);
                             break;
                         case 113:
                             Talk(THRALL_SAY_SANCTUM_5);
                             JumpToNextStep(12 * IN_MILLISECONDS);
                             break;
                         case 114:
                             Talk(THRALL_SAY_SANCTUM_6);
                             DoCast(me, SPELL_CALL_OF_EARTH);
                             JumpToNextStep(6 * IN_MILLISECONDS);
                             break;
                         case 115:
{
                                 std::list<GameObject*> SaronitList;
                                 GetGameObjectListWithEntryInGrid(SaronitList, me, GO_BLOCKED_PASSAGE, 80.0f);
                                 for (std::list<GameObject*>::const_iterator itr = SaronitList.begin(); itr != SaronitList.end(); ++itr)
                                     if (GameObject* saronit = (*itr))
                                         saronit->UseDoorOrButton();
                                 JumpToNextStep(5 * IN_MILLISECONDS);
                                 break;
                             }
                         case 116:
                             Talk(THRALL_SAY_SANCTUM_7);
                             UpdateWorldState(me->GetMap(), WORLD_STATE_ROYAL_QUARTER_FIGHT_H, 1);
                             FollowThrall();
                             SetEscortPaused(false);
                             bStepping = false;
                             JumpToNextStep(0 * IN_MILLISECONDS);
                             break;
                         // Valimathras Intro
                         case 117:
                             Talk(THRALL_SAY_THRONE_1);
                             JumpToNextStep(5 * IN_MILLISECONDS);
                             break;
                         case 118:
                             if (Creature* valimathras = ObjectAccessor::GetCreature(*me, ValimathrasGUID))
{
                                 valimathras->AI()->Talk(SAY_THRONE_1);
                                 valimathras->CastSpell(me, SPELL_OPENING_LEGION_PORTALS);
                             }
                             JumpToNextStep(3 * IN_MILLISECONDS);
                             break;
                         case 119:
                             SpawnWave(20);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 120:
                             SpawnWave(21);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 121:
                             ActivateValimathrasPortal();
                             if (Creature* valimathras = ObjectAccessor::GetCreature(*me, ValimathrasGUID))
                                 valimathras->AI()->Talk(SAY_THRONE_2);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 122:
                             SpawnWave(20);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 123:
                             SpawnWave(21);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 124:
                             ActivateValimathrasPortal();
                             if (Creature* valimathras = ObjectAccessor::GetCreature(*me, ValimathrasGUID))
                                 valimathras->AI()->Talk(SAY_THRONE_3);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 125:
                             SpawnWave(20);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 126:
                             SpawnWave(21);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 127:
                             ActivateValimathrasPortal();
                             if (Creature* valimathras = ObjectAccessor::GetCreature(*me, ValimathrasGUID))
                                 valimathras->AI()->Talk(SAY_THRONE_4);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 128:
                             SpawnWave(20);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 129:
                             SpawnWave(21);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 130:
                             ActivateValimathrasPortal();
                             if (Creature* valimathras = ObjectAccessor::GetCreature(*me, ValimathrasGUID))
                                 valimathras->AI()->Talk(SAY_THRONE_5);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 131:
                             SpawnWave(20);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 132:
                             SpawnWave(21);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 133:
                             ActivateValimathrasPortal();
                             if (Creature* valimathras = ObjectAccessor::GetCreature(*me, ValimathrasGUID))
                                 valimathras->AI()->Talk(SAY_THRONE_6);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 134:
                             SpawnWave(20);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 135:
                             SpawnWave(21);
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 136:
                             ActivateValimathrasPortal();
                             JumpToNextStep(5 * IN_MILLISECONDS);
                             break;
                         // Valimathras Fight
                         case 137:
                             if (Creature* valimathras = ObjectAccessor::GetCreature(*me, ValimathrasGUID))
{
                                 valimathras->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC | UNIT_FLAG_IMMUNE_TO_PC);
                                 valimathras->RemoveAura(SPELL_AURA_OF_VARIMATHRAS);
                                 valimathras->RemoveAura(SPELL_OPENING_LEGION_PORTALS);
                                 valimathras->AI()->Talk(SAY_VALIMATHRAS_ATTACK);
                                 valimathras->AddThreat(me, 100.0f);
                                 me->AddThreat(valimathras, 100.0f);
                                 valimathras->AI()->AttackStart(me);
                             }
                             bStepping = false;
                             JumpToNextStep(0 * IN_MILLISECONDS);
                             break;
                         // Valimathras Won
                         case 138:
                             Talk(THRALL_SAY_THRONE_2);
                             JumpToNextStep(5 * IN_MILLISECONDS);
                             break;
                         case 139:
                             Talk(THRALL_SAY_THRONE_3);
                             JumpToNextStep(2 * IN_MILLISECONDS);
                             break;
                         case 140:
                             SetEscortPaused(false);
                             bStepping = false;
                             JumpToNextStep(0 * IN_MILLISECONDS);
                             break;
                         case 141:
                             JumpToNextStep(8 * IN_MILLISECONDS);
                             break;
                         case 142:
                             if (Creature* sylvanas = ObjectAccessor::GetCreature(*me, sylvanasfollowGUID))
                                 me->SetFacingToObject(sylvanas);
                             Talk(THRALL_SAY_THRONE_4);
                             JumpToNextStep(3 * IN_MILLISECONDS);
                             break;
                         case 143:
                             if (Creature* sylvanas = ObjectAccessor::GetCreature(*me, sylvanasfollowGUID))
{
                                 sylvanas->GetMotionMaster()->MovePoint(0, 1289.48f, 314.33f, -57.32f, true);
                                 sylvanas->CastSpell(sylvanas, SPELL_LEAP_TO_PLATFORM);
                             }
                             JumpToNextStep(10 * IN_MILLISECONDS);
                             break;
                         case 144:
                             if (Creature* sylvanas = ObjectAccessor::GetCreature(*me, sylvanasfollowGUID))
{
                                 sylvanas->AI()->Talk(SYLVANAS_SAY_THRONE_1);
                                 me->SetFacingToObject(sylvanas);
                                 sylvanas->SetFacingToObject(me);
                                 me->HandleEmoteCommand(EMOTE_ONESHOT_SALUTE);
                             }
                             JumpToNextStep(3 * IN_MILLISECONDS);
                             break;
                         case 145:
                             Talk(THRALL_SAY_THRONE_5);
                             FollowThrall();
                             SetEscortPaused(false);
                             bStepping = false;
                             JumpToNextStep(0 * IN_MILLISECONDS);
                             break;
                         case 146:
                             Talk(THRALL_SAY_THRONE_6);
                             JumpToNextStep(3 * IN_MILLISECONDS);
                             break;
                         case 147:
                             for (uint8 i = 0; i < ALLIANCE_FORCE_MAXCOUNT; ++i)
{
                                 if (Creature* temp = me->SummonCreature(NPC_SW_SOLDIER, AllianceSpawn[i + 25].x, AllianceSpawn[i + 25].y, AllianceSpawn[i + 25].z, AllianceSpawn[i + 25].o, TEMPSUMMON_MANUAL_DESPAWN))
{
                                     allianceForcesGUID[i] = temp->GetGUID();
                                     temp->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
                                     temp->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                                     temp->ApplySpellImmune(0, IMMUNITY_ID, SPELL_SYLVANAS_BUFF, true);
                                     temp->SetReactState(REACT_PASSIVE);
                                     temp->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_READY2H);
                                 }
                             }
                             if (Creature* wrynn = me->SummonCreature(NPC_WRYNN, 1308.862f, 381.809f, -66.044243f, TEMPSUMMON_MANUAL_DESPAWN))
{
                                 WrynnGUID = wrynn->GetGUID();
                                 wrynn->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
                                 wrynn->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                                 wrynn->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_READY2H);
                                 wrynn->SetReactState(REACT_PASSIVE);
                                 wrynn->GetMotionMaster()->MovePoint(0, 1302.543f, 359.472f, -67.295f, true);
                             }
                             if (Creature* jaina = me->SummonCreature(NPC_JAINA, 1308.862f, 381.809f, -66.044243f, TEMPSUMMON_MANUAL_DESPAWN))
{
                                 JainaGUID = jaina->GetGUID();
                                 jaina->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
                                 jaina->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                                 jaina->SetReactState(REACT_PASSIVE);
                             }
                             JumpToNextStep(6 * IN_MILLISECONDS);
                             break;
                         // Wrynn Intro
                         case 148:
                             if (Creature* wrynn = ObjectAccessor::GetCreature(*me, WrynnGUID))
                                 wrynn->AI()->Talk(WRYNN_SAY_THRONE_5);
                             JumpToNextStep(15 * IN_MILLISECONDS);
                             break;
                         case 149:
                             if (Creature* wrynn = ObjectAccessor::GetCreature(*me, WrynnGUID))
                                 wrynn->AI()->Talk(WRYNN_SAY_THRONE_6);
                             JumpToNextStep(15 * IN_MILLISECONDS);
                             break;
                         case 150:
                             if (Creature* wrynn = ObjectAccessor::GetCreature(*me, WrynnGUID))
                                 wrynn->AI()->Talk(WRYNN_SAY_THRONE_7);
                             JumpToNextStep(16.5 * IN_MILLISECONDS);
                             break;
                         case 151:
                             if (Creature* wrynn = ObjectAccessor::GetCreature(*me, WrynnGUID))
                                 wrynn->AI()->Talk(WRYNN_SAY_THRONE_8);
                             JumpToNextStep(6 * IN_MILLISECONDS);
                             break;
                         // Wrynn Fight
                         case 152:
                             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC | UNIT_FLAG_IMMUNE_TO_PC);
                             if (Creature* wrynn = ObjectAccessor::GetCreature(*me, WrynnGUID))
{
                                 wrynn->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
                                 wrynn->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                                 wrynn->SetReactState(REACT_AGGRESSIVE);
                                 wrynn->AddThreat(me, 100.0f);
                                 me->AddThreat(wrynn, 100.0f);
                                 wrynn->AI()->AttackStart(me);
                             }
                             for (uint8 i = 0; i < ALLIANCE_FORCE_MAXCOUNT; ++i)
{
                                 if (Creature* temp = ObjectAccessor::GetCreature(*me, allianceForcesGUID[i]))
{
                                     temp->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC | UNIT_FLAG_IMMUNE_TO_PC);
                                     temp->SetReactState(REACT_AGGRESSIVE);
                                     temp->AddThreat(me, 100.0f);
                                     temp->AI()->AttackStart(me);
                                 }
                             }
                             JumpToNextStep(6 * IN_MILLISECONDS);
                             break;
                         case 153:
                             if (Creature* jaina = ObjectAccessor::GetCreature(*me, JainaGUID))
{
                                 jaina->GetMotionMaster()->MovePoint(0, AllianceWP[9].x, AllianceWP[9].y, AllianceWP[9].z);
                                 jaina->AI()->Talk(JAINA_SAY_THRONE_2);
                             }
                             JumpToNextStep(8 * IN_MILLISECONDS);
                             break;
                         case 154:
                             if (Creature* jaina = ObjectAccessor::GetCreature(*me, JainaGUID))
{
                                 jaina->AI()->DoCastAOE(SPELL_DEEPFREEZE);
                                 jaina->AI()->Talk(JAINA_SAY_THRONE_3);
                             }
                             JumpToNextStep(5 * IN_MILLISECONDS);
                             break;
                         case 155:
{
                                 std::list<Creature*> HelperList;
                                 me->GetCreatureListWithEntryInGrid(HelperList, NPC_SW_SOLDIER, 100.0f);
                                 me->GetCreatureListWithEntryInGrid(HelperList, NPC_JAINA, 100.0f);
                                 me->GetCreatureListWithEntryInGrid(HelperList, NPC_WRYNN, 100.0f);
                                 if (!HelperList.empty())
                                     for (std::list<Creature*>::iterator itr = HelperList.begin(); itr != HelperList.end(); itr++)
                                         (*itr)->DespawnOrUnsummon();
                                 JumpToNextStep(8 * IN_MILLISECONDS);
                                 break;
                             }
                         case 156:
                             Talk(THRALL_SAY_THRONE_7);
                             SetEscortPaused(false);
                             bStepping = false;
                             JumpToNextStep(0 * IN_MILLISECONDS);
                             break;
                         case 157:
                             Talk(THRALL_SAY_THRONE_9);
                             me->SetStandState(UNIT_STAND_STATE_SIT);
                             JumpToNextStep(3 * IN_MILLISECONDS);
                             break;
                         // Ending
                         case 158:
                             if (Creature* saurfang = me->SummonCreature(NPC_OVERLORD_SAURFANG, 1297.574f, 347.154f, -65.027f, TEMPSUMMON_MANUAL_DESPAWN))
{
                                 SaurfangGUID = saurfang->GetGUID();
                                 saurfang->SetWalk(true);
                                 saurfang->GetMotionMaster()->MovePoint(0, 1300.862f, 353.670f, -66.187f, true);
                             }
                             JumpToNextStep(7 * IN_MILLISECONDS);
                             break;
                         case 159:
                             if (Creature* saurfang = ObjectAccessor::GetCreature(*me, SaurfangGUID))
{
                                 saurfang->AI()->Talk(SAY_SAURFANG_ARRIVAL_1);
                                 saurfang->SetStandState(UNIT_STAND_STATE_SIT);
                             }
                             JumpToNextStep(6 * IN_MILLISECONDS);
                             break;
                         case 160:
                             if (Creature* saurfang = ObjectAccessor::GetCreature(*me, SaurfangGUID))
                                 saurfang->AI()->Talk(SAY_SAURFANG_ARRIVAL_2);
                             JumpToNextStep(6 * IN_MILLISECONDS);
                             break;
                         case 161:
                             if (Creature* saurfang = ObjectAccessor::GetCreature(*me, SaurfangGUID))
                                 saurfang->AI()->Talk(SAY_SAURFANG_ARRIVAL_3);
                             if (Map* map = me->GetMap())
{
                                 Map::PlayerList const& PlayerList = map->GetPlayers();
                                 for (Map::PlayerList::const_iterator i = PlayerList.begin(); i != PlayerList.end(); ++i)
{
                                     if (Player* player = i->GetSource())
{
                                         if (me->IsInRange(player, 0.0f, 50.0f))
{
                                             if (player->GetTeamId() == TEAM_HORDE)
{
                                                 player->RemoveAura(SPELL_SYLVANAS_BUFF);
                                                 player->RemoveAura(SPELL_THRALL_BUFF);
                                                 player->CompleteQuest(QUEST_BATTLE_H);
                                                 player->CastSpell(player, SPELL_PHASING_HORDE);
                                             }
                                         }
                                     }
                                 }
                             }
                             JumpToNextStep(5 * IN_MILLISECONDS);
                             break;
                         case 162:
                             Talk(THRALL_SAY_THRONE_10);
                             JumpToNextStep(5 * IN_MILLISECONDS);
                             break;
                         case 163:
                             me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
                             me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_QUESTGIVER);
                             Talk(THRALL_SAY_THRONE_11);
                             UpdateWorldState(me->GetMap(), WORLD_STATE_ROYAL_QUARTER_FIGHT_H, 0);
                             UpdateWorldState(me->GetMap(), WORLD_STATE_INNER_SANKTUM_FIGHT_H, 0);
                             UpdateWorldState(me->GetMap(), WORLD_STATE_COURTYARD_FIGHT_H, 0);
                             std::list<Creature*> HelperList;
                             me->GetCreatureListWithEntryInGrid(HelperList, NPC_SYLVANAS, 100.0f);
                             me->GetCreatureListWithEntryInGrid(HelperList, NPC_OVERLORD_SAURFANG, 100.0f);
                             if (!HelperList.empty())
                                 for (std::list<Creature*>::iterator itr = HelperList.begin(); itr != HelperList.end(); itr++)
                                     (*itr)->DespawnOrUnsummon(120 * IN_MILLISECONDS);
                             me->DespawnOrUnsummon(120 * IN_MILLISECONDS);
                             bStepping = false;
                             JumpToNextStep(0 * IN_MILLISECONDS);
                             break;
                     }
                 }
                 else phaseTimer -= diff;
             }
             if (!UpdateVictim())
                 return;
             _events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             while (uint32 eventId = _events.ExecuteEvent())
             {
                 switch (eventId)
                 {
                     case EVENT_CHAIN_LIGHTNING:
                         DoCastVictim(SPELL_CHAIN_LIGHTNING);
                         _events.ScheduleEvent(EVENT_CHAIN_LIGHTNING, urand(5, 8) * IN_MILLISECONDS);
                         break;
                     case EVENT_LAVA_BURST:
                         DoCastVictim(SPELL_LAVA_BURST);
                         _events.ScheduleEvent(EVENT_LAVA_BURST, urand(3, 5) * IN_MILLISECONDS);
                         break;
                     case EVENT_THUNDER:
                         DoCast(me, SPELL_THUNDER);
                         _events.ScheduleEvent(EVENT_THUNDER, 15 * IN_MILLISECONDS);
                         break;
                     case EVENT_AGGRO_SYLVANAS:
                         if (me->GetVictim())
                             if (Creature* sylvanas = ObjectAccessor::GetCreature(*me, sylvanasfollowGUID))
                                 sylvanas->AI()->AttackStart(me->GetVictim());
                         _events.ScheduleEvent(EVENT_AGGRO_SYLVANAS, 2 * IN_MILLISECONDS);
                         break;
                     case EVENT_THRALL_BUFF:
                         DoCast(me, SPELL_THRALL_BUFF);
                         _events.ScheduleEvent(EVENT_THRALL_BUFF, 10 * IN_MILLISECONDS);
                         break;
                     default:
                         break;
                 }
             }
             DoMeleeAttackIfReady();
         }
References _events, ActivateValimathrasPortal(), Unit::AddThreat(), ALLIANCE_FORCE_MAXCOUNT, allianceForcesGUID, AllianceSpawn, AllianceWP, MapRefMgr::begin(), bStepping, Unit::CastSpell(), Creature::DespawnOrUnsummon(), diff(), Unit::Dismount(), UnitAI::DoCast(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), EMOTE_ONESHOT_SALUTE, EMOTE_STATE_READY2H, EnableAttack, MapRefMgr::end(), EVENT_AGGRO_SYLVANAS, EVENT_CHAIN_LIGHTNING, EVENT_LAVA_BURST, EVENT_THRALL_BUFF, EVENT_THUNDER, EventMap::ExecuteEvent(), FACTION_MONSTER, WorldObject::FindNearestCreature(), FollowThrall(), ObjectAccessor::GetCreature(), WorldObject::GetCreatureListWithEntryInGrid(), GetGameObjectListWithEntryInGrid(), WorldObject::GetMap(), Unit::GetMotionMaster(), Unit::GetVictim(), GO_BLOCKED_PASSAGE, GO_HORDE_BANNER, Unit::HandleEmoteCommand(), Unit::HasUnitState(), IMMUNITY_ID, IN_MILLISECONDS, WorldObject::IsInRange(), JAINA_SAY_THRONE_2, JAINA_SAY_THRONE_3, JainaGUID, JumpToNextStep(), ScriptedAI::me, MotionMaster::MoveJump(), NPC_BLIGHT_SLINGER, NPC_CHEMIST_H, NPC_DOCTOR_H, NPC_HORDE_GUARD, NPC_JAINA, NPC_OVERLORD_SAURFANG, NPC_PLAGUE_TRIGGER, NPC_SLINGER_TRIGGER, NPC_SW_SOLDIER, NPC_SYLVANAS, NPC_TREACHEROUS_GUARDIAN_H, NPC_WRYNN, Location::o, phaseTimer, QUEST_BATTLE_H, REACT_AGGRESSIVE, REACT_PASSIVE, Object::RemoveFlag(), SaurfangGUID, SAY_BURN_UC, SAY_PUTRESS_ANGER, SAY_SAURFANG_ARRIVAL_1, SAY_SAURFANG_ARRIVAL_2, SAY_SAURFANG_ARRIVAL_3, SAY_THRONE_1, SAY_THRONE_2, SAY_THRONE_3, SAY_THRONE_4, SAY_THRONE_5, SAY_THRONE_6, SAY_VALIMATHRAS_ATTACK, SAY_VALIMATHRAS_INNER_SANKTUM_0, SAY_VALIMATHRAS_INNER_SANKTUM_1, SAY_VALIMATHRAS_INTRO_0, SAY_VALIMATHRAS_INTRO_1, SAY_VALIMATHRAS_INTRO_2, EventMap::ScheduleEvent(), WorldObject::setActive(), npc_escortAI::SetEscortPaused(), Unit::SetFacingToObject(), Object::SetFlag(), npc_escortAI::SetRun(), Unit::SetStandState(), SpawnWave(), SPELL_AURA_OF_VARIMATHRAS, SPELL_CALL_OF_AIR, SPELL_CALL_OF_EARTH, SPELL_CHAIN_LIGHTNING, SPELL_DEEPFREEZE, SPELL_HEROIC_VANGUARD, SPELL_LAVA_BURST, SPELL_LEAP_TO_PLATFORM, SPELL_OPENING_LEGION_PORTALS, SPELL_PHASING_HORDE, SPELL_SYLVANAS_BUFF, SPELL_THRALL_BUFF, SPELL_THUNDER, SPELL_TIDAL_WAVE_SUMMON, SPELL_VALIMATHRAS_PORTAL, step, WorldObject::SummonCreature(), WorldObject::SummonGameObject(), SYLVANAS_SAY_ELEVATOR_1, SYLVANAS_SAY_SANCTUM_1, SYLVANAS_SAY_SANCTUM_2, SYLVANAS_SAY_SANCTUM_3, SYLVANAS_SAY_SANCTUM_4, SYLVANAS_SAY_SANCTUM_5, SYLVANAS_SAY_THRONE_1, sylvanasfollowGUID, CreatureAI::Talk(), TEAM_HORDE, TEMPSUMMON_MANUAL_DESPAWN, THRALL_SAY_COURTYARD_1, THRALL_SAY_COURTYARD_2, THRALL_SAY_COURTYARD_3, THRALL_SAY_COURTYARD_4, THRALL_SAY_COURTYARD_5, THRALL_SAY_ELEVATOR_1, THRALL_SAY_ELEVATOR_2, THRALL_SAY_ELEVATOR_3, THRALL_SAY_PREP_1, THRALL_SAY_PREP_2, THRALL_SAY_PREP_3, THRALL_SAY_PREP_4, THRALL_SAY_PREP_5, THRALL_SAY_PREP_6, THRALL_SAY_PREP_7, THRALL_SAY_PREP_8, THRALL_SAY_SANCTUM_2, THRALL_SAY_SANCTUM_3, THRALL_SAY_SANCTUM_4, THRALL_SAY_SANCTUM_5, THRALL_SAY_SANCTUM_6, THRALL_SAY_SANCTUM_7, THRALL_SAY_THRONE_1, THRALL_SAY_THRONE_10, THRALL_SAY_THRONE_11, THRALL_SAY_THRONE_2, THRALL_SAY_THRONE_3, THRALL_SAY_THRONE_4, THRALL_SAY_THRONE_5, THRALL_SAY_THRONE_6, THRALL_SAY_THRONE_7, THRALL_SAY_THRONE_9, ThrallSpawn, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, UNIT_NPC_EMOTESTATE, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAG_QUESTGIVER, UNIT_NPC_FLAGS, UNIT_STAND_STATE_SIT, UNIT_STATE_CASTING, EventMap::Update(), npc_escortAI::UpdateAI(), CreatureAI::UpdateVictim(), UpdateWorldState(), urand(), ValimathrasGUID, ValimathrasPortalGUID, WORLD_STATE_BATTLE_COUNTDOWN_H, WORLD_STATE_BATTLE_START_H, WORLD_STATE_COURTYARD_FIGHT_H, WORLD_STATE_INNER_SANKTUM_FIGHT_H, WORLD_STATE_ROYAL_QUARTER_FIGHT_H, WRYNN_SAY_THRONE_5, WRYNN_SAY_THRONE_6, WRYNN_SAY_THRONE_7, WRYNN_SAY_THRONE_8, WrynnGUID, G3D::x, Location::x, G3D::y, Location::y, G3D::z, and Location::z.
UpdateWorldState()
void npc_thrall_bfu::npc_thrall_bfuAI::UpdateWorldState (Map * map, uint32 id, uint32 state) inline
Definition at line 2533 of file zone_undercity.cpp.
         {
             Map::PlayerList const& players = map->GetPlayers();
             if (!players.isEmpty())
             {
                 for (Map::PlayerList::const_iterator itr = players.begin(); itr != players.end(); ++itr)
                 {
                     if (Player* player = itr->GetSource())
                         player->SendUpdateWorldState(id, state);
                 }
             }
         }
References MapRefMgr::begin(), MapRefMgr::end(), Map::GetPlayers(), and LinkedListHead::isEmpty().
Referenced by SummonedCreatureDies(), UpdateAI(), and WaypointReached().
WaypointReached()
void npc_thrall_bfu::npc_thrall_bfuAI::WaypointReached (uint32 waypointId) inline override virtual
Implements npc_escortAI.
Definition at line 2861 of file zone_undercity.cpp.
         {
             switch (waypointId)
             {
                 case 1:
                     SetHoldState(true);
                     bStepping = true;
                     break;
                 case 2:
                     SetHoldState(true);
                     bStepping = true;
                     break;
                 case 11:
                     SetHoldState(true);
                     bStepping = true;
                     break;
                 case 13:
                     SetHoldState(true);
                     bStepping = true;
                     break;
                 case 14:
                     SetHoldState(true);
                     bStepping = true;
                     break;
                 case 34:
                     SetHoldState(true);
                     bStepping = true;
                     break;
                 case 36:
                     Talk(THRALL_SAY_SANCTUM_1);
                     UpdateWorldState(me->GetMap(), WORLD_STATE_INNER_SANKTUM_FIGHT_H, 1);
                     break;
                 case 46:
                     SetHoldState(true);
                     bStepping = true;
                     break;
                 case 57:
                     SetHoldState(true);
                     bStepping = true;
                     break;
                 case 61:
                     SetHoldState(true);
                     bStepping = true;
                     break;
                 case 65:
                     SetHoldState(true);
                     bStepping = true;
                     break;
                 case 66:
                     SetHoldState(true);
                     bStepping = true;
                     break;
                 case 75:
                     SetHoldState(true);
                     bStepping = true;
                     break;
                 case 81:
                     SetHoldState(true);
                     bStepping = true;
                     break;
                 case 104:
                     SetHoldState(true);
                     bStepping = true;
                     break;
                 case 109:
                     SetHoldState(true);
                     bStepping = true;
                     break;
                 case 113:
                     SetHoldState(true);
                     bStepping = true;
                     break;
                 case 117:
                     SetHoldState(true);
                     bStepping = true;
                     break;
                 case 118:
                     Talk(THRALL_SAY_THRONE_8);
                     break;
                 case 120:
                     SetHoldState(true);
                     bStepping = true;
                     break;
             }
         }
References bStepping, WorldObject::GetMap(), ScriptedAI::me, SetHoldState(), CreatureAI::Talk(), THRALL_SAY_SANCTUM_1, THRALL_SAY_THRONE_8, UpdateWorldState(), and WORLD_STATE_INNER_SANKTUM_FIGHT_H.
Member Data Documentation
_events
EventMap npc_thrall_bfu::npc_thrall_bfuAI::_events
Definition at line 2350 of file zone_undercity.cpp.
Referenced by Reset(), and UpdateAI().
allianceForcesGUID
ObjectGuid npc_thrall_bfu::npc_thrall_bfuAI::allianceForcesGUID[ALLIANCE_FORCE_MAXCOUNT]
Definition at line 2342 of file zone_undercity.cpp.
Referenced by UpdateAI().
bStepping
bool npc_thrall_bfu::npc_thrall_bfuAI::bStepping
Definition at line 2335 of file zone_undercity.cpp.
Referenced by Reset(), SummonedCreatureDies(), UpdateAI(), and WaypointReached().
EnableAttack
bool npc_thrall_bfu::npc_thrall_bfuAI::EnableAttack
Definition at line 2336 of file zone_undercity.cpp.
Referenced by JustSummoned(), Reset(), and UpdateAI().
hordeGuardsGUID
GuidVector npc_thrall_bfu::npc_thrall_bfuAI::hordeGuardsGUID
Definition at line 2348 of file zone_undercity.cpp.
Referenced by npc_thrall_bfuAI(), Reset(), and SpawnWave().
JainaGUID
ObjectGuid npc_thrall_bfu::npc_thrall_bfuAI::JainaGUID
Definition at line 2346 of file zone_undercity.cpp.
Referenced by Reset(), and UpdateAI().
phaseTimer
uint32 npc_thrall_bfu::npc_thrall_bfuAI::phaseTimer
Definition at line 2339 of file zone_undercity.cpp.
Referenced by JumpToNextStep(), Reset(), and UpdateAI().
SaurfangGUID
ObjectGuid npc_thrall_bfu::npc_thrall_bfuAI::SaurfangGUID
Definition at line 2347 of file zone_undercity.cpp.
Referenced by Reset(), and UpdateAI().
step
uint32 npc_thrall_bfu::npc_thrall_bfuAI::step
Definition at line 2338 of file zone_undercity.cpp.
Referenced by JumpToNextStep(), Reset(), and UpdateAI().
sylvanasfollowGUID
ObjectGuid npc_thrall_bfu::npc_thrall_bfuAI::sylvanasfollowGUID
Definition at line 2341 of file zone_undercity.cpp.
Referenced by FollowThrall(), Reset(), and UpdateAI().
ValimathrasGUID
ObjectGuid npc_thrall_bfu::npc_thrall_bfuAI::ValimathrasGUID
Definition at line 2343 of file zone_undercity.cpp.
Referenced by Reset(), SpawnWave(), and UpdateAI().
ValimathrasPortalGUID
ObjectGuid npc_thrall_bfu::npc_thrall_bfuAI::ValimathrasPortalGUID
Definition at line 2344 of file zone_undercity.cpp.
Referenced by Reset(), SpawnWave(), and UpdateAI().
WrynnGUID
ObjectGuid npc_thrall_bfu::npc_thrall_bfuAI::WrynnGUID
Definition at line 2345 of file zone_undercity.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/zone_undercity.cpp