Azerotcore-wotlk: achievement_bg_control_all_nodes Class Reference
achievement_bg_control_all_nodes Class Reference
Public Member Functions
achievement_bg_control_all_nodes ()
bool OnCheck (Player *source, Unit *, uint32) override
Public Member Functions inherited from AchievementCriteriaScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AchievementCriteriaScript
AchievementCriteriaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 40 of file achievement_scripts.cpp.
Constructor & Destructor Documentation
achievement_bg_control_all_nodes()
achievement_bg_control_all_nodes::achievement_bg_control_all_nodes () inline
Definition at line 43 of file achievement_scripts.cpp.
 : AchievementCriteriaScript("achievement_bg_control_all_nodes") { }
Member Function Documentation
OnCheck()
bool achievement_bg_control_all_nodes::OnCheck (Player * source, Unit * , uint32) inline override virtual
Reimplemented from AchievementCriteriaScript.
Definition at line 45 of file achievement_scripts.cpp.
     {
         Battleground* bg = source->GetBattleground();
         return bg && bg->AllNodesConrolledByTeam(source->GetTeamId());
     }
References Battleground::AllNodesConrolledByTeam(), Player::GetBattleground(), and Player::GetTeamId().
The documentation for this class was generated from the following file:
src/server/scripts/World/achievement_scripts.cpp