Azerotcore-wotlk: boss_hexlord_malacrass::boss_hex_lord_malacrassAI Struct Reference
boss_hexlord_malacrass::boss_hex_lord_malacrassAI Struct Reference
Public Member Functions
boss_hex_lord_malacrassAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *) override
void KilledUnit (Unit *) override
void JustDied (Unit *) override
void SelectAddEntry ()
void SpawnAdds ()
void UpdateAI (uint32 diff) override
void UseAbility ()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * instance
ObjectGuid AddGUID [4]
uint32 AddEntry [4]
ObjectGuid PlayerGUID
uint32 SpiritBolts_Timer
uint32 DrainPower_Timer
uint32 SiphonSoul_Timer
uint32 PlayerAbility_Timer
uint32 CheckAddState_Timer
uint32 ResetTimer
uint32 PlayerClass
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 256 of file boss_hexlord.cpp.
Constructor & Destructor Documentation
boss_hex_lord_malacrassAI()
boss_hexlord_malacrass::boss_hex_lord_malacrassAI::boss_hex_lord_malacrassAI (Creature * creature) inline
Definition at line 258 of file boss_hexlord.cpp.
                                                       : ScriptedAI(creature)
         {
             instance = creature->GetInstanceScript();
             SelectAddEntry();
         }
References WorldObject::GetInstanceScript(), instance, and SelectAddEntry().
Member Function Documentation
EnterCombat()
void boss_hexlord_malacrass::boss_hex_lord_malacrassAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 297 of file boss_hexlord.cpp.
         {
             instance->SetData(DATA_HEXLORDEVENT, IN_PROGRESS);
             DoZoneInCombat();
             Talk(SAY_AGGRO);
             for (uint8 i = 0; i < 4; ++i)
             {
                 Creature* creature = ObjectAccessor::GetCreature(*me, AddGUID[i]);
                 if (creature && creature->IsAlive())
                     creature->AI()->AttackStart(me->GetVictim());
                 else
                 {
                     EnterEvadeMode();
                     break;
                 }
             }
         }
References AddGUID, Creature::AI(), UnitAI::AttackStart(), DATA_HEXLORDEVENT, CreatureAI::DoZoneInCombat(), CreatureAI::EnterEvadeMode(), ObjectAccessor::GetCreature(), Unit::GetVictim(), IN_PROGRESS, instance, Unit::IsAlive(), ScriptedAI::me, SAY_AGGRO, ZoneScript::SetData(), and CreatureAI::Talk().
JustDied()
void boss_hexlord_malacrass::boss_hex_lord_malacrassAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 330 of file boss_hexlord.cpp.
         {
             instance->SetData(DATA_HEXLORDEVENT, DONE);
             Talk(SAY_DEATH);
             for (uint8 i = 0; i < 4; ++i)
             {
                 Unit* Temp = ObjectAccessor::GetUnit(*me, AddGUID[i]);
                 if (Temp && Temp->IsAlive())
                     Unit::DealDamage(Temp, Temp, Temp->GetHealth(), nullptr, DIRECT_DAMAGE, SPELL_SCHOOL_MASK_NORMAL, nullptr, false);
             }
         }
References AddGUID, DATA_HEXLORDEVENT, Unit::DealDamage(), DIRECT_DAMAGE, DONE, Unit::GetHealth(), ObjectAccessor::GetUnit(), instance, Unit::IsAlive(), ScriptedAI::me, SAY_DEATH, ZoneScript::SetData(), SPELL_SCHOOL_MASK_NORMAL, and CreatureAI::Talk().
KilledUnit()
void boss_hexlord_malacrass::boss_hex_lord_malacrassAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 317 of file boss_hexlord.cpp.
         {
             switch (urand(0, 1))
             {
                 case 0:
                     Talk(SAY_KILL_ONE);
                     break;
                 case 1:
                     Talk(SAY_KILL_TWO);
                     break;
             }
         }
References SAY_KILL_ONE, SAY_KILL_TWO, CreatureAI::Talk(), and urand().
Reset()
void boss_hexlord_malacrass::boss_hex_lord_malacrassAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 280 of file boss_hexlord.cpp.
         {
             instance->SetData(DATA_HEXLORDEVENT, NOT_STARTED);
             SpiritBolts_Timer = 20000;
             DrainPower_Timer = 60000;
             SiphonSoul_Timer = 100000;
             PlayerAbility_Timer = 99999;
             CheckAddState_Timer = 5000;
             ResetTimer = 5000;
             SpawnAdds();
             me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID, 46916);
             me->SetByteValue(UNIT_FIELD_BYTES_2, 0, SHEATH_STATE_MELEE);
         }
References CheckAddState_Timer, DATA_HEXLORDEVENT, DrainPower_Timer, instance, ScriptedAI::me, NOT_STARTED, PlayerAbility_Timer, ResetTimer, Object::SetByteValue(), ZoneScript::SetData(), Object::SetUInt32Value(), SHEATH_STATE_MELEE, SiphonSoul_Timer, SpawnAdds(), SpiritBolts_Timer, UNIT_FIELD_BYTES_2, and UNIT_VIRTUAL_ITEM_SLOT_ID.
SelectAddEntry()
void boss_hexlord_malacrass::boss_hex_lord_malacrassAI::SelectAddEntry () inline
Definition at line 344 of file boss_hexlord.cpp.
         {
             std::vector<uint32> AddList;
             for (uint8 i = 0; i < 8; ++i)
                 AddList.push_back(AddEntryList[i]);
             while (AddList.size() > 4)
                 AddList.erase(AddList.begin() + rand() % AddList.size());
             uint8 i = 0;
             for (std::vector<uint32>::const_iterator itr = AddList.begin(); itr != AddList.end(); ++itr, ++i)
                 AddEntry[i] = *itr;
         }
References AddEntry, and AddEntryList.
Referenced by boss_hex_lord_malacrassAI().
SpawnAdds()
void boss_hexlord_malacrass::boss_hex_lord_malacrassAI::SpawnAdds () inline
Definition at line 359 of file boss_hexlord.cpp.
         {
             for (uint8 i = 0; i < 4; ++i)
             {
                 Creature* creature = (ObjectAccessor::GetCreature((*me), AddGUID[i]));
                 if (!creature || !creature->IsAlive())
                 {
                     if (creature) creature->setDeathState(DEAD);
                     creature = me->SummonCreature(AddEntry[i], Pos_X[i], POS_Y, POS_Z, ORIENT, TEMPSUMMON_DEAD_DESPAWN, 0);
                     if (creature) AddGUID[i] = creature->GetGUID();
                 }
                 else
                 {
                     creature->AI()->EnterEvadeMode();
                     creature->SetPosition(Pos_X[i], POS_Y, POS_Z, ORIENT);
                     creature->StopMovingOnCurrentPos();
                 }
             }
         }
References AddEntry, AddGUID, Creature::AI(), DEAD, CreatureAI::EnterEvadeMode(), ObjectAccessor::GetCreature(), Object::GetGUID(), Unit::IsAlive(), ScriptedAI::me, ORIENT, Pos_X, POS_Y, POS_Z, Creature::setDeathState(), Creature::SetPosition(), Unit::StopMovingOnCurrentPos(), WorldObject::SummonCreature(), and TEMPSUMMON_DEAD_DESPAWN.
Referenced by Reset().
UpdateAI()
void boss_hexlord_malacrass::boss_hex_lord_malacrassAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 379 of file boss_hexlord.cpp.
         {
             if (!UpdateVictim())
                 return;
             if (ResetTimer <= diff)
             {
                 if (me->IsWithinDist3d(119.223f, 1035.45f, 29.4481f, 10))
                 {
                     EnterEvadeMode();
                     return;
                 }
                 ResetTimer = 5000;
             }
             else ResetTimer -= diff;
             if (CheckAddState_Timer <= diff)
             {
                 for (uint8 i = 0; i < 4; ++i)
                     if (Creature* temp = ObjectAccessor::GetCreature(*me, AddGUID[i]))
                         if (temp->IsAlive() && !temp->GetVictim())
                             temp->AI()->AttackStart(me->GetVictim());
                 CheckAddState_Timer = 5000;
             }
             else CheckAddState_Timer -= diff;
             if (DrainPower_Timer <= diff)
             {
                 DoCast(me, SPELL_DRAIN_POWER, true);
                 Talk(SAY_DRAIN_POWER);
                 DrainPower_Timer = urand(40000, 55000);    // must cast in 60 sec, or buff/debuff will disappear
             }
             else DrainPower_Timer -= diff;
             if (SpiritBolts_Timer <= diff)
             {
                 if (DrainPower_Timer < 12000)    // channel 10 sec
                     SpiritBolts_Timer = 13000;   // cast drain power first
                 else
                 {
                     DoCast(me, SPELL_SPIRIT_BOLTS, false);
                     Talk(SAY_SPIRIT_BOLTS);
                     SpiritBolts_Timer = 40000;
                     SiphonSoul_Timer = 10000;    // ready to drain
                     PlayerAbility_Timer = 99999;
                 }
             }
             else SpiritBolts_Timer -= diff;
             if (SiphonSoul_Timer <= diff)
             {
                 Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 70, true);
                 Unit* trigger = DoSpawnCreature(NPC_TEMP_TRIGGER, 0, 0, 0, 0, TEMPSUMMON_TIMED_DESPAWN, 30000);
                 if (!target || !trigger)
                 {
                     EnterEvadeMode();
                     return;
                 }
                 else
                 {
                     trigger->SetDisplayId(11686);
                     trigger->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                     trigger->CastSpell(target, SPELL_SIPHON_SOUL, true);
                     trigger->GetMotionMaster()->MoveChase(me);
                     //DoCast(target, SPELL_SIPHON_SOUL, true);
                     //me->SetGuidValue(UNIT_FIELD_CHANNEL_OBJECT, target->GetGUID());
                     //me->SetUInt32Value(UNIT_CHANNEL_SPELL, SPELL_SIPHON_SOUL);
                     PlayerGUID = target->GetGUID();
                     PlayerAbility_Timer = urand(8000, 10000);
                     PlayerClass = target->getClass() - 1;
                     if (PlayerClass == CLASS_DRUID - 1)
                         PlayerClass = CLASS_DRUID;
                     else if (PlayerClass == CLASS_PRIEST - 1 && target->HasSpell(15473))
                         PlayerClass = CLASS_PRIEST; // shadow priest
                     SiphonSoul_Timer = 99999;   // buff lasts 30 sec
                 }
             }
             else SiphonSoul_Timer -= diff;
             if (PlayerAbility_Timer <= diff)
             {
                 //Unit* target = ObjectAccessor::GetUnit(*me, PlayerGUID);
                 //if (target && target->IsAlive())
                 //{
                 UseAbility();
                 PlayerAbility_Timer = urand(8000, 10000);
                 //}
             }
             else PlayerAbility_Timer -= diff;
             DoMeleeAttackIfReady();
         }
References AddGUID, Unit::CastSpell(), CheckAddState_Timer, CLASS_DRUID, CLASS_PRIEST, UnitAI::DoCast(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DoSpawnCreature(), DrainPower_Timer, CreatureAI::EnterEvadeMode(), Unit::getClass(), ObjectAccessor::GetCreature(), Object::GetGUID(), Unit::GetMotionMaster(), Unit::GetVictim(), Unit::HasSpell(), WorldObject::IsWithinDist3d(), ScriptedAI::me, MotionMaster::MoveChase(), NPC_TEMP_TRIGGER, PlayerAbility_Timer, PlayerClass, PlayerGUID, ResetTimer, SAY_DRAIN_POWER, SAY_SPIRIT_BOLTS, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Unit::SetDisplayId(), Object::SetFlag(), SiphonSoul_Timer, SPELL_DRAIN_POWER, SPELL_SIPHON_SOUL, SPELL_SPIRIT_BOLTS, SpiritBolts_Timer, CreatureAI::Talk(), TEMPSUMMON_TIMED_DESPAWN, UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE, CreatureAI::UpdateVictim(), urand(), and UseAbility().
UseAbility()
void boss_hexlord_malacrass::boss_hex_lord_malacrassAI::UseAbility () inline
Definition at line 477 of file boss_hexlord.cpp.
         {
             uint8 random = urand(0, 2);
             Unit* target = nullptr;
             switch (PlayerAbility[PlayerClass][random].target)
             {
                 case ABILITY_TARGET_SELF:
                     target = me;
                     break;
                 case ABILITY_TARGET_VICTIM:
                     target = me->GetVictim();
                     break;
                 case ABILITY_TARGET_ENEMY:
                 default:
                     target = SelectTarget(SELECT_TARGET_RANDOM, 0, 100, true);
                     break;
                 case ABILITY_TARGET_HEAL:
                     target = DoSelectLowestHpFriendly(50, 0);
                     break;
                 case ABILITY_TARGET_BUFF:
                     {
                         std::list<Creature*> templist = DoFindFriendlyMissingBuff(50, PlayerAbility[PlayerClass][random].spell);
                         if (!templist.empty())
                             target = *(templist.begin());
                     }
                     break;
             }
             if (target)
                 DoCast(target, PlayerAbility[PlayerClass][random].spell, false);
         }
References ABILITY_TARGET_BUFF, ABILITY_TARGET_ENEMY, ABILITY_TARGET_HEAL, ABILITY_TARGET_SELF, ABILITY_TARGET_VICTIM, UnitAI::DoCast(), ScriptedAI::DoFindFriendlyMissingBuff(), ScriptedAI::DoSelectLowestHpFriendly(), Unit::GetVictim(), ScriptedAI::me, PlayerAbility, PlayerClass, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), and urand().
Referenced by UpdateAI().
Member Data Documentation
AddEntry
uint32 boss_hexlord_malacrass::boss_hex_lord_malacrassAI::AddEntry[4]
Definition at line 267 of file boss_hexlord.cpp.
Referenced by SelectAddEntry(), and SpawnAdds().
AddGUID
ObjectGuid boss_hexlord_malacrass::boss_hex_lord_malacrassAI::AddGUID[4]
Definition at line 266 of file boss_hexlord.cpp.
Referenced by EnterCombat(), JustDied(), SpawnAdds(), and UpdateAI().
CheckAddState_Timer
uint32 boss_hexlord_malacrass::boss_hex_lord_malacrassAI::CheckAddState_Timer
Definition at line 275 of file boss_hexlord.cpp.
Referenced by Reset(), and UpdateAI().
DrainPower_Timer
uint32 boss_hexlord_malacrass::boss_hex_lord_malacrassAI::DrainPower_Timer
Definition at line 272 of file boss_hexlord.cpp.
Referenced by Reset(), and UpdateAI().
instance
InstanceScript* boss_hexlord_malacrass::boss_hex_lord_malacrassAI::instance
Definition at line 264 of file boss_hexlord.cpp.
Referenced by boss_hex_lord_malacrassAI(), EnterCombat(), JustDied(), and Reset().
PlayerAbility_Timer
uint32 boss_hexlord_malacrass::boss_hex_lord_malacrassAI::PlayerAbility_Timer
Definition at line 274 of file boss_hexlord.cpp.
Referenced by Reset(), and UpdateAI().
PlayerClass
uint32 boss_hexlord_malacrass::boss_hex_lord_malacrassAI::PlayerClass
Definition at line 278 of file boss_hexlord.cpp.
Referenced by UpdateAI(), and UseAbility().
PlayerGUID
ObjectGuid boss_hexlord_malacrass::boss_hex_lord_malacrassAI::PlayerGUID
Definition at line 269 of file boss_hexlord.cpp.
Referenced by UpdateAI().
ResetTimer
uint32 boss_hexlord_malacrass::boss_hex_lord_malacrassAI::ResetTimer
Definition at line 276 of file boss_hexlord.cpp.
Referenced by Reset(), and UpdateAI().
SiphonSoul_Timer
uint32 boss_hexlord_malacrass::boss_hex_lord_malacrassAI::SiphonSoul_Timer
Definition at line 273 of file boss_hexlord.cpp.
Referenced by Reset(), and UpdateAI().
SpiritBolts_Timer
uint32 boss_hexlord_malacrass::boss_hex_lord_malacrassAI::SpiritBolts_Timer
Definition at line 271 of file boss_hexlord.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/ZulAman/boss_hexlord.cpp