Azerotcore-wotlk: G3D::GCamera Class Reference
G3D::GCamera Class Reference
#include <GCamera.h>
Classes
class Frustum
Public Types
enum FOVDirection { HORIZONTAL , VERTICAL }
Public Member Functions
GCamera (const Any &any)
operator Any () const
GCamera ()
GCamera (const Matrix4 &proj, const CFrame &frame)
virtual ~GCamera ()
const CoordinateFrame & coordinateFrame () const
void setPixelOffset (const Vector2 &p)
const Vector2 & pixelOffset () const
void getCoordinateFrame (CoordinateFrame &c) const
void setCoordinateFrame (const CoordinateFrame &c)
void getProjectUnitMatrix (const Rect2D &viewport, Matrix4 &P) const
void getProjectPixelMatrix (const Rect2D &viewport, Matrix4 &P) const
Vector3 convertFromUnitToNormal (const Vector3 &in, const Rect2D &viewport) const
void setFieldOfView (float edgeToEdgeAngleRadians, FOVDirection direction)
void getFieldOfView (float &angle, FOVDirection &direction) const
Vector3 project (const G3D::Vector3 &point, const class Rect2D &viewport) const
Vector3 projectUnit (const G3D::Vector3 &point, const class Rect2D &viewport) const
Vector3 unproject (const Vector3 &v, const Rect2D &viewport) const
Vector3 unprojectUnit (const Vector3 &v, const Rect2D &viewport) const
float worldToScreenSpaceArea (float area, float z, const class Rect2D &viewport) const
void getNearViewportCorners (const class Rect2D &viewport, Vector3 &outUR, Vector3 &outUL, Vector3 &outLL, Vector3 &outLR) const
void getFarViewportCorners (const class Rect2D &viewport, Vector3 &outUR, Vector3 &outUL, Vector3 &outLL, Vector3 &outLR) const
float imagePlaneDepth () const
Ray worldRay (float x, float y, const class Rect2D &viewport) const
float nearPlaneZ () const
float farPlaneZ () const
void setFarPlaneZ (float z)
void setNearPlaneZ (float z)
float viewportWidth (const class Rect2D &viewport) const
float viewportHeight (const class Rect2D &viewport) const
void setPosition (const Vector3 &t)
void lookAt (const Vector3 &position, const Vector3 &up=Vector3::unitY())
void getClipPlanes (const Rect2D &viewport, Array< Plane > &outClip) const
void frustum (const Rect2D &viewport, GCamera::Frustum &f) const
GCamera::Frustum frustum (const Rect2D &viewport) const
void serialize (class BinaryOutput &bo) const
void deserialize (class BinaryInput &bi)
Private Attributes
float m_fieldOfView
float m_nearPlaneZ
float m_farPlaneZ
CoordinateFrame m_cframe
FOVDirection m_direction
Vector2 m_pixelOffset
Detailed Description
Abstraction of a pinhole camera.
The area a camera sees is called a frustum. It is bounded by the near plane, the far plane, and the sides of the view frame projected into the scene. It has the shape of a pyramid with the top cut off.
Cameras can project points from 3D to 2D. The "unit" projection matches OpenGL. It maps the entire view frustum to a cube of unit radius (i.e., edges of length 2) centered at the origin. The non-unit projection then maps that cube to the specified pixel viewport in X and Y and the range [0, 1] in Z. The projection is reversable as long as the projected Z value is known.
All viewport arguments are the pixel bounds of the viewport– e.g., RenderDevice::viewport().
See http://bittermanandy.wordpress.com/2009/04/10/a-view-to-a-thrill-part-one-camera-concepts/ for a nice introduction to camera transformations.
Definition at line 45 of file GCamera.h.
Member Enumeration Documentation
FOVDirection
enum G3D::GCamera::FOVDirection
Stores the direction of the field of view
Enumerator
HORIZONTAL
VERTICAL
Definition at line 51 of file GCamera.h.
 {HORIZONTAL, VERTICAL};
Constructor & Destructor Documentation
GCamera() [1/3]
G3D::GCamera::GCamera (const Any & any)
Must be of the format produced by the Any cast, e.g.,
GCamera {
    coordinateFrame = CFrame::fromXYZYPRDegrees(-13.3f, 8.0f, -1.9f, 246.6f, -3),
    nearPlaneZ = -0.5,
    farPlaneZ = -50,
    fovDirection = "HORIZONTAL",
    fovAngleDegrees = 90
}
Missing fields are filled from the default GCamera constructor.
Definition at line 22 of file GCamera.cpp.
{
     any.verifyName("GCamera");
     any.verifyType(Any::TABLE);
     *this = GCamera();
     const Any::AnyTable& table = any.table();
     Any::AnyTable::Iterator it = table.begin();
     while (it.hasMore()) {
         const std::string& k = toUpper(it->key);
         if (k == "FOVDIRECTION") {
             const std::string& v = toUpper(it->value);
             if (v == "HORIZONTAL") {
                 m_direction = HORIZONTAL;
             } else if (v == "VERTICAL") {
                 m_direction = VERTICAL;
             } else {
                 any.verify(false, "fovDirection must be \"HORIZONTAL\" or \"VERTICAL\"");
             }
         } else if (k == "COORDINATEFRAME") {
             m_cframe = it->value;
         } else if (k == "FOVDEGREES") {
             m_fieldOfView = toRadians(it->value.number());
         } else if (k == "NEARPLANEZ") {
             m_nearPlaneZ = it->value;
         } else if (k == "FARPLANEZ") {
             m_farPlaneZ = it->value;
         } else if (k == "PIXELOFFSET") {
             m_pixelOffset = it->value;
         } else {
             any.verify(false, std::string("Illegal key in table: ") + it->key);
         }
         ++it;
     }
 }
References G3D::any(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::begin(), GCamera(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Iterator::hasMore(), HORIZONTAL, G3D::Table< Key, Value, HashFunc, EqualsFunc >::Entry::key, m_cframe, m_direction, m_farPlaneZ, m_fieldOfView, m_nearPlaneZ, m_pixelOffset, G3D::Any::TABLE, G3D::toRadians(), G3D::toUpper(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::Entry::value, and VERTICAL.
GCamera() [2/3]
G3D::GCamera::GCamera ()
Definition at line 72 of file GCamera.cpp.
                  {
     setNearPlaneZ(-0.2f);
     setFarPlaneZ(-150.0f);
     setFieldOfView((float)toRadians(90.0f), HORIZONTAL);
 }
References HORIZONTAL, setFarPlaneZ(), setFieldOfView(), setNearPlaneZ(), and G3D::toRadians().
Referenced by GCamera().
GCamera() [3/3]
G3D::GCamera::GCamera (const Matrix4 & proj, const CFrame & frame)
Definition at line 79 of file GCamera.cpp.
{
     float left, right, bottom, top, nearval, farval;
     proj.getPerspectiveProjectionParameters(left, right, bottom, top, nearval, farval);
     setNearPlaneZ(-nearval);
     setFarPlaneZ(-farval);
     float x = right;
     // Assume horizontal field of view
     setFieldOfView(atan2(x, -m_nearPlaneZ) * 2.0f, HORIZONTAL);
     setCoordinateFrame(frame);
 }
References G3D::Matrix4::getPerspectiveProjectionParameters(), HORIZONTAL, align::left, m_nearPlaneZ, align::right, setCoordinateFrame(), setFarPlaneZ(), setFieldOfView(), setNearPlaneZ(), and G3D::x.
~GCamera()
G3D::GCamera::~GCamera () virtual
Definition at line 92 of file GCamera.cpp.
                   {
 }
Member Function Documentation
convertFromUnitToNormal()
Vector3 G3D::GCamera::convertFromUnitToNormal (const Vector3 & in, const Rect2D & viewport) const
Converts projected points from OpenGL standards (-1, 1) to normal 3D coordinate standards (0, 1)
Deprecated:
Definition at line 507 of file GCamera.cpp.
{
     return (in + Vector3(1,1,1)) * 0.5 * Vector3(viewport.width(), -viewport.height(), 1) +
            Vector3(viewport.x0(), viewport.y1(), 0);
 }
References G3D::Rect2D::height(), G3D::Rect2D::width(), G3D::Rect2D::x0(), and G3D::Rect2D::y1().
Referenced by project(), and unprojectUnit().
coordinateFrame()
const CoordinateFrame& G3D::GCamera::coordinateFrame () const inline
Returns the current coordinate frame
Definition at line 121 of file GCamera.h.
{
         return m_cframe;
     }
References m_cframe.
Referenced by projectUnit().
deserialize()
void G3D::GCamera::deserialize (class BinaryInput & bi)
Definition at line 495 of file GCamera.cpp.
{
     m_fieldOfView = bi.readFloat32();
     m_nearPlaneZ = bi.readFloat32();
     debugAssert(m_nearPlaneZ < 0.0f);
     m_farPlaneZ = bi.readFloat32();
     debugAssert(m_farPlaneZ < 0.0f);
     m_cframe.deserialize(bi);
     m_direction = (FOVDirection)bi.readInt8();
     m_pixelOffset.deserialize(bi);
 }
References debugAssert, G3D::CoordinateFrame::deserialize(), G3D::Vector2::deserialize(), m_cframe, m_direction, m_farPlaneZ, m_fieldOfView, m_nearPlaneZ, m_pixelOffset, G3D::BinaryInput::readFloat32(), and G3D::BinaryInput::readInt8().
farPlaneZ()
float G3D::GCamera::farPlaneZ () const inline
Returns a negative z-value.
Definition at line 279 of file GCamera.h.
{
         return m_farPlaneZ;
     }
References m_farPlaneZ.
Referenced by serialize().
frustum() [1/2]
GCamera::Frustum G3D::GCamera::frustum (const Rect2D & viewport) const
Definition at line 285 of file GCamera.cpp.
{
     Frustum f;
     frustum(viewport, f);
     return f;
 }
References f(), and frustum().
frustum() [2/2]
void G3D::GCamera::frustum (const Rect2D & viewport, GCamera::Frustum & f) const
Returns the world space view frustum, which is a truncated pyramid describing the volume of space seen by this camera.
Definition at line 292 of file GCamera.cpp.
{
     // The volume is the convex hull of the vertices definining the view
     // frustum and the light source point at infinity.
     const float x               = viewportWidth(viewport) / 2;
     const float y               = viewportHeight(viewport) / 2;
     const float zn              = m_nearPlaneZ;
     const float zf              = m_farPlaneZ;
     float xx, zz, yy;
     float halfFOV = m_fieldOfView * 0.5f;
     // This computes the normal, which is based on the complement of the
     // halfFOV angle, so the equations are "backwards"
     if (m_direction == VERTICAL) {
         yy = -cosf(halfFOV);
         xx = yy * viewport.height() / viewport.width();
         zz = -sinf(halfFOV);
     } else {
         xx = -cosf(halfFOV);
         yy = xx * viewport.width() / viewport.height();
         zz = -sinf(halfFOV);
     }
     // Near face (ccw from UR)
     fr.vertexPos.append(
         Vector4( x,  y, zn, 1),
         Vector4(-x,  y, zn, 1),
         Vector4(-x, -y, zn, 1),
         Vector4( x, -y, zn, 1));
     // Far face (ccw from UR, from origin)
     if (m_farPlaneZ == -finf()) {
         fr.vertexPos.append(Vector4( x,  y, zn, 0),
                             Vector4(-x,  y, zn, 0),
                             Vector4(-x, -y, zn, 0),
                             Vector4( x, -y, zn, 0));
     } else {
         // Finite
         const float s = zf / zn;
         fr.vertexPos.append(Vector4( x * s,  y * s, zf, 1),
                             Vector4(-x * s,  y * s, zf, 1),
                             Vector4(-x * s, -y * s, zf, 1),
                             Vector4( x * s, -y * s, zf, 1));
     }
     Frustum::Face face;
     // Near plane (wind backwards so normal faces into frustum)
     // Recall that nearPlane, farPlane are positive numbers, so
     // we need to negate them to produce actual z values.
     face.plane = Plane(Vector3(0,0,-1), Vector3(0,0,m_nearPlaneZ));
     face.vertexIndex[0] = 3;
     face.vertexIndex[1] = 2;
     face.vertexIndex[2] = 1;
     face.vertexIndex[3] = 0;
     fr.faceArray.append(face);
     // Right plane
     face.plane = Plane(Vector3(xx, 0, zz), Vector3::zero());
     face.vertexIndex[0] = 0;
     face.vertexIndex[1] = 4;
     face.vertexIndex[2] = 7;
     face.vertexIndex[3] = 3;
     fr.faceArray.append(face);
     // Left plane
     face.plane = Plane(Vector3(-fr.faceArray.last().plane.normal().x, 0, fr.faceArray.last().plane.normal().z), Vector3::zero());
     face.vertexIndex[0] = 5;
     face.vertexIndex[1] = 1;
     face.vertexIndex[2] = 2;
     face.vertexIndex[3] = 6;
     fr.faceArray.append(face);
     // Top plane
     face.plane = Plane(Vector3(0, yy, zz), Vector3::zero());
     face.vertexIndex[0] = 1;
     face.vertexIndex[1] = 5;
     face.vertexIndex[2] = 4;
     face.vertexIndex[3] = 0;
     fr.faceArray.append(face);
     // Bottom plane
     face.plane = Plane(Vector3(0, -fr.faceArray.last().plane.normal().y, fr.faceArray.last().plane.normal().z), Vector3::zero());
     face.vertexIndex[0] = 2;
     face.vertexIndex[1] = 3;
     face.vertexIndex[2] = 7;
     face.vertexIndex[3] = 6;
     fr.faceArray.append(face);
     // Far plane
     if (-m_farPlaneZ < finf()) {
         face.plane = Plane(Vector3(0, 0, 1), Vector3(0, 0, m_farPlaneZ));
         face.vertexIndex[0] = 4;
         face.vertexIndex[1] = 5;
         face.vertexIndex[2] = 6;
         face.vertexIndex[3] = 7;
         fr.faceArray.append(face);
     }
     // Transform vertices to world space
     for (int v = 0; v < fr.vertexPos.size(); ++v) {
         fr.vertexPos[v] = m_cframe.toWorldSpace(fr.vertexPos[v]);
     }
     // Transform planes to world space
     for (int p = 0; p < fr.faceArray.size(); ++p) {
         // Since there is no scale factor, we don't have to
         // worry about the inverse transpose of the normal.
         Vector3 normal;
         float d;
         fr.faceArray[p].plane.getEquation(normal, d);
         Vector3 newNormal = m_cframe.rotation * normal;
         if (isFinite(d)) {
             d = (newNormal * -d + m_cframe.translation).dot(newNormal);
             fr.faceArray[p].plane = Plane(newNormal, newNormal * d);
         } else {
             // When d is infinite, we can't multiply 0's by it without
             // generating NaNs.
             fr.faceArray[p].plane = Plane::fromEquation(newNormal.x, newNormal.y, newNormal.z, d);
         }
     }
 }
References mpq::d, G3D::dot(), G3D::GCamera::Frustum::faceArray, G3D::finf(), G3D::Plane::fromEquation(), G3D::Rect2D::height(), G3D::isFinite(), m_cframe, m_direction, m_farPlaneZ, m_fieldOfView, m_nearPlaneZ, G3D::GCamera::Frustum::Face::plane, G3D::CoordinateFrame::rotation, G3D::CoordinateFrame::toWorldSpace(), G3D::CoordinateFrame::translation, G3D::GCamera::Frustum::Face::vertexIndex, G3D::GCamera::Frustum::vertexPos, VERTICAL, viewportHeight(), viewportWidth(), G3D::Rect2D::width(), G3D::x, G3D::Vector3::x, G3D::xx(), G3D::y, G3D::Vector3::y, G3D::yy(), G3D::Vector3::z, G3D::Vector3::zero(), and G3D::zz().
Referenced by frustum(), and getClipPlanes().
getClipPlanes()
void G3D::GCamera::getClipPlanes (const Rect2D & viewport, Array< Plane > & outClip) const
Returns the clipping planes of the frustum, in world space.
The planes have normals facing into the view frustum.
The plane order is guaranteed to be: Near, Right, Left, Top, Bottom, [Far]
If the far plane is at infinity, the resulting array will have 5 planes, otherwise there will be 6.
The viewport is used only to determine the aspect ratio of the screen; the absolute dimensions and xy values don't matter.
Definition at line 272 of file GCamera.cpp.
{
     Frustum fr;
     frustum(viewport, fr);
     clip.resize(fr.faceArray.size(), DONT_SHRINK_UNDERLYING_ARRAY);
     for (int f = 0; f < clip.size(); ++f) {
         clip[f] = fr.faceArray[f].plane;
     }
 }
References G3D::DONT_SHRINK_UNDERLYING_ARRAY, f(), G3D::GCamera::Frustum::faceArray, frustum(), G3D::Array< T, MIN_ELEMENTS >::resize(), and G3D::Array< T, MIN_ELEMENTS >::size().
getCoordinateFrame()
void G3D::GCamera::getCoordinateFrame (CoordinateFrame & c) const
Sets c to the camera's coordinate frame
Definition at line 96 of file GCamera.cpp.
{
     c = m_cframe;
 }
References mpq::c, and m_cframe.
getFarViewportCorners()
void G3D::GCamera::getFarViewportCorners (const class Rect2D & viewport, Vector3 & outUR, Vector3 & outUL, Vector3 & outLL, Vector3 & outLR) const
Returns the world space 3D viewport corners. These are at the Far clipping plane. The corners are constructed from the nearPlaneZ, farPlaneZ, viewportWidth, and viewportHeight. "left" and "right" are from the GCamera's perspective.
Definition at line 445 of file GCamera.cpp.
{
     // Must be kept in sync with getFrustum()
     const float w = viewportWidth(viewport) * m_farPlaneZ / m_nearPlaneZ;
     const float h = viewportHeight(viewport) * m_farPlaneZ / m_nearPlaneZ;
     const float z = m_farPlaneZ;
     // Compute the points
     outUR = Vector3( w/2,  h/2, z);
     outUL = Vector3(-w/2,  h/2, z);
     outLL = Vector3(-w/2, -h/2, z);
     outLR = Vector3( w/2, -h/2, z);
     // Take to world space
     outUR = m_cframe.pointToWorldSpace(outUR);
     outUL = m_cframe.pointToWorldSpace(outUL);
     outLR = m_cframe.pointToWorldSpace(outLR);
     outLL = m_cframe.pointToWorldSpace(outLL);
 }
References m_cframe, m_farPlaneZ, m_nearPlaneZ, G3D::CoordinateFrame::pointToWorldSpace(), viewportHeight(), viewportWidth(), and G3D::z.
getFieldOfView()
void G3D::GCamera::getFieldOfView (float & angle, FOVDirection & direction) const inline
Returns the current full field of view angle (from the left side of the viewport to the right side) and direction
Definition at line 178 of file GCamera.h.
{
         angle = m_fieldOfView;
         direction = m_direction;
     }
References m_direction, and m_fieldOfView.
getNearViewportCorners()
void G3D::GCamera::getNearViewportCorners (const class Rect2D & viewport, Vector3 & outUR, Vector3 & outUL, Vector3 & outLL, Vector3 & outLR) const
Returns the world space 3D viewport corners. These are at the near clipping plane. The corners are constructed from the nearPlaneZ, viewportWidth, and viewportHeight. "left" and "right" are from the GCamera's perspective.
Definition at line 420 of file GCamera.cpp.
{
     // Must be kept in sync with getFrustum()
     const float w  = viewportWidth(viewport) / 2.0f;
     const float h  = viewportHeight(viewport) / 2.0f;
     const float z  = nearPlaneZ();
     // Compute the points
     outUR = Vector3( w,  h, z);
     outUL = Vector3(-w,  h, z);
     outLL = Vector3(-w, -h, z);
     outLR = Vector3( w, -h, z);
     // Take to world space
     outUR = m_cframe.pointToWorldSpace(outUR);
     outUL = m_cframe.pointToWorldSpace(outUL);
     outLR = m_cframe.pointToWorldSpace(outLR);
     outLL = m_cframe.pointToWorldSpace(outLL);
 }
References m_cframe, nearPlaneZ(), G3D::CoordinateFrame::pointToWorldSpace(), viewportHeight(), viewportWidth(), and G3D::z.
getProjectPixelMatrix()
void G3D::GCamera::getProjectPixelMatrix (const Rect2D & viewport, Matrix4 & P) const
Sets P equal to the matrix that transforms points to pixel coordinates on the given viewport. A point correspoinding to the top-left corner of the viewport in camera space will transform to viewport.x0y0() and the bottom-right to viewport.x1y1().
Definition at line 169 of file GCamera.cpp.
{
     getProjectUnitMatrix(viewport, P);
     float screenWidth  = viewport.width();
     float screenHeight = viewport.height();
     float sx = screenWidth / 2.0;
     float sy = screenHeight / 2.0;
     P = Matrix4(sx, 0, 0, sx + viewport.x0() - m_pixelOffset.x,
                 0, -sy, 0, sy + viewport.y0() + m_pixelOffset.y,
                 0, 0,  1, 0,
                 0, 0,  0, 1) * P;
 }
References getProjectUnitMatrix(), G3D::Rect2D::height(), m_pixelOffset, P, G3D::Rect2D::width(), G3D::Vector2::x, G3D::Rect2D::x0(), G3D::Vector2::y, and G3D::Rect2D::y0().
getProjectUnitMatrix()
void G3D::GCamera::getProjectUnitMatrix (const Rect2D & viewport, Matrix4 & P) const
Sets P equal to the camera's projection matrix. This is the matrix that maps points to the homogeneous clip cube that varies from -1 to 1 on all axes. The projection matrix does not include the camera transform.
This is the matrix that a RenderDevice (or OpenGL) uses as the projection matrix.
See also
RenderDevice::setProjectionAndCameraMatrix, RenderDevice::setProjectionMatrix, Matrix4::perspectiveProjection
Definition at line 184 of file GCamera.cpp.
{
     float screenWidth  = viewport.width();
     float screenHeight = viewport.height();
     float r, l, t, b, n, f, x, y;
     float s = 1.0f;
     if (m_direction == VERTICAL) {
         y = -m_nearPlaneZ * tan(m_fieldOfView / 2);
         x = y * (screenWidth / screenHeight);
         s = screenHeight;
     } else { //m_direction == HORIZONTAL
         x = -m_nearPlaneZ * tan(m_fieldOfView / 2);
         y = x * (screenHeight / screenWidth);
         s = screenWidth;
     }
     n = -m_nearPlaneZ;
     f = -m_farPlaneZ;
     r = x  - m_pixelOffset.x/s;
     l = -x - m_pixelOffset.x/s;
     t = y  + m_pixelOffset.y/s;
     b = -y + m_pixelOffset.y/s;
     P = Matrix4::perspectiveProjection(l, r, b, t, n, f);
 }
References b, f(), G3D::Rect2D::height(), mpq::l, m_direction, m_farPlaneZ, m_fieldOfView, m_nearPlaneZ, m_pixelOffset, P, G3D::Matrix4::perspectiveProjection(), tan, VERTICAL, G3D::Rect2D::width(), G3D::Vector2::x, G3D::x, G3D::Vector2::y, and G3D::y.
Referenced by getProjectPixelMatrix(), and projectUnit().
imagePlaneDepth()
float G3D::GCamera::imagePlaneDepth () const
Returns the image plane depth, assumes imagePlane is the same as the near clipping plane. returns a positive number.
Definition at line 114 of file GCamera.cpp.
{
     return -m_nearPlaneZ;
 }
References m_nearPlaneZ.
Referenced by serialize(), and worldToScreenSpaceArea().
lookAt()
void G3D::GCamera::lookAt (const Vector3 & position, const Vector3 & up = Vector3::unitY())
Rotate the camera in place to look at the target. Does not persistently look at that location when the camera moves; i.e., if you move the camera and still want it to look at the old target, you must call lookAt again after moving the camera.)
Definition at line 477 of file GCamera.cpp.
{
     m_cframe.lookAt(position, up);
 }
References G3D::CoordinateFrame::lookAt(), and m_cframe.
nearPlaneZ()
float G3D::GCamera::nearPlaneZ () const inline
Returns a negative z-value.
Definition at line 272 of file GCamera.h.
{
         return m_nearPlaneZ;
     }
References m_nearPlaneZ.
Referenced by getNearViewportCorners(), and serialize().
operator Any()
G3D::GCamera::operator Any () const
Definition at line 58 of file GCamera.cpp.
{
     Any any(Any::TABLE, "GCamera");
     any.set("fovDirection", std::string((m_direction == HORIZONTAL) ? "HORIZONTAL" : "VERTICAL"));
     any.set("fovDegrees", toDegrees(m_fieldOfView));
     any.set("nearPlaneZ", nearPlaneZ());
     any.set("farPlaneZ", farPlaneZ());
     any.set("coordinateFrame", coordinateFrame());
     any.set("pixelOffset", pixelOffset());
     return any;
 }
References G3D::any(), G3D::Any::TABLE, and G3D::toDegrees().
pixelOffset()
const Vector2& G3D::GCamera::pixelOffset () const inline
Definition at line 133 of file GCamera.h.
{
         return m_pixelOffset;
     }
References m_pixelOffset.
project()
Vector3 G3D::GCamera::project (const G3D::Vector3 & point, const class Rect2D & viewport) const
Projects a world space point onto a width x height screen. The returned coordinate uses pixmap addressing: x = right and y = down. The resulting z value is 0 at the near plane, 1 at the far plane, and is a linear compression of unit cube projection.
If the point is behind the camera, Vector3::inf() is returned.
Definition at line 223 of file GCamera.cpp.
{
     // Find the point in the homogeneous cube
     const Vector3& cube = projectUnit(point, viewport);
     return convertFromUnitToNormal(cube, viewport);
 }
References convertFromUnitToNormal(), and projectUnit().
projectUnit()
Vector3 G3D::GCamera::projectUnit (const G3D::Vector3 & point, const class Rect2D & viewport) const
Projects a world space point onto a unit cube. The resulting x,y,z values range between -1 and 1, where z is -1 at the near plane and 1 at the far plane and varies hyperbolically in between.
If the point is behind the camera, Vector3::inf() is returned.
Definition at line 213 of file GCamera.cpp.
{
     Matrix4 M;
     getProjectUnitMatrix(viewport, M);
     Vector4 cameraSpacePoint(coordinateFrame().pointToObjectSpace(point), 1.0f);
     const Vector4& screenSpacePoint = M * cameraSpacePoint;
     return Vector3(screenSpacePoint.xyz() / screenSpacePoint.w);
 }
References coordinateFrame(), getProjectUnitMatrix(), G3D::Vector4::w, and G3D::Vector4::xyz().
Referenced by project().
serialize()
void G3D::GCamera::serialize (class BinaryOutput & bo) const
Read and Write camera parameters
Definition at line 482 of file GCamera.cpp.
{
     bo.writeFloat32(m_fieldOfView);
     bo.writeFloat32(imagePlaneDepth());
     debugAssert(nearPlaneZ() < 0.0f);
     bo.writeFloat32(nearPlaneZ());
     debugAssert(farPlaneZ() < 0.0f);
     bo.writeFloat32(farPlaneZ());
     m_cframe.serialize(bo);
     bo.writeInt8(m_direction);
     m_pixelOffset.serialize(bo);
 }
References debugAssert, farPlaneZ(), imagePlaneDepth(), m_cframe, m_direction, m_fieldOfView, m_pixelOffset, nearPlaneZ(), G3D::CoordinateFrame::serialize(), G3D::Vector2::serialize(), G3D::BinaryOutput::writeFloat32(), and G3D::BinaryOutput::writeInt8().
setCoordinateFrame()
void G3D::GCamera::setCoordinateFrame (const CoordinateFrame & c)
Sets a new coordinate frame for the camera
Definition at line 101 of file GCamera.cpp.
{
     m_cframe = c;
 }
References mpq::c, and m_cframe.
Referenced by GCamera().
setFarPlaneZ()
void G3D::GCamera::setFarPlaneZ (float z) inline
Sets a new value for the far clipping plane Expects a negative value
Definition at line 287 of file GCamera.h.
{
         debugAssert(z < 0);
         m_farPlaneZ = z;
     }
References debugAssert, m_farPlaneZ, and G3D::z.
Referenced by GCamera().
setFieldOfView()
void G3D::GCamera::setFieldOfView (float edgeToEdgeAngleRadians, FOVDirection direction)
Sets the field of view, in radians. The initial angle is toRadians(55). Must specify the direction of the angle.
This is the full angle, i.e., from the left side of the viewport to the right side.
Definition at line 106 of file GCamera.cpp.
{
     debugAssert((angle < pi()) && (angle > 0));
     m_fieldOfView = angle;
     m_direction = dir;
 }
References debugAssert, m_direction, m_fieldOfView, and G3D::pi().
Referenced by GCamera().
setNearPlaneZ()
void G3D::GCamera::setNearPlaneZ (float z) inline
Sets a new value for the near clipping plane Expects a negative value
Definition at line 296 of file GCamera.h.
{
         debugAssert(z < 0);
         m_nearPlaneZ = z;
     }
References debugAssert, m_nearPlaneZ, and G3D::z.
Referenced by GCamera().
setPixelOffset()
void G3D::GCamera::setPixelOffset (const Vector2 & p) inline
Displacement from the upper left added in pixels in screen space to the projection matrix. This is useful for shifting the sampled location from the pixel center (OpenGL convention) to other locations, such as the upper-left.
Definition at line 129 of file GCamera.h.
{
         m_pixelOffset = p;
     }
References m_pixelOffset.
setPosition()
void G3D::GCamera::setPosition (const Vector3 & t)
Definition at line 472 of file GCamera.cpp.
{
     m_cframe.translation = t;
 }
References m_cframe, and G3D::CoordinateFrame::translation.
unproject()
Vector3 G3D::GCamera::unproject (const Vector3 & v, const Rect2D & viewport) const
Gives the world-space coordinates of screen space point v, where v.x is in pixels from the left, v.y is in pixels from the top, and v.z is on the range 0 (near plane) to 1 (far plane).
Definition at line 240 of file GCamera.cpp.
{
     const float n = m_nearPlaneZ;
     const float f = m_farPlaneZ;
     float z;
     if (-f >= finf()) {
         // Infinite far plane
         z = 1.0f / (((-1.0f / n) * v.z) + 1.0f / n);
     } else {
         z = 1.0f / ((((1.0f / f) - (1.0f / n)) * v.z) + 1.0f / n);
     }
     const Ray& ray = worldRay(v.x - m_pixelOffset.x, v.y - m_pixelOffset.y, viewport);
     // Find out where the ray reaches the specified depth.
     const Vector3& out = ray.origin() + ray.direction() * -z / (ray.direction().dot(m_cframe.lookVector()));
     return out;
 }
References G3D::Ray::direction(), G3D::Vector3::dot(), f(), G3D::finf(), G3D::CoordinateFrame::lookVector(), m_cframe, m_farPlaneZ, m_nearPlaneZ, m_pixelOffset, G3D::Ray::origin(), worldRay(), G3D::Vector2::x, G3D::Vector3::x, G3D::Vector2::y, G3D::Vector3::y, G3D::Vector3::z, and G3D::z.
Referenced by unprojectUnit().
unprojectUnit()
Vector3 G3D::GCamera::unprojectUnit (const Vector3 & v, const Rect2D & viewport) const
Gives the world-space coordinates of unit cube point v, where v varies from -1 to 1 on all axes. The unproject first transforms the point into a pixel location for the viewport, then calls unproject
Definition at line 232 of file GCamera.cpp.
{
     const Vector3& projectedPoint = convertFromUnitToNormal(v, viewport);
     return unproject(projectedPoint, viewport);
 }
References convertFromUnitToNormal(), and unproject().
viewportHeight()
float G3D::GCamera::viewportHeight (const class Rect2D & viewport) const
Returns the camera space height of the viewport at the near plane.
Definition at line 130 of file GCamera.cpp.
{
     // Compute the side of a square at the near plane based on our field of view
     float s = 2.0f * -m_nearPlaneZ * tan(m_fieldOfView * 0.5f);
     debugAssert(m_fieldOfView < toRadians(180));
     if (m_direction == HORIZONTAL) {
         s *= viewport.height() / viewport.width();
     }
     return s;
 }
References debugAssert, G3D::Rect2D::height(), HORIZONTAL, m_direction, m_fieldOfView, m_nearPlaneZ, tan, G3D::toRadians(), and G3D::Rect2D::width().
Referenced by frustum(), getFarViewportCorners(), getNearViewportCorners(), and worldRay().
viewportWidth()
float G3D::GCamera::viewportWidth (const class Rect2D & viewport) const
Returns the camera space width of the viewport at the near plane.
Definition at line 118 of file GCamera.cpp.
{
     // Compute the side of a square at the near plane based on our field of view
     float s = 2.0f * -m_nearPlaneZ * tan(m_fieldOfView * 0.5f);
     if (m_direction == VERTICAL) {
         s *= viewport.width() / viewport.height();
     }
     return s;
 }
References G3D::Rect2D::height(), m_direction, m_fieldOfView, m_nearPlaneZ, tan, VERTICAL, and G3D::Rect2D::width().
Referenced by frustum(), getFarViewportCorners(), getNearViewportCorners(), and worldRay().
worldRay()
Ray G3D::GCamera::worldRay (float x, float y, const class Rect2D & viewport) const
Returns the world space ray passing through the center of pixel (x, y) on the image plane. The pixel x and y axes are opposite the 3D object space axes: (0,0) is the upper left corner of the screen. They are in viewport coordinates, not screen coordinates.
The ray origin is at the origin. To start it at the image plane, move it forward by imagePlaneDepth/ray.direction.z
Integer (x, y) values correspond to the upper left corners of pixels. If you want to cast rays through pixel centers, add 0.5 to x and y.
Definition at line 143 of file GCamera.cpp.
{
     int screenWidth  = iFloor(viewport.width());
     int screenHeight = iFloor(viewport.height());
     Vector3 origin = m_cframe.translation;
     float cx = screenWidth  / 2.0f;
     float cy = screenHeight / 2.0f;
     float vw = viewportWidth(viewport);
     float vh = viewportHeight(viewport);
     Vector3 direction = Vector3( (x - cx) * vw / screenWidth,
                             -(y - cy) * vh / screenHeight,
                              m_nearPlaneZ);
     direction = m_cframe.vectorToWorldSpace(direction);
     // Normalize the direction (we didn't do it before)
     direction = direction.direction();
     return Ray::fromOriginAndDirection(origin, direction);
 }
References G3D::Vector3::direction(), G3D::Ray::fromOriginAndDirection(), G3D::Rect2D::height(), G3D::iFloor(), m_cframe, m_nearPlaneZ, G3D::CoordinateFrame::translation, G3D::CoordinateFrame::vectorToWorldSpace(), viewportHeight(), viewportWidth(), G3D::Rect2D::width(), G3D::x, and G3D::y.
Referenced by unproject().
worldToScreenSpaceArea()
float G3D::GCamera::worldToScreenSpaceArea (float area, float z, const class Rect2D & viewport) const
Returns the pixel area covered by a shape of the given world space area at the given z value (z must be negative).
Definition at line 263 of file GCamera.cpp.
{
     (void)viewport;
     if (z >= 0) {
         return finf();
     }
     return area * (float)square(imagePlaneDepth() / z);
 }
References G3D::finf(), imagePlaneDepth(), G3D::square(), and G3D::z.
Member Data Documentation
m_cframe
CoordinateFrame G3D::GCamera::m_cframe private
Stores the camera's location and orientation
Definition at line 65 of file GCamera.h.
Referenced by coordinateFrame(), deserialize(), frustum(), GCamera(), getCoordinateFrame(), getFarViewportCorners(), getNearViewportCorners(), lookAt(), serialize(), setCoordinateFrame(), setPosition(), unproject(), and worldRay().
m_direction
FOVDirection G3D::GCamera::m_direction private
Horizontal or Vertical
Definition at line 68 of file GCamera.h.
Referenced by deserialize(), frustum(), GCamera(), getFieldOfView(), getProjectUnitMatrix(), serialize(), setFieldOfView(), viewportHeight(), and viewportWidth().
m_farPlaneZ
float G3D::GCamera::m_farPlaneZ private
Negative
Definition at line 62 of file GCamera.h.
Referenced by deserialize(), farPlaneZ(), frustum(), GCamera(), getFarViewportCorners(), getProjectUnitMatrix(), setFarPlaneZ(), and unproject().
m_fieldOfView
float G3D::GCamera::m_fieldOfView private
Full field of view (in radians)
Definition at line 56 of file GCamera.h.
Referenced by deserialize(), frustum(), GCamera(), getFieldOfView(), getProjectUnitMatrix(), serialize(), setFieldOfView(), viewportHeight(), and viewportWidth().
m_nearPlaneZ
float G3D::GCamera::m_nearPlaneZ private
Clipping plane, not imaging plane. Negative numbers.
Definition at line 59 of file GCamera.h.
Referenced by deserialize(), frustum(), GCamera(), getFarViewportCorners(), getProjectUnitMatrix(), imagePlaneDepth(), nearPlaneZ(), setNearPlaneZ(), unproject(), viewportHeight(), viewportWidth(), and worldRay().
m_pixelOffset
Vector2 G3D::GCamera::m_pixelOffset private
Definition at line 70 of file GCamera.h.
Referenced by deserialize(), GCamera(), getProjectPixelMatrix(), getProjectUnitMatrix(), pixelOffset(), serialize(), setPixelOffset(), and unproject().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/GCamera.h
deps/g3dlite/source/GCamera.cpp