Azerotcore-wotlk: formatter< std::chrono::duration< Rep, Period >, Char >::spec_handler Struct Reference
formatter< std::chrono::duration< Rep, Period >, Char >::spec_handler Struct Reference
Public Member Functions
template<typename Id >
FMT_CONSTEXPR arg_ref_type make_arg_ref (Id arg_id)
FMT_CONSTEXPR arg_ref_type make_arg_ref (basic_string_view< Char > arg_id)
FMT_CONSTEXPR arg_ref_type make_arg_ref (detail::auto_id)
void on_error (const char *msg)
FMT_CONSTEXPR void on_fill (basic_string_view< Char > fill)
FMT_CONSTEXPR void on_align (align_t align)
FMT_CONSTEXPR void on_width (int width)
FMT_CONSTEXPR void on_precision (int _precision)
FMT_CONSTEXPR void end_precision ()
template<typename Id >
FMT_CONSTEXPR void on_dynamic_width (Id arg_id)
template<typename Id >
FMT_CONSTEXPR void on_dynamic_precision (Id arg_id)
Public Attributes
formatter & f
basic_format_parse_context< Char > & context
basic_string_view< Char > format_str
Detailed Description
template<typename Rep, typename Period, typename Char>
struct formatter< std::chrono::duration< Rep, Period >, Char >::spec_handler
Definition at line 1200 of file chrono.h.
Member Function Documentation
end_precision()
template<typename Rep , typename Period , typename Char > FMT_CONSTEXPR void formatter< std::chrono::duration< Rep, Period >, Char >::spec_handler::end_precision () inline
Definition at line 1228 of file chrono.h.
 {}
make_arg_ref() [1/3]
template<typename Rep , typename Period , typename Char > FMT_CONSTEXPR arg_ref_type formatter< std::chrono::duration< Rep, Period >, Char >::spec_handler::make_arg_ref (basic_string_view< Char > arg_id) inline
Definition at line 1210 of file chrono.h.
{
       context.check_arg_id(arg_id);
       return arg_ref_type(arg_id);
     }
References basic_format_parse_context< Char, ErrorHandler >::check_arg_id().
make_arg_ref() [2/3]
template<typename Rep , typename Period , typename Char > FMT_CONSTEXPR arg_ref_type formatter< std::chrono::duration< Rep, Period >, Char >::spec_handler::make_arg_ref (detail::auto_id) inline
Definition at line 1215 of file chrono.h.
{
       return arg_ref_type(context.next_arg_id());
     }
References basic_format_parse_context< Char, ErrorHandler >::next_arg_id().
make_arg_ref() [3/3]
template<typename Rep , typename Period , typename Char > template<typename Id > FMT_CONSTEXPR arg_ref_type formatter< std::chrono::duration< Rep, Period >, Char >::spec_handler::make_arg_ref (Id arg_id) inline
Definition at line 1205 of file chrono.h.
{
       context.check_arg_id(arg_id);
       return arg_ref_type(arg_id);
     }
References basic_format_parse_context< Char, ErrorHandler >::check_arg_id().
on_align()
template<typename Rep , typename Period , typename Char > FMT_CONSTEXPR void formatter< std::chrono::duration< Rep, Period >, Char >::spec_handler::on_align (align_t align) inline
Definition at line 1223 of file chrono.h.
 { f.specs.align = align; }
References f().
on_dynamic_precision()
template<typename Rep , typename Period , typename Char > template<typename Id > FMT_CONSTEXPR void formatter< std::chrono::duration< Rep, Period >, Char >::spec_handler::on_dynamic_precision (Id arg_id) inline
Definition at line 1234 of file chrono.h.
{
       f.precision_ref = make_arg_ref(arg_id);
     }
References f().
on_dynamic_width()
template<typename Rep , typename Period , typename Char > template<typename Id > FMT_CONSTEXPR void formatter< std::chrono::duration< Rep, Period >, Char >::spec_handler::on_dynamic_width (Id arg_id) inline
Definition at line 1230 of file chrono.h.
{
       f.width_ref = make_arg_ref(arg_id);
     }
References f().
on_error()
template<typename Rep , typename Period , typename Char > void formatter< std::chrono::duration< Rep, Period >, Char >::spec_handler::on_error (const char * msg) inline
Definition at line 1219 of file chrono.h.
 { FMT_THROW(format_error(msg)); }
References FMT_THROW.
on_fill()
template<typename Rep , typename Period , typename Char > FMT_CONSTEXPR void formatter< std::chrono::duration< Rep, Period >, Char >::spec_handler::on_fill (basic_string_view< Char > fill) inline
Definition at line 1220 of file chrono.h.
{
       f.specs.fill = fill;
     }
References f(), and fill().
on_precision()
template<typename Rep , typename Period , typename Char > FMT_CONSTEXPR void formatter< std::chrono::duration< Rep, Period >, Char >::spec_handler::on_precision (int _precision) inline
Definition at line 1225 of file chrono.h.
{
       f.precision = _precision;
     }
References f().
on_width()
template<typename Rep , typename Period , typename Char > FMT_CONSTEXPR void formatter< std::chrono::duration< Rep, Period >, Char >::spec_handler::on_width (int width) inline
Definition at line 1224 of file chrono.h.
 { f.specs.width = width; }
References f(), and width.
Member Data Documentation
context
template<typename Rep , typename Period , typename Char > basic_format_parse_context<Char>& formatter< std::chrono::duration< Rep, Period >, Char >::spec_handler::context
Definition at line 1202 of file chrono.h.
f
template<typename Rep , typename Period , typename Char > formatter& formatter< std::chrono::duration< Rep, Period >, Char >::spec_handler::f
Definition at line 1201 of file chrono.h.
format_str
template<typename Rep , typename Period , typename Char > basic_string_view<Char> formatter< std::chrono::duration< Rep, Period >, Char >::spec_handler::format_str
Definition at line 1203 of file chrono.h.
The documentation for this struct was generated from the following file:
deps/fmt/include/fmt/chrono.h