Azerotcore-wotlk: adyen_the_lightbringer Class Reference
adyen_the_lightbringer Class Reference
Classes
struct adyen_the_lightbringerAI
Public Member Functions
adyen_the_lightbringer ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 246 of file zone_netherstorm.cpp.
Constructor & Destructor Documentation
adyen_the_lightbringer()
adyen_the_lightbringer::adyen_the_lightbringer () inline
Definition at line 249 of file zone_netherstorm.cpp.
 : CreatureScript("adyen_the_lightbringer") { }
Member Function Documentation
GetAI()
CreatureAI* adyen_the_lightbringer::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 378 of file zone_netherstorm.cpp.
     {
         return new adyen_the_lightbringerAI(creature);
     }
OnGossipHello()
bool adyen_the_lightbringer::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 251 of file zone_netherstorm.cpp.
     {
         if (player->GetQuestStatus(DEATHBLOW_TO_THE_LEGION) == QUEST_STATUS_INCOMPLETE)
             AddGossipItemFor(player, ADYEN_THE_LIGHTBRINGER, 0, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
         SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), ADYEN_THE_LIGHTBRINGER, DEATHBLOW_TO_THE_LEGION, Player::GetGossipTextId(), Object::GetGUID(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_SENDER_MAIN, QUEST_STATUS_INCOMPLETE, and SendGossipMenuFor().
OnGossipSelect()
bool adyen_the_lightbringer::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 261 of file zone_netherstorm.cpp.
     {
         ClearGossipMenuFor(player);
         if (action == GOSSIP_ACTION_INFO_DEF + 1)
         {
             CloseGossipMenuFor(player);
             creature->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
             creature->AI()->DoAction(EVENT_START_PLAYER_READY);
             if (Creature* orelis = creature->FindNearestCreature(EXARCH_ORELIS, 15.0f, true))
                 orelis->AI()->DoAction(EVENT_ORELIS_WALK);
             if (Creature* karja = creature->FindNearestCreature(ANCHORITE_KARJA, 15.0f, true))
                 karja->AI()->DoAction(EVENT_KARJA_WALK);
             if (Creature* socrethar = creature->FindNearestCreature(SOCRETHAR, 500.0f, true))
                 socrethar->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_DISABLE_MOVE);
         }
         return true;
     }
References Creature::AI(), ANCHORITE_KARJA, ClearGossipMenuFor(), CloseGossipMenuFor(), UnitAI::DoAction(), EVENT_KARJA_WALK, EVENT_ORELIS_WALK, EVENT_START_PLAYER_READY, EXARCH_ORELIS, WorldObject::FindNearestCreature(), GOSSIP_ACTION_INFO_DEF, Object::RemoveFlag(), SOCRETHAR, UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE, UNIT_FLAG_NON_ATTACKABLE, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
The documentation for this class was generated from the following file:
src/server/scripts/Outland/zone_netherstorm.cpp