Azerotcore-wotlk: Acore::UnitListSearcher< Check > Struct Template Reference
Acore::UnitListSearcher< Check > Struct Template Reference
#include <GridNotifiers.h>
Public Member Functions
UnitListSearcher (WorldObject const *searcher, std::list< Unit * > &objects, Check &check)
void Visit (PlayerMapType &m)
void Visit (CreatureMapType &m)
template<class NOT_INTERESTED >
void Visit (GridRefMgr< NOT_INTERESTED > &)
Public Attributes
uint32 i_phaseMask
std::list< Unit * > & i_objects
Check & i_check
Detailed Description
template<class Check>
struct Acore::UnitListSearcher< Check >
Definition at line 391 of file GridNotifiers.h.
Constructor & Destructor Documentation
UnitListSearcher()
template<class Check > Acore::UnitListSearcher< Check >::UnitListSearcher (WorldObject const * searcher, std::list< Unit * > & objects, Check & check) inline
Definition at line 397 of file GridNotifiers.h.
             : i_phaseMask(searcher->GetPhaseMask()), i_objects(objects), i_check(check) {}
Member Function Documentation
Visit() [1/3]
template<class Check > void Acore::UnitListSearcher< Check >::Visit (CreatureMapType & m)
Definition at line 423 of file GridNotifiersImpl.h.
 {
     for (CreatureMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
         if (itr->GetSource()->InSamePhase(i_phaseMask))
             if (i_check(itr->GetSource()))
                 i_objects.push_back(itr->GetSource());
 }
References GridRefMgr< OBJECT >::begin(), and GridRefMgr< OBJECT >::end().
Visit() [2/3]
template<class Check > template<class NOT_INTERESTED > void Acore::UnitListSearcher< Check >::Visit (GridRefMgr< NOT_INTERESTED > &) inline
Definition at line 403 of file GridNotifiers.h.
 {}
Visit() [3/3]
template<class Check > void Acore::UnitListSearcher< Check >::Visit (PlayerMapType & m)
Definition at line 414 of file GridNotifiersImpl.h.
 {
     for (PlayerMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
         if (itr->GetSource()->InSamePhase(i_phaseMask))
             if (i_check(itr->GetSource()))
                 i_objects.push_back(itr->GetSource());
 }
References GridRefMgr< OBJECT >::begin(), and GridRefMgr< OBJECT >::end().
Member Data Documentation
i_check
template<class Check > Check& Acore::UnitListSearcher< Check >::i_check
Definition at line 395 of file GridNotifiers.h.
i_objects
template<class Check > std::list<Unit*>& Acore::UnitListSearcher< Check >::i_objects
Definition at line 394 of file GridNotifiers.h.
i_phaseMask
template<class Check > uint32 Acore::UnitListSearcher< Check >::i_phaseMask
Definition at line 393 of file GridNotifiers.h.
The documentation for this struct was generated from the following files:
src/server/game/Grids/Notifiers/GridNotifiers.h
src/server/game/Grids/Notifiers/GridNotifiersImpl.h