Azerotcore-wotlk: dtNodePool Class Reference
dtNodePool Class Reference
#include <DetourNode.h>
Public Member Functions
dtNodePool (int maxNodes, int hashSize)
~dtNodePool ()
void clear ()
dtNode * getNode (dtPolyRef id, unsigned char state=0)
dtNode * findNode (dtPolyRef id, unsigned char state)
unsigned int findNodes (dtPolyRef id, dtNode **nodes, const int maxNodes)
unsigned int getNodeIdx (const dtNode *node) const
dtNode * getNodeAtIdx (unsigned int idx)
const dtNode * getNodeAtIdx (unsigned int idx) const
int getMemUsed () const
int getMaxNodes () const
int getHashSize () const
dtNodeIndex getFirst (int bucket) const
dtNodeIndex getNext (int i) const
int getNodeCount () const
Private Member Functions
dtNodePool (const dtNodePool &)
dtNodePool & operator= (const dtNodePool &)
Private Attributes
dtNode * m_nodes
dtNodeIndex * m_first
dtNodeIndex * m_next
const int m_maxNodes
const int m_hashSize
int m_nodeCount
Detailed Description
Definition at line 49 of file DetourNode.h.
Constructor & Destructor Documentation
dtNodePool() [1/2]
dtNodePool::dtNodePool (int maxNodes, int hashSize)
Definition at line 51 of file DetourNode.cpp.
                                                  :
     m_nodes(0),
     m_first(0),
     m_next(0),
     m_maxNodes(maxNodes),
     m_hashSize(hashSize),
     m_nodeCount(0)
 {
     dtAssert(dtNextPow2(m_hashSize) == (unsigned int)m_hashSize);
     // pidx is special as 0 means "none" and 1 is the first node. For that reason
     // we have 1 fewer nodes available than the number of values it can contain.
     dtAssert(m_maxNodes > 0 && m_maxNodes <= DT_NULL_IDX && m_maxNodes <= (1 << DT_NODE_PARENT_BITS) - 1);
     m_nodes = (dtNode*)dtAlloc(sizeof(dtNode)*m_maxNodes, DT_ALLOC_PERM);
     m_next = (dtNodeIndex*)dtAlloc(sizeof(dtNodeIndex)*m_maxNodes, DT_ALLOC_PERM);
     m_first = (dtNodeIndex*)dtAlloc(sizeof(dtNodeIndex)*hashSize, DT_ALLOC_PERM);
     dtAssert(m_nodes);
     dtAssert(m_next);
     dtAssert(m_first);
     memset(m_first, 0xff, sizeof(dtNodeIndex)*m_hashSize);
     memset(m_next, 0xff, sizeof(dtNodeIndex)*m_maxNodes);
 }
References DT_ALLOC_PERM, DT_NODE_PARENT_BITS, DT_NULL_IDX, dtAlloc(), dtAssert, dtNextPow2(), m_first, m_hashSize, m_maxNodes, m_next, m_nodes, and memset.
~dtNodePool()
dtNodePool::~dtNodePool ()
Definition at line 76 of file DetourNode.cpp.
 {
     dtFree(m_nodes);
     dtFree(m_next);
     dtFree(m_first);
 }
References dtFree(), m_first, m_next, and m_nodes.
Referenced by dtNavMeshQuery::init(), and dtNavMeshQuery::~dtNavMeshQuery().
dtNodePool() [2/2]
dtNodePool::dtNodePool (const dtNodePool &) private
Member Function Documentation
clear()
void dtNodePool::clear ()
Definition at line 83 of file DetourNode.cpp.
 {
     memset(m_first, 0xff, sizeof(dtNodeIndex)*m_hashSize);
     m_nodeCount = 0;
 }
References m_first, m_hashSize, m_nodeCount, and memset.
Referenced by dtNavMeshQuery::findDistanceToWall(), dtNavMeshQuery::findLocalNeighbourhood(), dtNavMeshQuery::findPath(), dtNavMeshQuery::findPolysAroundCircle(), dtNavMeshQuery::findPolysAroundShape(), dtNavMeshQuery::findRandomPointAroundCircle(), dtNavMeshQuery::init(), dtNavMeshQuery::initSlicedFindPath(), and dtNavMeshQuery::moveAlongSurface().
findNode()
dtNode * dtNodePool::findNode (dtPolyRef id, unsigned char state)
Definition at line 108 of file DetourNode.cpp.
 {
     unsigned int bucket = dtHashRef(id) & (m_hashSize-1);
     dtNodeIndex i = m_first[bucket];
     while (i != DT_NULL_IDX)
     {
         if (m_nodes[i].id == id && m_nodes[i].state == state)
             return &m_nodes[i];
         i = m_next[i];
     }
     return 0;
 }
References DT_NULL_IDX, dtHashRef(), m_first, m_hashSize, m_next, and m_nodes.
findNodes()
unsigned int dtNodePool::findNodes (dtPolyRef id, dtNode ** nodes, const int maxNodes)
Definition at line 89 of file DetourNode.cpp.
 {
     int n = 0;
     unsigned int bucket = dtHashRef(id) & (m_hashSize-1);
     dtNodeIndex i = m_first[bucket];
     while (i != DT_NULL_IDX)
     {
         if (m_nodes[i].id == id)
         {
             if (n >= maxNodes)
                 return n;
             nodes[n++] = &m_nodes[i];
         }
         i = m_next[i];
     }
     return n;
 }
References DT_NULL_IDX, dtHashRef(), m_first, m_hashSize, m_next, and m_nodes.
Referenced by dtNavMeshQuery::finalizeSlicedFindPathPartial(), dtNavMeshQuery::getPathFromDijkstraSearch(), and dtNavMeshQuery::isInClosedList().
getFirst()
dtNodeIndex dtNodePool::getFirst (int bucket) const inline
Definition at line 91 of file DetourNode.h.
 { return m_first[bucket]; }
References m_first.
getHashSize()
int dtNodePool::getHashSize () const inline
Definition at line 90 of file DetourNode.h.
 { return m_hashSize; }
References m_hashSize.
getMaxNodes()
int dtNodePool::getMaxNodes () const inline
Definition at line 88 of file DetourNode.h.
 { return m_maxNodes; }
References m_maxNodes.
Referenced by dtNavMeshQuery::init().
getMemUsed()
int dtNodePool::getMemUsed () const inline
Definition at line 80 of file DetourNode.h.
     {
         return sizeof(*this) +
             sizeof(dtNode)*m_maxNodes +
             sizeof(dtNodeIndex)*m_maxNodes +
             sizeof(dtNodeIndex)*m_hashSize;
     }
References m_hashSize, and m_maxNodes.
getNext()
dtNodeIndex dtNodePool::getNext (int i) const inline
Definition at line 92 of file DetourNode.h.
 { return m_next[i]; }
References m_next.
getNode()
dtNode * dtNodePool::getNode (dtPolyRef id, unsigned char state = 0)
Definition at line 121 of file DetourNode.cpp.
 {
     unsigned int bucket = dtHashRef(id) & (m_hashSize-1);
     dtNodeIndex i = m_first[bucket];
     dtNode* node = 0;
     while (i != DT_NULL_IDX)
     {
         if (m_nodes[i].id == id && m_nodes[i].state == state)
             return &m_nodes[i];
         i = m_next[i];
     }
     if (m_nodeCount >= m_maxNodes)
         return 0;
     i = (dtNodeIndex)m_nodeCount;
     m_nodeCount++;
     // Init node
     node = &m_nodes[i];
     node->pidx = 0;
     node->cost = 0;
     node->total = 0;
     node->id = id;
     node->state = state;
     node->flags = 0;
     m_next[i] = m_first[bucket];
     m_first[bucket] = i;
     return node;
 }
References dtNode::cost, DT_NULL_IDX, dtHashRef(), dtNode::flags, dtNode::id, m_first, m_hashSize, m_maxNodes, m_next, m_nodeCount, m_nodes, dtNode::pidx, dtNode::state, and dtNode::total.
Referenced by dtNavMeshQuery::findDistanceToWall(), dtNavMeshQuery::findLocalNeighbourhood(), dtNavMeshQuery::findPath(), dtNavMeshQuery::findPolysAroundCircle(), dtNavMeshQuery::findPolysAroundShape(), dtNavMeshQuery::findRandomPointAroundCircle(), dtNavMeshQuery::initSlicedFindPath(), dtNavMeshQuery::moveAlongSurface(), and dtNavMeshQuery::updateSlicedFindPath().
getNodeAtIdx() [1/2]
dtNode* dtNodePool::getNodeAtIdx (unsigned int idx) inline
Definition at line 68 of file DetourNode.h.
     {
         if (!idx) return 0;
         return &m_nodes[idx - 1];
     }
References idx, and m_nodes.
Referenced by dtNavMeshQuery::finalizeSlicedFindPath(), dtNavMeshQuery::finalizeSlicedFindPathPartial(), dtNavMeshQuery::findDistanceToWall(), dtNavMeshQuery::findPath(), dtNavMeshQuery::findPolysAroundCircle(), dtNavMeshQuery::findPolysAroundShape(), dtNavMeshQuery::findRandomPointAroundCircle(), dtNavMeshQuery::getPathToNode(), dtNavMeshQuery::moveAlongSurface(), and dtNavMeshQuery::updateSlicedFindPath().
getNodeAtIdx() [2/2]
const dtNode* dtNodePool::getNodeAtIdx (unsigned int idx) const inline
Definition at line 74 of file DetourNode.h.
     {
         if (!idx) return 0;
         return &m_nodes[idx - 1];
     }
References idx, and m_nodes.
getNodeCount()
int dtNodePool::getNodeCount () const inline
Definition at line 93 of file DetourNode.h.
 { return m_nodeCount; }
References m_nodeCount.
getNodeIdx()
unsigned int dtNodePool::getNodeIdx (const dtNode * node) const inline
Definition at line 62 of file DetourNode.h.
     {
         if (!node) return 0;
         return (unsigned int)(node - m_nodes) + 1;
     }
References m_nodes.
Referenced by dtNavMeshQuery::finalizeSlicedFindPath(), dtNavMeshQuery::finalizeSlicedFindPathPartial(), dtNavMeshQuery::findDistanceToWall(), dtNavMeshQuery::findLocalNeighbourhood(), dtNavMeshQuery::findPath(), dtNavMeshQuery::findPolysAroundCircle(), dtNavMeshQuery::findPolysAroundShape(), dtNavMeshQuery::findRandomPointAroundCircle(), dtNavMeshQuery::moveAlongSurface(), and dtNavMeshQuery::updateSlicedFindPath().
operator=()
dtNodePool& dtNodePool::operator= (const dtNodePool &) private
Member Data Documentation
m_first
dtNodeIndex* dtNodePool::m_first private
Definition at line 101 of file DetourNode.h.
Referenced by clear(), dtNodePool(), findNode(), findNodes(), getFirst(), getNode(), and ~dtNodePool().
m_hashSize
const int dtNodePool::m_hashSize private
Definition at line 104 of file DetourNode.h.
Referenced by clear(), dtNodePool(), findNode(), findNodes(), getHashSize(), getMemUsed(), and getNode().
m_maxNodes
const int dtNodePool::m_maxNodes private
Definition at line 103 of file DetourNode.h.
Referenced by dtNodePool(), getMaxNodes(), getMemUsed(), and getNode().
m_next
dtNodeIndex* dtNodePool::m_next private
Definition at line 102 of file DetourNode.h.
Referenced by dtNodePool(), findNode(), findNodes(), getNext(), getNode(), and ~dtNodePool().
m_nodeCount
int dtNodePool::m_nodeCount private
Definition at line 105 of file DetourNode.h.
Referenced by clear(), getNode(), and getNodeCount().
m_nodes
dtNode* dtNodePool::m_nodes private
Definition at line 100 of file DetourNode.h.
Referenced by dtNodePool(), findNode(), findNodes(), getNode(), getNodeAtIdx(), getNodeIdx(), and ~dtNodePool().
The documentation for this class was generated from the following files:
deps/recastnavigation/Detour/Include/DetourNode.h
deps/recastnavigation/Detour/Source/DetourNode.cpp