Azerotcore-wotlk: npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI Struct Reference
npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI Struct Reference
Public Member Functions
npc_dark_iron_attack_generatorAI (Creature *creature)
void Reset () override
void MoveInLineOfSight (Unit *) override
void EnterCombat (Unit *) override
void SpellHit (Unit *caster, const SpellInfo *spellInfo) override
void UpdateAI (uint32 diff) override
void FinishEventDueToLoss ()
void FinishAttackDueToWin ()
void PrepareEvent ()
bool AllowStart ()
Creature * GetRandomBartender ()
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
SummonList summons
uint32 kegCounter
uint32 guzzlerCounter
uint8 thrown
GuidVector revelerGUIDs
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 345 of file brewfest.cpp.
Constructor & Destructor Documentation
npc_dark_iron_attack_generatorAI()
npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::npc_dark_iron_attack_generatorAI (Creature * creature) inline
Definition at line 347 of file brewfest.cpp.
                                                              : ScriptedAI(creature), summons(me)
         {
         }
Member Function Documentation
AllowStart()
bool npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::AllowStart () inline
Definition at line 569 of file brewfest.cpp.
         {
             time_t curtime = time(nullptr);
             tm strDate;
             localtime_r(&curtime, &strDate);
             if (strDate.tm_min == 0 || strDate.tm_min == 30)
                 return true;
             return false;
         }
References localtime_r().
Referenced by UpdateAI().
EnterCombat()
void npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 379 of file brewfest.cpp.
 {}
FinishAttackDueToWin()
void npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::FinishAttackDueToWin () inline
Definition at line 489 of file brewfest.cpp.
         {
             if (Creature* herald = me->FindNearestCreature(NPC_DARK_IRON_HERALD, 100.0f))
             {
                 char amount[500];
                 sprintf(amount, "RETREAT!! We've already lost %u and we can't afford to lose any more!!", guzzlerCounter);
                 herald->Yell(amount, LANG_UNIVERSAL);
             }
             me->CastSpell(me, (me->GetMapId() == 1 ? SPELL_SUMMON_PLANS_H : SPELL_SUMMON_PLANS_A), true);
             Reset();
         }
References Unit::CastSpell(), WorldObject::FindNearestCreature(), WorldLocation::GetMapId(), guzzlerCounter, LANG_UNIVERSAL, ScriptedAI::me, NPC_DARK_IRON_HERALD, Reset(), SPELL_SUMMON_PLANS_A, SPELL_SUMMON_PLANS_H, and sprintf().
Referenced by UpdateAI().
FinishEventDueToLoss()
void npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::FinishEventDueToLoss () inline
Definition at line 476 of file brewfest.cpp.
         {
             if (Creature* herald = me->FindNearestCreature(NPC_DARK_IRON_HERALD, 100.0f))
             {
                 char amount[500];
                 sprintf(amount, "We did it boys! Now back to the Grim Guzzler and we'll drink to the %u that were injured!", guzzlerCounter);
                 herald->Yell(amount, LANG_UNIVERSAL);
             }
             Reset();
             events.RescheduleEvent(EVENT_CHECK_HOUR, 60000);
         }
References EVENT_CHECK_HOUR, WorldObject::FindNearestCreature(), guzzlerCounter, LANG_UNIVERSAL, ScriptedAI::me, NPC_DARK_IRON_HERALD, Reset(), and sprintf().
Referenced by SpellHit().
GetRandomBartender()
Creature* npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::GetRandomBartender () inline
Definition at line 581 of file brewfest.cpp.
         {
             uint32 entry = 0;
             switch (urand(0, 2))
             {
                 case 0:
                     entry = (me->GetMapId() == 1 ? NPC_NORMAL_DROHN : NPC_NORMAL_THUNDERBREW);
                     break;
                 case 1:
                     entry = (me->GetMapId() == 1 ? NPC_NORMAL_VOODOO : NPC_NORMAL_BARLEYBREW);
                     break;
                 case 2:
                     entry = NPC_NORMAL_GORDOK;
                     break;
             }
             return me->FindNearestCreature(entry, 100.0f);
         }
References WorldObject::FindNearestCreature(), WorldLocation::GetMapId(), ScriptedAI::me, NPC_NORMAL_BARLEYBREW, NPC_NORMAL_DROHN, NPC_NORMAL_GORDOK, NPC_NORMAL_THUNDERBREW, NPC_NORMAL_VOODOO, and urand().
Referenced by UpdateAI().
MoveInLineOfSight()
void npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 378 of file brewfest.cpp.
 {}
PrepareEvent()
void npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::PrepareEvent () inline
Definition at line 502 of file brewfest.cpp.
         {
             std::list<Creature*> revelers;
             GetCreatureListWithEntryInGrid(revelers, me, NPC_BREWFEST_REVELER, 100.f);
             for (Creature* reveler : revelers)
             {
                 revelerGUIDs.push_back(reveler->GetGUID());
                 reveler->SetRespawnDelay(MONTH);
                 reveler->AI()->SetData(0, me->GetMapId());
             }
             Creature* cr;
             if (me->GetMapId() == 1) // Kalimdor
             {
                 if ((cr = me->SummonCreature(NPC_DROHN_KEG, 1183.69f, -4315.15f, 21.1875f, 0.750492f)))
                 {
                     cr->SetReactState(REACT_PASSIVE);
                     summons.Summon(cr);
                     revelerGUIDs.push_back(cr->GetGUID());
                 }
                 if ((cr = me->SummonCreature(NPC_VOODOO_KEG, 1182.42f, -4272.45f, 21.1182f, -1.02974f)))
                 {
                     cr->SetReactState(REACT_PASSIVE);
                     summons.Summon(cr);
                     revelerGUIDs.push_back(cr->GetGUID());
                 }
                 if ((cr = me->SummonCreature(NPC_GORDOK_KEG, 1223.78f, -4296.48f, 21.1707f, -2.86234f)))
                 {
                     cr->SetReactState(REACT_PASSIVE);
                     summons.Summon(cr);
                     revelerGUIDs.push_back(cr->GetGUID());
                 }
             }
             else if (me->GetMapId() == 0) // Eastern Kingdom
             {
                 if ((cr = me->SummonCreature(NPC_BARLEYBREW_KEG, -5187.23f, -599.779f, 397.176f, 0.017453f)))
                 {
                     cr->SetReactState(REACT_PASSIVE);
                     summons.Summon(cr);
                     revelerGUIDs.push_back(cr->GetGUID());
                 }
                 if ((cr = me->SummonCreature(NPC_THUNDERBREW_KEG, -5160.05f, -632.632f, 397.178f, 1.39626f)))
                 {
                     cr->SetReactState(REACT_PASSIVE);
                     summons.Summon(cr);
                     revelerGUIDs.push_back(cr->GetGUID());
                 }
                 if ((cr = me->SummonCreature(NPC_GORDOK_KEG, -5145.75f, -575.667f, 397.176f, -2.28638f)))
                 {
                     cr->SetReactState(REACT_PASSIVE);
                     summons.Summon(cr);
                     revelerGUIDs.push_back(cr->GetGUID());
                 }
             }
             if ((cr = me->SummonCreature(NPC_DARK_IRON_HERALD, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), 0.0f, TEMPSUMMON_TIMED_DESPAWN, 300000)))
                 summons.Summon(cr);
             kegCounter = 0;
             guzzlerCounter = 0;
             thrown = 0;
             events.ScheduleEvent(EVENT_SPAWN_MOLE_MACHINE, 1500);
             events.ScheduleEvent(EVENT_PRE_FINISH_ATTACK, 280000);
             events.ScheduleEvent(EVENT_BARTENDER_SAY, 5000);
         }
References EVENT_BARTENDER_SAY, EVENT_PRE_FINISH_ATTACK, EVENT_SPAWN_MOLE_MACHINE, GetCreatureListWithEntryInGrid(), Object::GetGUID(), WorldLocation::GetMapId(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), guzzlerCounter, kegCounter, ScriptedAI::me, MONTH, NPC_BARLEYBREW_KEG, NPC_BREWFEST_REVELER, NPC_DARK_IRON_HERALD, NPC_DROHN_KEG, NPC_GORDOK_KEG, NPC_THUNDERBREW_KEG, NPC_VOODOO_KEG, REACT_PASSIVE, revelerGUIDs, Creature::SetReactState(), SummonList::Summon(), WorldObject::SummonCreature(), summons, TEMPSUMMON_TIMED_DESPAWN, and thrown.
Referenced by UpdateAI().
Reset()
void npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 357 of file brewfest.cpp.
         {
             for (ObjectGuid const& guid : revelerGUIDs)
             {
                 if (Creature* reveler = ObjectAccessor::GetCreature(*me, guid))
                 {
                     reveler->SetRespawnDelay(5 * MINUTE);
                     reveler->Respawn();
                 }
             }
             revelerGUIDs.clear();
             summons.DespawnAll();
             events.Reset();
             events.ScheduleEvent(EVENT_CHECK_HOUR, 2000);
             kegCounter = 0;
             guzzlerCounter = 0;
             thrown = 0;
         }
References SummonList::DespawnAll(), EVENT_CHECK_HOUR, ObjectAccessor::GetCreature(), guzzlerCounter, kegCounter, ScriptedAI::me, MINUTE, revelerGUIDs, summons, and thrown.
Referenced by FinishAttackDueToWin(), and FinishEventDueToLoss().
SpellHit()
void npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::SpellHit (Unit * caster, const SpellInfo * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 381 of file brewfest.cpp.
         {
             if (spellInfo->Id == SPELL_REPORT_DEATH)
             {
                 if (caster->GetEntry() == NPC_DARK_IRON_GUZZLER)
                     guzzlerCounter++;
                 else
                 {
                     kegCounter++;
                     if (kegCounter == 3)
                         FinishEventDueToLoss();
                 }
             }
         }
References FinishEventDueToLoss(), Object::GetEntry(), guzzlerCounter, SpellInfo::Id, kegCounter, NPC_DARK_IRON_GUZZLER, and SPELL_REPORT_DEATH.
UpdateAI()
void npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 396 of file brewfest.cpp.
         {
             events.Update(diff);
             switch (events.ExecuteEvent())
             {
                 case EVENT_CHECK_HOUR:
                     {
                         // determine hour
                         if (AllowStart())
{
                             PrepareEvent();
                             events.RepeatEvent(300000);
                             return;
                         }
                         events.RepeatEvent(2000);
                         break;
                     }
                 case EVENT_SPAWN_MOLE_MACHINE:
                     {
                         if (me->GetMapId() == 1) // Kalimdor
{
                             float rand = 8 + rand_norm() * 12;
                             float angle = rand_norm() * 2 * M_PI;
                             float x = 1201.8f + rand * cos(angle);
                             float y = -4299.6f + rand * sin(angle);
                             if (Creature* cr = me->SummonCreature(NPC_MOLE_MACHINE_TRIGGER, x, y, 21.3f, 0.0f))
                                 cr->CastSpell(cr, SPELL_SPAWN_MOLE_MACHINE, true);
                         }
                         else if (me->GetMapId() == 0) // EK
{
                             float rand = rand_norm() * 20;
                             float angle = rand_norm() * 2 * M_PI;
                             float x = -5157.1f + rand * cos(angle);
                             float y = -598.98f + rand * sin(angle);
                             if (Creature* cr = me->SummonCreature(NPC_MOLE_MACHINE_TRIGGER, x, y, 398.11f, 0.0f))
                                 cr->CastSpell(cr, SPELL_SPAWN_MOLE_MACHINE, true);
                         }
                         events.RepeatEvent(3000);
                         break;
                     }
                 case EVENT_PRE_FINISH_ATTACK:
                     {
                         events.CancelEvent(EVENT_SPAWN_MOLE_MACHINE);
                         events.ScheduleEvent(EVENT_FINISH_ATTACK, 20000);
                         break;
                     }
                 case EVENT_FINISH_ATTACK:
                     {
                         FinishAttackDueToWin();
                         events.RescheduleEvent(EVENT_CHECK_HOUR, 60000);
                         break;
                     }
                 case EVENT_BARTENDER_SAY:
                     {
                         events.RepeatEvent(12000);
                         Creature* sayer = GetRandomBartender();
                         if (!sayer)
                             return;
                         thrown++;
                         if (thrown == 3)
{
                             thrown = 0;
                             sayer->Say("SOMEONE TRY THIS SUPER BREW!", LANG_UNIVERSAL);
                             //sayer->CastSpell(sayer, SPELL_CREATE_SUPER_BREW, true);
                             sayer->SummonCreature(NPC_SUPER_BREW_TRIGGER, sayer->GetPositionX() + 15 * cos(sayer->GetOrientation()), sayer->GetPositionY() + 15 * sin(sayer->GetOrientation()), sayer->GetPositionZ(), 0.0f, TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN, 30000);
                         }
                         else
{
                             if (urand(0, 1))
                                 sayer->Say("Chug and chuck! Chug and chuck!", LANG_UNIVERSAL);
                             else
                                 sayer->Say("Down the free brew and pelt the Guzzlers with your mug!", LANG_UNIVERSAL);
                         }
                         break;
                     }
             }
         }
References AllowStart(), diff(), EVENT_BARTENDER_SAY, EVENT_CHECK_HOUR, EVENT_FINISH_ATTACK, EVENT_PRE_FINISH_ATTACK, EVENT_SPAWN_MOLE_MACHINE, FinishAttackDueToWin(), WorldLocation::GetMapId(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GetRandomBartender(), LANG_UNIVERSAL, M_PI, ScriptedAI::me, NPC_MOLE_MACHINE_TRIGGER, NPC_SUPER_BREW_TRIGGER, PrepareEvent(), rand_norm(), Unit::Say(), SPELL_SPAWN_MOLE_MACHINE, WorldObject::SummonCreature(), TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN, thrown, urand(), G3D::x, and G3D::y.
Member Data Documentation
events
EventMap npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::events
Definition at line 351 of file brewfest.cpp.
guzzlerCounter
uint32 npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::guzzlerCounter
Definition at line 353 of file brewfest.cpp.
Referenced by FinishAttackDueToWin(), FinishEventDueToLoss(), PrepareEvent(), Reset(), and SpellHit().
kegCounter
uint32 npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::kegCounter
Definition at line 353 of file brewfest.cpp.
Referenced by PrepareEvent(), Reset(), and SpellHit().
revelerGUIDs
GuidVector npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::revelerGUIDs
Definition at line 355 of file brewfest.cpp.
Referenced by PrepareEvent(), and Reset().
summons
SummonList npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::summons
Definition at line 352 of file brewfest.cpp.
Referenced by PrepareEvent(), and Reset().
thrown
uint8 npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::thrown
Definition at line 354 of file brewfest.cpp.
Referenced by PrepareEvent(), Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Events/brewfest.cpp