Azerotcore-wotlk: npc_pos_leader_second::npc_pos_leader_secondAI Struct Reference
npc_pos_leader_second::npc_pos_leader_secondAI Struct Reference
Public Member Functions
npc_pos_leader_secondAI (Creature *creature)
void DoAction (int32 p) override
void SpellHitTarget (Unit *target, const SpellInfo *spell) override
void MovementInform (uint32 type, uint32 id) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void Reset ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
EventMap events
ObjectGuid barrierGUID
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1146 of file pit_of_saron.cpp.
Constructor & Destructor Documentation
npc_pos_leader_secondAI()
npc_pos_leader_second::npc_pos_leader_secondAI::npc_pos_leader_secondAI (Creature * creature) inline
Definition at line 1148 of file pit_of_saron.cpp.
                                                     : NullCreatureAI(creature)
         {
             pInstance = me->GetInstanceScript();
             barrierGUID.Clear();
             events.Reset();
             me->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_QUESTGIVER);
             if (pInstance)
             {
                 if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_RIMEFANG_GUID)))
                 {
                     c->RemoveAllAuras();
                     c->GetMotionMaster()->Clear();
                     c->GetMotionMaster()->MoveIdle();
                     c->SetVisible(false);
                 }
                 if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_MARTIN_OR_GORKUN_GUID)))
                 {
                     c->AI()->DoAction(2);
                 }
             }
         }
References barrierGUID, ObjectGuid::Clear(), DATA_MARTIN_OR_GORKUN_GUID, DATA_RIMEFANG_GUID, Map::GetCreature(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), InstanceScript::instance, CreatureAI::me, pInstance, Object::RemoveFlag(), UNIT_NPC_FLAG_QUESTGIVER, and UNIT_NPC_FLAGS.
Member Function Documentation
DoAction()
void npc_pos_leader_second::npc_pos_leader_secondAI::DoAction (int32 p) inline override virtual
Reimplemented from UnitAI.
Definition at line 1175 of file pit_of_saron.cpp.
         {
             if (p == 1)
             {
                 events.RescheduleEvent(1, me->GetEntry() == NPC_JAINA_PART2 ? 15500 : 18000);
                 events.RescheduleEvent(2, me->GetEntry() == NPC_JAINA_PART2 ? 16500 : 19000);
             }
         }
References Object::GetEntry(), CreatureAI::me, and NPC_JAINA_PART2.
MovementInform()
void npc_pos_leader_second::npc_pos_leader_secondAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from CreatureAI.
Definition at line 1194 of file pit_of_saron.cpp.
         {
             if (type != WAYPOINT_MOTION_TYPE)
                 return;
             switch(id)
             {
                 case 0:
                     Talk(me->GetEntry() == NPC_JAINA_PART2 ? SAY_JAINA_OUTRO_2 : SAY_SYLVANAS_OUTRO_2);
                     break;
                 case 1:
                     if (me->GetEntry() == NPC_JAINA_PART2)
                         Talk(SAY_JAINA_OUTRO_3);
                     break;
                 case 6:
                     me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_QUESTGIVER);
                     if (GameObject* g = me->FindNearestGameObject(GO_HOR_PORTCULLIS, 50.0f))
                         g->SetGoState(GO_STATE_ACTIVE);
                     break;
             }
         }
References WorldObject::FindNearestGameObject(), Object::GetEntry(), GO_HOR_PORTCULLIS, GO_STATE_ACTIVE, CreatureAI::me, NPC_JAINA_PART2, SAY_JAINA_OUTRO_2, SAY_JAINA_OUTRO_3, SAY_SYLVANAS_OUTRO_2, Object::SetFlag(), CreatureAI::Talk(), UNIT_NPC_FLAG_QUESTGIVER, UNIT_NPC_FLAGS, and WAYPOINT_MOTION_TYPE.
SpellHitTarget()
void npc_pos_leader_second::npc_pos_leader_secondAI::SpellHitTarget (Unit * target, const SpellInfo * spell) inline override virtual
Reimplemented from CreatureAI.
Definition at line 1184 of file pit_of_saron.cpp.
         {
             if ((spell->Id == SPELL_TELEPORT_JAINA || spell->Id == SPELL_TELEPORT_SYLVANAS) && target && target->GetTypeId() == TYPEID_PLAYER)
             {
                 float angle = rand_norm() * 2 * M_PI;
                 float dist = urand(1, 4);
                 target->ToPlayer()->NearTeleportTo(me->GetPositionX() + cos(angle)*dist, me->GetPositionY() + sin(angle)*dist, me->GetPositionZ(), me->GetOrientation());
             }
         }
References Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Object::GetTypeId(), SpellInfo::Id, CreatureAI::me, Unit::NearTeleportTo(), rand_norm(), SPELL_TELEPORT_JAINA, SPELL_TELEPORT_SYLVANAS, Object::ToPlayer(), TYPEID_PLAYER, and urand().
UpdateAI()
void npc_pos_leader_second::npc_pos_leader_secondAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 1216 of file pit_of_saron.cpp.
         {
             events.Update(diff);
             switch(events.ExecuteEvent())
             {
                 case 0:
                     break;
                 case 1:
                     if (pInstance)
                         if (Creature* c = me->SummonCreature(NPC_SINDRAGOSA, TSSindragosaPos1))
{
                             c->SetCanFly(true);
                             c->SetDisableGravity(true);
                             c->GetMotionMaster()->MovePoint(0, TSSindragosaPos2);
                         }
                     break;
                 case 2:
                     if (pInstance)
                         if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_MARTIN_OR_GORKUN_GUID)))
                             c->AI()->Talk(SAY_GENERAL_OUTRO_2);
                     events.RescheduleEvent(3, me->GetEntry() == NPC_JAINA_PART2 ? 7000 : 8000);
                     break;
                 case 3:
                     Talk(me->GetEntry() == NPC_JAINA_PART2 ? SAY_JAINA_OUTRO_1 : SAY_SYLVANAS_OUTRO_1);
                     me->CastSpell(me, me->GetEntry() == NPC_JAINA_PART2 ? SPELL_TELEPORT_JAINA_VISUAL : SPELL_TELEPORT_SYLVANAS_VISUAL, true);
                     events.RescheduleEvent(4, 2000);
                     break;
                 case 4:
                     me->CastSpell(me, me->GetEntry() == NPC_JAINA_PART2 ? SPELL_TELEPORT_JAINA : SPELL_TELEPORT_SYLVANAS, true);
                     if (GameObject* barrier = me->SummonGameObject(203005, 1055.49f, 115.03f, 628.15f, 2.08f, 0.0f, 0.0f, 0.0f, 0.0f, 86400, false))
                         barrierGUID = barrier->GetGUID();
                     events.RescheduleEvent(5, 1500);
                     break;
                 case 5:
                     if (pInstance)
                         if (Creature* x = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_MARTIN_OR_GORKUN_GUID)))
{
                             if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_SINDRAGOSA_GUID)))
                                 c->CastSpell(x->GetPositionX(), x->GetPositionY(), x->GetPositionZ(), SPELL_SINDRAGOSA_FROST_BOMB_POS, true);
                         }
                     events.RescheduleEvent(6, 5000);
                     events.RescheduleEvent(10, 2000);
                     break;
                 case 6:
                     if (pInstance)
                         if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_SINDRAGOSA_GUID)))
                             c->GetMotionMaster()->MovePoint(0, TSSindragosaPos1);
                     events.RescheduleEvent(7, 4500);
                     break;
                 case 7:
                     if (pInstance)
                         if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_SINDRAGOSA_GUID)))
                             c->SetVisible(false);
                     if (GameObject* barrier = pInstance->instance->GetGameObject(barrierGUID))
                         barrier->Delete();
                     barrierGUID.Clear();
                     events.RescheduleEvent(8, 2000);
                     break;
                 case 8:
                     me->GetMotionMaster()->MovePath(me->GetEntry() == NPC_JAINA_PART2 ? PATH_BEGIN_VALUE + 16 : PATH_BEGIN_VALUE + 17, false);
                     break;
                 case 10:
                     if (Creature* x = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_MARTIN_OR_GORKUN_GUID)))
                         x->AI()->DoAction(3);
                     break;
             }
         }
References barrierGUID, Unit::CastSpell(), ObjectGuid::Clear(), DATA_MARTIN_OR_GORKUN_GUID, DATA_SINDRAGOSA_GUID, Map::GetCreature(), Object::GetEntry(), Map::GetGameObject(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), InstanceScript::instance, CreatureAI::me, MotionMaster::MovePath(), NPC_JAINA_PART2, NPC_SINDRAGOSA, PATH_BEGIN_VALUE, pInstance, SAY_GENERAL_OUTRO_2, SAY_JAINA_OUTRO_1, SAY_SYLVANAS_OUTRO_1, SPELL_SINDRAGOSA_FROST_BOMB_POS, SPELL_TELEPORT_JAINA, SPELL_TELEPORT_JAINA_VISUAL, SPELL_TELEPORT_SYLVANAS, SPELL_TELEPORT_SYLVANAS_VISUAL, WorldObject::SummonCreature(), WorldObject::SummonGameObject(), CreatureAI::Talk(), TSSindragosaPos1, and TSSindragosaPos2.
Member Data Documentation
barrierGUID
ObjectGuid npc_pos_leader_second::npc_pos_leader_secondAI::barrierGUID
Definition at line 1173 of file pit_of_saron.cpp.
Referenced by npc_pos_leader_secondAI(), and UpdateAI().
events
EventMap npc_pos_leader_second::npc_pos_leader_secondAI::events
Definition at line 1172 of file pit_of_saron.cpp.
pInstance
InstanceScript* npc_pos_leader_second::npc_pos_leader_secondAI::pInstance
Definition at line 1171 of file pit_of_saron.cpp.
Referenced by npc_pos_leader_secondAI(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/FrozenHalls/PitOfSaron/pit_of_saron.cpp