Azerotcore-wotlk: npc_hor_leader_second::npc_hor_leader_secondAI Struct Reference
npc_hor_leader_second::npc_hor_leader_secondAI Struct Reference
Public Member Functions
npc_hor_leader_secondAI (Creature *creature)
void Reset () override
void DoAction (int32 actionId) override
void DamageTaken (Unit *, uint32 &dmg, DamageEffectType, SpellSchoolMask) override
void MoveToNextStopPoint ()
void MovementInform (uint32 type, uint32) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
EventMap events
uint8 currentStopPoint
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1643 of file halls_of_reflection.cpp.
Constructor & Destructor Documentation
npc_hor_leader_secondAI()
npc_hor_leader_second::npc_hor_leader_secondAI::npc_hor_leader_secondAI (Creature * creature) inline
Definition at line 1645 of file halls_of_reflection.cpp.
                                                     : NullCreatureAI(creature)
         {
             pInstance = me->GetInstanceScript();
             if (!pInstance)
                 me->IsAIEnabled = false;
         }
References WorldObject::GetInstanceScript(), Unit::IsAIEnabled, CreatureAI::me, and pInstance.
Member Function Documentation
DamageTaken()
void npc_hor_leader_second::npc_hor_leader_secondAI::DamageTaken (Unit * , uint32 & dmg, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from UnitAI.
Definition at line 1680 of file halls_of_reflection.cpp.
         {
             if (dmg >= me->GetHealth())
                 dmg = me->GetHealth() - 1;
         }
References Unit::GetHealth(), and CreatureAI::me.
DoAction()
void npc_hor_leader_second::npc_hor_leader_secondAI::DoAction (int32 actionId) inline override virtual
Reimplemented from UnitAI.
Definition at line 1662 of file halls_of_reflection.cpp.
         {
             switch(actionId)
             {
                 case ACTION_START_INTRO:
                     events.ScheduleEvent(EVENT_LK_SAY_AGGRO, 0);
                     break;
                 case ACTION_START_LK_FIGHT_REAL:
                     events.ScheduleEvent(EVENT_START_RUN, 0);
                     break;
                 case ACTION_INFORM_WALL_DESTROYED:
                     MoveToNextStopPoint();
                     if (currentStopPoint == 5)
                         events.ScheduleEvent(EVENT_SAY_OPENING, 3000);
                     break;
             }
         }
References ACTION_INFORM_WALL_DESTROYED, ACTION_START_INTRO, ACTION_START_LK_FIGHT_REAL, currentStopPoint, EVENT_LK_SAY_AGGRO, EVENT_SAY_OPENING, EVENT_START_RUN, and MoveToNextStopPoint().
MovementInform()
void npc_hor_leader_second::npc_hor_leader_secondAI::MovementInform (uint32 type, uint32) inline override virtual
Reimplemented from CreatureAI.
Definition at line 1697 of file halls_of_reflection.cpp.
         {
             if (type == ESCORT_MOTION_TYPE && me->movespline->Finalized())
                 events.ScheduleEvent(EVENT_SAY_LEADER_STOP_TEXT, 1000);
         }
References ESCORT_MOTION_TYPE, EVENT_SAY_LEADER_STOP_TEXT, Movement::MoveSpline::Finalized(), CreatureAI::me, and Unit::movespline.
MoveToNextStopPoint()
void npc_hor_leader_second::npc_hor_leader_secondAI::MoveToNextStopPoint () inline
Definition at line 1686 of file halls_of_reflection.cpp.
         {
             me->InterruptNonMeleeSpells(true);
             ++currentStopPoint;
             Movement::PointsArray path;
             path.push_back(G3D::Vector3(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()));
             for (uint8 i = WP_STOP[currentStopPoint - 1] + (currentStopPoint == 1 ? 0 : 1); i <= WP_STOP[currentStopPoint]; ++i)
                 path.push_back(G3D::Vector3(PathWaypoints[i].GetPositionX(), PathWaypoints[i].GetPositionY(), PathWaypoints[i].GetPositionZ()));
             me->GetMotionMaster()->MoveSplinePath(&path);
         }
References currentStopPoint, Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::InterruptNonMeleeSpells(), CreatureAI::me, MotionMaster::MoveSplinePath(), PathWaypoints, and WP_STOP.
Referenced by DoAction(), and UpdateAI().
Reset()
void npc_hor_leader_second::npc_hor_leader_secondAI::Reset () inline override virtual
Reimplemented from UnitAI.
Definition at line 1656 of file halls_of_reflection.cpp.
         {
             currentStopPoint = 0;
             events.Reset();
         }
References currentStopPoint.
UpdateAI()
void npc_hor_leader_second::npc_hor_leader_secondAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 1703 of file halls_of_reflection.cpp.
         {
             events.Update(diff);
             switch(events.ExecuteEvent())
             {
                 case EVENT_LK_SAY_AGGRO:
                     if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(NPC_LICH_KING_BOSS)))
                         c->AI()->Talk(me->GetEntry() == NPC_JAINA_PART2 ? SAY_LK_AGGRO_ALLY : SAY_LK_AGGRO_HORDE);
                     events.ScheduleEvent(me->GetEntry() == NPC_JAINA_PART2 ? EVENT_JAINA_IMMOBILIZE_LK : EVENT_SYLVANAS_IMMOBILIZE_JUMP, 12000);
                     break;
                 case EVENT_JAINA_IMMOBILIZE_LK:
                     if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(NPC_LICH_KING_BOSS)))
                     {
                         c->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                         me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                         me->CastSpell(c, SPELL_JAINA_ICE_PRISON, false);
                         events.ScheduleEvent(EVENT_SAY_LEAVE, 5000);
                     }
                     break;
                 case EVENT_SYLVANAS_IMMOBILIZE_JUMP:
                     if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(NPC_LICH_KING_BOSS)))
                     {
                         c->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                         me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                         me->KnockbackFrom(c->GetPositionX(), c->GetPositionY(), 10.0f, 3.0f);
                         events.ScheduleEvent(EVENT_SYLVANAS_DARK_BINDING, 1500);
                     }
                     break;
                 case EVENT_SYLVANAS_DARK_BINDING:
                     if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(NPC_LICH_KING_BOSS)))
                         me->CastSpell(c, SPELL_SYLVANAS_DARK_BINDING, false);
                     events.ScheduleEvent(EVENT_SAY_LEAVE, 3500);
                     break;
                 case EVENT_SAY_LEAVE:
                     {
                         Map::PlayerList const& pl = pInstance->instance->GetPlayers();
                         for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                             if (Player* p = itr->GetSource())
                                 p->KilledMonsterCredit(me->GetEntry()); // for quest
                         Talk(me->GetEntry() == NPC_JAINA_PART2 ? SAY_JAINA_LEAVE : SAY_SYLVANAS_LEAVE);
                         me->GetMotionMaster()->MovePoint(0, LeaderEscapePos);
                         events.ScheduleEvent(EVENT_ADD_GOSSIP, 8000);
                     }
                     break;
                 case EVENT_ADD_GOSSIP:
                     me->RemoveAura(me->GetEntry() == NPC_JAINA_PART2 ? SPELL_JAINA_ICE_BARRIER : SPELL_SYLVANAS_CLOAK_OF_DARKNESS);
                     me->SetFacingTo(LeaderEscapePos.GetOrientation());
                     me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
                     break;
                 case EVENT_START_RUN:
                     {
                         pInstance->SetData(ACTION_START_LK_FIGHT, 1);
                         me->setActive(true);
                         MoveToNextStopPoint();
                         if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(NPC_LICH_KING_BOSS)))
{
                             c->setActive(true);
                             c->SetInCombatWithZone();
                             c->RemoveAura(me->GetEntry() == NPC_JAINA_PART2 ? SPELL_JAINA_ICE_PRISON : SPELL_SYLVANAS_DARK_BINDING);
                             c->AI()->DoAction(ACTION_START_LK_FIGHT_REAL);
                         }
                     }
                     break;
                 case EVENT_SAY_LEADER_STOP_TEXT:
                     {
                         int32 textId = 0;
                         switch (currentStopPoint)
{
                             case 1:
                                 textId = SAY_SYLVANAS_IW_1;
                                 break;
                             case 2:
                                 textId = SAY_SYLVANAS_IW_2;
                                 break;
                             case 3:
                                 textId = SAY_SYLVANAS_IW_3;
                                 break;
                             case 4:
                                 textId = SAY_SYLVANAS_IW_4;
                                 break;
                             case 5:
                                 textId = SAY_SYLVANAS_END;
                                 break;
                         }
                         if (me->GetEntry() == NPC_JAINA_PART2)
                             textId += 10;
                         Talk(textId);
                         if (currentStopPoint <= 4)
                             me->CastSpell((Unit*)nullptr, (me->GetEntry() == NPC_JAINA_PART2 ? SPELL_DESTROY_WALL_JAINA : SPELL_DESTROY_WALL_SYLVANAS), false);
                         else
{
                             me->SetFacingTo(PathWaypoints[PATH_WP_COUNT - 1].GetOrientation());
                             me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_READY1H);
                         }
                     }
                     break;
                 case EVENT_SAY_OPENING:
                     Talk(me->GetEntry() == NPC_JAINA_PART2 ? SAY_JAINA_OPENING : SAY_SYLVANAS_OPENING);
                     break;
             }
         }
References ACTION_START_LK_FIGHT, ACTION_START_LK_FIGHT_REAL, MapRefMgr::begin(), Unit::CastSpell(), currentStopPoint, EMOTE_ONESHOT_NONE, EMOTE_ONESHOT_READY1H, MapRefMgr::end(), EVENT_ADD_GOSSIP, EVENT_JAINA_IMMOBILIZE_LK, EVENT_LK_SAY_AGGRO, EVENT_SAY_LEADER_STOP_TEXT, EVENT_SAY_LEAVE, EVENT_SAY_OPENING, EVENT_START_RUN, EVENT_SYLVANAS_DARK_BINDING, EVENT_SYLVANAS_IMMOBILIZE_JUMP, Map::GetCreature(), Object::GetEntry(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), Position::GetOrientation(), Map::GetPlayers(), InstanceScript::instance, Unit::KnockbackFrom(), LeaderEscapePos, CreatureAI::me, MotionMaster::MovePoint(), MoveToNextStopPoint(), NPC_JAINA_PART2, NPC_LICH_KING_BOSS, PATH_WP_COUNT, PathWaypoints, pInstance, Unit::RemoveAura(), SAY_JAINA_LEAVE, SAY_JAINA_OPENING, SAY_LK_AGGRO_ALLY, SAY_LK_AGGRO_HORDE, SAY_SYLVANAS_END, SAY_SYLVANAS_IW_1, SAY_SYLVANAS_IW_2, SAY_SYLVANAS_IW_3, SAY_SYLVANAS_IW_4, SAY_SYLVANAS_LEAVE, SAY_SYLVANAS_OPENING, WorldObject::setActive(), ZoneScript::SetData(), Unit::SetFacingTo(), Object::SetFlag(), Object::SetUInt32Value(), SPELL_DESTROY_WALL_JAINA, SPELL_DESTROY_WALL_SYLVANAS, SPELL_JAINA_ICE_BARRIER, SPELL_JAINA_ICE_PRISON, SPELL_SYLVANAS_CLOAK_OF_DARKNESS, SPELL_SYLVANAS_DARK_BINDING, CreatureAI::Talk(), UNIT_NPC_EMOTESTATE, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
Member Data Documentation
currentStopPoint
uint8 npc_hor_leader_second::npc_hor_leader_secondAI::currentStopPoint
Definition at line 1654 of file halls_of_reflection.cpp.
Referenced by DoAction(), MoveToNextStopPoint(), Reset(), and UpdateAI().
events
EventMap npc_hor_leader_second::npc_hor_leader_secondAI::events
Definition at line 1653 of file halls_of_reflection.cpp.
pInstance
InstanceScript* npc_hor_leader_second::npc_hor_leader_secondAI::pInstance
Definition at line 1652 of file halls_of_reflection.cpp.
Referenced by npc_hor_leader_secondAI(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/halls_of_reflection.cpp