Azerotcore-wotlk: boss_vazruden_the_herald::boss_vazruden_the_heraldAI Struct Reference
boss_vazruden_the_herald::boss_vazruden_the_heraldAI Struct Reference
Public Member Functions
boss_vazruden_the_heraldAI (Creature *creature)
void Reset () override
void AttackStart (Unit *) override
void JustSummoned (Creature *summon) override
void JustDied (Unit *) override
void MovementInform (uint32 type, uint32 id) override
void SummonedCreatureDies (Creature *summon, Unit *) override
void SummonedCreatureDespawn (Creature *summon) override
void UpdateAI (uint32) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void EnterCombat (Unit *) override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 72 of file boss_vazruden_the_herald.cpp.
Constructor & Destructor Documentation
boss_vazruden_the_heraldAI()
boss_vazruden_the_herald::boss_vazruden_the_heraldAI::boss_vazruden_the_heraldAI (Creature * creature) inline
Definition at line 74 of file boss_vazruden_the_herald.cpp.
                                                        : BossAI(creature, DATA_VAZRUDEN)
         {
         }
Member Function Documentation
AttackStart()
void boss_vazruden_the_herald::boss_vazruden_the_heraldAI::AttackStart (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 87 of file boss_vazruden_the_herald.cpp.
         {
         }
JustDied()
void boss_vazruden_the_herald::boss_vazruden_the_heraldAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 98 of file boss_vazruden_the_herald.cpp.
         {
             instance->SetBossState(DATA_VAZRUDEN, DONE);
         }
References DATA_VAZRUDEN, DONE, BossAI::instance, and InstanceScript::SetBossState().
JustSummoned()
void boss_vazruden_the_herald::boss_vazruden_the_heraldAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
Definition at line 91 of file boss_vazruden_the_herald.cpp.
         {
             summons.Summon(summon);
             if (summon->GetEntry() != NPC_HELLFIRE_SENTRY)
                 summon->SetInCombatWithZone();
         }
References Object::GetEntry(), NPC_HELLFIRE_SENTRY, Creature::SetInCombatWithZone(), SummonList::Summon(), and BossAI::summons.
MovementInform()
void boss_vazruden_the_herald::boss_vazruden_the_heraldAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 103 of file boss_vazruden_the_herald.cpp.
         {
             if (type == POINT_MOTION_TYPE && id == POINT_MIDDLE)
             {
                 me->SetVisible(false);
                 me->SummonCreature(NPC_VAZRUDEN, me->GetPositionX(), me->GetPositionY(), 81.2f, 5.46f);
                 me->SummonCreature(NPC_NAZAN, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), 5.46f);
             }
         }
References Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ScriptedAI::me, NPC_NAZAN, NPC_VAZRUDEN, POINT_MIDDLE, POINT_MOTION_TYPE, Unit::SetVisible(), and WorldObject::SummonCreature().
Reset()
void boss_vazruden_the_herald::boss_vazruden_the_heraldAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 78 of file boss_vazruden_the_herald.cpp.
         {
             BossAI::Reset();
             me->SetVisible(true);
             me->SetReactState(REACT_PASSIVE);
             me->SummonCreature(NPC_HELLFIRE_SENTRY, -1372.56f, 1724.31f, 82.967f, 5.3058f);
             me->SummonCreature(NPC_HELLFIRE_SENTRY, -1383.39f, 1711.82f, 82.7961f, 5.67232f);
         }
References ScriptedAI::me, NPC_HELLFIRE_SENTRY, REACT_PASSIVE, BossAI::Reset(), Creature::SetReactState(), Unit::SetVisible(), and WorldObject::SummonCreature().
SummonedCreatureDespawn()
void boss_vazruden_the_herald::boss_vazruden_the_heraldAI::SummonedCreatureDespawn (Creature * summon) inline override virtual
Reimplemented from BossAI.
Definition at line 128 of file boss_vazruden_the_herald.cpp.
         {
             summons.Despawn(summon);
             if (summon->GetEntry() != NPC_HELLFIRE_SENTRY)
                 BossAI::EnterEvadeMode();
         }
References SummonList::Despawn(), CreatureAI::EnterEvadeMode(), Object::GetEntry(), NPC_HELLFIRE_SENTRY, and BossAI::summons.
SummonedCreatureDies()
void boss_vazruden_the_herald::boss_vazruden_the_heraldAI::SummonedCreatureDies (Creature * summon, Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 113 of file boss_vazruden_the_herald.cpp.
         {
             summons.Despawn(summon);
             if (summon->GetEntry() == NPC_HELLFIRE_SENTRY && summons.size() == 0)
             {
                 Talk(SAY_INTRO);
                 me->GetMotionMaster()->MovePoint(POINT_MIDDLE, -1406.5f, 1746.5f, 85.0f, false);
                 me->setActive(true);
             }
             else if (summons.size() == 0)
             {
                 Unit::Kill(me, me);
             }
         }
References SummonList::Despawn(), Object::GetEntry(), Unit::GetMotionMaster(), Unit::Kill(), ScriptedAI::me, MotionMaster::MovePoint(), NPC_HELLFIRE_SENTRY, POINT_MIDDLE, SAY_INTRO, WorldObject::setActive(), SummonList::size(), BossAI::summons, and CreatureAI::Talk().
UpdateAI()
void boss_vazruden_the_herald::boss_vazruden_the_heraldAI::UpdateAI (uint32) inline override virtual
Reimplemented from BossAI.
Definition at line 135 of file boss_vazruden_the_herald.cpp.
         {
             if (!me->IsVisible() && summons.size() == 0)
                 BossAI::EnterEvadeMode();
         }
References CreatureAI::EnterEvadeMode(), Unit::IsVisible(), ScriptedAI::me, SummonList::size(), and BossAI::summons.
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/HellfireCitadel/HellfireRamparts/boss_vazruden_the_herald.cpp