Azerotcore-wotlk: instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript Struct Reference
instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript Struct Reference
Public Member Functions
instance_eye_of_eternity_InstanceMapScript (Map *pMap)
void Initialize () override
bool IsEncounterInProgress () const override
void OnPlayerEnter (Player *pPlayer) override
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void SetData (uint32 type, uint32 data) override
ObjectGuid GetGuidData (uint32 type) const override
void ProcessEvent (WorldObject *, uint32 eventId) override
std::string GetSaveData () override
void Load (const char *in) override
bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *, uint32) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void CreatureLooted (Creature *, LootType)
void SaveToDB ()
virtual void Update (uint32)
void OnCreatureRemove (Creature *creature) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
Public Attributes
uint32 EncounterStatus
std::string str_data
ObjectGuid NPC_MalygosGUID
ObjectGuid GO_IrisGUID
ObjectGuid GO_ExitPortalGUID
ObjectGuid GO_PlatformGUID
bool bPokeAchiev
Public Attributes inherited from InstanceScript
Map * instance
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Definition at line 46 of file instance_eye_of_eternity.cpp.
Constructor & Destructor Documentation
instance_eye_of_eternity_InstanceMapScript()
instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::instance_eye_of_eternity_InstanceMapScript (Map * pMap) inline
Definition at line 48 of file instance_eye_of_eternity.cpp.
 : InstanceScript(pMap) { Initialize(); }
References Initialize().
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::CheckAchievementCriteriaMeet (uint32 criteria_id, Player const * source, Unit const * , uint32) inline override virtual
Reimplemented from InstanceScript.
Definition at line 258 of file instance_eye_of_eternity.cpp.
         {
             switch(criteria_id)
             {
                 case ACHIEV_CRITERIA_A_POKE_IN_THE_EYE_10:
                 case ACHIEV_CRITERIA_A_POKE_IN_THE_EYE_25:
                     return bPokeAchiev;
                 case ACHIEV_CRITERIA_DENYIN_THE_SCION_10:
                 case ACHIEV_CRITERIA_DENYIN_THE_SCION_25:
                     return (source && source->GetVehicle() && source->GetVehicle()->GetVehicleInfo()->m_ID == 224);
             }
             return false;
         }
References ACHIEV_CRITERIA_A_POKE_IN_THE_EYE_10, ACHIEV_CRITERIA_A_POKE_IN_THE_EYE_25, ACHIEV_CRITERIA_DENYIN_THE_SCION_10, ACHIEV_CRITERIA_DENYIN_THE_SCION_25, bPokeAchiev, Unit::GetVehicle(), Vehicle::GetVehicleInfo(), and VehicleEntry::m_ID.
GetGuidData()
ObjectGuid instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::GetGuidData (uint32 type) const inline override virtual
Reimplemented from InstanceScript.
Definition at line 185 of file instance_eye_of_eternity.cpp.
         {
             switch(type)
             {
                 case DATA_MALYGOS_GUID:
                     return NPC_MalygosGUID;
             }
             return ObjectGuid::Empty;
         }
References DATA_MALYGOS_GUID, ObjectGuid::Empty, and NPC_MalygosGUID.
GetSaveData()
std::string instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
Definition at line 211 of file instance_eye_of_eternity.cpp.
         {
             OUT_SAVE_INST_DATA;
             std::ostringstream saveStream;
             saveStream << "E E " << EncounterStatus;
             str_data = saveStream.str();
             OUT_SAVE_INST_DATA_COMPLETE;
             return str_data;
         }
References EncounterStatus, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, and str_data.
Initialize()
void instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::Initialize (void) inline override virtual
Reimplemented from InstanceScript.
Definition at line 59 of file instance_eye_of_eternity.cpp.
         {
             EncounterStatus = NOT_STARTED;
             bPokeAchiev = false;
         }
References bPokeAchiev, EncounterStatus, and NOT_STARTED.
Referenced by instance_eye_of_eternity_InstanceMapScript().
IsEncounterInProgress()
bool instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::IsEncounterInProgress () const inline override virtual
Reimplemented from InstanceScript.
Definition at line 66 of file instance_eye_of_eternity.cpp.
         {
             return EncounterStatus == IN_PROGRESS;
         }
References EncounterStatus, and IN_PROGRESS.
Load()
void instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::Load (const char * in) inline override virtual
Reimplemented from InstanceScript.
Definition at line 221 of file instance_eye_of_eternity.cpp.
         {
             if( !in )
             {
                 OUT_LOAD_INST_DATA_FAIL;
                 return;
             }
             OUT_LOAD_INST_DATA(in);
             char dataHead1, dataHead2;
             uint32 data0;
             std::istringstream loadStream(in);
             loadStream >> dataHead1 >> dataHead2 >> data0;
             if( dataHead1 == 'E' && dataHead2 == 'E' )
             {
                 EncounterStatus = data0;
                 switch(EncounterStatus)
                 {
                     case IN_PROGRESS:
                         EncounterStatus = NOT_STARTED;
                         break;
                     case DONE:
                         // destroy platform, hide iris
                         ProcessEvent(nullptr, 20158);
                         if (GameObject* go = instance->GetGameObject(GO_IrisGUID))
                             go->SetPhaseMask(2, true);
                         break;
                 }
             }
             else
                 OUT_LOAD_INST_DATA_FAIL;
             OUT_LOAD_INST_DATA_COMPLETE;
         }
References DONE, EncounterStatus, Map::GetGameObject(), GO_IrisGUID, IN_PROGRESS, InstanceScript::instance, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, OUT_LOAD_INST_DATA_FAIL, and ProcessEvent().
OnCreatureCreate()
void instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 98 of file instance_eye_of_eternity.cpp.
         {
             switch(creature->GetEntry())
             {
                 case NPC_MALYGOS:
                     NPC_MalygosGUID = creature->GetGUID();
                     break;
             }
         }
References Object::GetEntry(), Object::GetGUID(), NPC_MALYGOS, and NPC_MalygosGUID.
OnGameObjectCreate()
void instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
Definition at line 108 of file instance_eye_of_eternity.cpp.
         {
             switch(go->GetEntry())
             {
                 case GO_IRIS_N:
                 case GO_IRIS_H:
                     GO_IrisGUID = go->GetGUID();
                     break;
                 case GO_EXIT_PORTAL:
                     GO_ExitPortalGUID = go->GetGUID();
                     break;
                 case GO_NEXUS_PLATFORM:
                     GO_PlatformGUID = go->GetGUID();
                     break;
             }
         }
References Object::GetEntry(), Object::GetGUID(), GO_EXIT_PORTAL, GO_ExitPortalGUID, GO_IRIS_H, GO_IRIS_N, GO_IrisGUID, GO_NEXUS_PLATFORM, and GO_PlatformGUID.
OnPlayerEnter()
void instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::OnPlayerEnter (Player * pPlayer) inline override virtual
Reimplemented from InstanceScript.
Definition at line 71 of file instance_eye_of_eternity.cpp.
         {
             if (EncounterStatus == DONE)
             {
                 // destroy platform, hide iris (actually ensure, done at loading, but doesn't always work
                 ProcessEvent(nullptr, 20158);
                 if (GameObject* go = instance->GetGameObject(GO_IrisGUID))
                     if (go->GetPhaseMask() != 2)
                         go->SetPhaseMask(2, true);
                 // no floor, so put players on drakes
                 if (pPlayer)
                 {
                     if (!pPlayer->IsAlive())
                         return;
                     if (Creature* c = pPlayer->SummonCreature(NPC_WYRMREST_SKYTALON, pPlayer->GetPositionX(), pPlayer->GetPositionY(), pPlayer->GetPositionZ() - 20.0f, 0.0f, TEMPSUMMON_MANUAL_DESPAWN, 0))
                     {
                         c->SetCanFly(true);
                         c->SetFaction(pPlayer->GetFaction());
                         //pPlayer->CastCustomSpell(60683, SPELLVALUE_BASE_POINT0, 1, c, true);
                         c->m_Events.AddEvent(new EoEDrakeEnterVehicleEvent(*c, pPlayer->GetGUID()), c->m_Events.CalculateTime(500));
                     }
                 }
             }
         }
References DONE, EncounterStatus, Unit::GetFaction(), Map::GetGameObject(), Object::GetGUID(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GO_IrisGUID, InstanceScript::instance, Unit::IsAlive(), NPC_WYRMREST_SKYTALON, ProcessEvent(), WorldObject::SummonCreature(), and TEMPSUMMON_MANUAL_DESPAWN.
ProcessEvent()
void instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::ProcessEvent (WorldObject * , uint32 eventId) inline override virtual
Reimplemented from ZoneScript.
Definition at line 196 of file instance_eye_of_eternity.cpp.
         {
             switch(eventId)
             {
                 case 20158:
                     if (GameObject* go = instance->GetGameObject(GO_PlatformGUID))
                         if (Creature* c = instance->GetCreature(NPC_MalygosGUID))
{
                             go->ModifyHealth(-6500000, c); // We have HP 6 million in the database... So we have to do at least that
                             go->EnableCollision(false);
                         }
                     break;
             }
         }
References Map::GetCreature(), Map::GetGameObject(), GO_PlatformGUID, InstanceScript::instance, and NPC_MalygosGUID.
Referenced by Load(), and OnPlayerEnter().
SetData()
void instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
Definition at line 125 of file instance_eye_of_eternity.cpp.
         {
             switch(type)
             {
                 case DATA_IRIS_ACTIVATED:
                     if (EncounterStatus == NOT_STARTED)
                         if (Creature* c = instance->GetCreature(NPC_MalygosGUID))
                             if (Player* plr = c->SelectNearestPlayer(250.0f))
                                 c->AI()->AttackStart(plr);
                     break;
                 case DATA_ENCOUNTER_STATUS:
                     EncounterStatus = data;
                     switch(data)
                     {
                         case NOT_STARTED:
                             bPokeAchiev = false;
                             if (GameObject* go = instance->GetGameObject(GO_IrisGUID))
{
                                 go->SetPhaseMask(1, true);
                                 HandleGameObject(GO_IrisGUID, false, go);
                             }
                             if (GameObject* go = instance->GetGameObject(GO_ExitPortalGUID))
                                 go->SetPhaseMask(1, true);
                             if (GameObject* go = instance->GetGameObject(GO_PlatformGUID))
{
                                 go->SetDestructibleState(GO_DESTRUCTIBLE_REBUILDING, nullptr, true);
                                 go->EnableCollision(true);
                             }
                             break;
                         case IN_PROGRESS:
                             bPokeAchiev = (instance->GetPlayersCountExceptGMs() < (instance->GetSpawnMode() == 0 ? (uint32)9 : (uint32)21));
                             break;
                         case DONE:
                             bPokeAchiev = false;
                             if (GameObject* go = instance->GetGameObject(GO_ExitPortalGUID))
                                 go->SetPhaseMask(1, true);
                             if (Creature* c = instance->GetCreature(NPC_MalygosGUID))
                                 if (c->SummonCreature(NPC_ALEXSTRASZA, 798.0f, 1268.0f, 299.0f, 2.45f, TEMPSUMMON_TIMED_DESPAWN, 604800000))
                                     break;
                     }
                     if (data == DONE)
                         SaveToDB();
                     break;
                 case DATA_SET_IRIS_INACTIVE:
                     if (GameObject* go = instance->GetGameObject(GO_IrisGUID))
                     {
                         HandleGameObject(GO_IrisGUID, true, go);
                         if (Creature* c = go->SummonCreature(NPC_WORLD_TRIGGER_LAOI, *go, TEMPSUMMON_TIMED_DESPAWN, 10000))
                             c->CastSpell(c, SPELL_IRIS_ACTIVATED, true);
                     }
                     break;
                 case DATA_HIDE_IRIS_AND_PORTAL:
                     if (GameObject* go = instance->GetGameObject(GO_IrisGUID))
                         go->SetPhaseMask(2, true);
                     if (GameObject* go = instance->GetGameObject(GO_ExitPortalGUID))
                         go->SetPhaseMask(2, true);
                     break;
             }
         }
References bPokeAchiev, DATA_ENCOUNTER_STATUS, DATA_HIDE_IRIS_AND_PORTAL, DATA_IRIS_ACTIVATED, DATA_SET_IRIS_INACTIVE, DONE, EncounterStatus, Map::GetCreature(), Map::GetGameObject(), Map::GetPlayersCountExceptGMs(), Map::GetSpawnMode(), GO_DESTRUCTIBLE_REBUILDING, GO_ExitPortalGUID, GO_IrisGUID, GO_PlatformGUID, InstanceScript::HandleGameObject(), IN_PROGRESS, InstanceScript::instance, NOT_STARTED, NPC_ALEXSTRASZA, NPC_MalygosGUID, NPC_WORLD_TRIGGER_LAOI, InstanceScript::SaveToDB(), WorldObject::SelectNearestPlayer(), SPELL_IRIS_ACTIVATED, WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_DESPAWN.
Member Data Documentation
bPokeAchiev
bool instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::bPokeAchiev
Definition at line 57 of file instance_eye_of_eternity.cpp.
Referenced by CheckAchievementCriteriaMeet(), Initialize(), and SetData().
EncounterStatus
uint32 instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::EncounterStatus
Definition at line 50 of file instance_eye_of_eternity.cpp.
Referenced by GetSaveData(), Initialize(), IsEncounterInProgress(), Load(), OnPlayerEnter(), and SetData().
GO_ExitPortalGUID
ObjectGuid instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::GO_ExitPortalGUID
Definition at line 55 of file instance_eye_of_eternity.cpp.
Referenced by OnGameObjectCreate(), and SetData().
GO_IrisGUID
ObjectGuid instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::GO_IrisGUID
Definition at line 54 of file instance_eye_of_eternity.cpp.
Referenced by Load(), OnGameObjectCreate(), OnPlayerEnter(), and SetData().
GO_PlatformGUID
ObjectGuid instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::GO_PlatformGUID
Definition at line 56 of file instance_eye_of_eternity.cpp.
Referenced by OnGameObjectCreate(), ProcessEvent(), and SetData().
NPC_MalygosGUID
ObjectGuid instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::NPC_MalygosGUID
Definition at line 53 of file instance_eye_of_eternity.cpp.
Referenced by GetGuidData(), OnCreatureCreate(), ProcessEvent(), and SetData().
str_data
std::string instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::str_data
Definition at line 51 of file instance_eye_of_eternity.cpp.
Referenced by GetSaveData().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Nexus/EyeOfEternity/instance_eye_of_eternity.cpp