Azerotcore-wotlk: src/server/scripts/Kalimdor/kalimdor_script_loader.cpp File Reference
kalimdor_script_loader.cpp File Reference
Functions
void AddSC_instance_blackfathom_deeps ()
void AddSC_hyjal ()
void AddSC_boss_archimonde ()
void AddSC_instance_mount_hyjal ()
void AddSC_hyjal_trash ()
void AddSC_boss_rage_winterchill ()
void AddSC_boss_anetheron ()
void AddSC_boss_kazrogal ()
void AddSC_boss_azgalor ()
void AddSC_boss_captain_skarloc ()
void AddSC_boss_epoch_hunter ()
void AddSC_boss_lieutenant_drake ()
void AddSC_instance_old_hillsbrad ()
void AddSC_old_hillsbrad ()
void AddSC_boss_aeonus ()
void AddSC_boss_chrono_lord_deja ()
void AddSC_boss_temporus ()
void AddSC_the_black_morass ()
void AddSC_instance_the_black_morass ()
void AddSC_boss_epoch ()
void AddSC_boss_infinite_corruptor ()
void AddSC_boss_salramm ()
void AddSC_boss_mal_ganis ()
void AddSC_boss_meathook ()
void AddSC_culling_of_stratholme ()
void AddSC_instance_culling_of_stratholme ()
void AddSC_instance_dire_maul ()
void AddSC_instance_maraudon ()
void AddSC_boss_onyxia ()
void AddSC_instance_onyxias_lair ()
void AddSC_instance_ragefire_chasm ()
void AddSC_razorfen_downs ()
void AddSC_instance_razorfen_downs ()
void AddSC_instance_razorfen_kraul ()
void AddSC_boss_kurinnaxx ()
void AddSC_boss_rajaxx ()
void AddSC_boss_moam ()
void AddSC_boss_buru ()
void AddSC_boss_ayamiss ()
void AddSC_boss_ossirian ()
void AddSC_instance_ruins_of_ahnqiraj ()
void AddSC_boss_cthun ()
void AddSC_boss_viscidus ()
void AddSC_boss_fankriss ()
void AddSC_boss_huhuran ()
void AddSC_bug_trio ()
void AddSC_boss_sartura ()
void AddSC_boss_skeram ()
void AddSC_boss_twinemperors ()
void AddSC_boss_ouro ()
void AddSC_npc_anubisath_sentinel ()
void AddSC_instance_temple_of_ahnqiraj ()
void AddSC_instance_wailing_caverns ()
void AddSC_zulfarrak ()
void AddSC_instance_zulfarrak ()
void AddSC_ashenvale ()
void AddSC_azshara ()
void AddSC_azuremyst_isle ()
void AddSC_bloodmyst_isle ()
void AddSC_boss_azuregos ()
void AddSC_darkshore ()
void AddSC_desolace ()
void AddSC_durotar ()
void AddSC_dustwallow_marsh ()
void AddSC_felwood ()
void AddSC_feralas ()
void AddSC_moonglade ()
void AddSC_orgrimmar ()
void AddSC_silithus ()
void AddSC_stonetalon_mountains ()
void AddSC_tanaris ()
void AddSC_the_barrens ()
void AddSC_thousand_needles ()
void AddSC_thunder_bluff ()
void AddSC_ungoro_crater ()
void AddSC_winterspring ()
void AddKalimdorScripts ()
Function Documentation
AddKalimdorScripts()
void AddKalimdorScripts ()
Definition at line 98 of file kalimdor_script_loader.cpp.
 {
     AddSC_instance_blackfathom_deeps();     //Blackfathom Depths
     AddSC_hyjal();                          //CoT Battle for Mt. Hyjal
     AddSC_boss_archimonde();
     AddSC_instance_mount_hyjal();
     AddSC_hyjal_trash();
     AddSC_boss_rage_winterchill();
     AddSC_boss_anetheron();
     AddSC_boss_kazrogal();
     AddSC_boss_azgalor();
     AddSC_boss_captain_skarloc();           //CoT Old Hillsbrad
     AddSC_boss_epoch_hunter();
     AddSC_boss_lieutenant_drake();
     AddSC_instance_old_hillsbrad();
     AddSC_old_hillsbrad();
     AddSC_boss_aeonus();                    //CoT The Black Morass
     AddSC_boss_chrono_lord_deja();
     AddSC_boss_temporus();
     AddSC_the_black_morass();
     AddSC_instance_the_black_morass();
     AddSC_boss_epoch();                     //CoT Culling Of Stratholme
     AddSC_boss_infinite_corruptor();
     AddSC_boss_salramm();
     AddSC_boss_mal_ganis();
     AddSC_boss_meathook();
     AddSC_culling_of_stratholme();
     AddSC_instance_culling_of_stratholme();
     AddSC_instance_dire_maul();             //Dire Maul
     AddSC_instance_maraudon();              //Maraudon
     AddSC_boss_onyxia();                    //Onyxia's Lair
     AddSC_instance_onyxias_lair();
     AddSC_instance_ragefire_chasm();        //Ragefire Chasm
     AddSC_razorfen_downs();
     AddSC_instance_razorfen_downs();        //Razorfen Downs
     AddSC_instance_razorfen_kraul();        //Razorfen Kraul
     AddSC_boss_kurinnaxx();                 //Ruins of ahn'qiraj
     AddSC_boss_rajaxx();
     AddSC_boss_moam();
     AddSC_boss_buru();
     AddSC_boss_ayamiss();
     AddSC_boss_ossirian();
     AddSC_instance_ruins_of_ahnqiraj();
     AddSC_boss_cthun();                     //Temple of ahn'qiraj
     AddSC_boss_viscidus();
     AddSC_boss_fankriss();
     AddSC_boss_huhuran();
     AddSC_bug_trio();
     AddSC_boss_sartura();
     AddSC_boss_skeram();
     AddSC_boss_twinemperors();
     AddSC_boss_ouro();
     AddSC_npc_anubisath_sentinel();
     AddSC_instance_temple_of_ahnqiraj();
     AddSC_instance_wailing_caverns();       //Wailing caverns
     AddSC_zulfarrak();
     AddSC_instance_zulfarrak();             //Zul'Farrak instance script
     AddSC_ashenvale();
     AddSC_azshara();
     AddSC_azuremyst_isle();
     AddSC_bloodmyst_isle();
     AddSC_boss_azuregos();
     AddSC_darkshore();
     AddSC_desolace();
     AddSC_durotar();
     AddSC_dustwallow_marsh();
     AddSC_felwood();
     AddSC_feralas();
     AddSC_moonglade();
     AddSC_orgrimmar();
     AddSC_silithus();
     AddSC_stonetalon_mountains();
     AddSC_tanaris();
     AddSC_the_barrens();
     AddSC_thousand_needles();
     AddSC_thunder_bluff();
     AddSC_ungoro_crater();
     AddSC_winterspring();
 }
References AddSC_ashenvale(), AddSC_azshara(), AddSC_azuremyst_isle(), AddSC_bloodmyst_isle(), AddSC_boss_aeonus(), AddSC_boss_anetheron(), AddSC_boss_archimonde(), AddSC_boss_ayamiss(), AddSC_boss_azgalor(), AddSC_boss_azuregos(), AddSC_boss_buru(), AddSC_boss_captain_skarloc(), AddSC_boss_chrono_lord_deja(), AddSC_boss_cthun(), AddSC_boss_epoch(), AddSC_boss_epoch_hunter(), AddSC_boss_fankriss(), AddSC_boss_huhuran(), AddSC_boss_infinite_corruptor(), AddSC_boss_kazrogal(), AddSC_boss_kurinnaxx(), AddSC_boss_lieutenant_drake(), AddSC_boss_mal_ganis(), AddSC_boss_meathook(), AddSC_boss_moam(), AddSC_boss_onyxia(), AddSC_boss_ossirian(), AddSC_boss_ouro(), AddSC_boss_rage_winterchill(), AddSC_boss_rajaxx(), AddSC_boss_salramm(), AddSC_boss_sartura(), AddSC_boss_skeram(), AddSC_boss_temporus(), AddSC_boss_twinemperors(), AddSC_boss_viscidus(), AddSC_bug_trio(), AddSC_culling_of_stratholme(), AddSC_darkshore(), AddSC_desolace(), AddSC_durotar(), AddSC_dustwallow_marsh(), AddSC_felwood(), AddSC_feralas(), AddSC_hyjal(), AddSC_hyjal_trash(), AddSC_instance_blackfathom_deeps(), AddSC_instance_culling_of_stratholme(), AddSC_instance_dire_maul(), AddSC_instance_maraudon(), AddSC_instance_mount_hyjal(), AddSC_instance_old_hillsbrad(), AddSC_instance_onyxias_lair(), AddSC_instance_ragefire_chasm(), AddSC_instance_razorfen_downs(), AddSC_instance_razorfen_kraul(), AddSC_instance_ruins_of_ahnqiraj(), AddSC_instance_temple_of_ahnqiraj(), AddSC_instance_the_black_morass(), AddSC_instance_wailing_caverns(), AddSC_instance_zulfarrak(), AddSC_moonglade(), AddSC_npc_anubisath_sentinel(), AddSC_old_hillsbrad(), AddSC_orgrimmar(), AddSC_razorfen_downs(), AddSC_silithus(), AddSC_stonetalon_mountains(), AddSC_tanaris(), AddSC_the_barrens(), AddSC_the_black_morass(), AddSC_thousand_needles(), AddSC_thunder_bluff(), AddSC_ungoro_crater(), AddSC_winterspring(), and AddSC_zulfarrak().
AddSC_ashenvale()
void AddSC_ashenvale ()
Definition at line 237 of file zone_ashenvale.cpp.
 {
     new npc_muglash();
     new go_naga_brazier();
 }
Referenced by AddKalimdorScripts().
AddSC_azshara()
void AddSC_azshara ()
Definition at line 461 of file zone_azshara.cpp.
 {
     new npc_spitelashes();
     new npc_rizzle_sprysprocket();
     new npc_depth_charge();
 }
Referenced by AddKalimdorScripts().
AddSC_azuremyst_isle()
void AddSC_azuremyst_isle ()
Definition at line 525 of file zone_azuremyst_isle.cpp.
 {
     new npc_draenei_survivor();
     new npc_injured_draenei();
     new npc_magwin();
     new npc_death_ravager();
     new go_ravager_cage();
     new npc_stillpine_capitive();
     new go_bristlelimb_cage();
 }
Referenced by AddKalimdorScripts().
AddSC_bloodmyst_isle()
void AddSC_bloodmyst_isle ()
Definition at line 90 of file zone_bloodmyst_isle.cpp.
 {
     new npc_webbed_creature();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_aeonus()
void AddSC_boss_aeonus ()
Definition at line 163 of file boss_aeonus.cpp.
 {
     new boss_aeonus();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_anetheron()
void AddSC_boss_anetheron ()
Definition at line 268 of file boss_anetheron.cpp.
 {
     new boss_anetheron();
     new npc_towering_infernal();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_archimonde()
void AddSC_boss_archimonde ()
Definition at line 780 of file boss_archimonde.cpp.
 {
     new spell_red_sky_effect();
     new spell_hand_of_death();
     new spell_finger_of_death();
     new boss_archimonde();
     new npc_doomfire();
     new npc_doomfire_targetting();
     new npc_ancient_wisp();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_ayamiss()
void AddSC_boss_ayamiss ()
Definition at line 292 of file boss_ayamiss.cpp.
 {
     new boss_ayamiss();
     new npc_hive_zara_larva();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_azgalor()
void AddSC_boss_azgalor ()
Definition at line 282 of file boss_azgalor.cpp.
 {
     new boss_azgalor();
     new npc_lesser_doomguard();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_azuregos()
void AddSC_boss_azuregos ()
Definition at line 167 of file boss_azuregos.cpp.
 {
     new boss_azuregos();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_buru()
void AddSC_boss_buru ()
Definition at line 276 of file boss_buru.cpp.
 {
     new boss_buru();
     new npc_buru_egg();
     new spell_egg_explosion();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_captain_skarloc()
void AddSC_boss_captain_skarloc ()
Definition at line 221 of file boss_captain_skarloc.cpp.
 {
     new boss_captain_skarloc();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_chrono_lord_deja()
void AddSC_boss_chrono_lord_deja ()
Definition at line 152 of file boss_chrono_lord_deja.cpp.
 {
     new boss_chrono_lord_deja();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_cthun()
void AddSC_boss_cthun ()
Definition at line 1309 of file boss_cthun.cpp.
 {
     new boss_eye_of_cthun();
     new boss_cthun();
     new npc_eye_tentacle();
     new npc_claw_tentacle();
     new npc_giant_claw_tentacle();
     new npc_giant_eye_tentacle();
     new npc_giant_flesh_tentacle();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_epoch()
void AddSC_boss_epoch ()
Definition at line 157 of file boss_epoch.cpp.
 {
     new boss_epoch();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_epoch_hunter()
void AddSC_boss_epoch_hunter ()
Definition at line 122 of file boss_epoch_hunter.cpp.
 {
     new boss_epoch_hunter();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_fankriss()
void AddSC_boss_fankriss ()
Definition at line 219 of file boss_fankriss.cpp.
 {
     new boss_fankriss();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_huhuran()
void AddSC_boss_huhuran ()
Definition at line 158 of file boss_huhuran.cpp.
 {
     new boss_huhuran();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_infinite_corruptor()
void AddSC_boss_infinite_corruptor ()
Definition at line 163 of file boss_infinite.cpp.
 {
     new boss_infinite_corruptor();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_kazrogal()
void AddSC_boss_kazrogal ()
Definition at line 226 of file boss_kazrogal.cpp.
 {
     new boss_kazrogal();
     new spell_mark_of_kazrogal();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_kurinnaxx()
void AddSC_boss_kurinnaxx ()
Definition at line 133 of file boss_kurinnaxx.cpp.
 {
     new boss_kurinnaxx();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_lieutenant_drake()
void AddSC_boss_lieutenant_drake ()
Definition at line 168 of file boss_lieutenant_drake.cpp.
 {
     new boss_lieutenant_drake();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_mal_ganis()
void AddSC_boss_mal_ganis ()
Definition at line 173 of file boss_mal_ganis.cpp.
 {
     new boss_mal_ganis();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_meathook()
void AddSC_boss_meathook ()
Definition at line 119 of file boss_meathook.cpp.
 {
     new boss_meathook();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_moam()
void AddSC_boss_moam ()
Definition at line 184 of file boss_moam.cpp.
 {
     new boss_moam();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_onyxia()
void AddSC_boss_onyxia ()
Definition at line 651 of file boss_onyxia.cpp.
 {
     new boss_onyxia();
     new npc_onyxian_lair_guard();
     new npc_onyxia_whelp();
     new npc_onyxia_trigger();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_ossirian()
void AddSC_boss_ossirian ()
Definition at line 297 of file boss_ossirian.cpp.
 {
     new boss_ossirian();
     new go_ossirian_crystal();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_ouro()
void AddSC_boss_ouro ()
Definition at line 146 of file boss_ouro.cpp.
 {
     new boss_ouro();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_rage_winterchill()
void AddSC_boss_rage_winterchill ()
Definition at line 164 of file boss_rage_winterchill.cpp.
 {
     new boss_rage_winterchill();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_rajaxx()
void AddSC_boss_rajaxx ()
Definition at line 127 of file boss_rajaxx.cpp.
 {
     new boss_rajaxx();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_salramm()
void AddSC_boss_salramm ()
Definition at line 195 of file boss_salramm.cpp.
 {
     new boss_salramm();
     new spell_boss_salramm_steal_flesh();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_sartura()
void AddSC_boss_sartura ()
Definition at line 311 of file boss_sartura.cpp.
 {
     new boss_sartura();
     new npc_sartura_royal_guard();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_skeram()
void AddSC_boss_skeram ()
Definition at line 223 of file boss_skeram.cpp.
 {
     new boss_skeram();
     new spell_skeram_arcane_explosion();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_temporus()
void AddSC_boss_temporus ()
Definition at line 151 of file boss_temporus.cpp.
 {
     new boss_temporus();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_twinemperors()
void AddSC_boss_twinemperors ()
Definition at line 595 of file boss_twinemperors.cpp.
 {
     new boss_veknilash();
     new boss_veklor();
 }
Referenced by AddKalimdorScripts().
AddSC_boss_viscidus()
void AddSC_boss_viscidus ()
Definition at line 302 of file boss_viscidus.cpp.
 {
     new boss_viscidus();
     new npc_glob_of_viscidus();
 }
Referenced by AddKalimdorScripts().
AddSC_bug_trio()
void AddSC_bug_trio ()
Definition at line 339 of file boss_bug_trio.cpp.
 {
     new boss_kri();
     new boss_vem();
     new boss_yauj();
 }
Referenced by AddKalimdorScripts().
AddSC_culling_of_stratholme()
void AddSC_culling_of_stratholme ()
Definition at line 1613 of file culling_of_stratholme.cpp.
 {
     new npc_arthas();
     new npc_crate_helper();
     new npc_cos_chromie_start();
     new npc_cos_chromie_middle();
     new npc_cos_stratholme_citizien();
 }
References npc_arthas::npc_arthas().
Referenced by AddKalimdorScripts().
AddSC_darkshore()
void AddSC_darkshore ()
Definition at line 425 of file zone_darkshore.cpp.
 {
     // Ours
     new npc_murkdeep();
     // Theirs
     new npc_kerlonian();
     new npc_prospector_remtravel();
 }
Referenced by AddKalimdorScripts().
AddSC_desolace()
void AddSC_desolace ()
Definition at line 511 of file zone_desolace.cpp.
 {
     // Ours
     new npc_cork_gizelton();
     // Theirs
     new npc_aged_dying_ancient_kodo();
 }
Referenced by AddKalimdorScripts().
AddSC_durotar()
void AddSC_durotar ()
Definition at line 501 of file zone_durotar.cpp.
 {
     new npc_tiger_matriarch_credit();
     new npc_tiger_matriarch();
     new npc_troll_volunteer();
     new spell_mount_check();
     new spell_voljin_war_drums();
     new spell_voodoo();
 }
Referenced by AddKalimdorScripts().
AddSC_dustwallow_marsh()
void AddSC_dustwallow_marsh ()
Definition at line 329 of file zone_dustwallow_marsh.cpp.
 {
     new npc_lady_jaina_proudmoore();
     new npc_nat_pagle();
     new npc_zelfrax();
     new spell_ooze_zap();
     new spell_ooze_zap_channel_end();
     new spell_energize_aoe();
 }
Referenced by AddKalimdorScripts().
AddSC_felwood()
void AddSC_felwood ()
Definition at line 140 of file zone_felwood.cpp.
 {
     new npcs_riverbreeze_and_silversky();
     new at_ancient_leaf();
 }
Referenced by AddKalimdorScripts().
AddSC_feralas()
void AddSC_feralas ()
Definition at line 292 of file zone_feralas.cpp.
 {
     new spell_gordunni_trap();
     new npc_shay_leafrunner();
 }
Referenced by AddKalimdorScripts().
AddSC_hyjal()
void AddSC_hyjal ()
Definition at line 253 of file hyjal.cpp.
 {
     new npc_jaina_proudmoore();
     new npc_thrall();
     new npc_tyrande_whisperwind();
 }
Referenced by AddKalimdorScripts().
AddSC_hyjal_trash()
void AddSC_hyjal_trash ()
Definition at line 1467 of file hyjal_trash.cpp.
 {
     new npc_giant_infernal();
     new npc_abomination();
     new npc_ghoul();
     new npc_necromancer();
     new npc_banshee();
     new npc_crypt_fiend();
     new npc_fel_stalker();
     new npc_frost_wyrm();
     new npc_gargoyle();
     new alliance_rifleman();
 }
Referenced by AddKalimdorScripts().
AddSC_instance_blackfathom_deeps()
void AddSC_instance_blackfathom_deeps ()
Definition at line 141 of file instance_blackfathom_deeps.cpp.
 {
     new instance_blackfathom_deeps();
 }
Referenced by AddKalimdorScripts().
AddSC_instance_culling_of_stratholme()
void AddSC_instance_culling_of_stratholme ()
Definition at line 422 of file instance_culling_of_stratholme.cpp.
 {
     new instance_culling_of_stratholme();
 }
Referenced by AddKalimdorScripts().
AddSC_instance_dire_maul()
void AddSC_instance_dire_maul ()
Definition at line 189 of file instance_dire_maul.cpp.
 {
     new instance_dire_maul();
 }
Referenced by AddKalimdorScripts().
AddSC_instance_maraudon()
void AddSC_instance_maraudon ()
Definition at line 98 of file instance_maraudon.cpp.
 {
     new instance_maraudon();
 }
Referenced by AddKalimdorScripts().
AddSC_instance_mount_hyjal()
void AddSC_instance_mount_hyjal ()
Definition at line 345 of file instance_hyjal.cpp.
 {
     new instance_hyjal();
 }
Referenced by AddKalimdorScripts().
AddSC_instance_old_hillsbrad()
void AddSC_instance_old_hillsbrad ()
Definition at line 354 of file instance_old_hillsbrad.cpp.
 {
     new instance_old_hillsbrad();
 }
Referenced by AddKalimdorScripts().
AddSC_instance_onyxias_lair()
void AddSC_instance_onyxias_lair ()
Definition at line 190 of file instance_onyxias_lair.cpp.
 {
     new instance_onyxias_lair();
 }
Referenced by AddKalimdorScripts().
AddSC_instance_ragefire_chasm()
void AddSC_instance_ragefire_chasm ()
Definition at line 37 of file instance_ragefire_chasm.cpp.
 {
     new instance_ragefire_chasm();
 }
Referenced by AddKalimdorScripts().
AddSC_instance_razorfen_downs()
void AddSC_instance_razorfen_downs ()
Definition at line 107 of file instance_razorfen_downs.cpp.
 {
     new instance_razorfen_downs();
 }
Referenced by AddKalimdorScripts().
AddSC_instance_razorfen_kraul()
void AddSC_instance_razorfen_kraul ()
Definition at line 37 of file instance_razorfen_kraul.cpp.
 {
     new instance_razorfen_kraul();
 }
Referenced by AddKalimdorScripts().
AddSC_instance_ruins_of_ahnqiraj()
void AddSC_instance_ruins_of_ahnqiraj ()
Definition at line 155 of file instance_ruins_of_ahnqiraj.cpp.
 {
     new instance_ruins_of_ahnqiraj();
 }
Referenced by AddKalimdorScripts().
AddSC_instance_temple_of_ahnqiraj()
void AddSC_instance_temple_of_ahnqiraj ()
Definition at line 177 of file instance_temple_of_ahnqiraj.cpp.
 {
     new instance_temple_of_ahnqiraj();
 }
Referenced by AddKalimdorScripts().
AddSC_instance_the_black_morass()
void AddSC_instance_the_black_morass ()
Definition at line 355 of file instance_the_black_morass.cpp.
 {
     new instance_the_black_morass();
 }
Referenced by AddKalimdorScripts().
AddSC_instance_wailing_caverns()
void AddSC_instance_wailing_caverns ()
Definition at line 127 of file instance_wailing_caverns.cpp.
 {
     new instance_wailing_caverns();
 }
Referenced by AddKalimdorScripts().
AddSC_instance_zulfarrak()
void AddSC_instance_zulfarrak ()
Definition at line 545 of file instance_zulfarrak.cpp.
 {
     new instance_zulfarrak();
     new spell_zulfarrak_summon_zulfarrak_zombies();
     new spell_zulfarrak_unlocking();
 }
Referenced by AddKalimdorScripts().
AddSC_moonglade()
void AddSC_moonglade ()
Definition at line 702 of file zone_moonglade.cpp.
 {
     new npc_bunthen_plainswind();
     new npc_great_bear_spirit();
     new npc_silva_filnaveth();
     new npc_clintar_spirit();
     new npc_omen();
     new npc_giant_spotlight();
 }
Referenced by AddKalimdorScripts().
AddSC_npc_anubisath_sentinel()
void AddSC_npc_anubisath_sentinel ()
Definition at line 280 of file mob_anubisath_sentinel.cpp.
 {
     new npc_anubisath_sentinel();
 }
Referenced by AddKalimdorScripts().
AddSC_old_hillsbrad()
void AddSC_old_hillsbrad ()
Definition at line 915 of file old_hillsbrad.cpp.
 {
     new npc_thrall_old_hillsbrad();
     new npc_taretha();
 }
Referenced by AddKalimdorScripts().
AddSC_orgrimmar()
void AddSC_orgrimmar ()
Definition at line 251 of file zone_orgrimmar.cpp.
 {
     new npc_shenthul();
     new npc_thrall_warchief();
 }
Referenced by AddKalimdorScripts().
AddSC_razorfen_downs()
void AddSC_razorfen_downs ()
Definition at line 279 of file razorfen_downs.cpp.
 {
     new npc_belnistrasz();
     new npc_idol_room_spawner();
 }
Referenced by AddKalimdorScripts().
AddSC_silithus()
void AddSC_silithus ()
Definition at line 1162 of file zone_silithus.cpp.
 {
     new go_crystalline_tear();
     new npc_anachronos_quest_trigger();
     new npc_anachronos_the_ancient();
     new npc_qiraj_war_spawn();
     new go_wind_stone();
 }
References npc_qiraj_war_spawn::npc_qiraj_war_spawn().
Referenced by AddKalimdorScripts().
AddSC_stonetalon_mountains()
void AddSC_stonetalon_mountains ()
Definition at line 171 of file zone_stonetalon_mountains.cpp.
 {
     new npc_braug_dimspirit();
     new npc_kaya_flathoof();
 }
Referenced by AddKalimdorScripts().
AddSC_tanaris()
void AddSC_tanaris ()
Definition at line 553 of file zone_tanaris.cpp.
 {
     new npc_aquementas();
     new npc_custodian_of_time();
     new npc_steward_of_time();
     new npc_stone_watcher_of_norgannon();
     new npc_tooga();
 }
Referenced by AddKalimdorScripts().
AddSC_the_barrens()
void AddSC_the_barrens ()
Definition at line 659 of file zone_the_barrens.cpp.
 {
     new npc_beaten_corpse();
     new npc_gilthares();
     new npc_taskmaster_fizzule();
     new npc_twiggy_flathead();
     new npc_wizzlecrank_shredder();
 }
Referenced by AddKalimdorScripts().
AddSC_the_black_morass()
void AddSC_the_black_morass ()
Definition at line 412 of file the_black_morass.cpp.
 {
     new npc_medivh_bm();
     new npc_time_rift();
     new spell_black_morass_corrupt_medivh();
 }
Referenced by AddKalimdorScripts().
AddSC_thousand_needles()
void AddSC_thousand_needles ()
Definition at line 379 of file zone_thousand_needles.cpp.
 {
     new npc_lakota_windsong();
     new npc_paoka_swiftmountain();
     new npc_plucky();
     new npc_enraged_panther();
     new go_panther_cage();
 }
Referenced by AddKalimdorScripts().
AddSC_thunder_bluff()
void AddSC_thunder_bluff ()
Definition at line 140 of file zone_thunder_bluff.cpp.
 {
     new npc_cairne_bloodhoof();
 }
Referenced by AddKalimdorScripts().
AddSC_ungoro_crater()
void AddSC_ungoro_crater ()
Definition at line 344 of file zone_ungoro_crater.cpp.
 {
     new npc_ame();
     new npc_ringo();
 }
Referenced by AddKalimdorScripts().
AddSC_winterspring()
void AddSC_winterspring ()
Definition at line 619 of file zone_winterspring.cpp.
 {
     // Theirs
     new npc_rivern_frostwind();
     new npc_ranshalla();
     new go_elune_fire();
 }
Referenced by AddKalimdorScripts().
AddSC_zulfarrak()
void AddSC_zulfarrak ()
Definition at line 668 of file zulfarrak.cpp.
 {
     new npc_sergeant_bly();
     new npc_weegli_blastfuse();
     new npc_shadowpriest_sezziz();
     new go_troll_cage();
 }
Referenced by AddKalimdorScripts().