Azerotcore-wotlk: deps/jemalloc/src/chunk.c File Reference
chunk.c File Reference
#include "jemalloc/internal/jemalloc_internal.h"
Macros
#define JEMALLOC_CHUNK_C_
Functions
static void * chunk_recycle (extent_tree_t *chunks_szad, extent_tree_t *chunks_ad, size_t size, size_t alignment, bool base, bool *zero)
static void chunk_record (extent_tree_t *chunks_szad, extent_tree_t *chunks_ad, void *chunk, size_t size)
void * chunk_alloc (size_t size, size_t alignment, bool base, bool *zero, dss_prec_t dss_prec)
void chunk_unmap (void *chunk, size_t size)
void chunk_dealloc (void *chunk, size_t size, bool unmap)
bool chunk_boot (void)
void chunk_prefork (void)
void chunk_postfork_parent (void)
void chunk_postfork_child (void)
Variables
const char * opt_dss = DSS_DEFAULT
size_t opt_lg_chunk = LG_CHUNK_DEFAULT
malloc_mutex_t chunks_mtx
chunk_stats_t stats_chunks
static extent_tree_t chunks_szad_mmap
static extent_tree_t chunks_ad_mmap
static extent_tree_t chunks_szad_dss
static extent_tree_t chunks_ad_dss
rtree_t * chunks_rtree
size_t chunksize
size_t chunksize_mask
size_t chunk_npages
size_t map_bias
size_t arena_maxclass
Macro Definition Documentation
JEMALLOC_CHUNK_C_
#define JEMALLOC_CHUNK_C_
Definition at line 1 of file chunk.c.
Function Documentation
chunk_alloc()
void* chunk_alloc (size_t size, size_t alignment, bool base, bool * zero, dss_prec_t dss_prec)
Definition at line 145 of file chunk.c.
 {
     void *ret;
     assert(size != 0);
     assert((size & chunksize_mask) == 0);
     assert(alignment != 0);
     assert((alignment & chunksize_mask) == 0);
     /* "primary" dss. */
     if (config_dss && dss_prec == dss_prec_primary) {
         if ((ret = chunk_recycle(&chunks_szad_dss, &chunks_ad_dss, size,
             alignment, base, zero)) != NULL)
             goto label_return;
         if ((ret = chunk_alloc_dss(size, alignment, zero)) != NULL)
             goto label_return;
     }
     /* mmap. */
     if ((ret = chunk_recycle(&chunks_szad_mmap, &chunks_ad_mmap, size,
         alignment, base, zero)) != NULL)
         goto label_return;
     if ((ret = chunk_alloc_mmap(size, alignment, zero)) != NULL)
         goto label_return;
     /* "secondary" dss. */
     if (config_dss && dss_prec == dss_prec_secondary) {
         if ((ret = chunk_recycle(&chunks_szad_dss, &chunks_ad_dss, size,
             alignment, base, zero)) != NULL)
             goto label_return;
         if ((ret = chunk_alloc_dss(size, alignment, zero)) != NULL)
             goto label_return;
     }
     /* All strategies for allocation failed. */
     ret = NULL;
 label_return:
     if (ret != NULL) {
         if (config_ivsalloc && base == false) {
             if (rtree_set(chunks_rtree, (uintptr_t)ret, 1)) {
                 chunk_dealloc(ret, size, true);
                 return (NULL);
             }
         }
         if (config_stats || config_prof) {
             bool gdump;
             malloc_mutex_lock(&chunks_mtx);
             if (config_stats)
                 stats_chunks.nchunks += (size / chunksize);
             stats_chunks.curchunks += (size / chunksize);
             if (stats_chunks.curchunks > stats_chunks.highchunks) {
                 stats_chunks.highchunks =
                     stats_chunks.curchunks;
                 if (config_prof)
                     gdump = true;
             } else if (config_prof)
                 gdump = false;
             malloc_mutex_unlock(&chunks_mtx);
             if (config_prof && opt_prof && opt_prof_gdump && gdump)
                 prof_gdump();
         }
         if (config_valgrind)
             VALGRIND_MAKE_MEM_UNDEFINED(ret, size);
     }
     assert(CHUNK_ADDR2BASE(ret) == ret);
     return (ret);
 }
References assert(), chunk_alloc_dss(), chunk_alloc_mmap(), chunk_dealloc(), chunk_recycle(), chunks_ad_dss, chunks_ad_mmap, chunks_mtx, chunks_rtree, chunks_szad_dss, chunks_szad_mmap, chunksize, chunksize_mask, config_dss, config_ivsalloc, config_prof, config_stats, config_valgrind, dss_prec_primary, dss_prec_secondary, malloc_mutex_lock(), malloc_mutex_unlock(), NULL, opt_prof, opt_prof_gdump, prof_gdump, ret, stats_chunks, VALGRIND_MAKE_MEM_UNDEFINED, and G3D::zero().
Referenced by huge_palloc().
chunk_boot()
bool chunk_boot (void)
Definition at line 337 of file chunk.c.
 {
     /* Set variables according to the value of opt_lg_chunk. */
     chunksize = (ZU(1) << opt_lg_chunk);
     assert(chunksize >= PAGE);
     chunksize_mask = chunksize - 1;
     chunk_npages = (chunksize >> LG_PAGE);
     if (config_stats || config_prof) {
         if (malloc_mutex_init(&chunks_mtx))
             return (true);
         memset(&stats_chunks, 0, sizeof(chunk_stats_t));
     }
     if (config_dss && chunk_dss_boot())
         return (true);
     extent_tree_szad_new(&chunks_szad_mmap);
     extent_tree_ad_new(&chunks_ad_mmap);
     extent_tree_szad_new(&chunks_szad_dss);
     extent_tree_ad_new(&chunks_ad_dss);
     if (config_ivsalloc) {
         chunks_rtree = rtree_new((ZU(1) << (LG_SIZEOF_PTR+3)) -
             opt_lg_chunk, base_alloc, NULL);
         if (chunks_rtree == NULL)
             return (true);
     }
     return (false);
 }
References assert(), base_alloc, chunk_dss_boot(), chunk_npages, chunks_ad_dss, chunks_ad_mmap, chunks_mtx, chunks_rtree, chunks_szad_dss, chunks_szad_mmap, chunksize, chunksize_mask, config_dss, config_ivsalloc, config_prof, config_stats, LG_PAGE, malloc_mutex_init, memset, NULL, opt_lg_chunk, PAGE, rtree_new, stats_chunks, and ZU.
chunk_dealloc()
void chunk_dealloc (void * chunk, size_t size, bool unmap)
Definition at line 315 of file chunk.c.
 {
     assert(chunk != NULL);
     assert(CHUNK_ADDR2BASE(chunk) == chunk);
     assert(size != 0);
     assert((size & chunksize_mask) == 0);
     if (config_ivsalloc)
         rtree_set(chunks_rtree, (uintptr_t)chunk, 0);
     if (config_stats || config_prof) {
         malloc_mutex_lock(&chunks_mtx);
         assert(stats_chunks.curchunks >= (size / chunksize));
         stats_chunks.curchunks -= (size / chunksize);
         malloc_mutex_unlock(&chunks_mtx);
     }
     if (unmap)
         chunk_unmap(chunk, size);
 }
References assert(), chunk_unmap(), chunks_mtx, chunks_rtree, chunksize, chunksize_mask, config_ivsalloc, config_prof, config_stats, malloc_mutex_lock(), malloc_mutex_unlock(), NULL, and stats_chunks.
Referenced by chunk_alloc(), chunk_recycle(), and huge_dalloc().
chunk_postfork_child()
void chunk_postfork_child (void)
Definition at line 388 of file chunk.c.
 {
     chunk_dss_postfork_child();
     if (config_ivsalloc)
         rtree_postfork_child(chunks_rtree);
     malloc_mutex_postfork_child(&chunks_mtx);
 }
References chunk_dss_postfork_child(), chunks_mtx, chunks_rtree, config_ivsalloc, and malloc_mutex_postfork_child.
chunk_postfork_parent()
void chunk_postfork_parent (void)
Definition at line 378 of file chunk.c.
 {
     chunk_dss_postfork_parent();
     if (config_ivsalloc)
         rtree_postfork_parent(chunks_rtree);
     malloc_mutex_postfork_parent(&chunks_mtx);
 }
References chunk_dss_postfork_parent(), chunks_mtx, chunks_rtree, config_ivsalloc, and malloc_mutex_postfork_parent.
chunk_prefork()
void chunk_prefork (void)
Definition at line 368 of file chunk.c.
 {
     malloc_mutex_prefork(&chunks_mtx);
     if (config_ivsalloc)
         rtree_prefork(chunks_rtree);
     chunk_dss_prefork();
 }
References chunk_dss_prefork(), chunks_mtx, chunks_rtree, config_ivsalloc, and malloc_mutex_prefork.
chunk_record()
static void chunk_record (extent_tree_t * chunks_szad, extent_tree_t * chunks_ad, void * chunk, size_t size) static
Definition at line 213 of file chunk.c.
 {
     bool unzeroed;
     extent_node_t *xnode, *node, *prev, *xprev, key;
     unzeroed = pages_purge(chunk, size);
     VALGRIND_MAKE_MEM_NOACCESS(chunk, size);
     /*
      * Allocate a node before acquiring chunks_mtx even though it might not
      * be needed, because base_node_alloc() may cause a new base chunk to
      * be allocated, which could cause deadlock if chunks_mtx were already
      * held.
      */
     xnode = base_node_alloc();
     /* Use xprev to implement conditional deferred deallocation of prev. */
     xprev = NULL;
     malloc_mutex_lock(&chunks_mtx);
     key.addr = (void *)((uintptr_t)chunk + size);
     node = extent_tree_ad_nsearch(chunks_ad, &key);
     /* Try to coalesce forward. */
     if (node != NULL && node->addr == key.addr) {
         /*
          * Coalesce chunk with the following address range.  This does
          * not change the position within chunks_ad, so only
          * remove/insert from/into chunks_szad.
          */
         extent_tree_szad_remove(chunks_szad, node);
         node->addr = chunk;
         node->size += size;
         node->zeroed = (node->zeroed && (unzeroed == false));
         extent_tree_szad_insert(chunks_szad, node);
     } else {
         /* Coalescing forward failed, so insert a new node. */
         if (xnode == NULL) {
             /*
              * base_node_alloc() failed, which is an exceedingly
              * unlikely failure.  Leak chunk; its pages have
              * already been purged, so this is only a virtual
              * memory leak.
              */
             goto label_return;
         }
         node = xnode;
         xnode = NULL; /* Prevent deallocation below. */
         node->addr = chunk;
         node->size = size;
         node->zeroed = (unzeroed == false);
         extent_tree_ad_insert(chunks_ad, node);
         extent_tree_szad_insert(chunks_szad, node);
     }
     /* Try to coalesce backward. */
     prev = extent_tree_ad_prev(chunks_ad, node);
     if (prev != NULL && (void *)((uintptr_t)prev->addr + prev->size) ==
         chunk) {
         /*
          * Coalesce chunk with the previous address range.  This does
          * not change the position within chunks_ad, so only
          * remove/insert node from/into chunks_szad.
          */
         extent_tree_szad_remove(chunks_szad, prev);
         extent_tree_ad_remove(chunks_ad, prev);
         extent_tree_szad_remove(chunks_szad, node);
         node->addr = prev->addr;
         node->size += prev->size;
         node->zeroed = (node->zeroed && prev->zeroed);
         extent_tree_szad_insert(chunks_szad, node);
         xprev = prev;
     }
 label_return:
     malloc_mutex_unlock(&chunks_mtx);
     /*
      * Deallocate xnode and/or xprev after unlocking chunks_mtx in order to
      * avoid potential deadlock.
      */
     if (xnode != NULL)
         base_node_dealloc(xnode);
     if (xprev != NULL)
         base_node_dealloc(xprev);
 }
References chunks_mtx, malloc_mutex_lock(), malloc_mutex_unlock(), NULL, pages_purge(), prev(), and VALGRIND_MAKE_MEM_NOACCESS.
Referenced by chunk_unmap().
chunk_recycle()
static void * chunk_recycle (extent_tree_t * chunks_szad, extent_tree_t * chunks_ad, size_t size, size_t alignment, bool base, bool * zero) static
Definition at line 45 of file chunk.c.
 {
     void *ret;
     extent_node_t *node;
     extent_node_t key;
     size_t alloc_size, leadsize, trailsize;
     bool zeroed;
     if (base) {
         /*
          * This function may need to call base_node_{,de}alloc(), but
          * the current chunk allocation request is on behalf of the
          * base allocator.  Avoid deadlock (and if that weren't an
          * issue, potential for infinite recursion) by returning NULL.
          */
         return (NULL);
     }
     alloc_size = size + alignment - chunksize;
     /* Beware size_t wrap-around. */
     if (alloc_size < size)
         return (NULL);
     key.addr = NULL;
     key.size = alloc_size;
     malloc_mutex_lock(&chunks_mtx);
     node = extent_tree_szad_nsearch(chunks_szad, &key);
     if (node == NULL) {
         malloc_mutex_unlock(&chunks_mtx);
         return (NULL);
     }
     leadsize = ALIGNMENT_CEILING((uintptr_t)node->addr, alignment) -
         (uintptr_t)node->addr;
     assert(node->size >= leadsize + size);
     trailsize = node->size - leadsize - size;
     ret = (void *)((uintptr_t)node->addr + leadsize);
     zeroed = node->zeroed;
     if (zeroed)
         *zero = true;
     /* Remove node from the tree. */
     extent_tree_szad_remove(chunks_szad, node);
     extent_tree_ad_remove(chunks_ad, node);
     if (leadsize != 0) {
         /* Insert the leading space as a smaller chunk. */
         node->size = leadsize;
         extent_tree_szad_insert(chunks_szad, node);
         extent_tree_ad_insert(chunks_ad, node);
         node = NULL;
     }
     if (trailsize != 0) {
         /* Insert the trailing space as a smaller chunk. */
         if (node == NULL) {
             /*
              * An additional node is required, but
              * base_node_alloc() can cause a new base chunk to be
              * allocated.  Drop chunks_mtx in order to avoid
              * deadlock, and if node allocation fails, deallocate
              * the result before returning an error.
              */
             malloc_mutex_unlock(&chunks_mtx);
             node = base_node_alloc();
             if (node == NULL) {
                 chunk_dealloc(ret, size, true);
                 return (NULL);
             }
             malloc_mutex_lock(&chunks_mtx);
         }
         node->addr = (void *)((uintptr_t)(ret) + size);
         node->size = trailsize;
         node->zeroed = zeroed;
         extent_tree_szad_insert(chunks_szad, node);
         extent_tree_ad_insert(chunks_ad, node);
         node = NULL;
     }
     malloc_mutex_unlock(&chunks_mtx);
     if (node != NULL)
         base_node_dealloc(node);
     if (*zero) {
         if (zeroed == false)
             memset(ret, 0, size);
         else if (config_debug) {
             size_t i;
             size_t *p = (size_t *)(uintptr_t)ret;
             VALGRIND_MAKE_MEM_DEFINED(ret, size);
             for (i = 0; i < size / sizeof(size_t); i++)
                 assert(p[i] == 0);
         }
     }
     return (ret);
 }
References ALIGNMENT_CEILING, assert(), chunk_dealloc(), chunks_mtx, chunksize, config_debug, malloc_mutex_lock(), malloc_mutex_unlock(), memset, NULL, ret, uintptr_t, VALGRIND_MAKE_MEM_DEFINED, and G3D::zero().
Referenced by chunk_alloc().
chunk_unmap()
void chunk_unmap (void * chunk, size_t size)
Definition at line 301 of file chunk.c.
 {
     assert(chunk != NULL);
     assert(CHUNK_ADDR2BASE(chunk) == chunk);
     assert(size != 0);
     assert((size & chunksize_mask) == 0);
     if (config_dss && chunk_in_dss(chunk))
         chunk_record(&chunks_szad_dss, &chunks_ad_dss, chunk, size);
     else if (chunk_dealloc_mmap(chunk, size))
         chunk_record(&chunks_szad_mmap, &chunks_ad_mmap, chunk, size);
 }
References assert(), chunk_dealloc_mmap(), chunk_in_dss(), chunk_record(), chunks_ad_dss, chunks_ad_mmap, chunks_szad_dss, chunks_szad_mmap, chunksize_mask, config_dss, and NULL.
Referenced by chunk_alloc_dss(), and chunk_dealloc().
Variable Documentation
arena_maxclass
size_t arena_maxclass
Definition at line 31 of file chunk.c.
Referenced by huge_ralloc_no_move(), icalloct(), imalloct(), ipalloct(), iralloct(), ixalloc(), s2u(), and sa2u().
chunk_npages
size_t chunk_npages
Definition at line 29 of file chunk.c.
Referenced by chunk_boot().
chunks_ad_dss
extent_tree_t chunks_ad_dss static
Definition at line 22 of file chunk.c.
Referenced by chunk_alloc(), chunk_boot(), and chunk_unmap().
chunks_ad_mmap
extent_tree_t chunks_ad_mmap static
Definition at line 20 of file chunk.c.
Referenced by chunk_alloc(), chunk_boot(), and chunk_unmap().
chunks_mtx
malloc_mutex_t chunks_mtx
Definition at line 10 of file chunk.c.
Referenced by chunk_alloc(), chunk_boot(), chunk_dealloc(), chunk_postfork_child(), chunk_postfork_parent(), chunk_prefork(), chunk_record(), and chunk_recycle().
chunks_rtree
rtree_t* chunks_rtree
Definition at line 24 of file chunk.c.
Referenced by chunk_alloc(), chunk_boot(), chunk_dealloc(), chunk_postfork_child(), chunk_postfork_parent(), chunk_prefork(), and ivsalloc().
chunks_szad_dss
extent_tree_t chunks_szad_dss static
Definition at line 21 of file chunk.c.
Referenced by chunk_alloc(), chunk_boot(), and chunk_unmap().
chunks_szad_mmap
extent_tree_t chunks_szad_mmap static
Definition at line 19 of file chunk.c.
Referenced by chunk_alloc(), chunk_boot(), and chunk_unmap().
chunksize
size_t chunksize
Definition at line 27 of file chunk.c.
Referenced by chunk_alloc(), chunk_alloc_dss(), chunk_boot(), chunk_dealloc(), chunk_recycle(), huge_malloc(), huge_ralloc(), ipalloct(), and soap_putdime().
chunksize_mask
size_t chunksize_mask
Definition at line 28 of file chunk.c.
Referenced by chunk_alloc(), chunk_alloc_dss(), chunk_alloc_mmap(), chunk_boot(), chunk_dealloc(), and chunk_unmap().
map_bias
size_t map_bias
Definition at line 30 of file chunk.c.
opt_dss
const char* opt_dss = DSS_DEFAULT
Definition at line 7 of file chunk.c.
opt_lg_chunk
size_t opt_lg_chunk = LG_CHUNK_DEFAULT
Definition at line 8 of file chunk.c.
Referenced by chunk_boot().
stats_chunks
chunk_stats_t stats_chunks
Definition at line 11 of file chunk.c.
Referenced by chunk_alloc(), chunk_boot(), and chunk_dealloc().