Azerotcore-wotlk: MMAP::MMapFactory Class Reference
MMAP::MMapFactory Class Reference
#include <MMapFactory.h>
Static Public Member Functions
static MMapMgr * createOrGetMMapMgr ()
static void clear ()
static void InitializeDisabledMaps ()
Static Public Attributes
static bool forbiddenMaps [1000] = {0}
Detailed Description
Definition at line 39 of file MMapFactory.h.
Member Function Documentation
clear()
void MMAP::MMapFactory::clear () static
Definition at line 50 of file MMapFactory.cpp.
     {
         if (g_MMapMgr)
         {
             delete g_MMapMgr;
             g_MMapMgr = nullptr;
         }
     }
References MMAP::g_MMapMgr.
Referenced by World::~World().
createOrGetMMapMgr()
MMapMgr * MMAP::MMapFactory::createOrGetMMapMgr () static
Definition at line 29 of file MMapFactory.cpp.
     {
         if (g_MMapMgr == nullptr)
         {
             g_MMapMgr = new MMapMgr();
         }
         return g_MMapMgr;
     }
References MMAP::g_MMapMgr.
Referenced by misc_commandscript::HandleGPSCommand(), mmaps_commandscript::HandleMmapLoadedTilesCommand(), mmaps_commandscript::HandleMmapLocCommand(), mmaps_commandscript::HandleMmapPathCommand(), mmaps_commandscript::HandleMmapStatsCommand(), Map::LoadMMap(), PathGenerator::PathGenerator(), World::SetInitialWorldSettings(), Map::UnloadGrid(), and Map::~Map().
InitializeDisabledMaps()
void MMAP::MMapFactory::InitializeDisabledMaps () static
Definition at line 39 of file MMapFactory.cpp.
     {
         memset(&forbiddenMaps, 0, sizeof(forbiddenMaps));
         int32 f[] = {616 /*EoE*/, 649 /*ToC25*/, 650 /*ToC5*/, -1};
         uint32 i = 0;
         while (f[i] >= 0)
         {
             forbiddenMaps[f[i++]] = true;
         }
     }
References f(), forbiddenMaps, and memset.
Referenced by World::LoadConfigSettings().
Member Data Documentation
forbiddenMaps
bool MMAP::MMapFactory::forbiddenMaps = {0} static
Definition at line 45 of file MMapFactory.h.
Referenced by InitializeDisabledMaps(), and DisableMgr::IsPathfindingEnabled().
The documentation for this class was generated from the following files:
src/common/Collision/Management/MMapFactory.h
src/common/Collision/Management/MMapFactory.cpp