Azerotcore-wotlk: MPQMgr Class Reference
MPQMgr Class Reference
#include <MPQMgr.h>
Public Member Functions
MPQMgr ()
~MPQMgr ()
void Initialize ()
FILE * GetFile (const std::string &path)
FILE * GetFileFrom (const std::string &path, MPQArchive *file)
DBC * GetDBC (const std::string &name)
std::vector< std::string > GetAllFiles (std::string extension)
Public Attributes
std::deque< MPQArchive * > Archives
int32 BaseLocale
std::set< uint32 > AvailableLocales
std::map< uint32, MPQArchive * > LocaleFiles
Static Public Attributes
static char const * Files []
static char const * Languages [] = { "enGB", "enUS", "deDE", "esES", "frFR", "koKR", "zhCN", "zhTW", "enCN", "enTW", "esMX", "ruRU" }
Protected Member Functions
void InitializeDBC ()
Private Attributes
std::mutex mutex
Detailed Description
Definition at line 28 of file MPQMgr.h.
Constructor & Destructor Documentation
MPQMgr()
MPQMgr::MPQMgr () inline
Definition at line 31 of file MPQMgr.h.
 {}
~MPQMgr()
MPQMgr::~MPQMgr () inline
Definition at line 32 of file MPQMgr.h.
 {}
Member Function Documentation
GetAllFiles()
std::vector<std::string> MPQMgr::GetAllFiles (std::string extension)
GetDBC()
DBC * MPQMgr::GetDBC (const std::string & name)
Definition at line 93 of file MPQMgr.cpp.
 {
     std::string path = "DBFilesClient\\" + name + ".dbc";
     return new DBC(GetFile(path));
 }
References GetFile(), and name.
Referenced by ExtractGameobjectModels(), and ExtractMMaps().
GetFile()
FILE * MPQMgr::GetFile (const std::string & path)
Definition at line 84 of file MPQMgr.cpp.
 {
     GUARD_RETURN(mutex, nullptr);
     MPQFile file(path.c_str());
     if (file.isEof())
         return nullptr;
     return file.GetFileStream();
 }
References mpq::file, GUARD_RETURN, and mutex.
Referenced by ChunkedData::ChunkedData(), GetDBC(), and Model::Model().
GetFileFrom()
FILE * MPQMgr::GetFileFrom (const std::string & path, MPQArchive * file)
Definition at line 99 of file MPQMgr.cpp.
 {
     GUARD_RETURN(mutex, nullptr);
     mpq_archive* mpq_a = file->mpq_a;
     uint32_t filenum;
     if (libmpq__file_number(mpq_a, path.c_str(), &filenum))
         return nullptr;
     libmpq__off_t transferred;
     libmpq__off_t size = 0;
     libmpq__file_unpacked_size(mpq_a, filenum, &size);
     // HACK: in patch.mpq some files don't want to open and give 1 for filesize
     if (size <= 1)
         return nullptr;
     uint8* buffer = new uint8[size];
     //libmpq_file_getdata
     libmpq__file_read(mpq_a, filenum, (unsigned char*)buffer, size, &transferred);
     // Pack the return into a FILE stream
     FILE* ret = tmpfile();
     if (!ret)
     {
         printf("Could not create temporary file. Please run as Administrator or root\n");
         exit(1);
     }
     fwrite(buffer, sizeof(uint8), size, ret);
     fseek(ret, 0, SEEK_SET);
     delete[] buffer;
     return ret;
 }
References buffer, mpq::file, GUARD_RETURN, libmpq__file_number(), libmpq__file_read(), libmpq__file_unpacked_size(), mutex, printf(), ret, and SEEK_SET.
Referenced by ExtractDBCs().
Initialize()
void MPQMgr::Initialize (void)
Definition at line 36 of file MPQMgr.cpp.
 {
     InitializeDBC();
     uint32 size = sizeof(Files) / sizeof(char*);
     for (uint32 i = 0; i < size; ++i)
     {
         MPQArchive* arc = new MPQArchive(std::string("Data/" + std::string(Files[i])).c_str());
         Archives.push_front(arc); // MPQ files have to be transversed in reverse order to properly account for patched files
         printf("Opened %s\n", Files[i]);
     }
 }
References Archives, Files, InitializeDBC(), and printf().
Referenced by main().
InitializeDBC()
void MPQMgr::InitializeDBC () protected
Definition at line 48 of file MPQMgr.cpp.
 {
     BaseLocale = -1;
     std::string fileName;
     uint32 size = sizeof(Languages) / sizeof(char*);
     MPQArchive* _baseLocale = nullptr;
     for (uint32 i = 0; i < size; ++i)
     {
         std::string _fileName = "Data/" + std::string(Languages[i]) + "/locale-" + std::string(Languages[i]) + ".MPQ";
         FILE* file = fopen(_fileName.c_str(), "rb");
         if (file)
         {
             if (BaseLocale == -1)
             {
                 BaseLocale = i;
                 _baseLocale = new MPQArchive(_fileName.c_str());
                 fileName = _fileName;
                 LocaleFiles[i] = _baseLocale;
             }
             else
                 LocaleFiles[i] = new MPQArchive(_fileName.c_str());
             AvailableLocales.insert(i);
             printf("Detected locale: %s\n", Languages[i]);
         }
     }
     Archives.push_front(_baseLocale);
     if (BaseLocale == -1)
     {
         printf("No locale data detected. Please make sure that the executable is in the same folder as your WoW installation.\n");
         ABORT();
     }
     else
         printf("Using default locale: %s\n", Languages[BaseLocale]);
 }
References ABORT, Archives, AvailableLocales, BaseLocale, mpq::file, Languages, LocaleFiles, and printf().
Referenced by Initialize().
Member Data Documentation
Archives
std::deque<MPQArchive*> MPQMgr::Archives
Definition at line 40 of file MPQMgr.h.
Referenced by Initialize(), and InitializeDBC().
AvailableLocales
std::set<uint32> MPQMgr::AvailableLocales
Definition at line 42 of file MPQMgr.h.
Referenced by ExtractDBCs(), and InitializeDBC().
BaseLocale
int32 MPQMgr::BaseLocale
Definition at line 41 of file MPQMgr.h.
Referenced by ExtractDBCs(), and InitializeDBC().
Files
char const * MPQMgr::Files static
Initial value:
=
{
    "common.MPQ",
    "common-2.MPQ",
    "expansion.MPQ",
    "lichking.MPQ",
    "patch.MPQ",
    "patch-2.MPQ",
    "patch-3.MPQ"
}
Definition at line 45 of file MPQMgr.h.
Referenced by Initialize().
Languages
char const * MPQMgr::Languages = { "enGB", "enUS", "deDE", "esES", "frFR", "koKR", "zhCN", "zhTW", "enCN", "enTW", "esMX", "ruRU" } static
Definition at line 46 of file MPQMgr.h.
Referenced by ExtractDBCs(), and InitializeDBC().
LocaleFiles
std::map<uint32, MPQArchive*> MPQMgr::LocaleFiles
Definition at line 43 of file MPQMgr.h.
Referenced by ExtractDBCs(), and InitializeDBC().
mutex
std::mutex MPQMgr::mutex private
Definition at line 50 of file MPQMgr.h.
Referenced by GetFile(), and GetFileFrom().
The documentation for this class was generated from the following files:
src/tools/mesh_extractor/MPQMgr.h
src/tools/mesh_extractor/MPQMgr.cpp