Azerotcore-wotlk: deps/g3dlite/include/G3D/Matrix.h File Reference
Matrix.h File Reference
#include "G3D/g3dmath.h"
#include "G3D/Vector3.h"
#include "G3D/Vector4.h"
#include "G3D/Matrix3.h"
#include "G3D/Matrix4.h"
#include "G3D/ReferenceCount.h"
Classes
class G3D::Matrix
class G3D::Matrix::Impl
class G3D::Matrix::SortRank
Namespaces
G3D
Macros
#define DECLARE_METHODS_1(method)
Functions
G3D::Matrix operator- (const G3D::Matrix::T &v, const G3D::Matrix &M)
G3D::Matrix operator* (const G3D::Matrix::T &v, const G3D::Matrix &M)
G3D::Matrix operator+ (const G3D::Matrix::T &v, const G3D::Matrix &M)
G3D::Matrix abs (const G3D::Matrix &M)
Detailed Description
Author
Morgan McGuire, http://graphics.cs.williams.edu
@created 2005-10-23 @edited 2007-07-18
Definition in file Matrix.h.
Macro Definition Documentation
DECLARE_METHODS_1
#define DECLARE_METHODS_1 (method)
Value:
    inline Matrix method() const {\
        Matrix C(impl->R, impl->C);\
        impl->method(*C.impl);\
        return C;\
    }\
    void method(Matrix& out) const;
Definition at line 446 of file Matrix.h.
Function Documentation
abs()
G3D::Matrix abs (const G3D::Matrix & M) inline
Definition at line 632 of file Matrix.h.
{
     return M.abs();
 }
Referenced by AuraApplication::_HandleEffect(), Player::_LoadMail(), Player::ApplyEnchantment(), AuraEffect::CalculateAmount(), instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::CheckAchievementCriteriaMeet(), Spell::CheckItems(), LootTemplate::LootGroup::CheckLootRefs(), LootTemplate::CheckLootRefs(), BattlegroundQueue::CheckNormalMatch(), boss_isle_of_conquest::boss_isle_of_conquestAI::CheckRageBuff(), WorldSession::ComputeNewClockDelta(), LootTemplate::CopyConditions(), BattlegroundQueue::FillPlayersToBG(), BattlegroundQueue::FillPlayersToBGWithSpecific(), SpellInfo::GetDuration(), SpellInfo::GetMaxDuration(), getSlopeAngle(), getSlopeAngleAbs(), modify_commandscript::HandleModifyMoneyCommand(), LootTemplate::LootGroup::HasQuestDrop(), LootTemplate::HasQuestDrop(), LootTemplate::HasQuestDropForPlayer(), LootTemplate::LootGroup::HasQuestDropForPlayer(), ChaseAngle::IsAngleOkay(), Aura::IsAuraStronger(), boss_netherspite::boss_netherspiteAI::IsBetween(), SpellInfo::IsStrongerAuraActive(), PathGenerator::IsWalkableClimb(), BattlegroundQueue::SelectionPool::KickGroup(), ConditionMgr::LoadConditions(), Player::LoadFromDB(), ObjectMgr::LoadQuests(), SmartAIMgr::LoadSmartAIFromDB(), SpellMgr::LoadSpellAreas(), SpellMgr::LoadSpellLinked(), LootTemplate::Process(), LootTemplate::LootGroup::Process(), Player::RewardReputation(), Player::SatisfyQuestPreviousQuest(), Map::ScriptsProcess(), BigNumber::SetDword(), soap_dateTime2s(), instance_the_black_morass::instance_the_black_morass_InstanceMapScript::SummonPortalKeeper(), Spell::TakeReagents(), PetAI::UpdateAI(), World::UpdateGlobalPlayerMails(), BattlefieldWG::UpdateTenacity(), and Guild::BankTab::WriteSlotPacket().
operator*()
G3D::Matrix operator* (const G3D::Matrix::T & v, const G3D::Matrix & M) inline
Definition at line 624 of file Matrix.h.
{
     return M * v;
 }
operator+()
G3D::Matrix operator+ (const G3D::Matrix::T & v, const G3D::Matrix & M) inline
Definition at line 628 of file Matrix.h.
{
     return M + v;
 }
operator-()
G3D::Matrix operator- (const G3D::Matrix::T & v, const G3D::Matrix & M) inline
Definition at line 620 of file Matrix.h.
{
     return M.lsub(v);
 }
References G3D::Matrix::lsub().