Azerotcore-wotlk: npc_sergeant_bly::npc_sergeant_blyAI Struct Reference
npc_sergeant_bly::npc_sergeant_blyAI Struct Reference
Public Member Functions
npc_sergeant_blyAI (Creature *creature)
void InitializeAI () override
void Reset () override
void MovementInform (uint32 type, uint32) override
void UpdateAI (uint32 diff) override
void DoAction (int32) override
void switchFactionIfAlive (uint32 entry, Player *target)
void sGossipSelect (Player *player, uint32, uint32 gossipListId) override
void sGossipHello (Player *player) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * instance
bool startedFight
uint32 postGossipStep
uint32 Text_Timer
uint32 ShieldBash_Timer
uint32 Revenge_Timer
ObjectGuid PlayerGUID
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 58 of file zulfarrak.cpp.
Constructor & Destructor Documentation
npc_sergeant_blyAI()
npc_sergeant_bly::npc_sergeant_blyAI::npc_sergeant_blyAI (Creature * creature) inline
Definition at line 60 of file zulfarrak.cpp.
                                                : ScriptedAI(creature)
         {
             instance = creature->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), and instance.
Member Function Documentation
DoAction()
void npc_sergeant_bly::npc_sergeant_blyAI::DoAction (int32) inline override virtual
Reimplemented from UnitAI.
Definition at line 177 of file zulfarrak.cpp.
         {
             postGossipStep = 1;
             Text_Timer = 0;
         }
References postGossipStep, and Text_Timer.
Referenced by sGossipSelect().
InitializeAI()
void npc_sergeant_bly::npc_sergeant_blyAI::InitializeAI () inline override virtual
Reimplemented from UnitAI.
Definition at line 65 of file zulfarrak.cpp.
         {
             startedFight = false;
             me->SetFaction(FACTION_FRIENDLY);
             postGossipStep = 0;
             Text_Timer = 0;
             me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
         }
References FACTION_FRIENDLY, ScriptedAI::me, postGossipStep, Unit::SetFaction(), Object::SetFlag(), startedFight, Text_Timer, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
MovementInform()
void npc_sergeant_bly::npc_sergeant_blyAI::MovementInform (uint32 type, uint32) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 89 of file zulfarrak.cpp.
         {
             if (type != POINT_MOTION_TYPE)
             {
                 return;
             }
             if (instance->GetData(DATA_PYRAMID) == PYRAMID_WAVE_3)
             {
                 if (Creature* shadowpriest = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_SHADOWPRIEST_SEZZZIZ)))
                 {
                     AttackStart(shadowpriest);
                     shadowpriest->CallAssistance();
                 }
             }
         }
References ScriptedAI::AttackStart(), DATA_PYRAMID, ObjectAccessor::GetCreature(), ZoneScript::GetData(), InstanceScript::GetGuidData(), instance, ScriptedAI::me, NPC_SHADOWPRIEST_SEZZZIZ, POINT_MOTION_TYPE, and PYRAMID_WAVE_3.
Reset()
void npc_sergeant_bly::npc_sergeant_blyAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 83 of file zulfarrak.cpp.
         {
             ShieldBash_Timer = 5000;
             Revenge_Timer = 8000;
         }
References Revenge_Timer, and ShieldBash_Timer.
sGossipHello()
void npc_sergeant_bly::npc_sergeant_blyAI::sGossipHello (Player * player) inline override virtual
Reimplemented from UnitAI.
Definition at line 212 of file zulfarrak.cpp.
         {
             if (instance->GetData(DATA_PYRAMID) >= PYRAMID_DESTROY_GATES && !startedFight)
             {
                 startedFight = true;
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_BLY, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
                 SendGossipMenuFor(player, 1517, me->GetGUID());
             }
             else
             {
                 if (instance->GetData(DATA_PYRAMID) == PYRAMID_NOT_STARTED)
                 {
                     SendGossipMenuFor(player, 1515, me->GetGUID());
                 }
                 else
                 {
                     SendGossipMenuFor(player, 1516, me->GetGUID());
                 }
             }
         }
References AddGossipItemFor(), DATA_PYRAMID, ZoneScript::GetData(), Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, GOSSIP_BLY, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, instance, ScriptedAI::me, PYRAMID_DESTROY_GATES, PYRAMID_NOT_STARTED, SendGossipMenuFor(), and startedFight.
sGossipSelect()
void npc_sergeant_bly::npc_sergeant_blyAI::sGossipSelect (Player * player, uint32 , uint32 gossipListId) inline override virtual
Reimplemented from UnitAI.
Definition at line 199 of file zulfarrak.cpp.
         {
             uint32 const action = player->PlayerTalkClass->GetGossipOptionAction(gossipListId);
             ClearGossipMenuFor(player);
             if (action == GOSSIP_ACTION_INFO_DEF + 1)
             {
                 CloseGossipMenuFor(player);
                 PlayerGUID = player->GetGUID();
                 DoAction(0);
             }
         }
References ClearGossipMenuFor(), CloseGossipMenuFor(), DoAction(), PlayerMenu::GetGossipOptionAction(), Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, PlayerGUID, and Player::PlayerTalkClass.
switchFactionIfAlive()
void npc_sergeant_bly::npc_sergeant_blyAI::switchFactionIfAlive (uint32 entry, Player * target) inline
Definition at line 183 of file zulfarrak.cpp.
         {
             if (Creature* crew = ObjectAccessor::GetCreature(*me, instance->GetGuidData(entry)))
             {
                 if (crew->IsAlive())
                 {
                     crew->SetFaction(FACTION_MONSTER);
                     if (target)
                     {
                         crew->AI()->AttackStart(target);
                     }
                 }
             }
         }
References FACTION_MONSTER, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), instance, and ScriptedAI::me.
Referenced by UpdateAI().
UpdateAI()
void npc_sergeant_bly::npc_sergeant_blyAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 106 of file zulfarrak.cpp.
         {
             if (postGossipStep > 0 && postGossipStep < 4)
             {
                 if (Text_Timer <= diff)
                 {
                     switch (postGossipStep)
                     {
                         case 1:
                             //weegli doesn't fight - he goes & blows up the door
                             if (Creature* pWeegli = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_WEEGLI)))
{
                                 pWeegli->AI()->DoAction(0);
                             }
                             Talk(SAY_1);
                             Text_Timer = 5000;
                             break;
                         case 2:
                             Talk(SAY_2);
                             Text_Timer = 5000;
                             break;
                         case 3:
                             me->SetFaction(FACTION_MONSTER);
                             Player* target = ObjectAccessor::GetPlayer(*me, PlayerGUID);
                             switchFactionIfAlive(NPC_RAVEN, target);
                             switchFactionIfAlive(NPC_ORO, target);
                             switchFactionIfAlive(NPC_MURTA, target);
                             if (target)
{
                                 AttackStart(target);
                             }
                     }
                     postGossipStep++;
                 }
                 else
                 {
                     Text_Timer -= diff;
                 }
             }
             if (!UpdateVictim())
             {
                 return;
             }
             if (ShieldBash_Timer <= diff)
             {
                 DoCastVictim(SPELL_SHIELD_BASH);
                 ShieldBash_Timer = 15000;
             }
             else
             {
                 ShieldBash_Timer -= diff;
             }
             if (Revenge_Timer <= diff)
             {
                 DoCastVictim(SPELL_REVENGE);
                 Revenge_Timer = 10000;
             }
             else
             {
                 Revenge_Timer -= diff;
             }
             DoMeleeAttackIfReady();
         }
References ScriptedAI::AttackStart(), diff(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), FACTION_MONSTER, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), ObjectAccessor::GetPlayer(), instance, ScriptedAI::me, NPC_MURTA, NPC_ORO, NPC_RAVEN, NPC_WEEGLI, PlayerGUID, postGossipStep, Revenge_Timer, SAY_1, SAY_2, Unit::SetFaction(), ShieldBash_Timer, SPELL_REVENGE, SPELL_SHIELD_BASH, switchFactionIfAlive(), CreatureAI::Talk(), Text_Timer, and CreatureAI::UpdateVictim().
Member Data Documentation
instance
InstanceScript* npc_sergeant_bly::npc_sergeant_blyAI::instance
Definition at line 74 of file zulfarrak.cpp.
Referenced by MovementInform(), npc_sergeant_blyAI(), sGossipHello(), switchFactionIfAlive(), and UpdateAI().
PlayerGUID
ObjectGuid npc_sergeant_bly::npc_sergeant_blyAI::PlayerGUID
Definition at line 81 of file zulfarrak.cpp.
Referenced by sGossipSelect(), and UpdateAI().
postGossipStep
uint32 npc_sergeant_bly::npc_sergeant_blyAI::postGossipStep
Definition at line 77 of file zulfarrak.cpp.
Referenced by DoAction(), InitializeAI(), and UpdateAI().
Revenge_Timer
uint32 npc_sergeant_bly::npc_sergeant_blyAI::Revenge_Timer
Definition at line 80 of file zulfarrak.cpp.
Referenced by Reset(), and UpdateAI().
ShieldBash_Timer
uint32 npc_sergeant_bly::npc_sergeant_blyAI::ShieldBash_Timer
Definition at line 79 of file zulfarrak.cpp.
Referenced by Reset(), and UpdateAI().
startedFight
bool npc_sergeant_bly::npc_sergeant_blyAI::startedFight
Definition at line 76 of file zulfarrak.cpp.
Referenced by InitializeAI(), and sGossipHello().
Text_Timer
uint32 npc_sergeant_bly::npc_sergeant_blyAI::Text_Timer
Definition at line 78 of file zulfarrak.cpp.
Referenced by DoAction(), InitializeAI(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/ZulFarrak/zulfarrak.cpp