Azerotcore-wotlk: boss_ick::boss_ickAI Struct Reference
boss_ick::boss_ickAI Struct Reference
Public Member Functions
boss_ickAI (Creature *creature)
void Reset () override
bool CanAIAttack (const Unit *) const override
void EnterCombat (Unit *) override
void SpellHitTarget (Unit *target, const SpellInfo *spell) override
Creature * GetKrick ()
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *who) override
void JustSummoned (Creature *) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
EventMap events
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 78 of file boss_krickandick.cpp.
Constructor & Destructor Documentation
boss_ickAI()
boss_ick::boss_ickAI::boss_ickAI (Creature * creature) inline
Definition at line 80 of file boss_krickandick.cpp.
                                        : ScriptedAI(creature)
         {
             pInstance = creature->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), and pInstance.
Member Function Documentation
CanAIAttack()
bool boss_ick::boss_ickAI::CanAIAttack (const Unit *) const inline override virtual
Reimplemented from UnitAI.
Definition at line 96 of file boss_krickandick.cpp.
         {
             return pInstance && pInstance->GetData(DATA_INSTANCE_PROGRESS) >= INSTANCE_PROGRESS_FINISHED_INTRO;
         }
References DATA_INSTANCE_PROGRESS, ZoneScript::GetData(), INSTANCE_PROGRESS_FINISHED_INTRO, and pInstance.
DamageTaken()
void boss_ick::boss_ickAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 141 of file boss_krickandick.cpp.
         {
             if (damage >= me->GetHealth())
                 if (Creature* krick = GetKrick())
                 {
                     krick->InterruptNonMeleeSpells(true);
                     krick->RemoveAllAuras();
                     Position myPos(*me), exitPos;
                     float ang = me->GetOrientation() + 3 * M_PI / 2;
                     float dist = 3.0f;
                     exitPos.Relocate(myPos.GetPositionX() + dist * cos(ang), myPos.GetPositionY() + dist * sin(ang), 515.0f, M_PI);
                     exitPos.m_positionZ = me->GetMap()->GetHeight(exitPos.GetPositionX(), exitPos.GetPositionY(), exitPos.GetPositionZ());
                     if (exitPos.GetPositionZ() < 505.0f || exitPos.GetPositionZ() > 512.0f || !me->IsWithinLOS(exitPos.GetPositionX(), exitPos.GetPositionY(), exitPos.GetPositionZ()))
                         exitPos.Relocate(myPos);
                     krick->_ExitVehicle(&exitPos);
                     krick->AI()->DoAction(1);
                 }
         }
References Unit::GetHealth(), Map::GetHeight(), GetKrick(), WorldObject::GetMap(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), WorldObject::IsWithinLOS(), Position::m_positionZ, ScriptedAI::me, and Position::Relocate().
EnterCombat()
void boss_ick::boss_ickAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 101 of file boss_krickandick.cpp.
         {
             if (Creature* k = GetKrick())
                 k->AI()->Talk(SAY_AGGRO);
             DoZoneInCombat();
             events.Reset();
             events.RescheduleEvent(EVENT_SPELL_TOXIC_WASTE, urand(3000, 5000));
             events.RescheduleEvent(EVENT_SPELL_MIGHTY_KICK, urand(10000, 20000));
             events.RescheduleEvent(EVENT_SPELL_SHADOW_BOLT, 10000);
             events.RescheduleEvent(EVENT_SPECIAL, 25000);
             if (pInstance)
                 pInstance->SetData(DATA_ICK, IN_PROGRESS);
         }
References DATA_ICK, CreatureAI::DoZoneInCombat(), EVENT_SPECIAL, EVENT_SPELL_MIGHTY_KICK, EVENT_SPELL_SHADOW_BOLT, EVENT_SPELL_TOXIC_WASTE, GetKrick(), IN_PROGRESS, pInstance, SAY_AGGRO, ZoneScript::SetData(), and urand().
GetKrick()
Creature* boss_ick::boss_ickAI::GetKrick () inline
Definition at line 133 of file boss_krickandick.cpp.
         {
             if (Vehicle* v = me->GetVehicleKit())
                 if (Unit* p = v->GetPassenger(0))
                     return p->ToCreature();
             return (Creature*)nullptr;
         }
References Unit::GetVehicleKit(), ScriptedAI::me, and Object::ToCreature().
Referenced by DamageTaken(), EnterCombat(), KilledUnit(), and UpdateAI().
JustDied()
void boss_ick::boss_ickAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 257 of file boss_krickandick.cpp.
         {
             if (pInstance)
                 pInstance->SetData(DATA_ICK, DONE);
             me->RemoveAllAuras();
         }
References DATA_ICK, DONE, ScriptedAI::me, pInstance, Unit::RemoveAllAuras(), and ZoneScript::SetData().
JustSummoned()
void boss_ick::boss_ickAI::JustSummoned (Creature *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 276 of file boss_krickandick.cpp.
         {
         }
KilledUnit()
void boss_ick::boss_ickAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 264 of file boss_krickandick.cpp.
         {
             // if during pursuit ick kills his target, set to aggressive again
             if (who && me->GetVictim() && who->GetGUID() == me->GetVictim()->GetGUID())
                 if (me->GetReactState() == REACT_PASSIVE)
                     me->SetReactState(REACT_AGGRESSIVE);
             if (who->GetTypeId() == TYPEID_PLAYER)
                 if (Creature* k = GetKrick())
                     k->AI()->Talk(RAND(SAY_SLAY_1, SAY_SLAY_2));
         }
References Object::GetGUID(), GetKrick(), Creature::GetReactState(), Object::GetTypeId(), Unit::GetVictim(), ScriptedAI::me, RAND(), REACT_AGGRESSIVE, REACT_PASSIVE, SAY_SLAY_1, SAY_SLAY_2, Creature::SetReactState(), and TYPEID_PLAYER.
Reset()
void boss_ick::boss_ickAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 88 of file boss_krickandick.cpp.
         {
             me->SetReactState(REACT_AGGRESSIVE);
             events.Reset();
             if (pInstance)
                 pInstance->SetData(DATA_ICK, NOT_STARTED);
         }
References DATA_ICK, ScriptedAI::me, NOT_STARTED, pInstance, REACT_AGGRESSIVE, ZoneScript::SetData(), and Creature::SetReactState().
SpellHitTarget()
void boss_ick::boss_ickAI::SpellHitTarget (Unit * target, const SpellInfo * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 116 of file boss_krickandick.cpp.
         {
             if (!target || !spell)
                 return;
             if (spell->Id == SPELL_PURSUIT && target->GetTypeId() == TYPEID_PLAYER)
             {
                 WorldPacket data;
                 ChatHandler::BuildChatPacket(data, CHAT_MSG_RAID_BOSS_EMOTE, LANG_UNIVERSAL, me, nullptr, EMOTE_ICK_CHASING);
                 target->ToPlayer()->GetSession()->SendPacket(&data);
                 AttackStart(target);
                 me->SetReactState(REACT_PASSIVE);
                 events.RescheduleEvent(EVENT_SET_REACT_AGGRESSIVE, 12000);
             }
         }
References ScriptedAI::AttackStart(), ChatHandler::BuildChatPacket(), CHAT_MSG_RAID_BOSS_EMOTE, EMOTE_ICK_CHASING, EVENT_SET_REACT_AGGRESSIVE, Player::GetSession(), Object::GetTypeId(), SpellInfo::Id, LANG_UNIVERSAL, ScriptedAI::me, REACT_PASSIVE, WorldSession::SendPacket(), Creature::SetReactState(), SPELL_PURSUIT, Object::ToPlayer(), and TYPEID_PLAYER.
UpdateAI()
void boss_ick::boss_ickAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 162 of file boss_krickandick.cpp.
         {
             if (!UpdateVictim())
                 return;
             if (me->GetVictim())
             {
                 float x, y, z;
                 me->GetVictim()->GetPosition(x, y, z);
                 if (KrickCenterPos.GetExactDist(x, y, z) > 80.0f || z > KrickCenterPos.GetPositionZ() + 20.0f || z < KrickCenterPos.GetPositionZ() - 20.0f)
                 {
                     me->SetHealth(me->GetMaxHealth());
                     EnterEvadeMode();
                     return;
                 }
             }
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING | UNIT_STATE_STUNNED))
                 return;
             switch(events.ExecuteEvent())
             {
                 case 0:
                     break;
                 case EVENT_SPELL_TOXIC_WASTE:
                     if (Creature* k = GetKrick())
                         if (!k->HasUnitState(UNIT_STATE_CASTING))
                             if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 40.0f, true))
{
                                 k->CastSpell(target, SPELL_TOXIC_WASTE);
                                 events.RepeatEvent(urand(7000, 10000));
                                 break;
                             }
                     events.RepeatEvent(2500);
                     break;
                 case EVENT_SPELL_MIGHTY_KICK:
                     me->CastSpell(me->GetVictim(), SPELL_MIGHTY_KICK, false);
                     events.RepeatEvent(urand(20000, 25000));
                     break;
                 case EVENT_SPELL_SHADOW_BOLT:
                     if (Creature* k = GetKrick())
                         if (!k->HasUnitState(UNIT_STATE_CASTING))
                             if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 35.0f, true))
{
                                 k->CastSpell(target, SPELL_SHADOW_BOLT);
                                 events.RepeatEvent(14000);
                                 break;
                             }
                     events.RepeatEvent(2500);
                     break;
                 case EVENT_SET_REACT_AGGRESSIVE:
                     me->SetReactState(REACT_AGGRESSIVE);
                     if (!UpdateVictim())
                         return;
                     break;
                 case EVENT_SPECIAL:
                     switch(urand(0, 2))
                     {
                         case 0: // Pursuit
                             if (Creature* k = GetKrick())
                                 k->AI()->Talk(RAND(SAY_TARGET_1, SAY_TARGET_2, SAY_TARGET_3));
                             if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 70.0f, true))
                                 me->CastSpell(target, SPELL_PURSUIT, false);
                             break;
                         case 1: // Poison Nova
                             if (Creature* k = GetKrick())
{
                                 k->AI()->Talk(SAY_ORDER_BLOW);
                                 Talk(EMOTE_ICK_POISON);
                             }
                             me->CastSpell(me, SPELL_POISON_NOVA, false);
                             break;
                         case 2: // Explosive Barrage
                             if (Creature* k = GetKrick())
{
                                 k->AI()->Talk(SAY_ORDER_STOP);
                                 k->AI()->Talk(EMOTE_KRICK_MINES);
                                 k->InterruptNonMeleeSpells(false);
                                 me->InterruptNonMeleeSpells(false);
                                 k->CastSpell(k, SPELL_EXPLOSIVE_BARRAGE_KRICK, false);
                                 me->CastSpell(me, SPELL_EXPLOSIVE_BARRAGE_ICK, false);
                             }
                             events.DelayEvents(20000);
                             break;
                     }
                     events.RepeatEvent(urand(25000, 30000));
                     break;
             }
             DoMeleeAttackIfReady();
         }
References Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), EMOTE_ICK_POISON, EMOTE_KRICK_MINES, CreatureAI::EnterEvadeMode(), EVENT_SET_REACT_AGGRESSIVE, EVENT_SPECIAL, EVENT_SPELL_MIGHTY_KICK, EVENT_SPELL_SHADOW_BOLT, EVENT_SPELL_TOXIC_WASTE, Position::GetExactDist(), GetKrick(), Unit::GetMaxHealth(), Position::GetPosition(), Position::GetPositionZ(), Unit::GetVictim(), Unit::HasUnitState(), Unit::InterruptNonMeleeSpells(), KrickCenterPos, ScriptedAI::me, RAND(), REACT_AGGRESSIVE, SAY_ORDER_BLOW, SAY_ORDER_STOP, SAY_TARGET_1, SAY_TARGET_2, SAY_TARGET_3, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Unit::SetHealth(), Creature::SetReactState(), SPELL_EXPLOSIVE_BARRAGE_ICK, SPELL_EXPLOSIVE_BARRAGE_KRICK, SPELL_MIGHTY_KICK, SPELL_POISON_NOVA, SPELL_PURSUIT, SPELL_SHADOW_BOLT, SPELL_TOXIC_WASTE, CreatureAI::Talk(), UNIT_STATE_CASTING, UNIT_STATE_STUNNED, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
events
EventMap boss_ick::boss_ickAI::events
Definition at line 86 of file boss_krickandick.cpp.
pInstance
InstanceScript* boss_ick::boss_ickAI::pInstance
Definition at line 85 of file boss_krickandick.cpp.
Referenced by boss_ickAI(), CanAIAttack(), EnterCombat(), JustDied(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/FrozenHalls/PitOfSaron/boss_krickandick.cpp