Azerotcore-wotlk: HyperlinkDataTokenizer Class Reference
HyperlinkDataTokenizer Class Reference
Public Member Functions
HyperlinkDataTokenizer (std::string_view str)
template<typename T >
bool TryConsumeTo (T &val)
bool IsEmpty ()
Private Attributes
std::string_view _str
Detailed Description
Definition at line 27 of file HyperlinkTags.cpp.
Constructor & Destructor Documentation
HyperlinkDataTokenizer()
HyperlinkDataTokenizer::HyperlinkDataTokenizer (std::string_view str) inline
Definition at line 30 of file HyperlinkTags.cpp.
 : _str(str) {}
Member Function Documentation
IsEmpty()
bool HyperlinkDataTokenizer::IsEmpty () inline
Definition at line 54 of file HyperlinkTags.cpp.
 { return _str.empty(); }
References _str.
Referenced by Acore::Hyperlinks::LinkTags::achievement::StoreTo(), Acore::Hyperlinks::LinkTags::glyph::StoreTo(), Acore::Hyperlinks::LinkTags::item::StoreTo(), Acore::Hyperlinks::LinkTags::quest::StoreTo(), Acore::Hyperlinks::LinkTags::enchant::StoreTo(), Acore::Hyperlinks::LinkTags::spell::StoreTo(), Acore::Hyperlinks::LinkTags::talent::StoreTo(), Acore::Hyperlinks::LinkTags::trade::StoreTo(), and TryConsumeTo().
TryConsumeTo()
template<typename T > bool HyperlinkDataTokenizer::TryConsumeTo (T & val) inline
Definition at line 33 of file HyperlinkTags.cpp.
         {
             if (IsEmpty())
                 return false;
             if (size_t off = _str.find(HYPERLINK_DATA_DELIMITER); off != std::string_view::npos)
             {
                 if (!Acore::Hyperlinks::LinkTags::base_tag::StoreTo(val, _str.substr(0, off)))
                     return false;
                 _str = _str.substr(off+1);
             }
             else
             {
                 if (!Acore::Hyperlinks::LinkTags::base_tag::StoreTo(val, _str))
                     return false;
                 _str = std::string_view();
             }
             return true;
         }
References _str, HYPERLINK_DATA_DELIMITER, IsEmpty(), and Acore::Hyperlinks::LinkTags::base_tag::StoreTo().
Referenced by Acore::Hyperlinks::LinkTags::achievement::StoreTo(), Acore::Hyperlinks::LinkTags::glyph::StoreTo(), Acore::Hyperlinks::LinkTags::item::StoreTo(), Acore::Hyperlinks::LinkTags::quest::StoreTo(), Acore::Hyperlinks::LinkTags::enchant::StoreTo(), Acore::Hyperlinks::LinkTags::spell::StoreTo(), Acore::Hyperlinks::LinkTags::talent::StoreTo(), and Acore::Hyperlinks::LinkTags::trade::StoreTo().
Member Data Documentation
_str
std::string_view HyperlinkDataTokenizer::_str private
Definition at line 57 of file HyperlinkTags.cpp.
Referenced by IsEmpty(), and TryConsumeTo().
The documentation for this class was generated from the following file:
src/server/game/Chat/HyperlinkTags.cpp