Azerotcore-wotlk: Battlefield Class Reference
Battlefield Class Reference abstract
#include <Battlefield.h>
Public Types
typedef std::vector< BfCapturePoint * > BfCapturePointVector
typedef of map witch store capturepoint and the associate gameobject entry
Public Member Functions
Battlefield ()
Constructor.
~Battlefield () override
Destructor.
virtual bool SetupBattlefield ()
Call this to init the Battlefield.
void SendUpdateWorldState (uint32 field, uint32 value)
Update data of a worldstate to all players present in zone.
virtual bool Update (uint32 diff)
Called every time for update bf data and time.
void InvitePlayersInZoneToQueue ()
Invite all players in zone to join the queue, called x minutes before battle start in Update()
void InvitePlayersInQueueToWar ()
Invite all players in queue to join battle on battle start.
void InvitePlayersInZoneToWar ()
Invite all players in zone to join battle on battle start.
virtual void HandleKill (Player *, Unit *)
Called when a Unit is kill in battlefield zone.
uint32 GetTypeId ()
uint32 GetZoneId ()
void TeamApplyBuff (TeamId team, uint32 spellId, uint32 spellId2=0)
bool IsWarTime ()
Return true if battle is start, false if battle is not started.
void ToggleBattlefield (bool enable)
Enable or Disable battlefield.
bool IsEnabled ()
Return if battlefield is enable.
void KickPlayerFromBattlefield (ObjectGuid guid)
Kick player from battlefield and teleport him to kick-point location.
void HandlePlayerEnterZone (Player *player, uint32 zone)
Called when player (player) enter in zone.
void HandlePlayerLeaveZone (Player *player, uint32 zone)
Called when player (player) leave the zone.
uint64 GetData64 (uint32 dataId) const override
void SetData64 (uint32 dataId, uint64 value) override
uint32 GetData (uint32 dataId) const override
void SetData (uint32 dataId, uint32 value) override
virtual void UpdateData (uint32 index, int32 pad)
TeamId GetDefenderTeam ()
TeamId GetAttackerTeam ()
TeamId GetOtherTeam (TeamId team)
void SetDefenderTeam (TeamId team)
Group * GetFreeBfRaid (TeamId TeamId)
Find a not full battlefield group, if there is no, create one.
Group * GetGroupPlayer (ObjectGuid guid, TeamId TeamId)
Return battlefield group where player is.
bool AddOrSetPlayerToCorrectBfGroup (Player *player)
Force player to join a battlefield group.
GraveyardStruct const * GetClosestGraveyard (Player *player)
virtual void AddPlayerToResurrectQueue (ObjectGuid npc_guid, ObjectGuid player_guid)
void RemovePlayerFromResurrectQueue (ObjectGuid player_guid)
void SetGraveyardNumber (uint32 number)
BfGraveyard * GetGraveyardById (uint32 id) const
Creature * SpawnCreature (uint32 entry, float x, float y, float z, float o, TeamId teamId)
Creature * SpawnCreature (uint32 entry, Position pos, TeamId teamId)
GameObject * SpawnGameObject (uint32 entry, float x, float y, float z, float o)
Creature * GetCreature (ObjectGuid const guid)
GameObject * GetGameObject (ObjectGuid const guid)
virtual void OnBattleStart ()
Called on start.
virtual void OnBattleEnd (bool)
Called at the end of battle.
virtual void OnStartGrouping ()
Called x minutes before battle start when player in zone are invite to join queue.
virtual void OnPlayerJoinWar (Player *)
Called when a player accept to join the battle.
virtual void OnPlayerLeaveWar (Player *)
Called when a player leave the battle.
virtual void OnPlayerLeaveZone (Player *)
Called when a player leave battlefield zone.
virtual void OnPlayerEnterZone (Player *)
Called when a player enter in battlefield zone.
void SendWarningToAllInZone (uint32 entry)
void SendWarningToPlayer (Player *player, uint32 entry)
void PlayerAcceptInviteToQueue (Player *player)
void PlayerAcceptInviteToWar (Player *player)
uint32 GetBattleId ()
void AskToLeaveQueue (Player *player)
void PlayerAskToLeave (Player *player)
virtual void SendInitWorldStatesToAll ()=0
Send all worldstate data to all player in zone.
virtual void FillInitialWorldStates (WorldPacket &)=0
bool CanFlyIn ()
Return if we can use mount in battlefield.
void SendAreaSpiritHealerQueryOpcode (Player *player, const ObjectGuid &guid)
void StartBattle ()
void EndBattle (bool endByTimer)
void HideNpc (Creature *creature)
void ShowNpc (Creature *creature, bool aggressive)
GraveyardVect GetGraveyardVector ()
uint32 GetTimer ()
void SetTimer (uint32 timer)
void DoPlaySoundToAll (uint32 SoundID)
void InvitePlayerToQueue (Player *player)
void InvitePlayerToWar (Player *player)
void InitStalker (uint32 entry, float x, float y, float z, float o)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual void ProcessEvent (WorldObject *, uint32)
Protected Member Functions
void KickAfkPlayers ()
virtual void SendRemoveWorldStates (Player *)
void BroadcastPacketToZone (WorldPacket &data) const
void BroadcastPacketToQueue (WorldPacket &data) const
void BroadcastPacketToWar (WorldPacket &data) const
void AddCapturePoint (BfCapturePoint *cp)
void RegisterZone (uint32 zoneid)
bool HasPlayer (Player *player) const
void TeamCastSpell (TeamId team, int32 spellId)
Protected Attributes
ObjectGuid StalkerGuid
uint32 m_Timer
bool m_IsEnabled
bool m_isActive
TeamId m_DefenderTeam
BfCapturePointVector m_capturePoints
GuidUnorderedSet m_players [BG_TEAMS_COUNT]
GuidUnorderedSet m_PlayersInQueue [BG_TEAMS_COUNT]
GuidUnorderedSet m_PlayersInWar [BG_TEAMS_COUNT]
PlayerTimerMap m_InvitedPlayers [BG_TEAMS_COUNT]
PlayerTimerMap m_PlayersWillBeKick [BG_TEAMS_COUNT]
uint32 m_TypeId
uint32 m_BattleId
uint32 m_ZoneId
uint32 m_MapId
Map * m_Map
uint32 m_MaxPlayer
uint32 m_MinPlayer
uint32 m_MinLevel
uint32 m_BattleTime
uint32 m_NoWarBattleTime
uint32 m_RestartAfterCrash
uint32 m_TimeForAcceptInvite
uint32 m_uiKickDontAcceptTimer
WorldLocation KickPosition
uint32 m_uiKickAfkPlayersTimer
GraveyardVect m_GraveyardList
uint32 m_LastResurectTimer
uint32 m_StartGroupingTimer
bool m_StartGrouping
GuidUnorderedSet m_Groups [BG_TEAMS_COUNT]
std::vector< uint64 > m_Data64
std::vector< uint32 > m_Data32
Friends
class BattlefieldMgr
Detailed Description
Definition at line 204 of file Battlefield.h.
Member Typedef Documentation
BfCapturePointVector
typedef std::vector<BfCapturePoint*> Battlefield::BfCapturePointVector
typedef of map witch store capturepoint and the associate gameobject entry
Definition at line 215 of file Battlefield.h.
Constructor & Destructor Documentation
Battlefield()
Battlefield::Battlefield ()
Constructor.
Definition at line 34 of file Battlefield.cpp.
 {
     m_Timer = 0;
     m_IsEnabled = true;
     m_isActive = false;
     m_DefenderTeam = TEAM_NEUTRAL;
     m_TypeId = 0;
     m_BattleId = 0;
     m_ZoneId = 0;
     m_Map = nullptr;
     m_MapId = 0;
     m_MaxPlayer = 0;
     m_MinPlayer = 0;
     m_MinLevel = 0;
     m_BattleTime = 0;
     m_NoWarBattleTime = 0;
     m_RestartAfterCrash = 0;
     m_TimeForAcceptInvite = 20;
     m_uiKickDontAcceptTimer = 1000;
     m_uiKickAfkPlayersTimer = 1000;
     m_LastResurectTimer = RESURRECTION_INTERVAL;
     m_StartGroupingTimer = 0;
     m_StartGrouping = false;
 }
References m_BattleId, m_BattleTime, m_DefenderTeam, m_isActive, m_IsEnabled, m_LastResurectTimer, m_Map, m_MapId, m_MaxPlayer, m_MinLevel, m_MinPlayer, m_NoWarBattleTime, m_RestartAfterCrash, m_StartGrouping, m_StartGroupingTimer, m_TimeForAcceptInvite, m_Timer, m_TypeId, m_uiKickAfkPlayersTimer, m_uiKickDontAcceptTimer, m_ZoneId, RESURRECTION_INTERVAL, and TEAM_NEUTRAL.
~Battlefield()
Battlefield::~Battlefield () override
Destructor.
Definition at line 62 of file Battlefield.cpp.
 {
     for (BfCapturePointVector::iterator itr = m_capturePoints.begin(); itr != m_capturePoints.end(); ++itr)
         delete *itr;
     for (GraveyardVect::const_iterator itr = m_GraveyardList.begin(); itr != m_GraveyardList.end(); ++itr)
         delete *itr;
     m_capturePoints.clear();
 }
References m_capturePoints, and m_GraveyardList.
Member Function Documentation
AddCapturePoint()
void Battlefield::AddCapturePoint (BfCapturePoint * cp) inline protected
Definition at line 422 of file Battlefield.h.
 { m_capturePoints.push_back(cp); }
References m_capturePoints.
Referenced by BattlefieldWG::OnGameObjectCreate().
AddOrSetPlayerToCorrectBfGroup()
bool Battlefield::AddOrSetPlayerToCorrectBfGroup (Player * player)
Force player to join a battlefield group.
Definition at line 549 of file Battlefield.cpp.
 {
     if (!player->IsInWorld())
         return false;
     if (player->GetGroup() && (player->GetGroup()->isBGGroup() || player->GetGroup()->isBFGroup()))
     {
         LOG_INFO("misc", "Battlefield::AddOrSetPlayerToCorrectBfGroup - player is already in %s group!", (player->GetGroup()->isBGGroup() ? "BG" : "BF"));
         return false;
     }
     Group* group = GetFreeBfRaid(player->GetTeamId());
     if (!group)
     {
         group = new Group;
         group->SetBattlefieldGroup(this);
         group->Create(player);
         sGroupMgr->AddGroup(group);
         m_Groups[player->GetTeamId()].insert(group->GetGUID());
     }
     else if (group->IsMember(player->GetGUID()))
     {
         uint8 subgroup = group->GetMemberGroup(player->GetGUID());
         player->SetBattlegroundOrBattlefieldRaid(group, subgroup);
     }
     else
         group->AddMember(player);
     return true;
 }
References Group::AddMember(), Group::Create(), GetFreeBfRaid(), Player::GetGroup(), Group::GetGUID(), Object::GetGUID(), Group::GetMemberGroup(), Player::GetTeamId(), Group, Group::isBFGroup(), Group::isBGGroup(), Object::IsInWorld(), Group::IsMember(), LOG_INFO, m_Groups, Group::SetBattlefieldGroup(), Player::SetBattlegroundOrBattlefieldRaid(), and sGroupMgr.
Referenced by PlayerAcceptInviteToWar().
AddPlayerToResurrectQueue()
void Battlefield::AddPlayerToResurrectQueue (ObjectGuid npc_guid, ObjectGuid player_guid) virtual
Definition at line 630 of file Battlefield.cpp.
 {
     for (uint8 i = 0; i < m_GraveyardList.size(); i++)
     {
         if (!m_GraveyardList[i])
             continue;
         if (m_GraveyardList[i]->HasNpc(npcGuid))
         {
             m_GraveyardList[i]->AddPlayer(playerGuid);
             break;
         }
     }
 }
References m_GraveyardList.
AskToLeaveQueue()
void Battlefield::AskToLeaveQueue (Player * player)
Definition at line 401 of file Battlefield.cpp.
 {
     // Remove player from queue
     m_PlayersInQueue[player->GetTeamId()].erase(player->GetGUID());
 }
References Object::GetGUID(), Player::GetTeamId(), and m_PlayersInQueue.
Referenced by WorldSession::HandleBfExitRequest().
BroadcastPacketToQueue()
void Battlefield::BroadcastPacketToQueue (WorldPacket & data) const protected
Definition at line 457 of file Battlefield.cpp.
 {
     for (uint8 team = 0; team < BG_TEAMS_COUNT; ++team)
         for (GuidUnorderedSet::const_iterator itr = m_PlayersInQueue[team].begin(); itr != m_PlayersInQueue[team].end(); ++itr)
             if (Player* player = ObjectAccessor::FindPlayer(*itr))
                 player->GetSession()->SendPacket(&data);
 }
References BG_TEAMS_COUNT, ObjectAccessor::FindPlayer(), and m_PlayersInQueue.
BroadcastPacketToWar()
void Battlefield::BroadcastPacketToWar (WorldPacket & data) const protected
Definition at line 465 of file Battlefield.cpp.
 {
     for (uint8 team = 0; team < BG_TEAMS_COUNT; ++team)
         for (GuidUnorderedSet::const_iterator itr = m_PlayersInWar[team].begin(); itr != m_PlayersInWar[team].end(); ++itr)
             if (Player* player = ObjectAccessor::FindPlayer(*itr))
                 player->GetSession()->SendPacket(&data);
 }
References BG_TEAMS_COUNT, ObjectAccessor::FindPlayer(), and m_PlayersInWar.
BroadcastPacketToZone()
void Battlefield::BroadcastPacketToZone (WorldPacket & data) const protected
Definition at line 449 of file Battlefield.cpp.
 {
     for (uint8 team = 0; team < BG_TEAMS_COUNT; ++team)
         for (GuidUnorderedSet::const_iterator itr = m_players[team].begin(); itr != m_players[team].end(); ++itr)
             if (Player* player = ObjectAccessor::FindPlayer(*itr))
                 player->GetSession()->SendPacket(&data);
 }
References BG_TEAMS_COUNT, ObjectAccessor::FindPlayer(), and m_players.
CanFlyIn()
bool Battlefield::CanFlyIn () inline
Return if we can use mount in battlefield.
Definition at line 342 of file Battlefield.h.
 { return !m_isActive; }
References m_isActive.
Referenced by Spell::CheckCast(), spell_gen_mount::HandleMount(), and SpellArea::IsFitToRequirements().
DoPlaySoundToAll()
void Battlefield::DoPlaySoundToAll (uint32 SoundID)
Definition at line 374 of file Battlefield.cpp.
 {
     WorldPacket data;
     data.Initialize(SMSG_PLAY_SOUND, 4);
     data << uint32(SoundID);
     for (int team = 0; team < BG_TEAMS_COUNT; team++)
         for (GuidUnorderedSet::const_iterator itr = m_PlayersInWar[team].begin(); itr != m_PlayersInWar[team].end(); ++itr)
             if (Player* player = ObjectAccessor::FindPlayer(*itr))
                 player->GetSession()->SendPacket(&data);
 }
References BG_TEAMS_COUNT, ObjectAccessor::FindPlayer(), WorldPacket::Initialize(), m_PlayersInWar, and SMSG_PLAY_SOUND.
Referenced by EndBattle(), and StartBattle().
EndBattle()
void Battlefield::EndBattle (bool endByTimer)
Definition at line 350 of file Battlefield.cpp.
 {
     if (!m_isActive)
         return;
     m_isActive = false;
     m_StartGrouping = false;
     if (!endByTimer)
         SetDefenderTeam(GetAttackerTeam());
     if (GetDefenderTeam() == TEAM_ALLIANCE)
         DoPlaySoundToAll(BF_ALLIANCE_WINS);
     else
         DoPlaySoundToAll(BF_HORDE_WINS);
     OnBattleEnd(endByTimer);
     // Reset battlefield timer
     m_Timer = m_NoWarBattleTime;
     SendInitWorldStatesToAll();
 }
References BF_ALLIANCE_WINS, BF_HORDE_WINS, DoPlaySoundToAll(), GetAttackerTeam(), GetDefenderTeam(), m_isActive, m_NoWarBattleTime, m_StartGrouping, m_Timer, OnBattleEnd(), SendInitWorldStatesToAll(), SetDefenderTeam(), and TEAM_ALLIANCE.
Referenced by bf_commandscript::HandleBattlefieldEnd(), bf_commandscript::HandleBattlefieldSwitch(), BattlefieldWG::ProcessEvent(), and Update().
FillInitialWorldStates()
virtual void Battlefield::FillInitialWorldStates (WorldPacket &) pure virtual
Implemented in BattlefieldWG.
Referenced by Player::SendInitWorldStates().
GetAttackerTeam()
TeamId Battlefield::GetAttackerTeam () inline
Definition at line 277 of file Battlefield.h.
 { return TeamId(1 - m_DefenderTeam); }
References m_DefenderTeam.
Referenced by BfWGGameObjectBuilding::Damaged(), EndBattle(), BattlefieldWG::FillInitialWorldStates(), BfWGGameObjectBuilding::Init(), BattlefieldWG::OnBattleEnd(), BattlefieldWG::OnBattleStart(), BattlefieldWG::OnGameObjectCreate(), npc_wg_quest_giver::OnGossipHello(), BattlefieldWG::OnPlayerEnterZone(), BattlefieldWG::OnPlayerJoinWar(), BfWGGameObjectBuilding::Rebuild(), BattlefieldWG::SetupBattlefield(), BfWGGameObjectBuilding::UpdateCreatureAndGo(), BattlefieldWG::UpdateDamagedTowerCount(), BattlefieldWG::UpdatedDestroyedTowerCount(), and BfWGGameObjectBuilding::UpdateTurretAttack().
GetBattleId()
uint32 Battlefield::GetBattleId () inline
Definition at line 331 of file Battlefield.h.
 { return m_BattleId; }
References m_BattleId.
GetClosestGraveyard()
GraveyardStruct const * Battlefield::GetClosestGraveyard (Player * player)
Definition at line 604 of file Battlefield.cpp.
 {
     BfGraveyard* closestGY = nullptr;
     float maxdist = -1;
     for (uint8 i = 0; i < m_GraveyardList.size(); i++)
     {
         if (m_GraveyardList[i])
         {
             if (m_GraveyardList[i]->GetControlTeamId() != player->GetTeamId())
                 continue;
             float dist = m_GraveyardList[i]->GetDistance(player);
             if (dist < maxdist || maxdist < 0)
             {
                 closestGY = m_GraveyardList[i];
                 maxdist = dist;
             }
         }
     }
     if (closestGY)
         return sGraveyard->GetGraveyard(closestGY->GetGraveyardId());
     return nullptr;
 }
References BfGraveyard::GetGraveyardId(), Player::GetTeamId(), m_GraveyardList, and sGraveyard.
Referenced by BfGraveyard::RelocateDeadPlayers().
GetCreature()
Creature * Battlefield::GetCreature (ObjectGuid const guid)
Definition at line 856 of file Battlefield.cpp.
 {
     if (!m_Map)
         return nullptr;
     return m_Map->GetCreature(guid);
 }
References Map::GetCreature(), and m_Map.
Referenced by BfWGGameObjectBuilding::Damaged(), BattlefieldWG::OnBattleEnd(), BattlefieldWG::OnBattleStart(), SendWarningToAllInZone(), BattlefieldWG::SetupBattlefield(), BfWGGameObjectBuilding::UpdateCreatureAndGo(), BattlefieldWG::UpdateTenacity(), and BfWGGameObjectBuilding::UpdateTurretAttack().
GetData()
uint32 Battlefield::GetData (uint32 dataId) const inline override virtual
Reimplemented from ZoneScript.
Reimplemented in BattlefieldWG.
Definition at line 271 of file Battlefield.h.
 { return m_Data32[dataId]; }
References m_Data32.
Referenced by npc_wg_demolisher_engineer::canBuild(), BattlefieldWG::GetData(), and SpellArea::IsFitToRequirements().
GetData64()
uint64 Battlefield::GetData64 (uint32 dataId) const inline override virtual
Reimplemented from ZoneScript.
Definition at line 267 of file Battlefield.h.
 { return m_Data64[dataId]; }
References m_Data64.
GetDefenderTeam()
TeamId Battlefield::GetDefenderTeam () inline
Definition at line 276 of file Battlefield.h.
 { return m_DefenderTeam; }
References m_DefenderTeam.
Referenced by EndBattle(), BattlefieldWG::FillInitialWorldStates(), spell_wintergrasp_portal::spell_wintergrasp_portal_SpellScript::HandleScript(), BfWGGameObjectBuilding::Init(), SpellArea::IsFitToRequirements(), BattlefieldWG::OnBattleEnd(), BattlefieldWG::OnBattleStart(), npc_wg_queue::OnGossipHello(), npc_wg_quest_giver::OnGossipHello(), BattlefieldWG::OnPlayerJoinWar(), BfWGGameObjectBuilding::Rebuild(), BattlefieldWG::SetupBattlefield(), BfWGGameObjectBuilding::UpdateCreatureAndGo(), BattlefieldWG::UpdatedDestroyedTowerCount(), WGWorkshop::UpdateGraveyardAndWorkshop(), and BfWGGameObjectBuilding::UpdateTurretAttack().
GetFreeBfRaid()
Group * Battlefield::GetFreeBfRaid (TeamId TeamId)
Find a not full battlefield group, if there is no, create one.
Parameters
TeamId : Id of player team for who we search a group (player->GetTeamId())
Definition at line 529 of file Battlefield.cpp.
 {
     for (GuidUnorderedSet::const_iterator itr = m_Groups[TeamId].begin(); itr != m_Groups[TeamId].end(); ++itr)
         if (Group* group = sGroupMgr->GetGroupByGUID(itr->GetCounter()))
             if (!group->IsFull())
                 return group;
     return nullptr;
 }
References m_Groups, and sGroupMgr.
Referenced by AddOrSetPlayerToCorrectBfGroup().
GetGameObject()
GameObject * Battlefield::GetGameObject (ObjectGuid const guid)
Definition at line 864 of file Battlefield.cpp.
 {
     if (!m_Map)
         return nullptr;
     return m_Map->GetGameObject(guid);
 }
References Map::GetGameObject(), and m_Map.
Referenced by BfWGGameObjectBuilding::Destroyed(), BfCapturePoint::GetCapturePointGo(), BattlefieldWG::GetRelic(), BfWGGameObjectBuilding::Rebuild(), and BfWGGameObjectBuilding::UpdateTurretAttack().
GetGraveyardById()
BfGraveyard * Battlefield::GetGraveyardById (uint32 id) const
Definition at line 589 of file Battlefield.cpp.
 {
     if (id < m_GraveyardList.size())
     {
         if (m_GraveyardList[id])
             return m_GraveyardList[id];
         else
             LOG_ERROR("bg.battlefield", "Battlefield::GetGraveyardById Id:%u not existed", id);
     }
     else
         LOG_ERROR("bg.battlefield", "Battlefield::GetGraveyardById Id:%u cant be found", id);
     return nullptr;
 }
References LOG_ERROR, and m_GraveyardList.
Referenced by BattlefieldWG::GetData(), WGWorkshop::GiveControlTo(), BattlefieldWG::OnBattleEnd(), Update(), and WGWorkshop::UpdateGraveyardAndWorkshop().
GetGraveyardVector()
GraveyardVect Battlefield::GetGraveyardVector () inline
Definition at line 352 of file Battlefield.h.
 { return m_GraveyardList; }
References m_GraveyardList.
Referenced by npc_wg_spirit_guide::OnGossipHello(), and npc_wg_spirit_guide::OnGossipSelect().
GetGroupPlayer()
Group * Battlefield::GetGroupPlayer (ObjectGuid guid, TeamId TeamId)
Return battlefield group where player is.
Definition at line 539 of file Battlefield.cpp.
 {
     for (GuidUnorderedSet::const_iterator itr = m_Groups[TeamId].begin(); itr != m_Groups[TeamId].end(); ++itr)
         if (Group* group = sGroupMgr->GetGroupByGUID(itr->GetCounter()))
             if (group->IsMember(guid))
                 return group;
     return nullptr;
 }
References m_Groups, and sGroupMgr.
GetOtherTeam()
TeamId Battlefield::GetOtherTeam (TeamId team) inline
Definition at line 278 of file Battlefield.h.
 { return (team == TEAM_HORDE ? TEAM_ALLIANCE : TEAM_HORDE); }
References TEAM_ALLIANCE, and TEAM_HORDE.
Referenced by InvitePlayerToQueue().
GetTimer()
uint32 Battlefield::GetTimer () inline
Definition at line 354 of file Battlefield.h.
 { return m_Timer; }
References m_Timer.
Referenced by instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::IsEncounterInProgress(), achievement_wg_within_our_grasp::OnCheck(), npc_wg_queue::OnGossipHello(), and npc_wg_queue::OnGossipSelect().
GetTypeId()
uint32 Battlefield::GetTypeId () inline
Definition at line 242 of file Battlefield.h.
 { return m_TypeId; }
References m_TypeId.
Referenced by SpellArea::IsFitToRequirements(), and Player::SendInitWorldStates().
GetZoneId()
uint32 Battlefield::GetZoneId () inline
Definition at line 243 of file Battlefield.h.
 { return m_ZoneId; }
References m_ZoneId.
Referenced by WorldSession::HandleBfEntryInviteResponse(), KickAfkPlayers(), and KickPlayerFromBattlefield().
HandleKill()
virtual void Battlefield::HandleKill (Player * , Unit *) inline virtual
Called when a Unit is kill in battlefield zone.
Reimplemented in BattlefieldWG.
Definition at line 240 of file Battlefield.h.
 {};
HandlePlayerEnterZone()
void Battlefield::HandlePlayerEnterZone (Player * player, uint32 zone)
Called when player (player) enter in zone.
Definition at line 74 of file Battlefield.cpp.
 {
     // Xinef: do not invite players on taxi
     if (!player->IsInFlight())
     {
         // If battle is started,
         // If not full of players > invite player to join the war
         // If full of players > announce to player that BF is full and kick him after a few second if he desn't leave
         if (IsWarTime())
         {
             if (m_PlayersInWar[player->GetTeamId()].size() + m_InvitedPlayers[player->GetTeamId()].size() < m_MaxPlayer) // Vacant spaces
                 InvitePlayerToWar(player);
             else // No more vacant places
             {
                 // TODO: Send a packet to announce it to player
                 m_PlayersWillBeKick[player->GetTeamId()][player->GetGUID()] = time(nullptr) + (player->IsGameMaster() ? 30 * MINUTE : 10);
                 InvitePlayerToQueue(player);
             }
         }
         else
         {
             // If time left is < 15 minutes invite player to join queue
             if (m_Timer <= m_StartGroupingTimer)
                 InvitePlayerToQueue(player);
         }
     }
     // Add player in the list of player in zone
     m_players[player->GetTeamId()].insert(player->GetGUID());
     OnPlayerEnterZone(player);
 }
References Object::GetGUID(), Player::GetTeamId(), InvitePlayerToQueue(), InvitePlayerToWar(), Player::IsGameMaster(), Unit::IsInFlight(), IsWarTime(), m_InvitedPlayers, m_MaxPlayer, m_players, m_PlayersInWar, m_PlayersWillBeKick, m_StartGroupingTimer, m_Timer, MINUTE, and OnPlayerEnterZone().
HandlePlayerLeaveZone()
void Battlefield::HandlePlayerLeaveZone (Player * player, uint32 zone)
Called when player (player) leave the zone.
Definition at line 107 of file Battlefield.cpp.
 {
     if (IsWarTime())
     {
         // If the player is participating to the battle
         if (m_PlayersInWar[player->GetTeamId()].find(player->GetGUID()) != m_PlayersInWar[player->GetTeamId()].end())
         {
             m_PlayersInWar[player->GetTeamId()].erase(player->GetGUID());
             player->GetSession()->SendBfLeaveMessage(m_BattleId);
             if (Group* group = player->GetGroup()) // Remove the player from the raid group
                 if (group->isBFGroup())
                     group->RemoveMember(player->GetGUID());
             OnPlayerLeaveWar(player);
         }
     }
     for (BfCapturePointVector::iterator itr = m_capturePoints.begin(); itr != m_capturePoints.end(); ++itr)
         (*itr)->HandlePlayerLeave(player);
     m_InvitedPlayers[player->GetTeamId()].erase(player->GetGUID());
     m_PlayersWillBeKick[player->GetTeamId()].erase(player->GetGUID());
     m_players[player->GetTeamId()].erase(player->GetGUID());
     SendRemoveWorldStates(player);
     RemovePlayerFromResurrectQueue(player->GetGUID());
     OnPlayerLeaveZone(player);
 }
References Player::GetGroup(), Object::GetGUID(), Player::GetSession(), Player::GetTeamId(), IsWarTime(), m_BattleId, m_capturePoints, m_InvitedPlayers, m_players, m_PlayersInWar, m_PlayersWillBeKick, OnPlayerLeaveWar(), OnPlayerLeaveZone(), RemovePlayerFromResurrectQueue(), WorldSession::SendBfLeaveMessage(), and SendRemoveWorldStates().
HasPlayer()
bool Battlefield::HasPlayer (Player * player) const protected
Definition at line 386 of file Battlefield.cpp.
 {
     return m_players[player->GetTeamId()].find(player->GetGUID()) != m_players[player->GetTeamId()].end();
 }
References Object::GetGUID(), Player::GetTeamId(), and m_players.
Referenced by RemovePlayerFromResurrectQueue().
HideNpc()
void Battlefield::HideNpc (Creature * creature)
Definition at line 500 of file Battlefield.cpp.
 {
     creature->CombatStop();
     creature->SetReactState(REACT_PASSIVE);
     creature->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE);
     creature->SetPhaseMask(2, false); // pussywizard: false because UpdateObjectVisibility(true) is called below in SetVisible(), no need to have it here
     creature->DisappearAndDie();
     creature->SetVisible(false);
 }
References Unit::CombatStop(), Creature::DisappearAndDie(), REACT_PASSIVE, Object::SetFlag(), Unit::SetPhaseMask(), Creature::SetReactState(), Unit::SetVisible(), UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
Referenced by BfWGGameObjectBuilding::Damaged(), BfWGGameObjectBuilding::Init(), BattlefieldWG::OnBattleEnd(), BattlefieldWG::SetupBattlefield(), BfWGGameObjectBuilding::UpdateCreatureAndGo(), and BfWGGameObjectBuilding::UpdateTurretAttack().
InitStalker()
void Battlefield::InitStalker (uint32 entry, float x, float y, float z, float o)
Definition at line 301 of file Battlefield.cpp.
 {
     if (Creature* creature = SpawnCreature(entry, x, y, z, o, TEAM_NEUTRAL))
         StalkerGuid = creature->GetGUID();
     else
         LOG_ERROR("bg.battlefield", "Battlefield::InitStalker: could not spawn Stalker (Creature entry %u), zone messeges will be un-available", entry);
 }
References LOG_ERROR, SpawnCreature(), StalkerGuid, and TEAM_NEUTRAL.
Referenced by BattlefieldWG::SetupBattlefield().
InvitePlayersInQueueToWar()
void Battlefield::InvitePlayersInQueueToWar ()
Invite all players in queue to join battle on battle start.
Definition at line 231 of file Battlefield.cpp.
 {
     for (uint8 team = 0; team < BG_TEAMS_COUNT; ++team)
     {
         GuidUnorderedSet copy(m_PlayersInQueue[team]);
         for (GuidUnorderedSet::const_iterator itr = copy.begin(); itr != copy.end(); ++itr)
         {
             if (Player* player = ObjectAccessor::FindPlayer(*itr))
             {
                 if (m_PlayersInWar[player->GetTeamId()].size() + m_InvitedPlayers[player->GetTeamId()].size() < m_MaxPlayer)
                     InvitePlayerToWar(player);
                 else
                 {
                     //Full
                 }
             }
         }
         m_PlayersInQueue[team].clear();
     }
 }
References BG_TEAMS_COUNT, ObjectAccessor::FindPlayer(), InvitePlayerToWar(), m_InvitedPlayers, m_MaxPlayer, m_PlayersInQueue, and m_PlayersInWar.
Referenced by StartBattle().
InvitePlayersInZoneToQueue()
void Battlefield::InvitePlayersInZoneToQueue ()
Invite all players in zone to join the queue, called x minutes before battle start in Update()
Definition at line 214 of file Battlefield.cpp.
 {
     for (uint8 team = 0; team < 2; ++team)
         for (GuidUnorderedSet::const_iterator itr = m_players[team].begin(); itr != m_players[team].end(); ++itr)
             if (Player* player = ObjectAccessor::FindPlayer(*itr))
                 InvitePlayerToQueue(player);
 }
References ObjectAccessor::FindPlayer(), InvitePlayerToQueue(), and m_players.
Referenced by Update().
InvitePlayersInZoneToWar()
void Battlefield::InvitePlayersInZoneToWar ()
Invite all players in zone to join battle on battle start.
Definition at line 252 of file Battlefield.cpp.
 {
     for (uint8 team = 0; team < BG_TEAMS_COUNT; ++team)
         for (GuidUnorderedSet::const_iterator itr = m_players[team].begin(); itr != m_players[team].end(); ++itr)
         {
             if (Player* player = ObjectAccessor::FindPlayer(*itr))
             {
                 if (m_PlayersInWar[player->GetTeamId()].count(player->GetGUID()) || m_InvitedPlayers[player->GetTeamId()].count(player->GetGUID()))
                     continue;
                 if (m_PlayersInWar[player->GetTeamId()].size() + m_InvitedPlayers[player->GetTeamId()].size() < m_MaxPlayer)
                     InvitePlayerToWar(player);
                 else if (m_PlayersWillBeKick[player->GetTeamId()].count(player->GetGUID()) == 0)// Battlefield is full of players
                     m_PlayersWillBeKick[player->GetTeamId()][player->GetGUID()] = time(nullptr) + 10;
             }
         }
 }
References BG_TEAMS_COUNT, ObjectAccessor::FindPlayer(), InvitePlayerToWar(), m_InvitedPlayers, m_MaxPlayer, m_players, m_PlayersInWar, and m_PlayersWillBeKick.
Referenced by StartBattle(), and Update().
InvitePlayerToQueue()
void Battlefield::InvitePlayerToQueue (Player * player)
Definition at line 222 of file Battlefield.cpp.
 {
     if (m_PlayersInQueue[player->GetTeamId()].count(player->GetGUID()))
         return;
     if (m_PlayersInQueue[player->GetTeamId()].size() <= m_MinPlayer || m_PlayersInQueue[GetOtherTeam(player->GetTeamId())].size() >= m_MinPlayer)
         player->GetSession()->SendBfInvitePlayerToQueue(m_BattleId);
 }
References Object::GetGUID(), GetOtherTeam(), Player::GetSession(), Player::GetTeamId(), m_BattleId, m_MinPlayer, m_PlayersInQueue, and WorldSession::SendBfInvitePlayerToQueue().
Referenced by HandlePlayerEnterZone(), InvitePlayersInZoneToQueue(), and npc_wg_queue::OnGossipSelect().
InvitePlayerToWar()
void Battlefield::InvitePlayerToWar (Player * player)
Definition at line 269 of file Battlefield.cpp.
 {
     if (!player)
         return;
     // TODO : needed ?
     if (player->IsInFlight())
         return;
     if (player->InBattleground())
     {
         m_PlayersInQueue[player->GetTeamId()].erase(player->GetGUID());
         return;
     }
     // If the player does not match minimal level requirements for the battlefield, kick him
     if (player->getLevel() < m_MinLevel)
     {
         if (m_PlayersWillBeKick[player->GetTeamId()].count(player->GetGUID()) == 0)
             m_PlayersWillBeKick[player->GetTeamId()][player->GetGUID()] = time(nullptr) + 10;
         return;
     }
     // Check if player is not already in war
     if (m_PlayersInWar[player->GetTeamId()].count(player->GetGUID()) || m_InvitedPlayers[player->GetTeamId()].count(player->GetGUID()))
         return;
     m_PlayersWillBeKick[player->GetTeamId()].erase(player->GetGUID());
     m_InvitedPlayers[player->GetTeamId()][player->GetGUID()] = time(nullptr) + m_TimeForAcceptInvite;
     player->GetSession()->SendBfInvitePlayerToWar(m_BattleId, m_ZoneId, m_TimeForAcceptInvite);
 }
References Object::GetGUID(), Unit::getLevel(), Player::GetSession(), Player::GetTeamId(), Player::InBattleground(), Unit::IsInFlight(), m_BattleId, m_InvitedPlayers, m_MinLevel, m_PlayersInQueue, m_PlayersInWar, m_PlayersWillBeKick, m_TimeForAcceptInvite, m_ZoneId, and WorldSession::SendBfInvitePlayerToWar().
Referenced by HandlePlayerEnterZone(), InvitePlayersInQueueToWar(), InvitePlayersInZoneToWar(), and npc_wg_queue::OnGossipSelect().
IsEnabled()
bool Battlefield::IsEnabled () inline
Return if battlefield is enable.
Definition at line 253 of file Battlefield.h.
 { return m_IsEnabled; }
References m_IsEnabled.
Referenced by bf_commandscript::HandleBattlefieldEnable(), and Update().
IsWarTime()
bool Battlefield::IsWarTime () inline
Return true if battle is start, false if battle is not started.
Definition at line 248 of file Battlefield.h.
 { return m_isActive; }
References m_isActive.
Referenced by Player::CreateCorpse(), BattlefieldWG::FillInitialWorldStates(), spell_wintergrasp_hide_small_elementals::spell_wintergrasp_hide_small_elementals_AuraScript::HandlePeriodicDummy(), HandlePlayerEnterZone(), HandlePlayerLeaveZone(), instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::IsEncounterInProgress(), SpellArea::IsFitToRequirements(), BattlefieldWG::OnCreatureCreate(), npc_wg_queue::OnGossipHello(), npc_wg_queue::OnGossipSelect(), BattlefieldWG::OnStartGrouping(), BattlefieldWG::OnUnitDeath(), PlayerAcceptInviteToWar(), BattlefieldWG::ProcessEvent(), Update(), and BattlefieldWG::Update().
KickAfkPlayers()
void Battlefield::KickAfkPlayers () protected
Definition at line 309 of file Battlefield.cpp.
 {
     // xinef: optimization, dont lookup player twice
     for (uint8 team = 0; team < BG_TEAMS_COUNT; ++team)
         for (GuidUnorderedSet::const_iterator itr = m_PlayersInWar[team].begin(); itr != m_PlayersInWar[team].end(); ++itr)
             if (Player* player = ObjectAccessor::FindPlayer(*itr))
                 if (player->isAFK() && player->GetZoneId() == GetZoneId() && !player->IsGameMaster())
                     player->TeleportTo(KickPosition);
 }
References BG_TEAMS_COUNT, ObjectAccessor::FindPlayer(), GetZoneId(), KickPosition, and m_PlayersInWar.
Referenced by Update().
KickPlayerFromBattlefield()
void Battlefield::KickPlayerFromBattlefield (ObjectGuid guid)
Kick player from battlefield and teleport him to kick-point location.
Parameters
guid : guid of player who must be kick
Definition at line 319 of file Battlefield.cpp.
 {
     if (Player* player = ObjectAccessor::FindPlayer(guid))
     {
         if (player->GetZoneId() == GetZoneId() && !player->IsGameMaster())
             player->TeleportTo(KickPosition);
     }
 }
References ObjectAccessor::FindPlayer(), GetZoneId(), and KickPosition.
Referenced by WorldSession::HandleBfEntryInviteResponse(), BattlefieldWG::OnPlayerEnterZone(), and Update().
OnBattleEnd()
virtual void Battlefield::OnBattleEnd (bool) inline virtual
Called at the end of battle.
Reimplemented in BattlefieldWG.
Definition at line 314 of file Battlefield.h.
 {};
Referenced by EndBattle().
OnBattleStart()
virtual void Battlefield::OnBattleStart () inline virtual
Called on start.
Reimplemented in BattlefieldWG.
Definition at line 312 of file Battlefield.h.
 {};
Referenced by StartBattle().
OnPlayerEnterZone()
virtual void Battlefield::OnPlayerEnterZone (Player *) inline virtual
Called when a player enter in battlefield zone.
Reimplemented in BattlefieldWG.
Definition at line 324 of file Battlefield.h.
 {};
Referenced by HandlePlayerEnterZone().
OnPlayerJoinWar()
virtual void Battlefield::OnPlayerJoinWar (Player *) inline virtual
Called when a player accept to join the battle.
Reimplemented in BattlefieldWG.
Definition at line 318 of file Battlefield.h.
 {};
Referenced by PlayerAcceptInviteToWar().
OnPlayerLeaveWar()
virtual void Battlefield::OnPlayerLeaveWar (Player *) inline virtual
Called when a player leave the battle.
Reimplemented in BattlefieldWG.
Definition at line 320 of file Battlefield.h.
 {};
Referenced by HandlePlayerLeaveZone().
OnPlayerLeaveZone()
virtual void Battlefield::OnPlayerLeaveZone (Player *) inline virtual
Called when a player leave battlefield zone.
Reimplemented in BattlefieldWG.
Definition at line 322 of file Battlefield.h.
 {};
Referenced by HandlePlayerLeaveZone().
OnStartGrouping()
virtual void Battlefield::OnStartGrouping () inline virtual
Called x minutes before battle start when player in zone are invite to join queue.
Reimplemented in BattlefieldWG.
Definition at line 316 of file Battlefield.h.
 {};
Referenced by Update().
PlayerAcceptInviteToQueue()
void Battlefield::PlayerAcceptInviteToQueue (Player * player)
Definition at line 392 of file Battlefield.cpp.
 {
     // Add player in queue
     m_PlayersInQueue[player->GetTeamId()].insert(player->GetGUID());
     // Send notification
     player->GetSession()->SendBfQueueInviteResponse(m_BattleId, m_ZoneId);
 }
References Object::GetGUID(), Player::GetSession(), Player::GetTeamId(), m_BattleId, m_PlayersInQueue, m_ZoneId, and WorldSession::SendBfQueueInviteResponse().
Referenced by WorldSession::HandleBfQueueInviteResponse().
PlayerAcceptInviteToWar()
void Battlefield::PlayerAcceptInviteToWar (Player * player)
Definition at line 415 of file Battlefield.cpp.
 {
     if (!IsWarTime())
         return;
     if (AddOrSetPlayerToCorrectBfGroup(player))
     {
         player->GetSession()->SendBfEntered(m_BattleId);
         m_PlayersInWar[player->GetTeamId()].insert(player->GetGUID());
         m_InvitedPlayers[player->GetTeamId()].erase(player->GetGUID());
         if (player->isAFK())
             player->ToggleAFK();
         OnPlayerJoinWar(player);                               //for scripting
     }
 }
References AddOrSetPlayerToCorrectBfGroup(), Object::GetGUID(), Player::GetSession(), Player::GetTeamId(), Player::isAFK(), IsWarTime(), m_BattleId, m_InvitedPlayers, m_PlayersInWar, OnPlayerJoinWar(), WorldSession::SendBfEntered(), and Player::ToggleAFK().
Referenced by WorldSession::HandleBfEntryInviteResponse().
PlayerAskToLeave()
void Battlefield::PlayerAskToLeave (Player * player)
Definition at line 408 of file Battlefield.cpp.
 {
     // Player leaving Wintergrasp, trigger Hearthstone spell.
     player->CastSpell(player, 8690, true);
 }
References Unit::CastSpell().
RegisterZone()
void Battlefield::RegisterZone (uint32 zoneid) protected
Definition at line 495 of file Battlefield.cpp.
 {
     sBattlefieldMgr->AddZone(zoneId, this);
 }
References sBattlefieldMgr.
Referenced by BattlefieldWG::SetupBattlefield().
RemovePlayerFromResurrectQueue()
void Battlefield::RemovePlayerFromResurrectQueue (ObjectGuid player_guid)
Definition at line 645 of file Battlefield.cpp.
 {
     for (uint8 i = 0; i < m_GraveyardList.size(); i++)
     {
         if (!m_GraveyardList[i])
             continue;
         if (m_GraveyardList[i]->HasPlayer(playerGuid))
         {
             m_GraveyardList[i]->RemovePlayer(playerGuid);
             break;
         }
     }
 }
References HasPlayer(), and m_GraveyardList.
Referenced by HandlePlayerLeaveZone().
SendAreaSpiritHealerQueryOpcode()
void Battlefield::SendAreaSpiritHealerQueryOpcode (Player * player, const ObjectGuid & guid)
Definition at line 660 of file Battlefield.cpp.
 {
     WorldPacket data(SMSG_AREA_SPIRIT_HEALER_TIME, 12);
     uint32 time = m_LastResurectTimer;  // resurrect every 30 seconds
     data << guid << time;
     ASSERT(player);
     player->GetSession()->SendPacket(&data);
 }
References ASSERT, Player::GetSession(), m_LastResurectTimer, WorldSession::SendPacket(), and SMSG_AREA_SPIRIT_HEALER_TIME.
SendInitWorldStatesToAll()
virtual void Battlefield::SendInitWorldStatesToAll () pure virtual
Send all worldstate data to all player in zone.
Implemented in BattlefieldWG.
Referenced by EndBattle(), and bf_commandscript::HandleBattlefieldTimer().
SendRemoveWorldStates()
virtual void Battlefield::SendRemoveWorldStates (Player *) inline protected virtual
Definition at line 414 of file Battlefield.h.
 {}
Referenced by HandlePlayerLeaveZone().
SendUpdateWorldState()
void Battlefield::SendUpdateWorldState (uint32 field, uint32 value)
Update data of a worldstate to all players present in zone.
Definition at line 487 of file Battlefield.cpp.
 {
     for (uint8 i = 0; i < BG_TEAMS_COUNT; ++i)
         for (GuidUnorderedSet::iterator itr = m_players[i].begin(); itr != m_players[i].end(); ++itr)
             if (Player* player = ObjectAccessor::FindPlayer(*itr))
                 player->SendUpdateWorldState(field, value);
 }
References BG_TEAMS_COUNT, ObjectAccessor::FindPlayer(), and m_players.
Referenced by BfWGGameObjectBuilding::Damaged(), BfWGGameObjectBuilding::Destroyed(), WGWorkshop::GiveControlTo(), and BfWGGameObjectBuilding::Rebuild().
SendWarningToAllInZone()
void Battlefield::SendWarningToAllInZone (uint32 entry)
Definition at line 473 of file Battlefield.cpp.
 {
     if (Creature* stalker = GetCreature(StalkerGuid))
         sCreatureTextMgr->SendChat(stalker, (uint8)entry, nullptr, CHAT_MSG_ADDON, LANG_ADDON, TEXT_RANGE_ZONE);
 }
References CHAT_MSG_ADDON, GetCreature(), LANG_ADDON, sCreatureTextMgr, StalkerGuid, and TEXT_RANGE_ZONE.
Referenced by BfWGGameObjectBuilding::Damaged(), BfWGGameObjectBuilding::Destroyed(), WGWorkshop::GiveControlTo(), BattlefieldWG::OnBattleEnd(), BattlefieldWG::OnBattleStart(), and BattlefieldWG::OnStartGrouping().
SendWarningToPlayer()
void Battlefield::SendWarningToPlayer (Player * player, uint32 entry)
Definition at line 479 of file Battlefield.cpp.
 {
     if (player)
         if (Unit* unit = ObjectAccessor::GetCreature(*player, StalkerGuid))
             if (Creature* stalker = unit->ToCreature())
                 sCreatureTextMgr->SendChat(stalker, (uint8)entry, player);
 }
References ObjectAccessor::GetCreature(), sCreatureTextMgr, StalkerGuid, and Object::ToCreature().
Referenced by BattlefieldWG::PromotePlayer().
SetData()
void Battlefield::SetData (uint32 dataId, uint32 value) inline override virtual
Reimplemented from ZoneScript.
Definition at line 272 of file Battlefield.h.
 { m_Data32[dataId] = value; }
References m_Data32.
Referenced by BattlefieldWG::OnBattleStart(), and BattlefieldWG::UpdateCounterVehicle().
SetData64()
void Battlefield::SetData64 (uint32 dataId, uint64 value) inline override virtual
Reimplemented from ZoneScript.
Definition at line 268 of file Battlefield.h.
 { m_Data64[dataId] = value; }
References m_Data64.
SetDefenderTeam()
void Battlefield::SetDefenderTeam (TeamId team) inline
Definition at line 279 of file Battlefield.h.
 { m_DefenderTeam = team; }
References m_DefenderTeam.
Referenced by EndBattle().
SetGraveyardNumber()
void Battlefield::SetGraveyardNumber (uint32 number) inline
Definition at line 298 of file Battlefield.h.
 { m_GraveyardList.resize(number); }
References m_GraveyardList.
Referenced by BattlefieldWG::SetupBattlefield().
SetTimer()
void Battlefield::SetTimer (uint32 timer) inline
Definition at line 355 of file Battlefield.h.
 { m_Timer = timer; }
References m_Timer.
Referenced by bf_commandscript::HandleBattlefieldTimer().
SetupBattlefield()
virtual bool Battlefield::SetupBattlefield () inline virtual
Call this to init the Battlefield.
Reimplemented in BattlefieldWG.
Definition at line 218 of file Battlefield.h.
 { return true; }
Referenced by BattlefieldMgr::InitBattlefield().
ShowNpc()
void Battlefield::ShowNpc (Creature * creature, bool aggressive)
Definition at line 510 of file Battlefield.cpp.
 {
     creature->SetPhaseMask(1, false); // pussywizard: false because UpdateObjectVisibility(true) is called below in SetVisible(), no need to have it here
     creature->SetVisible(true);
     creature->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE);
     if (!creature->IsAlive())
         creature->Respawn(true);
     if (aggressive)
         creature->SetReactState(REACT_AGGRESSIVE);
     else
     {
         creature->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
         creature->SetReactState(REACT_PASSIVE);
     }
 }
References Unit::IsAlive(), REACT_AGGRESSIVE, REACT_PASSIVE, Object::RemoveFlag(), Creature::Respawn(), Object::SetFlag(), Unit::SetPhaseMask(), Creature::SetReactState(), Unit::SetVisible(), UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
Referenced by BattlefieldWG::OnBattleEnd(), BattlefieldWG::OnBattleStart(), BfWGGameObjectBuilding::UpdateCreatureAndGo(), and BfWGGameObjectBuilding::UpdateTurretAttack().
SpawnCreature() [1/2]
Creature * Battlefield::SpawnCreature (uint32 entry, float x, float y, float z, float o, TeamId teamId)
Definition at line 792 of file Battlefield.cpp.
 {
     //Get map object
     Map* map = sMapMgr->CreateBaseMap(m_MapId);
     if (!map)
     {
         LOG_ERROR("bg.battlefield", "Battlefield::SpawnCreature: Can't create creature entry: %u map not found", entry);
         return nullptr;
     }
     CreatureTemplate const* cinfo = sObjectMgr->GetCreatureTemplate(entry);
     if (!cinfo)
     {
         LOG_ERROR("sql.sql", "Battlefield::SpawnCreature: entry %u does not exist.", entry);
         return nullptr;
     }
     Creature* creature = new Creature(true);
     if (!creature->Create(map->GenerateLowGuid<HighGuid::Unit>(), map, PHASEMASK_NORMAL, entry, 0, x, y, z, o))
     {
         LOG_ERROR("bg.battlefield", "Battlefield::SpawnCreature: Can't create creature entry: %u", entry);
         delete creature;
         return nullptr;
     }
     creature->SetFaction(BattlefieldFactions[teamId]);
     creature->SetHomePosition(x, y, z, o);
     // force using DB speeds -- do we really need this?
     creature->SetSpeed(MOVE_WALK, cinfo->speed_walk);
     creature->SetSpeed(MOVE_RUN, cinfo->speed_run);
     // Set creature in world
     map->AddToMap(creature);
     creature->setActive(true);
     return creature;
 }
References Map::AddToMap(), BattlefieldFactions, Creature::Create(), Map::GenerateLowGuid(), LOG_ERROR, m_MapId, MOVE_RUN, MOVE_WALK, PHASEMASK_NORMAL, WorldObject::setActive(), Unit::SetFaction(), Creature::SetHomePosition(), Unit::SetSpeed(), sMapMgr, sObjectMgr, CreatureTemplate::speed_run, CreatureTemplate::speed_walk, and Unit.
Referenced by BfWGGameObjectBuilding::Init(), InitStalker(), BattlefieldWG::SetupBattlefield(), and SpawnCreature().
SpawnCreature() [2/2]
Creature * Battlefield::SpawnCreature (uint32 entry, Position pos, TeamId teamId)
Definition at line 787 of file Battlefield.cpp.
 {
     return SpawnCreature(entry, pos.m_positionX, pos.m_positionY, pos.m_positionZ, pos.m_orientation, teamId);
 }
References Position::m_orientation, Position::m_positionX, Position::m_positionY, Position::m_positionZ, and SpawnCreature().
SpawnGameObject()
GameObject * Battlefield::SpawnGameObject (uint32 entry, float x, float y, float z, float o)
Definition at line 832 of file Battlefield.cpp.
 {
     // Get map object
     Map* map = sMapMgr->CreateBaseMap(m_MapId);
     if (!map)
         return 0;
     // Create gameobject
     GameObject* go = sObjectMgr->IsGameObjectStaticTransport(entry) ? new StaticTransport() : new GameObject();
     if (!go->Create(map->GenerateLowGuid<HighGuid::GameObject>(), entry, map, PHASEMASK_NORMAL, x, y, z, o, G3D::Quat(), 100, GO_STATE_READY))
     {
         LOG_ERROR("sql.sql", "Battlefield::SpawnGameObject: Gameobject template %u not found in database! Battlefield not created!", entry);
         LOG_ERROR("bg.battlefield", "Battlefield::SpawnGameObject: Cannot create gameobject template %u! Battlefield not created!", entry);
         delete go;
         return nullptr;
     }
     // Add to world
     map->AddToMap(go);
     go->setActive(true);
     return go;
 }
References Map::AddToMap(), GameObject::Create(), GameObject, Map::GenerateLowGuid(), GO_STATE_READY, LOG_ERROR, m_MapId, PHASEMASK_NORMAL, WorldObject::setActive(), sMapMgr, and sObjectMgr.
Referenced by BfWGGameObjectBuilding::Init(), BattlefieldWG::OnBattleStart(), and BattlefieldWG::SetupBattlefield().
StartBattle()
void Battlefield::StartBattle ()
Definition at line 328 of file Battlefield.cpp.
 {
     if (m_isActive)
         return;
     for (int team = 0; team < BG_TEAMS_COUNT; team++)
     {
         m_PlayersInWar[team].clear();
         m_Groups[team].clear();
     }
     m_Timer = m_BattleTime;
     m_isActive = true;
     InvitePlayersInZoneToWar();
     InvitePlayersInQueueToWar();
     DoPlaySoundToAll(BF_START);
     OnBattleStart();
 }
References BF_START, BG_TEAMS_COUNT, DoPlaySoundToAll(), InvitePlayersInQueueToWar(), InvitePlayersInZoneToWar(), m_BattleTime, m_Groups, m_isActive, m_PlayersInWar, m_Timer, and OnBattleStart().
Referenced by bf_commandscript::HandleBattlefieldStart(), and Update().
TeamApplyBuff()
void Battlefield::TeamApplyBuff (TeamId team, uint32 spellId, uint32 spellId2 = 0)
TeamCastSpell()
void Battlefield::TeamCastSpell (TeamId team, int32 spellId) protected
Definition at line 433 of file Battlefield.cpp.
 {
     if (spellId > 0)
     {
         for (GuidUnorderedSet::const_iterator itr = m_PlayersInWar[team].begin(); itr != m_PlayersInWar[team].end(); ++itr)
             if (Player* player = ObjectAccessor::FindPlayer(*itr))
                 player->CastSpell(player, uint32(spellId), true);
     }
     else
     {
         for (GuidUnorderedSet::const_iterator itr = m_PlayersInWar[team].begin(); itr != m_PlayersInWar[team].end(); ++itr)
             if (Player* player = ObjectAccessor::FindPlayer(*itr))
                 player->RemoveAuraFromStack(uint32(-spellId));
     }
 }
References ObjectAccessor::FindPlayer(), and m_PlayersInWar.
ToggleBattlefield()
void Battlefield::ToggleBattlefield (bool enable) inline
Enable or Disable battlefield.
Definition at line 251 of file Battlefield.h.
 { m_IsEnabled = enable; }
References m_IsEnabled.
Referenced by bf_commandscript::HandleBattlefieldEnable().
Update()
bool Battlefield::Update (uint32 diff) virtual
Called every time for update bf data and time.
Update timer for start/end battle
Invite player in zone to queue m_StartGroupingTimer minutes before start
Kick Afk players
Parameters
diff : time ellapsed since last call (in ms)
Reimplemented in BattlefieldWG.
Definition at line 135 of file Battlefield.cpp.
 {
     if (m_Timer <= diff)
     {
         if (!IsEnabled() || (!IsWarTime() && sWorld->GetActiveSessionCount() > 3500)) // if WG is disabled or there is more than 3500 connections, switch automaticly
         {
             m_isActive = true;
             EndBattle(false);
             return false;
         }
         // Battlefield ends on time
         if (IsWarTime())
             EndBattle(true);
         else // Time to start a new battle!
             StartBattle();
     }
     else
         m_Timer -= diff;
     if (!IsEnabled())
         return false;
     // Invite players a few minutes before the battle's beginning
     if (!IsWarTime() && !m_StartGrouping && m_Timer <= m_StartGroupingTimer)
     {
         m_StartGrouping = true;
         InvitePlayersInZoneToQueue();
         OnStartGrouping();
     }
     bool objective_changed = false;
     if (IsWarTime())
     {
         if (m_uiKickAfkPlayersTimer <= diff)
         {
             m_uiKickAfkPlayersTimer = 20000;
             KickAfkPlayers();
         }
         else
             m_uiKickAfkPlayersTimer -= diff;
         // Kick players who chose not to accept invitation to the battle
         if (m_uiKickDontAcceptTimer <= diff)
         {
             time_t now = time(nullptr);
             for (int team = 0; team < 2; team++)
                 for (PlayerTimerMap::iterator itr = m_InvitedPlayers[team].begin(); itr != m_InvitedPlayers[team].end(); ++itr)
                     if (itr->second <= now)
                         KickPlayerFromBattlefield(itr->first);
             InvitePlayersInZoneToWar();
             for (int team = 0; team < 2; team++)
                 for (PlayerTimerMap::iterator itr = m_PlayersWillBeKick[team].begin(); itr != m_PlayersWillBeKick[team].end(); ++itr)
                     if (itr->second <= now)
                         KickPlayerFromBattlefield(itr->first);
             m_uiKickDontAcceptTimer = 5000;
         }
         else
             m_uiKickDontAcceptTimer -= diff;
         for (BfCapturePointVector::iterator itr = m_capturePoints.begin(); itr != m_capturePoints.end(); ++itr)
             if ((*itr)->Update(diff))
                 objective_changed = true;
     }
     if (m_LastResurectTimer <= diff)
     {
         for (uint8 i = 0; i < m_GraveyardList.size(); i++)
             if (GetGraveyardById(i))
                 m_GraveyardList[i]->Resurrect();
         m_LastResurectTimer = RESURRECTION_INTERVAL;
     }
     else
         m_LastResurectTimer -= diff;
     return objective_changed;
 }
References EndBattle(), GetGraveyardById(), InvitePlayersInZoneToQueue(), InvitePlayersInZoneToWar(), IsEnabled(), IsWarTime(), KickAfkPlayers(), KickPlayerFromBattlefield(), m_capturePoints, m_GraveyardList, m_InvitedPlayers, m_isActive, m_LastResurectTimer, m_PlayersWillBeKick, m_StartGrouping, m_StartGroupingTimer, m_Timer, m_uiKickAfkPlayersTimer, m_uiKickDontAcceptTimer, OnStartGrouping(), RESURRECTION_INTERVAL, StartBattle(), and sWorld.
Referenced by BattlefieldWG::Update().
UpdateData()
virtual void Battlefield::UpdateData (uint32 index, int32 pad) inline virtual
Definition at line 273 of file Battlefield.h.
 { m_Data32[index] += pad; }
References m_Data32.
Referenced by BattlefieldWG::FindAndRemoveVehicleFromList(), BattlefieldWG::OnCreatureCreate(), BattlefieldWG::UpdateCounterVehicle(), BattlefieldWG::UpdateDamagedTowerCount(), and BattlefieldWG::UpdatedDestroyedTowerCount().
Friends And Related Function Documentation
BattlefieldMgr
friend class BattlefieldMgr friend
Definition at line 206 of file Battlefield.h.
Member Data Documentation
KickPosition
WorldLocation Battlefield::KickPosition protected
Definition at line 395 of file Battlefield.h.
Referenced by KickAfkPlayers(), KickPlayerFromBattlefield(), and BattlefieldWG::SetupBattlefield().
m_BattleId
uint32 Battlefield::m_BattleId protected
Definition at line 383 of file Battlefield.h.
Referenced by Battlefield(), GetBattleId(), HandlePlayerLeaveZone(), InvitePlayerToQueue(), InvitePlayerToWar(), PlayerAcceptInviteToQueue(), PlayerAcceptInviteToWar(), and BattlefieldWG::SetupBattlefield().
m_BattleTime
uint32 Battlefield::m_BattleTime protected
Definition at line 390 of file Battlefield.h.
Referenced by Battlefield(), BattlefieldWG::SetupBattlefield(), and StartBattle().
m_capturePoints
BfCapturePointVector Battlefield::m_capturePoints protected
Definition at line 372 of file Battlefield.h.
Referenced by AddCapturePoint(), HandlePlayerLeaveZone(), Update(), and ~Battlefield().
m_Data32
std::vector<uint32> Battlefield::m_Data32 protected
Definition at line 409 of file Battlefield.h.
Referenced by GetData(), SetData(), BattlefieldWG::SetupBattlefield(), and UpdateData().
m_Data64
std::vector<uint64> Battlefield::m_Data64 protected
Definition at line 408 of file Battlefield.h.
Referenced by GetData64(), and SetData64().
m_DefenderTeam
TeamId Battlefield::m_DefenderTeam protected
Definition at line 369 of file Battlefield.h.
Referenced by Battlefield(), GetAttackerTeam(), GetDefenderTeam(), BattlefieldWG::OnBattleEnd(), BattlefieldWG::OnPlayerEnterZone(), SetDefenderTeam(), BattlefieldWG::SetupBattlefield(), and BattlefieldWG::Update().
m_GraveyardList
GraveyardVect Battlefield::m_GraveyardList protected
Definition at line 400 of file Battlefield.h.
Referenced by AddPlayerToResurrectQueue(), GetClosestGraveyard(), GetGraveyardById(), GetGraveyardVector(), BattlefieldWG::OnCreatureCreate(), RemovePlayerFromResurrectQueue(), SetGraveyardNumber(), BattlefieldWG::SetupBattlefield(), Update(), and ~Battlefield().
m_Groups
GuidUnorderedSet Battlefield::m_Groups[BG_TEAMS_COUNT] protected
Definition at line 406 of file Battlefield.h.
Referenced by AddOrSetPlayerToCorrectBfGroup(), GetFreeBfRaid(), GetGroupPlayer(), and StartBattle().
m_InvitedPlayers
PlayerTimerMap Battlefield::m_InvitedPlayers[BG_TEAMS_COUNT] protected
Definition at line 378 of file Battlefield.h.
Referenced by HandlePlayerEnterZone(), HandlePlayerLeaveZone(), InvitePlayersInQueueToWar(), InvitePlayersInZoneToWar(), InvitePlayerToWar(), PlayerAcceptInviteToWar(), and Update().
m_isActive
bool Battlefield::m_isActive protected
Definition at line 368 of file Battlefield.h.
Referenced by Battlefield(), CanFlyIn(), EndBattle(), IsWarTime(), BattlefieldWG::OnPlayerEnterZone(), BattlefieldWG::OnPlayerLeaveZone(), BattlefieldWG::PromotePlayer(), BattlefieldWG::SetupBattlefield(), StartBattle(), Update(), and BattlefieldWG::Update().
m_IsEnabled
bool Battlefield::m_IsEnabled protected
Definition at line 367 of file Battlefield.h.
Referenced by Battlefield(), IsEnabled(), BattlefieldWG::SetupBattlefield(), and ToggleBattlefield().
m_LastResurectTimer
uint32 Battlefield::m_LastResurectTimer protected
Definition at line 401 of file Battlefield.h.
Referenced by Battlefield(), SendAreaSpiritHealerQueryOpcode(), and Update().
m_Map
Map* Battlefield::m_Map protected
Definition at line 386 of file Battlefield.h.
Referenced by Battlefield(), GetCreature(), GetGameObject(), and BattlefieldWG::SetupBattlefield().
m_MapId
uint32 Battlefield::m_MapId protected
Definition at line 385 of file Battlefield.h.
Referenced by Battlefield(), BattlefieldWG::SendInitWorldStatesTo(), BattlefieldWG::SetupBattlefield(), SpawnCreature(), and SpawnGameObject().
m_MaxPlayer
uint32 Battlefield::m_MaxPlayer protected
Definition at line 387 of file Battlefield.h.
Referenced by Battlefield(), HandlePlayerEnterZone(), InvitePlayersInQueueToWar(), InvitePlayersInZoneToWar(), and BattlefieldWG::SetupBattlefield().
m_MinLevel
uint32 Battlefield::m_MinLevel protected
Definition at line 389 of file Battlefield.h.
Referenced by Battlefield(), InvitePlayerToWar(), and BattlefieldWG::SetupBattlefield().
m_MinPlayer
uint32 Battlefield::m_MinPlayer protected
Definition at line 388 of file Battlefield.h.
Referenced by Battlefield(), InvitePlayerToQueue(), and BattlefieldWG::SetupBattlefield().
m_NoWarBattleTime
uint32 Battlefield::m_NoWarBattleTime protected
Definition at line 391 of file Battlefield.h.
Referenced by Battlefield(), EndBattle(), and BattlefieldWG::SetupBattlefield().
m_players
GuidUnorderedSet Battlefield::m_players[BG_TEAMS_COUNT] protected
Definition at line 375 of file Battlefield.h.
Referenced by BroadcastPacketToZone(), BattlefieldWG::CapturePointTaken(), HandlePlayerEnterZone(), HandlePlayerLeaveZone(), HasPlayer(), InvitePlayersInZoneToQueue(), InvitePlayersInZoneToWar(), BattlefieldWG::OnBattleEnd(), BattlefieldWG::OnBattleStart(), BattlefieldWG::SendInitWorldStatesToAll(), SendUpdateWorldState(), and BattlefieldWG::UpdateVehicleCountWG().
m_PlayersInQueue
GuidUnorderedSet Battlefield::m_PlayersInQueue[BG_TEAMS_COUNT] protected
Definition at line 376 of file Battlefield.h.
Referenced by AskToLeaveQueue(), BroadcastPacketToQueue(), InvitePlayersInQueueToWar(), InvitePlayerToQueue(), InvitePlayerToWar(), and PlayerAcceptInviteToQueue().
m_PlayersInWar
GuidUnorderedSet Battlefield::m_PlayersInWar[BG_TEAMS_COUNT] protected
Definition at line 377 of file Battlefield.h.
Referenced by BroadcastPacketToWar(), DoPlaySoundToAll(), BattlefieldWG::HandleKill(), HandlePlayerEnterZone(), HandlePlayerLeaveZone(), InvitePlayersInQueueToWar(), InvitePlayersInZoneToWar(), InvitePlayerToWar(), KickAfkPlayers(), BattlefieldWG::OnBattleEnd(), PlayerAcceptInviteToWar(), StartBattle(), TeamCastSpell(), BattlefieldWG::UpdatedDestroyedTowerCount(), and BattlefieldWG::UpdateTenacity().
m_PlayersWillBeKick
PlayerTimerMap Battlefield::m_PlayersWillBeKick[BG_TEAMS_COUNT] protected
Definition at line 379 of file Battlefield.h.
Referenced by HandlePlayerEnterZone(), HandlePlayerLeaveZone(), InvitePlayersInZoneToWar(), InvitePlayerToWar(), and Update().
m_RestartAfterCrash
uint32 Battlefield::m_RestartAfterCrash protected
Definition at line 392 of file Battlefield.h.
Referenced by Battlefield(), and BattlefieldWG::SetupBattlefield().
m_StartGrouping
bool Battlefield::m_StartGrouping protected
Definition at line 404 of file Battlefield.h.
Referenced by Battlefield(), EndBattle(), BattlefieldWG::SetupBattlefield(), and Update().
m_StartGroupingTimer
uint32 Battlefield::m_StartGroupingTimer protected
Definition at line 403 of file Battlefield.h.
Referenced by Battlefield(), HandlePlayerEnterZone(), BattlefieldWG::SetupBattlefield(), and Update().
m_TimeForAcceptInvite
uint32 Battlefield::m_TimeForAcceptInvite protected
Definition at line 393 of file Battlefield.h.
Referenced by Battlefield(), InvitePlayerToWar(), and BattlefieldWG::SetupBattlefield().
m_Timer
uint32 Battlefield::m_Timer protected
Definition at line 366 of file Battlefield.h.
Referenced by Battlefield(), EndBattle(), BattlefieldWG::FillInitialWorldStates(), GetTimer(), HandlePlayerEnterZone(), SetTimer(), BattlefieldWG::SetupBattlefield(), StartBattle(), Update(), BattlefieldWG::Update(), and BattlefieldWG::UpdatedDestroyedTowerCount().
m_TypeId
uint32 Battlefield::m_TypeId protected
Definition at line 382 of file Battlefield.h.
Referenced by Battlefield(), GetTypeId(), and BattlefieldWG::SetupBattlefield().
m_uiKickAfkPlayersTimer
uint32 Battlefield::m_uiKickAfkPlayersTimer protected
Definition at line 397 of file Battlefield.h.
Referenced by Battlefield(), and Update().
m_uiKickDontAcceptTimer
uint32 Battlefield::m_uiKickDontAcceptTimer protected
Definition at line 394 of file Battlefield.h.
Referenced by Battlefield(), and Update().
m_ZoneId
uint32 Battlefield::m_ZoneId protected
Definition at line 384 of file Battlefield.h.
Referenced by Battlefield(), GetZoneId(), InvitePlayerToWar(), PlayerAcceptInviteToQueue(), BattlefieldWG::SendInitWorldStatesTo(), and BattlefieldWG::SetupBattlefield().
StalkerGuid
ObjectGuid Battlefield::StalkerGuid protected
Definition at line 365 of file Battlefield.h.
Referenced by InitStalker(), SendWarningToAllInZone(), and SendWarningToPlayer().
The documentation for this class was generated from the following files:
src/server/game/Battlefield/Battlefield.h
src/server/game/Battlefield/Battlefield.cpp