Azerotcore-wotlk: deps/mysqllite/strings/ctype.c File Reference
ctype.c File Reference
#include <my_global.h>
#include <m_ctype.h>
#include <my_xml.h>
#include <m_string.h>
Classes
struct my_cs_file_section_st
struct my_cs_file_info
Macros
#define _CS_MISC 1
#define _CS_ID 2
#define _CS_CSNAME 3
#define _CS_FAMILY 4
#define _CS_ORDER 5
#define _CS_COLNAME 6
#define _CS_FLAG 7
#define _CS_CHARSET 8
#define _CS_COLLATION 9
#define _CS_UPPERMAP 10
#define _CS_LOWERMAP 11
#define _CS_UNIMAP 12
#define _CS_COLLMAP 13
#define _CS_CTYPEMAP 14
#define _CS_PRIMARY_ID 15
#define _CS_BINARY_ID 16
#define _CS_CSDESCRIPT 17
#define _CS_RESET 18
#define _CS_DIFF1 19
#define _CS_DIFF2 20
#define _CS_DIFF3 21
#define _CS_IDENTICAL 22
#define MY_CS_CSDESCR_SIZE 64
#define MY_CS_TAILORING_SIZE 1024
Typedefs
typedef struct my_cs_file_info MY_CHARSET_LOADER
Functions
static char * mstr (char *str, const char *src, size_t l1, size_t l2)
static struct my_cs_file_section_st * cs_file_sec (const char *attr, size_t len)
static int fill_uchar (uchar *a, uint size, const char *str, size_t len)
static int fill_uint16 (uint16 *a, uint size, const char *str, size_t len)
static int cs_enter (MY_XML_PARSER *st, const char *attr, size_t len)
static int cs_leave (MY_XML_PARSER *st, const char *attr, size_t len)
static int cs_value (MY_XML_PARSER *st, const char *attr, size_t len)
my_bool my_parse_charset_xml (const char *buf, size_t len, int(*add_collation)(CHARSET_INFO *cs))
uint my_string_repertoire (CHARSET_INFO *cs, const char *str, ulong length)
uint my_charset_repertoire (CHARSET_INFO *cs)
my_bool my_charset_is_ascii_based (CHARSET_INFO *cs)
my_bool my_charset_is_8bit_pure_ascii (CHARSET_INFO *cs)
my_bool my_charset_is_ascii_compatible (CHARSET_INFO *cs)
Variables
static struct my_cs_file_section_st sec []
Macro Definition Documentation
_CS_BINARY_ID
#define _CS_BINARY_ID 16
Definition at line 71 of file ctype.c.
_CS_CHARSET
#define _CS_CHARSET 8
Definition at line 63 of file ctype.c.
_CS_COLLATION
#define _CS_COLLATION 9
Definition at line 64 of file ctype.c.
_CS_COLLMAP
#define _CS_COLLMAP 13
Definition at line 68 of file ctype.c.
_CS_COLNAME
#define _CS_COLNAME 6
Definition at line 61 of file ctype.c.
_CS_CSDESCRIPT
#define _CS_CSDESCRIPT 17
Definition at line 72 of file ctype.c.
_CS_CSNAME
#define _CS_CSNAME 3
Definition at line 58 of file ctype.c.
_CS_CTYPEMAP
#define _CS_CTYPEMAP 14
Definition at line 69 of file ctype.c.
_CS_DIFF1
#define _CS_DIFF1 19
Definition at line 74 of file ctype.c.
_CS_DIFF2
#define _CS_DIFF2 20
Definition at line 75 of file ctype.c.
_CS_DIFF3
#define _CS_DIFF3 21
Definition at line 76 of file ctype.c.
_CS_FAMILY
#define _CS_FAMILY 4
Definition at line 59 of file ctype.c.
_CS_FLAG
#define _CS_FLAG 7
Definition at line 62 of file ctype.c.
_CS_ID
#define _CS_ID 2
Definition at line 57 of file ctype.c.
_CS_IDENTICAL
#define _CS_IDENTICAL 22
Definition at line 77 of file ctype.c.
_CS_LOWERMAP
#define _CS_LOWERMAP 11
Definition at line 66 of file ctype.c.
_CS_MISC
#define _CS_MISC 1
Definition at line 56 of file ctype.c.
_CS_ORDER
#define _CS_ORDER 5
Definition at line 60 of file ctype.c.
_CS_PRIMARY_ID
#define _CS_PRIMARY_ID 15
Definition at line 70 of file ctype.c.
_CS_RESET
#define _CS_RESET 18
Definition at line 73 of file ctype.c.
_CS_UNIMAP
#define _CS_UNIMAP 12
Definition at line 67 of file ctype.c.
_CS_UPPERMAP
#define _CS_UPPERMAP 10
Definition at line 65 of file ctype.c.
MY_CS_CSDESCR_SIZE
#define MY_CS_CSDESCR_SIZE 64
Definition at line 127 of file ctype.c.
MY_CS_TAILORING_SIZE
#define MY_CS_TAILORING_SIZE 1024
Definition at line 128 of file ctype.c.
Typedef Documentation
MY_CHARSET_LOADER
typedef struct my_cs_file_info MY_CHARSET_LOADER
Function Documentation
cs_enter()
static int cs_enter (MY_XML_PARSER * st, const char * attr, size_t len) static
Definition at line 183 of file ctype.c.
 {
   struct my_cs_file_info *i= (struct my_cs_file_info *)st->user_data;
   struct my_cs_file_section_st *s= cs_file_sec(attr,len);
   if ( s && (s->state == _CS_CHARSET))
     bzero(&i->cs,sizeof(i->cs));
   if (s && (s->state == _CS_COLLATION))
     i->tailoring_length= 0;
   return MY_XML_OK;
 }
References _CS_CHARSET, _CS_COLLATION, bzero, my_cs_file_info::cs, cs_file_sec(), MY_XML_OK, my_cs_file_info::tailoring_length, and xml_stack_st::user_data.
Referenced by my_parse_charset_xml().
cs_file_sec()
static struct my_cs_file_section_st* cs_file_sec (const char * attr, size_t len) static
Definition at line 116 of file ctype.c.
 {
   struct my_cs_file_section_st *s;
   for (s=sec; s->str; s++)
   {
     if (!strncmp(attr,s->str,len))
       return s;
   }
   return NULL;
 }
References NULL, sec, and my_cs_file_section_st::str.
Referenced by cs_enter(), cs_leave(), and cs_value().
cs_leave()
static int cs_leave (MY_XML_PARSER * st, const char * attr, size_t len) static
Definition at line 198 of file ctype.c.
 {
   struct my_cs_file_info *i= (struct my_cs_file_info *)st->user_data;
   struct my_cs_file_section_st *s= cs_file_sec(attr,len);
   int    state= s ? s->state : 0;
   int    rc;
   switch(state){
   case _CS_COLLATION:
     rc= i->add_collation ? i->add_collation(&i->cs) : MY_XML_OK;
     break;
   default:
     rc=MY_XML_OK;
   }
   return rc;
 }
References _CS_COLLATION, my_cs_file_info::add_collation, my_cs_file_info::cs, cs_file_sec(), MY_XML_OK, my_cs_file_section_st::state, and xml_stack_st::user_data.
Referenced by my_parse_charset_xml().
cs_value()
static int cs_value (MY_XML_PARSER * st, const char * attr, size_t len) static
Definition at line 216 of file ctype.c.
 {
   struct my_cs_file_info *i= (struct my_cs_file_info *)st->user_data;
   struct my_cs_file_section_st *s;
   int    state= (int)((s=cs_file_sec(st->attr, strlen(st->attr))) ? s->state :
                       0);
   switch (state) {
   case _CS_ID:
     i->cs.number= strtol(attr,(char**)NULL,10);
     break;
   case _CS_BINARY_ID:
     i->cs.binary_number= strtol(attr,(char**)NULL,10);
     break;
   case _CS_PRIMARY_ID:
     i->cs.primary_number= strtol(attr,(char**)NULL,10);
     break;
   case _CS_COLNAME:
     i->cs.name=mstr(i->name,attr,len,MY_CS_NAME_SIZE-1);
     break;
   case _CS_CSNAME:
     i->cs.csname=mstr(i->csname,attr,len,MY_CS_NAME_SIZE-1);
     break;
   case _CS_CSDESCRIPT:
     i->cs.comment=mstr(i->comment,attr,len,MY_CS_CSDESCR_SIZE-1);
     break;
   case _CS_FLAG:
     if (!strncmp("primary",attr,len))
       i->cs.state|= MY_CS_PRIMARY;
     else if (!strncmp("binary",attr,len))
       i->cs.state|= MY_CS_BINSORT;
     else if (!strncmp("compiled",attr,len))
       i->cs.state|= MY_CS_COMPILED;
     break;
   case _CS_UPPERMAP:
     fill_uchar(i->to_upper,MY_CS_TO_UPPER_TABLE_SIZE,attr,len);
     i->cs.to_upper=i->to_upper;
     break;
   case _CS_LOWERMAP:
     fill_uchar(i->to_lower,MY_CS_TO_LOWER_TABLE_SIZE,attr,len);
     i->cs.to_lower=i->to_lower;
     break;
   case _CS_UNIMAP:
     fill_uint16(i->tab_to_uni,MY_CS_TO_UNI_TABLE_SIZE,attr,len);
     i->cs.tab_to_uni=i->tab_to_uni;
     break;
   case _CS_COLLMAP:
     fill_uchar(i->sort_order,MY_CS_SORT_ORDER_TABLE_SIZE,attr,len);
     i->cs.sort_order=i->sort_order;
     break;
   case _CS_CTYPEMAP:
     fill_uchar(i->ctype,MY_CS_CTYPE_TABLE_SIZE,attr,len);
     i->cs.ctype=i->ctype;
     break;
   case _CS_RESET:
   case _CS_DIFF1:
   case _CS_DIFF2:
   case _CS_DIFF3:
   case _CS_IDENTICAL:
     {
       /*
         Convert collation description from
         Locale Data Markup Language (LDML)
         into ICU Collation Customization expression.
       */
       char arg[16];
       const char *cmd[]= {"&","<","<<","<<<","="};
       i->cs.tailoring= i->tailoring;
       mstr(arg,attr,len,sizeof(arg)-1);
       if (i->tailoring_length + 20 < sizeof(i->tailoring))
       {
         char *dst= i->tailoring_length + i->tailoring;
         i->tailoring_length+= sprintf(dst," %s %s",cmd[state-_CS_RESET],arg);
       }
     }
   }
   return MY_XML_OK;
 }
References _CS_BINARY_ID, _CS_COLLMAP, _CS_COLNAME, _CS_CSDESCRIPT, _CS_CSNAME, _CS_CTYPEMAP, _CS_DIFF1, _CS_DIFF2, _CS_DIFF3, _CS_FLAG, _CS_ID, _CS_IDENTICAL, _CS_LOWERMAP, _CS_PRIMARY_ID, _CS_RESET, _CS_UNIMAP, _CS_UPPERMAP, arg(), xml_stack_st::attr, charset_info_st::binary_number, charset_info_st::comment, my_cs_file_info::comment, my_cs_file_info::cs, cs_file_sec(), charset_info_st::csname, my_cs_file_info::csname, charset_info_st::ctype, my_cs_file_info::ctype, fill_uchar(), fill_uint16(), mstr(), MY_CS_BINSORT, MY_CS_COMPILED, MY_CS_CSDESCR_SIZE, MY_CS_CTYPE_TABLE_SIZE, MY_CS_NAME_SIZE, MY_CS_PRIMARY, MY_CS_SORT_ORDER_TABLE_SIZE, MY_CS_TO_LOWER_TABLE_SIZE, MY_CS_TO_UNI_TABLE_SIZE, MY_CS_TO_UPPER_TABLE_SIZE, MY_XML_OK, charset_info_st::name, my_cs_file_info::name, NULL, charset_info_st::number, charset_info_st::primary_number, charset_info_st::sort_order, my_cs_file_info::sort_order, sprintf(), charset_info_st::state, strtol(), charset_info_st::tab_to_uni, my_cs_file_info::tab_to_uni, charset_info_st::tailoring, my_cs_file_info::tailoring, my_cs_file_info::tailoring_length, charset_info_st::to_lower, my_cs_file_info::to_lower, charset_info_st::to_upper, my_cs_file_info::to_upper, and xml_stack_st::user_data.
Referenced by my_parse_charset_xml().
fill_uchar()
static int fill_uchar (uchar * a, uint size, const char * str, size_t len) static
Definition at line 148 of file ctype.c.
 {
   uint i= 0;
   const char *s, *b, *e=str+len;
   for (s=str ; s < e ; i++)
   {
     for ( ; (s < e) && strchr(" \t\r\n",s[0]); s++) ;
     b=s;
     for ( ; (s < e) && !strchr(" \t\r\n",s[0]); s++) ;
     if (s == b || i > size)
       break;
     a[i]= (uchar) strtoul(b,NULL,16);
   }
   return 0;
 }
References mpq::a, b, NULL, and strtoul().
Referenced by cs_value().
fill_uint16()
static int fill_uint16 (uint16 * a, uint size, const char * str, size_t len) static
Definition at line 165 of file ctype.c.
 {
   uint i= 0;
   const char *s, *b, *e=str+len;
   for (s=str ; s < e ; i++)
   {
     for ( ; (s < e) && strchr(" \t\r\n",s[0]); s++) ;
     b=s;
     for ( ; (s < e) && !strchr(" \t\r\n",s[0]); s++) ;
     if (s == b || i > size)
       break;
     a[i]= (uint16) strtol(b,NULL,16);
   }
   return 0;
 }
References mpq::a, b, NULL, and strtol().
Referenced by cs_value().
mstr()
static char* mstr (char * str, const char * src, size_t l1, size_t l2) static
Definition at line 42 of file ctype.c.
 {
   l1= l1<l2 ? l1 : l2;
   memcpy(str,src,l1);
   str[l1]='\0';
   return str;
 }
References memcpy.
Referenced by cs_value().
my_charset_is_8bit_pure_ascii()
my_bool my_charset_is_8bit_pure_ascii (CHARSET_INFO * cs)
Definition at line 399 of file ctype.c.
 {
   size_t code;
   if (!cs->tab_to_uni)
     return 0;
   for (code= 0; code < 256; code++)
   {
     if (cs->tab_to_uni[code] > 0x7F)
       return 0;
   }
   return 1;
 }
References my_cs_file_info::cs, and charset_info_st::tab_to_uni.
Referenced by add_collation().
my_charset_is_ascii_based()
my_bool my_charset_is_ascii_based (CHARSET_INFO * cs)
Definition at line 383 of file ctype.c.
 {
   return
     (cs->mbmaxlen == 1 && cs->tab_to_uni && cs->tab_to_uni['{'] == '{') ||
     (cs->mbminlen == 1 && cs->mbmaxlen > 1);
 }
References my_cs_file_info::cs, charset_info_st::mbmaxlen, charset_info_st::mbminlen, and charset_info_st::tab_to_uni.
my_charset_is_ascii_compatible()
my_bool my_charset_is_ascii_compatible (CHARSET_INFO * cs)
Definition at line 419 of file ctype.c.
 {
   uint i;
   if (!cs->tab_to_uni)
     return 1;
   for (i= 0; i < 128; i++)
   {
     if (cs->tab_to_uni[i] != i)
       return 0;
   }
   return 1;
 }
References my_cs_file_info::cs, and charset_info_st::tab_to_uni.
Referenced by add_collation().
my_charset_repertoire()
uint my_charset_repertoire (CHARSET_INFO * cs)
Definition at line 349 of file ctype.c.
 {
   return cs->state & MY_CS_PUREASCII ?
     MY_REPERTOIRE_ASCII : MY_REPERTOIRE_UNICODE30;
 }
References my_cs_file_info::cs, MY_CS_PUREASCII, MY_REPERTOIRE_ASCII, MY_REPERTOIRE_UNICODE30, and charset_info_st::state.
my_parse_charset_xml()
my_bool my_parse_charset_xml (const char * buf, size_t len, int(*)(CHARSET_INFO *cs) add_collation)
Definition at line 296 of file ctype.c.
 {
   MY_XML_PARSER p;
   struct my_cs_file_info i;
   my_bool rc;
   my_xml_parser_create(&p);
   my_xml_set_enter_handler(&p,cs_enter);
   my_xml_set_value_handler(&p,cs_value);
   my_xml_set_leave_handler(&p,cs_leave);
   i.add_collation= add_collation;
   my_xml_set_user_data(&p,(void*)&i);
   rc= (my_xml_parse(&p,buf,len) == MY_XML_OK) ? FALSE : TRUE;
   my_xml_parser_free(&p);
   return rc;
 }
References add_collation(), my_cs_file_info::add_collation, cs_enter(), cs_leave(), cs_value(), FALSE, MY_XML_OK, my_xml_parse(), my_xml_parser_create(), my_xml_parser_free(), my_xml_set_enter_handler(), my_xml_set_leave_handler(), my_xml_set_user_data(), my_xml_set_value_handler(), and TRUE.
Referenced by my_read_charset_file().
my_string_repertoire()
uint my_string_repertoire (CHARSET_INFO * cs, const char * str, ulong length)
Definition at line 319 of file ctype.c.
 {
   const char *strend= str + length;
   if (cs->mbminlen == 1)
   {
     for ( ; str < strend; str++)
     {
       if (((uchar) *str) > 0x7F)
         return MY_REPERTOIRE_UNICODE30;
     }
   }
   else
   {
     my_wc_t wc;
     int chlen;
     for (;
          (chlen= cs->cset->mb_wc(cs, &wc, (uchar*) str, (uchar*) strend)) > 0;
          str+= chlen)
     {
       if (wc > 0x7F)
         return MY_REPERTOIRE_UNICODE30;
     }
   }
   return MY_REPERTOIRE_ASCII;
 }
References my_cs_file_info::cs, charset_info_st::cset, G3D::length(), my_charset_handler_st::mb_wc, charset_info_st::mbminlen, MY_REPERTOIRE_ASCII, MY_REPERTOIRE_UNICODE30, my_wc_t, and strend().
Variable Documentation
sec
struct my_cs_file_section_st sec[] static
Definition at line 42 of file ctype.c.
Referenced by Channel::Announce(), cs_file_sec(), World::KickAllLess(), Channel::KickOrBan(), my_sleep(), nstime_init2(), ScriptMgr::OnSetServerSideVisibility(), ScriptMgr::OnSetServerSideVisibilityDetect(), Movement::SecToMS(), Channel::SetMode(), Channel::SetOwner(), World::SetPlayerSecurityLimit(), Player::SetServerSideVisibility(), Player::SetServerSideVisibilityDetect(), thr_alarm(), and Channel::UnBan().