Azerotcore-wotlk: go_bristlelimb_cage Class Reference
go_bristlelimb_cage Class Reference
Public Member Functions
go_bristlelimb_cage ()
bool OnGossipHello (Player *player, GameObject *go) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Definition at line 504 of file zone_azuremyst_isle.cpp.
Constructor & Destructor Documentation
go_bristlelimb_cage()
go_bristlelimb_cage::go_bristlelimb_cage () inline
Definition at line 507 of file zone_azuremyst_isle.cpp.
 : GameObjectScript("go_bristlelimb_cage") { }
Member Function Documentation
OnGossipHello()
bool go_bristlelimb_cage::OnGossipHello (Player * player, GameObject * go) inline override virtual
Reimplemented from GameObjectScript.
Definition at line 509 of file zone_azuremyst_isle.cpp.
     {
         go->SetGoState(GO_STATE_READY);
         if (player->GetQuestStatus(QUEST_THE_PROPHECY_OF_AKIDA) == QUEST_STATUS_INCOMPLETE)
         {
             if (Creature* capitive = go->FindNearestCreature(NPC_STILLPINE_CAPITIVE, 5.0f, true))
             {
                 go->ResetDoorOrButton();
                 CAST_AI(npc_stillpine_capitive::npc_stillpine_capitiveAI, capitive->AI())->StartMoving(player);
                 return false;
             }
         }
         return true;
     }
References CAST_AI, WorldObject::FindNearestCreature(), Player::GetQuestStatus(), GO_STATE_READY, NPC_STILLPINE_CAPITIVE, QUEST_STATUS_INCOMPLETE, QUEST_THE_PROPHECY_OF_AKIDA, GameObject::ResetDoorOrButton(), and GameObject::SetGoState().
The documentation for this class was generated from the following file:
src/server/scripts/Kalimdor/zone_azuremyst_isle.cpp