Azerotcore-wotlk: boss_bjarngrim::boss_bjarngrimAI Struct Reference
boss_bjarngrim::boss_bjarngrimAI Struct Reference
Public Member Functions
boss_bjarngrimAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *) override
void KilledUnit (Unit *victim) override
void JustDied (Unit *) override
void RemoveStanceAura (uint8 stance)
void RollStance (uint8 stance, uint8 force=0)
void WaypointReached (uint32 Point) override
void UpdateEscortAI (uint32 diff) override
Public Member Functions inherited from npc_escortAI
npc_escortAI (Creature *creature)
~npc_escortAI () override
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void JustRespawned () override
void ReturnToLastPoint ()
void EnterEvadeMode () override
void UpdateAI (uint32 diff) override
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
virtual void WaypointStart (uint32)
void Start (bool isActiveAttacker=true, bool run=false, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetRun (bool on=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * m_pInstance
EventMap events
SummonList summons
uint8 m_uiStance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from npc_escortAI
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 119 of file boss_bjarngrim.cpp.
Constructor & Destructor Documentation
boss_bjarngrimAI()
boss_bjarngrim::boss_bjarngrimAI::boss_bjarngrimAI (Creature * creature) inline
Definition at line 121 of file boss_bjarngrim.cpp.
                                              : npc_escortAI(creature), summons(creature)
         {
             m_pInstance = creature->GetInstanceScript();
             // Init waypoints
             AddWaypoint(1, 1262.18f, 99.3f, 33.5f, 0);
             AddWaypoint(2, 1281.6f, 99.5f, 33.5f, 0);
             AddWaypoint(3, 1311.7f, 99.4f, 40.1f, 0);
             AddWaypoint(4, 1332.5f, 99.7f, 40.18f, 0);
             AddWaypoint(5, 1311.7f, 99.4f, 40.1f, 0);
             AddWaypoint(6, 1281.6f, 99.5f, 33.5f, 0);
             AddWaypoint(7, 1262.18f, 99.3f, 33.5f, 0);
             AddWaypoint(8, 1262, -26.9f, 33.5f, 0);
             AddWaypoint(9, 1281.2f, -26.8f, 33.5f, 0);
             AddWaypoint(10, 1311.3f, -26.9f, 40.03f, 0);
             AddWaypoint(11, 1332, -26.6f, 40.18f, 0);
             AddWaypoint(12, 1311.3f, -26.9f, 40.03f, 0);
             AddWaypoint(13, 1281.2f, -26.8f, 33.5f, 0);
             AddWaypoint(14, 1262, -26.9f, 33.5f, 0);
             Start(true, false, ObjectGuid::Empty, nullptr, false, true);
         }
References npc_escortAI::AddWaypoint(), ObjectGuid::Empty, WorldObject::GetInstanceScript(), m_pInstance, and npc_escortAI::Start().
Member Function Documentation
EnterCombat()
void boss_bjarngrim::boss_bjarngrimAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 169 of file boss_bjarngrim.cpp.
         {
             me->SetInCombatWithZone();
             Talk(SAY_AGGRO);
             events.ScheduleEvent(EVENT_BJARNGRIM_CHANGE_STANCE, 20000, 0);
             // DEFENSIVE STANCE
             events.ScheduleEvent(EVENT_BJARNGRIM_REFLECTION, 8000, STANCE_DEFENSIVE);
             events.ScheduleEvent(EVENT_BJARNGRIM_PUMMEL, 5000, STANCE_DEFENSIVE);
             events.ScheduleEvent(EVENT_BJARNGRIM_KNOCK, 16000, STANCE_DEFENSIVE);
             events.ScheduleEvent(EVENT_BJARNGRIM_IRONFORM, 12000, STANCE_DEFENSIVE);
             // BERSERKER STANCE
             events.ScheduleEvent(EVENT_BJARNGRIM_MORTAL_STRIKE, 20000 + 4000, STANCE_BERSERKER);
             events.ScheduleEvent(EVENT_BJARNGRIM_WHIRLWIND, 20000 + 6000, STANCE_BERSERKER);
             // BATTLE STANCE
             events.ScheduleEvent(EVENT_BJARNGRIM_INTERCEPT, 20000 + 3000, STANCE_BATTLE);
             events.ScheduleEvent(EVENT_BJARNGRIM_CLEAVE, 20000 + 5000, STANCE_BATTLE);
             events.ScheduleEvent(EVENT_BJARNGRIM_SLAM, 20000 + 10000, STANCE_BATTLE);
             if (m_pInstance)
             {
                 m_pInstance->SetData(TYPE_BJARNGRIM, IN_PROGRESS);
                 m_pInstance->SetData(DATA_BJARNGRIM_ACHIEVEMENT, me->HasAura(SPELL_TEMPORARY_ELECTRICAL_CHARGE));
             }
         }
References DATA_BJARNGRIM_ACHIEVEMENT, EVENT_BJARNGRIM_CHANGE_STANCE, EVENT_BJARNGRIM_CLEAVE, EVENT_BJARNGRIM_INTERCEPT, EVENT_BJARNGRIM_IRONFORM, EVENT_BJARNGRIM_KNOCK, EVENT_BJARNGRIM_MORTAL_STRIKE, EVENT_BJARNGRIM_PUMMEL, EVENT_BJARNGRIM_REFLECTION, EVENT_BJARNGRIM_SLAM, EVENT_BJARNGRIM_WHIRLWIND, Unit::HasAura(), IN_PROGRESS, m_pInstance, ScriptedAI::me, SAY_AGGRO, ZoneScript::SetData(), Creature::SetInCombatWithZone(), SPELL_TEMPORARY_ELECTRICAL_CHARGE, STANCE_BATTLE, STANCE_BERSERKER, STANCE_DEFENSIVE, CreatureAI::Talk(), and TYPE_BJARNGRIM.
JustDied()
void boss_bjarngrim::boss_bjarngrimAI::JustDied (Unit *) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 206 of file boss_bjarngrim.cpp.
         {
             Talk(SAY_DEATH);
             if (m_pInstance)
                 m_pInstance->SetData(TYPE_BJARNGRIM, DONE);
         }
References DONE, m_pInstance, SAY_DEATH, ZoneScript::SetData(), CreatureAI::Talk(), and TYPE_BJARNGRIM.
KilledUnit()
void boss_bjarngrim::boss_bjarngrimAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 198 of file boss_bjarngrim.cpp.
         {
             if (victim->GetTypeId() != TYPEID_PLAYER)
                 return;
             Talk(SAY_SLAY);
         }
References Object::GetTypeId(), SAY_SLAY, CreatureAI::Talk(), and TYPEID_PLAYER.
RemoveStanceAura()
void boss_bjarngrim::boss_bjarngrimAI::RemoveStanceAura (uint8 stance) inline
Definition at line 214 of file boss_bjarngrim.cpp.
         {
             switch (stance)
             {
                 case STANCE_DEFENSIVE:
                     me->RemoveAura(SPELL_DEFENSIVE_STANCE);
                     me->RemoveAura(SPELL_DEFENSIVE_AURA);
                     break;
                 case STANCE_BERSERKER:
                     me->RemoveAura(SPELL_BERSERKER_STANCE);
                     me->RemoveAura(SPELL_BERSERKER_AURA);
                     break;
                 case STANCE_BATTLE:
                     me->RemoveAura(SPELL_BATTLE_STANCE);
                     me->RemoveAura(SPELL_BATTLE_AURA);
                     break;
             }
         }
References ScriptedAI::me, Unit::RemoveAura(), SPELL_BATTLE_AURA, SPELL_BATTLE_STANCE, SPELL_BERSERKER_AURA, SPELL_BERSERKER_STANCE, SPELL_DEFENSIVE_AURA, SPELL_DEFENSIVE_STANCE, STANCE_BATTLE, STANCE_BERSERKER, and STANCE_DEFENSIVE.
Referenced by UpdateEscortAI().
Reset()
void boss_bjarngrim::boss_bjarngrimAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 149 of file boss_bjarngrim.cpp.
         {
             events.Reset();
             summons.DespawnAll();
             for (uint8 i = 0; i < 2; ++i)
                 if (Creature* dwarf = me->SummonCreature(NPC_STORMFORGED_LIEUTENANT, me->GetPositionX() + urand(4, 12), me->GetPositionY() + urand(4, 12), me->GetPositionZ()))
                 {
                     dwarf->GetMotionMaster()->MoveFollow(me, 3, rand_norm() * 2 * 3.14f);
                     summons.Summon(dwarf);
                 }
             me->RemoveAllAuras();
             me->CastSpell(me, SPELL_TEMPORARY_ELECTRICAL_CHARGE, true);
             RollStance(0, STANCE_DEFENSIVE);
             if (m_pInstance)
                 m_pInstance->SetData(TYPE_BJARNGRIM, NOT_STARTED);
         }
References Unit::CastSpell(), SummonList::DespawnAll(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), m_pInstance, ScriptedAI::me, NOT_STARTED, NPC_STORMFORGED_LIEUTENANT, rand_norm(), Unit::RemoveAllAuras(), RollStance(), ZoneScript::SetData(), SPELL_TEMPORARY_ELECTRICAL_CHARGE, STANCE_DEFENSIVE, SummonList::Summon(), WorldObject::SummonCreature(), summons, TYPE_BJARNGRIM, and urand().
Referenced by UpdateEscortAI().
RollStance()
void boss_bjarngrim::boss_bjarngrimAI::RollStance (uint8 stance, uint8 force = 0) inline
Definition at line 233 of file boss_bjarngrim.cpp.
         {
             if (urand(0, 1))
                 stance = (++stance == 4 ? 1 : stance);
             else
                 stance = (--stance == 0 ? 3 : stance);
             if (force)
                 stance = force;
             switch (stance)
             {
                 case STANCE_DEFENSIVE:
                     Talk(SAY_DEFENSIVE_STANCE);
                     me->CastSpell(me, SPELL_DEFENSIVE_STANCE, true);
                     me->CastSpell(me, SPELL_DEFENSIVE_AURA, true);
                     events.DelayEvents(20000, STANCE_BERSERKER);
                     events.DelayEvents(20000, STANCE_BATTLE);
                     SetEquipmentSlots(false, EQUIP_SWORD, EQUIP_SHIELD, EQUIP_NO_CHANGE);
                     break;
                 case STANCE_BERSERKER:
                     Talk(SAY_BERSERKER_STANCE);
                     me->CastSpell(me, SPELL_BERSERKER_STANCE, true);
                     me->CastSpell(me, SPELL_BERSERKER_AURA, true);
                     events.DelayEvents(20000, STANCE_DEFENSIVE);
                     events.DelayEvents(20000, STANCE_BATTLE);
                     SetEquipmentSlots(false, EQUIP_SWORD, EQUIP_SWORD, EQUIP_NO_CHANGE);
                     break;
                 case STANCE_BATTLE:
                     Talk(SAY_BATTLE_STANCE);
                     me->CastSpell(me, SPELL_BATTLE_STANCE, true);
                     me->CastSpell(me, SPELL_BATTLE_AURA, true);
                     events.DelayEvents(20000, STANCE_BERSERKER);
                     events.DelayEvents(20000, STANCE_DEFENSIVE);
                     SetEquipmentSlots(false, EQUIP_MACE, EQUIP_UNEQUIP, EQUIP_NO_CHANGE);
                     break;
             }
             m_uiStance = stance;
         }
References Unit::CastSpell(), EQUIP_MACE, EQUIP_NO_CHANGE, EQUIP_SHIELD, EQUIP_SWORD, EQUIP_UNEQUIP, m_uiStance, ScriptedAI::me, SAY_BATTLE_STANCE, SAY_BERSERKER_STANCE, SAY_DEFENSIVE_STANCE, ScriptedAI::SetEquipmentSlots(), SPELL_BATTLE_AURA, SPELL_BATTLE_STANCE, SPELL_BERSERKER_AURA, SPELL_BERSERKER_STANCE, SPELL_DEFENSIVE_AURA, SPELL_DEFENSIVE_STANCE, STANCE_BATTLE, STANCE_BERSERKER, STANCE_DEFENSIVE, CreatureAI::Talk(), and urand().
Referenced by Reset(), and UpdateEscortAI().
UpdateEscortAI()
void boss_bjarngrim::boss_bjarngrimAI::UpdateEscortAI (uint32 diff) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 291 of file boss_bjarngrim.cpp.
         {
             if (!me->IsInCombat())
                 return;
             // Return since we have no target
             if (!UpdateVictim())
             {
                 Reset();
                 return;
             }
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_BJARNGRIM_CHANGE_STANCE:
                     // roll new stance
                     RemoveStanceAura(m_uiStance);
                     RollStance(m_uiStance);
                     events.RepeatEvent(20000);
                     break;
                 case EVENT_BJARNGRIM_REFLECTION:
                     me->CastSpell(me, SPELL_BJARNGRIM_REFLETION, true);
                     events.RepeatEvent(8000 + rand() % 1000);
                     break;
                 case EVENT_BJARNGRIM_PUMMEL:
                     me->CastSpell(me->GetVictim(), SPELL_PUMMEL, false);
                     events.RepeatEvent(10000 + rand() % 1000);
                     break;
                 case EVENT_BJARNGRIM_KNOCK:
                     me->CastSpell(me, SPELL_KNOCK_AWAY, false);
                     events.RepeatEvent(20000 + rand() % 1000);
                     break;
                 case EVENT_BJARNGRIM_IRONFORM:
                     me->CastSpell(me, SPELL_IRONFORM, true);
                     events.RepeatEvent(18000 + rand() % 5000);
                     break;
                 case EVENT_BJARNGRIM_MORTAL_STRIKE:
                     me->CastSpell(me->GetVictim(), SPELL_MORTAL_STRIKE, false);
                     events.RepeatEvent(10000);
                     break;
                 case EVENT_BJARNGRIM_WHIRLWIND:
                     me->CastSpell(me, SPELL_WHIRLWIND, true);
                     events.RepeatEvent(25000);
                     break;
                 case EVENT_BJARNGRIM_INTERCEPT:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM))
                         me->CastSpell(target, SPELL_INTERCEPT, true);
                     events.RepeatEvent(30000);
                     break;
                 case EVENT_BJARNGRIM_CLEAVE:
                     me->CastSpell(me->GetVictim(), SPELL_CLEAVE, false);
                     events.RepeatEvent(25000);
                     break;
                 case EVENT_BJARNGRIM_SLAM:
                     me->CastSpell(me->GetVictim(), SPELL_SLAM, false);
                     events.RepeatEvent(10000 + rand() % 2000);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), EVENT_BJARNGRIM_CHANGE_STANCE, EVENT_BJARNGRIM_CLEAVE, EVENT_BJARNGRIM_INTERCEPT, EVENT_BJARNGRIM_IRONFORM, EVENT_BJARNGRIM_KNOCK, EVENT_BJARNGRIM_MORTAL_STRIKE, EVENT_BJARNGRIM_PUMMEL, EVENT_BJARNGRIM_REFLECTION, EVENT_BJARNGRIM_SLAM, EVENT_BJARNGRIM_WHIRLWIND, Unit::GetVictim(), Unit::HasUnitState(), Unit::IsInCombat(), m_uiStance, ScriptedAI::me, RemoveStanceAura(), Reset(), RollStance(), SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), SPELL_BJARNGRIM_REFLETION, SPELL_CLEAVE, SPELL_INTERCEPT, SPELL_IRONFORM, SPELL_KNOCK_AWAY, SPELL_MORTAL_STRIKE, SPELL_PUMMEL, SPELL_SLAM, SPELL_WHIRLWIND, UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
WaypointReached()
void boss_bjarngrim::boss_bjarngrimAI::WaypointReached (uint32 Point) inline override virtual
Implements npc_escortAI.
Definition at line 283 of file boss_bjarngrim.cpp.
         {
             if (Point == 1 || Point == 8)
                 me->CastSpell(me, SPELL_TEMPORARY_ELECTRICAL_CHARGE, true);
             else if (Point == 7 || Point == 14)
                 me->RemoveAura(SPELL_TEMPORARY_ELECTRICAL_CHARGE);
         }
References Unit::CastSpell(), ScriptedAI::me, Unit::RemoveAura(), and SPELL_TEMPORARY_ELECTRICAL_CHARGE.
Member Data Documentation
events
EventMap boss_bjarngrim::boss_bjarngrimAI::events
Definition at line 145 of file boss_bjarngrim.cpp.
m_pInstance
InstanceScript* boss_bjarngrim::boss_bjarngrimAI::m_pInstance
Definition at line 144 of file boss_bjarngrim.cpp.
Referenced by boss_bjarngrimAI(), EnterCombat(), JustDied(), and Reset().
m_uiStance
uint8 boss_bjarngrim::boss_bjarngrimAI::m_uiStance
Definition at line 147 of file boss_bjarngrim.cpp.
Referenced by RollStance(), and UpdateEscortAI().
summons
SummonList boss_bjarngrim::boss_bjarngrimAI::summons
Definition at line 146 of file boss_bjarngrim.cpp.
Referenced by Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/HallsOfLightning/boss_bjarngrim.cpp