Azerotcore-wotlk: ticket_commandscript Class Reference
ticket_commandscript Class Reference
Public Member Functions
ticket_commandscript ()
ChatCommandTable GetCommands () const override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Static Public Member Functions
static bool HandleGMTicketAssignToCommand (ChatHandler *handler, char const *args)
static bool HandleGMTicketCloseByIdCommand (ChatHandler *handler, char const *args)
static bool HandleGMTicketCommentCommand (ChatHandler *handler, char const *args)
static bool HandleGMTicketListClosedCommand (ChatHandler *handler, char const *)
static bool HandleGMTicketCompleteCommand (ChatHandler *handler, char const *args)
static bool HandleGMTicketDeleteByIdCommand (ChatHandler *handler, char const *args)
static bool HandleGMTicketEscalateCommand (ChatHandler *handler, char const *args)
static bool HandleGMTicketListEscalatedCommand (ChatHandler *handler, char const *)
static bool HandleGMTicketListCommand (ChatHandler *handler, char const *)
static bool HandleGMTicketListOnlineCommand (ChatHandler *handler, char const *)
static bool HandleGMTicketResetCommand (ChatHandler *handler, char const *)
static bool HandleToggleGMTicketSystem (ChatHandler *handler, char const *)
static bool HandleGMTicketUnAssignCommand (ChatHandler *handler, char const *args)
static bool HandleGMTicketGetByIdCommand (ChatHandler *handler, char const *args)
static bool HandleGMTicketGetByNameCommand (ChatHandler *handler, char const *args)
static bool _HandleGMTicketResponseAppendCommand (char const *args, bool newLine, ChatHandler *handler)
static bool HandleGMTicketResponseAppendCommand (ChatHandler *handler, char const *args)
static bool HandleGMTicketResponseAppendLnCommand (ChatHandler *handler, char const *args)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 41 of file cs_ticket.cpp.
Constructor & Destructor Documentation
ticket_commandscript()
ticket_commandscript::ticket_commandscript () inline
Definition at line 44 of file cs_ticket.cpp.
 : CommandScript("ticket_commandscript") { }
Member Function Documentation
_HandleGMTicketResponseAppendCommand()
static bool ticket_commandscript::_HandleGMTicketResponseAppendCommand (char const * args, bool newLine, ChatHandler * handler) inline static
Console excluded
Definition at line 488 of file cs_ticket.cpp.
     {
         if (!*args)
             return false;
         char* ticketIdStr = strtok((char*)args, " ");
         uint32 ticketId = atoi(ticketIdStr);
         char* response = strtok(nullptr, "\n");
         if (!response)
             return false;
         GmTicket* ticket = sTicketMgr->GetTicket(ticketId);
         if (!ticket || ticket->IsClosed())
         {
             handler->PSendSysMessage(LANG_COMMAND_TICKETNOTEXIST);
             return true;
         }
         // Cannot add response to ticket, assigned to someone else
         Player* player = handler->GetSession() ? handler->GetSession()->GetPlayer() : nullptr;
         if (player && ticket->IsAssignedNotTo(player->GetGUID()))
         {
             handler->PSendSysMessage(LANG_COMMAND_TICKETALREADYASSIGNED, ticket->GetId());
             return true;
         }
         CharacterDatabaseTransaction trans = CharacterDatabaseTransaction(nullptr);
         ticket->AppendResponse(response);
         if (newLine)
             ticket->AppendResponse("\n");
         ticket->SaveToDB(trans);
         return true;
     }
References GmTicket::AppendResponse(), Object::GetGUID(), GmTicket::GetId(), WorldSession::GetPlayer(), ChatHandler::GetSession(), GmTicket::IsAssignedNotTo(), GmTicket::IsClosed(), LANG_COMMAND_TICKETALREADYASSIGNED, LANG_COMMAND_TICKETNOTEXIST, ChatHandler::PSendSysMessage(), GmTicket::SaveToDB(), and sTicketMgr.
GetCommands()
ChatCommandTable ticket_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
Definition at line 46 of file cs_ticket.cpp.
     {
         static ChatCommandTable ticketResponseCommandTable =
         {
             { "append",         SEC_GAMEMASTER,      true,  &HandleGMTicketResponseAppendCommand,    "" },
             { "appendln",       SEC_GAMEMASTER,      true,  &HandleGMTicketResponseAppendLnCommand,  "" }
         };
         static ChatCommandTable ticketCommandTable =
         {
             { "assign",         SEC_GAMEMASTER,      true,  &HandleGMTicketAssignToCommand,          "" },
             { "close",          SEC_GAMEMASTER,      true,  &HandleGMTicketCloseByIdCommand,         "" },
             { "closedlist",     SEC_GAMEMASTER,      true,  &HandleGMTicketListClosedCommand,        "" },
             { "comment",        SEC_GAMEMASTER,      true,  &HandleGMTicketCommentCommand,           "" },
             { "complete",       SEC_GAMEMASTER,      true,  &HandleGMTicketCompleteCommand,          "" },
             { "delete",         SEC_ADMINISTRATOR,   true,  &HandleGMTicketDeleteByIdCommand,        "" },
             { "escalate",       SEC_GAMEMASTER,      true,  &HandleGMTicketEscalateCommand,          "" },
             { "escalatedlist",  SEC_GAMEMASTER,      true,  &HandleGMTicketListEscalatedCommand,     "" },
             { "list",           SEC_GAMEMASTER,      true,  &HandleGMTicketListCommand,              "" },
             { "onlinelist",     SEC_GAMEMASTER,      true,  &HandleGMTicketListOnlineCommand,        "" },
             { "reset",          SEC_CONSOLE,         true,  &HandleGMTicketResetCommand,             "" },
             { "response",       SEC_GAMEMASTER,      true,  nullptr,                                 "", ticketResponseCommandTable },
             { "togglesystem",   SEC_ADMINISTRATOR,   true,  &HandleToggleGMTicketSystem,             "" },
             { "unassign",       SEC_GAMEMASTER,      true,  &HandleGMTicketUnAssignCommand,          "" },
             { "viewid",         SEC_GAMEMASTER,      true,  &HandleGMTicketGetByIdCommand,           "" },
             { "viewname",       SEC_GAMEMASTER,      true,  &HandleGMTicketGetByNameCommand,         "" }
         };
         static ChatCommandTable commandTable =
         {
             { "ticket",         SEC_GAMEMASTER,      false, nullptr,                                 "", ticketCommandTable }
         };
         return commandTable;
     }
References SEC_ADMINISTRATOR, SEC_CONSOLE, and SEC_GAMEMASTER.
HandleGMTicketAssignToCommand()
static bool ticket_commandscript::HandleGMTicketAssignToCommand (ChatHandler * handler, char const * args) inline static
Console can override though
Definition at line 79 of file cs_ticket.cpp.
     {
         if (!*args)
             return false;
         char* ticketIdStr = strtok((char*)args, " ");
         uint32 ticketId = atoi(ticketIdStr);
         char* targetStr = strtok(nullptr, " ");
         if (!targetStr)
             return false;
         std::string target(targetStr);
         if (!normalizePlayerName(target))
             return false;
         GmTicket* ticket = sTicketMgr->GetTicket(ticketId);
         if (!ticket || ticket->IsClosed())
         {
             handler->SendSysMessage(LANG_COMMAND_TICKETNOTEXIST);
             return true;
         }
         // Get target information
         ObjectGuid targetGuid = sObjectMgr->GetPlayerGUIDByName(target.c_str());
         uint32 targetAccountId = sObjectMgr->GetPlayerAccountIdByGUID(targetGuid.GetCounter());
         uint32 targetGmLevel = AccountMgr::GetSecurity(targetAccountId, realm.Id.Realm);
         // Target must exist and have administrative rights
         if (!targetGuid || AccountMgr::IsPlayerAccount(targetGmLevel))
         {
             handler->SendSysMessage(LANG_COMMAND_TICKETASSIGNERROR_A);
             return true;
         }
         // If already assigned, leave
         if (ticket->IsAssignedTo(targetGuid))
         {
             handler->PSendSysMessage(LANG_COMMAND_TICKETASSIGNERROR_B, ticket->GetId());
             return true;
         }
         // If assigned to different player other than current, leave
         Player* player = handler->GetSession() ? handler->GetSession()->GetPlayer() : nullptr;
         if (player && ticket->IsAssignedNotTo(player->GetGUID()))
         {
             handler->PSendSysMessage(LANG_COMMAND_TICKETALREADYASSIGNED, ticket->GetId(), target.c_str());
             return true;
         }
         // Assign ticket
         CharacterDatabaseTransaction trans = CharacterDatabaseTransaction(nullptr);
         ticket->SetAssignedTo(targetGuid, AccountMgr::IsAdminAccount(targetGmLevel));
         ticket->SaveToDB(trans);
         sTicketMgr->UpdateLastChange();
         std::string msg = ticket->FormatMessageString(*handler, nullptr, target.c_str(), nullptr, nullptr);
         handler->SendGlobalGMSysMessage(msg.c_str());
         return true;
     }
References GmTicket::FormatMessageString(), ObjectGuid::GetCounter(), Object::GetGUID(), GmTicket::GetId(), WorldSession::GetPlayer(), AccountMgr::GetSecurity(), ChatHandler::GetSession(), Realm::Id, AccountMgr::IsAdminAccount(), GmTicket::IsAssignedNotTo(), GmTicket::IsAssignedTo(), GmTicket::IsClosed(), AccountMgr::IsPlayerAccount(), LANG_COMMAND_TICKETALREADYASSIGNED, LANG_COMMAND_TICKETASSIGNERROR_A, LANG_COMMAND_TICKETASSIGNERROR_B, LANG_COMMAND_TICKETNOTEXIST, normalizePlayerName(), ChatHandler::PSendSysMessage(), realm, RealmHandle::Realm, GmTicket::SaveToDB(), ChatHandler::SendGlobalGMSysMessage(), ChatHandler::SendSysMessage(), GmTicket::SetAssignedTo(), sObjectMgr, and sTicketMgr.
HandleGMTicketCloseByIdCommand()
static bool ticket_commandscript::HandleGMTicketCloseByIdCommand (ChatHandler * handler, char const * args) inline static
Definition at line 141 of file cs_ticket.cpp.
     {
         if (!*args)
             return false;
         uint32 ticketId = atoi(args);
         GmTicket* ticket = sTicketMgr->GetTicket(ticketId);
         if (!ticket || ticket->IsClosed() || ticket->IsCompleted())
         {
             handler->SendSysMessage(LANG_COMMAND_TICKETNOTEXIST);
             return true;
         }
         // Ticket should be assigned to the player who tries to close it.
         // Console can override though
         Player* player = handler->GetSession() ? handler->GetSession()->GetPlayer() : nullptr;
         if (player && ticket->IsAssignedNotTo(player->GetGUID()))
         {
             handler->PSendSysMessage(LANG_COMMAND_TICKETCANNOTCLOSE, ticket->GetId());
             return true;
         }
         sTicketMgr->ResolveAndCloseTicket(ticket->GetId(), player ? player->GetGUID() : ObjectGuid::Empty);
         sTicketMgr->UpdateLastChange();
         std::string msg = ticket->FormatMessageString(*handler, player ? player->GetName().c_str() : "Console", nullptr, nullptr, nullptr);
         handler->SendGlobalGMSysMessage(msg.c_str());
         // Inform player, who submitted this ticket, that it is closed
         if (Player* submitter = ticket->GetPlayer())
         {
             WorldPacket data(SMSG_GMTICKET_DELETETICKET, 4);
             data << uint32(GMTICKET_RESPONSE_TICKET_DELETED);
             submitter->GetSession()->SendPacket(&data);
             ChatHandler(submitter->GetSession()).SendSysMessage(LANG_TICKET_CLOSED);
         }
         return true;
     }
References ObjectGuid::Empty, GmTicket::FormatMessageString(), Object::GetGUID(), GmTicket::GetId(), WorldObject::GetName(), WorldSession::GetPlayer(), GmTicket::GetPlayer(), ChatHandler::GetSession(), GMTICKET_RESPONSE_TICKET_DELETED, GmTicket::IsAssignedNotTo(), GmTicket::IsClosed(), GmTicket::IsCompleted(), LANG_COMMAND_TICKETCANNOTCLOSE, LANG_COMMAND_TICKETNOTEXIST, LANG_TICKET_CLOSED, ChatHandler::PSendSysMessage(), ChatHandler::SendGlobalGMSysMessage(), ChatHandler::SendSysMessage(), SMSG_GMTICKET_DELETETICKET, and sTicketMgr.
HandleGMTicketCommentCommand()
static bool ticket_commandscript::HandleGMTicketCommentCommand (ChatHandler * handler, char const * args) inline static
Definition at line 180 of file cs_ticket.cpp.
     {
         if (!*args)
             return false;
         char* ticketIdStr = strtok((char*)args, " ");
         uint32 ticketId = atoi(ticketIdStr);
         char* comment = strtok(nullptr, "\n");
         if (!comment)
             return false;
         GmTicket* ticket = sTicketMgr->GetTicket(ticketId);
         if (!ticket)
         {
             handler->PSendSysMessage(LANG_COMMAND_TICKETNOTEXIST);
             return true;
         }
         // Cannot comment ticket assigned to someone else (unless done from the Console)
         Player* player = handler->GetSession() ? handler->GetSession()->GetPlayer() : nullptr;
         if (player && ticket->IsAssignedNotTo(player->GetGUID()))
         {
             handler->PSendSysMessage(LANG_COMMAND_TICKETALREADYASSIGNED, ticket->GetId());
             return true;
         }
         CharacterDatabaseTransaction trans = CharacterDatabaseTransaction(nullptr);
         ticket->SetComment(comment);
         ticket->SaveToDB(trans);
         sTicketMgr->UpdateLastChange();
         std::string const assignedName = ticket->GetAssignedToName();
         std::string msg = ticket->FormatMessageString(*handler, assignedName.empty() ? nullptr : assignedName.c_str(), nullptr, nullptr, nullptr);
         msg += handler->PGetParseString(LANG_COMMAND_TICKETLISTADDCOMMENT, player ? player->GetName().c_str() : "Console", comment);
         handler->SendGlobalGMSysMessage(msg.c_str());
         return true;
     }
References GmTicket::FormatMessageString(), GmTicket::GetAssignedToName(), Object::GetGUID(), GmTicket::GetId(), WorldObject::GetName(), WorldSession::GetPlayer(), ChatHandler::GetSession(), GmTicket::IsAssignedNotTo(), LANG_COMMAND_TICKETALREADYASSIGNED, LANG_COMMAND_TICKETLISTADDCOMMENT, LANG_COMMAND_TICKETNOTEXIST, ChatHandler::PGetParseString(), ChatHandler::PSendSysMessage(), GmTicket::SaveToDB(), ChatHandler::SendGlobalGMSysMessage(), GmTicket::SetComment(), and sTicketMgr.
HandleGMTicketCompleteCommand()
static bool ticket_commandscript::HandleGMTicketCompleteCommand (ChatHandler * handler, char const * args) inline static
Definition at line 227 of file cs_ticket.cpp.
     {
         if (!*args)
             return false;
         char* ticketIdStr = strtok((char*)args, " ");
         uint32 ticketId = atoi(ticketIdStr);
         GmTicket* ticket = sTicketMgr->GetTicket(ticketId);
         if (!ticket || ticket->IsClosed() || ticket->IsCompleted())
         {
             handler->SendSysMessage(LANG_COMMAND_TICKETNOTEXIST);
             return true;
         }
         // Check if handler is not assignee in which case return
         Player* player = handler->GetSession() ? handler->GetSession()->GetPlayer() : nullptr;
         if (player && ticket->IsAssignedNotTo(player->GetGUID()))
         {
             handler->PSendSysMessage(LANG_COMMAND_TICKETALREADYASSIGNED, ticket->GetId());
             return true;
         }
         char* response = strtok(nullptr, "\n");
         if (response)
             ticket->AppendResponse(response);
         if (Player* player2 = ticket->GetPlayer())
         {
             ticket->SendResponse(player2->GetSession());
             ChatHandler(player2->GetSession()).SendSysMessage(LANG_TICKET_COMPLETED);
         }
         Player* gm = handler->GetSession() ? handler->GetSession()->GetPlayer() : nullptr;
         CharacterDatabaseTransaction trans = CharacterDatabaseTransaction(nullptr);
         ticket->SetCompleted();
         ticket->SetResolvedBy(gm ? gm->GetGUID() : ObjectGuid::Empty);
         ticket->SaveToDB(trans);
         std::string msg = ticket->FormatMessageString(*handler, nullptr, nullptr, nullptr, nullptr);
         msg += handler->PGetParseString(LANG_COMMAND_TICKETCOMPLETED, gm ? gm->GetName().c_str() : "Console");
         handler->SendGlobalGMSysMessage(msg.c_str());
         sTicketMgr->UpdateLastChange();
         return true;
     }
References GmTicket::AppendResponse(), ObjectGuid::Empty, GmTicket::FormatMessageString(), Object::GetGUID(), GmTicket::GetId(), WorldObject::GetName(), WorldSession::GetPlayer(), GmTicket::GetPlayer(), ChatHandler::GetSession(), GmTicket::IsAssignedNotTo(), GmTicket::IsClosed(), GmTicket::IsCompleted(), LANG_COMMAND_TICKETALREADYASSIGNED, LANG_COMMAND_TICKETCOMPLETED, LANG_COMMAND_TICKETNOTEXIST, LANG_TICKET_COMPLETED, ChatHandler::PGetParseString(), ChatHandler::PSendSysMessage(), GmTicket::SaveToDB(), ChatHandler::SendGlobalGMSysMessage(), GmTicket::SendResponse(), ChatHandler::SendSysMessage(), GmTicket::SetCompleted(), GmTicket::SetResolvedBy(), and sTicketMgr.
HandleGMTicketDeleteByIdCommand()
static bool ticket_commandscript::HandleGMTicketDeleteByIdCommand (ChatHandler * handler, char const * args) inline static
Definition at line 275 of file cs_ticket.cpp.
     {
         if (!*args)
             return false;
         uint32 ticketId = atoi(args);
         GmTicket* ticket = sTicketMgr->GetTicket(ticketId);
         if (!ticket)
         {
             handler->SendSysMessage(LANG_COMMAND_TICKETNOTEXIST);
             return true;
         }
         if (!ticket->IsClosed())
         {
             handler->SendSysMessage(LANG_COMMAND_TICKETCLOSEFIRST);
             return true;
         }
         std::string msg = ticket->FormatMessageString(*handler, nullptr, nullptr, nullptr, handler->GetSession() ? handler->GetSession()->GetPlayer()->GetName().c_str() : "Console");
         handler->SendGlobalGMSysMessage(msg.c_str());
         sTicketMgr->RemoveTicket(ticket->GetId());
         sTicketMgr->UpdateLastChange();
         if (Player* player = ticket->GetPlayer())
         {
             // Force abandon ticket
             WorldPacket data(SMSG_GMTICKET_DELETETICKET, 4);
             data << uint32(GMTICKET_RESPONSE_TICKET_DELETED);
             player->GetSession()->SendPacket(&data);
         }
         return true;
     }
References GmTicket::FormatMessageString(), GmTicket::GetId(), WorldObject::GetName(), WorldSession::GetPlayer(), GmTicket::GetPlayer(), ChatHandler::GetSession(), GMTICKET_RESPONSE_TICKET_DELETED, GmTicket::IsClosed(), LANG_COMMAND_TICKETCLOSEFIRST, LANG_COMMAND_TICKETNOTEXIST, ChatHandler::SendGlobalGMSysMessage(), ChatHandler::SendSysMessage(), SMSG_GMTICKET_DELETETICKET, and sTicketMgr.
HandleGMTicketEscalateCommand()
static bool ticket_commandscript::HandleGMTicketEscalateCommand (ChatHandler * handler, char const * args) inline static
Definition at line 311 of file cs_ticket.cpp.
     {
         if (!*args)
             return false;
         uint32 ticketId = atoi(args);
         GmTicket* ticket = sTicketMgr->GetTicket(ticketId);
         if (!ticket || ticket->IsClosed() || ticket->IsCompleted() || ticket->GetEscalatedStatus() != TICKET_UNASSIGNED)
         {
             handler->SendSysMessage(LANG_COMMAND_TICKETNOTEXIST);
             return true;
         }
         ticket->SetEscalatedStatus(TICKET_IN_ESCALATION_QUEUE);
         if (Player* player = ticket->GetPlayer())
             sTicketMgr->SendTicket(player->GetSession(), ticket);
         sTicketMgr->UpdateLastChange();
         return true;
     }
References GmTicket::GetEscalatedStatus(), GmTicket::GetPlayer(), GmTicket::IsClosed(), GmTicket::IsCompleted(), LANG_COMMAND_TICKETNOTEXIST, ChatHandler::SendSysMessage(), GmTicket::SetEscalatedStatus(), sTicketMgr, TICKET_IN_ESCALATION_QUEUE, and TICKET_UNASSIGNED.
HandleGMTicketGetByIdCommand()
static bool ticket_commandscript::HandleGMTicketGetByIdCommand (ChatHandler * handler, char const * args) inline static
Definition at line 428 of file cs_ticket.cpp.
     {
         if (!*args)
             return false;
         uint32 ticketId = atoi(args);
         GmTicket* ticket = sTicketMgr->GetTicket(ticketId);
         if (!ticket || ticket->IsClosed() || ticket->IsCompleted())
         {
             handler->SendSysMessage(LANG_COMMAND_TICKETNOTEXIST);
             return true;
         }
         CharacterDatabaseTransaction trans = CharacterDatabaseTransaction(nullptr);
         ticket->SetViewed();
         ticket->SaveToDB(trans);
         handler->SendSysMessage(ticket->FormatMessageString(*handler, true).c_str());
         return true;
     }
References GmTicket::FormatMessageString(), GmTicket::IsClosed(), GmTicket::IsCompleted(), LANG_COMMAND_TICKETNOTEXIST, GmTicket::SaveToDB(), ChatHandler::SendSysMessage(), GmTicket::SetViewed(), and sTicketMgr.
HandleGMTicketGetByNameCommand()
static bool ticket_commandscript::HandleGMTicketGetByNameCommand (ChatHandler * handler, char const * args) inline static
Definition at line 449 of file cs_ticket.cpp.
     {
         if (!*args)
             return false;
         std::string name(args);
         if (!normalizePlayerName(name))
             return false;
         // Detect target's GUID
         ObjectGuid guid;
         if (Player* player = ObjectAccessor::FindPlayerByName(name, false))
             guid = player->GetGUID();
         else
             guid = sObjectMgr->GetPlayerGUIDByName(name);
         // Target must exist
         if (!guid)
         {
             handler->SendSysMessage(LANG_NO_PLAYERS_FOUND);
             return true;
         }
         // Ticket must exist
         GmTicket* ticket = sTicketMgr->GetTicketByPlayer(guid);
         if (!ticket)
         {
             handler->SendSysMessage(LANG_COMMAND_TICKETNOTEXIST);
             return true;
         }
         CharacterDatabaseTransaction trans = CharacterDatabaseTransaction(nullptr);
         ticket->SetViewed();
         ticket->SaveToDB(trans);
         handler->SendSysMessage(ticket->FormatMessageString(*handler, true).c_str());
         return true;
     }
References ObjectAccessor::FindPlayerByName(), GmTicket::FormatMessageString(), LANG_COMMAND_TICKETNOTEXIST, LANG_NO_PLAYERS_FOUND, normalizePlayerName(), GmTicket::SaveToDB(), ChatHandler::SendSysMessage(), GmTicket::SetViewed(), sObjectMgr, and sTicketMgr.
HandleGMTicketListClosedCommand()
static bool ticket_commandscript::HandleGMTicketListClosedCommand (ChatHandler * handler, char const *) inline static
Definition at line 221 of file cs_ticket.cpp.
     {
         sTicketMgr->ShowClosedList(*handler);
         return true;
     }
References sTicketMgr.
HandleGMTicketListCommand()
static bool ticket_commandscript::HandleGMTicketListCommand (ChatHandler * handler, char const *) inline static
Definition at line 339 of file cs_ticket.cpp.
     {
         sTicketMgr->ShowList(*handler, false);
         return true;
     }
References sTicketMgr.
HandleGMTicketListEscalatedCommand()
static bool ticket_commandscript::HandleGMTicketListEscalatedCommand (ChatHandler * handler, char const *) inline static
Definition at line 333 of file cs_ticket.cpp.
     {
         sTicketMgr->ShowEscalatedList(*handler);
         return true;
     }
References sTicketMgr.
HandleGMTicketListOnlineCommand()
static bool ticket_commandscript::HandleGMTicketListOnlineCommand (ChatHandler * handler, char const *) inline static
Definition at line 345 of file cs_ticket.cpp.
     {
         sTicketMgr->ShowList(*handler, true);
         return true;
     }
References sTicketMgr.
HandleGMTicketResetCommand()
static bool ticket_commandscript::HandleGMTicketResetCommand (ChatHandler * handler, char const *) inline static
Definition at line 351 of file cs_ticket.cpp.
     {
         if (sTicketMgr->GetOpenTicketCount())
         {
             handler->SendSysMessage(LANG_COMMAND_TICKETPENDING);
             return true;
         }
         else
         {
             sTicketMgr->ResetTickets();
             handler->SendSysMessage(LANG_COMMAND_TICKETRESET);
         }
         return true;
     }
References LANG_COMMAND_TICKETPENDING, LANG_COMMAND_TICKETRESET, ChatHandler::SendSysMessage(), and sTicketMgr.
HandleGMTicketResponseAppendCommand()
static bool ticket_commandscript::HandleGMTicketResponseAppendCommand (ChatHandler * handler, char const * args) inline static
Definition at line 525 of file cs_ticket.cpp.
     {
         return _HandleGMTicketResponseAppendCommand(args, false, handler);
     }
HandleGMTicketResponseAppendLnCommand()
static bool ticket_commandscript::HandleGMTicketResponseAppendLnCommand (ChatHandler * handler, char const * args) inline static
Definition at line 530 of file cs_ticket.cpp.
     {
         return _HandleGMTicketResponseAppendCommand(args, true, handler);
     }
HandleGMTicketUnAssignCommand()
static bool ticket_commandscript::HandleGMTicketUnAssignCommand (ChatHandler * handler, char const * args) inline static
If no m_session present it means we're issuing this command from the console
Definition at line 375 of file cs_ticket.cpp.
     {
         if (!*args)
             return false;
         uint32 ticketId = atoi(args);
         GmTicket* ticket = sTicketMgr->GetTicket(ticketId);
         if (!ticket || ticket->IsClosed())
         {
             handler->SendSysMessage(LANG_COMMAND_TICKETNOTEXIST);
             return true;
         }
         // Ticket must be assigned
         if (!ticket->IsAssigned())
         {
             handler->PSendSysMessage(LANG_COMMAND_TICKETNOTASSIGNED, ticket->GetId());
             return true;
         }
         // Get security level of player, whom this ticket is assigned to
         uint32 security = SEC_PLAYER;
         Player* assignedPlayer = ticket->GetAssignedPlayer();
         if (assignedPlayer)
             security = assignedPlayer->GetSession()->GetSecurity();
         else
         {
             ObjectGuid guid = ticket->GetAssignedToGUID();
             uint32 accountId = sObjectMgr->GetPlayerAccountIdByGUID(guid.GetCounter());
             security = AccountMgr::GetSecurity(accountId, realm.Id.Realm);
         }
         // Check security
         uint32 mySecurity = handler->GetSession() ? handler->GetSession()->GetSecurity() : SEC_CONSOLE;
         if (security > mySecurity)
         {
             handler->SendSysMessage(LANG_COMMAND_TICKETUNASSIGNSECURITY);
             return true;
         }
         std::string assignedTo = ticket->GetAssignedToName(); // copy assignedto name because we need it after the ticket has been unnassigned
         CharacterDatabaseTransaction trans = CharacterDatabaseTransaction(nullptr);
         ticket->SetUnassigned();
         ticket->SaveToDB(trans);
         sTicketMgr->UpdateLastChange();
         std::string msg = ticket->FormatMessageString(*handler, nullptr, assignedTo.c_str(),
                           handler->GetSession() ? handler->GetSession()->GetPlayer()->GetName().c_str() : "Console", nullptr);
         handler->SendGlobalGMSysMessage(msg.c_str());
         return true;
     }
References GmTicket::FormatMessageString(), GmTicket::GetAssignedPlayer(), GmTicket::GetAssignedToGUID(), GmTicket::GetAssignedToName(), ObjectGuid::GetCounter(), GmTicket::GetId(), WorldObject::GetName(), WorldSession::GetPlayer(), WorldSession::GetSecurity(), AccountMgr::GetSecurity(), ChatHandler::GetSession(), Player::GetSession(), Realm::Id, GmTicket::IsAssigned(), GmTicket::IsClosed(), LANG_COMMAND_TICKETNOTASSIGNED, LANG_COMMAND_TICKETNOTEXIST, LANG_COMMAND_TICKETUNASSIGNSECURITY, ChatHandler::PSendSysMessage(), realm, RealmHandle::Realm, GmTicket::SaveToDB(), SEC_CONSOLE, SEC_PLAYER, ChatHandler::SendGlobalGMSysMessage(), ChatHandler::SendSysMessage(), GmTicket::SetUnassigned(), sObjectMgr, and sTicketMgr.
HandleToggleGMTicketSystem()
static bool ticket_commandscript::HandleToggleGMTicketSystem (ChatHandler * handler, char const *) inline static
Definition at line 367 of file cs_ticket.cpp.
     {
         bool status = !sTicketMgr->GetStatus();
         sTicketMgr->SetStatus(status);
         handler->PSendSysMessage(status ? LANG_ALLOW_TICKETS : LANG_DISALLOW_TICKETS);
         return true;
     }
References LANG_ALLOW_TICKETS, LANG_DISALLOW_TICKETS, ChatHandler::PSendSysMessage(), and sTicketMgr.
The documentation for this class was generated from the following file:
src/server/scripts/Commands/cs_ticket.cpp