Azerotcore-wotlk: at_zulgurub_entrance_speech Class Reference
at_zulgurub_entrance_speech Class Reference
Public Member Functions
at_zulgurub_entrance_speech ()
bool _OnTrigger (Player *player, const AreaTrigger *) override
Public Member Functions inherited from OnlyOnceAreaTriggerScript
bool OnTrigger (Player *, AreaTrigger const *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from OnlyOnceAreaTriggerScript
void ResetAreaTriggerDone (InstanceScript *, uint32)
void ResetAreaTriggerDone (Player const *, AreaTrigger const *)
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 179 of file boss_hakkar.cpp.
Constructor & Destructor Documentation
at_zulgurub_entrance_speech()
at_zulgurub_entrance_speech::at_zulgurub_entrance_speech () inline
Definition at line 182 of file boss_hakkar.cpp.
 : OnlyOnceAreaTriggerScript("at_zulgurub_entrance_speech") {}
Member Function Documentation
_OnTrigger()
bool at_zulgurub_entrance_speech::_OnTrigger (Player * player, const AreaTrigger *) inline override virtual
Implements OnlyOnceAreaTriggerScript.
Definition at line 184 of file boss_hakkar.cpp.
     {
         if (InstanceScript* instance = player->GetInstanceScript())
         {
             // Instance map's enormous, Hakkar's GRID is not loaded by the time players enter.
             // Without this, the creature never says anything, because it doesn't load in time.
             player->GetMap()->LoadGrid(-11783.99f, -1655.27f);
             if (Creature* hakkar = ObjectAccessor::GetCreature(*player, instance->GetGuidData(DATA_HAKKAR)))
             {
                 hakkar->setActive(true);
                 if (hakkar->GetAI())
                 {
                     hakkar->AI()->Talk(SAY_PROTECT_ALTAR);
                 }
             }
             return false;
         }
         return false;
     }
References DATA_HAKKAR, ObjectAccessor::GetCreature(), WorldObject::GetInstanceScript(), WorldObject::GetMap(), Map::LoadGrid(), and SAY_PROTECT_ALTAR.
The documentation for this class was generated from the following file:
src/server/scripts/EasternKingdoms/ZulGurub/boss_hakkar.cpp