Azerotcore-wotlk: npc_anubarak_spike::npc_anubarak_spikeAI Struct Reference
npc_anubarak_spike::npc_anubarak_spikeAI Struct Reference
Public Member Functions
npc_anubarak_spikeAI (Creature *pCreature)
void DoAction (int32 param) override
void SelectNewTarget (bool next)
void Reset () override
void UpdateAI (uint32 diff) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
ObjectGuid TargetGUID
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 733 of file boss_anubarak_trial.cpp.
Constructor & Destructor Documentation
npc_anubarak_spikeAI()
npc_anubarak_spike::npc_anubarak_spikeAI::npc_anubarak_spikeAI (Creature * pCreature) inline
Definition at line 735 of file boss_anubarak_trial.cpp.
                                                   : ScriptedAI(pCreature)
         {
             me->SetReactState(REACT_PASSIVE);
             me->SetCorpseDelay(0);
         }
References ScriptedAI::me, REACT_PASSIVE, Creature::SetCorpseDelay(), and Creature::SetReactState().
Member Function Documentation
DamageTaken()
void npc_anubarak_spike::npc_anubarak_spikeAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 825 of file boss_anubarak_trial.cpp.
         {
             damage = 0;
         }
DoAction()
void npc_anubarak_spike::npc_anubarak_spikeAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 744 of file boss_anubarak_trial.cpp.
         {
             if( param == -1 )
             {
                 if( Unit* target = ObjectAccessor::GetPlayer(*me, TargetGUID) )
                     target->RemoveAura(SPELL_MARK);
                 TargetGUID.Clear();
                 me->RemoveAllAuras();
                 me->GetMotionMaster()->MoveIdle();
                 events.Reset();
                 events.RescheduleEvent(3, 4000);
             }
         }
References ObjectGuid::Clear(), Unit::GetMotionMaster(), ObjectAccessor::GetPlayer(), ScriptedAI::me, MotionMaster::MoveIdle(), Unit::RemoveAllAuras(), SPELL_MARK, and TargetGUID.
Reset()
void npc_anubarak_spike::npc_anubarak_spikeAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 787 of file boss_anubarak_trial.cpp.
         {
             SelectNewTarget(false);
         }
References SelectNewTarget().
Referenced by UpdateAI().
SelectNewTarget()
void npc_anubarak_spike::npc_anubarak_spikeAI::SelectNewTarget (bool next) inline
Definition at line 758 of file boss_anubarak_trial.cpp.
         {
             if (TargetGUID)
                 if( Unit* target = ObjectAccessor::GetPlayer(*me, TargetGUID) )
                     target->RemoveAura(SPELL_MARK);
             TargetGUID.Clear();
             if (!next)
             {
                 events.Reset();
                 me->RemoveAllAuras();
             }
             DoZoneInCombat();
             DoResetThreat();
             if( Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 250.0f, true) )
             {
                 if (!next)
                 {
                     me->CastSpell(me, SPELL_SPIKE_SPEED1, true);
                     me->CastSpell(me, SPELL_SPIKE_TRAIL, true);
                     events.RescheduleEvent(1, 7000);
                 }
                 TargetGUID = target->GetGUID();
                 me->CastSpell(target, SPELL_MARK, true);
                 Talk(EMOTE_SPIKE, target);
                 AttackStart(target);
                 me->GetMotionMaster()->MoveChase(target);
             }
         }
References ScriptedAI::AttackStart(), Unit::CastSpell(), ObjectGuid::Clear(), ScriptedAI::DoResetThreat(), CreatureAI::DoZoneInCombat(), EMOTE_SPIKE, Unit::GetMotionMaster(), ObjectAccessor::GetPlayer(), ScriptedAI::me, MotionMaster::MoveChase(), Unit::RemoveAllAuras(), SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), SPELL_MARK, SPELL_SPIKE_SPEED1, SPELL_SPIKE_TRAIL, CreatureAI::Talk(), and TargetGUID.
Referenced by Reset(), and UpdateAI().
UpdateAI()
void npc_anubarak_spike::npc_anubarak_spikeAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 792 of file boss_anubarak_trial.cpp.
         {
             if( TargetGUID )
             {
                 Unit* target = ObjectAccessor::GetPlayer(*me, TargetGUID);
                 if( !target || !target->HasAura(SPELL_MARK) || !me->IsValidAttackTarget(target) || me->GetMotionMaster()->GetCurrentMovementGeneratorType() != CHASE_MOTION_TYPE || !me->HasUnitState(UNIT_STATE_CHASE_MOVE) )
                 {
                     SelectNewTarget(true);
                     return;
                 }
             }
             events.Update(diff);
             switch( events.ExecuteEvent() )
             {
                 case 0:
                     break;
                 case 1:
                     me->CastSpell(me, SPELL_SPIKE_SPEED2, true);
                     events.RescheduleEvent(2, 7000);
                     break;
                 case 2:
                     me->CastSpell(me, SPELL_SPIKE_SPEED3, true);
                     break;
                 case 3:
                     Reset();
                     break;
             }
         }
References Unit::CastSpell(), CHASE_MOTION_TYPE, MotionMaster::GetCurrentMovementGeneratorType(), Unit::GetMotionMaster(), ObjectAccessor::GetPlayer(), Unit::HasAura(), Unit::HasUnitState(), Unit::IsValidAttackTarget(), ScriptedAI::me, Reset(), SelectNewTarget(), SPELL_MARK, SPELL_SPIKE_SPEED2, SPELL_SPIKE_SPEED3, TargetGUID, and UNIT_STATE_CHASE_MOVE.
Member Data Documentation
events
EventMap npc_anubarak_spike::npc_anubarak_spikeAI::events
Definition at line 741 of file boss_anubarak_trial.cpp.
TargetGUID
ObjectGuid npc_anubarak_spike::npc_anubarak_spikeAI::TargetGUID
Definition at line 742 of file boss_anubarak_trial.cpp.
Referenced by DoAction(), SelectNewTarget(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_anubarak_trial.cpp