Azerotcore-wotlk: AvgDiffTracker Class Reference
AvgDiffTracker Class Reference
#include <AvgDiffTracker.h>
Public Member Functions
AvgDiffTracker ()
uint32 getAverage ()
uint32 getTimeWeightedAverage ()
uint32 getMax ()
void Update (uint32 diff)
Private Attributes
uint32 tab [AVG_DIFF_COUNT]
uint32 total
uint32 index
uint32 max [2]
uint32 average
Detailed Description
Definition at line 26 of file AvgDiffTracker.h.
Constructor & Destructor Documentation
AvgDiffTracker()
AvgDiffTracker::AvgDiffTracker () inline
Definition at line 29 of file AvgDiffTracker.h.
 : total(0), index(0), average(0) { memset(&tab, 0, sizeof(tab)); max[0] = 0; max[1] = 0; }
References max, memset, and tab.
Member Function Documentation
getAverage()
uint32 AvgDiffTracker::getAverage () inline
Definition at line 31 of file AvgDiffTracker.h.
     {
         return average;
     }
References average.
Referenced by AuctionHouseObject::BuildListAuctionItems(), server_commandscript::HandleServerInfoCommand(), and World::Update().
getMax()
uint32 AvgDiffTracker::getMax () inline
Definition at line 50 of file AvgDiffTracker.h.
     {
         return max[0] > max[1] ? max[0] : max[1];
     }
References max.
Referenced by server_commandscript::HandleServerInfoCommand().
getTimeWeightedAverage()
uint32 AvgDiffTracker::getTimeWeightedAverage () inline
Definition at line 36 of file AvgDiffTracker.h.
     {
         if (tab[AVG_DIFF_COUNT - 1] == 0)
             return 0;
         uint32 sum = 0, weightsum = 0;
         for (uint32 i = 0; i < AVG_DIFF_COUNT; ++i)
         {
             sum += tab[i] * tab[i];
             weightsum += tab[i];
         }
         return sum / weightsum;
     }
References AVG_DIFF_COUNT, and tab.
Referenced by server_commandscript::HandleServerInfoCommand().
Update()
void AvgDiffTracker::Update (uint32 diff) inline
Definition at line 55 of file AvgDiffTracker.h.
     {
         if (diff < 1)
             diff = 1;
         total -= tab[index];
         total += diff;
         tab[index] = diff;
         if (diff > max[0])
             max[0] = diff;
         if (++index >= AVG_DIFF_COUNT)
         {
             index = 0;
             max[1] = max[0];
             max[0] = 0;
         }
         if (tab[AVG_DIFF_COUNT - 1])
             average = total / AVG_DIFF_COUNT;
         else if (index)
             average = total / index;
         else
             average = 0;
     }
References average, AVG_DIFF_COUNT, diff(), index, max, tab, and total.
Referenced by LFGUpdateRequest::call(), MapMgr::Update(), and WorldUpdateLoop().
Member Data Documentation
average
uint32 AvgDiffTracker::average private
Definition at line 84 of file AvgDiffTracker.h.
Referenced by getAverage(), and Update().
index
uint32 AvgDiffTracker::index private
Definition at line 82 of file AvgDiffTracker.h.
Referenced by Update().
max
uint32 AvgDiffTracker::max[2] private
Definition at line 83 of file AvgDiffTracker.h.
Referenced by AvgDiffTracker(), getMax(), and Update().
tab
uint32 AvgDiffTracker::tab[AVG_DIFF_COUNT] private
Definition at line 80 of file AvgDiffTracker.h.
Referenced by AvgDiffTracker(), getTimeWeightedAverage(), and Update().
total
uint32 AvgDiffTracker::total private
Definition at line 81 of file AvgDiffTracker.h.
Referenced by Update().
The documentation for this class was generated from the following file:
src/server/game/Misc/AvgDiffTracker.h