Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/sz.h File Reference
sz.h File Reference
#include "jemalloc/internal/bit_util.h"
#include "jemalloc/internal/pages.h"
#include "jemalloc/internal/sc.h"
#include "jemalloc/internal/util.h"
Functions
void sz_boot (const sc_data_t *sc_data)
JEMALLOC_ALWAYS_INLINE pszind_t sz_psz2ind (size_t psz)
static size_t sz_pind2sz_compute (pszind_t pind)
static size_t sz_pind2sz_lookup (pszind_t pind)
static size_t sz_pind2sz (pszind_t pind)
static size_t sz_psz2u (size_t psz)
static szind_t sz_size2index_compute (size_t size)
JEMALLOC_ALWAYS_INLINE szind_t sz_size2index_lookup (size_t size)
JEMALLOC_ALWAYS_INLINE szind_t sz_size2index (size_t size)
static size_t sz_index2size_compute (szind_t index)
JEMALLOC_ALWAYS_INLINE size_t sz_index2size_lookup (szind_t index)
JEMALLOC_ALWAYS_INLINE size_t sz_index2size (szind_t index)
JEMALLOC_ALWAYS_INLINE size_t sz_s2u_compute (size_t size)
JEMALLOC_ALWAYS_INLINE size_t sz_s2u_lookup (size_t size)
JEMALLOC_ALWAYS_INLINE size_t sz_s2u (size_t size)
JEMALLOC_ALWAYS_INLINE size_t sz_sa2u (size_t size, size_t alignment)
Variables
size_t sz_pind2sz_tab [SC_NPSIZES+1]
size_t sz_index2size_tab [SC_NSIZES]
uint8_t sz_size2index_tab []
static const size_t sz_large_pad
Function Documentation
sz_boot()
void sz_boot (const sc_data_t * sc_data)
Definition at line 60 of file sz.c.
{
     sz_boot_pind2sz_tab(sc_data);
     sz_boot_index2size_tab(sc_data);
     sz_boot_size2index_tab(sc_data);
 }
References sz_boot_index2size_tab(), sz_boot_pind2sz_tab(), and sz_boot_size2index_tab().
sz_index2size()
JEMALLOC_ALWAYS_INLINE size_t sz_index2size (szind_t index)
Definition at line 205 of file sz.h.
{
     assert(index < SC_NSIZES);
     return sz_index2size_lookup(index);
 }
References assert(), index, SC_NSIZES, and sz_index2size_lookup().
Referenced by arena_malloc_hard(), arena_malloc_small(), arena_reset(), arena_salloc(), arena_stats_merge(), arena_vsalloc(), ctl_arena_stats_amerge(), extent_usize_get(), free_fastpath(), ifree(), imalloc_body(), je_rallocx(), je_realloc(), je_xallocx(), JEMALLOC_ATTR(), tcache_alloc_large(), tcache_alloc_small(), and tcache_dalloc_large().
sz_index2size_compute()
static size_t sz_index2size_compute (szind_t index) inline static
Definition at line 172 of file sz.h.
{
 #if (SC_NTINY > 0)
     if (index < SC_NTINY) {
         return (ZU(1) << (SC_LG_TINY_MAXCLASS - SC_NTINY + 1 + index));
     }
 #endif
     {
         size_t reduced_index = index - SC_NTINY;
         size_t grp = reduced_index >> SC_LG_NGROUP;
         size_t mod = reduced_index & ((ZU(1) << SC_LG_NGROUP) -
             1);
         size_t grp_size_mask = ~((!!grp)-1);
         size_t grp_size = ((ZU(1) << (LG_QUANTUM +
             (SC_LG_NGROUP-1))) << grp) & grp_size_mask;
         size_t shift = (grp == 0) ? 1 : grp;
         size_t lg_delta = shift + (LG_QUANTUM-1);
         size_t mod_size = (mod+1) << lg_delta;
         size_t usize = grp_size + mod_size;
         return usize;
     }
 }
References index, mod(), SC_LG_NGROUP, SC_LG_TINY_MAXCLASS, SC_NTINY, and ZU.
Referenced by sz_index2size_lookup().
sz_index2size_lookup()
JEMALLOC_ALWAYS_INLINE size_t sz_index2size_lookup (szind_t index)
Definition at line 198 of file sz.h.
{
     size_t ret = (size_t)sz_index2size_tab[index];
     assert(ret == sz_index2size_compute(index));
     return ret;
 }
References assert(), index, ret, sz_index2size_compute(), and sz_index2size_tab.
Referenced by sz_index2size(), and sz_s2u_lookup().
sz_pind2sz()
static size_t sz_pind2sz (pszind_t pind) inline static
Definition at line 101 of file sz.h.
{
     assert(pind < SC_NPSIZES + 1);
     return sz_pind2sz_lookup(pind);
 }
References assert(), SC_NPSIZES, and sz_pind2sz_lookup().
Referenced by arena_retain_grow_limit_get_set(), base_block_alloc(), extent_grow_retained(), extent_size_quantize_ceil(), extent_size_quantize_floor(), extents_first_fit_locked(), and stats_arena_extents_print().
sz_pind2sz_compute()
static size_t sz_pind2sz_compute (pszind_t pind) inline static
Definition at line 74 of file sz.h.
{
     if (unlikely(pind == SC_NPSIZES)) {
         return SC_LARGE_MAXCLASS + PAGE;
     }
     size_t grp = pind >> SC_LG_NGROUP;
     size_t mod = pind & ((ZU(1) << SC_LG_NGROUP) - 1);
     size_t grp_size_mask = ~((!!grp)-1);
     size_t grp_size = ((ZU(1) << (LG_PAGE + (SC_LG_NGROUP-1))) << grp)
         & grp_size_mask;
     size_t shift = (grp == 0) ? 1 : grp;
     size_t lg_delta = shift + (LG_PAGE-1);
     size_t mod_size = (mod+1) << lg_delta;
     size_t sz = grp_size + mod_size;
     return sz;
 }
References LG_PAGE, mod(), PAGE, SC_LARGE_MAXCLASS, SC_LG_NGROUP, SC_NPSIZES, unlikely, and ZU.
Referenced by sz_pind2sz_lookup().
sz_pind2sz_lookup()
static size_t sz_pind2sz_lookup (pszind_t pind) inline static
Definition at line 94 of file sz.h.
{
     size_t ret = (size_t)sz_pind2sz_tab[pind];
     assert(ret == sz_pind2sz_compute(pind));
     return ret;
 }
References assert(), ret, sz_pind2sz_compute(), and sz_pind2sz_tab.
Referenced by sz_pind2sz().
sz_psz2ind()
JEMALLOC_ALWAYS_INLINE pszind_t sz_psz2ind (size_t psz)
Definition at line 53 of file sz.h.
{
     if (unlikely(psz > SC_LARGE_MAXCLASS)) {
         return SC_NPSIZES;
     }
     pszind_t x = lg_floor((psz<<1)-1);
     pszind_t shift = (x < SC_LG_NGROUP + LG_PAGE) ?
         0 : x - (SC_LG_NGROUP + LG_PAGE);
     pszind_t grp = shift << SC_LG_NGROUP;
     pszind_t lg_delta = (x < SC_LG_NGROUP + LG_PAGE + 1) ?
         LG_PAGE : x - SC_LG_NGROUP - 1;
     size_t delta_inverse_mask = ZU(-1) << lg_delta;
     pszind_t mod = ((((psz-1) & delta_inverse_mask) >> lg_delta)) &
         ((ZU(1) << SC_LG_NGROUP) - 1);
     pszind_t ind = grp + mod;
     return ind;
 }
References lg_floor(), LG_PAGE, mod(), SC_LARGE_MAXCLASS, SC_LG_NGROUP, SC_NPSIZES, unlikely, G3D::x, and ZU.
Referenced by arena_new(), arena_retain_grow_limit_get_set(), base_block_alloc(), extent_grow_retained(), extent_size_quantize_ceil(), extent_size_quantize_floor(), extents_first_fit_locked(), extents_fit_alignment(), extents_insert_locked(), and extents_remove_locked().
sz_psz2u()
static size_t sz_psz2u (size_t psz) inline static
Definition at line 107 of file sz.h.
                      {
     if (unlikely(psz > SC_LARGE_MAXCLASS)) {
         return SC_LARGE_MAXCLASS + PAGE;
     }
     size_t x = lg_floor((psz<<1)-1);
     size_t lg_delta = (x < SC_LG_NGROUP + LG_PAGE + 1) ?
         LG_PAGE : x - SC_LG_NGROUP - 1;
     size_t delta = ZU(1) << lg_delta;
     size_t delta_mask = delta - 1;
     size_t usize = (psz + delta_mask) & ~delta_mask;
     return usize;
 }
References lg_floor(), LG_PAGE, PAGE, SC_LARGE_MAXCLASS, SC_LG_NGROUP, unlikely, G3D::x, and ZU.
Referenced by base_block_alloc().
sz_s2u()
JEMALLOC_ALWAYS_INLINE size_t sz_s2u (size_t size)
Definition at line 251 of file sz.h.
                     {
     if (likely(size <= SC_LOOKUP_MAXCLASS)) {
         return sz_s2u_lookup(size);
     }
     return sz_s2u_compute(size);
 }
References likely, SC_LOOKUP_MAXCLASS, sz_s2u_compute(), and sz_s2u_lookup().
Referenced by arena_ralloc(), arena_ralloc_no_move(), imalloc_sample(), inallocx(), ixallocx_prof(), je_rallocx(), je_realloc(), large_malloc(), prof_alloc_prep(), sz_sa2u(), tcache_alloc_large(), and zone_good_size().
sz_s2u_compute()
JEMALLOC_ALWAYS_INLINE size_t sz_s2u_compute (size_t size)
Definition at line 211 of file sz.h.
{
     if (unlikely(size > SC_LARGE_MAXCLASS)) {
         return 0;
     }
     if (size == 0) {
         size++;
     }
 #if (SC_NTINY > 0)
     if (size <= (ZU(1) << SC_LG_TINY_MAXCLASS)) {
         size_t lg_tmin = SC_LG_TINY_MAXCLASS - SC_NTINY + 1;
         size_t lg_ceil = lg_floor(pow2_ceil_zu(size));
         return (lg_ceil < lg_tmin ? (ZU(1) << lg_tmin) :
             (ZU(1) << lg_ceil));
     }
 #endif
     {
         size_t x = lg_floor((size<<1)-1);
         size_t lg_delta = (x < SC_LG_NGROUP + LG_QUANTUM + 1)
             ?  LG_QUANTUM : x - SC_LG_NGROUP - 1;
         size_t delta = ZU(1) << lg_delta;
         size_t delta_mask = delta - 1;
         size_t usize = (size + delta_mask) & ~delta_mask;
         return usize;
     }
 }
References lg_ceil(), lg_floor(), pow2_ceil_zu(), SC_LARGE_MAXCLASS, SC_LG_NGROUP, SC_LG_TINY_MAXCLASS, SC_NTINY, unlikely, G3D::x, and ZU.
Referenced by sz_s2u(), and sz_s2u_lookup().
sz_s2u_lookup()
JEMALLOC_ALWAYS_INLINE size_t sz_s2u_lookup (size_t size)
Definition at line 239 of file sz.h.
{
     size_t ret = sz_index2size_lookup(sz_size2index_lookup(size));
     assert(ret == sz_s2u_compute(size));
     return ret;
 }
References assert(), ret, sz_index2size_lookup(), sz_s2u_compute(), and sz_size2index_lookup().
Referenced by sz_s2u().
sz_sa2u()
JEMALLOC_ALWAYS_INLINE size_t sz_sa2u (size_t size, size_t alignment)
Definition at line 263 of file sz.h.
{
     size_t usize;
     assert(alignment != 0 && ((alignment - 1) & alignment) == 0);
     /* Try for a small size class. */
     if (size <= SC_SMALL_MAXCLASS && alignment < PAGE) {
         /*
          * Round size up to the nearest multiple of alignment.
          *
          * This done, we can take advantage of the fact that for each
          * small size class, every object is aligned at the smallest
          * power of two that is non-zero in the base two representation
          * of the size.  For example:
          *
          *   Size |   Base 2 | Minimum alignment
          *   -----+----------+------------------
          *     96 |  1100000 |  32
          *    144 | 10100000 |  32
          *    192 | 11000000 |  64
          */
         usize = sz_s2u(ALIGNMENT_CEILING(size, alignment));
         if (usize < SC_LARGE_MINCLASS) {
             return usize;
         }
     }
     /* Large size class.  Beware of overflow. */
     if (unlikely(alignment > SC_LARGE_MAXCLASS)) {
         return 0;
     }
     /* Make sure result is a large size class. */
     if (size <= SC_LARGE_MINCLASS) {
         usize = SC_LARGE_MINCLASS;
     } else {
         usize = sz_s2u(size);
         if (usize < size) {
             /* size_t overflow. */
             return 0;
         }
     }
     /*
      * Calculate the multi-page mapping that large_palloc() would need in
      * order to guarantee the alignment.
      */
     if (usize + sz_large_pad + PAGE_CEILING(alignment) - PAGE < usize) {
         /* size_t overflow. */
         return 0;
     }
     return usize;
 }
References ALIGNMENT_CEILING, assert(), PAGE, PAGE_CEILING, SC_LARGE_MAXCLASS, SC_LARGE_MINCLASS, SC_SMALL_MAXCLASS, sz_large_pad, sz_s2u(), and unlikely.
Referenced by arena_ralloc_move_helper(), ckh_grow(), ckh_new(), ckh_shrink(), imalloc_body(), imalloc_sample(), inallocx(), ipallocztm(), iralloct_realign(), ixallocx_prof(), je_rallocx(), large_palloc(), tcache_create_explicit(), and tsd_tcache_data_init().
sz_size2index()
JEMALLOC_ALWAYS_INLINE szind_t sz_size2index (size_t size)
Definition at line 164 of file sz.h.
{
     if (likely(size <= SC_LOOKUP_MAXCLASS)) {
         return sz_size2index_lookup(size);
     }
     return sz_size2index_compute(size);
 }
References likely, SC_LOOKUP_MAXCLASS, sz_size2index_compute(), and sz_size2index_lookup().
Referenced by a0ialloc(), arena_dalloc_promoted(), arena_extent_alloc_large(), arena_large_dalloc_stats_update(), arena_large_malloc_stats_update(), arena_palloc(), arena_prof_promote(), arena_ralloc_move_helper(), arena_ralloc_no_move(), arena_sdalloc(), arena_sdalloc_no_tcache(), arena_slab_alloc(), base_alloc_impl(), base_extent_bump_alloc_post(), imalloc_body(), imalloc_sample(), isfree(), large_ralloc_no_move_expand(), large_ralloc_no_move_shrink(), prof_gctx_create(), prof_log_bt_index(), prof_log_thr_index(), prof_lookup(), prof_tdata_init_impl(), prof_thread_name_alloc(), prof_try_log(), and tcache_boot().
sz_size2index_compute()
static szind_t sz_size2index_compute (size_t size) inline static
Definition at line 121 of file sz.h.
{
     if (unlikely(size > SC_LARGE_MAXCLASS)) {
         return SC_NSIZES;
     }
     if (size == 0) {
         return 0;
     }
 #if (SC_NTINY != 0)
     if (size <= (ZU(1) << SC_LG_TINY_MAXCLASS)) {
         szind_t lg_tmin = SC_LG_TINY_MAXCLASS - SC_NTINY + 1;
         szind_t lg_ceil = lg_floor(pow2_ceil_zu(size));
         return (lg_ceil < lg_tmin ? 0 : lg_ceil - lg_tmin);
     }
 #endif
     {
         szind_t x = lg_floor((size<<1)-1);
         szind_t shift = (x < SC_LG_NGROUP + LG_QUANTUM) ? 0 :
             x - (SC_LG_NGROUP + LG_QUANTUM);
         szind_t grp = shift << SC_LG_NGROUP;
         szind_t lg_delta = (x < SC_LG_NGROUP + LG_QUANTUM + 1)
             ? LG_QUANTUM : x - SC_LG_NGROUP - 1;
         size_t delta_inverse_mask = ZU(-1) << lg_delta;
         szind_t mod = ((((size-1) & delta_inverse_mask) >> lg_delta)) &
             ((ZU(1) << SC_LG_NGROUP) - 1);
         szind_t index = SC_NTINY + grp + mod;
         return index;
     }
 }
References index, lg_ceil(), lg_floor(), mod(), pow2_ceil_zu(), SC_LARGE_MAXCLASS, SC_LG_NGROUP, SC_LG_TINY_MAXCLASS, SC_NSIZES, SC_NTINY, unlikely, G3D::x, and ZU.
Referenced by bin_update_shard_size(), sz_size2index(), and sz_size2index_lookup().
sz_size2index_lookup()
JEMALLOC_ALWAYS_INLINE szind_t sz_size2index_lookup (size_t size)
Definition at line 155 of file sz.h.
{
     assert(size <= SC_LOOKUP_MAXCLASS);
     szind_t ret = (sz_size2index_tab[(size + (ZU(1) << SC_LG_TINY_MIN) - 1)
                      >> SC_LG_TINY_MIN]);
     assert(ret == sz_size2index_compute(size));
     return ret;
 }
References assert(), ret, SC_LG_TINY_MIN, SC_LOOKUP_MAXCLASS, sz_size2index_compute(), sz_size2index_tab, and ZU.
Referenced by free_fastpath(), JEMALLOC_ATTR(), sz_s2u_lookup(), and sz_size2index().
Variable Documentation
sz_index2size_tab
size_t sz_index2size_tab[SC_NSIZES] extern
Definition at line 24 of file sz.c.
Referenced by sz_boot_index2size_tab(), and sz_index2size_lookup().
sz_large_pad
const size_t sz_large_pad static
Initial value:
=
    0
Definition at line 42 of file sz.h.
Referenced by arena_extent_alloc_large(), extent_size_quantize_ceil(), extent_size_quantize_floor(), large_ralloc_no_move_shrink(), and sz_sa2u().
sz_pind2sz_tab
size_t sz_pind2sz_tab[SC_NPSIZES+1] extern
Definition at line 5 of file sz.c.
Referenced by sz_boot_pind2sz_tab(), and sz_pind2sz_lookup().
sz_size2index_tab
uint8_t sz_size2index_tab[] extern
Definition at line 40 of file sz.c.
Referenced by sz_boot_size2index_tab(), and sz_size2index_lookup().