Azerotcore-wotlk: InstanceMapScript Class Reference
InstanceMapScript Class Reference
#include <ScriptMgr.h>
Public Member Functions
bool IsDatabaseBound () const override
void checkValidity () override
virtual InstanceScript * GetInstanceScript (InstanceMap *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
const std::string & GetName () const
Public Member Functions inherited from MapScript< InstanceMap >
void checkMap ()
MapEntry const * GetEntry ()
virtual void OnCreate (InstanceMap *)
virtual void OnDestroy (InstanceMap *)
virtual void OnLoadGridMap (InstanceMap *, GridMap *, uint32, uint32)
virtual void OnUnloadGridMap (InstanceMap *, GridMap *, uint32, uint32)
virtual void OnPlayerEnter (InstanceMap *, Player *)
virtual void OnPlayerLeave (InstanceMap *, Player *)
void OnUpdate (InstanceMap *, uint32) override
Public Member Functions inherited from UpdatableScript< TObject >
virtual void OnUpdate (TObject *, uint32)
Protected Member Functions
InstanceMapScript (const char *name, uint32 mapId)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from MapScript< InstanceMap >
MapScript (uint32 mapId)
Protected Member Functions inherited from UpdatableScript< TObject >
UpdatableScript ()=default
Detailed Description
Definition at line 319 of file ScriptMgr.h.
Constructor & Destructor Documentation
InstanceMapScript()
InstanceMapScript::InstanceMapScript (const char * name, uint32 mapId) protected
Definition at line 3214 of file ScriptMgr.cpp.
     : ScriptObject(name), MapScript<InstanceMap>(mapId)
 {
     ScriptRegistry<InstanceMapScript>::AddScript(this);
 }
References ScriptRegistry< TScript >::AddScript().
Member Function Documentation
checkValidity()
void InstanceMapScript::checkValidity () inline override virtual
Reimplemented from ScriptObject.
Definition at line 327 of file ScriptMgr.h.
     {
         checkMap();
         if (GetEntry() && !GetEntry()->IsDungeon())
             LOG_ERROR("maps.script", "InstanceMapScript for map %u is invalid.", GetEntry()->MapID);
     }
References MapScript< InstanceMap >::checkMap(), MapScript< InstanceMap >::GetEntry(), and LOG_ERROR.
GetInstanceScript()
virtual InstanceScript* InstanceMapScript::GetInstanceScript (InstanceMap *) const inline virtual
Reimplemented in instance_violet_hold, instance_utgarde_pinnacle, instance_utgarde_keep, instance_ulduar, instance_halls_of_stone, instance_halls_of_lightning, instance_oculus, instance_eye_of_eternity, instance_naxxramas, instance_gundrak, instance_halls_of_reflection, instance_trial_of_the_champion, instance_obsidian_sanctum, instance_onyxias_lair, instance_culling_of_stratholme, instance_mechanar, instance_the_eye, instance_the_botanica, instance_arcatraz, instance_shattered_halls, instance_magtheridons_lair, instance_hellfire_ramparts, instance_blood_furnace, instance_gruuls_lair, instance_the_underbog, instance_steam_vault, instance_the_slave_pens, instance_serpent_shrine, instance_black_temple, instance_shadow_labyrinth, instance_sethekk_halls, instance_mana_tombs, instance_auchenai_crypts, instance_vault_of_archavon, instance_nexus, instance_icecrown_citadel, instance_pit_of_saron, instance_forge_of_souls, instance_drak_tharon_keep, instance_trial_of_the_crusader, instance_ruby_sanctum, instance_azjol_nerub, instance_ahnkahet, instance_zulfarrak, instance_wailing_caverns, instance_temple_of_ahnqiraj, instance_ruins_of_ahnqiraj, instance_razorfen_kraul, instance_razorfen_downs, instance_ragefire_chasm, instance_maraudon, instance_dire_maul, instance_the_black_morass, instance_old_hillsbrad, instance_hyjal, instance_blackfathom_deeps, instance_zulgurub, instance_zulaman, instance_uldaman, instance_the_stockade, instance_sunwell_plateau, instance_sunken_temple, instance_stratholme, instance_shadowfang_keep, instance_scholomance, instance_scarlet_monastery, instance_magisters_terrace, instance_karazhan, instance_gnomeregan, instance_deadmines, instance_molten_core, instance_blackrock_spire, instance_blackrock_depths, and instance_blackwing_lair.
Definition at line 336 of file ScriptMgr.h.
 { return nullptr; }
IsDatabaseBound()
bool InstanceMapScript::IsDatabaseBound () const inline override virtual
Reimplemented from ScriptObject.
Definition at line 325 of file ScriptMgr.h.
 { return true; }
The documentation for this class was generated from the following files:
src/server/game/Scripting/ScriptMgr.h
src/server/game/Scripting/ScriptMgr.cpp