Azerotcore-wotlk: Field Class Reference
Field Class Reference
Class used to access individual fields of database query result.
#include <Field.h>
Public Member Functions
Field ()
~Field ()
bool GetBool () const
uint8 GetUInt8 () const
int8 GetInt8 () const
uint16 GetUInt16 () const
int16 GetInt16 () const
uint32 GetUInt32 () const
int32 GetInt32 () const
uint64 GetUInt64 () const
int64 GetInt64 () const
float GetFloat () const
double GetDouble () const
char const * GetCString () const
std::string GetString () const
std::string_view GetStringView () const
std::vector< uint8 > GetBinary () const
template<size_t S>
std::array< uint8, S > GetBinary () const
bool IsNull () const
DatabaseFieldTypes GetType ()
Protected Member Functions
void SetByteValue (char const *newValue, uint32 length)
void SetStructuredValue (char const *newValue, uint32 length)
bool IsType (DatabaseFieldTypes type) const
bool IsNumeric () const
Protected Attributes
struct {
char const * value
uint32 length
bool raw
} data
Private Member Functions
void LogWrongType (char const *getter) const
void SetMetadata (QueryResultFieldMetadata const *fieldMeta)
void GetBinarySizeChecked (uint8 *buf, size_t size) const
Private Attributes
QueryResultFieldMetadata const * meta
Friends
class ResultSet
class PreparedResultSet
Detailed Description
Class used to access individual fields of database query result.
Guideline on field type matching:
MySQL type method to use
TINYINT GetBool, GetInt8, GetUInt8
SMALLINT GetInt16, GetUInt16
MEDIUMINT, INT GetInt32, GetUInt32
BIGINT GetInt64, GetUInt64
FLOAT GetFloat
DOUBLE, DECIMAL GetDouble
CHAR, VARCHAR, GetCString, GetString
TINYTEXT, MEDIUMTEXT, GetCString, GetString
TEXT, LONGTEXT GetCString, GetString
TINYBLOB, MEDIUMBLOB, GetBinary, GetString
BLOB, LONGBLOB GetBinary, GetString
BINARY, VARBINARY GetBinary
Return types of aggregate functions:
Function Type
MIN, MAX Same as the field
SUM, AVG DECIMAL
COUNT BIGINT
Definition at line 83 of file Field.h.
Constructor & Destructor Documentation
Field()
Field::Field ()
Definition at line 23 of file Field.cpp.
 {
     data.value = nullptr;
     data.length = 0;
     data.raw = false;
     meta = nullptr;
 }
References meta.
~Field()
Field::~Field () default
Member Function Documentation
GetBinary() [1/2]
std::vector< uint8 > Field::GetBinary () const
Definition at line 252 of file Field.cpp.
 {
     std::vector<uint8> result;
     if (!data.value || !data.length)
         return result;
     result.resize(data.length);
     memcpy(result.data(), data.value, data.length);
     return result;
 }
References memcpy.
Referenced by AccountInfo::AccountInfo(), SecretMgr::AttemptTransition(), account_commandscript::HandleAccount2FARemoveCommand(), AuthSession::LogonChallengeCallback(), and AuthSession::ReconnectChallengeCallback().
GetBinary() [2/2]
template<size_t S> std::array<uint8, S> Field::GetBinary () const inline
Definition at line 113 of file Field.h.
     {
         std::array<uint8, S> buf;
         GetBinarySizeChecked(buf.data(), S);
         return buf;
     }
GetBinarySizeChecked()
void Field::GetBinarySizeChecked (uint8 * buf, size_t size) const private
Definition at line 263 of file Field.cpp.
 {
     ASSERT(data.value && (data.length == length), "Expected %zu-byte binary blob, got %sdata (%u bytes) instead", length, data.value ? "" : "no ", data.length);
     memcpy(buf, data.value, length);
 }
References ASSERT, length, and memcpy.
GetBool()
bool Field::GetBool () const inline
Definition at line 92 of file Field.h.
     {
         return GetUInt8() == 1 ? true : false;
     }
References true.
Referenced by Player::_LoadSpellCooldowns(), AccountInfo::AccountInfo(), Player::DeleteFromDB(), ObjectMgr::LoadAccessRequirements(), InstanceSaveMgr::LoadCharacterBinds(), ObjectMgr::LoadCreatureAddons(), ObjectMgr::LoadCreatureTemplate(), ObjectMgr::LoadCreatureTemplateAddons(), GmTicket::LoadFromDB(), ObjectMgr::LoadGossipMenuItems(), ObjectMgr::LoadInstanceTemplate(), LootStore::LoadLootTable(), ObjectMgr::LoadPetNames(), ObjectMgr::LoadReputationOnKill(), AccountInfo::LoadResult(), SpellMgr::LoadSpellAreas(), ObjectMgr::LoadVehicleAccessories(), ObjectMgr::LoadVehicleTemplateAccessories(), and ObjectMgr::ReturnOrDeleteOldMails().
GetCString()
char const * Field::GetCString () const
Definition at line 213 of file Field.cpp.
 {
     if (!data.value)
         return nullptr;
 #ifdef ACORE_STRICT_DATABASE_TYPE_CHECKS
     if (IsNumeric() && data.raw)
     {
         LogWrongType(__FUNCTION__);
         return nullptr;
     }
 #endif
     return static_cast<char const*>(data.value);
 }
References const, IsNumeric(), and LogWrongType().
Referenced by GetString(), GetStringView(), account_commandscript::HandleAccountOnlineListCommand(), ban_commandscript::HandleBanInfoCharacterCommand(), ban_commandscript::HandleBanInfoHelper(), ban_commandscript::HandleBanInfoIPCommand(), ban_commandscript::HandleBanListCharacterCommand(), ban_commandscript::HandleBanListHelper(), ban_commandscript::HandleBanListIPCommand(), gm_commandscript::HandleGMListFullCommand(), wp_commandscript::HandleWpEventCommand(), ObjectMgr::LoadAreaTriggerScripts(), ChannelMgr::LoadChannelRights(), and ObjectMgr::LoadSpellScriptNames().
GetDouble()
double Field::GetDouble () const
Definition at line 195 of file Field.cpp.
 {
     if (!data.value)
         return 0.0f;
 #ifdef ACORE_STRICT_DATABASE_TYPE_CHECKS
     if (!IsType(DatabaseFieldTypes::Double) && !IsType(DatabaseFieldTypes::Decimal))
     {
         LogWrongType(__FUNCTION__);
         return 0.0f;
     }
 #endif
     if (data.raw && !IsType(DatabaseFieldTypes::Decimal))
         return *reinterpret_cast<double const*>(data.value);
     return static_cast<double>(atof(data.value));
 }
References const, Decimal, Double, IsType(), and LogWrongType().
GetFloat()
float Field::GetFloat () const
Definition at line 177 of file Field.cpp.
 {
     if (!data.value)
         return 0.0f;
 #ifdef ACORE_STRICT_DATABASE_TYPE_CHECKS
     if (!IsType(DatabaseFieldTypes::Float))
     {
         LogWrongType(__FUNCTION__);
         return 0.0f;
     }
 #endif
     if (data.raw)
         return *reinterpret_cast<float const*>(data.value);
     return static_cast<float>(atof(data.value));
 }
References const, Float, IsType(), and LogWrongType().
Referenced by Player::_LoadHomeBind(), Player::BuildEnumData(), BattlegroundMgr::CreateInitialBattlegrounds(), Player::GetZoneIdFromDB(), gobject_commandscript::HandleGameObjectNearCommand(), gobject_commandscript::HandleGameObjectTargetCommand(), list_commandscript::HandleListCreatureCommand(), list_commandscript::HandleListObjectCommand(), npc_commandscript::HandleNpcNearCommand(), wp_commandscript::HandleWpEventCommand(), wp_commandscript::HandleWpShowCommand(), WaypointMgr::Load(), ObjectMgr::LoadAreaTriggers(), ObjectMgr::LoadAreaTriggerTeleports(), Corpse::LoadCorpseFromDB(), ObjectMgr::LoadCreatureClassLevelStats(), FormationMgr::LoadCreatureFormations(), ObjectMgr::LoadCreatureModelInfo(), ObjectMgr::LoadCreatures(), ObjectMgr::LoadCreatureTemplate(), CreatureTextMgr::LoadCreatureTexts(), SmartWaypointMgr::LoadFromDB(), GameEventMgr::LoadFromDB(), PoolMgr::LoadFromDB(), GmTicket::LoadFromDB(), Player::LoadFromDB(), ObjectMgr::LoadGameobjects(), ObjectMgr::LoadGameObjectTemplate(), ObjectMgr::LoadGameTele(), ObjectMgr::LoadGossipText(), Graveyard::LoadGraveyardFromDB(), ObjectMgr::LoadItemTemplates(), lfg::LFGMgr::LoadLFGDungeons(), LootStore::LoadLootTable(), ObjectMgr::LoadPlayerInfo(), ObjectMgr::LoadPointsOfInterest(), Player::LoadPositionFromDB(), LoadRandomEnchantmentsTable(), LoadRealmInfo(), ObjectMgr::LoadReputationRewardRate(), ObjectMgr::LoadReputationSpilloverTemplate(), ObjectMgr::LoadScripts(), SystemMgr::LoadScriptWaypoints(), LoadSkillDiscoveryTable(), LoadSkillExtraItemTable(), LoadSkillPerfectItemTable(), SmartAIMgr::LoadSmartAIFromDB(), SpellMgr::LoadSpellBonusess(), SpellMgr::LoadSpellEnchantProcData(), SpellMgr::LoadSpellMixology(), SpellMgr::LoadSpellProcEvents(), SpellMgr::LoadSpellProcs(), SpellMgr::LoadSpellTargetPositions(), SpellMgr::LoadSpellThreats(), ObjectMgr::LoadTempSummons(), Quest::Quest(), WaypointMgr::ReloadPath(), TransportMgr::SpawnContinentTransports(), and RealmList::UpdateRealms().
GetInt16()
int16 Field::GetInt16 () const
Definition at line 87 of file Field.cpp.
 {
     if (!data.value)
         return 0;
 #ifdef ACORE_STRICT_DATABASE_TYPE_CHECKS
     if (!IsType(DatabaseFieldTypes::Int16))
     {
         LogWrongType(__FUNCTION__);
         return 0;
     }
 #endif
     if (data.raw)
         return *reinterpret_cast<int16 const*>(data.value);
     return static_cast<int16>(strtol(data.value, nullptr, 10));
 }
References const, Int16, IsType(), LogWrongType(), and strtol().
Referenced by Player::_LoadMail(), WaypointMgr::Load(), ObjectMgr::LoadCreatureTemplateResistances(), ObjectMgr::LoadFishingBaseSkillLevel(), ObjectMgr::LoadReputationOnKill(), Quest::Quest(), and ObjectMgr::ReturnOrDeleteOldMails().
GetInt32()
int32 Field::GetInt32 () const
Definition at line 123 of file Field.cpp.
 {
     if (!data.value)
         return 0;
 #ifdef ACORE_STRICT_DATABASE_TYPE_CHECKS
     if (!IsType(DatabaseFieldTypes::Int32))
     {
         LogWrongType(__FUNCTION__);
         return 0;
     }
 #endif
     if (data.raw)
         return *reinterpret_cast<int32 const*>(data.value);
     return static_cast<int32>(strtol(data.value, nullptr, 10));
 }
References const, Int32, IsType(), LogWrongType(), and strtol().
Referenced by Pet::_LoadAuras(), Player::_LoadAuras(), Player::_LoadMail(), WorldSession::HandleCharFactionOrRaceChangeCallback(), ConditionMgr::LoadConditions(), ObjectMgr::LoadExplorationBaseXP(), CalendarMgr::LoadFromDB(), Player::LoadFromDB(), ReputationMgr::LoadFromDB(), ObjectMgr::LoadGameobjects(), ObjectMgr::LoadGameObjectTemplate(), ObjectMgr::LoadItemTemplates(), LootStore::LoadLootTable(), ObjectMgr::LoadPlayerInfo(), ObjectMgr::LoadQuestPOI(), Quest::LoadQuestTemplateAddon(), ObjectMgr::LoadReferenceVendor(), ObjectMgr::LoadReputationOnKill(), ObjectMgr::LoadScripts(), LoadSkillDiscoveryTable(), LoadSkillExtraItemTable(), SmartAIMgr::LoadSmartAIFromDB(), SpellMgr::LoadSpellAreas(), SpellMgr::LoadSpellLinked(), SpellMgr::LoadSpellProcEvents(), SpellMgr::LoadSpellProcs(), ObjectMgr::LoadSpellScriptNames(), SpellMgr::LoadSpellThreats(), ObjectMgr::LoadVendors(), Quest::Quest(), and ObjectMgr::ReturnOrDeleteOldMails().
GetInt64()
int64 Field::GetInt64 () const
Definition at line 159 of file Field.cpp.
 {
     if (!data.value)
         return 0;
 #ifdef ACORE_STRICT_DATABASE_TYPE_CHECKS
     if (!IsType(DatabaseFieldTypes::Int64))
     {
         LogWrongType(__FUNCTION__);
         return 0;
     }
 #endif
     if (data.raw)
         return *reinterpret_cast<int64 const*>(data.value);
     return static_cast<int64>(strtoll(data.value, nullptr, 10));
 }
References const, Int64, IsType(), LogWrongType(), and strtoll.
Referenced by AccountInfo::AccountInfo().
GetInt8()
int8 Field::GetInt8 () const
Definition at line 51 of file Field.cpp.
 {
     if (!data.value)
         return 0;
 #ifdef ACORE_STRICT_DATABASE_TYPE_CHECKS
     if (!IsType(DatabaseFieldTypes::Int8))
     {
         LogWrongType(__FUNCTION__);
         return 0;
     }
 #endif
     if (data.raw)
         return *reinterpret_cast<int8 const*>(data.value);
     return static_cast<int8>(strtol(data.value, nullptr, 10));
 }
References const, Int8, IsType(), LogWrongType(), and strtol().
Referenced by ObjectMgr::LoadCreatures(), GameEventMgr::LoadFromDB(), ObjectMgr::LoadGameobjects(), SpellMgr::LoadSpellGroupStackRules(), SpellMgr::LoadSpellProcEvents(), and SpellMgr::LoadSpellProcs().
GetString()
std::string Field::GetString () const
Definition at line 228 of file Field.cpp.
 {
     if (!data.value)
         return "";
     char const* string = GetCString();
     if (!string)
         return "";
     return std::string(string, data.length);
 }
References GetCString().
Referenced by Player::_LoadEntryPointData(), Player::_LoadEquipmentSets(), Player::_LoadMail(), AccountInfo::AccountInfo(), Guild::AddMember(), Player::BuildEnumData(), CreateDumpString(), Player::DeleteFromDB(), character_commandscript::GetDeletedCharacterInfoList(), World::GetGlobalPlayerData(), account_commandscript::HandleAccountOnlineListCommand(), ban_commandscript::HandleBanListCharacterCommand(), ban_commandscript::HandleBanListHelper(), WorldSession::HandleCharacterAuraFrozen(), WorldSession::HandleCharCustomizeCallback(), WorldSession::HandleCharFactionOrRaceChangeCallback(), WorldSession::HandleCharRenameCallBack(), list_commandscript::HandleListItemCommand(), misc_commandscript::HandlePInfoCommand(), WorldSession::HandleWhoisOpcode(), ObjectMgr::LoadAccessRequirements(), WorldSession::LoadAccountData(), AchievementGlobalMgr::LoadAchievementCriteriaData(), ArenaTeam::LoadArenaTeamFromDB(), World::LoadAutobroadcasts(), ObjectMgr::LoadBroadcastTexts(), RealmList::LoadBuildInfo(), ChannelMgr::LoadChannels(), ObjectMgr::LoadCreatureTemplate(), CreatureTextMgr::LoadCreatureTexts(), World::LoadDBRevision(), World::LoadDBVersion(), DisableMgr::LoadDisables(), AddonMgr::LoadFromDB(), CalendarMgr::LoadFromDB(), GameEventMgr::LoadFromDB(), Guild::Member::LoadFromDB(), Guild::RankInfo::LoadFromDB(), Guild::BankTab::LoadFromDB(), Guild::LoadFromDB(), GmTicket::LoadFromDB(), Player::LoadFromDB(), Item::LoadFromDB(), SocialMgr::LoadFromDB(), ObjectMgr::LoadGameObjectTemplate(), ObjectMgr::LoadGameTele(), ObjectMgr::LoadGossipMenuItems(), ObjectMgr::LoadGossipText(), Graveyard::LoadGraveyardFromDB(), InstanceSaveMgr::LoadInstanceSaves(), ObjectMgr::LoadItemSetNames(), ObjectMgr::LoadItemTemplates(), ObjectMgr::LoadPageTexts(), ObjectMgr::LoadPetNames(), ObjectMgr::LoadPointsOfInterest(), Player::LoadPositionFromDB(), Quest::LoadQuestOfferReward(), ObjectMgr::LoadQuestOfferRewardLocale(), Quest::LoadQuestRequestItems(), ObjectMgr::LoadQuestRequestItemsLocale(), LoadRealmInfo(), ObjectMgr::LoadReservedPlayersNames(), AccountInfo::LoadResult(), AchievementGlobalMgr::LoadRewards(), WardenCheckMgr::LoadWardenChecks(), lookup_commandscript::LookupPlayerSearchCommand(), Quest::Quest(), UpdateFetcher::ReceiveAppliedFiles(), UpdateFetcher::ReceiveIncludedDirectories(), WorldSession::SendStablePetCallback(), StoreGUID(), and RealmList::UpdateRealms().
GetStringView()
std::string_view Field::GetStringView () const
Definition at line 240 of file Field.cpp.
 {
     if (!data.value)
         return {};
     char const* const string = GetCString();
     if (!string)
         return {};
     return { string, data.length };
 }
References GetCString().
Referenced by Acore::Impl::ChatCommands::ChatCommandNode::LoadCommandMap().
GetType()
DatabaseFieldTypes Field::GetType () inline
Definition at line 125 of file Field.h.
 { return meta->Type; }
GetUInt16()
uint16 Field::GetUInt16 () const
Definition at line 69 of file Field.cpp.
 {
     if (!data.value)
         return 0;
 #ifdef ACORE_STRICT_DATABASE_TYPE_CHECKS
     if (!IsType(DatabaseFieldTypes::Int16))
     {
         LogWrongType(__FUNCTION__);
         return 0;
     }
 #endif
     if (data.raw)
         return *reinterpret_cast<uint16 const*>(data.value);
     return static_cast<uint16>(strtoul(data.value, nullptr, 10));
 }
References const, Int16, IsType(), LogWrongType(), and strtoul().
Referenced by Player::_LoadGlyphs(), Player::_LoadHomeBind(), Player::_LoadQuestStatus(), Player::_LoadSkills(), Pet::_LoadSpellCooldowns(), Player::_LoadSpellCooldowns(), Player::BuildEnumData(), BattlegroundMgr::CreateInitialBattlegrounds(), Player::DeleteFromDB(), Player::GetZoneIdFromDB(), account_commandscript::HandleAccountOnlineListCommand(), WorldSession::HandleCharCustomizeCallback(), WorldSession::HandleCharFactionOrRaceChangeCallback(), WorldSession::HandleCharRenameCallBack(), gobject_commandscript::HandleGameObjectNearCommand(), gobject_commandscript::HandleGameObjectTargetCommand(), list_commandscript::HandleListCreatureCommand(), list_commandscript::HandleListObjectCommand(), WorldSession::HandleLoadPetFromDBFirstCallback(), npc_commandscript::HandleNpcNearCommand(), misc_commandscript::HandlePInfoCommand(), tele_commandscript::HandleTeleNameCommand(), ObjectMgr::LoadAccessRequirements(), ObjectMgr::LoadAreaTriggerTeleports(), ArenaTeam::LoadArenaTeamFromDB(), AchievementGlobalMgr::LoadCompletedAchievements(), Corpse::LoadCorpseFromDB(), ObjectMgr::LoadCreatureClassLevelStats(), FormationMgr::LoadCreatureFormations(), ObjectMgr::LoadCreatures(), GameEventMgr::LoadFromDB(), GmTicket::LoadFromDB(), Player::LoadFromDB(), Item::LoadFromDB(), AchievementMgr::LoadFromDB(), ReputationMgr::LoadFromDB(), ObjectMgr::LoadGameobjects(), ObjectMgr::LoadGameTele(), ObjectMgr::LoadGossipMenu(), ObjectMgr::LoadGossipMenuItems(), ObjectMgr::LoadGossipMenuItemsLocales(), ObjectMgr::LoadGossipText(), Graveyard::LoadGraveyardZones(), ObjectMgr::LoadInstanceEncounters(), InstanceSaveMgr::LoadInstanceSaves(), ObjectMgr::LoadInstanceTemplate(), LootStore::LoadLootTable(), ArenaTeam::LoadMembersFromDB(), ObjectMgr::LoadNPCSpellClickSpells(), ObjectMgr::LoadPetLevelInfo(), ObjectMgr::LoadPlayerInfo(), Player::LoadPositionFromDB(), Quest::LoadQuestRequestItems(), Quest::LoadQuestTemplateAddon(), LoadRealmInfo(), ObjectMgr::LoadReputationSpilloverTemplate(), InstanceSaveMgr::LoadResetTimes(), LoadSkillDiscoveryTable(), SmartAIMgr::LoadSmartAIFromDB(), SpellMgr::LoadSpellProcEvents(), SpellMgr::LoadSpellProcs(), SpellMgr::LoadSpellTargetPositions(), ObjectMgr::LoadTrainerSpell(), WardenCheckMgr::LoadWardenChecks(), WardenCheckMgr::LoadWardenOverrides(), Quest::Quest(), TransportMgr::SpawnContinentTransports(), and RealmList::UpdateRealms().
GetUInt32()
uint32 Field::GetUInt32 () const
Definition at line 105 of file Field.cpp.
 {
     if (!data.value)
         return 0;
 #ifdef ACORE_STRICT_DATABASE_TYPE_CHECKS
     if (!IsType(DatabaseFieldTypes::Int32))
     {
         LogWrongType(__FUNCTION__);
         return 0;
     }
 #endif
     if (data.raw)
         return *reinterpret_cast<uint32 const*>(data.value);
     return static_cast<uint32>(strtoul(data.value, nullptr, 10));
 }
References const, Int32, IsType(), LogWrongType(), and strtoul().
Referenced by Player::_LoadActions(), Pet::_LoadAuras(), Player::_LoadAuras(), Player::_LoadBrewOfTheMonth(), Player::_LoadDailyQuestStatus(), Player::_LoadEntryPointData(), Player::_LoadEquipmentSets(), lfg::LFGMgr::_LoadFromDB(), Player::_LoadInventory(), Player::_LoadItem(), Player::_LoadMail(), Player::_LoadMailedItem(), Player::_LoadMonthlyQuestStatus(), Player::_LoadQuestStatus(), Player::_LoadQuestStatusRewarded(), Player::_LoadSeasonalQuestStatus(), Pet::_LoadSpellCooldowns(), Player::_LoadSpellCooldowns(), Player::_LoadWeeklyQuestStatus(), World::_UpdateRealmCharCount(), AccountInfo::AccountInfo(), SecretMgr::AttemptTransition(), BanMgr::BanIP(), Player::BuildEnumData(), CharacterDatabaseCleaner::CheckUnique(), BattlegroundMgr::CreateInitialBattlegrounds(), Player::DeleteFromDB(), character_commandscript::GetDeletedCharacterInfoList(), World::GetGlobalPlayerGUID(), account_commandscript::HandleAccountOnlineListCommand(), ban_commandscript::HandleBanInfoCharacterCommand(), ban_commandscript::HandleBanListHelper(), WorldSession::HandleCharFactionOrRaceChangeCallback(), WorldSession::HandleCharRenameCallBack(), gobject_commandscript::HandleGameObjectNearCommand(), gobject_commandscript::HandleGameObjectTargetCommand(), misc_commandscript::HandleGearStatsCommand(), list_commandscript::HandleListCreatureCommand(), list_commandscript::HandleListItemCommand(), list_commandscript::HandleListObjectCommand(), WorldSession::HandleLoadPetFromDBFirstCallback(), misc_commandscript::HandleMuteInfoHelper(), npc_commandscript::HandleNpcNearCommand(), WorldSession::HandleOpenWrappedItemCallback(), misc_commandscript::HandlePInfoCommand(), WorldSession::HandleStableSwapPetCallback(), WorldSession::HandleUnstablePetCallback(), wp_commandscript::HandleWpEventCommand(), wp_commandscript::HandleWpModifyCommand(), wp_commandscript::HandleWpShowCommand(), Player::LeaveAllArenaTeams(), WaypointMgr::Load(), DBCDatabaseLoader::Load(), ObjectMgr::LoadAccessRequirements(), AchievementGlobalMgr::LoadAchievementCriteriaData(), ObjectMgr::LoadAcoreStrings(), ObjectMgr::LoadAreaTriggers(), ObjectMgr::LoadAreaTriggerScripts(), ObjectMgr::LoadAreaTriggerTeleports(), ArenaTeam::LoadArenaTeamFromDB(), AuctionHouseMgr::LoadAuctionItems(), Guild::LoadBankEventLogFromDB(), BattlegroundMgr::LoadBattleMastersEntry(), ObjectMgr::LoadBroadcastTextLocales(), ObjectMgr::LoadBroadcastTexts(), RealmList::LoadBuildInfo(), ChannelMgr::LoadChannels(), InstanceSaveMgr::LoadCharacterBinds(), ConditionMgr::LoadConditions(), Map::LoadCorpseData(), Corpse::LoadCorpseFromDB(), ObjectMgr::LoadCreatureAddons(), FormationMgr::LoadCreatureFormations(), ObjectMgr::LoadCreatureLocales(), ObjectMgr::LoadCreatureModelInfo(), ObjectMgr::LoadCreatureQuestItems(), ObjectMgr::LoadCreatures(), ObjectMgr::LoadCreatureTemplate(), ObjectMgr::LoadCreatureTemplateAddons(), ObjectMgr::LoadCreatureTemplateResistances(), ObjectMgr::LoadCreatureTemplateSpells(), CreatureTextMgr::LoadCreatureTextLocales(), CreatureTextMgr::LoadCreatureTexts(), World::LoadDBVersion(), DisableMgr::LoadDisables(), ObjectMgr::LoadEquipmentTemplates(), ObjectMgr::LoadFactionChangeAchievements(), ObjectMgr::LoadFactionChangeItems(), ObjectMgr::LoadFactionChangeQuests(), ObjectMgr::LoadFactionChangeReputations(), ObjectMgr::LoadFactionChangeSpells(), ObjectMgr::LoadFactionChangeTitles(), ObjectMgr::LoadFishingBaseSkillLevel(), AddonMgr::LoadFromDB(), SmartWaypointMgr::LoadFromDB(), CalendarMgr::LoadFromDB(), GameEventMgr::LoadFromDB(), PoolMgr::LoadFromDB(), AuctionEntry::LoadFromDB(), Guild::Member::LoadFromDB(), Guild::RankInfo::LoadFromDB(), Guild::LoadFromDB(), GmTicket::LoadFromDB(), Player::LoadFromDB(), Item::LoadFromDB(), AchievementMgr::LoadFromDB(), ObjectMgr::LoadGameObjectAddons(), ObjectMgr::LoadGameObjectLocales(), ObjectMgr::LoadGameObjectQuestItems(), ObjectMgr::LoadGameobjects(), ObjectMgr::LoadGameObjectTemplate(), ObjectMgr::LoadGameObjectTemplateAddons(), ObjectMgr::LoadGameTele(), World::LoadGlobalPlayerDataStore(), ObjectMgr::LoadGossipMenu(), ObjectMgr::LoadGossipMenuItems(), ObjectMgr::LoadGossipText(), Graveyard::LoadGraveyardFromDB(), Graveyard::LoadGraveyardZones(), Group::LoadGroupFromDB(), GuildMgr::LoadGuilds(), GameEventMgr::LoadHolidayDates(), ObjectMgr::LoadInstanceEncounters(), InstanceSaveMgr::LoadInstanceSaves(), Guild::BankTab::LoadItemFromDB(), ObjectMgr::LoadItemLocales(), ObjectMgr::LoadItemSetNameLocales(), ObjectMgr::LoadItemSetNames(), ObjectMgr::LoadItemTemplates(), lfg::LFGMgr::LoadLFGDungeons(), ObjectMgr::LoadLinkedRespawn(), LootStore::LoadLootTable(), ObjectMgr::LoadMailLevelRewards(), ArenaTeam::LoadMembersFromDB(), ObjectMgr::LoadNPCSpellClickSpells(), ObjectMgr::LoadNpcTextLocales(), ObjectMgr::LoadPageTextLocales(), ObjectMgr::LoadPageTexts(), ObjectMgr::LoadPetLevelInfo(), ObjectMgr::LoadPetNames(), ObjectMgr::LoadPetNumber(), ObjectMgr::LoadPlayerInfo(), ObjectMgr::LoadPointOfInterestLocales(), ObjectMgr::LoadPointsOfInterest(), ObjectMgr::LoadQuestAreaTriggers(), ObjectMgr::LoadQuestLocales(), ObjectMgr::LoadQuestMoneyRewards(), ObjectMgr::LoadQuestOfferRewardLocale(), ObjectMgr::LoadQuestPOI(), ObjectMgr::LoadQuestRequestItemsLocale(), ObjectMgr::LoadQuests(), Quest::LoadQuestTemplateAddon(), LoadRandomEnchantmentsTable(), LoadRealmInfo(), ObjectMgr::LoadReferenceVendor(), ObjectMgr::LoadReputationOnKill(), ObjectMgr::LoadReputationRewardRate(), InstanceSaveMgr::LoadResetTimes(), Map::LoadRespawnTimes(), AccountInfo::LoadResult(), AchievementGlobalMgr::LoadRewardLocales(), AchievementGlobalMgr::LoadRewards(), lfg::LFGMgr::LoadRewards(), ObjectMgr::LoadScripts(), SystemMgr::LoadScriptWaypoints(), LoadSkillDiscoveryTable(), LoadSkillExtraItemTable(), LoadSkillPerfectItemTable(), SmartAIMgr::LoadSmartAIFromDB(), SpellMgr::LoadSpellAreas(), SpellMgr::LoadSpellBonusess(), SpellMgr::LoadSpellCustomAttr(), SpellMgr::LoadSpellEnchantProcData(), SpellMgr::LoadSpellGroups(), SpellMgr::LoadSpellGroupStackRules(), SpellMgr::LoadSpellMixology(), SpellMgr::LoadSpellPetAuras(), SpellMgr::LoadSpellProcEvents(), SpellMgr::LoadSpellProcs(), SpellMgr::LoadSpellRanks(), SpellMgr::LoadSpellRequired(), SpellMgr::LoadSpellTargetPositions(), SpellMgr::LoadSpellThreats(), ObjectMgr::LoadTavernAreaTriggers(), ObjectMgr::LoadTempSummons(), ObjectMgr::LoadTrainerSpell(), TransportMgr::LoadTransportTemplates(), ObjectMgr::LoadVehicleAccessories(), ObjectMgr::LoadVehicleTemplateAccessories(), ObjectMgr::LoadVendors(), WardenCheckMgr::LoadWardenChecks(), ObjectMgr::LoadWaypointScripts(), WeatherMgr::LoadWeatherData(), World::LoadWorldStates(), lookup_commandscript::LookupPlayerSearchCommand(), Quest::Quest(), AuthSession::RealmListCallback(), WaypointMgr::ReloadPath(), Pet::resetTalentsForAllPetsOf(), ObjectMgr::ReturnOrDeleteOldMails(), TransportMgr::SpawnContinentTransports(), StoreGUID(), Pet::TryLoadFromDB(), and RealmList::UpdateRealms().
GetUInt64()
uint64 Field::GetUInt64 () const
Definition at line 141 of file Field.cpp.
 {
     if (!data.value)
         return 0;
 #ifdef ACORE_STRICT_DATABASE_TYPE_CHECKS
     if (!IsType(DatabaseFieldTypes::Int64))
     {
         LogWrongType(__FUNCTION__);
         return 0;
     }
 #endif
     if (data.raw)
         return *reinterpret_cast<uint64 const*>(data.value);
     return static_cast<uint64>(strtoull(data.value, nullptr, 10));
 }
References const, Int64, IsType(), LogWrongType(), and strtoull.
Referenced by Player::_LoadEquipmentSets(), AccountInfo::AccountInfo(), Battleground::EndBattleground(), ban_commandscript::HandleBanInfoHelper(), ban_commandscript::HandleBanInfoIPCommand(), misc_commandscript::HandlePInfoCommand(), CalendarMgr::LoadFromDB(), GameEventMgr::LoadFromDB(), Guild::LoadFromDB(), and UpdateFetcher::ReceiveAppliedFiles().
GetUInt8()
uint8 Field::GetUInt8 () const
Definition at line 33 of file Field.cpp.
 {
     if (!data.value)
         return 0;
 #ifdef ACORE_STRICT_DATABASE_TYPE_CHECKS
     if (!IsType(DatabaseFieldTypes::Int8))
     {
         LogWrongType(__FUNCTION__);
         return 0;
     }
 #endif
     if (data.raw)
         return *reinterpret_cast<uint8 const*>(data.value);
     return static_cast<uint8>(strtoul(data.value, nullptr, 10));
 }
References const, Int8, IsType(), LogWrongType(), and strtoul().
Referenced by Player::_LoadActions(), Pet::_LoadAuras(), Player::_LoadAuras(), Player::_LoadEquipmentSets(), lfg::LFGMgr::_LoadFromDB(), Player::_LoadGlyphs(), Player::_LoadInventory(), Player::_LoadMail(), Player::_LoadQuestStatus(), AccountInfo::AccountInfo(), Player::BuildEnumData(), BattlegroundMgr::CreateInitialBattlegrounds(), Player::DeleteFromDB(), account_commandscript::HandleAccountOnlineListCommand(), gm_commandscript::HandleGMListFullCommand(), list_commandscript::HandleListItemCommand(), WorldSession::HandleLoadPetFromDBFirstCallback(), misc_commandscript::HandlePInfoCommand(), WorldSession::HandleStablePetCallback(), WorldSession::HandleStableSwapPetCallback(), GameEventMgr::Initialize(), OutdoorPvPMgr::InitOutdoorPvP(), ObjectMgr::LoadAccessRequirements(), WorldSession::LoadAccountData(), AchievementGlobalMgr::LoadAchievementCriteriaData(), ArenaTeam::LoadArenaTeamFromDB(), World::LoadAutobroadcasts(), Guild::LoadBankEventLogFromDB(), Guild::LoadBankItemFromDB(), Guild::LoadBankTabFromDB(), Acore::Impl::ChatCommands::ChatCommandNode::LoadCommandMap(), ConditionMgr::LoadConditions(), ObjectMgr::LoadCreatureClassLevelStats(), ObjectMgr::LoadCreatureModelInfo(), ObjectMgr::LoadCreatures(), ObjectMgr::LoadCreatureTemplate(), ObjectMgr::LoadCreatureTemplateResistances(), ObjectMgr::LoadCreatureTemplateSpells(), CreatureTextMgr::LoadCreatureTextLocales(), CreatureTextMgr::LoadCreatureTexts(), DisableMgr::LoadDisables(), ObjectMgr::LoadEquipmentTemplates(), ObjectMgr::LoadExplorationBaseXP(), GameEventMgr::LoadFromDB(), AuctionEntry::LoadFromDB(), EmblemInfo::LoadFromDB(), Guild::RankInfo::LoadFromDB(), Player::LoadFromDB(), SocialMgr::LoadFromDB(), ObjectMgr::LoadGameobjects(), ObjectMgr::LoadGossipMenuItems(), ObjectMgr::LoadGossipText(), Group::LoadGroupFromDB(), GameEventMgr::LoadHolidayDates(), ObjectMgr::LoadInstanceEncounters(), InstanceSaveMgr::LoadInstanceSaves(), Guild::BankTab::LoadItemFromDB(), ObjectMgr::LoadItemSetNames(), ObjectMgr::LoadLinkedRespawn(), LootStore::LoadLootTable(), ObjectMgr::LoadMailLevelRewards(), ArenaTeam::LoadMembersFromDB(), ObjectMgr::LoadNPCSpellClickSpells(), ObjectMgr::LoadPetLevelInfo(), ObjectMgr::LoadPlayerInfo(), Quest::LoadQuestTemplateAddon(), LoadRealmInfo(), ObjectMgr::LoadReferenceVendor(), ObjectMgr::LoadReputationOnKill(), ObjectMgr::LoadReputationSpilloverTemplate(), AccountInfo::LoadResult(), lfg::LFGMgr::LoadRewards(), ObjectMgr::LoadScripts(), SmartAIMgr::LoadSmartAIFromDB(), SpellMgr::LoadSpellLinked(), SpellMgr::LoadSpellPetAuras(), SpellMgr::LoadSpellRanks(), ObjectMgr::LoadTempSummons(), ObjectMgr::LoadTrainerSpell(), ObjectMgr::LoadVehicleAccessories(), ObjectMgr::LoadVehicleTemplateAccessories(), ObjectMgr::LoadVendors(), WardenCheckMgr::LoadWardenChecks(), WardenCheckMgr::LoadWardenOverrides(), Quest::Quest(), AuthSession::RealmListCallback(), WaypointMgr::ReloadPath(), ObjectMgr::ReturnOrDeleteOldMails(), GameEventMgr::StartArenaSeason(), and RealmList::UpdateRealms().
IsNull()
bool Field::IsNull () const inline
Definition at line 120 of file Field.h.
     {
         return data.value == nullptr;
     }
Referenced by account_commandscript::HandleAccount2FARemoveCommand(), and ObjectMgr::LoadAccessRequirements().
IsNumeric()
bool Field::IsNumeric () const protected
Definition at line 290 of file Field.cpp.
 {
     return (meta->Type == DatabaseFieldTypes::Int8 ||
         meta->Type == DatabaseFieldTypes::Int16 ||
         meta->Type == DatabaseFieldTypes::Int32 ||
         meta->Type == DatabaseFieldTypes::Int64 ||
         meta->Type == DatabaseFieldTypes::Float ||
         meta->Type == DatabaseFieldTypes::Double);
 }
References Double, Float, Int16, Int32, Int64, Int8, meta, and QueryResultFieldMetadata::Type.
Referenced by GetCString().
IsType()
bool Field::IsType (DatabaseFieldTypes type) const protected
Definition at line 285 of file Field.cpp.
 {
     return meta->Type == type;
 }
References meta, and QueryResultFieldMetadata::Type.
Referenced by GetDouble(), GetFloat(), GetInt16(), GetInt32(), GetInt64(), GetInt8(), GetUInt16(), GetUInt32(), GetUInt64(), and GetUInt8().
LogWrongType()
void Field::LogWrongType (char const * getter) const private
Definition at line 300 of file Field.cpp.
 {
     LOG_WARN("sql.sql", "Warning: %s on %s field %s.%s (%s.%s) at index %u.",
         getter, meta->TypeName, meta->TableAlias, meta->Alias, meta->TableName, meta->Name, meta->Index);
 }
References QueryResultFieldMetadata::Alias, QueryResultFieldMetadata::Index, LOG_WARN, meta, QueryResultFieldMetadata::Name, QueryResultFieldMetadata::TableAlias, QueryResultFieldMetadata::TableName, and QueryResultFieldMetadata::TypeName.
Referenced by GetCString(), GetDouble(), GetFloat(), GetInt16(), GetInt32(), GetInt64(), GetInt8(), GetUInt16(), GetUInt32(), GetUInt64(), and GetUInt8().
SetByteValue()
void Field::SetByteValue (char const * newValue, uint32 length) protected
Definition at line 269 of file Field.cpp.
 {
     // This value stores raw bytes that have to be explicitly cast later
     data.value = newValue;
     data.length = length;
     data.raw = true;
 }
References length.
SetMetadata()
void Field::SetMetadata (QueryResultFieldMetadata const * fieldMeta) private
Definition at line 306 of file Field.cpp.
 {
     meta = fieldMeta;
 }
References meta.
Referenced by ResultSet::ResultSet().
SetStructuredValue()
void Field::SetStructuredValue (char const * newValue, uint32 length) protected
Definition at line 277 of file Field.cpp.
 {
     // This value stores somewhat structured data that needs function style casting
     data.value = newValue;
     data.length = length;
     data.raw = false;
 }
References length.
Friends And Related Function Documentation
PreparedResultSet
friend class PreparedResultSet friend
Definition at line 86 of file Field.h.
ResultSet
friend class ResultSet friend
Definition at line 85 of file Field.h.
Member Data Documentation
struct { ... } Field::data
length
uint32 Field::length
Definition at line 131 of file Field.h.
Referenced by GetBinarySizeChecked(), SetByteValue(), and SetStructuredValue().
meta
QueryResultFieldMetadata const* Field::meta private
Definition at line 141 of file Field.h.
Referenced by Field(), IsNumeric(), IsType(), LogWrongType(), and SetMetadata().
raw
bool Field::raw
Definition at line 132 of file Field.h.
value
char const* Field::value
Definition at line 130 of file Field.h.
The documentation for this class was generated from the following files:
src/server/database/Database/Field.h
src/server/database/Database/Field.cpp