Azerotcore-wotlk: achievement_yogg_saron_kiss_and_make_up Class Reference
achievement_yogg_saron_kiss_and_make_up Class Reference
Public Member Functions
achievement_yogg_saron_kiss_and_make_up ()
bool OnCheck (Player *, Unit *target, uint32) override
Public Member Functions inherited from AchievementCriteriaScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AchievementCriteriaScript
AchievementCriteriaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 3050 of file boss_yoggsaron.cpp.
Constructor & Destructor Documentation
achievement_yogg_saron_kiss_and_make_up()
achievement_yogg_saron_kiss_and_make_up::achievement_yogg_saron_kiss_and_make_up () inline
Definition at line 3053 of file boss_yoggsaron.cpp.
 : AchievementCriteriaScript("achievement_yogg_saron_kiss_and_make_up") {}
Member Function Documentation
OnCheck()
bool achievement_yogg_saron_kiss_and_make_up::OnCheck (Player * , Unit * target, uint32) inline override virtual
Reimplemented from AchievementCriteriaScript.
Definition at line 3055 of file boss_yoggsaron.cpp.
     {
         return target && target->GetEntry() == NPC_SARA && target->GetAI() && target->GetAI()->GetData(DATA_GET_SARA_PHASE);
     }
References DATA_GET_SARA_PHASE, Unit::GetAI(), UnitAI::GetData(), Object::GetEntry(), and NPC_SARA.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_yoggsaron.cpp