Azerotcore-wotlk: deps/SFMT/SFMT-common.h File Reference
SFMT-common.h File Reference
SIMD oriented Fast Mersenne Twister(SFMT) pseudorandom number generator with jump function. This file includes common functions used in random number generation and jump.
#include "SFMT.h"
Macros
#define SFMT_COMMON_H
Functions
static void do_recursion (w128_t *r, w128_t *a, w128_t *b, w128_t *c, w128_t *d)
static void rshift128 (w128_t *out, w128_t const *in, int shift)
static void lshift128 (w128_t *out, w128_t const *in, int shift)
Detailed Description
SIMD oriented Fast Mersenne Twister(SFMT) pseudorandom number generator with jump function. This file includes common functions used in random number generation and jump.
Author
Mutsuo Saito (Hiroshima University)
Makoto Matsumoto (The University of Tokyo)
Copyright (C) 2006, 2007 Mutsuo Saito, Makoto Matsumoto and Hiroshima University. Copyright (C) 2012 Mutsuo Saito, Makoto Matsumoto, Hiroshima University and The University of Tokyo. All rights reserved.
The 3-clause BSD License is applied to this software, see LICENSE.txt
Definition in file SFMT-common.h.
Macro Definition Documentation
SFMT_COMMON_H
#define SFMT_COMMON_H
Definition at line 22 of file SFMT-common.h.
Function Documentation
do_recursion()
static void do_recursion (w128_t * r, w128_t * a, w128_t * b, w128_t * c, w128_t * d) inline static
This function represents the recursion formula.
Parameters
r output
a a 128-bit part of the internal state array
b a 128-bit part of the internal state array
c a 128-bit part of the internal state array
d a 128-bit part of the internal state array
Definition at line 142 of file SFMT-common.h.
 {
     w128_t x;
     w128_t y;
     lshift128(&x, a, SFMT_SL2);
     rshift128(&y, c, SFMT_SR2);
     r->u[0] = a->u[0] ^ x.u[0] ^ ((b->u[0] >> SFMT_SR1) & SFMT_MSK1)
         ^ y.u[0] ^ (d->u[0] << SFMT_SL1);
     r->u[1] = a->u[1] ^ x.u[1] ^ ((b->u[1] >> SFMT_SR1) & SFMT_MSK2)
         ^ y.u[1] ^ (d->u[1] << SFMT_SL1);
     r->u[2] = a->u[2] ^ x.u[2] ^ ((b->u[2] >> SFMT_SR1) & SFMT_MSK3)
         ^ y.u[2] ^ (d->u[2] << SFMT_SL1);
     r->u[3] = a->u[3] ^ x.u[3] ^ ((b->u[3] >> SFMT_SR1) & SFMT_MSK4)
         ^ y.u[3] ^ (d->u[3] << SFMT_SL1);
 }
References mpq::a, b, mpq::c, mpq::d, lshift128(), rshift128(), SFMT_MSK1, SFMT_MSK2, SFMT_MSK3, SFMT_MSK4, SFMT_SL1, SFMT_SL2, SFMT_SR1, SFMT_SR2, W128_T::u, G3D::x, and G3D::y.
Referenced by gen_rand_array(), and sfmt_gen_rand_all().
lshift128()
static void lshift128 (w128_t * out, w128_t const * in, int shift) inline static
This function simulates SIMD 128-bit left shift by the standard C. The 128-bit integer given in in is shifted by (shift * 8) bits. This function simulates the LITTLE ENDIAN SIMD.
Parameters
out the output of this function
in the 128-bit data to be shifted
shift the shift value
Definition at line 100 of file SFMT-common.h.
 {
     uint64_t th, tl, oh, ol;
     th = ((uint64_t)in->u[3] << 32) | ((uint64_t)in->u[2]);
     tl = ((uint64_t)in->u[1] << 32) | ((uint64_t)in->u[0]);
     oh = th << (shift * 8);
     ol = tl << (shift * 8);
     oh |= tl >> (64 - shift * 8);
     out->u[1] = (uint32_t)(ol >> 32);
     out->u[0] = (uint32_t)ol;
     out->u[3] = (uint32_t)(oh >> 32);
     out->u[2] = (uint32_t)oh;
 }
References W128_T::u.
Referenced by do_recursion().
rshift128()
static void rshift128 (w128_t * out, w128_t const * in, int shift) inline static
This function simulates SIMD 128-bit right shift by the standard C. The 128-bit integer given in in is shifted by (shift * 8) bits. This function simulates the LITTLE ENDIAN SIMD.
Parameters
out the output of this function
in the 128-bit data to be shifted
shift the shift value
Definition at line 60 of file SFMT-common.h.
 {
     uint64_t th, tl, oh, ol;
     th = ((uint64_t)in->u[3] << 32) | ((uint64_t)in->u[2]);
     tl = ((uint64_t)in->u[1] << 32) | ((uint64_t)in->u[0]);
     oh = th >> (shift * 8);
     ol = tl >> (shift * 8);
     ol |= th << (64 - shift * 8);
     out->u[1] = (uint32_t)(ol >> 32);
     out->u[0] = (uint32_t)ol;
     out->u[3] = (uint32_t)(oh >> 32);
     out->u[2] = (uint32_t)oh;
 }
References W128_T::u.
Referenced by do_recursion().