Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/witness.h File Reference
witness.h File Reference
#include "jemalloc/internal/ql.h"
Classes
struct witness_s
struct witness_tsd_s
struct witness_tsdn_s
Macros
#define WITNESS_RANK_OMIT 0U
#define WITNESS_RANK_MIN 1U
#define WITNESS_RANK_INIT 1U
#define WITNESS_RANK_CTL 1U
#define WITNESS_RANK_TCACHES 2U
#define WITNESS_RANK_ARENAS 3U
#define WITNESS_RANK_BACKGROUND_THREAD_GLOBAL 4U
#define WITNESS_RANK_PROF_DUMP 5U
#define WITNESS_RANK_PROF_BT2GCTX 6U
#define WITNESS_RANK_PROF_TDATAS 7U
#define WITNESS_RANK_PROF_TDATA 8U
#define WITNESS_RANK_PROF_LOG 9U
#define WITNESS_RANK_PROF_GCTX 10U
#define WITNESS_RANK_BACKGROUND_THREAD 11U
#define WITNESS_RANK_CORE 12U
#define WITNESS_RANK_DECAY 12U
#define WITNESS_RANK_TCACHE_QL 13U
#define WITNESS_RANK_EXTENT_GROW 14U
#define WITNESS_RANK_EXTENTS 15U
#define WITNESS_RANK_EXTENT_AVAIL 16U
#define WITNESS_RANK_EXTENT_POOL 17U
#define WITNESS_RANK_RTREE 18U
#define WITNESS_RANK_BASE 19U
#define WITNESS_RANK_ARENA_LARGE 20U
#define WITNESS_RANK_HOOK 21U
#define WITNESS_RANK_LEAF 0xffffffffU
#define WITNESS_RANK_BIN WITNESS_RANK_LEAF
#define WITNESS_RANK_ARENA_STATS WITNESS_RANK_LEAF
#define WITNESS_RANK_DSS WITNESS_RANK_LEAF
#define WITNESS_RANK_PROF_ACTIVE WITNESS_RANK_LEAF
#define WITNESS_RANK_PROF_ACCUM WITNESS_RANK_LEAF
#define WITNESS_RANK_PROF_DUMP_SEQ WITNESS_RANK_LEAF
#define WITNESS_RANK_PROF_GDUMP WITNESS_RANK_LEAF
#define WITNESS_RANK_PROF_NEXT_THR_UID WITNESS_RANK_LEAF
#define WITNESS_RANK_PROF_THREAD_ACTIVE_INIT WITNESS_RANK_LEAF
#define WITNESS_INITIALIZER(name, rank)
#define WITNESS_TSD_INITIALIZER { ql_head_initializer(witnesses), false }
#define WITNESS_TSDN_NULL ((witness_tsdn_t *)0)
Typedefs
typedef struct witness_s witness_t
typedef unsigned witness_rank_t
typedef int witness_comp_t(const witness_t *, void *, const witness_t *, void *)
typedef struct witness_tsd_s witness_tsd_t
typedef struct witness_tsdn_s witness_tsdn_t
typedef void() witness_lock_error_t(const witness_list_t *, const witness_t *)
typedef void() witness_owner_error_t(const witness_t *)
typedef void() witness_not_owner_error_t(const witness_t *)
typedef void() witness_depth_error_t(const witness_list_t *, witness_rank_t rank_inclusive, unsigned depth)
Functions
typedef ql_head (witness_t) witness_list_t
JEMALLOC_ALWAYS_INLINE witness_tsdn_t * witness_tsd_tsdn (witness_tsd_t *witness_tsd)
JEMALLOC_ALWAYS_INLINE bool witness_tsdn_null (witness_tsdn_t *witness_tsdn)
JEMALLOC_ALWAYS_INLINE witness_tsd_t * witness_tsdn_tsd (witness_tsdn_t *witness_tsdn)
void witness_init (witness_t *witness, const char *name, witness_rank_t rank, witness_comp_t *comp, void *opaque)
void witnesses_cleanup (witness_tsd_t *witness_tsd)
void witness_prefork (witness_tsd_t *witness_tsd)
void witness_postfork_parent (witness_tsd_t *witness_tsd)
void witness_postfork_child (witness_tsd_t *witness_tsd)
static bool witness_owner (witness_tsd_t *witness_tsd, const witness_t *witness)
static void witness_assert_owner (witness_tsdn_t *witness_tsdn, const witness_t *witness)
static void witness_assert_not_owner (witness_tsdn_t *witness_tsdn, const witness_t *witness)
static void witness_assert_depth_to_rank (witness_tsdn_t *witness_tsdn, witness_rank_t rank_inclusive, unsigned depth)
static void witness_assert_depth (witness_tsdn_t *witness_tsdn, unsigned depth)
static void witness_assert_lockless (witness_tsdn_t *witness_tsdn)
static void witness_lock (witness_tsdn_t *witness_tsdn, witness_t *witness)
static void witness_unlock (witness_tsdn_t *witness_tsdn, witness_t *witness)
Variables
witness_lock_error_t *JET_MUTABLE witness_lock_error
witness_owner_error_t *JET_MUTABLE witness_owner_error
witness_not_owner_error_t *JET_MUTABLE witness_not_owner_error
witness_depth_error_t *JET_MUTABLE witness_depth_error
Macro Definition Documentation
WITNESS_INITIALIZER
#define WITNESS_INITIALIZER (name, rank)
Definition at line 71 of file witness.h.
WITNESS_RANK_ARENA_LARGE
#define WITNESS_RANK_ARENA_LARGE 20U
Definition at line 51 of file witness.h.
WITNESS_RANK_ARENA_STATS
#define WITNESS_RANK_ARENA_STATS WITNESS_RANK_LEAF
Definition at line 56 of file witness.h.
WITNESS_RANK_ARENAS
#define WITNESS_RANK_ARENAS 3U
Definition at line 22 of file witness.h.
WITNESS_RANK_BACKGROUND_THREAD
#define WITNESS_RANK_BACKGROUND_THREAD 11U
Definition at line 32 of file witness.h.
WITNESS_RANK_BACKGROUND_THREAD_GLOBAL
#define WITNESS_RANK_BACKGROUND_THREAD_GLOBAL 4U
Definition at line 24 of file witness.h.
WITNESS_RANK_BASE
#define WITNESS_RANK_BASE 19U
Definition at line 50 of file witness.h.
WITNESS_RANK_BIN
#define WITNESS_RANK_BIN WITNESS_RANK_LEAF
Definition at line 55 of file witness.h.
WITNESS_RANK_CORE
#define WITNESS_RANK_CORE 12U
Definition at line 40 of file witness.h.
WITNESS_RANK_CTL
#define WITNESS_RANK_CTL 1U
Definition at line 20 of file witness.h.
WITNESS_RANK_DECAY
#define WITNESS_RANK_DECAY 12U
Definition at line 42 of file witness.h.
WITNESS_RANK_DSS
#define WITNESS_RANK_DSS WITNESS_RANK_LEAF
Definition at line 57 of file witness.h.
WITNESS_RANK_EXTENT_AVAIL
#define WITNESS_RANK_EXTENT_AVAIL 16U
Definition at line 46 of file witness.h.
WITNESS_RANK_EXTENT_GROW
#define WITNESS_RANK_EXTENT_GROW 14U
Definition at line 44 of file witness.h.
WITNESS_RANK_EXTENT_POOL
#define WITNESS_RANK_EXTENT_POOL 17U
Definition at line 48 of file witness.h.
WITNESS_RANK_EXTENTS
#define WITNESS_RANK_EXTENTS 15U
Definition at line 45 of file witness.h.
WITNESS_RANK_HOOK
#define WITNESS_RANK_HOOK 21U
Definition at line 52 of file witness.h.
WITNESS_RANK_INIT
#define WITNESS_RANK_INIT 1U
Definition at line 19 of file witness.h.
WITNESS_RANK_LEAF
#define WITNESS_RANK_LEAF 0xffffffffU
Definition at line 54 of file witness.h.
WITNESS_RANK_MIN
#define WITNESS_RANK_MIN 1U
Definition at line 17 of file witness.h.
WITNESS_RANK_OMIT
#define WITNESS_RANK_OMIT 0U
Definition at line 15 of file witness.h.
WITNESS_RANK_PROF_ACCUM
#define WITNESS_RANK_PROF_ACCUM WITNESS_RANK_LEAF
Definition at line 59 of file witness.h.
WITNESS_RANK_PROF_ACTIVE
#define WITNESS_RANK_PROF_ACTIVE WITNESS_RANK_LEAF
Definition at line 58 of file witness.h.
WITNESS_RANK_PROF_BT2GCTX
#define WITNESS_RANK_PROF_BT2GCTX 6U
Definition at line 27 of file witness.h.
WITNESS_RANK_PROF_DUMP
#define WITNESS_RANK_PROF_DUMP 5U
Definition at line 26 of file witness.h.
WITNESS_RANK_PROF_DUMP_SEQ
#define WITNESS_RANK_PROF_DUMP_SEQ WITNESS_RANK_LEAF
Definition at line 60 of file witness.h.
WITNESS_RANK_PROF_GCTX
#define WITNESS_RANK_PROF_GCTX 10U
Definition at line 31 of file witness.h.
WITNESS_RANK_PROF_GDUMP
#define WITNESS_RANK_PROF_GDUMP WITNESS_RANK_LEAF
Definition at line 61 of file witness.h.
WITNESS_RANK_PROF_LOG
#define WITNESS_RANK_PROF_LOG 9U
Definition at line 30 of file witness.h.
WITNESS_RANK_PROF_NEXT_THR_UID
#define WITNESS_RANK_PROF_NEXT_THR_UID WITNESS_RANK_LEAF
Definition at line 62 of file witness.h.
WITNESS_RANK_PROF_TDATA
#define WITNESS_RANK_PROF_TDATA 8U
Definition at line 29 of file witness.h.
WITNESS_RANK_PROF_TDATAS
#define WITNESS_RANK_PROF_TDATAS 7U
Definition at line 28 of file witness.h.
WITNESS_RANK_PROF_THREAD_ACTIVE_INIT
#define WITNESS_RANK_PROF_THREAD_ACTIVE_INIT WITNESS_RANK_LEAF
Definition at line 63 of file witness.h.
WITNESS_RANK_RTREE
#define WITNESS_RANK_RTREE 18U
Definition at line 49 of file witness.h.
WITNESS_RANK_TCACHE_QL
#define WITNESS_RANK_TCACHE_QL 13U
Definition at line 43 of file witness.h.
WITNESS_RANK_TCACHES
#define WITNESS_RANK_TCACHES 2U
Definition at line 21 of file witness.h.
WITNESS_TSD_INITIALIZER
#define WITNESS_TSD_INITIALIZER { ql_head_initializer(witnesses), false }
Definition at line 113 of file witness.h.
WITNESS_TSDN_NULL
#define WITNESS_TSDN_NULL ((witness_tsdn_t *)0)
Definition at line 114 of file witness.h.
Typedef Documentation
witness_comp_t
typedef int witness_comp_t(const witness_t *, void *, const witness_t *, void *)
Definition at line 77 of file witness.h.
witness_depth_error_t
typedef void() witness_depth_error_t(const witness_list_t *, witness_rank_t rank_inclusive, unsigned depth)
Definition at line 155 of file witness.h.
witness_lock_error_t
typedef void() witness_lock_error_t(const witness_list_t *, const witness_t *)
Definition at line 146 of file witness.h.
witness_not_owner_error_t
typedef void() witness_not_owner_error_t(const witness_t *)
Definition at line 152 of file witness.h.
witness_owner_error_t
typedef void() witness_owner_error_t(const witness_t *)
Definition at line 149 of file witness.h.
witness_rank_t
typedef unsigned witness_rank_t
Definition at line 75 of file witness.h.
witness_t
typedef struct witness_s witness_t
Definition at line 1 of file witness.h.
witness_tsd_t
typedef struct witness_tsd_s witness_tsd_t
Definition at line 77 of file witness.h.
witness_tsdn_t
typedef struct witness_tsdn_s witness_tsdn_t
Definition at line 77 of file witness.h.
Function Documentation
ql_head()
typedef ql_head (witness_t)
witness_assert_depth()
static void witness_assert_depth (witness_tsdn_t * witness_tsdn, unsigned depth) inline static
Definition at line 265 of file witness.h.
{
     witness_assert_depth_to_rank(witness_tsdn, WITNESS_RANK_MIN, depth);
 }
References witness_assert_depth_to_rank(), and WITNESS_RANK_MIN.
Referenced by tcaches_create(), and witness_assert_lockless().
witness_assert_depth_to_rank()
static void witness_assert_depth_to_rank (witness_tsdn_t * witness_tsdn, witness_rank_t rank_inclusive, unsigned depth) inline static
Definition at line 232 of file witness.h.
{
     witness_tsd_t *witness_tsd;
     unsigned d;
     witness_list_t *witnesses;
     witness_t *w;
     if (!config_debug) {
         return;
     }
     if (witness_tsdn_null(witness_tsdn)) {
         return;
     }
     witness_tsd = witness_tsdn_tsd(witness_tsdn);
     d = 0;
     witnesses = &witness_tsd->witnesses;
     w = ql_last(witnesses, link);
     if (w != NULL) {
         ql_reverse_foreach(w, witnesses, link) {
             if (w->rank < rank_inclusive) {
                 break;
             }
             d++;
         }
     }
     if (d != depth) {
         witness_depth_error(witnesses, rank_inclusive, depth);
     }
 }
References config_debug, mpq::d, NULL, ql_last, ql_reverse_foreach, witness_s::rank, witness_depth_error, witness_tsdn_null(), witness_tsdn_tsd(), and witness_tsd_s::witnesses.
Referenced by arena_decay_to_limit(), arena_extent_alloc_large(), arena_extents_dirty_dalloc(), arena_slab_alloc(), arena_slab_alloc_hard(), arena_stash_decayed(), extent_alloc_wrapper(), extent_commit_impl(), extent_dalloc_gap(), extent_dalloc_wrapper(), extent_dalloc_wrapper_try(), extent_decommit_wrapper(), extent_destroy_wrapper(), extent_gdump_add(), extent_merge_impl(), extent_purge_forced_impl(), extent_purge_lazy_impl(), extent_recycle(), extent_recycle_extract(), extent_split_impl(), extents_alloc(), extents_dalloc(), iallocztm(), idalloctm(), ipallocztm(), iralloct(), iralloct_realign(), isdalloct(), ixalloc(), and witness_assert_depth().
witness_assert_lockless()
static void witness_assert_lockless (witness_tsdn_t * witness_tsdn) inline static
Definition at line 270 of file witness.h.
{
     witness_assert_depth(witness_tsdn, 0);
 }
References witness_assert_depth().
Referenced by check_entry_exit_locking(), malloc_init_hard(), and witnesses_cleanup().
witness_assert_not_owner()
static void witness_assert_not_owner (witness_tsdn_t * witness_tsdn, const witness_t * witness) inline static
Definition at line 205 of file witness.h.
{
     witness_tsd_t *witness_tsd;
     witness_list_t *witnesses;
     witness_t *w;
     if (!config_debug) {
         return;
     }
     if (witness_tsdn_null(witness_tsdn)) {
         return;
     }
     witness_tsd = witness_tsdn_tsd(witness_tsdn);
     if (witness->rank == WITNESS_RANK_OMIT) {
         return;
     }
     witnesses = &witness_tsd->witnesses;
     ql_foreach(w, witnesses, link) {
         if (w == witness) {
             witness_not_owner_error(witness);
         }
     }
 }
References config_debug, ql_foreach, witness_s::rank, witness_not_owner_error, WITNESS_RANK_OMIT, witness_tsdn_null(), witness_tsdn_tsd(), and witness_tsd_s::witnesses.
Referenced by malloc_mutex_assert_not_owner(), malloc_mutex_lock(), malloc_mutex_trylock(), and witness_lock().
witness_assert_owner()
static void witness_assert_owner (witness_tsdn_t * witness_tsdn, const witness_t * witness) inline static
Definition at line 183 of file witness.h.
{
     witness_tsd_t *witness_tsd;
     if (!config_debug) {
         return;
     }
     if (witness_tsdn_null(witness_tsdn)) {
         return;
     }
     witness_tsd = witness_tsdn_tsd(witness_tsdn);
     if (witness->rank == WITNESS_RANK_OMIT) {
         return;
     }
     if (witness_owner(witness_tsd, witness)) {
         return;
     }
     witness_owner_error(witness);
 }
References config_debug, witness_s::rank, witness_owner(), witness_owner_error, WITNESS_RANK_OMIT, witness_tsdn_null(), and witness_tsdn_tsd().
Referenced by malloc_mutex_assert_owner(), and witness_unlock().
witness_init()
void witness_init (witness_t * witness, const char * name, witness_rank_t rank, witness_comp_t * comp, void * opaque)
Definition at line 9 of file witness.c.
{
     witness->name = name;
     witness->rank = rank;
     witness->comp = comp;
     witness->opaque = opaque;
 }
References witness_s::comp, witness_s::name, witness_s::opaque, and witness_s::rank.
witness_lock()
static void witness_lock (witness_tsdn_t * witness_tsdn, witness_t * witness) inline static
Definition at line 275 of file witness.h.
{
     witness_tsd_t *witness_tsd;
     witness_list_t *witnesses;
     witness_t *w;
     if (!config_debug) {
         return;
     }
     if (witness_tsdn_null(witness_tsdn)) {
         return;
     }
     witness_tsd = witness_tsdn_tsd(witness_tsdn);
     if (witness->rank == WITNESS_RANK_OMIT) {
         return;
     }
     witness_assert_not_owner(witness_tsdn, witness);
     witnesses = &witness_tsd->witnesses;
     w = ql_last(witnesses, link);
     if (w == NULL) {
         /* No other locks; do nothing. */
     } else if (witness_tsd->forking && w->rank <= witness->rank) {
         /* Forking, and relaxed ranking satisfied. */
     } else if (w->rank > witness->rank) {
         /* Not forking, rank order reversal. */
         witness_lock_error(witnesses, witness);
     } else if (w->rank == witness->rank && (w->comp == NULL || w->comp !=
         witness->comp || w->comp(w, w->opaque, witness, witness->opaque) >
         0)) {
         /*
          * Missing/incompatible comparison function, or comparison
          * function indicates rank order reversal.
          */
         witness_lock_error(witnesses, witness);
     }
     ql_elm_new(witness, link);
     ql_tail_insert(witnesses, witness, link);
 }
References witness_s::comp, config_debug, witness_tsd_s::forking, NULL, witness_s::opaque, ql_elm_new, ql_last, ql_tail_insert, witness_s::rank, witness_assert_not_owner(), witness_lock_error, WITNESS_RANK_OMIT, witness_tsdn_null(), witness_tsdn_tsd(), and witness_tsd_s::witnesses.
Referenced by malloc_mutex_lock(), and malloc_mutex_trylock().
witness_owner()
static bool witness_owner (witness_tsd_t * witness_tsd, const witness_t * witness) inline static
Definition at line 166 of file witness.h.
{
     witness_list_t *witnesses;
     witness_t *w;
     cassert(config_debug);
     witnesses = &witness_tsd->witnesses;
     ql_foreach(w, witnesses, link) {
         if (w == witness) {
             return true;
         }
     }
     return false;
 }
References cassert(), config_debug, ql_foreach, and witness_tsd_s::witnesses.
Referenced by witness_assert_owner(), and witness_unlock().
witness_postfork_child()
void witness_postfork_child (witness_tsd_t * witness_tsd)
Definition at line 89 of file witness.c.
{
     if (!config_debug) {
         return;
     }
 #ifndef JEMALLOC_MUTEX_INIT_CB
     witness_list_t *witnesses;
     witnesses = &witness_tsd->witnesses;
     ql_new(witnesses);
 #endif
     witness_tsd->forking = false;
 }
References config_debug, witness_tsd_s::forking, ql_new, and witness_tsd_s::witnesses.
witness_postfork_parent()
void witness_postfork_parent (witness_tsd_t * witness_tsd)
Definition at line 81 of file witness.c.
{
     if (!config_debug) {
         return;
     }
     witness_tsd->forking = false;
 }
References config_debug, and witness_tsd_s::forking.
witness_prefork()
void witness_prefork (witness_tsd_t * witness_tsd)
Definition at line 73 of file witness.c.
{
     if (!config_debug) {
         return;
     }
     witness_tsd->forking = true;
 }
References config_debug, and witness_tsd_s::forking.
witness_tsd_tsdn()
JEMALLOC_ALWAYS_INLINE witness_tsdn_t* witness_tsd_tsdn (witness_tsd_t * witness_tsd)
Definition at line 125 of file witness.h.
{
     return (witness_tsdn_t *)witness_tsd;
 }
Referenced by malloc_init_hard(), and witnesses_cleanup().
witness_tsdn_null()
JEMALLOC_ALWAYS_INLINE bool witness_tsdn_null (witness_tsdn_t * witness_tsdn)
Definition at line 130 of file witness.h.
{
     return witness_tsdn == NULL;
 }
References NULL.
Referenced by witness_assert_depth_to_rank(), witness_assert_not_owner(), witness_assert_owner(), witness_lock(), witness_tsdn_tsd(), and witness_unlock().
witness_tsdn_tsd()
JEMALLOC_ALWAYS_INLINE witness_tsd_t* witness_tsdn_tsd (witness_tsdn_t * witness_tsdn)
Definition at line 135 of file witness.h.
{
     assert(!witness_tsdn_null(witness_tsdn));
     return &witness_tsdn->witness_tsd;
 }
References assert(), witness_tsdn_s::witness_tsd, and witness_tsdn_null().
Referenced by witness_assert_depth_to_rank(), witness_assert_not_owner(), witness_assert_owner(), witness_lock(), and witness_unlock().
witness_unlock()
static void witness_unlock (witness_tsdn_t * witness_tsdn, witness_t * witness) inline static
Definition at line 318 of file witness.h.
{
     witness_tsd_t *witness_tsd;
     witness_list_t *witnesses;
     if (!config_debug) {
         return;
     }
     if (witness_tsdn_null(witness_tsdn)) {
         return;
     }
     witness_tsd = witness_tsdn_tsd(witness_tsdn);
     if (witness->rank == WITNESS_RANK_OMIT) {
         return;
     }
     /*
      * Check whether owner before removal, rather than relying on
      * witness_assert_owner() to abort, so that unit tests can test this
      * function's failure mode without causing undefined behavior.
      */
     if (witness_owner(witness_tsd, witness)) {
         witnesses = &witness_tsd->witnesses;
         ql_remove(witnesses, witness, link);
     } else {
         witness_assert_owner(witness_tsdn, witness);
     }
 }
References config_debug, ql_remove, witness_s::rank, witness_assert_owner(), witness_owner(), WITNESS_RANK_OMIT, witness_tsdn_null(), witness_tsdn_tsd(), and witness_tsd_s::witnesses.
Referenced by malloc_mutex_unlock().
witnesses_cleanup()
void witnesses_cleanup (witness_tsd_t * witness_tsd)
Definition at line 66 of file witness.c.
{
     witness_assert_lockless(witness_tsd_tsdn(witness_tsd));
     /* Do nothing. */
 }
References witness_assert_lockless(), and witness_tsd_tsdn().
Variable Documentation
witness_depth_error
witness_depth_error_t* JET_MUTABLE witness_depth_error extern
Definition at line 62 of file witness.c.
Referenced by witness_assert_depth_to_rank().
witness_lock_error
witness_lock_error_t* JET_MUTABLE witness_lock_error extern
Definition at line 29 of file witness.c.
Referenced by witness_lock().
witness_not_owner_error
witness_not_owner_error_t* JET_MUTABLE witness_not_owner_error extern
Definition at line 46 of file witness.c.
Referenced by witness_assert_not_owner().
witness_owner_error
witness_owner_error_t* JET_MUTABLE witness_owner_error extern
Definition at line 37 of file witness.c.
Referenced by witness_assert_owner().