Azerotcore-wotlk: npc_muradin_bronzebeard_icc Class Reference
npc_muradin_bronzebeard_icc Class Reference
Classes
struct npc_muradin_bronzebeard_iccAI
Public Member Functions
npc_muradin_bronzebeard_icc ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 780 of file boss_deathbringer_saurfang.cpp.
Constructor & Destructor Documentation
npc_muradin_bronzebeard_icc()
npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_icc () inline
Definition at line 783 of file boss_deathbringer_saurfang.cpp.
 : CreatureScript("npc_muradin_bronzebeard_icc") { }
Member Function Documentation
GetAI()
CreatureAI* npc_muradin_bronzebeard_icc::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 988 of file boss_deathbringer_saurfang.cpp.
     {
         return GetIcecrownCitadelAI<npc_muradin_bronzebeard_iccAI>(creature);
     }
OnGossipHello()
bool npc_muradin_bronzebeard_icc::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 962 of file boss_deathbringer_saurfang.cpp.
     {
         InstanceScript* instance = creature->GetInstanceScript();
         if (instance && instance->GetBossState(DATA_DEATHBRINGER_SAURFANG) != DONE && instance->GetBossState(DATA_DEATHBRINGER_SAURFANG) != IN_PROGRESS)
         {
             AddGossipItemFor(player, 0, "Let it begin...", 631, -ACTION_START_EVENT + 1);
             SendGossipMenuFor(player, DEFAULT_GOSSIP_MESSAGE, creature->GetGUID());
         }
         return true;
     }
References ACTION_START_EVENT, AddGossipItemFor(), DATA_DEATHBRINGER_SAURFANG, DEFAULT_GOSSIP_MESSAGE, DONE, InstanceScript::GetBossState(), Object::GetGUID(), WorldObject::GetInstanceScript(), IN_PROGRESS, and SendGossipMenuFor().
OnGossipSelect()
bool npc_muradin_bronzebeard_icc::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 974 of file boss_deathbringer_saurfang.cpp.
     {
         InstanceScript* instance = creature->GetInstanceScript();
         if (instance && instance->GetBossState(DATA_DEATHBRINGER_SAURFANG) != DONE && instance->GetBossState(DATA_DEATHBRINGER_SAURFANG) != IN_PROGRESS)
         {
             ClearGossipMenuFor(player);
             CloseGossipMenuFor(player);
             if (action == -ACTION_START_EVENT + 1)
                 creature->AI()->DoAction(ACTION_START_EVENT);
         }
         return true;
     }
References ACTION_START_EVENT, Creature::AI(), ClearGossipMenuFor(), CloseGossipMenuFor(), DATA_DEATHBRINGER_SAURFANG, UnitAI::DoAction(), DONE, InstanceScript::GetBossState(), WorldObject::GetInstanceScript(), and IN_PROGRESS.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_deathbringer_saurfang.cpp