Azerotcore-wotlk: npc_prof_alchemy Class Reference
npc_prof_alchemy Class Reference
Public Member Functions
npc_prof_alchemy ()
bool HasAlchemySpell (Player *player)
bool OnGossipHello (Player *player, Creature *creature) override
void SendActionMenu (Player *player, Creature *creature, uint32 action)
void SendConfirmLearn (Player *player, Creature *creature, uint32 action)
void SendConfirmUnlearn (Player *player, Creature *creature, uint32 action)
bool OnGossipSelect (Player *player, Creature *creature, uint32 sender, uint32 action) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 434 of file npc_professions.cpp.
Constructor & Destructor Documentation
npc_prof_alchemy()
npc_prof_alchemy::npc_prof_alchemy () inline
Definition at line 437 of file npc_professions.cpp.
 : CreatureScript("npc_prof_alchemy") { }
Member Function Documentation
HasAlchemySpell()
bool npc_prof_alchemy::HasAlchemySpell (Player * player) inline
Definition at line 439 of file npc_professions.cpp.
     {
         return (player->HasSpell(S_TRANSMUTE) || player->HasSpell(S_ELIXIR) || player->HasSpell(S_POTION));
     }
References Player::HasSpell(), S_ELIXIR, S_POTION, and S_TRANSMUTE.
Referenced by OnGossipHello().
OnGossipHello()
bool npc_prof_alchemy::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 444 of file npc_professions.cpp.
     {
         if (creature->IsQuestGiver())
             player->PrepareQuestMenu(creature->GetGUID());
         if (creature->IsVendor())
             AddGossipItemFor(player, GOSSIP_ICON_VENDOR, GOSSIP_TEXT_BROWSE_GOODS, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_TRADE);
         if (creature->IsTrainer())
             AddGossipItemFor(player, GOSSIP_ICON_TRAINER, GOSSIP_TEXT_TRAIN, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_TRAIN);
         if (player->HasSkill(SKILL_ALCHEMY) && player->GetBaseSkillValue(SKILL_ALCHEMY) >= 350 && player->getLevel() > 67)
         {
             if (player->GetQuestRewardStatus(Q_MASTER_TRANSMUTE) || player->GetQuestRewardStatus(Q_MASTER_ELIXIR) || player->GetQuestRewardStatus(Q_MASTER_POTION))
             {
                 switch (creature->GetEntry())
                 {
                     case N_TRAINER_TRANSMUTE:                                 //Zarevhi
                         if (!HasAlchemySpell(player))
                             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_LEARN_TRANSMUTE,    GOSSIP_SENDER_LEARN,    GOSSIP_ACTION_INFO_DEF + 1);
                         if (player->HasSpell(S_TRANSMUTE))
                             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_UNLEARN_TRANSMUTE,  GOSSIP_SENDER_UNLEARN,  GOSSIP_ACTION_INFO_DEF + 4);
                         break;
                     case N_TRAINER_ELIXIR:                                 //Lorokeem
                         if (!HasAlchemySpell(player))
                             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_LEARN_ELIXIR,       GOSSIP_SENDER_LEARN,    GOSSIP_ACTION_INFO_DEF + 2);
                         if (player->HasSpell(S_ELIXIR))
                             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_UNLEARN_ELIXIR,     GOSSIP_SENDER_UNLEARN,  GOSSIP_ACTION_INFO_DEF + 5);
                         break;
                     case N_TRAINER_POTION:                                 //Lauranna Thar'well
                         if (!HasAlchemySpell(player))
                             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_LEARN_POTION,       GOSSIP_SENDER_LEARN,    GOSSIP_ACTION_INFO_DEF + 3);
                         if (player->HasSpell(S_POTION))
                             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_UNLEARN_POTION,     GOSSIP_SENDER_UNLEARN,  GOSSIP_ACTION_INFO_DEF + 6);
                         break;
                 }
             }
         }
         SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), Player::GetBaseSkillValue(), Object::GetEntry(), Player::GetGossipTextId(), Object::GetGUID(), Unit::getLevel(), Player::GetQuestRewardStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ACTION_TRADE, GOSSIP_ACTION_TRAIN, GOSSIP_ICON_CHAT, GOSSIP_ICON_TRAINER, GOSSIP_ICON_VENDOR, GOSSIP_LEARN_ELIXIR, GOSSIP_LEARN_POTION, GOSSIP_LEARN_TRANSMUTE, GOSSIP_SENDER_LEARN, GOSSIP_SENDER_MAIN, GOSSIP_SENDER_UNLEARN, GOSSIP_TEXT_BROWSE_GOODS, GOSSIP_TEXT_TRAIN, GOSSIP_UNLEARN_ELIXIR, GOSSIP_UNLEARN_POTION, GOSSIP_UNLEARN_TRANSMUTE, HasAlchemySpell(), Player::HasSkill(), Player::HasSpell(), Unit::IsQuestGiver(), Unit::IsTrainer(), Unit::IsVendor(), N_TRAINER_ELIXIR, N_TRAINER_POTION, N_TRAINER_TRANSMUTE, Player::PrepareQuestMenu(), Q_MASTER_ELIXIR, Q_MASTER_POTION, Q_MASTER_TRANSMUTE, S_ELIXIR, S_POTION, S_TRANSMUTE, SendGossipMenuFor(), and SKILL_ALCHEMY.
OnGossipSelect()
bool npc_prof_alchemy::OnGossipSelect (Player * player, Creature * creature, uint32 sender, uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 570 of file npc_professions.cpp.
     {
         ClearGossipMenuFor(player);
         switch (sender)
         {
             case GOSSIP_SENDER_MAIN:
                 SendActionMenu(player, creature, action);
                 break;
             case GOSSIP_SENDER_LEARN:
                 SendConfirmLearn(player, creature, action);
                 break;
             case GOSSIP_SENDER_UNLEARN:
                 SendConfirmUnlearn(player, creature, action);
                 break;
             case GOSSIP_SENDER_CHECK:
                 SendActionMenu(player, creature, action);
                 break;
         }
         return true;
     }
References ClearGossipMenuFor(), GOSSIP_SENDER_CHECK, GOSSIP_SENDER_LEARN, GOSSIP_SENDER_MAIN, GOSSIP_SENDER_UNLEARN, SendActionMenu(), SendConfirmLearn(), and SendConfirmUnlearn().
SendActionMenu()
void npc_prof_alchemy::SendActionMenu (Player * player, Creature * creature, uint32 action) inline
Definition at line 487 of file npc_professions.cpp.
     {
         switch (action)
         {
             case GOSSIP_ACTION_TRADE:
                 player->GetSession()->SendListInventory(creature->GetGUID());
                 break;
             case GOSSIP_ACTION_TRAIN:
                 player->GetSession()->SendTrainerList(creature->GetGUID());
                 break;
             //Learn Alchemy
             case GOSSIP_ACTION_INFO_DEF + 1:
                 ProcessCastaction(player, creature, S_TRANSMUTE, S_LEARN_TRANSMUTE, DoLearnCost(player));
                 break;
             case GOSSIP_ACTION_INFO_DEF + 2:
                 ProcessCastaction(player, creature, S_ELIXIR, S_LEARN_ELIXIR, DoLearnCost(player));
                 break;
             case GOSSIP_ACTION_INFO_DEF + 3:
                 ProcessCastaction(player, creature, S_POTION, S_LEARN_POTION, DoLearnCost(player));
                 break;
             //Unlearn Alchemy
             case GOSSIP_ACTION_INFO_DEF + 4:
                 ProcessUnlearnAction(player, creature, S_UNLEARN_TRANSMUTE, 0, DoHighUnlearnCost(player));
                 break;
             case GOSSIP_ACTION_INFO_DEF + 5:
                 ProcessUnlearnAction(player, creature, S_UNLEARN_ELIXIR, 0, DoHighUnlearnCost(player));
                 break;
             case GOSSIP_ACTION_INFO_DEF + 6:
                 ProcessUnlearnAction(player, creature, S_UNLEARN_POTION, 0, DoHighUnlearnCost(player));
                 break;
         }
     }
References DoHighUnlearnCost(), DoLearnCost(), Object::GetGUID(), Player::GetSession(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ACTION_TRADE, GOSSIP_ACTION_TRAIN, ProcessCastaction(), ProcessUnlearnAction(), S_ELIXIR, S_LEARN_ELIXIR, S_LEARN_POTION, S_LEARN_TRANSMUTE, S_POTION, S_TRANSMUTE, S_UNLEARN_ELIXIR, S_UNLEARN_POTION, S_UNLEARN_TRANSMUTE, WorldSession::SendListInventory(), and WorldSession::SendTrainerList().
Referenced by OnGossipSelect().
SendConfirmLearn()
void npc_prof_alchemy::SendConfirmLearn (Player * player, Creature * creature, uint32 action) inline
Definition at line 520 of file npc_professions.cpp.
     {
         if (action)
         {
             switch (creature->GetEntry())
             {
                 case N_TRAINER_TRANSMUTE:
                     AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_LEARN_TRANSMUTE, GOSSIP_SENDER_CHECK, action);
                     //unknown textID ()
                     SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
                     break;
                 case N_TRAINER_ELIXIR:
                     AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_LEARN_ELIXIR,    GOSSIP_SENDER_CHECK, action);
                     //unknown textID ()
                     SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
                     break;
                 case N_TRAINER_POTION:
                     AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_LEARN_POTION,    GOSSIP_SENDER_CHECK, action);
                     //unknown textID ()
                     SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
                     break;
             }
         }
     }
References AddGossipItemFor(), Object::GetEntry(), Player::GetGossipTextId(), Object::GetGUID(), GOSSIP_ICON_CHAT, GOSSIP_LEARN_ELIXIR, GOSSIP_LEARN_POTION, GOSSIP_LEARN_TRANSMUTE, GOSSIP_SENDER_CHECK, N_TRAINER_ELIXIR, N_TRAINER_POTION, N_TRAINER_TRANSMUTE, and SendGossipMenuFor().
Referenced by OnGossipSelect().
SendConfirmUnlearn()
void npc_prof_alchemy::SendConfirmUnlearn (Player * player, Creature * creature, uint32 action) inline
Definition at line 545 of file npc_professions.cpp.
     {
         if (action)
         {
             switch (creature->GetEntry())
             {
                 case N_TRAINER_TRANSMUTE:                                     //Zarevhi
                     AddGossipItemFor(player, 0, GOSSIP_UNLEARN_TRANSMUTE, GOSSIP_SENDER_CHECK, action, BOX_UNLEARN_ALCHEMY_SPEC, DoHighUnlearnCost(player), false);
                     //unknown textID ()
                     SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
                     break;
                 case N_TRAINER_ELIXIR:                                     //Lorokeem
                     AddGossipItemFor(player, 0, GOSSIP_UNLEARN_ELIXIR, GOSSIP_SENDER_CHECK, action,    BOX_UNLEARN_ALCHEMY_SPEC, DoHighUnlearnCost(player), false);
                     //unknown textID ()
                     SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
                     break;
                 case N_TRAINER_POTION:                                     //Lauranna Thar'well
                     AddGossipItemFor(player, 0, GOSSIP_UNLEARN_POTION, GOSSIP_SENDER_CHECK, action,    BOX_UNLEARN_ALCHEMY_SPEC, DoHighUnlearnCost(player), false);
                     //unknown textID ()
                     SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
                     break;
             }
         }
     }
References AddGossipItemFor(), BOX_UNLEARN_ALCHEMY_SPEC, DoHighUnlearnCost(), Object::GetEntry(), Player::GetGossipTextId(), Object::GetGUID(), GOSSIP_SENDER_CHECK, GOSSIP_UNLEARN_ELIXIR, GOSSIP_UNLEARN_POTION, GOSSIP_UNLEARN_TRANSMUTE, N_TRAINER_ELIXIR, N_TRAINER_POTION, N_TRAINER_TRANSMUTE, and SendGossipMenuFor().
Referenced by OnGossipSelect().
The documentation for this class was generated from the following file:
src/server/scripts/World/npc_professions.cpp