Azerotcore-wotlk: G3D::Array< T, MIN_ELEMENTS > Class Template Reference
G3D::Array< T, MIN_ELEMENTS > Class Template Reference
Dynamic 1D array tuned for performance.
#include <Array.h>
Classes
class DefaultComparator
Public Types
typedef T * Iterator
typedef const T * ConstIterator
typedef Iterator iterator
typedef ConstIterator const_iterator
typedef T value_type
typedef int size_type
typedef int difference_type
Public Member Functions
Array & operator= (const Array &other)
Array & operator= (const std::vector< T > &other)
Iterator begin ()
ConstIterator begin () const
ConstIterator end () const
Iterator end ()
T * getCArray ()
const T * getCArray () const
Array ()
Array (const T &v0)
Array (const T &v0, const T &v1)
Array (const T &v0, const T &v1, const T &v2)
Array (const T &v0, const T &v1, const T &v2, const T &v3)
Array (const T &v0, const T &v1, const T &v2, const T &v3, const T &v4)
Array (const Array &other)
Array (const std::vector< T > &other)
void copyFrom (const Array< T > &other)
void copyPOD (const Array< T > &other)
void appendPOD (const Array< T > &other)
~Array ()
void clear (bool shrink=true)
void clearAndSetMemoryManager (const MemoryManager::Ref &m)
void fastClear ()
MemoryManager::Ref memoryManager () const
int size () const
int length () const
void fastRemove (int index, bool shrinkIfNecessary=false)
void insert (int n, const T &value)
void setAll (const T &value)
void trimToSize ()
void resize (size_t n, bool shrinkIfNecessary=true)
void append (const T &value)
void append (const T &v1, const T &v2)
void append (const T &v1, const T &v2, const T &v3)
void append (const T &v1, const T &v2, const T &v3, const T &v4)
void append (const T &v1, const T &v2, const T &v3, const T &v4, const T &v5)
void append (const T &v1, const T &v2, const T &v3, const T &v4, const T &v5, const T &v6)
bool contains (const T &e) const
void append (const Array< T > &array)
T & next ()
void push (const T &value)
void push (const Array< T > &array)
void push_back (const T &v)
void pop_back ()
int capacity () const
T & front ()
const T & front () const
T & back ()
const T & back () const
T pop (bool shrinkUnderlyingArrayIfNecessary=true)
void popDiscard (bool shrinkUnderlyingArrayIfNecessary=false)
void swap (Array< T > &str)
T & operator[] (int n)
T & operator[] (uint32 n)
T & operator[] (uint64 n)
const T & operator[] (int n) const
const T & operator[] (uint32 n) const
const T & operator[] (uint64 n) const
T & randomElement ()
const T & randomElement () const
const T & last () const
T & last ()
int lastIndex () const
int firstIndex () const
T & first ()
const T & first () const
int middleIndex () const
const T & middle () const
T & middle ()
void invokeDeleteOnAllElements ()
void G3D_DEPRECATED deleteAll ()
int rfindIndex (const T &value) const
int findIndex (const T &value) const
Iterator find (const T &value)
ConstIterator find (const T &value) const
void remove (Iterator element, int count=1)
void remove (int index, int count=1)
void reverse ()
template<class LessThan >
void sort (const LessThan &lessThan)
void sort (int direction=SORT_INCREASING)
void sortSubArray (int beginIndex, int endIndex, int direction=SORT_INCREASING)
void sortSubArray (int beginIndex, int endIndex, bool(__cdecl *lessThan)(const T &elem1, const T &elem2))
template<typename StrictWeakOrdering >
void sortSubArray (int beginIndex, int endIndex, StrictWeakOrdering &lessThan)
template<typename Comparator >
void partition (const T &partitionElement, Array< T > &ltArray, Array< T > &eqArray, Array< T > &gtArray, const Comparator &comparator) const
void partition (const T &partitionElement, Array< T > &ltArray, Array< T > &eqArray, Array< T > &gtArray) const
template<typename Comparator >
void medianPartition (Array< T > &ltMedian, Array< T > &eqMedian, Array< T > &gtMedian, Array< T > &tempArray, const Comparator &comparator) const
void medianPartition (Array< T > &ltMedian, Array< T > &eqMedian, Array< T > &gtMedian) const
void randomize ()
void reserve (int n)
size_t sizeInMemory () const
void removeNulls ()
Static Public Member Functions
static void swap (Array< T, MIN_ELEMENTS > &a, Array< T, MIN_ELEMENTS > &b)
Private Member Functions
void init (size_t n, const MemoryManager::Ref &m)
void _copy (const Array &other)
bool inArray (const T *address)
void realloc (size_t oldNum)
Static Private Member Functions
static bool __cdecl compareGT (const T &a, const T &b)
Private Attributes
T * data
size_t num
size_t numAllocated
MemoryManager::Ref m_memoryManager
Static Private Attributes
static const size_t MIN_BYTES = 32
Detailed Description
template<class T, size_t MIN_ELEMENTS = 10>
class G3D::Array< T, MIN_ELEMENTS >
Dynamic 1D array tuned for performance.
Objects must have a default constructor (constructor that takes no arguments) in order to be used with this template. You will get the error "no appropriate default constructor found" if they do not.
Do not use with objects that overload placement operator new, since the speed of Array is partly due to pooled allocation.
Array is highly optimized compared to std::vector.
Array operations are less expensive than on std::vector and for large amounts of data, Array consumes only 1.5x the total size of the data, while std::vector consumes 2.0x. The default array takes up zero heap space. The first resize (or append) operation grows it to a reasonable internal size so it is efficient to append to small arrays.
Then Array needs to copy data internally on a resize operation it correctly invokes copy constructors of the elements (the MSVC6 implementation of std::vector uses realloc, which can create memory leaks for classes containing references and pointers). Array provides a guaranteed safe way to access the underlying data as a flat C array – Array::getCArray. Although (T*)std::vector::begin() can be used for this purpose, it is not guaranteed to succeed on all platforms.
To serialize an array, see G3D::serialize.
The template parameter MIN_ELEMENTS indicates the smallest number of elements that will be allocated. The default of 10 is designed to avoid the overhead of repeatedly allocating the array as it grows from 1, to 2, and so on. If you are creating a lot of small Arrays, however, you may want to set this smaller to reduce the memory cost. Once the array has been allocated, it will never deallocate the underlying array unless MIN_ELEMENTS is set to 0, MIN_BYTES is 0, and the array is empty.
Do not subclass an Array.
See also
G3D::SmallArray
Definition at line 95 of file Array.h.
Member Typedef Documentation
const_iterator
template<class T , size_t MIN_ELEMENTS = 10> typedef ConstIterator G3D::Array< T, MIN_ELEMENTS >::const_iterator
stl porting compatibility helper
Definition at line 221 of file Array.h.
ConstIterator
template<class T , size_t MIN_ELEMENTS = 10> typedef const T* G3D::Array< T, MIN_ELEMENTS >::ConstIterator
G3D C++ STL style const iterator in same style as Iterator.
Definition at line 216 of file Array.h.
difference_type
template<class T , size_t MIN_ELEMENTS = 10> typedef int G3D::Array< T, MIN_ELEMENTS >::difference_type
stl porting compatibility helper
Definition at line 227 of file Array.h.
Iterator
template<class T , size_t MIN_ELEMENTS = 10> typedef T* G3D::Array< T, MIN_ELEMENTS >::Iterator
G3D C++ STL style iterator variable. Call begin() to get the first iterator, pre-increment (++i) the iterator to get to the next value. Use dereference (*i) to access the element.
Definition at line 214 of file Array.h.
iterator
template<class T , size_t MIN_ELEMENTS = 10> typedef Iterator G3D::Array< T, MIN_ELEMENTS >::iterator
stl porting compatibility helper
Definition at line 219 of file Array.h.
size_type
template<class T , size_t MIN_ELEMENTS = 10> typedef int G3D::Array< T, MIN_ELEMENTS >::size_type
stl porting compatibility helper
Definition at line 225 of file Array.h.
value_type
template<class T , size_t MIN_ELEMENTS = 10> typedef T G3D::Array< T, MIN_ELEMENTS >::value_type
stl porting compatibility helper
Definition at line 223 of file Array.h.
Constructor & Destructor Documentation
Array() [1/8]
template<class T , size_t MIN_ELEMENTS = 10> G3D::Array< T, MIN_ELEMENTS >::Array () inline
Creates a zero length array (no heap allocation occurs until resize).
Definition at line 281 of file Array.h.
             : num(0) {
         init(0, MemoryManager::create());
     }
References G3D::MemoryManager::create(), and G3D::Array< T, MIN_ELEMENTS >::init().
Array() [2/8]
template<class T , size_t MIN_ELEMENTS = 10> G3D::Array< T, MIN_ELEMENTS >::Array (const T & v0) inline explicit
Creates an array containing v0.
Definition at line 287 of file Array.h.
{
         init(1, MemoryManager::create());
         (*this)[0] = v0;
     }
References G3D::MemoryManager::create(), and G3D::Array< T, MIN_ELEMENTS >::init().
Array() [3/8]
template<class T , size_t MIN_ELEMENTS = 10> G3D::Array< T, MIN_ELEMENTS >::Array (const T & v0, const T & v1) inline
Creates an array containing v0 and v1.
Definition at line 293 of file Array.h.
{
         init(2, MemoryManager::create());
         (*this)[0] = v0;
         (*this)[1] = v1;
     }
References G3D::MemoryManager::create(), and G3D::Array< T, MIN_ELEMENTS >::init().
Array() [4/8]
template<class T , size_t MIN_ELEMENTS = 10> G3D::Array< T, MIN_ELEMENTS >::Array (const T & v0, const T & v1, const T & v2) inline
Creates an array containing v0...v2.
Definition at line 300 of file Array.h.
{
        init(3, MemoryManager::create());
        (*this)[0] = v0;
        (*this)[1] = v1;
        (*this)[2] = v2;
     }
References G3D::MemoryManager::create(), and G3D::Array< T, MIN_ELEMENTS >::init().
Array() [5/8]
template<class T , size_t MIN_ELEMENTS = 10> G3D::Array< T, MIN_ELEMENTS >::Array (const T & v0, const T & v1, const T & v2, const T & v3) inline
Creates an array containing v0...v3.
Definition at line 308 of file Array.h.
{
        init(4, MemoryManager::create());
        (*this)[0] = v0;
        (*this)[1] = v1;
        (*this)[2] = v2;
        (*this)[3] = v3;
     }
References G3D::MemoryManager::create(), and G3D::Array< T, MIN_ELEMENTS >::init().
Array() [6/8]
template<class T , size_t MIN_ELEMENTS = 10> G3D::Array< T, MIN_ELEMENTS >::Array (const T & v0, const T & v1, const T & v2, const T & v3, const T & v4) inline
Creates an array containing v0...v4.
Definition at line 317 of file Array.h.
{
        init(5, MemoryManager::create());
        (*this)[0] = v0;
        (*this)[1] = v1;
        (*this)[2] = v2;
        (*this)[3] = v3;
        (*this)[4] = v4;
     }
References G3D::MemoryManager::create(), and G3D::Array< T, MIN_ELEMENTS >::init().
Array() [7/8]
template<class T , size_t MIN_ELEMENTS = 10> G3D::Array< T, MIN_ELEMENTS >::Array (const Array< T, MIN_ELEMENTS > & other) inline
Copy constructor. Copying arrays is slow...perhaps you want to pass a reference or a pointer instead?
Definition at line 331 of file Array.h.
                              : num(0) {
        _copy(other);
    }
References G3D::Array< T, MIN_ELEMENTS >::_copy().
Array() [8/8]
template<class T , size_t MIN_ELEMENTS = 10> G3D::Array< T, MIN_ELEMENTS >::Array (const std::vector< T > & other) inline explicit
Definition at line 335 of file Array.h.
                                              : num(0), data(NULL) {
        *this = other;
    }
~Array()
template<class T , size_t MIN_ELEMENTS = 10> G3D::Array< T, MIN_ELEMENTS >::~Array () inline
Destructor does not delete() the objects if T is a pointer type (e.g. T = int*) instead, it deletes the pointers themselves and leaves the objects. Call deleteAll if you want to dealocate the objects referenced. Do not call deleteAll if T is not a pointer type (e.g. do call Array<Foo*>::deleteAll, do not call Array<Foo>::deleteAll).
Definition at line 391 of file Array.h.
             {
        // Invoke the destructors on the elements
        for (size_t i = 0; i < num; ++i) {
            (data + i)->~T();
        }
        m_memoryManager->free(data);
        // Set to 0 in case this Array is global and gets referenced during app exit
        data = NULL;
        num = 0;
        numAllocated = 0;
    }
References G3D::Array< T, MIN_ELEMENTS >::m_memoryManager, NULL, G3D::Array< T, MIN_ELEMENTS >::num, and G3D::Array< T, MIN_ELEMENTS >::numAllocated.
Member Function Documentation
_copy()
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::_copy (const Array< T, MIN_ELEMENTS > & other) inline private
Definition at line 124 of file Array.h.
{
         init(other.num, MemoryManager::create());
         for (size_t i = 0; i < num; ++i) {
             data[i] = other.data[i];
         }
     }
References G3D::MemoryManager::create(), G3D::Array< T, MIN_ELEMENTS >::data, G3D::Array< T, MIN_ELEMENTS >::init(), and G3D::Array< T, MIN_ELEMENTS >::num.
Referenced by G3D::Array< T, MIN_ELEMENTS >::Array().
append() [1/7]
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::append (const Array< T > & array) inline
Append the elements of array. Cannot be called with this array as an argument.
Definition at line 748 of file Array.h.
{
        debugAssert(this != &array);
        size_t oldNum = num;
        size_t arrayLength = array.length();
        resize(num + arrayLength, false);
        for (size_t i = 0; i < arrayLength; ++i) {
            data[oldNum + i] = array.data[i];
        }
    }
References array, debugAssert, G3D::Array< T, MIN_ELEMENTS >::num, and G3D::Array< T, MIN_ELEMENTS >::resize().
append() [2/7]
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::append (const T & v1, const T & v2) inline
Definition at line 607 of file Array.h.
{
         if (inArray(&v1) || inArray(&v2)) {
             // Copy into temporaries so that the references won't break when
             // the array resizes.
             T t1 = v1;
             T t2 = v2;
             append(t1, t2);
         } else if (num + 1 < numAllocated) {
             // This is a simple situation; just stick it in the next free slot using
             // the copy constructor.
             new (data + num) T(v1);
             new (data + num + 1) T(v2);
             num += 2;
         } else {
             // Resize the array.  Note that neither value is already in the array.
             resize(num + 2, DONT_SHRINK_UNDERLYING_ARRAY);
             data[num - 2] = v1;
             data[num - 1] = v2;
         }
     }
References G3D::Array< T, MIN_ELEMENTS >::append(), G3D::DONT_SHRINK_UNDERLYING_ARRAY, G3D::Array< T, MIN_ELEMENTS >::inArray(), G3D::Array< T, MIN_ELEMENTS >::num, G3D::Array< T, MIN_ELEMENTS >::numAllocated, and G3D::Array< T, MIN_ELEMENTS >::resize().
append() [3/7]
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::append (const T & v1, const T & v2, const T & v3) inline
Definition at line 629 of file Array.h.
{
         if (inArray(&v1) || inArray(&v2) || inArray(&v3)) {
             T t1 = v1;
             T t2 = v2;
             T t3 = v3;
             append(t1, t2, t3);
         } else if (num + 2 < numAllocated) {
             // This is a simple situation; just stick it in the next free slot using
             // the copy constructor.
             new (data + num) T(v1);
             new (data + num + 1) T(v2);
             new (data + num + 2) T(v3);
             num += 3;
         } else {
             resize(num + 3, DONT_SHRINK_UNDERLYING_ARRAY);
             data[num - 3] = v1;
             data[num - 2] = v2;
             data[num - 1] = v3;
         }
     }
References G3D::Array< T, MIN_ELEMENTS >::append(), G3D::DONT_SHRINK_UNDERLYING_ARRAY, G3D::Array< T, MIN_ELEMENTS >::inArray(), G3D::Array< T, MIN_ELEMENTS >::num, G3D::Array< T, MIN_ELEMENTS >::numAllocated, and G3D::Array< T, MIN_ELEMENTS >::resize().
append() [4/7]
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::append (const T & v1, const T & v2, const T & v3, const T & v4) inline
Definition at line 651 of file Array.h.
{
         if (inArray(&v1) || inArray(&v2) || inArray(&v3) || inArray(&v4)) {
             T t1 = v1;
             T t2 = v2;
             T t3 = v3;
             T t4 = v4;
             append(t1, t2, t3, t4);
         } else if (num + 3 < numAllocated) {
             // This is a simple situation; just stick it in the next free slot using
             // the copy constructor.
             new (data + num) T(v1);
             new (data + num + 1) T(v2);
             new (data + num + 2) T(v3);
             new (data + num + 3) T(v4);
             num += 4;
         } else {
             resize(num + 4, DONT_SHRINK_UNDERLYING_ARRAY);
             data[num - 4] = v1;
             data[num - 3] = v2;
             data[num - 2] = v3;
             data[num - 1] = v4;
         }
     }
References G3D::Array< T, MIN_ELEMENTS >::append(), G3D::DONT_SHRINK_UNDERLYING_ARRAY, G3D::Array< T, MIN_ELEMENTS >::inArray(), G3D::Array< T, MIN_ELEMENTS >::num, G3D::Array< T, MIN_ELEMENTS >::numAllocated, and G3D::Array< T, MIN_ELEMENTS >::resize().
append() [5/7]
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::append (const T & v1, const T & v2, const T & v3, const T & v4, const T & v5) inline
Definition at line 675 of file Array.h.
{
         if (inArray(&v1) || inArray(&v2) || inArray(&v3) || inArray(&v4) || inArray(&v5)) {
             T t1 = v1;
             T t2 = v2;
             T t3 = v3;
             T t4 = v4;
             T t5 = v5;
             append(t1, t2, t3, t4, t5);
         } else if (num + 4 < numAllocated) {
             // This is a simple situation; just stick it in the next free slot using
             // the copy constructor.
             new (data + num) T(v1);
             new (data + num + 1) T(v2);
             new (data + num + 2) T(v3);
             new (data + num + 3) T(v4);
             new (data + num + 4) T(v5);
             num += 5;
         } else {
             resize(num + 5, DONT_SHRINK_UNDERLYING_ARRAY);
             data[num - 5] = v1;
             data[num - 4] = v2;
             data[num - 3] = v3;
             data[num - 2] = v4;
             data[num - 1] = v5;
         }
     }
References G3D::Array< T, MIN_ELEMENTS >::append(), G3D::DONT_SHRINK_UNDERLYING_ARRAY, G3D::Array< T, MIN_ELEMENTS >::inArray(), G3D::Array< T, MIN_ELEMENTS >::num, G3D::Array< T, MIN_ELEMENTS >::numAllocated, and G3D::Array< T, MIN_ELEMENTS >::resize().
append() [6/7]
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::append (const T & v1, const T & v2, const T & v3, const T & v4, const T & v5, const T & v6) inline
Definition at line 702 of file Array.h.
{
         if (inArray(&v1) || inArray(&v2) || inArray(&v3) || inArray(&v4) || inArray(&v5) || inArray(&v6)) {
             T t1 = v1;
             T t2 = v2;
             T t3 = v3;
             T t4 = v4;
             T t5 = v5;
             T t6 = v6;
             append(t1, t2, t3, t4, t5, t6);
         } else if (num + 5 < numAllocated) {
             // This is a simple situation; just stick it in the next free slot using
             // the copy constructor.
             new (data + num) T(v1);
             new (data + num + 1) T(v2);
             new (data + num + 2) T(v3);
             new (data + num + 3) T(v4);
             new (data + num + 4) T(v5);
             new (data + num + 5) T(v6);
             num += 6;
         } else {
             resize(num + 6, DONT_SHRINK_UNDERLYING_ARRAY);
             data[num - 6] = v1;
             data[num - 5] = v2;
             data[num - 4] = v3;
             data[num - 3] = v4;
             data[num - 2] = v5;
             data[num - 1] = v6;
         }
     }
References G3D::Array< T, MIN_ELEMENTS >::append(), G3D::DONT_SHRINK_UNDERLYING_ARRAY, G3D::Array< T, MIN_ELEMENTS >::inArray(), G3D::Array< T, MIN_ELEMENTS >::num, G3D::Array< T, MIN_ELEMENTS >::numAllocated, and G3D::Array< T, MIN_ELEMENTS >::resize().
append() [7/7]
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::append (const T & value) inline
Add an element to the end of the array. Will not shrink the underlying array under any circumstances. It is safe to append an element that is already in the array.
Definition at line 585 of file Array.h.
{
         if (num < numAllocated) {
             // This is a simple situation; just stick it in the next free slot using
             // the copy constructor.
             new (data + num) T(value);
             ++num;
         } else if (inArray(&value)) {
             // The value was in the original array; resizing
             // is dangerous because it may move the value
             // we have a reference to.
             T tmp = value;
             append(tmp);
         } else {
             // Here we run the empty initializer where we don't have to, but
             // this simplifies the computation.
             resize(num + 1, DONT_SHRINK_UNDERLYING_ARRAY);
             data[num - 1] = value;
         }
     }
References G3D::DONT_SHRINK_UNDERLYING_ARRAY, G3D::Array< T, MIN_ELEMENTS >::inArray(), G3D::Array< T, MIN_ELEMENTS >::num, G3D::Array< T, MIN_ELEMENTS >::numAllocated, and G3D::Array< T, MIN_ELEMENTS >::resize().
Referenced by G3D::NetworkDevice::addAdapter(), G3D::Array< T, MIN_ELEMENTS >::append(), G3D::Spline< Control >::append(), G3D::bayer_bggr8_to_rgba32f(), G3D::bayer_gbrg8_to_rgba32f(), G3D::bayer_grbg8_to_rgba32f(), G3D::bayer_rggb8_to_rgba32f(), MMAP::MapBuilder::buildTile(), MMAP::TerrainBuilder::cleanVertices(), G3D::Rect2D::clipSide2D(), G3D::MeshBuilder::commit(), G3D::MeshAlg::computeAdjacency(), G3D::_internal::WeldHelper::computeFaceNormals(), G3D::ImageFormat::convert(), G3D::Array< T, MIN_ELEMENTS >::copyFrom(), MMAP::TerrainBuilder::copyIndices(), G3D::ConvexPolyhedron::cut(), G3D::System::findDataFile(), G3D::MeshAlg::generateGrid(), MMAP::IntermediateValues::generateObjFile(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Node::getHandles(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::getHandles(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Node::getIntersectingMembers(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::getIntersectingMembers(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::getIntersectingMembers(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::getIntersectingMembers(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::getKeys(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::getMembers(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::getValues(), G3D::WeakCache< Key, ValueRef >::getValues(), G3D::ThreadSet::insert(), MMAP::TerrainBuilder::loadMap(), MMAP::TerrainBuilder::loadOffMeshConnections(), MMAP::TerrainBuilder::loadVMap(), G3D::Array< T, MIN_ELEMENTS >::medianPartition(), G3D::FilePath::parse(), G3D::parseFilename(), G3D::Array< T, MIN_ELEMENTS >::partition(), G3D::CollisionDetection::penetrationDepthForFixedBoxFixedPlane(), G3D::CollisionDetection::penetrationDepthForFixedSphereFixedBox(), G3D::CollisionDetection::penetrationDepthForFixedSphereFixedPlane(), G3D::CollisionDetection::penetrationDepthForFixedSphereFixedSphere(), G3D::PhysicsFrameSpline::PhysicsFrameSpline(), G3D::Array< T, MIN_ELEMENTS >::push(), G3D::rgba32f_to_bayer_bggr8(), G3D::rgba32f_to_bayer_gbrg8(), G3D::rgba32f_to_bayer_grbg8(), G3D::rgba32f_to_bayer_rggb8(), G3D::ThreadSet::start(), G3D::stringSplit(), G3D::_internal::WeldHelper::unroll(), G3D::Welder::weld(), G3D::MeshAlg::weldAdjacency(), G3D::MeshAlg::weldBoundaryEdges(), and G3D::TextOutput::wordWrapIndentAppend().
appendPOD()
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::appendPOD (const Array< T > & other) inline
Resizes this to just barely match the size of other + itself and then copies the data to the end of the array from other using memcpy.
This is only safe for POD types
Definition at line 367 of file Array.h.
{
        static_assert(std::is_standard_layout<T>::value, "appendPOD called on non-POD type");
        const size_t oldSize = num;
        num += other.num;
        if (numAllocated < num) {
            alwaysAssertM(other.data, "non-zero array with no allocated space");
            T* old = data;
            data = (T*)m_memoryManager->alloc(sizeof(T) * num);
            System::memcpy(data, old, sizeof(T) * oldSize);
            m_memoryManager->free(old);
            numAllocated = num;
        }
        if (other.data) {
            System::memcpy((data + oldSize), other.data, sizeof(T) * other.num);
        }
    }
References alwaysAssertM, G3D::Array< T, MIN_ELEMENTS >::data, G3D::Array< T, MIN_ELEMENTS >::m_memoryManager, G3D::System::memcpy(), G3D::Array< T, MIN_ELEMENTS >::num, and G3D::Array< T, MIN_ELEMENTS >::numAllocated.
back() [1/2]
template<class T , size_t MIN_ELEMENTS = 10> T& G3D::Array< T, MIN_ELEMENTS >::back () inline
"The member function returns a reference to the last element of the controlled sequence, which must be non-empty." For compatibility with std::vector.
Definition at line 823 of file Array.h.
              {
        return (*this)[size()-1];
    }
References G3D::Array< T, MIN_ELEMENTS >::size().
back() [2/2]
template<class T , size_t MIN_ELEMENTS = 10> const T& G3D::Array< T, MIN_ELEMENTS >::back () const inline
"The member function returns a reference to the last element of the controlled sequence, which must be non-empty." For compatibility with std::vector.
Definition at line 832 of file Array.h.
{
        return (*this)[size()-1];
    }
References G3D::Array< T, MIN_ELEMENTS >::size().
begin() [1/2]
template<class T , size_t MIN_ELEMENTS = 10> Iterator G3D::Array< T, MIN_ELEMENTS >::begin () inline
C++ STL style iterator method. Returns the first iterator element. Do not change the size of the array while iterating.
Definition at line 233 of file Array.h.
                      {
         return data;
     }
References G3D::Array< T, MIN_ELEMENTS >::data.
Referenced by G3D::ThreadSet::begin(), and G3D::Array< T, MIN_ELEMENTS >::remove().
begin() [2/2]
template<class T , size_t MIN_ELEMENTS = 10> ConstIterator G3D::Array< T, MIN_ELEMENTS >::begin () const inline
Definition at line 237 of file Array.h.
{
         return data;
     }
References G3D::Array< T, MIN_ELEMENTS >::data.
capacity()
template<class T , size_t MIN_ELEMENTS = 10> int G3D::Array< T, MIN_ELEMENTS >::capacity () const inline
"The member function returns the storage currently allocated to hold the controlled sequence, a value at least as large as size()" For compatibility with std::vector.
Definition at line 796 of file Array.h.
{
         return (int)numAllocated;
    }
References G3D::Array< T, MIN_ELEMENTS >::numAllocated.
Referenced by G3D::Array< T, MIN_ELEMENTS >::trimToSize().
clear()
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::clear (bool shrink = true) inline
Removes all elements. Use resize(0, false) or fastClear if you want to remove all elements without deallocating the underlying array so that future append() calls will be faster.
Definition at line 409 of file Array.h.
{
        resize(0, shrink);
    }
References G3D::Array< T, MIN_ELEMENTS >::resize().
Referenced by G3D::System::cleanup(), MMAP::TerrainBuilder::cleanVertices(), G3D::Spline< Control >::clear(), G3D::ThreadSet::clear(), G3D::MeshEdgeTable::clear(), G3D::Array< T, MIN_ELEMENTS >::clearAndSetMemoryManager(), G3D::Rect2D::clip(), G3D::Rect2D::clipSide2D(), G3D::MeshAlg::computeAdjacency(), G3D::Array< T, MIN_ELEMENTS >::fastClear(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::makeNode(), G3D::FilePath::parse(), G3D::parseFilename(), G3D::_internal::WeldHelper::process(), G3D::System::setAppDataDir(), and G3D::MeshAlg::weldAdjacency().
clearAndSetMemoryManager()
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::clearAndSetMemoryManager (const MemoryManager::Ref & m) inline
Definition at line 413 of file Array.h.
{
        clear();
        debugAssert(data == NULL);
        m_memoryManager = m;
    }
References G3D::Array< T, MIN_ELEMENTS >::clear(), debugAssert, G3D::Array< T, MIN_ELEMENTS >::m_memoryManager, and NULL.
Referenced by G3D::MeshEdgeTable::MeshEdgeTable().
compareGT()
template<class T , size_t MIN_ELEMENTS = 10> static bool __cdecl G3D::Array< T, MIN_ELEMENTS >::compareGT (const T & a, const T & b) inline static private
Only compiled if you use the sort procedure.
Definition at line 141 of file Array.h.
{
         return a > b;
     }
References mpq::a, and b.
Referenced by G3D::Array< T, MIN_ELEMENTS >::sort(), and G3D::Array< T, MIN_ELEMENTS >::sortSubArray().
contains()
template<class T , size_t MIN_ELEMENTS = 10> bool G3D::Array< T, MIN_ELEMENTS >::contains (const T & e) const inline
Returns true if the given element is in the array.
Definition at line 734 of file Array.h.
{
         for (int i = 0; i < size(); ++i) {
             if ((*this)[i] == e) {
                 return true;
             }
         }
         return false;
     }
References G3D::Array< T, MIN_ELEMENTS >::size().
Referenced by G3D::generateFilenameBase().
copyFrom()
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::copyFrom (const Array< T > & other) inline
Definition at line 341 of file Array.h.
{
         resize(0);
         append(other);
    }
References G3D::Array< T, MIN_ELEMENTS >::append(), and G3D::Array< T, MIN_ELEMENTS >::resize().
copyPOD()
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::copyPOD (const Array< T > & other) inline
Resizes this to match the size of other and then copies the data from other using memcpy. This is only safe for POD types
Definition at line 348 of file Array.h.
{
        static_assert(std::is_standard_layout<T>::value, "copyPOD called on non-POD type");
        if (numAllocated < other.num) {
            m_memoryManager->free(data);
            data = NULL;
            if (other.data) {
               data = (T*)m_memoryManager->alloc(sizeof(T) * other.num);
            }
            numAllocated = other.num;
        }
        num = other.num;
        if (other.data && (num > 0)) {
            System::memcpy(data, other.data, sizeof(T) * num);
        }
    }
References G3D::Array< T, MIN_ELEMENTS >::data, G3D::Array< T, MIN_ELEMENTS >::m_memoryManager, G3D::System::memcpy(), NULL, G3D::Array< T, MIN_ELEMENTS >::num, and G3D::Array< T, MIN_ELEMENTS >::numAllocated.
deleteAll()
template<class T , size_t MIN_ELEMENTS = 10> void G3D_DEPRECATED G3D::Array< T, MIN_ELEMENTS >::deleteAll () inline
Deprecated:
Definition at line 990 of file Array.h.
{
         invokeDeleteOnAllElements();
     }
References G3D::Array< T, MIN_ELEMENTS >::invokeDeleteOnAllElements().
end() [1/2]
template<class T , size_t MIN_ELEMENTS = 10> Iterator G3D::Array< T, MIN_ELEMENTS >::end () inline
Definition at line 248 of file Array.h.
                    {
         return data + num;
     }
References G3D::Array< T, MIN_ELEMENTS >::num.
end() [2/2]
template<class T , size_t MIN_ELEMENTS = 10> ConstIterator G3D::Array< T, MIN_ELEMENTS >::end () const inline
C++ STL style iterator method. Returns one after the last valid iterator element.
Definition at line 244 of file Array.h.
{
         return data + num;
     }
References G3D::Array< T, MIN_ELEMENTS >::num.
Referenced by G3D::ThreadSet::end(), G3D::Array< T, MIN_ELEMENTS >::find(), G3D::Array< T, MIN_ELEMENTS >::realloc(), and G3D::Array< T, MIN_ELEMENTS >::remove().
fastClear()
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::fastClear () inline
resize(0, false)
Deprecated:
Definition at line 421 of file Array.h.
                     {
        clear(false);
    }
References G3D::Array< T, MIN_ELEMENTS >::clear().
Referenced by BIHWrap< T, BoundsFunc >::balance(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::balance(), MMAP::TerrainBuilder::cleanVertices(), G3D::MeshAlg::generateGrid(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::makeNode(), G3D::Array< T, MIN_ELEMENTS >::medianPartition(), and G3D::Array< T, MIN_ELEMENTS >::partition().
fastRemove()
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::fastRemove (int index, bool shrinkIfNecessary = false) inline
Swaps element index with the last element in the array then shrinks the array by one.
Definition at line 448 of file Array.h.
{
        debugAssert(index < (int)num);
        data[index] = data[num - 1];
        resize(size() - 1, shrinkIfNecessary);
    }
References debugAssert, index, G3D::Array< T, MIN_ELEMENTS >::num, G3D::Array< T, MIN_ELEMENTS >::resize(), and G3D::Array< T, MIN_ELEMENTS >::size().
Referenced by G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::makeNode(), G3D::ThreadSet::remove(), G3D::ThreadSet::removeCompleted(), and G3D::MeshAlg::weldBoundaryEdges().
find() [1/2]
template<class T , size_t MIN_ELEMENTS = 10> Iterator G3D::Array< T, MIN_ELEMENTS >::find (const T & value) inline
Finds an element and returns the iterator to it. If the element isn't found then returns end().
Definition at line 1024 of file Array.h.
{
         for (int i = 0; i < num; ++i) {
             if (data[i] == value) {
                 return data + i;
             }
         }
         return end();
     }
References G3D::Array< T, MIN_ELEMENTS >::end(), and G3D::Array< T, MIN_ELEMENTS >::num.
find() [2/2]
template<class T , size_t MIN_ELEMENTS = 10> ConstIterator G3D::Array< T, MIN_ELEMENTS >::find (const T & value) const inline
Definition at line 1033 of file Array.h.
{
         for (int i = 0; i < num; ++i) {
             if (data[i] == value) {
                 return data + i;
             }
         }
         return end();
     }
References G3D::Array< T, MIN_ELEMENTS >::end(), and G3D::Array< T, MIN_ELEMENTS >::num.
findIndex()
template<class T , size_t MIN_ELEMENTS = 10> int G3D::Array< T, MIN_ELEMENTS >::findIndex (const T & value) const inline
Returns the index of (the first occurance of) an index or -1 if not found.
Definition at line 1011 of file Array.h.
{
         for (size_t i = 0; i < num; ++i) {
             if (data[i] == value) {
                 return (int)i;
             }
         }
         return -1;
     }
References G3D::Array< T, MIN_ELEMENTS >::num.
Referenced by G3D::NetworkDevice::addAdapter().
first() [1/2]
template<class T , size_t MIN_ELEMENTS = 10> T& G3D::Array< T, MIN_ELEMENTS >::first () inline
Returns element firstIndex(), performing a check in debug mode to ensure that there is at least one
Definition at line 950 of file Array.h.
                       {
         debugAssertM(num > 0, "Array is empty");
         return data[0];
     }
References debugAssertM, and G3D::Array< T, MIN_ELEMENTS >::num.
Referenced by G3D::Array< T, MIN_ELEMENTS >::medianPartition().
first() [2/2]
template<class T , size_t MIN_ELEMENTS = 10> const T& G3D::Array< T, MIN_ELEMENTS >::first () const inline
Definition at line 955 of file Array.h.
{
         debugAssertM(num > 0, "Array is empty");
         return data[0];
     }
References debugAssertM, and G3D::Array< T, MIN_ELEMENTS >::num.
firstIndex()
template<class T , size_t MIN_ELEMENTS = 10> int G3D::Array< T, MIN_ELEMENTS >::firstIndex () const inline
Definition at line 944 of file Array.h.
{
         debugAssertM(num > 0, "Array is empty");
         return 0;
     }
References debugAssertM, and G3D::Array< T, MIN_ELEMENTS >::num.
front() [1/2]
template<class T , size_t MIN_ELEMENTS = 10> T& G3D::Array< T, MIN_ELEMENTS >::front () inline
"The member function returns a reference to the first element of the controlled sequence, which must be non-empty." For compatibility with std::vector.
Definition at line 805 of file Array.h.
               {
        return (*this)[0];
    }
front() [2/2]
template<class T , size_t MIN_ELEMENTS = 10> const T& G3D::Array< T, MIN_ELEMENTS >::front () const inline
"The member function returns a reference to the first element of the controlled sequence, which must be non-empty." For compatibility with std::vector.
Definition at line 814 of file Array.h.
{
        return (*this)[0];
    }
getCArray() [1/2]
template<class T , size_t MIN_ELEMENTS = 10> T* G3D::Array< T, MIN_ELEMENTS >::getCArray () inline
The array returned is only valid until the next append() or resize call, or the Array is deallocated.
Definition at line 256 of file Array.h.
                   {
        return data;
    }
References G3D::Array< T, MIN_ELEMENTS >::data.
Referenced by MMAP::MapBuilder::buildMoveMapTile(), MMAP::MapBuilder::buildTile(), MMAP::TerrainBuilder::cleanVertices(), G3D::MeshAlg::computeTangentSpaceBasis(), MMAP::TerrainBuilder::copyIndices(), G3D::cyclicCatmullRomSpline(), MMAP::IntermediateValues::generateObjFile(), MMAP::MapBuilder::getGridBounds(), BIHWrap< T, BoundsFunc >::intersectPoint(), BIHWrap< T, BoundsFunc >::intersectRay(), MMAP::TerrainBuilder::loadMap(), G3D::BinaryInput::readFixedLengthString(), G3D::LightweightConduit::receive(), and G3D::LightweightConduit::waitingMessageType().
getCArray() [2/2]
template<class T , size_t MIN_ELEMENTS = 10> const T* G3D::Array< T, MIN_ELEMENTS >::getCArray () const inline
The array returned is only valid until the next append() or resize call, or the Array is deallocated.
Definition at line 276 of file Array.h.
{
        return data;
    }
References G3D::Array< T, MIN_ELEMENTS >::data.
inArray()
template<class T , size_t MIN_ELEMENTS = 10> bool G3D::Array< T, MIN_ELEMENTS >::inArray (const T * address) inline private
Returns true iff address points to an element of this array. Used by append.
Definition at line 135 of file Array.h.
{
         return (address >= data) && (address < data + num);
     }
References G3D::Array< T, MIN_ELEMENTS >::num.
Referenced by G3D::Array< T, MIN_ELEMENTS >::append().
init()
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::init (size_t n, const MemoryManager::Ref & m) inline private
Parameters
n Number of elements
Definition at line 112 of file Array.h.
{
         m_memoryManager = m;
         this->num = 0;
         this->numAllocated = 0;
         data = NULL;
         if (n > 0) {
             resize(n);
         } else {
             data = NULL;
         }
     }
References G3D::Array< T, MIN_ELEMENTS >::m_memoryManager, NULL, and G3D::Array< T, MIN_ELEMENTS >::resize().
Referenced by G3D::Array< T, MIN_ELEMENTS >::_copy(), and G3D::Array< T, MIN_ELEMENTS >::Array().
insert()
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::insert (int n, const T & value) inline
Inserts at the specified index and shifts all other elements up by one.
Definition at line 458 of file Array.h.
{
        // Add space for the extra element
        resize(num + 1, false);
        for (size_t i = (size_t)(num - 1); i > (size_t)n; --i) {
            data[i] = data[i - 1];
        }
        data[n] = value;
    }
References G3D::Array< T, MIN_ELEMENTS >::num, and G3D::Array< T, MIN_ELEMENTS >::resize().
invokeDeleteOnAllElements()
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::invokeDeleteOnAllElements () inline
Calls delete on all objects[0...size-1] and sets the size to zero.
Definition at line 982 of file Array.h.
{
         for (size_t i = 0; i < num; ++i) {
             delete data[i];
         }
         resize(0);
     }
References G3D::Array< T, MIN_ELEMENTS >::num, and G3D::Array< T, MIN_ELEMENTS >::resize().
Referenced by G3D::Array< T, MIN_ELEMENTS >::deleteAll().
last() [1/2]
template<class T , size_t MIN_ELEMENTS = 10> T& G3D::Array< T, MIN_ELEMENTS >::last () inline
Returns element lastIndex()
Definition at line 932 of file Array.h.
                      {
         debugAssert(num > 0);
         debugAssert(data!=NULL);
         return data[num - 1];
     }
References debugAssert, NULL, and G3D::Array< T, MIN_ELEMENTS >::num.
last() [2/2]
template<class T , size_t MIN_ELEMENTS = 10> const T& G3D::Array< T, MIN_ELEMENTS >::last () const inline
Returns the last element, performing a check in debug mode that there is at least one element.
Definition at line 925 of file Array.h.
{
         debugAssert(num > 0);
         debugAssert(data!=NULL);
         return data[num - 1];
     }
References debugAssert, NULL, and G3D::Array< T, MIN_ELEMENTS >::num.
Referenced by G3D::Spline< Control >::append(), G3D::computeAppName(), G3D::MeshAlg::computeAreaStatistics(), G3D::ConvexPolyhedron::cut(), G3D::SplineBase::duration(), G3D::Spline< Control >::getControl(), G3D::Array< T, MIN_ELEMENTS >::medianPartition(), G3D::Array< T, MIN_ELEMENTS >::next(), G3D::BinaryInput::readFixedLengthString(), G3D::Array< T, MIN_ELEMENTS >::remove(), and G3D::ThreadSet::start().
lastIndex()
template<class T , size_t MIN_ELEMENTS = 10> int G3D::Array< T, MIN_ELEMENTS >::lastIndex () const inline
Returns size() - 1
Definition at line 939 of file Array.h.
{
         debugAssertM(num > 0, "Array is empty");
         return num - 1;
     }
References debugAssertM, and G3D::Array< T, MIN_ELEMENTS >::num.
length()
template<class T , size_t MIN_ELEMENTS = 10> int G3D::Array< T, MIN_ELEMENTS >::length () const inline
Number of elements in the array. (Same as size; this is just here for convenience).
Definition at line 440 of file Array.h.
{
       return size();
    }
References G3D::Array< T, MIN_ELEMENTS >::size().
Referenced by G3D::Rect2D::clipSide2D(), G3D::ConvexPolyhedron::cut(), G3D::NetAddress::NetAddress(), G3D::UprightSpline::toAny(), G3D::UprightSpline::UprightSpline(), and G3D::zipfileExists().
medianPartition() [1/2]
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::medianPartition (Array< T > & ltMedian, Array< T > & eqMedian, Array< T > & gtMedian) const inline
Computes a median partition using the default comparator and a dynamically allocated temporary working array. If the median is not in the array, it is chosen to be the largest value smaller than the true median.
Definition at line 1393 of file Array.h.
{
         Array<T> temp;
         medianPartition(ltMedian, eqMedian, gtMedian, temp, DefaultComparator());
     }
References G3D::Array< T, MIN_ELEMENTS >::medianPartition().
medianPartition() [2/2]
template<class T , size_t MIN_ELEMENTS = 10> template<typename Comparator > void G3D::Array< T, MIN_ELEMENTS >::medianPartition (Array< T > & ltMedian, Array< T > & eqMedian, Array< T > & gtMedian, Array< T > & tempArray, const Comparator & comparator) const inline
Paritions the array into those below the median, those above the median, and those elements equal to the median in expected O(n) time using quickselect. If the array has an even number of different elements, the median for partition purposes is the largest value less than the median.
Parameters
tempArray used for working scratch space
comparator see parition() for a discussion.
Definition at line 1249 of file Array.h.
{
         ltMedian.fastClear();
         eqMedian.fastClear();
         gtMedian.fastClear();
         // Handle trivial cases first
         switch (size()) {
         case 0:
             // Array is empty; no parition is possible
             return;
         case 1:
             // One element
             eqMedian.append(first());
             return;
         case 2:
             {
                 // Two element array; median is the smaller
                 int c = comparator(first(), last());
                 switch (c) {
                 case -1:
                     // first was bigger
                     eqMedian.append(last());
                     gtMedian.append(first());
                     break;
                 case 0:
                     // Both equal to the median
                     eqMedian.append(first(), last());
                     break;
                 case 1:
                     // Last was bigger
                     eqMedian.append(first());
                     gtMedian.append(last());
                     break;
                 }
             }
             return;
         }
         // All other cases use a recursive randomized median
         // Number of values less than all in the current arrays
         int ltBoost = 0;
         // Number of values greater than all in the current arrays
         int gtBoost = 0;
         // For even length arrays, force the gt array to be one larger than the
         // lt array:
         //  [1 2 3] size = 3, choose half = (s + 1) /2
         //
         int lowerHalfSize, upperHalfSize;
         if (isEven(size())) {
             lowerHalfSize = size() / 2;
             upperHalfSize = lowerHalfSize + 1;
         } else {
             lowerHalfSize = upperHalfSize = (size() + 1) / 2;
         }
         const T* xPtr = NULL;
         // Maintain pointers to the arrays; we'll switch these around during sorting
         // to avoid copies.
         const Array<T>* source = this;
         Array<T>* lt     = &ltMedian;
         Array<T>* eq     = &eqMedian;
         Array<T>* gt     = &gtMedian;
         Array<T>* extra  = &tempArray;
         while (true) {
             // Choose a random element -- choose the middle element; this is theoretically
             // suboptimal, but for loosly sorted array is actually the best strategy
             xPtr = &(source->middle());
             if (source->size() == 1) {
                 // Done; there's only one element left
                 break;
             }
             const T& x = *xPtr;
             // Note: partition (fast) clears the arrays for us
             source->partition(x, *lt, *eq, *gt, comparator);
             int L = lt->size() + ltBoost + eq->size();
             int U = gt->size() + gtBoost + eq->size();
             if ((L >= lowerHalfSize) &&
                 (U >= upperHalfSize)) {
                 // x must be the partition median
                 break;
             } else if (L < lowerHalfSize) {
                 // x must be smaller than the median.  Recurse into the 'gt' array.
                 ltBoost += lt->size() + eq->size();
                 // The new gt array will be the old source array, unless
                 // that was the this pointer (i.e., unless we are on the
                 // first iteration)
                 Array<T>* newGt = (source == this) ? extra : const_cast<Array<T>*>(source);
                 // Now set up the gt array as the new source
                 source = gt;
                 gt = newGt;
             } else {
                 // x must be bigger than the median.  Recurse into the 'lt' array.
                 gtBoost += gt->size() + eq->size();
                 // The new lt array will be the old source array, unless
                 // that was the this pointer (i.e., unless we are on the
                 // first iteration)
                 Array<T>* newLt = (source == this) ? extra : const_cast<Array<T>*>(source);
                 // Now set up the lt array as the new source
                 source = lt;
                 lt = newLt;
             }
         }
         // Now that we know the median, make a copy of it (since we're about to destroy the array that it
         // points into).
         T median = *xPtr;
         xPtr = NULL;
         // Partition the original array (note that this fast clears for us)
         partition(median, ltMedian, eqMedian, gtMedian, comparator);
     }
References G3D::Array< T, MIN_ELEMENTS >::append(), mpq::c, G3D::Array< T, MIN_ELEMENTS >::fastClear(), G3D::Array< T, MIN_ELEMENTS >::first(), G3D::isEven(), G3D::Array< T, MIN_ELEMENTS >::last(), median(), G3D::Array< T, MIN_ELEMENTS >::middle(), NULL, G3D::Array< T, MIN_ELEMENTS >::partition(), G3D::Array< T, MIN_ELEMENTS >::size(), and G3D::x.
Referenced by G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::makeNode(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::makeNode(), and G3D::Array< T, MIN_ELEMENTS >::medianPartition().
memoryManager()
template<class T , size_t MIN_ELEMENTS = 10> MemoryManager::Ref G3D::Array< T, MIN_ELEMENTS >::memoryManager () const inline
Definition at line 425 of file Array.h.
{
        return m_memoryManager;
    }
References G3D::Array< T, MIN_ELEMENTS >::m_memoryManager.
middle() [1/2]
template<class T , size_t MIN_ELEMENTS = 10> T& G3D::Array< T, MIN_ELEMENTS >::middle () inline
Returns element middleIndex()
Definition at line 973 of file Array.h.
{
         debugAssertM(num > 0, "Array is empty");
         return data[num >> 1];
     }
References debugAssertM, and G3D::Array< T, MIN_ELEMENTS >::num.
middle() [2/2]
template<class T , size_t MIN_ELEMENTS = 10> const T& G3D::Array< T, MIN_ELEMENTS >::middle () const inline
Returns element middleIndex()
Definition at line 967 of file Array.h.
{
         debugAssertM(num > 0, "Array is empty");
         return data[num >> 1];
     }
References debugAssertM, and G3D::Array< T, MIN_ELEMENTS >::num.
Referenced by G3D::Array< T, MIN_ELEMENTS >::medianPartition().
middleIndex()
template<class T , size_t MIN_ELEMENTS = 10> int G3D::Array< T, MIN_ELEMENTS >::middleIndex () const inline
Returns iFloor(size() / 2), throws an assertion in debug mode if the array is empty
Definition at line 961 of file Array.h.
{
         debugAssertM(num > 0, "Array is empty");
         return num >> 1;
     }
References debugAssertM, and G3D::Array< T, MIN_ELEMENTS >::num.
next()
template<class T , size_t MIN_ELEMENTS = 10> T& G3D::Array< T, MIN_ELEMENTS >::next () inline
Pushes a new element onto the end and returns its address. This is the same as A.resize(A.size() + 1, false); A.last()
Definition at line 764 of file Array.h.
                     {
        resize(num + 1, false);
        return last();
    }
References G3D::Array< T, MIN_ELEMENTS >::last(), G3D::Array< T, MIN_ELEMENTS >::num, and G3D::Array< T, MIN_ELEMENTS >::resize().
Referenced by G3D::MeshAlg::computeAdjacency(), and G3D::MeshAlg::weldBoundaryEdges().
operator=() [1/2]
template<class T , size_t MIN_ELEMENTS = 10> Array& G3D::Array< T, MIN_ELEMENTS >::operator= (const Array< T, MIN_ELEMENTS > & other) inline
Assignment operator. Will be private in a future release because this is slow and can be invoked by accident by novice C++ programmers. If you really want to copy an Array, use the explicit copy constructor.
Definition at line 191 of file Array.h.
{
        resize(other.num);
        for (int i = 0; i < (int)num; ++i) {
            data[i] = other[i];
        }
        return *this;
    }
References G3D::Array< T, MIN_ELEMENTS >::num, and G3D::Array< T, MIN_ELEMENTS >::resize().
operator=() [2/2]
template<class T , size_t MIN_ELEMENTS = 10> Array& G3D::Array< T, MIN_ELEMENTS >::operator= (const std::vector< T > & other) inline
Definition at line 199 of file Array.h.
{
        resize(other.size());
        for (size_t i = 0; i < num; ++i) {
            data[i] = other[i];
        }
        return *this;
    }
References G3D::Array< T, MIN_ELEMENTS >::num, and G3D::Array< T, MIN_ELEMENTS >::resize().
operator[]() [1/6]
template<class T , size_t MIN_ELEMENTS = 10> T& G3D::Array< T, MIN_ELEMENTS >::operator[] (int n) inline
Performs bounds checks in debug mode
Definition at line 870 of file Array.h.
{
         debugAssertM((n >= 0) && (n < (int)num),
                      format("Array index out of bounds. n = %d, size() = %d", (int)n, (int)num));
         debugAssert(data!=NULL);
         return data[n];
    }
References debugAssert, debugAssertM, G3D::format(), NULL, and G3D::Array< T, MIN_ELEMENTS >::num.
operator[]() [2/6]
template<class T , size_t MIN_ELEMENTS = 10> const T& G3D::Array< T, MIN_ELEMENTS >::operator[] (int n) const inline
Performs bounds checks in debug mode
Definition at line 891 of file Array.h.
{
         debugAssert((n >= 0) && (n < (int)num));
         debugAssert(data != NULL);
         return data[n];
     }
References debugAssert, NULL, and G3D::Array< T, MIN_ELEMENTS >::num.
operator[]() [3/6]
template<class T , size_t MIN_ELEMENTS = 10> T& G3D::Array< T, MIN_ELEMENTS >::operator[] (uint32 n) inline
Definition at line 877 of file Array.h.
{
        debugAssertM(n < (uint32)num, format("Array index out of bounds. n = %d, size() = %d",
                                             (int)n, (int)num));
        return data[n];
    }
References debugAssertM, G3D::format(), and G3D::Array< T, MIN_ELEMENTS >::num.
operator[]() [4/6]
template<class T , size_t MIN_ELEMENTS = 10> const T& G3D::Array< T, MIN_ELEMENTS >::operator[] (uint32 n) const inline
Definition at line 897 of file Array.h.
{
         debugAssert((n < (uint32)num));
         debugAssert(data!=NULL);
         return data[n];
     }
References debugAssert, NULL, and G3D::Array< T, MIN_ELEMENTS >::num.
operator[]() [5/6]
template<class T , size_t MIN_ELEMENTS = 10> T& G3D::Array< T, MIN_ELEMENTS >::operator[] (uint64 n) inline
Definition at line 883 of file Array.h.
{
        debugAssertM(n < (uint64)num, format("Array index out of bounds. n = %d, size() = %d", (int)n, (int)num));
        return data[n];
    }
References debugAssertM, G3D::format(), and G3D::Array< T, MIN_ELEMENTS >::num.
operator[]() [6/6]
template<class T , size_t MIN_ELEMENTS = 10> const T& G3D::Array< T, MIN_ELEMENTS >::operator[] (uint64 n) const inline
Definition at line 903 of file Array.h.
{
         debugAssert((n < (uint64)num));
         debugAssert(data!=NULL);
         return data[n];
     }
References debugAssert, NULL, and G3D::Array< T, MIN_ELEMENTS >::num.
partition() [1/2]
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::partition (const T & partitionElement, Array< T > & ltArray, Array< T > & eqArray, Array< T > & gtArray) const inline
Uses < and == on elements to perform a partition. See partition().
Definition at line 1231 of file Array.h.
{
         partition(partitionElement, ltArray, eqArray, gtArray, typename Array<T>::DefaultComparator());
     }
References G3D::Array< T, MIN_ELEMENTS >::partition().
partition() [2/2]
template<class T , size_t MIN_ELEMENTS = 10> template<typename Comparator > void G3D::Array< T, MIN_ELEMENTS >::partition (const T & partitionElement, Array< T > & ltArray, Array< T > & eqArray, Array< T > & gtArray, const Comparator & comparator) const inline
The output arrays are resized with fastClear() so that if they are already of the same size as this array no memory is allocated during partitioning.
Parameters
comparator A function, or class instance with an overloaded operator() that compares two elements of type T and returns 0 if they are equal, -1 if the second is smaller, and 1 if the first is smaller (i.e., following the conventions of std::string::compare). For example:
int compare(int A, int B) {
    if (A < B) {
        return 1;
    } else if (A == B) {
        return 0;
    } else {
        return -1;
    }
}
Definition at line 1196 of file Array.h.
{
         // Make sure all arrays are independent
         debugAssert(&ltArray != this);
         debugAssert(&eqArray != this);
         debugAssert(&gtArray != this);
         debugAssert(&ltArray != &eqArray);
         debugAssert(&ltArray != &gtArray);
         debugAssert(&eqArray != &gtArray);
         // Clear the arrays
         ltArray.fastClear();
         eqArray.fastClear();
         gtArray.fastClear();
         // Form a table of buckets for lt, eq, and gt
         Array<T>* bucket[3] = {&ltArray, &eqArray, &gtArray};
         for (size_t i = 0; i < num; ++i) {
             int c = comparator(partitionElement, data[i]);
             debugAssertM(c >= -1 && c <= 1, "Comparator returned an illegal value.");
             // Insert into the correct bucket, 0, 1, or 2
             bucket[c + 1]->append(data[i]);
         }
     }
References G3D::Array< T, MIN_ELEMENTS >::append(), mpq::c, debugAssert, debugAssertM, G3D::Array< T, MIN_ELEMENTS >::fastClear(), and G3D::Array< T, MIN_ELEMENTS >::num.
Referenced by G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::makeNode(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::makeNode(), G3D::Array< T, MIN_ELEMENTS >::medianPartition(), and G3D::Array< T, MIN_ELEMENTS >::partition().
pop()
template<class T , size_t MIN_ELEMENTS = 10> T G3D::Array< T, MIN_ELEMENTS >::pop (bool shrinkUnderlyingArrayIfNecessary = true) inline
Removes the last element and returns it. By default, shrinks the underlying array.
Definition at line 839 of file Array.h.
{
        debugAssert(num > 0);
        T temp = data[num - 1];
        resize(num - 1, shrinkUnderlyingArrayIfNecessary);
        return temp;
    }
References debugAssert, G3D::Array< T, MIN_ELEMENTS >::num, and G3D::Array< T, MIN_ELEMENTS >::resize().
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::clearData(), and G3D::Array< T, MIN_ELEMENTS >::pop_back().
pop_back()
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::pop_back () inline
"The member function removes the last element of the controlled sequence, which must be non-empty." For compatibility with std::vector.
Definition at line 787 of file Array.h.
{
        pop();
    }
References G3D::Array< T, MIN_ELEMENTS >::pop().
popDiscard()
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::popDiscard (bool shrinkUnderlyingArrayIfNecessary = false) inline
Pops the last element and discards it without returning anything. Faster than pop. By default, does not shrink the underlying array.
Definition at line 848 of file Array.h.
{
        debugAssert(num > 0);
        resize(num - 1, shrinkUnderlyingArrayIfNecessary);
    }
References debugAssert, G3D::Array< T, MIN_ELEMENTS >::num, and G3D::Array< T, MIN_ELEMENTS >::resize().
push() [1/2]
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::push (const Array< T > & array) inline
Definition at line 776 of file Array.h.
{
        append(array);
    }
References G3D::Array< T, MIN_ELEMENTS >::append(), and array.
push() [2/2]
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::push (const T & value) inline
Pushes an element onto the end (appends)
Definition at line 772 of file Array.h.
{
        append(value);
    }
References G3D::Array< T, MIN_ELEMENTS >::append().
Referenced by G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::clearData(), G3D::CollisionDetection::penetrationDepthForFixedBoxFixedBox(), and G3D::Array< T, MIN_ELEMENTS >::push_back().
push_back()
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::push_back (const T & v) inline
Alias to provide std::vector compatibility
Definition at line 781 of file Array.h.
{
        push(v);
    }
References G3D::Array< T, MIN_ELEMENTS >::push().
Referenced by MMAP::TerrainBuilder::copyIndices(), and MMAP::TerrainBuilder::copyVertices().
randomElement() [1/2]
template<class T , size_t MIN_ELEMENTS = 10> T& G3D::Array< T, MIN_ELEMENTS >::randomElement () inline
Definition at line 909 of file Array.h.
{
         debugAssert(num > 0);
         debugAssert(data!=NULL);
         return data[iRandom(0, (int)num - 1)];
     }
References debugAssert, G3D::iRandom(), NULL, and G3D::Array< T, MIN_ELEMENTS >::num.
randomElement() [2/2]
template<class T , size_t MIN_ELEMENTS = 10> const T& G3D::Array< T, MIN_ELEMENTS >::randomElement () const inline
Definition at line 915 of file Array.h.
{
         debugAssert(num > 0);
         debugAssert(data!=NULL);
         return data[iRandom(0, num - 1)];
     }
References debugAssert, G3D::iRandom(), NULL, and G3D::Array< T, MIN_ELEMENTS >::num.
randomize()
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::randomize () inline
Redistributes the elements so that the new order is statistically independent of the original order. O(n) time.
Definition at line 1407 of file Array.h.
                      {
         T temp;
         for (int i = size() - 1; i >= 0; --i) {
             int x = iRandom(0, i);
             temp = data[i];
             data[i] = data[x];
             data[x] = temp;
         }
     }
References G3D::iRandom(), G3D::Array< T, MIN_ELEMENTS >::size(), and G3D::x.
realloc()
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::realloc (size_t oldNum) inline private
Allocates a new array of size numAllocated (not a parameter to the method) and then copies at most oldNum elements from the old array to it. Destructors are called for oldNum elements of the old array.
Definition at line 151 of file Array.h.
{
          T* oldData = data;
          // The allocation is separate from the constructor invocation because we don't want
          // to pay for the cost of constructors until the newly allocated
          // elements are actually revealed to the application.  They
          // will be constructed in the resize() method.
          data = (T*)m_memoryManager->alloc(sizeof(T) * numAllocated);
          alwaysAssertM(data, "Memory manager returned NULL: out of memory?");
          // Call the copy constructors
          {const size_t N = G3D::min(oldNum, numAllocated);
           const T* end = data + N;
           T* oldPtr = oldData;
           for (T* ptr = data; ptr < end; ++ptr, ++oldPtr) {
              // Use placement new to invoke the constructor at the location
              // that we determined.  Use the copy constructor to make the assignment.
              const T* constructed = new (ptr) T(*oldPtr);
              (void)constructed;
              debugAssertM(constructed == ptr,
                  "new returned a different address than the one provided by Array.");
          }}
          // Call destructors on the old array (if there is no destructor, this will compile away)
          {const T* end = oldData + oldNum;
           for (T* ptr = oldData; ptr < end; ++ptr) {
               ptr->~T();
          }}
          m_memoryManager->free(oldData);
     }
References alwaysAssertM, G3D::Array< T, MIN_ELEMENTS >::data, debugAssertM, G3D::Array< T, MIN_ELEMENTS >::end(), G3D::Array< T, MIN_ELEMENTS >::m_memoryManager, G3D::min(), G3D::Array< T, MIN_ELEMENTS >::numAllocated, and ptr().
Referenced by G3D::Array< T, MIN_ELEMENTS >::resize(), and G3D::Array< T, MIN_ELEMENTS >::trimToSize().
remove() [1/2]
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::remove (int index, int count = 1) inline
Definition at line 1059 of file Array.h.
{
         debugAssert((index >= 0) && (index < (int)num));
         debugAssert((count > 0) && (index + count <= (int)num));
         remove(begin() + index, count);
     }
References G3D::Array< T, MIN_ELEMENTS >::begin(), count(), debugAssert, index, G3D::Array< T, MIN_ELEMENTS >::num, and G3D::Array< T, MIN_ELEMENTS >::remove().
remove() [2/2]
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::remove (Iterator element, int count = 1) inline
Removes count elements from the array referenced either by index or Iterator.
Definition at line 1046 of file Array.h.
{
         debugAssert((element >= begin()) && (element < end()));
         debugAssert((count > 0) && (element + count) <= end());
         Iterator last = end() - count;
         while(element < last) {
             element[0] = element[count];
             ++element;
         }
         resize(num - count);
     }
References G3D::Array< T, MIN_ELEMENTS >::begin(), count(), debugAssert, G3D::Array< T, MIN_ELEMENTS >::end(), G3D::Array< T, MIN_ELEMENTS >::last(), G3D::Array< T, MIN_ELEMENTS >::num, and G3D::Array< T, MIN_ELEMENTS >::resize().
Referenced by G3D::Array< T, MIN_ELEMENTS >::remove(), and G3D::zipfileExists().
removeNulls()
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::removeNulls () inline
Remove all NULL elements in linear time without affecting order of the other elements.
Definition at line 1435 of file Array.h.
{
          int nextNull = 0;
          for (int i = 0; i < size(); ++i) {
              if (notNull(data[i])) {
                  if (i > nextNull) {
                     // Move value i down to squeeze out NULLs
                     data[nextNull] = data[i];
                  }
                 ++nextNull;
              }
          }
          resize(nextNull, false);
     }
References G3D::notNull(), G3D::Array< T, MIN_ELEMENTS >::resize(), and G3D::Array< T, MIN_ELEMENTS >::size().
reserve()
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::reserve (int n) inline
Ensures that future append() calls can grow up to size n without allocating memory.
Definition at line 1421 of file Array.h.
{
         debugAssert(n >= size());
         const int oldSize = size();
         resize(n);
         resize(oldSize, false);
     }
References debugAssert, G3D::Array< T, MIN_ELEMENTS >::resize(), and G3D::Array< T, MIN_ELEMENTS >::size().
Referenced by G3D::_internal::WeldHelper::process().
resize()
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::resize (size_t n, bool shrinkIfNecessary = true) inline
Parameters
shrinkIfNecessary if false, memory will never be reallocated when the array shrinks. This makes resizing much faster but can waste memory. Default = true.
See also
clear, trimToSize
Definition at line 492 of file Array.h.
{
         alwaysAssertM(n < 0xFFFFFFFF, "This implementation does not support arrays with more than 2^32 elements, although the size in memory may be larger.");
         if (num == n) {
             return;
         }
         size_t oldNum = num;
         num = n;
         // Call the destructors on newly hidden elements if there are any
         for (size_t i = num; i < oldNum; ++i) {
             (data + i)->~T();
         }
         // Once allocated, always maintain MIN_ELEMENTS elements or 32 bytes, whichever is higher.
         const size_t minSize = G3D::max(MIN_ELEMENTS, (size_t)(MIN_BYTES / sizeof(T)));
         if ((MIN_ELEMENTS == 0) && (MIN_BYTES == 0) && (n == 0) && shrinkIfNecessary) {
             // Deallocate the array completely
             numAllocated = 0;
             m_memoryManager->free(data);
             data = NULL;
             return;
         }
         if (num > numAllocated) {
           // Grow the underlying array
           if (numAllocated == 0) {
               // First allocation; grow to exactly the size requested to avoid wasting space.
               numAllocated = n;
               debugAssert(oldNum == 0);
               realloc(oldNum);
           } else {
               if (num < minSize) {
                   // Grow to at least the minimum size
                   numAllocated = minSize;
               } else {
                   // Increase the underlying size of the array.  Grow aggressively
                   // up to 64k, less aggressively up to 400k, and then grow relatively
                   // slowly (1.5x per resize) to avoid excessive space consumption.
                   //
                   // These numbers are tweaked according to performance tests.
                   double growFactor = 3.0f;
                   size_t oldSizeBytes = numAllocated * sizeof(T);
                   if (oldSizeBytes > 10000000) {
                       // Conserve memory more tightly above 10 MB
                       growFactor = 1.2f;
                   } else if (oldSizeBytes > 400000) {
                       // Avoid bloat above 400k
                       growFactor = 1.5f;
                   } else if (oldSizeBytes > 64000) {
                       // This is what std:: uses at all times
                       growFactor = 2.0f;
                   }
                   numAllocated = (num - numAllocated) + (size_t)(numAllocated * growFactor);
                   if (numAllocated < minSize) {
                       numAllocated = minSize;
                   }
               }
               realloc(oldNum);
           }
       } else if ((num <= numAllocated / 3) && shrinkIfNecessary && (num > minSize)) {
           // Shrink the underlying array
           // Only copy over old elements that still remain after resizing
           // (destructors were called for others if we're shrinking)
           realloc(min(num, oldNum));
       }
       // Call the constructors on newly revealed elements.
       // Do not use parens because we don't want the intializer
       // invoked for POD types.
       for (size_t i = oldNum; i < num; ++i) {
           new (data + i) T;
       }
    }
References alwaysAssertM, debugAssert, G3D::Array< T, MIN_ELEMENTS >::m_memoryManager, G3D::max(), G3D::min(), G3D::Array< T, MIN_ELEMENTS >::MIN_BYTES, NULL, G3D::Array< T, MIN_ELEMENTS >::num, G3D::Array< T, MIN_ELEMENTS >::numAllocated, and G3D::Array< T, MIN_ELEMENTS >::realloc().
Referenced by G3D::Array< T, MIN_ELEMENTS >::append(), G3D::Array< T, MIN_ELEMENTS >::clear(), G3D::MeshAlg::computeAdjacency(), G3D::MeshAlg::computeAreaStatistics(), G3D::MeshAlg::computeBounds(), G3D::MeshAlg::computeFaceNormals(), G3D::MeshAlg::computeNormals(), G3D::MeshAlg::computeTangentSpaceBasis(), G3D::Array< T, MIN_ELEMENTS >::copyFrom(), G3D::GImage::decodeICO(), G3D::UprightSpline::deserialize(), G3D::Array< T, MIN_ELEMENTS >::fastRemove(), G3D::gaussian1D(), G3D::GCamera::getClipPlanes(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::getKeys(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::getValues(), G3D::MeshAlg::identifyBackfaces(), G3D::Spline< Control >::init(), G3D::Array< T, MIN_ELEMENTS >::init(), G3D::Array< T, MIN_ELEMENTS >::insert(), G3D::Matrix::Impl::inverseInPlaceGaussJordan(), G3D::Array< T, MIN_ELEMENTS >::invokeDeleteOnAllElements(), G3D::Array< T, MIN_ELEMENTS >::next(), G3D::CoordinateFrame::normalToObjectSpace(), G3D::CoordinateFrame::normalToWorldSpace(), G3D::Array< T, MIN_ELEMENTS >::operator=(), G3D::CollisionDetection::penetrationDepthForFixedBoxFixedBox(), G3D::CollisionDetection::penetrationDepthForFixedBoxFixedPlane(), G3D::CollisionDetection::penetrationDepthForFixedSphereFixedBox(), G3D::CollisionDetection::penetrationDepthForFixedSphereFixedPlane(), G3D::CollisionDetection::penetrationDepthForFixedSphereFixedSphere(), G3D::CoordinateFrame::pointToObjectSpace(), G3D::CoordinateFrame::pointToWorldSpace(), G3D::Array< T, MIN_ELEMENTS >::pop(), G3D::Array< T, MIN_ELEMENTS >::popDiscard(), G3D::_internal::WeldHelper::process(), G3D::BinaryInput::readFixedLengthString(), G3D::Array< T, MIN_ELEMENTS >::remove(), G3D::Array< T, MIN_ELEMENTS >::removeNulls(), G3D::Array< T, MIN_ELEMENTS >::reserve(), G3D::MeshEdgeTable::resize(), G3D::_internal::WeldHelper::smoothNormals(), G3D::Matrix::svd(), G3D::MeshAlg::toIndexedTriList(), G3D::UprightSpline::UprightSpline(), G3D::CoordinateFrame::vectorToObjectSpace(), G3D::CoordinateFrame::vectorToWorldSpace(), G3D::LightweightConduit::waitingMessageType(), G3D::_internal::Welder::weld(), G3D::MeshAlg::weldAdjacency(), and G3D::MeshAlg::weldBoundaryEdges().
reverse()
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::reverse () inline
Reverse the elements of the array in place.
Definition at line 1069 of file Array.h.
                    {
         T temp;
         size_t n2 = num / 2;
         for (size_t i = 0; i < n2; ++i) {
             temp = data[num - 1 - i];
             data[num - 1 - i] = data[i];
             data[i] = temp;
         }
     }
References G3D::Array< T, MIN_ELEMENTS >::num.
Referenced by G3D::MeshAlg::generateGrid().
rfindIndex()
template<class T , size_t MIN_ELEMENTS = 10> int G3D::Array< T, MIN_ELEMENTS >::rfindIndex (const T & value) const inline
Returns the index of (the first occurance of) an index or -1 if not found. Searches from the right.
Definition at line 998 of file Array.h.
{
         for (int i = num -1 ; i >= 0; --i) {
             if (data[i] == value) {
                 return i;
             }
         }
         return -1;
     }
References G3D::Array< T, MIN_ELEMENTS >::num.
setAll()
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::setAll (const T & value) inline
Sets all elements currently in the array to
Parameters
value
Definition at line 469 of file Array.h.
{
        for (size_t i = 0; i < num; ++i) {
            data[i] = value;
        }
    }
References G3D::Array< T, MIN_ELEMENTS >::num.
size()
template<class T , size_t MIN_ELEMENTS = 10> int G3D::Array< T, MIN_ELEMENTS >::size () const inline
Number of elements in the array.
Definition at line 432 of file Array.h.
{
       return (int)num;
    }
References G3D::Array< T, MIN_ELEMENTS >::num.
Referenced by G3D::FileSystem::_clearCache(), G3D::FileSystem::_createDirectory(), G3D::Spline< Control >::append(), G3D::Array< T, MIN_ELEMENTS >::back(), MMAP::MapBuilder::buildMoveMapTile(), MMAP::MapBuilder::buildTile(), MMAP::TerrainBuilder::cleanVertices(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::clearData(), G3D::MeshAlg::computeAdjacency(), G3D::computeAppName(), G3D::MeshAlg::computeAreaStatistics(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::computeBounds(), G3D::MeshAlg::computeBounds(), G3D::_internal::WeldHelper::computeFaceNormals(), G3D::MeshAlg::computeFaceNormals(), G3D::SplineBase::computeIndex(), G3D::SplineBase::computeIndexInBounds(), G3D::MeshAlg::computeNormals(), G3D::MeshAlg::computeTangentSpaceBasis(), G3D::Array< T, MIN_ELEMENTS >::contains(), G3D::ThreadSet::contains(), MMAP::TerrainBuilder::copyIndices(), G3D::MeshAlg::countBoundaryEdges(), G3D::GUniqueID::create(), G3D::createDirectory(), G3D::cyclicCatmullRomSpline(), G3D::MeshAlg::debugCheckConsistency(), G3D::UprightSpline::deserialize(), G3D::SplineBase::duration(), G3D::Spline< Control >::evaluate(), G3D::Array< T, MIN_ELEMENTS >::fastRemove(), G3D::System::findDataFile(), G3D::generateFilenameBase(), G3D::MeshAlg::generateGrid(), MMAP::IntermediateValues::generateObjFile(), G3D::GCamera::getClipPlanes(), G3D::Spline< Control >::getControl(), G3D::SplineBase::getFinalInterval(), MMAP::MapBuilder::getGridBounds(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::getIntersectingMembers(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::getIntersectingMembers(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::getMembers(), G3D::WeakCache< Key, ValueRef >::getValues(), G3D::MeshAlg::identifyBackfaces(), G3D::Spline< Control >::init(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::insert(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::insert(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::insert(), G3D::ThreadSet::insert(), BIHWrap< T, BoundsFunc >::intersectPoint(), BIHWrap< T, BoundsFunc >::intersectRay(), G3D::Array< T, MIN_ELEMENTS >::length(), MMAP::TerrainBuilder::loadMap(), MMAP::TerrainBuilder::loadVMap(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::makeNode(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::makeNode(), G3D::Array< T, MIN_ELEMENTS >::medianPartition(), G3D::CoordinateFrame::normalToObjectSpace(), G3D::CoordinateFrame::normalToWorldSpace(), G3D::ThreadSet::numStarted(), G3D::MeshEdgeTable::Iterator::operator++(), G3D::SmallArray< T, N >::operator=(), G3D::PhysicsFrameSpline::operator==(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::PointHashGrid(), G3D::CoordinateFrame::pointToObjectSpace(), G3D::CoordinateFrame::pointToWorldSpace(), G3D::_internal::WeldHelper::process(), G3D::Array< T, MIN_ELEMENTS >::randomize(), G3D::LightweightConduit::receive(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::remove(), G3D::ThreadSet::remove(), G3D::ThreadSet::removeCompleted(), G3D::Array< T, MIN_ELEMENTS >::removeNulls(), G3D::Array< T, MIN_ELEMENTS >::reserve(), G3D::UprightSpline::serialize(), G3D::Any::serialize(), G3D::Spline< Control >::size(), G3D::ThreadSet::size(), G3D::_internal::WeldHelper::smoothNormals(), G3D::ThreadSet::start(), G3D::ThreadSet::terminate(), G3D::MeshAlg::toIndexedTriList(), G3D::toUpper(), G3D::Array< T, MIN_ELEMENTS >::trimToSize(), G3D::_internal::WeldHelper::unroll(), G3D::_internal::WeldHelper::updateTriLists(), G3D::CoordinateFrame::vectorToObjectSpace(), G3D::CoordinateFrame::vectorToWorldSpace(), G3D::ThreadSet::waitForCompletion(), G3D::LightweightConduit::waitingMessageType(), G3D::MeshAlg::weldAdjacency(), G3D::MeshAlg::weldBoundaryEdges(), and G3D::TextOutput::wordWrapIndentAppend().
sizeInMemory()
template<class T , size_t MIN_ELEMENTS = 10> size_t G3D::Array< T, MIN_ELEMENTS >::sizeInMemory () const inline
Number of bytes used by the array object and the memory allocated for it's data pointer. Does not include the memory of objects pointed to by objects in the data array
Definition at line 1430 of file Array.h.
{
         return sizeof(Array<T>) + (sizeof(T) * numAllocated);
     }
References G3D::Array< T, MIN_ELEMENTS >::numAllocated.
sort() [1/2]
template<class T , size_t MIN_ELEMENTS = 10> template<class LessThan > void G3D::Array< T, MIN_ELEMENTS >::sort (const LessThan & lessThan) inline
 Sort using a specific less-than function, e.g.:
bool __cdecl myLT(const MyClass& elem1, const MyClass& elem2) {
    return elem1.x < elem2.x;
}
Note that for pointer arrays, the const must come after the class name, e.g., Array<MyClass*> uses:
bool __cdecl myLT(MyClass*const& elem1, MyClass*const& elem2) {
    return elem1->x < elem2->x;
}
or a functor, e.g.,
bool
less_than_functor::operator()(const double& lhs, const double& rhs) const
{
return(lhs < rhs? true : false);
}
Definition at line 1111 of file Array.h.
{
         // Using std::sort, which according to http://www.open-std.org/JTC1/SC22/WG21/docs/D_4.cpp
         // was 2x faster than qsort for arrays around size 2000 on intel core2 with gcc
         std::sort(data, data + num, lessThan);
     }
References G3D::Array< T, MIN_ELEMENTS >::num.
Referenced by G3D::MeshAlg::computeAreaStatistics(), G3D::Any::serialize(), and G3D::Matrix::svd().
sort() [2/2]
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::sort (int direction = SORT_INCREASING) inline
Sorts the array in increasing order using the > or < operator. To invoke this method on Array<T>, T must override those operator. You can overide these operators as follows:
bool T::operator>(const T& other) const {
   return ...;
}
bool T::operator<(const T& other) const {
   return ...;
}
Definition at line 1130 of file Array.h.
{
         if (direction == SORT_INCREASING) {
             std::sort(data, data + num);
         } else {
             std::sort(data, data + num, compareGT);
         }
     }
References G3D::Array< T, MIN_ELEMENTS >::compareGT(), G3D::Array< T, MIN_ELEMENTS >::num, and G3D::SORT_INCREASING.
sortSubArray() [1/3]
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::sortSubArray (int beginIndex, int endIndex, bool(__cdecl *lessThan)(const T &elem1, const T &elem2)) inline
Definition at line 1149 of file Array.h.
{
         std::sort(data + beginIndex, data + endIndex + 1, lessThan);
     }
sortSubArray() [2/3]
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::sortSubArray (int beginIndex, int endIndex, int direction = SORT_INCREASING) inline
Sorts elements beginIndex through and including endIndex.
Definition at line 1141 of file Array.h.
{
         if (direction == SORT_INCREASING) {
             std::sort(data + beginIndex, data + endIndex + 1);
         } else {
             std::sort(data + beginIndex, data + endIndex + 1, compareGT);
         }
     }
References G3D::Array< T, MIN_ELEMENTS >::compareGT(), and G3D::SORT_INCREASING.
sortSubArray() [3/3]
template<class T , size_t MIN_ELEMENTS = 10> template<typename StrictWeakOrdering > void G3D::Array< T, MIN_ELEMENTS >::sortSubArray (int beginIndex, int endIndex, StrictWeakOrdering & lessThan) inline
The StrictWeakOrdering can be either a class that overloads the function call operator() or a function pointer of the form bool (__cdecl *lessThan)(const T& elem1, const T& elem2)
Definition at line 1158 of file Array.h.
{
         std::sort(data + beginIndex, data + endIndex + 1, lessThan);
     }
swap() [1/2]
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::swap (Array< T > & str) inline
"The member function swaps the controlled sequences between *this and str." Note that this is slower than the optimal std implementation.
For compatibility with std::vector.
Definition at line 860 of file Array.h.
{
        Array<T> temp = str;
        str = *this;
        *this = temp;
    }
swap() [2/2]
template<class T , size_t MIN_ELEMENTS = 10> static void G3D::Array< T, MIN_ELEMENTS >::swap (Array< T, MIN_ELEMENTS > & a, Array< T, MIN_ELEMENTS > & b) inline static
Exchanges all data between the two arrays, which are required to have a common MemoryManager. This is a convenient way to avoid large array copies when handing off data without involving reference counting or manual memory management. Beware that pointers or references into the arrays will access memory in the other array after the swap.
Definition at line 265 of file Array.h.
{
        alwaysAssertM(a.memoryManager() == b.memoryManager(), "The arrays are required to have the same memory manager");
         std::swap(a.data, b.data);
         std::swap(a.num, b.num);
         std::swap(a.numAllocated, b.numAllocated);
    }
References mpq::a, alwaysAssertM, b, and swap().
trimToSize()
template<class T , size_t MIN_ELEMENTS = 10> void G3D::Array< T, MIN_ELEMENTS >::trimToSize () inline
Resize this array to consume exactly the capacity required by its size.
See also
clear, resize, capacity, size
Definition at line 478 of file Array.h.
                      {
        if (size() != capacity()) {
            size_t oldNum = numAllocated;
            numAllocated = size();
            realloc(oldNum);
        }
    }
References G3D::Array< T, MIN_ELEMENTS >::capacity(), G3D::Array< T, MIN_ELEMENTS >::numAllocated, G3D::Array< T, MIN_ELEMENTS >::realloc(), and G3D::Array< T, MIN_ELEMENTS >::size().
Member Data Documentation
data
template<class T , size_t MIN_ELEMENTS = 10> T* G3D::Array< T, MIN_ELEMENTS >::data private
0...num-1 are initialized elements, num...numAllocated-1 are not
Definition at line 103 of file Array.h.
Referenced by G3D::Array< T, MIN_ELEMENTS >::_copy(), G3D::Array< T, MIN_ELEMENTS >::appendPOD(), G3D::Array< T, MIN_ELEMENTS >::begin(), G3D::Array< T, MIN_ELEMENTS >::copyPOD(), G3D::Array< T, MIN_ELEMENTS >::getCArray(), G3D::Array< T, MIN_ELEMENTS >::realloc(), and G3D::Map2D< Storage, Compute >::set().
m_memoryManager
template<class T , size_t MIN_ELEMENTS = 10> MemoryManager::Ref G3D::Array< T, MIN_ELEMENTS >::m_memoryManager private
Definition at line 108 of file Array.h.
Referenced by G3D::Array< T, MIN_ELEMENTS >::appendPOD(), G3D::Array< T, MIN_ELEMENTS >::clearAndSetMemoryManager(), G3D::Array< T, MIN_ELEMENTS >::copyPOD(), G3D::Array< T, MIN_ELEMENTS >::init(), G3D::Array< T, MIN_ELEMENTS >::memoryManager(), G3D::Array< T, MIN_ELEMENTS >::realloc(), G3D::Array< T, MIN_ELEMENTS >::resize(), and G3D::Array< T, MIN_ELEMENTS >::~Array().
MIN_BYTES
template<class T , size_t MIN_ELEMENTS = 10> const size_t G3D::Array< T, MIN_ELEMENTS >::MIN_BYTES = 32 static private
Once the array has been allocated, it will never deallocate the underlying array unless MIN_ELEMENTS is set to 0, MIN_BYTES is 0, and the array is empty.
Definition at line 100 of file Array.h.
Referenced by G3D::Array< T, MIN_ELEMENTS >::resize().
num
template<class T , size_t MIN_ELEMENTS = 10> size_t G3D::Array< T, MIN_ELEMENTS >::num private
Definition at line 105 of file Array.h.
Referenced by G3D::Array< T, MIN_ELEMENTS >::_copy(), G3D::Array< T, MIN_ELEMENTS >::append(), G3D::Array< T, MIN_ELEMENTS >::appendPOD(), G3D::Array< T, MIN_ELEMENTS >::copyPOD(), G3D::Array< T, MIN_ELEMENTS >::end(), G3D::Array< T, MIN_ELEMENTS >::fastRemove(), G3D::Array< T, MIN_ELEMENTS >::find(), G3D::Array< T, MIN_ELEMENTS >::findIndex(), G3D::Array< T, MIN_ELEMENTS >::first(), G3D::Array< T, MIN_ELEMENTS >::firstIndex(), G3D::Array< T, MIN_ELEMENTS >::inArray(), G3D::Array< T, MIN_ELEMENTS >::insert(), G3D::Array< T, MIN_ELEMENTS >::invokeDeleteOnAllElements(), G3D::Array< T, MIN_ELEMENTS >::last(), G3D::Array< T, MIN_ELEMENTS >::lastIndex(), G3D::Array< T, MIN_ELEMENTS >::middle(), G3D::Array< T, MIN_ELEMENTS >::middleIndex(), G3D::Array< T, MIN_ELEMENTS >::next(), G3D::Array< T, MIN_ELEMENTS >::operator=(), G3D::Array< T, MIN_ELEMENTS >::operator[](), G3D::Array< T, MIN_ELEMENTS >::partition(), G3D::Array< T, MIN_ELEMENTS >::pop(), G3D::Array< T, MIN_ELEMENTS >::popDiscard(), G3D::Array< T, MIN_ELEMENTS >::randomElement(), G3D::Array< T, MIN_ELEMENTS >::remove(), G3D::Array< T, MIN_ELEMENTS >::resize(), G3D::Array< T, MIN_ELEMENTS >::reverse(), G3D::Array< T, MIN_ELEMENTS >::rfindIndex(), G3D::Array< T, MIN_ELEMENTS >::setAll(), G3D::Array< T, MIN_ELEMENTS >::size(), G3D::Array< T, MIN_ELEMENTS >::sort(), and G3D::Array< T, MIN_ELEMENTS >::~Array().
numAllocated
template<class T , size_t MIN_ELEMENTS = 10> size_t G3D::Array< T, MIN_ELEMENTS >::numAllocated private
Definition at line 106 of file Array.h.
Referenced by G3D::Array< T, MIN_ELEMENTS >::append(), G3D::Array< T, MIN_ELEMENTS >::appendPOD(), G3D::Array< T, MIN_ELEMENTS >::capacity(), G3D::Array< T, MIN_ELEMENTS >::copyPOD(), G3D::Array< T, MIN_ELEMENTS >::realloc(), G3D::Array< T, MIN_ELEMENTS >::resize(), G3D::Array< T, MIN_ELEMENTS >::sizeInMemory(), G3D::Array< T, MIN_ELEMENTS >::trimToSize(), and G3D::Array< T, MIN_ELEMENTS >::~Array().
The documentation for this class was generated from the following file:
deps/g3dlite/include/G3D/Array.h