Azerotcore-wotlk: deps/mysqllite/mysys/my_lib.c File Reference
my_lib.c File Reference
#include "mysys_priv.h"
#include <m_string.h>
#include <my_dir.h>
#include "mysys_err.h"
Macros
#define dirent direct
#define NAMLEN(dirent) (dirent)->d_namlen
#define READDIR(A, B, C) (!(C=readdir(A)))
#define ENTRIES_START_SIZE (8192/sizeof(FILEINFO))
#define ENTRIES_INCREMENT (65536/sizeof(FILEINFO))
#define NAMES_START_SIZE 32768
Functions
static int comp_names (struct fileinfo *a, struct fileinfo *b)
void my_dirend (MY_DIR *buffer)
MY_DIR * my_dir (const char *path, myf MyFlags)
char * directory_file_name (char *dst, const char *src)
int my_fstat (File Filedes, MY_STAT *stat_area, myf MyFlags __attribute__((unused)))
MY_STAT * my_stat (const char *path, MY_STAT *stat_area, myf my_flags)
Macro Definition Documentation
dirent
#define dirent direct
Definition at line 26 of file my_lib.c.
ENTRIES_INCREMENT
#define ENTRIES_INCREMENT (65536/sizeof(FILEINFO))
Definition at line 56 of file my_lib.c.
ENTRIES_START_SIZE
#define ENTRIES_START_SIZE (8192/sizeof(FILEINFO))
Definition at line 55 of file my_lib.c.
NAMES_START_SIZE
#define NAMES_START_SIZE 32768
Definition at line 57 of file my_lib.c.
NAMLEN
#define NAMLEN (dirent) (dirent)->d_namlen
Definition at line 27 of file my_lib.c.
READDIR
#define READDIR (A, B, C) (!(C=readdir(A)))
Definition at line 47 of file my_lib.c.
Function Documentation
comp_names()
static int comp_names (struct fileinfo * a, struct fileinfo * b) static
Definition at line 82 of file my_lib.c.
 {
   return (strcmp(a->name,b->name));
 } /* comp_names */
References mpq::a, and b.
Referenced by my_dir().
directory_file_name()
char* directory_file_name (char * dst, const char * src)
Definition at line 196 of file my_lib.c.
 {
   /* Process as Unix format: just remove test the final slash. */
   char *end;
   if (src[0] == 0)
     src= (char*) ".";               /* Use empty as current */
   end=strmov(dst, src);
   if (end[-1] != FN_LIBCHAR)
   {
     end[0]=FN_LIBCHAR;              /* Add last '/' */
     end[1]='\0';
   }
   return dst;
 }
References FN_LIBCHAR, and strmov().
Referenced by my_dir().
my_dir()
MY_DIR* my_dir (const char * path, myf MyFlags)
Definition at line 90 of file my_lib.c.
 {
   char          *buffer;
   MY_DIR        *result= 0;
   FILEINFO      finfo;
   DYNAMIC_ARRAY *dir_entries_storage;
   MEM_ROOT      *names_storage;
   DIR       *dirp;
   struct dirent *dp;
   char      tmp_path[FN_REFLEN+1],*tmp_file;
   char  dirent_tmp[sizeof(struct dirent)+_POSIX_PATH_MAX+1];
   DBUG_ENTER("my_dir");
   DBUG_PRINT("my",("path: '%s' MyFlags: %d",path,MyFlags));
 #if !defined(HAVE_READDIR_R)
   mysql_mutex_lock(&THR_LOCK_open);
 #endif
   dirp = opendir(directory_file_name(tmp_path,(char *) path));
 #if defined(__amiga__)
   if ((dirp->dd_fd) < 0)            /* Directory doesn't exists */
     goto error;
 #endif
   if (dirp == NULL ||
       ! (buffer= my_malloc(ALIGN_SIZE(sizeof(MY_DIR)) +
                            ALIGN_SIZE(sizeof(DYNAMIC_ARRAY)) +
                            sizeof(MEM_ROOT), MyFlags)))
     goto error;
   dir_entries_storage= (DYNAMIC_ARRAY*)(buffer + ALIGN_SIZE(sizeof(MY_DIR)));
   names_storage= (MEM_ROOT*)(buffer + ALIGN_SIZE(sizeof(MY_DIR)) +
                              ALIGN_SIZE(sizeof(DYNAMIC_ARRAY)));
   if (my_init_dynamic_array(dir_entries_storage, sizeof(FILEINFO),
                             ENTRIES_START_SIZE, ENTRIES_INCREMENT))
   {
     my_free(buffer);
     goto error;
   }
   init_alloc_root(names_storage, NAMES_START_SIZE, NAMES_START_SIZE);
   /* MY_DIR structure is allocated and completly initialized at this point */
   result= (MY_DIR*)buffer;
   tmp_file=strend(tmp_path);
   dp= (struct dirent*) dirent_tmp;
   while (!(READDIR(dirp,(struct dirent*) dirent_tmp,dp)))
   {
     if (!(finfo.name= strdup_root(names_storage, dp->d_name)))
       goto error;
     if (MyFlags & MY_WANT_STAT)
     {
       if (!(finfo.mystat= (MY_STAT*)alloc_root(names_storage,
                                                sizeof(MY_STAT))))
         goto error;
       bzero(finfo.mystat, sizeof(MY_STAT));
       (void) strmov(tmp_file,dp->d_name);
       (void) my_stat(tmp_path, finfo.mystat, MyFlags);
       if (!(finfo.mystat->st_mode & MY_S_IREAD))
         continue;
     }
     else
       finfo.mystat= NULL;
     if (push_dynamic(dir_entries_storage, (uchar*)&finfo))
       goto error;
   }
   (void) closedir(dirp);
 #if !defined(HAVE_READDIR_R)
   mysql_mutex_unlock(&THR_LOCK_open);
 #endif
   result->dir_entry= (FILEINFO *)dir_entries_storage->buffer;
   result->number_off_files= dir_entries_storage->elements;
   if (!(MyFlags & MY_DONT_SORT))
     my_qsort((void *) result->dir_entry, result->number_off_files,
           sizeof(FILEINFO), (qsort_cmp) comp_names);
   DBUG_RETURN(result);
  error:
 #if !defined(HAVE_READDIR_R)
   mysql_mutex_unlock(&THR_LOCK_open);
 #endif
   my_errno=errno;
   if (dirp)
     (void) closedir(dirp);
   my_dirend(result);
   if (MyFlags & (MY_FAE | MY_WME))
     my_error(EE_DIR,MYF(ME_BELL+ME_WAITTANG),path,my_errno);
   DBUG_RETURN((MY_DIR *) NULL);
 } /* my_dir */
References ALIGN_SIZE, alloc_root(), buffer, st_dynamic_array::buffer, bzero, closedir(), comp_names(), dirent::d_name, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, directory_file_name(), EE_DIR, st_dynamic_array::elements, ENTRIES_INCREMENT, ENTRIES_START_SIZE, errno, error(), FN_REFLEN, if(), init_alloc_root(), ME_BELL, ME_WAITTANG, my_dirend(), MY_DONT_SORT, my_errno, my_error(), MY_FAE, my_free(), my_init_dynamic_array, my_malloc(), my_qsort(), MY_S_IREAD, MY_STAT, my_stat(), MY_WANT_STAT, MY_WME, MYF, mysql_mutex_lock, mysql_mutex_unlock, fileinfo::mystat, fileinfo::name, NAMES_START_SIZE, NULL, opendir(), push_dynamic, qsort_cmp, READDIR, strdup_root(), strend(), strmov(), and THR_LOCK_open.
Referenced by search_default_file_with_ext().
my_dirend()
void my_dirend (MY_DIR * buffer)
Definition at line 65 of file my_lib.c.
 {
   DBUG_ENTER("my_dirend");
   if (buffer)
   {
     delete_dynamic((DYNAMIC_ARRAY*)((char*)buffer +
                                     ALIGN_SIZE(sizeof(MY_DIR))));
     free_root((MEM_ROOT*)((char*)buffer + ALIGN_SIZE(sizeof(MY_DIR)) +
                           ALIGN_SIZE(sizeof(DYNAMIC_ARRAY))), MYF(0));
     my_free(buffer);
   }
   DBUG_VOID_RETURN;
 } /* my_dirend */
References ALIGN_SIZE, DBUG_ENTER, DBUG_VOID_RETURN, delete_dynamic(), free_root(), my_free(), and MYF.
Referenced by my_dir(), and search_default_file_with_ext().
my_fstat()
int my_fstat (File Filedes, MY_STAT * stat_area, myf MyFlags __attribute__(unused))
Definition at line 382 of file my_lib.c.
 {
   DBUG_ENTER("my_fstat");
   DBUG_PRINT("my",("fd: %d  MyFlags: %d", Filedes, MyFlags));
 #ifdef _WIN32
   DBUG_RETURN(my_win_fstat(Filedes, stat_area));
 #else
   DBUG_RETURN(fstat(Filedes, (struct stat *) stat_area));
 #endif
 }
References DBUG_ENTER, DBUG_PRINT, and DBUG_RETURN.
my_stat()
MY_STAT* my_stat (const char * path, MY_STAT * stat_area, myf my_flags)
Definition at line 395 of file my_lib.c.
 {
   int m_used;
   DBUG_ENTER("my_stat");
   DBUG_PRINT("my", ("path: '%s'  stat_area: 0x%lx  MyFlags: %d", path,
                     (long) stat_area, my_flags));
   if ((m_used= (stat_area == NULL)))
     if (!(stat_area= (MY_STAT *) my_malloc(sizeof(MY_STAT), my_flags)))
       goto error;
 #ifndef _WIN32
     if (! stat((char *) path, (struct stat *) stat_area) )
       DBUG_RETURN(stat_area);
 #else
     if (! my_win_stat(path, stat_area) )
       DBUG_RETURN(stat_area);
 #endif
   DBUG_PRINT("error",("Got errno: %d from stat", errno));
   my_errno= errno;
   if (m_used)                   /* Free if new area */
     my_free(stat_area);
 error:
   if (my_flags & (MY_FAE+MY_WME))
   {
     my_error(EE_STAT, MYF(ME_BELL+ME_WAITTANG),path,my_errno);
     DBUG_RETURN((MY_STAT *) NULL);
   }
   DBUG_RETURN((MY_STAT *) NULL);
 } /* my_stat */
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_STAT, errno, error(), ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_FAE, my_free(), my_malloc(), MY_STAT, MY_WME, MYF, and NULL.
Referenced by inline_mysql_file_stat(), my_copy(), my_dir(), my_read_charset_file(), my_rename(), and search_default_file_with_ext().