Azerotcore-wotlk: deps/mysqllite/mysys/queues.c File Reference
queues.c File Reference
#include "mysys_priv.h"
#include "mysys_err.h"
#include <queues.h>
Functions
int init_queue (QUEUE *queue, uint max_elements, uint offset_to_key, pbool max_at_top, int(*compare)(void *, uchar *, uchar *), void *first_cmp_arg)
int init_queue_ex (QUEUE *queue, uint max_elements, uint offset_to_key, pbool max_at_top, int(*compare)(void *, uchar *, uchar *), void *first_cmp_arg, uint auto_extent)
int reinit_queue (QUEUE *queue, uint max_elements, uint offset_to_key, pbool max_at_top, int(*compare)(void *, uchar *, uchar *), void *first_cmp_arg)
int resize_queue (QUEUE *queue, uint max_elements)
void delete_queue (QUEUE *queue)
void queue_insert (register QUEUE *queue, uchar *element)
int queue_insert_safe (register QUEUE *queue, uchar *element)
uchar * queue_remove (register QUEUE *queue, uint idx)
void queue_replaced (QUEUE *queue)
void _downheap (register QUEUE *queue, uint idx)
void queue_fix (QUEUE *queue)
Function Documentation
_downheap()
void _downheap (register QUEUE * queue, uint idx)
Definition at line 272 of file queues.c.
 {
   uchar *element;
   uint elements,half_queue,offset_to_key, next_index;
   my_bool first= TRUE;
   uint start_idx= idx;
   offset_to_key=queue->offset_to_key;
   element=queue->root[idx];
   half_queue=(elements=queue->elements) >> 1;
   while (idx <= half_queue)
   {
     next_index=idx+idx;
     if (next_index < elements &&
     (queue->compare(queue->first_cmp_arg,
             queue->root[next_index]+offset_to_key,
             queue->root[next_index+1]+offset_to_key) *
      queue->max_at_top) > 0)
       next_index++;
     if (first &&
         (((queue->compare(queue->first_cmp_arg,
                           queue->root[next_index]+offset_to_key,
                           element+offset_to_key) * queue->max_at_top) >= 0)))
     {
       queue->root[idx]= element;
       return;
     }
     queue->root[idx]=queue->root[next_index];
     idx=next_index;
     first= FALSE;
   }
   next_index= idx >> 1;
   while (next_index > start_idx)
   {
     if ((queue->compare(queue->first_cmp_arg,
                        queue->root[next_index]+offset_to_key,
                        element+offset_to_key) *
          queue->max_at_top) < 0)
       break;
     queue->root[idx]=queue->root[next_index];
     idx=next_index;
     next_index= idx >> 1;
   }
   queue->root[idx]=element;
 }
References st_queue::compare, st_queue::elements, FALSE, detail::first(), st_queue::first_cmp_arg, idx, st_queue::max_at_top, st_queue::offset_to_key, st_queue::root, and TRUE.
Referenced by queue_fix(), queue_remove(), and queue_replaced().
delete_queue()
void delete_queue (QUEUE * queue)
Definition at line 194 of file queues.c.
 {
   DBUG_ENTER("delete_queue");
   my_free(queue->root);
   queue->root= NULL;
   DBUG_VOID_RETURN;
 }
References DBUG_ENTER, DBUG_VOID_RETURN, my_free(), NULL, and st_queue::root.
Referenced by end_thr_alarm().
init_queue()
int init_queue (QUEUE * queue, uint max_elements, uint offset_to_key, pbool max_at_top, int(*)(void *, uchar *, uchar *) compare, void * first_cmp_arg)
Definition at line 51 of file queues.c.
 {
   DBUG_ENTER("init_queue");
   if ((queue->root= (uchar **) my_malloc((max_elements+1)*sizeof(void*),
                      MYF(MY_WME))) == 0)
     DBUG_RETURN(1);
   queue->elements=0;
   queue->compare=compare;
   queue->first_cmp_arg=first_cmp_arg;
   queue->max_elements=max_elements;
   queue->offset_to_key=offset_to_key;
   queue_set_max_at_top(queue, max_at_top);
   DBUG_RETURN(0);
 }
References st_queue::compare, DBUG_ENTER, DBUG_RETURN, st_queue::elements, st_queue::first_cmp_arg, st_queue::max_elements, my_malloc(), MY_WME, MYF, st_queue::offset_to_key, queue_set_max_at_top, and st_queue::root.
Referenced by init_queue_ex().
init_queue_ex()
int init_queue_ex (QUEUE * queue, uint max_elements, uint offset_to_key, pbool max_at_top, int(*)(void *, uchar *, uchar *) compare, void * first_cmp_arg, uint auto_extent)
Definition at line 94 of file queues.c.
 {
   int ret;
   DBUG_ENTER("init_queue_ex");
   if ((ret= init_queue(queue, max_elements, offset_to_key, max_at_top, compare,
                        first_cmp_arg)))
     DBUG_RETURN(ret);
   queue->auto_extent= auto_extent;
   DBUG_RETURN(0);
 }
References st_queue::auto_extent, DBUG_ENTER, DBUG_RETURN, init_queue(), and ret.
queue_fix()
void queue_fix (QUEUE * queue)
Definition at line 361 of file queues.c.
 {
   uint i;
   for (i= queue->elements >> 1; i > 0; i--)
     _downheap(queue, i);
 }
References _downheap(), and st_queue::elements.
queue_insert()
void queue_insert (register QUEUE * queue, uchar * element)
Definition at line 205 of file queues.c.
 {
   reg2 uint idx, next;
   DBUG_ASSERT(queue->elements < queue->max_elements);
   queue->root[0]= element;
   idx= ++queue->elements;
   /* max_at_top swaps the comparison if we want to order by desc */
   while ((queue->compare(queue->first_cmp_arg,
                          element + queue->offset_to_key,
                          queue->root[(next= idx >> 1)] +
                          queue->offset_to_key) * queue->max_at_top) < 0)
   {
     queue->root[idx]= queue->root[next];
     idx= next;
   }
   queue->root[idx]= element;
 }
References st_queue::compare, DBUG_ASSERT, st_queue::elements, st_queue::first_cmp_arg, idx, st_queue::max_at_top, st_queue::max_elements, next(), st_queue::offset_to_key, reg2, and st_queue::root.
Referenced by queue_insert_safe().
queue_insert_safe()
int queue_insert_safe (register QUEUE * queue, uchar * element)
Definition at line 232 of file queues.c.
 {
   if (queue->elements == queue->max_elements)
   {
     if (!queue->auto_extent)
       return 2;
     else if (resize_queue(queue, queue->max_elements + queue->auto_extent))
       return 1;
   }
   queue_insert(queue, element);
   return 0;
 }
References st_queue::auto_extent, st_queue::elements, st_queue::max_elements, queue_insert(), and resize_queue().
queue_remove()
uchar* queue_remove (register QUEUE * queue, uint idx)
Definition at line 251 of file queues.c.
 {
   uchar *element;
   DBUG_ASSERT(idx < queue->max_elements);
   element= queue->root[++idx];  /* Intern index starts from 1 */
   queue->root[idx]= queue->root[queue->elements--];
   _downheap(queue, idx);
   return element;
 }
References _downheap(), DBUG_ASSERT, st_queue::elements, idx, and st_queue::root.
queue_replaced()
void queue_replaced (QUEUE * queue)
Definition at line 264 of file queues.c.
 {
   _downheap(queue,1);
 }
References _downheap().
Referenced by process_alarm_part2().
reinit_queue()
int reinit_queue (QUEUE * queue, uint max_elements, uint offset_to_key, pbool max_at_top, int(*)(void *, uchar *, uchar *) compare, void * first_cmp_arg)
Definition at line 131 of file queues.c.
 {
   DBUG_ENTER("reinit_queue");
   queue->elements=0;
   queue->compare=compare;
   queue->first_cmp_arg=first_cmp_arg;
   queue->offset_to_key=offset_to_key;
   queue_set_max_at_top(queue, max_at_top);
   resize_queue(queue, max_elements);
   DBUG_RETURN(0);
 }
References st_queue::compare, DBUG_ENTER, DBUG_RETURN, st_queue::elements, st_queue::first_cmp_arg, st_queue::offset_to_key, queue_set_max_at_top, and resize_queue().
resize_queue()
int resize_queue (QUEUE * queue, uint max_elements)
Definition at line 163 of file queues.c.
 {
   uchar **new_root;
   DBUG_ENTER("resize_queue");
   if (queue->max_elements == max_elements)
     DBUG_RETURN(0);
   if ((new_root= (uchar **) my_realloc((void *)queue->root,
                       (max_elements+1)*sizeof(void*),
                       MYF(MY_WME))) == 0)
     DBUG_RETURN(1);
   set_if_smaller(queue->elements, max_elements);
   queue->max_elements= max_elements;
   queue->root= new_root;
   DBUG_RETURN(0);
 }
References DBUG_ENTER, DBUG_RETURN, st_queue::elements, st_queue::max_elements, my_realloc(), MY_WME, MYF, st_queue::root, and set_if_smaller.
Referenced by queue_insert_safe(), reinit_queue(), and resize_thr_alarm().