Azerotcore-wotlk: G3D::PhysicsFrameSpline Class Reference
G3D::PhysicsFrameSpline Class Reference
#include <PhysicsFrameSpline.h>
Public Member Functions
PhysicsFrameSpline ()
PhysicsFrameSpline (const Any &any)
bool operator== (const PhysicsFrameSpline &a) const
bool operator!= (const PhysicsFrameSpline &a) const
void scaleControlPoints (float scaleFactor)
virtual void correct (PhysicsFrame &frame) const
virtual void ensureShortestPath (PhysicsFrame *A, int N) const
virtual Any toAny (const std::string &myName) const override
Any toAny () const
Public Member Functions inherited from G3D::Spline< PhysicsFrame >
Spline ()
Spline (const Any &any)
void append (float t, const PhysicsFrame &c)
void append (const PhysicsFrame &c)
void clear ()
int size () const
void getControl (int i, float &t, PhysicsFrame &c) const
PhysicsFrame evaluate (float s) const
Public Member Functions inherited from G3D::SplineBase
SplineBase ()
virtual ~SplineBase ()
float getFinalInterval () const
float duration () const
void computeIndex (float s, int &i, float &u) const
Additional Inherited Members
Static Public Member Functions inherited from G3D::SplineBase
static Matrix4 computeBasis ()
Public Attributes inherited from G3D::Spline< PhysicsFrame >
Array< PhysicsFrame > control
Public Attributes inherited from G3D::SplineBase
Array< float > time
SplineExtrapolationMode extrapolationMode
float finalInterval
SplineInterpolationMode interpolationMode
Protected Member Functions inherited from G3D::Spline< PhysicsFrame >
void getControls (int i, float *T, PhysicsFrame *A, int N) const
virtual void init (AnyTableReader &propertyTable)
Protected Member Functions inherited from G3D::SplineBase
void computeIndexInBounds (float s, int &i, float &u) const
Protected Attributes inherited from G3D::Spline< PhysicsFrame >
PhysicsFrame zero
Detailed Description
A subclass of Spline that keeps the rotation field of a PhysicsFrame normalized and rotating the short direction.
See also
UprightFrameSpline
Definition at line 21 of file PhysicsFrameSpline.h.
Constructor & Destructor Documentation
PhysicsFrameSpline() [1/2]
G3D::PhysicsFrameSpline::PhysicsFrameSpline ()
Definition at line 13 of file PhysicsFrameSpline.cpp.
 {}
PhysicsFrameSpline() [2/2]
G3D::PhysicsFrameSpline::PhysicsFrameSpline (const Any & any)
Accepts a table of properties, or any valid PhysicsFrame specification for a single control
Definition at line 16 of file PhysicsFrameSpline.cpp.
{
     if (beginsWith(any.name(), "PFrameSpline") ||
         beginsWith(any.name(), "PhysicsFrameSpline") ||
         beginsWith(any.name(), "CFrameSpline") ||
         beginsWith(any.name(), "CoordinateFrameSpline") ||
         beginsWith(any.name(), "UprightSpline") ||
         beginsWith(any.name(), "UprightFrameSpline")) {
         AnyTableReader t(any);
         init(t);
         t.verifyDone();
     } else {
         // Must be a single control point
         control.append(any);
         time.append(0);
     }
 }
References G3D::any(), G3D::Array< T, MIN_ELEMENTS >::append(), G3D::beginsWith(), G3D::Spline< PhysicsFrame >::control, G3D::Spline< PhysicsFrame >::init(), G3D::SplineBase::time, and G3D::AnyTableReader::verifyDone().
Member Function Documentation
correct()
void G3D::PhysicsFrameSpline::correct (PhysicsFrame & A) const virtual
Normalize or otherwise adjust this interpolated Control.
Reimplemented from G3D::Spline< PhysicsFrame >.
Definition at line 59 of file PhysicsFrameSpline.cpp.
{
     frame.rotation.unitize();
 }
References G3D::PhysicsFrame::rotation, and G3D::Quat::unitize().
ensureShortestPath()
void G3D::PhysicsFrameSpline::ensureShortestPath (PhysicsFrame * A, int N) const virtual
Mutates the array of N control points that begins at A. It is useful to override this method by one that wraps the values if they are angles or quaternions for which "shortest path" interpolation is significant.
Reimplemented from G3D::Spline< PhysicsFrame >.
Definition at line 69 of file PhysicsFrameSpline.cpp.
{
     for (int i = 1; i < N; ++i) {
         const Quat& p = A[i - 1].rotation;
         Quat& q = A[i].rotation;
         float cosphi = p.dot(q);
         if (cosphi < 0) {
             // Going the long way, so change the order
             q = -q;
         }
     }
 }
References G3D::Quat::dot(), and G3D::PhysicsFrame::rotation.
operator!=()
bool G3D::PhysicsFrameSpline::operator!= (const PhysicsFrameSpline & a) const inline
Definition at line 31 of file PhysicsFrameSpline.h.
{
         return ! ((*this) == a);
     }
References mpq::a.
operator==()
bool G3D::PhysicsFrameSpline::operator== (const PhysicsFrameSpline & a) const
Definition at line 34 of file PhysicsFrameSpline.cpp.
{
     if ((extrapolationMode == other.extrapolationMode) &&
         (time.size() == other.size()) &&
         (finalInterval == other.finalInterval) &&
         (control.size() == other.control.size())) {
         // Check actual values
         for (int i = 0; i < time.size(); ++i) {
             if (time[i] != other.time[i]) {
                 return false;
             }
         }
         for (int i = 0; i < control.size(); ++i) {
             if (control[i] != other.control[i]) {
                 return false;
             }
         }
         return true;
     } else {
         return false;
     }
 }
References G3D::Spline< PhysicsFrame >::control, G3D::Spline< Control >::control, G3D::SplineBase::extrapolationMode, G3D::SplineBase::finalInterval, G3D::Array< T, MIN_ELEMENTS >::size(), G3D::Spline< Control >::size(), and G3D::SplineBase::time.
scaleControlPoints()
void G3D::PhysicsFrameSpline::scaleControlPoints (float scaleFactor)
Mutates all underlying PhysicsFrames by scaling their translation by
Parameters
scaleFactor
Definition at line 63 of file PhysicsFrameSpline.cpp.
{
     for (int i = 0; i < control.size(); ++i) {
         control[i].translation *= scaleFactor;
     }
 }
References G3D::Spline< PhysicsFrame >::control.
toAny() [1/2]
Any G3D::PhysicsFrameSpline::toAny () const inline
Definition at line 45 of file PhysicsFrameSpline.h.
                       {
         return toAny("PFrameSpline");
     }
toAny() [2/2]
virtual Any G3D::PhysicsFrameSpline::toAny (const std::string & myName) const inline override virtual
Note that invoking classes can call setName on the returned value instead of passing a name in.
Reimplemented from G3D::Spline< PhysicsFrame >.
Definition at line 41 of file PhysicsFrameSpline.h.
{
         return Spline<PhysicsFrame>::toAny(myName);
     }
References G3D::Spline< Control >::toAny().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/PhysicsFrameSpline.h
deps/g3dlite/source/PhysicsFrameSpline.cpp