Azerotcore-wotlk: src/server/game/Instances/InstanceScript.cpp File Reference
InstanceScript.cpp File Reference
#include "Creature.h"
#include "CreatureAI.h"
#include "DatabaseEnv.h"
#include "GameObject.h"
#include "Group.h"
#include "InstanceScript.h"
#include "LFGMgr.h"
#include "Log.h"
#include "Map.h"
#include "Opcodes.h"
#include "Pet.h"
#include "Player.h"
#include "Spell.h"
Functions
bool InstanceHasScript (WorldObject const *obj, char const *scriptName)
Function Documentation
InstanceHasScript()
bool InstanceHasScript (WorldObject const * obj, char const * scriptName)
Definition at line 582 of file InstanceScript.cpp.
 {
     if (InstanceMap* instance = obj->GetMap()->ToInstanceMap())
     {
         return instance->GetScriptName() == scriptName;
     }
     return false;
 }
References WorldObject::GetMap(), and Map::ToInstanceMap().
Referenced by GetInstanceAI().