Azerotcore-wotlk: Acore::Impl::ChatCommands::ArgInfo< T, std::enable_if_t< std::is_integral_v< T >||std::is_floating_point_v< T > > > Struct Template Reference
Acore::Impl::ChatCommands::ArgInfo< T, std::enable_if_t< std::is_integral_v< T >||std::is_floating_point_v< T > > > Struct Template Reference
#include <ChatCommandArgs.h>
Static Public Member Functions
static ChatCommandResult TryConsume (T &val, ChatHandler const *handler, std::string_view args)
Detailed Description
template<typename T>
struct Acore::Impl::ChatCommands::ArgInfo< T, std::enable_if_t< std::is_integral_v< T >||std::is_floating_point_v< T > > >
Definition at line 54 of file ChatCommandArgs.h.
Member Function Documentation
TryConsume()
template<typename T > static ChatCommandResult Acore::Impl::ChatCommands::ArgInfo< T, std::enable_if_t< std::is_integral_v< T >||std::is_floating_point_v< T > > >::TryConsume (T & val, ChatHandler const * handler, std::string_view args) inline static
Definition at line 56 of file ChatCommandArgs.h.
         {
             auto [token, tail] = tokenize(args);
             if (token.empty())
                 return std::nullopt;
             if (Optional<T> v = StringTo<T>(token, 0))
                 val = *v;
             else
                 return FormatAcoreString(handler, LANG_CMDPARSER_STRING_VALUE_INVALID, STRING_VIEW_FMT_ARG(token), GetTypeName<T>().c_str());
             if constexpr (std::is_floating_point_v<T>)
             {
                 if (!std::isfinite(val))
                     return FormatAcoreString(handler, LANG_CMDPARSER_STRING_VALUE_INVALID, STRING_VIEW_FMT_ARG(token), GetTypeName<T>().c_str());
             }
             return tail;
         }
References Acore::Impl::ChatCommands::FormatAcoreString(), isfinite(), LANG_CMDPARSER_STRING_VALUE_INVALID, STRING_VIEW_FMT_ARG, and Acore::Impl::ChatCommands::tokenize().
The documentation for this struct was generated from the following file:
src/server/game/Chat/ChatCommands/ChatCommandArgs.h