Azerotcore-wotlk: npc_hallows_end_train_fire::npc_hallows_end_train_fireAI Struct Reference
npc_hallows_end_train_fire::npc_hallows_end_train_fireAI Struct Reference
Public Member Functions
npc_hallows_end_train_fireAI (Creature *creature)
void Reset () override
void UpdateAI (uint32 diff) override
void SpellHit (Unit *caster, const SpellInfo *spellInfo) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
uint32 timer
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 984 of file hallows_end.cpp.
Constructor & Destructor Documentation
npc_hallows_end_train_fireAI()
npc_hallows_end_train_fire::npc_hallows_end_train_fireAI::npc_hallows_end_train_fireAI (Creature * creature) inline
Definition at line 986 of file hallows_end.cpp.
                                                          : NullCreatureAI(creature)
         {
         }
Member Function Documentation
Reset()
void npc_hallows_end_train_fire::npc_hallows_end_train_fireAI::Reset () inline override virtual
Reimplemented from UnitAI.
Definition at line 991 of file hallows_end.cpp.
         {
             timer = 0;
         }
References timer.
SpellHit()
void npc_hallows_end_train_fire::npc_hallows_end_train_fireAI::SpellHit (Unit * caster, const SpellInfo * spellInfo) inline override virtual
Reimplemented from CreatureAI.
Definition at line 1004 of file hallows_end.cpp.
         {
             if (spellInfo->Id == SPELL_WATER_SPLASH && caster->ToPlayer())
             {
                 if (AuraEffect* aurEff = me->GetAuraEffect(SPELL_FIRE_AURA_BASE, EFFECT_0))
                 {
                     int32 amt = aurEff->GetAmount();
                     if (amt > 1)
                         aurEff->SetAmount(amt - 1);
                     else
                         me->RemoveAllAuras();
                     caster->ToPlayer()->KilledMonsterCredit(me->GetEntry());
                 }
             }
         }
References EFFECT_0, Unit::GetAuraEffect(), Object::GetEntry(), SpellInfo::Id, Player::KilledMonsterCredit(), CreatureAI::me, Unit::RemoveAllAuras(), SPELL_FIRE_AURA_BASE, SPELL_WATER_SPLASH, and Object::ToPlayer().
UpdateAI()
void npc_hallows_end_train_fire::npc_hallows_end_train_fireAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 996 of file hallows_end.cpp.
         {
             timer += diff;
             if (timer >= 5000)
                 if (!me->GetAuraEffect(SPELL_FIRE_AURA_BASE, EFFECT_0))
                     me->CastSpell(me, SPELL_FIRE_AURA_BASE, true);
         }
References Unit::CastSpell(), diff(), EFFECT_0, Unit::GetAuraEffect(), CreatureAI::me, SPELL_FIRE_AURA_BASE, and timer.
Member Data Documentation
timer
uint32 npc_hallows_end_train_fire::npc_hallows_end_train_fireAI::timer
Definition at line 990 of file hallows_end.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Events/hallows_end.cpp