Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/tsd_malloc_thread_cleanup.h File Reference
tsd_malloc_thread_cleanup.h File Reference
Macros
#define JEMALLOC_INTERNAL_TSD_MALLOC_THREAD_CLEANUP_H
#define JEMALLOC_TSD_TYPE_ATTR(type) __thread type JEMALLOC_TLS_MODEL
Functions
JEMALLOC_TSD_TYPE_ATTR (tsd_t) tsd_tls
JEMALLOC_TSD_TYPE_ATTR (bool) tsd_initialized
JEMALLOC_ALWAYS_INLINE bool tsd_cleanup_wrapper (void)
JEMALLOC_ALWAYS_INLINE bool tsd_boot0 (void)
JEMALLOC_ALWAYS_INLINE void tsd_boot1 (void)
JEMALLOC_ALWAYS_INLINE bool tsd_boot (void)
JEMALLOC_ALWAYS_INLINE bool tsd_booted_get (void)
JEMALLOC_ALWAYS_INLINE bool tsd_get_allocates (void)
JEMALLOC_ALWAYS_INLINE tsd_t * tsd_get (bool init)
JEMALLOC_ALWAYS_INLINE void tsd_set (tsd_t *val)
Variables
bool tsd_booted
Macro Definition Documentation
JEMALLOC_INTERNAL_TSD_MALLOC_THREAD_CLEANUP_H
#define JEMALLOC_INTERNAL_TSD_MALLOC_THREAD_CLEANUP_H
Definition at line 4 of file tsd_malloc_thread_cleanup.h.
JEMALLOC_TSD_TYPE_ATTR
#define JEMALLOC_TSD_TYPE_ATTR (type) __thread type JEMALLOC_TLS_MODEL
Definition at line 6 of file tsd_malloc_thread_cleanup.h.
Function Documentation
JEMALLOC_TSD_TYPE_ATTR() [1/2]
JEMALLOC_TSD_TYPE_ATTR (bool)
JEMALLOC_TSD_TYPE_ATTR() [2/2]
JEMALLOC_TSD_TYPE_ATTR (tsd_t)
tsd_boot()
JEMALLOC_ALWAYS_INLINE bool tsd_boot (void)
Definition at line 35 of file tsd_malloc_thread_cleanup.h.
                {
     return tsd_boot0();
 }
References tsd_boot0().
tsd_boot0()
JEMALLOC_ALWAYS_INLINE bool tsd_boot0 (void)
Definition at line 23 of file tsd_malloc_thread_cleanup.h.
                 {
     malloc_tsd_cleanup_register(&tsd_cleanup_wrapper);
     tsd_booted = true;
     return false;
 }
References malloc_tsd_cleanup_register, tsd_booted, and tsd_cleanup_wrapper().
Referenced by tsd_boot().
tsd_boot1()
JEMALLOC_ALWAYS_INLINE void tsd_boot1 (void)
Definition at line 30 of file tsd_malloc_thread_cleanup.h.
                 {
     /* Do nothing. */
 }
tsd_booted_get()
JEMALLOC_ALWAYS_INLINE bool tsd_booted_get (void)
Definition at line 40 of file tsd_malloc_thread_cleanup.h.
                      {
     return tsd_booted;
 }
References tsd_booted.
tsd_cleanup_wrapper()
JEMALLOC_ALWAYS_INLINE bool tsd_cleanup_wrapper (void)
Definition at line 14 of file tsd_malloc_thread_cleanup.h.
{
     if (tsd_initialized) {
         tsd_initialized = false;
         tsd_cleanup(&tsd_tls);
     }
     return tsd_initialized;
 }
References tsd_cleanup, and tsd_tls.
Referenced by tsd_boot0().
tsd_get()
JEMALLOC_ALWAYS_INLINE tsd_t* tsd_get (bool init)
Definition at line 51 of file tsd_malloc_thread_cleanup.h.
                    {
     return &tsd_tls;
 }
References tsd_tls.
tsd_get_allocates()
JEMALLOC_ALWAYS_INLINE bool tsd_get_allocates (void)
Definition at line 45 of file tsd_malloc_thread_cleanup.h.
{
     return false;
 }
tsd_set()
JEMALLOC_ALWAYS_INLINE void tsd_set (tsd_t * val)
Definition at line 55 of file tsd_malloc_thread_cleanup.h.
                     {
     assert(tsd_booted);
     if (likely(&tsd_tls != val)) {
         tsd_tls = (*val);
     }
     tsd_initialized = true;
 }
References assert(), likely, tsd_booted, and tsd_tls.
Variable Documentation
tsd_booted
bool tsd_booted extern
Definition at line 53 of file tsd.c.
Referenced by tsd_boot0(), tsd_booted_get(), and tsd_set().