Azerotcore-wotlk: npc_isle_of_conquest_turret::npc_isle_of_conquest_turretAI Struct Reference
npc_isle_of_conquest_turret::npc_isle_of_conquest_turretAI Struct Reference
Public Member Functions
npc_isle_of_conquest_turretAI (Creature *creature)
void JustDied (Unit *) override
void SpellHit (Unit *, SpellInfo const *spellInfo) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from VehicleAI
VehicleAI (Creature *creature)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void OnCharmed (bool apply) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void EnterCombat (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
uint32 faction
EventMap events
Additional Inherited Members
Static Public Member Functions inherited from VehicleAI
static int Permissible (Creature const *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 37 of file isle_of_conquest.cpp.
Constructor & Destructor Documentation
npc_isle_of_conquest_turretAI()
npc_isle_of_conquest_turret::npc_isle_of_conquest_turretAI::npc_isle_of_conquest_turretAI (Creature * creature) inline
Definition at line 39 of file isle_of_conquest.cpp.
 : VehicleAI(creature), faction(0) { }
Member Function Documentation
JustDied()
void npc_isle_of_conquest_turret::npc_isle_of_conquest_turretAI::JustDied (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 44 of file isle_of_conquest.cpp.
         {
             if (me->GetEntry() == NPC_KEEP_CANNON)
             {
                 faction = me->GetFaction();
                 me->Respawn();
                 me->UpdateEntry(NPC_BROKEN_KEEP_CANNON, nullptr, false);
                 me->RemoveVehicleKit();
                 me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_SPELLCLICK);
             }
         }
References faction, Object::GetEntry(), Unit::GetFaction(), CreatureAI::me, NPC_BROKEN_KEEP_CANNON, NPC_KEEP_CANNON, Unit::RemoveVehicleKit(), Creature::Respawn(), Object::SetFlag(), UNIT_NPC_FLAG_SPELLCLICK, UNIT_NPC_FLAGS, and Creature::UpdateEntry().
SpellHit()
void npc_isle_of_conquest_turret::npc_isle_of_conquest_turretAI::SpellHit (Unit * , SpellInfo const * spellInfo) inline override virtual
Reimplemented from CreatureAI.
Definition at line 56 of file isle_of_conquest.cpp.
         {
             if (spellInfo->Id == SPELL_REPAIR_TURRET_DUMMY && me->GetEntry() == NPC_BROKEN_KEEP_CANNON)
             {
                 me->UpdateEntry(NPC_KEEP_CANNON, nullptr, false);
                 if (faction)
                     me->SetFaction(faction);
                 me->CreateVehicleKit(510, NPC_KEEP_CANNON);
                 me->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_SPELLCLICK);
                 events.ScheduleEvent(EVENT_RESTORE_FLAG, 4000);
             }
         }
References Unit::CreateVehicleKit(), EVENT_RESTORE_FLAG, faction, Object::GetEntry(), SpellInfo::Id, CreatureAI::me, NPC_BROKEN_KEEP_CANNON, NPC_KEEP_CANNON, Object::RemoveFlag(), Unit::SetFaction(), SPELL_REPAIR_TURRET_DUMMY, UNIT_NPC_FLAG_SPELLCLICK, UNIT_NPC_FLAGS, and Creature::UpdateEntry().
UpdateAI()
void npc_isle_of_conquest_turret::npc_isle_of_conquest_turretAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from VehicleAI.
Definition at line 69 of file isle_of_conquest.cpp.
         {
             events.Update(diff);
             switch (events.ExecuteEvent())
             {
                 case EVENT_RESTORE_FLAG:
                     me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_SPELLCLICK);
                     break;
             }
             VehicleAI::UpdateAI(diff);
         }
References EVENT_RESTORE_FLAG, CreatureAI::me, Object::SetFlag(), UNIT_NPC_FLAG_SPELLCLICK, UNIT_NPC_FLAGS, and VehicleAI::UpdateAI().
Member Data Documentation
events
EventMap npc_isle_of_conquest_turret::npc_isle_of_conquest_turretAI::events
Definition at line 42 of file isle_of_conquest.cpp.
faction
uint32 npc_isle_of_conquest_turret::npc_isle_of_conquest_turretAI::faction
Definition at line 41 of file isle_of_conquest.cpp.
Referenced by JustDied(), and SpellHit().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/isle_of_conquest.cpp