Azerotcore-wotlk: npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI Struct Reference
npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI Struct Reference
Public Member Functions
npc_q24545_wretched_ghoulAI (Creature *c)
void Reset () override
void DoAction (int32 a) override
void AttackStart (Unit *who) override
bool CanAIAttack (const Unit *target) const override
void Activate ()
void Deactivate ()
void JustDied (Unit *) override
void JustRespawned () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1115 of file zone_dragonblight.cpp.
Constructor & Destructor Documentation
npc_q24545_wretched_ghoulAI()
npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::npc_q24545_wretched_ghoulAI (Creature * c) inline
Definition at line 1117 of file zone_dragonblight.cpp.
                                                  : ScriptedAI(c)
         {
             Deactivate();
         }
References Deactivate().
Member Function Documentation
Activate()
void npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::Activate () inline
Definition at line 1155 of file zone_dragonblight.cpp.
         {
             me->SetDisplayId(me->GetNativeDisplayId());
             me->CastSpell(me, SPELL_SAC_EMERGE, true);
             me->m_Events.AddEvent(new SACActivateEvent(me), me->m_Events.CalculateTime(4000));
         }
References EventProcessor::AddEvent(), EventProcessor::CalculateTime(), Unit::CastSpell(), Unit::GetNativeDisplayId(), Unit::m_Events, ScriptedAI::me, Creature::SetDisplayId(), and SPELL_SAC_EMERGE.
Referenced by DoAction().
AttackStart()
void npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1140 of file zone_dragonblight.cpp.
         {
             if (me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE))
                 return;
             ScriptedAI::AttackStart(who);
         }
References ScriptedAI::AttackStart(), Object::HasFlag(), ScriptedAI::me, UNIT_FIELD_FLAGS, and UNIT_FLAG_NOT_SELECTABLE.
CanAIAttack()
bool npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::CanAIAttack (const Unit * target) const inline override virtual
Reimplemented from UnitAI.
Definition at line 1147 of file zone_dragonblight.cpp.
         {
             if (me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE) || target->HasUnitState(UNIT_STATE_STUNNED) || me->GetDisplayId() == 11686)
                 return false;
             Position homePos = me->GetHomePosition();
             return target->GetExactDistSq(&homePos) < 30.0f * 30.0f;
         }
References Unit::GetDisplayId(), Position::GetExactDistSq(), Creature::GetHomePosition(), Object::HasFlag(), Unit::HasUnitState(), ScriptedAI::me, UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE, and UNIT_STATE_STUNNED.
Deactivate()
void npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::Deactivate () inline
Definition at line 1162 of file zone_dragonblight.cpp.
         {
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
             me->SetReactState(REACT_PASSIVE);
             me->SetDisplayId(11686);
         }
References ScriptedAI::me, REACT_PASSIVE, Creature::SetDisplayId(), Object::SetFlag(), Creature::SetReactState(), UNIT_FIELD_FLAGS, and UNIT_FLAG_NOT_SELECTABLE.
Referenced by DoAction(), JustRespawned(), and npc_q24545_wretched_ghoulAI().
DoAction()
void npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::DoAction (int32 a) inline override virtual
Reimplemented from UnitAI.
Definition at line 1127 of file zone_dragonblight.cpp.
         {
             if (a == -1)
                 Activate();
             else if (a == -2)
             {
                 me->CastSpell(me, SPELL_SAC_GHOUL_EXPLODE, true);
                 Unit::Kill(me, me);
                 me->m_Events.KillAllEvents(true);
                 Deactivate();
             }
         }
References mpq::a, Activate(), Unit::CastSpell(), Deactivate(), Unit::Kill(), EventProcessor::KillAllEvents(), Unit::m_Events, ScriptedAI::me, and SPELL_SAC_GHOUL_EXPLODE.
JustDied()
void npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1169 of file zone_dragonblight.cpp.
         {
             me->RemoveAurasDueToSpell(SPELL_SAC_GHOUL_AREA_AURA);
             me->m_Events.AddEvent(new SACDeactivateEvent(me), me->m_Events.CalculateTime(4000));
         }
References EventProcessor::AddEvent(), EventProcessor::CalculateTime(), Unit::m_Events, ScriptedAI::me, Unit::RemoveAurasDueToSpell(), and SPELL_SAC_GHOUL_AREA_AURA.
JustRespawned()
void npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::JustRespawned () inline override virtual
Reimplemented from CreatureAI.
Definition at line 1175 of file zone_dragonblight.cpp.
         {
             Deactivate();
         }
References Deactivate().
Reset()
void npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1122 of file zone_dragonblight.cpp.
         {
             me->SetCorpseDelay(3);
         }
References ScriptedAI::me, and Creature::SetCorpseDelay().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/zone_dragonblight.cpp