Azerotcore-wotlk: DBCFile Class Reference
DBCFile Class Reference
#include <dbcfile.h>
Classes
class Exception
class Iterator
class NotFound
class Record
Public Member Functions
DBCFile (std::string filename)
~DBCFile ()
bool open ()
Record getRecord (size_t id)
Iterator begin ()
Get begin iterator over records.
Iterator end ()
Get begin iterator over records.
size_t getRecordCount () const
Trivial.
size_t getFieldCount () const
size_t getMaxId ()
DBCFile (std::string filename)
~DBCFile ()
bool open ()
Record getRecord (size_t id)
Iterator begin ()
Get begin iterator over records.
Iterator end ()
Get begin iterator over records.
size_t getRecordCount () const
Trivial.
size_t getFieldCount () const
Private Attributes
std::string filename
size_t recordSize
size_t recordCount
size_t fieldCount
size_t stringSize
unsigned char * data
unsigned char * stringTable
Detailed Description
Definition at line 24 of file dbcfile.h.
Constructor & Destructor Documentation
DBCFile() [1/2]
DBCFile::DBCFile (std::string filename)
Definition at line 25 of file dbcfile.cpp.
                                    :
     filename(std::move(filename)), recordSize(0), recordCount(0), fieldCount(0), stringSize(0), data(nullptr), stringTable(nullptr)
 {
 }
~DBCFile() [1/2]
DBCFile::~DBCFile ()
Definition at line 67 of file dbcfile.cpp.
 {
     delete [] data;
 }
References data.
DBCFile() [2/2]
DBCFile::DBCFile (std::string filename)
~DBCFile() [2/2]
DBCFile::~DBCFile ()
Member Function Documentation
begin() [1/2]
DBCFile::Iterator DBCFile::begin ()
Get begin iterator over records.
Definition at line 91 of file dbcfile.cpp.
 {
     assert(data);
     return Iterator(*this, data);
 }
References assert().
begin() [2/2]
Iterator DBCFile::begin ()
Get begin iterator over records.
end() [1/2]
DBCFile::Iterator DBCFile::end ()
Get begin iterator over records.
Definition at line 96 of file dbcfile.cpp.
 {
     assert(data);
     return Iterator(*this, stringTable);
 }
References assert(), and stringTable.
end() [2/2]
Iterator DBCFile::end ()
Get begin iterator over records.
getFieldCount() [1/2]
size_t DBCFile::getFieldCount () const inline
Definition at line 125 of file dbcfile.h.
 { return fieldCount; }
References fieldCount.
getFieldCount() [2/2]
size_t DBCFile::getFieldCount () const inline
Definition at line 144 of file dbcfile.h.
 { return fieldCount; }
References fieldCount.
getMaxId()
size_t DBCFile::getMaxId ()
Definition at line 78 of file dbcfile.cpp.
 {
     assert(data);
     size_t maxId = 0;
     for (size_t i = 0; i < getRecordCount(); ++i)
     {
         if (maxId < getRecord(i).getUInt(0))
             maxId = getRecord(i).getUInt(0);
     }
     return maxId;
 }
References assert(), getRecord(), getRecordCount(), and DBCFile::Record::getUInt().
Referenced by ReadLiquidTypeTableDBC().
getRecord() [1/2]
DBCFile::Record DBCFile::getRecord (size_t id)
Definition at line 72 of file dbcfile.cpp.
 {
     assert(data);
     return Record(*this, data + id * recordSize);
 }
References assert(), and recordSize.
Referenced by ExtractCameraFiles(), getMaxId(), main(), ReadLiquidTypeTableDBC(), and ReadMapDBC().
getRecord() [2/2]
Record DBCFile::getRecord (size_t id)
getRecordCount() [1/2]
size_t DBCFile::getRecordCount () const inline
Trivial.
Definition at line 124 of file dbcfile.h.
 { return recordCount;}
References recordCount.
Referenced by ExtractCameraFiles(), getMaxId(), main(), ReadLiquidTypeTableDBC(), and ReadMapDBC().
getRecordCount() [2/2]
size_t DBCFile::getRecordCount () const inline
Trivial.
Definition at line 143 of file dbcfile.h.
 { return recordCount;}
References recordCount.
open() [1/2]
bool DBCFile::open ()
Definition at line 30 of file dbcfile.cpp.
 {
     MPQFile f(filename.c_str());
     char header[4];
     unsigned int na, nb, es, ss;
     if (f.read(header, 4) != 4)                             // Number of records
         return false;
     if (header[0] != 'W' || header[1] != 'D' || header[2] != 'B' || header[3] != 'C')
         return false;
     if (f.read(&na, 4) != 4)                                // Number of records
         return false;
     if (f.read(&nb, 4) != 4)                                // Number of fields
         return false;
     if (f.read(&es, 4) != 4)                                // Size of a record
         return false;
     if (f.read(&ss, 4) != 4)                                // String size
         return false;
     recordSize = es;
     recordCount = na;
     fieldCount = nb;
     stringSize = ss;
     if (fieldCount * 4 != recordSize)
         return false;
     data = new unsigned char[recordSize * recordCount + stringSize];
     stringTable = data + recordSize * recordCount;
     size_t data_size = recordSize * recordCount + stringSize;
     if (f.read(data, data_size) != data_size)
         return false;
     f.close();
     return true;
 }
References f(), fieldCount, filename, recordCount, recordSize, stringSize, and stringTable.
Referenced by ExtractCameraFiles(), ExtractGameobjectModels(), main(), ReadLiquidTypeTableDBC(), and ReadMapDBC().
open() [2/2]
bool DBCFile::open ()
Member Data Documentation
data
unsigned char * DBCFile::data private
Definition at line 133 of file dbcfile.h.
Referenced by ~DBCFile().
fieldCount
size_t DBCFile::fieldCount private
Definition at line 131 of file dbcfile.h.
Referenced by getFieldCount(), DBCFile::Record::getFloat(), DBCFile::Record::getInt(), DBCFile::Record::getString(), DBCFile::Record::getUInt(), and open().
filename
std::string DBCFile::filename private
Definition at line 128 of file dbcfile.h.
Referenced by open().
recordCount
size_t DBCFile::recordCount private
Definition at line 130 of file dbcfile.h.
Referenced by getRecordCount(), and open().
recordSize
size_t DBCFile::recordSize private
Definition at line 129 of file dbcfile.h.
Referenced by DBCFile::Record::getByte(), getRecord(), open(), and DBCFile::Iterator::operator++().
stringSize
size_t DBCFile::stringSize private
Definition at line 132 of file dbcfile.h.
Referenced by DBCFile::Record::getString(), and open().
stringTable
unsigned char * DBCFile::stringTable private
Definition at line 134 of file dbcfile.h.
Referenced by end(), DBCFile::Record::getString(), and open().
The documentation for this class was generated from the following files:
src/tools/map_extractor/dbcfile.h
src/tools/map_extractor/dbcfile.cpp