Azerotcore-wotlk: AddonMgr Namespace Reference
AddonMgr Namespace Reference
Namespaces
anonymous_namespace{AddonMgr.cpp}
Typedefs
typedef std::list< BannedAddon > BannedAddonList
Functions
void LoadFromDB ()
void SaveAddon (AddonInfo const &addon)
SavedAddon const * GetAddonInfo (const std::string &name)
BannedAddonList const * GetBannedAddons ()
Typedef Documentation
BannedAddonList
typedef std::list<BannedAddon> AddonMgr::BannedAddonList
Definition at line 65 of file AddonMgr.h.
Function Documentation
GetAddonInfo()
SavedAddon const * AddonMgr::GetAddonInfo (const std::string & name)
Definition at line 114 of file AddonMgr.cpp.
     {
         for (SavedAddonsList::const_iterator it = m_knownAddons.begin(); it != m_knownAddons.end(); ++it)
         {
             SavedAddon const& addon = (*it);
             if (addon.Name == name)
                 return &addon;
         }
         return nullptr;
     }
References AddonMgr::anonymous_namespace{AddonMgr.cpp}::m_knownAddons, and SavedAddon::Name.
Referenced by WorldSession::ReadAddonsInfo().
GetBannedAddons()
BannedAddonList const * AddonMgr::GetBannedAddons ()
Definition at line 126 of file AddonMgr.cpp.
     {
         return &m_bannedAddons;
     }
References AddonMgr::anonymous_namespace{AddonMgr.cpp}::m_bannedAddons.
Referenced by WorldSession::SendAddonsInfo().
LoadFromDB()
void AddonMgr::LoadFromDB ()
Definition at line 40 of file AddonMgr.cpp.
     {
         uint32 oldMSTime = getMSTime();
         QueryResult result = CharacterDatabase.Query("SELECT name, crc FROM addons");
         if (!result)
         {
             LOG_INFO("server.loading", ">> Loaded 0 known addons. DB table `addons` is empty!");
             LOG_INFO("server.loading", " ");
             return;
         }
         uint32 count = 0;
         do
         {
             Field* fields = result->Fetch();
             std::string name = fields[0].GetString();
             uint32 crc = fields[1].GetUInt32();
             m_knownAddons.push_back(SavedAddon(name, crc));
             ++count;
         } while (result->NextRow());
         LOG_INFO("server.loading", ">> Loaded %u known addons in %u ms", count, GetMSTimeDiffToNow(oldMSTime));
         LOG_INFO("server.loading", " ");
         oldMSTime = getMSTime();
         result = CharacterDatabase.Query("SELECT id, name, version, UNIX_TIMESTAMP(timestamp) FROM banned_addons");
         if (result)
         {
             uint32 count2 = 0;
             uint32 offset = 102;
             do
             {
                 Field* fields = result->Fetch();
                 BannedAddon addon;
                 addon.Id = fields[0].GetUInt32() + offset;
                 addon.Timestamp = uint32(fields[3].GetUInt64());
                 std::string name = fields[1].GetString();
                 std::string version = fields[2].GetString();
                 MD5(reinterpret_cast<uint8 const*>(name.c_str()), name.length(), addon.NameMD5);
                 MD5(reinterpret_cast<uint8 const*>(version.c_str()), version.length(), addon.VersionMD5);
                 m_bannedAddons.push_back(addon);
                 ++count2;
             } while (result->NextRow());
             LOG_INFO("server.loading", ">> Loaded %u banned addons in %u ms", count2, GetMSTimeDiffToNow(oldMSTime));
             LOG_INFO("server.loading", " ");
         }
     }
References CharacterDatabase, getMSTime(), GetMSTimeDiffToNow(), Field::GetString(), Field::GetUInt32(), BannedAddon::Id, LOG_INFO, AddonMgr::anonymous_namespace{AddonMgr.cpp}::m_bannedAddons, AddonMgr::anonymous_namespace{AddonMgr.cpp}::m_knownAddons, BannedAddon::NameMD5, BannedAddon::Timestamp, and BannedAddon::VersionMD5.
Referenced by World::SetInitialWorldSettings().
SaveAddon()
void AddonMgr::SaveAddon (AddonInfo const & addon)
Definition at line 100 of file AddonMgr.cpp.
     {
         std::string name = addon.Name;
         CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_ADDON);
         stmt->setString(0, name);
         stmt->setUInt32(1, addon.CRC);
         CharacterDatabase.Execute(stmt);
         m_knownAddons.push_back(SavedAddon(addon.Name, addon.CRC));
     }
References CHAR_INS_ADDON, CharacterDatabase, AddonInfo::CRC, AddonMgr::anonymous_namespace{AddonMgr.cpp}::m_knownAddons, AddonInfo::Name, PreparedStatementBase::setString(), and PreparedStatementBase::setUInt32().
Referenced by WorldSession::ReadAddonsInfo().