Azerotcore-wotlk: format_string_checker< Char, ErrorHandler, Args > Class Template Reference
format_string_checker< Char, ErrorHandler, Args > Class Template Reference
#include <core.h>
Public Member Functions
FMT_CONSTEXPR format_string_checker (basic_string_view< Char > format_str, ErrorHandler eh)
FMT_CONSTEXPR void on_text (const Char *, const Char *)
FMT_CONSTEXPR auto on_arg_id () -> int
FMT_CONSTEXPR auto on_arg_id (int id) -> int
FMT_CONSTEXPR auto on_arg_id (basic_string_view< Char > id) -> int
FMT_CONSTEXPR void on_replacement_field (int, const Char *)
FMT_CONSTEXPR auto on_format_specs (int id, const Char *begin, const Char *) -> const Char *
FMT_CONSTEXPR void on_error (const char *message)
Private Types
enum { num_args = sizeof...(Args) }
using parse_context_type = compile_parse_context< Char, ErrorHandler >
using parse_func = const Char *(*)(parse_context_type &)
Private Attributes
parse_context_type context_
parse_func parse_funcs_ [num_args > 0 ? num_args :1]
Detailed Description
template<typename Char, typename ErrorHandler, typename... Args>
class format_string_checker< Char, ErrorHandler, Args >
Definition at line 2673 of file core.h.
Member Typedef Documentation
parse_context_type
template<typename Char , typename ErrorHandler , typename... Args> using format_string_checker< Char, ErrorHandler, Args >::parse_context_type = compile_parse_context<Char, ErrorHandler> private
Definition at line 2675 of file core.h.
parse_func
template<typename Char , typename ErrorHandler , typename... Args> using format_string_checker< Char, ErrorHandler, Args >::parse_func = const Char* (*)(parse_context_type&) private
Definition at line 2679 of file core.h.
Member Enumeration Documentation
anonymous enum
template<typename Char , typename ErrorHandler , typename... Args> anonymous enum private
Enumerator
num_args
Definition at line 2676 of file core.h.
 { num_args = sizeof...(Args) };
Constructor & Destructor Documentation
format_string_checker()
template<typename Char , typename ErrorHandler , typename... Args> FMT_CONSTEXPR format_string_checker< Char, ErrorHandler, Args >::format_string_checker (basic_string_view< Char > format_str, ErrorHandler eh) inline explicit
Definition at line 2685 of file core.h.
       : context_(format_str, num_args, eh),
         parse_funcs_{&parse_format_specs<Args, parse_context_type>...} {}
Member Function Documentation
on_arg_id() [1/3]
template<typename Char , typename ErrorHandler , typename... Args> FMT_CONSTEXPR auto format_string_checker< Char, ErrorHandler, Args >::on_arg_id () -> int inline
Definition at line 2692 of file core.h.
 { return context_.next_arg_id(); }
References compile_parse_context< Char, ErrorHandler >::next_arg_id().
on_arg_id() [2/3]
template<typename Char , typename ErrorHandler , typename... Args> FMT_CONSTEXPR auto format_string_checker< Char, ErrorHandler, Args >::on_arg_id (basic_string_view< Char > id) -> int inline
Definition at line 2696 of file core.h.
{
 #if FMT_USE_NONTYPE_TEMPLATE_PARAMETERS
     auto index = get_arg_index_by_name<Args...>(id);
     if (index == invalid_arg_index) on_error("named argument is not found");
     return context_.check_arg_id(index), index;
 #else
     (void)id;
     on_error("compile-time checks for named arguments require C++20 support");
     return 0;
 #endif
   }
References compile_parse_context< Char, ErrorHandler >::check_arg_id(), get_arg_index_by_name(), index, and invalid_arg_index.
on_arg_id() [3/3]
template<typename Char , typename ErrorHandler , typename... Args> FMT_CONSTEXPR auto format_string_checker< Char, ErrorHandler, Args >::on_arg_id (int id) -> int inline
Definition at line 2693 of file core.h.
{
     return context_.check_arg_id(id), id;
   }
References compile_parse_context< Char, ErrorHandler >::check_arg_id().
on_error()
template<typename Char , typename ErrorHandler , typename... Args> FMT_CONSTEXPR void format_string_checker< Char, ErrorHandler, Args >::on_error (const char * message) inline
Definition at line 2717 of file core.h.
{
     context_.on_error(message);
   }
References message(), and basic_format_parse_context< Char, ErrorHandler >::on_error().
on_format_specs()
template<typename Char , typename ErrorHandler , typename... Args> FMT_CONSTEXPR auto format_string_checker< Char, ErrorHandler, Args >::on_format_specs (int id, const Char * begin, const Char *) -> const Char* inline
Definition at line 2710 of file core.h.
                      {
     context_.advance_to(context_.begin() + (begin - &*context_.begin()));
     // id >= 0 check is a workaround for gcc 10 bug (#2065).
     return id >= 0 && id < num_args ? parse_funcs_[id](context_) : begin;
   }
References basic_format_parse_context< Char, ErrorHandler >::advance_to(), and basic_format_parse_context< Char, ErrorHandler >::begin().
on_replacement_field()
template<typename Char , typename ErrorHandler , typename... Args> FMT_CONSTEXPR void format_string_checker< Char, ErrorHandler, Args >::on_replacement_field (int , const Char *) inline
Definition at line 2708 of file core.h.
 {}
on_text()
template<typename Char , typename ErrorHandler , typename... Args> FMT_CONSTEXPR void format_string_checker< Char, ErrorHandler, Args >::on_text (const Char * , const Char *) inline
Definition at line 2690 of file core.h.
 {}
Member Data Documentation
context_
template<typename Char , typename ErrorHandler , typename... Args> parse_context_type format_string_checker< Char, ErrorHandler, Args >::context_ private
Definition at line 2681 of file core.h.
parse_funcs_
template<typename Char , typename ErrorHandler , typename... Args> parse_func format_string_checker< Char, ErrorHandler, Args >::parse_funcs_[num_args > 0 ? num_args :1] private
Definition at line 2682 of file core.h.
The documentation for this class was generated from the following file:
deps/fmt/include/fmt/core.h