Azerotcore-wotlk: deps/bzip2/bzlib.c File Reference
bzlib.c File Reference
#include "bzlib_private.h"
Classes
struct bzFile
Macros
#define ADD_CHAR_TO_BLOCK(zs, zchh0)
#define BZ_SETERR(eee)
#define SET_BINARY_MODE(file)
Functions
void BZ2_bz__AssertH__fail (int errcode)
static int bz_config_ok (void)
static void * default_bzalloc (void *opaque, Int32 items, Int32 size)
static void default_bzfree (void *opaque, void *addr)
static void prepare_new_block (EState *s)
static void init_RL (EState *s)
static Bool isempty_RL (EState *s)
int BZ_API() BZ2_bzCompressInit (bz_stream *strm, int blockSize100k, int verbosity, int workFactor)
static void add_pair_to_block (EState *s)
static void flush_RL (EState *s)
static Bool copy_input_until_stop (EState *s)
static Bool copy_output_until_stop (EState *s)
static Bool handle_compress (bz_stream *strm)
int BZ_API() BZ2_bzCompress (bz_stream *strm, int action)
int BZ_API() BZ2_bzCompressEnd (bz_stream *strm)
int BZ_API() BZ2_bzDecompressInit (bz_stream *strm, int verbosity, int small)
static Bool unRLE_obuf_to_output_FAST (DState *s)
__inline__ Int32 BZ2_indexIntoF (Int32 indx, Int32 *cftab)
static Bool unRLE_obuf_to_output_SMALL (DState *s)
int BZ_API() BZ2_bzDecompress (bz_stream *strm)
int BZ_API() BZ2_bzDecompressEnd (bz_stream *strm)
static Bool myfeof (FILE *f)
BZFILE *BZ_API() BZ2_bzWriteOpen (int *bzerror, FILE *f, int blockSize100k, int verbosity, int workFactor)
void BZ_API() BZ2_bzWrite (int *bzerror, BZFILE *b, void *buf, int len)
void BZ_API() BZ2_bzWriteClose (int *bzerror, BZFILE *b, int abandon, unsigned int *nbytes_in, unsigned int *nbytes_out)
void BZ_API() BZ2_bzWriteClose64 (int *bzerror, BZFILE *b, int abandon, unsigned int *nbytes_in_lo32, unsigned int *nbytes_in_hi32, unsigned int *nbytes_out_lo32, unsigned int *nbytes_out_hi32)
BZFILE *BZ_API() BZ2_bzReadOpen (int *bzerror, FILE *f, int verbosity, int small, void *unused, int nUnused)
void BZ_API() BZ2_bzReadClose (int *bzerror, BZFILE *b)
int BZ_API() BZ2_bzRead (int *bzerror, BZFILE *b, void *buf, int len)
void BZ_API() BZ2_bzReadGetUnused (int *bzerror, BZFILE *b, void **unused, int *nUnused)
int BZ_API() BZ2_bzBuffToBuffCompress (char *dest, unsigned int *destLen, char *source, unsigned int sourceLen, int blockSize100k, int verbosity, int workFactor)
int BZ_API() BZ2_bzBuffToBuffDecompress (char *dest, unsigned int *destLen, char *source, unsigned int sourceLen, int small, int verbosity)
const char *BZ_API() BZ2_bzlibVersion (void)
static BZFILE * bzopen_or_bzdopen (const char *path, int fd, const char *mode, int open_mode)
BZFILE *BZ_API() BZ2_bzopen (const char *path, const char *mode)
BZFILE *BZ_API() BZ2_bzdopen (int fd, const char *mode)
int BZ_API() BZ2_bzread (BZFILE *b, void *buf, int len)
int BZ_API() BZ2_bzwrite (BZFILE *b, void *buf, int len)
int BZ_API() BZ2_bzflush (BZFILE *b)
void BZ_API() BZ2_bzclose (BZFILE *b)
const char *BZ_API() BZ2_bzerror (BZFILE *b, int *errnum)
Variables
static const char * bzerrorstrings []
Macro Definition Documentation
ADD_CHAR_TO_BLOCK
#define ADD_CHAR_TO_BLOCK (zs, zchh0)
Value:
{                                                 \
   UInt32 zchh = (UInt32)(zchh0);                 \
   /*-- fast track the common case --*/           \
   if (zchh != zs->state_in_ch &&                 \
       zs->state_in_len == 1) {                   \
      UChar ch = (UChar)(zs->state_in_ch);        \
      BZ_UPDATE_CRC( zs->blockCRC, ch );          \
      zs->inUse[zs->state_in_ch] = True;          \
      zs->block[zs->nblock] = (UChar)ch;          \
      zs->nblock++;                               \
      zs->state_in_ch = zchh;                     \
   }                                              \
   else                                           \
   /*-- general, uncommon cases --*/              \
   if (zchh != zs->state_in_ch ||                 \
      zs->state_in_len == 255) {                  \
      if (zs->state_in_ch < 256)                  \
         add_pair_to_block ( zs );                \
      zs->state_in_ch = zchh;                     \
      zs->state_in_len = 1;                       \
   } else {                                       \
      zs->state_in_len++;                         \
   }                                              \
}
Definition at line 260 of file bzlib.c.
BZ_SETERR
#define BZ_SETERR (eee)
Value:
{                                         \
   if (bzerror != NULL) *bzerror = eee;   \
   if (bzf != NULL) bzf->lastErr = eee;   \
}
Definition at line 886 of file bzlib.c.
SET_BINARY_MODE
#define SET_BINARY_MODE (file)
Definition at line 1380 of file bzlib.c.
Function Documentation
add_pair_to_block()
static void add_pair_to_block (EState * s) static
Definition at line 216 of file bzlib.c.
 {
    Int32 i;
    UChar ch = (UChar)(s->state_in_ch);
    for (i = 0; i < s->state_in_len; i++) {
       BZ_UPDATE_CRC( s->blockCRC, ch );
    }
    s->inUse[s->state_in_ch] = True;
    switch (s->state_in_len) {
       case 1:
          s->block[s->nblock] = (UChar)ch; s->nblock++;
          break;
       case 2:
          s->block[s->nblock] = (UChar)ch; s->nblock++;
          s->block[s->nblock] = (UChar)ch; s->nblock++;
          break;
       case 3:
          s->block[s->nblock] = (UChar)ch; s->nblock++;
          s->block[s->nblock] = (UChar)ch; s->nblock++;
          s->block[s->nblock] = (UChar)ch; s->nblock++;
          break;
       default:
          s->inUse[s->state_in_len-4] = True;
          s->block[s->nblock] = (UChar)ch; s->nblock++;
          s->block[s->nblock] = (UChar)ch; s->nblock++;
          s->block[s->nblock] = (UChar)ch; s->nblock++;
          s->block[s->nblock] = (UChar)ch; s->nblock++;
          s->block[s->nblock] = ((UChar)(s->state_in_len-4));
          s->nblock++;
          break;
    }
 }
References EState::block, EState::blockCRC, BZ_UPDATE_CRC, EState::inUse, EState::nblock, EState::state_in_ch, EState::state_in_len, and True.
Referenced by flush_RL().
BZ2_bz__AssertH__fail()
void BZ2_bz__AssertH__fail (int errcode)
Definition at line 41 of file bzlib.c.
 {
    fprintf(stderr,
       "\n\nbzip2/libbzip2: internal error number %d.\n"
       "This is a bug in bzip2/libbzip2, %s.\n"
       "Please report it to me at: jseward@bzip.org.  If this happened\n"
       "when you were using some program which uses libbzip2 as a\n"
       "component, you should also report this bug to the author(s)\n"
       "of that program.  Please make an effort to report this bug;\n"
       "timely and accurate bug reports eventually lead to higher\n"
       "quality software.  Thanks.  Julian Seward, 10 December 2007.\n\n",
       errcode,
       BZ2_bzlibVersion()
    );
    if (errcode == 1007) {
    fprintf(stderr,
       "\n*** A special note about internal error number 1007 ***\n"
       "\n"
       "Experience suggests that a common cause of i.e. 1007\n"
       "is unreliable memory or other hardware.  The 1007 assertion\n"
       "just happens to cross-check the results of huge numbers of\n"
       "memory reads/writes, and so acts (unintendedly) as a stress\n"
       "test of your memory system.\n"
       "\n"
       "I suggest the following: try compressing the file again,\n"
       "possibly monitoring progress in detail with the -vv flag.\n"
       "\n"
       "* If the error cannot be reproduced, and/or happens at different\n"
       "  points in compression, you may have a flaky memory system.\n"
       "  Try a memory-test program.  I have used Memtest86\n"
       "  (www.memtest86.com).  At the time of writing it is free (GPLd).\n"
       "  Memtest86 tests memory much more thorougly than your BIOSs\n"
       "  power-on test, and may find failures that the BIOS doesn't.\n"
       "\n"
       "* If the error can be repeatably reproduced, this is a bug in\n"
       "  bzip2, and I would very much like to hear about it.  Please\n"
       "  let me know, and, ideally, save a copy of the file causing the\n"
       "  problem -- without which I will be unable to investigate it.\n"
       "\n"
    );
    }
    exit(3);
 }
References BZ2_bzlibVersion(), and fprintf().
BZ2_bzBuffToBuffCompress()
int BZ_API() BZ2_bzBuffToBuffCompress (char * dest, unsigned int * destLen, char * source, unsigned int sourceLen, int blockSize100k, int verbosity, int workFactor)
Definition at line 1247 of file bzlib.c.
 {
    bz_stream strm;
    int ret;
    if (dest == NULL || destLen == NULL ||
        source == NULL ||
        blockSize100k < 1 || blockSize100k > 9 ||
        verbosity < 0 || verbosity > 4 ||
        workFactor < 0 || workFactor > 250)
       return BZ_PARAM_ERROR;
    if (workFactor == 0) workFactor = 30;
    strm.bzalloc = NULL;
    strm.bzfree = NULL;
    strm.opaque = NULL;
    ret = BZ2_bzCompressInit ( &strm, blockSize100k,
                               verbosity, workFactor );
    if (ret != BZ_OK) return ret;
    strm.next_in = source;
    strm.next_out = dest;
    strm.avail_in = sourceLen;
    strm.avail_out = *destLen;
    ret = BZ2_bzCompress ( &strm, BZ_FINISH );
    if (ret == BZ_FINISH_OK) goto output_overflow;
    if (ret != BZ_STREAM_END) goto errhandler;
    /* normal termination */
    *destLen -= strm.avail_out;
    BZ2_bzCompressEnd ( &strm );
    return BZ_OK;
    output_overflow:
    BZ2_bzCompressEnd ( &strm );
    return BZ_OUTBUFF_FULL;
    errhandler:
    BZ2_bzCompressEnd ( &strm );
    return ret;
 }
References bz_stream::avail_in, bz_stream::avail_out, BZ2_bzCompress(), BZ2_bzCompressEnd(), BZ2_bzCompressInit(), BZ_FINISH, BZ_FINISH_OK, BZ_OK, BZ_OUTBUFF_FULL, BZ_PARAM_ERROR, BZ_STREAM_END, bz_stream::bzalloc, bz_stream::bzfree, bz_stream::next_in, bz_stream::next_out, NULL, bz_stream::opaque, and ret.
BZ2_bzBuffToBuffDecompress()
int BZ_API() BZ2_bzBuffToBuffDecompress (char * dest, unsigned int * destLen, char * source, unsigned int sourceLen, int small, int verbosity)
Definition at line 1299 of file bzlib.c.
 {
    bz_stream strm;
    int ret;
    if (dest == NULL || destLen == NULL ||
        source == NULL ||
        (small != 0 && small != 1) ||
        verbosity < 0 || verbosity > 4)
           return BZ_PARAM_ERROR;
    strm.bzalloc = NULL;
    strm.bzfree = NULL;
    strm.opaque = NULL;
    ret = BZ2_bzDecompressInit ( &strm, verbosity, small );
    if (ret != BZ_OK) return ret;
    strm.next_in = source;
    strm.next_out = dest;
    strm.avail_in = sourceLen;
    strm.avail_out = *destLen;
    ret = BZ2_bzDecompress ( &strm );
    if (ret == BZ_OK) goto output_overflow_or_eof;
    if (ret != BZ_STREAM_END) goto errhandler;
    /* normal termination */
    *destLen -= strm.avail_out;
    BZ2_bzDecompressEnd ( &strm );
    return BZ_OK;
    output_overflow_or_eof:
    if (strm.avail_out > 0) {
       BZ2_bzDecompressEnd ( &strm );
       return BZ_UNEXPECTED_EOF;
    } else {
       BZ2_bzDecompressEnd ( &strm );
       return BZ_OUTBUFF_FULL;
    };
    errhandler:
    BZ2_bzDecompressEnd ( &strm );
    return ret;
 }
References bz_stream::avail_in, bz_stream::avail_out, BZ2_bzDecompress(), BZ2_bzDecompressEnd(), BZ2_bzDecompressInit(), BZ_OK, BZ_OUTBUFF_FULL, BZ_PARAM_ERROR, BZ_STREAM_END, BZ_UNEXPECTED_EOF, bz_stream::bzalloc, bz_stream::bzfree, bz_stream::next_in, bz_stream::next_out, NULL, bz_stream::opaque, and ret.
BZ2_bzclose()
void BZ_API() BZ2_bzclose (BZFILE * b)
Definition at line 1514 of file bzlib.c.
 {
    int bzerr;
    FILE *fp;
    if (b==NULL) {return;}
    fp = ((bzFile *)b)->handle;
    if(((bzFile*)b)->writing){
       BZ2_bzWriteClose(&bzerr,b,0,NULL,NULL);
       if(bzerr != BZ_OK){
          BZ2_bzWriteClose(NULL,b,1,NULL,NULL);
       }
    }else{
       BZ2_bzReadClose(&bzerr,b);
    }
    if(fp!=stdin && fp!=stdout){
       fclose(fp);
    }
 }
References b, BZ2_bzReadClose(), BZ2_bzWriteClose(), BZ_OK, and NULL.
BZ2_bzCompress()
int BZ_API() BZ2_bzCompress (bz_stream * strm, int action)
Definition at line 407 of file bzlib.c.
 {
    Bool progress;
    EState* s;
    if (strm == NULL) return BZ_PARAM_ERROR;
    s = strm->state;
    if (s == NULL) return BZ_PARAM_ERROR;
    if (s->strm != strm) return BZ_PARAM_ERROR;
    preswitch:
    switch (s->mode) {
       case BZ_M_IDLE:
          return BZ_SEQUENCE_ERROR;
       case BZ_M_RUNNING:
          if (action == BZ_RUN) {
             progress = handle_compress ( strm );
             return progress ? BZ_RUN_OK : BZ_PARAM_ERROR;
          }
          else
      if (action == BZ_FLUSH) {
             s->avail_in_expect = strm->avail_in;
             s->mode = BZ_M_FLUSHING;
             goto preswitch;
          }
          else
          if (action == BZ_FINISH) {
             s->avail_in_expect = strm->avail_in;
             s->mode = BZ_M_FINISHING;
             goto preswitch;
          }
          else
             return BZ_PARAM_ERROR;
       case BZ_M_FLUSHING:
          if (action != BZ_FLUSH) return BZ_SEQUENCE_ERROR;
          if (s->avail_in_expect != s->strm->avail_in)
             return BZ_SEQUENCE_ERROR;
          progress = handle_compress ( strm );
          if (s->avail_in_expect > 0 || !isempty_RL(s) ||
              s->state_out_pos < s->numZ) return BZ_FLUSH_OK;
          s->mode = BZ_M_RUNNING;
          return BZ_RUN_OK;
       case BZ_M_FINISHING:
          if (action != BZ_FINISH) return BZ_SEQUENCE_ERROR;
          if (s->avail_in_expect != s->strm->avail_in)
             return BZ_SEQUENCE_ERROR;
          progress = handle_compress ( strm );
          if (!progress) return BZ_SEQUENCE_ERROR;
          if (s->avail_in_expect > 0 || !isempty_RL(s) ||
              s->state_out_pos < s->numZ) return BZ_FINISH_OK;
          s->mode = BZ_M_IDLE;
          return BZ_STREAM_END;
    }
    return BZ_OK; /*--not reached--*/
 }
References bz_stream::avail_in, EState::avail_in_expect, BZ_FINISH, BZ_FINISH_OK, BZ_FLUSH, BZ_FLUSH_OK, BZ_M_FINISHING, BZ_M_FLUSHING, BZ_M_IDLE, BZ_M_RUNNING, BZ_OK, BZ_PARAM_ERROR, BZ_RUN, BZ_RUN_OK, BZ_SEQUENCE_ERROR, BZ_STREAM_END, handle_compress(), isempty_RL(), EState::mode, NULL, EState::numZ, EState::state, EState::state_out_pos, and EState::strm.
Referenced by BZ2_bzBuffToBuffCompress(), BZ2_bzWrite(), and BZ2_bzWriteClose64().
BZ2_bzCompressEnd()
int BZ_API() BZ2_bzCompressEnd (bz_stream * strm)
Definition at line 468 of file bzlib.c.
 {
    EState* s;
    if (strm == NULL) return BZ_PARAM_ERROR;
    s = strm->state;
    if (s == NULL) return BZ_PARAM_ERROR;
    if (s->strm != strm) return BZ_PARAM_ERROR;
    if (s->arr1 != NULL) BZFREE(s->arr1);
    if (s->arr2 != NULL) BZFREE(s->arr2);
    if (s->ftab != NULL) BZFREE(s->ftab);
    BZFREE(strm->state);
    strm->state = NULL;
    return BZ_OK;
 }
References EState::arr1, EState::arr2, BZ_OK, BZ_PARAM_ERROR, BZFREE, EState::ftab, NULL, EState::state, and EState::strm.
Referenced by BZ2_bzBuffToBuffCompress(), and BZ2_bzWriteClose64().
BZ2_bzCompressInit()
int BZ_API() BZ2_bzCompressInit (bz_stream * strm, int blockSize100k, int verbosity, int workFactor)
Definition at line 148 of file bzlib.c.
 {
    Int32   n;
    EState* s;
    if (!bz_config_ok()) return BZ_CONFIG_ERROR;
    if (strm == NULL ||
        blockSize100k < 1 || blockSize100k > 9 ||
        workFactor < 0 || workFactor > 250)
      return BZ_PARAM_ERROR;
    if (workFactor == 0) workFactor = 30;
    if (strm->bzalloc == NULL) strm->bzalloc = default_bzalloc;
    if (strm->bzfree == NULL) strm->bzfree = default_bzfree;
    s = BZALLOC( sizeof(EState) );
    if (s == NULL) return BZ_MEM_ERROR;
    s->strm = strm;
    s->arr1 = NULL;
    s->arr2 = NULL;
    s->ftab = NULL;
    n       = 100000 * blockSize100k;
    s->arr1 = BZALLOC( n                  * sizeof(UInt32) );
    s->arr2 = BZALLOC( (n+BZ_N_OVERSHOOT) * sizeof(UInt32) );
    s->ftab = BZALLOC( 65537              * sizeof(UInt32) );
    if (s->arr1 == NULL || s->arr2 == NULL || s->ftab == NULL) {
       if (s->arr1 != NULL) BZFREE(s->arr1);
       if (s->arr2 != NULL) BZFREE(s->arr2);
       if (s->ftab != NULL) BZFREE(s->ftab);
       if (s       != NULL) BZFREE(s);
       return BZ_MEM_ERROR;
    }
    s->blockNo           = 0;
    s->state             = BZ_S_INPUT;
    s->mode              = BZ_M_RUNNING;
    s->combinedCRC       = 0;
    s->blockSize100k     = blockSize100k;
    s->nblockMAX         = 100000 * blockSize100k - 19;
    s->verbosity         = verbosity;
    s->workFactor        = workFactor;
    s->block             = (UChar*)s->arr2;
    s->mtfv              = (UInt16*)s->arr1;
    s->zbits             = NULL;
    s->ptr               = (UInt32*)s->arr1;
    strm->state          = s;
    strm->total_in_lo32  = 0;
    strm->total_in_hi32  = 0;
    strm->total_out_lo32 = 0;
    strm->total_out_hi32 = 0;
    init_RL ( s );
    prepare_new_block ( s );
    return BZ_OK;
 }
References EState::arr1, EState::arr2, EState::block, EState::blockNo, EState::blockSize100k, BZ_CONFIG_ERROR, bz_config_ok(), BZ_M_RUNNING, BZ_MEM_ERROR, BZ_N_OVERSHOOT, BZ_OK, BZ_PARAM_ERROR, BZ_S_INPUT, BZALLOC, BZFREE, EState::combinedCRC, default_bzalloc(), default_bzfree(), EState::ftab, init_RL(), EState::mode, EState::mtfv, EState::nblockMAX, NULL, prepare_new_block(), EState::ptr, EState::state, EState::strm, EState::verbosity, EState::workFactor, and EState::zbits.
Referenced by BZ2_bzBuffToBuffCompress(), and BZ2_bzWriteOpen().
BZ2_bzDecompress()
int BZ_API() BZ2_bzDecompress (bz_stream * strm)
Definition at line 808 of file bzlib.c.
 {
    Bool    corrupt;
    DState* s;
    if (strm == NULL) return BZ_PARAM_ERROR;
    s = strm->state;
    if (s == NULL) return BZ_PARAM_ERROR;
    if (s->strm != strm) return BZ_PARAM_ERROR;
    while (True) {
       if (s->state == BZ_X_IDLE) return BZ_SEQUENCE_ERROR;
       if (s->state == BZ_X_OUTPUT) {
          if (s->smallDecompress)
             corrupt = unRLE_obuf_to_output_SMALL ( s ); else
             corrupt = unRLE_obuf_to_output_FAST  ( s );
          if (corrupt) return BZ_DATA_ERROR;
          if (s->nblock_used == s->save_nblock+1 && s->state_out_len == 0) {
             BZ_FINALISE_CRC ( s->calculatedBlockCRC );
             if (s->verbosity >= 3)
                VPrintf2 ( " {0x%08x, 0x%08x}", s->storedBlockCRC,
                           s->calculatedBlockCRC );
             if (s->verbosity >= 2) VPrintf0 ( "]" );
             if (s->calculatedBlockCRC != s->storedBlockCRC)
                return BZ_DATA_ERROR;
             s->calculatedCombinedCRC
                = (s->calculatedCombinedCRC << 1) |
                     (s->calculatedCombinedCRC >> 31);
             s->calculatedCombinedCRC ^= s->calculatedBlockCRC;
             s->state = BZ_X_BLKHDR_1;
          } else {
             return BZ_OK;
          }
       }
       if (s->state >= BZ_X_MAGIC_1) {
          Int32 r = BZ2_decompress ( s );
          if (r == BZ_STREAM_END) {
             if (s->verbosity >= 3)
                VPrintf2 ( "\n    combined CRCs: stored = 0x%08x, computed = 0x%08x",
                           s->storedCombinedCRC, s->calculatedCombinedCRC );
             if (s->calculatedCombinedCRC != s->storedCombinedCRC)
                return BZ_DATA_ERROR;
             return r;
          }
          if (s->state != BZ_X_OUTPUT) return r;
       }
    }
    AssertH ( 0, 6001 );
    return 0;  /*NOTREACHED*/
 }
References AssertH, BZ2_decompress(), BZ_DATA_ERROR, BZ_FINALISE_CRC, BZ_OK, BZ_PARAM_ERROR, BZ_SEQUENCE_ERROR, BZ_STREAM_END, BZ_X_BLKHDR_1, BZ_X_IDLE, BZ_X_MAGIC_1, BZ_X_OUTPUT, DState::calculatedBlockCRC, DState::calculatedCombinedCRC, DState::nblock_used, NULL, DState::save_nblock, DState::smallDecompress, DState::state, DState::state_out_len, DState::storedBlockCRC, DState::storedCombinedCRC, DState::strm, True, unRLE_obuf_to_output_FAST(), unRLE_obuf_to_output_SMALL(), DState::verbosity, VPrintf0, and VPrintf2.
Referenced by BZ2_bzBuffToBuffDecompress(), BZ2_bzRead(), and libmpq__decompress_bzip2().
BZ2_bzDecompressEnd()
int BZ_API() BZ2_bzDecompressEnd (bz_stream * strm)
Definition at line 862 of file bzlib.c.
 {
    DState* s;
    if (strm == NULL) return BZ_PARAM_ERROR;
    s = strm->state;
    if (s == NULL) return BZ_PARAM_ERROR;
    if (s->strm != strm) return BZ_PARAM_ERROR;
    if (s->tt   != NULL) BZFREE(s->tt);
    if (s->ll16 != NULL) BZFREE(s->ll16);
    if (s->ll4  != NULL) BZFREE(s->ll4);
    BZFREE(strm->state);
    strm->state = NULL;
    return BZ_OK;
 }
References BZ_OK, BZ_PARAM_ERROR, BZFREE, DState::ll16, DState::ll4, NULL, DState::state, DState::strm, and DState::tt.
Referenced by BZ2_bzBuffToBuffDecompress(), BZ2_bzReadClose(), and libmpq__decompress_bzip2().
BZ2_bzDecompressInit()
int BZ_API() BZ2_bzDecompressInit (bz_stream * strm, int verbosity, int small)
Definition at line 492 of file bzlib.c.
 {
    DState* s;
    if (!bz_config_ok()) return BZ_CONFIG_ERROR;
    if (strm == NULL) return BZ_PARAM_ERROR;
    if (small != 0 && small != 1) return BZ_PARAM_ERROR;
    if (verbosity < 0 || verbosity > 4) return BZ_PARAM_ERROR;
    if (strm->bzalloc == NULL) strm->bzalloc = default_bzalloc;
    if (strm->bzfree == NULL) strm->bzfree = default_bzfree;
    s = BZALLOC( sizeof(DState) );
    if (s == NULL) return BZ_MEM_ERROR;
    s->strm                  = strm;
    strm->state              = s;
    s->state                 = BZ_X_MAGIC_1;
    s->bsLive                = 0;
    s->bsBuff                = 0;
    s->calculatedCombinedCRC = 0;
    strm->total_in_lo32      = 0;
    strm->total_in_hi32      = 0;
    strm->total_out_lo32     = 0;
    strm->total_out_hi32     = 0;
    s->smallDecompress       = (Bool)small;
    s->ll4                   = NULL;
    s->ll16                  = NULL;
    s->tt                    = NULL;
    s->currBlockNo           = 0;
    s->verbosity             = verbosity;
    return BZ_OK;
 }
References DState::bsBuff, DState::bsLive, BZ_CONFIG_ERROR, bz_config_ok(), BZ_MEM_ERROR, BZ_OK, BZ_PARAM_ERROR, BZ_X_MAGIC_1, BZALLOC, DState::calculatedCombinedCRC, DState::currBlockNo, default_bzalloc(), default_bzfree(), DState::ll16, DState::ll4, NULL, DState::smallDecompress, bz_stream::state, DState::state, DState::strm, DState::tt, and DState::verbosity.
Referenced by BZ2_bzBuffToBuffDecompress(), BZ2_bzReadOpen(), and libmpq__decompress_bzip2().
BZ2_bzdopen()
BZFILE* BZ_API() BZ2_bzdopen (int fd, const char * mode)
Definition at line 1469 of file bzlib.c.
 {
    return bzopen_or_bzdopen(NULL,fd,mode,/*bzdopen*/1);
 }
References bzopen_or_bzdopen(), and NULL.
BZ2_bzerror()
const char* BZ_API() BZ2_bzerror (BZFILE * b, int * errnum)
Definition at line 1559 of file bzlib.c.
 {
    int err = ((bzFile *)b)->lastErr;
    if(err>0) err = 0;
    *errnum = err;
    return bzerrorstrings[err*-1];
 }
References b, and bzerrorstrings.
BZ2_bzflush()
int BZ_API() BZ2_bzflush (BZFILE * b)
Definition at line 1506 of file bzlib.c.
 {
    /* do nothing now... */
    return 0;
 }
BZ2_bzlibVersion()
const char* BZ_API() BZ2_bzlibVersion (void)
Definition at line 1366 of file bzlib.c.
 {
    return BZ_VERSION;
 }
References BZ_VERSION.
Referenced by BZ2_bz__AssertH__fail().
BZ2_bzopen()
BZFILE* BZ_API() BZ2_bzopen (const char * path, const char * mode)
Definition at line 1460 of file bzlib.c.
 {
    return bzopen_or_bzdopen(path,-1,mode,/*bzopen*/0);
 }
References bzopen_or_bzdopen().
BZ2_bzread()
int BZ_API() BZ2_bzread (BZFILE * b, void * buf, int len)
Definition at line 1478 of file bzlib.c.
 {
    int bzerr, nread;
    if (((bzFile*)b)->lastErr == BZ_STREAM_END) return 0;
    nread = BZ2_bzRead(&bzerr,b,buf,len);
    if (bzerr == BZ_OK || bzerr == BZ_STREAM_END) {
       return nread;
    } else {
       return -1;
    }
 }
References b, BZ2_bzRead(), BZ_OK, and BZ_STREAM_END.
BZ2_bzRead()
int BZ_API() BZ2_bzRead (int * bzerror, BZFILE * b, void * buf, int len)
Definition at line 1161 of file bzlib.c.
 {
    Int32   n, ret;
    bzFile* bzf = (bzFile*)b;
    BZ_SETERR(BZ_OK);
    if (bzf == NULL || buf == NULL || len < 0)
       { BZ_SETERR(BZ_PARAM_ERROR); return 0; };
    if (bzf->writing)
       { BZ_SETERR(BZ_SEQUENCE_ERROR); return 0; };
    if (len == 0)
       { BZ_SETERR(BZ_OK); return 0; };
    bzf->strm.avail_out = len;
    bzf->strm.next_out = buf;
    while (True) {
       if (ferror(bzf->handle))
          { BZ_SETERR(BZ_IO_ERROR); return 0; };
       if (bzf->strm.avail_in == 0 && !myfeof(bzf->handle)) {
          n = fread ( bzf->buf, sizeof(UChar),
                      BZ_MAX_UNUSED, bzf->handle );
          if (ferror(bzf->handle))
             { BZ_SETERR(BZ_IO_ERROR); return 0; };
          bzf->bufN = n;
          bzf->strm.avail_in = bzf->bufN;
          bzf->strm.next_in = bzf->buf;
       }
       ret = BZ2_bzDecompress ( &(bzf->strm) );
       if (ret != BZ_OK && ret != BZ_STREAM_END)
          { BZ_SETERR(ret); return 0; };
       if (ret == BZ_OK && myfeof(bzf->handle) &&
           bzf->strm.avail_in == 0 && bzf->strm.avail_out > 0)
          { BZ_SETERR(BZ_UNEXPECTED_EOF); return 0; };
       if (ret == BZ_STREAM_END)
          { BZ_SETERR(BZ_STREAM_END);
            return len - bzf->strm.avail_out; };
       if (bzf->strm.avail_out == 0)
          { BZ_SETERR(BZ_OK); return len; };
    }
    return 0; /*not reached*/
 }
References bz_stream::avail_in, bz_stream::avail_out, b, bzFile::buf, bzFile::bufN, BZ2_bzDecompress(), BZ_IO_ERROR, BZ_MAX_UNUSED, BZ_OK, BZ_PARAM_ERROR, BZ_SEQUENCE_ERROR, BZ_SETERR, BZ_STREAM_END, BZ_UNEXPECTED_EOF, bzFile::handle, myfeof(), bz_stream::next_in, bz_stream::next_out, NULL, ret, bzFile::strm, True, and bzFile::writing.
Referenced by BZ2_bzread().
BZ2_bzReadClose()
void BZ_API() BZ2_bzReadClose (int * bzerror, BZFILE * b)
Definition at line 1143 of file bzlib.c.
 {
    bzFile* bzf = (bzFile*)b;
    BZ_SETERR(BZ_OK);
    if (bzf == NULL)
       { BZ_SETERR(BZ_OK); return; };
    if (bzf->writing)
       { BZ_SETERR(BZ_SEQUENCE_ERROR); return; };
    if (bzf->initialisedOk)
       (void)BZ2_bzDecompressEnd ( &(bzf->strm) );
    free ( bzf );
 }
References b, BZ2_bzDecompressEnd(), BZ_OK, BZ_SEQUENCE_ERROR, BZ_SETERR, bzFile::initialisedOk, NULL, bzFile::strm, and bzFile::writing.
Referenced by BZ2_bzclose().
BZ2_bzReadGetUnused()
void BZ_API() BZ2_bzReadGetUnused (int * bzerror, BZFILE * b, void ** unused, int * nUnused)
Definition at line 1221 of file bzlib.c.
 {
    bzFile* bzf = (bzFile*)b;
    if (bzf == NULL)
       { BZ_SETERR(BZ_PARAM_ERROR); return; };
    if (bzf->lastErr != BZ_STREAM_END)
       { BZ_SETERR(BZ_SEQUENCE_ERROR); return; };
    if (unused == NULL || nUnused == NULL)
       { BZ_SETERR(BZ_PARAM_ERROR); return; };
    BZ_SETERR(BZ_OK);
    *nUnused = bzf->strm.avail_in;
    *unused = bzf->strm.next_in;
 }
References bz_stream::avail_in, b, BZ_OK, BZ_PARAM_ERROR, BZ_SEQUENCE_ERROR, BZ_SETERR, BZ_STREAM_END, bzFile::lastErr, bz_stream::next_in, NULL, and bzFile::strm.
BZ2_bzReadOpen()
BZFILE* BZ_API() BZ2_bzReadOpen (int * bzerror, FILE * f, int verbosity, int small, void * unused, int nUnused)
Definition at line 1087 of file bzlib.c.
 {
    bzFile* bzf = NULL;
    int     ret;
    BZ_SETERR(BZ_OK);
    if (f == NULL ||
        (small != 0 && small != 1) ||
        (verbosity < 0 || verbosity > 4) ||
        (unused == NULL && nUnused != 0) ||
        (unused != NULL && (nUnused < 0 || nUnused > BZ_MAX_UNUSED)))
       { BZ_SETERR(BZ_PARAM_ERROR); return NULL; };
    if (ferror(f))
       { BZ_SETERR(BZ_IO_ERROR); return NULL; };
    bzf = malloc ( sizeof(bzFile) );
    if (bzf == NULL)
       { BZ_SETERR(BZ_MEM_ERROR); return NULL; };
    BZ_SETERR(BZ_OK);
    bzf->initialisedOk = False;
    bzf->handle        = f;
    bzf->bufN          = 0;
    bzf->writing       = False;
    bzf->strm.bzalloc  = NULL;
    bzf->strm.bzfree   = NULL;
    bzf->strm.opaque   = NULL;
    while (nUnused > 0) {
       bzf->buf[bzf->bufN] = *((UChar*)(unused)); bzf->bufN++;
       unused = ((void*)( 1 + ((UChar*)(unused))  ));
       nUnused--;
    }
    ret = BZ2_bzDecompressInit ( &(bzf->strm), verbosity, small );
    if (ret != BZ_OK)
       { BZ_SETERR(ret); free(bzf); return NULL; };
    bzf->strm.avail_in = bzf->bufN;
    bzf->strm.next_in  = bzf->buf;
    bzf->initialisedOk = True;
    return bzf;
 }
References bz_stream::avail_in, bzFile::buf, bzFile::bufN, BZ2_bzDecompressInit(), BZ_IO_ERROR, BZ_MAX_UNUSED, BZ_MEM_ERROR, BZ_OK, BZ_PARAM_ERROR, BZ_SETERR, bz_stream::bzalloc, bz_stream::bzfree, f(), False, bzFile::handle, bzFile::initialisedOk, bz_stream::next_in, NULL, bz_stream::opaque, ret, bzFile::strm, True, and bzFile::writing.
Referenced by bzopen_or_bzdopen().
BZ2_bzwrite()
int BZ_API() BZ2_bzwrite (BZFILE * b, void * buf, int len)
Definition at line 1492 of file bzlib.c.
 {
    int bzerr;
    BZ2_bzWrite(&bzerr,b,buf,len);
    if(bzerr == BZ_OK){
       return len;
    }else{
       return -1;
    }
 }
References b, BZ2_bzWrite(), and BZ_OK.
BZ2_bzWrite()
void BZ_API() BZ2_bzWrite (int * bzerror, BZFILE * b, void * buf, int len)
Definition at line 964 of file bzlib.c.
 {
    Int32 n, n2, ret;
    bzFile* bzf = (bzFile*)b;
    BZ_SETERR(BZ_OK);
    if (bzf == NULL || buf == NULL || len < 0)
       { BZ_SETERR(BZ_PARAM_ERROR); return; };
    if (!(bzf->writing))
       { BZ_SETERR(BZ_SEQUENCE_ERROR); return; };
    if (ferror(bzf->handle))
       { BZ_SETERR(BZ_IO_ERROR); return; };
    if (len == 0)
       { BZ_SETERR(BZ_OK); return; };
    bzf->strm.avail_in = len;
    bzf->strm.next_in  = buf;
    while (True) {
       bzf->strm.avail_out = BZ_MAX_UNUSED;
       bzf->strm.next_out = bzf->buf;
       ret = BZ2_bzCompress ( &(bzf->strm), BZ_RUN );
       if (ret != BZ_RUN_OK)
          { BZ_SETERR(ret); return; };
       if (bzf->strm.avail_out < BZ_MAX_UNUSED) {
          n = BZ_MAX_UNUSED - bzf->strm.avail_out;
          n2 = fwrite ( (void*)(bzf->buf), sizeof(UChar),
                        n, bzf->handle );
          if (n != n2 || ferror(bzf->handle))
             { BZ_SETERR(BZ_IO_ERROR); return; };
       }
       if (bzf->strm.avail_in == 0)
          { BZ_SETERR(BZ_OK); return; };
    }
 }
References bz_stream::avail_in, bz_stream::avail_out, b, bzFile::buf, BZ2_bzCompress(), BZ_IO_ERROR, BZ_MAX_UNUSED, BZ_OK, BZ_PARAM_ERROR, BZ_RUN, BZ_RUN_OK, BZ_SEQUENCE_ERROR, BZ_SETERR, bzFile::handle, bz_stream::next_in, bz_stream::next_out, NULL, ret, bzFile::strm, True, and bzFile::writing.
Referenced by BZ2_bzwrite().
BZ2_bzWriteClose()
void BZ_API() BZ2_bzWriteClose (int * bzerror, BZFILE * b, int abandon, unsigned int * nbytes_in, unsigned int * nbytes_out)
Definition at line 1009 of file bzlib.c.
 {
    BZ2_bzWriteClose64 ( bzerror, b, abandon,
                         nbytes_in, NULL, nbytes_out, NULL );
 }
References b, BZ2_bzWriteClose64(), and NULL.
Referenced by BZ2_bzclose().
BZ2_bzWriteClose64()
void BZ_API() BZ2_bzWriteClose64 (int * bzerror, BZFILE * b, int abandon, unsigned int * nbytes_in_lo32, unsigned int * nbytes_in_hi32, unsigned int * nbytes_out_lo32, unsigned int * nbytes_out_hi32)
Definition at line 1021 of file bzlib.c.
 {
    Int32   n, n2, ret;
    bzFile* bzf = (bzFile*)b;
    if (bzf == NULL)
       { BZ_SETERR(BZ_OK); return; };
    if (!(bzf->writing))
       { BZ_SETERR(BZ_SEQUENCE_ERROR); return; };
    if (ferror(bzf->handle))
       { BZ_SETERR(BZ_IO_ERROR); return; };
    if (nbytes_in_lo32 != NULL) *nbytes_in_lo32 = 0;
    if (nbytes_in_hi32 != NULL) *nbytes_in_hi32 = 0;
    if (nbytes_out_lo32 != NULL) *nbytes_out_lo32 = 0;
    if (nbytes_out_hi32 != NULL) *nbytes_out_hi32 = 0;
    if ((!abandon) && bzf->lastErr == BZ_OK) {
       while (True) {
          bzf->strm.avail_out = BZ_MAX_UNUSED;
          bzf->strm.next_out = bzf->buf;
          ret = BZ2_bzCompress ( &(bzf->strm), BZ_FINISH );
          if (ret != BZ_FINISH_OK && ret != BZ_STREAM_END)
             { BZ_SETERR(ret); return; };
          if (bzf->strm.avail_out < BZ_MAX_UNUSED) {
             n = BZ_MAX_UNUSED - bzf->strm.avail_out;
             n2 = fwrite ( (void*)(bzf->buf), sizeof(UChar),
                           n, bzf->handle );
             if (n != n2 || ferror(bzf->handle))
                { BZ_SETERR(BZ_IO_ERROR); return; };
          }
          if (ret == BZ_STREAM_END) break;
       }
    }
    if ( !abandon && !ferror ( bzf->handle ) ) {
       fflush ( bzf->handle );
       if (ferror(bzf->handle))
          { BZ_SETERR(BZ_IO_ERROR); return; };
    }
    if (nbytes_in_lo32 != NULL)
       *nbytes_in_lo32 = bzf->strm.total_in_lo32;
    if (nbytes_in_hi32 != NULL)
       *nbytes_in_hi32 = bzf->strm.total_in_hi32;
    if (nbytes_out_lo32 != NULL)
       *nbytes_out_lo32 = bzf->strm.total_out_lo32;
    if (nbytes_out_hi32 != NULL)
       *nbytes_out_hi32 = bzf->strm.total_out_hi32;
    BZ_SETERR(BZ_OK);
    BZ2_bzCompressEnd ( &(bzf->strm) );
    free ( bzf );
 }
References bz_stream::avail_out, b, bzFile::buf, BZ2_bzCompress(), BZ2_bzCompressEnd(), BZ_FINISH, BZ_FINISH_OK, BZ_IO_ERROR, BZ_MAX_UNUSED, BZ_OK, BZ_SEQUENCE_ERROR, BZ_SETERR, BZ_STREAM_END, bzFile::handle, bzFile::lastErr, bz_stream::next_out, NULL, ret, bzFile::strm, bz_stream::total_in_hi32, bz_stream::total_in_lo32, bz_stream::total_out_hi32, bz_stream::total_out_lo32, True, and bzFile::writing.
Referenced by BZ2_bzWriteClose().
BZ2_bzWriteOpen()
BZFILE* BZ_API() BZ2_bzWriteOpen (int * bzerror, FILE * f, int blockSize100k, int verbosity, int workFactor)
Definition at line 916 of file bzlib.c.
 {
    Int32   ret;
    bzFile* bzf = NULL;
    BZ_SETERR(BZ_OK);
    if (f == NULL ||
        (blockSize100k < 1 || blockSize100k > 9) ||
        (workFactor < 0 || workFactor > 250) ||
        (verbosity < 0 || verbosity > 4))
       { BZ_SETERR(BZ_PARAM_ERROR); return NULL; };
    if (ferror(f))
       { BZ_SETERR(BZ_IO_ERROR); return NULL; };
    bzf = malloc ( sizeof(bzFile) );
    if (bzf == NULL)
       { BZ_SETERR(BZ_MEM_ERROR); return NULL; };
    BZ_SETERR(BZ_OK);
    bzf->initialisedOk = False;
    bzf->bufN          = 0;
    bzf->handle        = f;
    bzf->writing       = True;
    bzf->strm.bzalloc  = NULL;
    bzf->strm.bzfree   = NULL;
    bzf->strm.opaque   = NULL;
    if (workFactor == 0) workFactor = 30;
    ret = BZ2_bzCompressInit ( &(bzf->strm), blockSize100k,
                               verbosity, workFactor );
    if (ret != BZ_OK)
       { BZ_SETERR(ret); free(bzf); return NULL; };
    bzf->strm.avail_in = 0;
    bzf->initialisedOk = True;
    return bzf;
 }
References bz_stream::avail_in, bzFile::bufN, BZ2_bzCompressInit(), BZ_IO_ERROR, BZ_MEM_ERROR, BZ_OK, BZ_PARAM_ERROR, BZ_SETERR, bz_stream::bzalloc, bz_stream::bzfree, f(), False, bzFile::handle, bzFile::initialisedOk, NULL, bz_stream::opaque, ret, bzFile::strm, True, and bzFile::writing.
Referenced by bzopen_or_bzdopen().
BZ2_indexIntoF()
__inline__ Int32 BZ2_indexIntoF (Int32 indx, Int32 * cftab)
Definition at line 687 of file bzlib.c.
 {
    Int32 nb, na, mid;
    nb = 0;
    na = 256;
    do {
       mid = (nb + na) >> 1;
       if (indx >= cftab[mid]) nb = mid; else na = mid;
    }
    while (na - nb != 1);
    return nb;
 }
bz_config_ok()
static int bz_config_ok (void) static
Definition at line 91 of file bzlib.c.
 {
    if (sizeof(int)   != 4) return 0;
    if (sizeof(short) != 2) return 0;
    if (sizeof(char)  != 1) return 0;
    return 1;
 }
Referenced by BZ2_bzCompressInit(), and BZ2_bzDecompressInit().
bzopen_or_bzdopen()
static BZFILE* bzopen_or_bzdopen (const char * path, int fd, const char * mode, int open_mode) static
Definition at line 1383 of file bzlib.c.
 {
    int    bzerr;
    char   unused[BZ_MAX_UNUSED];
    int    blockSize100k = 9;
    int    writing       = 0;
    char   mode2[10]     = "";
    FILE   *fp           = NULL;
    BZFILE *bzfp         = NULL;
    int    verbosity     = 0;
    int    workFactor    = 30;
    int    smallMode     = 0;
    int    nUnused       = 0;
    if (mode == NULL) return NULL;
    while (*mode) {
       switch (*mode) {
       case 'r':
          writing = 0; break;
       case 'w':
          writing = 1; break;
       case 's':
          smallMode = 1; break;
       default:
          if (isdigit((int)(*mode))) {
             blockSize100k = *mode-BZ_HDR_0;
          }
       }
       mode++;
    }
    strcat(mode2, writing ? "w" : "r" );
    strcat(mode2,"b");   /* binary mode */
    if (open_mode==0) {
       if (path==NULL || strcmp(path,"")==0) {
         fp = (writing ? stdout : stdin);
         SET_BINARY_MODE(fp);
       } else {
         fp = fopen(path,mode2);
       }
    } else {
 #ifdef BZ_STRICT_ANSI
       fp = NULL;
 #else
       fp = fdopen(fd,mode2);
 #endif
    }
    if (fp == NULL) return NULL;
    if (writing) {
       /* Guard against total chaos and anarchy -- JRS */
       if (blockSize100k < 1) blockSize100k = 1;
       if (blockSize100k > 9) blockSize100k = 9;
       bzfp = BZ2_bzWriteOpen(&bzerr,fp,blockSize100k,
                              verbosity,workFactor);
    } else {
       bzfp = BZ2_bzReadOpen(&bzerr,fp,verbosity,smallMode,
                             unused,nUnused);
    }
    if (bzfp == NULL) {
       if (fp != stdin && fp != stdout) fclose(fp);
       return NULL;
    }
    return bzfp;
 }
References BZ2_bzReadOpen(), BZ2_bzWriteOpen(), BZ_HDR_0, BZ_MAX_UNUSED, NULL, and SET_BINARY_MODE.
Referenced by BZ2_bzdopen(), and BZ2_bzopen().
copy_input_until_stop()
static Bool copy_input_until_stop (EState * s) static
Definition at line 289 of file bzlib.c.
 {
    Bool progress_in = False;
    if (s->mode == BZ_M_RUNNING) {
       /*-- fast track the common case --*/
       while (True) {
          /*-- block full? --*/
          if (s->nblock >= s->nblockMAX) break;
          /*-- no input? --*/
          if (s->strm->avail_in == 0) break;
          progress_in = True;
          ADD_CHAR_TO_BLOCK ( s, (UInt32)(*((UChar*)(s->strm->next_in))) );
          s->strm->next_in++;
          s->strm->avail_in--;
          s->strm->total_in_lo32++;
          if (s->strm->total_in_lo32 == 0) s->strm->total_in_hi32++;
       }
    } else {
       /*-- general, uncommon case --*/
       while (True) {
          /*-- block full? --*/
          if (s->nblock >= s->nblockMAX) break;
          /*-- no input? --*/
          if (s->strm->avail_in == 0) break;
          /*-- flush/finish end? --*/
          if (s->avail_in_expect == 0) break;
          progress_in = True;
          ADD_CHAR_TO_BLOCK ( s, (UInt32)(*((UChar*)(s->strm->next_in))) );
          s->strm->next_in++;
          s->strm->avail_in--;
          s->strm->total_in_lo32++;
          if (s->strm->total_in_lo32 == 0) s->strm->total_in_hi32++;
          s->avail_in_expect--;
       }
    }
    return progress_in;
 }
References ADD_CHAR_TO_BLOCK, bz_stream::avail_in, EState::avail_in_expect, BZ_M_RUNNING, False, EState::mode, EState::nblock, EState::nblockMAX, bz_stream::next_in, EState::strm, bz_stream::total_in_hi32, bz_stream::total_in_lo32, and True.
Referenced by handle_compress().
copy_output_until_stop()
static Bool copy_output_until_stop (EState * s) static
Definition at line 334 of file bzlib.c.
 {
    Bool progress_out = False;
    while (True) {
       /*-- no output space? --*/
       if (s->strm->avail_out == 0) break;
       /*-- block done? --*/
       if (s->state_out_pos >= s->numZ) break;
       progress_out = True;
       *(s->strm->next_out) = s->zbits[s->state_out_pos];
       s->state_out_pos++;
       s->strm->avail_out--;
       s->strm->next_out++;
       s->strm->total_out_lo32++;
       if (s->strm->total_out_lo32 == 0) s->strm->total_out_hi32++;
    }
    return progress_out;
 }
References bz_stream::avail_out, False, if(), bz_stream::next_out, EState::numZ, EState::state_out_pos, EState::strm, bz_stream::total_out_hi32, bz_stream::total_out_lo32, True, and EState::zbits.
Referenced by handle_compress().
default_bzalloc()
static void* default_bzalloc (void * opaque, Int32 items, Int32 size) static
Definition at line 102 of file bzlib.c.
 {
    void* v = malloc ( items * size );
    return v;
 }
Referenced by BZ2_bzCompressInit(), and BZ2_bzDecompressInit().
default_bzfree()
static void default_bzfree (void * opaque, void * addr) static
Definition at line 109 of file bzlib.c.
 {
    if (addr != NULL) free ( addr );
 }
References NULL.
Referenced by BZ2_bzCompressInit(), and BZ2_bzDecompressInit().
flush_RL()
static void flush_RL (EState * s) static
Definition at line 252 of file bzlib.c.
 {
    if (s->state_in_ch < 256) add_pair_to_block ( s );
    init_RL ( s );
 }
References add_pair_to_block(), init_RL(), and EState::state_in_ch.
Referenced by handle_compress().
handle_compress()
static Bool handle_compress (bz_stream * strm) static
Definition at line 361 of file bzlib.c.
 {
    Bool progress_in  = False;
    Bool progress_out = False;
    EState* s = strm->state;
    while (True) {
       if (s->state == BZ_S_OUTPUT) {
          progress_out |= copy_output_until_stop ( s );
          if (s->state_out_pos < s->numZ) break;
          if (s->mode == BZ_M_FINISHING &&
              s->avail_in_expect == 0 &&
              isempty_RL(s)) break;
          prepare_new_block ( s );
          s->state = BZ_S_INPUT;
          if (s->mode == BZ_M_FLUSHING &&
              s->avail_in_expect == 0 &&
              isempty_RL(s)) break;
       }
       if (s->state == BZ_S_INPUT) {
          progress_in |= copy_input_until_stop ( s );
          if (s->mode != BZ_M_RUNNING && s->avail_in_expect == 0) {
             flush_RL ( s );
             BZ2_compressBlock ( s, (Bool)(s->mode == BZ_M_FINISHING) );
             s->state = BZ_S_OUTPUT;
          }
          else
          if (s->nblock >= s->nblockMAX) {
             BZ2_compressBlock ( s, False );
             s->state = BZ_S_OUTPUT;
          }
          else
          if (s->strm->avail_in == 0) {
             break;
          }
       }
    }
    return progress_in || progress_out;
 }
References bz_stream::avail_in, EState::avail_in_expect, BZ2_compressBlock(), BZ_M_FINISHING, BZ_M_FLUSHING, BZ_M_RUNNING, BZ_S_INPUT, BZ_S_OUTPUT, copy_input_until_stop(), copy_output_until_stop(), False, flush_RL(), isempty_RL(), EState::mode, EState::nblock, EState::nblockMAX, EState::numZ, prepare_new_block(), bz_stream::state, EState::state, EState::state_out_pos, EState::strm, and True.
Referenced by BZ2_bzCompress().
init_RL()
static void init_RL (EState * s) static
Definition at line 131 of file bzlib.c.
 {
    s->state_in_ch  = 256;
    s->state_in_len = 0;
 }
References EState::state_in_ch, and EState::state_in_len.
Referenced by BZ2_bzCompressInit(), and flush_RL().
isempty_RL()
static Bool isempty_RL (EState * s) static
Definition at line 139 of file bzlib.c.
 {
    if (s->state_in_ch < 256 && s->state_in_len > 0)
       return False; else
       return True;
 }
References False, EState::state_in_ch, EState::state_in_len, and True.
Referenced by BZ2_bzCompress(), and handle_compress().
myfeof()
static Bool myfeof (FILE * f) static
Definition at line 906 of file bzlib.c.
 {
    Int32 c = fgetc ( f );
    if (c == EOF) return True;
    ungetc ( c, f );
    return False;
 }
References mpq::c, f(), False, and True.
Referenced by BZ2_bzRead().
prepare_new_block()
static void prepare_new_block (EState * s) static
Definition at line 117 of file bzlib.c.
 {
    Int32 i;
    s->nblock = 0;
    s->numZ = 0;
    s->state_out_pos = 0;
    BZ_INITIALISE_CRC ( s->blockCRC );
    for (i = 0; i < 256; i++) s->inUse[i] = False;
    s->blockNo++;
 }
References EState::blockCRC, EState::blockNo, BZ_INITIALISE_CRC, False, EState::inUse, EState::nblock, EState::numZ, and EState::state_out_pos.
Referenced by BZ2_bzCompressInit(), and handle_compress().
unRLE_obuf_to_output_FAST()
static Bool unRLE_obuf_to_output_FAST (DState * s) static
Definition at line 536 of file bzlib.c.
 {
    UChar k1;
    if (s->blockRandomised) {
       while (True) {
          /* try to finish existing run */
          while (True) {
             if (s->strm->avail_out == 0) return False;
             if (s->state_out_len == 0) break;
             *( (UChar*)(s->strm->next_out) ) = s->state_out_ch;
             BZ_UPDATE_CRC ( s->calculatedBlockCRC, s->state_out_ch );
             s->state_out_len--;
             s->strm->next_out++;
             s->strm->avail_out--;
             s->strm->total_out_lo32++;
             if (s->strm->total_out_lo32 == 0) s->strm->total_out_hi32++;
          }
          /* can a new run be started? */
          if (s->nblock_used == s->save_nblock+1) return False;
          /* Only caused by corrupt data stream? */
          if (s->nblock_used > s->save_nblock+1)
             return True;
          s->state_out_len = 1;
          s->state_out_ch = s->k0;
          BZ_GET_FAST(k1); BZ_RAND_UPD_MASK;
          k1 ^= BZ_RAND_MASK; s->nblock_used++;
          if (s->nblock_used == s->save_nblock+1) continue;
          if (k1 != s->k0) { s->k0 = k1; continue; };
          s->state_out_len = 2;
          BZ_GET_FAST(k1); BZ_RAND_UPD_MASK;
          k1 ^= BZ_RAND_MASK; s->nblock_used++;
          if (s->nblock_used == s->save_nblock+1) continue;
          if (k1 != s->k0) { s->k0 = k1; continue; };
          s->state_out_len = 3;
          BZ_GET_FAST(k1); BZ_RAND_UPD_MASK;
          k1 ^= BZ_RAND_MASK; s->nblock_used++;
          if (s->nblock_used == s->save_nblock+1) continue;
          if (k1 != s->k0) { s->k0 = k1; continue; };
          BZ_GET_FAST(k1); BZ_RAND_UPD_MASK;
          k1 ^= BZ_RAND_MASK; s->nblock_used++;
          s->state_out_len = ((Int32)k1) + 4;
          BZ_GET_FAST(s->k0); BZ_RAND_UPD_MASK;
          s->k0 ^= BZ_RAND_MASK; s->nblock_used++;
       }
    } else {
       /* restore */
       UInt32        c_calculatedBlockCRC = s->calculatedBlockCRC;
       UChar         c_state_out_ch       = s->state_out_ch;
       Int32         c_state_out_len      = s->state_out_len;
       Int32         c_nblock_used        = s->nblock_used;
       Int32         c_k0                 = s->k0;
       UInt32*       c_tt                 = s->tt;
       UInt32        c_tPos               = s->tPos;
       char*         cs_next_out          = s->strm->next_out;
       unsigned int  cs_avail_out         = s->strm->avail_out;
       Int32         ro_blockSize100k     = s->blockSize100k;
       /* end restore */
       UInt32       avail_out_INIT = cs_avail_out;
       Int32        s_save_nblockPP = s->save_nblock+1;
       unsigned int total_out_lo32_old;
       while (True) {
          /* try to finish existing run */
          if (c_state_out_len > 0) {
             while (True) {
                if (cs_avail_out == 0) goto return_notr;
                if (c_state_out_len == 1) break;
                *( (UChar*)(cs_next_out) ) = c_state_out_ch;
                BZ_UPDATE_CRC ( c_calculatedBlockCRC, c_state_out_ch );
                c_state_out_len--;
                cs_next_out++;
                cs_avail_out--;
             }
             s_state_out_len_eq_one:
             {
                if (cs_avail_out == 0) {
                   c_state_out_len = 1; goto return_notr;
                };
                *( (UChar*)(cs_next_out) ) = c_state_out_ch;
                BZ_UPDATE_CRC ( c_calculatedBlockCRC, c_state_out_ch );
                cs_next_out++;
                cs_avail_out--;
             }
          }
          /* Only caused by corrupt data stream? */
          if (c_nblock_used > s_save_nblockPP)
             return True;
          /* can a new run be started? */
          if (c_nblock_used == s_save_nblockPP) {
             c_state_out_len = 0; goto return_notr;
          };
          c_state_out_ch = c_k0;
          BZ_GET_FAST_C(k1); c_nblock_used++;
          if (k1 != c_k0) {
             c_k0 = k1; goto s_state_out_len_eq_one;
          };
          if (c_nblock_used == s_save_nblockPP)
             goto s_state_out_len_eq_one;
          c_state_out_len = 2;
          BZ_GET_FAST_C(k1); c_nblock_used++;
          if (c_nblock_used == s_save_nblockPP) continue;
          if (k1 != c_k0) { c_k0 = k1; continue; };
          c_state_out_len = 3;
          BZ_GET_FAST_C(k1); c_nblock_used++;
          if (c_nblock_used == s_save_nblockPP) continue;
          if (k1 != c_k0) { c_k0 = k1; continue; };
          BZ_GET_FAST_C(k1); c_nblock_used++;
          c_state_out_len = ((Int32)k1) + 4;
          BZ_GET_FAST_C(c_k0); c_nblock_used++;
       }
       return_notr:
       total_out_lo32_old = s->strm->total_out_lo32;
       s->strm->total_out_lo32 += (avail_out_INIT - cs_avail_out);
       if (s->strm->total_out_lo32 < total_out_lo32_old)
          s->strm->total_out_hi32++;
       /* save */
       s->calculatedBlockCRC = c_calculatedBlockCRC;
       s->state_out_ch       = c_state_out_ch;
       s->state_out_len      = c_state_out_len;
       s->nblock_used        = c_nblock_used;
       s->k0                 = c_k0;
       s->tt                 = c_tt;
       s->tPos               = c_tPos;
       s->strm->next_out     = cs_next_out;
       s->strm->avail_out    = cs_avail_out;
       /* end save */
    }
    return False;
 }
References bz_stream::avail_out, DState::blockRandomised, DState::blockSize100k, BZ_GET_FAST, BZ_GET_FAST_C, BZ_RAND_MASK, BZ_RAND_UPD_MASK, BZ_UPDATE_CRC, DState::calculatedBlockCRC, False, DState::k0, DState::nblock_used, bz_stream::next_out, DState::save_nblock, DState::state_out_ch, DState::state_out_len, DState::strm, bz_stream::total_out_hi32, bz_stream::total_out_lo32, DState::tPos, True, and DState::tt.
Referenced by BZ2_bzDecompress().
unRLE_obuf_to_output_SMALL()
static Bool unRLE_obuf_to_output_SMALL (DState * s) static
Definition at line 706 of file bzlib.c.
 {
    UChar k1;
    if (s->blockRandomised) {
       while (True) {
          /* try to finish existing run */
          while (True) {
             if (s->strm->avail_out == 0) return False;
             if (s->state_out_len == 0) break;
             *( (UChar*)(s->strm->next_out) ) = s->state_out_ch;
             BZ_UPDATE_CRC ( s->calculatedBlockCRC, s->state_out_ch );
             s->state_out_len--;
             s->strm->next_out++;
             s->strm->avail_out--;
             s->strm->total_out_lo32++;
             if (s->strm->total_out_lo32 == 0) s->strm->total_out_hi32++;
          }
          /* can a new run be started? */
          if (s->nblock_used == s->save_nblock+1) return False;
          /* Only caused by corrupt data stream? */
          if (s->nblock_used > s->save_nblock+1)
             return True;
          s->state_out_len = 1;
          s->state_out_ch = s->k0;
          BZ_GET_SMALL(k1); BZ_RAND_UPD_MASK;
          k1 ^= BZ_RAND_MASK; s->nblock_used++;
          if (s->nblock_used == s->save_nblock+1) continue;
          if (k1 != s->k0) { s->k0 = k1; continue; };
          s->state_out_len = 2;
          BZ_GET_SMALL(k1); BZ_RAND_UPD_MASK;
          k1 ^= BZ_RAND_MASK; s->nblock_used++;
          if (s->nblock_used == s->save_nblock+1) continue;
          if (k1 != s->k0) { s->k0 = k1; continue; };
          s->state_out_len = 3;
          BZ_GET_SMALL(k1); BZ_RAND_UPD_MASK;
          k1 ^= BZ_RAND_MASK; s->nblock_used++;
          if (s->nblock_used == s->save_nblock+1) continue;
          if (k1 != s->k0) { s->k0 = k1; continue; };
          BZ_GET_SMALL(k1); BZ_RAND_UPD_MASK;
          k1 ^= BZ_RAND_MASK; s->nblock_used++;
          s->state_out_len = ((Int32)k1) + 4;
          BZ_GET_SMALL(s->k0); BZ_RAND_UPD_MASK;
          s->k0 ^= BZ_RAND_MASK; s->nblock_used++;
       }
    } else {
       while (True) {
          /* try to finish existing run */
          while (True) {
             if (s->strm->avail_out == 0) return False;
             if (s->state_out_len == 0) break;
             *( (UChar*)(s->strm->next_out) ) = s->state_out_ch;
             BZ_UPDATE_CRC ( s->calculatedBlockCRC, s->state_out_ch );
             s->state_out_len--;
             s->strm->next_out++;
             s->strm->avail_out--;
             s->strm->total_out_lo32++;
             if (s->strm->total_out_lo32 == 0) s->strm->total_out_hi32++;
          }
          /* can a new run be started? */
          if (s->nblock_used == s->save_nblock+1) return False;
          /* Only caused by corrupt data stream? */
          if (s->nblock_used > s->save_nblock+1)
             return True;
          s->state_out_len = 1;
          s->state_out_ch = s->k0;
          BZ_GET_SMALL(k1); s->nblock_used++;
          if (s->nblock_used == s->save_nblock+1) continue;
          if (k1 != s->k0) { s->k0 = k1; continue; };
          s->state_out_len = 2;
          BZ_GET_SMALL(k1); s->nblock_used++;
          if (s->nblock_used == s->save_nblock+1) continue;
          if (k1 != s->k0) { s->k0 = k1; continue; };
          s->state_out_len = 3;
          BZ_GET_SMALL(k1); s->nblock_used++;
          if (s->nblock_used == s->save_nblock+1) continue;
          if (k1 != s->k0) { s->k0 = k1; continue; };
          BZ_GET_SMALL(k1); s->nblock_used++;
          s->state_out_len = ((Int32)k1) + 4;
          BZ_GET_SMALL(s->k0); s->nblock_used++;
       }
    }
 }
References bz_stream::avail_out, DState::blockRandomised, BZ_GET_SMALL, BZ_RAND_MASK, BZ_RAND_UPD_MASK, BZ_UPDATE_CRC, DState::calculatedBlockCRC, False, DState::k0, DState::nblock_used, bz_stream::next_out, DState::save_nblock, DState::state_out_ch, DState::state_out_len, DState::strm, bz_stream::total_out_hi32, bz_stream::total_out_lo32, and True.
Referenced by BZ2_bzDecompress().
Variable Documentation
bzerrorstrings
const char* bzerrorstrings[] static
Initial value:
= {
       "OK"
      ,"SEQUENCE_ERROR"
      ,"PARAM_ERROR"
      ,"MEM_ERROR"
      ,"DATA_ERROR"
      ,"DATA_ERROR_MAGIC"
      ,"IO_ERROR"
      ,"UNEXPECTED_EOF"
      ,"OUTBUFF_FULL"
      ,"CONFIG_ERROR"
      ,"???"
      ,"???"
      ,"???"
      ,"???"
      ,"???"
      ,"???"
}
Definition at line 1539 of file bzlib.c.
Referenced by BZ2_bzerror().