Azerotcore-wotlk: npc_gunship_gunner::npc_gunship_gunnerAI Struct Reference
npc_gunship_gunner::npc_gunship_gunnerAI Struct Reference
Public Member Functions
npc_gunship_gunnerAI (Creature *creature)
void AttackStart (Unit *target) override
void MovementInform (uint32 type, uint32 pointId) override
void UpdateAI (uint32 diff) override
bool CanAIAttack (const Unit *target) const override
Public Member Functions inherited from gunship_npc_AI
gunship_npc_AI (Creature *creature)
void SetData (uint32 type, uint32 data) override
void EnterEvadeMode () override
void JustDied (Unit *) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Protected Attributes
bool anyValid
uint16 checkTimer
Protected Attributes inherited from gunship_npc_AI
InstanceScript * Instance
SlotInfo const * Slot
uint32 Index
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from gunship_npc_AI
void SetSlotInfo (uint32 index)
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Detailed Description
Definition at line 1824 of file boss_icecrown_gunship_battle.cpp.
Constructor & Destructor Documentation
npc_gunship_gunnerAI()
npc_gunship_gunner::npc_gunship_gunnerAI::npc_gunship_gunnerAI (Creature * creature) inline
Definition at line 1826 of file boss_icecrown_gunship_battle.cpp.
                                                  : gunship_npc_AI(creature)
         {
             anyValid = true;
             checkTimer = 1000;
             creature->m_CombatDistance = 150.0f;
         }
References anyValid, checkTimer, and Creature::m_CombatDistance.
Member Function Documentation
AttackStart()
void npc_gunship_gunner::npc_gunship_gunnerAI::AttackStart (Unit * target) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1833 of file boss_icecrown_gunship_battle.cpp.
         {
             me->Attack(target, false);
         }
References Unit::Attack(), and ScriptedAI::me.
CanAIAttack()
bool npc_gunship_gunner::npc_gunship_gunnerAI::CanAIAttack (const Unit * target) const inline override virtual
Reimplemented from UnitAI.
Definition at line 1881 of file boss_icecrown_gunship_battle.cpp.
         {
             return Instance->GetBossState(DATA_ICECROWN_GUNSHIP_BATTLE) == IN_PROGRESS && target->GetTransport() && target->GetTransport() != me->GetTransport();
         }
References DATA_ICECROWN_GUNSHIP_BATTLE, InstanceScript::GetBossState(), WorldObject::GetTransport(), IN_PROGRESS, gunship_npc_AI::Instance, and ScriptedAI::me.
Referenced by UpdateAI().
MovementInform()
void npc_gunship_gunner::npc_gunship_gunnerAI::MovementInform (uint32 type, uint32 pointId) inline override virtual
Reimplemented from gunship_npc_AI.
Definition at line 1838 of file boss_icecrown_gunship_battle.cpp.
         {
             gunship_npc_AI::MovementInform(type, pointId);
             if (type == POINT_MOTION_TYPE && pointId == EVENT_CHARGE_PREPATH)
                 me->SetControlled(true, UNIT_STATE_ROOT);
         }
References EVENT_CHARGE_PREPATH, ScriptedAI::me, gunship_npc_AI::MovementInform(), POINT_MOTION_TYPE, Unit::SetControlled(), and UNIT_STATE_ROOT.
UpdateAI()
void npc_gunship_gunner::npc_gunship_gunnerAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1845 of file boss_icecrown_gunship_battle.cpp.
         {
             if (Instance->GetBossState(DATA_ICECROWN_GUNSHIP_BATTLE) != IN_PROGRESS)
                 return;
             if (me->GetReactState() == REACT_PASSIVE)
                 return;
             if (checkTimer <= diff)
             {
                 checkTimer = 1000;
                 anyValid = false;
                 Map::PlayerList const& pl = me->GetMap()->GetPlayers();
                 for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                     if (Player* p = itr->GetSource())
                         if (CanAIAttack(p) && me->IsValidAttackTarget(p))
{
                             anyValid = true;
                             me->SetInCombatWith(p);
                             p->SetInCombatWith(me);
                             me->AddThreat(p, 0.0f);
                         }
             }
             else
                 checkTimer -= diff;
             UpdateVictim();
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             if (!anyValid)
             {
                 TriggerBurningPitch(me);
                 return;
             }
             if (!me->GetVictim())
                 return;
             DoSpellAttackIfReady(me->GetEntry() == NPC_SKYBREAKER_RIFLEMAN ? SPELL_SHOOT : SPELL_HURL_AXE);
         }
References Unit::AddThreat(), anyValid, MapRefMgr::begin(), CanAIAttack(), checkTimer, DATA_ICECROWN_GUNSHIP_BATTLE, UnitAI::DoSpellAttackIfReady(), MapRefMgr::end(), InstanceScript::GetBossState(), Object::GetEntry(), WorldObject::GetMap(), Map::GetPlayers(), Creature::GetReactState(), Unit::GetVictim(), Unit::HasUnitState(), IN_PROGRESS, gunship_npc_AI::Instance, Unit::IsValidAttackTarget(), ScriptedAI::me, NPC_SKYBREAKER_RIFLEMAN, REACT_PASSIVE, Unit::SetInCombatWith(), SPELL_HURL_AXE, SPELL_SHOOT, TriggerBurningPitch(), UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
anyValid
bool npc_gunship_gunner::npc_gunship_gunnerAI::anyValid protected
Definition at line 1887 of file boss_icecrown_gunship_battle.cpp.
Referenced by npc_gunship_gunnerAI(), and UpdateAI().
checkTimer
uint16 npc_gunship_gunner::npc_gunship_gunnerAI::checkTimer protected
Definition at line 1888 of file boss_icecrown_gunship_battle.cpp.
Referenced by npc_gunship_gunnerAI(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp