Azerotcore-wotlk: boss_terestian_illhoof::boss_terestianAI Struct Reference
boss_terestian_illhoof::boss_terestianAI Struct Reference
Public Member Functions
boss_terestianAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *) override
void JustSummoned (Creature *summoned) override
void KilledUnit (Unit *) override
void JustDied (Unit *) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * instance
ObjectGuid PortalGUID [2]
uint8 PortalsCount
uint32 SacrificeTimer
uint32 ShadowboltTimer
uint32 SummonTimer
uint32 BerserkTimer
uint32 SummonKilrekTimer
bool SummonedPortals
bool Berserk
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 253 of file boss_terestian_illhoof.cpp.
Constructor & Destructor Documentation
boss_terestianAI()
boss_terestian_illhoof::boss_terestianAI::boss_terestianAI (Creature * creature) inline
Definition at line 255 of file boss_terestian_illhoof.cpp.
                                              : ScriptedAI(creature)
         {
             instance = creature->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), and instance.
Member Function Documentation
EnterCombat()
void boss_terestian_illhoof::boss_terestianAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 316 of file boss_terestian_illhoof.cpp.
         {
             Talk(SAY_AGGRO);
             DoZoneInCombat();
         }
References CreatureAI::DoZoneInCombat(), SAY_AGGRO, and CreatureAI::Talk().
JustDied()
void boss_terestian_illhoof::boss_terestianAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 342 of file boss_terestian_illhoof.cpp.
         {
             for (uint8 i = 0; i < 2; ++i)
             {
                 if (PortalGUID[i])
                 {
                     if (Creature* pPortal = ObjectAccessor::GetCreature((*me), PortalGUID[i]))
                         pPortal->DespawnOrUnsummon();
                     PortalGUID[i].Clear();
                 }
             }
             Talk(SAY_DEATH);
             instance->SetData(DATA_TERESTIAN, DONE);
         }
References ObjectGuid::Clear(), DATA_TERESTIAN, DONE, ObjectAccessor::GetCreature(), instance, ScriptedAI::me, PortalGUID, SAY_DEATH, ZoneScript::SetData(), and CreatureAI::Talk().
JustSummoned()
void boss_terestian_illhoof::boss_terestianAI::JustSummoned (Creature * summoned) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 322 of file boss_terestian_illhoof.cpp.
         {
             if (summoned->GetEntry() == NPC_PORTAL)
             {
                 PortalGUID[PortalsCount] = summoned->GetGUID();
                 ++PortalsCount;
                 if (summoned->GetUInt32Value(UNIT_CREATED_BY_SPELL) == SPELL_FIENDISH_PORTAL_1)
                 {
                     Talk(SAY_SUMMON);
                     SummonedPortals = true;
                 }
             }
         }
References Object::GetEntry(), Object::GetGUID(), Object::GetUInt32Value(), NPC_PORTAL, PortalGUID, PortalsCount, SAY_SUMMON, SPELL_FIENDISH_PORTAL_1, SummonedPortals, CreatureAI::Talk(), and UNIT_CREATED_BY_SPELL.
KilledUnit()
void boss_terestian_illhoof::boss_terestianAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 337 of file boss_terestian_illhoof.cpp.
         {
             Talk(SAY_SLAY);
         }
References SAY_SLAY, and CreatureAI::Talk().
Reset()
void boss_terestian_illhoof::boss_terestianAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 274 of file boss_terestian_illhoof.cpp.
         {
             for (uint8 i = 0; i < 2; ++i)
             {
                 if (PortalGUID[i])
                 {
                     if (Creature* pPortal = ObjectAccessor::GetCreature(*me, PortalGUID[i]))
                     {
                         CAST_AI(npc_fiendish_portal::npc_fiendish_portalAI, pPortal->AI())->DespawnAllImp();
                         pPortal->DespawnOrUnsummon();
                     }
                     PortalGUID[i].Clear();
                 }
             }
             PortalsCount = 0;
             SacrificeTimer = 30000;
             ShadowboltTimer = 5000;
             SummonTimer = 10000;
             BerserkTimer = 600000;
             SummonKilrekTimer = 0;
             SummonedPortals = false;
             Berserk = false;
             instance->SetData(DATA_TERESTIAN, NOT_STARTED);
             me->RemoveAurasDueToSpell(SPELL_BROKEN_PACT);
             if (Minion* Kilrek = me->GetFirstMinion())
             {
                 if (!Kilrek->IsAlive())
                 {
                     Kilrek->UnSummon();
                     DoCast(me, SPELL_SUMMON_IMP, true);
                 }
             }
             else
                 DoCast(me, SPELL_SUMMON_IMP, true);
         }
References Berserk, BerserkTimer, CAST_AI, ObjectGuid::Clear(), DATA_TERESTIAN, UnitAI::DoCast(), ObjectAccessor::GetCreature(), Unit::GetFirstMinion(), instance, ScriptedAI::me, NOT_STARTED, PortalGUID, PortalsCount, Unit::RemoveAurasDueToSpell(), SacrificeTimer, ZoneScript::SetData(), ShadowboltTimer, SPELL_BROKEN_PACT, SPELL_SUMMON_IMP, SummonedPortals, SummonKilrekTimer, and SummonTimer.
UpdateAI()
void boss_terestian_illhoof::boss_terestianAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 359 of file boss_terestian_illhoof.cpp.
         {
             if (!UpdateVictim())
                 return;
             if (Minion* Kilrek = me->GetFirstMinion())
             {
                 if (!Kilrek->IsAlive())
                 {
                     Kilrek->UnSummon();
                     SummonKilrekTimer = 45000;
                 }
             }
             if (SummonKilrekTimer <= diff)
             {
                 DoCast(me, SPELL_SUMMON_IMP, true);
                 me->RemoveAura(SPELL_BROKEN_PACT);
             }
             else
                 SummonKilrekTimer -= diff;
             if (SacrificeTimer <= diff)
             {
                 Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 1, 100, true);
                 if (target && target->IsAlive())
                 {
                     DoCast(target, SPELL_SACRIFICE, true);
                     DoCast(target, SPELL_SUMMON_DEMONCHAINS, true);
                     if (Creature* Chains = me->FindNearestCreature(NPC_DEMONCHAINS, 5000))
                     {
                         CAST_AI(npc_demon_chain::npc_demon_chainAI, Chains->AI())->SacrificeGUID = target->GetGUID();
                         Chains->CastSpell(Chains, SPELL_DEMON_CHAINS, true);
                         Talk(SAY_SACRIFICE);
                         SacrificeTimer = 30000;
                     }
                 }
             }
             else
                 SacrificeTimer -= diff;
             if (ShadowboltTimer <= diff)
             {
                 DoCast(SelectTarget(SELECT_TARGET_TOPAGGRO, 0), SPELL_SHADOW_BOLT);
                 ShadowboltTimer = 10000;
             }
             else
                 ShadowboltTimer -= diff;
             if (SummonTimer <= diff)
             {
                 if (!PortalGUID[0])
                     DoCastVictim(SPELL_FIENDISH_PORTAL, false);
                 if (!PortalGUID[1])
                     DoCastVictim(SPELL_FIENDISH_PORTAL_1, false);
                 if (PortalGUID[0] && PortalGUID[1])
                 {
                     if (Creature* pPortal = ObjectAccessor::GetCreature(*me, PortalGUID[urand(0, 1)]))
                         pPortal->CastSpell(me->GetVictim(), SPELL_SUMMON_FIENDISIMP, false);
                     SummonTimer = 5000;
                 }
             }
             else
                 SummonTimer -= diff;
             if (!Berserk)
             {
                 if (BerserkTimer <= diff)
                 {
                     DoCast(me, SPELL_BERSERK);
                     Berserk = true;
                 }
                 else
                     BerserkTimer -= diff;
             }
             DoMeleeAttackIfReady();
         }
References Berserk, BerserkTimer, CAST_AI, UnitAI::DoCast(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), WorldObject::FindNearestCreature(), ObjectAccessor::GetCreature(), Unit::GetFirstMinion(), Object::GetGUID(), Unit::GetVictim(), Unit::IsAlive(), ScriptedAI::me, NPC_DEMONCHAINS, PortalGUID, Unit::RemoveAura(), SacrificeTimer, SAY_SACRIFICE, SELECT_TARGET_RANDOM, SELECT_TARGET_TOPAGGRO, UnitAI::SelectTarget(), ShadowboltTimer, SPELL_BERSERK, SPELL_BROKEN_PACT, SPELL_DEMON_CHAINS, SPELL_FIENDISH_PORTAL, SPELL_FIENDISH_PORTAL_1, SPELL_SACRIFICE, SPELL_SHADOW_BOLT, SPELL_SUMMON_DEMONCHAINS, SPELL_SUMMON_FIENDISIMP, SPELL_SUMMON_IMP, SummonKilrekTimer, SummonTimer, CreatureAI::Talk(), CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
Berserk
bool boss_terestian_illhoof::boss_terestianAI::Berserk
Definition at line 272 of file boss_terestian_illhoof.cpp.
Referenced by Reset(), and UpdateAI().
BerserkTimer
uint32 boss_terestian_illhoof::boss_terestianAI::BerserkTimer
Definition at line 268 of file boss_terestian_illhoof.cpp.
Referenced by Reset(), and UpdateAI().
instance
InstanceScript* boss_terestian_illhoof::boss_terestianAI::instance
Definition at line 260 of file boss_terestian_illhoof.cpp.
Referenced by boss_terestianAI(), JustDied(), and Reset().
PortalGUID
ObjectGuid boss_terestian_illhoof::boss_terestianAI::PortalGUID[2]
Definition at line 262 of file boss_terestian_illhoof.cpp.
Referenced by JustDied(), JustSummoned(), Reset(), and UpdateAI().
PortalsCount
uint8 boss_terestian_illhoof::boss_terestianAI::PortalsCount
Definition at line 263 of file boss_terestian_illhoof.cpp.
Referenced by JustSummoned(), and Reset().
SacrificeTimer
uint32 boss_terestian_illhoof::boss_terestianAI::SacrificeTimer
Definition at line 265 of file boss_terestian_illhoof.cpp.
Referenced by Reset(), and UpdateAI().
ShadowboltTimer
uint32 boss_terestian_illhoof::boss_terestianAI::ShadowboltTimer
Definition at line 266 of file boss_terestian_illhoof.cpp.
Referenced by Reset(), and UpdateAI().
SummonedPortals
bool boss_terestian_illhoof::boss_terestianAI::SummonedPortals
Definition at line 271 of file boss_terestian_illhoof.cpp.
Referenced by JustSummoned(), and Reset().
SummonKilrekTimer
uint32 boss_terestian_illhoof::boss_terestianAI::SummonKilrekTimer
Definition at line 269 of file boss_terestian_illhoof.cpp.
Referenced by Reset(), and UpdateAI().
SummonTimer
uint32 boss_terestian_illhoof::boss_terestianAI::SummonTimer
Definition at line 267 of file boss_terestian_illhoof.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/Karazhan/boss_terestian_illhoof.cpp