Azerotcore-wotlk: Acore::NearestPlayerInObjectRangeCheck Class Reference
Acore::NearestPlayerInObjectRangeCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
NearestPlayerInObjectRangeCheck (WorldObject const *obj, float range)
bool operator() (Player *u)
Private Member Functions
NearestPlayerInObjectRangeCheck (NearestPlayerInObjectRangeCheck const &)
Private Attributes
WorldObject const * i_obj
float i_range
Detailed Description
Definition at line 1284 of file GridNotifiers.h.
Constructor & Destructor Documentation
NearestPlayerInObjectRangeCheck() [1/2]
Acore::NearestPlayerInObjectRangeCheck::NearestPlayerInObjectRangeCheck (WorldObject const * obj, float range) inline
Definition at line 1287 of file GridNotifiers.h.
                                                                              : i_obj(obj), i_range(range)
         {
         }
NearestPlayerInObjectRangeCheck() [2/2]
Acore::NearestPlayerInObjectRangeCheck::NearestPlayerInObjectRangeCheck (NearestPlayerInObjectRangeCheck const &) private
Member Function Documentation
operator()()
bool Acore::NearestPlayerInObjectRangeCheck::operator() (Player * u) inline
Definition at line 1291 of file GridNotifiers.h.
         {
             if (u->IsAlive() && i_obj->IsWithinDistInMap(u, i_range))
             {
                 i_range = i_obj->GetDistance(u);
                 return true;
             }
             return false;
         }
References WorldObject::GetDistance(), i_obj, i_range, Unit::IsAlive(), and WorldObject::IsWithinDistInMap().
Member Data Documentation
i_obj
WorldObject const* Acore::NearestPlayerInObjectRangeCheck::i_obj private
Definition at line 1302 of file GridNotifiers.h.
Referenced by operator()().
i_range
float Acore::NearestPlayerInObjectRangeCheck::i_range private
Definition at line 1303 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/game/Grids/Notifiers/GridNotifiers.h