Azerotcore-wotlk: Acore::Impl::GenericHMAC< HashCreator, DigestLength > Class Template Reference
Acore::Impl::GenericHMAC< HashCreator, DigestLength > Class Template Reference
#include <HMAC.h>
Public Types
using Digest = std::array< uint8, DIGEST_LENGTH >
Public Member Functions
GenericHMAC (uint8 const *seed, size_t len)
template<typename Container >
GenericHMAC (Container const &container)
~GenericHMAC ()
void UpdateData (uint8 const *data, size_t len)
void UpdateData (std::string_view str)
void UpdateData (std::string const &str)
void UpdateData (char const *str)
template<typename Container >
void UpdateData (Container const &c)
void Finalize ()
Digest const & GetDigest () const
Static Public Member Functions
template<typename Container >
static Digest GetDigestOf (Container const &seed, uint8 const *data, size_t len)
template<typename Container , typename... Ts>
static auto GetDigestOf (Container const &seed, Ts &&... pack) -> std::enable_if_t< !(std::is_integral_v< std::decay_t< Ts >>||...), Digest >
Static Public Attributes
static constexpr size_t DIGEST_LENGTH = DigestLength
Private Attributes
HMAC_CTX * _ctx
Digest _digest = { }
Detailed Description
template<HMACImpl::HashCreator HashCreator, size_t DigestLength>
class Acore::Impl::GenericHMAC< HashCreator, DigestLength >
Definition at line 57 of file HMAC.h.
Member Typedef Documentation
Digest
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> using Acore::Impl::GenericHMAC< HashCreator, DigestLength >::Digest = std::array<uint8, DIGEST_LENGTH>
Definition at line 61 of file HMAC.h.
Constructor & Destructor Documentation
GenericHMAC() [1/2]
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GenericHMAC (uint8 const * seed, size_t len) inline
Definition at line 81 of file HMAC.h.
                                                    : _ctx(HMACImpl::MakeCTX())
         {
             int result = HMAC_Init_ex(_ctx, seed, len, HashCreator(), nullptr);
             ASSERT(result == 1);
         }
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_ctx, and ASSERT.
GenericHMAC() [2/2]
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> template<typename Container > Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GenericHMAC (Container const & container) inline
Definition at line 86 of file HMAC.h.
 : GenericHMAC(std::data(container), std::size(container)) {}
~GenericHMAC()
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> Acore::Impl::GenericHMAC< HashCreator, DigestLength >::~GenericHMAC () inline
Definition at line 88 of file HMAC.h.
         {
             if (!_ctx)
             {
                 return;
             }
             HMACImpl::DestroyCTX(_ctx);
             _ctx = nullptr;
         }
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_ctx, and Acore::Impl::HMACImpl::DestroyCTX().
Member Function Documentation
Finalize()
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> void Acore::Impl::GenericHMAC< HashCreator, DigestLength >::Finalize () inline
Definition at line 109 of file HMAC.h.
         {
             uint32 length = 0;
             int result = HMAC_Final(_ctx, _digest.data(), &length);
             ASSERT(result == 1);
             ASSERT(length == DIGEST_LENGTH);
             HMACImpl::DestroyCTX(_ctx);
             _ctx = nullptr;
         }
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_ctx, Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_digest, ASSERT, Acore::Impl::HMACImpl::DestroyCTX(), Acore::Impl::GenericHMAC< HashCreator, DigestLength >::DIGEST_LENGTH, and G3D::length().
GetDigest()
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> Digest const& Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GetDigest () const inline
Definition at line 119 of file HMAC.h.
 { return _digest; }
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_digest.
GetDigestOf() [1/2]
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> template<typename Container , typename... Ts> static auto Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GetDigestOf (Container const & seed, Ts &&... pack) -> std::enable_if_t < !(std::is_integral_v<std::decay_t<Ts>> || ...), Digest > inline static
Definition at line 73 of file HMAC.h.
         {
             GenericHMAC hash(seed);
             (hash.UpdateData(std::forward<Ts>(pack)), ...);
             hash.Finalize();
             return hash.GetDigest();
         }
References hash().
GetDigestOf() [2/2]
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> template<typename Container > static Digest Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GetDigestOf (Container const & seed, uint8 const * data, size_t len) inline static
Definition at line 64 of file HMAC.h.
         {
             GenericHMAC hash(seed);
             hash.UpdateData(data, len);
             hash.Finalize();
             return hash.GetDigest();
         }
References hash().
Referenced by AuthCrypt::Init(), and WardenWin::RequestChecks().
UpdateData() [1/5]
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> void Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData (char const * str) inline
Definition at line 105 of file HMAC.h.
 { UpdateData(std::string_view(str)); } /* explicit overload to avoid using the container template */
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData().
Referenced by Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData().
UpdateData() [2/5]
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> template<typename Container > void Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData (Container const & c) inline
Definition at line 107 of file HMAC.h.
 { UpdateData(std::data(c), std::size(c)); }
References mpq::c, and Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData().
Referenced by Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData().
UpdateData() [3/5]
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> void Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData (std::string const & str) inline
Definition at line 104 of file HMAC.h.
 { UpdateData(std::string_view(str)); } /* explicit overload to avoid using the container template */
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData().
Referenced by Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData().
UpdateData() [4/5]
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> void Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData (std::string_view str) inline
Definition at line 103 of file HMAC.h.
 { UpdateData(reinterpret_cast<uint8 const*>(str.data()), str.size()); }
References const, and Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData().
Referenced by Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData().
UpdateData() [5/5]
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> void Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData (uint8 const * data, size_t len) inline
Definition at line 98 of file HMAC.h.
         {
             int result = HMAC_Update(_ctx, data, len);
             ASSERT(result == 1);
         }
References Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_ctx, and ASSERT.
Member Data Documentation
_ctx
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> HMAC_CTX* Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_ctx private
Definition at line 121 of file HMAC.h.
Referenced by Acore::Impl::GenericHMAC< HashCreator, DigestLength >::Finalize(), Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GenericHMAC(), Acore::Impl::GenericHMAC< HashCreator, DigestLength >::UpdateData(), and Acore::Impl::GenericHMAC< HashCreator, DigestLength >::~GenericHMAC().
_digest
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> Digest Acore::Impl::GenericHMAC< HashCreator, DigestLength >::_digest = { } private
Definition at line 122 of file HMAC.h.
Referenced by Acore::Impl::GenericHMAC< HashCreator, DigestLength >::Finalize(), and Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GetDigest().
DIGEST_LENGTH
template<HMACImpl::HashCreator HashCreator, size_t DigestLength> constexpr size_t Acore::Impl::GenericHMAC< HashCreator, DigestLength >::DIGEST_LENGTH = DigestLength static constexpr
Definition at line 60 of file HMAC.h.
Referenced by Acore::Impl::GenericHMAC< HashCreator, DigestLength >::Finalize().
The documentation for this class was generated from the following file:
src/common/Cryptography/HMAC.h