Azerotcore-wotlk: ProducerConsumerQueue< T > Class Template Reference
ProducerConsumerQueue< T > Class Template Reference
#include <PCQueue.h>
Public Member Functions
ProducerConsumerQueue ()
void Push (const T &value)
bool Empty ()
size_t Size () const
bool Pop (T &value)
void WaitAndPop (T &value)
void Cancel ()
Private Member Functions
template<typename E = T>
std::enable_if< std::is_pointer< E >::value >::type DeleteQueuedObject (E &obj)
template<typename E = T>
std::enable_if<!std::is_pointer< E >::value >::type DeleteQueuedObject (E const &)
Private Attributes
std::mutex _queueLock
std::queue< T > _queue
std::condition_variable _condition
std::atomic< bool > _shutdown
Detailed Description
template<typename T>
class ProducerConsumerQueue< T >
Definition at line 28 of file PCQueue.h.
Constructor & Destructor Documentation
ProducerConsumerQueue()
template<typename T > ProducerConsumerQueue< T >::ProducerConsumerQueue () inline
Definition at line 34 of file PCQueue.h.
 : _shutdown(false) { }
Member Function Documentation
Cancel()
template<typename T > void ProducerConsumerQueue< T >::Cancel () inline
Definition at line 96 of file PCQueue.h.
     {
         std::unique_lock<std::mutex> lock(_queueLock);
         while (!_queue.empty())
         {
             T& value = _queue.front();
             DeleteQueuedObject(value);
             _queue.pop();
         }
         _shutdown = true;
         _condition.notify_all();
     }
References ProducerConsumerQueue< T >::_condition, ProducerConsumerQueue< T >::_queue, ProducerConsumerQueue< T >::_queueLock, ProducerConsumerQueue< T >::_shutdown, and ProducerConsumerQueue< T >::DeleteQueuedObject().
Referenced by MMAP::MapBuilder::buildAllMaps(), MapUpdater::deactivate(), and DatabaseWorker::~DatabaseWorker().
DeleteQueuedObject() [1/2]
template<typename T > template<typename E = T> std::enable_if<std::is_pointer<E>::value>::type ProducerConsumerQueue< T >::DeleteQueuedObject (E & obj) inline private
Definition at line 116 of file PCQueue.h.
 { delete obj; }
Referenced by ProducerConsumerQueue< T >::Cancel().
DeleteQueuedObject() [2/2]
template<typename T > template<typename E = T> std::enable_if<!std::is_pointer<E>::value>::type ProducerConsumerQueue< T >::DeleteQueuedObject (E const &) inline private
Definition at line 119 of file PCQueue.h.
 { }
Empty()
template<typename T > bool ProducerConsumerQueue< T >::Empty () inline
Definition at line 47 of file PCQueue.h.
     {
         std::lock_guard<std::mutex> lock(_queueLock);
         return _queue.empty();
     }
References ProducerConsumerQueue< T >::_queue, and ProducerConsumerQueue< T >::_queueLock.
Referenced by MMAP::MapBuilder::buildAllMaps().
Pop()
template<typename T > bool ProducerConsumerQueue< T >::Pop (T & value) inline
Definition at line 59 of file PCQueue.h.
     {
         std::lock_guard<std::mutex> lock(_queueLock);
         if (_queue.empty() || _shutdown)
         {
             return false;
         }
         value = _queue.front();
         _queue.pop();
         return true;
     }
References ProducerConsumerQueue< T >::_queue, ProducerConsumerQueue< T >::_queueLock, and ProducerConsumerQueue< T >::_shutdown.
Push()
template<typename T > void ProducerConsumerQueue< T >::Push (const T & value) inline
Definition at line 39 of file PCQueue.h.
     {
         std::lock_guard<std::mutex> lock(_queueLock);
         _queue.push(std::move(value));
         _condition.notify_one();
     }
References ProducerConsumerQueue< T >::_condition, ProducerConsumerQueue< T >::_queue, and ProducerConsumerQueue< T >::_queueLock.
Referenced by MMAP::MapBuilder::buildAllMaps(), MapUpdater::schedule_lfg_update(), and MapUpdater::schedule_update().
Size()
template<typename T > size_t ProducerConsumerQueue< T >::Size () const inline
Definition at line 54 of file PCQueue.h.
     {
         return _queue.size();
     }
References ProducerConsumerQueue< T >::_queue.
WaitAndPop()
template<typename T > void ProducerConsumerQueue< T >::WaitAndPop (T & value) inline
Definition at line 75 of file PCQueue.h.
     {
         std::unique_lock<std::mutex> lock(_queueLock);
         // we could be using .wait(lock, predicate) overload here but it is broken
         // https://connect.microsoft.com/VisualStudio/feedback/details/1098841
         while (_queue.empty() && !_shutdown)
         {
             _condition.wait(lock);
         }
         if (_queue.empty() || _shutdown)
         {
             return;
         }
         value = _queue.front();
         _queue.pop();
     }
References ProducerConsumerQueue< T >::_condition, ProducerConsumerQueue< T >::_queue, ProducerConsumerQueue< T >::_queueLock, and ProducerConsumerQueue< T >::_shutdown.
Referenced by DatabaseWorker::WorkerThread(), MapUpdater::WorkerThread(), and MMAP::MapBuilder::WorkerThread().
Member Data Documentation
_condition
template<typename T > std::condition_variable ProducerConsumerQueue< T >::_condition private
Definition at line 33 of file PCQueue.h.
Referenced by ProducerConsumerQueue< T >::Cancel(), ProducerConsumerQueue< T >::Push(), and ProducerConsumerQueue< T >::WaitAndPop().
_queue
template<typename T > std::queue<T> ProducerConsumerQueue< T >::_queue private
Definition at line 32 of file PCQueue.h.
Referenced by ProducerConsumerQueue< T >::Cancel(), ProducerConsumerQueue< T >::Empty(), ProducerConsumerQueue< T >::Pop(), ProducerConsumerQueue< T >::Push(), ProducerConsumerQueue< T >::Size(), and ProducerConsumerQueue< T >::WaitAndPop().
_queueLock
template<typename T > std::mutex ProducerConsumerQueue< T >::_queueLock private
Definition at line 31 of file PCQueue.h.
Referenced by ProducerConsumerQueue< T >::Cancel(), ProducerConsumerQueue< T >::Empty(), ProducerConsumerQueue< T >::Pop(), ProducerConsumerQueue< T >::Push(), and ProducerConsumerQueue< T >::WaitAndPop().
_shutdown
template<typename T > std::atomic<bool> ProducerConsumerQueue< T >::_shutdown private
Definition at line 34 of file PCQueue.h.
Referenced by ProducerConsumerQueue< T >::Cancel(), ProducerConsumerQueue< T >::Pop(), and ProducerConsumerQueue< T >::WaitAndPop().
The documentation for this class was generated from the following file:
src/common/Threading/PCQueue.h