Azerotcore-wotlk: dtFindNearestPolyQuery Class Reference
dtFindNearestPolyQuery Class Reference
Public Member Functions
dtFindNearestPolyQuery (const dtNavMeshQuery *query, const float *center)
dtPolyRef nearestRef () const
const float * nearestPoint () const
void process (const dtMeshTile *tile, dtPoly **polys, dtPolyRef *refs, int count)
Public Member Functions inherited from dtPolyQuery
virtual ~dtPolyQuery ()
Private Attributes
const dtNavMeshQuery * m_query
const float * m_center
float m_nearestDistanceSqr
dtPolyRef m_nearestRef
float m_nearestPoint [3]
Detailed Description
Definition at line 626 of file DetourNavMeshQuery.cpp.
Constructor & Destructor Documentation
dtFindNearestPolyQuery()
dtFindNearestPolyQuery::dtFindNearestPolyQuery (const dtNavMeshQuery * query, const float * center) inline
Definition at line 635 of file DetourNavMeshQuery.cpp.
         : m_query(query), m_center(center), m_nearestDistanceSqr(FLT_MAX), m_nearestRef(0), m_nearestPoint()
     {
     }
Member Function Documentation
nearestPoint()
const float* dtFindNearestPolyQuery::nearestPoint () const inline
Definition at line 641 of file DetourNavMeshQuery.cpp.
 { return m_nearestPoint; }
References m_nearestPoint.
Referenced by dtNavMeshQuery::findNearestPoly().
nearestRef()
dtPolyRef dtFindNearestPolyQuery::nearestRef () const inline
Definition at line 640 of file DetourNavMeshQuery.cpp.
 { return m_nearestRef; }
References m_nearestRef.
Referenced by dtNavMeshQuery::findNearestPoly().
process()
void dtFindNearestPolyQuery::process (const dtMeshTile * tile, dtPoly ** polys, dtPolyRef * refs, int count) inline virtual
Called for each batch of unique polygons touched by the search area in dtNavMeshQuery::queryPolygons. This can be called multiple times for a single query.
Implements dtPolyQuery.
Definition at line 643 of file DetourNavMeshQuery.cpp.
     {
         dtIgnoreUnused(polys);
         for (int i = 0; i < count; ++i)
         {
             dtPolyRef ref = refs[i];
             float closestPtPoly[3];
             float diff[3];
             bool posOverPoly = false;
             float d;
             m_query->closestPointOnPoly(ref, m_center, closestPtPoly, &posOverPoly);
             // If a point is directly over a polygon and closer than
             // climb height, favor that instead of straight line nearest point.
             dtVsub(diff, m_center, closestPtPoly);
             if (posOverPoly)
             {
                 d = dtAbs(diff[1]) - tile->header->walkableClimb;
                 d = d > 0 ? d*d : 0;
             }
             else
             {
                 d = dtVlenSqr(diff);
             }
             if (d < m_nearestDistanceSqr)
             {
                 dtVcopy(m_nearestPoint, closestPtPoly);
                 m_nearestDistanceSqr = d;
                 m_nearestRef = ref;
             }
         }
     }
References dtNavMeshQuery::closestPointOnPoly(), count(), mpq::d, diff(), dtAbs(), dtIgnoreUnused(), dtVcopy(), dtVlenSqr(), dtVsub(), dtMeshTile::header, m_center, m_nearestDistanceSqr, m_nearestPoint, m_nearestRef, m_query, and dtMeshHeader::walkableClimb.
Member Data Documentation
m_center
const float* dtFindNearestPolyQuery::m_center private
Definition at line 629 of file DetourNavMeshQuery.cpp.
Referenced by process().
m_nearestDistanceSqr
float dtFindNearestPolyQuery::m_nearestDistanceSqr private
Definition at line 630 of file DetourNavMeshQuery.cpp.
Referenced by process().
m_nearestPoint
float dtFindNearestPolyQuery::m_nearestPoint[3] private
Definition at line 632 of file DetourNavMeshQuery.cpp.
Referenced by nearestPoint(), and process().
m_nearestRef
dtPolyRef dtFindNearestPolyQuery::m_nearestRef private
Definition at line 631 of file DetourNavMeshQuery.cpp.
Referenced by nearestRef(), and process().
m_query
const dtNavMeshQuery* dtFindNearestPolyQuery::m_query private
Definition at line 628 of file DetourNavMeshQuery.cpp.
Referenced by process().
The documentation for this class was generated from the following file:
deps/recastnavigation/Detour/Source/DetourNavMeshQuery.cpp