Azerotcore-wotlk: npc_maghar_captive::npc_maghar_captiveAI Struct Reference
npc_maghar_captive::npc_maghar_captiveAI Struct Reference
Public Member Functions
npc_maghar_captiveAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *) override
void JustDied (Unit *) override
void WaypointReached (uint32 waypointId) override
void JustSummoned (Creature *summoned) override
void SpellHitTarget (Unit *, const SpellInfo *spell) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from npc_escortAI
npc_escortAI (Creature *creature)
~npc_escortAI () override
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void JustRespawned () override
void ReturnToLastPoint ()
void EnterEvadeMode () override
virtual void UpdateEscortAI (uint32 diff)
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
virtual void WaypointStart (uint32)
void Start (bool isActiveAttacker=true, bool run=false, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetRun (bool on=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
uint32 ChainLightningTimer
uint32 HealTimer
uint32 FrostShockTimer
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from npc_escortAI
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 96 of file zone_nagrand.cpp.
Constructor & Destructor Documentation
npc_maghar_captiveAI()
npc_maghar_captive::npc_maghar_captiveAI::npc_maghar_captiveAI (Creature * creature) inline
Definition at line 98 of file zone_nagrand.cpp.
 : npc_escortAI(creature) { Reset(); }
References Reset().
Member Function Documentation
EnterCombat()
void npc_maghar_captive::npc_maghar_captiveAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 111 of file zone_nagrand.cpp.
         {
             DoCast(me, SPELL_EARTHBIND_TOTEM, false);
         }
References UnitAI::DoCast(), ScriptedAI::me, and SPELL_EARTHBIND_TOTEM.
JustDied()
void npc_maghar_captive::npc_maghar_captiveAI::JustDied (Unit *) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 116 of file zone_nagrand.cpp.
         {
             if (!HasEscortState(STATE_ESCORT_ESCORTING))
                 return;
             if (Player* player = GetPlayerForEscort())
             {
                 if (player->GetQuestStatus(QUEST_TOTEM_KARDASH_H) != QUEST_STATUS_COMPLETE)
                     player->FailQuest(QUEST_TOTEM_KARDASH_H);
             }
         }
References npc_escortAI::GetPlayerForEscort(), npc_escortAI::HasEscortState(), QUEST_STATUS_COMPLETE, QUEST_TOTEM_KARDASH_H, and STATE_ESCORT_ESCORTING.
JustSummoned()
void npc_maghar_captive::npc_maghar_captiveAI::JustSummoned (Creature * summoned) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 153 of file zone_nagrand.cpp.
         {
             if (summoned->GetEntry() == NPC_MURK_BRUTE)
                 summoned->AI()->Talk(SAY_MAG_NO_ESCAPE);
             if (summoned->IsTotem())
                 return;
             summoned->SetWalk(false);
             summoned->GetMotionMaster()->MovePoint(0, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ());
             summoned->AI()->AttackStart(me);
         }
References Creature::AI(), UnitAI::AttackStart(), Object::GetEntry(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::IsTotem(), ScriptedAI::me, MotionMaster::MovePoint(), NPC_MURK_BRUTE, SAY_MAG_NO_ESCAPE, Creature::SetWalk(), and CreatureAI::Talk().
Reset()
void npc_maghar_captive::npc_maghar_captiveAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 104 of file zone_nagrand.cpp.
         {
             ChainLightningTimer = 1000;
             HealTimer = 0;
             FrostShockTimer = 6000;
         }
References ChainLightningTimer, FrostShockTimer, and HealTimer.
Referenced by npc_maghar_captiveAI().
SpellHitTarget()
void npc_maghar_captive::npc_maghar_captiveAI::SpellHitTarget (Unit * , const SpellInfo * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 166 of file zone_nagrand.cpp.
         {
             if (spell->Id == SPELL_CHAIN_LIGHTNING)
             {
                 if (rand() % 10)
                     return;
                 Talk(SAY_MAG_LIGHTNING);
             }
         }
References SpellInfo::Id, SAY_MAG_LIGHTNING, SPELL_CHAIN_LIGHTNING, and CreatureAI::Talk().
UpdateAI()
void npc_maghar_captive::npc_maghar_captiveAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 177 of file zone_nagrand.cpp.
         {
             npc_escortAI::UpdateAI(diff);
             if (!UpdateVictim())
                 return;
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             if (ChainLightningTimer <= diff)
             {
                 DoCastVictim(SPELL_CHAIN_LIGHTNING);
                 ChainLightningTimer = urand(7000, 14000);
             }
             else
                 ChainLightningTimer -= diff;
             if (HealthBelowPct(30))
             {
                 if (HealTimer <= diff)
                 {
                     DoCast(me, SPELL_HEALING_WAVE);
                     HealTimer = 5000;
                 }
                 else
                     HealTimer -= diff;
             }
             if (FrostShockTimer <= diff)
             {
                 DoCastVictim(SPELL_FROST_SHOCK);
                 FrostShockTimer = urand(7500, 15000);
             }
             else
                 FrostShockTimer -= diff;
             DoMeleeAttackIfReady();
         }
References ChainLightningTimer, diff(), UnitAI::DoCast(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), FrostShockTimer, Unit::HasUnitState(), ScriptedAI::HealthBelowPct(), HealTimer, ScriptedAI::me, SPELL_CHAIN_LIGHTNING, SPELL_FROST_SHOCK, SPELL_HEALING_WAVE, UNIT_STATE_CASTING, npc_escortAI::UpdateAI(), CreatureAI::UpdateVictim(), and urand().
WaypointReached()
void npc_maghar_captive::npc_maghar_captiveAI::WaypointReached (uint32 waypointId) inline override virtual
Implements npc_escortAI.
Definition at line 128 of file zone_nagrand.cpp.
         {
             switch (waypointId)
             {
                 case 7:
                     Talk(SAY_MAG_MORE);
                     if (Creature* temp = me->SummonCreature(NPC_MURK_PUTRIFIER, m_afAmbushB[0], m_afAmbushB[1], m_afAmbushB[2], 0.0f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 25000))
                         temp->AI()->Talk(SAY_MAG_MORE_REPLY);
                     me->SummonCreature(NPC_MURK_PUTRIFIER, m_afAmbushB[0] - 2.5f, m_afAmbushB[1] - 2.5f, m_afAmbushB[2], 0.0f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 25000);
                     me->SummonCreature(NPC_MURK_SCAVENGER, m_afAmbushB[0] + 2.5f, m_afAmbushB[1] + 2.5f, m_afAmbushB[2], 0.0f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 25000);
                     me->SummonCreature(NPC_MURK_SCAVENGER, m_afAmbushB[0] + 2.5f, m_afAmbushB[1] - 2.5f, m_afAmbushB[2], 0.0f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 25000);
                     break;
                 case 16:
                     Talk(SAY_MAG_COMPLETE);
                     if (Player* player = GetPlayerForEscort())
                         player->GroupEventHappens(QUEST_TOTEM_KARDASH_H, me);
                     SetRun();
                     break;
             }
         }
References npc_escortAI::GetPlayerForEscort(), m_afAmbushB, ScriptedAI::me, NPC_MURK_PUTRIFIER, NPC_MURK_SCAVENGER, QUEST_TOTEM_KARDASH_H, SAY_MAG_COMPLETE, SAY_MAG_MORE, SAY_MAG_MORE_REPLY, npc_escortAI::SetRun(), WorldObject::SummonCreature(), CreatureAI::Talk(), and TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT.
Member Data Documentation
ChainLightningTimer
uint32 npc_maghar_captive::npc_maghar_captiveAI::ChainLightningTimer
Definition at line 100 of file zone_nagrand.cpp.
Referenced by Reset(), and UpdateAI().
FrostShockTimer
uint32 npc_maghar_captive::npc_maghar_captiveAI::FrostShockTimer
Definition at line 102 of file zone_nagrand.cpp.
Referenced by Reset(), and UpdateAI().
HealTimer
uint32 npc_maghar_captive::npc_maghar_captiveAI::HealTimer
Definition at line 101 of file zone_nagrand.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/zone_nagrand.cpp