Azerotcore-wotlk: boss_bronjahm::boss_bronjahmAI Struct Reference
boss_bronjahm::boss_bronjahmAI Struct Reference
Public Member Functions
boss_bronjahmAI (Creature *creature)
void JustReachedHome () override
void Reset () override
void EnterCombat (Unit *) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void SpellHitTarget (Unit *, const SpellInfo *spell) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *who) override
void JustSummoned (Creature *summon) override
void EnterEvadeMode () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
EventMap events
SummonList summons
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 66 of file boss_bronjahm.cpp.
Constructor & Destructor Documentation
boss_bronjahmAI()
boss_bronjahm::boss_bronjahmAI::boss_bronjahmAI (Creature * creature) inline
Definition at line 68 of file boss_bronjahm.cpp.
                                             : ScriptedAI(creature), summons(me)
         {
             pInstance = creature->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), and pInstance.
Member Function Documentation
DamageTaken()
void boss_bronjahm::boss_bronjahmAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 107 of file boss_bronjahm.cpp.
         {
             if (!me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE) && me->HealthBelowPctDamaged(35, damage))
             {
                 me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE);
                 me->GetMotionMaster()->Clear();
                 me->GetMotionMaster()->MoveIdle();
                 me->CastSpell(me, SPELL_TELEPORT, false);
                 events.CancelEvent(EVENT_SPELL_CORRUPT_SOUL);
                 events.DelayEvents(6000);
                 events.RescheduleEvent(EVENT_SPELL_FEAR, urand(8000, 14000));
             }
         }
References Unit::CastSpell(), MotionMaster::Clear(), EVENT_SPELL_CORRUPT_SOUL, EVENT_SPELL_FEAR, Unit::GetMotionMaster(), Object::HasFlag(), Unit::HealthBelowPctDamaged(), ScriptedAI::me, MotionMaster::MoveIdle(), Object::SetFlag(), SPELL_TELEPORT, UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE, and urand().
EnterCombat()
void boss_bronjahm::boss_bronjahmAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 92 of file boss_bronjahm.cpp.
         {
             Talk(SAY_AGGRO);
             me->RemoveAurasDueToSpell(SPELL_SOULSTORM_CHANNEL_OOC);
             DoZoneInCombat();
             events.Reset();
             events.RescheduleEvent(EVENT_SPELL_SHADOW_BOLT, 2000);
             events.RescheduleEvent(EVENT_SPELL_MAGICS_BANE, urand(5000, 10000));
             events.RescheduleEvent(EVENT_SPELL_CORRUPT_SOUL, urand(14000, 20000));
             if (pInstance)
                 pInstance->SetData(DATA_BRONJAHM, IN_PROGRESS);
         }
References DATA_BRONJAHM, CreatureAI::DoZoneInCombat(), EVENT_SPELL_CORRUPT_SOUL, EVENT_SPELL_MAGICS_BANE, EVENT_SPELL_SHADOW_BOLT, IN_PROGRESS, ScriptedAI::me, pInstance, Unit::RemoveAurasDueToSpell(), SAY_AGGRO, ZoneScript::SetData(), SPELL_SOULSTORM_CHANNEL_OOC, CreatureAI::Talk(), and urand().
EnterEvadeMode()
void boss_bronjahm::boss_bronjahmAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 201 of file boss_bronjahm.cpp.
         {
             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE);
             ScriptedAI::EnterEvadeMode();
         }
References CreatureAI::EnterEvadeMode(), ScriptedAI::me, Object::RemoveFlag(), UNIT_FIELD_FLAGS, and UNIT_FLAG_DISABLE_MOVE.
JustDied()
void boss_bronjahm::boss_bronjahmAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 182 of file boss_bronjahm.cpp.
         {
             Talk(SAY_DEATH);
             if (pInstance)
                 pInstance->SetData(DATA_BRONJAHM, DONE);
         }
References DATA_BRONJAHM, DONE, pInstance, SAY_DEATH, ZoneScript::SetData(), and CreatureAI::Talk().
JustReachedHome()
void boss_bronjahm::boss_bronjahmAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 77 of file boss_bronjahm.cpp.
         {
             me->CastSpell(me, SPELL_SOULSTORM_CHANNEL_OOC, true);
         }
References Unit::CastSpell(), ScriptedAI::me, and SPELL_SOULSTORM_CHANNEL_OOC.
JustSummoned()
void boss_bronjahm::boss_bronjahmAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 195 of file boss_bronjahm.cpp.
         {
             summons.Summon(summon);
             summon->SetReactState(REACT_PASSIVE);
         }
References REACT_PASSIVE, Creature::SetReactState(), SummonList::Summon(), and summons.
KilledUnit()
void boss_bronjahm::boss_bronjahmAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 189 of file boss_bronjahm.cpp.
         {
             if (who->GetTypeId() == TYPEID_PLAYER)
                 Talk(SAY_SLAY);
         }
References Object::GetTypeId(), SAY_SLAY, CreatureAI::Talk(), and TYPEID_PLAYER.
Reset()
void boss_bronjahm::boss_bronjahmAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 82 of file boss_bronjahm.cpp.
         {
             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE);
             me->CastSpell(me, SPELL_SOULSTORM_CHANNEL_OOC, true);
             events.Reset();
             summons.DespawnAll();
             if (pInstance)
                 pInstance->SetData(DATA_BRONJAHM, NOT_STARTED);
         }
References Unit::CastSpell(), DATA_BRONJAHM, SummonList::DespawnAll(), ScriptedAI::me, NOT_STARTED, pInstance, Object::RemoveFlag(), ZoneScript::SetData(), SPELL_SOULSTORM_CHANNEL_OOC, summons, UNIT_FIELD_FLAGS, and UNIT_FLAG_DISABLE_MOVE.
SpellHitTarget()
void boss_bronjahm::boss_bronjahmAI::SpellHitTarget (Unit * , const SpellInfo * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 121 of file boss_bronjahm.cpp.
         {
             if (spell->Id == SPELL_TELEPORT)
             {
                 me->CastSpell(me, SPELL_TELEPORT_VISUAL, true);
                 events.RescheduleEvent(EVENT_START_SOULSTORM, 1);
             }
         }
References Unit::CastSpell(), EVENT_START_SOULSTORM, SpellInfo::Id, ScriptedAI::me, SPELL_TELEPORT, and SPELL_TELEPORT_VISUAL.
UpdateAI()
void boss_bronjahm::boss_bronjahmAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 130 of file boss_bronjahm.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             if (me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE))
                 if (me->isAttackReady())
                     me->SetFacingToObject(me->GetVictim());
             switch(events.ExecuteEvent())
             {
                 case 0:
                     break;
                 case EVENT_SPELL_SHADOW_BOLT:
                     if (!me->IsWithinMeleeRange(me->GetVictim()))
                         me->CastSpell(me->GetVictim(), SPELL_SHADOW_BOLT, false);
                     events.RepeatEvent(2000);
                     break;
                 case EVENT_SPELL_FEAR:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 10.0f, true))
                         me->CastCustomSpell(SPELL_FEAR, SPELLVALUE_MAX_TARGETS, 1, target, false);
                     events.RepeatEvent(urand(8000, 12000));
                     break;
                 case EVENT_SPELL_MAGICS_BANE:
                     me->CastSpell(me->GetVictim(), SPELL_MAGICS_BANE, false);
                     events.RepeatEvent(urand(10000, 15000));
                     break;
                 case EVENT_SPELL_CORRUPT_SOUL:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 100.0f, true))
                     {
                         Talk(SAY_CORRUPT_SOUL);
                         me->CastSpell(target, SPELL_CORRUPT_SOUL, false);
                     }
                     events.RepeatEvent(urand(20000, 25000));
                     break;
                 case EVENT_START_SOULSTORM:
                     Talk(SAY_SOUL_STORM);
                     me->CastSpell(me, SPELL_SOULSTORM, false);
                     me->CastSpell(me, SPELL_TELEPORT_VISUAL, true);
                     me->CastSpell(me, SPELL_SOULSTORM_VISUAL, true);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References Unit::CastCustomSpell(), Unit::CastSpell(), diff(), UnitAI::DoMeleeAttackIfReady(), EVENT_SPELL_CORRUPT_SOUL, EVENT_SPELL_FEAR, EVENT_SPELL_MAGICS_BANE, EVENT_SPELL_SHADOW_BOLT, EVENT_START_SOULSTORM, Unit::GetVictim(), Object::HasFlag(), Unit::HasUnitState(), Unit::isAttackReady(), Unit::IsWithinMeleeRange(), ScriptedAI::me, SAY_CORRUPT_SOUL, SAY_SOUL_STORM, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Unit::SetFacingToObject(), SPELL_CORRUPT_SOUL, SPELL_FEAR, SPELL_MAGICS_BANE, SPELL_SHADOW_BOLT, SPELL_SOULSTORM, SPELL_SOULSTORM_VISUAL, SPELL_TELEPORT_VISUAL, SPELLVALUE_MAX_TARGETS, CreatureAI::Talk(), UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
events
EventMap boss_bronjahm::boss_bronjahmAI::events
Definition at line 74 of file boss_bronjahm.cpp.
pInstance
InstanceScript* boss_bronjahm::boss_bronjahmAI::pInstance
Definition at line 73 of file boss_bronjahm.cpp.
Referenced by boss_bronjahmAI(), EnterCombat(), JustDied(), and Reset().
summons
SummonList boss_bronjahm::boss_bronjahmAI::summons
Definition at line 75 of file boss_bronjahm.cpp.
Referenced by JustSummoned(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/FrozenHalls/ForgeOfSouls/boss_bronjahm.cpp