Azerotcore-wotlk: boss_pyroguard_emberseer::boss_pyroguard_emberseerAI Struct Reference
boss_pyroguard_emberseer::boss_pyroguard_emberseerAI Struct Reference
Public Member Functions
boss_pyroguard_emberseerAI (Creature *creature)
void Reset () override
void SetData (uint32, uint32 data) override
void EnterCombat (Unit *) override
void JustDied (Unit *) override
void SpellHit (Unit *, SpellInfo const *spell) override
void OpenDoors (bool Boss_Killed)
void UpdateRunes (GOState state)
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 76 of file boss_pyroguard_emberseer.cpp.
Constructor & Destructor Documentation
boss_pyroguard_emberseerAI()
boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::boss_pyroguard_emberseerAI (Creature * creature) inline
Definition at line 78 of file boss_pyroguard_emberseer.cpp.
 : BossAI(creature, DATA_PYROGAURD_EMBERSEER) { }
Member Function Documentation
EnterCombat()
void boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::EnterCombat (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 122 of file boss_pyroguard_emberseer.cpp.
         {
             // ### TODO Check combat timing ###
             events.ScheduleEvent(EVENT_FIRENOVA,    6000);
             events.ScheduleEvent(EVENT_FLAMEBUFFET, 3000);
             events.ScheduleEvent(EVENT_PYROBLAST,  14000);
         }
References EVENT_FIRENOVA, EVENT_FLAMEBUFFET, and EVENT_PYROBLAST.
JustDied()
void boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 130 of file boss_pyroguard_emberseer.cpp.
         {
             // Activate all the runes
             UpdateRunes(GO_STATE_READY);
             // Opens all 3 doors
             OpenDoors(true);
             // Complete encounter
             instance->SetBossState(DATA_PYROGAURD_EMBERSEER, DONE);
         }
References DATA_PYROGAURD_EMBERSEER, DONE, GO_STATE_READY, BossAI::instance, OpenDoors(), InstanceScript::SetBossState(), and UpdateRunes().
OpenDoors()
void boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::OpenDoors (bool Boss_Killed) inline
Definition at line 166 of file boss_pyroguard_emberseer.cpp.
         {
             // These two doors reopen on reset or boss kill
             if (GameObject* door1 = me->GetMap()->GetGameObject(instance->GetGuidData(GO_EMBERSEER_IN)))
                 door1->SetGoState(GO_STATE_ACTIVE);
             if (GameObject* door2 = me->GetMap()->GetGameObject(instance->GetGuidData(GO_DOORS)))
                 door2->SetGoState(GO_STATE_ACTIVE);
             // This door opens on boss kill
             if (Boss_Killed)
                 if (GameObject* door3 = me->GetMap()->GetGameObject(instance->GetGuidData(GO_EMBERSEER_OUT)))
                     door3->SetGoState(GO_STATE_ACTIVE);
         }
References Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), GO_DOORS, GO_EMBERSEER_IN, GO_EMBERSEER_OUT, GO_STATE_ACTIVE, BossAI::instance, and ScriptedAI::me.
Referenced by JustDied(), and Reset().
Reset()
void boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 80 of file boss_pyroguard_emberseer.cpp.
         {
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_NOT_SELECTABLE);
             events.Reset();
             // Apply auras on spawn and reset
             // DoCast(me, SPELL_FIRE_SHIELD_TRIGGER); // Need to find this in old DBC if possible
             me->RemoveAura(SPELL_EMBERSEER_FULL_STRENGTH);
             me->RemoveAura(SPELL_EMBERSEER_GROWING);
             me->RemoveAura(SPELL_EMBERSEER_GROWING_TRIGGER);
             events.ScheduleEvent(EVENT_RESPAWN, 5000);
             // Hack for missing trigger spell
             events.ScheduleEvent(EVENT_FIRE_SHIELD, 3000);
             // Open doors on reset
             if (instance->GetBossState(DATA_PYROGAURD_EMBERSEER) == IN_PROGRESS)
                 OpenDoors(false); // Opens 2 entrance doors
         }
References DATA_PYROGAURD_EMBERSEER, EVENT_FIRE_SHIELD, EVENT_RESPAWN, InstanceScript::GetBossState(), IN_PROGRESS, BossAI::instance, ScriptedAI::me, OpenDoors(), Unit::RemoveAura(), Object::SetFlag(), SPELL_EMBERSEER_FULL_STRENGTH, SPELL_EMBERSEER_GROWING, SPELL_EMBERSEER_GROWING_TRIGGER, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC, and UNIT_FLAG_NOT_SELECTABLE.
Referenced by SetData().
SetData()
void boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::SetData (uint32 , uint32 data) inline override virtual
Reimplemented from UnitAI.
Definition at line 98 of file boss_pyroguard_emberseer.cpp.
         {
             switch (data)
             {
                 case 1:
                     events.ScheduleEvent(EVENT_PLAYER_CHECK, 5000);
                     break;
                 case 2:
                     // Close these two doors on Blackhand Incarcerators aggro
                     if (GameObject* door1 = me->GetMap()->GetGameObject(instance->GetGuidData(GO_EMBERSEER_IN)))
                         if (door1->GetGoState() == GO_STATE_ACTIVE)
                             door1->SetGoState(GO_STATE_READY);
                     if (GameObject* door2 = me->GetMap()->GetGameObject(instance->GetGuidData(GO_DOORS)))
                         if (door2->GetGoState() == GO_STATE_ACTIVE)
                             door2->SetGoState(GO_STATE_READY);
                     break;
                 case 3:
                     Reset();
                     break;
                 default:
                     break;
             }
         }
References EVENT_PLAYER_CHECK, Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), GO_DOORS, GO_EMBERSEER_IN, GO_STATE_ACTIVE, GO_STATE_READY, BossAI::instance, ScriptedAI::me, and Reset().
SpellHit()
void boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::SpellHit (Unit * , SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 140 of file boss_pyroguard_emberseer.cpp.
         {
             if (spell->Id == SPELL_ENCAGE_EMBERSEER)
             {
                 if (!me->GetAuraCount(SPELL_ENCAGED_EMBERSEER))
                     me->CastSpell(me, SPELL_ENCAGED_EMBERSEER);
             }
             if (spell->Id == SPELL_EMBERSEER_GROWING_TRIGGER)
             {
                 if (me->GetAuraCount(SPELL_EMBERSEER_GROWING_TRIGGER) == 10)
                     Talk(EMOTE_TEN_STACK);
                 if (me->GetAuraCount(SPELL_EMBERSEER_GROWING_TRIGGER) == 20)
                 {
                     me->RemoveAura(SPELL_ENCAGED_EMBERSEER);
                     me->RemoveAura(SPELL_FREEZE_ANIM);
                     me->CastSpell(me, SPELL_EMBERSEER_FULL_STRENGTH);
                     Talk(EMOTE_FREE_OF_BONDS);
                     Talk(YELL_FREE_OF_BONDS);
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_NOT_SELECTABLE);
                     events.ScheduleEvent(EVENT_ENTER_COMBAT, 2000);
                 }
             }
         }
References Unit::CastSpell(), EMOTE_FREE_OF_BONDS, EMOTE_TEN_STACK, EVENT_ENTER_COMBAT, Unit::GetAuraCount(), SpellInfo::Id, ScriptedAI::me, Unit::RemoveAura(), Object::RemoveFlag(), SPELL_EMBERSEER_FULL_STRENGTH, SPELL_EMBERSEER_GROWING_TRIGGER, SPELL_ENCAGE_EMBERSEER, SPELL_ENCAGED_EMBERSEER, SPELL_FREEZE_ANIM, CreatureAI::Talk(), UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC, UNIT_FLAG_NOT_SELECTABLE, and YELL_FREE_OF_BONDS.
UpdateAI()
void boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 199 of file boss_pyroguard_emberseer.cpp.
         {
             if (!UpdateVictim())
             {
                 events.Update(diff);
                 while (uint32 eventId = events.ExecuteEvent())
                 {
                     switch (eventId)
                     {
                         case EVENT_RESPAWN:
{
                                 // Respawn all Blackhand Incarcerators
                                 std::list<Creature*> creatureList;
                                 GetCreatureListWithEntryInGrid(creatureList, me, NPC_BLACKHAND_INCARCERATOR, 35.0f);
                                 for (std::list<Creature*>::iterator itr = creatureList.begin(); itr != creatureList.end(); ++itr)
                                     if (Creature* creature = *itr)
{
                                         if (!creature->IsAlive())
                                             creature->Respawn();
                                         creature->AI()->SetData(1, 2);
                                     }
                                 me->AddAura(SPELL_ENCAGED_EMBERSEER, me);
                                 instance->SetBossState(DATA_PYROGAURD_EMBERSEER, NOT_STARTED);
                                 break;
                             }
                         case EVENT_PRE_FIGHT_1:
{
                                 // Set data on all Blackhand Incarcerators
                                 std::list<Creature*> creatureList;
                                 GetCreatureListWithEntryInGrid(creatureList, me, NPC_BLACKHAND_INCARCERATOR, 35.0f);
                                 for (std::list<Creature*>::iterator itr = creatureList.begin(); itr != creatureList.end(); ++itr)
{
                                     if (Creature* creature = *itr)
                                         creature->AI()->SetData(1, 1);
                                 }
                                 events.ScheduleEvent(EVENT_PRE_FIGHT_2, 32000);
                                 break;
                             }
                         case EVENT_PRE_FIGHT_2:
                             me->CastSpell(me, SPELL_FREEZE_ANIM);
                             me->CastSpell(me, SPELL_EMBERSEER_GROWING);
                             Talk(EMOTE_ONE_STACK);
                             break;
                         case EVENT_FIRE_SHIELD:
                             // #### Spell isn't doing any damage ??? ####
                             DoCast(me, SPELL_FIRE_SHIELD);
                             events.ScheduleEvent(EVENT_FIRE_SHIELD, 3000);
                             break;
                         case EVENT_PLAYER_CHECK:
{
                                 // Check to see if all players in instance have aura SPELL_EMBERSEER_START before starting event
                                 bool _hasAura = false;
                                 Map::PlayerList const& players = me->GetMap()->GetPlayers();
                                 for (Map::PlayerList::const_iterator itr = players.begin(); itr != players.end(); ++itr)
                                     if (Player* player = itr->GetSource()->ToPlayer())
                                         if (player->HasAura(SPELL_EMBERSEER_OBJECT_VISUAL))
                                             _hasAura = true;
                                 if (_hasAura)
{
                                     events.ScheduleEvent(EVENT_PRE_FIGHT_1, 1000);
                                     instance->SetBossState(DATA_PYROGAURD_EMBERSEER, IN_PROGRESS);
                                 }
                                 break;
                             }
                         case EVENT_ENTER_COMBAT:
                             DoZoneInCombat();
                             break;
                         default:
                             break;
                     }
                 }
                 return;
             }
             events.Update(diff);
             while (uint32 eventId = events.ExecuteEvent())
             {
                 switch (eventId)
                 {
                     case EVENT_FIRE_SHIELD:
                         DoCast(me, SPELL_FIRE_SHIELD);
                         events.ScheduleEvent(EVENT_FIRE_SHIELD, 3000);
                         break;
                     case EVENT_FIRENOVA:
                         DoCast(me, SPELL_FIRENOVA);
                         events.ScheduleEvent(EVENT_FIRENOVA, 6000);
                         break;
                     case EVENT_FLAMEBUFFET:
                         DoCast(me, SPELL_FLAMEBUFFET);
                         events.ScheduleEvent(EVENT_FLAMEBUFFET, 14000);
                         break;
                     case EVENT_PYROBLAST:
                         DoCastRandomTarget(SPELL_PYROBLAST, 0, 100.0f);
                         events.ScheduleEvent(EVENT_PYROBLAST, 15000);
                         break;
                     default:
                         break;
                 }
             }
             DoMeleeAttackIfReady();
         }
References Unit::AddAura(), MapRefMgr::begin(), Unit::CastSpell(), DATA_PYROGAURD_EMBERSEER, UnitAI::DoCast(), UnitAI::DoCastRandomTarget(), UnitAI::DoMeleeAttackIfReady(), CreatureAI::DoZoneInCombat(), EMOTE_ONE_STACK, MapRefMgr::end(), EVENT_ENTER_COMBAT, EVENT_FIRE_SHIELD, EVENT_FIRENOVA, EVENT_FLAMEBUFFET, EVENT_PLAYER_CHECK, EVENT_PRE_FIGHT_1, EVENT_PRE_FIGHT_2, EVENT_PYROBLAST, EVENT_RESPAWN, GetCreatureListWithEntryInGrid(), WorldObject::GetMap(), Map::GetPlayers(), IN_PROGRESS, BossAI::instance, ScriptedAI::me, NOT_STARTED, NPC_BLACKHAND_INCARCERATOR, InstanceScript::SetBossState(), SPELL_EMBERSEER_GROWING, SPELL_EMBERSEER_OBJECT_VISUAL, SPELL_ENCAGED_EMBERSEER, SPELL_FIRE_SHIELD, SPELL_FIRENOVA, SPELL_FLAMEBUFFET, SPELL_FREEZE_ANIM, SPELL_PYROBLAST, CreatureAI::Talk(), Object::ToPlayer(), and CreatureAI::UpdateVictim().
UpdateRunes()
void boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::UpdateRunes (GOState state) inline
Definition at line 180 of file boss_pyroguard_emberseer.cpp.
         {
             // update all runes
             if (GameObject* rune1 = me->GetMap()->GetGameObject(instance->GetGuidData(GO_EMBERSEER_RUNE_1)))
                 rune1->SetGoState(state);
             if (GameObject* rune2 = me->GetMap()->GetGameObject(instance->GetGuidData(GO_EMBERSEER_RUNE_2)))
                 rune2->SetGoState(state);
             if (GameObject* rune3 = me->GetMap()->GetGameObject(instance->GetGuidData(GO_EMBERSEER_RUNE_3)))
                 rune3->SetGoState(state);
             if (GameObject* rune4 = me->GetMap()->GetGameObject(instance->GetGuidData(GO_EMBERSEER_RUNE_4)))
                 rune4->SetGoState(state);
             if (GameObject* rune5 = me->GetMap()->GetGameObject(instance->GetGuidData(GO_EMBERSEER_RUNE_5)))
                 rune5->SetGoState(state);
             if (GameObject* rune6 = me->GetMap()->GetGameObject(instance->GetGuidData(GO_EMBERSEER_RUNE_6)))
                 rune6->SetGoState(state);
             if (GameObject* rune7 = me->GetMap()->GetGameObject(instance->GetGuidData(GO_EMBERSEER_RUNE_7)))
                 rune7->SetGoState(state);
         }
References Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), GO_EMBERSEER_RUNE_1, GO_EMBERSEER_RUNE_2, GO_EMBERSEER_RUNE_3, GO_EMBERSEER_RUNE_4, GO_EMBERSEER_RUNE_5, GO_EMBERSEER_RUNE_6, GO_EMBERSEER_RUNE_7, BossAI::instance, and ScriptedAI::me.
Referenced by JustDied().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/boss_pyroguard_emberseer.cpp