Azerotcore-wotlk: MapObject Namespace Reference
MapObject Namespace Reference
Functions
void Extract (ADT::MODF const &mapObjDef, char const *WmoInstName, uint32 mapID, uint32 tileX, uint32 tileY, FILE *pDirfile)
Function Documentation
Extract()
void MapObject::Extract (ADT::MODF const & mapObjDef, char const * WmoInstName, uint32 mapID, uint32 tileX, uint32 tileY, FILE * pDirfile)
Definition at line 510 of file wmo.cpp.
 {
     // destructible wmo, do not dump. we can handle the vmap for these
     // in dynamic tree (gameobject vmaps)
     if ((mapObjDef.Flags & 0x1) != 0)
         return;
     //-----------add_in _dir_file----------------
     char tempname[1036];
     sprintf(tempname, "%s/%s", szWorkDirWmo, WmoInstName);
     FILE* input;
     input = fopen(tempname, "r+b");
     if (!input)
     {
         printf("WMOInstance::WMOInstance: couldn't open %s\n", tempname);
         return;
     }
     fseek(input, 8, SEEK_SET); // get the correct no of vertices
     int nVertices;
     int count = fread(&nVertices, sizeof (int), 1, input);
     fclose(input);
     if (count != 1 || nVertices == 0)
         return;
     Vec3D position = mapObjDef.Position;
     float x, z;
     x = position.x;
     z = position.z;
     if (x == 0 && z == 0)
     {
         position.x = 533.33333f * 32;
         position.z = 533.33333f * 32;
     }
     position = fixCoords(position);
     AaBox3D bounds;
     bounds.min = fixCoords(mapObjDef.Bounds.min);
     bounds.max = fixCoords(mapObjDef.Bounds.max);
     float scale = 1.0f;
     uint32 uniqueId = GenerateUniqueObjectId(mapObjDef.UniqueId, 0);
     uint32 flags = MOD_HAS_BOUND;
     if (tileX == 65 && tileY == 65) flags |= MOD_WORLDSPAWN;
     //write mapID, tileX, tileY, Flags, NameSet, UniqueId, Pos, Rot, Scale, Bound_lo, Bound_hi, name
     fwrite(&mapID, sizeof(uint32), 1, pDirfile);
     fwrite(&tileX, sizeof(uint32), 1, pDirfile);
     fwrite(&tileY, sizeof(uint32), 1, pDirfile);
     fwrite(&flags, sizeof(uint32), 1, pDirfile);
     fwrite(&mapObjDef.NameSet, sizeof(uint16), 1, pDirfile);
     fwrite(&uniqueId, sizeof(uint32), 1, pDirfile);
     fwrite(&position, sizeof(Vec3D), 1, pDirfile);
     fwrite(&mapObjDef.Rotation, sizeof(Vec3D), 1, pDirfile);
     fwrite(&scale, sizeof(float), 1, pDirfile);
     fwrite(&bounds, sizeof(AaBox3D), 1, pDirfile);
     uint32 nlen = strlen(WmoInstName);
     fwrite(&nlen, sizeof(uint32), 1, pDirfile);
     fwrite(WmoInstName, sizeof(char), nlen, pDirfile);
 }
References ADT::MODF::Bounds, fixCoords(), ADT::MODF::Flags, GenerateUniqueObjectId(), AaBox3D::max, AaBox3D::min, MOD_HAS_BOUND, MOD_WORLDSPAWN, ADT::MODF::NameSet, ADT::MODF::Position, ADT::MODF::Rotation, szWorkDirWmo, ADT::MODF::UniqueId, Vec3D::x, and Vec3D::z.
Referenced by ADTFile::init(), and WDTFile::init().