Azerotcore-wotlk: AuthSocketMgr Class Reference
AuthSocketMgr Class Reference
#include <AuthSocketMgr.h>
Public Member Functions
bool StartNetwork (Acore::Asio::IoContext &ioContext, std::string const &bindIp, uint16 port, int threadCount=1) override
Public Member Functions inherited from SocketMgr< AuthSession >
virtual ~SocketMgr ()
virtual void StopNetwork ()
void Wait ()
virtual void OnSocketOpen (tcp::socket &&sock, uint32 threadIndex)
int32 GetNetworkThreadCount () const
uint32 SelectThreadWithMinConnections () const
std::pair< tcp::socket *, uint32 > GetSocketForAccept ()
Static Public Member Functions
static AuthSocketMgr & Instance ()
Protected Member Functions
NetworkThread< AuthSession > * CreateThreads () const override
Protected Member Functions inherited from SocketMgr< AuthSession >
SocketMgr ()
Static Protected Member Functions
static void OnSocketAccept (tcp::socket &&sock, uint32 threadIndex)
Private Types
typedef SocketMgr< AuthSession > BaseSocketMgr
Additional Inherited Members
Protected Attributes inherited from SocketMgr< AuthSession >
AsyncAcceptor * _acceptor
NetworkThread< AuthSession > * _threads
int32 _threadCount
Detailed Description
Definition at line 24 of file AuthSocketMgr.h.
Member Typedef Documentation
BaseSocketMgr
typedef SocketMgr<AuthSession> AuthSocketMgr::BaseSocketMgr private
Definition at line 26 of file AuthSocketMgr.h.
Member Function Documentation
CreateThreads()
NetworkThread<AuthSession>* AuthSocketMgr::CreateThreads () const inline override protected virtual
Implements SocketMgr< AuthSession >.
Definition at line 45 of file AuthSocketMgr.h.
     {
         return new NetworkThread<AuthSession>[1];
     }
Instance()
static AuthSocketMgr& AuthSocketMgr::Instance () inline static
Definition at line 29 of file AuthSocketMgr.h.
     {
         static AuthSocketMgr instance;
         return instance;
     }
Referenced by OnSocketAccept().
OnSocketAccept()
static void AuthSocketMgr::OnSocketAccept (tcp::socket && sock, uint32 threadIndex) inline static protected
Definition at line 50 of file AuthSocketMgr.h.
     {
         Instance().OnSocketOpen(std::forward<tcp::socket>(sock), threadIndex);
     }
References Instance(), and SocketMgr< SocketType >::OnSocketOpen().
Referenced by StartNetwork().
StartNetwork()
bool AuthSocketMgr::StartNetwork (Acore::Asio::IoContext & ioContext, std::string const & bindIp, uint16 port, int threadCount = 1) inline override virtual
Reimplemented from SocketMgr< AuthSession >.
Definition at line 35 of file AuthSocketMgr.h.
     {
         if (!BaseSocketMgr::StartNetwork(ioContext, bindIp, port, threadCount))
             return false;
         _acceptor->AsyncAcceptWithCallback<&AuthSocketMgr::OnSocketAccept>();
         return true;
     }
References SocketMgr< AuthSession >::_acceptor, AsyncAcceptor::AsyncAcceptWithCallback(), OnSocketAccept(), and SocketMgr< AuthSession >::StartNetwork().
The documentation for this class was generated from the following file:
src/server/authserver/Server/AuthSocketMgr.h