Azerotcore-wotlk: specs_checker< Handler > Class Template Reference
specs_checker< Handler > Class Template Reference
#include <core.h>
Public Member Functions
FMT_CONSTEXPR specs_checker (const Handler &handler, detail::type arg_type)
FMT_CONSTEXPR void on_align (align_t align)
FMT_CONSTEXPR void on_sign (sign_t s)
FMT_CONSTEXPR void on_hash ()
FMT_CONSTEXPR void on_localized ()
FMT_CONSTEXPR void on_zero ()
FMT_CONSTEXPR void end_precision ()
Private Member Functions
FMT_CONSTEXPR void require_numeric_argument ()
Private Attributes
detail::type arg_type_
Detailed Description
template<typename Handler>
class specs_checker< Handler >
Definition at line 2592 of file core.h.
Constructor & Destructor Documentation
specs_checker()
template<typename Handler > FMT_CONSTEXPR specs_checker< Handler >::specs_checker (const Handler & handler, detail::type arg_type) inline
Definition at line 2602 of file core.h.
       : Handler(handler), arg_type_(arg_type) {}
Member Function Documentation
end_precision()
template<typename Handler > FMT_CONSTEXPR void specs_checker< Handler >::end_precision () inline
Definition at line 2634 of file core.h.
{
     if (is_integral_type(arg_type_) || arg_type_ == type::pointer_type)
       this->on_error("precision not allowed for this argument type");
   }
References is_integral_type(), and pointer_type.
on_align()
template<typename Handler > FMT_CONSTEXPR void specs_checker< Handler >::on_align (align_t align) inline
Definition at line 2605 of file core.h.
{
     if (align == align::numeric) require_numeric_argument();
     Handler::on_align(align);
   }
References align::numeric.
on_hash()
template<typename Handler > FMT_CONSTEXPR void specs_checker< Handler >::on_hash () inline
Definition at line 2619 of file core.h.
{
     require_numeric_argument();
     Handler::on_hash();
   }
on_localized()
template<typename Handler > FMT_CONSTEXPR void specs_checker< Handler >::on_localized () inline
Definition at line 2624 of file core.h.
{
     require_numeric_argument();
     Handler::on_localized();
   }
on_sign()
template<typename Handler > FMT_CONSTEXPR void specs_checker< Handler >::on_sign (sign_t s) inline
Definition at line 2610 of file core.h.
{
     require_numeric_argument();
     if (is_integral_type(arg_type_) && arg_type_ != type::int_type &&
         arg_type_ != type::long_long_type && arg_type_ != type::char_type) {
       this->on_error("format specifier requires signed argument");
     }
     Handler::on_sign(s);
   }
References char_type, int_type, is_integral_type(), and long_long_type.
on_zero()
template<typename Handler > FMT_CONSTEXPR void specs_checker< Handler >::on_zero () inline
Definition at line 2629 of file core.h.
{
     require_numeric_argument();
     Handler::on_zero();
   }
require_numeric_argument()
template<typename Handler > FMT_CONSTEXPR void specs_checker< Handler >::require_numeric_argument () inline private
Definition at line 2596 of file core.h.
{
     if (!is_arithmetic_type(arg_type_))
       this->on_error("format specifier requires numeric argument");
   }
References is_arithmetic_type().
Member Data Documentation
arg_type_
template<typename Handler > detail::type specs_checker< Handler >::arg_type_ private
Definition at line 2594 of file core.h.
The documentation for this class was generated from the following file:
deps/fmt/include/fmt/core.h