Azerotcore-wotlk: CharacterDatabaseCleaner Namespace Reference
CharacterDatabaseCleaner Namespace Reference
Enumerations
enum CleaningFlags {
CLEANING_FLAG_ACHIEVEMENT_PROGRESS = 0x1 , CLEANING_FLAG_SKILLS = 0x2 , CLEANING_FLAG_SPELLS = 0x4 , CLEANING_FLAG_TALENTS = 0x8 ,
CLEANING_FLAG_QUESTSTATUS = 0x10
}
Functions
void CleanDatabase ()
void CheckUnique (const char *column, const char *table, bool(*check)(uint32))
bool AchievementProgressCheck (uint32 criteria)
bool SkillCheck (uint32 skill)
bool SpellCheck (uint32 spell_id)
bool TalentCheck (uint32 talent_id)
void CleanCharacterAchievementProgress ()
void CleanCharacterSkills ()
void CleanCharacterSpell ()
void CleanCharacterTalent ()
void CleanCharacterQuestStatus ()
Enumeration Type Documentation
CleaningFlags
enum CharacterDatabaseCleaner::CleaningFlags
Enumerator
CLEANING_FLAG_ACHIEVEMENT_PROGRESS
CLEANING_FLAG_SKILLS
CLEANING_FLAG_SPELLS
CLEANING_FLAG_TALENTS
CLEANING_FLAG_QUESTSTATUS
Definition at line 25 of file CharacterDatabaseCleaner.h.
     {
         CLEANING_FLAG_ACHIEVEMENT_PROGRESS  = 0x1,
         CLEANING_FLAG_SKILLS                = 0x2,
         CLEANING_FLAG_SPELLS                = 0x4,
         CLEANING_FLAG_TALENTS               = 0x8,
         CLEANING_FLAG_QUESTSTATUS           = 0x10
     };
Function Documentation
AchievementProgressCheck()
bool CharacterDatabaseCleaner::AchievementProgressCheck (uint32 criteria)
Definition at line 108 of file CharacterDatabaseCleaner.cpp.
 {
     return sAchievementCriteriaStore.LookupEntry(criteria);
 }
References sAchievementCriteriaStore.
Referenced by CleanCharacterAchievementProgress().
CheckUnique()
void CharacterDatabaseCleaner::CheckUnique (const char * column, const char * table, bool(*)(uint32) check)
Definition at line 70 of file CharacterDatabaseCleaner.cpp.
 {
     QueryResult result = CharacterDatabase.PQuery("SELECT DISTINCT %s FROM %s", column, table);
     if (!result)
     {
         LOG_INFO("sql.sql", "Table %s is empty.", table);
         return;
     }
     bool found = false;
     std::ostringstream ss;
     do
     {
         Field* fields = result->Fetch();
         uint32 id = fields[0].GetUInt32();
         if (!check(id))
         {
             if (!found)
             {
                 ss << "DELETE FROM " << table << " WHERE " << column << " IN (";
                 found = true;
             }
             else
                 ss << ',';
             ss << id;
         }
     } while (result->NextRow());
     if (found)
     {
         ss << ')';
         CharacterDatabase.Execute(ss.str().c_str());
     }
 }
References CharacterDatabase, Field::GetUInt32(), and LOG_INFO.
Referenced by CleanCharacterAchievementProgress(), CleanCharacterSkills(), CleanCharacterSpell(), and CleanCharacterTalent().
CleanCharacterAchievementProgress()
void CharacterDatabaseCleaner::CleanCharacterAchievementProgress ()
Definition at line 113 of file CharacterDatabaseCleaner.cpp.
 {
     CheckUnique("criteria", "character_achievement_progress", &AchievementProgressCheck);
 }
References AchievementProgressCheck(), and CheckUnique().
Referenced by CleanDatabase().
CleanCharacterQuestStatus()
void CharacterDatabaseCleaner::CleanCharacterQuestStatus ()
Definition at line 153 of file CharacterDatabaseCleaner.cpp.
 {
     CharacterDatabase.DirectExecute("DELETE FROM character_queststatus WHERE status = 0");
 }
References CharacterDatabase.
Referenced by CleanDatabase().
CleanCharacterSkills()
void CharacterDatabaseCleaner::CleanCharacterSkills ()
Definition at line 123 of file CharacterDatabaseCleaner.cpp.
 {
     CheckUnique("skill", "character_skills", &SkillCheck);
 }
References CheckUnique(), and SkillCheck().
Referenced by CleanDatabase().
CleanCharacterSpell()
void CharacterDatabaseCleaner::CleanCharacterSpell ()
Definition at line 133 of file CharacterDatabaseCleaner.cpp.
 {
     CheckUnique("spell", "character_spell", &SpellCheck);
 }
References CheckUnique(), and SpellCheck().
Referenced by CleanDatabase().
CleanCharacterTalent()
void CharacterDatabaseCleaner::CleanCharacterTalent ()
Definition at line 147 of file CharacterDatabaseCleaner.cpp.
 {
     CharacterDatabase.DirectPExecute("DELETE FROM character_talent WHERE specMask >= %u", 1 << MAX_TALENT_SPECS);
     CheckUnique("spell", "character_talent", &TalentCheck);
 }
References CharacterDatabase, CheckUnique(), MAX_TALENT_SPECS, and TalentCheck().
Referenced by CleanDatabase().
CleanDatabase()
void CharacterDatabaseCleaner::CleanDatabase ()
Definition at line 26 of file CharacterDatabaseCleaner.cpp.
 {
     // config to disable
     if (!sWorld->getBoolConfig(CONFIG_CLEAN_CHARACTER_DB))
         return;
     LOG_INFO("misc", "Cleaning character database...");
     uint32 oldMSTime = getMSTime();
     // check flags which clean ups are necessary
     QueryResult result = CharacterDatabase.PQuery("SELECT value FROM worldstates WHERE entry = %d", WS_CLEANING_FLAGS);
     if (!result)
         return;
     uint32 flags = (*result)[0].GetUInt32();
     // clean up
     if (flags & CLEANING_FLAG_ACHIEVEMENT_PROGRESS)
         CleanCharacterAchievementProgress();
     if (flags & CLEANING_FLAG_SKILLS)
         CleanCharacterSkills();
     if (flags & CLEANING_FLAG_SPELLS)
         CleanCharacterSpell();
     if (flags & CLEANING_FLAG_TALENTS)
         CleanCharacterTalent();
     if (flags & CLEANING_FLAG_QUESTSTATUS)
         CleanCharacterQuestStatus();
     // NOTE: In order to have persistentFlags be set in worldstates for the next cleanup,
     // you need to define them at least once in worldstates.
     flags &= sWorld->getIntConfig(CONFIG_PERSISTENT_CHARACTER_CLEAN_FLAGS);
     CharacterDatabase.DirectPExecute("UPDATE worldstates SET value = %u WHERE entry = %d", flags, WS_CLEANING_FLAGS);
     sWorld->SetCleaningFlags(flags);
     LOG_INFO("server.loading", ">> Cleaned character database in %u ms", GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
 }
References CharacterDatabase, CleanCharacterAchievementProgress(), CleanCharacterQuestStatus(), CleanCharacterSkills(), CleanCharacterSpell(), CleanCharacterTalent(), CLEANING_FLAG_ACHIEVEMENT_PROGRESS, CLEANING_FLAG_QUESTSTATUS, CLEANING_FLAG_SKILLS, CLEANING_FLAG_SPELLS, CLEANING_FLAG_TALENTS, CONFIG_CLEAN_CHARACTER_DB, CONFIG_PERSISTENT_CHARACTER_CLEAN_FLAGS, getMSTime(), GetMSTimeDiffToNow(), LOG_INFO, sWorld, and WS_CLEANING_FLAGS.
Referenced by World::SetInitialWorldSettings().
SkillCheck()
bool CharacterDatabaseCleaner::SkillCheck (uint32 skill)
Definition at line 118 of file CharacterDatabaseCleaner.cpp.
 {
     return sSkillLineStore.LookupEntry(skill);
 }
References sSkillLineStore.
Referenced by CleanCharacterSkills().
SpellCheck()
bool CharacterDatabaseCleaner::SpellCheck (uint32 spell_id)
Definition at line 128 of file CharacterDatabaseCleaner.cpp.
 {
     return sSpellMgr->GetSpellInfo(spell_id) && !GetTalentSpellPos(spell_id);
 }
References GetTalentSpellPos(), and sSpellMgr.
Referenced by CleanCharacterSpell().
TalentCheck()
bool CharacterDatabaseCleaner::TalentCheck (uint32 talent_id)
Definition at line 138 of file CharacterDatabaseCleaner.cpp.
 {
     TalentEntry const* talentInfo = sTalentStore.LookupEntry(talent_id);
     if (!talentInfo)
         return false;
     return sTalentTabStore.LookupEntry(talentInfo->TalentTab);
 }
References sTalentStore, sTalentTabStore, and TalentEntry::TalentTab.
Referenced by CleanCharacterTalent().