Azerotcore-wotlk: npc_oculus_drake::npc_oculus_drakeAI Struct Reference
npc_oculus_drake::npc_oculus_drakeAI Struct Reference
Public Member Functions
npc_oculus_drakeAI (Creature *creature)
void IsSummonedBy (Unit *summoner) override
void MovementInform (uint32 type, uint32 id) override
void PassengerBoarded (Unit *passenger, int8, bool add) override
== Fields =======================================
void SpellHitTarget (Unit *target, SpellInfo const *spell) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from VehicleAI
VehicleAI (Creature *creature)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void OnCharmed (bool apply) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * m_pInstance
bool JustSummoned
uint16 despawnTimer
Additional Inherited Members
Static Public Member Functions inherited from VehicleAI
static int Permissible (Creature const *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 343 of file oculus.cpp.
Constructor & Destructor Documentation
npc_oculus_drakeAI()
npc_oculus_drake::npc_oculus_drakeAI::npc_oculus_drakeAI (Creature * creature) inline
Definition at line 345 of file oculus.cpp.
                                                : VehicleAI(creature)
         {
             m_pInstance = me->GetInstanceScript();
             JustSummoned = true;
         }
References WorldObject::GetInstanceScript(), JustSummoned, m_pInstance, and CreatureAI::me.
Member Function Documentation
IsSummonedBy()
void npc_oculus_drake::npc_oculus_drakeAI::IsSummonedBy (Unit * summoner) inline override virtual
Reimplemented from CreatureAI.
Definition at line 355 of file oculus.cpp.
         {
             if (m_pInstance->GetBossState(DATA_EREGOS) == IN_PROGRESS)
                 if (Creature* eregos = me->FindNearestCreature(NPC_EREGOS, 450.0f, true))
                     eregos->DespawnOrUnsummon(); // On retail this kills abusive call of drake during engaged Eregos
             me->SetFacingToObject(summoner);
             switch (me->GetEntry())
             {
                 case NPC_RUBY_DRAKE:
                     me->CastSpell(summoner, SPELL_RIDE_RUBY_DRAKE_QUE);
                     break;
                 case NPC_EMERALD_DRAKE:
                     me->CastSpell(summoner, SPELL_RIDE_EMERALD_DRAKE_QUE);
                     break;
                 case NPC_AMBER_DRAKE:
                     me->CastSpell(summoner, SPELL_RIDE_AMBER_DRAKE_QUE);
                     break;
                 default:
                     return;
             }
             Position pos = summoner->GetPosition();
             me->GetMotionMaster()->MovePoint(POINT_LAND, pos);
         }
References Unit::CastSpell(), DATA_EREGOS, WorldObject::FindNearestCreature(), InstanceScript::GetBossState(), Object::GetEntry(), Unit::GetMotionMaster(), Position::GetPosition(), IN_PROGRESS, m_pInstance, CreatureAI::me, MotionMaster::MovePoint(), NPC_AMBER_DRAKE, NPC_EMERALD_DRAKE, NPC_EREGOS, NPC_RUBY_DRAKE, POINT_LAND, pos(), Unit::SetFacingToObject(), SPELL_RIDE_AMBER_DRAKE_QUE, SPELL_RIDE_EMERALD_DRAKE_QUE, and SPELL_RIDE_RUBY_DRAKE_QUE.
MovementInform()
void npc_oculus_drake::npc_oculus_drakeAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from CreatureAI.
Definition at line 382 of file oculus.cpp.
         {
             if (type == POINT_MOTION_TYPE && id == POINT_LAND)
                 me->SetDisableGravity(false); // Needed this for proper animation after spawn, the summon in air fall to ground bug leave no other option for now, if this isn't used the drake will only walk on move.
         }
References CreatureAI::me, POINT_LAND, POINT_MOTION_TYPE, and Creature::SetDisableGravity().
PassengerBoarded()
void npc_oculus_drake::npc_oculus_drakeAI::PassengerBoarded (Unit * , int8 , bool) inline override virtual
== Fields =======================================
Reimplemented from CreatureAI.
Definition at line 388 of file oculus.cpp.
         {
             if (passenger->GetTypeId() != TYPEID_PLAYER)
                 return;
             if (add)
             {
                 despawnTimer = 0;
             }
             else
             {
                 me->DespawnOrUnsummon(2050);
                 me->SetOrientation(2.5f);
                 me->SetSpeedRate(MOVE_FLIGHT, 1.0f);
                 Position pos = me->GetPosition();
                 Position offset = { 10.0f, 10.0f, 12.0f, 0.0f };
                 pos.RelocateOffset(offset);
                 me->SetDisableGravity(true);
                 me->GetMotionMaster()->MovePoint(POINT_TAKE_OFF, pos);
             }
         }
References Creature::DespawnOrUnsummon(), despawnTimer, Unit::GetMotionMaster(), Position::GetPosition(), Object::GetTypeId(), CreatureAI::me, MOVE_FLIGHT, MotionMaster::MovePoint(), POINT_TAKE_OFF, pos(), Creature::SetDisableGravity(), Position::SetOrientation(), Unit::SetSpeedRate(), and TYPEID_PLAYER.
SpellHitTarget()
void npc_oculus_drake::npc_oculus_drakeAI::SpellHitTarget (Unit * target, SpellInfo const * spell) inline override virtual
Reimplemented from CreatureAI.
Definition at line 410 of file oculus.cpp.
         {
             for( uint8 i = 0; i < 8; ++i )
                 if( me->m_spells[i] == spell->Id )
                 {
                     if( target && target->IsAlive() && !target->CanFly() && target->IsHostileTo(me) && !spell->IsTargetingArea())
                     {
                         if( Unit* charmer = me->GetCharmer() )
                             Unit::Kill(charmer, charmer, false);
                     }
                     break;
                 }
         }
References Unit::CanFly(), Unit::GetCharmer(), SpellInfo::Id, Unit::IsAlive(), Unit::IsHostileTo(), SpellInfo::IsTargetingArea(), Unit::Kill(), Creature::m_spells, and CreatureAI::me.
UpdateAI()
void npc_oculus_drake::npc_oculus_drakeAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from VehicleAI.
Definition at line 424 of file oculus.cpp.
         {
             if (JustSummoned)
             {
                 despawnTimer = 1;
                 JustSummoned = false;
                 if (m_pInstance)
                 {
                     if (!m_pInstance->IsEncounterInProgress() || m_pInstance->GetData(DATA_EREGOS) == IN_PROGRESS)
                     {
                         if (me->GetVehicleKit() && me->IsSummon())
                             if (!me->GetVehicleKit()->GetPassenger(0))
{
                                 if (m_pInstance->GetData(DATA_UROM) == DONE)
{
                                     switch (me->GetEntry())
{
                                         case 27692:
                                             me->m_spells[5] = 50344;
                                             break;
                                         case 27755:
                                             me->m_spells[5] = 49592;
                                             break;
                                         case 27756:
                                             me->m_spells[5] = 50253;
                                             break;
                                     }
                                 }
                             }
                     }
                     else
                     {
                         me->DespawnOrUnsummon(2050);
                         me->SetOrientation(2.5f);
                         me->SetSpeedRate(MOVE_FLIGHT, 1.0f);
                         Position pos = me->GetPosition();
                         Position offset = { 10.0f, 10.0f, 12.0f, 0.0f };
                         pos.RelocateOffset(offset);
                         me->SetDisableGravity(true);
                         me->GetMotionMaster()->MovePoint(POINT_TAKE_OFF, pos);
                         return;
                     }
                 }
             }
             if (despawnTimer)
             {
                 if (despawnTimer >= 5000)
                 {
                     me->DespawnOrUnsummon(2050);
                     me->SetOrientation(2.5f);
                     Position pos = me->GetPosition();
                     Position offset = { 10.0f, 10.0f, 12.0f, 0.0f };
                     pos.RelocateOffset(offset);
                     return;
                 }
                 else
                     despawnTimer += diff;
             }
             VehicleAI::UpdateAI(diff);
         }
References DATA_EREGOS, DATA_UROM, Creature::DespawnOrUnsummon(), despawnTimer, diff(), DONE, ZoneScript::GetData(), Object::GetEntry(), Unit::GetMotionMaster(), Vehicle::GetPassenger(), Position::GetPosition(), Unit::GetVehicleKit(), IN_PROGRESS, InstanceScript::IsEncounterInProgress(), Unit::IsSummon(), JustSummoned, m_pInstance, Creature::m_spells, CreatureAI::me, MOVE_FLIGHT, MotionMaster::MovePoint(), POINT_TAKE_OFF, pos(), Creature::SetDisableGravity(), Position::SetOrientation(), Unit::SetSpeedRate(), and VehicleAI::UpdateAI().
Member Data Documentation
despawnTimer
uint16 npc_oculus_drake::npc_oculus_drakeAI::despawnTimer
Definition at line 353 of file oculus.cpp.
Referenced by PassengerBoarded(), and UpdateAI().
JustSummoned
bool npc_oculus_drake::npc_oculus_drakeAI::JustSummoned
Definition at line 352 of file oculus.cpp.
Referenced by npc_oculus_drakeAI(), and UpdateAI().
m_pInstance
InstanceScript* npc_oculus_drake::npc_oculus_drakeAI::m_pInstance
Definition at line 351 of file oculus.cpp.
Referenced by IsSummonedBy(), npc_oculus_drakeAI(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Nexus/Oculus/oculus.cpp