Azerotcore-wotlk: WMORoot Class Reference
WMORoot Class Reference
#include <wmo.h>
Public Member Functions
WMORoot (std::string const &filename)
bool open ()
bool ConvertToVMAPRootWmo (FILE *output)
Public Attributes
unsigned int color
uint32 nTextures
uint32 nGroups
uint32 nPortals
uint32 nLights
uint32 nDoodadNames
uint32 nDoodadDefs
uint32 nDoodadSets
uint32 RootWMOID
uint32 liquidType
float bbcorn1 [3]
float bbcorn2 [3]
WMODoodadData DoodadData
std::unordered_set< uint32 > ValidDoodadNames
Private Attributes
std::string filename
Detailed Description
Definition at line 81 of file wmo.h.
Constructor & Destructor Documentation
WMORoot()
WMORoot::WMORoot (std::string const & filename)
Definition at line 32 of file wmo.cpp.
     : filename(filename), color(0), nTextures(0), nGroups(0), nPortals(0), nLights(0),
     nDoodadNames(0), nDoodadDefs(0), nDoodadSets(0), RootWMOID(0), liquidType(0)
 {
     memset(bbcorn1, 0, sizeof(bbcorn1));
     memset(bbcorn2, 0, sizeof(bbcorn2));
 }
References bbcorn1, and bbcorn2.
Member Function Documentation
ConvertToVMAPRootWmo()
bool WMORoot::ConvertToVMAPRootWmo (FILE * output)
Definition at line 146 of file wmo.cpp.
 {
     //printf("Convert RootWmo...\n");
     fwrite(VMAP::RAW_VMAP_MAGIC, 1, 8, pOutfile);
     unsigned int nVectors = 0;
     fwrite(&nVectors, sizeof(nVectors), 1, pOutfile); // will be filled later
     fwrite(&nGroups, 4, 1, pOutfile);
     fwrite(&RootWMOID, 4, 1, pOutfile);
     return true;
 }
References nGroups, VMAP::RAW_VMAP_MAGIC, and RootWMOID.
Referenced by ExtractSingleWmo().
open()
bool WMORoot::open ()
Definition at line 40 of file wmo.cpp.
 {
     MPQFile f(filename.c_str());
     if (f.isEof ())
     {
         printf("No such file.\n");
         return false;
     }
     uint32 size;
     char fourcc[5];
     while (!f.isEof())
     {
         f.read(fourcc, 4);
         f.read(&size, 4);
         flipcc(fourcc);
         fourcc[4] = 0;
         size_t nextpos = f.getPos() + size;
         if (!strcmp(fourcc, "MOHD")) // header
         {
             f.read(&nTextures, 4);
             f.read(&nGroups, 4);
             f.read(&nPortals, 4);
             f.read(&nLights, 4);
             f.read(&nDoodadNames, 4);
             f.read(&nDoodadDefs, 4);
             f.read(&nDoodadSets, 4);
             f.read(&color, 4);
             f.read(&RootWMOID, 4);
             f.read(bbcorn1, 12);
             f.read(bbcorn2, 12);
             f.read(&liquidType, 4);
         }
         else if (!strcmp(fourcc, "MODS"))
         {
             DoodadData.Sets.resize(size / sizeof(WMO::MODS));
             f.read(DoodadData.Sets.data(), size);
         }
         else if (!strcmp(fourcc,"MODN"))
         {
             char* ptr = f.getPointer();
             char* end = ptr + size;
             DoodadData.Paths = std::make_unique<char[]>(size);
             memcpy(DoodadData.Paths.get(), ptr, size);
             while (ptr < end)
             {
                 std::string path = ptr;
                 char* s = GetPlainName(ptr);
                 fixnamen(s, strlen(s));
                 fixname2(s, strlen(s));
                 uint32 doodadNameIndex = ptr - f.getPointer();
                 ptr += path.length() + 1;
                 if (ExtractSingleModel(path))
                     ValidDoodadNames.insert(doodadNameIndex);
             }
         }
         else if (!strcmp(fourcc,"MODD"))
         {
             DoodadData.Spawns.resize(size / sizeof(WMO::MODD));
             f.read(DoodadData.Spawns.data(), size);
         }
         /*
         else if (!strcmp(fourcc,"MOTX"))
         {
         }
         else if (!strcmp(fourcc,"MOMT"))
         {
         }
         else if (!strcmp(fourcc,"MOGN"))
         {
         }
         else if (!strcmp(fourcc,"MOGI"))
         {
         }
         else if (!strcmp(fourcc,"MOLT"))
         {
         }
         else if (!strcmp(fourcc,"MOSB"))
         {
         }
         else if (!strcmp(fourcc,"MOPV"))
         {
         }
         else if (!strcmp(fourcc,"MOPT"))
         {
         }
         else if (!strcmp(fourcc,"MOPR"))
         {
         }
         else if (!strcmp(fourcc,"MFOG"))
         {
         }
         */
         f.seek((int)nextpos);
     }
     f.close ();
     return true;
 }
References bbcorn1, bbcorn2, MPQFile::close(), color, DoodadData, ExtractSingleModel(), filename, fixname2(), fixnamen(), flipcc(), GetPlainName(), MPQFile::getPointer(), MPQFile::getPos(), MPQFile::isEof(), liquidType, nDoodadDefs, nDoodadNames, nDoodadSets, nGroups, nLights, nPortals, nTextures, WMODoodadData::Paths, MPQFile::read(), RootWMOID, MPQFile::seek(), WMODoodadData::Sets, WMODoodadData::Spawns, and ValidDoodadNames.
Referenced by ExtractSingleWmo().
Member Data Documentation
bbcorn1
float WMORoot::bbcorn1[3]
Definition at line 88 of file wmo.h.
Referenced by open(), and WMORoot().
bbcorn2
float WMORoot::bbcorn2[3]
Definition at line 89 of file wmo.h.
Referenced by open(), and WMORoot().
color
unsigned int WMORoot::color
Definition at line 86 of file wmo.h.
Referenced by open().
DoodadData
WMODoodadData WMORoot::DoodadData
Definition at line 91 of file wmo.h.
Referenced by ExtractSingleWmo(), and open().
filename
std::string WMORoot::filename private
Definition at line 84 of file wmo.h.
Referenced by open().
liquidType
uint32 WMORoot::liquidType
Definition at line 87 of file wmo.h.
Referenced by WMOGroup::ConvertToVMAPGroupWmo(), and open().
nDoodadDefs
uint32 WMORoot::nDoodadDefs
Definition at line 87 of file wmo.h.
Referenced by open().
nDoodadNames
uint32 WMORoot::nDoodadNames
Definition at line 87 of file wmo.h.
Referenced by open().
nDoodadSets
uint32 WMORoot::nDoodadSets
Definition at line 87 of file wmo.h.
Referenced by open().
nGroups
uint32 WMORoot::nGroups
Definition at line 87 of file wmo.h.
Referenced by ConvertToVMAPRootWmo(), ExtractSingleWmo(), and open().
nLights
uint32 WMORoot::nLights
Definition at line 87 of file wmo.h.
Referenced by open().
nPortals
uint32 WMORoot::nPortals
Definition at line 87 of file wmo.h.
Referenced by open().
nTextures
uint32 WMORoot::nTextures
Definition at line 87 of file wmo.h.
Referenced by open().
RootWMOID
uint32 WMORoot::RootWMOID
Definition at line 87 of file wmo.h.
Referenced by ConvertToVMAPRootWmo(), and open().
ValidDoodadNames
std::unordered_set<uint32> WMORoot::ValidDoodadNames
Definition at line 92 of file wmo.h.
Referenced by ExtractSingleWmo(), and open().
The documentation for this class was generated from the following files:
src/tools/vmap4_extractor/wmo.h
src/tools/vmap4_extractor/wmo.cpp