Azerotcore-wotlk: printf_arg_formatter< OutputIt, Char > Class Template Reference
printf_arg_formatter< OutputIt, Char > Class Template Reference
#include <printf.h>
Public Member Functions
printf_arg_formatter (OutputIt iter, format_specs &s, context_type &ctx)
OutputIt operator() (monostate value)
template<typename T , FMT_ENABLE_IF(detail::is_integral< T >::value) >
OutputIt operator() (T value)
template<typename T , FMT_ENABLE_IF(std::is_floating_point< T >::value) >
OutputIt operator() (T value)
OutputIt operator() (const char *value)
OutputIt operator() (const wchar_t *value)
OutputIt operator() (basic_string_view< Char > value)
OutputIt operator() (const void *value)
OutputIt operator() (typename basic_format_arg< context_type >::handle handle)
Public Member Functions inherited from arg_formatter< Char >
template<typename T >
FMT_CONSTEXPR FMT_INLINE auto operator() (T value) -> iterator
auto operator() (typename basic_format_arg< context >::handle) -> iterator
Private Types
using base = arg_formatter< Char >
using context_type = basic_printf_context< OutputIt, Char >
using format_specs = basic_format_specs< Char >
Private Member Functions
OutputIt write_null_pointer (bool is_string=false)
Private Attributes
context_type & context_
Additional Inherited Members
Public Types inherited from arg_formatter< Char >
using iterator = buffer_appender< Char >
using context = buffer_context< Char >
Public Attributes inherited from arg_formatter< Char >
iterator out
const basic_format_specs< Char > & specs
locale_ref locale
Detailed Description
template<typename OutputIt, typename Char>
class printf_arg_formatter< OutputIt, Char >
Definition at line 226 of file printf.h.
Member Typedef Documentation
base
template<typename OutputIt , typename Char > using printf_arg_formatter< OutputIt, Char >::base = arg_formatter<Char> private
Definition at line 228 of file printf.h.
context_type
template<typename OutputIt , typename Char > using printf_arg_formatter< OutputIt, Char >::context_type = basic_printf_context<OutputIt, Char> private
Definition at line 229 of file printf.h.
format_specs
template<typename OutputIt , typename Char > using printf_arg_formatter< OutputIt, Char >::format_specs = basic_format_specs<Char> private
Definition at line 230 of file printf.h.
Constructor & Destructor Documentation
printf_arg_formatter()
template<typename OutputIt , typename Char > printf_arg_formatter< OutputIt, Char >::printf_arg_formatter (OutputIt iter, format_specs & s, context_type & ctx) inline
Definition at line 241 of file printf.h.
       : base{iter, s, locale_ref()}, context_(ctx) {}
Member Function Documentation
operator()() [1/8]
template<typename OutputIt , typename Char > OutputIt printf_arg_formatter< OutputIt, Char >::operator() (basic_string_view< Char > value) inline
Definition at line 283 of file printf.h.
{
     return base::operator()(value);
   }
References arg_formatter< Char >::operator()().
operator()() [2/8]
template<typename OutputIt , typename Char > OutputIt printf_arg_formatter< OutputIt, Char >::operator() (const char * value) inline
Formats a null-terminated C string.
Definition at line 272 of file printf.h.
{
     if (value) return base::operator()(value);
     return write_null_pointer(this->specs.type != 'p');
   }
References arg_formatter< Char >::operator()(), arg_formatter< Char >::specs, and printf_arg_formatter< OutputIt, Char >::write_null_pointer().
operator()() [3/8]
template<typename OutputIt , typename Char > OutputIt printf_arg_formatter< OutputIt, Char >::operator() (const void * value) inline
Formats a pointer.
Definition at line 288 of file printf.h.
{
     return value ? base::operator()(value) : write_null_pointer();
   }
References arg_formatter< Char >::operator()(), and printf_arg_formatter< OutputIt, Char >::write_null_pointer().
operator()() [4/8]
template<typename OutputIt , typename Char > OutputIt printf_arg_formatter< OutputIt, Char >::operator() (const wchar_t * value) inline
Formats a null-terminated wide C string.
Definition at line 278 of file printf.h.
{
     if (value) return base::operator()(value);
     return write_null_pointer(this->specs.type != 'p');
   }
References arg_formatter< Char >::operator()(), arg_formatter< Char >::specs, and printf_arg_formatter< OutputIt, Char >::write_null_pointer().
operator()() [5/8]
template<typename OutputIt , typename Char > OutputIt printf_arg_formatter< OutputIt, Char >::operator() (monostate value) inline
Definition at line 244 of file printf.h.
 { return base::operator()(value); }
References arg_formatter< Char >::operator()().
operator()() [6/8]
template<typename OutputIt , typename Char > template<typename T , FMT_ENABLE_IF(detail::is_integral< T >::value) > OutputIt printf_arg_formatter< OutputIt, Char >::operator() (T value) inline
Definition at line 247 of file printf.h.
{
     // MSVC2013 fails to compile separate overloads for bool and Char so use
     // std::is_same instead.
     if (std::is_same<T, Char>::value) {
       format_specs fmt_specs = this->specs;
       if (fmt_specs.type && fmt_specs.type != 'c')
         return (*this)(static_cast<int>(value));
       fmt_specs.sign = sign::none;
       fmt_specs.alt = false;
       fmt_specs.fill[0] = ' ';  // Ignore '0' flag for char types.
       // align::numeric needs to be overwritten here since the '0' flag is
       // ignored for non-numeric types
       if (fmt_specs.align == align::none || fmt_specs.align == align::numeric)
         fmt_specs.align = align::right;
       return write<Char>(this->out, static_cast<Char>(value), fmt_specs);
     }
     return base::operator()(value);
   }
References basic_format_specs< Char >::align, basic_format_specs< Char >::alt, basic_format_specs< Char >::fill, align::none, sign::none, align::numeric, arg_formatter< Char >::operator()(), arg_formatter< Char >::out, align::right, basic_format_specs< Char >::sign, arg_formatter< Char >::specs, and basic_format_specs< Char >::type.
operator()() [7/8]
template<typename OutputIt , typename Char > template<typename T , FMT_ENABLE_IF(std::is_floating_point< T >::value) > OutputIt printf_arg_formatter< OutputIt, Char >::operator() (T value) inline
Definition at line 267 of file printf.h.
{
     return base::operator()(value);
   }
References arg_formatter< Char >::operator()().
operator()() [8/8]
template<typename OutputIt , typename Char > OutputIt printf_arg_formatter< OutputIt, Char >::operator() (typename basic_format_arg< context_type >::handle handle) inline
Formats an argument of a custom (user-defined) type.
Definition at line 293 of file printf.h.
{
     auto parse_ctx =
         basic_printf_parse_context<Char>(basic_string_view<Char>());
     handle.format(parse_ctx, context_);
     return this->out;
   }
References printf_arg_formatter< OutputIt, Char >::context_, basic_format_arg< Context >::handle::format(), and arg_formatter< Char >::out.
write_null_pointer()
template<typename OutputIt , typename Char > OutputIt printf_arg_formatter< OutputIt, Char >::write_null_pointer (bool is_string = false) inline private
Definition at line 234 of file printf.h.
{
     auto s = this->specs;
     s.type = 0;
     return write_bytes(this->out, is_string ? "(null)" : "(nil)", s);
   }
References arg_formatter< Char >::out, arg_formatter< Char >::specs, and write_bytes().
Referenced by printf_arg_formatter< OutputIt, Char >::operator()().
Member Data Documentation
context_
template<typename OutputIt , typename Char > context_type& printf_arg_formatter< OutputIt, Char >::context_ private
Definition at line 232 of file printf.h.
Referenced by printf_arg_formatter< OutputIt, Char >::operator()().
The documentation for this class was generated from the following file:
deps/fmt/include/fmt/printf.h