Azerotcore-wotlk: RASession Class Reference
RASession Class Reference
#include <RASession.h>
Public Member Functions
RASession (tcp::socket &&socket)
void Start ()
const std::string GetRemoteIpAddress () const
unsigned short GetRemotePort () const
Private Member Functions
int Send (std::string_view data)
std::string ReadString ()
bool CheckAccessLevel (const std::string &user)
bool CheckPassword (const std::string &user, const std::string &pass)
bool ProcessCommand (std::string &command)
Static Private Member Functions
static void CommandPrint (void *callbackArg, std::string_view text)
static void CommandFinished (void *callbackArg, bool)
Private Attributes
tcp::socket _socket
boost::asio::streambuf _readBuffer
boost::asio::streambuf _writeBuffer
std::promise< void > * _commandExecuting
Detailed Description
Definition at line 31 of file RASession.h.
Constructor & Destructor Documentation
RASession()
RASession::RASession (tcp::socket && socket) inline
Definition at line 34 of file RASession.h.
                                   :
         _socket(std::move(socket)), _commandExecuting(nullptr) { }
Member Function Documentation
CheckAccessLevel()
bool RASession::CheckAccessLevel (const std::string & user) private
Definition at line 123 of file RASession.cpp.
 {
     std::string safeUser = user;
     Utf8ToUpperOnlyLatin(safeUser);
     auto* stmt = LoginDatabase.GetPreparedStatement(LOGIN_SEL_ACCOUNT_ACCESS);
     stmt->setString(0, safeUser);
     PreparedQueryResult result = LoginDatabase.Query(stmt);
     if (!result)
     {
         LOG_INFO("commands.ra", "User %s does not exist in database", user.c_str());
         return false;
     }
     Field* fields = result->Fetch();
     if (fields[1].GetUInt8() < sConfigMgr->GetOption<int32>("Ra.MinLevel", 3))
     {
         LOG_INFO("commands.ra", "User %s has no privilege to login", user.c_str());
         return false;
     }
     else if (fields[2].GetInt32() != -1)
     {
         LOG_INFO("commands.ra", "User %s has to be assigned on all realms (with RealmID = '-1')", user.c_str());
         return false;
     }
     return true;
 }
References LOG_INFO, LOGIN_SEL_ACCOUNT_ACCESS, LoginDatabase, sConfigMgr, and Utf8ToUpperOnlyLatin().
Referenced by Start().
CheckPassword()
bool RASession::CheckPassword (const std::string & user, const std::string & pass) private
Definition at line 155 of file RASession.cpp.
 {
     std::string safe_user = user;
     std::transform(safe_user.begin(), safe_user.end(), safe_user.begin(), ::toupper);
     Utf8ToUpperOnlyLatin(safe_user);
     std::string safe_pass = pass;
     Utf8ToUpperOnlyLatin(safe_pass);
     std::transform(safe_pass.begin(), safe_pass.end(), safe_pass.begin(), ::toupper);
     auto* stmt = LoginDatabase.GetPreparedStatement(LOGIN_SEL_CHECK_PASSWORD_BY_NAME);
     stmt->setString(0, safe_user);
     if (PreparedQueryResult result = LoginDatabase.Query(stmt))
     {
         Acore::Crypto::SRP6::Salt salt = (*result)[0].GetBinary<Acore::Crypto::SRP6::SALT_LENGTH>();
         Acore::Crypto::SRP6::Verifier verifier = (*result)[1].GetBinary<Acore::Crypto::SRP6::VERIFIER_LENGTH>();
         if (Acore::Crypto::SRP6::CheckLogin(safe_user, safe_pass, salt, verifier))
             return true;
     }
     LOG_INFO("commands.ra", "Wrong password for user: %s", user.c_str());
     return false;
 }
References Acore::Crypto::SRP6::CheckLogin(), LOG_INFO, LOGIN_SEL_CHECK_PASSWORD_BY_NAME, LoginDatabase, Acore::Crypto::SRP6::SALT_LENGTH, Utf8ToUpperOnlyLatin(), and Acore::Crypto::SRP6::VERIFIER_LENGTH.
Referenced by Start().
CommandFinished()
void RASession::CommandFinished (void * callbackArg, bool) static private
Definition at line 220 of file RASession.cpp.
 {
     RASession* session = static_cast<RASession*>(callbackArg);
     session->_commandExecuting->set_value();
 }
References _commandExecuting.
Referenced by ProcessCommand().
CommandPrint()
void RASession::CommandPrint (void * callbackArg, std::string_view text) static private
Definition at line 209 of file RASession.cpp.
 {
     if (text.empty())
     {
         return;
     }
     RASession* session = static_cast<RASession*>(callbackArg);
     session->Send(text);
 }
References Send().
Referenced by ProcessCommand().
GetRemoteIpAddress()
const std::string RASession::GetRemoteIpAddress () const inline
Definition at line 39 of file RASession.h.
 { return _socket.remote_endpoint().address().to_string(); }
References _socket.
Referenced by Start().
GetRemotePort()
unsigned short RASession::GetRemotePort () const inline
Definition at line 40 of file RASession.h.
 { return _socket.remote_endpoint().port(); }
References _socket.
ProcessCommand()
bool RASession::ProcessCommand (std::string & command) private
Definition at line 182 of file RASession.cpp.
 {
     if (command.length() == 0)
         return true;
     LOG_INFO("commands.ra", "Received command: %s", command.c_str());
     // handle quit, exit and logout commands to terminate connection
     if (command == "quit" || command == "exit" || command == "logout")
     {
         Send("Bye\r\n");
         return true;
     }
     // Obtain a new promise per command
     delete _commandExecuting;
     _commandExecuting = new std::promise<void>();
     CliCommandHolder* cmd = new CliCommandHolder(this, command.c_str(), &RASession::CommandPrint, &RASession::CommandFinished);
     sWorld->QueueCliCommand(cmd);
     // Wait for the command to finish
     _commandExecuting->get_future().wait();
     return false;
 }
References _commandExecuting, CommandFinished(), CommandPrint(), LOG_INFO, Send(), and sWorld.
Referenced by Start().
ReadString()
std::string RASession::ReadString () private
Definition at line 103 of file RASession.cpp.
 {
     boost::system::error_code error;
     size_t read = boost::asio::read_until(_socket, _readBuffer, "\r\n", error);
     if (!read)
     {
         _socket.close();
         return "";
     }
     std::string line;
     std::istream is(&_readBuffer);
     std::getline(is, line);
     if (*line.rbegin() == '\r')
         line.erase(line.length() - 1);
     return line;
 }
References _readBuffer, _socket, error(), and read.
Referenced by Start().
Send()
int RASession::Send (std::string_view data) private
Definition at line 94 of file RASession.cpp.
 {
     std::ostream os(&_writeBuffer);
     os << data;
     size_t written = _socket.send(_writeBuffer.data());
     _writeBuffer.consume(written);
     return written;
 }
References _socket, and _writeBuffer.
Referenced by CommandPrint(), ProcessCommand(), and Start().
Start()
void RASession::Start ()
Definition at line 35 of file RASession.cpp.
 {
     // wait 1 second for active connections to send negotiation request
     for (int counter = 0; counter < 10 && _socket.available() == 0; counter++)
         std::this_thread::sleep_for(100ms);
     // Check if there are bytes available, if they are, then the client is requesting the negotiation
     if (_socket.available() > 0)
     {
         // Handle subnegotiation
         char buf[1024] = { };
         _socket.read_some(boost::asio::buffer(buf));
         // Send the end-of-negotiation packet
         uint8 const reply[2] = { 0xFF, 0xF0 };
         _socket.write_some(boost::asio::buffer(reply));
     }
     Send("Authentication Required\r\n");
     Send("Username: ");
     std::string username = ReadString();
     if (username.empty())
         return;
     LOG_INFO("commands.ra", "Accepting RA connection from user %s (IP: %s)", username.c_str(), GetRemoteIpAddress().c_str());
     Send("Password: ");
     std::string password = ReadString();
     if (password.empty())
         return;
     if (!CheckAccessLevel(username) || !CheckPassword(username, password))
     {
         Send("Authentication failed\r\n");
         _socket.close();
         return;
     }
     LOG_INFO("commands.ra", "User %s (IP: %s) authenticated correctly to RA", username.c_str(), GetRemoteIpAddress().c_str());
     // Authentication successful, send the motd
     Send(std::string(std::string(Motd::GetMotd()) + "\r\n").c_str());
     // Read commands
     for (;;)
     {
         Send("AC>");
         std::string command = ReadString();
         if (ProcessCommand(command))
             break;
     }
     _socket.close();
 }
References _socket, buffer, CheckAccessLevel(), CheckPassword(), Motd::GetMotd(), GetRemoteIpAddress(), LOG_INFO, ProcessCommand(), ReadString(), and Send().
Member Data Documentation
_commandExecuting
std::promise<void>* RASession::_commandExecuting private
Definition at line 55 of file RASession.h.
Referenced by CommandFinished(), and ProcessCommand().
_readBuffer
boost::asio::streambuf RASession::_readBuffer private
Definition at line 53 of file RASession.h.
Referenced by ReadString().
_socket
tcp::socket RASession::_socket private
Definition at line 52 of file RASession.h.
Referenced by GetRemoteIpAddress(), GetRemotePort(), ReadString(), Send(), and Start().
_writeBuffer
boost::asio::streambuf RASession::_writeBuffer private
Definition at line 54 of file RASession.h.
Referenced by Send().
The documentation for this class was generated from the following files:
src/server/worldserver/RemoteAccess/RASession.h
src/server/worldserver/RemoteAccess/RASession.cpp