Azerotcore-wotlk: npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI Struct Reference
npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI Struct Reference
Public Member Functions
npc_green_dragon_combat_triggerAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *target) override
void AttackStart (Unit *target) override
void MoveInLineOfSight (Unit *) override
bool CanAIAttack (Unit const *target) const override
void JustReachedHome () override
void DoAction (int32 action) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void JustDied (Unit *) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
uint16 checkTimer
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 505 of file boss_valithria_dreamwalker.cpp.
Constructor & Destructor Documentation
npc_green_dragon_combat_triggerAI()
npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::npc_green_dragon_combat_triggerAI (Creature * creature) inline
Definition at line 507 of file boss_valithria_dreamwalker.cpp.
                                                               : BossAI(creature, DATA_VALITHRIA_DREAMWALKER)
         {
         }
Member Function Documentation
AttackStart()
void npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::AttackStart (Unit * target) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 552 of file boss_valithria_dreamwalker.cpp.
         {
             if (target->GetTypeId() == TYPEID_PLAYER)
                 BossAI::AttackStart(target);
         }
References ScriptedAI::AttackStart(), Object::GetTypeId(), and TYPEID_PLAYER.
CanAIAttack()
bool npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::CanAIAttack (Unit const * target) const inline override virtual
Reimplemented from UnitAI.
Definition at line 560 of file boss_valithria_dreamwalker.cpp.
         {
             return target->GetTypeId() == TYPEID_PLAYER;
         }
References Object::GetTypeId(), and TYPEID_PLAYER.
DoAction()
void npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 573 of file boss_valithria_dreamwalker.cpp.
         {
             if (action == ACTION_DEATH)
                 me->m_Events.AddEvent(new ValithriaDespawner(me), me->m_Events.CalculateTime(5000));
             else if (action == ACTION_ENTER_COMBAT)
             {
                 if (!me->IsInCombat())
                     me->SetInCombatWithZone();
             }
         }
References ACTION_DEATH, ACTION_ENTER_COMBAT, EventProcessor::AddEvent(), EventProcessor::CalculateTime(), Unit::IsInCombat(), Unit::m_Events, ScriptedAI::me, and Creature::SetInCombatWithZone().
Referenced by JustReachedHome().
EnterCombat()
void npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::EnterCombat (Unit * target) inline override virtual
Reimplemented from BossAI.
Definition at line 521 of file boss_valithria_dreamwalker.cpp.
         {
             if (!instance->CheckRequiredBosses(DATA_VALITHRIA_DREAMWALKER, target->ToPlayer()))
             {
                 me->setActive(true);
                 EnterEvadeMode();
                 instance->DoCastSpellOnPlayers(LIGHT_S_HAMMER_TELEPORT);
                 return;
             }
             if (instance->GetBossState(DATA_VALITHRIA_DREAMWALKER) == DONE)
             {
                 me->CombatStop();
                 return;
             }
             me->setActive(true);
             me->SetInCombatWithZone();
             instance->SetBossState(DATA_VALITHRIA_DREAMWALKER, IN_PROGRESS);
             if (Creature* valithria = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_VALITHRIA_DREAMWALKER)))
                 valithria->AI()->DoAction(ACTION_ENTER_COMBAT);
             if (Creature* lichKing = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_VALITHRIA_LICH_KING)))
                 lichKing->AI()->DoAction(ACTION_ENTER_COMBAT);
             std::list<Creature*> archmages;
             RisenArchmageCheck check;
             Acore::CreatureListSearcher<RisenArchmageCheck> searcher(me, archmages, check);
             Cell::VisitGridObjects(me, searcher, 100.0f);
             for (std::list<Creature*>::iterator itr = archmages.begin(); itr != archmages.end(); ++itr)
                 (*itr)->AI()->DoAction(ACTION_ENTER_COMBAT);
         }
References ACTION_ENTER_COMBAT, InstanceScript::CheckRequiredBosses(), Unit::CombatStop(), DATA_VALITHRIA_DREAMWALKER, DATA_VALITHRIA_LICH_KING, InstanceScript::DoCastSpellOnPlayers(), DONE, CreatureAI::EnterEvadeMode(), InstanceScript::GetBossState(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), IN_PROGRESS, BossAI::instance, LIGHT_S_HAMMER_TELEPORT, ScriptedAI::me, WorldObject::setActive(), InstanceScript::SetBossState(), Creature::SetInCombatWithZone(), Object::ToPlayer(), and Cell::VisitGridObjects().
JustReachedHome()
void npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::JustReachedHome () inline override virtual
Reimplemented from BossAI.
Definition at line 565 of file boss_valithria_dreamwalker.cpp.
         {
             if (instance->GetBossState(DATA_VALITHRIA_DREAMWALKER) != DONE)
                 DoAction(ACTION_DEATH); // setActive(false) in ValithriaDespawner
             else
                 _JustReachedHome();
         }
References BossAI::_JustReachedHome(), ACTION_DEATH, DATA_VALITHRIA_DREAMWALKER, DoAction(), DONE, InstanceScript::GetBossState(), and BossAI::instance.
MoveInLineOfSight()
void npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 558 of file boss_valithria_dreamwalker.cpp.
 {}
Reset()
void npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 511 of file boss_valithria_dreamwalker.cpp.
         {
             events.Reset();
             summons.DespawnAll();
             if (instance->GetBossState(DATA_VALITHRIA_DREAMWALKER) != DONE)
                 instance->SetBossState(DATA_VALITHRIA_DREAMWALKER, NOT_STARTED);
             me->SetReactState(REACT_PASSIVE);
             checkTimer = 5000;
         }
References checkTimer, DATA_VALITHRIA_DREAMWALKER, SummonList::DespawnAll(), DONE, InstanceScript::GetBossState(), BossAI::instance, ScriptedAI::me, NOT_STARTED, REACT_PASSIVE, InstanceScript::SetBossState(), Creature::SetReactState(), and BossAI::summons.
UpdateAI()
void npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 584 of file boss_valithria_dreamwalker.cpp.
         {
             if (!me->IsInCombat())
                 return;
             if (checkTimer <= diff)
             {
                 checkTimer = 3000;
                 me->SetInCombatWithZone();
                 ThreatContainer::StorageType const& threatList = me->getThreatMgr().getThreatList();
                 if (!threatList.empty())
                     for (ThreatContainer::StorageType::const_iterator itr = threatList.begin(); itr != threatList.end(); ++itr)
                         if (Unit* target = (*itr)->getTarget())
                             if (target->IsAlive() && target->GetTypeId() == TYPEID_PLAYER && me->GetExactDist(target) < 200.0f && !target->IsImmunedToDamageOrSchool(SPELL_SCHOOL_MASK_ALL))
                                 return;
                 EnterEvadeMode();
             }
             else
                 checkTimer -= diff;
         }
References checkTimer, diff(), CreatureAI::EnterEvadeMode(), Position::GetExactDist(), ThreatMgr::getThreatList(), Unit::getThreatMgr(), Unit::IsInCombat(), ScriptedAI::me, Creature::SetInCombatWithZone(), SPELL_SCHOOL_MASK_ALL, and TYPEID_PLAYER.
Member Data Documentation
checkTimer
uint16 npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::checkTimer private
Definition at line 606 of file boss_valithria_dreamwalker.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_valithria_dreamwalker.cpp