Azerotcore-wotlk: G3D::Matrix2 Class Reference
G3D::Matrix2 Class Reference
#include <Matrix2.h>
Public Member Functions
Matrix2 ()
Matrix2 (float v00, float v01, float v10, float v11)
Vector2 operator* (const Vector2 &v) const
Matrix2 inverse () const
Matrix2 transpose () const
float determinant () const
Matrix2 operator* (float f) const
Matrix2 operator/ (float f) const
float * operator[] (int i)
const float * operator[] (int i) const
operator float * ()
operator const float * () const
Static Public Member Functions
static Matrix2 identity ()
Private Attributes
float data [2][2]
Detailed Description
@beta
Definition at line 10 of file Matrix2.h.
Constructor & Destructor Documentation
Matrix2() [1/2]
G3D::Matrix2::Matrix2 () inline
Definition at line 17 of file Matrix2.h.
               {
         data[0][0] = 1.0f; data[0][1] = 0.0f;
         data[1][0] = 0.0f; data[1][1] = 1.0f;
     }
Referenced by identity(), inverse(), operator*(), operator/(), and transpose().
Matrix2() [2/2]
G3D::Matrix2::Matrix2 (float v00, float v01, float v10, float v11) inline
Definition at line 22 of file Matrix2.h.
{
         data[0][0] = v00; data[0][1] = v01;
         data[1][0] = v10; data[1][1] = v11;
     }
Member Function Documentation
determinant()
float G3D::Matrix2::determinant () const inline
Definition at line 46 of file Matrix2.h.
{
         return data[0][0] * data[1][1] - data[0][1] * data[1][0];
     }
Referenced by inverse().
identity()
static Matrix2 G3D::Matrix2::identity () inline static
Definition at line 27 of file Matrix2.h.
{
         return Matrix2(1.0f, 0.0f, 0.0f, 1.0f);
     }
References Matrix2().
inverse()
Matrix2 G3D::Matrix2::inverse () const inline
Definition at line 36 of file Matrix2.h.
{
         return Matrix2(data[1][1], -data[0][1],
                        -data[1][0], data[0][0]) * (1.0f / determinant());
     }
References determinant(), and Matrix2().
operator const float *()
G3D::Matrix2::operator const float * () const inline
Definition at line 74 of file Matrix2.h.
{
         return (const float*)&data[0][0];
     }
operator float *()
G3D::Matrix2::operator float * () inline
Definition at line 70 of file Matrix2.h.
{
         return (float*)&data[0][0];
     }
operator*() [1/2]
Vector2 G3D::Matrix2::operator* (const Vector2 & v) const inline
Definition at line 31 of file Matrix2.h.
{
         return Vector2(data[0][0] * v[0] + data[0][1] * v[1],
                        data[1][0] * v[0] + data[1][1] * v[1]);
     }
operator*() [2/2]
Matrix2 G3D::Matrix2::operator* (float f) const inline
Definition at line 50 of file Matrix2.h.
{
         return Matrix2(data[0][0] * f, data[0][1] * f,
                        data[1][0] * f, data[1][1] * f);
     }
References f(), and Matrix2().
operator/()
Matrix2 G3D::Matrix2::operator/ (float f) const inline
Definition at line 55 of file Matrix2.h.
{
         return Matrix2(data[0][0] / f, data[0][1] / f,
                        data[1][0] / f, data[1][1] / f);
     }
References f(), and Matrix2().
operator[]() [1/2]
float* G3D::Matrix2::operator[] (int i) inline
Definition at line 60 of file Matrix2.h.
{
         debugAssert(i >= 0 && i <= 1);
         return (float*)&data[i][0];
     }
References debugAssert.
operator[]() [2/2]
const float* G3D::Matrix2::operator[] (int i) const inline
Definition at line 65 of file Matrix2.h.
{
         debugAssert(i >= 0 && i <= 1);
         return (const float*)&data[i][0];
     }
References debugAssert.
transpose()
Matrix2 G3D::Matrix2::transpose () const inline
Definition at line 41 of file Matrix2.h.
{
         return Matrix2(data[0][0], data[1][0],
                        data[0][1], data[1][1]);
     }
References Matrix2().
Member Data Documentation
data
float G3D::Matrix2::data[2][2] private
Definition at line 13 of file Matrix2.h.
The documentation for this class was generated from the following file:
deps/g3dlite/include/G3D/Matrix2.h