Azerotcore-wotlk: TotemAI Class Reference
TotemAI Class Reference
#include <TotemAI.h>
Public Member Functions
TotemAI (Creature *c)
void MoveInLineOfSight (Unit *who) override
void AttackStart (Unit *victim) override
void EnterEvadeMode () override
void SpellHit (Unit *, const SpellInfo *) override
void DoAction (int32 param) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void Reset ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Static Public Member Functions
static int Permissible (Creature const *creature)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Private Attributes
ObjectGuid i_victimGuid
Additional Inherited Members
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 27 of file TotemAI.h.
Constructor & Destructor Documentation
TotemAI()
TotemAI::TotemAI (Creature * c) explicit
Definition at line 36 of file TotemAI.cpp.
                             : CreatureAI(c)
 {
     ASSERT(c->IsTotem());
 }
References ASSERT, and mpq::c.
Member Function Documentation
AttackStart()
void TotemAI::AttackStart (Unit * victim) override virtual
Reimplemented from UnitAI.
Definition at line 109 of file TotemAI.cpp.
 {
     // Sentry totem sends ping on attack
     if (me->GetEntry() == SENTRY_TOTEM_ENTRY && me->GetOwner()->GetTypeId() == TYPEID_PLAYER)
     {
         WorldPacket data(MSG_MINIMAP_PING, (8 + 4 + 4));
         data << me->GetGUID();
         data << me->GetPositionX();
         data << me->GetPositionY();
         me->GetOwner()->ToPlayer()->GetSession()->SendPacket(&data);
     }
 }
References Object::GetEntry(), Object::GetGUID(), Unit::GetOwner(), Position::GetPositionX(), Position::GetPositionY(), Player::GetSession(), Object::GetTypeId(), CreatureAI::me, MSG_MINIMAP_PING, WorldSession::SendPacket(), SENTRY_TOTEM_ENTRY, Object::ToPlayer(), and TYPEID_PLAYER.
DoAction()
void TotemAI::DoAction (int32 param) override virtual
Reimplemented from UnitAI.
Definition at line 45 of file TotemAI.cpp.
 {
 }
EnterEvadeMode()
void TotemAI::EnterEvadeMode () override virtual
Reimplemented from CreatureAI.
Definition at line 53 of file TotemAI.cpp.
 {
     me->CombatStop(true);
 }
References Unit::CombatStop(), and CreatureAI::me.
MoveInLineOfSight()
void TotemAI::MoveInLineOfSight (Unit * who) override virtual
Reimplemented from CreatureAI.
Definition at line 49 of file TotemAI.cpp.
 {
 }
Permissible()
int TotemAI::Permissible (Creature const * creature) static
Definition at line 28 of file TotemAI.cpp.
 {
     if (creature->IsTotem())
         return PERMIT_BASE_PROACTIVE;
     return PERMIT_BASE_NO;
 }
References Unit::IsTotem(), PERMIT_BASE_NO, and PERMIT_BASE_PROACTIVE.
SpellHit()
void TotemAI::SpellHit (Unit * , const SpellInfo *) override virtual
Reimplemented from CreatureAI.
Definition at line 41 of file TotemAI.cpp.
 {
 }
UpdateAI()
void TotemAI::UpdateAI (uint32 diff) override virtual
Implements UnitAI.
Definition at line 58 of file TotemAI.cpp.
 {
     if (me->ToTotem()->GetTotemType() != TOTEM_ACTIVE)
         return;
     if (!me->IsAlive() || me->IsNonMeleeSpellCast(false))
         return;
     // Search spell
     SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(me->ToTotem()->GetSpell());
     if (!spellInfo)
         return;
     // Get spell range
     float max_range = spellInfo->GetMaxRange(false);
     // SPELLMOD_RANGE not applied in this place just because not existence range mods for attacking totems
     // pointer to appropriate target if found any
     Unit* victim = i_victimGuid ? ObjectAccessor::GetUnit(*me, i_victimGuid) : nullptr;
     // Search victim if no, not attackable, or out of range, or friendly (possible in case duel end)
     if (!victim ||
             !victim->isTargetableForAttack(true, me) || !me->IsWithinDistInMap(victim, max_range) ||
             me->IsFriendlyTo(victim) || !me->CanSeeOrDetect(victim))
     {
         victim = nullptr;
         Acore::NearestAttackableUnitInObjectRangeCheck u_check(me, me, max_range);
         Acore::UnitLastSearcher<Acore::NearestAttackableUnitInObjectRangeCheck> checker(me, victim, u_check);
         Cell::VisitAllObjects(me, checker, max_range);
     }
     if (!victim && me->GetCharmerOrOwnerOrSelf()->IsInCombat())
     {
         victim = me->GetCharmerOrOwnerOrSelf()->getAttackerForHelper();
     }
     // If have target
     if (victim)
     {
         // remember
         i_victimGuid = victim->GetGUID();
         // attack
         me->SetInFront(victim);                         // client change orientation by self
         me->CastSpell(victim, me->ToTotem()->GetSpell(), false);
     }
     else
         i_victimGuid.Clear();
 }
References WorldObject::CanSeeOrDetect(), Unit::CastSpell(), ObjectGuid::Clear(), Unit::getAttackerForHelper(), Unit::GetCharmerOrOwnerOrSelf(), Object::GetGUID(), SpellInfo::GetMaxRange(), Totem::GetSpell(), Totem::GetTotemType(), ObjectAccessor::GetUnit(), i_victimGuid, Unit::IsAlive(), Unit::IsFriendlyTo(), Unit::IsInCombat(), Unit::IsNonMeleeSpellCast(), Unit::isTargetableForAttack(), WorldObject::IsWithinDistInMap(), CreatureAI::me, Unit::SetInFront(), sSpellMgr, TOTEM_ACTIVE, Unit::ToTotem(), and Cell::VisitAllObjects().
Member Data Documentation
i_victimGuid
ObjectGuid TotemAI::i_victimGuid private
Definition at line 42 of file TotemAI.h.
Referenced by UpdateAI().
The documentation for this class was generated from the following files:
src/server/game/AI/CoreAI/TotemAI.h
src/server/game/AI/CoreAI/TotemAI.cpp