Azerotcore-wotlk: Acore::Encoding::Base32 Struct Reference
Acore::Encoding::Base32 Struct Reference
#include <Base32.h>
Static Public Member Functions
static std::string Encode (std::vector< uint8 > const &data)
static Optional< std::vector< uint8 > > Decode (std::string const &data)
Detailed Description
Definition at line 16 of file Base32.h.
Member Function Documentation
Decode()
Optional< std::vector< uint8 > > Acore::Encoding::Base32::Decode (std::string const & data) static
Definition at line 40 of file Base32.cpp.
 {
     return Acore::Impl::GenericBaseEncoding<B32Impl>::Decode(data);
 }
References Acore::Impl::GenericBaseEncoding< Encoding >::Decode().
Referenced by account_commandscript::HandleAccountSet2FACommand().
Encode()
std::string Acore::Encoding::Base32::Encode (std::vector< uint8 > const & data) static
Definition at line 35 of file Base32.cpp.
 {
     return Acore::Impl::GenericBaseEncoding<B32Impl>::Encode(data);
 }
References Acore::Impl::GenericBaseEncoding< Encoding >::Encode().
Referenced by account_commandscript::HandleAccount2FASetupCommand().
The documentation for this struct was generated from the following files:
src/common/Encoding/Base32.h
src/common/Encoding/Base32.cpp