Azerotcore-wotlk: deps/mysqllite/mysys/lf_alloc-pin.c File Reference
lf_alloc-pin.c File Reference
#include <my_global.h>
#include <my_sys.h>
#include <lf.h>
Classes
struct st_harvester
Macros
#define LF_PINBOX_MAX_PINS 65536
#define add_to_purgatory(PINS, ADDR)
#define available_stack_size(CUR, END) (long) ((char*)(END) - (char*)(CUR))
#define next_node(P, X) (*((uchar * volatile *)(((uchar *)(X)) + (P)->free_ptr_offset)))
#define anext_node(X) next_node(&allocator->pinbox, (X))
Functions
static void _lf_pinbox_real_free (LF_PINS *pins)
void lf_pinbox_init (LF_PINBOX *pinbox, uint free_ptr_offset, lf_pinbox_free_func *free_func, void *free_func_arg)
void lf_pinbox_destroy (LF_PINBOX *pinbox)
LF_PINS * _lf_pinbox_get_pins (LF_PINBOX *pinbox)
void _lf_pinbox_put_pins (LF_PINS *pins)
static int ptr_cmp (void **a, void **b)
void _lf_pinbox_free (LF_PINS *pins, void *addr)
static int harvest_pins (LF_PINS *el, struct st_harvester *hv)
static int match_pins (LF_PINS *el, void *addr)
static void alloc_free (uchar *first, uchar volatile *last, LF_ALLOCATOR *allocator)
void lf_alloc_init (LF_ALLOCATOR *allocator, uint size, uint free_ptr_offset)
void lf_alloc_destroy (LF_ALLOCATOR *allocator)
void * _lf_alloc_new (LF_PINS *pins)
uint lf_alloc_pool_count (LF_ALLOCATOR *allocator)
Macro Definition Documentation
add_to_purgatory
#define add_to_purgatory (PINS, ADDR)
Value:
  do                                                                    \
  {                                                                     \
    *(void **)((char *)(ADDR)+(PINS)->pinbox->free_ptr_offset)=         \
      (PINS)->purgatory;                                                \
    (PINS)->purgatory= (ADDR);                                          \
    (PINS)->purgatory_count++;                                          \
  } while (0)
Definition at line 246 of file lf_alloc-pin.c.
anext_node
#define anext_node (X) next_node(&allocator->pinbox, (X))
Definition at line 323 of file lf_alloc-pin.c.
available_stack_size
#define available_stack_size (CUR, END) (long) ((char*)(END) - (char*)(CUR))
Definition at line 319 of file lf_alloc-pin.c.
LF_PINBOX_MAX_PINS
#define LF_PINBOX_MAX_PINS 65536
Definition at line 106 of file lf_alloc-pin.c.
next_node
#define next_node (P, X) (*((uchar * volatile *)(((uchar *)(X)) + (P)->free_ptr_offset)))
Definition at line 322 of file lf_alloc-pin.c.
Function Documentation
_lf_alloc_new()
void* _lf_alloc_new (LF_PINS * pins)
Definition at line 485 of file lf_alloc-pin.c.
 {
   LF_ALLOCATOR *allocator= (LF_ALLOCATOR *)(pins->pinbox->free_func_arg);
   uchar *node;
   for (;;)
   {
     do
     {
       node= allocator->top;
       _lf_pin(pins, 0, node);
     } while (node != allocator->top && LF_BACKOFF);
     if (!node)
     {
       node= (void *)my_malloc(allocator->element_size, MYF(MY_WME));
 #ifdef MY_LF_EXTRA_DEBUG
       if (likely(node != 0))
         my_atomic_add32(&allocator->mallocs, 1);
 #endif
       break;
     }
     if (my_atomic_casptr((void **)(char *)&allocator->top,
                          (void *)&node, anext_node(node)))
       break;
   }
   _lf_unpin(pins, 0);
   return node;
 }
References _lf_pin, _lf_unpin, anext_node, LF_PINBOX::free_func_arg, LF_ALLOCATOR, LF_BACKOFF, likely, my_malloc(), MY_WME, MYF, LF_PINS::pinbox, and pins.
Referenced by lf_hash_insert().
_lf_pinbox_free()
void _lf_pinbox_free (LF_PINS * pins, void * addr)
Definition at line 262 of file lf_alloc-pin.c.
 {
   add_to_purgatory(pins, addr);
   if (pins->purgatory_count % LF_PURGATORY_SIZE)
     _lf_pinbox_real_free(pins);
 }
References _lf_pinbox_real_free(), add_to_purgatory, LF_PURGATORY_SIZE, pins, and LF_PINS::purgatory_count.
_lf_pinbox_get_pins()
LF_PINS* _lf_pinbox_get_pins (LF_PINBOX * pinbox)
Definition at line 147 of file lf_alloc-pin.c.
 {
   uint32 pins, next, top_ver;
   LF_PINS *el;
   /*
     We have an array of max. 64k elements.
     The highest index currently allocated is pinbox->pins_in_array.
     Freed elements are in a lifo stack, pinstack_top_ver.
     pinstack_top_ver is 32 bits; 16 low bits are the index in the
     array, to the first element of the list. 16 high bits are a version
     (every time the 16 low bits are updated, the 16 high bits are
     incremented). Versioniong prevents the ABA problem.
   */
   top_ver= pinbox->pinstack_top_ver;
   do
   {
     if (!(pins= top_ver % LF_PINBOX_MAX_PINS))
     {
       /* the stack of free elements is empty */
       pins= my_atomic_add32((int32 volatile*) &pinbox->pins_in_array, 1)+1;
       if (unlikely(pins >= LF_PINBOX_MAX_PINS))
         return 0;
       /*
         note that the first allocated element has index 1 (pins==1).
         index 0 is reserved to mean "NULL pointer"
       */
       el= (LF_PINS *)_lf_dynarray_lvalue(&pinbox->pinarray, pins);
       if (unlikely(!el))
         return 0;
       break;
     }
     el= (LF_PINS *)_lf_dynarray_value(&pinbox->pinarray, pins);
     next= el->link;
   } while (!my_atomic_cas32((int32 volatile*) &pinbox->pinstack_top_ver,
                             (int32*) &top_ver,
                             top_ver-pins+next+LF_PINBOX_MAX_PINS));
   /*
     set el->link to the index of el in the dynarray (el->link has two usages:
     - if element is allocated, it's its own index
     - if element is free, it's its next element in the free stack
   */
   el->link= pins;
   el->purgatory_count= 0;
   el->pinbox= pinbox;
   el->stack_ends_here= & my_thread_var->stack_ends_here;
   return el;
 }
References _lf_dynarray_lvalue(), _lf_dynarray_value(), LF_PINBOX_MAX_PINS, LF_PINS::link, my_thread_var, next(), LF_PINBOX::pinarray, LF_PINS::pinbox, pins, LF_PINBOX::pins_in_array, LF_PINBOX::pinstack_top_ver, LF_PINS::purgatory_count, LF_PINS::stack_ends_here, and unlikely.
_lf_pinbox_put_pins()
void _lf_pinbox_put_pins (LF_PINS * pins)
Definition at line 203 of file lf_alloc-pin.c.
 {
   LF_PINBOX *pinbox= pins->pinbox;
   uint32 top_ver, nr;
   nr= pins->link;
 #ifdef MY_LF_EXTRA_DEBUG
   {
     int i;
     for (i= 0; i < LF_PINBOX_PINS; i++)
       DBUG_ASSERT(pins->pin[i] == 0);
   }
 #endif
   /*
     XXX this will deadlock if other threads will wait for
     the caller to do something after _lf_pinbox_put_pins(),
     and they would have pinned addresses that the caller wants to free.
     Thus: only free pins when all work is done and nobody can wait for you!!!
   */
   while (pins->purgatory_count)
   {
     _lf_pinbox_real_free(pins);
     if (pins->purgatory_count)
     {
       my_atomic_rwlock_wrunlock(&pins->pinbox->pinarray.lock);
       pthread_yield();
       my_atomic_rwlock_wrlock(&pins->pinbox->pinarray.lock);
     }
   }
   top_ver= pinbox->pinstack_top_ver;
   do
   {
     pins->link= top_ver % LF_PINBOX_MAX_PINS;
   } while (!my_atomic_cas32((int32 volatile*) &pinbox->pinstack_top_ver,
                             (int32*) &top_ver,
                             top_ver-pins->link+nr+LF_PINBOX_MAX_PINS));
   return;
 }
References _lf_pinbox_real_free(), DBUG_ASSERT, LF_PINBOX_MAX_PINS, LF_PINBOX_PINS, LF_PINS::link, LF_DYNARRAY::lock, my_atomic_rwlock_wrlock, my_atomic_rwlock_wrunlock, LF_PINS::pin, LF_PINBOX::pinarray, LF_PINS::pinbox, pins, LF_PINBOX::pinstack_top_ver, and LF_PINS::purgatory_count.
_lf_pinbox_real_free()
static void _lf_pinbox_real_free (LF_PINS * pins) static
Definition at line 328 of file lf_alloc-pin.c.
 {
   int npins, alloca_size;
   void *list, **addr;
   void *first= NULL, *last= NULL;
   LF_PINBOX *pinbox= pins->pinbox;
   npins= pinbox->pins_in_array+1;
 #ifdef HAVE_ALLOCA
   alloca_size= sizeof(void *)*LF_PINBOX_PINS*npins;
   /* create a sorted list of pinned addresses, to speed up searches */
   if (available_stack_size(&pinbox, *pins->stack_ends_here) > alloca_size)
   {
     struct st_harvester hv;
     addr= (void **) alloca(alloca_size);
     hv.granary= addr;
     hv.npins= npins;
     /* scan the dynarray and accumulate all pinned addresses */
     _lf_dynarray_iterate(&pinbox->pinarray,
                          (lf_dynarray_func)harvest_pins, &hv);
     npins= hv.granary-addr;
     /* and sort them */
     if (npins)
       qsort(addr, npins, sizeof(void *), (qsort_cmp)ptr_cmp);
   }
   else
 #endif
     addr= 0;
   list= pins->purgatory;
   pins->purgatory= 0;
   pins->purgatory_count= 0;
   while (list)
   {
     void *cur= list;
     list= *(void **)((char *)cur+pinbox->free_ptr_offset);
     if (npins)
     {
       if (addr) /* use binary search */
       {
         void **a, **b, **c;
         for (a= addr, b= addr+npins-1, c= a+(b-a)/2; (b-a) > 1; c= a+(b-a)/2)
           if (cur == *c)
             a= b= c;
           else if (cur > *c)
             a= c;
           else
             b= c;
         if (cur == *a || cur == *b)
           goto found;
       }
       else /* no alloca - no cookie. linear search here */
       {
         if (_lf_dynarray_iterate(&pinbox->pinarray,
                                  (lf_dynarray_func)match_pins, cur))
           goto found;
       }
     }
     /* not pinned - freeing */
     if (last)
       last= next_node(pinbox, last)= (uchar *)cur;
     else
       first= last= (uchar *)cur;
     continue;
 found:
     /* pinned - keeping */
     add_to_purgatory(pins, cur);
   }
   if (last)
     pinbox->free_func(first, last, pinbox->free_func_arg);
 }
References _lf_dynarray_iterate(), mpq::a, add_to_purgatory, available_stack_size, b, mpq::c, detail::first(), LF_PINBOX::free_func, LF_PINBOX::free_func_arg, LF_PINBOX::free_ptr_offset, st_harvester::granary, harvest_pins(), LF_PINBOX_PINS, list(), match_pins(), next_node, st_harvester::npins, NULL, LF_PINBOX::pinarray, LF_PINS::pinbox, pins, LF_PINBOX::pins_in_array, ptr_cmp(), LF_PINS::purgatory, LF_PINS::purgatory_count, qsort_cmp, and LF_PINS::stack_ends_here.
Referenced by _lf_pinbox_free(), and _lf_pinbox_put_pins().
alloc_free()
static void alloc_free (uchar * first, uchar volatile * last, LF_ALLOCATOR * allocator) static
Definition at line 414 of file lf_alloc-pin.c.
 {
   /*
     we need a union here to access type-punned pointer reliably.
     otherwise gcc -fstrict-aliasing will not see 'tmp' changed in the loop
   */
   union { uchar * node; void *ptr; } tmp;
   tmp.node= allocator->top;
   do
   {
     anext_node(last)= tmp.node;
   } while (!my_atomic_casptr((void **)(char *)&allocator->top,
                              (void **)&tmp.ptr, first) && LF_BACKOFF);
 }
References anext_node, detail::first(), LF_BACKOFF, and ptr().
Referenced by lf_alloc_init().
harvest_pins()
static int harvest_pins (LF_PINS * el, struct st_harvester * hv) static
Definition at line 278 of file lf_alloc-pin.c.
 {
   int i;
   LF_PINS *el_end= el+min(hv->npins, LF_DYNARRAY_LEVEL_LENGTH);
   for (; el < el_end; el++)
   {
     for (i= 0; i < LF_PINBOX_PINS; i++)
     {
       void *p= el->pin[i];
       if (p)
         *hv->granary++= p;
     }
   }
   /*
     hv->npins may become negative below, but it means that
     we're on the last dynarray page and harvest_pins() won't be
     called again. We don't bother to make hv->npins() correct
     (that is 0) in this case.
   */
   hv->npins-= LF_DYNARRAY_LEVEL_LENGTH;
   return 0;
 }
References st_harvester::granary, LF_DYNARRAY_LEVEL_LENGTH, LF_PINBOX_PINS, min, st_harvester::npins, and LF_PINS::pin.
Referenced by _lf_pinbox_real_free().
lf_alloc_destroy()
void lf_alloc_destroy (LF_ALLOCATOR * allocator)
Definition at line 465 of file lf_alloc-pin.c.
 {
   uchar *node= allocator->top;
   while (node)
   {
     uchar *tmp= anext_node(node);
     my_free(node);
     node= tmp;
   }
   lf_pinbox_destroy(&allocator->pinbox);
   allocator->top= 0;
 }
References anext_node, lf_pinbox_destroy(), and my_free().
Referenced by lf_hash_destroy().
lf_alloc_init()
void lf_alloc_init (LF_ALLOCATOR * allocator, uint size, uint free_ptr_offset)
Definition at line 444 of file lf_alloc-pin.c.
 {
   lf_pinbox_init(&allocator->pinbox, free_ptr_offset,
                  (lf_pinbox_free_func *)alloc_free, allocator);
   allocator->top= 0;
   allocator->mallocs= 0;
   allocator->element_size= size;
   DBUG_ASSERT(size >= sizeof(void*) + free_ptr_offset);
 }
References alloc_free(), DBUG_ASSERT, and lf_pinbox_init().
Referenced by lf_hash_init().
lf_alloc_pool_count()
uint lf_alloc_pool_count (LF_ALLOCATOR * allocator)
Definition at line 519 of file lf_alloc-pin.c.
 {
   uint i;
   uchar *node;
   for (node= allocator->top, i= 0; node; node= anext_node(node), i++)
     /* no op */;
   return i;
 }
References anext_node.
lf_pinbox_destroy()
void lf_pinbox_destroy (LF_PINBOX * pinbox)
Definition at line 127 of file lf_alloc-pin.c.
 {
   lf_dynarray_destroy(&pinbox->pinarray);
 }
References lf_dynarray_destroy(), and LF_PINBOX::pinarray.
Referenced by lf_alloc_destroy().
lf_pinbox_init()
void lf_pinbox_init (LF_PINBOX * pinbox, uint free_ptr_offset, lf_pinbox_free_func * free_func, void * free_func_arg)
Definition at line 114 of file lf_alloc-pin.c.
 {
   DBUG_ASSERT(free_ptr_offset % sizeof(void *) == 0);
   compile_time_assert(sizeof(LF_PINS) == 64);
   lf_dynarray_init(&pinbox->pinarray, sizeof(LF_PINS));
   pinbox->pinstack_top_ver= 0;
   pinbox->pins_in_array= 0;
   pinbox->free_ptr_offset= free_ptr_offset;
   pinbox->free_func= free_func;
   pinbox->free_func_arg= free_func_arg;
 }
References compile_time_assert, DBUG_ASSERT, LF_PINBOX::free_func, LF_PINBOX::free_func_arg, LF_PINBOX::free_ptr_offset, lf_dynarray_init(), LF_PINBOX::pinarray, LF_PINBOX::pins_in_array, and LF_PINBOX::pinstack_top_ver.
Referenced by lf_alloc_init().
match_pins()
static int match_pins (LF_PINS * el, void * addr) static
Definition at line 305 of file lf_alloc-pin.c.
 {
   int i;
   LF_PINS *el_end= el+LF_DYNARRAY_LEVEL_LENGTH;
   for (; el < el_end; el++)
     for (i= 0; i < LF_PINBOX_PINS; i++)
       if (el->pin[i] == addr)
         return 1;
   return 0;
 }
References LF_DYNARRAY_LEVEL_LENGTH, LF_PINBOX_PINS, and LF_PINS::pin.
Referenced by _lf_pinbox_real_free().
ptr_cmp()
static int ptr_cmp (void ** a, void ** b) static
Definition at line 241 of file lf_alloc-pin.c.
 {
   return *a < *b ? -1 : *a == *b ? 0 : 1;
 }
References mpq::a, and b.
Referenced by _lf_pinbox_real_free(), and my_qsort().