Azerotcore-wotlk: npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI Struct Reference
npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI Struct Reference
Public Member Functions
npc_av_marshal_or_warmasterAI (Creature *creature)
void Reset () override
void JustRespawned () override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
EventMap events
bool _hasAura
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 85 of file alterac_valley.cpp.
Constructor & Destructor Documentation
npc_av_marshal_or_warmasterAI()
npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI::npc_av_marshal_or_warmasterAI (Creature * creature) inline
Definition at line 87 of file alterac_valley.cpp.
 : ScriptedAI(creature) { }
Member Function Documentation
JustRespawned()
void npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI::JustRespawned () inline override virtual
Reimplemented from CreatureAI.
Definition at line 102 of file alterac_valley.cpp.
         {
             Reset();
         }
References Reset().
Reset()
void npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 89 of file alterac_valley.cpp.
         {
             events.Reset();
             events.ScheduleEvent(EVENT_CHARGE_TARGET, urand(2 * IN_MILLISECONDS, 12 * IN_MILLISECONDS));
             events.ScheduleEvent(EVENT_CLEAVE, urand(1 * IN_MILLISECONDS, 11 * IN_MILLISECONDS));
             events.ScheduleEvent(EVENT_DEMORALIZING_SHOUT, 2000);
             events.ScheduleEvent(EVENT_WHIRLWIND, urand(5 * IN_MILLISECONDS, 20 * IN_MILLISECONDS));
             events.ScheduleEvent(EVENT_ENRAGE, urand(5 * IN_MILLISECONDS, 20 * IN_MILLISECONDS));
             events.ScheduleEvent(EVENT_CHECK_RESET, 5000);
             _hasAura = false;
         }
References _hasAura, EVENT_CHARGE_TARGET, EVENT_CHECK_RESET, EVENT_CLEAVE, EVENT_DEMORALIZING_SHOUT, EVENT_ENRAGE, EVENT_WHIRLWIND, IN_MILLISECONDS, and urand().
Referenced by JustRespawned().
UpdateAI()
void npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 107 of file alterac_valley.cpp.
         {
             // I have a feeling this isn't blizzlike, but owell, I'm only passing by and cleaning up.
             if (!_hasAura)
             {
                 for (uint8 i = 0; i < MAX_SPELL_PAIRS; ++i)
                     if (_auraPairs[i].npcEntry == me->GetEntry())
                         DoCast(me, _auraPairs[i].spellId);
                 _hasAura = true;
             }
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             while (uint32 eventId = events.ExecuteEvent())
             {
                 switch (eventId)
                 {
                     case EVENT_CHARGE_TARGET:
                         DoCastVictim(SPELL_CHARGE);
                         events.ScheduleEvent(EVENT_CHARGE, urand(10 * IN_MILLISECONDS, 25 * IN_MILLISECONDS));
                         break;
                     case EVENT_CLEAVE:
                         DoCastVictim(SPELL_CLEAVE);
                         events.ScheduleEvent(EVENT_CLEAVE, urand(10 * IN_MILLISECONDS, 16 * IN_MILLISECONDS));
                         break;
                     case EVENT_DEMORALIZING_SHOUT:
                         DoCast(me, SPELL_DEMORALIZING_SHOUT);
                         events.ScheduleEvent(EVENT_DEMORALIZING_SHOUT, urand(10 * IN_MILLISECONDS, 15 * IN_MILLISECONDS));
                         break;
                     case EVENT_WHIRLWIND:
                         DoCast(me, SPELL_WHIRLWIND);
                         events.ScheduleEvent(EVENT_WHIRLWIND, urand(10 * IN_MILLISECONDS, 25 * IN_MILLISECONDS));
                         break;
                     case EVENT_ENRAGE:
                         DoCast(me, SPELL_ENRAGE);
                         events.ScheduleEvent(EVENT_ENRAGE, urand(10 * IN_MILLISECONDS, 30 * IN_MILLISECONDS));
                         break;
                     case EVENT_CHECK_RESET:
{
                             Position const& _homePosition = me->GetHomePosition();
                             if (me->GetDistance2d(_homePosition.GetPositionX(), _homePosition.GetPositionY()) > 50.0f)
{
                                 EnterEvadeMode();
                                 return;
                             }
                             events.ScheduleEvent(EVENT_CHECK_RESET, 5000);
                             break;
                         }
                 }
             }
             DoMeleeAttackIfReady();
         }
References _auraPairs, _hasAura, diff(), UnitAI::DoCast(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), CreatureAI::EnterEvadeMode(), EVENT_CHARGE, EVENT_CHARGE_TARGET, EVENT_CHECK_RESET, EVENT_CLEAVE, EVENT_DEMORALIZING_SHOUT, EVENT_ENRAGE, EVENT_WHIRLWIND, WorldObject::GetDistance2d(), Object::GetEntry(), Creature::GetHomePosition(), Position::GetPositionX(), Position::GetPositionY(), Unit::HasUnitState(), IN_MILLISECONDS, MAX_SPELL_PAIRS, ScriptedAI::me, SPELL_CHARGE, SPELL_CLEAVE, SPELL_DEMORALIZING_SHOUT, SPELL_ENRAGE, SPELL_WHIRLWIND, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
_hasAura
bool npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI::_hasAura private
Definition at line 170 of file alterac_valley.cpp.
Referenced by Reset(), and UpdateAI().
events
EventMap npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI::events private
Definition at line 169 of file alterac_valley.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/AlteracValley/alterac_valley.cpp