Azerotcore-wotlk: G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Handle Class Reference
G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Handle Class Reference
#include <KDTree.h>
Public Member Functions
Handle ()
Handle (const T &v)
bool operator== (const Handle &other) const
size_t hashCode () const
Public Attributes
AABox bounds
Vector3 center
T value
Detailed Description
template<class T, class BoundsFunc = BoundsTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>>
class G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Handle
Wrapper for a value that includes a cache of its bounds. Except for the test value used in a set-query operation, there is only ever one instance of the handle associated with any value and the memberTable and Nodes maintain pointers to that heap-allocated value.
Definition at line 203 of file KDTree.h.
Constructor & Destructor Documentation
Handle() [1/2]
template<class T , class BoundsFunc = BoundsTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Handle::Handle () inline
Definition at line 216 of file KDTree.h.
 {}
Handle() [2/2]
template<class T , class BoundsFunc = BoundsTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Handle::Handle (const T & v) inline
Definition at line 218 of file KDTree.h.
                                   : value(v) {
             BoundsFunc::getBounds(v, bounds);
             bounds = bounds.intersect(AABox::large());
             center = bounds.center();
         }
References G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Handle::bounds, G3D::AABox::center(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Handle::center, G3D::AABox::intersect(), and G3D::AABox::large().
Member Function Documentation
hashCode()
template<class T , class BoundsFunc = BoundsTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> size_t G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Handle::hashCode () const inline
Definition at line 228 of file KDTree.h.
{
             return HashFunc::hashCode(value);
         }
References G3D::hashCode().
operator==()
template<class T , class BoundsFunc = BoundsTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> bool G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Handle::operator== (const Handle & other) const inline
Definition at line 224 of file KDTree.h.
{
             return EqualsFunc::equals(value, other.value);
         }
References G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Handle::value.
Member Data Documentation
bounds
template<class T , class BoundsFunc = BoundsTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> AABox G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Handle::bounds
The bounds of each object are constrained to AABox::large
Definition at line 206 of file KDTree.h.
Referenced by G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Handle::Handle(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::insert(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::makeNode(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::BoundsComparator::operator()(), and G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Comparator::operator()().
center
template<class T , class BoundsFunc = BoundsTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> Vector3 G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Handle::center
Center of bounds. We cache this value to avoid recomputing it during the median sort, and because MSVC 6 std::sort goes into an infinite loop if we compute the midpoint on the fly (possibly a floating point roundoff issue, where B<A and A<B both are true).
Definition at line 212 of file KDTree.h.
Referenced by G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Handle::Handle(), and G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::CenterComparator::operator()().
value
template<class T , class BoundsFunc = BoundsTrait<T>, class HashFunc = HashTrait<T>, class EqualsFunc = EqualsTrait<T>> T G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Handle::value
Definition at line 214 of file KDTree.h.
Referenced by G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Handle::operator==().
The documentation for this class was generated from the following file:
deps/g3dlite/include/G3D/KDTree.h