Azerotcore-wotlk: npc_xt002_heart::npc_xt002_heartAI Struct Reference
npc_xt002_heart::npc_xt002_heartAI Struct Reference
Public Member Functions
npc_xt002_heartAI (Creature *pCreature)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void JustSummoned (Creature *cr) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void SummonPiles ()
void DoAction (int32 param) override
void SendEnergyToCorner ()
void SpellHitTarget (Unit *target, const SpellInfo *spellInfo) override
void JustDied (Unit *) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from PassiveAI
PassiveAI (Creature *c)
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void EnterCombat (Unit *)
virtual void KilledUnit (Unit *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void Reset ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
SummonList summons
uint32 _damageDone
uint32 _timerSpawn
uint8 _spawnSelection
uint8 _pummelerCount
Additional Inherited Members
Static Public Member Functions inherited from PassiveAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 420 of file boss_xt002.cpp.
Constructor & Destructor Documentation
npc_xt002_heartAI()
npc_xt002_heart::npc_xt002_heartAI::npc_xt002_heartAI (Creature * pCreature) inline
Definition at line 422 of file boss_xt002.cpp.
                                                : PassiveAI(pCreature), summons(me)
         {
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE);
         }
References CreatureAI::me, Object::SetFlag(), UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
Member Function Documentation
AttackStart()
void npc_xt002_heart::npc_xt002_heartAI::AttackStart (Unit *) inline override virtual
Reimplemented from PassiveAI.
Definition at line 435 of file boss_xt002.cpp.
 { }
DamageTaken()
void npc_xt002_heart::npc_xt002_heartAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from UnitAI.
Definition at line 443 of file boss_xt002.cpp.
         {
             _damageDone += damage;
         }
References _damageDone.
DoAction()
void npc_xt002_heart::npc_xt002_heartAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 456 of file boss_xt002.cpp.
         {
             if (param == ACTION_AWAKEN_HEART)
             {
                 _pummelerCount = 0;
                 _spawnSelection = 0;
                 _damageDone = 0;
                 _timerSpawn = 0;
                 me->SetHealth(me->GetMaxHealth());
                 me->CastSpell(me, SPELL_HEART_OVERLOAD, true);
                 me->CastSpell(me, SPELL_EXPOSED_HEART, false);    // Channeled
                 me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE);
                 if (!summons.HasEntry(NPC_PILE_TRIGGER))
                     SummonPiles();
             }
             else if (param == ACTION_HIDE_HEART)
             {
                 if (Creature* pXT002 = ObjectAccessor::GetCreature(*me, me->GetInstanceScript()->GetGuidData(TYPE_XT002)))
                     if (pXT002->AI())
                     {
                         pXT002->AI()->DoAction(_damageDone);
                         _damageDone = 0;
                     }
                 me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE);
             }
         }
References _damageDone, _pummelerCount, _spawnSelection, _timerSpawn, ACTION_AWAKEN_HEART, ACTION_HIDE_HEART, Unit::CastSpell(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), Unit::GetMaxHealth(), SummonList::HasEntry(), CreatureAI::me, NPC_PILE_TRIGGER, Object::RemoveFlag(), Object::SetFlag(), Unit::SetHealth(), SPELL_EXPOSED_HEART, SPELL_HEART_OVERLOAD, SummonPiles(), summons, TYPE_XT002, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
JustDied()
void npc_xt002_heart::npc_xt002_heartAI::JustDied (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 536 of file boss_xt002.cpp.
         {
             me->SetVisible(false);
             if (me->GetInstanceScript())
                 if (Creature* XT002 = ObjectAccessor::GetCreature(*me, me->GetInstanceScript()->GetGuidData(TYPE_XT002)))
                     if (XT002->AI())
                         XT002->AI()->DoAction(ACTION_HEART_BROKEN);
         }
References ACTION_HEART_BROKEN, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), CreatureAI::me, Unit::SetVisible(), and TYPE_XT002.
JustSummoned()
void npc_xt002_heart::npc_xt002_heartAI::JustSummoned (Creature * cr) inline override virtual
Reimplemented from CreatureAI.
Definition at line 436 of file boss_xt002.cpp.
         {
             summons.Summon(cr);
             if (Unit* owner = me->GetVehicleBase())
                 if (owner->GetTypeId() == TYPEID_UNIT)
                     owner->ToCreature()->AI()->JustSummoned(cr);
         }
References Unit::GetVehicleBase(), CreatureAI::me, SummonList::Summon(), summons, and TYPEID_UNIT.
MoveInLineOfSight()
void npc_xt002_heart::npc_xt002_heartAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from PassiveAI.
Definition at line 434 of file boss_xt002.cpp.
 { }
SendEnergyToCorner()
void npc_xt002_heart::npc_xt002_heartAI::SendEnergyToCorner () inline
Definition at line 484 of file boss_xt002.cpp.
         {
             Unit* pile = nullptr;
             uint8 num = urand(1, 4);
             for (SummonList::const_iterator itr = summons.begin(); itr != summons.end(); ++itr)
                 if (Creature* summon = ObjectAccessor::GetCreature(*me, *itr))
                     if (summon->GetEntry() == NPC_PILE_TRIGGER)
                     {
                         pile = summon;
                         if ((--num) == 0)
                             break;
                     }
             if (pile)
                 me->CastSpell(pile, SPELL_ENERGY_ORB, true);
         }
References SummonList::begin(), Unit::CastSpell(), SummonList::end(), ObjectAccessor::GetCreature(), CreatureAI::me, NPC_PILE_TRIGGER, SPELL_ENERGY_ORB, summons, and urand().
Referenced by UpdateAI().
SpellHitTarget()
void npc_xt002_heart::npc_xt002_heartAI::SpellHitTarget (Unit * target, const SpellInfo * spellInfo) inline override virtual
Reimplemented from CreatureAI.
Definition at line 501 of file boss_xt002.cpp.
         {
             // spawn not-so-random robots
             if (spellInfo->Id == SPELL_ENERGY_ORB_TRIGGER && target->GetEntry() == NPC_PILE_TRIGGER)
                 switch (_spawnSelection)
                 {
                     case 0:
                         for (uint8 i = 0; i < 5; ++i)
                             me->SummonCreature(NPC_XS013_SCRAPBOT, target->GetPositionX() + irand(-3, 3), target->GetPositionY() + irand(-3, 3), target->GetPositionZ() + 2, 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 1000);
                         _spawnSelection++;
                         break;
                     case 1:
                         me->SummonCreature(NPC_XE321_BOOMBOT, target->GetPositionX(), target->GetPositionY(), target->GetPositionZ() + 2, 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 5000);
                         _spawnSelection++;
                         break;
                     case 2:
                         for (uint8 i = 0; i < 5; ++i)
                             me->SummonCreature(NPC_XS013_SCRAPBOT, target->GetPositionX() + irand(-3, 3), target->GetPositionY() + irand(-3, 3), target->GetPositionZ() + 2, 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 1000);
                         _spawnSelection++;
                         break;
                     case 3:
                         if(_pummelerCount < 2)
                             me->SummonCreature(NPC_XM024_PUMMELLER, target->GetPositionX(), target->GetPositionY(), target->GetPositionZ() + 2, 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 5000);
                         _pummelerCount++;
                         _spawnSelection++;
                         break;
                     case 4:
                         for (uint8 i = 0; i < 5; ++i)
                             me->SummonCreature(NPC_XS013_SCRAPBOT, target->GetPositionX() + irand(-3, 3), target->GetPositionY() + irand(-3, 3), target->GetPositionZ() + 2, 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 1000);
                         _spawnSelection = 0;
                         break;
                 }
         }
References _pummelerCount, _spawnSelection, Object::GetEntry(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), SpellInfo::Id, irand(), CreatureAI::me, NPC_PILE_TRIGGER, NPC_XE321_BOOMBOT, NPC_XM024_PUMMELLER, NPC_XS013_SCRAPBOT, SPELL_ENERGY_ORB_TRIGGER, WorldObject::SummonCreature(), and TEMPSUMMON_CORPSE_TIMED_DESPAWN.
SummonPiles()
void npc_xt002_heart::npc_xt002_heartAI::SummonPiles () inline
Definition at line 448 of file boss_xt002.cpp.
         {
             me->SummonCreature(NPC_PILE_TRIGGER, 893.290f, 66.820f, 409.81f, 4.2f);
             me->SummonCreature(NPC_PILE_TRIGGER, 898.099f, -88.9115f, 409.887f, 2.23402f);
             me->SummonCreature(NPC_PILE_TRIGGER, 793.096f, -95.158f,  409.887f, 0.855211f);
             me->SummonCreature(NPC_PILE_TRIGGER, 794.600f, 59.660f, 409.82f, 5.34f);
         }
References CreatureAI::me, NPC_PILE_TRIGGER, and WorldObject::SummonCreature().
Referenced by DoAction().
UpdateAI()
void npc_xt002_heart::npc_xt002_heartAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from PassiveAI.
Definition at line 545 of file boss_xt002.cpp.
         {
             if (!me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE))
             {
                 _timerSpawn += diff;
                 if (_timerSpawn >= 1900)
                 {
                     SendEnergyToCorner();
                     _timerSpawn -= 1900;
                 }
             }
         }
References _timerSpawn, Object::HasFlag(), CreatureAI::me, SendEnergyToCorner(), UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
Member Data Documentation
_damageDone
uint32 npc_xt002_heart::npc_xt002_heartAI::_damageDone
Definition at line 428 of file boss_xt002.cpp.
Referenced by DamageTaken(), and DoAction().
_pummelerCount
uint8 npc_xt002_heart::npc_xt002_heartAI::_pummelerCount
Definition at line 432 of file boss_xt002.cpp.
Referenced by DoAction(), and SpellHitTarget().
_spawnSelection
uint8 npc_xt002_heart::npc_xt002_heartAI::_spawnSelection
Definition at line 431 of file boss_xt002.cpp.
Referenced by DoAction(), and SpellHitTarget().
_timerSpawn
uint32 npc_xt002_heart::npc_xt002_heartAI::_timerSpawn
Definition at line 429 of file boss_xt002.cpp.
Referenced by DoAction(), and UpdateAI().
summons
SummonList npc_xt002_heart::npc_xt002_heartAI::summons
Definition at line 427 of file boss_xt002.cpp.
Referenced by DoAction(), JustSummoned(), and SendEnergyToCorner().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_xt002.cpp