Azerotcore-wotlk: achievement_shadowdodger Class Reference
achievement_shadowdodger Class Reference
Public Member Functions
achievement_shadowdodger ()
bool OnCheck (Player *, Unit *target, uint32) override
Public Member Functions inherited from AchievementCriteriaScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AchievementCriteriaScript
AchievementCriteriaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 666 of file boss_general_vezax.cpp.
Constructor & Destructor Documentation
achievement_shadowdodger()
achievement_shadowdodger::achievement_shadowdodger () inline
Definition at line 669 of file boss_general_vezax.cpp.
 : AchievementCriteriaScript("achievement_shadowdodger") {}
Member Function Documentation
OnCheck()
bool achievement_shadowdodger::OnCheck (Player * , Unit * target, uint32) inline override virtual
Reimplemented from AchievementCriteriaScript.
Definition at line 671 of file boss_general_vezax.cpp.
     {
         return target && target->GetEntry() == NPC_VEZAX && target->GetTypeId() == TYPEID_UNIT && target->ToCreature()->AI()->GetData(2);
     }
References Creature::AI(), UnitAI::GetData(), Object::GetEntry(), Object::GetTypeId(), NPC_VEZAX, Object::ToCreature(), and TYPEID_UNIT.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_general_vezax.cpp