Azerotcore-wotlk: The World
The World
Files
file Weather.cpp
file Weather.h
file WeatherMgr.cpp
file WeatherMgr.h
file World.cpp
file World.h
Classes
struct WeatherSeasonChances
struct WeatherData
class Weather
Weather for one zone.
struct PetitionData
class World
The World.
Macros
#define WEATHER_SEASONS 4
#define WORLD_SLEEP_CONST 10
#define sWorld getWorldInstance()
Typedefs
typedef std::map< ObjectGuid::LowType, GlobalPlayerData > GlobalPlayerDataMap
typedef std::map< std::string, ObjectGuid::LowType > GlobalPlayerNameMap
Enumerations
enum WeatherState {
WEATHER_STATE_FINE = 0 , WEATHER_STATE_FOG = 1 , WEATHER_STATE_LIGHT_RAIN = 3 , WEATHER_STATE_MEDIUM_RAIN = 4 ,
WEATHER_STATE_HEAVY_RAIN = 5 , WEATHER_STATE_LIGHT_SNOW = 6 , WEATHER_STATE_MEDIUM_SNOW = 7 , WEATHER_STATE_HEAVY_SNOW = 8 ,
WEATHER_STATE_LIGHT_SANDSTORM = 22 , WEATHER_STATE_MEDIUM_SANDSTORM = 41 , WEATHER_STATE_HEAVY_SANDSTORM = 42 , WEATHER_STATE_THUNDERS = 86 ,
WEATHER_STATE_BLACKRAIN = 90 , WEATHER_STATE_BLACKSNOW = 106
}
enum ShutdownMask { SHUTDOWN_MASK_RESTART = 1 , SHUTDOWN_MASK_IDLE = 2 }
enum ShutdownExitCode { SHUTDOWN_EXIT_CODE = 0 , ERROR_EXIT_CODE = 1 , RESTART_EXIT_CODE = 2 }
enum WorldTimers {
WUPDATE_AUCTIONS , WUPDATE_WEATHERS , WUPDATE_UPTIME , WUPDATE_CORPSES ,
WUPDATE_EVENTS , WUPDATE_CLEANDB , WUPDATE_AUTOBROADCAST , WUPDATE_MAILBOXQUEUE ,
WUPDATE_PINGDB , WUPDATE_5_SECS , WUPDATE_WHO_LIST , WUPDATE_COUNT
}
Timers for different object refresh rates.
enum BillingPlanFlags {
SESSION_NONE = 0x00 , SESSION_UNUSED = 0x01 , SESSION_RECURRING_BILL = 0x02 , SESSION_FREE_TRIAL = 0x04 ,
SESSION_IGR = 0x08 , SESSION_USAGE = 0x10 , SESSION_TIME_MIXTURE = 0x20 , SESSION_RESTRICTED = 0x40 ,
SESSION_ENABLE_CAIS = 0x80
}
Can be used in SMSG_AUTH_RESPONSE packet.
enum RealmZone {
REALM_ZONE_UNKNOWN = 0 , REALM_ZONE_DEVELOPMENT = 1 , REALM_ZONE_UNITED_STATES = 2 , REALM_ZONE_OCEANIC = 3 ,
REALM_ZONE_LATIN_AMERICA = 4 , REALM_ZONE_TOURNAMENT_5 = 5 , REALM_ZONE_KOREA = 6 , REALM_ZONE_TOURNAMENT_7 = 7 ,
REALM_ZONE_ENGLISH = 8 , REALM_ZONE_GERMAN = 9 , REALM_ZONE_FRENCH = 10 , REALM_ZONE_SPANISH = 11 ,
REALM_ZONE_RUSSIAN = 12 , REALM_ZONE_TOURNAMENT_13 = 13 , REALM_ZONE_TAIWAN = 14 , REALM_ZONE_TOURNAMENT_15 = 15 ,
REALM_ZONE_CHINA = 16 , REALM_ZONE_CN1 = 17 , REALM_ZONE_CN2 = 18 , REALM_ZONE_CN3 = 19 ,
REALM_ZONE_CN4 = 20 , REALM_ZONE_CN5 = 21 , REALM_ZONE_CN6 = 22 , REALM_ZONE_CN7 = 23 ,
REALM_ZONE_CN8 = 24 , REALM_ZONE_TOURNAMENT_25 = 25 , REALM_ZONE_TEST_SERVER = 26 , REALM_ZONE_TOURNAMENT_27 = 27 ,
REALM_ZONE_QA_SERVER = 28 , REALM_ZONE_CN9 = 29 , REALM_ZONE_TEST_SERVER_2 = 30 , REALM_ZONE_CN10 = 31 ,
REALM_ZONE_CTC = 32 , REALM_ZONE_CNC = 33 , REALM_ZONE_CN1_4 = 34 , REALM_ZONE_CN2_6_9 = 35 ,
REALM_ZONE_CN3_7 = 36 , REALM_ZONE_CN5_8 = 37
}
enum WorldStates {
WS_ARENA_DISTRIBUTION_TIME = 20001 , WS_WEEKLY_QUEST_RESET_TIME = 20002 , WS_BG_DAILY_RESET_TIME = 20003 , WS_CLEANING_FLAGS = 20004 ,
WS_DAILY_QUEST_RESET_TIME = 20005 , WS_GUILD_DAILY_RESET_TIME = 20006 , WS_MONTHLY_QUEST_RESET_TIME = 20007 , WS_DAILY_CALENDAR_DELETION_OLD_EVENTS_TIME = 20008
}
enum GlobalPlayerUpdateMask {
PLAYER_UPDATE_DATA_LEVEL = 0x01 , PLAYER_UPDATE_DATA_RACE = 0x02 , PLAYER_UPDATE_DATA_CLASS = 0x04 , PLAYER_UPDATE_DATA_GENDER = 0x08 ,
PLAYER_UPDATE_DATA_NAME = 0x10
}
Functions
Weather::Weather (uint32 zone, WeatherData const *weatherChances)
Create the Weather object.
Weather::~Weather ()=default
bool Weather::Update (uint32 diff)
Launch a weather update.
bool Weather::ReGenerate ()
Calculate the new weather.
bool Weather::UpdateWeather ()
Send the new weather to all players in the zone.
void Weather::SendWeatherUpdateToPlayer (Player *player)
void Weather::SetWeather (WeatherType type, float grade)
Set the weather.
uint32 Weather::GetZone () const
For which zone is this weather?
uint32 Weather::GetScriptId () const
WeatherState Weather::GetWeatherState () const
Get the sound number associated with the current weather.
void WeatherMgr::LoadWeatherData ()
Weather * WeatherMgr::FindWeather (uint32 id)
Find a Weather object by the given zoneid.
Weather * WeatherMgr::AddWeather (uint32 zone_id)
Add a Weather object to the list.
void WeatherMgr::RemoveWeather (uint32 id)
Remove a Weather object for the given zoneid.
void WeatherMgr::SendFineWeatherUpdateToPlayer (Player *player)
void WeatherMgr::Update (uint32 diff)
std::unique_ptr< IWorld > & getWorldInstance ()
Variables
uint32 WeatherSeasonChances::rainChance
uint32 WeatherSeasonChances::snowChance
uint32 WeatherSeasonChances::stormChance
WeatherSeasonChances WeatherData::data [WEATHER_SEASONS]
uint32 WeatherData::ScriptId
uint32 Weather::m_zone
WeatherType Weather::m_type
float Weather::m_grade
IntervalTimer Weather::m_timer
WeatherData const * Weather::m_weatherChances
AC_GAME_API Realm realm
Detailed Description
Macro Definition Documentation
sWorld
#define sWorld getWorldInstance()
Definition at line 511 of file World.h.
WEATHER_SEASONS
#define WEATHER_SEASONS 4
Definition at line 31 of file Weather.h.
WORLD_SLEEP_CONST
#define WORLD_SLEEP_CONST 10
Definition at line 144 of file World.h.
Typedef Documentation
GlobalPlayerDataMap
typedef std::map<ObjectGuid::LowType, GlobalPlayerData> GlobalPlayerDataMap
Definition at line 155 of file World.h.
GlobalPlayerNameMap
typedef std::map<std::string, ObjectGuid::LowType> GlobalPlayerNameMap
Definition at line 156 of file World.h.
Enumeration Type Documentation
BillingPlanFlags
enum BillingPlanFlags
Can be used in SMSG_AUTH_RESPONSE packet.
Enumerator
SESSION_NONE
SESSION_UNUSED
SESSION_RECURRING_BILL
SESSION_FREE_TRIAL
SESSION_IGR
SESSION_USAGE
SESSION_TIME_MIXTURE
SESSION_RESTRICTED
SESSION_ENABLE_CAIS
Definition at line 77 of file World.h.
 {
     SESSION_NONE            = 0x00,
     SESSION_UNUSED          = 0x01,
     SESSION_RECURRING_BILL  = 0x02,
     SESSION_FREE_TRIAL      = 0x04,
     SESSION_IGR             = 0x08,
     SESSION_USAGE           = 0x10,
     SESSION_TIME_MIXTURE    = 0x20,
     SESSION_RESTRICTED      = 0x40,
     SESSION_ENABLE_CAIS     = 0x80,
 };
GlobalPlayerUpdateMask
enum GlobalPlayerUpdateMask
Enumerator
PLAYER_UPDATE_DATA_LEVEL
PLAYER_UPDATE_DATA_RACE
PLAYER_UPDATE_DATA_CLASS
PLAYER_UPDATE_DATA_GENDER
PLAYER_UPDATE_DATA_NAME
Definition at line 146 of file World.h.
 {
     PLAYER_UPDATE_DATA_LEVEL            = 0x01,
     PLAYER_UPDATE_DATA_RACE             = 0x02,
     PLAYER_UPDATE_DATA_CLASS            = 0x04,
     PLAYER_UPDATE_DATA_GENDER           = 0x08,
     PLAYER_UPDATE_DATA_NAME             = 0x10,
 };
RealmZone
enum RealmZone
Enumerator
REALM_ZONE_UNKNOWN
REALM_ZONE_DEVELOPMENT
REALM_ZONE_UNITED_STATES
REALM_ZONE_OCEANIC
REALM_ZONE_LATIN_AMERICA
REALM_ZONE_TOURNAMENT_5
REALM_ZONE_KOREA
REALM_ZONE_TOURNAMENT_7
REALM_ZONE_ENGLISH
REALM_ZONE_GERMAN
REALM_ZONE_FRENCH
REALM_ZONE_SPANISH
REALM_ZONE_RUSSIAN
REALM_ZONE_TOURNAMENT_13
REALM_ZONE_TAIWAN
REALM_ZONE_TOURNAMENT_15
REALM_ZONE_CHINA
REALM_ZONE_CN1
REALM_ZONE_CN2
REALM_ZONE_CN3
REALM_ZONE_CN4
REALM_ZONE_CN5
REALM_ZONE_CN6
REALM_ZONE_CN7
REALM_ZONE_CN8
REALM_ZONE_TOURNAMENT_25
REALM_ZONE_TEST_SERVER
REALM_ZONE_TOURNAMENT_27
REALM_ZONE_QA_SERVER
REALM_ZONE_CN9
REALM_ZONE_TEST_SERVER_2
REALM_ZONE_CN10
REALM_ZONE_CTC
REALM_ZONE_CNC
REALM_ZONE_CN1_4
REALM_ZONE_CN2_6_9
REALM_ZONE_CN3_7
REALM_ZONE_CN5_8
Definition at line 90 of file World.h.
 {
     REALM_ZONE_UNKNOWN       = 0,                           // any language
     REALM_ZONE_DEVELOPMENT   = 1,                           // any language
     REALM_ZONE_UNITED_STATES = 2,                           // extended-Latin
     REALM_ZONE_OCEANIC       = 3,                           // extended-Latin
     REALM_ZONE_LATIN_AMERICA = 4,                           // extended-Latin
     REALM_ZONE_TOURNAMENT_5  = 5,                           // basic-Latin at create, any at login
     REALM_ZONE_KOREA         = 6,                           // East-Asian
     REALM_ZONE_TOURNAMENT_7  = 7,                           // basic-Latin at create, any at login
     REALM_ZONE_ENGLISH       = 8,                           // extended-Latin
     REALM_ZONE_GERMAN        = 9,                           // extended-Latin
     REALM_ZONE_FRENCH        = 10,                          // extended-Latin
     REALM_ZONE_SPANISH       = 11,                          // extended-Latin
     REALM_ZONE_RUSSIAN       = 12,                          // Cyrillic
     REALM_ZONE_TOURNAMENT_13 = 13,                          // basic-Latin at create, any at login
     REALM_ZONE_TAIWAN        = 14,                          // East-Asian
     REALM_ZONE_TOURNAMENT_15 = 15,                          // basic-Latin at create, any at login
     REALM_ZONE_CHINA         = 16,                          // East-Asian
     REALM_ZONE_CN1           = 17,                          // basic-Latin at create, any at login
     REALM_ZONE_CN2           = 18,                          // basic-Latin at create, any at login
     REALM_ZONE_CN3           = 19,                          // basic-Latin at create, any at login
     REALM_ZONE_CN4           = 20,                          // basic-Latin at create, any at login
     REALM_ZONE_CN5           = 21,                          // basic-Latin at create, any at login
     REALM_ZONE_CN6           = 22,                          // basic-Latin at create, any at login
     REALM_ZONE_CN7           = 23,                          // basic-Latin at create, any at login
     REALM_ZONE_CN8           = 24,                          // basic-Latin at create, any at login
     REALM_ZONE_TOURNAMENT_25 = 25,                          // basic-Latin at create, any at login
     REALM_ZONE_TEST_SERVER   = 26,                          // any language
     REALM_ZONE_TOURNAMENT_27 = 27,                          // basic-Latin at create, any at login
     REALM_ZONE_QA_SERVER     = 28,                          // any language
     REALM_ZONE_CN9           = 29,                          // basic-Latin at create, any at login
     REALM_ZONE_TEST_SERVER_2 = 30,                          // any language
     REALM_ZONE_CN10          = 31,                          // basic-Latin at create, any at login
     REALM_ZONE_CTC           = 32,
     REALM_ZONE_CNC           = 33,
     REALM_ZONE_CN1_4         = 34,                          // basic-Latin at create, any at login
     REALM_ZONE_CN2_6_9       = 35,                          // basic-Latin at create, any at login
     REALM_ZONE_CN3_7         = 36,                          // basic-Latin at create, any at login
     REALM_ZONE_CN5_8         = 37                           // basic-Latin at create, any at login
 };
ShutdownExitCode
enum ShutdownExitCode
Enumerator
SHUTDOWN_EXIT_CODE
ERROR_EXIT_CODE
RESTART_EXIT_CODE
Definition at line 52 of file World.h.
 {
     SHUTDOWN_EXIT_CODE = 0,
     ERROR_EXIT_CODE    = 1,
     RESTART_EXIT_CODE  = 2,
 };
ShutdownMask
enum ShutdownMask
Enumerator
SHUTDOWN_MASK_RESTART
SHUTDOWN_MASK_IDLE
Definition at line 46 of file World.h.
 {
     SHUTDOWN_MASK_RESTART = 1,
     SHUTDOWN_MASK_IDLE    = 2,
 };
WeatherState
enum WeatherState
Enumerator
WEATHER_STATE_FINE
WEATHER_STATE_FOG
WEATHER_STATE_LIGHT_RAIN
WEATHER_STATE_MEDIUM_RAIN
WEATHER_STATE_HEAVY_RAIN
WEATHER_STATE_LIGHT_SNOW
WEATHER_STATE_MEDIUM_SNOW
WEATHER_STATE_HEAVY_SNOW
WEATHER_STATE_LIGHT_SANDSTORM
WEATHER_STATE_MEDIUM_SANDSTORM
WEATHER_STATE_HEAVY_SANDSTORM
WEATHER_STATE_THUNDERS
WEATHER_STATE_BLACKRAIN
WEATHER_STATE_BLACKSNOW
Definition at line 45 of file Weather.h.
 {
     WEATHER_STATE_FINE              = 0,
     WEATHER_STATE_FOG               = 1,
     WEATHER_STATE_LIGHT_RAIN        = 3,
     WEATHER_STATE_MEDIUM_RAIN       = 4,
     WEATHER_STATE_HEAVY_RAIN        = 5,
     WEATHER_STATE_LIGHT_SNOW        = 6,
     WEATHER_STATE_MEDIUM_SNOW       = 7,
     WEATHER_STATE_HEAVY_SNOW        = 8,
     WEATHER_STATE_LIGHT_SANDSTORM   = 22,
     WEATHER_STATE_MEDIUM_SANDSTORM  = 41,
     WEATHER_STATE_HEAVY_SANDSTORM   = 42,
     WEATHER_STATE_THUNDERS          = 86,
     WEATHER_STATE_BLACKRAIN         = 90,
     WEATHER_STATE_BLACKSNOW         = 106
 };
WorldStates
enum WorldStates
Enumerator
WS_ARENA_DISTRIBUTION_TIME
WS_WEEKLY_QUEST_RESET_TIME
WS_BG_DAILY_RESET_TIME
WS_CLEANING_FLAGS
WS_DAILY_QUEST_RESET_TIME
WS_GUILD_DAILY_RESET_TIME
WS_MONTHLY_QUEST_RESET_TIME
WS_DAILY_CALENDAR_DELETION_OLD_EVENTS_TIME
Definition at line 132 of file World.h.
 {
     WS_ARENA_DISTRIBUTION_TIME                 = 20001,                     // Next arena distribution time
     WS_WEEKLY_QUEST_RESET_TIME                 = 20002,                     // Next weekly reset time
     WS_BG_DAILY_RESET_TIME                     = 20003,                     // Next daily BG reset time
     WS_CLEANING_FLAGS                          = 20004,                     // Cleaning Flags
     WS_DAILY_QUEST_RESET_TIME                  = 20005,                     // Next daily reset time
     WS_GUILD_DAILY_RESET_TIME                  = 20006,                     // Next guild cap reset time
     WS_MONTHLY_QUEST_RESET_TIME                = 20007,                     // Next monthly reset time
     WS_DAILY_CALENDAR_DELETION_OLD_EVENTS_TIME = 20008                      // Next daily calendar deletions of old events time
 };
WorldTimers
enum WorldTimers
Timers for different object refresh rates.
Enumerator
WUPDATE_AUCTIONS
WUPDATE_WEATHERS
WUPDATE_UPTIME
WUPDATE_CORPSES
WUPDATE_EVENTS
WUPDATE_CLEANDB
WUPDATE_AUTOBROADCAST
WUPDATE_MAILBOXQUEUE
WUPDATE_PINGDB
WUPDATE_5_SECS
WUPDATE_WHO_LIST
WUPDATE_COUNT
Definition at line 60 of file World.h.
 {
     WUPDATE_AUCTIONS,
     WUPDATE_WEATHERS,
     WUPDATE_UPTIME,
     WUPDATE_CORPSES,
     WUPDATE_EVENTS,
     WUPDATE_CLEANDB,
     WUPDATE_AUTOBROADCAST,
     WUPDATE_MAILBOXQUEUE,
     WUPDATE_PINGDB,
     WUPDATE_5_SECS,
     WUPDATE_WHO_LIST,
     WUPDATE_COUNT
 };
Function Documentation
AddWeather()
Weather * WeatherMgr::AddWeather (uint32 zone_id)
Add a Weather object to the list.
Definition at line 67 of file WeatherMgr.cpp.
     {
         WeatherData const* weatherChances = GetWeatherData(zone_id);
         // zone does not have weather, ignore
         if (!weatherChances)
             return nullptr;
         Weather* w = new Weather(zone_id, weatherChances);
         m_weathers[w->GetZone()].reset(w);
         w->ReGenerate();
         w->UpdateWeather();
         return w;
     }
References WeatherMgr::anonymous_namespace{WeatherMgr.cpp}::GetWeatherData(), Weather::GetZone(), WeatherMgr::anonymous_namespace{WeatherMgr.cpp}::m_weathers, Weather::ReGenerate(), and Weather::UpdateWeather().
Referenced by misc_commandscript::HandleChangeWeather(), and Player::UpdateZone().
FindWeather()
Weather * WeatherMgr::FindWeather (uint32 id)
Find a Weather object by the given zoneid.
Definition at line 50 of file WeatherMgr.cpp.
     {
         WeatherMap::const_iterator itr = m_weathers.find(id);
         return (itr != m_weathers.end()) ? itr->second.get() : 0;
     }
References WeatherMgr::anonymous_namespace{WeatherMgr.cpp}::m_weathers.
Referenced by misc_commandscript::HandleChangeWeather(), and Player::UpdateZone().
GetScriptId()
uint32 Weather::GetScriptId () const inline
Definition at line 79 of file Weather.h.
 { return m_weatherChances->ScriptId; }
References Weather::m_weatherChances, and WeatherData::ScriptId.
Referenced by ScriptMgr::OnWeatherChange(), and ScriptMgr::OnWeatherUpdate().
GetWeatherState()
WeatherState Weather::GetWeatherState () const private
Get the sound number associated with the current weather.
Definition at line 280 of file Weather.cpp.
 {
     if (m_grade < 0.27f)
         return WEATHER_STATE_FINE;
     switch (m_type)
     {
         case WEATHER_TYPE_RAIN:
             if (m_grade < 0.40f)
                 return WEATHER_STATE_LIGHT_RAIN;
             else if (m_grade < 0.70f)
                 return WEATHER_STATE_MEDIUM_RAIN;
             else
                 return WEATHER_STATE_HEAVY_RAIN;
         case WEATHER_TYPE_SNOW:
             if (m_grade < 0.40f)
                 return WEATHER_STATE_LIGHT_SNOW;
             else if (m_grade < 0.70f)
                 return WEATHER_STATE_MEDIUM_SNOW;
             else
                 return WEATHER_STATE_HEAVY_SNOW;
         case WEATHER_TYPE_STORM:
             if (m_grade < 0.40f)
                 return WEATHER_STATE_LIGHT_SANDSTORM;
             else if (m_grade < 0.70f)
                 return WEATHER_STATE_MEDIUM_SANDSTORM;
             else
                 return WEATHER_STATE_HEAVY_SANDSTORM;
         case WEATHER_TYPE_BLACKRAIN:
             return WEATHER_STATE_BLACKRAIN;
         case WEATHER_TYPE_THUNDERS:
             return WEATHER_STATE_THUNDERS;
         case WEATHER_TYPE_FINE:
         default:
             return WEATHER_STATE_FINE;
     }
 }
References Weather::m_grade, Weather::m_type, WEATHER_STATE_BLACKRAIN, WEATHER_STATE_FINE, WEATHER_STATE_HEAVY_RAIN, WEATHER_STATE_HEAVY_SANDSTORM, WEATHER_STATE_HEAVY_SNOW, WEATHER_STATE_LIGHT_RAIN, WEATHER_STATE_LIGHT_SANDSTORM, WEATHER_STATE_LIGHT_SNOW, WEATHER_STATE_MEDIUM_RAIN, WEATHER_STATE_MEDIUM_SANDSTORM, WEATHER_STATE_MEDIUM_SNOW, WEATHER_STATE_THUNDERS, WEATHER_TYPE_BLACKRAIN, WEATHER_TYPE_FINE, WEATHER_TYPE_RAIN, WEATHER_TYPE_SNOW, WEATHER_TYPE_STORM, and WEATHER_TYPE_THUNDERS.
Referenced by Weather::SendWeatherUpdateToPlayer(), and Weather::UpdateWeather().
getWorldInstance()
std::unique_ptr<IWorld>& getWorldInstance ()
Definition at line 175 of file World.cpp.
 {
     static std::unique_ptr<IWorld> instance = std::make_unique<World>();
     return instance;
 }
GetZone()
uint32 Weather::GetZone () const inline
For which zone is this weather?
Definition at line 78 of file Weather.h.
 { return m_zone; };
References Weather::m_zone.
Referenced by WeatherMgr::AddWeather(), and ScriptMgr::OnWeatherChange().
LoadWeatherData()
void WeatherMgr::LoadWeatherData ()
Definition at line 83 of file WeatherMgr.cpp.
     {
         uint32 oldMSTime = getMSTime();
         uint32 count = 0;
         QueryResult result = WorldDatabase.Query("SELECT "
                              "zone, spring_rain_chance, spring_snow_chance, spring_storm_chance,"
                              "summer_rain_chance, summer_snow_chance, summer_storm_chance,"
                              "fall_rain_chance, fall_snow_chance, fall_storm_chance,"
                              "winter_rain_chance, winter_snow_chance, winter_storm_chance,"
                              "ScriptName FROM game_weather");
         if (!result)
         {
             LOG_ERROR("sql.sql", ">> Loaded 0 weather definitions. DB table `game_weather` is empty.");
             LOG_INFO("server.loading", " ");
             return;
         }
         do
         {
             Field* fields = result->Fetch();
             uint32 zone_id = fields[0].GetUInt32();
             WeatherData& wzc = mWeatherZoneMap[zone_id];
             for (uint8 season = 0; season < WEATHER_SEASONS; ++season)
             {
                 wzc.data[season].rainChance  = fields[season * (MAX_WEATHER_TYPE - 1) + 1].GetUInt8();
                 wzc.data[season].snowChance  = fields[season * (MAX_WEATHER_TYPE - 1) + 2].GetUInt8();
                 wzc.data[season].stormChance = fields[season * (MAX_WEATHER_TYPE - 1) + 3].GetUInt8();
                 if (wzc.data[season].rainChance > 100)
                 {
                     wzc.data[season].rainChance = 25;
                     LOG_ERROR("sql.sql", "Weather for zone %u season %u has wrong rain chance > 100%%", zone_id, season);
                 }
                 if (wzc.data[season].snowChance > 100)
                 {
                     wzc.data[season].snowChance = 25;
                     LOG_ERROR("sql.sql", "Weather for zone %u season %u has wrong snow chance > 100%%", zone_id, season);
                 }
                 if (wzc.data[season].stormChance > 100)
                 {
                     wzc.data[season].stormChance = 25;
                     LOG_ERROR("sql.sql", "Weather for zone %u season %u has wrong storm chance > 100%%", zone_id, season);
                 }
             }
             wzc.ScriptId = sObjectMgr->GetScriptId(fields[13].GetCString());
             ++count;
         } while (result->NextRow());
         LOG_INFO("server.loading", ">> Loaded %u weather definitions in %u ms", count, GetMSTimeDiffToNow(oldMSTime));
         LOG_INFO("server.loading", " ");
     }
References count(), WeatherData::data, getMSTime(), GetMSTimeDiffToNow(), Field::GetUInt32(), LOG_ERROR, LOG_INFO, MAX_WEATHER_TYPE, WeatherMgr::anonymous_namespace{WeatherMgr.cpp}::mWeatherZoneMap, WeatherSeasonChances::rainChance, WeatherData::ScriptId, WeatherSeasonChances::snowChance, sObjectMgr, WeatherSeasonChances::stormChance, WEATHER_SEASONS, and WorldDatabase.
Referenced by World::SetInitialWorldSettings().
ReGenerate()
bool Weather::ReGenerate ()
Calculate the new weather.
Weather statistics:
30% - no change
30% - weather gets better (if not fine) or change weather type
30% - weather worsens (if not fine)
10% - radical change (if not fine)
Radical change:
if light -> heavy
if medium -> change weather type
if heavy -> 50% light, 50% change weather type
New weather statistics (if not fine):
85% light
7% medium
7% heavy If fine 100% sun (no fog)
Definition at line 66 of file Weather.cpp.
 {
     if (!m_weatherChances)
     {
         m_type = WEATHER_TYPE_FINE;
         m_grade = 0.0f;
         return false;
     }
     uint32 u = urand(0, 99);
     if (u < 30)
         return false;
     // remember old values
     WeatherType old_type = m_type;
     float old_grade = m_grade;
     //78 days between January 1st and March 20nd; 365/4=91 days by season
     // season source http://aa.usno.navy.mil/data/docs/EarthSeasons.html
     time_t gtime = sWorld->GetGameTime();
     struct tm ltime;
     localtime_r(&gtime, &ltime);
     uint32 season = ((ltime.tm_yday - 78 + 365) / 91) % 4;
     static char const* seasonName[WEATHER_SEASONS] = { "spring", "summer", "fall", "winter" };
     LOG_DEBUG("weather", "Generating a change in %s weather for zone %u.", seasonName[season], m_zone);
     if ((u < 60) && (m_grade < 0.33333334f))                // Get fair
     {
         m_type = WEATHER_TYPE_FINE;
         m_grade = 0.0f;
     }
     if ((u < 60) && (m_type != WEATHER_TYPE_FINE))          // Get better
     {
         m_grade -= 0.33333334f;
         return true;
     }
     if ((u < 90) && (m_type != WEATHER_TYPE_FINE))          // Get worse
     {
         m_grade += 0.33333334f;
         return true;
     }
     if (m_type != WEATHER_TYPE_FINE)
     {
         if (m_grade < 0.33333334f)
         {
             m_grade = 0.9999f;                              // go nuts
             return true;
         }
         else
         {
             if (m_grade > 0.6666667f)
             {
                 // Severe change, but how severe?
                 uint32 rnd = urand(0, 99);
                 if (rnd < 50)
                 {
                     m_grade -= 0.6666667f;
                     return true;
                 }
             }
             m_type = WEATHER_TYPE_FINE;                     // clear up
             m_grade = 0;
         }
     }
     // At this point, only weather that isn't doing anything remains but that have weather data
     uint32 chance1 = m_weatherChances->data[season].rainChance;
     uint32 chance2 = chance1 + m_weatherChances->data[season].snowChance;
     uint32 chance3 = chance2 + m_weatherChances->data[season].stormChance;
     uint32 rnd = urand(0, 99);
     if (rnd <= chance1)
         m_type = WEATHER_TYPE_RAIN;
     else if (rnd <= chance2)
         m_type = WEATHER_TYPE_SNOW;
     else if (rnd <= chance3)
         m_type = WEATHER_TYPE_STORM;
     else
         m_type = WEATHER_TYPE_FINE;
     if (m_type == WEATHER_TYPE_FINE)
     {
         m_grade = 0.0f;
     }
     else if (u < 90)
     {
         m_grade = (float)rand_norm() * 0.3333f;
     }
     else
     {
         // Severe change, but how severe?
         rnd = urand(0, 99);
         if (rnd < 50)
             m_grade = (float)rand_norm() * 0.3333f + 0.3334f;
         else
             m_grade = (float)rand_norm() * 0.3333f + 0.6667f;
     }
     // return true only in case weather changes
     return m_type != old_type || m_grade != old_grade;
 }
References WeatherData::data, localtime_r(), LOG_DEBUG, Weather::m_grade, Weather::m_type, Weather::m_weatherChances, Weather::m_zone, WeatherSeasonChances::rainChance, rand_norm(), WeatherSeasonChances::snowChance, WeatherSeasonChances::stormChance, sWorld, urand(), WEATHER_SEASONS, WEATHER_TYPE_FINE, WEATHER_TYPE_RAIN, WEATHER_TYPE_SNOW, and WEATHER_TYPE_STORM.
Referenced by WeatherMgr::AddWeather(), and Weather::Update().
RemoveWeather()
void WeatherMgr::RemoveWeather (uint32 id)
Remove a Weather object for the given zoneid.
Definition at line 57 of file WeatherMgr.cpp.
     {
         // not called at the moment. Kept for completeness
         WeatherMap::iterator itr = m_weathers.find(id);
         if (itr != m_weathers.end())
             m_weathers.erase(itr);
     }
References WeatherMgr::anonymous_namespace{WeatherMgr.cpp}::m_weathers.
SendFineWeatherUpdateToPlayer()
void WeatherMgr::SendFineWeatherUpdateToPlayer (Player * player)
Definition at line 145 of file WeatherMgr.cpp.
     {
         WorldPacket data(SMSG_WEATHER, (4 + 4 + 1));
         data << (uint32)WEATHER_STATE_FINE;
         data << (float)0.0f;
         data << uint8(0);
         player->GetSession()->SendPacket(&data);
     }
References Player::GetSession(), WorldSession::SendPacket(), SMSG_WEATHER, and WEATHER_STATE_FINE.
Referenced by Player::UpdateZone().
SendWeatherUpdateToPlayer()
void Weather::SendWeatherUpdateToPlayer (Player * player)
Definition at line 189 of file Weather.cpp.
 {
     WorldPacket data(SMSG_WEATHER, (4 + 4 + 1));
     data << uint32(GetWeatherState());
     data << (float)m_grade;
     data << uint8(0);
 }
References Weather::GetWeatherState(), Weather::m_grade, and SMSG_WEATHER.
SetWeather()
void Weather::SetWeather (WeatherType type, float grade)
Set the weather.
Definition at line 269 of file Weather.cpp.
 {
     if (m_type == type && m_grade == grade)
         return;
     m_type = type;
     m_grade = grade;
     UpdateWeather();
 }
References Weather::m_grade, Weather::m_type, and Weather::UpdateWeather().
Referenced by misc_commandscript::HandleChangeWeather().
Update() [1/2]
bool Weather::Update (uint32 diff)
Launch a weather update.
If the timer has passed, ReGenerate the weather
Weather will be removed if not updated (no players in zone anymore)
Definition at line 41 of file Weather.cpp.
 {
     if (m_timer.GetCurrent() >= 0)
         m_timer.Update(diff);
     else
         m_timer.SetCurrent(0);
     if (m_timer.Passed())
     {
         m_timer.Reset();
         // update only if Regenerate has changed the weather
         if (ReGenerate())
         {
             if (!UpdateWeather())
                 return false;
         }
     }
     sScriptMgr->OnWeatherUpdate(this, diff);
     return true;
 }
References diff(), IntervalTimer::GetCurrent(), Weather::m_timer, IntervalTimer::Passed(), Weather::ReGenerate(), IntervalTimer::Reset(), IntervalTimer::SetCurrent(), sScriptMgr, IntervalTimer::Update(), and Weather::UpdateWeather().
Update() [2/2]
void WeatherMgr::Update (uint32 diff)
Send an update signal to Weather objects
and remove Weather objects for zones with no player
Definition at line 154 of file WeatherMgr.cpp.
     {
         WeatherMap::iterator itr, next;
         for (itr = m_weathers.begin(); itr != m_weathers.end(); itr = next)
         {
             next = itr;
             ++next;
             // As interval > WorldTick
             if (!itr->second->Update(diff))
                 m_weathers.erase(itr);
         }
     }
References diff(), WeatherMgr::anonymous_namespace{WeatherMgr.cpp}::m_weathers, and next().
Referenced by World::Update(), and MotionMaster::UpdateMotion().
UpdateWeather()
bool Weather::UpdateWeather ()
Send the new weather to all players in the zone.
Send the weather packet to all players in this zone
Log the event
Definition at line 198 of file Weather.cpp.
 {
     if (m_grade >= 1)
         m_grade = 0.9999f;
     else if (m_grade < 0)
         m_grade = 0.0001f;
     WeatherState state = GetWeatherState();
     WorldPacket data(SMSG_WEATHER, (4 + 4 + 1));
     data << uint32(state);
     data << (float)m_grade;
     data << uint8(0);
     //- Returns false if there were no players found to update
     if (!sWorld->SendZoneMessage(m_zone, &data))
         return false;
     char const* wthstr;
     switch (state)
     {
         case WEATHER_STATE_FOG:
             wthstr = "fog";
             break;
         case WEATHER_STATE_LIGHT_RAIN:
             wthstr = "light rain";
             break;
         case WEATHER_STATE_MEDIUM_RAIN:
             wthstr = "medium rain";
             break;
         case WEATHER_STATE_HEAVY_RAIN:
             wthstr = "heavy rain";
             break;
         case WEATHER_STATE_LIGHT_SNOW:
             wthstr = "light snow";
             break;
         case WEATHER_STATE_MEDIUM_SNOW:
             wthstr = "medium snow";
             break;
         case WEATHER_STATE_HEAVY_SNOW:
             wthstr = "heavy snow";
             break;
         case WEATHER_STATE_LIGHT_SANDSTORM:
             wthstr = "light sandstorm";
             break;
         case WEATHER_STATE_MEDIUM_SANDSTORM:
             wthstr = "medium sandstorm";
             break;
         case WEATHER_STATE_HEAVY_SANDSTORM:
             wthstr = "heavy sandstorm";
             break;
         case WEATHER_STATE_THUNDERS:
             wthstr = "thunders";
             break;
         case WEATHER_STATE_BLACKRAIN:
             wthstr = "blackrain";
             break;
         case WEATHER_STATE_FINE:
         default:
             wthstr = "fine";
             break;
     }
     LOG_DEBUG("weather", "Change the weather of zone %u to %s.", m_zone, wthstr);
     sScriptMgr->OnWeatherChange(this, state, m_grade);
     return true;
 }
References Weather::GetWeatherState(), LOG_DEBUG, Weather::m_grade, Weather::m_zone, SMSG_WEATHER, sScriptMgr, sWorld, WEATHER_STATE_BLACKRAIN, WEATHER_STATE_FINE, WEATHER_STATE_FOG, WEATHER_STATE_HEAVY_RAIN, WEATHER_STATE_HEAVY_SANDSTORM, WEATHER_STATE_HEAVY_SNOW, WEATHER_STATE_LIGHT_RAIN, WEATHER_STATE_LIGHT_SANDSTORM, WEATHER_STATE_LIGHT_SNOW, WEATHER_STATE_MEDIUM_RAIN, WEATHER_STATE_MEDIUM_SANDSTORM, WEATHER_STATE_MEDIUM_SNOW, and WEATHER_STATE_THUNDERS.
Referenced by WeatherMgr::AddWeather(), Weather::SetWeather(), and Weather::Update().
Weather()
Weather::Weather (uint32 zone, WeatherData const * weatherChances)
Create the Weather object.
Definition at line 30 of file Weather.cpp.
     : m_zone(zone), m_weatherChances(weatherChances)
 {
     m_timer.SetInterval(sWorld->getIntConfig(CONFIG_INTERVAL_CHANGEWEATHER));
     m_type = WEATHER_TYPE_FINE;
     m_grade = 0;
     LOG_DEBUG("weather", "WORLD: Starting weather system for zone %u (change every %u minutes).", m_zone, (uint32)(m_timer.GetInterval() / (MINUTE * IN_MILLISECONDS)));
 }
References CONFIG_INTERVAL_CHANGEWEATHER, IntervalTimer::GetInterval(), IN_MILLISECONDS, LOG_DEBUG, Weather::m_grade, Weather::m_timer, Weather::m_type, Weather::m_zone, MINUTE, IntervalTimer::SetInterval(), sWorld, and WEATHER_TYPE_FINE.
~Weather()
Weather::~Weather () default
Variable Documentation
data
WeatherSeasonChances WeatherData::data[WEATHER_SEASONS]
Definition at line 41 of file Weather.h.
Referenced by WeatherMgr::LoadWeatherData(), and Weather::ReGenerate().
m_grade
float Weather::m_grade private
Definition at line 85 of file Weather.h.
Referenced by Weather::GetWeatherState(), Weather::ReGenerate(), Weather::SendWeatherUpdateToPlayer(), Weather::SetWeather(), Weather::UpdateWeather(), and Weather::Weather().
m_timer
IntervalTimer Weather::m_timer private
Definition at line 86 of file Weather.h.
Referenced by Weather::Update(), and Weather::Weather().
m_type
WeatherType Weather::m_type private
Definition at line 84 of file Weather.h.
Referenced by Weather::GetWeatherState(), Weather::ReGenerate(), Weather::SetWeather(), and Weather::Weather().
m_weatherChances
WeatherData const* Weather::m_weatherChances private
Definition at line 87 of file Weather.h.
Referenced by Weather::GetScriptId(), and Weather::ReGenerate().
m_zone
uint32 Weather::m_zone private
Definition at line 83 of file Weather.h.
Referenced by Weather::GetZone(), Weather::ReGenerate(), Weather::UpdateWeather(), and Weather::Weather().
rainChance
uint32 WeatherSeasonChances::rainChance
Definition at line 34 of file Weather.h.
Referenced by WeatherMgr::LoadWeatherData(), and Weather::ReGenerate().
realm
AC_GAME_API Realm realm extern
Definition at line 108 of file World.cpp.
Referenced by World::_UpdateRealmCharCount(), ClearOnlineAccounts(), account_commandscript::HandleAccountSetGmLevelCommand(), WorldSession::HandleAddFriendOpcode(), WorldSocket::HandleAuthSession(), WorldSocket::HandleAuthSessionCallback(), gm_commandscript::HandleGMListFullCommand(), ticket_commandscript::HandleGMTicketAssignToCommand(), ticket_commandscript::HandleGMTicketUnAssignCommand(), misc_commandscript::HandlePInfoCommand(), WorldSession::HandlePlayerLoginFromDB(), server_commandscript::HandleServerDebugCommand(), ChatHandler::HasLowerSecurityAccount(), World::LoadConfigSettings(), World::LoadDBAllowedSecurityLevel(), LoadRealmInfo(), main(), AuthSession::RealmListCallback(), World::SetInitialWorldSettings(), StartDB(), World::Update(), RealmList::UpdateRealm(), and RealmList::UpdateRealms().
ScriptId
uint32 WeatherData::ScriptId
Definition at line 42 of file Weather.h.
Referenced by Weather::GetScriptId(), and WeatherMgr::LoadWeatherData().
snowChance
uint32 WeatherSeasonChances::snowChance
Definition at line 35 of file Weather.h.
Referenced by WeatherMgr::LoadWeatherData(), and Weather::ReGenerate().
stormChance
uint32 WeatherSeasonChances::stormChance
Definition at line 36 of file Weather.h.
Referenced by WeatherMgr::LoadWeatherData(), and Weather::ReGenerate().