Azerotcore-wotlk: BuiltInConfig Namespace Reference
BuiltInConfig Namespace Reference
Functions
AC_COMMON_API std::string GetCMakeCommand ()
AC_COMMON_API std::string GetBuildDirectory ()
AC_COMMON_API std::string GetSourceDirectory ()
AC_COMMON_API std::string GetMySQLExecutable ()
Detailed Description
Provides helper functions to access built-in values which can be overwritten in config
Function Documentation
GetBuildDirectory()
std::string BuiltInConfig::GetBuildDirectory ()
Returns the build directory path when any is specified in the config, returns the built-in one otherwise
Definition at line 36 of file BuiltInConfig.cpp.
 {
     return GetStringWithDefaultValueFromFunction(
         "BuildDirectory", GitRevision::GetBuildDirectory);
 }
References GitRevision::GetBuildDirectory(), and GetStringWithDefaultValueFromFunction().
GetCMakeCommand()
std::string BuiltInConfig::GetCMakeCommand ()
Returns the CMake command when any is specified in the config, returns the built-in path otherwise
Definition at line 30 of file BuiltInConfig.cpp.
 {
     return GetStringWithDefaultValueFromFunction(
         "CMakeCommand", GitRevision::GetCMakeCommand);
 }
References GitRevision::GetCMakeCommand(), and GetStringWithDefaultValueFromFunction().
GetMySQLExecutable()
std::string BuiltInConfig::GetMySQLExecutable ()
Returns the path to the mysql executable (mysql) when any is specified in the config, returns the built-in one otherwise
Definition at line 48 of file BuiltInConfig.cpp.
 {
     return GetStringWithDefaultValueFromFunction(
         "MySQLExecutable", GitRevision::GetMySQLExecutable);
 }
References GitRevision::GetMySQLExecutable(), and GetStringWithDefaultValueFromFunction().
Referenced by DBUpdaterUtil::GetCorrectedMySQLExecutable().
GetSourceDirectory()
std::string BuiltInConfig::GetSourceDirectory ()
Returns the source directory path when any is specified in the config, returns the built-in one otherwise
Definition at line 42 of file BuiltInConfig.cpp.
 {
     return GetStringWithDefaultValueFromFunction(
         "SourceDirectory", GitRevision::GetSourceDirectory);
 }
References GitRevision::GetSourceDirectory(), and GetStringWithDefaultValueFromFunction().
Referenced by DBUpdater< T >::GetBaseFilesDirectory(), and DBUpdater< T >::Update().