Azerotcore-wotlk: MapSessionFilter Class Reference
MapSessionFilter Class Reference
User to World Communication
#include <WorldSession.h>
Public Member Functions
MapSessionFilter (WorldSession *pSession)
~MapSessionFilter () override=default
bool Process (WorldPacket *packet) override
bool ProcessUnsafe () const override
Public Member Functions inherited from PacketFilter
PacketFilter (WorldSession *pSession)
virtual ~PacketFilter ()=default
Additional Inherited Members
Protected Attributes inherited from PacketFilter
WorldSession *const m_pSession
Detailed Description
Definition at line 155 of file WorldSession.h.
Constructor & Destructor Documentation
MapSessionFilter()
MapSessionFilter::MapSessionFilter (WorldSession * pSession) inline explicit
Definition at line 158 of file WorldSession.h.
 : PacketFilter(pSession) {}
~MapSessionFilter()
MapSessionFilter::~MapSessionFilter () override default
Member Function Documentation
Process()
bool MapSessionFilter::Process (WorldPacket * packet) override virtual
Reimplemented from PacketFilter.
Definition at line 63 of file WorldSession.cpp.
 {
     ClientOpcodeHandler const* opHandle = opcodeTable[static_cast<OpcodeClient>(packet->GetOpcode())];
     //let's check if our opcode can be really processed in Map::Update()
     if (opHandle->ProcessingPlace == PROCESS_INPLACE)
         return true;
     //we do not process thread-unsafe packets
     if (opHandle->ProcessingPlace == PROCESS_THREADUNSAFE)
         return false;
     Player* player = m_pSession->GetPlayer();
     if (!player)
         return false;
     //in Map::Update() we do not process packets where player is not in world!
     return player->IsInWorld();
 }
References WorldPacket::GetOpcode(), WorldSession::GetPlayer(), Object::IsInWorld(), PacketFilter::m_pSession, opcodeTable, PROCESS_INPLACE, PROCESS_THREADUNSAFE, and ClientOpcodeHandler::ProcessingPlace.
ProcessUnsafe()
bool MapSessionFilter::ProcessUnsafe () const inline override virtual
Reimplemented from PacketFilter.
Definition at line 163 of file WorldSession.h.
 { return false; }
The documentation for this class was generated from the following files:
src/server/game/Server/WorldSession.h
src/server/game/Server/WorldSession.cpp