Azerotcore-wotlk: boss_sartharion_tenebron::boss_sartharion_tenebronAI Struct Reference
boss_sartharion_tenebron::boss_sartharion_tenebronAI Struct Reference
Public Member Functions
boss_sartharion_tenebronAI (Creature *pCreature)
void Reset () override
void JustSummoned (Creature *summon) override
void JustDied (Unit *killer) override
void HandleExtraEvent (uint32 const eventId) override
void ExecuteEvent (uint32 eventId) override
void ClearInstance () override
Public Member Functions inherited from boss_sartharion_dragonAI
boss_sartharion_dragonAI (Creature *pCreature, uint32 bossId)
void DoAction (int32 param) final
void MoveInLineOfSight (Unit *who) final
void MovementInform (uint32 type, uint32 pointId) final
void EnterCombat (Unit *) final
void KilledUnit (Unit *victim) final
void UpdateAI (uint32 diff) final
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
SummonList summons2
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from boss_sartharion_dragonAI
void RemoveTwilightPortal ()
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from boss_sartharion_dragonAI
EventMap extraEvents
ObjectGuid portalGUID
bool isCalledBySartharion
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1026 of file boss_sartharion.cpp.
Constructor & Destructor Documentation
boss_sartharion_tenebronAI()
boss_sartharion_tenebron::boss_sartharion_tenebronAI::boss_sartharion_tenebronAI (Creature * pCreature) inline
Definition at line 1028 of file boss_sartharion.cpp.
                                                         : boss_sartharion_dragonAI(pCreature, DATA_TENEBRON), summons2(pCreature)
         {
         }
Member Function Documentation
ClearInstance()
void boss_sartharion_tenebron::boss_sartharion_tenebronAI::ClearInstance () inline override virtual
Reimplemented from boss_sartharion_dragonAI.
Definition at line 1184 of file boss_sartharion.cpp.
         {
             boss_sartharion_dragonAI::ClearInstance();
             summons2.DespawnAll();
         }
References boss_sartharion_dragonAI::ClearInstance(), SummonList::DespawnAll(), and summons2.
ExecuteEvent()
void boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent (uint32 eventId) inline override virtual
Reimplemented from BossAI.
Definition at line 1075 of file boss_sartharion.cpp.
         {
             switch (eventId)
             {
                 case EVENT_MINIBOSS_SHADOW_BREATH:
                 {
                     if (!urand(0, 10))
                     {
                         Talk(SAY_TENEBRON_BREATH);
                     }
                     DoCastVictim(SPELL_SHADOW_BREATH, false);
                     events.RepeatEvent(17500);
                     break;
                 }
                 case EVENT_MINIBOSS_SHADOW_FISSURE:
                 {
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM))
                     {
                         DoCast(target, SPELL_SHADOW_FISSURE, false);
                     }
                     events.RepeatEvent(22500);
                     break;
                 }
                 case EVENT_MINIBOSS_OPEN_PORTAL:
                 {
                     Talk(WHISPER_OPEN_PORTAL);
                     Talk(SAY_TENEBRON_SPECIAL);
                     if (!isCalledBySartharion)
                     {
                         if (GameObject* Portal = me->GetVictim()->SummonGameObject(GO_TWILIGHT_PORTAL, portalPos[DATA_TENEBRON].GetPositionX(), portalPos[DATA_TENEBRON].GetPositionY(), portalPos[DATA_TENEBRON].GetPositionZ(), 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0))
{
                             portalGUID = Portal->GetGUID();
                         }
                     }
                     else
                     {
                         instance->DoAction(ACTION_ADD_PORTAL);
                     }
                     events.ScheduleEvent(EVENT_MINIBOSS_SPAWN_HELPERS, 2000);
                     events.RepeatEvent(60000);
                     break;
                 }
                 case EVENT_MINIBOSS_SPAWN_HELPERS:
                 {
                     Talk(WHISPER_HATCH_EGGS);
                     for (uint8 i = 0; i < MAX_TENEBORN_EGGS_SUMMONS; ++i)
                     {
                         if (Creature* egg = me->SummonCreature(NPC_TWILIGHT_EGG, TenebronEggsPos[isCalledBySartharion ? 1 : 0][i], TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 60000))
{
                             summons.Summon(egg);
                             if (isCalledBySartharion && instance->GetBossState(DATA_SARTHARION) == IN_PROGRESS)
{
                                 if (Creature* sartharion = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_SARTHARION)))
{
                                     sartharion->AI()->JustSummoned(egg);
                                 }
                             }
                             egg->SetPhaseMask(16, true);
                         }
                     }
                     events.ScheduleEvent(EVENT_MINIBOSS_HATCH_EGGS, 25000);
                     break;
                 }
                 case EVENT_MINIBOSS_HATCH_EGGS:
                 {
                     summons.RemoveNotExisting();
                     summons.DespawnEntry(NPC_TWILIGHT_WHELP);
                     for (ObjectGuid const& summonGuid : summons)
                     {
                         Creature const* summon = ObjectAccessor::GetCreature(*me, summonGuid);
                         if (!summon || !summon->IsAlive() || summon->GetEntry() != NPC_TWILIGHT_EGG)
{
                             continue;
                         }
                         if (Creature* whelp = me->SummonCreature(NPC_TWILIGHT_WHELP, summon->GetPosition(), TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 60000))
{
                             summons2.Summon(whelp);
                             if (isCalledBySartharion && instance->GetBossState(DATA_SARTHARION) == IN_PROGRESS)
{
                                 if (Creature* sartharion = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_SARTHARION)))
{
                                     sartharion->AI()->JustSummoned(whelp);
                                 }
                             }
                         }
                     }
                     if (!isCalledBySartharion)
                     {
                         // Remove phase shift
                         instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_TWILIGHT_SHIFT);
                         RemoveTwilightPortal();
                     }
                     else
                     {
                         instance->DoAction(ACTION_CLEAR_PORTAL);
                     }
                     EntryCheckPredicate pred(NPC_TWILIGHT_EGG);
                     summons.DoAction(ACTION_SWITCH_PHASE, pred);
                     break;
                 }
             }
         }
References ACTION_ADD_PORTAL, ACTION_CLEAR_PORTAL, ACTION_SWITCH_PHASE, DATA_SARTHARION, DATA_TENEBRON, SummonList::DespawnEntry(), SummonList::DoAction(), InstanceScript::DoAction(), UnitAI::DoCast(), UnitAI::DoCastVictim(), InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), EVENT_MINIBOSS_HATCH_EGGS, EVENT_MINIBOSS_OPEN_PORTAL, EVENT_MINIBOSS_SHADOW_BREATH, EVENT_MINIBOSS_SHADOW_FISSURE, EVENT_MINIBOSS_SPAWN_HELPERS, InstanceScript::GetBossState(), ObjectAccessor::GetCreature(), Object::GetEntry(), InstanceScript::GetGuidData(), Position::GetPosition(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetVictim(), GO_TWILIGHT_PORTAL, IN_PROGRESS, BossAI::instance, Unit::IsAlive(), boss_sartharion_dragonAI::isCalledBySartharion, MAX_TENEBORN_EGGS_SUMMONS, ScriptedAI::me, NPC_TWILIGHT_EGG, NPC_TWILIGHT_WHELP, boss_sartharion_dragonAI::portalGUID, portalPos, SummonList::RemoveNotExisting(), boss_sartharion_dragonAI::RemoveTwilightPortal(), SAY_TENEBRON_BREATH, SAY_TENEBRON_SPECIAL, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), SPELL_SHADOW_BREATH, SPELL_SHADOW_FISSURE, SPELL_TWILIGHT_SHIFT, SummonList::Summon(), WorldObject::SummonCreature(), WorldObject::SummonGameObject(), BossAI::summons, summons2, CreatureAI::Talk(), TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, TenebronEggsPos, urand(), WHISPER_HATCH_EGGS, and WHISPER_OPEN_PORTAL.
HandleExtraEvent()
void boss_sartharion_tenebron::boss_sartharion_tenebronAI::HandleExtraEvent (uint32 const eventId) inline override virtual
Reimplemented from boss_sartharion_dragonAI.
Definition at line 1064 of file boss_sartharion.cpp.
         {
             if (eventId == EVENT_MINIDRAKE_SPEECH)
             {
                 Talk(SAY_TENEBRON_RESPOND);
                 me->SetCanFly(true);
                 me->SetSpeed(MOVE_FLIGHT, 3.0f);
                 me->GetMotionMaster()->MovePath(me->GetEntry() * 10, false);
             }
         }
References EVENT_MINIDRAKE_SPEECH, Object::GetEntry(), Unit::GetMotionMaster(), ScriptedAI::me, MOVE_FLIGHT, MotionMaster::MovePath(), SAY_TENEBRON_RESPOND, Creature::SetCanFly(), Unit::SetSpeed(), and CreatureAI::Talk().
JustDied()
void boss_sartharion_tenebron::boss_sartharion_tenebronAI::JustDied (Unit * killer) inline override virtual
Reimplemented from boss_sartharion_dragonAI.
Definition at line 1054 of file boss_sartharion.cpp.
         {
             if (!isCalledBySartharion)
             {
                 summons2.DespawnAll();
             }
             boss_sartharion_dragonAI::JustDied(killer);
         }
References SummonList::DespawnAll(), boss_sartharion_dragonAI::isCalledBySartharion, boss_sartharion_dragonAI::JustDied(), and summons2.
JustSummoned()
void boss_sartharion_tenebron::boss_sartharion_tenebronAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from boss_sartharion_dragonAI.
Definition at line 1045 of file boss_sartharion.cpp.
         {
             if (summon->GetEntry() != NPC_TWILIGHT_EGG)
             {
                 summons.Summon(summon);
             }
             // Summons to Sartharion are linked manually
         }
References Object::GetEntry(), NPC_TWILIGHT_EGG, SummonList::Summon(), and BossAI::summons.
Reset()
void boss_sartharion_tenebron::boss_sartharion_tenebronAI::Reset () inline override virtual
Reimplemented from boss_sartharion_dragonAI.
Definition at line 1032 of file boss_sartharion.cpp.
         {
             boss_sartharion_dragonAI::Reset();
             if (!isCalledBySartharion)
             {
                 summons2.DespawnAll();
             }
             events.ScheduleEvent(EVENT_MINIBOSS_SHADOW_FISSURE, 20000);
             events.ScheduleEvent(EVENT_MINIBOSS_SHADOW_BREATH, 10000);
             events.ScheduleEvent(EVENT_MINIBOSS_OPEN_PORTAL, 15000);
         }
References SummonList::DespawnAll(), EVENT_MINIBOSS_OPEN_PORTAL, EVENT_MINIBOSS_SHADOW_BREATH, EVENT_MINIBOSS_SHADOW_FISSURE, boss_sartharion_dragonAI::isCalledBySartharion, boss_sartharion_dragonAI::Reset(), and summons2.
Member Data Documentation
summons2
SummonList boss_sartharion_tenebron::boss_sartharion_tenebronAI::summons2 private
Definition at line 1191 of file boss_sartharion.cpp.
Referenced by ClearInstance(), ExecuteEvent(), JustDied(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp