Azerotcore-wotlk: npc_llod_generic::npc_llod_genericAI Struct Reference
npc_llod_generic::npc_llod_genericAI Struct Reference
Public Member Functions
npc_llod_genericAI (Creature *pCreature)
void Reset () override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from CombatAI
CombatAI (Creature *c)
void InitializeAI () override
void EnterCombat (Unit *who) override
void JustDied (Unit *killer) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
uint32 attackTimer
uint32 summonTimer
Additional Inherited Members
Static Public Member Functions inherited from CombatAI
static int Permissible (Creature const *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CombatAI
EventMap events
SpellVct spells
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 383 of file zone_icecrown.cpp.
Constructor & Destructor Documentation
npc_llod_genericAI()
npc_llod_generic::npc_llod_genericAI::npc_llod_genericAI (Creature * pCreature) inline
Definition at line 385 of file zone_icecrown.cpp.
 : CombatAI(pCreature) { attackTimer = 0; summonTimer = 1; }
References attackTimer, and summonTimer.
Member Function Documentation
Reset()
void npc_llod_generic::npc_llod_genericAI::Reset () inline override virtual
Reimplemented from CombatAI.
Definition at line 390 of file zone_icecrown.cpp.
         {
             summonTimer = 1;
             CombatAI::Reset();
         }
References CombatAI::Reset(), and summonTimer.
UpdateAI()
void npc_llod_generic::npc_llod_genericAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from CombatAI.
Definition at line 396 of file zone_icecrown.cpp.
         {
             attackTimer += diff;
             if (attackTimer >= 1500)
             {
                 if (!me->IsInCombat())
                     if (Unit* target = me->SelectNearbyTarget(nullptr, 20.0f))
                         AttackStart(target);
                 attackTimer = 0;
             }
             if (summonTimer)
             {
                 summonTimer += diff;
                 if (summonTimer >= 8000)
                 {
                     for (uint8 i = 0; i < 3; ++i)
                         me->SummonCreature(30593, me->GetPositionX() + irand(-5, 5), me->GetPositionY() + irand(-5, 5), me->GetPositionZ(), 0.0f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 15000);
                     if (roll_chance_i(10))
                         me->SummonCreature(30575, me->GetPositionX() + irand(-5, 5), me->GetPositionY() + irand(-5, 5), me->GetPositionZ(), 0.0f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 15000);
                     summonTimer = 0;
                 }
             }
             CombatAI::UpdateAI(diff);
         }
References UnitAI::AttackStart(), attackTimer, diff(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), irand(), Unit::IsInCombat(), CreatureAI::me, roll_chance_i(), Unit::SelectNearbyTarget(), WorldObject::SummonCreature(), summonTimer, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, and CombatAI::UpdateAI().
Member Data Documentation
attackTimer
uint32 npc_llod_generic::npc_llod_genericAI::attackTimer
Definition at line 387 of file zone_icecrown.cpp.
Referenced by npc_llod_genericAI(), and UpdateAI().
summonTimer
uint32 npc_llod_generic::npc_llod_genericAI::summonTimer
Definition at line 388 of file zone_icecrown.cpp.
Referenced by npc_llod_genericAI(), Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/zone_icecrown.cpp