Azerotcore-wotlk: FleeingMovementGenerator< T > Class Template Reference
FleeingMovementGenerator< T > Class Template Reference
#include <FleeingMovementGenerator.h>
Public Member Functions
FleeingMovementGenerator (ObjectGuid fright)
void DoInitialize (T *)
void DoFinalize (T *)
void DoReset (T *)
bool DoUpdate (T *, uint32)
MovementGeneratorType GetMovementGeneratorType ()
void DoFinalize (Player *owner)
Public Member Functions inherited from MovementGeneratorMedium< T, FleeingMovementGenerator< T > >
void Initialize (Unit *u) override
void Finalize (Unit *u) override
void Reset (Unit *u) override
bool Update (Unit *u, uint32 time_diff) override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual uint32 GetSplineId () const
virtual void unitSpeedChanged ()
virtual bool GetResetPosition (float &, float &, float &)
Private Member Functions
void _setTargetLocation (T *)
bool _getPoint (T *, float &x, float &y, float &z)
bool _setMoveData (T *owner)
void _Init (T *)
void _Init (Player *)
Private Attributes
bool is_water_ok: 1
bool is_land_ok: 1
bool i_only_forward: 1
float i_caster_x
float i_caster_y
float i_caster_z
float i_last_distance_from_caster
float i_to_distance_from_caster
float i_cur_angle
ObjectGuid i_frightGUID
TimeTracker i_nextCheckTime
Detailed Description
template<class T>
class FleeingMovementGenerator< T >
Definition at line 24 of file FleeingMovementGenerator.h.
Constructor & Destructor Documentation
FleeingMovementGenerator()
template<class T > FleeingMovementGenerator< T >::FleeingMovementGenerator (ObjectGuid fright) inline
Definition at line 27 of file FleeingMovementGenerator.h.
 : i_frightGUID(fright), i_nextCheckTime(0) {}
Member Function Documentation
_getPoint()
template<class T > template bool FleeingMovementGenerator< T >::_getPoint (T * , float & x, float & y, float & z) private
Definition at line 59 of file FleeingMovementGenerator.cpp.
 {
     if (!owner)
         return false;
     const Map* _map = owner->GetMap();
     x = owner->GetPositionX();
     y = owner->GetPositionY();
     z = owner->GetPositionZ();
     float temp_x, temp_y, angle;
     // primitive path-finding
     for (uint8 i = 0; i < 18; ++i)
     {
         if (i_only_forward && i > 2)
             break;
         float distance = 5.0f;
         switch (i)
         {
             case 0:
                 angle = i_cur_angle;
                 break;
             case 1:
                 angle = i_cur_angle;
                 distance /= 2;
                 break;
             case 2:
                 angle = i_cur_angle;
                 distance /= 4;
                 break;
             case 3:
                 angle = i_cur_angle + static_cast<float>(M_PI / 4);
                 break;
             case 4:
                 angle = i_cur_angle - static_cast<float>(M_PI / 4);
                 break;
             case 5:
                 angle = i_cur_angle + static_cast<float>(M_PI / 4);
                 distance /= 2;
                 break;
             case 6:
                 angle = i_cur_angle - static_cast<float>(M_PI / 4);
                 distance /= 2;
                 break;
             case 7:
                 angle = i_cur_angle + static_cast<float>(M_PI / 2);
                 break;
             case 8:
                 angle = i_cur_angle - static_cast<float>(M_PI / 2);
                 break;
             case 9:
                 angle = i_cur_angle + static_cast<float>(M_PI / 2);
                 distance /= 2;
                 break;
             case 10:
                 angle = i_cur_angle - static_cast<float>(M_PI / 2);
                 distance /= 2;
                 break;
             case 11:
                 angle = i_cur_angle + static_cast<float>(M_PI / 4);
                 distance /= 4;
                 break;
             case 12:
                 angle = i_cur_angle - static_cast<float>(M_PI / 4);
                 distance /= 4;
                 break;
             case 13:
                 angle = i_cur_angle + static_cast<float>(M_PI / 2);
                 distance /= 4;
                 break;
             case 14:
                 angle = i_cur_angle - static_cast<float>(M_PI / 2);
                 distance /= 4;
                 break;
             case 15:
                 angle = i_cur_angle +  static_cast<float>(3 * M_PI / 4);
                 distance /= 2;
                 break;
             case 16:
                 angle = i_cur_angle -  static_cast<float>(3 * M_PI / 4);
                 distance /= 2;
                 break;
             case 17:
                 angle = i_cur_angle + static_cast<float>(M_PI);
                 distance /= 2;
                 break;
             default:
                 angle = 0.0f;
                 distance = 0.0f;
                 break;
         }
         temp_x = x + distance * cos(angle);
         temp_y = y + distance * sin(angle);
         float temp_z = z;
         if (!_map->CanReachPositionAndGetValidCoords(owner, temp_x, temp_y, temp_z, true, true))
         {
             break;
         }
         if (!(temp_z - z) || distance / fabs(temp_z - z) > 1.0f)
         {
             float temp_z_left = _map->GetHeight(owner->GetPhaseMask(), temp_x + 1.0f * cos(angle + static_cast<float>(M_PI / 2)), temp_y + 1.0f * sin(angle + static_cast<float>(M_PI / 2)), z, true);
             float temp_z_right = _map->GetHeight(owner->GetPhaseMask(), temp_x + 1.0f * cos(angle - static_cast<float>(M_PI / 2)), temp_y + 1.0f * sin(angle - static_cast<float>(M_PI / 2)), z, true);
             if (fabs(temp_z_left - temp_z) < 1.2f && fabs(temp_z_right - temp_z) < 1.2f)
             {
                 // use new values
                 x = temp_x;
                 y = temp_y;
                 z = temp_z;
                 return true;
             }
         }
     }
     i_to_distance_from_caster = 0.0f;
     i_nextCheckTime.Reset(urand(500, 1000));
     return false;
 }
References Map::CanReachPositionAndGetValidCoords(), Map::GetHeight(), and urand().
_Init() [1/2]
void FleeingMovementGenerator< Player >::_Init (Player *) private
Definition at line 317 of file FleeingMovementGenerator.cpp.
 {
     is_water_ok = true;
     is_land_ok  = true;
 }
_Init() [2/2]
template<class T > void FleeingMovementGenerator< T >::_Init (T *) private
_setMoveData()
template<class T > template bool FleeingMovementGenerator< T >::_setMoveData (T * owner) private
Definition at line 183 of file FleeingMovementGenerator.cpp.
 {
     float cur_dist_xyz = owner->GetDistance(i_caster_x, i_caster_y, i_caster_z);
     if (i_to_distance_from_caster > 0.0f)
     {
         if ((i_last_distance_from_caster > i_to_distance_from_caster && cur_dist_xyz < i_to_distance_from_caster)   ||
                 // if we reach lower distance
                 (i_last_distance_from_caster > i_to_distance_from_caster && cur_dist_xyz > i_last_distance_from_caster) ||
                 // if we can't be close
                 (i_last_distance_from_caster < i_to_distance_from_caster && cur_dist_xyz > i_to_distance_from_caster)   ||
                 // if we reach bigger distance
                 (cur_dist_xyz > MAX_QUIET_DISTANCE) ||           // if we are too far
                 (i_last_distance_from_caster > MIN_QUIET_DISTANCE && cur_dist_xyz < MIN_QUIET_DISTANCE))
             // if we leave 'quiet zone'
         {
             // we are very far or too close, stopping
             i_to_distance_from_caster = 0.0f;
             i_nextCheckTime.Reset(urand(500, 1000));
             return false;
         }
         else
         {
             // now we are running, continue
             i_last_distance_from_caster = cur_dist_xyz;
             return true;
         }
     }
     float cur_dist;
     float angle_to_caster;
     if (Unit* fright = ObjectAccessor::GetUnit(*owner, i_frightGUID))
     {
         cur_dist = fright->GetDistance(owner);
         if (cur_dist < cur_dist_xyz)
         {
             i_caster_x = fright->GetPositionX();
             i_caster_y = fright->GetPositionY();
             i_caster_z = fright->GetPositionZ();
             angle_to_caster = fright->GetAngle(owner);
         }
         else
         {
             cur_dist = cur_dist_xyz;
             angle_to_caster = owner->GetAngle(i_caster_x, i_caster_y) + static_cast<float>(M_PI);
         }
     }
     else
     {
         cur_dist = cur_dist_xyz;
         angle_to_caster = owner->GetAngle(i_caster_x, i_caster_y) + static_cast<float>(M_PI);
     }
     // if we too close may use 'path-finding' else just stop
     i_only_forward = cur_dist >= MIN_QUIET_DISTANCE / 3;
     //get angle and 'distance from caster' to run
     float angle;
     if (i_cur_angle == 0.0f && i_last_distance_from_caster == 0.0f) //just started, first time
     {
         angle = (float)rand_norm() * (1.0f - cur_dist / MIN_QUIET_DISTANCE) * static_cast<float>(M_PI / 3) + (float)rand_norm() * static_cast<float>(M_PI * 2 / 3);
         i_to_distance_from_caster = MIN_QUIET_DISTANCE;
         i_only_forward = true;
     }
     else if (cur_dist < MIN_QUIET_DISTANCE)
     {
         angle = static_cast<float>(M_PI / 6) + (float)rand_norm() * static_cast<float>(M_PI * 2 / 3);
         i_to_distance_from_caster = cur_dist * 2 / 3 + (float)rand_norm() * (MIN_QUIET_DISTANCE - cur_dist * 2 / 3);
     }
     else if (cur_dist > MAX_QUIET_DISTANCE)
     {
         angle = (float)rand_norm() * static_cast<float>(M_PI / 3) + static_cast<float>(M_PI * 2 / 3);
         i_to_distance_from_caster = MIN_QUIET_DISTANCE + 2.5f + (float)rand_norm() * (MAX_QUIET_DISTANCE - MIN_QUIET_DISTANCE - 2.5f);
     }
     else
     {
         angle = (float)rand_norm() * static_cast<float>(M_PI);
         i_to_distance_from_caster = MIN_QUIET_DISTANCE + 2.5f + (float)rand_norm() * (MAX_QUIET_DISTANCE - MIN_QUIET_DISTANCE - 2.5f);
     }
     int8 sign = (float)rand_norm() > 0.5f ? 1 : -1;
     i_cur_angle = sign * angle + angle_to_caster;
     // current distance
     i_last_distance_from_caster = cur_dist;
     return true;
 }
References ObjectAccessor::GetUnit(), MAX_QUIET_DISTANCE, MIN_QUIET_DISTANCE, rand_norm(), and urand().
_setTargetLocation()
template<class T > template void FleeingMovementGenerator< T >::_setTargetLocation (T *) private
Definition at line 31 of file FleeingMovementGenerator.cpp.
 {
     if (!owner)
         return;
     if (owner->HasUnitState(UNIT_STATE_NOT_MOVE) || owner->IsMovementPreventedByCasting())
     {
         return;
     }
     if (!_setMoveData(owner))
         return;
     float x, y, z;
     if (!_getPoint(owner, x, y, z)) {
         i_nextCheckTime.Reset(100);
         return;
     }
     owner->AddUnitState(UNIT_STATE_FLEEING_MOVE);
     Movement::MoveSplineInit init(owner);
     init.MoveTo(x, y, z, true);
     init.SetWalk(false);
     init.Launch();
 }
DoFinalize() [1/2]
void FleeingMovementGenerator< Player >::DoFinalize (Player * owner)
Definition at line 324 of file FleeingMovementGenerator.cpp.
 {
     owner->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_FLEEING);
     owner->ClearUnitState(UNIT_STATE_FLEEING | UNIT_STATE_FLEEING_MOVE);
 }
References Unit::ClearUnitState(), Object::RemoveFlag(), UNIT_FIELD_FLAGS, UNIT_FLAG_FLEEING, UNIT_STATE_FLEEING, and UNIT_STATE_FLEEING_MOVE.
DoFinalize() [2/2]
template<class T > void FleeingMovementGenerator< T >::DoFinalize (T *)
DoInitialize()
template<class T > template void FleeingMovementGenerator< T >::DoInitialize (T *)
Definition at line 275 of file FleeingMovementGenerator.cpp.
 {
     if (!owner)
         return;
     owner->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_FLEEING);
     owner->AddUnitState(UNIT_STATE_FLEEING | UNIT_STATE_FLEEING_MOVE);
     _Init(owner);
     if (Unit* fright = ObjectAccessor::GetUnit(*owner, i_frightGUID))
     {
         i_caster_x = fright->GetPositionX();
         i_caster_y = fright->GetPositionY();
         i_caster_z = fright->GetPositionZ();
     }
     else
     {
         i_caster_x = owner->GetPositionX();
         i_caster_y = owner->GetPositionY();
         i_caster_z = owner->GetPositionZ();
     }
     i_only_forward = true;
     i_cur_angle = 0.0f;
     i_last_distance_from_caster = 0.0f;
     i_to_distance_from_caster = 0.0f;
     _setTargetLocation(owner);
 }
References ObjectAccessor::GetUnit(), UNIT_FIELD_FLAGS, UNIT_FLAG_FLEEING, UNIT_STATE_FLEEING, and UNIT_STATE_FLEEING_MOVE.
DoReset()
template<class T > template void FleeingMovementGenerator< T >::DoReset (T *)
Definition at line 340 of file FleeingMovementGenerator.cpp.
 {
     DoInitialize(owner);
 }
DoUpdate()
template<class T > template bool FleeingMovementGenerator< T >::DoUpdate (T * , uint32)
Definition at line 346 of file FleeingMovementGenerator.cpp.
 {
     if (!owner || !owner->IsAlive())
         return false;
     if (owner->HasUnitState(UNIT_STATE_NOT_MOVE) || owner->IsMovementPreventedByCasting())
     {
         owner->StopMoving();
         return true;
     }
     i_nextCheckTime.Update(time_diff);
     if (i_nextCheckTime.Passed() && owner->movespline->Finalized())
         _setTargetLocation(owner);
     return true;
 }
References UNIT_STATE_NOT_MOVE.
GetMovementGeneratorType()
template<class T > MovementGeneratorType FleeingMovementGenerator< T >::GetMovementGeneratorType () inline virtual
Implements MovementGenerator.
Definition at line 34 of file FleeingMovementGenerator.h.
 { return FLEEING_MOTION_TYPE; }
References FLEEING_MOTION_TYPE.
Member Data Documentation
i_caster_x
template<class T > float FleeingMovementGenerator< T >::i_caster_x private
Definition at line 46 of file FleeingMovementGenerator.h.
i_caster_y
template<class T > float FleeingMovementGenerator< T >::i_caster_y private
Definition at line 47 of file FleeingMovementGenerator.h.
i_caster_z
template<class T > float FleeingMovementGenerator< T >::i_caster_z private
Definition at line 48 of file FleeingMovementGenerator.h.
i_cur_angle
template<class T > float FleeingMovementGenerator< T >::i_cur_angle private
Definition at line 51 of file FleeingMovementGenerator.h.
i_frightGUID
template<class T > ObjectGuid FleeingMovementGenerator< T >::i_frightGUID private
Definition at line 52 of file FleeingMovementGenerator.h.
i_last_distance_from_caster
template<class T > float FleeingMovementGenerator< T >::i_last_distance_from_caster private
Definition at line 49 of file FleeingMovementGenerator.h.
i_nextCheckTime
template<class T > TimeTracker FleeingMovementGenerator< T >::i_nextCheckTime private
Definition at line 53 of file FleeingMovementGenerator.h.
i_only_forward
template<class T > bool FleeingMovementGenerator< T >::i_only_forward private
Definition at line 44 of file FleeingMovementGenerator.h.
i_to_distance_from_caster
template<class T > float FleeingMovementGenerator< T >::i_to_distance_from_caster private
Definition at line 50 of file FleeingMovementGenerator.h.
is_land_ok
template<class T > bool FleeingMovementGenerator< T >::is_land_ok private
Definition at line 43 of file FleeingMovementGenerator.h.
is_water_ok
template<class T > bool FleeingMovementGenerator< T >::is_water_ok private
Definition at line 42 of file FleeingMovementGenerator.h.
The documentation for this class was generated from the following files:
src/server/game/Movement/MovementGenerators/FleeingMovementGenerator.h
src/server/game/Movement/MovementGenerators/FleeingMovementGenerator.cpp