Azerotcore-wotlk: AuthHelper Namespace Reference
AuthHelper Namespace Reference
Functions
bool IsPreBCAcceptedClientBuild (uint32 build)
bool IsPostBCAcceptedClientBuild (uint32 build)
bool IsAcceptedClientBuild (uint32 build)
Variables
constexpr static uint32 MAX_PRE_BC_CLIENT_BUILD = 6141
Function Documentation
IsAcceptedClientBuild()
bool AuthHelper::IsAcceptedClientBuild (uint32 build)
Definition at line 35 of file AuthCodes.cpp.
     {
         return sRealmList->GetBuildInfo(build) != nullptr;
     }
References sRealmList.
Referenced by AuthSession::LogonChallengeCallback().
IsPostBCAcceptedClientBuild()
bool AuthHelper::IsPostBCAcceptedClientBuild (uint32 build)
Definition at line 30 of file AuthCodes.cpp.
     {
         return build > MAX_PRE_BC_CLIENT_BUILD && sRealmList->GetBuildInfo(build);
     }
References MAX_PRE_BC_CLIENT_BUILD, and sRealmList.
Referenced by AuthSession::HandleLogonChallenge(), and AuthSession::HandleReconnectChallenge().
IsPreBCAcceptedClientBuild()
bool AuthHelper::IsPreBCAcceptedClientBuild (uint32 build)
Definition at line 25 of file AuthCodes.cpp.
     {
         return build <= MAX_PRE_BC_CLIENT_BUILD && sRealmList->GetBuildInfo(build);
     }
References MAX_PRE_BC_CLIENT_BUILD, and sRealmList.
Referenced by AuthSession::HandleLogonChallenge(), AuthSession::HandleReconnectChallenge(), and AuthSession::RealmListCallback().
Variable Documentation
MAX_PRE_BC_CLIENT_BUILD
constexpr static uint32 AuthHelper::MAX_PRE_BC_CLIENT_BUILD = 6141 static constexpr
Definition at line 23 of file AuthCodes.cpp.
Referenced by IsPostBCAcceptedClientBuild(), and IsPreBCAcceptedClientBuild().