Azerotcore-wotlk: npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI Struct Reference
npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI Struct Reference
Public Member Functions
npc_muradin_bronzebeard_igbAI (Creature *creature)
void sGossipSelect (Player *, uint32, uint32) override
void EnterCombat (Unit *) override
void EnterEvadeMode () override
void DoAction (int32 action) override
void SetData (uint32 type, uint32 data) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void AttackStart (Unit *victim) override
bool CanAIAttack (const Unit *target) const override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
EventMap _events
PassengerController _controller
InstanceScript * _instance
time_t _firstMageCooldown
time_t _riflemanYellCooldown
time_t _mortarYellCooldown
uint16 checkTimer
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1078 of file boss_icecrown_gunship_battle.cpp.
Constructor & Destructor Documentation
npc_muradin_bronzebeard_igbAI()
npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::npc_muradin_bronzebeard_igbAI (Creature * creature) inline
Definition at line 1080 of file boss_icecrown_gunship_battle.cpp.
                                                           : ScriptedAI(creature), _instance(creature->GetInstanceScript())
         {
             _events.Reset();
             _controller.ResetSlots(TEAM_ALLIANCE, creature->GetTransport()->ToMotionTransport());
             me->SetRegeneratingHealth(false);
             me->m_CombatDistance = 70.0f;
             _firstMageCooldown = time(nullptr) + 45;
             _riflemanYellCooldown = time_t(0);
             _mortarYellCooldown = time_t(0);
             checkTimer = 1000;
         }
References _controller, _events, _firstMageCooldown, _mortarYellCooldown, _riflemanYellCooldown, checkTimer, WorldObject::GetTransport(), Creature::m_CombatDistance, ScriptedAI::me, EventMap::Reset(), PassengerController::ResetSlots(), Creature::SetRegeneratingHealth(), TEAM_ALLIANCE, and GameObject::ToMotionTransport().
Member Function Documentation
AttackStart()
void npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::AttackStart (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1372 of file boss_icecrown_gunship_battle.cpp.
         {
             if (victim && me->Attack(victim, true))
             {
                 if (victim->GetPositionZ() < 478.0f)
                     me->GetMotionMaster()->MoveChase(victim);
                 else
                 {
                     float x, y, z, o;
                     me->GetHomePosition(x, y, z, o);
                     me->GetMotionMaster()->MovePoint(0, x, y, z, false);
                 }
             }
         }
References Unit::Attack(), Creature::GetHomePosition(), Unit::GetMotionMaster(), Position::GetPositionZ(), ScriptedAI::me, MotionMaster::MoveChase(), and MotionMaster::MovePoint().
CanAIAttack()
bool npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::CanAIAttack (const Unit * target) const inline override virtual
Reimplemented from UnitAI.
Definition at line 1387 of file boss_icecrown_gunship_battle.cpp.
         {
             if (_instance->GetBossState(DATA_ICECROWN_GUNSHIP_BATTLE) != IN_PROGRESS)
                 return false;
             if (target->GetEntry() == NPC_KOR_KRON_REAVER || target->GetEntry() == NPC_KOR_KRON_SERGEANT)
                 return target->ToCreature()->GetReactState() != REACT_PASSIVE;
             return target->GetTransport() == me->GetTransport() && target->GetPositionY() > (_instance->GetData(DATA_TEAMID_IN_INSTANCE) == TEAM_ALLIANCE ? 2042.0f : 2445.0f);
         }
References _instance, DATA_ICECROWN_GUNSHIP_BATTLE, DATA_TEAMID_IN_INSTANCE, InstanceScript::GetBossState(), ZoneScript::GetData(), Object::GetEntry(), Position::GetPositionY(), Creature::GetReactState(), WorldObject::GetTransport(), IN_PROGRESS, ScriptedAI::me, NPC_KOR_KRON_REAVER, NPC_KOR_KRON_SERGEANT, REACT_PASSIVE, TEAM_ALLIANCE, and Object::ToCreature().
Referenced by UpdateAI().
DamageTaken()
void npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1201 of file boss_icecrown_gunship_battle.cpp.
         {
             if (me->HealthBelowPctDamaged(65, damage) && !me->HasAura(SPELL_TASTE_OF_BLOOD))
                 me->CastSpell(me, SPELL_TASTE_OF_BLOOD, true);
             if (damage >= me->GetHealth())
                 damage = me->GetHealth() - 1;
         }
References Unit::CastSpell(), Unit::GetHealth(), Unit::HasAura(), Unit::HealthBelowPctDamaged(), ScriptedAI::me, and SPELL_TASTE_OF_BLOOD.
DoAction()
void npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 1127 of file boss_icecrown_gunship_battle.cpp.
         {
             if (action == ACTION_ENEMY_GUNSHIP_TALK)
             {
                 _instance->SetBossState(DATA_ICECROWN_GUNSHIP_BATTLE, IN_PROGRESS);
                 me->GetMap()->SetZoneMusic(AREA_ICECROWN_CITADEL, MUSIC_ENCOUNTER);
                 if (Creature* saurfang = me->FindNearestCreature(NPC_IGB_HIGH_OVERLORD_SAURFANG, 200.0f))
                     saurfang->AI()->DoAction(ACTION_SPAWN_ALL_ADDS);
                 Talk(SAY_MURADIN_INTRO_6);
                 _events.ScheduleEvent(EVENT_INTRO_A_6, 5000);
                 _events.ScheduleEvent(EVENT_INTRO_A_7, 11000);
                 _events.ScheduleEvent(EVENT_KEEP_PLAYER_IN_COMBAT, 1);
                 if (Creature* orgrimsHammer = me->FindNearestCreature(NPC_ORGRIMS_HAMMER, 200.0f))
                     _instance->SendEncounterUnit(ENCOUNTER_FRAME_ENGAGE, orgrimsHammer, 1);
                 if (Creature* skybreaker = me->FindNearestCreature(NPC_THE_SKYBREAKER, 200.0f))
                 {
                     _instance->SendEncounterUnit(ENCOUNTER_FRAME_ENGAGE, skybreaker, 2);
                     skybreaker->CastSpell(skybreaker, SPELL_CHECK_FOR_PLAYERS, true);
                 }
             }
             else if (action == ACTION_SPAWN_MAGE)
             {
                 time_t now = time(nullptr);
                 if (_firstMageCooldown > now)
                     _events.ScheduleEvent(EVENT_SUMMON_MAGE, (_firstMageCooldown - now) * IN_MILLISECONDS);
                 else
                     _events.ScheduleEvent(EVENT_SUMMON_MAGE, 1);
             }
             else if (action == ACTION_SPAWN_ALL_ADDS)
             {
                 _events.ScheduleEvent(EVENT_ADDS, 12000);
                 _events.ScheduleEvent(EVENT_CHECK_RIFLEMAN, 13000);
                 _events.ScheduleEvent(EVENT_CHECK_MORTAR, 13000);
                 if (Is25ManRaid())
                     _controller.SummonCreatures(me, SLOT_MAGE_1, SLOT_MORTAR_4);
                 else
                 {
                     _controller.SummonCreatures(me, SLOT_MAGE_1, SLOT_MAGE_2);
                     _controller.SummonCreatures(me, SLOT_MORTAR_1, SLOT_MORTAR_2);
                     _controller.SummonCreatures(me, SLOT_RIFLEMAN_1, SLOT_RIFLEMAN_4);
                 }
             }
             else if (action == ACTION_EXIT_SHIP)
             {
                 G3D::Vector3 points[MuradinExitPathSize];
                 for (uint8 i = 0; i < MuradinExitPathSize; ++i)
                 {
                     points[i].x = MuradinExitPath[i].GetPositionX();
                     points[i].y = MuradinExitPath[i].GetPositionY();
                     points[i].z = MuradinExitPath[i].GetPositionZ();
                 }
                 Movement::PointsArray path(points, points + MuradinExitPathSize);
                 me->SetWalk(true);
                 Movement::MoveSplineInit init(me);
                 init.DisableTransportPathTransformations();
                 init.MovebyPath(path, 0);
                 init.Launch();
                 me->DespawnOrUnsummon(18000);
             }
         }
References _controller, _events, _firstMageCooldown, _instance, ACTION_ENEMY_GUNSHIP_TALK, ACTION_EXIT_SHIP, ACTION_SPAWN_ALL_ADDS, ACTION_SPAWN_MAGE, AREA_ICECROWN_CITADEL, DATA_ICECROWN_GUNSHIP_BATTLE, Creature::DespawnOrUnsummon(), Movement::MoveSplineInit::DisableTransportPathTransformations(), ENCOUNTER_FRAME_ENGAGE, EVENT_ADDS, EVENT_CHECK_MORTAR, EVENT_CHECK_RIFLEMAN, EVENT_INTRO_A_6, EVENT_INTRO_A_7, EVENT_KEEP_PLAYER_IN_COMBAT, EVENT_SUMMON_MAGE, WorldObject::FindNearestCreature(), WorldObject::GetMap(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), IN_MILLISECONDS, IN_PROGRESS, ScriptedAI::Is25ManRaid(), Movement::MoveSplineInit::Launch(), ScriptedAI::me, Movement::MoveSplineInit::MovebyPath(), MuradinExitPath, MuradinExitPathSize, MUSIC_ENCOUNTER, NPC_IGB_HIGH_OVERLORD_SAURFANG, NPC_ORGRIMS_HAMMER, NPC_THE_SKYBREAKER, SAY_MURADIN_INTRO_6, EventMap::ScheduleEvent(), InstanceScript::SendEncounterUnit(), InstanceScript::SetBossState(), Creature::SetWalk(), Map::SetZoneMusic(), SLOT_MAGE_1, SLOT_MAGE_2, SLOT_MORTAR_1, SLOT_MORTAR_2, SLOT_MORTAR_4, SLOT_RIFLEMAN_1, SLOT_RIFLEMAN_4, SPELL_CHECK_FOR_PLAYERS, PassengerController::SummonCreatures(), and CreatureAI::Talk().
EnterCombat()
void npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1107 of file boss_icecrown_gunship_battle.cpp.
         {
             if (_instance->GetData(DATA_TEAMID_IN_INSTANCE) == TEAM_ALLIANCE && !me->HasAura(SPELL_FRIENDLY_BOSS_DAMAGE_MOD))
                 me->CastSpell(me, SPELL_FRIENDLY_BOSS_DAMAGE_MOD, true);
             if (!me->HasAura(SPELL_BATTLE_FURY))
                 me->CastSpell(me, SPELL_BATTLE_FURY, true);
             _events.CancelEvent(EVENT_CLEAVE);
             _events.ScheduleEvent(EVENT_CLEAVE, urand(3000, 6000));
         }
References _events, _instance, EventMap::CancelEvent(), Unit::CastSpell(), DATA_TEAMID_IN_INSTANCE, EVENT_CLEAVE, ZoneScript::GetData(), Unit::HasAura(), ScriptedAI::me, EventMap::ScheduleEvent(), SPELL_BATTLE_FURY, SPELL_FRIENDLY_BOSS_DAMAGE_MOD, TEAM_ALLIANCE, and urand().
EnterEvadeMode()
void npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 1117 of file boss_icecrown_gunship_battle.cpp.
         {
             if (!me->IsAlive())
                 return;
             me->DeleteThreatList();
             me->CombatStop(true);
             me->GetMotionMaster()->MoveTargetedHome();
             Reset();
         }
References Unit::CombatStop(), Unit::DeleteThreatList(), Unit::GetMotionMaster(), Unit::IsAlive(), ScriptedAI::me, MotionMaster::MoveTargetedHome(), and ScriptedAI::Reset().
SetData()
void npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from UnitAI.
Definition at line 1191 of file boss_icecrown_gunship_battle.cpp.
         {
             if (type == ACTION_CLEAR_SLOT)
             {
                 _controller.ClearSlot(PassengerSlots(data));
                 if (data == SLOT_FREEZE_MAGE)
                     _events.ScheduleEvent(EVENT_SUMMON_MAGE, urand(30000, 33500));
             }
         }
References _controller, _events, ACTION_CLEAR_SLOT, PassengerController::ClearSlot(), EVENT_SUMMON_MAGE, EventMap::ScheduleEvent(), SLOT_FREEZE_MAGE, and urand().
sGossipSelect()
void npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::sGossipSelect (Player * , uint32 , uint32) inline override virtual
Reimplemented from UnitAI.
Definition at line 1092 of file boss_icecrown_gunship_battle.cpp.
         {
             if (!me->HasFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP))
                 return;
             me->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
             me->GetTransport()->setActive(true);
             me->GetTransport()->ToMotionTransport()->EnableMovement(true);
             _events.ScheduleEvent(EVENT_INTRO_A_1, 5000);
             _events.ScheduleEvent(EVENT_INTRO_A_2, 10000);
             _events.ScheduleEvent(EVENT_INTRO_SUMMON_ORGRIMS_HAMMER, 28000);
             _events.ScheduleEvent(EVENT_INTRO_A_3, 33000);
             _events.ScheduleEvent(EVENT_INTRO_A_4, 39000);
             _events.ScheduleEvent(EVENT_INTRO_A_5, 45000);
         }
References _events, MotionTransport::EnableMovement(), EVENT_INTRO_A_1, EVENT_INTRO_A_2, EVENT_INTRO_A_3, EVENT_INTRO_A_4, EVENT_INTRO_A_5, EVENT_INTRO_SUMMON_ORGRIMS_HAMMER, WorldObject::GetTransport(), Object::HasFlag(), ScriptedAI::me, Object::RemoveFlag(), EventMap::ScheduleEvent(), WorldObject::setActive(), GameObject::ToMotionTransport(), UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
UpdateAI()
void npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1210 of file boss_icecrown_gunship_battle.cpp.
         {
             if (_instance->GetBossState(DATA_ICECROWN_GUNSHIP_BATTLE) == IN_PROGRESS)
             {
                 if (me->GetVictim())
                 {
                     if (me->GetMotionMaster()->GetCurrentMovementGeneratorType() == CHASE_MOTION_TYPE)
                     {
                         if (me->GetVictim()->GetPositionZ() >= 478.0f)
{
                             float x, y, z, o;
                             me->GetHomePosition(x, y, z, o);
                             me->GetMotionMaster()->MovePoint(0, x, y, z, false);
                         }
                     }
                     else
                     {
                         if (me->GetVictim()->GetPositionZ() < 478.0f)
                             me->GetMotionMaster()->MoveChase(me->GetVictim());
                     }
                 }
                 if (checkTimer <= diff)
                 {
                     checkTimer = 1000;
                     Map::PlayerList const& pl = me->GetMap()->GetPlayers();
                     for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                         if (Player* p = itr->GetSource())
                             if (CanAIAttack(p) && me->IsValidAttackTarget(p))
{
                                 me->SetInCombatWith(p);
                                 p->SetInCombatWith(me);
                                 me->AddThreat(p, 0.0f);
                             }
                 }
                 else
                     checkTimer -= diff;
             }
             UpdateVictim();
             _events.Update(diff);
             switch (_events.ExecuteEvent())
             {
                 case 0:
                     break;
                 case EVENT_INTRO_A_1:
                     Talk(SAY_MURADIN_INTRO_1);
                     break;
                 case EVENT_INTRO_A_2:
                     Talk(SAY_MURADIN_INTRO_2);
                     break;
                 case EVENT_INTRO_SUMMON_ORGRIMS_HAMMER:
                     sTransportMgr->CreateTransport(GO_ORGRIMS_HAMMER_A, 0, me->GetMap());
                     break;
                 case EVENT_INTRO_A_3:
                     Talk(SAY_MURADIN_INTRO_3);
                     break;
                 case EVENT_INTRO_A_4:
                     Talk(SAY_MURADIN_INTRO_4);
                     break;
                 case EVENT_INTRO_A_5:
                     Talk(SAY_MURADIN_INTRO_5);
                     break;
                 case EVENT_INTRO_A_6:
                     if (Creature* saurfang = me->FindNearestCreature(NPC_IGB_HIGH_OVERLORD_SAURFANG, 200.0f))
                         saurfang->AI()->Talk(SAY_SAURFANG_INTRO_A);
                     break;
                 case EVENT_INTRO_A_7:
                     Talk(SAY_MURADIN_INTRO_7);
                     break;
                 case EVENT_KEEP_PLAYER_IN_COMBAT:
                     if (_instance->GetBossState(DATA_ICECROWN_GUNSHIP_BATTLE) == IN_PROGRESS)
                     {
                         //_instance->DoCastSpellOnPlayers(SPELL_LOCK_PLAYERS_AND_TAP_CHEST);
                         Map::PlayerList const& pl = me->GetMap()->GetPlayers();
                         for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                             if (Player* p = itr->GetSource())
                                 if (!p->IsGameMaster())
                                     p->SetInCombatState(true);
                         _events.ScheduleEvent(EVENT_KEEP_PLAYER_IN_COMBAT, 4000);
                     }
                     break;
                 case EVENT_SUMMON_MAGE:
                     Talk(SAY_MURADIN_SORCERERS);
                     _controller.SummonCreatures(me, SLOT_FREEZE_MAGE, SLOT_FREEZE_MAGE);
                     break;
                 case EVENT_ADDS:
                     Talk(SAY_MURADIN_ENTER_ORGRIMMS_HAMMER);
                     _controller.SummonCreatures(me, SLOT_MAGE_1, SLOT_MAGE_2);
                     _controller.SummonCreatures(me, SLOT_MARINE_1, Is25ManRaid() ? SLOT_MARINE_4 : SLOT_MARINE_2);
                     _controller.SummonCreatures(me, SLOT_SERGEANT_1, Is25ManRaid() ? SLOT_SERGEANT_2 : SLOT_SERGEANT_1);
                     if (MotionTransport* skybreaker = (me->GetTransport() ? me->GetTransport()->ToMotionTransport() : nullptr))
                     {
                         float x, y, z, o;
                         SkybreakerTeleportPortal.GetPosition(x, y, z, o);
                         skybreaker->CalculatePassengerPosition(x, y, z, &o);
                         me->SummonCreature(NPC_TELEPORT_PORTAL, x, y, z, o, TEMPSUMMON_TIMED_DESPAWN, 21000);
                     }
                     if (Transport* transport = _instance->instance->GetTransport(_instance->GetGuidData(DATA_ICECROWN_GUNSHIP_BATTLE)))
                         if (MotionTransport* orgrimsHammer = transport->ToMotionTransport())
{
                             float x, y, z, o;
                             OrgrimsHammerTeleportExit.GetPosition(x, y, z, o);
                             orgrimsHammer->CalculatePassengerPosition(x, y, z, &o);
                             me->SummonCreature(NPC_TELEPORT_EXIT, x, y, z, o, TEMPSUMMON_TIMED_DESPAWN, 23000);
                         }
                     _events.ScheduleEvent(EVENT_ADDS_BOARD_YELL, 6000);
                     _events.ScheduleEvent(EVENT_ADDS, 60000);
                     break;
                 case EVENT_ADDS_BOARD_YELL:
                     if (Creature* saurfang = me->FindNearestCreature(NPC_IGB_HIGH_OVERLORD_SAURFANG, 200.0f))
                         saurfang->AI()->Talk(SAY_SAURFANG_BOARD);
                     break;
                 case EVENT_CHECK_RIFLEMAN:
                     if (_controller.SummonCreatures(me, SLOT_RIFLEMAN_1, Is25ManRaid() ? SLOT_RIFLEMAN_8 : SLOT_RIFLEMAN_4))
                     {
                         if (_riflemanYellCooldown < time(nullptr))
{
                             Talk(SAY_MURADIN_RIFLEMAN);
                             _riflemanYellCooldown = time(nullptr) + 5;
                         }
                     }
                     _events.ScheduleEvent(EVENT_CHECK_RIFLEMAN, 1500);
                     break;
                 case EVENT_CHECK_MORTAR:
                     if (_controller.SummonCreatures(me, SLOT_MORTAR_1, Is25ManRaid() ? SLOT_MORTAR_4 : SLOT_MORTAR_2))
                     {
                         if (_mortarYellCooldown < time(nullptr))
{
                             Talk(SAY_MURADIN_MORTAR);
                             _mortarYellCooldown = time(nullptr) + 5;
                         }
                     }
                     _events.ScheduleEvent(EVENT_CHECK_MORTAR, 1500);
                     break;
                 case EVENT_CLEAVE:
                     if (me->GetVictim())
                         me->CastSpell(me->GetVictim(), SPELL_CLEAVE, false);
                     _events.ScheduleEvent(EVENT_CLEAVE, urand(4000, 8000));
                     break;
                 default:
                     break;
             }
             if (!me->GetVictim() || me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             if (me->IsWithinMeleeRange(me->GetVictim()))
                 DoMeleeAttackIfReady();
             else if (me->isAttackReady())
             {
                 me->SetOrientation(me->GetAngle(me->GetVictim()));
                 me->CastSpell(me->GetVictim(), SPELL_RENDING_THROW, false);
                 me->resetAttackTimer();
             }
         }
References _controller, _events, _instance, _mortarYellCooldown, _riflemanYellCooldown, Unit::AddThreat(), MapRefMgr::begin(), CanAIAttack(), Unit::CastSpell(), CHASE_MOTION_TYPE, checkTimer, DATA_ICECROWN_GUNSHIP_BATTLE, UnitAI::DoMeleeAttackIfReady(), MapRefMgr::end(), EVENT_ADDS, EVENT_ADDS_BOARD_YELL, EVENT_CHECK_MORTAR, EVENT_CHECK_RIFLEMAN, EVENT_CLEAVE, EVENT_INTRO_A_1, EVENT_INTRO_A_2, EVENT_INTRO_A_3, EVENT_INTRO_A_4, EVENT_INTRO_A_5, EVENT_INTRO_A_6, EVENT_INTRO_A_7, EVENT_INTRO_SUMMON_ORGRIMS_HAMMER, EVENT_KEEP_PLAYER_IN_COMBAT, EVENT_SUMMON_MAGE, EventMap::ExecuteEvent(), WorldObject::FindNearestCreature(), Position::GetAngle(), InstanceScript::GetBossState(), MotionMaster::GetCurrentMovementGeneratorType(), InstanceScript::GetGuidData(), Creature::GetHomePosition(), WorldObject::GetMap(), Unit::GetMotionMaster(), Map::GetPlayers(), Position::GetPosition(), Position::GetPositionZ(), WorldObject::GetTransport(), Map::GetTransport(), Unit::GetVictim(), GO_ORGRIMS_HAMMER_A, Unit::HasUnitState(), IN_PROGRESS, InstanceScript::instance, ScriptedAI::Is25ManRaid(), Unit::isAttackReady(), Unit::IsValidAttackTarget(), Unit::IsWithinMeleeRange(), ScriptedAI::me, MotionMaster::MoveChase(), MotionMaster::MovePoint(), NPC_IGB_HIGH_OVERLORD_SAURFANG, NPC_TELEPORT_EXIT, NPC_TELEPORT_PORTAL, OrgrimsHammerTeleportExit, Unit::resetAttackTimer(), SAY_MURADIN_ENTER_ORGRIMMS_HAMMER, SAY_MURADIN_INTRO_1, SAY_MURADIN_INTRO_2, SAY_MURADIN_INTRO_3, SAY_MURADIN_INTRO_4, SAY_MURADIN_INTRO_5, SAY_MURADIN_INTRO_7, SAY_MURADIN_MORTAR, SAY_MURADIN_RIFLEMAN, SAY_MURADIN_SORCERERS, SAY_SAURFANG_BOARD, SAY_SAURFANG_INTRO_A, EventMap::ScheduleEvent(), Unit::SetInCombatWith(), Position::SetOrientation(), SkybreakerTeleportPortal, SLOT_FREEZE_MAGE, SLOT_MAGE_1, SLOT_MAGE_2, SLOT_MARINE_1, SLOT_MARINE_2, SLOT_MARINE_4, SLOT_MORTAR_1, SLOT_MORTAR_2, SLOT_MORTAR_4, SLOT_RIFLEMAN_1, SLOT_RIFLEMAN_4, SLOT_RIFLEMAN_8, SLOT_SERGEANT_1, SLOT_SERGEANT_2, SPELL_CLEAVE, SPELL_RENDING_THROW, sTransportMgr, WorldObject::SummonCreature(), PassengerController::SummonCreatures(), CreatureAI::Talk(), TEMPSUMMON_TIMED_DESPAWN, GameObject::ToMotionTransport(), UNIT_STATE_CASTING, EventMap::Update(), CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
_controller
PassengerController npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::_controller private
Definition at line 1398 of file boss_icecrown_gunship_battle.cpp.
Referenced by DoAction(), npc_muradin_bronzebeard_igbAI(), SetData(), and UpdateAI().
_events
EventMap npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::_events private
Definition at line 1397 of file boss_icecrown_gunship_battle.cpp.
Referenced by DoAction(), EnterCombat(), npc_muradin_bronzebeard_igbAI(), SetData(), sGossipSelect(), and UpdateAI().
_firstMageCooldown
time_t npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::_firstMageCooldown private
Definition at line 1400 of file boss_icecrown_gunship_battle.cpp.
Referenced by DoAction(), and npc_muradin_bronzebeard_igbAI().
_instance
InstanceScript* npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::_instance private
Definition at line 1399 of file boss_icecrown_gunship_battle.cpp.
Referenced by CanAIAttack(), DoAction(), EnterCombat(), and UpdateAI().
_mortarYellCooldown
time_t npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::_mortarYellCooldown private
Definition at line 1402 of file boss_icecrown_gunship_battle.cpp.
Referenced by npc_muradin_bronzebeard_igbAI(), and UpdateAI().
_riflemanYellCooldown
time_t npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::_riflemanYellCooldown private
Definition at line 1401 of file boss_icecrown_gunship_battle.cpp.
Referenced by npc_muradin_bronzebeard_igbAI(), and UpdateAI().
checkTimer
uint16 npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::checkTimer private
Definition at line 1403 of file boss_icecrown_gunship_battle.cpp.
Referenced by npc_muradin_bronzebeard_igbAI(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp