Azerotcore-wotlk: SocketMgr< SocketType > Class Template Reference
SocketMgr< SocketType > Class Template Reference abstract
#include <SocketMgr.h>
Public Member Functions
virtual ~SocketMgr ()
virtual bool StartNetwork (Acore::Asio::IoContext &ioContext, std::string const &bindIp, uint16 port, int threadCount)
virtual void StopNetwork ()
void Wait ()
virtual void OnSocketOpen (tcp::socket &&sock, uint32 threadIndex)
int32 GetNetworkThreadCount () const
uint32 SelectThreadWithMinConnections () const
std::pair< tcp::socket *, uint32 > GetSocketForAccept ()
Protected Member Functions
SocketMgr ()
virtual NetworkThread< SocketType > * CreateThreads () const =0
Protected Attributes
AsyncAcceptor * _acceptor
NetworkThread< SocketType > * _threads
int32 _threadCount
Detailed Description
template<class SocketType>
class SocketMgr< SocketType >
Definition at line 30 of file SocketMgr.h.
Constructor & Destructor Documentation
~SocketMgr()
template<class SocketType > virtual SocketMgr< SocketType >::~SocketMgr () inline virtual
Definition at line 33 of file SocketMgr.h.
     {
         ASSERT(!_threads && !_acceptor && !_threadCount, "StopNetwork must be called prior to SocketMgr destruction");
     }
References SocketMgr< SocketType >::_acceptor, SocketMgr< SocketType >::_threadCount, SocketMgr< SocketType >::_threads, and ASSERT.
SocketMgr()
template<class SocketType > SocketMgr< SocketType >::SocketMgr () inline protected
Definition at line 133 of file SocketMgr.h.
                 :
         _acceptor(nullptr), _threads(nullptr), _threadCount(0) { }
Member Function Documentation
CreateThreads()
template<class SocketType > virtual NetworkThread<SocketType>* SocketMgr< SocketType >::CreateThreads () const protected pure virtual
Implemented in WorldSocketMgr, and AuthSocketMgr.
Referenced by SocketMgr< SocketType >::StartNetwork().
GetNetworkThreadCount()
template<class SocketType > int32 SocketMgr< SocketType >::GetNetworkThreadCount () const inline
Definition at line 113 of file SocketMgr.h.
 { return _threadCount; }
References SocketMgr< SocketType >::_threadCount.
GetSocketForAccept()
template<class SocketType > std::pair<tcp::socket*, uint32> SocketMgr< SocketType >::GetSocketForAccept () inline
Definition at line 126 of file SocketMgr.h.
     {
         uint32 threadIndex = SelectThreadWithMinConnections();
         return std::make_pair(_threads[threadIndex].GetSocketForAccept(), threadIndex);
     }
References SocketMgr< SocketType >::_threads, and SocketMgr< SocketType >::SelectThreadWithMinConnections().
Referenced by SocketMgr< SocketType >::StartNetwork().
OnSocketOpen()
template<class SocketType > virtual void SocketMgr< SocketType >::OnSocketOpen (tcp::socket && sock, uint32 threadIndex) inline virtual
Reimplemented in WorldSocketMgr.
Definition at line 98 of file SocketMgr.h.
     {
         try
         {
             std::shared_ptr<SocketType> newSocket = std::make_shared<SocketType>(std::move(sock));
             newSocket->Start();
             _threads[threadIndex].AddSocket(newSocket);
         }
         catch (boost::system::system_error const& err)
         {
             LOG_WARN("network", "Failed to retrieve client's remote address %s", err.what());
         }
     }
References SocketMgr< SocketType >::_threads, LOG_WARN, and system_error().
Referenced by AuthSocketMgr::OnSocketAccept().
SelectThreadWithMinConnections()
template<class SocketType > uint32 SocketMgr< SocketType >::SelectThreadWithMinConnections () const inline
Definition at line 115 of file SocketMgr.h.
     {
         uint32 min = 0;
         for (int32 i = 1; i < _threadCount; ++i)
             if (_threads[i].GetConnectionCount() < _threads[min].GetConnectionCount())
                 min = i;
         return min;
     }
References SocketMgr< SocketType >::_threadCount, SocketMgr< SocketType >::_threads, and min.
Referenced by SocketMgr< SocketType >::GetSocketForAccept().
StartNetwork()
template<class SocketType > virtual bool SocketMgr< SocketType >::StartNetwork (Acore::Asio::IoContext & ioContext, std::string const & bindIp, uint16 port, int threadCount) inline virtual
Reimplemented in AuthSocketMgr.
Definition at line 38 of file SocketMgr.h.
     {
         ASSERT(threadCount > 0);
         AsyncAcceptor* acceptor = nullptr;
         try
         {
             acceptor = new AsyncAcceptor(ioContext, bindIp, port);
         }
         catch (boost::system::system_error const& err)
         {
             LOG_ERROR("network", "Exception caught in SocketMgr.StartNetwork (%s:%u): %s", bindIp.c_str(), port, err.what());
             return false;
         }
         if (!acceptor->Bind())
         {
             LOG_ERROR("network", "StartNetwork failed to bind socket acceptor");
             delete acceptor;
             return false;
         }
         _acceptor = acceptor;
         _threadCount = threadCount;
         _threads = CreateThreads();
         ASSERT(_threads);
         for (int32 i = 0; i < _threadCount; ++i)
             _threads[i].Start();
         _acceptor->SetSocketFactory([this]() { return GetSocketForAccept(); });
         return true;
     }
References SocketMgr< SocketType >::_acceptor, SocketMgr< SocketType >::_threadCount, SocketMgr< SocketType >::_threads, ASSERT, AsyncAcceptor::Bind(), SocketMgr< SocketType >::CreateThreads(), SocketMgr< SocketType >::GetSocketForAccept(), LOG_ERROR, AsyncAcceptor::SetSocketFactory(), and system_error().
StopNetwork()
template<class SocketType > virtual void SocketMgr< SocketType >::StopNetwork () inline virtual
Reimplemented in WorldSocketMgr.
Definition at line 74 of file SocketMgr.h.
     {
         _acceptor->Close();
         if (_threadCount != 0)
             for (int32 i = 0; i < _threadCount; ++i)
                 _threads[i].Stop();
         Wait();
         delete _acceptor;
         _acceptor = nullptr;
         delete[] _threads;
         _threads = nullptr;
         _threadCount = 0;
     }
References SocketMgr< SocketType >::_acceptor, SocketMgr< SocketType >::_threadCount, SocketMgr< SocketType >::_threads, AsyncAcceptor::Close(), and SocketMgr< SocketType >::Wait().
Wait()
template<class SocketType > void SocketMgr< SocketType >::Wait () inline
Definition at line 91 of file SocketMgr.h.
     {
         if (_threadCount != 0)
             for (int32 i = 0; i < _threadCount; ++i)
                 _threads[i].Wait();
     }
References SocketMgr< SocketType >::_threadCount, and SocketMgr< SocketType >::_threads.
Referenced by SocketMgr< SocketType >::StopNetwork().
Member Data Documentation
_acceptor
template<class SocketType > AsyncAcceptor* SocketMgr< SocketType >::_acceptor protected
Definition at line 138 of file SocketMgr.h.
Referenced by SocketMgr< SocketType >::StartNetwork(), SocketMgr< SocketType >::StopNetwork(), and SocketMgr< SocketType >::~SocketMgr().
_threadCount
template<class SocketType > int32 SocketMgr< SocketType >::_threadCount protected
Definition at line 140 of file SocketMgr.h.
Referenced by SocketMgr< SocketType >::GetNetworkThreadCount(), SocketMgr< SocketType >::SelectThreadWithMinConnections(), SocketMgr< SocketType >::StartNetwork(), SocketMgr< SocketType >::StopNetwork(), SocketMgr< SocketType >::Wait(), and SocketMgr< SocketType >::~SocketMgr().
_threads
template<class SocketType > NetworkThread<SocketType>* SocketMgr< SocketType >::_threads protected
Definition at line 139 of file SocketMgr.h.
Referenced by SocketMgr< SocketType >::GetSocketForAccept(), SocketMgr< SocketType >::OnSocketOpen(), SocketMgr< SocketType >::SelectThreadWithMinConnections(), SocketMgr< SocketType >::StartNetwork(), SocketMgr< SocketType >::StopNetwork(), SocketMgr< SocketType >::Wait(), and SocketMgr< SocketType >::~SocketMgr().
The documentation for this class was generated from the following file:
src/server/shared/Network/SocketMgr.h