Azerotcore-wotlk: ObjectWorldLoader Class Reference
ObjectWorldLoader Class Reference
Public Member Functions
ObjectWorldLoader (ObjectGridLoader &gloader)
void Visit (CorpseMapType &m)
template<class T >
void Visit (GridRefMgr< T > &)
Public Attributes
uint32 & i_corpses
Private Attributes
Cell i_cell
Map * i_map
NGridType & i_grid
Detailed Description
Definition at line 32 of file ObjectGridLoader.cpp.
Constructor & Destructor Documentation
ObjectWorldLoader()
ObjectWorldLoader::ObjectWorldLoader (ObjectGridLoader & gloader) inline explicit
Definition at line 35 of file ObjectGridLoader.cpp.
         : i_cell(gloader.i_cell), i_map(gloader.i_map), i_grid(gloader.i_grid), i_corpses(gloader.i_corpses)
     {}
Member Function Documentation
Visit() [1/2]
void ObjectWorldLoader::Visit (CorpseMapType & m)
Definition at line 151 of file ObjectGridLoader.cpp.
 {
     CellCoord cellCoord = i_cell.GetCellCoord();
     if (std::unordered_set<Corpse*> const* corpses = i_map->GetCorpsesInCell(cellCoord.GetId()))
     {
         for (Corpse* corpse : *corpses)
         {
             corpse->AddToWorld();
             GridType& cell = i_grid.GetGridType(i_cell.CellX(), i_cell.CellY());
             if (corpse->IsWorldObject())
                 cell.AddWorldObject(corpse);
             else
                 cell.AddGridObject(corpse);
             ++i_corpses;
         }
     }
 }
References Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::AddGridObject(), Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::AddWorldObject(), Cell::CellX(), Cell::CellY(), Cell::GetCellCoord(), Map::GetCorpsesInCell(), NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::GetGridType(), CoordPair< LIMIT >::GetId(), i_cell, i_corpses, i_grid, and i_map.
Visit() [2/2]
template<class T > void ObjectWorldLoader::Visit (GridRefMgr< T > &) inline
Definition at line 41 of file ObjectGridLoader.cpp.
 { }
Member Data Documentation
i_cell
Cell ObjectWorldLoader::i_cell private
Definition at line 44 of file ObjectGridLoader.cpp.
Referenced by Visit().
i_corpses
uint32& ObjectWorldLoader::i_corpses
Definition at line 48 of file ObjectGridLoader.cpp.
Referenced by Visit().
i_grid
NGridType& ObjectWorldLoader::i_grid private
Definition at line 46 of file ObjectGridLoader.cpp.
Referenced by Visit().
i_map
Map* ObjectWorldLoader::i_map private
Definition at line 45 of file ObjectGridLoader.cpp.
Referenced by Visit().
The documentation for this class was generated from the following file:
src/server/game/Grids/ObjectGridLoader.cpp