Azerotcore-wotlk: deps/argon2/argon2/encoding.h File Reference
encoding.h File Reference
#include "argon2.h"
Macros
#define ARGON2_MAX_DECODED_LANES UINT32_C(255)
#define ARGON2_MIN_DECODED_SALT_LEN UINT32_C(8)
#define ARGON2_MIN_DECODED_OUT_LEN UINT32_C(12)
Functions
int encode_string (char *dst, size_t dst_len, argon2_context *ctx, argon2_type type)
int decode_string (argon2_context *ctx, const char *str, argon2_type type)
size_t b64len (uint32_t len)
size_t numlen (uint32_t num)
Macro Definition Documentation
ARGON2_MAX_DECODED_LANES
#define ARGON2_MAX_DECODED_LANES UINT32_C(255)
Definition at line 22 of file encoding.h.
ARGON2_MIN_DECODED_OUT_LEN
#define ARGON2_MIN_DECODED_OUT_LEN UINT32_C(12)
Definition at line 24 of file encoding.h.
ARGON2_MIN_DECODED_SALT_LEN
#define ARGON2_MIN_DECODED_SALT_LEN UINT32_C(8)
Definition at line 23 of file encoding.h.
Function Documentation
b64len()
size_t b64len (uint32_t len)
Definition at line 440 of file encoding.c.
{
     size_t olen = ((size_t)len / 3) << 2;
     switch (len % 3) {
     case 2:
         olen++;
     /* fall through */
     case 1:
         olen += 2;
         break;
     }
     return olen;
 }
Referenced by argon2_encodedlen().
decode_string()
int decode_string (argon2_context * ctx, const char * str, argon2_type type)
Definition at line 258 of file encoding.c.
{
 /* check for prefix */
 #define CC(prefix)                                                             \
     do {                                                                       \
         size_t cc_len = strlen(prefix);                                        \
         if (strncmp(str, prefix, cc_len) != 0) {                               \
             return ARGON2_DECODING_FAIL;                                       \
         }                                                                      \
         str += cc_len;                                                         \
     } while ((void)0, 0)
 /* optional prefix checking with supplied code */
 #define CC_opt(prefix, code)                                                   \
     do {                                                                       \
         size_t cc_len = strlen(prefix);                                        \
         if (strncmp(str, prefix, cc_len) == 0) {                               \
             str += cc_len;                                                     \
             { code; }                                                          \
         }                                                                      \
     } while ((void)0, 0)
 /* Decoding prefix into decimal */
 #define DECIMAL(x)                                                             \
     do {                                                                       \
         unsigned long dec_x;                                                   \
         str = decode_decimal(str, &dec_x);                                     \
         if (str == NULL) {                                                     \
             return ARGON2_DECODING_FAIL;                                       \
         }                                                                      \
         (x) = dec_x;                                                           \
     } while ((void)0, 0)
 /* Decoding prefix into uint32_t decimal */
 #define DECIMAL_U32(x)                                                         \
     do {                                                                       \
         unsigned long dec_x;                                                   \
         str = decode_decimal(str, &dec_x);                                     \
         if (str == NULL || dec_x > UINT32_MAX) {                               \
             return ARGON2_DECODING_FAIL;                                       \
         }                                                                      \
         (x) = (uint32_t)dec_x;                                                 \
     } while ((void)0, 0)
 /* Decoding base64 into a binary buffer */
 #define BIN(buf, max_len, len)                                                 \
     do {                                                                       \
         size_t bin_len = (max_len);                                            \
         str = from_base64(buf, &bin_len, str);                                 \
         if (str == NULL || bin_len > UINT32_MAX) {                             \
             return ARGON2_DECODING_FAIL;                                       \
         }                                                                      \
         (len) = (uint32_t)bin_len;                                             \
     } while ((void)0, 0)
     size_t maxsaltlen = ctx->saltlen;
     size_t maxoutlen = ctx->outlen;
     int validation_result;
     const char* type_string;
     /* We should start with the argon2_type we are using */
     type_string = argon2_type2string(type, 0);
     if (!type_string) {
         return ARGON2_INCORRECT_TYPE;
     }
     CC("$");
     CC(type_string);
     /* Reading the version number if the default is suppressed */
     ctx->version = ARGON2_VERSION_10;
     CC_opt("$v=", DECIMAL_U32(ctx->version));
     CC("$m=");
     DECIMAL_U32(ctx->m_cost);
     CC(",t=");
     DECIMAL_U32(ctx->t_cost);
     CC(",p=");
     DECIMAL_U32(ctx->lanes);
     ctx->threads = ctx->lanes;
     CC("$");
     BIN(ctx->salt, maxsaltlen, ctx->saltlen);
     CC("$");
     BIN(ctx->out, maxoutlen, ctx->outlen);
     /* The rest of the fields get the default values */
     ctx->secret = NULL;
     ctx->secretlen = 0;
     ctx->ad = NULL;
     ctx->adlen = 0;
     ctx->allocate_cbk = NULL;
     ctx->free_cbk = NULL;
     ctx->flags = ARGON2_DEFAULT_FLAGS;
     /* On return, must have valid context */
     validation_result = validate_inputs(ctx);
     if (validation_result != ARGON2_OK) {
         return validation_result;
     }
     /* Can't have any additional characters */
     if (*str == 0) {
         return ARGON2_OK;
     } else {
         return ARGON2_DECODING_FAIL;
     }
 #undef CC
 #undef CC_opt
 #undef DECIMAL
 #undef BIN
 }
References Argon2_Context::ad, Argon2_Context::adlen, Argon2_Context::allocate_cbk, ARGON2_DECODING_FAIL, ARGON2_DEFAULT_FLAGS, ARGON2_INCORRECT_TYPE, ARGON2_OK, argon2_type2string(), ARGON2_VERSION_10, BIN, CC, CC_opt, DECIMAL_U32, Argon2_Context::flags, Argon2_Context::free_cbk, Argon2_Context::lanes, Argon2_Context::m_cost, NULL, Argon2_Context::out, Argon2_Context::outlen, Argon2_Context::salt, Argon2_Context::saltlen, Argon2_Context::secret, Argon2_Context::secretlen, Argon2_Context::t_cost, Argon2_Context::threads, validate_inputs(), and Argon2_Context::version.
Referenced by argon2_verify().
encode_string()
int encode_string (char * dst, size_t dst_len, argon2_context * ctx, argon2_type type)
Definition at line 373 of file encoding.c.
{
 #define SS(str)                                                                \
     do {                                                                       \
         size_t pp_len = strlen(str);                                           \
         if (pp_len >= dst_len) {                                               \
             return ARGON2_ENCODING_FAIL;                                       \
         }                                                                      \
         memcpy(dst, str, pp_len + 1);                                          \
         dst += pp_len;                                                         \
         dst_len -= pp_len;                                                     \
     } while ((void)0, 0)
 #define SX(x)                                                                  \
     do {                                                                       \
         char tmp[30];                                                          \
         sprintf(tmp, "%lu", (unsigned long)(x));                               \
         SS(tmp);                                                               \
     } while ((void)0, 0)
 #define SB(buf, len)                                                           \
     do {                                                                       \
         size_t sb_len = to_base64(dst, dst_len, buf, len);                     \
         if (sb_len == (size_t)-1) {                                            \
             return ARGON2_ENCODING_FAIL;                                       \
         }                                                                      \
         dst += sb_len;                                                         \
         dst_len -= sb_len;                                                     \
     } while ((void)0, 0)
     const char* type_string = argon2_type2string(type, 0);
     int validation_result = validate_inputs(ctx);
     if (!type_string) {
       return ARGON2_ENCODING_FAIL;
     }
     if (validation_result != ARGON2_OK) {
       return validation_result;
     }
     SS("$");
     SS(type_string);
     SS("$v=");
     SX(ctx->version);
     SS("$m=");
     SX(ctx->m_cost);
     SS(",t=");
     SX(ctx->t_cost);
     SS(",p=");
     SX(ctx->lanes);
     SS("$");
     SB(ctx->salt, ctx->saltlen);
     SS("$");
     SB(ctx->out, ctx->outlen);
     return ARGON2_OK;
 #undef SS
 #undef SX
 #undef SB
 }
References ARGON2_ENCODING_FAIL, ARGON2_OK, argon2_type2string(), Argon2_Context::lanes, Argon2_Context::m_cost, Argon2_Context::out, Argon2_Context::outlen, Argon2_Context::salt, Argon2_Context::saltlen, SB, SS, SX, Argon2_Context::t_cost, validate_inputs(), and Argon2_Context::version.
Referenced by argon2_hash().
numlen()
size_t numlen (uint32_t num)
Definition at line 455 of file encoding.c.
{
     size_t len = 1;
     while (num >= 10) {
         ++len;
         num = num / 10;
     }
     return len;
 }
Referenced by argon2_encodedlen().