Azerotcore-wotlk: Acore::NearestAttackableUnitInObjectRangeCheck Class Reference
Acore::NearestAttackableUnitInObjectRangeCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
NearestAttackableUnitInObjectRangeCheck (WorldObject const *obj, Unit const *funit, float range)
bool operator() (Unit *u)
Private Member Functions
NearestAttackableUnitInObjectRangeCheck (NearestAttackableUnitInObjectRangeCheck const &)
Private Attributes
WorldObject const * i_obj
Unit const * i_funit
float i_range
Detailed Description
Definition at line 944 of file GridNotifiers.h.
Constructor & Destructor Documentation
NearestAttackableUnitInObjectRangeCheck() [1/2]
Acore::NearestAttackableUnitInObjectRangeCheck::NearestAttackableUnitInObjectRangeCheck (WorldObject const * obj, Unit const * funit, float range) inline
Definition at line 947 of file GridNotifiers.h.
 : i_obj(obj), i_funit(funit), i_range(range) {}
NearestAttackableUnitInObjectRangeCheck() [2/2]
Acore::NearestAttackableUnitInObjectRangeCheck::NearestAttackableUnitInObjectRangeCheck (NearestAttackableUnitInObjectRangeCheck const &) private
Member Function Documentation
operator()()
bool Acore::NearestAttackableUnitInObjectRangeCheck::operator() (Unit * u) inline
Definition at line 948 of file GridNotifiers.h.
         {
             if (u->isTargetableForAttack(true, i_funit) && i_obj->IsWithinDistInMap(u, i_range) &&
                 (i_funit->IsInCombatWith(u) || u->IsHostileTo(i_funit)) && i_obj->CanSeeOrDetect(u))
             {
                 i_range = i_obj->GetDistance(u);        // use found unit range as new range limit for next check
                 return true;
             }
             return false;
         }
References WorldObject::CanSeeOrDetect(), WorldObject::GetDistance(), i_funit, i_obj, i_range, Unit::IsHostileTo(), Unit::IsInCombatWith(), Unit::isTargetableForAttack(), and WorldObject::IsWithinDistInMap().
Member Data Documentation
i_funit
Unit const* Acore::NearestAttackableUnitInObjectRangeCheck::i_funit private
Definition at line 961 of file GridNotifiers.h.
Referenced by operator()().
i_obj
WorldObject const* Acore::NearestAttackableUnitInObjectRangeCheck::i_obj private
Definition at line 960 of file GridNotifiers.h.
Referenced by operator()().
i_range
float Acore::NearestAttackableUnitInObjectRangeCheck::i_range private
Definition at line 962 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/game/Grids/Notifiers/GridNotifiers.h