Azerotcore-wotlk: formatter< TupleT, Char, enable_if_t< fmt::is_tuple_like< TupleT >::value > > Struct Template Reference
formatter< TupleT, Char, enable_if_t< fmt::is_tuple_like< TupleT >::value > > Struct Template Reference
#include <ranges.h>
Classes
struct format_each
Public Member Functions
template<typename ParseContext >
FMT_CONSTEXPR auto parse (ParseContext &ctx) -> decltype(ctx.begin())
template<typename FormatContext = format_context>
auto format (const TupleT &values, FormatContext &ctx) -> decltype(ctx.out())
Public Attributes
formatting_tuple< Char > formatting
Detailed Description
template<typename TupleT, typename Char>
struct formatter< TupleT, Char, enable_if_t< fmt::is_tuple_like< TupleT >::value > >
Definition at line 289 of file ranges.h.
Member Function Documentation
format()
template<typename TupleT , typename Char > template<typename FormatContext = format_context> auto formatter< TupleT, Char, enable_if_t< fmt::is_tuple_like< TupleT >::value > >::format (const TupleT & values, FormatContext & ctx) -> decltype(ctx.out()) inline
Definition at line 313 of file ranges.h.
{
     auto out = ctx.out();
     size_t i = 0;
     detail::copy(formatting.prefix, out);
     detail::for_each(values, format_each<FormatContext>{formatting, i, out});
     detail::copy(formatting.postfix, out);
     return ctx.out();
   }
References detail::copy(), detail::for_each(), formatting_tuple< Char, Enable >::postfix, and formatting_tuple< Char, Enable >::prefix.
parse()
template<typename TupleT , typename Char > template<typename ParseContext > FMT_CONSTEXPR auto formatter< TupleT, Char, enable_if_t< fmt::is_tuple_like< TupleT >::value > >::parse (ParseContext & ctx) -> decltype(ctx.begin()) inline
Definition at line 308 of file ranges.h.
{
     return formatting.parse(ctx);
   }
References formatting_tuple< Char, Enable >::parse().
Member Data Documentation
formatting
template<typename TupleT , typename Char > formatting_tuple<Char> formatter< TupleT, Char, enable_if_t< fmt::is_tuple_like< TupleT >::value > >::formatting
Definition at line 305 of file ranges.h.
The documentation for this struct was generated from the following file:
deps/fmt/include/fmt/ranges.h