Azerotcore-wotlk: npc_air_force_bots::npc_air_force_botsAI Struct Reference
npc_air_force_bots::npc_air_force_botsAI Struct Reference
Public Member Functions
npc_air_force_botsAI (Creature *creature)
void Reset () override
Creature * SummonGuard ()
Creature * GetSummonedGuard ()
void MoveInLineOfSight (Unit *who) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
SpawnAssociation * SpawnAssoc
ObjectGuid SpawnedGUID
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 497 of file npcs_special.cpp.
Constructor & Destructor Documentation
npc_air_force_botsAI()
npc_air_force_bots::npc_air_force_botsAI::npc_air_force_botsAI (Creature * creature) inline
Definition at line 499 of file npcs_special.cpp.
                                                  : ScriptedAI(creature)
         {
             SpawnAssoc = nullptr;
             SpawnedGUID.Clear();
             // find the correct spawnhandling
             static uint32 entryCount = sizeof(spawnAssociations) / sizeof(SpawnAssociation);
             for (uint8 i = 0; i < entryCount; ++i)
             {
                 if (spawnAssociations[i].thisCreatureEntry == creature->GetEntry())
                 {
                     SpawnAssoc = &spawnAssociations[i];
                     break;
                 }
             }
             if (!SpawnAssoc)
                 LOG_ERROR("sql.sql", "TCSR: Creature template entry %u has ScriptName npc_air_force_bots, but it's not handled by that script", creature->GetEntry());
             else
             {
                 CreatureTemplate const* spawnedTemplate = sObjectMgr->GetCreatureTemplate(SpawnAssoc->spawnedCreatureEntry);
                 if (!spawnedTemplate)
                 {
                     LOG_ERROR("sql.sql", "TCSR: Creature template entry %u does not exist in DB, which is required by npc_air_force_bots", SpawnAssoc->spawnedCreatureEntry);
                     SpawnAssoc = nullptr;
                     return;
                 }
             }
         }
References ObjectGuid::Clear(), Object::GetEntry(), LOG_ERROR, sObjectMgr, SpawnAssoc, spawnAssociations, SpawnAssociation::spawnedCreatureEntry, and SpawnedGUID.
Member Function Documentation
GetSummonedGuard()
Creature* npc_air_force_bots::npc_air_force_botsAI::GetSummonedGuard () inline
Definition at line 551 of file npcs_special.cpp.
         {
             Creature* creature = ObjectAccessor::GetCreature(*me, SpawnedGUID);
             if (creature && creature->IsAlive())
                 return creature;
             return nullptr;
         }
References ObjectAccessor::GetCreature(), Unit::IsAlive(), ScriptedAI::me, and SpawnedGUID.
Referenced by MoveInLineOfSight().
MoveInLineOfSight()
void npc_air_force_bots::npc_air_force_botsAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
Definition at line 561 of file npcs_special.cpp.
         {
             if (!SpawnAssoc)
                 return;
             if (me->IsValidAttackTarget(who))
             {
                 Player* playerTarget = who->ToPlayer();
                 // airforce guards only spawn for players
                 if (!playerTarget)
                     return;
                 Creature* lastSpawnedGuard = !SpawnedGUID ? nullptr : GetSummonedGuard();
                 // prevent calling ObjectAccessor::GetUnit at next MoveInLineOfSight call - speedup
                 if (!lastSpawnedGuard)
                     SpawnedGUID.Clear();
                 switch (SpawnAssoc->spawnType)
                 {
                     case SPAWNTYPE_ALARMBOT:
{
                             if (!who->IsWithinDistInMap(me, RANGE_GUARDS_MARK))
                                 return;
                             Aura* markAura = who->GetAura(SPELL_GUARDS_MARK);
                             if (markAura)
{
                                 // the target wasn't able to move out of our range within 25 seconds
                                 if (!lastSpawnedGuard)
{
                                     lastSpawnedGuard = SummonGuard();
                                     if (!lastSpawnedGuard)
                                         return;
                                 }
                                 if (markAura->GetDuration() < AURA_DURATION_TIME_LEFT)
                                     if (!lastSpawnedGuard->GetVictim())
                                         lastSpawnedGuard->AI()->AttackStart(who);
                             }
                             else
{
                                 if (!lastSpawnedGuard)
                                     lastSpawnedGuard = SummonGuard();
                                 if (!lastSpawnedGuard)
                                     return;
                                 lastSpawnedGuard->CastSpell(who, SPELL_GUARDS_MARK, true);
                             }
                             break;
                         }
                     case SPAWNTYPE_TRIPWIRE_ROOFTOP:
{
                             if (!who->IsWithinDistInMap(me, RANGE_TRIPWIRE))
                                 return;
                             if (!lastSpawnedGuard)
                                 lastSpawnedGuard = SummonGuard();
                             if (!lastSpawnedGuard)
                                 return;
                             // ROOFTOP only triggers if the player is on the ground
                             if (!playerTarget->IsFlying() && !lastSpawnedGuard->GetVictim())
                                 lastSpawnedGuard->AI()->AttackStart(who);
                             break;
                         }
                 }
             }
         }
References Creature::AI(), UnitAI::AttackStart(), AURA_DURATION_TIME_LEFT, Unit::CastSpell(), ObjectGuid::Clear(), Unit::GetAura(), Aura::GetDuration(), GetSummonedGuard(), Unit::GetVictim(), Unit::IsFlying(), Unit::IsValidAttackTarget(), WorldObject::IsWithinDistInMap(), ScriptedAI::me, RANGE_GUARDS_MARK, RANGE_TRIPWIRE, SpawnAssoc, SpawnedGUID, SpawnAssociation::spawnType, SPAWNTYPE_ALARMBOT, SPAWNTYPE_TRIPWIRE_ROOFTOP, SPELL_GUARDS_MARK, SummonGuard(), and Object::ToPlayer().
Reset()
void npc_air_force_bots::npc_air_force_botsAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 534 of file npcs_special.cpp.
 {}
SummonGuard()
Creature* npc_air_force_bots::npc_air_force_botsAI::SummonGuard () inline
Definition at line 536 of file npcs_special.cpp.
         {
             Creature* summoned = me->SummonCreature(SpawnAssoc->spawnedCreatureEntry, 0.0f, 0.0f, 0.0f, 0.0f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 300000);
             if (summoned)
                 SpawnedGUID = summoned->GetGUID();
             else
             {
                 LOG_ERROR("sql.sql", "TCSR: npc_air_force_bots: wasn't able to spawn Creature %u", SpawnAssoc->spawnedCreatureEntry);
                 SpawnAssoc = nullptr;
             }
             return summoned;
         }
References Object::GetGUID(), LOG_ERROR, ScriptedAI::me, SpawnAssoc, SpawnAssociation::spawnedCreatureEntry, SpawnedGUID, WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT.
Referenced by MoveInLineOfSight().
Member Data Documentation
SpawnAssoc
SpawnAssociation* npc_air_force_bots::npc_air_force_botsAI::SpawnAssoc
Definition at line 531 of file npcs_special.cpp.
Referenced by MoveInLineOfSight(), npc_air_force_botsAI(), and SummonGuard().
SpawnedGUID
ObjectGuid npc_air_force_bots::npc_air_force_botsAI::SpawnedGUID
Definition at line 532 of file npcs_special.cpp.
Referenced by GetSummonedGuard(), MoveInLineOfSight(), npc_air_force_botsAI(), and SummonGuard().
The documentation for this struct was generated from the following file:
src/server/scripts/World/npcs_special.cpp