Azerotcore-wotlk: G3D::Image4uint8 Class Reference
G3D::Image4uint8 Class Reference
#include <Image4uint8.h>
Public Types
typedef Image4uint8 Type
typedef Image4uint8Ref Ref
Public Types inherited from G3D::Map2D< Color4uint8, Color4 >
typedef Color4uint8 StorageType
typedef Color4 ComputeType
typedef Map2D< Color4uint8, Color4 > Type
typedef shared_ptr< Map2D > Ref
Public Member Functions
const class ImageFormat * format () const
void load (const std::string &filename, GImage::Format fmt=GImage::AUTODETECT)
void save (const std::string &filename, GImage::Format fmt=GImage::AUTODETECT)
ReferenceCountedPointer< class Image1uint8 > getChannel (int c) const
Public Member Functions inherited from G3D::Map2D< Color4uint8, Color4 >
const Color4uint8 & fastGet (int x, int y) const
void fastSet (int x, int y, const Color4uint8 &v)
Color4 bicubic (float x, float y, WrapMode wrap) const
Color4 bicubic (float x, float y) const
Color4 bicubic (const Vector2 &p, WrapMode wrap) const
Color4 bicubic (const Vector2 &p) const
void resize (uint32 newW, uint32 newH)
bool changed ()
void setChanged (bool c)
Color4uint8 * getCArray ()
const Color4uint8 * getCArray () const
Array< Color4uint8 > & getArray ()
const Array< Color4uint8 > & getArray () const
bool inBounds (int x, int y) const
bool inBounds (const Vector2int16 &v) const
const Color4uint8 & get (int x, int y, WrapMode wrap) const
const Color4uint8 & get (int x, int y) const
const Color4uint8 & get (const Vector2int16 &p) const
const Color4uint8 & get (const Vector2int16 &p, WrapMode wrap) const
Color4uint8 & get (int x, int y, WrapMode wrap)
Color4uint8 & get (int x, int y)
Color4uint8 & get (const Vector2int16 &p)
void set (const Vector2int16 &p, const Color4uint8 &v)
void set (int x, int y, const Color4uint8 &v, WrapMode wrap)
void set (int x, int y, const Color4uint8 &v)
void set (const shared_ptr< Map2D< Color4uint8, T > > &src)
void setAll (const Color4uint8 &v)
void maybeFlipVertical (bool flip)
virtual void flipVertical ()
virtual void flipHorizontal ()
virtual void crop (int newX, int newY, int newW, int newH)
virtual void crop (const Rect2D &rect)
Color4 nearest (float x, float y, WrapMode wrap) const
Color4 nearest (float x, float y) const
Color4 nearest (const Vector2 &p) const
Color4 average () const
Color4 bilinear (float x, float y, WrapMode wrap) const
Color4 bilinear (float x, float y) const
Color4 bilinear (const Vector2 &p) const
Color4 bilinear (const Vector2 &p, WrapMode wrap) const
int32 width () const
int32 height () const
Vector2int16 size () const
Rect2D rect2DBounds () const
size_t sizeInMemory () const
WrapMode wrapMode () const
void setWrapMode (WrapMode m)
Public Member Functions inherited from G3D::ReferenceCountedObject
virtual ~ReferenceCountedObject ()
Static Public Member Functions
static Ref createEmpty (int width, int height, WrapMode wrap=WrapMode::ERROR)
static Ref createEmpty (WrapMode wrap=WrapMode::ERROR)
static Ref fromFile (const std::string &filename, WrapMode wrap=WrapMode::ERROR, GImage::Format fmt=GImage::AUTODETECT)
static Ref fromGImage (const class GImage &im, WrapMode wrap=WrapMode::ERROR)
static Ref fromArray (const class Color1uint8 *ptr, int width, int height, WrapMode wrap=WrapMode::ERROR)
static Ref fromArray (const class Color3uint8 *ptr, int width, int height, WrapMode wrap=WrapMode::ERROR)
static Ref fromArray (const class Color4uint8 *ptr, int width, int height, WrapMode wrap=WrapMode::ERROR)
static Ref fromArray (const class Color1 *ptr, int width, int height, WrapMode wrap=WrapMode::ERROR)
static Ref fromArray (const class Color3 *ptr, int width, int height, WrapMode wrap=WrapMode::ERROR)
static Ref fromArray (const class Color4 *ptr, int width, int height, WrapMode wrap=WrapMode::ERROR)
static Ref fromImage4 (const ReferenceCountedPointer< class Image4 > &im)
Static Public Member Functions inherited from G3D::Map2D< Color4uint8, Color4 >
static Ref create (int w=0, int h=0, WrapMode wrap=WrapMode::ERROR)
Protected Member Functions
Image4uint8 (int w, int h, WrapMode wrap)
void copyGImage (const class GImage &im)
void copyArray (const Color1 *src, int w, int h)
void copyArray (const Color3 *src, int w, int h)
void copyArray (const Color4 *src, int w, int h)
void copyArray (const Color1uint8 *src, int w, int h)
void copyArray (const Color3uint8 *src, int w, int h)
void copyArray (const Color4uint8 *src, int w, int h)
Protected Member Functions inherited from G3D::Map2D< Color4uint8, Color4 >
const Color4uint8 & slowGet (int x, int y, WrapMode wrap)
Color4 bicubic (const Color4 *ctrl, double s) const
Map2D (int w, int h, WrapMode wrap)
Additional Inherited Members
Public Attributes inherited from G3D::Map2D< Color4uint8, Color4 >
GMutex mutex
Protected Attributes inherited from G3D::Map2D< Color4uint8, Color4 >
Color4uint8 ZERO
uint32 w
uint32 h
WrapMode _wrapMode
AtomicInt32 m_changed
Array< Color4uint8 > data
Detailed Description
Compact storage for RGBA 8-bit per channel images.
See also G3D::Image4, G3D::GImage
Definition at line 29 of file Image4uint8.h.
Member Typedef Documentation
Ref
typedef Image4uint8Ref G3D::Image4uint8::Ref
Definition at line 33 of file Image4uint8.h.
Type
typedef Image4uint8 G3D::Image4uint8::Type
Definition at line 32 of file Image4uint8.h.
Constructor & Destructor Documentation
Image4uint8()
G3D::Image4uint8::Image4uint8 (int w, int h, WrapMode wrap) protected
Definition at line 23 of file Image4uint8.cpp.
                                                     : Map2D<Color4uint8, Color4>(w, h, wrap) {
     setAll(Color4::zero());
 }
References G3D::Map2D< Color4uint8, Color4 >::setAll(), and G3D::Color4::zero().
Member Function Documentation
copyArray() [1/6]
void G3D::Image4uint8::copyArray (const Color1 * src, int w, int h) protected
Definition at line 147 of file Image4uint8.cpp.
{
     resize(w, h);
     int N = w * h;
     Color4uint8* dst = getCArray();
     for (int i = 0; i < N; ++i) {
         dst[i].r = dst[i].g = dst[i].b = Color1uint8(src[i]).value;
         dst[i].a = 255;
     }
 }
References G3D::Color4uint8::a, G3D::Color4uint8::b, G3D::Color4uint8::g, G3D::Map2D< Color4uint8, Color4 >::getCArray(), G3D::Map2D< Color4uint8, Color4 >::h, G3D::Color4uint8::r, G3D::Map2D< Color4uint8, Color4 >::resize(), G3D::Color1uint8::value, and G3D::Map2D< Color4uint8, Color4 >::w.
Referenced by copyGImage().
copyArray() [2/6]
void G3D::Image4uint8::copyArray (const Color1uint8 * src, int w, int h) protected
Definition at line 136 of file Image4uint8.cpp.
{
     resize(w, h);
     int N = w * h;
     Color4uint8* dst = getCArray();
     for (int i = 0; i < N; ++i) {
         dst[i].r = dst[i].g = dst[i].b = src[i].value;
         dst[i].a = 255;
     }
 }
References G3D::Color4uint8::a, G3D::Color4uint8::b, G3D::Color4uint8::g, G3D::Map2D< Color4uint8, Color4 >::getCArray(), G3D::Map2D< Color4uint8, Color4 >::h, G3D::Color4uint8::r, G3D::Map2D< Color4uint8, Color4 >::resize(), G3D::Color1uint8::value, and G3D::Map2D< Color4uint8, Color4 >::w.
copyArray() [3/6]
void G3D::Image4uint8::copyArray (const Color3 * src, int w, int h) protected
Definition at line 183 of file Image4uint8.cpp.
{
     resize(w, h);
     int N = w * h;
     Color4uint8* dst = getCArray();
     for (int i = 0; i < N; ++i) {
         dst[i] = Color4uint8(Color4(src[i], 1.0f));
     }
 }
References G3D::Map2D< Color4uint8, Color4 >::getCArray(), G3D::Map2D< Color4uint8, Color4 >::h, G3D::Map2D< Color4uint8, Color4 >::resize(), and G3D::Map2D< Color4uint8, Color4 >::w.
copyArray() [4/6]
void G3D::Image4uint8::copyArray (const Color3uint8 * src, int w, int h) protected
Definition at line 176 of file Image4uint8.cpp.
{
     resize(w, h);
     GImage::RGBtoRGBA((const uint8*)ptr, (uint8*)getCArray(), w * h);
 }
References G3D::Map2D< Color4uint8, Color4 >::getCArray(), G3D::Map2D< Color4uint8, Color4 >::h, ptr(), G3D::Map2D< Color4uint8, Color4 >::resize(), G3D::GImage::RGBtoRGBA(), and G3D::Map2D< Color4uint8, Color4 >::w.
copyArray() [5/6]
void G3D::Image4uint8::copyArray (const Color4 * src, int w, int h) protected
Definition at line 165 of file Image4uint8.cpp.
{
     resize(w, h);
     int N = w * h;
     Color4uint8* dst = getCArray();
     for (int i = 0; i < N; ++i) {
         dst[i] = Color4uint8(src[i]);
     }
 }
References G3D::Map2D< Color4uint8, Color4 >::getCArray(), G3D::Map2D< Color4uint8, Color4 >::h, G3D::Map2D< Color4uint8, Color4 >::resize(), and G3D::Map2D< Color4uint8, Color4 >::w.
copyArray() [6/6]
void G3D::Image4uint8::copyArray (const Color4uint8 * src, int w, int h) protected
Definition at line 159 of file Image4uint8.cpp.
{
     resize(w, h);
     System::memcpy(getCArray(), ptr, w * h * 4);
 }
References G3D::Map2D< Color4uint8, Color4 >::getCArray(), G3D::Map2D< Color4uint8, Color4 >::h, G3D::System::memcpy(), ptr(), G3D::Map2D< Color4uint8, Color4 >::resize(), and G3D::Map2D< Color4uint8, Color4 >::w.
copyGImage()
void G3D::Image4uint8::copyGImage (const class GImage & im) protected
Definition at line 119 of file Image4uint8.cpp.
{
     switch (im.channels()) {
     case 1:
         copyArray(im.pixel1(), im.width(), im.height());
         break;
     case 3:
         copyArray(im.pixel3(), im.width(), im.height());
         break;
     case 4:
         copyArray(im.pixel4(), im.width(), im.height());
         break;
     }
 }
References G3D::GImage::channels(), copyArray(), G3D::GImage::height(), G3D::GImage::pixel1(), G3D::GImage::pixel3(), G3D::GImage::pixel4(), and G3D::GImage::width().
Referenced by load().
createEmpty() [1/2]
Image4uint8::Ref G3D::Image4uint8::createEmpty (int width, int height, WrapMode wrap = WrapMode::ERROR) static
Creates an all-zero width x height image.
Definition at line 54 of file Image4uint8.cpp.
{
     return new Type(width, height, wrap);
 }
References G3D::Map2D< Color4uint8, Color4 >::height(), G3D::Map2D< Color4uint8, Color4 >::width(), and G3D::wrap().
Referenced by createEmpty(), fromArray(), fromFile(), and fromImage4().
createEmpty() [2/2]
Image4uint8::Ref G3D::Image4uint8::createEmpty (WrapMode wrap = WrapMode::ERROR) static
Creates a 0 x 0 image.
Definition at line 59 of file Image4uint8.cpp.
{
     return createEmpty(0, 0, wrap);
 }
References createEmpty(), and G3D::wrap().
format()
const ImageFormat * G3D::Image4uint8::format () const
Definition at line 218 of file Image4uint8.cpp.
{
     return ImageFormat::RGBA8();
 }
References G3D::ImageFormat::RGBA8().
fromArray() [1/6]
Image4uint8::Ref G3D::Image4uint8::fromArray (const class Color1 * ptr, int width, int height, WrapMode wrap = WrapMode::ERROR) static
Definition at line 78 of file Image4uint8.cpp.
{
     Ref out = createEmpty(wrap);
     out->copyArray(ptr, w, h);
     return out;
 }
References createEmpty(), G3D::Map2D< Color4uint8, Color4 >::h, ptr(), G3D::Map2D< Color4uint8, Color4 >::w, and G3D::wrap().
fromArray() [2/6]
Image4uint8::Ref G3D::Image4uint8::fromArray (const class Color1uint8 * ptr, int width, int height, WrapMode wrap = WrapMode::ERROR) static
Definition at line 85 of file Image4uint8.cpp.
{
     Ref out = createEmpty(wrap);
     out->copyArray(ptr, w, h);
     return out;
 }
References createEmpty(), G3D::Map2D< Color4uint8, Color4 >::h, ptr(), G3D::Map2D< Color4uint8, Color4 >::w, and G3D::wrap().
Referenced by fromGImage().
fromArray() [3/6]
Image4uint8::Ref G3D::Image4uint8::fromArray (const class Color3 * ptr, int width, int height, WrapMode wrap = WrapMode::ERROR) static
Definition at line 92 of file Image4uint8.cpp.
{
     Ref out = createEmpty(wrap);
     out->copyArray(ptr, w, h);
     return out;
 }
References createEmpty(), G3D::Map2D< Color4uint8, Color4 >::h, ptr(), G3D::Map2D< Color4uint8, Color4 >::w, and G3D::wrap().
fromArray() [4/6]
Image4uint8::Ref G3D::Image4uint8::fromArray (const class Color3uint8 * ptr, int width, int height, WrapMode wrap = WrapMode::ERROR) static
Definition at line 71 of file Image4uint8.cpp.
{
     Ref out = createEmpty(wrap);
     out->copyArray(ptr, w, h);
     return out;
 }
References createEmpty(), G3D::Map2D< Color4uint8, Color4 >::h, ptr(), G3D::Map2D< Color4uint8, Color4 >::w, and G3D::wrap().
fromArray() [5/6]
Image4uint8::Ref G3D::Image4uint8::fromArray (const class Color4 * ptr, int width, int height, WrapMode wrap = WrapMode::ERROR) static
Definition at line 106 of file Image4uint8.cpp.
{
     Ref out = createEmpty(wrap);
     out->copyArray(ptr, w, h);
     return out;
 }
References createEmpty(), G3D::Map2D< Color4uint8, Color4 >::h, ptr(), G3D::Map2D< Color4uint8, Color4 >::w, and G3D::wrap().
fromArray() [6/6]
Image4uint8::Ref G3D::Image4uint8::fromArray (const class Color4uint8 * ptr, int width, int height, WrapMode wrap = WrapMode::ERROR) static
Definition at line 99 of file Image4uint8.cpp.
{
     Ref out = createEmpty(wrap);
     out->copyArray(ptr, w, h);
     return out;
 }
References createEmpty(), G3D::Map2D< Color4uint8, Color4 >::h, ptr(), G3D::Map2D< Color4uint8, Color4 >::w, and G3D::wrap().
fromFile()
Image4uint8::Ref G3D::Image4uint8::fromFile (const std::string & filename, WrapMode wrap = WrapMode::ERROR, GImage::Format fmt = GImage::AUTODETECT) static
Definition at line 64 of file Image4uint8.cpp.
{
     Ref out = createEmpty(wrap);
     out->load(filename, fmt);
     return out;
 }
References createEmpty(), fmt, and G3D::wrap().
fromGImage()
Image4uint8::Ref G3D::Image4uint8::fromGImage (const class GImage & im, WrapMode wrap = WrapMode::ERROR) static
Definition at line 28 of file Image4uint8.cpp.
{
     switch (im.channels()) {
     case 1:
         return fromArray(im.pixel1(), im.width(), im.height(), wrap);
     case 3:
         return fromArray(im.pixel3(), im.width(), im.height(), wrap);
     case 4:
         return fromArray(im.pixel4(), im.width(), im.height(), wrap);
     default:
         debugAssertM(false, "Input GImage must have 1, 3, or 4 channels.");
         return NULL;
     }
 }
References G3D::GImage::channels(), debugAssertM, fromArray(), G3D::GImage::height(), NULL, G3D::GImage::pixel1(), G3D::GImage::pixel3(), G3D::GImage::pixel4(), G3D::GImage::width(), and G3D::wrap().
fromImage4()
Image4uint8::Ref G3D::Image4uint8::fromImage4 (const ReferenceCountedPointer< class Image4 > & im) static
Definition at line 46 of file Image4uint8.cpp.
{
     Ref out = createEmpty(static_cast<WrapMode>(im->wrapMode()));
     out->copyArray(im->getCArray(), im->width(), im->height());
     return out;
 }
References createEmpty().
getChannel()
ReferenceCountedPointer< class Image1uint8 > G3D::Image4uint8::getChannel (int c) const
Extracts color channel 0 <= c <= 3 and returns it as a new monochrome image.
Definition at line 202 of file Image4uint8.cpp.
{
     debugAssert(c >= 0 && c <= 3);
     Image1uint8Ref dst = Image1uint8::createEmpty(width(), height(), wrapMode());
     const Color4uint8* srcArray = getCArray();
     Color1uint8* dstArray = dst->getCArray();
     const int N = width() * height();
     for (int i = 0; i < N; ++i) {
         dstArray[i] = Color1uint8(srcArray[i][c]);
     }
     return dst;
 }
References mpq::c, G3D::Image1uint8::createEmpty(), debugAssert, G3D::Map2D< Color4uint8, Color4 >::getCArray(), G3D::Map2D< Color4uint8, Color4 >::height(), G3D::Map2D< Color4uint8, Color4 >::width(), and G3D::Map2D< Color4uint8, Color4 >::wrapMode().
load()
void G3D::Image4uint8::load (const std::string & filename, GImage::Format fmt = GImage::AUTODETECT)
Loads from any of the file formats supported by G3D::GImage. If there is an alpha channel on the input, it is stripped.
Definition at line 113 of file Image4uint8.cpp.
{
     copyGImage(GImage(filename, fmt));
     setChanged(true);
 }
References copyGImage(), fmt, and G3D::Map2D< Color4uint8, Color4 >::setChanged().
save()
void G3D::Image4uint8::save (const std::string & filename, GImage::Format fmt = GImage::AUTODETECT)
Saves in any of the formats supported by G3D::GImage.
Definition at line 195 of file Image4uint8.cpp.
{
     GImage im(width(), height(), 4);
     System::memcpy(im.byte(), getCArray(), width() * height() * 4);
     im.save(filename, fmt);
 }
References G3D::GImage::byte(), fmt, G3D::Map2D< Color4uint8, Color4 >::getCArray(), G3D::Map2D< Color4uint8, Color4 >::height(), G3D::System::memcpy(), G3D::GImage::save(), and G3D::Map2D< Color4uint8, Color4 >::width().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/Image4uint8.h
deps/g3dlite/source/Image4uint8.cpp