Azerotcore-wotlk: BattlegroundMgr Class Reference
BattlegroundMgr Class Reference
#include <BattlegroundMgr.h>
Public Member Functions
void Update (uint32 diff)
void BuildPlayerJoinedBattlegroundPacket (WorldPacket *data, Player *player)
void BuildPlayerLeftBattlegroundPacket (WorldPacket *data, ObjectGuid guid)
void BuildBattlegroundListPacket (WorldPacket *data, ObjectGuid guid, Player *player, BattlegroundTypeId bgTypeId, uint8 fromWhere)
void BuildGroupJoinedBattlegroundPacket (WorldPacket *data, GroupJoinBattlegroundResult result)
void BuildUpdateWorldStatePacket (WorldPacket *data, uint32 field, uint32 value)
void BuildPvpLogDataPacket (WorldPacket *data, Battleground *bg)
void BuildBattlegroundStatusPacket (WorldPacket *data, Battleground *bg, uint8 queueSlot, uint8 statusId, uint32 time1, uint32 time2, uint8 arenaType, TeamId teamId, bool isRated=false, BattlegroundTypeId forceBgTypeId=BATTLEGROUND_TYPE_NONE)
void BuildPlaySoundPacket (WorldPacket *data, uint32 soundid)
void SendAreaSpiritHealerQueryOpcode (Player *player, Battleground *bg, ObjectGuid guid)
Battleground * GetBattleground (uint32 InstanceID)
Battleground * GetBattlegroundTemplate (BattlegroundTypeId bgTypeId)
Battleground * CreateNewBattleground (BattlegroundTypeId bgTypeId, uint32 minLevel, uint32 maxLevel, uint8 arenaType, bool isRated)
void AddBattleground (Battleground *bg)
void RemoveBattleground (BattlegroundTypeId bgTypeId, uint32 instanceId)
void CreateInitialBattlegrounds ()
void DeleteAllBattlegrounds ()
void SendToBattleground (Player *player, uint32 InstanceID, BattlegroundTypeId bgTypeId)
BattlegroundQueue & GetBattlegroundQueue (BattlegroundQueueTypeId bgQueueTypeId)
void ScheduleArenaQueueUpdate (uint32 arenaRatedTeamId, BattlegroundQueueTypeId bgQueueTypeId, BattlegroundBracketId bracket_id)
uint32 GetPrematureFinishTime () const
void ToggleArenaTesting ()
void ToggleTesting ()
void SetHolidayWeekends (uint32 mask)
bool isArenaTesting () const
bool isTesting () const
uint32 GetRatingDiscardTimer () const
void InitAutomaticArenaPointDistribution ()
void LoadBattleMastersEntry ()
void CheckBattleMasters ()
BattlegroundTypeId GetBattleMasterBG (uint32 entry) const
const BattlegroundContainer & GetBattlegroundList ()
Static Public Member Functions
static BattlegroundMgr * instance ()
static void InviteGroupToBG (GroupQueueInfo *ginfo, Battleground *bg, TeamId teamId)
static BattlegroundQueueTypeId BGQueueTypeId (BattlegroundTypeId bgTypeId, uint8 arenaType)
static BattlegroundTypeId BGTemplateId (BattlegroundQueueTypeId bgQueueTypeId)
static bool IsArenaType (BattlegroundTypeId bgTypeId)
static uint8 BGArenaType (BattlegroundQueueTypeId bgQueueTypeId)
static HolidayIds BGTypeToWeekendHolidayId (BattlegroundTypeId bgTypeId)
static BattlegroundTypeId WeekendHolidayIdToBGType (HolidayIds holiday)
static bool IsBGWeekend (BattlegroundTypeId bgTypeId)
Static Public Attributes
static std::unordered_map< int, BattlegroundQueueTypeId > bgToQueue
static std::unordered_map< int, BattlegroundTypeId > queueToBg
static std::unordered_map< int, Battleground * > bgtypeToBattleground
static std::unordered_map< int, bgRef > bgTypeToTemplate
static std::unordered_map< int, bgMapRef > getBgFromMap = {}
static std::unordered_map< int, bgTypeRef > getBgFromTypeID
static std::unordered_map< uint32, BattlegroundQueueTypeId > ArenaTypeToQueue
static std::unordered_map< uint32, ArenaType > QueueToArenaType
Private Types
typedef std::map< BattlegroundTypeId, Battleground * > BattlegroundTemplateContainer
typedef std::map< BattlegroundTypeId, uint8 > BattlegroundSelectionWeightMap
typedef std::map< BattlegroundTypeId, CreateBattlegroundData > BattlegroundTemplateMap
typedef std::map< uint32, CreateBattlegroundData * > BattlegroundMapTemplateContainer
Private Member Functions
BattlegroundMgr ()
~BattlegroundMgr ()
bool CreateBattleground (CreateBattlegroundData &data)
uint32 GetNextClientVisibleInstanceId ()
BattlegroundTypeId GetRandomBG (BattlegroundTypeId id)
CreateBattlegroundData const * GetBattlegroundTemplateByTypeId (BattlegroundTypeId id)
CreateBattlegroundData const * GetBattlegroundTemplateByMapId (uint32 mapId)
Private Attributes
BattlegroundTemplateContainer m_BattlegroundTemplates
BattlegroundContainer m_Battlegrounds
BattlegroundQueue m_BattlegroundQueues [MAX_BATTLEGROUND_QUEUE_TYPES]
std::vector< uint64 > m_ArenaQueueUpdateScheduler
bool m_ArenaTesting
bool m_Testing
uint32 m_lastClientVisibleInstanceId
time_t m_NextAutoDistributionTime
uint32 m_AutoDistributionTimeChecker
uint32 m_NextPeriodicQueueUpdateTime
BattleMastersMap mBattleMastersMap
BattlegroundTemplateMap _battlegroundTemplates
BattlegroundMapTemplateContainer _battlegroundMapTemplates
Detailed Description
Definition at line 62 of file BattlegroundMgr.h.
Member Typedef Documentation
BattlegroundMapTemplateContainer
typedef std::map<uint32 , CreateBattlegroundData*> BattlegroundMgr::BattlegroundMapTemplateContainer private
Definition at line 183 of file BattlegroundMgr.h.
BattlegroundSelectionWeightMap
typedef std::map<BattlegroundTypeId, uint8 > BattlegroundMgr::BattlegroundSelectionWeightMap private
Definition at line 180 of file BattlegroundMgr.h.
BattlegroundTemplateContainer
typedef std::map<BattlegroundTypeId, Battleground*> BattlegroundMgr::BattlegroundTemplateContainer private
Definition at line 149 of file BattlegroundMgr.h.
BattlegroundTemplateMap
typedef std::map<BattlegroundTypeId, CreateBattlegroundData> BattlegroundMgr::BattlegroundTemplateMap private
Definition at line 182 of file BattlegroundMgr.h.
Constructor & Destructor Documentation
BattlegroundMgr()
BattlegroundMgr::BattlegroundMgr () private
Definition at line 59 of file BattlegroundMgr.cpp.
                                  : m_ArenaTesting(false), m_Testing(false),
     m_lastClientVisibleInstanceId(0), m_NextAutoDistributionTime(0), m_AutoDistributionTimeChecker(0), m_NextPeriodicQueueUpdateTime(5 * IN_MILLISECONDS)
 {
     for (uint32 qtype = BATTLEGROUND_QUEUE_NONE; qtype < MAX_BATTLEGROUND_QUEUE_TYPES; ++qtype)
         m_BattlegroundQueues[qtype].SetBgTypeIdAndArenaType(BGTemplateId(BattlegroundQueueTypeId(qtype)), BGArenaType(BattlegroundQueueTypeId(qtype)));
 }
References BATTLEGROUND_QUEUE_NONE, BGArenaType(), BGTemplateId(), m_BattlegroundQueues, and MAX_BATTLEGROUND_QUEUE_TYPES.
~BattlegroundMgr()
BattlegroundMgr::~BattlegroundMgr () private
Definition at line 66 of file BattlegroundMgr.cpp.
 {
     DeleteAllBattlegrounds();
 }
References DeleteAllBattlegrounds().
Member Function Documentation
AddBattleground()
void BattlegroundMgr::AddBattleground (Battleground * bg)
Definition at line 991 of file BattlegroundMgr.cpp.
 {
     if (bg->GetInstanceID() == 0)
         m_BattlegroundTemplates[bg->GetBgTypeID()] = bg;
     else
         m_Battlegrounds[bg->GetInstanceID()] = bg;
 #ifdef ELUNA
     sEluna->OnBGCreate(bg, bg->GetBgTypeID(), bg->GetInstanceID());
 #endif
 }
References bg(), m_Battlegrounds, and m_BattlegroundTemplates.
Referenced by CreateBattleground().
BGArenaType()
uint8 BattlegroundMgr::BGArenaType (BattlegroundQueueTypeId bgQueueTypeId) static
Definition at line 782 of file BattlegroundMgr.cpp.
 {
     uint8 arenaType = 0;
     if (BattlegroundMgr::QueueToArenaType.find(bgQueueTypeId) != BattlegroundMgr::QueueToArenaType.end())
     {
         arenaType = BattlegroundMgr::QueueToArenaType.at(bgQueueTypeId);
     }
     sScriptMgr->OnArenaQueueIdToArenaType(bgQueueTypeId, arenaType);
     return arenaType;
 }
References find(), QueueToArenaType, and sScriptMgr.
Referenced by BattlegroundMgr().
BGQueueTypeId()
BattlegroundQueueTypeId BattlegroundMgr::BGQueueTypeId (BattlegroundTypeId bgTypeId, uint8 arenaType) static
Definition at line 748 of file BattlegroundMgr.cpp.
 {
     uint32 queueTypeID = BATTLEGROUND_QUEUE_NONE;
     if (arenaType)
     {
         if (BattlegroundMgr::ArenaTypeToQueue.find(arenaType) != BattlegroundMgr::ArenaTypeToQueue.end())
         {
             queueTypeID = BattlegroundMgr::ArenaTypeToQueue.at(arenaType);
         }
         sScriptMgr->OnArenaTypeIDToQueueID(bgTypeId, arenaType, queueTypeID);
         return static_cast<BattlegroundQueueTypeId>(queueTypeID);
     }
     if (BattlegroundMgr::bgToQueue.find(bgTypeId) != BattlegroundMgr::bgToQueue.end())
     {
         queueTypeID = BattlegroundMgr::bgToQueue.at(bgTypeId);
     }
     return static_cast<BattlegroundQueueTypeId>(queueTypeID);
 }
References ArenaTypeToQueue, BATTLEGROUND_QUEUE_NONE, bgToQueue, find(), and sScriptMgr.
Referenced by Group::CanJoinBattlegroundQueue(), ArenaTeam::DelMember(), BGQueueInviteEvent::Execute(), WorldSession::HandleArenaTeamDisbandOpcode(), WorldSession::HandleArenaTeamLeaveOpcode(), WorldSession::HandleArenaTeamRemoveOpcode(), WorldSession::HandleBattleFieldPortOpcode(), WorldSession::HandleBattlemasterJoinArena(), WorldSession::HandleBattlemasterJoinOpcode(), InviteGroupToBG(), and BattlegroundQueue::RemovePlayer().
BGTemplateId()
BattlegroundTypeId BattlegroundMgr::BGTemplateId (BattlegroundQueueTypeId bgQueueTypeId) static
Definition at line 772 of file BattlegroundMgr.cpp.
 {
     if (BattlegroundMgr::queueToBg.find(bgQueueTypeId) == BattlegroundMgr::queueToBg.end())
     {
         return BattlegroundTypeId(0);
     }
     return BattlegroundMgr::queueToBg[bgQueueTypeId];
 }
References find(), and queueToBg.
Referenced by BattlegroundMgr(), and WorldSession::HandleBattlefieldStatusOpcode().
BGTypeToWeekendHolidayId()
HolidayIds BattlegroundMgr::BGTypeToWeekendHolidayId (BattlegroundTypeId bgTypeId) static
Definition at line 916 of file BattlegroundMgr.cpp.
 {
     switch (bgTypeId)
     {
         case BATTLEGROUND_AV:
             return HOLIDAY_CALL_TO_ARMS_AV;
         case BATTLEGROUND_EY:
             return HOLIDAY_CALL_TO_ARMS_EY;
         case BATTLEGROUND_WS:
             return HOLIDAY_CALL_TO_ARMS_WS;
         case BATTLEGROUND_SA:
             return HOLIDAY_CALL_TO_ARMS_SA;
         case BATTLEGROUND_AB:
             return HOLIDAY_CALL_TO_ARMS_AB;
         case BATTLEGROUND_IC:
             return HOLIDAY_CALL_TO_ARMS_IC;
         default:
             return HOLIDAY_NONE;
     }
 }
References BATTLEGROUND_AB, BATTLEGROUND_AV, BATTLEGROUND_EY, BATTLEGROUND_IC, BATTLEGROUND_SA, BATTLEGROUND_WS, HOLIDAY_CALL_TO_ARMS_AB, HOLIDAY_CALL_TO_ARMS_AV, HOLIDAY_CALL_TO_ARMS_EY, HOLIDAY_CALL_TO_ARMS_IC, HOLIDAY_CALL_TO_ARMS_SA, HOLIDAY_CALL_TO_ARMS_WS, and HOLIDAY_NONE.
Referenced by IsBGWeekend().
BuildBattlegroundListPacket()
void BattlegroundMgr::BuildBattlegroundListPacket (WorldPacket * data, ObjectGuid guid, Player * player, BattlegroundTypeId bgTypeId, uint8 fromWhere)
Definition at line 660 of file BattlegroundMgr.cpp.
 {
     if (!player)
         return;
     uint32 winner_kills = player->GetRandomWinner() ? sWorld->getIntConfig(CONFIG_BG_REWARD_WINNER_HONOR_LAST) : sWorld->getIntConfig(CONFIG_BG_REWARD_WINNER_HONOR_FIRST);
     uint32 winner_arena = player->GetRandomWinner() ? sWorld->getIntConfig(CONFIG_BG_REWARD_WINNER_ARENA_LAST) : sWorld->getIntConfig(CONFIG_BG_REWARD_WINNER_ARENA_FIRST);
     uint32 loser_kills = player->GetRandomWinner() ? sWorld->getIntConfig(CONFIG_BG_REWARD_LOSER_HONOR_LAST) : sWorld->getIntConfig(CONFIG_BG_REWARD_LOSER_HONOR_FIRST);
     winner_kills = Acore::Honor::hk_honor_at_level(player->getLevel(), float(winner_kills));
     loser_kills = Acore::Honor::hk_honor_at_level(player->getLevel(), float(loser_kills));
     data->Initialize(SMSG_BATTLEFIELD_LIST);
     *data << guid;                                          // battlemaster guid
     *data << uint8(fromWhere);                              // from where you joined
     *data << uint32(bgTypeId);                              // battleground id
     *data << uint8(0);                                      // unk
     *data << uint8(0);                                      // unk
     // Rewards
     *data << uint8(player->GetRandomWinner());              // 3.3.3 hasWin
     *data << uint32(winner_kills);                          // 3.3.3 winHonor
     *data << uint32(winner_arena);                          // 3.3.3 winArena
     *data << uint32(loser_kills);                           // 3.3.3 lossHonor
     uint8 isQueueRandom = (bgTypeId == BATTLEGROUND_RB);
     *data << uint8(isQueueRandom);                          // 3.3.3 isRandom
     if (isQueueRandom)
     {
         // Rewards (random)
         *data << uint8(player->GetRandomWinner());          // 3.3.3 hasWin_Random
         *data << uint32(winner_kills);                      // 3.3.3 winHonor_Random
         *data << uint32(winner_arena);                      // 3.3.3 winArena_Random
         *data << uint32(loser_kills);                       // 3.3.3 lossHonor_Random
     }
     if (bgTypeId == BATTLEGROUND_AA)                        // arena
         *data << uint32(0);                                 // unk (count?)
     else                                                    // battleground
     {
         size_t count_pos = data->wpos();
         *data << uint32(0);                                 // number of bg instances
         if (Battleground* bgt = GetBattlegroundTemplate(bgTypeId))
             if (GetBattlegroundBracketByLevel(bgt->GetMapId(), player->getLevel()))
             {
                 uint32 count = 0;
                 /*for (BattlegroundClientIdsContainer::const_iterator itr = clientIds.begin(); itr != clientIds.end(); ++itr)
                 {
                     *data << uint32(*itr);
                     ++count;
                 }*/
                 data->put<uint32>(count_pos, count);
             }
     }
 }
References BATTLEGROUND_AA, BATTLEGROUND_RB, CONFIG_BG_REWARD_LOSER_HONOR_FIRST, CONFIG_BG_REWARD_LOSER_HONOR_LAST, CONFIG_BG_REWARD_WINNER_ARENA_FIRST, CONFIG_BG_REWARD_WINNER_ARENA_LAST, CONFIG_BG_REWARD_WINNER_HONOR_FIRST, CONFIG_BG_REWARD_WINNER_HONOR_LAST, count(), GetBattlegroundBracketByLevel(), GetBattlegroundTemplate(), Unit::getLevel(), Player::GetRandomWinner(), Acore::Honor::hk_honor_at_level(), SMSG_BATTLEFIELD_LIST, and sWorld.
BuildBattlegroundStatusPacket()
void BattlegroundMgr::BuildBattlegroundStatusPacket (WorldPacket * data, Battleground * bg, uint8 queueSlot, uint8 statusId, uint32 time1, uint32 time2, uint8 arenaType, TeamId teamId, bool isRated = false, BattlegroundTypeId forceBgTypeId = BATTLEGROUND_TYPE_NONE)
Definition at line 160 of file BattlegroundMgr.cpp.
 {
     // pussywizard:
     //ASSERT(QueueSlot < PLAYER_MAX_BATTLEGROUND_QUEUES);
     if (StatusID == STATUS_NONE || !bg)
     {
         data->Initialize(SMSG_BATTLEFIELD_STATUS, 4 + 8);
         *data << uint32(QueueSlot);
         *data << uint64(0);
         return;
     }
     data->Initialize(SMSG_BATTLEFIELD_STATUS, (4 + 8 + 1 + 1 + 4 + 1 + 4 + 4 + 4));
     *data << uint32(QueueSlot);
     // The following segment is read as uint64 in client but can be appended as their original type.
     *data << uint8(arenatype);
     *data << uint8(bg->isArena() ? 0xE : 0x0);
     *data << uint32(forceBgTypeId != BATTLEGROUND_TYPE_NONE ? forceBgTypeId : bg->GetBgTypeID());
     *data << uint16(0x1F90);
     // End of uint64 segment, decomposed this way for simplicity
     *data << uint8(bg->GetMinLevel());
     *data << uint8(bg->GetMaxLevel());
     *data << uint32(bg->GetClientInstanceID());
     // following displays the minimap icon. 0 = faction icon, 1 = arenaicon
     *data << uint8(bg->isRated() || isRated); // 1 for rated match, 0 for bg or non rated match
     *data << uint32(StatusID);                                  // status
     switch (StatusID)
     {
         case STATUS_WAIT_QUEUE:                                 // status_in_queue
             *data << uint32(Time1);                             // average wait time, milliseconds
             *data << uint32(Time2);                             // time in queue, updated every minute!, milliseconds
             break;
         case STATUS_WAIT_JOIN:                                  // status_invite
             *data << uint32(bg->GetMapId());                    // map id
             *data << uint64(0);                                 // 3.3.5, unknown
             *data << uint32(Time1);                             // time to remove from queue, milliseconds
             break;
         case STATUS_IN_PROGRESS:                                // status_in_progress
             *data << uint32(bg->GetMapId());                    // map id
             *data << uint64(0);                                 // 3.3.5, unknown
             *data << uint32(Time1);                             // time to bg auto leave, 0 at bg start, 120000 after bg end, milliseconds
             *data << uint32(Time2);                             // time from bg start, milliseconds
             *data << uint8(teamId == TEAM_ALLIANCE ? 1 : 0);   // arenafaction (0 for horde, 1 for alliance)
             break;
         default:
             break;
     }
 }
References BATTLEGROUND_TYPE_NONE, bg(), SMSG_BATTLEFIELD_STATUS, STATUS_IN_PROGRESS, STATUS_NONE, STATUS_WAIT_JOIN, STATUS_WAIT_QUEUE, and TEAM_ALLIANCE.
BuildGroupJoinedBattlegroundPacket()
void BattlegroundMgr::BuildGroupJoinedBattlegroundPacket (WorldPacket * data, GroupJoinBattlegroundResult result)
Definition at line 385 of file BattlegroundMgr.cpp.
 {
     data->Initialize(SMSG_GROUP_JOINED_BATTLEGROUND, 4);
     *data << int32(result);
     if (result == ERR_BATTLEGROUND_JOIN_TIMED_OUT || result == ERR_BATTLEGROUND_JOIN_FAILED)
         *data << uint64(0);                                 // player guid
 }
References ERR_BATTLEGROUND_JOIN_FAILED, ERR_BATTLEGROUND_JOIN_TIMED_OUT, and SMSG_GROUP_JOINED_BATTLEGROUND.
BuildPlayerJoinedBattlegroundPacket()
void BattlegroundMgr::BuildPlayerJoinedBattlegroundPacket (WorldPacket * data, Player * player)
Definition at line 412 of file BattlegroundMgr.cpp.
 {
     data->Initialize(SMSG_BATTLEGROUND_PLAYER_JOINED, 8);
     *data << player->GetGUID();
 }
References Object::GetGUID(), and SMSG_BATTLEGROUND_PLAYER_JOINED.
BuildPlayerLeftBattlegroundPacket()
void BattlegroundMgr::BuildPlayerLeftBattlegroundPacket (WorldPacket * data, ObjectGuid guid)
Definition at line 406 of file BattlegroundMgr.cpp.
 {
     data->Initialize(SMSG_BATTLEGROUND_PLAYER_LEFT, 8);
     *data << guid;
 }
References SMSG_BATTLEGROUND_PLAYER_LEFT.
BuildPlaySoundPacket()
void BattlegroundMgr::BuildPlaySoundPacket (WorldPacket * data, uint32 soundid)
Definition at line 400 of file BattlegroundMgr.cpp.
 {
     data->Initialize(SMSG_PLAY_SOUND, 4);
     *data << uint32(soundid);
 }
References SMSG_PLAY_SOUND.
BuildPvpLogDataPacket()
void BattlegroundMgr::BuildPvpLogDataPacket (WorldPacket * data, Battleground * bg)
Definition at line 212 of file BattlegroundMgr.cpp.
 {
     uint8 type = (bg->isArena() ? 1 : 0);
     data->Initialize(MSG_PVP_LOG_DATA, (1 + 1 + 4 + 40 * bg->GetPlayerScoresSize()));
     *data << uint8(type);                                   // type (battleground=0/arena=1)
     if (type)                                               // arena
     {
         // it seems this must be according to BG_WINNER_A/H and _NOT_ TEAM_A/H
         for (TeamId iTeamId = TEAM_ALLIANCE; iTeamId <= TEAM_HORDE; iTeamId = TeamId(iTeamId + 1))
         {
             // Xinef: oryginally this was looping in reverse order, loop order was changed so we have to change checked teamId
             int32 rating_change = bg->GetArenaTeamRatingChangeForTeam(Battleground::GetOtherTeamId(iTeamId));
             uint32 pointsLost = rating_change < 0 ? -rating_change : 0;
             uint32 pointsGained = rating_change > 0 ? rating_change : 0;
             uint32 MatchmakerRating = bg->GetArenaMatchmakerRating(Battleground::GetOtherTeamId(iTeamId));
             *data << uint32(pointsLost);                    // Rating Lost
             *data << uint32(pointsGained);                  // Rating gained
             *data << uint32(MatchmakerRating);              // Matchmaking Value
         }
         for (TeamId iTeamId = TEAM_ALLIANCE; iTeamId <= TEAM_HORDE; iTeamId = TeamId(iTeamId + 1))
         {
             if (ArenaTeam* at = sArenaTeamMgr->GetArenaTeamById(bg->GetArenaTeamIdForTeam(Battleground::GetOtherTeamId(iTeamId))))
                 * data << at->GetName();
             else
                 *data << uint8(0);
         }
     }
     if (bg->GetStatus() != STATUS_WAIT_LEAVE)
         *data << uint8(0);                                          // bg not ended
     else
     {
         *data << uint8(1);                                          // bg ended
         *data << uint8(bg->GetWinner() == TEAM_ALLIANCE ? TEAM_HORDE : TEAM_ALLIANCE); // who win
     }
     size_t wpos = data->wpos();
     uint32 scoreCount = 0;
     *data << uint32(scoreCount);                            // placeholder
     Battleground::BattlegroundScoreMap::const_iterator itr2 = bg->GetPlayerScoresBegin();
     for (Battleground::BattlegroundScoreMap::const_iterator itr = itr2; itr != bg->GetPlayerScoresEnd();)
     {
         itr2 = itr++;
         if (!bg->IsPlayerInBattleground(itr2->first))
         {
             LOG_ERROR("bg.battleground", "Player %s has scoreboard entry for battleground %u but is not in battleground!", itr->first.ToString().c_str(), bg->GetBgTypeID());
             continue;
         }
         *data << itr2->first;
         *data << uint32(itr2->second->KillingBlows);
         if (type == 0)
         {
             *data << uint32(itr2->second->HonorableKills);
             *data << uint32(itr2->second->Deaths);
             *data << uint32(itr2->second->BonusHonor);
         }
         else
         {
             *data << uint8(itr2->second->player->GetBgTeamId() == TEAM_ALLIANCE ? 1 : 0); // green or yellow
         }
         *data << uint32(itr2->second->DamageDone);              // damage done
         *data << uint32(itr2->second->HealingDone);             // healing done
         BattlegroundTypeId bgTypeId = bg->GetBgTypeID();
         switch (bgTypeId)                              // battleground specific things
         {
             case BATTLEGROUND_RB:
                 switch (bg->GetMapId())
                 {
                     case 489:
                         *data << uint32(0x00000002);            // count of next fields
                         *data << uint32(((BattlegroundWGScore*)itr2->second)->FlagCaptures);        // flag captures
                         *data << uint32(((BattlegroundWGScore*)itr2->second)->FlagReturns);         // flag returns
                         break;
                     case 566:
                         *data << uint32(0x00000001);            // count of next fields
                         *data << uint32(((BattlegroundEYScore*)itr2->second)->FlagCaptures);        // flag captures
                         break;
                     case 529:
                         *data << uint32(0x00000002);            // count of next fields
                         *data << uint32(((BattlegroundABScore*)itr2->second)->BasesAssaulted);      // bases asssulted
                         *data << uint32(((BattlegroundABScore*)itr2->second)->BasesDefended);       // bases defended
                         break;
                     case 30:
                         *data << uint32(0x00000005);            // count of next fields
                         *data << uint32(((BattlegroundAVScore*)itr2->second)->GraveyardsAssaulted); // GraveyardsAssaulted
                         *data << uint32(((BattlegroundAVScore*)itr2->second)->GraveyardsDefended);  // GraveyardsDefended
                         *data << uint32(((BattlegroundAVScore*)itr2->second)->TowersAssaulted);     // TowersAssaulted
                         *data << uint32(((BattlegroundAVScore*)itr2->second)->TowersDefended);      // TowersDefended
                         *data << uint32(((BattlegroundAVScore*)itr2->second)->MinesCaptured);       // MinesCaptured
                         break;
                     case 607:
                         *data << uint32(0x00000002);            // count of next fields
                         *data << uint32(((BattlegroundSAScore*)itr2->second)->demolishers_destroyed);
                         *data << uint32(((BattlegroundSAScore*)itr2->second)->gates_destroyed);
                         break;
                     case 628:                                   // IC
                         *data << uint32(0x00000002);            // count of next fields
                         *data << uint32(((BattlegroundICScore*)itr2->second)->BasesAssaulted);       // bases asssulted
                         *data << uint32(((BattlegroundICScore*)itr2->second)->BasesDefended);        // bases defended
                         [[fallthrough]]; // TODO: Not sure whether the fallthrough was a mistake (forgetting a break) or intended. This should be double-checked.
                     default:
                         if (BattlegroundMgr::getBgFromMap.find(bg->GetMapId()) != BattlegroundMgr::getBgFromMap.end())
                             BattlegroundMgr::getBgFromMap[bg->GetMapId()](data, itr2);
                         else
                             *data << uint32(0);
                         break;
                 }
                 break;
             case BATTLEGROUND_AV:
                 *data << uint32(0x00000005);                    // count of next fields
                 *data << uint32(((BattlegroundAVScore*)itr2->second)->GraveyardsAssaulted); // GraveyardsAssaulted
                 *data << uint32(((BattlegroundAVScore*)itr2->second)->GraveyardsDefended);  // GraveyardsDefended
                 *data << uint32(((BattlegroundAVScore*)itr2->second)->TowersAssaulted);     // TowersAssaulted
                 *data << uint32(((BattlegroundAVScore*)itr2->second)->TowersDefended);      // TowersDefended
                 *data << uint32(((BattlegroundAVScore*)itr2->second)->MinesCaptured);       // MinesCaptured
                 break;
             case BATTLEGROUND_WS:
                 *data << uint32(0x00000002);                    // count of next fields
                 *data << uint32(((BattlegroundWGScore*)itr2->second)->FlagCaptures);        // flag captures
                 *data << uint32(((BattlegroundWGScore*)itr2->second)->FlagReturns);         // flag returns
                 break;
             case BATTLEGROUND_AB:
                 *data << uint32(0x00000002);                    // count of next fields
                 *data << uint32(((BattlegroundABScore*)itr2->second)->BasesAssaulted);      // bases asssulted
                 *data << uint32(((BattlegroundABScore*)itr2->second)->BasesDefended);       // bases defended
                 break;
             case BATTLEGROUND_EY:
                 *data << uint32(0x00000001);                    // count of next fields
                 *data << uint32(((BattlegroundEYScore*)itr2->second)->FlagCaptures);        // flag captures
                 break;
             case BATTLEGROUND_SA:
                 *data << uint32(0x00000002);                    // count of next fields
                 *data << uint32(((BattlegroundSAScore*)itr2->second)->demolishers_destroyed);
                 *data << uint32(((BattlegroundSAScore*)itr2->second)->gates_destroyed);
                 break;
             case BATTLEGROUND_IC:
                 *data << uint32(0x00000002);                // count of next fields
                 *data << uint32(((BattlegroundICScore*)itr2->second)->BasesAssaulted);       // bases assaulted
                 *data << uint32(((BattlegroundICScore*)itr2->second)->BasesDefended);        // bases defended
                 break;
             case BATTLEGROUND_NA:
             case BATTLEGROUND_BE:
             case BATTLEGROUND_AA:
             case BATTLEGROUND_RL:
             case BATTLEGROUND_DS:
             case BATTLEGROUND_RV:
                 *data << uint32(0);
                 break;
             default:
                 if (BattlegroundMgr::getBgFromTypeID.find(bgTypeId) != BattlegroundMgr::getBgFromTypeID.end())
                     BattlegroundMgr::getBgFromTypeID[bgTypeId](data, itr2, bg);
                 else
                     *data << uint32(0);
                 break;
         }
         // should never happen
         if (++scoreCount >= bg->GetMaxPlayersPerTeam() * 2 && itr != bg->GetPlayerScoresEnd())
         {
             LOG_INFO("misc", "Battleground %u scoreboard has more entries (%u) than allowed players in this bg (%u)", bgTypeId, bg->GetPlayerScoresSize(), bg->GetMaxPlayersPerTeam() * 2);
             break;
         }
     }
     data->put(wpos, scoreCount);
 }
References BATTLEGROUND_AA, BATTLEGROUND_AB, BATTLEGROUND_AV, BATTLEGROUND_BE, BATTLEGROUND_DS, BATTLEGROUND_EY, BATTLEGROUND_IC, BATTLEGROUND_NA, BATTLEGROUND_RB, BATTLEGROUND_RL, BATTLEGROUND_RV, BATTLEGROUND_SA, BATTLEGROUND_WS, bg(), find(), getBgFromMap, getBgFromTypeID, Battleground::GetOtherTeamId(), LOG_ERROR, LOG_INFO, MSG_PVP_LOG_DATA, sArenaTeamMgr, STATUS_WAIT_LEAVE, TEAM_ALLIANCE, and TEAM_HORDE.
BuildUpdateWorldStatePacket()
void BattlegroundMgr::BuildUpdateWorldStatePacket (WorldPacket * data, uint32 field, uint32 value)
Definition at line 393 of file BattlegroundMgr.cpp.
 {
     data->Initialize(SMSG_UPDATE_WORLD_STATE, 4 + 4);
     *data << uint32(field);
     *data << uint32(value);
 }
References SMSG_UPDATE_WORLD_STATE.
CheckBattleMasters()
void BattlegroundMgr::CheckBattleMasters ()
Definition at line 903 of file BattlegroundMgr.cpp.
 {
     CreatureTemplateContainer const* ctc = sObjectMgr->GetCreatureTemplates();
     for (CreatureTemplateContainer::const_iterator itr = ctc->begin(); itr != ctc->end(); ++itr)
     {
         if ((itr->second.npcflag & UNIT_NPC_FLAG_BATTLEMASTER) && mBattleMastersMap.find(itr->second.Entry) == mBattleMastersMap.end())
         {
             LOG_ERROR("sql.sql", "CreatureTemplate (Entry: %u) has UNIT_NPC_FLAG_BATTLEMASTER but no data in `battlemaster_entry` table. Removing flag!", itr->second.Entry);
             const_cast<CreatureTemplate*>(&itr->second)->npcflag &= ~UNIT_NPC_FLAG_BATTLEMASTER;
         }
     }
 }
References LOG_ERROR, mBattleMastersMap, sObjectMgr, and UNIT_NPC_FLAG_BATTLEMASTER.
Referenced by LoadBattleMastersEntry().
CreateBattleground()
bool BattlegroundMgr::CreateBattleground (CreateBattlegroundData & data) private
Definition at line 491 of file BattlegroundMgr.cpp.
 {
     // Create the BG
     Battleground* bg = nullptr;
     bg = BattlegroundMgr::bgtypeToBattleground[data.bgTypeId];
     if (bg == nullptr)
         return false;
     if (data.bgTypeId == BATTLEGROUND_RB)
         bg->SetRandom(true);
     bg->SetMapId(data.MapID);
     bg->SetBgTypeID(data.bgTypeId);
     bg->SetInstanceID(0);
     bg->SetArenaorBGType(data.IsArena);
     bg->SetMinPlayersPerTeam(data.MinPlayersPerTeam);
     bg->SetMaxPlayersPerTeam(data.MaxPlayersPerTeam);
     bg->SetName(data.BattlegroundName);
     bg->SetTeamStartLoc(TEAM_ALLIANCE, data.Team1StartLocX, data.Team1StartLocY, data.Team1StartLocZ, data.Team1StartLocO);
     bg->SetTeamStartLoc(TEAM_HORDE,    data.Team2StartLocX, data.Team2StartLocY, data.Team2StartLocZ, data.Team2StartLocO);
     bg->SetStartMaxDist(data.StartMaxDist);
     bg->SetLevelRange(data.LevelMin, data.LevelMax);
     bg->SetScriptId(data.scriptId);
     AddBattleground(bg);
     return true;
 }
References AddBattleground(), BATTLEGROUND_RB, bg(), bgtypeToBattleground, TEAM_ALLIANCE, and TEAM_HORDE.
Referenced by CreateInitialBattlegrounds().
CreateInitialBattlegrounds()
void BattlegroundMgr::CreateInitialBattlegrounds ()
Definition at line 521 of file BattlegroundMgr.cpp.
 {
     uint32 oldMSTime = getMSTime();
     _battlegroundMapTemplates.clear();
     _battlegroundTemplates.clear();
     //                                               0   1                  2                  3       4       5                 6               7              8            9             10      11
     QueryResult result = WorldDatabase.Query("SELECT ID, MinPlayersPerTeam, MaxPlayersPerTeam, MinLvl, MaxLvl, AllianceStartLoc, AllianceStartO, HordeStartLoc, HordeStartO, StartMaxDist, Weight, ScriptName FROM battleground_template");
     if (!result)
     {
         LOG_ERROR("bg.battleground", ">> Loaded 0 battlegrounds. DB table `battleground_template` is empty.");
         return;
     }
     uint32 count = 0;
     do
     {
         Field* fields = result->Fetch();
         uint32 bgTypeId = fields[0].GetUInt32();
         if (DisableMgr::IsDisabledFor(DISABLE_TYPE_BATTLEGROUND, bgTypeId, nullptr))
             continue;
         // can be overwrite by values from DB
         BattlemasterListEntry const* bl = sBattlemasterListStore.LookupEntry(bgTypeId);
         if (!bl)
         {
             LOG_ERROR("bg.battleground", "Battleground ID %u not found in BattlemasterList.dbc. Battleground not created.", bgTypeId);
             continue;
         }
         CreateBattlegroundData data;
         data.bgTypeId = BattlegroundTypeId(bgTypeId);
         data.IsArena = (bl->type == TYPE_ARENA);
         data.MinPlayersPerTeam = fields[1].GetUInt16();
         data.MaxPlayersPerTeam = fields[2].GetUInt16();
         data.LevelMin = fields[3].GetUInt8();
         data.LevelMax = fields[4].GetUInt8();
         float dist = fields[9].GetFloat();
         data.StartMaxDist = dist * dist;
         data.Weight = fields[10].GetUInt8();
         data.scriptId = sObjectMgr->GetScriptId(fields[11].GetCString());
         data.BattlegroundName = bl->name[sWorld->GetDefaultDbcLocale()];
         data.MapID = bl->mapid[0];
         if (data.MaxPlayersPerTeam == 0 || data.MinPlayersPerTeam > data.MaxPlayersPerTeam)
         {
             LOG_ERROR("bg.battleground", "Table `battleground_template` for id %u has bad values for MinPlayersPerTeam (%u) and MaxPlayersPerTeam(%u)",
                            data.bgTypeId, data.MinPlayersPerTeam, data.MaxPlayersPerTeam);
             continue;
         }
         if (data.LevelMin == 0 || data.LevelMax == 0 || data.LevelMin > data.LevelMax)
         {
             LOG_ERROR("bg.battleground", "Table `battleground_template` for id %u has bad values for LevelMin (%u) and LevelMax(%u)",
                            data.bgTypeId, data.LevelMin, data.LevelMax);
             continue;
         }
         if (data.bgTypeId == BATTLEGROUND_AA || data.bgTypeId == BATTLEGROUND_RB)
         {
             data.Team1StartLocX = 0;
             data.Team1StartLocY = 0;
             data.Team1StartLocZ = 0;
             data.Team1StartLocO = fields[6].GetFloat();
             data.Team2StartLocX = 0;
             data.Team2StartLocY = 0;
             data.Team2StartLocZ = 0;
             data.Team2StartLocO = fields[8].GetFloat();
         }
         else
         {
             uint32 startId = fields[5].GetUInt32();
             if (GraveyardStruct const* start = sGraveyard->GetGraveyard(startId))
             {
                 data.Team1StartLocX = start->x;
                 data.Team1StartLocY = start->y;
                 data.Team1StartLocZ = start->z;
                 data.Team1StartLocO = fields[6].GetFloat();
             }
             else
             {
                 LOG_ERROR("bg.battleground", "Table `battleground_template` for id %u have non-existed `game_graveyard` table id %u in field `AllianceStartLoc`. BG not created.", data.bgTypeId, startId);
                 continue;
             }
             startId = fields[7].GetUInt32();
             if (GraveyardStruct const* start = sGraveyard->GetGraveyard(startId))
             {
                 data.Team2StartLocX = start->x;
                 data.Team2StartLocY = start->y;
                 data.Team2StartLocZ = start->z;
                 data.Team2StartLocO = fields[8].GetFloat();
             }
             else
             {
                 LOG_ERROR("bg.battleground", "Table `battleground_template` for id %u have non-existed `game_graveyard` table id %u in field `HordeStartLoc`. BG not created.", data.bgTypeId, startId);
                 continue;
             }
         }
         if (!CreateBattleground(data))
             continue;
         _battlegroundTemplates[BattlegroundTypeId(bgTypeId)] = data;
         if (bl->mapid[1] == -1) // in this case we have only one mapId
             _battlegroundMapTemplates[bl->mapid[0]] = &_battlegroundTemplates[BattlegroundTypeId(bgTypeId)];
         ++count;
     } while (result->NextRow());
     LOG_INFO("server.loading", ">> Loaded %u battlegrounds in %u ms", count, GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
 }
References _battlegroundMapTemplates, _battlegroundTemplates, BATTLEGROUND_AA, BATTLEGROUND_RB, count(), CreateBattleground(), DISABLE_TYPE_BATTLEGROUND, Field::GetFloat(), getMSTime(), GetMSTimeDiffToNow(), Field::GetUInt16(), Field::GetUInt32(), Field::GetUInt8(), DisableMgr::IsDisabledFor(), LOG_ERROR, LOG_INFO, BattlemasterListEntry::mapid, BattlemasterListEntry::name, sBattlemasterListStore, sGraveyard, sObjectMgr, sWorld, BattlemasterListEntry::type, TYPE_ARENA, and WorldDatabase.
CreateNewBattleground()
Battleground * BattlegroundMgr::CreateNewBattleground (BattlegroundTypeId bgTypeId, uint32 minLevel, uint32 maxLevel, uint8 arenaType, bool isRated)
Definition at line 445 of file BattlegroundMgr.cpp.
 {
     BattlegroundTypeId bgTypeId = GetRandomBG(originalBgTypeId);
     if (originalBgTypeId == BATTLEGROUND_AA)
         originalBgTypeId = bgTypeId;
     // get the template BG
     Battleground* bg_template = GetBattlegroundTemplate(bgTypeId);
     if (!bg_template)
         return nullptr;
     Battleground* bg = nullptr;
     // create a copy of the BG template
     if (BattlegroundMgr::bgTypeToTemplate.find(bgTypeId) == BattlegroundMgr::bgTypeToTemplate.end())
     {
         return nullptr;
     }
     bg = BattlegroundMgr::bgTypeToTemplate[bgTypeId](bg_template);
     bool isRandom = bgTypeId != originalBgTypeId && !bg->isArena();
     bg->SetLevelRange(minLevel, maxLevel);
     bg->SetInstanceID(sMapMgr->GenerateInstanceId());
     bg->SetClientInstanceID(IsArenaType(originalBgTypeId) ? 0 : GetNextClientVisibleInstanceId());
     bg->Init();
     bg->SetStatus(STATUS_WAIT_JOIN); // start the joining of the bg
     bg->SetArenaType(arenaType);
     bg->SetBgTypeID(originalBgTypeId);
     bg->SetRandomTypeID(bgTypeId);
     bg->SetRated(isRated);
     bg->SetRandom(isRandom);
     // Set up correct min/max player counts for scoreboards
     if (bg->isArena())
     {
         uint32 maxPlayersPerTeam = ArenaTeam::GetReqPlayersForType(arenaType) / 2;
         sScriptMgr->OnSetArenaMaxPlayersPerTeam(arenaType, maxPlayersPerTeam);
         bg->SetMaxPlayersPerTeam(maxPlayersPerTeam);
     }
     return bg;
 }
References BATTLEGROUND_AA, bg(), bgTypeToTemplate, find(), GetBattlegroundTemplate(), GetNextClientVisibleInstanceId(), GetRandomBG(), ArenaTeam::GetReqPlayersForType(), IsArenaType(), sMapMgr, sScriptMgr, and STATUS_WAIT_JOIN.
DeleteAllBattlegrounds()
void BattlegroundMgr::DeleteAllBattlegrounds ()
Definition at line 77 of file BattlegroundMgr.cpp.
 {
     while (!m_Battlegrounds.empty())
         delete m_Battlegrounds.begin()->second;
     m_Battlegrounds.clear();
     while (!m_BattlegroundTemplates.empty())
         delete m_BattlegroundTemplates.begin()->second;
     m_BattlegroundTemplates.clear();
 }
References m_Battlegrounds, and m_BattlegroundTemplates.
Referenced by ~BattlegroundMgr().
GetBattleground()
Battleground * BattlegroundMgr::GetBattleground (uint32 InstanceID)
Definition at line 418 of file BattlegroundMgr.cpp.
 {
     if (!instanceId)
         return nullptr;
     BattlegroundContainer::const_iterator itr = m_Battlegrounds.find(instanceId);
     if (itr != m_Battlegrounds.end())
         return itr->second;
     return nullptr;
 }
References m_Battlegrounds.
Referenced by SendToBattleground().
GetBattlegroundList()
const BattlegroundContainer& BattlegroundMgr::GetBattlegroundList () inline
Definition at line 133 of file BattlegroundMgr.h.
 { return m_Battlegrounds; } // pussywizard
References m_Battlegrounds.
GetBattlegroundQueue()
BattlegroundQueue& BattlegroundMgr::GetBattlegroundQueue (BattlegroundQueueTypeId bgQueueTypeId) inline
Definition at line 98 of file BattlegroundMgr.h.
 { return m_BattlegroundQueues[bgQueueTypeId]; }
References m_BattlegroundQueues.
GetBattlegroundTemplate()
Battleground * BattlegroundMgr::GetBattlegroundTemplate (BattlegroundTypeId bgTypeId)
Definition at line 430 of file BattlegroundMgr.cpp.
 {
     BattlegroundTemplateContainer::const_iterator itr = m_BattlegroundTemplates.find(bgTypeId);
     if (itr != m_BattlegroundTemplates.end())
         return itr->second;
     return nullptr;
 }
References m_BattlegroundTemplates.
Referenced by BuildBattlegroundListPacket(), CreateNewBattleground(), and SetHolidayWeekends().
GetBattlegroundTemplateByMapId()
CreateBattlegroundData const* BattlegroundMgr::GetBattlegroundTemplateByMapId (uint32 mapId) inline private
Definition at line 172 of file BattlegroundMgr.h.
     {
         BattlegroundMapTemplateContainer::const_iterator itr = _battlegroundMapTemplates.find(mapId);
         if (itr != _battlegroundMapTemplates.end())
             return itr->second;
         return nullptr;
     }
References _battlegroundMapTemplates.
Referenced by GetRandomBG().
GetBattlegroundTemplateByTypeId()
CreateBattlegroundData const* BattlegroundMgr::GetBattlegroundTemplateByTypeId (BattlegroundTypeId id) inline private
Definition at line 164 of file BattlegroundMgr.h.
     {
         BattlegroundTemplateMap::const_iterator itr = _battlegroundTemplates.find(id);
         if (itr != _battlegroundTemplates.end())
             return &itr->second;
         return nullptr;
     }
References _battlegroundTemplates.
Referenced by GetRandomBG().
GetBattleMasterBG()
BattlegroundTypeId BattlegroundMgr::GetBattleMasterBG (uint32 entry) const inline
Definition at line 125 of file BattlegroundMgr.h.
     {
         BattleMastersMap::const_iterator itr = mBattleMastersMap.find(entry);
         if (itr != mBattleMastersMap.end())
             return itr->second;
         return BATTLEGROUND_TYPE_NONE;
     }
References BATTLEGROUND_TYPE_NONE, and mBattleMastersMap.
GetNextClientVisibleInstanceId()
uint32 BattlegroundMgr::GetNextClientVisibleInstanceId () private
Definition at line 439 of file BattlegroundMgr.cpp.
 {
     return ++m_lastClientVisibleInstanceId;
 }
References m_lastClientVisibleInstanceId.
Referenced by CreateNewBattleground().
GetPrematureFinishTime()
uint32 BattlegroundMgr::GetPrematureFinishTime () const
Definition at line 847 of file BattlegroundMgr.cpp.
 {
     return sWorld->getIntConfig(CONFIG_BATTLEGROUND_PREMATURE_FINISH_TIMER);
 }
References CONFIG_BATTLEGROUND_PREMATURE_FINISH_TIMER, and sWorld.
GetRandomBG()
BattlegroundTypeId BattlegroundMgr::GetRandomBG (BattlegroundTypeId id) private
Definition at line 963 of file BattlegroundMgr.cpp.
 {
     if (GetBattlegroundTemplateByTypeId(bgTypeId))
     {
         std::vector<BattlegroundTypeId> ids;
         ids.reserve(16);
         std::vector<double> weights;
         weights.reserve(16);
         BattlemasterListEntry const* bl = sBattlemasterListStore.LookupEntry(bgTypeId);
         for (int32 mapId : bl->mapid)
         {
             if (mapId == -1)
                 break;
             if (CreateBattlegroundData const* bg = GetBattlegroundTemplateByMapId(mapId))
             {
                 ids.push_back(bg->bgTypeId);
                 weights.push_back(bg->Weight);
             }
         }
         return *Acore::Containers::SelectRandomWeightedContainerElement(ids, weights);
     }
     return BATTLEGROUND_TYPE_NONE;
 }
References BATTLEGROUND_TYPE_NONE, bg(), GetBattlegroundTemplateByMapId(), GetBattlegroundTemplateByTypeId(), BattlemasterListEntry::mapid, sBattlemasterListStore, and Acore::Containers::SelectRandomWeightedContainerElement().
Referenced by CreateNewBattleground().
GetRatingDiscardTimer()
uint32 BattlegroundMgr::GetRatingDiscardTimer () const
Definition at line 842 of file BattlegroundMgr.cpp.
 {
     return sWorld->getIntConfig(CONFIG_ARENA_RATING_DISCARD_TIMER);
 }
References CONFIG_ARENA_RATING_DISCARD_TIMER, and sWorld.
InitAutomaticArenaPointDistribution()
void BattlegroundMgr::InitAutomaticArenaPointDistribution ()
Definition at line 642 of file BattlegroundMgr.cpp.
 {
     if (!sWorld->getBoolConfig(CONFIG_ARENA_AUTO_DISTRIBUTE_POINTS))
         return;
     time_t wstime = time_t(sWorld->getWorldState(WS_ARENA_DISTRIBUTION_TIME));
     time_t curtime = time(nullptr);
     LOG_INFO("server.loading", "Initializing Automatic Arena Point Distribution");
     if (wstime < curtime)
     {
         m_NextAutoDistributionTime = curtime;           // reset will be called in the next update
         LOG_INFO("server.loading", "Next arena point distribution time in the past, reseting it now.");
     }
     else
         m_NextAutoDistributionTime = wstime;
     LOG_INFO("server.loading", "Automatic Arena Point Distribution initialized.");
 }
References CONFIG_ARENA_AUTO_DISTRIBUTE_POINTS, LOG_INFO, m_NextAutoDistributionTime, sWorld, and WS_ARENA_DISTRIBUTION_TIME.
instance()
BattlegroundMgr * BattlegroundMgr::instance () static
Definition at line 71 of file BattlegroundMgr.cpp.
 {
     static BattlegroundMgr instance;
     return &instance;
 }
InviteGroupToBG()
void BattlegroundMgr::InviteGroupToBG (GroupQueueInfo * ginfo, Battleground * bg, TeamId teamId) static
Definition at line 1010 of file BattlegroundMgr.cpp.
 {
     if (ginfo->IsInvitedToBGInstanceGUID)
         return;
     // set side if needed
     if (teamId != TEAM_NEUTRAL)
         ginfo->teamId = teamId;
     // set invitation
     ginfo->IsInvitedToBGInstanceGUID = bg->GetInstanceID();
     BattlegroundQueueTypeId bgQueueTypeId = BattlegroundMgr::BGQueueTypeId(ginfo->BgTypeId, ginfo->ArenaType);
     BattlegroundQueue& bgQueue = sBattlegroundMgr->GetBattlegroundQueue(bgQueueTypeId);
     // set ArenaTeamId for rated matches
     if (bg->isArena() && bg->isRated())
         bg->SetArenaTeamIdForTeam(ginfo->teamId, ginfo->ArenaTeamId);
     ginfo->RemoveInviteTime = World::GetGameTimeMS() + INVITE_ACCEPT_WAIT_TIME;
     // loop through the players
     for (auto itr : ginfo->Players)
     {
         // get the player
         Player* player = ObjectAccessor::FindConnectedPlayer(itr);
         if (!player)
             continue;
         // update average wait time
         bgQueue.PlayerInvitedToBGUpdateAverageWaitTime(ginfo);
         // increase invited counter for each invited player
         bg->IncreaseInvitedCount(ginfo->teamId);
         // create remind invite events
         BGQueueInviteEvent* inviteEvent = new BGQueueInviteEvent(player->GetGUID(), ginfo->IsInvitedToBGInstanceGUID, ginfo->BgTypeId, ginfo->ArenaType, ginfo->RemoveInviteTime);
         bgQueue.AddEvent(inviteEvent, INVITATION_REMIND_TIME);
         // create automatic remove events
         BGQueueRemoveEvent* removeEvent = new BGQueueRemoveEvent(player->GetGUID(), ginfo->IsInvitedToBGInstanceGUID, bgQueueTypeId, ginfo->RemoveInviteTime);
         bgQueue.AddEvent(removeEvent, INVITE_ACCEPT_WAIT_TIME);
         // Check queueSlot
         uint32 queueSlot = player->GetBattlegroundQueueIndex(bgQueueTypeId);
         ASSERT(queueSlot < PLAYER_MAX_BATTLEGROUND_QUEUES);
         // send status packet
         WorldPacket data;
         sBattlegroundMgr->BuildBattlegroundStatusPacket(&data, bg, queueSlot, STATUS_WAIT_JOIN, INVITE_ACCEPT_WAIT_TIME, 0, ginfo->ArenaType, TEAM_NEUTRAL, bg->isRated(), ginfo->BgTypeId);
         player->GetSession()->SendPacket(&data);
         // pussywizard:
         if (bg->isArena() && bg->isRated())
             bg->ArenaLogEntries[player->GetGUID()].Fill(player->GetName().c_str(), player->GetGUID().GetCounter(), player->GetSession()->GetAccountId(), ginfo->ArenaTeamId, player->GetSession()->GetRemoteAddress());
     }
 }
References BattlegroundQueue::AddEvent(), GroupQueueInfo::ArenaTeamId, GroupQueueInfo::ArenaType, ASSERT, bg(), BGQueueTypeId(), GroupQueueInfo::BgTypeId, ObjectAccessor::FindConnectedPlayer(), WorldSession::GetAccountId(), Player::GetBattlegroundQueueIndex(), ObjectGuid::GetCounter(), World::GetGameTimeMS(), Object::GetGUID(), WorldObject::GetName(), WorldSession::GetRemoteAddress(), Player::GetSession(), INVITATION_REMIND_TIME, INVITE_ACCEPT_WAIT_TIME, GroupQueueInfo::IsInvitedToBGInstanceGUID, PLAYER_MAX_BATTLEGROUND_QUEUES, BattlegroundQueue::PlayerInvitedToBGUpdateAverageWaitTime(), GroupQueueInfo::Players, GroupQueueInfo::RemoveInviteTime, sBattlegroundMgr, WorldSession::SendPacket(), STATUS_WAIT_JOIN, TEAM_NEUTRAL, and GroupQueueInfo::teamId.
Referenced by BattlegroundQueue::BattlegroundQueueUpdate().
isArenaTesting()
bool BattlegroundMgr::isArenaTesting () const inline
Definition at line 109 of file BattlegroundMgr.h.
 { return m_ArenaTesting; }
References m_ArenaTesting.
IsArenaType()
bool BattlegroundMgr::IsArenaType (BattlegroundTypeId bgTypeId) static
Definition at line 738 of file BattlegroundMgr.cpp.
 {
     return bgTypeId == BATTLEGROUND_AA
            || bgTypeId == BATTLEGROUND_BE
            || bgTypeId == BATTLEGROUND_NA
            || bgTypeId == BATTLEGROUND_DS
            || bgTypeId == BATTLEGROUND_RV
            || bgTypeId == BATTLEGROUND_RL;
 }
References BATTLEGROUND_AA, BATTLEGROUND_BE, BATTLEGROUND_DS, BATTLEGROUND_NA, BATTLEGROUND_RL, and BATTLEGROUND_RV.
Referenced by BattlegroundQueue::BattlegroundQueueUpdate(), and CreateNewBattleground().
IsBGWeekend()
bool BattlegroundMgr::IsBGWeekend (BattlegroundTypeId bgTypeId) static
Definition at line 958 of file BattlegroundMgr.cpp.
 {
     return IsHolidayActive(BGTypeToWeekendHolidayId(bgTypeId));
 }
References BGTypeToWeekendHolidayId(), and IsHolidayActive().
Referenced by Battleground::EndBattleground(), BattlegroundAB::Init(), BattlegroundEY::Init(), and Player::SendBGWeekendWorldStates().
isTesting()
bool BattlegroundMgr::isTesting () const inline
Definition at line 110 of file BattlegroundMgr.h.
 { return m_Testing; }
References m_Testing.
LoadBattleMastersEntry()
void BattlegroundMgr::LoadBattleMastersEntry ()
Definition at line 852 of file BattlegroundMgr.cpp.
 {
     uint32 oldMSTime = getMSTime();
     mBattleMastersMap.clear();                                  // need for reload case
     QueryResult result = WorldDatabase.Query("SELECT entry, bg_template FROM battlemaster_entry");
     if (!result)
     {
         LOG_INFO("server.loading", ">> Loaded 0 battlemaster entries. DB table `battlemaster_entry` is empty!");
         LOG_INFO("server.loading", " ");
         return;
     }
     uint32 count = 0;
     do
     {
         ++count;
         Field* fields = result->Fetch();
         uint32 entry = fields[0].GetUInt32();
         if (CreatureTemplate const* cInfo = sObjectMgr->GetCreatureTemplate(entry))
         {
             if ((cInfo->npcflag & UNIT_NPC_FLAG_BATTLEMASTER) == 0)
                 LOG_ERROR("sql.sql", "Creature (Entry: %u) listed in `battlemaster_entry` is not a battlemaster.", entry);
         }
         else
         {
             LOG_ERROR("sql.sql", "Creature (Entry: %u) listed in `battlemaster_entry` does not exist.", entry);
             continue;
         }
         uint32 bgTypeId  = fields[1].GetUInt32();
         if (!sBattlemasterListStore.LookupEntry(bgTypeId))
         {
             LOG_ERROR("sql.sql", "Table `battlemaster_entry` contain entry %u for not existed battleground type %u, ignored.", entry, bgTypeId);
             continue;
         }
         mBattleMastersMap[entry] = BattlegroundTypeId(bgTypeId);
     } while (result->NextRow());
     CheckBattleMasters();
     LOG_INFO("server.loading", ">> Loaded %u battlemaster entries in %u ms", count, GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
 }
References CheckBattleMasters(), count(), getMSTime(), GetMSTimeDiffToNow(), Field::GetUInt32(), LOG_ERROR, LOG_INFO, mBattleMastersMap, sBattlemasterListStore, sObjectMgr, UNIT_NPC_FLAG_BATTLEMASTER, and WorldDatabase.
RemoveBattleground()
void BattlegroundMgr::RemoveBattleground (BattlegroundTypeId bgTypeId, uint32 instanceId)
Definition at line 1002 of file BattlegroundMgr.cpp.
 {
     if (instanceId == 0)
         m_BattlegroundTemplates.erase(bgTypeId);
     else
         m_Battlegrounds.erase(instanceId);
 }
References m_Battlegrounds, and m_BattlegroundTemplates.
ScheduleArenaQueueUpdate()
void BattlegroundMgr::ScheduleArenaQueueUpdate (uint32 arenaRatedTeamId, BattlegroundQueueTypeId bgQueueTypeId, BattlegroundBracketId bracket_id)
Definition at line 835 of file BattlegroundMgr.cpp.
 {
     uint64 const scheduleId = ((uint64)arenaRatedTeamId << 32) | (bgQueueTypeId << 16) | bracket_id;
     if (std::find(m_ArenaQueueUpdateScheduler.begin(), m_ArenaQueueUpdateScheduler.end(), scheduleId) == m_ArenaQueueUpdateScheduler.end())
         m_ArenaQueueUpdateScheduler.push_back(scheduleId);
 }
References find(), and m_ArenaQueueUpdateScheduler.
SendAreaSpiritHealerQueryOpcode()
void BattlegroundMgr::SendAreaSpiritHealerQueryOpcode (Player * player, Battleground * bg, ObjectGuid guid)
Definition at line 728 of file BattlegroundMgr.cpp.
 {
     WorldPacket data(SMSG_AREA_SPIRIT_HEALER_TIME, 12);
     uint32 time_ = RESURRECTION_INTERVAL - bg->GetLastResurrectTime();      // resurrect every X seconds
     if (time_ == uint32(-1))
         time_ = 0;
     data << guid << time_;
     player->GetSession()->SendPacket(&data);
 }
References bg(), Player::GetSession(), RESURRECTION_INTERVAL, WorldSession::SendPacket(), and SMSG_AREA_SPIRIT_HEALER_TIME.
SendToBattleground()
void BattlegroundMgr::SendToBattleground (Player * player, uint32 InstanceID, BattlegroundTypeId bgTypeId)
Definition at line 718 of file BattlegroundMgr.cpp.
 {
     if (Battleground* bg = GetBattleground(instanceId))
     {
         float x, y, z, o;
         bg->GetTeamStartLoc(player->GetBgTeamId(), x, y, z, o);
         player->TeleportTo(bg->GetMapId(), x, y, z, o);
     }
 }
References bg(), GetBattleground(), Player::GetBgTeamId(), Player::TeleportTo(), G3D::x, G3D::y, and G3D::z.
SetHolidayWeekends()
void BattlegroundMgr::SetHolidayWeekends (uint32 mask)
Definition at line 824 of file BattlegroundMgr.cpp.
 {
     for (uint32 bgtype = 1; bgtype < MAX_BATTLEGROUND_TYPE_ID; ++bgtype)
     {
         if (bgtype == BATTLEGROUND_RB)
             continue;
         if (Battleground* bgt = GetBattlegroundTemplate(BattlegroundTypeId(bgtype)))
             bgt->SetHoliday(mask & (1 << bgtype));
     }
 }
References BATTLEGROUND_RB, GetBattlegroundTemplate(), and MAX_BATTLEGROUND_TYPE_ID.
ToggleArenaTesting()
void BattlegroundMgr::ToggleArenaTesting ()
Definition at line 810 of file BattlegroundMgr.cpp.
 {
     if (sWorld->getBoolConfig(CONFIG_DEBUG_ARENA))
     {
         m_ArenaTesting = true;
         sWorld->SendWorldText(LANG_DEBUG_ARENA_CONF);
     }
     else
     {
         m_ArenaTesting = !m_ArenaTesting;
         sWorld->SendWorldText(m_ArenaTesting ? LANG_DEBUG_ARENA_ON : LANG_DEBUG_ARENA_OFF);
     }
 }
References CONFIG_DEBUG_ARENA, LANG_DEBUG_ARENA_CONF, LANG_DEBUG_ARENA_OFF, LANG_DEBUG_ARENA_ON, m_ArenaTesting, and sWorld.
ToggleTesting()
void BattlegroundMgr::ToggleTesting ()
Definition at line 796 of file BattlegroundMgr.cpp.
 {
     if (sWorld->getBoolConfig(CONFIG_DEBUG_BATTLEGROUND))
     {
         m_Testing = true;
         sWorld->SendWorldText(LANG_DEBUG_BG_CONF);
     }
     else
     {
         m_Testing = !m_Testing;
         sWorld->SendWorldText(m_Testing ? LANG_DEBUG_BG_ON : LANG_DEBUG_BG_OFF);
     }
 }
References CONFIG_DEBUG_BATTLEGROUND, LANG_DEBUG_BG_CONF, LANG_DEBUG_BG_OFF, LANG_DEBUG_BG_ON, m_Testing, and sWorld.
Update()
void BattlegroundMgr::Update (uint32 diff)
Definition at line 89 of file BattlegroundMgr.cpp.
 {
     // update all battlegrounds and delete if needed
     for (BattlegroundContainer::iterator itr = m_Battlegrounds.begin(), itrDelete; itr != m_Battlegrounds.end(); )
     {
         itrDelete = itr++;
         Battleground* bg = itrDelete->second;
         bg->Update(diff);
         if (bg->ToBeDeleted())
         {
             itrDelete->second = nullptr;
             m_Battlegrounds.erase(itrDelete);
             delete bg;
         }
     }
     // update events
     for (int qtype = BATTLEGROUND_QUEUE_NONE; qtype < MAX_BATTLEGROUND_QUEUE_TYPES; ++qtype)
         m_BattlegroundQueues[qtype].UpdateEvents(diff);
     // update using scheduled tasks (used only for rated arenas, initial opponent search works differently than periodic queue update)
     if (!m_ArenaQueueUpdateScheduler.empty())
     {
         std::vector<uint64> scheduled;
         std::swap(scheduled, m_ArenaQueueUpdateScheduler);
         for (uint8 i = 0; i < scheduled.size(); i++)
         {
             uint32 arenaRatedTeamId = scheduled[i] >> 32;
             BattlegroundQueueTypeId bgQueueTypeId = BattlegroundQueueTypeId(scheduled[i] >> 16 & 255);
             BattlegroundBracketId bracket_id = BattlegroundBracketId(scheduled[i] & 255);
             m_BattlegroundQueues[bgQueueTypeId].BattlegroundQueueUpdate(diff, bracket_id, true, arenaRatedTeamId); // pussywizard: looking for opponents only for this team
         }
     }
     // periodic queue update
     if (m_NextPeriodicQueueUpdateTime < diff)
     {
         m_NextPeriodicQueueUpdateTime = 5 * IN_MILLISECONDS;
         // for rated arenas
         for (uint32 qtype = BATTLEGROUND_QUEUE_2v2; qtype < MAX_BATTLEGROUND_QUEUE_TYPES; ++qtype)
             for (uint32 bracket = BG_BRACKET_ID_FIRST; bracket < MAX_BATTLEGROUND_BRACKETS; ++bracket)
                 m_BattlegroundQueues[qtype].BattlegroundQueueUpdate(m_NextPeriodicQueueUpdateTime, BattlegroundBracketId(bracket), true, 0); // pussywizard: 0 for rated means looking for opponents for every team
         // for battlegrounds and not rated arenas
         // in first loop try to fill already running battlegrounds, then in a second loop try to create new battlegrounds
         for (uint32 qtype = BATTLEGROUND_QUEUE_AV; qtype < MAX_BATTLEGROUND_QUEUE_TYPES; ++qtype)
             for (uint32 bracket = BG_BRACKET_ID_FIRST; bracket < MAX_BATTLEGROUND_BRACKETS; ++bracket)
                 m_BattlegroundQueues[qtype].BattlegroundQueueUpdate(m_NextPeriodicQueueUpdateTime, BattlegroundBracketId(bracket), false, 0);
     }
     else
         m_NextPeriodicQueueUpdateTime -= diff;
     // arena points auto-distribution
     if (sWorld->getBoolConfig(CONFIG_ARENA_AUTO_DISTRIBUTE_POINTS))
     {
         if (m_AutoDistributionTimeChecker < diff)
         {
             if (time(nullptr) > m_NextAutoDistributionTime)
             {
                 sArenaTeamMgr->DistributeArenaPoints();
                 m_NextAutoDistributionTime = m_NextAutoDistributionTime + BATTLEGROUND_ARENA_POINT_DISTRIBUTION_DAY * sWorld->getIntConfig(CONFIG_ARENA_AUTO_DISTRIBUTE_INTERVAL_DAYS);
                 sWorld->setWorldState(WS_ARENA_DISTRIBUTION_TIME, uint64(m_NextAutoDistributionTime));
             }
             m_AutoDistributionTimeChecker = 600000; // 10 minutes check
         }
         else
             m_AutoDistributionTimeChecker -= diff;
     }
 }
References BATTLEGROUND_ARENA_POINT_DISTRIBUTION_DAY, BATTLEGROUND_QUEUE_2v2, BATTLEGROUND_QUEUE_AV, BATTLEGROUND_QUEUE_NONE, BattlegroundQueue::BattlegroundQueueUpdate(), bg(), BG_BRACKET_ID_FIRST, CONFIG_ARENA_AUTO_DISTRIBUTE_INTERVAL_DAYS, CONFIG_ARENA_AUTO_DISTRIBUTE_POINTS, diff(), IN_MILLISECONDS, m_ArenaQueueUpdateScheduler, m_AutoDistributionTimeChecker, m_BattlegroundQueues, m_Battlegrounds, m_NextAutoDistributionTime, m_NextPeriodicQueueUpdateTime, MAX_BATTLEGROUND_BRACKETS, MAX_BATTLEGROUND_QUEUE_TYPES, sArenaTeamMgr, swap(), sWorld, and WS_ARENA_DISTRIBUTION_TIME.
WeekendHolidayIdToBGType()
BattlegroundTypeId BattlegroundMgr::WeekendHolidayIdToBGType (HolidayIds holiday) static
Definition at line 937 of file BattlegroundMgr.cpp.
 {
     switch (holiday)
     {
         case HOLIDAY_CALL_TO_ARMS_AV:
             return BATTLEGROUND_AV;
         case HOLIDAY_CALL_TO_ARMS_EY:
             return BATTLEGROUND_EY;
         case HOLIDAY_CALL_TO_ARMS_WS:
             return BATTLEGROUND_WS;
         case HOLIDAY_CALL_TO_ARMS_SA:
             return BATTLEGROUND_SA;
         case HOLIDAY_CALL_TO_ARMS_AB:
             return BATTLEGROUND_AB;
         case HOLIDAY_CALL_TO_ARMS_IC:
             return BATTLEGROUND_IC;
         default:
             return BATTLEGROUND_TYPE_NONE;
     }
 }
References BATTLEGROUND_AB, BATTLEGROUND_AV, BATTLEGROUND_EY, BATTLEGROUND_IC, BATTLEGROUND_SA, BATTLEGROUND_TYPE_NONE, BATTLEGROUND_WS, HOLIDAY_CALL_TO_ARMS_AB, HOLIDAY_CALL_TO_ARMS_AV, HOLIDAY_CALL_TO_ARMS_EY, HOLIDAY_CALL_TO_ARMS_IC, HOLIDAY_CALL_TO_ARMS_SA, and HOLIDAY_CALL_TO_ARMS_WS.
Referenced by GameEventMgr::UpdateWorldStates().
Member Data Documentation
_battlegroundMapTemplates
BattlegroundMapTemplateContainer BattlegroundMgr::_battlegroundMapTemplates private
Definition at line 185 of file BattlegroundMgr.h.
Referenced by CreateInitialBattlegrounds(), and GetBattlegroundTemplateByMapId().
_battlegroundTemplates
BattlegroundTemplateMap BattlegroundMgr::_battlegroundTemplates private
Definition at line 184 of file BattlegroundMgr.h.
Referenced by CreateInitialBattlegrounds(), and GetBattlegroundTemplateByTypeId().
ArenaTypeToQueue
std::unordered_map< uint32, BattlegroundQueueTypeId > BattlegroundMgr::ArenaTypeToQueue static
Initial value:
=
{
    { ARENA_TYPE_2v2, BATTLEGROUND_QUEUE_2v2 },
    { ARENA_TYPE_3v3, BATTLEGROUND_QUEUE_3v3 },
    { ARENA_TYPE_5v5, BATTLEGROUND_QUEUE_5v5 }
}
Definition at line 141 of file BattlegroundMgr.h.
Referenced by BGQueueTypeId().
bgToQueue
std::unordered_map< int, BattlegroundQueueTypeId > BattlegroundMgr::bgToQueue static
Initial value:
=
{
    { BATTLEGROUND_AV, BATTLEGROUND_QUEUE_AV},
    { BATTLEGROUND_WS, BATTLEGROUND_QUEUE_WS},
    { BATTLEGROUND_AB, BATTLEGROUND_QUEUE_AB},
    { BATTLEGROUND_EY, BATTLEGROUND_QUEUE_EY},
    { BATTLEGROUND_SA, BATTLEGROUND_QUEUE_SA},
    { BATTLEGROUND_IC, BATTLEGROUND_QUEUE_IC},
    { BATTLEGROUND_RB, BATTLEGROUND_QUEUE_RB},
    { BATTLEGROUND_NA, BattlegroundQueueTypeId(0)},
    { BATTLEGROUND_BE, BattlegroundQueueTypeId(0)},
    { BATTLEGROUND_AA, BattlegroundQueueTypeId(0)},
    { BATTLEGROUND_RL, BattlegroundQueueTypeId(0)},
    { BATTLEGROUND_DS, BattlegroundQueueTypeId(0)},
    { BATTLEGROUND_RV, BattlegroundQueueTypeId(0)},
}
Definition at line 135 of file BattlegroundMgr.h.
Referenced by BGQueueTypeId().
bgtypeToBattleground
std::unordered_map< int, Battleground * > BattlegroundMgr::bgtypeToBattleground static
Initial value:
=
{
    { BATTLEGROUND_AV, new BattlegroundAV },
    { BATTLEGROUND_WS, new BattlegroundWS },
    { BATTLEGROUND_AB, new BattlegroundAB },
    { BATTLEGROUND_NA, new BattlegroundNA },
    { BATTLEGROUND_BE, new BattlegroundBE },
    { BATTLEGROUND_EY, new BattlegroundEY },
    { BATTLEGROUND_RL, new BattlegroundRL },
    { BATTLEGROUND_SA, new BattlegroundSA },
    { BATTLEGROUND_DS, new BattlegroundDS },
    { BATTLEGROUND_RV, new BattlegroundRV },
    { BATTLEGROUND_IC, new BattlegroundIC },
    { BATTLEGROUND_AA, new Battleground },
    { BATTLEGROUND_RB, new Battleground },
}
Definition at line 137 of file BattlegroundMgr.h.
Referenced by CreateBattleground().
bgTypeToTemplate
std::unordered_map< int, bgRef > BattlegroundMgr::bgTypeToTemplate static
Initial value:
=
{
    { BATTLEGROUND_AV, [](Battleground * bg_t) -> Battleground* { return new BattlegroundAV(*(BattlegroundAV*)bg_t); } },
    { BATTLEGROUND_WS, [](Battleground * bg_t) -> Battleground* { return new BattlegroundWS(*(BattlegroundWS*)bg_t); } },
    { BATTLEGROUND_AB, [](Battleground * bg_t) -> Battleground* { return new BattlegroundAB(*(BattlegroundAB*)bg_t); } },
    { BATTLEGROUND_NA, [](Battleground * bg_t) -> Battleground* { return new BattlegroundNA(*(BattlegroundNA*)bg_t); } },
    { BATTLEGROUND_BE, [](Battleground * bg_t) -> Battleground* { return new BattlegroundBE(*(BattlegroundBE*)bg_t); } },
    { BATTLEGROUND_EY, [](Battleground * bg_t) -> Battleground* { return new BattlegroundEY(*(BattlegroundEY*)bg_t); } },
    { BATTLEGROUND_RL, [](Battleground * bg_t) -> Battleground* { return new BattlegroundRL(*(BattlegroundRL*)bg_t); } },
    { BATTLEGROUND_SA, [](Battleground * bg_t) -> Battleground* { return new BattlegroundSA(*(BattlegroundSA*)bg_t); } },
    { BATTLEGROUND_DS, [](Battleground * bg_t) -> Battleground* { return new BattlegroundDS(*(BattlegroundDS*)bg_t); } },
    { BATTLEGROUND_RV, [](Battleground * bg_t) -> Battleground* { return new BattlegroundRV(*(BattlegroundRV*)bg_t); } },
    { BATTLEGROUND_IC, [](Battleground * bg_t) -> Battleground* { return new BattlegroundIC(*(BattlegroundIC*)bg_t); } },
    { BATTLEGROUND_RB, [](Battleground * bg_t) -> Battleground* { return new Battleground(*bg_t); }, },
    { BATTLEGROUND_AA, [](Battleground * bg_t) -> Battleground* { return new Battleground(*bg_t); }, },
}
Definition at line 138 of file BattlegroundMgr.h.
Referenced by CreateNewBattleground().
getBgFromMap
std::unordered_map< int, bgMapRef > BattlegroundMgr::getBgFromMap = {} static
Definition at line 139 of file BattlegroundMgr.h.
Referenced by BuildPvpLogDataPacket().
getBgFromTypeID
std::unordered_map< int, bgTypeRef > BattlegroundMgr::getBgFromTypeID static
Initial value:
=
{
    {
        BATTLEGROUND_RB,
        [](WorldPacket * data, Battleground::BattlegroundScoreMap::const_iterator itr2, Battleground * bg)
        {
            if (BattlegroundMgr::getBgFromMap.find(bg->GetMapId()) == BattlegroundMgr::getBgFromMap.end())
            {
                *data << uint32(0);
            }
            else
            {
                BattlegroundMgr::getBgFromMap[bg->GetMapId()](data, itr2);
            }
        }
    }
}
Definition at line 140 of file BattlegroundMgr.h.
Referenced by BuildPvpLogDataPacket().
m_ArenaQueueUpdateScheduler
std::vector<uint64> BattlegroundMgr::m_ArenaQueueUpdateScheduler private
Definition at line 155 of file BattlegroundMgr.h.
Referenced by ScheduleArenaQueueUpdate(), and Update().
m_ArenaTesting
bool BattlegroundMgr::m_ArenaTesting private
Definition at line 156 of file BattlegroundMgr.h.
Referenced by isArenaTesting(), and ToggleArenaTesting().
m_AutoDistributionTimeChecker
uint32 BattlegroundMgr::m_AutoDistributionTimeChecker private
Definition at line 160 of file BattlegroundMgr.h.
Referenced by Update().
m_BattlegroundQueues
BattlegroundQueue BattlegroundMgr::m_BattlegroundQueues[MAX_BATTLEGROUND_QUEUE_TYPES] private
Definition at line 153 of file BattlegroundMgr.h.
Referenced by BattlegroundMgr(), GetBattlegroundQueue(), and Update().
m_Battlegrounds
BattlegroundContainer BattlegroundMgr::m_Battlegrounds private
Definition at line 151 of file BattlegroundMgr.h.
Referenced by AddBattleground(), DeleteAllBattlegrounds(), GetBattleground(), GetBattlegroundList(), RemoveBattleground(), and Update().
m_BattlegroundTemplates
BattlegroundTemplateContainer BattlegroundMgr::m_BattlegroundTemplates private
Definition at line 150 of file BattlegroundMgr.h.
Referenced by AddBattleground(), DeleteAllBattlegrounds(), GetBattlegroundTemplate(), and RemoveBattleground().
m_lastClientVisibleInstanceId
uint32 BattlegroundMgr::m_lastClientVisibleInstanceId private
Definition at line 158 of file BattlegroundMgr.h.
Referenced by GetNextClientVisibleInstanceId().
m_NextAutoDistributionTime
time_t BattlegroundMgr::m_NextAutoDistributionTime private
Definition at line 159 of file BattlegroundMgr.h.
Referenced by InitAutomaticArenaPointDistribution(), and Update().
m_NextPeriodicQueueUpdateTime
uint32 BattlegroundMgr::m_NextPeriodicQueueUpdateTime private
Definition at line 161 of file BattlegroundMgr.h.
Referenced by Update().
m_Testing
bool BattlegroundMgr::m_Testing private
Definition at line 157 of file BattlegroundMgr.h.
Referenced by isTesting(), and ToggleTesting().
mBattleMastersMap
BattleMastersMap BattlegroundMgr::mBattleMastersMap private
Definition at line 162 of file BattlegroundMgr.h.
Referenced by CheckBattleMasters(), GetBattleMasterBG(), and LoadBattleMastersEntry().
QueueToArenaType
std::unordered_map< uint32, ArenaType > BattlegroundMgr::QueueToArenaType static
Initial value:
=
{
    { BATTLEGROUND_QUEUE_2v2, ARENA_TYPE_2v2 },
    { BATTLEGROUND_QUEUE_3v3, ARENA_TYPE_3v3 },
    { BATTLEGROUND_QUEUE_5v5, ARENA_TYPE_5v5 }
}
Definition at line 142 of file BattlegroundMgr.h.
Referenced by BGArenaType().
queueToBg
std::unordered_map< int, BattlegroundTypeId > BattlegroundMgr::queueToBg static
Initial value:
=
{
    { BATTLEGROUND_QUEUE_NONE,  BATTLEGROUND_TYPE_NONE },
    { BATTLEGROUND_QUEUE_AV,    BATTLEGROUND_AV },
    { BATTLEGROUND_QUEUE_WS,    BATTLEGROUND_WS },
    { BATTLEGROUND_QUEUE_AB,    BATTLEGROUND_AB },
    { BATTLEGROUND_QUEUE_EY,    BATTLEGROUND_EY },
    { BATTLEGROUND_QUEUE_SA,    BATTLEGROUND_SA },
    { BATTLEGROUND_QUEUE_IC,    BATTLEGROUND_IC },
    { BATTLEGROUND_QUEUE_RB,    BATTLEGROUND_RB },
    { BATTLEGROUND_QUEUE_2v2,   BATTLEGROUND_AA },
    { BATTLEGROUND_QUEUE_3v3,   BATTLEGROUND_AA },
    { BATTLEGROUND_QUEUE_5v5,   BATTLEGROUND_AA },
}
Definition at line 136 of file BattlegroundMgr.h.
Referenced by BGTemplateId().
The documentation for this class was generated from the following files:
src/server/game/Battlegrounds/BattlegroundMgr.h
src/server/game/Battlegrounds/BattlegroundMgr.cpp