Azerotcore-wotlk: npc_doctor::npc_doctorAI Struct Reference
npc_doctor::npc_doctorAI Struct Reference
Public Member Functions
npc_doctorAI (Creature *creature)
void Reset () override
void BeginEvent (Player *player)
void PatientDied (Location *point)
void PatientSaved (Creature *, Player *player, Location *point)
void UpdateAI (uint32 diff) override
void EnterCombat (Unit *) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
ObjectGuid PlayerGUID
uint32 SummonPatientTimer
uint32 SummonPatientCount
uint32 PatientDiedCount
uint32 PatientSavedCount
bool Event
GuidList Patients
std::vector< Location * > Coordinates
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 900 of file npcs_special.cpp.
Constructor & Destructor Documentation
npc_doctorAI()
npc_doctor::npc_doctorAI::npc_doctorAI (Creature * creature) inline
Definition at line 902 of file npcs_special.cpp.
 : ScriptedAI(creature) { }
Member Function Documentation
BeginEvent()
void npc_doctor::npc_doctorAI::BeginEvent (Player * player) inline
Definition at line 933 of file npcs_special.cpp.
         {
             PlayerGUID = player->GetGUID();
             SummonPatientTimer = 10000;
             SummonPatientCount = 0;
             PatientDiedCount = 0;
             PatientSavedCount = 0;
             switch (me->GetEntry())
             {
                 case DOCTOR_ALLIANCE:
                     for (uint8 i = 0; i < ALLIANCE_COORDS; ++i)
                         Coordinates.push_back(&AllianceCoords[i]);
                     break;
                 case DOCTOR_HORDE:
                     for (uint8 i = 0; i < HORDE_COORDS; ++i)
                         Coordinates.push_back(&HordeCoords[i]);
                     break;
             }
             Event = true;
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
         }
References ALLIANCE_COORDS, AllianceCoords, Coordinates, DOCTOR_ALLIANCE, DOCTOR_HORDE, Object::GetEntry(), Object::GetGUID(), HORDE_COORDS, HordeCoords, ScriptedAI::me, PatientDiedCount, PatientSavedCount, PlayerGUID, Object::SetFlag(), SummonPatientCount, SummonPatientTimer, UNIT_FIELD_FLAGS, and UNIT_FLAG_NOT_SELECTABLE.
EnterCombat()
void npc_doctor::npc_doctorAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1018 of file npcs_special.cpp.
 { }
PatientDied()
void npc_doctor::npc_doctorAI::PatientDied (Location * point) inline
Definition at line 958 of file npcs_special.cpp.
         {
             Player* player = ObjectAccessor::GetPlayer(*me, PlayerGUID);
             if (player && ((player->GetQuestStatus(6624) == QUEST_STATUS_INCOMPLETE) || (player->GetQuestStatus(6622) == QUEST_STATUS_INCOMPLETE)))
             {
                 ++PatientDiedCount;
                 if (PatientDiedCount > 5 && Event)
                 {
                     if (player->GetQuestStatus(6624) == QUEST_STATUS_INCOMPLETE)
                         player->FailQuest(6624);
                     else if (player->GetQuestStatus(6622) == QUEST_STATUS_INCOMPLETE)
                         player->FailQuest(6622);
                     Reset();
                     return;
                 }
                 Coordinates.push_back(point);
             }
             else
                 // If no player or player abandon quest in progress
                 Reset();
         }
References Coordinates, Player::FailQuest(), ObjectAccessor::GetPlayer(), Player::GetQuestStatus(), ScriptedAI::me, PatientDiedCount, PlayerGUID, QUEST_STATUS_INCOMPLETE, and Reset().
PatientSaved()
void npc_doctor::npc_doctorAI::PatientSaved (Creature * , Player * player, Location * point) inline
Definition at line 983 of file npcs_special.cpp.
         {
             if (player && PlayerGUID == player->GetGUID())
             {
                 if ((player->GetQuestStatus(6624) == QUEST_STATUS_INCOMPLETE) || (player->GetQuestStatus(6622) == QUEST_STATUS_INCOMPLETE))
                 {
                     ++PatientSavedCount;
                     if (PatientSavedCount == 15)
                     {
                         if (!Patients.empty())
{
                             for (ObjectGuid const& guid : Patients)
{
                                 if (Creature* patient = ObjectAccessor::GetCreature(*me, guid))
                                     patient->setDeathState(JUST_DIED);
                             }
                         }
                         if (player->GetQuestStatus(6624) == QUEST_STATUS_INCOMPLETE)
                             player->AreaExploredOrEventHappens(6624);
                         else if (player->GetQuestStatus(6622) == QUEST_STATUS_INCOMPLETE)
                             player->AreaExploredOrEventHappens(6622);
                         Reset();
                         return;
                     }
                     Coordinates.push_back(point);
                 }
             }
         }
References Player::AreaExploredOrEventHappens(), Coordinates, ObjectAccessor::GetCreature(), Object::GetGUID(), Player::GetQuestStatus(), JUST_DIED, ScriptedAI::me, Patients, PatientSavedCount, PlayerGUID, QUEST_STATUS_INCOMPLETE, and Reset().
Reset()
void npc_doctor::npc_doctorAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 916 of file npcs_special.cpp.
         {
             PlayerGUID.Clear();
             SummonPatientTimer = 10000;
             SummonPatientCount = 0;
             PatientDiedCount = 0;
             PatientSavedCount = 0;
             Patients.clear();
             Coordinates.clear();
             Event = false;
             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
         }
References ObjectGuid::Clear(), Coordinates, ScriptedAI::me, PatientDiedCount, Patients, PatientSavedCount, PlayerGUID, Object::RemoveFlag(), SummonPatientCount, SummonPatientTimer, UNIT_FIELD_FLAGS, and UNIT_FLAG_NOT_SELECTABLE.
Referenced by PatientDied(), PatientSaved(), and UpdateAI().
UpdateAI()
void npc_doctor::npc_doctorAI::UpdateAI (uint32 diff) override virtual
Reimplemented from ScriptedAI.
Definition at line 1153 of file npcs_special.cpp.
 {
     if (Event && SummonPatientCount >= 20)
     {
         Reset();
         return;
     }
     if (Event)
     {
         if (SummonPatientTimer <= diff)
         {
             if (Coordinates.empty())
                 return;
             std::vector<Location*>::iterator itr = Coordinates.begin() + rand() % Coordinates.size();
             uint32 patientEntry = 0;
             switch (me->GetEntry())
             {
                 case DOCTOR_ALLIANCE:
                     patientEntry = AllianceSoldierId[rand() % 3];
                     break;
                 case DOCTOR_HORDE:
                     patientEntry = HordeSoldierId[rand() % 3];
                     break;
                 default:
                     LOG_ERROR("scripts", "Invalid entry for Triage doctor. Please check your database");
                     return;
             }
             if (Location* point = *itr)
             {
                 if (Creature* Patient = me->SummonCreature(patientEntry, point->x, point->y, point->z, point->o, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 5000))
                 {
                     //303, this flag appear to be required for client side item->spell to work (TARGET_SINGLE_FRIEND)
                     Patient->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PLAYER_CONTROLLED);
                     Patients.push_back(Patient->GetGUID());
                     CAST_AI(npc_injured_patient::npc_injured_patientAI, Patient->AI())->DoctorGUID = me->GetGUID();
                     CAST_AI(npc_injured_patient::npc_injured_patientAI, Patient->AI())->Coord = point;
                     Coordinates.erase(itr);
                 }
             }
             SummonPatientTimer = 10000;
             ++SummonPatientCount;
         }
         else
             SummonPatientTimer -= diff;
     }
 }
References AllianceSoldierId, CAST_AI, Coordinates, DOCTOR_ALLIANCE, DOCTOR_HORDE, Object::GetEntry(), Object::GetGUID(), HordeSoldierId, LOG_ERROR, ScriptedAI::me, Patients, Reset(), WorldObject::SummonCreature(), SummonPatientCount, SummonPatientTimer, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, UNIT_FIELD_FLAGS, and UNIT_FLAG_PLAYER_CONTROLLED.
Member Data Documentation
Coordinates
std::vector<Location*> npc_doctor::npc_doctorAI::Coordinates
Definition at line 914 of file npcs_special.cpp.
Referenced by BeginEvent(), PatientDied(), PatientSaved(), Reset(), and UpdateAI().
Event
bool npc_doctor::npc_doctorAI::Event
Definition at line 911 of file npcs_special.cpp.
PatientDiedCount
uint32 npc_doctor::npc_doctorAI::PatientDiedCount
Definition at line 908 of file npcs_special.cpp.
Referenced by BeginEvent(), PatientDied(), and Reset().
Patients
GuidList npc_doctor::npc_doctorAI::Patients
Definition at line 913 of file npcs_special.cpp.
Referenced by PatientSaved(), Reset(), and UpdateAI().
PatientSavedCount
uint32 npc_doctor::npc_doctorAI::PatientSavedCount
Definition at line 909 of file npcs_special.cpp.
Referenced by BeginEvent(), PatientSaved(), and Reset().
PlayerGUID
ObjectGuid npc_doctor::npc_doctorAI::PlayerGUID
Definition at line 904 of file npcs_special.cpp.
Referenced by BeginEvent(), PatientDied(), PatientSaved(), and Reset().
SummonPatientCount
uint32 npc_doctor::npc_doctorAI::SummonPatientCount
Definition at line 907 of file npcs_special.cpp.
Referenced by BeginEvent(), Reset(), and UpdateAI().
SummonPatientTimer
uint32 npc_doctor::npc_doctorAI::SummonPatientTimer
Definition at line 906 of file npcs_special.cpp.
Referenced by BeginEvent(), Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/World/npcs_special.cpp