Azerotcore-wotlk: ctl_named_node_s Struct Reference
ctl_named_node_s Struct Reference
#include <ctl.h>
Public Attributes
ctl_node_t node
const char * name
size_t nchildren
const ctl_node_t * children
int(* ctl)(tsd_t *, const size_t *, size_t, void *, size_t *, void *, size_t)
Detailed Description
Definition at line 18 of file ctl.h.
Member Data Documentation
children
const ctl_node_t* ctl_named_node_s::children
Definition at line 23 of file ctl.h.
Referenced by ctl_bymib(), ctl_lookup(), and ctl_named_children().
ctl
int(* ctl_named_node_s::ctl) (tsd_t *, const size_t *, size_t, void *, size_t *, void *, size_t)
Definition at line 24 of file ctl.h.
Referenced by ctl_bymib(), ctl_byname(), and ctl_lookup().
name
const char* ctl_named_node_s::name
Definition at line 20 of file ctl.h.
Referenced by ctl_lookup().
nchildren
size_t ctl_named_node_s::nchildren
Definition at line 22 of file ctl.h.
Referenced by ctl_bymib(), and ctl_lookup().
node
ctl_node_t ctl_named_node_s::node
Definition at line 19 of file ctl.h.
The documentation for this struct was generated from the following file:
deps/jemalloc/include/jemalloc/internal/ctl.h