Azerotcore-wotlk: SmartWaypointMgr Class Reference
SmartWaypointMgr Class Reference
#include <SmartScriptMgr.h>
Public Member Functions
~SmartWaypointMgr ()
void LoadFromDB ()
WPPath * GetPath (uint32 id)
Static Public Member Functions
static SmartWaypointMgr * instance ()
Private Member Functions
SmartWaypointMgr ()
Private Attributes
std::unordered_map< uint32, WPPath * > waypoint_map
Detailed Description
Definition at line 1791 of file SmartScriptMgr.h.
Constructor & Destructor Documentation
SmartWaypointMgr()
SmartWaypointMgr::SmartWaypointMgr () inline private
Definition at line 1793 of file SmartScriptMgr.h.
 {}
~SmartWaypointMgr()
SmartWaypointMgr::~SmartWaypointMgr ()
Definition at line 101 of file SmartScriptMgr.cpp.
 {
     for (std::unordered_map<uint32, WPPath*>::iterator itr = waypoint_map.begin(); itr != waypoint_map.end(); ++itr)
     {
         for (WPPath::iterator pathItr = itr->second->begin(); pathItr != itr->second->end(); ++pathItr)
             delete pathItr->second;
         delete itr->second;
     }
 }
References waypoint_map.
Member Function Documentation
GetPath()
WPPath* SmartWaypointMgr::GetPath (uint32 id) inline
Definition at line 1801 of file SmartScriptMgr.h.
     {
         if (waypoint_map.find(id) != waypoint_map.end())
             return waypoint_map[id];
         else return 0;
     }
References waypoint_map.
instance()
SmartWaypointMgr * SmartWaypointMgr::instance () static
Definition at line 33 of file SmartScriptMgr.cpp.
 {
     static SmartWaypointMgr instance;
     return &instance;
 }
LoadFromDB()
void SmartWaypointMgr::LoadFromDB ()
Definition at line 39 of file SmartScriptMgr.cpp.
 {
     uint32 oldMSTime = getMSTime();
     for (std::unordered_map<uint32, WPPath*>::iterator itr = waypoint_map.begin(); itr != waypoint_map.end(); ++itr)
     {
         for (WPPath::iterator pathItr = itr->second->begin(); pathItr != itr->second->end(); ++pathItr)
             delete pathItr->second;
         delete itr->second;
     }
     waypoint_map.clear();
     WorldDatabasePreparedStatement* stmt = WorldDatabase.GetPreparedStatement(WORLD_SEL_SMARTAI_WP);
     PreparedQueryResult result = WorldDatabase.Query(stmt);
     if (!result)
     {
         LOG_INFO("server.loading", ">> Loaded 0 SmartAI Waypoint Paths. DB table `waypoints` is empty.");
         LOG_INFO("server.loading", " ");
         return;
     }
     uint32 count = 0;
     uint32 total = 0;
     uint32 last_entry = 0;
     uint32 last_id = 1;
     do
     {
         Field* fields = result->Fetch();
         uint32 entry = fields[0].GetUInt32();
         uint32 id = fields[1].GetUInt32();
         float x, y, z, o;
         x = fields[2].GetFloat();
         y = fields[3].GetFloat();
         z = fields[4].GetFloat();
         o = fields[5].GetFloat();
         uint32 delay = fields[6].GetUInt32();
         if (last_entry != entry)
         {
             waypoint_map[entry] = new WPPath();
             last_id = 1;
             count++;
         }
         if (last_id != id)
             LOG_ERROR("sql.sql", "SmartWaypointMgr::LoadFromDB: Path entry %u, unexpected point id %u, expected %u.", entry, id, last_id);
         last_id++;
         (*waypoint_map[entry])[id] = new WayPoint(id, x, y, z, o, delay);
         last_entry = entry;
         total++;
     } while (result->NextRow());
     LOG_INFO("server.loading", ">> Loaded %u SmartAI waypoint paths (total %u waypoints) in %u ms", count, total, GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
 }
References count(), Field::GetFloat(), getMSTime(), GetMSTimeDiffToNow(), Field::GetUInt32(), LOG_ERROR, LOG_INFO, waypoint_map, WORLD_SEL_SMARTAI_WP, WorldDatabase, G3D::x, G3D::y, and G3D::z.
Member Data Documentation
waypoint_map
std::unordered_map<uint32, WPPath*> SmartWaypointMgr::waypoint_map private
Definition at line 1809 of file SmartScriptMgr.h.
Referenced by GetPath(), LoadFromDB(), and ~SmartWaypointMgr().
The documentation for this class was generated from the following files:
src/server/game/AI/SmartScripts/SmartScriptMgr.h
src/server/game/AI/SmartScripts/SmartScriptMgr.cpp