Azerotcore-wotlk: boss_yauj::boss_yaujAI Struct Reference
boss_yauj::boss_yaujAI Struct Reference
Public Member Functions
boss_yaujAI (Creature *creature)
void Reset () override
void JustDied (Unit *) override
void EnterCombat (Unit *) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * instance
uint32 Heal_Timer
uint32 Fear_Timer
uint32 Check_Timer
bool VemDead
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 238 of file boss_bug_trio.cpp.
Constructor & Destructor Documentation
boss_yaujAI()
boss_yauj::boss_yaujAI::boss_yaujAI (Creature * creature) inline
Definition at line 240 of file boss_bug_trio.cpp.
                                         : ScriptedAI(creature)
         {
             instance = creature->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), and instance.
Member Function Documentation
EnterCombat()
void boss_yauj::boss_yaujAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 278 of file boss_bug_trio.cpp.
         {
         }
JustDied()
void boss_yauj::boss_yaujAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 262 of file boss_bug_trio.cpp.
         {
             if (instance->GetData(DATA_BUG_TRIO_DEATH) < 2)// Unlootable if death
                 me->RemoveFlag(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_LOOTABLE);
             instance->SetData(DATA_BUG_TRIO_DEATH, 1);
             for (uint8 i = 0; i < 10; ++i)
             {
                 if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
                 {
                     if (Creature* Summoned = me->SummonCreature(15621, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), 0, TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN, 90000))
                         Summoned->AI()->AttackStart(target);
                 }
             }
         }
References DATA_BUG_TRIO_DEATH, ZoneScript::GetData(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), instance, ScriptedAI::me, Object::RemoveFlag(), SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), ZoneScript::SetData(), WorldObject::SummonCreature(), TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN, UNIT_DYNAMIC_FLAGS, and UNIT_DYNFLAG_LOOTABLE.
Reset()
void boss_yauj::boss_yaujAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 253 of file boss_bug_trio.cpp.
         {
             Heal_Timer = urand(25000, 40000);
             Fear_Timer = urand(12000, 24000);
             Check_Timer = 2000;
             VemDead = false;
         }
References Check_Timer, Fear_Timer, Heal_Timer, urand(), and VemDead.
UpdateAI()
void boss_yauj::boss_yaujAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 282 of file boss_bug_trio.cpp.
         {
             //Return since we have no target
             if (!UpdateVictim())
                 return;
             //Fear_Timer
             if (Fear_Timer <= diff)
             {
                 DoCastVictim(SPELL_FEAR);
                 DoResetThreat();
                 Fear_Timer = 20000;
             }
             else Fear_Timer -= diff;
             //Casting Heal to other twins or herself.
             if (Heal_Timer <= diff)
             {
                 switch (urand(0, 2))
                 {
                     case 0:
                         if (Creature* kri = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_KRI)))
                             DoCast(kri, SPELL_HEAL);
                         break;
                     case 1:
                         if (Creature* vem = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_VEM)))
                             DoCast(vem, SPELL_HEAL);
                         break;
                     case 2:
                         DoCast(me, SPELL_HEAL);
                         break;
                 }
                 Heal_Timer = 15000 + rand() % 15000;
             }
             else Heal_Timer -= diff;
             //Checking if Vem is dead. If yes we will enrage.
             if (Check_Timer <= diff)
             {
                 if (!VemDead)
                 {
                     if (instance->GetData(DATA_VEMISDEAD))
                     {
                         DoCast(me, SPELL_ENRAGE);
                         VemDead = true;
                     }
                 }
                 Check_Timer = 2000;
             }
             else Check_Timer -= diff;
             DoMeleeAttackIfReady();
         }
References Check_Timer, DATA_KRI, DATA_VEM, DATA_VEMISDEAD, UnitAI::DoCast(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DoResetThreat(), Fear_Timer, ObjectAccessor::GetCreature(), ZoneScript::GetData(), InstanceScript::GetGuidData(), Heal_Timer, instance, ScriptedAI::me, SPELL_ENRAGE, SPELL_FEAR, SPELL_HEAL, CreatureAI::UpdateVictim(), urand(), and VemDead.
Member Data Documentation
Check_Timer
uint32 boss_yauj::boss_yaujAI::Check_Timer
Definition at line 249 of file boss_bug_trio.cpp.
Referenced by Reset(), and UpdateAI().
Fear_Timer
uint32 boss_yauj::boss_yaujAI::Fear_Timer
Definition at line 248 of file boss_bug_trio.cpp.
Referenced by Reset(), and UpdateAI().
Heal_Timer
uint32 boss_yauj::boss_yaujAI::Heal_Timer
Definition at line 247 of file boss_bug_trio.cpp.
Referenced by Reset(), and UpdateAI().
instance
InstanceScript* boss_yauj::boss_yaujAI::instance
Definition at line 245 of file boss_bug_trio.cpp.
Referenced by boss_yaujAI(), JustDied(), and UpdateAI().
VemDead
bool boss_yauj::boss_yaujAI::VemDead
Definition at line 251 of file boss_bug_trio.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_bug_trio.cpp