Azerotcore-wotlk: GitRevision Namespace Reference
GitRevision Namespace Reference
Functions
AC_COMMON_API char const * GetHash ()
AC_COMMON_API char const * GetDate ()
AC_COMMON_API char const * GetBranch ()
AC_COMMON_API char const * GetCMakeCommand ()
AC_COMMON_API char const * GetCMakeVersion ()
AC_COMMON_API char const * GetHostOSVersion ()
AC_COMMON_API char const * GetBuildDirectory ()
AC_COMMON_API char const * GetSourceDirectory ()
AC_COMMON_API char const * GetMySQLExecutable ()
AC_COMMON_API char const * GetFullVersion ()
AC_COMMON_API char const * GetCompanyNameStr ()
AC_COMMON_API char const * GetLegalCopyrightStr ()
AC_COMMON_API char const * GetFileVersionStr ()
AC_COMMON_API char const * GetProductVersionStr ()
Function Documentation
GetBranch()
char const * GitRevision::GetBranch ()
Definition at line 19 of file GitRevision.cpp.
 {
     return _BRANCH;
 }
GetBuildDirectory()
char const * GitRevision::GetBuildDirectory ()
Definition at line 39 of file GitRevision.cpp.
 {
     return _BUILD_DIRECTORY;
 }
Referenced by BuiltInConfig::GetBuildDirectory().
GetCMakeCommand()
char const * GitRevision::GetCMakeCommand ()
Definition at line 24 of file GitRevision.cpp.
 {
     return _CMAKE_COMMAND;
 }
Referenced by BuiltInConfig::GetCMakeCommand().
GetCMakeVersion()
char const * GitRevision::GetCMakeVersion ()
Definition at line 29 of file GitRevision.cpp.
 {
     return _CMAKE_VERSION;
 }
Referenced by server_commandscript::HandleServerDebugCommand().
GetCompanyNameStr()
char const * GitRevision::GetCompanyNameStr ()
Definition at line 75 of file GitRevision.cpp.
 {
     return VER_COMPANYNAME_STR;
 }
GetDate()
char const * GitRevision::GetDate ()
Definition at line 14 of file GitRevision.cpp.
 {
     return _DATE;
 }
Referenced by Player::AddQuest().
GetFileVersionStr()
char const * GitRevision::GetFileVersionStr ()
Definition at line 85 of file GitRevision.cpp.
 {
     return VER_FILEVERSION_STR;
 }
GetFullVersion()
char const * GitRevision::GetFullVersion ()
Definition at line 70 of file GitRevision.cpp.
 {
     return VER_COMPANYNAME_STR " rev. " VER_PRODUCTVERSION_STR " (" AZEROTH_PLATFORM_STR ", " _BUILD_DIRECTIVE ", " ACORE_LINKAGE_TYPE_STR ")";
 }
References ACORE_LINKAGE_TYPE_STR, and AZEROTH_PLATFORM_STR.
Referenced by WheatyExceptionReport::GenerateExceptionReport(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandlePlayerLoginToCharInWorld(), server_commandscript::HandleServerDebugCommand(), server_commandscript::HandleServerInfoCommand(), main(), World::SetInitialWorldSettings(), Acore::Banner::Show(), and StartDB().
GetHash()
char const * GitRevision::GetHash ()
Definition at line 9 of file GitRevision.cpp.
 {
     return _HASH;
 }
Referenced by Player::AddQuest(), StartDB(), and WheatyExceptionReport::WheatyUnhandledExceptionFilter().
GetHostOSVersion()
char const * GitRevision::GetHostOSVersion ()
Definition at line 34 of file GitRevision.cpp.
 {
     return _CMAKE_HOST_SYSTEM;
 }
Referenced by server_commandscript::HandleServerDebugCommand().
GetLegalCopyrightStr()
char const * GitRevision::GetLegalCopyrightStr ()
Definition at line 80 of file GitRevision.cpp.
 {
     return VER_LEGALCOPYRIGHT_STR;
 }
GetMySQLExecutable()
char const * GitRevision::GetMySQLExecutable ()
Definition at line 49 of file GitRevision.cpp.
 {
     return _MYSQL_EXECUTABLE;
 }
Referenced by BuiltInConfig::GetMySQLExecutable().
GetProductVersionStr()
char const * GitRevision::GetProductVersionStr ()
Definition at line 90 of file GitRevision.cpp.
 {
     return VER_PRODUCTVERSION_STR;
 }
GetSourceDirectory()
char const * GitRevision::GetSourceDirectory ()
Definition at line 44 of file GitRevision.cpp.
 {
     return _SOURCE_DIRECTORY;
 }
Referenced by BuiltInConfig::GetSourceDirectory().