Azerotcore-wotlk: src/server/game/Grids/ObjectGridLoader.cpp File Reference
ObjectGridLoader.cpp File Reference
#include "CellImpl.h"
#include "Corpse.h"
#include "Creature.h"
#include "CreatureAI.h"
#include "DynamicObject.h"
#include "GameObject.h"
#include "ObjectAccessor.h"
#include "ObjectGridLoader.h"
#include "ObjectMgr.h"
#include "Transport.h"
#include "Vehicle.h"
Classes
class ObjectWorldLoader
Functions
template<class T >
void AddObjectHelper (CellCoord &cell, GridRefMgr< T > &m, uint32 &count, Map *, T *obj)
template<>
void AddObjectHelper (CellCoord &cell, CreatureMapType &m, uint32 &count, Map *map, Creature *obj)
template<>
void AddObjectHelper (CellCoord &cell, GameObjectMapType &m, uint32 &count, Map *map, GameObject *obj)
template<class T >
void LoadHelper (CellGuidSet const &guid_set, CellCoord &cell, GridRefMgr< T > &m, uint32 &count, Map *map)
template<>
void LoadHelper (CellGuidSet const &guid_set, CellCoord &cell, GridRefMgr< GameObject > &m, uint32 &count, Map *map)
Function Documentation
AddObjectHelper() [1/3]
template<> void AddObjectHelper (CellCoord & cell, CreatureMapType & m, uint32 & count, Map * map, Creature * obj)
Definition at line 77 of file ObjectGridLoader.cpp.
 {
     obj->AddToGrid(m);
     ObjectGridLoader::SetObjectCell(obj, cell);
     obj->AddToWorld();
     if (obj->isActiveObject())
         map->AddToActive(obj);
     ++count;
 }
References Map::AddToActive(), GridObject< T >::AddToGrid(), Creature::AddToWorld(), WorldObject::isActiveObject(), and ObjectGridLoader::SetObjectCell().
AddObjectHelper() [2/3]
template<> void AddObjectHelper (CellCoord & cell, GameObjectMapType & m, uint32 & count, Map * map, GameObject * obj)
Definition at line 89 of file ObjectGridLoader.cpp.
 {
     obj->AddToGrid(m);
     ObjectGridLoader::SetObjectCell(obj, cell);
     obj->AddToWorld();
     if (obj->isActiveObject())
         map->AddToActive(obj);
     ++count;
 }
References Map::AddToActive(), GridObject< T >::AddToGrid(), GameObject::AddToWorld(), WorldObject::isActiveObject(), and ObjectGridLoader::SetObjectCell().
AddObjectHelper() [3/3]
template<class T > void AddObjectHelper (CellCoord & cell, GridRefMgr< T > & m, uint32 & count, Map * , T * obj)
Definition at line 68 of file ObjectGridLoader.cpp.
 {
     obj->AddToGrid(m);
     ObjectGridLoader::SetObjectCell(obj, cell);
     obj->AddToWorld();
     ++count;
 }
References ObjectGridLoader::SetObjectCell().
Referenced by LoadHelper().
LoadHelper() [1/2]
template<> void LoadHelper (CellGuidSet const & guid_set, CellCoord & cell, GridRefMgr< GameObject > & m, uint32 & count, Map * map)
Definition at line 119 of file ObjectGridLoader.cpp.
 {
     for (CellGuidSet::const_iterator i_guid = guid_set.begin(); i_guid != guid_set.end(); ++i_guid)
     {
         ObjectGuid::LowType guid = *i_guid;
         GameObjectData const* data = sObjectMgr->GetGOData(guid);
         GameObject* obj = data && sObjectMgr->IsGameObjectStaticTransport(data->id) ? new StaticTransport() : new GameObject();
         if (!obj->LoadFromDB(guid, map))
         {
             delete obj;
             continue;
         }
         AddObjectHelper(cell, m, count, map, obj);
     }
 }
References AddObjectHelper(), GameObjectData::id, GameObject::LoadFromDB(), and sObjectMgr.
LoadHelper() [2/2]
template<class T > void LoadHelper (CellGuidSet const & guid_set, CellCoord & cell, GridRefMgr< T > & m, uint32 & count, Map * map)
Definition at line 101 of file ObjectGridLoader.cpp.
 {
     for (CellGuidSet::const_iterator i_guid = guid_set.begin(); i_guid != guid_set.end(); ++i_guid)
     {
         T* obj = new T;
         ObjectGuid::LowType guid = *i_guid;
         if (!obj->LoadFromDB(guid, map))
         {
             delete obj;
             continue;
         }
         AddObjectHelper(cell, m, count, map, obj);
     }
 }
References AddObjectHelper().
Referenced by ObjectGridLoader::Visit().