Azerotcore-wotlk: deps/acore/mysql-tools/dump-parser.c File Reference
dump-parser.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
Macros
#define BUFFER 100000
Functions
bool is_escaped (char *string, int offset)
bool is_commented (char *string)
int main (int argc, char *argv[])
Macro Definition Documentation
BUFFER
#define BUFFER 100000
Definition at line 13 of file dump-parser.c.
Function Documentation
is_commented()
bool is_commented (char * string)
Definition at line 25 of file dump-parser.c.
{
     char buffer[4];
     sprintf(buffer, "%.3s", string);
     return strcmp(buffer, "-- ") == 0;
 }
References sprintf().
Referenced by main().
is_escaped()
bool is_escaped (char * string, int offset)
Definition at line 15 of file dump-parser.c.
{
     if (offset == 0) {
         return false;
     } else if (string[offset - 1] == '\\') {
         return !is_escaped(string, offset - 1);
     } else {
         return false;
     }
 }
main()
int main (int argc, char * argv[])
Definition at line 33 of file dump-parser.c.
 {
     FILE* file = argc > 1 ? fopen(argv[1], "r") : stdin;
     char buffer[BUFFER];
     char* line;
     int pos;
     int parenthesis = 0;
     bool quote = false;
     bool escape = false;
     bool comment = false;
     while (fgets(buffer, BUFFER, file) != NULL) {
         line = buffer;
         /* skip commented */
         if (comment || is_commented(line)) {
             comment = line[strlen(line) - 1] != '\n';
             fputs(line, stdout);
         } else {
             pos = 0;
             nullchar:
             while (line[pos] != '\0') {
                 /* if we are still in escape state, we need to check first char. */
                 if (!escape) {
                      /* find any character in ()' */
                     pos = strcspn(line, "()'\\");
                 }
                 if (pos > 0) {
                     /* print before match */
                     printf("%.*s", pos, line);
                 }
                 switch (line[pos]) {
                     case '(':
                         if (!quote) {
                             if (parenthesis == 0) {
                                 putchar('\n');
                             }
                             parenthesis++;
                         }
                         if (escape) {
                             escape = false;
                         }
                         break;
                     case ')':
                         if (!quote) {
                             if (parenthesis > 0) {
                                 parenthesis--;
                             } else {
                                 /* whoops */
                                 puts("\n");
                                 fputs(line, stdout);
                                 fputs("Found closing parenthesis without opening one.\n", stderr);
                                 exit(1);
                             }
                         }
                         if (escape) {
                             escape = false;
                         }
                         break;
                     case '\\':
                         escape = !escape;
                         break;
                     case '\'':
                         if (escape) {
                             escape = false;
                         } else {
                             quote = !quote;
                         }
                         break;
                     case '\0':
                         goto nullchar;
                     default:
                         if (escape) {
                             escape = false;
                         }
                         break;
                 }
                 /* print char then skip it (to make sure we don’t double match) */
                 putchar(line[pos]);
                 line = line + pos + 1;
                 pos = 0;
             }
         }
     }
     return 0;
 }
References BUFFER, buffer, G3D::escape(), mpq::file, fputs(), is_commented(), NULL, pos(), and printf().