Azerotcore-wotlk: SystemMgr Class Reference
SystemMgr Class Reference
#include <ScriptSystem.h>
Public Types
typedef std::unordered_map< uint32, ScriptPointVector > PointMoveMap
Public Member Functions
void LoadScriptWaypoints ()
ScriptPointVector const & GetPointMoveList (uint32 creatureEntry) const
Static Public Member Functions
static SystemMgr * instance ()
Protected Attributes
PointMoveMap m_mPointMoveMap
Private Member Functions
SystemMgr ()
~SystemMgr ()
Static Private Attributes
static ScriptPointVector const _empty
Detailed Description
Definition at line 61 of file ScriptSystem.h.
Member Typedef Documentation
PointMoveMap
typedef std::unordered_map<uint32, ScriptPointVector> SystemMgr::PointMoveMap
Definition at line 69 of file ScriptSystem.h.
Constructor & Destructor Documentation
SystemMgr()
SystemMgr::SystemMgr () inline private
Definition at line 63 of file ScriptSystem.h.
 {}
~SystemMgr()
SystemMgr::~SystemMgr () inline private
Definition at line 64 of file ScriptSystem.h.
 {}
Member Function Documentation
GetPointMoveList()
ScriptPointVector const& SystemMgr::GetPointMoveList (uint32 creatureEntry) const inline
Definition at line 74 of file ScriptSystem.h.
     {
         PointMoveMap::const_iterator itr = m_mPointMoveMap.find(creatureEntry);
         if (itr == m_mPointMoveMap.end())
             return _empty;
         return itr->second;
     }
References _empty, and m_mPointMoveMap.
instance()
SystemMgr * SystemMgr::instance () static
Definition at line 25 of file ScriptSystem.cpp.
 {
     static SystemMgr instance;
     return &instance;
 }
LoadScriptWaypoints()
void SystemMgr::LoadScriptWaypoints ()
Definition at line 31 of file ScriptSystem.cpp.
 {
     uint32 oldMSTime = getMSTime();
     // Drop Existing Waypoint list
     m_mPointMoveMap.clear();
     uint64 uiCreatureCount = 0;
     // Load Waypoints
     QueryResult result = WorldDatabase.Query("SELECT COUNT(entry) FROM script_waypoint GROUP BY entry");
     if (result)
         uiCreatureCount = result->GetRowCount();
     LOG_INFO("server.loading", "Loading Script Waypoints for " UI64FMTD " creature(s)...", uiCreatureCount);
     //                                     0       1         2           3           4           5
     result = WorldDatabase.Query("SELECT entry, pointid, location_x, location_y, location_z, waittime FROM script_waypoint ORDER BY pointid");
     if (!result)
     {
         LOG_INFO("server.loading", ">> Loaded 0 Script Waypoints. DB table `script_waypoint` is empty.");
         LOG_INFO("server.loading", " ");
         return;
     }
     uint32 count = 0;
     do
     {
         Field* pFields = result->Fetch();
         ScriptPointMove temp;
         temp.uiCreatureEntry   = pFields[0].GetUInt32();
         uint32 uiEntry          = temp.uiCreatureEntry;
         temp.uiPointId         = pFields[1].GetUInt32();
         temp.fX                = pFields[2].GetFloat();
         temp.fY                = pFields[3].GetFloat();
         temp.fZ                = pFields[4].GetFloat();
         temp.uiWaitTime        = pFields[5].GetUInt32();
         CreatureTemplate const* pCInfo = sObjectMgr->GetCreatureTemplate(temp.uiCreatureEntry);
         if (!pCInfo)
         {
             LOG_ERROR("sql.sql", "DB table script_waypoint has waypoint for non-existant creature entry %u", temp.uiCreatureEntry);
             continue;
         }
         if (!pCInfo->ScriptID)
             LOG_ERROR("sql.sql", "DB table script_waypoint has waypoint for creature entry %u, but creature does not have ScriptName defined and then useless.", temp.uiCreatureEntry);
         m_mPointMoveMap[uiEntry].push_back(temp);
         ++count;
     } while (result->NextRow());
     LOG_INFO("server.loading", ">> Loaded %u Script Waypoint nodes in %u ms", count, GetMSTimeDiffToNow(oldMSTime));
 }
References ScriptPointMove::fX, ScriptPointMove::fY, ScriptPointMove::fZ, Field::GetFloat(), getMSTime(), GetMSTimeDiffToNow(), Field::GetUInt32(), LOG_ERROR, LOG_INFO, m_mPointMoveMap, CreatureTemplate::ScriptID, sObjectMgr, UI64FMTD, ScriptPointMove::uiCreatureEntry, ScriptPointMove::uiPointId, ScriptPointMove::uiWaitTime, and WorldDatabase.
Member Data Documentation
_empty
ScriptPointVector const SystemMgr::_empty static private
Definition at line 88 of file ScriptSystem.h.
Referenced by GetPointMoveList().
m_mPointMoveMap
PointMoveMap SystemMgr::m_mPointMoveMap protected
Definition at line 85 of file ScriptSystem.h.
Referenced by GetPointMoveList(), and LoadScriptWaypoints().
The documentation for this class was generated from the following files:
src/server/game/Scripting/ScriptSystem.h
src/server/game/Scripting/ScriptSystem.cpp