Azerotcore-wotlk: npc_alchemist_adrianna Class Reference
npc_alchemist_adrianna Class Reference
Public Member Functions
npc_alchemist_adrianna ()
bool OnGossipHello (Player *player, Creature *creature) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 1839 of file icecrown_citadel.cpp.
Constructor & Destructor Documentation
npc_alchemist_adrianna()
npc_alchemist_adrianna::npc_alchemist_adrianna () inline
Definition at line 1842 of file icecrown_citadel.cpp.
 : CreatureScript("npc_alchemist_adrianna") { }
Member Function Documentation
OnGossipHello()
bool npc_alchemist_adrianna::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 1844 of file icecrown_citadel.cpp.
     {
         if (InstanceScript* instance = creature->GetInstanceScript())
             if (instance->GetBossState(DATA_ROTFACE) == DONE && instance->GetBossState(DATA_FESTERGUT) == DONE && !creature->FindCurrentSpellBySpellId(SPELL_HARVEST_BLIGHT_SPECIMEN) && !creature->FindCurrentSpellBySpellId(SPELL_HARVEST_BLIGHT_SPECIMEN25))
                 if (player->HasAura(SPELL_ORANGE_BLIGHT_RESIDUE) && player->HasAura(SPELL_GREEN_BLIGHT_RESIDUE))
                     creature->CastSpell(creature, SPELL_HARVEST_BLIGHT_SPECIMEN, false);
         return false;
     }
References Unit::CastSpell(), DATA_FESTERGUT, DATA_ROTFACE, DONE, Unit::FindCurrentSpellBySpellId(), WorldObject::GetInstanceScript(), Unit::HasAura(), SPELL_GREEN_BLIGHT_RESIDUE, SPELL_HARVEST_BLIGHT_SPECIMEN, SPELL_HARVEST_BLIGHT_SPECIMEN25, and SPELL_ORANGE_BLIGHT_RESIDUE.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp