Azerotcore-wotlk: src/server/scripts/CMakeLists.txt File Reference
src/server/scripts/CMakeLists.txt File Reference
Functions
message ("") GetScriptModuleList(SCRIPT_MODULE_LIST) GetModuleSourceList(MODULES_MODULE_LIST) GetInstallOffset(INSTALL_OFFSET) if(SCRIPTS MATCHES "dynamic") set(SCRIPTS_DEFAULT_LINKAGE "dynamic") elseif(SCRIPTS MATCHES "static") set(SCRIPTS_DEFAULT_LINKAGE "static") else() set(SCRIPTS_DEFAULT_LINKAGE "disabled") endif() if(MODULES MATCHES "dynamic") set(MODULES_DEFAULT_LINKAGE "dynamic") elseif(MODULES MATCHES "static") set(MODULES_DEFAULT_LINKAGE "static") else() set(MODULES_DEFAULT_LINKAGE "disabled") endif() if(SCRIPTS MATCHES "minimal") set(SCRIPTS_USE_WHITELIST ON) list(APPEND SCRIPTS_WHITELIST Commands Spells) endif() set("AC_SCRIPTS_INCLUDES" "") set("AC_MODULE_LIST" "") set("AC_SCRIPTS_LIST" "") foreach(include $
set ("AC_SCRIPTS_INCLUDES" "#include \"${include}\"\n${AC_SCRIPTS_INCLUDES}") endforeach() foreach(void $
set ("AC_MODULE_LIST" "void ${void};\n${AC_MODULE_LIST}") endforeach() foreach(scriptName $
set ("AC_SCRIPTS_LIST" " ${scriptName};\n${AC_SCRIPTS_LIST}") endforeach() foreach(SCRIPT_MODULE $
ScriptModuleNameToVariable (${SCRIPT_MODULE} SCRIPT_MODULE_VARIABLE) if($
STREQUAL default if (SCRIPTS_USE_WHITELIST) list(FIND SCRIPTS_WHITELIST "$
INDEX if (${INDEX} GREATER -1) set($
Function Documentation
if() [1/2]
INDEX if (${INDEX} GREATER -)
Definition at line 84 of file CMakeLists.txt.
           {INDEX} GREATER -1)
         set(${SCRIPT_MODULE_VARIABLE} ${SCRIPTS_DEFAULT_LINKAGE})
if() [2/2]
STREQUAL default if (SCRIPTS_USE_WHITELIST)
Definition at line 82 of file CMakeLists.txt.
                                     {SCRIPT_MODULE}" INDEX)
message()
message ("")
Definition at line 15 of file CMakeLists.txt.
                     {SCRIPT_MODULE} variables
 # when using predefined templates for script building
 # like dynamic, static, minimal-static...
 # Sets SCRIPTS_DEFAULT_LINKAGE
 if(SCRIPTS MATCHES "dynamic")
   set(SCRIPTS_DEFAULT_LINKAGE "dynamic")
 elseif(SCRIPTS MATCHES "static")
   set(SCRIPTS_DEFAULT_LINKAGE "static")
 else()
   set(SCRIPTS_DEFAULT_LINKAGE "disabled")
 endif()
 # Sets the MODULES_${SOURCE_MODULE} variables
 # when using predefined templates for script building
 # like dynamic, static
 # Sets MODULES_DEFAULT_LINKAGE
 if(MODULES MATCHES "dynamic")
   set(MODULES_DEFAULT_LINKAGE "dynamic")
 elseif(MODULES MATCHES "static")
   set(MODULES_DEFAULT_LINKAGE "static")
 else()
   set(MODULES_DEFAULT_LINKAGE "disabled")
 endif()
 # Sets SCRIPTS_USE_WHITELIST
 # Sets SCRIPTS_WHITELIST
 if(SCRIPTS MATCHES "minimal")
   set(SCRIPTS_USE_WHITELIST ON)
   # Whitelist which is used when minimal is selected
   list(APPEND SCRIPTS_WHITELIST Commands Spells)
 endif()
 # Add support old api modules
 CU_GET_GLOBAL("AC_ADD_SCRIPTS_LIST")
 CU_GET_GLOBAL("AC_ADD_SCRIPTS_INCLUDE")
 set("AC_SCRIPTS_INCLUDES" "")
 set("AC_MODULE_LIST" "")
 set("AC_SCRIPTS_LIST" "")
 foreach(include ${AC_ADD_SCRIPTS_INCLUDE})
Referenced by Log::_outMessageFmt(), AppenderConsole::_write(), AppenderFile::_write(), AppenderDB::_write(), Acore::Abort(), GossipMenu::AddMenuItem(), Acore::Assert(), ChatHandler::BuildChatPacket(), MMAP::MapBuilder::buildMoveMapTile(), MMAP::MapBuilder::buildNavMesh(), ArenaSpectator::CreatePacket(), Acore::Error(), BattlegroundAB::EventPlayerClickedOnFlag(), Acore::Fatal(), finish(), MMAP::IntermediateValues::generateObjFile(), message_commandscript::HandleAnnounceCommand(), message_commandscript::HandleGMAnnounceCommand(), message_commandscript::HandleGMNameAnnounceCommand(), message_commandscript::HandleGMNotifyCommand(), WorldSession::HandleGMTicketCreateOpcode(), WorldSession::HandleGMTicketUpdateOpcode(), message_commandscript::HandleNameAnnounceCommand(), message_commandscript::HandleNotifyCommand(), WorldSession::HandleTextEmoteOpcode(), Log::outCommand(), Log::outMessage(), WorldPackets::PacketArrayMaxCapacityException::PacketArrayMaxCapacityException(), anonymous_namespace{Config.cpp}::PrintError(), AchievementMgr::SendAchievementEarned(), GmTicket::SetMessage(), Acore::Warning(), Appender::write(), and Logger::write().
ScriptModuleNameToVariable()
ScriptModuleNameToVariable (${SCRIPT_MODULE})
Definition at line 79 of file CMakeLists.txt.
                               {SCRIPT_MODULE} SCRIPT_MODULE_VARIABLE)
   if(${SCRIPT_MODULE_VARIABLE} STREQUAL "default")
set() [1/3]
set ("AC_MODULE_LIST" "void ${void};\n${AC_MODULE_LIST}")
Definition at line 69 of file CMakeLists.txt.
                               {void};\n${AC_MODULE_LIST}")
 endforeach()
 foreach(scriptName ${AC_ADD_SCRIPTS_LIST})
set() [2/3]
set ("AC_SCRIPTS_INCLUDES" "#include \"${include}\"\n${AC_SCRIPTS_INCLUDES}")
Definition at line 65 of file CMakeLists.txt.
                                          {include}\"\n${AC_SCRIPTS_INCLUDES}")
 endforeach()
 foreach(void ${AC_ADD_SCRIPTS_LIST})
Referenced by AddItemsSetItem(), lookup_commandscript::HandleLookupItemSetCommand(), WorldModelHandler::InsertModelGeometry(), Object::PrintIndexError(), RemoveItemsSetItem(), Unit::SetInstantCast(), Channel::SetMode(), Channel::SetModerator(), Channel::SetMute(), and Runes::SetRuneState().
set() [3/3]
set ("AC_SCRIPTS_LIST" " ${scriptName};\n${AC_SCRIPTS_LIST}")
Definition at line 73 of file CMakeLists.txt.
                               {scriptName};\n${AC_SCRIPTS_LIST}")
 endforeach()
 # Set the SCRIPTS_${SCRIPT_MODULE} variables from the
 # variables set above
 foreach(SCRIPT_MODULE ${SCRIPT_MODULE_LIST})