Azerotcore-wotlk: src/server/shared/Secrets/SecretMgr.cpp File Reference
SecretMgr.cpp File Reference
#include "SecretMgr.h"
#include "AES.h"
#include "Argon2.h"
#include "Config.h"
#include "CryptoGenerics.h"
#include "DatabaseEnv.h"
#include "Errors.h"
#include "Log.h"
#include "SharedDefines.h"
#include <functional>
Classes
struct SecretInfo
Macros
#define SECRET_FLAG_FOR(key, val, server) server ## _ ## key = (val ## ull << (16*SERVER_PROCESS_ ## server))
#define SECRET_FLAG(key, val) SECRET_FLAG_ ## key = val, SECRET_FLAG_FOR(key, val, AUTHSERVER), SECRET_FLAG_FOR(key, val, WORLDSERVER)
Enumerations
enum SecretFlags : uint64
Functions
static Optional< BigNumber > GetHexFromConfig (char const *configKey, int bits)
Variables
static constexpr SecretInfo secret_info [NUM_SECRETS]
Macro Definition Documentation
SECRET_FLAG
#define SECRET_FLAG (key, val) SECRET_FLAG_ ## key = val, SECRET_FLAG_FOR(key, val, AUTHSERVER), SECRET_FLAG_FOR(key, val, WORLDSERVER)
Definition at line 30 of file SecretMgr.cpp.
SECRET_FLAG_FOR
#define SECRET_FLAG_FOR (key, val, server) server ## _ ## key = (val ## ull << (16*SERVER_PROCESS_ ## server))
Definition at line 29 of file SecretMgr.cpp.
Enumeration Type Documentation
SecretFlags
enum SecretFlags : uint64
Definition at line 31 of file SecretMgr.cpp.
 {
     SECRET_FLAG(DEFER_LOAD, 0x1)
 };
Function Documentation
GetHexFromConfig()
static Optional<BigNumber> GetHexFromConfig (char const * configKey, int bits) static
Definition at line 59 of file SecretMgr.cpp.
 {
     ASSERT(bits > 0);
     std::string str = sConfigMgr->GetOption<std::string>(configKey, "");
     if (str.empty())
         return {};
     BigNumber secret;
     if (!secret.SetHexStr(str.c_str()))
     {
         LOG_FATAL("server.loading", "Invalid value for '%s' - specify a hexadecimal integer of up to %d bits with no prefix.", configKey, bits);
         ABORT();
     }
     BigNumber threshold(2);
     threshold <<= bits;
     if (!((BigNumber(0) <= secret) && (secret < threshold)))
     {
         LOG_ERROR("server.loading", "Value for '%s' is out of bounds (should be an integer of up to %d bits with no prefix). Truncated to %d bits.", configKey, bits, bits);
         secret %= threshold;
     }
     ASSERT(((BigNumber(0) <= secret) && (secret < threshold)));
     return secret;
 }
References ABORT, ASSERT, G3D::bits(), LOG_ERROR, LOG_FATAL, sConfigMgr, and BigNumber::SetHexStr().
Referenced by SecretMgr::AttemptLoad().
Variable Documentation
secret_info
constexpr SecretInfo secret_info[NUM_SECRETS] static constexpr
Initial value:
=
{
    { "TOTPMasterSecret", "TOTPOldMasterSecret", 128, SERVER_PROCESS_AUTHSERVER, WORLDSERVER_DEFER_LOAD }
}
Definition at line 48 of file SecretMgr.cpp.
Referenced by SecretMgr::AttemptLoad(), SecretMgr::AttemptTransition(), and SecretMgr::Initialize().