Azerotcore-wotlk: utf8_to_utf16 Class Reference
utf8_to_utf16 Class Reference
#include <format.h>
Public Member Functions
FMT_API utf8_to_utf16 (string_view s)
operator basic_string_view< wchar_t > () const
auto size () const -> size_t
auto c_str () const -> const wchar_t *
auto str () const -> std::wstring
Private Attributes
basic_memory_buffer< wchar_t > buffer_
Detailed Description
Definition at line 1140 of file format.h.
Constructor & Destructor Documentation
utf8_to_utf16()
FMT_FUNC utf8_to_utf16::utf8_to_utf16 (string_view s) explicit
Definition at line 2527 of file format-inl.h.
{
   for_each_codepoint(s, [this](uint32_t cp, int error) {
     if (error != 0) FMT_THROW(std::runtime_error("invalid utf8"));
     if (cp <= 0xFFFF) {
       buffer_.push_back(static_cast<wchar_t>(cp));
     } else {
       cp -= 0x10000;
       buffer_.push_back(static_cast<wchar_t>(0xD800 + (cp >> 10)));
       buffer_.push_back(static_cast<wchar_t>(0xDC00 + (cp & 0x3FF)));
     }
   });
   buffer_.push_back(0);
 }
References error(), FMT_THROW, and detail::for_each_codepoint().
Member Function Documentation
c_str()
auto utf8_to_utf16::c_str () const -> const wchar_t* inline
Definition at line 1148 of file format.h.
 { return &buffer_[0]; }
Referenced by copy_unit().
operator basic_string_view< wchar_t >()
utf8_to_utf16::operator basic_string_view< wchar_t > () const inline
Definition at line 1146 of file format.h.
 { return {&buffer_[0], size()}; }
size()
auto utf8_to_utf16::size () const -> size_t inline
Definition at line 1147 of file format.h.
 { return buffer_.size() - 1; }
Referenced by copy_unit().
str()
auto utf8_to_utf16::str () const -> std::wstring inline
Definition at line 1149 of file format.h.
 { return {&buffer_[0], size()}; }
Member Data Documentation
buffer_
basic_memory_buffer<wchar_t> utf8_to_utf16::buffer_ private
Definition at line 1142 of file format.h.
The documentation for this class was generated from the following files:
deps/fmt/include/fmt/format.h
deps/fmt/include/fmt/format-inl.h