Azerotcore-wotlk: boss_rotface::boss_rotfaceAI Struct Reference
boss_rotface::boss_rotfaceAI Struct Reference
Public Member Functions
boss_rotfaceAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *who) override
void JustDied (Unit *) override
void JustReachedHome () override
void JustSummoned (Creature *summon) override
void KilledUnit (Unit *victim) override
void EnterEvadeMode () override
void SpellHitTarget (Unit *target, SpellInfo const *spell) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SpellHit (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
uint32 infectionCooldown
ObjectGuid _oozeFloodDummyGUIDs [4][2]
uint8 _oozeFloodStage
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 127 of file boss_rotface.cpp.
Constructor & Destructor Documentation
boss_rotfaceAI()
boss_rotface::boss_rotfaceAI::boss_rotfaceAI (Creature * creature) inline
Definition at line 129 of file boss_rotface.cpp.
                                            : BossAI(creature, DATA_ROTFACE)
         {
         }
Member Function Documentation
EnterCombat()
void boss_rotface::boss_rotfaceAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from BossAI.
Definition at line 150 of file boss_rotface.cpp.
         {
             if (!instance->CheckRequiredBosses(DATA_ROTFACE, who->ToPlayer()))
             {
                 EnterEvadeMode();
                 instance->DoCastSpellOnPlayers(LIGHT_S_HAMMER_TELEPORT);
                 return;
             }
             // schedule events
             events.Reset();
             events.ScheduleEvent(EVENT_SLIME_SPRAY, 20000);
             events.ScheduleEvent(EVENT_HASTEN_INFECTIONS, 90000);
             events.ScheduleEvent(EVENT_MUTATED_INFECTION, 14000);
             events.ScheduleEvent(EVENT_ROTFACE_OOZE_FLOOD, 8000);
             if (IsHeroic())
                 events.ScheduleEvent(EVENT_ROTFACE_VILE_GAS, urand(15000, 20000));
             me->setActive(true);
             Talk(SAY_AGGRO);
             DoZoneInCombat();
             if (Creature* professor = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_PROFESSOR_PUTRICIDE)))
                 professor->AI()->DoAction(ACTION_ROTFACE_COMBAT);
             instance->SetData(DATA_OOZE_DANCE_ACHIEVEMENT, uint32(true)); // reset
             // randomize ooze flood
             _oozeFloodStage = urand(0, 3);
             std::list<Creature*> list;
             GetCreatureListWithEntryInGrid(list, me, NPC_PUDDLE_STALKER, 60.0f);
             list.remove_if(RotfaceHeightCheck()); // remove from the list all on the ground
             for (std::list<Creature*>::const_iterator itr = list.begin(); itr != list.end(); ++itr)
             {
                 uint32 index = me->GetHomePosition().GetAngle(*itr) / (M_PI / 2.0f);
                 if (index > 3) index = 3;
                 if (_oozeFloodDummyGUIDs[index][0])
                     _oozeFloodDummyGUIDs[index][1] = (*itr)->GetGUID();
                 else
                     _oozeFloodDummyGUIDs[index][0] = (*itr)->GetGUID();
             }
         }
References _oozeFloodDummyGUIDs, _oozeFloodStage, ACTION_ROTFACE_COMBAT, InstanceScript::CheckRequiredBosses(), DATA_OOZE_DANCE_ACHIEVEMENT, DATA_PROFESSOR_PUTRICIDE, DATA_ROTFACE, InstanceScript::DoCastSpellOnPlayers(), CreatureAI::DoZoneInCombat(), EnterEvadeMode(), EVENT_HASTEN_INFECTIONS, EVENT_MUTATED_INFECTION, EVENT_ROTFACE_OOZE_FLOOD, EVENT_ROTFACE_VILE_GAS, EVENT_SLIME_SPRAY, ObjectAccessor::GetCreature(), GetCreatureListWithEntryInGrid(), InstanceScript::GetGuidData(), Creature::GetHomePosition(), BossAI::instance, ScriptedAI::IsHeroic(), LIGHT_S_HAMMER_TELEPORT, ScriptedAI::me, NPC_PUDDLE_STALKER, SAY_AGGRO, WorldObject::setActive(), ZoneScript::SetData(), CreatureAI::Talk(), Object::ToPlayer(), and urand().
EnterEvadeMode()
void boss_rotface::boss_rotfaceAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 222 of file boss_rotface.cpp.
         {
             me->SetControlled(false, UNIT_STATE_ROOT);
             me->DisableRotate(false);
             ScriptedAI::EnterEvadeMode();
             if (Creature* professor = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_PROFESSOR_PUTRICIDE)))
                 professor->AI()->EnterEvadeMode();
         }
References DATA_PROFESSOR_PUTRICIDE, Unit::DisableRotate(), CreatureAI::EnterEvadeMode(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), BossAI::instance, ScriptedAI::me, Unit::SetControlled(), and UNIT_STATE_ROOT.
Referenced by EnterCombat().
JustDied()
void boss_rotface::boss_rotfaceAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 193 of file boss_rotface.cpp.
         {
             instance->DoRemoveAurasDueToSpellOnPlayers(MUTATED_INFECTION);
             _JustDied();
             Talk(SAY_DEATH);
             if (Creature* professor = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_PROFESSOR_PUTRICIDE)))
                 professor->AI()->DoAction(ACTION_ROTFACE_DEATH);
         }
References BossAI::_JustDied(), ACTION_ROTFACE_DEATH, DATA_PROFESSOR_PUTRICIDE, InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), BossAI::instance, ScriptedAI::me, MUTATED_INFECTION, SAY_DEATH, and CreatureAI::Talk().
JustReachedHome()
void boss_rotface::boss_rotfaceAI::JustReachedHome () inline override virtual
Reimplemented from BossAI.
Definition at line 202 of file boss_rotface.cpp.
         {
             _JustReachedHome();
             instance->SetBossState(DATA_ROTFACE, FAIL);
         }
References BossAI::_JustReachedHome(), DATA_ROTFACE, FAIL, BossAI::instance, and InstanceScript::SetBossState().
JustSummoned()
void boss_rotface::boss_rotfaceAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
Definition at line 208 of file boss_rotface.cpp.
         {
             if (me->IsAlive() && me->IsInCombat() && !me->IsInEvadeMode())
                 summons.Summon(summon);
             else
                 summon->DespawnOrUnsummon(1);
         }
References Creature::DespawnOrUnsummon(), Unit::IsAlive(), Unit::IsInCombat(), Creature::IsInEvadeMode(), ScriptedAI::me, SummonList::Summon(), and BossAI::summons.
KilledUnit()
void boss_rotface::boss_rotfaceAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 216 of file boss_rotface.cpp.
         {
             if (victim->GetTypeId() == TYPEID_PLAYER)
                 Talk(SAY_KILL);
         }
References Object::GetTypeId(), SAY_KILL, CreatureAI::Talk(), and TYPEID_PLAYER.
Reset()
void boss_rotface::boss_rotfaceAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 137 of file boss_rotface.cpp.
         {
             infectionCooldown = 14000;
             for (uint8 i = 0; i < 4; ++i)
                 for (uint8 j = 0; j < 2; ++j)
                     _oozeFloodDummyGUIDs[i][j].Clear();
             _oozeFloodStage = 0;
             _Reset();
             events.Reset();
         }
References _oozeFloodDummyGUIDs, _oozeFloodStage, BossAI::_Reset(), and infectionCooldown.
SpellHitTarget()
void boss_rotface::boss_rotfaceAI::SpellHitTarget (Unit * target, SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 231 of file boss_rotface.cpp.
         {
             switch (spell->Id)
             {
                 case SPELL_SLIME_SPRAY:
                     Talk(SAY_SLIME_SPRAY);
                     break;
                 case 69507: // Slime Spray damage
                 case 71213:
                 case 73189:
                 case 73190:
                     if (Player* p = target->ToPlayer())
                         if (p->GetQuestStatus(QUEST_RESIDUE_RENDEZVOUS_10) == QUEST_STATUS_INCOMPLETE || p->GetQuestStatus(QUEST_RESIDUE_RENDEZVOUS_25) == QUEST_STATUS_INCOMPLETE)
                             p->CastSpell(p, SPELL_GREEN_BLIGHT_RESIDUE, true);
                     break;
                 case 69782:
                 case 69796:
                 case 69798:
                 case 69801:
                     {
                         uint32 index = getOozeFloodSpellIndex(spell->Id);
                         if (target->GetGUID() == _oozeFloodDummyGUIDs[index][0] || target->GetGUID() == _oozeFloodDummyGUIDs[index][1])
                             target->CastSpell((Unit*)nullptr, spell->Effects[0].CalcValue(), false);
                     }
                     break;
             }
         }
References _oozeFloodDummyGUIDs, Unit::CastSpell(), SpellInfo::Effects, Object::GetGUID(), getOozeFloodSpellIndex(), SpellInfo::Id, QUEST_RESIDUE_RENDEZVOUS_10, QUEST_RESIDUE_RENDEZVOUS_25, QUEST_STATUS_INCOMPLETE, SAY_SLIME_SPRAY, SPELL_GREEN_BLIGHT_RESIDUE, SPELL_SLIME_SPRAY, CreatureAI::Talk(), and Object::ToPlayer().
UpdateAI()
void boss_rotface::boss_rotfaceAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 259 of file boss_rotface.cpp.
         {
             if (!UpdateVictim() || !CheckInRoom())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_UNROOT:
                     me->SetControlled(false, UNIT_STATE_ROOT);
                     me->DisableRotate(false);
                     break;
                 case EVENT_SLIME_SPRAY:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, NonTankTargetSelector(me)))
                     {
                         if (Creature* c = me->SummonCreature(NPC_OOZE_SPRAY_STALKER, *target, TEMPSUMMON_TIMED_DESPAWN, 8000))
{
                             me->SetOrientation(me->GetAngle(c));
                             me->SetControlled(true, UNIT_STATE_ROOT);
                             me->DisableRotate(true);
                             me->SetFacingTo(me->GetAngle(c));
                             me->SendMovementFlagUpdate();
                             Talk(EMOTE_SLIME_SPRAY);
                             me->CastSpell(c, SPELL_SLIME_SPRAY, false);
                         }
                     }
                     events.DelayEvents(1);
                     events.ScheduleEvent(EVENT_SLIME_SPRAY, 20000);
                     events.ScheduleEvent(EVENT_UNROOT, 0);
                     break;
                 case EVENT_HASTEN_INFECTIONS:
                     if (infectionCooldown >= 8000)
                     {
                         infectionCooldown -= 2000;
                         events.ScheduleEvent(EVENT_HASTEN_INFECTIONS, 90000);
                     }
                     break;
                 case EVENT_MUTATED_INFECTION:
                     me->CastCustomSpell(SPELL_MUTATED_INFECTION, SPELLVALUE_MAX_TARGETS, 1, nullptr, false);
                     events.ScheduleEvent(EVENT_MUTATED_INFECTION, infectionCooldown);
                     break;
                 case EVENT_ROTFACE_OOZE_FLOOD:
                     if (Creature* professor = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_PROFESSOR_PUTRICIDE)))
                     {
                         professor->AI()->Talk(SAY_ROTFACE_OOZE_FLOOD);
                         me->CastSpell((Unit*)nullptr, oozeFloodSpells[_oozeFloodStage], true);
                         if (++_oozeFloodStage == 4)
                             _oozeFloodStage = 0;
                     }
                     events.ScheduleEvent(EVENT_ROTFACE_OOZE_FLOOD, 25000);
                     break;
                 case EVENT_ROTFACE_VILE_GAS:
                     {
                         std::list<Unit*> targets;
                         uint32 minTargets = RAID_MODE<uint32>(3, 8, 3, 8);
                         SelectTargetList(targets, minTargets, SELECT_TARGET_RANDOM, -5.0f, true);
                         float minDist = 0.0f;
                         if (targets.size() >= minTargets)
                             minDist = -5.0f;
                         if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, minDist, true))
                             if (Creature* professor = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_PROFESSOR_PUTRICIDE)))
                                 professor->CastSpell(target, SPELL_VILE_GAS_H, true); // triggered, to skip LoS check
                     }
                     events.ScheduleEvent(EVENT_ROTFACE_VILE_GAS, urand(15000, 20000));
                     break;
                 default:
                     break;
             }
             DoMeleeAttackIfReady();
         }
References _oozeFloodStage, Unit::CastCustomSpell(), Unit::CastSpell(), BossAI::CheckInRoom(), DATA_PROFESSOR_PUTRICIDE, Unit::DisableRotate(), UnitAI::DoMeleeAttackIfReady(), EMOTE_SLIME_SPRAY, EVENT_HASTEN_INFECTIONS, EVENT_MUTATED_INFECTION, EVENT_ROTFACE_OOZE_FLOOD, EVENT_ROTFACE_VILE_GAS, EVENT_SLIME_SPRAY, EVENT_UNROOT, Position::GetAngle(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Unit::HasUnitState(), infectionCooldown, BossAI::instance, ScriptedAI::me, NPC_OOZE_SPRAY_STALKER, oozeFloodSpells, SAY_ROTFACE_OOZE_FLOOD, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), UnitAI::SelectTargetList(), Unit::SendMovementFlagUpdate(), Unit::SetControlled(), Unit::SetFacingTo(), Position::SetOrientation(), SPELL_MUTATED_INFECTION, SPELL_SLIME_SPRAY, SPELL_VILE_GAS_H, SPELLVALUE_MAX_TARGETS, WorldObject::SummonCreature(), CreatureAI::Talk(), TEMPSUMMON_TIMED_DESPAWN, UNIT_STATE_CASTING, UNIT_STATE_ROOT, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
_oozeFloodDummyGUIDs
ObjectGuid boss_rotface::boss_rotfaceAI::_oozeFloodDummyGUIDs[4][2]
Definition at line 134 of file boss_rotface.cpp.
Referenced by EnterCombat(), Reset(), and SpellHitTarget().
_oozeFloodStage
uint8 boss_rotface::boss_rotfaceAI::_oozeFloodStage
Definition at line 135 of file boss_rotface.cpp.
Referenced by EnterCombat(), Reset(), and UpdateAI().
infectionCooldown
uint32 boss_rotface::boss_rotfaceAI::infectionCooldown
Definition at line 133 of file boss_rotface.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_rotface.cpp