Azerotcore-wotlk: at_trigger_the_beast_movement Class Reference
at_trigger_the_beast_movement Class Reference
The beast room areatrigger, this one triggers boss pathing. (AT Id 2066)
Public Member Functions
at_trigger_the_beast_movement ()
bool OnTrigger (Player *player, AreaTrigger const *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
The beast room areatrigger, this one triggers boss pathing. (AT Id 2066)
Definition at line 257 of file boss_the_beast.cpp.
Constructor & Destructor Documentation
at_trigger_the_beast_movement()
at_trigger_the_beast_movement::at_trigger_the_beast_movement () inline
Definition at line 260 of file boss_the_beast.cpp.
 : AreaTriggerScript("at_trigger_the_beast_movement") { }
Member Function Documentation
OnTrigger()
bool at_trigger_the_beast_movement::OnTrigger (Player * player, AreaTrigger const *) inline override virtual
Reimplemented from AreaTriggerScript.
Definition at line 262 of file boss_the_beast.cpp.
     {
         if (player->IsGameMaster())
         {
             return false;
         }
         if (InstanceScript* instance = player->GetInstanceScript())
         {
             if (Creature* beast = ObjectAccessor::GetCreature(*player, instance->GetGuidData(DATA_THE_BEAST)))
             {
                 beast->AI()->SetData(DATA_BEAST_REACHED, DATA_BEAST_REACHED);
             }
             return true;
         }
         return false;
     }
References DATA_BEAST_REACHED, DATA_THE_BEAST, ObjectAccessor::GetCreature(), WorldObject::GetInstanceScript(), and Player::IsGameMaster().
The documentation for this class was generated from the following file:
src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/boss_the_beast.cpp