Azerotcore-wotlk: src/common/Collision/Models/GameObjectModel.h File Reference
GameObjectModel.h File Reference
#include "Define.h"
#include <G3D/AABox.h>
#include <G3D/Matrix3.h>
#include <G3D/Ray.h>
#include <G3D/Vector3.h>
Classes
class GameObjectModelOwnerBase
class GameObjectModel
Namespaces
VMAP
Functions
void LoadGameObjectModelList (std::string const &dataPath)
Function Documentation
LoadGameObjectModelList()
void LoadGameObjectModelList (std::string const & dataPath)
Definition at line 44 of file GameObjectModel.cpp.
 {
     uint32 oldMSTime = getMSTime();
     FILE* model_list_file = fopen((dataPath + "vmaps/" + VMAP::GAMEOBJECT_MODELS).c_str(), "rb");
     if (!model_list_file)
     {
         LOG_ERROR("maps", "Unable to open '%s' file.", VMAP::GAMEOBJECT_MODELS);
         return;
     }
     char magic[8];
     if (fread(magic, 1, 8, model_list_file) != 8 || memcmp(magic, VMAP::VMAP_MAGIC, 8) != 0)
     {
         LOG_ERROR("maps", "File '%s' has wrong header, expected %s.", VMAP::GAMEOBJECT_MODELS, VMAP::VMAP_MAGIC);
         return;
     }
     uint32 name_length, displayId;
     uint8 isWmo;
     char buff[500];
     while (true)
     {
         Vector3 v1, v2;
         if (fread(&displayId, sizeof(uint32), 1, model_list_file) != 1)
             if (feof(model_list_file))  // EOF flag is only set after failed reading attempt
             {
                 break;
             }
         if (fread(&isWmo, sizeof(uint8), 1, model_list_file) != 1
                 || fread(&name_length, sizeof(uint32), 1, model_list_file) != 1
                 || name_length >= sizeof(buff)
                 || fread(&buff, sizeof(char), name_length, model_list_file) != name_length
                 || fread(&v1, sizeof(Vector3), 1, model_list_file) != 1
                 || fread(&v2, sizeof(Vector3), 1, model_list_file) != 1)
         {
             LOG_ERROR("maps", "File '%s' seems to be corrupted!", VMAP::GAMEOBJECT_MODELS);
             fclose(model_list_file);
             break;
         }
         if (v1.isNaN() || v2.isNaN())
         {
             LOG_ERROR("maps", "File '%s' Model '%s' has invalid v1%s v2%s values!",
                       VMAP::GAMEOBJECT_MODELS, std::string(buff, name_length).c_str(), v1.toString().c_str(), v2.toString().c_str());
             continue;
         }
         model_list.emplace(std::piecewise_construct, std::forward_as_tuple(displayId), std::forward_as_tuple(&buff[0], name_length, v1, v2, isWmo != 0));
     }
     fclose(model_list_file);
     LOG_INFO("server.loading", ">> Loaded %u GameObject models in %u ms", uint32(model_list.size()), GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
 }
References VMAP::GAMEOBJECT_MODELS, getMSTime(), GetMSTimeDiffToNow(), G3D::Vector3::isNaN(), LOG_ERROR, LOG_INFO, model_list, G3D::Vector3::toString(), and VMAP::VMAP_MAGIC.
Referenced by World::SetInitialWorldSettings().