Azerotcore-wotlk: boss_lady_vashj::boss_lady_vashjAI Struct Reference
boss_lady_vashj::boss_lady_vashjAI Struct Reference
Public Member Functions
boss_lady_vashjAI (Creature *creature)
void Reset () override
void KilledUnit (Unit *) override
void JustDied (Unit *killer) override
void EnterCombat (Unit *who) override
void JustSummoned (Creature *summon) override
void MoveInLineOfSight (Unit *who) override
void MovementInform (uint32 type, uint32 id) override
void UpdateAI (uint32 diff) override
bool CheckEvadeIfOutOfCombatArea () const override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
bool intro
int32 count
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 110 of file boss_lady_vashj.cpp.
Constructor & Destructor Documentation
boss_lady_vashjAI()
boss_lady_vashj::boss_lady_vashjAI::boss_lady_vashjAI (Creature * creature) inline
Definition at line 112 of file boss_lady_vashj.cpp.
                                               : BossAI(creature, DATA_LADY_VASHJ)
         {
             intro = false;
         }
References intro.
Member Function Documentation
CheckEvadeIfOutOfCombatArea()
bool boss_lady_vashj::boss_lady_vashjAI::CheckEvadeIfOutOfCombatArea () const inline override virtual
Reimplemented from ScriptedAI.
Definition at line 291 of file boss_lady_vashj.cpp.
         {
             return me->GetHomePosition().GetExactDist2d(me) > 80.0f || !SelectTargetFromPlayerList(100.0f);
         }
References Creature::GetHomePosition(), ScriptedAI::me, and ScriptedAI::SelectTargetFromPlayerList().
EnterCombat()
void boss_lady_vashj::boss_lady_vashjAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from BossAI.
Definition at line 141 of file boss_lady_vashj.cpp.
         {
             BossAI::EnterCombat(who);
             Talk(SAY_AGGRO);
             me->CastSpell(me, SPELL_REMOVE_TAINTED_CORES, true);
             events.ScheduleEvent(EVENT_SPELL_SHOCK_BLAST, 10000);
             events.ScheduleEvent(EVENT_SPELL_STATIC_CHARGE, 15000);
             events.ScheduleEvent(EVENT_SPELL_ENTANGLE, 20000);
             events.ScheduleEvent(EVENT_CHECK_HEALTH, 1000);
         }
References Unit::CastSpell(), BossAI::EnterCombat(), EVENT_CHECK_HEALTH, EVENT_SPELL_ENTANGLE, EVENT_SPELL_SHOCK_BLAST, EVENT_SPELL_STATIC_CHARGE, ScriptedAI::me, SAY_AGGRO, SPELL_REMOVE_TAINTED_CORES, and CreatureAI::Talk().
JustDied()
void boss_lady_vashj::boss_lady_vashjAI::JustDied (Unit * killer) inline override virtual
Reimplemented from BossAI.
Definition at line 135 of file boss_lady_vashj.cpp.
         {
             Talk(SAY_DEATH);
             BossAI::JustDied(killer);
         }
References BossAI::JustDied(), SAY_DEATH, and CreatureAI::Talk().
JustSummoned()
void boss_lady_vashj::boss_lady_vashjAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
Definition at line 153 of file boss_lady_vashj.cpp.
         {
             summons.Summon(summon);
             if (summon->GetEntry() == WORLD_TRIGGER)
                 summon->CastSpell(summon, SPELL_MAGIC_BARRIER, false);
             else if (summon->GetEntry() == NPC_ENCHANTED_ELEMENTAL)
             {
                 summon->SetWalk(true);
                 summon->m_Events.AddEvent(new startFollow(summon), summon->m_Events.CalculateTime(0));
             }
             else if (summon->GetEntry() == NPC_TOXIC_SPOREBAT)
                 summon->GetMotionMaster()->MoveRandom(30.0f);
             else if (summon->GetEntry() != NPC_TAINTED_ELEMENTAL)
                 summon->GetMotionMaster()->MovePoint(POINT_HOME, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), true, true);
         }
References EventProcessor::AddEvent(), EventProcessor::CalculateTime(), Unit::CastSpell(), Object::GetEntry(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::m_Events, ScriptedAI::me, MotionMaster::MovePoint(), MotionMaster::MoveRandom(), NPC_ENCHANTED_ELEMENTAL, NPC_TAINTED_ELEMENTAL, NPC_TOXIC_SPOREBAT, POINT_HOME, Creature::SetWalk(), SPELL_MAGIC_BARRIER, SummonList::Summon(), BossAI::summons, and WORLD_TRIGGER.
KilledUnit()
void boss_lady_vashj::boss_lady_vashjAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 126 of file boss_lady_vashj.cpp.
         {
             if (events.GetNextEventTime(EVENT_KILL_TALK) == 0)
             {
                 Talk(SAY_SLAY);
                 events.ScheduleEvent(EVENT_KILL_TALK, 6000);
             }
         }
References EVENT_KILL_TALK, SAY_SLAY, and CreatureAI::Talk().
MoveInLineOfSight()
void boss_lady_vashj::boss_lady_vashjAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
Definition at line 169 of file boss_lady_vashj.cpp.
         {
             if (!intro && who->GetTypeId() == TYPEID_PLAYER)
             {
                 intro = true;
                 Talk(SAY_INTRO);
             }
             BossAI::MoveInLineOfSight(who);
         }
References Object::GetTypeId(), intro, CreatureAI::MoveInLineOfSight(), SAY_INTRO, CreatureAI::Talk(), and TYPEID_PLAYER.
MovementInform()
void boss_lady_vashj::boss_lady_vashjAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 180 of file boss_lady_vashj.cpp.
         {
             if (type != POINT_MOTION_TYPE || id != POINT_HOME)
                 return;
             me->SetFacingTo(me->GetHomePosition().GetOrientation());
             instance->SetData(DATA_ACTIVATE_SHIELD, 0);
             events.Reset();
             events.ScheduleEvent(EVENT_SPELL_FORKED_LIGHTNING, 3000);
             events.ScheduleEvent(EVENT_SUMMON_A, 0);
             events.ScheduleEvent(EVENT_SUMMON_B, 45000);
             events.ScheduleEvent(EVENT_SUMMON_C, 60000);
             events.ScheduleEvent(EVENT_SUMMON_D, 50000);
             events.ScheduleEvent(EVENT_CHECK_HEALTH2, 1000);
         }
References DATA_ACTIVATE_SHIELD, EVENT_CHECK_HEALTH2, EVENT_SPELL_FORKED_LIGHTNING, EVENT_SUMMON_A, EVENT_SUMMON_B, EVENT_SUMMON_C, EVENT_SUMMON_D, Creature::GetHomePosition(), BossAI::instance, ScriptedAI::me, POINT_HOME, POINT_MOTION_TYPE, ZoneScript::SetData(), and Unit::SetFacingTo().
Reset()
void boss_lady_vashj::boss_lady_vashjAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 120 of file boss_lady_vashj.cpp.
         {
             count = 0;
             BossAI::Reset();
         }
References count, and BossAI::Reset().
UpdateAI()
void boss_lady_vashj::boss_lady_vashjAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 196 of file boss_lady_vashj.cpp.
         {
             EnterEvadeIfOutOfCombatArea();
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_SPELL_SHOCK_BLAST:
                     me->CastSpell(me->GetVictim(), SPELL_SHOCK_BLAST, false);
                     events.ScheduleEvent(EVENT_SPELL_SHOCK_BLAST, urand(10000, 20000));
                     break;
                 case EVENT_SPELL_STATIC_CHARGE:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 40.0f))
                         me->CastSpell(target, SPELL_STATIC_CHARGE, false);
                     events.ScheduleEvent(EVENT_SPELL_STATIC_CHARGE, 20000);
                     break;
                 case EVENT_SPELL_ENTANGLE:
                     me->CastSpell(me, SPELL_ENTANGLE, false);
                     events.ScheduleEvent(EVENT_SPELL_ENTANGLE, 30000);
                     break;
                 case EVENT_CHECK_HEALTH:
                     if (me->HealthBelowPct(71))
                     {
                         Talk(SAY_PHASE2);
                         me->SetReactState(REACT_PASSIVE);
                         me->GetMotionMaster()->MovePoint(POINT_HOME, me->GetHomePosition().GetPositionX(), me->GetHomePosition().GetPositionY(), me->GetHomePosition().GetPositionZ(), true, true);
                         break;
                     }
                     events.ScheduleEvent(EVENT_CHECK_HEALTH, 1000);
                     break;
                 case EVENT_SPELL_FORKED_LIGHTNING:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 60.0f))
                         me->CastSpell(target, SPELL_FORKED_LIGHTNING, false);
                     events.ScheduleEvent(EVENT_SPELL_FORKED_LIGHTNING, urand(2500, 5000));
                     break;
                 case EVENT_SUMMON_A:
                     me->CastSpell(me, SPELL_SUMMON_ENCHANTED_ELEMENTAL, true);
                     events.ScheduleEvent(EVENT_SUMMON_A, 2500);
                     break;
                 case EVENT_SUMMON_B:
                     me->CastSpell(me, SPELL_SUMMON_COILFANG_ELITE, true);
                     events.ScheduleEvent(EVENT_SUMMON_B, 45000);
                     break;
                 case EVENT_SUMMON_C:
                     me->CastSpell(me, SPELL_SUMMON_COILFANG_STRIDER, true);
                     events.ScheduleEvent(EVENT_SUMMON_C, 60000);
                     break;
                 case EVENT_SUMMON_D:
                     me->CastSpell(me, SPELL_SUMMON_TAINTED_ELEMENTAL, true);
                     events.ScheduleEvent(EVENT_SUMMON_D, 50000);
                     break;
                 case EVENT_CHECK_HEALTH2:
                     if (!me->HasAura(SPELL_MAGIC_BARRIER))
                     {
                         Talk(SAY_PHASE3);
                         me->SetReactState(REACT_AGGRESSIVE);
                         me->GetMotionMaster()->MoveChase(me->GetVictim());
                         events.Reset();
                         events.ScheduleEvent(EVENT_SPELL_SHOCK_BLAST, 10000);
                         events.ScheduleEvent(EVENT_SPELL_STATIC_CHARGE, 15000);
                         events.ScheduleEvent(EVENT_SPELL_ENTANGLE, 20000);
                         events.ScheduleEvent(EVENT_SUMMON_SPOREBAT, 5000);
                         break;
                     }
                     events.ScheduleEvent(EVENT_CHECK_HEALTH2, 1000);
                     break;
                 case EVENT_SUMMON_SPOREBAT:
                     me->CastSpell(me, SPELL_SUMMON_TOXIC_SPOREBAT, true);
                     events.ScheduleEvent(EVENT_SUMMON_SPOREBAT, 20000 - 1000 * std::min(count++, 16));
                     break;
             }
             if (me->GetReactState() != REACT_AGGRESSIVE || !me->isAttackReady())
                 return;
             if (!me->IsWithinMeleeRange(me->GetVictim()))
             {
                 me->resetAttackTimer();
                 me->SetSheath(SHEATH_STATE_RANGED);
                 me->CastSpell(me->GetVictim(), roll_chance_i(33) ? SPELL_MULTI_SHOT : SPELL_SHOOT, false);
                 if (roll_chance_i(15))
                     Talk(SAY_BOWSHOT);
             }
             else
             {
                 me->SetSheath(SHEATH_STATE_MELEE);
                 DoMeleeAttackIfReady();
             }
         }
References Unit::CastSpell(), count, UnitAI::DoMeleeAttackIfReady(), ScriptedAI::EnterEvadeIfOutOfCombatArea(), EVENT_CHECK_HEALTH, EVENT_CHECK_HEALTH2, EVENT_SPELL_ENTANGLE, EVENT_SPELL_FORKED_LIGHTNING, EVENT_SPELL_SHOCK_BLAST, EVENT_SPELL_STATIC_CHARGE, EVENT_SUMMON_A, EVENT_SUMMON_B, EVENT_SUMMON_C, EVENT_SUMMON_D, EVENT_SUMMON_SPOREBAT, Creature::GetHomePosition(), Unit::GetMotionMaster(), Creature::GetReactState(), Unit::GetVictim(), Unit::HasAura(), Unit::HasUnitState(), Unit::HealthBelowPct(), Unit::isAttackReady(), Unit::IsWithinMeleeRange(), ScriptedAI::me, MotionMaster::MoveChase(), MotionMaster::MovePoint(), POINT_HOME, REACT_AGGRESSIVE, REACT_PASSIVE, Unit::resetAttackTimer(), roll_chance_i(), SAY_BOWSHOT, SAY_PHASE2, SAY_PHASE3, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Creature::SetReactState(), Unit::SetSheath(), SHEATH_STATE_MELEE, SHEATH_STATE_RANGED, SPELL_ENTANGLE, SPELL_FORKED_LIGHTNING, SPELL_MAGIC_BARRIER, SPELL_MULTI_SHOT, SPELL_SHOCK_BLAST, SPELL_SHOOT, SPELL_STATIC_CHARGE, SPELL_SUMMON_COILFANG_ELITE, SPELL_SUMMON_COILFANG_STRIDER, SPELL_SUMMON_ENCHANTED_ELEMENTAL, SPELL_SUMMON_TAINTED_ELEMENTAL, SPELL_SUMMON_TOXIC_SPOREBAT, CreatureAI::Talk(), UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
count
int32 boss_lady_vashj::boss_lady_vashjAI::count
Definition at line 118 of file boss_lady_vashj.cpp.
Referenced by Reset(), and UpdateAI().
intro
bool boss_lady_vashj::boss_lady_vashjAI::intro
Definition at line 117 of file boss_lady_vashj.cpp.
Referenced by boss_lady_vashjAI(), and MoveInLineOfSight().
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_lady_vashj.cpp