Azerotcore-wotlk: src/server/game/Grids/Notifiers/GridNotifiers.cpp File Reference
GridNotifiers.cpp File Reference
#include "GridNotifiers.h"
#include "GridNotifiersImpl.h"
#include "Map.h"
#include "ObjectAccessor.h"
#include "SpellInfo.h"
#include "Transport.h"
#include "UpdateData.h"
#include "WorldPacket.h"
Functions
void CreatureUnitRelocationWorker (Creature *c, Unit *u)
Function Documentation
CreatureUnitRelocationWorker()
void CreatureUnitRelocationWorker (Creature * c, Unit * u) inline
Definition at line 150 of file GridNotifiers.cpp.
 {
     if (!u->IsAlive() || !c->IsAlive() || c == u || u->IsInFlight())
     {
         return;
     }
     if (!c->HasUnitState(UNIT_STATE_SIGHTLESS))
     {
         if (c->IsAIEnabled && c->CanSeeOrDetect(u, false, true))
         {
             c->AI()->MoveInLineOfSight_Safe(u);
         }
         else if (u->GetTypeId() == TYPEID_PLAYER && u->HasStealthAura() && c->IsAIEnabled && c->CanSeeOrDetect(u, false, true, true))
         {
             c->AI()->TriggerAlert(u);
         }
     }
 }
References mpq::c, Object::GetTypeId(), Unit::HasStealthAura(), Unit::IsAlive(), Unit::IsInFlight(), TYPEID_PLAYER, and UNIT_STATE_SIGHTLESS.
Referenced by Acore::AIRelocationNotifier::Visit(), and Acore::CreatureRelocationNotifier::Visit().