Azerotcore-wotlk: CalendarInvite Struct Reference
CalendarInvite Struct Reference
#include <CalendarMgr.h>
Public Member Functions
CalendarInvite (CalendarInvite const &calendarInvite, uint64 inviteId, uint64 eventId)
CalendarInvite ()
CalendarInvite (uint64 inviteId, uint64 eventId, ObjectGuid invitee, ObjectGuid senderGUID, time_t statusTime, CalendarInviteStatus status, CalendarModerationRank rank, std::string text)
~CalendarInvite ()
void SetInviteId (uint64 inviteId)
uint64 GetInviteId () const
void SetEventId (uint64 eventId)
uint64 GetEventId () const
void SetSenderGUID (ObjectGuid guid)
ObjectGuid GetSenderGUID () const
void SetInvitee (ObjectGuid guid)
ObjectGuid GetInviteeGUID () const
void SetStatusTime (time_t statusTime)
time_t GetStatusTime () const
void SetText (const std::string &text)
std::string GetText () const
void SetStatus (CalendarInviteStatus status)
CalendarInviteStatus GetStatus () const
void SetRank (CalendarModerationRank rank)
CalendarModerationRank GetRank () const
Private Attributes
uint64 _inviteId
uint64 _eventId
ObjectGuid _invitee
ObjectGuid _senderGUID
time_t _statusTime
CalendarInviteStatus _status
CalendarModerationRank _rank
std::string _text
Detailed Description
Definition at line 135 of file CalendarMgr.h.
Constructor & Destructor Documentation
CalendarInvite() [1/3]
CalendarInvite::CalendarInvite (CalendarInvite const & calendarInvite, uint64 inviteId, uint64 eventId) inline
Definition at line 138 of file CalendarMgr.h.
     {
         _inviteId = inviteId;
         _eventId = eventId;
         _invitee = calendarInvite.GetInviteeGUID();
         _senderGUID = calendarInvite.GetSenderGUID();
         _statusTime = calendarInvite.GetStatusTime();
         _status = calendarInvite.GetStatus();
         _rank = calendarInvite.GetRank();
         _text = calendarInvite.GetText();
     }
References _eventId, _invitee, _inviteId, _rank, _senderGUID, _status, _statusTime, _text, GetInviteeGUID(), GetRank(), GetSenderGUID(), GetStatus(), GetStatusTime(), and GetText().
CalendarInvite() [2/3]
CalendarInvite::CalendarInvite () inline
Definition at line 150 of file CalendarMgr.h.
                      : _inviteId(1), _eventId(0), _statusTime(time(nullptr)),
         _status(CALENDAR_STATUS_INVITED), _rank(CALENDAR_RANK_PLAYER), _text("") { }
CalendarInvite() [3/3]
CalendarInvite::CalendarInvite (uint64 inviteId, uint64 eventId, ObjectGuid invitee, ObjectGuid senderGUID, time_t statusTime, CalendarInviteStatus status, CalendarModerationRank rank, std::string text) inline
Definition at line 153 of file CalendarMgr.h.
                                                                                              :
         _inviteId(inviteId), _eventId(eventId), _invitee(invitee), _senderGUID(senderGUID), _statusTime(statusTime),
         _status(status), _rank(rank), _text(text) { }
~CalendarInvite()
CalendarInvite::~CalendarInvite ()
Definition at line 27 of file CalendarMgr.cpp.
 {
     // Free _inviteId only if it's a real invite and not just a pre-invite or guild announcement
     if (_inviteId != 0 && _eventId != 0)
         sCalendarMgr->FreeInviteId(_inviteId);
 }
References _eventId, _inviteId, and sCalendarMgr.
Member Function Documentation
GetEventId()
uint64 CalendarInvite::GetEventId () const inline
Definition at line 164 of file CalendarMgr.h.
 { return _eventId; }
References _eventId.
Referenced by CalendarMgr::AddInvite(), CalendarMgr::SendCalendarEventInvite(), CalendarMgr::SendCalendarEventInviteRemove(), CalendarMgr::SendCalendarEventModeratorStatusAlert(), and CalendarMgr::UpdateInvite().
GetInviteeGUID()
ObjectGuid CalendarInvite::GetInviteeGUID () const inline
Definition at line 170 of file CalendarMgr.h.
 { return _invitee; }
References _invitee.
Referenced by CalendarMgr::AddInvite(), CalendarInvite(), CalendarMgr::RemoveEvent(), CalendarMgr::SendCalendarEvent(), CalendarMgr::SendCalendarEventInvite(), CalendarMgr::SendCalendarEventInviteAlert(), CalendarMgr::SendCalendarEventInviteRemove(), CalendarMgr::SendCalendarEventModeratorStatusAlert(), CalendarMgr::SendCalendarEventStatus(), and CalendarMgr::UpdateInvite().
GetInviteId()
uint64 CalendarInvite::GetInviteId () const inline
Definition at line 161 of file CalendarMgr.h.
 { return _inviteId; }
References _inviteId.
Referenced by CalendarMgr::RemoveEvent(), CalendarMgr::SendCalendarEvent(), CalendarMgr::SendCalendarEventInvite(), CalendarMgr::SendCalendarEventInviteAlert(), and CalendarMgr::UpdateInvite().
GetRank()
CalendarModerationRank CalendarInvite::GetRank () const inline
Definition at line 182 of file CalendarMgr.h.
 { return _rank; }
References _rank.
Referenced by CalendarInvite(), CalendarMgr::SendCalendarEvent(), CalendarMgr::SendCalendarEventInviteAlert(), CalendarMgr::SendCalendarEventModeratorStatusAlert(), CalendarMgr::SendCalendarEventStatus(), and CalendarMgr::UpdateInvite().
GetSenderGUID()
ObjectGuid CalendarInvite::GetSenderGUID () const inline
Definition at line 167 of file CalendarMgr.h.
 { return _senderGUID; }
References _senderGUID.
Referenced by CalendarInvite(), CalendarMgr::SendCalendarEventInvite(), CalendarMgr::SendCalendarEventInviteAlert(), and CalendarMgr::UpdateInvite().
GetStatus()
CalendarInviteStatus CalendarInvite::GetStatus () const inline
Definition at line 179 of file CalendarMgr.h.
 { return _status; }
References _status.
Referenced by CalendarInvite(), CalendarMgr::SendCalendarEvent(), CalendarMgr::SendCalendarEventInvite(), CalendarMgr::SendCalendarEventInviteAlert(), CalendarMgr::SendCalendarEventStatus(), and CalendarMgr::UpdateInvite().
GetStatusTime()
time_t CalendarInvite::GetStatusTime () const inline
Definition at line 173 of file CalendarMgr.h.
 { return _statusTime; }
References _statusTime.
Referenced by CalendarInvite(), CalendarMgr::SendCalendarEvent(), CalendarMgr::SendCalendarEventInvite(), CalendarMgr::SendCalendarEventStatus(), and CalendarMgr::UpdateInvite().
GetText()
std::string CalendarInvite::GetText () const inline
Definition at line 176 of file CalendarMgr.h.
 { return _text; }
References _text.
Referenced by CalendarInvite(), CalendarMgr::SendCalendarEvent(), and CalendarMgr::UpdateInvite().
SetEventId()
void CalendarInvite::SetEventId (uint64 eventId) inline
Definition at line 163 of file CalendarMgr.h.
 { _eventId = eventId; }
References _eventId.
SetInvitee()
void CalendarInvite::SetInvitee (ObjectGuid guid) inline
Definition at line 169 of file CalendarMgr.h.
 { _invitee = guid; }
References _invitee.
SetInviteId()
void CalendarInvite::SetInviteId (uint64 inviteId) inline
Definition at line 160 of file CalendarMgr.h.
 { _inviteId = inviteId; }
References _inviteId.
SetRank()
void CalendarInvite::SetRank (CalendarModerationRank rank) inline
Definition at line 181 of file CalendarMgr.h.
 { _rank = rank; }
References _rank.
SetSenderGUID()
void CalendarInvite::SetSenderGUID (ObjectGuid guid) inline
Definition at line 166 of file CalendarMgr.h.
 { _senderGUID = guid; }
References _senderGUID.
SetStatus()
void CalendarInvite::SetStatus (CalendarInviteStatus status) inline
Definition at line 178 of file CalendarMgr.h.
 { _status = status; }
References _status.
SetStatusTime()
void CalendarInvite::SetStatusTime (time_t statusTime) inline
Definition at line 172 of file CalendarMgr.h.
 { _statusTime = statusTime; }
References _statusTime.
SetText()
void CalendarInvite::SetText (const std::string & text) inline
Definition at line 175 of file CalendarMgr.h.
 { _text = text; }
References _text.
Member Data Documentation
_eventId
uint64 CalendarInvite::_eventId private
Definition at line 186 of file CalendarMgr.h.
Referenced by CalendarInvite(), GetEventId(), SetEventId(), and ~CalendarInvite().
_invitee
ObjectGuid CalendarInvite::_invitee private
Definition at line 187 of file CalendarMgr.h.
Referenced by CalendarInvite(), GetInviteeGUID(), and SetInvitee().
_inviteId
uint64 CalendarInvite::_inviteId private
Definition at line 185 of file CalendarMgr.h.
Referenced by CalendarInvite(), GetInviteId(), SetInviteId(), and ~CalendarInvite().
_rank
CalendarModerationRank CalendarInvite::_rank private
Definition at line 191 of file CalendarMgr.h.
Referenced by CalendarInvite(), GetRank(), and SetRank().
_senderGUID
ObjectGuid CalendarInvite::_senderGUID private
Definition at line 188 of file CalendarMgr.h.
Referenced by CalendarInvite(), GetSenderGUID(), and SetSenderGUID().
_status
CalendarInviteStatus CalendarInvite::_status private
Definition at line 190 of file CalendarMgr.h.
Referenced by CalendarInvite(), GetStatus(), and SetStatus().
_statusTime
time_t CalendarInvite::_statusTime private
Definition at line 189 of file CalendarMgr.h.
Referenced by CalendarInvite(), GetStatusTime(), and SetStatusTime().
_text
std::string CalendarInvite::_text private
Definition at line 192 of file CalendarMgr.h.
Referenced by CalendarInvite(), GetText(), and SetText().
The documentation for this struct was generated from the following files:
src/server/game/Calendar/CalendarMgr.h
src/server/game/Calendar/CalendarMgr.cpp