Azerotcore-wotlk: DistractMovementGenerator Class Reference
DistractMovementGenerator Class Reference
#include <IdleMovementGenerator.h>
Public Member Functions
DistractMovementGenerator (uint32 timer)
void Initialize (Unit *) override
void Finalize (Unit *) override
void Reset (Unit *owner) override
bool Update (Unit *, uint32) override
MovementGeneratorType GetMovementGeneratorType () override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual uint32 GetSplineId () const
virtual void unitSpeedChanged ()
virtual bool GetResetPosition (float &, float &, float &)
Private Attributes
uint32 m_timer
Detailed Description
Definition at line 51 of file IdleMovementGenerator.h.
Constructor & Destructor Documentation
DistractMovementGenerator()
DistractMovementGenerator::DistractMovementGenerator (uint32 timer) inline explicit
Definition at line 54 of file IdleMovementGenerator.h.
 : m_timer(timer) {}
Member Function Documentation
Finalize()
void DistractMovementGenerator::Finalize (Unit * owner) override virtual
Implements MovementGenerator.
Reimplemented in AssistanceDistractMovementGenerator.
Definition at line 90 of file IdleMovementGenerator.cpp.
 {
     owner->ClearUnitState(UNIT_STATE_DISTRACTED);
     // If this is a creature, then return orientation to original position (for idle movement creatures)
     if (owner->GetTypeId() == TYPEID_UNIT && owner->ToCreature())
     {
         float angle = owner->ToCreature()->GetHomePosition().GetOrientation();
         owner->SetFacingTo(angle);
     }
 }
References Unit::ClearUnitState(), Creature::GetHomePosition(), Object::GetTypeId(), Unit::SetFacingTo(), Object::ToCreature(), TYPEID_UNIT, and UNIT_STATE_DISTRACTED.
GetMovementGeneratorType()
MovementGeneratorType DistractMovementGenerator::GetMovementGeneratorType () inline override virtual
Implements MovementGenerator.
Reimplemented in AssistanceDistractMovementGenerator.
Definition at line 60 of file IdleMovementGenerator.h.
 { return DISTRACT_MOTION_TYPE; }
References DISTRACT_MOTION_TYPE.
Initialize()
void DistractMovementGenerator::Initialize (Unit * owner) override virtual
Implements MovementGenerator.
Definition at line 81 of file IdleMovementGenerator.cpp.
 {
     // Distracted creatures stand up if not standing
     if (!owner->IsStandState())
         owner->SetStandState(UNIT_STAND_STATE_STAND);
     owner->AddUnitState(UNIT_STATE_DISTRACTED);
 }
References Unit::AddUnitState(), Unit::IsStandState(), Unit::SetStandState(), UNIT_STAND_STATE_STAND, and UNIT_STATE_DISTRACTED.
Referenced by Reset().
Reset()
void DistractMovementGenerator::Reset (Unit * owner) inline override virtual
Implements MovementGenerator.
Definition at line 58 of file IdleMovementGenerator.h.
 { Initialize(owner); }
References Initialize().
Update()
bool DistractMovementGenerator::Update (Unit * owner, uint32 time_diff) override virtual
Implements MovementGenerator.
Definition at line 102 of file IdleMovementGenerator.cpp.
 {
     if (owner->IsInCombat() || time_diff > m_timer)
         return false;
     m_timer -= time_diff;
     return true;
 }
References Unit::IsInCombat(), and m_timer.
Member Data Documentation
m_timer
uint32 DistractMovementGenerator::m_timer private
Definition at line 63 of file IdleMovementGenerator.h.
Referenced by Update().
The documentation for this class was generated from the following files:
src/server/game/Movement/MovementGenerators/IdleMovementGenerator.h
src/server/game/Movement/MovementGenerators/IdleMovementGenerator.cpp