Azerotcore-wotlk: Acore::MostHPMissingInRange Class Reference
Acore::MostHPMissingInRange Class Reference
#include <GridNotifiers.h>
Public Member Functions
MostHPMissingInRange (Unit const *obj, float range, uint32 hp)
bool operator() (Unit *u)
Private Attributes
Unit const * i_obj
float i_range
uint32 i_hp
Detailed Description
Definition at line 740 of file GridNotifiers.h.
Constructor & Destructor Documentation
MostHPMissingInRange()
Acore::MostHPMissingInRange::MostHPMissingInRange (Unit const * obj, float range, uint32 hp) inline
Definition at line 743 of file GridNotifiers.h.
 : i_obj(obj), i_range(range), i_hp(hp) {}
Member Function Documentation
operator()()
bool Acore::MostHPMissingInRange::operator() (Unit * u) inline
Definition at line 744 of file GridNotifiers.h.
         {
             if (u->IsAlive() && u->IsInCombat() && !i_obj->IsHostileTo(u) && i_obj->IsWithinDistInMap(u, i_range) && u->GetMaxHealth() - u->GetHealth() > i_hp)
             {
                 i_hp = u->GetMaxHealth() - u->GetHealth();
                 return true;
             }
             return false;
         }
References Unit::GetHealth(), Unit::GetMaxHealth(), i_hp, i_obj, i_range, Unit::IsAlive(), Unit::IsHostileTo(), Unit::IsInCombat(), and WorldObject::IsWithinDistInMap().
Member Data Documentation
i_hp
uint32 Acore::MostHPMissingInRange::i_hp private
Definition at line 756 of file GridNotifiers.h.
Referenced by operator()().
i_obj
Unit const* Acore::MostHPMissingInRange::i_obj private
Definition at line 754 of file GridNotifiers.h.
Referenced by operator()().
i_range
float Acore::MostHPMissingInRange::i_range private
Definition at line 755 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/game/Grids/Notifiers/GridNotifiers.h