Azerotcore-wotlk: deps/mysqllite/include/internal/thr_lock.h File Reference
thr_lock.h File Reference
#include <my_pthread.h>
#include <my_list.h>
Classes
struct st_thr_lock_info
struct st_thr_lock_data
struct st_lock_list
struct st_thr_lock
Typedefs
typedef struct st_thr_lock_info THR_LOCK_INFO
typedef struct st_thr_lock_data THR_LOCK_DATA
typedef struct st_thr_lock THR_LOCK
Enumerations
enum thr_lock_type {
TL_IGNORE =-1 , TL_UNLOCK , TL_READ_DEFAULT , TL_READ ,
TL_READ_WITH_SHARED_LOCKS , TL_READ_HIGH_PRIORITY , TL_READ_NO_INSERT , TL_WRITE_ALLOW_WRITE ,
TL_WRITE_CONCURRENT_INSERT , TL_WRITE_DELAYED , TL_WRITE_DEFAULT , TL_WRITE_LOW_PRIORITY ,
TL_WRITE , TL_WRITE_ONLY
}
enum enum_thr_lock_result { THR_LOCK_SUCCESS = 0 , THR_LOCK_ABORTED = 1 , THR_LOCK_WAIT_TIMEOUT = 2 , THR_LOCK_DEADLOCK = 3 }
Functions
my_bool init_thr_lock (void)
void thr_lock_info_init (THR_LOCK_INFO *info)
void thr_lock_init (THR_LOCK *lock)
void thr_lock_delete (THR_LOCK *lock)
void thr_lock_data_init (THR_LOCK *lock, THR_LOCK_DATA *data, void *status_param)
enum enum_thr_lock_result thr_lock (THR_LOCK_DATA *data, THR_LOCK_INFO *owner, enum thr_lock_type lock_type, ulong lock_wait_timeout)
void thr_unlock (THR_LOCK_DATA *data)
enum enum_thr_lock_result thr_multi_lock (THR_LOCK_DATA **data, uint count, THR_LOCK_INFO *owner, ulong lock_wait_timeout)
void thr_multi_unlock (THR_LOCK_DATA **data, uint count)
void thr_lock_merge_status (THR_LOCK_DATA **data, uint count)
void thr_abort_locks (THR_LOCK *lock, my_bool upgrade_lock)
my_bool thr_abort_locks_for_thread (THR_LOCK *lock, my_thread_id thread)
void thr_print_locks (void)
my_bool thr_upgrade_write_delay_lock (THR_LOCK_DATA *data, enum thr_lock_type new_lock_type, ulong lock_wait_timeout)
void thr_downgrade_write_lock (THR_LOCK_DATA *data, enum thr_lock_type new_lock_type)
my_bool thr_reschedule_write_lock (THR_LOCK_DATA *data, ulong lock_wait_timeout)
void thr_set_lock_wait_callback (void(*before_wait)(void), void(*after_wait)(void))
Variables
ulong locks_immediate
ulong locks_waited
ulong max_write_lock_count
my_bool thr_lock_inited
enum thr_lock_type thr_upgraded_concurrent_insert_lock
LIST * thr_lock_thread_list
mysql_mutex_t THR_LOCK_lock
Typedef Documentation
THR_LOCK
typedef struct st_thr_lock THR_LOCK
THR_LOCK_DATA
typedef struct st_thr_lock_data THR_LOCK_DATA
THR_LOCK_INFO
typedef struct st_thr_lock_info THR_LOCK_INFO
Enumeration Type Documentation
enum_thr_lock_result
enum enum_thr_lock_result
Enumerator
THR_LOCK_SUCCESS
THR_LOCK_ABORTED
THR_LOCK_WAIT_TIMEOUT
THR_LOCK_DEADLOCK
Definition at line 75 of file thr_lock.h.
                           { THR_LOCK_SUCCESS= 0, THR_LOCK_ABORTED= 1,
                             THR_LOCK_WAIT_TIMEOUT= 2, THR_LOCK_DEADLOCK= 3 };
thr_lock_type
enum thr_lock_type
Enumerator
TL_IGNORE
TL_UNLOCK
TL_READ_DEFAULT
TL_READ
TL_READ_WITH_SHARED_LOCKS
TL_READ_HIGH_PRIORITY
TL_READ_NO_INSERT
TL_WRITE_ALLOW_WRITE
TL_WRITE_CONCURRENT_INSERT
TL_WRITE_DELAYED
TL_WRITE_DEFAULT
TL_WRITE_LOW_PRIORITY
TL_WRITE
TL_WRITE_ONLY
Definition at line 34 of file thr_lock.h.
                    { TL_IGNORE=-1,
              TL_UNLOCK,         /* UNLOCK ANY LOCK */
                      /*
                        Parser only! At open_tables() becomes TL_READ or
                        TL_READ_NO_INSERT depending on the binary log format
                        (SBR/RBR) and on the table category (log table).
                        Used for tables that are read by statements which
                        modify tables.
                      */
                      TL_READ_DEFAULT,
              TL_READ,           /* Read lock */
              TL_READ_WITH_SHARED_LOCKS,
              /* High prior. than TL_WRITE. Allow concurrent insert */
              TL_READ_HIGH_PRIORITY,
              /* READ, Don't allow concurrent insert */
              TL_READ_NO_INSERT,
              /*
             Write lock, but allow other threads to read / write.
             Used by BDB tables in MySQL to mark that someone is
             reading/writing to the table.
               */
              TL_WRITE_ALLOW_WRITE,
              /*
                WRITE lock used by concurrent insert. Will allow
                READ, if one could use concurrent insert on table.
              */
              TL_WRITE_CONCURRENT_INSERT,
              /* Write used by INSERT DELAYED.  Allows READ locks */
              TL_WRITE_DELAYED,
                      /*
                        parser only! Late bound low_priority flag.
                        At open_tables() becomes thd->update_lock_default.
                      */
                      TL_WRITE_DEFAULT,
              /* WRITE lock that has lower priority than TL_READ */
              TL_WRITE_LOW_PRIORITY,
              /* Normal WRITE lock */
              TL_WRITE,
              /* Abort new lock request with an error */
              TL_WRITE_ONLY};
Function Documentation
init_thr_lock()
my_bool init_thr_lock (void)
Definition at line 112 of file thr_lock.c.
 {
   thr_lock_inited=1;
   return 0;
 }
References thr_lock_inited.
thr_abort_locks()
void thr_abort_locks (THR_LOCK * lock, my_bool upgrade_lock)
Definition at line 1174 of file thr_lock.c.
 {
   THR_LOCK_DATA *data;
   DBUG_ENTER("thr_abort_locks");
   mysql_mutex_lock(&lock->mutex);
   for (data=lock->read_wait.data; data ; data=data->next)
   {
     data->type=TL_UNLOCK;           /* Mark killed */
     /* It's safe to signal the cond first: we're still holding the mutex. */
     mysql_cond_signal(data->cond);
     data->cond=0;               /* Removed from list */
   }
   for (data=lock->write_wait.data; data ; data=data->next)
   {
     data->type=TL_UNLOCK;
     mysql_cond_signal(data->cond);
     data->cond=0;
   }
   lock->read_wait.last= &lock->read_wait.data;
   lock->write_wait.last= &lock->write_wait.data;
   lock->read_wait.data=lock->write_wait.data=0;
   if (upgrade_lock && lock->write.data)
     lock->write.data->type=TL_WRITE_ONLY;
   mysql_mutex_unlock(&lock->mutex);
   DBUG_VOID_RETURN;
 }
References st_lock_list::data, DBUG_ENTER, DBUG_VOID_RETURN, st_lock_list::last, st_thr_lock::mutex, mysql_cond_signal, mysql_mutex_lock, mysql_mutex_unlock, st_thr_lock::read_wait, TL_UNLOCK, TL_WRITE_ONLY, st_thr_lock_data::type, st_thr_lock::write, and st_thr_lock::write_wait.
thr_abort_locks_for_thread()
my_bool thr_abort_locks_for_thread (THR_LOCK * lock, my_thread_id thread)
Definition at line 1209 of file thr_lock.c.
 {
   THR_LOCK_DATA *data;
   my_bool found= FALSE;
   DBUG_ENTER("thr_abort_locks_for_thread");
   mysql_mutex_lock(&lock->mutex);
   for (data= lock->read_wait.data; data ; data= data->next)
   {
     if (data->owner->thread_id == thread_id)    /* purecov: tested */
     {
       DBUG_PRINT("info",("Aborting read-wait lock"));
       data->type= TL_UNLOCK;            /* Mark killed */
       /* It's safe to signal the cond first: we're still holding the mutex. */
       found= TRUE;
       mysql_cond_signal(data->cond);
       data->cond= 0;                /* Removed from list */
       if (((*data->prev)= data->next))
     data->next->prev= data->prev;
       else
     lock->read_wait.last= data->prev;
     }
   }
   for (data= lock->write_wait.data; data ; data= data->next)
   {
     if (data->owner->thread_id == thread_id) /* purecov: tested */
     {
       DBUG_PRINT("info",("Aborting write-wait lock"));
       data->type= TL_UNLOCK;
       found= TRUE;
       mysql_cond_signal(data->cond);
       data->cond= 0;
       if (((*data->prev)= data->next))
     data->next->prev= data->prev;
       else
     lock->write_wait.last= data->prev;
     }
   }
   wake_up_waiters(lock);
   mysql_mutex_unlock(&lock->mutex);
   DBUG_RETURN(found);
 }
References st_lock_list::data, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, FALSE, st_lock_list::last, st_thr_lock::mutex, mysql_cond_signal, mysql_mutex_lock, mysql_mutex_unlock, st_thr_lock::read_wait, thread_id, TL_UNLOCK, TRUE, wake_up_waiters(), and st_thr_lock::write_wait.
thr_downgrade_write_lock()
void thr_downgrade_write_lock (THR_LOCK_DATA * data, enum thr_lock_type new_lock_type)
Definition at line 1282 of file thr_lock.c.
 {
   THR_LOCK *lock=in_data->lock;
 #ifndef DBUG_OFF
   enum thr_lock_type old_lock_type= in_data->type;
 #endif
   DBUG_ENTER("thr_downgrade_write_only_lock");
   mysql_mutex_lock(&lock->mutex);
   DBUG_ASSERT(old_lock_type == TL_WRITE_ONLY);
   DBUG_ASSERT(old_lock_type > new_lock_type);
   in_data->type= new_lock_type;
   check_locks(lock,"after downgrading lock",0);
   mysql_mutex_unlock(&lock->mutex);
   DBUG_VOID_RETURN;
 }
References check_locks, DBUG_ASSERT, DBUG_ENTER, DBUG_VOID_RETURN, st_thr_lock_data::lock, st_thr_lock::mutex, mysql_mutex_lock, mysql_mutex_unlock, TL_WRITE_ONLY, and st_thr_lock_data::type.
thr_lock()
enum enum_thr_lock_result thr_lock (THR_LOCK_DATA * data, THR_LOCK_INFO * owner, enum thr_lock_type lock_type, ulong lock_wait_timeout)
Definition at line 390 of file thr_lock.c.
 {
   THR_LOCK *lock=data->lock;
   enum enum_thr_lock_result result= THR_LOCK_SUCCESS;
   struct st_lock_list *wait_queue;
   DBUG_ENTER("thr_lock");
   data->next=0;
   data->cond=0;                 /* safety */
   data->type=lock_type;
   data->owner= owner;                           /* Must be reset ! */
   mysql_mutex_lock(&lock->mutex);
   DBUG_PRINT("lock",("data: 0x%lx  thread: 0x%lx  lock: 0x%lx  type: %d",
                      (long) data, data->owner->thread_id,
                      (long) lock, (int) lock_type));
   check_locks(lock,(uint) lock_type <= (uint) TL_READ_NO_INSERT ?
           "enter read_lock" : "enter write_lock",0);
   if ((int) lock_type <= (int) TL_READ_NO_INSERT)
   {
     /* Request for READ lock */
     if (lock->write.data)
     {
       /*
         We can allow a read lock even if there is already a
         write lock on the table if they are owned by the same
         thread or if they satisfy the following lock
         compatibility matrix:
            Request
           /-------
          H|++++  WRITE_ALLOW_WRITE
          e|+++-  WRITE_CONCURRENT_INSERT
          l|++++  WRITE_DELAYED
          d ||||
            |||\= READ_NO_INSERT
            ||\ = READ_HIGH_PRIORITY
            |\  = READ_WITH_SHARED_LOCKS
            \   = READ
         + = Request can be satisified.
         - = Request cannot be satisified.
         READ_NO_INSERT and WRITE_ALLOW_WRITE should in principle
         be incompatible. However this will cause starvation of
         LOCK TABLE READ in InnoDB under high write load.
         See Bug#42147 for more information.
       */
       DBUG_PRINT("lock",("write locked 1 by thread: 0x%lx",
              lock->write.data->owner->thread_id));
       if (thr_lock_owner_equal(data->owner, lock->write.data->owner) ||
       (lock->write.data->type <= TL_WRITE_DELAYED &&
        (((int) lock_type <= (int) TL_READ_HIGH_PRIORITY) ||
         (lock->write.data->type != TL_WRITE_CONCURRENT_INSERT))))
       {                     /* Already got a write lock */
     (*lock->read.last)=data;        /* Add to running FIFO */
     data->prev=lock->read.last;
     lock->read.last= &data->next;
     if (lock_type == TL_READ_NO_INSERT)
       lock->read_no_write_count++;
     check_locks(lock,"read lock with old write lock",0);
     if (lock->get_status)
       (*lock->get_status)(data->status_param, 0);
     statistic_increment(locks_immediate,&THR_LOCK_lock);
     goto end;
       }
       if (lock->write.data->type == TL_WRITE_ONLY)
       {
     /* We are not allowed to get a READ lock in this case */
     data->type=TL_UNLOCK;
         result= THR_LOCK_ABORTED;               /* Can't wait for this one */
     goto end;
       }
     }
     else if (!lock->write_wait.data ||
          lock->write_wait.data->type <= TL_WRITE_LOW_PRIORITY ||
          lock_type == TL_READ_HIGH_PRIORITY ||
          has_old_lock(lock->read.data, data->owner)) /* Has old read lock */
     {                       /* No important write-locks */
       (*lock->read.last)=data;          /* Add to running FIFO */
       data->prev=lock->read.last;
       lock->read.last= &data->next;
       if (lock->get_status)
     (*lock->get_status)(data->status_param, 0);
       if (lock_type == TL_READ_NO_INSERT)
     lock->read_no_write_count++;
       check_locks(lock,"read lock with no write locks",0);
       statistic_increment(locks_immediate,&THR_LOCK_lock);
       goto end;
     }
     /*
       We're here if there is an active write lock or no write
       lock but a high priority write waiting in the write_wait queue.
       In the latter case we should yield the lock to the writer.
     */
     wait_queue= &lock->read_wait;
   }
   else                      /* Request for WRITE lock */
   {
     if (lock_type == TL_WRITE_DELAYED)
     {
       if (lock->write.data && lock->write.data->type == TL_WRITE_ONLY)
       {
     data->type=TL_UNLOCK;
         result= THR_LOCK_ABORTED;               /* Can't wait for this one */
     goto end;
       }
       if (lock->write.data || lock->read.data)
       {
     /* Add delayed write lock to write_wait queue, and return at once */
     (*lock->write_wait.last)=data;
     data->prev=lock->write_wait.last;
     lock->write_wait.last= &data->next;
     data->cond=get_cond();
         /*
           We don't have to do get_status here as we will do it when we change
           the delayed lock to a real write lock
         */
     statistic_increment(locks_immediate,&THR_LOCK_lock);
     goto end;
       }
     }
     else if (lock_type == TL_WRITE_CONCURRENT_INSERT && ! lock->check_status)
       data->type=lock_type= thr_upgraded_concurrent_insert_lock;
     if (lock->write.data)           /* If there is a write lock */
     {
       if (lock->write.data->type == TL_WRITE_ONLY)
       {
         /* purecov: begin tested */
         /* Allow lock owner to bypass TL_WRITE_ONLY. */
         if (!thr_lock_owner_equal(data->owner, lock->write.data->owner))
         {
           /* We are not allowed to get a lock in this case */
           data->type=TL_UNLOCK;
           result= THR_LOCK_ABORTED;               /* Can't wait for this one */
           goto end;
         }
         /* purecov: end */
       }
       /*
         The idea is to allow us to get a lock at once if we already have
         a write lock or if there is no pending write locks and if all
         write locks are of TL_WRITE_ALLOW_WRITE type.
         Note that, since lock requests for the same table are sorted in
         such way that requests with higher thr_lock_type value come first
         (with one exception (*)), lock being requested usually (**) has
         equal or "weaker" type than one which thread might have already
         acquired.
         *)  The only exception to this rule is case when type of old lock
             is TL_WRITE_LOW_PRIORITY and type of new lock is changed inside
             of thr_lock() from TL_WRITE_CONCURRENT_INSERT to TL_WRITE since
             engine turns out to be not supporting concurrent inserts.
             Note that since TL_WRITE has the same compatibility rules as
             TL_WRITE_LOW_PRIORITY (their only difference is priority),
             it is OK to grant new lock without additional checks in such
             situation.
         **) The exceptions are situations when:
             - when old lock type is TL_WRITE_DELAYED
             But these should never happen within MySQL.
         Therefore it is OK to allow acquiring write lock on the table if
         this thread already holds some write lock on it.
         (INSERT INTO t1 VALUES (f1()), where f1() is stored function which
         tries to update t1, is an example of statement which requests two
         different types of write lock on the same table).
       */
       DBUG_ASSERT(! has_old_lock(lock->write.data, data->owner) ||
                   ((lock_type <= lock->write.data->type ||
                     (lock_type == TL_WRITE &&
                      lock->write.data->type == TL_WRITE_LOW_PRIORITY)) &&
                    lock->write.data->type != TL_WRITE_DELAYED));
       if ((lock_type == TL_WRITE_ALLOW_WRITE &&
            ! lock->write_wait.data &&
            lock->write.data->type == TL_WRITE_ALLOW_WRITE) ||
           has_old_lock(lock->write.data, data->owner))
       {
     /*
           We have already got a write lock or all locks are
           TL_WRITE_ALLOW_WRITE
         */
         DBUG_PRINT("info", ("write_wait.data: 0x%lx  old_type: %d",
                             (ulong) lock->write_wait.data,
                             lock->write.data->type));
     (*lock->write.last)=data;   /* Add to running fifo */
     data->prev=lock->write.last;
     lock->write.last= &data->next;
     check_locks(lock,"second write lock",0);
     if (data->lock->get_status)
       (*data->lock->get_status)(data->status_param, 0);
     statistic_increment(locks_immediate,&THR_LOCK_lock);
     goto end;
       }
       DBUG_PRINT("lock",("write locked 2 by thread: 0x%lx",
              lock->write.data->owner->thread_id));
     }
     else
     {
       DBUG_PRINT("info", ("write_wait.data: 0x%lx",
                           (ulong) lock->write_wait.data));
       if (!lock->write_wait.data)
       {                     /* no scheduled write locks */
         my_bool concurrent_insert= 0;
     if (lock_type == TL_WRITE_CONCURRENT_INSERT)
         {
           concurrent_insert= 1;
           if ((*lock->check_status)(data->status_param))
           {
             concurrent_insert= 0;
             data->type=lock_type= thr_upgraded_concurrent_insert_lock;
           }
         }
     if (!lock->read.data ||
         (lock_type <= TL_WRITE_DELAYED &&
          ((lock_type != TL_WRITE_CONCURRENT_INSERT &&
            lock_type != TL_WRITE_ALLOW_WRITE) ||
           !lock->read_no_write_count)))
     {
       (*lock->write.last)=data;     /* Add as current write lock */
       data->prev=lock->write.last;
       lock->write.last= &data->next;
       if (data->lock->get_status)
         (*data->lock->get_status)(data->status_param, concurrent_insert);
       check_locks(lock,"only write lock",0);
       statistic_increment(locks_immediate,&THR_LOCK_lock);
       goto end;
     }
       }
       DBUG_PRINT("lock",("write locked 3 by thread: 0x%lx  type: %d",
              lock->read.data->owner->thread_id, data->type));
     }
     wait_queue= &lock->write_wait;
   }
   /* Can't get lock yet;  Wait for it */
   DBUG_RETURN(wait_for_lock(wait_queue, data, 0, lock_wait_timeout));
 end:
   mysql_mutex_unlock(&lock->mutex);
   DBUG_RETURN(result);
 }
thr_lock_data_init()
void thr_lock_data_init (THR_LOCK * lock, THR_LOCK_DATA * data, void * status_param)
Definition at line 357 of file thr_lock.c.
 {
   data->lock=lock;
   data->type=TL_UNLOCK;
   data->owner= 0;                               /* no owner yet */
   data->status_param=param;
   data->cond=0;
 }
References TL_UNLOCK.
thr_lock_delete()
void thr_lock_delete (THR_LOCK * lock)
Definition at line 337 of file thr_lock.c.
 {
   DBUG_ENTER("thr_lock_delete");
   mysql_mutex_lock(&THR_LOCK_lock);
   thr_lock_thread_list=list_delete(thr_lock_thread_list,&lock->list);
   mysql_mutex_unlock(&THR_LOCK_lock);
   mysql_mutex_destroy(&lock->mutex);
   DBUG_VOID_RETURN;
 }
References DBUG_ENTER, DBUG_VOID_RETURN, st_thr_lock::list, list_delete(), st_thr_lock::mutex, mysql_mutex_destroy, mysql_mutex_lock, mysql_mutex_unlock, THR_LOCK_lock, and thr_lock_thread_list.
thr_lock_info_init()
void thr_lock_info_init (THR_LOCK_INFO * info)
Definition at line 348 of file thr_lock.c.
 {
   struct st_my_thread_var *tmp= my_thread_var;
   info->thread=    tmp->pthread_self;
   info->thread_id= tmp->id;
 }
References st_my_thread_var::id, my_thread_var, st_my_thread_var::pthread_self, st_thr_lock_info::thread, and st_thr_lock_info::thread_id.
thr_lock_init()
void thr_lock_init (THR_LOCK * lock)
Definition at line 319 of file thr_lock.c.
 {
   DBUG_ENTER("thr_lock_init");
   bzero((char*) lock,sizeof(*lock));
   mysql_mutex_init(key_THR_LOCK_mutex, &lock->mutex, MY_MUTEX_INIT_FAST);
   lock->read.last= &lock->read.data;
   lock->read_wait.last= &lock->read_wait.data;
   lock->write_wait.last= &lock->write_wait.data;
   lock->write.last= &lock->write.data;
   mysql_mutex_lock(&THR_LOCK_lock);              /* Add to locks in use */
   lock->list.data=(void*) lock;
   thr_lock_thread_list=list_add(thr_lock_thread_list,&lock->list);
   mysql_mutex_unlock(&THR_LOCK_lock);
   DBUG_VOID_RETURN;
 }
References bzero, st_lock_list::data, st_list::data, DBUG_ENTER, DBUG_VOID_RETURN, st_lock_list::last, st_thr_lock::list, list_add(), st_thr_lock::mutex, MY_MUTEX_INIT_FAST, mysql_mutex_init, mysql_mutex_lock, mysql_mutex_unlock, st_thr_lock::read, st_thr_lock::read_wait, THR_LOCK_lock, thr_lock_thread_list, st_thr_lock::write, and st_thr_lock::write_wait.
thr_lock_merge_status()
void thr_lock_merge_status (THR_LOCK_DATA ** data, uint count)
Ensure that all locks for a given table have the same status_param.
This is a MyISAM and possibly Maria specific crutch. MyISAM engine stores data file length, record count and other table properties in status_param member of handler. When a table is locked, connection-local copy is made from a global copy (myisam_share) by mi_get_status(). When a table is unlocked, the changed status is transferred back to the global share by mi_update_status().
One thing MyISAM doesn't do is to ensure that when the same table is opened twice in a connection all instances share the same status_param. This is necessary, however: for one, to keep all instances of a connection "on the same page" with regard to the current state of the table. For other, unless this is done, myisam_share will always get updated from the last unlocked instance (in mi_update_status()), and when this instance was not the one that was used to update data, records may be lost.
For each table, this function looks up the last lock_data in the list of acquired locks, and makes sure that all other instances share status_param with it.
Definition at line 1094 of file thr_lock.c.
 {
 #if !defined(DONT_USE_RW_LOCKS)
   THR_LOCK_DATA **pos= data;
   THR_LOCK_DATA **end= data + count;
   if (count > 1)
   {
     THR_LOCK_DATA *last_lock= end[-1];
     pos=end-1;
     do
     {
       pos--;
       if (last_lock->lock == (*pos)->lock &&
       last_lock->lock->copy_status)
       {
     if (last_lock->type <= TL_READ_NO_INSERT)
     {
       THR_LOCK_DATA **read_lock;
       /*
         If we are locking the same table with read locks we must ensure
         that all tables share the status of the last write lock or
         the same read lock.
       */
       for (;
            (*pos)->type <= TL_READ_NO_INSERT &&
          pos != data &&
          pos[-1]->lock == (*pos)->lock ;
            pos--) ;
       read_lock = pos+1;
       do
       {
         (last_lock->lock->copy_status)((*read_lock)->status_param,
                        (*pos)->status_param);
       } while (*(read_lock++) != last_lock);
       last_lock= (*pos);            /* Point at last write lock */
     }
     else
       (*last_lock->lock->copy_status)((*pos)->status_param,
                       last_lock->status_param);
       }
       else
     last_lock=(*pos);
     } while (pos != data);
   }
 #endif
 }
References st_thr_lock::copy_status, count(), st_lock_list::data, st_thr_lock_data::lock, pos(), st_thr_lock_data::status_param, TL_READ_NO_INSERT, and st_thr_lock_data::type.
thr_multi_lock()
enum enum_thr_lock_result thr_multi_lock (THR_LOCK_DATA ** data, uint count, THR_LOCK_INFO * owner, ulong lock_wait_timeout)
Definition at line 1016 of file thr_lock.c.
 {
   THR_LOCK_DATA **pos,**end;
   DBUG_ENTER("thr_multi_lock");
   DBUG_PRINT("lock",("data: 0x%lx  count: %d", (long) data, count));
   if (count > 1)
     sort_locks(data,count);
   /* lock everything */
   for (pos=data,end=data+count; pos < end ; pos++)
   {
     enum enum_thr_lock_result result= thr_lock(*pos, owner, (*pos)->type,
                                                lock_wait_timeout);
     if (result != THR_LOCK_SUCCESS)
     {                       /* Aborted */
       thr_multi_unlock(data,(uint) (pos-data));
       DBUG_RETURN(result);
     }
     DEBUG_SYNC_C("thr_multi_lock_after_thr_lock");
 #ifdef MAIN
     printf("Thread: %s  Got lock: 0x%lx  type: %d\n",my_thread_name(),
        (long) pos[0]->lock, pos[0]->type); fflush(stdout);
 #endif
   }
   thr_lock_merge_status(data, count);
   DBUG_RETURN(THR_LOCK_SUCCESS);
 }
thr_multi_unlock()
void thr_multi_unlock (THR_LOCK_DATA ** data, uint count)
Definition at line 1144 of file thr_lock.c.
 {
   THR_LOCK_DATA **pos,**end;
   DBUG_ENTER("thr_multi_unlock");
   DBUG_PRINT("lock",("data: 0x%lx  count: %d", (long) data, count));
   for (pos=data,end=data+count; pos < end ; pos++)
   {
 #ifdef MAIN
     printf("Thread: %s  Rel lock: 0x%lx  type: %d\n",
        my_thread_name(), (long) pos[0]->lock, pos[0]->type);
     fflush(stdout);
 #endif
     if ((*pos)->type != TL_UNLOCK)
       thr_unlock(*pos);
     else
     {
       DBUG_PRINT("lock",("Free lock: data: 0x%lx  thread: 0x%lx  lock: 0x%lx",
                          (long) *pos, (*pos)->owner->thread_id,
                          (long) (*pos)->lock));
     }
   }
   DBUG_VOID_RETURN;
 }
References count(), DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, my_thread_name(), pos(), printf(), thr_unlock(), and TL_UNLOCK.
thr_print_locks()
void thr_print_locks (void)
Definition at line 1417 of file thr_lock.c.
 {
   LIST *list;
   uint count=0;
   mysql_mutex_lock(&THR_LOCK_lock);
   puts("Current locks:");
   for (list= thr_lock_thread_list; list && count++ < MAX_THREADS;
        list= list_rest(list))
   {
     THR_LOCK *lock=(THR_LOCK*) list->data;
     mysql_mutex_lock(&lock->mutex);
     printf("lock: 0x%lx:",(ulong) lock);
     if ((lock->write_wait.data || lock->read_wait.data) &&
     (! lock->read.data && ! lock->write.data))
       printf(" WARNING: ");
     if (lock->write.data)
       printf(" write");
     if (lock->write_wait.data)
       printf(" write_wait");
     if (lock->read.data)
       printf(" read");
     if (lock->read_wait.data)
       printf(" read_wait");
     puts("");
     thr_print_lock("write",&lock->write);
     thr_print_lock("write_wait",&lock->write_wait);
     thr_print_lock("read",&lock->read);
     thr_print_lock("read_wait",&lock->read_wait);
     mysql_mutex_unlock(&lock->mutex);
     puts("");
   }
   fflush(stdout);
   mysql_mutex_unlock(&THR_LOCK_lock);
 }
References count(), st_lock_list::data, list(), list_rest, MAX_THREADS, st_thr_lock::mutex, mysql_mutex_lock, mysql_mutex_unlock, printf(), st_thr_lock::read, st_thr_lock::read_wait, THR_LOCK_lock, thr_lock_thread_list, thr_print_lock(), st_thr_lock::write, and st_thr_lock::write_wait.
thr_reschedule_write_lock()
my_bool thr_reschedule_write_lock (THR_LOCK_DATA * data, ulong lock_wait_timeout)
Definition at line 1354 of file thr_lock.c.
 {
   THR_LOCK *lock=data->lock;
   enum thr_lock_type write_lock_type;
   DBUG_ENTER("thr_reschedule_write_lock");
   mysql_mutex_lock(&lock->mutex);
   if (!lock->read_wait.data)            /* No waiting read locks */
   {
     mysql_mutex_unlock(&lock->mutex);
     DBUG_RETURN(0);
   }
   write_lock_type= data->type;
   data->type=TL_WRITE_DELAYED;
   if (lock->update_status)
     (*lock->update_status)(data->status_param);
   if (((*data->prev)=data->next))       /* remove from lock-list */
     data->next->prev= data->prev;
   else
     lock->write.last=data->prev;
   if ((data->next=lock->write_wait.data))   /* Put first in lock_list */
     data->next->prev= &data->next;
   else
     lock->write_wait.last= &data->next;
   data->prev= &lock->write_wait.data;
   data->cond=get_cond();            /* This was zero */
   lock->write_wait.data=data;
   free_all_read_locks(lock,0);
   mysql_mutex_unlock(&lock->mutex);
   DBUG_RETURN(thr_upgrade_write_delay_lock(data, write_lock_type,
                                            lock_wait_timeout));
 }
References st_lock_list::data, DBUG_ENTER, DBUG_RETURN, free_all_read_locks(), get_cond(), if(), st_lock_list::last, st_thr_lock::mutex, mysql_mutex_lock, mysql_mutex_unlock, st_thr_lock::read_wait, thr_upgrade_write_delay_lock(), TL_WRITE_DELAYED, st_thr_lock::update_status, st_thr_lock::write, and st_thr_lock::write_wait.
thr_set_lock_wait_callback()
void thr_set_lock_wait_callback (void(*)(void) before_wait, void(*)(void) after_wait)
Definition at line 96 of file thr_lock.c.
 {
   before_lock_wait= before_wait;
   after_lock_wait= after_wait;
 }
References after_lock_wait, and before_lock_wait.
thr_unlock()
void thr_unlock (THR_LOCK_DATA * data)
Definition at line 838 of file thr_lock.c.
 {
   THR_LOCK *lock=data->lock;
   enum thr_lock_type lock_type=data->type;
   DBUG_ENTER("thr_unlock");
   DBUG_PRINT("lock",("data: 0x%lx  thread: 0x%lx  lock: 0x%lx",
                      (long) data, data->owner->thread_id, (long) lock));
   mysql_mutex_lock(&lock->mutex);
   check_locks(lock,"start of release lock",0);
   if (((*data->prev)=data->next))       /* remove from lock-list */
     data->next->prev= data->prev;
   else if (lock_type <= TL_READ_NO_INSERT)
     lock->read.last=data->prev;
   else if (lock_type == TL_WRITE_DELAYED && data->cond)
   {
     /*
       This only happens in extreme circumstances when a
       write delayed lock that is waiting for a lock
     */
     lock->write_wait.last=data->prev;       /* Put it on wait queue */
   }
   else
     lock->write.last=data->prev;
   if (lock_type >= TL_WRITE_CONCURRENT_INSERT)
   {
     if (lock->update_status)
       (*lock->update_status)(data->status_param);
   }
   else
   {
     if (lock->restore_status)
       (*lock->restore_status)(data->status_param);
   }
   if (lock_type == TL_READ_NO_INSERT)
     lock->read_no_write_count--;
   data->type=TL_UNLOCK;             /* Mark unlocked */
   check_locks(lock,"after releasing lock",1);
   wake_up_waiters(lock);
   mysql_mutex_unlock(&lock->mutex);
   DBUG_VOID_RETURN;
 }
References check_locks, DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, st_lock_list::last, st_thr_lock::mutex, mysql_mutex_lock, mysql_mutex_unlock, st_thr_lock::read, st_thr_lock::read_no_write_count, st_thr_lock::restore_status, TL_READ_NO_INSERT, TL_UNLOCK, TL_WRITE_CONCURRENT_INSERT, TL_WRITE_DELAYED, st_thr_lock::update_status, wake_up_waiters(), st_thr_lock::write, and st_thr_lock::write_wait.
Referenced by thr_multi_unlock().
thr_upgrade_write_delay_lock()
my_bool thr_upgrade_write_delay_lock (THR_LOCK_DATA * data, enum thr_lock_type new_lock_type, ulong lock_wait_timeout)
Definition at line 1303 of file thr_lock.c.
 {
   THR_LOCK *lock=data->lock;
   DBUG_ENTER("thr_upgrade_write_delay_lock");
   mysql_mutex_lock(&lock->mutex);
   if (data->type == TL_UNLOCK || data->type >= TL_WRITE_LOW_PRIORITY)
   {
     mysql_mutex_unlock(&lock->mutex);
     DBUG_RETURN(data->type == TL_UNLOCK);   /* Test if Aborted */
   }
   check_locks(lock,"before upgrading lock",0);
   /* TODO:  Upgrade to TL_WRITE_CONCURRENT_INSERT in some cases */
   data->type= new_lock_type;                    /* Upgrade lock */
   /* Check if someone has given us the lock */
   if (!data->cond)
   {
     if (!lock->read.data)           /* No read locks */
     {                       /* We have the lock */
       if (data->lock->get_status)
     (*data->lock->get_status)(data->status_param, 0);
       mysql_mutex_unlock(&lock->mutex);
       DBUG_RETURN(0);
     }
     if (((*data->prev)=data->next))     /* remove from lock-list */
       data->next->prev= data->prev;
     else
       lock->write.last=data->prev;
     if ((data->next=lock->write_wait.data)) /* Put first in lock_list */
       data->next->prev= &data->next;
     else
       lock->write_wait.last= &data->next;
     data->prev= &lock->write_wait.data;
     lock->write_wait.data=data;
     check_locks(lock,"upgrading lock",0);
   }
   else
   {
     check_locks(lock,"waiting for lock",0);
   }
   DBUG_RETURN(wait_for_lock(&lock->write_wait,data,1, lock_wait_timeout));
 }
References check_locks, st_lock_list::data, DBUG_ENTER, DBUG_RETURN, st_lock_list::last, st_thr_lock::mutex, mysql_mutex_lock, mysql_mutex_unlock, st_thr_lock::read, TL_UNLOCK, TL_WRITE_LOW_PRIORITY, wait_for_lock(), st_thr_lock::write, and st_thr_lock::write_wait.
Referenced by thr_reschedule_write_lock().
Variable Documentation
locks_immediate
ulong locks_immediate extern
Definition at line 82 of file thr_lock.c.
locks_waited
ulong locks_waited
Definition at line 28 of file thr_lock.h.
max_write_lock_count
ulong max_write_lock_count extern
Definition at line 91 of file thr_lock.c.
Referenced by wake_up_waiters().
thr_lock_inited
my_bool thr_lock_inited extern
Definition at line 81 of file thr_lock.c.
Referenced by init_thr_lock().
THR_LOCK_lock
mysql_mutex_t THR_LOCK_lock extern
Definition at line 27 of file my_thr_init.c.
Referenced by thr_lock_delete(), thr_lock_init(), and thr_print_locks().
thr_lock_thread_list
LIST* thr_lock_thread_list extern
Definition at line 90 of file thr_lock.c.
Referenced by thr_lock_delete(), thr_lock_init(), and thr_print_locks().
thr_upgraded_concurrent_insert_lock
enum thr_lock_type thr_upgraded_concurrent_insert_lock extern
Definition at line 82 of file thr_lock.c.