Azerotcore-wotlk: VMAP::ModelPosition Class Reference
VMAP::ModelPosition Class Reference
#include <TileAssembler.h>
Public Member Functions
ModelPosition ()
void init ()
G3D::Vector3 transform (const G3D::Vector3 &pIn) const
void moveToBasePos (const G3D::Vector3 &pBasePos)
Public Attributes
G3D::Vector3 iPos
G3D::Vector3 iDir
float iScale {0.0f}
Private Attributes
G3D::Matrix3 iRotation
Detailed Description
This Class is used to convert raw vector data into balanced BSP-Trees. To start the conversion call convertWorld().
Definition at line 37 of file TileAssembler.h.
Constructor & Destructor Documentation
ModelPosition()
VMAP::ModelPosition::ModelPosition () inline
Definition at line 42 of file TileAssembler.h.
 { }
Member Function Documentation
init()
void VMAP::ModelPosition::init () inline
Definition at line 46 of file TileAssembler.h.
         {
             iRotation = G3D::Matrix3::fromEulerAnglesZYX(G3D::pif() * iDir.y / 180.f, G3D::pif() * iDir.x / 180.f, G3D::pif() * iDir.z / 180.f);
         }
References G3D::Matrix3::fromEulerAnglesZYX(), iDir, iRotation, G3D::pif(), G3D::Vector3::x, G3D::Vector3::y, and G3D::Vector3::z.
Referenced by VMAP::TileAssembler::calculateTransformedBound().
moveToBasePos()
void VMAP::ModelPosition::moveToBasePos (const G3D::Vector3 & pBasePos) inline
Definition at line 51 of file TileAssembler.h.
 { iPos -= pBasePos; }
References iPos.
transform()
Vector3 VMAP::ModelPosition::transform (const G3D::Vector3 & pIn) const
Definition at line 45 of file TileAssembler.cpp.
     {
         Vector3 out = pIn * iScale;
         out = iRotation * out;
         return (out);
     }
References iRotation, and iScale.
Referenced by VMAP::TileAssembler::calculateTransformedBound().
Member Data Documentation
iDir
G3D::Vector3 VMAP::ModelPosition::iDir
Definition at line 44 of file TileAssembler.h.
Referenced by VMAP::TileAssembler::calculateTransformedBound(), and init().
iPos
G3D::Vector3 VMAP::ModelPosition::iPos
Definition at line 43 of file TileAssembler.h.
Referenced by moveToBasePos().
iRotation
G3D::Matrix3 VMAP::ModelPosition::iRotation private
Definition at line 40 of file TileAssembler.h.
Referenced by init(), and transform().
iScale
float VMAP::ModelPosition::iScale {0.0f}
Definition at line 45 of file TileAssembler.h.
Referenced by VMAP::TileAssembler::calculateTransformedBound(), and transform().
The documentation for this class was generated from the following files:
src/common/Collision/Maps/TileAssembler.h
src/common/Collision/Maps/TileAssembler.cpp