Azerotcore-wotlk: event_commandscript Class Reference
event_commandscript Class Reference
Public Member Functions
event_commandscript ()
ChatCommandTable GetCommands () const override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Static Public Member Functions
static bool HandleEventActiveListCommand (ChatHandler *handler)
static bool HandleEventInfoCommand (ChatHandler *handler, EventEntry const eventId)
static bool HandleEventStartCommand (ChatHandler *handler, EventEntry const eventId)
static bool HandleEventStopCommand (ChatHandler *handler, EventEntry const eventId)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 35 of file cs_event.cpp.
Constructor & Destructor Documentation
event_commandscript()
event_commandscript::event_commandscript () inline
Definition at line 38 of file cs_event.cpp.
 : CommandScript("event_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable event_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
Definition at line 40 of file cs_event.cpp.
     {
         static ChatCommandTable eventCommandTable =
         {
             { "activelist", HandleEventActiveListCommand, SEC_GAMEMASTER, Console::Yes },
             { "start",      HandleEventStartCommand,      SEC_GAMEMASTER, Console::Yes },
             { "stop",       HandleEventStopCommand,       SEC_GAMEMASTER, Console::Yes },
             { "info",       HandleEventInfoCommand,       SEC_GAMEMASTER, Console::Yes }
         };
         static ChatCommandTable commandTable =
         {
             { "event", eventCommandTable }
         };
         return commandTable;
     }
References SEC_GAMEMASTER, and Acore::ChatCommands::Yes.
HandleEventActiveListCommand()
static bool event_commandscript::HandleEventActiveListCommand (ChatHandler * handler) inline static
Definition at line 56 of file cs_event.cpp.
     {
         uint32 counter = 0;
         GameEventMgr::GameEventDataMap const& events = sGameEventMgr->GetEventMap();
         GameEventMgr::ActiveEvents const& activeEvents = sGameEventMgr->GetActiveEventList();
         char const* active = handler->GetAcoreString(LANG_ACTIVE);
         for (uint16 eventId : activeEvents)
         {
             GameEventData const& eventData = events[eventId];
             if (handler->GetSession())
             {
                 handler->PSendSysMessage(LANG_EVENT_ENTRY_LIST_CHAT, eventId, eventId, eventData.description.c_str(), active);
             }
             else
             {
                 handler->PSendSysMessage(LANG_EVENT_ENTRY_LIST_CONSOLE, eventId, eventData.description.c_str(), active);
             }
             ++counter;
         }
         if (counter == 0)
         {
             handler->SendSysMessage(LANG_NOEVENTFOUND);
         }
         handler->SetSentErrorMessage(true);
         return true;
     }
References GameEventData::description, ChatHandler::GetAcoreString(), ChatHandler::GetSession(), LANG_ACTIVE, LANG_EVENT_ENTRY_LIST_CHAT, LANG_EVENT_ENTRY_LIST_CONSOLE, LANG_NOEVENTFOUND, ChatHandler::PSendSysMessage(), ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), and sGameEventMgr.
HandleEventInfoCommand()
static bool event_commandscript::HandleEventInfoCommand (ChatHandler * handler, EventEntry const eventId) inline static
Definition at line 91 of file cs_event.cpp.
     {
         GameEventMgr::GameEventDataMap const& events = sGameEventMgr->GetEventMap();
         if (std::size_t(eventId) >= events.size())
         {
             handler->SendSysMessage(LANG_EVENT_NOT_EXIST);
             handler->SetSentErrorMessage(true);
             return false;
         }
         GameEventData const& eventData = events[eventId];
         if (!eventData.isValid())
         {
             handler->SendSysMessage(LANG_EVENT_NOT_EXIST);
             handler->SetSentErrorMessage(true);
             return false;
         }
         GameEventMgr::ActiveEvents const& activeEvents = sGameEventMgr->GetActiveEventList();
         bool active = activeEvents.find(eventId) != activeEvents.end();
         char const* activeStr = active ? handler->GetAcoreString(LANG_ACTIVE) : "";
         std::string startTimeStr = TimeToTimestampStr(eventData.start);
         std::string endTimeStr = TimeToTimestampStr(eventData.end);
         uint32 delay = sGameEventMgr->NextCheck(eventId);
         time_t nextTime = time(nullptr) + delay;
         std::string nextStr = nextTime >= eventData.start && nextTime < eventData.end ? TimeToTimestampStr(time(nullptr) + delay) : "-";
         std::string occurenceStr = secsToTimeString(eventData.occurence * MINUTE, true);
         std::string lengthStr = secsToTimeString(eventData.length * MINUTE, true);
         handler->PSendSysMessage(LANG_EVENT_INFO, uint16(eventId), eventData.description.c_str(), activeStr,
             startTimeStr.c_str(), endTimeStr.c_str(), occurenceStr.c_str(), lengthStr.c_str(),
             nextStr.c_str());
         return true;
     }
References GameEventData::description, GameEventData::end, ChatHandler::GetAcoreString(), GameEventData::isValid(), LANG_ACTIVE, LANG_EVENT_INFO, LANG_EVENT_NOT_EXIST, GameEventData::length, MINUTE, GameEventData::occurence, ChatHandler::PSendSysMessage(), secsToTimeString(), ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), sGameEventMgr, GameEventData::start, and TimeToTimestampStr().
HandleEventStartCommand()
static bool event_commandscript::HandleEventStartCommand (ChatHandler * handler, EventEntry const eventId) inline static
Definition at line 131 of file cs_event.cpp.
     {
         GameEventMgr::GameEventDataMap const& events = sGameEventMgr->GetEventMap();
         if (*eventId < 1 || *eventId >= events.size())
         {
             handler->SendSysMessage(LANG_EVENT_NOT_EXIST);
             handler->SetSentErrorMessage(true);
             return false;
         }
         GameEventData const& eventData = events[eventId];
         if (!eventData.isValid())
         {
             handler->SendSysMessage(LANG_EVENT_NOT_EXIST);
             handler->SetSentErrorMessage(true);
             return false;
         }
         GameEventMgr::ActiveEvents const& activeEvents = sGameEventMgr->GetActiveEventList();
         if (activeEvents.find(eventId) != activeEvents.end())
         {
             handler->PSendSysMessage(LANG_EVENT_ALREADY_ACTIVE, uint16(eventId));
             handler->SetSentErrorMessage(true);
             return false;
         }
         sGameEventMgr->StartEvent(eventId, true);
         return true;
     }
References GameEventData::isValid(), LANG_EVENT_ALREADY_ACTIVE, LANG_EVENT_NOT_EXIST, ChatHandler::PSendSysMessage(), ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), and sGameEventMgr.
HandleEventStopCommand()
static bool event_commandscript::HandleEventStopCommand (ChatHandler * handler, EventEntry const eventId) inline static
Definition at line 162 of file cs_event.cpp.
     {
         GameEventMgr::GameEventDataMap const& events = sGameEventMgr->GetEventMap();
         if (*eventId < 1 || *eventId >= events.size())
         {
             handler->SendSysMessage(LANG_EVENT_NOT_EXIST);
             handler->SetSentErrorMessage(true);
             return false;
         }
         GameEventData const& eventData = events[eventId];
         if (!eventData.isValid())
         {
             handler->SendSysMessage(LANG_EVENT_NOT_EXIST);
             handler->SetSentErrorMessage(true);
             return false;
         }
         GameEventMgr::ActiveEvents const& activeEvents = sGameEventMgr->GetActiveEventList();
         if (activeEvents.find(eventId) == activeEvents.end())
         {
             handler->PSendSysMessage(LANG_EVENT_NOT_ACTIVE, uint16(eventId));
             handler->SetSentErrorMessage(true);
             return false;
         }
         sGameEventMgr->StopEvent(eventId, true);
         return true;
     }
References GameEventData::isValid(), LANG_EVENT_NOT_ACTIVE, LANG_EVENT_NOT_EXIST, ChatHandler::PSendSysMessage(), ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), and sGameEventMgr.
The documentation for this class was generated from the following file:
src/server/scripts/Commands/cs_event.cpp