Azerotcore-wotlk: Pet Class Reference
Pet Class Reference
#include <Pet.h>
Public Member Functions
Pet (Player *owner, PetType type=MAX_PET_TYPE)
~Pet () override
void AddToWorld () override
void RemoveFromWorld () override
void SetDisplayId (uint32 modelId) override
PetType getPetType () const
void setPetType (PetType type)
bool isControlled () const
bool isTemporarySummoned () const
bool IsPermanentPetFor (Player *owner) const
bool Create (ObjectGuid::LowType guidlow, Map *map, uint32 phaseMask, uint32 Entry, uint32 pet_number)
bool CreateBaseAtCreature (Creature *creature)
bool CreateBaseAtCreatureInfo (CreatureTemplate const *cinfo, Unit *owner)
bool CreateBaseAtTamed (CreatureTemplate const *cinfo, Map *map, uint32 phaseMask)
bool isBeingLoaded () const override
void SavePetToDB (PetSaveMode mode, bool logout)
void Remove (PetSaveMode mode, bool returnreagent=false)
void setDeathState (DeathState s, bool despawn=false) override
void Update (uint32 diff) override
uint8 GetPetAutoSpellSize () const override
uint32 GetPetAutoSpellOnPos (uint8 pos) const override
void LoseHappiness ()
HappinessState GetHappinessState ()
void GivePetXP (uint32 xp)
void GivePetLevel (uint8 level)
void SynchronizeLevelWithOwner ()
bool HaveInDiet (ItemTemplate const *item) const
uint32 GetCurrentFoodBenefitLevel (uint32 itemlevel) const
void SetDuration (int32 dur)
int32 GetDuration () const
void ToggleAutocast (SpellInfo const *spellInfo, bool apply)
bool HasSpell (uint32 spell) const override
void LearnPetPassives ()
void CastPetAuras (bool current)
void CastWhenWillAvailable (uint32 spellid, Unit *spellTarget, Unit *oldTarget, bool spellIsPositive=false)
void ClearCastWhenWillAvailable ()
void RemoveSpellCooldown (uint32 spell_id, bool update)
void _SaveSpellCooldowns (CharacterDatabaseTransaction trans, bool logout)
void _SaveAuras (CharacterDatabaseTransaction trans, bool logout)
void _SaveSpells (CharacterDatabaseTransaction trans)
void _LoadSpellCooldowns (PreparedQueryResult result)
void _LoadAuras (PreparedQueryResult result, uint32 timediff)
void _LoadSpells (PreparedQueryResult result)
bool addSpell (uint32 spellId, ActiveStates active=ACT_DECIDE, PetSpellState state=PETSPELL_NEW, PetSpellType type=PETSPELL_NORMAL)
bool learnSpell (uint32 spell_id)
void learnSpellHighRank (uint32 spellid)
void InitLevelupSpellsForLevel ()
bool unlearnSpell (uint32 spell_id, bool learn_prev, bool clear_ab=true)
bool removeSpell (uint32 spell_id, bool learn_prev, bool clear_ab=true)
void CleanupActionBar ()
void InitPetCreateSpells ()
bool resetTalents ()
void InitTalentForLevel ()
uint8 GetMaxTalentPointsForLevel (uint8 level)
uint8 GetFreeTalentPoints ()
void SetFreeTalentPoints (uint8 points)
uint64 GetAuraUpdateMaskForRaid () const
void SetAuraUpdateMaskForRaid (uint8 slot)
void ResetAuraUpdateMaskForRaid ()
DeclinedName const * GetDeclinedNames () const
Player * GetOwner () const
void SetLoading (bool load)
void HandleAsynchLoadSucceed ()
uint8 GetAsynchLoadType () const
void SetAsynchLoadType (uint8 type)
Public Member Functions inherited from Guardian
Guardian (SummonPropertiesEntry const *properties, ObjectGuid owner, bool isWorldObject)
void InitStats (uint32 duration) override
bool InitStatsForLevel (uint8 level)
void InitSummon () override
bool UpdateStats (Stats stat) override
bool UpdateAllStats () override
void UpdateArmor () override
void UpdateMaxHealth () override
void UpdateMaxPower (Powers power) override
void UpdateAttackPowerAndDamage (bool ranged=false) override
void UpdateDamagePhysical (WeaponAttackType attType) override
Public Member Functions inherited from Minion
Minion (SummonPropertiesEntry const *properties, ObjectGuid owner, bool isWorldObject)
Unit * GetOwner () const
float GetFollowAngle () const override
void SetFollowAngle (float angle)
bool IsPetGhoul () const
bool IsGuardianPet () const
Public Member Functions inherited from TempSummon
TempSummon (SummonPropertiesEntry const *properties, ObjectGuid owner, bool isWorldObject)
~TempSummon () override=default
virtual void UnSummon (uint32 msTime=0)
void SetTempSummonType (TempSummonType type)
WorldObject * GetSummoner () const
Unit * GetSummonerUnit () const
Creature * GetSummonerCreatureBase () const
GameObject * GetSummonerGameObject () const
ObjectGuid GetSummonerGUID ()
TempSummonType const & GetSummonType ()
uint32 GetTimer ()
void SetTimer (uint32 t)
Public Member Functions inherited from Creature
Creature (bool isWorldObject=false)
~Creature () override
void SetObjectScale (float scale) override
void DisappearAndDie ()
bool isVendorWithIconSpeak () const
bool Create (ObjectGuid::LowType guidlow, Map *map, uint32 phaseMask, uint32 Entry, uint32 vehId, float x, float y, float z, float ang, const CreatureData *data=nullptr)
bool LoadCreaturesAddon (bool reload=false)
void SelectLevel (bool changelevel=true)
void LoadEquipment (int8 id=1, bool force=false)
ObjectGuid::LowType GetSpawnId () const
void GetRespawnPosition (float &x, float &y, float &z, float *ori=nullptr, float *dist=nullptr) const
void SetCorpseDelay (uint32 delay)
uint32 GetCorpseDelay () const
bool IsRacialLeader () const
bool IsCivilian () const
bool IsTrigger () const
bool IsGuard () const
bool CanWalk () const
bool CanSwim () const override
This method check the current flag/status of a creature and its inhabit type.
bool CanEnterWater () const override
bool CanFly () const override
bool CanHover () const
void SetReactState (ReactStates st)
ReactStates GetReactState () const
bool HasReactState (ReactStates state) const
void InitializeReactState ()
bool isCanInteractWithBattleMaster (Player *player, bool msg) const
bool isCanTrainingAndResetTalentsOf (Player *player) const
bool IsValidTrainerForPlayer (Player *player, uint32 *npcFlags=nullptr) const
bool CanCreatureAttack (Unit const *victim, bool skipDistCheck=false) const
void LoadSpellTemplateImmunity ()
bool IsImmunedToSpell (SpellInfo const *spellInfo) override
bool HasMechanicTemplateImmunity (uint32 mask) const
bool IsImmunedToSpellEffect (SpellInfo const *spellInfo, uint32 index) const override
bool isElite () const
bool isWorldBoss () const
bool IsDungeonBoss () const
bool IsImmuneToKnockback () const
bool IsAvoidingAOE () const
uint8 getLevelForTarget (WorldObject const *target) const override
bool IsInEvadeMode () const
bool IsEvadingAttacks () const
bool AIM_Initialize (CreatureAI *ai=nullptr)
void Motion_Initialize ()
CreatureAI * AI () const
bool SetWalk (bool enable) override
bool SetDisableGravity (bool disable, bool packetOnly=false) override
bool SetSwim (bool enable) override
bool SetCanFly (bool enable, bool packetOnly=false) override
bool SetWaterWalking (bool enable, bool packetOnly=false) override
bool SetFeatherFall (bool enable, bool packetOnly=false) override
bool SetHover (bool enable, bool packetOnly=false) override
bool HasSpellFocus (Spell const *focusSpell=nullptr) const
uint32 GetShieldBlockValue () const override
SpellSchoolMask GetMeleeDamageSchoolMask () const override
void SetMeleeDamageSchool (SpellSchools school)
void _AddCreatureSpellCooldown (uint32 spell_id, uint16 categoryId, uint32 end_time)
void AddSpellCooldown (uint32 spell_id, uint32, uint32 end_time, bool needSendToClient=false, bool forceSendToSpectator=false) override
bool HasSpellCooldown (uint32 spell_id) const override
uint32 GetSpellCooldown (uint32 spell_id) const
void ProhibitSpellSchool (SpellSchoolMask idSchoolMask, uint32 unTimeMs) override
bool IsSpellProhibited (SpellSchoolMask idSchoolMask) const
void UpdateMovementFlags ()
bool UpdateEntry (uint32 entry, const CreatureData *data=nullptr, bool changelevel=true)
void UpdateResistances (uint32 school) override
void CalculateMinMaxDamage (WeaponAttackType attType, bool normalized, bool addTotalPct, float &minDamage, float &maxDamage) override
void SetCanDualWield (bool value) override
int8 GetOriginalEquipmentId () const
uint8 GetCurrentEquipmentId ()
void SetCurrentEquipmentId (uint8 id)
float GetSpellDamageMod (int32 Rank)
VendorItemData const * GetVendorItems () const
uint32 GetVendorItemCurrentCount (VendorItem const *vItem)
uint32 UpdateVendorItemCurrentCount (VendorItem const *vItem, uint32 used_count)
TrainerSpellData const * GetTrainerSpells () const
CreatureTemplate const * GetCreatureTemplate () const
CreatureData const * GetCreatureData () const
void SetDetectionDistance (float dist)
CreatureAddon const * GetCreatureAddon () const
std::string GetAIName () const
std::string GetScriptName () const
uint32 GetScriptId () const
std::string const & GetNameForLocaleIdx (LocaleConstant locale_idx) const override
bool LoadFromDB (ObjectGuid::LowType guid, Map *map, bool allowDuplicate=false)
bool LoadCreatureFromDB (ObjectGuid::LowType guid, Map *map, bool addToMap=true, bool gridLoad=false, bool allowDuplicate=false)
void SaveToDB ()
ObjectGuid GetLootRecipientGUID () const
Player * GetLootRecipient () const
ObjectGuid::LowType GetLootRecipientGroupGUID () const
Group * GetLootRecipientGroup () const
bool hasLootRecipient () const
bool isTappedBy (Player const *player) const
bool CanGeneratePickPocketLoot () const
void SetPickPocketLootTime ()
void ResetPickPocketLootTime ()
void SetLootRecipient (Unit *unit, bool withGroup=true)
void AllLootRemovedFromCorpse ()
uint16 GetLootMode () const
bool HasLootMode (uint16 lootMode) const
void SetLootMode (uint16 lootMode)
void AddLootMode (uint16 lootMode)
void RemoveLootMode (uint16 lootMode)
void ResetLootMode ()
SpellInfo const * reachWithSpellAttack (Unit *victim)
SpellInfo const * reachWithSpellCure (Unit *victim)
bool CanStartAttack (Unit const *u) const
float GetAggroRange (Unit const *target) const
float GetAttackDistance (Unit const *player) const
float GetDetectionRange () const
void SendAIReaction (AiReaction reactionType)
Unit * SelectNearestTarget (float dist=0, bool playerOnly=false) const
Unit * SelectNearestTargetInAttackDistance (float dist) const
void DoFleeToGetAssistance ()
void CallForHelp (float fRadius)
void CallAssistance (Unit *target=nullptr)
void SetNoCallAssistance (bool val)
void SetNoSearchAssistance (bool val)
bool HasSearchedAssistance ()
bool CanAssistTo (const Unit *u, const Unit *enemy, bool checkfaction=true) const
bool _IsTargetAcceptable (const Unit *target) const
bool CanIgnoreFeignDeath () const
bool _CanDetectFeignDeathOf (const Unit *target) const
void UpdateMoveInLineOfSightState ()
bool IsMoveInLineOfSightDisabled ()
bool IsMoveInLineOfSightStrictlyDisabled ()
MovementGeneratorType GetDefaultMovementType () const
void SetDefaultMovementType (MovementGeneratorType mgt)
void RemoveCorpse (bool setSpawnTime=true, bool skipVisibility=false)
void DespawnOrUnsummon (Milliseconds msTimeToDespawn, Seconds forcedRespawnTimer)
void DespawnOrUnsummon (uint32 msTimeToDespawn=0)
void DespawnOnEvade ()
void RespawnOnEvade ()
time_t const & GetRespawnTime () const
time_t GetRespawnTimeEx () const
void SetRespawnTime (uint32 respawn)
void Respawn (bool force=false)
void SaveRespawnTime () override
uint32 GetRespawnDelay () const
void SetRespawnDelay (uint32 delay)
float GetWanderDistance () const
void SetWanderDistance (float dist)
void SendZoneUnderAttackMessage (Player *attacker)
Send a message to LocalDefense channel for players opposition team in the zone.
void SetInCombatWithZone ()
bool hasQuest (uint32 quest_id) const override
bool hasInvolvedQuest (uint32 quest_id) const override
bool isRegeneratingHealth ()
void SetRegeneratingHealth (bool c)
void SetCannotReachTarget (bool cannotReach)
bool CanNotReachTarget () const
bool IsNotReachable () const
bool IsNotReachableAndNeedRegen () const
void SetPosition (float x, float y, float z, float o)
void SetPosition (const Position &pos)
void SetHomePosition (float x, float y, float z, float o)
void SetHomePosition (const Position &pos)
void GetHomePosition (float &x, float &y, float &z, float &ori) const
Position const & GetHomePosition () const
void SetTransportHomePosition (float x, float y, float z, float o)
void SetTransportHomePosition (const Position &pos)
void GetTransportHomePosition (float &x, float &y, float &z, float &ori) const
Position const & GetTransportHomePosition () const
uint32 GetWaypointPath () const
void LoadPath (uint32 pathid)
uint32 GetCurrentWaypointID () const
void UpdateWaypointID (uint32 wpID)
void SearchFormation ()
CreatureGroup const * GetFormation () const
CreatureGroup * GetFormation ()
void SetFormation (CreatureGroup *formation)
Unit * SelectVictim ()
void SetDisableReputationGain (bool disable)
bool IsReputationGainDisabled () const
bool IsDamageEnoughForLootingAndReward () const
void LowerPlayerDamageReq (uint32 unDamage)
void ResetPlayerDamageReq ()
uint32 GetOriginalEntry () const
void SetOriginalEntry (uint32 entry)
void SetTarget (ObjectGuid guid=ObjectGuid::Empty) override
void FocusTarget (Spell const *focusSpell, WorldObject const *target)
void ReleaseFocus (Spell const *focusSpell)
bool IsMovementPreventedByCasting () const override
time_t GetLastDamagedTime () const
std::shared_ptr< time_t > const & GetLastDamagedTimePtr () const
void SetLastDamagedTime (time_t val)
void SetLastDamagedTimePtr (std::shared_ptr< time_t > const &val)
bool IsFreeToMove ()
bool HasSwimmingFlagOutOfCombat () const
void RefreshSwimmingFlag (bool recheck=false)
void SetAssistanceTimer (uint32 value)
Public Member Functions inherited from Unit
~Unit () override
UnitAI * GetAI ()
void SetAI (UnitAI *newAI)
void AddToWorld () override
void RemoveFromWorld () override
void CleanupBeforeRemoveFromMap (bool finalCleanup)
void CleanupsBeforeDelete (bool finalCleanup=true) override
DiminishingLevels GetDiminishing (DiminishingGroup group)
void IncrDiminishing (DiminishingGroup group)
float ApplyDiminishingToDuration (DiminishingGroup group, int32 &duration, Unit *caster, DiminishingLevels Level, int32 limitduration)
void ApplyDiminishingAura (DiminishingGroup group, bool apply)
void ClearDiminishings ()
float GetSpellMaxRangeForTarget (Unit const *target, SpellInfo const *spellInfo) const
float GetSpellMinRangeForTarget (Unit const *target, SpellInfo const *spellInfo) const
void Update (uint32 time) override
void setAttackTimer (WeaponAttackType type, int32 time)
void resetAttackTimer (WeaponAttackType type=BASE_ATTACK)
int32 getAttackTimer (WeaponAttackType type) const
bool isAttackReady (WeaponAttackType type=BASE_ATTACK) const
bool haveOffhandWeapon () const
bool CanDualWield () const
float GetCombatReach () const override
float GetMeleeReach () const
bool IsWithinRange (Unit const *obj, float dist) const
bool IsWithinCombatRange (const Unit *obj, float dist2compare) const
bool IsWithinMeleeRange (const Unit *obj, float dist=0.f) const
float GetMeleeRange (Unit const *target) const
bool GetRandomContactPoint (const Unit *target, float &x, float &y, float &z, bool force=false) const
void _addAttacker (Unit *pAttacker)
void _removeAttacker (Unit *pAttacker)
Unit * getAttackerForHelper () const
bool Attack (Unit *victim, bool meleeAttack)
void CastStop (uint32 except_spellid=0, bool withInstant=true)
bool AttackStop ()
void RemoveAllAttackers ()
AttackerSet const & getAttackers () const
bool GetMeleeAttackPoint (Unit *attacker, Position &pos)
bool isAttackingPlayer () const
Unit * GetVictim () const
void CombatStop (bool includingCast=false)
void CombatStopWithPets (bool includingCast=false)
void StopAttackFaction (uint32 faction_id)
Unit * SelectNearbyTarget (Unit *exclude=nullptr, float dist=NOMINAL_MELEE_RANGE) const
Unit * SelectNearbyNoTotemTarget (Unit *exclude=nullptr, float dist=NOMINAL_MELEE_RANGE) const
void SendMeleeAttackStop (Unit *victim=nullptr)
void SendMeleeAttackStart (Unit *victim, Player *sendTo=nullptr)
void AddUnitState (uint32 f)
bool HasUnitState (const uint32 f) const
void ClearUnitState (uint32 f)
uint32 GetUnitState () const
bool CanFreeMove () const
uint32 HasUnitTypeMask (uint32 mask) const
void AddUnitTypeMask (uint32 mask)
uint32 GetUnitTypeMask () const
bool IsSummon () const
bool IsGuardian () const
bool IsControllableGuardian () const
bool IsPet () const
bool IsHunterPet () const
bool IsTotem () const
bool IsVehicle () const
uint8 getLevel () const
uint8 getLevelForTarget (WorldObject const *) const override
void SetLevel (uint8 lvl, bool showLevelChange=true)
uint8 getRace (bool original=false) const
void setRace (uint8 race)
uint32 getRaceMask () const
uint8 getClass () const
uint32 getClassMask () const
uint8 getGender () const
float GetStat (Stats stat) const
void SetStat (Stats stat, int32 val)
uint32 GetArmor () const
void SetArmor (int32 val)
uint32 GetResistance (SpellSchools school) const
uint32 GetResistance (SpellSchoolMask mask) const
void SetResistance (SpellSchools school, int32 val)
uint32 GetHealth () const
uint32 GetMaxHealth () const
bool IsFullHealth () const
bool HealthBelowPct (int32 pct) const
bool HealthBelowPctDamaged (int32 pct, uint32 damage) const
bool HealthAbovePct (int32 pct) const
bool HealthAbovePctHealed (int32 pct, uint32 heal) const
float GetHealthPct () const
uint32 CountPctFromMaxHealth (int32 pct) const
uint32 CountPctFromCurHealth (int32 pct) const
float GetPowerPct (Powers power) const
void SetHealth (uint32 val)
void SetMaxHealth (uint32 val)
void SetFullHealth ()
int32 ModifyHealth (int32 val)
int32 GetHealthGain (int32 dVal)
Powers getPowerType () const
void setPowerType (Powers power)
uint32 GetPower (Powers power) const
uint32 GetMaxPower (Powers power) const
void SetPower (Powers power, uint32 val)
void SetMaxPower (Powers power, uint32 val)
int32 ModifyPower (Powers power, int32 val)
int32 ModifyPowerPct (Powers power, float pct, bool apply=true)
uint32 GetAttackTime (WeaponAttackType att) const
void SetAttackTime (WeaponAttackType att, uint32 val)
void ApplyAttackTimePercentMod (WeaponAttackType att, float val, bool apply)
void ApplyCastTimePercentMod (float val, bool apply)
SheathState GetSheath () const
virtual void SetSheath (SheathState sheathed)
uint32 GetFaction () const
void SetFaction (uint32 faction)
FactionTemplateEntry const * GetFactionTemplateEntry () const
ReputationRank GetReactionTo (Unit const *target) const
ReputationRank GetFactionReactionTo (FactionTemplateEntry const *factionTemplateEntry, Unit const *target) const
bool IsHostileTo (Unit const *unit) const
bool IsHostileToPlayers () const
bool IsFriendlyTo (Unit const *unit) const
bool IsNeutralToAll () const
bool IsInPartyWith (Unit const *unit) const
bool IsInRaidWith (Unit const *unit) const
void GetPartyMembers (std::list< Unit * > &units)
bool IsContestedGuard () const
bool IsInSanctuary () const
bool IsPvP () const
bool IsFFAPvP () const
void SetPvP (bool state)
uint32 GetCreatureType () const
uint32 GetCreatureTypeMask () const
uint8 getStandState () const
bool IsSitState () const
bool IsStandState () const
void SetStandState (uint8 state)
void SetStandFlags (uint8 flags)
void RemoveStandFlags (uint8 flags)
bool IsMounted () const
uint32 GetMountID () const
void Mount (uint32 mount, uint32 vehicleId=0, uint32 creatureEntry=0)
void Dismount ()
uint16 GetMaxSkillValueForLevel (Unit const *target=nullptr) const
void ProcDamageAndSpell (Unit *victim, uint32 procAttacker, uint32 procVictim, uint32 procEx, uint32 amount, WeaponAttackType attType=BASE_ATTACK, SpellInfo const *procSpellInfo=nullptr, SpellInfo const *procAura=nullptr, int8 procAuraEffectIndex=-1, Spell const *procSpell=nullptr, DamageInfo *damageInfo=nullptr, HealInfo *healInfo=nullptr)
void ProcDamageAndSpellFor (bool isVictim, Unit *target, uint32 procFlag, uint32 procExtra, WeaponAttackType attType, SpellInfo const *procSpellInfo, uint32 damage, SpellInfo const *procAura=nullptr, int8 procAuraEffectIndex=-1, Spell const *procSpell=nullptr, DamageInfo *damageInfo=nullptr, HealInfo *healInfo=nullptr)
void GetProcAurasTriggeredOnEvent (std::list< AuraApplication * > &aurasTriggeringProc, std::list< AuraApplication * > *procAuras, ProcEventInfo eventInfo)
void TriggerAurasProcOnEvent (CalcDamageInfo &damageInfo)
void TriggerAurasProcOnEvent (std::list< AuraApplication * > *myProcAuras, std::list< AuraApplication * > *targetProcAuras, Unit *actionTarget, uint32 typeMaskActor, uint32 typeMaskActionTarget, uint32 spellTypeMask, uint32 spellPhaseMask, uint32 hitMask, Spell *spell, DamageInfo *damageInfo, HealInfo *healInfo)
void TriggerAurasProcOnEvent (ProcEventInfo &eventInfo, std::list< AuraApplication * > &procAuras)
void HandleEmoteCommand (uint32 anim_id)
void AttackerStateUpdate (Unit *victim, WeaponAttackType attType=BASE_ATTACK, bool extra=false)
void CalculateMeleeDamage (Unit *victim, uint32 damage, CalcDamageInfo *damageInfo, WeaponAttackType attackType=BASE_ATTACK, const bool sittingVictim=false)
void DealMeleeDamage (CalcDamageInfo *damageInfo, bool durabilityLoss)
void HandleProcExtraAttackFor (Unit *victim)
void CalculateSpellDamageTaken (SpellNonMeleeDamage *damageInfo, int32 damage, SpellInfo const *spellInfo, WeaponAttackType attackType=BASE_ATTACK, bool crit=false)
void DealSpellDamage (SpellNonMeleeDamage *damageInfo, bool durabilityLoss)
float GetMeleeCritChanceReduction () const
float GetRangedCritChanceReduction () const
float GetSpellCritChanceReduction () const
uint32 GetMeleeCritDamageReduction (uint32 damage) const
uint32 GetRangedCritDamageReduction (uint32 damage) const
uint32 GetSpellCritDamageReduction (uint32 damage) const
uint32 GetMeleeDamageReduction (uint32 damage) const
uint32 GetRangedDamageReduction (uint32 damage) const
uint32 GetSpellDamageReduction (uint32 damage) const
float MeleeSpellMissChance (const Unit *victim, WeaponAttackType attType, int32 skillDiff, uint32 spellId) const
SpellMissInfo MeleeSpellHitResult (Unit *victim, SpellInfo const *spell)
SpellMissInfo MagicSpellHitResult (Unit *victim, SpellInfo const *spell)
SpellMissInfo SpellHitResult (Unit *victim, SpellInfo const *spell, bool canReflect=false)
float GetUnitDodgeChance () const
float GetUnitParryChance () const
float GetUnitBlockChance () const
float GetUnitMissChance (WeaponAttackType attType) const
float GetUnitCriticalChance (WeaponAttackType attackType, const Unit *victim) const
int32 GetMechanicResistChance (const SpellInfo *spell)
bool CanUseAttackType (uint8 attacktype) const
uint32 GetShieldBlockValue (uint32 soft_cap, uint32 hard_cap) const
uint32 GetUnitMeleeSkill (Unit const *target=nullptr) const
uint32 GetDefenseSkillValue (Unit const *target=nullptr) const
uint32 GetWeaponSkillValue (WeaponAttackType attType, Unit const *target=nullptr) const
float GetWeaponProcChance () const
float GetPPMProcChance (uint32 WeaponSpeed, float PPM, const SpellInfo *spellProto) const
MeleeHitOutcome RollMeleeOutcomeAgainst (const Unit *victim, WeaponAttackType attType) const
MeleeHitOutcome RollMeleeOutcomeAgainst (const Unit *victim, WeaponAttackType attType, int32 crit_chance, int32 miss_chance, int32 dodge_chance, int32 parry_chance, int32 block_chance) const
bool IsVendor () const
bool IsTrainer () const
bool IsQuestGiver () const
bool IsGossip () const
bool IsTaxi () const
bool IsGuildMaster () const
bool IsBattleMaster () const
bool IsBanker () const
bool IsInnkeeper () const
bool IsSpiritHealer () const
bool IsSpiritGuide () const
bool IsTabardDesigner () const
bool IsAuctioner () const
bool IsArmorer () const
bool IsServiceProvider () const
bool IsSpiritService () const
bool IsCritter () const
bool IsInFlight () const
bool IsInCombat () const
bool IsInCombatWith (Unit const *who) const
bool IsPetInCombat () const
void CombatStart (Unit *target, bool initialAggro=true)
void CombatStartOnCast (Unit *target, bool initialAggro=true, uint32 duration=0)
void SetInCombatState (bool PvP, Unit *enemy=nullptr, uint32 duration=0)
void SetInCombatWith (Unit *enemy, uint32 duration=0)
void ClearInCombat ()
void ClearInPetCombat ()
uint32 GetCombatTimer () const
bool HasAuraTypeWithFamilyFlags (AuraType auraType, uint32 familyName, uint32 familyFlags) const
bool HasBreakableByDamageAuraType (AuraType type, uint32 excludeAura=0) const
bool HasBreakableByDamageCrowdControlAura (Unit *excludeCasterChannel=nullptr) const
bool HasStealthAura () const
bool HasInvisibilityAura () const
bool isFeared () const
bool isInRoots () const
bool IsPolymorphed () const
bool isFrozen () const
bool isTargetableForAttack (bool checkFakeDeath=true, Unit const *byWho=nullptr) const
bool IsValidAttackTarget (Unit const *target) const
bool _IsValidAttackTarget (Unit const *target, SpellInfo const *bySpell, WorldObject const *obj=nullptr) const
bool IsValidAssistTarget (Unit const *target) const
bool _IsValidAssistTarget (Unit const *target, SpellInfo const *bySpell) const
virtual bool IsInWater () const
virtual bool IsUnderWater () const
bool isInAccessiblePlaceFor (Creature const *c) const
void SendHealSpellLog (Unit *victim, uint32 SpellID, uint32 Damage, uint32 OverHeal, uint32 Absorb, bool critical=false)
int32 HealBySpell (HealInfo &healInfo, bool critical=false)
void SendEnergizeSpellLog (Unit *victim, uint32 SpellID, uint32 Damage, Powers powertype)
void EnergizeBySpell (Unit *victim, uint32 SpellID, uint32 Damage, Powers powertype)
SpellCastResult CastSpell (SpellCastTargets const &targets, SpellInfo const *spellInfo, CustomSpellValues const *value, TriggerCastFlags triggerFlags=TRIGGERED_NONE, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastSpell (Unit *victim, uint32 spellId, bool triggered, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastSpell (Unit *victim, uint32 spellId, TriggerCastFlags triggerFlags=TRIGGERED_NONE, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastSpell (Unit *victim, SpellInfo const *spellInfo, bool triggered, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastSpell (Unit *victim, SpellInfo const *spellInfo, TriggerCastFlags triggerFlags=TRIGGERED_NONE, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastSpell (float x, float y, float z, uint32 spellId, bool triggered, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastSpell (GameObject *go, uint32 spellId, bool triggered, Item *castItem=nullptr, AuraEffect *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastCustomSpell (Unit *victim, uint32 spellId, int32 const *bp0, int32 const *bp1, int32 const *bp2, bool triggered, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastCustomSpell (uint32 spellId, SpellValueMod mod, int32 value, Unit *victim, bool triggered, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastCustomSpell (uint32 spellId, SpellValueMod mod, int32 value, Unit *victim=nullptr, TriggerCastFlags triggerFlags=TRIGGERED_NONE, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastCustomSpell (uint32 spellId, CustomSpellValues const &value, Unit *victim=nullptr, TriggerCastFlags triggerFlags=TRIGGERED_NONE, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
Aura * AddAura (uint32 spellId, Unit *target)
Aura * AddAura (SpellInfo const *spellInfo, uint8 effMask, Unit *target)
void SetAuraStack (uint32 spellId, Unit *target, uint32 stack)
void SendPlaySpellVisual (uint32 id)
void SendPlaySpellImpact (ObjectGuid guid, uint32 id)
void BuildCooldownPacket (WorldPacket &data, uint8 flags, uint32 spellId, uint32 cooldown)
void BuildCooldownPacket (WorldPacket &data, uint8 flags, PacketCooldowns const &cooldowns)
void DeMorph ()
void SendAttackStateUpdate (CalcDamageInfo *damageInfo)
void SendAttackStateUpdate (uint32 HitInfo, Unit *target, uint8 SwingType, SpellSchoolMask damageSchoolMask, uint32 Damage, uint32 AbsorbDamage, uint32 Resist, VictimState TargetState, uint32 BlockedAmount)
void SendSpellNonMeleeDamageLog (SpellNonMeleeDamage *log)
void SendSpellNonMeleeReflectLog (SpellNonMeleeDamage *log, Unit *attacker)
void SendSpellNonMeleeDamageLog (Unit *target, SpellInfo const *spellInfo, uint32 Damage, SpellSchoolMask damageSchoolMask, uint32 AbsorbedDamage, uint32 Resist, bool PhysicalDamage, uint32 Blocked, bool CriticalHit=false)
void SendPeriodicAuraLog (SpellPeriodicAuraLogInfo *pInfo)
void SendSpellMiss (Unit *target, uint32 spellID, SpellMissInfo missInfo)
void SendSpellDamageResist (Unit *target, uint32 spellId)
void SendSpellDamageImmune (Unit *target, uint32 spellId)
void NearTeleportTo (float x, float y, float z, float orientation, bool casting=false, bool vehicleTeleport=false, bool withPet=false, bool removeTransport=false)
void SendTameFailure (uint8 result)
void SendTeleportPacket (Position &pos)
virtual bool UpdatePosition (float x, float y, float z, float ang, bool teleport=false)
bool UpdatePosition (const Position &pos, bool teleport=false)
void UpdateOrientation (float orientation)
Only server-side orientation update, does not broadcast to client.
void UpdateHeight (float newZ)
Only server-side height update, does not broadcast to client.
void KnockbackFrom (float x, float y, float speedXY, float speedZ)
void JumpTo (float speedXY, float speedZ, bool forward=true)
void JumpTo (WorldObject *obj, float speedZ)
void SendMonsterMove (float NewPosX, float NewPosY, float NewPosZ, uint32 TransitTime, SplineFlags sf=SPLINEFLAG_WALK_MODE)
void MonsterMoveWithSpeed (float x, float y, float z, float speed)
void SendMovementFlagUpdate (bool self=false)
void SendMovementWaterWalking (Player *sendTo)
void SendMovementFeatherFall (Player *sendTo)
void SendMovementHover (Player *sendTo)
void SetInFront (WorldObject const *target)
void SetFacingTo (float ori)
void SetFacingToObject (WorldObject *object)
void SendChangeCurrentVictimOpcode (HostileReference *pHostileReference)
void SendClearThreatListOpcode ()
void SendRemoveFromThreatListOpcode (HostileReference *pHostileReference)
void SendThreatListUpdate ()
void SendClearTarget ()
void BuildHeartBeatMsg (WorldPacket *data) const
bool IsAlive () const
bool isDying () const
bool isDead () const
DeathState getDeathState ()
ObjectGuid GetOwnerGUID () const
void SetOwnerGUID (ObjectGuid owner)
ObjectGuid GetCreatorGUID () const
void SetCreatorGUID (ObjectGuid creator)
ObjectGuid GetMinionGUID () const
void SetMinionGUID (ObjectGuid guid)
ObjectGuid GetCharmerGUID () const
void SetCharmerGUID (ObjectGuid owner)
ObjectGuid GetCharmGUID () const
void SetPetGUID (ObjectGuid guid)
ObjectGuid GetPetGUID () const
void SetCritterGUID (ObjectGuid guid)
ObjectGuid GetCritterGUID () const
bool IsControlledByPlayer () const
bool IsCreatedByPlayer () const
ObjectGuid GetCharmerOrOwnerGUID () const
ObjectGuid GetCharmerOrOwnerOrOwnGUID () const
bool IsCharmedOwnedByPlayerOrPlayer () const
Player * GetSpellModOwner () const
Unit * GetOwner () const
Guardian * GetGuardianPet () const
Minion * GetFirstMinion () const
Unit * GetCharmer () const
Unit * GetCharm () const
Unit * GetCharmerOrOwner () const
Unit * GetCharmerOrOwnerOrSelf () const
Player * GetCharmerOrOwnerPlayerOrPlayerItself () const
Player * GetAffectingPlayer () const
void SetMinion (Minion *minion, bool apply)
void GetAllMinionsByEntry (std::list< Creature * > &Minions, uint32 entry)
void RemoveAllMinionsByEntry (uint32 entry)
void SetCharm (Unit *target, bool apply)
Unit * GetNextRandomRaidMemberOrPet (float radius)
bool SetCharmedBy (Unit *charmer, CharmType type, AuraApplication const *aurApp=nullptr)
void RemoveCharmedBy (Unit *charmer)
void RestoreFaction ()
Unit * GetFirstControlled () const
void RemoveAllControlled (bool onDeath=false)
bool IsCharmed () const
bool isPossessed () const
bool isPossessedByPlayer () const
bool isPossessing () const
bool isPossessing (Unit *u) const
CharmInfo * GetCharmInfo ()
CharmInfo * InitCharmInfo ()
void DeleteCharmInfo ()
void UpdateCharmAI ()
SharedVisionList const & GetSharedVisionList ()
void AddPlayerToVision (Player *player)
void RemovePlayerFromVision (Player *player)
bool HasSharedVision () const
void RemoveBindSightAuras ()
void RemoveCharmAuras ()
Pet * CreateTamedPetFrom (Creature *creatureTarget, uint32 spell_id=0)
Pet * CreateTamedPetFrom (uint32 creatureEntry, uint32 spell_id=0)
bool InitTamedPet (Pet *pet, uint8 level, uint32 spell_id)
Aura * _TryStackingOrRefreshingExistingAura (SpellInfo const *newAura, uint8 effMask, Unit *caster, int32 *baseAmount=nullptr, Item *castItem=nullptr, ObjectGuid casterGUID=ObjectGuid::Empty, bool periodicReset=false)
void _AddAura (UnitAura *aura, Unit *caster)
AuraApplication * _CreateAuraApplication (Aura *aura, uint8 effMask)
void _ApplyAuraEffect (Aura *aura, uint8 effIndex)
void _ApplyAura (AuraApplication *aurApp, uint8 effMask)
void _UnapplyAura (AuraApplicationMap::iterator &i, AuraRemoveMode removeMode)
void _UnapplyAura (AuraApplication *aurApp, AuraRemoveMode removeMode)
void _RemoveNoStackAuraApplicationsDueToAura (Aura *aura)
void _RemoveNoStackAurasDueToAura (Aura *aura)
bool _IsNoStackAuraDueToAura (Aura *appliedAura, Aura *existingAura) const
void _RegisterAuraEffect (AuraEffect *aurEff, bool apply)
AuraMap & GetOwnedAuras ()
AuraMap const & GetOwnedAuras () const
void RemoveOwnedAura (AuraMap::iterator &i, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
void RemoveOwnedAura (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, uint8 reqEffMask=0, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
void RemoveOwnedAura (Aura *aura, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
Aura * GetOwnedAura (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, ObjectGuid itemCasterGUID=ObjectGuid::Empty, uint8 reqEffMask=0, Aura *except=nullptr) const
AuraApplicationMap & GetAppliedAuras ()
AuraApplicationMap const & GetAppliedAuras () const
void RemoveAura (AuraApplicationMap::iterator &i, AuraRemoveMode mode=AURA_REMOVE_BY_DEFAULT)
void RemoveAura (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, uint8 reqEffMask=0, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
void RemoveAura (AuraApplication *aurApp, AuraRemoveMode mode=AURA_REMOVE_BY_DEFAULT)
void RemoveAura (Aura *aur, AuraRemoveMode mode=AURA_REMOVE_BY_DEFAULT)
void RemoveAppliedAuras (std::function< bool(AuraApplication const *)> const &check)
void RemoveOwnedAuras (std::function< bool(Aura const *)> const &check)
void RemoveAppliedAuras (uint32 spellId, std::function< bool(AuraApplication const *)> const &check)
void RemoveOwnedAuras (uint32 spellId, std::function< bool(Aura const *)> const &check)
void RemoveAurasDueToSpell (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, uint8 reqEffMask=0, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
void RemoveAuraFromStack (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
void RemoveAurasDueToSpellByDispel (uint32 spellId, uint32 dispellerSpellId, ObjectGuid casterGUID, Unit *dispeller, uint8 chargesRemoved=1)
void RemoveAurasDueToSpellBySteal (uint32 spellId, ObjectGuid casterGUID, Unit *stealer)
void RemoveAurasDueToItemSpell (uint32 spellId, ObjectGuid castItemGuid)
void RemoveAurasByType (AuraType auraType, ObjectGuid casterGUID=ObjectGuid::Empty, Aura *except=nullptr, bool negative=true, bool positive=true)
void RemoveNotOwnSingleTargetAuras ()
void RemoveAurasWithInterruptFlags (uint32 flag, uint32 except=0)
void RemoveAurasWithAttribute (uint32 flags)
void RemoveAurasWithFamily (SpellFamilyNames family, uint32 familyFlag1, uint32 familyFlag2, uint32 familyFlag3, ObjectGuid casterGUID)
void RemoveAurasWithMechanic (uint32 mechanic_mask, AuraRemoveMode removemode=AURA_REMOVE_BY_DEFAULT, uint32 except=0)
void RemoveMovementImpairingAuras (bool withRoot)
void RemoveAurasByShapeShift ()
void RemoveAreaAurasDueToLeaveWorld ()
void RemoveAllAuras ()
void RemoveArenaAuras ()
void RemoveAllAurasOnDeath ()
void RemoveAllAurasRequiringDeadTarget ()
void RemoveAllAurasExceptType (AuraType type)
void RemoveEvadeAuras ()
void DelayOwnedAuras (uint32 spellId, ObjectGuid caster, int32 delaytime)
void _RemoveAllAuraStatMods ()
void _ApplyAllAuraStatMods ()
AuraEffectList const & GetAuraEffectsByType (AuraType type) const
AuraList & GetSingleCastAuras ()
AuraList const & GetSingleCastAuras () const
AuraEffect * GetAuraEffect (uint32 spellId, uint8 effIndex, ObjectGuid casterGUID=ObjectGuid::Empty) const
AuraEffect * GetAuraEffectOfRankedSpell (uint32 spellId, uint8 effIndex, ObjectGuid casterGUID=ObjectGuid::Empty) const
AuraEffect * GetAuraEffect (AuraType type, SpellFamilyNames name, uint32 iconId, uint8 effIndex) const
AuraEffect * GetAuraEffect (AuraType type, SpellFamilyNames family, uint32 familyFlag1, uint32 familyFlag2, uint32 familyFlag3, ObjectGuid casterGUID=ObjectGuid::Empty) const
AuraEffect * GetAuraEffectDummy (uint32 spellid) const
AuraEffect * GetDummyAuraEffect (SpellFamilyNames name, uint32 iconId, uint8 effIndex) const
AuraApplication * GetAuraApplication (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, ObjectGuid itemCasterGUID=ObjectGuid::Empty, uint8 reqEffMask=0, AuraApplication *except=nullptr) const
Aura * GetAura (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, ObjectGuid itemCasterGUID=ObjectGuid::Empty, uint8 reqEffMask=0) const
AuraApplication * GetAuraApplicationOfRankedSpell (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, ObjectGuid itemCasterGUID=ObjectGuid::Empty, uint8 reqEffMask=0, AuraApplication *except=nullptr) const
Aura * GetAuraOfRankedSpell (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, ObjectGuid itemCasterGUID=ObjectGuid::Empty, uint8 reqEffMask=0) const
void GetDispellableAuraList (Unit *caster, uint32 dispelMask, DispelChargesList &dispelList)
bool HasAuraEffect (uint32 spellId, uint8 effIndex, ObjectGuid caster=ObjectGuid::Empty) const
uint32 GetAuraCount (uint32 spellId) const
bool HasAura (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, ObjectGuid itemCasterGUID=ObjectGuid::Empty, uint8 reqEffMask=0) const
bool HasAuraType (AuraType auraType) const
bool HasAuraTypeWithCaster (AuraType auratype, ObjectGuid caster) const
bool HasAuraTypeWithMiscvalue (AuraType auratype, int32 miscvalue) const
bool HasAuraTypeWithAffectMask (AuraType auratype, SpellInfo const *affectedSpell) const
bool HasAuraTypeWithValue (AuraType auratype, int32 value) const
bool HasNegativeAuraWithInterruptFlag (uint32 flag, ObjectGuid guid=ObjectGuid::Empty)
bool HasVisibleAuraType (AuraType auraType) const
bool HasNegativeAuraWithAttribute (uint32 flag, ObjectGuid guid=ObjectGuid::Empty)
bool HasAuraWithMechanic (uint32 mechanicMask) const
AuraEffect * IsScriptOverriden (SpellInfo const *spell, int32 script) const
uint32 GetDiseasesByCaster (ObjectGuid casterGUID, uint8 mode=0)
uint32 GetDoTsByCaster (ObjectGuid casterGUID) const
int32 GetTotalAuraModifierAreaExclusive (AuraType auratype) const
int32 GetTotalAuraModifier (AuraType auratype) const
float GetTotalAuraMultiplier (AuraType auratype) const
int32 GetMaxPositiveAuraModifier (AuraType auratype)
int32 GetMaxNegativeAuraModifier (AuraType auratype) const
int32 GetTotalAuraModifierByMiscMask (AuraType auratype, uint32 misc_mask) const
float GetTotalAuraMultiplierByMiscMask (AuraType auratype, uint32 misc_mask) const
int32 GetMaxPositiveAuraModifierByMiscMask (AuraType auratype, uint32 misc_mask, const AuraEffect *except=nullptr) const
int32 GetMaxNegativeAuraModifierByMiscMask (AuraType auratype, uint32 misc_mask) const
int32 GetTotalAuraModifierByMiscValue (AuraType auratype, int32 misc_value) const
float GetTotalAuraMultiplierByMiscValue (AuraType auratype, int32 misc_value) const
int32 GetMaxPositiveAuraModifierByMiscValue (AuraType auratype, int32 misc_value) const
int32 GetMaxNegativeAuraModifierByMiscValue (AuraType auratype, int32 misc_value) const
int32 GetTotalAuraModifierByAffectMask (AuraType auratype, SpellInfo const *affectedSpell) const
float GetTotalAuraMultiplierByAffectMask (AuraType auratype, SpellInfo const *affectedSpell) const
int32 GetMaxPositiveAuraModifierByAffectMask (AuraType auratype, SpellInfo const *affectedSpell) const
int32 GetMaxNegativeAuraModifierByAffectMask (AuraType auratype, SpellInfo const *affectedSpell) const
float GetResistanceBuffMods (SpellSchools school, bool positive) const
void SetResistanceBuffMods (SpellSchools school, bool positive, float val)
void ApplyResistanceBuffModsMod (SpellSchools school, bool positive, float val, bool apply)
void ApplyResistanceBuffModsPercentMod (SpellSchools school, bool positive, float val, bool apply)
void InitStatBuffMods ()
void ApplyStatBuffMod (Stats stat, float val, bool apply)
void ApplyStatPercentBuffMod (Stats stat, float val, bool apply)
void SetCreateStat (Stats stat, float val)
void SetCreateHealth (uint32 val)
uint32 GetCreateHealth () const
void SetCreateMana (uint32 val)
uint32 GetCreateMana () const
uint32 GetCreatePowers (Powers power) const
float GetPosStat (Stats stat) const
float GetNegStat (Stats stat) const
float GetCreateStat (Stats stat) const
void SetCurrentCastedSpell (Spell *pSpell)
void InterruptSpell (CurrentSpellTypes spellType, bool withDelayed=true, bool withInstant=true, bool bySelf=false)
void FinishSpell (CurrentSpellTypes spellType, bool ok=true)
bool IsNonMeleeSpellCast (bool withDelayed, bool skipChanneled=false, bool skipAutorepeat=false, bool isAutoshoot=false, bool skipInstant=true) const
void InterruptNonMeleeSpells (bool withDelayed, uint32 spellid=0, bool withInstant=true, bool bySelf=false)
bool CanMoveDuringChannel () const
Spell * GetCurrentSpell (CurrentSpellTypes spellType) const
Spell * GetCurrentSpell (uint32 spellType) const
Spell * FindCurrentSpellBySpellId (uint32 spell_id) const
int32 GetCurrentSpellCastTime (uint32 spell_id) const
ShapeshiftForm GetShapeshiftForm () const
void SetShapeshiftForm (ShapeshiftForm form)
bool IsInFeralForm () const
bool IsInDisallowedMountForm () const
bool HandleStatModifier (UnitMods unitMod, UnitModifierType modifierType, float amount, bool apply)
void SetModifierValue (UnitMods unitMod, UnitModifierType modifierType, float value)
float GetModifierValue (UnitMods unitMod, UnitModifierType modifierType) const
float GetTotalStatValue (Stats stat, float additionalValue=0.0f) const
float GetTotalAuraModValue (UnitMods unitMod) const
SpellSchools GetSpellSchoolByAuraGroup (UnitMods unitMod) const
Stats GetStatByAuraGroup (UnitMods unitMod) const
Powers GetPowerTypeByAuraGroup (UnitMods unitMod) const
bool CanModifyStats () const
void SetCanModifyStats (bool modifyStats)
virtual void UpdateAllResistances ()
float GetTotalAttackPowerValue (WeaponAttackType attType, Unit *pVictim=nullptr) const
float GetWeaponDamageRange (WeaponAttackType attType, WeaponDamageRange type) const
void SetBaseWeaponDamage (WeaponAttackType attType, WeaponDamageRange damageRange, float value)
uint32 CalculateDamage (WeaponAttackType attType, bool normalized, bool addTotalPct)
float GetAPMultiplier (WeaponAttackType attType, bool normalized)
bool isInFrontInMap (Unit const *target, float distance, float arc=M_PI) const
bool isInBackInMap (Unit const *target, float distance, float arc=M_PI) const
bool IsVisible () const
void SetVisible (bool x)
void SetModelVisible (bool on)
uint32 GetPhaseByAuras () const
void SetPhaseMask (uint32 newPhaseMask, bool update) override
void UpdateObjectVisibility (bool forced=true, bool fromUpdate=false) override
bool CanHaveThreatList () const
void AddThreat (Unit *victim, float fThreat, SpellSchoolMask schoolMask=SPELL_SCHOOL_MASK_NORMAL, SpellInfo const *threatSpell=nullptr)
float ApplyTotalThreatModifier (float fThreat, SpellSchoolMask schoolMask=SPELL_SCHOOL_MASK_NORMAL)
void DeleteThreatList ()
void TauntApply (Unit *victim)
void TauntFadeOut (Unit *taunter)
ThreatMgr & getThreatMgr ()
void addHatedBy (HostileReference *pHostileReference)
void removeHatedBy (HostileReference *)
HostileRefMgr & getHostileRefMgr ()
VisibleAuraMap const * GetVisibleAuras ()
AuraApplication * GetVisibleAura (uint8 slot)
void SetVisibleAura (uint8 slot, AuraApplication *aur)
void RemoveVisibleAura (uint8 slot)
uint32 GetInterruptMask () const
void AddInterruptMask (uint32 mask)
void UpdateInterruptMask ()
uint32 GetDisplayId ()
uint32 GetNativeDisplayId () const
void RestoreDisplayId ()
void SetNativeDisplayId (uint32 modelId)
void setTransForm (uint32 spellid)
uint32 getTransForm () const
void _RegisterDynObject (DynamicObject *dynObj)
void _UnregisterDynObject (DynamicObject *dynObj)
DynamicObject * GetDynObject (uint32 spellId)
void RemoveDynObject (uint32 spellId)
void RemoveAllDynObjects ()
GameObject * GetGameObject (uint32 spellId) const
void AddGameObject (GameObject *gameObj)
void RemoveGameObject (GameObject *gameObj, bool del)
void RemoveGameObject (uint32 spellid, bool del)
void RemoveAllGameObjects ()
void ModifyAuraState (AuraStateType flag, bool apply)
uint32 BuildAuraStateUpdateForTarget (Unit *target) const
bool HasAuraState (AuraStateType flag, SpellInfo const *spellProto=nullptr, Unit const *Caster=nullptr) const
void UnsummonAllTotems (bool onDeath=false)
Unit * GetMagicHitRedirectTarget (Unit *victim, SpellInfo const *spellInfo)
Unit * GetMeleeHitRedirectTarget (Unit *victim, SpellInfo const *spellInfo=nullptr)
int32 SpellBaseDamageBonusDone (SpellSchoolMask schoolMask)
int32 SpellBaseDamageBonusTaken (SpellSchoolMask schoolMask, bool isDoT=false)
float SpellPctDamageModsDone (Unit *victim, SpellInfo const *spellProto, DamageEffectType damagetype)
uint32 SpellDamageBonusDone (Unit *victim, SpellInfo const *spellProto, uint32 pdamage, DamageEffectType damagetype, float TotalMod=0.0f, uint32 stack=1)
uint32 SpellDamageBonusTaken (Unit *caster, SpellInfo const *spellProto, uint32 pdamage, DamageEffectType damagetype, uint32 stack=1)
int32 SpellBaseHealingBonusDone (SpellSchoolMask schoolMask)
int32 SpellBaseHealingBonusTaken (SpellSchoolMask schoolMask)
float SpellPctHealingModsDone (Unit *victim, SpellInfo const *spellProto, DamageEffectType damagetype)
uint32 SpellHealingBonusDone (Unit *victim, SpellInfo const *spellProto, uint32 healamount, DamageEffectType damagetype, float TotalMod=0.0f, uint32 stack=1)
uint32 SpellHealingBonusTaken (Unit *caster, SpellInfo const *spellProto, uint32 healamount, DamageEffectType damagetype, uint32 stack=1)
uint32 MeleeDamageBonusDone (Unit *pVictim, uint32 damage, WeaponAttackType attType, SpellInfo const *spellProto=nullptr)
uint32 MeleeDamageBonusTaken (Unit *attacker, uint32 pdamage, WeaponAttackType attType, SpellInfo const *spellProto=nullptr)
bool isSpellBlocked (Unit *victim, SpellInfo const *spellProto, WeaponAttackType attackType=BASE_ATTACK)
bool isBlockCritical ()
float SpellDoneCritChance (Unit const *, SpellInfo const *spellProto, SpellSchoolMask schoolMask, WeaponAttackType attackType, bool skipEffectCheck) const
float SpellTakenCritChance (Unit const *caster, SpellInfo const *spellProto, SpellSchoolMask schoolMask, float doneChance, WeaponAttackType attackType, bool skipEffectCheck) const
void SetLastManaUse (uint32 spellCastTime)
bool IsUnderLastManaUseEffect () const
void SetContestedPvP (Player *attackedPlayer=nullptr, bool lookForNearContestedGuards=true)
uint32 GetCastingTimeForBonus (SpellInfo const *spellProto, DamageEffectType damagetype, uint32 CastingTime) const
float CalculateDefaultCoefficient (SpellInfo const *spellInfo, DamageEffectType damagetype) const
void CastDelayedSpellWithPeriodicAmount (Unit *caster, uint32 spellId, AuraType auraType, int32 addAmount, uint8 effectIndex=0)
void ApplySpellImmune (uint32 spellId, uint32 op, uint32 type, bool apply, SpellImmuneBlockType blockType=SPELL_BLOCK_TYPE_ALL)
void ApplySpellDispelImmunity (const SpellInfo *spellProto, DispelType type, bool apply)
bool IsImmunedToDamage (SpellSchoolMask meleeSchoolMask) const
bool IsImmunedToDamage (SpellInfo const *spellInfo) const
bool IsImmunedToSchool (SpellSchoolMask meleeSchoolMask) const
bool IsImmunedToSchool (SpellInfo const *spellInfo) const
bool IsImmunedToDamageOrSchool (SpellSchoolMask meleeSchoolMask) const
bool IsImmunedToDamageOrSchool (SpellInfo const *spellInfo) const
void UpdateSpeed (UnitMoveType mtype, bool forced)
float GetSpeed (UnitMoveType mtype) const
float GetSpeedRate (UnitMoveType mtype) const
void SetSpeed (UnitMoveType mtype, float rate, bool forced=false)
void SetSpeedRate (UnitMoveType mtype, float rate)
float ApplyEffectModifiers (SpellInfo const *spellProto, uint8 effect_index, float value) const
int32 CalculateSpellDamage (Unit const *target, SpellInfo const *spellProto, uint8 effect_index, int32 const *basePoints=nullptr) const
int32 CalcSpellDuration (SpellInfo const *spellProto)
int32 ModSpellDuration (SpellInfo const *spellProto, Unit const *target, int32 duration, bool positive, uint32 effectMask)
void ModSpellCastTime (SpellInfo const *spellProto, int32 &castTime, Spell *spell=nullptr)
float CalculateLevelPenalty (SpellInfo const *spellProto) const
void addFollower (FollowerReference *pRef)
void removeFollower (FollowerReference *)
MotionMaster * GetMotionMaster ()
const MotionMaster * GetMotionMaster () const
bool IsStopped () const
void StopMoving ()
-------—End of Pet responses methods-------—
void StopMovingOnCurrentPos ()
void AddUnitMovementFlag (uint32 f)
void RemoveUnitMovementFlag (uint32 f)
bool HasUnitMovementFlag (uint32 f) const
uint32 GetUnitMovementFlags () const
void SetUnitMovementFlags (uint32 f)
void AddExtraUnitMovementFlag (uint16 f)
void RemoveExtraUnitMovementFlag (uint16 f)
uint16 HasExtraUnitMovementFlag (uint16 f) const
uint16 GetExtraUnitMovementFlags () const
void SetExtraUnitMovementFlags (uint16 f)
void SetControlled (bool apply, UnitState state)
void DisableRotate (bool apply)
void DisableSpline ()
void AddComboPointHolder (ObjectGuid lowguid)
void RemoveComboPointHolder (ObjectGuid lowguid)
void ClearComboPointHolders ()
void SendPetActionFeedback (uint8 msg)
-------—Pet responses methods--------------—
void SendPetTalk (uint32 pettalk)
void SendPetAIReaction (ObjectGuid guid)
void propagateSpeedChange ()
-------—End of Pet responses methods-------—
void ClearAllReactives ()
void StartReactiveTimer (ReactiveType reactive)
void UpdateReactives (uint32 p_time)
void UpdateAuraForGroup (uint8 slot)
bool CanProc ()
void SetCantProc (bool apply)
void AddPetAura (PetAura const *petSpell)
void RemovePetAura (PetAura const *petSpell)
void CastPetAura (PetAura const *aura)
bool IsPetAura (Aura const *aura)
uint32 GetModelForForm (ShapeshiftForm form) const
uint32 GetModelForTotem (PlayerTotemType totemType)
void SetRedirectThreat (ObjectGuid guid, uint32 pct)
void ResetRedirectThreat ()
void ModifyRedirectThreat (int32 amount)
uint32 GetRedirectThreatPercent ()
Unit * GetRedirectThreatTarget () const
bool CreateVehicleKit (uint32 id, uint32 creatureEntry)
void RemoveVehicleKit ()
Vehicle * GetVehicleKit () const
Vehicle * GetVehicle () const
bool IsOnVehicle (const Unit *vehicle) const
Unit * GetVehicleBase () const
Creature * GetVehicleCreatureBase () const
ObjectGuid GetTransGUID () const override
TransportBase * GetDirectTransport () const
Returns the transport this unit is on directly (if on vehicle and transport, return vehicle)
bool HandleSpellClick (Unit *clicker, int8 seatId=-1)
void EnterVehicle (Unit *base, int8 seatId=-1)
void EnterVehicleUnattackable (Unit *base, int8 seatId=-1)
void ExitVehicle (Position const *exitPosition=nullptr)
void ChangeSeat (int8 seatId, bool next=true)
void _ExitVehicle (Position const *exitPosition=nullptr)
void _EnterVehicle (Vehicle *vehicle, int8 seatId, AuraApplication const *aurApp=nullptr)
void BuildMovementPacket (ByteBuffer *data) const
bool IsLevitating () const
bool IsWalking () const
bool isMoving () const
bool isTurning () const
bool IsHovering () const
bool isSwimming () const
bool IsFlying () const
bool IsFalling () const
float GetHoverHeight () const
void RewardRage (uint32 damage, uint32 weaponSpeedHitFactor, bool attacker)
void OutDebugInfo () const
bool IsDuringRemoveFromWorld () const
Pet * ToPet ()
Totem * ToTotem ()
TempSummon * ToTempSummon ()
const TempSummon * ToTempSummon () const
void AddPointedBy (SafeUnitPointer *sup)
void RemovePointedBy (SafeUnitPointer *sup)
void ExecuteDelayedUnitRelocationEvent ()
void ExecuteDelayedUnitAINotifyEvent ()
virtual bool HasSpellItemCooldown (uint32, uint32) const
bool CanApplyResilience () const
void PetSpellFail (const SpellInfo *spellInfo, Unit *target, uint32 result)
int32 CalculateAOEDamageReduction (int32 damage, uint32 schoolMask, Unit *caster) const
ObjectGuid GetTarget () const
void SetInstantCast (bool set)
bool CanInstantCast () const
virtual void Talk (std::string_view text, ChatMsg msgType, Language language, float textRange, WorldObject const *target)
virtual void Say (std::string_view text, Language language, WorldObject const *target=nullptr)
virtual void Yell (std::string_view text, Language language, WorldObject const *target=nullptr)
virtual void TextEmote (std::string_view text, WorldObject const *target=nullptr, bool isBossEmote=false)
virtual void Whisper (std::string_view text, Language language, Player *target, bool isBossWhisper=false)
virtual void Talk (uint32 textId, ChatMsg msgType, float textRange, WorldObject const *target)
virtual void Say (uint32 textId, WorldObject const *target=nullptr)
virtual void Yell (uint32 textId, WorldObject const *target=nullptr)
virtual void TextEmote (uint32 textId, WorldObject const *target=nullptr, bool isBossEmote=false)
virtual void Whisper (uint32 textId, Player *target, bool isBossWhisper=false)
float GetCollisionHeight () const override
Return collision height sent to client.
float GetCollisionWidth () const override
this method gets the diameter of a Unit by DB if any value is defined, otherwise it gets the value by the DBC
float GetCollisionRadius () const override
this method gets the radius of a Unit by DB if any value is defined, otherwise it gets the value by the DBC
void ProcessPositionDataChanged (PositionFullTerrainStatus const &data) override
virtual void ProcessTerrainStatusUpdate ()
Public Member Functions inherited from WorldObject
~WorldObject () override
void _Create (ObjectGuid::LowType guidlow, HighGuid guidhigh, uint32 phaseMask)
void GetNearPoint2D (WorldObject const *searcher, float &x, float &y, float distance, float absAngle, Position const *startPos=nullptr) const
void GetNearPoint2D (float &x, float &y, float distance, float absAngle, Position const *startPos=nullptr) const
void GetNearPoint (WorldObject const *searcher, float &x, float &y, float &z, float searcher_size, float distance2d, float absAngle, float controlZ=0, Position const *startPos=nullptr) const
void GetVoidClosePoint (float &x, float &y, float &z, float size, float distance2d=0, float relAngle=0, float controlZ=0) const
bool GetClosePoint (float &x, float &y, float &z, float size, float distance2d=0, float angle=0, const WorldObject *forWho=nullptr, bool force=false) const
void MovePosition (Position &pos, float dist, float angle)
Position GetNearPosition (float dist, float angle)
void MovePositionToFirstCollision (Position &pos, float dist, float angle)
Position GetFirstCollisionPosition (float startX, float startY, float startZ, float destX, float destY)
Position GetFirstCollisionPosition (float destX, float destY, float destZ)
Position GetFirstCollisionPosition (float dist, float angle)
Position GetRandomNearPosition (float radius)
void GetContactPoint (const WorldObject *obj, float &x, float &y, float &z, float distance2d=CONTACT_DISTANCE) const
void GetChargeContactPoint (const WorldObject *obj, float &x, float &y, float &z, float distance2d=CONTACT_DISTANCE) const
float GetObjectSize () const
void UpdateGroundPositionZ (float x, float y, float &z) const
void UpdateAllowedPositionZ (float x, float y, float &z, float *groundZ=nullptr) const
void GetRandomPoint (const Position &srcPos, float distance, float &rand_x, float &rand_y, float &rand_z) const
Position GetRandomPoint (const Position &srcPos, float distance) const
uint32 GetInstanceId () const
uint32 GetPhaseMask () const
bool InSamePhase (WorldObject const *obj) const
bool InSamePhase (uint32 phasemask) const
uint32 GetZoneId () const
uint32 GetAreaId () const
void GetZoneAndAreaId (uint32 &zoneid, uint32 &areaid) const
bool IsOutdoors () const
LiquidData const & GetLiquidData () const
InstanceScript * GetInstanceScript () const
std::string const & GetName () const
void SetName (std::string const &newname)
float GetDistance (const WorldObject *obj) const
float GetDistance (const Position &pos) const
float GetDistance (float x, float y, float z) const
float GetDistance2d (const WorldObject *obj) const
float GetDistance2d (float x, float y) const
float GetDistanceZ (const WorldObject *obj) const
bool IsSelfOrInSameMap (const WorldObject *obj) const
bool IsInMap (const WorldObject *obj) const
bool IsWithinDist3d (float x, float y, float z, float dist) const
bool IsWithinDist3d (const Position *pos, float dist) const
bool IsWithinDist2d (float x, float y, float dist) const
bool IsWithinDist2d (const Position *pos, float dist) const
bool IsWithinDist (WorldObject const *obj, float dist2compare, bool is3D=true, bool useBoundingRadius=true) const
bool IsWithinDistInMap (WorldObject const *obj, float dist2compare, bool is3D=true, bool useBoundingRadius=true) const
bool IsWithinLOS (float x, float y, float z, LineOfSightChecks checks=LINEOFSIGHT_ALL_CHECKS) const
bool IsWithinLOSInMap (WorldObject const *obj, LineOfSightChecks checks=LINEOFSIGHT_ALL_CHECKS) const
Position GetHitSpherePointFor (Position const &dest) const
void GetHitSpherePointFor (Position const &dest, float &x, float &y, float &z) const
bool GetDistanceOrder (WorldObject const *obj1, WorldObject const *obj2, bool is3D=true) const
bool IsInRange (WorldObject const *obj, float minRange, float maxRange, bool is3D=true) const
bool IsInRange2d (float x, float y, float minRange, float maxRange) const
bool IsInRange3d (float x, float y, float z, float minRange, float maxRange) const
bool isInFront (WorldObject const *target, float arc=M_PI) const
bool isInBack (WorldObject const *target, float arc=M_PI) const
bool IsInBetween (const WorldObject *obj1, const WorldObject *obj2, float size=0) const
virtual void SendMessageToSet (WorldPacket *data, bool self)
virtual void SendMessageToSetInRange (WorldPacket *data, float dist, bool, bool includeMargin=false, Player const *skipped_rcvr=nullptr)
virtual void SendMessageToSet (WorldPacket *data, Player const *skipped_rcvr)
void PlayDistanceSound (uint32 sound_id, Player *target=nullptr)
void PlayDirectSound (uint32 sound_id, Player *target=nullptr)
void PlayDirectMusic (uint32 music_id, Player *target=nullptr)
void SendObjectDeSpawnAnim (ObjectGuid guid)
void AddObjectToRemoveList ()
float GetGridActivationRange () const
float GetVisibilityRange () const
virtual float GetSightRange (const WorldObject *target=nullptr) const
bool CanSeeOrDetect (WorldObject const *obj, bool ignoreStealth=false, bool distanceCheck=false, bool checkAlert=false) const
void SendPlayMusic (uint32 Music, bool OnlySelf)
virtual void SetMap (Map *map)
virtual void ResetMap ()
Map * GetMap () const
Map * FindMap () const
void SetZoneScript ()
void ClearZoneScript ()
ZoneScript * GetZoneScript () const
TempSummon * SummonCreature (uint32 id, const Position &pos, TempSummonType spwtype=TEMPSUMMON_MANUAL_DESPAWN, uint32 despwtime=0, uint32 vehId=0, SummonPropertiesEntry const *properties=nullptr) const
TempSummon * SummonCreature (uint32 id, float x, float y, float z, float ang=0, TempSummonType spwtype=TEMPSUMMON_MANUAL_DESPAWN, uint32 despwtime=0, SummonPropertiesEntry const *properties=nullptr)
GameObject * SummonGameObject (uint32 entry, float x, float y, float z, float ang, float rotation0, float rotation1, float rotation2, float rotation3, uint32 respawnTime, bool checkTransport=true)
Creature * SummonTrigger (float x, float y, float z, float ang, uint32 dur, bool setLevel=false, CreatureAI *(*GetAI)(Creature *)=nullptr)
void SummonCreatureGroup (uint8 group, std::list< TempSummon * > *list=nullptr)
Creature * FindNearestCreature (uint32 entry, float range, bool alive=true) const
GameObject * FindNearestGameObject (uint32 entry, float range, bool onlySpawned=false) const
GameObject * FindNearestGameObjectOfType (GameobjectTypes type, float range) const
Player * SelectNearestPlayer (float distance=0) const
void GetGameObjectListWithEntryInGrid (std::list< GameObject * > &lList, uint32 uiEntry, float fMaxSearchRange) const
void GetCreatureListWithEntryInGrid (std::list< Creature * > &lList, uint32 uiEntry, float fMaxSearchRange) const
void GetDeadCreatureListInGrid (std::list< Creature * > &lList, float maxSearchRange, bool alive=false) const
void DestroyForNearbyPlayers ()
void BuildUpdate (UpdateDataMapType &data_map, UpdatePlayerSet &player_set) override
void GetCreaturesWithEntryInRange (std::list< Creature * > &creatureList, float radius, uint32 entry)
void SetPositionDataUpdate ()
void UpdatePositionData ()
void AddToObjectUpdate () override
void RemoveFromObjectUpdate () override
void AddToNotify (uint16 f)
void RemoveFromNotify (uint16 f)
bool isNeedNotify (uint16 f) const
uint16 GetNotifyFlags () const
bool NotifyExecuted (uint16 f) const
void SetNotified (uint16 f)
void ResetAllNotifies ()
bool isActiveObject () const
void setActive (bool isActiveObject)
bool IsVisibilityOverridden () const
void SetVisibilityDistanceOverride (bool isVisibilityDistanceOverride)
void SetWorldObject (bool apply)
bool IsPermanentWorldObject () const
bool IsWorldObject () const
bool IsInWintergrasp () const
Transport * GetTransport () const
float GetTransOffsetX () const
float GetTransOffsetY () const
float GetTransOffsetZ () const
float GetTransOffsetO () const
uint32 GetTransTime () const
int8 GetTransSeat () const
void SetTransport (Transport *t)
virtual float GetStationaryX () const
virtual float GetStationaryY () const
virtual float GetStationaryZ () const
virtual float GetStationaryO () const
float GetMapWaterOrGroundLevel (float x, float y, float z, float *ground=nullptr) const
float GetMapHeight (float x, float y, float z, bool vmap=true, float distanceToSearch=50.0f) const
float GetFloorZ () const
float GetMinHeightInWater () const
Get the minimum height of a object that should be in water to start floating/swim.
void AddAllowedLooter (ObjectGuid guid)
void ResetAllowedLooters ()
void SetAllowedLooters (GuidUnorderedSet const looters)
bool HasAllowedLooter (ObjectGuid guid) const
GuidUnorderedSet const & GetAllowedLooters () const
Public Member Functions inherited from Object
virtual ~Object ()
bool IsInWorld () const
ObjectGuid GetGUID () const
PackedGuid const & GetPackGUID () const
uint32 GetEntry () const
void SetEntry (uint32 entry)
float GetObjectScale () const
TypeID GetTypeId () const
bool isType (uint16 mask) const
virtual void BuildCreateUpdateBlockForPlayer (UpdateData *data, Player *target) const
void SendUpdateToPlayer (Player *player)
void BuildValuesUpdateBlockForPlayer (UpdateData *data, Player *target) const
void BuildOutOfRangeUpdateBlock (UpdateData *data) const
void BuildMovementUpdateBlock (UpdateData *data, uint32 flags=0) const
virtual void DestroyForPlayer (Player *target, bool onDeath=false) const
int32 GetInt32Value (uint16 index) const
uint32 GetUInt32Value (uint16 index) const
uint64 GetUInt64Value (uint16 index) const
float GetFloatValue (uint16 index) const
uint8 GetByteValue (uint16 index, uint8 offset) const
uint16 GetUInt16Value (uint16 index, uint8 offset) const
ObjectGuid GetGuidValue (uint16 index) const
void SetInt32Value (uint16 index, int32 value)
void SetUInt32Value (uint16 index, uint32 value)
void UpdateUInt32Value (uint16 index, uint32 value)
void SetUInt64Value (uint16 index, uint64 value)
void SetFloatValue (uint16 index, float value)
void SetByteValue (uint16 index, uint8 offset, uint8 value)
void SetUInt16Value (uint16 index, uint8 offset, uint16 value)
void SetInt16Value (uint16 index, uint8 offset, int16 value)
void SetGuidValue (uint16 index, ObjectGuid value)
void SetStatFloatValue (uint16 index, float value)
void SetStatInt32Value (uint16 index, int32 value)
bool AddGuidValue (uint16 index, ObjectGuid value)
bool RemoveGuidValue (uint16 index, ObjectGuid value)
void ApplyModUInt32Value (uint16 index, int32 val, bool apply)
void ApplyModInt32Value (uint16 index, int32 val, bool apply)
void ApplyModUInt64Value (uint16 index, int32 val, bool apply)
void ApplyModPositiveFloatValue (uint16 index, float val, bool apply)
void ApplyModSignedFloatValue (uint16 index, float val, bool apply)
void ApplyPercentModFloatValue (uint16 index, float val, bool apply)
void SetFlag (uint16 index, uint32 newFlag)
void RemoveFlag (uint16 index, uint32 oldFlag)
void ToggleFlag (uint16 index, uint32 flag)
bool HasFlag (uint16 index, uint32 flag) const
void ApplyModFlag (uint16 index, uint32 flag, bool apply)
void SetByteFlag (uint16 index, uint8 offset, uint8 newFlag)
void RemoveByteFlag (uint16 index, uint8 offset, uint8 newFlag)
bool HasByteFlag (uint16 index, uint8 offset, uint8 flag) const
void SetFlag64 (uint16 index, uint64 newFlag)
void RemoveFlag64 (uint16 index, uint64 oldFlag)
void ToggleFlag64 (uint16 index, uint64 flag)
bool HasFlag64 (uint16 index, uint64 flag) const
void ApplyModFlag64 (uint16 index, uint64 flag, bool apply)
void ClearUpdateMask (bool remove)
uint16 GetValuesCount () const
void BuildFieldsUpdate (Player *, UpdateDataMapType &) const
void SetFieldNotifyFlag (uint16 flag)
void RemoveFieldNotifyFlag (uint16 flag)
void ForceValuesUpdateAtIndex (uint32)
bool IsPlayer () const
Player * ToPlayer ()
Player const * ToPlayer () const
Creature * ToCreature ()
Creature const * ToCreature () const
Unit * ToUnit ()
Unit const * ToUnit () const
GameObject * ToGameObject ()
GameObject const * ToGameObject () const
Corpse * ToCorpse ()
Corpse const * ToCorpse () const
DynamicObject * ToDynObject ()
DynamicObject const * ToDynObject () const
Public Member Functions inherited from WorldLocation
WorldLocation (uint32 _mapId=MAPID_INVALID, float x=0.f, float y=0.f, float z=0.f, float o=0.f)
WorldLocation (uint32 mapId, Position const &position)
void WorldRelocate (const WorldLocation &loc)
void WorldRelocate (uint32 mapId=MAPID_INVALID, float x=0.f, float y=0.f, float z=0.f, float o=0.f)
void SetMapId (uint32 mapId)
uint32 GetMapId () const
void GetWorldLocation (uint32 &mapId, float &x, float &y) const
void GetWorldLocation (uint32 &mapId, float &x, float &y, float &z) const
void GetWorldLocation (uint32 &mapId, float &x, float &y, float &z, float &o) const
void GetWorldLocation (WorldLocation *location) const
WorldLocation GetWorldLocation () const
Public Member Functions inherited from Position
Position (float x=0, float y=0, float z=0, float o=0)
Position (Position const &loc)
bool operator== (Position const &a) const
bool operator!= (Position const &a)
operator G3D::Vector3 () const
void Relocate (float x, float y)
void Relocate (float x, float y, float z)
void Relocate (float x, float y, float z, float orientation)
void Relocate (const Position &pos)
void Relocate (const Position *pos)
void RelocatePolarOffset (float angle, float dist, float z=0.0f)
void RelocateOffset (const Position &offset)
void SetOrientation (float orientation)
float GetPositionX () const
float GetPositionY () const
float GetPositionZ () const
float GetOrientation () const
void GetPosition (float &x, float &y) const
void GetPosition (float &x, float &y, float &z) const
void GetPosition (float &x, float &y, float &z, float &o) const
Position GetPosition () const
Position::PositionXYZStreamer PositionXYZStream ()
Position::PositionXYZOStreamer PositionXYZOStream ()
bool IsPositionValid () const
float GetExactDist2dSq (const float x, const float y) const
float GetExactDist2dSq (Position const &pos) const
float GetExactDist2dSq (Position const *pos) const
float GetExactDist2d (const float x, const float y) const
float GetExactDist2d (Position const &pos) const
float GetExactDist2d (Position const *pos) const
float GetExactDistSq (float x, float y, float z) const
float GetExactDistSq (Position const &pos) const
float GetExactDistSq (Position const *pos) const
float GetExactDist (float x, float y, float z) const
float GetExactDist (Position const &pos) const
float GetExactDist (Position const *pos) const
void GetPositionOffsetTo (const Position &endPos, Position &retOffset) const
Position GetPositionWithOffset (Position const &offset) const
float GetAngle (const Position *pos) const
float GetAngle (float x, float y) const
float GetAbsoluteAngle (float x, float y) const
float GetAbsoluteAngle (Position const &pos) const
float GetAbsoluteAngle (Position const *pos) const
float GetRelativeAngle (const Position *pos) const
float GetRelativeAngle (float x, float y) const
float ToAbsoluteAngle (float relAngle) const
void GetSinCos (float x, float y, float &vsin, float &vcos) const
bool IsInDist2d (float x, float y, float dist) const
bool IsInDist2d (const Position *pos, float dist) const
bool IsInDist (float x, float y, float z, float dist) const
bool IsInDist (const Position *pos, float dist) const
bool IsWithinBox (const Position &center, float xradius, float yradius, float zradius) const
bool HasInArc (float arcangle, const Position *pos, float targetRadius=0.0f) const
bool HasInLine (WorldObject const *target, float width) const
std::string ToString () const
Public Member Functions inherited from GridObject< Creature >
bool IsInGrid () const
void AddToGrid (GridRefMgr< Creature > &m)
void RemoveFromGrid ()
Static Public Member Functions
static SpellCastResult TryLoadFromDB (Player *owner, bool current=false, PetType mandatoryPetType=MAX_PET_TYPE, bool checkDead=false)
static bool LoadPetFromDB (Player *owner, uint8 asynchLoadType, uint32 petentry=0, uint32 petnumber=0, bool current=false, AsynchPetSummon *info=nullptr)
static void DeleteFromDB (ObjectGuid::LowType guidlow)
static void resetTalentsForAllPetsOf (Player *owner, Pet *online_pet=nullptr)
static void HandleAsynchLoadFailed (AsynchPetSummon *info, Player *player, uint8 asynchLoadType, uint8 loadResult)
Static Public Member Functions inherited from Creature
static float _GetDamageMod (int32 Rank)
Static Public Member Functions inherited from Unit
static float GetEffectiveResistChance (Unit const *owner, SpellSchoolMask schoolMask, Unit const *victim, SpellInfo const *spellInfo=nullptr)
static void DealDamageMods (Unit const *victim, uint32 &damage, uint32 *absorb)
static uint32 DealDamage (Unit *attacker, Unit *victim, uint32 damage, CleanDamage const *cleanDamage=nullptr, DamageEffectType damagetype=DIRECT_DAMAGE, SpellSchoolMask damageSchoolMask=SPELL_SCHOOL_MASK_NORMAL, SpellInfo const *spellProto=nullptr, bool durabilityLoss=true, bool allowGM=false)
static void Kill (Unit *killer, Unit *victim, bool durabilityLoss=true, WeaponAttackType attackType=BASE_ATTACK, SpellInfo const *spellProto=nullptr)
static int32 DealHeal (Unit *healer, Unit *victim, uint32 addhealth)
static void ApplyResilience (const Unit *victim, float *crit, int32 *damage, bool isCrit, CombatRating type)
static uint32 SpellCriticalDamageBonus (Unit const *caster, SpellInfo const *spellProto, uint32 damage, Unit const *victim)
static uint32 SpellCriticalHealingBonus (Unit const *caster, SpellInfo const *spellProto, uint32 damage, Unit const *victim)
static bool IsDamageReducedByArmor (SpellSchoolMask damageSchoolMask, SpellInfo const *spellInfo=nullptr, uint8 effIndex=MAX_SPELL_EFFECTS)
static uint32 CalcArmorReducedDamage (Unit const *attacker, Unit const *victim, const uint32 damage, SpellInfo const *spellInfo, uint8 attackerLevel=0, WeaponAttackType attackType=MAX_ATTACK)
static void CalcAbsorbResist (DamageInfo &dmgInfo, bool Splited=false)
static void CalcHealAbsorb (HealInfo &healInfo)
static void HandleSafeUnitPointersOnDelete (Unit *thisUnit)
Static Public Member Functions inherited from Object
static ObjectGuid GetGUID (Object const *o)
Static Public Member Functions inherited from Position
static float NormalizeOrientation (float o)
Public Attributes
PetSpellMap m_spells
AutoSpellList m_autospells
uint32 m_usedTalentCount
bool m_removed
Public Attributes inherited from TempSummon
const SummonPropertiesEntry *const m_Properties
Public Attributes inherited from Creature
struct {
::Spell const * Spell = nullptr
uint32 Delay = 0
ObjectGuid Target
float Orientation = 0.0f
} _spellFocusInfo
Loot loot
uint32 m_spells [MAX_CREATURE_SPELLS]
CreatureSpellCooldowns m_CreatureSpellCooldowns
uint32 m_ProhibitSchoolTime [7]
uint32 m_groupLootTimer
uint32 lootingGroupLowGUID
uint32 m_PlayerDamageReq
float m_SightDistance
float m_CombatDistance
bool m_isTempWorldObject
uint32 m_moveCircleMovementTime = MOVE_CIRCLE_CHECK_INTERVAL
uint32 m_moveBackwardsMovementTime = MOVE_BACKWARDS_CHECK_INTERVAL
Public Attributes inherited from Unit
uint32 m_extraAttacks
bool m_canDualWield
ControlSet m_Controlled
SafeUnitPointer m_movedByPlayer
ObjectGuid m_SummonSlot [MAX_SUMMON_SLOT]
ObjectGuid m_ObjectSlot [MAX_GAMEOBJECT_SLOT]
float m_modMeleeHitChance
float m_modRangedHitChance
float m_modSpellHitChance
int32 m_baseSpellCritChance
float m_threatModifier [MAX_SPELL_SCHOOL]
float m_modAttackSpeedPct [3]
EventProcessor m_Events
SpellImmuneList m_spellImmune [MAX_SPELL_IMMUNITY]
uint32 m_lastSanctuaryTime
PetAuraSet m_petAuras
bool IsAIEnabled
bool NeedChangeAI
bool m_ControlledByPlayer
bool m_CreatedByPlayer
std::set< SafeUnitPointer * > SafeUnitPointerSet
Position m_last_notify_position
uint32 m_last_notify_mstime
uint16 m_delayed_unit_relocation_timer
uint16 m_delayed_unit_ai_notify_timer
bool bRequestForcedVisibilityUpdate
Movement::MoveSpline * movespline
Public Attributes inherited from WorldObject
FlaggedValuesArray32< int32, uint32, StealthType, TOTAL_STEALTH_TYPES > m_stealth
FlaggedValuesArray32< int32, uint32, StealthType, TOTAL_STEALTH_TYPES > m_stealthDetect
FlaggedValuesArray32< int32, uint32, InvisibilityType, TOTAL_INVISIBILITY_TYPES > m_invisibility
FlaggedValuesArray32< int32, uint32, InvisibilityType, TOTAL_INVISIBILITY_TYPES > m_invisibilityDetect
FlaggedValuesArray32< int32, uint32, ServerSideVisibilityType, TOTAL_SERVERSIDE_VISIBILITY_TYPES > m_serverSideVisibility
FlaggedValuesArray32< int32, uint32, ServerSideVisibilityType, TOTAL_SERVERSIDE_VISIBILITY_TYPES > m_serverSideVisibilityDetect
uint32 LastUsedScriptID
MovementInfo m_movementInfo
Public Attributes inherited from Object
DataMap CustomData
Public Attributes inherited from WorldLocation
uint32 m_mapId
Public Attributes inherited from Position
float m_positionX = 0
float m_positionY = 0
float m_positionZ = 0
float m_orientation = 0
Protected Attributes
Player * m_owner
int32 m_happinessTimer
PetType m_petType
int32 m_duration
uint64 m_auraRaidUpdateMask
bool m_loading
int32 m_petRegenTimer
DeclinedName * m_declinedname
Unit * m_tempspellTarget
Unit * m_tempoldTarget
bool m_tempspellIsPositive
uint32 m_tempspell
uint8 asynchLoadType
Protected Attributes inherited from Minion
const ObjectGuid m_owner
float m_followAngle
Protected Attributes inherited from Creature
VendorItemCounts m_vendorItemCounts
ObjectGuid m_lootRecipient
ObjectGuid::LowType m_lootRecipientGroup
time_t m_corpseRemoveTime
Timers.
time_t m_respawnTime
time_t m_respawnedTime
uint32 m_respawnDelay
uint32 m_corpseDelay
float m_wanderDistance
uint16 m_transportCheckTimer
uint32 lootPickPocketRestoreTime
ReactStates m_reactState
MovementGeneratorType m_defaultMovementType
ObjectGuid::LowType m_spawnId
For new or temporary creatures is 0 for saved it is lowguid.
uint8 m_equipmentId
int8 m_originalEquipmentId
uint8 m_originalAnimTier
bool m_AlreadyCallAssistance
bool m_AlreadySearchedAssistance
bool m_regenHealth
bool m_AI_locked
SpellSchoolMask m_meleeDamageSchoolMask
uint32 m_originalEntry
bool m_moveInLineOfSightDisabled
bool m_moveInLineOfSightStrictlyDisabled
Position m_homePosition
Position m_transportHomePosition
bool DisableReputationGain
CreatureTemplate const * m_creatureInfo
CreatureData const * m_creatureData
float m_detectionDistance
uint16 m_LootMode
Protected Attributes inherited from Unit
UnitAI * i_AI
UnitAI * i_disabledAI
uint8 m_realRace
uint8 m_race
bool m_AutoRepeatFirstCast
int32 m_attackTimer [MAX_ATTACK]
float m_createStats [MAX_STATS]
AttackerSet m_attackers
Unit * m_attacking
DeathState m_deathState
int32 m_procDeep
DynObjectList m_dynObj
GameObjectList m_gameObj
uint32 m_transform
Spell * m_currentSpells [CURRENT_MAX_SPELL]
AuraMap m_ownedAuras
AuraApplicationMap m_appliedAuras
AuraList m_removedAuras
AuraMap::iterator m_auraUpdateIterator
uint32 m_removedAurasCount
AuraEffectList m_modAuras [TOTAL_AURAS]
AuraList m_scAuras
AuraApplicationList m_interruptableAuras
AuraStateAurasMap m_auraStateAuras
uint32 m_interruptMask
float m_auraModifiersGroup [UNIT_MOD_END][MODIFIER_TYPE_END]
float m_weaponDamage [MAX_ATTACK][2]
bool m_canModifyStats
VisibleAuraMap m_visibleAuras
float m_speed_rate [MAX_MOVE_TYPE]
CharmInfo * m_charmInfo
SharedVisionList m_sharedVision
MotionMaster * i_motionMaster
uint32 m_reactiveTimer [MAX_REACTIVE]
int32 m_regenTimer
ThreatMgr m_ThreatMgr
CharmThreatMap _charmThreatInfo
Vehicle * m_vehicle
Vehicle * m_vehicleKit
uint32 m_unitTypeMask
LiquidTypeEntry const * _lastLiquid
bool m_applyResilience
bool _instantCast
Protected Attributes inherited from WorldObject
std::string m_name
bool m_isActive
bool m_isVisibilityDistanceOverride
const bool m_isWorldObject
ZoneScript * m_zoneScript
uint32 _zoneId
uint32 _areaId
float _floorZ
bool _outdoors
LiquidData _liquidData
bool _updatePositionData
Transport * m_transport
Protected Attributes inherited from Object
uint16 m_objectType
TypeID m_objectTypeId
uint16 m_updateFlag
union {
int32 * m_int32Values
uint32 * m_uint32Values
float * m_floatValues
};
UpdateMask _changesMask
uint16 m_valuesCount
uint16 _fieldNotifyFlags
bool m_objectUpdated
Private Member Functions
void SaveToDB (uint32, uint8, uint32) override
void DeleteFromDB () override
Additional Inherited Members
Public Types inherited from Unit
typedef std::unordered_set< Unit * > AttackerSet
typedef std::set< Unit * > ControlSet
typedef std::multimap< uint32, Aura * > AuraMap
typedef std::pair< AuraMap::const_iterator, AuraMap::const_iterator > AuraMapBounds
typedef std::pair< AuraMap::iterator, AuraMap::iterator > AuraMapBoundsNonConst
typedef std::multimap< uint32, AuraApplication * > AuraApplicationMap
typedef std::pair< AuraApplicationMap::const_iterator, AuraApplicationMap::const_iterator > AuraApplicationMapBounds
typedef std::pair< AuraApplicationMap::iterator, AuraApplicationMap::iterator > AuraApplicationMapBoundsNonConst
typedef std::multimap< AuraStateType, AuraApplication * > AuraStateAurasMap
typedef std::pair< AuraStateAurasMap::const_iterator, AuraStateAurasMap::const_iterator > AuraStateAurasMapBounds
typedef std::list< AuraEffect * > AuraEffectList
typedef std::list< Aura * > AuraList
typedef std::list< AuraApplication * > AuraApplicationList
typedef std::list< DiminishingReturn > Diminishing
typedef GuidUnorderedSet ComboPointHolderSet
typedef std::map< uint8, AuraApplication * > VisibleAuraMap
typedef std::set< PetAura const * > PetAuraSet
Static Public Attributes inherited from Creature
static constexpr uint32 MOVE_CIRCLE_CHECK_INTERVAL = 3000
static constexpr uint32 MOVE_BACKWARDS_CHECK_INTERVAL = 2000
Protected Types inherited from Unit
typedef std::list< DynamicObject * > DynObjectList
typedef GuidList GameObjectList
typedef std::map< ObjectGuid, float > CharmThreatMap
Protected Member Functions inherited from Creature
bool CreateFromProto (ObjectGuid::LowType guidlow, uint32 Entry, uint32 vehId, const CreatureData *data=nullptr)
bool InitEntry (uint32 entry, const CreatureData *data=nullptr)
void RegenerateHealth ()
void Regenerate (Powers power)
bool IsInvisibleDueToDespawn () const override
bool CanAlwaysSee (WorldObject const *obj) const override
Protected Member Functions inherited from Unit
Unit (bool isWorldObject)
void BuildValuesUpdate (uint8 updatetype, ByteBuffer *data, Player *target) const override
void _UpdateSpells (uint32 time)
void _DeleteRemovedAuras ()
void _UpdateAutoRepeatSpell ()
bool IsAlwaysVisibleFor (WorldObject const *seer) const override
bool IsAlwaysDetectableFor (WorldObject const *seer) const override
Protected Member Functions inherited from WorldObject
WorldObject (bool isWorldObject)
void SetLocationMapId (uint32 _mapId)
void SetLocationInstanceId (uint32 _instanceId)
virtual bool IsNeverVisible () const
Protected Member Functions inherited from Object
Object ()
void _InitValues ()
void _Create (ObjectGuid::LowType guidlow, uint32 entry, HighGuid guidhigh)
std::string _ConcatFields (uint16 startIndex, uint16 size) const
void _LoadIntoDataField (std::string const &data, uint32 startOffset, uint32 count)
uint32 GetUpdateFieldData (Player const *target, uint32 *&flags) const
void BuildMovementUpdate (ByteBuffer *data, uint16 flags) const
void AddToObjectUpdateIfNeeded ()
Protected Member Functions inherited from MovableMapObject
MovableMapObject ()
Static Protected Member Functions inherited from Creature
static float _GetHealthMod (int32 Rank)
Detailed Description
Definition at line 54 of file Pet.h.
Constructor & Destructor Documentation
Pet()
Pet::Pet (Player * owner, PetType type = MAX_PET_TYPE) explicit
Definition at line 42 of file Pet.cpp.
                                     : Guardian(nullptr, owner ? owner->GetGUID() : ObjectGuid::Empty, true),
     m_usedTalentCount(0), m_removed(false), m_owner(owner),
     m_happinessTimer(PET_LOSE_HAPPINES_INTERVAL), m_petType(type), m_duration(0),
     m_auraRaidUpdateMask(0), m_loading(false), m_petRegenTimer(PET_FOCUS_REGEN_INTERVAL), m_declinedname(nullptr), m_tempspellTarget(nullptr), m_tempoldTarget(nullptr), m_tempspellIsPositive(false), m_tempspell(0), asynchLoadType(PET_LOAD_DEFAULT)
 {
     m_unitTypeMask |= UNIT_MASK_PET;
     if (type == HUNTER_PET)
         m_unitTypeMask |= UNIT_MASK_HUNTER_PET;
     if (!(m_unitTypeMask & UNIT_MASK_CONTROLABLE_GUARDIAN))
     {
         m_unitTypeMask |= UNIT_MASK_CONTROLABLE_GUARDIAN;
         InitCharmInfo();
     }
     m_name = "Pet";
 }
References HUNTER_PET, Unit::InitCharmInfo(), WorldObject::m_name, Unit::m_unitTypeMask, UNIT_MASK_CONTROLABLE_GUARDIAN, UNIT_MASK_HUNTER_PET, and UNIT_MASK_PET.
Referenced by HandleAsynchLoadFailed().
~Pet()
Pet::~Pet () override
Definition at line 60 of file Pet.cpp.
 {
     delete m_declinedname;
 }
References m_declinedname.
Member Function Documentation
_LoadAuras()
void Pet::_LoadAuras (PreparedQueryResult result, uint32 timediff)
Definition at line 1301 of file Pet.cpp.
 {
     LOG_DEBUG("entities.pet", "Loading auras for pet %s", GetGUID().ToString().c_str());
     if (result)
     {
         do
         {
             int32 damage[3];
             int32 baseDamage[3];
             Field* fields = result->Fetch();
             ObjectGuid caster_guid = ObjectGuid(fields[0].GetUInt64());
             // nullptr guid stored - pet is the caster of the spell - see Pet::_SaveAuras
             if (!caster_guid)
                 caster_guid = GetGUID();
             uint32 spellid = fields[1].GetUInt32();
             uint8 effmask = fields[2].GetUInt8();
             uint8 recalculatemask = fields[3].GetUInt8();
             uint8 stackcount = fields[4].GetUInt8();
             damage[0] = fields[5].GetInt32();
             damage[1] = fields[6].GetInt32();
             damage[2] = fields[7].GetInt32();
             baseDamage[0] = fields[8].GetInt32();
             baseDamage[1] = fields[9].GetInt32();
             baseDamage[2] = fields[10].GetInt32();
             int32 maxduration = fields[11].GetInt32();
             int32 remaintime = fields[12].GetInt32();
             uint8 remaincharges = fields[13].GetUInt8();
             SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(spellid);
             if (!spellInfo)
             {
                 LOG_ERROR("entities.pet", "Unknown aura (spellid %u), ignore.", spellid);
                 continue;
             }
             // avoid higher level auras if any, and adjust
             SpellInfo const* scaledSpellInfo = spellInfo->GetAuraRankForLevel(getLevel());
             if (scaledSpellInfo != spellInfo)
                 spellInfo = scaledSpellInfo;
             // again after level check
             if (!spellInfo)
                 continue;
             // negative effects should continue counting down after logout
             if (remaintime != -1 && !spellInfo->IsPositive())
             {
                 if (remaintime / IN_MILLISECONDS <= int32(timediff))
                     continue;
                 remaintime -= timediff * IN_MILLISECONDS;
             }
             // prevent wrong values of remaincharges
             if (spellInfo->ProcCharges)
             {
                 if (remaincharges <= 0 || remaincharges > spellInfo->ProcCharges)
                     remaincharges = spellInfo->ProcCharges;
             }
             else
                 remaincharges = 0;
             if (Aura* aura = Aura::TryCreate(spellInfo, effmask, this, nullptr, &baseDamage[0], nullptr, caster_guid))
             {
                 if (!aura->CanBeSaved())
                 {
                     aura->Remove();
                     continue;
                 }
                 aura->SetLoadedState(maxduration, remaintime, remaincharges, stackcount, recalculatemask, &damage[0]);
                 aura->ApplyForTargets();
                 LOG_DEBUG("entities.pet", "Added aura spellid %u, effectmask %u", spellInfo->Id, effmask);
             }
         } while (result->NextRow());
     }
 }
References SpellInfo::GetAuraRankForLevel(), Object::GetGUID(), Field::GetInt32(), Unit::getLevel(), Field::GetUInt32(), Field::GetUInt8(), SpellInfo::Id, IN_MILLISECONDS, SpellInfo::IsPositive(), LOG_DEBUG, LOG_ERROR, SpellInfo::ProcCharges, sSpellMgr, Position::ToString(), and Aura::TryCreate().
Referenced by WorldSession::HandleLoadPetFromDBSecondCallback().
_LoadSpellCooldowns()
void Pet::_LoadSpellCooldowns (PreparedQueryResult result)
Definition at line 1161 of file Pet.cpp.
 {
     m_CreatureSpellCooldowns.clear();
     if (result)
     {
         time_t curTime = time(nullptr);
         PacketCooldowns cooldowns;
         WorldPacket data;
         do
         {
             Field* fields = result->Fetch();
             uint32 spell_id = fields[0].GetUInt32();
             uint16 category = fields[1].GetUInt16();
             time_t db_time  = time_t(fields[2].GetUInt32());
             if (!sSpellMgr->GetSpellInfo(spell_id))
             {
                 LOG_ERROR("entities.pet", "Pet %u have unknown spell %u in `pet_spell_cooldown`, skipping.", m_charmInfo->GetPetNumber(), spell_id);
                 continue;
             }
             // skip outdated cooldown
             if (db_time <= curTime)
                 continue;
             uint32 cooldown = (db_time - curTime) * IN_MILLISECONDS;
             cooldowns[spell_id] = cooldown;
             _AddCreatureSpellCooldown(spell_id, category, cooldown);
             LOG_DEBUG("entities.pet", "Pet (Number: %u) spell %u cooldown loaded (%u secs).", m_charmInfo->GetPetNumber(), spell_id, uint32(db_time - curTime));
         } while (result->NextRow());
         if (!cooldowns.empty() && GetOwner())
         {
             BuildCooldownPacket(data, SPELL_COOLDOWN_FLAG_NONE, cooldowns);
             GetOwner()->GetSession()->SendPacket(&data);
         }
     }
 }
References Creature::_AddCreatureSpellCooldown(), Unit::BuildCooldownPacket(), GetOwner(), CharmInfo::GetPetNumber(), Player::GetSession(), Field::GetUInt16(), Field::GetUInt32(), IN_MILLISECONDS, LOG_DEBUG, LOG_ERROR, Unit::m_charmInfo, Creature::m_CreatureSpellCooldowns, WorldSession::SendPacket(), SPELL_COOLDOWN_FLAG_NONE, and sSpellMgr.
Referenced by WorldSession::HandleLoadPetFromDBSecondCallback().
_LoadSpells()
void Pet::_LoadSpells (PreparedQueryResult result)
Definition at line 1239 of file Pet.cpp.
 {
     if (result)
     {
         do
         {
             Field* fields = result->Fetch();
             addSpell(fields[0].GetUInt32(), ActiveStates(fields[1].GetUInt8()), PETSPELL_UNCHANGED);
         } while (result->NextRow());
     }
 }
References addSpell(), and PETSPELL_UNCHANGED.
Referenced by WorldSession::HandleLoadPetFromDBSecondCallback().
_SaveAuras()
void Pet::_SaveAuras (CharacterDatabaseTransaction trans, bool logout)
Definition at line 1379 of file Pet.cpp.
 {
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_PET_AURAS);
     stmt->setUInt32(0, m_charmInfo->GetPetNumber());
     trans->Append(stmt);
     for (AuraMap::const_iterator itr = m_ownedAuras.begin(); itr != m_ownedAuras.end(); ++itr)
     {
         // check if the aura has to be saved
         if (!itr->second->CanBeSaved() || IsPetAura(itr->second))
             continue;
         Aura* aura = itr->second;
         if (!logout && aura->GetDuration() < 60 * IN_MILLISECONDS)
             continue;
         // dont save infinite negative auras! (lavas, transformations etc)
         if (aura->IsPermanent() && !aura->GetSpellInfo()->IsPositive())
             continue;
         // pussywizard: don't save auras that cannot be cancelled (needed for ICC buff on pets/summons)
         if (aura->GetSpellInfo()->HasAttribute(SPELL_ATTR0_NO_AURA_CANCEL))
             continue;
         // xinef: don't save hidden auras
         if (aura->GetSpellInfo()->HasAttribute(SPELL_ATTR1_NO_AURA_ICON))
             continue;
         // Xinef: Dont save auras with model change
         if (aura->GetSpellInfo()->HasAura(SPELL_AURA_TRANSFORM))
             continue;
         // xinef: don's save auras with interrupt flags on map change
         if (aura->GetSpellInfo()->AuraInterruptFlags & AURA_INTERRUPT_FLAG_CHANGE_MAP)
             continue;
         int32 damage[MAX_SPELL_EFFECTS];
         int32 baseDamage[MAX_SPELL_EFFECTS];
         uint8 effMask = 0;
         uint8 recalculateMask = 0;
         for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
         {
             if (aura->GetEffect(i))
             {
                 baseDamage[i] = aura->GetEffect(i)->GetBaseAmount();
                 damage[i] = aura->GetEffect(i)->GetAmount();
                 effMask |= (1 << i);
                 if (aura->GetEffect(i)->CanBeRecalculated())
                     recalculateMask |= (1 << i);
             }
             else
             {
                 baseDamage[i] = 0;
                 damage[i] = 0;
             }
         }
         // don't save guid of caster in case we are caster of the spell - guid for pet is generated every pet load, so it won't match saved guid anyways
         ObjectGuid casterGUID = (itr->second->GetCasterGUID() == GetGUID()) ? ObjectGuid::Empty : itr->second->GetCasterGUID();
         uint8 index = 0;
         CharacterDatabasePreparedStatement* stmt2 = CharacterDatabase.GetPreparedStatement(CHAR_INS_PET_AURA);
         stmt2->setUInt32(index++, m_charmInfo->GetPetNumber());
         stmt2->setUInt64(index++, casterGUID.GetRawValue());
         stmt2->setUInt32(index++, itr->second->GetId());
         stmt2->setUInt8(index++, effMask);
         stmt2->setUInt8(index++, recalculateMask);
         stmt2->setUInt8(index++, itr->second->GetStackAmount());
         stmt2->setInt32(index++, damage[0]);
         stmt2->setInt32(index++, damage[1]);
         stmt2->setInt32(index++, damage[2]);
         stmt2->setInt32(index++, baseDamage[0]);
         stmt2->setInt32(index++, baseDamage[1]);
         stmt2->setInt32(index++, baseDamage[2]);
         stmt2->setInt32(index++, itr->second->GetMaxDuration());
         stmt2->setInt32(index++, itr->second->GetDuration());
         stmt2->setUInt8(index++, itr->second->GetCharges());
         trans->Append(stmt2);
     }
 }
References AURA_INTERRUPT_FLAG_CHANGE_MAP, SpellInfo::AuraInterruptFlags, AuraEffect::CanBeRecalculated(), CHAR_DEL_PET_AURAS, CHAR_INS_PET_AURA, CharacterDatabase, ObjectGuid::Empty, AuraEffect::GetAmount(), AuraEffect::GetBaseAmount(), Aura::GetDuration(), Aura::GetEffect(), Object::GetGUID(), CharmInfo::GetPetNumber(), ObjectGuid::GetRawValue(), Aura::GetSpellInfo(), SpellInfo::HasAttribute(), SpellInfo::HasAura(), IN_MILLISECONDS, Aura::IsPermanent(), Unit::IsPetAura(), SpellInfo::IsPositive(), Unit::m_charmInfo, Unit::m_ownedAuras, MAX_SPELL_EFFECTS, PreparedStatementBase::setInt32(), PreparedStatementBase::setUInt32(), PreparedStatementBase::setUInt64(), PreparedStatementBase::setUInt8(), SPELL_ATTR0_NO_AURA_CANCEL, SPELL_ATTR1_NO_AURA_ICON, and SPELL_AURA_TRANSFORM.
Referenced by SavePetToDB().
_SaveSpellCooldowns()
void Pet::_SaveSpellCooldowns (CharacterDatabaseTransaction trans, bool logout)
Definition at line 1205 of file Pet.cpp.
 {
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_PET_SPELL_COOLDOWNS);
     stmt->setUInt32(0, m_charmInfo->GetPetNumber());
     trans->Append(stmt);
     time_t curTime = time(nullptr);
     uint32 curMSTime = World::GetGameTimeMS();
     uint32 infTime   = curMSTime + infinityCooldownDelayCheck;
     // remove oudated and save active
     CreatureSpellCooldowns::iterator itr, itr2;
     for (itr = m_CreatureSpellCooldowns.begin(); itr != m_CreatureSpellCooldowns.end();)
     {
         itr2 = itr;
         ++itr;
         if (itr2->second.end <= curMSTime + 1000)
         {
             m_CreatureSpellCooldowns.erase(itr2);
         }
         else if (itr2->second.end <= infTime && (logout || itr2->second.end > (curMSTime + 30 * IN_MILLISECONDS)))
         {
             uint32 cooldown = ((itr2->second.end - curMSTime) / IN_MILLISECONDS) + curTime;
             stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_PET_SPELL_COOLDOWN);
             stmt->setUInt32(0, m_charmInfo->GetPetNumber());
             stmt->setUInt32(1, itr2->first);
             stmt->setUInt16(2, itr2->second.category);
             stmt->setUInt32(3, cooldown);
             trans->Append(stmt);
         }
     }
 }
References CHAR_DEL_PET_SPELL_COOLDOWNS, CHAR_INS_PET_SPELL_COOLDOWN, CharacterDatabase, World::GetGameTimeMS(), CharmInfo::GetPetNumber(), IN_MILLISECONDS, infinityCooldownDelayCheck, Unit::m_charmInfo, Creature::m_CreatureSpellCooldowns, PreparedStatementBase::setUInt16(), and PreparedStatementBase::setUInt32().
Referenced by SavePetToDB().
_SaveSpells()
void Pet::_SaveSpells (CharacterDatabaseTransaction trans)
Definition at line 1252 of file Pet.cpp.
 {
     for (PetSpellMap::iterator itr = m_spells.begin(), next = m_spells.begin(); itr != m_spells.end(); itr = next)
     {
         ++next;
         // prevent saving family passives to DB
         if (itr->second.type == PETSPELL_FAMILY)
             continue;
         CharacterDatabasePreparedStatement* stmt;
         switch (itr->second.state)
         {
             case PETSPELL_REMOVED:
                 stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_PET_SPELL_BY_SPELL);
                 stmt->setUInt32(0, m_charmInfo->GetPetNumber());
                 stmt->setUInt32(1, itr->first);
                 trans->Append(stmt);
                 m_spells.erase(itr);
                 continue;
             case PETSPELL_CHANGED:
                 stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_PET_SPELL_BY_SPELL);
                 stmt->setUInt32(0, m_charmInfo->GetPetNumber());
                 stmt->setUInt32(1, itr->first);
                 trans->Append(stmt);
                 stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_PET_SPELL);
                 stmt->setUInt32(0, m_charmInfo->GetPetNumber());
                 stmt->setUInt32(1, itr->first);
                 stmt->setUInt8(2, itr->second.active);
                 trans->Append(stmt);
                 break;
             case PETSPELL_NEW:
                 stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_PET_SPELL);
                 stmt->setUInt32(0, m_charmInfo->GetPetNumber());
                 stmt->setUInt32(1, itr->first);
                 stmt->setUInt8(2, itr->second.active);
                 trans->Append(stmt);
                 break;
             case PETSPELL_UNCHANGED:
                 continue;
         }
         itr->second.state = PETSPELL_UNCHANGED;
     }
 }
References CHAR_DEL_PET_SPELL_BY_SPELL, CHAR_INS_PET_SPELL, CharacterDatabase, CharmInfo::GetPetNumber(), Unit::m_charmInfo, m_spells, PETSPELL_CHANGED, PETSPELL_FAMILY, PETSPELL_NEW, PETSPELL_REMOVED, PETSPELL_UNCHANGED, PreparedStatementBase::setUInt32(), and PreparedStatementBase::setUInt8().
Referenced by SavePetToDB().
addSpell()
bool Pet::addSpell (uint32 spellId, ActiveStates active = ACT_DECIDE, PetSpellState state = PETSPELL_NEW, PetSpellType type = PETSPELL_NORMAL)
Definition at line 1461 of file Pet.cpp.
 {
     SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(spellId);
     if (!spellInfo)
     {
         // do pet spell book cleanup
         if (state == PETSPELL_UNCHANGED)                    // spell load case
         {
             LOG_ERROR("entities.pet", "Pet::addSpell: Non-existed in SpellStore spell #%u request, deleting for all pets in `pet_spell`.", spellId);
             CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_INVALID_PET_SPELL);
             stmt->setUInt32(0, spellId);
             CharacterDatabase.Execute(stmt);
         }
         else
             LOG_ERROR("entities.pet", "Pet::addSpell: Non-existed in SpellStore spell #%u request.", spellId);
         return false;
     }
     PetSpellMap::iterator itr = m_spells.find(spellId);
     if (itr != m_spells.end())
     {
         if (itr->second.state == PETSPELL_REMOVED)
         {
             m_spells.erase(itr);
             state = PETSPELL_CHANGED;
         }
         else if (state == PETSPELL_UNCHANGED && itr->second.state != PETSPELL_UNCHANGED)
         {
             // can be in case spell loading but learned at some previous spell loading
             itr->second.state = PETSPELL_UNCHANGED;
             ToggleAutocast(spellInfo, active == ACT_ENABLED);
             return false;
         }
         else
             return false;
     }
     PetSpell newspell;
     newspell.state = state;
     newspell.type = type;
     if (active == ACT_DECIDE)                               // active was not used before, so we save it's autocast/passive state here
     {
         if (spellInfo->IsAutocastable())
             newspell.active = ACT_DISABLED;
         else
             newspell.active = ACT_PASSIVE;
     }
     else
         newspell.active = active;
     // talent: unlearn all other talent ranks (high and low)
     if (TalentSpellPos const* talentPos = GetTalentSpellPos(spellId))
     {
         if (TalentEntry const* talentInfo = sTalentStore.LookupEntry(talentPos->talent_id))
         {
             for (uint8 i = 0; i < MAX_TALENT_RANK; ++i)
             {
                 // skip learning spell and no rank spell case
                 uint32 rankSpellId = talentInfo->RankID[i];
                 if (!rankSpellId || rankSpellId == spellId)
                     continue;
                 // skip unknown ranks
                 if (!HasSpell(rankSpellId))
                     continue;
                 removeSpell(rankSpellId, false, false);
             }
         }
     }
     else if (spellInfo->IsRanked())
     {
         for (PetSpellMap::const_iterator itr2 = m_spells.begin(); itr2 != m_spells.end(); ++itr2)
         {
             if (itr2->second.state == PETSPELL_REMOVED)
                 continue;
             SpellInfo const* oldRankSpellInfo = sSpellMgr->GetSpellInfo(itr2->first);
             if (!oldRankSpellInfo)
                 continue;
             if (spellInfo->IsDifferentRankOf(oldRankSpellInfo))
             {
                 // replace by new high rank
                 if (spellInfo->IsHighRankOf(oldRankSpellInfo))
                 {
                     newspell.active = itr2->second.active;
                     if (newspell.active == ACT_ENABLED)
                         ToggleAutocast(oldRankSpellInfo, false);
                     unlearnSpell(itr2->first, false, false);
                     break;
                 }
                 // ignore new lesser rank
                 else
                     return false;
             }
         }
     }
     m_spells[spellId] = newspell;
     if (spellInfo->IsPassive())
         CastSpell(this, spellId, true);
     else
         m_charmInfo->AddSpellToActionBar(spellInfo);
     // unapply aura stats if dont meet requirements
     // handle only if player is not loaded, loading is handled in loadfromdb
     if (!m_loading)
         if (Aura* aura = GetAura(spellId))
         {
             if (aura->GetSpellInfo()->CasterAuraState == AURA_STATE_HEALTHLESS_35_PERCENT ||
                     aura->GetSpellInfo()->CasterAuraState == AURA_STATE_HEALTH_ABOVE_75_PERCENT ||
                     aura->GetSpellInfo()->CasterAuraState == AURA_STATE_HEALTHLESS_20_PERCENT )
                 if (!HasAuraState((AuraStateType)aura->GetSpellInfo()->CasterAuraState))
                     aura->HandleAllEffects(aura->GetApplicationOfTarget(GetGUID()), AURA_EFFECT_HANDLE_REAL, false);
         }
     ToggleAutocast(spellInfo, (newspell.active == ACT_ENABLED));
     uint32 talentCost = GetTalentSpellCost(spellId);
     if (talentCost)
     {
         int32 free_points = GetMaxTalentPointsForLevel(getLevel());
         m_usedTalentCount += talentCost;
         // update free talent points
         free_points -= m_usedTalentCount;
         SetFreeTalentPoints(free_points > 0 ? free_points : 0);
     }
     return true;
 }
References ACT_DECIDE, ACT_DISABLED, ACT_ENABLED, ACT_PASSIVE, PetSpell::active, CharmInfo::AddSpellToActionBar(), AURA_EFFECT_HANDLE_REAL, AURA_STATE_HEALTH_ABOVE_75_PERCENT, AURA_STATE_HEALTHLESS_20_PERCENT, AURA_STATE_HEALTHLESS_35_PERCENT, Unit::CastSpell(), CHAR_DEL_INVALID_PET_SPELL, CharacterDatabase, Unit::GetAura(), Object::GetGUID(), Unit::getLevel(), GetMaxTalentPointsForLevel(), GetTalentSpellCost(), GetTalentSpellPos(), Unit::HasAuraState(), HasSpell(), SpellInfo::IsAutocastable(), SpellInfo::IsDifferentRankOf(), SpellInfo::IsHighRankOf(), SpellInfo::IsPassive(), SpellInfo::IsRanked(), LOG_ERROR, Unit::m_charmInfo, m_loading, m_spells, m_usedTalentCount, MAX_TALENT_RANK, PETSPELL_CHANGED, PETSPELL_REMOVED, PETSPELL_UNCHANGED, removeSpell(), SetFreeTalentPoints(), PreparedStatementBase::setUInt32(), sSpellMgr, sTalentStore, PetSpell::state, ToggleAutocast(), PetSpell::type, and unlearnSpell().
Referenced by _LoadSpells(), LearnPetPassives(), and learnSpell().
AddToWorld()
void Pet::AddToWorld () override virtual
Register the pet for guid lookup
Register the pet for guid lookup
Reimplemented from Creature.
Definition at line 65 of file Pet.cpp.
 {
     if (!IsInWorld())
     {
         GetMap()->GetObjectsStore().Insert<Pet>(GetGUID(), this);
         Unit::AddToWorld();
         Motion_Initialize();
         AIM_Initialize();
     }
     // pussywizard: apply ICC buff to pets
     if (GetOwnerGUID().IsPlayer() && GetMapId() == 631 && FindMap() && FindMap()->ToInstanceMap() && FindMap()->ToInstanceMap()->GetInstanceScript() && FindMap()->ToInstanceMap()->GetInstanceScript()->GetData(251 /*DATA_BUFF_AVAILABLE*/))
         if (Unit* owner = GetOwner())
             if (Player* plr = owner->ToPlayer())
             {
                 SpellAreaForAreaMapBounds saBounds = sSpellMgr->GetSpellAreaForAreaMapBounds(4812);
                 for (SpellAreaForAreaMap::const_iterator itr = saBounds.first; itr != saBounds.second; ++itr)
                     if ((itr->second->raceMask & plr->getRaceMask()) && !HasAura(itr->second->spellId))
                         if (const SpellInfo* si = sSpellMgr->GetSpellInfo(itr->second->spellId))
                             if (si->HasAura(SPELL_AURA_MOD_INCREASE_HEALTH_PERCENT))
                                 AddAura(itr->second->spellId, this);
             }
     // Prevent stuck pets when zoning. Pets default to "follow" when added to world
     // so we'll reset flags and let the AI handle things
     if (GetCharmInfo() && GetCharmInfo()->HasCommandState(COMMAND_FOLLOW))
     {
         GetCharmInfo()->SetIsCommandAttack(false);
         GetCharmInfo()->SetIsCommandFollow(false);
         GetCharmInfo()->SetIsAtStay(false);
         GetCharmInfo()->SetIsFollowing(false);
         GetCharmInfo()->SetIsReturning(false);
     }
 #ifdef ELUNA
     if (GetOwnerGUID().IsPlayer())
         sEluna->OnPetAddedToWorld(GetOwner(), this);
 #endif
 }
References Unit::AddAura(), Unit::AddToWorld(), Creature::AIM_Initialize(), COMMAND_FOLLOW, WorldObject::FindMap(), Unit::GetCharmInfo(), Object::GetGUID(), WorldObject::GetInstanceScript(), WorldObject::GetMap(), WorldLocation::GetMapId(), Map::GetObjectsStore(), GetOwner(), Unit::GetOwnerGUID(), Unit::HasAura(), TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::Insert(), Object::IsInWorld(), Object::IsPlayer(), Creature::Motion_Initialize(), CharmInfo::SetIsAtStay(), CharmInfo::SetIsCommandAttack(), CharmInfo::SetIsCommandFollow(), CharmInfo::SetIsFollowing(), CharmInfo::SetIsReturning(), SPELL_AURA_MOD_INCREASE_HEALTH_PERCENT, sSpellMgr, and Object::ToPlayer().
CastPetAuras()
void Pet::CastPetAuras (bool current)
Definition at line 2055 of file Pet.cpp.
 {
     Unit* owner = GetOwner();
     if (!owner || owner->GetTypeId() != TYPEID_PLAYER)
         return;
     if (!IsPermanentPetFor(owner->ToPlayer()))
         return;
     for (PetAuraSet::const_iterator itr = owner->m_petAuras.begin(); itr != owner->m_petAuras.end();)
     {
         PetAura const* pa = *itr;
         ++itr;
         if (!current && pa->IsRemovedOnChangePet())
             owner->RemovePetAura(pa);
         else
             CastPetAura(pa);
     }
 }
References Unit::CastPetAura(), GetOwner(), Object::GetTypeId(), IsPermanentPetFor(), PetAura::IsRemovedOnChangePet(), Unit::m_petAuras, Unit::RemovePetAura(), Object::ToPlayer(), and TYPEID_PLAYER.
Referenced by WorldSession::HandleLoadPetFromDBSecondCallback(), InitPetCreateSpells(), and setDeathState().
CastWhenWillAvailable()
void Pet::CastWhenWillAvailable (uint32 spellid, Unit * spellTarget, Unit * oldTarget, bool spellIsPositive = false)
Definition at line 2344 of file Pet.cpp.
 {
     if (!spellid)
         return;
     if (!spellTarget)
         return;
     m_tempspellTarget = spellTarget;
     m_tempspell = spellid;
     m_tempspellIsPositive = spellIsPositive;
     if (oldTarget)
         m_tempoldTarget = oldTarget;
 }
References m_tempoldTarget, m_tempspell, m_tempspellIsPositive, and m_tempspellTarget.
Referenced by WorldSession::HandlePetActionHelper().
CleanupActionBar()
void Pet::CleanupActionBar ()
Definition at line 1722 of file Pet.cpp.
 {
     for (uint8 i = 0; i < MAX_UNIT_ACTION_BAR_INDEX; ++i)
         if (UnitActionBarEntry const* ab = m_charmInfo->GetActionBarEntry(i))
             if (ab->GetAction() && ab->IsActionBarForSpell())
             {
                 if (!HasSpell(ab->GetAction()))
                     m_charmInfo->SetActionBar(i, 0, ACT_PASSIVE);
                 else if (SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(ab->GetAction()))
                     ToggleAutocast(spellInfo, ab->GetType() == ACT_ENABLED);
             }
 }
References ACT_ENABLED, ACT_PASSIVE, CharmInfo::GetActionBarEntry(), HasSpell(), Unit::m_charmInfo, MAX_UNIT_ACTION_BAR_INDEX, CharmInfo::SetActionBar(), sSpellMgr, and ToggleAutocast().
Referenced by WorldSession::HandleLoadPetFromDBSecondCallback().
ClearCastWhenWillAvailable()
void Pet::ClearCastWhenWillAvailable ()
Definition at line 2360 of file Pet.cpp.
 {
     m_tempspellIsPositive = false;
     m_tempspell = 0;
     m_tempspellTarget = nullptr;
     m_tempoldTarget = nullptr;
 }
References m_tempoldTarget, m_tempspell, m_tempspellIsPositive, and m_tempspellTarget.
Referenced by WorldSession::HandlePetActionHelper().
Create()
bool Pet::Create (ObjectGuid::LowType guidlow, Map * map, uint32 phaseMask, uint32 Entry, uint32 pet_number)
Definition at line 2007 of file Pet.cpp.
 {
     ASSERT(map);
     SetMap(map);
     SetPhaseMask(phaseMask, false);
     Object::_Create(guidlow, pet_number, HighGuid::Pet);
     m_spawnId = guidlow;
     m_originalEntry = Entry;
     if (!InitEntry(Entry))
         return false;
     SetSheath(SHEATH_STATE_MELEE);
     return true;
 }
References Object::_Create(), ASSERT, Entry, Creature::InitEntry(), Creature::m_originalEntry, Creature::m_spawnId, Pet, WorldObject::SetMap(), Unit::SetPhaseMask(), Unit::SetSheath(), and SHEATH_STATE_MELEE.
Referenced by CreateBaseAtTamed(), and HandleAsynchLoadFailed().
CreateBaseAtCreature()
bool Pet::CreateBaseAtCreature (Creature * creature)
Definition at line 671 of file Pet.cpp.
 {
     ASSERT(creature);
     if (!CreateBaseAtTamed(creature->GetCreatureTemplate(), creature->GetMap(), creature->GetPhaseMask()))
         return false;
     Relocate(creature->GetPositionX(), creature->GetPositionY(), creature->GetPositionZ(), creature->GetOrientation());
     if (!IsPositionValid())
     {
         LOG_ERROR("entities.pet", "Pet %s not created base at creature. Suggested coordinates isn't valid (X: %f Y: %f)",
                        GetGUID().ToString().c_str(), GetPositionX(), GetPositionY());
         return false;
     }
     CreatureTemplate const* cinfo = GetCreatureTemplate();
     if (!cinfo)
     {
         LOG_ERROR("entities.pet", "CreateBaseAtCreature() failed, creatureInfo is missing!");
         return false;
     }
     SetDisplayId(creature->GetDisplayId());
     UpdatePositionData();
     if (CreatureFamilyEntry const* cFamily = sCreatureFamilyStore.LookupEntry(cinfo->family))
         SetName(cFamily->Name[sWorld->GetDefaultDbcLocale()]);
     else
         SetName(creature->GetNameForLocaleIdx(sObjectMgr->GetDBCLocaleIndex()));
     return true;
 }
References ASSERT, CreateBaseAtTamed(), CreatureTemplate::family, Creature::GetCreatureTemplate(), Unit::GetDisplayId(), Object::GetGUID(), WorldObject::GetMap(), Creature::GetNameForLocaleIdx(), Position::GetOrientation(), WorldObject::GetPhaseMask(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Position::IsPositionValid(), LOG_ERROR, Position::Relocate(), sCreatureFamilyStore, SetDisplayId(), WorldObject::SetName(), sObjectMgr, sWorld, Position::ToString(), and WorldObject::UpdatePositionData().
Referenced by Unit::CreateTamedPetFrom(), and misc_commandscript::HandleCreatePetCommand().
CreateBaseAtCreatureInfo()
bool Pet::CreateBaseAtCreatureInfo (CreatureTemplate const * cinfo, Unit * owner)
Definition at line 706 of file Pet.cpp.
 {
     if (!CreateBaseAtTamed(cinfo, owner->GetMap(), owner->GetPhaseMask()))
         return false;
     if (CreatureFamilyEntry const* cFamily = sCreatureFamilyStore.LookupEntry(cinfo->family))
         SetName(cFamily->Name[sWorld->GetDefaultDbcLocale()]);
     Relocate(owner->GetPositionX(), owner->GetPositionY(), owner->GetPositionZ(), owner->GetOrientation());
     UpdatePositionData();
     return true;
 }
References CreateBaseAtTamed(), CreatureTemplate::family, WorldObject::GetMap(), Position::GetOrientation(), WorldObject::GetPhaseMask(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Position::Relocate(), sCreatureFamilyStore, WorldObject::SetName(), sWorld, and WorldObject::UpdatePositionData().
Referenced by Unit::CreateTamedPetFrom().
CreateBaseAtTamed()
bool Pet::CreateBaseAtTamed (CreatureTemplate const * cinfo, Map * map, uint32 phaseMask)
Definition at line 721 of file Pet.cpp.
 {
     LOG_DEBUG("entities.pet", "Pet::CreateBaseForTamed");
     ObjectGuid::LowType guid = map->GenerateLowGuid<HighGuid::Pet>();
     uint32 pet_number = sObjectMgr->GeneratePetNumber();
     if (!Create(guid, map, phaseMask, cinfo->Entry, pet_number))
         return false;
     SetMaxPower(POWER_HAPPINESS, GetCreatePowers(POWER_HAPPINESS));
     SetPower(POWER_HAPPINESS, 166500);
     setPowerType(POWER_FOCUS);
     SetUInt32Value(UNIT_FIELD_PET_NAME_TIMESTAMP, 0);
     SetUInt32Value(UNIT_FIELD_PETEXPERIENCE, 0);
     SetUInt32Value(UNIT_FIELD_PETNEXTLEVELEXP, uint32(sObjectMgr->GetXPForLevel(getLevel() + 1)* sWorld->getRate(RATE_XP_PET_NEXT_LEVEL)));
     SetUInt32Value(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_NONE);
     if (cinfo->type == CREATURE_TYPE_BEAST)
     {
         SetUInt32Value(UNIT_FIELD_BYTES_0, 0x02020100);
         SetSheath(SHEATH_STATE_MELEE);
         SetByteFlag(UNIT_FIELD_BYTES_2, 2, UNIT_CAN_BE_RENAMED | UNIT_CAN_BE_ABANDONED);
     }
     return true;
 }
References Create(), CREATURE_TYPE_BEAST, CreatureTemplate::Entry, Map::GenerateLowGuid(), Unit::GetCreatePowers(), Unit::getLevel(), LOG_DEBUG, Pet, POWER_FOCUS, POWER_HAPPINESS, RATE_XP_PET_NEXT_LEVEL, Object::SetByteFlag(), Unit::SetMaxPower(), Unit::SetPower(), Unit::setPowerType(), Unit::SetSheath(), Object::SetUInt32Value(), SHEATH_STATE_MELEE, sObjectMgr, sWorld, CreatureTemplate::type, UNIT_CAN_BE_ABANDONED, UNIT_CAN_BE_RENAMED, UNIT_FIELD_BYTES_0, UNIT_FIELD_BYTES_2, UNIT_FIELD_PET_NAME_TIMESTAMP, UNIT_FIELD_PETEXPERIENCE, UNIT_FIELD_PETNEXTLEVELEXP, UNIT_NPC_FLAG_NONE, and UNIT_NPC_FLAGS.
Referenced by CreateBaseAtCreature(), and CreateBaseAtCreatureInfo().
DeleteFromDB() [1/2]
void Pet::DeleteFromDB () inline override private virtual
Reimplemented from Creature.
Definition at line 195 of file Pet.h.
     {
         ABORT();
     }
References ABORT.
Referenced by Player::DeleteFromDB(), and SavePetToDB().
DeleteFromDB() [2/2]
void Pet::DeleteFromDB (ObjectGuid::LowType guidlow) static
Definition at line 344 of file Pet.cpp.
 {
     CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_CHAR_PET_BY_ID);
     stmt->setUInt32(0, guidlow);
     trans->Append(stmt);
     stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_CHAR_PET_DECLINEDNAME);
     stmt->setUInt32(0, guidlow);
     trans->Append(stmt);
     stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_PET_AURAS);
     stmt->setUInt32(0, guidlow);
     trans->Append(stmt);
     stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_PET_SPELLS);
     stmt->setUInt32(0, guidlow);
     trans->Append(stmt);
     stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_PET_SPELL_COOLDOWNS);
     stmt->setUInt32(0, guidlow);
     trans->Append(stmt);
     CharacterDatabase.CommitTransaction(trans);
 }
References CHAR_DEL_CHAR_PET_BY_ID, CHAR_DEL_CHAR_PET_DECLINEDNAME, CHAR_DEL_PET_AURAS, CHAR_DEL_PET_SPELL_COOLDOWNS, CHAR_DEL_PET_SPELLS, CharacterDatabase, and PreparedStatementBase::setUInt32().
GetAsynchLoadType()
uint8 Pet::GetAsynchLoadType () const inline
Definition at line 170 of file Pet.h.
 { return asynchLoadType; }
References asynchLoadType.
Referenced by HandleAsynchLoadSucceed(), and WorldSession::HandleLoadPetFromDBSecondCallback().
GetAuraUpdateMaskForRaid()
uint64 Pet::GetAuraUpdateMaskForRaid () const inline
Definition at line 158 of file Pet.h.
 { return m_auraRaidUpdateMask; }
References m_auraRaidUpdateMask.
Referenced by WorldSession::BuildPartyMemberStatsChangedPacket().
GetCurrentFoodBenefitLevel()
uint32 Pet::GetCurrentFoodBenefitLevel (uint32 itemlevel) const
Definition at line 1145 of file Pet.cpp.
 {
     // -5 or greater food level
     if (getLevel() <= itemlevel + 5)                         //possible to feed level 60 pet with level 55 level food for full effect
         return 35000;
     // -10..-6
     else if (getLevel() <= itemlevel + 10)                   //pure guess, but sounds good
         return 17000;
     // -14..-11
     else if (getLevel() <= itemlevel + 14)                   //level 55 food gets green on 70, makes sense to me
         return 8000;
     // -15 or less
     else
         return 0;                                           //food too low level
 }
References Unit::getLevel().
Referenced by Spell::CheckCast(), and Spell::EffectFeedPet().
GetDeclinedNames()
DeclinedName const* Pet::GetDeclinedNames () const inline
Definition at line 162 of file Pet.h.
 { return m_declinedname; }
References m_declinedname.
GetDuration()
int32 Pet::GetDuration () const inline
Definition at line 103 of file Pet.h.
 { return m_duration; }
References m_duration.
Referenced by Player::PetSpellInitialize().
GetFreeTalentPoints()
uint8 Pet::GetFreeTalentPoints () inline
Definition at line 153 of file Pet.h.
 { return GetByteValue(UNIT_FIELD_BYTES_1, 1); }
References Object::GetByteValue(), and UNIT_FIELD_BYTES_1.
Referenced by Player::BuildPetTalentsInfoData(), and Player::LearnPetTalent().
GetHappinessState()
HappinessState Pet::GetHappinessState ()
Definition at line 601 of file Pet.cpp.
 {
     if (GetPower(POWER_HAPPINESS) < HAPPINESS_LEVEL_SIZE)
         return UNHAPPY;
     else if (GetPower(POWER_HAPPINESS) >= HAPPINESS_LEVEL_SIZE * 2)
         return HAPPY;
     else
         return CONTENT;
 }
References CONTENT, Unit::GetPower(), HAPPINESS_LEVEL_SIZE, HAPPY, POWER_HAPPINESS, and UNHAPPY.
Referenced by Guardian::UpdateDamagePhysical().
GetMaxTalentPointsForLevel()
uint8 Pet::GetMaxTalentPointsForLevel (uint8 level)
Definition at line 1923 of file Pet.cpp.
 {
     uint8 points = (level >= 20) ? ((level - 16) / 4) : 0;
     // Mod points from owner SPELL_AURA_MOD_PET_TALENT_POINTS
     if (Unit* owner = GetOwner())
         points += owner->GetTotalAuraModifier(SPELL_AURA_MOD_PET_TALENT_POINTS);
     sScriptMgr->OnCalculateMaxTalentPointsForLevel(this, level, points);
     return points;
 }
References GetOwner(), SPELL_AURA_MOD_PET_TALENT_POINTS, and sScriptMgr.
Referenced by addSpell(), InitTalentForLevel(), removeSpell(), and resetTalents().
GetOwner()
Player* Pet::GetOwner () const inline
Definition at line 166 of file Pet.h.
 { return m_owner; }
References m_owner.
Referenced by _LoadSpellCooldowns(), AddToWorld(), CastPetAuras(), Spell::CheckCast(), Spell::EffectDismissPet(), Spell::EffectLearnPetSpell(), GetMaxTalentPointsForLevel(), GivePetXP(), HandleAsynchLoadSucceed(), WorldSession::HandlePetRename(), InitTalentForLevel(), removeSpell(), resetTalents(), SavePetToDB(), SetDisplayId(), SynchronizeLevelWithOwner(), and Update().
GetPetAutoSpellOnPos()
uint32 Pet::GetPetAutoSpellOnPos (uint8 pos) const inline override virtual
Reimplemented from Creature.
Definition at line 87 of file Pet.h.
     {
         if (pos >= m_autospells.size())
             return 0;
         else
             return m_autospells[pos];
     }
References m_autospells.
GetPetAutoSpellSize()
uint8 Pet::GetPetAutoSpellSize () const inline override virtual
Reimplemented from Creature.
Definition at line 86 of file Pet.h.
 { return m_autospells.size(); }
References m_autospells.
getPetType()
PetType Pet::getPetType () const inline
Definition at line 65 of file Pet.h.
 { return m_petType; }
References m_petType.
Referenced by Spell::EffectRenamePet(), Spell::EffectSummonPet(), GivePetLevel(), GivePetXP(), WorldSession::HandleLoadPetFromDBSecondCallback(), WorldSession::HandlePetAbandon(), WorldSession::HandlePetActionHelper(), WorldSession::HandleStablePet(), WorldSession::HandleStableSwapPet(), isControlled(), IsPermanentPetFor(), Player::RemovePet(), Player::ResetPetTalents(), SavePetToDB(), WorldSession::SendStablePetCallback(), setDeathState(), SynchronizeLevelWithOwner(), and Update().
GivePetLevel()
void Pet::GivePetLevel (uint8 level)
Definition at line 655 of file Pet.cpp.
 {
     if (!level || level == getLevel())
         return;
     if (getPetType() == HUNTER_PET)
     {
         SetUInt32Value(UNIT_FIELD_PETEXPERIENCE, 0);
         SetUInt32Value(UNIT_FIELD_PETNEXTLEVELEXP, uint32(sObjectMgr->GetXPForLevel(level)*sWorld->getRate(RATE_XP_PET_NEXT_LEVEL)));
     }
     InitStatsForLevel(level);
     InitLevelupSpellsForLevel();
     InitTalentForLevel();
 }
References Unit::getLevel(), getPetType(), HUNTER_PET, InitLevelupSpellsForLevel(), Guardian::InitStatsForLevel(), InitTalentForLevel(), RATE_XP_PET_NEXT_LEVEL, Object::SetUInt32Value(), sObjectMgr, sWorld, UNIT_FIELD_PETEXPERIENCE, and UNIT_FIELD_PETNEXTLEVELEXP.
Referenced by GivePetXP(), and SynchronizeLevelWithOwner().
GivePetXP()
void Pet::GivePetXP (uint32 xp)
Definition at line 616 of file Pet.cpp.
 {
     if (getPetType() != HUNTER_PET)
         return;
     xp *= sWorld->getRate(RATE_XP_PET);
     if (xp < 1)
         return;
     if (!IsAlive())
         return;
     uint8 maxlevel = std::min((uint8)sWorld->getIntConfig(CONFIG_MAX_PLAYER_LEVEL), GetOwner()->getLevel());
     uint8 petlevel = getLevel();
     // If pet is detected to be at, or above(?) the players level, don't hand out XP
     if (petlevel >= maxlevel)
         return;
     uint32 nextLvlXP = GetUInt32Value(UNIT_FIELD_PETNEXTLEVELEXP);
     uint32 curXP = GetUInt32Value(UNIT_FIELD_PETEXPERIENCE);
     uint32 newXP = curXP + xp;
     // Check how much XP the pet should receive, and hand off have any left from previous levelups
     while (newXP >= nextLvlXP && petlevel < maxlevel)
     {
         // Subtract newXP from amount needed for nextlevel, and give pet the level
         newXP -= nextLvlXP;
         ++petlevel;
         GivePetLevel(petlevel);
         nextLvlXP = GetUInt32Value(UNIT_FIELD_PETNEXTLEVELEXP);
     }
     // Not affected by special conditions - give it new XP
     SetUInt32Value(UNIT_FIELD_PETEXPERIENCE, petlevel < maxlevel ? newXP : 0);
 }
References CONFIG_MAX_PLAYER_LEVEL, Unit::getLevel(), GetOwner(), getPetType(), Object::GetUInt32Value(), GivePetLevel(), HUNTER_PET, Unit::IsAlive(), RATE_XP_PET, Object::SetUInt32Value(), sWorld, UNIT_FIELD_PETEXPERIENCE, and UNIT_FIELD_PETNEXTLEVELEXP.
HandleAsynchLoadFailed()
void Pet::HandleAsynchLoadFailed (AsynchPetSummon * info, Player * player, uint8 asynchLoadType, uint8 loadResult) static
Definition at line 2207 of file Pet.cpp.
 {
     if (loadResult == PET_LOAD_ERROR && asynchLoadType == PET_LOAD_HANDLE_UNSTABLE_CALLBACK)
     {
         player->GetSession()->SendStableResult(0x06 /*STABLE_ERR_STABLE*/);
     }
     else if (loadResult == PET_LOAD_NO_RESULT && info && (asynchLoadType == PET_LOAD_SUMMON_PET || asynchLoadType == PET_LOAD_SUMMON_DEAD_PET))
     {
         // xinef: petentry == 0 for hunter "call pet" (current pet summoned if any)
         if (!info->m_entry || !player)
             return;
         Pet* pet = new Pet(player, info->m_petType);
         pet->Relocate(info->pos); // already validated (IsPositionValid)
         Map* map = player->GetMap();
         uint32 pet_number = sObjectMgr->GeneratePetNumber();
         if (!pet->Create(map->GenerateLowGuid<HighGuid::Pet>(), map, player->GetPhaseMask(), info->m_entry, pet_number))
         {
             LOG_ERROR("entities.pet", "no such creature entry %u", info->m_entry);
             delete pet;
             return;
         }
         if (info->m_createdBySpell)
             pet->SetUInt32Value(UNIT_CREATED_BY_SPELL, info->m_createdBySpell);
         pet->SetCreatorGUID(player->GetGUID());
         pet->SetUInt32Value(UNIT_FIELD_FACTIONTEMPLATE, player->GetFaction());
         pet->setPowerType(POWER_MANA);
         pet->SetUInt32Value(UNIT_NPC_FLAGS, 0);
         pet->SetUInt32Value(UNIT_FIELD_BYTES_1, 0);
         pet->InitStatsForLevel(player->getLevel());
         player->SetMinion(pet, true);
         if (info->m_petType == SUMMON_PET)
         {
             if (pet->GetCreatureTemplate()->type == CREATURE_TYPE_DEMON || pet->GetCreatureTemplate()->type == CREATURE_TYPE_UNDEAD)
                 pet->GetCharmInfo()->SetPetNumber(pet_number, true); // Show pet details tab (Shift+P) only for demons & undead
             else
                 pet->GetCharmInfo()->SetPetNumber(pet_number, false);
             pet->SetUInt32Value(UNIT_FIELD_BYTES_0, 2048);
             pet->SetUInt32Value(UNIT_FIELD_PETEXPERIENCE, 0);
             pet->SetUInt32Value(UNIT_FIELD_PETNEXTLEVELEXP, 1000);
             pet->SetFullHealth();
             pet->SetPower(POWER_MANA, pet->GetMaxPower(POWER_MANA));
             pet->SetUInt32Value(UNIT_FIELD_PET_NAME_TIMESTAMP, uint32(time(nullptr))); // cast can't be helped in this case
         }
         map->AddToMap(pet->ToCreature(), true);
         if (info->m_petType == SUMMON_PET)
         {
             pet->InitPetCreateSpells();
             pet->InitTalentForLevel();
             pet->SavePetToDB(PET_SAVE_AS_CURRENT, false);
             player->PetSpellInitialize(); // no need to check, no other possibility
             // Remove Demonic Sacrifice auras (known pet)
             Unit::AuraEffectList const& auraClassScripts = player->GetAuraEffectsByType(SPELL_AURA_OVERRIDE_CLASS_SCRIPTS);
             for (Unit::AuraEffectList::const_iterator itr = auraClassScripts.begin(); itr != auraClassScripts.end();)
             {
                 if ((*itr)->GetMiscValue() == 2228)
                 {
                     player->RemoveAurasDueToSpell((*itr)->GetId());
                     itr = auraClassScripts.begin();
                 }
                 else
                     ++itr;
             }
         }
         if (info->m_duration > 0)
             pet->SetDuration(info->m_duration);
         // we are almost at home...
         if (asynchLoadType == PET_LOAD_SUMMON_PET)
         {
             Unit* caster = ObjectAccessor::GetUnit(*player, info->m_casterGUID);
             if (!caster)
                 caster = player;
             if (caster->GetTypeId() == TYPEID_UNIT)
             {
                 if (caster->ToCreature()->IsTotem())
                     pet->SetReactState(REACT_AGGRESSIVE);
                 else
                     pet->SetReactState(REACT_DEFENSIVE);
             }
             // Reset cooldowns
             if (player->getClass() != CLASS_HUNTER)
             {
                 pet->m_CreatureSpellCooldowns.clear();
                 player->ToPlayer()->PetSpellInitialize();
             }
             // Set health to max if new pet is summoned
             // in this function old pet is saved with current health eg. 20% and new one is loaded from db with same amount
             // pet should have full health
             pet->SetHealth(pet->GetMaxHealth());
             // generate new name for summon pet
             std::string new_name = sObjectMgr->GeneratePetName(info->m_entry);
             if (!new_name.empty())
                 pet->SetName(new_name);
         }
         else // if GetAsynchLoad() == PET_LOAD_SUMMON_DEAD_PET
         {
             pet->SetUInt32Value(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_NONE);
             pet->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_SKINNABLE);
             pet->setDeathState(ALIVE);
             pet->ClearUnitState(uint32(UNIT_STATE_ALL_STATE & ~(UNIT_STATE_POSSESSED))); // xinef: just in case
             pet->SetHealth(pet->CountPctFromMaxHealth(uint32(info->m_casterGUID.GetRawValue()))); // damage for this effect is saved in caster guid, dont create next variable...
             //AIM_Initialize();
             //owner->PetSpellInitialize();
             pet->SavePetToDB(PET_SAVE_AS_CURRENT, false);
         }
     }
 }
References Map::AddToMap(), ALIVE, asynchLoadType, CLASS_HUNTER, Unit::ClearUnitState(), Unit::CountPctFromMaxHealth(), Create(), CREATURE_TYPE_DEMON, CREATURE_TYPE_UNDEAD, Map::GenerateLowGuid(), Unit::GetAuraEffectsByType(), Unit::GetCharmInfo(), Unit::getClass(), Creature::GetCreatureTemplate(), Unit::GetFaction(), Object::GetGUID(), Unit::getLevel(), WorldObject::GetMap(), Unit::GetMaxHealth(), Unit::GetMaxPower(), WorldObject::GetPhaseMask(), ObjectGuid::GetRawValue(), Player::GetSession(), Object::GetTypeId(), ObjectAccessor::GetUnit(), InitPetCreateSpells(), Guardian::InitStatsForLevel(), InitTalentForLevel(), Unit::IsTotem(), LOG_ERROR, AsynchPetSummon::m_casterGUID, AsynchPetSummon::m_createdBySpell, Creature::m_CreatureSpellCooldowns, AsynchPetSummon::m_duration, AsynchPetSummon::m_entry, AsynchPetSummon::m_petType, Pet, Pet(), PET_LOAD_ERROR, PET_LOAD_HANDLE_UNSTABLE_CALLBACK, PET_LOAD_NO_RESULT, PET_LOAD_SUMMON_DEAD_PET, PET_LOAD_SUMMON_PET, PET_SAVE_AS_CURRENT, Player::PetSpellInitialize(), AsynchPetSummon::pos, POWER_MANA, REACT_AGGRESSIVE, REACT_DEFENSIVE, Position::Relocate(), Unit::RemoveAurasDueToSpell(), Object::RemoveFlag(), SavePetToDB(), WorldSession::SendStableResult(), Unit::SetCreatorGUID(), setDeathState(), SetDuration(), Unit::SetFullHealth(), Unit::SetHealth(), Unit::SetMinion(), WorldObject::SetName(), CharmInfo::SetPetNumber(), Unit::SetPower(), Unit::setPowerType(), Creature::SetReactState(), Object::SetUInt32Value(), sObjectMgr, SPELL_AURA_OVERRIDE_CLASS_SCRIPTS, SUMMON_PET, Object::ToCreature(), Object::ToPlayer(), CreatureTemplate::type, TYPEID_UNIT, UNIT_CREATED_BY_SPELL, UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_NONE, UNIT_FIELD_BYTES_0, UNIT_FIELD_BYTES_1, UNIT_FIELD_FACTIONTEMPLATE, UNIT_FIELD_FLAGS, UNIT_FIELD_PET_NAME_TIMESTAMP, UNIT_FIELD_PETEXPERIENCE, UNIT_FIELD_PETNEXTLEVELEXP, UNIT_FLAG_SKINNABLE, UNIT_NPC_FLAGS, UNIT_STATE_ALL_STATE, and UNIT_STATE_POSSESSED.
HandleAsynchLoadSucceed()
void Pet::HandleAsynchLoadSucceed ()
Definition at line 2108 of file Pet.cpp.
 {
     Player* owner = GetOwner();
     if (!owner)
         return;
     if (GetAsynchLoadType() == PET_LOAD_HANDLE_UNSTABLE_CALLBACK)
     {
         if (Player* player = owner->ToPlayer())
             player->GetSession()->SendStableResult(0x09 /*STABLE_SUCCESS_UNSTABLE*/);
     }
     else// if (GetAsynchLoadType() == PET_LOAD_BG_RESURRECT || GetAsynchLoadType() == PET_LOAD_SUMMON_PET || GetAsynchLoadType() == PET_LOAD_SUMMON_DEAD_PET)
     {
         // Remove Demonic Sacrifice auras (known pet)
         Unit::AuraEffectList const& auraClassScripts = owner->GetAuraEffectsByType(SPELL_AURA_OVERRIDE_CLASS_SCRIPTS);
         for (Unit::AuraEffectList::const_iterator itr = auraClassScripts.begin(); itr != auraClassScripts.end();)
         {
             if ((*itr)->GetMiscValue() == 2228)
             {
                 owner->RemoveAurasDueToSpell((*itr)->GetId());
                 itr = auraClassScripts.begin();
             }
             else
                 ++itr;
         }
         SetUInt32Value(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_NONE);
         RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_SKINNABLE);
         if (GetAsynchLoadType() == PET_LOAD_SUMMON_DEAD_PET)
         {
             setDeathState(ALIVE);
             ClearUnitState(uint32(UNIT_STATE_ALL_STATE & ~(UNIT_STATE_POSSESSED))); // xinef: added just in case... some linked auras and so on
             SetHealth(CountPctFromMaxHealth(15)); // Xinef: well, only two pet reviving spells exist and both revive with 15%
             SavePetToDB(PET_SAVE_AS_CURRENT, false);
         }
     }
     // xinef: resurrect with full health if resurrected by BG / BF spirit
     if (GetAsynchLoadType() == PET_LOAD_BG_RESURRECT)
         SetHealth(GetMaxHealth());
     // xinef: We are summoned in arena / battleground, remove all positive auras
     // xinef: and set health to full if in preparation phase
     if (GetMap()->IsBattlegroundOrArena())
     {
         if (GetMap()->IsBattleArena())
             RemoveArenaAuras();
         if (Player* player = owner->ToPlayer())
             if (Battleground* bg = player->GetBattleground())
                 if (bg->GetStatus() == STATUS_WAIT_JOIN)
                 {
                     if (IsAlive())
                         SetHealth(GetMaxHealth());
                     if (GetMap()->IsBattleground())
                         CastSpell(this, SPELL_PREPARATION, true);
                 }
     }
     // Fix aurastate auras, depending on health!
     // Set aurastate manualy, prevents aura switching
     if (HealthBelowPct(20))
         SetFlag(UNIT_FIELD_AURASTATE, 1 << (AURA_STATE_HEALTHLESS_20_PERCENT - 1));
     if (HealthBelowPct(35))
         SetFlag(UNIT_FIELD_AURASTATE, 1 << (AURA_STATE_HEALTHLESS_35_PERCENT - 1));
     if (HealthAbovePct(75))
         SetFlag(UNIT_FIELD_AURASTATE, 1 << (AURA_STATE_HEALTH_ABOVE_75_PERCENT - 1));
     // unapply aura stats if dont meet requirements
     AuraApplicationMap const& Auras = GetAppliedAuras();
     for (AuraApplicationMap::const_iterator itr = Auras.begin(); itr != Auras.end(); ++itr)
     {
         // we assume that all auras are applied now, aurastate was modfied MANUALY preventing any apply/unapply state switching
         Aura* aura = itr->second->GetBase();
         SpellInfo const* m_spellInfo = aura->GetSpellInfo();
         if (m_spellInfo->CasterAuraState != AURA_STATE_HEALTHLESS_20_PERCENT &&
                 m_spellInfo->CasterAuraState != AURA_STATE_HEALTHLESS_35_PERCENT &&
                 m_spellInfo->CasterAuraState != AURA_STATE_HEALTH_ABOVE_75_PERCENT)
             continue;
         if (!HasAuraState((AuraStateType)m_spellInfo->CasterAuraState))
             aura->HandleAllEffects(itr->second, AURA_EFFECT_HANDLE_REAL, false);
     }
     SetAsynchLoadType(PET_LOAD_DEFAULT);
     // Warlock pet exception, check if owner is casting new summon spell
     if (Spell* spell = owner->GetCurrentSpell(CURRENT_GENERIC_SPELL))
         if (spell->GetSpellInfo()->HasEffect(SPELL_EFFECT_SUMMON_PET))
             CastSpell(this, 32752, true, nullptr, nullptr, GetGUID());
     if (owner->NeedSendSpectatorData() && GetCreatureTemplate()->family)
     {
         ArenaSpectator::SendCommand_UInt32Value(owner->FindMap(), owner->GetGUID(), "PHP", (uint32)GetHealthPct());
         ArenaSpectator::SendCommand_UInt32Value(owner->FindMap(), owner->GetGUID(), "PET", GetCreatureTemplate()->family);
     }
 }
References ALIVE, AURA_EFFECT_HANDLE_REAL, AURA_STATE_HEALTH_ABOVE_75_PERCENT, AURA_STATE_HEALTHLESS_20_PERCENT, AURA_STATE_HEALTHLESS_35_PERCENT, SpellInfo::CasterAuraState, Unit::CastSpell(), Unit::ClearUnitState(), Unit::CountPctFromMaxHealth(), CURRENT_GENERIC_SPELL, WorldObject::FindMap(), Unit::GetAppliedAuras(), GetAsynchLoadType(), Unit::GetAuraEffectsByType(), Creature::GetCreatureTemplate(), Unit::GetCurrentSpell(), Object::GetGUID(), Unit::GetHealthPct(), WorldObject::GetMap(), Unit::GetMaxHealth(), GetOwner(), Aura::GetSpellInfo(), Aura::HandleAllEffects(), Unit::HasAuraState(), Unit::HealthAbovePct(), Unit::HealthBelowPct(), Unit::IsAlive(), Player::NeedSendSpectatorData(), PET_LOAD_BG_RESURRECT, PET_LOAD_DEFAULT, PET_LOAD_HANDLE_UNSTABLE_CALLBACK, PET_LOAD_SUMMON_DEAD_PET, PET_SAVE_AS_CURRENT, Unit::RemoveArenaAuras(), Unit::RemoveAurasDueToSpell(), Object::RemoveFlag(), SavePetToDB(), ArenaSpectator::SendCommand_UInt32Value(), SetAsynchLoadType(), setDeathState(), Object::SetFlag(), Unit::SetHealth(), Object::SetUInt32Value(), SPELL_AURA_OVERRIDE_CLASS_SCRIPTS, SPELL_EFFECT_SUMMON_PET, SPELL_PREPARATION, STATUS_WAIT_JOIN, Object::ToPlayer(), UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_NONE, UNIT_FIELD_AURASTATE, UNIT_FIELD_FLAGS, UNIT_FLAG_SKINNABLE, UNIT_STATE_ALL_STATE, and UNIT_STATE_POSSESSED.
Referenced by WorldSession::HandleLoadPetFromDBSecondCallback().
HasSpell()
bool Pet::HasSpell (uint32 spell) const override virtual
Reimplemented from Creature.
Definition at line 2027 of file Pet.cpp.
 {
     PetSpellMap::const_iterator itr = m_spells.find(spell);
     return itr != m_spells.end() && itr->second.state != PETSPELL_REMOVED;
 }
References m_spells, and PETSPELL_REMOVED.
Referenced by addSpell(), Player::BuildPetTalentsInfoData(), CleanupActionBar(), misc_commandscript::HandlePetLearnCommand(), misc_commandscript::HandlePetUnlearnCommand(), and Player::LearnPetTalent().
HaveInDiet()
bool Pet::HaveInDiet (ItemTemplate const * item) const
Definition at line 1127 of file Pet.cpp.
 {
     if (!item->FoodType)
         return false;
     CreatureTemplate const* cInfo = GetCreatureTemplate();
     if (!cInfo)
         return false;
     CreatureFamilyEntry const* cFamily = sCreatureFamilyStore.LookupEntry(cInfo->family);
     if (!cFamily)
         return false;
     uint32 diet = cFamily->petFoodMask;
     uint32 FoodMask = 1 << (item->FoodType - 1);
     return diet & FoodMask;
 }
References CreatureTemplate::family, ItemTemplate::FoodType, Creature::GetCreatureTemplate(), CreatureFamilyEntry::petFoodMask, and sCreatureFamilyStore.
Referenced by Spell::CheckCast().
InitLevelupSpellsForLevel()
void Pet::InitLevelupSpellsForLevel ()
Definition at line 1617 of file Pet.cpp.
 {
     uint8 level = getLevel();
     if (PetLevelupSpellSet const* levelupSpells = GetCreatureTemplate()->family ? sSpellMgr->GetPetLevelupSpellList(GetCreatureTemplate()->family) : nullptr)
     {
         // PetLevelupSpellSet ordered by levels, process in reversed order
         for (PetLevelupSpellSet::const_reverse_iterator itr = levelupSpells->rbegin(); itr != levelupSpells->rend(); ++itr)
         {
             // will called first if level down
             if (itr->first > level && sScriptMgr->CanUnlearnSpellSet(this, itr->first, itr->second))
                 unlearnSpell(itr->second, true);                 // will learn prev rank if any
             // will called if level up
             else
                 learnSpell(itr->second);                        // will unlearn prev rank if any
         }
     }
     int32 petSpellsId = GetCreatureTemplate()->PetSpellDataId ? -(int32)GetCreatureTemplate()->PetSpellDataId : GetEntry();
     // default spells (can be not learned if pet level (as owner level decrease result for example) less first possible in normal game)
     if (PetDefaultSpellsEntry const* defSpells = sSpellMgr->GetPetDefaultSpellsEntry(petSpellsId))
     {
         for (uint8 i = 0; i < MAX_CREATURE_SPELL_DATA_SLOT; ++i)
         {
             SpellInfo const* spellEntry = sSpellMgr->GetSpellInfo(defSpells->spellid[i]);
             if (!spellEntry)
                 continue;
             // will called first if level down
             if (spellEntry->SpellLevel > level && sScriptMgr->CanUnlearnSpellDefault(this, spellEntry))
                 unlearnSpell(spellEntry->Id, true);
             // will called if level up
             else
                 learnSpell(spellEntry->Id);
         }
     }
 }
References Creature::GetCreatureTemplate(), Object::GetEntry(), Unit::getLevel(), SpellInfo::Id, learnSpell(), MAX_CREATURE_SPELL_DATA_SLOT, CreatureTemplate::PetSpellDataId, SpellInfo::SpellLevel, sScriptMgr, sSpellMgr, and unlearnSpell().
Referenced by GivePetLevel(), WorldSession::HandleLoadPetFromDBSecondCallback(), and InitPetCreateSpells().
InitPetCreateSpells()
void Pet::InitPetCreateSpells ()
Definition at line 1735 of file Pet.cpp.
 {
     m_charmInfo->InitPetActionBar();
     m_spells.clear();
     LearnPetPassives();
     InitLevelupSpellsForLevel();
     CastPetAuras(false);
 }
References CastPetAuras(), InitLevelupSpellsForLevel(), CharmInfo::InitPetActionBar(), LearnPetPassives(), Unit::m_charmInfo, and m_spells.
Referenced by HandleAsynchLoadFailed(), misc_commandscript::HandleCreatePetCommand(), and Unit::InitTamedPet().
InitTalentForLevel()
void Pet::InitTalentForLevel ()
Definition at line 1904 of file Pet.cpp.
 {
     uint8 level = getLevel();
     uint32 talentPointsForLevel = GetMaxTalentPointsForLevel(level);
     Unit* owner = GetOwner();
     if (!owner || owner->GetTypeId() != TYPEID_PLAYER)
         return;
     // Reset talents in case low level (on level down) or wrong points for level (hunter can unlearn TP increase talent)
     if (talentPointsForLevel == 0 || m_usedTalentCount > talentPointsForLevel)
         resetTalents(); // Remove all talent points
     SetFreeTalentPoints(talentPointsForLevel - m_usedTalentCount);
     if (!m_loading)
         owner->ToPlayer()->SendTalentsInfoData(true);
 }
References Unit::getLevel(), GetMaxTalentPointsForLevel(), GetOwner(), Object::GetTypeId(), m_loading, m_usedTalentCount, resetTalents(), Player::SendTalentsInfoData(), SetFreeTalentPoints(), Object::ToPlayer(), and TYPEID_PLAYER.
Referenced by Spell::EffectCreateTamedPet(), Spell::EffectTameCreature(), GivePetLevel(), HandleAsynchLoadFailed(), and WorldSession::HandleLoadPetFromDBSecondCallback().
isBeingLoaded()
bool Pet::isBeingLoaded () const inline override virtual
Reimplemented from Unit.
Definition at line 78 of file Pet.h.
 { return m_loading;}
References m_loading.
isControlled()
bool Pet::isControlled () const inline
Definition at line 67 of file Pet.h.
 { return getPetType() == SUMMON_PET || getPetType() == HUNTER_PET; }
References getPetType(), HUNTER_PET, and SUMMON_PET.
Referenced by Unit::GetRandomContactPoint(), WorldSession::HandleLoadPetFromDBSecondCallback(), Unit::Kill(), Player::RemovePet(), SavePetToDB(), SetDisplayId(), Player::UnsummonPetTemporaryIfAny(), Update(), and Unit::UpdateAuraForGroup().
IsPermanentPetFor()
bool Pet::IsPermanentPetFor (Player * owner) const
Definition at line 1984 of file Pet.cpp.
 {
     switch (getPetType())
     {
         case SUMMON_PET:
             switch (owner->getClass())
             {
                 case CLASS_WARLOCK:
                     return GetCreatureTemplate()->type == CREATURE_TYPE_DEMON;
                 case CLASS_DEATH_KNIGHT:
                     return GetCreatureTemplate()->type == CREATURE_TYPE_UNDEAD;
                 case CLASS_MAGE:
                     return GetEntry() == 37994;
                 default:
                     return false;
             }
         case HUNTER_PET:
             return true;
         default:
             return false;
     }
 }
References CLASS_DEATH_KNIGHT, CLASS_MAGE, CLASS_WARLOCK, CREATURE_TYPE_DEMON, CREATURE_TYPE_UNDEAD, Unit::getClass(), Creature::GetCreatureTemplate(), Object::GetEntry(), getPetType(), HUNTER_PET, SUMMON_PET, and CreatureTemplate::type.
Referenced by CastPetAuras(), reset_commandscript::HandleResetTalentsCommand(), and Player::PetSpellInitialize().
isTemporarySummoned()
bool Pet::isTemporarySummoned () const inline
Definition at line 68 of file Pet.h.
 { return m_duration > 0; }
References m_duration.
Referenced by WorldSession::HandleLoadPetFromDBSecondCallback(), TryLoadFromDB(), and Player::UnsummonPetTemporaryIfAny().
LearnPetPassives()
void Pet::LearnPetPassives ()
Definition at line 2034 of file Pet.cpp.
 {
     CreatureTemplate const* cInfo = GetCreatureTemplate();
     if (!cInfo)
         return;
     CreatureFamilyEntry const* cFamily = sCreatureFamilyStore.LookupEntry(cInfo->family);
     if (!cFamily)
         return;
     PetFamilySpellsStore::const_iterator petStore = sPetFamilySpellsStore.find(cFamily->ID);
     if (petStore != sPetFamilySpellsStore.end())
     {
         // For general hunter pets skill 270
         // Passive 01~10, Passive 00 (20782, not used), Ferocious Inspiration (34457)
         // Scale 01~03 (34902~34904, bonus from owner, not used)
         for (PetFamilySpellsSet::const_iterator petSet = petStore->second.begin(); petSet != petStore->second.end(); ++petSet)
             addSpell(*petSet, ACT_DECIDE, PETSPELL_NEW, PETSPELL_FAMILY);
     }
 }
References ACT_DECIDE, addSpell(), CreatureTemplate::family, Creature::GetCreatureTemplate(), CreatureFamilyEntry::ID, PETSPELL_FAMILY, PETSPELL_NEW, sCreatureFamilyStore, and sPetFamilySpellsStore.
Referenced by WorldSession::HandleLoadPetFromDBSecondCallback(), and InitPetCreateSpells().
learnSpell()
bool Pet::learnSpell (uint32 spell_id)
Definition at line 1601 of file Pet.cpp.
 {
     // prevent duplicated entires in spell book
     if (!addSpell(spell_id))
         return false;
     if (!m_loading)
     {
         WorldPacket data(SMSG_PET_LEARNED_SPELL, 4);
         data << uint32(spell_id);
         m_owner->GetSession()->SendPacket(&data);
         m_owner->PetSpellInitialize();
     }
     return true;
 }
References addSpell(), Player::GetSession(), m_loading, m_owner, Player::PetSpellInitialize(), WorldSession::SendPacket(), and SMSG_PET_LEARNED_SPELL.
Referenced by Spell::EffectLearnPetSpell(), misc_commandscript::HandlePetLearnCommand(), InitLevelupSpellsForLevel(), Player::LearnPetTalent(), learnSpellHighRank(), and removeSpell().
learnSpellHighRank()
void Pet::learnSpellHighRank (uint32 spellid)
Definition at line 2076 of file Pet.cpp.
 {
     learnSpell(spellid);
     if (uint32 next = sSpellMgr->GetNextSpellInChain(spellid))
         learnSpellHighRank(next);
 }
References learnSpell(), and sSpellMgr.
Referenced by learn_commandscript::HandleLearnAllMyPetTalentsCommand().
LoadPetFromDB()
bool Pet::LoadPetFromDB (Player * owner, uint8 asynchLoadType, uint32 petentry = 0, uint32 petnumber = 0, bool current = false, AsynchPetSummon * info = nullptr) static
Definition at line 173 of file Pet.cpp.
 {
     // we are loading pet at that moment
     if (owner->IsSpectator() || owner->GetPet() || !owner->IsInWorld() || !owner->FindMap())
         return false;
     bool forceLoadFromDB = false;
     sScriptMgr->OnBeforeLoadPetFromDB(owner, petentry, petnumber, current, forceLoadFromDB);
     if (!forceLoadFromDB)
         if (owner->getClass() == CLASS_DEATH_KNIGHT && !owner->CanSeeDKPet()) // DK Pet exception
             return false;
     ObjectGuid::LowType ownerGuid = owner->GetGUID().GetCounter();
     CharacterDatabasePreparedStatement* stmt;
     if (petnumber)
     {
         // Known petnumber entry
         stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_CHAR_PET_BY_ENTRY);
         stmt->setUInt32(0, ownerGuid);
         stmt->setUInt32(1, petnumber);
     }
     else if (current)
     {
         // Current pet (slot 0)
         stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_CHAR_PET_BY_ENTRY_AND_SLOT);
         stmt->setUInt32(0, ownerGuid);
         stmt->setUInt8(1, uint8(PET_SAVE_AS_CURRENT));
     }
     else if (petentry)
     {
         // known petentry entry (unique for summoned pet, but non unique for hunter pet (only from current or not stabled pets)
         stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_CHAR_PET_BY_ENTRY_AND_SLOT_2);
         stmt->setUInt32(0, ownerGuid);
         stmt->setUInt32(1, petentry);
         stmt->setUInt8(2, uint8(PET_SAVE_AS_CURRENT));
         stmt->setUInt8(3, uint8(PET_SAVE_LAST_STABLE_SLOT));
     }
     else
     {
         // Any current or other non-stabled pet (for hunter "call pet")
         stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_CHAR_PET_BY_SLOT);
         stmt->setUInt32(0, ownerGuid);
         stmt->setUInt8(1, uint8(PET_SAVE_AS_CURRENT));
         stmt->setUInt8(2, uint8(PET_SAVE_LAST_STABLE_SLOT));
     }
     // load them asynchronously
     {
         WorldSession* mySess = owner->GetSession();
         mySess->GetQueryProcessor().AddCallback(CharacterDatabase.AsyncQuery(stmt)
         .WithPreparedCallback([mySess, asynchLoadType, info, owner](PreparedQueryResult result)
         {
             // process only if player is in world (teleport crashes?)
             // otherwise wait with result till he logs in
             uint8 loadResult = mySess->HandleLoadPetFromDBFirstCallback(result, asynchLoadType);
             if (loadResult != PET_LOAD_OK)
                 Pet::HandleAsynchLoadFailed(info, owner, asynchLoadType, loadResult);
         }));
     }
     return true;
 }
References AsyncCallbackProcessor< T >::AddCallback(), asynchLoadType, Player::CanSeeDKPet(), CHAR_SEL_CHAR_PET_BY_ENTRY, CHAR_SEL_CHAR_PET_BY_ENTRY_AND_SLOT, CHAR_SEL_CHAR_PET_BY_ENTRY_AND_SLOT_2, CHAR_SEL_CHAR_PET_BY_SLOT, CharacterDatabase, CLASS_DEATH_KNIGHT, WorldObject::FindMap(), Unit::getClass(), ObjectGuid::GetCounter(), Object::GetGUID(), Player::GetPet(), WorldSession::GetQueryProcessor(), Player::GetSession(), Object::IsInWorld(), Player::IsSpectator(), PET_SAVE_AS_CURRENT, PET_SAVE_LAST_STABLE_SLOT, PreparedStatementBase::setUInt32(), PreparedStatementBase::setUInt8(), and sScriptMgr.
Referenced by spell_gen_pet_summoned::HandleScript(), WorldSession::HandleStableSwapPetCallback(), WorldSession::HandleUnstablePetCallback(), Player::LoadPet(), Player::ResummonPetTemporaryUnSummonedIfAny(), and Player::SummonPet().
LoseHappiness()
void Pet::LoseHappiness ()
Definition at line 590 of file Pet.cpp.
 {
     uint32 curValue = GetPower(POWER_HAPPINESS);
     if (curValue <= 0)
         return;
     int32 addvalue = 670;                                   //value is 70/35/17/8/4 (per min) * 1000 / 8 (timer 7.5 secs)
     if (IsInCombat())                                        //we know in combat happiness fades faster, multiplier guess
         addvalue = int32(addvalue * 1.5f);
     ModifyPower(POWER_HAPPINESS, -addvalue);
 }
References Unit::GetPower(), Unit::IsInCombat(), Unit::ModifyPower(), and POWER_HAPPINESS.
Referenced by Update().
Remove()
void Pet::Remove (PetSaveMode mode, bool returnreagent = false)
Definition at line 611 of file Pet.cpp.
 {
     m_owner->RemovePet(this, mode, returnreagent);
 }
References m_owner, and Player::RemovePet().
Referenced by AuraEffect::HandleModPossessPet(), and Update().
RemoveFromWorld()
void Pet::RemoveFromWorld () override virtual
Remove the pet from the accessor
Don't call the function for Creature, normal mobs + totems go in a different storage
Reimplemented from Minion.
Definition at line 107 of file Pet.cpp.
 {
     if (IsInWorld())
     {
         Unit::RemoveFromWorld();
         GetMap()->GetObjectsStore().Remove<Pet>(GetGUID());
     }
 }
References Object::GetGUID(), WorldObject::GetMap(), Map::GetObjectsStore(), Object::IsInWorld(), TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::Remove(), and Unit::RemoveFromWorld().
removeSpell()
bool Pet::removeSpell (uint32 spell_id, bool learn_prev, bool clear_ab = true)
Definition at line 1671 of file Pet.cpp.
 {
     PetSpellMap::iterator itr = m_spells.find(spell_id);
     if (itr == m_spells.end())
         return false;
     if (itr->second.state == PETSPELL_REMOVED)
         return false;
     if (itr->second.state == PETSPELL_NEW)
         m_spells.erase(itr);
     else
         itr->second.state = PETSPELL_REMOVED;
     RemoveAurasDueToSpell(spell_id);
     uint32 talentCost = GetTalentSpellCost(spell_id);
     if (talentCost > 0)
     {
         if (m_usedTalentCount > talentCost)
             m_usedTalentCount -= talentCost;
         else
             m_usedTalentCount = 0;
         // update free talent points
         int32 free_points = GetMaxTalentPointsForLevel(getLevel()) - m_usedTalentCount;
         SetFreeTalentPoints(free_points > 0 ? free_points : 0);
     }
     if (learn_prev)
     {
         if (uint32 prev_id = sSpellMgr->GetPrevSpellInChain (spell_id))
             learnSpell(prev_id);
         else
             learn_prev = false;
     }
     // if remove last rank or non-ranked then update action bar at server and client if need
     if (clear_ab && !learn_prev && m_charmInfo->RemoveSpellFromActionBar(spell_id))
     {
         if (!m_loading)
         {
             // need update action bar for last removed rank
             if (Unit* owner = GetOwner())
                 if (owner->GetTypeId() == TYPEID_PLAYER)
                     owner->ToPlayer()->PetSpellInitialize();
         }
     }
     return true;
 }
References Unit::getLevel(), GetMaxTalentPointsForLevel(), GetOwner(), GetTalentSpellCost(), learnSpell(), Unit::m_charmInfo, m_loading, m_spells, m_usedTalentCount, PETSPELL_NEW, PETSPELL_REMOVED, Unit::RemoveAurasDueToSpell(), CharmInfo::RemoveSpellFromActionBar(), SetFreeTalentPoints(), sSpellMgr, and TYPEID_PLAYER.
Referenced by addSpell(), misc_commandscript::HandlePetUnlearnCommand(), and unlearnSpell().
RemoveSpellCooldown()
void Pet::RemoveSpellCooldown (uint32 spell_id, bool update)
Definition at line 2368 of file Pet.cpp.
 {
     m_CreatureSpellCooldowns.erase(spell_id);
     if (update)
     {
         if (Player* playerOwner = GetCharmerOrOwnerPlayerOrPlayerItself())
         {
             WorldPacket data(SMSG_CLEAR_COOLDOWN, 4 + 8);
             data << uint32(spell_id);
             data << GetGUID();
             playerOwner->SendDirectMessage(&data);
         }
     }
 }
References Unit::GetCharmerOrOwnerPlayerOrPlayerItself(), Object::GetGUID(), Creature::m_CreatureSpellCooldowns, and SMSG_CLEAR_COOLDOWN.
Referenced by WorldSession::HandlePetActionHelper().
ResetAuraUpdateMaskForRaid()
void Pet::ResetAuraUpdateMaskForRaid () inline
Definition at line 160 of file Pet.h.
 { m_auraRaidUpdateMask = 0; }
References m_auraRaidUpdateMask.
resetTalents()
bool Pet::resetTalents ()
Definition at line 1746 of file Pet.cpp.
 {
     Unit* owner = GetOwner();
     if (!owner || owner->GetTypeId() != TYPEID_PLAYER)
         return false;
     if (!sScriptMgr->CanResetTalents(this))
         return false;
     // not need after this call
     if (owner->ToPlayer()->HasAtLoginFlag(AT_LOGIN_RESET_PET_TALENTS))
         owner->ToPlayer()->RemoveAtLoginFlag(AT_LOGIN_RESET_PET_TALENTS, true);
     CreatureTemplate const* ci = GetCreatureTemplate();
     if (!ci)
         return false;
     // Check pet talent type
     CreatureFamilyEntry const* pet_family = sCreatureFamilyStore.LookupEntry(ci->family);
     if (!pet_family || pet_family->petTalentType < 0)
         return false;
     Player* player = owner->ToPlayer();
     uint8 level = getLevel();
     uint32 talentPointsForLevel = GetMaxTalentPointsForLevel(level);
     if (m_usedTalentCount == 0)
     {
         SetFreeTalentPoints(talentPointsForLevel);
         return false;
     }
     for (uint32 i = 0; i < sTalentStore.GetNumRows(); ++i)
     {
         TalentEntry const* talentInfo = sTalentStore.LookupEntry(i);
         if (!talentInfo)
             continue;
         TalentTabEntry const* talentTabInfo = sTalentTabStore.LookupEntry(talentInfo->TalentTab);
         if (!talentTabInfo)
             continue;
         // unlearn only talents for pets family talent type
         if (!((1 << pet_family->petTalentType) & talentTabInfo->petTalentMask))
             continue;
         for (uint8 j = 0; j < MAX_TALENT_RANK; ++j)
         {
             for (PetSpellMap::const_iterator itr = m_spells.begin(); itr != m_spells.end();)
             {
                 if (itr->second.state == PETSPELL_REMOVED)
                 {
                     ++itr;
                     continue;
                 }
                 // remove learned spells (all ranks)
                 uint32 itrFirstId = sSpellMgr->GetFirstSpellInChain(itr->first);
                 // unlearn if first rank is talent or learned by talent
                 if (itrFirstId == talentInfo->RankID[j])
                 {
                     unlearnSpell(itr->first, false);
                     itr = m_spells.begin();
                     continue;
                 }
                 else
                     ++itr;
             }
         }
     }
     SetFreeTalentPoints(talentPointsForLevel);
     if (!m_loading)
         player->PetSpellInitialize();
     return true;
 }
References AT_LOGIN_RESET_PET_TALENTS, CreatureTemplate::family, Creature::GetCreatureTemplate(), Unit::getLevel(), GetMaxTalentPointsForLevel(), GetOwner(), Object::GetTypeId(), Player::HasAtLoginFlag(), m_loading, m_spells, m_usedTalentCount, MAX_TALENT_RANK, PETSPELL_REMOVED, Player::PetSpellInitialize(), TalentTabEntry::petTalentMask, CreatureFamilyEntry::petTalentType, TalentEntry::RankID, Player::RemoveAtLoginFlag(), sCreatureFamilyStore, SetFreeTalentPoints(), sScriptMgr, sSpellMgr, sTalentStore, sTalentTabStore, TalentEntry::TalentTab, Object::ToPlayer(), TYPEID_PLAYER, and unlearnSpell().
Referenced by reset_commandscript::HandleResetTalentsCommand(), InitTalentForLevel(), Player::ResetPetTalents(), and resetTalentsForAllPetsOf().
resetTalentsForAllPetsOf()
void Pet::resetTalentsForAllPetsOf (Player * owner, Pet * online_pet = nullptr) static
Definition at line 1826 of file Pet.cpp.
 {
     // not need after this call
     if (owner->ToPlayer()->HasAtLoginFlag(AT_LOGIN_RESET_PET_TALENTS))
         owner->ToPlayer()->RemoveAtLoginFlag(AT_LOGIN_RESET_PET_TALENTS, true);
     // reset for online
     if (online_pet)
         online_pet->resetTalents();
     // now need only reset for offline pets (all pets except online case)
     uint32 except_petnumber = online_pet ? online_pet->GetCharmInfo()->GetPetNumber() : 0;
     // xinef: zomg! sync query
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_CHAR_PET);
     stmt->setUInt32(0, owner->GetGUID().GetCounter());
     stmt->setUInt32(1, except_petnumber);
     PreparedQueryResult resultPets = CharacterDatabase.Query(stmt);
     // no offline pets
     if (!resultPets)
         return;
     // xinef: zomg! sync query
     stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_PET_SPELL_LIST);
     stmt->setUInt32(0, owner->GetGUID().GetCounter());
     stmt->setUInt32(1, except_petnumber);
     PreparedQueryResult result = CharacterDatabase.Query(stmt);
     if (!result)
         return;
     bool need_comma = false;
     std::ostringstream ss;
     ss << "DELETE FROM pet_spell WHERE guid IN (";
     do
     {
         Field* fields = resultPets->Fetch();
         uint32 id = fields[0].GetUInt32();
         if (need_comma)
             ss << ',';
         ss << id;
         need_comma = true;
     } while (resultPets->NextRow());
     ss << ") AND spell IN (";
     bool need_execute = false;
     do
     {
         Field* fields = result->Fetch();
         uint32 spell = fields[0].GetUInt32();
         if (!GetTalentSpellCost(spell))
             continue;
         if (need_execute)
             ss << ',';
         ss << spell;
         need_execute = true;
     } while (result->NextRow());
     if (!need_execute)
         return;
     ss << ')';
     CharacterDatabase.Execute(ss.str().c_str());
 }
References AT_LOGIN_RESET_PET_TALENTS, CHAR_SEL_CHAR_PET, CHAR_SEL_PET_SPELL_LIST, CharacterDatabase, Unit::GetCharmInfo(), ObjectGuid::GetCounter(), Object::GetGUID(), CharmInfo::GetPetNumber(), GetTalentSpellCost(), Field::GetUInt32(), Player::HasAtLoginFlag(), Player::RemoveAtLoginFlag(), resetTalents(), PreparedStatementBase::setUInt32(), and Object::ToPlayer().
Referenced by WorldSession::HandlePlayerLoginFromDB(), and reset_commandscript::HandleResetTalentsCommand().
SavePetToDB()
void Pet::SavePetToDB (PetSaveMode mode, bool logout)
Definition at line 239 of file Pet.cpp.
 {
     // not save not player pets
     if (!GetOwnerGUID().IsPlayer())
         return;
     // dont allow to save pet when it is loaded, possibly bugs action bar!, save only fully controlled creature
     Player* owner = GetOwner()->ToPlayer();
     if (!owner || m_loading || !GetEntry() || !isControlled())
         return;
     // not save pet as current if another pet temporary unsummoned
     if (mode == PET_SAVE_AS_CURRENT && owner->GetTemporaryUnsummonedPetNumber() &&
             owner->GetTemporaryUnsummonedPetNumber() != m_charmInfo->GetPetNumber())
     {
         // pet will lost anyway at restore temporary unsummoned
         if (getPetType() == HUNTER_PET)
             return;
         // for warlock case
         mode = PET_SAVE_NOT_IN_SLOT;
     }
     uint32 curhealth = GetHealth();
     uint32 curmana = GetPower(POWER_MANA);
     CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
     // save auras before possibly removing them
     _SaveAuras(trans, logout);
     // stable and not in slot saves
     if (mode > PET_SAVE_AS_CURRENT)
         RemoveAllAuras();
     _SaveSpells(trans);
     _SaveSpellCooldowns(trans, logout);
     CharacterDatabase.CommitTransaction(trans);
     // current/stable/not_in_slot
     if (mode >= PET_SAVE_AS_CURRENT)
     {
         ObjectGuid::LowType ownerLowGUID = GetOwnerGUID().GetCounter();
         trans = CharacterDatabase.BeginTransaction();
         // remove current data
         CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_CHAR_PET_BY_ID);
         stmt->setUInt32(0, m_charmInfo->GetPetNumber());
         trans->Append(stmt);
         // prevent duplicate using slot (except PET_SAVE_NOT_IN_SLOT)
         if (mode <= PET_SAVE_LAST_STABLE_SLOT)
         {
             stmt = CharacterDatabase.GetPreparedStatement(CHAR_UDP_CHAR_PET_SLOT_BY_SLOT);
             stmt->setUInt8(0, uint8(PET_SAVE_NOT_IN_SLOT));
             stmt->setUInt32(1, ownerLowGUID);
             stmt->setUInt8(2, uint8(mode));
             trans->Append(stmt);
         }
         // prevent existence another hunter pet in PET_SAVE_AS_CURRENT and PET_SAVE_NOT_IN_SLOT
         if (getPetType() == HUNTER_PET && (mode == PET_SAVE_AS_CURRENT || mode > PET_SAVE_LAST_STABLE_SLOT))
         {
             stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_CHAR_PET_BY_SLOT);
             stmt->setUInt32(0, ownerLowGUID);
             stmt->setUInt8(1, uint8(PET_SAVE_AS_CURRENT));
             stmt->setUInt8(2, uint8(PET_SAVE_LAST_STABLE_SLOT));
             trans->Append(stmt);
         }
         // save pet
         stmt = CharacterDatabase.GetPreparedStatement(CHAR_REP_CHAR_PET);
         stmt->setUInt32(0, m_charmInfo->GetPetNumber());
         stmt->setUInt32(1, GetEntry());
         stmt->setUInt32(2, ownerLowGUID);
         stmt->setUInt32(3, GetNativeDisplayId());
         stmt->setUInt32(4, GetUInt32Value(UNIT_CREATED_BY_SPELL));
         stmt->setUInt8(5, uint8(getPetType()));
         stmt->setUInt8(6, getLevel());
         stmt->setUInt32(7, GetUInt32Value(UNIT_FIELD_PETEXPERIENCE));
         stmt->setUInt8(8, uint8(GetReactState()));
         stmt->setString(9, GetName());
         stmt->setUInt8(10, uint8(HasByteFlag(UNIT_FIELD_BYTES_2, 2, UNIT_CAN_BE_RENAMED) ? 0 : 1));
         stmt->setUInt8(11, uint8(mode));
         stmt->setUInt32(12, curhealth);
         stmt->setUInt32(13, curmana);
         stmt->setUInt32(14, GetPower(POWER_HAPPINESS));
         stmt->setUInt32(15, time(nullptr));
         std::ostringstream ss;
         for (uint32 i = ACTION_BAR_INDEX_START; i < ACTION_BAR_INDEX_END; ++i)
             ss << uint32(m_charmInfo->GetActionBarEntry(i)->GetType()) << ' ' << uint32(m_charmInfo->GetActionBarEntry(i)->GetAction()) << ' ';
         stmt->setString(16, ss.str());
         trans->Append(stmt);
         CharacterDatabase.CommitTransaction(trans);
     }
     // delete
     else
     {
         RemoveAllAuras();
         DeleteFromDB(m_charmInfo->GetPetNumber());
     }
 }
References _SaveAuras(), _SaveSpellCooldowns(), _SaveSpells(), ACTION_BAR_INDEX_END, ACTION_BAR_INDEX_START, CHAR_DEL_CHAR_PET_BY_ID, CHAR_DEL_CHAR_PET_BY_SLOT, CHAR_REP_CHAR_PET, CHAR_UDP_CHAR_PET_SLOT_BY_SLOT, CharacterDatabase, DeleteFromDB(), UnitActionBarEntry::GetAction(), CharmInfo::GetActionBarEntry(), ObjectGuid::GetCounter(), Object::GetEntry(), Unit::GetHealth(), Unit::getLevel(), WorldObject::GetName(), Unit::GetNativeDisplayId(), GetOwner(), Unit::GetOwnerGUID(), CharmInfo::GetPetNumber(), getPetType(), Unit::GetPower(), Creature::GetReactState(), Player::GetTemporaryUnsummonedPetNumber(), UnitActionBarEntry::GetType(), Object::GetUInt32Value(), Object::HasByteFlag(), HUNTER_PET, isControlled(), Object::IsPlayer(), Unit::m_charmInfo, m_loading, PET_SAVE_AS_CURRENT, PET_SAVE_LAST_STABLE_SLOT, PET_SAVE_NOT_IN_SLOT, POWER_HAPPINESS, POWER_MANA, Unit::RemoveAllAuras(), PreparedStatementBase::setString(), PreparedStatementBase::setUInt32(), PreparedStatementBase::setUInt8(), Object::ToPlayer(), UNIT_CAN_BE_RENAMED, UNIT_CREATED_BY_SPELL, UNIT_FIELD_BYTES_2, and UNIT_FIELD_PETEXPERIENCE.
Referenced by Spell::EffectCreateTamedPet(), Spell::EffectLearnPetSpell(), Spell::EffectResurrectPet(), Spell::EffectTameCreature(), HandleAsynchLoadFailed(), HandleAsynchLoadSucceed(), misc_commandscript::HandleCreatePetCommand(), npc_commandscript::HandleNpcTameCommand(), and Player::RemovePet().
SaveToDB()
void Pet::SaveToDB (uint32 , uint8 , uint32) inline override private virtual
Reimplemented from TempSummon.
Definition at line 191 of file Pet.h.
     {
         ABORT();
     }
References ABORT.
SetAsynchLoadType()
void Pet::SetAsynchLoadType (uint8 type) inline
Definition at line 171 of file Pet.h.
 { asynchLoadType = type; }
References asynchLoadType.
Referenced by HandleAsynchLoadSucceed().
SetAuraUpdateMaskForRaid()
void Pet::SetAuraUpdateMaskForRaid (uint8 slot) inline
Definition at line 159 of file Pet.h.
 { m_auraRaidUpdateMask |= (uint64(1) << slot); }
References m_auraRaidUpdateMask.
Referenced by Unit::UpdateAuraForGroup().
setDeathState()
void Pet::setDeathState (DeathState s, bool despawn = false) override virtual
Reimplemented from Minion.
Definition at line 371 of file Pet.cpp.
 {
     Creature::setDeathState(s);
     if (getDeathState() == CORPSE)
     {
         if (getPetType() == HUNTER_PET)
         {
             // pet corpse non lootable and non skinnable
             SetUInt32Value(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_NONE);
             RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_SKINNABLE);
             //lose happiness when died and not in BG/Arena
             MapEntry const* mapEntry = sMapStore.LookupEntry(GetMapId());
             if (!mapEntry || (mapEntry->map_type != MAP_ARENA && mapEntry->map_type != MAP_BATTLEGROUND))
                 ModifyPower(POWER_HAPPINESS, -HAPPINESS_LEVEL_SIZE);
             //SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_STUNNED);
         }
     }
     else if (getDeathState() == ALIVE)
     {
         //RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_STUNNED);
         CastPetAuras(true);
     }
 }
References ALIVE, CastPetAuras(), CORPSE, Unit::getDeathState(), WorldLocation::GetMapId(), getPetType(), HAPPINESS_LEVEL_SIZE, HUNTER_PET, MAP_ARENA, MAP_BATTLEGROUND, MapEntry::map_type, Unit::ModifyPower(), POWER_HAPPINESS, Object::RemoveFlag(), Creature::setDeathState(), Object::SetUInt32Value(), sMapStore, UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_NONE, UNIT_FIELD_FLAGS, and UNIT_FLAG_SKINNABLE.
Referenced by Spell::EffectResurrectPet(), HandleAsynchLoadFailed(), HandleAsynchLoadSucceed(), and WorldSession::HandleLoadPetFromDBSecondCallback().
SetDisplayId()
void Pet::SetDisplayId (uint32 modelId) override virtual
Reimplemented from Creature.
Definition at line 2331 of file Pet.cpp.
 {
     Guardian::SetDisplayId(modelId);
     if (!isControlled())
         return;
     if (Unit* owner = GetOwner())
         if (Player* player = owner->ToPlayer())
             if (player->GetGroup())
                 player->SetGroupUpdateFlag(GROUP_UPDATE_FLAG_PET_MODEL_ID);
 }
References GetOwner(), GROUP_UPDATE_FLAG_PET_MODEL_ID, isControlled(), Creature::SetDisplayId(), and Object::ToPlayer().
Referenced by CreateBaseAtCreature().
SetDuration()
void Pet::SetDuration (int32 dur) inline
Definition at line 102 of file Pet.h.
 { m_duration = dur; }
References m_duration.
Referenced by HandleAsynchLoadFailed().
SetFreeTalentPoints()
void Pet::SetFreeTalentPoints (uint8 points) inline
Definition at line 154 of file Pet.h.
 { SetByteValue(UNIT_FIELD_BYTES_1, UNIT_BYTES_1_OFFSET_PET_TALENTS, points); }
References Object::SetByteValue(), UNIT_BYTES_1_OFFSET_PET_TALENTS, and UNIT_FIELD_BYTES_1.
Referenced by addSpell(), learn_commandscript::HandleLearnAllMyPetTalentsCommand(), InitTalentForLevel(), Player::LearnPetTalent(), removeSpell(), and resetTalents().
SetLoading()
void Pet::SetLoading (bool load) inline
Definition at line 167 of file Pet.h.
 { m_loading = load; }
References m_loading.
Referenced by WorldSession::HandleLoadPetFromDBSecondCallback().
setPetType()
void Pet::setPetType (PetType type) inline
Definition at line 66 of file Pet.h.
 { m_petType = type; }
References m_petType.
SynchronizeLevelWithOwner()
void Pet::SynchronizeLevelWithOwner ()
Definition at line 2084 of file Pet.cpp.
 {
     Unit* owner = GetOwner();
     if (!owner || owner->GetTypeId() != TYPEID_PLAYER)
         return;
     switch (getPetType())
     {
         // always same level
         case SUMMON_PET:
             GivePetLevel(owner->getLevel());
             break;
         // can't be greater owner level
         case HUNTER_PET:
             if (getLevel() > owner->getLevel())
                 GivePetLevel(owner->getLevel());
             else if (getLevel() + 5 < owner->getLevel())
                 GivePetLevel(owner->getLevel() - 5);
             break;
         default:
             break;
     }
 }
References Unit::getLevel(), GetOwner(), getPetType(), Object::GetTypeId(), GivePetLevel(), HUNTER_PET, SUMMON_PET, and TYPEID_PLAYER.
ToggleAutocast()
void Pet::ToggleAutocast (SpellInfo const * spellInfo, bool apply)
Definition at line 1935 of file Pet.cpp.
 {
     if (!spellInfo->IsAutocastable())
         return;
     uint32 spellid = spellInfo->Id;
     PetSpellMap::iterator itr = m_spells.find(spellid);
     if (itr == m_spells.end())
         return;
     uint32 i;
     if (apply)
     {
         for (i = 0; i < m_autospells.size() && m_autospells[i] != spellid; ++i)
             ;                                               // just search
         if (i == m_autospells.size())
         {
             m_autospells.push_back(spellid);
             if (itr->second.active != ACT_ENABLED)
             {
                 itr->second.active = ACT_ENABLED;
                 if (itr->second.state != PETSPELL_NEW)
                     itr->second.state = PETSPELL_CHANGED;
             }
         }
     }
     else
     {
         AutoSpellList::iterator itr2 = m_autospells.begin();
         for (i = 0; i < m_autospells.size() && m_autospells[i] != spellid; ++i, ++itr2)
             ;                                               // just search
         if (i < m_autospells.size())
         {
             m_autospells.erase(itr2);
             if (itr->second.active != ACT_DISABLED)
             {
                 itr->second.active = ACT_DISABLED;
                 if (itr->second.state != PETSPELL_NEW)
                     itr->second.state = PETSPELL_CHANGED;
             }
         }
     }
 }
References ACT_DISABLED, ACT_ENABLED, ByteConverter::apply(), SpellInfo::Id, SpellInfo::IsAutocastable(), m_autospells, m_spells, PETSPELL_CHANGED, and PETSPELL_NEW.
Referenced by addSpell(), and CleanupActionBar().
TryLoadFromDB()
SpellCastResult Pet::TryLoadFromDB (Player * owner, bool current = false, PetType mandatoryPetType = MAX_PET_TYPE, bool checkDead = false) static
Definition at line 118 of file Pet.cpp.
 {
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_CHAR_PET_BY_ENTRY_AND_SLOT_SYNS);
     stmt->setUInt32(0, owner->GetGUID().GetCounter());
     stmt->setUInt8(1, uint8(current ? PET_SAVE_AS_CURRENT : PET_SAVE_NOT_IN_SLOT));
     PreparedQueryResult result = CharacterDatabase.Query(stmt);
     if (!result)
         return SPELL_FAILED_NO_PET;
     Field* fields = result->Fetch();
     uint32 petentry = fields[1].GetUInt32();
     uint32 savedHealth = fields[10].GetUInt32();
     uint32 summon_spell_id = fields[15].GetUInt32();
     auto petType = PetType(fields[16].GetUInt8());
     // update for case of current pet "slot = 0"
     if (!petentry)
         return SPELL_FAILED_NO_PET;
     CreatureTemplate const* creatureInfo = sObjectMgr->GetCreatureTemplate(petentry);
     if (!creatureInfo)
     {
         LOG_ERROR("entities.pet", "Pet entry %u does not exist but used at pet load (owner: %s).", petentry, owner->GetName().c_str());
         return SPELL_FAILED_NO_PET;
     }
     SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(summon_spell_id);
     bool isTemporarySummoned = spellInfo && spellInfo->GetDuration() > 0;
     // check temporary summoned pets like mage water elemental
     if (current && isTemporarySummoned)
         return SPELL_FAILED_NO_PET;
     if (!checkDead)
     {
         if (!savedHealth)
         {
             owner->ToPlayer()->SendTameFailure(PET_TAME_DEAD);
             return SPELL_FAILED_TARGETS_DEAD;
         }
     }
     else if (savedHealth)
     {
         return SPELL_FAILED_TARGET_NOT_DEAD;
     }
     if (mandatoryPetType != MAX_PET_TYPE && petType != mandatoryPetType)
         return SPELL_FAILED_BAD_TARGETS;
     return SPELL_CAST_OK;
 }
References CHAR_SEL_CHAR_PET_BY_ENTRY_AND_SLOT_SYNS, CharacterDatabase, ObjectGuid::GetCounter(), SpellInfo::GetDuration(), Object::GetGUID(), WorldObject::GetName(), Field::GetUInt32(), isTemporarySummoned(), LOG_ERROR, MAX_PET_TYPE, PET_SAVE_AS_CURRENT, PET_SAVE_NOT_IN_SLOT, PET_TAME_DEAD, Unit::SendTameFailure(), PreparedStatementBase::setUInt32(), PreparedStatementBase::setUInt8(), sObjectMgr, SPELL_CAST_OK, SPELL_FAILED_BAD_TARGETS, SPELL_FAILED_NO_PET, SPELL_FAILED_TARGET_NOT_DEAD, SPELL_FAILED_TARGETS_DEAD, sSpellMgr, and Object::ToPlayer().
Referenced by Spell::CheckCast(), WorldSession::HandleStablePet(), WorldSession::HandleStableSwapPet(), and WorldSession::HandleUnstablePetCallback().
unlearnSpell()
bool Pet::unlearnSpell (uint32 spell_id, bool learn_prev, bool clear_ab = true)
Definition at line 1656 of file Pet.cpp.
 {
     if (removeSpell(spell_id, learn_prev, clear_ab))
     {
         if (!m_loading)
         {
             WorldPacket data(SMSG_PET_REMOVED_SPELL, 4);
             data << uint32(spell_id);
             m_owner->GetSession()->SendPacket(&data);
         }
         return true;
     }
     return false;
 }
References Player::GetSession(), m_loading, m_owner, removeSpell(), WorldSession::SendPacket(), and SMSG_PET_REMOVED_SPELL.
Referenced by addSpell(), InitLevelupSpellsForLevel(), and resetTalents().
Update()
void Pet::Update (uint32 diff) override virtual
Reimplemented from TempSummon.
Definition at line 397 of file Pet.cpp.
 {
     if (m_removed)                                           // pet already removed, just wait in remove queue, no updates
         return;
     if (m_loading)
         return;
     switch (m_deathState)
     {
         case CORPSE:
             {
                 if (getPetType() != HUNTER_PET || m_corpseRemoveTime <= time(nullptr))
                 {
                     Remove(PET_SAVE_NOT_IN_SLOT);               //hunters' pets never get removed because of death, NEVER!
                     return;
                 }
                 break;
             }
         case ALIVE:
             {
                 // unsummon pet that lost owner
                 Player* owner = GetOwner();
                 if (!owner || (!IsWithinDistInMap(owner, GetMap()->GetVisibilityRange()) && !isPossessed()) || (isControlled() && !owner->GetPetGUID()))
                     //if (!owner || (!IsWithinDistInMap(owner, GetMap()->GetVisibilityDistance()) && (owner->GetCharmGUID() && (owner->GetCharmGUID() != GetGUID()))) || (isControlled() && !owner->GetPetGUID()))
                 {
                     Remove(PET_SAVE_NOT_IN_SLOT, true);
                     return;
                 }
                 if (isControlled())
                 {
                     if (owner->GetPetGUID() != GetGUID())
                     {
                         LOG_ERROR("entities.pet", "Pet %u is not pet of owner %s, removed", GetEntry(), m_owner->GetName().c_str());
                         Remove(getPetType() == HUNTER_PET ? PET_SAVE_AS_DELETED : PET_SAVE_NOT_IN_SLOT);
                         return;
                     }
                 }
                 if (m_duration > 0)
                 {
                     if (uint32(m_duration) > diff)
                         m_duration -= diff;
                     else
                     {
                         Remove(getPetType() != SUMMON_PET ? PET_SAVE_AS_DELETED : PET_SAVE_NOT_IN_SLOT);
                         return;
                     }
                 }
                 // xinef: m_regenTimer is decrased in Creature::Update()
                 // xinef: just check if we can update focus in current period
                 if (getPowerType() == POWER_FOCUS)
                 {
                     m_petRegenTimer -= diff;
                     if (m_petRegenTimer <= int32(0))
                     {
                         m_petRegenTimer += PET_FOCUS_REGEN_INTERVAL;
                         Regenerate(POWER_FOCUS);
                     }
                 }
                 if (m_tempspell != 0)
                 {
                     Unit* tempspellTarget = m_tempspellTarget;
                     Unit* tempoldTarget = m_tempoldTarget;
                     bool tempspellIsPositive = m_tempspellIsPositive;
                     uint32 tempspell = m_tempspell;
                     Unit* charmer = GetCharmerOrOwner();
                     if (!charmer)
                         return;
                     if (!GetCharmInfo())
                         return;
                     if (tempspellTarget && tempspellTarget->IsAlive())
                     {
                         SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(tempspell);
                         if (!spellInfo)
                             return;
                         float max_range = GetSpellMaxRangeForTarget(tempspellTarget, spellInfo);
                         if (spellInfo->RangeEntry->type == SPELL_RANGE_MELEE)
                             max_range -= 2 * MIN_MELEE_REACH;
                         if (IsWithinLOSInMap(tempspellTarget) && GetDistance(tempspellTarget) < max_range)
{
                             if (!GetCharmInfo()->GetGlobalCooldownMgr().HasGlobalCooldown(spellInfo) && !HasSpellCooldown(tempspell))
{
                                 StopMoving();
                                 GetMotionMaster()->Clear(false);
                                 GetMotionMaster()->MoveIdle();
                                 GetCharmInfo()->SetIsCommandAttack(false);
                                 GetCharmInfo()->SetIsAtStay(true);
                                 GetCharmInfo()->SetIsCommandFollow(false);
                                 GetCharmInfo()->SetIsFollowing(false);
                                 GetCharmInfo()->SetIsReturning(false);
                                 GetCharmInfo()->SaveStayPosition(true);
                                 CastSpell(tempspellTarget, tempspell, false);
                                 m_tempspell = 0;
                                 m_tempspellTarget = nullptr;
                                 if (tempspellIsPositive)
{
                                     if (tempoldTarget && tempoldTarget->IsAlive())
{
                                         GetCharmInfo()->SetIsCommandAttack(true);
                                         GetCharmInfo()->SetIsAtStay(false);
                                         GetCharmInfo()->SetIsFollowing(false);
                                         GetCharmInfo()->SetIsCommandFollow(false);
                                         GetCharmInfo()->SetIsReturning(false);
                                         if (ToCreature() && ToCreature()->IsAIEnabled)
                                             ToCreature()->AI()->AttackStart(tempoldTarget);
                                     }
                                     else
{
                                         GetCharmInfo()->SetCommandState(COMMAND_FOLLOW);
                                         GetCharmInfo()->SetIsCommandAttack(false);
                                         GetCharmInfo()->SetIsAtStay(false);
                                         GetCharmInfo()->SetIsReturning(true);
                                         GetCharmInfo()->SetIsCommandFollow(true);
                                         GetCharmInfo()->SetIsFollowing(false);
                                         GetMotionMaster()->MoveFollow(charmer, PET_FOLLOW_DIST, GetFollowAngle());
                                     }
                                     m_tempoldTarget = nullptr;
                                     m_tempspellIsPositive = false;
                                 }
                             }
                         }
                     }
                     else
                     {
                         m_tempspell = 0;
                         m_tempspellTarget = nullptr;
                         m_tempoldTarget = nullptr;
                         m_tempspellIsPositive = false;
                         Unit* victim = charmer->GetVictim();
                         if (victim && victim->IsAlive())
{
                             StopMoving();
                             GetMotionMaster()->Clear(false);
                             GetMotionMaster()->MoveIdle();
                             GetCharmInfo()->SetIsCommandAttack(true);
                             GetCharmInfo()->SetIsAtStay(false);
                             GetCharmInfo()->SetIsFollowing(false);
                             GetCharmInfo()->SetIsCommandFollow(false);
                             GetCharmInfo()->SetIsReturning(false);
                             if (ToCreature() && ToCreature()->IsAIEnabled)
                                 ToCreature()->AI()->AttackStart(victim);
                         }
                         else
{
                             StopMoving();
                             GetMotionMaster()->Clear(false);
                             GetMotionMaster()->MoveIdle();
                             GetCharmInfo()->SetCommandState(COMMAND_FOLLOW);
                             GetCharmInfo()->SetIsCommandAttack(false);
                             GetCharmInfo()->SetIsAtStay(false);
                             GetCharmInfo()->SetIsReturning(true);
                             GetCharmInfo()->SetIsCommandFollow(true);
                             GetCharmInfo()->SetIsFollowing(false);
                             GetMotionMaster()->MoveFollow(charmer, PET_FOLLOW_DIST, GetFollowAngle());
                         }
                     }
                 }
                 if (getPetType() == HUNTER_PET)
                 {
                     m_happinessTimer -= diff;
                     if (m_happinessTimer <= int32(0))
                     {
                         LoseHappiness();
                         m_happinessTimer += PET_LOSE_HAPPINES_INTERVAL;
                     }
                 }
                 break;
             }
         default:
             break;
     }
     Creature::Update(diff);
 }
References Creature::AI(), ALIVE, UnitAI::AttackStart(), Unit::CastSpell(), MotionMaster::Clear(), COMMAND_FOLLOW, CORPSE, Unit::GetCharmerOrOwner(), Unit::GetCharmInfo(), WorldObject::GetDistance(), Object::GetEntry(), Minion::GetFollowAngle(), Object::GetGUID(), WorldObject::GetMap(), Unit::GetMotionMaster(), WorldObject::GetName(), GetOwner(), Unit::GetPetGUID(), getPetType(), Unit::getPowerType(), Unit::GetSpellMaxRangeForTarget(), Unit::GetVictim(), WorldObject::GetVisibilityRange(), Creature::HasSpellCooldown(), HUNTER_PET, Unit::IsAIEnabled, Unit::IsAlive(), isControlled(), Unit::isPossessed(), WorldObject::IsWithinDistInMap(), WorldObject::IsWithinLOSInMap(), LOG_ERROR, LoseHappiness(), Creature::m_corpseRemoveTime, Unit::m_deathState, m_duration, m_happinessTimer, m_loading, m_owner, m_petRegenTimer, m_removed, m_tempoldTarget, m_tempspell, m_tempspellIsPositive, m_tempspellTarget, MIN_MELEE_REACH, MotionMaster::MoveFollow(), MotionMaster::MoveIdle(), PET_FOCUS_REGEN_INTERVAL, PET_FOLLOW_DIST, PET_LOSE_HAPPINES_INTERVAL, PET_SAVE_AS_DELETED, PET_SAVE_NOT_IN_SLOT, POWER_FOCUS, SpellInfo::RangeEntry, Creature::Regenerate(), Remove(), CharmInfo::SaveStayPosition(), CharmInfo::SetCommandState(), CharmInfo::SetIsAtStay(), CharmInfo::SetIsCommandAttack(), CharmInfo::SetIsCommandFollow(), CharmInfo::SetIsFollowing(), CharmInfo::SetIsReturning(), SPELL_RANGE_MELEE, sSpellMgr, Unit::StopMoving(), SUMMON_PET, Object::ToCreature(), SpellRangeEntry::type, and Creature::Update().
Member Data Documentation
asynchLoadType
uint8 Pet::asynchLoadType protected
Definition at line 188 of file Pet.h.
Referenced by GetAsynchLoadType(), HandleAsynchLoadFailed(), LoadPetFromDB(), and SetAsynchLoadType().
m_auraRaidUpdateMask
uint64 Pet::m_auraRaidUpdateMask protected
Definition at line 177 of file Pet.h.
Referenced by GetAuraUpdateMaskForRaid(), ResetAuraUpdateMaskForRaid(), and SetAuraUpdateMaskForRaid().
m_autospells
AutoSpellList Pet::m_autospells
Definition at line 144 of file Pet.h.
Referenced by GetPetAutoSpellOnPos(), GetPetAutoSpellSize(), and ToggleAutocast().
m_declinedname
DeclinedName* Pet::m_declinedname protected
Definition at line 181 of file Pet.h.
Referenced by GetDeclinedNames(), and ~Pet().
m_duration
int32 Pet::m_duration protected
Definition at line 176 of file Pet.h.
Referenced by GetDuration(), isTemporarySummoned(), SetDuration(), and Update().
m_happinessTimer
int32 Pet::m_happinessTimer protected
Definition at line 174 of file Pet.h.
Referenced by Update().
m_loading
bool Pet::m_loading protected
Definition at line 178 of file Pet.h.
Referenced by addSpell(), InitTalentForLevel(), isBeingLoaded(), learnSpell(), removeSpell(), resetTalents(), SavePetToDB(), SetLoading(), unlearnSpell(), and Update().
m_owner
Player* Pet::m_owner protected
Definition at line 173 of file Pet.h.
Referenced by GetOwner(), learnSpell(), Remove(), unlearnSpell(), and Update().
m_petRegenTimer
int32 Pet::m_petRegenTimer protected
Definition at line 179 of file Pet.h.
Referenced by Update().
m_petType
PetType Pet::m_petType protected
Definition at line 175 of file Pet.h.
Referenced by getPetType(), and setPetType().
m_removed
bool Pet::m_removed
Definition at line 164 of file Pet.h.
Referenced by Player::RemovePet(), and Update().
m_spells
PetSpellMap Pet::m_spells
Definition at line 143 of file Pet.h.
Referenced by _SaveSpells(), addSpell(), HasSpell(), InitPetCreateSpells(), Player::PetSpellInitialize(), removeSpell(), resetTalents(), and ToggleAutocast().
m_tempoldTarget
Unit* Pet::m_tempoldTarget protected
Definition at line 184 of file Pet.h.
Referenced by CastWhenWillAvailable(), ClearCastWhenWillAvailable(), and Update().
m_tempspell
uint32 Pet::m_tempspell protected
Definition at line 186 of file Pet.h.
Referenced by CastWhenWillAvailable(), ClearCastWhenWillAvailable(), and Update().
m_tempspellIsPositive
bool Pet::m_tempspellIsPositive protected
Definition at line 185 of file Pet.h.
Referenced by CastWhenWillAvailable(), ClearCastWhenWillAvailable(), and Update().
m_tempspellTarget
Unit* Pet::m_tempspellTarget protected
Definition at line 183 of file Pet.h.
Referenced by CastWhenWillAvailable(), ClearCastWhenWillAvailable(), and Update().
m_usedTalentCount
uint32 Pet::m_usedTalentCount
Definition at line 156 of file Pet.h.
Referenced by addSpell(), InitTalentForLevel(), removeSpell(), Player::ResetPetTalents(), and resetTalents().
The documentation for this class was generated from the following files:
src/server/game/Entities/Pet/Pet.h
src/server/game/Entities/Pet/Pet.cpp