Azerotcore-wotlk: TransportBase Class Reference
TransportBase Class Reference abstract
#include <VehicleDefines.h>
Public Member Functions
virtual void CalculatePassengerPosition (float &x, float &y, float &z, float *o=nullptr) const =0
This method transforms supplied transport offsets into global coordinates.
virtual void CalculatePassengerOffset (float &x, float &y, float &z, float *o=nullptr) const =0
This method transforms supplied global coordinates into local offsets.
Protected Member Functions
TransportBase ()=default
virtual ~TransportBase ()=default
Static Protected Member Functions
static void CalculatePassengerPosition (float &x, float &y, float &z, float *o, float transX, float transY, float transZ, float transO)
static void CalculatePassengerOffset (float &x, float &y, float &z, float *o, float transX, float transY, float transZ, float transO)
Detailed Description
Definition at line 106 of file VehicleDefines.h.
Constructor & Destructor Documentation
TransportBase()
TransportBase::TransportBase () protected default
~TransportBase()
virtual TransportBase::~TransportBase () protected virtual default
Member Function Documentation
CalculatePassengerOffset() [1/2]
static void TransportBase::CalculatePassengerOffset (float & x, float & y, float & z, float * o, float transX, float transY, float transZ, float transO) inline static protected
Definition at line 131 of file VehicleDefines.h.
     {
         if (o)
             *o = Position::NormalizeOrientation(*o - transO);
         z -= transZ;
         y -= transY;    // y = searchedY * std::cos(o) + searchedX * std::sin(o)
         x -= transX;    // x = searchedX * std::cos(o) + searchedY * std::sin(o + pi)
         float inx = x, iny = y;
         y = (iny - inx * std::tan(transO)) / (std::cos(transO) + std::sin(transO) * std::tan(transO));
         x = (inx + iny * std::tan(transO)) / (std::cos(transO) + std::sin(transO) * std::tan(transO));
     }
References Position::NormalizeOrientation().
CalculatePassengerOffset() [2/2]
virtual void TransportBase::CalculatePassengerOffset (float & x, float & y, float & z, float * o = nullptr) const pure virtual
This method transforms supplied global coordinates into local offsets.
Implemented in Transport, and Vehicle.
Referenced by Vehicle::CalculatePassengerOffset(), and Transport::CalculatePassengerOffset().
CalculatePassengerPosition() [1/2]
static void TransportBase::CalculatePassengerPosition (float & x, float & y, float & z, float * o, float transX, float transY, float transZ, float transO) inline static protected
Definition at line 120 of file VehicleDefines.h.
     {
         float inx = x, iny = y, inz = z;
         if (o)
             *o = Position::NormalizeOrientation(transO + *o);
         x = transX + inx * std::cos(transO) - iny * std::sin(transO);
         y = transY + iny * std::cos(transO) + inx * std::sin(transO);
         z = transZ + inz;
     }
References Position::NormalizeOrientation().
CalculatePassengerPosition() [2/2]
virtual void TransportBase::CalculatePassengerPosition (float & x, float & y, float & z, float * o = nullptr) const pure virtual
This method transforms supplied transport offsets into global coordinates.
Implemented in Transport, and Vehicle.
Referenced by Vehicle::CalculatePassengerPosition(), Transport::CalculatePassengerPosition(), MotionTransport::DelayedTeleportTransport(), and MotionTransport::TeleportTransport().
The documentation for this class was generated from the following file:
src/server/game/Entities/Vehicle/VehicleDefines.h