Azerotcore-wotlk: deps/jemalloc/src/util.c File Reference
util.c File Reference
#include "jemalloc/internal/jemalloc_internal.h"
Macros
#define assert(e)
#define not_reached()
#define not_implemented()
#define JEMALLOC_UTIL_C_
#define U2S_BUFSIZE ((1U << (LG_SIZEOF_INTMAX_T + 3)) + 1)
#define D2S_BUFSIZE (1 + U2S_BUFSIZE)
#define O2S_BUFSIZE (1 + U2S_BUFSIZE)
#define X2S_BUFSIZE (2 + U2S_BUFSIZE)
#define APPEND_C(c)
#define APPEND_S(s, slen)
#define APPEND_PADDED_S(s, slen, width, left_justify)
#define GET_ARG_NUMERIC(val, len)
Functions
static void wrtmessage (void *cbopaque, const char *s)
static char * u2s (uintmax_t x, unsigned base, bool uppercase, char *s, size_t *slen_p)
static char * d2s (intmax_t x, char sign, char *s, size_t *slen_p)
static char * o2s (uintmax_t x, bool alt_form, char *s, size_t *slen_p)
static char * x2s (uintmax_t x, bool alt_form, bool uppercase, char *s, size_t *slen_p)
void malloc_write (const char *s)
int buferror (int err, char *buf, size_t buflen)
uintmax_t malloc_strtoumax (const char *restrict nptr, char **restrict endptr, int base)
int malloc_vsnprintf (char *str, size_t size, const char *format, va_list ap)
int malloc_snprintf (char *str, size_t size, const char *format,...)
void malloc_vcprintf (void(*write_cb)(void *, const char *), void *cbopaque, const char *format, va_list ap)
void malloc_cprintf (void(*write_cb)(void *, const char *), void *cbopaque, const char *format,...)
void malloc_printf (const char *format,...)
Variables
JEMALLOC_EXPORT void(* je_malloc_message)(void *, const char *s)
Macro Definition Documentation
APPEND_C
#define APPEND_C (c)
Value:
    do {                        \
    if (i < size)                           \
        str[i] = (c);                       \
    i++;                                \
} while (0)
APPEND_PADDED_S
#define APPEND_PADDED_S (s, slen, width, left_justify)
Value:
    do {        \
    /* Left padding. */                     \
    size_t pad_len = (width == -1) ? 0 : ((slen < (size_t)width) ?  \
        (size_t)width - slen : 0);                  \
    if (left_justify == false && pad_len != 0) {            \
        size_t j;                       \
        for (j = 0; j < pad_len; j++)               \
            APPEND_C(' ');                  \
    }                               \
    /* Value. */                            \
    APPEND_S(s, slen);                      \
    /* Right padding. */                        \
    if (left_justify && pad_len != 0) {             \
        size_t j;                       \
        for (j = 0; j < pad_len; j++)               \
            APPEND_C(' ');                  \
    }                               \
} while (0)
APPEND_S
#define APPEND_S (s, slen)
Value:
    do {                        \
    if (i < size) {                         \
        size_t cpylen = (slen <= size - i) ? slen : size - i;   \
        memcpy(&str[i], s, cpylen);             \
    }                               \
    i += slen;                          \
} while (0)
assert
#define assert (e)
Value:
    do {                            \
    if (config_debug && !(e)) {                 \
        malloc_write("<jemalloc>: Failed assertion\n");     \
        abort();                        \
    }                               \
} while (0)
Definition at line 1 of file util.c.
D2S_BUFSIZE
#define D2S_BUFSIZE (1 + U2S_BUFSIZE)
Definition at line 32 of file util.c.
GET_ARG_NUMERIC
#define GET_ARG_NUMERIC (val, len)
JEMALLOC_UTIL_C_
#define JEMALLOC_UTIL_C_
Definition at line 22 of file util.c.
not_implemented
#define not_implemented ()
Value:
    do {                        \
    if (config_debug) {                     \
        malloc_write("<jemalloc>: Not implemented\n");      \
        abort();                        \
    }                               \
} while (0)
Definition at line 15 of file util.c.
not_reached
#define not_reached ()
Value:
    do {                        \
    if (config_debug) {                     \
        malloc_write("<jemalloc>: Unreachable code reached\n"); \
        abort();                        \
    }                               \
} while (0)
Definition at line 8 of file util.c.
O2S_BUFSIZE
#define O2S_BUFSIZE (1 + U2S_BUFSIZE)
Definition at line 34 of file util.c.
U2S_BUFSIZE
#define U2S_BUFSIZE ((1U << (LG_SIZEOF_INTMAX_T + 3)) + 1)
Definition at line 29 of file util.c.
X2S_BUFSIZE
#define X2S_BUFSIZE (2 + U2S_BUFSIZE)
Definition at line 36 of file util.c.
Function Documentation
buferror()
int buferror (int err, char * buf, size_t buflen)
Definition at line 80 of file util.c.
 {
 #ifdef _WIN32
     FormatMessageA(FORMAT_MESSAGE_FROM_SYSTEM, NULL, GetLastError(), 0,
         (LPSTR)buf, buflen, NULL);
     return (0);
 #elif defined(_GNU_SOURCE)
     char *b = strerror_r(err, buf, buflen);
     if (b != buf) {
         strncpy(buf, b, buflen);
         buf[buflen-1] = '\0';
     }
     return (0);
 #else
     return (strerror_r(err, buf, buflen));
 #endif
 }
References b, and NULL.
d2s()
static char * d2s (intmax_t x, char sign, char * s, size_t * slen_p) static
Definition at line 258 of file util.c.
 {
     bool neg;
     if ((neg = (x < 0)))
         x = -x;
     s = u2s(x, 10, false, s, slen_p);
     if (neg)
         sign = '-';
     switch (sign) {
     case '-':
         if (neg == false)
             break;
         /* Fall through. */
     case ' ':
     case '+':
         s--;
         (*slen_p)++;
         *s = sign;
         break;
     default: not_reached();
     }
     return (s);
 }
References not_reached, G3D::sign(), u2s(), and G3D::x.
Referenced by malloc_vsnprintf().
malloc_cprintf()
void malloc_cprintf (void(*)(void *, const char *) write_cb, void * cbopaque, const char * format, ...)
Definition at line 628 of file util.c.
 {
     va_list ap;
     va_start(ap, format);
     malloc_vcprintf(write_cb, cbopaque, format, ap);
     va_end(ap);
 }
References format(), and malloc_vcprintf().
malloc_printf()
void malloc_printf (const char * format, ...)
Definition at line 641 of file util.c.
 {
     va_list ap;
     va_start(ap, format);
     malloc_vcprintf(NULL, NULL, format, ap);
     va_end(ap);
 }
References format(), malloc_vcprintf(), and NULL.
malloc_snprintf()
int malloc_snprintf (char * str, size_t size, const char * format, ...)
Definition at line 589 of file util.c.
 {
     int ret;
     va_list ap;
     va_start(ap, format);
     ret = malloc_vsnprintf(str, size, format, ap);
     va_end(ap);
     return (ret);
 }
References format(), malloc_vsnprintf(), and ret.
malloc_strtoumax()
uintmax_t malloc_strtoumax (const char *restrict nptr, char **restrict endptr, int base)
Definition at line 100 of file util.c.
 {
     uintmax_t ret, digit;
     int b;
     bool neg;
     const char *p, *ns;
     p = nptr;
     if (base < 0 || base == 1 || base > 36) {
         ns = p;
         set_errno(EINVAL);
         ret = UINTMAX_MAX;
         goto label_return;
     }
     b = base;
     /* Swallow leading whitespace and get sign, if any. */
     neg = false;
     while (true) {
         switch (*p) {
         case '\t': case '\n': case '\v': case '\f': case '\r': case ' ':
             p++;
             break;
         case '-':
             neg = true;
             /* Fall through. */
         case '+':
             p++;
             /* Fall through. */
         default:
             goto label_prefix;
         }
     }
     /* Get prefix, if any. */
     label_prefix:
     /*
      * Note where the first non-whitespace/sign character is so that it is
      * possible to tell whether any digits are consumed (e.g., "  0" vs.
      * "  -x").
      */
     ns = p;
     if (*p == '0') {
         switch (p[1]) {
         case '0': case '1': case '2': case '3': case '4': case '5':
         case '6': case '7':
             if (b == 0)
                 b = 8;
             if (b == 8)
                 p++;
             break;
         case 'X': case 'x':
             switch (p[2]) {
             case '0': case '1': case '2': case '3': case '4':
             case '5': case '6': case '7': case '8': case '9':
             case 'A': case 'B': case 'C': case 'D': case 'E':
             case 'F':
             case 'a': case 'b': case 'c': case 'd': case 'e':
             case 'f':
                 if (b == 0)
                     b = 16;
                 if (b == 16)
                     p += 2;
                 break;
             default:
                 break;
             }
             break;
         default:
             p++;
             ret = 0;
             goto label_return;
         }
     }
     if (b == 0)
         b = 10;
     /* Convert. */
     ret = 0;
     while ((*p >= '0' && *p <= '9' && (digit = *p - '0') < b)
         || (*p >= 'A' && *p <= 'Z' && (digit = 10 + *p - 'A') < b)
         || (*p >= 'a' && *p <= 'z' && (digit = 10 + *p - 'a') < b)) {
         uintmax_t pret = ret;
         ret *= b;
         ret += digit;
         if (ret < pret) {
             /* Overflow. */
             set_errno(ERANGE);
             ret = UINTMAX_MAX;
             goto label_return;
         }
         p++;
     }
     if (neg)
         ret = -ret;
     if (p == ns) {
         /* No conversion performed. */
         set_errno(EINVAL);
         ret = UINTMAX_MAX;
         goto label_return;
     }
 label_return:
     if (endptr != NULL) {
         if (p == ns) {
             /* No characters were converted. */
             *endptr = (char *)nptr;
         } else
             *endptr = (char *)p;
     }
     return (ret);
 }
References b, NULL, ret, set_errno(), and UINTMAX_MAX.
Referenced by malloc_vsnprintf().
malloc_vcprintf()
void malloc_vcprintf (void(*)(void *, const char *) write_cb, void * cbopaque, const char * format, va_list ap)
Definition at line 602 of file util.c.
 {
     char buf[MALLOC_PRINTF_BUFSIZE];
     if (write_cb == NULL) {
         /*
          * The caller did not provide an alternate write_cb callback
          * function, so use the default one.  malloc_write() is an
          * inline function, so use malloc_message() directly here.
          */
         write_cb = (je_malloc_message != NULL) ? je_malloc_message :
             wrtmessage;
         cbopaque = NULL;
     }
     malloc_vsnprintf(buf, sizeof(buf), format, ap);
     write_cb(cbopaque, buf);
 }
References format(), je_malloc_message, MALLOC_PRINTF_BUFSIZE, malloc_vsnprintf(), NULL, and wrtmessage().
Referenced by malloc_cprintf(), and malloc_printf().
malloc_vsnprintf()
int malloc_vsnprintf (char * str, size_t size, const char * format, va_list ap)
Definition at line 310 of file util.c.
 {
     int ret;
     size_t i;
     const char *f;
 #define APPEND_C(c) do {                        \
     if (i < size)                           \
         str[i] = (c);                       \
     i++;                                \
 } while (0)
 #define APPEND_S(s, slen) do {                      \
     if (i < size) {                         \
         size_t cpylen = (slen <= size - i) ? slen : size - i;   \
         memcpy(&str[i], s, cpylen);             \
     }                               \
     i += slen;                          \
 } while (0)
 #define APPEND_PADDED_S(s, slen, width, left_justify) do {      \
     /* Left padding. */                     \
     size_t pad_len = (width == -1) ? 0 : ((slen < (size_t)width) ?  \
         (size_t)width - slen : 0);                  \
     if (left_justify == false && pad_len != 0) {            \
         size_t j;                       \
         for (j = 0; j < pad_len; j++)               \
             APPEND_C(' ');                  \
     }                               \
     /* Value. */                            \
     APPEND_S(s, slen);                      \
     /* Right padding. */                        \
     if (left_justify && pad_len != 0) {             \
         size_t j;                       \
         for (j = 0; j < pad_len; j++)               \
             APPEND_C(' ');                  \
     }                               \
 } while (0)
 #define GET_ARG_NUMERIC(val, len) do {                  \
     switch (len) {                          \
     case '?':                           \
         val = va_arg(ap, int);                  \
         break;                          \
     case '?' | 0x80:                        \
         val = va_arg(ap, unsigned int);             \
         break;                          \
     case 'l':                           \
         val = va_arg(ap, long);                 \
         break;                          \
     case 'l' | 0x80:                        \
         val = va_arg(ap, unsigned long);            \
         break;                          \
     case 'q':                           \
         val = va_arg(ap, long long);                \
         break;                          \
     case 'q' | 0x80:                        \
         val = va_arg(ap, unsigned long long);           \
         break;                          \
     case 'j':                           \
         val = va_arg(ap, intmax_t);             \
         break;                          \
     case 'j' | 0x80:                        \
         val = va_arg(ap, uintmax_t);                \
         break;                          \
     case 't':                           \
         val = va_arg(ap, ptrdiff_t);                \
         break;                          \
     case 'z':                           \
         val = va_arg(ap, ssize_t);              \
         break;                          \
     case 'z' | 0x80:                        \
         val = va_arg(ap, size_t);               \
         break;                          \
     case 'p': /* Synthetic; used for %p. */             \
         val = va_arg(ap, uintptr_t);                \
         break;                          \
     default: not_reached();                     \
     }                               \
 } while (0)
     i = 0;
     f = format;
     while (true) {
         switch (*f) {
         case '\0': goto label_out;
         case '%': {
             bool alt_form = false;
             bool left_justify = false;
             bool plus_space = false;
             bool plus_plus = false;
             int prec = -1;
             int width = -1;
             unsigned char len = '?';
             f++;
             /* Flags. */
             while (true) {
                 switch (*f) {
                 case '#':
                     assert(alt_form == false);
                     alt_form = true;
                     break;
                 case '-':
                     assert(left_justify == false);
                     left_justify = true;
                     break;
                 case ' ':
                     assert(plus_space == false);
                     plus_space = true;
                     break;
                 case '+':
                     assert(plus_plus == false);
                     plus_plus = true;
                     break;
                 default: goto label_width;
                 }
                 f++;
             }
             /* Width. */
             label_width:
             switch (*f) {
             case '*':
                 width = va_arg(ap, int);
                 f++;
                 if (width < 0) {
                     left_justify = true;
                     width = -width;
                 }
                 break;
             case '0': case '1': case '2': case '3': case '4':
             case '5': case '6': case '7': case '8': case '9': {
                 uintmax_t uwidth;
                 set_errno(0);
                 uwidth = malloc_strtoumax(f, (char **)&f, 10);
                 assert(uwidth != UINTMAX_MAX || get_errno() !=
                     ERANGE);
                 width = (int)uwidth;
                 break;
             } default:
                 break;
             }
             /* Width/precision separator. */
             if (*f == '.')
                 f++;
             else
                 goto label_length;
             /* Precision. */
             switch (*f) {
             case '*':
                 prec = va_arg(ap, int);
                 f++;
                 break;
             case '0': case '1': case '2': case '3': case '4':
             case '5': case '6': case '7': case '8': case '9': {
                 uintmax_t uprec;
                 set_errno(0);
                 uprec = malloc_strtoumax(f, (char **)&f, 10);
                 assert(uprec != UINTMAX_MAX || get_errno() !=
                     ERANGE);
                 prec = (int)uprec;
                 break;
             }
             default: break;
             }
             /* Length. */
             label_length:
             switch (*f) {
             case 'l':
                 f++;
                 if (*f == 'l') {
                     len = 'q';
                     f++;
                 } else
                     len = 'l';
                 break;
             case 'q': case 'j': case 't': case 'z':
                 len = *f;
                 f++;
                 break;
             default: break;
             }
             /* Conversion specifier. */
             switch (*f) {
                 char *s;
                 size_t slen;
             case '%':
                 /* %% */
                 APPEND_C(*f);
                 f++;
                 break;
             case 'd': case 'i': {
                 intmax_t val JEMALLOC_CC_SILENCE_INIT(0);
                 char buf[D2S_BUFSIZE];
                 GET_ARG_NUMERIC(val, len);
                 s = d2s(val, (plus_plus ? '+' : (plus_space ?
                     ' ' : '-')), buf, &slen);
                 APPEND_PADDED_S(s, slen, width, left_justify);
                 f++;
                 break;
             } case 'o': {
                 uintmax_t val JEMALLOC_CC_SILENCE_INIT(0);
                 char buf[O2S_BUFSIZE];
                 GET_ARG_NUMERIC(val, len | 0x80);
                 s = o2s(val, alt_form, buf, &slen);
                 APPEND_PADDED_S(s, slen, width, left_justify);
                 f++;
                 break;
             } case 'u': {
                 uintmax_t val JEMALLOC_CC_SILENCE_INIT(0);
                 char buf[U2S_BUFSIZE];
                 GET_ARG_NUMERIC(val, len | 0x80);
                 s = u2s(val, 10, false, buf, &slen);
                 APPEND_PADDED_S(s, slen, width, left_justify);
                 f++;
                 break;
             } case 'x': case 'X': {
                 uintmax_t val JEMALLOC_CC_SILENCE_INIT(0);
                 char buf[X2S_BUFSIZE];
                 GET_ARG_NUMERIC(val, len | 0x80);
                 s = x2s(val, alt_form, *f == 'X', buf, &slen);
                 APPEND_PADDED_S(s, slen, width, left_justify);
                 f++;
                 break;
             } case 'c': {
                 unsigned char val;
                 char buf[2];
                 assert(len == '?' || len == 'l');
                 assert_not_implemented(len != 'l');
                 val = va_arg(ap, int);
                 buf[0] = val;
                 buf[1] = '\0';
                 APPEND_PADDED_S(buf, 1, width, left_justify);
                 f++;
                 break;
             } case 's':
                 assert(len == '?' || len == 'l');
                 assert_not_implemented(len != 'l');
                 s = va_arg(ap, char *);
                 slen = (prec < 0) ? strlen(s) : prec;
                 APPEND_PADDED_S(s, slen, width, left_justify);
                 f++;
                 break;
             case 'p': {
                 uintmax_t val;
                 char buf[X2S_BUFSIZE];
                 GET_ARG_NUMERIC(val, 'p');
                 s = x2s(val, true, false, buf, &slen);
                 APPEND_PADDED_S(s, slen, width, left_justify);
                 f++;
                 break;
             } default: not_reached();
             }
             break;
         } default: {
             APPEND_C(*f);
             f++;
             break;
         }}
     }
     label_out:
     if (i < size)
         str[i] = '\0';
     else
         str[size - 1] = '\0';
     ret = i;
 #undef APPEND_C
 #undef APPEND_S
 #undef APPEND_PADDED_S
 #undef GET_ARG_NUMERIC
     return (ret);
 }
References APPEND_C, APPEND_PADDED_S, assert, assert_not_implemented, d2s(), D2S_BUFSIZE, f(), format(), GET_ARG_NUMERIC, get_errno(), JEMALLOC_CC_SILENCE_INIT, malloc_strtoumax(), not_reached, o2s(), O2S_BUFSIZE, ret, set_errno(), u2s(), U2S_BUFSIZE, UINTMAX_MAX, width, x2s(), and X2S_BUFSIZE.
Referenced by malloc_snprintf(), and malloc_vcprintf().
malloc_write()
void malloc_write (const char * s)
Definition at line 66 of file util.c.
 {
     if (je_malloc_message != NULL)
         je_malloc_message(NULL, s);
     else
         wrtmessage(NULL, s);
 }
References je_malloc_message, NULL, and wrtmessage().
o2s()
static char * o2s (uintmax_t x, bool alt_form, char * s, size_t * slen_p) static
Definition at line 284 of file util.c.
 {
     s = u2s(x, 8, false, s, slen_p);
     if (alt_form && *s != '0') {
         s--;
         (*slen_p)++;
         *s = '0';
     }
     return (s);
 }
References u2s(), and G3D::x.
Referenced by malloc_vsnprintf().
u2s()
static char * u2s (uintmax_t x, unsigned base, bool uppercase, char * s, size_t * slen_p) static
Definition at line 215 of file util.c.
 {
     unsigned i;
     i = U2S_BUFSIZE - 1;
     s[i] = '\0';
     switch (base) {
     case 10:
         do {
             i--;
             s[i] = "0123456789"[x % (uint64_t)10];
             x /= (uint64_t)10;
         } while (x > 0);
         break;
     case 16: {
         const char *digits = (uppercase)
             ? "0123456789ABCDEF"
             : "0123456789abcdef";
         do {
             i--;
             s[i] = digits[x & 0xf];
             x >>= 4;
         } while (x > 0);
         break;
     } default: {
         const char *digits = (uppercase)
             ? "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
             : "0123456789abcdefghijklmnopqrstuvwxyz";
         assert(base >= 2 && base <= 36);
         do {
             i--;
             s[i] = digits[x % (uint64_t)base];
             x /= (uint64_t)base;
         } while (x > 0);
     }}
     *slen_p = U2S_BUFSIZE - 1 - i;
     return (&s[i]);
 }
References assert, U2S_BUFSIZE, and G3D::x.
Referenced by d2s(), malloc_vsnprintf(), o2s(), and x2s().
wrtmessage()
static void wrtmessage (void * cbopaque, const char * s) static
Definition at line 44 of file util.c.
 {
 #ifdef SYS_write
     /*
      * Use syscall(2) rather than write(2) when possible in order to avoid
      * the possibility of memory allocation within libc.  This is necessary
      * on FreeBSD; most operating systems do not have this problem though.
      */
     UNUSED int result = syscall(SYS_write, STDERR_FILENO, s, strlen(s));
 #else
     UNUSED int result = write(STDERR_FILENO, s, strlen(s));
 #endif
 }
References UNUSED, and write.
Referenced by malloc_vcprintf(), and malloc_write().
x2s()
static char * x2s (uintmax_t x, bool alt_form, bool uppercase, char * s, size_t * slen_p) static
Definition at line 297 of file util.c.
 {
     s = u2s(x, 16, uppercase, s, slen_p);
     if (alt_form) {
         s -= 2;
         (*slen_p) += 2;
         memcpy(s, uppercase ? "0X" : "0x", 2);
     }
     return (s);
 }
References memcpy, u2s(), and G3D::x.
Referenced by malloc_vsnprintf().
Variable Documentation
je_malloc_message
JEMALLOC_EXPORT void(* je_malloc_message) (void *, const char *s) (void * cbopaque, const char * s)
Definition at line 59 of file util.c.
Referenced by malloc_vcprintf(), and malloc_write().