Azerotcore-wotlk: npc_harrison_jones::npc_harrison_jonesAI Struct Reference
npc_harrison_jones::npc_harrison_jonesAI Struct Reference
Public Member Functions
npc_harrison_jonesAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *) override
void sGossipSelect (Player *player, uint32 sender, uint32 action) override
void SpellHit (Unit *, const SpellInfo *spell) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * instance
uint8 _gongEvent
uint32 _gongTimer
ObjectGuid uiTargetGUID
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 601 of file zulaman.cpp.
Constructor & Destructor Documentation
npc_harrison_jonesAI()
npc_harrison_jones::npc_harrison_jonesAI::npc_harrison_jonesAI (Creature * creature) inline
Definition at line 603 of file zulaman.cpp.
                                                  : ScriptedAI(creature)
         {
             instance = creature->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), and instance.
Member Function Documentation
EnterCombat()
void npc_harrison_jones::npc_harrison_jonesAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 621 of file zulaman.cpp.
 { }
Reset()
void npc_harrison_jones::npc_harrison_jonesAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 614 of file zulaman.cpp.
         {
             _gongEvent = 0;
             _gongTimer = 0;
             uiTargetGUID.Clear();
         }
References _gongEvent, _gongTimer, ObjectGuid::Clear(), and uiTargetGUID.
sGossipSelect()
void npc_harrison_jones::npc_harrison_jonesAI::sGossipSelect (Player * player, uint32 sender, uint32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 623 of file zulaman.cpp.
         {
             if (me->GetCreatureTemplate()->GossipMenuId == sender && !action)
             {
                 CloseGossipMenuFor(player);
                 me->SetFacingToObject(player);
                 me->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
                 Talk(SAY_HARRISON_0);
                 _gongEvent = GONG_EVENT_1;
                 _gongTimer = 4000;
             }
         }
References _gongEvent, _gongTimer, CloseGossipMenuFor(), Creature::GetCreatureTemplate(), GONG_EVENT_1, CreatureTemplate::GossipMenuId, ScriptedAI::me, Object::RemoveFlag(), SAY_HARRISON_0, Unit::SetFacingToObject(), CreatureAI::Talk(), UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
SpellHit()
void npc_harrison_jones::npc_harrison_jonesAI::SpellHit (Unit * , const SpellInfo * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 636 of file zulaman.cpp.
         {
             if (spell->Id == SPELL_COSMETIC_SPEAR_THROW)
             {
                 me->RemoveAllAuras();
                 me->SetEntry(NPC_HARRISON_JONES_2);
                 me->SetDisplayId(MODEL_HARRISON_JONES_2);
                 me->SetTarget();
                 me->SetByteValue(UNIT_FIELD_BYTES_1, UNIT_BYTES_1_OFFSET_STAND_STATE, UNIT_STAND_STATE_DEAD);
                 me->SetFlag(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_DEAD);
                 instance->SetData(DATA_GONGEVENT, DONE);
             }
         }
References DATA_GONGEVENT, DONE, SpellInfo::Id, instance, ScriptedAI::me, MODEL_HARRISON_JONES_2, NPC_HARRISON_JONES_2, Unit::RemoveAllAuras(), Object::SetByteValue(), ZoneScript::SetData(), Creature::SetDisplayId(), Object::SetEntry(), Object::SetFlag(), Creature::SetTarget(), SPELL_COSMETIC_SPEAR_THROW, UNIT_BYTES_1_OFFSET_STAND_STATE, UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_DEAD, UNIT_FIELD_BYTES_1, and UNIT_STAND_STATE_DEAD.
UpdateAI()
void npc_harrison_jones::npc_harrison_jonesAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 650 of file zulaman.cpp.
         {
             if (_gongEvent)
             {
                 if (_gongTimer <= diff)
                 {
                     switch (_gongEvent)
                     {
                         case GONG_EVENT_1:
                             me->GetMotionMaster()->MovePath(HARRISON_MOVE_1, false);
                             _gongEvent = GONG_EVENT_2;
                             _gongTimer = 12000;
                             break;
                         case GONG_EVENT_2:
                             me->SetFacingTo(6.235659f);
                             Talk(SAY_HARRISON_1);
                             DoCast(me, SPELL_BANGING_THE_GONG);
                             me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 0, uint32(WEAPON_MACE));
                             me->SetSheath(SHEATH_STATE_MELEE);
                             _gongEvent = GONG_EVENT_3;
                             _gongTimer = 4000;
                             break;
                         case GONG_EVENT_3:
                             if (GameObject* gong = me->GetMap()->GetGameObject(instance->GetGuidData(GO_STRANGE_GONG)))
                                 gong->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                             _gongEvent = GONG_EVENT_4;
                             _gongTimer = 105000;
                             break;
                         case GONG_EVENT_4:
                             me->RemoveAura(SPELL_BANGING_THE_GONG);
                             if (GameObject* gong = me->GetMap()->GetGameObject(instance->GetGuidData(GO_STRANGE_GONG)))
                                 gong->SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                             // trigger or gong will need to be scripted to set IN_PROGRESS after enough hits.
                             // This is temp workaround.
                             instance->SetData(DATA_GONGEVENT, IN_PROGRESS); // to be removed.
                             if (instance->GetData(DATA_GONGEVENT) == IN_PROGRESS)
{
                                 // Players are Now Saved to instance at SPECIAL (Player should be notified?)
                                 me->GetMotionMaster()->MovePath(HARRISON_MOVE_2, false);
                                 _gongEvent = GONG_EVENT_5;
                                 _gongTimer = 5000;
                             }
                             else
{
                                 _gongTimer = 1000;
                                 _gongEvent = GONG_EVENT_9;
                             }
                             break;
                         case GONG_EVENT_5:
                             me->SetEntry(NPC_HARRISON_JONES_1);
                             me->SetDisplayId(MODEL_HARRISON_JONES_1);
                             Talk(SAY_HARRISON_2);
                             _gongTimer = 12000;
                             _gongEvent = GONG_EVENT_6;
                             break;
                         case GONG_EVENT_6:
                             me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_USE_STANDING);
                             Talk(SAY_HARRISON_3);
                             _gongTimer = 7000;
                             _gongEvent = GONG_EVENT_7;
                             break;
                         case GONG_EVENT_7:
                             if (!uiTargetGUID)
{
                                 std::list<Creature*> targetList;
                                 GetCreatureListWithEntryInGrid(targetList, me, NPC_AMANISHI_GUARDIAN, 26.0f);
                                 if (!targetList.empty())
{
                                     for (std::list<Creature*>::const_iterator itr = targetList.begin(); itr != targetList.end(); ++itr)
{
                                         if (Creature* ptarget = *itr)
{
                                             if (ptarget->GetPositionX() > 120)
{
                                                 ptarget->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 0, uint32(WEAPON_SPEAR));
                                                 ptarget->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                                                 ptarget->SetReactState(REACT_PASSIVE);
                                                 ptarget->AI()->SetData(0, 1);
                                             }
                                             else
{
                                                 ptarget->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                                                 ptarget->SetReactState(REACT_PASSIVE);
                                                 ptarget->AI()->SetData(0, 2);
                                             }
                                         }
                                     }
                                 }
                             }
                             if (GameObject* gate = me->GetMap()->GetGameObject(instance->GetGuidData(GO_MASSIVE_GATE)))
                                 gate->SetGoState(GO_STATE_ACTIVE);
                             _gongTimer = 2000;
                             _gongEvent = GONG_EVENT_8;
                             break;
                         case GONG_EVENT_8:
                             DoCast(me, SPELL_STEALTH);
                             me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 0, uint32(0));
                             me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                             me->GetMotionMaster()->MovePath(HARRISON_MOVE_3, false);
                             _gongTimer = 1000;
                             _gongEvent = 0;
                             break;
                         case GONG_EVENT_9:
                             me->GetMotionMaster()->MovePoint(0, 120.687f, 1674.0f, 42.0217f);
                             _gongTimer = 12000;
                             _gongEvent = GONG_EVENT_10;
                             break;
                         case GONG_EVENT_10:
                             me->SetFacingTo(1.59044f);
                             _gongEvent = 11;
                             _gongTimer = 6000;
                             break;
                         case GONG_EVENT_11:
                             me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
                             instance->SetData(DATA_GONGEVENT, NOT_STARTED);
                             _gongEvent = 0;
                             _gongTimer = 1000;
                             break;
                     }
                 }
                 else
                     _gongTimer -= diff;
             }
         }
References _gongEvent, _gongTimer, DATA_GONGEVENT, UnitAI::DoCast(), EMOTE_ONESHOT_NONE, EMOTE_STATE_USE_STANDING, GAMEOBJECT_FLAGS, GetCreatureListWithEntryInGrid(), ZoneScript::GetData(), Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), Unit::GetMotionMaster(), GO_FLAG_NOT_SELECTABLE, GO_MASSIVE_GATE, GO_STATE_ACTIVE, GO_STRANGE_GONG, GONG_EVENT_1, GONG_EVENT_10, GONG_EVENT_11, GONG_EVENT_2, GONG_EVENT_3, GONG_EVENT_4, GONG_EVENT_5, GONG_EVENT_6, GONG_EVENT_7, GONG_EVENT_8, GONG_EVENT_9, HARRISON_MOVE_1, HARRISON_MOVE_2, HARRISON_MOVE_3, IN_PROGRESS, instance, ScriptedAI::me, MODEL_HARRISON_JONES_1, MotionMaster::MovePath(), MotionMaster::MovePoint(), NOT_STARTED, NPC_AMANISHI_GUARDIAN, NPC_HARRISON_JONES_1, REACT_PASSIVE, Unit::RemoveAura(), SAY_HARRISON_1, SAY_HARRISON_2, SAY_HARRISON_3, ZoneScript::SetData(), Creature::SetDisplayId(), Object::SetEntry(), Unit::SetFacingTo(), Object::SetFlag(), Unit::SetSheath(), Object::SetUInt32Value(), SHEATH_STATE_MELEE, SPELL_BANGING_THE_GONG, SPELL_STEALTH, CreatureAI::Talk(), uiTargetGUID, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC, UNIT_NPC_EMOTESTATE, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAGS, UNIT_VIRTUAL_ITEM_SLOT_ID, WEAPON_MACE, and WEAPON_SPEAR.
Member Data Documentation
_gongEvent
uint8 npc_harrison_jones::npc_harrison_jonesAI::_gongEvent
Definition at line 610 of file zulaman.cpp.
Referenced by Reset(), sGossipSelect(), and UpdateAI().
_gongTimer
uint32 npc_harrison_jones::npc_harrison_jonesAI::_gongTimer
Definition at line 611 of file zulaman.cpp.
Referenced by Reset(), sGossipSelect(), and UpdateAI().
instance
InstanceScript* npc_harrison_jones::npc_harrison_jonesAI::instance
Definition at line 608 of file zulaman.cpp.
Referenced by npc_harrison_jonesAI(), SpellHit(), and UpdateAI().
uiTargetGUID
ObjectGuid npc_harrison_jones::npc_harrison_jonesAI::uiTargetGUID
Definition at line 612 of file zulaman.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/ZulAman/zulaman.cpp