Azerotcore-wotlk: go_bashir_crystalforge Class Reference
go_bashir_crystalforge Class Reference
Public Member Functions
go_bashir_crystalforge ()
bool OnGossipHello (Player *player, GameObject *go) override
bool OnGossipSelect (Player *player, GameObject *go, uint32, uint32 action) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Definition at line 1102 of file go_scripts.cpp.
Constructor & Destructor Documentation
go_bashir_crystalforge()
go_bashir_crystalforge::go_bashir_crystalforge () inline
Definition at line 1105 of file go_scripts.cpp.
 : GameObjectScript("go_bashir_crystalforge") { }
Member Function Documentation
OnGossipHello()
bool go_bashir_crystalforge::OnGossipHello (Player * player, GameObject * go) inline override virtual
Reimplemented from GameObjectScript.
Definition at line 1107 of file go_scripts.cpp.
     {
         if (go->GetGoType() == GAMEOBJECT_TYPE_QUESTGIVER) /* != GAMEOBJECT_TYPE_QUESTGIVER) */
             player->PrepareQuestMenu(go->GetGUID()); /* return true*/
         AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_BASHIR_CRYSTALFORGE_ITEM_1, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF);
         AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_BASHIR_CRYSTALFORGE_ITEM_5, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
         SendGossipMenuFor(player, GOSSIP_BASHIR_CRYSTALFORGE_TEXT, go->GetGUID());
         return true;
     }
References AddGossipItemFor(), GAMEOBJECT_TYPE_QUESTGIVER, GameObject::GetGoType(), Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, GOSSIP_BASHIR_CRYSTALFORGE_ITEM_1, GOSSIP_BASHIR_CRYSTALFORGE_ITEM_5, GOSSIP_BASHIR_CRYSTALFORGE_TEXT, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, Player::PrepareQuestMenu(), and SendGossipMenuFor().
OnGossipSelect()
bool go_bashir_crystalforge::OnGossipSelect (Player * player, GameObject * go, uint32 , uint32 action) inline override virtual
Reimplemented from GameObjectScript.
Definition at line 1120 of file go_scripts.cpp.
     {
         ClearGossipMenuFor(player);
         switch (action)
         {
             case GOSSIP_ACTION_INFO_DEF:
                 player->CastSpell(player, SPELL_CREATE_1_FLASK_OF_SORCERER, false);
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_BASHIR_CRYSTALFORGE_ITEM_RETURN, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
                 SendGossipMenuFor(player, GOSSIP_BASHIR_CRYSTALFORGE_ITEM_TEXT_RETURN, go->GetGUID());
                 break;
             case GOSSIP_ACTION_INFO_DEF + 1:
                 player->CastSpell(player, SPELL_CREATE_5_FLASK_OF_SORCERER, false);
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_BASHIR_CRYSTALFORGE_ITEM_RETURN, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
                 SendGossipMenuFor(player, GOSSIP_BASHIR_CRYSTALFORGE_ITEM_TEXT_RETURN, go->GetGUID());
                 break;
             case GOSSIP_ACTION_INFO_DEF + 2:
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_BASHIR_CRYSTALFORGE_ITEM_1, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF);
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_BASHIR_CRYSTALFORGE_ITEM_5, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
                 SendGossipMenuFor(player, GOSSIP_BASHIR_CRYSTALFORGE_TEXT, go->GetGUID());
                 break;
         }
         return true;
     }
References AddGossipItemFor(), Unit::CastSpell(), ClearGossipMenuFor(), Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, GOSSIP_BASHIR_CRYSTALFORGE_ITEM_1, GOSSIP_BASHIR_CRYSTALFORGE_ITEM_5, GOSSIP_BASHIR_CRYSTALFORGE_ITEM_RETURN, GOSSIP_BASHIR_CRYSTALFORGE_ITEM_TEXT_RETURN, GOSSIP_BASHIR_CRYSTALFORGE_TEXT, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, SendGossipMenuFor(), SPELL_CREATE_1_FLASK_OF_SORCERER, and SPELL_CREATE_5_FLASK_OF_SORCERER.
The documentation for this class was generated from the following file:
src/server/scripts/World/go_scripts.cpp