Azerotcore-wotlk: adt_MHDR Class Reference
adt_MHDR Class Reference
#include <adt.h>
Public Member Functions
bool prepareLoadedData ()
adt_MCIN * getMCIN ()
adt_MH2O * getMH2O ()
adt_MFBO * getMFBO ()
Public Attributes
uint32 size
uint32 flags
uint32 offsMCIN
uint32 offsTex
uint32 offsModels
uint32 offsModelsIds
uint32 offsMapObejcts
uint32 offsMapObejctsIds
uint32 offsDoodsDef
uint32 offsObjectsDef
uint32 offsMFBO
uint32 offsMH2O
uint32 data1
uint32 data2
uint32 data3
uint32 data4
uint32 data5
uint32 fcc
char fcc_txt [4]
Private Attributes
union {
uint32 fcc
char fcc_txt [4]
};
Detailed Description
Definition at line 294 of file adt.h.
Member Function Documentation
getMCIN()
adt_MCIN* adt_MHDR::getMCIN () inline
Definition at line 322 of file adt.h.
     {
         return reinterpret_cast<adt_MCIN*>(reinterpret_cast<uint8*>(&flags) + offsMCIN);
     }
References flags, and offsMCIN.
Referenced by ConvertADT(), and prepareLoadedData().
getMFBO()
adt_MFBO* adt_MHDR::getMFBO () inline
Definition at line 332 of file adt.h.
     {
         if (flags & 1 && offsMFBO)
             return reinterpret_cast<adt_MFBO*>(reinterpret_cast<uint8*>(&flags) + offsMFBO);
         return nullptr;
     }
References flags, and offsMFBO.
Referenced by ConvertADT(), and prepareLoadedData().
getMH2O()
adt_MH2O* adt_MHDR::getMH2O () inline
Definition at line 326 of file adt.h.
     {
         if (offsMH2O)
             return reinterpret_cast<adt_MH2O*>(reinterpret_cast<uint8*>(&flags) + offsMH2O);
         return nullptr;
     }
References flags, and offsMH2O.
Referenced by ConvertADT(), and prepareLoadedData().
prepareLoadedData()
bool adt_MHDR::prepareLoadedData ()
Definition at line 79 of file adt.cpp.
 {
     if (fcc != MHDRMagic.fcc)
         return false;
     if (size != sizeof(adt_MHDR) - 8)
         return false;
     // Check and prepare MCIN
     if (offsMCIN && !getMCIN()->prepareLoadedData())
         return false;
     // Check and prepare MH2O
     if (offsMH2O && !getMH2O()->prepareLoadedData())
         return false;
     if (offsMFBO && flags & 1 && !getMFBO()->prepareLoadedData())
         return false;
     return true;
 }
References fcc, u_map_fcc::fcc, flags, getMCIN(), getMFBO(), getMH2O(), MHDRMagic, offsMCIN, offsMFBO, offsMH2O, and size.
Referenced by ADT_file::prepareLoadedData().
Member Data Documentation
union { ... }
data1
uint32 adt_MHDR::data1
Definition at line 315 of file adt.h.
data2
uint32 adt_MHDR::data2
Definition at line 316 of file adt.h.
data3
uint32 adt_MHDR::data3
Definition at line 317 of file adt.h.
data4
uint32 adt_MHDR::data4
Definition at line 318 of file adt.h.
data5
uint32 adt_MHDR::data5
Definition at line 319 of file adt.h.
fcc
uint32 adt_MHDR::fcc
Definition at line 298 of file adt.h.
Referenced by prepareLoadedData().
fcc_txt
char adt_MHDR::fcc_txt[4]
Definition at line 299 of file adt.h.
flags
uint32 adt_MHDR::flags
Definition at line 304 of file adt.h.
Referenced by getMCIN(), getMFBO(), getMH2O(), and prepareLoadedData().
offsDoodsDef
uint32 adt_MHDR::offsDoodsDef
Definition at line 311 of file adt.h.
offsMapObejcts
uint32 adt_MHDR::offsMapObejcts
Definition at line 309 of file adt.h.
offsMapObejctsIds
uint32 adt_MHDR::offsMapObejctsIds
Definition at line 310 of file adt.h.
offsMCIN
uint32 adt_MHDR::offsMCIN
Definition at line 305 of file adt.h.
Referenced by getMCIN(), and prepareLoadedData().
offsMFBO
uint32 adt_MHDR::offsMFBO
Definition at line 313 of file adt.h.
Referenced by getMFBO(), and prepareLoadedData().
offsMH2O
uint32 adt_MHDR::offsMH2O
Definition at line 314 of file adt.h.
Referenced by getMH2O(), and prepareLoadedData().
offsModels
uint32 adt_MHDR::offsModels
Definition at line 307 of file adt.h.
offsModelsIds
uint32 adt_MHDR::offsModelsIds
Definition at line 308 of file adt.h.
offsObjectsDef
uint32 adt_MHDR::offsObjectsDef
Definition at line 312 of file adt.h.
offsTex
uint32 adt_MHDR::offsTex
Definition at line 306 of file adt.h.
size
uint32 adt_MHDR::size
Definition at line 302 of file adt.h.
Referenced by prepareLoadedData().
The documentation for this class was generated from the following files:
src/tools/map_extractor/adt.h
src/tools/map_extractor/adt.cpp