Azerotcore-wotlk: Acore::Impl::GenericHash< HashCreator, DigestLength > Class Template Reference
Acore::Impl::GenericHash< HashCreator, DigestLength > Class Template Reference
#include <CryptoHash.h>
Public Types
using Digest = std::array< uint8, DIGEST_LENGTH >
Public Member Functions
GenericHash ()
~GenericHash ()
void UpdateData (uint8 const *data, size_t len)
void UpdateData (std::string_view str)
void UpdateData (std::string const &str)
void UpdateData (char const *str)
template<typename Container >
void UpdateData (Container const &c)
void Finalize ()
Digest const & GetDigest () const
Static Public Member Functions
static Digest GetDigestOf (uint8 const *data, size_t len)
template<typename... Ts>
static auto GetDigestOf (Ts &&... pack) -> std::enable_if_t< !(std::is_integral_v< std::decay_t< Ts >>||...), Digest >
Static Public Attributes
static constexpr size_t DIGEST_LENGTH = DigestLength
Private Attributes
EVP_MD_CTX * _ctx
Digest _digest = { }
Detailed Description
template<GenericHashImpl::HashCreator HashCreator, size_t DigestLength>
class Acore::Impl::GenericHash< HashCreator, DigestLength >
Definition at line 47 of file CryptoHash.h.
Member Typedef Documentation
Digest
template<GenericHashImpl::HashCreator HashCreator, size_t DigestLength> using Acore::Impl::GenericHash< HashCreator, DigestLength >::Digest = std::array<uint8, DIGEST_LENGTH>
Definition at line 51 of file CryptoHash.h.
Constructor & Destructor Documentation
GenericHash()
template<GenericHashImpl::HashCreator HashCreator, size_t DigestLength> Acore::Impl::GenericHash< HashCreator, DigestLength >::GenericHash () inline
Definition at line 70 of file CryptoHash.h.
                       : _ctx(GenericHashImpl::MakeCTX())
         {
             int result = EVP_DigestInit_ex(_ctx, HashCreator(), nullptr);
             ASSERT(result == 1);
         }
References Acore::Impl::GenericHash< HashCreator, DigestLength >::_ctx, and ASSERT.
~GenericHash()
template<GenericHashImpl::HashCreator HashCreator, size_t DigestLength> Acore::Impl::GenericHash< HashCreator, DigestLength >::~GenericHash () inline
Definition at line 76 of file CryptoHash.h.
         {
             if (!_ctx)
             {
                 return;
             }
             GenericHashImpl::DestroyCTX(_ctx);
             _ctx = nullptr;
         }
References Acore::Impl::GenericHash< HashCreator, DigestLength >::_ctx, and Acore::Impl::GenericHashImpl::DestroyCTX().
Member Function Documentation
Finalize()
template<GenericHashImpl::HashCreator HashCreator, size_t DigestLength> void Acore::Impl::GenericHash< HashCreator, DigestLength >::Finalize () inline
Definition at line 97 of file CryptoHash.h.
         {
             uint32 length;
             int result = EVP_DigestFinal_ex(_ctx, _digest.data(), &length);
             ASSERT(result == 1);
             ASSERT(length == DIGEST_LENGTH);
             GenericHashImpl::DestroyCTX(_ctx);
             _ctx = nullptr;
         }
References Acore::Impl::GenericHash< HashCreator, DigestLength >::_ctx, Acore::Impl::GenericHash< HashCreator, DigestLength >::_digest, ASSERT, Acore::Impl::GenericHashImpl::DestroyCTX(), Acore::Impl::GenericHash< HashCreator, DigestLength >::DIGEST_LENGTH, and G3D::length().
Referenced by WorldSocket::HandleAuthSessionCallback(), WardenMac::HandleData(), WardenMac::HandleHashResult(), and AuthSession::HandleReconnectProof().
GetDigest()
template<GenericHashImpl::HashCreator HashCreator, size_t DigestLength> Digest const& Acore::Impl::GenericHash< HashCreator, DigestLength >::GetDigest () const inline
Definition at line 107 of file CryptoHash.h.
 { return _digest; }
References Acore::Impl::GenericHash< HashCreator, DigestLength >::_digest.
Referenced by WorldSocket::HandleAuthSessionCallback(), WardenMac::HandleData(), WardenMac::HandleHashResult(), and AuthSession::HandleReconnectProof().
GetDigestOf() [1/2]
template<GenericHashImpl::HashCreator HashCreator, size_t DigestLength> template<typename... Ts> static auto Acore::Impl::GenericHash< HashCreator, DigestLength >::GetDigestOf (Ts &&... pack) -> std::enable_if_t < !(std::is_integral_v<std::decay_t<Ts>> || ...), Digest > inline static
Definition at line 62 of file CryptoHash.h.
         {
             GenericHash hash;
             (hash.UpdateData(std::forward<Ts>(pack)), ...);
             hash.Finalize();
             return hash.GetDigest();
         }
References hash().
GetDigestOf() [2/2]
template<GenericHashImpl::HashCreator HashCreator, size_t DigestLength> static Digest Acore::Impl::GenericHash< HashCreator, DigestLength >::GetDigestOf (uint8 const * data, size_t len) inline static
Definition at line 53 of file CryptoHash.h.
         {
             GenericHash hash;
             hash.UpdateData(data, len);
             hash.Finalize();
             return hash.GetDigest();
         }
References hash().
Referenced by Acore::Crypto::SRP6::CalculateVerifier(), Acore::Crypto::SRP6::GetSessionVerifier(), Acore::Crypto::SRP6::SHA1Interleave(), UpdateFetcher::Update(), and Acore::Crypto::SRP6::VerifyChallengeResponse().
UpdateData() [1/5]
template<GenericHashImpl::HashCreator HashCreator, size_t DigestLength> void Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData (char const * str) inline
Definition at line 93 of file CryptoHash.h.
 { UpdateData(std::string_view(str)); } /* explicit overload to avoid using the container template */
References Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData().
Referenced by Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData().
UpdateData() [2/5]
template<GenericHashImpl::HashCreator HashCreator, size_t DigestLength> template<typename Container > void Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData (Container const & c) inline
Definition at line 95 of file CryptoHash.h.
 { UpdateData(std::data(c), std::size(c)); }
References mpq::c, and Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData().
Referenced by Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData().
UpdateData() [3/5]
template<GenericHashImpl::HashCreator HashCreator, size_t DigestLength> void Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData (std::string const & str) inline
Definition at line 92 of file CryptoHash.h.
 { UpdateData(std::string_view(str)); } /* explicit overload to avoid using the container template */
References Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData().
Referenced by Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData().
UpdateData() [4/5]
template<GenericHashImpl::HashCreator HashCreator, size_t DigestLength> void Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData (std::string_view str) inline
Definition at line 91 of file CryptoHash.h.
 { UpdateData(reinterpret_cast<uint8 const*>(str.data()), str.size()); }
References const, and Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData().
Referenced by Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData().
UpdateData() [5/5]
template<GenericHashImpl::HashCreator HashCreator, size_t DigestLength> void Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData (uint8 const * data, size_t len) inline
Definition at line 86 of file CryptoHash.h.
         {
             int result = EVP_DigestUpdate(_ctx, data, len);
             ASSERT(result == 1);
         }
References Acore::Impl::GenericHash< HashCreator, DigestLength >::_ctx, and ASSERT.
Referenced by WorldSocket::HandleAuthSessionCallback(), WardenMac::HandleData(), WardenMac::HandleHashResult(), and AuthSession::HandleReconnectProof().
Member Data Documentation
_ctx
template<GenericHashImpl::HashCreator HashCreator, size_t DigestLength> EVP_MD_CTX* Acore::Impl::GenericHash< HashCreator, DigestLength >::_ctx private
Definition at line 110 of file CryptoHash.h.
Referenced by Acore::Impl::GenericHash< HashCreator, DigestLength >::Finalize(), Acore::Impl::GenericHash< HashCreator, DigestLength >::GenericHash(), Acore::Impl::GenericHash< HashCreator, DigestLength >::UpdateData(), and Acore::Impl::GenericHash< HashCreator, DigestLength >::~GenericHash().
_digest
template<GenericHashImpl::HashCreator HashCreator, size_t DigestLength> Digest Acore::Impl::GenericHash< HashCreator, DigestLength >::_digest = { } private
Definition at line 111 of file CryptoHash.h.
Referenced by Acore::Impl::GenericHash< HashCreator, DigestLength >::Finalize(), and Acore::Impl::GenericHash< HashCreator, DigestLength >::GetDigest().
DIGEST_LENGTH
template<GenericHashImpl::HashCreator HashCreator, size_t DigestLength> constexpr size_t Acore::Impl::GenericHash< HashCreator, DigestLength >::DIGEST_LENGTH = DigestLength static constexpr
Definition at line 50 of file CryptoHash.h.
Referenced by Acore::Impl::GenericHash< HashCreator, DigestLength >::Finalize(), and Acore::Crypto::SRP6::SHA1Interleave().
The documentation for this class was generated from the following file:
src/common/Cryptography/CryptoHash.h