Azerotcore-wotlk: st_mysql_methods Struct Reference
st_mysql_methods Struct Reference
#include <sql_common.h>
Public Attributes
my_bool(* read_query_result)(MYSQL *mysql)
my_bool(* advanced_command)(MYSQL *mysql, enum enum_server_command command, const unsigned char *header, unsigned long header_length, const unsigned char *arg, unsigned long arg_length, my_bool skip_check, MYSQL_STMT *stmt)
MYSQL_DATA *(* read_rows)(MYSQL *mysql, MYSQL_FIELD *mysql_fields, unsigned int fields)
MYSQL_RES *(* use_result)(MYSQL *mysql)
void(* fetch_lengths)(unsigned long *to, MYSQL_ROW column, unsigned int field_count)
void(* flush_use_result)(MYSQL *mysql, my_bool flush_all_results)
int(* read_change_user_result)(MYSQL *mysql)
MYSQL_FIELD *(* list_fields)(MYSQL *mysql)
my_bool(* read_prepare_result)(MYSQL *mysql, MYSQL_STMT *stmt)
int(* stmt_execute)(MYSQL_STMT *stmt)
int(* read_binary_rows)(MYSQL_STMT *stmt)
int(* unbuffered_fetch)(MYSQL *mysql, char **row)
void(* free_embedded_thd)(MYSQL *mysql)
const char *(* read_statistics)(MYSQL *mysql)
my_bool(* next_result)(MYSQL *mysql)
int(* read_rows_from_cursor)(MYSQL_STMT *stmt)
Detailed Description
Definition at line 36 of file sql_common.h.
Member Data Documentation
advanced_command
my_bool(* st_mysql_methods::advanced_command) (MYSQL *mysql, enum enum_server_command command, const unsigned char *header, unsigned long header_length, const unsigned char *arg, unsigned long arg_length, my_bool skip_check, MYSQL_STMT *stmt)
Definition at line 39 of file sql_common.h.
Referenced by mysql_stmt_send_long_data(), reset_stmt_handle(), and stmt_read_row_from_cursor().
fetch_lengths
void(* st_mysql_methods::fetch_lengths) (unsigned long *to, MYSQL_ROW column, unsigned int field_count)
Definition at line 50 of file sql_common.h.
Referenced by mysql_fetch_lengths().
flush_use_result
void(* st_mysql_methods::flush_use_result) (MYSQL *mysql, my_bool flush_all_results)
Definition at line 52 of file sql_common.h.
Referenced by mysql_free_result(), mysql_stmt_close(), and reset_stmt_handle().
free_embedded_thd
void(* st_mysql_methods::free_embedded_thd) (MYSQL *mysql)
Definition at line 60 of file sql_common.h.
Referenced by mysql_close().
list_fields
MYSQL_FIELD*(* st_mysql_methods::list_fields) (MYSQL *mysql)
Definition at line 55 of file sql_common.h.
Referenced by mysql_list_fields().
next_result
my_bool(* st_mysql_methods::next_result) (MYSQL *mysql)
Definition at line 62 of file sql_common.h.
Referenced by mysql_next_result().
read_binary_rows
int(* st_mysql_methods::read_binary_rows) (MYSQL_STMT *stmt)
Definition at line 58 of file sql_common.h.
Referenced by mysql_stmt_store_result().
read_change_user_result
int(* st_mysql_methods::read_change_user_result) (MYSQL *mysql)
Definition at line 53 of file sql_common.h.
Referenced by client_mpvio_read_packet(), and run_plugin_auth().
read_prepare_result
my_bool(* st_mysql_methods::read_prepare_result) (MYSQL *mysql, MYSQL_STMT *stmt)
Definition at line 56 of file sql_common.h.
Referenced by mysql_stmt_prepare().
read_query_result
my_bool(* st_mysql_methods::read_query_result) (MYSQL *mysql)
Definition at line 38 of file sql_common.h.
Referenced by execute(), mysql_read_query_result(), and mysql_real_query().
read_rows
MYSQL_DATA*(* st_mysql_methods::read_rows) (MYSQL *mysql, MYSQL_FIELD *mysql_fields, unsigned int fields)
Definition at line 47 of file sql_common.h.
Referenced by cli_read_prepare_result(), mysql_list_processes(), and mysql_store_result().
read_rows_from_cursor
int(* st_mysql_methods::read_rows_from_cursor) (MYSQL_STMT *stmt)
Definition at line 63 of file sql_common.h.
Referenced by stmt_read_row_from_cursor().
read_statistics
const char*(* st_mysql_methods::read_statistics) (MYSQL *mysql)
Definition at line 61 of file sql_common.h.
Referenced by mysql_stat().
stmt_execute
int(* st_mysql_methods::stmt_execute) (MYSQL_STMT *stmt)
Definition at line 57 of file sql_common.h.
Referenced by mysql_stmt_execute().
unbuffered_fetch
int(* st_mysql_methods::unbuffered_fetch) (MYSQL *mysql, char **row)
Definition at line 59 of file sql_common.h.
Referenced by stmt_read_row_unbuffered().
use_result
MYSQL_RES*(* st_mysql_methods::use_result) (MYSQL *mysql)
Definition at line 49 of file sql_common.h.
Referenced by mysql_use_result().
The documentation for this struct was generated from the following file:
deps/mysqllite/include/sql_common.h