Azerotcore-wotlk: MapUpdater Class Reference
MapUpdater Class Reference
#include <MapUpdater.h>
Public Member Functions
MapUpdater ()
virtual ~MapUpdater ()
void schedule_update (Map &map, uint32 diff, uint32 s_diff)
void schedule_lfg_update (uint32 diff)
void wait ()
void activate (size_t num_threads)
void deactivate ()
bool activated ()
void update_finished ()
Private Member Functions
void WorkerThread ()
Private Attributes
ProducerConsumerQueue< UpdateRequest * > _queue
std::vector< std::thread > _workerThreads
std::atomic< bool > _cancelationToken
std::mutex _lock
std::condition_variable _condition
size_t pending_requests
Detailed Description
Definition at line 30 of file MapUpdater.h.
Constructor & Destructor Documentation
MapUpdater()
MapUpdater::MapUpdater ()
Definition at line 73 of file MapUpdater.cpp.
                       : pending_requests(0)
 {
 }
~MapUpdater()
MapUpdater::~MapUpdater () virtual
Definition at line 77 of file MapUpdater.cpp.
 {
     deactivate();
 }
References deactivate().
Member Function Documentation
activate()
void MapUpdater::activate (size_t num_threads)
Definition at line 82 of file MapUpdater.cpp.
 {
     _workerThreads.reserve(num_threads);
     for (size_t i = 0; i < num_threads; ++i)
     {
         _workerThreads.push_back(std::thread(&MapUpdater::WorkerThread, this));
     }
 }
References _workerThreads, and WorkerThread().
Referenced by MapMgr::Initialize().
activated()
bool MapUpdater::activated ()
Definition at line 136 of file MapUpdater.cpp.
 {
     return _workerThreads.size() > 0;
 }
References _workerThreads.
Referenced by MapMgr::UnloadAll(), and MapMgr::Update().
deactivate()
void MapUpdater::deactivate ()
Definition at line 91 of file MapUpdater.cpp.
 {
     _cancelationToken = true;
     wait();
     _queue.Cancel();
     for (auto& thread : _workerThreads)
     {
         if (thread.joinable())
         {
             thread.join();
         }
     }
 }
References _cancelationToken, _queue, _workerThreads, ProducerConsumerQueue< T >::Cancel(), and wait().
Referenced by MapMgr::UnloadAll(), and ~MapUpdater().
schedule_lfg_update()
void MapUpdater::schedule_lfg_update (uint32 diff)
Definition at line 127 of file MapUpdater.cpp.
 {
     std::lock_guard<std::mutex> guard(_lock);
     ++pending_requests;
     _queue.Push(new LFGUpdateRequest(*this, diff));
 }
References _lock, _queue, pending_requests, and ProducerConsumerQueue< T >::Push().
Referenced by MapMgr::Update().
schedule_update()
void MapUpdater::schedule_update (Map & map, uint32 diff, uint32 s_diff)
Definition at line 118 of file MapUpdater.cpp.
 {
     std::lock_guard<std::mutex> guard(_lock);
     ++pending_requests;
     _queue.Push(new MapUpdateRequest(map, *this, diff, s_diff));
 }
References _lock, _queue, pending_requests, and ProducerConsumerQueue< T >::Push().
Referenced by MapMgr::Update().
update_finished()
void MapUpdater::update_finished ()
Definition at line 141 of file MapUpdater.cpp.
 {
     std::lock_guard<std::mutex> lock(_lock);
     --pending_requests;
     _condition.notify_all();
 }
References _condition, _lock, and pending_requests.
Referenced by MapUpdateRequest::call(), and LFGUpdateRequest::call().
wait()
void MapUpdater::wait ()
Definition at line 108 of file MapUpdater.cpp.
 {
     std::unique_lock<std::mutex> guard(_lock);
     while (pending_requests > 0)
         _condition.wait(guard);
     guard.unlock();
 }
References _condition, _lock, and pending_requests.
Referenced by deactivate(), and MapMgr::Update().
WorkerThread()
void MapUpdater::WorkerThread () private
Definition at line 150 of file MapUpdater.cpp.
 {
     while (1)
     {
         UpdateRequest* request = nullptr;
         _queue.WaitAndPop(request);
         if (_cancelationToken)
             return;
         request->call();
         delete request;
     }
 }
References _cancelationToken, _queue, UpdateRequest::call(), and ProducerConsumerQueue< T >::WaitAndPop().
Referenced by activate().
Member Data Documentation
_cancelationToken
std::atomic<bool> MapUpdater::_cancelationToken private
Definition at line 50 of file MapUpdater.h.
Referenced by deactivate(), and WorkerThread().
_condition
std::condition_variable MapUpdater::_condition private
Definition at line 53 of file MapUpdater.h.
Referenced by update_finished(), and wait().
_lock
std::mutex MapUpdater::_lock private
Definition at line 52 of file MapUpdater.h.
Referenced by schedule_lfg_update(), schedule_update(), update_finished(), and wait().
_queue
ProducerConsumerQueue<UpdateRequest*> MapUpdater::_queue private
Definition at line 47 of file MapUpdater.h.
Referenced by deactivate(), schedule_lfg_update(), schedule_update(), and WorkerThread().
_workerThreads
std::vector<std::thread> MapUpdater::_workerThreads private
Definition at line 49 of file MapUpdater.h.
Referenced by activate(), activated(), and deactivate().
pending_requests
size_t MapUpdater::pending_requests private
Definition at line 54 of file MapUpdater.h.
Referenced by schedule_lfg_update(), schedule_update(), update_finished(), and wait().
The documentation for this class was generated from the following files:
src/server/game/Maps/MapUpdater.h
src/server/game/Maps/MapUpdater.cpp