Azerotcore-wotlk: gobject_commandscript Class Reference
gobject_commandscript Class Reference
Public Member Functions
gobject_commandscript ()
ChatCommandTable GetCommands () const override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Static Public Member Functions
static bool HandleGameObjectActivateCommand (ChatHandler *handler, GameObjectSpawnId guidLow)
static bool HandleGameObjectAddCommand (ChatHandler *handler, GameObjectEntry objectId, Optional< int32 > spawnTimeSecs)
static bool HandleGameObjectAddTempCommand (ChatHandler *handler, GameObjectEntry objectId, Optional< uint64 > spawntime)
static bool HandleGameObjectTargetCommand (ChatHandler *handler, Optional< Variant< GameObjectEntry, std::string_view >> objectId)
static bool HandleGameObjectDeleteCommand (ChatHandler *handler, GameObjectSpawnId spawnId)
static bool HandleGameObjectTurnCommand (ChatHandler *handler, GameObjectSpawnId guidLow, Optional< float > oz, Optional< float > oy, Optional< float > ox)
static bool HandleGameObjectMoveCommand (ChatHandler *handler, GameObjectSpawnId guidLow, Optional< std::array< float, 3 >> xyz)
static bool HandleGameObjectSetPhaseCommand (ChatHandler *handler, GameObjectSpawnId guidLow, uint32 phaseMask)
static bool HandleGameObjectNearCommand (ChatHandler *handler, Optional< float > dist)
static bool HandleGameObjectInfoCommand (ChatHandler *handler, Optional< Variant< GameObjectEntry, std::string_view >> objectId)
static bool HandleGameObjectSetStateCommand (ChatHandler *handler, GameObjectSpawnId guidLow, int32 objectType, Optional< uint32 > objectState)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 42 of file cs_gobject.cpp.
Constructor & Destructor Documentation
gobject_commandscript()
gobject_commandscript::gobject_commandscript () inline
Definition at line 45 of file cs_gobject.cpp.
 : CommandScript("gobject_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable gobject_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
Definition at line 47 of file cs_gobject.cpp.
     {
         static ChatCommandTable gobjectCommandTable =
         {
             { "activate",  HandleGameObjectActivateCommand, SEC_GAMEMASTER,    Console::No },
             { "delete",    HandleGameObjectDeleteCommand,   SEC_ADMINISTRATOR, Console::No },
             { "info",      HandleGameObjectInfoCommand,     SEC_MODERATOR,     Console::No },
             { "move",      HandleGameObjectMoveCommand,     SEC_ADMINISTRATOR, Console::No },
             { "near",      HandleGameObjectNearCommand,     SEC_MODERATOR,     Console::No },
             { "target",    HandleGameObjectTargetCommand,   SEC_MODERATOR,     Console::No },
             { "turn",      HandleGameObjectTurnCommand,     SEC_ADMINISTRATOR, Console::No },
             { "add temp",  HandleGameObjectAddTempCommand,  SEC_GAMEMASTER,    Console::No },
             { "add",       HandleGameObjectAddCommand,      SEC_ADMINISTRATOR, Console::No },
             { "set phase", HandleGameObjectSetPhaseCommand, SEC_ADMINISTRATOR, Console::No },
             { "set state", HandleGameObjectSetStateCommand, SEC_ADMINISTRATOR, Console::No }
         };
         static ChatCommandTable commandTable =
         {
             { "gobject", gobjectCommandTable }
         };
         return commandTable;
     }
References Acore::ChatCommands::No, SEC_ADMINISTRATOR, SEC_GAMEMASTER, and SEC_MODERATOR.
HandleGameObjectActivateCommand()
static bool gobject_commandscript::HandleGameObjectActivateCommand (ChatHandler * handler, GameObjectSpawnId guidLow) inline static
Definition at line 70 of file cs_gobject.cpp.
     {
         GameObject* object = handler->GetObjectFromPlayerMapByDbGuid(guidLow);
         if (!object)
         {
             handler->PSendSysMessage(LANG_COMMAND_OBJNOTFOUND, uint32(guidLow));
             handler->SetSentErrorMessage(true);
             return false;
         }
         uint32_t const autoCloseTime = object->GetGOInfo()->GetAutoCloseTime() ? 10000u : 0u;
         // Activate
         object->SetLootState(GO_READY);
         object->UseDoorOrButton(autoCloseTime, false, handler->GetSession()->GetPlayer());
         handler->PSendSysMessage("Object activated!");
         return true;
     }
References ChatHandler::GetObjectFromPlayerMapByDbGuid(), WorldSession::GetPlayer(), ChatHandler::GetSession(), GO_READY, LANG_COMMAND_OBJNOTFOUND, ChatHandler::PSendSysMessage(), and ChatHandler::SetSentErrorMessage().
HandleGameObjectAddCommand()
static bool gobject_commandscript::HandleGameObjectAddCommand (ChatHandler * handler, GameObjectEntry objectId, Optional< int32 > spawnTimeSecs) inline static
Todo:
is it really necessary to add both the real and DB table guid here ?
Definition at line 92 of file cs_gobject.cpp.
     {
         if (!objectId)
             return false;
         GameObjectTemplate const* objectInfo = sObjectMgr->GetGameObjectTemplate(objectId);
         if (!objectInfo)
         {
             handler->PSendSysMessage(LANG_GAMEOBJECT_NOT_EXIST, uint32(objectId));
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (objectInfo->displayId && !sGameObjectDisplayInfoStore.LookupEntry(objectInfo->displayId))
         {
             // report to DB errors log as in loading case
             LOG_ERROR("sql.sql", "Gameobject (Entry %u GoType: %u) have invalid displayId (%u), not spawned.", *objectId, objectInfo->type, objectInfo->displayId);
             handler->PSendSysMessage(LANG_GAMEOBJECT_HAVE_INVALID_DATA, uint32(objectId));
             handler->SetSentErrorMessage(true);
             return false;
         }
         Player* player = handler->GetSession()->GetPlayer();
         float x = float(player->GetPositionX());
         float y = float(player->GetPositionY());
         float z = float(player->GetPositionZ());
         float o = float(player->GetOrientation());
         Map* map = player->GetMap();
         GameObject* object = sObjectMgr->IsGameObjectStaticTransport(objectInfo->entry) ? new StaticTransport() : new GameObject();
         ObjectGuid::LowType guidLow = map->GenerateLowGuid<HighGuid::GameObject>();
         if (!object->Create(guidLow, objectInfo->entry, map, player->GetPhaseMaskForSpawn(), x, y, z, o, G3D::Quat(), 0, GO_STATE_READY))
         {
             delete object;
             return false;
         }
         if (spawnTimeSecs)
             object->SetRespawnTime(*spawnTimeSecs);
         // fill the gameobject data and save to the db
         object->SaveToDB(map->GetId(), (1 << map->GetSpawnMode()), player->GetPhaseMaskForSpawn());
         guidLow = object->GetSpawnId();
         // delete the old object and do a clean load from DB with a fresh new GameObject instance.
         // this is required to avoid weird behavior and memory leaks
         delete object;
         object = sObjectMgr->IsGameObjectStaticTransport(objectInfo->entry) ? new StaticTransport() : new GameObject();
         // this will generate a new guid if the object is in an instance
         if (!object->LoadGameObjectFromDB(guidLow, map, true))
         {
             delete object;
             return false;
         }
         sObjectMgr->AddGameobjectToGrid(guidLow, sObjectMgr->GetGOData(guidLow));
         handler->PSendSysMessage(LANG_GAMEOBJECT_ADD, uint32(objectId), objectInfo->name.c_str(), guidLow, player->GetPositionX(), player->GetPositionY(), player->GetPositionZ());
         return true;
     }
References GameObject::Create(), GameObjectTemplate::displayId, GameObjectTemplate::entry, GameObject, Map::GenerateLowGuid(), Map::GetId(), WorldObject::GetMap(), Position::GetOrientation(), Player::GetPhaseMaskForSpawn(), WorldSession::GetPlayer(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ChatHandler::GetSession(), Map::GetSpawnMode(), GO_STATE_READY, LANG_GAMEOBJECT_ADD, LANG_GAMEOBJECT_HAVE_INVALID_DATA, LANG_GAMEOBJECT_NOT_EXIST, GameObject::LoadGameObjectFromDB(), LOG_ERROR, GameObjectTemplate::name, ChatHandler::PSendSysMessage(), GameObject::SetRespawnTime(), ChatHandler::SetSentErrorMessage(), sGameObjectDisplayInfoStore, sObjectMgr, and GameObjectTemplate::type.
HandleGameObjectAddTempCommand()
static bool gobject_commandscript::HandleGameObjectAddTempCommand (ChatHandler * handler, GameObjectEntry objectId, Optional< uint64 > spawntime) inline static
Definition at line 157 of file cs_gobject.cpp.
     {
         Player* player = handler->GetSession()->GetPlayer();
         uint64 spawntm(spawntime.value_or(300));
         if (!sObjectMgr->GetGameObjectTemplate(objectId))
         {
             handler->PSendSysMessage(LANG_GAMEOBJECT_NOT_EXIST, uint32(objectId));
             handler->SetSentErrorMessage(true);
             return false;
         }
         float x = player->GetPositionX();
         float y = player->GetPositionY();
         float z = player->GetPositionZ();
         float ang = player->GetOrientation();
         float rot2 = sin(ang / 2);
         float rot3 = cos(ang / 2);
         player->SummonGameObject(objectId, x, y, z, ang, 0, 0, rot2, rot3, spawntm);
         return true;
     }
References Position::GetOrientation(), WorldSession::GetPlayer(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ChatHandler::GetSession(), LANG_GAMEOBJECT_NOT_EXIST, ChatHandler::PSendSysMessage(), ChatHandler::SetSentErrorMessage(), sObjectMgr, and WorldObject::SummonGameObject().
HandleGameObjectDeleteCommand()
static bool gobject_commandscript::HandleGameObjectDeleteCommand (ChatHandler * handler, GameObjectSpawnId spawnId) inline static
Definition at line 296 of file cs_gobject.cpp.
     {
         GameObject* object = handler->GetObjectFromPlayerMapByDbGuid(spawnId);
         if (!object)
         {
             handler->PSendSysMessage(LANG_COMMAND_OBJNOTFOUND, uint32(spawnId));
             handler->SetSentErrorMessage(true);
             return false;
         }
         ObjectGuid ownerGuid = object->GetOwnerGUID();
         if (ownerGuid)
         {
             Unit* owner = ObjectAccessor::GetUnit(*handler->GetSession()->GetPlayer(), ownerGuid);
             if (!owner || !ownerGuid.IsPlayer())
             {
                 handler->PSendSysMessage(LANG_COMMAND_DELOBJREFERCREATURE, ownerGuid.GetCounter(), object->GetSpawnId());
                 handler->SetSentErrorMessage(true);
                 return false;
             }
             owner->RemoveGameObject(object, false);
         }
         object->SetRespawnTime(0);                                 // not save respawn time
         object->Delete();
         object->DeleteFromDB();
         handler->PSendSysMessage(LANG_COMMAND_DELOBJMESSAGE, object->GetSpawnId());
         return true;
     }
References ObjectGuid::GetCounter(), ChatHandler::GetObjectFromPlayerMapByDbGuid(), WorldSession::GetPlayer(), ChatHandler::GetSession(), GameObject::GetSpawnId(), ObjectAccessor::GetUnit(), ObjectGuid::IsPlayer(), LANG_COMMAND_DELOBJMESSAGE, LANG_COMMAND_DELOBJREFERCREATURE, LANG_COMMAND_OBJNOTFOUND, ChatHandler::PSendSysMessage(), Unit::RemoveGameObject(), and ChatHandler::SetSentErrorMessage().
HandleGameObjectInfoCommand()
static bool gobject_commandscript::HandleGameObjectInfoCommand (ChatHandler * handler, Optional< Variant< GameObjectEntry, std::string_view >> objectId) inline static
Definition at line 498 of file cs_gobject.cpp.
     {
         uint32 entry = 0;
         uint32 type = 0;
         uint32 displayId = 0;
         std::string name;
         uint32 lootId = 0;
         GameObject* gameObject = nullptr;
         if (!objectId)
         {
             if (WorldObject* object = handler->getSelectedObject())
             {
                 entry = object->GetEntry();
                 if (object->GetTypeId() == TYPEID_GAMEOBJECT)
                     gameObject = object->ToGameObject();
             }
         }
         else
             entry = static_cast<uint32>(objectId->get<GameObjectEntry>());
         GameObjectTemplate const* gameObjectInfo = sObjectMgr->GetGameObjectTemplate(entry);
         if (!gameObjectInfo)
         {
             handler->PSendSysMessage(LANG_GAMEOBJECT_NOT_EXIST, entry);
             handler->SetSentErrorMessage(true);
             return false;
         }
         type = gameObjectInfo->type;
         displayId = gameObjectInfo->displayId;
         name = gameObjectInfo->name;
         if (type == GAMEOBJECT_TYPE_CHEST)
             lootId = gameObjectInfo->chest.lootId;
         else if (type == GAMEOBJECT_TYPE_FISHINGHOLE)
             lootId = gameObjectInfo->fishinghole.lootId;
         handler->PSendSysMessage(LANG_GOINFO_ENTRY, entry);
         handler->PSendSysMessage(LANG_GOINFO_TYPE, type);
         handler->PSendSysMessage(LANG_GOINFO_LOOTID, lootId);
         handler->PSendSysMessage(LANG_GOINFO_DISPLAYID, displayId);
         if (gameObject)
         {
             handler->PSendSysMessage("LootMode: %u", gameObject->GetLootMode());
             handler->PSendSysMessage("LootState: %u", gameObject->getLootState());
             handler->PSendSysMessage("GOState: %u", gameObject->GetGoState());
             handler->PSendSysMessage("PhaseMask: %u", gameObject->GetPhaseMask());
             handler->PSendSysMessage("IsLootEmpty: %u", gameObject->loot.empty());
             handler->PSendSysMessage("IsLootLooted: %u", gameObject->loot.isLooted());
         }
         handler->PSendSysMessage(LANG_GOINFO_NAME, name.c_str());
         return true;
     }
References GameObjectTemplate::chest, GameObjectTemplate::displayId, Loot::empty(), GameObjectTemplate::fishinghole, GAMEOBJECT_TYPE_CHEST, GAMEOBJECT_TYPE_FISHINGHOLE, Object::GetEntry(), GameObject::GetGoState(), GameObject::GetLootMode(), GameObject::getLootState(), WorldObject::GetPhaseMask(), ChatHandler::getSelectedObject(), Loot::isLooted(), LANG_GAMEOBJECT_NOT_EXIST, LANG_GOINFO_DISPLAYID, LANG_GOINFO_ENTRY, LANG_GOINFO_LOOTID, LANG_GOINFO_NAME, LANG_GOINFO_TYPE, GameObject::loot, GameObjectTemplate::name, ChatHandler::PSendSysMessage(), ChatHandler::SetSentErrorMessage(), sObjectMgr, Object::ToGameObject(), GameObjectTemplate::type, and TYPEID_GAMEOBJECT.
HandleGameObjectMoveCommand()
static bool gobject_commandscript::HandleGameObjectMoveCommand (ChatHandler * handler, GameObjectSpawnId guidLow, Optional< std::array< float, 3 >> xyz) inline static
Definition at line 369 of file cs_gobject.cpp.
     {
         if (!guidLow)
             return false;
         GameObject* object = handler->GetObjectFromPlayerMapByDbGuid(guidLow);
         if (!object)
         {
             handler->PSendSysMessage(LANG_COMMAND_OBJNOTFOUND, uint32(guidLow));
             handler->SetSentErrorMessage(true);
             return false;
         }
         Position pos;
         if (xyz)
         {
             pos = { (*xyz)[0], (*xyz)[1], (*xyz)[2] };
             if (!MapMgr::IsValidMapCoord(object->GetMapId(), pos))
             {
                 handler->PSendSysMessage(LANG_INVALID_TARGET_COORD, pos.GetPositionX(), pos.GetPositionY(), object->GetMapId());
                 handler->SetSentErrorMessage(true);
                 return false;
             }
         }
         else
         {
             pos = handler->GetSession()->GetPlayer()->GetPosition();
         }
         Map* map = object->GetMap();
         pos.SetOrientation(object->GetOrientation());
         object->Relocate(pos);
         // update which cell has this gameobject registered for loading
         sObjectMgr->RemoveGameobjectFromGrid(guidLow, object->GetGOData());
         object->SaveToDB();
         sObjectMgr->AddGameobjectToGrid(guidLow, object->GetGOData());
         // Generate a completely new spawn with new guid
         // 3.3.5a client caches recently deleted objects and brings them back to life
         // when CreateObject block for this guid is received again
         // however it entirely skips parsing that block and only uses already known location
         object->Delete();
         object = new GameObject();
         if (!object->LoadGameObjectFromDB(guidLow, map, true))
         {
             delete object;
             return false;
         }
         handler->PSendSysMessage(LANG_COMMAND_MOVEOBJMESSAGE, object->GetSpawnId(), object->GetGOInfo()->name.c_str(), object->GetSpawnId());
         return true;
     }
References GameObject::GetGOData(), GameObject::GetGOInfo(), WorldLocation::GetMapId(), ChatHandler::GetObjectFromPlayerMapByDbGuid(), Position::GetOrientation(), WorldSession::GetPlayer(), Position::GetPosition(), Position::GetPositionX(), Position::GetPositionY(), ChatHandler::GetSession(), GameObject::GetSpawnId(), MapMgr::IsValidMapCoord(), LANG_COMMAND_MOVEOBJMESSAGE, LANG_COMMAND_OBJNOTFOUND, LANG_INVALID_TARGET_COORD, GameObject::LoadGameObjectFromDB(), GameObjectTemplate::name, ChatHandler::PSendSysMessage(), Position::SetOrientation(), ChatHandler::SetSentErrorMessage(), and sObjectMgr.
HandleGameObjectNearCommand()
static bool gobject_commandscript::HandleGameObjectNearCommand (ChatHandler * handler, Optional< float > dist) inline static
Definition at line 451 of file cs_gobject.cpp.
     {
         float distance = dist.value_or(10.0f);
         uint32 count = 0;
         Player* player = handler->GetSession()->GetPlayer();
         WorldDatabasePreparedStatement* stmt = WorldDatabase.GetPreparedStatement(WORLD_SEL_GAMEOBJECT_NEAREST);
         stmt->setFloat(0, player->GetPositionX());
         stmt->setFloat(1, player->GetPositionY());
         stmt->setFloat(2, player->GetPositionZ());
         stmt->setUInt32(3, player->GetMapId());
         stmt->setFloat(4, player->GetPositionX());
         stmt->setFloat(5, player->GetPositionY());
         stmt->setFloat(6, player->GetPositionZ());
         stmt->setFloat(7, distance * distance);
         stmt->setUInt32(8, player->GetPhaseMask());
         PreparedQueryResult result = WorldDatabase.Query(stmt);
         if (result)
         {
             do
             {
                 Field* fields = result->Fetch();
                 ObjectGuid::LowType guid = fields[0].GetUInt32();
                 uint32 entry = fields[1].GetUInt32();
                 float x = fields[2].GetFloat();
                 float y = fields[3].GetFloat();
                 float z = fields[4].GetFloat();
                 uint16 mapId = fields[5].GetUInt16();
                 GameObjectTemplate const* gameObjectInfo = sObjectMgr->GetGameObjectTemplate(entry);
                 if (!gameObjectInfo)
                     continue;
                 handler->PSendSysMessage(LANG_GO_LIST_CHAT, guid, entry, guid, gameObjectInfo->name.c_str(), x, y, z, mapId, "", "");
                 ++count;
             } while (result->NextRow());
         }
         handler->PSendSysMessage(LANG_COMMAND_NEAROBJMESSAGE, distance, count);
         return true;
     }
References Field::GetFloat(), WorldLocation::GetMapId(), WorldObject::GetPhaseMask(), WorldSession::GetPlayer(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ChatHandler::GetSession(), Field::GetUInt16(), Field::GetUInt32(), LANG_COMMAND_NEAROBJMESSAGE, LANG_GO_LIST_CHAT, GameObjectTemplate::name, ChatHandler::PSendSysMessage(), PreparedStatementBase::setFloat(), PreparedStatementBase::setUInt32(), sObjectMgr, WORLD_SEL_GAMEOBJECT_NEAREST, and WorldDatabase.
HandleGameObjectSetPhaseCommand()
static bool gobject_commandscript::HandleGameObjectSetPhaseCommand (ChatHandler * handler, GameObjectSpawnId guidLow, uint32 phaseMask) inline static
Definition at line 426 of file cs_gobject.cpp.
     {
         if (!guidLow)
             return false;
         GameObject* object = handler->GetObjectFromPlayerMapByDbGuid(guidLow);
         if (!object)
         {
             handler->PSendSysMessage(LANG_COMMAND_OBJNOTFOUND, uint32(guidLow));
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (!phaseMask)
         {
             handler->SendSysMessage(LANG_BAD_VALUE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         object->SetPhaseMask(phaseMask, true);
         object->SaveToDB();
         return true;
     }
References ChatHandler::GetObjectFromPlayerMapByDbGuid(), LANG_BAD_VALUE, LANG_COMMAND_OBJNOTFOUND, ChatHandler::PSendSysMessage(), ChatHandler::SendSysMessage(), and ChatHandler::SetSentErrorMessage().
HandleGameObjectSetStateCommand()
static bool gobject_commandscript::HandleGameObjectSetStateCommand (ChatHandler * handler, GameObjectSpawnId guidLow, int32 objectType, Optional< uint32 > objectState) inline static
Definition at line 554 of file cs_gobject.cpp.
     {
         if (!guidLow)
             return false;
         GameObject* object = handler->GetObjectFromPlayerMapByDbGuid(guidLow);
         if (!object)
         {
             handler->PSendSysMessage(LANG_COMMAND_OBJNOTFOUND, uint32(guidLow));
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (objectType < 0)
         {
             if (objectType == -1)
                 object->SendObjectDeSpawnAnim(object->GetGUID());
             else if (objectType == -2)
                 return false;
             return true;
         }
         if (!objectState)
             return false;
         if (objectType < 4)
             object->SetByteValue(GAMEOBJECT_BYTES_1, objectType, *objectState);
         else if (objectType == 4)
         {
             WorldPacket data(SMSG_GAMEOBJECT_CUSTOM_ANIM, 8+4);
             data << object->GetGUID();
             data << static_cast<uint32>(*objectState);
             object->SendMessageToSet(&data, true);
         }
         handler->PSendSysMessage("Set gobject type %d state %u", objectType, *objectState);
         return true;
     }
References GAMEOBJECT_BYTES_1, Object::GetGUID(), ChatHandler::GetObjectFromPlayerMapByDbGuid(), LANG_COMMAND_OBJNOTFOUND, ChatHandler::PSendSysMessage(), ChatHandler::SetSentErrorMessage(), and SMSG_GAMEOBJECT_CUSTOM_ANIM.
HandleGameObjectTargetCommand()
static bool gobject_commandscript::HandleGameObjectTargetCommand (ChatHandler * handler, Optional< Variant< GameObjectEntry, std::string_view >> objectId) inline static
Definition at line 182 of file cs_gobject.cpp.
     {
         Player* player = handler->GetSession()->GetPlayer();
         QueryResult result;
         GameEventMgr::ActiveEvents const& activeEventsList = sGameEventMgr->GetActiveEventList();
         if (objectId)
         {
             if (objectId->holds_alternative<GameObjectEntry>())
             {
                 result = WorldDatabase.PQuery("SELECT guid, id, position_x, position_y, position_z, orientation, map, phaseMask, (POW(position_x - '%f', 2) + POW(position_y - '%f', 2) + POW(position_z - '%f', 2)) AS order_ FROM gameobject WHERE map = '%i' AND id = '%u' ORDER BY order_ ASC LIMIT 1",
                                               player->GetPositionX(), player->GetPositionY(), player->GetPositionZ(), player->GetMapId(), static_cast<uint32>(objectId->get<GameObjectEntry>()));
             }
             else
             {
                 std::string name = std::string(objectId->get<std::string_view>());
                 WorldDatabase.EscapeString(name);
                 result = WorldDatabase.PQuery(
                         "SELECT guid, id, position_x, position_y, position_z, orientation, map, phaseMask, (POW(position_x - %f, 2) + POW(position_y - %f, 2) + POW(position_z - %f, 2)) AS order_ "
                         "FROM gameobject LEFT JOIN gameobject_template ON gameobject_template.entry = gameobject.id WHERE map = %i AND name LIKE '%%%s%%' ORDER BY order_ ASC LIMIT 1",
                         player->GetPositionX(), player->GetPositionY(), player->GetPositionZ(), player->GetMapId(), name.c_str());
             }
         }
         else
         {
             std::ostringstream eventFilter;
             eventFilter << " AND (eventEntry IS NULL ";
             bool initString = true;
             for (GameEventMgr::ActiveEvents::const_iterator itr = activeEventsList.begin(); itr != activeEventsList.end(); ++itr)
             {
                 if (initString)
                 {
                     eventFilter  <<  "OR eventEntry IN (" << *itr;
                     initString = false;
                 }
                 else
                     eventFilter << ',' << *itr;
             }
             if (!initString)
                 eventFilter << "))";
             else
                 eventFilter << ')';
             result = WorldDatabase.PQuery("SELECT gameobject.guid, id, position_x, position_y, position_z, orientation, map, phaseMask, "
                                           "(POW(position_x - %f, 2) + POW(position_y - %f, 2) + POW(position_z - %f, 2)) AS order_ FROM gameobject "
                                           "LEFT OUTER JOIN game_event_gameobject on gameobject.guid = game_event_gameobject.guid WHERE map = '%i' %s ORDER BY order_ ASC LIMIT 10",
                                           handler->GetSession()->GetPlayer()->GetPositionX(), handler->GetSession()->GetPlayer()->GetPositionY(), handler->GetSession()->GetPlayer()->GetPositionZ(),
                                           handler->GetSession()->GetPlayer()->GetMapId(), eventFilter.str().c_str());
         }
         if (!result)
         {
             handler->SendSysMessage(LANG_COMMAND_TARGETOBJNOTFOUND);
             return true;
         }
         bool found = false;
         float x, y, z, o;
         ObjectGuid::LowType guidLow;
         uint32 id, phase;
         uint16 mapId;
         uint32 poolId;
         do
         {
             Field* fields = result->Fetch();
             guidLow = fields[0].GetUInt32();
             id =      fields[1].GetUInt32();
             x =       fields[2].GetFloat();
             y =       fields[3].GetFloat();
             z =       fields[4].GetFloat();
             o =       fields[5].GetFloat();
             mapId =   fields[6].GetUInt16();
             phase =   fields[7].GetUInt32();
             poolId =  sPoolMgr->IsPartOfAPool<GameObject>(guidLow);
             if (!poolId || sPoolMgr->IsSpawnedObject<GameObject>(guidLow))
                 found = true;
         } while (result->NextRow() && !found);
         if (!found)
         {
             handler->PSendSysMessage(LANG_GAMEOBJECT_NOT_EXIST, id);
             return false;
         }
         GameObjectTemplate const* objectInfo = sObjectMgr->GetGameObjectTemplate(id);
         if (!objectInfo)
         {
             handler->PSendSysMessage(LANG_GAMEOBJECT_NOT_EXIST, id);
             return false;
         }
         GameObject* target = handler->GetObjectFromPlayerMapByDbGuid(guidLow);
         handler->PSendSysMessage(LANG_GAMEOBJECT_DETAIL, guidLow, objectInfo->name.c_str(), guidLow, id, x, y, z, mapId, o, phase);
         if (target)
         {
             int32 curRespawnDelay = int32(target->GetRespawnTimeEx() - time(nullptr));
             if (curRespawnDelay < 0)
                 curRespawnDelay = 0;
             std::string curRespawnDelayStr = secsToTimeString(curRespawnDelay, true);
             std::string defRespawnDelayStr = secsToTimeString(target->GetRespawnDelay(), true);
             handler->PSendSysMessage(LANG_COMMAND_RAWPAWNTIMES, defRespawnDelayStr.c_str(), curRespawnDelayStr.c_str());
         }
         return true;
     }
References Field::GetFloat(), WorldLocation::GetMapId(), ChatHandler::GetObjectFromPlayerMapByDbGuid(), WorldSession::GetPlayer(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GameObject::GetRespawnDelay(), GameObject::GetRespawnTimeEx(), ChatHandler::GetSession(), Field::GetUInt16(), Field::GetUInt32(), LANG_COMMAND_RAWPAWNTIMES, LANG_COMMAND_TARGETOBJNOTFOUND, LANG_GAMEOBJECT_DETAIL, LANG_GAMEOBJECT_NOT_EXIST, GameObjectTemplate::name, ChatHandler::PSendSysMessage(), secsToTimeString(), ChatHandler::SendSysMessage(), sGameEventMgr, sObjectMgr, sPoolMgr, and WorldDatabase.
HandleGameObjectTurnCommand()
static bool gobject_commandscript::HandleGameObjectTurnCommand (ChatHandler * handler, GameObjectSpawnId guidLow, Optional< float > oz, Optional< float > oy, Optional< float > ox) inline static
Definition at line 330 of file cs_gobject.cpp.
     {
         if (!guidLow)
             return false;
         GameObject* object = handler->GetObjectFromPlayerMapByDbGuid(guidLow);
         if (!object)
         {
             handler->PSendSysMessage(LANG_COMMAND_OBJNOTFOUND, uint32(guidLow));
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (!oz)
             oz = handler->GetSession()->GetPlayer()->GetOrientation();
         Map* map = object->GetMap();
         object->Relocate(object->GetPositionX(), object->GetPositionY(), object->GetPositionZ(), *oz);
         object->SetLocalRotationAngles(*oz, oy.value_or(0.0f), ox.value_or(0.0f));
         object->SaveToDB();
         // Generate a completely new spawn with new guid
         // 3.3.5a client caches recently deleted objects and brings them back to life
         // when CreateObject block for this guid is received again
         // however it entirely skips parsing that block and only uses already known location
         object->Delete();
         object = new GameObject();
         if (!object->LoadGameObjectFromDB(guidLow, map, true))
         {
             delete object;
             return false;
         }
         handler->PSendSysMessage(LANG_COMMAND_TURNOBJMESSAGE, object->GetSpawnId(), object->GetGOInfo()->name.c_str(), object->GetSpawnId());
         return true;
     }
References GameObject::GetGOInfo(), ChatHandler::GetObjectFromPlayerMapByDbGuid(), Position::GetOrientation(), WorldSession::GetPlayer(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ChatHandler::GetSession(), GameObject::GetSpawnId(), LANG_COMMAND_OBJNOTFOUND, LANG_COMMAND_TURNOBJMESSAGE, GameObject::LoadGameObjectFromDB(), GameObjectTemplate::name, ChatHandler::PSendSysMessage(), and ChatHandler::SetSentErrorMessage().
The documentation for this class was generated from the following file:
src/server/scripts/Commands/cs_gobject.cpp