Azerotcore-wotlk: at_ancient_leaf Class Reference
at_ancient_leaf Class Reference
Public Member Functions
at_ancient_leaf ()
bool OnTrigger (Player *player, AreaTrigger const *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 117 of file zone_felwood.cpp.
Constructor & Destructor Documentation
at_ancient_leaf()
at_ancient_leaf::at_ancient_leaf () inline
Definition at line 120 of file zone_felwood.cpp.
 : AreaTriggerScript("at_ancient_leaf") { }
Member Function Documentation
OnTrigger()
bool at_ancient_leaf::OnTrigger (Player * player, AreaTrigger const *) inline override virtual
Reimplemented from AreaTriggerScript.
Definition at line 122 of file zone_felwood.cpp.
     {
         if (player->IsGameMaster() || !player->IsAlive())
             return false;
         // Handle Call Ancients event start - The area trigger summons 3 ancients
         if ((player->GetQuestStatus(QUEST_ANCIENT_LEAF) == QUEST_STATUS_COMPLETE) || (player->GetQuestStatus(QUEST_ANCIENT_LEAF) == QUEST_STATUS_REWARDED))
         {
             // If ancients are already spawned, skip the rest
             if (GetClosestCreatureWithEntry(player, NPC_VARTRUS, 50.0f) || GetClosestCreatureWithEntry(player, NPC_STOMA, 50.0f) || GetClosestCreatureWithEntry(player, NPC_HASTAT, 50.0f))
                 return true;
             player->GetMap()->SummonCreatureGroup(CREATURE_GROUP_ANCIENTS);
         }
         return false;
     }
References CREATURE_GROUP_ANCIENTS, GetClosestCreatureWithEntry(), WorldObject::GetMap(), Player::GetQuestStatus(), Unit::IsAlive(), Player::IsGameMaster(), NPC_HASTAT, NPC_STOMA, NPC_VARTRUS, QUEST_ANCIENT_LEAF, QUEST_STATUS_COMPLETE, QUEST_STATUS_REWARDED, and Map::SummonCreatureGroup().
The documentation for this class was generated from the following file:
src/server/scripts/Kalimdor/zone_felwood.cpp