Azerotcore-wotlk: Acore::Impl::ChatCommands::ArgInfo< T, std::enable_if_t< std::is_enum_v< T > > > Struct Template Reference
Acore::Impl::ChatCommands::ArgInfo< T, std::enable_if_t< std::is_enum_v< T > > > Struct Template Reference
#include <ChatCommandArgs.h>
Public Types
using SearchMap = std::map< std::string_view, Optional< T >, StringCompareLessI_T >
Static Public Member Functions
static SearchMap MakeSearchMap ()
static T const * Match (std::string_view s)
static ChatCommandResult TryConsume (T &val, ChatHandler const *handler, std::string_view args)
Static Public Attributes
static SearchMap const _map = MakeSearchMap()
Detailed Description
template<typename T>
struct Acore::Impl::ChatCommands::ArgInfo< T, std::enable_if_t< std::is_enum_v< T > > >
Definition at line 128 of file ChatCommandArgs.h.
Member Typedef Documentation
SearchMap
template<typename T > using Acore::Impl::ChatCommands::ArgInfo< T, std::enable_if_t< std::is_enum_v< T > > >::SearchMap = std::map<std::string_view, Optional<T>, StringCompareLessI_T>
Definition at line 130 of file ChatCommandArgs.h.
Member Function Documentation
MakeSearchMap()
template<typename T > static SearchMap Acore::Impl::ChatCommands::ArgInfo< T, std::enable_if_t< std::is_enum_v< T > > >::MakeSearchMap () inline static
Definition at line 131 of file ChatCommandArgs.h.
         {
             SearchMap map;
             for (T val : EnumUtils::Iterate<T>())
             {
                 EnumText text = EnumUtils::ToString(val);
                 std::string_view title(text.Title);
                 std::string_view constant(text.Constant);
                 auto [constantIt, constantNew] = map.try_emplace(title, val);
                 if (!constantNew)
                     constantIt->second = std::nullopt;
                 if (title != constant)
                 {
                     auto [titleIt, titleNew] = map.try_emplace(title, val);
                     if (!titleNew)
                         titleIt->second = std::nullopt;
                 }
             }
             return map;
         }
References EnumText::Constant, EnumText::Title, and EnumUtils::ToString().
Match()
template<typename T > static T const* Acore::Impl::ChatCommands::ArgInfo< T, std::enable_if_t< std::is_enum_v< T > > >::Match (std::string_view s) inline static
Definition at line 157 of file ChatCommandArgs.h.
         {
             auto it = _map.lower_bound(s);
             if (it == _map.end() || !StringStartsWithI(it->first, s)) // not a match
                 return nullptr;
             if (!StringEqualI(it->first, s)) // we don't have an exact match - check if it is unique
             {
                 auto it2 = it;
                 ++it2;
                 if ((it2 != _map.end()) && StringStartsWithI(it2->first, s)) // not unique
                     return nullptr;
             }
             if (it->second)
                 return &*it->second;
             else
                 return nullptr;
         }
References StringEqualI(), and StringStartsWithI().
TryConsume()
template<typename T > static ChatCommandResult Acore::Impl::ChatCommands::ArgInfo< T, std::enable_if_t< std::is_enum_v< T > > >::TryConsume (T & val, ChatHandler const * handler, std::string_view args) inline static
Definition at line 177 of file ChatCommandArgs.h.
         {
             std::string_view strVal;
             ChatCommandResult next1 = ArgInfo<std::string_view>::TryConsume(strVal, handler, args);
             if (next1)
             {
                 if (T const* match = Match(strVal))
                 {
                     val = *match;
                     return next1;
                 }
             }
             // Value not found. Try to parse arg as underlying type and cast it to enum type
             using U = std::underlying_type_t<T>;
             U uVal = 0;
             if (ChatCommandResult next2 = ArgInfo<U>::TryConsume(uVal, handler, args))
             {
                 if (EnumUtils::IsValid<T>(uVal))
                 {
                     val = static_cast<T>(uVal);
                     return next2;
                 }
             }
             if (next1)
                 return FormatAcoreString(handler, LANG_CMDPARSER_STRING_VALUE_INVALID, STRING_VIEW_FMT_ARG(strVal), GetTypeName<T>().c_str());
             else
                 return next1;
         }
References Acore::Impl::ChatCommands::FormatAcoreString(), LANG_CMDPARSER_STRING_VALUE_INVALID, and STRING_VIEW_FMT_ARG.
Member Data Documentation
_map
template<typename T > SearchMap const Acore::Impl::ChatCommands::ArgInfo< T, std::enable_if_t< std::is_enum_v< T > > >::_map = MakeSearchMap() inline static
Definition at line 155 of file ChatCommandArgs.h.
The documentation for this struct was generated from the following file:
src/server/game/Chat/ChatCommands/ChatCommandArgs.h