Azerotcore-wotlk: src/server/game/DataStores/DBCStores.cpp File Reference
DBCStores.cpp File Reference
#include "BattlegroundMgr.h"
#include "DBCFileLoader.h"
#include "DBCfmt.h"
#include "DBCStores.h"
#include "Errors.h"
#include "Log.h"
#include "SharedDefines.h"
#include "SpellMgr.h"
#include "TransportMgr.h"
#include "World.h"
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
Macros
#define LOAD_DBC(store, file, dbtable) LoadDBC(availableDbcLocales, bad_dbc_files, store, dbcPath, file, dbtable)
Typedefs
typedef std::map< uint16, uint32 > AreaFlagByAreaID
typedef std::map< uint32, uint32 > AreaFlagByMapID
typedef std::tuple< int16, int8, int32 > WMOAreaTableKey
typedef std::map< WMOAreaTableKey, WMOAreaTableEntry const * > WMOAreaInfoByTripple
typedef std::map< uint32, SimpleFactionsList > FactionTeamMap
typedef std::list< std::string > StoreProblemList
Functions
static bool LoadDBC_assert_print (uint32 fsize, uint32 rsize, const std::string &filename)
template<class T >
void LoadDBC (uint32 &availableDbcLocales, StoreProblemList &errors, DBCStorage< T > &storage, std::string const &dbcPath, std::string const &filename, char const *dbTable=nullptr)
void LoadDBCStores (const std::string &dataPath)
G3D::Vector3 TranslateLocation (G3D::Vector4 const *DBCPosition, G3D::Vector3 const *basePosition, G3D::Vector3 const *splineVector)
bool readCamera (M2Camera const *cam, uint32 buffSize, M2Header const *header, CinematicCameraEntry const *dbcentry)
void LoadM2Cameras (const std::string &dataPath)
SimpleFactionsList const * GetFactionTeamList (uint32 faction)
char const * GetPetName (uint32 petfamily, uint32 dbclang)
TalentSpellPos const * GetTalentSpellPos (uint32 spellId)
uint32 GetTalentSpellCost (uint32 spellId)
WMOAreaTableEntry const * GetWMOAreaTableEntryByTripple (int32 rootid, int32 adtid, int32 groupid)
uint32 GetVirtualMapForMapAndZone (uint32 mapid, uint32 zoneId)
ContentLevels GetContentLevelsForMapAndZone (uint32 mapid, uint32 zoneId)
void Zone2MapCoordinates (float &x, float &y, uint32 zone)
void Map2ZoneCoordinates (float &x, float &y, uint32 zone)
MapDifficulty const * GetMapDifficultyData (uint32 mapId, Difficulty difficulty)
MapDifficulty const * GetDownscaledMapDifficultyData (uint32 mapId, Difficulty &difficulty)
PvPDifficultyEntry const * GetBattlegroundBracketByLevel (uint32 mapid, uint32 level)
PvPDifficultyEntry const * GetBattlegroundBracketById (uint32 mapid, BattlegroundBracketId id)
uint32 const * GetTalentTabPages (uint8 cls)
bool IsSharedDifficultyMap (uint32 mapid)
uint32 GetLiquidFlags (uint32 liquidType)
CharStartOutfitEntry const * GetCharStartOutfitEntry (uint8 race, uint8 class_, uint8 gender)
LFGDungeonEntry const * GetLFGDungeon (uint32 mapId, Difficulty difficulty)
Returns LFGDungeonEntry for a specific map and difficulty. Will return first found entry if multiple dungeons use the same map (such as Scarlet Monastery)
uint32 GetDefaultMapLight (uint32 mapId)
SkillRaceClassInfoEntry const * GetSkillRaceClassInfo (uint32 skill, uint8 race, uint8 class_)
Variables
DBCStorage< AreaTableEntry > sAreaTableStore (AreaTableEntryfmt)
DBCStorage< AreaGroupEntry > sAreaGroupStore (AreaGroupEntryfmt)
DBCStorage< AreaPOIEntry > sAreaPOIStore (AreaPOIEntryfmt)
static WMOAreaInfoByTripple sWMOAreaInfoByTripple
DBCStorage< AchievementEntry > sAchievementStore (Achievementfmt)
DBCStorage< AchievementCategoryEntry > sAchievementCategoryStore (AchievementCategoryfmt)
DBCStorage< AchievementCriteriaEntry > sAchievementCriteriaStore (AchievementCriteriafmt)
DBCStorage< AuctionHouseEntry > sAuctionHouseStore (AuctionHouseEntryfmt)
DBCStorage< BankBagSlotPricesEntry > sBankBagSlotPricesStore (BankBagSlotPricesEntryfmt)
DBCStorage< BattlemasterListEntry > sBattlemasterListStore (BattlemasterListEntryfmt)
DBCStorage< BarberShopStyleEntry > sBarberShopStyleStore (BarberShopStyleEntryfmt)
DBCStorage< CharStartOutfitEntry > sCharStartOutfitStore (CharStartOutfitEntryfmt)
std::map< uint32, CharStartOutfitEntry const * > sCharStartOutfitMap
DBCStorage< CharTitlesEntry > sCharTitlesStore (CharTitlesEntryfmt)
DBCStorage< ChatChannelsEntry > sChatChannelsStore (ChatChannelsEntryfmt)
DBCStorage< ChrClassesEntry > sChrClassesStore (ChrClassesEntryfmt)
DBCStorage< ChrRacesEntry > sChrRacesStore (ChrRacesEntryfmt)
DBCStorage< CinematicCameraEntry > sCinematicCameraStore (CinematicCameraEntryfmt)
DBCStorage< CinematicSequencesEntry > sCinematicSequencesStore (CinematicSequencesEntryfmt)
DBCStorage< CreatureDisplayInfoEntry > sCreatureDisplayInfoStore (CreatureDisplayInfofmt)
DBCStorage< CreatureFamilyEntry > sCreatureFamilyStore (CreatureFamilyfmt)
DBCStorage< CreatureModelDataEntry > sCreatureModelDataStore (CreatureModelDatafmt)
DBCStorage< CreatureSpellDataEntry > sCreatureSpellDataStore (CreatureSpellDatafmt)
DBCStorage< CreatureTypeEntry > sCreatureTypeStore (CreatureTypefmt)
DBCStorage< CurrencyTypesEntry > sCurrencyTypesStore (CurrencyTypesfmt)
DBCStorage< DestructibleModelDataEntry > sDestructibleModelDataStore (DestructibleModelDatafmt)
DBCStorage< DungeonEncounterEntry > sDungeonEncounterStore (DungeonEncounterfmt)
DBCStorage< DurabilityQualityEntry > sDurabilityQualityStore (DurabilityQualityfmt)
DBCStorage< DurabilityCostsEntry > sDurabilityCostsStore (DurabilityCostsfmt)
DBCStorage< EmotesEntry > sEmotesStore (EmotesEntryfmt)
DBCStorage< EmotesTextEntry > sEmotesTextStore (EmotesTextEntryfmt)
static FactionTeamMap sFactionTeamMap
DBCStorage< FactionEntry > sFactionStore (FactionEntryfmt)
DBCStorage< FactionTemplateEntry > sFactionTemplateStore (FactionTemplateEntryfmt)
DBCStorage< GameObjectDisplayInfoEntry > sGameObjectDisplayInfoStore (GameObjectDisplayInfofmt)
DBCStorage< GemPropertiesEntry > sGemPropertiesStore (GemPropertiesEntryfmt)
DBCStorage< GlyphPropertiesEntry > sGlyphPropertiesStore (GlyphPropertiesfmt)
DBCStorage< GlyphSlotEntry > sGlyphSlotStore (GlyphSlotfmt)
DBCStorage< GtBarberShopCostBaseEntry > sGtBarberShopCostBaseStore (GtBarberShopCostBasefmt)
DBCStorage< GtCombatRatingsEntry > sGtCombatRatingsStore (GtCombatRatingsfmt)
DBCStorage< GtChanceToMeleeCritBaseEntry > sGtChanceToMeleeCritBaseStore (GtChanceToMeleeCritBasefmt)
DBCStorage< GtChanceToMeleeCritEntry > sGtChanceToMeleeCritStore (GtChanceToMeleeCritfmt)
DBCStorage< GtChanceToSpellCritBaseEntry > sGtChanceToSpellCritBaseStore (GtChanceToSpellCritBasefmt)
DBCStorage< GtChanceToSpellCritEntry > sGtChanceToSpellCritStore (GtChanceToSpellCritfmt)
DBCStorage< GtNPCManaCostScalerEntry > sGtNPCManaCostScalerStore (GtNPCManaCostScalerfmt)
DBCStorage< GtOCTClassCombatRatingScalarEntry > sGtOCTClassCombatRatingScalarStore (GtOCTClassCombatRatingScalarfmt)
DBCStorage< GtOCTRegenHPEntry > sGtOCTRegenHPStore (GtOCTRegenHPfmt)
DBCStorage< GtRegenHPPerSptEntry > sGtRegenHPPerSptStore (GtRegenHPPerSptfmt)
DBCStorage< GtRegenMPPerSptEntry > sGtRegenMPPerSptStore (GtRegenMPPerSptfmt)
DBCStorage< HolidaysEntry > sHolidaysStore (Holidaysfmt)
DBCStorage< ItemBagFamilyEntry > sItemBagFamilyStore (ItemBagFamilyfmt)
DBCStorage< ItemDisplayInfoEntry > sItemDisplayInfoStore (ItemDisplayTemplateEntryfmt)
DBCStorage< ItemExtendedCostEntry > sItemExtendedCostStore (ItemExtendedCostEntryfmt)
DBCStorage< ItemLimitCategoryEntry > sItemLimitCategoryStore (ItemLimitCategoryEntryfmt)
DBCStorage< ItemRandomPropertiesEntry > sItemRandomPropertiesStore (ItemRandomPropertiesfmt)
DBCStorage< ItemRandomSuffixEntry > sItemRandomSuffixStore (ItemRandomSuffixfmt)
DBCStorage< ItemSetEntry > sItemSetStore (ItemSetEntryfmt)
DBCStorage< LFGDungeonEntry > sLFGDungeonStore (LFGDungeonEntryfmt)
DBCStorage< LightEntry > sLightStore (LightEntryfmt)
DBCStorage< LiquidTypeEntry > sLiquidTypeStore (LiquidTypefmt)
DBCStorage< LockEntry > sLockStore (LockEntryfmt)
DBCStorage< MailTemplateEntry > sMailTemplateStore (MailTemplateEntryfmt)
DBCStorage< MapEntry > sMapStore (MapEntryfmt)
DBCStorage< MapDifficultyEntry > sMapDifficultyStore (MapDifficultyEntryfmt)
MapDifficultyMap sMapDifficultyMap
DBCStorage< MovieEntry > sMovieStore (MovieEntryfmt)
DBCStorage< OverrideSpellDataEntry > sOverrideSpellDataStore (OverrideSpellDatafmt)
DBCStorage< PowerDisplayEntry > sPowerDisplayStore (PowerDisplayfmt)
DBCStorage< PvPDifficultyEntry > sPvPDifficultyStore (PvPDifficultyfmt)
DBCStorage< QuestSortEntry > sQuestSortStore (QuestSortEntryfmt)
DBCStorage< QuestXPEntry > sQuestXPStore (QuestXPfmt)
DBCStorage< QuestFactionRewEntry > sQuestFactionRewardStore (QuestFactionRewardfmt)
DBCStorage< RandomPropertiesPointsEntry > sRandomPropertiesPointsStore (RandomPropertiesPointsfmt)
DBCStorage< ScalingStatDistributionEntry > sScalingStatDistributionStore (ScalingStatDistributionfmt)
DBCStorage< ScalingStatValuesEntry > sScalingStatValuesStore (ScalingStatValuesfmt)
DBCStorage< SkillLineEntry > sSkillLineStore (SkillLinefmt)
DBCStorage< SkillLineAbilityEntry > sSkillLineAbilityStore (SkillLineAbilityfmt)
DBCStorage< SkillRaceClassInfoEntry > sSkillRaceClassInfoStore (SkillRaceClassInfofmt)
SkillRaceClassInfoMap SkillRaceClassInfoBySkill
DBCStorage< SkillTiersEntry > sSkillTiersStore (SkillTiersfmt)
DBCStorage< SoundEntriesEntry > sSoundEntriesStore (SoundEntriesfmt)
DBCStorage< SpellItemEnchantmentEntry > sSpellItemEnchantmentStore (SpellItemEnchantmentfmt)
DBCStorage< SpellItemEnchantmentConditionEntry > sSpellItemEnchantmentConditionStore (SpellItemEnchantmentConditionfmt)
DBCStorage< SpellEntry > sSpellStore (SpellEntryfmt)
SpellCategoryStore sSpellsByCategoryStore
PetFamilySpellsStore sPetFamilySpellsStore
DBCStorage< SpellCastTimesEntry > sSpellCastTimesStore (SpellCastTimefmt)
DBCStorage< SpellCategoryEntry > sSpellCategoryStore (SpellCategoryfmt)
DBCStorage< SpellDifficultyEntry > sSpellDifficultyStore (SpellDifficultyfmt)
DBCStorage< SpellDurationEntry > sSpellDurationStore (SpellDurationfmt)
DBCStorage< SpellFocusObjectEntry > sSpellFocusObjectStore (SpellFocusObjectfmt)
DBCStorage< SpellRadiusEntry > sSpellRadiusStore (SpellRadiusfmt)
DBCStorage< SpellRangeEntry > sSpellRangeStore (SpellRangefmt)
DBCStorage< SpellRuneCostEntry > sSpellRuneCostStore (SpellRuneCostfmt)
DBCStorage< SpellShapeshiftEntry > sSpellShapeshiftStore (SpellShapeshiftfmt)
DBCStorage< SpellVisualEntry > sSpellVisualStore (SpellVisualfmt)
DBCStorage< StableSlotPricesEntry > sStableSlotPricesStore (StableSlotPricesfmt)
DBCStorage< SummonPropertiesEntry > sSummonPropertiesStore (SummonPropertiesfmt)
DBCStorage< TalentEntry > sTalentStore (TalentEntryfmt)
TalentSpellPosMap sTalentSpellPosMap
DBCStorage< TalentTabEntry > sTalentTabStore (TalentTabEntryfmt)
static uint32 sTalentTabPages [MAX_CLASSES][3]
DBCStorage< TaxiNodesEntry > sTaxiNodesStore (TaxiNodesEntryfmt)
TaxiMask sTaxiNodesMask
TaxiMask sOldContinentsNodesMask
TaxiMask sHordeTaxiNodesMask
TaxiMask sAllianceTaxiNodesMask
TaxiMask sDeathKnightTaxiNodesMask
TaxiPathSetBySource sTaxiPathSetBySource
DBCStorage< TaxiPathEntry > sTaxiPathStore (TaxiPathEntryfmt)
TaxiPathNodesByPath sTaxiPathNodesByPath
static DBCStorage< TaxiPathNodeEntry > sTaxiPathNodeStore (TaxiPathNodeEntryfmt)
DBCStorage< TeamContributionPointsEntry > sTeamContributionPointsStore (TeamContributionPointsfmt)
DBCStorage< TotemCategoryEntry > sTotemCategoryStore (TotemCategoryEntryfmt)
DBCStorage< TransportAnimationEntry > sTransportAnimationStore (TransportAnimationfmt)
DBCStorage< TransportRotationEntry > sTransportRotationStore (TransportRotationfmt)
DBCStorage< VehicleEntry > sVehicleStore (VehicleEntryfmt)
DBCStorage< VehicleSeatEntry > sVehicleSeatStore (VehicleSeatEntryfmt)
DBCStorage< WMOAreaTableEntry > sWMOAreaTableStore (WMOAreaTableEntryfmt)
DBCStorage< WorldMapAreaEntry > sWorldMapAreaStore (WorldMapAreaEntryfmt)
DBCStorage< WorldMapOverlayEntry > sWorldMapOverlayStore (WorldMapOverlayEntryfmt)
std::unordered_map< uint32, FlyByCameraCollection > sFlyByCameraStore
uint32 DBCFileCount = 0
Macro Definition Documentation
LOAD_DBC
#define LOAD_DBC (store, file, dbtable) LoadDBC(availableDbcLocales, bad_dbc_files, store, dbcPath, file, dbtable)
Typedef Documentation
AreaFlagByAreaID
typedef std::map<uint16, uint32> AreaFlagByAreaID
Definition at line 33 of file DBCStores.cpp.
AreaFlagByMapID
typedef std::map<uint32, uint32> AreaFlagByMapID
Definition at line 34 of file DBCStores.cpp.
FactionTeamMap
typedef std::map<uint32, SimpleFactionsList> FactionTeamMap
Definition at line 75 of file DBCStores.cpp.
StoreProblemList
typedef std::list<std::string> StoreProblemList
Definition at line 195 of file DBCStores.cpp.
WMOAreaInfoByTripple
typedef std::map<WMOAreaTableKey, WMOAreaTableEntry const*> WMOAreaInfoByTripple
Definition at line 37 of file DBCStores.cpp.
WMOAreaTableKey
typedef std::tuple<int16, int8, int32> WMOAreaTableKey
Definition at line 36 of file DBCStores.cpp.
Function Documentation
GetBattlegroundBracketById()
PvPDifficultyEntry const* GetBattlegroundBracketById (uint32 mapid, BattlegroundBracketId id)
Definition at line 1056 of file DBCStores.cpp.
 {
     for (PvPDifficultyEntry const* entry : sPvPDifficultyStore)
         if (entry->mapId == mapid && entry->GetBracketId() == id)
             return entry;
     return nullptr;
 }
References sPvPDifficultyStore.
Referenced by BattlegroundQueue::BattlegroundQueueUpdate().
GetBattlegroundBracketByLevel()
PvPDifficultyEntry const* GetBattlegroundBracketByLevel (uint32 mapid, uint32 level)
Definition at line 1034 of file DBCStores.cpp.
 {
     PvPDifficultyEntry const* maxEntry = nullptr;              // used for level > max listed level case
     for (PvPDifficultyEntry const* entry : sPvPDifficultyStore)
     {
         // skip unrelated and too-high brackets
         if (entry->mapId != mapid || entry->minLevel > level)
             continue;
         // exactly fit
         if (entry->maxLevel >= level)
             return entry;
         // remember for possible out-of-range case (search higher from existed)
         if (!maxEntry || maxEntry->maxLevel < entry->maxLevel)
             maxEntry = entry;
     }
     return maxEntry;
 }
References PvPDifficultyEntry::maxLevel, and sPvPDifficultyStore.
Referenced by BattlegroundMgr::BuildBattlegroundListPacket(), Group::CanJoinBattlegroundQueue(), MapInstanced::CreateBattleground(), WorldSession::HandleBattleFieldPortOpcode(), WorldSession::HandleBattlefieldStatusOpcode(), WorldSession::HandleBattlemasterJoinArena(), and WorldSession::HandleBattlemasterJoinOpcode().
GetCharStartOutfitEntry()
CharStartOutfitEntry const* GetCharStartOutfitEntry (uint8 race, uint8 class_, uint8 gender)
Definition at line 1083 of file DBCStores.cpp.
 {
     std::map<uint32, CharStartOutfitEntry const*>::const_iterator itr = sCharStartOutfitMap.find(race | (class_ << 8) | (gender << 16));
     if (itr == sCharStartOutfitMap.end())
         return nullptr;
     return itr->second;
 }
References sCharStartOutfitMap.
Referenced by Player::Create(), and ObjectMgr::PlayerCreateInfoAddItemHelper().
GetContentLevelsForMapAndZone()
ContentLevels GetContentLevelsForMapAndZone (uint32 mapid, uint32 zoneId)
Definition at line 955 of file DBCStores.cpp.
 {
     mapid = GetVirtualMapForMapAndZone(mapid, zoneId);
     if (mapid < 2)
         return CONTENT_1_60;
     MapEntry const* mapEntry = sMapStore.LookupEntry(mapid);
     if (!mapEntry)
         return CONTENT_1_60;
     switch (mapEntry->Expansion())
     {
         default:
             return CONTENT_1_60;
         case 1:
             return CONTENT_61_70;
         case 2:
             return CONTENT_71_80;
     }
 }
References CONTENT_1_60, CONTENT_61_70, CONTENT_71_80, MapEntry::Expansion(), GetVirtualMapForMapAndZone(), and sMapStore.
Referenced by Acore::XP::Gain().
GetDefaultMapLight()
uint32 GetDefaultMapLight (uint32 mapId)
Definition at line 1102 of file DBCStores.cpp.
 {
     for (int32 i = sLightStore.GetNumRows(); i >= 0; --i)
     {
         LightEntry const* light = sLightStore.LookupEntry(uint32(i));
         if (!light)
             continue;
         if (light->MapId == mapId && light->X == 0.0f && light->Y == 0.0f && light->Z == 0.0f)
             return light->Id;
     }
     return 0;
 }
References LightEntry::Id, LightEntry::MapId, sLightStore, LightEntry::X, LightEntry::Y, and LightEntry::Z.
GetDownscaledMapDifficultyData()
MapDifficulty const* GetDownscaledMapDifficultyData (uint32 mapId, Difficulty & difficulty)
Definition at line 1008 of file DBCStores.cpp.
 {
     uint32 tmpDiff = difficulty;
     MapDifficulty const* mapDiff = GetMapDifficultyData(mapId, Difficulty(tmpDiff));
     if (!mapDiff)
     {
         if (tmpDiff > RAID_DIFFICULTY_25MAN_NORMAL) // heroic, downscale to normal
             tmpDiff -= 2;
         else
             tmpDiff -= 1;   // any non-normal mode for raids like tbc (only one mode)
         // pull new data
         mapDiff = GetMapDifficultyData(mapId, Difficulty(tmpDiff)); // we are 10 normal or 25 normal
         if (!mapDiff)
         {
             tmpDiff -= 1;
             mapDiff = GetMapDifficultyData(mapId, Difficulty(tmpDiff)); // 10 normal
         }
     }
     difficulty = Difficulty(tmpDiff);
     return mapDiff;
 }
References GetMapDifficultyData(), and RAID_DIFFICULTY_25MAN_NORMAL.
Referenced by MapInstanced::CreateInstance(), DisableMgr::IsDisabledFor(), MapMgr::PlayerCannotEnter(), InstanceSaveMgr::PlayerGetBoundInstance(), and Player::Satisfy().
GetFactionTeamList()
SimpleFactionsList const* GetFactionTeamList (uint32 faction)
Definition at line 897 of file DBCStores.cpp.
 {
     FactionTeamMap::const_iterator itr = sFactionTeamMap.find(faction);
     if (itr != sFactionTeamMap.end())
         return &itr->second;
     return nullptr;
 }
References sFactionTeamMap.
Referenced by ReputationMgr::SetReputation().
GetLFGDungeon()
LFGDungeonEntry const* GetLFGDungeon (uint32 mapId, Difficulty difficulty)
Returns LFGDungeonEntry for a specific map and difficulty. Will return first found entry if multiple dungeons use the same map (such as Scarlet Monastery)
Definition at line 1093 of file DBCStores.cpp.
 {
     for (LFGDungeonEntry const* dungeon : sLFGDungeonStore)
         if (dungeon->map == int32(mapId) && Difficulty(dungeon->difficulty) == difficulty)
             return dungeon;
     return nullptr;
 }
References sLFGDungeonStore.
Referenced by Player::RewardReputation().
GetLiquidFlags()
uint32 GetLiquidFlags (uint32 liquidType)
Definition at line 1075 of file DBCStores.cpp.
 {
     if (LiquidTypeEntry const* liq = sLiquidTypeStore.LookupEntry(liquidType))
         return 1 << liq->Type;
     return 0;
 }
References sLiquidTypeStore.
Referenced by World::SetInitialWorldSettings().
GetMapDifficultyData()
MapDifficulty const* GetMapDifficultyData (uint32 mapId, Difficulty difficulty)
Definition at line 1002 of file DBCStores.cpp.
 {
     MapDifficultyMap::const_iterator itr = sMapDifficultyMap.find(MAKE_PAIR32(mapId, difficulty));
     return itr != sMapDifficultyMap.end() ? &itr->second : nullptr;
 }
References MAKE_PAIR32(), and sMapDifficultyMap.
Referenced by InstanceSaveMgr::_ResetOrWarnAll(), GetDownscaledMapDifficultyData(), Map::GetMapDifficulty(), WorldSession::HandleMoveWorldportAck(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandlePlayerLoginToCharInWorld(), ObjectMgr::LoadCreatures(), DisableMgr::LoadDisables(), ObjectMgr::LoadGameobjects(), and InstanceSaveMgr::LoadResetTimes().
GetPetName()
char const* GetPetName (uint32 petfamily, uint32 dbclang)
Definition at line 906 of file DBCStores.cpp.
 {
     if (!petfamily)
         return nullptr;
     CreatureFamilyEntry const* pet_family = sCreatureFamilyStore.LookupEntry(petfamily);
     if (!pet_family)
         return nullptr;
     return pet_family->Name[dbclang];
 }
References CreatureFamilyEntry::Name, and sCreatureFamilyStore.
Referenced by ObjectMgr::GeneratePetName().
GetSkillRaceClassInfo()
SkillRaceClassInfoEntry const* GetSkillRaceClassInfo (uint32 skill, uint8 race, uint8 class_)
Definition at line 1117 of file DBCStores.cpp.
 {
     SkillRaceClassInfoBounds bounds = SkillRaceClassInfoBySkill.equal_range(skill);
     for (SkillRaceClassInfoMap::iterator itr = bounds.first; itr != bounds.second; ++itr)
     {
         if (itr->second->RaceMask && !(itr->second->RaceMask & (1 << (race - 1))))
         {
             continue;
         }
         if (itr->second->ClassMask && !(itr->second->ClassMask & (1 << (class_ - 1))))
         {
             continue;
         }
         return itr->second;
     }
     return nullptr;
 }
References SkillRaceClassInfoBySkill.
Referenced by Player::_LoadSkills(), Player::LearnDefaultSkill(), ObjectMgr::LoadPlayerInfo(), and Player::UpdateSkillsForLevel().
GetTalentSpellCost()
uint32 GetTalentSpellCost (uint32 spellId)
Definition at line 927 of file DBCStores.cpp.
 {
     if (TalentSpellPos const* pos = GetTalentSpellPos(spellId))
         return pos->rank + 1;
     return 0;
 }
References GetTalentSpellPos(), and pos().
Referenced by Pet::addSpell(), ObjectMgr::AddSpellToTrainer(), SpellInfo::CheckShapeshift(), learn_commandscript::HandleLearnAllMySpellsCommand(), Acore::PlayerCommand::HandleLearnSpellCommand(), lookup_commandscript::HandleLookupSpellCommand(), lookup_commandscript::HandleLookupSpellIdCommand(), Acore::PlayerCommand::HandleUnlearnSpellCommand(), Player::learnSpell(), list_commandscript::ListAurasCommand(), ObjectMgr::LoadQuests(), SpellMgr::LoadSpellRequired(), Pet::removeSpell(), Player::removeSpell(), and Pet::resetTalentsForAllPetsOf().
GetTalentSpellPos()
TalentSpellPos const* GetTalentSpellPos (uint32 spellId)
Definition at line 918 of file DBCStores.cpp.
 {
     TalentSpellPosMap::const_iterator itr = sTalentSpellPosMap.find(spellId);
     if (itr == sTalentSpellPosMap.end())
         return nullptr;
     return &itr->second;
 }
References sTalentSpellPosMap.
Referenced by Player::_LoadTalents(), Player::ActivateSpec(), Pet::addSpell(), Player::addTalent(), Player::BuildPlayerTalentsInfoData(), GetTalentSpellCost(), Player::LearnTalent(), Player::removeSpell(), and CharacterDatabaseCleaner::SpellCheck().
GetTalentTabPages()
uint32 const* GetTalentTabPages (uint8 cls)
Definition at line 1065 of file DBCStores.cpp.
 {
     return sTalentTabPages[cls];
 }
References sTalentTabPages.
Referenced by Player::GetSpec().
GetVirtualMapForMapAndZone()
uint32 GetVirtualMapForMapAndZone (uint32 mapid, uint32 zoneId)
Definition at line 944 of file DBCStores.cpp.
 {
     if (mapid != 530 && mapid != 571)                        // speed for most cases
         return mapid;
     if (WorldMapAreaEntry const* wma = sWorldMapAreaStore.LookupEntry(zoneId))
         return wma->virtual_map_id >= 0 ? wma->virtual_map_id : wma->map_id;
     return mapid;
 }
References sWorldMapAreaStore.
Referenced by Player::canFlyInZone(), GetContentLevelsForMapAndZone(), and spell_gen_mount::HandleMount().
GetWMOAreaTableEntryByTripple()
WMOAreaTableEntry const* GetWMOAreaTableEntryByTripple (int32 rootid, int32 adtid, int32 groupid)
Definition at line 935 of file DBCStores.cpp.
 {
     auto i = sWMOAreaInfoByTripple.find(WMOAreaTableKey(int16(rootid), int8(adtid), groupid));
     if (i != sWMOAreaInfoByTripple.end())
         return i->second;
     return nullptr;
 }
References sWMOAreaInfoByTripple.
Referenced by Map::GetAreaId(), and Map::GetFullTerrainStatusForPosition().
IsSharedDifficultyMap()
bool IsSharedDifficultyMap (uint32 mapid)
Definition at line 1070 of file DBCStores.cpp.
 {
     return sWorld->getBoolConfig(CONFIG_INSTANCE_SHARED_ID) && (mapid == 631 || mapid == 724);
 }
References CONFIG_INSTANCE_SHARED_ID, and sWorld.
Referenced by MapInstanced::CreateInstanceForPlayer(), WorldSession::HandleSetRaidDifficultyOpcode(), InstanceSaveMgr::PlayerGetBoundInstance(), and Map::UpdateEncounterState().
LoadDBC()
template<class T > void LoadDBC (uint32 & availableDbcLocales, StoreProblemList & errors, DBCStorage< T > & storage, std::string const & dbcPath, std::string const & filename, char const * dbTable = nullptr) inline
Definition at line 208 of file DBCStores.cpp.
 {
     // compatibility format and C++ structure sizes
     ASSERT(DBCFileLoader::GetFormatRecordSize(storage.GetFormat()) == sizeof(T) || LoadDBC_assert_print(DBCFileLoader::GetFormatRecordSize(storage.GetFormat()), sizeof(T), filename));
     ++DBCFileCount;
     std::string dbcFilename = dbcPath + filename;
     bool existDBData = false;
     if (storage.Load(dbcFilename.c_str()))
     {
         for (uint8 i = 0; i < TOTAL_LOCALES; ++i)
         {
             if (!(availableDbcLocales & (1 << i)))
                 continue;
             std::string localizedName(dbcPath);
             localizedName.append(localeNames[i]);
             localizedName.push_back('/');
             localizedName.append(filename);
             if (!storage.LoadStringsFrom(localizedName.c_str()))
                 availableDbcLocales &= ~(1 << i);             // mark as not available for speedup next checks
         }
     }
     if (dbTable)
         storage.LoadFromDB(dbTable, storage.GetFormat());
     if (storage.GetNumRows())
         existDBData = true;
     if (!existDBData)
     {
         // sort problematic dbc to (1) non compatible and (2) non-existed
         if (FILE* f = fopen(dbcFilename.c_str(), "rb"))
         {
             std::ostringstream stream;
             stream << dbcFilename << " exists, and has " << storage.GetFieldCount() << " field(s) (expected " << strlen(storage.GetFormat()) << "). Extracted file might be from wrong client version or a database-update has been forgotten.";
             std::string buf = stream.str();
             errors.push_back(buf);
             fclose(f);
         }
         else
             errors.push_back(dbcFilename);
     }
 }
References ASSERT, DBCFileCount, mpq::errors, f(), DBCStorageBase::GetFieldCount(), DBCStorageBase::GetFormat(), DBCFileLoader::GetFormatRecordSize(), DBCStorage< T >::GetNumRows(), DBCStorage< T >::Load(), LoadDBC_assert_print(), DBCStorage< T >::LoadFromDB(), DBCStorage< T >::LoadStringsFrom(), localeNames, and TOTAL_LOCALES.
LoadDBC_assert_print()
static bool LoadDBC_assert_print (uint32 fsize, uint32 rsize, const std::string & filename) static
Definition at line 199 of file DBCStores.cpp.
 {
     LOG_ERROR("dbc", "Size of '%s' set by format string (%u) not equal size of C++ structure (%u).", filename.c_str(), fsize, rsize);
     // ASSERT must fail after function call
     return false;
 }
References LOG_ERROR.
Referenced by LoadDBC().
LoadDBCStores()
void LoadDBCStores (const std::string & dataPath)
Definition at line 256 of file DBCStores.cpp.
 {
     uint32 oldMSTime = getMSTime();
     std::string dbcPath = dataPath + "dbc/";
     StoreProblemList bad_dbc_files;
     uint32 availableDbcLocales = 0xFFFFFFFF;
 #define LOAD_DBC(store, file, dbtable) LoadDBC(availableDbcLocales, bad_dbc_files, store, dbcPath, file, dbtable)
     LOAD_DBC(sAreaTableStore,                       "AreaTable.dbc",                        "areatable_dbc");
     LOAD_DBC(sAchievementStore,                     "Achievement.dbc",                      "achievement_dbc");
     LOAD_DBC(sAchievementCategoryStore,             "Achievement_Category.dbc",             "achievement_category_dbc");
     LOAD_DBC(sAchievementCriteriaStore,             "Achievement_Criteria.dbc",             "achievement_criteria_dbc");
     LOAD_DBC(sAreaGroupStore,                       "AreaGroup.dbc",                        "areagroup_dbc");
     LOAD_DBC(sAreaPOIStore,                         "AreaPOI.dbc",                          "areapoi_dbc");
     LOAD_DBC(sAuctionHouseStore,                    "AuctionHouse.dbc",                     "auctionhouse_dbc");
     LOAD_DBC(sBankBagSlotPricesStore,               "BankBagSlotPrices.dbc",                "bankbagslotprices_dbc");
     LOAD_DBC(sBattlemasterListStore,                "BattlemasterList.dbc",                 "battlemasterlist_dbc");
     LOAD_DBC(sBarberShopStyleStore,                 "BarberShopStyle.dbc",                  "barbershopstyle_dbc");
     LOAD_DBC(sCharStartOutfitStore,                 "CharStartOutfit.dbc",                  "charstartoutfit_dbc");
     LOAD_DBC(sCharTitlesStore,                      "CharTitles.dbc",                       "chartitles_dbc");
     LOAD_DBC(sChatChannelsStore,                    "ChatChannels.dbc",                     "chatchannels_dbc");
     LOAD_DBC(sChrClassesStore,                      "ChrClasses.dbc",                       "chrclasses_dbc");
     LOAD_DBC(sChrRacesStore,                        "ChrRaces.dbc",                         "chrraces_dbc");
     LOAD_DBC(sCinematicCameraStore,                 "CinematicCamera.dbc",                  "cinematiccamera_dbc");
     LOAD_DBC(sCinematicSequencesStore,              "CinematicSequences.dbc",               "cinematicsequences_dbc");
     LOAD_DBC(sCreatureDisplayInfoStore,             "CreatureDisplayInfo.dbc",              "creaturedisplayinfo_dbc");
     LOAD_DBC(sCreatureFamilyStore,                  "CreatureFamily.dbc",                   "creaturefamily_dbc");
     LOAD_DBC(sCreatureModelDataStore,               "CreatureModelData.dbc",                "creaturemodeldata_dbc");
     LOAD_DBC(sCreatureSpellDataStore,               "CreatureSpellData.dbc",                "creaturespelldata_dbc");
     LOAD_DBC(sCreatureTypeStore,                    "CreatureType.dbc",                     "creaturetype_dbc");
     LOAD_DBC(sCurrencyTypesStore,                   "CurrencyTypes.dbc",                    "currencytypes_dbc");
     LOAD_DBC(sDestructibleModelDataStore,           "DestructibleModelData.dbc",            "destructiblemodeldata_dbc");
     LOAD_DBC(sDungeonEncounterStore,                "DungeonEncounter.dbc",                 "dungeonencounter_dbc");
     LOAD_DBC(sDurabilityCostsStore,                 "DurabilityCosts.dbc",                  "durabilitycosts_dbc");
     LOAD_DBC(sDurabilityQualityStore,               "DurabilityQuality.dbc",                "durabilityquality_dbc");
     LOAD_DBC(sEmotesStore,                          "Emotes.dbc",                           "emotes_dbc");
     LOAD_DBC(sEmotesTextStore,                      "EmotesText.dbc",                       "emotestext_dbc");
     LOAD_DBC(sFactionStore,                         "Faction.dbc",                          "faction_dbc");
     LOAD_DBC(sFactionTemplateStore,                 "FactionTemplate.dbc",                  "factiontemplate_dbc");
     LOAD_DBC(sGameObjectDisplayInfoStore,           "GameObjectDisplayInfo.dbc",            "gameobjectdisplayinfo_dbc");
     LOAD_DBC(sGemPropertiesStore,                   "GemProperties.dbc",                    "gemproperties_dbc");
     LOAD_DBC(sGlyphPropertiesStore,                 "GlyphProperties.dbc",                  "glyphproperties_dbc");
     LOAD_DBC(sGlyphSlotStore,                       "GlyphSlot.dbc",                        "glyphslot_dbc");
     LOAD_DBC(sGtBarberShopCostBaseStore,            "gtBarberShopCostBase.dbc",             "gtbarbershopcostbase_dbc");
     LOAD_DBC(sGtCombatRatingsStore,                 "gtCombatRatings.dbc",                  "gtcombatratings_dbc");
     LOAD_DBC(sGtChanceToMeleeCritBaseStore,         "gtChanceToMeleeCritBase.dbc",          "gtchancetomeleecritbase_dbc");
     LOAD_DBC(sGtChanceToMeleeCritStore,             "gtChanceToMeleeCrit.dbc",              "gtchancetomeleecrit_dbc");
     LOAD_DBC(sGtChanceToSpellCritBaseStore,         "gtChanceToSpellCritBase.dbc",          "gtchancetospellcritbase_dbc");
     LOAD_DBC(sGtChanceToSpellCritStore,             "gtChanceToSpellCrit.dbc",              "gtchancetospellcrit_dbc");
     LOAD_DBC(sGtNPCManaCostScalerStore,             "gtNPCManaCostScaler.dbc",              "gtnpcmanacostscaler_dbc");
     LOAD_DBC(sGtOCTClassCombatRatingScalarStore,    "gtOCTClassCombatRatingScalar.dbc",     "gtoctclasscombatratingscalar_dbc");
     LOAD_DBC(sGtOCTRegenHPStore,                    "gtOCTRegenHP.dbc",                     "gtoctregenhp_dbc");
     //LOAD_DBC(sGtOCTRegenMPStore,                  "gtOCTRegenMP.dbc",                     "gtoctregenmp_dbc");       -- not used currently
     LOAD_DBC(sGtRegenHPPerSptStore,                 "gtRegenHPPerSpt.dbc",                  "gtregenhpperspt_dbc");
     LOAD_DBC(sGtRegenMPPerSptStore,                 "gtRegenMPPerSpt.dbc",                  "gtregenmpperspt_dbc");
     LOAD_DBC(sHolidaysStore,                        "Holidays.dbc",                         "holidays_dbc");
     LOAD_DBC(sItemBagFamilyStore,                   "ItemBagFamily.dbc",                    "itembagfamily_dbc");
     LOAD_DBC(sItemDisplayInfoStore,                 "ItemDisplayInfo.dbc",                  "itemdisplayinfo_dbc");
     //LOAD_DBC(sItemCondExtCostsStore,              "ItemCondExtCosts.dbc",                 "itemcondextcosts_dbc");
     LOAD_DBC(sItemExtendedCostStore,                "ItemExtendedCost.dbc",                 "itemextendedcost_dbc");
     LOAD_DBC(sItemLimitCategoryStore,               "ItemLimitCategory.dbc",                "itemlimitcategory_dbc");
     LOAD_DBC(sItemRandomPropertiesStore,            "ItemRandomProperties.dbc",             "itemrandomproperties_dbc");
     LOAD_DBC(sItemRandomSuffixStore,                "ItemRandomSuffix.dbc",                 "itemrandomsuffix_dbc");
     LOAD_DBC(sItemSetStore,                         "ItemSet.dbc",                          "itemset_dbc");
     LOAD_DBC(sLFGDungeonStore,                      "LFGDungeons.dbc",                      "lfgdungeons_dbc");
     LOAD_DBC(sLightStore,                           "Light.dbc",                            "light_dbc");
     LOAD_DBC(sLiquidTypeStore,                      "LiquidType.dbc",                       "liquidtype_dbc");
     LOAD_DBC(sLockStore,                            "Lock.dbc",                             "lock_dbc");
     LOAD_DBC(sMailTemplateStore,                    "MailTemplate.dbc",                     "mailtemplate_dbc");
     LOAD_DBC(sMapStore,                             "Map.dbc",                              "map_dbc");
     LOAD_DBC(sMapDifficultyStore,                   "MapDifficulty.dbc",                    "mapdifficulty_dbc");
     LOAD_DBC(sMovieStore,                           "Movie.dbc",                            "movie_dbc");
     LOAD_DBC(sOverrideSpellDataStore,               "OverrideSpellData.dbc",                "overridespelldata_dbc");
     LOAD_DBC(sPowerDisplayStore,                    "PowerDisplay.dbc",                     "powerdisplay_dbc");
     LOAD_DBC(sPvPDifficultyStore,                   "PvpDifficulty.dbc",                    "pvpdifficulty_dbc");
     LOAD_DBC(sQuestXPStore,                         "QuestXP.dbc",                          "questxp_dbc");
     LOAD_DBC(sQuestFactionRewardStore,              "QuestFactionReward.dbc",               "questfactionreward_dbc");
     LOAD_DBC(sQuestSortStore,                       "QuestSort.dbc",                        "questsort_dbc");
     LOAD_DBC(sRandomPropertiesPointsStore,          "RandPropPoints.dbc",                   "randproppoints_dbc");
     LOAD_DBC(sScalingStatDistributionStore,         "ScalingStatDistribution.dbc",          "scalingstatdistribution_dbc");
     LOAD_DBC(sScalingStatValuesStore,               "ScalingStatValues.dbc",                "scalingstatvalues_dbc");
     LOAD_DBC(sSkillLineStore,                       "SkillLine.dbc",                        "skillline_dbc");
     LOAD_DBC(sSkillLineAbilityStore,                "SkillLineAbility.dbc",                 "skilllineability_dbc");
     LOAD_DBC(sSkillRaceClassInfoStore,              "SkillRaceClassInfo.dbc",               "skillraceclassinfo_dbc");
     LOAD_DBC(sSkillTiersStore,                      "SkillTiers.dbc",                       nullptr); // TODO: add the SQL table!
     LOAD_DBC(sSoundEntriesStore,                    "SoundEntries.dbc",                     "soundentries_dbc");
     LOAD_DBC(sSpellStore,                           "Spell.dbc",                            "spell_dbc");
     LOAD_DBC(sSpellCastTimesStore,                  "SpellCastTimes.dbc",                   "spellcasttimes_dbc");
     LOAD_DBC(sSpellCategoryStore,                   "SpellCategory.dbc",                    "spellcategory_dbc");
     LOAD_DBC(sSpellDifficultyStore,                 "SpellDifficulty.dbc",                  "spelldifficulty_dbc");
     LOAD_DBC(sSpellDurationStore,                   "SpellDuration.dbc",                    "spellduration_dbc");
     LOAD_DBC(sSpellFocusObjectStore,                "SpellFocusObject.dbc",                 "spellfocusobject_dbc");
     LOAD_DBC(sSpellItemEnchantmentStore,            "SpellItemEnchantment.dbc",             "spellitemenchantment_dbc");
     LOAD_DBC(sSpellItemEnchantmentConditionStore,   "SpellItemEnchantmentCondition.dbc",    "spellitemenchantmentcondition_dbc");
     LOAD_DBC(sSpellRadiusStore,                     "SpellRadius.dbc",                      "spellradius_dbc");
     LOAD_DBC(sSpellRangeStore,                      "SpellRange.dbc",                       "spellrange_dbc");
     LOAD_DBC(sSpellRuneCostStore,                   "SpellRuneCost.dbc",                    "spellrunecost_dbc");
     LOAD_DBC(sSpellShapeshiftStore,                 "SpellShapeshiftForm.dbc",              "spellshapeshiftform_dbc");
     LOAD_DBC(sSpellVisualStore,                     "SpellVisual.dbc",                      "spellvisual_dbc");
     LOAD_DBC(sStableSlotPricesStore,                "StableSlotPrices.dbc",                 "stableslotprices_dbc");
     LOAD_DBC(sSummonPropertiesStore,                "SummonProperties.dbc",                 "summonproperties_dbc");
     LOAD_DBC(sTalentStore,                          "Talent.dbc",                           "talent_dbc");
     LOAD_DBC(sTalentTabStore,                       "TalentTab.dbc",                        "talenttab_dbc");
     LOAD_DBC(sTaxiNodesStore,                       "TaxiNodes.dbc",                        "taxinodes_dbc");
     LOAD_DBC(sTaxiPathStore,                        "TaxiPath.dbc",                         "taxipath_dbc");
     LOAD_DBC(sTaxiPathNodeStore,                    "TaxiPathNode.dbc",                     "taxipathnode_dbc");
     LOAD_DBC(sTeamContributionPointsStore,          "TeamContributionPoints.dbc",           "teamcontributionpoints_dbc");
     LOAD_DBC(sTotemCategoryStore,                   "TotemCategory.dbc",                    "totemcategory_dbc");
     LOAD_DBC(sTransportAnimationStore,              "TransportAnimation.dbc",               "transportanimation_dbc");
     LOAD_DBC(sTransportRotationStore,               "TransportRotation.dbc",                "transportrotation_dbc");
     LOAD_DBC(sVehicleStore,                         "Vehicle.dbc",                          "vehicle_dbc");
     LOAD_DBC(sVehicleSeatStore,                     "VehicleSeat.dbc",                      "vehicleseat_dbc");
     LOAD_DBC(sWMOAreaTableStore,                    "WMOAreaTable.dbc",                     "wmoareatable_dbc");
     LOAD_DBC(sWorldMapAreaStore,                    "WorldMapArea.dbc",                     "worldmaparea_dbc");
     LOAD_DBC(sWorldMapOverlayStore,                 "WorldMapOverlay.dbc",                  "worldmapoverlay_dbc");
 #undef LOAD_DBC
     for (CharStartOutfitEntry const* outfit : sCharStartOutfitStore)
         sCharStartOutfitMap[outfit->Race | (outfit->Class << 8) | (outfit->Gender << 16)] = outfit;
     for (FactionEntry const* faction : sFactionStore)
     {
         if (faction->team)
         {
             SimpleFactionsList& flist = sFactionTeamMap[faction->team];
             flist.push_back(faction->ID);
         }
     }
     for (GameObjectDisplayInfoEntry const* info : sGameObjectDisplayInfoStore)
     {
         if (info->maxX < info->minX)
             std::swap(*(float*)(&info->maxX), *(float*)(&info->minX));
         if (info->maxY < info->minY)
             std::swap(*(float*)(&info->maxY), *(float*)(&info->minY));
         if (info->maxZ < info->minZ)
             std::swap(*(float*)(&info->maxZ), *(float*)(&info->minZ));
     }
     // fill data
     for (MapDifficultyEntry const* entry : sMapDifficultyStore)
         sMapDifficultyMap[MAKE_PAIR32(entry->MapId, entry->Difficulty)] = MapDifficulty(entry->resetTime, entry->maxPlayers, entry->areaTriggerText[0] != '\0');
     for (PvPDifficultyEntry const* entry : sPvPDifficultyStore)
         if (entry->bracketId > MAX_BATTLEGROUND_BRACKETS)
             ASSERT(false && "Need update MAX_BATTLEGROUND_BRACKETS by DBC data");
     for (auto i : sSpellStore)
         if (i->Category)
             sSpellsByCategoryStore[i->Category].emplace(false, i->Id);
     for (SkillRaceClassInfoEntry const* entry : sSkillRaceClassInfoStore)
     {
         if (sSkillLineStore.LookupEntry(entry->SkillID))
         {
             SkillRaceClassInfoBySkill.emplace(entry->SkillID, entry);
         }
     }
     for (SkillLineAbilityEntry const* skillLine : sSkillLineAbilityStore)
     {
         SpellEntry const* spellInfo = sSpellStore.LookupEntry(skillLine->Spell);
         if (spellInfo && spellInfo->Attributes & SPELL_ATTR0_PASSIVE)
         {
             for (CreatureFamilyEntry const* cFamily : sCreatureFamilyStore)
             {
                 if (skillLine->SkillLine != cFamily->skillLine[0] && skillLine->SkillLine != cFamily->skillLine[1])
                 {
                     continue;
                 }
                 if (spellInfo->SpellLevel)
                 {
                     continue;
                 }
                 if (skillLine->AcquireMethod != SKILL_LINE_ABILITY_LEARNED_ON_SKILL_LEARN)
                 {
                     continue;
                 }
                 sPetFamilySpellsStore[cFamily->ID].insert(spellInfo->Id);
             }
         }
     }
     // Create Spelldifficulty searcher
     for (SpellDifficultyEntry const* spellDiff : sSpellDifficultyStore)
     {
         SpellDifficultyEntry newEntry;
         memset(newEntry.SpellID, 0, 4 * sizeof(uint32));
         for (uint8 x = 0; x < MAX_DIFFICULTY; ++x)
         {
             if (spellDiff->SpellID[x] <= 0 || !sSpellStore.LookupEntry(spellDiff->SpellID[x]))
             {
                 if (spellDiff->SpellID[x] > 0) //don't show error if spell is <= 0, not all modes have spells and there are unknown negative values
                     LOG_ERROR("sql.sql", "spelldifficulty_dbc: spell %i at field id: %u at spellid %i does not exist in SpellStore (spell.dbc), loaded as 0", spellDiff->SpellID[x], spellDiff->ID, x);
                 newEntry.SpellID[x] = 0; // spell was <= 0 or invalid, set to 0
             }
             else
                 newEntry.SpellID[x] = spellDiff->SpellID[x];
         }
         if (newEntry.SpellID[0] <= 0 || newEntry.SpellID[1] <= 0) // id0-1 must be always set!
             continue;
         for (uint8 x = 0; x < MAX_DIFFICULTY; ++x)
             if (newEntry.SpellID[x])
                 sSpellMgr->SetSpellDifficultyId(uint32(newEntry.SpellID[x]), spellDiff->ID);
     }
     // create talent spells set
     for (TalentEntry const* talentInfo : sTalentStore)
         for (uint8 j = 0; j < MAX_TALENT_RANK; ++j)
             if (talentInfo->RankID[j])
                 sTalentSpellPosMap[talentInfo->RankID[j]] = TalentSpellPos(talentInfo->TalentID, j);
     // prepare fast data access to bit pos of talent ranks for use at inspecting
     {
         // now have all max ranks (and then bit amount used for store talent ranks in inspect)
         for (uint32 talentTabId = 1; talentTabId < sTalentTabStore.GetNumRows(); ++talentTabId)
         {
             TalentTabEntry const* talentTabInfo = sTalentTabStore.LookupEntry(talentTabId);
             if (!talentTabInfo)
                 continue;
             // prevent memory corruption; otherwise cls will become 12 below
             if ((talentTabInfo->ClassMask & CLASSMASK_ALL_PLAYABLE) == 0)
                 continue;
             // store class talent tab pages
             for (uint32 cls = 1; cls < MAX_CLASSES; ++cls)
                 if (talentTabInfo->ClassMask & (1 << (cls - 1)))
                     sTalentTabPages[cls][talentTabInfo->tabpage] = talentTabId;
         }
     }
     for (uint32 i = 1; i < sTaxiPathStore.GetNumRows(); ++i)
         if (TaxiPathEntry const* entry = sTaxiPathStore.LookupEntry(i))
             sTaxiPathSetBySource[entry->from][entry->to] = TaxiPathBySourceAndDestination(entry->ID, entry->price);
     // Calculate path nodes count
     uint32 pathCount = sTaxiPathStore.GetNumRows();
     std::vector<uint32> pathLength;
     pathLength.resize(pathCount);                           // 0 and some other indexes not used
     for (uint32 i = 1; i < sTaxiPathNodeStore.GetNumRows(); ++i)
         if (TaxiPathNodeEntry const* entry = sTaxiPathNodeStore.LookupEntry(i))
             if (pathLength[entry->path] < entry->index + 1)
                 pathLength[entry->path] = entry->index + 1;
     // Set path length
     sTaxiPathNodesByPath.resize(pathCount);                 // 0 and some other indexes not used
     for (uint32 i = 1; i < sTaxiPathNodesByPath.size(); ++i)
         sTaxiPathNodesByPath[i].resize(pathLength[i]);
     // fill data
     for (TaxiPathNodeEntry const* entry : sTaxiPathNodeStore)
         sTaxiPathNodesByPath[entry->path][entry->index] = entry;
     // Initialize global taxinodes mask
     // include existed nodes that have at least single not spell base (scripted) path
     {
         std::set<uint32> spellPaths;
         for (SpellEntry const* sInfo : sSpellStore)
             for (uint8 j = 0; j < MAX_SPELL_EFFECTS; ++j)
                 if (sInfo->Effect[j] == SPELL_EFFECT_SEND_TAXI)
                     spellPaths.insert(sInfo->EffectMiscValue[j]);
         memset(sTaxiNodesMask, 0, sizeof(sTaxiNodesMask));
         memset(sOldContinentsNodesMask, 0, sizeof(sOldContinentsNodesMask));
         memset(sHordeTaxiNodesMask, 0, sizeof(sHordeTaxiNodesMask));
         memset(sAllianceTaxiNodesMask, 0, sizeof(sAllianceTaxiNodesMask));
         memset(sDeathKnightTaxiNodesMask, 0, sizeof(sDeathKnightTaxiNodesMask));
         for (uint32 i = 1; i < sTaxiNodesStore.GetNumRows(); ++i)
         {
             TaxiNodesEntry const* node = sTaxiNodesStore.LookupEntry(i);
             if (!node)
                 continue;
             TaxiPathSetBySource::const_iterator src_i = sTaxiPathSetBySource.find(i);
             if (src_i != sTaxiPathSetBySource.end() && !src_i->second.empty())
             {
                 bool ok = false;
                 for (TaxiPathSetForSource::const_iterator dest_i = src_i->second.begin(); dest_i != src_i->second.end(); ++dest_i)
                 {
                     // not spell path
                     if (dest_i->second.price || spellPaths.find(dest_i->second.ID) == spellPaths.end())
                     {
                         ok = true;
                         break;
                     }
                 }
                 if (!ok)
                     continue;
             }
             // valid taxi network node
             uint8  field   = (uint8)((i - 1) / 32);
             uint32 submask = 1 << ((i - 1) % 32);
             sTaxiNodesMask[field] |= submask;
             if (node->MountCreatureID[0] && node->MountCreatureID[0] != 32981)
                 sHordeTaxiNodesMask[field] |= submask;
             if (node->MountCreatureID[1] && node->MountCreatureID[1] != 32981)
                 sAllianceTaxiNodesMask[field] |= submask;
             if (node->MountCreatureID[0] == 32981 || node->MountCreatureID[1] == 32981)
                 sDeathKnightTaxiNodesMask[field] |= submask;
             // old continent node (+ nodes virtually at old continents, check explicitly to avoid loading map files for zone info)
             if (node->map_id < 2 || i == 82 || i == 83 || i == 93 || i == 94)
                 sOldContinentsNodesMask[field] |= submask;
             // fix DK node at Ebon Hold and Shadow Vault flight master
             if (i == 315 || i == 333)
                 ((TaxiNodesEntry*)node)->MountCreatureID[1] = 32981;
         }
     }
     for (TransportAnimationEntry const* anim : sTransportAnimationStore)
         sTransportMgr->AddPathNodeToTransport(anim->TransportEntry, anim->TimeSeg, anim);
     for (TransportRotationEntry const* rot : sTransportRotationStore)
         sTransportMgr->AddPathRotationToTransport(rot->TransportEntry, rot->TimeSeg, rot);
     for (WMOAreaTableEntry const* entry : sWMOAreaTableStore)
         sWMOAreaInfoByTripple[WMOAreaTableKey(entry->rootId, entry->adtId, entry->groupId)] = entry;
     // error checks
     if (bad_dbc_files.size() >= DBCFileCount)
     {
         LOG_ERROR("dbc", "Incorrect DataDir value in worldserver.conf or ALL required *.dbc files (%d) not found by path: %sdbc", DBCFileCount, dataPath.c_str());
         exit(1);
     }
     else if (!bad_dbc_files.empty())
     {
         std::string str;
         for (StoreProblemList::iterator i = bad_dbc_files.begin(); i != bad_dbc_files.end(); ++i)
             str += *i + "\n";
         LOG_ERROR("dbc", "Some required *.dbc files (%u from %d) not found or not compatible:\n%s", (uint32)bad_dbc_files.size(), DBCFileCount, str.c_str());
         exit(1);
     }
     // Check loaded DBC files proper version
     if (!sAreaTableStore.LookupEntry(4987)         ||       // last area added in 3.3.5a
             !sCharTitlesStore.LookupEntry(177)         ||       // last char title added in 3.3.5a
             !sGemPropertiesStore.LookupEntry(1629)     ||       // last added spell in 3.3.5a
             !sItemExtendedCostStore.LookupEntry(2997)  ||       // last item extended cost added in 3.3.5a
             !sMapStore.LookupEntry(724)                ||       // last map added in 3.3.5a
             !sSpellStore.LookupEntry(80864)            )        // last client known item added in 3.3.5a
     {
         LOG_ERROR("dbc", "You have _outdated_ DBC data. Please extract correct versions from current using client.");
         exit(1);
     }
     LoadM2Cameras(dataPath);
     LOG_INFO("server.loading", ">> Initialized %d data stores in %u ms", DBCFileCount, GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
 }
Referenced by World::SetInitialWorldSettings().
LoadM2Cameras()
void LoadM2Cameras (const std::string & dataPath)
Definition at line 807 of file DBCStores.cpp.
 {
     sFlyByCameraStore.clear();
     LOG_INFO("server.loading", ">> Loading Cinematic Camera files");
     uint32 oldMSTime = getMSTime();
     for (uint32 i = 0; i < sCinematicCameraStore.GetNumRows(); ++i)
     {
         if (CinematicCameraEntry const* dbcentry = sCinematicCameraStore.LookupEntry(i))
         {
             std::string filename = dataPath.c_str();
             filename.append(dbcentry->filename);
             // Replace slashes
             size_t loc = filename.find("\\");
             while (loc != std::string::npos)
             {
                 filename.replace(loc, 1, "/");
                 loc = filename.find("\\");
             }
             // Replace mdx to .m2
             loc = filename.find(".mdx");
             if (loc != std::string::npos)
             {
                 filename.replace(loc, 4, ".m2");
             }
             std::ifstream m2file(filename.c_str(), std::ios::in | std::ios::binary);
             if (!m2file.is_open())
             {
                 continue;
             }
             // Get file size
             m2file.seekg(0, std::ios::end);
             std::streamoff const fileSize = m2file.tellg();
             // Reject if not at least the size of the header
             if (static_cast<uint32>(fileSize) < sizeof(M2Header))
             {
                 LOG_ERROR("dbc", "Camera file %s is damaged. File is smaller than header size", filename.c_str());
                 m2file.close();
                 continue;
             }
             // Read 4 bytes (signature)
             m2file.seekg(0, std::ios::beg);
             char fileCheck[5];
             m2file.read(fileCheck, 4);
             fileCheck[4] = 0;
             // Check file has correct magic (MD20)
             if (strcmp(fileCheck, "MD20"))
             {
                 LOG_ERROR("dbc", "Camera file %s is damaged. File identifier not found", filename.c_str());
                 m2file.close();
                 continue;
             }
             // Now we have a good file, read it all into a vector of char's, then close the file.
             std::vector<char> buffer(fileSize);
             m2file.seekg(0, std::ios::beg);
             if (!m2file.read(buffer.data(), fileSize))
             {
                 m2file.close();
                 continue;
             }
             m2file.close();
             // Read header
             M2Header const* header = reinterpret_cast<M2Header const*>(buffer.data());
             if (header->ofsCameras + sizeof(M2Camera) > static_cast<uint32>(fileSize))
             {
                 LOG_ERROR("dbc", "Camera file %s is damaged. Camera references position beyond file end", filename.c_str());
                 continue;
             }
             // Get camera(s) - Main header, then dump them.
             M2Camera const* cam = reinterpret_cast<M2Camera const*>(buffer.data() + header->ofsCameras);
             if (!readCamera(cam, fileSize, header, dbcentry))
             {
                 LOG_ERROR("dbc", "Camera file %s is damaged. Camera references position beyond file end", filename.c_str());
             }
         }
     }
     LOG_INFO("server.loading", ">> Loaded %u cinematic waypoint sets in %u ms", (uint32)sFlyByCameraStore.size(), GetMSTimeDiffToNow(oldMSTime));
 }
References buffer, const, buffer< T >::data(), getMSTime(), GetMSTimeDiffToNow(), LOG_ERROR, LOG_INFO, M2Header::ofsCameras, readCamera(), sCinematicCameraStore, and sFlyByCameraStore.
Map2ZoneCoordinates()
void Map2ZoneCoordinates (float & x, float & y, uint32 zone)
Definition at line 989 of file DBCStores.cpp.
 {
     WorldMapAreaEntry const* maEntry = sWorldMapAreaStore.LookupEntry(zone);
     // if not listed then map coordinates (instance)
     if (!maEntry)
         return;
     x = (x - maEntry->x1) / ((maEntry->x2 - maEntry->x1) / 100);
     y = (y - maEntry->y1) / ((maEntry->y2 - maEntry->y1) / 100); // client y coord from top to down
     std::swap(x, y);                                         // client have map coords swapped
 }
References swap(), sWorldMapAreaStore, G3D::x, WorldMapAreaEntry::x1, WorldMapAreaEntry::x2, G3D::y, WorldMapAreaEntry::y1, and WorldMapAreaEntry::y2.
Referenced by misc_commandscript::HandleGPSCommand().
readCamera()
bool readCamera (M2Camera const * cam, uint32 buffSize, M2Header const * header, CinematicCameraEntry const * dbcentry)
Definition at line 653 of file DBCStores.cpp.
 {
     char const* buffer = reinterpret_cast<char const*>(header);
     FlyByCameraCollection cameras;
     FlyByCameraCollection targetcam;
     G3D::Vector4 DBCData;
     DBCData.x = dbcentry->base_x;
     DBCData.y = dbcentry->base_y;
     DBCData.z = dbcentry->base_z;
     DBCData.w = dbcentry->base_o;
     // Read target locations, only so that we can calculate orientation
     for (uint32 k = 0; k < cam->target_positions.timestamps.number; ++k)
     {
         // Extract Target positions
         if (cam->target_positions.timestamps.offset_elements + sizeof(M2Array) > buffSize)
         {
             return false;
         }
         M2Array const* targTsArray = reinterpret_cast<M2Array const*>(buffer + cam->target_positions.timestamps.offset_elements);
         if (targTsArray->offset_elements + sizeof(uint32) > buffSize || cam->target_positions.values.offset_elements + sizeof(M2Array) > buffSize)
         {
             return false;
         }
         uint32 const* targTimestamps = reinterpret_cast<uint32 const*>(buffer + targTsArray->offset_elements);
         M2Array const* targArray = reinterpret_cast<M2Array const*>(buffer + cam->target_positions.values.offset_elements);
         if (targArray->offset_elements + sizeof(M2SplineKey<G3D::Vector3>) > buffSize)
         {
             return false;
         }
         M2SplineKey<G3D::Vector3> const* targPositions = reinterpret_cast<M2SplineKey<G3D::Vector3> const*>(buffer + targArray->offset_elements);
         // Read the data for this set
         uint32 currPos = targArray->offset_elements;
         for (uint32 i = 0; i < targTsArray->number; ++i)
         {
             if (currPos + sizeof(M2SplineKey<G3D::Vector3>) > buffSize)
             {
                 return false;
             }
             // Translate co-ordinates
             G3D::Vector3 newPos = TranslateLocation(&DBCData, &cam->target_position_base, &targPositions->p0);
             // Add to vector
             FlyByCamera thisCam;
             thisCam.timeStamp = targTimestamps[i];
             thisCam.locations.x = newPos.x;
             thisCam.locations.y = newPos.y;
             thisCam.locations.z = newPos.z;
             thisCam.locations.w = 0.0f;
             targetcam.push_back(thisCam);
             targPositions++;
             currPos += sizeof(M2SplineKey<G3D::Vector3>);
         }
     }
     // Read camera positions and timestamps (translating first position of 3 only, we don't need to translate the whole spline)
     for (uint32 k = 0; k < cam->positions.timestamps.number; ++k)
     {
         // Extract Camera positions for this set
         if (cam->positions.timestamps.offset_elements + sizeof(M2Array) > buffSize)
         {
             return false;
         }
         M2Array const* posTsArray = reinterpret_cast<M2Array const*>(buffer + cam->positions.timestamps.offset_elements);
         if (posTsArray->offset_elements + sizeof(uint32) > buffSize || cam->positions.values.offset_elements + sizeof(M2Array) > buffSize)
         {
             return false;
         }
         uint32 const* posTimestamps = reinterpret_cast<uint32 const*>(buffer + posTsArray->offset_elements);
         M2Array const* posArray = reinterpret_cast<M2Array const*>(buffer + cam->positions.values.offset_elements);
         if (posArray->offset_elements + sizeof(M2SplineKey<G3D::Vector3>) > buffSize)
         {
             return false;
         }
         M2SplineKey<G3D::Vector3> const* positions = reinterpret_cast<M2SplineKey<G3D::Vector3> const*>(buffer + posArray->offset_elements);
         // Read the data for this set
         uint32 currPos = posArray->offset_elements;
         for (uint32 i = 0; i < posTsArray->number; ++i)
         {
             if (currPos + sizeof(M2SplineKey<G3D::Vector3>) > buffSize)
             {
                 return false;
             }
             // Translate co-ordinates
             G3D::Vector3 newPos = TranslateLocation(&DBCData, &cam->position_base, &positions->p0);
             // Add to vector
             FlyByCamera thisCam;
             thisCam.timeStamp = posTimestamps[i];
             thisCam.locations.x = newPos.x;
             thisCam.locations.y = newPos.y;
             thisCam.locations.z = newPos.z;
             if (targetcam.size() > 0)
             {
                 // Find the target camera before and after this camera
                 FlyByCamera lastTarget;
                 FlyByCamera nextTarget;
                 // Pre-load first item
                 lastTarget = targetcam[0];
                 nextTarget = targetcam[0];
                 for (uint32 j = 0; j < targetcam.size(); ++j)
                 {
                     nextTarget = targetcam[j];
                     if (targetcam[j].timeStamp > posTimestamps[i])
                     {
                         break;
                     }
                     lastTarget = targetcam[j];
                 }
                 float x = lastTarget.locations.x;
                 float y = lastTarget.locations.y;
                 // float z = lastTarget.locations.z;
                 // Now, the timestamps for target cam and position can be different. So, if they differ we interpolate
                 if (lastTarget.timeStamp != posTimestamps[i])
                 {
                     uint32 timeDiffTarget = nextTarget.timeStamp - lastTarget.timeStamp;
                     uint32 timeDiffThis = posTimestamps[i] - lastTarget.timeStamp;
                     float xDiff = nextTarget.locations.x - lastTarget.locations.x;
                     float yDiff = nextTarget.locations.y - lastTarget.locations.y;
                     // float zDiff = nextTarget.locations.z - lastTarget.locations.z;
                     x = lastTarget.locations.x + (xDiff * (float(timeDiffThis) / float(timeDiffTarget)));
                     y = lastTarget.locations.y + (yDiff * (float(timeDiffThis) / float(timeDiffTarget)));
                     // z = lastTarget.locations.z + (zDiff * (float(timeDiffThis) / float(timeDiffTarget)));
                 }
                 float xDiff = x - thisCam.locations.x;
                 float yDiff = y - thisCam.locations.y;
                 thisCam.locations.w = std::atan2(yDiff, xDiff);
                 if (thisCam.locations.w < 0)
                 {
                     thisCam.locations.w += 2 * float(M_PI);
                 }
             }
             cameras.push_back(thisCam);
             positions++;
             currPos += sizeof(M2SplineKey<G3D::Vector3>);
         }
     }
     sFlyByCameraStore[dbcentry->id] = cameras;
     return true;
 }
References CinematicCameraEntry::base_o, CinematicCameraEntry::base_x, CinematicCameraEntry::base_y, CinematicCameraEntry::base_z, const, CinematicCameraEntry::id, FlyByCamera::locations, M_PI, M2Array::number, M2Array::offset_elements, M2SplineKey< T >::p0, M2Camera::position_base, positions, M2Camera::positions, sFlyByCameraStore, M2Camera::target_position_base, M2Camera::target_positions, FlyByCamera::timeStamp, M2Track::timestamps, TranslateLocation(), M2Track::values, G3D::Vector4::w, G3D::x, G3D::Vector3::x, G3D::Vector4::x, G3D::y, G3D::Vector3::y, G3D::Vector4::y, G3D::Vector3::z, and G3D::Vector4::z.
Referenced by LoadM2Cameras().
TranslateLocation()
G3D::Vector3 TranslateLocation (G3D::Vector4 const * DBCPosition, G3D::Vector3 const * basePosition, G3D::Vector3 const * splineVector)
Definition at line 632 of file DBCStores.cpp.
 {
     G3D::Vector3 work;
     float x = basePosition->x + splineVector->x;
     float y = basePosition->y + splineVector->y;
     float z = basePosition->z + splineVector->z;
     float const distance = sqrt((x * x) + (y * y));
     float angle = std::atan2(x, y) - DBCPosition->w;
     if (angle < 0)
     {
         angle += 2 * float(M_PI);
     }
     work.x = DBCPosition->x + (distance * sin(angle));
     work.y = DBCPosition->y + (distance * cos(angle));
     work.z = DBCPosition->z + z;
     return work;
 }
References G3D::distance(), M_PI, G3D::Vector4::w, G3D::x, G3D::Vector3::x, G3D::Vector4::x, G3D::y, G3D::Vector3::y, G3D::Vector4::y, G3D::Vector3::z, G3D::z, and G3D::Vector4::z.
Referenced by readCamera().
Zone2MapCoordinates()
void Zone2MapCoordinates (float & x, float & y, uint32 zone)
Definition at line 976 of file DBCStores.cpp.
 {
     WorldMapAreaEntry const* maEntry = sWorldMapAreaStore.LookupEntry(zone);
     // if not listed then map coordinates (instance)
     if (!maEntry)
         return;
     std::swap(x, y);                                         // at client map coords swapped
     x = x * ((maEntry->x2 - maEntry->x1) / 100) + maEntry->x1;
     y = y * ((maEntry->y2 - maEntry->y1) / 100) + maEntry->y1; // client y coord from top to down
 }
References swap(), sWorldMapAreaStore, G3D::x, WorldMapAreaEntry::x1, WorldMapAreaEntry::x2, G3D::y, WorldMapAreaEntry::y1, and WorldMapAreaEntry::y2.
Referenced by go_commandscript::HandleGoZoneXYCommand().
Variable Documentation
DBCFileCount
uint32 DBCFileCount = 0
Definition at line 197 of file DBCStores.cpp.
Referenced by LoadDBC().
sAchievementCategoryStore
DBCStorage<AchievementCategoryEntry> sAchievementCategoryStore(AchievementCategoryfmt) (AchievementCategoryfmt)
Referenced by AchievementGlobalMgr::isStatisticAchievement().
sAchievementCriteriaStore
DBCStorage<AchievementCriteriaEntry> sAchievementCriteriaStore(AchievementCriteriafmt) (AchievementCriteriafmt)
Referenced by CharacterDatabaseCleaner::AchievementProgressCheck(), AchievementGlobalMgr::LoadAchievementCriteriaData(), AchievementGlobalMgr::LoadAchievementCriteriaList(), DisableMgr::LoadDisables(), AchievementMgr::LoadFromDB(), AchievementCriteriaData::Meets(), and AchievementMgr::UpdateTimedAchievements().
sAchievementStore
DBCStorage<AchievementEntry> sAchievementStore(Achievementfmt) (Achievementfmt)
Referenced by AchievementMgr::BuildAllDataPacket(), AchievementGlobalMgr::GetAchievement(), ConditionMgr::isConditionTypeValid(), AchievementGlobalMgr::IsStatisticCriteria(), ObjectMgr::LoadAccessRequirements(), AchievementGlobalMgr::LoadAchievementCriteriaData(), AchievementGlobalMgr::LoadAchievementReferenceList(), AchievementGlobalMgr::LoadCompletedAchievements(), SpellMgr::LoadDbcDataCorrections(), ObjectMgr::LoadFactionChangeAchievements(), AchievementMgr::LoadFromDB(), AchievementGlobalMgr::LoadRewards(), Condition::Meets(), Player::PrettyPrintRequirementsAchievementsList(), AchievementMgr::ResetAchievementCriteria(), AchievementMgr::SetCriteriaProgress(), AchievementMgr::StartTimedAchievement(), and AchievementMgr::UpdateAchievementCriteria().
sAllianceTaxiNodesMask
TaxiMask sAllianceTaxiNodesMask
Definition at line 172 of file DBCStores.cpp.
Referenced by WorldSession::HandleCharFactionOrRaceChangeCallback().
sAreaGroupStore
DBCStorage<AreaGroupEntry> sAreaGroupStore(AreaGroupEntryfmt) (AreaGroupEntryfmt)
Referenced by SpellInfo::CheckLocation().
sAreaPOIStore
DBCStorage<AreaPOIEntry> sAreaPOIStore(AreaPOIEntryfmt) (AreaPOIEntryfmt)
sAreaTableStore
DBCStorage<AreaTableEntry> sAreaTableStore(AreaTableEntryfmt) (AreaTableEntryfmt)
Referenced by ObjectMgr::ChangeFishingBaseSkillLevel(), Player::CheckAreaExploreAndOutdoor(), Spell::CheckCast(), SpellInfo::CheckLocation(), Spell::EffectDuel(), Map::GetFullTerrainStatusForPosition(), GridMap::GetLiquidData(), Map::GetLiquidData(), Map::GetZoneAndAreaId(), Map::GetZoneId(), go_commandscript::HandleGoZoneXYCommand(), misc_commandscript::HandleGPSCommand(), WorldSession::HandleHearthAndResurrect(), misc_commandscript::HandleHideAreaCommand(), WorldSession::HandleJoinChannel(), misc_commandscript::HandleLinkGraveCommand(), WorldSession::HandleLogoutRequestOpcode(), lookup_commandscript::HandleLookupAreaCommand(), spell_gen_mount::HandleMount(), misc_commandscript::HandlePInfoCommand(), misc_commandscript::HandleShowAreaCommand(), WorldSession::HandleWhoOpcode(), ConditionMgr::isConditionTypeValid(), SmartAIMgr::IsEventValid(), SpellArea::IsFitToRequirements(), AchievementCriteriaData::IsValid(), SpellMgr::LoadDbcDataCorrections(), ObjectMgr::LoadFishingBaseSkillLevel(), Graveyard::LoadGraveyardZones(), ObjectMgr::LoadItemTemplates(), LoadLootTemplates_Fishing(), ObjectMgr::LoadQuests(), SpellMgr::LoadSpellAreas(), LogCommandUsage(), WorldObject::ProcessPositionDataChanged(), Player::RepopAtGraveyard(), OutdoorPvP::SetMapFromZone(), AchievementMgr::UpdateAchievementCriteria(), Player::UpdateArea(), Player::UpdateLocalChannels(), and Player::UpdateZone().
sAuctionHouseStore
DBCStorage<AuctionHouseEntry> sAuctionHouseStore(AuctionHouseEntryfmt) (AuctionHouseEntryfmt)
Referenced by AuctionHouseMgr::GetAuctionHouseEntry(), and AuctionHouseMgr::GetAuctionHouseEntryFromHouse().
sBankBagSlotPricesStore
DBCStorage<BankBagSlotPricesEntry> sBankBagSlotPricesStore(BankBagSlotPricesEntryfmt) (BankBagSlotPricesEntryfmt)
Referenced by WorldSession::HandleBuyBankSlotOpcode().
sBarberShopStyleStore
DBCStorage<BarberShopStyleEntry> sBarberShopStyleStore(BarberShopStyleEntryfmt) (BarberShopStyleEntryfmt)
Referenced by WorldSession::HandleAlterAppearance().
sBattlemasterListStore
DBCStorage<BattlemasterListEntry> sBattlemasterListStore(BattlemasterListEntryfmt) (BattlemasterListEntryfmt)
Referenced by Group::CanJoinBattlegroundQueue(), BattlegroundMgr::CreateInitialBattlegrounds(), BattlegroundMgr::GetRandomBG(), disable_commandscript::HandleAddDisables(), WorldSession::HandleBattlefieldListOpcode(), WorldSession::HandleBattleFieldPortOpcode(), WorldSession::HandleBattlemasterJoinOpcode(), BattlegroundMgr::LoadBattleMastersEntry(), DisableMgr::LoadDisables(), Player::SendBGWeekendWorldStates(), and GameEventMgr::UpdateWorldStates().
sCharStartOutfitMap
std::map<uint32, CharStartOutfitEntry const*> sCharStartOutfitMap
Definition at line 53 of file DBCStores.cpp.
Referenced by GetCharStartOutfitEntry().
sCharStartOutfitStore
DBCStorage<CharStartOutfitEntry> sCharStartOutfitStore(CharStartOutfitEntryfmt) (CharStartOutfitEntryfmt)
Referenced by ObjectMgr::LoadItemTemplates().
sCharTitlesStore
DBCStorage<CharTitlesEntry> sCharTitlesStore(CharTitlesEntryfmt) (CharTitlesEntryfmt)
Referenced by Player::_LoadQuestStatusRewarded(), AchievementMgr::CompletedAchievement(), character_commandscript::HandleCharacterTitlesCommand(), WorldSession::HandleCharFactionOrRaceChangeCallback(), lookup_commandscript::HandleLookupTitleCommand(), titles_commandscript::HandleTitlesAddCommand(), titles_commandscript::HandleTitlesCurrentCommand(), titles_commandscript::HandleTitlesRemoveCommand(), titles_commandscript::HandleTitlesSetMaskCommand(), ConditionMgr::isConditionTypeValid(), AchievementCriteriaData::IsValid(), ObjectMgr::LoadFactionChangeTitles(), AchievementMgr::LoadFromDB(), ObjectMgr::LoadQuests(), AchievementGlobalMgr::LoadRewards(), AchievementCriteriaData::Meets(), and Player::RewardQuest().
sChatChannelsStore
DBCStorage<ChatChannelsEntry> sChatChannelsStore(ChatChannelsEntryfmt) (ChatChannelsEntryfmt)
Referenced by Channel::Channel(), WorldSession::HandleJoinChannel(), and Player::UpdateLocalChannels().
sChrClassesStore
DBCStorage<ChrClassesEntry> sChrClassesStore(ChrClassesEntryfmt) (ChrClassesEntryfmt)
Referenced by Player::Create(), WorldSession::HandleCharCreateOpcode(), learn_commandscript::HandleLearnAllMySpellsCommand(), WorldSession::HandlePlayerLoginFromDB(), reset_commandscript::HandleResetStatsOrLevelHelper(), Player::InitDataForForm(), and ObjectMgr::LoadPlayerInfo().
sChrRacesStore
DBCStorage<ChrRacesEntry> sChrRacesStore(ChrRacesEntryfmt) (ChrRacesEntryfmt)
Referenced by World::DetectDBCLang(), WorldSession::HandleCharCreateOpcode(), WorldSession::HandlePlayerLoginFromDB(), ObjectMgr::LoadPlayerInfo(), Player::SetFactionForRace(), and Player::TeamIdForRace().
sCinematicCameraStore
DBCStorage<CinematicCameraEntry> sCinematicCameraStore(CinematicCameraEntryfmt) (CinematicCameraEntryfmt)
Referenced by LoadM2Cameras().
sCinematicSequencesStore
DBCStorage<CinematicSequencesEntry> sCinematicSequencesStore(CinematicSequencesEntryfmt) (CinematicSequencesEntryfmt)
Referenced by debug_commandscript::HandleDebugPlayCinematicCommand(), and Player::SendCinematicStart().
sCreatureDisplayInfoStore
DBCStorage<CreatureDisplayInfoEntry> sCreatureDisplayInfoStore(CreatureDisplayInfofmt) (CreatureDisplayInfofmt)
Referenced by ObjectMgr::CheckCreatureTemplate(), Unit::GetCollisionHeight(), Unit::GetCollisionWidth(), modify_commandscript::HandleModifyMountCommand(), npc_commandscript::HandleNpcSetModelCommand(), SmartAIMgr::IsEventValid(), ObjectMgr::LoadCreatureAddons(), ObjectMgr::LoadCreatureModelInfo(), ObjectMgr::LoadCreatureTemplateAddons(), and SpellMgr::LoadDbcDataCorrections().
sCreatureFamilyStore
DBCStorage<CreatureFamilyEntry> sCreatureFamilyStore(CreatureFamilyfmt) (CreatureFamilyfmt)
Referenced by Player::BuildPetTalentsInfoData(), ObjectMgr::CheckCreatureTemplate(), Pet::CreateBaseAtCreature(), Pet::CreateBaseAtCreatureInfo(), GetPetName(), learn_commandscript::HandleLearnAllMyPetTalentsCommand(), Pet::HaveInDiet(), Guardian::InitStatsForLevel(), Pet::LearnPetPassives(), Player::LearnPetTalent(), SpellMgr::LoadPetLevelupSpellMap(), and Pet::resetTalents().
sCreatureModelDataStore
DBCStorage<CreatureModelDataEntry> sCreatureModelDataStore(CreatureModelDatafmt) (CreatureModelDatafmt)
Referenced by Unit::GetCollisionHeight(), and Unit::GetCollisionWidth().
sCreatureSpellDataStore
DBCStorage<CreatureSpellDataEntry> sCreatureSpellDataStore(CreatureSpellDatafmt) (CreatureSpellDatafmt)
Referenced by ObjectMgr::CheckCreatureTemplate(), and SpellMgr::LoadPetDefaultSpells().
sCreatureTypeStore
DBCStorage<CreatureTypeEntry> sCreatureTypeStore(CreatureTypefmt) (CreatureTypefmt)
Referenced by ObjectMgr::CheckCreatureTemplate().
sCurrencyTypesStore
DBCStorage<CurrencyTypesEntry> sCurrencyTypesStore(CurrencyTypesfmt) (CurrencyTypesfmt)
Referenced by Player::AddKnownCurrency(), and ObjectMgr::LoadItemTemplates().
sDeathKnightTaxiNodesMask
TaxiMask sDeathKnightTaxiNodesMask
Definition at line 173 of file DBCStores.cpp.
Referenced by WorldSession::HandleCharFactionOrRaceChangeCallback().
sDestructibleModelDataStore
DBCStorage<DestructibleModelDataEntry> sDestructibleModelDataStore(DestructibleModelDatafmt) (DestructibleModelDatafmt)
Referenced by GameObject::SetDestructibleState().
sDungeonEncounterStore
DBCStorage<DungeonEncounterEntry> sDungeonEncounterStore(DungeonEncounterfmt) (DungeonEncounterfmt)
Referenced by ObjectMgr::LoadInstanceEncounters().
sDurabilityCostsStore
DBCStorage<DurabilityCostsEntry> sDurabilityCostsStore(DurabilityCostsfmt) (DurabilityCostsfmt)
Referenced by Player::DurabilityRepair().
sDurabilityQualityStore
DBCStorage<DurabilityQualityEntry> sDurabilityQualityStore(DurabilityQualityfmt) (DurabilityQualityfmt)
Referenced by Player::DurabilityRepair().
sEmotesStore
DBCStorage<EmotesEntry> sEmotesStore(EmotesEntryfmt) (EmotesEntryfmt)
Referenced by SmartAIMgr::IsEmoteValid(), ObjectMgr::LoadBroadcastTexts(), ObjectMgr::LoadCreatureAddons(), ObjectMgr::LoadCreatureTemplateAddons(), CreatureTextMgr::LoadCreatureTexts(), and ObjectMgr::LoadScripts().
sEmotesTextStore
DBCStorage<EmotesTextEntry> sEmotesTextStore(EmotesTextEntryfmt) (EmotesTextEntryfmt)
Referenced by WorldSession::HandleTextEmoteOpcode(), and SmartAIMgr::IsTextEmoteValid().
sFactionStore
DBCStorage<FactionEntry> sFactionStore(FactionEntryfmt) (FactionEntryfmt)
Referenced by Unit::_IsValidAttackTarget(), Player::AddQuest(), Spell::EffectReputation(), Unit::GetDispellableAuraList(), Unit::GetFactionReactionTo(), Unit::GetReactionTo(), ReputationMgr::GetReputation(), Player::GetReputation(), Player::GetReputationRank(), OutdoorPvPSI::HandleAreaTrigger(), character_commandscript::HandleCharacterReputationCommand(), WorldSession::HandleCharFactionOrRaceChangeCallback(), spell_gen_oracle_wolvar_reputation::HandleDummy(), lookup_commandscript::HandleLookupFactionCommand(), modify_commandscript::HandleModifyRepCommand(), WorldSession::HandlePlayerLoginFromDB(), quest_commandscript::HandleQuestComplete(), ReputationMgr::Initialize(), ReputationMgr::IsAtWar(), ConditionMgr::isConditionTypeValid(), Unit::IsHostileToPlayers(), Unit::IsNeutralToAll(), SpellMgr::LoadDbcDataCorrections(), ObjectMgr::LoadFactionChangeReputations(), ReputationMgr::LoadFromDB(), ObjectMgr::LoadItemTemplates(), ObjectMgr::LoadQuests(), ObjectMgr::LoadReputationOnKill(), ObjectMgr::LoadReputationRewardRate(), ObjectMgr::LoadReputationSpilloverTemplate(), Condition::Meets(), Player::RewardReputation(), Battleground::RewardReputationToTeam(), ReputationMgr::SetReputation(), Player::SetReputation(), and ReputationMgr::SetVisible().
sFactionTeamMap
FactionTeamMap sFactionTeamMap static
Definition at line 76 of file DBCStores.cpp.
Referenced by GetFactionTeamList().
sFactionTemplateStore
DBCStorage<FactionTemplateEntry> sFactionTemplateStore(FactionTemplateEntryfmt) (FactionTemplateEntryfmt)
Referenced by Player::CanUseBattlegroundObject(), ObjectMgr::CheckCreatureTemplate(), Spell::EffectGameObjectDamage(), AuctionHouseMgr::GetAuctionHouseEntry(), AuctionHouseMgr::GetAuctionsMap(), Unit::GetFactionTemplateEntry(), WorldSession::HandleGossipHelloOpcode(), modify_commandscript::HandleModifyFactionCommand(), npc_commandscript::HandleNpcSetFactionIdCommand(), SmartAIMgr::IsEventValid(), SpellMgr::LoadDbcDataCorrections(), ObjectMgr::LoadGameObjectTemplateAddons(), Creature::UpdateEntry(), and Creature::UpdateMoveInLineOfSightState().
sFlyByCameraStore
std::unordered_map<uint32, FlyByCameraCollection> sFlyByCameraStore
Definition at line 193 of file DBCStores.cpp.
Referenced by Player::BeginCinematic(), debug_commandscript::HandleDebugPlayCinematicCommand(), LoadM2Cameras(), and readCamera().
sGameObjectDisplayInfoStore
DBCStorage<GameObjectDisplayInfoEntry> sGameObjectDisplayInfoStore(GameObjectDisplayInfofmt) (GameObjectDisplayInfofmt)
Referenced by gobject_commandscript::HandleGameObjectAddCommand(), GameObject::IsAtInteractDistance(), GameObject::IsInRange(), and ObjectMgr::LoadGameobjects().
sGemPropertiesStore
DBCStorage<GemPropertiesEntry> sGemPropertiesStore(GemPropertiesEntryfmt) (GemPropertiesEntryfmt)
Referenced by Player::EnchantmentFitsRequirements(), Item::GemsFitSockets(), WorldSession::HandleSocketOpcode(), and ObjectMgr::LoadItemTemplates().
sGlyphPropertiesStore
DBCStorage<GlyphPropertiesEntry> sGlyphPropertiesStore(GlyphPropertiesfmt) (GlyphPropertiesfmt)
Referenced by Player::_LoadGlyphAuras(), Player::ActivateSpec(), Spell::CheckCast(), Spell::EffectApplyGlyph(), ChatHandler::extractSpellIdFromLink(), WorldSession::HandleRemoveGlyph(), AuraEffect::HandleShapeshiftBoosts(), Player::SendInitialSpells(), and Acore::Hyperlinks::LinkTags::glyph::StoreTo().
sGlyphSlotStore
DBCStorage<GlyphSlotEntry> sGlyphSlotStore(GlyphSlotfmt) (GlyphSlotfmt)
Referenced by Player::_LoadGlyphAuras(), Spell::EffectApplyGlyph(), Player::InitGlyphsForLevel(), and Acore::Hyperlinks::LinkTags::glyph::StoreTo().
sGtBarberShopCostBaseStore
DBCStorage<GtBarberShopCostBaseEntry> sGtBarberShopCostBaseStore(GtBarberShopCostBasefmt) (GtBarberShopCostBasefmt)
Referenced by Player::GetBarberShopCost().
sGtChanceToMeleeCritBaseStore
DBCStorage<GtChanceToMeleeCritBaseEntry> sGtChanceToMeleeCritBaseStore(GtChanceToMeleeCritBasefmt) (GtChanceToMeleeCritBasefmt)
Referenced by Player::GetMeleeCritFromAgility().
sGtChanceToMeleeCritStore
DBCStorage<GtChanceToMeleeCritEntry> sGtChanceToMeleeCritStore(GtChanceToMeleeCritfmt) (GtChanceToMeleeCritfmt)
Referenced by Player::GetDodgeFromAgility(), and Player::GetMeleeCritFromAgility().
sGtChanceToSpellCritBaseStore
DBCStorage<GtChanceToSpellCritBaseEntry> sGtChanceToSpellCritBaseStore(GtChanceToSpellCritBasefmt) (GtChanceToSpellCritBasefmt)
Referenced by Player::GetSpellCritFromIntellect().
sGtChanceToSpellCritStore
DBCStorage<GtChanceToSpellCritEntry> sGtChanceToSpellCritStore(GtChanceToSpellCritfmt) (GtChanceToSpellCritfmt)
Referenced by Player::GetSpellCritFromIntellect().
sGtCombatRatingsStore
DBCStorage<GtCombatRatingsEntry> sGtCombatRatingsStore(GtCombatRatingsfmt) (GtCombatRatingsfmt)
Referenced by Player::GetRatingMultiplier().
sGtNPCManaCostScalerStore
DBCStorage<GtNPCManaCostScalerEntry> sGtNPCManaCostScalerStore(GtNPCManaCostScalerfmt) (GtNPCManaCostScalerfmt)
Referenced by SpellInfo::CalcPowerCost(), and SpellEffectInfo::CalcValue().
sGtOCTClassCombatRatingScalarStore
DBCStorage<GtOCTClassCombatRatingScalarEntry> sGtOCTClassCombatRatingScalarStore(GtOCTClassCombatRatingScalarfmt) (GtOCTClassCombatRatingScalarfmt)
Referenced by Player::GetRatingMultiplier().
sGtOCTRegenHPStore
DBCStorage<GtOCTRegenHPEntry> sGtOCTRegenHPStore(GtOCTRegenHPfmt) (GtOCTRegenHPfmt)
Referenced by Player::OCTRegenHPPerSpirit().
sGtRegenHPPerSptStore
DBCStorage<GtRegenHPPerSptEntry> sGtRegenHPPerSptStore(GtRegenHPPerSptfmt) (GtRegenHPPerSptfmt)
Referenced by Player::OCTRegenHPPerSpirit().
sGtRegenMPPerSptStore
DBCStorage<GtRegenMPPerSptEntry> sGtRegenMPPerSptStore(GtRegenMPPerSptfmt) (GtRegenMPPerSptfmt)
Referenced by Player::OCTRegenMPPerSpirit().
sHolidaysStore
DBCStorage<HolidaysEntry> sHolidaysStore(Holidaysfmt) (Holidaysfmt)
Referenced by WorldSession::HandleCalendarGetCalendar(), AchievementCriteriaData::IsValid(), GameEventMgr::LoadFromDB(), GameEventMgr::LoadHolidayDates(), ObjectMgr::LoadItemTemplates(), and GameEventMgr::SetHolidayEventTime().
sHordeTaxiNodesMask
TaxiMask sHordeTaxiNodesMask
Definition at line 171 of file DBCStores.cpp.
Referenced by WorldSession::HandleCharFactionOrRaceChangeCallback().
sItemBagFamilyStore
DBCStorage<ItemBagFamilyEntry> sItemBagFamilyStore(ItemBagFamilyfmt) (ItemBagFamilyfmt)
Referenced by ObjectMgr::LoadItemTemplates().
sItemDisplayInfoStore
DBCStorage<ItemDisplayInfoEntry> sItemDisplayInfoStore(ItemDisplayTemplateEntryfmt) (ItemDisplayTemplateEntryfmt)
sItemExtendedCostStore
DBCStorage<ItemExtendedCostEntry> sItemExtendedCostStore(ItemExtendedCostEntryfmt) (ItemExtendedCostEntryfmt)
Referenced by Player::_StoreOrEquipNewItem(), Player::BuyItemFromVendorSlot(), ObjectMgr::IsVendorItemValid(), Player::RefundItem(), and Player::SendRefundInfo().
sItemLimitCategoryStore
DBCStorage<ItemLimitCategoryEntry> sItemLimitCategoryStore(ItemLimitCategoryEntryfmt) (ItemLimitCategoryEntryfmt)
Referenced by Player::CanEquipUniqueItem(), Player::CanTakeMoreSimilarItems(), WorldSession::HandleSocketOpcode(), and ObjectMgr::LoadItemTemplates().
sItemRandomPropertiesStore
DBCStorage<ItemRandomPropertiesEntry> sItemRandomPropertiesStore(ItemRandomPropertiesfmt) (ItemRandomPropertiesfmt)
Referenced by AuctionHouseObject::BuildListAuctionItems(), Item::GenerateItemRandomPropertyId(), ObjectMgr::LoadItemTemplates(), Item::SetItemRandomProperties(), and Acore::Hyperlinks::LinkTags::item::StoreTo().
sItemRandomSuffixStore
DBCStorage<ItemRandomSuffixEntry> sItemRandomSuffixStore(ItemRandomSuffixfmt) (ItemRandomSuffixfmt)
Referenced by Player::ApplyEnchantment(), AuctionHouseObject::BuildListAuctionItems(), AuraEffect::CalculateAmount(), Item::GenerateItemRandomPropertyId(), ObjectMgr::LoadItemTemplates(), Item::SetItemRandomProperties(), and Acore::Hyperlinks::LinkTags::item::StoreTo().
sItemSetStore
DBCStorage<ItemSetEntry> sItemSetStore(ItemSetEntryfmt) (ItemSetEntryfmt)
Referenced by AddItemsSetItem(), lookup_commandscript::HandleLookupItemSetCommand(), ObjectMgr::LoadItemSetNames(), ObjectMgr::LoadItemTemplates(), and RemoveItemsSetItem().
SkillRaceClassInfoBySkill
SkillRaceClassInfoMap SkillRaceClassInfoBySkill
Definition at line 138 of file DBCStores.cpp.
Referenced by GetSkillRaceClassInfo().
sLFGDungeonStore
DBCStorage<LFGDungeonEntry> sLFGDungeonStore(LFGDungeonEntryfmt) (LFGDungeonEntryfmt)
Referenced by lfg::LFGQueue::CheckCompatibility(), GetLFGDungeon(), and lfg::LFGMgr::LoadLFGDungeons().
sLightStore
DBCStorage<LightEntry> sLightStore(LightEntryfmt) (LightEntryfmt)
Referenced by GetDefaultMapLight().
sLiquidTypeStore
DBCStorage<LiquidTypeEntry> sLiquidTypeStore(LiquidTypefmt) (LiquidTypefmt)
Referenced by Map::GetFullTerrainStatusForPosition(), GridMap::GetLiquidData(), Map::GetLiquidData(), GetLiquidFlags(), and Unit::ProcessTerrainStatusUpdate().
sLockStore
DBCStorage<LockEntry> sLockStore(LockEntryfmt) (LockEntryfmt)
Referenced by Spell::CanOpenLock(), CheckGOLockId(), GameObject::GetSpellForLock(), go_celestial_planetarium_access::go_celestial_planetarium_accessAI::GossipHello(), WorldSession::HandleOpenItemOpcode(), SpellMgr::LoadDbcDataCorrections(), ObjectMgr::LoadItemTemplates(), and Spell::OnSpellLaunch().
sMailTemplateStore
DBCStorage<MailTemplateEntry> sMailTemplateStore(MailTemplateEntryfmt) (MailTemplateEntryfmt)
Referenced by Player::_LoadMail(), WorldSession::HandleMailCreateTextItem(), LoadLootTemplates_Mail(), ObjectMgr::LoadMailLevelRewards(), ObjectMgr::LoadQuests(), and AchievementGlobalMgr::LoadRewards().
sMapDifficultyMap
MapDifficultyMap sMapDifficultyMap
Definition at line 119 of file DBCStores.cpp.
Referenced by GetMapDifficultyData(), and InstanceSaveMgr::LoadResetTimes().
sMapDifficultyStore
DBCStorage<MapDifficultyEntry> sMapDifficultyStore(MapDifficultyEntryfmt) (MapDifficultyEntryfmt)
sMapStore
DBCStorage<MapEntry> sMapStore(MapEntryfmt) (MapEntryfmt)
Referenced by Group::_homebindIfInstance(), Player::_LoadHomeBind(), InstanceSaveMgr::_ResetOrWarnAll(), KillRewarder::_RewardGroup(), Player::_SaveEntryPoint(), InstanceSaveMgr::AddInstanceSave(), Spell::CheckCast(), SpellInfo::CheckLocation(), MapScript< TMap >::checkMap(), MapMgr::CreateBaseMap(), MapInstanced::CreateInstance(), TransportMgr::CreateTransport(), TransportMgr::GeneratePath(), Graveyard::GetClosestGraveyard(), GetContentLevelsForMapAndZone(), ObjectMgr::GetGoBackTrigger(), InstanceSave::GetMapEntry(), InstanceSave::GetResetTimeForDB(), Player::GetZoneIdFromDB(), disable_commandscript::HandleAddDisables(), WorldSession::HandleCalendarGetCalendar(), WorldSession::HandleCorpseQueryOpcode(), misc_commandscript::HandleGPSCommand(), lookup_commandscript::HandleLookupMapCommand(), WorldSession::HandleMoveWorldportAck(), misc_commandscript::HandlePInfoCommand(), WorldSession::HandleSetSavedInstanceExtend(), tele_commandscript::HandleTeleCommand(), tele_commandscript::HandleTeleGroupCommand(), lfg::LFGMgr::InitializeLockedDungeons(), ConditionMgr::isConditionTypeValid(), DisableMgr::IsDisabledFor(), SmartAIMgr::IsEventValid(), AchievementCriteriaData::IsValid(), MapMgr::IsValidMAP(), Player::KillPlayer(), ObjectMgr::LoadAreaTriggers(), ObjectMgr::LoadAreaTriggerTeleports(), Player::LoadCorpse(), ObjectMgr::LoadCreatures(), DisableMgr::LoadDisables(), Player::LoadFromDB(), ObjectMgr::LoadGameobjects(), ObjectMgr::LoadItemTemplates(), ObjectMgr::LoadLinkedRespawn(), ObjectMgr::LoadPlayerInfo(), ObjectMgr::LoadScripts(), SpellMgr::LoadSpellTargetPositions(), ObjectMgr::LoadTempSummons(), lfg::LFGPlayerScript::OnBindToInstance(), MapMgr::PlayerCannotEnter(), Player::ResetInstances(), Group::ResetInstances(), Player::Satisfy(), ObjectMgr::SetCreatureLinkedRespawn(), Pet::setDeathState(), World::SetInitialWorldSettings(), TransportMgr::SpawnContinentTransports(), Player::TeleportTo(), and spell_gen_bg_preparation::Update().
sMovieStore
DBCStorage<MovieEntry> sMovieStore(MovieEntryfmt) (MovieEntryfmt)
Referenced by debug_commandscript::HandleDebugPlayMovieCommand(), and spell_the_lich_king_play_movie::spell_the_lich_king_play_movie_SpellScript::Validate().
sOldContinentsNodesMask
TaxiMask sOldContinentsNodesMask
Definition at line 170 of file DBCStores.cpp.
Referenced by PlayerTaxi::InitTaxiNodesForLevel().
sOverrideSpellDataStore
DBCStorage<OverrideSpellDataEntry> sOverrideSpellDataStore(OverrideSpellDatafmt) (OverrideSpellDatafmt)
Referenced by AuraEffect::HandleAuraOverrideSpells().
sPetFamilySpellsStore
PetFamilySpellsStore sPetFamilySpellsStore
Definition at line 147 of file DBCStores.cpp.
Referenced by Pet::LearnPetPassives().
sPowerDisplayStore
DBCStorage<PowerDisplayEntry> sPowerDisplayStore(PowerDisplayfmt) (PowerDisplayfmt)
Referenced by Vehicle::Install().
sPvPDifficultyStore
DBCStorage<PvPDifficultyEntry> sPvPDifficultyStore(PvPDifficultyfmt) (PvPDifficultyfmt)
Referenced by GetBattlegroundBracketById(), and GetBattlegroundBracketByLevel().
sQuestFactionRewardStore
DBCStorage<QuestFactionRewEntry> sQuestFactionRewardStore(QuestFactionRewardfmt) (QuestFactionRewardfmt)
Referenced by Player::RewardReputation().
sQuestSortStore
DBCStorage<QuestSortEntry> sQuestSortStore(QuestSortEntryfmt) (QuestSortEntryfmt)
Referenced by ObjectMgr::LoadQuests().
sQuestXPStore
DBCStorage<QuestXPEntry> sQuestXPStore(QuestXPfmt) (QuestXPfmt)
Referenced by Quest::XPValue().
sRandomPropertiesPointsStore
DBCStorage<RandomPropertiesPointsEntry> sRandomPropertiesPointsStore(RandomPropertiesPointsfmt) (RandomPropertiesPointsfmt)
Referenced by GenerateEnchSuffixFactor().
sScalingStatDistributionStore
DBCStorage<ScalingStatDistributionEntry> sScalingStatDistributionStore(ScalingStatDistributionfmt) (ScalingStatDistributionfmt)
Referenced by Player::_ApplyItemBonuses(), Player::_ApplyWeaponDamage(), and Player::CanEquipItem().
sScalingStatValuesStore
DBCStorage<ScalingStatValuesEntry> sScalingStatValuesStore(ScalingStatValuesfmt) (ScalingStatValuesfmt)
Referenced by Player::_ApplyItemBonuses(), and Player::_ApplyWeaponDamage().
sSkillLineAbilityStore
DBCStorage<SkillLineAbilityEntry> sSkillLineAbilityStore(SkillLineAbilityfmt) (SkillLineAbilityfmt)
Referenced by learn_commandscript::HandleLearnAllMySpellsCommand(), learn_commandscript::HandleLearnSkillRecipesHelper(), Player::learnSkillRewardedSpells(), SpellMgr::LoadPetLevelupSpellMap(), SpellMgr::LoadSkillLineAbilityMap(), and Player::SetSkill().
sSkillLineStore
DBCStorage<SkillLineEntry> sSkillLineStore(SkillLinefmt) (SkillLinefmt)
Referenced by Player::_addSpell(), GetSkillRangeType(), character_commandscript::HandleCharacterCheckProfessionCommand(), learn_commandscript::HandleLearnAllCraftsCommand(), learn_commandscript::HandleLearnAllRecipesCommand(), lookup_commandscript::HandleLookupSkillCommand(), misc_commandscript::HandleSetSkillCommand(), ConditionMgr::isConditionTypeValid(), IsPrimaryProfessionSkill(), LinkValidator< LinkTags::enchant >::IsTextValid(), ObjectMgr::LoadPlayerInfo(), ObjectMgr::LoadQuests(), Player::removeSpell(), Player::SetSkill(), and CharacterDatabaseCleaner::SkillCheck().
sSkillRaceClassInfoStore
DBCStorage<SkillRaceClassInfoEntry> sSkillRaceClassInfoStore(SkillRaceClassInfofmt) (SkillRaceClassInfofmt)
sSkillTiersStore
DBCStorage<SkillTiersEntry> sSkillTiersStore(SkillTiersfmt) (SkillTiersfmt)
Referenced by Player::_LoadSkills(), GetSkillRangeType(), and Player::LearnDefaultSkill().
sSoundEntriesStore
DBCStorage<SoundEntriesEntry> sSoundEntriesStore(SoundEntriesfmt) (SoundEntriesfmt)
Referenced by ScriptedAI::DoPlaySoundToSet(), Spell::EffectPlayMusic(), Spell::EffectPlaySound(), debug_commandscript::HandleDebugPlayMusicCommand(), debug_commandscript::HandleDebugPlaySoundCommand(), misc_commandscript::HandlePlayAllCommand(), SmartAIMgr::IsSoundValid(), ObjectMgr::LoadBroadcastTexts(), and CreatureTextMgr::LoadCreatureTexts().
sSpellCastTimesStore
DBCStorage<SpellCastTimesEntry> sSpellCastTimesStore(SpellCastTimefmt) (SpellCastTimefmt)
Referenced by SpellInfo::SpellInfo().
sSpellCategoryStore
DBCStorage<SpellCategoryEntry> sSpellCategoryStore(SpellCategoryfmt) (SpellCategoryfmt)
Referenced by SpellInfo::SpellInfo().
sSpellDifficultyStore
DBCStorage<SpellDifficultyEntry> sSpellDifficultyStore(SpellDifficultyfmt) (SpellDifficultyfmt)
Referenced by SpellMgr::GetSpellIdForDifficulty().
sSpellDurationStore
DBCStorage<SpellDurationEntry> sSpellDurationStore(SpellDurationfmt) (SpellDurationfmt)
Referenced by SpellInfo::SpellInfo().
sSpellFocusObjectStore
DBCStorage<SpellFocusObjectEntry> sSpellFocusObjectStore(SpellFocusObjectfmt) (SpellFocusObjectfmt)
Referenced by ObjectMgr::LoadGameObjectTemplate().
sSpellItemEnchantmentConditionStore
DBCStorage<SpellItemEnchantmentConditionEntry> sSpellItemEnchantmentConditionStore(SpellItemEnchantmentConditionfmt) (SpellItemEnchantmentConditionfmt)
Referenced by Player::EnchantmentFitsRequirements().
sSpellItemEnchantmentStore
DBCStorage<SpellItemEnchantmentEntry> sSpellItemEnchantmentStore(SpellItemEnchantmentfmt) (SpellItemEnchantmentfmt)
Referenced by Player::ApplyEnchantment(), Player::BuildEnumData(), AuraEffect::CalculateAmount(), Player::CanEquipUniqueItem(), Player::CastItemCombatSpell(), Player::CastItemUseSpell(), Spell::CheckItems(), Player::CorrectMetaGemEnchants(), Spell::EffectEnchantHeldItem(), Spell::EffectEnchantItemPerm(), Spell::EffectEnchantItemPrismatic(), Spell::EffectEnchantItemTmp(), Player::EnchantmentFitsRequirements(), Item::GemsFitSockets(), Item::GetEnchantRequiredLevel(), Item::GetGemCountWithID(), Item::GetGemCountWithLimitCategory(), spell_rog_deadly_poison::HandleAfterHit(), WorldSession::HandleSocketOpcode(), Item::HasEnchantRequiredSkill(), Item::IsBoundByEnchant(), Item::IsBoundByTempEnchant(), SpellMgr::LoadEnchantCustomAttr(), SpellMgr::LoadSpellCustomAttr(), SpellMgr::LoadSpellEnchantProcData(), Player::ToggleMetaGemsActive(), and Player::UpdateSkillEnchantments().
sSpellRadiusStore
DBCStorage<SpellRadiusEntry> sSpellRadiusStore(SpellRadiusfmt) (SpellRadiusfmt)
Referenced by SpellEffectInfo::SpellEffectInfo().
sSpellRangeStore
DBCStorage<SpellRangeEntry> sSpellRangeStore(SpellRangefmt) (SpellRangefmt)
Referenced by SpellInfo::SpellInfo().
sSpellRuneCostStore
DBCStorage<SpellRuneCostEntry> sSpellRuneCostStore(SpellRuneCostfmt) (SpellRuneCostfmt)
Referenced by Spell::CheckRuneCost(), and Spell::TakeRunePower().
sSpellsByCategoryStore
SpellCategoryStore sSpellsByCategoryStore
Definition at line 146 of file DBCStores.cpp.
Referenced by Player::AddSpellAndCategoryCooldowns(), Creature::AddSpellCooldown(), ObjectMgr::LoadItemTemplates(), and Player::RemoveCategoryCooldown().
sSpellShapeshiftStore
DBCStorage<SpellShapeshiftEntry> sSpellShapeshiftStore(SpellShapeshiftfmt) (SpellShapeshiftfmt)
Referenced by SpellInfo::CalcPowerCost(), Spell::CheckCast(), SpellInfo::CheckShapeshift(), Unit::GetCreatureType(), Unit::GetModelForForm(), AuraEffect::HandleAuraModShapeshift(), and Player::InitDataForForm().
sSpellStore
DBCStorage<SpellEntry> sSpellStore(SpellEntryfmt) (SpellEntryfmt)
Referenced by ApplySpellFix(), ObjectMgr::InitializeSpellInfoPrecomputedData(), SpellMgr::LoadDbcDataCorrections(), and SpellMgr::LoadSpellInfoStore().
sSpellVisualStore
DBCStorage<SpellVisualEntry> sSpellVisualStore(SpellVisualfmt) (SpellVisualfmt)
Referenced by SpellMgr::LoadSpellCustomAttr().
sStableSlotPricesStore
DBCStorage<StableSlotPricesEntry> sStableSlotPricesStore(StableSlotPricesfmt) (StableSlotPricesfmt)
Referenced by WorldSession::HandleBuyStableSlot().
sSummonPropertiesStore
DBCStorage<SummonPropertiesEntry> sSummonPropertiesStore(SummonPropertiesfmt) (SummonPropertiesfmt)
Referenced by Spell::CheckCast(), Spell::EffectSummonPet(), Spell::EffectSummonType(), spell_halion_damage_aoe_summon::spell_halion_damage_aoe_summon_SpellScript::HandleSummon(), spell_putricide_mutated_transformation::spell_putricide_mutated_transformation_SpellScript::HandleSummon(), spell_wintergrasp_create_vehicle::spell_wintergrasp_create_vehicle_SpellScript::HandleSummon(), and SpellMgr::LoadDbcDataCorrections().
sTalentSpellPosMap
TalentSpellPosMap sTalentSpellPosMap
Definition at line 162 of file DBCStores.cpp.
Referenced by GetTalentSpellPos().
sTalentStore
DBCStorage<TalentEntry> sTalentStore(TalentEntryfmt) (TalentEntryfmt)
Referenced by Pet::addSpell(), Player::addTalent(), Player::BuildPetTalentsInfoData(), ChatHandler::extractSpellIdFromLink(), Player::GetMostPointsTalentTree(), Player::GetSpec(), Player::GetTalentTreePoints(), learn_commandscript::HandleLearnAllMyPetTalentsCommand(), learn_commandscript::HandleLearnAllMyTalentsCommand(), Player::LearnPetTalent(), Player::LearnTalent(), SpellMgr::LoadSpellCustomAttr(), SpellMgr::LoadSpellTalentRanks(), Pet::resetTalents(), Player::resetTalents(), Acore::Hyperlinks::LinkTags::talent::StoreTo(), and CharacterDatabaseCleaner::TalentCheck().
sTalentTabPages
uint32 sTalentTabPages[MAX_CLASSES][3] static
Definition at line 166 of file DBCStores.cpp.
Referenced by GetTalentTabPages().
sTalentTabStore
DBCStorage<TalentTabEntry> sTalentTabStore(TalentTabEntryfmt) (TalentTabEntryfmt)
Referenced by Player::BuildPetTalentsInfoData(), Player::GetMostPointsTalentTree(), Player::GetTalentTreePoints(), learn_commandscript::HandleLearnAllMyPetTalentsCommand(), learn_commandscript::HandleLearnAllMyTalentsCommand(), Player::LearnPetTalent(), Player::LearnTalent(), Pet::resetTalents(), and CharacterDatabaseCleaner::TalentCheck().
sTaxiNodesMask
TaxiMask sTaxiNodesMask
Definition at line 169 of file DBCStores.cpp.
Referenced by PlayerTaxi::AppendTaximaskTo(), ObjectMgr::GetNearestTaxiNode(), and PlayerTaxi::LoadTaxiMask().
sTaxiNodesStore
DBCStorage<TaxiNodesEntry> sTaxiNodesStore(TaxiNodesEntryfmt) (TaxiNodesEntryfmt)
Referenced by Player::ActivateTaxiPathTo(), Spell::EffectDiscoverTaxi(), ObjectMgr::GetNearestTaxiNode(), ObjectMgr::GetTaxiMountDisplayId(), go_commandscript::HandleGoTaxinodeCommand(), and lookup_commandscript::HandleLookupTaxiNodeCommand().
sTaxiPathNodesByPath
TaxiPathNodesByPath sTaxiPathNodesByPath
Definition at line 180 of file DBCStores.cpp.
Referenced by Player::ContinueTaxiFlight(), TransportMgr::GeneratePath(), ObjectMgr::LoadEventScripts(), ObjectMgr::LoadGameObjectTemplate(), FlightPathMovementGenerator::LoadPath(), TransportMgr::LoadTransportTemplates(), and MotionMaster::MoveTaxiFlight().
sTaxiPathNodeStore
DBCStorage<TaxiPathNodeEntry> sTaxiPathNodeStore(TaxiPathNodeEntryfmt) (TaxiPathNodeEntryfmt) static
sTaxiPathSetBySource
TaxiPathSetBySource sTaxiPathSetBySource
Definition at line 176 of file DBCStores.cpp.
Referenced by ObjectMgr::GetTaxiPath().
sTaxiPathStore
DBCStorage<TaxiPathEntry> sTaxiPathStore(TaxiPathEntryfmt) (TaxiPathEntryfmt)
Referenced by Player::ActivateTaxiPathTo(), and SmartAIMgr::IsEventValid().
sTeamContributionPointsStore
DBCStorage<TeamContributionPointsEntry> sTeamContributionPointsStore(TeamContributionPointsfmt) (TeamContributionPointsfmt)
Referenced by Quest::CalculateHonorGain().
sTotemCategoryStore
DBCStorage<TotemCategoryEntry> sTotemCategoryStore(TotemCategoryEntryfmt) (TotemCategoryEntryfmt)
Referenced by Player::IsTotemCategoryCompatiableWith(), and ObjectMgr::LoadItemTemplates().
sTransportAnimationStore
DBCStorage<TransportAnimationEntry> sTransportAnimationStore(TransportAnimationfmt) (TransportAnimationfmt)
sTransportRotationStore
DBCStorage<TransportRotationEntry> sTransportRotationStore(TransportRotationfmt) (TransportRotationfmt)
sVehicleSeatStore
DBCStorage<VehicleSeatEntry> sVehicleSeatStore(VehicleSeatEntryfmt) (VehicleSeatEntryfmt)
Referenced by SpellMgr::LoadDbcDataCorrections(), and Vehicle::Vehicle().
sVehicleStore
DBCStorage<VehicleEntry> sVehicleStore(VehicleEntryfmt) (VehicleEntryfmt)
Referenced by ObjectMgr::CheckCreatureTemplate(), Unit::CreateVehicleKit(), and debug_commandscript::HandleDebugSpawnVehicleCommand().
sWMOAreaInfoByTripple
WMOAreaInfoByTripple sWMOAreaInfoByTripple static
Definition at line 43 of file DBCStores.cpp.
Referenced by GetWMOAreaTableEntryByTripple().
sWMOAreaTableStore
DBCStorage<WMOAreaTableEntry> sWMOAreaTableStore(WMOAreaTableEntryfmt) (WMOAreaTableEntryfmt)
sWorldMapAreaStore
DBCStorage<WorldMapAreaEntry> sWorldMapAreaStore(WorldMapAreaEntryfmt) (WorldMapAreaEntryfmt)
Referenced by GetVirtualMapForMapAndZone(), Map2ZoneCoordinates(), and Zone2MapCoordinates().
sWorldMapOverlayStore
DBCStorage<WorldMapOverlayEntry> sWorldMapOverlayStore(WorldMapOverlayEntryfmt) (WorldMapOverlayEntryfmt)
Referenced by AchievementGlobalMgr::LoadAchievementCriteriaList(), and AchievementMgr::UpdateAchievementCriteria().