Azerotcore-wotlk: UnboundPlagueTargetSelector Class Reference
UnboundPlagueTargetSelector Class Reference
Public Member Functions
UnboundPlagueTargetSelector (Creature *source)
bool operator() (WorldObject *object) const
Private Attributes
Creature const * _source
Detailed Description
Definition at line 181 of file boss_professor_putricide.cpp.
Constructor & Destructor Documentation
UnboundPlagueTargetSelector()
UnboundPlagueTargetSelector::UnboundPlagueTargetSelector (Creature * source) inline
Definition at line 184 of file boss_professor_putricide.cpp.
 : _source(source) { }
Member Function Documentation
operator()()
bool UnboundPlagueTargetSelector::operator() (WorldObject * object) const inline
Definition at line 186 of file boss_professor_putricide.cpp.
     {
         if (!object)
             return false;
         if (Player* p = object->ToPlayer())
         {
             if (p == _source->GetVictim() || p->GetExactDist(_source) >= 45.0f)
                 return false;
             return true;
         }
         return false;
     }
References _source, Position::GetExactDist(), Unit::GetVictim(), and Object::ToPlayer().
Member Data Documentation
_source
Creature const* UnboundPlagueTargetSelector::_source private
Definition at line 200 of file boss_professor_putricide.cpp.
Referenced by mpq::Archive::__repr__(), and operator()().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_professor_putricide.cpp