Azerotcore-wotlk: boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI Struct Reference
boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI Struct Reference
Public Member Functions
boss_blood_queen_lana_thelAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *who) override
void JustDied (Unit *) override
void GoToMinchar ()
void DoAction (int32 action) override
void JustReachedHome () override
void KilledUnit (Unit *victim) override
void MovementInform (uint32 type, uint32 id) override
void UpdateAI (uint32 diff) override
void CleanAuras ()
bool WasVampire (ObjectGuid guid)
bool WasBloodbolted (ObjectGuid guid)
void SetGUID (ObjectGuid guid, int32 type=0) override
void EnterEvadeMode () override
bool CanAIAttack (const Unit *) const override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
bool _creditBloodQuickening
bool _killMinchar
ObjectGuid _tankGUID
ObjectGuid _offtankGUID
GuidSet _bloodboltedPlayers
GuidSet _vampires
bool bEnteredCombat
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 140 of file boss_blood_queen_lana_thel.cpp.
Constructor & Destructor Documentation
boss_blood_queen_lana_thelAI()
boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::boss_blood_queen_lana_thelAI (Creature * creature) inline
Definition at line 142 of file boss_blood_queen_lana_thel.cpp.
                                                          : BossAI(creature, DATA_BLOOD_QUEEN_LANA_THEL)
         {
             bEnteredCombat = false;
         }
References bEnteredCombat.
Member Function Documentation
CanAIAttack()
bool boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::CanAIAttack (const Unit *) const inline override virtual
Reimplemented from UnitAI.
Definition at line 576 of file boss_blood_queen_lana_thel.cpp.
         {
             return me->IsVisible();
         }
References Unit::IsVisible(), and ScriptedAI::me.
CleanAuras()
void boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::CleanAuras () inline
Definition at line 515 of file boss_blood_queen_lana_thel.cpp.
         {
             instance->DoRemoveAurasDueToSpellOnPlayers(ESSENCE_OF_BLOOD_QUEEN);
             instance->DoRemoveAurasDueToSpellOnPlayers(ESSENCE_OF_BLOOD_QUEEN_PLR);
             instance->DoRemoveAurasDueToSpellOnPlayers(FRENZIED_BLOODTHIRST);
             instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_FRENZIED_BLOODTHIRST_VISUAL);
             instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_UNCONTROLLABLE_FRENZY);
             instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_BLOOD_MIRROR_DAMAGE);
             instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_BLOOD_MIRROR_VISUAL);
             instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_BLOOD_MIRROR_DUMMY);
             instance->DoRemoveAurasDueToSpellOnPlayers(DELIRIOUS_SLASH);
             instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_PACT_OF_THE_DARKFALLEN);
             instance->DoRemoveAurasDueToSpellOnPlayers(PRESENCE_OF_THE_DARKFALLEN);
         }
References DELIRIOUS_SLASH, InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), ESSENCE_OF_BLOOD_QUEEN, ESSENCE_OF_BLOOD_QUEEN_PLR, FRENZIED_BLOODTHIRST, BossAI::instance, PRESENCE_OF_THE_DARKFALLEN, SPELL_BLOOD_MIRROR_DAMAGE, SPELL_BLOOD_MIRROR_DUMMY, SPELL_BLOOD_MIRROR_VISUAL, SPELL_FRENZIED_BLOODTHIRST_VISUAL, SPELL_PACT_OF_THE_DARKFALLEN, and SPELL_UNCONTROLLABLE_FRENZY.
Referenced by EnterCombat(), JustDied(), and Reset().
DoAction()
void boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 245 of file boss_blood_queen_lana_thel.cpp.
         {
             if (action != ACTION_KILL_MINCHAR)
                 return;
             if (instance->GetBossState(DATA_BLOOD_QUEEN_LANA_THEL) == IN_PROGRESS)
                 _killMinchar = true;
             else
                 GoToMinchar();
         }
References _killMinchar, ACTION_KILL_MINCHAR, DATA_BLOOD_QUEEN_LANA_THEL, InstanceScript::GetBossState(), GoToMinchar(), IN_PROGRESS, and BossAI::instance.
EnterCombat()
void boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from BossAI.
Definition at line 171 of file boss_blood_queen_lana_thel.cpp.
         {
             if (!instance->CheckRequiredBosses(DATA_BLOOD_QUEEN_LANA_THEL, who->ToPlayer()) || !me->IsVisible())
             {
                 EnterEvadeMode();
                 instance->DoCastSpellOnPlayers(LIGHT_S_HAMMER_TELEPORT);
                 return;
             }
             bEnteredCombat = true;
             me->CastSpell(me, SPELL_SHROUD_OF_SORROW, true);
             me->CastSpell(me, SPELL_FRENZIED_BLOODTHIRST_VISUAL, true);
             events.Reset();
             events.ScheduleEvent(EVENT_BERSERK, 330000);
             events.ScheduleEvent(EVENT_VAMPIRIC_BITE, 15000);
             events.ScheduleEvent(EVENT_BLOOD_MIRROR, 2500);
             events.ScheduleEvent(EVENT_DELIRIOUS_SLASH, urand(10000, 12000));
             events.ScheduleEvent(EVENT_PACT_OF_THE_DARKFALLEN, 20000);
             events.ScheduleEvent(EVENT_SWARMING_SHADOWS, 30000);
             events.ScheduleEvent(EVENT_TWILIGHT_BLOODBOLT, urand(15000, 25000));
             events.ScheduleEvent(EVENT_AIR_PHASE, 124000 + uint32(Is25ManRaid() ? 3000 : 0));
             CleanAuras();
             me->setActive(true);
             DoZoneInCombat();
             Talk(SAY_AGGRO);
             if (instance->GetBossState(DATA_BLOOD_QUEEN_LANA_THEL) != DONE)
                 instance->SetBossState(DATA_BLOOD_QUEEN_LANA_THEL, IN_PROGRESS);
             _creditBloodQuickening = instance->GetData(DATA_BLOOD_QUICKENING_STATE) == IN_PROGRESS;
         }
References _creditBloodQuickening, bEnteredCombat, Unit::CastSpell(), InstanceScript::CheckRequiredBosses(), CleanAuras(), DATA_BLOOD_QUEEN_LANA_THEL, DATA_BLOOD_QUICKENING_STATE, InstanceScript::DoCastSpellOnPlayers(), DONE, CreatureAI::DoZoneInCombat(), EnterEvadeMode(), EVENT_AIR_PHASE, EVENT_BERSERK, EVENT_BLOOD_MIRROR, EVENT_DELIRIOUS_SLASH, EVENT_PACT_OF_THE_DARKFALLEN, EVENT_SWARMING_SHADOWS, EVENT_TWILIGHT_BLOODBOLT, EVENT_VAMPIRIC_BITE, InstanceScript::GetBossState(), ZoneScript::GetData(), IN_PROGRESS, BossAI::instance, ScriptedAI::Is25ManRaid(), Unit::IsVisible(), LIGHT_S_HAMMER_TELEPORT, ScriptedAI::me, SAY_AGGRO, WorldObject::setActive(), InstanceScript::SetBossState(), SPELL_FRENZIED_BLOODTHIRST_VISUAL, SPELL_SHROUD_OF_SORROW, CreatureAI::Talk(), Object::ToPlayer(), and urand().
EnterEvadeMode()
void boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 555 of file boss_blood_queen_lana_thel.cpp.
         {
             const Map::PlayerList& pl = me->GetMap()->GetPlayers();
             for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                 if (Player* p = itr->GetSource())
                     if (p->IsAlive() && p->HasAura(SPELL_UNCONTROLLABLE_FRENZY))
                         Unit::Kill(me, p);
             if (_killMinchar)
             {
                 if (!me->IsAlive())
                     return;
                 _EnterEvadeMode();
                 Reset();
                 GoToMinchar();
                 return;
             }
             BossAI::EnterEvadeMode();
         }
References CreatureAI::_EnterEvadeMode(), _killMinchar, MapRefMgr::begin(), MapRefMgr::end(), CreatureAI::EnterEvadeMode(), WorldObject::GetMap(), Map::GetPlayers(), GoToMinchar(), Unit::IsAlive(), Unit::Kill(), ScriptedAI::me, Reset(), and SPELL_UNCONTROLLABLE_FRENZY.
Referenced by EnterCombat().
GoToMinchar()
void boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::GoToMinchar () inline
Definition at line 230 of file boss_blood_queen_lana_thel.cpp.
         {
             if (!me->IsAlive())
                 return;
             instance->SetData(DATA_BLOOD_QUICKENING_STATE, DONE);
             me->AddUnitState(UNIT_STATE_EVADE);
             me->SendMeleeAttackStop(me->GetVictim());
             me->GetMotionMaster()->MoveIdle();
             me->StopMoving();
             me->SetCanFly(true);
             me->SetDisableGravity(true);
             me->SendMovementFlagUpdate();
             me->GetMotionMaster()->MovePoint(POINT_MINCHAR, mincharPos);
         }
References Unit::AddUnitState(), DATA_BLOOD_QUICKENING_STATE, DONE, Unit::GetMotionMaster(), Unit::GetVictim(), BossAI::instance, Unit::IsAlive(), ScriptedAI::me, mincharPos, MotionMaster::MoveIdle(), MotionMaster::MovePoint(), POINT_MINCHAR, Unit::SendMeleeAttackStop(), Unit::SendMovementFlagUpdate(), Creature::SetCanFly(), ZoneScript::SetData(), Creature::SetDisableGravity(), Unit::StopMoving(), and UNIT_STATE_EVADE.
Referenced by DoAction(), and EnterEvadeMode().
JustDied()
void boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 202 of file boss_blood_queen_lana_thel.cpp.
         {
             _JustDied();
             Talk(SAY_DEATH);
             if (Is25ManRaid() && me->HasAura(SPELL_SHADOWS_FATE))
                 DoCastAOE(SPELL_BLOOD_INFUSION_CREDIT, true);
             CleanAuras();
             if (_creditBloodQuickening)
             {
                 instance->SetData(DATA_BLOOD_QUICKENING_STATE, DONE);
                 Map::PlayerList const& pl = me->GetMap()->GetPlayers();
                 for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                     if (Player* p = itr->GetSource())
                         p->KilledMonsterCredit(RAID_MODE(NPC_INFILTRATOR_MINCHAR_BQ, NPC_BLOOD_QUICKENING_CREDIT_25));
                 if (Creature* minchar = me->FindNearestCreature(NPC_INFILTRATOR_MINCHAR_BQ, 200.0f))
                 {
                     minchar->SetUInt32Value(UNIT_NPC_EMOTESTATE, 0);
                     minchar->SetCanFly(false);
                     minchar->SetDisableGravity(false);
                     minchar->RemoveAllAuras();
                     minchar->GetMotionMaster()->MoveCharge(4629.3711f, 2782.6089f, 401.5301f, SPEED_CHARGE / 3.0f);
                 }
             }
         }
References _creditBloodQuickening, BossAI::_JustDied(), MapRefMgr::begin(), CleanAuras(), DATA_BLOOD_QUICKENING_STATE, UnitAI::DoCastAOE(), DONE, MapRefMgr::end(), WorldObject::FindNearestCreature(), WorldObject::GetMap(), Map::GetPlayers(), Unit::HasAura(), BossAI::instance, ScriptedAI::Is25ManRaid(), ScriptedAI::me, NPC_BLOOD_QUICKENING_CREDIT_25, NPC_INFILTRATOR_MINCHAR_BQ, ScriptedAI::RAID_MODE(), SAY_DEATH, ZoneScript::SetData(), SPEED_CHARGE, SPELL_BLOOD_INFUSION_CREDIT, SPELL_SHADOWS_FATE, CreatureAI::Talk(), and UNIT_NPC_EMOTESTATE.
JustReachedHome()
void boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::JustReachedHome () inline override virtual
Reimplemented from BossAI.
Definition at line 256 of file boss_blood_queen_lana_thel.cpp.
         {
             me->SetCanFly(false);
             me->SetDisableGravity(false);
             _JustReachedHome();
             if (bEnteredCombat)
             {
                 bEnteredCombat = false;
                 if (me->IsAlive() && instance->GetBossState(DATA_BLOOD_QUEEN_LANA_THEL) != DONE)
                     instance->SetBossState(DATA_BLOOD_QUEEN_LANA_THEL, FAIL);
             }
         }
References BossAI::_JustReachedHome(), bEnteredCombat, DATA_BLOOD_QUEEN_LANA_THEL, DONE, FAIL, InstanceScript::GetBossState(), BossAI::instance, Unit::IsAlive(), ScriptedAI::me, InstanceScript::SetBossState(), Creature::SetCanFly(), and Creature::SetDisableGravity().
KilledUnit()
void boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 270 of file boss_blood_queen_lana_thel.cpp.
         {
             if (victim->GetTypeId() == TYPEID_PLAYER)
                 Talk(SAY_KILL);
         }
References Object::GetTypeId(), SAY_KILL, CreatureAI::Talk(), and TYPEID_PLAYER.
MovementInform()
void boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 276 of file boss_blood_queen_lana_thel.cpp.
         {
             if (type != EFFECT_MOTION_TYPE && type != POINT_MOTION_TYPE)
                 return;
             switch (id)
             {
                 case POINT_CENTER:
                     me->CastSpell(me, SPELL_INCITE_TERROR, false);
                     events.ScheduleEvent(EVENT_AIR_PHASE, 100000 + uint32(Is25ManRaid() ? 0 : 20000));
                     events.ScheduleEvent(EVENT_AIR_START_FLYING, 2500);
                     break;
                 case POINT_AIR:
                     _bloodboltedPlayers.clear();
                     me->CastSpell(me, SPELL_BLOODBOLT_WHIRL, false);
                     Talk(SAY_AIR_PHASE);
                     events.ScheduleEvent(EVENT_AIR_FLY_DOWN, 7000);
                     break;
                 case POINT_GROUND:
                     me->SetCanFly(false);
                     me->SetDisableGravity(false);
                     me->SetReactState(REACT_AGGRESSIVE);
                     if (Unit* target = me->SelectVictim())
                         AttackStart(target);
                     events.RescheduleEvent(EVENT_PACT_OF_THE_DARKFALLEN, 5000);
                     events.RescheduleEvent(EVENT_SWARMING_SHADOWS, 20000);
                     break;
                 case POINT_MINCHAR:
                     me->CastSpell(me, SPELL_ANNIHILATE, true);
                     me->GetMotionMaster()->MoveTargetedHome();
                     Reset();
                 default:
                     break;
             }
         }
References _bloodboltedPlayers, ScriptedAI::AttackStart(), Unit::CastSpell(), EFFECT_MOTION_TYPE, EVENT_AIR_FLY_DOWN, EVENT_AIR_PHASE, EVENT_AIR_START_FLYING, EVENT_PACT_OF_THE_DARKFALLEN, EVENT_SWARMING_SHADOWS, Unit::GetMotionMaster(), ScriptedAI::Is25ManRaid(), ScriptedAI::me, MotionMaster::MoveTargetedHome(), POINT_AIR, POINT_CENTER, POINT_GROUND, POINT_MINCHAR, POINT_MOTION_TYPE, REACT_AGGRESSIVE, Reset(), SAY_AIR_PHASE, Creature::SelectVictim(), Creature::SetCanFly(), Creature::SetDisableGravity(), Creature::SetReactState(), SPELL_ANNIHILATE, SPELL_BLOODBOLT_WHIRL, SPELL_INCITE_TERROR, and CreatureAI::Talk().
Reset()
void boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 155 of file boss_blood_queen_lana_thel.cpp.
         {
             _creditBloodQuickening = false;
             _killMinchar = false;
             _tankGUID.Clear();
             _offtankGUID.Clear();
             _vampires.clear();
             CleanAuras();
             me->SetReactState(REACT_AGGRESSIVE);
             events.Reset();
             summons.DespawnAll();
             if (instance->GetBossState(DATA_BLOOD_QUEEN_LANA_THEL) != DONE)
                 instance->SetBossState(DATA_BLOOD_QUEEN_LANA_THEL, NOT_STARTED);
         }
References _creditBloodQuickening, _killMinchar, _offtankGUID, _tankGUID, _vampires, CleanAuras(), ObjectGuid::Clear(), DATA_BLOOD_QUEEN_LANA_THEL, SummonList::DespawnAll(), DONE, InstanceScript::GetBossState(), BossAI::instance, ScriptedAI::me, NOT_STARTED, REACT_AGGRESSIVE, InstanceScript::SetBossState(), Creature::SetReactState(), and BossAI::summons.
Referenced by EnterEvadeMode(), and MovementInform().
SetGUID()
void boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::SetGUID (ObjectGuid guid, int32 type = 0) inline override virtual
Reimplemented from UnitAI.
Definition at line 540 of file boss_blood_queen_lana_thel.cpp.
         {
             switch (type)
             {
                 case GUID_BLOODBOLT:
                     _bloodboltedPlayers.insert(guid);
                     break;
                 case GUID_VAMPIRE:
                     _vampires.insert(guid);
                     break;
                 default:
                     break;
             }
         }
References _bloodboltedPlayers, _vampires, GUID_BLOODBOLT, and GUID_VAMPIRE.
Referenced by UpdateAI().
UpdateAI()
void boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 312 of file boss_blood_queen_lana_thel.cpp.
         {
             if (!UpdateVictim() || !CheckInRoom())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_BERSERK:
                     Talk(EMOTE_BERSERK_RAID);
                     Talk(SAY_BERSERK);
                     me->CastSpell(me, SPELL_BERSERK, true);
                     break;
                 case EVENT_VAMPIRIC_BITE:
                     {
                         Player* target = nullptr;
                         float maxThreat = 0.0f;
                         const Map::PlayerList& pl = me->GetMap()->GetPlayers();
                         for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                             if (Player* p = itr->GetSource())
                                 if (p->IsAlive() && p != me->GetVictim() && p->GetGUID() != _offtankGUID && !p->IsGameMaster() && p->GetDistance(me) < 70.0f)
{
                                     float th = me->getThreatMgr().getThreatWithoutTemp(p);
                                     if (!target || th > maxThreat)
{
                                         target = p;
                                         maxThreat = th;
                                     }
                                 }
                         if (target)
{
                             me->CastSpell(target, SPELL_VAMPIRIC_BITE, false);
                             me->CastSpell((Unit*)nullptr, SPELL_VAMPIRIC_BITE_DUMMY, true);
                             Talk(SAY_VAMPIRIC_BITE);
                             SetGUID(target->GetGUID(), GUID_VAMPIRE);
                             target->CastSpell(target, SPELL_PRESENCE_OF_THE_DARKFALLEN_DUMMY, TRIGGERED_FULL_MASK);
                             target->CastSpell(target, SPELL_PRESENCE_OF_THE_DARKFALLEN_SE, TRIGGERED_FULL_MASK);
                         }
                     }
                     break;
                 case EVENT_BLOOD_MIRROR:
                     if (me->GetVictim())
                     {
                         std::list<Player*> myList;
                         const Map::PlayerList& pl = me->GetMap()->GetPlayers();
                         for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                             if (Player* p = itr->GetSource())
                                 if (p->IsAlive() && p != me->GetVictim() && !p->IsGameMaster() && !p->HasAura(SPELL_UNCONTROLLABLE_FRENZY))
                                     myList.push_back(p);
                         if (!myList.empty())
{
                             myList.sort(Acore::ObjectDistanceOrderPred(me->GetVictim()));
                             Player* target = myList.front();
                             if (me->GetVictim()->GetGUID() != _tankGUID || target->GetGUID() != _offtankGUID)
{
                                 // remove manually from previous, single target flag has nothing to do with this shit as caster is in every case different... tc retards
                                 if (_tankGUID)
                                     if (Player* prevTank = ObjectAccessor::GetPlayer(*me, _tankGUID))
{
                                         prevTank->RemoveAurasDueToSpell(SPELL_BLOOD_MIRROR_DAMAGE);
                                         prevTank->RemoveAurasDueToSpell(SPELL_BLOOD_MIRROR_VISUAL);
                                     }
                                 if (_offtankGUID)
                                     if (Player* prevOfftank = ObjectAccessor::GetPlayer(*me, _offtankGUID))
                                         prevOfftank->RemoveAurasDueToSpell(SPELL_BLOOD_MIRROR_DUMMY);
                                 if (target->GetDistance(me->GetVictim()) > 39.0f || me->GetDistance(me->GetVictim()) > 39.0f)
{
                                     _tankGUID.Clear();
                                     _offtankGUID.Clear();
                                     events.ScheduleEvent(EVENT_BLOOD_MIRROR, 2500);
                                     break;
                                 }
                                 _tankGUID = me->GetVictim()->GetGUID();
                                 _offtankGUID = target->GetGUID();
                                 target->CastSpell(me->GetVictim(), SPELL_BLOOD_MIRROR_DAMAGE, true);
                                 me->GetVictim()->CastSpell(target, SPELL_BLOOD_MIRROR_DUMMY, true);
                                 me->CastSpell(me->GetVictim(), SPELL_BLOOD_MIRROR_VISUAL, false);
                                 if (Is25ManRaid() && target->GetQuestStatus(QUEST_BLOOD_INFUSION) == QUEST_STATUS_INCOMPLETE &&
                                         target->HasAura(SPELL_UNSATED_CRAVING) && !target->HasAura(SPELL_THIRST_QUENCHED) && !target->HasAura(SPELL_GUSHING_WOUND))
                                     target->CastSpell(target, SPELL_GUSHING_WOUND, TRIGGERED_FULL_MASK);
                             }
                         }
                     }
                     events.ScheduleEvent(EVENT_BLOOD_MIRROR, 2500);
                     break;
                 case EVENT_DELIRIOUS_SLASH:
                     if (!me->HasReactState(REACT_PASSIVE))
                     {
                         Unit* target = nullptr;
                         if (_offtankGUID)
                             if (Unit* t = ObjectAccessor::GetUnit(*me, _offtankGUID))
                                 if (t->IsAlive() && t->GetDistance(me) < 10.0f)
                                     target = t;
                         if (!target)
                             if (me->GetVictim() && me->GetVictim()->GetDistance(me) < 10.0f)
                                 target = me->GetVictim();
                         if (!target)
{
                             events.ScheduleEvent(EVENT_DELIRIOUS_SLASH, 5000);
                             break;
                         }
                         me->CastSpell(target, SPELL_DELIRIOUS_SLASH, false);
                         events.ScheduleEvent(EVENT_DELIRIOUS_SLASH, urand(20000, 24000));
                         break;
                     }
                     events.ScheduleEvent(EVENT_DELIRIOUS_SLASH, 5000);
                     break;
                 case EVENT_PACT_OF_THE_DARKFALLEN:
                     if (!me->HasReactState(REACT_PASSIVE))
                     {
                         std::list<Player*> myList;
                         const Map::PlayerList& pl = me->GetMap()->GetPlayers();
                         for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                             if (Player* p = itr->GetSource())
                                 if (p->IsAlive() && p != me->GetVictim() && p->GetGUID() != _offtankGUID && !p->IsGameMaster() && p->GetDistance(me) < 100.0f && !p->HasAura(SPELL_UNCONTROLLABLE_FRENZY))
                                     myList.push_back(p);
                         Acore::Containers::RandomResize(myList, Is25ManRaid() ? 3 : 2);
                         if (myList.size() > 1)
{
                             Talk(SAY_PACT_OF_THE_DARKFALLEN);
                             for (std::list<Player*>::iterator itr = myList.begin(); itr != myList.end(); ++itr)
                                 me->CastSpell(*itr, SPELL_PACT_OF_THE_DARKFALLEN, false);
                             events.ScheduleEvent(EVENT_PACT_OF_THE_DARKFALLEN, 30000);
                         }
                         else
                             events.ScheduleEvent(EVENT_PACT_OF_THE_DARKFALLEN, 5000);
                         break;
                     }
                     events.ScheduleEvent(EVENT_PACT_OF_THE_DARKFALLEN, 5000);
                     break;
                 case EVENT_SWARMING_SHADOWS:
                     if (!me->HasReactState(REACT_PASSIVE))
                     {
                         std::list<Player*> myList;
                         const Map::PlayerList& pl = me->GetMap()->GetPlayers();
                         for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                             if (Player* p = itr->GetSource())
                                 if (p->IsAlive() && p != me->GetVictim() && p->GetGUID() != _offtankGUID && !p->IsGameMaster() && !p->HasAura(SPELL_PACT_OF_THE_DARKFALLEN) && !p->HasAura(SPELL_UNCONTROLLABLE_FRENZY))
                                     myList.push_back(p);
                         if (!myList.empty())
{
                             Acore::Containers::RandomResize(myList, 1);
                             Player* target = myList.front();
                             Talk(EMOTE_SWARMING_SHADOWS, target);
                             Talk(SAY_SWARMING_SHADOWS);
                             me->CastSpell(target, SPELL_SWARMING_SHADOWS, false);
                         }
                         events.ScheduleEvent(EVENT_SWARMING_SHADOWS, 30000);
                         break;
                     }
                     events.ScheduleEvent(EVENT_SWARMING_SHADOWS, 5000);
                     break;
                 case EVENT_TWILIGHT_BLOODBOLT:
                     if (!me->HasReactState(REACT_PASSIVE))
                     {
                         std::list<Player*> myList;
                         const Map::PlayerList& pl = me->GetMap()->GetPlayers();
                         for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                             if (Player* p = itr->GetSource())
                                 if (p->IsAlive() && p != me->GetVictim() && p->GetGUID() != _offtankGUID && !p->IsGameMaster() && !p->HasAura(SPELL_PACT_OF_THE_DARKFALLEN) && !p->HasAura(SPELL_UNCONTROLLABLE_FRENZY))
                                     myList.push_back(p);
                         Acore::Containers::RandomResize(myList, uint32(Is25ManRaid() ? 4 : 2));
                         for (std::list<Player*>::iterator itr = myList.begin(); itr != myList.end(); ++itr)
                             me->CastSpell(*itr, SPELL_TWILIGHT_BLOODBOLT, false);
                         me->CastSpell(me, SPELL_TWILIGHT_BLOODBOLT_TARGET, false);
                         events.ScheduleEvent(EVENT_TWILIGHT_BLOODBOLT, urand(10000, 15000));
                         break;
                     }
                     events.ScheduleEvent(EVENT_TWILIGHT_BLOODBOLT, 5000);
                     break;
                 case EVENT_AIR_PHASE:
                     me->AttackStop();
                     me->SetReactState(REACT_PASSIVE);
                     me->GetMotionMaster()->MovePoint(POINT_CENTER, centerPos);
                     break;
                 case EVENT_AIR_START_FLYING:
                     me->SendMeleeAttackStop(me->GetVictim());
                     me->GetMotionMaster()->MoveIdle();
                     me->DisableSpline();
                     me->SetCanFly(true);
                     me->SetDisableGravity(true);
                     me->SendMovementFlagUpdate();
                     me->GetMotionMaster()->MoveTakeoff(POINT_AIR, airPos, 0.642857f * 7.0f);
                     break;
                 case EVENT_AIR_FLY_DOWN:
                     me->GetMotionMaster()->MoveLand(POINT_GROUND, centerPos, 0.642857f * 7.0f);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References _offtankGUID, _tankGUID, airPos, Unit::AttackStop(), MapRefMgr::begin(), Unit::CastSpell(), centerPos, BossAI::CheckInRoom(), ObjectGuid::Clear(), diff(), Unit::DisableSpline(), UnitAI::DoMeleeAttackIfReady(), EMOTE_BERSERK_RAID, EMOTE_SWARMING_SHADOWS, MapRefMgr::end(), EVENT_AIR_FLY_DOWN, EVENT_AIR_PHASE, EVENT_AIR_START_FLYING, EVENT_BERSERK, EVENT_BLOOD_MIRROR, EVENT_DELIRIOUS_SLASH, EVENT_PACT_OF_THE_DARKFALLEN, EVENT_SWARMING_SHADOWS, EVENT_TWILIGHT_BLOODBOLT, EVENT_VAMPIRIC_BITE, WorldObject::GetDistance(), Object::GetGUID(), WorldObject::GetMap(), Unit::GetMotionMaster(), ObjectAccessor::GetPlayer(), Map::GetPlayers(), Player::GetQuestStatus(), Unit::getThreatMgr(), ThreatMgr::getThreatWithoutTemp(), ObjectAccessor::GetUnit(), Unit::GetVictim(), GUID_VAMPIRE, Unit::HasAura(), Creature::HasReactState(), Unit::HasUnitState(), ScriptedAI::Is25ManRaid(), ScriptedAI::me, MotionMaster::MoveIdle(), MotionMaster::MoveLand(), MotionMaster::MovePoint(), MotionMaster::MoveTakeoff(), POINT_AIR, POINT_CENTER, POINT_GROUND, QUEST_BLOOD_INFUSION, QUEST_STATUS_INCOMPLETE, Acore::Containers::RandomResize(), REACT_PASSIVE, Unit::RemoveAurasDueToSpell(), SAY_BERSERK, SAY_PACT_OF_THE_DARKFALLEN, SAY_SWARMING_SHADOWS, SAY_VAMPIRIC_BITE, Unit::SendMeleeAttackStop(), Unit::SendMovementFlagUpdate(), Creature::SetCanFly(), Creature::SetDisableGravity(), SetGUID(), Creature::SetReactState(), SPELL_BERSERK, SPELL_BLOOD_MIRROR_DAMAGE, SPELL_BLOOD_MIRROR_DUMMY, SPELL_BLOOD_MIRROR_VISUAL, SPELL_DELIRIOUS_SLASH, SPELL_GUSHING_WOUND, SPELL_PACT_OF_THE_DARKFALLEN, SPELL_PRESENCE_OF_THE_DARKFALLEN_DUMMY, SPELL_PRESENCE_OF_THE_DARKFALLEN_SE, SPELL_SWARMING_SHADOWS, SPELL_THIRST_QUENCHED, SPELL_TWILIGHT_BLOODBOLT, SPELL_TWILIGHT_BLOODBOLT_TARGET, SPELL_UNCONTROLLABLE_FRENZY, SPELL_UNSATED_CRAVING, SPELL_VAMPIRIC_BITE, SPELL_VAMPIRIC_BITE_DUMMY, CreatureAI::Talk(), TRIGGERED_FULL_MASK, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
WasBloodbolted()
bool boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::WasBloodbolted (ObjectGuid guid) inline
Definition at line 535 of file boss_blood_queen_lana_thel.cpp.
         {
             return _bloodboltedPlayers.count(guid) != 0;
         }
References _bloodboltedPlayers.
Referenced by BloodboltHitCheck::operator()().
WasVampire()
bool boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::WasVampire (ObjectGuid guid) inline
Definition at line 530 of file boss_blood_queen_lana_thel.cpp.
         {
             return _vampires.count(guid) != 0;
         }
References _vampires.
Member Data Documentation
_bloodboltedPlayers
GuidSet boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::_bloodboltedPlayers
Definition at line 151 of file boss_blood_queen_lana_thel.cpp.
Referenced by MovementInform(), SetGUID(), and WasBloodbolted().
_creditBloodQuickening
bool boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::_creditBloodQuickening
Definition at line 147 of file boss_blood_queen_lana_thel.cpp.
Referenced by EnterCombat(), JustDied(), and Reset().
_killMinchar
bool boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::_killMinchar
Definition at line 148 of file boss_blood_queen_lana_thel.cpp.
Referenced by DoAction(), EnterEvadeMode(), and Reset().
_offtankGUID
ObjectGuid boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::_offtankGUID
Definition at line 150 of file boss_blood_queen_lana_thel.cpp.
Referenced by Reset(), and UpdateAI().
_tankGUID
ObjectGuid boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::_tankGUID
Definition at line 149 of file boss_blood_queen_lana_thel.cpp.
Referenced by Reset(), and UpdateAI().
_vampires
GuidSet boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::_vampires
Definition at line 152 of file boss_blood_queen_lana_thel.cpp.
Referenced by Reset(), SetGUID(), and WasVampire().
bEnteredCombat
bool boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::bEnteredCombat
Definition at line 153 of file boss_blood_queen_lana_thel.cpp.
Referenced by boss_blood_queen_lana_thelAI(), EnterCombat(), and JustReachedHome().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_blood_queen_lana_thel.cpp