Azerotcore-wotlk: go_veil_skith_cage Class Reference
go_veil_skith_cage Class Reference
Public Member Functions
go_veil_skith_cage ()
bool OnGossipHello (Player *player, GameObject *go) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Definition at line 1603 of file go_scripts.cpp.
Constructor & Destructor Documentation
go_veil_skith_cage()
go_veil_skith_cage::go_veil_skith_cage () inline
Definition at line 1606 of file go_scripts.cpp.
 : GameObjectScript("go_veil_skith_cage") { }
Member Function Documentation
OnGossipHello()
bool go_veil_skith_cage::OnGossipHello (Player * player, GameObject * go) inline override virtual
Reimplemented from GameObjectScript.
Definition at line 1608 of file go_scripts.cpp.
     {
         go->UseDoorOrButton();
         if (player->GetQuestStatus(QUEST_MISSING_FRIENDS) == QUEST_STATUS_INCOMPLETE)
         {
             std::list<Creature*> childrenList;
             GetCreatureListWithEntryInGrid(childrenList, go, NPC_CAPTIVE_CHILD, INTERACTION_DISTANCE);
             for (std::list<Creature*>::const_iterator itr = childrenList.begin(); itr != childrenList.end(); ++itr)
             {
                 player->KilledMonsterCredit(NPC_CAPTIVE_CHILD, (*itr)->GetGUID());
                 (*itr)->DespawnOrUnsummon(5000);
                 (*itr)->GetMotionMaster()->MovePoint(1, go->GetPositionX() + 5, go->GetPositionY(), go->GetPositionZ());
                 (*itr)->AI()->Talk(SAY_FREE_0);
                 (*itr)->GetMotionMaster()->Clear();
             }
         }
         return false;
     }
References GetCreatureListWithEntryInGrid(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Player::GetQuestStatus(), INTERACTION_DISTANCE, Player::KilledMonsterCredit(), NPC_CAPTIVE_CHILD, QUEST_MISSING_FRIENDS, QUEST_STATUS_INCOMPLETE, SAY_FREE_0, and GameObject::UseDoorOrButton().
The documentation for this class was generated from the following file:
src/server/scripts/World/go_scripts.cpp