Azerotcore-wotlk: ban_commandscript Class Reference
ban_commandscript Class Reference
Public Member Functions
ban_commandscript ()
ChatCommandTable GetCommands () const override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Static Public Member Functions
static bool HandleBanAccountCommand (ChatHandler *handler, char const *args)
static bool HandleBanCharacterCommand (ChatHandler *handler, char const *args)
static bool HandleBanAccountByCharCommand (ChatHandler *handler, char const *args)
static bool HandleBanIPCommand (ChatHandler *handler, char const *args)
static bool HandleBanHelper (BanMode mode, char const *args, ChatHandler *handler)
static bool HandleBanInfoAccountCommand (ChatHandler *handler, char const *args)
static bool HandleBanInfoHelper (uint32 accountId, char const *accountName, ChatHandler *handler)
static bool HandleBanInfoCharacterCommand (ChatHandler *handler, char const *args)
static bool HandleBanInfoIPCommand (ChatHandler *handler, char const *args)
static bool HandleBanListAccountCommand (ChatHandler *handler, char const *args)
static bool HandleBanListHelper (PreparedQueryResult result, ChatHandler *handler)
static bool HandleBanListCharacterCommand (ChatHandler *handler, char const *args)
static bool HandleBanListIPCommand (ChatHandler *handler, char const *args)
static bool HandleUnBanAccountCommand (ChatHandler *handler, char const *args)
static bool HandleUnBanCharacterCommand (ChatHandler *handler, char const *args)
static bool HandleUnBanAccountByCharCommand (ChatHandler *handler, char const *args)
static bool HandleUnBanIPCommand (ChatHandler *handler, char const *args)
static bool HandleUnBanHelper (BanMode mode, char const *args, ChatHandler *handler)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 48 of file cs_ban.cpp.
Constructor & Destructor Documentation
ban_commandscript()
ban_commandscript::ban_commandscript () inline
Definition at line 51 of file cs_ban.cpp.
 : CommandScript("ban_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable ban_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
Definition at line 53 of file cs_ban.cpp.
     {
         static ChatCommandTable unbanCommandTable =
         {
             { "account",        SEC_ADMINISTRATOR,  true,  &HandleUnBanAccountCommand,          "" },
             { "character",      SEC_ADMINISTRATOR,  true,  &HandleUnBanCharacterCommand,        "" },
             { "playeraccount",  SEC_ADMINISTRATOR,  true,  &HandleUnBanAccountByCharCommand,    "" },
             { "ip",             SEC_ADMINISTRATOR,  true,  &HandleUnBanIPCommand,               "" }
         };
         static ChatCommandTable banlistCommandTable =
         {
             { "account",        SEC_GAMEMASTER,  true,  &HandleBanListAccountCommand,        "" },
             { "character",      SEC_GAMEMASTER,  true,  &HandleBanListCharacterCommand,      "" },
             { "ip",             SEC_GAMEMASTER,  true,  &HandleBanListIPCommand,             "" }
         };
         static ChatCommandTable baninfoCommandTable =
         {
             { "account",        SEC_GAMEMASTER,  true,  &HandleBanInfoAccountCommand,        "" },
             { "character",      SEC_GAMEMASTER,  true,  &HandleBanInfoCharacterCommand,      "" },
             { "ip",             SEC_GAMEMASTER,  true,  &HandleBanInfoIPCommand,             "" }
         };
         static ChatCommandTable banCommandTable =
         {
             { "account",        SEC_GAMEMASTER,  true,  &HandleBanAccountCommand,            "" },
             { "character",      SEC_GAMEMASTER,  true,  &HandleBanCharacterCommand,          "" },
             { "playeraccount",  SEC_GAMEMASTER,  true,  &HandleBanAccountByCharCommand,      "" },
             { "ip",             SEC_GAMEMASTER,  true,  &HandleBanIPCommand,                 "" }
         };
         static ChatCommandTable commandTable =
         {
             { "ban",            SEC_GAMEMASTER,     true,  nullptr, "", banCommandTable },
             { "baninfo",        SEC_GAMEMASTER,     true,  nullptr, "", baninfoCommandTable },
             { "banlist",        SEC_GAMEMASTER,     true,  nullptr, "", banlistCommandTable },
             { "unban",          SEC_ADMINISTRATOR,  true,  nullptr, "", unbanCommandTable }
         };
         return commandTable;
     }
References SEC_ADMINISTRATOR, and SEC_GAMEMASTER.
HandleBanAccountByCharCommand()
static bool ban_commandscript::HandleBanAccountByCharCommand (ChatHandler * handler, char const * args) inline static
Definition at line 154 of file cs_ban.cpp.
     {
         return HandleBanHelper(BAN_CHARACTER, args, handler);
     }
References BAN_CHARACTER.
HandleBanAccountCommand()
static bool ban_commandscript::HandleBanAccountCommand (ChatHandler * handler, char const * args) inline static
Definition at line 96 of file cs_ban.cpp.
     {
         return HandleBanHelper(BAN_ACCOUNT, args, handler);
     }
References BAN_ACCOUNT.
HandleBanCharacterCommand()
static bool ban_commandscript::HandleBanCharacterCommand (ChatHandler * handler, char const * args) inline static
Definition at line 101 of file cs_ban.cpp.
     {
         if (!*args)
             return false;
         char* nameStr = strtok((char*)args, " ");
         if (!nameStr)
             return false;
         std::string name = nameStr;
         char* durationStr = strtok(nullptr, " ");
         if (!durationStr || !atoi(durationStr))
             return false;
         char* reasonStr = strtok(nullptr, "");
         if (!reasonStr)
             return false;
         if (!normalizePlayerName(name))
         {
             handler->SendSysMessage(LANG_PLAYER_NOT_FOUND);
             handler->SetSentErrorMessage(true);
             return false;
         }
         switch (sBan->BanCharacter(name, durationStr, reasonStr, handler->GetSession() ? handler->GetSession()->GetPlayerName() : ""))
         {
             case BAN_SUCCESS:
                 if (atoi(durationStr) > 0)
                 {
                     if (!sWorld->getBoolConfig(CONFIG_SHOW_BAN_IN_WORLD))
                         handler->PSendSysMessage(LANG_BAN_YOUBANNED, name.c_str(), secsToTimeString(TimeStringToSecs(durationStr), true).c_str(), reasonStr);
                 }
                 else
                 {
                     if (!sWorld->getBoolConfig(CONFIG_SHOW_BAN_IN_WORLD))
                         handler->PSendSysMessage(LANG_BAN_YOUPERMBANNED, name.c_str(), reasonStr);
                 }
                 break;
             case BAN_NOTFOUND:
                 {
                     handler->PSendSysMessage(LANG_BAN_NOTFOUND, "character", name.c_str());
                     handler->SetSentErrorMessage(true);
                     return false;
                 }
             default:
                 break;
         }
         return true;
     }
References BAN_NOTFOUND, BAN_SUCCESS, CONFIG_SHOW_BAN_IN_WORLD, WorldSession::GetPlayerName(), ChatHandler::GetSession(), LANG_BAN_NOTFOUND, LANG_BAN_YOUBANNED, LANG_BAN_YOUPERMBANNED, LANG_PLAYER_NOT_FOUND, normalizePlayerName(), ChatHandler::PSendSysMessage(), sBan, secsToTimeString(), ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), sWorld, and TimeStringToSecs().
HandleBanHelper()
static bool ban_commandscript::HandleBanHelper (BanMode mode, char const * args, ChatHandler * handler) inline static
Definition at line 164 of file cs_ban.cpp.
     {
         if (!*args)
             return false;
         char* cnameOrIP = strtok((char*)args, " ");
         if (!cnameOrIP)
             return false;
         std::string nameOrIP = cnameOrIP;
         char* durationStr = strtok(nullptr, " ");
         if (!durationStr || !atoi(durationStr))
             return false;
         char* reasonStr = strtok(nullptr, "");
         if (!reasonStr)
             return false;
         switch (mode)
         {
             case BAN_ACCOUNT:
                 if (!Utf8ToUpperOnlyLatin(nameOrIP))
                 {
                     handler->PSendSysMessage(LANG_ACCOUNT_NOT_EXIST, nameOrIP.c_str());
                     handler->SetSentErrorMessage(true);
                     return false;
                 }
                 break;
             case BAN_CHARACTER:
                 if (!normalizePlayerName(nameOrIP))
                 {
                     handler->SendSysMessage(LANG_PLAYER_NOT_FOUND);
                     handler->SetSentErrorMessage(true);
                     return false;
                 }
                 break;
             case BAN_IP:
                 if (!IsIPAddress(nameOrIP.c_str()))
                     return false;
                 break;
         }
         BanReturn banReturn;
         switch (mode)
         {
             case BAN_ACCOUNT:
                 banReturn = sBan->BanAccount(nameOrIP, durationStr, reasonStr, handler->GetSession() ? handler->GetSession()->GetPlayerName() : "");
                 break;
             case BAN_CHARACTER:
                 banReturn = sBan->BanAccountByPlayerName(nameOrIP, durationStr, reasonStr, handler->GetSession() ? handler->GetSession()->GetPlayerName() : "");
                 break;
             case BAN_IP:
             default:
                 banReturn = sBan->BanIP(nameOrIP, durationStr, reasonStr, handler->GetSession() ? handler->GetSession()->GetPlayerName() : "");
                 break;
         }
         switch (banReturn)
         {
             case BAN_SUCCESS:
                 if (atoi(durationStr) > 0)
                 {
                     if (!sWorld->getBoolConfig(CONFIG_SHOW_BAN_IN_WORLD))
                         handler->PSendSysMessage(LANG_BAN_YOUBANNED, nameOrIP.c_str(), secsToTimeString(TimeStringToSecs(durationStr), true).c_str(), reasonStr);
                 }
                 else
                 {
                     if (!sWorld->getBoolConfig(CONFIG_SHOW_BAN_IN_WORLD))
                         handler->PSendSysMessage(LANG_BAN_YOUPERMBANNED, nameOrIP.c_str(), reasonStr);
                 }
                 break;
             case BAN_SYNTAX_ERROR:
                 return false;
             case BAN_NOTFOUND:
                 switch (mode)
                 {
                     default:
                         handler->PSendSysMessage(LANG_BAN_NOTFOUND, "account", nameOrIP.c_str());
                         break;
                     case BAN_CHARACTER:
                         handler->PSendSysMessage(LANG_BAN_NOTFOUND, "character", nameOrIP.c_str());
                         break;
                     case BAN_IP:
                         handler->PSendSysMessage(LANG_BAN_NOTFOUND, "ip", nameOrIP.c_str());
                         break;
                 }
                 handler->SetSentErrorMessage(true);
                 return false;
             case BAN_LONGER_EXISTS:
                 handler->PSendSysMessage("Unsuccessful! A longer ban is already present on this account!");
                 break;
             default:
                 break;
         }
         return true;
     }
References BAN_ACCOUNT, BAN_CHARACTER, BAN_IP, BAN_LONGER_EXISTS, BAN_NOTFOUND, BAN_SUCCESS, BAN_SYNTAX_ERROR, CONFIG_SHOW_BAN_IN_WORLD, WorldSession::GetPlayerName(), ChatHandler::GetSession(), IsIPAddress(), LANG_ACCOUNT_NOT_EXIST, LANG_BAN_NOTFOUND, LANG_BAN_YOUBANNED, LANG_BAN_YOUPERMBANNED, LANG_PLAYER_NOT_FOUND, normalizePlayerName(), ChatHandler::PSendSysMessage(), sBan, secsToTimeString(), ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), sWorld, TimeStringToSecs(), and Utf8ToUpperOnlyLatin().
HandleBanInfoAccountCommand()
static bool ban_commandscript::HandleBanInfoAccountCommand (ChatHandler * handler, char const * args) inline static
Definition at line 264 of file cs_ban.cpp.
     {
         if (!*args)
             return false;
         char* nameStr = strtok((char*)args, "");
         if (!nameStr)
             return false;
         std::string accountName = nameStr;
         if (!Utf8ToUpperOnlyLatin(accountName))
         {
             handler->PSendSysMessage(LANG_ACCOUNT_NOT_EXIST, accountName.c_str());
             handler->SetSentErrorMessage(true);
             return false;
         }
         uint32 accountId = AccountMgr::GetId(accountName);
         if (!accountId)
         {
             handler->PSendSysMessage(LANG_ACCOUNT_NOT_EXIST, accountName.c_str());
             return true;
         }
         return HandleBanInfoHelper(accountId, accountName.c_str(), handler);
     }
References AccountMgr::GetId(), LANG_ACCOUNT_NOT_EXIST, ChatHandler::PSendSysMessage(), ChatHandler::SetSentErrorMessage(), and Utf8ToUpperOnlyLatin().
HandleBanInfoCharacterCommand()
static bool ban_commandscript::HandleBanInfoCharacterCommand (ChatHandler * handler, char const * args) inline static
Definition at line 318 of file cs_ban.cpp.
     {
         if (!*args)
             return false;
         Player* target = ObjectAccessor::FindPlayerByName(args, false);
         ObjectGuid targetGuid;
         std::string name(args);
         if (!target)
         {
             targetGuid = sWorld->GetGlobalPlayerGUID(name);
             if (!targetGuid)
             {
                 handler->PSendSysMessage(LANG_BANINFO_NOCHARACTER);
                 return false;
             }
         }
         else
             targetGuid = target->GetGUID();
         CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_BANINFO);
         stmt->setUInt32(0, targetGuid.GetCounter());
         PreparedQueryResult result = CharacterDatabase.Query(stmt);
         if (!result)
         {
             handler->PSendSysMessage(LANG_CHAR_NOT_BANNED, name.c_str());
             return true;
         }
         handler->PSendSysMessage(LANG_BANINFO_BANHISTORY, name.c_str());
         do
         {
             Field* fields = result->Fetch();
             time_t unbanDate = time_t(fields[3].GetUInt32());
             bool active = false;
             if (fields[2].GetUInt8() && (!fields[1].GetUInt32() || unbanDate >= time(nullptr)))
                 active = true;
             bool permanent = (fields[1].GetUInt32() == uint32(0));
             std::string banTime = permanent ? handler->GetAcoreString(LANG_BANINFO_INFINITE) : secsToTimeString(fields[1].GetUInt64(), true);
             handler->PSendSysMessage(LANG_BANINFO_HISTORYENTRY,
                                      fields[0].GetCString(), banTime.c_str(), active ? handler->GetAcoreString(LANG_YES) : handler->GetAcoreString(LANG_NO), fields[4].GetCString(), fields[5].GetCString());
         } while (result->NextRow());
         return true;
     }
References CHAR_SEL_BANINFO, CharacterDatabase, ObjectAccessor::FindPlayerByName(), ChatHandler::GetAcoreString(), ObjectGuid::GetCounter(), Field::GetCString(), Object::GetGUID(), Field::GetUInt32(), LANG_BANINFO_BANHISTORY, LANG_BANINFO_HISTORYENTRY, LANG_BANINFO_INFINITE, LANG_BANINFO_NOCHARACTER, LANG_CHAR_NOT_BANNED, LANG_NO, LANG_YES, ChatHandler::PSendSysMessage(), secsToTimeString(), PreparedStatementBase::setUInt32(), and sWorld.
HandleBanInfoHelper()
static bool ban_commandscript::HandleBanInfoHelper (uint32 accountId, char const * accountName, ChatHandler * handler) inline static
Definition at line 291 of file cs_ban.cpp.
     {
         QueryResult result = LoginDatabase.PQuery("SELECT FROM_UNIXTIME(bandate, '%%Y-%%m-%%d..%%H:%%I:%%s') as bandate, unbandate-bandate, active, unbandate, banreason, bannedby FROM account_banned WHERE id = '%u' ORDER BY bandate ASC", accountId);
         if (!result)
         {
             handler->PSendSysMessage(LANG_BANINFO_NOACCOUNTBAN, accountName);
             return true;
         }
         handler->PSendSysMessage(LANG_BANINFO_BANHISTORY, accountName);
         do
         {
             Field* fields = result->Fetch();
             time_t unbanDate = time_t(fields[3].GetUInt32());
             bool active = false;
             if (fields[2].GetBool() && (fields[1].GetUInt64() == uint64(0) || unbanDate >= time(nullptr)))
                 active = true;
             bool permanent = (fields[1].GetUInt64() == uint64(0));
             std::string banTime = permanent ? handler->GetAcoreString(LANG_BANINFO_INFINITE) : secsToTimeString(fields[1].GetUInt64(), true);
             handler->PSendSysMessage(LANG_BANINFO_HISTORYENTRY,
                                      fields[0].GetCString(), banTime.c_str(), active ? handler->GetAcoreString(LANG_YES) : handler->GetAcoreString(LANG_NO), fields[4].GetCString(), fields[5].GetCString());
         } while (result->NextRow());
         return true;
     }
References ChatHandler::GetAcoreString(), Field::GetCString(), Field::GetUInt64(), LANG_BANINFO_BANHISTORY, LANG_BANINFO_HISTORYENTRY, LANG_BANINFO_INFINITE, LANG_BANINFO_NOACCOUNTBAN, LANG_NO, LANG_YES, LoginDatabase, ChatHandler::PSendSysMessage(), and secsToTimeString().
HandleBanInfoIPCommand()
static bool ban_commandscript::HandleBanInfoIPCommand (ChatHandler * handler, char const * args) inline static
Definition at line 366 of file cs_ban.cpp.
     {
         if (!*args)
             return false;
         char* ipStr = strtok((char*)args, "");
         if (!ipStr)
             return false;
         if (!IsIPAddress(ipStr))
             return false;
         std::string IP = ipStr;
         LoginDatabase.EscapeString(IP);
         QueryResult result = LoginDatabase.PQuery("SELECT ip, FROM_UNIXTIME(bandate), FROM_UNIXTIME(unbandate), unbandate-UNIX_TIMESTAMP(), banreason, bannedby, unbandate-bandate FROM ip_banned WHERE ip = '%s'", IP.c_str());
         if (!result)
         {
             handler->PSendSysMessage(LANG_BANINFO_NOIP);
             return true;
         }
         Field* fields = result->Fetch();
         bool permanent = !fields[6].GetUInt64();
         handler->PSendSysMessage(LANG_BANINFO_IPENTRY,
                                  fields[0].GetCString(), fields[1].GetCString(), permanent ? handler->GetAcoreString(LANG_BANINFO_NEVER) : fields[2].GetCString(),
                                  permanent ? handler->GetAcoreString(LANG_BANINFO_INFINITE) : secsToTimeString(fields[3].GetUInt64(), true).c_str(), fields[4].GetCString(), fields[5].GetCString());
         return true;
     }
References ChatHandler::GetAcoreString(), Field::GetCString(), Field::GetUInt64(), IsIPAddress(), LANG_BANINFO_INFINITE, LANG_BANINFO_IPENTRY, LANG_BANINFO_NEVER, LANG_BANINFO_NOIP, LoginDatabase, ChatHandler::PSendSysMessage(), and secsToTimeString().
HandleBanIPCommand()
static bool ban_commandscript::HandleBanIPCommand (ChatHandler * handler, char const * args) inline static
Definition at line 159 of file cs_ban.cpp.
     {
         return HandleBanHelper(BAN_IP, args, handler);
     }
References BAN_IP.
HandleBanListAccountCommand()
static bool ban_commandscript::HandleBanListAccountCommand (ChatHandler * handler, char const * args) inline static
Definition at line 397 of file cs_ban.cpp.
     {
         LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_DEL_EXPIRED_IP_BANS);
         LoginDatabase.Execute(stmt);
         char* filterStr = strtok((char*)args, " ");
         std::string filter = filterStr ? filterStr : "";
         PreparedQueryResult result;
         if (filter.empty())
         {
             LoginDatabasePreparedStatement* stmt2 = LoginDatabase.GetPreparedStatement(LOGIN_SEL_ACCOUNT_BANNED_ALL);
             result = LoginDatabase.Query(stmt2);
         }
         else
         {
             LoginDatabasePreparedStatement* stmt2 = LoginDatabase.GetPreparedStatement(LOGIN_SEL_ACCOUNT_BANNED_BY_USERNAME);
             stmt2->setString(0, filter);
             result = LoginDatabase.Query(stmt2);
         }
         if (!result)
         {
             handler->PSendSysMessage(LANG_BANLIST_NOACCOUNT);
             return true;
         }
         return HandleBanListHelper(result, handler);
     }
References LANG_BANLIST_NOACCOUNT, LOGIN_DEL_EXPIRED_IP_BANS, LOGIN_SEL_ACCOUNT_BANNED_ALL, LOGIN_SEL_ACCOUNT_BANNED_BY_USERNAME, LoginDatabase, ChatHandler::PSendSysMessage(), and PreparedStatementBase::setString().
HandleBanListCharacterCommand()
static bool ban_commandscript::HandleBanListCharacterCommand (ChatHandler * handler, char const * args) inline static
Definition at line 506 of file cs_ban.cpp.
     {
         if (!*args)
             return false;
         char* filterStr = strtok((char*)args, " ");
         if (!filterStr)
             return false;
         std::string filter(filterStr);
         CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_GUID_BY_NAME_FILTER);
         stmt->setString(0, filter);
         PreparedQueryResult result = CharacterDatabase.Query(stmt);
         if (!result)
         {
             handler->PSendSysMessage(LANG_BANLIST_NOCHARACTER);
             return true;
         }
         handler->PSendSysMessage(LANG_BANLIST_MATCHINGCHARACTER);
         // Chat short output
         if (handler->GetSession())
         {
             do
             {
                 Field* fields = result->Fetch();
                 CharacterDatabasePreparedStatement* stmt2 = CharacterDatabase.GetPreparedStatement(CHAR_SEL_BANNED_NAME);
                 stmt2->setUInt32(0, fields[0].GetUInt32());
                 PreparedQueryResult banResult = CharacterDatabase.Query(stmt2);
                 if (banResult)
                     handler->PSendSysMessage("%s", (*banResult)[0].GetCString());
             } while (result->NextRow());
         }
         // Console wide output
         else
         {
             handler->SendSysMessage(LANG_BANLIST_CHARACTERS);
             handler->SendSysMessage(" =============================================================================== ");
             handler->SendSysMessage(LANG_BANLIST_CHARACTERS_HEADER);
             do
             {
                 handler->SendSysMessage("-------------------------------------------------------------------------------");
                 Field* fields = result->Fetch();
                 std::string char_name = fields[1].GetString();
                 CharacterDatabasePreparedStatement* stmt2 = CharacterDatabase.GetPreparedStatement(CHAR_SEL_BANINFO_LIST);
                 stmt2->setUInt32(0, fields[0].GetUInt32());
                 PreparedQueryResult banInfo = CharacterDatabase.Query(stmt2);
                 if (banInfo)
                 {
                     Field* banFields = banInfo->Fetch();
                     do
                     {
                         time_t timeBan = time_t(banFields[0].GetUInt32());
                         tm tmBan;
                         localtime_r(&timeBan, &tmBan);
                         if (banFields[0].GetUInt32() == banFields[1].GetUInt32())
{
                             handler->PSendSysMessage("|%-15.15s|%02d-%02d-%02d %02d:%02d|   permanent  |%-15.15s|%-15.15s|",
                                                      char_name.c_str(), tmBan.tm_year % 100, tmBan.tm_mon + 1, tmBan.tm_mday, tmBan.tm_hour, tmBan.tm_min,
                                                      banFields[2].GetCString(), banFields[3].GetCString());
                         }
                         else
{
                             time_t timeUnban = time_t(banFields[1].GetUInt32());
                             tm tmUnban;
                             localtime_r(&timeUnban, &tmUnban);
                             handler->PSendSysMessage("|%-15.15s|%02d-%02d-%02d %02d:%02d|%02d-%02d-%02d %02d:%02d|%-15.15s|%-15.15s|",
                                                      char_name.c_str(), tmBan.tm_year % 100, tmBan.tm_mon + 1, tmBan.tm_mday, tmBan.tm_hour, tmBan.tm_min,
                                                      tmUnban.tm_year % 100, tmUnban.tm_mon + 1, tmUnban.tm_mday, tmUnban.tm_hour, tmUnban.tm_min,
                                                      banFields[2].GetCString(), banFields[3].GetCString());
                         }
                     } while (banInfo->NextRow());
                 }
             } while (result->NextRow());
             handler->SendSysMessage(" =============================================================================== ");
         }
         return true;
     }
References CHAR_SEL_BANINFO_LIST, CHAR_SEL_BANNED_NAME, CHAR_SEL_GUID_BY_NAME_FILTER, CharacterDatabase, Field::GetCString(), ChatHandler::GetSession(), Field::GetString(), LANG_BANLIST_CHARACTERS, LANG_BANLIST_CHARACTERS_HEADER, LANG_BANLIST_MATCHINGCHARACTER, LANG_BANLIST_NOCHARACTER, localtime_r(), ChatHandler::PSendSysMessage(), ChatHandler::SendSysMessage(), PreparedStatementBase::setString(), and PreparedStatementBase::setUInt32().
HandleBanListHelper()
static bool ban_commandscript::HandleBanListHelper (PreparedQueryResult result, ChatHandler * handler) inline static
Definition at line 428 of file cs_ban.cpp.
     {
         handler->PSendSysMessage(LANG_BANLIST_MATCHINGACCOUNT);
         // Chat short output
         if (handler->GetSession())
         {
             do
             {
                 Field* fields = result->Fetch();
                 uint32 accountid = fields[0].GetUInt32();
                 QueryResult banResult = LoginDatabase.PQuery("SELECT account.username FROM account, account_banned WHERE account_banned.id='%u' AND account_banned.id=account.id", accountid);
                 if (banResult)
                 {
                     Field* fields2 = banResult->Fetch();
                     handler->PSendSysMessage("%s", fields2[0].GetCString());
                 }
             } while (result->NextRow());
         }
         // Console wide output
         else
         {
             handler->SendSysMessage(LANG_BANLIST_ACCOUNTS);
             handler->SendSysMessage(" ===============================================================================");
             handler->SendSysMessage(LANG_BANLIST_ACCOUNTS_HEADER);
             do
             {
                 handler->SendSysMessage("-------------------------------------------------------------------------------");
                 Field* fields = result->Fetch();
                 uint32 accountId = fields[0].GetUInt32();
                 std::string accountName;
                 // "account" case, name can be get in same query
                 if (result->GetFieldCount() > 1)
                     accountName = fields[1].GetString();
                 // "character" case, name need extract from another DB
                 else
                     AccountMgr::GetName(accountId, accountName);
                 // No SQL injection. id is uint32.
                 QueryResult banInfo = LoginDatabase.PQuery("SELECT bandate, unbandate, bannedby, banreason FROM account_banned WHERE id = %u ORDER BY unbandate", accountId);
                 if (banInfo)
                 {
                     Field* fields2 = banInfo->Fetch();
                     do
                     {
                         time_t timeBan = time_t(fields2[0].GetUInt32());
                         tm tmBan;
                         localtime_r(&timeBan, &tmBan);
                         if (fields2[0].GetUInt32() == fields2[1].GetUInt32())
{
                             handler->PSendSysMessage("|%-15.15s|%02d-%02d-%02d %02d:%02d|   permanent  |%-15.15s|%-15.15s|",
                                                      accountName.c_str(), tmBan.tm_year % 100, tmBan.tm_mon + 1, tmBan.tm_mday, tmBan.tm_hour, tmBan.tm_min,
                                                      fields2[2].GetCString(), fields2[3].GetCString());
                         }
                         else
{
                             time_t timeUnban = time_t(fields2[1].GetUInt32());
                             tm tmUnban;
                             localtime_r(&timeUnban, &tmUnban);
                             handler->PSendSysMessage("|%-15.15s|%02d-%02d-%02d %02d:%02d|%02d-%02d-%02d %02d:%02d|%-15.15s|%-15.15s|",
                                                      accountName.c_str(), tmBan.tm_year % 100, tmBan.tm_mon + 1, tmBan.tm_mday, tmBan.tm_hour, tmBan.tm_min,
                                                      tmUnban.tm_year % 100, tmUnban.tm_mon + 1, tmUnban.tm_mday, tmUnban.tm_hour, tmUnban.tm_min,
                                                      fields2[2].GetCString(), fields2[3].GetCString());
                         }
                     } while (banInfo->NextRow());
                 }
             } while (result->NextRow());
             handler->SendSysMessage(" ===============================================================================");
         }
         return true;
     }
References Field::GetCString(), AccountMgr::GetName(), ChatHandler::GetSession(), Field::GetString(), Field::GetUInt32(), LANG_BANLIST_ACCOUNTS, LANG_BANLIST_ACCOUNTS_HEADER, LANG_BANLIST_MATCHINGACCOUNT, localtime_r(), LoginDatabase, ChatHandler::PSendSysMessage(), and ChatHandler::SendSysMessage().
HandleBanListIPCommand()
static bool ban_commandscript::HandleBanListIPCommand (ChatHandler * handler, char const * args) inline static
Definition at line 593 of file cs_ban.cpp.
     {
         LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_DEL_EXPIRED_IP_BANS);
         LoginDatabase.Execute(stmt);
         char* filterStr = strtok((char*)args, " ");
         std::string filter = filterStr ? filterStr : "";
         LoginDatabase.EscapeString(filter);
         PreparedQueryResult result;
         if (filter.empty())
         {
             LoginDatabasePreparedStatement* stmt2 = LoginDatabase.GetPreparedStatement(LOGIN_SEL_IP_BANNED_ALL);
             result = LoginDatabase.Query(stmt2);
         }
         else
         {
             LoginDatabasePreparedStatement* stmt2 = LoginDatabase.GetPreparedStatement(LOGIN_SEL_IP_BANNED_BY_IP);
             stmt2->setString(0, filter);
             result = LoginDatabase.Query(stmt2);
         }
         if (!result)
         {
             handler->PSendSysMessage(LANG_BANLIST_NOIP);
             return true;
         }
         handler->PSendSysMessage(LANG_BANLIST_MATCHINGIP);
         // Chat short output
         if (handler->GetSession())
         {
             do
             {
                 Field* fields = result->Fetch();
                 handler->PSendSysMessage("%s", fields[0].GetCString());
             } while (result->NextRow());
         }
         // Console wide output
         else
         {
             handler->SendSysMessage(LANG_BANLIST_IPS);
             handler->SendSysMessage(" ===============================================================================");
             handler->SendSysMessage(LANG_BANLIST_IPS_HEADER);
             do
             {
                 handler->SendSysMessage("-------------------------------------------------------------------------------");
                 Field* fields = result->Fetch();
                 time_t timeBan = time_t(fields[1].GetUInt32());
                 tm tmBan;
                 localtime_r(&timeBan, &tmBan);
                 if (fields[1].GetUInt32() == fields[2].GetUInt32())
                 {
                     handler->PSendSysMessage("|%-15.15s|%02d-%02d-%02d %02d:%02d|   permanent  |%-15.15s|%-15.15s|",
                                              fields[0].GetCString(), tmBan.tm_year % 100, tmBan.tm_mon + 1, tmBan.tm_mday, tmBan.tm_hour, tmBan.tm_min,
                                              fields[3].GetCString(), fields[4].GetCString());
                 }
                 else
                 {
                     time_t timeUnban = time_t(fields[2].GetUInt32());
                     tm tmUnban;
                     localtime_r(&timeUnban, &tmUnban);
                     handler->PSendSysMessage("|%-15.15s|%02d-%02d-%02d %02d:%02d|%02d-%02d-%02d %02d:%02d|%-15.15s|%-15.15s|",
                                              fields[0].GetCString(), tmBan.tm_year % 100, tmBan.tm_mon + 1, tmBan.tm_mday, tmBan.tm_hour, tmBan.tm_min,
                                              tmUnban.tm_year % 100, tmUnban.tm_mon + 1, tmUnban.tm_mday, tmUnban.tm_hour, tmUnban.tm_min,
                                              fields[3].GetCString(), fields[4].GetCString());
                 }
             } while (result->NextRow());
             handler->SendSysMessage(" ===============================================================================");
         }
         return true;
     }
References Field::GetCString(), ChatHandler::GetSession(), LANG_BANLIST_IPS, LANG_BANLIST_IPS_HEADER, LANG_BANLIST_MATCHINGIP, LANG_BANLIST_NOIP, localtime_r(), LOGIN_DEL_EXPIRED_IP_BANS, LOGIN_SEL_IP_BANNED_ALL, LOGIN_SEL_IP_BANNED_BY_IP, LoginDatabase, ChatHandler::PSendSysMessage(), ChatHandler::SendSysMessage(), and PreparedStatementBase::setString().
HandleUnBanAccountByCharCommand()
static bool ban_commandscript::HandleUnBanAccountByCharCommand (ChatHandler * handler, char const * args) inline static
Definition at line 702 of file cs_ban.cpp.
     {
         return HandleUnBanHelper(BAN_CHARACTER, args, handler);
     }
References BAN_CHARACTER.
HandleUnBanAccountCommand()
static bool ban_commandscript::HandleUnBanAccountCommand (ChatHandler * handler, char const * args) inline static
Definition at line 669 of file cs_ban.cpp.
     {
         return HandleUnBanHelper(BAN_ACCOUNT, args, handler);
     }
References BAN_ACCOUNT.
HandleUnBanCharacterCommand()
static bool ban_commandscript::HandleUnBanCharacterCommand (ChatHandler * handler, char const * args) inline static
Definition at line 674 of file cs_ban.cpp.
     {
         if (!*args)
             return false;
         char* nameStr = strtok((char*)args, " ");
         if (!nameStr)
             return false;
         std::string CharacterName = nameStr;
         if (!normalizePlayerName(CharacterName))
         {
             handler->SendSysMessage(LANG_PLAYER_NOT_FOUND);
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (!sBan->RemoveBanCharacter(CharacterName))
         {
             handler->SendSysMessage(LANG_PLAYER_NOT_FOUND);
             handler->SetSentErrorMessage(true);
             return false;
         }
         return true;
     }
References LANG_PLAYER_NOT_FOUND, normalizePlayerName(), sBan, ChatHandler::SendSysMessage(), and ChatHandler::SetSentErrorMessage().
HandleUnBanHelper()
static bool ban_commandscript::HandleUnBanHelper (BanMode mode, char const * args, ChatHandler * handler) inline static
Definition at line 712 of file cs_ban.cpp.
     {
         if (!*args)
             return false;
         char* nameOrIPStr = strtok((char*)args, " ");
         if (!nameOrIPStr)
             return false;
         std::string nameOrIP = nameOrIPStr;
         switch (mode)
         {
             case BAN_ACCOUNT:
                 if (!Utf8ToUpperOnlyLatin(nameOrIP))
                 {
                     handler->PSendSysMessage(LANG_ACCOUNT_NOT_EXIST, nameOrIP.c_str());
                     handler->SetSentErrorMessage(true);
                     return false;
                 }
                 break;
             case BAN_CHARACTER:
                 if (!normalizePlayerName(nameOrIP))
                 {
                     handler->SendSysMessage(LANG_PLAYER_NOT_FOUND);
                     handler->SetSentErrorMessage(true);
                     return false;
                 }
                 break;
             case BAN_IP:
                 if (!IsIPAddress(nameOrIP.c_str()))
                     return false;
                 break;
         }
         switch (mode)
         {
             case BAN_ACCOUNT:
                 if (sBan->RemoveBanAccount(nameOrIP))
                     handler->PSendSysMessage(LANG_UNBAN_UNBANNED, nameOrIP.c_str());
                 else
                     handler->PSendSysMessage(LANG_UNBAN_ERROR, nameOrIP.c_str());
                 break;
             case BAN_CHARACTER:
                 if (sBan->RemoveBanAccountByPlayerName(nameOrIP))
                     handler->PSendSysMessage(LANG_UNBAN_UNBANNED, nameOrIP.c_str());
                 else
                     handler->PSendSysMessage(LANG_UNBAN_ERROR, nameOrIP.c_str());
                 break;
             case BAN_IP:
                 if (sBan->RemoveBanIP(nameOrIP))
                     handler->PSendSysMessage(LANG_UNBAN_UNBANNED, nameOrIP.c_str());
                 else
                     handler->PSendSysMessage(LANG_UNBAN_ERROR, nameOrIP.c_str());
                 break;
             default:
                 break;
         }
         return true;
     }
References BAN_ACCOUNT, BAN_CHARACTER, BAN_IP, IsIPAddress(), LANG_ACCOUNT_NOT_EXIST, LANG_PLAYER_NOT_FOUND, LANG_UNBAN_ERROR, LANG_UNBAN_UNBANNED, normalizePlayerName(), ChatHandler::PSendSysMessage(), sBan, ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), and Utf8ToUpperOnlyLatin().
HandleUnBanIPCommand()
static bool ban_commandscript::HandleUnBanIPCommand (ChatHandler * handler, char const * args) inline static
Definition at line 707 of file cs_ban.cpp.
     {
         return HandleUnBanHelper(BAN_IP, args, handler);
     }
References BAN_IP.
The documentation for this class was generated from the following file:
src/server/scripts/Commands/cs_ban.cpp