Azerotcore-wotlk: deps/mysqllite/mysys/mf_radix.c File Reference
mf_radix.c File Reference
#include "mysys_priv.h"
#include <m_string.h>
Functions
void radixsort_for_str_ptr (uchar **base, uint number_of_elements, size_t size_of_element, uchar **buffer)
Function Documentation
radixsort_for_str_ptr()
void radixsort_for_str_ptr (uchar ** base, uint number_of_elements, size_t size_of_element, uchar ** buffer)
Definition at line 28 of file mf_radix.c.
 {
   uchar **end,**ptr,**buffer_ptr;
   uint32 *count_ptr,*count_end,count[256];
   int pass;
   end=base+number_of_elements; count_end=count+256;
   for (pass=(int) size_of_element-1 ; pass >= 0 ; pass--)
   {
     bzero((uchar*) count,sizeof(uint32)*256);
     for (ptr= base ; ptr < end ; ptr++)
       count[ptr[0][pass]]++;
     if (count[0] == number_of_elements)
       goto next;
     for (count_ptr=count+1 ; count_ptr < count_end ; count_ptr++)
     {
       if (*count_ptr == number_of_elements)
     goto next;
       (*count_ptr)+= *(count_ptr-1);
     }
     for (ptr= end ; ptr-- != base ;)
       buffer[--count[ptr[0][pass]]]= *ptr;
     for (ptr=base, buffer_ptr=buffer ; ptr < end ;)
       (*ptr++) = *buffer_ptr++;
   next:;
   }
 }
References bzero, count(), next(), and ptr().