Azerotcore-wotlk: src/server/authserver/CMakeLists.txt File Reference
src/server/authserver/CMakeLists.txt File Reference
Functions
CollectSourceFiles (${CMAKE_CURRENT_SOURCE_DIR} PRIVATE_SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/PrecompiledHeaders) if(WIN32) list(APPEND PRIVATE_SOURCES $
if (MSVC) list(APPEND PRIVATE_SOURCES authserver.rc) endif() endif() if(USE_COREPCH) set(PRIVATE_PCH_HEADER PrecompiledHeaders/authPCH.h) endif() GroupSources($
add_executable (authserver ${PRIVATE_SOURCES}) add_dependencies(authserver revision.h) target_link_libraries(authserver PRIVATE acore-core-interface PUBLIC shared) CollectIncludeDirectories($
Function Documentation
add_executable()
add_executable (authserver ${PRIVATE_SOURCES})
Definition at line 35 of file CMakeLists.txt.
    {PRIVATE_SOURCES})
 add_dependencies(authserver revision.h)
 target_link_libraries(authserver
   PRIVATE
     acore-core-interface
   PUBLIC
     shared)
 CollectIncludeDirectories(
   ${CMAKE_CURRENT_SOURCE_DIR}
CollectSourceFiles()
CollectSourceFiles (${CMAKE_CURRENT_SOURCE_DIR} PRIVATE_SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/)
Definition at line 15 of file CMakeLists.txt.
    {CMAKE_CURRENT_SOURCE_DIR}
   PRIVATE_SOURCES
   # Exclude
   ${CMAKE_CURRENT_SOURCE_DIR}/PrecompiledHeaders)
 if( WIN32 )
   list(APPEND PRIVATE_SOURCES ${winDebugging})
if()
if (MSVC)
Definition at line 23 of file CMakeLists.txt.
               {CMAKE_CURRENT_SOURCE_DIR})
Referenced by Unit::CalculateMeleeDamage(), Player::CastItemCombatSpell(), ConvertADT(), CasterAI::EnterCombat(), Unit::ExecuteDelayedUnitRelocationEvent(), spell_shazzrah_gate_dummy::spell_shazzrah_gate_dummy_SpellScript::FilterTargets(), Map::GetFullTerrainStatusForPosition(), WheatyExceptionReport::GetLogicalAddress(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveRootAck(), WorldSession::HandleMoveUnRootAck(), CasterAI::InitializeAI(), SmartAIMgr::IsEventValid(), SpellMgr::LoadDbcDataCorrections(), SpellMgr::LoadPetDefaultSpells(), SpellMgr::LoadSpellCustomAttr(), SmartScript::ProcessEvent(), lfg::LFGMgr::RBPacketAppendPlayer(), Unit::SpellDamageBonusTaken(), Unit::SpellHealingBonusTaken(), and World::UpdateGlobalPlayerMails().