Azerotcore-wotlk: NonTankLKTargetSelector Struct Reference
NonTankLKTargetSelector Struct Reference
Public Member Functions
NonTankLKTargetSelector (Creature *source, bool playerOnly=true, bool reqLOS=false, float maxDist=0.0f, uint32 exclude1=0, uint32 exclude2=0)
bool operator() (Unit const *target) const
Private Attributes
Creature const * _source
bool _playerOnly
bool _reqLOS
float _maxDist
uint32 _exclude1
uint32 _exclude2
Additional Inherited Members
Public Types inherited from Acore::unary_function< Unit *, bool >
typedef Unit * argument_type
typedef bool result_type
Detailed Description
Definition at line 399 of file boss_the_lich_king.cpp.
Constructor & Destructor Documentation
NonTankLKTargetSelector()
NonTankLKTargetSelector::NonTankLKTargetSelector (Creature * source, bool playerOnly = true, bool reqLOS = false, float maxDist = 0.0f, uint32 exclude1 = 0, uint32 exclude2 = 0) inline
Definition at line 402 of file boss_the_lich_king.cpp.
 : _source(source), _playerOnly(playerOnly), _reqLOS(reqLOS), _maxDist(maxDist), _exclude1(exclude1), _exclude2(exclude2) { }
Member Function Documentation
operator()()
bool NonTankLKTargetSelector::operator() (Unit const * target) const inline
Definition at line 403 of file boss_the_lich_king.cpp.
     {
         if (!target)
             return false;
         if (!target->IsAlive())
             return false;
         if (_playerOnly && target->GetTypeId() != TYPEID_PLAYER)
             return false;
         if (target == _source->GetVictim())
             return false;
         if (target->HasAura(SPELL_BOSS_HITTIN_YA_AURA))
             return false;
         if (_maxDist && _source->GetExactDist(target) > _maxDist)
             return false;
         if ((_exclude1 && target->HasAura(_exclude1)) || (_exclude2 && target->HasAura(_exclude2)))
             return false;
         if (_reqLOS && !_source->IsWithinLOSInMap(target))
             return false;
         return true;
     }
References _exclude1, _exclude2, _maxDist, _playerOnly, _reqLOS, _source, Position::GetExactDist(), Object::GetTypeId(), Unit::GetVictim(), Unit::HasAura(), Unit::IsAlive(), WorldObject::IsWithinLOSInMap(), SPELL_BOSS_HITTIN_YA_AURA, and TYPEID_PLAYER.
Member Data Documentation
_exclude1
uint32 NonTankLKTargetSelector::_exclude1 private
Definition at line 429 of file boss_the_lich_king.cpp.
Referenced by operator()().
_exclude2
uint32 NonTankLKTargetSelector::_exclude2 private
Definition at line 430 of file boss_the_lich_king.cpp.
Referenced by operator()().
_maxDist
float NonTankLKTargetSelector::_maxDist private
Definition at line 428 of file boss_the_lich_king.cpp.
Referenced by operator()().
_playerOnly
bool NonTankLKTargetSelector::_playerOnly private
Definition at line 426 of file boss_the_lich_king.cpp.
Referenced by operator()().
_reqLOS
bool NonTankLKTargetSelector::_reqLOS private
Definition at line 427 of file boss_the_lich_king.cpp.
Referenced by operator()().
_source
Creature const* NonTankLKTargetSelector::_source private
Definition at line 425 of file boss_the_lich_king.cpp.
Referenced by mpq::Archive::__repr__(), and operator()().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp