Azerotcore-wotlk: Acore::Impl::ChatCommands::CommandInvoker Struct Reference
Acore::Impl::ChatCommands::CommandInvoker Struct Reference
#include <ChatCommand.h>
Public Member Functions
CommandInvoker ()
template<typename TypedHandler >
CommandInvoker (TypedHandler &handler)
CommandInvoker (bool(&handler)(ChatHandler *, char const *))
operator bool () const
bool operator() (ChatHandler *chatHandler, std::string_view args) const
Private Types
using wrapper_func = bool(void *, ChatHandler *, std::string_view)
Private Attributes
wrapper_func * _wrapper
void * _handler
Detailed Description
Definition at line 121 of file ChatCommand.h.
Member Typedef Documentation
wrapper_func
using Acore::Impl::ChatCommands::CommandInvoker::wrapper_func = bool(void*, ChatHandler*, std::string_view) private
Definition at line 165 of file ChatCommand.h.
Constructor & Destructor Documentation
CommandInvoker() [1/3]
Acore::Impl::ChatCommands::CommandInvoker::CommandInvoker () inline
Definition at line 123 of file ChatCommand.h.
 : _wrapper(nullptr), _handler(nullptr) {}
CommandInvoker() [2/3]
template<typename TypedHandler > Acore::Impl::ChatCommands::CommandInvoker::CommandInvoker (TypedHandler & handler) inline
Definition at line 125 of file ChatCommand.h.
         {
             _wrapper = [](void* handler, ChatHandler* chatHandler, std::string_view argsStr)
             {
                 using Tuple = TupleType<TypedHandler>;
                 Tuple arguments;
                 std::get<0>(arguments) = chatHandler;
                 ChatCommandResult result = ConsumeFromOffset<Tuple, 1>(arguments, chatHandler, argsStr);
                 if (result)
                     return std::apply(reinterpret_cast<TypedHandler*>(handler), std::move(arguments));
                 else
                 {
                     if (result.HasErrorMessage())
                         SendErrorMessageToHandler(chatHandler, result.GetErrorMessage());
                     return false;
                 }
             };
             _handler = reinterpret_cast<void*>(handler);
         }
References _handler, _wrapper, ByteConverter::apply(), Acore::Impl::ChatCommands::ChatCommandResult::GetErrorMessage(), Acore::Impl::ChatCommands::ChatCommandResult::HasErrorMessage(), and Acore::Impl::ChatCommands::SendErrorMessageToHandler().
CommandInvoker() [3/3]
Acore::Impl::ChatCommands::CommandInvoker::CommandInvoker (bool(&)(ChatHandler *, char const *) handler) inline
Definition at line 145 of file ChatCommand.h.
         {
             _wrapper = [](void* handler, ChatHandler* chatHandler, std::string_view argsStr)
             {
                 // make a copy of the argument string
                 // legacy handlers can destroy input strings with strtok
                 std::string argsStrCopy(argsStr);
                 return reinterpret_cast<bool(*)(ChatHandler*, char const*)>(handler)(chatHandler, argsStrCopy.c_str());
             };
             _handler = reinterpret_cast<void*>(handler);
         }
References _handler, and _wrapper.
Member Function Documentation
operator bool()
Acore::Impl::ChatCommands::CommandInvoker::operator bool () const inline explicit
Definition at line 157 of file ChatCommand.h.
 { return (_wrapper != nullptr); }
References _wrapper.
operator()()
bool Acore::Impl::ChatCommands::CommandInvoker::operator() (ChatHandler * chatHandler, std::string_view args) const inline
Definition at line 158 of file ChatCommand.h.
         {
             ASSERT(_wrapper && _handler);
             return _wrapper(_handler, chatHandler, args);
         }
References _handler, _wrapper, and ASSERT.
Member Data Documentation
_handler
void* Acore::Impl::ChatCommands::CommandInvoker::_handler private
Definition at line 167 of file ChatCommand.h.
Referenced by CommandInvoker(), and operator()().
_wrapper
wrapper_func* Acore::Impl::ChatCommands::CommandInvoker::_wrapper private
Definition at line 166 of file ChatCommand.h.
Referenced by CommandInvoker(), operator bool(), and operator()().
The documentation for this struct was generated from the following file:
src/server/game/Chat/ChatCommands/ChatCommand.h