Azerotcore-wotlk: npc_twilight_volunteer::npc_twilight_volunteerAI Struct Reference
npc_twilight_volunteer::npc_twilight_volunteerAI Struct Reference
Public Member Functions
npc_twilight_volunteerAI (Creature *pCreature)
void DoAction (int32 action) override
void EnterEvadeMode () override
void AttackStart (Unit *who) override
void MovementInform (uint32 type, uint32 id) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
InstanceScript * pInstance
EventMap events
bool isSacraficeTarget
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 584 of file boss_jedoga_shadowseeker.cpp.
Constructor & Destructor Documentation
npc_twilight_volunteerAI()
npc_twilight_volunteer::npc_twilight_volunteerAI::npc_twilight_volunteerAI (Creature * pCreature) inline
Definition at line 586 of file boss_jedoga_shadowseeker.cpp.
                                                       : ScriptedAI(pCreature),
             pInstance(pCreature->GetInstanceScript()),
             isSacraficeTarget(false)
         {
         }
Member Function Documentation
AttackStart()
void npc_twilight_volunteer::npc_twilight_volunteerAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 620 of file boss_jedoga_shadowseeker.cpp.
         {
             if (!isSacraficeTarget)
             {
                 ScriptedAI::AttackStart(who);
             }
         }
References ScriptedAI::AttackStart(), and isSacraficeTarget.
DoAction()
void npc_twilight_volunteer::npc_twilight_volunteerAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 592 of file boss_jedoga_shadowseeker.cpp.
         {
             if (action == ACTION_RITUAL_BEGIN)
             {
                 isSacraficeTarget = true;
                 me->SetRegeneratingHealth(false);
                 me->GetMotionMaster()->Clear();
                 me->GetMotionMaster()->MoveIdle();
                 DoCastSelf(SPELL_ACTIVATE_INITIATE, true);
                 me->RemoveAurasDueToSpell(SPELL_WHITE_SPHERE);
                 me->SetControlled(false, UNIT_STATE_STUNNED);
                 me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_IMMUNE_TO_NPC | UNIT_FLAG_IMMUNE_TO_PC);
                 Talk(SAY_CHOSEN);
                 me->SetStandState(UNIT_STAND_STATE_STAND);
                 events.ScheduleEvent(EVENT_RITUAL_BEGIN_MOVE, 1500);
             }
         }
References ACTION_RITUAL_BEGIN, MotionMaster::Clear(), UnitAI::DoCastSelf(), EVENT_RITUAL_BEGIN_MOVE, Unit::GetMotionMaster(), isSacraficeTarget, ScriptedAI::me, MotionMaster::MoveIdle(), Unit::RemoveAurasDueToSpell(), Object::RemoveFlag(), SAY_CHOSEN, Unit::SetControlled(), Creature::SetRegeneratingHealth(), Unit::SetStandState(), SPELL_ACTIVATE_INITIATE, SPELL_WHITE_SPHERE, CreatureAI::Talk(), UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, UNIT_STAND_STATE_STAND, and UNIT_STATE_STUNNED.
EnterEvadeMode()
void npc_twilight_volunteer::npc_twilight_volunteerAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 612 of file boss_jedoga_shadowseeker.cpp.
         {
             if (!isSacraficeTarget)
             {
                 ScriptedAI::EnterEvadeMode();
             }
         }
References CreatureAI::EnterEvadeMode(), and isSacraficeTarget.
MovementInform()
void npc_twilight_volunteer::npc_twilight_volunteerAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 628 of file boss_jedoga_shadowseeker.cpp.
         {
             if (type != POINT_MOTION_TYPE)
             {
                 return;
             }
             if (id == POINT_INITIAL)
             {
                 me->SetFacingTo(me->GetAngle(&JedogaPosition[0]));
                 me->SendMovementFlagUpdate();
                 DoCastSelf(SPELL_WHITE_SPHERE, false);
                 me->SetControlled(true, UNIT_STATE_STUNNED);
                 me->SetStandState(UNIT_STAND_STATE_KNEEL);
             }
             else if (id == POINT_RITUAL)
             {
                 if (Creature* jedoga = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(DATA_JEDOGA_SHADOWSEEKER)))
                 {
                     jedoga->AI()->Talk(SAY_SACRIFICE_2);
                     jedoga->CastSpell(nullptr, SPELL_SACRIFICE_BEAM);
                     if (Creature* ritualTrigger = jedoga->SummonCreature(NPC_JEDOGA_CONTROLLER, JedogaPosition[2], TEMPSUMMON_TIMED_DESPAWN, 5000))
                     {
                         ritualTrigger->CastSpell(ritualTrigger, SPELL_SACRIFICE_VISUAL);
                     }
                 }
                 Talk(SAY_SACRIFICED);
                 me->SetStandState(UNIT_STAND_STATE_KNEEL);
             }
         }
References DATA_JEDOGA_SHADOWSEEKER, UnitAI::DoCastSelf(), Position::GetAngle(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), JedogaPosition, ScriptedAI::me, NPC_JEDOGA_CONTROLLER, pInstance, POINT_INITIAL, POINT_MOTION_TYPE, POINT_RITUAL, SAY_SACRIFICE_2, SAY_SACRIFICED, Unit::SendMovementFlagUpdate(), Unit::SetControlled(), Unit::SetFacingTo(), Unit::SetStandState(), SPELL_SACRIFICE_BEAM, SPELL_SACRIFICE_VISUAL, SPELL_WHITE_SPHERE, WorldObject::SummonCreature(), CreatureAI::Talk(), TEMPSUMMON_TIMED_DESPAWN, UNIT_STAND_STATE_KNEEL, and UNIT_STATE_STUNNED.
UpdateAI()
void npc_twilight_volunteer::npc_twilight_volunteerAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 661 of file boss_jedoga_shadowseeker.cpp.
         {
             if (!events.Empty())
             {
                 events.Update(diff);
                 if (events.ExecuteEvent() == EVENT_RITUAL_BEGIN_MOVE)
                 {
                     me->GetMotionMaster()->Clear();
                     me->SetHomePosition(JedogaPosition[2]);
                     me->SetWalk(true);
                     me->GetMotionMaster()->MovePoint(POINT_RITUAL, JedogaPosition[2], false);
                 }
             }
             if (!isSacraficeTarget && UpdateVictim())
             {
                 DoMeleeAttackIfReady();
             }
         }
References MotionMaster::Clear(), UnitAI::DoMeleeAttackIfReady(), EVENT_RITUAL_BEGIN_MOVE, Unit::GetMotionMaster(), isSacraficeTarget, JedogaPosition, ScriptedAI::me, MotionMaster::MovePoint(), POINT_RITUAL, Creature::SetHomePosition(), Creature::SetWalk(), and CreatureAI::UpdateVictim().
Member Data Documentation
events
EventMap npc_twilight_volunteer::npc_twilight_volunteerAI::events private
Definition at line 683 of file boss_jedoga_shadowseeker.cpp.
isSacraficeTarget
bool npc_twilight_volunteer::npc_twilight_volunteerAI::isSacraficeTarget private
Definition at line 684 of file boss_jedoga_shadowseeker.cpp.
Referenced by AttackStart(), DoAction(), EnterEvadeMode(), and UpdateAI().
pInstance
InstanceScript* npc_twilight_volunteer::npc_twilight_volunteerAI::pInstance private
Definition at line 682 of file boss_jedoga_shadowseeker.cpp.
Referenced by MovementInform().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/AzjolNerub/ahnkahet/boss_jedoga_shadowseeker.cpp