Azerotcore-wotlk: WorldModelHandler Class Reference
WorldModelHandler Class Reference
#include <WorldModelHandler.h>
Public Member Functions
WorldModelHandler (ADT *adt)
~WorldModelHandler ()
bool IsSane ()
Public Member Functions inherited from ObjectDataHandler
ObjectDataHandler (ADT *_adt)
void ProcessMapChunk (MapChunk *chunk)
Static Public Member Functions
static void InsertModelGeometry (std::vector< Vector3 > &verts, std::vector< Triangle< uint32 >> &tris, const WorldModelDefinition &def, WorldModelRoot *root, bool translate=true)
Public Attributes
std::vector< Vector3 > Vertices
std::vector< Triangle< uint32 > > Triangles
Public Attributes inherited from ObjectDataHandler
ADT * Source
Protected Member Functions
void ProcessInternal (MapChunk *data)
Private Member Functions
void ReadDefinitions ()
void ReadModelPaths ()
Private Attributes
std::set< uint32 > _drawn
std::vector< WorldModelDefinition > * _definitions
std::vector< std::string > * _paths
Detailed Description
Definition at line 45 of file WorldModelHandler.h.
Constructor & Destructor Documentation
WorldModelHandler()
WorldModelHandler::WorldModelHandler (ADT * adt)
Definition at line 48 of file WorldModelHandler.cpp.
                                                : ObjectDataHandler(adt), _definitions(nullptr), _paths(nullptr)
 {
     ReadModelPaths();
     ReadDefinitions();
 }
References ReadDefinitions(), and ReadModelPaths().
~WorldModelHandler()
WorldModelHandler::~WorldModelHandler ()
Definition at line 230 of file WorldModelHandler.cpp.
 {
     delete _definitions;
     delete _paths;
 }
References _definitions, and _paths.
Member Function Documentation
InsertModelGeometry()
void WorldModelHandler::InsertModelGeometry (std::vector< Vector3 > & verts, std::vector< Triangle< uint32 >> & tris, const WorldModelDefinition & def, WorldModelRoot * root, bool translate = true) static
Definition at line 98 of file WorldModelHandler.cpp.
 {
     for (std::vector<WorldModelGroup>::iterator group =  root->Groups.begin(); group != root->Groups.end(); ++group)
     {
         uint32 vertOffset = verts.size();
         for (std::vector<Vector3>::iterator itr2 = group->Vertices.begin(); itr2 != group->Vertices.end(); ++itr2)
         {
             Vector3 v = Utils::TransformDoodadVertex(def, *itr2, translate);
             // If translate is false, then we were called directly from the TileBuilder to add data to it's _Geometry member, hence, we have to manually convert the vertices to Recast format.
             verts.push_back(translate ? v : Utils::ToRecast(v)); // Transform the vertex to world space
         }
         for (uint32 i = 0; i < group->Triangles.size(); ++i)
         {
             // only include colliding tris
             if ((group->TriangleFlags[i] & 0x04) != 0 && group->TriangleMaterials[i] != 0xFF)
                 continue;
             Triangle<uint16> tri = group->Triangles[i];
             tris.push_back(Triangle<uint32>(Constants::TRIANGLE_TYPE_WMO, tri.V0 + vertOffset, tri.V1 + vertOffset, tri.V2 + vertOffset));
         }
     }
     if (def.DoodadSet < root->DoodadSets.size())
     {
         DoodadSet set = root->DoodadSets[def.DoodadSet];
         std::vector<DoodadInstance> instances;
         instances.reserve(set.CountInstances);
         for (uint32 i = set.FirstInstanceIndex; i < (set.CountInstances + set.FirstInstanceIndex); i++)
         {
             if (i >= root->DoodadInstances.size())
                 break;
             instances.push_back(root->DoodadInstances[i]);
         }
         for (std::vector<DoodadInstance>::iterator instance = instances.begin(); instance != instances.end(); ++instance)
         {
             Model* model = Cache->ModelCache.Get(instance->File);
             if (!model)
             {
                 model = new Model(instance->File);
                 Cache->ModelCache.Insert(instance->File, model);
             }
             if (!model->IsCollidable)
                 continue;
             int vertOffset = verts.size();
             for (std::vector<Vector3>::iterator itr2 = model->Vertices.begin(); itr2 != model->Vertices.end(); ++itr2)
             {
                 Vector3 v = Utils::TransformDoodadVertex(def, Utils::TransformWmoDoodad(*instance, def, *itr2, false), translate);
                 verts.push_back(translate ? v : Utils::ToRecast(v));
             }
             for (std::vector<Triangle<uint16>>::iterator itr2 = model->Triangles.begin(); itr2 != model->Triangles.end(); ++itr2)
                 tris.push_back(Triangle<uint32>(Constants::TRIANGLE_TYPE_WMO, itr2->V0 + vertOffset, itr2->V1 + vertOffset, itr2->V2 + vertOffset));
         }
         for (std::vector<WorldModelGroup>::iterator group =  root->Groups.begin(); group != root->Groups.end(); ++group)
         {
             if (!group->HasLiquidData)
                 continue;
             const LiquidHeader& liquidHeader = group->LiquidDataHeader;
             LiquidData& liquidDataGeometry = group->LiquidDataGeometry;
             for (uint32 y = 0; y < liquidHeader.Height; y++)
             {
                 for (uint32 x = 0; x < liquidHeader.Width; x++)
                 {
                     if (!liquidDataGeometry.ShouldRender(x, y))
                         continue;
                     uint32 vertOffset = verts.size();
                     Vector3 v1 = Utils::GetLiquidVert(def, liquidHeader.BaseLocation,
                                                       liquidDataGeometry.HeightMap[x][y], x, y, translate);
                     Vector3 v2 = Utils::GetLiquidVert(def, liquidHeader.BaseLocation,
                                                       liquidDataGeometry.HeightMap[x + 1][y], x + 1, y, translate);
                     Vector3 v3 = Utils::GetLiquidVert(def, liquidHeader.BaseLocation,
                                                       liquidDataGeometry.HeightMap[x][y + 1], x, y + 1, translate);
                     Vector3 v4 = Utils::GetLiquidVert(def, liquidHeader.BaseLocation,
                                                       liquidDataGeometry.HeightMap[x + 1][y + 1], x + 1, y + 1, translate);
                     verts.push_back(translate ? v1 : Utils::ToRecast(v1));
                     verts.push_back(translate ? v2 : Utils::ToRecast(v2));
                     verts.push_back(translate ? v3 : Utils::ToRecast(v3));
                     verts.push_back(translate ? v4 : Utils::ToRecast(v4));
                     tris.push_back(Triangle<uint32>(Constants::TRIANGLE_TYPE_WATER, vertOffset, vertOffset + 2, vertOffset + 1));
                     tris.push_back(Triangle<uint32>(Constants::TRIANGLE_TYPE_WATER, vertOffset + 2, vertOffset + 3, vertOffset + 1));
                 }
             }
         }
     }
 }
References LiquidHeader::BaseLocation, Cache, WorldModelRoot::DoodadInstances, WorldModelDefinition::DoodadSet, WorldModelRoot::DoodadSets, GenericCache< K, T >::Get(), Utils::GetLiquidVert(), WorldModelRoot::Groups, LiquidHeader::Height, LiquidData::HeightMap, GenericCache< K, T >::Insert(), Model::IsCollidable, CacheClass::ModelCache, set(), LiquidData::ShouldRender(), Utils::ToRecast(), Utils::TransformDoodadVertex(), Utils::TransformWmoDoodad(), Constants::TRIANGLE_TYPE_WATER, Constants::TRIANGLE_TYPE_WMO, Model::Triangles, Triangle< T >::V0, Triangle< T >::V1, Triangle< T >::V2, Model::Vertices, and LiquidHeader::Width.
Referenced by TileBuilder::AddGeometry(), and ProcessInternal().
IsSane()
bool WorldModelHandler::IsSane () inline
Definition at line 53 of file WorldModelHandler.h.
 { return _definitions && _paths; }
References _definitions, and _paths.
Referenced by ProcessInternal().
ProcessInternal()
void WorldModelHandler::ProcessInternal (MapChunk * data) protected virtual
Implements ObjectDataHandler.
Definition at line 54 of file WorldModelHandler.cpp.
 {
     if (!IsSane())
         return;
     uint32 refCount = mcnk->Header.MapObjectRefs;
     FILE* stream = mcnk->Source->GetStream();
     fseek(stream, mcnk->Source->Offset + mcnk->Header.OffsetMCRF, SEEK_SET);
     // Start looping at the last Doodad Ref index
     for (uint32 i = mcnk->Header.DoodadRefs; i < refCount; i++)
     {
         int32 index;
         if (fread(&index, sizeof(int32), 1, stream) != 1)
             printf("WorldModelDefinition::Read: Error reading data, expected 1, read 0\n");
         if (index < 0 || uint32(index) >= _definitions->size())
             continue;
         WorldModelDefinition wmo = (*_definitions)[index];
         if (_drawn.find(wmo.UniqueId) != _drawn.end())
             continue;
         _drawn.insert(wmo.UniqueId);
         if (wmo.MwidIndex >= _paths->size())
             continue;
         std::string path = (*_paths)[wmo.MwidIndex];
         WorldModelRoot* model = Cache->WorldModelCache.Get(path);
         if (!model)
         {
             model = new WorldModelRoot(path);
             Cache->WorldModelCache.Insert(path, model);
         }
         Vertices.reserve(1000);
         Triangles.reserve(1000);
         InsertModelGeometry(Vertices, Triangles, wmo, model);
     }
     // Restore the stream position
     fseek(stream, mcnk->Source->Offset, SEEK_SET);
 }
References _definitions, _drawn, _paths, Cache, MapChunkHeader::DoodadRefs, GenericCache< K, T >::Get(), Chunk::GetStream(), MapChunk::Header, GenericCache< K, T >::Insert(), InsertModelGeometry(), IsSane(), MapChunkHeader::MapObjectRefs, WorldModelDefinition::MwidIndex, Chunk::Offset, MapChunkHeader::OffsetMCRF, MapChunk::Source, Triangles, WorldModelDefinition::UniqueId, Vertices, and CacheClass::WorldModelCache.
ReadDefinitions()
void WorldModelHandler::ReadDefinitions () private
Definition at line 192 of file WorldModelHandler.cpp.
 {
     Chunk* chunk = Source->ObjectData->GetChunkByName("MODF");
     if (!chunk)
         return;
     const int32 definitionSize = 64;
     uint32 definitionCount = chunk->Length / definitionSize;
     _definitions = new std::vector<WorldModelDefinition>;
     _definitions->reserve(definitionCount);
     FILE* stream = chunk->GetStream();
     for (uint32 i = 0; i < definitionCount; i++)
         _definitions->push_back(WorldModelDefinition::Read(stream));
 }
References _definitions, ChunkedData::GetChunkByName(), ADT::ObjectData, WorldModelDefinition::Read(), and ObjectDataHandler::Source.
Referenced by WorldModelHandler().
ReadModelPaths()
void WorldModelHandler::ReadModelPaths () private
Definition at line 207 of file WorldModelHandler.cpp.
 {
     Chunk* mwid = Source->ObjectData->GetChunkByName("MWID");
     Chunk* mwmo = Source->ObjectData->GetChunkByName("MWMO");
     if (!mwid || !mwmo)
         return;
     uint32 paths = mwid->Length / 4;
     _paths = new std::vector<std::string>;
     _paths->reserve(paths);
     for (uint32 i = 0; i < paths; i++)
     {
         FILE* stream = mwid->GetStream();
         fseek(stream, i * 4, SEEK_CUR);
         uint32 offset;
         if (fread(&offset, sizeof(uint32), 1, stream) != 1)
             printf("WorldModelDefinition::Read: Error reading data, expected 1, read 0\n");
         FILE* dataStream = mwmo->GetStream();
         fseek(dataStream, offset + mwmo->Offset, SEEK_SET);
         _paths->push_back(Utils::ReadString(dataStream));
     }
 }
References _paths, ChunkedData::GetChunkByName(), Chunk::GetStream(), Chunk::Length, ADT::ObjectData, Chunk::Offset, Utils::ReadString(), and ObjectDataHandler::Source.
Referenced by WorldModelHandler().
Member Data Documentation
_definitions
std::vector<WorldModelDefinition>* WorldModelHandler::_definitions private
Definition at line 61 of file WorldModelHandler.h.
Referenced by IsSane(), ProcessInternal(), ReadDefinitions(), and ~WorldModelHandler().
_drawn
std::set<uint32> WorldModelHandler::_drawn private
Definition at line 60 of file WorldModelHandler.h.
Referenced by ProcessInternal().
_paths
std::vector<std::string>* WorldModelHandler::_paths private
Definition at line 62 of file WorldModelHandler.h.
Referenced by IsSane(), ProcessInternal(), ReadModelPaths(), and ~WorldModelHandler().
Triangles
std::vector<Triangle<uint32> > WorldModelHandler::Triangles
Definition at line 52 of file WorldModelHandler.h.
Referenced by Geometry::AddAdt(), and ProcessInternal().
Vertices
std::vector<Vector3> WorldModelHandler::Vertices
Definition at line 51 of file WorldModelHandler.h.
Referenced by Geometry::AddAdt(), and ProcessInternal().
The documentation for this class was generated from the following files:
src/tools/mesh_extractor/WorldModelHandler.h
src/tools/mesh_extractor/WorldModelHandler.cpp