Azerotcore-wotlk: spell_pilgrims_bounty_feast_on_generic::spell_pilgrims_bounty_feast_on_generic_SpellScript Class Reference
spell_pilgrims_bounty_feast_on_generic::spell_pilgrims_bounty_feast_on_generic_SpellScript Class Reference
Private Member Functions
PrepareSpellScript (spell_pilgrims_bounty_feast_on_generic_SpellScript)
void HandleDummy (SpellEffIndex)
void Register () override
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Definition at line 474 of file pilgrims_bounty.cpp.
Member Function Documentation
HandleDummy()
void spell_pilgrims_bounty_feast_on_generic::spell_pilgrims_bounty_feast_on_generic_SpellScript::HandleDummy (SpellEffIndex) inline private
Definition at line 478 of file pilgrims_bounty.cpp.
         {
             Player* player = GetCaster()->GetCharmerOrOwnerPlayerOrPlayerItself();
             if (!player)
                 return;
             uint32 spellId = 0;
             switch (GetSpellInfo()->Id)
             {
                 case SPELL_FEAST_ON_TURKEY:
                     spellId = SPELL_PLAYER_TURKEY;
                     break;
                 case SPELL_FEAST_ON_STUFFING:
                     spellId = SPELL_PLAYER_STUFFING;
                     break;
                 case SPELL_FEAST_ON_PIE:
                     spellId = SPELL_PLAYER_PIE;
                     break;
                 case SPELL_FEAST_ON_CRANBERRY:
                     spellId = SPELL_PLAYER_CRANBERRY;
                     break;
                 case SPELL_FEAST_ON_SWEET_POTATOES:
                     spellId = SPELL_PLAYER_SWEET_POTATOES;
                     break;
             }
             if (spellId)
             {
                 player->CastSpell(player, spellId, true);
                 if (AuraEffect* aur = player->GetAuraEffectDummy(spellId))
                 {
                     if (aur->GetBase()->GetStackAmount() >= 5)
                     {
                         switch (spellId)
{
                             case SPELL_PLAYER_TURKEY:
                                 player->CastSpell(player, SPELL_WELL_FED_TURKEY, true);
                                 break;
                             case SPELL_PLAYER_STUFFING:
                                 player->CastSpell(player, SPELL_WELL_FED_STUFFING, true);
                                 break;
                             case SPELL_PLAYER_PIE:
                                 player->CastSpell(player, SPELL_WELL_FED_PIE, true);
                                 break;
                             case SPELL_PLAYER_CRANBERRY:
                                 player->CastSpell(player, SPELL_WELL_FED_CRANBERRY, true);
                                 break;
                             case SPELL_PLAYER_SWEET_POTATOES:
                                 player->CastSpell(player, SPELL_WELL_FED_SWEET_POTATOES, true);
                                 break;
                         }
                         uint8 count = 0;
                         Unit::AuraEffectList const& dummyAuras = player->GetAuraEffectsByType(SPELL_AURA_DUMMY);
                         for (Unit::AuraEffectList::const_iterator i = dummyAuras.begin(); i != dummyAuras.end(); ++i)
{
                             if ((*i)->GetId() >= SPELL_PLAYER_CRANBERRY && (*i)->GetId() <= SPELL_PLAYER_PIE)
                                 if ((*i)->GetBase()->GetStackAmount() >= 5)
                                     ++count;
                         }
                         // Cast spirit of sharing
                         if (count >= 5)
                             player->CastSpell(player, SPELL_SPIRIT_OF_SHARING, true);
                     }
                 }
             }
         }
References Unit::CastSpell(), count(), Unit::GetAuraEffectDummy(), Unit::GetAuraEffectsByType(), SpellScript::GetCaster(), Unit::GetCharmerOrOwnerPlayerOrPlayerItself(), SpellScript::GetSpellInfo(), SPELL_AURA_DUMMY, SPELL_FEAST_ON_CRANBERRY, SPELL_FEAST_ON_PIE, SPELL_FEAST_ON_STUFFING, SPELL_FEAST_ON_SWEET_POTATOES, SPELL_FEAST_ON_TURKEY, SPELL_PLAYER_CRANBERRY, SPELL_PLAYER_PIE, SPELL_PLAYER_STUFFING, SPELL_PLAYER_SWEET_POTATOES, SPELL_PLAYER_TURKEY, SPELL_SPIRIT_OF_SHARING, SPELL_WELL_FED_CRANBERRY, SPELL_WELL_FED_PIE, SPELL_WELL_FED_STUFFING, SPELL_WELL_FED_SWEET_POTATOES, and SPELL_WELL_FED_TURKEY.
Referenced by Register().
PrepareSpellScript()
spell_pilgrims_bounty_feast_on_generic::spell_pilgrims_bounty_feast_on_generic_SpellScript::PrepareSpellScript (spell_pilgrims_bounty_feast_on_generic_SpellScript) private
Register()
void spell_pilgrims_bounty_feast_on_generic::spell_pilgrims_bounty_feast_on_generic_SpellScript::Register () inline override private virtual
Implements _SpellScript.
Definition at line 547 of file pilgrims_bounty.cpp.
         {
             OnEffectHitTarget += SpellEffectFn(spell_pilgrims_bounty_feast_on_generic_SpellScript::HandleDummy, EFFECT_0, SPELL_EFFECT_DUMMY);
         }
References EFFECT_0, HandleDummy(), SpellScript::OnEffectHitTarget, SPELL_EFFECT_DUMMY, and SpellEffectFn.
The documentation for this class was generated from the following file:
src/server/scripts/Events/pilgrims_bounty.cpp