Azerotcore-wotlk: AsyncCallbackProcessor< T > Class Template Reference
AsyncCallbackProcessor< T > Class Template Reference
#include <AsyncCallbackProcessor.h>
Public Member Functions
AsyncCallbackProcessor ()=default
~AsyncCallbackProcessor ()=default
T & AddCallback (T &&query)
void ProcessReadyCallbacks ()
Private Member Functions
AsyncCallbackProcessor (AsyncCallbackProcessor const &)=delete
AsyncCallbackProcessor & operator= (AsyncCallbackProcessor const &)=delete
Private Attributes
std::vector< T > _callbacks
Detailed Description
template<typename T>
class AsyncCallbackProcessor< T >
Definition at line 29 of file AsyncCallbackProcessor.h.
Constructor & Destructor Documentation
AsyncCallbackProcessor() [1/2]
template<typename T > AsyncCallbackProcessor< T >::AsyncCallbackProcessor () default
~AsyncCallbackProcessor()
template<typename T > AsyncCallbackProcessor< T >::~AsyncCallbackProcessor () default
AsyncCallbackProcessor() [2/2]
template<typename T > AsyncCallbackProcessor< T >::AsyncCallbackProcessor (AsyncCallbackProcessor< T > const &) private delete
Member Function Documentation
AddCallback()
template<typename T > T& AsyncCallbackProcessor< T >::AddCallback (T && query) inline
Definition at line 35 of file AsyncCallbackProcessor.h.
     {
         _callbacks.emplace_back(std::move(query));
         return _callbacks.back();
     }
References AsyncCallbackProcessor< T >::_callbacks.
Referenced by Player::ActivateSpec(), WorldSession::AddQueryHolderCallback(), WorldSession::AddTransactionCallback(), WorldSocket::HandleAuthSession(), WorldSession::HandleCharCreateOpcode(), WorldSession::HandleCharCustomize(), WorldSession::HandleCharEnumOpcode(), WorldSession::HandleCharFactionOrRaceChange(), WorldSession::HandleCharRenameOpcode(), AuthSession::HandleLogonChallenge(), WorldSession::HandleOpenItemOpcode(), AuthSession::HandleRealmList(), AuthSession::HandleReconnectChallenge(), WorldSession::HandleStablePet(), WorldSession::HandleStableSwapPet(), WorldSession::HandleUnstablePet(), Pet::LoadPetFromDB(), WorldSession::SendStablePet(), AuthSession::Start(), WorldSocket::Start(), and World::UpdateRealmCharCount().
operator=()
template<typename T > AsyncCallbackProcessor& AsyncCallbackProcessor< T >::operator= (AsyncCallbackProcessor< T > const &) private delete
ProcessReadyCallbacks()
template<typename T > void AsyncCallbackProcessor< T >::ProcessReadyCallbacks () inline
Definition at line 41 of file AsyncCallbackProcessor.h.
     {
         if (_callbacks.empty())
             return;
         std::vector<T> updateCallbacks{ std::move(_callbacks) };
         updateCallbacks.erase(std::remove_if(updateCallbacks.begin(), updateCallbacks.end(), [](T& callback)
         {
             return callback.InvokeIfReady();
         }), updateCallbacks.end());
         _callbacks.insert(_callbacks.end(), std::make_move_iterator(updateCallbacks.begin()), std::make_move_iterator(updateCallbacks.end()));
     }
References AsyncCallbackProcessor< T >::_callbacks.
Referenced by WorldSession::ProcessQueryCallbacks(), World::ProcessQueryCallbacks(), AuthSession::Update(), and WorldSocket::Update().
Member Data Documentation
_callbacks
template<typename T > std::vector<T> AsyncCallbackProcessor< T >::_callbacks private
Definition at line 60 of file AsyncCallbackProcessor.h.
Referenced by AsyncCallbackProcessor< T >::AddCallback(), and AsyncCallbackProcessor< T >::ProcessReadyCallbacks().
The documentation for this class was generated from the following file:
src/common/Utilities/AsyncCallbackProcessor.h