Azerotcore-wotlk: formatter< std::tm, Char > Struct Template Reference
formatter< std::tm, Char > Struct Template Reference
#include <chrono.h>
Public Member Functions
template<typename ParseContext >
FMT_CONSTEXPR auto parse (ParseContext &ctx) -> decltype(ctx.begin())
template<typename FormatContext >
auto format (const std::tm &tm, FormatContext &ctx) const -> decltype(ctx.out())
Public Attributes
basic_string_view< Char > specs
Detailed Description
template<typename Char>
struct formatter< std::tm, Char >
Definition at line 511 of file chrono.h.
Member Function Documentation
format()
template<typename Char > template<typename FormatContext > auto formatter< std::tm, Char >::format (const std::tm & tm, FormatContext & ctx) const -> decltype(ctx.out()) inline
Definition at line 523 of file chrono.h.
{
     basic_memory_buffer<Char> tm_format;
     tm_format.append(specs.begin(), specs.end());
     // By appending an extra space we can distinguish an empty result that
     // indicates insufficient buffer size from a guaranteed non-empty result
     // https://github.com/fmtlib/fmt/issues/2238
     tm_format.push_back(' ');
     tm_format.push_back('\0');
     basic_memory_buffer<Char> buf;
     size_t start = buf.size();
     for (;;) {
       size_t size = buf.capacity() - start;
       size_t count = detail::strftime(&buf[start], size, &tm_format[0], &tm);
       if (count != 0) {
         buf.resize(start + count);
         break;
       }
       const size_t MIN_GROWTH = 10;
       buf.reserve(buf.capacity() + (size > MIN_GROWTH ? size : MIN_GROWTH));
     }
     // Remove the extra space.
     return std::copy(buf.begin(), buf.end() - 1, ctx.out());
   }
References basic_memory_buffer< T, SIZE, Allocator >::append(), detail::copy(), count(), basic_memory_buffer< T, SIZE, Allocator >::reserve(), basic_memory_buffer< T, SIZE, Allocator >::resize(), and strftime().
parse()
template<typename Char > template<typename ParseContext > FMT_CONSTEXPR auto formatter< std::tm, Char >::parse (ParseContext & ctx) -> decltype(ctx.begin()) inline
Definition at line 513 of file chrono.h.
{
     auto it = ctx.begin();
     if (it != ctx.end() && *it == ':') ++it;
     auto end = it;
     while (end != ctx.end() && *end != '}') ++end;
     specs = {it, detail::to_unsigned(end - it)};
     return end;
   }
References to_unsigned().
Member Data Documentation
specs
template<typename Char > basic_string_view<Char> formatter< std::tm, Char >::specs
Definition at line 548 of file chrono.h.
The documentation for this struct was generated from the following file:
deps/fmt/include/fmt/chrono.h