Azerotcore-wotlk: instance_shadowfang_keep::instance_shadowfang_keep_InstanceMapScript Struct Reference
instance_shadowfang_keep::instance_shadowfang_keep_InstanceMapScript Struct Reference
Public Member Functions
instance_shadowfang_keep_InstanceMapScript (Map *map)
void Initialize () override
void OnGameObjectCreate (GameObject *gameobject) override
void SetData (uint32 type, uint32 data) override
std::string GetSaveData () override
void Load (const char *in) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void CreatureLooted (Creature *, LootType)
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void ProcessEvent (WorldObject *, uint32)
Private Attributes
uint32 _encounters [MAX_ENCOUNTERS]
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Definition at line 41 of file instance_shadowfang_keep.cpp.
Constructor & Destructor Documentation
instance_shadowfang_keep_InstanceMapScript()
instance_shadowfang_keep::instance_shadowfang_keep_InstanceMapScript::instance_shadowfang_keep_InstanceMapScript (Map * map) inline
Definition at line 43 of file instance_shadowfang_keep.cpp.
 : InstanceScript(map) { }
Member Function Documentation
GetSaveData()
std::string instance_shadowfang_keep::instance_shadowfang_keep_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
Definition at line 84 of file instance_shadowfang_keep.cpp.
         {
             std::ostringstream saveStream;
             saveStream << "S K " << _encounters[0] << ' ' << _encounters[1] << ' ' << _encounters[2];
             return saveStream.str();
         }
References _encounters.
Initialize()
void instance_shadowfang_keep::instance_shadowfang_keep_InstanceMapScript::Initialize (void) inline override virtual
Reimplemented from InstanceScript.
Definition at line 45 of file instance_shadowfang_keep.cpp.
         {
             memset(&_encounters, 0, sizeof(_encounters));
         }
References _encounters.
Load()
void instance_shadowfang_keep::instance_shadowfang_keep_InstanceMapScript::Load (const char * in) inline override virtual
Reimplemented from InstanceScript.
Definition at line 91 of file instance_shadowfang_keep.cpp.
         {
             if (!in)
                 return;
             char dataHead1, dataHead2;
             std::istringstream loadStream(in);
             loadStream >> dataHead1 >> dataHead2;
             if (dataHead1 == 'S' && dataHead2 == 'K')
             {
                 for (uint8 i = 0; i < MAX_ENCOUNTERS; ++i)
                 {
                     loadStream >> _encounters[i];
                     if (_encounters[i] == IN_PROGRESS)
                         _encounters[i] = NOT_STARTED;
                 }
             }
         }
References _encounters, IN_PROGRESS, MAX_ENCOUNTERS, and NOT_STARTED.
OnGameObjectCreate()
void instance_shadowfang_keep::instance_shadowfang_keep_InstanceMapScript::OnGameObjectCreate (GameObject * gameobject) inline override virtual
Reimplemented from InstanceScript.
Definition at line 50 of file instance_shadowfang_keep.cpp.
         {
             switch (gameobject->GetEntry())
             {
                 case GO_COURTYARD_DOOR:
                     if (_encounters[TYPE_COURTYARD] == DONE)
                         HandleGameObject(ObjectGuid::Empty, true, gameobject);
                     break;
                 case GO_SORCERER_DOOR:
                     if (_encounters[TYPE_FENRUS_THE_DEVOURER] == DONE)
                         HandleGameObject(ObjectGuid::Empty, true, gameobject);
                     break;
                 case GO_ARUGAL_DOOR:
                     if (_encounters[TYPE_WOLF_MASTER_NANDOS] == DONE)
                         HandleGameObject(ObjectGuid::Empty, true, gameobject);
                     break;
             }
         }
References _encounters, DONE, ObjectGuid::Empty, Object::GetEntry(), GO_ARUGAL_DOOR, GO_COURTYARD_DOOR, GO_SORCERER_DOOR, InstanceScript::HandleGameObject(), TYPE_COURTYARD, TYPE_FENRUS_THE_DEVOURER, and TYPE_WOLF_MASTER_NANDOS.
SetData()
void instance_shadowfang_keep::instance_shadowfang_keep_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
Definition at line 69 of file instance_shadowfang_keep.cpp.
         {
             switch (type)
             {
                 case TYPE_COURTYARD:
                 case TYPE_FENRUS_THE_DEVOURER:
                 case TYPE_WOLF_MASTER_NANDOS:
                     _encounters[type] = data;
                     break;
             }
             if (data == DONE)
                 SaveToDB();
         }
References _encounters, DONE, InstanceScript::SaveToDB(), TYPE_COURTYARD, TYPE_FENRUS_THE_DEVOURER, and TYPE_WOLF_MASTER_NANDOS.
Member Data Documentation
_encounters
uint32 instance_shadowfang_keep::instance_shadowfang_keep_InstanceMapScript::_encounters[MAX_ENCOUNTERS] private
Definition at line 111 of file instance_shadowfang_keep.cpp.
Referenced by GetSaveData(), Initialize(), Load(), OnGameObjectCreate(), and SetData().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/ShadowfangKeep/instance_shadowfang_keep.cpp