Azerotcore-wotlk: boss_cthun::cthunAI Struct Reference
boss_cthun::cthunAI Struct Reference
Public Member Functions
cthunAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *) override
void SpawnEyeTentacle (float x, float y)
Unit * SelectRandomNotStomach ()
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void DoAction (int32 param) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * instance
uint32 WisperTimer
uint32 PhaseTimer
ObjectGuid HoldPlayer
uint32 EyeTentacleTimer
uint8 FleshTentaclesKilled
uint32 GiantClawTentacleTimer
uint32 GiantEyeTentacleTimer
uint32 StomachAcidTimer
uint32 StomachEnterTimer
uint32 StomachEnterVisTimer
ObjectGuid StomachEnterTarget
std::unordered_map< ObjectGuid, bool > Stomach_Map
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 464 of file boss_cthun.cpp.
Constructor & Destructor Documentation
cthunAI()
boss_cthun::cthunAI::cthunAI (Creature * creature) inline
Definition at line 466 of file boss_cthun.cpp.
                                     : ScriptedAI(creature)
         {
             SetCombatMovement(false);
             instance = creature->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), instance, and ScriptedAI::SetCombatMovement().
Member Function Documentation
DamageTaken()
void boss_cthun::cthunAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 868 of file boss_cthun.cpp.
         {
             switch (instance->GetData(DATA_CTHUN_PHASE))
             {
                 case PHASE_CTHUN_STOMACH:
                     //Not weakened so reduce damage by 99%
                     damage /= 100;
                     if (damage == 0)
                         damage = 1;
                     //Prevent death in non-weakened state
                     if (damage >= me->GetHealth())
                         damage = 0;
                     return;
                 case PHASE_CTHUN_WEAK:
                     //Weakened - takes normal damage
                     return;
                 default:
                     damage = 0;
                     break;
             }
         }
References DATA_CTHUN_PHASE, ZoneScript::GetData(), Unit::GetHealth(), instance, ScriptedAI::me, PHASE_CTHUN_STOMACH, and PHASE_CTHUN_WEAK.
DoAction()
void boss_cthun::cthunAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 894 of file boss_cthun.cpp.
         {
             switch (param)
             {
                 case ACTION_FLESH_TENTACLE_KILLED:
                     ++FleshTentaclesKilled;
                     break;
             }
         }
References ACTION_FLESH_TENTACLE_KILLED, and FleshTentaclesKilled.
EnterCombat()
void boss_cthun::cthunAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 531 of file boss_cthun.cpp.
         {
             DoZoneInCombat();
         }
References CreatureAI::DoZoneInCombat().
JustDied()
void boss_cthun::cthunAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 863 of file boss_cthun.cpp.
         {
             instance->SetData(DATA_CTHUN_PHASE, PHASE_CTHUN_DONE);
         }
References DATA_CTHUN_PHASE, instance, PHASE_CTHUN_DONE, and ZoneScript::SetData().
Reset()
void boss_cthun::cthunAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 499 of file boss_cthun.cpp.
         {
             //One random wisper every 90 - 300 seconds
             WisperTimer = 90000;
             //Phase information
             PhaseTimer = 10000;                                 //Emerge in 10 seconds
             //No hold player for transition
             HoldPlayer.Clear();
             //Body Phase
             EyeTentacleTimer = 30000;
             FleshTentaclesKilled = 0;
             GiantClawTentacleTimer = 15000;                     //15 seconds into body phase (1 min repeat)
             GiantEyeTentacleTimer = 45000;                      //15 seconds into body phase (1 min repeat)
             StomachAcidTimer = 4000;                            //Every 4 seconds
             StomachEnterTimer = 10000;                          //Every 10 seconds
             StomachEnterVisTimer = 0;                           //Always 3.5 seconds after Stomach Enter Timer
             StomachEnterTarget.Clear();                         //Target to be teleported to stomach
             //Clear players in stomach and outside
             Stomach_Map.clear();
             //Reset flags
             me->RemoveAurasDueToSpell(SPELL_TRANSFORM);
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
             me->SetVisible(false);
             instance->SetData(DATA_CTHUN_PHASE, PHASE_NOT_STARTED);
         }
References ObjectGuid::Clear(), DATA_CTHUN_PHASE, EyeTentacleTimer, FleshTentaclesKilled, GiantClawTentacleTimer, GiantEyeTentacleTimer, HoldPlayer, instance, ScriptedAI::me, PHASE_NOT_STARTED, PhaseTimer, Unit::RemoveAurasDueToSpell(), ZoneScript::SetData(), Object::SetFlag(), Unit::SetVisible(), SPELL_TRANSFORM, Stomach_Map, StomachAcidTimer, StomachEnterTarget, StomachEnterTimer, StomachEnterVisTimer, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, and WisperTimer.
SelectRandomNotStomach()
Unit* boss_cthun::cthunAI::SelectRandomNotStomach () inline
Definition at line 545 of file boss_cthun.cpp.
         {
             if (Stomach_Map.empty())
                 return nullptr;
             std::unordered_map<ObjectGuid, bool>::const_iterator i = Stomach_Map.begin();
             std::list<Unit*> temp;
             std::list<Unit*>::const_iterator j;
             //Get all players in map
             while (i != Stomach_Map.end())
             {
                 //Check for valid player
                 Unit* unit = ObjectAccessor::GetUnit(*me, i->first);
                 //Only units out of stomach
                 if (unit && !i->second)
                     temp.push_back(unit);
                 ++i;
             }
             if (temp.empty())
                 return nullptr;
             j = temp.begin();
             //Get random but only if we have more than one unit on threat list
             if (temp.size() > 1)
                 advance (j, rand() % (temp.size() - 1));
             return (*j);
         }
References ObjectAccessor::GetUnit(), ScriptedAI::me, and Stomach_Map.
Referenced by SpawnEyeTentacle(), and UpdateAI().
SpawnEyeTentacle()
void boss_cthun::cthunAI::SpawnEyeTentacle (float x, float y) inline
Definition at line 536 of file boss_cthun.cpp.
         {
             Creature* Spawned;
             Spawned = DoSpawnCreature(NPC_EYE_TENTACLE, x, y, 0, 0, TEMPSUMMON_CORPSE_DESPAWN, 500);
             if (Spawned && Spawned->AI())
                 if (Unit* target = SelectRandomNotStomach())
                     Spawned->AI()->AttackStart(target);
         }
References Creature::AI(), UnitAI::AttackStart(), ScriptedAI::DoSpawnCreature(), NPC_EYE_TENTACLE, SelectRandomNotStomach(), and TEMPSUMMON_CORPSE_DESPAWN.
Referenced by UpdateAI().
UpdateAI()
void boss_cthun::cthunAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 580 of file boss_cthun.cpp.
         {
             //Check if we have a target
             if (!UpdateVictim())
             {
                 //No target so we'll use this section to do our random wispers instance wide
                 //WisperTimer
                 if (WisperTimer <= diff)
                 {
                     Map* map = me->GetMap();
                     if (!map->IsDungeon())
                         return;
                     //Play random sound to the zone
                     Map::PlayerList const& PlayerList = map->GetPlayers();
                     if (!PlayerList.isEmpty())
                     {
                         for (Map::PlayerList::const_iterator itr = PlayerList.begin(); itr != PlayerList.end(); ++itr)
{
                             if (Player* pPlr = itr->GetSource())
                                 pPlr->PlayDirectSound(RANDOM_SOUND_WHISPER, pPlr);
                         }
                     }
                     //One random wisper every 90 - 300 seconds
                     WisperTimer = urand(90000, 300000);
                 }
                 else WisperTimer -= diff;
                 return;
             }
             me->SetTarget();
             uint32 currentPhase = instance->GetData(DATA_CTHUN_PHASE);
             if (currentPhase == PHASE_CTHUN_STOMACH || currentPhase == PHASE_CTHUN_WEAK)
             {
                 // EyeTentacleTimer
                 if (EyeTentacleTimer <= diff)
                 {
                     //Spawn the 8 Eye Tentacles in the corret spots
                     SpawnEyeTentacle(0, 20);                //south
                     SpawnEyeTentacle(10, 10);               //south west
                     SpawnEyeTentacle(20, 0);                //west
                     SpawnEyeTentacle(10, -10);              //north west
                     SpawnEyeTentacle(0, -20);               //north
                     SpawnEyeTentacle(-10, -10);             //north east
                     SpawnEyeTentacle(-20, 0);               // east
                     SpawnEyeTentacle(-10, 10);              // south east
                     EyeTentacleTimer = 30000; // every 30sec in phase 2
                 }
                 else EyeTentacleTimer -= diff;
             }
             switch (currentPhase)
             {
                 //Transition phase
                 case PHASE_CTHUN_TRANSITION:
                     //PhaseTimer
                     if (PhaseTimer <= diff)
                     {
                         //Switch
                         instance->SetData(DATA_CTHUN_PHASE, PHASE_CTHUN_STOMACH);
                         //Switch to c'thun model
                         me->InterruptNonMeleeSpells(false);
                         DoCast(me, SPELL_TRANSFORM, false);
                         me->SetFullHealth();
                         me->SetVisible(true);
                         me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
                         //Emerging phase
                         //AttackStart(ObjectAccessor::GetUnit(*me, HoldpPlayer));
                         DoZoneInCombat();
                         //Place all units in threat list on outside of stomach
                         Stomach_Map.clear();
                         for (std::list<HostileReference*>::const_iterator i = me->getThreatMgr().getThreatList().begin(); i != me->getThreatMgr().getThreatList().end(); ++i)
                             Stomach_Map[(*i)->getUnitGuid()] = false;   //Outside stomach
                         //Spawn 2 flesh tentacles
                         FleshTentaclesKilled = 0;
                         //Spawn flesh tentacle
                         for (uint8 i = 0; i < 2; i++)
{
                             Creature* spawned = me->SummonCreature(NPC_FLESH_TENTACLE, FleshTentaclePos[i], TEMPSUMMON_CORPSE_DESPAWN);
                             if (!spawned)
                                 ++FleshTentaclesKilled;
                         }
                         PhaseTimer = 0;
                     }
                     else PhaseTimer -= diff;
                     break;
                 //Body Phase
                 case PHASE_CTHUN_STOMACH:
                     //Remove Target field
                     me->SetTarget();
                     //Weaken
                     if (FleshTentaclesKilled > 1)
                     {
                         instance->SetData(DATA_CTHUN_PHASE, PHASE_CTHUN_WEAK);
                         Talk(EMOTE_WEAKENED);
                         PhaseTimer = 45000;
                         DoCast(me, SPELL_PURPLE_COLORATION, true);
                         std::unordered_map<ObjectGuid, bool>::iterator i = Stomach_Map.begin();
                         //Kick all players out of stomach
                         while (i != Stomach_Map.end())
{
                             //Check for valid player
                             Unit* unit = ObjectAccessor::GetUnit(*me, i->first);
                             //Only move units in stomach
                             if (unit && i->second)
{
                                 //Teleport each player out
                                 DoTeleportPlayer(unit, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ() + 10, float(rand() % 6));
                                 //Cast knockback on them
                                 DoCast(unit, SPELL_EXIT_STOMACH_KNOCKBACK, true);
                                 //Remove the acid debuff
                                 unit->RemoveAurasDueToSpell(SPELL_DIGESTIVE_ACID);
                                 i->second = false;
                             }
                             ++i;
                         }
                         return;
                     }
                     //Stomach acid
                     if (StomachAcidTimer <= diff)
                     {
                         //Apply aura to all players in stomach
                         std::unordered_map<ObjectGuid, bool>::iterator i = Stomach_Map.begin();
                         while (i != Stomach_Map.end())
{
                             //Check for valid player
                             Unit* unit = ObjectAccessor::GetUnit(*me, i->first);
                             //Only apply to units in stomach
                             if (unit && i->second)
{
                                 //Cast digestive acid on them
                                 DoCast(unit, SPELL_DIGESTIVE_ACID, true);
                                 //Check if player should be kicked from stomach
                                 if (unit->IsWithinDist3d(&KickPos, 15.0f))
{
                                     //Teleport each player out
                                     DoTeleportPlayer(unit, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ() + 10, float(rand() % 6));
                                     //Cast knockback on them
                                     DoCast(unit, SPELL_EXIT_STOMACH_KNOCKBACK, true);
                                     //Remove the acid debuff
                                     unit->RemoveAurasDueToSpell(SPELL_DIGESTIVE_ACID);
                                     i->second = false;
                                 }
                             }
                             ++i;
                         }
                         StomachAcidTimer = 4000;
                     }
                     else StomachAcidTimer -= diff;
                     //Stomach Enter Timer
                     if (StomachEnterTimer <= diff)
                     {
                         if (Unit* target = SelectRandomNotStomach())
{
                             //Set target in stomach
                             Stomach_Map[target->GetGUID()] = true;
                             target->InterruptNonMeleeSpells(false);
                             target->CastSpell(target, SPELL_MOUTH_TENTACLE, true, nullptr, nullptr, me->GetGUID());
                             StomachEnterTarget = target->GetGUID();
                             StomachEnterVisTimer = 3800;
                         }
                         StomachEnterTimer = 13800;
                     }
                     else StomachEnterTimer -= diff;
                     if (StomachEnterVisTimer && StomachEnterTarget)
                     {
                         if (StomachEnterVisTimer <= diff)
{
                             //Check for valid player
                             Unit* unit = ObjectAccessor::GetUnit(*me, StomachEnterTarget);
                             if (unit)
{
                                 DoTeleportPlayer(unit, STOMACH_X, STOMACH_Y, STOMACH_Z, STOMACH_O);
                             }
                             StomachEnterTarget.Clear();
                             StomachEnterVisTimer = 0;
                         }
                         else StomachEnterVisTimer -= diff;
                     }
                     //GientClawTentacleTimer
                     if (GiantClawTentacleTimer <= diff)
                     {
                         if (Unit* target = SelectRandomNotStomach())
{
                             //Spawn claw tentacle on the random target
                             if (Creature* spawned = me->SummonCreature(NPC_GIANT_CLAW_TENTACLE, *target, TEMPSUMMON_CORPSE_DESPAWN, 500))
                                 if (spawned->AI())
                                     spawned->AI()->AttackStart(target);
                         }
                         //One giant claw tentacle every minute
                         GiantClawTentacleTimer = 60000;
                     }
                     else GiantClawTentacleTimer -= diff;
                     //GiantEyeTentacleTimer
                     if (GiantEyeTentacleTimer <= diff)
                     {
                         if (Unit* target = SelectRandomNotStomach())
{
                             //Spawn claw tentacle on the random target
                             if (Creature* spawned = me->SummonCreature(NPC_GIANT_EYE_TENTACLE, *target, TEMPSUMMON_CORPSE_DESPAWN, 500))
                                 if (spawned->AI())
                                     spawned->AI()->AttackStart(target);
                         }
                         //One giant eye tentacle every minute
                         GiantEyeTentacleTimer = 60000;
                     }
                     else GiantEyeTentacleTimer -= diff;
                     break;
                 //Weakened state
                 case PHASE_CTHUN_WEAK:
                     //PhaseTimer
                     if (PhaseTimer <= diff)
                     {
                         //Switch
                         instance->SetData(DATA_CTHUN_PHASE, PHASE_CTHUN_STOMACH);
                         //Remove purple coloration
                         me->RemoveAurasDueToSpell(SPELL_PURPLE_COLORATION);
                         //Spawn 2 flesh tentacles
                         FleshTentaclesKilled = 0;
                         //Spawn flesh tentacle
                         for (uint8 i = 0; i < 2; i++)
{
                             Creature* spawned = me->SummonCreature(NPC_FLESH_TENTACLE, FleshTentaclePos[i], TEMPSUMMON_CORPSE_DESPAWN);
                             if (!spawned)
                                 ++FleshTentaclesKilled;
                         }
                         PhaseTimer = 0;
                     }
                     else PhaseTimer -= diff;
                     break;
             }
         }
References MapRefMgr::begin(), ObjectGuid::Clear(), DATA_CTHUN_PHASE, UnitAI::DoCast(), ScriptedAI::DoTeleportPlayer(), CreatureAI::DoZoneInCombat(), EMOTE_WEAKENED, MapRefMgr::end(), EyeTentacleTimer, FleshTentaclePos, FleshTentaclesKilled, ZoneScript::GetData(), Object::GetGUID(), WorldObject::GetMap(), Map::GetPlayers(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ThreatMgr::getThreatList(), Unit::getThreatMgr(), ObjectAccessor::GetUnit(), GiantClawTentacleTimer, GiantEyeTentacleTimer, instance, Unit::InterruptNonMeleeSpells(), Map::IsDungeon(), LinkedListHead::isEmpty(), WorldObject::IsWithinDist3d(), KickPos, ScriptedAI::me, NPC_FLESH_TENTACLE, NPC_GIANT_CLAW_TENTACLE, NPC_GIANT_EYE_TENTACLE, PHASE_CTHUN_STOMACH, PHASE_CTHUN_TRANSITION, PHASE_CTHUN_WEAK, PhaseTimer, RANDOM_SOUND_WHISPER, Unit::RemoveAurasDueToSpell(), Object::RemoveFlag(), SelectRandomNotStomach(), ZoneScript::SetData(), Unit::SetFullHealth(), Creature::SetTarget(), Unit::SetVisible(), SpawnEyeTentacle(), SPELL_DIGESTIVE_ACID, SPELL_EXIT_STOMACH_KNOCKBACK, SPELL_MOUTH_TENTACLE, SPELL_PURPLE_COLORATION, SPELL_TRANSFORM, Stomach_Map, STOMACH_O, STOMACH_X, STOMACH_Y, STOMACH_Z, StomachAcidTimer, StomachEnterTarget, StomachEnterTimer, StomachEnterVisTimer, WorldObject::SummonCreature(), CreatureAI::Talk(), TEMPSUMMON_CORPSE_DESPAWN, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, CreatureAI::UpdateVictim(), urand(), and WisperTimer.
Member Data Documentation
EyeTentacleTimer
uint32 boss_cthun::cthunAI::EyeTentacleTimer
Definition at line 487 of file boss_cthun.cpp.
Referenced by Reset(), and UpdateAI().
FleshTentaclesKilled
uint8 boss_cthun::cthunAI::FleshTentaclesKilled
Definition at line 488 of file boss_cthun.cpp.
Referenced by DoAction(), Reset(), and UpdateAI().
GiantClawTentacleTimer
uint32 boss_cthun::cthunAI::GiantClawTentacleTimer
Definition at line 489 of file boss_cthun.cpp.
Referenced by Reset(), and UpdateAI().
GiantEyeTentacleTimer
uint32 boss_cthun::cthunAI::GiantEyeTentacleTimer
Definition at line 490 of file boss_cthun.cpp.
Referenced by Reset(), and UpdateAI().
HoldPlayer
ObjectGuid boss_cthun::cthunAI::HoldPlayer
Definition at line 484 of file boss_cthun.cpp.
Referenced by Reset().
instance
InstanceScript* boss_cthun::cthunAI::instance
Definition at line 473 of file boss_cthun.cpp.
Referenced by cthunAI(), DamageTaken(), JustDied(), Reset(), and UpdateAI().
PhaseTimer
uint32 boss_cthun::cthunAI::PhaseTimer
Definition at line 479 of file boss_cthun.cpp.
Referenced by Reset(), and UpdateAI().
Stomach_Map
std::unordered_map<ObjectGuid, bool> boss_cthun::cthunAI::Stomach_Map
Definition at line 497 of file boss_cthun.cpp.
Referenced by Reset(), SelectRandomNotStomach(), and UpdateAI().
StomachAcidTimer
uint32 boss_cthun::cthunAI::StomachAcidTimer
Definition at line 491 of file boss_cthun.cpp.
Referenced by Reset(), and UpdateAI().
StomachEnterTarget
ObjectGuid boss_cthun::cthunAI::StomachEnterTarget
Definition at line 494 of file boss_cthun.cpp.
Referenced by Reset(), and UpdateAI().
StomachEnterTimer
uint32 boss_cthun::cthunAI::StomachEnterTimer
Definition at line 492 of file boss_cthun.cpp.
Referenced by Reset(), and UpdateAI().
StomachEnterVisTimer
uint32 boss_cthun::cthunAI::StomachEnterVisTimer
Definition at line 493 of file boss_cthun.cpp.
Referenced by Reset(), and UpdateAI().
WisperTimer
uint32 boss_cthun::cthunAI::WisperTimer
Definition at line 476 of file boss_cthun.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_cthun.cpp