Azerotcore-wotlk: AppenderDB Class Reference
AppenderDB Class Reference
#include <AppenderDB.h>
Public Member Functions
AppenderDB (uint8 id, std::string const &name, LogLevel level, AppenderFlags flags, std::vector< std::string_view > const &args)
~AppenderDB ()
void setRealmId (uint32 realmId) override
AppenderType getType () const override
Public Member Functions inherited from Appender
Appender (uint8 _id, std::string const &name, LogLevel level=LOG_LEVEL_DISABLED, AppenderFlags flags=APPENDER_FLAGS_NONE)
virtual ~Appender ()
uint8 getId () const
std::string const & getName () const
LogLevel getLogLevel () const
AppenderFlags getFlags () const
void setLogLevel (LogLevel)
void write (LogMessage *message)
Static Public Attributes
static constexpr AppenderType type = APPENDER_DB
Private Member Functions
void _write (LogMessage const *message) override
Private Attributes
uint32 realmId
bool enabled
Additional Inherited Members
Static Public Member Functions inherited from Appender
static char const * getLogLevelString (LogLevel level)
Detailed Description
Definition at line 23 of file AppenderDB.h.
Constructor & Destructor Documentation
AppenderDB()
AppenderDB::AppenderDB (uint8 id, std::string const & name, LogLevel level, AppenderFlags flags, std::vector< std::string_view > const & args)
Definition at line 23 of file AppenderDB.cpp.
     : Appender(id, name, level), realmId(0), enabled(false) { }
~AppenderDB()
AppenderDB::~AppenderDB ()
Definition at line 26 of file AppenderDB.cpp.
 { }
Member Function Documentation
_write()
void AppenderDB::_write (LogMessage const * message) override private virtual
Implements Appender.
Definition at line 28 of file AppenderDB.cpp.
 {
     // Avoid infinite loop, PExecute triggers Logging with "sql.sql" type
     if (!enabled || (message->type.find("sql") != std::string::npos))
         return;
     LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_INS_LOG);
     stmt->setUInt64(0, message->mtime);
     stmt->setUInt32(1, realmId);
     stmt->setString(2, message->type);
     stmt->setUInt8(3, uint8(message->level));
     stmt->setString(4, message->text);
     LoginDatabase.Execute(stmt);
 }
References enabled, LOGIN_INS_LOG, LoginDatabase, message(), realmId, PreparedStatementBase::setString(), PreparedStatementBase::setUInt32(), PreparedStatementBase::setUInt64(), and PreparedStatementBase::setUInt8().
getType()
AppenderType AppenderDB::getType () const inline override virtual
Implements Appender.
Definition at line 32 of file AppenderDB.h.
 { return type; }
References type.
setRealmId()
void AppenderDB::setRealmId (uint32 realmId) override virtual
Reimplemented from Appender.
Definition at line 43 of file AppenderDB.cpp.
 {
     enabled = true;
     realmId = _realmId;
 }
References enabled, and realmId.
Member Data Documentation
enabled
bool AppenderDB::enabled private
Definition at line 36 of file AppenderDB.h.
Referenced by _write(), and setRealmId().
realmId
uint32 AppenderDB::realmId private
Definition at line 35 of file AppenderDB.h.
Referenced by _write(), and setRealmId().
type
constexpr AppenderType AppenderDB::type = APPENDER_DB static constexpr
Definition at line 26 of file AppenderDB.h.
Referenced by getType().
The documentation for this class was generated from the following files:
src/server/database/Logging/AppenderDB.h
src/server/database/Logging/AppenderDB.cpp