Azerotcore-wotlk: AssistDelayEvent Class Reference
AssistDelayEvent Class Reference
#include <Creature.h>
Public Member Functions
AssistDelayEvent (ObjectGuid victim, Creature *owner)
bool Execute (uint64 e_time, uint32 p_time) override
void AddAssistant (ObjectGuid guid)
Public Member Functions inherited from BasicEvent
BasicEvent ()
virtual ~BasicEvent ()
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Member Functions
AssistDelayEvent ()
Private Attributes
ObjectGuid m_victim
GuidList m_assistants
Creature * m_owner
Detailed Description
Definition at line 469 of file Creature.h.
Constructor & Destructor Documentation
AssistDelayEvent() [1/2]
AssistDelayEvent::AssistDelayEvent (ObjectGuid victim, Creature * owner) inline
Definition at line 472 of file Creature.h.
 : BasicEvent(), m_victim(victim), m_owner(owner) { }
AssistDelayEvent() [2/2]
AssistDelayEvent::AssistDelayEvent () private
Member Function Documentation
AddAssistant()
void AssistDelayEvent::AddAssistant (ObjectGuid guid) inline
Definition at line 475 of file Creature.h.
 { m_assistants.push_back(guid); }
References m_assistants.
Referenced by Creature::CallAssistance().
Execute()
bool AssistDelayEvent::Execute (uint64 e_time, uint32 p_time) override virtual
Reimplemented from BasicEvent.
Definition at line 140 of file Creature.cpp.
 {
     if (Unit* victim = ObjectAccessor::GetUnit(*m_owner, m_victim))
     {
         // Initialize last damage timer if it doesn't exist
         m_owner->SetLastDamagedTime(sWorld->GetGameTime() + MAX_AGGRO_RESET_TIME);
         while (!m_assistants.empty())
         {
             Creature* assistant = ObjectAccessor::GetCreature(*m_owner, *m_assistants.begin());
             m_assistants.pop_front();
             if (assistant && assistant->CanAssistTo(m_owner, victim))
             {
                 assistant->SetNoCallAssistance(true);
                 assistant->CombatStart(victim);
                 if (assistant->IsAIEnabled)
                     assistant->AI()->AttackStart(victim);
                 assistant->SetLastDamagedTimePtr(m_owner->GetLastDamagedTimePtr());
             }
         }
     }
     return true;
 }
References Creature::AI(), UnitAI::AttackStart(), Creature::CanAssistTo(), Unit::CombatStart(), ObjectAccessor::GetCreature(), Creature::GetLastDamagedTimePtr(), ObjectAccessor::GetUnit(), Unit::IsAIEnabled, m_assistants, m_owner, m_victim, MAX_AGGRO_RESET_TIME, Creature::SetLastDamagedTime(), Creature::SetLastDamagedTimePtr(), Creature::SetNoCallAssistance(), and sWorld.
Member Data Documentation
m_assistants
GuidList AssistDelayEvent::m_assistants private
Definition at line 481 of file Creature.h.
Referenced by AddAssistant(), and Execute().
m_owner
Creature* AssistDelayEvent::m_owner private
Definition at line 482 of file Creature.h.
Referenced by Execute().
m_victim
ObjectGuid AssistDelayEvent::m_victim private
Definition at line 480 of file Creature.h.
Referenced by Execute().
The documentation for this class was generated from the following files:
src/server/game/Entities/Creature/Creature.h
src/server/game/Entities/Creature/Creature.cpp