Azerotcore-wotlk: src/server/game/Entities/Object/Object.cpp File Reference
Object.cpp File Reference
#include "Battlefield.h"
#include "BattlefieldMgr.h"
#include "CellImpl.h"
#include "Chat.h"
#include "Common.h"
#include "Creature.h"
#include "DynamicTree.h"
#include "DynamicVisibility.h"
#include "GameObjectAI.h"
#include "GridNotifiers.h"
#include "Log.h"
#include "MapMgr.h"
#include "MovementPacketBuilder.h"
#include "Object.h"
#include "ObjectAccessor.h"
#include "ObjectMgr.h"
#include "Opcodes.h"
#include "OutdoorPvPMgr.h"
#include "Physics.h"
#include "Player.h"
#include "ScriptMgr.h"
#include "SharedDefines.h"
#include "SpellAuraEffects.h"
#include "TargetedMovementGenerator.h"
#include "TemporarySummon.h"
#include "Totem.h"
#include "Transport.h"
#include "UpdateData.h"
#include "UpdateFieldFlags.h"
#include "UpdateMask.h"
#include "Util.h"
#include "Vehicle.h"
#include "World.h"
#include "WorldPacket.h"
#include "GridNotifiersImpl.h"
Classes
struct WorldObjectChangeAccumulator
Functions
ByteBuffer & operator>> (ByteBuffer &buf, Position::PositionXYZOStreamer const &streamer)
ByteBuffer & operator<< (ByteBuffer &buf, Position::PositionXYZStreamer const &streamer)
ByteBuffer & operator>> (ByteBuffer &buf, Position::PositionXYZStreamer const &streamer)
ByteBuffer & operator<< (ByteBuffer &buf, Position::PositionXYZOStreamer const &streamer)
Function Documentation
operator<<() [1/2]
ByteBuffer& operator<< (ByteBuffer & buf, Position::PositionXYZOStreamer const & streamer)
Definition at line 1056 of file Object.cpp.
 {
     float x, y, z, o;
     streamer.m_pos->GetPosition(x, y, z, o);
     buf << x << y << z << o;
     return buf;
 }
References Position::GetPosition(), and Position::PositionXYZOStreamer::m_pos.
operator<<() [2/2]
ByteBuffer& operator<< (ByteBuffer & buf, Position::PositionXYZStreamer const & streamer)
Definition at line 1040 of file Object.cpp.
 {
     float x, y, z;
     streamer.m_pos->GetPosition(x, y, z);
     buf << x << y << z;
     return buf;
 }
References Position::GetPosition(), and Position::PositionXYZStreamer::m_pos.
Referenced by ByteBuffer::operator<<().
operator>>() [1/2]
ByteBuffer& operator>> (ByteBuffer & buf, Position::PositionXYZOStreamer const & streamer)
Definition at line 1033 of file Object.cpp.
 {
     float x, y, z, o;
     buf >> x >> y >> z >> o;
     streamer.m_pos->Relocate(x, y, z, o);
     return buf;
 }
References Position::PositionXYZOStreamer::m_pos, and Position::Relocate().
operator>>() [2/2]
ByteBuffer& operator>> (ByteBuffer & buf, Position::PositionXYZStreamer const & streamer)
Definition at line 1048 of file Object.cpp.
 {
     float x, y, z;
     buf >> x >> y >> z;
     streamer.m_pos->Relocate(x, y, z);
     return buf;
 }
References Position::PositionXYZStreamer::m_pos, and Position::Relocate().