Azerotcore-wotlk: npc_akama_illidan::npc_akama_illidanAI Struct Reference
npc_akama_illidan::npc_akama_illidanAI Struct Reference
Public Member Functions
npc_akama_illidanAI (Creature *creature)
void DoAction (int32 param) override
void Reset () override
void sGossipSelect (Player *player, uint32, uint32) override
void JustSummoned (Creature *summon) override
void WaypointReached (uint32 pointId) override
void MoveInLineOfSight (Unit *) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void UpdateEscortAI (uint32 diff) override
Public Member Functions inherited from npc_escortAI
npc_escortAI (Creature *creature)
~npc_escortAI () override
void AttackStart (Unit *who) override
void JustDied (Unit *) override
void JustRespawned () override
void ReturnToLastPoint ()
void EnterEvadeMode () override
void UpdateAI (uint32 diff) override
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
virtual void WaypointStart (uint32)
void Start (bool isActiveAttacker=true, bool run=false, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetRun (bool on=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void KilledUnit (Unit *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
EventMap events
SummonList summons
InstanceScript * instance
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from npc_escortAI
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 764 of file boss_illidan.cpp.
Constructor & Destructor Documentation
npc_akama_illidanAI()
npc_akama_illidan::npc_akama_illidanAI::npc_akama_illidanAI (Creature * creature) inline
Definition at line 766 of file boss_illidan.cpp.
                                                 : npc_escortAI(creature), summons(me)
         {
             instance = creature->GetInstanceScript();
             if (instance->GetBossState(DATA_AKAMA_FINISHED) == DONE)
             {
                 me->GetMap()->LoadGrid(751.664f, 238.933f);
                 me->SetHomePosition(751.664f, 238.933f, 353.106f, 2.18f);
                 me->NearTeleportTo(751.664f, 238.933f, 353.106f, 2.18f);
             }
         }
References DATA_AKAMA_FINISHED, DONE, InstanceScript::GetBossState(), WorldObject::GetInstanceScript(), WorldObject::GetMap(), instance, Map::LoadGrid(), ScriptedAI::me, Unit::NearTeleportTo(), and Creature::SetHomePosition().
Member Function Documentation
DamageTaken()
void npc_akama_illidan::npc_akama_illidanAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 875 of file boss_illidan.cpp.
         {
             if (damage >= me->GetHealth())
                 damage = 0;
         }
References Unit::GetHealth(), and ScriptedAI::me.
DoAction()
void npc_akama_illidan::npc_akama_illidanAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 777 of file boss_illidan.cpp.
         {
             if (param == ACTION_FIGHT_MINIONS)
             {
                 me->CombatStop(true);
                 events.ScheduleEvent(EVENT_AKAMA_SUMMON_ILLIDARI, 8000);
                 events.ScheduleEvent(EVENT_AKAMA_SPELL_CHAIN, 7000);
                 events.ScheduleEvent(EVENT_AKAMA_HEALTH, 1000);
                 me->GetMotionMaster()->MoveCharge(741.97f, 358.74f, 353.0f, 10.0f, POINT_FIGHT_MINIONS);
                 Talk(SAY_AKAMA_LEAVE);
             }
             else if (param == ACTION_ILLIDAN_DEAD)
             {
                 events.Reset();
                 summons.DespawnAll();
                 me->CombatStop(true);
             }
         }
References ACTION_FIGHT_MINIONS, ACTION_ILLIDAN_DEAD, Unit::CombatStop(), SummonList::DespawnAll(), EVENT_AKAMA_HEALTH, EVENT_AKAMA_SPELL_CHAIN, EVENT_AKAMA_SUMMON_ILLIDARI, Unit::GetMotionMaster(), ScriptedAI::me, MotionMaster::MoveCharge(), POINT_FIGHT_MINIONS, SAY_AKAMA_LEAVE, summons, and CreatureAI::Talk().
JustSummoned()
void npc_akama_illidan::npc_akama_illidanAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 835 of file boss_illidan.cpp.
         {
             summons.Summon(summon);
             summon->SetUInt32Value(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_NONE);
             if (summon->GetEntry() == NPC_ILLIDARI_ELITE)
             {
                 me->AddThreat(summon, 1000000.0f);
                 summon->AddThreat(me, 1000000.0f);
                 summon->AI()->AttackStart(me);
                 AttackStart(summon);
             }
         }
References Unit::AddThreat(), Creature::AI(), UnitAI::AttackStart(), npc_escortAI::AttackStart(), Object::GetEntry(), ScriptedAI::me, NPC_ILLIDARI_ELITE, Object::SetUInt32Value(), SummonList::Summon(), summons, UNIT_NPC_FLAG_NONE, and UNIT_NPC_FLAGS.
MoveInLineOfSight()
void npc_akama_illidan::npc_akama_illidanAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 873 of file boss_illidan.cpp.
 { }
Reset()
void npc_akama_illidan::npc_akama_illidanAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 796 of file boss_illidan.cpp.
         {
             me->SetReactState(REACT_AGGRESSIVE);
             me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
             me->setActive(false);
             me->SetVisible(instance->GetBossState(DATA_ILLIDARI_COUNCIL) == DONE && instance->GetBossState(DATA_ILLIDAN_STORMRAGE) != DONE);
             events.Reset();
             summons.DespawnAll();
         }
References DATA_ILLIDAN_STORMRAGE, DATA_ILLIDARI_COUNCIL, SummonList::DespawnAll(), DONE, InstanceScript::GetBossState(), instance, ScriptedAI::me, REACT_AGGRESSIVE, WorldObject::setActive(), Object::SetFlag(), Creature::SetReactState(), Unit::SetVisible(), summons, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
sGossipSelect()
void npc_akama_illidan::npc_akama_illidanAI::sGossipSelect (Player * player, uint32 , uint32) inline override virtual
Reimplemented from UnitAI.
Definition at line 806 of file boss_illidan.cpp.
         {
             CloseGossipMenuFor(player);
             me->SetUInt32Value(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_NONE);
             me->setActive(true);
             if (instance->GetBossState(DATA_AKAMA_FINISHED) != DONE)
             {
                 me->SetReactState(REACT_PASSIVE);
                 Start(false, true);
                 SetDespawnAtEnd(false);
             }
             else
             {
                 me->GetMotionMaster()->MovePoint(POINT_ILLIDAN, 744.45f, 304.84f, 353.0f);
                 events.Reset();
                 events.ScheduleEvent(EVENT_AKAMA_SCENE_20, 5000);
                 events.ScheduleEvent(EVENT_AKAMA_SCENE_21, 8000);
                 events.ScheduleEvent(EVENT_AKAMA_SCENE_22, 10000);
                 events.ScheduleEvent(EVENT_AKAMA_SCENE_23, 23000);
                 events.ScheduleEvent(EVENT_AKAMA_SCENE_24, 34000);
                 events.ScheduleEvent(EVENT_AKAMA_SCENE_25, 41000);
                 events.ScheduleEvent(EVENT_AKAMA_SCENE_26, 46000);
                 events.ScheduleEvent(EVENT_AKAMA_SCENE_27, 49000);
                 events.ScheduleEvent(EVENT_AKAMA_SCENE_28, 49200);
                 events.ScheduleEvent(EVENT_AKAMA_SCENE_29, 52000);
             }
         }
References CloseGossipMenuFor(), DATA_AKAMA_FINISHED, DONE, EVENT_AKAMA_SCENE_20, EVENT_AKAMA_SCENE_21, EVENT_AKAMA_SCENE_22, EVENT_AKAMA_SCENE_23, EVENT_AKAMA_SCENE_24, EVENT_AKAMA_SCENE_25, EVENT_AKAMA_SCENE_26, EVENT_AKAMA_SCENE_27, EVENT_AKAMA_SCENE_28, EVENT_AKAMA_SCENE_29, InstanceScript::GetBossState(), Unit::GetMotionMaster(), instance, ScriptedAI::me, MotionMaster::MovePoint(), POINT_ILLIDAN, REACT_PASSIVE, WorldObject::setActive(), npc_escortAI::SetDespawnAtEnd(), Creature::SetReactState(), Object::SetUInt32Value(), npc_escortAI::Start(), UNIT_NPC_FLAG_NONE, and UNIT_NPC_FLAGS.
UpdateEscortAI()
void npc_akama_illidan::npc_akama_illidanAI::UpdateEscortAI (uint32 diff) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 881 of file boss_illidan.cpp.
         {
             events.Update(diff);
             switch (events.ExecuteEvent())
             {
                 case EVENT_AKAMA_SCENE_1:
                     me->SetFacingTo(0.0f);
                     break;
                 case EVENT_AKAMA_SCENE_2:
                     Talk(SAY_AKAMA_DOORS);
                     break;
                 case EVENT_AKAMA_SCENE_3:
                     me->CastSpell(me, SPELL_AKAMA_DOOR_FAIL, false);
                     break;
                 case EVENT_AKAMA_SCENE_4:
                     Talk(SAY_AKAMA_FAIL);
                     break;
                 case EVENT_AKAMA_SCENE_5:
                     me->SummonCreature(NPC_SPIRIT_OF_UDALO, me->GetPositionX() - 5.0f, me->GetPositionY() + 8.0f, me->GetPositionZ(), 0.0f, TEMPSUMMON_TIMED_DESPAWN, 60000);
                     me->SummonCreature(NPC_SPIRIT_OF_OLUM, me->GetPositionX() - 5.0f, me->GetPositionY() - 8.0f, me->GetPositionZ(), 0.0f, TEMPSUMMON_TIMED_DESPAWN, 60000);
                     break;
                 case EVENT_AKAMA_SCENE_6:
                     if (Creature* udalo = me->FindNearestCreature(NPC_SPIRIT_OF_UDALO, 15.0f))
                         udalo->AI()->Talk(SAY_UDALO);
                     break;
                 case EVENT_AKAMA_SCENE_7:
                     if (Creature* olum = me->FindNearestCreature(NPC_SPIRIT_OF_OLUM, 15.0f))
                         olum->AI()->Talk(SAY_OLUM);
                     break;
                 case EVENT_AKAMA_SCENE_8:
                     me->CastSpell(me, SPELL_AKAMA_DOOR_OPEN, false);
                     if (Creature* olum = me->FindNearestCreature(NPC_SPIRIT_OF_OLUM, 15.0f))
                         olum->CastSpell(olum, SPELL_AKAMA_DOOR_OPEN, false);
                     if (Creature* udalo = me->FindNearestCreature(NPC_SPIRIT_OF_UDALO, 15.0f))
                         udalo->CastSpell(udalo, SPELL_AKAMA_DOOR_OPEN, false);
                     break;
                 case EVENT_AKAMA_SCENE_9:
                     instance->SetBossState(DATA_AKAMA_FINISHED, NOT_STARTED);
                     instance->SetBossState(DATA_AKAMA_FINISHED, DONE);
                     break;
                 case EVENT_AKAMA_SCENE_10:
                     Talk(SAY_AKAMA_BEWARE);
                     break;
                 case EVENT_AKAMA_SCENE_11:
                     SetEscortPaused(false);
                     break;
                 case EVENT_AKAMA_SCENE_20:
                     if (Creature* illidan = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_ILLIDAN_STORMRAGE)))
                         illidan->SetStandState(UNIT_STAND_STATE_STAND);
                     break;
                 case EVENT_AKAMA_SCENE_21:
                     me->SetFacingTo(M_PI);
                     break;
                 case EVENT_AKAMA_SCENE_22:
                     if (Creature* illidan = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_ILLIDAN_STORMRAGE)))
                         illidan->AI()->Talk(SAY_ILLIDAN_AKAMA1);
                     break;
                 case EVENT_AKAMA_SCENE_23:
                     Talk(SAY_AKAMA_ILLIDAN1);
                     break;
                 case EVENT_AKAMA_SCENE_24:
                     if (Creature* illidan = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_ILLIDAN_STORMRAGE)))
                         illidan->AI()->Talk(SAY_ILLIDAN_AKAMA2);
                     break;
                 case EVENT_AKAMA_SCENE_25:
                     Talk(SAY_AKAMA_ILLIDAN2);
                     break;
                 case EVENT_AKAMA_SCENE_26:
                     if (Creature* illidan = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_ILLIDAN_STORMRAGE)))
                         illidan->AI()->Talk(SAY_ILLIDAN_AKAMA3);
                     break;
                 case EVENT_AKAMA_SCENE_27:
                     if (Creature* illidan = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_ILLIDAN_STORMRAGE)))
                         illidan->LoadEquipment(1, true);
                     break;
                 case EVENT_AKAMA_SCENE_28:
                     if (Creature* illidan = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_ILLIDAN_STORMRAGE)))
                         illidan->HandleEmoteCommand(EMOTE_ONESHOT_TALK_NO_SHEATHE);
                     break;
                 case EVENT_AKAMA_SCENE_29:
                     if (Creature* illidan = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_ILLIDAN_STORMRAGE)))
                     {
                         illidan->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
                         illidan->SetInCombatWithZone();
                         AttackStart(illidan);
                     }
                     break;
                 case EVENT_AKAMA_SUMMON_ILLIDARI:
                     me->SummonCreature(NPC_ILLIDARI_ELITE, 742.55f, 359.12f, 353.0f, 4.35f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30000);
                     events.ScheduleEvent(EVENT_AKAMA_SUMMON_ILLIDARI, urand(2000, 6000));
                     break;
                 case EVENT_AKAMA_SPELL_CHAIN:
                     if (me->GetVictim())
                         me->CastSpell(me->GetVictim(), SPELL_CHAIN_LIGHTNING, false);
                     events.ScheduleEvent(EVENT_AKAMA_SPELL_CHAIN, 20000);
                     break;
                 case EVENT_AKAMA_HEALTH:
                     if (me->HealthBelowPct(20))
                         me->CastSpell(me, SPELL_HEALING_POTION, false);
                     events.ScheduleEvent(EVENT_AKAMA_HEALTH, 1000);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References npc_escortAI::AttackStart(), Unit::CastSpell(), DATA_AKAMA_FINISHED, UnitAI::DoMeleeAttackIfReady(), DONE, EMOTE_ONESHOT_TALK_NO_SHEATHE, EVENT_AKAMA_HEALTH, EVENT_AKAMA_SCENE_1, EVENT_AKAMA_SCENE_10, EVENT_AKAMA_SCENE_11, EVENT_AKAMA_SCENE_2, EVENT_AKAMA_SCENE_20, EVENT_AKAMA_SCENE_21, EVENT_AKAMA_SCENE_22, EVENT_AKAMA_SCENE_23, EVENT_AKAMA_SCENE_24, EVENT_AKAMA_SCENE_25, EVENT_AKAMA_SCENE_26, EVENT_AKAMA_SCENE_27, EVENT_AKAMA_SCENE_28, EVENT_AKAMA_SCENE_29, EVENT_AKAMA_SCENE_3, EVENT_AKAMA_SCENE_4, EVENT_AKAMA_SCENE_5, EVENT_AKAMA_SCENE_6, EVENT_AKAMA_SCENE_7, EVENT_AKAMA_SCENE_8, EVENT_AKAMA_SCENE_9, EVENT_AKAMA_SPELL_CHAIN, EVENT_AKAMA_SUMMON_ILLIDARI, WorldObject::FindNearestCreature(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetVictim(), Unit::HealthBelowPct(), instance, ScriptedAI::me, NOT_STARTED, NPC_ILLIDAN_STORMRAGE, NPC_ILLIDARI_ELITE, NPC_SPIRIT_OF_OLUM, NPC_SPIRIT_OF_UDALO, SAY_AKAMA_BEWARE, SAY_AKAMA_DOORS, SAY_AKAMA_FAIL, SAY_AKAMA_ILLIDAN1, SAY_AKAMA_ILLIDAN2, SAY_ILLIDAN_AKAMA1, SAY_ILLIDAN_AKAMA2, SAY_ILLIDAN_AKAMA3, SAY_OLUM, SAY_UDALO, InstanceScript::SetBossState(), npc_escortAI::SetEscortPaused(), Unit::SetFacingTo(), SPELL_AKAMA_DOOR_FAIL, SPELL_AKAMA_DOOR_OPEN, SPELL_CHAIN_LIGHTNING, SPELL_HEALING_POTION, WorldObject::SummonCreature(), CreatureAI::Talk(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, TEMPSUMMON_TIMED_DESPAWN, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, UNIT_STAND_STATE_STAND, and urand().
WaypointReached()
void npc_akama_illidan::npc_akama_illidanAI::WaypointReached (uint32 pointId) inline override virtual
Implements npc_escortAI.
Definition at line 848 of file boss_illidan.cpp.
         {
             if (pointId == POINT_DOORS)
             {
                 SetEscortPaused(true);
                 events.ScheduleEvent(EVENT_AKAMA_SCENE_1, 0);
                 events.ScheduleEvent(EVENT_AKAMA_SCENE_2, 4000);
                 events.ScheduleEvent(EVENT_AKAMA_SCENE_3, 7000);
                 events.ScheduleEvent(EVENT_AKAMA_SCENE_4, 17000);
                 events.ScheduleEvent(EVENT_AKAMA_SCENE_5, 23000);
                 events.ScheduleEvent(EVENT_AKAMA_SCENE_6, 25000);
                 events.ScheduleEvent(EVENT_AKAMA_SCENE_7, 31000);
                 events.ScheduleEvent(EVENT_AKAMA_SCENE_8, 40000);
                 events.ScheduleEvent(EVENT_AKAMA_SCENE_9, 54000);
                 events.ScheduleEvent(EVENT_AKAMA_SCENE_10, 57000);
                 events.ScheduleEvent(EVENT_AKAMA_SCENE_11, 62000);
             }
             else if (pointId == POINT_ILLIDAN)
             {
                 me->SetUInt32Value(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
                 me->setActive(false);
                 me->SetReactState(REACT_AGGRESSIVE);
             }
         }
References EVENT_AKAMA_SCENE_1, EVENT_AKAMA_SCENE_10, EVENT_AKAMA_SCENE_11, EVENT_AKAMA_SCENE_2, EVENT_AKAMA_SCENE_3, EVENT_AKAMA_SCENE_4, EVENT_AKAMA_SCENE_5, EVENT_AKAMA_SCENE_6, EVENT_AKAMA_SCENE_7, EVENT_AKAMA_SCENE_8, EVENT_AKAMA_SCENE_9, ScriptedAI::me, POINT_DOORS, POINT_ILLIDAN, REACT_AGGRESSIVE, WorldObject::setActive(), npc_escortAI::SetEscortPaused(), Creature::SetReactState(), Object::SetUInt32Value(), UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
Member Data Documentation
events
EventMap npc_akama_illidan::npc_akama_illidanAI::events private
Definition at line 988 of file boss_illidan.cpp.
instance
InstanceScript* npc_akama_illidan::npc_akama_illidanAI::instance private
Definition at line 990 of file boss_illidan.cpp.
Referenced by npc_akama_illidanAI(), Reset(), sGossipSelect(), and UpdateEscortAI().
summons
SummonList npc_akama_illidan::npc_akama_illidanAI::summons private
Definition at line 989 of file boss_illidan.cpp.
Referenced by DoAction(), JustSummoned(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/BlackTemple/boss_illidan.cpp