Azerotcore-wotlk: spell_gen_mount Class Reference
spell_gen_mount Class Reference
Public Member Functions
spell_gen_mount (uint32 mount0, uint32 mount60, uint32 mount100, uint32 mount150, uint32 mount280, uint32 mount310)
bool Validate (SpellInfo const *) override
void HandleMount (SpellEffIndex effIndex)
void Register () override
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual bool Load ()
virtual void Unload ()
Private Member Functions
PrepareSpellScript (spell_gen_mount)
Private Attributes
uint32 _mount0
uint32 _mount60
uint32 _mount100
uint32 _mount150
uint32 _mount280
uint32 _mount310
Additional Inherited Members
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Definition at line 3782 of file spell_generic.cpp.
Constructor & Destructor Documentation
spell_gen_mount()
spell_gen_mount::spell_gen_mount (uint32 mount0, uint32 mount60, uint32 mount100, uint32 mount150, uint32 mount280, uint32 mount310) inline
Definition at line 3787 of file spell_generic.cpp.
                                                                                                                        : SpellScript(),
         _mount0(mount0), _mount60(mount60), _mount100(mount100), _mount150(mount150), _mount280(mount280), _mount310(mount310) { }
Member Function Documentation
HandleMount()
void spell_gen_mount::HandleMount (SpellEffIndex effIndex) inline
Definition at line 3807 of file spell_generic.cpp.
     {
         PreventHitDefaultEffect(effIndex);
         if (Player* target = GetHitPlayer())
         {
             uint32 petNumber = target->GetTemporaryUnsummonedPetNumber();
             target->SetTemporaryUnsummonedPetNumber(0);
             // Prevent stacking of mounts and client crashes upon dismounting
             target->RemoveAurasByType(SPELL_AURA_MOUNTED, ObjectGuid::Empty, GetHitAura());
             // Triggered spell id dependent on riding skill and zone
             bool canFly = false;
             uint32 map = GetVirtualMapForMapAndZone(target->GetMapId(), target->GetZoneId());
             if (map == 530 || (map == 571 && target->HasSpell(SPELL_COLD_WEATHER_FLYING)))
                 canFly = true;
             AreaTableEntry const* area = sAreaTableStore.LookupEntry(target->GetAreaId());
             // Xinef: add battlefield check
             Battlefield* Bf = sBattlefieldMgr->GetBattlefieldToZoneId(target->GetZoneId());
             if (!area || (canFly && ((area->flags & AREA_FLAG_NO_FLY_ZONE) || (Bf && !Bf->CanFlyIn()))))
                 canFly = false;
             uint32 mount = 0;
             switch (target->GetBaseSkillValue(SKILL_RIDING))
             {
                 case 0:
                     mount = _mount0;
                     break;
                 case 75:
                     mount = _mount60;
                     break;
                 case 150:
                     mount = _mount100;
                     break;
                 case 225:
                     if (canFly)
                         mount = _mount150;
                     else
                         mount = _mount100;
                     break;
                 case 300:
                     if (canFly)
                     {
                         if (_mount310 && target->Has310Flyer(false))
                             mount = _mount310;
                         else
                             mount = _mount280;
                     }
                     else
                         mount = _mount100;
                     break;
                 default:
                     break;
             }
             if (mount)
             {
                 PreventHitAura();
                 target->CastSpell(target, mount, true);
             }
             if (petNumber)
                 target->SetTemporaryUnsummonedPetNumber(petNumber);
         }
     }
References _mount0, _mount100, _mount150, _mount280, _mount310, _mount60, AREA_FLAG_NO_FLY_ZONE, Battlefield::CanFlyIn(), ObjectGuid::Empty, AreaTableEntry::flags, SpellScript::GetHitAura(), SpellScript::GetHitPlayer(), GetVirtualMapForMapAndZone(), SpellScript::PreventHitAura(), SpellScript::PreventHitDefaultEffect(), sAreaTableStore, sBattlefieldMgr, SKILL_RIDING, SPELL_AURA_MOUNTED, and SPELL_COLD_WEATHER_FLYING.
Referenced by Register().
PrepareSpellScript()
spell_gen_mount::PrepareSpellScript (spell_gen_mount) private
Register()
void spell_gen_mount::Register () inline override virtual
Implements _SpellScript.
Definition at line 3875 of file spell_generic.cpp.
     {
         OnEffectHitTarget += SpellEffectFn(spell_gen_mount::HandleMount, EFFECT_2, SPELL_EFFECT_SCRIPT_EFFECT);
     }
References EFFECT_2, HandleMount(), SpellScript::OnEffectHitTarget, SPELL_EFFECT_SCRIPT_EFFECT, and SpellEffectFn.
Validate()
bool spell_gen_mount::Validate (SpellInfo const *) inline override virtual
Reimplemented from _SpellScript.
Definition at line 3790 of file spell_generic.cpp.
     {
         if (_mount0 && !sSpellMgr->GetSpellInfo(_mount0))
             return false;
         if (_mount60 && !sSpellMgr->GetSpellInfo(_mount60))
             return false;
         if (_mount100 && !sSpellMgr->GetSpellInfo(_mount100))
             return false;
         if (_mount150 && !sSpellMgr->GetSpellInfo(_mount150))
             return false;
         if (_mount280 && !sSpellMgr->GetSpellInfo(_mount280))
             return false;
         if (_mount310 && !sSpellMgr->GetSpellInfo(_mount310))
             return false;
         return true;
     }
References _mount0, _mount100, _mount150, _mount280, _mount310, _mount60, and sSpellMgr.
Member Data Documentation
_mount0
uint32 spell_gen_mount::_mount0 private
Definition at line 3881 of file spell_generic.cpp.
Referenced by HandleMount(), and Validate().
_mount100
uint32 spell_gen_mount::_mount100 private
Definition at line 3883 of file spell_generic.cpp.
Referenced by HandleMount(), and Validate().
_mount150
uint32 spell_gen_mount::_mount150 private
Definition at line 3884 of file spell_generic.cpp.
Referenced by HandleMount(), and Validate().
_mount280
uint32 spell_gen_mount::_mount280 private
Definition at line 3885 of file spell_generic.cpp.
Referenced by HandleMount(), and Validate().
_mount310
uint32 spell_gen_mount::_mount310 private
Definition at line 3886 of file spell_generic.cpp.
Referenced by HandleMount(), and Validate().
_mount60
uint32 spell_gen_mount::_mount60 private
Definition at line 3882 of file spell_generic.cpp.
Referenced by HandleMount(), and Validate().
The documentation for this class was generated from the following file:
src/server/scripts/Spells/spell_generic.cpp