Azerotcore-wotlk: tele_commandscript Class Reference
tele_commandscript Class Reference
Public Member Functions
tele_commandscript ()
ChatCommandTable GetCommands () const override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Static Public Member Functions
static bool HandleTeleAddCommand (ChatHandler *handler, std::string const &name)
static bool HandleTeleDelCommand (ChatHandler *handler, GameTele const *tele)
static bool DoNameTeleport (ChatHandler *handler, PlayerIdentifier player, uint32 mapId, Position const &pos, std::string const &locationName)
static bool HandleTeleNameCommand (ChatHandler *handler, Optional< PlayerIdentifier > player, Variant< GameTele const *, EXACT_SEQUENCE("$home")> where)
static bool HandleTeleGroupCommand (ChatHandler *handler, GameTele const *tele)
static bool HandleTeleCommand (ChatHandler *handler, GameTele const *tele)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 35 of file cs_tele.cpp.
Constructor & Destructor Documentation
tele_commandscript()
tele_commandscript::tele_commandscript () inline
Definition at line 38 of file cs_tele.cpp.
 : CommandScript("tele_commandscript") { }
Member Function Documentation
DoNameTeleport()
static bool tele_commandscript::DoNameTeleport (ChatHandler * handler, PlayerIdentifier player, uint32 mapId, Position const & pos, std::string const & locationName) inline static
Definition at line 107 of file cs_tele.cpp.
     {
         if (!MapMgr::IsValidMapCoord(mapId, pos) || sObjectMgr->IsTransportMap(mapId))
         {
             handler->PSendSysMessage(LANG_INVALID_TARGET_COORD, pos.GetPositionX(), pos.GetPositionY(), mapId);
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (Player* target = player.GetConnectedPlayer())
         {
             // check online security
             if (handler->HasLowerSecurity(target, ObjectGuid::Empty))
                 return false;
             std::string chrNameLink = handler->playerLink(target->GetName());
             if (target->IsBeingTeleported())
             {
                 handler->PSendSysMessage(LANG_IS_TELEPORTED, chrNameLink.c_str());
                 handler->SetSentErrorMessage(true);
                 return false;
             }
             handler->PSendSysMessage(LANG_TELEPORTING_TO, chrNameLink.c_str(), "", locationName.c_str());
             if (handler->needReportToTarget(target))
                 ChatHandler(target->GetSession()).PSendSysMessage(LANG_TELEPORTED_TO_BY, handler->GetNameLink().c_str());
             // stop flight if need
             if (target->IsInFlight())
             {
                 target->GetMotionMaster()->MovementExpired();
                 target->CleanupAfterTaxiFlight();
             }
             else // save only in non-flight case
                 target->SaveRecallPosition();
             target->TeleportTo({ mapId, pos });
         }
         else
         {
             // check offline security
             if (handler->HasLowerSecurity(nullptr, player.GetGUID()))
                 return false;
             std::string nameLink = handler->playerLink(player.GetName());
             handler->PSendSysMessage(LANG_TELEPORTING_TO, nameLink.c_str(), handler->GetAcoreString(LANG_OFFLINE), locationName.c_str());
             Player::SavePositionInDB({ mapId, pos }, sMapMgr->GetZoneId(PHASEMASK_NORMAL, { mapId, pos }), player.GetGUID(), nullptr);
         }
         return true;
     }
References ObjectGuid::Empty, ChatHandler::GetAcoreString(), Acore::ChatCommands::PlayerIdentifier::GetConnectedPlayer(), Acore::ChatCommands::PlayerIdentifier::GetGUID(), Acore::ChatCommands::PlayerIdentifier::GetName(), ChatHandler::GetNameLink(), ChatHandler::HasLowerSecurity(), MapMgr::IsValidMapCoord(), LANG_INVALID_TARGET_COORD, LANG_IS_TELEPORTED, LANG_OFFLINE, LANG_TELEPORTED_TO_BY, LANG_TELEPORTING_TO, ChatHandler::needReportToTarget(), PHASEMASK_NORMAL, ChatHandler::playerLink(), pos(), ChatHandler::PSendSysMessage(), Player::SavePositionInDB(), ChatHandler::SetSentErrorMessage(), sMapMgr, and sObjectMgr.
GetCommands()
ChatCommandTable tele_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
Definition at line 40 of file cs_tele.cpp.
     {
         static ChatCommandTable teleCommandTable =
         {
             { "add",    HandleTeleAddCommand,   SEC_ADMINISTRATOR, Console::No },
             { "del",    HandleTeleDelCommand,   SEC_ADMINISTRATOR, Console::Yes },
             { "name",   HandleTeleNameCommand,  SEC_GAMEMASTER,    Console::Yes },
             { "group",  HandleTeleGroupCommand, SEC_GAMEMASTER,    Console::No },
             { "",       HandleTeleCommand,      SEC_GAMEMASTER,    Console::No }
         };
         static ChatCommandTable commandTable =
         {
             { "teleport", teleCommandTable }
         };
         return commandTable;
     }
References Acore::ChatCommands::No, SEC_ADMINISTRATOR, SEC_GAMEMASTER, and Acore::ChatCommands::Yes.
HandleTeleAddCommand()
static bool tele_commandscript::HandleTeleAddCommand (ChatHandler * handler, std::string const & name) inline static
Definition at line 57 of file cs_tele.cpp.
     {
         Player* player = handler->GetSession()->GetPlayer();
         if (!player)
             return false;
         if (sObjectMgr->GetGameTele(name))
         {
             handler->SendSysMessage(LANG_COMMAND_TP_ALREADYEXIST);
             handler->SetSentErrorMessage(true);
             return false;
         }
         GameTele tele;
         tele.position_x  = player->GetPositionX();
         tele.position_y  = player->GetPositionY();
         tele.position_z  = player->GetPositionZ();
         tele.orientation = player->GetOrientation();
         tele.mapId       = player->GetMapId();
         tele.name        = name;
         if (sObjectMgr->AddGameTele(tele))
         {
             handler->SendSysMessage(LANG_COMMAND_TP_ADDED);
         }
         else
         {
             handler->SendSysMessage(LANG_COMMAND_TP_ADDEDERR);
             handler->SetSentErrorMessage(true);
             return false;
         }
         return true;
     }
References WorldLocation::GetMapId(), Position::GetOrientation(), WorldSession::GetPlayer(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ChatHandler::GetSession(), LANG_COMMAND_TP_ADDED, LANG_COMMAND_TP_ADDEDERR, LANG_COMMAND_TP_ALREADYEXIST, GameTele::mapId, GameTele::name, GameTele::orientation, GameTele::position_x, GameTele::position_y, GameTele::position_z, ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), and sObjectMgr.
HandleTeleCommand()
static bool tele_commandscript::HandleTeleCommand (ChatHandler * handler, GameTele const * tele) inline static
Definition at line 276 of file cs_tele.cpp.
     {
         if (!tele)
         {
             handler->SendSysMessage(LANG_COMMAND_TELE_NOTFOUND);
             handler->SetSentErrorMessage(true);
             return false;
         }
         Player* player = handler->GetSession()->GetPlayer();
         if (player->IsInCombat())
         {
             handler->SendSysMessage(LANG_YOU_IN_COMBAT);
             handler->SetSentErrorMessage(true);
             return false;
         }
         MapEntry const* map = sMapStore.LookupEntry(tele->mapId);
         if (!map || (map->IsBattlegroundOrArena() && (player->GetMapId() != tele->mapId || !player->IsGameMaster())))
         {
             handler->SendSysMessage(LANG_CANNOT_TELE_TO_BG);
             handler->SetSentErrorMessage(true);
             return false;
         }
         // stop flight if need
         if (player->IsInFlight())
         {
             player->GetMotionMaster()->MovementExpired();
             player->CleanupAfterTaxiFlight();
         }
         else // save only in non-flight case
             player->SaveRecallPosition();
         player->TeleportTo(tele->mapId, tele->position_x, tele->position_y, tele->position_z, tele->orientation);
         return true;
     }
References Player::CleanupAfterTaxiFlight(), WorldLocation::GetMapId(), Unit::GetMotionMaster(), WorldSession::GetPlayer(), ChatHandler::GetSession(), MapEntry::IsBattlegroundOrArena(), Player::IsGameMaster(), Unit::IsInCombat(), Unit::IsInFlight(), LANG_CANNOT_TELE_TO_BG, LANG_COMMAND_TELE_NOTFOUND, LANG_YOU_IN_COMBAT, GameTele::mapId, MotionMaster::MovementExpired(), GameTele::orientation, GameTele::position_x, GameTele::position_y, GameTele::position_z, Player::SaveRecallPosition(), ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), sMapStore, and Player::TeleportTo().
HandleTeleDelCommand()
static bool tele_commandscript::HandleTeleDelCommand (ChatHandler * handler, GameTele const * tele) inline static
Definition at line 92 of file cs_tele.cpp.
     {
         if (!tele)
         {
             handler->SendSysMessage(LANG_COMMAND_TELE_NOTFOUND);
             handler->SetSentErrorMessage(true);
             return false;
         }
         std::string name = tele->name;
         sObjectMgr->DeleteGameTele(name);
         handler->SendSysMessage(LANG_COMMAND_TP_DELETED);
         return true;
     }
References LANG_COMMAND_TELE_NOTFOUND, LANG_COMMAND_TP_DELETED, GameTele::name, ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), and sObjectMgr.
HandleTeleGroupCommand()
static bool tele_commandscript::HandleTeleGroupCommand (ChatHandler * handler, GameTele const * tele) inline static
Definition at line 199 of file cs_tele.cpp.
     {
         if (!tele)
         {
             handler->SendSysMessage(LANG_COMMAND_TELE_NOTFOUND);
             handler->SetSentErrorMessage(true);
             return false;
         }
         Player* target = handler->getSelectedPlayer();
         if (!target)
         {
             handler->SendSysMessage(LANG_NO_CHAR_SELECTED);
             handler->SetSentErrorMessage(true);
             return false;
         }
         // check online security
         if (handler->HasLowerSecurity(target, ObjectGuid::Empty))
             return false;
         MapEntry const* map = sMapStore.LookupEntry(tele->mapId);
         if (!map || map->IsBattlegroundOrArena())
         {
             handler->SendSysMessage(LANG_CANNOT_TELE_TO_BG);
             handler->SetSentErrorMessage(true);
             return false;
         }
         std::string nameLink = handler->GetNameLink(target);
         Group* grp = target->GetGroup();
         if (!grp)
         {
             handler->PSendSysMessage(LANG_NOT_IN_GROUP, nameLink.c_str());
             handler->SetSentErrorMessage(true);
             return false;
         }
         for (GroupReference* itr = grp->GetFirstMember(); itr != nullptr; itr = itr->next())
         {
             Player* player = itr->GetSource();
             if (!player || !player->GetSession())
                 continue;
             // check online security
             if (handler->HasLowerSecurity(player, ObjectGuid::Empty))
                 return false;
             std::string plNameLink = handler->GetNameLink(player);
             if (player->IsBeingTeleported())
             {
                 handler->PSendSysMessage(LANG_IS_TELEPORTED, plNameLink.c_str());
                 continue;
             }
             handler->PSendSysMessage(LANG_TELEPORTING_TO, plNameLink.c_str(), "", tele->name.c_str());
             if (handler->needReportToTarget(player))
                 ChatHandler(player->GetSession()).PSendSysMessage(LANG_TELEPORTED_TO_BY, nameLink.c_str());
             // stop flight if need
             if (target->IsInFlight())
             {
                 target->GetMotionMaster()->MovementExpired();
                 target->CleanupAfterTaxiFlight();
             }
             else // save only in non-flight case
                 target->SaveRecallPosition();
             player->TeleportTo(tele->mapId, tele->position_x, tele->position_y, tele->position_z, tele->orientation);
         }
         return true;
     }
References Player::CleanupAfterTaxiFlight(), ObjectGuid::Empty, Group::GetFirstMember(), Player::GetGroup(), Unit::GetMotionMaster(), ChatHandler::GetNameLink(), ChatHandler::getSelectedPlayer(), Player::GetSession(), ChatHandler::HasLowerSecurity(), MapEntry::IsBattlegroundOrArena(), Player::IsBeingTeleported(), Unit::IsInFlight(), LANG_CANNOT_TELE_TO_BG, LANG_COMMAND_TELE_NOTFOUND, LANG_IS_TELEPORTED, LANG_NO_CHAR_SELECTED, LANG_NOT_IN_GROUP, LANG_TELEPORTED_TO_BY, LANG_TELEPORTING_TO, GameTele::mapId, MotionMaster::MovementExpired(), GameTele::name, ChatHandler::needReportToTarget(), GroupReference::next(), GameTele::orientation, GameTele::position_x, GameTele::position_y, GameTele::position_z, ChatHandler::PSendSysMessage(), Player::SaveRecallPosition(), ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), sMapStore, and Player::TeleportTo().
HandleTeleNameCommand()
static bool tele_commandscript::HandleTeleNameCommand (ChatHandler * handler, Optional< PlayerIdentifier > player, Variant< GameTele const *, EXACT_SEQUENCE("$home")> where) inline static
Definition at line 163 of file cs_tele.cpp.
     {
         if (!player)
             player = PlayerIdentifier::FromTargetOrSelf(handler);
         if (!player)
             return false;
         if (where.index() == 1)    // References target's homebind
         {
             if (Player* target = player->GetConnectedPlayer())
                 target->TeleportTo(target->m_homebindMapId, target->m_homebindX, target->m_homebindY, target->m_homebindZ, target->GetOrientation());
             else
             {
                 CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_CHAR_HOMEBIND);
                 stmt->setUInt32(0, player->GetGUID().GetCounter());
                 PreparedQueryResult resultDB = CharacterDatabase.Query(stmt);
                 if (resultDB)
                 {
                     Field* fieldsDB = resultDB->Fetch();
                     WorldLocation loc(fieldsDB[0].GetUInt16(), fieldsDB[2].GetFloat(), fieldsDB[3].GetFloat(), fieldsDB[4].GetFloat(), 0.0f);
                     uint32 zoneId = fieldsDB[1].GetUInt16();
                     Player::SavePositionInDB(loc, zoneId, player->GetGUID(), nullptr);
                 }
             }
             return true;
         }
         // id, or string, or [name] Shift-click form |color|Htele:id|h[name]|h|r
         GameTele const* tele = where.get<GameTele const*>();
         return DoNameTeleport(handler, *player, tele->mapId, { tele->position_x, tele->position_y, tele->position_z, tele->orientation }, tele->name);
     }
References CHAR_SEL_CHAR_HOMEBIND, CharacterDatabase, Acore::ChatCommands::PlayerIdentifier::FromTargetOrSelf(), Field::GetUInt16(), GameTele::mapId, GameTele::name, Player::SavePositionInDB(), and PreparedStatementBase::setUInt32().
The documentation for this class was generated from the following file:
src/server/scripts/Commands/cs_tele.cpp