Azerotcore-wotlk: G3D::Cone Class Reference
G3D::Cone Class Reference
#include <Cone.h>
Public Member Functions
Cone (const Vector3 &tip, const Vector3 &direction, float angle)
Cone (const Vector3 &tip, const class Box &box)
virtual ~Cone ()
bool intersects (const class Sphere &s) const
bool contains (const class Vector3 &v) const
Vector3 randomDirectionInCone (Random &rng) const
Static Public Member Functions
static float solidAngleFromHalfAngle (float halfAngle)
static double solidAngleFromHalfAngle (double halfAngle)
static float halfAngleFromSolidAngle (float solidAngle)
static double halfAngleFromSolidAngle (double solidAngle)
Private Attributes
Vector3 tip
Vector3 direction
float angle
Detailed Description
An infinite cone.
Definition at line 28 of file Cone.h.
Constructor & Destructor Documentation
Cone() [1/2]
G3D::Cone::Cone (const Vector3 & tip, const Vector3 & direction, float angle)
Parameters
angle Angle from the center line to the edge, in radians
Definition at line 38 of file Cone.cpp.
{
     this->tip = tip;
     this->direction = direction.direction();
     this->angle = angle;
     debugAssert(angle >= 0);
     debugAssert(angle <= pi());
 }
References angle, debugAssert, direction, G3D::Vector3::direction(), G3D::pi(), and tip.
Referenced by intersects().
Cone() [2/2]
G3D::Cone::Cone (const Vector3 & tip, const class Box & box)
Forms the smallest cone that contains the box. Undefined if the tip is inside or on the box.
~Cone()
virtual G3D::Cone::~Cone () inline virtual
Definition at line 50 of file Cone.h.
 {}
Member Function Documentation
contains()
bool G3D::Cone::contains (const class Vector3 & v) const
True if v is a point inside the cone.
Definition at line 124 of file Cone.cpp.
{
     Vector3 d = (v - tip).direction();
     float x = d.dot(direction);
     return (x > 0) && (x >= cosf(angle));
 }
References angle, mpq::d, direction, tip, and G3D::x.
halfAngleFromSolidAngle() [1/2]
double G3D::Cone::halfAngleFromSolidAngle (double solidAngle) static
Definition at line 33 of file Cone.cpp.
{
     return aCos((1.0 - (solidAngle / (2.0 * pi()))));
 }
References G3D::aCos(), and G3D::pi().
halfAngleFromSolidAngle() [2/2]
float G3D::Cone::halfAngleFromSolidAngle (float solidAngle) static
Returns the half-angle (in radians) of a cone that subtends solidAngle (in steradians)
Definition at line 29 of file Cone.cpp.
{
     return acos((1.0f - (solidAngle / (2.0f * pif()))));
 }
References G3D::acos(), and G3D::pif().
intersects()
bool G3D::Cone::intersects (const class Sphere & s) const
Returns true if the cone touches, intersects, or contains b.
If c.intersects(s) and c.intersects(Sphere(s.center, s.radius * 2) then the sphere s is entirely within cone c.
Definition at line 108 of file Cone.cpp.
{
     // If the bounding sphere contains the tip, then
     // they definitely touch.
     if (b.contains(this->tip)) {
         return true;
     }
     // Move the tip backwards, effectively making the cone bigger
     // to account for the radius of the sphere.
     Vector3 tip = this->tip - direction * b.radius / sinf(angle);
     return Cone(tip, direction, angle).contains(b.center);
 }
References angle, b, Cone(), direction, and tip.
randomDirectionInCone()
Vector3 G3D::Cone::randomDirectionInCone (Random & rng) const
Definition at line 47 of file Cone.cpp.
{
         const float cosThresh = cos(angle);
         float cosAngle;
         float normalizer;
         Vector3 v;
         do {
             float vlenSquared;
             // Sample uniformly on a sphere by rejection sampling and then normalizing
             do {
                 v.x = rng.uniform(-1, 1);
                 v.y = rng.uniform(-1, 1);
                 v.z = rng.uniform(-1, 1);
                 // Sample uniformly on a cube
                 vlenSquared = v.squaredLength();
             } while (vlenSquared > 1);
             const float temp = v.dot(direction);
             // Compute 1 / ||v||, but
             // if the vector is in the wrong hemisphere, flip the sign
             normalizer = rsqrt(vlenSquared) * sign(temp);
             // Cosine of the angle between v and the light's negative-z axis
             cosAngle = temp * normalizer;
         } while (cosAngle < cosThresh);
         // v was within the cone.  Normalize it and maybe flip the hemisphere.
         return v * normalizer;
     }
References angle, direction, G3D::Vector3::dot(), G3D::rsqrt(), G3D::sign(), G3D::Vector3::squaredLength(), G3D::Random::uniform(), G3D::Vector3::x, G3D::Vector3::y, and G3D::Vector3::z.
solidAngleFromHalfAngle() [1/2]
double G3D::Cone::solidAngleFromHalfAngle (double halfAngle) static
Definition at line 25 of file Cone.cpp.
{
     return 2.0 * pi() * (1.0 - cos(halfAngle));
 }
References G3D::pi().
solidAngleFromHalfAngle() [2/2]
float G3D::Cone::solidAngleFromHalfAngle (float halfAngle) static
Returns the solid angle (in steradians) subtended by a cone with half-angle halfAngle
Definition at line 21 of file Cone.cpp.
{
     return 2.0f * pif() * (1 - cosf(halfAngle));
 }
References G3D::pif().
Member Data Documentation
angle
float G3D::Cone::angle private
Angle from the center line to the edge.
Definition at line 35 of file Cone.h.
Referenced by Cone(), contains(), intersects(), and randomDirectionInCone().
direction
Vector3 G3D::Cone::direction private
Definition at line 32 of file Cone.h.
Referenced by Cone(), contains(), intersects(), and randomDirectionInCone().
tip
Vector3 G3D::Cone::tip private
Definition at line 31 of file Cone.h.
Referenced by Cone(), contains(), and intersects().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/Cone.h
deps/g3dlite/source/Cone.cpp