Azerotcore-wotlk: deps/jemalloc/src/tsd.c File Reference
tsd.c File Reference
#include "jemalloc/internal/jemalloc_preamble.h"
#include "jemalloc/internal/jemalloc_internal_includes.h"
#include "jemalloc/internal/assert.h"
#include "jemalloc/internal/mutex.h"
#include "jemalloc/internal/rtree.h"
Classes
struct tsd_init_head_s
Macros
#define JEMALLOC_TSD_C_
Functions
JEMALLOC_DIAGNOSTIC_POP typedef ql_head (tsd_t)
static void tsd_add_nominal (tsd_t *tsd)
static void tsd_remove_nominal (tsd_t *tsd)
static void tsd_force_recompute (tsdn_t *tsdn)
void tsd_global_slow_inc (tsdn_t *tsdn)
void tsd_global_slow_dec (tsdn_t *tsdn)
static bool tsd_local_slow (tsd_t *tsd)
bool tsd_global_slow ()
static uint8_t tsd_state_compute (tsd_t *tsd)
void tsd_slow_update (tsd_t *tsd)
void tsd_state_set (tsd_t *tsd, uint8_t new_state)
static bool tsd_data_init (tsd_t *tsd)
static void assert_tsd_data_cleanup_done (tsd_t *tsd)
static bool tsd_data_init_nocleanup (tsd_t *tsd)
tsd_t * tsd_fetch_slow (tsd_t *tsd, bool minimal)
void * malloc_tsd_malloc (size_t size)
void malloc_tsd_dalloc (void *wrapper)
void malloc_tsd_cleanup_register (bool(*f)(void))
static void tsd_do_data_cleanup (tsd_t *tsd)
void tsd_cleanup (void *arg)
tsd_t * malloc_tsd_boot0 (void)
void malloc_tsd_boot1 (void)
void * tsd_init_check_recursion (tsd_init_head_t *head, tsd_init_block_t *block)
void tsd_init_finish (tsd_init_head_t *head, tsd_init_block_t *block)
void tsd_prefork (tsd_t *tsd)
void tsd_postfork_parent (tsd_t *tsd)
void tsd_postfork_child (tsd_t *tsd)
Variables
static unsigned ncleanups
static malloc_tsd_cleanup_t cleanups [MALLOC_TSD_CLEANUPS_MAX]
pthread_key_t tsd_tsd
tsd_init_head_t tsd_init_head
tsd_wrapper_t tsd_boot_wrapper
bool tsd_booted = false
Macro Definition Documentation
JEMALLOC_TSD_C_
#define JEMALLOC_TSD_C_
Definition at line 1 of file tsd.c.
Function Documentation
assert_tsd_data_cleanup_done()
static void assert_tsd_data_cleanup_done (tsd_t * tsd) static
Definition at line 240 of file tsd.c.
{
     assert(!tsd_nominal(tsd));
     assert(!tsd_in_nominal_list(tsd));
     assert(*tsd_arenap_get_unsafe(tsd) == NULL);
     assert(*tsd_iarenap_get_unsafe(tsd) == NULL);
     assert(*tsd_arenas_tdata_bypassp_get_unsafe(tsd) == true);
     assert(*tsd_arenas_tdatap_get_unsafe(tsd) == NULL);
     assert(*tsd_tcache_enabledp_get_unsafe(tsd) == false);
     assert(*tsd_prof_tdatap_get_unsafe(tsd) == NULL);
 }
References assert(), NULL, and tsd_nominal().
Referenced by tsd_cleanup(), tsd_data_init_nocleanup(), and tsd_fetch_slow().
malloc_tsd_boot0()
tsd_t* malloc_tsd_boot0 (void)
Definition at line 418 of file tsd.c.
{
     tsd_t *tsd;
     ncleanups = 0;
     if (malloc_mutex_init(&tsd_nominal_tsds_lock, "tsd_nominal_tsds_lock",
         WITNESS_RANK_OMIT, malloc_mutex_rank_exclusive)) {
         return NULL;
     }
     if (tsd_boot0()) {
         return NULL;
     }
     tsd = tsd_fetch();
     *tsd_arenas_tdata_bypassp_get(tsd) = true;
     return tsd;
 }
References malloc_mutex_init, malloc_mutex_rank_exclusive, ncleanups, NULL, tsd_boot0(), tsd_fetch(), and WITNESS_RANK_OMIT.
malloc_tsd_boot1()
void malloc_tsd_boot1 (void)
Definition at line 435 of file tsd.c.
{
     tsd_boot1();
     tsd_t *tsd = tsd_fetch();
     /* malloc_slow has been set properly.  Update tsd_slow. */
     tsd_slow_update(tsd);
     *tsd_arenas_tdata_bypassp_get(tsd) = false;
 }
References tsd_boot1(), tsd_fetch(), and tsd_slow_update().
malloc_tsd_cleanup_register()
void malloc_tsd_cleanup_register (bool(*)(void) f)
Definition at line 356 of file tsd.c.
{
     assert(ncleanups < MALLOC_TSD_CLEANUPS_MAX);
     cleanups[ncleanups] = f;
     ncleanups++;
 }
References assert(), cleanups, f(), MALLOC_TSD_CLEANUPS_MAX, and ncleanups.
malloc_tsd_dalloc()
void malloc_tsd_dalloc (void * wrapper)
Definition at line 324 of file tsd.c.
{
     a0dalloc(wrapper);
 }
References a0dalloc.
malloc_tsd_malloc()
void* malloc_tsd_malloc (size_t size)
Definition at line 319 of file tsd.c.
{
     return a0malloc(CACHELINE_CEILING(size));
 }
References a0malloc, and CACHELINE_CEILING.
ql_head()
JEMALLOC_DIAGNOSTIC_POP typedef ql_head (tsd_t)
Definition at line 61 of file tsd.c.
{
     tsd_t *tsd_list;
     bool found = false;
     /*
      * We don't know that tsd is nominal; it might not be safe to get data
      * out of it here.
      */
     malloc_mutex_lock(TSDN_NULL, &tsd_nominal_tsds_lock);
     ql_foreach(tsd_list, &tsd_nominal_tsds, TSD_MANGLE(tcache).tsd_link) {
         if (tsd == tsd_list) {
             found = true;
             break;
         }
     }
     malloc_mutex_unlock(TSDN_NULL, &tsd_nominal_tsds_lock);
     return found;
 }
tsd_add_nominal()
static void tsd_add_nominal (tsd_t * tsd) static
Definition at line 88 of file tsd.c.
{
     assert(!tsd_in_nominal_list(tsd));
     assert(tsd_state_get(tsd) <= tsd_state_nominal_max);
     ql_elm_new(tsd, TSD_MANGLE(tcache).tsd_link);
     malloc_mutex_lock(tsd_tsdn(tsd), &tsd_nominal_tsds_lock);
     ql_tail_insert(&tsd_nominal_tsds, tsd, TSD_MANGLE(tcache).tsd_link);
     malloc_mutex_unlock(tsd_tsdn(tsd), &tsd_nominal_tsds_lock);
 }
References assert(), malloc_mutex_lock(), malloc_mutex_unlock(), ql_elm_new, ql_tail_insert, TSD_MANGLE, tsd_state_get(), tsd_state_nominal_max, and tsd_tsdn().
Referenced by tsd_postfork_child(), and tsd_state_set().
tsd_cleanup()
void tsd_cleanup (void * arg)
Definition at line 373 of file tsd.c.
{
     tsd_t *tsd = (tsd_t *)arg;
     switch (tsd_state_get(tsd)) {
     case tsd_state_uninitialized:
         /* Do nothing. */
         break;
     case tsd_state_minimal_initialized:
         /* This implies the thread only did free() in its life time. */
         /* Fall through. */
     case tsd_state_reincarnated:
         /*
          * Reincarnated means another destructor deallocated memory
          * after the destructor was called.  Cleanup isn't required but
          * is still called for testing and completeness.
          */
         assert_tsd_data_cleanup_done(tsd);
         /* Fall through. */
     case tsd_state_nominal:
     case tsd_state_nominal_slow:
         tsd_do_data_cleanup(tsd);
         tsd_state_set(tsd, tsd_state_purgatory);
         tsd_set(tsd);
         break;
     case tsd_state_purgatory:
         /*
          * The previous time this destructor was called, we set the
          * state to tsd_state_purgatory so that other destructors
          * wouldn't cause re-creation of the tsd.  This time, do
          * nothing, and do not request another callback.
          */
         break;
     default:
         not_reached();
     }
 #ifdef JEMALLOC_JET
     test_callback_t test_callback = *tsd_test_callbackp_get_unsafe(tsd);
     int *data = tsd_test_datap_get_unsafe(tsd);
     if (test_callback != NULL) {
         test_callback(data);
     }
 #endif
 }
References arg(), assert_tsd_data_cleanup_done(), not_reached, NULL, tsd_do_data_cleanup(), tsd_set(), tsd_state_get(), tsd_state_minimal_initialized, tsd_state_nominal, tsd_state_nominal_slow, tsd_state_purgatory, tsd_state_reincarnated, tsd_state_set(), and tsd_state_uninitialized.
tsd_data_init()
static bool tsd_data_init (tsd_t * tsd) static
Definition at line 219 of file tsd.c.
{
     /*
      * We initialize the rtree context first (before the tcache), since the
      * tcache initialization depends on it.
      */
     rtree_ctx_data_init(tsd_rtree_ctxp_get_unsafe(tsd));
     /*
      * A nondeterministic seed based on the address of tsd reduces
      * the likelihood of lockstep non-uniform cache index
      * utilization among identical concurrent processes, but at the
      * cost of test repeatability.  For debug builds, instead use a
      * deterministic seed.
      */
     *tsd_offset_statep_get(tsd) = config_debug ? 0 :
         (uint64_t)(uintptr_t)tsd;
     return tsd_tcache_enabled_data_init(tsd);
 }
References config_debug, rtree_ctx_data_init, and tsd_tcache_enabled_data_init.
Referenced by tsd_fetch_slow().
tsd_data_init_nocleanup()
static bool tsd_data_init_nocleanup (tsd_t * tsd) static
Definition at line 252 of file tsd.c.
{
     assert(tsd_state_get(tsd) == tsd_state_reincarnated ||
         tsd_state_get(tsd) == tsd_state_minimal_initialized);
     /*
      * During reincarnation, there is no guarantee that the cleanup function
      * will be called (deallocation may happen after all tsd destructors).
      * We set up tsd in a way that no cleanup is needed.
      */
     rtree_ctx_data_init(tsd_rtree_ctxp_get_unsafe(tsd));
     *tsd_arenas_tdata_bypassp_get(tsd) = true;
     *tsd_tcache_enabledp_get_unsafe(tsd) = false;
     *tsd_reentrancy_levelp_get(tsd) = 1;
     assert_tsd_data_cleanup_done(tsd);
     return false;
 }
References assert(), assert_tsd_data_cleanup_done(), rtree_ctx_data_init, tsd_state_get(), tsd_state_minimal_initialized, and tsd_state_reincarnated.
Referenced by tsd_fetch_slow().
tsd_do_data_cleanup()
static void tsd_do_data_cleanup (tsd_t * tsd) static
Definition at line 363 of file tsd.c.
{
     prof_tdata_cleanup(tsd);
     iarena_cleanup(tsd);
     arena_cleanup(tsd);
     arenas_tdata_cleanup(tsd);
     tcache_cleanup(tsd);
     witnesses_cleanup(tsd_witness_tsdp_get_unsafe(tsd));
 }
References arena_cleanup, arenas_tdata_cleanup, iarena_cleanup, prof_tdata_cleanup, tcache_cleanup, and witnesses_cleanup.
Referenced by tsd_cleanup().
tsd_fetch_slow()
tsd_t* tsd_fetch_slow (tsd_t * tsd, bool minimal)
Definition at line 270 of file tsd.c.
{
     assert(!tsd_fast(tsd));
     if (tsd_state_get(tsd) == tsd_state_nominal_slow) {
         /*
          * On slow path but no work needed.  Note that we can't
          * necessarily *assert* that we're slow, because we might be
          * slow because of an asynchronous modification to global state,
          * which might be asynchronously modified *back*.
          */
     } else if (tsd_state_get(tsd) == tsd_state_nominal_recompute) {
         tsd_slow_update(tsd);
     } else if (tsd_state_get(tsd) == tsd_state_uninitialized) {
         if (!minimal) {
             if (tsd_booted) {
                 tsd_state_set(tsd, tsd_state_nominal);
                 tsd_slow_update(tsd);
                 /* Trigger cleanup handler registration. */
                 tsd_set(tsd);
                 tsd_data_init(tsd);
             }
         } else {
             tsd_state_set(tsd, tsd_state_minimal_initialized);
             tsd_set(tsd);
             tsd_data_init_nocleanup(tsd);
         }
     } else if (tsd_state_get(tsd) == tsd_state_minimal_initialized) {
         if (!minimal) {
             /* Switch to fully initialized. */
             tsd_state_set(tsd, tsd_state_nominal);
             assert(*tsd_reentrancy_levelp_get(tsd) >= 1);
             (*tsd_reentrancy_levelp_get(tsd))--;
             tsd_slow_update(tsd);
             tsd_data_init(tsd);
         } else {
             assert_tsd_data_cleanup_done(tsd);
         }
     } else if (tsd_state_get(tsd) == tsd_state_purgatory) {
         tsd_state_set(tsd, tsd_state_reincarnated);
         tsd_set(tsd);
         tsd_data_init_nocleanup(tsd);
     } else {
         assert(tsd_state_get(tsd) == tsd_state_reincarnated);
     }
     return tsd;
 }
References assert(), assert_tsd_data_cleanup_done(), tsd_booted, tsd_data_init(), tsd_data_init_nocleanup(), tsd_fast(), tsd_set(), tsd_slow_update(), tsd_state_get(), tsd_state_minimal_initialized, tsd_state_nominal, tsd_state_nominal_recompute, tsd_state_nominal_slow, tsd_state_purgatory, tsd_state_reincarnated, tsd_state_set(), and tsd_state_uninitialized.
tsd_force_recompute()
static void tsd_force_recompute (tsdn_t * tsdn) static
Definition at line 107 of file tsd.c.
{
     /*
      * The stores to tsd->state here need to synchronize with the exchange
      * in tsd_slow_update.
      */
     atomic_fence(ATOMIC_RELEASE);
     malloc_mutex_lock(tsdn, &tsd_nominal_tsds_lock);
     tsd_t *remote_tsd;
     ql_foreach(remote_tsd, &tsd_nominal_tsds, TSD_MANGLE(tcache).tsd_link) {
         assert(tsd_atomic_load(&remote_tsd->state, ATOMIC_RELAXED)
             <= tsd_state_nominal_max);
         tsd_atomic_store(&remote_tsd->state, tsd_state_nominal_recompute,
             ATOMIC_RELAXED);
     }
     malloc_mutex_unlock(tsdn, &tsd_nominal_tsds_lock);
 }
References assert(), atomic_fence, ATOMIC_RELAXED, ATOMIC_RELEASE, malloc_mutex_lock(), malloc_mutex_unlock(), ql_foreach, tsd_s::state, tsd_atomic_load, tsd_atomic_store, TSD_MANGLE, tsd_state_nominal_max, and tsd_state_nominal_recompute.
Referenced by tsd_global_slow_dec(), and tsd_global_slow_inc().
tsd_global_slow()
bool tsd_global_slow ()
Definition at line 151 of file tsd.c.
                   {
     return atomic_load_u32(&tsd_global_slow_count, ATOMIC_RELAXED) > 0;
 }
References ATOMIC_RELAXED.
Referenced by tsd_state_compute().
tsd_global_slow_dec()
void tsd_global_slow_dec (tsdn_t * tsdn)
Definition at line 138 of file tsd.c.
{
     atomic_fetch_sub_u32(&tsd_global_slow_count, 1, ATOMIC_RELAXED);
     /* See the note in ..._inc(). */
     tsd_force_recompute(tsdn);
 }
References ATOMIC_RELAXED, and tsd_force_recompute().
tsd_global_slow_inc()
void tsd_global_slow_inc (tsdn_t * tsdn)
Definition at line 125 of file tsd.c.
{
     atomic_fetch_add_u32(&tsd_global_slow_count, 1, ATOMIC_RELAXED);
     /*
      * We unconditionally force a recompute, even if the global slow count
      * was already positive.  If we didn't, then it would be possible for us
      * to return to the user, have the user synchronize externally with some
      * other thread, and then have that other thread not have picked up the
      * update yet (since the original incrementing thread might still be
      * making its way through the tsd list).
      */
     tsd_force_recompute(tsdn);
 }
References ATOMIC_RELAXED, and tsd_force_recompute().
tsd_init_check_recursion()
void* tsd_init_check_recursion (tsd_init_head_t * head, tsd_init_block_t * block)
Definition at line 488 of file tsd.c.
{
     pthread_t self = pthread_self();
     tsd_init_block_t *iter;
     /* Check whether this thread has already inserted into the list. */
     malloc_mutex_lock(TSDN_NULL, &head->lock);
     ql_foreach(iter, &head->blocks, link) {
         if (iter->thread == self) {
             malloc_mutex_unlock(TSDN_NULL, &head->lock);
             return iter->data;
         }
     }
     /* Insert block into list. */
     ql_elm_new(block, link);
     block->thread = self;
     ql_tail_insert(&head->blocks, block, link);
     malloc_mutex_unlock(TSDN_NULL, &head->lock);
     return NULL;
 }
References tsd_init_block_s::data, malloc_mutex_lock(), malloc_mutex_unlock(), NULL, ql_elm_new, ql_foreach, ql_tail_insert, tsd_init_block_s::thread, and TSDN_NULL.
Referenced by tsd_wrapper_get().
tsd_init_finish()
void tsd_init_finish (tsd_init_head_t * head, tsd_init_block_t * block)
Definition at line 509 of file tsd.c.
{
     malloc_mutex_lock(TSDN_NULL, &head->lock);
     ql_remove(&head->blocks, block, link);
     malloc_mutex_unlock(TSDN_NULL, &head->lock);
 }
References malloc_mutex_lock(), malloc_mutex_unlock(), ql_remove, and TSDN_NULL.
Referenced by tsd_wrapper_get().
tsd_local_slow()
static bool tsd_local_slow (tsd_t * tsd) static
Definition at line 145 of file tsd.c.
{
     return !tsd_tcache_enabled_get(tsd)
         || tsd_reentrancy_level_get(tsd) > 0;
 }
Referenced by tsd_state_compute().
tsd_postfork_child()
void tsd_postfork_child (tsd_t * tsd)
Definition at line 527 of file tsd.c.
{
     malloc_mutex_postfork_child(tsd_tsdn(tsd), &tsd_nominal_tsds_lock);
     ql_new(&tsd_nominal_tsds);
     if (tsd_state_get(tsd) <= tsd_state_nominal_max) {
         tsd_add_nominal(tsd);
     }
 }
References malloc_mutex_postfork_child, ql_new, tsd_add_nominal(), tsd_state_get(), tsd_state_nominal_max, and tsd_tsdn().
tsd_postfork_parent()
void tsd_postfork_parent (tsd_t * tsd)
Definition at line 522 of file tsd.c.
{
     malloc_mutex_postfork_parent(tsd_tsdn(tsd), &tsd_nominal_tsds_lock);
 }
References malloc_mutex_postfork_parent, and tsd_tsdn().
tsd_prefork()
void tsd_prefork (tsd_t * tsd)
Definition at line 517 of file tsd.c.
{
     malloc_mutex_prefork(tsd_tsdn(tsd), &tsd_nominal_tsds_lock);
 }
References malloc_mutex_prefork, and tsd_tsdn().
tsd_remove_nominal()
static void tsd_remove_nominal (tsd_t * tsd) static
Definition at line 98 of file tsd.c.
{
     assert(tsd_in_nominal_list(tsd));
     assert(tsd_state_get(tsd) <= tsd_state_nominal_max);
     malloc_mutex_lock(tsd_tsdn(tsd), &tsd_nominal_tsds_lock);
     ql_remove(&tsd_nominal_tsds, tsd, TSD_MANGLE(tcache).tsd_link);
     malloc_mutex_unlock(tsd_tsdn(tsd), &tsd_nominal_tsds_lock);
 }
References assert(), malloc_mutex_lock(), malloc_mutex_unlock(), ql_remove, TSD_MANGLE, tsd_state_get(), tsd_state_nominal_max, and tsd_tsdn().
Referenced by tsd_state_set().
tsd_slow_update()
void tsd_slow_update (tsd_t * tsd)
Definition at line 171 of file tsd.c.
{
     uint8_t old_state;
     do {
         uint8_t new_state = tsd_state_compute(tsd);
         old_state = tsd_atomic_exchange(&tsd->state, new_state,
             ATOMIC_ACQUIRE);
     } while (old_state == tsd_state_nominal_recompute);
 }
References ATOMIC_ACQUIRE, tsd_s::state, tsd_atomic_exchange, tsd_state_compute(), and tsd_state_nominal_recompute.
Referenced by malloc_tsd_boot1(), tsd_fetch_slow(), and tsd_state_set().
tsd_state_compute()
static uint8_t tsd_state_compute (tsd_t * tsd) static
Definition at line 158 of file tsd.c.
{
     if (!tsd_nominal(tsd)) {
         return tsd_state_get(tsd);
     }
     /* We're in *a* nominal state; but which one? */
     if (malloc_slow || tsd_local_slow(tsd) || tsd_global_slow()) {
         return tsd_state_nominal_slow;
     } else {
         return tsd_state_nominal;
     }
 }
References malloc_slow, tsd_global_slow(), tsd_local_slow(), tsd_nominal(), tsd_state_get(), tsd_state_nominal, and tsd_state_nominal_slow.
Referenced by tsd_slow_update().
tsd_state_set()
void tsd_state_set (tsd_t * tsd, uint8_t new_state)
Definition at line 181 of file tsd.c.
{
     /* Only the tsd module can change the state *to* recompute. */
     assert(new_state != tsd_state_nominal_recompute);
     uint8_t old_state = tsd_atomic_load(&tsd->state, ATOMIC_RELAXED);
     if (old_state > tsd_state_nominal_max) {
         /*
          * Not currently in the nominal list, but it might need to be
          * inserted there.
          */
         assert(!tsd_in_nominal_list(tsd));
         tsd_atomic_store(&tsd->state, new_state, ATOMIC_RELAXED);
         if (new_state <= tsd_state_nominal_max) {
             tsd_add_nominal(tsd);
         }
     } else {
         /*
          * We're currently nominal.  If the new state is non-nominal,
          * great; we take ourselves off the list and just enter the new
          * state.
          */
         assert(tsd_in_nominal_list(tsd));
         if (new_state > tsd_state_nominal_max) {
             tsd_remove_nominal(tsd);
             tsd_atomic_store(&tsd->state, new_state,
                 ATOMIC_RELAXED);
         } else {
             /*
              * This is the tricky case.  We're transitioning from
              * one nominal state to another.  The caller can't know
              * about any races that are occuring at the same time,
              * so we always have to recompute no matter what.
              */
             tsd_slow_update(tsd);
         }
     }
 }
References assert(), ATOMIC_RELAXED, tsd_s::state, tsd_add_nominal(), tsd_atomic_load, tsd_atomic_store, tsd_remove_nominal(), tsd_slow_update(), tsd_state_nominal_max, and tsd_state_nominal_recompute.
Referenced by tsd_cleanup(), tsd_fetch_slow(), and tsd_internal_fetch().
Variable Documentation
cleanups
malloc_tsd_cleanup_t cleanups[MALLOC_TSD_CLEANUPS_MAX] static
Definition at line 13 of file tsd.c.
Referenced by malloc_tsd_cleanup_register().
ncleanups
unsigned ncleanups static
Definition at line 12 of file tsd.c.
Referenced by malloc_tsd_boot0(), and malloc_tsd_cleanup_register().
tsd_boot_wrapper
tsd_wrapper_t tsd_boot_wrapper
Initial value:
= {
    false,
    TSD_INITIALIZER
}
Definition at line 49 of file tsd.c.
Referenced by tsd_boot0(), and tsd_boot1().
tsd_booted
bool tsd_booted = false
Definition at line 53 of file tsd.c.
Referenced by tsd_boot0(), tsd_booted_get(), tsd_fetch_slow(), tsd_get(), and tsd_set().
tsd_init_head
tsd_init_head_t tsd_init_head
Initial value:
= {
    ql_head_initializer(blocks),
    MALLOC_MUTEX_INITIALIZER
}
Definition at line 44 of file tsd.c.
Referenced by tsd_wrapper_get().
tsd_tsd
pthread_key_t tsd_tsd
Definition at line 43 of file tsd.c.
Referenced by tsd_boot0(), tsd_cleanup_wrapper(), tsd_set(), tsd_wrapper_get(), and tsd_wrapper_set().