Azerotcore-wotlk: src/server/scripts/Commands/cs_lfg.cpp File Reference
cs_lfg.cpp File Reference
#include "ScriptMgr.h"
#include "Chat.h"
#include "DatabaseEnv.h"
#include "Group.h"
#include "Language.h"
#include "LFGMgr.h"
#include "Player.h"
Classes
class lfg_commandscript
Functions
void GetPlayerInfo (ChatHandler *handler, Player *player)
void AddSC_lfg_commandscript ()
Function Documentation
AddSC_lfg_commandscript()
void AddSC_lfg_commandscript ()
Definition at line 132 of file cs_lfg.cpp.
 {
     new lfg_commandscript();
 }
Referenced by AddCommandsScripts().
GetPlayerInfo()
void GetPlayerInfo (ChatHandler * handler, Player * player)
Definition at line 26 of file cs_lfg.cpp.
 {
     if (!player)
         return;
     ObjectGuid guid = player->GetGUID();
     lfg::LfgDungeonSet dungeons = sLFGMgr->GetSelectedDungeons(guid);
     std::string const& state = lfg::GetStateString(sLFGMgr->GetState(guid));
     handler->PSendSysMessage(LANG_LFG_PLAYER_INFO, player->GetName().c_str(),
                              state.c_str(), uint8(dungeons.size()), lfg::ConcatenateDungeons(dungeons).c_str(),
                              lfg::GetRolesString(sLFGMgr->GetRoles(guid)).c_str(), sLFGMgr->GetComment(guid).c_str());
 }
References lfg::ConcatenateDungeons(), Object::GetGUID(), WorldObject::GetName(), lfg::GetRolesString(), lfg::GetStateString(), LANG_LFG_PLAYER_INFO, ChatHandler::PSendSysMessage(), and sLFGMgr.
Referenced by lfg_commandscript::HandleLfgGroupInfoCommand(), and lfg_commandscript::HandleLfgPlayerInfoCommand().