Azerotcore-wotlk: G3D::NetworkDevice::EthernetAdapter Class Reference
G3D::NetworkDevice::EthernetAdapter Class Reference
Description of an ethernet or wireless ethernet adapter.
#include <NetworkDevice.h>
Public Member Functions
EthernetAdapter ()
void describe (TextOutput &t) const
Public Attributes
std::string hostname
std::string name
uint32 ip
uint32 subnet
uint32 broadcast
uint8 mac [6]
Detailed Description
Description of an ethernet or wireless ethernet adapter.
Definition at line 612 of file NetworkDevice.h.
Constructor & Destructor Documentation
EthernetAdapter()
G3D::NetworkDevice::EthernetAdapter::EthernetAdapter ()
Definition at line 177 of file NetworkDevice.cpp.
{
     name = "";
     ip = 0;
     hostname = "";
     subnet = 0;
     broadcast = 0;
     for (int i = 0; i < 6; ++i) {
         mac[i] = 0;
     }
 }
References broadcast, hostname, ip, mac, name, and subnet.
Member Function Documentation
describe()
void G3D::NetworkDevice::EthernetAdapter::describe (TextOutput & t) const
Produces a text description of this adapter
Definition at line 188 of file NetworkDevice.cpp.
{
     t.writeSymbol("{");
     t.pushIndent();
     t.writeNewline();
     t.writeSymbols("hostname", "=");
     t.writeString(hostname + ";");
     t.writeNewline();
     t.writeSymbols("name", "=");
     t.writeString(name + ";");
     t.writeNewline();
     t.writeSymbols("ip", "=");
     t.writeSymbol("\"" + formatIP(ip) + "\";");
     t.writeNewline();
     t.writeSymbols("subnet", "=");
     t.writeSymbol("\"" + formatIP(subnet) + "\";");
     t.writeNewline();
     t.writeSymbols("broadcast", "=");
     t.writeSymbol("\"" + formatIP(broadcast) + "\";");
     t.writeNewline();
     t.writeSymbols("mac", "=");
     t.writeSymbol("\"" + formatMAC(mac) + "\";");
     t.writeNewline();
     t.popIndent();
     t.writeSymbol("};");
     t.writeNewline();
 }
References G3D::NetworkDevice::formatIP(), G3D::NetworkDevice::formatMAC(), name, G3D::TextOutput::popIndent(), G3D::TextOutput::pushIndent(), G3D::TextOutput::writeNewline(), G3D::TextOutput::writeString(), G3D::TextOutput::writeSymbol(), and G3D::TextOutput::writeSymbols().
Member Data Documentation
broadcast
uint32 G3D::NetworkDevice::EthernetAdapter::broadcast
UDP broadcast address in host byte order.
Definition at line 627 of file NetworkDevice.h.
Referenced by EthernetAdapter().
hostname
std::string G3D::NetworkDevice::EthernetAdapter::hostname
Reverse-DNS of the ip address.
Definition at line 615 of file NetworkDevice.h.
Referenced by EthernetAdapter().
ip
uint32 G3D::NetworkDevice::EthernetAdapter::ip
IP address in host byte order.
Definition at line 621 of file NetworkDevice.h.
Referenced by EthernetAdapter().
mac
uint8 G3D::NetworkDevice::EthernetAdapter::mac[6]
MAC (hardware) address, if known
Definition at line 630 of file NetworkDevice.h.
Referenced by EthernetAdapter().
name
std::string G3D::NetworkDevice::EthernetAdapter::name
Name of the adapter
Definition at line 618 of file NetworkDevice.h.
Referenced by EthernetAdapter().
subnet
uint32 G3D::NetworkDevice::EthernetAdapter::subnet
Subnet mask in host byte order.
Definition at line 624 of file NetworkDevice.h.
Referenced by EthernetAdapter().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/NetworkDevice.h
deps/g3dlite/source/NetworkDevice.cpp