Azerotcore-wotlk: GenericCache< K, T > Class Template Reference
GenericCache< K, T > Class Template Reference
#include <Cache.h>
Public Member Functions
GenericCache ()
void Insert (K key, T *val)
T * Get (K key)
void Clear ()
Static Public Attributes
static const uint32 FlushLimit = 300
Private Attributes
std::map< K, T * > _items
std::mutex mutex
Detailed Description
template<class K, class T>
class GenericCache< K, T >
Definition at line 29 of file Cache.h.
Constructor & Destructor Documentation
GenericCache()
template<class K , class T > GenericCache< K, T >::GenericCache () inline
Definition at line 32 of file Cache.h.
 {}
Member Function Documentation
Clear()
template<class K , class T > void GenericCache< K, T >::Clear () inline
Definition at line 54 of file Cache.h.
     {
         for (typename std::map<K, T*>::iterator itr = _items.begin(); itr != _items.end(); ++itr)
             delete itr->second;
         _items.clear();
     }
References GenericCache< K, T >::_items.
Referenced by CacheClass::Clear(), and GenericCache< K, T >::Insert().
Get()
template<class K , class T > T* GenericCache< K, T >::Get (K key) inline
Definition at line 45 of file Cache.h.
     {
         GUARD_RETURN(mutex, nullptr);
         typename std::map<K, T*>::iterator itr = _items.find(key);
         if (itr != _items.end())
             return itr->second;
         return nullptr;
     }
References GenericCache< K, T >::_items, GUARD_RETURN, and GenericCache< K, T >::mutex.
Referenced by WorldModelHandler::InsertModelGeometry(), DoodadHandler::ProcessInternal(), and WorldModelHandler::ProcessInternal().
Insert()
template<class K , class T > void GenericCache< K, T >::Insert (K key, T * val) inline
Definition at line 36 of file Cache.h.
     {
         std::lock_guard<std::mutex> guard(mutex);
         if (_items.size() > FlushLimit)
             Clear();
         _items[key] = val;
     }
References GenericCache< K, T >::_items, GenericCache< K, T >::Clear(), GenericCache< K, T >::FlushLimit, and GenericCache< K, T >::mutex.
Referenced by WorldModelHandler::InsertModelGeometry(), DoodadHandler::ProcessInternal(), and WorldModelHandler::ProcessInternal().
Member Data Documentation
_items
template<class K , class T > std::map<K, T*> GenericCache< K, T >::_items private
Definition at line 61 of file Cache.h.
Referenced by GenericCache< K, T >::Clear(), GenericCache< K, T >::Get(), and GenericCache< K, T >::Insert().
FlushLimit
template<class K , class T > const uint32 GenericCache< K, T >::FlushLimit = 300 static
Definition at line 34 of file Cache.h.
Referenced by GenericCache< K, T >::Insert().
mutex
template<class K , class T > std::mutex GenericCache< K, T >::mutex private
Definition at line 62 of file Cache.h.
Referenced by GenericCache< K, T >::Get(), and GenericCache< K, T >::Insert().
The documentation for this class was generated from the following file:
src/tools/mesh_extractor/Cache.h