Azerotcore-wotlk: QueryCallback::QueryCallbackData Struct Reference
QueryCallback::QueryCallbackData Struct Reference
Public Member Functions
QueryCallbackData (std::function< void(QueryCallback &, QueryResult)> &&callback)
QueryCallbackData (std::function< void(QueryCallback &, PreparedQueryResult)> &&callback)
QueryCallbackData (QueryCallbackData &&right)
QueryCallbackData & operator= (QueryCallbackData &&right)
~QueryCallbackData ()
Private Member Functions
QueryCallbackData (QueryCallbackData const &)=delete
QueryCallbackData & operator= (QueryCallbackData const &)=delete
Private Attributes
union {
std::function< void(QueryCallback &, QueryResult)> _string
std::function< void(QueryCallback &, PreparedQueryResult)> _prepared
};
bool _isPrepared
Friends
class QueryCallback
template<typename T >
void ConstructActiveMember (T *obj)
template<typename T >
void DestroyActiveMember (T *obj)
template<typename T >
void MoveFrom (T *to, T &&from)
Detailed Description
Definition at line 62 of file QueryCallback.cpp.
Constructor & Destructor Documentation
QueryCallbackData() [1/4]
QueryCallback::QueryCallbackData::QueryCallbackData (std::function< void(QueryCallback &, QueryResult)> && callback) inline
Definition at line 67 of file QueryCallback.cpp.
 : _string(std::move(callback)), _isPrepared(false) { }
QueryCallbackData() [2/4]
QueryCallback::QueryCallbackData::QueryCallbackData (std::function< void(QueryCallback &, PreparedQueryResult)> && callback) inline
Definition at line 68 of file QueryCallback.cpp.
 : _prepared(std::move(callback)), _isPrepared(true) { }
QueryCallbackData() [3/4]
QueryCallback::QueryCallbackData::QueryCallbackData (QueryCallbackData && right) inline
Definition at line 69 of file QueryCallback.cpp.
     {
         _isPrepared = right._isPrepared;
         ConstructActiveMember(this);
         MoveFrom(this, std::move(right));
     }
References _isPrepared, ConstructActiveMember, MoveFrom, and align::right.
~QueryCallbackData()
QueryCallback::QueryCallbackData::~QueryCallbackData () inline
Definition at line 89 of file QueryCallback.cpp.
 { DestroyActiveMember(this); }
References DestroyActiveMember.
QueryCallbackData() [4/4]
QueryCallback::QueryCallbackData::QueryCallbackData (QueryCallbackData const &) private delete
Member Function Documentation
operator=() [1/2]
QueryCallbackData& QueryCallback::QueryCallbackData::operator= (QueryCallbackData && right) inline
Definition at line 75 of file QueryCallback.cpp.
     {
         if (this != &right)
         {
             if (_isPrepared != right._isPrepared)
             {
                 DestroyActiveMember(this);
                 _isPrepared = right._isPrepared;
                 ConstructActiveMember(this);
             }
             MoveFrom(this, std::move(right));
         }
         return *this;
     }
References _isPrepared, ConstructActiveMember, DestroyActiveMember, MoveFrom, and align::right.
operator=() [2/2]
QueryCallbackData& QueryCallback::QueryCallbackData::operator= (QueryCallbackData const &) private delete
Friends And Related Function Documentation
ConstructActiveMember
template<typename T > void ConstructActiveMember (T * obj) friend
Definition at line 34 of file QueryCallback.cpp.
 {
     if (!obj->_isPrepared)
         Construct(obj->_string);
     else
         Construct(obj->_prepared);
 }
Referenced by operator=(), and QueryCallbackData().
DestroyActiveMember
template<typename T > void DestroyActiveMember (T * obj) friend
Definition at line 43 of file QueryCallback.cpp.
 {
     if (!obj->_isPrepared)
         Destroy(obj->_string);
     else
         Destroy(obj->_prepared);
 }
Referenced by operator=(), and ~QueryCallbackData().
MoveFrom
template<typename T > void MoveFrom (T * to, T && from) friend
Definition at line 52 of file QueryCallback.cpp.
 {
     ASSERT(to->_isPrepared == from._isPrepared);
     if (!to->_isPrepared)
         to->_string = std::move(from._string);
     else
         to->_prepared = std::move(from._prepared);
 }
Referenced by operator=(), and QueryCallbackData().
QueryCallback
friend class QueryCallback friend
Definition at line 65 of file QueryCallback.cpp.
Member Data Documentation
union { ... }
_isPrepared
bool QueryCallback::QueryCallbackData::_isPrepared private
Definition at line 104 of file QueryCallback.cpp.
Referenced by operator=(), and QueryCallbackData().
_prepared
std::function<void(QueryCallback&, PreparedQueryResult)> QueryCallback::QueryCallbackData::_prepared
Definition at line 102 of file QueryCallback.cpp.
Referenced by QueryCallback::InvokeIfReady().
_string
std::function<void(QueryCallback&, QueryResult)> QueryCallback::QueryCallbackData::_string
Definition at line 101 of file QueryCallback.cpp.
Referenced by QueryCallback::InvokeIfReady().
The documentation for this struct was generated from the following file:
src/server/database/Database/QueryCallback.cpp