Azerotcore-wotlk: Acore::Runnable Class Reference
Acore::Runnable Class Reference abstract
#include <Threading.h>
Public Member Functions
virtual ~Runnable ()=default
virtual void run ()=0
void incReference ()
void decReference ()
Private Attributes
std::atomic_long m_refs
Detailed Description
Definition at line 26 of file Threading.h.
Constructor & Destructor Documentation
~Runnable()
virtual Acore::Runnable::~Runnable () virtual default
Member Function Documentation
decReference()
void Acore::Runnable::decReference () inline
Definition at line 33 of file Threading.h.
         {
             if (!--m_refs)
             {
                 delete this;
             }
         }
References m_refs.
Referenced by Acore::Thread::~Thread().
incReference()
void Acore::Runnable::incReference () inline
Definition at line 32 of file Threading.h.
 { ++m_refs; }
References m_refs.
Referenced by Acore::Thread::Thread().
run()
virtual void Acore::Runnable::run () pure virtual
Referenced by Acore::Thread::ThreadTask().
Member Data Documentation
m_refs
std::atomic_long Acore::Runnable::m_refs private
Definition at line 41 of file Threading.h.
Referenced by decReference(), and incReference().
The documentation for this class was generated from the following file:
src/common/Threading/Threading.h