Azerotcore-wotlk: ThreatMgr Class Reference
ThreatMgr Class Reference
#include <ThreatMgr.h>
Public Member Functions
ThreatMgr (Unit *owner)
~ThreatMgr ()
void clearReferences ()
void addThreat (Unit *victim, float threat, SpellSchoolMask schoolMask=SPELL_SCHOOL_MASK_NORMAL, SpellInfo const *threatSpell=nullptr)
void doAddThreat (Unit *victim, float threat)
void modifyThreatPercent (Unit *victim, int32 percent)
float getThreat (Unit *victim, bool alsoSearchOfflineList=false)
float getThreatWithoutTemp (Unit *victim, bool alsoSearchOfflineList=false)
bool isThreatListEmpty () const
bool areThreatListsEmpty () const
void processThreatEvent (ThreatRefStatusChangeEvent *threatRefStatusChangeEvent)
bool isNeedUpdateToClient (uint32 time)
HostileReference * getCurrentVictim () const
Unit * GetOwner () const
Unit * getHostilTarget ()
void tauntApply (Unit *taunter)
void tauntFadeOut (Unit *taunter)
void setCurrentVictim (HostileReference *hostileRef)
void setDirty (bool isDirty)
void resetAllAggro ()
template<class PREDICATE >
void resetAggro (PREDICATE predicate)
ThreatContainer::StorageType const & getThreatList () const
ThreatContainer::StorageType const & getOfflineThreatList () const
ThreatContainer & getOnlineContainer ()
ThreatContainer & getOfflineContainer ()
Private Member Functions
void _addThreat (Unit *victim, float threat)
Private Attributes
HostileReference * iCurrentVictim
Unit * iOwner
uint32 iUpdateTimer
ThreatContainer iThreatContainer
ThreatContainer iThreatOfflineContainer
Friends
class HostileReference
Detailed Description
Definition at line 191 of file ThreatMgr.h.
Constructor & Destructor Documentation
ThreatMgr()
ThreatMgr::ThreatMgr (Unit * owner) explicit
Definition at line 405 of file ThreatMgr.cpp.
                                 : iCurrentVictim(nullptr), iOwner(owner), iUpdateTimer(THREAT_UPDATE_INTERVAL)
 {
 }
~ThreatMgr()
ThreatMgr::~ThreatMgr () inline
Definition at line 198 of file ThreatMgr.h.
 { clearReferences(); }
References clearReferences().
Member Function Documentation
_addThreat()
void ThreatMgr::_addThreat (Unit * victim, float threat) private
Definition at line 448 of file ThreatMgr.cpp.
 {
     HostileReference* ref = iThreatContainer.addThreat(victim, threat);
     // Ref is not in the online refs, search the offline refs next
     if (!ref)
         ref = iThreatOfflineContainer.addThreat(victim, threat);
     if (!ref) // there was no ref => create a new one
     {
         // threat has to be 0 here
         HostileReference* hostileRef = new HostileReference(victim, this, 0);
         iThreatContainer.addReference(hostileRef);
         hostileRef->addThreat(threat); // now we add the real threat
         if (victim->GetTypeId() == TYPEID_PLAYER && victim->ToPlayer()->IsGameMaster())
             hostileRef->setOnlineOfflineState(false); // GM is always offline
     }
 }
References ThreatContainer::addReference(), HostileReference::addThreat(), ThreatContainer::addThreat(), Object::GetTypeId(), HostileReference, Player::IsGameMaster(), iThreatContainer, iThreatOfflineContainer, HostileReference::setOnlineOfflineState(), Object::ToPlayer(), and TYPEID_PLAYER.
Referenced by doAddThreat().
addThreat()
void ThreatMgr::addThreat (Unit * victim, float threat, SpellSchoolMask schoolMask = SPELL_SCHOOL_MASK_NORMAL, SpellInfo const * threatSpell = nullptr)
Definition at line 421 of file ThreatMgr.cpp.
 {
     if (!ThreatCalcHelper::isValidProcess(victim, GetOwner(), threatSpell))
         return;
     doAddThreat(victim, ThreatCalcHelper::calcThreat(victim, iOwner, threat, schoolMask, threatSpell));
 }
References ThreatCalcHelper::calcThreat(), doAddThreat(), GetOwner(), iOwner, and ThreatCalcHelper::isValidProcess().
Referenced by HostileReference::addThreat(), Unit::AddThreat(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::SpellHitTarget(), boss_gothik::boss_gothikAI::UpdateAI(), and boss_netherspite::boss_netherspiteAI::UpdatePortals().
areThreatListsEmpty()
bool ThreatMgr::areThreatListsEmpty () const inline
Definition at line 213 of file ThreatMgr.h.
 { return iThreatContainer.empty() && iThreatOfflineContainer.empty(); }
References ThreatContainer::empty(), iThreatContainer, and iThreatOfflineContainer.
clearReferences()
void ThreatMgr::clearReferences ()
Definition at line 411 of file ThreatMgr.cpp.
 {
     iThreatContainer.clearReferences();
     iThreatOfflineContainer.clearReferences();
     iCurrentVictim = nullptr;
     iUpdateTimer = THREAT_UPDATE_INTERVAL;
 }
References ThreatContainer::clearReferences(), iCurrentVictim, iThreatContainer, iThreatOfflineContainer, iUpdateTimer, and THREAT_UPDATE_INTERVAL.
Referenced by boss_eadric::boss_eadricAI::DamageTaken(), boss_paletress::boss_paletressAI::DamageTaken(), Unit::DeleteThreatList(), spell_halion_twilight_phasing::spell_halion_twilight_phasing_AuraScript::OnApply(), spell_halion_twilight_phasing::spell_halion_twilight_phasing_AuraScript::OnRemove(), and ~ThreatMgr().
doAddThreat()
void ThreatMgr::doAddThreat (Unit * victim, float threat)
Definition at line 429 of file ThreatMgr.cpp.
 {
     uint32 redirectThreadPct = victim->GetRedirectThreatPercent();
     // must check > 0.0f, otherwise dead loop
     if (threat > 0.0f && redirectThreadPct)
     {
         if (Unit* redirectTarget = victim->GetRedirectThreatTarget())
         {
             float redirectThreat = CalculatePct(threat, redirectThreadPct);
             threat -= redirectThreat;
             if (ThreatCalcHelper::isValidProcess(redirectTarget, GetOwner()))
                 _addThreat(redirectTarget, redirectThreat);
         }
     }
     _addThreat(victim, threat);
 }
References _addThreat(), CalculatePct(), GetOwner(), Unit::GetRedirectThreatPercent(), Unit::GetRedirectThreatTarget(), and ThreatCalcHelper::isValidProcess().
Referenced by addThreat(), Spell::EffectTaunt(), and HostileRefMgr::threatAssist().
getCurrentVictim()
HostileReference* ThreatMgr::getCurrentVictim () const inline
Definition at line 219 of file ThreatMgr.h.
 { return iCurrentVictim; }
References iCurrentVictim.
Referenced by getHostilTarget(), processThreatEvent(), and tauntApply().
getHostilTarget()
Unit * ThreatMgr::getHostilTarget ()
Definition at line 475 of file ThreatMgr.cpp.
 {
     iThreatContainer.update();
     HostileReference* nextVictim = iThreatContainer.selectNextVictim(GetOwner()->ToCreature(), getCurrentVictim());
     setCurrentVictim(nextVictim);
     return getCurrentVictim() != nullptr ? getCurrentVictim()->getTarget() : nullptr;
 }
References getCurrentVictim(), GetOwner(), Reference< TO, FROM >::getTarget(), iThreatContainer, ThreatContainer::selectNextVictim(), setCurrentVictim(), and ThreatContainer::update().
Referenced by boss_veknilash::boss_veknilashAI::CastSpellOnBug(), and Creature::SelectVictim().
getOfflineContainer()
ThreatContainer& ThreatMgr::getOfflineContainer () inline
Definition at line 257 of file ThreatMgr.h.
 { return iThreatOfflineContainer; }
References iThreatOfflineContainer.
getOfflineThreatList()
ThreatContainer::StorageType const& ThreatMgr::getOfflineThreatList () const inline
Definition at line 255 of file ThreatMgr.h.
 { return iThreatOfflineContainer.getThreatList(); }
References ThreatContainer::getThreatList(), and iThreatOfflineContainer.
Referenced by debug_commandscript::HandleDebugThreatListCommand(), and Unit::SetPhaseMask().
getOnlineContainer()
ThreatContainer& ThreatMgr::getOnlineContainer () inline
Definition at line 256 of file ThreatMgr.h.
 { return iThreatContainer; }
References iThreatContainer.
Referenced by Spell::EffectTaunt(), boss_priestess_lackey_commonAI::RecalculateThreat(), boss_faction_championsAI::RecalculateThreat(), and npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI::SpellHit().
GetOwner()
Unit* ThreatMgr::GetOwner () const inline
Definition at line 221 of file ThreatMgr.h.
 { return iOwner; }
References iOwner.
Referenced by addThreat(), HostileRefMgr::deleteReference(), HostileRefMgr::deleteReferencesForFaction(), HostileRefMgr::deleteReferencesOutOfRange(), doAddThreat(), getHostilTarget(), debug_commandscript::HandleDebugHostileRefListCommand(), npc_pet_mage_mirror_image::InitializeAI(), processThreatEvent(), HostileRefMgr::setOnlineOfflineState(), Unit::SetPhaseMask(), HostileRefMgr::threatAssist(), and Map::Update().
getThreat()
float ThreatMgr::getThreat (Unit * victim, bool alsoSearchOfflineList = false)
Definition at line 485 of file ThreatMgr.cpp.
 {
     float threat = 0.0f;
     HostileReference* ref = iThreatContainer.getReferenceByTarget(victim);
     if (!ref && alsoSearchOfflineList)
         ref = iThreatOfflineContainer.getReferenceByTarget(victim);
     if (ref)
         threat = ref->getThreat();
     return threat;
 }
References ThreatContainer::getReferenceByTarget(), HostileReference::getThreat(), iThreatContainer, and iThreatOfflineContainer.
Referenced by ScriptedAI::DoGetThreat(), Spell::EffectTaunt(), processThreatEvent(), boss_priestess_lackey_commonAI::RecalculateThreat(), boss_faction_championsAI::RecalculateThreat(), tauntApply(), and boss_thaddius_summon::boss_thaddius_summonAI::UpdateAI().
getThreatList()
ThreatContainer::StorageType const& ThreatMgr::getThreatList () const inline
Definition at line 254 of file ThreatMgr.h.
 { return iThreatContainer.getThreatList(); }
References ThreatContainer::getThreatList(), and iThreatContainer.
Referenced by boss_archimonde::boss_archimondeAI::CanUseFingerOfDeath(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::DamageTaken(), UnitAI::DoAddAuraToAllHostilePlayers(), boss_archimonde::boss_archimondeAI::DoCastProtection(), UnitAI::DoCastToAllHostilePlayers(), boss_faction_championsAI::EnemiesInRange(), boss_malchezaar::boss_malchezaarAI::EnfeebleHealthEffect(), boss_supremus::boss_supremusAI::FindHatefulStrikeTarget(), boss_shade_of_aran::boss_aranAI::FlameWreathEffect(), SmartScript::GetTargets(), debug_commandscript::HandleDebugThreatListCommand(), Unit::IsInCombatWith(), StoneGripTargetSelector::operator()(), SmartScript::ProcessAction(), boss_priestess_lackey_commonAI::RecalculateThreat(), boss_faction_championsAI::RecalculateThreat(), boss_faction_championsAI::SelectEnemyCaster(), UnitAI::SelectTarget(), UnitAI::SelectTargetList(), npc_scholomance_occultist::npc_scholomance_occultistAI::SelectUnitCasting(), Unit::SendChangeCurrentVictimOpcode(), Unit::SendThreatListUpdate(), Unit::SetPhaseMask(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::SpellHitTarget(), BossAI::TeleportCheaters(), boss_yazzai::boss_yazzaiAI::UpdateAI(), boss_azuregos::boss_azuregosAI::UpdateAI(), boss_moam::boss_moamAI::UpdateAI(), boss_cthun::cthunAI::UpdateAI(), boss_taldaram::boss_taldaramAI::UpdateAI(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::UpdateAI(), boss_kelthuzad::boss_kelthuzadAI::UpdateAI(), boss_patchwerk::boss_patchwerkAI::UpdateAI(), boss_sapphiron::boss_sapphironAI::UpdateAI(), boss_blackheart_the_inciter::boss_blackheart_the_inciterAI::UpdateAI(), boss_murmur::boss_murmurAI::UpdateAI(), boss_the_lurker_below::boss_the_lurker_belowAI::UpdateAI(), boss_alar::boss_alarAI::UpdateAI(), npc_phase_hunter::npc_phase_hunterAI::UpdateAI(), and HostileRefMgr::UpdateVisibility().
getThreatWithoutTemp()
float ThreatMgr::getThreatWithoutTemp (Unit * victim, bool alsoSearchOfflineList = false)
Definition at line 498 of file ThreatMgr.cpp.
 {
     float threat = 0.0f;
     HostileReference* ref = iThreatContainer.getReferenceByTarget(victim);
     if (!ref && alsoSearchOfflineList)
         ref = iThreatOfflineContainer.getReferenceByTarget(victim);
     if (ref)
         threat = ref->getThreat() - ref->getTempThreatModifier();
     return threat;
 }
References ThreatContainer::getReferenceByTarget(), HostileReference::getTempThreatModifier(), HostileReference::getThreat(), iThreatContainer, and iThreatOfflineContainer.
Referenced by boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::UpdateAI().
isNeedUpdateToClient()
bool ThreatMgr::isNeedUpdateToClient (uint32 time)
Definition at line 596 of file ThreatMgr.cpp.
 {
     if (isThreatListEmpty())
         return false;
     if (time >= iUpdateTimer)
     {
         iUpdateTimer = THREAT_UPDATE_INTERVAL;
         return true;
     }
     iUpdateTimer -= time;
     return false;
 }
References isThreatListEmpty(), iUpdateTimer, and THREAT_UPDATE_INTERVAL.
isThreatListEmpty()
bool ThreatMgr::isThreatListEmpty () const inline
Definition at line 212 of file ThreatMgr.h.
 { return iThreatContainer.empty(); }
References ThreatContainer::empty(), and iThreatContainer.
Referenced by Unit::DeleteThreatList(), ScriptedAI::DoResetThreat(), StartMovementEvent::Execute(), isNeedUpdateToClient(), Creature::SelectVictim(), Unit::TauntFadeOut(), npc_raging_spirit::npc_raging_spiritAI::UpdateAI(), and CreatureAI::UpdateVictim().
modifyThreatPercent()
void ThreatMgr::modifyThreatPercent (Unit * victim, int32 percent)
Definition at line 468 of file ThreatMgr.cpp.
 {
     iThreatContainer.modifyThreatPercent(victim, percent);
 }
References iThreatContainer, and ThreatContainer::modifyThreatPercent().
Referenced by ScriptedAI::DoModifyThreatPercent(), Spell::EffectModifyThreatPercent(), Unit::HandleProcTriggerSpell(), spell_gurtogg_eject::spell_gurtogg_eject_SpellScript::HandleScriptEffect(), SmartScript::ProcessAction(), boss_priestess_lackey_commonAI::RecalculateThreat(), boss_faction_championsAI::RecalculateThreat(), and boss_thaddius_summon::boss_thaddius_summonAI::UpdateAI().
processThreatEvent()
void ThreatMgr::processThreatEvent (ThreatRefStatusChangeEvent * threatRefStatusChangeEvent)
Definition at line 545 of file ThreatMgr.cpp.
 {
     threatRefStatusChangeEvent->setThreatMgr(this);     // now we can set the threat manager
     HostileReference* hostilRef = threatRefStatusChangeEvent->getReference();
     switch (threatRefStatusChangeEvent->getType())
     {
         case UEV_THREAT_REF_THREAT_CHANGE:
             if ((getCurrentVictim() == hostilRef && threatRefStatusChangeEvent->getFValue() < 0.0f) ||
                     (getCurrentVictim() != hostilRef && threatRefStatusChangeEvent->getFValue() > 0.0f))
                 setDirty(true);                             // the order in the threat list might have changed
             break;
         case UEV_THREAT_REF_ONLINE_STATUS:
             if (!hostilRef->isOnline())
             {
                 if (hostilRef == getCurrentVictim())
                 {
                     setCurrentVictim(nullptr);
                     setDirty(true);
                 }
                 if (GetOwner() && GetOwner()->IsInWorld())
                     if (Unit* target = ObjectAccessor::GetUnit(*GetOwner(), hostilRef->getUnitGuid()))
                         if (GetOwner()->IsInMap(target))
                             GetOwner()->SendRemoveFromThreatListOpcode(hostilRef);
                 iThreatContainer.remove(hostilRef);
                 iThreatOfflineContainer.addReference(hostilRef);
             }
             else
             {
                 if (getCurrentVictim() && hostilRef->getThreat() > (1.1f * getCurrentVictim()->getThreat()))
                     setDirty(true);
                 iThreatContainer.addReference(hostilRef);
                 iThreatOfflineContainer.remove(hostilRef);
             }
             break;
         case UEV_THREAT_REF_REMOVE_FROM_LIST:
             if (hostilRef == getCurrentVictim())
             {
                 setCurrentVictim(nullptr);
                 setDirty(true);
             }
             iOwner->SendRemoveFromThreatListOpcode(hostilRef);
             if (hostilRef->isOnline())
                 iThreatContainer.remove(hostilRef);
             else
                 iThreatOfflineContainer.remove(hostilRef);
             break;
     }
 }
References ThreatContainer::addReference(), getCurrentVictim(), ThreatRefStatusChangeEvent::getFValue(), GetOwner(), ThreatRefStatusChangeEvent::getReference(), HostileReference::getThreat(), getThreat(), UnitBaseEvent::getType(), ObjectAccessor::GetUnit(), HostileReference::getUnitGuid(), iOwner, HostileReference::isOnline(), iThreatContainer, iThreatOfflineContainer, ThreatContainer::remove(), Unit::SendRemoveFromThreatListOpcode(), setCurrentVictim(), setDirty(), ThreatRefStatusChangeEvent::setThreatMgr(), UEV_THREAT_REF_ONLINE_STATUS, UEV_THREAT_REF_REMOVE_FROM_LIST, and UEV_THREAT_REF_THREAT_CHANGE.
Referenced by HostileReference::fireStatusChanged().
resetAggro()
template<class PREDICATE > void ThreatMgr::resetAggro (PREDICATE predicate) inline
Definition at line 236 of file ThreatMgr.h.
     {
         ThreatContainer::StorageType& threatList = iThreatContainer.iThreatList;
         if (threatList.empty())
             return;
         for (auto ref : threatList)
         {
             if (predicate(ref->getTarget()))
             {
                 ref->setThreat(0);
                 setDirty(true);
             }
         }
     }
References iThreatContainer, ThreatContainer::iThreatList, and setDirty().
Referenced by boss_gothik::boss_gothikAI::UpdateAI().
resetAllAggro()
void ThreatMgr::resetAllAggro ()
Definition at line 611 of file ThreatMgr.cpp.
 {
     ThreatContainer::StorageType& threatList = iThreatContainer.iThreatList;
     if (threatList.empty())
         return;
     for (ThreatContainer::StorageType::iterator itr = threatList.begin(); itr != threatList.end(); ++itr)
         (*itr)->setThreat(0);
     setDirty(true);
 }
References iThreatContainer, ThreatContainer::iThreatList, and setDirty().
Referenced by npc_vengeful_shade::npc_vengeful_shadeAI::AttackStart(), boss_thorim_start_npcs::boss_thorim_start_npcsAI::DamageTaken(), ScriptedAI::DoResetThreat(), spell_karazhan_blink::spell_karazhan_blink_SpellScript::HandleDummy(), spell_pursue::spell_pursue_SpellScript::HandleScript(), spell_leotheras_whirlwind::spell_leotheras_whirlwind_SpellScript::HandleScriptEffect(), npc_pet_mage_mirror_image::MySelectNextTarget(), npc_ulduar_iron_construct::npc_ulduar_iron_constructAI::SpellHit(), npc_toc5_grand_champion_minion::npc_toc5_grand_champion_minionAI::UpdateAI(), boss_grand_champion::boss_grand_championAI::UpdateAI(), boss_tharon_ja::boss_tharon_jaAI::UpdateAI(), boss_eck::boss_eckAI::UpdateAI(), npc_frozen_orb::npc_frozen_orbAI::UpdateAI(), and boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI().
setCurrentVictim()
void ThreatMgr::setCurrentVictim (HostileReference * hostileRef)
Definition at line 532 of file ThreatMgr.cpp.
 {
     if (pHostileReference && pHostileReference != iCurrentVictim)
     {
         iOwner->SendChangeCurrentVictimOpcode(pHostileReference);
     }
     iCurrentVictim = pHostileReference;
 }
References iCurrentVictim, iOwner, and Unit::SendChangeCurrentVictimOpcode().
Referenced by Spell::EffectTaunt(), getHostilTarget(), and processThreatEvent().
setDirty()
void ThreatMgr::setDirty (bool isDirty) inline
Definition at line 230 of file ThreatMgr.h.
 { iThreatContainer.setDirty(isDirty); }
References iThreatContainer, and ThreatContainer::setDirty().
Referenced by processThreatEvent(), resetAggro(), and resetAllAggro().
tauntApply()
void ThreatMgr::tauntApply (Unit * taunter)
Definition at line 511 of file ThreatMgr.cpp.
 {
     HostileReference* ref = iThreatContainer.getReferenceByTarget(taunter);
     if (getCurrentVictim() && ref && (ref->getThreat() < getCurrentVictim()->getThreat()))
     {
         if (ref->getTempThreatModifier() == 0.0f) // Ok, temp threat is unused
             ref->setTempThreat(getCurrentVictim()->getThreat());
     }
 }
References getCurrentVictim(), ThreatContainer::getReferenceByTarget(), HostileReference::getTempThreatModifier(), HostileReference::getThreat(), getThreat(), iThreatContainer, and HostileReference::setTempThreat().
tauntFadeOut()
void ThreatMgr::tauntFadeOut (Unit * taunter)
Definition at line 523 of file ThreatMgr.cpp.
 {
     HostileReference* ref = iThreatContainer.getReferenceByTarget(taunter);
     if (ref)
         ref->resetTempThreat();
 }
References ThreatContainer::getReferenceByTarget(), iThreatContainer, and HostileReference::resetTempThreat().
Friends And Related Function Documentation
HostileReference
friend class HostileReference friend
Definition at line 194 of file ThreatMgr.h.
Referenced by _addThreat().
Member Data Documentation
iCurrentVictim
HostileReference* ThreatMgr::iCurrentVictim private
Definition at line 261 of file ThreatMgr.h.
Referenced by clearReferences(), getCurrentVictim(), and setCurrentVictim().
iOwner
Unit* ThreatMgr::iOwner private
Definition at line 262 of file ThreatMgr.h.
Referenced by addThreat(), GetOwner(), processThreatEvent(), and setCurrentVictim().
iThreatContainer
ThreatContainer ThreatMgr::iThreatContainer private
Definition at line 264 of file ThreatMgr.h.
Referenced by _addThreat(), areThreatListsEmpty(), clearReferences(), getHostilTarget(), getOnlineContainer(), getThreat(), getThreatList(), getThreatWithoutTemp(), isThreatListEmpty(), modifyThreatPercent(), processThreatEvent(), resetAggro(), resetAllAggro(), setDirty(), tauntApply(), and tauntFadeOut().
iThreatOfflineContainer
ThreatContainer ThreatMgr::iThreatOfflineContainer private
Definition at line 265 of file ThreatMgr.h.
Referenced by _addThreat(), areThreatListsEmpty(), clearReferences(), getOfflineContainer(), getOfflineThreatList(), getThreat(), getThreatWithoutTemp(), and processThreatEvent().
iUpdateTimer
uint32 ThreatMgr::iUpdateTimer private
Definition at line 263 of file ThreatMgr.h.
Referenced by clearReferences(), and isNeedUpdateToClient().
The documentation for this class was generated from the following files:
src/server/game/Combat/ThreatMgr.h
src/server/game/Combat/ThreatMgr.cpp