Azerotcore-wotlk: src/tools/vmap4_extractor/adtfile.h File Reference
adtfile.h File Reference
#include "mpq_libmpq04.h"
#include "wmo.h"
#include "model.h"
Classes
struct svec
struct vec
struct triangle
struct Cell
struct chunk
struct mcell
struct MapChunkHeader
struct ADT::MDDF
struct ADT::MODF
class ADTFile
Namespaces
ADT
Macros
#define TILESIZE (533.33333f)
#define CHUNKSIZE ((TILESIZE) / 16.0f)
#define UNITSIZE (CHUNKSIZE / 8.0f)
Functions
const char * GetPlainName (const char *FileName)
char * GetPlainName (char *FileName)
char * GetExtension (char *FileName)
void fixnamen (char *name, size_t len)
void fixname2 (char *name, size_t len)
Macro Definition Documentation
CHUNKSIZE
#define CHUNKSIZE ((TILESIZE) / 16.0f)
Definition at line 26 of file adtfile.h.
TILESIZE
#define TILESIZE (533.33333f)
Definition at line 25 of file adtfile.h.
UNITSIZE
#define UNITSIZE (CHUNKSIZE / 8.0f)
Definition at line 27 of file adtfile.h.
Function Documentation
fixname2()
void fixname2 (char * name, size_t len)
Definition at line 63 of file adtfile.cpp.
 {
     if (len < 3)
         return;
     for (size_t i = 0; i < len - 3; i++)
         if (name[i] == ' ')
             name[i] = '_';
 }
Referenced by ExtractGameobjectModels(), Doodad::ExtractSet(), ExtractSingleModel(), ExtractSingleWmo(), ADTFile::init(), WDTFile::init(), and WMORoot::open().
fixnamen()
void fixnamen (char * name, size_t len)
Definition at line 45 of file adtfile.cpp.
 {
     if (len < 3)
         return;
     for (size_t i = 0; i < len - 3; i++)
     {
         if (i > 0 && name[i] >= 'A' && name[i] <= 'Z' && isalpha(name[i - 1]))
             name[i] |= 0x20;
         else if ((i == 0 || !isalpha(name[i - 1])) && name[i] >= 'a' && name[i] <= 'z')
             name[i] &= ~0x20;
     }
     //extension in lowercase
     for (size_t i = len - 3; i < len; i++)
         name[i] |= 0x20;
 }
Referenced by ExtractGameobjectModels(), Doodad::ExtractSet(), ExtractSingleModel(), ExtractSingleWmo(), ADTFile::init(), WDTFile::init(), and WMORoot::open().
GetExtension()
char* GetExtension (char * FileName)
Definition at line 73 of file adtfile.cpp.
 {
     if (char* szTemp = strrchr(FileName, '.'))
         return szTemp;
     return nullptr;
 }
Referenced by ExtractGameobjectModels().
GetPlainName() [1/2]
char* GetPlainName (char * FileName)
Definition at line 36 of file adtfile.cpp.
 {
     char* szTemp;
     if ((szTemp = strrchr(FileName, '\\')) != nullptr)
         FileName = szTemp + 1;
     return FileName;
 }
GetPlainName() [2/2]
const char* GetPlainName (const char * FileName)
Definition at line 27 of file adtfile.cpp.
 {
     const char* szTemp;
     if ((szTemp = strrchr(FileName, '\\')) != nullptr)
         FileName = szTemp + 1;
     return FileName;
 }
Referenced by ExtractGameobjectModels(), Doodad::ExtractSet(), ExtractSingleModel(), ExtractSingleWmo(), ADTFile::init(), and WMORoot::open().