Azerotcore-wotlk: go_troll_cage::go_troll_cageAI Struct Reference
go_troll_cage::go_troll_cageAI Struct Reference
Public Member Functions
go_troll_cageAI (GameObject *go)
bool GossipHello (Player *, bool reportUse) override
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void UpdateAI (uint32)
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32)
virtual ObjectGuid GetGUID (int32) const
virtual bool GossipSelect (Player *, uint32, uint32)
virtual bool GossipSelectCode (Player *, uint32, uint32, char const *)
virtual bool QuestAccept (Player *, Quest const *)
virtual bool QuestReward (Player *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *)
virtual void Destroyed (Player *, uint32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void OnGameEvent (bool, uint16)
virtual void OnStateChanged (uint32, Unit *)
virtual void EventInform (uint32)
virtual void SpellHit (Unit *, const SpellInfo *)
virtual bool CanBeSeen (Player const *)
Public Attributes
InstanceScript * instance
Private Member Functions
void initBlyCrewMember (uint32 entry, float x, float y, float z)
Additional Inherited Members
Static Public Member Functions inherited from GameObjectAI
static int Permissible (GameObject const *go)
Protected Attributes inherited from GameObjectAI
GameObject *const me
Detailed Description
Definition at line 249 of file zulfarrak.cpp.
Constructor & Destructor Documentation
go_troll_cageAI()
go_troll_cage::go_troll_cageAI::go_troll_cageAI (GameObject * go) inline
Definition at line 251 of file zulfarrak.cpp.
 : GameObjectAI(go), instance(go->GetInstanceScript()) { }
Member Function Documentation
GossipHello()
bool go_troll_cage::go_troll_cageAI::GossipHello (Player * , bool reportUse) inline override virtual
Reimplemented from GameObjectAI.
Definition at line 255 of file zulfarrak.cpp.
         {
             if (reportUse)
             {
                 return true;
             }
             instance->SetData(DATA_PYRAMID, PYRAMID_CAGES_OPEN);
             //set bly & co to aggressive & start moving to top of stairs
             initBlyCrewMember(NPC_BLY, 1884.99f, 1263, 41.52f);
             initBlyCrewMember(NPC_RAVEN, 1882.5f, 1263, 41.52f);
             initBlyCrewMember(NPC_ORO, 1886.47f, 1270.68f, 41.68f);
             initBlyCrewMember(NPC_WEEGLI, 1890, 1263, 41.52f);
             initBlyCrewMember(NPC_MURTA, 1891.19f, 1272.03f, 41.60f);
             return false;
         }
References DATA_PYRAMID, initBlyCrewMember(), instance, NPC_BLY, NPC_MURTA, NPC_ORO, NPC_RAVEN, NPC_WEEGLI, PYRAMID_CAGES_OPEN, and ZoneScript::SetData().
initBlyCrewMember()
void go_troll_cage::go_troll_cageAI::initBlyCrewMember (uint32 entry, float x, float y, float z) inline private
Definition at line 274 of file zulfarrak.cpp.
         {
             if (Creature* crew = ObjectAccessor::GetCreature(*me, instance->GetGuidData(entry)))
             {
                 crew->SetReactState(REACT_AGGRESSIVE);
                 crew->SetWalk(true);
                 crew->SetHomePosition(x, y, z, 4.78f);
                 crew->GetMotionMaster()->MovePoint(1, { x, y, z, 4.78f });
                 crew->SetFaction(FACTION_ESCORT_N_NEUTRAL_ACTIVE);
                 switch (entry)
                 {
                     case NPC_BLY:
                     case NPC_WEEGLI:
                         crew->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
                         break;
                     default:
                         break;
                 }
             }
         }
References FACTION_ESCORT_N_NEUTRAL_ACTIVE, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), instance, GameObjectAI::me, NPC_BLY, NPC_WEEGLI, REACT_AGGRESSIVE, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
Referenced by GossipHello().
Member Data Documentation
instance
InstanceScript* go_troll_cage::go_troll_cageAI::instance
Definition at line 253 of file zulfarrak.cpp.
Referenced by GossipHello(), and initBlyCrewMember().
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/ZulFarrak/zulfarrak.cpp