Azerotcore-wotlk: deps/recastnavigation/Detour/Source/DetourNode.cpp File Reference
DetourNode.cpp File Reference
#include "DetourNode.h"
#include "DetourAlloc.h"
#include "DetourAssert.h"
#include "DetourCommon.h"
#include <string.h>
Functions
unsigned int dtHashRef (dtPolyRef a)
Function Documentation
dtHashRef()
unsigned int dtHashRef (dtPolyRef a) inline
Definition at line 38 of file DetourNode.cpp.
 {
     a += ~(a<<15);
     a ^=  (a>>10);
     a +=  (a<<3);
     a ^=  (a>>6);
     a += ~(a<<11);
     a ^=  (a>>16);
     return (unsigned int)a;
 }
References mpq::a.
Referenced by dtNodePool::findNode(), dtNodePool::findNodes(), and dtNodePool::getNode().