Azerotcore-wotlk: item_petrov_cluster_bombs Class Reference
item_petrov_cluster_bombs Class Reference
Public Member Functions
item_petrov_cluster_bombs ()
bool OnUse (Player *player, Item *item, const SpellCastTargets &) override
Public Member Functions inherited from ItemScript
bool IsDatabaseBound () const override
virtual bool OnQuestAccept (Player *, Item *, Quest const *)
virtual bool OnRemove (Player *, Item *)
virtual bool OnCastItemCombatSpell (Player *, Unit *, SpellInfo const *, Item *)
virtual bool OnExpire (Player *, ItemTemplate const *)
virtual void OnGossipSelect (Player *, Item *, uint32, uint32)
virtual void OnGossipSelectCode (Player *, Item *, uint32, uint32, const char *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from ItemScript
ItemScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 198 of file item_scripts.cpp.
Constructor & Destructor Documentation
item_petrov_cluster_bombs()
item_petrov_cluster_bombs::item_petrov_cluster_bombs () inline
Definition at line 201 of file item_scripts.cpp.
 : ItemScript("item_petrov_cluster_bombs") { }
Member Function Documentation
OnUse()
bool item_petrov_cluster_bombs::OnUse (Player * player, Item * item, const SpellCastTargets &) inline override virtual
Reimplemented from ItemScript.
Definition at line 203 of file item_scripts.cpp.
     {
         if (player->GetZoneId() != ZONE_ID_HOWLING)
             return false;
         if (!player->GetTransport() || player->GetAreaId() != AREA_ID_SHATTERED_STRAITS)
         {
             player->SendEquipError(EQUIP_ERR_NONE, item, nullptr);
             if (const SpellInfo* spellInfo = sSpellMgr->GetSpellInfo(SPELL_PETROV_BOMB))
                 Spell::SendCastResult(player, spellInfo, 1, SPELL_FAILED_NOT_HERE);
             return true;
         }
         return false;
     }
References AREA_ID_SHATTERED_STRAITS, EQUIP_ERR_NONE, WorldObject::GetAreaId(), WorldObject::GetTransport(), WorldObject::GetZoneId(), Spell::SendCastResult(), Player::SendEquipError(), SPELL_FAILED_NOT_HERE, SPELL_PETROV_BOMB, sSpellMgr, and ZONE_ID_HOWLING.
The documentation for this class was generated from the following file:
src/server/scripts/World/item_scripts.cpp