Azerotcore-wotlk: deps/mysqllite/strings/longlong2str.c File Reference
longlong2str.c File Reference
#include <my_global.h>
#include "m_string.h"
Functions
char * ll2str (longlong val, char *dst, int radix, int upcase)
char * longlong10_to_str (longlong val, char *dst, int radix)
Function Documentation
ll2str()
char* ll2str (longlong val, char * dst, int radix, int upcase)
Definition at line 49 of file longlong2str.c.
 {
   char buffer[65];
   register char *p;
   long long_val;
   char *dig_vec= upcase ? _dig_vec_upper : _dig_vec_lower;
   ulonglong uval= (ulonglong) val;
   if (radix < 0)
   {
     if (radix < -36 || radix > -2) return (char*) 0;
     if (val < 0) {
       *dst++ = '-';
       /* Avoid integer overflow in (-val) for LONGLONG_MIN (BUG#31799). */
       uval = (ulonglong)0 - uval;
     }
     radix = -radix;
   }
   else
   {
     if (radix > 36 || radix < 2) return (char*) 0;
   }
   if (uval == 0)
   {
     *dst++='0';
     *dst='\0';
     return dst;
   }
   p = &buffer[sizeof(buffer)-1];
   *p = '\0';
   while (uval > (ulonglong) LONG_MAX)
   {
     ulonglong quo= uval/(uint) radix;
     uint rem= (uint) (uval- quo* (uint) radix);
     *--p= dig_vec[rem];
     uval= quo;
   }
   long_val= (long) uval;
   while (long_val != 0)
   {
     long quo= long_val/radix;
     *--p= dig_vec[(uchar) (long_val - quo*radix)];
     long_val= quo;
   }
   while ((*dst++ = *p++) != 0) ;
   return dst-1;
 }
References _dig_vec_lower, _dig_vec_upper, and buffer.
Referenced by process_int_arg().
longlong10_to_str()
char* longlong10_to_str (longlong val, char * dst, int radix)
Definition at line 100 of file longlong2str.c.
 {
   char buffer[65];
   register char *p;
   long long_val;
   ulonglong uval= (ulonglong) val;
   if (radix < 0)
   {
     if (val < 0)
     {
       *dst++ = '-';
       /* Avoid integer overflow in (-val) for LONGLONG_MIN (BUG#31799). */
       uval = (ulonglong)0 - uval;
     }
   }
   if (uval == 0)
   {
     *dst++='0';
     *dst='\0';
     return dst;
   }
   p = &buffer[sizeof(buffer)-1];
   *p = '\0';
   while (uval > (ulonglong) LONG_MAX)
   {
     ulonglong quo= uval/(uint) 10;
     uint rem= (uint) (uval- quo* (uint) 10);
     *--p = _dig_vec_upper[rem];
     uval= quo;
   }
   long_val= (long) uval;
   while (long_val != 0)
   {
     long quo= long_val/10;
     *--p = _dig_vec_upper[(uchar) (long_val - quo*10)];
     long_val= quo;
   }
   while ((*dst++ = *p++) != 0) ;
   return dst-1;
 }
References _dig_vec_upper, and buffer.
Referenced by fetch_long_with_conversion(), llstr(), process_int_arg(), and ullstr().