Azerotcore-wotlk: PassengerController Class Reference
PassengerController Class Reference
Public Member Functions
PassengerController ()
void ResetSlots (TeamId teamId, MotionTransport *t)
bool SummonCreatures (Creature *summoner, PassengerSlots first, PassengerSlots last)
void ClearSlot (PassengerSlots slot)
Private Member Functions
Position SelectSpawnPoint () const
Private Attributes
ObjectGuid _controlledSlots [MAX_SLOTS]
time_t _respawnCooldowns [MAX_SLOTS]
MotionTransport * _transport
Position const * _spawnPoint
SlotInfo const * _slotInfo
Detailed Description
Definition at line 398 of file boss_icecrown_gunship_battle.cpp.
Constructor & Destructor Documentation
PassengerController()
PassengerController::PassengerController () inline
Definition at line 401 of file boss_icecrown_gunship_battle.cpp.
     {
         ResetSlots(TEAM_HORDE, nullptr);
     }
References ResetSlots(), and TEAM_HORDE.
Member Function Documentation
ClearSlot()
void PassengerController::ClearSlot (PassengerSlots slot) inline
Definition at line 459 of file boss_icecrown_gunship_battle.cpp.
     {
         _controlledSlots[slot].Clear();
         _respawnCooldowns[slot] = time(nullptr) + _slotInfo[slot].Cooldown;
     }
References _controlledSlots, _respawnCooldowns, _slotInfo, ObjectGuid::Clear(), and SlotInfo::Cooldown.
Referenced by npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::SetData(), and npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::SetData().
ResetSlots()
void PassengerController::ResetSlots (TeamId teamId, MotionTransport * t) inline
Definition at line 406 of file boss_icecrown_gunship_battle.cpp.
     {
         _transport = t;
         for (uint8 i = 0; i < MAX_SLOTS; ++i)
         {
             _controlledSlots[i].Clear();
             _respawnCooldowns[i] = time_t(0);
         }
         _spawnPoint = teamId == TEAM_HORDE ? &OrgrimsHammerAddsSpawnPos : &SkybreakerAddsSpawnPos;
         _slotInfo = teamId == TEAM_HORDE ? OrgrimsHammerSlotInfo : SkybreakerSlotInfo;
     }
References _controlledSlots, _respawnCooldowns, _slotInfo, _spawnPoint, _transport, ObjectGuid::Clear(), MAX_SLOTS, OrgrimsHammerAddsSpawnPos, OrgrimsHammerSlotInfo, SkybreakerAddsSpawnPos, SkybreakerSlotInfo, and TEAM_HORDE.
Referenced by npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::npc_high_overlord_saurfang_igbAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::npc_muradin_bronzebeard_igbAI(), and PassengerController().
SelectSpawnPoint()
Position PassengerController::SelectSpawnPoint () const inline private
Definition at line 466 of file boss_icecrown_gunship_battle.cpp.
     {
         float angle = frand(-M_PI * 0.5f, M_PI * 0.5f);
         Position newPos;
         newPos.m_positionX = _spawnPoint->GetPositionX() + 2.0f * std::cos(angle);
         newPos.m_positionY = _spawnPoint->GetPositionY() + 2.0f * std::sin(angle);
         newPos.m_positionZ = _spawnPoint->GetPositionZ();
         newPos.SetOrientation(_spawnPoint->GetOrientation());
         _transport->CalculatePassengerPosition(newPos.m_positionX, newPos.m_positionY, newPos.m_positionZ, &(newPos.m_orientation));
         return newPos;
     }
References _spawnPoint, _transport, Transport::CalculatePassengerPosition(), G3D::frand(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Position::m_orientation, M_PI, Position::m_positionX, Position::m_positionY, Position::m_positionZ, and Position::SetOrientation().
Referenced by SummonCreatures().
SummonCreatures()
bool PassengerController::SummonCreatures (Creature * summoner, PassengerSlots first, PassengerSlots last) inline
Definition at line 420 of file boss_icecrown_gunship_battle.cpp.
     {
         if (!_transport)
             return false;
         bool summoned = false;
         time_t now = time(nullptr);
         for (int32 i = first; i <= last; ++i)
         {
             if (_respawnCooldowns[i] > now)
                 continue;
             if (_controlledSlots[i])
             {
                 Creature* current = ObjectAccessor::GetCreature(*_transport, _controlledSlots[i]);
                 if (current && current->IsAlive())
                     continue;
             }
             Position spawnPos = SelectSpawnPoint();
             if (Creature* passenger = summoner->SummonCreature(_slotInfo[i].Entry, spawnPos, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 15000))
             {
                 if (!passenger->GetTransport())
                     _transport->AddPassenger(passenger, true);
                 passenger->ApplySpellImmune(0, IMMUNITY_ID, 49576, true); // death grip
                 if (i >= SLOT_MAGE_1 && i <= SLOT_MORTAR_4) // only these npcs are pooled
                 {
                     _controlledSlots[i] = passenger->GetGUID();
                     _respawnCooldowns[i] = time_t(0);
                 }
                 passenger->AI()->SetData(ACTION_SET_SLOT, i);
                 summoned = true;
             }
         }
         return summoned;
     }
References _controlledSlots, _respawnCooldowns, _slotInfo, _transport, ACTION_SET_SLOT, MotionTransport::AddPassenger(), SlotInfo::Entry, detail::first(), ObjectAccessor::GetCreature(), IMMUNITY_ID, Unit::IsAlive(), SelectSpawnPoint(), SLOT_MAGE_1, SLOT_MORTAR_4, WorldObject::SummonCreature(), and TEMPSUMMON_CORPSE_TIMED_DESPAWN.
Referenced by npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::DoAction(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::DoAction(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), and npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI().
Member Data Documentation
_controlledSlots
ObjectGuid PassengerController::_controlledSlots[MAX_SLOTS] private
Definition at line 478 of file boss_icecrown_gunship_battle.cpp.
Referenced by ClearSlot(), ResetSlots(), and SummonCreatures().
_respawnCooldowns
time_t PassengerController::_respawnCooldowns[MAX_SLOTS] private
Definition at line 479 of file boss_icecrown_gunship_battle.cpp.
Referenced by ClearSlot(), ResetSlots(), and SummonCreatures().
_slotInfo
SlotInfo const* PassengerController::_slotInfo private
Definition at line 482 of file boss_icecrown_gunship_battle.cpp.
Referenced by ClearSlot(), ResetSlots(), and SummonCreatures().
_spawnPoint
Position const* PassengerController::_spawnPoint private
Definition at line 481 of file boss_icecrown_gunship_battle.cpp.
Referenced by ResetSlots(), and SelectSpawnPoint().
_transport
MotionTransport* PassengerController::_transport private
Definition at line 480 of file boss_icecrown_gunship_battle.cpp.
Referenced by ResetSlots(), SelectSpawnPoint(), and SummonCreatures().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp