Azerotcore-wotlk: spell_brewfest_toss_mug::spell_brewfest_toss_mug_SpellScript Class Reference
spell_brewfest_toss_mug::spell_brewfest_toss_mug_SpellScript Class Reference
Private Member Functions
PrepareSpellScript (spell_brewfest_toss_mug_SpellScript)
SpellCastResult CheckCast ()
void FilterTargets (std::list< WorldObject * > &targets)
void HandleBeforeHit (SpellMissInfo missInfo)
void HandleScriptEffect (SpellEffIndex)
void Register () override
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Definition at line 1318 of file brewfest.cpp.
Member Function Documentation
CheckCast()
SpellCastResult spell_brewfest_toss_mug::spell_brewfest_toss_mug_SpellScript::CheckCast () inline private
Definition at line 1322 of file brewfest.cpp.
         {
             if (Unit* caster = GetCaster())
             {
                 float z = caster->GetMapHeight(caster->GetPositionX() + 14 * cos(caster->GetOrientation()), caster->GetPositionY() + 14 * sin(caster->GetOrientation()), caster->GetPositionZ());
                 WorldLocation pPosition = WorldLocation(caster->GetMapId(), caster->GetPositionX() + 14 * cos(caster->GetOrientation()), caster->GetPositionY() + 14 * sin(caster->GetOrientation()), z, caster->GetOrientation());
                 SetExplTargetDest(pPosition);
             }
             return SPELL_CAST_OK;
         }
References SpellScript::GetCaster(), SpellScript::SetExplTargetDest(), SPELL_CAST_OK, and G3D::z.
Referenced by Register().
FilterTargets()
void spell_brewfest_toss_mug::spell_brewfest_toss_mug_SpellScript::FilterTargets (std::list< WorldObject * > & targets) inline private
Definition at line 1334 of file brewfest.cpp.
         {
             Unit* caster = GetCaster();
             if (!caster)
                 return;
             WorldObject* target = nullptr;
             for (std::list<WorldObject*>::iterator itr = targets.begin(); itr != targets.end(); ++itr)
                 if (caster->HasInLine((*itr), 2.0f))
                 {
                     target = (*itr);
                     break;
                 }
             targets.clear();
             if (target)
                 targets.push_back(target);
             targets.push_back(caster);
         }
References SpellScript::GetCaster(), and Position::HasInLine().
Referenced by Register().
HandleBeforeHit()
void spell_brewfest_toss_mug::spell_brewfest_toss_mug_SpellScript::HandleBeforeHit (SpellMissInfo missInfo) inline private
Definition at line 1355 of file brewfest.cpp.
         {
             if (missInfo != SPELL_MISS_NONE)
             {
                 return;
             }
             if (Unit* target = GetHitUnit())
             {
                 if (!GetCaster() || target->GetGUID() == GetCaster()->GetGUID())
                     return;
                 WorldLocation pPosition = WorldLocation(target->GetMapId(), target->GetPositionX(), target->GetPositionY(), target->GetPositionZ() + 4.0f, target->GetOrientation());
                 SetExplTargetDest(pPosition);
             }
         }
References SpellScript::GetCaster(), Object::GetGUID(), SpellScript::GetHitUnit(), SpellScript::SetExplTargetDest(), and SPELL_MISS_NONE.
Referenced by Register().
HandleScriptEffect()
void spell_brewfest_toss_mug::spell_brewfest_toss_mug_SpellScript::HandleScriptEffect (SpellEffIndex) inline private
Definition at line 1372 of file brewfest.cpp.
         {
             Unit* caster = GetCaster();
             if (!caster)
                 return;
             if (!GetHitUnit() || GetHitUnit()->GetGUID() != caster->GetGUID())
                 return;
             std::vector<Creature*> bakers;
             if (caster->GetMapId() == 1) // Kalimdor
             {
                 if (Creature* creature = caster->FindNearestCreature(NPC_NORMAL_VOODOO, 40.0f))
                 {
                     bakers.push_back(creature);
                 }
                 if (Creature* creature = caster->FindNearestCreature(NPC_NORMAL_DROHN, 40.0f))
                 {
                     bakers.push_back(creature);
                 }
                 if (Creature* creature = caster->FindNearestCreature(NPC_NORMAL_GORDOK, 40.0f))
                 {
                     bakers.push_back(creature);
                 }
             }
             else // EK
             {
                 if (Creature* creature = caster->FindNearestCreature(NPC_NORMAL_THUNDERBREW, 40.0f))
                 {
                     bakers.push_back(creature);
                 }
                 if (Creature* creature = caster->FindNearestCreature(NPC_NORMAL_BARLEYBREW, 40.0f))
                 {
                     bakers.push_back(creature);
                 }
                 if (Creature* creature = caster->FindNearestCreature(NPC_NORMAL_GORDOK, 40.0f))
                 {
                     bakers.push_back(creature);
                 }
             }
             if (!bakers.empty())
             {
                 std::sort(bakers.begin(), bakers.end(), Acore::ObjectDistanceOrderPred(caster));
                 if (Creature* creature = *bakers.begin())
                 {
                     creature->CastSpell(caster, SPELL_THROW_MUG_TO_PLAYER, true);
                 }
             }
         }
References WorldObject::FindNearestCreature(), SpellScript::GetCaster(), Object::GetGUID(), SpellScript::GetHitUnit(), WorldLocation::GetMapId(), NPC_NORMAL_BARLEYBREW, NPC_NORMAL_DROHN, NPC_NORMAL_GORDOK, NPC_NORMAL_THUNDERBREW, NPC_NORMAL_VOODOO, and SPELL_THROW_MUG_TO_PLAYER.
Referenced by Register().
PrepareSpellScript()
spell_brewfest_toss_mug::spell_brewfest_toss_mug_SpellScript::PrepareSpellScript (spell_brewfest_toss_mug_SpellScript) private
Register()
void spell_brewfest_toss_mug::spell_brewfest_toss_mug_SpellScript::Register () inline override private virtual
Implements _SpellScript.
Definition at line 1427 of file brewfest.cpp.
         {
             OnCheckCast += SpellCheckCastFn(spell_brewfest_toss_mug_SpellScript::CheckCast);
             OnObjectAreaTargetSelect += SpellObjectAreaTargetSelectFn(spell_brewfest_toss_mug_SpellScript::FilterTargets, EFFECT_0, TARGET_UNIT_SRC_AREA_ENTRY);
             BeforeHit += BeforeSpellHitFn(spell_brewfest_toss_mug_SpellScript::HandleBeforeHit);
             OnEffectHitTarget += SpellEffectFn(spell_brewfest_toss_mug_SpellScript::HandleScriptEffect, EFFECT_0, SPELL_EFFECT_SCRIPT_EFFECT);
         }
References SpellScript::BeforeHit, BeforeSpellHitFn, CheckCast(), EFFECT_0, FilterTargets(), HandleBeforeHit(), HandleScriptEffect(), SpellScript::OnCheckCast, SpellScript::OnEffectHitTarget, SpellScript::OnObjectAreaTargetSelect, SPELL_EFFECT_SCRIPT_EFFECT, SpellCheckCastFn, SpellEffectFn, SpellObjectAreaTargetSelectFn, and TARGET_UNIT_SRC_AREA_ENTRY.
The documentation for this class was generated from the following file:
src/server/scripts/Events/brewfest.cpp