Azerotcore-wotlk: boss_kalecgos::boss_kalecgosAI Struct Reference
boss_kalecgos::boss_kalecgosAI Struct Reference
Public Member Functions
boss_kalecgosAI (Creature *creature)
bool CanAIAttack (Unit const *target) const override
void JustReachedHome () override
void Reset () override
void ClearPlayerAuras () const
void DoAction (int32 param) override
void JustDied (Unit *who) override
void EnterCombat (Unit *who) override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *victim) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
bool sathBanished
EventMap events2
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 119 of file boss_kalecgos.cpp.
Constructor & Destructor Documentation
boss_kalecgosAI()
boss_kalecgos::boss_kalecgosAI::boss_kalecgosAI (Creature * creature) inline
Definition at line 121 of file boss_kalecgos.cpp.
                                             : BossAI(creature, DATA_KALECGOS)
         {
         }
Member Function Documentation
CanAIAttack()
bool boss_kalecgos::boss_kalecgosAI::CanAIAttack (Unit const * target) const inline override virtual
Reimplemented from UnitAI.
Definition at line 128 of file boss_kalecgos.cpp.
         {
             return target->GetPositionZ() > 50.0f;
         }
References Position::GetPositionZ().
ClearPlayerAuras()
void boss_kalecgos::boss_kalecgosAI::ClearPlayerAuras () const inline
Definition at line 153 of file boss_kalecgos.cpp.
         {
             instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_CURSE_OF_BOUNDLESS_AGONY);
             instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_CURSE_OF_BOUNDLESS_AGONY_PLR);
             instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_SPECTRAL_REALM);
         }
References InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), BossAI::instance, SPELL_CURSE_OF_BOUNDLESS_AGONY, SPELL_CURSE_OF_BOUNDLESS_AGONY_PLR, and SPELL_SPECTRAL_REALM.
Referenced by DoAction(), and Reset().
DamageTaken()
void boss_kalecgos::boss_kalecgosAI::DamageTaken (Unit * attacker, uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 221 of file boss_kalecgos.cpp.
         {
             if (damage >= me->GetHealth() && attacker != me)
                 damage = 0;
         }
References Unit::GetHealth(), and ScriptedAI::me.
DoAction()
void boss_kalecgos::boss_kalecgosAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 160 of file boss_kalecgos.cpp.
         {
             if (param == ACTION_ENRAGE || param == ACTION_ENRAGE_OTHER)
             {
                 Talk(param == ACTION_ENRAGE ? SAY_KALEC_ENRAGE_SATH : SAY_SATH_ENRAGE_ME);
                 me->CastSpell(me, SPELL_CRAZED_RAGE, true);
                 events.CancelEvent(EVENT_CHECK_HEALTH);
                 return;
             }
             else if (param == ACTION_BANISH)
             {
                 me->CastSpell(me, SPELL_BANISH, true);
                 events.Reset();
             }
             else if (param == ACTION_SATH_BANISH)
                 sathBanished = true;
             else if (param == ACTION_KALEC_DIED)
             {
                 events.Reset();
                 events2.ScheduleEvent(EVENT_TALK_BAD_1, 0);
                 ClearPlayerAuras();
                 return;
             }
             if (me->HasAura(SPELL_BANISH) && sathBanished)
             {
                 events.Reset();
                 events2.ScheduleEvent(EVENT_TALK_GOOD_1, 1000);
                 ClearPlayerAuras();
                 if (Creature* Sath = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_SATHROVARR)))
                 {
                     Sath->RemoveAllAuras();
                     Sath->GetMotionMaster()->MovementExpired();
                     Sath->SetReactState(REACT_PASSIVE);
                     Sath->NearTeleportTo(1696.20f, 915.0f, DRAGON_REALM_Z, Sath->GetOrientation());
                 }
             }
         }
References ACTION_BANISH, ACTION_ENRAGE, ACTION_ENRAGE_OTHER, ACTION_KALEC_DIED, ACTION_SATH_BANISH, Unit::CastSpell(), ClearPlayerAuras(), DRAGON_REALM_Z, EVENT_CHECK_HEALTH, EVENT_TALK_BAD_1, EVENT_TALK_GOOD_1, events2, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Unit::HasAura(), BossAI::instance, ScriptedAI::me, NPC_SATHROVARR, REACT_PASSIVE, sathBanished, SAY_KALEC_ENRAGE_SATH, SAY_SATH_ENRAGE_ME, EventMap::ScheduleEvent(), SPELL_BANISH, SPELL_CRAZED_RAGE, and CreatureAI::Talk().
Referenced by UpdateAI().
EnterCombat()
void boss_kalecgos::boss_kalecgosAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from BossAI.
Definition at line 204 of file boss_kalecgos.cpp.
         {
             BossAI::EnterCombat(who);
             events.ScheduleEvent(EVENT_ARCANE_BUFFET, 6000);
             events.ScheduleEvent(EVENT_FROST_BREATH, 15000);
             events.ScheduleEvent(EVENT_WILD_MAGIC, 10000);
             events.ScheduleEvent(EVENT_TAIL_LASH, 25000);
             events.ScheduleEvent(EVENT_SPECTRAL_BLAST, 20000);
             events.ScheduleEvent(EVENT_CHECK_POS, 5000);
             events.ScheduleEvent(EVENT_CHECK_HEALTH, 1000);
             events.ScheduleEvent(EVENT_CHECK_HEALTH2, 1000);
             events.ScheduleEvent(EVENT_SPAWN_SPECTRALS, 16000);
             me->SetStandState(UNIT_STAND_STATE_STAND);
             Talk(SAY_EVIL_AGGRO);
         }
References BossAI::EnterCombat(), EVENT_ARCANE_BUFFET, EVENT_CHECK_HEALTH, EVENT_CHECK_HEALTH2, EVENT_CHECK_POS, EVENT_FROST_BREATH, EVENT_SPAWN_SPECTRALS, EVENT_SPECTRAL_BLAST, EVENT_TAIL_LASH, EVENT_WILD_MAGIC, ScriptedAI::me, SAY_EVIL_AGGRO, Unit::SetStandState(), CreatureAI::Talk(), and UNIT_STAND_STATE_STAND.
JustDied()
void boss_kalecgos::boss_kalecgosAI::JustDied (Unit * who) inline override virtual
Reimplemented from BossAI.
Definition at line 199 of file boss_kalecgos.cpp.
         {
             BossAI::JustDied(who);
         }
References BossAI::JustDied().
JustReachedHome()
void boss_kalecgos::boss_kalecgosAI::JustReachedHome () inline override virtual
Reimplemented from BossAI.
Definition at line 133 of file boss_kalecgos.cpp.
         {
             BossAI::JustReachedHome();
             me->SetVisible(true);
         }
References BossAI::JustReachedHome(), ScriptedAI::me, and Unit::SetVisible().
KilledUnit()
void boss_kalecgos::boss_kalecgosAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 227 of file boss_kalecgos.cpp.
         {
             if (victim->GetTypeId() == TYPEID_PLAYER && roll_chance_i(50))
                 Talk(SAY_EVIL_SLAY);
         }
References Object::GetTypeId(), roll_chance_i(), SAY_EVIL_SLAY, CreatureAI::Talk(), and TYPEID_PLAYER.
Reset()
void boss_kalecgos::boss_kalecgosAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 139 of file boss_kalecgos.cpp.
         {
             BossAI::Reset();
             me->SetHealth(me->GetMaxHealth());
             me->SetStandState(UNIT_STAND_STATE_SLEEP);
             me->SetDisableGravity(false);
             me->SetReactState(REACT_AGGRESSIVE);
             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE + UNIT_FLAG_NOT_SELECTABLE);
             events2.Reset();
             sathBanished = false;
             ClearPlayerAuras();
         }
References ClearPlayerAuras(), events2, Unit::GetMaxHealth(), ScriptedAI::me, REACT_AGGRESSIVE, Object::RemoveFlag(), EventMap::Reset(), BossAI::Reset(), sathBanished, Creature::SetDisableGravity(), Unit::SetHealth(), Creature::SetReactState(), Unit::SetStandState(), UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, and UNIT_STAND_STATE_SLEEP.
UpdateAI()
void boss_kalecgos::boss_kalecgosAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 233 of file boss_kalecgos.cpp.
         {
             events2.Update(diff);
             switch (events2.ExecuteEvent())
             {
                 case EVENT_TALK_GOOD_1:
                     me->SetRegeneratingHealth(false);
                     me->RemoveAllAuras();
                     me->SetReactState(REACT_PASSIVE);
                     me->CombatStop();
                     me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                     me->SetFaction(FACTION_FRIENDLY);
                     events2.ScheduleEvent(EVENT_TALK_GOOD_2, 1000);
                     break;
                 case EVENT_TALK_GOOD_2:
                     if (Creature* Sath = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_SATHROVARR)))
                     {
                         summons.Despawn(Sath);
                         Unit::Kill(me, Sath);
                     }
                     events2.ScheduleEvent(EVENT_TALK_GOOD_3, 8000);
                     break;
                 case EVENT_TALK_GOOD_3:
                     Talk(SAY_GOOD_PLRWIN);
                     events2.ScheduleEvent(EVENT_TALK_GOOD_4, 10000);
                     break;
                 case EVENT_TALK_GOOD_4:
                     me->SetDisableGravity(true);
                     me->HandleEmoteCommand(EMOTE_ONESHOT_LIFTOFF);
                     events2.ScheduleEvent(EVENT_TALK_GOOD_5, 10000);
                     break;
                 case EVENT_TALK_GOOD_5:
                     me->SetVisible(false);
                     Unit::Kill(me, me);
                     break;
                 case EVENT_TALK_BAD_1:
                     me->SetReactState(REACT_PASSIVE);
                     me->CombatStop();
                     me->RemoveAllAuras();
                     me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                     Talk(SAY_EVIL_ENRAGE);
                     events2.ScheduleEvent(EVENT_TALK_BAD_2, 3000);
                     break;
                 case EVENT_TALK_BAD_2:
                     me->SetDisableGravity(true);
                     me->HandleEmoteCommand(EMOTE_ONESHOT_LIFTOFF);
                     events2.ScheduleEvent(EVENT_TALK_BAD_3, 15000);
                     break;
                 case EVENT_TALK_BAD_3:
                     me->SetVisible(false);
                     EnterEvadeMode();
                     break;
             }
             if (!events2.Empty())
                 return;
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_SPAWN_SPECTRALS:
                     me->SummonCreature(NPC_KALEC, 1702.21f, 931.7f, -74.56f, 5.07f, TEMPSUMMON_MANUAL_DESPAWN);
                     me->SummonCreature(NPC_SATHROVARR, 1704.62f, 927.78f, -73.9f, 2.0f, TEMPSUMMON_MANUAL_DESPAWN);
                     break;
                 case EVENT_ARCANE_BUFFET:
                     me->CastSpell(me, SPELL_ARCANE_BUFFET, false);
                     events.ScheduleEvent(EVENT_ARCANE_BUFFET, 8000);
                     break;
                 case EVENT_FROST_BREATH:
                     me->CastSpell(me->GetVictim(), SPELL_FROST_BREATH, false);
                     events.ScheduleEvent(EVENT_FROST_BREATH, 15000);
                     break;
                 case EVENT_TAIL_LASH:
                     me->CastSpell(me->GetVictim(), SPELL_TAIL_LASH, false);
                     events.ScheduleEvent(EVENT_TAIL_LASH, 15000);
                     break;
                 case EVENT_WILD_MAGIC:
                     me->CastCustomSpell(RAND(44978, 45001, 45002, 45004, 45006, 45010), SPELLVALUE_MAX_TARGETS, 1, me, false);
                     events.ScheduleEvent(EVENT_WILD_MAGIC, 20000);
                     break;
                 case EVENT_SPECTRAL_BLAST:
                     me->CastSpell(me, SPELL_SPECTRAL_BLAST, false);
                     events.ScheduleEvent(EVENT_SPECTRAL_BLAST, urand(15000, 25000));
                     break;
                 case EVENT_CHECK_POS:
                     if (me->GetDistance(me->GetHomePosition()) > 50.0f)
                     {
                         EnterEvadeMode();
                         return;
                     }
                     events.ScheduleEvent(EVENT_CHECK_POS, 5000);
                     break;
                 case EVENT_CHECK_HEALTH:
                     if (me->HealthBelowPct(10))
                     {
                         if (Creature* Sath = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_SATHROVARR)))
                             Sath->AI()->DoAction(ACTION_ENRAGE_OTHER);
                         DoAction(ACTION_ENRAGE);
                         break;
                     }
                     events.ScheduleEvent(EVENT_CHECK_HEALTH, 1000);
                     break;
                 case EVENT_CHECK_HEALTH2:
                     if (me->HealthBelowPct(1))
                     {
                         DoAction(ACTION_BANISH);
                         break;
                     }
                     events.ScheduleEvent(EVENT_CHECK_HEALTH2, 1000);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References ACTION_BANISH, ACTION_ENRAGE, ACTION_ENRAGE_OTHER, Unit::CastCustomSpell(), Unit::CastSpell(), Unit::CombatStop(), SummonList::Despawn(), diff(), DoAction(), UnitAI::DoMeleeAttackIfReady(), EMOTE_ONESHOT_LIFTOFF, EventMap::Empty(), CreatureAI::EnterEvadeMode(), EVENT_ARCANE_BUFFET, EVENT_CHECK_HEALTH, EVENT_CHECK_HEALTH2, EVENT_CHECK_POS, EVENT_FROST_BREATH, EVENT_SPAWN_SPECTRALS, EVENT_SPECTRAL_BLAST, EVENT_TAIL_LASH, EVENT_TALK_BAD_1, EVENT_TALK_BAD_2, EVENT_TALK_BAD_3, EVENT_TALK_GOOD_1, EVENT_TALK_GOOD_2, EVENT_TALK_GOOD_3, EVENT_TALK_GOOD_4, EVENT_TALK_GOOD_5, EVENT_WILD_MAGIC, events2, EventMap::ExecuteEvent(), FACTION_FRIENDLY, ObjectAccessor::GetCreature(), WorldObject::GetDistance(), InstanceScript::GetGuidData(), Creature::GetHomePosition(), Unit::GetVictim(), Unit::HandleEmoteCommand(), Unit::HasUnitState(), Unit::HealthBelowPct(), BossAI::instance, Unit::Kill(), ScriptedAI::me, NPC_KALEC, NPC_SATHROVARR, RAND(), REACT_PASSIVE, Unit::RemoveAllAuras(), SAY_EVIL_ENRAGE, SAY_GOOD_PLRWIN, EventMap::ScheduleEvent(), Creature::SetDisableGravity(), Unit::SetFaction(), Object::SetFlag(), Creature::SetReactState(), Creature::SetRegeneratingHealth(), Unit::SetVisible(), SPELL_ARCANE_BUFFET, SPELL_FROST_BREATH, SPELL_SPECTRAL_BLAST, SPELL_TAIL_LASH, SPELLVALUE_MAX_TARGETS, WorldObject::SummonCreature(), BossAI::summons, CreatureAI::Talk(), TEMPSUMMON_MANUAL_DESPAWN, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, UNIT_STATE_CASTING, EventMap::Update(), CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
events2
EventMap boss_kalecgos::boss_kalecgosAI::events2
Definition at line 126 of file boss_kalecgos.cpp.
Referenced by DoAction(), Reset(), and UpdateAI().
sathBanished
bool boss_kalecgos::boss_kalecgosAI::sathBanished
Definition at line 125 of file boss_kalecgos.cpp.
Referenced by DoAction(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/SunwellPlateau/boss_kalecgos.cpp