Azerotcore-wotlk: npc_boss_gothik_minion::npc_boss_gothik_minionAI Struct Reference
npc_boss_gothik_minion::npc_boss_gothik_minionAI Struct Reference
Public Member Functions
npc_boss_gothik_minionAI (Creature *c)
bool IsOnSameSide (Unit const *who) const
void Reset () override
void EnterCombat (Unit *) override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *who) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from CombatAI
CombatAI (Creature *c)
void InitializeAI () override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
bool livingSide
Additional Inherited Members
Static Public Member Functions inherited from CombatAI
static int Permissible (Creature const *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CombatAI
EventMap events
SpellVct spells
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 523 of file boss_gothik.cpp.
Constructor & Destructor Documentation
npc_boss_gothik_minionAI()
npc_boss_gothik_minion::npc_boss_gothik_minionAI::npc_boss_gothik_minionAI (Creature * c) inline explicit
Definition at line 525 of file boss_gothik.cpp.
                                                        : CombatAI(c)
         {
             livingSide = IN_LIVE_SIDE(me);
         }
References IN_LIVE_SIDE, livingSide, and CreatureAI::me.
Member Function Documentation
DamageTaken()
void npc_boss_gothik_minion::npc_boss_gothik_minionAI::DamageTaken (Unit * attacker, uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from UnitAI.
Definition at line 569 of file boss_gothik.cpp.
         {
             if (!attacker || !IsOnSameSide(attacker))
             {
                 damage = 0;
             }
             if (!me->IsInCombat())
             {
                 me->CallForHelp(25.0f);
                 AttackStart(attacker);
             }
         }
References UnitAI::AttackStart(), Creature::CallForHelp(), Unit::IsInCombat(), IsOnSameSide(), and CreatureAI::me.
EnterCombat()
void npc_boss_gothik_minion::npc_boss_gothik_minionAI::EnterCombat (Unit *) inline override virtual
Reimplemented from CombatAI.
Definition at line 540 of file boss_gothik.cpp.
         {
             switch (me->GetEntry())
             {
                 case NPC_LIVING_TRAINEE:
                     events.ScheduleEvent(EVENT_DEATH_PLAGUE, 3000);
                     break;
                 case NPC_DEAD_TRAINEE:
                     events.ScheduleEvent(EVENT_ARCANE_EXPLOSION, 2500);
                     break;
                 case NPC_LIVING_KNIGHT:
                     events.ScheduleEvent(EVENT_SHADOW_MARK, 3000);
                     break;
                 case NPC_DEAD_KNIGHT:
                     events.ScheduleEvent(EVENT_WHIRLWIND, 2000);
                     break;
                 case NPC_LIVING_RIDER:
                     events.ScheduleEvent(EVENT_SHADOW_BOLT_VOLLEY, 3000);
                     break;
                 case NPC_DEAD_RIDER:
                     events.ScheduleEvent(EVENT_DRAIN_LIFE, urand(2000, 3500));
                     events.ScheduleEvent(EVENT_UNHOLY_FRENZY, urand(5000, 9000));
                     break;
                 case NPC_DEAD_HORSE:
                     events.ScheduleEvent(EVENT_STOMP, urand(2000, 5000));
                     break;
             }
         }
References EVENT_ARCANE_EXPLOSION, EVENT_DEATH_PLAGUE, EVENT_DRAIN_LIFE, EVENT_SHADOW_BOLT_VOLLEY, EVENT_SHADOW_MARK, EVENT_STOMP, EVENT_UNHOLY_FRENZY, EVENT_WHIRLWIND, Object::GetEntry(), CreatureAI::me, NPC_DEAD_HORSE, NPC_DEAD_KNIGHT, NPC_DEAD_RIDER, NPC_DEAD_TRAINEE, NPC_LIVING_KNIGHT, NPC_LIVING_RIDER, NPC_LIVING_TRAINEE, and urand().
IsOnSameSide()
bool npc_boss_gothik_minion::npc_boss_gothik_minionAI::IsOnSameSide (Unit const * who) const inline
Definition at line 531 of file boss_gothik.cpp.
 { return livingSide == IN_LIVE_SIDE(who); }
References IN_LIVE_SIDE, and livingSide.
Referenced by DamageTaken().
JustDied()
void npc_boss_gothik_minion::npc_boss_gothik_minionAI::JustDied (Unit *) inline override virtual
Reimplemented from CombatAI.
Definition at line 583 of file boss_gothik.cpp.
         {
             switch (me->GetEntry())
             {
                 case NPC_LIVING_TRAINEE:
                     me->CastSpell(me, SPELL_INFORM_LIVING_TRAINEE, true);
                     break;
                 case NPC_LIVING_KNIGHT:
                     me->CastSpell(me, SPELL_INFORM_LIVING_KNIGHT, true);
                     break;
                 case NPC_LIVING_RIDER:
                     me->CastSpell(me, SPELL_INFORM_LIVING_RIDER, true);
                     break;
             }
         }
References Unit::CastSpell(), Object::GetEntry(), CreatureAI::me, NPC_LIVING_KNIGHT, NPC_LIVING_RIDER, NPC_LIVING_TRAINEE, SPELL_INFORM_LIVING_KNIGHT, SPELL_INFORM_LIVING_RIDER, and SPELL_INFORM_LIVING_TRAINEE.
KilledUnit()
void npc_boss_gothik_minion::npc_boss_gothik_minionAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from CreatureAI.
Definition at line 599 of file boss_gothik.cpp.
         {
             if (who->GetTypeId() == TYPEID_PLAYER && me->GetInstanceScript())
             {
                 me->GetInstanceScript()->SetData(DATA_IMMORTAL_FAIL, 0);
             }
         }
References DATA_IMMORTAL_FAIL, WorldObject::GetInstanceScript(), Object::GetTypeId(), CreatureAI::me, ZoneScript::SetData(), and TYPEID_PLAYER.
Reset()
void npc_boss_gothik_minion::npc_boss_gothik_minionAI::Reset () inline override virtual
Reimplemented from CombatAI.
Definition at line 533 of file boss_gothik.cpp.
         {
             me->SetReactState(REACT_AGGRESSIVE);
             me->SetNoCallAssistance(false);
             events.Reset();
         }
References CreatureAI::me, REACT_AGGRESSIVE, Creature::SetNoCallAssistance(), and Creature::SetReactState().
UpdateAI()
void npc_boss_gothik_minion::npc_boss_gothik_minionAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from CombatAI.
Definition at line 607 of file boss_gothik.cpp.
         {
             events.Update(diff);
             if (me->GetUnitState() == UNIT_STATE_CASTING)
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_DEATH_PLAGUE:
                     me->CastSpell(me->GetVictim(), SPELL_DEATH_PLAGUE, false);
                     events.RepeatEvent(urand(4000, 7000));
                     break;
                 case EVENT_ARCANE_EXPLOSION:
                     if (Unit* victim = me->GetVictim())
                     {
                         if (victim->IsWithinDist(me, 20))
{
                             me->CastSpell(victim, SPELL_ARCANE_EXPLOSION, false);
                         }
                     }
                     events.RepeatEvent(2500);
                     break;
                 case EVENT_SHADOW_MARK:
                     if (Unit* victim = me->GetVictim())
                     {
                         if (!victim->HasAura(SPELL_SHADOW_MARK))
{
                             me->CastSpell(me->GetVictim(), SPELL_SHADOW_MARK, false);
                         }
                     }
                     events.RepeatEvent(urand(5000, 7000));
                     break;
                 case EVENT_WHIRLWIND:
                     if (Unit* victim = me->GetVictim())
                     {
                         if (victim->IsWithinDist(me, 10))
{
                             me->CastSpell(victim, SPELL_WHIRLWIND, false);
                         }
                     }
                     events.RepeatEvent(urand(4000, 6000));
                     break;
                 case EVENT_SHADOW_BOLT_VOLLEY:
                     me->CastSpell(me->GetVictim(), SPELL_SHADOW_BOLT_VOLLEY, false);
                     events.RepeatEvent(5000);
                     break;
                 case EVENT_DRAIN_LIFE:
                     if (Unit* victim = me->GetVictim())
                     {
                         if (victim->IsWithinDist(me, 20))
{
                             me->CastSpell(victim, SPELL_DRAIN_LIFE, false);
                         }
                     }
                     events.RepeatEvent(urand(8000, 12000));
                     break;
                 case EVENT_UNHOLY_FRENZY:
                     me->AddAura(SPELL_UNHOLY_FRENZY, me);
                     events.RepeatEvent(urand(15000, 17000));
                     break;
                 case EVENT_STOMP:
                     if (Unit* victim = me->GetVictim())
                     {
                         if (victim->IsWithinDist(me, 10))
{
                             me->CastSpell(victim, SPELL_STOMP, false);
                         }
                     }
                     events.RepeatEvent(urand(4000, 9000));
                     break;
             }
             DoMeleeAttackIfReady();
         }
References Unit::AddAura(), Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), EVENT_ARCANE_EXPLOSION, EVENT_DEATH_PLAGUE, EVENT_DRAIN_LIFE, EVENT_SHADOW_BOLT_VOLLEY, EVENT_SHADOW_MARK, EVENT_STOMP, EVENT_UNHOLY_FRENZY, EVENT_WHIRLWIND, Unit::GetUnitState(), Unit::GetVictim(), CreatureAI::me, SPELL_ARCANE_EXPLOSION, SPELL_DEATH_PLAGUE, SPELL_DRAIN_LIFE, SPELL_SHADOW_BOLT_VOLLEY, SPELL_SHADOW_MARK, SPELL_STOMP, SPELL_UNHOLY_FRENZY, SPELL_WHIRLWIND, UNIT_STATE_CASTING, and urand().
Member Data Documentation
events
EventMap npc_boss_gothik_minion::npc_boss_gothik_minionAI::events
Definition at line 529 of file boss_gothik.cpp.
livingSide
bool npc_boss_gothik_minion::npc_boss_gothik_minionAI::livingSide
Definition at line 530 of file boss_gothik.cpp.
Referenced by IsOnSameSide(), and npc_boss_gothik_minionAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Naxxramas/boss_gothik.cpp