Azerotcore-wotlk: deps/SFMT/SFMT.h File Reference
SFMT.h File Reference
SIMD oriented Fast Mersenne Twister(SFMT) pseudorandom number generator using C structure.
#include <stdio.h>
#include <assert.h>
#include <inttypes.h>
#include "SFMT-params.h"
Classes
union W128_T
struct SFMT_T
Macros
#define SFMTST_H
#define PRIu64 "llu"
#define PRIx64 "llx"
Typedefs
typedef union W128_T w128_t
typedef struct SFMT_T sfmt_t
Functions
void sfmt_fill_array32 (sfmt_t *sfmt, uint32_t *array, int size)
void sfmt_fill_array64 (sfmt_t *sfmt, uint64_t *array, int size)
void sfmt_init_gen_rand (sfmt_t *sfmt, uint32_t seed)
void sfmt_init_by_array (sfmt_t *sfmt, uint32_t *init_key, int key_length)
const char * sfmt_get_idstring (sfmt_t *sfmt)
int sfmt_get_min_array_size32 (sfmt_t *sfmt)
int sfmt_get_min_array_size64 (sfmt_t *sfmt)
void sfmt_gen_rand_all (sfmt_t *sfmt)
static uint32_t sfmt_genrand_uint32 (sfmt_t *sfmt)
static uint64_t sfmt_genrand_uint64 (sfmt_t *sfmt)
static double sfmt_to_real1 (uint32_t v)
static double sfmt_genrand_real1 (sfmt_t *sfmt)
static double sfmt_to_real2 (uint32_t v)
static double sfmt_genrand_real2 (sfmt_t *sfmt)
static double sfmt_to_real3 (uint32_t v)
static double sfmt_genrand_real3 (sfmt_t *sfmt)
static double sfmt_to_res53 (uint64_t v)
static double sfmt_genrand_res53 (sfmt_t *sfmt)
static double sfmt_to_res53_mix (uint32_t x, uint32_t y)
static double sfmt_genrand_res53_mix (sfmt_t *sfmt)
Detailed Description
SIMD oriented Fast Mersenne Twister(SFMT) pseudorandom number generator using C structure.
Author
Mutsuo Saito (Hiroshima University)
Makoto Matsumoto (The University of Tokyo)
Copyright (C) 2006, 2007 Mutsuo Saito, Makoto Matsumoto and Hiroshima University. Copyright (C) 2012 Mutsuo Saito, Makoto Matsumoto, Hiroshima University and The University of Tokyo. All rights reserved.
The 3-clause BSD License is applied to this software, see LICENSE.txt
Note
We assume that your system has inttypes.h. If your system doesn't have inttypes.h, you have to typedef uint32_t and uint64_t, and you have to define PRIu64 and PRIx64 in this file as follows:
 typedef unsigned int uint32_t
 typedef unsigned long long uint64_t
 #define PRIu64 "llu"
 #define PRIx64 "llx"
uint32_t must be exactly 32-bit unsigned integer type (no more, no less), and uint64_t must be exactly 64-bit unsigned integer type. PRIu64 and PRIx64 are used for printf function to print 64-bit unsigned int and 64-bit unsigned int in hexadecimal format.
Definition in file SFMT.h.
Macro Definition Documentation
PRIu64
#define PRIu64 "llu"
Definition at line 62 of file SFMT.h.
PRIx64
#define PRIx64 "llx"
Definition at line 63 of file SFMT.h.
SFMTST_H
#define SFMTST_H
Definition at line 36 of file SFMT.h.
Typedef Documentation
sfmt_t
typedef struct SFMT_T sfmt_t
Definition at line 1 of file SFMT.h.
w128_t
typedef union W128_T w128_t
128-bit data type
Definition at line 1 of file SFMT.h.
Function Documentation
sfmt_fill_array32()
void sfmt_fill_array32 (sfmt_t * sfmt, uint32_t * array, int size)
This function generates pseudorandom 32-bit integers in the specified array[] by one call. The number of pseudorandom integers is specified by the argument size, which must be at least 624 and a multiple of four. The generation by this function is much faster than the following gen_rand function.
For initialization, init_gen_rand or init_by_array must be called before the first call of this function. This function can not be used after calling gen_rand function, without initialization.
Parameters
sfmt SFMT internal state
array an array where pseudorandom 32-bit integers are filled by this function. The pointer to the array must be "aligned" (namely, must be a multiple of 16) in the SIMD version, since it refers to the address of a 128-bit integer. In the standard C version, the pointer is arbitrary.
size the number of 32-bit pseudorandom integers to be generated. size must be a multiple of 4, and greater than or equal to (MEXP / 128 + 1) * 4.
Note
memalign or posix_memalign is available to get aligned memory. Mac OSX doesn't have these functions, but malloc of OSX returns the pointer to the aligned memory block.
Definition at line 293 of file SFMT.c.
{
     assert(sfmt->idx == SFMT_N32);
     assert(size % 4 == 0);
     assert(size >= SFMT_N32);
     gen_rand_array(sfmt, (w128_t *)array, size / 4);
     sfmt->idx = SFMT_N32;
 }
References array, assert(), gen_rand_array(), SFMT_T::idx, and SFMT_N32.
sfmt_fill_array64()
void sfmt_fill_array64 (sfmt_t * sfmt, uint64_t * array, int size)
This function generates pseudorandom 64-bit integers in the specified array[] by one call. The number of pseudorandom integers is specified by the argument size, which must be at least 312 and a multiple of two. The generation by this function is much faster than the following gen_rand function.
Parameters
sfmt SFMT internal state For initialization, init_gen_rand or init_by_array must be called before the first call of this function. This function can not be used after calling gen_rand function, without initialization.
array an array where pseudorandom 64-bit integers are filled by this function. The pointer to the array must be "aligned" (namely, must be a multiple of 16) in the SIMD version, since it refers to the address of a 128-bit integer. In the standard C version, the pointer is arbitrary.
size the number of 64-bit pseudorandom integers to be generated. size must be a multiple of 2, and greater than or equal to (MEXP / 128 + 1) * 2
Note
memalign or posix_memalign is available to get aligned memory. Mac OSX doesn't have these functions, but malloc of OSX returns the pointer to the aligned memory block.
Definition at line 329 of file SFMT.c.
{
     assert(sfmt->idx == SFMT_N32);
     assert(size % 2 == 0);
     assert(size >= SFMT_N64);
     gen_rand_array(sfmt, (w128_t *)array, size / 2);
     sfmt->idx = SFMT_N32;
 #if defined(BIG_ENDIAN64) && !defined(ONLY64)
     swap((w128_t *)array, size /2);
 #endif
 }
References array, assert(), gen_rand_array(), SFMT_T::idx, SFMT_N32, SFMT_N64, and swap().
sfmt_gen_rand_all()
void sfmt_gen_rand_all (sfmt_t * sfmt)
This function fills the internal state array with pseudorandom integers.
This function fills the internal state array with pseudorandom integers.
Parameters
sfmt SFMT internal state
Definition at line 68 of file SFMT-alti.h.
{
     int i;
     vector unsigned int r, r1, r2;
     r1 = sfmt->state[N - 2].s;
     r2 = sfmt->state[N - 1].s;
     for (i = 0; i < N - POS1; i++) {
     r = vec_recursion(sfmt->state[i].s, sfmt->state[i + POS1].s, r1, r2);
     sfmt->state[i].s = r;
     r1 = r2;
     r2 = r;
     }
     for (; i < N; i++) {
     r = vec_recursion(sfmt->state[i].s, sfmt->state[i + POS1 - N].s, r1, r2);
     sfmt->state[i].s = r;
     r1 = r2;
     r2 = r;
     }
 }
References do_recursion(), mm_recursion(), neon_recursion(), SFMT_N, SFMT_POS1, SFMT_T::state, and vec_recursion().
Referenced by sfmt_genrand_uint32(), and sfmt_genrand_uint64().
sfmt_genrand_real1()
static double sfmt_genrand_real1 (sfmt_t * sfmt) inline static
generates a random number on [0,1]-real-interval
Parameters
sfmt SFMT internal state
Returns
double on [0,1]-real-interval
Definition at line 204 of file SFMT.h.
 {
     return sfmt_to_real1(sfmt_genrand_uint32(sfmt));
 }
References sfmt_genrand_uint32(), and sfmt_to_real1().
sfmt_genrand_real2()
static double sfmt_genrand_real2 (sfmt_t * sfmt) inline static
generates a random number on [0,1)-real-interval
Parameters
sfmt SFMT internal state
Returns
double on [0,1)-real-interval
Definition at line 225 of file SFMT.h.
 {
     return sfmt_to_real2(sfmt_genrand_uint32(sfmt));
 }
References sfmt_genrand_uint32(), and sfmt_to_real2().
sfmt_genrand_real3()
static double sfmt_genrand_real3 (sfmt_t * sfmt) inline static
generates a random number on (0,1)-real-interval
Parameters
sfmt SFMT internal state
Returns
double on (0,1)-real-interval
Definition at line 246 of file SFMT.h.
 {
     return sfmt_to_real3(sfmt_genrand_uint32(sfmt));
 }
References sfmt_genrand_uint32(), and sfmt_to_real3().
sfmt_genrand_res53()
static double sfmt_genrand_res53 (sfmt_t * sfmt) inline static
generates a random number on [0,1) with 53-bit resolution
Parameters
sfmt SFMT internal state
Returns
double on [0,1) with 53-bit resolution
Definition at line 267 of file SFMT.h.
 {
     return sfmt_to_res53(sfmt_genrand_uint64(sfmt));
 }
References sfmt_genrand_uint64(), and sfmt_to_res53().
sfmt_genrand_res53_mix()
static double sfmt_genrand_res53_mix (sfmt_t * sfmt) inline static
generates a random number on [0,1) with 53-bit resolution using two 32bit integers.
Parameters
sfmt SFMT internal state
Returns
double on [0,1) with 53-bit resolution
Definition at line 291 of file SFMT.h.
 {
     uint32_t x, y;
     x = sfmt_genrand_uint32(sfmt);
     y = sfmt_genrand_uint32(sfmt);
     return sfmt_to_res53_mix(x, y);
 }
References sfmt_genrand_uint32(), sfmt_to_res53_mix(), G3D::x, and G3D::y.
sfmt_genrand_uint32()
static uint32_t sfmt_genrand_uint32 (sfmt_t * sfmt) inline static
This function generates and returns 32-bit pseudorandom number. init_gen_rand or init_by_array must be called before this function.
Parameters
sfmt SFMT internal state
Returns
32-bit pseudorandom number
Definition at line 139 of file SFMT.h.
{
     uint32_t r;
     uint32_t * psfmt32 = &sfmt->state[0].u[0];
     if (sfmt->idx >= SFMT_N32) {
         sfmt_gen_rand_all(sfmt);
         sfmt->idx = 0;
     }
     r = psfmt32[sfmt->idx++];
     return r;
 }
References SFMT_T::idx, sfmt_gen_rand_all(), SFMT_N32, SFMT_T::state, and W128_T::u.
Referenced by SFMTRand::RandomUInt32(), sfmt_genrand_real1(), sfmt_genrand_real2(), sfmt_genrand_real3(), and sfmt_genrand_res53_mix().
sfmt_genrand_uint64()
static uint64_t sfmt_genrand_uint64 (sfmt_t * sfmt) inline static
This function generates and returns 64-bit pseudorandom number. init_gen_rand or init_by_array must be called before this function. The function gen_rand64 should not be called after gen_rand32, unless an initialization is again executed.
Parameters
sfmt SFMT internal state
Returns
64-bit pseudorandom number
Definition at line 159 of file SFMT.h.
{
 #if defined(BIG_ENDIAN64) && !defined(ONLY64)
     uint32_t * psfmt32 = &sfmt->state[0].u[0];
     uint32_t r1, r2;
 #else
     uint64_t r;
 #endif
     uint64_t * psfmt64 = &sfmt->state[0].u64[0];
     assert(sfmt->idx % 2 == 0);
     if (sfmt->idx >= SFMT_N32) {
         sfmt_gen_rand_all(sfmt);
         sfmt->idx = 0;
     }
 #if defined(BIG_ENDIAN64) && !defined(ONLY64)
     r1 = psfmt32[sfmt->idx];
     r2 = psfmt32[sfmt->idx + 1];
     sfmt->idx += 2;
     return ((uint64_t)r2 << 32) | r1;
 #else
     r = psfmt64[sfmt->idx / 2];
     sfmt->idx += 2;
     return r;
 #endif
 }
References assert(), SFMT_T::idx, sfmt_gen_rand_all(), SFMT_N32, SFMT_T::state, W128_T::u, and W128_T::u64.
Referenced by sfmt_genrand_res53().
sfmt_get_idstring()
const char* sfmt_get_idstring (sfmt_t * sfmt)
This function returns the identification string. The string shows the word size, the Mersenne exponent, and all parameters of this generator.
Parameters
sfmt SFMT internal state
Definition at line 212 of file SFMT.c.
{
     UNUSED_VARIABLE(sfmt);
     return SFMT_IDSTR;
 }
References SFMT_IDSTR, and UNUSED_VARIABLE.
sfmt_get_min_array_size32()
int sfmt_get_min_array_size32 (sfmt_t * sfmt)
This function returns the minimum size of array used for fill_array32() function.
Parameters
sfmt SFMT internal state
Returns
minimum size of array used for fill_array32() function.
Definition at line 223 of file SFMT.c.
{
     UNUSED_VARIABLE(sfmt);
     return SFMT_N32;
 }
References SFMT_N32, and UNUSED_VARIABLE.
sfmt_get_min_array_size64()
int sfmt_get_min_array_size64 (sfmt_t * sfmt)
This function returns the minimum size of array used for fill_array64() function.
Parameters
sfmt SFMT internal state
Returns
minimum size of array used for fill_array64() function.
Definition at line 234 of file SFMT.c.
{
     UNUSED_VARIABLE(sfmt);
     return SFMT_N64;
 }
References SFMT_N64, and UNUSED_VARIABLE.
sfmt_init_by_array()
void sfmt_init_by_array (sfmt_t * sfmt, uint32_t * init_key, int key_length)
This function initializes the internal state array, with an array of 32-bit integers used as the seeds
Parameters
sfmt SFMT internal state
init_key the array of 32-bit integers, used as a seed.
key_length the length of init_key.
Definition at line 371 of file SFMT.c.
{
     int i, j, count;
     uint32_t r;
     int lag;
     int mid;
     int size = SFMT_N * 4;
     uint32_t *psfmt32 = &sfmt->state[0].u[0];
     if (size >= 623) {
         lag = 11;
     } else if (size >= 68) {
         lag = 7;
     } else if (size >= 39) {
         lag = 5;
     } else {
         lag = 3;
     }
     mid = (size - lag) / 2;
     memset(sfmt, 0x8b, sizeof(sfmt_t));
     if (key_length + 1 > SFMT_N32) {
         count = key_length + 1;
     } else {
         count = SFMT_N32;
     }
     r = func1(psfmt32[idxof(0)] ^ psfmt32[idxof(mid)]
               ^ psfmt32[idxof(SFMT_N32 - 1)]);
     psfmt32[idxof(mid)] += r;
     r += key_length;
     psfmt32[idxof(mid + lag)] += r;
     psfmt32[idxof(0)] = r;
     count--;
     for (i = 1, j = 0; (j < count) && (j < key_length); j++) {
         r = func1(psfmt32[idxof(i)] ^ psfmt32[idxof((i + mid) % SFMT_N32)]
                   ^ psfmt32[idxof((i + SFMT_N32 - 1) % SFMT_N32)]);
         psfmt32[idxof((i + mid) % SFMT_N32)] += r;
         r += init_key[j] + i;
         psfmt32[idxof((i + mid + lag) % SFMT_N32)] += r;
         psfmt32[idxof(i)] = r;
         i = (i + 1) % SFMT_N32;
     }
     for (; j < count; j++) {
         r = func1(psfmt32[idxof(i)] ^ psfmt32[idxof((i + mid) % SFMT_N32)]
                   ^ psfmt32[idxof((i + SFMT_N32 - 1) % SFMT_N32)]);
         psfmt32[idxof((i + mid) % SFMT_N32)] += r;
         r += i;
         psfmt32[idxof((i + mid + lag) % SFMT_N32)] += r;
         psfmt32[idxof(i)] = r;
         i = (i + 1) % SFMT_N32;
     }
     for (j = 0; j < SFMT_N32; j++) {
         r = func2(psfmt32[idxof(i)] + psfmt32[idxof((i + mid) % SFMT_N32)]
                   + psfmt32[idxof((i + SFMT_N32 - 1) % SFMT_N32)]);
         psfmt32[idxof((i + mid) % SFMT_N32)] ^= r;
         r -= i;
         psfmt32[idxof((i + mid + lag) % SFMT_N32)] ^= r;
         psfmt32[idxof(i)] = r;
         i = (i + 1) % SFMT_N32;
     }
     sfmt->idx = SFMT_N32;
     period_certification(sfmt);
 }
References count(), func1(), func2(), SFMT_T::idx, idxof(), memset, period_certification(), SFMT_N, SFMT_N32, SFMT_T::state, and W128_T::u.
Referenced by SFMTRand::SFMTRand().
sfmt_init_gen_rand()
void sfmt_init_gen_rand (sfmt_t * sfmt, uint32_t seed)
This function initializes the internal state array with a 32-bit integer seed.
Parameters
sfmt SFMT internal state
seed a 32-bit integer used as the seed.
Definition at line 349 of file SFMT.c.
{
     int i;
     uint32_t *psfmt32 = &sfmt->state[0].u[0];
     psfmt32[idxof(0)] = seed;
     for (i = 1; i < SFMT_N32; i++) {
         psfmt32[idxof(i)] = 1812433253UL * (psfmt32[idxof(i - 1)]
                                             ^ (psfmt32[idxof(i - 1)] >> 30))
             + i;
     }
     sfmt->idx = SFMT_N32;
     period_certification(sfmt);
 }
References SFMT_T::idx, idxof(), period_certification(), SFMT_N32, SFMT_T::state, and W128_T::u.
Referenced by SFMTRand::SFMTRand().
sfmt_to_real1()
static double sfmt_to_real1 (uint32_t v) inline static
converts an unsigned 32-bit number to a double on [0,1]-real-interval.
Parameters
v 32-bit unsigned integer
Returns
double on [0,1]-real-interval
Definition at line 193 of file SFMT.h.
 {
     return v * (1.0/4294967295.0);
     /* divided by 2^32-1 */
 }
Referenced by sfmt_genrand_real1().
sfmt_to_real2()
static double sfmt_to_real2 (uint32_t v) inline static
converts an unsigned 32-bit integer to a double on [0,1)-real-interval.
Parameters
v 32-bit unsigned integer
Returns
double on [0,1)-real-interval
Definition at line 214 of file SFMT.h.
 {
     return v * (1.0/4294967296.0);
     /* divided by 2^32 */
 }
Referenced by sfmt_genrand_real2().
sfmt_to_real3()
static double sfmt_to_real3 (uint32_t v) inline static
converts an unsigned 32-bit integer to a double on (0,1)-real-interval.
Parameters
v 32-bit unsigned integer
Returns
double on (0,1)-real-interval
Definition at line 235 of file SFMT.h.
 {
     return (((double)v) + 0.5)*(1.0/4294967296.0);
     /* divided by 2^32 */
 }
Referenced by sfmt_genrand_real3().
sfmt_to_res53()
static double sfmt_to_res53 (uint64_t v) inline static
converts an unsigned 32-bit integer to double on [0,1) with 53-bit resolution.
Parameters
v 32-bit unsigned integer
Returns
double on [0,1)-real-interval with 53-bit resolution.
Definition at line 257 of file SFMT.h.
 {
     return (v >> 11) * (1.0/9007199254740992.0);
 }
Referenced by sfmt_genrand_res53(), and sfmt_to_res53_mix().
sfmt_to_res53_mix()
static double sfmt_to_res53_mix (uint32_t x, uint32_t y) inline static
generates a random number on [0,1) with 53-bit resolution from two 32 bit integers
Definition at line 280 of file SFMT.h.
 {
     return sfmt_to_res53(x | ((uint64_t)y << 32));
 }
References sfmt_to_res53(), G3D::x, and G3D::y.
Referenced by sfmt_genrand_res53_mix().