Azerotcore-wotlk: G3D::GMutex Class Reference
G3D::GMutex Class Reference
Mutual exclusion lock used for synchronization.
#include <GMutex.h>
Public Member Functions
GMutex ()
~GMutex ()
void lock ()
bool tryLock ()
void unlock ()
Private Member Functions
GMutex (const GMutex &mlock)
GMutex & operator= (const GMutex &)
bool operator== (const GMutex &)
Private Attributes
pthread_mutex_t m_handle
pthread_mutexattr_t m_attr
Detailed Description
Mutual exclusion lock used for synchronization.
See also
G3D::GThread, G3D::AtomicInt32, G3D::Spinlock
Definition at line 76 of file GMutex.h.
Constructor & Destructor Documentation
GMutex() [1/2]
G3D::GMutex::GMutex (const GMutex & mlock) private
GMutex() [2/2]
G3D::GMutex::GMutex ()
Definition at line 215 of file GThread.cpp.
                {
 #ifdef G3D_WINDOWS
     ::InitializeCriticalSection(&m_handle);
 #else
     int ret = pthread_mutexattr_init(&m_attr);
     debugAssert(ret == 0);
     ret = pthread_mutexattr_settype(&m_attr, PTHREAD_MUTEX_RECURSIVE);
     debugAssert(ret == 0);
     ret = pthread_mutex_init(&m_handle, &m_attr);
     debugAssert(ret == 0);
 #endif
 }
References debugAssert, m_attr, m_handle, and ret.
~GMutex()
G3D::GMutex::~GMutex ()
Definition at line 228 of file GThread.cpp.
                 {
     //TODO: Debug check for locked
 #ifdef G3D_WINDOWS
     ::DeleteCriticalSection(&m_handle);
 #else
     int ret = pthread_mutex_destroy(&m_handle);
     debugAssert(ret == 0);
     ret = pthread_mutexattr_destroy(&m_attr);
     debugAssert(ret == 0);
 #endif
 }
References debugAssert, m_attr, m_handle, and ret.
Member Function Documentation
lock()
void G3D::GMutex::lock ()
Locks the mutex or blocks until available.
Definition at line 248 of file GThread.cpp.
                   {
 #ifdef G3D_WINDOWS
     ::EnterCriticalSection(&m_handle);
 #else
     pthread_mutex_lock(&m_handle);
 #endif
 }
References m_handle.
Referenced by G3D::FileSystem::cacheLifetime(), G3D::ThreadSet::clear(), G3D::FileSystem::clearCache(), G3D::ThreadSet::contains(), G3D::FileSystem::copyFile(), G3D::FileSystem::createDirectory(), G3D::FileSystem::currentDirectory(), G3D::FileSystem::exists(), G3D::FileSystem::fclose(), G3D::FileSystem::fopen(), G3D::FileSystem::getDirectories(), G3D::FileSystem::getFiles(), G3D::GMutexLock::GMutexLock(), G3D::ThreadSet::insert(), G3D::FileSystem::inZipfile(), G3D::FileSystem::isDirectory(), G3D::FileSystem::isFile(), G3D::FileSystem::isNewer(), G3D::FileSystem::isZipfile(), G3D::FileSystem::list(), G3D::FileSystem::markFileUsed(), G3D::ThreadSet::numStarted(), G3D::ThreadSet::remove(), G3D::ThreadSet::removeCompleted(), G3D::FileSystem::removeFile(), G3D::FileSystem::resolve(), G3D::FileSystem::setCacheLifetime(), G3D::ThreadSet::size(), G3D::FileSystem::size(), G3D::ThreadSet::start(), G3D::ThreadSet::terminate(), and G3D::ThreadSet::waitForCompletion().
operator=()
GMutex& G3D::GMutex::operator= (const GMutex &) private
operator==()
bool G3D::GMutex::operator== (const GMutex &) private
tryLock()
bool G3D::GMutex::tryLock ()
Locks the mutex if it not already locked. Returns true if lock successful, false otherwise.
Definition at line 240 of file GThread.cpp.
                      {
 #ifdef G3D_WINDOWS
     return (::TryEnterCriticalSection(&m_handle) != 0);
 #else
     return (pthread_mutex_trylock(&m_handle) == 0);
 #endif
 }
References m_handle.
unlock()
void G3D::GMutex::unlock ()
Unlocks the mutex.
Definition at line 256 of file GThread.cpp.
                     {
 #ifdef G3D_WINDOWS
     ::LeaveCriticalSection(&m_handle);
 #else
     pthread_mutex_unlock(&m_handle);
 #endif
 }
References m_handle.
Referenced by G3D::FileSystem::cacheLifetime(), G3D::ThreadSet::clear(), G3D::FileSystem::clearCache(), G3D::ThreadSet::contains(), G3D::FileSystem::copyFile(), G3D::FileSystem::createDirectory(), G3D::FileSystem::currentDirectory(), G3D::FileSystem::exists(), G3D::FileSystem::fclose(), G3D::FileSystem::fopen(), G3D::FileSystem::getDirectories(), G3D::FileSystem::getFiles(), G3D::ThreadSet::insert(), G3D::FileSystem::inZipfile(), G3D::FileSystem::isDirectory(), G3D::FileSystem::isFile(), G3D::FileSystem::isNewer(), G3D::FileSystem::isZipfile(), G3D::FileSystem::list(), G3D::FileSystem::markFileUsed(), G3D::ThreadSet::numStarted(), G3D::ThreadSet::remove(), G3D::ThreadSet::removeCompleted(), G3D::FileSystem::removeFile(), G3D::FileSystem::resolve(), G3D::FileSystem::setCacheLifetime(), G3D::ThreadSet::size(), G3D::FileSystem::size(), G3D::ThreadSet::start(), G3D::ThreadSet::terminate(), G3D::ThreadSet::waitForCompletion(), and G3D::GMutexLock::~GMutexLock().
Member Data Documentation
m_attr
pthread_mutexattr_t G3D::GMutex::m_attr private
Definition at line 82 of file GMutex.h.
Referenced by GMutex(), and ~GMutex().
m_handle
pthread_mutex_t G3D::GMutex::m_handle private
Definition at line 81 of file GMutex.h.
Referenced by GMutex(), lock(), tryLock(), unlock(), and ~GMutex().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/GMutex.h
deps/g3dlite/source/GThread.cpp