Azerotcore-wotlk: instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript Struct Reference
instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript Struct Reference
Public Member Functions
instance_culling_of_stratholme_InstanceMapScript (Map *pMap)
bool IsEncounterInProgress () const override
void FillInitialWorldStates (WorldPacket &data) override
void OnPlayerEnter (Player *plr) override
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 type) const override
ObjectGuid GetGuidData (uint32 identifier) const override
void Update (uint32 diff) override
void UpdateEventState ()
void ChromieWhisper (uint8 textId)
void Reposition (Creature *arthas)
void EnsureGridLoaded ()
std::string GetSaveData () override
void Load (const char *in) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void CreatureLooted (Creature *, LootType)
void SaveToDB ()
void OnCreatureRemove (Creature *creature) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual void ProcessEvent (WorldObject *, uint32)
Private Attributes
ObjectGuid _arthasGUID
ObjectGuid _infiniteGUID
ObjectGuid _shkafGateGUID
ObjectGuid _exitGateGUID
uint32 _encounterState
uint32 _crateCount
uint32 _showCrateTimer
uint32 _guardianTimer
bool _respawnAndReposition
uint32 _loadTimer
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Definition at line 36 of file instance_culling_of_stratholme.cpp.
Constructor & Destructor Documentation
instance_culling_of_stratholme_InstanceMapScript()
instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::instance_culling_of_stratholme_InstanceMapScript (Map * pMap) inline
Definition at line 38 of file instance_culling_of_stratholme.cpp.
                                                                     : InstanceScript(pMap)
         {
             // Instance
             _crateCount = 0;
             _showCrateTimer = 0;
             _guardianTimer = 0;
             _respawnAndReposition = false;
             _encounterState = COS_PROGRESS_NOT_STARTED;
             _loadTimer = 0;
         }
References _crateCount, _encounterState, _guardianTimer, _loadTimer, _respawnAndReposition, _showCrateTimer, and COS_PROGRESS_NOT_STARTED.
Member Function Documentation
ChromieWhisper()
void instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::ChromieWhisper (uint8 textId) inline
Definition at line 299 of file instance_culling_of_stratholme.cpp.
         {
             if (!instance->GetPlayers().isEmpty())
                 if (Player* player = instance->GetPlayers().getFirst()->GetSource())
                 {
                     Position pos = player->GetPosition();
                     if (Creature* cr = instance->SummonCreature(NPC_CHROMIE_MIDDLE, pos))
                     {
                         cr->SetVisible(false);
                         cr->DespawnOrUnsummon(1000);
                         sCreatureTextMgr->SendChat(cr, textId, player, CHAT_MSG_ADDON, LANG_ADDON, TEXT_RANGE_MAP);
                     }
                 }
         }
References CHAT_MSG_ADDON, MapRefMgr::getFirst(), Map::GetPlayers(), Position::GetPosition(), Reference< TO, FROM >::GetSource(), InstanceScript::instance, LinkedListHead::isEmpty(), LANG_ADDON, NPC_CHROMIE_MIDDLE, sCreatureTextMgr, Map::SummonCreature(), and TEXT_RANGE_MAP.
Referenced by Update(), and UpdateEventState().
EnsureGridLoaded()
void instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::EnsureGridLoaded () inline
Definition at line 353 of file instance_culling_of_stratholme.cpp.
         {
             instance->LoadGrid(LeaderIntroPos1.GetPositionX(), LeaderIntroPos1.GetPositionY());
             instance->LoadGrid(LeaderIntroPos2.GetPositionX(), LeaderIntroPos2.GetPositionY());
             instance->LoadGrid(LeaderIntroPos3.GetPositionX(), LeaderIntroPos3.GetPositionY());
             instance->LoadGrid(LeaderIntroPos4.GetPositionX(), LeaderIntroPos4.GetPositionY());
             instance->LoadGrid(LeaderIntroPos5.GetPositionX(), LeaderIntroPos5.GetPositionY());
             instance->LoadGrid(LeaderIntroPos6.GetPositionX(), LeaderIntroPos6.GetPositionY());
         }
References Position::GetPositionX(), Position::GetPositionY(), InstanceScript::instance, LeaderIntroPos1, LeaderIntroPos2, LeaderIntroPos3, LeaderIntroPos4, LeaderIntroPos5, LeaderIntroPos6, and Map::LoadGrid().
Referenced by OnPlayerEnter(), and Update().
FillInitialWorldStates()
void instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::FillInitialWorldStates (WorldPacket & data) inline override virtual
Reimplemented from InstanceScript.
Definition at line 54 of file instance_culling_of_stratholme.cpp.
         {
             data << uint32(WORLDSTATE_SHOW_CRATES) << uint32(0);
             data << uint32(WORLDSTATE_CRATES_REVEALED) << uint32(_crateCount);
             data << uint32(WORLDSTATE_WAVE_COUNT) << uint32(0);
             data << uint32(WORLDSTATE_TIME_GUARDIAN) << uint32(25);
             data << uint32(WORLDSTATE_TIME_GUARDIAN_SHOW) << uint32(0);
         }
References _crateCount, WORLDSTATE_CRATES_REVEALED, WORLDSTATE_SHOW_CRATES, WORLDSTATE_TIME_GUARDIAN, WORLDSTATE_TIME_GUARDIAN_SHOW, and WORLDSTATE_WAVE_COUNT.
GetData()
uint32 instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
Definition at line 180 of file instance_culling_of_stratholme.cpp.
         {
             switch (type)
             {
                 case DATA_ARTHAS_EVENT:
                     return _encounterState;
                 case DATA_GUARDIANTIME_EVENT:
                     return _guardianTimer;
             }
             return 0;
         }
References _encounterState, _guardianTimer, DATA_ARTHAS_EVENT, and DATA_GUARDIANTIME_EVENT.
Referenced by Reposition(), and SetData().
GetGuidData()
ObjectGuid instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::GetGuidData (uint32 identifier) const inline override virtual
Reimplemented from InstanceScript.
Definition at line 192 of file instance_culling_of_stratholme.cpp.
         {
             switch (identifier)
             {
                 case DATA_SHKAF_GATE:
                     return _shkafGateGUID;
                 case DATA_ARTHAS:
                     return _arthasGUID;
                 case DATA_EXIT_GATE:
                     return _exitGateGUID;
             }
             return ObjectGuid::Empty;
         }
References _arthasGUID, _exitGateGUID, _shkafGateGUID, DATA_ARTHAS, DATA_EXIT_GATE, DATA_SHKAF_GATE, and ObjectGuid::Empty.
GetSaveData()
std::string instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
Definition at line 363 of file instance_culling_of_stratholme.cpp.
         {
             OUT_SAVE_INST_DATA;
             std::ostringstream saveStream;
             saveStream << "C S " << _encounterState << ' ' << _guardianTimer;
             OUT_SAVE_INST_DATA_COMPLETE;
             return saveStream.str();
         }
References _encounterState, _guardianTimer, OUT_SAVE_INST_DATA, and OUT_SAVE_INST_DATA_COMPLETE.
IsEncounterInProgress()
bool instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::IsEncounterInProgress () const inline override virtual
Reimplemented from InstanceScript.
Definition at line 49 of file instance_culling_of_stratholme.cpp.
         {
             return false;
         }
Load()
void instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::Load (const char * in) inline override virtual
Reimplemented from InstanceScript.
Definition at line 374 of file instance_culling_of_stratholme.cpp.
         {
             if (!in)
             {
                 OUT_LOAD_INST_DATA_FAIL;
                 return;
             }
             OUT_LOAD_INST_DATA(in);
             char dataHead1, dataHead2;
             uint32 data0, data1;
             std::istringstream loadStream(in);
             loadStream >> dataHead1 >> dataHead2 >> data0 >> data1;
             if (dataHead1 == 'C' && dataHead2 == 'S')
             {
                 _encounterState = data0;
                 _guardianTimer = data1;
                 //UpdateEventState();
                 _loadTimer++;
             }
             else
                 OUT_LOAD_INST_DATA_FAIL;
             OUT_LOAD_INST_DATA_COMPLETE;
         }
References _encounterState, _guardianTimer, _loadTimer, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 74 of file instance_culling_of_stratholme.cpp.
         {
             switch (creature->GetEntry())
             {
                 case NPC_ARTHAS:
                     _arthasGUID = creature->GetGUID();
                     if (_encounterState == COS_PROGRESS_FINISHED)
                         creature->SetVisible(false);
                     else
                         Reposition(creature);
                     break;
                 case NPC_INFINITE:
                     _infiniteGUID = creature->GetGUID();
                     break;
             }
         }
References _arthasGUID, _encounterState, _infiniteGUID, COS_PROGRESS_FINISHED, Object::GetEntry(), Object::GetGUID(), NPC_ARTHAS, NPC_INFINITE, Reposition(), and Unit::SetVisible().
OnGameObjectCreate()
void instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
Definition at line 91 of file instance_culling_of_stratholme.cpp.
         {
             switch (go->GetEntry())
             {
                 case GO_SHKAF_GATE:
                     _shkafGateGUID = go->GetGUID();
                     if (_encounterState >= COS_PROGRESS_KILLED_EPOCH)
                         go->SetGoState(GO_STATE_ACTIVE);
                     break;
                 case GO_EXIT_GATE:
                     _exitGateGUID = go->GetGUID();
                     if (_encounterState == COS_PROGRESS_FINISHED)
                         go->SetGoState(GO_STATE_ACTIVE);
                     break;
             }
         }
References _encounterState, _exitGateGUID, _shkafGateGUID, COS_PROGRESS_FINISHED, COS_PROGRESS_KILLED_EPOCH, Object::GetEntry(), Object::GetGUID(), GO_EXIT_GATE, GO_SHKAF_GATE, GO_STATE_ACTIVE, and GameObject::SetGoState().
OnPlayerEnter()
void instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::OnPlayerEnter (Player * plr) inline override virtual
Reimplemented from InstanceScript.
Definition at line 63 of file instance_culling_of_stratholme.cpp.
         {
             if (instance->GetPlayersCountExceptGMs() == 1)
                 SetData(DATA_ARTHAS_REPOSITION, 2);
             EnsureGridLoaded();
             if (plr->getRace() != RACE_HUMAN && plr->getRace() != RACE_DWARF && plr->getRace() != RACE_GNOME)
                 plr->CastSpell(plr, ((plr->getGender() == GENDER_MALE) ? SPELL_HUMAN_MALE : SPELL_HUMAN_FEMALE), true);
         }
References Unit::CastSpell(), DATA_ARTHAS_REPOSITION, EnsureGridLoaded(), GENDER_MALE, Unit::getGender(), Map::GetPlayersCountExceptGMs(), Unit::getRace(), InstanceScript::instance, RACE_DWARF, RACE_GNOME, RACE_HUMAN, SetData(), SPELL_HUMAN_FEMALE, and SPELL_HUMAN_MALE.
Reposition()
void instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::Reposition (Creature * arthas) inline
Definition at line 314 of file instance_culling_of_stratholme.cpp.
         {
             switch (GetData(DATA_ARTHAS_EVENT))
             {
                 case COS_PROGRESS_FINISHED_INTRO:
                     arthas->UpdatePosition(LeaderIntroPos2, true);
                     arthas->SetHomePosition(LeaderIntroPos2);
                     arthas->SetFacingTo(LeaderIntroPos2.GetOrientation());
                     break;
                 case COS_PROGRESS_FINISHED_CITY_INTRO:
                 case COS_PROGRESS_KILLED_MEATHOOK:
                 case COS_PROGRESS_KILLED_SALRAMM:
                     arthas->UpdatePosition(LeaderIntroPos2special, true);
                     arthas->SetHomePosition(LeaderIntroPos2special);
                     arthas->SetFacingTo(LeaderIntroPos2special.GetOrientation());
                     break;
                 case COS_PROGRESS_REACHED_TOWN_HALL:
                     arthas->UpdatePosition(LeaderIntroPos3, true);
                     arthas->SetHomePosition(LeaderIntroPos3);
                     arthas->SetFacingTo(LeaderIntroPos3.GetOrientation());
                     break;
                 case COS_PROGRESS_KILLED_EPOCH:
                     arthas->UpdatePosition(LeaderIntroPos4, true);
                     arthas->SetHomePosition(LeaderIntroPos4);
                     arthas->SetFacingTo(LeaderIntroPos4.GetOrientation());
                     break;
                 case COS_PROGRESS_LAST_CITY:
                     arthas->UpdatePosition(LeaderIntroPos5, true);
                     arthas->SetHomePosition(LeaderIntroPos5);
                     arthas->SetFacingTo(LeaderIntroPos5.GetOrientation());
                     break;
                 case COS_PROGRESS_BEFORE_MALGANIS:
                     arthas->UpdatePosition(LeaderIntroPos6, true);
                     arthas->SetHomePosition(LeaderIntroPos6);
                     arthas->SetFacingTo(LeaderIntroPos6.GetOrientation());
                     break;
             }
         }
References COS_PROGRESS_BEFORE_MALGANIS, COS_PROGRESS_FINISHED_CITY_INTRO, COS_PROGRESS_FINISHED_INTRO, COS_PROGRESS_KILLED_EPOCH, COS_PROGRESS_KILLED_MEATHOOK, COS_PROGRESS_KILLED_SALRAMM, COS_PROGRESS_LAST_CITY, COS_PROGRESS_REACHED_TOWN_HALL, DATA_ARTHAS_EVENT, GetData(), Position::GetOrientation(), LeaderIntroPos2, LeaderIntroPos2special, LeaderIntroPos3, LeaderIntroPos4, LeaderIntroPos5, LeaderIntroPos6, Unit::SetFacingTo(), Creature::SetHomePosition(), and Unit::UpdatePosition().
Referenced by OnCreatureCreate(), and SetData().
SetData()
void instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
Definition at line 108 of file instance_culling_of_stratholme.cpp.
         {
             switch (type)
             {
                 case DATA_SHOW_CRATES:
                     DoUpdateWorldState(WORLDSTATE_SHOW_CRATES, data);
                     return;
                 case DATA_SHOW_INFINITE_TIMER:
                     if (!instance->IsHeroic() || !_guardianTimer)
                         return;
                     DoUpdateWorldState(WORLDSTATE_TIME_GUARDIAN_SHOW, data);
                     DoUpdateWorldState(WORLDSTATE_TIME_GUARDIAN, uint32(_guardianTimer / (MINUTE * IN_MILLISECONDS)));
                     if (data == 0)
                     {
                         _guardianTimer = 0;
                         SaveToDB();
                     }
                     else if (!_infiniteGUID)
                         instance->SummonCreature(NPC_INFINITE, EventPos[EVENT_SRC_CORRUPTOR]);
                     return;
                 case DATA_START_WAVES:
                     DoUpdateWorldState(WORLDSTATE_WAVE_COUNT, 1);
                     if (instance->IsHeroic())
                     {
                         DoUpdateWorldState(WORLDSTATE_TIME_GUARDIAN_SHOW, true);
                         _guardianTimer = 26 * MINUTE * IN_MILLISECONDS;
                         if (!_infiniteGUID)
                             instance->SummonCreature(NPC_INFINITE, EventPos[EVENT_SRC_CORRUPTOR]);
                     }
                     return;
                 case DATA_CRATE_COUNT:
                     _crateCount++;
                     if (_crateCount == 5)
                     {
                         Map::PlayerList const& PlayerList = instance->GetPlayers();
                         if (!PlayerList.isEmpty())
                             for (Map::PlayerList::const_iterator i = PlayerList.begin(); i != PlayerList.end(); ++i)
                                 i->GetSource()->KilledMonsterCredit(NPC_GRAIN_CREATE_TRIGGER);
                         _showCrateTimer++;
                         if (GetData(DATA_ARTHAS_EVENT) < COS_PROGRESS_CRATES_FOUND)
                             SetData(DATA_ARTHAS_EVENT, COS_PROGRESS_CRATES_FOUND);
                     }
                     DoUpdateWorldState(WORLDSTATE_CRATES_REVEALED, _crateCount);
                     return;
                 case DATA_ARTHAS_EVENT:
                     // Start Event
                     _encounterState = data;
                     if (data == COS_PROGRESS_START_INTRO)
                     {
                         if (Creature* arthas = instance->GetCreature(_arthasGUID))
                             arthas->AI()->DoAction(ACTION_START_EVENT);
                     }
                     else if (data == COS_PROGRESS_KILLED_SALRAMM)
                     {
                         if (Creature* arthas = instance->GetCreature(_arthasGUID))
                             arthas->AI()->DoAction(ACTION_KILLED_SALRAMM);
                     }
                     break;
                 case DATA_ARTHAS_REPOSITION:
                     if (data == 2)
                         _respawnAndReposition = true;
                     else if (Creature* arthas = instance->GetCreature(_arthasGUID))
                         Reposition(arthas);
                     return;
             }
             if (type == DATA_ARTHAS_EVENT)
                 SaveToDB();
         }
References _arthasGUID, _crateCount, _encounterState, _guardianTimer, _infiniteGUID, _respawnAndReposition, _showCrateTimer, ACTION_KILLED_SALRAMM, ACTION_START_EVENT, MapRefMgr::begin(), COS_PROGRESS_CRATES_FOUND, COS_PROGRESS_KILLED_SALRAMM, COS_PROGRESS_START_INTRO, DATA_ARTHAS_EVENT, DATA_ARTHAS_REPOSITION, DATA_CRATE_COUNT, DATA_SHOW_CRATES, DATA_SHOW_INFINITE_TIMER, DATA_START_WAVES, InstanceScript::DoUpdateWorldState(), MapRefMgr::end(), EVENT_SRC_CORRUPTOR, EventPos, Map::GetCreature(), GetData(), Map::GetPlayers(), IN_MILLISECONDS, InstanceScript::instance, LinkedListHead::isEmpty(), Map::IsHeroic(), MINUTE, NPC_GRAIN_CREATE_TRIGGER, NPC_INFINITE, Reposition(), InstanceScript::SaveToDB(), Map::SummonCreature(), WORLDSTATE_CRATES_REVEALED, WORLDSTATE_SHOW_CRATES, WORLDSTATE_TIME_GUARDIAN, WORLDSTATE_TIME_GUARDIAN_SHOW, and WORLDSTATE_WAVE_COUNT.
Referenced by OnPlayerEnter().
Update()
void instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::Update (uint32 diff) inline override virtual
Reimplemented from InstanceScript.
Definition at line 207 of file instance_culling_of_stratholme.cpp.
         {
             if (_loadTimer)
             {
                 _loadTimer += diff;
                 if (_loadTimer > 3000)
                 {
                     UpdateEventState();
                     _loadTimer = 0;
                 }
             }
             // Used when arthas dies
             if (_respawnAndReposition)
             {
                 if (Creature* arthas = instance->GetCreature(_arthasGUID))
                 {
                     if (!arthas->IsAlive())
                     {
                         EnsureGridLoaded();
                         arthas->setDeathState(DEAD);
                         arthas->Respawn();
                     }
                     else
                     {
                         arthas->AI()->Reset();
                         _respawnAndReposition = false;
                     }
                 }
             }
             // Used after 5-th crates is revealed
             if (_showCrateTimer)
             {
                 _showCrateTimer += diff;
                 if (_showCrateTimer >= 20000)
                 {
                     UpdateEventState();
                     _showCrateTimer = 0; // just to be sure
                 }
             }
             // Used to display how much time players have
             if (_guardianTimer)
             {
                 uint32 div = uint32(_guardianTimer / (MINUTE * IN_MILLISECONDS));
                 _guardianTimer -= diff;
                 uint32 divAfter = uint32(_guardianTimer / (MINUTE * IN_MILLISECONDS));
                 if (divAfter == 0)
                 {
                     _guardianTimer = 0;
                     DoUpdateWorldState(WORLDSTATE_TIME_GUARDIAN_SHOW, 0);
                     // Inform infinite we run out of time
                     if (instance->IsHeroic() && _infiniteGUID)
                         if (Creature* cr = instance->GetCreature(_infiniteGUID))
                             cr->AI()->DoAction(ACTION_RUN_OUT_OF_TIME);
                 }
                 else if (div > divAfter)
                 {
                     if (divAfter == 5)
                         ChromieWhisper(1);
                     else if (divAfter == 1)
                         ChromieWhisper(2);
                     DoUpdateWorldState(WORLDSTATE_TIME_GUARDIAN, divAfter);
                     SaveToDB();
                 }
             }
         }
References _arthasGUID, _guardianTimer, _infiniteGUID, _loadTimer, _respawnAndReposition, _showCrateTimer, ACTION_RUN_OUT_OF_TIME, ChromieWhisper(), DEAD, InstanceScript::DoUpdateWorldState(), EnsureGridLoaded(), Map::GetCreature(), IN_MILLISECONDS, InstanceScript::instance, Map::IsHeroic(), MINUTE, InstanceScript::SaveToDB(), UpdateEventState(), WORLDSTATE_TIME_GUARDIAN, and WORLDSTATE_TIME_GUARDIAN_SHOW.
UpdateEventState()
void instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::UpdateEventState () inline
Definition at line 278 of file instance_culling_of_stratholme.cpp.
         {
             if (_encounterState > COS_PROGRESS_NOT_STARTED)
             {
                 // Summon Chromie and global whisper
                 instance->SummonCreature(NPC_CHROMIE_MIDDLE, EventPos[EVENT_POS_CHROMIE]);
                 instance->SummonCreature(NPC_HOURGLASS, EventPos[EVENT_POS_HOURGLASS]);
                 if (_encounterState == COS_PROGRESS_CRATES_FOUND ||
                         _encounterState == COS_PROGRESS_START_INTRO)
                 {
                     ChromieWhisper(0);
                     // hide crates count
                     DoUpdateWorldState(WORLDSTATE_SHOW_CRATES, 0);
                     _showCrateTimer = 0;
                     _encounterState = COS_PROGRESS_CRATES_FOUND;
                 }
             }
         }
References _encounterState, _showCrateTimer, ChromieWhisper(), COS_PROGRESS_CRATES_FOUND, COS_PROGRESS_NOT_STARTED, COS_PROGRESS_START_INTRO, InstanceScript::DoUpdateWorldState(), EVENT_POS_CHROMIE, EVENT_POS_HOURGLASS, EventPos, InstanceScript::instance, NPC_CHROMIE_MIDDLE, NPC_HOURGLASS, Map::SummonCreature(), and WORLDSTATE_SHOW_CRATES.
Referenced by Update().
Member Data Documentation
_arthasGUID
ObjectGuid instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::_arthasGUID private
Definition at line 406 of file instance_culling_of_stratholme.cpp.
Referenced by GetGuidData(), OnCreatureCreate(), SetData(), and Update().
_crateCount
uint32 instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::_crateCount private
Definition at line 413 of file instance_culling_of_stratholme.cpp.
Referenced by FillInitialWorldStates(), instance_culling_of_stratholme_InstanceMapScript(), and SetData().
_encounterState
uint32 instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::_encounterState private
Definition at line 412 of file instance_culling_of_stratholme.cpp.
Referenced by GetData(), GetSaveData(), instance_culling_of_stratholme_InstanceMapScript(), Load(), OnCreatureCreate(), OnGameObjectCreate(), SetData(), and UpdateEventState().
_exitGateGUID
ObjectGuid instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::_exitGateGUID private
Definition at line 411 of file instance_culling_of_stratholme.cpp.
Referenced by GetGuidData(), and OnGameObjectCreate().
_guardianTimer
uint32 instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::_guardianTimer private
Definition at line 415 of file instance_culling_of_stratholme.cpp.
Referenced by GetData(), GetSaveData(), instance_culling_of_stratholme_InstanceMapScript(), Load(), SetData(), and Update().
_infiniteGUID
ObjectGuid instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::_infiniteGUID private
Definition at line 407 of file instance_culling_of_stratholme.cpp.
Referenced by OnCreatureCreate(), SetData(), and Update().
_loadTimer
uint32 instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::_loadTimer private
Definition at line 418 of file instance_culling_of_stratholme.cpp.
Referenced by instance_culling_of_stratholme_InstanceMapScript(), Load(), and Update().
_respawnAndReposition
bool instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::_respawnAndReposition private
Definition at line 417 of file instance_culling_of_stratholme.cpp.
Referenced by instance_culling_of_stratholme_InstanceMapScript(), SetData(), and Update().
_shkafGateGUID
ObjectGuid instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::_shkafGateGUID private
Definition at line 410 of file instance_culling_of_stratholme.cpp.
Referenced by GetGuidData(), and OnGameObjectCreate().
_showCrateTimer
uint32 instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::_showCrateTimer private
Definition at line 414 of file instance_culling_of_stratholme.cpp.
Referenced by instance_culling_of_stratholme_InstanceMapScript(), SetData(), Update(), and UpdateEventState().
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/CavernsOfTime/CullingOfStratholme/instance_culling_of_stratholme.cpp