Azerotcore-wotlk: npc_doctor Class Reference
npc_doctor Class Reference
Classes
struct npc_doctorAI
Public Member Functions
npc_doctor ()
bool OnQuestAccept (Player *player, Creature *creature, Quest const *quest) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 895 of file npcs_special.cpp.
Constructor & Destructor Documentation
npc_doctor()
npc_doctor::npc_doctor () inline
Definition at line 898 of file npcs_special.cpp.
 : CreatureScript("npc_doctor") { }
Referenced by AddSC_npcs_special().
Member Function Documentation
GetAI()
CreatureAI* npc_doctor::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 1029 of file npcs_special.cpp.
     {
         return new npc_doctorAI(creature);
     }
OnQuestAccept()
bool npc_doctor::OnQuestAccept (Player * player, Creature * creature, Quest const * quest) inline override virtual
Reimplemented from CreatureScript.
Definition at line 1021 of file npcs_special.cpp.
     {
         if ((quest->GetQuestId() == 6624) || (quest->GetQuestId() == 6622))
             CAST_AI(npc_doctor::npc_doctorAI, creature->AI())->BeginEvent(player);
         return true;
     }
References Creature::AI(), CAST_AI, and Quest::GetQuestId().
The documentation for this class was generated from the following file:
src/server/scripts/World/npcs_special.cpp