Azerotcore-wotlk: brann_bronzebeard::brann_bronzebeardAI Struct Reference
brann_bronzebeard::brann_bronzebeardAI Struct Reference
Public Member Functions
brann_bronzebeardAI (Creature *c)
void DespawnHeads ()
void SwitchHeadVisaul (uint8 headMask, bool activate)
void ResetEvent ()
void WaypointReached (uint32 id) override
void InitializeEvent ()
Creature * GetAbedneum ()
Creature * GetMarnak ()
Creature * GetKaddrak ()
void MoveInLineOfSight (Unit *) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void Reset () override
void DoAction (int32 action) override
void JustSummoned (Creature *cr) override
void UpdateEscortAI (uint32 diff) override
void SummonCreatures (uint32 entry, uint8 count)
void JustDied (Unit *) override
Public Member Functions inherited from npc_escortAI
npc_escortAI (Creature *creature)
~npc_escortAI () override
void AttackStart (Unit *who) override
void JustRespawned () override
void ReturnToLastPoint ()
void EnterEvadeMode () override
void UpdateAI (uint32 diff) override
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
virtual void WaypointStart (uint32)
void Start (bool isActiveAttacker=true, bool run=false, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetRun (bool on=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void KilledUnit (Unit *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
EventMap events
SummonList summons
ObjectGuid AbedneumGUID
ObjectGuid MarnakGUID
ObjectGuid KaddrakGUID
uint8 WaveNum
bool TalkEvent
uint32 SpeechCount
uint32 SpeechPause
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from npc_escortAI
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 235 of file brann_bronzebeard.cpp.
Constructor & Destructor Documentation
brann_bronzebeardAI()
brann_bronzebeard::brann_bronzebeardAI::brann_bronzebeardAI (Creature * c) inline
Definition at line 237 of file brann_bronzebeard.cpp.
                                          : npc_escortAI(c), summons(me)
         {
             pInstance = c->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), and pInstance.
Member Function Documentation
DamageTaken()
void brann_bronzebeard::brann_bronzebeardAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 304 of file brann_bronzebeard.cpp.
         {
             if (damage && pInstance)
                 pInstance->SetData(DATA_BRANN_ACHIEVEMENT, false);
         }
References DATA_BRANN_ACHIEVEMENT, pInstance, and ZoneScript::SetData().
DespawnHeads()
void brann_bronzebeard::brann_bronzebeardAI::DespawnHeads () inline
Definition at line 253 of file brann_bronzebeard.cpp.
         {
             Creature* cr;
             if ((cr = GetAbedneum())) cr->DespawnOrUnsummon();
             if ((cr = GetMarnak())) cr->DespawnOrUnsummon();
             if ((cr = GetKaddrak())) cr->DespawnOrUnsummon();
             SwitchHeadVisaul(0x7, false);
         }
References Creature::DespawnOrUnsummon(), GetAbedneum(), GetKaddrak(), GetMarnak(), and SwitchHeadVisaul().
Referenced by ResetEvent().
DoAction()
void brann_bronzebeard::brann_bronzebeardAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 331 of file brann_bronzebeard.cpp.
         {
             switch (action)
             {
                 case ACTION_START_EVENT:
                     Start(false, true, ObjectGuid::Empty, 0, true, false);
                     break;
                 case ACTION_START_TRIBUNAL:
                     {
                         Map::PlayerList const& PlayerList = me->GetMap()->GetPlayers();
                         if (!PlayerList.isEmpty())
                             for (Map::PlayerList::const_iterator i = PlayerList.begin(); i != PlayerList.end(); ++i)
{
                                 me->SetFaction(i->GetSource()->GetFaction());
                                 break;
                             }
                         SetEscortPaused(false);
                         InitializeEvent();
                         me->SetUInt32Value(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_NONE);
                         break;
                     }
                 case ACTION_GO_TO_SJONNIR:
                     SetEscortPaused(false);
                     ResetEvent();
                     me->SetUInt32Value(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_NONE);
                     break;
                 case ACTION_START_SJONNIR_FIGHT:
                     me->SetFaction(FACTION_FRIENDLY);
                     me->Yell("Don't worry! Ol' Brann's got yer back! Keep that metal monstrosity busy, and I'll see if I can't sweet talk this machine into helping ye!", LANG_UNIVERSAL);
                     me->PlayDirectSound(14274);
                     SetEscortPaused(false);
                     break;
                 case ACTION_SJONNIR_DEAD:
                     me->Yell("Loken? That's downright bothersome... We might've neutralized the iron dwarves, but I'd lay odds there's another machine somewhere else churnin' out a whole mess o' these iron vrykul!", LANG_UNIVERSAL);
                     me->PlayDirectSound(14278);
                     events.ScheduleEvent(EVENT_END, 14000);
                     break;
                 case ACTION_ENTEREVADEMODE:
                     RemoveEscortState(0x7); // all states
                     me->SetHomePosition(1077.41f, 474.16f, 207.8f, 2.70526f);
                     me->UpdatePosition(1077.41f, 474.16f, 207.9f, 2.70526f, true);
                     me->StopMovingOnCurrentPos();
                     Reset();
                     break;
                 case ACTION_WIPE_START:
                     Start(false, true, ObjectGuid::Empty, 0, true, false);
                     SetNextWaypoint(20, false);
                     ResetEvent();
                     me->SetUInt32Value(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_NONE);
                     break;
                 case ACTION_OPEN_DOOR:
                     if (GameObject* door = ObjectAccessor::GetGameObject(*me, pInstance->GetGuidData(GO_SJONNIR_DOOR)))
                         door->SetGoState(GO_STATE_ACTIVE);
                     SetEscortPaused(false);
                     me->RemoveAura(58506);
                     break;
             }
         }
References ACTION_ENTEREVADEMODE, ACTION_GO_TO_SJONNIR, ACTION_OPEN_DOOR, ACTION_SJONNIR_DEAD, ACTION_START_EVENT, ACTION_START_SJONNIR_FIGHT, ACTION_START_TRIBUNAL, ACTION_WIPE_START, MapRefMgr::begin(), ObjectGuid::Empty, MapRefMgr::end(), EVENT_END, FACTION_FRIENDLY, ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), Map::GetPlayers(), GO_SJONNIR_DOOR, GO_STATE_ACTIVE, InitializeEvent(), LinkedListHead::isEmpty(), LANG_UNIVERSAL, ScriptedAI::me, pInstance, WorldObject::PlayDirectSound(), Unit::RemoveAura(), npc_escortAI::RemoveEscortState(), Reset(), ResetEvent(), npc_escortAI::SetEscortPaused(), Unit::SetFaction(), Creature::SetHomePosition(), npc_escortAI::SetNextWaypoint(), Object::SetUInt32Value(), npc_escortAI::Start(), Unit::StopMovingOnCurrentPos(), UNIT_NPC_FLAG_NONE, UNIT_NPC_FLAGS, Unit::UpdatePosition(), and Unit::Yell().
GetAbedneum()
Creature* brann_bronzebeard::brann_bronzebeardAI::GetAbedneum () inline
Definition at line 299 of file brann_bronzebeard.cpp.
 { return ObjectAccessor::GetCreature(*me, AbedneumGUID); }
References AbedneumGUID, ObjectAccessor::GetCreature(), and ScriptedAI::me.
Referenced by DespawnHeads(), and UpdateEscortAI().
GetKaddrak()
Creature* brann_bronzebeard::brann_bronzebeardAI::GetKaddrak () inline
Definition at line 301 of file brann_bronzebeard.cpp.
 { return ObjectAccessor::GetCreature(*me, KaddrakGUID); }
References ObjectAccessor::GetCreature(), KaddrakGUID, and ScriptedAI::me.
Referenced by DespawnHeads(), and UpdateEscortAI().
GetMarnak()
Creature* brann_bronzebeard::brann_bronzebeardAI::GetMarnak () inline
Definition at line 300 of file brann_bronzebeard.cpp.
 { return ObjectAccessor::GetCreature(*me, MarnakGUID); }
References ObjectAccessor::GetCreature(), MarnakGUID, and ScriptedAI::me.
Referenced by DespawnHeads(), and UpdateEscortAI().
InitializeEvent()
void brann_bronzebeard::brann_bronzebeardAI::InitializeEvent ()
Definition at line 615 of file brann_bronzebeard.cpp.
 {
     Creature* cr = nullptr;
     if ((cr = me->SummonCreature(NPC_KADDRAK, 923.7f, 326.9f, 219.5f, 2.1f, TEMPSUMMON_TIMED_DESPAWN, 580000)))
     {
         cr->SetInCombatWithZone();
         KaddrakGUID = cr->GetGUID();
     }
     if ((cr = me->SummonCreature(NPC_MARNAK, 895.974f, 363.571f, 219.337f, 5.5f, TEMPSUMMON_TIMED_DESPAWN, 580000)))
     {
         cr->SetInCombatWithZone();
         MarnakGUID = cr->GetGUID();
     }
     if ((cr = me->SummonCreature(NPC_ABEDNEUM, 892.25f, 331.25f, 223.86f, 0.6f, TEMPSUMMON_TIMED_DESPAWN, 580000)))
     {
         cr->SetInCombatWithZone();
         AbedneumGUID = cr->GetGUID();
     }
     TalkEvent = true;
     events.Reset();
     events.ScheduleEvent(EVENT_SUMMON_MONSTERS, 21000);
     events.ScheduleEvent(EVENT_KADDRAK_HEAD, 20000);
     events.ScheduleEvent(EVENT_MARNAK_HEAD, 105000);
     events.ScheduleEvent(EVENT_ABEDNEUM_HEAD, 205000);
     events.ScheduleEvent(EVENT_TRIBUNAL_END, 315000);
     // Viusals
     events.ScheduleEvent(EVENT_KADDRAK_VISUAL, 20000);
     events.ScheduleEvent(EVENT_MARNAK_VISUAL, 105000);
     events.ScheduleEvent(EVENT_ABEDNEUM_VISUAL, 205000);
 }
References AbedneumGUID, EVENT_ABEDNEUM_HEAD, EVENT_ABEDNEUM_VISUAL, EVENT_KADDRAK_HEAD, EVENT_KADDRAK_VISUAL, EVENT_MARNAK_HEAD, EVENT_MARNAK_VISUAL, EVENT_SUMMON_MONSTERS, EVENT_TRIBUNAL_END, Object::GetGUID(), KaddrakGUID, MarnakGUID, ScriptedAI::me, NPC_ABEDNEUM, NPC_KADDRAK, NPC_MARNAK, Creature::SetInCombatWithZone(), WorldObject::SummonCreature(), TalkEvent, and TEMPSUMMON_TIMED_DESPAWN.
Referenced by DoAction().
JustDied()
void brann_bronzebeard::brann_bronzebeardAI::JustDied (Unit *) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 597 of file brann_bronzebeard.cpp.
         {
             ResetEvent();
             if(pInstance)
             {
                 if (Creature* brann = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_BRANN)))
                 {
                     brann->setDeathState(JUST_DIED);
                     brann->Respawn();
                     brann->AI()->DoAction(5);
                 }
                 if (pInstance->GetData(BOSS_TRIBUNAL_OF_AGES) != DONE)
                     pInstance->SetData(BOSS_TRIBUNAL_OF_AGES, NOT_STARTED);
             }
         }
References BOSS_TRIBUNAL_OF_AGES, DONE, ObjectAccessor::GetCreature(), ZoneScript::GetData(), InstanceScript::GetGuidData(), JUST_DIED, ScriptedAI::me, NOT_STARTED, NPC_BRANN, pInstance, ResetEvent(), and ZoneScript::SetData().
JustSummoned()
void brann_bronzebeard::brann_bronzebeardAI::JustSummoned (Creature * cr) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 391 of file brann_bronzebeard.cpp.
         {
             if (cr->GetEntry() == NPC_ABEDNEUM || cr->GetEntry() == NPC_KADDRAK || cr->GetEntry() == NPC_MARNAK)
                 cr->SetCanFly(true);
             else
                 summons.Summon(cr);
         }
References Object::GetEntry(), NPC_ABEDNEUM, NPC_KADDRAK, NPC_MARNAK, Creature::SetCanFly(), SummonList::Summon(), and summons.
MoveInLineOfSight()
void brann_bronzebeard::brann_bronzebeardAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 303 of file brann_bronzebeard.cpp.
 { }
Reset()
void brann_bronzebeard::brann_bronzebeardAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 310 of file brann_bronzebeard.cpp.
         {
             RemoveEscortState(0x7); // all states
             SetDespawnAtFar(false);
             SetDespawnAtEnd(false);
             ResetEvent();
             me->SetFaction(FACTION_FRIENDLY);
             me->SetReactState(REACT_PASSIVE);
             me->SetUInt32Value(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP | UNIT_NPC_FLAG_QUESTGIVER);
             if(pInstance)
             {
                 pInstance->SetData(BRANN_BRONZEBEARD, 1);
                 pInstance->SetData(DATA_BRANN_ACHIEVEMENT, true);
                 if (pInstance->GetData(BOSS_TRIBUNAL_OF_AGES) == DONE)
                     pInstance->SetData(BRANN_BRONZEBEARD, (pInstance->GetData(BOSS_SJONNIR) == DONE) ? 5 : 4);
             }
         }
References BOSS_SJONNIR, BOSS_TRIBUNAL_OF_AGES, BRANN_BRONZEBEARD, DATA_BRANN_ACHIEVEMENT, DONE, FACTION_FRIENDLY, ZoneScript::GetData(), ScriptedAI::me, pInstance, REACT_PASSIVE, npc_escortAI::RemoveEscortState(), ResetEvent(), ZoneScript::SetData(), npc_escortAI::SetDespawnAtEnd(), npc_escortAI::SetDespawnAtFar(), Unit::SetFaction(), Creature::SetReactState(), Object::SetUInt32Value(), UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAG_QUESTGIVER, and UNIT_NPC_FLAGS.
Referenced by DoAction().
ResetEvent()
void brann_bronzebeard::brann_bronzebeardAI::ResetEvent () inline
Definition at line 281 of file brann_bronzebeard.cpp.
         {
             if (GameObject* tribunal = ObjectAccessor::GetGameObject(*me, pInstance->GetGuidData(GO_TRIBUNAL_CONSOLE)))
                 tribunal->SetGoState(GO_STATE_READY);
             events.Reset();
             summons.DespawnAll();
             DespawnHeads();
             WaveNum = 0;
             SpeechCount = 0;
             SpeechPause = 0;
             TalkEvent = false;
         }
References SummonList::DespawnAll(), DespawnHeads(), ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), GO_STATE_READY, GO_TRIBUNAL_CONSOLE, ScriptedAI::me, pInstance, SpeechCount, SpeechPause, summons, TalkEvent, and WaveNum.
Referenced by DoAction(), JustDied(), Reset(), and UpdateEscortAI().
SummonCreatures()
void brann_bronzebeard::brann_bronzebeardAI::SummonCreatures (uint32 entry, uint8 count) inline
Definition at line 583 of file brann_bronzebeard.cpp.
         {
             for (int i = 0; i < count; ++i)
             {
                 Creature* cr = me->SummonCreature(entry, 946.5971f + urand(0, 6), 383.5330f + urand(0, 6), 205.9943f, 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 20000);
                 if(cr)
                 {
                     cr->AI()->AttackStart(me);
                     cr->AddThreat(me, 100.0f);
                     cr->SetInCombatWithZone();
                 }
             }
         }
References Unit::AddThreat(), Creature::AI(), UnitAI::AttackStart(), ScriptedAI::me, Creature::SetInCombatWithZone(), WorldObject::SummonCreature(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, and urand().
Referenced by UpdateEscortAI().
SwitchHeadVisaul()
void brann_bronzebeard::brann_bronzebeardAI::SwitchHeadVisaul (uint8 headMask, bool activate) inline
Definition at line 262 of file brann_bronzebeard.cpp.
         {
             if (!pInstance)
                 return;
             GameObject* go = nullptr;
             if (headMask & 0x1) // Kaddrak
                 if ((go = me->GetMap()->GetGameObject(pInstance->GetGuidData(GO_KADDRAK))))
                     activate ? go->SendCustomAnim(0) : go->SetGoState(GO_STATE_READY);
             if (headMask & 0x2) // Marnak
                 if ((go = me->GetMap()->GetGameObject(pInstance->GetGuidData(GO_MARNAK))))
                     activate ? go->SendCustomAnim(0) : go->SetGoState(GO_STATE_READY);
             if (headMask & 0x4) // Abedneum
                 if ((go = me->GetMap()->GetGameObject(pInstance->GetGuidData(GO_ABEDNEUM))))
                     activate ? go->SendCustomAnim(0) : go->SetGoState(GO_STATE_READY);
         }
References Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), GO_ABEDNEUM, GO_KADDRAK, GO_MARNAK, GO_STATE_READY, ScriptedAI::me, pInstance, GameObject::SendCustomAnim(), and GameObject::SetGoState().
Referenced by DespawnHeads(), and UpdateEscortAI().
UpdateEscortAI()
void brann_bronzebeard::brann_bronzebeardAI::UpdateEscortAI (uint32 diff) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 399 of file brann_bronzebeard.cpp.
         {
             events.Update(diff);
             switch (events.ExecuteEvent())
             {
                 case EVENT_KADDRAK_VISUAL:
                     {
                         SwitchHeadVisaul(0x1, true);
                         break;
                     }
                 case EVENT_MARNAK_VISUAL:
                     {
                         SwitchHeadVisaul(0x2, true);
                         break;
                     }
                 case EVENT_ABEDNEUM_VISUAL:
                     {
                         SwitchHeadVisaul(0x4, true);
                         break;
                     }
                 case EVENT_KADDRAK_HEAD: // First
                     {
                         if (Creature* kaddrak = GetKaddrak())
{
                             if (Player* plr = SelectTargetFromPlayerList(100.0f))
                                 kaddrak->CastSpell(plr, DUNGEON_MODE(SPELL_GLARE_OF_THE_TRIBUNAL, SPELL_GLARE_OF_THE_TRIBUNAL_H), true);
                         }
                         events.RescheduleEvent(EVENT_KADDRAK_SWITCH_EYE, 1500);
                         events.RepeatEvent(2000 + urand(0, 2000));
                         break;
                     }
                 case EVENT_KADDRAK_SWITCH_EYE:
                     {
                         if (Creature* kaddrak = GetKaddrak())
{
                             if (urand(0, 1))
                                 kaddrak->UpdatePosition(927.9f, 330.9f, 219.4f, 2.4f, true);
                             else
                                 kaddrak->UpdatePosition(923.7f, 326.9f, 219.5f, 2.1f, true);
                             kaddrak->StopMovingOnCurrentPos();
                         }
                         break;
                     }
                 case EVENT_MARNAK_HEAD: // Second
                     {
                         if (Creature* marnak = GetMarnak())
{
                             if (Creature* cr = me->SummonCreature(NPC_DARK_MATTER_TRIGGER, marnak->GetPositionX(), marnak->GetPositionY(), marnak->GetPositionZ(), 0, TEMPSUMMON_TIMED_DESPAWN, 7000))
{
                                 cr->CastSpell(cr, SPELL_DARK_MATTER_VISUAL, true);
                                 if (Player* plr = SelectTargetFromPlayerList(100.0f))
{
                                     float speed = me->GetDistance(plr->GetPositionX(), plr->GetPositionY(), plr->GetPositionZ()) / (4000.0f * 0.001f);
                                     cr->MonsterMoveWithSpeed(plr->GetPositionX(), plr->GetPositionY(), plr->GetPositionZ(), speed);
                                 }
                             }
                         }
                         events.RepeatEvent(20000);
                         break;
                     }
                 case EVENT_ABEDNEUM_HEAD: // Third
                     {
                         if (GetAbedneum())
{
                             Player* plr = SelectTargetFromPlayerList(100.0f);
                             if (!plr)
                                 break;
                             if (Creature* cr = me->SummonCreature(NPC_SEARING_GAZE_TRIGGER, plr->GetPositionX(), plr->GetPositionY(), plr->GetPositionZ(), 0, TEMPSUMMON_TIMED_DESPAWN, 10000))
{
                                 // summon another abedneum to create double beam, despawn just after trigger despawn
                                 me->SummonCreature(NPC_ABEDNEUM, 897.0f, 326.9f, 223.5f, 0.0f, TEMPSUMMON_TIMED_DESPAWN, 12000);
                                 cr->CastSpell(cr, DUNGEON_MODE(SPELL_SEARING_GAZE, SPELL_SEARING_GAZE_H), true);
                             }
                         }
                         events.RepeatEvent(30000);
                         break;
                     }
                 case EVENT_SUMMON_MONSTERS:
                     {
                         uint32 Time = 45000 - (2500 * WaveNum);
                         SummonCreatures(NPC_DARK_RUNE_PROTECTOR, 3);
                         if (WaveNum > 2)
                             SummonCreatures(NPC_DARK_RUNE_STORMCALLER, 2);
                         if (WaveNum > 5)
                             SummonCreatures(NPC_IRON_GOLEM_CUSTODIAN, 1);
                         WaveNum++;
                         events.RepeatEvent(Time);
                         break;
                     }
                 case EVENT_TRIBUNAL_END:
                     {
                         // Has to be here!
                         events.Reset();
                         //DespawnHeads();
                         summons.DespawnAll();
                         if (pInstance)
{
                             pInstance->SetData(BOSS_TRIBUNAL_OF_AGES, DONE);
                             pInstance->SetData(BRANN_BRONZEBEARD, 3);
                             me->CastSpell(me, 59046, true); // credit
                         }
                         me->SetUInt32Value(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP | UNIT_NPC_FLAG_QUESTGIVER);
                         // Spawn Chest and quest credit
                         if (Player* plr = SelectTargetFromPlayerList(200.0f))
{
                             if (GameObject* go = plr->SummonGameObject((IsHeroic() ? GO_TRIBUNAL_CHEST_H : GO_TRIBUNAL_CHEST), 880.406f, 345.164f, 203.706f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0))
{
                                 plr->RemoveGameObject(go, false);
                                 go->SetLootMode(1);
                                 go->SetUInt32Value(GAMEOBJECT_FLAGS, 0);
                             }
                             plr->GroupEventHappens(QUEST_HALLS_OF_STONE, me);
                         }
                         events.ScheduleEvent(EVENT_GO_TO_SJONNIR, 279000);
                         break;
                     }
                 case EVENT_GO_TO_SJONNIR:
                     {
                         if (GameObject* door = ObjectAccessor::GetGameObject(*me, pInstance->GetGuidData(GO_SJONNIR_DOOR)))
                             door->SetGoState(GO_STATE_ACTIVE);
                         SetEscortPaused(false);
                         ResetEvent();
                         me->SetUInt32Value(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_NONE);
                         break;
                     }
                 case EVENT_END:
                     {
                         events.Reset();
                         if (pInstance)
                             pInstance->SetData(BRANN_BRONZEBEARD, 6);
                         me->SetUInt32Value(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP | UNIT_NPC_FLAG_QUESTGIVER);
                         me->Yell("I'll use the forge to make batches o' earthen to stand guard... But our greatest challenge still remains: find and stop Loken!", LANG_UNIVERSAL);
                         me->PlayDirectSound(14279);
                         break;
                     }
             }
             if (TalkEvent)
             {
                 SpeechPause += diff;
                 if (SpeechPause >= Conversation[SpeechCount].timer)
                 {
                     Creature* cs = nullptr;
                     switch (Conversation[SpeechCount].creature)
                     {
                         case NPC_BRANN:
                             cs = me;
                             break;
                         case NPC_ABEDNEUM:
                             cs = GetAbedneum();
                             break;
                         case NPC_KADDRAK:
                             cs = GetKaddrak();
                             break;
                         case NPC_MARNAK:
                             cs = GetMarnak();
                             break;
                     }
                     if (cs)
                     {
                         cs->Yell(Conversation[SpeechCount].text, LANG_UNIVERSAL);
                         cs->PlayDirectSound(Conversation[SpeechCount].sound);
                     }
                     if (SpeechCount < 38)
                         SpeechPause = Conversation[SpeechCount++].timer;
                     else
                         TalkEvent = false;
                 }
             }
         }
References BOSS_TRIBUNAL_OF_AGES, BRANN_BRONZEBEARD, Unit::CastSpell(), Conversation, SummonList::DespawnAll(), DONE, ScriptedAI::DUNGEON_MODE(), EVENT_ABEDNEUM_HEAD, EVENT_ABEDNEUM_VISUAL, EVENT_END, EVENT_GO_TO_SJONNIR, EVENT_KADDRAK_HEAD, EVENT_KADDRAK_SWITCH_EYE, EVENT_KADDRAK_VISUAL, EVENT_MARNAK_HEAD, EVENT_MARNAK_VISUAL, EVENT_SUMMON_MONSTERS, EVENT_TRIBUNAL_END, GAMEOBJECT_FLAGS, GetAbedneum(), WorldObject::GetDistance(), ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), GetKaddrak(), GetMarnak(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GO_SJONNIR_DOOR, GO_STATE_ACTIVE, GO_TRIBUNAL_CHEST, GO_TRIBUNAL_CHEST_H, ScriptedAI::IsHeroic(), LANG_UNIVERSAL, ScriptedAI::me, NPC_ABEDNEUM, NPC_BRANN, NPC_DARK_MATTER_TRIGGER, NPC_DARK_RUNE_PROTECTOR, NPC_DARK_RUNE_STORMCALLER, NPC_IRON_GOLEM_CUSTODIAN, NPC_KADDRAK, NPC_MARNAK, NPC_SEARING_GAZE_TRIGGER, pInstance, WorldObject::PlayDirectSound(), QUEST_HALLS_OF_STONE, ResetEvent(), ScriptedAI::SelectTargetFromPlayerList(), ZoneScript::SetData(), npc_escortAI::SetEscortPaused(), Object::SetUInt32Value(), SpeechCount, SpeechPause, SPELL_DARK_MATTER_VISUAL, SPELL_GLARE_OF_THE_TRIBUNAL, SPELL_GLARE_OF_THE_TRIBUNAL_H, SPELL_SEARING_GAZE, SPELL_SEARING_GAZE_H, WorldObject::SummonCreature(), SummonCreatures(), WorldObject::SummonGameObject(), summons, SwitchHeadVisaul(), TalkEvent, TEMPSUMMON_TIMED_DESPAWN, Yells::timer, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAG_NONE, UNIT_NPC_FLAG_QUESTGIVER, UNIT_NPC_FLAGS, urand(), WaveNum, and Unit::Yell().
WaypointReached()
void brann_bronzebeard::brann_bronzebeardAI::WaypointReached (uint32 id) override virtual
Implements npc_escortAI.
Definition at line 649 of file brann_bronzebeard.cpp.
 {
     switch (id)
     {
         // Stop before stairs and ask to start
         case 9:
             SetEscortPaused(true);
             me->SetUInt32Value(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP | UNIT_NPC_FLAG_QUESTGIVER);
             if (pInstance)
                 pInstance->SetData(BRANN_BRONZEBEARD, 2);
             break;
         // In front of Console
         case 11:
             SetEscortPaused(true);
             if(pInstance)
             {
                 pInstance->SetData(BOSS_TRIBUNAL_OF_AGES, IN_PROGRESS);
                 if (GameObject* tribunal = ObjectAccessor::GetGameObject(*me, pInstance->GetGuidData(GO_TRIBUNAL_CONSOLE)))
                     tribunal->SetGoState(GO_STATE_ACTIVE);
             }
             break;
         // Before Sjonnir's door
         case 27:
             SetEscortPaused(true);
             if(pInstance)
             {
                 pInstance->SetData(BRANN_BRONZEBEARD, 5);
                 me->SetUInt32Value(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP | UNIT_NPC_FLAG_QUESTGIVER);
                 if (Creature* cr = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_SJONNIR)))
                     cr->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                 me->SetOrientation(3.132660f);
                 DoCast(me, 58506, false);
             }
             break;
         case 28:
             SetEscortPaused(true);
             break;
         case 29:
             SetEscortPaused(true);
             me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_USE_STANDING);
             if (pInstance)
                 if (GameObject* console = ObjectAccessor::GetGameObject(*me, pInstance->GetGuidData(GO_SJONNIR_CONSOLE)))
                     console->SetGoState(GO_STATE_ACTIVE);
             break;
     }
 }
References BOSS_TRIBUNAL_OF_AGES, BRANN_BRONZEBEARD, EMOTE_STATE_USE_STANDING, ObjectAccessor::GetCreature(), ObjectAccessor::GetGameObject(), GO_SJONNIR_CONSOLE, GO_STATE_ACTIVE, GO_TRIBUNAL_CONSOLE, IN_PROGRESS, NPC_SJONNIR, UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE, UNIT_NPC_EMOTESTATE, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAG_QUESTGIVER, and UNIT_NPC_FLAGS.
Member Data Documentation
AbedneumGUID
ObjectGuid brann_bronzebeard::brann_bronzebeardAI::AbedneumGUID
Definition at line 245 of file brann_bronzebeard.cpp.
Referenced by GetAbedneum(), and InitializeEvent().
events
EventMap brann_bronzebeard::brann_bronzebeardAI::events
Definition at line 243 of file brann_bronzebeard.cpp.
KaddrakGUID
ObjectGuid brann_bronzebeard::brann_bronzebeardAI::KaddrakGUID
Definition at line 247 of file brann_bronzebeard.cpp.
Referenced by GetKaddrak(), and InitializeEvent().
MarnakGUID
ObjectGuid brann_bronzebeard::brann_bronzebeardAI::MarnakGUID
Definition at line 246 of file brann_bronzebeard.cpp.
Referenced by GetMarnak(), and InitializeEvent().
pInstance
InstanceScript* brann_bronzebeard::brann_bronzebeardAI::pInstance
Definition at line 242 of file brann_bronzebeard.cpp.
Referenced by brann_bronzebeardAI(), DamageTaken(), DoAction(), JustDied(), Reset(), ResetEvent(), SwitchHeadVisaul(), and UpdateEscortAI().
SpeechCount
uint32 brann_bronzebeard::brann_bronzebeardAI::SpeechCount
Definition at line 251 of file brann_bronzebeard.cpp.
Referenced by ResetEvent(), and UpdateEscortAI().
SpeechPause
uint32 brann_bronzebeard::brann_bronzebeardAI::SpeechPause
Definition at line 251 of file brann_bronzebeard.cpp.
Referenced by ResetEvent(), and UpdateEscortAI().
summons
SummonList brann_bronzebeard::brann_bronzebeardAI::summons
Definition at line 244 of file brann_bronzebeard.cpp.
Referenced by JustSummoned(), ResetEvent(), and UpdateEscortAI().
TalkEvent
bool brann_bronzebeard::brann_bronzebeardAI::TalkEvent
Definition at line 250 of file brann_bronzebeard.cpp.
Referenced by InitializeEvent(), ResetEvent(), and UpdateEscortAI().
WaveNum
uint8 brann_bronzebeard::brann_bronzebeardAI::WaveNum
Definition at line 248 of file brann_bronzebeard.cpp.
Referenced by ResetEvent(), and UpdateEscortAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/HallsOfStone/brann_bronzebeard.cpp