Azerotcore-wotlk: PreparedResultSet Class Reference
PreparedResultSet Class Reference
#include <QueryResult.h>
Public Member Functions
PreparedResultSet (MySQLStmt *stmt, MySQLResult *result, uint64 rowCount, uint32 fieldCount)
~PreparedResultSet ()
bool NextRow ()
uint64 GetRowCount () const
uint32 GetFieldCount () const
Field * Fetch () const
Field const & operator[] (std::size_t index) const
Protected Attributes
std::vector< QueryResultFieldMetadata > m_fieldMetadata
std::vector< Field > m_rows
uint64 m_rowCount
uint64 m_rowPosition
uint32 m_fieldCount
Private Member Functions
void CleanUp ()
bool _NextRow ()
PreparedResultSet (PreparedResultSet const &right)=delete
PreparedResultSet & operator= (PreparedResultSet const &right)=delete
Private Attributes
MySQLBind * m_rBind
MySQLStmt * m_stmt
MySQLResult * m_metadataResult
Field metadata, returned by mysql_stmt_result_metadata.
Detailed Description
Definition at line 54 of file QueryResult.h.
Constructor & Destructor Documentation
PreparedResultSet() [1/2]
PreparedResultSet::PreparedResultSet (MySQLStmt * stmt, MySQLResult * result, uint64 rowCount, uint32 fieldCount)
All data is buffered, let go of mysql c api structures
Definition at line 182 of file QueryResult.cpp.
                                                                                                              :
 m_rowCount(rowCount),
 m_rowPosition(0),
 m_fieldCount(fieldCount),
 m_rBind(nullptr),
 m_stmt(stmt),
 m_metadataResult(result)
 {
     if (!m_metadataResult)
         return;
     if (m_stmt->bind_result_done)
     {
         delete[] m_stmt->bind->length;
         delete[] m_stmt->bind->is_null;
     }
     m_rBind = new MySQLBind[m_fieldCount];
     //- for future readers wondering where the fuck this is freed - mysql_stmt_bind_result moves pointers to these
     // from m_rBind to m_stmt->bind and it is later freed by the `if (m_stmt->bind_result_done)` block just above here
     // MYSQL_STMT lifetime is equal to connection lifetime
     MySQLBool* m_isNull = new MySQLBool[m_fieldCount];
     unsigned long* m_length = new unsigned long[m_fieldCount];
     memset(m_isNull, 0, sizeof(MySQLBool) * m_fieldCount);
     memset(m_rBind, 0, sizeof(MySQLBind) * m_fieldCount);
     memset(m_length, 0, sizeof(unsigned long) * m_fieldCount);
     //- This is where we store the (entire) resultset
     if (mysql_stmt_store_result(m_stmt))
     {
         LOG_WARN("sql.sql", "%s:mysql_stmt_store_result, cannot bind result from MySQL server. Error: %s", __FUNCTION__, mysql_stmt_error(m_stmt));
         delete[] m_rBind;
         delete[] m_isNull;
         delete[] m_length;
         return;
     }
     m_rowCount = mysql_stmt_num_rows(m_stmt);
     //- This is where we prepare the buffer based on metadata
     MySQLField* field = reinterpret_cast<MySQLField*>(mysql_fetch_fields(m_metadataResult));
     m_fieldMetadata.resize(m_fieldCount);
     std::size_t rowSize = 0;
     for (uint32 i = 0; i < m_fieldCount; ++i)
     {
         uint32 size = SizeForType(&field[i]);
         rowSize += size;
         InitializeDatabaseFieldMetadata(&m_fieldMetadata[i], &field[i], i);
         m_rBind[i].buffer_type = field[i].type;
         m_rBind[i].buffer_length = size;
         m_rBind[i].length = &m_length[i];
         m_rBind[i].is_null = &m_isNull[i];
         m_rBind[i].error = nullptr;
         m_rBind[i].is_unsigned = field[i].flags & UNSIGNED_FLAG;
     }
     char* dataBuffer = new char[rowSize * m_rowCount];
     for (uint32 i = 0, offset = 0; i < m_fieldCount; ++i)
     {
         m_rBind[i].buffer = dataBuffer + offset;
         offset += m_rBind[i].buffer_length;
     }
     //- This is where we bind the bind the buffer to the statement
     if (mysql_stmt_bind_result(m_stmt, m_rBind))
     {
         LOG_WARN("sql.sql", "%s:mysql_stmt_bind_result, cannot bind result from MySQL server. Error: %s", __FUNCTION__, mysql_stmt_error(m_stmt));
         mysql_stmt_free_result(m_stmt);
         CleanUp();
         delete[] m_isNull;
         delete[] m_length;
         return;
     }
     m_rows.resize(uint32(m_rowCount) * m_fieldCount);
     while (_NextRow())
     {
         for (uint32 fIndex = 0; fIndex < m_fieldCount; ++fIndex)
         {
             m_rows[uint32(m_rowPosition) * m_fieldCount + fIndex].SetMetadata(&m_fieldMetadata[fIndex]);
             unsigned long buffer_length = m_rBind[fIndex].buffer_length;
             unsigned long fetched_length = *m_rBind[fIndex].length;
             if (!*m_rBind[fIndex].is_null)
             {
                 void* buffer = m_stmt->bind[fIndex].buffer;
                 switch (m_rBind[fIndex].buffer_type)
                 {
                     case MYSQL_TYPE_TINY_BLOB:
                     case MYSQL_TYPE_MEDIUM_BLOB:
                     case MYSQL_TYPE_LONG_BLOB:
                     case MYSQL_TYPE_BLOB:
                     case MYSQL_TYPE_STRING:
                     case MYSQL_TYPE_VAR_STRING:
                         // warning - the string will not be null-terminated if there is no space for it in the buffer
                         // when mysql_stmt_fetch returned MYSQL_DATA_TRUNCATED
                         // we cannot blindly null-terminate the data either as it may be retrieved as binary blob and not specifically a string
                         // in this case using Field::GetCString will result in garbage
                         // TODO: remove Field::GetCString and use std::string_view in C++17
                         if (fetched_length < buffer_length)
                             *((char*)buffer + fetched_length) = '\0';
                         break;
                     default:
                         break;
                 }
                 m_rows[uint32(m_rowPosition) * m_fieldCount + fIndex].SetByteValue(
                     (char const*)buffer,
                     fetched_length);
                 // move buffer pointer to next part
                 m_stmt->bind[fIndex].buffer = (char*)buffer + rowSize;
             }
             else
             {
                 m_rows[uint32(m_rowPosition) * m_fieldCount + fIndex].SetByteValue(
                     nullptr,
                     *m_rBind[fIndex].length);
             }
         }
         m_rowPosition++;
     }
     m_rowPosition = 0;
     mysql_stmt_free_result(m_stmt);
 }
References _NextRow(), st_mysql_stmt::bind, st_mysql_stmt::bind_result_done, st_mysql_bind::buffer, st_mysql_bind::buffer_length, st_mysql_bind::buffer_type, CleanUp(), st_mysql_bind::error, st_mysql_field::flags, anonymous_namespace{QueryResult.cpp}::InitializeDatabaseFieldMetadata(), st_mysql_bind::is_null, st_mysql_bind::is_unsigned, G3D::length(), st_mysql_bind::length, LOG_WARN, m_fieldCount, m_fieldMetadata, m_metadataResult, m_rBind, m_rowCount, m_rowPosition, m_rows, m_stmt, memset, mysql_fetch_fields(), mysql_stmt_bind_result(), mysql_stmt_error(), mysql_stmt_free_result(), mysql_stmt_num_rows(), mysql_stmt_store_result(), MYSQL_TYPE_BLOB, MYSQL_TYPE_LONG_BLOB, MYSQL_TYPE_MEDIUM_BLOB, MYSQL_TYPE_STRING, MYSQL_TYPE_TINY_BLOB, MYSQL_TYPE_VAR_STRING, anonymous_namespace{QueryResult.cpp}::SizeForType(), st_mysql_field::type, and UNSIGNED_FLAG.
~PreparedResultSet()
PreparedResultSet::~PreparedResultSet ()
Definition at line 319 of file QueryResult.cpp.
 {
     CleanUp();
 }
References CleanUp().
PreparedResultSet() [2/2]
PreparedResultSet::PreparedResultSet (PreparedResultSet const & right) private delete
Member Function Documentation
_NextRow()
bool PreparedResultSet::_NextRow () private
Only called in low-level code, namely the constructor Will iterate over every row of data and buffer it
Definition at line 368 of file QueryResult.cpp.
 {
     if (m_rowPosition >= m_rowCount)
         return false;
     int retval = mysql_stmt_fetch(m_stmt);
     return retval == 0 || retval == MYSQL_DATA_TRUNCATED;
 }
References m_rowCount, m_rowPosition, m_stmt, MYSQL_DATA_TRUNCATED, and mysql_stmt_fetch().
Referenced by PreparedResultSet().
CleanUp()
void PreparedResultSet::CleanUp () private
Definition at line 413 of file QueryResult.cpp.
 {
     if (m_metadataResult)
         mysql_free_result(m_metadataResult);
     if (m_rBind)
     {
         delete[](char*)m_rBind->buffer;
         delete[] m_rBind;
         m_rBind = nullptr;
     }
 }
References st_mysql_bind::buffer, m_metadataResult, m_rBind, and mysql_free_result().
Referenced by PreparedResultSet(), and ~PreparedResultSet().
Fetch()
Field * PreparedResultSet::Fetch () const
Definition at line 400 of file QueryResult.cpp.
 {
     ASSERT(m_rowPosition < m_rowCount);
     return const_cast<Field*>(&m_rows[uint32(m_rowPosition) * m_fieldCount]);
 }
References ASSERT, m_fieldCount, m_rowCount, m_rowPosition, and m_rows.
GetFieldCount()
uint32 PreparedResultSet::GetFieldCount () const inline
Definition at line 62 of file QueryResult.h.
 { return m_fieldCount; }
GetRowCount()
uint64 PreparedResultSet::GetRowCount () const inline
Definition at line 61 of file QueryResult.h.
 { return m_rowCount; }
NextRow()
bool PreparedResultSet::NextRow ()
Only updates the m_rowPosition so upper level code knows in which element of the rows vector to look
Definition at line 358 of file QueryResult.cpp.
 {
     if (++m_rowPosition >= m_rowCount)
         return false;
     return true;
 }
References m_rowCount, and m_rowPosition.
operator=()
PreparedResultSet& PreparedResultSet::operator= (PreparedResultSet const & right) private delete
operator[]()
Field const & PreparedResultSet::operator[] (std::size_t index) const
Definition at line 406 of file QueryResult.cpp.
 {
     ASSERT(m_rowPosition < m_rowCount);
     ASSERT(index < m_fieldCount);
     return m_rows[uint32(m_rowPosition) * m_fieldCount + index];
 }
References ASSERT, index, m_fieldCount, m_rowCount, m_rowPosition, and m_rows.
Member Data Documentation
m_fieldCount
uint32 PreparedResultSet::m_fieldCount protected
Definition at line 72 of file QueryResult.h.
Referenced by Fetch(), operator[](), and PreparedResultSet().
m_fieldMetadata
std::vector<QueryResultFieldMetadata> PreparedResultSet::m_fieldMetadata protected
Definition at line 68 of file QueryResult.h.
Referenced by PreparedResultSet().
m_metadataResult
MySQLResult* PreparedResultSet::m_metadataResult private
Field metadata, returned by mysql_stmt_result_metadata.
Definition at line 77 of file QueryResult.h.
Referenced by CleanUp(), and PreparedResultSet().
m_rBind
MySQLBind* PreparedResultSet::m_rBind private
Definition at line 75 of file QueryResult.h.
Referenced by CleanUp(), and PreparedResultSet().
m_rowCount
uint64 PreparedResultSet::m_rowCount protected
Definition at line 70 of file QueryResult.h.
Referenced by _NextRow(), Fetch(), NextRow(), operator[](), and PreparedResultSet().
m_rowPosition
uint64 PreparedResultSet::m_rowPosition protected
Definition at line 71 of file QueryResult.h.
Referenced by _NextRow(), Fetch(), NextRow(), operator[](), and PreparedResultSet().
m_rows
std::vector<Field> PreparedResultSet::m_rows protected
Definition at line 69 of file QueryResult.h.
Referenced by Fetch(), operator[](), and PreparedResultSet().
m_stmt
MySQLStmt* PreparedResultSet::m_stmt private
Definition at line 76 of file QueryResult.h.
Referenced by _NextRow(), and PreparedResultSet().
The documentation for this class was generated from the following files:
src/server/database/Database/QueryResult.h
src/server/database/Database/QueryResult.cpp