Azerotcore-wotlk: G3D::Cylinder Class Reference
G3D::Cylinder Class Reference
#include <Cylinder.h>
Public Member Functions
Cylinder ()
Cylinder (class BinaryInput &b)
Cylinder (const Vector3 &_p1, const Vector3 &_p2, float _r)
void serialize (class BinaryOutput &b) const
void deserialize (class BinaryInput &b)
Line axis () const
void getReferenceFrame (class CoordinateFrame &cframe) const
const Vector3 & point (int i) const
bool contains (const Vector3 &p) const
float area () const
float volume () const
float radius () const
Vector3 center () const
float height () const
void getBounds (AABox &out) const
void getRandomSurfacePoint (Vector3 &P, Vector3 &N) const
Vector3 randomInteriorPoint () const
Private Attributes
Vector3 p1
Vector3 p2
float mRadius
Detailed Description
Right cylinder
Definition at line 27 of file Cylinder.h.
Constructor & Destructor Documentation
Cylinder() [1/3]
G3D::Cylinder::Cylinder ()
Uninitialized
Definition at line 29 of file Cylinder.cpp.
                    {
 }
Cylinder() [2/3]
G3D::Cylinder::Cylinder (class BinaryInput & b)
Definition at line 24 of file Cylinder.cpp.
{
     deserialize(b);
 }
References b, and deserialize().
Cylinder() [3/3]
G3D::Cylinder::Cylinder (const Vector3 & _p1, const Vector3 & _p2, float _r)
Definition at line 33 of file Cylinder.cpp.
     : p1(_p1), p2(_p2), mRadius(_r) {
 }
Member Function Documentation
area()
float G3D::Cylinder::area () const
Definition at line 69 of file Cylinder.cpp.
{
     return
         // Sides
         ((float)twoPi() * mRadius) * height() +
          // Caps
          (float)twoPi() * square(mRadius);
 }
References height(), mRadius, G3D::square(), and G3D::twoPi().
axis()
Line G3D::Cylinder::axis () const
The line down the center of the Cylinder
Definition at line 52 of file Cylinder.cpp.
{
     return Line::fromTwoPoints(p1, p2);
 }
References G3D::Line::fromTwoPoints(), p1, and p2.
center()
Vector3 G3D::Cylinder::center () const inline
Center of mass
Definition at line 70 of file Cylinder.h.
{
         return (p1 + p2) / 2.0f;
     }
References p1, and p2.
Referenced by getReferenceFrame().
contains()
bool G3D::Cylinder::contains (const Vector3 & p) const
Returns true if the point is inside the Cylinder or on its surface.
Definition at line 84 of file Cylinder.cpp.
{
     return LineSegment::fromTwoPoints(p1, p2).distanceSquared(p) <= square(mRadius);
 }
References G3D::LineSegment::distanceSquared(), G3D::LineSegment::fromTwoPoints(), mRadius, p1, p2, and G3D::square().
deserialize()
void G3D::Cylinder::deserialize (class BinaryInput & b)
Definition at line 45 of file Cylinder.cpp.
{
     p1.deserialize(b);
     p2.deserialize(b);
     mRadius = (float)b.readFloat64();
 }
References b, G3D::Vector3::deserialize(), mRadius, p1, and p2.
Referenced by Cylinder().
getBounds()
void G3D::Cylinder::getBounds (AABox & out) const
Get close axis aligned bounding box. With vertical world orientation, the top and bottom might not be very tight.
Definition at line 78 of file Cylinder.cpp.
{
     Vector3 min = p1.min(p2) - (Vector3(1, 1, 1) * mRadius);
     Vector3 max = p1.max(p2) + (Vector3(1, 1, 1) * mRadius);
     out = AABox(min, max);
 }
References G3D::max(), G3D::Vector3::max(), G3D::min(), G3D::Vector3::min(), mRadius, p1, and p2.
getRandomSurfacePoint()
void G3D::Cylinder::getRandomSurfacePoint (Vector3 & P, Vector3 & N) const
Random world space point with outward facing normal.
Definition at line 102 of file Cylinder.cpp.
{
     float h = height();
     float r = radius();
     // Create a random point on a standard cylinder and then rotate to the global frame.
     // Relative areas (factor of 2PI already taken out)
     float capRelArea  = square(r) / 2.0f;
     float sideRelArea = r * h;
     float r1 = uniformRandom(0, capRelArea * 2 + sideRelArea);
     if (r1 < capRelArea * 2) {
         // Select a point uniformly at random on a disk
         // @cite http://mathworld.wolfram.com/DiskPointPicking.html
         float a = uniformRandom(0, (float)twoPi());
         float r2 = sqrt(uniformRandom(0, 1)) * r;
         p.x = cos(a) * r2;
         p.z = sin(a) * r2;
         N.x = 0;
         N.z = 0;
         if (r1 < capRelArea) {
             // Top
             p.y = h / 2.0f;
             N.y = 1;
         } else {
             // Bottom
             p.y = -h / 2.0f;
             N.y = -1;
         }
     } else {
         // Side
         float a = uniformRandom(0, (float)twoPi());
         N.x = cos(a);
         N.y = 0;
         N.z = sin(a);
         p.x = N.x * r;
         p.z = N.y * r;
         p.y = uniformRandom(-h / 2.0f, h / 2.0f);
     }
     // Transform to world space
     CoordinateFrame cframe;
     getReferenceFrame(cframe);
     p = cframe.pointToWorldSpace(p);
     N = cframe.normalToWorldSpace(N);
 }
References mpq::a, getReferenceFrame(), height(), G3D::CoordinateFrame::normalToWorldSpace(), G3D::CoordinateFrame::pointToWorldSpace(), radius(), G3D::square(), G3D::twoPi(), G3D::uniformRandom(), G3D::Vector3::x, G3D::Vector3::y, and G3D::Vector3::z.
getReferenceFrame()
void G3D::Cylinder::getReferenceFrame (class CoordinateFrame & cframe) const
A reference frame in which the center of mass is at the origin and the Y-axis is the cylinder's axis. If the cylinder is transformed, this reference frame may freely rotate around its axis.
Definition at line 89 of file Cylinder.cpp.
{
     cframe.translation = center();
     Vector3 Y = (p1 - p2).direction();
     Vector3 X = (abs(Y.dot(Vector3::unitX())) > 0.9) ? Vector3::unitY() : Vector3::unitX();
     Vector3 Z = X.cross(Y).direction();
     X = Y.cross(Z);
     cframe.rotation.setColumn(0, X);
     cframe.rotation.setColumn(1, Y);
     cframe.rotation.setColumn(2, Z);
 }
References G3D::abs(), center(), p1, p2, G3D::CoordinateFrame::rotation, G3D::Matrix3::setColumn(), G3D::CoordinateFrame::translation, G3D::Vector3::unitX(), G3D::Vector3::unitY(), X, Y, and Z.
Referenced by getRandomSurfacePoint(), and randomInteriorPoint().
height()
float G3D::Cylinder::height () const inline
Definition at line 74 of file Cylinder.h.
{
         return (p1 - p2).magnitude();
     }
References p1, and p2.
Referenced by area(), getRandomSurfacePoint(), and randomInteriorPoint().
point()
const Vector3& G3D::Cylinder::point (int i) const inline
Returns point 0 or 1
Definition at line 53 of file Cylinder.h.
{
         debugAssert(i >= 0 && i <= 1);
         return (i == 0) ? p1 : p2;
     }
References debugAssert, p1, and p2.
radius()
float G3D::Cylinder::radius () const
Definition at line 58 of file Cylinder.cpp.
{
     return mRadius;
 }
References mRadius.
Referenced by getRandomSurfacePoint(), and randomInteriorPoint().
randomInteriorPoint()
Vector3 G3D::Cylinder::randomInteriorPoint () const
Point selected uniformly at random over the volume.
Definition at line 154 of file Cylinder.cpp.
{
     float h = height();
     float r = radius();
     // Create a random point in a standard cylinder and then rotate to the global frame.
     // Select a point uniformly at random on a disk
     // @cite http://mathworld.wolfram.com/DiskPointPicking.html
     float a = uniformRandom(0, (float)twoPi());
     float r2 = sqrt(uniformRandom(0, 1)) * r;
     Vector3 p(  cos(a) * r2,
                 uniformRandom(-h / 2.0f, h / 2.0f),
                 sin(a) * r2);
     // Transform to world space
     CoordinateFrame cframe;
     getReferenceFrame(cframe);
     return cframe.pointToWorldSpace(p);
 }
References mpq::a, getReferenceFrame(), height(), G3D::CoordinateFrame::pointToWorldSpace(), radius(), G3D::twoPi(), and G3D::uniformRandom().
serialize()
void G3D::Cylinder::serialize (class BinaryOutput & b) const
Definition at line 38 of file Cylinder.cpp.
{
     p1.serialize(b);
     p2.serialize(b);
     b.writeFloat64(mRadius);
 }
References b, mRadius, p1, p2, and G3D::Vector3::serialize().
volume()
float G3D::Cylinder::volume () const
Definition at line 63 of file Cylinder.cpp.
{
     return
         (float)pi() * square(mRadius) * (p1 - p2).magnitude();
 }
References mRadius, p1, p2, G3D::pi(), and G3D::square().
Member Data Documentation
mRadius
float G3D::Cylinder::mRadius private
Definition at line 32 of file Cylinder.h.
Referenced by area(), contains(), deserialize(), getBounds(), radius(), serialize(), and volume().
p1
Vector3 G3D::Cylinder::p1 private
Definition at line 29 of file Cylinder.h.
Referenced by axis(), center(), contains(), deserialize(), getBounds(), getReferenceFrame(), height(), point(), serialize(), and volume().
p2
Vector3 G3D::Cylinder::p2 private
Definition at line 30 of file Cylinder.h.
Referenced by axis(), center(), contains(), deserialize(), getBounds(), getReferenceFrame(), height(), point(), serialize(), and volume().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/Cylinder.h
deps/g3dlite/source/Cylinder.cpp