Azerotcore-wotlk: npc_hidden_cultist::npc_hidden_cultistAI Struct Reference
npc_hidden_cultist::npc_hidden_cultistAI Struct Reference
Public Member Functions
npc_hidden_cultistAI (Creature *creature)
void Initialize ()
void Reset () override
void PreScript ()
void AttackPlayer ()
void UpdateAI (uint32 diff) override
void sGossipSelect (Player *player, uint32, uint32 gossipListId) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
EventMap _events
uint32 _emoteState
uint32 _npcFlags
ObjectGuid _playerGUID
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1179 of file zone_borean_tundra.cpp.
Constructor & Destructor Documentation
npc_hidden_cultistAI()
npc_hidden_cultist::npc_hidden_cultistAI::npc_hidden_cultistAI (Creature * creature) inline
Definition at line 1181 of file zone_borean_tundra.cpp.
                                                  : ScriptedAI(creature)
         {
             Initialize();
             _emoteState = creature->GetUInt32Value(UNIT_NPC_EMOTESTATE);
             _npcFlags   = creature->GetUInt32Value(UNIT_NPC_FLAGS);
         }
References _emoteState, _npcFlags, Object::GetUInt32Value(), Initialize(), UNIT_NPC_EMOTESTATE, and UNIT_NPC_FLAGS.
Member Function Documentation
AttackPlayer()
void npc_hidden_cultist::npc_hidden_cultistAI::AttackPlayer () inline
Definition at line 1222 of file zone_borean_tundra.cpp.
         {
             me->SetFaction(FACTION_MONSTER);
             if (Player* player = ObjectAccessor::GetPlayer(*me, _playerGUID))
             {
                 AttackStart(player);
             }
         }
References _playerGUID, ScriptedAI::AttackStart(), FACTION_MONSTER, ObjectAccessor::GetPlayer(), ScriptedAI::me, and Unit::SetFaction().
Referenced by UpdateAI().
Initialize()
void npc_hidden_cultist::npc_hidden_cultistAI::Initialize (void) inline
Definition at line 1188 of file zone_borean_tundra.cpp.
         {
             _playerGUID.Clear();
         }
References _playerGUID, and ObjectGuid::Clear().
Referenced by npc_hidden_cultistAI(), and Reset().
PreScript()
void npc_hidden_cultist::npc_hidden_cultistAI::PreScript () inline
Definition at line 1210 of file zone_borean_tundra.cpp.
         {
             me->StopMoving();
             me->SetUInt32Value(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_NONE);
             me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
             if (Player* player = ObjectAccessor::GetPlayer(*me, _playerGUID))
             {
                 me->SetFacingToObject(player);
             }
             _events.ScheduleEvent(EVENT_CULTIST_SCRIPT_1, 3000);
         }
References _events, _playerGUID, EMOTE_ONESHOT_NONE, EVENT_CULTIST_SCRIPT_1, ObjectAccessor::GetPlayer(), ScriptedAI::me, EventMap::ScheduleEvent(), Unit::SetFacingToObject(), Object::SetUInt32Value(), Unit::StopMoving(), UNIT_NPC_EMOTESTATE, UNIT_NPC_FLAG_NONE, and UNIT_NPC_FLAGS.
Referenced by sGossipSelect().
Reset()
void npc_hidden_cultist::npc_hidden_cultistAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1193 of file zone_borean_tundra.cpp.
         {
             if (_emoteState)
             {
                 me->SetUInt32Value(UNIT_NPC_EMOTESTATE, _emoteState);
             }
             if (_npcFlags)
             {
                 me->SetUInt32Value(UNIT_NPC_FLAGS, _npcFlags);
             }
             Initialize();
             DoCast(SPELL_SHROUD_OF_THE_DEATH_CULTIST);
             me->RestoreFaction();
         }
References _emoteState, _npcFlags, UnitAI::DoCast(), Initialize(), ScriptedAI::me, Unit::RestoreFaction(), Object::SetUInt32Value(), SPELL_SHROUD_OF_THE_DEATH_CULTIST, UNIT_NPC_EMOTESTATE, and UNIT_NPC_FLAGS.
sGossipSelect()
void npc_hidden_cultist::npc_hidden_cultistAI::sGossipSelect (Player * player, uint32 , uint32 gossipListId) inline override virtual
Reimplemented from UnitAI.
Definition at line 1301 of file zone_borean_tundra.cpp.
         {
             if (gossipListId == 0)
             {
                 CloseGossipMenuFor(player);
                 _playerGUID = player->GetGUID();
                 PreScript();
             }
         }
References _playerGUID, CloseGossipMenuFor(), Object::GetGUID(), and PreScript().
UpdateAI()
void npc_hidden_cultist::npc_hidden_cultistAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1231 of file zone_borean_tundra.cpp.
         {
             _events.Update(diff);
             while (uint32 eventId = _events.ExecuteEvent())
             {
                 switch (eventId)
                 {
                     case EVENT_CULTIST_SCRIPT_1:
                     {
                         switch (me->GetEntry())
{
                             case NPC_SALTY_JOHN_THORPE:
                                 Talk(SAY_HIDDEN_CULTIST_1);
                                 _events.ScheduleEvent(EVENT_CULTIST_SCRIPT_2, 5000);
                                 break;
                             case NPC_GUARD_MITCHELLS:
                                 Talk(SAY_HIDDEN_CULTIST_2);
                                 _events.ScheduleEvent(EVENT_CULTIST_SCRIPT_2, 5000);
                                 break;
                             case NPC_TOM_HEGGER:
                                 if (Player* player = ObjectAccessor::GetPlayer(*me, _playerGUID))
{
                                     Talk(SAY_HIDDEN_CULTIST_3, player);
                                 }
                                 _events.ScheduleEvent(EVENT_CULTIST_SCRIPT_2, 5000);
                                 break;
                         }
                         break;
                     }
                     case EVENT_CULTIST_SCRIPT_2:
                     {
                         switch (me->GetEntry())
{
                             case NPC_SALTY_JOHN_THORPE:
                                 Talk(SAY_HIDDEN_CULTIST_4);
                                 if (Player* player = ObjectAccessor::GetPlayer(*me, _playerGUID))
{
                                     me->SetFacingToObject(player);
                                 }
                                 _events.ScheduleEvent(EVENT_CULTIST_SCRIPT_3, 3000);
                                 break;
                             case NPC_GUARD_MITCHELLS:
                             case NPC_TOM_HEGGER:
                                 AttackPlayer();
                                 break;
                         }
                         break;
                     }
                     case EVENT_CULTIST_SCRIPT_3:
                     {
                         if (me->GetEntry() == NPC_SALTY_JOHN_THORPE)
{
                             AttackPlayer();
                         }
                         break;
                     }
                     default:
                         break;
                 }
             }
             if (!UpdateVictim())
             {
                 return;
             }
             DoMeleeAttackIfReady();
         }
References _events, _playerGUID, AttackPlayer(), UnitAI::DoMeleeAttackIfReady(), EVENT_CULTIST_SCRIPT_1, EVENT_CULTIST_SCRIPT_2, EVENT_CULTIST_SCRIPT_3, EventMap::ExecuteEvent(), Object::GetEntry(), ObjectAccessor::GetPlayer(), ScriptedAI::me, NPC_GUARD_MITCHELLS, NPC_SALTY_JOHN_THORPE, NPC_TOM_HEGGER, SAY_HIDDEN_CULTIST_1, SAY_HIDDEN_CULTIST_2, SAY_HIDDEN_CULTIST_3, SAY_HIDDEN_CULTIST_4, EventMap::ScheduleEvent(), Unit::SetFacingToObject(), CreatureAI::Talk(), EventMap::Update(), and CreatureAI::UpdateVictim().
Member Data Documentation
_emoteState
uint32 npc_hidden_cultist::npc_hidden_cultistAI::_emoteState private
Definition at line 1312 of file zone_borean_tundra.cpp.
Referenced by npc_hidden_cultistAI(), and Reset().
_events
EventMap npc_hidden_cultist::npc_hidden_cultistAI::_events private
Definition at line 1311 of file zone_borean_tundra.cpp.
Referenced by PreScript(), and UpdateAI().
_npcFlags
uint32 npc_hidden_cultist::npc_hidden_cultistAI::_npcFlags private
Definition at line 1313 of file zone_borean_tundra.cpp.
Referenced by npc_hidden_cultistAI(), and Reset().
_playerGUID
ObjectGuid npc_hidden_cultist::npc_hidden_cultistAI::_playerGUID private
Definition at line 1314 of file zone_borean_tundra.cpp.
Referenced by AttackPlayer(), Initialize(), PreScript(), sGossipSelect(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/zone_borean_tundra.cpp