Azerotcore-wotlk: npc_battle_at_valhalas::npc_battle_at_valhalasAI Struct Reference
npc_battle_at_valhalas::npc_battle_at_valhalasAI Struct Reference
Public Member Functions
npc_battle_at_valhalasAI (Creature *creature)
void Reset () override
void ResetData ()
void JustSummoned (Creature *creature) override
void PrepareSummons ()
void StartBattle (ObjectGuid guid, uint32 questId)
void CheckSummons ()
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
SummonList summons
ObjectGuid playerGUID
ObjectGuid playerGUID2
uint32 currentQuest
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 115 of file zone_icecrown.cpp.
Constructor & Destructor Documentation
npc_battle_at_valhalasAI()
npc_battle_at_valhalas::npc_battle_at_valhalasAI::npc_battle_at_valhalasAI (Creature * creature) inline
Definition at line 117 of file zone_icecrown.cpp.
                                                      : ScriptedAI(creature), summons(me)
         {
         }
Member Function Documentation
CheckSummons()
void npc_battle_at_valhalas::npc_battle_at_valhalasAI::CheckSummons () inline
Definition at line 187 of file zone_icecrown.cpp.
         {
             bool allow = true;
             for (ObjectGuid const& guid : summons)
                 if (Creature* cr = ObjectAccessor::GetCreature(*me, guid))
                     if (cr->IsAlive())
                         allow = false;
             if (allow)
             {
                 uint32 quest = currentQuest;
                 if (Player* player = ObjectAccessor::GetPlayer(*me, playerGUID))
                 {
                     switch (quest)
                     {
                         case QUEST_BFV_FALLEN_HEROES:
                             me->Yell("$N has defeated the fallen heroes of Valhalas battles past. This is only a beginning, but it will suffice.", LANG_UNIVERSAL, ObjectAccessor::GetPlayer(*me, playerGUID));
                             break;
                         case QUEST_BFV_DARK_MASTER:
                             me->Yell("Khit'rix the Dark Master has been defeated by $N and his band of companions. Let the next challenge be issued!", LANG_UNIVERSAL, ObjectAccessor::GetPlayer(*me, playerGUID));
                             break;
                         case QUEST_BFV_SIGRID:
                             me->Yell("$N has defeated Sigrid Iceborn for a second time. Well, this time he did it with the help of his friends, but a win is a win!", LANG_UNIVERSAL, ObjectAccessor::GetPlayer(*me, playerGUID));
                             break;
                         case QUEST_BFV_CARNAGE:
                             me->Yell("The horror known as Carnage is no more. Could it be that $N is truly worthy of battle in Valhalas? We shall see.", LANG_UNIVERSAL, ObjectAccessor::GetPlayer(*me, playerGUID));
                             break;
                         case QUEST_BFV_THANE:
                             me->Yell("Thane Banahogg the Deathblow has fallen to $N and his fighting companions. He has but one challenge ahead of him. Who will it be?", LANG_UNIVERSAL, ObjectAccessor::GetPlayer(*me, playerGUID));
                             break;
                         case QUEST_BFV_FINAL:
                             me->Yell("The unthinkable has happened... $N has slain Prince Sandoval!", LANG_UNIVERSAL, ObjectAccessor::GetPlayer(*me, playerGUID));
                             break;
                     }
                     player->GroupEventHappens(quest, player);
                 }
                 playerGUID2 = playerGUID;
                 EnterEvadeMode();
                 if (quest == QUEST_BFV_FINAL)
                     events.ScheduleEvent(EVENT_VALHALAS_THIRD, 7000);
             }
             else
             {
                 uint32 quest = currentQuest;
                 if (Player* player = ObjectAccessor::GetPlayer(*me, playerGUID))
                 {
                     if (!player->HasQuest(quest))
                     {
                         ResetData();
                         return;
                     }
                 }
             }
         }
References currentQuest, CreatureAI::EnterEvadeMode(), EVENT_VALHALAS_THIRD, ObjectAccessor::GetCreature(), ObjectAccessor::GetPlayer(), LANG_UNIVERSAL, ScriptedAI::me, playerGUID, playerGUID2, QUEST_BFV_CARNAGE, QUEST_BFV_DARK_MASTER, QUEST_BFV_FALLEN_HEROES, QUEST_BFV_FINAL, QUEST_BFV_SIGRID, QUEST_BFV_THANE, ResetData(), summons, and Unit::Yell().
Referenced by UpdateAI().
JustSummoned()
void npc_battle_at_valhalas::npc_battle_at_valhalasAI::JustSummoned (Creature * creature) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 141 of file zone_icecrown.cpp.
         {
             summons.Summon(creature);
             if (creature->GetEntry() != NPC_PRINCE)
                 if (Player* player = ObjectAccessor::GetPlayer(*me, playerGUID))
                     creature->AI()->AttackStart(player);
         }
References Creature::AI(), UnitAI::AttackStart(), Object::GetEntry(), ObjectAccessor::GetPlayer(), ScriptedAI::me, NPC_PRINCE, playerGUID, SummonList::Summon(), and summons.
PrepareSummons()
void npc_battle_at_valhalas::npc_battle_at_valhalasAI::PrepareSummons () inline
Definition at line 149 of file zone_icecrown.cpp.
         {
             switch(currentQuest)
             {
                 case QUEST_BFV_FALLEN_HEROES:
                     me->SummonCreature(NPC_ELDRETH, 8245.5f, 3522.7f, 627.67f, 3.11f, TEMPSUMMON_MANUAL_DESPAWN, 30000);
                     me->SummonCreature(NPC_GENESS, 8217.45f, 3546.0f, 628.20f, 4.41f, TEMPSUMMON_MANUAL_DESPAWN, 30000);
                     me->SummonCreature(NPC_JHADRAS, 8179.99f, 3523.72f, 628.1f, 5.95f, TEMPSUMMON_MANUAL_DESPAWN, 30000);
                     me->SummonCreature(NPC_MASUD, 8184.97f, 3491.2f, 625.33f, 0.6f, TEMPSUMMON_MANUAL_DESPAWN, 30000);
                     me->SummonCreature(NPC_RITH, 8213.5f, 3478.5f, 626.79f, 1.56f, TEMPSUMMON_MANUAL_DESPAWN, 30000);
                     me->SummonCreature(NPC_TALLA, 8238.30f, 3485.5f, 628.5f, 2.157f, TEMPSUMMON_MANUAL_DESPAWN, 30000);
                     break;
                 case QUEST_BFV_DARK_MASTER:
                     me->SummonCreature(NPC_DARK_MASTER, 8184.97f, 3491.2f, 625.33f, 0.6f, TEMPSUMMON_MANUAL_DESPAWN, 30000);
                     break;
                 case QUEST_BFV_SIGRID:
                     me->SummonCreature(NPC_SIGRID, 8238.30f, 3485.5f, 628.5f, 2.157f, TEMPSUMMON_MANUAL_DESPAWN, 30000);
                     break;
                 case QUEST_BFV_CARNAGE:
                     me->SummonCreature(NPC_CARNAGE, 8179.99f, 3523.72f, 628.1f, 5.95f, TEMPSUMMON_MANUAL_DESPAWN, 30000);
                     break;
                 case QUEST_BFV_THANE:
                     me->SummonCreature(NPC_THANE, 8217.45f, 3546.0f, 628.20f, 4.41f, TEMPSUMMON_MANUAL_DESPAWN, 30000);
                     break;
                 case QUEST_BFV_FINAL:
                     me->SummonCreature(NPC_PRINCE, 8245.5f, 3522.7f, 627.67f, 3.11f, TEMPSUMMON_MANUAL_DESPAWN, 30000);
                     break;
             }
         }
References currentQuest, ScriptedAI::me, NPC_CARNAGE, NPC_DARK_MASTER, NPC_ELDRETH, NPC_GENESS, NPC_JHADRAS, NPC_MASUD, NPC_PRINCE, NPC_RITH, NPC_SIGRID, NPC_TALLA, NPC_THANE, QUEST_BFV_CARNAGE, QUEST_BFV_DARK_MASTER, QUEST_BFV_FALLEN_HEROES, QUEST_BFV_FINAL, QUEST_BFV_SIGRID, QUEST_BFV_THANE, WorldObject::SummonCreature(), and TEMPSUMMON_MANUAL_DESPAWN.
Referenced by UpdateAI().
Reset()
void npc_battle_at_valhalas::npc_battle_at_valhalasAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 127 of file zone_icecrown.cpp.
         {
             ResetData();
         }
References ResetData().
ResetData()
void npc_battle_at_valhalas::npc_battle_at_valhalasAI::ResetData () inline
Definition at line 132 of file zone_icecrown.cpp.
         {
             events.Reset();
             summons.DespawnAll();
             playerGUID.Clear();
             currentQuest = 0;
             me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_QUESTGIVER);
         }
References ObjectGuid::Clear(), currentQuest, SummonList::DespawnAll(), ScriptedAI::me, playerGUID, Object::SetFlag(), summons, UNIT_NPC_FLAG_QUESTGIVER, and UNIT_NPC_FLAGS.
Referenced by CheckSummons(), npc_battle_at_valhalas::OnQuestAccept(), and Reset().
StartBattle()
void npc_battle_at_valhalas::npc_battle_at_valhalasAI::StartBattle (ObjectGuid guid, uint32 questId) inline
Definition at line 179 of file zone_icecrown.cpp.
         {
             events.ScheduleEvent(EVENT_VALHALAS_FIRST, 6000);
             events.ScheduleEvent(EVENT_VALHALAS_CHECK_PLAYER, 30000);
             currentQuest = questId;
             playerGUID = guid;
         }
References currentQuest, EVENT_VALHALAS_CHECK_PLAYER, EVENT_VALHALAS_FIRST, and playerGUID.
Referenced by npc_battle_at_valhalas::OnQuestAccept().
UpdateAI()
void npc_battle_at_valhalas::npc_battle_at_valhalasAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 242 of file zone_icecrown.cpp.
         {
             events.Update(diff);
             switch (events.ExecuteEvent())
             {
                 case EVENT_VALHALAS_FIRST:
                     {
                         switch (currentQuest)
{
                             case QUEST_BFV_FALLEN_HEROES:
                                 events.ScheduleEvent(EVENT_VALHALAS_SECOND, 8000);
                                 me->Yell("$N and comrades in arms have chosen to accept honorable combat within the sacred confines of Valhalas.", LANG_UNIVERSAL, ObjectAccessor::GetPlayer(*me, playerGUID));
                                 break;
                             case QUEST_BFV_DARK_MASTER:
                                 events.ScheduleEvent(EVENT_VALHALAS_SECOND, 8000);
                                 me->Yell("$N has accepted the challenge of Khit'rix the Dark Master. May the gods show mercy upon him for Khit'rix surely will not.", LANG_UNIVERSAL, ObjectAccessor::GetPlayer(*me, playerGUID));
                                 break;
                             case QUEST_BFV_SIGRID:
                                 PrepareSummons();
                                 me->TextEmote("Circling Valhalas, Sigrid Iceborn approaches to seek her revenge!", nullptr, true);
                                 break;
                             case QUEST_BFV_CARNAGE:
                                 events.ScheduleEvent(EVENT_VALHALAS_SECOND, 8000);
                                 me->Yell("From the bowels of the Underhalls comes Carnage. Brave and foolish $N has accepted the challenge. $N and his group stand ready to face the monstrosity.", LANG_UNIVERSAL, ObjectAccessor::GetPlayer(*me, playerGUID));
                                 break;
                             case QUEST_BFV_THANE:
                                 events.ScheduleEvent(EVENT_VALHALAS_SECOND, 8000);
                                 me->Yell("Thane Banahogg returns to Valhalas for the first time in ages to prove that the vrykul are the only beings worthy to fight within its sacred ring. Will $N prove him wrong?", LANG_UNIVERSAL, ObjectAccessor::GetPlayer(*me, playerGUID));
                                 break;
                             case QUEST_BFV_FINAL:
                                 events.ScheduleEvent(EVENT_VALHALAS_SECOND, 8000);
                                 me->Yell("From the depths of Icecrown Citadel, one of the Lich King's chosen comes to put an end to the existence of $N and his friends.", LANG_UNIVERSAL, ObjectAccessor::GetPlayer(*me, playerGUID));
                                 break;
                         }
                         me->GetMotionMaster()->MovePoint(0, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ() + 20.0f);
                         me->SetPosition(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ() + 20.0f, me->GetOrientation());
                         break;
                     }
                 case EVENT_VALHALAS_SECOND:
                     {
                         switch (currentQuest)
{
                             case QUEST_BFV_FALLEN_HEROES:
                                 me->Yell("There can only be one outcome to such a battle: death for one side or the other. Let $n prove himself upon the bones of these outsiders who have fallen before!", LANG_UNIVERSAL, ObjectAccessor::GetPlayer(*me, playerGUID));
                                 me->TextEmote("The fallen heroes of Valhalas emerge from the ground to do battle once more!", nullptr, true);
                                 break;
                             case QUEST_BFV_DARK_MASTER:
                                 me->TextEmote("Khit'rix the Dark Master skitters into Valhalas from the southeast!", nullptr, true);
                                 break;
                             case QUEST_BFV_CARNAGE:
                                 me->TextEmote("Lumbering in from the south, the smell of Carnage precedes him!", nullptr, true);
                                 break;
                             case QUEST_BFV_THANE:
                                 me->TextEmote("Thane Banahogg appears upon the overlook to the southeast!", nullptr, true);
                                 break;
                             case QUEST_BFV_FINAL:
                                 me->Yell("Warriors of Jotunheim, I present to you, Blood Prince Sandoval!", LANG_UNIVERSAL);
                                 me->TextEmote("Without warning, Prince Sandoval magically appears within Valhalas!", nullptr, true);
                                 break;
                         }
                         PrepareSummons();
                         break;
                     }
                 case EVENT_VALHALAS_THIRD:
                     {
                         me->Yell("In defeating him, he and his fighting companions have proven themselves worthy of battle in this most sacred place of vrykul honor.", LANG_UNIVERSAL, ObjectAccessor::GetPlayer(*me, playerGUID));
                         events.ScheduleEvent(EVENT_VALHALAS_THIRD + 2, 7000);
                         break;
                     }
                 case EVENT_VALHALAS_THIRD+2:
                     {
                         me->Yell("ALL HAIL $N, CHAMPION OF VALHALAS! ", LANG_UNIVERSAL, ObjectAccessor::GetPlayer(*me, playerGUID2));
                         break;
                     }
                 case EVENT_VALHALAS_CHECK_PLAYER:
                     {
                         bool fail = true;
                         if (Player* player = ObjectAccessor::GetPlayer(*me, playerGUID))
                             if (me->GetDistance(player) < 100.0f)
{
                                 fail = false;
                                 CheckSummons();
                             }
                         if (fail)
                             EnterEvadeMode();
                         events.RepeatEvent(5000);
                         break;
                     }
             }
         }
References CheckSummons(), currentQuest, CreatureAI::EnterEvadeMode(), EVENT_VALHALAS_CHECK_PLAYER, EVENT_VALHALAS_FIRST, EVENT_VALHALAS_SECOND, EVENT_VALHALAS_THIRD, WorldObject::GetDistance(), Unit::GetMotionMaster(), Position::GetOrientation(), ObjectAccessor::GetPlayer(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), LANG_UNIVERSAL, ScriptedAI::me, MotionMaster::MovePoint(), playerGUID, playerGUID2, PrepareSummons(), QUEST_BFV_CARNAGE, QUEST_BFV_DARK_MASTER, QUEST_BFV_FALLEN_HEROES, QUEST_BFV_FINAL, QUEST_BFV_SIGRID, QUEST_BFV_THANE, Creature::SetPosition(), Unit::TextEmote(), and Unit::Yell().
Member Data Documentation
currentQuest
uint32 npc_battle_at_valhalas::npc_battle_at_valhalasAI::currentQuest
Definition at line 125 of file zone_icecrown.cpp.
Referenced by CheckSummons(), PrepareSummons(), ResetData(), StartBattle(), and UpdateAI().
events
EventMap npc_battle_at_valhalas::npc_battle_at_valhalasAI::events
Definition at line 121 of file zone_icecrown.cpp.
playerGUID
ObjectGuid npc_battle_at_valhalas::npc_battle_at_valhalasAI::playerGUID
Definition at line 123 of file zone_icecrown.cpp.
Referenced by CheckSummons(), JustSummoned(), ResetData(), StartBattle(), and UpdateAI().
playerGUID2
ObjectGuid npc_battle_at_valhalas::npc_battle_at_valhalasAI::playerGUID2
Definition at line 124 of file zone_icecrown.cpp.
Referenced by CheckSummons(), and UpdateAI().
summons
SummonList npc_battle_at_valhalas::npc_battle_at_valhalasAI::summons
Definition at line 122 of file zone_icecrown.cpp.
Referenced by CheckSummons(), JustSummoned(), and ResetData().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/zone_icecrown.cpp