Azerotcore-wotlk: GroupReference Class Reference
GroupReference Class Reference
#include <GroupReference.h>
Public Member Functions
GroupReference ()
~GroupReference () override
GroupReference * next ()
GroupReference const * next () const
uint8 getSubGroup () const
void setSubGroup (uint8 pSubGroup)
Public Member Functions inherited from Reference< Group, Player >
Reference ()
virtual ~Reference ()=default
void link (Group *toObj, Player *fromObj)
void unlink ()
void invalidate ()
bool isValid () const
Reference< Group, Player > * next ()
Reference< Group, Player > const * next () const
Reference< Group, Player > * prev ()
Reference< Group, Player > const * prev () const
Reference< Group, Player > * nocheck_next ()
Reference< Group, Player > const * nocheck_next () const
Reference< Group, Player > * nocheck_prev ()
Reference< Group, Player > const * nocheck_prev () const
Group * operator-> () const
Group * getTarget () const
Player * GetSource () const
Public Member Functions inherited from LinkedListElement
LinkedListElement ()
~LinkedListElement ()
bool hasNext () const
bool hasPrev () const
bool isInList () const
LinkedListElement * next ()
LinkedListElement const * next () const
LinkedListElement * prev ()
LinkedListElement const * prev () const
LinkedListElement * nocheck_next ()
LinkedListElement const * nocheck_next () const
LinkedListElement * nocheck_prev ()
LinkedListElement const * nocheck_prev () const
void delink ()
void insertBefore (LinkedListElement *pElem)
void insertAfter (LinkedListElement *pElem)
Protected Member Functions
void targetObjectBuildLink () override
void targetObjectDestroyLink () override
void sourceObjectDestroyLink () override
Protected Attributes
uint8 iSubGroup {0}
Detailed Description
Definition at line 26 of file GroupReference.h.
Constructor & Destructor Documentation
GroupReference()
GroupReference::GroupReference () inline
Definition at line 34 of file GroupReference.h.
 : Reference<Group, Player>() {}
~GroupReference()
GroupReference::~GroupReference () inline override
Definition at line 35 of file GroupReference.h.
 { unlink(); }
References Reference< Group, Player >::unlink().
Member Function Documentation
getSubGroup()
uint8 GroupReference::getSubGroup () const inline
Definition at line 38 of file GroupReference.h.
 { return iSubGroup; }
References iSubGroup.
Referenced by Player::GetOriginalSubGroup(), and Player::GetSubGroup().
next() [1/2]
GroupReference* GroupReference::next () inline
Definition at line 36 of file GroupReference.h.
 { return (GroupReference*)Reference<Group, Player>::next(); }
References Reference< TO, FROM >::next().
Referenced by KillRewarder::_InitGroupData(), KillRewarder::_RewardGroup(), BattlegroundQueue::AddGroup(), Group::AddMember(), Group::BroadcastPacket(), Group::BroadcastReadyCheck(), Group::CanJoinBattlegroundQueue(), Player::CanUninviteFromGroup(), Spell::CheckCast(), npc_unkor_the_ruthless::npc_unkor_the_ruthlessAI::DamageTaken(), SmartAI::EndPath(), npc_shay_leafrunner::npc_shay_leafrunnerAI::FailQuest(), Loot::FillLoot(), FollowerAI::GetLeaderForFollower(), Player::GetNextRandomRaidMember(), Unit::GetNextRandomRaidMemberOrPet(), Unit::GetPartyMembers(), Player::GetsRecruitAFriendBonus(), SmartScript::GetTargets(), Player::GroupEventHappens(), Group::GroupLoot(), Unit::HandleAuraRaidProcFromChargeWithValue(), WorldSession::HandleBattlemasterJoinArena(), WorldSession::HandleBattlemasterJoinOpcode(), misc_commandscript::HandleGroupSummonCommand(), OutdoorPvP::HandleKill(), lfg_commandscript::HandleLfgGroupInfoCommand(), WorldSession::HandleLfgPartyLockInfoRequestOpcode(), WorldSession::HandleLootMoneyOpcode(), WorldSession::HandlePushQuestToParty(), WorldSession::HandleQuestgiverAcceptQuestOpcode(), spell_razelikh_teleport_group::spell_razelikh_teleport_group_SpellScript::HandleScriptEffect(), WorldSession::HandleSetDungeonDifficultyOpcode(), WorldSession::HandleSetRaidDifficultyOpcode(), tele_commandscript::HandleTeleGroupCommand(), SmartAI::IsEscortInvokerInRange(), npc_escortAI::IsPlayerOrGroupInRange(), lfg::LFGMgr::JoinLfg(), npc_escortAI::JustDied(), FollowerAI::JustDied(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustDied(), npc_darnavan::npc_darnavanAI::JustDied(), Unit::Kill(), lfg::LFGMgr::MakeNewGroup(), Group::MasterLoot(), Group::NeedBeforeGreed(), lfg::LFGPlayerScript::OnMapChanged(), Player::RewardPlayerAndGroupAtEvent(), Group::SetDungeonDifficulty(), Group::SetRaidDifficulty(), Totem::UnSummon(), FollowerAI::UpdateAI(), PetAI::UpdateAllies(), Group::UpdatePlayerOutOfRange(), and GameObject::Use().
next() [2/2]
GroupReference const* GroupReference::next () const inline
Definition at line 37 of file GroupReference.h.
 { return (GroupReference const*)Reference<Group, Player>::next(); }
References Reference< TO, FROM >::next().
setSubGroup()
void GroupReference::setSubGroup (uint8 pSubGroup) inline
Definition at line 39 of file GroupReference.h.
 { iSubGroup = pSubGroup; }
References iSubGroup.
Referenced by Player::RemoveFromBattlegroundOrBattlefieldRaid(), Player::SetBattlegroundOrBattlefieldRaid(), Player::SetGroup(), and Player::SetOriginalGroup().
sourceObjectDestroyLink()
void GroupReference::sourceObjectDestroyLink () override protected virtual
Implements Reference< Group, Player >.
Definition at line 32 of file GroupReference.cpp.
 {
     // called from invalidate()
 }
targetObjectBuildLink()
void GroupReference::targetObjectBuildLink () override protected virtual
Implements Reference< Group, Player >.
Definition at line 21 of file GroupReference.cpp.
 {
     // called from link()
     getTarget()->LinkMember(this);
 }
References Reference< Group, Player >::getTarget(), and Group::LinkMember().
targetObjectDestroyLink()
void GroupReference::targetObjectDestroyLink () override protected virtual
Implements Reference< Group, Player >.
Definition at line 27 of file GroupReference.cpp.
 {
     // called from unlink()
 }
Member Data Documentation
iSubGroup
uint8 GroupReference::iSubGroup {0} protected
Definition at line 29 of file GroupReference.h.
Referenced by getSubGroup(), and setSubGroup().
The documentation for this class was generated from the following files:
src/server/game/Groups/GroupReference.h
src/server/game/Groups/GroupReference.cpp