Azerotcore-wotlk: src/common/Dynamic/TypeContainerVisitor.h File Reference
TypeContainerVisitor.h File Reference
#include "Define.h"
#include "Dynamic/TypeContainer.h"
Classes
class TypeContainerVisitor< VISITOR, TYPE_CONTAINER >
Functions
template<class VISITOR , class TYPE_CONTAINER >
void VisitorHelper (VISITOR &v, TYPE_CONTAINER &c)
template<class VISITOR >
void VisitorHelper (VISITOR &, ContainerMapList< TypeNull > &)
template<class VISITOR , class T >
void VisitorHelper (VISITOR &v, ContainerMapList< T > &c)
template<class VISITOR , class H , class T >
void VisitorHelper (VISITOR &v, ContainerMapList< TypeList< H, T >> &c)
template<class VISITOR , class OBJECT_TYPES >
void VisitorHelper (VISITOR &v, TypeMapContainer< OBJECT_TYPES > &c)
template<class VISITOR , class KEY_TYPE >
void VisitorHelper (VISITOR &, ContainerUnorderedMap< TypeNull, KEY_TYPE > &)
template<class VISITOR , class KEY_TYPE , class T >
void VisitorHelper (VISITOR &v, ContainerUnorderedMap< T, KEY_TYPE > &c)
template<class VISITOR , class KEY_TYPE , class H , class T >
void VisitorHelper (VISITOR &v, ContainerUnorderedMap< TypeList< H, T >, KEY_TYPE > &c)
template<class VISITOR , class OBJECT_TYPES , class KEY_TYPE >
void VisitorHelper (VISITOR &v, TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE > &c)
Function Documentation
VisitorHelper() [1/9]
template<class VISITOR > void VisitorHelper (VISITOR & , ContainerMapList< TypeNull > &)
Definition at line 40 of file TypeContainerVisitor.h.
 { }
VisitorHelper() [2/9]
template<class VISITOR , class KEY_TYPE > void VisitorHelper (VISITOR & , ContainerUnorderedMap< TypeNull, KEY_TYPE > &)
Definition at line 62 of file TypeContainerVisitor.h.
 { }
VisitorHelper() [3/9]
template<class VISITOR , class T > void VisitorHelper (VISITOR & v, ContainerMapList< T > & c)
Definition at line 42 of file TypeContainerVisitor.h.
 {
     v.Visit(c._element);
 }
References ContainerMapList< OBJECT >::_element.
VisitorHelper() [4/9]
template<class VISITOR , class H , class T > void VisitorHelper (VISITOR & v, ContainerMapList< TypeList< H, T >> & c)
Definition at line 48 of file TypeContainerVisitor.h.
 {
     VisitorHelper(v, c._elements);
     VisitorHelper(v, c._TailElements);
 }
References VisitorHelper().
VisitorHelper() [5/9]
template<class VISITOR , class KEY_TYPE , class T > void VisitorHelper (VISITOR & v, ContainerUnorderedMap< T, KEY_TYPE > & c)
Definition at line 65 of file TypeContainerVisitor.h.
 {
     v.Visit(c._element);
 }
References ContainerUnorderedMap< OBJECT, KEY_TYPE >::_element.
VisitorHelper() [6/9]
template<class VISITOR , class KEY_TYPE , class H , class T > void VisitorHelper (VISITOR & v, ContainerUnorderedMap< TypeList< H, T >, KEY_TYPE > & c)
Definition at line 71 of file TypeContainerVisitor.h.
 {
     VisitorHelper(v, c._elements);
     VisitorHelper(v, c._TailElements);
 }
References VisitorHelper().
VisitorHelper() [7/9]
template<class VISITOR , class TYPE_CONTAINER > void VisitorHelper (VISITOR & v, TYPE_CONTAINER & c)
Definition at line 34 of file TypeContainerVisitor.h.
 {
     v.Visit(c);
 }
Referenced by TypeContainerVisitor< VISITOR, TYPE_CONTAINER >::Visit(), and VisitorHelper().
VisitorHelper() [8/9]
template<class VISITOR , class OBJECT_TYPES > void VisitorHelper (VISITOR & v, TypeMapContainer< OBJECT_TYPES > & c)
Definition at line 55 of file TypeContainerVisitor.h.
 {
     VisitorHelper(v, c.GetElements());
 }
References TypeMapContainer< OBJECT_TYPES >::GetElements(), and VisitorHelper().
VisitorHelper() [9/9]
template<class VISITOR , class OBJECT_TYPES , class KEY_TYPE > void VisitorHelper (VISITOR & v, TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE > & c)
Definition at line 78 of file TypeContainerVisitor.h.
 {
     VisitorHelper(v, c.GetElements());
 }
References TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::GetElements(), and VisitorHelper().