Azerotcore-wotlk: G3D::Matrix::Impl Class Reference
G3D::Matrix::Impl Class Reference
#include <Matrix.h>
Public Member Functions
~Impl ()
Public Member Functions inherited from G3D::ReferenceCountedObject
virtual ~ReferenceCountedObject ()
Static Public Member Functions
static void * operator new (size_t size)
static void operator delete (void *p)
Private Member Functions
void setSize (int newRows, int newCols)
Impl ()
Impl (const Matrix3 &M)
Impl (const Matrix4 &M)
Impl (int r, int c)
Impl & operator= (const Impl &m)
Impl (const Impl &B)
void setZero ()
void set (int r, int c, T v)
const T & get (int r, int c) const
void mul (const Impl &B, Impl &out) const
void add (const Impl &B, Impl &out) const
void add (T B, Impl &out) const
void sub (const Impl &B, Impl &out) const
void sub (T B, Impl &out) const
void lsub (T B, Impl &out) const
void arrayMul (const Impl &B, Impl &out) const
void mul (T B, Impl &out) const
void arrayDiv (const Impl &B, Impl &out) const
void div (T B, Impl &out) const
void negate (Impl &out) const
void inverseViaAdjoint (Impl &out) const
void inverseInPlaceGaussJordan ()
void adjoint (Impl &out) const
void cofactor (Impl &out) const
T cofactor (int r, int c) const
void transpose (Impl &out) const
T determinant () const
T determinant (int r, int c) const
void arrayLog (Impl &out) const
void arrayExp (Impl &out) const
void arraySqrt (Impl &out) const
void arrayCos (Impl &out) const
void arraySin (Impl &out) const
void swapRows (int r0, int r1)
void swapAndNegateCols (int c0, int c1)
void mulRow (int r, const T &v)
void abs (Impl &out) const
void withoutRowAndCol (int excludeRow, int excludeCol, Impl &out) const
bool anyNonZero () const
bool allNonZero () const
void setRow (int r, const T *vals)
void setCol (int c, const T *vals)
Private Attributes
T ** elt
T * data
int R
int C
int dataSize
Friends
class Matrix
Detailed Description
Used internally by Matrix.
Does not throw exceptions– assumes the caller has taken care of argument checking.
Definition at line 82 of file Matrix.h.
Constructor & Destructor Documentation
~Impl()
G3D::Matrix::Impl::~Impl ()
Definition at line 580 of file Matrix.cpp.
                   {
     //delete[] elt;
     System::free(elt);
     System::alignedFree(data);
 }
References G3D::System::alignedFree(), and G3D::System::free().
Impl() [1/5]
G3D::Matrix::Impl::Impl () inline private
Definition at line 117 of file Matrix.h.
 : elt(NULL), data(NULL), R(0), C(0), dataSize(0) {}
Impl() [2/5]
G3D::Matrix::Impl::Impl (const Matrix3 & M) private
Definition at line 529 of file Matrix.cpp.
                                  : elt(NULL), data(NULL), R(0), C(0), dataSize(0){
     setSize(3, 3);
     for (int r = 0; r < 3; ++r) {
         for (int c = 0; c < 3; ++c) {
             set(r, c, M[r][c]);
         }
     }
 }
References mpq::c, set(), and setSize().
Impl() [3/5]
G3D::Matrix::Impl::Impl (const Matrix4 & M) private
Definition at line 540 of file Matrix.cpp.
                                 : elt(NULL), data(NULL), R(0), C(0), dataSize(0) {
     setSize(4, 4);
     for (int r = 0; r < 4; ++r) {
         for (int c = 0; c < 4; ++c) {
             set(r, c, M[r][c]);
         }
     }
 }
References mpq::c, set(), and setSize().
Impl() [4/5]
G3D::Matrix::Impl::Impl (int r, int c) inline private
Definition at line 123 of file Matrix.h.
                                   : elt(NULL), data(NULL), R(0), C(0), dataSize(0) {
             setSize(r, c);
         }
References mpq::c, and setSize().
Impl() [5/5]
G3D::Matrix::Impl::Impl (const Impl & B) inline private
Definition at line 129 of file Matrix.h.
                                    : elt(NULL), data(NULL), R(0), C(0), dataSize(0) {
             // Use the assignment operator
             *this = B;
         }
Member Function Documentation
abs()
void G3D::Matrix::Impl::abs (Impl & out) const private
add() [1/2]
void G3D::Matrix::Impl::add (const Impl & B, Impl & out) const private
Ok if out == this or out == B
add() [2/2]
void G3D::Matrix::Impl::add (T B, Impl & out) const private
Ok if out == this or out == B
adjoint()
void G3D::Matrix::Impl::adjoint (Impl & out) const private
Definition at line 776 of file Matrix.cpp.
{
     cofactor(out);
     // Transpose is safe to perform in place
     out.transpose(out);
 }
References transpose().
allNonZero()
bool G3D::Matrix::Impl::allNonZero () const private
Definition at line 1474 of file Matrix.cpp.
{
     int N = R * C;
     for (int i = 0; i < N; ++i) {
         if (data[i] == 0.0) {
             return false;
         }
     }
     return true;
 }
anyNonZero()
bool G3D::Matrix::Impl::anyNonZero () const private
Definition at line 1463 of file Matrix.cpp.
{
     int N = R * C;
     for (int i = 0; i < N; ++i) {
         if (data[i] != 0.0) {
             return true;
         }
     }
     return false;
 }
arrayCos()
void G3D::Matrix::Impl::arrayCos (Impl & out) const private
arrayDiv()
void G3D::Matrix::Impl::arrayDiv (const Impl & B, Impl & out) const private
Ok if out == this or out == B
arrayExp()
void G3D::Matrix::Impl::arrayExp (Impl & out) const private
arrayLog()
void G3D::Matrix::Impl::arrayLog (Impl & out) const private
arrayMul()
void G3D::Matrix::Impl::arrayMul (const Impl & B, Impl & out) const private
Ok if out == this or out == B
arraySin()
void G3D::Matrix::Impl::arraySin (Impl & out) const private
arraySqrt()
void G3D::Matrix::Impl::arraySqrt (Impl & out) const private
cofactor() [1/2]
void G3D::Matrix::Impl::cofactor (Impl & out) const private
Matrix of all cofactors
Definition at line 783 of file Matrix.cpp.
{
     debugAssert(&out != this);
     for(int r = 0; r < R; ++r) {
         for(int c = 0; c < C; ++c) {
             out.set(r, c, cofactor(r, c));
         }
     }
 }
References mpq::c, debugAssert, and set().
cofactor() [2/2]
Matrix::T G3D::Matrix::Impl::cofactor (int r, int c) const private
Cofactor [r][c] is defined as C[r][c] = -1 ^(r+c) * det(A[r][c]), where A[r][c] is the (R-1)x(C-1) matrix formed by removing row r and column c from the original matrix.
Definition at line 793 of file Matrix.cpp.
{
     // Strang p. 217
     float s = isEven(r + c) ? 1.0f : -1.0f;
     return s * determinant(r, c);
 }
References mpq::c, G3D::Matrix::determinant(), and G3D::isEven().
determinant() [1/2]
Matrix::T G3D::Matrix::Impl::determinant () const private
Definition at line 823 of file Matrix.cpp.
{
     debugAssert(R == C);
     // Compute using cofactors
     switch(R) {
     case 0:
         return 0;
     case 1:
         // Determinant of a 1x1 is the element
         return elt[0][0];
     case 2:
         // Determinant of a 2x2 is ad-bc
         return elt[0][0] * elt[1][1] - elt[0][1] * elt[1][0];
     case 3:
         {
           // Determinant of an nxn matrix is the dot product of the first
           // row with the first row of cofactors.  The base cases of this
           // method get called a lot, so we spell out the implementation
           // for the 3x3 case.
           float cofactor00 = elt[1][1] * elt[2][2] - elt[1][2] * elt[2][1];
           float cofactor10 = elt[1][2] * elt[2][0] - elt[1][0] * elt[2][2];
           float cofactor20 = elt[1][0] * elt[2][1] - elt[1][1] * elt[2][0];
           return Matrix::T(
             elt[0][0] * cofactor00 +
             elt[0][1] * cofactor10 +
             elt[0][2] * cofactor20);
         }
     default:
         {
             // Determinant of an n x n matrix is the dot product of the first
             // row with the first row of cofactors
             T det = 0;
             for (int c = 0; c < C; ++c) {
                 det += elt[0][c] * cofactor(0, c);
             }
             return det;
         }
     }
 }
References mpq::c, and debugAssert.
Referenced by determinant().
determinant() [2/2]
Matrix::T G3D::Matrix::Impl::determinant (int r, int c) const private
Determinant computed without the given row and column
Definition at line 801 of file Matrix.cpp.
{
     debugAssert(R > 0);
     debugAssert(C > 0);
     Impl A(R - 1, C - 1);
     withoutRowAndCol(nr, nc, A);
     return A.determinant();
 }
References debugAssert, and determinant().
div()
void G3D::Matrix::Impl::div (T B, Impl & out) const private
Ok if out == this or out == B
Referenced by inverseViaAdjoint().
get()
const T& G3D::Matrix::Impl::get (int r, int c) const inline private
Definition at line 142 of file Matrix.h.
{
             debugAssert(r < R);
             debugAssert(c < C);
             return elt[r][c];
         }
References C, mpq::c, debugAssert, elt, and R.
Referenced by mul().
inverseInPlaceGaussJordan()
void G3D::Matrix::Impl::inverseInPlaceGaussJordan () private
Use Gaussian elimination with pivots to solve for the inverse destructively in place.
Definition at line 1353 of file Matrix.cpp.
{
     debugAssertM(R == C,
         format(
         "Cannot perform Gauss-Jordan inverse on a non-square matrix."
         " (Argument was %dx%d)",
         R, C));
     // Exchange to float elements
 #   define SWAP(x, y) {float temp = x; x = y; y = temp;}
     // The integer arrays pivot, rowIndex, and colIndex are
     // used for bookkeeping on the pivoting
     static Array<int> colIndex, rowIndex, pivot;
     int col = 0, row = 0;
     colIndex.resize(R);
     rowIndex.resize(R);
     pivot.resize(R);
     static const int NO_PIVOT = -1;
     // Initialize the pivot array to default values.
     for (int i = 0; i < R; ++i) {
         pivot[i] = NO_PIVOT;
     }
     // This is the main loop over the columns to be reduced
     // Loop over the columns.
     for (int c = 0; c < R; ++c) {
         // Find the largest element and use that as a pivot
         float largestMagnitude = 0.0;
         // This is the outer loop of the search for a pivot element
         for (int r = 0; r < R; ++r) {
             // Unless we've already found the pivot, keep going
             if (pivot[r] != 0) {
                 // Find the largest pivot
                 for (int k = 0; k < R; ++k) {
                     if (pivot[k] == NO_PIVOT) {
                         const float mag = fabs(elt[r][k]);
                         if (mag >= largestMagnitude) {
                             largestMagnitude = mag;
                             row = r; col = k;
                         }
                     }
                 }
             }
         }
         pivot[col] += 1;
         // Interchange columns so that the pivot element is on the diagonal (we'll have to undo this
         // at the end)
         if (row != col) {
             for (int k = 0; k < R; ++k) {
                 SWAP(elt[row][k], elt[col][k])
             }
         }
         // The pivot is now at [row, col]
         rowIndex[c] = row;
         colIndex[c] = col;
         double piv = elt[col][col];
         debugAssertM(piv != 0.0, "Matrix is singular");
         // Divide everything by the pivot (avoid computing the division
         // multiple times).
         const double pivotInverse = 1.0 / piv;
         elt[col][col] = 1.0;
         for (int k = 0; k < R; ++k) {
             elt[col][k] *= Matrix::T(pivotInverse);
         }
         // Reduce all rows
         for (int r = 0; r < R; ++r) {
             // Skip over the pivot row
             if (r != col) {
                 double oldValue = elt[r][col];
                 elt[r][col] = 0.0;
                 for (int k = 0; k < R; ++k) {
                     elt[r][k] -= Matrix::T(elt[col][k] * oldValue);
                 }
             }
         }
     }
     // Put the columns back in the correct locations
     for (int i = R - 1; i >= 0; --i) {
         if (rowIndex[i] != colIndex[i]) {
             for (int k = 0; k < R; ++k) {
                 SWAP(elt[k][rowIndex[i]], elt[k][colIndex[i]]);
             }
         }
     }
 #   undef SWAP
 }
References mpq::c, G3D::Matrix::col(), debugAssertM, G3D::format(), G3D::Array< T, MIN_ELEMENTS >::resize(), G3D::Matrix::row(), and SWAP.
Referenced by G3D::Matrix::inverse().
inverseViaAdjoint()
void G3D::Matrix::Impl::inverseViaAdjoint (Impl & out) const private
Slow way of computing an inverse; for reference
Definition at line 734 of file Matrix.cpp.
{
     debugAssert(&out != this);
     // Inverse = adjoint / determinant
     adjoint(out);
     // Don't call the determinant method when we already have an
     // adjoint matrix; there's a faster way of computing it: the dot
     // product of the first row and the adjoint's first col.
     double det = 0.0;
     for (int r = R - 1; r >= 0; --r) {
         det += elt[0][r] * out.elt[r][0];
     }
     out.div(Matrix::T(det), out);
 }
References G3D::Matrix::adjoint(), debugAssert, div(), and elt.
lsub()
void G3D::Matrix::Impl::lsub (Matrix::T B, Impl & out) const private
B - this
Definition at line 722 of file Matrix.cpp.
{
     const Impl& A = *this;
     debugAssert(A.C == out.C);
     debugAssert(A.R == out.R);
     for (int i = R * C - 1; i >= 0; --i) {
         out.data[i] = B - A.data[i];
     }
 }
References C, data, debugAssert, and R.
mul() [1/2]
void G3D::Matrix::Impl::mul (const Impl & B, Impl & out) const private
Multiplies this by B and puts the result in out.
Definition at line 632 of file Matrix.cpp.
{
     const Impl& A = *this;
     debugAssertM(
         (this != &out) && (&B != &out),
         "Output argument to mul cannot be the same as an input argument.");
     debugAssert(A.C == B.R);
     debugAssert(A.R == out.R);
     debugAssert(B.C == out.C);
     for (int r = 0; r < out.R; ++r) {
         for (int c = 0; c < out.C; ++c) {
             T sum = 0.0;
             for (int i = 0; i < A.C; ++i) {
                 sum += A.get(r, i) * B.get(i, c);
             }
             out.set(r, c, sum);
         }
     }
 }
References C, mpq::c, debugAssert, debugAssertM, get(), R, and set().
mul() [2/2]
void G3D::Matrix::Impl::mul (T B, Impl & out) const private
Ok if out == this or out == B
mulRow()
void G3D::Matrix::Impl::mulRow (int r, const T & v) private
Definition at line 623 of file Matrix.cpp.
{
     T* row = elt[r];
     for (int c = 0; c < C; ++c) {
         row[c] *= v;
     }
 }
References mpq::c, and G3D::Matrix::row().
negate()
void G3D::Matrix::Impl::negate (Impl & out) const private
operator delete()
static void G3D::Matrix::Impl::operator delete (void * p) inline static
Definition at line 89 of file Matrix.h.
{
             System::free(p);
         }
References G3D::System::free().
operator new()
static void* G3D::Matrix::Impl::operator new (size_t size) inline static
Definition at line 85 of file Matrix.h.
{
             return System::malloc(size);
         }
References G3D::System::malloc(), and G3D::Matrix::size().
operator=()
Matrix::Impl & G3D::Matrix::Impl::operator= (const Impl & m) private
Definition at line 587 of file Matrix.cpp.
{
     setSize(m.R, m.C);
     System::memcpy(data, m.data, R * C * sizeof(T));
     ++Matrix::debugNumCopyOps;
     return *this;
 }
References C, data, G3D::Matrix::debugNumCopyOps, G3D::System::memcpy(), and R.
set()
void G3D::Matrix::Impl::set (int r, int c, T v) inline private
Definition at line 136 of file Matrix.h.
{
             debugAssert(r < R);
             debugAssert(c < C);
             elt[r][c] = v;
         }
References C, mpq::c, debugAssert, elt, and R.
Referenced by cofactor(), Impl(), mul(), and transpose().
setCol()
void G3D::Matrix::Impl::setCol (int c, const T * vals) private
Definition at line 816 of file Matrix.cpp.
{
     for (int r = 0; r < R; ++r) {
         elt[r][c] = vals[r];
     }
 }
References mpq::c.
setRow()
void G3D::Matrix::Impl::setRow (int r, const T * vals) private
Definition at line 810 of file Matrix.cpp.
{
     debugAssert(r >= 0);
     System::memcpy(elt[r], vals, sizeof(T) * C);
 }
References debugAssert, and G3D::System::memcpy().
setSize()
void G3D::Matrix::Impl::setSize (int newRows, int newCols) private
If R*C is much larger or smaller than the current, deletes all previous data and resets to random data. Otherwise re-uses existing memory and just resets R, C, and the row pointers.
Definition at line 550 of file Matrix.cpp.
{
     if ((R == newRows) && (C == newCols)) {
         // Nothing to do
         return;
     }
     int newSize = newRows * newCols;
     R = newRows; C = newCols;
     // Only allocate if we need more space
     // or the size difference is ridiculous
     if ((newSize > dataSize) || (newSize < dataSize / 4)) {
         System::alignedFree(data);
         data = (float*)System::alignedMalloc(R * C * sizeof(T), 16);
         ++Matrix::debugNumAllocOps;
         dataSize = newSize;
     }
     // Construct the row pointers
     //delete[] elt;
     System::free(elt);
     elt = (T**)System::malloc(R * sizeof(T*));// new T*[R];
     for (int r = 0; r < R; ++ r) {
         elt[r] = data + r * C;
     }
 }
References G3D::System::alignedFree(), G3D::System::alignedMalloc(), G3D::Matrix::debugNumAllocOps, G3D::System::free(), and G3D::System::malloc().
Referenced by Impl().
setZero()
void G3D::Matrix::Impl::setZero () private
Definition at line 595 of file Matrix.cpp.
{
     System::memset(data, 0, R * C * sizeof(T));
 }
References G3D::System::memset().
Referenced by G3D::Matrix::identity(), and G3D::Matrix::zero().
sub() [1/2]
void G3D::Matrix::Impl::sub (const Impl & B, Impl & out) const private
Ok if out == this or out == B
sub() [2/2]
void G3D::Matrix::Impl::sub (T B, Impl & out) const private
Ok if out == this or out == B
swapAndNegateCols()
void G3D::Matrix::Impl::swapAndNegateCols (int c0, int c1) private
Definition at line 612 of file Matrix.cpp.
{
     for (int r = 0; r < R; ++r) {
         T* row = elt[r];
         const T temp = -row[c0];
         row[c0] = -row[c1];
         row[c1] = temp;
     }
 }
References G3D::Matrix::row().
swapRows()
void G3D::Matrix::Impl::swapRows (int r0, int r1) private
Definition at line 600 of file Matrix.cpp.
{
     T* R0 = elt[r0];
     T* R1 = elt[r1];
     for (int c = 0; c < C; ++c) {
         T temp = R0[c];
         R0[c] = R1[c];
         R1[c] = temp;
     }
 }
References mpq::c.
transpose()
void G3D::Matrix::Impl::transpose (Impl & out) const private
Ok if out == this or out == B
Definition at line 753 of file Matrix.cpp.
{
     debugAssert(out.R == C);
     debugAssert(out.C == R);
     if (&out == this) {
         // Square matrix in place
         for (int r = 0; r < R; ++r) {
             for (int c = r + 1; c < C; ++c) {
                 T temp = get(r, c);
                 out.set(r, c, get(c, r));
                 out.set(c, r, temp);
             }
         }
     } else {
         for (int r = 0; r < R; ++r) {
             for (int c = 0; c < C; ++c) {
                 out.set(c, r, get(r, c));
             }
         }
     }
 }
References C, mpq::c, debugAssert, G3D::Matrix::get(), R, and set().
Referenced by adjoint().
withoutRowAndCol()
void G3D::Matrix::Impl::withoutRowAndCol (int excludeRow, int excludeCol, Impl & out) const private
Makes a (R-1)x(C-1) copy of this matrix
Definition at line 873 of file Matrix.cpp.
{
     debugAssert(out.R == R - 1);
     debugAssert(out.C == C - 1);
     for (int r = 0; r < out.R; ++r) {
         for (int c = 0; c < out.C; ++c) {
             out.elt[r][c] = elt[r + ((r >= excludeRow) ? 1 : 0)][c + ((c >= excludeCol) ? 1 : 0)];
         }
     }
 }
References C, mpq::c, debugAssert, elt, and R.
Friends And Related Function Documentation
Matrix
friend class Matrix friend
Definition at line 96 of file Matrix.h.
Member Data Documentation
C
int G3D::Matrix::Impl::C private
The number of columns
Definition at line 108 of file Matrix.h.
Referenced by get(), lsub(), mul(), operator=(), set(), transpose(), and withoutRowAndCol().
data
T* G3D::Matrix::Impl::data private
Row major data for the entire matrix.
Definition at line 102 of file Matrix.h.
Referenced by lsub(), G3D::Matrix::one(), operator=(), and G3D::Matrix::random().
dataSize
int G3D::Matrix::Impl::dataSize private
Definition at line 110 of file Matrix.h.
elt
T** G3D::Matrix::Impl::elt private
elt[r][c] = the element. Pointers into data.
Definition at line 99 of file Matrix.h.
Referenced by get(), G3D::Matrix::identity(), inverseViaAdjoint(), set(), and withoutRowAndCol().
R
int G3D::Matrix::Impl::R private
The number of rows
Definition at line 105 of file Matrix.h.
Referenced by get(), lsub(), mul(), operator=(), set(), transpose(), and withoutRowAndCol().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/Matrix.h
deps/g3dlite/source/Matrix.cpp