Azerotcore-wotlk: boss_leotheras_the_blind::boss_leotheras_the_blindAI Struct Reference
boss_leotheras_the_blind::boss_leotheras_the_blindAI Struct Reference
Public Member Functions
boss_leotheras_the_blindAI (Creature *creature)
void Reset () override
void InitializeAI () override
void JustReachedHome () override
void SummonChannelers ()
void MoveInLineOfSight (Unit *) override
void JustSummoned (Creature *summon) override
void SummonedCreatureDies (Creature *summon, Unit *) override
void KilledUnit (Unit *) override
void JustDied (Unit *killer) override
void EnterCombat (Unit *who) override
void AttackStart (Unit *who) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 93 of file boss_leotheras_the_blind.cpp.
Constructor & Destructor Documentation
boss_leotheras_the_blindAI()
boss_leotheras_the_blind::boss_leotheras_the_blindAI::boss_leotheras_the_blindAI (Creature * creature) inline
Definition at line 95 of file boss_leotheras_the_blind.cpp.
                                                        : BossAI(creature, DATA_LEOTHERAS_THE_BLIND)
         {
         }
Member Function Documentation
AttackStart()
void boss_leotheras_the_blind::boss_leotheras_the_blindAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 181 of file boss_leotheras_the_blind.cpp.
         {
             if (who && me->Attack(who, true))
                 me->GetMotionMaster()->MoveChase(who, me->GetDisplayId() == me->GetNativeDisplayId() ? 0.0f : 25.0f);
         }
References Unit::Attack(), Unit::GetDisplayId(), Unit::GetMotionMaster(), Unit::GetNativeDisplayId(), ScriptedAI::me, and MotionMaster::MoveChase().
EnterCombat()
void boss_leotheras_the_blind::boss_leotheras_the_blindAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from BossAI.
Definition at line 175 of file boss_leotheras_the_blind.cpp.
         {
             BossAI::EnterCombat(who);
             me->SetStandState(UNIT_STAND_STATE_KNEEL);
         }
References BossAI::EnterCombat(), ScriptedAI::me, Unit::SetStandState(), and UNIT_STAND_STATE_KNEEL.
InitializeAI()
void boss_leotheras_the_blind::boss_leotheras_the_blindAI::InitializeAI () inline override virtual
Reimplemented from UnitAI.
Definition at line 109 of file boss_leotheras_the_blind.cpp.
         {
             BossAI::InitializeAI();
             SummonChannelers();
         }
References UnitAI::InitializeAI(), and SummonChannelers().
JustDied()
void boss_leotheras_the_blind::boss_leotheras_the_blindAI::JustDied (Unit * killer) inline override virtual
Reimplemented from BossAI.
Definition at line 168 of file boss_leotheras_the_blind.cpp.
         {
             me->CastSpell(me, SPELL_CLEAR_CONSUMING_MADNESS, true);
             Talk(SAY_DEATH);
             BossAI::JustDied(killer);
         }
References Unit::CastSpell(), BossAI::JustDied(), ScriptedAI::me, SAY_DEATH, SPELL_CLEAR_CONSUMING_MADNESS, and CreatureAI::Talk().
JustReachedHome()
void boss_leotheras_the_blind::boss_leotheras_the_blindAI::JustReachedHome () inline override virtual
Reimplemented from BossAI.
Definition at line 115 of file boss_leotheras_the_blind.cpp.
         {
             BossAI::JustReachedHome();
             SummonChannelers();
         }
References BossAI::JustReachedHome(), and SummonChannelers().
JustSummoned()
void boss_leotheras_the_blind::boss_leotheras_the_blindAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
Definition at line 134 of file boss_leotheras_the_blind.cpp.
         {
             summons.Summon(summon);
         }
References SummonList::Summon(), and BossAI::summons.
KilledUnit()
void boss_leotheras_the_blind::boss_leotheras_the_blindAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 159 of file boss_leotheras_the_blind.cpp.
         {
             if (events.GetNextEventTime(EVENT_KILL_TALK) == 0)
             {
                 Talk(me->GetDisplayId() != me->GetNativeDisplayId() ? SAY_DEMON_SLAY : SAY_NIGHTELF_SLAY);
                 events.ScheduleEvent(EVENT_KILL_TALK, 6000);
             }
         }
References EVENT_KILL_TALK, Unit::GetDisplayId(), Unit::GetNativeDisplayId(), ScriptedAI::me, SAY_DEMON_SLAY, SAY_NIGHTELF_SLAY, and CreatureAI::Talk().
MoveInLineOfSight()
void boss_leotheras_the_blind::boss_leotheras_the_blindAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 132 of file boss_leotheras_the_blind.cpp.
 { }
Reset()
void boss_leotheras_the_blind::boss_leotheras_the_blindAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 99 of file boss_leotheras_the_blind.cpp.
         {
             BossAI::Reset();
             me->CastSpell(me, SPELL_CLEAR_CONSUMING_MADNESS, true);
             me->CastSpell(me, SPELL_DUAL_WIELD, true);
             me->SetStandState(UNIT_STAND_STATE_KNEEL);
             me->LoadEquipment(0, true);
             me->SetReactState(REACT_PASSIVE);
         }
References Unit::CastSpell(), Creature::LoadEquipment(), ScriptedAI::me, REACT_PASSIVE, BossAI::Reset(), Creature::SetReactState(), Unit::SetStandState(), SPELL_CLEAR_CONSUMING_MADNESS, SPELL_DUAL_WIELD, and UNIT_STAND_STATE_KNEEL.
SummonChannelers()
void boss_leotheras_the_blind::boss_leotheras_the_blindAI::SummonChannelers () inline
Definition at line 121 of file boss_leotheras_the_blind.cpp.
         {
             me->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_BANISH, false);
             me->CastSpell(me, SPELL_BANISH, true);
             me->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_BANISH, true);
             summons.DespawnAll();
             for (uint8 i = 0; i < MAX_CHANNELERS; ++i)
                 me->SummonCreature(NPC_GREYHEART_SPELLBINDER, channelersPos[i], TEMPSUMMON_CORPSE_TIMED_DESPAWN, 5000);
         }
References Unit::ApplySpellImmune(), Unit::CastSpell(), channelersPos, SummonList::DespawnAll(), IMMUNITY_MECHANIC, MAX_CHANNELERS, ScriptedAI::me, MECHANIC_BANISH, NPC_GREYHEART_SPELLBINDER, SPELL_BANISH, WorldObject::SummonCreature(), BossAI::summons, and TEMPSUMMON_CORPSE_TIMED_DESPAWN.
Referenced by InitializeAI(), and JustReachedHome().
SummonedCreatureDies()
void boss_leotheras_the_blind::boss_leotheras_the_blindAI::SummonedCreatureDies (Creature * summon, Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 139 of file boss_leotheras_the_blind.cpp.
         {
             me->SetInCombatWithZone();
             summons.Despawn(summon);
             if (summon->GetEntry() == NPC_GREYHEART_SPELLBINDER)
                 if (!summons.HasEntry(NPC_GREYHEART_SPELLBINDER))
                 {
                     me->RemoveAllAuras();
                     me->LoadEquipment();
                     me->SetReactState(REACT_AGGRESSIVE);
                     me->SetStandState(UNIT_STAND_STATE_STAND);
                     Talk(SAY_AGGRO);
                     events.ScheduleEvent(EVENT_SPELL_BERSERK, 600000);
                     events.ScheduleEvent(EVENT_HEALTH_CHECK, 1000);
                     events.ScheduleEvent(EVENT_SWITCH_TO_DEMON, 55000);
                     events.ScheduleEvent(EVENT_SPELL_WHIRLWIND, 10000);
                 }
         }
References SummonList::Despawn(), EVENT_HEALTH_CHECK, EVENT_SPELL_BERSERK, EVENT_SPELL_WHIRLWIND, EVENT_SWITCH_TO_DEMON, Object::GetEntry(), SummonList::HasEntry(), Creature::LoadEquipment(), ScriptedAI::me, NPC_GREYHEART_SPELLBINDER, REACT_AGGRESSIVE, Unit::RemoveAllAuras(), SAY_AGGRO, Creature::SetInCombatWithZone(), Creature::SetReactState(), Unit::SetStandState(), BossAI::summons, CreatureAI::Talk(), and UNIT_STAND_STATE_STAND.
UpdateAI()
void boss_leotheras_the_blind::boss_leotheras_the_blindAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 187 of file boss_leotheras_the_blind.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_SPELL_BERSERK:
                     me->CastSpell(me, SPELL_BERSERK, true);
                     break;
                 case EVENT_HEALTH_CHECK:
                     if (me->HealthBelowPct(15))
                     {
                         if (me->GetDisplayId() != me->GetNativeDisplayId())
{
                             DoResetThreat();
                             me->LoadEquipment();
                             me->RemoveAurasDueToSpell(SPELL_METAMORPHOSIS);
                             events.ScheduleEvent(EVENT_SPELL_WHIRLWIND, 10000);
                         }
                         events.CancelEvent(EVENT_SWITCH_TO_DEMON);
                         events.CancelEvent(EVENT_SPELL_INSIDIOUS_WHISPER);
                         events.DelayEvents(10000);
                         events.ScheduleEvent(EVENT_SUMMON_DEMON, 4000);
                         events.ScheduleEvent(EVENT_RESTORE_FIGHT, 6000);
                         me->SetStandState(UNIT_STAND_STATE_KNEEL);
                         me->SetReactState(REACT_PASSIVE);
                         me->GetMotionMaster()->Clear();
                         me->StopMoving();
                         Talk(SAY_FINAL_FORM);
                         break;
                     }
                     events.ScheduleEvent(EVENT_HEALTH_CHECK, 1000);
                     break;
                 case EVENT_SWITCH_TO_DEMON:
                     DoResetThreat();
                     Talk(SAY_SWITCH_TO_DEMON);
                     me->LoadEquipment(0, true);
                     me->GetMotionMaster()->MoveChase(me->GetVictim(), 25.0f);
                     me->CastSpell(me, SPELL_METAMORPHOSIS, true);
                     events.CancelEvent(EVENT_SPELL_WHIRLWIND);
                     events.ScheduleEvent(EVENT_SPELL_INSIDIOUS_WHISPER, 25000);
                     events.ScheduleEvent(EVENT_SWITCH_TO_ELF, 60000);
                     break;
                 case EVENT_SWITCH_TO_ELF:
                     DoResetThreat();
                     me->LoadEquipment();
                     me->GetMotionMaster()->MoveChase(me->GetVictim(), 0.0f);
                     me->RemoveAurasDueToSpell(SPELL_METAMORPHOSIS);
                     events.ScheduleEvent(EVENT_SWITCH_TO_DEMON, 55000);
                     events.ScheduleEvent(EVENT_SPELL_WHIRLWIND, 10000);
                     break;
                 case EVENT_SPELL_WHIRLWIND:
                     me->CastSpell(me, SPELL_WHIRLWIND, false);
                     events.ScheduleEvent(EVENT_SPELL_WHIRLWIND, 27000);
                     break;
                 case EVENT_SPELL_INSIDIOUS_WHISPER:
                     Talk(SAY_INNER_DEMONS);
                     me->CastCustomSpell(SPELL_INSIDIOUS_WHISPER, SPELLVALUE_MAX_TARGETS, 5, me, false);
                     break;
                 case EVENT_SUMMON_DEMON:
                     me->CastSpell(me, SPELL_SUMMON_SHADOW_OF_LEOTHERAS, true);
                     break;
                 case EVENT_RESTORE_FIGHT:
                     me->SetStandState(UNIT_STAND_STATE_STAND);
                     me->SetReactState(REACT_AGGRESSIVE);
                     me->GetMotionMaster()->MoveChase(me->GetVictim());
                     break;
             }
             if (me->GetDisplayId() == me->GetNativeDisplayId())
                 DoMeleeAttackIfReady();
             else if (me->isAttackReady(BASE_ATTACK))
             {
                 me->CastSpell(me->GetVictim(), SPELL_CHAOS_BLAST, false);
                 me->setAttackTimer(BASE_ATTACK, 2000);
             }
         }
References BASE_ATTACK, Unit::CastCustomSpell(), Unit::CastSpell(), MotionMaster::Clear(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DoResetThreat(), EVENT_HEALTH_CHECK, EVENT_RESTORE_FIGHT, EVENT_SPELL_BERSERK, EVENT_SPELL_INSIDIOUS_WHISPER, EVENT_SPELL_WHIRLWIND, EVENT_SUMMON_DEMON, EVENT_SWITCH_TO_DEMON, EVENT_SWITCH_TO_ELF, Unit::GetDisplayId(), Unit::GetMotionMaster(), Unit::GetNativeDisplayId(), Unit::GetVictim(), Unit::HasUnitState(), Unit::HealthBelowPct(), Unit::isAttackReady(), Creature::LoadEquipment(), ScriptedAI::me, MotionMaster::MoveChase(), REACT_AGGRESSIVE, REACT_PASSIVE, Unit::RemoveAurasDueToSpell(), SAY_FINAL_FORM, SAY_INNER_DEMONS, SAY_SWITCH_TO_DEMON, Unit::setAttackTimer(), Creature::SetReactState(), Unit::SetStandState(), SPELL_BERSERK, SPELL_CHAOS_BLAST, SPELL_INSIDIOUS_WHISPER, SPELL_METAMORPHOSIS, SPELL_SUMMON_SHADOW_OF_LEOTHERAS, SPELL_WHIRLWIND, SPELLVALUE_MAX_TARGETS, Unit::StopMoving(), CreatureAI::Talk(), UNIT_STAND_STATE_KNEEL, UNIT_STAND_STATE_STAND, UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_leotheras_the_blind.cpp