Azerotcore-wotlk: Guild::EventLogEntry Class Reference
Guild::EventLogEntry Class Reference
Public Member Functions
EventLogEntry (uint32 guildId, ObjectGuid::LowType guid, GuildEventLogTypes eventType, ObjectGuid playerGuid1, ObjectGuid playerGuid2, uint8 newRank)
EventLogEntry (uint32 guildId, ObjectGuid::LowType guid, time_t timestamp, GuildEventLogTypes eventType, ObjectGuid playerGuid1, ObjectGuid playerGuid2, uint8 newRank)
~EventLogEntry () override
void SaveToDB (CharacterDatabaseTransaction trans) const override
void WritePacket (WorldPacket &data) const override
Public Member Functions inherited from Guild::LogEntry
LogEntry (uint32 guildId, ObjectGuid::LowType guid)
LogEntry (uint32 guildId, ObjectGuid::LowType guid, time_t timestamp)
virtual ~LogEntry ()
ObjectGuid::LowType GetGUID () const
uint64 GetTimestamp () const
Private Attributes
GuildEventLogTypes m_eventType
ObjectGuid m_playerGuid1
ObjectGuid m_playerGuid2
uint8 m_newRank
Additional Inherited Members
Protected Attributes inherited from Guild::LogEntry
uint32 m_guildId
ObjectGuid::LowType m_guid
uint64 m_timestamp
Detailed Description
Definition at line 408 of file Guild.h.
Constructor & Destructor Documentation
EventLogEntry() [1/2]
Guild::EventLogEntry::EventLogEntry (uint32 guildId, ObjectGuid::LowType guid, GuildEventLogTypes eventType, ObjectGuid playerGuid1, ObjectGuid playerGuid2, uint8 newRank) inline
Definition at line 411 of file Guild.h.
                                                                                                                                                            :
             LogEntry(guildId, guid), m_eventType(eventType), m_playerGuid1(playerGuid1), m_playerGuid2(playerGuid2), m_newRank(newRank) { }
EventLogEntry() [2/2]
Guild::EventLogEntry::EventLogEntry (uint32 guildId, ObjectGuid::LowType guid, time_t timestamp, GuildEventLogTypes eventType, ObjectGuid playerGuid1, ObjectGuid playerGuid2, uint8 newRank) inline
Definition at line 414 of file Guild.h.
                                                                                                                                                                              :
             LogEntry(guildId, guid, timestamp), m_eventType(eventType), m_playerGuid1(playerGuid1), m_playerGuid2(playerGuid2), m_newRank(newRank) { }
~EventLogEntry()
Guild::EventLogEntry::~EventLogEntry () inline override
Definition at line 417 of file Guild.h.
 { }
Member Function Documentation
SaveToDB()
void Guild::EventLogEntry::SaveToDB (CharacterDatabaseTransaction trans) const override virtual
Implements Guild::LogEntry.
Definition at line 178 of file Guild.cpp.
 {
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_GUILD_EVENTLOG);
     stmt->setUInt32(0, m_guildId);
     stmt->setUInt32(1, m_guid);
     CharacterDatabase.ExecuteOrAppend(trans, stmt);
     uint8 index = 0;
     stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_GUILD_EVENTLOG);
     stmt->setUInt32(  index, m_guildId);
     stmt->setUInt32(++index, m_guid);
     stmt->setUInt8 (++index, uint8(m_eventType));
     stmt->setUInt32(++index, m_playerGuid1.GetCounter());
     stmt->setUInt32(++index, m_playerGuid2.GetCounter());
     stmt->setUInt8 (++index, m_newRank);
     stmt->setUInt64(++index, m_timestamp);
     CharacterDatabase.ExecuteOrAppend(trans, stmt);
 }
References CHAR_DEL_GUILD_EVENTLOG, CHAR_INS_GUILD_EVENTLOG, CharacterDatabase, PreparedStatementBase::setUInt32(), PreparedStatementBase::setUInt64(), and PreparedStatementBase::setUInt8().
WritePacket()
void Guild::EventLogEntry::WritePacket (WorldPacket & data) const override virtual
Implements Guild::LogEntry.
Definition at line 197 of file Guild.cpp.
 {
     // Event type
     data << uint8(m_eventType);
     // Player 1
     data << m_playerGuid1;
     // Player 2 not for left/join guild events
     if (m_eventType != GUILD_EVENT_LOG_JOIN_GUILD && m_eventType != GUILD_EVENT_LOG_LEAVE_GUILD)
         data << m_playerGuid2;
     // New Rank - only for promote/demote guild events
     if (m_eventType == GUILD_EVENT_LOG_PROMOTE_PLAYER || m_eventType == GUILD_EVENT_LOG_DEMOTE_PLAYER)
         data << uint8(m_newRank);
     // Event timestamp
     data << uint32(::time(nullptr) - m_timestamp);
 }
References GUILD_EVENT_LOG_DEMOTE_PLAYER, GUILD_EVENT_LOG_JOIN_GUILD, GUILD_EVENT_LOG_LEAVE_GUILD, and GUILD_EVENT_LOG_PROMOTE_PLAYER.
Member Data Documentation
m_eventType
GuildEventLogTypes Guild::EventLogEntry::m_eventType private
Definition at line 423 of file Guild.h.
m_newRank
uint8 Guild::EventLogEntry::m_newRank private
Definition at line 426 of file Guild.h.
m_playerGuid1
ObjectGuid Guild::EventLogEntry::m_playerGuid1 private
Definition at line 424 of file Guild.h.
m_playerGuid2
ObjectGuid Guild::EventLogEntry::m_playerGuid2 private
Definition at line 425 of file Guild.h.
The documentation for this class was generated from the following files:
src/server/game/Guilds/Guild.h
src/server/game/Guilds/Guild.cpp