Azerotcore-wotlk: G3D::Queue< T > Class Template Reference
G3D::Queue< T > Class Template Reference
#include <Queue.h>
Public Member Functions
Queue ()
Queue (const Queue &other)
virtual ~Queue ()
void pushFront (const T &e)
void pushBack (const T &e)
void enqueue (const T &e)
T popBack ()
T popFront ()
T dequeue ()
void clear (bool freeStorage=true)
void fastClear ()
Queue & operator= (const Queue &other)
int size () const
int length () const
T & operator[] (int n)
const T & operator[] (int n) const
const T & last () const
T & last ()
bool empty () const
bool contains (const T &e) const
void deleteAll ()
Private Member Functions
void _copy (const Queue &other)
int index (int i) const
void repackAndRealloc (int newSize)
void reserveSpace ()
Private Attributes
T * data
int head
int num
int numAllocated
Detailed Description
template<class T>
class G3D::Queue< T >
Dynamic queue that uses a circular buffer for performance.
Faster than std::deque for objects with constructors.
Definition at line 44 of file Queue.h.
Constructor & Destructor Documentation
Queue() [1/2]
template<class T > G3D::Queue< T >::Queue () inline
Definition at line 144 of file Queue.h.
             :
       data(NULL),
       head(0),
       num(0),
       numAllocated(0) {
     }
Queue() [2/2]
template<class T > G3D::Queue< T >::Queue (const Queue< T > & other) inline
Copy constructor
Definition at line 155 of file Queue.h.
                               : data(NULL) {
        _copy(other);
     }
References G3D::Queue< T >::_copy().
~Queue()
template<class T > virtual G3D::Queue< T >::~Queue () inline virtual
Destructor does not delete() the objects if T is a pointer type (e.g. T = int*) instead, it deletes the pointers themselves and leaves the objects. Call deleteAll if you want to dealocate the objects referenced.
Definition at line 166 of file Queue.h.
                      {
         clear();
     }
References G3D::Queue< T >::clear().
Member Function Documentation
_copy()
template<class T > void G3D::Queue< T >::_copy (const Queue< T > & other) inline private
If a clear was needed, assumes it already occured
Definition at line 76 of file Queue.h.
{
         debugAssert(data == NULL);
         data = (T*)System::malloc(sizeof(T) * other.numAllocated);
         debugAssert(data);
         head = other.head;
         num = other.num;
         numAllocated = other.numAllocated;
         FIND_ENDS;
         for (int i = head; i < firstEnd; ++i) {
             new (data + i)T(other.data[i]);
         }
         for (int i = 0; i < secondEnd; ++i) {
             new (data + i)T(other.data[i]);
         }
     }
References G3D::Queue< T >::data, debugAssert, FIND_ENDS, G3D::Queue< T >::head, G3D::System::malloc(), NULL, G3D::Queue< T >::num, and G3D::Queue< T >::numAllocated.
Referenced by G3D::Queue< T >::operator=(), and G3D::Queue< T >::Queue().
clear()
template<class T > void G3D::Queue< T >::clear (bool freeStorage = true) inline
Removes all elements (invoking their destructors).
Parameters
freeStorage If false, the underlying array is not deallocated (allowing fast push in the future), however, the size of the Queue is reported as zero.
Definition at line 253 of file Queue.h.
{
        FIND_ENDS;
        // Invoke the destructors on the elements
        int i;
        for (i = head; i < firstEnd; ++i) {
            (data + i)->~T();
        }
        for (i = 0; i < secondEnd; ++i) {
            (data + i)->~T();
        }
        num = 0;
        head = 0;
        if (freeStorage) {
            numAllocated = 0;
            System::free(data);
            data = NULL;
        }
    }
References FIND_ENDS, G3D::System::free(), G3D::Queue< T >::head, NULL, G3D::Queue< T >::num, and G3D::Queue< T >::numAllocated.
Referenced by G3D::Queue< T >::deleteAll(), G3D::Queue< T >::fastClear(), G3D::Queue< T >::operator=(), and G3D::Queue< T >::~Queue().
contains()
template<class T > bool G3D::Queue< T >::contains (const T & e) const inline
Returns true if the given element is in the queue.
Definition at line 337 of file Queue.h.
{
         for (int i = 0; i < size(); ++i) {
             if ((*this)[i] == e) {
                 return true;
             }
         }
         return false;
     }
References G3D::Queue< T >::size().
deleteAll()
template<class T > void G3D::Queue< T >::deleteAll () inline
Calls delete on all objects[0...size-1] and sets the queue size to zero.
Definition at line 351 of file Queue.h.
                      {
         FIND_ENDS;
         int i;
         for (i = 0; i < secondEnd; ++i) {
             delete data[i];
         }
         for (i = head; i < firstEnd; ++i) {
             delete data[i];
         }
         clear();
     }
References G3D::Queue< T >::clear(), FIND_ENDS, and G3D::Queue< T >::head.
dequeue()
template<class T > T G3D::Queue< T >::dequeue () inline
popFront
Definition at line 241 of file Queue.h.
                       {
        return popFront();
    }
References G3D::Queue< T >::popFront().
empty()
template<class T > bool G3D::Queue< T >::empty () const inline
Definition at line 330 of file Queue.h.
{
         return size() == 0;
     }
References G3D::Queue< T >::size().
enqueue()
template<class T > void G3D::Queue< T >::enqueue (const T & e) inline
pushBack
Definition at line 205 of file Queue.h.
{
         pushBack(e);
     }
References G3D::Queue< T >::pushBack().
fastClear()
template<class T > void G3D::Queue< T >::fastClear () inline
Clear without freeing the underlying array.
Definition at line 277 of file Queue.h.
                     {
        clear(false);
    }
References G3D::Queue< T >::clear().
index()
template<class T > int G3D::Queue< T >::index (int i) const inline private
Computes a data array index from a queue position. The queue position may be negative.
Definition at line 100 of file Queue.h.
{
         return (head + i + numAllocated) % numAllocated;
     }
References G3D::Queue< T >::head, and G3D::Queue< T >::numAllocated.
Referenced by G3D::Queue< T >::operator[](), G3D::Queue< T >::popBack(), G3D::Queue< T >::pushBack(), and G3D::Queue< T >::pushFront().
last() [1/2]
template<class T > T& G3D::Queue< T >::last () inline
Definition at line 326 of file Queue.h.
                      {
         return (*this)[size() - 1];
     }
References G3D::Queue< T >::size().
last() [2/2]
template<class T > const T& G3D::Queue< T >::last () const inline
Returns the back element
Definition at line 322 of file Queue.h.
{
         return (*this)[size() - 1];
     }
References G3D::Queue< T >::size().
length()
template<class T > int G3D::Queue< T >::length () const inline
Number of elements in the queue.
Definition at line 300 of file Queue.h.
{
       return size();
    }
References G3D::Queue< T >::size().
operator=()
template<class T > Queue& G3D::Queue< T >::operator= (const Queue< T > & other) inline
Assignment operator.
Definition at line 284 of file Queue.h.
{
        clear();
        _copy(other);
        return *this;
    }
References G3D::Queue< T >::_copy(), and G3D::Queue< T >::clear().
operator[]() [1/2]
template<class T > T& G3D::Queue< T >::operator[] (int n) inline
Performs bounds checks in debug mode
Definition at line 307 of file Queue.h.
{
       debugAssert((n >= 0) && (n < num));
       return data[index(n)];
    }
References debugAssert, G3D::Queue< T >::index(), and G3D::Queue< T >::num.
operator[]() [2/2]
template<class T > const T& G3D::Queue< T >::operator[] (int n) const inline
Performs bounds checks in debug mode
Definition at line 315 of file Queue.h.
{
         debugAssert((n >= 0) && (n < num));
         return data[index(n)];
     }
References debugAssert, G3D::Queue< T >::index(), and G3D::Queue< T >::num.
popBack()
template<class T > T G3D::Queue< T >::popBack () inline
Remove the last element from the queue. The queue will never shrink in size. (A typical queue only uses popFront).
Definition at line 214 of file Queue.h.
{
         int tail = index(num - 1);
         T result(data[tail]);
         // Call the destructor
         (data + tail)->~T();
         --num;
         return result;
     }
References G3D::Queue< T >::index(), and G3D::Queue< T >::num.
popFront()
template<class T > T G3D::Queue< T >::popFront () inline
Remove the next element from the head of the queue. The queue will never shrink in size.
Definition at line 228 of file Queue.h.
{
         T result(data[head]);
         // Call the destructor
         (data + head)->~T();
         head = (head + 1) % numAllocated;
         --num;
         return result;
     }
References G3D::Queue< T >::head, G3D::Queue< T >::num, and G3D::Queue< T >::numAllocated.
Referenced by G3D::Queue< T >::dequeue().
pushBack()
template<class T > void G3D::Queue< T >::pushBack (const T & e) inline
Insert a new element at the end of the queue.
Definition at line 191 of file Queue.h.
{
         reserveSpace();
         // Get the index of 1+tail
         int i = index(num);
         // Initialize that element
         new (data + i)T(e);
         ++num;
     }
References G3D::Queue< T >::index(), G3D::Queue< T >::num, and G3D::Queue< T >::reserveSpace().
Referenced by G3D::Queue< T >::enqueue().
pushFront()
template<class T > void G3D::Queue< T >::pushFront (const T & e) inline
Insert a new element into the front of the queue (a traditional queue only uses pushBack).
Definition at line 174 of file Queue.h.
{
         reserveSpace();
         // Get the index of head-1
         int i = index(-1);
         // Call the constructor on the newly exposed element.
         new (data + i)T(e);
         // Reassign the head to point to this index
         head = i;
         ++num;
     }
References G3D::Queue< T >::head, G3D::Queue< T >::index(), G3D::Queue< T >::num, and G3D::Queue< T >::reserveSpace().
repackAndRealloc()
template<class T > void G3D::Queue< T >::repackAndRealloc (int newSize) inline private
Allocates newSize elements and repacks the array.
Definition at line 107 of file Queue.h.
{
         // TODO: shrink queue
         T* old = data;
         data = (T*)System::malloc(newSize * sizeof(T));
         debugAssert(data != NULL);
         FIND_ENDS;
         int j = 0;
         for (int i = head; i < firstEnd; ++i, ++j) {
             new (data + j)T(old[i]);
             (old + i)->~T();
         }
         for (int i = 0; i < secondEnd; ++i, ++j) {
             new (data + j)T(old[i]);
             (old + i)->~T();
         }
         head = 0;
         System::free(old);
         numAllocated = newSize;
     }
References G3D::Queue< T >::data, debugAssert, FIND_ENDS, G3D::System::free(), G3D::Queue< T >::head, G3D::System::malloc(), NULL, and G3D::Queue< T >::numAllocated.
Referenced by G3D::Queue< T >::reserveSpace().
reserveSpace()
template<class T > void G3D::Queue< T >::reserveSpace () inline private
Ensure that there is at least one element between the tail and head, wrapping around in the circular buffer.
Definition at line 136 of file Queue.h.
{
         if (num == numAllocated) {
             repackAndRealloc(numAllocated * 3 + 20);
         }
     }
References G3D::Queue< T >::num, G3D::Queue< T >::numAllocated, and G3D::Queue< T >::repackAndRealloc().
Referenced by G3D::Queue< T >::pushBack(), and G3D::Queue< T >::pushFront().
size()
template<class T > int G3D::Queue< T >::size () const inline
Number of elements in the queue.
Definition at line 293 of file Queue.h.
{
       return num;
    }
References G3D::Queue< T >::num.
Referenced by G3D::Queue< T >::contains(), G3D::Queue< T >::empty(), G3D::Queue< T >::last(), and G3D::Queue< T >::length().
Member Data Documentation
data
template<class T > T* G3D::Queue< T >::data private
Only num elements are initialized.
Definition at line 58 of file Queue.h.
Referenced by G3D::Queue< T >::_copy(), and G3D::Queue< T >::repackAndRealloc().
head
template<class T > int G3D::Queue< T >::head private
Index of the next element to be dequeue-d in data.
Definition at line 63 of file Queue.h.
Referenced by G3D::Queue< T >::_copy(), G3D::Queue< T >::clear(), G3D::Queue< T >::deleteAll(), G3D::Queue< T >::index(), G3D::Queue< T >::popFront(), G3D::Queue< T >::pushFront(), and G3D::Queue< T >::repackAndRealloc().
num
template<class T > int G3D::Queue< T >::num private
Number of elements (including head) that are visible and initialized.
Definition at line 68 of file Queue.h.
Referenced by G3D::Queue< T >::_copy(), G3D::Queue< T >::clear(), G3D::Queue< T >::operator[](), G3D::Queue< T >::popBack(), G3D::Queue< T >::popFront(), G3D::Queue< T >::pushBack(), G3D::Queue< T >::pushFront(), G3D::Queue< T >::reserveSpace(), and G3D::Queue< T >::size().
numAllocated
template<class T > int G3D::Queue< T >::numAllocated private
Size of data array in elements.
Definition at line 73 of file Queue.h.
Referenced by G3D::Queue< T >::_copy(), G3D::Queue< T >::clear(), G3D::Queue< T >::index(), G3D::Queue< T >::popFront(), G3D::Queue< T >::repackAndRealloc(), and G3D::Queue< T >::reserveSpace().
The documentation for this class was generated from the following file:
deps/g3dlite/include/G3D/Queue.h