Azerotcore-wotlk: Vehicle Class Reference
Vehicle Class Reference
#include <Vehicle.h>
Public Member Functions
void Install ()
void Uninstall ()
void Reset (bool evading=false)
void InstallAllAccessories (bool evading)
void ApplyAllImmunities ()
void InstallAccessory (uint32 entry, int8 seatId, bool minion, uint8 type, uint32 summonTime)
Unit * GetBase () const
May be called from scripts.
VehicleEntry const * GetVehicleInfo () const
uint32 GetCreatureEntry () const
bool HasEmptySeat (int8 seatId) const
Unit * GetPassenger (int8 seatId) const
int8 GetNextEmptySeat (int8 seatId, bool next) const
uint8 GetAvailableSeatCount () const
bool AddPassenger (Unit *passenger, int8 seatId=-1)
void EjectPassenger (Unit *passenger, Unit *controller)
void RemovePassenger (Unit *passenger)
void RelocatePassengers ()
void RemoveAllPassengers ()
void Dismiss ()
bool IsVehicleInUse ()
void TeleportVehicle (float x, float y, float z, float ang)
VehicleSeatEntry const * GetSeatForPassenger (Unit const *passenger)
SeatMap::iterator GetSeatIteratorForPassenger (Unit *passenger)
Public Attributes
SeatMap Seats
Protected Member Functions
Vehicle (Unit *unit, VehicleEntry const *vehInfo, uint32 creatureEntry)
~Vehicle () override
Protected Member Functions inherited from TransportBase
TransportBase ()=default
virtual ~TransportBase ()=default
Private Types
enum Status { STATUS_NONE , STATUS_INSTALLED , STATUS_UNINSTALLING }
Private Member Functions
void InitMovementInfoForBase ()
void CalculatePassengerPosition (float &x, float &y, float &z, float *o) const override
This method transforms supplied transport offsets into global coordinates.
void CalculatePassengerOffset (float &x, float &y, float &z, float *o) const override
This method transforms supplied global coordinates into local offsets.
Private Attributes
Unit * _me
VehicleEntry const * _vehicleInfo
uint32 _usableSeatNum
uint32 _creatureEntry
Status _status
Friends
bool Unit::CreateVehicleKit (uint32 id, uint32 creatureEntry)
void Unit::RemoveVehicleKit ()
Additional Inherited Members
Static Protected Member Functions inherited from TransportBase
static void CalculatePassengerPosition (float &x, float &y, float &z, float *o, float transX, float transY, float transZ, float transO)
static void CalculatePassengerOffset (float &x, float &y, float &z, float *o, float transX, float transY, float transZ, float transO)
Detailed Description
Definition at line 29 of file Vehicle.h.
Member Enumeration Documentation
Status
enum Vehicle::Status private
Enumerator
STATUS_NONE
STATUS_INSTALLED
STATUS_UNINSTALLING
Definition at line 69 of file Vehicle.h.
     {
         STATUS_NONE,
         STATUS_INSTALLED,
         STATUS_UNINSTALLING,
     };
Constructor & Destructor Documentation
Vehicle()
Vehicle::Vehicle (Unit * unit, VehicleEntry const * vehInfo, uint32 creatureEntry) protected
Definition at line 33 of file Vehicle.cpp.
                                                                               :
     _me(unit), _vehicleInfo(vehInfo), _usableSeatNum(0), _creatureEntry(creatureEntry), _status(STATUS_NONE)
 {
     for (uint32 i = 0; i < MAX_VEHICLE_SEATS; ++i)
     {
         if (uint32 seatId = _vehicleInfo->m_seatID[i])
             if (VehicleSeatEntry const* veSeat = sVehicleSeatStore.LookupEntry(seatId))
             {
                 Seats.insert(std::make_pair(i, VehicleSeat(veSeat)));
                 if (veSeat->CanEnterOrExit())
                     ++_usableSeatNum;
             }
     }
     // Ulduar demolisher
     if (vehInfo->m_ID == 338)
         ++_usableSeatNum;
     InitMovementInfoForBase();
 }
References _usableSeatNum, _vehicleInfo, InitMovementInfoForBase(), VehicleEntry::m_ID, VehicleEntry::m_seatID, MAX_VEHICLE_SEATS, and sVehicleSeatStore.
~Vehicle()
Vehicle::~Vehicle () override protected
@Uninstall must be called before this.
Definition at line 54 of file Vehicle.cpp.
 {
     ASSERT(_status == STATUS_UNINSTALLING);
     for (SeatMap::const_iterator itr = Seats.begin(); itr != Seats.end(); ++itr)
         if (itr->second.Passenger.Guid)
         {
             if (Unit* unit = ObjectAccessor::GetUnit(*_me, itr->second.Passenger.Guid))
             {
                 LOG_FATAL("vehicles", "ZOMG! ~Vehicle(), unit: %s, entry: %u, typeid: %u, this_entry: %u, this_typeid: %u!", unit->GetName().c_str(), unit->GetEntry(), unit->GetTypeId(), _me ? _me->GetEntry() : 0, _me ? _me->GetTypeId() : 0);
                 unit->_ExitVehicle();
             }
             else
                 LOG_FATAL("vehicles", "ZOMG! ~Vehicle(), unknown guid!");
         }
 }
References _me, _status, ASSERT, Object::GetEntry(), Object::GetTypeId(), ObjectAccessor::GetUnit(), LOG_FATAL, and STATUS_UNINSTALLING.
Member Function Documentation
AddPassenger()
bool Vehicle::AddPassenger (Unit * passenger, int8 seatId = -1)
@Prevent adding passengers when vehicle is uninstalling. (Bad script in OnUninstall/OnRemovePassenger/PassengerBoarded hook.)
Definition at line 307 of file Vehicle.cpp.
 {
     if (_status == STATUS_UNINSTALLING)
     {
         LOG_DEBUG("vehicles", "Passenger %s, attempting to board vehicle %s during uninstall! SeatId: %i",
             unit->GetGUID().ToString().c_str(), _me->GetGUID().ToString().c_str(), (int32)seatId);
         return false;
     }
     if (unit->GetVehicle() != this)
         return false;
     SeatMap::iterator seat;
     if (seatId < 0) // no specific seat requirement
     {
         for (seat = Seats.begin(); seat != Seats.end(); ++seat)
             if (seat->second.IsEmpty() && (seat->second.SeatInfo->CanEnterOrExit() || seat->second.SeatInfo->IsUsableByOverride()))
                 break;
         if (seat == Seats.end()) // no available seat
             return false;
     }
     else
     {
         seat = Seats.find(seatId);
         if (seat == Seats.end())
             return false;
         if (!seat->second.IsEmpty())
         {
             if (Unit* passenger = ObjectAccessor::GetUnit(*GetBase(), seat->second.Passenger.Guid))
                 passenger->ExitVehicle();
             seat->second.Passenger.Guid.Clear();
         }
         ASSERT(seat->second.IsEmpty());
     }
     LOG_DEBUG("vehicles", "Unit %s enter vehicle entry %u id %u (%s) seat %d",
         unit->GetName().c_str(), _me->GetEntry(), _vehicleInfo->m_ID, _me->GetGUID().ToString().c_str(), (int32)seat->first);
     seat->second.Passenger.Guid = unit->GetGUID();
     seat->second.Passenger.IsUnselectable = unit->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
     if (seat->second.SeatInfo->CanEnterOrExit())
     {
         ASSERT(_usableSeatNum);
         --_usableSeatNum;
         if (!_usableSeatNum)
         {
             if (_me->GetTypeId() == TYPEID_PLAYER)
                 _me->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_PLAYER_VEHICLE);
             else
                 _me->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_SPELLCLICK);
         }
     }
     if (!_me || !_me->IsInWorld() || _me->IsDuringRemoveFromWorld())
         return false;
     // Xinef: moved from unit.cpp, if aura passes seatId == -1 (choose automaticly) we wont get appropriate flags
     if (unit->GetTypeId() == TYPEID_PLAYER && !(seat->second.SeatInfo->m_flagsB & VEHICLE_SEAT_FLAG_B_KEEP_PET))
         unit->ToPlayer()->UnsummonPetTemporaryIfAny();
     if (seat->second.SeatInfo->m_flags & VEHICLE_SEAT_FLAG_PASSENGER_NOT_SELECTABLE)
         unit->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
     unit->AddUnitMovementFlag(MOVEMENTFLAG_ONTRANSPORT);
     VehicleSeatEntry const* veSeat = seat->second.SeatInfo;
     unit->m_movementInfo.transport.pos.Relocate(veSeat->m_attachmentOffsetX, veSeat->m_attachmentOffsetY, veSeat->m_attachmentOffsetZ);
     unit->m_movementInfo.transport.time = 0;
     unit->m_movementInfo.transport.seat = seat->first;
     unit->m_movementInfo.transport.guid = _me->GetGUID();
     // xinef: removed seat->first == 0 check...
     if (_me->GetTypeId() == TYPEID_UNIT
             && unit->GetTypeId() == TYPEID_PLAYER
             && seat->second.SeatInfo->m_flags & VEHICLE_SEAT_FLAG_CAN_CONTROL)
     {
         try
         {
             if (!_me->SetCharmedBy(unit, CHARM_TYPE_VEHICLE))
                 ABORT();
         }
         catch (...)
         {
             LOG_INFO("vehicles", "ZOMG! CRASH! Try-catch in Unit::SetCharmedBy()!");
             LOG_INFO("vehicles", "ZOMG! CRASH! Try-catch in Unit::SetCharmedBy(). not null: %u", _me ? 1 : 0);
             if (!_me)
                 return false;
             LOG_INFO("vehicles", "ZOMG! CRASH! Try-catch in Unit::SetCharmedBy(). Is: %u!", _me->IsInWorld());
             LOG_INFO("vehicles", "ZOMG! CRASH! Try-catch in Unit::SetCharmedBy(). Is2: %u!", _me->IsDuringRemoveFromWorld());
             LOG_INFO("vehicles", "ZOMG! CRASH! Try-catch in Unit::SetCharmedBy(). Unit %s!", _me->GetName().c_str());
             LOG_INFO("vehicles", "ZOMG! CRASH! Try-catch in Unit::SetCharmedBy(). typeid: %u!", _me->GetTypeId());
             LOG_INFO("vehicles", "ZOMG! CRASH! Try-catch in Unit::SetCharmedBy(). Unit %s, typeid: %u, in world: %u, duringremove: %u has wrong CharmType! Charmer %s, typeid: %u, in world: %u, duringremove: %u.", _me->GetName().c_str(), _me->GetTypeId(), _me->IsInWorld(), _me->IsDuringRemoveFromWorld(), unit->GetName().c_str(), unit->GetTypeId(), unit->IsInWorld(), unit->IsDuringRemoveFromWorld());
             return false;
         }
     }
     if (_me->IsInWorld())
     {
         unit->SendClearTarget();                                // SMSG_BREAK_TARGET
         unit->SetControlled(true, UNIT_STATE_ROOT);              // SMSG_FORCE_ROOT - In some cases we send SMSG_SPLINE_MOVE_ROOT here (for creatures)
         // also adds MOVEMENTFLAG_ROOT
         Movement::MoveSplineInit init(unit);
         init.DisableTransportPathTransformations();
         init.MoveTo(veSeat->m_attachmentOffsetX, veSeat->m_attachmentOffsetY, veSeat->m_attachmentOffsetZ);
         // Xinef: did not found anything unique in dbc, maybe missed something
         if (veSeat->m_ID == 3566 || veSeat->m_ID == 3567 || veSeat->m_ID == 3568 || veSeat->m_ID == 3570)
         {
             float x = veSeat->m_attachmentOffsetX, y = veSeat->m_attachmentOffsetY, z = veSeat->m_attachmentOffsetZ, o;
             CalculatePassengerPosition(x, y, z, &o);
             init.SetFacing(_me->GetAngle(x, y));
         }
         else
             init.SetFacing(0.0f);
         init.SetTransportEnter();
         init.Launch();
         if (_me->GetTypeId() == TYPEID_UNIT)
         {
             if (_me->ToCreature()->IsAIEnabled)
                 _me->ToCreature()->AI()->PassengerBoarded(unit, seat->first, true);
         }
     }
     if (GetBase()->GetTypeId() == TYPEID_UNIT)
         sScriptMgr->OnAddPassenger(this, unit, seatId);
     // Remove parachute on vehicle switch
     unit->RemoveAurasDueToSpell(VEHICLE_SPELL_PARACHUTE);
     return true;
 }
References _me, _status, _usableSeatNum, _vehicleInfo, ABORT, Unit::AddUnitMovementFlag(), Creature::AI(), ASSERT, CalculatePassengerPosition(), CHARM_TYPE_VEHICLE, Movement::MoveSplineInit::DisableTransportPathTransformations(), Position::GetAngle(), GetBase(), Object::GetEntry(), Object::GetGUID(), WorldObject::GetName(), Object::GetTypeId(), ObjectAccessor::GetUnit(), Unit::GetVehicle(), MovementInfo::TransportInfo::guid, Object::HasFlag(), Unit::IsAIEnabled, Unit::IsDuringRemoveFromWorld(), Object::IsInWorld(), Movement::MoveSplineInit::Launch(), LOG_DEBUG, LOG_INFO, VehicleSeatEntry::m_attachmentOffsetX, VehicleSeatEntry::m_attachmentOffsetY, VehicleSeatEntry::m_attachmentOffsetZ, VehicleEntry::m_ID, VehicleSeatEntry::m_ID, WorldObject::m_movementInfo, MOVEMENTFLAG_ONTRANSPORT, Movement::MoveSplineInit::MoveTo(), CreatureAI::PassengerBoarded(), MovementInfo::TransportInfo::pos, Position::Relocate(), Unit::RemoveAurasDueToSpell(), Object::RemoveFlag(), MovementInfo::TransportInfo::seat, Unit::SendClearTarget(), Unit::SetCharmedBy(), Unit::SetControlled(), Movement::MoveSplineInit::SetFacing(), Object::SetFlag(), Movement::MoveSplineInit::SetTransportEnter(), sScriptMgr, STATUS_UNINSTALLING, MovementInfo::TransportInfo::time, Object::ToCreature(), Object::ToPlayer(), ObjectGuid::ToString(), MovementInfo::transport, TYPEID_PLAYER, TYPEID_UNIT, UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE, UNIT_NPC_FLAG_PLAYER_VEHICLE, UNIT_NPC_FLAG_SPELLCLICK, UNIT_NPC_FLAGS, UNIT_STATE_ROOT, Player::UnsummonPetTemporaryIfAny(), VEHICLE_SEAT_FLAG_B_KEEP_PET, VEHICLE_SEAT_FLAG_CAN_CONTROL, VEHICLE_SEAT_FLAG_PASSENGER_NOT_SELECTABLE, VEHICLE_SPELL_PARACHUTE, G3D::x, G3D::y, and G3D::z.
Referenced by Unit::_EnterVehicle(), and Unit::ChangeSeat().
ApplyAllImmunities()
void Vehicle::ApplyAllImmunities ()
Definition at line 138 of file Vehicle.cpp.
 {
     // This couldn't be done in DB, because some spells have MECHANIC_NONE
     // Vehicles should be immune on Knockback ...
     //_me->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_KNOCK_BACK, true);
     //_me->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_KNOCK_BACK_DEST, true);
     // Mechanical units & vehicles ( which are not Bosses, they have own immunities in DB ) should be also immune on healing ( exceptions in switch below )
     if (_me->ToCreature() && _me->ToCreature()->GetCreatureTemplate()->type == CREATURE_TYPE_MECHANICAL && !_me->ToCreature()->isWorldBoss())
     {
         // Heal & dispel ...
         _me->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_HEAL, true);
         _me->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_HEAL_PCT, true);
         _me->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_HEAL_MAX_HEALTH, true); // Xinef
         _me->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_DISPEL, true);
         _me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_PERIODIC_HEAL, true);
         // ... Shield & Immunity grant spells ...
         _me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_SCHOOL_IMMUNITY, true);
         //_me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_UNATTACKABLE, true);
         _me->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_SHIELD, true);
         _me->ApplySpellImmune(0, IMMUNITY_MECHANIC, MECHANIC_IMMUNE_SHIELD, true);
         if (_me->GetZoneId() == BATTLEFIELD_WG_ZONEID || _me->ToCreature()->GetSpawnId() || (_me->FindMap() && _me->FindMap()->Instanceable()))
             _me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_SCHOOL_ABSORB, true);
         // ... Resistance, Split damage, Change stats ...
         _me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_DAMAGE_SHIELD, true);
         _me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_SPLIT_DAMAGE_PCT, true);
         _me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_RESISTANCE, true);
         _me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_STAT, true);
         // Taunt
         _me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_TAUNT, true);
         _me->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_ATTACK_ME, true);
     }
     // Different immunities for vehicles goes below
     switch (GetVehicleInfo()->m_ID)
     {
         case 160: //Isle of conquest turret
         case 244: //Wintergrasp turret
         case 510: // Isle of Conquest
         case 452: // Isle of Conquest
         case 543: // Isle of Conquest
             //_me->SetControlled(true, UNIT_STATE_ROOT);
             //me->AddUnitMovementFlag(MOVEMENTFLAG_ROOT);
             //me->SetSpeed(MOVE_TURN_RATE, 0.7f);
             //me->SetSpeed(MOVE_PITCH_RATE, 0.7f);
             //me->m_movementInfo.flags2=59;
             _me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_DECREASE_SPEED, true);
             break;
         // Ulduar vehicles, remove immunities used in flame leviathan spells
         case 335:
         case 336:
         case 338:
             _me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN, false);
             _me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_SCHOOL_ABSORB, false);
             break;
         default:
             break;
     }
 }
References _me, Unit::ApplySpellImmune(), BATTLEFIELD_WG_ZONEID, CREATURE_TYPE_MECHANICAL, WorldObject::FindMap(), Creature::GetCreatureTemplate(), Creature::GetSpawnId(), GetVehicleInfo(), WorldObject::GetZoneId(), IMMUNITY_EFFECT, IMMUNITY_MECHANIC, IMMUNITY_STATE, Map::Instanceable(), Creature::isWorldBoss(), MECHANIC_IMMUNE_SHIELD, MECHANIC_SHIELD, SPELL_AURA_DAMAGE_SHIELD, SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN, SPELL_AURA_MOD_DECREASE_SPEED, SPELL_AURA_MOD_RESISTANCE, SPELL_AURA_MOD_STAT, SPELL_AURA_MOD_TAUNT, SPELL_AURA_PERIODIC_HEAL, SPELL_AURA_SCHOOL_ABSORB, SPELL_AURA_SCHOOL_IMMUNITY, SPELL_AURA_SPLIT_DAMAGE_PCT, SPELL_EFFECT_ATTACK_ME, SPELL_EFFECT_DISPEL, SPELL_EFFECT_HEAL, SPELL_EFFECT_HEAL_MAX_HEALTH, SPELL_EFFECT_HEAL_PCT, Object::ToCreature(), and CreatureTemplate::type.
Referenced by Reset().
CalculatePassengerOffset()
void Vehicle::CalculatePassengerOffset (float & x, float & y, float & z, float * o) const inline override private virtual
This method transforms supplied global coordinates into local offsets.
Implements TransportBase.
Definition at line 87 of file Vehicle.h.
     {
         TransportBase::CalculatePassengerOffset(x, y, z, o,
                                                 GetBase()->GetPositionX(), GetBase()->GetPositionY(),
                                                 GetBase()->GetPositionZ(), GetBase()->GetOrientation());
     }
References TransportBase::CalculatePassengerOffset(), GetBase(), G3D::x, G3D::y, and G3D::z.
CalculatePassengerPosition()
void Vehicle::CalculatePassengerPosition (float & x, float & y, float & z, float * o) const inline override private virtual
This method transforms supplied transport offsets into global coordinates.
Implements TransportBase.
Definition at line 79 of file Vehicle.h.
     {
         TransportBase::CalculatePassengerPosition(x, y, z, o,
                 GetBase()->GetPositionX(), GetBase()->GetPositionY(),
                 GetBase()->GetPositionZ(), GetBase()->GetOrientation());
     }
References TransportBase::CalculatePassengerPosition(), GetBase(), G3D::x, G3D::y, and G3D::z.
Referenced by AddPassenger(), and RelocatePassengers().
Dismiss()
void Vehicle::Dismiss ()
Definition at line 523 of file Vehicle.cpp.
 {
     if (GetBase()->GetTypeId() != TYPEID_UNIT)
         return;
     LOG_DEBUG("vehicles", "Vehicle::Dismiss %s", _me->GetGUID().ToString().c_str());
     Uninstall();
     GetBase()->ToCreature()->DespawnOrUnsummon();
 }
References _me, Creature::DespawnOrUnsummon(), GetBase(), Object::GetGUID(), LOG_DEBUG, Object::ToCreature(), ObjectGuid::ToString(), TYPEID_UNIT, and Uninstall().
Referenced by Unit::_ExitVehicle(), BattlefieldWG::OnPlayerLeaveWar(), and Player::UpdateAreaDependentAuras().
EjectPassenger()
void Vehicle::EjectPassenger (Unit * passenger, Unit * controller)
GetAvailableSeatCount()
uint8 Vehicle::GetAvailableSeatCount () const
Definition at line 602 of file Vehicle.cpp.
 {
     uint8 ret = 0;
     SeatMap::const_iterator itr;
     for (itr = Seats.begin(); itr != Seats.end(); ++itr)
         if (itr->second.IsEmpty() && (itr->second.SeatInfo->CanEnterOrExit() || itr->second.SeatInfo->IsUsableByOverride()))
             ++ret;
     return ret;
 }
References ret.
Referenced by Aura::CanStackWith(), and npc_brunnhildar_prisoner::npc_brunnhildar_prisonerAI::SpellHit().
GetBase()
Unit* Vehicle::GetBase () const inline
May be called from scripts.
Definition at line 39 of file Vehicle.h.
 { return _me; }
References _me.
Referenced by Unit::_EnterVehicle(), Unit::_ExitVehicle(), Creature::_IsTargetAcceptable(), Unit::_IsValidAssistTarget(), Unit::_IsValidAttackTarget(), AddPassenger(), Unit::BuildMovementPacket(), CalculatePassengerOffset(), CalculatePassengerPosition(), Dismiss(), GetPassenger(), SmartScript::GetTargets(), ObjectMgr::GetVehicleAccessoryList(), Unit::GetVehicleBase(), WorldSession::HandleEjectPassenger(), spell_auto_repair::spell_auto_repair_SpellScript::HandleScript(), Install(), InstallAccessory(), InstallAllAccessories(), npc_tiger_matriarch::npc_tiger_matriarchAI::IsSummonedBy(), IsVehicleInUse(), ScriptMgr::OnAddPassenger(), ScriptMgr::OnInstall(), ScriptMgr::OnInstallAccessory(), ScriptMgr::OnRemovePassenger(), ScriptMgr::OnReset(), ScriptMgr::OnUninstall(), RelocatePassengers(), RemovePassenger(), Reset(), TeleportVehicle(), and Uninstall().
GetCreatureEntry()
uint32 Vehicle::GetCreatureEntry () const inline
Definition at line 41 of file Vehicle.h.
 { return _creatureEntry; }
References _creatureEntry.
Referenced by ObjectMgr::GetVehicleAccessoryList(), Unit::HandleSpellClick(), and InstallAccessory().
GetNextEmptySeat()
int8 Vehicle::GetNextEmptySeat (int8 seatId, bool next) const
Definition at line 235 of file Vehicle.cpp.
 {
     SeatMap::const_iterator seat = Seats.find(seatId);
     if (seat == Seats.end())
         return -1;
     while (!seat->second.IsEmpty() || (!seat->second.SeatInfo->CanEnterOrExit() && !seat->second.SeatInfo->IsUsableByOverride()))
     {
         if (next)
         {
             ++seat;
             if (seat == Seats.end())
                 seat = Seats.begin();
         }
         else
         {
             if (seat == Seats.begin())
                 seat = Seats.end();
             --seat;
         }
         if (seat->first == seatId)
             return -1; // no available seat
     }
     return seat->first;
 }
References next().
Referenced by Unit::ChangeSeat().
GetPassenger()
Unit * Vehicle::GetPassenger (int8 seatId) const
Definition at line 226 of file Vehicle.cpp.
 {
     SeatMap::const_iterator seat = Seats.find(seatId);
     if (seat == Seats.end())
         return nullptr;
     return ObjectAccessor::GetUnit(*GetBase(), seat->second.Passenger.Guid);
 }
References GetBase(), and ObjectAccessor::GetUnit().
Referenced by boss_xt002::boss_xt002AI::AttachHeart(), Aura::CanStackWith(), spell_demolisher_ride_vehicle::spell_demolisher_ride_vehicle_SpellScript::CheckCast(), npc_orb_carrier::npc_orb_carrierAI::DoAction(), boss_skadi_grauf::boss_skadi_graufAI::DoAction(), SmartScript::GetTargets(), spell_switch_infragreen_bomber_station::spell_switch_infragreen_bomber_station_SpellScript::HandleDummy(), spell_q13280_13283_plant_battle_standard::HandleDummy(), spell_auto_repair::spell_auto_repair_SpellScript::HandleScript(), spell_q12919_gymers_throw::HandleScript(), InstallAccessory(), boss_flame_leviathan_overload_device::boss_flame_leviathan_overload_deviceAI::OnSpellClick(), boss_flame_leviathan_seat::boss_flame_leviathan_seatAI::PassengerBoarded(), spell_fight_fire_bomber::spell_fight_fire_bomber_SpellScript::PrepareSpellScript(), boss_skadi_grauf::boss_skadi_graufAI::RemoveSkadi(), Spell::SelectImplicitCasterObjectTargets(), npc_vics_flying_machine::npc_vics_flying_machineAI::SpellHit(), npc_infra_green_bomber_generic::npc_infra_green_bomber_genericAI::SpreadFire(), npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::UpdateAI(), npc_vortex_ride::npc_vortex_rideAI::UpdateAI(), npc_oculus_drake::npc_oculus_drakeAI::UpdateAI(), boss_flame_leviathan::boss_flame_leviathanAI::UpdateAI(), boss_xt002::boss_xt002AI::UpdateAI(), npc_q24545_lich_king::npc_q24545_lich_kingAI::UpdateAI(), and npc_freed_protodrake::npc_freed_protodrakeAI::UpdateAI().
GetSeatForPassenger()
VehicleSeatEntry const * Vehicle::GetSeatForPassenger (Unit const * passenger)
Definition at line 582 of file Vehicle.cpp.
 {
     SeatMap::iterator itr;
     for (itr = Seats.begin(); itr != Seats.end(); ++itr)
         if (itr->second.Passenger.Guid == passenger->GetGUID())
             return itr->second.SeatInfo;
     return nullptr;
 }
References Object::GetGUID().
Referenced by Spell::CheckCast(), WorldSession::HandleChangeSeatsOnControlledVehicle(), WorldSession::HandleEjectPassenger(), and Player::ProcessTerrainStatusUpdate().
GetSeatIteratorForPassenger()
SeatMap::iterator Vehicle::GetSeatIteratorForPassenger (Unit * passenger)
Definition at line 592 of file Vehicle.cpp.
 {
     SeatMap::iterator itr;
     for (itr = Seats.begin(); itr != Seats.end(); ++itr)
         if (itr->second.Passenger.Guid == passenger->GetGUID())
             return itr;
     return Seats.end();
 }
References Object::GetGUID().
Referenced by spell_switch_infragreen_bomber_station::spell_switch_infragreen_bomber_station_SpellScript::HandleDummy(), and RemovePassenger().
GetVehicleInfo()
VehicleEntry const* Vehicle::GetVehicleInfo () const inline
Definition at line 40 of file Vehicle.h.
 { return _vehicleInfo; }
References _vehicleInfo.
Referenced by Unit::_ExitVehicle(), ApplyAllImmunities(), Object::BuildMovementUpdate(), instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::CheckAchievementCriteriaMeet(), WorldSession::HandleRequestPartyMemberStatsOpcode(), and InitMovementInfoForBase().
HasEmptySeat()
bool Vehicle::HasEmptySeat (int8 seatId) const
Definition at line 218 of file Vehicle.cpp.
 {
     SeatMap::const_iterator seat = Seats.find(seatId);
     if (seat == Seats.end())
         return false;
     return seat->second.IsEmpty();
 }
Referenced by Unit::ChangeSeat().
InitMovementInfoForBase()
void Vehicle::InitMovementInfoForBase () private
Definition at line 566 of file Vehicle.cpp.
 {
     uint32 vehicleFlags = GetVehicleInfo()->m_flags;
     if (vehicleFlags & VEHICLE_FLAG_NO_STRAFE)
         _me->AddExtraUnitMovementFlag(MOVEMENTFLAG2_NO_STRAFE);
     if (vehicleFlags & VEHICLE_FLAG_NO_JUMPING)
         _me->AddExtraUnitMovementFlag(MOVEMENTFLAG2_NO_JUMPING);
     if (vehicleFlags & VEHICLE_FLAG_FULLSPEEDTURNING)
         _me->AddExtraUnitMovementFlag(MOVEMENTFLAG2_FULL_SPEED_TURNING);
     if (vehicleFlags & VEHICLE_FLAG_ALLOW_PITCHING)
         _me->AddExtraUnitMovementFlag(MOVEMENTFLAG2_ALWAYS_ALLOW_PITCHING);
     if (vehicleFlags & VEHICLE_FLAG_FULLSPEEDPITCHING)
         _me->AddExtraUnitMovementFlag(MOVEMENTFLAG2_FULL_SPEED_PITCHING);
 }
References _me, Unit::AddExtraUnitMovementFlag(), GetVehicleInfo(), VehicleEntry::m_flags, MOVEMENTFLAG2_ALWAYS_ALLOW_PITCHING, MOVEMENTFLAG2_FULL_SPEED_PITCHING, MOVEMENTFLAG2_FULL_SPEED_TURNING, MOVEMENTFLAG2_NO_JUMPING, MOVEMENTFLAG2_NO_STRAFE, VEHICLE_FLAG_ALLOW_PITCHING, VEHICLE_FLAG_FULLSPEEDPITCHING, VEHICLE_FLAG_FULLSPEEDTURNING, VEHICLE_FLAG_NO_JUMPING, and VEHICLE_FLAG_NO_STRAFE.
Referenced by Vehicle().
Install()
void Vehicle::Install ()
Definition at line 72 of file Vehicle.cpp.
 {
     if (_me->GetTypeId() == TYPEID_UNIT)
     {
         if (PowerDisplayEntry const* powerDisplay = sPowerDisplayStore.LookupEntry(_vehicleInfo->m_powerDisplayId))
             _me->setPowerType(Powers(powerDisplay->PowerType));
         else if (_me->getClass() == CLASS_ROGUE)
             _me->setPowerType(POWER_ENERGY);
     }
     _status = STATUS_INSTALLED;
     if (GetBase()->GetTypeId() == TYPEID_UNIT)
         sScriptMgr->OnInstall(this);
 }
References _me, _status, _vehicleInfo, CLASS_ROGUE, GetBase(), Unit::getClass(), Object::GetTypeId(), VehicleEntry::m_powerDisplayId, POWER_ENERGY, Unit::setPowerType(), sPowerDisplayStore, sScriptMgr, STATUS_INSTALLED, and TYPEID_UNIT.
Referenced by Creature::AddToWorld().
InstallAccessory()
void Vehicle::InstallAccessory (uint32 entry, int8 seatId, bool minion, uint8 type, uint32 summonTime)
@Prevent adding accessories when vehicle is uninstalling. (Bad script in OnUninstall/OnRemovePassenger/PassengerBoarded hook.)
Definition at line 263 of file Vehicle.cpp.
 {
     if (_status == STATUS_UNINSTALLING)
     {
         LOG_ERROR("vehicles", "Vehicle %s attempts to install accessory Entry: %u on seat %d with STATUS_UNINSTALLING! "
                        "Check Uninstall/PassengerBoarded script hooks for errors.", _me->GetGUID().ToString().c_str(), entry, (int32)seatId);
         return;
     }
     LOG_DEBUG("vehicles", "Vehicle: Installing accessory entry %u on vehicle entry %u (seat:%i)", entry, GetCreatureEntry(), seatId);
     if (Unit* passenger = GetPassenger(seatId))
     {
         // already installed
         if (passenger->GetEntry() == entry)
         {
             ASSERT(passenger->GetTypeId() == TYPEID_UNIT);
             if (_me->GetTypeId() == TYPEID_UNIT)
             {
                 if (_me->ToCreature()->IsInEvadeMode() && passenger->ToCreature()->IsAIEnabled)
                     passenger->ToCreature()->AI()->EnterEvadeMode();
                 return;
             }
         }
         else
             passenger->ExitVehicle(); // this should not happen
     }
     if (TempSummon* accessory = _me->SummonCreature(entry, *_me, TempSummonType(type), summonTime))
     {
         if (minion)
             accessory->AddUnitTypeMask(UNIT_MASK_ACCESSORY);
         if (!_me->HandleSpellClick(accessory, seatId))
         {
             accessory->UnSummon();
             return;
         }
         if (GetBase()->GetTypeId() == TYPEID_UNIT)
             sScriptMgr->OnInstallAccessory(this, accessory);
     }
 }
References _me, _status, ASSERT, GetBase(), GetCreatureEntry(), Object::GetGUID(), GetPassenger(), Object::GetTypeId(), Unit::HandleSpellClick(), Creature::IsInEvadeMode(), LOG_DEBUG, LOG_ERROR, sScriptMgr, STATUS_UNINSTALLING, WorldObject::SummonCreature(), Object::ToCreature(), ObjectGuid::ToString(), TYPEID_UNIT, and UNIT_MASK_ACCESSORY.
Referenced by InstallAllAccessories().
InstallAllAccessories()
void Vehicle::InstallAllAccessories (bool evading)
Definition at line 87 of file Vehicle.cpp.
 {
     if (GetBase()->GetTypeId() == TYPEID_PLAYER || !evading)
         RemoveAllPassengers();   // We might have aura's saved in the DB with now invalid casters - remove
     VehicleAccessoryList const* accessories = sObjectMgr->GetVehicleAccessoryList(this);
     if (!accessories)
         return;
     for (VehicleAccessoryList::const_iterator itr = accessories->begin(); itr != accessories->end(); ++itr)
         if (!evading || itr->IsMinion)  // only install minions on evade mode
             InstallAccessory(itr->AccessoryEntry, itr->SeatId, itr->IsMinion, itr->SummonedType, itr->SummonTime);
 }
References GetBase(), InstallAccessory(), RemoveAllPassengers(), sObjectMgr, and TYPEID_PLAYER.
Referenced by boss_flame_leviathan_seat::boss_flame_leviathan_seatAI::EnterEvadeMode(), Unit::Mount(), Reset(), and npc_hyldsmeet_protodrake::npc_hyldsmeet_protodrakeAI::UpdateAI().
IsVehicleInUse()
bool Vehicle::IsVehicleInUse ()
Definition at line 533 of file Vehicle.cpp.
 {
     for (SeatMap::const_iterator itr = Seats.begin(); itr != Seats.end(); ++itr)
         if (Unit* passenger = ObjectAccessor::GetUnit(*GetBase(), itr->second.Passenger.Guid))
         {
             if (passenger->GetTypeId() == TYPEID_PLAYER)
                 return true;
             else if (passenger->GetTypeId() == TYPEID_UNIT && passenger->GetVehicleKit() && passenger->GetVehicleKit()->IsVehicleInUse())
                 return true;
         }
     return false;
 }
References GetBase(), ObjectAccessor::GetUnit(), TYPEID_PLAYER, and TYPEID_UNIT.
Referenced by VehicleAI::OnCharmed().
RelocatePassengers()
void Vehicle::RelocatePassengers ()
Definition at line 498 of file Vehicle.cpp.
 {
     ASSERT(_me->GetMap());
     std::vector<std::pair<Unit*, Position>> seatRelocation;
     seatRelocation.reserve(Seats.size());
     // not sure that absolute position calculation is correct, it must depend on vehicle pitch angle
     for (auto const& itr : Seats)
     {
         if (Unit* passenger = ObjectAccessor::GetUnit(*GetBase(), itr.second.Passenger.Guid))
         {
             ASSERT(passenger->IsInWorld());
             float px, py, pz, po;
             passenger->m_movementInfo.transport.pos.GetPosition(px, py, pz, po);
             CalculatePassengerPosition(px, py, pz, &po);
             seatRelocation.emplace_back(passenger, Position(px, py, pz, po));
         }
     }
     for (auto const& pair : seatRelocation)
         pair.first->UpdatePosition(pair.second);
 }
References _me, ASSERT, CalculatePassengerPosition(), GetBase(), WorldObject::GetMap(), and ObjectAccessor::GetUnit().
Referenced by Map::CreatureRelocation(), Map::PlayerRelocation(), Unit::UpdateHeight(), and Unit::UpdateOrientation().
RemoveAllPassengers()
void Vehicle::RemoveAllPassengers ()
Definition at line 202 of file Vehicle.cpp.
 {
     LOG_DEBUG("vehicles", "Vehicle::RemoveAllPassengers. %s", _me->GetGUID().ToString().c_str());
     // Passengers always cast an aura with SPELL_AURA_CONTROL_VEHICLE on the vehicle
     // We just remove the aura and the unapply handler will make the target leave the vehicle.
     // We don't need to iterate over Seats
     _me->RemoveAurasByType(SPELL_AURA_CONTROL_VEHICLE);
     // Following the above logic, this assertion should NEVER fail.
     // Even in 'hacky' cases, there should at least be VEHICLE_SPELL_RIDE_HARDCODED on us.
     // SeatMap::const_iterator itr;
     // for (itr = Seats.begin(); itr != Seats.end(); ++itr)
     //    ASSERT(!itr->second.passenger.Guid);
 }
References _me, Object::GetGUID(), LOG_DEBUG, Unit::RemoveAurasByType(), SPELL_AURA_CONTROL_VEHICLE, and ObjectGuid::ToString().
Referenced by InstallAllAccessories(), and Uninstall().
RemovePassenger()
void Vehicle::RemovePassenger (Unit * passenger)
Definition at line 444 of file Vehicle.cpp.
 {
     if (unit->GetVehicle() != this)
         return;
     SeatMap::iterator seat = GetSeatIteratorForPassenger(unit);
     // it can happen that unit enters vehicle and removes owner passenger
     // then vehicles is dissmised and removes all existing passengers, even the unit (vehicle has aura of unit)
     // but the unit is not on the vehicles seat yet, thus crashing at ASSERT(seat != Seats.end());
     // ASSERT(seat != Seats.end());
     if (seat == Seats.end())
     {
         LOG_ERROR("vehicles", "Vehicle::RemovePassenger: Vehicle entry (%u) id (%u) is dissmised and removed all existing passangers, but the unit (%s) was not on the vehicle!",
             _me->GetEntry(), _vehicleInfo->m_ID, unit->GetName().c_str());
         return;
     }
     LOG_DEBUG("vehicles", "Unit %s exit vehicle entry %u id %u (%s) seat %d",
         unit->GetName().c_str(), _me->GetEntry(), _vehicleInfo->m_ID, _me->GetGUID().ToString().c_str(), (int32)seat->first);
     if (seat->second.SeatInfo->CanEnterOrExit() && ++_usableSeatNum)
         _me->SetFlag(UNIT_NPC_FLAGS, (_me->GetTypeId() == TYPEID_PLAYER ? UNIT_NPC_FLAG_PLAYER_VEHICLE : UNIT_NPC_FLAG_SPELLCLICK));
     // Remove UNIT_FLAG_NOT_SELECTABLE if passenger did not have it before entering vehicle
     if (seat->second.SeatInfo->m_flags & VEHICLE_SEAT_FLAG_PASSENGER_NOT_SELECTABLE && !seat->second.Passenger.IsUnselectable)
         unit->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
     seat->second.Passenger.Reset();
     if (_me->GetTypeId() == TYPEID_UNIT && unit->GetTypeId() == TYPEID_PLAYER && seat->second.SeatInfo->m_flags & VEHICLE_SEAT_FLAG_CAN_CONTROL)
         _me->RemoveCharmedBy(unit);
     if (_me->IsInWorld())
     {
         if (!_me->GetTransport())
         {
             unit->RemoveUnitMovementFlag(MOVEMENTFLAG_ONTRANSPORT);
             unit->m_movementInfo.transport.Reset();
         }
         else
             unit->m_movementInfo.transport = _me->m_movementInfo.transport;
     }
     // only for flyable vehicles
     if (_me->IsFlying() && !_me->GetInstanceId() && unit->GetTypeId() == TYPEID_PLAYER && !(unit->ToPlayer()->GetDelayedOperations() & DELAYED_VEHICLE_TELEPORT) && _me->GetEntry() != 30275 /*NPC_WILD_WYRM*/)
         _me->CastSpell(unit, VEHICLE_SPELL_PARACHUTE, true);
     if (_me->GetTypeId() == TYPEID_UNIT && _me->ToCreature()->IsAIEnabled)
         _me->ToCreature()->AI()->PassengerBoarded(unit, seat->first, false);
     if (GetBase()->GetTypeId() == TYPEID_UNIT)
         sScriptMgr->OnRemovePassenger(this, unit);
 }
References _me, _usableSeatNum, _vehicleInfo, Creature::AI(), Unit::CastSpell(), DELAYED_VEHICLE_TELEPORT, GetBase(), Player::GetDelayedOperations(), Object::GetEntry(), Object::GetGUID(), WorldObject::GetInstanceId(), WorldObject::GetName(), GetSeatIteratorForPassenger(), WorldObject::GetTransport(), Object::GetTypeId(), Unit::GetVehicle(), Unit::IsAIEnabled, Unit::IsFlying(), Object::IsInWorld(), LOG_DEBUG, LOG_ERROR, VehicleEntry::m_ID, WorldObject::m_movementInfo, MOVEMENTFLAG_ONTRANSPORT, CreatureAI::PassengerBoarded(), Unit::RemoveCharmedBy(), Object::RemoveFlag(), Unit::RemoveUnitMovementFlag(), MovementInfo::TransportInfo::Reset(), Object::SetFlag(), sScriptMgr, Object::ToCreature(), Object::ToPlayer(), ObjectGuid::ToString(), MovementInfo::transport, TYPEID_PLAYER, TYPEID_UNIT, UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE, UNIT_NPC_FLAG_PLAYER_VEHICLE, UNIT_NPC_FLAG_SPELLCLICK, UNIT_NPC_FLAGS, VEHICLE_SEAT_FLAG_CAN_CONTROL, VEHICLE_SEAT_FLAG_PASSENGER_NOT_SELECTABLE, and VEHICLE_SPELL_PARACHUTE.
Referenced by Unit::_ExitVehicle(), and Unit::ChangeSeat().
Reset()
void Vehicle::Reset (bool evading = false)
Definition at line 118 of file Vehicle.cpp.
 {
     LOG_DEBUG("vehicles", "Vehicle::Reset: %s", _me->GetGUID().ToString().c_str());
     if (_me->GetTypeId() == TYPEID_PLAYER)
     {
         if (_usableSeatNum)
             _me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_PLAYER_VEHICLE);
     }
     else
     {
         ApplyAllImmunities();
         InstallAllAccessories(evading);
         if (_usableSeatNum)
             _me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_SPELLCLICK);
     }
     if (GetBase()->GetTypeId() == TYPEID_UNIT)
         sScriptMgr->OnReset(this);
 }
References _me, _usableSeatNum, ApplyAllImmunities(), GetBase(), Object::GetGUID(), Object::GetTypeId(), InstallAllAccessories(), LOG_DEBUG, Object::SetFlag(), sScriptMgr, ObjectGuid::ToString(), TYPEID_PLAYER, TYPEID_UNIT, UNIT_NPC_FLAG_PLAYER_VEHICLE, UNIT_NPC_FLAG_SPELLCLICK, and UNIT_NPC_FLAGS.
Referenced by Creature::AIM_Initialize(), CreatureAI::EnterEvadeMode(), Unit::Mount(), Creature::RespawnOnEvade(), and Creature::Update().
TeleportVehicle()
void Vehicle::TeleportVehicle (float x, float y, float z, float ang)
Definition at line 547 of file Vehicle.cpp.
 {
     _me->GetMap()->LoadGrid(x, y);
     _me->NearTeleportTo(x, y, z, ang, true);
     for (SeatMap::const_iterator itr = Seats.begin(); itr != Seats.end(); ++itr)
         if (Unit* passenger = ObjectAccessor::GetUnit(*GetBase(), itr->second.Passenger.Guid))
         {
             if (passenger->GetTypeId() == TYPEID_PLAYER)
             {
                 passenger->ToPlayer()->SetMover(passenger);
                 passenger->NearTeleportTo(x, y, z, ang, false, true);
                 passenger->ToPlayer()->ScheduleDelayedOperation(DELAYED_VEHICLE_TELEPORT);
             }
             else if (passenger->GetTypeId() == TYPEID_UNIT && passenger->GetVehicleKit())
                 passenger->GetVehicleKit()->TeleportVehicle(x, y, z, ang);
         }
 }
References _me, DELAYED_VEHICLE_TELEPORT, GetBase(), WorldObject::GetMap(), ObjectAccessor::GetUnit(), Map::LoadGrid(), Unit::NearTeleportTo(), TYPEID_PLAYER, TYPEID_UNIT, G3D::x, G3D::y, and G3D::z.
Referenced by Spell::EffectTeleportUnits().
Uninstall()
void Vehicle::Uninstall ()
@Prevent recursive uninstall call. (Bad script in OnUninstall/OnRemovePassenger/PassengerBoarded hook.)
Definition at line 101 of file Vehicle.cpp.
 {
     if (_status == STATUS_UNINSTALLING && !GetBase()->HasUnitTypeMask(UNIT_MASK_MINION))
     {
         LOG_ERROR("vehicles", "Vehicle %s attempts to uninstall, but already has STATUS_UNINSTALLING! "
                        "Check Uninstall/PassengerBoarded script hooks for errors.", _me->GetGUID().ToString().c_str());
         return;
     }
     _status = STATUS_UNINSTALLING;
     LOG_DEBUG("vehicles", "Vehicle::Uninstall %s", _me->GetGUID().ToString().c_str());
     RemoveAllPassengers();
     if (GetBase()->GetTypeId() == TYPEID_UNIT)
         sScriptMgr->OnUninstall(this);
 }
References _me, _status, GetBase(), Object::GetGUID(), LOG_DEBUG, LOG_ERROR, RemoveAllPassengers(), sScriptMgr, STATUS_UNINSTALLING, ObjectGuid::ToString(), TYPEID_UNIT, and UNIT_MASK_MINION.
Referenced by Unit::_ExitVehicle(), Dismiss(), and Unit::RemoveVehicleKit().
Friends And Related Function Documentation
Unit::CreateVehicleKit
bool Unit::CreateVehicleKit (uint32 id, uint32 creatureEntry) friend
Unit::RemoveVehicleKit
void Unit::RemoveVehicleKit () friend
Member Data Documentation
_creatureEntry
uint32 Vehicle::_creatureEntry private
Definition at line 97 of file Vehicle.h.
Referenced by GetCreatureEntry().
_me
Unit* Vehicle::_me private
Definition at line 94 of file Vehicle.h.
Referenced by AddPassenger(), ApplyAllImmunities(), Dismiss(), GetBase(), InitMovementInfoForBase(), Install(), InstallAccessory(), RelocatePassengers(), RemoveAllPassengers(), RemovePassenger(), Reset(), TeleportVehicle(), Uninstall(), and ~Vehicle().
_status
Status Vehicle::_status private
Definition at line 98 of file Vehicle.h.
Referenced by AddPassenger(), Install(), InstallAccessory(), Uninstall(), and ~Vehicle().
_usableSeatNum
uint32 Vehicle::_usableSeatNum private
Definition at line 96 of file Vehicle.h.
Referenced by AddPassenger(), RemovePassenger(), Reset(), and Vehicle().
_vehicleInfo
VehicleEntry const* Vehicle::_vehicleInfo private
Definition at line 95 of file Vehicle.h.
Referenced by AddPassenger(), GetVehicleInfo(), Install(), RemovePassenger(), and Vehicle().
Seats
SeatMap Vehicle::Seats
Definition at line 57 of file Vehicle.h.
Referenced by SmartAI::CheckConditions(), spell_switch_infragreen_bomber_station::spell_switch_infragreen_bomber_station_SpellScript::HandleDummy(), FlameLeviathanPursuedTargetSelector::operator()(), boss_flame_leviathan::boss_flame_leviathanAI::SpellHitTarget(), and npc_wg_siege_machine::npc_wg_siege_machineAI::UpdateAI().
The documentation for this class was generated from the following files:
src/server/game/Entities/Vehicle/Vehicle.h
src/server/game/Entities/Vehicle/Vehicle.cpp