Azerotcore-wotlk: deps/jemalloc/src/pages.c File Reference
pages.c File Reference
#include "jemalloc/internal/jemalloc_preamble.h"
#include "jemalloc/internal/pages.h"
#include "jemalloc/internal/jemalloc_internal_includes.h"
#include "jemalloc/internal/assert.h"
#include "jemalloc/internal/malloc_io.h"
Macros
#define JEMALLOC_PAGES_C_
#define PAGES_PROT_COMMIT (PROT_READ | PROT_WRITE)
#define PAGES_PROT_DECOMMIT (PROT_NONE)
Functions
static void os_pages_unmap (void *addr, size_t size)
static void * os_pages_map (void *addr, size_t size, size_t alignment, bool *commit)
static void * os_pages_trim (void *addr, size_t alloc_size, size_t leadsize, size_t size, bool *commit)
static void * pages_map_slow (size_t size, size_t alignment, bool *commit)
void * pages_map (void *addr, size_t size, size_t alignment, bool *commit)
void pages_unmap (void *addr, size_t size)
static bool pages_commit_impl (void *addr, size_t size, bool commit)
bool pages_commit (void *addr, size_t size)
bool pages_decommit (void *addr, size_t size)
bool pages_purge_lazy (void *addr, size_t size)
bool pages_purge_forced (void *addr, size_t size)
static bool pages_huge_impl (void *addr, size_t size, bool aligned)
bool pages_huge (void *addr, size_t size)
static bool pages_huge_unaligned (void *addr, size_t size)
static bool pages_nohuge_impl (void *addr, size_t size, bool aligned)
bool pages_nohuge (void *addr, size_t size)
static bool pages_nohuge_unaligned (void *addr, size_t size)
bool pages_dontdump (void *addr, size_t size)
bool pages_dodump (void *addr, size_t size)
static size_t os_page_detect (void)
void pages_set_thp_state (void *ptr, size_t size)
static void init_thp_state (void)
bool pages_boot (void)
Variables
static size_t os_page
static int mmap_flags
static bool os_overcommits
const char * thp_mode_names []
thp_mode_t opt_thp = THP_MODE_DEFAULT
thp_mode_t init_system_thp_mode
static bool pages_can_purge_lazy_runtime = true
Macro Definition Documentation
JEMALLOC_PAGES_C_
#define JEMALLOC_PAGES_C_
Definition at line 1 of file pages.c.
PAGES_PROT_COMMIT
#define PAGES_PROT_COMMIT (PROT_READ | PROT_WRITE)
Definition at line 25 of file pages.c.
PAGES_PROT_DECOMMIT
#define PAGES_PROT_DECOMMIT (PROT_NONE)
Definition at line 26 of file pages.c.
Function Documentation
init_thp_state()
static void init_thp_state (void) static
Definition at line 549 of file pages.c.
                      {
     if (!have_madvise_huge) {
         if (metadata_thp_enabled() && opt_abort) {
             malloc_write("<jemalloc>: no MADV_HUGEPAGE support\n");
             abort();
         }
         goto label_error;
     }
     static const char sys_state_madvise[] = "always [madvise] never\n";
     static const char sys_state_always[] = "[always] madvise never\n";
     static const char sys_state_never[] = "always madvise [never]\n";
     char buf[sizeof(sys_state_madvise)];
 #if defined(JEMALLOC_USE_SYSCALL) && defined(SYS_open)
     int fd = (int)syscall(SYS_open,
         "/sys/kernel/mm/transparent_hugepage/enabled", O_RDONLY);
 #else
     int fd = open("/sys/kernel/mm/transparent_hugepage/enabled", O_RDONLY);
 #endif
     if (fd == -1) {
         goto label_error;
     }
     ssize_t nread = malloc_read_fd(fd, &buf, sizeof(buf));
 #if defined(JEMALLOC_USE_SYSCALL) && defined(SYS_close)
     syscall(SYS_close, fd);
 #else
     close(fd);
 #endif
         if (nread < 0) {
         goto label_error;
         }
     if (strncmp(buf, sys_state_madvise, (size_t)nread) == 0) {
         init_system_thp_mode = thp_mode_default;
     } else if (strncmp(buf, sys_state_always, (size_t)nread) == 0) {
         init_system_thp_mode = thp_mode_always;
     } else if (strncmp(buf, sys_state_never, (size_t)nread) == 0) {
         init_system_thp_mode = thp_mode_never;
     } else {
         goto label_error;
     }
     return;
 label_error:
     opt_thp = init_system_thp_mode = thp_mode_not_supported;
 }
References close, have_madvise_huge, init_system_thp_mode, malloc_read_fd(), malloc_write, metadata_thp_enabled(), open, opt_abort, opt_thp, thp_mode_always, thp_mode_default, thp_mode_never, and thp_mode_not_supported.
Referenced by pages_boot().
os_page_detect()
static size_t os_page_detect (void) static
Definition at line 417 of file pages.c.
                      {
 #ifdef _WIN32
     SYSTEM_INFO si;
     GetSystemInfo(&si);
     return si.dwPageSize;
 #elif defined(__FreeBSD__)
     /*
      * This returns the value obtained from
      * the auxv vector, avoiding a syscall.
      */
     return getpagesize();
 #else
     long result = sysconf(_SC_PAGESIZE);
     if (result == -1) {
         return LG_PAGE;
     }
     return (size_t)result;
 #endif
 }
References LG_PAGE.
Referenced by pages_boot().
os_pages_map()
static void* os_pages_map (void * addr, size_t size, size_t alignment, bool * commit) static
Definition at line 54 of file pages.c.
{
     assert(ALIGNMENT_ADDR2BASE(addr, os_page) == addr);
     assert(ALIGNMENT_CEILING(size, os_page) == size);
     assert(size != 0);
     if (os_overcommits) {
         *commit = true;
     }
     void *ret;
 #ifdef _WIN32
     /*
      * If VirtualAlloc can't allocate at the given address when one is
      * given, it fails and returns NULL.
      */
     ret = VirtualAlloc(addr, size, MEM_RESERVE | (*commit ? MEM_COMMIT : 0),
         PAGE_READWRITE);
 #else
     /*
      * We don't use MAP_FIXED here, because it can cause the *replacement*
      * of existing mappings, and we only want to create new mappings.
      */
     {
         int prot = *commit ? PAGES_PROT_COMMIT : PAGES_PROT_DECOMMIT;
         ret = mmap(addr, size, prot, mmap_flags, -1, 0);
     }
     assert(ret != NULL);
     if (ret == MAP_FAILED) {
         ret = NULL;
     } else if (addr != NULL && ret != addr) {
         /*
          * We succeeded in mapping memory, but not in the right place.
          */
         os_pages_unmap(ret, size);
         ret = NULL;
     }
 #endif
     assert(ret == NULL || (addr == NULL && ret != addr) || (addr != NULL &&
         ret == addr));
     return ret;
 }
References ALIGNMENT_ADDR2BASE, ALIGNMENT_CEILING, assert(), MAP_FAILED, mmap_flags, NULL, os_overcommits, os_page, os_pages_unmap(), PAGES_PROT_COMMIT, PAGES_PROT_DECOMMIT, and ret.
Referenced by os_pages_trim(), pages_boot(), pages_map(), and pages_map_slow().
os_pages_trim()
static void* os_pages_trim (void * addr, size_t alloc_size, size_t leadsize, size_t size, bool * commit) static
Definition at line 99 of file pages.c.
                   {
     void *ret = (void *)((uintptr_t)addr + leadsize);
     assert(alloc_size >= leadsize + size);
 #ifdef _WIN32
     os_pages_unmap(addr, alloc_size);
     void *new_addr = os_pages_map(ret, size, PAGE, commit);
     if (new_addr == ret) {
         return ret;
     }
     if (new_addr != NULL) {
         os_pages_unmap(new_addr, size);
     }
     return NULL;
 #else
     size_t trailsize = alloc_size - leadsize - size;
     if (leadsize != 0) {
         os_pages_unmap(addr, leadsize);
     }
     if (trailsize != 0) {
         os_pages_unmap((void *)((uintptr_t)ret + size), trailsize);
     }
     return ret;
 #endif
 }
References assert(), NULL, os_pages_map(), os_pages_unmap(), PAGE, and ret.
Referenced by pages_map_slow().
os_pages_unmap()
static void os_pages_unmap (void * addr, size_t size) static
Definition at line 128 of file pages.c.
{
     assert(ALIGNMENT_ADDR2BASE(addr, os_page) == addr);
     assert(ALIGNMENT_CEILING(size, os_page) == size);
 #ifdef _WIN32
     if (VirtualFree(addr, 0, MEM_RELEASE) == 0)
 #else
     if (munmap(addr, size) == -1)
 #endif
     {
         char buf[BUFERROR_BUF];
         buferror(get_errno(), buf, sizeof(buf));
         malloc_printf("<jemalloc>: Error in "
 #ifdef _WIN32
             "VirtualFree"
 #else
             "munmap"
 #endif
             "(): %s\n", buf);
         if (opt_abort) {
             abort();
         }
     }
 }
References ALIGNMENT_ADDR2BASE, ALIGNMENT_CEILING, assert(), buferror, BUFERROR_BUF, endif(), get_errno(), malloc_printf, opt_abort, and os_page.
Referenced by os_pages_map(), os_pages_trim(), pages_boot(), pages_commit_impl(), pages_map(), and pages_unmap().
pages_boot()
bool pages_boot (void)
Definition at line 599 of file pages.c.
                  {
     os_page = os_page_detect();
     if (os_page > PAGE) {
         malloc_write("<jemalloc>: Unsupported system page size\n");
         if (opt_abort) {
             abort();
         }
         return true;
     }
 #ifndef _WIN32
     mmap_flags = MAP_PRIVATE | MAP_ANON;
 #endif
 #ifdef JEMALLOC_SYSCTL_VM_OVERCOMMIT
     os_overcommits = os_overcommits_sysctl();
 #elif defined(JEMALLOC_PROC_SYS_VM_OVERCOMMIT_MEMORY)
     os_overcommits = os_overcommits_proc();
 #  ifdef MAP_NORESERVE
     if (os_overcommits) {
         mmap_flags |= MAP_NORESERVE;
     }
 #  endif
 #else
     os_overcommits = false;
 #endif
     init_thp_state();
 #ifdef __FreeBSD__
     /*
      * FreeBSD doesn't need the check; madvise(2) is known to work.
      */
 #else
     /* Detect lazy purge runtime support. */
     if (pages_can_purge_lazy) {
         bool committed = false;
         void *madv_free_page = os_pages_map(NULL, PAGE, PAGE, &committed);
         if (madv_free_page == NULL) {
             return true;
         }
         assert(pages_can_purge_lazy_runtime);
         if (pages_purge_lazy(madv_free_page, PAGE)) {
             pages_can_purge_lazy_runtime = false;
         }
         os_pages_unmap(madv_free_page, PAGE);
     }
 #endif
     return false;
 }
References assert(), init_thp_state(), malloc_write, MAP_NORESERVE, MAP_PRIVATE, mmap_flags, NULL, opt_abort, os_overcommits, os_page, os_page_detect(), os_pages_map(), os_pages_unmap(), PAGE, pages_can_purge_lazy, pages_can_purge_lazy_runtime, and pages_purge_lazy().
pages_commit()
bool pages_commit (void * addr, size_t size)
Definition at line 282 of file pages.c.
{
     return pages_commit_impl(addr, size, true);
 }
References pages_commit_impl().
Referenced by pages_purge_forced().
pages_commit_impl()
static bool pages_commit_impl (void * addr, size_t size, bool commit) static
Definition at line 249 of file pages.c.
{
     assert(PAGE_ADDR2BASE(addr) == addr);
     assert(PAGE_CEILING(size) == size);
     if (os_overcommits) {
         return true;
     }
 #ifdef _WIN32
     return (commit ? (addr != VirtualAlloc(addr, size, MEM_COMMIT,
         PAGE_READWRITE)) : (!VirtualFree(addr, size, MEM_DECOMMIT)));
 #else
     {
         int prot = commit ? PAGES_PROT_COMMIT : PAGES_PROT_DECOMMIT;
         void *result = mmap(addr, size, prot, mmap_flags | MAP_FIXED,
             -1, 0);
         if (result == MAP_FAILED) {
             return true;
         }
         if (result != addr) {
             /*
              * We succeeded in mapping memory, but not in the right
              * place.
              */
             os_pages_unmap(result, size);
             return true;
         }
         return false;
     }
 #endif
 }
References assert(), MAP_FAILED, mmap_flags, os_overcommits, os_pages_unmap(), PAGE_ADDR2BASE, PAGE_CEILING, PAGES_PROT_COMMIT, and PAGES_PROT_DECOMMIT.
Referenced by pages_commit(), and pages_decommit().
pages_decommit()
bool pages_decommit (void * addr, size_t size)
Definition at line 287 of file pages.c.
{
     return pages_commit_impl(addr, size, false);
 }
References pages_commit_impl().
pages_dodump()
bool pages_dodump (void * addr, size_t size)
Definition at line 405 of file pages.c.
{
     assert(PAGE_ADDR2BASE(addr) == addr);
     assert(PAGE_CEILING(size) == size);
 #ifdef JEMALLOC_MADVISE_DONTDUMP
     return madvise(addr, size, MADV_DODUMP) != 0;
 #else
     return false;
 #endif
 }
References assert(), PAGE_ADDR2BASE, and PAGE_CEILING.
pages_dontdump()
bool pages_dontdump (void * addr, size_t size)
Definition at line 394 of file pages.c.
{
     assert(PAGE_ADDR2BASE(addr) == addr);
     assert(PAGE_CEILING(size) == size);
 #ifdef JEMALLOC_MADVISE_DONTDUMP
     return madvise(addr, size, MADV_DONTDUMP) != 0;
 #else
     return false;
 #endif
 }
References assert(), PAGE_ADDR2BASE, and PAGE_CEILING.
pages_huge()
bool pages_huge (void * addr, size_t size)
Definition at line 360 of file pages.c.
{
     return pages_huge_impl(addr, size, true);
 }
References pages_huge_impl().
pages_huge_impl()
static bool pages_huge_impl (void * addr, size_t size, bool aligned) static
Definition at line 347 of file pages.c.
{
     if (aligned) {
         assert(HUGEPAGE_ADDR2BASE(addr) == addr);
         assert(HUGEPAGE_CEILING(size) == size);
     }
 #ifdef JEMALLOC_HAVE_MADVISE_HUGE
     return (madvise(addr, size, MADV_HUGEPAGE) != 0);
 #else
     return true;
 #endif
 }
References assert(), HUGEPAGE_ADDR2BASE, and HUGEPAGE_CEILING.
Referenced by pages_huge(), and pages_huge_unaligned().
pages_huge_unaligned()
static bool pages_huge_unaligned (void * addr, size_t size) static
Definition at line 365 of file pages.c.
{
     return pages_huge_impl(addr, size, false);
 }
References pages_huge_impl().
Referenced by pages_set_thp_state().
pages_map()
void* pages_map (void * addr, size_t size, size_t alignment, bool * commit)
Definition at line 179 of file pages.c.
{
     assert(alignment >= PAGE);
     assert(ALIGNMENT_ADDR2BASE(addr, alignment) == addr);
 #if defined(__FreeBSD__) && defined(MAP_EXCL)
     /*
      * FreeBSD has mechanisms both to mmap at specific address without
      * touching existing mappings, and to mmap with specific alignment.
      */
     {
         if (os_overcommits) {
             *commit = true;
         }
         int prot = *commit ? PAGES_PROT_COMMIT : PAGES_PROT_DECOMMIT;
         int flags = mmap_flags;
         if (addr != NULL) {
             flags |= MAP_FIXED | MAP_EXCL;
         } else {
             unsigned alignment_bits = ffs_zu(alignment);
             assert(alignment_bits > 1);
             flags |= MAP_ALIGNED(alignment_bits - 1);
         }
         void *ret = mmap(addr, size, prot, flags, -1, 0);
         if (ret == MAP_FAILED) {
             ret = NULL;
         }
         return ret;
     }
 #endif
     /*
      * Ideally, there would be a way to specify alignment to mmap() (like
      * NetBSD has), but in the absence of such a feature, we have to work
      * hard to efficiently create aligned mappings.  The reliable, but
      * slow method is to create a mapping that is over-sized, then trim the
      * excess.  However, that always results in one or two calls to
      * os_pages_unmap(), and it can leave holes in the process's virtual
      * memory map if memory grows downward.
      *
      * Optimistically try mapping precisely the right amount before falling
      * back to the slow method, with the expectation that the optimistic
      * approach works most of the time.
      */
     void *ret = os_pages_map(addr, size, os_page, commit);
     if (ret == NULL || ret == addr) {
         return ret;
     }
     assert(addr == NULL);
     if (ALIGNMENT_ADDR2OFFSET(ret, alignment) != 0) {
         os_pages_unmap(ret, size);
         return pages_map_slow(size, alignment, commit);
     }
     assert(PAGE_ADDR2BASE(ret) == ret);
     return ret;
 }
References ALIGNMENT_ADDR2BASE, ALIGNMENT_ADDR2OFFSET, assert(), ffs_zu(), MAP_FAILED, mmap_flags, NULL, os_overcommits, os_page, os_pages_map(), os_pages_unmap(), PAGE, PAGE_ADDR2BASE, pages_map_slow(), PAGES_PROT_COMMIT, PAGES_PROT_DECOMMIT, and ret.
pages_map_slow()
static void* pages_map_slow (size_t size, size_t alignment, bool * commit) static
Definition at line 155 of file pages.c.
{
     size_t alloc_size = size + alignment - os_page;
     /* Beware size_t wrap-around. */
     if (alloc_size < size) {
         return NULL;
     }
     void *ret;
     do {
         void *pages = os_pages_map(NULL, alloc_size, alignment, commit);
         if (pages == NULL) {
             return NULL;
         }
         size_t leadsize = ALIGNMENT_CEILING((uintptr_t)pages, alignment)
             - (uintptr_t)pages;
         ret = os_pages_trim(pages, alloc_size, leadsize, size, commit);
     } while (ret == NULL);
     assert(ret != NULL);
     assert(PAGE_ADDR2BASE(ret) == ret);
     return ret;
 }
References ALIGNMENT_CEILING, assert(), NULL, os_page, os_pages_map(), os_pages_trim(), PAGE_ADDR2BASE, ret, and uintptr_t.
Referenced by pages_map().
pages_nohuge()
bool pages_nohuge (void * addr, size_t size)
Definition at line 384 of file pages.c.
{
     return pages_nohuge_impl(addr, size, true);
 }
References pages_nohuge_impl().
pages_nohuge_impl()
static bool pages_nohuge_impl (void * addr, size_t size, bool aligned) static
Definition at line 370 of file pages.c.
{
     if (aligned) {
         assert(HUGEPAGE_ADDR2BASE(addr) == addr);
         assert(HUGEPAGE_CEILING(size) == size);
     }
 #ifdef JEMALLOC_HAVE_MADVISE_HUGE
     return (madvise(addr, size, MADV_NOHUGEPAGE) != 0);
 #else
     return false;
 #endif
 }
References assert(), HUGEPAGE_ADDR2BASE, and HUGEPAGE_CEILING.
Referenced by pages_nohuge(), and pages_nohuge_unaligned().
pages_nohuge_unaligned()
static bool pages_nohuge_unaligned (void * addr, size_t size) static
Definition at line 389 of file pages.c.
{
     return pages_nohuge_impl(addr, size, false);
 }
References pages_nohuge_impl().
Referenced by pages_set_thp_state().
pages_purge_forced()
bool pages_purge_forced (void * addr, size_t size)
Definition at line 327 of file pages.c.
{
     assert(PAGE_ADDR2BASE(addr) == addr);
     assert(PAGE_CEILING(size) == size);
     if (!pages_can_purge_forced) {
         return true;
     }
 #if defined(JEMALLOC_PURGE_MADVISE_DONTNEED) && \
     defined(JEMALLOC_PURGE_MADVISE_DONTNEED_ZEROS)
     return (madvise(addr, size, MADV_DONTNEED) != 0);
 #elif defined(JEMALLOC_MAPS_COALESCE)
     /* Try to overlay a new demand-zeroed mapping. */
     return pages_commit(addr, size);
 #else
     not_reached();
 #endif
 }
References assert(), not_reached, PAGE_ADDR2BASE, PAGE_CEILING, pages_can_purge_forced, and pages_commit().
pages_purge_lazy()
bool pages_purge_lazy (void * addr, size_t size)
Definition at line 292 of file pages.c.
{
     assert(ALIGNMENT_ADDR2BASE(addr, os_page) == addr);
     assert(PAGE_CEILING(size) == size);
     if (!pages_can_purge_lazy) {
         return true;
     }
     if (!pages_can_purge_lazy_runtime) {
         /*
          * Built with lazy purge enabled, but detected it was not
          * supported on the current system.
          */
         return true;
     }
 #ifdef _WIN32
     VirtualAlloc(addr, size, MEM_RESET, PAGE_READWRITE);
     return false;
 #elif defined(JEMALLOC_PURGE_MADVISE_FREE)
     return (madvise(addr, size,
 #  ifdef MADV_FREE
         MADV_FREE
 #  else
         JEMALLOC_MADV_FREE
 #  endif
         ) != 0);
 #elif defined(JEMALLOC_PURGE_MADVISE_DONTNEED) && \
     !defined(JEMALLOC_PURGE_MADVISE_DONTNEED_ZEROS)
     return (madvise(addr, size, MADV_DONTNEED) != 0);
 #else
     not_reached();
 #endif
 }
References ALIGNMENT_ADDR2BASE, assert(), endif(), not_reached, os_page, PAGE_CEILING, pages_can_purge_lazy, and pages_can_purge_lazy_runtime.
Referenced by pages_boot().
pages_set_thp_state()
void pages_set_thp_state (void * ptr, size_t size)
Definition at line 530 of file pages.c.
{
     if (opt_thp == thp_mode_default || opt_thp == init_system_thp_mode) {
         return;
     }
     assert(opt_thp != thp_mode_not_supported &&
         init_system_thp_mode != thp_mode_not_supported);
     if (opt_thp == thp_mode_always
         && init_system_thp_mode != thp_mode_never) {
         assert(init_system_thp_mode == thp_mode_default);
         pages_huge_unaligned(ptr, size);
     } else if (opt_thp == thp_mode_never) {
         assert(init_system_thp_mode == thp_mode_default ||
             init_system_thp_mode == thp_mode_always);
         pages_nohuge_unaligned(ptr, size);
     }
 }
References assert(), init_system_thp_mode, opt_thp, pages_huge_unaligned(), pages_nohuge_unaligned(), ptr(), thp_mode_always, thp_mode_default, thp_mode_never, and thp_mode_not_supported.
pages_unmap()
void pages_unmap (void * addr, size_t size)
Definition at line 241 of file pages.c.
{
     assert(PAGE_ADDR2BASE(addr) == addr);
     assert(PAGE_CEILING(size) == size);
     os_pages_unmap(addr, size);
 }
References assert(), buferror, BUFERROR_BUF, endif(), get_errno(), malloc_printf, opt_abort, os_pages_unmap(), PAGE_ADDR2BASE, and PAGE_CEILING.
Variable Documentation
init_system_thp_mode
thp_mode_t init_system_thp_mode
Definition at line 38 of file pages.c.
Referenced by init_thp_state(), and pages_set_thp_state().
mmap_flags
int mmap_flags static
Definition at line 27 of file pages.c.
Referenced by os_pages_map(), pages_boot(), pages_commit_impl(), and pages_map().
opt_thp
thp_mode_t opt_thp = THP_MODE_DEFAULT
Definition at line 37 of file pages.c.
Referenced by init_thp_state(), and pages_set_thp_state().
os_overcommits
bool os_overcommits static
Definition at line 29 of file pages.c.
Referenced by os_pages_map(), pages_boot(), pages_commit_impl(), and pages_map().
os_page
size_t os_page static
Definition at line 22 of file pages.c.
Referenced by os_pages_map(), os_pages_unmap(), pages_boot(), pages_map(), pages_map_slow(), and pages_purge_lazy().
pages_can_purge_lazy_runtime
bool pages_can_purge_lazy_runtime = true static
Definition at line 41 of file pages.c.
Referenced by pages_boot(), and pages_purge_lazy().
thp_mode_names
const char* thp_mode_names[]
Initial value:
= {
    "default",
    "always",
    "never",
    "not supported"
}
Definition at line 31 of file pages.c.