Azerotcore-wotlk: boss_devourer_of_souls::boss_devourer_of_soulsAI Struct Reference
boss_devourer_of_souls::boss_devourer_of_soulsAI Struct Reference
Public Member Functions
boss_devourer_of_soulsAI (Creature *creature)
void Reset () override
uint32 GetData (uint32 id) const override
void EnterCombat (Unit *) override
void SpellHitTarget (Unit *target, const SpellInfo *spell) override
bool CanAIAttack (const Unit *target) const override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *victim) override
void JustSummoned (Creature *summon) override
void EnterEvadeMode () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
EventMap events
SummonList summons
bool bAchiev
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 87 of file boss_devourer_of_souls.cpp.
Constructor & Destructor Documentation
boss_devourer_of_soulsAI()
boss_devourer_of_souls::boss_devourer_of_soulsAI::boss_devourer_of_soulsAI (Creature * creature) inline
Definition at line 89 of file boss_devourer_of_souls.cpp.
                                                      : ScriptedAI(creature), summons(me)
         {
             pInstance = creature->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), and pInstance.
Member Function Documentation
CanAIAttack()
bool boss_devourer_of_souls::boss_devourer_of_soulsAI::CanAIAttack (const Unit * target) const inline override virtual
Reimplemented from UnitAI.
Definition at line 168 of file boss_devourer_of_souls.cpp.
 { return target->GetPositionZ() > 706.5f; }
References Position::GetPositionZ().
EnterCombat()
void boss_devourer_of_souls::boss_devourer_of_soulsAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 119 of file boss_devourer_of_souls.cpp.
         {
             Talk(SAY_FACE_AGGRO);
             DoZoneInCombat();
             events.Reset();
             events.RescheduleEvent(EVENT_SPELL_PHANTOM_BLAST, 5000);
             events.RescheduleEvent(EVENT_SPELL_MIRRORED_SOUL, 9000);
             events.RescheduleEvent(EVENT_SPELL_WELL_OF_SOULS, urand(6000, 8000));
             events.RescheduleEvent(EVENT_SPELL_UNLEASHED_SOULS, urand(18000, 20000));
             events.RescheduleEvent(EVENT_SPELL_WAILING_SOULS, 65000);
             if (pInstance)
                 pInstance->SetData(DATA_DEVOURER, IN_PROGRESS);
             // Suport for Quest Tempering the Blade
             Map::PlayerList const& pList = me->GetMap()->GetPlayers();
             for(Map::PlayerList::const_iterator itr = pList.begin(); itr != pList.end(); ++itr)
             {
                 Player* player = itr->GetSource();
                 if ((player->GetTeamId() == TEAM_ALLIANCE && player->GetQuestStatus(QUEST_TEMPERING_THE_BLADE_A) == QUEST_STATUS_INCOMPLETE) ||
                         (player->GetTeamId() == TEAM_HORDE && player->GetQuestStatus(QUEST_TEMPERING_THE_BLADE_H) == QUEST_STATUS_INCOMPLETE))
                 {
                     if (!me->FindNearestCreature(NPC_CRUCIBLE_OF_SOULS, 100.0f))
                         me->SummonCreature(NPC_CRUCIBLE_OF_SOULS, 5672.29f, 2520.69f, 713.44f, 0.96f);
                 }
             }
         }
References MapRefMgr::begin(), DATA_DEVOURER, CreatureAI::DoZoneInCombat(), MapRefMgr::end(), EVENT_SPELL_MIRRORED_SOUL, EVENT_SPELL_PHANTOM_BLAST, EVENT_SPELL_UNLEASHED_SOULS, EVENT_SPELL_WAILING_SOULS, EVENT_SPELL_WELL_OF_SOULS, WorldObject::FindNearestCreature(), WorldObject::GetMap(), Map::GetPlayers(), Player::GetQuestStatus(), Player::GetTeamId(), IN_PROGRESS, ScriptedAI::me, NPC_CRUCIBLE_OF_SOULS, pInstance, QUEST_STATUS_INCOMPLETE, QUEST_TEMPERING_THE_BLADE_A, QUEST_TEMPERING_THE_BLADE_H, SAY_FACE_AGGRO, ZoneScript::SetData(), WorldObject::SummonCreature(), CreatureAI::Talk(), TEAM_ALLIANCE, TEAM_HORDE, and urand().
EnterEvadeMode()
void boss_devourer_of_souls::boss_devourer_of_soulsAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 296 of file boss_devourer_of_souls.cpp.
         {
             me->SetControlled(false, UNIT_STATE_ROOT);
             me->DisableRotate(false);
             ScriptedAI::EnterEvadeMode();
         }
References Unit::DisableRotate(), CreatureAI::EnterEvadeMode(), ScriptedAI::me, Unit::SetControlled(), and UNIT_STATE_ROOT.
GetData()
uint32 boss_devourer_of_souls::boss_devourer_of_soulsAI::GetData (uint32 id) const inline override virtual
Reimplemented from UnitAI.
Definition at line 111 of file boss_devourer_of_souls.cpp.
         {
             if (id == 1)
                 return bAchiev;
             return 0;
         }
References bAchiev.
JustDied()
void boss_devourer_of_souls::boss_devourer_of_soulsAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 250 of file boss_devourer_of_souls.cpp.
         {
             Talk(SAY_FACE_DEATH);
             summons.DespawnAll();
             if (pInstance)
                 pInstance->SetData(DATA_DEVOURER, DONE);
         }
References DATA_DEVOURER, SummonList::DespawnAll(), DONE, pInstance, SAY_FACE_DEATH, ZoneScript::SetData(), summons, and CreatureAI::Talk().
JustSummoned()
void boss_devourer_of_souls::boss_devourer_of_soulsAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 283 of file boss_devourer_of_souls.cpp.
         {
             if (summon->GetEntry() != NPC_CRUCIBLE_OF_SOULS)
                 summons.Summon(summon);
             if (summon->GetEntry() == 36595)
                 if (Player* plr = summon->SelectNearestPlayer(100.0f))
                 {
                     summon->AddThreat(plr, 100000.0f);
                     summon->AI()->AttackStart(plr);
                 }
         }
References Unit::AddThreat(), Creature::AI(), UnitAI::AttackStart(), Object::GetEntry(), NPC_CRUCIBLE_OF_SOULS, WorldObject::SelectNearestPlayer(), SummonList::Summon(), and summons.
KilledUnit()
void boss_devourer_of_souls::boss_devourer_of_soulsAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 258 of file boss_devourer_of_souls.cpp.
         {
             if (victim->GetTypeId() != TYPEID_PLAYER)
                 return;
             int32 textId = 0;
             switch (me->GetDisplayId())
             {
                 case DISPLAY_ANGER:
                     textId =  SAY_FACE_ANGER_SLAY;
                     break;
                 case DISPLAY_SORROW:
                     textId = SAY_FACE_SORROW_SLAY;
                     break;
                 case DISPLAY_DESIRE:
                     textId = SAY_FACE_DESIRE_SLAY;
                     break;
                 default:
                     break;
             }
             if (textId)
                 Talk(textId);
         }
References DISPLAY_ANGER, DISPLAY_DESIRE, DISPLAY_SORROW, Unit::GetDisplayId(), Object::GetTypeId(), ScriptedAI::me, SAY_FACE_ANGER_SLAY, SAY_FACE_DESIRE_SLAY, SAY_FACE_SORROW_SLAY, CreatureAI::Talk(), and TYPEID_PLAYER.
Reset()
void boss_devourer_of_souls::boss_devourer_of_soulsAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 99 of file boss_devourer_of_souls.cpp.
         {
             bAchiev = true;
             me->SetControlled(false, UNIT_STATE_ROOT);
             me->DisableRotate(false);
             me->SetReactState(REACT_AGGRESSIVE);
             events.Reset();
             summons.DespawnAll();
             if (pInstance)
                 pInstance->SetData(DATA_DEVOURER, NOT_STARTED);
         }
References bAchiev, DATA_DEVOURER, SummonList::DespawnAll(), Unit::DisableRotate(), ScriptedAI::me, NOT_STARTED, pInstance, REACT_AGGRESSIVE, Unit::SetControlled(), ZoneScript::SetData(), Creature::SetReactState(), summons, and UNIT_STATE_ROOT.
SpellHitTarget()
void boss_devourer_of_souls::boss_devourer_of_soulsAI::SpellHitTarget (Unit * target, const SpellInfo * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 147 of file boss_devourer_of_souls.cpp.
         {
             if (spell->Id == SPELL_PHANTOM_BLAST_H)
                 bAchiev = false;
             else if (spell->Id == SPELL_WAILING_SOULS_TARGETING)
             {
                 me->SetOrientation(me->GetAngle(target));
                 me->SetControlled(true, UNIT_STATE_ROOT);
                 me->DisableRotate(true);
                 me->SetGuidValue(UNIT_FIELD_TARGET, ObjectGuid::Empty);
                 me->SetReactState(REACT_PASSIVE);
                 me->GetMotionMaster()->Clear(false);
                 me->GetMotionMaster()->MoveIdle();
                 me->StopMovingOnCurrentPos();
                 me->SetFacingToObject(target);
                 me->SendMovementFlagUpdate();
                 me->CastSpell(me, SPELL_WAILING_SOULS, false);
             }
         }
References bAchiev, Unit::CastSpell(), MotionMaster::Clear(), Unit::DisableRotate(), ObjectGuid::Empty, Position::GetAngle(), Unit::GetMotionMaster(), SpellInfo::Id, ScriptedAI::me, MotionMaster::MoveIdle(), REACT_PASSIVE, Unit::SendMovementFlagUpdate(), Unit::SetControlled(), Unit::SetFacingToObject(), Object::SetGuidValue(), Position::SetOrientation(), Creature::SetReactState(), SPELL_PHANTOM_BLAST_H, SPELL_WAILING_SOULS, SPELL_WAILING_SOULS_TARGETING, Unit::StopMovingOnCurrentPos(), UNIT_FIELD_TARGET, and UNIT_STATE_ROOT.
UpdateAI()
void boss_devourer_of_souls::boss_devourer_of_soulsAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 170 of file boss_devourer_of_souls.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (Spell* s = me->GetCurrentSpell(CURRENT_CHANNELED_SPELL))
                 if (s->m_spellInfo->Id == SPELL_MIRRORED_SOUL)
                 {
                     switch (events.ExecuteEvent())
                     {
                         case 0:
                             break;
                         case EVENT_SPELL_PHANTOM_BLAST:
                             me->CastSpell(me->GetVictim(), SPELL_PHANTOM_BLAST, false);
                             events.RepeatEvent(5000);
                             break;
                         default:
                             events.RepeatEvent(1000);
                             break;
                     }
                     if (!me->GetCurrentSpell(CURRENT_GENERIC_SPELL))
                     {
                         me->ClearUnitState(UNIT_STATE_CASTING);
                         DoMeleeAttackIfReady();
                         me->AddUnitState(UNIT_STATE_CASTING);
                     }
                     return;
                 }
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch(events.ExecuteEvent())
             {
                 case 0:
                     break;
                 case EVENT_SPELL_PHANTOM_BLAST:
                     me->CastSpell(me->GetVictim(), SPELL_PHANTOM_BLAST, false);
                     events.RepeatEvent(5000);
                     break;
                 case EVENT_SPELL_MIRRORED_SOUL:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 90.0f, true))
                     {
                         me->CastSpell(target, SPELL_MIRRORED_SOUL, false);
                         me->setAttackTimer(BASE_ATTACK, 2500);
                         Talk(EMOTE_MIRRORED_SOUL);
                     }
                     events.RepeatEvent(urand(20000, 30000));
                     break;
                 case EVENT_SPELL_WELL_OF_SOULS:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 40.0f, true))
                         me->CastSpell(target, SPELL_WELL_OF_SOULS, false);
                     events.RepeatEvent(urand(25000, 30000));
                     events.DelayEventsToMax(4000, 0);
                     break;
                 case EVENT_SPELL_UNLEASHED_SOULS:
                     me->CastSpell(me, SPELL_UNLEASHED_SOULS, false);
                     Talk(SAY_FACE_UNLEASH_SOUL);
                     Talk(EMOTE_UNLEASH_SOUL);
                     events.RepeatEvent(urand(30000, 40000));
                     events.DelayEventsToMax(5000, 0);
                     me->setAttackTimer(BASE_ATTACK, 5500);
                     break;
                 case EVENT_SPELL_WAILING_SOULS:
                     Talk(SAY_FACE_WAILING_SOUL);
                     Talk(EMOTE_WAILING_SOUL);
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 0.0f, true))
                         me->CastCustomSpell(SPELL_WAILING_SOULS_TARGETING, SPELLVALUE_MAX_TARGETS, 1, target, false);
                     events.RepeatEvent(80000);
                     events.DelayEventsToMax(20000, 0);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References Unit::AddUnitState(), BASE_ATTACK, Unit::CastCustomSpell(), Unit::CastSpell(), Unit::ClearUnitState(), CURRENT_CHANNELED_SPELL, CURRENT_GENERIC_SPELL, UnitAI::DoMeleeAttackIfReady(), EMOTE_MIRRORED_SOUL, EMOTE_UNLEASH_SOUL, EMOTE_WAILING_SOUL, EVENT_SPELL_MIRRORED_SOUL, EVENT_SPELL_PHANTOM_BLAST, EVENT_SPELL_UNLEASHED_SOULS, EVENT_SPELL_WAILING_SOULS, EVENT_SPELL_WELL_OF_SOULS, Unit::GetCurrentSpell(), Unit::GetVictim(), Unit::HasUnitState(), ScriptedAI::me, SAY_FACE_UNLEASH_SOUL, SAY_FACE_WAILING_SOUL, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Unit::setAttackTimer(), SPELL_MIRRORED_SOUL, SPELL_PHANTOM_BLAST, SPELL_UNLEASHED_SOULS, SPELL_WAILING_SOULS_TARGETING, SPELL_WELL_OF_SOULS, SPELLVALUE_MAX_TARGETS, CreatureAI::Talk(), UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
bAchiev
bool boss_devourer_of_souls::boss_devourer_of_soulsAI::bAchiev
Definition at line 97 of file boss_devourer_of_souls.cpp.
Referenced by GetData(), Reset(), and SpellHitTarget().
events
EventMap boss_devourer_of_souls::boss_devourer_of_soulsAI::events
Definition at line 95 of file boss_devourer_of_souls.cpp.
pInstance
InstanceScript* boss_devourer_of_souls::boss_devourer_of_soulsAI::pInstance
Definition at line 94 of file boss_devourer_of_souls.cpp.
Referenced by boss_devourer_of_soulsAI(), EnterCombat(), JustDied(), and Reset().
summons
SummonList boss_devourer_of_souls::boss_devourer_of_soulsAI::summons
Definition at line 96 of file boss_devourer_of_souls.cpp.
Referenced by JustDied(), JustSummoned(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/FrozenHalls/ForgeOfSouls/boss_devourer_of_souls.cpp