Azerotcore-wotlk: npc_toc5_player_vehicle::npc_toc5_player_vehicleAI Struct Reference
npc_toc5_player_vehicle::npc_toc5_player_vehicleAI Struct Reference
Public Member Functions
npc_toc5_player_vehicleAI (Creature *pCreature)
void Reset () override
void OnCharmed (bool apply) override
void PassengerBoarded (Unit *who, int8, bool apply) override
== Fields =======================================
void MoveInLineOfSight (Unit *) override
void UpdateAI (uint32 diff) override
void AttackStart (Unit *) override
void EnterCombat (Unit *) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void EnterEvadeMode () override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
ConditionList conditions
uint16 m_ConditionsTimer
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 148 of file boss_grand_champions.cpp.
Constructor & Destructor Documentation
npc_toc5_player_vehicleAI()
npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::npc_toc5_player_vehicleAI (Creature * pCreature) inline
Definition at line 150 of file boss_grand_champions.cpp.
                                                        : NullCreatureAI(pCreature)
         {
             conditions = sConditionMgr->GetConditionsForNotGroupedEntry(CONDITION_SOURCE_TYPE_CREATURE_TEMPLATE_VEHICLE, me->GetEntry());
             m_ConditionsTimer = 1000;
         }
References CONDITION_SOURCE_TYPE_CREATURE_TEMPLATE_VEHICLE, conditions, Object::GetEntry(), m_ConditionsTimer, CreatureAI::me, and sConditionMgr.
Member Function Documentation
AttackStart()
void npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::AttackStart (Unit *) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 214 of file boss_grand_champions.cpp.
 {}
EnterCombat()
void npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::EnterCombat (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 215 of file boss_grand_champions.cpp.
 {}
MoveInLineOfSight()
void npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 200 of file boss_grand_champions.cpp.
 {}
OnCharmed()
void npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::OnCharmed (bool apply) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 165 of file boss_grand_champions.cpp.
         {
             if (me->IsDuringRemoveFromWorld())
                 return;
             if( apply )
             {
                 me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                 me->SetSpeed(MOVE_RUN, 2.0f, false);
                 me->CastSpell(me, SPELL_TRAMPLE_AURA, true);
             }
             else
             {
                 me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                 me->StopMoving();
                 me->RemoveAura(SPELL_TRAMPLE_AURA);
             }
         }
References ByteConverter::apply(), Unit::CastSpell(), Unit::IsDuringRemoveFromWorld(), CreatureAI::me, MOVE_RUN, Unit::RemoveAura(), Object::RemoveFlag(), Object::SetFlag(), Unit::SetSpeed(), SPELL_TRAMPLE_AURA, Unit::StopMoving(), UNIT_FIELD_FLAGS, and UNIT_FLAG_NON_ATTACKABLE.
PassengerBoarded()
void npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::PassengerBoarded (Unit * , int8 , bool) inline override virtual
== Fields =======================================
Reimplemented from CreatureAI.
Definition at line 185 of file boss_grand_champions.cpp.
         {
             if (me->IsDuringRemoveFromWorld())
                 return;
             if( !apply )
             {
                 me->RemoveAura(SPELL_PLAYER_VEHICLE_DEFEND);
                 who->RemoveAura(SPELL_PLAYER_VEHICLE_DEFEND);
                 for (uint8 i = 0; i < 3; ++i)
                     who->RemoveAura(SPELL_SHIELD_LEVEL_1_VISUAL + i);
             }
         }
References ByteConverter::apply(), Unit::IsDuringRemoveFromWorld(), CreatureAI::me, Unit::RemoveAura(), SPELL_PLAYER_VEHICLE_DEFEND, and SPELL_SHIELD_LEVEL_1_VISUAL.
Reset()
void npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::Reset () inline override virtual
Reimplemented from UnitAI.
Definition at line 159 of file boss_grand_champions.cpp.
         {
             me->SetReactState(REACT_PASSIVE);
             me->getHostileRefMgr().setOnlineOfflineState(false);
         }
References Unit::getHostileRefMgr(), CreatureAI::me, REACT_PASSIVE, HostileRefMgr::setOnlineOfflineState(), and Creature::SetReactState().
UpdateAI()
void npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 201 of file boss_grand_champions.cpp.
         {
             if (m_ConditionsTimer <= diff)
             {
                 if (!conditions.empty())
                     if (Unit* passenger = me->GetVehicleKit()->GetPassenger(0))
                         if (!sConditionMgr->IsObjectMeetToConditions(passenger, me, conditions))
                             passenger->ExitVehicle();
                 m_ConditionsTimer = VEHICLE_CONDITION_CHECK_TIME;
             }
             else
                 m_ConditionsTimer -= diff;
         }
References conditions, diff(), Vehicle::GetPassenger(), Unit::GetVehicleKit(), m_ConditionsTimer, CreatureAI::me, sConditionMgr, and VEHICLE_CONDITION_CHECK_TIME.
Member Data Documentation
conditions
ConditionList npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::conditions
Definition at line 156 of file boss_grand_champions.cpp.
Referenced by npc_toc5_player_vehicleAI(), and UpdateAI().
m_ConditionsTimer
uint16 npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::m_ConditionsTimer
Definition at line 157 of file boss_grand_champions.cpp.
Referenced by npc_toc5_player_vehicleAI(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/boss_grand_champions.cpp