Azerotcore-wotlk: StartMovementEvent Class Reference
StartMovementEvent Class Reference
Public Member Functions
StartMovementEvent (Creature *summoner, Creature *owner)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()
virtual ~BasicEvent ()
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Creature * _summoner
Creature * _owner
Detailed Description
Definition at line 493 of file boss_the_lich_king.cpp.
Constructor & Destructor Documentation
StartMovementEvent()
StartMovementEvent::StartMovementEvent (Creature * summoner, Creature * owner) inline
Definition at line 496 of file boss_the_lich_king.cpp.
 : _summoner(summoner), _owner(owner) {}
Member Function Documentation
Execute()
bool StartMovementEvent::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
Definition at line 498 of file boss_the_lich_king.cpp.
     {
         _owner->SetReactState(REACT_AGGRESSIVE);
         if (!_owner->getThreatMgr().isThreatListEmpty())
             if (Unit* target = _owner->SelectVictim())
                 _owner->AI()->AttackStart(target);
         if (!_owner->GetVictim())
             if (Unit* target = _summoner->AI()->SelectTarget(SELECT_TARGET_RANDOM, 0, NonTankLKTargetSelector(_summoner)))
                 _owner->AI()->AttackStart(target);
         _owner->AI()->DoZoneInCombat();
         return true;
     }
References _owner, _summoner, Creature::AI(), UnitAI::AttackStart(), CreatureAI::DoZoneInCombat(), Unit::getThreatMgr(), Unit::GetVictim(), ThreatMgr::isThreatListEmpty(), REACT_AGGRESSIVE, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Creature::SelectVictim(), and Creature::SetReactState().
Member Data Documentation
_owner
Creature* StartMovementEvent::_owner private
Definition at line 513 of file boss_the_lich_king.cpp.
Referenced by Execute().
_summoner
Creature* StartMovementEvent::_summoner private
Definition at line 512 of file boss_the_lich_king.cpp.
Referenced by Execute().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp