Azerotcore-wotlk: deps/mysqllite/include/mysql.h File Reference
mysql.h File Reference
#include <sys/types.h>
#include "mysql_version.h"
#include "mysql_com.h"
#include "mysql_time.h"
#include "my_list.h"
#include "typelib.h"
#include "my_alloc.h"
Classes
struct st_mysql_field
struct st_mysql_rows
struct st_mysql_data
struct st_mysql_options
struct character_set
struct st_mysql
struct st_mysql_res
struct st_mysql_parameters
struct st_mysql_bind
struct st_mysql_stmt
Macros
#define STDCALL
#define CLIENT_NET_READ_TIMEOUT 365*24*3600 /* Timeout on read */
#define CLIENT_NET_WRITE_TIMEOUT 365*24*3600 /* Timeout on write */
#define IS_PRI_KEY(n) ((n) & PRI_KEY_FLAG)
#define IS_NOT_NULL(n) ((n) & NOT_NULL_FLAG)
#define IS_BLOB(n) ((n) & BLOB_FLAG)
#define IS_NUM(t) (((t) <= MYSQL_TYPE_INT24 && (t) != MYSQL_TYPE_TIMESTAMP) || (t) == MYSQL_TYPE_YEAR || (t) == MYSQL_TYPE_NEWDECIMAL)
#define IS_LONGDATA(t) ((t) >= MYSQL_TYPE_TINY_BLOB && (t) <= MYSQL_TYPE_STRING)
#define MYSQL_COUNT_ERROR (~(my_ulonglong) 0)
#define ER_WARN_DATA_TRUNCATED WARN_DATA_TRUNCATED
#define MYSQL_CLIENT
#define max_allowed_packet (*mysql_get_parameters()->p_max_allowed_packet)
#define net_buffer_length (*mysql_get_parameters()->p_net_buffer_length)
#define mysql_library_init mysql_server_init
#define mysql_library_end mysql_server_end
#define LOCAL_INFILE_ERROR_LEN 512
#define MYSQL_NO_DATA 100
#define MYSQL_DATA_TRUNCATED 101
#define mysql_reload(mysql) mysql_refresh((mysql),REFRESH_GRANT)
#define HAVE_MYSQL_REAL_CONNECT
Typedefs
typedef char my_bool
typedef int my_socket
typedef struct st_mysql_field MYSQL_FIELD
typedef char ** MYSQL_ROW
typedef unsigned int MYSQL_FIELD_OFFSET
typedef unsigned long long my_ulonglong
typedef struct st_mysql_rows MYSQL_ROWS
typedef MYSQL_ROWS * MYSQL_ROW_OFFSET
typedef struct embedded_query_result EMBEDDED_QUERY_RESULT
typedef struct st_mysql_data MYSQL_DATA
typedef struct character_set MY_CHARSET_INFO
typedef struct st_mysql MYSQL
typedef struct st_mysql_res MYSQL_RES
typedef struct st_mysql_parameters MYSQL_PARAMETERS
typedef struct st_mysql_bind MYSQL_BIND
typedef struct st_mysql_stmt MYSQL_STMT
Enumerations
enum mysql_option {
MYSQL_OPT_CONNECT_TIMEOUT , MYSQL_OPT_COMPRESS , MYSQL_OPT_NAMED_PIPE , MYSQL_INIT_COMMAND ,
MYSQL_READ_DEFAULT_FILE , MYSQL_READ_DEFAULT_GROUP , MYSQL_SET_CHARSET_DIR , MYSQL_SET_CHARSET_NAME ,
MYSQL_OPT_LOCAL_INFILE , MYSQL_OPT_PROTOCOL , MYSQL_SHARED_MEMORY_BASE_NAME , MYSQL_OPT_READ_TIMEOUT ,
MYSQL_OPT_WRITE_TIMEOUT , MYSQL_OPT_USE_RESULT , MYSQL_OPT_USE_REMOTE_CONNECTION , MYSQL_OPT_USE_EMBEDDED_CONNECTION ,
MYSQL_OPT_GUESS_CONNECTION , MYSQL_SET_CLIENT_IP , MYSQL_SECURE_AUTH , MYSQL_REPORT_DATA_TRUNCATION ,
MYSQL_OPT_RECONNECT , MYSQL_OPT_SSL_VERIFY_SERVER_CERT , MYSQL_PLUGIN_DIR , MYSQL_DEFAULT_AUTH
}
enum mysql_status { MYSQL_STATUS_READY , MYSQL_STATUS_GET_RESULT , MYSQL_STATUS_USE_RESULT , MYSQL_STATUS_STATEMENT_GET_RESULT }
enum mysql_protocol_type {
MYSQL_PROTOCOL_DEFAULT , MYSQL_PROTOCOL_TCP , MYSQL_PROTOCOL_SOCKET , MYSQL_PROTOCOL_PIPE ,
MYSQL_PROTOCOL_MEMORY
}
enum enum_mysql_stmt_state { MYSQL_STMT_INIT_DONE = 1 , MYSQL_STMT_PREPARE_DONE , MYSQL_STMT_EXECUTE_DONE , MYSQL_STMT_FETCH_DONE }
enum enum_stmt_attr_type { STMT_ATTR_UPDATE_MAX_LENGTH , STMT_ATTR_CURSOR_TYPE , STMT_ATTR_PREFETCH_ROWS }
Functions
int STDCALL mysql_server_init (int argc, char **argv, char **groups)
void STDCALL mysql_server_end (void)
MYSQL_PARAMETERS *STDCALL mysql_get_parameters (void)
my_bool STDCALL mysql_thread_init (void)
void STDCALL mysql_thread_end (void)
my_ulonglong STDCALL mysql_num_rows (MYSQL_RES *res)
unsigned int STDCALL mysql_num_fields (MYSQL_RES *res)
my_bool STDCALL mysql_eof (MYSQL_RES *res)
MYSQL_FIELD *STDCALL mysql_fetch_field_direct (MYSQL_RES *res, unsigned int fieldnr)
MYSQL_FIELD *STDCALL mysql_fetch_fields (MYSQL_RES *res)
MYSQL_ROW_OFFSET STDCALL mysql_row_tell (MYSQL_RES *res)
MYSQL_FIELD_OFFSET STDCALL mysql_field_tell (MYSQL_RES *res)
unsigned int STDCALL mysql_field_count (MYSQL *mysql)
my_ulonglong STDCALL mysql_affected_rows (MYSQL *mysql)
my_ulonglong STDCALL mysql_insert_id (MYSQL *mysql)
unsigned int STDCALL mysql_errno (MYSQL *mysql)
const char *STDCALL mysql_error (MYSQL *mysql)
const char *STDCALL mysql_sqlstate (MYSQL *mysql)
unsigned int STDCALL mysql_warning_count (MYSQL *mysql)
const char *STDCALL mysql_info (MYSQL *mysql)
unsigned long STDCALL mysql_thread_id (MYSQL *mysql)
const char *STDCALL mysql_character_set_name (MYSQL *mysql)
int STDCALL mysql_set_character_set (MYSQL *mysql, const char *csname)
MYSQL *STDCALL mysql_init (MYSQL *mysql)
my_bool STDCALL mysql_ssl_set (MYSQL *mysql, const char *key, const char *cert, const char *ca, const char *capath, const char *cipher)
const char *STDCALL mysql_get_ssl_cipher (MYSQL *mysql)
my_bool STDCALL mysql_change_user (MYSQL *mysql, const char *user, const char *passwd, const char *db)
MYSQL *STDCALL mysql_real_connect (MYSQL *mysql, const char *host, const char *user, const char *passwd, const char *db, unsigned int port, const char *unix_socket, unsigned long clientflag)
int STDCALL mysql_select_db (MYSQL *mysql, const char *db)
int STDCALL mysql_query (MYSQL *mysql, const char *q)
int STDCALL mysql_send_query (MYSQL *mysql, const char *q, unsigned long length)
int STDCALL mysql_real_query (MYSQL *mysql, const char *q, unsigned long length)
MYSQL_RES *STDCALL mysql_store_result (MYSQL *mysql)
MYSQL_RES *STDCALL mysql_use_result (MYSQL *mysql)
void STDCALL mysql_get_character_set_info (MYSQL *mysql, MY_CHARSET_INFO *charset)
void mysql_set_local_infile_handler (MYSQL *mysql, int(*local_infile_init)(void **, const char *, void *), int(*local_infile_read)(void *, char *, unsigned int), void(*local_infile_end)(void *), int(*local_infile_error)(void *, char *, unsigned int), void *)
void mysql_set_local_infile_default (MYSQL *mysql)
int STDCALL mysql_shutdown (MYSQL *mysql, enum mysql_enum_shutdown_level shutdown_level)
int STDCALL mysql_dump_debug_info (MYSQL *mysql)
int STDCALL mysql_refresh (MYSQL *mysql, unsigned int refresh_options)
int STDCALL mysql_kill (MYSQL *mysql, unsigned long pid)
int STDCALL mysql_set_server_option (MYSQL *mysql, enum enum_mysql_set_option option)
int STDCALL mysql_ping (MYSQL *mysql)
const char *STDCALL mysql_stat (MYSQL *mysql)
const char *STDCALL mysql_get_server_info (MYSQL *mysql)
const char *STDCALL mysql_get_client_info (void)
unsigned long STDCALL mysql_get_client_version (void)
const char *STDCALL mysql_get_host_info (MYSQL *mysql)
unsigned long STDCALL mysql_get_server_version (MYSQL *mysql)
unsigned int STDCALL mysql_get_proto_info (MYSQL *mysql)
MYSQL_RES *STDCALL mysql_list_dbs (MYSQL *mysql, const char *wild)
MYSQL_RES *STDCALL mysql_list_tables (MYSQL *mysql, const char *wild)
MYSQL_RES *STDCALL mysql_list_processes (MYSQL *mysql)
int STDCALL mysql_options (MYSQL *mysql, enum mysql_option option, const void *arg)
void STDCALL mysql_free_result (MYSQL_RES *result)
void STDCALL mysql_data_seek (MYSQL_RES *result, my_ulonglong offset)
MYSQL_ROW_OFFSET STDCALL mysql_row_seek (MYSQL_RES *result, MYSQL_ROW_OFFSET offset)
MYSQL_FIELD_OFFSET STDCALL mysql_field_seek (MYSQL_RES *result, MYSQL_FIELD_OFFSET offset)
MYSQL_ROW STDCALL mysql_fetch_row (MYSQL_RES *result)
unsigned long *STDCALL mysql_fetch_lengths (MYSQL_RES *result)
MYSQL_FIELD *STDCALL mysql_fetch_field (MYSQL_RES *result)
MYSQL_RES *STDCALL mysql_list_fields (MYSQL *mysql, const char *table, const char *wild)
unsigned long STDCALL mysql_escape_string (char *to, const char *from, unsigned long from_length)
unsigned long STDCALL mysql_hex_string (char *to, const char *from, unsigned long from_length)
unsigned long STDCALL mysql_real_escape_string (MYSQL *mysql, char *to, const char *from, unsigned long length)
void STDCALL mysql_debug (const char *debug)
void STDCALL myodbc_remove_escape (MYSQL *mysql, char *name)
unsigned int STDCALL mysql_thread_safe (void)
my_bool STDCALL mysql_embedded (void)
my_bool STDCALL mysql_read_query_result (MYSQL *mysql)
MYSQL_STMT *STDCALL mysql_stmt_init (MYSQL *mysql)
int STDCALL mysql_stmt_prepare (MYSQL_STMT *stmt, const char *query, unsigned long length)
int STDCALL mysql_stmt_execute (MYSQL_STMT *stmt)
int STDCALL mysql_stmt_fetch (MYSQL_STMT *stmt)
int STDCALL mysql_stmt_fetch_column (MYSQL_STMT *stmt, MYSQL_BIND *bind_arg, unsigned int column, unsigned long offset)
int STDCALL mysql_stmt_store_result (MYSQL_STMT *stmt)
unsigned long STDCALL mysql_stmt_param_count (MYSQL_STMT *stmt)
my_bool STDCALL mysql_stmt_attr_set (MYSQL_STMT *stmt, enum enum_stmt_attr_type attr_type, const void *attr)
my_bool STDCALL mysql_stmt_attr_get (MYSQL_STMT *stmt, enum enum_stmt_attr_type attr_type, void *attr)
my_bool STDCALL mysql_stmt_bind_param (MYSQL_STMT *stmt, MYSQL_BIND *bnd)
my_bool STDCALL mysql_stmt_bind_result (MYSQL_STMT *stmt, MYSQL_BIND *bnd)
my_bool STDCALL mysql_stmt_close (MYSQL_STMT *stmt)
my_bool STDCALL mysql_stmt_reset (MYSQL_STMT *stmt)
my_bool STDCALL mysql_stmt_free_result (MYSQL_STMT *stmt)
my_bool STDCALL mysql_stmt_send_long_data (MYSQL_STMT *stmt, unsigned int param_number, const char *data, unsigned long length)
MYSQL_RES *STDCALL mysql_stmt_result_metadata (MYSQL_STMT *stmt)
MYSQL_RES *STDCALL mysql_stmt_param_metadata (MYSQL_STMT *stmt)
unsigned int STDCALL mysql_stmt_errno (MYSQL_STMT *stmt)
const char *STDCALL mysql_stmt_error (MYSQL_STMT *stmt)
const char *STDCALL mysql_stmt_sqlstate (MYSQL_STMT *stmt)
MYSQL_ROW_OFFSET STDCALL mysql_stmt_row_seek (MYSQL_STMT *stmt, MYSQL_ROW_OFFSET offset)
MYSQL_ROW_OFFSET STDCALL mysql_stmt_row_tell (MYSQL_STMT *stmt)
void STDCALL mysql_stmt_data_seek (MYSQL_STMT *stmt, my_ulonglong offset)
my_ulonglong STDCALL mysql_stmt_num_rows (MYSQL_STMT *stmt)
my_ulonglong STDCALL mysql_stmt_affected_rows (MYSQL_STMT *stmt)
my_ulonglong STDCALL mysql_stmt_insert_id (MYSQL_STMT *stmt)
unsigned int STDCALL mysql_stmt_field_count (MYSQL_STMT *stmt)
my_bool STDCALL mysql_commit (MYSQL *mysql)
my_bool STDCALL mysql_rollback (MYSQL *mysql)
my_bool STDCALL mysql_autocommit (MYSQL *mysql, my_bool auto_mode)
my_bool STDCALL mysql_more_results (MYSQL *mysql)
int STDCALL mysql_next_result (MYSQL *mysql)
int STDCALL mysql_stmt_next_result (MYSQL_STMT *stmt)
void STDCALL mysql_close (MYSQL *sock)
Variables
unsigned int mysql_port
char * mysql_unix_port
Macro Definition Documentation
CLIENT_NET_READ_TIMEOUT
#define CLIENT_NET_READ_TIMEOUT 365*24*3600 /* Timeout on read */
Definition at line 80 of file mysql.h.
CLIENT_NET_WRITE_TIMEOUT
#define CLIENT_NET_WRITE_TIMEOUT 365*24*3600 /* Timeout on write */
Definition at line 81 of file mysql.h.
ER_WARN_DATA_TRUNCATED
#define ER_WARN_DATA_TRUNCATED WARN_DATA_TRUNCATED
Definition at line 136 of file mysql.h.
HAVE_MYSQL_REAL_CONNECT
#define HAVE_MYSQL_REAL_CONNECT
Definition at line 707 of file mysql.h.
IS_BLOB
#define IS_BLOB (n) ((n) & BLOB_FLAG)
Definition at line 85 of file mysql.h.
IS_LONGDATA
#define IS_LONGDATA (t) ((t) >= MYSQL_TYPE_TINY_BLOB && (t) <= MYSQL_TYPE_STRING)
Definition at line 91 of file mysql.h.
IS_NOT_NULL
#define IS_NOT_NULL (n) ((n) & NOT_NULL_FLAG)
Definition at line 84 of file mysql.h.
IS_NUM
#define IS_NUM (t) (((t) <= MYSQL_TYPE_INT24 && (t) != MYSQL_TYPE_TIMESTAMP) || (t) == MYSQL_TYPE_YEAR || (t) == MYSQL_TYPE_NEWDECIMAL)
Returns true if the value is a number which does not need quotes for the sql_lex.cc parser to parse correctly.
Definition at line 90 of file mysql.h.
IS_PRI_KEY
#define IS_PRI_KEY (n) ((n) & PRI_KEY_FLAG)
Definition at line 83 of file mysql.h.
LOCAL_INFILE_ERROR_LEN
#define LOCAL_INFILE_ERROR_LEN 512
Definition at line 407 of file mysql.h.
max_allowed_packet
#define max_allowed_packet (*mysql_get_parameters()->p_max_allowed_packet)
Definition at line 318 of file mysql.h.
MYSQL_CLIENT
#define MYSQL_CLIENT
Definition at line 306 of file mysql.h.
MYSQL_COUNT_ERROR
#define MYSQL_COUNT_ERROR (~(my_ulonglong) 0)
Definition at line 133 of file mysql.h.
MYSQL_DATA_TRUNCATED
#define MYSQL_DATA_TRUNCATED 101
Definition at line 697 of file mysql.h.
mysql_library_end
#define mysql_library_end mysql_server_end
Definition at line 340 of file mysql.h.
mysql_library_init
#define mysql_library_init mysql_server_init
Definition at line 339 of file mysql.h.
MYSQL_NO_DATA
#define MYSQL_NO_DATA 100
Definition at line 696 of file mysql.h.
mysql_reload
#define mysql_reload (mysql) mysql_refresh((mysql),REFRESH_GRANT)
Definition at line 699 of file mysql.h.
net_buffer_length
#define net_buffer_length (*mysql_get_parameters()->p_net_buffer_length)
Definition at line 319 of file mysql.h.
STDCALL
#define STDCALL
Definition at line 57 of file mysql.h.
Typedef Documentation
EMBEDDED_QUERY_RESULT
typedef struct embedded_query_result EMBEDDED_QUERY_RESULT
Definition at line 144 of file mysql.h.
my_bool
typedef char my_bool
Definition at line 52 of file mysql.h.
MY_CHARSET_INFO
typedef struct character_set MY_CHARSET_INFO
my_socket
typedef int my_socket
Definition at line 66 of file mysql.h.
my_ulonglong
typedef unsigned long long my_ulonglong
Definition at line 127 of file mysql.h.
MYSQL
typedef struct st_mysql MYSQL
MYSQL_BIND
typedef struct st_mysql_bind MYSQL_BIND
MYSQL_DATA
typedef struct st_mysql_data MYSQL_DATA
MYSQL_FIELD
typedef struct st_mysql_field MYSQL_FIELD
MYSQL_FIELD_OFFSET
typedef unsigned int MYSQL_FIELD_OFFSET
Definition at line 119 of file mysql.h.
MYSQL_PARAMETERS
typedef struct st_mysql_parameters MYSQL_PARAMETERS
MYSQL_RES
typedef struct st_mysql_res MYSQL_RES
MYSQL_ROW
typedef char** MYSQL_ROW
Definition at line 118 of file mysql.h.
MYSQL_ROW_OFFSET
typedef MYSQL_ROWS* MYSQL_ROW_OFFSET
Definition at line 144 of file mysql.h.
MYSQL_ROWS
typedef struct st_mysql_rows MYSQL_ROWS
MYSQL_STMT
typedef struct st_mysql_stmt MYSQL_STMT
Enumeration Type Documentation
enum_mysql_stmt_state
enum enum_mysql_stmt_state
Enumerator
MYSQL_STMT_INIT_DONE
MYSQL_STMT_PREPARE_DONE
MYSQL_STMT_EXECUTE_DONE
MYSQL_STMT_FETCH_DONE
Definition at line 478 of file mysql.h.
 {
   MYSQL_STMT_INIT_DONE= 1, MYSQL_STMT_PREPARE_DONE, MYSQL_STMT_EXECUTE_DONE,
   MYSQL_STMT_FETCH_DONE
 };
enum_stmt_attr_type
enum enum_stmt_attr_type
Enumerator
STMT_ATTR_UPDATE_MAX_LENGTH
STMT_ATTR_CURSOR_TYPE
STMT_ATTR_PREFETCH_ROWS
Definition at line 624 of file mysql.h.
 {
   /*
     When doing mysql_stmt_store_result calculate max_length attribute
     of statement metadata. This is to be consistent with the old API,
     where this was done automatically.
     In the new API we do that only by request because it slows down
     mysql_stmt_store_result sufficiently.
   */
   STMT_ATTR_UPDATE_MAX_LENGTH,
   /*
     unsigned long with combination of cursor flags (read only, for update,
     etc)
   */
   STMT_ATTR_CURSOR_TYPE,
   /*
     Amount of rows to retrieve from server per one fetch if using cursors.
     Accepts unsigned long attribute in the range 1 - ulong_max
   */
   STMT_ATTR_PREFETCH_ROWS
 };
mysql_option
enum mysql_option
Enumerator
MYSQL_OPT_CONNECT_TIMEOUT
MYSQL_OPT_COMPRESS
MYSQL_OPT_NAMED_PIPE
MYSQL_INIT_COMMAND
MYSQL_READ_DEFAULT_FILE
MYSQL_READ_DEFAULT_GROUP
MYSQL_SET_CHARSET_DIR
MYSQL_SET_CHARSET_NAME
MYSQL_OPT_LOCAL_INFILE
MYSQL_OPT_PROTOCOL
MYSQL_SHARED_MEMORY_BASE_NAME
MYSQL_OPT_READ_TIMEOUT
MYSQL_OPT_WRITE_TIMEOUT
MYSQL_OPT_USE_RESULT
MYSQL_OPT_USE_REMOTE_CONNECTION
MYSQL_OPT_USE_EMBEDDED_CONNECTION
MYSQL_OPT_GUESS_CONNECTION
MYSQL_SET_CLIENT_IP
MYSQL_SECURE_AUTH
MYSQL_REPORT_DATA_TRUNCATION
MYSQL_OPT_RECONNECT
MYSQL_OPT_SSL_VERIFY_SERVER_CERT
MYSQL_PLUGIN_DIR
MYSQL_DEFAULT_AUTH
Definition at line 159 of file mysql.h.
 {
   MYSQL_OPT_CONNECT_TIMEOUT, MYSQL_OPT_COMPRESS, MYSQL_OPT_NAMED_PIPE,
   MYSQL_INIT_COMMAND, MYSQL_READ_DEFAULT_FILE, MYSQL_READ_DEFAULT_GROUP,
   MYSQL_SET_CHARSET_DIR, MYSQL_SET_CHARSET_NAME, MYSQL_OPT_LOCAL_INFILE,
   MYSQL_OPT_PROTOCOL, MYSQL_SHARED_MEMORY_BASE_NAME, MYSQL_OPT_READ_TIMEOUT,
   MYSQL_OPT_WRITE_TIMEOUT, MYSQL_OPT_USE_RESULT,
   MYSQL_OPT_USE_REMOTE_CONNECTION, MYSQL_OPT_USE_EMBEDDED_CONNECTION,
   MYSQL_OPT_GUESS_CONNECTION, MYSQL_SET_CLIENT_IP, MYSQL_SECURE_AUTH,
   MYSQL_REPORT_DATA_TRUNCATION, MYSQL_OPT_RECONNECT,
   MYSQL_OPT_SSL_VERIFY_SERVER_CERT, MYSQL_PLUGIN_DIR, MYSQL_DEFAULT_AUTH
 };
mysql_protocol_type
enum mysql_protocol_type
Enumerator
MYSQL_PROTOCOL_DEFAULT
MYSQL_PROTOCOL_TCP
MYSQL_PROTOCOL_SOCKET
MYSQL_PROTOCOL_PIPE
MYSQL_PROTOCOL_MEMORY
Definition at line 220 of file mysql.h.
 {
   MYSQL_PROTOCOL_DEFAULT, MYSQL_PROTOCOL_TCP, MYSQL_PROTOCOL_SOCKET,
   MYSQL_PROTOCOL_PIPE, MYSQL_PROTOCOL_MEMORY
 };
mysql_status
enum mysql_status
Enumerator
MYSQL_STATUS_READY
MYSQL_STATUS_GET_RESULT
MYSQL_STATUS_USE_RESULT
MYSQL_STATUS_STATEMENT_GET_RESULT
Definition at line 214 of file mysql.h.
 {
   MYSQL_STATUS_READY, MYSQL_STATUS_GET_RESULT, MYSQL_STATUS_USE_RESULT,
   MYSQL_STATUS_STATEMENT_GET_RESULT
 };
Function Documentation
myodbc_remove_escape()
void STDCALL myodbc_remove_escape (MYSQL * mysql, char * name)
Definition at line 1174 of file libmysql.c.
 {
   char *to;
 #ifdef USE_MB
   my_bool use_mb_flag=use_mb(mysql->charset);
   char *UNINIT_VAR(end);
   if (use_mb_flag)
     for (end=name; *end ; end++) ;
 #endif
   for (to=name ; *name ; name++)
   {
 #ifdef USE_MB
     int l;
     if (use_mb_flag && (l = my_ismbchar( mysql->charset, name , end ) ) )
     {
       while (l--)
     *to++ = *name++;
       name--;
       continue;
     }
 #endif
     if (*name == '\\' && name[1])
       name++;
     *to++= *name;
   }
   *to=0;
 }
References st_mysql::charset, mpq::l, my_ismbchar, UNINIT_VAR, and use_mb.
mysql_affected_rows()
my_ulonglong STDCALL mysql_affected_rows (MYSQL * mysql)
Definition at line 1034 of file libmysql.c.
 {
   return mysql->affected_rows;
 }
References st_mysql::affected_rows.
Referenced by MySQLConnection::_Query().
mysql_autocommit()
my_bool STDCALL mysql_autocommit (MYSQL * mysql, my_bool auto_mode)
Definition at line 4723 of file libmysql.c.
 {
   DBUG_ENTER("mysql_autocommit");
   DBUG_PRINT("enter", ("mode : %d", auto_mode));
   DBUG_RETURN((my_bool) mysql_real_query(mysql, auto_mode ?
                                          "set autocommit=1":"set autocommit=0",
                                          16));
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, and mysql_real_query().
Referenced by MySQLConnection::Open().
mysql_change_user()
my_bool STDCALL mysql_change_user (MYSQL * mysql, const char * user, const char * passwd, const char * db)
Definition at line 343 of file libmysql.c.
 {
   int rc;
   CHARSET_INFO *saved_cs= mysql->charset;
   char *saved_user= mysql->user;
   char *saved_passwd= mysql->passwd;
   char *saved_db= mysql->db;
   DBUG_ENTER("mysql_change_user");
   /* Get the connection-default character set. */
   if (mysql_init_character_set(mysql))
   {
     mysql->charset= saved_cs;
     DBUG_RETURN(TRUE);
   }
   /* Use an empty string instead of NULL. */
   mysql->user= (char*)(user ? user : "");
   mysql->passwd= (char*)(passwd ? passwd : "");
   mysql->db= 0;
   rc= run_plugin_auth(mysql, 0, 0, 0, db);
   /*
     The server will close all statements no matter was the attempt
     to change user successful or not.
   */
   mysql_detach_stmt_list(&mysql->stmts, "mysql_change_user");
   if (rc == 0)
   {
     /* Free old connect information */
     my_free(saved_user);
     my_free(saved_passwd);
     my_free(saved_db);
     /* alloc new connect information */
     mysql->user= my_strdup(mysql->user, MYF(MY_WME));
     mysql->passwd= my_strdup(mysql->passwd, MYF(MY_WME));
     mysql->db= db ? my_strdup(db, MYF(MY_WME)) : 0;
   }
   else
   {
     mysql->charset= saved_cs;
     mysql->user= saved_user;
     mysql->passwd= saved_passwd;
     mysql->db= saved_db;
   }
   DBUG_RETURN(rc);
 }
References st_mysql::charset, st_mysql::db, DBUG_ENTER, DBUG_RETURN, my_free(), my_strdup(), MY_WME, MYF, mysql_detach_stmt_list(), mysql_init_character_set(), st_mysql::passwd, run_plugin_auth(), st_mysql::stmts, TRUE, and st_mysql::user.
Referenced by native_password_auth_client(), and old_password_auth_client().
mysql_character_set_name()
const char* STDCALL mysql_character_set_name (MYSQL * mysql)
Definition at line 1064 of file libmysql.c.
 {
   return mysql->charset->csname;
 }
References st_mysql::charset, and charset_info_st::csname.
mysql_close()
void STDCALL mysql_close (MYSQL * sock)
Definition at line 3688 of file client.c.
 {
   DBUG_ENTER("mysql_close");
   if (mysql)                    /* Some simple safety */
   {
     /* If connection is still up, send a QUIT message */
     if (mysql->net.vio != 0)
     {
       free_old_query(mysql);
       mysql->status=MYSQL_STATUS_READY; /* Force command */
       mysql->reconnect=0;
       simple_command(mysql,COM_QUIT,(uchar*) 0,0,1);
       end_server(mysql);            /* Sets mysql->net.vio= 0 */
     }
     mysql_close_free_options(mysql);
     mysql_close_free(mysql);
     mysql_detach_stmt_list(&mysql->stmts, "mysql_close");
 #ifndef MYSQL_SERVER
     if (mysql->thd)
       (*mysql->methods->free_embedded_thd)(mysql);
 #endif
     if (mysql->free_me)
       my_free(mysql);
   }
   DBUG_VOID_RETURN;
 }
References COM_QUIT, DBUG_ENTER, DBUG_VOID_RETURN, end_server(), st_mysql_methods::free_embedded_thd, st_mysql::free_me, free_old_query(), st_mysql::methods, my_free(), mysql_close_free(), mysql_close_free_options(), mysql_detach_stmt_list(), MYSQL_STATUS_READY, st_mysql::net, st_mysql::reconnect, simple_command, st_mysql::status, st_mysql::stmts, st_mysql::thd, and st_net::vio.
Referenced by MySQLConnection::_HandleMySQLErrno(), MySQLConnection::Close(), mysql_reconnect(), and MySQLConnection::Open().
mysql_commit()
my_bool STDCALL mysql_commit (MYSQL * mysql)
Definition at line 4702 of file libmysql.c.
 {
   DBUG_ENTER("mysql_commit");
   DBUG_RETURN((my_bool) mysql_real_query(mysql, "commit", 6));
 }
References DBUG_ENTER, DBUG_RETURN, and mysql_real_query().
mysql_data_seek()
void STDCALL mysql_data_seek (MYSQL_RES * result, my_ulonglong offset)
Definition at line 721 of file libmysql.c.
 {
   MYSQL_ROWS    *tmp=0;
   DBUG_PRINT("info",("mysql_data_seek(%ld)",(long) row));
   if (result->data)
     for (tmp=result->data->data; row-- && tmp ; tmp = tmp->next) ;
   result->current_row=0;
   result->data_cursor = tmp;
 }
References DBUG_PRINT, and st_mysql_rows::next.
mysql_debug()
void STDCALL mysql_debug (const char * debug)
Referenced by mysql_read_default_options().
mysql_dump_debug_info()
int STDCALL mysql_dump_debug_info (MYSQL * mysql)
Definition at line 930 of file libmysql.c.
 {
   DBUG_ENTER("mysql_dump_debug_info");
   DBUG_RETURN(simple_command(mysql,COM_DEBUG,0,0,0));
 }
References COM_DEBUG, DBUG_ENTER, DBUG_RETURN, and simple_command.
mysql_embedded()
my_bool STDCALL mysql_embedded (void)
Definition at line 1091 of file libmysql.c.
 {
 #ifdef EMBEDDED_LIBRARY
   return 1;
 #else
   return 0;
 #endif
 }
mysql_eof()
my_bool STDCALL mysql_eof (MYSQL_RES * res)
Definition at line 1002 of file libmysql.c.
 {
   return res->eof;
 }
References st_mysql_res::eof.
mysql_errno()
unsigned int STDCALL mysql_errno (MYSQL * mysql)
Definition at line 4093 of file client.c.
 {
   return mysql ? mysql->net.last_errno : mysql_server_last_errno;
 }
References st_net::last_errno, mysql_server_last_errno, and st_mysql::net.
Referenced by MySQLConnection::_Query(), MySQLConnection::Execute(), MySQLConnection::GetLastError(), and MySQLConnection::Open().
mysql_error()
const char* STDCALL mysql_error (MYSQL * mysql)
Definition at line 4099 of file client.c.
 {
   return mysql ? mysql->net.last_error : mysql_server_last_error;
 }
References st_net::last_error, mysql_server_last_error, and st_mysql::net.
Referenced by MySQLConnection::_Query(), MySQLConnection::Execute(), ResultSet::NextRow(), MySQLConnection::Open(), and MySQLConnection::PrepareStatement().
mysql_escape_string()
unsigned long STDCALL mysql_escape_string (char * to, const char * from, unsigned long from_length)
Definition at line 1159 of file libmysql.c.
 {
   return (uint) escape_string_for_mysql(default_charset_info, to, 0, from, length);
 }
References default_charset_info, escape_string_for_mysql(), and G3D::length().
mysql_fetch_field()
MYSQL_FIELD* STDCALL mysql_fetch_field (MYSQL_RES * result)
Definition at line 708 of file libmysql.c.
 {
   if (result->current_field >= result->field_count)
     return(NULL);
   return &result->fields[result->current_field++];
 }
References NULL.
mysql_fetch_field_direct()
MYSQL_FIELD* STDCALL mysql_fetch_field_direct (MYSQL_RES * res, unsigned int fieldnr)
Definition at line 1007 of file libmysql.c.
 {
   return &(res)->fields[fieldnr];
 }
mysql_fetch_fields()
MYSQL_FIELD* STDCALL mysql_fetch_fields (MYSQL_RES * res)
Definition at line 1012 of file libmysql.c.
 {
   return (res)->fields;
 }
Referenced by MySQLConnection::_Query(), and PreparedResultSet::PreparedResultSet().
mysql_fetch_lengths()
unsigned long* STDCALL mysql_fetch_lengths (MYSQL_RES * result)
Definition at line 3972 of file client.c.
 {
   MYSQL_ROW column;
   if (!(column=res->current_row))
     return 0;                   /* Something is wrong */
   if (res->data)
     (*res->methods->fetch_lengths)(res->lengths, column, res->field_count);
   return res->lengths;
 }
References st_mysql_res::current_row, st_mysql_res::data, st_mysql_methods::fetch_lengths, st_mysql_res::field_count, st_mysql_res::lengths, and st_mysql_res::methods.
Referenced by ResultSet::NextRow().
mysql_fetch_row()
MYSQL_ROW STDCALL mysql_fetch_row (MYSQL_RES * result)
Definition at line 3917 of file client.c.
 {
   DBUG_ENTER("mysql_fetch_row");
   if (!res->data)
   {                     /* Unbufferred fetch */
     if (!res->eof)
     {
       MYSQL *mysql= res->handle;
       if (mysql->status != MYSQL_STATUS_USE_RESULT)
       {
         set_mysql_error(mysql,
                         res->unbuffered_fetch_cancelled ?
                         CR_FETCH_CANCELED : CR_COMMANDS_OUT_OF_SYNC,
                         unknown_sqlstate);
       }
       else if (!(read_one_row(mysql, res->field_count, res->row, res->lengths)))
       {
     res->row_count++;
     DBUG_RETURN(res->current_row=res->row);
       }
       DBUG_PRINT("info",("end of data"));
       res->eof=1;
       mysql->status=MYSQL_STATUS_READY;
       /*
         Reset only if owner points to us: there is a chance that somebody
         started new query after mysql_stmt_close():
       */
       if (mysql->unbuffered_fetch_owner == &res->unbuffered_fetch_cancelled)
         mysql->unbuffered_fetch_owner= 0;
       /* Don't clear handle in mysql_free_result */
       res->handle=0;
     }
     DBUG_RETURN((MYSQL_ROW) NULL);
   }
   {
     MYSQL_ROW tmp;
     if (!res->data_cursor)
     {
       DBUG_PRINT("info",("end of data"));
       DBUG_RETURN(res->current_row=(MYSQL_ROW) NULL);
     }
     tmp = res->data_cursor->data;
     res->data_cursor = res->data_cursor->next;
     DBUG_RETURN(res->current_row=tmp);
   }
 }
References CR_COMMANDS_OUT_OF_SYNC, CR_FETCH_CANCELED, st_mysql_res::current_row, st_mysql_rows::data, st_mysql_res::data, st_mysql_res::data_cursor, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, st_mysql_res::eof, st_mysql_res::field_count, st_mysql_res::handle, st_mysql_res::lengths, MYSQL_STATUS_READY, MYSQL_STATUS_USE_RESULT, st_mysql_rows::next, NULL, read_one_row(), st_mysql_res::row, st_mysql_res::row_count, set_mysql_error(), st_mysql::status, st_mysql_res::unbuffered_fetch_cancelled, st_mysql::unbuffered_fetch_owner, and unknown_sqlstate.
Referenced by ResultSet::NextRow().
mysql_field_count()
unsigned int STDCALL mysql_field_count (MYSQL * mysql)
Definition at line 1029 of file libmysql.c.
 {
   return mysql->field_count;
 }
References st_mysql::field_count.
Referenced by MySQLConnection::_Query().
mysql_field_seek()
MYSQL_FIELD_OFFSET STDCALL mysql_field_seek (MYSQL_RES * result, MYSQL_FIELD_OFFSET offset)
Definition at line 749 of file libmysql.c.
 {
   MYSQL_FIELD_OFFSET return_value=result->current_field;
   result->current_field=field_offset;
   return return_value;
 }
mysql_field_tell()
MYSQL_FIELD_OFFSET STDCALL mysql_field_tell (MYSQL_RES * res)
Definition at line 1022 of file libmysql.c.
 {
   return (res)->current_field;
 }
mysql_free_result()
void STDCALL mysql_free_result (MYSQL_RES * result)
Definition at line 1098 of file client.c.
 {
   DBUG_ENTER("mysql_free_result");
   DBUG_PRINT("enter",("mysql_res: 0x%lx", (long) result));
   if (result)
   {
     MYSQL *mysql= result->handle;
     if (mysql)
     {
       if (mysql->unbuffered_fetch_owner == &result->unbuffered_fetch_cancelled)
         mysql->unbuffered_fetch_owner= 0;
       if (mysql->status == MYSQL_STATUS_USE_RESULT)
       {
         (*mysql->methods->flush_use_result)(mysql, FALSE);
         mysql->status=MYSQL_STATUS_READY;
         if (mysql->unbuffered_fetch_owner)
           *mysql->unbuffered_fetch_owner= TRUE;
       }
     }
     free_rows(result->data);
     if (result->fields)
       free_root(&result->field_alloc,MYF(0));
     my_free(result->row);
     my_free(result);
   }
   DBUG_VOID_RETURN;
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, FALSE, st_mysql_methods::flush_use_result, free_root(), free_rows(), st_mysql::methods, my_free(), MYF, MYSQL_STATUS_READY, MYSQL_STATUS_USE_RESULT, st_mysql::status, TRUE, and st_mysql::unbuffered_fetch_owner.
Referenced by MySQLConnection::_Query(), ResultSet::CleanUp(), PreparedResultSet::CleanUp(), and CLI_MYSQL_REAL_CONNECT().
mysql_get_character_set_info()
void STDCALL mysql_get_character_set_info (MYSQL * mysql, MY_CHARSET_INFO * charset)
Definition at line 1069 of file libmysql.c.
 {
   csinfo->number   = mysql->charset->number;
   csinfo->state    = mysql->charset->state;
   csinfo->csname   = mysql->charset->csname;
   csinfo->name     = mysql->charset->name;
   csinfo->comment  = mysql->charset->comment;
   csinfo->mbminlen = mysql->charset->mbminlen;
   csinfo->mbmaxlen = mysql->charset->mbmaxlen;
   if (mysql->options.charset_dir)
     csinfo->dir = mysql->options.charset_dir;
   else
     csinfo->dir = charsets_dir;
 }
References st_mysql::charset, st_mysql_options::charset_dir, charsets_dir, charset_info_st::comment, character_set::comment, charset_info_st::csname, character_set::csname, character_set::dir, charset_info_st::mbmaxlen, character_set::mbmaxlen, charset_info_st::mbminlen, character_set::mbminlen, charset_info_st::name, character_set::name, charset_info_st::number, character_set::number, st_mysql::options, charset_info_st::state, and character_set::state.
mysql_get_client_info()
const char* STDCALL mysql_get_client_info (void)
Definition at line 992 of file libmysql.c.
 {
   return (char*) MYSQL_SERVER_VERSION;
 }
Referenced by DatabaseWorkerPool< T >::DatabaseWorkerPool(), and MySQLConnection::Open().
mysql_get_client_version()
unsigned long STDCALL mysql_get_client_version (void)
Definition at line 997 of file libmysql.c.
 {
   return MYSQL_VERSION_ID;
 }
Referenced by DatabaseWorkerPool< T >::DatabaseWorkerPool().
mysql_get_host_info()
const char* STDCALL mysql_get_host_info (MYSQL * mysql)
Definition at line 979 of file libmysql.c.
 {
   return(mysql->host_info);
 }
References st_mysql::host_info.
mysql_get_parameters()
MYSQL_PARAMETERS* STDCALL mysql_get_parameters (void)
Definition at line 223 of file libmysql.c.
 {
   return &mysql_internal_parameters;
 }
References mysql_internal_parameters.
mysql_get_proto_info()
unsigned int STDCALL mysql_get_proto_info (MYSQL * mysql)
Definition at line 986 of file libmysql.c.
 {
   return (mysql->protocol_version);
 }
References st_mysql::protocol_version.
mysql_get_server_info()
const char* STDCALL mysql_get_server_info (MYSQL * mysql)
Definition at line 972 of file libmysql.c.
 {
   return((char*) mysql->server_version);
 }
References st_mysql::server_version.
Referenced by MySQLConnection::Open().
mysql_get_server_version()
unsigned long STDCALL mysql_get_server_version (MYSQL * mysql)
Definition at line 4123 of file client.c.
 {
   uint major, minor, version;
   char *pos= mysql->server_version, *end_pos;
   major=   (uint) strtoul(pos, &end_pos, 10);   pos=end_pos+1;
   minor=   (uint) strtoul(pos, &end_pos, 10);   pos=end_pos+1;
   version= (uint) strtoul(pos, &end_pos, 10);
   return (ulong) major*10000L+(ulong) (minor*100+version);
 }
References pos(), st_mysql::server_version, strtoul(), and setup::version.
Referenced by MySQLConnection::GetServerVersion(), and mysql_set_character_set().
mysql_get_ssl_cipher()
const char* STDCALL mysql_get_ssl_cipher (MYSQL * mysql)
mysql_hex_string()
unsigned long STDCALL mysql_hex_string (char * to, const char * from, unsigned long from_length)
Definition at line 1138 of file libmysql.c.
 {
   char *to0= to;
   const char *end;
   for (end= from + length; from < end; from++)
   {
     *to++= _dig_vec_upper[((unsigned char) *from) >> 4];
     *to++= _dig_vec_upper[((unsigned char) *from) & 0x0F];
   }
   *to= '\0';
   return (ulong) (to-to0);
 }
References _dig_vec_upper, and G3D::length().
mysql_info()
const char* STDCALL mysql_info (MYSQL * mysql)
Definition at line 1054 of file libmysql.c.
 {
   return mysql->info;
 }
References st_mysql::info.
mysql_init()
MYSQL* STDCALL mysql_init (MYSQL * mysql)
Definition at line 1694 of file client.c.
 {
   if (mysql_server_init(0, NULL, NULL))
     return 0;
   if (!mysql)
   {
     if (!(mysql=(MYSQL*) my_malloc(sizeof(*mysql),MYF(MY_WME | MY_ZEROFILL))))
     {
       set_mysql_error(NULL, CR_OUT_OF_MEMORY, unknown_sqlstate);
       return 0;
     }
     mysql->free_me=1;
   }
   else
     bzero((char*) (mysql), sizeof(*(mysql)));
   mysql->options.connect_timeout= CONNECT_TIMEOUT;
   mysql->charset=default_client_charset_info;
   strmov(mysql->net.sqlstate, not_error_sqlstate);
   /*
     Only enable LOAD DATA INFILE by default if configured with
     --enable-local-infile
   */
 #if defined(ENABLED_LOCAL_INFILE) && !defined(MYSQL_SERVER)
   mysql->options.client_flag|= CLIENT_LOCAL_FILES;
 #endif
 #ifdef HAVE_SMEM
   mysql->options.shared_memory_base_name= (char*) def_shared_memory_base_name;
 #endif
   mysql->options.methods_to_use= MYSQL_OPT_GUESS_CONNECTION;
   mysql->options.report_data_truncation= TRUE;  /* default */
   /*
     By default we don't reconnect because it could silently corrupt data (after
     reconnection you potentially lose table locks, user variables, session
     variables (transactions but they are specifically dealt with in
     mysql_reconnect()).
     This is a change: < 5.0.3 mysql->reconnect was set to 1 by default.
     How this change impacts existing apps:
     - existing apps which relyed on the default will see a behaviour change;
     they will have to set reconnect=1 after mysql_real_connect().
     - existing apps which explicitely asked for reconnection (the only way they
     could do it was by setting mysql.reconnect to 1 after mysql_real_connect())
     will not see a behaviour change.
     - existing apps which explicitely asked for no reconnection
     (mysql.reconnect=0) will not see a behaviour change.
   */
   mysql->reconnect= 0;
   return mysql;
 }
References bzero, st_mysql::charset, st_mysql_options::client_flag, CLIENT_LOCAL_FILES, st_mysql_options::connect_timeout, CONNECT_TIMEOUT, CR_OUT_OF_MEMORY, default_client_charset_info, st_mysql::free_me, st_mysql_options::methods_to_use, my_malloc(), MY_WME, MY_ZEROFILL, MYF, MYSQL_OPT_GUESS_CONNECTION, mysql_server_init(), st_mysql::net, not_error_sqlstate, NULL, st_mysql::options, st_mysql::reconnect, st_mysql_options::report_data_truncation, set_mysql_error(), st_mysql_options::shared_memory_base_name, st_net::sqlstate, strmov(), TRUE, and unknown_sqlstate.
Referenced by mysql_reconnect(), and MySQLConnection::Open().
mysql_insert_id()
my_ulonglong STDCALL mysql_insert_id (MYSQL * mysql)
Definition at line 1039 of file libmysql.c.
 {
   return mysql->insert_id;
 }
References st_mysql::insert_id.
mysql_kill()
int STDCALL mysql_kill (MYSQL * mysql, unsigned long pid)
Definition at line 910 of file libmysql.c.
 {
   uchar buff[4];
   DBUG_ENTER("mysql_kill");
   int4store(buff,pid);
   DBUG_RETURN(simple_command(mysql,COM_PROCESS_KILL,buff,sizeof(buff),0));
 }
References COM_PROCESS_KILL, DBUG_ENTER, DBUG_RETURN, int4store, and simple_command.
mysql_list_dbs()
MYSQL_RES* STDCALL mysql_list_dbs (MYSQL * mysql, const char * wild)
Definition at line 762 of file libmysql.c.
 {
   char buff[255];
   DBUG_ENTER("mysql_list_dbs");
   append_wild(strmov(buff,"show databases"),buff+sizeof(buff),wild);
   if (mysql_query(mysql,buff))
     DBUG_RETURN(0);
   DBUG_RETURN (mysql_store_result(mysql));
 }
References append_wild(), DBUG_ENTER, DBUG_RETURN, mysql_query(), mysql_store_result(), and strmov().
mysql_list_fields()
MYSQL_RES* STDCALL mysql_list_fields (MYSQL * mysql, const char * table, const char * wild)
Definition at line 813 of file libmysql.c.
 {
   MYSQL_RES   *result;
   MYSQL_FIELD *fields;
   char       buff[258],*end;
   DBUG_ENTER("mysql_list_fields");
   DBUG_PRINT("enter",("table: '%s'  wild: '%s'",table,wild ? wild : ""));
   end=strmake(strmake(buff, table,128)+1,wild ? wild : "",128);
   free_old_query(mysql);
   if (simple_command(mysql, COM_FIELD_LIST, (uchar*) buff,
                      (ulong) (end-buff), 1) ||
       !(fields= (*mysql->methods->list_fields)(mysql)))
     DBUG_RETURN(NULL);
   if (!(result = (MYSQL_RES *) my_malloc(sizeof(MYSQL_RES),
                      MYF(MY_WME | MY_ZEROFILL))))
     DBUG_RETURN(NULL);
   result->methods= mysql->methods;
   result->field_alloc=mysql->field_alloc;
   mysql->fields=0;
   result->field_count = mysql->field_count;
   result->fields= fields;
   result->eof=1;
   DBUG_RETURN(result);
 }
References COM_FIELD_LIST, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, st_mysql::field_alloc, st_mysql::field_count, st_mysql::fields, free_old_query(), st_mysql_methods::list_fields, st_mysql::methods, my_malloc(), MY_WME, MY_ZEROFILL, MYF, NULL, simple_command, and strmake().
mysql_list_processes()
MYSQL_RES* STDCALL mysql_list_processes (MYSQL * mysql)
Definition at line 844 of file libmysql.c.
 {
   MYSQL_DATA *fields;
   uint field_count;
   uchar *pos;
   DBUG_ENTER("mysql_list_processes");
   LINT_INIT(fields);
   if (simple_command(mysql,COM_PROCESS_INFO,0,0,0))
     DBUG_RETURN(0);
   free_old_query(mysql);
   pos=(uchar*) mysql->net.read_pos;
   field_count=(uint) net_field_length(&pos);
   if (!(fields = (*mysql->methods->read_rows)(mysql,(MYSQL_FIELD*) 0,
                           protocol_41(mysql) ? 7 : 5)))
     DBUG_RETURN(NULL);
   if (!(mysql->fields=unpack_fields(fields,&mysql->field_alloc,field_count,0,
                     mysql->server_capabilities)))
     DBUG_RETURN(0);
   mysql->status=MYSQL_STATUS_GET_RESULT;
   mysql->field_count=field_count;
   DBUG_RETURN(mysql_store_result(mysql));
 }
References COM_PROCESS_INFO, DBUG_ENTER, DBUG_RETURN, st_mysql::field_alloc, st_mysql::field_count, st_mysql::fields, free_old_query(), LINT_INIT, st_mysql::methods, MYSQL_STATUS_GET_RESULT, mysql_store_result(), st_mysql::net, net_field_length(), NULL, pos(), protocol_41, st_net::read_pos, st_mysql_methods::read_rows, st_mysql::server_capabilities, simple_command, st_mysql::status, and unpack_fields().
mysql_list_tables()
MYSQL_RES* STDCALL mysql_list_tables (MYSQL * mysql, const char * wild)
Definition at line 780 of file libmysql.c.
 {
   char buff[255];
   DBUG_ENTER("mysql_list_tables");
   append_wild(strmov(buff,"show tables"),buff+sizeof(buff),wild);
   if (mysql_query(mysql,buff))
     DBUG_RETURN(0);
   DBUG_RETURN (mysql_store_result(mysql));
 }
References append_wild(), DBUG_ENTER, DBUG_RETURN, mysql_query(), mysql_store_result(), and strmov().
mysql_more_results()
my_bool STDCALL mysql_more_results (MYSQL * mysql)
Definition at line 4743 of file libmysql.c.
 {
   my_bool res;
   DBUG_ENTER("mysql_more_results");
   res= ((mysql->server_status & SERVER_MORE_RESULTS_EXISTS) ? 1: 0);
   DBUG_PRINT("exit",("More results exists ? %d", res));
   DBUG_RETURN(res);
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, SERVER_MORE_RESULTS_EXISTS, and st_mysql::server_status.
Referenced by MySQLConnection::Query().
mysql_next_result()
int STDCALL mysql_next_result (MYSQL * mysql)
Definition at line 4757 of file libmysql.c.
 {
   DBUG_ENTER("mysql_next_result");
   if (mysql->status != MYSQL_STATUS_READY)
   {
     set_mysql_error(mysql, CR_COMMANDS_OUT_OF_SYNC, unknown_sqlstate);
     DBUG_RETURN(1);
   }
   net_clear_error(&mysql->net);
   mysql->affected_rows= ~(my_ulonglong) 0;
   if (mysql->server_status & SERVER_MORE_RESULTS_EXISTS)
     DBUG_RETURN((*mysql->methods->next_result)(mysql));
   DBUG_RETURN(-1);              /* No more results */
 }
References st_mysql::affected_rows, CR_COMMANDS_OUT_OF_SYNC, DBUG_ENTER, DBUG_RETURN, st_mysql::methods, MYSQL_STATUS_READY, st_mysql::net, net_clear_error(), st_mysql_methods::next_result, SERVER_MORE_RESULTS_EXISTS, st_mysql::server_status, set_mysql_error(), st_mysql::status, and unknown_sqlstate.
Referenced by CLI_MYSQL_REAL_CONNECT(), mysql_stmt_next_result(), and MySQLConnection::Query().
mysql_num_fields()
unsigned int STDCALL mysql_num_fields (MYSQL_RES * res)
Definition at line 4088 of file client.c.
 {
   return res->field_count;
 }
References st_mysql_res::field_count.
mysql_num_rows()
my_ulonglong STDCALL mysql_num_rows (MYSQL_RES * res)
Definition at line 4083 of file client.c.
 {
   return res->row_count;
 }
References st_mysql_res::row_count.
mysql_options()
int STDCALL mysql_options (MYSQL * mysql, enum mysql_option option, const void * arg)
Definition at line 3985 of file client.c.
 {
   DBUG_ENTER("mysql_option");
   DBUG_PRINT("enter",("option: %d",(int) option));
   switch (option) {
   case MYSQL_OPT_CONNECT_TIMEOUT:
     mysql->options.connect_timeout= *(uint*) arg;
     break;
   case MYSQL_OPT_READ_TIMEOUT:
     mysql->options.read_timeout= *(uint*) arg;
     break;
   case MYSQL_OPT_WRITE_TIMEOUT:
     mysql->options.write_timeout= *(uint*) arg;
     break;
   case MYSQL_OPT_COMPRESS:
     mysql->options.compress= 1;         /* Remember for connect */
     mysql->options.client_flag|= CLIENT_COMPRESS;
     break;
   case MYSQL_OPT_NAMED_PIPE:            /* This option is depricated */
     mysql->options.protocol=MYSQL_PROTOCOL_PIPE; /* Force named pipe */
     break;
   case MYSQL_OPT_LOCAL_INFILE:          /* Allow LOAD DATA LOCAL ?*/
     if (!arg || test(*(uint*) arg))
       mysql->options.client_flag|= CLIENT_LOCAL_FILES;
     else
       mysql->options.client_flag&= ~CLIENT_LOCAL_FILES;
     break;
   case MYSQL_INIT_COMMAND:
     add_init_command(&mysql->options,arg);
     break;
   case MYSQL_READ_DEFAULT_FILE:
     my_free(mysql->options.my_cnf_file);
     mysql->options.my_cnf_file=my_strdup(arg,MYF(MY_WME));
     break;
   case MYSQL_READ_DEFAULT_GROUP:
     my_free(mysql->options.my_cnf_group);
     mysql->options.my_cnf_group=my_strdup(arg,MYF(MY_WME));
     break;
   case MYSQL_SET_CHARSET_DIR:
     my_free(mysql->options.charset_dir);
     mysql->options.charset_dir=my_strdup(arg,MYF(MY_WME));
     break;
   case MYSQL_SET_CHARSET_NAME:
     my_free(mysql->options.charset_name);
     mysql->options.charset_name=my_strdup(arg,MYF(MY_WME));
     break;
   case MYSQL_OPT_PROTOCOL:
     mysql->options.protocol= *(uint*) arg;
     break;
   case MYSQL_SHARED_MEMORY_BASE_NAME:
 #ifdef HAVE_SMEM
     if (mysql->options.shared_memory_base_name != def_shared_memory_base_name)
       my_free(mysql->options.shared_memory_base_name);
     mysql->options.shared_memory_base_name=my_strdup(arg,MYF(MY_WME));
 #endif
     break;
   case MYSQL_OPT_USE_REMOTE_CONNECTION:
   case MYSQL_OPT_USE_EMBEDDED_CONNECTION:
   case MYSQL_OPT_GUESS_CONNECTION:
     mysql->options.methods_to_use= option;
     break;
   case MYSQL_SET_CLIENT_IP:
     mysql->options.client_ip= my_strdup(arg, MYF(MY_WME));
     break;
   case MYSQL_SECURE_AUTH:
     mysql->options.secure_auth= *(my_bool *) arg;
     break;
   case MYSQL_REPORT_DATA_TRUNCATION:
     mysql->options.report_data_truncation= test(*(my_bool *) arg);
     break;
   case MYSQL_OPT_RECONNECT:
     mysql->reconnect= *(my_bool *) arg;
     break;
   case MYSQL_OPT_SSL_VERIFY_SERVER_CERT:
     if (*(my_bool*) arg)
       mysql->options.client_flag|= CLIENT_SSL_VERIFY_SERVER_CERT;
     else
       mysql->options.client_flag&= ~CLIENT_SSL_VERIFY_SERVER_CERT;
     break;
   case MYSQL_PLUGIN_DIR:
     EXTENSION_SET_STRING(&mysql->options, plugin_dir, arg);
     break;
   case MYSQL_DEFAULT_AUTH:
     EXTENSION_SET_STRING(&mysql->options, default_auth, arg);
     break;
   default:
     DBUG_RETURN(1);
   }
   DBUG_RETURN(0);
 }
References add_init_command(), arg(), st_mysql_options::charset_dir, st_mysql_options::charset_name, CLIENT_COMPRESS, st_mysql_options::client_flag, st_mysql_options::client_ip, CLIENT_LOCAL_FILES, CLIENT_SSL_VERIFY_SERVER_CERT, st_mysql_options::compress, st_mysql_options::connect_timeout, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EXTENSION_SET_STRING, st_mysql_options::methods_to_use, st_mysql_options::my_cnf_file, st_mysql_options::my_cnf_group, my_free(), my_strdup(), MY_WME, MYF, MYSQL_DEFAULT_AUTH, MYSQL_INIT_COMMAND, MYSQL_OPT_COMPRESS, MYSQL_OPT_CONNECT_TIMEOUT, MYSQL_OPT_GUESS_CONNECTION, MYSQL_OPT_LOCAL_INFILE, MYSQL_OPT_NAMED_PIPE, MYSQL_OPT_PROTOCOL, MYSQL_OPT_READ_TIMEOUT, MYSQL_OPT_RECONNECT, MYSQL_OPT_SSL_VERIFY_SERVER_CERT, MYSQL_OPT_USE_EMBEDDED_CONNECTION, MYSQL_OPT_USE_REMOTE_CONNECTION, MYSQL_OPT_WRITE_TIMEOUT, MYSQL_PLUGIN_DIR, MYSQL_PROTOCOL_PIPE, MYSQL_READ_DEFAULT_FILE, MYSQL_READ_DEFAULT_GROUP, MYSQL_REPORT_DATA_TRUNCATION, MYSQL_SECURE_AUTH, MYSQL_SET_CHARSET_DIR, MYSQL_SET_CHARSET_NAME, MYSQL_SET_CLIENT_IP, MYSQL_SHARED_MEMORY_BASE_NAME, st_mysql::options, st_mysql_options::protocol, st_mysql_options::read_timeout, st_mysql::reconnect, st_mysql_options::report_data_truncation, st_mysql_options::secure_auth, st_mysql_options::shared_memory_base_name, test, and st_mysql_options::write_timeout.
Referenced by MySQLConnection::Open().
mysql_ping()
int STDCALL mysql_ping (MYSQL * mysql)
Definition at line 960 of file libmysql.c.
 {
   int res;
   DBUG_ENTER("mysql_ping");
   res= simple_command(mysql,COM_PING,0,0,0);
   if (res == CR_SERVER_LOST && mysql->reconnect)
     res= simple_command(mysql,COM_PING,0,0,0);
   DBUG_RETURN(res);
 }
References COM_PING, CR_SERVER_LOST, DBUG_ENTER, DBUG_RETURN, st_mysql::reconnect, and simple_command.
Referenced by MySQLConnection::Ping().
mysql_query()
int STDCALL mysql_query (MYSQL * mysql, const char * q)
Definition at line 697 of file libmysql.c.
 {
   return mysql_real_query(mysql,query, (uint) strlen(query));
 }
References mysql_real_query().
Referenced by MySQLConnection::_Query(), MySQLConnection::Execute(), mysql_list_dbs(), and mysql_list_tables().
mysql_read_query_result()
my_bool STDCALL mysql_read_query_result (MYSQL * mysql)
Definition at line 4828 of file libmysql.c.
 {
   return (*mysql->methods->read_query_result)(mysql);
 }
References st_mysql::methods, and st_mysql_methods::read_query_result.
mysql_real_connect()
MYSQL* STDCALL mysql_real_connect (MYSQL * mysql, const char * host, const char * user, const char * passwd, const char * db, unsigned int port, const char * unix_socket, unsigned long clientflag)
Referenced by mysql_reconnect(), and MySQLConnection::Open().
mysql_real_escape_string()
unsigned long STDCALL mysql_real_escape_string (MYSQL * mysql, char * to, const char * from, unsigned long length)
Definition at line 1165 of file libmysql.c.
 {
   if (mysql->server_status & SERVER_STATUS_NO_BACKSLASH_ESCAPES)
     return (uint) escape_quotes_for_mysql(mysql->charset, to, 0, from, length);
   return (uint) escape_string_for_mysql(mysql->charset, to, 0, from, length);
 }
References st_mysql::charset, escape_quotes_for_mysql(), escape_string_for_mysql(), G3D::length(), st_mysql::server_status, and SERVER_STATUS_NO_BACKSLASH_ESCAPES.
Referenced by MySQLConnection::EscapeString().
mysql_real_query()
int STDCALL mysql_real_query (MYSQL * mysql, const char * q, unsigned long length)
Definition at line 3803 of file client.c.
 {
   DBUG_ENTER("mysql_real_query");
   DBUG_PRINT("enter",("handle: 0x%lx", (long) mysql));
   DBUG_PRINT("query",("Query = '%-.4096s'",query));
   if (mysql_send_query(mysql,query,length))
     DBUG_RETURN(1);
   DBUG_RETURN((int) (*mysql->methods->read_query_result)(mysql));
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, G3D::length(), st_mysql::methods, mysql_send_query(), and st_mysql_methods::read_query_result.
Referenced by CLI_MYSQL_REAL_CONNECT(), mysql_autocommit(), mysql_commit(), mysql_query(), mysql_rollback(), and mysql_set_character_set().
mysql_refresh()
int STDCALL mysql_refresh (MYSQL * mysql, unsigned int refresh_options)
Definition at line 900 of file libmysql.c.
 {
   uchar bits[1];
   DBUG_ENTER("mysql_refresh");
   bits[0]= (uchar) options;
   DBUG_RETURN(simple_command(mysql, COM_REFRESH, bits, 1, 0));
 }
References G3D::bits(), COM_REFRESH, DBUG_ENTER, DBUG_RETURN, and simple_command.
mysql_rollback()
my_bool STDCALL mysql_rollback (MYSQL * mysql)
Definition at line 4712 of file libmysql.c.
 {
   DBUG_ENTER("mysql_rollback");
   DBUG_RETURN((my_bool) mysql_real_query(mysql, "rollback", 8));
 }
References DBUG_ENTER, DBUG_RETURN, and mysql_real_query().
mysql_row_seek()
MYSQL_ROW_OFFSET STDCALL mysql_row_seek (MYSQL_RES * result, MYSQL_ROW_OFFSET offset)
Definition at line 739 of file libmysql.c.
 {
   MYSQL_ROW_OFFSET return_value=result->data_cursor;
   result->current_row= 0;
   result->data_cursor= row;
   return return_value;
 }
mysql_row_tell()
MYSQL_ROW_OFFSET STDCALL mysql_row_tell (MYSQL_RES * res)
Definition at line 1017 of file libmysql.c.
 {
   return res->data_cursor;
 }
References st_mysql_res::data_cursor.
mysql_select_db()
int STDCALL mysql_select_db (MYSQL * mysql, const char * db)
Definition at line 3533 of file client.c.
 {
   int error;
   DBUG_ENTER("mysql_select_db");
   DBUG_PRINT("enter",("db: '%s'",db));
   if ((error=simple_command(mysql,COM_INIT_DB, (const uchar*) db,
                             (ulong) strlen(db),0)))
     DBUG_RETURN(error);
   my_free(mysql->db);
   mysql->db=my_strdup(db,MYF(MY_WME));
   DBUG_RETURN(0);
 }
References COM_INIT_DB, st_mysql::db, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, error(), my_free(), my_strdup(), MY_WME, MYF, and simple_command.
Referenced by CLI_MYSQL_REAL_CONNECT().
mysql_send_query()
int STDCALL mysql_send_query (MYSQL * mysql, const char * q, unsigned long length)
Definition at line 3795 of file client.c.
 {
   DBUG_ENTER("mysql_send_query");
   DBUG_RETURN(simple_command(mysql, COM_QUERY, (uchar*) query, length, 1));
 }
References COM_QUERY, DBUG_ENTER, DBUG_RETURN, G3D::length(), and simple_command.
Referenced by mysql_real_query().
mysql_server_end()
void STDCALL mysql_server_end (void)
Definition at line 193 of file libmysql.c.
 {
   if (!mysql_client_init)
     return;
   mysql_client_plugin_deinit();
 #ifdef EMBEDDED_LIBRARY
   end_embedded_server();
 #endif
   finish_client_errs();
   vio_end();
   /* If library called my_init(), free memory allocated by it */
   if (!org_my_init_done)
   {
     my_end(0);
   }
   else
   {
     free_charsets();
     mysql_thread_end();
   }
   mysql_client_init= org_my_init_done= 0;
 }
References finish_client_errs(), free_charsets(), my_end(), mysql_client_init, mysql_client_plugin_deinit(), mysql_thread_end(), org_my_init_done, and vio_end().
mysql_server_init()
int STDCALL mysql_server_init (int argc, char ** argv, char ** groups)
Referenced by mysql_init().
mysql_set_character_set()
int STDCALL mysql_set_character_set (MYSQL * mysql, const char * csname)
Definition at line 4140 of file client.c.
 {
   struct charset_info_st *cs;
   const char *save_csdir= charsets_dir;
   if (mysql->options.charset_dir)
     charsets_dir= mysql->options.charset_dir;
   if (strlen(cs_name) < MY_CS_NAME_SIZE &&
      (cs= get_charset_by_csname(cs_name, MY_CS_PRIMARY, MYF(0))))
   {
     char buff[MY_CS_NAME_SIZE + 10];
     charsets_dir= save_csdir;
     /* Skip execution of "SET NAMES" for pre-4.1 servers */
     if (mysql_get_server_version(mysql) < 40100)
       return 0;
     sprintf(buff, "SET NAMES %s", cs_name);
     if (!mysql_real_query(mysql, buff, (uint) strlen(buff)))
     {
       mysql->charset= cs;
     }
   }
   else
   {
     char cs_dir_name[FN_REFLEN];
     get_charsets_dir(cs_dir_name);
     set_mysql_extended_error(mysql, CR_CANT_READ_CHARSET, unknown_sqlstate,
                              ER(CR_CANT_READ_CHARSET), cs_name, cs_dir_name);
   }
   charsets_dir= save_csdir;
   return mysql->net.last_errno;
 }
References st_mysql::charset, st_mysql_options::charset_dir, charsets_dir, CR_CANT_READ_CHARSET, ER, FN_REFLEN, get_charset_by_csname(), get_charsets_dir(), st_net::last_errno, MY_CS_NAME_SIZE, MY_CS_PRIMARY, MYF, mysql_get_server_version(), mysql_real_query(), st_mysql::net, st_mysql::options, set_mysql_extended_error(), sprintf(), and unknown_sqlstate.
Referenced by mysql_reconnect(), and MySQLConnection::Open().
mysql_set_local_infile_default()
void mysql_set_local_infile_default (MYSQL * mysql)
Definition at line 682 of file libmysql.c.
 {
   mysql->options.local_infile_init=  default_local_infile_init;
   mysql->options.local_infile_read=  default_local_infile_read;
   mysql->options.local_infile_end=   default_local_infile_end;
   mysql->options.local_infile_error= default_local_infile_error;
 }
References default_local_infile_end(), default_local_infile_error(), default_local_infile_init(), default_local_infile_read(), st_mysql_options::local_infile_end, st_mysql_options::local_infile_error, st_mysql_options::local_infile_init, st_mysql_options::local_infile_read, and st_mysql::options.
Referenced by handle_local_infile().
mysql_set_local_infile_handler()
void mysql_set_local_infile_handler (MYSQL * mysql, int(*)(void **, const char *, void *) local_infile_init, int(*)(void *, char *, unsigned int) local_infile_read, void(*)(void *) local_infile_end, int(*)(void *, char *, unsigned int) local_infile_error, void * userdata)
Definition at line 666 of file libmysql.c.
 {
   mysql->options.local_infile_init=  local_infile_init;
   mysql->options.local_infile_read=  local_infile_read;
   mysql->options.local_infile_end=   local_infile_end;
   mysql->options.local_infile_error= local_infile_error;
   mysql->options.local_infile_userdata = userdata;
 }
References st_mysql_options::local_infile_end, st_mysql_options::local_infile_error, st_mysql_options::local_infile_init, st_mysql_options::local_infile_read, st_mysql_options::local_infile_userdata, and st_mysql::options.
mysql_set_server_option()
int STDCALL mysql_set_server_option (MYSQL * mysql, enum enum_mysql_set_option option)
Definition at line 920 of file libmysql.c.
 {
   uchar buff[2];
   DBUG_ENTER("mysql_set_server_option");
   int2store(buff, (uint) option);
   DBUG_RETURN(simple_command(mysql, COM_SET_OPTION, buff, sizeof(buff), 0));
 }
References COM_SET_OPTION, DBUG_ENTER, DBUG_RETURN, int2store, and simple_command.
mysql_shutdown()
int STDCALL mysql_shutdown (MYSQL * mysql, enum mysql_enum_shutdown_level shutdown_level)
Definition at line 890 of file libmysql.c.
 {
   uchar level[1];
   DBUG_ENTER("mysql_shutdown");
   level[0]= (uchar) shutdown_level;
   DBUG_RETURN(simple_command(mysql, COM_SHUTDOWN, level, 1, 0));
 }
References COM_SHUTDOWN, DBUG_ENTER, DBUG_RETURN, and simple_command.
mysql_sqlstate()
const char* STDCALL mysql_sqlstate (MYSQL * mysql)
Definition at line 1044 of file libmysql.c.
 {
   return mysql ? mysql->net.sqlstate : cant_connect_sqlstate;
 }
References cant_connect_sqlstate, st_mysql::net, and st_net::sqlstate.
mysql_ssl_set()
my_bool STDCALL mysql_ssl_set (MYSQL * mysql, const char * key, const char * cert, const char * ca, const char * capath, const char * cipher)
mysql_stat()
const char* STDCALL mysql_stat (MYSQL * mysql)
Definition at line 950 of file libmysql.c.
 {
   DBUG_ENTER("mysql_stat");
   if (simple_command(mysql,COM_STATISTICS,0,0,0))
     DBUG_RETURN(mysql->net.last_error);
   DBUG_RETURN((*mysql->methods->read_statistics)(mysql));
 }
References COM_STATISTICS, DBUG_ENTER, DBUG_RETURN, st_net::last_error, st_mysql::methods, st_mysql::net, st_mysql_methods::read_statistics, and simple_command.
mysql_stmt_affected_rows()
my_ulonglong STDCALL mysql_stmt_affected_rows (MYSQL_STMT * stmt)
Definition at line 2527 of file libmysql.c.
 {
   return stmt->affected_rows;
 }
References st_mysql_stmt::affected_rows.
mysql_stmt_attr_get()
my_bool STDCALL mysql_stmt_attr_get (MYSQL_STMT * stmt, enum enum_stmt_attr_type attr_type, void * attr)
Definition at line 2348 of file libmysql.c.
 {
   switch (attr_type) {
   case STMT_ATTR_UPDATE_MAX_LENGTH:
     *(my_bool*) value= stmt->update_max_length;
     break;
   case STMT_ATTR_CURSOR_TYPE:
     *(ulong*) value= stmt->flags;
     break;
   case STMT_ATTR_PREFETCH_ROWS:
     *(ulong*) value= stmt->prefetch_rows;
     break;
   default:
     return TRUE;
   }
   return FALSE;
 }
References FALSE, st_mysql_stmt::flags, st_mysql_stmt::prefetch_rows, STMT_ATTR_CURSOR_TYPE, STMT_ATTR_PREFETCH_ROWS, STMT_ATTR_UPDATE_MAX_LENGTH, TRUE, and st_mysql_stmt::update_max_length.
mysql_stmt_attr_set()
my_bool STDCALL mysql_stmt_attr_set (MYSQL_STMT * stmt, enum enum_stmt_attr_type attr_type, const void * attr)
Definition at line 2313 of file libmysql.c.
 {
   switch (attr_type) {
   case STMT_ATTR_UPDATE_MAX_LENGTH:
     stmt->update_max_length= value ? *(const my_bool*) value : 0;
     break;
   case STMT_ATTR_CURSOR_TYPE:
   {
     ulong cursor_type;
     cursor_type= value ? *(ulong*) value : 0UL;
     if (cursor_type > (ulong) CURSOR_TYPE_READ_ONLY)
       goto err_not_implemented;
     stmt->flags= cursor_type;
     break;
   }
   case STMT_ATTR_PREFETCH_ROWS:
   {
     ulong prefetch_rows= value ? *(ulong*) value : DEFAULT_PREFETCH_ROWS;
     if (value == 0)
       return TRUE;
     stmt->prefetch_rows= prefetch_rows;
     break;
   }
   default:
     goto err_not_implemented;
   }
   return FALSE;
 err_not_implemented:
   set_stmt_error(stmt, CR_NOT_IMPLEMENTED, unknown_sqlstate, NULL);
   return TRUE;
 }
References CR_NOT_IMPLEMENTED, CURSOR_TYPE_READ_ONLY, DEFAULT_PREFETCH_ROWS, FALSE, st_mysql_stmt::flags, NULL, st_mysql_stmt::prefetch_rows, set_stmt_error(), STMT_ATTR_CURSOR_TYPE, STMT_ATTR_PREFETCH_ROWS, STMT_ATTR_UPDATE_MAX_LENGTH, TRUE, unknown_sqlstate, and st_mysql_stmt::update_max_length.
Referenced by MySQLPreparedStatement::MySQLPreparedStatement().
mysql_stmt_bind_param()
my_bool STDCALL mysql_stmt_bind_param (MYSQL_STMT * stmt, MYSQL_BIND * bnd)
Definition at line 2738 of file libmysql.c.
 {
   uint count=0;
   MYSQL_BIND *param, *end;
   DBUG_ENTER("mysql_stmt_bind_param");
   if (!stmt->param_count)
   {
     if ((int) stmt->state < (int) MYSQL_STMT_PREPARE_DONE)
     {
       set_stmt_error(stmt, CR_NO_PREPARE_STMT, unknown_sqlstate, NULL);
       DBUG_RETURN(1);
     }
     DBUG_RETURN(0);
   }
   /* Allocated on prepare */
   memcpy((char*) stmt->params, (char*) my_bind,
      sizeof(MYSQL_BIND) * stmt->param_count);
   for (param= stmt->params, end= param+stmt->param_count;
        param < end ;
        param++)
   {
     param->param_number= count++;
     param->long_data_used= 0;
     /* If param->is_null is not set, then the value can never be NULL */
     if (!param->is_null)
       param->is_null= &int_is_null_false;
     /* Setup data copy functions for the different supported types */
     switch (param->buffer_type) {
     case MYSQL_TYPE_NULL:
       param->is_null= &int_is_null_true;
       break;
     case MYSQL_TYPE_TINY:
       /* Force param->length as this is fixed for this type */
       param->length= &param->buffer_length;
       param->buffer_length= 1;
       param->store_param_func= store_param_tinyint;
       break;
     case MYSQL_TYPE_SHORT:
       param->length= &param->buffer_length;
       param->buffer_length= 2;
       param->store_param_func= store_param_short;
       break;
     case MYSQL_TYPE_LONG:
       param->length= &param->buffer_length;
       param->buffer_length= 4;
       param->store_param_func= store_param_int32;
       break;
     case MYSQL_TYPE_LONGLONG:
       param->length= &param->buffer_length;
       param->buffer_length= 8;
       param->store_param_func= store_param_int64;
       break;
     case MYSQL_TYPE_FLOAT:
       param->length= &param->buffer_length;
       param->buffer_length= 4;
       param->store_param_func= store_param_float;
       break;
     case MYSQL_TYPE_DOUBLE:
       param->length= &param->buffer_length;
       param->buffer_length= 8;
       param->store_param_func= store_param_double;
       break;
     case MYSQL_TYPE_TIME:
       param->store_param_func= store_param_time;
       param->buffer_length= MAX_TIME_REP_LENGTH;
       break;
     case MYSQL_TYPE_DATE:
       param->store_param_func= store_param_date;
       param->buffer_length= MAX_DATE_REP_LENGTH;
       break;
     case MYSQL_TYPE_DATETIME:
     case MYSQL_TYPE_TIMESTAMP:
       param->store_param_func= store_param_datetime;
       param->buffer_length= MAX_DATETIME_REP_LENGTH;
       break;
     case MYSQL_TYPE_TINY_BLOB:
     case MYSQL_TYPE_MEDIUM_BLOB:
     case MYSQL_TYPE_LONG_BLOB:
     case MYSQL_TYPE_BLOB:
     case MYSQL_TYPE_VARCHAR:
     case MYSQL_TYPE_VAR_STRING:
     case MYSQL_TYPE_STRING:
     case MYSQL_TYPE_DECIMAL:
     case MYSQL_TYPE_NEWDECIMAL:
       param->store_param_func= store_param_str;
       /*
         For variable length types user must set either length or
         buffer_length.
       */
       break;
     default:
       strmov(stmt->sqlstate, unknown_sqlstate);
       sprintf(stmt->last_error,
           ER(stmt->last_errno= CR_UNSUPPORTED_PARAM_TYPE),
           param->buffer_type, count);
       DBUG_RETURN(1);
     }
     /*
       If param->length is not given, change it to point to buffer_length.
       This way we can always use *param->length to get the length of data
     */
     if (!param->length)
       param->length= &param->buffer_length;
   }
   /* We have to send/resend type information to MySQL */
   stmt->send_types_to_server= TRUE;
   stmt->bind_param_done= TRUE;
   DBUG_RETURN(0);
 }
References st_mysql_stmt::bind_param_done, st_mysql_bind::buffer_length, st_mysql_bind::buffer_type, count(), CR_NO_PREPARE_STMT, CR_UNSUPPORTED_PARAM_TYPE, DBUG_ENTER, DBUG_RETURN, ER, int_is_null_false, int_is_null_true, st_mysql_bind::is_null, st_mysql_stmt::last_errno, st_mysql_stmt::last_error, st_mysql_bind::length, st_mysql_bind::long_data_used, MAX_DATE_REP_LENGTH, MAX_DATETIME_REP_LENGTH, MAX_TIME_REP_LENGTH, memcpy, MYSQL_STMT_PREPARE_DONE, MYSQL_TYPE_BLOB, MYSQL_TYPE_DATE, MYSQL_TYPE_DATETIME, MYSQL_TYPE_DECIMAL, MYSQL_TYPE_DOUBLE, MYSQL_TYPE_FLOAT, MYSQL_TYPE_LONG, MYSQL_TYPE_LONG_BLOB, MYSQL_TYPE_LONGLONG, MYSQL_TYPE_MEDIUM_BLOB, MYSQL_TYPE_NEWDECIMAL, MYSQL_TYPE_NULL, MYSQL_TYPE_SHORT, MYSQL_TYPE_STRING, MYSQL_TYPE_TIME, MYSQL_TYPE_TIMESTAMP, MYSQL_TYPE_TINY, MYSQL_TYPE_TINY_BLOB, MYSQL_TYPE_VAR_STRING, MYSQL_TYPE_VARCHAR, NULL, st_mysql_stmt::param_count, st_mysql_bind::param_number, st_mysql_stmt::params, st_mysql_stmt::send_types_to_server, set_stmt_error(), sprintf(), st_mysql_stmt::sqlstate, st_mysql_stmt::state, store_param_date(), store_param_datetime(), store_param_double(), store_param_float(), st_mysql_bind::store_param_func, store_param_int32(), store_param_int64(), store_param_short(), store_param_str(), store_param_time(), store_param_tinyint(), strmov(), TRUE, and unknown_sqlstate.
Referenced by MySQLConnection::_Query(), and MySQLConnection::Execute().
mysql_stmt_bind_result()
my_bool STDCALL mysql_stmt_bind_result (MYSQL_STMT * stmt, MYSQL_BIND * bnd)
Definition at line 3993 of file libmysql.c.
 {
   MYSQL_BIND *param, *end;
   MYSQL_FIELD *field;
   ulong       bind_count= stmt->field_count;
   uint        param_count= 0;
   DBUG_ENTER("mysql_stmt_bind_result");
   DBUG_PRINT("enter",("field_count: %lu", bind_count));
   if (!bind_count)
   {
     int errorcode= (int) stmt->state < (int) MYSQL_STMT_PREPARE_DONE ?
                    CR_NO_PREPARE_STMT : CR_NO_STMT_METADATA;
     set_stmt_error(stmt, errorcode, unknown_sqlstate, NULL);
     DBUG_RETURN(1);
   }
   /*
     We only need to check that stmt->field_count - if it is not null
     stmt->bind was initialized in mysql_stmt_prepare
     stmt->bind overlaps with bind if mysql_stmt_bind_param
     is called from mysql_stmt_store_result.
   */
   if (stmt->bind != my_bind)
     memcpy((char*) stmt->bind, (char*) my_bind,
            sizeof(MYSQL_BIND) * bind_count);
   for (param= stmt->bind, end= param + bind_count, field= stmt->fields ;
        param < end ;
        param++, field++)
   {
     DBUG_PRINT("info",("buffer_type: %u  field_type: %u",
                        (uint) param->buffer_type, (uint) field->type));
     /*
       Set param->is_null to point to a dummy variable if it's not set.
       This is to make the execute code easier
     */
     if (!param->is_null)
       param->is_null= &param->is_null_value;
     if (!param->length)
       param->length= &param->length_value;
     if (!param->error)
       param->error= &param->error_value;
     param->param_number= param_count++;
     param->offset= 0;
     if (setup_one_fetch_function(param, field))
     {
       strmov(stmt->sqlstate, unknown_sqlstate);
       sprintf(stmt->last_error,
               ER(stmt->last_errno= CR_UNSUPPORTED_PARAM_TYPE),
               field->type, param_count);
       DBUG_RETURN(1);
     }
   }
   stmt->bind_result_done= BIND_RESULT_DONE;
   if (stmt->mysql->options.report_data_truncation)
     stmt->bind_result_done|= REPORT_DATA_TRUNCATION;
   DBUG_RETURN(0);
 }
References st_mysql_stmt::bind, st_mysql_stmt::bind_result_done, BIND_RESULT_DONE, st_mysql_bind::buffer_type, CR_NO_PREPARE_STMT, CR_NO_STMT_METADATA, CR_UNSUPPORTED_PARAM_TYPE, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, ER, st_mysql_bind::error, st_mysql_bind::error_value, st_mysql_stmt::field_count, st_mysql_stmt::fields, st_mysql_bind::is_null, st_mysql_bind::is_null_value, st_mysql_stmt::last_errno, st_mysql_stmt::last_error, st_mysql_bind::length, st_mysql_bind::length_value, memcpy, st_mysql_stmt::mysql, MYSQL_STMT_PREPARE_DONE, NULL, st_mysql_bind::offset, st_mysql::options, st_mysql_bind::param_number, st_mysql_options::report_data_truncation, REPORT_DATA_TRUNCATION, set_stmt_error(), setup_one_fetch_function(), sprintf(), st_mysql_stmt::sqlstate, st_mysql_stmt::state, strmov(), st_mysql_field::type, and unknown_sqlstate.
Referenced by mysql_stmt_store_result(), and PreparedResultSet::PreparedResultSet().
mysql_stmt_close()
my_bool STDCALL mysql_stmt_close (MYSQL_STMT * stmt)
Definition at line 4600 of file libmysql.c.
 {
   MYSQL *mysql= stmt->mysql;
   int rc= 0;
   DBUG_ENTER("mysql_stmt_close");
   free_root(&stmt->result.alloc, MYF(0));
   free_root(&stmt->mem_root, MYF(0));
   if (mysql)
   {
     mysql->stmts= list_delete(mysql->stmts, &stmt->list);
     /*
       Clear NET error state: if the following commands come through
       successfully, connection will still be usable for other commands.
     */
     net_clear_error(&mysql->net);
     if ((int) stmt->state > (int) MYSQL_STMT_INIT_DONE)
     {
       uchar buff[MYSQL_STMT_HEADER];             /* 4 bytes - stmt id */
       if (mysql->unbuffered_fetch_owner == &stmt->unbuffered_fetch_cancelled)
         mysql->unbuffered_fetch_owner= 0;
       if (mysql->status != MYSQL_STATUS_READY)
       {
         /*
           Flush result set of the connection. If it does not belong
           to this statement, set a warning.
         */
         (*mysql->methods->flush_use_result)(mysql, TRUE);
         if (mysql->unbuffered_fetch_owner)
           *mysql->unbuffered_fetch_owner= TRUE;
         mysql->status= MYSQL_STATUS_READY;
       }
       int4store(buff, stmt->stmt_id);
       if ((rc= stmt_command(mysql, COM_STMT_CLOSE, buff, 4, stmt)))
       {
         set_stmt_errmsg(stmt, &mysql->net);
       }
     }
   }
   my_free(stmt);
   DBUG_RETURN(test(rc));
 }
References st_mysql_data::alloc, COM_STMT_CLOSE, DBUG_ENTER, DBUG_RETURN, st_mysql_methods::flush_use_result, free_root(), int4store, st_mysql_stmt::list, list_delete(), st_mysql_stmt::mem_root, st_mysql::methods, my_free(), MYF, st_mysql_stmt::mysql, MYSQL_STATUS_READY, MYSQL_STMT_HEADER, MYSQL_STMT_INIT_DONE, st_mysql::net, net_clear_error(), st_mysql_stmt::result, set_stmt_errmsg(), st_mysql_stmt::state, st_mysql::status, stmt_command, st_mysql_stmt::stmt_id, st_mysql::stmts, test, TRUE, st_mysql_stmt::unbuffered_fetch_cancelled, and st_mysql::unbuffered_fetch_owner.
Referenced by MySQLConnection::PrepareStatement(), and MySQLPreparedStatement::~MySQLPreparedStatement().
mysql_stmt_data_seek()
void STDCALL mysql_stmt_data_seek (MYSQL_STMT * stmt, my_ulonglong offset)
Definition at line 4471 of file libmysql.c.
 {
   MYSQL_ROWS *tmp= stmt->result.data;
   DBUG_ENTER("mysql_stmt_data_seek");
   DBUG_PRINT("enter",("row id to seek: %ld",(long) row));
   for (; tmp && row; --row, tmp= tmp->next)
     ;
   stmt->data_cursor= tmp;
   if (!row && tmp)
   {
        /*  Rewind the counter */
     stmt->read_row_func= stmt_read_row_buffered;
     stmt->state= MYSQL_STMT_EXECUTE_DONE;
   }
   DBUG_VOID_RETURN;
 }
References st_mysql_data::data, st_mysql_stmt::data_cursor, DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, MYSQL_STMT_EXECUTE_DONE, st_mysql_rows::next, st_mysql_stmt::read_row_func, st_mysql_stmt::result, st_mysql_stmt::state, and stmt_read_row_buffered().
mysql_stmt_errno()
unsigned int STDCALL mysql_stmt_errno (MYSQL_STMT * stmt)
Definition at line 4671 of file libmysql.c.
 {
   DBUG_ENTER("mysql_stmt_errno");
   DBUG_RETURN(stmt->last_errno);
 }
References DBUG_ENTER, DBUG_RETURN, and st_mysql_stmt::last_errno.
mysql_stmt_error()
const char* STDCALL mysql_stmt_error (MYSQL_STMT * stmt)
Definition at line 4687 of file libmysql.c.
 {
   DBUG_ENTER("mysql_stmt_error");
   DBUG_RETURN(stmt->last_error);
 }
References DBUG_ENTER, DBUG_RETURN, and st_mysql_stmt::last_error.
Referenced by MySQLConnection::_Query(), MySQLConnection::Execute(), PreparedResultSet::PreparedResultSet(), and MySQLConnection::PrepareStatement().
mysql_stmt_execute()
int STDCALL mysql_stmt_execute (MYSQL_STMT * stmt)
Definition at line 2484 of file libmysql.c.
 {
   MYSQL *mysql= stmt->mysql;
   DBUG_ENTER("mysql_stmt_execute");
   if (!mysql)
   {
     /* Error is already set in mysql_detatch_stmt_list */
     DBUG_RETURN(1);
   }
   if (reset_stmt_handle(stmt, RESET_STORE_RESULT | RESET_CLEAR_ERROR))
     DBUG_RETURN(1);
   /*
     No need to check for stmt->state: if the statement wasn't
     prepared we'll get 'unknown statement handler' error from server.
   */
   if (mysql->methods->stmt_execute(stmt))
     DBUG_RETURN(1);
   stmt->state= MYSQL_STMT_EXECUTE_DONE;
   if (mysql->field_count)
   {
     reinit_result_set_metadata(stmt);
     prepare_to_fetch_result(stmt);
   }
   DBUG_RETURN(test(stmt->last_errno));
 }
References DBUG_ENTER, DBUG_RETURN, st_mysql::field_count, st_mysql_stmt::last_errno, st_mysql::methods, st_mysql_stmt::mysql, MYSQL_STMT_EXECUTE_DONE, prepare_to_fetch_result(), reinit_result_set_metadata(), RESET_CLEAR_ERROR, reset_stmt_handle(), RESET_STORE_RESULT, st_mysql_stmt::state, st_mysql_methods::stmt_execute, and test.
Referenced by MySQLConnection::_Query(), and MySQLConnection::Execute().
mysql_stmt_fetch()
int STDCALL mysql_stmt_fetch (MYSQL_STMT * stmt)
Definition at line 4140 of file libmysql.c.
 {
   int rc;
   uchar *row;
   DBUG_ENTER("mysql_stmt_fetch");
   if ((rc= (*stmt->read_row_func)(stmt, &row)) ||
       ((rc= stmt_fetch_row(stmt, row)) && rc != MYSQL_DATA_TRUNCATED))
   {
     stmt->state= MYSQL_STMT_PREPARE_DONE;       /* XXX: this is buggy */
     stmt->read_row_func= (rc == MYSQL_NO_DATA) ?
       stmt_read_row_no_data : stmt_read_row_no_result_set;
   }
   else
   {
     /* This is to know in mysql_stmt_fetch_column that data was fetched */
     stmt->state= MYSQL_STMT_FETCH_DONE;
   }
   DBUG_RETURN(rc);
 }
References DBUG_ENTER, DBUG_RETURN, MYSQL_DATA_TRUNCATED, MYSQL_NO_DATA, MYSQL_STMT_FETCH_DONE, MYSQL_STMT_PREPARE_DONE, st_mysql_stmt::read_row_func, st_mysql_stmt::state, stmt_fetch_row(), stmt_read_row_no_data(), and stmt_read_row_no_result_set().
Referenced by PreparedResultSet::_NextRow().
mysql_stmt_fetch_column()
int STDCALL mysql_stmt_fetch_column (MYSQL_STMT * stmt, MYSQL_BIND * bind_arg, unsigned int column, unsigned long offset)
Definition at line 4178 of file libmysql.c.
 {
   MYSQL_BIND *param= stmt->bind+column;
   DBUG_ENTER("mysql_stmt_fetch_column");
   if ((int) stmt->state < (int) MYSQL_STMT_FETCH_DONE)
   {
     set_stmt_error(stmt, CR_NO_DATA, unknown_sqlstate, NULL);
     return 1;
   }
   if (column >= stmt->field_count)
   {
     set_stmt_error(stmt, CR_INVALID_PARAMETER_NO, unknown_sqlstate, NULL);
     DBUG_RETURN(1);
   }
   if (!my_bind->error)
     my_bind->error= &my_bind->error_value;
   *my_bind->error= 0;
   if (param->row_ptr)
   {
     MYSQL_FIELD *field= stmt->fields+column;
     uchar *row= param->row_ptr;
     my_bind->offset= offset;
     if (my_bind->is_null)
       *my_bind->is_null= 0;
     if (my_bind->length) /* Set the length if non char/binary types */
       *my_bind->length= *param->length;
     else
       my_bind->length= &param->length_value;       /* Needed for fetch_result() */
     fetch_result_with_conversion(my_bind, field, &row);
   }
   else
   {
     if (my_bind->is_null)
       *my_bind->is_null= 1;
   }
   DBUG_RETURN(0);
 }
References st_mysql_stmt::bind, CR_INVALID_PARAMETER_NO, CR_NO_DATA, DBUG_ENTER, DBUG_RETURN, st_mysql_bind::error, st_mysql_bind::error_value, fetch_result_with_conversion(), st_mysql_stmt::field_count, st_mysql_stmt::fields, st_mysql_bind::is_null, st_mysql_bind::length, st_mysql_bind::length_value, MYSQL_STMT_FETCH_DONE, NULL, st_mysql_bind::offset, st_mysql_bind::row_ptr, set_stmt_error(), st_mysql_stmt::state, and unknown_sqlstate.
mysql_stmt_field_count()
unsigned int STDCALL mysql_stmt_field_count (MYSQL_STMT * stmt)
Definition at line 2538 of file libmysql.c.
 {
   return stmt->field_count;
 }
References st_mysql_stmt::field_count.
Referenced by MySQLConnection::_Query().
mysql_stmt_free_result()
my_bool STDCALL mysql_stmt_free_result (MYSQL_STMT * stmt)
Definition at line 4575 of file libmysql.c.
 {
   DBUG_ENTER("mysql_stmt_free_result");
   /* Free the client side and close the server side cursor if there is one */
   DBUG_RETURN(reset_stmt_handle(stmt, RESET_LONG_DATA | RESET_STORE_RESULT |
                                 RESET_CLEAR_ERROR));
 }
References DBUG_ENTER, DBUG_RETURN, RESET_CLEAR_ERROR, RESET_LONG_DATA, reset_stmt_handle(), and RESET_STORE_RESULT.
Referenced by PreparedResultSet::PreparedResultSet().
mysql_stmt_init()
MYSQL_STMT* STDCALL mysql_stmt_init (MYSQL * mysql)
Definition at line 1478 of file libmysql.c.
 {
   MYSQL_STMT *stmt;
   DBUG_ENTER("mysql_stmt_init");
   if (!(stmt= (MYSQL_STMT *) my_malloc(sizeof(MYSQL_STMT),
                                        MYF(MY_WME | MY_ZEROFILL))))
   {
     set_mysql_error(mysql, CR_OUT_OF_MEMORY, unknown_sqlstate);
     DBUG_RETURN(0);
   }
   init_alloc_root(&stmt->mem_root, 2048, 2048);
   init_alloc_root(&stmt->result.alloc, 4096, 4096);
   stmt->result.alloc.min_malloc= sizeof(MYSQL_ROWS);
   mysql->stmts= list_add(mysql->stmts, &stmt->list);
   stmt->list.data= stmt;
   stmt->state= MYSQL_STMT_INIT_DONE;
   stmt->mysql= mysql;
   stmt->read_row_func= stmt_read_row_no_result_set;
   stmt->prefetch_rows= DEFAULT_PREFETCH_ROWS;
   strmov(stmt->sqlstate, not_error_sqlstate);
   /* The rest of statement members was bzeroed inside malloc */
   DBUG_RETURN(stmt);
 }
References st_mysql_data::alloc, CR_OUT_OF_MEMORY, st_list::data, DBUG_ENTER, DBUG_RETURN, DEFAULT_PREFETCH_ROWS, init_alloc_root(), st_mysql_stmt::list, list_add(), st_mysql_stmt::mem_root, st_mem_root::min_malloc, my_malloc(), MY_WME, MY_ZEROFILL, MYF, st_mysql_stmt::mysql, MYSQL_STMT_INIT_DONE, not_error_sqlstate, st_mysql_stmt::prefetch_rows, st_mysql_stmt::read_row_func, st_mysql_stmt::result, set_mysql_error(), st_mysql_stmt::sqlstate, st_mysql_stmt::state, stmt_read_row_no_result_set(), st_mysql::stmts, strmov(), and unknown_sqlstate.
Referenced by MySQLConnection::PrepareStatement().
mysql_stmt_insert_id()
my_ulonglong STDCALL mysql_stmt_insert_id (MYSQL_STMT * stmt)
Definition at line 2559 of file libmysql.c.
 {
   return stmt->insert_id;
 }
References st_mysql_stmt::insert_id.
mysql_stmt_next_result()
int STDCALL mysql_stmt_next_result (MYSQL_STMT * stmt)
Definition at line 4777 of file libmysql.c.
 {
   MYSQL *mysql= stmt->mysql;
   int rc;
   DBUG_ENTER("mysql_stmt_next_result");
   if (!mysql)
     DBUG_RETURN(1);
   if (stmt->last_errno)
     DBUG_RETURN(stmt->last_errno);
   if (mysql->server_status & SERVER_MORE_RESULTS_EXISTS)
   {
     if (reset_stmt_handle(stmt, RESET_STORE_RESULT))
       DBUG_RETURN(1);
   }
   rc= mysql_next_result(mysql);
   if (rc)
   {
     set_stmt_errmsg(stmt, &mysql->net);
     DBUG_RETURN(rc);
   }
   if (mysql->status == MYSQL_STATUS_GET_RESULT)
     mysql->status= MYSQL_STATUS_STATEMENT_GET_RESULT;
   stmt->state= MYSQL_STMT_EXECUTE_DONE;
   stmt->bind_result_done= FALSE;
   if (mysql->field_count)
   {
     alloc_stmt_fields(stmt);
     prepare_to_fetch_result(stmt);
   }
   else
   {
     stmt->field_count= mysql->field_count;
   }
   DBUG_RETURN(0);
 }
References alloc_stmt_fields(), st_mysql_stmt::bind_result_done, DBUG_ENTER, DBUG_RETURN, FALSE, st_mysql::field_count, st_mysql_stmt::field_count, st_mysql_stmt::last_errno, st_mysql_stmt::mysql, mysql_next_result(), MYSQL_STATUS_GET_RESULT, MYSQL_STATUS_STATEMENT_GET_RESULT, MYSQL_STMT_EXECUTE_DONE, st_mysql::net, prepare_to_fetch_result(), reset_stmt_handle(), RESET_STORE_RESULT, SERVER_MORE_RESULTS_EXISTS, st_mysql::server_status, set_stmt_errmsg(), st_mysql_stmt::state, and st_mysql::status.
mysql_stmt_num_rows()
my_ulonglong STDCALL mysql_stmt_num_rows (MYSQL_STMT * stmt)
Definition at line 4494 of file libmysql.c.
 {
   DBUG_ENTER("mysql_stmt_num_rows");
   DBUG_RETURN(stmt->result.rows);
 }
References DBUG_ENTER, DBUG_RETURN, st_mysql_stmt::result, and st_mysql_data::rows.
Referenced by MySQLConnection::_Query(), and PreparedResultSet::PreparedResultSet().
mysql_stmt_param_count()
unsigned long STDCALL mysql_stmt_param_count (MYSQL_STMT * stmt)
Definition at line 2517 of file libmysql.c.
 {
   DBUG_ENTER("mysql_stmt_param_count");
   DBUG_RETURN(stmt->param_count);
 }
References DBUG_ENTER, DBUG_RETURN, and st_mysql_stmt::param_count.
Referenced by MySQLPreparedStatement::MySQLPreparedStatement().
mysql_stmt_param_metadata()
MYSQL_RES* STDCALL mysql_stmt_param_metadata (MYSQL_STMT * stmt)
Definition at line 1802 of file libmysql.c.
 {
   DBUG_ENTER("mysql_stmt_param_metadata");
   if (!stmt->param_count)
     DBUG_RETURN(0);
   /*
     TODO: Fix this when server sends the information.
     Till then keep a dummy prototype.
   */
   DBUG_RETURN(0);
 }
References DBUG_ENTER, DBUG_RETURN, and st_mysql_stmt::param_count.
mysql_stmt_prepare()
int STDCALL mysql_stmt_prepare (MYSQL_STMT * stmt, const char * query, unsigned long length)
Definition at line 1541 of file libmysql.c.
 {
   MYSQL *mysql= stmt->mysql;
   DBUG_ENTER("mysql_stmt_prepare");
   if (!mysql)
   {
     /* mysql can be reset in mysql_close called from mysql_reconnect */
     set_stmt_error(stmt, CR_SERVER_LOST, unknown_sqlstate, NULL);
     DBUG_RETURN(1);
   }
   /*
     Reset the last error in any case: that would clear the statement
     if the previous prepare failed.
   */
   stmt->last_errno= 0;
   stmt->last_error[0]= '\0';
   if ((int) stmt->state > (int) MYSQL_STMT_INIT_DONE)
   {
     /* This is second prepare with another statement */
     uchar buff[MYSQL_STMT_HEADER];               /* 4 bytes - stmt id */
     if (reset_stmt_handle(stmt, RESET_LONG_DATA | RESET_STORE_RESULT))
       DBUG_RETURN(1);
     /*
       These members must be reset for API to
       function in case of error or misuse.
     */
     stmt->bind_param_done= stmt->bind_result_done= FALSE;
     stmt->param_count= stmt->field_count= 0;
     free_root(&stmt->mem_root, MYF(MY_KEEP_PREALLOC));
     int4store(buff, stmt->stmt_id);
     /*
       Close statement in server
       If there was a 'use' result from another statement, or from
       mysql_use_result it won't be freed in mysql_stmt_free_result and
       we should get 'Commands out of sync' here.
     */
     stmt->state= MYSQL_STMT_INIT_DONE;
     if (stmt_command(mysql, COM_STMT_CLOSE, buff, 4, stmt))
     {
       set_stmt_errmsg(stmt, &mysql->net);
       DBUG_RETURN(1);
     }
   }
   if (stmt_command(mysql, COM_STMT_PREPARE, (const uchar*) query, length, stmt))
   {
     set_stmt_errmsg(stmt, &mysql->net);
     DBUG_RETURN(1);
   }
   if ((*mysql->methods->read_prepare_result)(mysql, stmt))
   {
     set_stmt_errmsg(stmt, &mysql->net);
     DBUG_RETURN(1);
   }
   /*
     alloc_root will return valid address even in case when param_count
     and field_count are zero. Thus we should never rely on stmt->bind
     or stmt->params when checking for existence of placeholders or
     result set.
   */
   if (!(stmt->params= (MYSQL_BIND *) alloc_root(&stmt->mem_root,
                         sizeof(MYSQL_BIND)*
                                                 (stmt->param_count +
                                                  stmt->field_count))))
   {
     set_stmt_error(stmt, CR_OUT_OF_MEMORY, unknown_sqlstate, NULL);
     DBUG_RETURN(1);
   }
   stmt->bind= stmt->params + stmt->param_count;
   stmt->state= MYSQL_STMT_PREPARE_DONE;
   DBUG_PRINT("info", ("Parameter count: %u", stmt->param_count));
   DBUG_RETURN(0);
 }
References alloc_root(), st_mysql_stmt::bind, st_mysql_stmt::bind_param_done, st_mysql_stmt::bind_result_done, COM_STMT_CLOSE, COM_STMT_PREPARE, CR_OUT_OF_MEMORY, CR_SERVER_LOST, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, FALSE, st_mysql_stmt::field_count, free_root(), int4store, st_mysql_stmt::last_errno, st_mysql_stmt::last_error, G3D::length(), st_mysql_stmt::mem_root, st_mysql::methods, MY_KEEP_PREALLOC, MYF, st_mysql_stmt::mysql, MYSQL_STMT_HEADER, MYSQL_STMT_INIT_DONE, MYSQL_STMT_PREPARE_DONE, st_mysql::net, NULL, st_mysql_stmt::param_count, st_mysql_stmt::params, st_mysql_methods::read_prepare_result, RESET_LONG_DATA, reset_stmt_handle(), RESET_STORE_RESULT, set_stmt_errmsg(), set_stmt_error(), st_mysql_stmt::state, stmt_command, st_mysql_stmt::stmt_id, and unknown_sqlstate.
Referenced by MySQLConnection::PrepareStatement().
mysql_stmt_reset()
my_bool STDCALL mysql_stmt_reset (MYSQL_STMT * stmt)
Definition at line 4651 of file libmysql.c.
 {
   DBUG_ENTER("mysql_stmt_reset");
   DBUG_ASSERT(stmt != 0);
   if (!stmt->mysql)
   {
     /* mysql can be reset in mysql_close called from mysql_reconnect */
     set_stmt_error(stmt, CR_SERVER_LOST, unknown_sqlstate, NULL);
     DBUG_RETURN(1);
   }
   /* Reset the client and server sides of the prepared statement */
   DBUG_RETURN(reset_stmt_handle(stmt,
                                 RESET_SERVER_SIDE | RESET_LONG_DATA |
                                 RESET_CLEAR_ERROR));
 }
References CR_SERVER_LOST, DBUG_ASSERT, DBUG_ENTER, DBUG_RETURN, st_mysql_stmt::mysql, NULL, RESET_CLEAR_ERROR, RESET_LONG_DATA, RESET_SERVER_SIDE, reset_stmt_handle(), set_stmt_error(), and unknown_sqlstate.
mysql_stmt_result_metadata()
MYSQL_RES* STDCALL mysql_stmt_result_metadata (MYSQL_STMT * stmt)
Definition at line 1755 of file libmysql.c.
 {
   MYSQL_RES *result;
   DBUG_ENTER("mysql_stmt_result_metadata");
   /*
     stmt->fields is only defined if stmt->field_count is not null;
     stmt->field_count is initialized in prepare.
   */
   if (!stmt->field_count)
      DBUG_RETURN(0);
   if (!(result=(MYSQL_RES*) my_malloc(sizeof(*result),
                                       MYF(MY_WME | MY_ZEROFILL))))
   {
     set_stmt_error(stmt, CR_OUT_OF_MEMORY, unknown_sqlstate, NULL);
     DBUG_RETURN(0);
   }
   result->methods=  stmt->mysql->methods;
   result->eof=      1;                      /* Marker for buffered */
   result->fields=   stmt->fields;
   result->field_count=  stmt->field_count;
   /* The rest of members of 'result' was bzeroed inside malloc */
   DBUG_RETURN(result);
 }
References CR_OUT_OF_MEMORY, DBUG_ENTER, DBUG_RETURN, st_mysql_stmt::field_count, st_mysql_stmt::fields, st_mysql::methods, my_malloc(), MY_WME, MY_ZEROFILL, MYF, st_mysql_stmt::mysql, NULL, set_stmt_error(), and unknown_sqlstate.
Referenced by MySQLConnection::_Query().
mysql_stmt_row_seek()
MYSQL_ROW_OFFSET STDCALL mysql_stmt_row_seek (MYSQL_STMT * stmt, MYSQL_ROW_OFFSET offset)
Definition at line 4443 of file libmysql.c.
 {
   MYSQL_ROW_OFFSET offset= stmt->data_cursor;
   DBUG_ENTER("mysql_stmt_row_seek");
   stmt->data_cursor= row;
   DBUG_RETURN(offset);
 }
References st_mysql_stmt::data_cursor, DBUG_ENTER, and DBUG_RETURN.
mysql_stmt_row_tell()
MYSQL_ROW_OFFSET STDCALL mysql_stmt_row_tell (MYSQL_STMT * stmt)
Definition at line 4458 of file libmysql.c.
 {
   DBUG_ENTER("mysql_stmt_row_tell");
   DBUG_RETURN(stmt->data_cursor);
 }
References st_mysql_stmt::data_cursor, DBUG_ENTER, and DBUG_RETURN.
mysql_stmt_send_long_data()
my_bool STDCALL mysql_stmt_send_long_data (MYSQL_STMT * stmt, unsigned int param_number, const char * data, unsigned long length)
Definition at line 2898 of file libmysql.c.
 {
   MYSQL_BIND *param;
   DBUG_ENTER("mysql_stmt_send_long_data");
   DBUG_ASSERT(stmt != 0);
   DBUG_PRINT("enter",("param no: %d  data: 0x%lx, length : %ld",
               param_number, (long) data, length));
   /*
     We only need to check for stmt->param_count, if it's not null
     prepare was done.
   */
   if (param_number >= stmt->param_count)
   {
     set_stmt_error(stmt, CR_INVALID_PARAMETER_NO, unknown_sqlstate, NULL);
     DBUG_RETURN(1);
   }
   param= stmt->params+param_number;
   if (!IS_LONGDATA(param->buffer_type))
   {
     /* Long data handling should be used only for string/binary types */
     strmov(stmt->sqlstate, unknown_sqlstate);
     sprintf(stmt->last_error, ER(stmt->last_errno= CR_INVALID_BUFFER_USE),
         param->param_number);
     DBUG_RETURN(1);
   }
   /*
     Send long data packet if there is data or we're sending long data
     for the first time.
   */
   if (length || param->long_data_used == 0)
   {
     MYSQL *mysql= stmt->mysql;
     /* Packet header: stmt id (4 bytes), param no (2 bytes) */
     uchar buff[MYSQL_LONG_DATA_HEADER];
     int4store(buff, stmt->stmt_id);
     int2store(buff + 4, param_number);
     param->long_data_used= 1;
     /*
       Note that we don't get any ok packet from the server in this case
       This is intentional to save bandwidth.
     */
     if ((*mysql->methods->advanced_command)(mysql, COM_STMT_SEND_LONG_DATA,
                                             buff, sizeof(buff), (uchar*) data,
                                             length, 1, stmt))
     {
       /*
         Don't set stmt error if stmt->mysql is NULL, as the error in this case
         has already been set by mysql_prune_stmt_list().
       */
       if (stmt->mysql)
         set_stmt_errmsg(stmt, &mysql->net);
       DBUG_RETURN(1);
     }
   }
   DBUG_RETURN(0);
 }
References st_mysql_methods::advanced_command, st_mysql_bind::buffer_type, COM_STMT_SEND_LONG_DATA, CR_INVALID_BUFFER_USE, CR_INVALID_PARAMETER_NO, DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, ER, int2store, int4store, IS_LONGDATA, st_mysql_stmt::last_errno, st_mysql_stmt::last_error, G3D::length(), st_mysql_bind::long_data_used, st_mysql::methods, st_mysql_stmt::mysql, MYSQL_LONG_DATA_HEADER, st_mysql::net, NULL, st_mysql_stmt::param_count, st_mysql_bind::param_number, st_mysql_stmt::params, set_stmt_errmsg(), set_stmt_error(), sprintf(), st_mysql_stmt::sqlstate, st_mysql_stmt::stmt_id, strmov(), and unknown_sqlstate.
mysql_stmt_sqlstate()
const char* STDCALL mysql_stmt_sqlstate (MYSQL_STMT * stmt)
Definition at line 4677 of file libmysql.c.
 {
   DBUG_ENTER("mysql_stmt_sqlstate");
   DBUG_RETURN(stmt->sqlstate);
 }
References DBUG_ENTER, DBUG_RETURN, and st_mysql_stmt::sqlstate.
mysql_stmt_store_result()
int STDCALL mysql_stmt_store_result (MYSQL_STMT * stmt)
Definition at line 4326 of file libmysql.c.
 {
   MYSQL *mysql= stmt->mysql;
   MYSQL_DATA *result= &stmt->result;
   DBUG_ENTER("mysql_stmt_store_result");
   if (!mysql)
   {
     /* mysql can be reset in mysql_close called from mysql_reconnect */
     set_stmt_error(stmt, CR_SERVER_LOST, unknown_sqlstate, NULL);
     DBUG_RETURN(1);
   }
   if (!stmt->field_count)
     DBUG_RETURN(0);
   if ((int) stmt->state < (int) MYSQL_STMT_EXECUTE_DONE)
   {
     set_stmt_error(stmt, CR_COMMANDS_OUT_OF_SYNC, unknown_sqlstate, NULL);
     DBUG_RETURN(1);
   }
   if (stmt->last_errno)
   {
     /* An attempt to use an invalid statement handle. */
     DBUG_RETURN(1);
   }
   if (mysql->status == MYSQL_STATUS_READY &&
       stmt->server_status & SERVER_STATUS_CURSOR_EXISTS)
   {
     /*
       Server side cursor exist, tell server to start sending the rows
     */
     NET *net= &mysql->net;
     uchar buff[4 /* statement id */ +
                4 /* number of rows to fetch */];
     /* Send row request to the server */
     int4store(buff, stmt->stmt_id);
     int4store(buff + 4, (int)~0); /* number of rows to fetch */
     if (cli_advanced_command(mysql, COM_STMT_FETCH, buff, sizeof(buff),
                              (uchar*) 0, 0, 1, stmt))
     {
       /*
         Don't set stmt error if stmt->mysql is NULL, as the error in this case
         has already been set by mysql_prune_stmt_list().
       */
       if (stmt->mysql)
         set_stmt_errmsg(stmt, net);
       DBUG_RETURN(1);
     }
   }
   else if (mysql->status != MYSQL_STATUS_STATEMENT_GET_RESULT)
   {
     set_stmt_error(stmt, CR_COMMANDS_OUT_OF_SYNC, unknown_sqlstate, NULL);
     DBUG_RETURN(1);
   }
   if (stmt->update_max_length && !stmt->bind_result_done)
   {
     /*
       We must initalize the bind structure to be able to calculate
       max_length
     */
     MYSQL_BIND  *my_bind, *end;
     MYSQL_FIELD *field;
     bzero((char*) stmt->bind, sizeof(*stmt->bind)* stmt->field_count);
     for (my_bind= stmt->bind, end= my_bind + stmt->field_count,
            field= stmt->fields;
      my_bind < end ;
      my_bind++, field++)
     {
       my_bind->buffer_type= MYSQL_TYPE_NULL;
       my_bind->buffer_length=1;
     }
     if (mysql_stmt_bind_result(stmt, stmt->bind))
       DBUG_RETURN(1);
     stmt->bind_result_done= 0;          /* No normal bind done */
   }
   if ((*mysql->methods->read_binary_rows)(stmt))
   {
     free_root(&result->alloc, MYF(MY_KEEP_PREALLOC));
     result->data= NULL;
     result->rows= 0;
     mysql->status= MYSQL_STATUS_READY;
     DBUG_RETURN(1);
   }
   /* Assert that if there was a cursor, all rows have been fetched */
   DBUG_ASSERT(mysql->status != MYSQL_STATUS_READY ||
               (mysql->server_status & SERVER_STATUS_LAST_ROW_SENT));
   if (stmt->update_max_length)
   {
     MYSQL_ROWS *cur= result->data;
     for(; cur; cur=cur->next)
       stmt_update_metadata(stmt, cur);
   }
   stmt->data_cursor= result->data;
   mysql->affected_rows= stmt->affected_rows= result->rows;
   stmt->read_row_func= stmt_read_row_buffered;
   mysql->unbuffered_fetch_owner= 0;             /* set in stmt_execute */
   mysql->status= MYSQL_STATUS_READY;        /* server is ready */
   DBUG_RETURN(0); /* Data buffered, must be fetched with mysql_stmt_fetch() */
 }
References st_mysql::affected_rows, st_mysql_stmt::affected_rows, st_mysql_stmt::bind, st_mysql_stmt::bind_result_done, st_mysql_bind::buffer_length, st_mysql_bind::buffer_type, bzero, cli_advanced_command(), COM_STMT_FETCH, CR_COMMANDS_OUT_OF_SYNC, CR_SERVER_LOST, st_mysql_stmt::data_cursor, DBUG_ASSERT, DBUG_ENTER, DBUG_RETURN, st_mysql_stmt::field_count, st_mysql_stmt::fields, free_root(), int4store, st_mysql_stmt::last_errno, st_mysql::methods, MY_KEEP_PREALLOC, MYF, st_mysql_stmt::mysql, MYSQL_STATUS_READY, MYSQL_STATUS_STATEMENT_GET_RESULT, mysql_stmt_bind_result(), MYSQL_STMT_EXECUTE_DONE, MYSQL_TYPE_NULL, st_mysql::net, st_mysql_rows::next, NULL, st_mysql_methods::read_binary_rows, st_mysql_stmt::read_row_func, st_mysql_stmt::result, st_mysql::server_status, st_mysql_stmt::server_status, SERVER_STATUS_CURSOR_EXISTS, SERVER_STATUS_LAST_ROW_SENT, set_stmt_errmsg(), set_stmt_error(), st_mysql_stmt::state, st_mysql::status, st_mysql_stmt::stmt_id, stmt_read_row_buffered(), stmt_update_metadata(), st_mysql::unbuffered_fetch_owner, unknown_sqlstate, and st_mysql_stmt::update_max_length.
Referenced by prepare_to_fetch_result(), and PreparedResultSet::PreparedResultSet().
mysql_store_result()
MYSQL_RES* STDCALL mysql_store_result (MYSQL * mysql)
Definition at line 3820 of file client.c.
 {
   MYSQL_RES *result;
   DBUG_ENTER("mysql_store_result");
   if (!mysql->fields)
     DBUG_RETURN(0);
   if (mysql->status != MYSQL_STATUS_GET_RESULT)
   {
     set_mysql_error(mysql, CR_COMMANDS_OUT_OF_SYNC, unknown_sqlstate);
     DBUG_RETURN(0);
   }
   mysql->status=MYSQL_STATUS_READY;     /* server is ready */
   if (!(result=(MYSQL_RES*) my_malloc((uint) (sizeof(MYSQL_RES)+
                           sizeof(ulong) *
                           mysql->field_count),
                       MYF(MY_WME | MY_ZEROFILL))))
   {
     set_mysql_error(mysql, CR_OUT_OF_MEMORY, unknown_sqlstate);
     DBUG_RETURN(0);
   }
   result->methods= mysql->methods;
   result->eof=1;                /* Marker for buffered */
   result->lengths=(ulong*) (result+1);
   if (!(result->data=
     (*mysql->methods->read_rows)(mysql,mysql->fields,mysql->field_count)))
   {
     my_free(result);
     DBUG_RETURN(0);
   }
   mysql->affected_rows= result->row_count= result->data->rows;
   result->data_cursor=  result->data->data;
   result->fields=   mysql->fields;
   result->field_alloc=  mysql->field_alloc;
   result->field_count=  mysql->field_count;
   /* The rest of result members is bzeroed in malloc */
   mysql->fields=0;              /* fields is now in result */
   clear_alloc_root(&mysql->field_alloc);
   /* just in case this was mistakenly called after mysql_stmt_execute() */
   mysql->unbuffered_fetch_owner= 0;
   DBUG_RETURN(result);              /* Data fetched */
 }
References st_mysql::affected_rows, clear_alloc_root, CR_COMMANDS_OUT_OF_SYNC, CR_OUT_OF_MEMORY, DBUG_ENTER, DBUG_RETURN, st_mysql::field_alloc, st_mysql::field_count, st_mysql::fields, st_mysql::methods, my_free(), my_malloc(), MY_WME, MY_ZEROFILL, MYF, MYSQL_STATUS_GET_RESULT, MYSQL_STATUS_READY, st_mysql_methods::read_rows, set_mysql_error(), st_mysql::status, st_mysql::unbuffered_fetch_owner, and unknown_sqlstate.
Referenced by MySQLConnection::_Query(), mysql_list_dbs(), mysql_list_processes(), and mysql_list_tables().
mysql_thread_end()
void STDCALL mysql_thread_end (void)
Definition at line 233 of file libmysql.c.
 {
   my_thread_end();
 }
References my_thread_end().
Referenced by mysql_server_end().
mysql_thread_id()
unsigned long STDCALL mysql_thread_id (MYSQL * mysql)
Definition at line 1059 of file libmysql.c.
 {
   return (mysql)->thread_id;
 }
mysql_thread_init()
my_bool STDCALL mysql_thread_init (void)
Definition at line 228 of file libmysql.c.
 {
   return my_thread_init();
 }
References my_thread_init().
mysql_thread_safe()
unsigned int STDCALL mysql_thread_safe (void)
Definition at line 1085 of file libmysql.c.
 {
   return 1;
 }
Referenced by DatabaseWorkerPool< T >::DatabaseWorkerPool().
mysql_use_result()
MYSQL_RES* STDCALL mysql_use_result (MYSQL * mysql)
Definition at line 4823 of file libmysql.c.
 {
   return (*mysql->methods->use_result)(mysql);
 }
References st_mysql::methods, and st_mysql_methods::use_result.
mysql_warning_count()
unsigned int STDCALL mysql_warning_count (MYSQL * mysql)
Definition at line 1049 of file libmysql.c.
 {
   return mysql->warning_count;
 }
References st_mysql::warning_count.
Variable Documentation
mysql_port
unsigned int mysql_port extern
Definition at line 118 of file client.c.
Referenced by mysql_server_init().
mysql_unix_port
char* mysql_unix_port extern
Definition at line 119 of file client.c.
Referenced by mysql_server_init().