Azerotcore-wotlk: src/server/game/AI/CreatureAIImpl.h File Reference
CreatureAIImpl.h File Reference
#include "Common.h"
#include "CreatureAI.h"
#include "Define.h"
#include "SpellMgr.h"
#include "TemporarySummon.h"
#include <functional>
#include <type_traits>
Classes
struct AISpellInfoType
Macros
#define AI_DEFAULT_COOLDOWN 5000
Enumerations
enum AITarget {
AITARGET_SELF , AITARGET_VICTIM , AITARGET_ENEMY , AITARGET_ALLY ,
AITARGET_BUFF , AITARGET_DEBUFF
}
enum AICondition { AICOND_AGGRO , AICOND_COMBAT , AICOND_DIE }
Functions
template<typename First , typename Second , typename... Rest>
static First const & RAND (First const &first, Second const &second, Rest const &... rest)
AISpellInfoType * GetAISpellInfo (uint32 i)
bool InstanceHasScript (WorldObject const *obj, char const *scriptName)
template<class AI , class T >
AI * GetInstanceAI (T *obj, char const *scriptName)
Macro Definition Documentation
AI_DEFAULT_COOLDOWN
#define AI_DEFAULT_COOLDOWN 5000
Definition at line 53 of file CreatureAIImpl.h.
Enumeration Type Documentation
AICondition
enum AICondition
Enumerator
AICOND_AGGRO
AICOND_COMBAT
AICOND_DIE
Definition at line 46 of file CreatureAIImpl.h.
 {
     AICOND_AGGRO,
     AICOND_COMBAT,
     AICOND_DIE,
 };
AITarget
enum AITarget
Enumerator
AITARGET_SELF
AITARGET_VICTIM
AITARGET_ENEMY
AITARGET_ALLY
AITARGET_BUFF
AITARGET_DEBUFF
Definition at line 36 of file CreatureAIImpl.h.
 {
     AITARGET_SELF,
     AITARGET_VICTIM,
     AITARGET_ENEMY,
     AITARGET_ALLY,
     AITARGET_BUFF,
     AITARGET_DEBUFF,
 };
Function Documentation
GetAISpellInfo()
AISpellInfoType* GetAISpellInfo (uint32 i)
Definition at line 53 of file CreatureAI.cpp.
 { return &CreatureAI::AISpellInfo[i]; }
References UnitAI::AISpellInfo.
Referenced by CasterAI::EnterCombat(), CasterAI::InitializeAI(), and CasterAI::UpdateAI().
GetInstanceAI()
template<class AI , class T > AI* GetInstanceAI (T * obj, char const * scriptName) inline
Definition at line 71 of file CreatureAIImpl.h.
 {
     return InstanceHasScript(obj, scriptName) ? new AI(obj) : nullptr;
 }
References InstanceHasScript().
InstanceHasScript()
bool InstanceHasScript (WorldObject const * obj, char const * scriptName)
Definition at line 582 of file InstanceScript.cpp.
 {
     if (InstanceMap* instance = obj->GetMap()->ToInstanceMap())
     {
         return instance->GetScriptName() == scriptName;
     }
     return false;
 }
References WorldObject::GetMap(), and Map::ToInstanceMap().
Referenced by GetInstanceAI().
RAND()
template<typename First , typename Second , typename... Rest> static First const& RAND (First const & first, Second const & second, Rest const &... rest) inline static
Definition at line 30 of file CreatureAIImpl.h.
 {
     std::reference_wrapper<typename std::add_const<First>::type> const pack[] = { first, second, rest... };
     return pack[urand(0, sizeof...(rest) + 1)].get();
 }
References detail::first(), and urand().
Referenced by npc_time_rift::npc_time_riftAI::DoSelectSummon(), boss_laj::boss_lajAI::DoTransform(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::EmpowerCultist(), boss_prince_valanar_icc::boss_prince_valanarAI::EnterCombat(), npc_simon_bunny::npc_simon_bunnyAI::GenerateColorSequence(), go_wind_stone::go_wind_stoneAI::GossipSelect(), spell_cataclysm_breath::spell_cataclysm_breath_SpellScript::HandleAfterCast(), spell_voodoo::spell_voodoo_SpellScript::HandleDummy(), spell_dred_raptor_call::spell_dred_raptor_call_SpellScript::HandleDummy(), spell_item_vanquished_clutches::HandleDummy(), Unit::HandleDummyAuraProc(), spell_q10930_big_bone_worm::spell_q10930_big_bone_worm_AuraScript::HandleEffectRemove(), spell_q10929_fumping::spell_q10929_fumping_AuraScript::HandleEffectRemove(), spell_halion_meteor_strike_spread::spell_halion_meteor_strike_spread_AuraScript::HandlePeriodic(), spell_q10923_evil_draws_near_periodic::spell_q10923_evil_draws_near_periodic_AuraScript::HandlePeriodic(), spell_winter_veil_mistletoe::spell_winter_veil_mistletoe_SpellScript::HandleScript(), spell_q13011_bear_flank_master::HandleScript(), spell_lady_vashj_summon_sporebat::spell_lady_vashj_summon_sporebat_SpellScript::HandleScriptEffect(), spell_winter_wondervolt_trap::spell_winter_wondervolt_trap_SpellScript::HandleScriptEffect(), spell_dtk_summon_random_drakkari::spell_dtk_summon_random_drakkari_SpellScript::HandleScriptEffect(), spell_q14112_14145_chum_the_water::HandleScriptEffect(), boss_moroes::boss_moroesAI::InitializeGuests(), npc_aged_dying_ancient_kodo::npc_aged_dying_ancient_kodoAI::JustRespawned(), npc_medivh_bm::npc_medivh_bmAI::JustSummoned(), npc_necromancer::npc_necromancerAI::KilledUnit(), boss_falric::boss_falricAI::KilledUnit(), boss_marwyn::boss_marwynAI::KilledUnit(), boss_ick::boss_ickAI::KilledUnit(), boss_tyrannus::boss_tyrannusAI::KilledUnit(), npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::npc_vh_teleportation_portalAI(), spell_item_ashbringer::OnDummyEffect(), spell_love_is_in_the_air_romantic_picnic::spell_love_is_in_the_air_romantic_picnic_AuraScript::OnPeriodic(), npc_anub_ar_crusher::npc_anub_ar_crusherAI::Reset(), boss_gathios_the_shatterer::boss_gathios_the_shattererAI::SelectCouncilMember(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SetBossState(), pyrewood_ambush::pyrewood_ambushAI::SummonCreatureWithRandomTarget(), instance_the_black_morass::instance_the_black_morass_InstanceMapScript::SummonPortalKeeper(), spell_mother_shahraz_random_periodic::spell_mother_shahraz_random_periodic_AuraScript::Update(), boss_chromaggus::boss_chromaggusAI::UpdateAI(), boss_curator::boss_curatorAI::UpdateAI(), boss_kalecgos::boss_kalecgosAI::UpdateAI(), npc_love_in_air_hummel_helper::npc_love_in_air_hummel_helperAI::UpdateAI(), boss_eye_of_cthun::eye_of_cthunAI::UpdateAI(), npc_toc_enh_shaman::npc_toc_enh_shamanAI::UpdateAI(), boss_novos::boss_novosAI::UpdateAI(), boss_marwyn::boss_marwynAI::UpdateAI(), boss_ick::boss_ickAI::UpdateAI(), boss_kelthuzad::boss_kelthuzadAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateAI(), boss_xevozz::boss_xevozzAI::UpdateAI(), npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::UpdateAI(), boss_nexusprince_shaffar::boss_nexusprince_shaffarAI::UpdateAI(), boss_mother_shahraz::boss_shahrazAI::UpdateAI(), boss_gathios_the_shatterer::boss_gathios_the_shattererAI::UpdateAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::UpdateAI(), npc_warden_mellichar::npc_warden_mellicharAI::UpdateAI(), boss_high_botanist_freywinn::boss_high_botanist_freywinnAI::UpdateAI(), boss_alar::boss_alarAI::UpdateAI(), npc_pet_hunter_snake_trap::UpdateAI(), and boss_yoggsaron_corruptor_tentacle::boss_yoggsaron_corruptor_tentacleAI::UpdateAI().