Azerotcore-wotlk: deps/recastnavigation/Recast/Source/Recast.cpp File Reference
Recast.cpp File Reference
#include <float.h>
#include <math.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <stdarg.h>
#include "Recast.h"
#include "RecastAlloc.h"
#include "RecastAssert.h"
Namespaces
anonymous_namespace{Recast.cpp}
Macros
#define _USE_MATH_DEFINES
Functions
template<typename T >
T * anonymous_namespace{Recast.cpp}::rcNew (rcAllocHint hint)
template<typename T >
void anonymous_namespace{Recast.cpp}::rcDelete (T *ptr)
float rcSqrt (float x)
rcHeightfield * rcAllocHeightfield ()
void rcFreeHeightField (rcHeightfield *hf)
rcCompactHeightfield * rcAllocCompactHeightfield ()
void rcFreeCompactHeightfield (rcCompactHeightfield *chf)
rcHeightfieldLayerSet * rcAllocHeightfieldLayerSet ()
void rcFreeHeightfieldLayerSet (rcHeightfieldLayerSet *lset)
rcContourSet * rcAllocContourSet ()
void rcFreeContourSet (rcContourSet *cset)
rcPolyMesh * rcAllocPolyMesh ()
void rcFreePolyMesh (rcPolyMesh *pmesh)
rcPolyMeshDetail * rcAllocPolyMeshDetail ()
void rcFreePolyMeshDetail (rcPolyMeshDetail *dmesh)
void rcCalcBounds (const float *verts, int nv, float *bmin, float *bmax)
void rcCalcGridSize (const float *bmin, const float *bmax, float cs, int *w, int *h)
bool rcCreateHeightfield (rcContext *ctx, rcHeightfield &hf, int width, int height, const float *bmin, const float *bmax, float cs, float ch)
static void calcTriNormal (const float *v0, const float *v1, const float *v2, float *norm)
void rcMarkWalkableTriangles (rcContext *ctx, const float walkableSlopeAngle, const float *verts, int nv, const int *tris, int nt, unsigned char *areas)
void rcClearUnwalkableTriangles (rcContext *ctx, const float walkableSlopeAngle, const float *verts, int, const int *tris, int nt, unsigned char *areas)
int rcGetHeightFieldSpanCount (rcContext *ctx, rcHeightfield &hf)
bool rcBuildCompactHeightfield (rcContext *ctx, const int walkableHeight, const int walkableClimb, rcHeightfield &hf, rcCompactHeightfield &chf)
Macro Definition Documentation
_USE_MATH_DEFINES
#define _USE_MATH_DEFINES
Definition at line 20 of file Recast.cpp.
Function Documentation
calcTriNormal()
static void calcTriNormal (const float * v0, const float * v1, const float * v2, float * norm) static
Definition at line 317 of file Recast.cpp.
 {
     float e0[3], e1[3];
     rcVsub(e0, v1, v0);
     rcVsub(e1, v2, v0);
     rcVcross(norm, e0, e1);
     rcVnormalize(norm);
 }
References rcVcross(), rcVnormalize(), and rcVsub().
Referenced by rcClearUnwalkableTriangles(), and rcMarkWalkableTriangles().
rcAllocCompactHeightfield()
rcCompactHeightfield* rcAllocCompactHeightfield ()
Allocates a compact heightfield object using the Recast allocator.
Returns
A compact heightfield that is ready for initialization, or null on failure.
See also
rcBuildCompactHeightfield, rcFreeCompactHeightfield
Definition at line 132 of file Recast.cpp.
 {
     return rcNew<rcCompactHeightfield>(RC_ALLOC_PERM);
 }
References RC_ALLOC_PERM.
Referenced by TileBuilder::BuildInstance(), MMAP::MapBuilder::buildMoveMapTile(), and TileBuilder::BuildTiled().
rcAllocContourSet()
rcContourSet* rcAllocContourSet ()
Allocates a contour set object using the Recast allocator.
Returns
A contour set that is ready for initialization, or null on failure.
See also
rcBuildContours, rcFreeContourSet
Definition at line 192 of file Recast.cpp.
 {
     return rcNew<rcContourSet>(RC_ALLOC_PERM);
 }
References RC_ALLOC_PERM.
Referenced by TileBuilder::BuildInstance(), MMAP::MapBuilder::buildMoveMapTile(), and TileBuilder::BuildTiled().
rcAllocHeightfield()
rcHeightfield* rcAllocHeightfield ()
Allocates a heightfield object using the Recast allocator.
Returns
A heightfield that is ready for initialization, or null on failure.
See also
rcCreateHeightfield, rcFreeHeightField
Definition at line 97 of file Recast.cpp.
 {
     return rcNew<rcHeightfield>(RC_ALLOC_PERM);
 }
References RC_ALLOC_PERM.
Referenced by TileBuilder::BuildInstance(), MMAP::MapBuilder::buildMoveMapTile(), and TileBuilder::BuildTiled().
rcAllocHeightfieldLayerSet()
rcHeightfieldLayerSet* rcAllocHeightfieldLayerSet ()
Allocates a heightfield layer set using the Recast allocator.
Returns
A heightfield layer set that is ready for initialization, or null on failure.
See also
rcBuildHeightfieldLayers, rcFreeHeightfieldLayerSet
Definition at line 169 of file Recast.cpp.
 {
     return rcNew<rcHeightfieldLayerSet>(RC_ALLOC_PERM);
 }
References RC_ALLOC_PERM.
rcAllocPolyMesh()
rcPolyMesh* rcAllocPolyMesh ()
Allocates a polygon mesh object using the Recast allocator.
Returns
A polygon mesh that is ready for initialization, or null on failure.
See also
rcBuildPolyMesh, rcFreePolyMesh
Definition at line 223 of file Recast.cpp.
 {
     return rcNew<rcPolyMesh>(RC_ALLOC_PERM);
 }
References RC_ALLOC_PERM.
Referenced by TileBuilder::BuildInstance(), MMAP::MapBuilder::buildMoveMapTile(), and TileBuilder::BuildTiled().
rcAllocPolyMeshDetail()
rcPolyMeshDetail* rcAllocPolyMeshDetail ()
Allocates a detail mesh object using the Recast allocator.
Returns
A detail mesh that is ready for initialization, or null on failure.
See also
rcBuildPolyMeshDetail, rcFreePolyMeshDetail
Definition at line 258 of file Recast.cpp.
 {
     rcPolyMeshDetail* dmesh = (rcPolyMeshDetail*)rcAlloc(sizeof(rcPolyMeshDetail), RC_ALLOC_PERM);
     memset(dmesh, 0, sizeof(rcPolyMeshDetail));
     return dmesh;
 }
References memset, RC_ALLOC_PERM, and rcAlloc().
Referenced by TileBuilder::BuildInstance(), MMAP::MapBuilder::buildMoveMapTile(), and TileBuilder::BuildTiled().
rcBuildCompactHeightfield()
bool rcBuildCompactHeightfield (rcContext * ctx, const int walkableHeight, const int walkableClimb, rcHeightfield & hf, rcCompactHeightfield & chf)
This is just the beginning of the process of fully building a compact heightfield. Various filters may be applied, then the distance field and regions built. E.g: rcBuildDistanceField and rcBuildRegions
See the rcConfig documentation for more information on the configuration parameters.
See also
rcAllocCompactHeightfield, rcHeightfield, rcCompactHeightfield, rcConfig
Definition at line 415 of file Recast.cpp.
 {
     rcAssert(ctx);
     rcScopedTimer timer(ctx, RC_TIMER_BUILD_COMPACTHEIGHTFIELD);
     const int w = hf.width;
     const int h = hf.height;
     const int spanCount = rcGetHeightFieldSpanCount(ctx, hf);
     // Fill in header.
     chf.width = w;
     chf.height = h;
     chf.spanCount = spanCount;
     chf.walkableHeight = walkableHeight;
     chf.walkableClimb = walkableClimb;
     chf.maxRegions = 0;
     rcVcopy(chf.bmin, hf.bmin);
     rcVcopy(chf.bmax, hf.bmax);
     chf.bmax[1] += walkableHeight*hf.ch;
     chf.cs = hf.cs;
     chf.ch = hf.ch;
     chf.cells = (rcCompactCell*)rcAlloc(sizeof(rcCompactCell)*w*h, RC_ALLOC_PERM);
     if (!chf.cells)
     {
         ctx->log(RC_LOG_ERROR, "rcBuildCompactHeightfield: Out of memory 'chf.cells' (%d)", w*h);
         return false;
     }
     memset(chf.cells, 0, sizeof(rcCompactCell)*w*h);
     chf.spans = (rcCompactSpan*)rcAlloc(sizeof(rcCompactSpan)*spanCount, RC_ALLOC_PERM);
     if (!chf.spans)
     {
         ctx->log(RC_LOG_ERROR, "rcBuildCompactHeightfield: Out of memory 'chf.spans' (%d)", spanCount);
         return false;
     }
     memset(chf.spans, 0, sizeof(rcCompactSpan)*spanCount);
     chf.areas = (unsigned char*)rcAlloc(sizeof(unsigned char)*spanCount, RC_ALLOC_PERM);
     if (!chf.areas)
     {
         ctx->log(RC_LOG_ERROR, "rcBuildCompactHeightfield: Out of memory 'chf.areas' (%d)", spanCount);
         return false;
     }
     memset(chf.areas, RC_NULL_AREA, sizeof(unsigned char)*spanCount);
     const int MAX_HEIGHT = 0xffff;
     // Fill in cells and spans.
     int idx = 0;
     for (int y = 0; y < h; ++y)
     {
         for (int x = 0; x < w; ++x)
         {
             const rcSpan* s = hf.spans[x + y*w];
             // If there are no spans at this cell, just leave the data to index=0, count=0.
             if (!s) continue;
             rcCompactCell& c = chf.cells[x+y*w];
             c.index = idx;
             c.count = 0;
             while (s)
             {
                 if (s->area != RC_NULL_AREA)
                 {
                     const int bot = (int)s->smax;
                     const int top = s->next ? (int)s->next->smin : MAX_HEIGHT;
                     chf.spans[idx].y = (unsigned short)rcClamp(bot, 0, 0xffff);
                     chf.spans[idx].h = (unsigned char)rcClamp(top - bot, 0, 0xff);
                     chf.areas[idx] = s->area;
                     idx++;
                     c.count++;
                 }
                 s = s->next;
             }
         }
     }
     // Find neighbour connections.
     const int MAX_LAYERS = RC_NOT_CONNECTED-1;
     int tooHighNeighbour = 0;
     for (int y = 0; y < h; ++y)
     {
         for (int x = 0; x < w; ++x)
         {
             const rcCompactCell& c = chf.cells[x+y*w];
             for (int i = (int)c.index, ni = (int)(c.index+c.count); i < ni; ++i)
             {
                 rcCompactSpan& s = chf.spans[i];
                 for (int dir = 0; dir < 4; ++dir)
                 {
                     rcSetCon(s, dir, RC_NOT_CONNECTED);
                     const int nx = x + rcGetDirOffsetX(dir);
                     const int ny = y + rcGetDirOffsetY(dir);
                     // First check that the neighbour cell is in bounds.
                     if (nx < 0 || ny < 0 || nx >= w || ny >= h)
                         continue;
                     // Iterate over all neighbour spans and check if any of the is
                     // accessible from current cell.
                     const rcCompactCell& nc = chf.cells[nx+ny*w];
                     for (int k = (int)nc.index, nk = (int)(nc.index+nc.count); k < nk; ++k)
                     {
                         const rcCompactSpan& ns = chf.spans[k];
                         const int bot = rcMax(s.y, ns.y);
                         const int top = rcMin(s.y+s.h, ns.y+ns.h);
                         // Check that the gap between the spans is walkable,
                         // and that the climb height between the gaps is not too high.
                         if ((top - bot) >= walkableHeight && rcAbs((int)ns.y - (int)s.y) <= walkableClimb)
{
                             // Mark direction as walkable.
                             const int lidx = k - (int)nc.index;
                             if (lidx < 0 || lidx > MAX_LAYERS)
{
                                 tooHighNeighbour = rcMax(tooHighNeighbour, lidx);
                                 continue;
                             }
                             rcSetCon(s, dir, lidx);
                             break;
                         }
                     }
                 }
             }
         }
     }
     if (tooHighNeighbour > MAX_LAYERS)
     {
         ctx->log(RC_LOG_ERROR, "rcBuildCompactHeightfield: Heightfield has too many layers %d (max: %d)",
                  tooHighNeighbour, MAX_LAYERS);
     }
     return true;
 }
References rcSpan::area, rcCompactHeightfield::areas, rcHeightfield::bmax, rcCompactHeightfield::bmax, rcHeightfield::bmin, rcCompactHeightfield::bmin, mpq::c, rcCompactHeightfield::cells, rcHeightfield::ch, rcCompactHeightfield::ch, rcCompactCell::count, rcHeightfield::cs, rcCompactHeightfield::cs, rcCompactSpan::h, rcHeightfield::height, rcCompactHeightfield::height, idx, if(), rcCompactCell::index, rcContext::log(), MAX_HEIGHT, rcCompactHeightfield::maxRegions, memset, rcSpan::next, RC_ALLOC_PERM, RC_LOG_ERROR, RC_NOT_CONNECTED, RC_NULL_AREA, RC_TIMER_BUILD_COMPACTHEIGHTFIELD, rcAbs(), rcAlloc(), rcAssert, rcClamp(), rcGetDirOffsetX(), rcGetDirOffsetY(), rcGetHeightFieldSpanCount(), rcMax(), rcMin(), rcSetCon(), rcVcopy(), rcSpan::smax, rcSpan::smin, rcCompactHeightfield::spanCount, rcHeightfield::spans, rcCompactHeightfield::spans, rcCompactHeightfield::walkableClimb, rcCompactHeightfield::walkableHeight, rcHeightfield::width, rcCompactHeightfield::width, G3D::x, G3D::y, and rcCompactSpan::y.
Referenced by TileBuilder::BuildInstance(), MMAP::MapBuilder::buildMoveMapTile(), and TileBuilder::BuildTiled().
rcCalcBounds()
void rcCalcBounds (const float * verts, int nv, float * bmin, float * bmax)
Calculates the bounding box of an array of vertices.
Parameters
[in] verts An array of vertices. [(x, y, z) * nv]
[in] nv The number of vertices in the verts array.
[out] bmin The minimum bounds of the AABB. [(x, y, z)] [Units: wu]
[out] bmax The maximum bounds of the AABB. [(x, y, z)] [Units: wu]
Definition at line 274 of file Recast.cpp.
 {
     // Calculate bounding box.
     rcVcopy(bmin, verts);
     rcVcopy(bmax, verts);
     for (int i = 1; i < nv; ++i)
     {
         const float* v = &verts[i*3];
         rcVmin(bmin, v);
         rcVmax(bmax, v);
     }
 }
References rcVcopy(), rcVmax(), and rcVmin().
Referenced by MMAP::MapBuilder::getGridBounds(), ContinentBuilder::getTileBounds(), and MMAP::MapBuilder::getTileBounds().
rcCalcGridSize()
void rcCalcGridSize (const float * bmin, const float * bmax, float cs, int * w, int * h)
Calculates the grid size based on the bounding box and grid cell size.
Parameters
[in] bmin The minimum bounds of the AABB. [(x, y, z)] [Units: wu]
[in] bmax The maximum bounds of the AABB. [(x, y, z)] [Units: wu]
[in] cs The xz-plane cell size. [Limit: > 0] [Units: wu]
[out] w The width along the x-axis. [Limit: >= 0] [Units: vx]
[out] h The height along the z-axis. [Limit: >= 0] [Units: vx]
Definition at line 287 of file Recast.cpp.
 {
     *w = (int)((bmax[0] - bmin[0])/cs+0.5f);
     *h = (int)((bmax[2] - bmin[2])/cs+0.5f);
 }
Referenced by TileBuilder::BuildInstance(), and MMAP::MapBuilder::buildMoveMapTile().
rcClearUnwalkableTriangles()
void rcClearUnwalkableTriangles (rcContext * ctx, const float walkableSlopeAngle, const float * verts, int nv, const int * tris, int nt, unsigned char * areas)
Only sets the area id's for the unwalkable triangles. Does not alter the area id's for walkable triangles.
See the rcConfig documentation for more information on the configuration parameters.
See also
rcHeightfield, rcClearUnwalkableTriangles, rcRasterizeTriangles
Definition at line 364 of file Recast.cpp.
 {
     rcIgnoreUnused(ctx);
     const float walkableThr = cosf(walkableSlopeAngle/180.0f*RC_PI);
     float norm[3];
     for (int i = 0; i < nt; ++i)
     {
         const int* tri = &tris[i*3];
         calcTriNormal(&verts[tri[0]*3], &verts[tri[1]*3], &verts[tri[2]*3], norm);
         // Check if the face is walkable.
         if (norm[1] <= walkableThr)
             areas[i] = RC_NULL_AREA;
     }
 }
References calcTriNormal(), RC_NULL_AREA, RC_PI, and rcIgnoreUnused().
Referenced by TileBuilder::BuildInstance(), MMAP::MapBuilder::buildMoveMapTile(), and TileBuilder::BuildTiled().
rcCreateHeightfield()
bool rcCreateHeightfield (rcContext * ctx, rcHeightfield & hf, int width, int height, const float * bmin, const float * bmax, float cs, float ch)
See the rcConfig documentation for more information on the configuration parameters.
See also
rcAllocHeightfield, rcHeightfield
Definition at line 298 of file Recast.cpp.
 {
     rcIgnoreUnused(ctx);
     hf.width = width;
     hf.height = height;
     rcVcopy(hf.bmin, bmin);
     rcVcopy(hf.bmax, bmax);
     hf.cs = cs;
     hf.ch = ch;
     hf.spans = (rcSpan**)rcAlloc(sizeof(rcSpan*)*hf.width*hf.height, RC_ALLOC_PERM);
     if (!hf.spans)
         return false;
     memset(hf.spans, 0, sizeof(rcSpan*)*hf.width*hf.height);
     return true;
 }
References rcHeightfield::bmax, rcHeightfield::bmin, rcHeightfield::ch, rcHeightfield::cs, rcHeightfield::height, memset, RC_ALLOC_PERM, rcAlloc(), rcIgnoreUnused(), rcVcopy(), rcHeightfield::spans, width, and rcHeightfield::width.
Referenced by TileBuilder::BuildInstance(), MMAP::MapBuilder::buildMoveMapTile(), and TileBuilder::BuildTiled().
rcFreeCompactHeightfield()
void rcFreeCompactHeightfield (rcCompactHeightfield * chf)
Frees the specified compact heightfield object using the Recast allocator.
Parameters
[in] chf A compact heightfield allocated using rcAllocCompactHeightfield
See also
rcAllocCompactHeightfield
Definition at line 137 of file Recast.cpp.
 {
     rcDelete(chf);
 }
References anonymous_namespace{Recast.cpp}::rcDelete().
Referenced by TileBuilder::BuildInstance(), MMAP::MapBuilder::buildMoveMapTile(), TileBuilder::BuildTiled(), MMAP::IntermediateValues::~IntermediateValues(), and MMAP::Tile::~Tile().
rcFreeContourSet()
void rcFreeContourSet (rcContourSet * cset)
Frees the specified contour set using the Recast allocator.
Parameters
[in] cset A contour set allocated using rcAllocContourSet
See also
rcAllocContourSet
Definition at line 196 of file Recast.cpp.
 {
     rcDelete(cset);
 }
References anonymous_namespace{Recast.cpp}::rcDelete().
Referenced by TileBuilder::BuildInstance(), MMAP::MapBuilder::buildMoveMapTile(), TileBuilder::BuildTiled(), MMAP::IntermediateValues::~IntermediateValues(), and MMAP::Tile::~Tile().
rcFreeHeightField()
void rcFreeHeightField (rcHeightfield * hf)
Frees the specified heightfield object using the Recast allocator.
Parameters
[in] hf A heightfield allocated using rcAllocHeightfield
See also
rcAllocHeightfield
Definition at line 127 of file Recast.cpp.
 {
     rcDelete(hf);
 }
References anonymous_namespace{Recast.cpp}::rcDelete().
Referenced by TileBuilder::BuildInstance(), MMAP::MapBuilder::buildMoveMapTile(), TileBuilder::BuildTiled(), MMAP::IntermediateValues::~IntermediateValues(), and MMAP::Tile::~Tile().
rcFreeHeightfieldLayerSet()
void rcFreeHeightfieldLayerSet (rcHeightfieldLayerSet * lset)
Frees the specified heightfield layer set using the Recast allocator.
Parameters
[in] lset A heightfield layer set allocated using rcAllocHeightfieldLayerSet
See also
rcAllocHeightfieldLayerSet
Definition at line 173 of file Recast.cpp.
 {
     rcDelete(lset);
 }
References anonymous_namespace{Recast.cpp}::rcDelete().
rcFreePolyMesh()
void rcFreePolyMesh (rcPolyMesh * pmesh)
Frees the specified polygon mesh using the Recast allocator.
Parameters
[in] pmesh A polygon mesh allocated using rcAllocPolyMesh
See also
rcAllocPolyMesh
Definition at line 227 of file Recast.cpp.
 {
     rcDelete(pmesh);
 }
References anonymous_namespace{Recast.cpp}::rcDelete().
Referenced by TileBuilder::BuildInstance(), TileBuilder::BuildTiled(), MMAP::IntermediateValues::~IntermediateValues(), and MMAP::Tile::~Tile().
rcFreePolyMeshDetail()
void rcFreePolyMeshDetail (rcPolyMeshDetail * dmesh)
Frees the specified detail mesh using the Recast allocator.
Parameters
[in] dmesh A detail mesh allocated using rcAllocPolyMeshDetail
See also
rcAllocPolyMeshDetail
Definition at line 265 of file Recast.cpp.
 {
     if (!dmesh) return;
     rcFree(dmesh->meshes);
     rcFree(dmesh->verts);
     rcFree(dmesh->tris);
     rcFree(dmesh);
 }
References rcPolyMeshDetail::meshes, rcFree(), rcPolyMeshDetail::tris, and rcPolyMeshDetail::verts.
Referenced by TileBuilder::BuildInstance(), TileBuilder::BuildTiled(), MMAP::IntermediateValues::~IntermediateValues(), and MMAP::Tile::~Tile().
rcGetHeightFieldSpanCount()
int rcGetHeightFieldSpanCount (rcContext * ctx, rcHeightfield & hf)
Returns the number of spans contained in the specified heightfield.
Parameters
[in,out] ctx The build context to use during the operation.
[in] hf An initialized heightfield.
Returns
The number of spans in the heightfield.
Definition at line 385 of file Recast.cpp.
 {
     rcIgnoreUnused(ctx);
     const int w = hf.width;
     const int h = hf.height;
     int spanCount = 0;
     for (int y = 0; y < h; ++y)
     {
         for (int x = 0; x < w; ++x)
         {
             for (rcSpan* s = hf.spans[x + y*w]; s; s = s->next)
             {
                 if (s->area != RC_NULL_AREA)
                     spanCount++;
             }
         }
     }
     return spanCount;
 }
References rcHeightfield::height, rcSpan::next, RC_NULL_AREA, rcIgnoreUnused(), rcHeightfield::spans, rcHeightfield::width, G3D::x, and G3D::y.
Referenced by rcBuildCompactHeightfield().
rcMarkWalkableTriangles()
void rcMarkWalkableTriangles (rcContext * ctx, const float walkableSlopeAngle, const float * verts, int nv, const int * tris, int nt, unsigned char * areas)
Only sets the area id's for the walkable triangles. Does not alter the area id's for unwalkable triangles.
See the rcConfig documentation for more information on the configuration parameters.
See also
rcHeightfield, rcClearUnwalkableTriangles, rcRasterizeTriangles
Definition at line 334 of file Recast.cpp.
 {
     rcIgnoreUnused(ctx);
     rcIgnoreUnused(nv);
     const float walkableThr = cosf(walkableSlopeAngle/180.0f*RC_PI);
     float norm[3];
     for (int i = 0; i < nt; ++i)
     {
         const int* tri = &tris[i*3];
         calcTriNormal(&verts[tri[0]*3], &verts[tri[1]*3], &verts[tri[2]*3], norm);
         // Check if the face is walkable.
         if (norm[1] > walkableThr)
             areas[i] = RC_WALKABLE_AREA;
     }
 }
References calcTriNormal(), RC_PI, RC_WALKABLE_AREA, and rcIgnoreUnused().
rcSqrt()
float rcSqrt (float x)
Returns the square root of the value.
Parameters
[in] x The value.
Returns
The square root of the vlaue.
Definition at line 54 of file Recast.cpp.
 {
     return sqrtf(x);
 }
References G3D::x.
Referenced by polyMinExtent(), rcOffsetPoly(), rcVdist(), and rcVnormalize().