Azerotcore-wotlk: boss_romulo::boss_romuloAI Struct Reference
boss_romulo::boss_romuloAI Struct Reference
Public Member Functions
boss_romuloAI (Creature *creature)
void Reset () override
void JustReachedHome () override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void EnterCombat (Unit *) override
void MoveInLineOfSight (Unit *who) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * instance
ObjectGuid JulianneGUID
uint32 Phase
uint32 EntryYellTimer
uint32 AggroYellTimer
uint32 BackwardLungeTimer
uint32 DaringTimer
uint32 DeadlySwatheTimer
uint32 PoisonThrustTimer
uint32 ResurrectTimer
bool IsFakingDeath
bool JulianneDead
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1167 of file bosses_opera.cpp.
Constructor & Destructor Documentation
boss_romuloAI()
boss_romulo::boss_romuloAI::boss_romuloAI (Creature * creature) inline
Definition at line 1169 of file bosses_opera.cpp.
                                           : ScriptedAI(creature)
         {
             instance = creature->GetInstanceScript();
             EntryYellTimer = 8000;
             AggroYellTimer = 15000;
         }
References WorldObject::GetInstanceScript().
Member Function Documentation
DamageTaken()
void boss_romulo::boss_romuloAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1212 of file bosses_opera.cpp.
         {
             if (damage < me->GetHealth())
                 return;
             //anything below only used if incoming damage will kill
             if (Phase == PHASE_ROMULO)
             {
                 Talk(SAY_ROMULO_DEATH);
                 PretendToDie(me);
                 IsFakingDeath = true;
                 Phase = PHASE_BOTH;
                 if (Creature* Julianne = (ObjectAccessor::GetCreature((*me), JulianneGUID)))
                 {
                     CAST_AI(boss_julianne::boss_julianneAI, Julianne->AI())->RomuloDead = true;
                     CAST_AI(boss_julianne::boss_julianneAI, Julianne->AI())->ResurrectSelfTimer = 10000;
                 }
                 damage = 0;
                 return;
             }
             if (Phase == PHASE_BOTH)
             {
                 if (JulianneDead)
                 {
                     if (Creature* Julianne = (ObjectAccessor::GetCreature((*me), JulianneGUID)))
                     {
                         Julianne->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                         Julianne->GetMotionMaster()->Clear();
                         Julianne->setDeathState(JUST_DIED);
                         Julianne->CombatStop(true);
                         Julianne->DeleteThreatList();
                         Julianne->SetUInt32Value(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_LOOTABLE);
                     }
                     return;
                 }
                 if (Creature* Julianne = (ObjectAccessor::GetCreature((*me), JulianneGUID)))
                 {
                     PretendToDie(me);
                     IsFakingDeath = true;
                     CAST_AI(boss_julianne::boss_julianneAI, Julianne->AI())->ResurrectTimer = 10000;
                     CAST_AI(boss_julianne::boss_julianneAI, Julianne->AI())->RomuloDead = true;
                     damage = 0;
                     return;
                 }
             }
             //TC_LOG_ERROR("scripts", "boss_romuloAI: DamageTaken reach end of code, that should not happen.");
         }
References CAST_AI, ObjectAccessor::GetCreature(), JUST_DIED, PHASE_BOTH, PHASE_ROMULO, PretendToDie(), SAY_ROMULO_DEATH, UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_LOOTABLE, UNIT_FIELD_FLAGS, and UNIT_FLAG_NOT_SELECTABLE.
EnterCombat()
void boss_romulo::boss_romuloAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1266 of file bosses_opera.cpp.
         {
             DoZoneInCombat();
             Talk(SAY_ROMULO_AGGRO);
             if (JulianneGUID)
             {
                 Creature* Julianne = ObjectAccessor::GetCreature(*me, JulianneGUID);
                 if (Julianne && Julianne->GetVictim())
                 {
                     me->AddThreat(Julianne->GetVictim(), 1.0f);
                     AttackStart(Julianne->GetVictim());
                 }
             }
         }
References ObjectAccessor::GetCreature(), Unit::GetVictim(), and SAY_ROMULO_AGGRO.
JustDied()
void boss_romulo::boss_romuloAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1290 of file bosses_opera.cpp.
         {
             Talk(SAY_ROMULO_DEATH);
             instance->SetBossState(DATA_OPERA_PERFORMANCE, DONE);
         }
References DATA_OPERA_PERFORMANCE, DONE, SAY_ROMULO_DEATH, and InstanceScript::SetBossState().
JustReachedHome()
void boss_romulo::boss_romuloAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 1207 of file bosses_opera.cpp.
         {
             me->DespawnOrUnsummon();
         }
KilledUnit()
void boss_romulo::boss_romuloAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1297 of file bosses_opera.cpp.
         {
             Talk(SAY_ROMULO_SLAY);
         }
References SAY_ROMULO_SLAY.
MoveInLineOfSight()
void boss_romulo::boss_romuloAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
Definition at line 1281 of file bosses_opera.cpp.
         {
             if (me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE))
                 return;
             ScriptedAI::MoveInLineOfSight(who);
         }
References CreatureAI::MoveInLineOfSight(), UNIT_FIELD_FLAGS, and UNIT_FLAG_NON_ATTACKABLE.
Reset()
void boss_romulo::boss_romuloAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1192 of file bosses_opera.cpp.
         {
             JulianneGUID.Clear();
             Phase = PHASE_ROMULO;
             BackwardLungeTimer = 15000;
             DaringTimer = 20000;
             DeadlySwatheTimer = 25000;
             PoisonThrustTimer = 10000;
             ResurrectTimer = 10000;
             IsFakingDeath = false;
             JulianneDead = false;
         }
References ObjectGuid::Clear(), and PHASE_ROMULO.
UpdateAI()
void boss_romulo::boss_romuloAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1302 of file bosses_opera.cpp.
         {
             if (!UpdateVictim() || IsFakingDeath)
                 return;
             if (JulianneDead)
             {
                 if (ResurrectTimer <= diff)
                 {
                     Creature* Julianne = (ObjectAccessor::GetCreature((*me), JulianneGUID));
                     if (Julianne && CAST_AI(boss_julianne::boss_julianneAI, Julianne->AI())->IsFakingDeath)
                     {
                         Talk(SAY_ROMULO_RESURRECT);
                         Resurrect(Julianne);
                         CAST_AI(boss_julianne::boss_julianneAI, Julianne->AI())->IsFakingDeath = false;
                         JulianneDead = false;
                         ResurrectTimer = 10000;
                     }
                 }
                 else
                     ResurrectTimer -= diff;
             }
             if (BackwardLungeTimer <= diff)
             {
                 Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 1, 100, true);
                 if (target && !me->HasInArc(M_PI, target))
                 {
                     DoCast(target, SPELL_BACKWARD_LUNGE);
                     BackwardLungeTimer = urand(15000, 30000);
                 }
             }
             else
                 BackwardLungeTimer -= diff;
             if (DaringTimer <= diff)
             {
                 DoCast(me, SPELL_DARING);
                 DaringTimer = urand(20000, 40000);
             }
             else
                 DaringTimer -= diff;
             if (DeadlySwatheTimer <= diff)
             {
                 if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 100, true))
                     DoCast(target, SPELL_DEADLY_SWATHE);
                 DeadlySwatheTimer = urand(15000, 25000);
             }
             else
                 DeadlySwatheTimer -= diff;
             if (PoisonThrustTimer <= diff)
             {
                 DoCastVictim(SPELL_POISON_THRUST);
                 PoisonThrustTimer = urand(10000, 20000);
             }
             else
                 PoisonThrustTimer -= diff;
             DoMeleeAttackIfReady();
         }
References Creature::AI(), CAST_AI, diff(), ObjectAccessor::GetCreature(), Position::HasInArc(), M_PI, Resurrect(), SAY_ROMULO_RESURRECT, SELECT_TARGET_RANDOM, SPELL_BACKWARD_LUNGE, SPELL_DARING, SPELL_DEADLY_SWATHE, SPELL_POISON_THRUST, and urand().
Member Data Documentation
AggroYellTimer
uint32 boss_romulo::boss_romuloAI::AggroYellTimer
Definition at line 1182 of file bosses_opera.cpp.
BackwardLungeTimer
uint32 boss_romulo::boss_romuloAI::BackwardLungeTimer
Definition at line 1183 of file bosses_opera.cpp.
DaringTimer
uint32 boss_romulo::boss_romuloAI::DaringTimer
Definition at line 1184 of file bosses_opera.cpp.
DeadlySwatheTimer
uint32 boss_romulo::boss_romuloAI::DeadlySwatheTimer
Definition at line 1185 of file bosses_opera.cpp.
EntryYellTimer
uint32 boss_romulo::boss_romuloAI::EntryYellTimer
Definition at line 1181 of file bosses_opera.cpp.
instance
InstanceScript* boss_romulo::boss_romuloAI::instance
Definition at line 1176 of file bosses_opera.cpp.
IsFakingDeath
bool boss_romulo::boss_romuloAI::IsFakingDeath
Definition at line 1189 of file bosses_opera.cpp.
JulianneDead
bool boss_romulo::boss_romuloAI::JulianneDead
Definition at line 1190 of file bosses_opera.cpp.
JulianneGUID
ObjectGuid boss_romulo::boss_romuloAI::JulianneGUID
Definition at line 1178 of file bosses_opera.cpp.
Phase
uint32 boss_romulo::boss_romuloAI::Phase
Definition at line 1179 of file bosses_opera.cpp.
PoisonThrustTimer
uint32 boss_romulo::boss_romuloAI::PoisonThrustTimer
Definition at line 1186 of file bosses_opera.cpp.
ResurrectTimer
uint32 boss_romulo::boss_romuloAI::ResurrectTimer
Definition at line 1187 of file bosses_opera.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/Karazhan/bosses_opera.cpp