Azerotcore-wotlk: src/common/Utilities/Physics.h File Reference
Physics.h File Reference
#include "Geometry.h"
#include <cmath>
#include <cstdlib>
#include <iostream>
Functions
float getWeight (float height, float width, float specificWeight)
float getOutOfWater (float width, float weight, float density)
Get the height immersed in water.
Function Documentation
getOutOfWater()
float getOutOfWater (float width, float weight, float density) inline
Get the height immersed in water.
Parameters
height
width
weight specific weight
Returns
float
Definition at line 49 of file Physics.h.
 {
     auto baseArea = getCircleAreaByRadius(width / 2.0f);
     return weight / (baseArea * density);
 }
References getCircleAreaByRadius(), and width.
Referenced by WorldObject::GetMinHeightInWater().
getWeight()
float getWeight (float height, float width, float specificWeight) inline
Definition at line 34 of file Physics.h.
 {
     auto volume = getCylinderVolume(height, width / 2.0f);
     auto weight = volume * specificWeight;
     return weight;
 }
References getCylinderVolume(), and width.
Referenced by WorldObject::GetMinHeightInWater().