Azerotcore-wotlk: go_commandscript Class Reference
go_commandscript Class Reference
Public Member Functions
go_commandscript ()
ChatCommandTable GetCommands () const override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Static Public Member Functions
static bool DoTeleport (ChatHandler *handler, Position pos, uint32 mapId=MAPID_INVALID)
static bool HandleGoCreatureCIdCommand (ChatHandler *handler, Variant< Hyperlink< creature_entry >, uint32 > cId)
static bool HandleGoCreatureSpawnIdCommand (ChatHandler *handler, Variant< Hyperlink< creature >, ObjectGuid::LowType > spawnId)
static bool HandleGoGameObjectSpawnIdCommand (ChatHandler *handler, uint32 spawnId)
static bool HandleGoGameObjectGOIdCommand (ChatHandler *handler, uint32 goId)
static bool HandleGoGraveyardCommand (ChatHandler *handler, uint32 gyId)
static bool HandleGoGridCommand (ChatHandler *handler, float gridX, float gridY, Optional< uint32 > oMapId)
static bool HandleGoTaxinodeCommand (ChatHandler *handler, Variant< Hyperlink< taxinode >, uint32 > nodeId)
static bool HandleGoTriggerCommand (ChatHandler *handler, Variant< Hyperlink< areatrigger >, uint32 > areaTriggerId)
static bool HandleGoZoneXYCommand (ChatHandler *handler, float x, float y, Optional< Variant< Hyperlink< area >, uint32 >> areaIdArg)
static bool HandleGoXYZCommand (ChatHandler *handler, float x, float y, Optional< float > z, Optional< uint32 > id, Optional< float > o)
static bool HandleGoTicketCommand (ChatHandler *handler, uint32 ticketId)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 36 of file cs_go.cpp.
Constructor & Destructor Documentation
go_commandscript()
go_commandscript::go_commandscript () inline
Definition at line 39 of file cs_go.cpp.
 : CommandScript("go_commandscript") { }
Member Function Documentation
DoTeleport()
static bool go_commandscript::DoTeleport (ChatHandler * handler, Position pos, uint32 mapId = MAPID_INVALID) inline static
Definition at line 65 of file cs_go.cpp.
     {
         Player* player = handler->GetSession()->GetPlayer();
         if (mapId == MAPID_INVALID)
             mapId = player->GetMapId();
         if (!MapMgr::IsValidMapCoord(mapId, pos) || sObjectMgr->IsTransportMap(mapId))
         {
             handler->PSendSysMessage(LANG_INVALID_TARGET_COORD, pos.GetPositionX(), pos.GetPositionY(), mapId);
             handler->SetSentErrorMessage(true);
             return false;
         }
         // stop flight if need
         if (player->IsInFlight())
         {
             player->GetMotionMaster()->MovementExpired();
             player->CleanupAfterTaxiFlight();
         }
         // save only in non-flight case
         else
             player->SaveRecallPosition();
         player->TeleportTo({ mapId, pos });
         return true;
     }
References Player::CleanupAfterTaxiFlight(), WorldLocation::GetMapId(), Unit::GetMotionMaster(), WorldSession::GetPlayer(), Position::GetPositionX(), Position::GetPositionY(), ChatHandler::GetSession(), Unit::IsInFlight(), MapMgr::IsValidMapCoord(), LANG_INVALID_TARGET_COORD, MAPID_INVALID, MotionMaster::MovementExpired(), ChatHandler::PSendSysMessage(), Player::SaveRecallPosition(), ChatHandler::SetSentErrorMessage(), sObjectMgr, and Player::TeleportTo().
GetCommands()
ChatCommandTable go_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
Definition at line 41 of file cs_go.cpp.
     {
         static ChatCommandTable goCommandTable =
         {
             { "creature",      HandleGoCreatureSpawnIdCommand,   SEC_MODERATOR,  Console::No },
             { "creature id",   HandleGoCreatureCIdCommand,       SEC_MODERATOR,  Console::No },
             { "gameobject",    HandleGoGameObjectSpawnIdCommand, SEC_MODERATOR,  Console::No },
             { "gameobject id", HandleGoGameObjectGOIdCommand,    SEC_MODERATOR,  Console::No },
             { "graveyard",     HandleGoGraveyardCommand,         SEC_MODERATOR,  Console::No },
             { "grid",          HandleGoGridCommand,              SEC_MODERATOR,  Console::No },
             { "taxinode",      HandleGoTaxinodeCommand,          SEC_MODERATOR,  Console::No },
             { "trigger",       HandleGoTriggerCommand,           SEC_MODERATOR,  Console::No },
             { "zonexy",        HandleGoZoneXYCommand,            SEC_MODERATOR,  Console::No },
             { "xyz",           HandleGoXYZCommand,               SEC_MODERATOR,  Console::No },
             { "ticket",        HandleGoTicketCommand,            SEC_GAMEMASTER, Console::No }
         };
         static ChatCommandTable commandTable =
         {
             { "go", goCommandTable }
         };
         return commandTable;
     }
References Acore::ChatCommands::No, SEC_GAMEMASTER, and SEC_MODERATOR.
HandleGoCreatureCIdCommand()
static bool go_commandscript::HandleGoCreatureCIdCommand (ChatHandler * handler, Variant< Hyperlink< creature_entry >, uint32 > cId) inline static
Definition at line 92 of file cs_go.cpp.
     {
         CreatureData const* spawnpoint = nullptr;
         for (auto const& pair : sObjectMgr->GetAllCreatureData())
         {
             if (pair.second.id != *cId)
                 continue;
             if (!spawnpoint)
                 spawnpoint = &pair.second;
             else
             {
                 handler->SendSysMessage(LANG_COMMAND_GOCREATMULTIPLE);
                 break;
             }
         }
         if (!spawnpoint)
         {
             handler->SendSysMessage(LANG_COMMAND_GOCREATNOTFOUND);
             handler->SetSentErrorMessage(true);
             return false;
         }
         return DoTeleport(handler, { spawnpoint->posX, spawnpoint->posY, spawnpoint->posZ }, spawnpoint->mapid);
     }
References LANG_COMMAND_GOCREATMULTIPLE, LANG_COMMAND_GOCREATNOTFOUND, CreatureData::mapid, CreatureData::posX, CreatureData::posY, CreatureData::posZ, ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), and sObjectMgr.
HandleGoCreatureSpawnIdCommand()
static bool go_commandscript::HandleGoCreatureSpawnIdCommand (ChatHandler * handler, Variant< Hyperlink< creature >, ObjectGuid::LowType > spawnId) inline static
Definition at line 119 of file cs_go.cpp.
     {
         CreatureData const* spawnpoint = sObjectMgr->GetCreatureData(spawnId);
         if (!spawnpoint)
         {
             handler->SendSysMessage(LANG_COMMAND_GOCREATNOTFOUND);
             handler->SetSentErrorMessage(true);
             return false;
         }
         return DoTeleport(handler, { spawnpoint->posX, spawnpoint->posY, spawnpoint->posZ }, spawnpoint->mapid);
     }
References LANG_COMMAND_GOCREATNOTFOUND, CreatureData::mapid, CreatureData::posX, CreatureData::posY, CreatureData::posZ, ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), and sObjectMgr.
HandleGoGameObjectGOIdCommand()
static bool go_commandscript::HandleGoGameObjectGOIdCommand (ChatHandler * handler, uint32 goId) inline static
Definition at line 145 of file cs_go.cpp.
     {
         GameObjectData const* spawnpoint = nullptr;
         for (auto const& pair : sObjectMgr->GetAllGOData())
         {
             if (pair.second.id != goId)
                 continue;
             if (!spawnpoint)
                 spawnpoint = &pair.second;
             else
             {
                 handler->SendSysMessage(LANG_COMMAND_GOCREATMULTIPLE);
                 break;
             }
         }
         if (!spawnpoint)
         {
             handler->SendSysMessage(LANG_COMMAND_GOOBJNOTFOUND);
             handler->SetSentErrorMessage(true);
             return false;
         }
         return DoTeleport(handler, { spawnpoint->posX, spawnpoint->posY, spawnpoint->posZ }, spawnpoint->mapid);
     }
References LANG_COMMAND_GOCREATMULTIPLE, LANG_COMMAND_GOOBJNOTFOUND, GameObjectData::mapid, GameObjectData::posX, GameObjectData::posY, GameObjectData::posZ, ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), and sObjectMgr.
HandleGoGameObjectSpawnIdCommand()
static bool go_commandscript::HandleGoGameObjectSpawnIdCommand (ChatHandler * handler, uint32 spawnId) inline static
Definition at line 132 of file cs_go.cpp.
     {
         GameObjectData const* spawnpoint = sObjectMgr->GetGOData(spawnId);
         if (!spawnpoint)
         {
             handler->SendSysMessage(LANG_COMMAND_GOOBJNOTFOUND);
             handler->SetSentErrorMessage(true);
             return false;
         }
         return DoTeleport(handler, { spawnpoint->posX, spawnpoint->posY, spawnpoint->posZ }, spawnpoint->mapid);
     }
References LANG_COMMAND_GOOBJNOTFOUND, GameObjectData::mapid, GameObjectData::posX, GameObjectData::posY, GameObjectData::posZ, ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), and sObjectMgr.
HandleGoGraveyardCommand()
static bool go_commandscript::HandleGoGraveyardCommand (ChatHandler * handler, uint32 gyId) inline static
Definition at line 172 of file cs_go.cpp.
     {
         GraveyardStruct const* gy = sGraveyard->GetGraveyard(gyId);
         if (!gy)
         {
             handler->PSendSysMessage(LANG_COMMAND_GRAVEYARDNOEXIST, gyId);
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (!MapMgr::IsValidMapCoord(gy->Map, gy->x, gy->y, gy->z))
         {
             handler->PSendSysMessage(LANG_INVALID_TARGET_COORD, gy->x, gy->y, gy->Map);
             handler->SetSentErrorMessage(true);
             return false;
         }
         Player* player = handler->GetSession()->GetPlayer();
         // stop flight if need
         if (player->IsInFlight())
         {
             player->GetMotionMaster()->MovementExpired();
             player->CleanupAfterTaxiFlight();
         }
         // save only in non-flight case
         else
             player->SaveRecallPosition();
         player->TeleportTo(gy->Map, gy->x, gy->y, gy->z, player->GetOrientation());
         return true;
     }
References Player::CleanupAfterTaxiFlight(), Unit::GetMotionMaster(), Position::GetOrientation(), WorldSession::GetPlayer(), ChatHandler::GetSession(), Unit::IsInFlight(), MapMgr::IsValidMapCoord(), LANG_COMMAND_GRAVEYARDNOEXIST, LANG_INVALID_TARGET_COORD, GraveyardStruct::Map, MotionMaster::MovementExpired(), ChatHandler::PSendSysMessage(), Player::SaveRecallPosition(), ChatHandler::SetSentErrorMessage(), sGraveyard, Player::TeleportTo(), GraveyardStruct::x, GraveyardStruct::y, and GraveyardStruct::z.
HandleGoGridCommand()
static bool go_commandscript::HandleGoGridCommand (ChatHandler * handler, float gridX, float gridY, Optional< uint32 > oMapId) inline static
Definition at line 205 of file cs_go.cpp.
     {
         Player* player = handler->GetSession()->GetPlayer();
         uint32 mapId = oMapId.value_or(player->GetMapId());
         // center of grid
         float x = (gridX - CENTER_GRID_ID + 0.5f) * SIZE_OF_GRIDS;
         float y = (gridY - CENTER_GRID_ID + 0.5f) * SIZE_OF_GRIDS;
         if (!MapMgr::IsValidMapCoord(mapId, x, y))
         {
             handler->PSendSysMessage(LANG_INVALID_TARGET_COORD, x, y, mapId);
             handler->SetSentErrorMessage(true);
             return false;
         }
         // stop flight if need
         if (player->IsInFlight())
         {
             player->GetMotionMaster()->MovementExpired();
             player->CleanupAfterTaxiFlight();
         }
         // save only in non-flight case
         else
             player->SaveRecallPosition();
         Map const* map = sMapMgr->CreateBaseMap(mapId);
         float z = std::max(map->GetHeight(x, y, MAX_HEIGHT), map->GetWaterLevel(x, y));
         player->TeleportTo(mapId, x, y, z, player->GetOrientation());
         return true;
     }
References CENTER_GRID_ID, Player::CleanupAfterTaxiFlight(), Map::GetHeight(), WorldLocation::GetMapId(), Unit::GetMotionMaster(), Position::GetOrientation(), WorldSession::GetPlayer(), ChatHandler::GetSession(), Map::GetWaterLevel(), Unit::IsInFlight(), MapMgr::IsValidMapCoord(), LANG_INVALID_TARGET_COORD, MAX_HEIGHT, MotionMaster::MovementExpired(), ChatHandler::PSendSysMessage(), Player::SaveRecallPosition(), ChatHandler::SetSentErrorMessage(), SIZE_OF_GRIDS, sMapMgr, and Player::TeleportTo().
HandleGoTaxinodeCommand()
static bool go_commandscript::HandleGoTaxinodeCommand (ChatHandler * handler, Variant< Hyperlink< taxinode >, uint32 > nodeId) inline static
Definition at line 238 of file cs_go.cpp.
     {
         TaxiNodesEntry const* node = sTaxiNodesStore.LookupEntry(nodeId);
         if (!node)
         {
             handler->PSendSysMessage(LANG_COMMAND_GOTAXINODENOTFOUND, uint32(nodeId));
             handler->SetSentErrorMessage(true);
             return false;
         }
         return DoTeleport(handler, { node->x, node->y, node->z }, node->map_id);
     }
References LANG_COMMAND_GOTAXINODENOTFOUND, TaxiNodesEntry::map_id, ChatHandler::PSendSysMessage(), ChatHandler::SetSentErrorMessage(), sTaxiNodesStore, TaxiNodesEntry::x, TaxiNodesEntry::y, and TaxiNodesEntry::z.
HandleGoTicketCommand()
static bool go_commandscript::HandleGoTicketCommand (ChatHandler * handler, uint32 ticketId) inline static
Definition at line 346 of file cs_go.cpp.
     {
         GmTicket* ticket = sTicketMgr->GetTicket(ticketId);
         if (!ticket)
         {
             handler->SendSysMessage(LANG_COMMAND_TICKETNOTEXIST);
             return true;
         }
         Player* player = handler->GetSession()->GetPlayer();
         // stop flight if need
         if (player->IsInFlight())
         {
             player->GetMotionMaster()->MovementExpired();
             player->CleanupAfterTaxiFlight();
         }
         // save only in non-flight case
         else
             player->SaveRecallPosition();
         ticket->TeleportTo(player);
         return true;
     }
References Player::CleanupAfterTaxiFlight(), Unit::GetMotionMaster(), WorldSession::GetPlayer(), ChatHandler::GetSession(), Unit::IsInFlight(), LANG_COMMAND_TICKETNOTEXIST, MotionMaster::MovementExpired(), Player::SaveRecallPosition(), ChatHandler::SendSysMessage(), sTicketMgr, and GmTicket::TeleportTo().
HandleGoTriggerCommand()
static bool go_commandscript::HandleGoTriggerCommand (ChatHandler * handler, Variant< Hyperlink< areatrigger >, uint32 > areaTriggerId) inline static
Definition at line 250 of file cs_go.cpp.
     {
         AreaTrigger const* at = sObjectMgr->GetAreaTrigger(areaTriggerId);
         if (!at)
         {
             handler->PSendSysMessage(LANG_COMMAND_GOAREATRNOTFOUND, uint32(areaTriggerId));
             handler->SetSentErrorMessage(true);
             return false;
         }
         return DoTeleport(handler, { at->x, at->y, at->z }, at->map);
     }
References LANG_COMMAND_GOAREATRNOTFOUND, AreaTrigger::map, ChatHandler::PSendSysMessage(), ChatHandler::SetSentErrorMessage(), sObjectMgr, AreaTrigger::x, AreaTrigger::y, and AreaTrigger::z.
HandleGoXYZCommand()
static bool go_commandscript::HandleGoXYZCommand (ChatHandler * handler, float x, float y, Optional< float > z, Optional< uint32 > id, Optional< float > o) inline static
Definition at line 317 of file cs_go.cpp.
     {
         Player* player = handler->GetSession()->GetPlayer();
         uint32 mapId = id.value_or(player->GetMapId());
         if (z)
         {
             if (!MapMgr::IsValidMapCoord(mapId, x, y, *z))
             {
                 handler->PSendSysMessage(LANG_INVALID_TARGET_COORD, x, y, mapId);
                 handler->SetSentErrorMessage(true);
                 return false;
             }
         }
         else
         {
             if (!MapMgr::IsValidMapCoord(mapId, x, y))
             {
                 handler->PSendSysMessage(LANG_INVALID_TARGET_COORD, x, y, mapId);
                 handler->SetSentErrorMessage(true);
                 return false;
             }
             Map const* map = sMapMgr->CreateBaseMap(mapId);
             z = std::max(map->GetHeight(x, y, MAX_HEIGHT), map->GetWaterLevel(x, y));
         }
         return DoTeleport(handler, { x, y, *z, o.value_or(0.0f) }, mapId);
     }
References Map::GetHeight(), WorldLocation::GetMapId(), WorldSession::GetPlayer(), ChatHandler::GetSession(), Map::GetWaterLevel(), MapMgr::IsValidMapCoord(), LANG_INVALID_TARGET_COORD, MAX_HEIGHT, ChatHandler::PSendSysMessage(), ChatHandler::SetSentErrorMessage(), and sMapMgr.
HandleGoZoneXYCommand()
static bool go_commandscript::HandleGoZoneXYCommand (ChatHandler * handler, float x, float y, Optional< Variant< Hyperlink< area >, uint32 >> areaIdArg) inline static
Definition at line 263 of file cs_go.cpp.
     {
         Player* player = handler->GetSession()->GetPlayer();
         uint32 areaId = areaIdArg ? *areaIdArg : player->GetZoneId();
         AreaTableEntry const* areaEntry = sAreaTableStore.LookupEntry(areaId);
         if (x < 0 || x > 100 || y < 0 || y > 100 || !areaEntry)
         {
             handler->PSendSysMessage(LANG_INVALID_ZONE_COORD, x, y, areaId);
             handler->SetSentErrorMessage(true);
             return false;
         }
         // update to parent zone if exist (client map show only zones without parents)
         AreaTableEntry const* zoneEntry = areaEntry->zone ? sAreaTableStore.LookupEntry(areaEntry->zone) : areaEntry;
                 ASSERT(zoneEntry);
         Map const* map = sMapMgr->CreateBaseMap(zoneEntry->mapid);
         if (map->Instanceable())
         {
             handler->PSendSysMessage(LANG_INVALID_ZONE_MAP, areaEntry->ID, areaEntry->area_name[handler->GetSessionDbcLocale()], map->GetId(), map->GetMapName());
             handler->SetSentErrorMessage(true);
             return false;
         }
         Zone2MapCoordinates(x, y, zoneEntry->ID);
         if (!MapMgr::IsValidMapCoord(zoneEntry->mapid, x, y))
         {
             handler->PSendSysMessage(LANG_INVALID_TARGET_COORD, x, y, zoneEntry->mapid);
             handler->SetSentErrorMessage(true);
             return false;
         }
         // stop flight if need
         if (player->IsInFlight())
         {
             player->GetMotionMaster()->MovementExpired();
             player->CleanupAfterTaxiFlight();
         }
         // save only in non-flight case
         else
             player->SaveRecallPosition();
         float z = std::max(map->GetHeight(x, y, MAX_HEIGHT), map->GetWaterLevel(x, y));
         player->TeleportTo(zoneEntry->mapid, x, y, z, player->GetOrientation());
         return true;
     }
References AreaTableEntry::area_name, ASSERT, Player::CleanupAfterTaxiFlight(), Map::GetHeight(), Map::GetId(), Map::GetMapName(), Unit::GetMotionMaster(), Position::GetOrientation(), WorldSession::GetPlayer(), ChatHandler::GetSession(), ChatHandler::GetSessionDbcLocale(), Map::GetWaterLevel(), WorldObject::GetZoneId(), AreaTableEntry::ID, Map::Instanceable(), Unit::IsInFlight(), MapMgr::IsValidMapCoord(), LANG_INVALID_TARGET_COORD, LANG_INVALID_ZONE_COORD, LANG_INVALID_ZONE_MAP, AreaTableEntry::mapid, MAX_HEIGHT, MotionMaster::MovementExpired(), ChatHandler::PSendSysMessage(), sAreaTableStore, Player::SaveRecallPosition(), ChatHandler::SetSentErrorMessage(), sMapMgr, Player::TeleportTo(), AreaTableEntry::zone, and Zone2MapCoordinates().
The documentation for this class was generated from the following file:
src/server/scripts/Commands/cs_go.cpp