Azerotcore-wotlk: GuildBankRightsAndSlots Class Reference
GuildBankRightsAndSlots Class Reference
#include <Guild.h>
Public Member Functions
GuildBankRightsAndSlots ()
GuildBankRightsAndSlots (uint8 _tabId)
GuildBankRightsAndSlots (uint8 _tabId, uint8 _rights, uint32 _slots)
void SetGuildMasterValues ()
void SetTabId (uint8 _tabId)
void SetSlots (uint32 _slots)
void SetRights (uint8 _rights)
int8 GetTabId () const
int32 GetSlots () const
int8 GetRights () const
Private Attributes
uint8 tabId
uint8 rights
uint32 slots
Detailed Description
Definition at line 250 of file Guild.h.
Constructor & Destructor Documentation
GuildBankRightsAndSlots() [1/3]
GuildBankRightsAndSlots::GuildBankRightsAndSlots () inline
Definition at line 253 of file Guild.h.
 : tabId(TAB_UNDEFINED), rights(0), slots(0) { }
GuildBankRightsAndSlots() [2/3]
GuildBankRightsAndSlots::GuildBankRightsAndSlots (uint8 _tabId) inline
Definition at line 254 of file Guild.h.
 : tabId(_tabId), rights(0), slots(0) { }
GuildBankRightsAndSlots() [3/3]
GuildBankRightsAndSlots::GuildBankRightsAndSlots (uint8 _tabId, uint8 _rights, uint32 _slots) inline
Definition at line 255 of file Guild.h.
 : tabId(_tabId), rights(_rights), slots(_slots) { }
Member Function Documentation
GetRights()
int8 GuildBankRightsAndSlots::GetRights () const inline
Definition at line 269 of file Guild.h.
 { return rights; }
References rights.
Referenced by Guild::RankInfo::CreateMissingTabsIfNeeded(), Guild::RankInfo::GetBankTabRights(), and Guild::RankInfo::SetBankTabSlotsAndRights().
GetSlots()
int32 GuildBankRightsAndSlots::GetSlots () const inline
Definition at line 268 of file Guild.h.
 { return slots; }
References slots.
Referenced by Guild::RankInfo::CreateMissingTabsIfNeeded(), Guild::RankInfo::GetBankTabSlotsPerDay(), and Guild::RankInfo::SetBankTabSlotsAndRights().
GetTabId()
int8 GuildBankRightsAndSlots::GetTabId () const inline
Definition at line 267 of file Guild.h.
 { return tabId; }
References tabId.
Referenced by Guild::_SetRankBankTabRightsAndSlots(), Guild::RankInfo::CreateMissingTabsIfNeeded(), and Guild::RankInfo::SetBankTabSlotsAndRights().
SetGuildMasterValues()
void GuildBankRightsAndSlots::SetGuildMasterValues () inline
Definition at line 257 of file Guild.h.
     {
         rights = GUILD_BANK_RIGHT_FULL;
         slots = uint32(GUILD_WITHDRAW_SLOT_UNLIMITED);
     }
References GUILD_BANK_RIGHT_FULL, GUILD_WITHDRAW_SLOT_UNLIMITED, rights, and slots.
Referenced by Guild::RankInfo::CreateMissingTabsIfNeeded(), and Guild::RankInfo::SetBankTabSlotsAndRights().
SetRights()
void GuildBankRightsAndSlots::SetRights (uint8 _rights) inline
Definition at line 265 of file Guild.h.
 { rights = _rights; }
References rights.
SetSlots()
void GuildBankRightsAndSlots::SetSlots (uint32 _slots) inline
Definition at line 264 of file Guild.h.
 { slots = _slots; }
References slots.
SetTabId()
void GuildBankRightsAndSlots::SetTabId (uint8 _tabId) inline
Definition at line 263 of file Guild.h.
 { tabId = _tabId; }
References tabId.
Referenced by Guild::RankInfo::CreateMissingTabsIfNeeded().
Member Data Documentation
rights
uint8 GuildBankRightsAndSlots::rights private
Definition at line 273 of file Guild.h.
Referenced by GetRights(), SetGuildMasterValues(), and SetRights().
slots
uint32 GuildBankRightsAndSlots::slots private
Definition at line 274 of file Guild.h.
Referenced by GetSlots(), SetGuildMasterValues(), and SetSlots().
tabId
uint8 GuildBankRightsAndSlots::tabId private
Definition at line 272 of file Guild.h.
Referenced by GetTabId(), and SetTabId().
The documentation for this class was generated from the following file:
src/server/game/Guilds/Guild.h