Azerotcore-wotlk: G3D::MeshEdgeTable Class Reference
G3D::MeshEdgeTable Class Reference
Classes
class Edge
class Iterator
Public Types
typedef SmallArray< int, 2 > FaceIndexArray
typedef SmallArray< Edge, 6 > EdgeArray
typedef Array< EdgeArray > ET
Public Member Functions
MeshEdgeTable ()
void clear ()
void resize (int maxV)
void insert (int v0, int v1, int faceIndex)
Iterator begin ()
Private Attributes
ET table
Detailed Description
Two-level table mapping index 0 -> index 1 -> list of face indices
Definition at line 23 of file MeshAlgAdjacency.cpp.
Member Typedef Documentation
EdgeArray
typedef SmallArray<Edge, 6> G3D::MeshEdgeTable::EdgeArray
We expect at most 6 edges per vertex; that matches a typical regular grid mesh
Definition at line 37 of file MeshAlgAdjacency.cpp.
ET
typedef Array< EdgeArray > G3D::MeshEdgeTable::ET
Definition at line 39 of file MeshAlgAdjacency.cpp.
FaceIndexArray
typedef SmallArray<int, 2> G3D::MeshEdgeTable::FaceIndexArray
We expect 2 faces per edge.
Definition at line 27 of file MeshAlgAdjacency.cpp.
Constructor & Destructor Documentation
MeshEdgeTable()
G3D::MeshEdgeTable::MeshEdgeTable () inline
Definition at line 47 of file MeshAlgAdjacency.cpp.
                     {
         AreaMemoryManager::Ref mm = AreaMemoryManager::create();
         table.clearAndSetMemoryManager(mm);
     }
References G3D::Array< T, MIN_ELEMENTS >::clearAndSetMemoryManager(), G3D::MemoryManager::create(), and table.
Member Function Documentation
begin()
Iterator G3D::MeshEdgeTable::begin () inline
Definition at line 145 of file MeshAlgAdjacency.cpp.
                      {
         return Iterator(table);
     }
References table.
Referenced by G3D::MeshAlg::computeAdjacency().
clear()
void G3D::MeshEdgeTable::clear () inline
Definition at line 52 of file MeshAlgAdjacency.cpp.
                  {
         table.clear();
     }
References G3D::Array< T, MIN_ELEMENTS >::clear(), and table.
Referenced by G3D::MeshAlg::computeAdjacency().
insert()
void G3D::MeshEdgeTable::insert (int v0, int v1, int faceIndex) inline
Inserts the faceIndex into the edge's face list. The index may be a negative number indicating a backface.
Parameters
v0 Vertex index 0
v1 Vertex index 1
Definition at line 67 of file MeshAlgAdjacency.cpp.
{
         debugAssert(v0 <= v1);
         EdgeArray& edgeArray = table[v0];
         for (int i = 0; i < edgeArray.size(); ++i) {
             if (edgeArray[i].i1 == v1) {
                 edgeArray[i].faceIndexArray.push(faceIndex);
                 return;
             }
         }
         Edge& p = edgeArray.next();
         p.i1 = v1;
         p.faceIndexArray.push(faceIndex);
     }
References debugAssert, G3D::MeshEdgeTable::Edge::faceIndexArray, G3D::MeshEdgeTable::Edge::i1, G3D::SmallArray< T, N >::next(), G3D::SmallArray< T, N >::push(), G3D::SmallArray< T, N >::size(), and table.
Referenced by G3D::MeshAlg::computeAdjacency().
resize()
void G3D::MeshEdgeTable::resize (int maxV) inline
Definition at line 56 of file MeshAlgAdjacency.cpp.
{
         table.resize(maxV);
     }
References G3D::Array< T, MIN_ELEMENTS >::resize(), and table.
Referenced by G3D::MeshAlg::computeAdjacency().
Member Data Documentation
table
ET G3D::MeshEdgeTable::table private
Definition at line 43 of file MeshAlgAdjacency.cpp.
Referenced by begin(), clear(), insert(), MeshEdgeTable(), and resize().
The documentation for this class was generated from the following file:
deps/g3dlite/source/MeshAlgAdjacency.cpp