Azerotcore-wotlk: Acore::Impl::ChatCommands::ChatCommandResult Struct Reference
Acore::Impl::ChatCommands::ChatCommandResult Struct Reference
#include <ChatCommandHelpers.h>
Public Member Functions
ChatCommandResult (std::nullopt_t)
ChatCommandResult (std::string const &)=delete
ChatCommandResult (std::string &&s)
ChatCommandResult (char const *c)
ChatCommandResult (std::string_view s)
ChatCommandResult (ChatCommandResult const &)=delete
ChatCommandResult (ChatCommandResult &&)=default
ChatCommandResult & operator= (ChatCommandResult const &)=delete
ChatCommandResult & operator= (ChatCommandResult &&)=default
std::string_view operator* () const
bool IsSuccessful () const
operator bool () const
bool HasErrorMessage () const
std::string const & GetErrorMessage () const
Private Attributes
std::variant< std::monostate, std::string_view, std::string > _storage
Detailed Description
Definition at line 100 of file ChatCommandHelpers.h.
Constructor & Destructor Documentation
ChatCommandResult() [1/7]
Acore::Impl::ChatCommands::ChatCommandResult::ChatCommandResult (std::nullopt_t) inline
Definition at line 102 of file ChatCommandHelpers.h.
 : _storage() {}
ChatCommandResult() [2/7]
Acore::Impl::ChatCommands::ChatCommandResult::ChatCommandResult (std::string const &) delete
ChatCommandResult() [3/7]
Acore::Impl::ChatCommands::ChatCommandResult::ChatCommandResult (std::string && s) inline
Definition at line 104 of file ChatCommandHelpers.h.
 : _storage(std::in_place_type<std::string>, std::forward<std::string>(s)) {}
ChatCommandResult() [4/7]
Acore::Impl::ChatCommands::ChatCommandResult::ChatCommandResult (char const * c) inline
Definition at line 105 of file ChatCommandHelpers.h.
 : _storage(std::in_place_type<std::string>, c) {}
ChatCommandResult() [5/7]
Acore::Impl::ChatCommands::ChatCommandResult::ChatCommandResult (std::string_view s) inline
Definition at line 106 of file ChatCommandHelpers.h.
 : _storage(std::in_place_type<std::string_view>, s) {}
ChatCommandResult() [6/7]
Acore::Impl::ChatCommands::ChatCommandResult::ChatCommandResult (ChatCommandResult const &) delete
ChatCommandResult() [7/7]
Acore::Impl::ChatCommands::ChatCommandResult::ChatCommandResult (ChatCommandResult &&) default
Member Function Documentation
GetErrorMessage()
std::string const& Acore::Impl::ChatCommands::ChatCommandResult::GetErrorMessage () const inline
Definition at line 117 of file ChatCommandHelpers.h.
 { return std::get<std::string>(_storage); }
References _storage.
Referenced by Acore::Impl::ChatCommands::CommandInvoker::CommandInvoker(), Acore::Impl::ChatCommands::ArgInfo< Acore::ChatCommands::Variant< Ts... > >::TryAtIndex(), Acore::Impl::ChatCommands::ArgInfo< Acore::ChatCommands::Variant< Ts... > >::TryConsume(), and Acore::Impl::ChatCommands::MultiConsumer< Tuple, Optional< NestedNextType >, offset >::TryConsumeTo().
HasErrorMessage()
bool Acore::Impl::ChatCommands::ChatCommandResult::HasErrorMessage () const inline
Definition at line 116 of file ChatCommandHelpers.h.
 { return std::holds_alternative<std::string>(_storage); }
References _storage.
Referenced by Acore::Impl::ChatCommands::CommandInvoker::CommandInvoker(), Acore::Impl::ChatCommands::ArgInfo< Acore::ChatCommands::Variant< Ts... > >::TryAtIndex(), Acore::Impl::ChatCommands::ArgInfo< Acore::ChatCommands::Variant< Ts... > >::TryConsume(), and Acore::Impl::ChatCommands::MultiConsumer< Tuple, Optional< NestedNextType >, offset >::TryConsumeTo().
IsSuccessful()
bool Acore::Impl::ChatCommands::ChatCommandResult::IsSuccessful () const inline
Definition at line 114 of file ChatCommandHelpers.h.
 { return std::holds_alternative<std::string_view>(_storage); }
References _storage.
Referenced by operator bool().
operator bool()
Acore::Impl::ChatCommands::ChatCommandResult::operator bool () const inline explicit
Definition at line 115 of file ChatCommandHelpers.h.
 { return IsSuccessful(); }
References IsSuccessful().
operator*()
std::string_view Acore::Impl::ChatCommands::ChatCommandResult::operator* () const inline
Definition at line 113 of file ChatCommandHelpers.h.
 { return std::get<std::string_view>(_storage); }
References _storage.
operator=() [1/2]
ChatCommandResult& Acore::Impl::ChatCommands::ChatCommandResult::operator= (ChatCommandResult &&) default
operator=() [2/2]
ChatCommandResult& Acore::Impl::ChatCommands::ChatCommandResult::operator= (ChatCommandResult const &) delete
Member Data Documentation
_storage
std::variant<std::monostate, std::string_view, std::string> Acore::Impl::ChatCommands::ChatCommandResult::_storage private
Definition at line 120 of file ChatCommandHelpers.h.
Referenced by GetErrorMessage(), HasErrorMessage(), IsSuccessful(), and operator*().
The documentation for this struct was generated from the following file:
src/server/game/Chat/ChatCommands/ChatCommandHelpers.h