Azerotcore-wotlk: boss_ignis::boss_ignisAI Struct Reference
boss_ignis::boss_ignisAI Struct Reference
Public Member Functions
boss_ignisAI (Creature *pCreature)
void Reset () override
void EnterCombat (Unit *) override
void SetData (uint32 id, uint32) override
uint32 GetData (uint32 id) const override
void JustReachedHome () override
void KilledUnit (Unit *) override
void JustDied (Unit *) override
void SpellHit (Unit *caster, const SpellInfo *spell) override
void MoveInLineOfSight (Unit *) override
void UpdateAI (uint32 diff) override
void EnterEvadeMode () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
uint8 counter
bool bShattered
uint32 lastShatterMSTime
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 210 of file boss_ignis.cpp.
Constructor & Destructor Documentation
boss_ignisAI()
boss_ignis::boss_ignisAI::boss_ignisAI (Creature * pCreature) inline
Definition at line 212 of file boss_ignis.cpp.
 : ScriptedAI(pCreature) { }
Member Function Documentation
EnterCombat()
void boss_ignis::boss_ignisAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 235 of file boss_ignis.cpp.
         {
             me->setActive(true);
             std::list<Creature*> icl;
             me->GetCreaturesWithEntryInRange(icl, 300.0f, NPC_IRON_CONSTRUCT);
             for( std::list<Creature*>::iterator itr = icl.begin(); itr != icl.end(); ++itr )
             {
                 if (!(*itr)->IsAlive())
                 {
                     (*itr)->Respawn();
                     (*itr)->UpdatePosition((*itr)->GetHomePosition(), true);
                     (*itr)->StopMovingOnCurrentPos();
                 }
                 (*itr)->AI()->Reset();
                 if (!(*itr)->HasAura(38757))
                     (*itr)->CastSpell((*itr), 38757, true);
             }
             bShattered = false;
             lastShatterMSTime = 0;
             events.Reset();
             events.ScheduleEvent(EVENT_ACTIVATE_CONSTRUCT, RAID_MODE(40000, 30000));
             events.ScheduleEvent(EVENT_SPELL_SCORCH, 10000);
             events.ScheduleEvent(EVENT_SPELL_FLAME_JETS, 32000);
             events.ScheduleEvent(EVENT_GRAB, 25000);
             me->Yell(TEXT_AGGRO, LANG_UNIVERSAL);
             me->PlayDirectSound(SOUND_AGGRO);
             DoZoneInCombat();
             if( InstanceScript* m_pInstance = me->GetInstanceScript() )
             {
                 m_pInstance->SetData(TYPE_IGNIS, IN_PROGRESS);
                 m_pInstance->DoStopTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, ACHIEV_STOKIN_THE_FURNACE_EVENT);
                 m_pInstance->DoStartTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, ACHIEV_STOKIN_THE_FURNACE_EVENT);
             }
         }
References ACHIEV_STOKIN_THE_FURNACE_EVENT, ACHIEVEMENT_TIMED_TYPE_EVENT, bShattered, CreatureAI::DoZoneInCombat(), EVENT_ACTIVATE_CONSTRUCT, EVENT_GRAB, EVENT_SPELL_FLAME_JETS, EVENT_SPELL_SCORCH, WorldObject::GetCreaturesWithEntryInRange(), WorldObject::GetInstanceScript(), IN_PROGRESS, LANG_UNIVERSAL, lastShatterMSTime, ScriptedAI::me, NPC_IRON_CONSTRUCT, WorldObject::PlayDirectSound(), ScriptedAI::RAID_MODE(), WorldObject::setActive(), SOUND_AGGRO, TEXT_AGGRO, TYPE_IGNIS, and Unit::Yell().
EnterEvadeMode()
void boss_ignis::boss_ignisAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 446 of file boss_ignis.cpp.
         {
             me->SetControlled(false, UNIT_STATE_ROOT);
             me->DisableRotate(false);
             ScriptedAI::EnterEvadeMode();
         }
References Unit::DisableRotate(), CreatureAI::EnterEvadeMode(), ScriptedAI::me, Unit::SetControlled(), and UNIT_STATE_ROOT.
Referenced by UpdateAI().
GetData()
uint32 boss_ignis::boss_ignisAI::GetData (uint32 id) const inline override virtual
Reimplemented from UnitAI.
Definition at line 286 of file boss_ignis.cpp.
         {
             if (id == 1337)
                 return (bShattered ? 1 : 0);
             return 0;
         }
References bShattered.
JustDied()
void boss_ignis::boss_ignisAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 312 of file boss_ignis.cpp.
         {
             me->Yell(TEXT_DEATH, LANG_UNIVERSAL);
             me->PlayDirectSound(SOUND_DEATH);
             if( me->GetInstanceScript() )
                 me->GetInstanceScript()->SetData(TYPE_IGNIS, DONE);
             std::list<Creature*> icl;
             me->GetCreaturesWithEntryInRange(icl, 300.0f, NPC_IRON_CONSTRUCT);
             for( std::list<Creature*>::iterator itr = icl.begin(); itr != icl.end(); ++itr )
                 if ((*itr)->IsAlive() && (*itr)->IsInCombat())
                     Unit::Kill(*itr, *itr);
         }
References DONE, WorldObject::GetCreaturesWithEntryInRange(), WorldObject::GetInstanceScript(), Unit::Kill(), LANG_UNIVERSAL, ScriptedAI::me, NPC_IRON_CONSTRUCT, WorldObject::PlayDirectSound(), ZoneScript::SetData(), SOUND_DEATH, TEXT_DEATH, TYPE_IGNIS, and Unit::Yell().
JustReachedHome()
void boss_ignis::boss_ignisAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 293 of file boss_ignis.cpp.
         {
             me->setActive(false);
         }
References ScriptedAI::me, and WorldObject::setActive().
KilledUnit()
void boss_ignis::boss_ignisAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 298 of file boss_ignis.cpp.
         {
             if( rand() % 2 )
             {
                 me->Yell(TEXT_SLAY_1, LANG_UNIVERSAL);
                 me->PlayDirectSound(SOUND_SLAY_1);
             }
             else
             {
                 me->Yell(TEXT_SLAY_2, LANG_UNIVERSAL);
                 me->PlayDirectSound(SOUND_SLAY_2);
             }
         }
References LANG_UNIVERSAL, ScriptedAI::me, WorldObject::PlayDirectSound(), SOUND_SLAY_1, SOUND_SLAY_2, TEXT_SLAY_1, TEXT_SLAY_2, and Unit::Yell().
MoveInLineOfSight()
void boss_ignis::boss_ignisAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 336 of file boss_ignis.cpp.
 {}
Reset()
void boss_ignis::boss_ignisAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 219 of file boss_ignis.cpp.
         {
             events.Reset();
             me->SetControlled(false, UNIT_STATE_ROOT);
             me->DisableRotate(false);
             counter = 0;
             bShattered = false;
             lastShatterMSTime = 0;
             if( InstanceScript* m_pInstance = me->GetInstanceScript() )
             {
                 m_pInstance->SetData(TYPE_IGNIS, NOT_STARTED);
                 m_pInstance->DoStopTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, ACHIEV_STOKIN_THE_FURNACE_EVENT);
             }
         }
References ACHIEV_STOKIN_THE_FURNACE_EVENT, ACHIEVEMENT_TIMED_TYPE_EVENT, bShattered, counter, Unit::DisableRotate(), WorldObject::GetInstanceScript(), lastShatterMSTime, ScriptedAI::me, NOT_STARTED, Unit::SetControlled(), TYPE_IGNIS, and UNIT_STATE_ROOT.
SetData()
void boss_ignis::boss_ignisAI::SetData (uint32 id, uint32) inline override virtual
Reimplemented from UnitAI.
Definition at line 274 of file boss_ignis.cpp.
         {
             if (id == 1337)
             {
                 if (lastShatterMSTime)
                     if (getMSTimeDiff(lastShatterMSTime, World::GetGameTimeMS()) <= 5000)
                         bShattered = true;
                 lastShatterMSTime = World::GetGameTimeMS();
             }
         }
References bShattered, World::GetGameTimeMS(), getMSTimeDiff(), and lastShatterMSTime.
SpellHit()
void boss_ignis::boss_ignisAI::SpellHit (Unit * caster, const SpellInfo * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 327 of file boss_ignis.cpp.
         {
             if (caster && spell->Id == SPELL_GRAB_CONTROL_2)
             {
                 //caster->ClearUnitState(UNIT_STATE_ONVEHICLE);
                 me->CastSpell(caster, S_SLAG_POT, true);
             }
         }
References Unit::CastSpell(), SpellInfo::Id, ScriptedAI::me, S_SLAG_POT, and SPELL_GRAB_CONTROL_2.
UpdateAI()
void boss_ignis::boss_ignisAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 338 of file boss_ignis.cpp.
         {
             if (!UpdateVictim())
                 return;
             if( me->GetPositionX() < 490.0f || me->GetPositionX() > 690.0f || me->GetPositionY() < 130.0f || me->GetPositionY() > 410.0f )
             {
                 EnterEvadeMode();
                 return;
             }
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case 0:
                     break;
                 case EVENT_ACTIVATE_CONSTRUCT:
                     me->CastCustomSpell(SPELL_ACTIVATE_CONSTRUCT, SPELLVALUE_MAX_TARGETS, 1, (Unit*)nullptr, false);
                     if (++counter >= 20)
                     {
                         me->Yell(TEXT_BERSERK, LANG_UNIVERSAL);
                         me->PlayDirectSound(SOUND_BERSERK);
                         me->CastSpell(me, SPELL_BERSERK, true);
                         break;
                     }
                     events.RepeatEvent(RAID_MODE(40000, 30000));
                     break;
                 case EVENT_SPELL_SCORCH:
                     if( rand() % 2 )
                     {
                         me->Yell(TEXT_SCORCH_1, LANG_UNIVERSAL);
                         me->PlayDirectSound(SOUND_SCORCH_1);
                     }
                     else
                     {
                         me->Yell(TEXT_SCORCH_2, LANG_UNIVERSAL);
                         me->PlayDirectSound(SOUND_SCORCH_2);
                     }
                     me->SetControlled(true, UNIT_STATE_ROOT);
                     me->DisableRotate(true);
                     me->SendMovementFlagUpdate();
                     me->CastSpell(me->GetVictim(), S_SCORCH, false);
                     events.RepeatEvent(20000);
                     events.RescheduleEvent(EVENT_ENABLE_ROTATE, 3001);
                     break;
                 case EVENT_ENABLE_ROTATE:
                     me->SetControlled(false, UNIT_STATE_ROOT);
                     me->DisableRotate(false);
                     break;
                 case EVENT_SPELL_FLAME_JETS:
                     me->TextEmote(TEXT_FLAME_JETS, nullptr, true);
                     me->CastSpell(me->GetVictim(), S_FLAME_JETS, false);
                     events.RepeatEvent(25000);
                     break;
                 case EVENT_GRAB:
                     {
                         std::list<Creature*> icl;
                         me->GetCreaturesWithEntryInRange(icl, 300.0f, NPC_IRON_CONSTRUCT);
                         GuidVector playerGUIDs;
                         Map::PlayerList const& pl = me->GetMap()->GetPlayers();
                         Player* temp = nullptr;
                         for( Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr )
{
                             temp = itr->GetSource();
                             if( !temp->IsAlive() || temp->GetExactDist2d(me) > 90.0f )
                                 continue;
                             if( me->GetVictim() && temp->GetGUID() == me->GetVictim()->GetGUID() )
                                 continue;
                             bool found = false;
                             for (std::list<Creature*>::iterator iterator = icl.begin(); iterator != icl.end(); ++iterator)
{
                                 if ((*iterator)->GetVictim() && (*iterator)->GetVictim()->GetGUID() == temp->GetGUID())
{
                                     found = true;
                                     break;
                                 }
                             }
                             if( !found )
                                 playerGUIDs.push_back(temp->GetGUID());
                         }
                         if( !playerGUIDs.empty() )
{
                             int8 pos = urand(0, playerGUIDs.size() - 1);
                             if( Player* pTarget = ObjectAccessor::GetPlayer(*me, playerGUIDs.at(pos)) )
{
                                 me->Yell(TEXT_SLAG_POT, LANG_UNIVERSAL);
                                 me->PlayDirectSound(SOUND_SLAG_POT);
                                 me->CastSpell(pTarget, SPELL_GRAB, false);
                             }
                         }
                         events.RepeatEvent(24000); // +6000 below
                         events.DelayEvents(6000);
                     }
                     break;
             }
             DoMeleeAttackIfReady();
         }
References MapRefMgr::begin(), Unit::CastCustomSpell(), Unit::CastSpell(), counter, Unit::DisableRotate(), UnitAI::DoMeleeAttackIfReady(), MapRefMgr::end(), EnterEvadeMode(), EVENT_ACTIVATE_CONSTRUCT, EVENT_ENABLE_ROTATE, EVENT_GRAB, EVENT_SPELL_FLAME_JETS, EVENT_SPELL_SCORCH, WorldObject::GetCreaturesWithEntryInRange(), Position::GetExactDist2d(), Object::GetGUID(), WorldObject::GetMap(), ObjectAccessor::GetPlayer(), Map::GetPlayers(), Position::GetPositionX(), Position::GetPositionY(), Unit::GetVictim(), Unit::HasUnitState(), Unit::IsAlive(), LANG_UNIVERSAL, ScriptedAI::me, NPC_IRON_CONSTRUCT, WorldObject::PlayDirectSound(), ScriptedAI::RAID_MODE(), S_FLAME_JETS, S_SCORCH, Unit::SendMovementFlagUpdate(), Unit::SetControlled(), SOUND_BERSERK, SOUND_SCORCH_1, SOUND_SCORCH_2, SOUND_SLAG_POT, SPELL_ACTIVATE_CONSTRUCT, SPELL_BERSERK, SPELL_GRAB, SPELLVALUE_MAX_TARGETS, TEXT_BERSERK, TEXT_FLAME_JETS, TEXT_SCORCH_1, TEXT_SCORCH_2, TEXT_SLAG_POT, Unit::TextEmote(), UNIT_STATE_CASTING, UNIT_STATE_ROOT, CreatureAI::UpdateVictim(), urand(), and Unit::Yell().
Member Data Documentation
bShattered
bool boss_ignis::boss_ignisAI::bShattered
Definition at line 216 of file boss_ignis.cpp.
Referenced by EnterCombat(), GetData(), Reset(), and SetData().
counter
uint8 boss_ignis::boss_ignisAI::counter
Definition at line 215 of file boss_ignis.cpp.
Referenced by Reset(), and UpdateAI().
events
EventMap boss_ignis::boss_ignisAI::events
Definition at line 214 of file boss_ignis.cpp.
lastShatterMSTime
uint32 boss_ignis::boss_ignisAI::lastShatterMSTime
Definition at line 217 of file boss_ignis.cpp.
Referenced by EnterCombat(), Reset(), and SetData().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_ignis.cpp