Azerotcore-wotlk: boss_jormungarAI Struct Reference
boss_jormungarAI Struct Reference
Public Member Functions
boss_jormungarAI (Creature *pCreature)
void DoAction (int32 param) override
void ScheduleEvents ()
void EnterCombat (Unit *) override
void JustReachedHome () override
void AttackStart (Unit *who) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void EnterEvadeMode () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
EventMap events
bool bIsStationary
uint32 _SPELL_BITE
uint32 _SPELL_SPEW
uint32 _SPELL_SPIT
uint32 _SPELL_SPRAY
uint32 _MODEL_STATIONARY
uint32 _MODEL_MOBILE
uint32 _TYPE_OTHER
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 469 of file boss_northrend_beasts.cpp.
Constructor & Destructor Documentation
boss_jormungarAI()
boss_jormungarAI::boss_jormungarAI (Creature * pCreature) inline
Definition at line 471 of file boss_northrend_beasts.cpp.
                                           : ScriptedAI(pCreature)
     {
         pInstance = pCreature->GetInstanceScript();
         me->SetReactState(REACT_PASSIVE);
     }
References WorldObject::GetInstanceScript(), ScriptedAI::me, pInstance, REACT_PASSIVE, and Creature::SetReactState().
Member Function Documentation
AttackStart()
void boss_jormungarAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 541 of file boss_northrend_beasts.cpp.
     {
         if( me->GetDisplayId() == _MODEL_STATIONARY )
         {
             if( !who )
                 return;
             if( me->Attack(who, true) )
                 DoStartNoMovement(who);
         }
         else
             ScriptedAI::AttackStart(who);
     }
References _MODEL_STATIONARY, Unit::Attack(), ScriptedAI::AttackStart(), ScriptedAI::DoStartNoMovement(), Unit::GetDisplayId(), and ScriptedAI::me.
DoAction()
void boss_jormungarAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 489 of file boss_northrend_beasts.cpp.
     {
         switch( param )
         {
             case -1:
                 if( !me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE) )
                     events.RescheduleEvent(EVENT_SUBMERGE, 1500);
                 break;
             case -2:
                 if( me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE) )
                     bIsStationary = true; // it will come out mobile soon
                 else if( me->GetDisplayId() == _MODEL_STATIONARY )
                     events.RescheduleEvent(EVENT_SUBMERGE, 1000);
                 else
                     events.CancelEvent(EVENT_SUBMERGE);
                 me->CastSpell(me, SPELL_ENRAGE, true);
                 Talk(EMOTE_ENRAGE);
                 break;
         }
     }
References _MODEL_STATIONARY, bIsStationary, Unit::CastSpell(), EMOTE_ENRAGE, EVENT_SUBMERGE, Unit::GetDisplayId(), Object::HasFlag(), ScriptedAI::me, SPELL_ENRAGE, CreatureAI::Talk(), UNIT_FIELD_FLAGS, and UNIT_FLAG_NON_ATTACKABLE.
EnterCombat()
void boss_jormungarAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 530 of file boss_northrend_beasts.cpp.
     {
         me->setActive(true);
         ScheduleEvents();
     }
References ScriptedAI::me, ScheduleEvents(), and WorldObject::setActive().
EnterEvadeMode()
void boss_jormungarAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 670 of file boss_northrend_beasts.cpp.
     {
         events.Reset();
         me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
         if( pInstance )
             pInstance->SetData(TYPE_FAILED, 1);
     }
References ScriptedAI::me, pInstance, ZoneScript::SetData(), Object::SetFlag(), TYPE_FAILED, UNIT_FIELD_FLAGS, and UNIT_FLAG_NON_ATTACKABLE.
JustDied()
void boss_jormungarAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 659 of file boss_northrend_beasts.cpp.
     {
         if( pInstance )
         {
             if( Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(_TYPE_OTHER)) )
                 if( c->IsAlive() )
                     c->AI()->DoAction(-2);
             pInstance->SetData(TYPE_JORMUNGAR, DONE);
         }
     }
References _TYPE_OTHER, DONE, Map::GetCreature(), InstanceScript::GetGuidData(), InstanceScript::instance, pInstance, ZoneScript::SetData(), and TYPE_JORMUNGAR.
JustReachedHome()
void boss_jormungarAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 536 of file boss_northrend_beasts.cpp.
     {
         me->setActive(false);
     }
References ScriptedAI::me, and WorldObject::setActive().
ScheduleEvents()
void boss_jormungarAI::ScheduleEvents () inline
Definition at line 510 of file boss_northrend_beasts.cpp.
     {
         events.Reset();
         if( me->GetDisplayId() == _MODEL_STATIONARY )
         {
             me->SetAttackTime(BASE_ATTACK, 1500);
             events.RescheduleEvent(EVENT_SPELL_SPRAY, (me->GetEntry() == NPC_ACIDMAW ? 20000 : 15000));
             events.RescheduleEvent(EVENT_SPELL_SWEEP, urand(15000, 30000));
         }
         else
         {
             me->SetAttackTime(BASE_ATTACK, 2000);
             events.RescheduleEvent(EVENT_SPELL_BITE, (me->GetEntry() == NPC_ACIDMAW ? 20000 : 15000));
             events.RescheduleEvent(EVENT_SPELL_SPEW, urand(15000, 30000));
             events.RescheduleEvent(EVENT_SPELL_SLIME_POOL, 15000);
         }
         if( !me->HasAura(SPELL_ENRAGE) )
             events.RescheduleEvent(EVENT_SUBMERGE, urand(45000, 50000));
     }
References _MODEL_STATIONARY, BASE_ATTACK, EVENT_SPELL_BITE, EVENT_SPELL_SLIME_POOL, EVENT_SPELL_SPEW, EVENT_SPELL_SPRAY, EVENT_SPELL_SWEEP, EVENT_SUBMERGE, Unit::GetDisplayId(), Object::GetEntry(), Unit::HasAura(), ScriptedAI::me, NPC_ACIDMAW, Unit::SetAttackTime(), SPELL_ENRAGE, and urand().
Referenced by EnterCombat(), and UpdateAI().
UpdateAI()
void boss_jormungarAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 554 of file boss_northrend_beasts.cpp.
     {
         if( !UpdateVictim() )
             return;
         events.Update(diff);
         if( me->HasUnitState(UNIT_STATE_CASTING) )
             return;
         switch( events.ExecuteEvent() )
         {
             case 0:
                 break;
             case EVENT_SUBMERGE:
                 {
                     bIsStationary = (me->GetDisplayId() == _MODEL_STATIONARY);
                     me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE);
                     me->CastSpell(me, SPELL_SUBMERGE_0, false);
                     Talk(EMOTE_SUBMERGE);
                     // second one submerge 1.5sec after the first one, used also for synchronizing
                     if( pInstance )
                         if( Creature* c = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(_TYPE_OTHER)) )
                             c->AI()->DoAction(-1);
                     events.Reset();
                     events.RescheduleEvent(EVENT_MOVE_UNDERGROUND, 2500);
                 }
                 break;
             case EVENT_MOVE_UNDERGROUND:
                 {
                     float angle = me->GetAngle(Locs[LOC_CENTER].GetPositionX() + urand(0, 20) - 10.0f, Locs[LOC_CENTER].GetPositionY() + urand(0, 20) - 10.0f), dist = urand(10, 35);
                     if( Creature* c = me->SummonCreature(NPC_WORLD_TRIGGER, *me, TEMPSUMMON_TIMED_DESPAWN, 6000) )
                     {
                         c->SetSpeed(MOVE_RUN, 2.5f);
                         c->CastSpell(c, SPELL_CHURNING_GROUND, true);
                         c->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_PACIFIED);
                         c->GetMotionMaster()->MovePoint(0, Locs[LOC_CENTER].GetPositionX() + cos(angle)*dist, Locs[LOC_CENTER].GetPositionY() + sin(angle)*dist, me->GetPositionZ());
                     }
                     me->UpdatePosition(Locs[LOC_CENTER].GetPositionX() + cos(angle)*dist, Locs[LOC_CENTER].GetPositionY() + sin(angle)*dist, me->GetPositionZ(), me->GetOrientation(), true);
                     me->StopMovingOnCurrentPos();
                     DoResetThreat();
                     events.RescheduleEvent(EVENT_EMERGE, 6000);
                 }
                 break;
             case EVENT_EMERGE:
                 {
                     me->GetMotionMaster()->Clear();
                     me->GetMotionMaster()->MoveIdle();
                     me->StopMoving();
                     if( bIsStationary )
                     {
                         me->SetNativeDisplayId(_MODEL_MOBILE);
                         SetCombatMovement(true);
                         if( Unit* victim = me->GetVictim() )
                             me->GetMotionMaster()->MoveChase(victim);
                     }
                     else
                     {
                         me->SetNativeDisplayId(_MODEL_STATIONARY);
                         SetCombatMovement(false);
                     }
                     me->RemoveAurasDueToSpell(SPELL_SUBMERGE_0);
                     me->CastSpell(me, SPELL_EMERGE_0, false);
                     Talk(EMOTE_EMERGE);
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE);
                     ScheduleEvents();
                 }
                 break;
             case EVENT_SPELL_SPRAY:
                 if( Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 100.0f, true) )
                     me->CastSpell(target, _SPELL_SPRAY, false);
                 events.RepeatEvent(20000);
                 break;
             case EVENT_SPELL_SWEEP:
                 me->CastSpell((Unit*)nullptr, SPELL_SWEEP_0, false);
                 events.RepeatEvent(urand(15000, 30000));
                 break;
             case EVENT_SPELL_BITE:
                 if( Unit* victim = me->GetVictim() )
                     me->CastSpell(victim, _SPELL_BITE, false);
                 events.RepeatEvent(20000);
                 break;
             case EVENT_SPELL_SPEW:
                 me->CastSpell(me->GetVictim(), _SPELL_SPEW, false);
                 events.RepeatEvent(urand(15000, 30000));
                 break;
             case EVENT_SPELL_SLIME_POOL:
                 if( Creature* c = me->SummonCreature(NPC_SLIME_POOL, *me, TEMPSUMMON_TIMED_DESPAWN, 30000) )
                     c->CastSpell(c, SPELL_SLIME_POOL_EFFECT, true);
                 events.RepeatEvent(30000);
                 break;
         }
         if( !me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE) )
         {
             if( me->GetDisplayId() == _MODEL_STATIONARY )
                 DoSpellAttackIfReady(_SPELL_SPIT);
             else
                 DoMeleeAttackIfReady();
         }
     }
References _MODEL_MOBILE, _MODEL_STATIONARY, _SPELL_BITE, _SPELL_SPEW, _SPELL_SPIT, _SPELL_SPRAY, _TYPE_OTHER, bIsStationary, Unit::CastSpell(), MotionMaster::Clear(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DoResetThreat(), UnitAI::DoSpellAttackIfReady(), EMOTE_EMERGE, EMOTE_SUBMERGE, EVENT_EMERGE, EVENT_MOVE_UNDERGROUND, EVENT_SPELL_BITE, EVENT_SPELL_SLIME_POOL, EVENT_SPELL_SPEW, EVENT_SPELL_SPRAY, EVENT_SPELL_SWEEP, EVENT_SUBMERGE, Position::GetAngle(), ObjectAccessor::GetCreature(), Unit::GetDisplayId(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), Position::GetOrientation(), Position::GetPositionZ(), Unit::GetVictim(), Object::HasFlag(), Unit::HasUnitState(), LOC_CENTER, Locs, ScriptedAI::me, MOVE_RUN, MotionMaster::MoveChase(), MotionMaster::MoveIdle(), NPC_SLIME_POOL, NPC_WORLD_TRIGGER, pInstance, Unit::RemoveAurasDueToSpell(), Object::RemoveFlag(), ScheduleEvents(), SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), ScriptedAI::SetCombatMovement(), Object::SetFlag(), Unit::SetNativeDisplayId(), SPELL_CHURNING_GROUND, SPELL_EMERGE_0, SPELL_SLIME_POOL_EFFECT, SPELL_SUBMERGE_0, SPELL_SWEEP_0, Unit::StopMoving(), Unit::StopMovingOnCurrentPos(), WorldObject::SummonCreature(), CreatureAI::Talk(), TEMPSUMMON_TIMED_DESPAWN, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, UNIT_FLAG_PACIFIED, UNIT_STATE_CASTING, Unit::UpdatePosition(), CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
_MODEL_MOBILE
uint32 boss_jormungarAI::_MODEL_MOBILE
Definition at line 486 of file boss_northrend_beasts.cpp.
Referenced by boss_acidmaw::boss_acidmawAI::boss_acidmawAI(), boss_dreadscale::boss_dreadscaleAI::boss_dreadscaleAI(), and UpdateAI().
_MODEL_STATIONARY
uint32 boss_jormungarAI::_MODEL_STATIONARY
Definition at line 485 of file boss_northrend_beasts.cpp.
Referenced by AttackStart(), boss_acidmaw::boss_acidmawAI::boss_acidmawAI(), boss_dreadscale::boss_dreadscaleAI::boss_dreadscaleAI(), DoAction(), ScheduleEvents(), and UpdateAI().
_SPELL_BITE
uint32 boss_jormungarAI::_SPELL_BITE
Definition at line 481 of file boss_northrend_beasts.cpp.
Referenced by boss_acidmaw::boss_acidmawAI::boss_acidmawAI(), boss_dreadscale::boss_dreadscaleAI::boss_dreadscaleAI(), and UpdateAI().
_SPELL_SPEW
uint32 boss_jormungarAI::_SPELL_SPEW
Definition at line 482 of file boss_northrend_beasts.cpp.
Referenced by boss_acidmaw::boss_acidmawAI::boss_acidmawAI(), boss_dreadscale::boss_dreadscaleAI::boss_dreadscaleAI(), and UpdateAI().
_SPELL_SPIT
uint32 boss_jormungarAI::_SPELL_SPIT
Definition at line 483 of file boss_northrend_beasts.cpp.
Referenced by boss_acidmaw::boss_acidmawAI::boss_acidmawAI(), boss_dreadscale::boss_dreadscaleAI::boss_dreadscaleAI(), and UpdateAI().
_SPELL_SPRAY
uint32 boss_jormungarAI::_SPELL_SPRAY
Definition at line 484 of file boss_northrend_beasts.cpp.
Referenced by boss_acidmaw::boss_acidmawAI::boss_acidmawAI(), boss_dreadscale::boss_dreadscaleAI::boss_dreadscaleAI(), and UpdateAI().
_TYPE_OTHER
uint32 boss_jormungarAI::_TYPE_OTHER
Definition at line 487 of file boss_northrend_beasts.cpp.
Referenced by boss_acidmaw::boss_acidmawAI::boss_acidmawAI(), boss_dreadscale::boss_dreadscaleAI::boss_dreadscaleAI(), JustDied(), and UpdateAI().
bIsStationary
bool boss_jormungarAI::bIsStationary
Definition at line 479 of file boss_northrend_beasts.cpp.
Referenced by DoAction(), and UpdateAI().
events
EventMap boss_jormungarAI::events
Definition at line 478 of file boss_northrend_beasts.cpp.
pInstance
InstanceScript* boss_jormungarAI::pInstance
Definition at line 477 of file boss_northrend_beasts.cpp.
Referenced by boss_jormungarAI(), EnterEvadeMode(), JustDied(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_northrend_beasts.cpp