Azerotcore-wotlk: MovableMapObject Class Reference
MovableMapObject Class Reference
#include <Object.h>
Protected Member Functions
MovableMapObject ()
Private Member Functions
Cell const & GetCurrentCell () const
void SetCurrentCell (Cell const &cell)
Private Attributes
Cell _currentCell
MapObjectCellMoveState _moveState {MAP_OBJECT_CELL_MOVE_NONE}
Friends
class Map
class ObjectGridLoader
template<class T >
class RandomMovementGenerator
Detailed Description
Definition at line 651 of file Object.h.
Constructor & Destructor Documentation
MovableMapObject()
MovableMapObject::MovableMapObject () inline protected
Definition at line 658 of file Object.h.
 {}
Member Function Documentation
GetCurrentCell()
Cell const& MovableMapObject::GetCurrentCell () const inline private
Definition at line 661 of file Object.h.
 { return _currentCell; }
References _currentCell.
Referenced by Map::CreatureRelocation(), Map::DynamicObjectRelocation(), Map::GameObjectRelocation(), Map::MoveAllCreaturesInMoveList(), Map::MoveAllDynamicObjectsInMoveList(), and Map::MoveAllGameObjectsInMoveList().
SetCurrentCell()
void MovableMapObject::SetCurrentCell (Cell const & cell) inline private
Definition at line 662 of file Object.h.
 { _currentCell = cell; }
References _currentCell.
Referenced by Map::AddToGrid(), and ObjectGridLoader::SetObjectCell().
Friends And Related Function Documentation
Map
friend class Map friend
Definition at line 653 of file Object.h.
ObjectGridLoader
friend class ObjectGridLoader friend
Definition at line 654 of file Object.h.
RandomMovementGenerator
template<class T > friend class RandomMovementGenerator friend
Definition at line 655 of file Object.h.
Member Data Documentation
_currentCell
Cell MovableMapObject::_currentCell private
Definition at line 664 of file Object.h.
Referenced by GetCurrentCell(), and SetCurrentCell().
_moveState
MapObjectCellMoveState MovableMapObject::_moveState {MAP_OBJECT_CELL_MOVE_NONE} private
Definition at line 665 of file Object.h.
Referenced by RandomMovementGenerator< T >::_setRandomLocation(), Map::AddCreatureToMoveList(), Map::AddDynamicObjectToMoveList(), Map::AddGameObjectToMoveList(), Map::MoveAllCreaturesInMoveList(), Map::MoveAllDynamicObjectsInMoveList(), Map::MoveAllGameObjectsInMoveList(), Map::RemoveCreatureFromMoveList(), Map::RemoveDynamicObjectFromMoveList(), and Map::RemoveGameObjectFromMoveList().
The documentation for this class was generated from the following file:
src/server/game/Entities/Object/Object.h