Azerotcore-wotlk: Acore::Impl::GenericBaseEncoding< Encoding > Struct Template Reference
Acore::Impl::GenericBaseEncoding< Encoding > Struct Template Reference
#include <BaseEncoding.h>
Static Public Member Functions
static constexpr std::size_t EncodedSize (std::size_t size)
static constexpr std::size_t DecodedSize (std::size_t size)
static std::string Encode (std::vector< uint8 > const &data)
static Optional< std::vector< uint8 > > Decode (std::string const &data)
Static Public Attributes
static constexpr std::size_t BITS_PER_CHAR = Encoding::BITS_PER_CHAR
static constexpr std::size_t PAD_TO = std::lcm(8u, BITS_PER_CHAR)
static constexpr uint8 DECODE_ERROR = Encoding::DECODE_ERROR
static constexpr char PADDING = Encoding::PADDING
Detailed Description
template<typename Encoding>
struct Acore::Impl::GenericBaseEncoding< Encoding >
Definition at line 18 of file BaseEncoding.h.
Member Function Documentation
Decode()
template<typename Encoding > static Optional<std::vector<uint8> > Acore::Impl::GenericBaseEncoding< Encoding >::Decode (std::string const & data) inline static
Definition at line 101 of file BaseEncoding.h.
         {
             auto it = data.begin(), end = data.end();
             if (it == end)
             {
                 return std::vector<uint8>();
             }
             std::vector<uint8> v;
             v.reserve(DecodedSize(data.size()));
             uint8 currentByte = 0;
             uint8 bitsLeft = 8; // in current byte
             while ((it != end) && (*it != PADDING))
             {
                 uint8 cur = Encoding::Decode(*(it++));
                 if (cur == DECODE_ERROR)
                     return {};
                 if (bitsLeft > BITS_PER_CHAR)
                 {
                     bitsLeft -= BITS_PER_CHAR;
                     currentByte |= (cur << bitsLeft);
                 }
                 else
                 {
                     bitsLeft = BITS_PER_CHAR - bitsLeft; // in encoded char
                     currentByte |= (cur >> bitsLeft);
                     v.push_back(currentByte);
                     currentByte = (cur & ((1 << bitsLeft) - 1));
                     bitsLeft = 8 - bitsLeft; // in byte again
                     currentByte <<= bitsLeft;
                 }
             }
             if (currentByte)
                 return {}; // decode error, trailing non-zero bits
             // process padding
             while ((it != end) && (*it == PADDING) && (bitsLeft != 8))
             {
                 if (bitsLeft > BITS_PER_CHAR)
                 {
                     bitsLeft -= BITS_PER_CHAR;
                 }
                 else
                 {
                     bitsLeft += (8 - BITS_PER_CHAR);
                 }
                 ++it;
             }
             // ok, all padding should be consumed, and we should be at end of string
             if (it == end)
             {
                 return v;
             }
             // anything else is an error
             return {};
         }
References Acore::Impl::GenericBaseEncoding< Encoding >::BITS_PER_CHAR, Acore::Impl::GenericBaseEncoding< Encoding >::DECODE_ERROR, Acore::Impl::GenericBaseEncoding< Encoding >::DecodedSize(), and Acore::Impl::GenericBaseEncoding< Encoding >::PADDING.
Referenced by Acore::Encoding::Base32::Decode(), and Acore::Encoding::Base64::Decode().
DecodedSize()
template<typename Encoding > static constexpr std::size_t Acore::Impl::GenericBaseEncoding< Encoding >::DecodedSize (std::size_t size) inline static constexpr
Definition at line 38 of file BaseEncoding.h.
         {
             size *= BITS_PER_CHAR; // bits in input
             if (size % PAD_TO) // pad to boundary
             {
                 size += (PAD_TO - (size % PAD_TO));
             }
             return (size / 8);
         }
References Acore::Impl::GenericBaseEncoding< Encoding >::BITS_PER_CHAR, and Acore::Impl::GenericBaseEncoding< Encoding >::PAD_TO.
Referenced by Acore::Impl::GenericBaseEncoding< Encoding >::Decode().
Encode()
template<typename Encoding > static std::string Acore::Impl::GenericBaseEncoding< Encoding >::Encode (std::vector< uint8 > const & data) inline static
Definition at line 48 of file BaseEncoding.h.
         {
             auto it = data.begin(), end = data.end();
             if (it == end)
             {
                 return "";
             }
             std::string s;
             s.reserve(EncodedSize(data.size()));
             uint8 bitsLeft = 8; // in current byte
             do
             {
                 uint8 thisC = 0;
                 if (bitsLeft >= BITS_PER_CHAR)
                 {
                     bitsLeft -= BITS_PER_CHAR;
                     thisC = ((*it >> bitsLeft) & ((1 << BITS_PER_CHAR) - 1));
                     if (!bitsLeft)
                     {
                         ++it;
                         bitsLeft = 8;
                     }
                 }
                 else
                 {
                     thisC = (*it & ((1 << bitsLeft) - 1)) << (BITS_PER_CHAR - bitsLeft);
                     bitsLeft += (8 - BITS_PER_CHAR);
                     if ((++it) != end)
                     {
                         thisC |= (*it >> bitsLeft);
                     }
                 }
                 s.append(1, Encoding::Encode(thisC));
             } while (it != end);
             while (bitsLeft != 8)
             {
                 if (bitsLeft > BITS_PER_CHAR)
                 {
                     bitsLeft -= BITS_PER_CHAR;
                 }
                 else
                 {
                     bitsLeft += (8 - BITS_PER_CHAR);
                 }
                 s.append(1, PADDING);
             }
             return s;
         }
References Acore::Impl::GenericBaseEncoding< Encoding >::BITS_PER_CHAR, Acore::Impl::GenericBaseEncoding< Encoding >::EncodedSize(), and Acore::Impl::GenericBaseEncoding< Encoding >::PADDING.
Referenced by Acore::Encoding::Base32::Encode(), and Acore::Encoding::Base64::Encode().
EncodedSize()
template<typename Encoding > static constexpr std::size_t Acore::Impl::GenericBaseEncoding< Encoding >::EncodedSize (std::size_t size) inline static constexpr
Definition at line 28 of file BaseEncoding.h.
         {
             size *= 8; // bits in input
             if (size % PAD_TO) // pad to boundary
             {
                 size += (PAD_TO - (size % PAD_TO));
             }
             return (size / BITS_PER_CHAR);
         }
References Acore::Impl::GenericBaseEncoding< Encoding >::BITS_PER_CHAR, and Acore::Impl::GenericBaseEncoding< Encoding >::PAD_TO.
Referenced by Acore::Impl::GenericBaseEncoding< Encoding >::Encode().
Member Data Documentation
BITS_PER_CHAR
template<typename Encoding > constexpr std::size_t Acore::Impl::GenericBaseEncoding< Encoding >::BITS_PER_CHAR = Encoding::BITS_PER_CHAR static constexpr
Definition at line 20 of file BaseEncoding.h.
Referenced by Acore::Impl::GenericBaseEncoding< Encoding >::Decode(), Acore::Impl::GenericBaseEncoding< Encoding >::DecodedSize(), Acore::Impl::GenericBaseEncoding< Encoding >::Encode(), and Acore::Impl::GenericBaseEncoding< Encoding >::EncodedSize().
DECODE_ERROR
template<typename Encoding > constexpr uint8 Acore::Impl::GenericBaseEncoding< Encoding >::DECODE_ERROR = Encoding::DECODE_ERROR static constexpr
Definition at line 25 of file BaseEncoding.h.
Referenced by Acore::Impl::GenericBaseEncoding< Encoding >::Decode().
PAD_TO
template<typename Encoding > constexpr std::size_t Acore::Impl::GenericBaseEncoding< Encoding >::PAD_TO = std::lcm(8u, BITS_PER_CHAR) static constexpr
Definition at line 21 of file BaseEncoding.h.
Referenced by Acore::Impl::GenericBaseEncoding< Encoding >::DecodedSize(), and Acore::Impl::GenericBaseEncoding< Encoding >::EncodedSize().
PADDING
template<typename Encoding > constexpr char Acore::Impl::GenericBaseEncoding< Encoding >::PADDING = Encoding::PADDING static constexpr
Definition at line 26 of file BaseEncoding.h.
Referenced by Acore::Impl::GenericBaseEncoding< Encoding >::Decode(), and Acore::Impl::GenericBaseEncoding< Encoding >::Encode().
The documentation for this struct was generated from the following file:
src/common/Encoding/BaseEncoding.h