Azerotcore-wotlk: at_icc_gauntlet_event Class Reference
at_icc_gauntlet_event Class Reference
Public Member Functions
at_icc_gauntlet_event ()
bool OnTrigger (Player *player, AreaTrigger const *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 3715 of file icecrown_citadel.cpp.
Constructor & Destructor Documentation
at_icc_gauntlet_event()
at_icc_gauntlet_event::at_icc_gauntlet_event () inline
Definition at line 3718 of file icecrown_citadel.cpp.
 : AreaTriggerScript("at_icc_gauntlet_event") { }
Member Function Documentation
OnTrigger()
bool at_icc_gauntlet_event::OnTrigger (Player * player, AreaTrigger const *) inline override virtual
Reimplemented from AreaTriggerScript.
Definition at line 3720 of file icecrown_citadel.cpp.
     {
         if (InstanceScript* instance = player->GetInstanceScript())
             if (instance->GetBossState(DATA_SINDRAGOSA_GAUNTLET) == NOT_STARTED && !player->IsGameMaster())
                 if (Creature* gauntlet = ObjectAccessor::GetCreature(*player, instance->GetGuidData(NPC_SINDRAGOSA_GAUNTLET)))
                     gauntlet->AI()->DoAction(ACTION_START_GAUNTLET);
         return true;
     }
References ACTION_START_GAUNTLET, DATA_SINDRAGOSA_GAUNTLET, ObjectAccessor::GetCreature(), WorldObject::GetInstanceScript(), Player::IsGameMaster(), NOT_STARTED, and NPC_SINDRAGOSA_GAUNTLET.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp