Azerotcore-wotlk: FormationMgr Class Reference
FormationMgr Class Reference
#include <CreatureGroups.h>
Public Member Functions
FormationMgr ()
~FormationMgr ()
void AddCreatureToGroup (uint32 group_id, Creature *creature)
void RemoveCreatureFromGroup (CreatureGroup *group, Creature *creature)
void LoadCreatureFormations ()
Static Public Member Functions
static FormationMgr * instance ()
Public Attributes
CreatureGroupInfoType CreatureGroupMap
Detailed Description
Definition at line 70 of file CreatureGroups.h.
Constructor & Destructor Documentation
FormationMgr()
FormationMgr::FormationMgr () inline
Definition at line 73 of file CreatureGroups.h.
 { }
~FormationMgr()
FormationMgr::~FormationMgr ()
Definition at line 25 of file CreatureGroups.cpp.
 {
 }
Member Function Documentation
AddCreatureToGroup()
void FormationMgr::AddCreatureToGroup (uint32 group_id, Creature * creature)
Definition at line 35 of file CreatureGroups.cpp.
 {
     Map* map = member->FindMap();
     if (!map)
     {
         return;
     }
     CreatureGroupHolderType::iterator itr = map->CreatureGroupHolder.find(groupId);
     //Add member to an existing group
     if (itr != map->CreatureGroupHolder.end())
     {
         LOG_DEBUG("entities.unit", "Group found: %u, inserting creature %s, Group InstanceID %u", groupId, member->GetGUID().ToString().c_str(), member->GetInstanceId());
         itr->second->AddMember(member);
     }
     //Create new group
     else
     {
         LOG_DEBUG("entities.unit", "Group not found: %u. Creating new group.", groupId);
         CreatureGroup* group = new CreatureGroup(groupId);
         map->CreatureGroupHolder[groupId] = group;
         group->AddMember(member);
     }
 }
References CreatureGroup::AddMember(), Map::CreatureGroupHolder, WorldObject::FindMap(), Object::GetGUID(), WorldObject::GetInstanceId(), LOG_DEBUG, and ObjectGuid::ToString().
instance()
FormationMgr * FormationMgr::instance () static
Definition at line 29 of file CreatureGroups.cpp.
 {
     static FormationMgr instance;
     return &instance;
 }
LoadCreatureFormations()
void FormationMgr::LoadCreatureFormations ()
Definition at line 80 of file CreatureGroups.cpp.
 {
     uint32 const oldMSTime = getMSTime();
     CreatureGroupMap.clear();
     //Get group data
     QueryResult result = WorldDatabase.Query("SELECT leaderGUID, memberGUID, dist, angle, groupAI, point_1, point_2 FROM creature_formations ORDER BY leaderGUID");
     if (!result)
     {
         LOG_ERROR("sql.sql", ">>  Loaded 0 creatures in formations. DB table `creature_formations` is empty!");
         LOG_INFO("server.loading", " ");
         return;
     }
     uint32 count = 0;
     do
     {
         Field const* fields = result->Fetch();
         //Load group member data
         FormationInfo group_member;
         group_member.leaderGUID            = fields[0].GetUInt32();
         ObjectGuid::LowType const memberGUID = fields[1].GetUInt32();
         float const follow_dist             = fields[2].GetFloat();
         float const follow_angle            = fields[3].GetFloat() * (static_cast<float>(M_PI) / 180);
         group_member.groupAI               = fields[4].GetUInt16();
         group_member.point_1               = fields[5].GetUInt16();
         group_member.point_2               = fields[6].GetUInt16();
         //If creature is group leader we may skip loading of dist/angle
         if (group_member.leaderGUID != memberGUID)
         {
             if (!group_member.HasGroupFlag(std::underlying_type_t<GroupAIFlags>(GroupAIFlags::GROUP_AI_FLAG_SUPPORTED)))
             {
                 LOG_ERROR("sql.sql", "creature_formations table leader guid %u and member guid %u has unsupported GroupAI flag value (%u). Skipped", group_member.leaderGUID, memberGUID, group_member.groupAI);
                 continue;
             }
             if (!group_member.HasGroupFlag(std::underlying_type_t<GroupAIFlags>(GroupAIFlags::GROUP_AI_FLAG_FOLLOW_LEADER)) && (follow_dist > 0.0f || follow_angle > 0.0f))
             {
                 LOG_ERROR("sql.sql", "creature_formations table member guid %u and leader guid %u cannot have follow distance or follow angle because don't have GROUP_AI_FLAG_FOLLOW_LEADER flag. Values are not gonna be used", memberGUID, group_member.leaderGUID);
                 group_member.follow_dist       = 0.0f;
                 group_member.follow_angle      = 0.0f;
             }
             else
             {
                 group_member.follow_dist       = follow_dist;
                 group_member.follow_angle      = follow_angle;
             }
         }
         else
         {
             // Leader can have 0 AI flags - its allowed
             if (group_member.groupAI && !group_member.HasGroupFlag(std::underlying_type_t<GroupAIFlags>(GroupAIFlags::GROUP_AI_FLAG_SUPPORTED)))
             {
                 LOG_ERROR("sql.sql", "creature_formations table leader guid %u and member guid %u has unsupported GroupAI flag value (%u). Skipped", group_member.leaderGUID, memberGUID, group_member.groupAI);
                 continue;
             }
             group_member.follow_dist       = 0.0f;
             group_member.follow_angle      = 0.0f;
             if (follow_dist > 0.0f || follow_angle > 0.0f)
             {
                 LOG_ERROR("sql.sql", "creature_formations table member guid %u and leader guid %u cannot have follow distance or follow angle. Values are not gonna be used", memberGUID, group_member.leaderGUID);
             }
         }
         if (!sObjectMgr->GetCreatureData(group_member.leaderGUID))
         {
             LOG_ERROR("sql.sql", "creature_formations table leader guid %u incorrect (does not exist). Skipped", group_member.leaderGUID);
             continue;
         }
         if (!sObjectMgr->GetCreatureData(memberGUID))
         {
             LOG_ERROR("sql.sql", "creature_formations table member guid %u incorrect (does not exist). Skipped", memberGUID);
             continue;
         }
         CreatureGroupMap[memberGUID] = group_member;
         ++count;
     } while (result->NextRow());
     LOG_INFO("server.loading", ">> Loaded %u creatures in formations in %u ms", count, GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
 }
References CreatureGroupMap, FormationInfo::follow_angle, FormationInfo::follow_dist, Field::GetFloat(), getMSTime(), GetMSTimeDiffToNow(), Field::GetUInt16(), Field::GetUInt32(), GROUP_AI_FLAG_FOLLOW_LEADER, GROUP_AI_FLAG_SUPPORTED, FormationInfo::groupAI, FormationInfo::HasGroupFlag(), FormationInfo::leaderGUID, LOG_ERROR, LOG_INFO, FormationInfo::point_1, FormationInfo::point_2, sObjectMgr, and WorldDatabase.
RemoveCreatureFromGroup()
void FormationMgr::RemoveCreatureFromGroup (CreatureGroup * group, Creature * creature)
Definition at line 61 of file CreatureGroups.cpp.
 {
     LOG_DEBUG("entities.unit", "Deleting member pointer to spawnId: %u from group %u", member->GetSpawnId(), group->GetId());
     group->RemoveMember(member);
     if (group->isEmpty())
     {
         Map* map = member->FindMap();
         if (!map)
         {
             return;
         }
         LOG_DEBUG("entities.unit", "Deleting group with InstanceID %u", member->GetInstanceId());
         map->CreatureGroupHolder.erase(group->GetId());
         delete group;
     }
 }
References Map::CreatureGroupHolder, WorldObject::FindMap(), CreatureGroup::GetId(), WorldObject::GetInstanceId(), Creature::GetSpawnId(), CreatureGroup::isEmpty(), LOG_DEBUG, and CreatureGroup::RemoveMember().
Member Data Documentation
CreatureGroupMap
CreatureGroupInfoType FormationMgr::CreatureGroupMap
Definition at line 81 of file CreatureGroups.h.
Referenced by LoadCreatureFormations().
The documentation for this class was generated from the following files:
src/server/game/Entities/Creature/CreatureGroups.h
src/server/game/Entities/Creature/CreatureGroups.cpp