Azerotcore-wotlk: DBCFile::Record Class Reference
DBCFile::Record Class Reference
#include <dbcfile.h>
Public Member Functions
float getFloat (size_t field) const
unsigned int getUInt (size_t field) const
int getInt (size_t field) const
const char * getString (size_t field) const
Record & operator= (const Record &r)
float getFloat (size_t field) const
unsigned int getUInt (size_t field) const
int getInt (size_t field) const
unsigned char getByte (size_t ofs) const
const char * getString (size_t field) const
Private Member Functions
Record (DBCFile &file, unsigned char *offset)
Record (DBCFile &file, unsigned char *offset)
Private Attributes
DBCFile & file
unsigned char * offset
Friends
class DBCFile
class DBCFile::Iterator
class Iterator
Detailed Description
Definition at line 52 of file dbcfile.h.
Constructor & Destructor Documentation
Record() [1/2]
DBCFile::Record::Record (DBCFile & file, unsigned char * offset) inline private
Definition at line 78 of file dbcfile.h.
 : file(file), offset(offset) {}
Record() [2/2]
DBCFile::Record::Record (DBCFile & file, unsigned char * offset) inline private
Definition at line 97 of file dbcfile.h.
 : file(file), offset(offset) {}
Member Function Documentation
getByte()
unsigned char DBCFile::Record::getByte (size_t ofs) const inline
Definition at line 82 of file dbcfile.h.
         {
             assert(ofs < file.recordSize);
             return *reinterpret_cast<unsigned char*>(offset + ofs);
         }
References file, offset, and DBCFile::recordSize.
getFloat() [1/2]
float DBCFile::Record::getFloat (size_t field) const inline
Definition at line 55 of file dbcfile.h.
         {
             assert(field < file.fieldCount);
             return *reinterpret_cast<float*>(offset + field * 4);
         }
References DBCFile::fieldCount, file, and offset.
getFloat() [2/2]
float DBCFile::Record::getFloat (size_t field) const inline
Definition at line 67 of file dbcfile.h.
         {
             assert(field < file.fieldCount);
             return *reinterpret_cast<float*>(offset + field * 4);
         }
References DBCFile::fieldCount, file, and offset.
getInt() [1/2]
int DBCFile::Record::getInt (size_t field) const inline
Definition at line 65 of file dbcfile.h.
         {
             assert(field < file.fieldCount);
             return *reinterpret_cast<int*>(offset + field * 4);
         }
References DBCFile::fieldCount, file, and offset.
getInt() [2/2]
int DBCFile::Record::getInt (size_t field) const inline
Definition at line 77 of file dbcfile.h.
         {
             assert(field < file.fieldCount);
             return *reinterpret_cast<int*>(offset + field * 4);
         }
References DBCFile::fieldCount, file, and offset.
getString() [1/2]
const char* DBCFile::Record::getString (size_t field) const inline
Definition at line 70 of file dbcfile.h.
         {
             assert(field < file.fieldCount);
             size_t stringOffset = getUInt(field);
             assert(stringOffset < file.stringSize);
             return reinterpret_cast<char*>(file.stringTable + stringOffset);
         }
References DBCFile::fieldCount, file, getUInt(), DBCFile::stringSize, and DBCFile::stringTable.
Referenced by ExtractCameraFiles(), main(), and ReadMapDBC().
getString() [2/2]
const char* DBCFile::Record::getString (size_t field) const inline
Definition at line 87 of file dbcfile.h.
         {
             assert(field < file.fieldCount);
             size_t stringOffset = getUInt(field);
             assert(stringOffset < file.stringSize);
             //char * tmp = (char*)file.stringTable + stringOffset;
             //unsigned char * tmp2 = file.stringTable + stringOffset;
             return reinterpret_cast<char*>(file.stringTable + stringOffset);
         }
References DBCFile::fieldCount, file, getUInt(), DBCFile::stringSize, and DBCFile::stringTable.
getUInt() [1/2]
unsigned int DBCFile::Record::getUInt (size_t field) const inline
Definition at line 60 of file dbcfile.h.
         {
             assert(field < file.fieldCount);
             return *reinterpret_cast<unsigned int*>(offset + field * 4);
         }
References DBCFile::fieldCount, file, and offset.
Referenced by DBCFile::getMaxId(), getString(), main(), ReadLiquidTypeTableDBC(), and ReadMapDBC().
getUInt() [2/2]
unsigned int DBCFile::Record::getUInt (size_t field) const inline
Definition at line 72 of file dbcfile.h.
         {
             assert(field < file.fieldCount);
             return *reinterpret_cast<unsigned int*>(offset + (field * 4));
         }
References DBCFile::fieldCount, file, and offset.
operator=()
Record& DBCFile::Record::operator= (const Record & r) inline
Definition at line 61 of file dbcfile.h.
         {
             file = r.file;
             offset = r.offset;
             return *this;
         }
References file, and offset.
Friends And Related Function Documentation
DBCFile
DBCFile friend
Definition at line 82 of file dbcfile.h.
DBCFile::Iterator
friend class DBCFile::Iterator friend
Definition at line 83 of file dbcfile.h.
Iterator
friend class Iterator friend
Definition at line 102 of file dbcfile.h.
Member Data Documentation
file
DBCFile & DBCFile::Record::file private
Definition at line 79 of file dbcfile.h.
Referenced by getByte(), getFloat(), getInt(), getString(), getUInt(), DBCFile::Iterator::operator++(), and operator=().
offset
unsigned char * DBCFile::Record::offset private
Definition at line 80 of file dbcfile.h.
Referenced by getByte(), getFloat(), getInt(), getUInt(), DBCFile::Iterator::operator!=(), DBCFile::Iterator::operator++(), operator=(), and DBCFile::Iterator::operator==().
The documentation for this class was generated from the following file:
src/tools/map_extractor/dbcfile.h