Azerotcore-wotlk: deps/mysqllite/mysys/my_open.c File Reference
my_open.c File Reference
#include "mysys_priv.h"
#include "mysys_err.h"
#include <my_dir.h>
#include <errno.h>
Functions
File my_open (const char *FileName, int Flags, myf MyFlags)
int my_close (File fd, myf MyFlags)
File my_register_filename (File fd, const char *FileName, enum file_type type_of_file, uint error_message_number, myf MyFlags)
Function Documentation
my_close()
int my_close (File fd, myf MyFlags)
Definition at line 67 of file my_open.c.
 {
   int err;
   DBUG_ENTER("my_close");
   DBUG_PRINT("my",("fd: %d  MyFlags: %d",fd, MyFlags));
   mysql_mutex_lock(&THR_LOCK_open);
 #ifndef _WIN32
   do
   {
     err= close(fd);
   } while (err == -1 && errno == EINTR);
 #else
   err= my_win_close(fd);
 #endif
   if (err)
   {
     DBUG_PRINT("error",("Got error %d on close",err));
     my_errno=errno;
     if (MyFlags & (MY_FAE | MY_WME))
       my_error(EE_BADCLOSE, MYF(ME_BELL+ME_WAITTANG),my_filename(fd),errno);
   }
   if ((uint) fd < my_file_limit && my_file_info[fd].type != UNOPEN)
   {
     my_free(my_file_info[fd].name);
 #if !defined(HAVE_PREAD) && !defined(_WIN32)
     mysql_mutex_destroy(&my_file_info[fd].mutex);
 #endif
     my_file_info[fd].type = UNOPEN;
   }
   my_file_opened--;
   mysql_mutex_unlock(&THR_LOCK_open);
   DBUG_RETURN(err);
 } /* my_close */
References close, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_BADCLOSE, errno, ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_FAE, my_file_info, my_file_limit, my_file_opened, my_filename(), my_free(), MY_WME, MYF, mysql_mutex_destroy, mysql_mutex_lock, mysql_mutex_unlock, THR_LOCK_open, st_my_file_info::type, and UNOPEN.
Referenced by cache_remove_open_tmp(), close_cached_file(), default_local_infile_end(), inline_mysql_file_close(), my_copy(), my_create(), my_create_with_symlink(), and my_register_filename().
my_open()
File my_open (const char * FileName, int Flags, myf MyFlags)
Definition at line 35 of file my_open.c.
 {
   File fd;
   DBUG_ENTER("my_open");
   DBUG_PRINT("my",("Name: '%s'  Flags: %d  MyFlags: %d",
            FileName, Flags, MyFlags));
 #if defined(_WIN32)
   fd= my_win_open(FileName, Flags);
 #elif !defined(NO_OPEN_3)
   fd = open(FileName, Flags, my_umask); /* Normal unix */
 #else
   fd = open((char *) FileName, Flags);
 #endif
   DBUG_RETURN(my_register_filename(fd, FileName, FILE_BY_OPEN,
                    EE_FILENOTFOUND, MyFlags));
 } /* my_open */
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_FILENOTFOUND, FILE_BY_OPEN, my_register_filename(), my_umask, and open.
Referenced by create_temp_file(), default_local_infile_init(), inline_mysql_file_open(), and my_copy().
my_register_filename()
File my_register_filename (File fd, const char * FileName, enum file_type type_of_file, uint error_message_number, myf MyFlags)
Definition at line 120 of file my_open.c.
 {
   DBUG_ENTER("my_register_filename");
   if ((int) fd >= MY_FILE_MIN)
   {
     if ((uint) fd >= my_file_limit)
     {
 #if !defined(HAVE_PREAD)
       my_errno= EMFILE;
 #else
       thread_safe_increment(my_file_opened,&THR_LOCK_open);
       DBUG_RETURN(fd);              /* safeguard */
 #endif
     }
     else
     {
       mysql_mutex_lock(&THR_LOCK_open);
       if ((my_file_info[fd].name = (char*) my_strdup(FileName,MyFlags)))
       {
         my_file_opened++;
         my_file_total_opened++;
         my_file_info[fd].type = type_of_file;
 #if !defined(HAVE_PREAD) && !defined(_WIN32)
         mysql_mutex_init(key_my_file_info_mutex, &my_file_info[fd].mutex,
                          MY_MUTEX_INIT_FAST);
 #endif
         mysql_mutex_unlock(&THR_LOCK_open);
         DBUG_PRINT("exit",("fd: %d",fd));
         DBUG_RETURN(fd);
       }
       mysql_mutex_unlock(&THR_LOCK_open);
       my_errno= ENOMEM;
     }
     (void) my_close(fd, MyFlags);
   }
   else
     my_errno= errno;
   DBUG_PRINT("error",("Got error %d on open", my_errno));
   if (MyFlags & (MY_FFNF | MY_FAE | MY_WME))
   {
     if (my_errno == EMFILE)
       error_message_number= EE_OUT_OF_FILERESOURCES;
     DBUG_PRINT("error",("print err: %d",error_message_number));
     my_error(error_message_number, MYF(ME_BELL+ME_WAITTANG),
              FileName, my_errno);
   }
   DBUG_RETURN(-1);
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_OUT_OF_FILERESOURCES, errno, ME_BELL, ME_WAITTANG, my_close(), my_errno, my_error(), MY_FAE, MY_FFNF, my_file_info, my_file_limit, MY_FILE_MIN, my_file_opened, my_file_total_opened, MY_MUTEX_INIT_FAST, my_strdup(), MY_WME, MYF, mysql_mutex_init, mysql_mutex_lock, mysql_mutex_unlock, THR_LOCK_open, thread_safe_increment, and st_my_file_info::type.
Referenced by create_temp_file(), my_create(), and my_open().