Azerotcore-wotlk: deps/zlib/adler32.c File Reference
adler32.c File Reference
#include "zutil.h"
Macros
#define local static
#define BASE 65521 /* largest prime smaller than 65536 */
#define NMAX 5552
#define DO1(buf, i) {adler += (buf)[i]; sum2 += adler;}
#define DO2(buf, i) DO1(buf,i); DO1(buf,i+1);
#define DO4(buf, i) DO2(buf,i); DO2(buf,i+2);
#define DO8(buf, i) DO4(buf,i); DO4(buf,i+4);
#define DO16(buf) DO8(buf,0); DO8(buf,8);
#define MOD(a) a %= BASE
#define MOD28(a) a %= BASE
#define MOD63(a) a %= BASE
Functions
uLong adler32_combine_ OF ((uLong adler1, uLong adler2, z_off64_t len2))
uLong ZEXPORT adler32 (uLong adler, const Bytef *buf, uInt len)
uLong adler32_combine_ (uLong adler1, uLong adler2, z_off64_t len2)
uLong ZEXPORT adler32_combine (uLong adler1, uLong adler2, z_off_t len2)
uLong ZEXPORT adler32_combine64 (uLong adler1, uLong adler2, z_off64_t len2)
Macro Definition Documentation
BASE
#define BASE 65521 /* largest prime smaller than 65536 */
Definition at line 14 of file adler32.c.
DO1
#define DO1 (buf, i) {adler += (buf)[i]; sum2 += adler;}
Definition at line 18 of file adler32.c.
DO16
#define DO16 (buf) DO8(buf,0); DO8(buf,8);
Definition at line 22 of file adler32.c.
DO2
#define DO2 (buf, i) DO1(buf,i); DO1(buf,i+1);
Definition at line 19 of file adler32.c.
DO4
#define DO4 (buf, i) DO2(buf,i); DO2(buf,i+2);
Definition at line 20 of file adler32.c.
DO8
#define DO8 (buf, i) DO4(buf,i); DO4(buf,i+4);
Definition at line 21 of file adler32.c.
local
#define local static
Definition at line 10 of file adler32.c.
MOD
#define MOD (a) a %= BASE
Definition at line 59 of file adler32.c.
MOD28
#define MOD28 (a) a %= BASE
Definition at line 60 of file adler32.c.
MOD63
#define MOD63 (a) a %= BASE
Definition at line 61 of file adler32.c.
NMAX
#define NMAX 5552
Definition at line 15 of file adler32.c.
Function Documentation
adler32()
uLong ZEXPORT adler32 (uLong adler, const Bytef * buf, uInt len)
Definition at line 65 of file adler32.c.
 {
     unsigned long sum2;
     unsigned n;
     /* split Adler-32 into component sums */
     sum2 = (adler >> 16) & 0xffff;
     adler &= 0xffff;
     /* in case user likes doing a byte at a time, keep it fast */
     if (len == 1) {
         adler += buf[0];
         if (adler >= BASE)
             adler -= BASE;
         sum2 += adler;
         if (sum2 >= BASE)
             sum2 -= BASE;
         return adler | (sum2 << 16);
     }
     /* initial Adler-32 value (deferred check for len == 1 speed) */
     if (buf == Z_NULL)
         return 1L;
     /* in case short lengths are provided, keep it somewhat fast */
     if (len < 16) {
         while (len--) {
             adler += *buf++;
             sum2 += adler;
         }
         if (adler >= BASE)
             adler -= BASE;
         MOD28(sum2);            /* only added so many BASE's */
         return adler | (sum2 << 16);
     }
     /* do length NMAX blocks -- requires just one modulo operation */
     while (len >= NMAX) {
         len -= NMAX;
         n = NMAX / 16;          /* NMAX is divisible by 16 */
         do {
             DO16(buf);          /* 16 sums unrolled */
             buf += 16;
         } while (--n);
         MOD(adler);
         MOD(sum2);
     }
     /* do remaining bytes (less than NMAX, still just one modulo) */
     if (len) {                  /* avoid modulos if none remaining */
         while (len >= 16) {
             len -= 16;
             DO16(buf);
             buf += 16;
         }
         while (len--) {
             adler += *buf++;
             sum2 += adler;
         }
         MOD(adler);
         MOD(sum2);
     }
     /* return recombined sums */
     return adler | (sum2 << 16);
 }
References BASE, DO16, MOD, MOD28, NMAX, and Z_NULL.
Referenced by deflate(), deflateResetKeep(), deflateSetDictionary(), inflate(), inflateSetDictionary(), and read_buf().
adler32_combine()
uLong ZEXPORT adler32_combine (uLong adler1, uLong adler2, z_off_t len2)
Definition at line 165 of file adler32.c.
 {
     return adler32_combine_(adler1, adler2, len2);
 }
References adler32_combine_().
adler32_combine64()
uLong ZEXPORT adler32_combine64 (uLong adler1, uLong adler2, z_off64_t len2)
Definition at line 173 of file adler32.c.
 {
     return adler32_combine_(adler1, adler2, len2);
 }
References adler32_combine_().
adler32_combine_()
uLong adler32_combine_ (uLong adler1, uLong adler2, z_off64_t len2)
Definition at line 136 of file adler32.c.
 {
     unsigned long sum1;
     unsigned long sum2;
     unsigned rem;
     /* for negative len, return invalid adler32 as a clue for debugging */
     if (len2 < 0)
         return 0xffffffffUL;
     /* the derivation of this formula is left as an exercise for the reader */
     MOD63(len2);                /* assumes len2 >= 0 */
     rem = (unsigned)len2;
     sum1 = adler1 & 0xffff;
     sum2 = rem * sum1;
     MOD(sum2);
     sum1 += (adler2 & 0xffff) + BASE - 1;
     sum2 += ((adler1 >> 16) & 0xffff) + ((adler2 >> 16) & 0xffff) + BASE - rem;
     if (sum1 >= BASE) sum1 -= BASE;
     if (sum1 >= BASE) sum1 -= BASE;
     if (sum2 >= (BASE << 1)) sum2 -= (BASE << 1);
     if (sum2 >= BASE) sum2 -= BASE;
     return sum1 | (sum2 << 16);
 }
References BASE, MOD, and MOD63.
Referenced by adler32_combine(), and adler32_combine64().
OF()
uLong adler32_combine_ OF ((uLong adler1, uLong adler2, z_off64_t len2))