Azerotcore-wotlk: Acore::Impl::ChatCommands Namespace Reference
Acore::Impl::ChatCommands Namespace Reference
Classes
struct FilteredCommandListIterator
struct MultiConsumer
struct MultiConsumer< Tuple, Optional< NestedNextType >, offset >
struct HandlerToTuple
struct HandlerToTuple< bool(ChatHandler *, Ts...)>
struct CommandInvoker
struct CommandPermissions
class ChatCommandNode
struct ArgInfo
struct ArgInfo< T, std::enable_if_t< std::is_integral_v< T >||std::is_floating_point_v< T > > >
struct ArgInfo< std::string_view, void >
struct ArgInfo< std::string, void >
struct ArgInfo< std::wstring, void >
struct ArgInfo< T, std::enable_if_t< std::is_enum_v< T > > >
struct ArgInfo< T, std::enable_if_t< std::is_base_of_v< ContainerTag, T > > >
struct ArgInfo< std::vector< T >, void >
struct ArgInfo< std::array< T, N >, void >
struct ArgInfo< Acore::ChatCommands::Variant< Ts... > >
struct ArgInfo< AchievementEntry const * >
struct ArgInfo< GameTele const * >
struct ArgInfo< ItemTemplate const * >
struct ArgInfo< SpellInfo const * >
struct tag_base
struct TokenizeResult
struct are_all_assignable
struct are_all_assignable< void, Ts... >
struct get_nth
struct get_nth< 0, T1, Ts... >
struct ChatCommandResult
struct ContainerTag
struct tag_base< T, std::enable_if_t< std::is_base_of_v< ContainerTag, T > > >
Typedefs
template<typename T >
using TupleType = typename HandlerToTuple< T >::type
template<typename T >
using tag_base_t = typename tag_base< T >::type
template<std::size_t index, typename... Ts>
using get_nth_t = typename get_nth< index, Ts... >::type
Functions
template<typename Tuple , size_t offset>
ChatCommandResult ConsumeFromOffset (Tuple &, ChatHandler const *handler, std::string_view args)
template<typename Tuple , size_t offset>
ChatCommandResult ConsumeFromOffset ([[maybe_unused]] Tuple &tuple, [[maybe_unused]] ChatHandler const *handler, std::string_view args)
TokenizeResult tokenize (std::string_view args)
AC_GAME_API void SendErrorMessageToHandler (ChatHandler *handler, std::string_view str)
AC_GAME_API char const * GetAcoreString (ChatHandler const *handler, AcoreStrings which)
template<typename... Ts>
std::string FormatAcoreString (ChatHandler const *handler, AcoreStrings which, Ts &&... args)
template<size_t N>
constexpr char GetChar (char const (&s)[N], size_t i)
Variables
static constexpr char COMMAND_DELIMITER = ' '
Typedef Documentation
get_nth_t
template<std::size_t index, typename... Ts> using Acore::Impl::ChatCommands::get_nth_t = typedef typename get_nth<index, Ts...>::type
Definition at line 92 of file ChatCommandHelpers.h.
tag_base_t
template<typename T > using Acore::Impl::ChatCommands::tag_base_t = typedef typename tag_base<T>::type
Definition at line 47 of file ChatCommandHelpers.h.
TupleType
template<typename T > using Acore::Impl::ChatCommands::TupleType = typedef typename HandlerToTuple<T>::type
Definition at line 119 of file ChatCommand.h.
Function Documentation
ConsumeFromOffset() [1/2]
template<typename Tuple , size_t offset> ChatCommandResult Acore::Impl::ChatCommands::ConsumeFromOffset ([[maybe_unused] ] Tuple & tuple, [[maybe_unused] ] ChatHandler const * handler, std::string_view args)
Definition at line 107 of file ChatCommand.h.
     {
         if constexpr (offset < std::tuple_size_v<Tuple>)
             return MultiConsumer<Tuple, std::tuple_element_t<offset, Tuple>, offset>::TryConsumeTo(tuple, handler, args);
         else if (!args.empty()) /* the entire string must be consumed */
             return std::nullopt;
         else
             return args;
     }
ConsumeFromOffset() [2/2]
template<typename Tuple , size_t offset> ChatCommandResult Acore::Impl::ChatCommands::ConsumeFromOffset (Tuple & , ChatHandler const * handler, std::string_view args)
FormatAcoreString()
template<typename... Ts> std::string Acore::Impl::ChatCommands::FormatAcoreString (ChatHandler const * handler, AcoreStrings which, Ts &&... args)
Definition at line 126 of file ChatCommandHelpers.h.
     {
         return Acore::StringFormat(GetAcoreString(handler, which), std::forward<Ts>(args)...);
     }
References GetAcoreString(), and Acore::StringFormat().
Referenced by Acore::Impl::ChatCommands::ArgInfo< AchievementEntry const * >::TryConsume(), Acore::ChatCommands::AccountIdentifier::TryConsume(), Acore::ChatCommands::PlayerIdentifier::TryConsume(), Acore::ChatCommands::ExactSequence< chars >::TryConsume(), Acore::Impl::ChatCommands::ArgInfo< GameTele const * >::TryConsume(), Acore::Impl::ChatCommands::ArgInfo< ItemTemplate const * >::TryConsume(), Acore::Impl::ChatCommands::ArgInfo< SpellInfo const * >::TryConsume(), Acore::Impl::ChatCommands::ArgInfo< T, std::enable_if_t< std::is_integral_v< T >||std::is_floating_point_v< T > > >::TryConsume(), and Acore::Impl::ChatCommands::ArgInfo< T, std::enable_if_t< std::is_enum_v< T > > >::TryConsume().
GetAcoreString()
char const * Acore::Impl::ChatCommands::GetAcoreString (ChatHandler const * handler, AcoreStrings which)
Definition at line 28 of file ChatCommandHelpers.cpp.
 {
     return handler->GetAcoreString(which);
 }
References ChatHandler::GetAcoreString().
Referenced by FormatAcoreString(), ChatHandler::PGetParseString(), Player::PrepareGossipMenu(), Player::Satisfy(), Acore::Impl::ChatCommands::ArgInfo< Acore::ChatCommands::Variant< Ts... > >::TryAtIndex(), Acore::Impl::ChatCommands::ArgInfo< Acore::ChatCommands::Variant< Ts... > >::TryConsume(), Acore::ChatCommands::WTail::TryConsume(), Acore::ChatCommands::AccountIdentifier::TryConsume(), Acore::ChatCommands::Hyperlink< linktag >::TryConsume(), Acore::Impl::ChatCommands::ArgInfo< std::wstring, void >::TryConsume(), and Acore::Impl::ChatCommands::MultiConsumer< Tuple, Optional< NestedNextType >, offset >::TryConsumeTo().
GetChar()
template<size_t N> constexpr char Acore::Impl::ChatCommands::GetChar (char const (&) s[N], size_t i) inline constexpr
Definition at line 56 of file ChatCommandTags.h.
     {
         static_assert(N <= 25, "The EXACT_SEQUENCE macro can only be used with up to 25 character long literals. Specify them char-by-char (null terminated) as parameters to ExactSequence<> instead.");
         return i >= N ? '\0' : s[i];
     }
SendErrorMessageToHandler()
void Acore::Impl::ChatCommands::SendErrorMessageToHandler (ChatHandler * handler, std::string_view str)
Definition at line 22 of file ChatCommandHelpers.cpp.
 {
     handler->SendSysMessage(str);
     handler->SetSentErrorMessage(true);
 }
References ChatHandler::SendSysMessage(), and ChatHandler::SetSentErrorMessage().
Referenced by Acore::Impl::ChatCommands::CommandInvoker::CommandInvoker().
tokenize()
TokenizeResult Acore::Impl::ChatCommands::tokenize (std::string_view args) inline
Definition at line 55 of file ChatCommandHelpers.h.
     {
         TokenizeResult result;
         if (size_t delimPos = args.find(COMMAND_DELIMITER); delimPos != std::string_view::npos)
         {
             result.token = args.substr(0, delimPos);
             if (size_t tailPos = args.find_first_not_of(COMMAND_DELIMITER, delimPos); tailPos != std::string_view::npos)
                 result.tail = args.substr(tailPos);
         }
         else
             result.token = args;
         return result;
     }
References COMMAND_DELIMITER, Acore::Impl::ChatCommands::TokenizeResult::tail, and Acore::Impl::ChatCommands::TokenizeResult::token.
Referenced by Acore::Impl::ChatCommands::ChatCommandNode::GetAutoCompletionsFor(), Acore::ChatCommands::QuotedString::TryConsume(), Acore::ChatCommands::Hyperlink< linktag >::TryConsume(), Acore::ChatCommands::ExactSequence< chars >::TryConsume(), Acore::Impl::ChatCommands::ArgInfo< std::string_view, void >::TryConsume(), Acore::Impl::ChatCommands::ArgInfo< T, std::enable_if_t< std::is_integral_v< T >||std::is_floating_point_v< T > > >::TryConsume(), and Acore::Impl::ChatCommands::ChatCommandNode::TryExecuteCommand().
Variable Documentation
COMMAND_DELIMITER
constexpr char Acore::Impl::ChatCommands::COMMAND_DELIMITER = ' ' static constexpr
Definition at line 38 of file ChatCommandHelpers.h.
Referenced by Acore::Impl::ChatCommands::ChatCommandNode::GetAutoCompletionsFor(), Acore::Impl::ChatCommands::ChatCommandNode::LoadCommandMap(), Acore::Impl::ChatCommands::ChatCommandNode::LoadCommandsIntoMap(), ChatHandler::ParseCommands(), Acore::Impl::ChatCommands::ChatCommandNode::ResolveNames(), Acore::Impl::ChatCommands::ChatCommandNode::SendCommandHelpFor(), tokenize(), and Acore::Impl::ChatCommands::ChatCommandNode::TryExecuteCommand().