Azerotcore-wotlk: deps/mysqllite/include/internal/sha1.h File Reference
sha1.h File Reference
Classes
struct SHA1_CONTEXT
Macros
#define SHA1_HASH_SIZE 20 /* Hash size in bytes */
Typedefs
typedef struct SHA1_CONTEXT SHA1_CONTEXT
Enumerations
enum sha_result_codes { SHA_SUCCESS = 0 , SHA_NULL , SHA_INPUT_TOO_LONG , SHA_STATE_ERROR }
Functions
C_MODE_START int mysql_sha1_reset (SHA1_CONTEXT *)
int mysql_sha1_input (SHA1_CONTEXT *, const uint8 *, unsigned int)
int mysql_sha1_result (SHA1_CONTEXT *, uint8 Message_Digest[SHA1_HASH_SIZE])
Macro Definition Documentation
SHA1_HASH_SIZE
#define SHA1_HASH_SIZE 20 /* Hash size in bytes */
Definition at line 75 of file sha1.h.
Typedef Documentation
SHA1_CONTEXT
typedef struct SHA1_CONTEXT SHA1_CONTEXT
Enumeration Type Documentation
sha_result_codes
enum sha_result_codes
Enumerator
SHA_SUCCESS
SHA_NULL
SHA_INPUT_TOO_LONG
SHA_STATE_ERROR
Definition at line 67 of file sha1.h.
 {
   SHA_SUCCESS = 0,
   SHA_NULL,     /* Null pointer parameter */
   SHA_INPUT_TOO_LONG,   /* input data too long */
   SHA_STATE_ERROR   /* called Input after Result */
 };
Function Documentation
mysql_sha1_input()
int mysql_sha1_input (SHA1_CONTEXT * , const uint8 * , unsigned int)
Referenced by check_scramble(), my_make_scrambled_password(), and scramble().
mysql_sha1_reset()
C_MODE_START int mysql_sha1_reset (SHA1_CONTEXT * context)
Definition at line 125 of file sha1.c.
 {
 #ifndef DBUG_OFF
   if (!context)
     return SHA_NULL;
 #endif
   context->Length         = 0;
   context->Message_Block_Index    = 0;
   context->Intermediate_Hash[0]   = sha_const_key[0];
   context->Intermediate_Hash[1]   = sha_const_key[1];
   context->Intermediate_Hash[2]   = sha_const_key[2];
   context->Intermediate_Hash[3]   = sha_const_key[3];
   context->Intermediate_Hash[4]   = sha_const_key[4];
   context->Computed   = 0;
   context->Corrupted  = 0;
   return SHA_SUCCESS;
 }
References SHA1_CONTEXT::Computed, SHA1_CONTEXT::Corrupted, SHA1_CONTEXT::Intermediate_Hash, SHA1_CONTEXT::Length, SHA1_CONTEXT::Message_Block_Index, sha_const_key, SHA_NULL, and SHA_SUCCESS.
Referenced by check_scramble(), my_make_scrambled_password(), and scramble().
mysql_sha1_result()
int mysql_sha1_result (SHA1_CONTEXT * context, uint8 Message_Digest[SHA1_HASH_SIZE])
Definition at line 165 of file sha1.c.
 {
   int i;
 #ifndef DBUG_OFF
   if (!context || !Message_Digest)
     return SHA_NULL;
   if (context->Corrupted)
     return context->Corrupted;
 #endif
   if (!context->Computed)
   {
     SHA1PadMessage(context);
      /* message may be sensitive, clear it out */
     bzero((char*) context->Message_Block,64);
     context->Length   = 0;    /* and clear length  */
     context->Computed = 1;
   }
   for (i = 0; i < SHA1_HASH_SIZE; i++)
     Message_Digest[i] = (int8)((context->Intermediate_Hash[i>>2] >> 8
              * ( 3 - ( i & 0x03 ) )));
   return SHA_SUCCESS;
 }
References bzero, SHA1_CONTEXT::Computed, SHA1_CONTEXT::Corrupted, SHA1_CONTEXT::Intermediate_Hash, SHA1_CONTEXT::Length, SHA1_CONTEXT::Message_Block, SHA1_HASH_SIZE, SHA1PadMessage(), SHA_NULL, and SHA_SUCCESS.
Referenced by check_scramble(), my_make_scrambled_password(), and scramble().