Azerotcore-wotlk: deps/zlib/trees.c File Reference
trees.c File Reference
#include "deflate.h"
Classes
struct static_tree_desc_s
Macros
#define MAX_BL_BITS 7
#define END_BLOCK 256
#define REP_3_6 16
#define REPZ_3_10 17
#define REPZ_11_138 18
#define DIST_CODE_LEN 512 /* see definition of array dist_code below */
#define send_code(s, c, tree) send_bits(s, tree[c].Code, tree[c].Len)
#define put_short(s, w)
#define send_bits(s, value, length)
#define SMALLEST 1
#define pqremove(s, tree, top)
#define smaller(tree, n, m, depth)
Functions
void tr_static_init OF ((void))
void init_block OF ((deflate_state *s))
void pqdownheap OF ((deflate_state *s, ct_data *tree, int k))
void gen_bitlen OF ((deflate_state *s, tree_desc *desc))
void gen_codes OF ((ct_data *tree, int max_code, ushf *bl_count))
void scan_tree OF ((deflate_state *s, ct_data *tree, int max_code))
void send_all_trees OF ((deflate_state *s, int lcodes, int dcodes, int blcodes))
void compress_block OF ((deflate_state *s, ct_data *ltree, ct_data *dtree))
unsigned bi_reverse OF ((unsigned value, int length))
void copy_block OF ((deflate_state *s, charf *buf, unsigned len, int header))
void tr_static_init ()
void ZLIB_INTERNAL _tr_init (deflate_state *s)
void init_block (deflate_state *s)
void pqdownheap (deflate_state *s, ct_data *tree, int k)
void gen_bitlen (deflate_state *s, tree_desc *desc)
void gen_codes (ct_data *tree, int max_code, ushf *bl_count)
void build_tree (deflate_state *s, tree_desc *desc)
void scan_tree (deflate_state *s, ct_data *tree, int max_code)
void send_tree (deflate_state *s, ct_data *tree, int max_code)
int build_bl_tree (deflate_state *s)
void send_all_trees (deflate_state *s, int lcodes, int dcodes, int blcodes)
void ZLIB_INTERNAL _tr_stored_block (deflate_state *s, charf *buf, ulg stored_len, int last)
void ZLIB_INTERNAL _tr_flush_bits (deflate_state *s)
void ZLIB_INTERNAL _tr_align (deflate_state *s)
void ZLIB_INTERNAL _tr_flush_block (deflate_state *s, charf *buf, ulg stored_len, int last)
int ZLIB_INTERNAL _tr_tally (deflate_state *s, unsigned dist, unsigned lc)
void compress_block (deflate_state *s, ct_data *ltree, ct_data *dtree)
int detect_data_type (deflate_state *s)
unsigned bi_reverse (unsigned code, int len)
void bi_flush (deflate_state *s)
void bi_windup (deflate_state *s)
void copy_block (deflate_state *s, charf *buf, unsigned len, int header)
Variables
const int extra_lbits [LENGTH_CODES] = {0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,0}
const int extra_dbits [D_CODES] = {0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13}
const int extra_blbits [BL_CODES] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,3,7}
const uch bl_order [BL_CODES] = {16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15}
ct_data static_ltree [L_CODES+2]
ct_data static_dtree [D_CODES]
uch _dist_code [DIST_CODE_LEN]
uch _length_code [MAX_MATCH-MIN_MATCH+1]
int base_length [LENGTH_CODES]
int base_dist [D_CODES]
static_tree_desc static_l_desc
static_tree_desc static_d_desc
static_tree_desc static_bl_desc
Macro Definition Documentation
DIST_CODE_LEN
#define DIST_CODE_LEN 512 /* see definition of array dist_code below */
Definition at line 81 of file trees.c.
END_BLOCK
#define END_BLOCK 256
Definition at line 50 of file trees.c.
MAX_BL_BITS
#define MAX_BL_BITS 7
Definition at line 47 of file trees.c.
pqremove
#define pqremove (s, tree, top)
Value:
{\
    top = s->heap[SMALLEST]; \
    s->heap[SMALLEST] = s->heap[s->heap_len--]; \
    pqdownheap(s, tree, SMALLEST); \
}
Definition at line 432 of file trees.c.
put_short
#define put_short (s, w)
Value:
    { \
    put_byte(s, (uch)((w) & 0xff)); \
    put_byte(s, (uch)((ush)(w) >> 8)); \
}
Definition at line 176 of file trees.c.
REP_3_6
#define REP_3_6 16
Definition at line 53 of file trees.c.
REPZ_11_138
#define REPZ_11_138 18
Definition at line 59 of file trees.c.
REPZ_3_10
#define REPZ_3_10 17
Definition at line 56 of file trees.c.
send_bits
#define send_bits (s, value, length)
Value:
{ int len = length;\
  if (s->bi_valid > (int)Buf_size - len) {\
    int val = value;\
    s->bi_buf |= (ush)val << s->bi_valid;\
    put_short(s, s->bi_buf);\
    s->bi_buf = (ush)val >> (Buf_size - s->bi_valid);\
    s->bi_valid += len - Buf_size;\
  } else {\
    s->bi_buf |= (ush)(value) << s->bi_valid;\
    s->bi_valid += len;\
  }\
}
Definition at line 213 of file trees.c.
send_code
#define send_code (s, c, tree) send_bits(s, tree[c].Code, tree[c].Len)
Definition at line 163 of file trees.c.
smaller
#define smaller (tree, n, m, depth)
Value:
   (tree[n].Freq < tree[m].Freq || \
   (tree[n].Freq == tree[m].Freq && depth[n] <= depth[m]))
Definition at line 443 of file trees.c.
SMALLEST
#define SMALLEST 1
Definition at line 424 of file trees.c.
Function Documentation
_tr_align()
void ZLIB_INTERNAL _tr_align (deflate_state * s)
Definition at line 892 of file trees.c.
 {
     send_bits(s, STATIC_TREES<<1, 3);
     send_code(s, END_BLOCK, static_ltree);
 #ifdef DEBUG
     s->compressed_len += 10L; /* 3 for block type, 7 for EOB */
 #endif
     bi_flush(s);
 }
References bi_flush(), END_BLOCK, send_bits, send_code, static_ltree, and STATIC_TREES.
Referenced by deflate().
_tr_flush_bits()
void ZLIB_INTERNAL _tr_flush_bits (deflate_state * s)
Definition at line 882 of file trees.c.
 {
     bi_flush(s);
 }
References bi_flush().
Referenced by deflatePrime(), and flush_pending().
_tr_flush_block()
void ZLIB_INTERNAL _tr_flush_block (deflate_state * s, charf * buf, ulg stored_len, int last)
Definition at line 907 of file trees.c.
 {
     ulg opt_lenb, static_lenb; /* opt_len and static_len in bytes */
     int max_blindex = 0;  /* index of last bit length code of non zero freq */
     /* Build the Huffman trees unless a stored block is forced */
     if (s->level > 0) {
         /* Check if the file is binary or text */
         if (s->strm->data_type == Z_UNKNOWN)
             s->strm->data_type = detect_data_type(s);
         /* Construct the literal and distance trees */
         build_tree(s, (tree_desc *)(&(s->l_desc)));
         Tracev((stderr, "\nlit data: dyn %ld, stat %ld", s->opt_len,
                 s->static_len));
         build_tree(s, (tree_desc *)(&(s->d_desc)));
         Tracev((stderr, "\ndist data: dyn %ld, stat %ld", s->opt_len,
                 s->static_len));
         /* At this point, opt_len and static_len are the total bit lengths of
          * the compressed block data, excluding the tree representations.
          */
         /* Build the bit length tree for the above two trees, and get the index
          * in bl_order of the last bit length code to send.
          */
         max_blindex = build_bl_tree(s);
         /* Determine the best encoding. Compute the block lengths in bytes. */
         opt_lenb = (s->opt_len+3+7)>>3;
         static_lenb = (s->static_len+3+7)>>3;
         Tracev((stderr, "\nopt %lu(%lu) stat %lu(%lu) stored %lu lit %u ",
                 opt_lenb, s->opt_len, static_lenb, s->static_len, stored_len,
                 s->last_lit));
         if (static_lenb <= opt_lenb) opt_lenb = static_lenb;
     } else {
         Assert(buf != (char*)0, "lost buf");
         opt_lenb = static_lenb = stored_len + 5; /* force a stored block */
     }
 #ifdef FORCE_STORED
     if (buf != (char*)0) { /* force stored block */
 #else
     if (stored_len+4 <= opt_lenb && buf != (char*)0) {
                        /* 4: two words for the lengths */
 #endif
         /* The test buf != NULL is only necessary if LIT_BUFSIZE > WSIZE.
          * Otherwise we can't have processed more than WSIZE input bytes since
          * the last block flush, because compression would have been
          * successful. If LIT_BUFSIZE <= WSIZE, it is never too late to
          * transform a block into a stored block.
          */
         _tr_stored_block(s, buf, stored_len, last);
 #ifdef FORCE_STATIC
     } else if (static_lenb >= 0) { /* force static trees */
 #else
     } else if (s->strategy == Z_FIXED || static_lenb == opt_lenb) {
 #endif
         send_bits(s, (STATIC_TREES<<1)+last, 3);
         compress_block(s, (ct_data *)static_ltree, (ct_data *)static_dtree);
 #ifdef DEBUG
         s->compressed_len += 3 + s->static_len;
 #endif
     } else {
         send_bits(s, (DYN_TREES<<1)+last, 3);
         send_all_trees(s, s->l_desc.max_code+1, s->d_desc.max_code+1,
                        max_blindex+1);
         compress_block(s, (ct_data *)s->dyn_ltree, (ct_data *)s->dyn_dtree);
 #ifdef DEBUG
         s->compressed_len += 3 + s->opt_len;
 #endif
     }
     Assert (s->compressed_len == s->bits_sent, "bad compressed size");
     /* The above check is made mod 2^32, for files larger than 512 MB
      * and uLong implemented on 32 bits.
      */
     init_block(s);
     if (last) {
         bi_windup(s);
 #ifdef DEBUG
         s->compressed_len += 7;  /* align on byte boundary */
 #endif
     }
     Tracev((stderr,"\ncomprlen %lu(%lu) ", s->compressed_len>>3,
            s->compressed_len-7*last));
 }
References _tr_stored_block(), Assert, bi_windup(), build_bl_tree(), build_tree(), compress_block(), detect_data_type(), DYN_TREES, init_block(), send_all_trees(), send_bits, static_dtree, static_ltree, STATIC_TREES, internal_state::strm, Tracev, Z_FIXED, and Z_UNKNOWN.
_tr_init()
void ZLIB_INTERNAL _tr_init (deflate_state * s)
Definition at line 381 of file trees.c.
 {
     tr_static_init();
     s->l_desc.dyn_tree = s->dyn_ltree;
     s->l_desc.stat_desc = &static_l_desc;
     s->d_desc.dyn_tree = s->dyn_dtree;
     s->d_desc.stat_desc = &static_d_desc;
     s->bl_desc.dyn_tree = s->bl_tree;
     s->bl_desc.stat_desc = &static_bl_desc;
     s->bi_buf = 0;
     s->bi_valid = 0;
 #ifdef DEBUG
     s->compressed_len = 0L;
     s->bits_sent = 0L;
 #endif
     /* Initialize the first block of the first file: */
     init_block(s);
 }
References init_block(), static_bl_desc, static_d_desc, static_l_desc, and tr_static_init().
Referenced by deflateResetKeep().
_tr_stored_block()
void ZLIB_INTERNAL _tr_stored_block (deflate_state * s, charf * buf, ulg stored_len, int last)
Definition at line 865 of file trees.c.
 {
     send_bits(s, (STORED_BLOCK<<1)+last, 3);    /* send block type */
 #ifdef DEBUG
     s->compressed_len = (s->compressed_len + 3 + 7) & (ulg)~7L;
     s->compressed_len += (stored_len + 4) << 3;
 #endif
     copy_block(s, buf, (unsigned)stored_len, 1); /* with header */
 }
References copy_block(), send_bits, and STORED_BLOCK.
Referenced by _tr_flush_block(), and deflate().
_tr_tally()
int ZLIB_INTERNAL _tr_tally (deflate_state * s, unsigned dist, unsigned lc)
Definition at line 1008 of file trees.c.
 {
     s->d_buf[s->last_lit] = (ush)dist;
     s->l_buf[s->last_lit++] = (uch)lc;
     if (dist == 0) {
         /* lc is the unmatched char */
         s->dyn_ltree[lc].Freq++;
     } else {
         s->matches++;
         /* Here, lc is the match length - MIN_MATCH */
         dist--;             /* dist = match distance - 1 */
         Assert((ush)dist < (ush)MAX_DIST(s) &&
                (ush)lc <= (ush)(MAX_MATCH-MIN_MATCH) &&
                (ush)d_code(dist) < (ush)D_CODES,  "_tr_tally: bad match");
         s->dyn_ltree[_length_code[lc]+LITERALS+1].Freq++;
         s->dyn_dtree[d_code(dist)].Freq++;
     }
 #ifdef TRUNCATE_BLOCK
     /* Try to guess if it is profitable to stop the current block here */
     if ((s->last_lit & 0x1fff) == 0 && s->level > 2) {
         /* Compute an upper bound for the compressed length */
         ulg out_length = (ulg)s->last_lit*8L;
         ulg in_length = (ulg)((long)s->strstart - s->block_start);
         int dcode;
         for (dcode = 0; dcode < D_CODES; dcode++) {
             out_length += (ulg)s->dyn_dtree[dcode].Freq *
                 (5L+extra_dbits[dcode]);
         }
         out_length >>= 3;
         Tracev((stderr,"\nlast_lit %u, in %ld, out ~%ld(%ld%%) ",
                s->last_lit, in_length, out_length,
                100L - out_length*100L/in_length));
         if (s->matches < s->last_lit/2 && out_length < in_length/2) return 1;
     }
 #endif
     return (s->last_lit == s->lit_bufsize-1);
     /* We avoid equality with lit_bufsize because of wraparound at 64K
      * on 16 bit machines and because stored blocks are restricted to
      * 64K-1 bytes.
      */
 }
References _length_code, Assert, internal_state::d_buf, d_code, D_CODES, extra_dbits, LITERALS, MAX_DIST, MAX_MATCH, MIN_MATCH, and Tracev.
bi_flush()
void bi_flush (deflate_state * s)
Definition at line 1167 of file trees.c.
 {
     if (s->bi_valid == 16) {
         put_short(s, s->bi_buf);
         s->bi_buf = 0;
         s->bi_valid = 0;
     } else if (s->bi_valid >= 8) {
         put_byte(s, (Byte)s->bi_buf);
         s->bi_buf >>= 8;
         s->bi_valid -= 8;
     }
 }
References put_byte, and put_short.
Referenced by _tr_align(), and _tr_flush_bits().
bi_reverse()
unsigned bi_reverse (unsigned code, int len)
Definition at line 1152 of file trees.c.
 {
     register unsigned res = 0;
     do {
         res |= code & 1;
         code >>= 1, res <<= 1;
     } while (--len > 0);
     return res >> 1;
 }
Referenced by gen_codes(), and tr_static_init().
bi_windup()
void bi_windup (deflate_state * s)
Definition at line 1184 of file trees.c.
 {
     if (s->bi_valid > 8) {
         put_short(s, s->bi_buf);
     } else if (s->bi_valid > 0) {
         put_byte(s, (Byte)s->bi_buf);
     }
     s->bi_buf = 0;
     s->bi_valid = 0;
 #ifdef DEBUG
     s->bits_sent = (s->bits_sent+7) & ~7;
 #endif
 }
References put_byte, and put_short.
Referenced by _tr_flush_block(), and copy_block().
build_bl_tree()
int build_bl_tree (deflate_state * s)
Definition at line 801 of file trees.c.
 {
     int max_blindex;  /* index of last bit length code of non zero freq */
     /* Determine the bit length frequencies for literal and distance trees */
     scan_tree(s, (ct_data *)s->dyn_ltree, s->l_desc.max_code);
     scan_tree(s, (ct_data *)s->dyn_dtree, s->d_desc.max_code);
     /* Build the bit length tree: */
     build_tree(s, (tree_desc *)(&(s->bl_desc)));
     /* opt_len now includes the length of the tree representations, except
      * the lengths of the bit lengths codes and the 5+5+4 bits for the counts.
      */
     /* Determine the number of bit length codes to send. The pkzip format
      * requires that at least 4 bit length codes be sent. (appnote.txt says
      * 3 but the actual value used is 4.)
      */
     for (max_blindex = BL_CODES-1; max_blindex >= 3; max_blindex--) {
         if (s->bl_tree[bl_order[max_blindex]].Len != 0) break;
     }
     /* Update opt_len to include the bit length tree and counts */
     s->opt_len += 3*(max_blindex+1) + 5+5+4;
     Tracev((stderr, "\ndyn trees: dyn %ld, stat %ld",
             s->opt_len, s->static_len));
     return max_blindex;
 }
References BL_CODES, bl_order, build_tree(), scan_tree(), and Tracev.
Referenced by _tr_flush_block().
build_tree()
void build_tree (deflate_state * s, tree_desc * desc)
Definition at line 617 of file trees.c.
 {
     ct_data *tree         = desc->dyn_tree;
     const ct_data *stree  = desc->stat_desc->static_tree;
     int elems             = desc->stat_desc->elems;
     int n, m;          /* iterate over heap elements */
     int max_code = -1; /* largest code with non zero frequency */
     int node;          /* new node being created */
     /* Construct the initial heap, with least frequent element in
      * heap[SMALLEST]. The sons of heap[n] are heap[2*n] and heap[2*n+1].
      * heap[0] is not used.
      */
     s->heap_len = 0, s->heap_max = HEAP_SIZE;
     for (n = 0; n < elems; n++) {
         if (tree[n].Freq != 0) {
             s->heap[++(s->heap_len)] = max_code = n;
             s->depth[n] = 0;
         } else {
             tree[n].Len = 0;
         }
     }
     /* The pkzip format requires that at least one distance code exists,
      * and that at least one bit should be sent even if there is only one
      * possible code. So to avoid special checks later on we force at least
      * two codes of non zero frequency.
      */
     while (s->heap_len < 2) {
         node = s->heap[++(s->heap_len)] = (max_code < 2 ? ++max_code : 0);
         tree[node].Freq = 1;
         s->depth[node] = 0;
         s->opt_len--; if (stree) s->static_len -= stree[node].Len;
         /* node is 0 or 1 so it does not have extra bits */
     }
     desc->max_code = max_code;
     /* The elements heap[heap_len/2+1 .. heap_len] are leaves of the tree,
      * establish sub-heaps of increasing lengths:
      */
     for (n = s->heap_len/2; n >= 1; n--) pqdownheap(s, tree, n);
     /* Construct the Huffman tree by repeatedly combining the least two
      * frequent nodes.
      */
     node = elems;              /* next internal node of the tree */
     do {
         pqremove(s, tree, n);  /* n = node of least frequency */
         m = s->heap[SMALLEST]; /* m = node of next least frequency */
         s->heap[--(s->heap_max)] = n; /* keep the nodes sorted by frequency */
         s->heap[--(s->heap_max)] = m;
         /* Create a new node father of n and m */
         tree[node].Freq = tree[n].Freq + tree[m].Freq;
         s->depth[node] = (uch)((s->depth[n] >= s->depth[m] ?
                                 s->depth[n] : s->depth[m]) + 1);
         tree[n].Dad = tree[m].Dad = (ush)node;
 #ifdef DUMP_BL_TREE
         if (tree == s->bl_tree) {
             fprintf(stderr,"\nnode %d(%d), sons %d(%d) %d(%d)",
                     node, tree[node].Freq, n, tree[n].Freq, m, tree[m].Freq);
         }
 #endif
         /* and insert the new node in the heap */
         s->heap[SMALLEST] = node++;
         pqdownheap(s, tree, SMALLEST);
     } while (s->heap_len >= 2);
     s->heap[--(s->heap_max)] = s->heap[SMALLEST];
     /* At this point, the fields freq and dad are set. We can now
      * generate the bit lengths.
      */
     gen_bitlen(s, (tree_desc *)desc);
     /* The field len is now set, we can generate the bit codes */
     gen_codes ((ct_data *)tree, max_code, s->bl_count);
 }
References tree_desc_s::dyn_tree, static_tree_desc_s::elems, fprintf(), Freq, gen_bitlen(), gen_codes(), HEAP_SIZE, tree_desc_s::max_code, pqdownheap(), pqremove, SMALLEST, tree_desc_s::stat_desc, and static_tree_desc_s::static_tree.
Referenced by _tr_flush_block(), and build_bl_tree().
compress_block()
void compress_block (deflate_state * s, ct_data * ltree, ct_data * dtree)
Definition at line 1058 of file trees.c.
 {
     unsigned dist;      /* distance of matched string */
     int lc;             /* match length or unmatched char (if dist == 0) */
     unsigned lx = 0;    /* running index in l_buf */
     unsigned code;      /* the code to send */
     int extra;          /* number of extra bits to send */
     if (s->last_lit != 0) do {
         dist = s->d_buf[lx];
         lc = s->l_buf[lx++];
         if (dist == 0) {
             send_code(s, lc, ltree); /* send a literal byte */
             Tracecv(isgraph(lc), (stderr," '%c' ", lc));
         } else {
             /* Here, lc is the match length - MIN_MATCH */
             code = _length_code[lc];
             send_code(s, code+LITERALS+1, ltree); /* send the length code */
             extra = extra_lbits[code];
             if (extra != 0) {
                 lc -= base_length[code];
                 send_bits(s, lc, extra);       /* send the extra length bits */
             }
             dist--; /* dist is now the match distance - 1 */
             code = d_code(dist);
             Assert (code < D_CODES, "bad d_code");
             send_code(s, code, dtree);       /* send the distance code */
             extra = extra_dbits[code];
             if (extra != 0) {
                 dist -= base_dist[code];
                 send_bits(s, dist, extra);   /* send the extra distance bits */
             }
         } /* literal or match pair ? */
         /* Check that the overlay between pending_buf and d_buf+l_buf is ok: */
         Assert((uInt)(s->pending) < s->lit_bufsize + 2*lx,
                "pendingBuf overflow");
     } while (lx < s->last_lit);
     send_code(s, END_BLOCK, ltree);
 }
References _length_code, Assert, base_dist, base_length, d_code, D_CODES, END_BLOCK, extra_dbits, extra_lbits, LITERALS, send_bits, send_code, and Tracecv.
Referenced by _tr_flush_block().
copy_block()
void copy_block (deflate_state * s, charf * buf, unsigned len, int header)
Definition at line 1203 of file trees.c.
 {
     bi_windup(s);        /* align on byte boundary */
     if (header) {
         put_short(s, (ush)len);
         put_short(s, (ush)~len);
 #ifdef DEBUG
         s->bits_sent += 2*16;
 #endif
     }
 #ifdef DEBUG
     s->bits_sent += (ulg)len<<3;
 #endif
     while (len--) {
         put_byte(s, *buf++);
     }
 }
References bi_windup(), put_byte, and put_short.
Referenced by _tr_stored_block().
detect_data_type()
int detect_data_type (deflate_state * s)
Definition at line 1118 of file trees.c.
 {
     /* black_mask is the bit mask of black-listed bytes
      * set bits 0..6, 14..25, and 28..31
      * 0xf3ffc07f = binary 11110011111111111100000001111111
      */
     unsigned long black_mask = 0xf3ffc07fUL;
     int n;
     /* Check for non-textual ("black-listed") bytes. */
     for (n = 0; n <= 31; n++, black_mask >>= 1)
         if ((black_mask & 1) && (s->dyn_ltree[n].Freq != 0))
             return Z_BINARY;
     /* Check for textual ("white-listed") bytes. */
     if (s->dyn_ltree[9].Freq != 0 || s->dyn_ltree[10].Freq != 0
             || s->dyn_ltree[13].Freq != 0)
         return Z_TEXT;
     for (n = 32; n < LITERALS; n++)
         if (s->dyn_ltree[n].Freq != 0)
             return Z_TEXT;
     /* There are no "black-listed" or "white-listed" bytes:
      * this stream either is empty or has tolerated ("gray-listed") bytes only.
      */
     return Z_BINARY;
 }
References LITERALS, Z_BINARY, and Z_TEXT.
Referenced by _tr_flush_block().
gen_bitlen()
void gen_bitlen (deflate_state * s, tree_desc * desc)
Definition at line 488 of file trees.c.
 {
     ct_data *tree        = desc->dyn_tree;
     int max_code         = desc->max_code;
     const ct_data *stree = desc->stat_desc->static_tree;
     const intf *extra    = desc->stat_desc->extra_bits;
     int base             = desc->stat_desc->extra_base;
     int max_length       = desc->stat_desc->max_length;
     int h;              /* heap index */
     int n, m;           /* iterate over the tree elements */
     int bits;           /* bit length */
     int xbits;          /* extra bits */
     ush f;              /* frequency */
     int overflow = 0;   /* number of elements with bit length too large */
     for (bits = 0; bits <= MAX_BITS; bits++) s->bl_count[bits] = 0;
     /* In a first pass, compute the optimal bit lengths (which may
      * overflow in the case of the bit length tree).
      */
     tree[s->heap[s->heap_max]].Len = 0; /* root of the heap */
     for (h = s->heap_max+1; h < HEAP_SIZE; h++) {
         n = s->heap[h];
         bits = tree[tree[n].Dad].Len + 1;
         if (bits > max_length) bits = max_length, overflow++;
         tree[n].Len = (ush)bits;
         /* We overwrite tree[n].Dad which is no longer needed */
         if (n > max_code) continue; /* not a leaf node */
         s->bl_count[bits]++;
         xbits = 0;
         if (n >= base) xbits = extra[n-base];
         f = tree[n].Freq;
         s->opt_len += (ulg)f * (bits + xbits);
         if (stree) s->static_len += (ulg)f * (stree[n].Len + xbits);
     }
     if (overflow == 0) return;
     Trace((stderr,"\nbit length overflow\n"));
     /* This happens for example on obj2 and pic of the Calgary corpus */
     /* Find the first bit length which could increase: */
     do {
         bits = max_length-1;
         while (s->bl_count[bits] == 0) bits--;
         s->bl_count[bits]--;      /* move one leaf down the tree */
         s->bl_count[bits+1] += 2; /* move one overflow item as its brother */
         s->bl_count[max_length]--;
         /* The brother of the overflow item also moves one step up,
          * but this does not affect bl_count[max_length]
          */
         overflow -= 2;
     } while (overflow > 0);
     /* Now recompute all bit lengths, scanning in increasing frequency.
      * h is still equal to HEAP_SIZE. (It is simpler to reconstruct all
      * lengths instead of fixing only the wrong ones. This idea is taken
      * from 'ar' written by Haruhiko Okumura.)
      */
     for (bits = max_length; bits != 0; bits--) {
         n = s->bl_count[bits];
         while (n != 0) {
             m = s->heap[--h];
             if (m > max_code) continue;
             if ((unsigned) tree[m].Len != (unsigned) bits) {
                 Trace((stderr,"code %d bits %d->%d\n", m, tree[m].Len, bits));
                 s->opt_len += ((long)bits - (long)tree[m].Len)
                               *(long)tree[m].Freq;
                 tree[m].Len = (ush)bits;
             }
             n--;
         }
     }
 }
References G3D::bits(), tree_desc_s::dyn_tree, static_tree_desc_s::extra_base, static_tree_desc_s::extra_bits, f(), HEAP_SIZE, Len, MAX_BITS, tree_desc_s::max_code, static_tree_desc_s::max_length, tree_desc_s::stat_desc, static_tree_desc_s::static_tree, and Trace.
Referenced by build_tree().
gen_codes()
void gen_codes (ct_data * tree, int max_code, ushf * bl_count)
Definition at line 575 of file trees.c.
 {
     ush next_code[MAX_BITS+1]; /* next code value for each bit length */
     ush code = 0;              /* running code value */
     int bits;                  /* bit index */
     int n;                     /* code index */
     /* The distribution counts are first used to generate the code values
      * without bit reversal.
      */
     for (bits = 1; bits <= MAX_BITS; bits++) {
         next_code[bits] = code = (code + bl_count[bits-1]) << 1;
     }
     /* Check that the bit counts in bl_count are consistent. The last code
      * must be all ones.
      */
     Assert (code + bl_count[MAX_BITS]-1 == (1<<MAX_BITS)-1,
             "inconsistent bit counts");
     Tracev((stderr,"\ngen_codes: max_code %d ", max_code));
     for (n = 0;  n <= max_code; n++) {
         int len = tree[n].Len;
         if (len == 0) continue;
         /* Now reverse the bits */
         tree[n].Code = bi_reverse(next_code[len]++, len);
         Tracecv(tree != static_ltree, (stderr,"\nn %3d %c l %2d c %4x (%x) ",
              n, (isgraph(n) ? n : ' '), len, tree[n].Code, next_code[len]-1));
     }
 }
References Assert, bi_reverse(), G3D::bits(), Code, MAX_BITS, static_ltree, Tracecv, and Tracev.
Referenced by build_tree(), and tr_static_init().
init_block()
void init_block (deflate_state * s)
Definition at line 409 of file trees.c.
 {
     int n; /* iterates over tree elements */
     /* Initialize the trees. */
     for (n = 0; n < L_CODES;  n++) s->dyn_ltree[n].Freq = 0;
     for (n = 0; n < D_CODES;  n++) s->dyn_dtree[n].Freq = 0;
     for (n = 0; n < BL_CODES; n++) s->bl_tree[n].Freq = 0;
     s->dyn_ltree[END_BLOCK].Freq = 1;
     s->opt_len = s->static_len = 0L;
     s->last_lit = s->matches = 0;
 }
References BL_CODES, D_CODES, internal_state::dyn_ltree, END_BLOCK, and L_CODES.
Referenced by _tr_flush_block(), and _tr_init().
OF() [1/10]
void gen_codes OF ((ct_data *tree, int max_code, ushf *bl_count))
OF() [2/10]
void init_block OF ((deflate_state *s))
OF() [3/10]
void copy_block OF ((deflate_state *s, charf *buf, unsigned len, int header))
OF() [4/10]
void compress_block OF ((deflate_state *s, ct_data *ltree, ct_data *dtree))
OF() [5/10]
void pqdownheap OF ((deflate_state *s, ct_data *tree, int k))
OF() [6/10]
void scan_tree OF ((deflate_state *s, ct_data *tree, int max_code))
OF() [7/10]
void send_all_trees OF ((deflate_state *s, int lcodes, int dcodes, int blcodes))
OF() [8/10]
void gen_bitlen OF ((deflate_state *s, tree_desc *desc))
OF() [9/10]
unsigned bi_reverse OF ((unsigned value, int length))
OF() [10/10]
void tr_static_init OF ((void))
pqdownheap()
void pqdownheap (deflate_state * s, ct_data * tree, int k)
Definition at line 453 of file trees.c.
 {
     int v = s->heap[k];
     int j = k << 1;  /* left son of k */
     while (j <= s->heap_len) {
         /* Set j to the smallest of the two sons: */
         if (j < s->heap_len &&
             smaller(tree, s->heap[j+1], s->heap[j], s->depth)) {
             j++;
         }
         /* Exit if v is smaller than both sons */
         if (smaller(tree, v, s->heap[j], s->depth)) break;
         /* Exchange v with the smallest son */
         s->heap[k] = s->heap[j];  k = j;
         /* And continue down the tree, setting j to the left son of k */
         j <<= 1;
     }
     s->heap[k] = v;
 }
References smaller.
Referenced by build_tree().
scan_tree()
void scan_tree (deflate_state * s, ct_data * tree, int max_code)
Definition at line 705 of file trees.c.
 {
     int n;                     /* iterates over all tree elements */
     int prevlen = -1;          /* last emitted length */
     int curlen;                /* length of current code */
     int nextlen = tree[0].Len; /* length of next code */
     int count = 0;             /* repeat count of the current code */
     int max_count = 7;         /* max repeat count */
     int min_count = 4;         /* min repeat count */
     if (nextlen == 0) max_count = 138, min_count = 3;
     tree[max_code+1].Len = (ush)0xffff; /* guard */
     for (n = 0; n <= max_code; n++) {
         curlen = nextlen; nextlen = tree[n+1].Len;
         if (++count < max_count && curlen == nextlen) {
             continue;
         } else if (count < min_count) {
             s->bl_tree[curlen].Freq += count;
         } else if (curlen != 0) {
             if (curlen != prevlen) s->bl_tree[curlen].Freq++;
             s->bl_tree[REP_3_6].Freq++;
         } else if (count <= 10) {
             s->bl_tree[REPZ_3_10].Freq++;
         } else {
             s->bl_tree[REPZ_11_138].Freq++;
         }
         count = 0; prevlen = curlen;
         if (nextlen == 0) {
             max_count = 138, min_count = 3;
         } else if (curlen == nextlen) {
             max_count = 6, min_count = 3;
         } else {
             max_count = 7, min_count = 4;
         }
     }
 }
References count(), REP_3_6, REPZ_11_138, and REPZ_3_10.
Referenced by build_bl_tree().
send_all_trees()
void send_all_trees (deflate_state * s, int lcodes, int dcodes, int blcodes)
Definition at line 836 of file trees.c.
 {
     int rank;                    /* index in bl_order */
     Assert (lcodes >= 257 && dcodes >= 1 && blcodes >= 4, "not enough codes");
     Assert (lcodes <= L_CODES && dcodes <= D_CODES && blcodes <= BL_CODES,
             "too many codes");
     Tracev((stderr, "\nbl counts: "));
     send_bits(s, lcodes-257, 5); /* not +255 as stated in appnote.txt */
     send_bits(s, dcodes-1,   5);
     send_bits(s, blcodes-4,  4); /* not -3 as stated in appnote.txt */
     for (rank = 0; rank < blcodes; rank++) {
         Tracev((stderr, "\nbl code %2d ", bl_order[rank]));
         send_bits(s, s->bl_tree[bl_order[rank]].Len, 3);
     }
     Tracev((stderr, "\nbl tree: sent %ld", s->bits_sent));
     send_tree(s, (ct_data *)s->dyn_ltree, lcodes-1); /* literal tree */
     Tracev((stderr, "\nlit tree: sent %ld", s->bits_sent));
     send_tree(s, (ct_data *)s->dyn_dtree, dcodes-1); /* distance tree */
     Tracev((stderr, "\ndist tree: sent %ld", s->bits_sent));
 }
References Assert, BL_CODES, bl_order, D_CODES, L_CODES, send_bits, send_tree(), and Tracev.
Referenced by _tr_flush_block().
send_tree()
void send_tree (deflate_state * s, ct_data * tree, int max_code)
Definition at line 750 of file trees.c.
 {
     int n;                     /* iterates over all tree elements */
     int prevlen = -1;          /* last emitted length */
     int curlen;                /* length of current code */
     int nextlen = tree[0].Len; /* length of next code */
     int count = 0;             /* repeat count of the current code */
     int max_count = 7;         /* max repeat count */
     int min_count = 4;         /* min repeat count */
     /* tree[max_code+1].Len = -1; */  /* guard already set */
     if (nextlen == 0) max_count = 138, min_count = 3;
     for (n = 0; n <= max_code; n++) {
         curlen = nextlen; nextlen = tree[n+1].Len;
         if (++count < max_count && curlen == nextlen) {
             continue;
         } else if (count < min_count) {
             do { send_code(s, curlen, s->bl_tree); } while (--count != 0);
         } else if (curlen != 0) {
             if (curlen != prevlen) {
                 send_code(s, curlen, s->bl_tree); count--;
             }
             Assert(count >= 3 && count <= 6, " 3_6?");
             send_code(s, REP_3_6, s->bl_tree); send_bits(s, count-3, 2);
         } else if (count <= 10) {
             send_code(s, REPZ_3_10, s->bl_tree); send_bits(s, count-3, 3);
         } else {
             send_code(s, REPZ_11_138, s->bl_tree); send_bits(s, count-11, 7);
         }
         count = 0; prevlen = curlen;
         if (nextlen == 0) {
             max_count = 138, min_count = 3;
         } else if (curlen == nextlen) {
             max_count = 6, min_count = 3;
         } else {
             max_count = 7, min_count = 4;
         }
     }
 }
References Assert, count(), REP_3_6, REPZ_11_138, REPZ_3_10, send_bits, and send_code.
Referenced by send_all_trees().
tr_static_init()
void tr_static_init ()
Definition at line 234 of file trees.c.
 {
 #if defined(GEN_TREES_H) || !defined(STDC)
     static int static_init_done = 0;
     int n;        /* iterates over tree elements */
     int bits;     /* bit counter */
     int length;   /* length value */
     int code;     /* code value */
     int dist;     /* distance index */
     ush bl_count[MAX_BITS+1];
     /* number of codes at each bit length for an optimal tree */
     if (static_init_done) return;
     /* For some embedded targets, global variables are not initialized: */
 #ifdef NO_INIT_GLOBAL_POINTERS
     static_l_desc.static_tree = static_ltree;
     static_l_desc.extra_bits = extra_lbits;
     static_d_desc.static_tree = static_dtree;
     static_d_desc.extra_bits = extra_dbits;
     static_bl_desc.extra_bits = extra_blbits;
 #endif
     /* Initialize the mapping length (0..255) -> length code (0..28) */
     length = 0;
     for (code = 0; code < LENGTH_CODES-1; code++) {
         base_length[code] = length;
         for (n = 0; n < (1<<extra_lbits[code]); n++) {
             _length_code[length++] = (uch)code;
         }
     }
     Assert (length == 256, "tr_static_init: length != 256");
     /* Note that the length 255 (match length 258) can be represented
      * in two different ways: code 284 + 5 bits or code 285, so we
      * overwrite length_code[255] to use the best encoding:
      */
     _length_code[length-1] = (uch)code;
     /* Initialize the mapping dist (0..32K) -> dist code (0..29) */
     dist = 0;
     for (code = 0 ; code < 16; code++) {
         base_dist[code] = dist;
         for (n = 0; n < (1<<extra_dbits[code]); n++) {
             _dist_code[dist++] = (uch)code;
         }
     }
     Assert (dist == 256, "tr_static_init: dist != 256");
     dist >>= 7; /* from now on, all distances are divided by 128 */
     for ( ; code < D_CODES; code++) {
         base_dist[code] = dist << 7;
         for (n = 0; n < (1<<(extra_dbits[code]-7)); n++) {
             _dist_code[256 + dist++] = (uch)code;
         }
     }
     Assert (dist == 256, "tr_static_init: 256+dist != 512");
     /* Construct the codes of the static literal tree */
     for (bits = 0; bits <= MAX_BITS; bits++) bl_count[bits] = 0;
     n = 0;
     while (n <= 143) static_ltree[n++].Len = 8, bl_count[8]++;
     while (n <= 255) static_ltree[n++].Len = 9, bl_count[9]++;
     while (n <= 279) static_ltree[n++].Len = 7, bl_count[7]++;
     while (n <= 287) static_ltree[n++].Len = 8, bl_count[8]++;
     /* Codes 286 and 287 do not exist, but we must include them in the
      * tree construction to get a canonical Huffman tree (longest code
      * all ones)
      */
     gen_codes((ct_data *)static_ltree, L_CODES+1, bl_count);
     /* The static distance tree is trivial: */
     for (n = 0; n < D_CODES; n++) {
         static_dtree[n].Len = 5;
         static_dtree[n].Code = bi_reverse((unsigned)n, 5);
     }
     static_init_done = 1;
 #  ifdef GEN_TREES_H
     gen_trees_header();
 #  endif
 #endif /* defined(GEN_TREES_H) || !defined(STDC) */
 }
References _dist_code, _length_code, Assert, base_dist, base_length, bi_reverse(), G3D::bits(), D_CODES, static_tree_desc_s::extra_bits, extra_blbits, extra_dbits, extra_lbits, gen_codes(), L_CODES, G3D::length(), LENGTH_CODES, MAX_BITS, static_bl_desc, static_d_desc, static_dtree, static_l_desc, static_ltree, and static_tree_desc_s::static_tree.
Referenced by _tr_init().
Variable Documentation
_dist_code
uch _dist_code[DIST_CODE_LEN]
Definition at line 98 of file trees.c.
Referenced by tr_static_init().
_length_code
uch _length_code[MAX_MATCH-MIN_MATCH+1]
Definition at line 104 of file trees.c.
Referenced by _tr_tally(), compress_block(), and tr_static_init().
base_dist
int base_dist[D_CODES]
Definition at line 110 of file trees.c.
Referenced by compress_block(), and tr_static_init().
base_length
int base_length[LENGTH_CODES]
Definition at line 107 of file trees.c.
Referenced by compress_block(), and tr_static_init().
bl_order
const uch bl_order[BL_CODES] = {16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15}
Definition at line 71 of file trees.c.
Referenced by build_bl_tree(), and send_all_trees().
extra_blbits
const int extra_blbits[BL_CODES] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,3,7}
Definition at line 68 of file trees.c.
Referenced by tr_static_init().
extra_dbits
const int extra_dbits[D_CODES] = {0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13}
Definition at line 65 of file trees.c.
Referenced by _tr_tally(), compress_block(), and tr_static_init().
extra_lbits
const int extra_lbits[LENGTH_CODES] = {0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,0}
Definition at line 62 of file trees.c.
Referenced by compress_block(), and tr_static_init().
static_bl_desc
static_tree_desc static_bl_desc
Initial value:
=
{(const ct_data *)0, extra_blbits, 0,   BL_CODES, MAX_BL_BITS}
Definition at line 131 of file trees.c.
Referenced by _tr_init(), and tr_static_init().
static_d_desc
static_tree_desc static_d_desc
Initial value:
=
{static_dtree, extra_dbits, 0,          D_CODES, MAX_BITS}
Definition at line 128 of file trees.c.
Referenced by _tr_init(), and tr_static_init().
static_dtree
ct_data static_dtree[D_CODES]
Definition at line 93 of file trees.c.
Referenced by _tr_flush_block(), and tr_static_init().
static_l_desc
static_tree_desc static_l_desc
Initial value:
=
{static_ltree, extra_lbits, LITERALS+1, L_CODES, MAX_BITS}
Definition at line 125 of file trees.c.
Referenced by _tr_init(), and tr_static_init().
static_ltree
ct_data static_ltree[L_CODES+2]
Definition at line 86 of file trees.c.
Referenced by _tr_align(), _tr_flush_block(), gen_codes(), and tr_static_init().