Azerotcore-wotlk: Acore::BattlegroundChatBuilder Class Reference
Acore::BattlegroundChatBuilder Class Reference
Public Member Functions
BattlegroundChatBuilder (ChatMsg msgtype, uint32 textId, Player const *source, va_list *args=nullptr)
void operator() (WorldPacket &data, LocaleConstant loc_idx)
Private Member Functions
void do_helper (WorldPacket &data, char const *text)
Private Attributes
ChatMsg _msgtype
uint32 _textId
Player const * _source
va_list * _args
Detailed Description
Definition at line 52 of file Battleground.cpp.
Constructor & Destructor Documentation
BattlegroundChatBuilder()
Acore::BattlegroundChatBuilder::BattlegroundChatBuilder (ChatMsg msgtype, uint32 textId, Player const * source, va_list * args = nullptr) inline
Definition at line 55 of file Battleground.cpp.
             : _msgtype(msgtype), _textId(textId), _source(source), _args(args) { }
Member Function Documentation
do_helper()
void Acore::BattlegroundChatBuilder::do_helper (WorldPacket & data, char const * text) inline private
Definition at line 78 of file Battleground.cpp.
         {
             ChatHandler::BuildChatPacket(data, _msgtype, LANG_UNIVERSAL, _source, _source, text);
         }
References _msgtype, _source, ChatHandler::BuildChatPacket(), and LANG_UNIVERSAL.
Referenced by operator()().
operator()()
void Acore::BattlegroundChatBuilder::operator() (WorldPacket & data, LocaleConstant loc_idx) inline
Definition at line 58 of file Battleground.cpp.
         {
             char const* text = sObjectMgr->GetAcoreString(_textId, loc_idx);
             if (_args)
             {
                 // we need copy va_list before use or original va_list will corrupted
                 va_list ap;
                 va_copy(ap, *_args);
                 char str[2048];
                 vsnprintf(str, 2048, text, ap);
                 va_end(ap);
                 do_helper(data, &str[0]);
             }
             else
                 do_helper(data, text);
         }
References _args, _textId, do_helper(), and sObjectMgr.
Member Data Documentation
_args
va_list* Acore::BattlegroundChatBuilder::_args private
Definition at line 86 of file Battleground.cpp.
Referenced by operator()().
_msgtype
ChatMsg Acore::BattlegroundChatBuilder::_msgtype private
Definition at line 83 of file Battleground.cpp.
Referenced by do_helper().
_source
Player const* Acore::BattlegroundChatBuilder::_source private
Definition at line 85 of file Battleground.cpp.
Referenced by mpq::Archive::__repr__(), and do_helper().
_textId
uint32 Acore::BattlegroundChatBuilder::_textId private
Definition at line 84 of file Battleground.cpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/game/Battlegrounds/Battleground.cpp