Azerotcore-wotlk: deps/mysqllite/libmysql/client_settings.h File Reference
client_settings.h File Reference
Macros
#define CLIENT_CAPABILITIES
Functions
sig_handler my_pipe_sig_handler (int sig)
void read_user_name (char *name)
my_bool handle_local_infile (MYSQL *mysql, const char *net_filename)
void mysql_read_default_options (struct st_mysql_options *options, const char *filename, const char *group)
void mysql_detach_stmt_list (LIST **stmt_list, const char *func_name)
MYSQL *STDCALL cli_mysql_real_connect (MYSQL *mysql, const char *host, const char *user, const char *passwd, const char *db, uint port, const char *unix_socket, ulong client_flag)
void cli_mysql_close (MYSQL *mysql)
MYSQL_FIELD * cli_list_fields (MYSQL *mysql)
my_bool cli_read_prepare_result (MYSQL *mysql, MYSQL_STMT *stmt)
MYSQL_DATA * cli_read_rows (MYSQL *mysql, MYSQL_FIELD *mysql_fields, uint fields)
int cli_stmt_execute (MYSQL_STMT *stmt)
int cli_read_binary_rows (MYSQL_STMT *stmt)
int cli_unbuffered_fetch (MYSQL *mysql, char **row)
const char * cli_read_statistics (MYSQL *mysql)
int cli_read_change_user_result (MYSQL *mysql)
C_MODE_START int mysql_init_character_set (MYSQL *mysql)
Variables
uint mysql_port
char * mysql_unix_port
Macro Definition Documentation
CLIENT_CAPABILITIES
#define CLIENT_CAPABILITIES
Value:
                             (CLIENT_LONG_PASSWORD | \
                             CLIENT_LONG_FLAG |     \
                             CLIENT_TRANSACTIONS |  \
                             CLIENT_PROTOCOL_41 | \
                             CLIENT_SECURE_CONNECTION | \
                             CLIENT_MULTI_RESULTS | \
                             CLIENT_PS_MULTI_RESULTS | \
                             CLIENT_PLUGIN_AUTH)
Definition at line 25 of file client_settings.h.
Function Documentation
cli_list_fields()
MYSQL_FIELD* cli_list_fields (MYSQL * mysql)
Definition at line 792 of file libmysql.c.
 {
   MYSQL_DATA *query;
   if (!(query= cli_read_rows(mysql,(MYSQL_FIELD*) 0,
                  protocol_41(mysql) ? 8 : 6)))
     return NULL;
   mysql->field_count= (uint) query->rows;
   return unpack_fields(query,&mysql->field_alloc,
                mysql->field_count, 1, mysql->server_capabilities);
 }
References cli_read_rows(), st_mysql::field_alloc, st_mysql::field_count, NULL, protocol_41, st_mysql_data::rows, st_mysql::server_capabilities, and unpack_fields().
cli_mysql_close()
void cli_mysql_close (MYSQL * mysql)
cli_mysql_real_connect()
MYSQL* STDCALL cli_mysql_real_connect (MYSQL * mysql, const char * host, const char * user, const char * passwd, const char * db, uint port, const char * unix_socket, ulong client_flag)
cli_read_binary_rows()
int cli_read_binary_rows (MYSQL_STMT * stmt)
Definition at line 4224 of file libmysql.c.
 {
   ulong      pkt_len;
   uchar      *cp;
   MYSQL      *mysql= stmt->mysql;
   MYSQL_DATA *result= &stmt->result;
   MYSQL_ROWS *cur, **prev_ptr= &result->data;
   NET        *net;
   DBUG_ENTER("cli_read_binary_rows");
   if (!mysql)
   {
     set_stmt_error(stmt, CR_SERVER_LOST, unknown_sqlstate, NULL);
     DBUG_RETURN(1);
   }
   net = &mysql->net;
   while ((pkt_len= cli_safe_read(mysql)) != packet_error)
   {
     cp= net->read_pos;
     if (cp[0] != 254 || pkt_len >= 8)
     {
       if (!(cur= (MYSQL_ROWS*) alloc_root(&result->alloc,
                                           sizeof(MYSQL_ROWS) + pkt_len - 1)))
       {
         set_stmt_error(stmt, CR_OUT_OF_MEMORY, unknown_sqlstate, NULL);
         goto err;
       }
       cur->data= (MYSQL_ROW) (cur+1);
       *prev_ptr= cur;
       prev_ptr= &cur->next;
       memcpy((char *) cur->data, (char *) cp+1, pkt_len-1);
       cur->length= pkt_len;     /* To allow us to do sanity checks */
       result->rows++;
     }
     else
     {
       /* end of data */
       *prev_ptr= 0;
       mysql->warning_count= uint2korr(cp+1);
       mysql->server_status= uint2korr(cp+3);
       DBUG_PRINT("info",("status: %u  warning_count: %u",
                          mysql->server_status, mysql->warning_count));
       DBUG_RETURN(0);
     }
   }
   set_stmt_errmsg(stmt, net);
 err:
   DBUG_RETURN(1);
 }
References alloc_root(), cli_safe_read(), CR_OUT_OF_MEMORY, CR_SERVER_LOST, st_mysql_rows::data, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, st_mysql_rows::length, memcpy, st_mysql_stmt::mysql, st_mysql::net, st_mysql_rows::next, NULL, packet_error, st_net::read_pos, st_mysql_stmt::result, st_mysql::server_status, set_stmt_errmsg(), set_stmt_error(), uint2korr, unknown_sqlstate, and st_mysql::warning_count.
cli_read_change_user_result()
int cli_read_change_user_result (MYSQL * mysql)
Definition at line 1916 of file client.c.
 {
   return cli_safe_read(mysql);
 }
References cli_safe_read().
cli_read_prepare_result()
my_bool cli_read_prepare_result (MYSQL * mysql, MYSQL_STMT * stmt)
Definition at line 1394 of file libmysql.c.
 {
   uchar *pos;
   uint field_count, param_count;
   ulong packet_length;
   MYSQL_DATA *fields_data;
   DBUG_ENTER("cli_read_prepare_result");
   if ((packet_length= cli_safe_read(mysql)) == packet_error)
     DBUG_RETURN(1);
   mysql->warning_count= 0;
   pos= (uchar*) mysql->net.read_pos;
   stmt->stmt_id= uint4korr(pos+1); pos+= 5;
   /* Number of columns in result set */
   field_count=   uint2korr(pos);   pos+= 2;
   /* Number of placeholders in the statement */
   param_count=   uint2korr(pos);   pos+= 2;
   if (packet_length >= 12)
     mysql->warning_count= uint2korr(pos+1);
   if (param_count != 0)
   {
     MYSQL_DATA *param_data;
     /* skip parameters data: we don't support it yet */
     if (!(param_data= (*mysql->methods->read_rows)(mysql, (MYSQL_FIELD*)0, 7)))
       DBUG_RETURN(1);
     free_rows(param_data);
   }
   if (field_count != 0)
   {
     if (!(mysql->server_status & SERVER_STATUS_AUTOCOMMIT))
       mysql->server_status|= SERVER_STATUS_IN_TRANS;
     if (!(fields_data= (*mysql->methods->read_rows)(mysql,(MYSQL_FIELD*)0,7)))
       DBUG_RETURN(1);
     if (!(stmt->fields= unpack_fields(fields_data,&stmt->mem_root,
                       field_count,0,
                       mysql->server_capabilities)))
       DBUG_RETURN(1);
   }
   stmt->field_count=  field_count;
   stmt->param_count=  (ulong) param_count;
   DBUG_PRINT("exit",("field_count: %u  param_count: %u  warning_count: %u",
                      field_count, param_count, (uint) mysql->warning_count));
   DBUG_RETURN(0);
 }
References cli_safe_read(), DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, st_mysql_stmt::field_count, st_mysql_stmt::fields, free_rows(), st_mysql_stmt::mem_root, st_mysql::methods, st_mysql::net, packet_error, st_mysql_stmt::param_count, pos(), st_net::read_pos, st_mysql_methods::read_rows, st_mysql::server_capabilities, st_mysql::server_status, SERVER_STATUS_AUTOCOMMIT, SERVER_STATUS_IN_TRANS, st_mysql_stmt::stmt_id, uint2korr, uint4korr, unpack_fields(), and st_mysql::warning_count.
cli_read_rows()
MYSQL_DATA* cli_read_rows (MYSQL * mysql, MYSQL_FIELD * mysql_fields, uint fields)
Definition at line 1537 of file client.c.
 {
   uint  field;
   ulong pkt_len;
   ulong len;
   uchar *cp;
   char  *to, *end_to;
   MYSQL_DATA *result;
   MYSQL_ROWS **prev_ptr,*cur;
   NET *net = &mysql->net;
   DBUG_ENTER("cli_read_rows");
   if ((pkt_len= cli_safe_read(mysql)) == packet_error)
     DBUG_RETURN(0);
   if (!(result=(MYSQL_DATA*) my_malloc(sizeof(MYSQL_DATA),
                        MYF(MY_WME | MY_ZEROFILL))))
   {
     set_mysql_error(mysql, CR_OUT_OF_MEMORY, unknown_sqlstate);
     DBUG_RETURN(0);
   }
   init_alloc_root(&result->alloc,8192,0);   /* Assume rowlength < 8192 */
   result->alloc.min_malloc=sizeof(MYSQL_ROWS);
   prev_ptr= &result->data;
   result->rows=0;
   result->fields=fields;
   /*
     The last EOF packet is either a single 254 character or (in MySQL 4.1)
     254 followed by 1-7 status bytes.
     This doesn't conflict with normal usage of 254 which stands for a
     string where the length of the string is 8 bytes. (see net_field_length())
   */
   while (*(cp=net->read_pos) != 254 || pkt_len >= 8)
   {
     result->rows++;
     if (!(cur= (MYSQL_ROWS*) alloc_root(&result->alloc,
                     sizeof(MYSQL_ROWS))) ||
     !(cur->data= ((MYSQL_ROW)
               alloc_root(&result->alloc,
                  (fields+1)*sizeof(char *)+pkt_len))))
     {
       free_rows(result);
       set_mysql_error(mysql, CR_OUT_OF_MEMORY, unknown_sqlstate);
       DBUG_RETURN(0);
     }
     *prev_ptr=cur;
     prev_ptr= &cur->next;
     to= (char*) (cur->data+fields+1);
     end_to=to+pkt_len-1;
     for (field=0 ; field < fields ; field++)
     {
       if ((len=(ulong) net_field_length(&cp)) == NULL_LENGTH)
       {                     /* null field */
     cur->data[field] = 0;
       }
       else
       {
     cur->data[field] = to;
         if (len > (ulong) (end_to - to))
         {
           free_rows(result);
           set_mysql_error(mysql, CR_MALFORMED_PACKET, unknown_sqlstate);
           DBUG_RETURN(0);
         }
     memcpy(to,(char*) cp,len); to[len]=0;
     to+=len+1;
     cp+=len;
     if (mysql_fields)
     {
       if (mysql_fields[field].max_length < len)
         mysql_fields[field].max_length=len;
     }
       }
     }
     cur->data[field]=to;            /* End of last field */
     if ((pkt_len=cli_safe_read(mysql)) == packet_error)
     {
       free_rows(result);
       DBUG_RETURN(0);
     }
   }
   *prev_ptr=0;                  /* last pointer is null */
   if (pkt_len > 1)              /* MySQL 4.1 protocol */
   {
     mysql->warning_count= uint2korr(cp+1);
     mysql->server_status= uint2korr(cp+3);
     DBUG_PRINT("info",("status: %u  warning_count:  %u",
                mysql->server_status, mysql->warning_count));
   }
   DBUG_PRINT("exit", ("Got %lu rows", (ulong) result->rows));
   DBUG_RETURN(result);
 }
References alloc_root(), cli_safe_read(), CR_MALFORMED_PACKET, CR_OUT_OF_MEMORY, st_mysql_rows::data, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, free_rows(), init_alloc_root(), st_mysql_field::max_length, memcpy, my_malloc(), MY_WME, MY_ZEROFILL, MYF, st_mysql::net, net_field_length(), st_mysql_rows::next, NULL_LENGTH, packet_error, st_net::read_pos, st_mysql::server_status, set_mysql_error(), uint2korr, unknown_sqlstate, and st_mysql::warning_count.
Referenced by cli_list_fields(), and cli_read_query_result().
cli_read_statistics()
const char* cli_read_statistics (MYSQL * mysql)
Definition at line 937 of file libmysql.c.
 {
   mysql->net.read_pos[mysql->packet_length]=0;  /* End of stat string */
   if (!mysql->net.read_pos[0])
   {
     set_mysql_error(mysql, CR_WRONG_HOST_INFO, unknown_sqlstate);
     return mysql->net.last_error;
   }
   return (char*) mysql->net.read_pos;
 }
References CR_WRONG_HOST_INFO, st_net::last_error, st_mysql::net, st_mysql::packet_length, st_net::read_pos, set_mysql_error(), and unknown_sqlstate.
cli_stmt_execute()
int cli_stmt_execute (MYSQL_STMT * stmt)
Definition at line 2053 of file libmysql.c.
 {
   DBUG_ENTER("cli_stmt_execute");
   if (stmt->param_count)
   {
     MYSQL *mysql= stmt->mysql;
     NET        *net= &mysql->net;
     MYSQL_BIND *param, *param_end;
     char       *param_data;
     ulong length;
     uint null_count;
     my_bool    result;
     if (!stmt->bind_param_done)
     {
       set_stmt_error(stmt, CR_PARAMS_NOT_BOUND, unknown_sqlstate, NULL);
       DBUG_RETURN(1);
     }
     if (mysql->status != MYSQL_STATUS_READY ||
         mysql->server_status & SERVER_MORE_RESULTS_EXISTS)
     {
       set_stmt_error(stmt, CR_COMMANDS_OUT_OF_SYNC, unknown_sqlstate, NULL);
       DBUG_RETURN(1);
     }
     net_clear(net, 1);              /* Sets net->write_pos */
     /* Reserve place for null-marker bytes */
     null_count= (stmt->param_count+7) /8;
     if (my_realloc_str(net, null_count + 1))
     {
       set_stmt_errmsg(stmt, net);
       DBUG_RETURN(1);
     }
     bzero((char*) net->write_pos, null_count);
     net->write_pos+= null_count;
     param_end= stmt->params + stmt->param_count;
     /* In case if buffers (type) altered, indicate to server */
     *(net->write_pos)++= (uchar) stmt->send_types_to_server;
     if (stmt->send_types_to_server)
     {
       if (my_realloc_str(net, 2 * stmt->param_count))
       {
         set_stmt_errmsg(stmt, net);
         DBUG_RETURN(1);
       }
       /*
     Store types of parameters in first in first package
     that is sent to the server.
       */
       for (param= stmt->params; param < param_end ; param++)
         store_param_type(&net->write_pos, param);
     }
     for (param= stmt->params; param < param_end; param++)
     {
       /* check if mysql_stmt_send_long_data() was used */
       if (param->long_data_used)
     param->long_data_used= 0;   /* Clear for next execute call */
       else if (store_param(stmt, param))
     DBUG_RETURN(1);
     }
     length= (ulong) (net->write_pos - net->buff);
     /* TODO: Look into avoding the following memdup */
     if (!(param_data= my_memdup(net->buff, length, MYF(0))))
     {
       set_stmt_error(stmt, CR_OUT_OF_MEMORY, unknown_sqlstate, NULL);
       DBUG_RETURN(1);
     }
     result= execute(stmt, param_data, length);
     stmt->send_types_to_server=0;
     my_free(param_data);
     DBUG_RETURN(result);
   }
   DBUG_RETURN((int) execute(stmt,0,0));
 }
References st_mysql_stmt::bind_param_done, st_net::buff, bzero, CR_COMMANDS_OUT_OF_SYNC, CR_OUT_OF_MEMORY, CR_PARAMS_NOT_BOUND, DBUG_ENTER, DBUG_RETURN, execute(), G3D::length(), st_mysql_bind::long_data_used, my_free(), my_memdup(), my_realloc_str(), MYF, st_mysql_stmt::mysql, MYSQL_STATUS_READY, st_mysql::net, net_clear(), NULL, st_mysql_stmt::param_count, st_mysql_stmt::params, st_mysql_stmt::send_types_to_server, SERVER_MORE_RESULTS_EXISTS, st_mysql::server_status, set_stmt_errmsg(), set_stmt_error(), st_mysql::status, store_param(), store_param_type(), unknown_sqlstate, and st_net::write_pos.
cli_unbuffered_fetch()
int cli_unbuffered_fetch (MYSQL * mysql, char ** row)
Definition at line 4125 of file libmysql.c.
 {
   if (packet_error == cli_safe_read(mysql))
     return 1;
   *row= ((mysql->net.read_pos[0] == 254) ? NULL :
      (char*) (mysql->net.read_pos+1));
   return 0;
 }
References cli_safe_read(), st_mysql::net, NULL, packet_error, and st_net::read_pos.
handle_local_infile()
my_bool handle_local_infile (MYSQL * mysql, const char * net_filename)
Definition at line 443 of file libmysql.c.
 {
   my_bool result= 1;
   uint packet_length=MY_ALIGN(mysql->net.max_packet-16,IO_SIZE);
   NET *net= &mysql->net;
   int readcount;
   void *li_ptr;          /* pass state to local_infile functions */
   char *buf;        /* buffer to be filled by local_infile_read */
   struct st_mysql_options *options= &mysql->options;
   DBUG_ENTER("handle_local_infile");
   /* check that we've got valid callback functions */
   if (!(options->local_infile_init &&
     options->local_infile_read &&
     options->local_infile_end &&
     options->local_infile_error))
   {
     /* if any of the functions is invalid, set the default */
     mysql_set_local_infile_default(mysql);
   }
   /* copy filename into local memory and allocate read buffer */
   if (!(buf=my_malloc(packet_length, MYF(0))))
   {
     set_mysql_error(mysql, CR_OUT_OF_MEMORY, unknown_sqlstate);
     DBUG_RETURN(1);
   }
   /* initialize local infile (open file, usually) */
   if ((*options->local_infile_init)(&li_ptr, net_filename,
     options->local_infile_userdata))
   {
     (void) my_net_write(net,(const uchar*) "",0); /* Server needs one packet */
     net_flush(net);
     strmov(net->sqlstate, unknown_sqlstate);
     net->last_errno=
       (*options->local_infile_error)(li_ptr,
                                      net->last_error,
                                      sizeof(net->last_error)-1);
     goto err;
   }
   /* read blocks of data from local infile callback */
   while ((readcount =
       (*options->local_infile_read)(li_ptr, buf,
                     packet_length)) > 0)
   {
     if (my_net_write(net, (uchar*) buf, readcount))
     {
       DBUG_PRINT("error",
          ("Lost connection to MySQL server during LOAD DATA of local file"));
       set_mysql_error(mysql, CR_SERVER_LOST, unknown_sqlstate);
       goto err;
     }
   }
   /* Send empty packet to mark end of file */
   if (my_net_write(net, (const uchar*) "", 0) || net_flush(net))
   {
     set_mysql_error(mysql, CR_SERVER_LOST, unknown_sqlstate);
     goto err;
   }
   if (readcount < 0)
   {
     net->last_errno=
       (*options->local_infile_error)(li_ptr,
                                      net->last_error,
                                      sizeof(net->last_error)-1);
     goto err;
   }
   result=0;                 /* Ok */
 err:
   /* free up memory allocated with _init, usually */
   (*options->local_infile_end)(li_ptr);
   my_free(buf);
   DBUG_RETURN(result);
 }
References CR_OUT_OF_MEMORY, CR_SERVER_LOST, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, IO_SIZE, st_net::last_errno, st_net::last_error, st_mysql_options::local_infile_end, st_mysql_options::local_infile_error, st_mysql_options::local_infile_init, st_mysql_options::local_infile_read, st_mysql_options::local_infile_userdata, st_net::max_packet, MY_ALIGN, my_free(), my_malloc(), my_net_write(), MYF, mysql_set_local_infile_default(), st_mysql::net, net_flush(), st_mysql::options, set_mysql_error(), st_net::sqlstate, strmov(), and unknown_sqlstate.
Referenced by cli_read_query_result().
my_pipe_sig_handler()
sig_handler my_pipe_sig_handler (int sig)
mysql_detach_stmt_list()
void mysql_detach_stmt_list (LIST ** stmt_list, const char * func_name)
Referenced by mysql_change_user().
mysql_init_character_set()
C_MODE_START int mysql_init_character_set (MYSQL * mysql)
Definition at line 2220 of file client.c.
 {
   /* Set character set */
   if (!mysql->options.charset_name)
   {
     if (!(mysql->options.charset_name=
        my_strdup(MYSQL_DEFAULT_CHARSET_NAME,MYF(MY_WME))))
       return 1;
   }
   else if (!strcmp(mysql->options.charset_name,
                    MYSQL_AUTODETECT_CHARSET_NAME) &&
             mysql_autodetect_character_set(mysql))
     return 1;
   mysql_set_character_set_with_default_collation(mysql);
   if (!mysql->charset)
   {
     if (mysql->options.charset_dir)
       set_mysql_extended_error(mysql, CR_CANT_READ_CHARSET, unknown_sqlstate,
                                ER(CR_CANT_READ_CHARSET),
                                mysql->options.charset_name,
                                mysql->options.charset_dir);
     else
     {
       char cs_dir_name[FN_REFLEN];
       get_charsets_dir(cs_dir_name);
       set_mysql_extended_error(mysql, CR_CANT_READ_CHARSET, unknown_sqlstate,
                                ER(CR_CANT_READ_CHARSET),
                                mysql->options.charset_name,
                                cs_dir_name);
     }
     return 1;
   }
   return 0;
 }
References st_mysql::charset, st_mysql_options::charset_dir, st_mysql_options::charset_name, CR_CANT_READ_CHARSET, ER, FN_REFLEN, get_charsets_dir(), my_strdup(), MY_WME, MYF, mysql_autodetect_character_set(), MYSQL_AUTODETECT_CHARSET_NAME, mysql_set_character_set_with_default_collation(), st_mysql::options, set_mysql_extended_error(), and unknown_sqlstate.
Referenced by CLI_MYSQL_REAL_CONNECT(), and mysql_change_user().
mysql_read_default_options()
void mysql_read_default_options (struct st_mysql_options * options, const char * filename, const char * group)
Definition at line 1192 of file client.c.
 {
   int argc;
   char *argv_buff[1],**argv;
   const char *groups[3];
   DBUG_ENTER("mysql_read_default_options");
   DBUG_PRINT("enter",("file: %s  group: %s",filename,group ? group :"NULL"));
   argc=1; argv=argv_buff; argv_buff[0]= (char*) "client";
   groups[0]= (char*) "client"; groups[1]= (char*) group; groups[2]=0;
   my_load_defaults(filename, groups, &argc, &argv, NULL);
   if (argc != 1)                /* If some default option */
   {
     char **option=argv;
     while (*++option)
     {
       if (option[0] == args_separator)          /* skip arguments separator */
         continue;
       /* DBUG_PRINT("info",("option: %s",option[0])); */
       if (option[0][0] == '-' && option[0][1] == '-')
       {
     char *end=strcend(*option,'=');
     char *opt_arg=0;
     if (*end)
     {
       opt_arg=end+1;
       *end=0;               /* Remove '=' */
     }
     /* Change all '_' in variable name to '-' */
     for (end= *option ; *(end= strcend(end,'_')) ; )
       *end= '-';
     switch (find_type(*option+2,&option_types,2)) {
     case OPT_port:
       if (opt_arg)
         options->port=atoi(opt_arg);
       break;
     case OPT_socket:
       if (opt_arg)
       {
         my_free(options->unix_socket);
         options->unix_socket=my_strdup(opt_arg,MYF(MY_WME));
       }
       break;
     case OPT_compress:
       options->compress=1;
       options->client_flag|= CLIENT_COMPRESS;
       break;
         case OPT_password:
       if (opt_arg)
       {
         my_free(options->password);
         options->password=my_strdup(opt_arg,MYF(MY_WME));
       }
       break;
         case OPT_pipe:
           options->protocol = MYSQL_PROTOCOL_PIPE;
     case OPT_connect_timeout:
     case OPT_timeout:
       if (opt_arg)
         options->connect_timeout=atoi(opt_arg);
       break;
     case OPT_user:
       if (opt_arg)
       {
         my_free(options->user);
         options->user=my_strdup(opt_arg,MYF(MY_WME));
       }
       break;
     case OPT_init_command:
       add_init_command(options,opt_arg);
       break;
     case OPT_host:
       if (opt_arg)
       {
         my_free(options->host);
         options->host=my_strdup(opt_arg,MYF(MY_WME));
       }
       break;
     case OPT_database:
       if (opt_arg)
       {
         my_free(options->db);
         options->db=my_strdup(opt_arg,MYF(MY_WME));
       }
       break;
     case OPT_debug:
 #ifdef MYSQL_CLIENT
       mysql_debug(opt_arg ? opt_arg : "d:t:o,/tmp/client.trace");
       break;
 #endif
     case OPT_return_found_rows:
       options->client_flag|=CLIENT_FOUND_ROWS;
       break;
 #if defined(HAVE_OPENSSL) && !defined(EMBEDDED_LIBRARY)
     case OPT_ssl_key:
       my_free(options->ssl_key);
           options->ssl_key = my_strdup(opt_arg, MYF(MY_WME));
           break;
     case OPT_ssl_cert:
       my_free(options->ssl_cert);
           options->ssl_cert = my_strdup(opt_arg, MYF(MY_WME));
           break;
     case OPT_ssl_ca:
       my_free(options->ssl_ca);
           options->ssl_ca = my_strdup(opt_arg, MYF(MY_WME));
           break;
     case OPT_ssl_capath:
       my_free(options->ssl_capath);
           options->ssl_capath = my_strdup(opt_arg, MYF(MY_WME));
           break;
         case OPT_ssl_cipher:
           my_free(options->ssl_cipher);
           options->ssl_cipher= my_strdup(opt_arg, MYF(MY_WME));
           break;
 #else
     case OPT_ssl_key:
     case OPT_ssl_cert:
     case OPT_ssl_ca:
     case OPT_ssl_capath:
         case OPT_ssl_cipher:
       break;
 #endif /* HAVE_OPENSSL && !EMBEDDED_LIBRARY */
     case OPT_character_sets_dir:
       my_free(options->charset_dir);
           options->charset_dir = my_strdup(opt_arg, MYF(MY_WME));
       break;
     case OPT_default_character_set:
       my_free(options->charset_name);
           options->charset_name = my_strdup(opt_arg, MYF(MY_WME));
       break;
     case OPT_interactive_timeout:
       options->client_flag|= CLIENT_INTERACTIVE;
       break;
     case OPT_local_infile:
       if (!opt_arg || atoi(opt_arg) != 0)
         options->client_flag|= CLIENT_LOCAL_FILES;
       else
         options->client_flag&= ~CLIENT_LOCAL_FILES;
       break;
     case OPT_disable_local_infile:
       options->client_flag&= ~CLIENT_LOCAL_FILES;
           break;
     case OPT_max_allowed_packet:
           if (opt_arg)
         options->max_allowed_packet= atoi(opt_arg);
       break;
         case OPT_protocol:
           if ((options->protocol= find_type(opt_arg,
                         &sql_protocol_typelib,0)) <= 0)
           {
             fprintf(stderr, "Unknown option to protocol: %s\n", opt_arg);
             exit(1);
           }
           break;
         case OPT_shared_memory_base_name:
 #ifdef HAVE_SMEM
           if (options->shared_memory_base_name != def_shared_memory_base_name)
             my_free(options->shared_memory_base_name);
           options->shared_memory_base_name=my_strdup(opt_arg,MYF(MY_WME));
 #endif
           break;
     case OPT_multi_results:
       options->client_flag|= CLIENT_MULTI_RESULTS;
       break;
     case OPT_multi_statements:
     case OPT_multi_queries:
       options->client_flag|= CLIENT_MULTI_STATEMENTS | CLIENT_MULTI_RESULTS;
       break;
         case OPT_secure_auth:
           options->secure_auth= TRUE;
           break;
         case OPT_report_data_truncation:
           options->report_data_truncation= opt_arg ? test(atoi(opt_arg)) : 1;
           break;
         case OPT_plugin_dir:
           {
             char buff[FN_REFLEN], buff2[FN_REFLEN];
             if (strlen(opt_arg) >= FN_REFLEN)
               opt_arg[FN_REFLEN]= '\0';
             if (my_realpath(buff, opt_arg, 0))
             {
               DBUG_PRINT("warning",("failed to normalize the plugin path: %s",
                                     opt_arg));
               break;
             }
             convert_dirname(buff, buff2, NULL);
             EXTENSION_SET_STRING(options, plugin_dir, buff2);
           }
           break;
         case OPT_default_auth:
           EXTENSION_SET_STRING(options, default_auth, opt_arg);
           break;
     default:
       DBUG_PRINT("warning",("unknown option: %s",option[0]));
     }
       }
     }
   }
   free_defaults(argv);
   DBUG_VOID_RETURN;
 }
Referenced by CLI_MYSQL_REAL_CONNECT().
read_user_name()
void read_user_name (char * name)
Definition at line 405 of file libmysql.c.
 {
   DBUG_ENTER("read_user_name");
   if (geteuid() == 0)
     (void) strmov(name,"root");     /* allow use of surun */
   else
   {
 #ifdef HAVE_GETPWUID
     struct passwd *skr;
     const char *str;
     if ((str=getlogin()) == NULL)
     {
       if ((skr=getpwuid(geteuid())) != NULL)
     str=skr->pw_name;
       else if (!(str=getenv("USER")) && !(str=getenv("LOGNAME")) &&
            !(str=getenv("LOGIN")))
     str="UNKNOWN_USER";
     }
     (void) strmake(name,str,USERNAME_LENGTH);
 #elif HAVE_CUSERID
     (void) cuserid(name);
 #else
     strmov(name,"UNKNOWN_USER");
 #endif
   }
   DBUG_VOID_RETURN;
 }
References DBUG_ENTER, DBUG_VOID_RETURN, if(), name, NULL, strmake(), strmov(), and USERNAME_LENGTH.
Referenced by send_client_reply_packet().
Variable Documentation
mysql_port
uint mysql_port extern
Definition at line 118 of file client.c.
Referenced by CLI_MYSQL_REAL_CONNECT().
mysql_unix_port
char* mysql_unix_port extern
Definition at line 119 of file client.c.
Referenced by CLI_MYSQL_REAL_CONNECT().