Azerotcore-wotlk: H2OHeader Class Reference
H2OHeader Class Reference
#include <Utils.h>
Public Member Functions
H2OHeader ()
Static Public Member Functions
static H2OHeader Read (FILE *stream)
Public Attributes
uint32 OffsetInformation
uint32 LayerCount
uint32 OffsetRender
Detailed Description
Definition at line 295 of file Utils.h.
Constructor & Destructor Documentation
H2OHeader()
H2OHeader::H2OHeader () inline
Definition at line 298 of file Utils.h.
 {}
Member Function Documentation
Read()
H2OHeader H2OHeader::Read (FILE * stream) static
Definition at line 499 of file Utils.cpp.
 {
     H2OHeader ret;
     int count = 0;
     count += fread(&ret.OffsetInformation, sizeof(uint32), 1, stream);
     count += fread(&ret.LayerCount, sizeof(uint32), 1, stream);
     count += fread(&ret.OffsetRender, sizeof(uint32), 1, stream);
     if (count != 3)
         printf("H2OHeader::Read: Failed to read some data expected 3, read %d\n", count);
     return ret;
 }
References count(), printf(), and ret.
Referenced by LiquidHandler::HandleNewLiquid().
Member Data Documentation
LayerCount
uint32 H2OHeader::LayerCount
Definition at line 300 of file Utils.h.
Referenced by LiquidHandler::HandleNewLiquid().
OffsetInformation
uint32 H2OHeader::OffsetInformation
Definition at line 299 of file Utils.h.
Referenced by LiquidHandler::HandleNewLiquid().
OffsetRender
uint32 H2OHeader::OffsetRender
Definition at line 301 of file Utils.h.
Referenced by LiquidHandler::HandleNewLiquid().
The documentation for this class was generated from the following files:
src/tools/mesh_extractor/Utils.h
src/tools/mesh_extractor/Utils.cpp