Azerotcore-wotlk: CMakeLists.txt File Reference
CMakeLists.txt File Reference
Functions
cmake_minimum_required (VERSION 3.16...3.22) message(STATUS "CMake version
cmake_policy (SET CMP0005 NEW) project(AzerothCore VERSION 3.0.0 LANGUAGES CXX C) set(CMAKE_DISABLE_SOURCE_CHANGES ON) set(CMAKE_DISABLE_IN_SOURCE_BUILD ON) set(CMAKE_SKIP_BUILD_RPATH 0) set(CMAKE_BUILD_WITH_INSTALL_RPATH 0) set(CMAKE_INSTALL_RPATH "$
lib set (CMAKE_INSTALL_RPATH_USE_LINK_PATH 1) set(AC_PATH_ROOT "$
list (APPEND CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/src/cmake/macros") include(CheckCXXSourceRuns) include(CheckIncludeFiles) include(ConfigureScripts) include(ConfigureModules) include(deps/acore/cmake-utils/utils.cmake) include(src/cmake/ac_macros.cmake) include(conf/dist/config.cmake) if(EXISTS "$
conf config cmake include (conf/config.cmake) endif() get_filename_component(MODULENAME $
NAME if (";${DISABLED_AC_MODULES};" MATCHES ";${MODULENAME};") continue() endif() if(EXISTS "$
CMakeLists txt add_subdirectory ("${subdir_rel}") endif() if(NOT CMAKE_BUILD_TYPE) set(CMAKE_BUILD_TYPE "RelWithDebInfo") endif() if(NOPCH) set(USE_COREPCH 0) set(USE_SCRIPTPCH 0) endif() include(ConfigureBaseTargets) include(CheckPlatform) include(GroupSources) include(AutoCollect) include(ConfigInstall) set(ACE_EXPECTED_VERSION 6.0.3) find_package(PCHSupport) find_package(MySQL REQUIRED) if(UNIX AND WITH_PERFTOOLS) find_package(Gperftools) endif() if(NOT WITHOUT_GIT) find_package(Git) endif() include(src/cmake/genrev.cmake) include(src/cmake/showoptions.cmake) add_subdirectory(deps) if(SERVERS OR TOOLS) add_subdirectory(src/common) endif() if(TOOLS) add_subdirectory(src/tools) endif() add_subdirectory(src) if(BUILD_TESTING) set(UNIT_TEST_CXX_FLAGS "-fprofile-arcs -ftest-coverage -fno-inline") if(CMAKE_CXX_COMPILER_ID MATCHES GNU) set(UNIT_TEST_CXX_FLAGS "$
fno inline small functions fno default inline endif () message("Unit tests code coverage
set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${UNIT_TEST_CXX_FLAGS}") include(src/cmake/googletest.cmake) fetch_googletest($
Function Documentation
add_subdirectory()
CMakeLists txt add_subdirectory ("${subdir_rel}")
Definition at line 74 of file CMakeLists.txt.
                            {subdir_rel}")
     endif()
 ENDFOREACH()
 CU_RUN_HOOK("AFTER_LOAD_CONF")
 # build in Release-mode by default if not explicitly set
 if(NOT CMAKE_BUILD_TYPE)
     set(CMAKE_BUILD_TYPE "RelWithDebInfo")
 endif()
 # turn off PCH totally if enabled (hidden setting, mainly for devs)
 if( NOPCH )
     set(USE_COREPCH 0)
     set(USE_SCRIPTPCH 0)
 endif()
 include(ConfigureBaseTargets)
 include(CheckPlatform)
 include(GroupSources)
 include(AutoCollect)
 include(ConfigInstall)
 CU_RUN_HOOK("AFTER_LOAD_CMAKE_MODULES")
 # basic packagesearching and setup (further support will be needed, this is a preliminary release!)
 set(ACE_EXPECTED_VERSION 6.0.3)
 find_package(PCHSupport)
 find_package(MySQL REQUIRED)
 if(UNIX AND WITH_PERFTOOLS)
     find_package(Gperftools)
 endif()
 if(NOT WITHOUT_GIT)
     find_package(Git)
 endif()
 # Find revision ID and hash of the sourcetree
 include(src/cmake/genrev.cmake)
 # print out the results before continuing
 include(src/cmake/showoptions.cmake)
 #
 # Loading framework
 #
 add_subdirectory(deps)
 if( SERVERS OR TOOLS)
     add_subdirectory(src/common)
 endif()
 if( TOOLS )
     add_subdirectory(src/tools)
 endif()
 #
 # Loading application sources
 #
 CU_RUN_HOOK("BEFORE_SRC_LOAD")
 # add core sources
 add_subdirectory(src)
 CU_RUN_HOOK("AFTER_SRC_LOAD")
 if( BUILD_TESTING )
     # we use these flags to get code coverage
     set(UNIT_TEST_CXX_FLAGS "-fprofile-arcs -ftest-coverage -fno-inline")
     # enable additional flags for GCC.
     if ( CMAKE_CXX_COMPILER_ID MATCHES GNU )
         set(UNIT_TEST_CXX_FLAGS "${UNIT_TEST_CXX_FLAGS} -fno-inline-small-functions -fno-default-inline")
cmake_minimum_required()
cmake_minimum_required (VERSION 3.16...3. 22)
Definition at line 14 of file CMakeLists.txt.
                              : ${CMAKE_VERSION}")
cmake_policy()
cmake_policy (SET CMP0005 NEW)
Definition at line 19 of file CMakeLists.txt.
                           {CMAKE_INSTALL_PREFIX}/lib")
endif()
HAVE_STRTOD_L endif ()
Definition at line 151 of file CMakeLists.txt.
                                      : enabling ${UNIT_TEST_CXX_FLAGS}")
Referenced by deflate_slow(), dtoa(), ObjectMgr::GetNearestTaxiNode(), gz_open(), http_response(), inflate(), inflateUndermine(), G3D::license(), main(), malloc_read_fd(), my_block_write(), my_getsystime(), my_micro_time(), my_micro_time_and_time(), my_quick_write(), my_rename(), my_strtod_int(), normalize_dirname(), os_pages_unmap(), pages_purge_lazy(), pages_unmap(), soap_begin_count(), soap_begin_recv(), soap_init(), soap_match_tag(), soap_rand_uuid(), soap_recv_raw(), soap_response(), soap_s2int(), soap_s2long(), soap_s2LONG64(), soap_s2ULONG64(), soap_s2unsignedInt(), soap_s2unsignedLong(), soap_try_connect_command(), stmt_update_metadata(), and vio_pending().
if()
NAME if (";${DISABLED_AC_MODULES};" MATCHES ";${MODULENAME};")
Definition at line 68 of file CMakeLists.txt.
            {DISABLED_AC_MODULES};" MATCHES ";${MODULENAME};")
         continue()
     endif()
     STRING(REGEX REPLACE "^${CMAKE_SOURCE_DIR}/" "" subdir_rel ${subdir})
     if(EXISTS "${subdir}/CMakeLists.txt")
Referenced by allocate_dynamic(), arena_decay_backlog_update_last(), Unit::CalculateMeleeDamage(), Player::CastItemCombatSpell(), cli_read_query_result(), ConvertADT(), copy_output_until_stop(), deflateResetKeep(), dynstr_append_mem(), CasterAI::EnterCombat(), Unit::ExecuteDelayedUnitRelocationEvent(), G3D::fill_input_buffer(), fill_window(), spell_shazzrah_gate_dummy::spell_shazzrah_gate_dummy_SpellScript::FilterTargets(), frecv(), get_index_dynamic(), Map::GetFullTerrainStatusForPosition(), WheatyExceptionReport::GetLogicalAddress(), getopt_ull_limit_value(), gzclose_w(), handle_options(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveRootAck(), WorldSession::HandleMoveUnRootAck(), http_parse(), inflate(), inflateBack(), inflateEnd(), inflateGetHeader(), inflatePrime(), inflateReset2(), inflateResetKeep(), inflateSetDictionary(), inflateSync(), CasterAI::InitializeAI(), G3D::LineSegment2D::intersection(), SmartAIMgr::IsEventValid(), libmpq__block_read(), libmpq__do_decompress_wave(), link_block(), SpellMgr::LoadDbcDataCorrections(), SpellMgr::LoadPetDefaultSpells(), SpellMgr::LoadSpellCustomAttr(), my_b_flush_io_cache(), my_dir(), my_load_defaults(), my_net_write(), mysql_prune_stmt_list(), net_write_command(), SmartScript::ProcessEvent(), dtNavMeshQuery::queryPolygonsInTile(), G3D::Intersect::rayAABox(), dtNavMeshQuery::raycast(), lfg::LFGMgr::RBPacketAppendPlayer(), rcBuildCompactHeightfield(), rcFilterLedgeSpans(), read_user_name(), sendMTFValues(), G3D::skip_input_data(), soap_array_begin_out(), soap_begin_recv(), soap_dealloc(), soap_element(), soap_end_recv(), soap_getdime(), soap_init_send(), soap_out_SOAP_ENV__Code(), soap_out_SOAP_ENV__Fault(), soap_print_fault_location(), soap_putdime(), soap_recv_raw(), soap_resolve_attachment(), soap_set_local_namespaces(), soap_try_connect_command(), soap_wstring(), Unit::SpellDamageBonusTaken(), Unit::SpellHealingBonusTaken(), thr_reschedule_write_lock(), G3D::Color3::toHSV(), tree_insert(), unlink_hash(), unpack_fields(), World::UpdateGlobalPlayerMails(), updatewindow(), vio_get_normalized_ip(), vio_pending(), vprintf(), and walkContour().
include()
conf config cmake include (conf/config. cmake)
Definition at line 55 of file CMakeLists.txt.
                           {CMAKE_SOURCE_DIR}/modules" FALSE FALSE)
 FOREACH(subdir ${sub_DIRS})
     get_filename_component(MODULENAME ${subdir} NAME)
list()
list (APPEND CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/src/cmake/macros")
Definition at line 37 of file CMakeLists.txt.
           {CMAKE_SOURCE_DIR}/src/cmake/macros")
 include(CheckCXXSourceRuns)
 include(CheckIncludeFiles)
 include(ConfigureScripts)
 include(ConfigureModules)
 # some utils for cmake
 include(deps/acore/cmake-utils/utils.cmake)
 include(src/cmake/ac_macros.cmake)
 # set default buildoptions and print them
 include(conf/dist/config.cmake)
 # load custom configurations for cmake if exists
 if(EXISTS "${CMAKE_SOURCE_DIR}/conf/config.cmake")
Referenced by _lf_pinbox_real_free(), ScriptedAI::DoFindFriendlyCC(), ScriptedAI::DoFindFriendlyMissingBuff(), SmartScript::DoFindFriendlyMissingBuff(), boss_rotface::boss_rotfaceAI::EnterCombat(), extent_list_append(), extent_list_first(), extent_list_init(), extent_list_last(), extent_list_prepend(), extent_list_remove(), extent_list_replace(), GetCreatureListWithEntryInGrid(), GetDeadCreatureListInGrid(), GetGameObjectListWithEntryInGrid(), G3D::_internal::Welder::getIndex(), Unit::IsImmunedToSpellEffect(), join(), list_cons(), list_length(), list_walk(), SpellMgr::LoadSpellRanks(), SmartScript::ProcessEvent(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::remove(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::remove(), G3D::_internal::WeldHelper::smoothNormals(), str_list_find(), WorldObject::SummonCreatureGroup(), Map::SummonCreatureGroup(), thr_print_lock(), and thr_print_locks().
set() [1/2]
set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${UNIT_TEST_CXX_FLAGS}")
Definition at line 154 of file CMakeLists.txt.
                           {CMAKE_CXX_FLAGS} ${UNIT_TEST_CXX_FLAGS}")
     include(src/cmake/googletest.cmake)
     fetch_googletest(
             ${PROJECT_SOURCE_DIR}/src/cmake
set() [2/2]
lib set (CMAKE_INSTALL_RPATH_USE_LINK_PATH 1)
Definition at line 32 of file CMakeLists.txt.
                    {CMAKE_SOURCE_DIR}")
Referenced by G3D::FileSystem::_getDirectories(), G3D::FileSystem::_getFiles(), AddItemsSetItem(), basic_memory_buffer< T, SIZE, Allocator >::basic_memory_buffer(), basic_memory_buffer< T, SIZE, Allocator >::grow(), lookup_commandscript::HandleLookupItemSetCommand(), WorldModelHandler::InsertModelGeometry(), malloc_ncpus(), basic_memory_buffer< T, SIZE, Allocator >::move(), Object::PrintIndexError(), RemoveItemsSetItem(), Unit::SetInstantCast(), Channel::SetMode(), Channel::SetModerator(), Channel::SetMute(), Runes::SetRuneState(), sigwait(), sigwait_setup(), soap_accept(), soap_bind(), strcont(), tcp_connect(), G3D::toUpper(), and G3D::XML::unparse().