Azerotcore-wotlk: instance_zulgurub::instance_zulgurub_InstanceMapScript Struct Reference
instance_zulgurub::instance_zulgurub_InstanceMapScript Struct Reference
Public Member Functions
instance_zulgurub_InstanceMapScript (Map *map)
bool IsEncounterInProgress () const override
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetGuidData (uint32 uiData) const override
std::string GetSaveData () override
void Load (const char *str) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void CreatureLooted (Creature *, LootType)
void SaveToDB ()
virtual void Update (uint32)
void OnCreatureRemove (Creature *creature) override
ObjectGuid GetObjectGuid (uint32 type) const
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Private Attributes
ObjectGuid _zealotLorkhanGUID
ObjectGuid _zealotZathGUID
ObjectGuid _highPriestTekalGUID
ObjectGuid _jindoTheHexxerGUID
ObjectGuid _vilebranchSpeakerGUID
ObjectGuid _arlokkGUID
ObjectGuid _goGongOfBethekkGUID
ObjectGuid _hakkarGUID
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Definition at line 40 of file instance_zulgurub.cpp.
Constructor & Destructor Documentation
instance_zulgurub_InstanceMapScript()
instance_zulgurub::instance_zulgurub_InstanceMapScript::instance_zulgurub_InstanceMapScript (Map * map) inline
Definition at line 42 of file instance_zulgurub.cpp.
                                                       : InstanceScript(map)
         {
             SetBossNumber(EncounterCount);
             LoadDoorData(doorData);
         }
References doorData, EncounterCount, InstanceScript::LoadDoorData(), and InstanceScript::SetBossNumber().
Member Function Documentation
GetGuidData()
ObjectGuid instance_zulgurub::instance_zulgurub_InstanceMapScript::GetGuidData (uint32 uiData) const inline override virtual
Reimplemented from InstanceScript.
Definition at line 113 of file instance_zulgurub.cpp.
         {
             switch (uiData)
             {
                 case DATA_LORKHAN:
                     return _zealotLorkhanGUID;
                 case DATA_ZATH:
                     return _zealotZathGUID;
                 case DATA_THEKAL:
                     return _highPriestTekalGUID;
                 case DATA_JINDO:
                     return _jindoTheHexxerGUID;
                 case NPC_ARLOKK:
                     return _arlokkGUID;
                 case GO_GONG_OF_BETHEKK:
                     return _goGongOfBethekkGUID;
                 case DATA_HAKKAR:
                     return _hakkarGUID;
             }
             return ObjectGuid::Empty;
         }
References _arlokkGUID, _goGongOfBethekkGUID, _hakkarGUID, _highPriestTekalGUID, _jindoTheHexxerGUID, _zealotLorkhanGUID, _zealotZathGUID, DATA_HAKKAR, DATA_JINDO, DATA_LORKHAN, DATA_THEKAL, DATA_ZATH, ObjectGuid::Empty, GO_GONG_OF_BETHEKK, and NPC_ARLOKK.
GetSaveData()
std::string instance_zulgurub::instance_zulgurub_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
Definition at line 136 of file instance_zulgurub.cpp.
         {
             OUT_SAVE_INST_DATA;
             std::ostringstream saveStream;
             saveStream << "Z G " << GetBossSaveData();
             OUT_SAVE_INST_DATA_COMPLETE;
             return saveStream.str();
         }
References InstanceScript::GetBossSaveData(), OUT_SAVE_INST_DATA, and OUT_SAVE_INST_DATA_COMPLETE.
IsEncounterInProgress()
bool instance_zulgurub::instance_zulgurub_InstanceMapScript::IsEncounterInProgress () const inline override virtual
Reimplemented from InstanceScript.
Definition at line 48 of file instance_zulgurub.cpp.
         {
             // not active in Zul'Gurub
             return false;
         }
Load()
void instance_zulgurub::instance_zulgurub_InstanceMapScript::Load (const char * str) inline override virtual
Reimplemented from InstanceScript.
Definition at line 147 of file instance_zulgurub.cpp.
         {
             if (!str)
             {
                 OUT_LOAD_INST_DATA_FAIL;
                 return;
             }
             OUT_LOAD_INST_DATA(str);
             char dataHead1, dataHead2;
             std::istringstream loadStream(str);
             loadStream >> dataHead1 >> dataHead2;
             if (dataHead1 == 'Z' && dataHead2 == 'G')
             {
                 for (uint32 i = 0; i < EncounterCount; ++i)
                 {
                     uint32 tmpState;
                     loadStream >> tmpState;
                     if (tmpState == IN_PROGRESS || tmpState > SPECIAL)
                         tmpState = NOT_STARTED;
                     SetBossState(i, EncounterState(tmpState));
                 }
             }
             else
                 OUT_LOAD_INST_DATA_FAIL;
             OUT_LOAD_INST_DATA_COMPLETE;
         }
References EncounterCount, IN_PROGRESS, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, OUT_LOAD_INST_DATA_FAIL, InstanceScript::SetBossState(), and SPECIAL.
OnCreatureCreate()
void instance_zulgurub::instance_zulgurub_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 54 of file instance_zulgurub.cpp.
         {
             switch (creature->GetEntry())
             {
                 case NPC_ZEALOT_LORKHAN:
                     _zealotLorkhanGUID = creature->GetGUID();
                     break;
                 case NPC_ZEALOT_ZATH:
                     _zealotZathGUID = creature->GetGUID();
                     break;
                 case NPC_HIGH_PRIEST_THEKAL:
                     _highPriestTekalGUID = creature->GetGUID();
                     break;
                 case NPC_JINDO_THE_HEXXER:
                     _jindoTheHexxerGUID = creature->GetGUID();
                     break;
                 case NPC_VILEBRANCH_SPEAKER:
                     _vilebranchSpeakerGUID = creature->GetGUID();
                     break;
                 case NPC_ARLOKK:
                     _arlokkGUID = creature->GetGUID();
                     break;
                 case NPC_HAKKAR:
                     _hakkarGUID = creature->GetGUID();
                     break;
             }
         }
References _arlokkGUID, _hakkarGUID, _highPriestTekalGUID, _jindoTheHexxerGUID, _vilebranchSpeakerGUID, _zealotLorkhanGUID, _zealotZathGUID, Object::GetEntry(), Object::GetGUID(), NPC_ARLOKK, NPC_HAKKAR, NPC_HIGH_PRIEST_THEKAL, NPC_JINDO_THE_HEXXER, NPC_VILEBRANCH_SPEAKER, NPC_ZEALOT_LORKHAN, and NPC_ZEALOT_ZATH.
OnGameObjectCreate()
void instance_zulgurub::instance_zulgurub_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
Definition at line 82 of file instance_zulgurub.cpp.
         {
             switch (go->GetEntry())
             {
                 case GO_FORCEFIELD:
                     AddDoor(go, true);
                     break;
                 case GO_GONG_OF_BETHEKK:
                     _goGongOfBethekkGUID = go->GetGUID();
                     if (GetBossState(DATA_ARLOKK) == DONE)
                         go->SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                     else
                         go->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                     break;
                 default:
                     break;
             }
         }
References _goGongOfBethekkGUID, InstanceScript::AddDoor(), DATA_ARLOKK, DONE, GAMEOBJECT_FLAGS, InstanceScript::GetBossState(), Object::GetEntry(), Object::GetGUID(), GO_FLAG_NOT_SELECTABLE, GO_FORCEFIELD, GO_GONG_OF_BETHEKK, Object::RemoveFlag(), and Object::SetFlag().
OnGameObjectRemove()
void instance_zulgurub::instance_zulgurub_InstanceMapScript::OnGameObjectRemove (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
Definition at line 101 of file instance_zulgurub.cpp.
         {
             switch (go->GetEntry())
             {
                 case GO_FORCEFIELD:
                     AddDoor(go, false);
                     break;
                 default:
                     break;
             }
         }
References InstanceScript::AddDoor(), Object::GetEntry(), and GO_FORCEFIELD.
Member Data Documentation
_arlokkGUID
ObjectGuid instance_zulgurub::instance_zulgurub_InstanceMapScript::_arlokkGUID private
Definition at line 187 of file instance_zulgurub.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
_goGongOfBethekkGUID
ObjectGuid instance_zulgurub::instance_zulgurub_InstanceMapScript::_goGongOfBethekkGUID private
Definition at line 188 of file instance_zulgurub.cpp.
Referenced by GetGuidData(), and OnGameObjectCreate().
_hakkarGUID
ObjectGuid instance_zulgurub::instance_zulgurub_InstanceMapScript::_hakkarGUID private
Definition at line 189 of file instance_zulgurub.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
_highPriestTekalGUID
ObjectGuid instance_zulgurub::instance_zulgurub_InstanceMapScript::_highPriestTekalGUID private
Definition at line 184 of file instance_zulgurub.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
_jindoTheHexxerGUID
ObjectGuid instance_zulgurub::instance_zulgurub_InstanceMapScript::_jindoTheHexxerGUID private
Definition at line 185 of file instance_zulgurub.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
_vilebranchSpeakerGUID
ObjectGuid instance_zulgurub::instance_zulgurub_InstanceMapScript::_vilebranchSpeakerGUID private
Definition at line 186 of file instance_zulgurub.cpp.
Referenced by OnCreatureCreate().
_zealotLorkhanGUID
ObjectGuid instance_zulgurub::instance_zulgurub_InstanceMapScript::_zealotLorkhanGUID private
Definition at line 182 of file instance_zulgurub.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
_zealotZathGUID
ObjectGuid instance_zulgurub::instance_zulgurub_InstanceMapScript::_zealotZathGUID private
Definition at line 183 of file instance_zulgurub.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/ZulGurub/instance_zulgurub.cpp