Azerotcore-wotlk: deps/mysqllite/include/mysql_com.h File Reference
mysql_com.h File Reference
Classes
struct st_net
struct rand_struct
struct st_udf_args
struct st_udf_init
Macros
#define HOSTNAME_LENGTH 60
#define SYSTEM_CHARSET_MBMAXLEN 3
#define NAME_CHAR_LEN 64 /* Field/table name length */
#define USERNAME_CHAR_LENGTH 16
#define NAME_LEN (NAME_CHAR_LEN*SYSTEM_CHARSET_MBMAXLEN)
#define USERNAME_LENGTH (USERNAME_CHAR_LENGTH*SYSTEM_CHARSET_MBMAXLEN)
#define MYSQL_AUTODETECT_CHARSET_NAME "auto"
#define SERVER_VERSION_LENGTH 60
#define SQLSTATE_LENGTH 5
#define TABLE_COMMENT_INLINE_MAXLEN 180 /* pre 6.0: 60 characters */
#define TABLE_COMMENT_MAXLEN 2048
#define COLUMN_COMMENT_MAXLEN 1024
#define INDEX_COMMENT_MAXLEN 1024
#define USER_HOST_BUFF_SIZE HOSTNAME_LENGTH + USERNAME_LENGTH + 2
#define LOCAL_HOST "localhost"
#define LOCAL_HOST_NAMEDPIPE "."
#define SCRAMBLE_LENGTH 20
#define SCRAMBLE_LENGTH_323 8
#define SCRAMBLED_PASSWORD_CHAR_LENGTH (SCRAMBLE_LENGTH*2+1)
#define SCRAMBLED_PASSWORD_CHAR_LENGTH_323 (SCRAMBLE_LENGTH_323*2)
#define NOT_NULL_FLAG 1 /* Field can't be NULL */
#define PRI_KEY_FLAG 2 /* Field is part of a primary key */
#define UNIQUE_KEY_FLAG 4 /* Field is part of a unique key */
#define MULTIPLE_KEY_FLAG 8 /* Field is part of a key */
#define BLOB_FLAG 16 /* Field is a blob */
#define UNSIGNED_FLAG 32 /* Field is unsigned */
#define ZEROFILL_FLAG 64 /* Field is zerofill */
#define BINARY_FLAG 128 /* Field is binary */
#define ENUM_FLAG 256 /* field is an enum */
#define AUTO_INCREMENT_FLAG 512 /* field is a autoincrement field */
#define TIMESTAMP_FLAG 1024 /* Field is a timestamp */
#define SET_FLAG 2048 /* field is a set */
#define NO_DEFAULT_VALUE_FLAG 4096 /* Field doesn't have default value */
#define ON_UPDATE_NOW_FLAG 8192 /* Field is set to NOW on UPDATE */
#define NUM_FLAG 32768 /* Field is num (for clients) */
#define PART_KEY_FLAG 16384 /* Intern; Part of some key */
#define GROUP_FLAG 32768 /* Intern: Group field */
#define UNIQUE_FLAG 65536 /* Intern: Used by sql_yacc */
#define BINCMP_FLAG 131072 /* Intern: Used by sql_yacc */
#define GET_FIXED_FIELDS_FLAG (1 << 18) /* Used to get fields in item tree */
#define FIELD_IN_PART_FUNC_FLAG (1 << 19)/* Field part of partition func */
#define FIELD_IN_ADD_INDEX (1<< 20) /* Intern: Field used in ADD INDEX */
#define FIELD_IS_RENAMED (1<< 21) /* Intern: Field is being renamed */
#define REFRESH_GRANT 1 /* Refresh grant tables */
#define REFRESH_LOG 2 /* Start on new log file */
#define REFRESH_TABLES 4 /* close all tables */
#define REFRESH_HOSTS 8 /* Flush host cache */
#define REFRESH_STATUS 16 /* Flush status variables */
#define REFRESH_THREADS 32 /* Flush thread cache */
#define REFRESH_SLAVE
#define REFRESH_MASTER
#define REFRESH_ERROR_LOG 256 /* Rotate only the erorr log */
#define REFRESH_ENGINE_LOG 512 /* Flush all storage engine logs */
#define REFRESH_BINARY_LOG 1024 /* Flush the binary log */
#define REFRESH_RELAY_LOG 2048 /* Flush the relay log */
#define REFRESH_GENERAL_LOG 4096 /* Flush the general log */
#define REFRESH_SLOW_LOG 8192 /* Flush the slow query log */
#define REFRESH_READ_LOCK 16384 /* Lock tables for read */
#define REFRESH_FAST 32768 /* Intern flag */
#define REFRESH_QUERY_CACHE 65536
#define REFRESH_QUERY_CACHE_FREE 0x20000L /* pack query cache */
#define REFRESH_DES_KEY_FILE 0x40000L
#define REFRESH_USER_RESOURCES 0x80000L
#define CLIENT_LONG_PASSWORD 1 /* new more secure passwords */
#define CLIENT_FOUND_ROWS 2 /* Found instead of affected rows */
#define CLIENT_LONG_FLAG 4 /* Get all column flags */
#define CLIENT_CONNECT_WITH_DB 8 /* One can specify db on connect */
#define CLIENT_NO_SCHEMA 16 /* Don't allow database.table.column */
#define CLIENT_COMPRESS 32 /* Can use compression protocol */
#define CLIENT_ODBC 64 /* Odbc client */
#define CLIENT_LOCAL_FILES 128 /* Can use LOAD DATA LOCAL */
#define CLIENT_IGNORE_SPACE 256 /* Ignore spaces before '(' */
#define CLIENT_PROTOCOL_41 512 /* New 4.1 protocol */
#define CLIENT_INTERACTIVE 1024 /* This is an interactive client */
#define CLIENT_SSL 2048 /* Switch to SSL after handshake */
#define CLIENT_IGNORE_SIGPIPE 4096 /* IGNORE sigpipes */
#define CLIENT_TRANSACTIONS 8192 /* Client knows about transactions */
#define CLIENT_RESERVED 16384 /* Old flag for 4.1 protocol */
#define CLIENT_SECURE_CONNECTION 32768 /* New 4.1 authentication */
#define CLIENT_MULTI_STATEMENTS (1UL << 16) /* Enable/disable multi-stmt support */
#define CLIENT_MULTI_RESULTS (1UL << 17) /* Enable/disable multi-results */
#define CLIENT_PS_MULTI_RESULTS (1UL << 18) /* Multi-results in PS-protocol */
#define CLIENT_PLUGIN_AUTH (1UL << 19) /* Client supports plugin authentication */
#define CLIENT_SSL_VERIFY_SERVER_CERT (1UL << 30)
#define CLIENT_REMEMBER_OPTIONS (1UL << 31)
#define CAN_CLIENT_COMPRESS 0
#define CLIENT_ALL_FLAGS
#define CLIENT_BASIC_FLAGS
#define SERVER_STATUS_IN_TRANS 1
#define SERVER_STATUS_AUTOCOMMIT 2 /* Server in auto_commit mode */
#define SERVER_MORE_RESULTS_EXISTS 8 /* Multi query - next query exists */
#define SERVER_QUERY_NO_GOOD_INDEX_USED 16
#define SERVER_QUERY_NO_INDEX_USED 32
#define SERVER_STATUS_CURSOR_EXISTS 64
#define SERVER_STATUS_LAST_ROW_SENT 128
#define SERVER_STATUS_DB_DROPPED 256 /* A database was dropped */
#define SERVER_STATUS_NO_BACKSLASH_ESCAPES 512
#define SERVER_STATUS_METADATA_CHANGED 1024
#define SERVER_QUERY_WAS_SLOW 2048
#define SERVER_PS_OUT_PARAMS 4096
#define SERVER_STATUS_CLEAR_SET
#define MYSQL_ERRMSG_SIZE 512
#define NET_READ_TIMEOUT 30 /* Timeout on read */
#define NET_WRITE_TIMEOUT 60 /* Timeout on write */
#define NET_WAIT_TIMEOUT 8*60*60 /* Wait for new query */
#define ONLY_KILL_QUERY 1
#define MAX_TINYINT_WIDTH 3 /* Max width for a TINY w.o. sign */
#define MAX_SMALLINT_WIDTH 5 /* Max width for a SHORT w.o. sign */
#define MAX_MEDIUMINT_WIDTH 8 /* Max width for a INT24 w.o. sign */
#define MAX_INT_WIDTH 10 /* Max width for a LONG w.o. sign */
#define MAX_BIGINT_WIDTH 20 /* Max width for a LONGLONG */
#define MAX_CHAR_WIDTH 255 /* Max length for a CHAR colum */
#define MAX_BLOB_WIDTH 16777216 /* Default width for blob */
#define packet_error (~(unsigned long) 0)
#define CLIENT_MULTI_QUERIES CLIENT_MULTI_STATEMENTS
#define FIELD_TYPE_DECIMAL MYSQL_TYPE_DECIMAL
#define FIELD_TYPE_NEWDECIMAL MYSQL_TYPE_NEWDECIMAL
#define FIELD_TYPE_TINY MYSQL_TYPE_TINY
#define FIELD_TYPE_SHORT MYSQL_TYPE_SHORT
#define FIELD_TYPE_LONG MYSQL_TYPE_LONG
#define FIELD_TYPE_FLOAT MYSQL_TYPE_FLOAT
#define FIELD_TYPE_DOUBLE MYSQL_TYPE_DOUBLE
#define FIELD_TYPE_NULL MYSQL_TYPE_NULL
#define FIELD_TYPE_TIMESTAMP MYSQL_TYPE_TIMESTAMP
#define FIELD_TYPE_LONGLONG MYSQL_TYPE_LONGLONG
#define FIELD_TYPE_INT24 MYSQL_TYPE_INT24
#define FIELD_TYPE_DATE MYSQL_TYPE_DATE
#define FIELD_TYPE_TIME MYSQL_TYPE_TIME
#define FIELD_TYPE_DATETIME MYSQL_TYPE_DATETIME
#define FIELD_TYPE_YEAR MYSQL_TYPE_YEAR
#define FIELD_TYPE_NEWDATE MYSQL_TYPE_NEWDATE
#define FIELD_TYPE_ENUM MYSQL_TYPE_ENUM
#define FIELD_TYPE_SET MYSQL_TYPE_SET
#define FIELD_TYPE_TINY_BLOB MYSQL_TYPE_TINY_BLOB
#define FIELD_TYPE_MEDIUM_BLOB MYSQL_TYPE_MEDIUM_BLOB
#define FIELD_TYPE_LONG_BLOB MYSQL_TYPE_LONG_BLOB
#define FIELD_TYPE_BLOB MYSQL_TYPE_BLOB
#define FIELD_TYPE_VAR_STRING MYSQL_TYPE_VAR_STRING
#define FIELD_TYPE_STRING MYSQL_TYPE_STRING
#define FIELD_TYPE_CHAR MYSQL_TYPE_TINY
#define FIELD_TYPE_INTERVAL MYSQL_TYPE_ENUM
#define FIELD_TYPE_GEOMETRY MYSQL_TYPE_GEOMETRY
#define FIELD_TYPE_BIT MYSQL_TYPE_BIT
#define MYSQL_SHUTDOWN_KILLABLE_CONNECT (unsigned char)(1 << 0)
#define MYSQL_SHUTDOWN_KILLABLE_TRANS (unsigned char)(1 << 1)
#define MYSQL_SHUTDOWN_KILLABLE_LOCK_TABLE (unsigned char)(1 << 2)
#define MYSQL_SHUTDOWN_KILLABLE_UPDATE (unsigned char)(1 << 3)
#define net_new_transaction(net) ((net)->pkt_nr=0)
#define NET_HEADER_SIZE 4 /* standard header size */
#define COMP_HEADER_SIZE 3 /* compression header extra size */
#define NULL_LENGTH ((unsigned long) ~0) /* For net_store_length */
#define MYSQL_STMT_HEADER 4
#define MYSQL_LONG_DATA_HEADER 6
#define NOT_FIXED_DEC 31
Typedefs
typedef struct st_vio Vio
typedef struct st_net NET
typedef struct st_udf_args UDF_ARGS
typedef struct st_udf_init UDF_INIT
Enumerations
enum enum_server_command {
COM_SLEEP , COM_QUIT , COM_INIT_DB , COM_QUERY ,
COM_FIELD_LIST , COM_CREATE_DB , COM_DROP_DB , COM_REFRESH ,
COM_SHUTDOWN , COM_STATISTICS , COM_PROCESS_INFO , COM_CONNECT ,
COM_PROCESS_KILL , COM_DEBUG , COM_PING , COM_TIME ,
COM_DELAYED_INSERT , COM_CHANGE_USER , COM_BINLOG_DUMP , COM_TABLE_DUMP ,
COM_CONNECT_OUT , COM_REGISTER_SLAVE , COM_STMT_PREPARE , COM_STMT_EXECUTE ,
COM_STMT_SEND_LONG_DATA , COM_STMT_CLOSE , COM_STMT_RESET , COM_SET_OPTION ,
COM_STMT_FETCH , COM_DAEMON , COM_END
}
enum enum_field_types {
MYSQL_TYPE_DECIMAL , MYSQL_TYPE_TINY , MYSQL_TYPE_SHORT , MYSQL_TYPE_LONG ,
MYSQL_TYPE_FLOAT , MYSQL_TYPE_DOUBLE , MYSQL_TYPE_NULL , MYSQL_TYPE_TIMESTAMP ,
MYSQL_TYPE_LONGLONG , MYSQL_TYPE_INT24 , MYSQL_TYPE_DATE , MYSQL_TYPE_TIME ,
MYSQL_TYPE_DATETIME , MYSQL_TYPE_YEAR , MYSQL_TYPE_NEWDATE , MYSQL_TYPE_VARCHAR ,
MYSQL_TYPE_BIT , MYSQL_TYPE_NEWDECIMAL =246 , MYSQL_TYPE_ENUM =247 , MYSQL_TYPE_SET =248 ,
MYSQL_TYPE_TINY_BLOB =249 , MYSQL_TYPE_MEDIUM_BLOB =250 , MYSQL_TYPE_LONG_BLOB =251 , MYSQL_TYPE_BLOB =252 ,
MYSQL_TYPE_VAR_STRING =253 , MYSQL_TYPE_STRING =254 , MYSQL_TYPE_GEOMETRY =255
}
enum mysql_enum_shutdown_level {
SHUTDOWN_DEFAULT = 0 , SHUTDOWN_WAIT_CONNECTIONS = MYSQL_SHUTDOWN_KILLABLE_CONNECT , SHUTDOWN_WAIT_TRANSACTIONS = MYSQL_SHUTDOWN_KILLABLE_TRANS , SHUTDOWN_WAIT_UPDATES = MYSQL_SHUTDOWN_KILLABLE_UPDATE ,
SHUTDOWN_WAIT_ALL_BUFFERS = (MYSQL_SHUTDOWN_KILLABLE_UPDATE << 1) , SHUTDOWN_WAIT_CRITICAL_BUFFERS = (MYSQL_SHUTDOWN_KILLABLE_UPDATE << 1) + 1 , KILL_CONNECTION = 255
}
enum enum_cursor_type { CURSOR_TYPE_NO_CURSOR = 0 , CURSOR_TYPE_READ_ONLY = 1 , CURSOR_TYPE_FOR_UPDATE = 2 , CURSOR_TYPE_SCROLLABLE = 4 }
enum enum_mysql_set_option { MYSQL_OPTION_MULTI_STATEMENTS_ON , MYSQL_OPTION_MULTI_STATEMENTS_OFF }
enum Item_result {
STRING_RESULT =0 , REAL_RESULT , INT_RESULT , ROW_RESULT ,
DECIMAL_RESULT
}
Functions
my_bool my_net_init (NET *net, Vio *vio)
void my_net_local_init (NET *net)
void net_end (NET *net)
void net_clear (NET *net, my_bool clear_buffer)
my_bool net_realloc (NET *net, size_t length)
my_bool net_flush (NET *net)
my_bool my_net_write (NET *net, const unsigned char *packet, size_t len)
my_bool net_write_command (NET *net, unsigned char command, const unsigned char *header, size_t head_len, const unsigned char *packet, size_t len)
int net_real_write (NET *net, const unsigned char *packet, size_t len)
unsigned long my_net_read (NET *net)
int my_connect (my_socket s, const struct sockaddr *name, unsigned int namelen, unsigned int timeout)
void randominit (struct rand_struct *, unsigned long seed1, unsigned long seed2)
double my_rnd (struct rand_struct *)
void create_random_string (char *to, unsigned int length, struct rand_struct *rand_st)
void hash_password (unsigned long *to, const char *password, unsigned int password_len)
void make_scrambled_password_323 (char *to, const char *password)
void scramble_323 (char *to, const char *message, const char *password)
my_bool check_scramble_323 (const unsigned char *reply, const char *message, unsigned long *salt)
void get_salt_from_password_323 (unsigned long *res, const char *password)
void make_password_from_salt_323 (char *to, const unsigned long *salt)
void make_scrambled_password (char *to, const char *password)
void scramble (char *to, const char *message, const char *password)
my_bool check_scramble (const unsigned char *reply, const char *message, const unsigned char *hash_stage2)
void get_salt_from_password (unsigned char *res, const char *password)
void make_password_from_salt (char *to, const unsigned char *hash_stage2)
char * octet2hex (char *to, const char *str, unsigned int len)
char * get_tty_password (const char *opt_message)
const char * mysql_errno_to_sqlstate (unsigned int mysql_errno)
my_bool my_thread_init (void)
void my_thread_end (void)
Macro Definition Documentation
AUTO_INCREMENT_FLAG
#define AUTO_INCREMENT_FLAG 512 /* field is a autoincrement field */
Definition at line 103 of file mysql_com.h.
BINARY_FLAG
#define BINARY_FLAG 128 /* Field is binary */
Definition at line 99 of file mysql_com.h.
BINCMP_FLAG
#define BINCMP_FLAG 131072 /* Intern: Used by sql_yacc */
Definition at line 112 of file mysql_com.h.
BLOB_FLAG
#define BLOB_FLAG 16 /* Field is a blob */
Definition at line 96 of file mysql_com.h.
CAN_CLIENT_COMPRESS
#define CAN_CLIENT_COMPRESS 0
Definition at line 171 of file mysql_com.h.
CLIENT_ALL_FLAGS
#define CLIENT_ALL_FLAGS
Value:
                           (CLIENT_LONG_PASSWORD | \
                           CLIENT_FOUND_ROWS | \
                           CLIENT_LONG_FLAG | \
                           CLIENT_CONNECT_WITH_DB | \
                           CLIENT_NO_SCHEMA | \
                           CLIENT_COMPRESS | \
                           CLIENT_ODBC | \
                           CLIENT_LOCAL_FILES | \
                           CLIENT_IGNORE_SPACE | \
                           CLIENT_PROTOCOL_41 | \
                           CLIENT_INTERACTIVE | \
                           CLIENT_SSL | \
                           CLIENT_IGNORE_SIGPIPE | \
                           CLIENT_TRANSACTIONS | \
                           CLIENT_RESERVED | \
                           CLIENT_SECURE_CONNECTION | \
                           CLIENT_MULTI_STATEMENTS | \
                           CLIENT_MULTI_RESULTS | \
                           CLIENT_PS_MULTI_RESULTS | \
                           CLIENT_SSL_VERIFY_SERVER_CERT | \
                           CLIENT_REMEMBER_OPTIONS | \
                           CLIENT_PLUGIN_AUTH)
Definition at line 175 of file mysql_com.h.
CLIENT_BASIC_FLAGS
#define CLIENT_BASIC_FLAGS
Value:
                                               (((CLIENT_ALL_FLAGS & ~CLIENT_SSL) \
                                               & ~CLIENT_COMPRESS) \
                                               & ~CLIENT_SSL_VERIFY_SERVER_CERT)
Definition at line 203 of file mysql_com.h.
CLIENT_COMPRESS
#define CLIENT_COMPRESS 32 /* Can use compression protocol */
Definition at line 148 of file mysql_com.h.
CLIENT_CONNECT_WITH_DB
#define CLIENT_CONNECT_WITH_DB 8 /* One can specify db on connect */
Definition at line 146 of file mysql_com.h.
CLIENT_FOUND_ROWS
#define CLIENT_FOUND_ROWS 2 /* Found instead of affected rows */
Definition at line 144 of file mysql_com.h.
CLIENT_IGNORE_SIGPIPE
#define CLIENT_IGNORE_SIGPIPE 4096 /* IGNORE sigpipes */
Definition at line 155 of file mysql_com.h.
CLIENT_IGNORE_SPACE
#define CLIENT_IGNORE_SPACE 256 /* Ignore spaces before '(' */
Definition at line 151 of file mysql_com.h.
CLIENT_INTERACTIVE
#define CLIENT_INTERACTIVE 1024 /* This is an interactive client */
Definition at line 153 of file mysql_com.h.
CLIENT_LOCAL_FILES
#define CLIENT_LOCAL_FILES 128 /* Can use LOAD DATA LOCAL */
Definition at line 150 of file mysql_com.h.
CLIENT_LONG_FLAG
#define CLIENT_LONG_FLAG 4 /* Get all column flags */
Definition at line 145 of file mysql_com.h.
CLIENT_LONG_PASSWORD
#define CLIENT_LONG_PASSWORD 1 /* new more secure passwords */
Definition at line 143 of file mysql_com.h.
CLIENT_MULTI_QUERIES
#define CLIENT_MULTI_QUERIES CLIENT_MULTI_STATEMENTS
Definition at line 359 of file mysql_com.h.
CLIENT_MULTI_RESULTS
#define CLIENT_MULTI_RESULTS (1UL << 17) /* Enable/disable multi-results */
Definition at line 160 of file mysql_com.h.
CLIENT_MULTI_STATEMENTS
#define CLIENT_MULTI_STATEMENTS (1UL << 16) /* Enable/disable multi-stmt support */
Definition at line 159 of file mysql_com.h.
CLIENT_NO_SCHEMA
#define CLIENT_NO_SCHEMA 16 /* Don't allow database.table.column */
Definition at line 147 of file mysql_com.h.
CLIENT_ODBC
#define CLIENT_ODBC 64 /* Odbc client */
Definition at line 149 of file mysql_com.h.
CLIENT_PLUGIN_AUTH
#define CLIENT_PLUGIN_AUTH (1UL << 19) /* Client supports plugin authentication */
Definition at line 163 of file mysql_com.h.
CLIENT_PROTOCOL_41
#define CLIENT_PROTOCOL_41 512 /* New 4.1 protocol */
Definition at line 152 of file mysql_com.h.
CLIENT_PS_MULTI_RESULTS
#define CLIENT_PS_MULTI_RESULTS (1UL << 18) /* Multi-results in PS-protocol */
Definition at line 161 of file mysql_com.h.
CLIENT_REMEMBER_OPTIONS
#define CLIENT_REMEMBER_OPTIONS (1UL << 31)
Definition at line 166 of file mysql_com.h.
CLIENT_RESERVED
#define CLIENT_RESERVED 16384 /* Old flag for 4.1 protocol */
Definition at line 157 of file mysql_com.h.
CLIENT_SECURE_CONNECTION
#define CLIENT_SECURE_CONNECTION 32768 /* New 4.1 authentication */
Definition at line 158 of file mysql_com.h.
CLIENT_SSL
#define CLIENT_SSL 2048 /* Switch to SSL after handshake */
Definition at line 154 of file mysql_com.h.
CLIENT_SSL_VERIFY_SERVER_CERT
#define CLIENT_SSL_VERIFY_SERVER_CERT (1UL << 30)
Definition at line 165 of file mysql_com.h.
CLIENT_TRANSACTIONS
#define CLIENT_TRANSACTIONS 8192 /* Client knows about transactions */
Definition at line 156 of file mysql_com.h.
COLUMN_COMMENT_MAXLEN
#define COLUMN_COMMENT_MAXLEN 1024
Definition at line 40 of file mysql_com.h.
COMP_HEADER_SIZE
#define COMP_HEADER_SIZE 3 /* compression header extra size */
Definition at line 511 of file mysql_com.h.
ENUM_FLAG
#define ENUM_FLAG 256 /* field is an enum */
Definition at line 102 of file mysql_com.h.
FIELD_IN_ADD_INDEX
#define FIELD_IN_ADD_INDEX (1<< 20) /* Intern: Field used in ADD INDEX */
Definition at line 115 of file mysql_com.h.
FIELD_IN_PART_FUNC_FLAG
#define FIELD_IN_PART_FUNC_FLAG (1 << 19)/* Field part of partition func */
Definition at line 114 of file mysql_com.h.
FIELD_IS_RENAMED
#define FIELD_IS_RENAMED (1<< 21) /* Intern: Field is being renamed */
Definition at line 116 of file mysql_com.h.
FIELD_TYPE_BIT
#define FIELD_TYPE_BIT MYSQL_TYPE_BIT
Definition at line 387 of file mysql_com.h.
FIELD_TYPE_BLOB
#define FIELD_TYPE_BLOB MYSQL_TYPE_BLOB
Definition at line 381 of file mysql_com.h.
FIELD_TYPE_CHAR
#define FIELD_TYPE_CHAR MYSQL_TYPE_TINY
Definition at line 384 of file mysql_com.h.
FIELD_TYPE_DATE
#define FIELD_TYPE_DATE MYSQL_TYPE_DATE
Definition at line 371 of file mysql_com.h.
FIELD_TYPE_DATETIME
#define FIELD_TYPE_DATETIME MYSQL_TYPE_DATETIME
Definition at line 373 of file mysql_com.h.
FIELD_TYPE_DECIMAL
#define FIELD_TYPE_DECIMAL MYSQL_TYPE_DECIMAL
Definition at line 360 of file mysql_com.h.
FIELD_TYPE_DOUBLE
#define FIELD_TYPE_DOUBLE MYSQL_TYPE_DOUBLE
Definition at line 366 of file mysql_com.h.
FIELD_TYPE_ENUM
#define FIELD_TYPE_ENUM MYSQL_TYPE_ENUM
Definition at line 376 of file mysql_com.h.
FIELD_TYPE_FLOAT
#define FIELD_TYPE_FLOAT MYSQL_TYPE_FLOAT
Definition at line 365 of file mysql_com.h.
FIELD_TYPE_GEOMETRY
#define FIELD_TYPE_GEOMETRY MYSQL_TYPE_GEOMETRY
Definition at line 386 of file mysql_com.h.
FIELD_TYPE_INT24
#define FIELD_TYPE_INT24 MYSQL_TYPE_INT24
Definition at line 370 of file mysql_com.h.
FIELD_TYPE_INTERVAL
#define FIELD_TYPE_INTERVAL MYSQL_TYPE_ENUM
Definition at line 385 of file mysql_com.h.
FIELD_TYPE_LONG
#define FIELD_TYPE_LONG MYSQL_TYPE_LONG
Definition at line 364 of file mysql_com.h.
FIELD_TYPE_LONG_BLOB
#define FIELD_TYPE_LONG_BLOB MYSQL_TYPE_LONG_BLOB
Definition at line 380 of file mysql_com.h.
FIELD_TYPE_LONGLONG
#define FIELD_TYPE_LONGLONG MYSQL_TYPE_LONGLONG
Definition at line 369 of file mysql_com.h.
FIELD_TYPE_MEDIUM_BLOB
#define FIELD_TYPE_MEDIUM_BLOB MYSQL_TYPE_MEDIUM_BLOB
Definition at line 379 of file mysql_com.h.
FIELD_TYPE_NEWDATE
#define FIELD_TYPE_NEWDATE MYSQL_TYPE_NEWDATE
Definition at line 375 of file mysql_com.h.
FIELD_TYPE_NEWDECIMAL
#define FIELD_TYPE_NEWDECIMAL MYSQL_TYPE_NEWDECIMAL
Definition at line 361 of file mysql_com.h.
FIELD_TYPE_NULL
#define FIELD_TYPE_NULL MYSQL_TYPE_NULL
Definition at line 367 of file mysql_com.h.
FIELD_TYPE_SET
#define FIELD_TYPE_SET MYSQL_TYPE_SET
Definition at line 377 of file mysql_com.h.
FIELD_TYPE_SHORT
#define FIELD_TYPE_SHORT MYSQL_TYPE_SHORT
Definition at line 363 of file mysql_com.h.
FIELD_TYPE_STRING
#define FIELD_TYPE_STRING MYSQL_TYPE_STRING
Definition at line 383 of file mysql_com.h.
FIELD_TYPE_TIME
#define FIELD_TYPE_TIME MYSQL_TYPE_TIME
Definition at line 372 of file mysql_com.h.
FIELD_TYPE_TIMESTAMP
#define FIELD_TYPE_TIMESTAMP MYSQL_TYPE_TIMESTAMP
Definition at line 368 of file mysql_com.h.
FIELD_TYPE_TINY
#define FIELD_TYPE_TINY MYSQL_TYPE_TINY
Definition at line 362 of file mysql_com.h.
FIELD_TYPE_TINY_BLOB
#define FIELD_TYPE_TINY_BLOB MYSQL_TYPE_TINY_BLOB
Definition at line 378 of file mysql_com.h.
FIELD_TYPE_VAR_STRING
#define FIELD_TYPE_VAR_STRING MYSQL_TYPE_VAR_STRING
Definition at line 382 of file mysql_com.h.
FIELD_TYPE_YEAR
#define FIELD_TYPE_YEAR MYSQL_TYPE_YEAR
Definition at line 374 of file mysql_com.h.
GET_FIXED_FIELDS_FLAG
#define GET_FIXED_FIELDS_FLAG (1 << 18) /* Used to get fields in item tree */
Definition at line 113 of file mysql_com.h.
GROUP_FLAG
#define GROUP_FLAG 32768 /* Intern: Group field */
Definition at line 110 of file mysql_com.h.
HOSTNAME_LENGTH
#define HOSTNAME_LENGTH 60
Definition at line 23 of file mysql_com.h.
INDEX_COMMENT_MAXLEN
#define INDEX_COMMENT_MAXLEN 1024
Definition at line 41 of file mysql_com.h.
LOCAL_HOST
#define LOCAL_HOST "localhost"
Definition at line 51 of file mysql_com.h.
LOCAL_HOST_NAMEDPIPE
#define LOCAL_HOST_NAMEDPIPE "."
Definition at line 52 of file mysql_com.h.
MAX_BIGINT_WIDTH
#define MAX_BIGINT_WIDTH 20 /* Max width for a LONGLONG */
Definition at line 277 of file mysql_com.h.
MAX_BLOB_WIDTH
#define MAX_BLOB_WIDTH 16777216 /* Default width for blob */
Definition at line 279 of file mysql_com.h.
MAX_CHAR_WIDTH
#define MAX_CHAR_WIDTH 255 /* Max length for a CHAR colum */
Definition at line 278 of file mysql_com.h.
MAX_INT_WIDTH
#define MAX_INT_WIDTH 10 /* Max width for a LONG w.o. sign */
Definition at line 276 of file mysql_com.h.
MAX_MEDIUMINT_WIDTH
#define MAX_MEDIUMINT_WIDTH 8 /* Max width for a INT24 w.o. sign */
Definition at line 275 of file mysql_com.h.
MAX_SMALLINT_WIDTH
#define MAX_SMALLINT_WIDTH 5 /* Max width for a SHORT w.o. sign */
Definition at line 274 of file mysql_com.h.
MAX_TINYINT_WIDTH
#define MAX_TINYINT_WIDTH 3 /* Max width for a TINY w.o. sign */
Definition at line 273 of file mysql_com.h.
MULTIPLE_KEY_FLAG
#define MULTIPLE_KEY_FLAG 8 /* Field is part of a key */
Definition at line 95 of file mysql_com.h.
MYSQL_AUTODETECT_CHARSET_NAME
#define MYSQL_AUTODETECT_CHARSET_NAME "auto"
Definition at line 30 of file mysql_com.h.
MYSQL_ERRMSG_SIZE
#define MYSQL_ERRMSG_SIZE 512
Definition at line 262 of file mysql_com.h.
MYSQL_LONG_DATA_HEADER
#define MYSQL_LONG_DATA_HEADER 6
Definition at line 567 of file mysql_com.h.
MYSQL_SHUTDOWN_KILLABLE_CONNECT
#define MYSQL_SHUTDOWN_KILLABLE_CONNECT (unsigned char)(1 << 0)
Definition at line 393 of file mysql_com.h.
MYSQL_SHUTDOWN_KILLABLE_LOCK_TABLE
#define MYSQL_SHUTDOWN_KILLABLE_LOCK_TABLE (unsigned char)(1 << 2)
Definition at line 395 of file mysql_com.h.
MYSQL_SHUTDOWN_KILLABLE_TRANS
#define MYSQL_SHUTDOWN_KILLABLE_TRANS (unsigned char)(1 << 1)
Definition at line 394 of file mysql_com.h.
MYSQL_SHUTDOWN_KILLABLE_UPDATE
#define MYSQL_SHUTDOWN_KILLABLE_UPDATE (unsigned char)(1 << 3)
Definition at line 396 of file mysql_com.h.
MYSQL_STMT_HEADER
#define MYSQL_STMT_HEADER 4
Definition at line 566 of file mysql_com.h.
NAME_CHAR_LEN
#define NAME_CHAR_LEN 64 /* Field/table name length */
Definition at line 25 of file mysql_com.h.
NAME_LEN
#define NAME_LEN (NAME_CHAR_LEN*SYSTEM_CHARSET_MBMAXLEN)
Definition at line 27 of file mysql_com.h.
NET_HEADER_SIZE
#define NET_HEADER_SIZE 4 /* standard header size */
Definition at line 510 of file mysql_com.h.
net_new_transaction
#define net_new_transaction (net) ((net)->pkt_nr=0)
Definition at line 439 of file mysql_com.h.
NET_READ_TIMEOUT
#define NET_READ_TIMEOUT 30 /* Timeout on read */
Definition at line 263 of file mysql_com.h.
NET_WAIT_TIMEOUT
#define NET_WAIT_TIMEOUT 8*60*60 /* Wait for new query */
Definition at line 265 of file mysql_com.h.
NET_WRITE_TIMEOUT
#define NET_WRITE_TIMEOUT 60 /* Timeout on write */
Definition at line 264 of file mysql_com.h.
NO_DEFAULT_VALUE_FLAG
#define NO_DEFAULT_VALUE_FLAG 4096 /* Field doesn't have default value */
Definition at line 106 of file mysql_com.h.
NOT_FIXED_DEC
#define NOT_FIXED_DEC 31
Definition at line 569 of file mysql_com.h.
NOT_NULL_FLAG
#define NOT_NULL_FLAG 1 /* Field can't be NULL */
Definition at line 92 of file mysql_com.h.
NULL_LENGTH
#define NULL_LENGTH ((unsigned long) ~0) /* For net_store_length */
Definition at line 565 of file mysql_com.h.
NUM_FLAG
#define NUM_FLAG 32768 /* Field is num (for clients) */
Definition at line 108 of file mysql_com.h.
ON_UPDATE_NOW_FLAG
#define ON_UPDATE_NOW_FLAG 8192 /* Field is set to NOW on UPDATE */
Definition at line 107 of file mysql_com.h.
ONLY_KILL_QUERY
#define ONLY_KILL_QUERY 1
Definition at line 267 of file mysql_com.h.
packet_error
#define packet_error (~(unsigned long) 0)
Definition at line 334 of file mysql_com.h.
PART_KEY_FLAG
#define PART_KEY_FLAG 16384 /* Intern; Part of some key */
Definition at line 109 of file mysql_com.h.
PRI_KEY_FLAG
#define PRI_KEY_FLAG 2 /* Field is part of a primary key */
Definition at line 93 of file mysql_com.h.
REFRESH_BINARY_LOG
#define REFRESH_BINARY_LOG 1024 /* Flush the binary log */
Definition at line 128 of file mysql_com.h.
REFRESH_DES_KEY_FILE
#define REFRESH_DES_KEY_FILE 0x40000L
Definition at line 140 of file mysql_com.h.
REFRESH_ENGINE_LOG
#define REFRESH_ENGINE_LOG 512 /* Flush all storage engine logs */
Definition at line 127 of file mysql_com.h.
REFRESH_ERROR_LOG
#define REFRESH_ERROR_LOG 256 /* Rotate only the erorr log */
Definition at line 126 of file mysql_com.h.
REFRESH_FAST
#define REFRESH_FAST 32768 /* Intern flag */
Definition at line 135 of file mysql_com.h.
REFRESH_GENERAL_LOG
#define REFRESH_GENERAL_LOG 4096 /* Flush the general log */
Definition at line 130 of file mysql_com.h.
REFRESH_GRANT
#define REFRESH_GRANT 1 /* Refresh grant tables */
Definition at line 118 of file mysql_com.h.
REFRESH_HOSTS
#define REFRESH_HOSTS 8 /* Flush host cache */
Definition at line 121 of file mysql_com.h.
REFRESH_LOG
#define REFRESH_LOG 2 /* Start on new log file */
Definition at line 119 of file mysql_com.h.
REFRESH_MASTER
#define REFRESH_MASTER
Value:
                       128     /* Remove all bin logs in the index
                       and truncate the index */
Definition at line 125 of file mysql_com.h.
REFRESH_QUERY_CACHE
#define REFRESH_QUERY_CACHE 65536
Definition at line 138 of file mysql_com.h.
REFRESH_QUERY_CACHE_FREE
#define REFRESH_QUERY_CACHE_FREE 0x20000L /* pack query cache */
Definition at line 139 of file mysql_com.h.
REFRESH_READ_LOCK
#define REFRESH_READ_LOCK 16384 /* Lock tables for read */
Definition at line 134 of file mysql_com.h.
REFRESH_RELAY_LOG
#define REFRESH_RELAY_LOG 2048 /* Flush the relay log */
Definition at line 129 of file mysql_com.h.
REFRESH_SLAVE
#define REFRESH_SLAVE
Value:
                       64      /* Reset master info and restart slave
                       thread */
Definition at line 124 of file mysql_com.h.
REFRESH_SLOW_LOG
#define REFRESH_SLOW_LOG 8192 /* Flush the slow query log */
Definition at line 131 of file mysql_com.h.
REFRESH_STATUS
#define REFRESH_STATUS 16 /* Flush status variables */
Definition at line 122 of file mysql_com.h.
REFRESH_TABLES
#define REFRESH_TABLES 4 /* close all tables */
Definition at line 120 of file mysql_com.h.
REFRESH_THREADS
#define REFRESH_THREADS 32 /* Flush thread cache */
Definition at line 123 of file mysql_com.h.
REFRESH_USER_RESOURCES
#define REFRESH_USER_RESOURCES 0x80000L
Definition at line 141 of file mysql_com.h.
SCRAMBLE_LENGTH
#define SCRAMBLE_LENGTH 20
Definition at line 85 of file mysql_com.h.
SCRAMBLE_LENGTH_323
#define SCRAMBLE_LENGTH_323 8
Definition at line 86 of file mysql_com.h.
SCRAMBLED_PASSWORD_CHAR_LENGTH
#define SCRAMBLED_PASSWORD_CHAR_LENGTH (SCRAMBLE_LENGTH*2+1)
Definition at line 88 of file mysql_com.h.
SCRAMBLED_PASSWORD_CHAR_LENGTH_323
#define SCRAMBLED_PASSWORD_CHAR_LENGTH_323 (SCRAMBLE_LENGTH_323*2)
Definition at line 89 of file mysql_com.h.
SERVER_MORE_RESULTS_EXISTS
#define SERVER_MORE_RESULTS_EXISTS 8 /* Multi query - next query exists */
Definition at line 216 of file mysql_com.h.
SERVER_PS_OUT_PARAMS
#define SERVER_PS_OUT_PARAMS 4096
To mark ResultSet containing output parameter values.
Definition at line 243 of file mysql_com.h.
SERVER_QUERY_NO_GOOD_INDEX_USED
#define SERVER_QUERY_NO_GOOD_INDEX_USED 16
Definition at line 217 of file mysql_com.h.
SERVER_QUERY_NO_INDEX_USED
#define SERVER_QUERY_NO_INDEX_USED 32
Definition at line 218 of file mysql_com.h.
SERVER_QUERY_WAS_SLOW
#define SERVER_QUERY_WAS_SLOW 2048
Definition at line 238 of file mysql_com.h.
SERVER_STATUS_AUTOCOMMIT
#define SERVER_STATUS_AUTOCOMMIT 2 /* Server in auto_commit mode */
Definition at line 215 of file mysql_com.h.
SERVER_STATUS_CLEAR_SET
#define SERVER_STATUS_CLEAR_SET
Value:
                                 (SERVER_QUERY_NO_GOOD_INDEX_USED| \
                                 SERVER_QUERY_NO_INDEX_USED|\
                                 SERVER_MORE_RESULTS_EXISTS|\
                                 SERVER_STATUS_METADATA_CHANGED |\
                                 SERVER_QUERY_WAS_SLOW |\
                                 SERVER_STATUS_DB_DROPPED |\
                                 SERVER_STATUS_CURSOR_EXISTS|\
                                 SERVER_STATUS_LAST_ROW_SENT)
Server status flags that must be cleared when starting execution of a new SQL statement. Flags from this set are only added to the current server status by the execution engine, but never removed – the execution engine expects them to disappear automagically by the next command.
Definition at line 253 of file mysql_com.h.
SERVER_STATUS_CURSOR_EXISTS
#define SERVER_STATUS_CURSOR_EXISTS 64
The server was able to fulfill the clients request and opened a read-only non-scrollable cursor for a query. This flag comes in reply to COM_STMT_EXECUTE and COM_STMT_FETCH commands.
Definition at line 224 of file mysql_com.h.
SERVER_STATUS_DB_DROPPED
#define SERVER_STATUS_DB_DROPPED 256 /* A database was dropped */
Definition at line 230 of file mysql_com.h.
SERVER_STATUS_IN_TRANS
#define SERVER_STATUS_IN_TRANS 1
Is raised when a multi-statement transaction has been started, either explicitly, by means of BEGIN or COMMIT AND CHAIN, or implicitly, by the first transactional statement, when autocommit=off.
Definition at line 214 of file mysql_com.h.
SERVER_STATUS_LAST_ROW_SENT
#define SERVER_STATUS_LAST_ROW_SENT 128
This flag is sent when a read-only cursor is exhausted, in reply to COM_STMT_FETCH command.
Definition at line 229 of file mysql_com.h.
SERVER_STATUS_METADATA_CHANGED
#define SERVER_STATUS_METADATA_CHANGED 1024
Sent to the client if after a prepared statement reprepare we discovered that the new statement returns a different number of result set columns.
Definition at line 237 of file mysql_com.h.
SERVER_STATUS_NO_BACKSLASH_ESCAPES
#define SERVER_STATUS_NO_BACKSLASH_ESCAPES 512
Definition at line 231 of file mysql_com.h.
SERVER_VERSION_LENGTH
#define SERVER_VERSION_LENGTH 60
Definition at line 32 of file mysql_com.h.
SET_FLAG
#define SET_FLAG 2048 /* field is a set */
Definition at line 105 of file mysql_com.h.
SQLSTATE_LENGTH
#define SQLSTATE_LENGTH 5
Definition at line 33 of file mysql_com.h.
SYSTEM_CHARSET_MBMAXLEN
#define SYSTEM_CHARSET_MBMAXLEN 3
Definition at line 24 of file mysql_com.h.
TABLE_COMMENT_INLINE_MAXLEN
#define TABLE_COMMENT_INLINE_MAXLEN 180 /* pre 6.0: 60 characters */
Definition at line 38 of file mysql_com.h.
TABLE_COMMENT_MAXLEN
#define TABLE_COMMENT_MAXLEN 2048
Definition at line 39 of file mysql_com.h.
TIMESTAMP_FLAG
#define TIMESTAMP_FLAG 1024 /* Field is a timestamp */
Definition at line 104 of file mysql_com.h.
UNIQUE_FLAG
#define UNIQUE_FLAG 65536 /* Intern: Used by sql_yacc */
Definition at line 111 of file mysql_com.h.
UNIQUE_KEY_FLAG
#define UNIQUE_KEY_FLAG 4 /* Field is part of a unique key */
Definition at line 94 of file mysql_com.h.
UNSIGNED_FLAG
#define UNSIGNED_FLAG 32 /* Field is unsigned */
Definition at line 97 of file mysql_com.h.
USER_HOST_BUFF_SIZE
#define USER_HOST_BUFF_SIZE HOSTNAME_LENGTH + USERNAME_LENGTH + 2
Definition at line 49 of file mysql_com.h.
USERNAME_CHAR_LENGTH
#define USERNAME_CHAR_LENGTH 16
Definition at line 26 of file mysql_com.h.
USERNAME_LENGTH
#define USERNAME_LENGTH (USERNAME_CHAR_LENGTH*SYSTEM_CHARSET_MBMAXLEN)
Definition at line 28 of file mysql_com.h.
ZEROFILL_FLAG
#define ZEROFILL_FLAG 64 /* Field is zerofill */
Definition at line 98 of file mysql_com.h.
Typedef Documentation
NET
typedef struct st_net NET
UDF_ARGS
typedef struct st_udf_args UDF_ARGS
UDF_INIT
typedef struct st_udf_init UDF_INIT
Vio
typedef struct st_vio Vio
Definition at line 1 of file mysql_com.h.
Enumeration Type Documentation
enum_cursor_type
enum enum_cursor_type
Enumerator
CURSOR_TYPE_NO_CURSOR
CURSOR_TYPE_READ_ONLY
CURSOR_TYPE_FOR_UPDATE
CURSOR_TYPE_SCROLLABLE
Definition at line 423 of file mysql_com.h.
 {
   CURSOR_TYPE_NO_CURSOR= 0,
   CURSOR_TYPE_READ_ONLY= 1,
   CURSOR_TYPE_FOR_UPDATE= 2,
enum_field_types
enum enum_field_types
Enumerator
MYSQL_TYPE_DECIMAL
MYSQL_TYPE_TINY
MYSQL_TYPE_SHORT
MYSQL_TYPE_LONG
MYSQL_TYPE_FLOAT
MYSQL_TYPE_DOUBLE
MYSQL_TYPE_NULL
MYSQL_TYPE_TIMESTAMP
MYSQL_TYPE_LONGLONG
MYSQL_TYPE_INT24
MYSQL_TYPE_DATE
MYSQL_TYPE_TIME
MYSQL_TYPE_DATETIME
MYSQL_TYPE_YEAR
MYSQL_TYPE_NEWDATE
MYSQL_TYPE_VARCHAR
MYSQL_TYPE_BIT
MYSQL_TYPE_NEWDECIMAL
MYSQL_TYPE_ENUM
MYSQL_TYPE_SET
MYSQL_TYPE_TINY_BLOB
MYSQL_TYPE_MEDIUM_BLOB
MYSQL_TYPE_LONG_BLOB
MYSQL_TYPE_BLOB
MYSQL_TYPE_VAR_STRING
MYSQL_TYPE_STRING
MYSQL_TYPE_GEOMETRY
Definition at line 336 of file mysql_com.h.
                       { MYSQL_TYPE_DECIMAL, MYSQL_TYPE_TINY,
             MYSQL_TYPE_SHORT,  MYSQL_TYPE_LONG,
             MYSQL_TYPE_FLOAT,  MYSQL_TYPE_DOUBLE,
             MYSQL_TYPE_NULL,   MYSQL_TYPE_TIMESTAMP,
             MYSQL_TYPE_LONGLONG,MYSQL_TYPE_INT24,
             MYSQL_TYPE_DATE,   MYSQL_TYPE_TIME,
             MYSQL_TYPE_DATETIME, MYSQL_TYPE_YEAR,
             MYSQL_TYPE_NEWDATE, MYSQL_TYPE_VARCHAR,
             MYSQL_TYPE_BIT,
                         MYSQL_TYPE_NEWDECIMAL=246,
             MYSQL_TYPE_ENUM=247,
             MYSQL_TYPE_SET=248,
             MYSQL_TYPE_TINY_BLOB=249,
             MYSQL_TYPE_MEDIUM_BLOB=250,
             MYSQL_TYPE_LONG_BLOB=251,
             MYSQL_TYPE_BLOB=252,
             MYSQL_TYPE_VAR_STRING=253,
             MYSQL_TYPE_STRING=254,
             MYSQL_TYPE_GEOMETRY=255
enum_mysql_set_option
enum enum_mysql_set_option
Enumerator
MYSQL_OPTION_MULTI_STATEMENTS_ON
MYSQL_OPTION_MULTI_STATEMENTS_OFF
Definition at line 433 of file mysql_com.h.
 {
   MYSQL_OPTION_MULTI_STATEMENTS_ON,
enum_server_command
enum enum_server_command
Enumerator
COM_SLEEP
COM_QUIT
COM_INIT_DB
COM_QUERY
COM_FIELD_LIST
COM_CREATE_DB
COM_DROP_DB
COM_REFRESH
COM_SHUTDOWN
COM_STATISTICS
COM_PROCESS_INFO
COM_CONNECT
COM_PROCESS_KILL
COM_DEBUG
COM_PING
COM_TIME
COM_DELAYED_INSERT
COM_CHANGE_USER
COM_BINLOG_DUMP
COM_TABLE_DUMP
COM_CONNECT_OUT
COM_REGISTER_SLAVE
COM_STMT_PREPARE
COM_STMT_EXECUTE
COM_STMT_SEND_LONG_DATA
COM_STMT_CLOSE
COM_STMT_RESET
COM_SET_OPTION
COM_STMT_FETCH
COM_DAEMON
COM_END
Definition at line 65 of file mysql_com.h.
 {
   COM_SLEEP, COM_QUIT, COM_INIT_DB, COM_QUERY, COM_FIELD_LIST,
   COM_CREATE_DB, COM_DROP_DB, COM_REFRESH, COM_SHUTDOWN, COM_STATISTICS,
   COM_PROCESS_INFO, COM_CONNECT, COM_PROCESS_KILL, COM_DEBUG, COM_PING,
   COM_TIME, COM_DELAYED_INSERT, COM_CHANGE_USER, COM_BINLOG_DUMP,
   COM_TABLE_DUMP, COM_CONNECT_OUT, COM_REGISTER_SLAVE,
   COM_STMT_PREPARE, COM_STMT_EXECUTE, COM_STMT_SEND_LONG_DATA, COM_STMT_CLOSE,
   COM_STMT_RESET, COM_SET_OPTION, COM_STMT_FETCH, COM_DAEMON,
   /* don't forget to update const char *command_name[] in sql_parse.cc */
   /* Must be last */
   COM_END
 };
Item_result
enum Item_result
Enumerator
STRING_RESULT
REAL_RESULT
INT_RESULT
ROW_RESULT
DECIMAL_RESULT
Definition at line 478 of file mysql_com.h.
                  {STRING_RESULT=0, REAL_RESULT, INT_RESULT, ROW_RESULT,
mysql_enum_shutdown_level
enum mysql_enum_shutdown_level
Enumerator
SHUTDOWN_DEFAULT
SHUTDOWN_WAIT_CONNECTIONS
SHUTDOWN_WAIT_TRANSACTIONS
SHUTDOWN_WAIT_UPDATES
SHUTDOWN_WAIT_ALL_BUFFERS
SHUTDOWN_WAIT_CRITICAL_BUFFERS
KILL_CONNECTION
Definition at line 398 of file mysql_com.h.
{
   /*
     We want levels to be in growing order of hardness (because we use number
     comparisons). Note that DEFAULT does not respect the growing property, but
     it's ok.
   */
   SHUTDOWN_DEFAULT = 0,
   /* wait for existing connections to finish */
   SHUTDOWN_WAIT_CONNECTIONS= MYSQL_SHUTDOWN_KILLABLE_CONNECT,
   /* wait for existing trans to finish */
   SHUTDOWN_WAIT_TRANSACTIONS= MYSQL_SHUTDOWN_KILLABLE_TRANS,
   /* wait for existing updates to finish (=> no partial MyISAM update) */
   SHUTDOWN_WAIT_UPDATES= MYSQL_SHUTDOWN_KILLABLE_UPDATE,
   /* flush InnoDB buffers and other storage engines' buffers*/
   SHUTDOWN_WAIT_ALL_BUFFERS= (MYSQL_SHUTDOWN_KILLABLE_UPDATE << 1),
   /* don't flush InnoDB buffers, flush other storage engines' buffers*/
   SHUTDOWN_WAIT_CRITICAL_BUFFERS= (MYSQL_SHUTDOWN_KILLABLE_UPDATE << 1) + 1,
   /* Now the 2 levels of the KILL command */
 #if MYSQL_VERSION_ID >= 50000
   KILL_QUERY= 254,
 #endif
Function Documentation
check_scramble()
my_bool check_scramble (const unsigned char * reply, const char * message, const unsigned char * hash_stage2)
Definition at line 513 of file password.c.
 {
   SHA1_CONTEXT sha1_context;
   uint8 buf[SHA1_HASH_SIZE];
   uint8 hash_stage2_reassured[SHA1_HASH_SIZE];
   mysql_sha1_reset(&sha1_context);
   /* create key to encrypt scramble */
   mysql_sha1_input(&sha1_context, (const uint8 *) message, SCRAMBLE_LENGTH);
   mysql_sha1_input(&sha1_context, hash_stage2, SHA1_HASH_SIZE);
   mysql_sha1_result(&sha1_context, buf);
   /* encrypt scramble */
     my_crypt((char *) buf, buf, scramble_arg, SCRAMBLE_LENGTH);
   /* now buf supposedly contains hash_stage1: so we can get hash_stage2 */
   mysql_sha1_reset(&sha1_context);
   mysql_sha1_input(&sha1_context, buf, SHA1_HASH_SIZE);
   mysql_sha1_result(&sha1_context, hash_stage2_reassured);
   return memcmp(hash_stage2, hash_stage2_reassured, SHA1_HASH_SIZE);
 }
References message(), my_crypt(), mysql_sha1_input(), mysql_sha1_reset(), mysql_sha1_result(), SCRAMBLE_LENGTH, and SHA1_HASH_SIZE.
check_scramble_323()
my_bool check_scramble_323 (const unsigned char * reply, const char * message, unsigned long * salt)
Definition at line 226 of file password.c.
 {
   struct rand_struct rand_st;
   ulong hash_message[2];
   uchar buff[16],*to,extra;                     /* Big enough for check */
   const uchar *pos;
   hash_password(hash_message, message, SCRAMBLE_LENGTH_323);
   randominit(&rand_st,hash_pass[0] ^ hash_message[0],
              hash_pass[1] ^ hash_message[1]);
   to=buff;
   DBUG_ASSERT(sizeof(buff) > SCRAMBLE_LENGTH_323);
   for (pos=scrambled ; *pos && to < buff+sizeof(buff) ; pos++)
     *to++=(char) (floor(my_rnd(&rand_st)*31)+64);
   if (pos-scrambled != SCRAMBLE_LENGTH_323)
     return 1;
   extra=(char) (floor(my_rnd(&rand_st)*31));
   to=buff;
   while (*scrambled)
   {
     if (*scrambled++ != (uchar) (*to++ ^ extra))
       return 1;                                 /* Wrong password */
   }
   return 0;
 }
References DBUG_ASSERT, G3D::floor(), hash_password(), message(), my_rnd(), pos(), randominit(), and SCRAMBLE_LENGTH_323.
create_random_string()
void create_random_string (char * to, unsigned int length, struct rand_struct * rand_st)
Definition at line 316 of file password.c.
 {
   char *end= to + length;
   /* Use pointer arithmetics as it is faster way to do so. */
   for (; to < end; to++)
     *to= (char) (my_rnd(rand_st)*94+33);
   *to= '\0';
 }
References G3D::length(), and my_rnd().
get_salt_from_password()
void get_salt_from_password (unsigned char * res, const char * password)
Definition at line 545 of file password.c.
 {
   hex2octet(hash_stage2, password+1 /* skip '*' */, SHA1_HASH_SIZE * 2);
 }
References hex2octet(), and SHA1_HASH_SIZE.
get_salt_from_password_323()
void get_salt_from_password_323 (unsigned long * res, const char * password)
Definition at line 271 of file password.c.
 {
   res[0]= res[1]= 0;
   if (password)
   {
     while (*password)
     {
       ulong val=0;
       uint i;
       for (i=0 ; i < 8 ; i++)
         val=(val << 4)+char_val(*password++);
       *res++=val;
     }
   }
 }
References char_val().
get_tty_password()
char* get_tty_password (const char * opt_message)
Definition at line 151 of file get_password.c.
 {
 #ifdef HAVE_GETPASS
   char *passbuff;
 #else /* ! HAVE_GETPASS */
   TERMIO org,tmp;
 #endif /* HAVE_GETPASS */
   char buff[80];
   DBUG_ENTER("get_tty_password");
 #ifdef HAVE_GETPASS
   passbuff = getpass(opt_message ? opt_message : "Enter password: ");
   /* copy the password to buff and clear original (static) buffer */
   strnmov(buff, passbuff, sizeof(buff) - 1);
 #ifdef _PASSWORD_LEN
   memset(passbuff, 0, _PASSWORD_LEN);
 #endif
 #else
   if (isatty(fileno(stdout)))
   {
     fputs(opt_message ? opt_message : "Enter password: ",stdout);
     fflush(stdout);
   }
 #if defined(HAVE_TERMIOS_H)
   tcgetattr(fileno(stdin), &org);
   tmp = org;
   tmp.c_lflag &= ~(ECHO | ISIG | ICANON);
   tmp.c_cc[VMIN] = 1;
   tmp.c_cc[VTIME] = 0;
   tcsetattr(fileno(stdin), TCSADRAIN, &tmp);
   get_password(buff, sizeof(buff)-1, fileno(stdin), isatty(fileno(stdout)));
   tcsetattr(fileno(stdin), TCSADRAIN, &org);
 #elif defined(HAVE_TERMIO_H)
   ioctl(fileno(stdin), (int) TCGETA, &org);
   tmp=org;
   tmp.c_lflag &= ~(ECHO | ISIG | ICANON);
   tmp.c_cc[VMIN] = 1;
   tmp.c_cc[VTIME]= 0;
   ioctl(fileno(stdin),(int) TCSETA, &tmp);
   get_password(buff,sizeof(buff)-1,fileno(stdin),isatty(fileno(stdout)));
   ioctl(fileno(stdin),(int) TCSETA, &org);
 #else
   gtty(fileno(stdin), &org);
   tmp=org;
   tmp.sg_flags &= ~ECHO;
   tmp.sg_flags |= RAW;
   stty(fileno(stdin), &tmp);
   get_password(buff,sizeof(buff)-1,fileno(stdin),isatty(fileno(stdout)));
   stty(fileno(stdin), &org);
 #endif
   if (isatty(fileno(stdout)))
     fputc('\n',stdout);
 #endif /* HAVE_GETPASS */
   DBUG_RETURN(my_strdup(buff,MYF(MY_FAE)));
 }
References DBUG_ENTER, DBUG_RETURN, fputs(), get_password(), memset, MY_FAE, my_strdup(), MYF, strnmov(), and TERMIO.
hash_password()
void hash_password (unsigned long * to, const char * password, unsigned int password_len)
Definition at line 118 of file password.c.
 {
   register ulong nr=1345345333L, add=7, nr2=0x12345671L;
   ulong tmp;
   const char *password_end= password + password_len;
   for (; password < password_end; password++)
   {
     if (*password == ' ' || *password == '\t')
       continue;                                 /* skip space in password */
     tmp= (ulong) (uchar) *password;
     nr^= (((nr & 63)+add)*tmp)+ (nr << 8);
     nr2+=(nr2 << 8) ^ nr;
     add+=tmp;
   }
   result[0]=nr & (((ulong) 1L << 31) -1L); /* Don't use sign bit (str2int) */;
   result[1]=nr2 & (((ulong) 1L << 31) -1L);
 }
Referenced by check_scramble_323(), my_make_scrambled_password_323(), and scramble_323().
make_password_from_salt()
void make_password_from_salt (char * to, const unsigned char * hash_stage2)
Definition at line 558 of file password.c.
 {
   *to++= PVERSION41_CHAR;
   octet2hex(to, (const char*) hash_stage2, SHA1_HASH_SIZE);
 }
References octet2hex(), PVERSION41_CHAR, and SHA1_HASH_SIZE.
make_password_from_salt_323()
void make_password_from_salt_323 (char * to, const unsigned long * salt)
Definition at line 296 of file password.c.
 {
   sprintf(to,"%08lx%08lx", salt[0], salt[1]);
 }
References sprintf().
make_scrambled_password()
void make_scrambled_password (char * to, const char * password)
Definition at line 444 of file password.c.
 {
   my_make_scrambled_password(to, password, strlen(password));
 }
References my_make_scrambled_password().
make_scrambled_password_323()
void make_scrambled_password_323 (char * to, const char * password)
Definition at line 167 of file password.c.
 {
   my_make_scrambled_password_323(to, password, strlen(password));
 }
References my_make_scrambled_password_323().
my_connect()
int my_connect (my_socket s, const struct sockaddr * name, unsigned int namelen, unsigned int timeout)
Definition at line 151 of file client.c.
 {
 #if defined(__WIN__)
   DBUG_ENTER("my_connect");
   DBUG_RETURN(connect(fd, (struct sockaddr*) name, namelen));
 #else
   int flags, res, s_err;
   DBUG_ENTER("my_connect");
   DBUG_PRINT("enter", ("fd: %d  timeout: %u", fd, timeout));
   /*
     If they passed us a timeout of zero, we should behave
     exactly like the normal connect() call does.
   */
   if (timeout == 0)
     DBUG_RETURN(connect(fd, (struct sockaddr*) name, namelen));
   flags = fcntl(fd, F_GETFL, 0);      /* Set socket to not block */
 #ifdef O_NONBLOCK
   fcntl(fd, F_SETFL, flags | O_NONBLOCK);  /* and save the flags..  */
 #endif
   DBUG_PRINT("info", ("connecting non-blocking"));
   res= connect(fd, (struct sockaddr*) name, namelen);
   DBUG_PRINT("info", ("connect result: %d  errno: %d", res, errno));
   s_err= errno;         /* Save the error... */
   fcntl(fd, F_SETFL, flags);
   if ((res != 0) && (s_err != EINPROGRESS))
   {
     errno= s_err;           /* Restore it */
     DBUG_RETURN(-1);
   }
   if (res == 0)             /* Connected quickly! */
     DBUG_RETURN(0);
   DBUG_RETURN(wait_for_data(fd, timeout));
 #endif
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, errno, and wait_for_data().
Referenced by CLI_MYSQL_REAL_CONNECT().
my_net_init()
my_bool my_net_init (NET * net, Vio * vio)
Init with packet info.
Definition at line 111 of file net_serv.cc.
 {
   DBUG_ENTER("my_net_init");
   net->vio = vio;
   my_net_local_init(net);           /* Set some limits */
   if (!(net->buff=(uchar*) my_malloc((size_t) net->max_packet+
                      NET_HEADER_SIZE + COMP_HEADER_SIZE,
                      MYF(MY_WME))))
     DBUG_RETURN(1);
   net->buff_end=net->buff+net->max_packet;
   net->error=0; net->return_status=0;
   net->pkt_nr=net->compress_pkt_nr=0;
   net->write_pos=net->read_pos = net->buff;
   net->last_error[0]=0;
   net->compress=0; net->reading_or_writing=0;
   net->where_b = net->remain_in_buf=0;
   net->last_errno=0;
   net->unused= 0;
 #if defined(MYSQL_SERVER) && !defined(EMBEDDED_LIBRARY)
   net->skip_big_packet= FALSE;
 #endif
   if (vio != 0)                 /* If real connection */
   {
     net->fd  = vio_fd(vio);         /* For perl DBI/DBD */
 #if defined(MYSQL_SERVER) && !defined(__WIN__)
     if (!(test_flags & TEST_BLOCKING))
     {
       my_bool old_mode;
       vio_blocking(vio, FALSE, &old_mode);
     }
 #endif
     vio_fastsend(vio);
   }
   DBUG_RETURN(0);
 }
References st_net::buff, st_net::buff_end, COMP_HEADER_SIZE, st_net::compress, st_net::compress_pkt_nr, DBUG_ENTER, DBUG_RETURN, st_net::error, FALSE, st_net::fd, st_net::last_errno, st_net::last_error, st_net::max_packet, my_malloc(), my_net_local_init(), MY_WME, MYF, NET_HEADER_SIZE, st_net::pkt_nr, st_net::read_pos, st_net::reading_or_writing, st_net::remain_in_buf, st_net::return_status, TEST_BLOCKING, st_net::unused, st_net::vio, vio_blocking, vio_fastsend, vio_fd(), st_net::where_b, and st_net::write_pos.
Referenced by CLI_MYSQL_REAL_CONNECT().
my_net_local_init()
void my_net_local_init (NET * net)
Definition at line 1108 of file libmysql.c.
 {
   net->max_packet=   (uint) net_buffer_length;
   my_net_set_read_timeout(net, CLIENT_NET_READ_TIMEOUT);
   my_net_set_write_timeout(net, CLIENT_NET_WRITE_TIMEOUT);
   net->retry_count=  1;
   net->max_packet_size= max(net_buffer_length, max_allowed_packet);
 }
References CLIENT_NET_READ_TIMEOUT, CLIENT_NET_WRITE_TIMEOUT, max, max_allowed_packet, st_net::max_packet, st_net::max_packet_size, my_net_set_read_timeout(), my_net_set_write_timeout(), net_buffer_length, and st_net::retry_count.
Referenced by my_net_init().
my_net_read()
unsigned long my_net_read (NET * net)
Read a packet from the client/server and return it without the internal package header.
If the packet is the first packet of a multi-packet packet (which is indicated by the length of the packet = 0xffffff) then all sub packets are read and concatenated.
If the packet was compressed, its uncompressed and the length of the uncompressed packet is returned.
Returns
The function returns the length of the found packet or packet_error. net->read_pos points to the read data.
Definition at line 1018 of file net_serv.cc.
 {
   size_t len, complen;
   MYSQL_NET_READ_START();
 #ifdef HAVE_COMPRESS
   if (!net->compress)
   {
 #endif
     len = my_real_read(net,&complen);
     if (len == MAX_PACKET_LENGTH)
     {
       /* First packet of a multi-packet.  Concatenate the packets */
       ulong save_pos = net->where_b;
       size_t total_length= 0;
       do
       {
     net->where_b += len;
     total_length += len;
     len = my_real_read(net,&complen);
       } while (len == MAX_PACKET_LENGTH);
       if (len != packet_error)
     len+= total_length;
       net->where_b = save_pos;
     }
     net->read_pos = net->buff + net->where_b;
     if (len != packet_error)
       net->read_pos[len]=0;     /* Safeguard for mysql_use_result */
     MYSQL_NET_READ_DONE(0, len);
     return len;
 #ifdef HAVE_COMPRESS
   }
   else
   {
     /* We are using the compressed protocol */
     ulong buf_length;
     ulong start_of_packet;
     ulong first_packet_offset;
     uint read_length, multi_byte_packet=0;
     if (net->remain_in_buf)
     {
       buf_length= net->buf_length;      /* Data left in old packet */
       first_packet_offset= start_of_packet= (net->buf_length -
                          net->remain_in_buf);
       /* Restore the character that was overwritten by the end 0 */
       net->buff[start_of_packet]= net->save_char;
     }
     else
     {
       /* reuse buffer, as there is nothing in it that we need */
       buf_length= start_of_packet= first_packet_offset= 0;
     }
     for (;;)
     {
       ulong packet_len;
       if (buf_length - start_of_packet >= NET_HEADER_SIZE)
       {
     read_length = uint3korr(net->buff+start_of_packet);
     if (!read_length)
     {
       /* End of multi-byte packet */
       start_of_packet += NET_HEADER_SIZE;
       break;
     }
     if (read_length + NET_HEADER_SIZE <= buf_length - start_of_packet)
     {
       if (multi_byte_packet)
       {
         /* Remove packet header for second packet */
         memmove(net->buff + first_packet_offset + start_of_packet,
             net->buff + first_packet_offset + start_of_packet +
             NET_HEADER_SIZE,
             buf_length - start_of_packet);
         start_of_packet += read_length;
         buf_length -= NET_HEADER_SIZE;
       }
       else
         start_of_packet+= read_length + NET_HEADER_SIZE;
       if (read_length != MAX_PACKET_LENGTH) /* last package */
       {
         multi_byte_packet= 0;       /* No last zero len packet */
         break;
       }
       multi_byte_packet= NET_HEADER_SIZE;
       /* Move data down to read next data packet after current one */
       if (first_packet_offset)
       {
         memmove(net->buff,net->buff+first_packet_offset,
             buf_length-first_packet_offset);
         buf_length-=first_packet_offset;
         start_of_packet -= first_packet_offset;
         first_packet_offset=0;
       }
       continue;
     }
       }
       /* Move data down to read next data packet after current one */
       if (first_packet_offset)
       {
     memmove(net->buff,net->buff+first_packet_offset,
         buf_length-first_packet_offset);
     buf_length-=first_packet_offset;
     start_of_packet -= first_packet_offset;
     first_packet_offset=0;
       }
       net->where_b=buf_length;
       if ((packet_len = my_real_read(net,&complen)) == packet_error)
       {
         MYSQL_NET_READ_DONE(1, 0);
     return packet_error;
       }
       if (my_uncompress(net->buff + net->where_b, packet_len,
             &complen))
       {
     net->error= 2;          /* caller will close socket */
         net->last_errno= ER_NET_UNCOMPRESS_ERROR;
 #ifdef MYSQL_SERVER
     my_error(ER_NET_UNCOMPRESS_ERROR, MYF(0));
 #endif
         MYSQL_NET_READ_DONE(1, 0);
     return packet_error;
       }
       buf_length+= complen;
     }
     net->read_pos=      net->buff+ first_packet_offset + NET_HEADER_SIZE;
     net->buf_length=    buf_length;
     net->remain_in_buf= (ulong) (buf_length - start_of_packet);
     len = ((ulong) (start_of_packet - first_packet_offset) - NET_HEADER_SIZE -
            multi_byte_packet);
     net->save_char= net->read_pos[len]; /* Must be saved */
     net->read_pos[len]=0;       /* Safeguard for mysql_use_result */
   }
 #endif /* HAVE_COMPRESS */
   MYSQL_NET_READ_DONE(0, len);
   return len;
 }
References st_net::buf_length, st_net::buff, st_net::compress, ER_NET_UNCOMPRESS_ERROR, st_net::error, st_net::last_errno, MAX_PACKET_LENGTH, memmove, my_error(), my_real_read(), my_uncompress(), MYF, MYSQL_NET_READ_DONE, MYSQL_NET_READ_START, NET_HEADER_SIZE, packet_error, st_net::read_pos, st_net::remain_in_buf, st_net::save_char, uint3korr, and st_net::where_b.
Referenced by cli_safe_read().
my_net_write()
my_bool my_net_write (NET * net, const uchar * packet, size_t len)
Write a logical packet with packet header.
Format: Packet length (3 bytes), packet number(1 byte) When compression is used a 3 byte compression length is added
Note
If compression is used the original package is modified!
Definition at line 363 of file net_serv.cc.
 {
   uchar buff[NET_HEADER_SIZE];
   int rc;
   if (unlikely(!net->vio)) /* nowhere to write */
     return 0;
   MYSQL_NET_WRITE_START(len);
   /*
     Big packets are handled by splitting them in packets of MAX_PACKET_LENGTH
     length. The last packet is always a packet that is < MAX_PACKET_LENGTH.
     (The last packet may even have a length of 0)
   */
   while (len >= MAX_PACKET_LENGTH)
   {
     const ulong z_size = MAX_PACKET_LENGTH;
     int3store(buff, z_size);
     buff[3]= (uchar) net->pkt_nr++;
     if (net_write_buff(net, buff, NET_HEADER_SIZE) ||
     net_write_buff(net, packet, z_size))
     {
       MYSQL_NET_WRITE_DONE(1);
       return 1;
     }
     packet += z_size;
     len-=     z_size;
   }
   /* Write last packet */
   int3store(buff,len);
   buff[3]= (uchar) net->pkt_nr++;
   if (net_write_buff(net, buff, NET_HEADER_SIZE))
   {
     MYSQL_NET_WRITE_DONE(1);
     return 1;
   }
 #ifndef DEBUG_DATA_PACKETS
   DBUG_DUMP("packet_header", buff, NET_HEADER_SIZE);
 #endif
   rc= test(net_write_buff(net,packet,len));
   MYSQL_NET_WRITE_DONE(rc);
   return rc;
 }
References DBUG_DUMP, if(), int3store, MAX_PACKET_LENGTH, MYSQL_NET_WRITE_DONE, MYSQL_NET_WRITE_START, NET_HEADER_SIZE, net_write_buff(), st_net::pkt_nr, test, unlikely, and st_net::vio.
Referenced by client_mpvio_write_packet(), handle_local_infile(), and send_client_reply_packet().
my_rnd()
double my_rnd (struct rand_struct * rand_st)
Definition at line 100 of file password.c.
 {
   rand_st->seed1=(rand_st->seed1*3+rand_st->seed2) % rand_st->max_value;
   rand_st->seed2=(rand_st->seed1+rand_st->seed2+33) % rand_st->max_value;
   return (((double) rand_st->seed1)/rand_st->max_value_dbl);
 }
References rand_struct::max_value, rand_struct::max_value_dbl, rand_struct::seed1, and rand_struct::seed2.
Referenced by check_scramble_323(), create_random_string(), and scramble_323().
my_thread_end()
void my_thread_end (void)
Definition at line 393 of file my_thr_init.c.
 {
   struct st_my_thread_var *tmp;
   tmp= my_pthread_getspecific(struct st_my_thread_var*,THR_KEY_mysys);
 #ifdef EXTRA_DEBUG_THREADS
   fprintf(stderr,"my_thread_end(): tmp: 0x%lx  pthread_self: 0x%lx  thread_id: %ld\n",
       (long) tmp, (long) pthread_self(), tmp ? (long) tmp->id : 0L);
 #endif
 #ifdef HAVE_PSI_INTERFACE
   /*
     Remove the instrumentation for this thread.
     This must be done before trashing st_my_thread_var,
     because the LF_HASH depends on it.
   */
   if (PSI_server)
     PSI_server->delete_current_thread();
 #endif
   if (tmp && tmp->init)
   {
 #if !defined(DBUG_OFF)
     /* tmp->dbug is allocated inside DBUG library */
     if (tmp->dbug)
     {
       DBUG_POP();
       free(tmp->dbug);
       tmp->dbug=0;
     }
 #endif
 #if !defined(__bsdi__) && !defined(__OpenBSD__)
  /* bsdi and openbsd 3.5 dumps core here */
     mysql_cond_destroy(&tmp->suspend);
 #endif
     mysql_mutex_destroy(&tmp->mutex);
     free(tmp);
     /*
       Decrement counter for number of running threads. We are using this
       in my_thread_global_end() to wait until all threads have called
       my_thread_end and thus freed all memory they have allocated in
       my_thread_init() and DBUG_xxxx
     */
     mysql_mutex_lock(&THR_LOCK_threads);
     DBUG_ASSERT(THR_thread_count != 0);
     if (--THR_thread_count == 0)
       mysql_cond_signal(&THR_COND_threads);
     mysql_mutex_unlock(&THR_LOCK_threads);
   }
   pthread_setspecific(THR_KEY_mysys,0);
 }
my_thread_init()
my_bool my_thread_init (void)
Definition at line 330 of file my_thr_init.c.
 {
   struct st_my_thread_var *tmp;
   my_bool error=0;
 #ifdef EXTRA_DEBUG_THREADS
   fprintf(stderr,"my_thread_init(): thread_id: 0x%lx\n",
           (ulong) pthread_self());
 #endif
   if (my_pthread_getspecific(struct st_my_thread_var *,THR_KEY_mysys))
   {
 #ifdef EXTRA_DEBUG_THREADS
     fprintf(stderr,"my_thread_init() called more than once in thread 0x%lx\n",
             (long) pthread_self());
 #endif
     goto end;
   }
 #ifdef _MSC_VER
   install_sigabrt_handler();
 #endif
   if (!(tmp= (struct st_my_thread_var *) calloc(1, sizeof(*tmp))))
   {
     error= 1;
     goto end;
   }
   pthread_setspecific(THR_KEY_mysys,tmp);
   tmp->pthread_self= pthread_self();
   mysql_mutex_init(key_my_thread_var_mutex, &tmp->mutex, MY_MUTEX_INIT_FAST);
   mysql_cond_init(key_my_thread_var_suspend, &tmp->suspend, NULL);
   tmp->stack_ends_here= (char*)&tmp +
                          STACK_DIRECTION * (long)my_thread_stack_size;
   mysql_mutex_lock(&THR_LOCK_threads);
   tmp->id= ++thread_id;
   ++THR_thread_count;
   mysql_mutex_unlock(&THR_LOCK_threads);
   tmp->init= 1;
 #ifndef DBUG_OFF
   /* Generate unique name for thread */
   (void) my_thread_name();
 #endif
 end:
   return error;
 }
Referenced by my_thread_basic_global_init(), and my_thread_global_init().
mysql_errno_to_sqlstate()
const char* mysql_errno_to_sqlstate (unsigned int mysql_errno)
net_clear()
void net_clear (NET * net, my_bool clear_buffer)
Remove unwanted characters from connection and check if disconnected.
Read from socket until there is nothing more to read. Discard what is read.
If there is anything when to read 'net_clear' is called this normally indicates an error in the protocol.
When connection is properly closed (for TCP it means with a FIN packet), then select() considers a socket "ready to read", in the sense that there's EOF to read, but read() returns 0.
Parameters
net NET handler
clear_buffer if <> 0, then clear all data from comm buff
Definition at line 274 of file net_serv.cc.
 {
 #if !defined(EMBEDDED_LIBRARY)
   size_t count;
   int ready;
 #endif
   DBUG_ENTER("net_clear");
 #if !defined(EMBEDDED_LIBRARY)
   if (clear_buffer)
   {
     while ((ready= net_data_is_ready(net->vio->sd)) > 0)
     {
       /* The socket is ready */
       if ((long) (count= vio_read(net->vio, net->buff,
                                   (size_t) net->max_packet)) > 0)
       {
         DBUG_PRINT("info",("skipped %ld bytes from file: %s",
                            (long) count, vio_description(net->vio)));
 #if defined(EXTRA_DEBUG)
         fprintf(stderr,"Note: net_clear() skipped %ld bytes from file: %s\n",
                 (long) count, vio_description(net->vio));
 #endif
       }
       else
       {
         DBUG_PRINT("info",("socket ready but only EOF to read - disconnected"));
         net->error= 2;
         break;
       }
     }
 #ifdef NET_DATA_IS_READY_CAN_RETURN_MINUS_ONE
     /* 'net_data_is_ready' returned "don't know" */
     if (ready == -1)
     {
       /* Read unblocking to clear net */
       my_bool old_mode;
       if (!vio_blocking(net->vio, FALSE, &old_mode))
       {
         while ((long) (count= vio_read(net->vio, net->buff,
                                        (size_t) net->max_packet)) > 0)
           DBUG_PRINT("info",("skipped %ld bytes from file: %s",
                              (long) count, vio_description(net->vio)));
         vio_blocking(net->vio, TRUE, &old_mode);
       }
     }
 #endif /* NET_DATA_IS_READY_CAN_RETURN_MINUS_ONE */
   }
 #endif /* EMBEDDED_LIBRARY */
   net->pkt_nr=net->compress_pkt_nr=0;       /* Ready for new command */
   net->write_pos=net->buff;
   DBUG_VOID_RETURN;
 }
References st_net::buff, st_net::compress_pkt_nr, count(), DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, st_net::error, FALSE, fprintf(), st_net::max_packet, net_data_is_ready(), st_net::pkt_nr, st_vio::sd, TRUE, st_net::vio, vio_blocking, vio_description(), vio_read, and st_net::write_pos.
Referenced by cli_advanced_command(), cli_stmt_execute(), and mysql_reconnect().
net_end()
void net_end (NET * net)
Definition at line 149 of file net_serv.cc.
 {
   DBUG_ENTER("net_end");
   my_free(net->buff);
   net->buff=0;
   DBUG_VOID_RETURN;
 }
References st_net::buff, DBUG_ENTER, DBUG_VOID_RETURN, and my_free().
Referenced by end_server().
net_flush()
my_bool net_flush (NET * net)
Flush write_buffer if not empty.
Definition at line 331 of file net_serv.cc.
 {
   my_bool error= 0;
   DBUG_ENTER("net_flush");
   if (net->buff != net->write_pos)
   {
     error=test(net_real_write(net, net->buff,
                   (size_t) (net->write_pos - net->buff)));
     net->write_pos=net->buff;
   }
   /* Sync packet number if using compression */
   if (net->compress)
     net->pkt_nr=net->compress_pkt_nr;
   DBUG_RETURN(error);
 }
References st_net::buff, st_net::compress, st_net::compress_pkt_nr, DBUG_ENTER, DBUG_RETURN, error(), net_real_write(), st_net::pkt_nr, test, and st_net::write_pos.
Referenced by client_mpvio_write_packet(), handle_local_infile(), net_write_command(), and send_client_reply_packet().
net_real_write()
int net_real_write (NET * net, const uchar * packet, size_t len)
Read and write one packet using timeouts. If needed, the packet is compressed before sending.
Todo:
TODO is it needed to set this variable if we have no socket
Definition at line 568 of file net_serv.cc.
 {
   size_t length;
   const uchar *pos,*end;
   thr_alarm_t alarmed;
 #ifndef NO_ALARM
   ALARM alarm_buff;
 #endif
   uint retry_count=0;
   my_bool net_blocking = vio_is_blocking(net->vio);
   DBUG_ENTER("net_real_write");
 #if defined(MYSQL_SERVER) && defined(USE_QUERY_CACHE)
   query_cache_insert((char*) packet, len, net->pkt_nr);
 #endif
   if (net->error == 2)
     DBUG_RETURN(-1);                /* socket can't be used */
   net->reading_or_writing=2;
 #ifdef HAVE_COMPRESS
   if (net->compress)
   {
     size_t complen;
     uchar *b;
     uint header_length=NET_HEADER_SIZE+COMP_HEADER_SIZE;
     if (!(b= (uchar*) my_malloc(len + NET_HEADER_SIZE +
                                 COMP_HEADER_SIZE, MYF(MY_WME))))
     {
       net->error= 2;
       net->last_errno= ER_OUT_OF_RESOURCES;
       /* In the server, the error is reported by MY_WME flag. */
       net->reading_or_writing= 0;
       DBUG_RETURN(1);
     }
     memcpy(b+header_length,packet,len);
     if (my_compress(b+header_length, &len, &complen))
       complen=0;
     int3store(&b[NET_HEADER_SIZE],complen);
     int3store(b,len);
     b[3]=(uchar) (net->compress_pkt_nr++);
     len+= header_length;
     packet= b;
   }
 #endif /* HAVE_COMPRESS */
 #ifdef DEBUG_DATA_PACKETS
   DBUG_DUMP("data", packet, len);
 #endif
 #ifndef NO_ALARM
   thr_alarm_init(&alarmed);
   if (net_blocking)
     thr_alarm(&alarmed, net->write_timeout, &alarm_buff);
 #else
   alarmed=0;
   /* Write timeout is set in my_net_set_write_timeout */
 #endif /* NO_ALARM */
   pos= packet;
   end=pos+len;
   while (pos != end)
   {
     if ((long) (length= vio_write(net->vio,pos,(size_t) (end-pos))) <= 0)
     {
       my_bool interrupted = vio_should_retry(net->vio);
 #if !defined(__WIN__)
       if ((interrupted || length == 0) && !thr_alarm_in_use(&alarmed))
       {
         if (!thr_alarm(&alarmed, net->write_timeout, &alarm_buff))
         {                                       /* Always true for client */
       my_bool old_mode;
       while (vio_blocking(net->vio, TRUE, &old_mode) < 0)
       {
         if (vio_should_retry(net->vio) && retry_count++ < net->retry_count)
           continue;
 #ifdef EXTRA_DEBUG
         fprintf(stderr,
             "%s: my_net_write: fcntl returned error %d, aborting thread\n",
             my_progname,vio_errno(net->vio));
 #endif /* EXTRA_DEBUG */
         net->error= 2;                     /* Close socket */
             net->last_errno= ER_NET_PACKET_TOO_LARGE;
 #ifdef MYSQL_SERVER
             my_error(ER_NET_PACKET_TOO_LARGE, MYF(0));
 #endif
         goto end;
       }
       retry_count=0;
       continue;
     }
       }
       else
 #endif /* !defined(__WIN__) */
     if (thr_alarm_in_use(&alarmed) && !thr_got_alarm(&alarmed) &&
         interrupted)
       {
     if (retry_count++ < net->retry_count)
         continue;
 #ifdef EXTRA_DEBUG
       fprintf(stderr, "%s: write looped, aborting thread\n",
           my_progname);
 #endif /* EXTRA_DEBUG */
       }
 #if defined(THREAD_SAFE_CLIENT) && !defined(MYSQL_SERVER)
       if (vio_errno(net->vio) == SOCKET_EINTR)
       {
     DBUG_PRINT("warning",("Interrupted write. Retrying..."));
     continue;
       }
 #endif /* defined(THREAD_SAFE_CLIENT) && !defined(MYSQL_SERVER) */
       net->error= 2;                /* Close socket */
       net->last_errno= (interrupted ? ER_NET_WRITE_INTERRUPTED :
                                ER_NET_ERROR_ON_WRITE);
 #ifdef MYSQL_SERVER
       my_error(net->last_errno, MYF(0));
 #endif /* MYSQL_SERVER */
       break;
     }
     pos+=length;
     update_statistics(thd_increment_bytes_sent(length));
   }
 #ifndef __WIN__
  end:
 #endif
 #ifdef HAVE_COMPRESS
   if (net->compress)
     my_free((void*) packet);
 #endif
   if (thr_alarm_in_use(&alarmed))
   {
     my_bool old_mode;
     thr_end_alarm(&alarmed);
     vio_blocking(net->vio, net_blocking, &old_mode);
   }
   net->reading_or_writing=0;
   DBUG_RETURN(((int) (pos != end)));
 }
References b, COMP_HEADER_SIZE, st_net::compress, st_net::compress_pkt_nr, DBUG_DUMP, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, ER_NET_ERROR_ON_WRITE, ER_NET_PACKET_TOO_LARGE, ER_NET_WRITE_INTERRUPTED, ER_OUT_OF_RESOURCES, st_net::error, fprintf(), int3store, st_net::last_errno, G3D::length(), memcpy, my_compress(), my_error(), my_free(), my_malloc(), my_progname, MY_WME, MYF, NET_HEADER_SIZE, st_net::pkt_nr, pos(), st_net::reading_or_writing, st_net::retry_count, SOCKET_EINTR, thd_increment_bytes_sent, thr_alarm(), thr_alarm_in_use, thr_alarm_init, thr_end_alarm(), thr_got_alarm, TRUE, update_statistics, st_net::vio, vio_blocking, vio_errno, vio_is_blocking, vio_should_retry, vio_write, and st_net::write_timeout.
Referenced by net_flush(), and net_write_buff().
net_realloc()
my_bool net_realloc (NET * net, size_t length)
Realloc the packet buffer.
Definition at line 160 of file net_serv.cc.
 {
   uchar *buff;
   size_t pkt_length;
   DBUG_ENTER("net_realloc");
   DBUG_PRINT("enter",("length: %lu", (ulong) length));
   if (length >= net->max_packet_size)
   {
     DBUG_PRINT("error", ("Packet too large. Max size: %lu",
                          net->max_packet_size));
     /* @todo: 1 and 2 codes are identical. */
     net->error= 1;
     net->last_errno= ER_NET_PACKET_TOO_LARGE;
 #ifdef MYSQL_SERVER
     my_error(ER_NET_PACKET_TOO_LARGE, MYF(0));
 #endif
     DBUG_RETURN(1);
   }
   pkt_length = (length+IO_SIZE-1) & ~(IO_SIZE-1);
   /*
     We must allocate some extra bytes for the end 0 and to be able to
     read big compressed blocks + 1 safety byte since uint3korr() in
     my_real_read() may actually read 4 bytes depending on build flags and
     platform.
   */
   if (!(buff= (uchar*) my_realloc((char*) net->buff, pkt_length +
                                   NET_HEADER_SIZE + COMP_HEADER_SIZE + 1,
                                   MYF(MY_WME))))
   {
     /* @todo: 1 and 2 codes are identical. */
     net->error= 1;
     net->last_errno= ER_OUT_OF_RESOURCES;
     /* In the server the error is reported by MY_WME flag. */
     DBUG_RETURN(1);
   }
   net->buff=net->write_pos=buff;
   net->buff_end=buff+(net->max_packet= (ulong) pkt_length);
   DBUG_RETURN(0);
 }
References st_net::buff, st_net::buff_end, COMP_HEADER_SIZE, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, ER_NET_PACKET_TOO_LARGE, ER_OUT_OF_RESOURCES, st_net::error, IO_SIZE, st_net::last_errno, G3D::length(), st_net::max_packet, st_net::max_packet_size, my_error(), my_realloc(), MY_WME, MYF, NET_HEADER_SIZE, and st_net::write_pos.
Referenced by my_real_read(), and my_realloc_str().
net_write_command()
my_bool net_write_command (NET * net, uchar command, const uchar * header, size_t head_len, const uchar * packet, size_t len)
Send a command to the server.
The reason for having both header and packet is so that libmysql can easy add a header to a special command (like prepared statements) without having to re-alloc the string.
As the command is part of the first data packet, we have to do some data juggling to put the command in there, without having to create a new packet.
This function will split big packets into sub-packets if needed. (Each sub packet can only be 2^24 bytes)
Parameters
net NET handler
command Command in MySQL server (enum enum_server_command)
header Header to write after command
head_len Length of header
packet Query or parameter to query
len Length of packet
Return values
0 ok
1 error
Definition at line 436 of file net_serv.cc.
 {
   size_t length=len+1+head_len;         /* 1 extra byte for command */
   uchar buff[NET_HEADER_SIZE+1];
   uint header_size=NET_HEADER_SIZE+1;
   int rc;
   DBUG_ENTER("net_write_command");
   DBUG_PRINT("enter",("length: %lu", (ulong) len));
   MYSQL_NET_WRITE_START(length);
   buff[4]=command;              /* For first packet */
   if (length >= MAX_PACKET_LENGTH)
   {
     /* Take into account that we have the command in the first header */
     len= MAX_PACKET_LENGTH - 1 - head_len;
     do
     {
       int3store(buff, MAX_PACKET_LENGTH);
       buff[3]= (uchar) net->pkt_nr++;
       if (net_write_buff(net, buff, header_size) ||
       net_write_buff(net, header, head_len) ||
       net_write_buff(net, packet, len))
       {
         MYSQL_NET_WRITE_DONE(1);
     DBUG_RETURN(1);
       }
       packet+= len;
       length-= MAX_PACKET_LENGTH;
       len= MAX_PACKET_LENGTH;
       head_len= 0;
       header_size= NET_HEADER_SIZE;
     } while (length >= MAX_PACKET_LENGTH);
     len=length;                 /* Data left to be written */
   }
   int3store(buff,length);
   buff[3]= (uchar) net->pkt_nr++;
   rc= test(net_write_buff(net, buff, header_size) ||
            (head_len && net_write_buff(net, header, head_len)) ||
            net_write_buff(net, packet, len) || net_flush(net));
   MYSQL_NET_WRITE_DONE(rc);
   DBUG_RETURN(rc);
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, if(), int3store, G3D::length(), MAX_PACKET_LENGTH, MYSQL_NET_WRITE_DONE, MYSQL_NET_WRITE_START, net_flush(), NET_HEADER_SIZE, net_write_buff(), st_net::pkt_nr, and test.
Referenced by cli_advanced_command().
octet2hex()
char* octet2hex (char * to, const char * str, unsigned int len)
Definition at line 343 of file password.c.
 {
   const char *str_end= str + len;
   for (; str != str_end; ++str)
   {
     *to++= _dig_vec_upper[((uchar) *str) >> 4];
     *to++= _dig_vec_upper[((uchar) *str) & 0x0F];
   }
   *to= '\0';
   return to;
 }
References _dig_vec_upper.
Referenced by make_password_from_salt(), and my_make_scrambled_password().
randominit()
void randominit (struct rand_struct * rand_st, unsigned long seed1, unsigned long seed2)
Definition at line 79 of file password.c.
 {                                               /* For mysql 3.21.# */
 #ifdef HAVE_purify
   bzero((char*) rand_st,sizeof(*rand_st));      /* Avoid UMC varnings */
 #endif
   rand_st->max_value= 0x3FFFFFFFL;
   rand_st->max_value_dbl=(double) rand_st->max_value;
   rand_st->seed1=seed1%rand_st->max_value ;
   rand_st->seed2=seed2%rand_st->max_value;
 }
References bzero, rand_struct::max_value, rand_struct::max_value_dbl, rand_struct::seed1, and rand_struct::seed2.
Referenced by check_scramble_323(), and scramble_323().
scramble()
void scramble (char * to, const char * message, const char * password)
Definition at line 468 of file password.c.
 {
   SHA1_CONTEXT sha1_context;
   uint8 hash_stage1[SHA1_HASH_SIZE];
   uint8 hash_stage2[SHA1_HASH_SIZE];
   mysql_sha1_reset(&sha1_context);
   /* stage 1: hash password */
   mysql_sha1_input(&sha1_context, (uint8 *) password, (uint) strlen(password));
   mysql_sha1_result(&sha1_context, hash_stage1);
   /* stage 2: hash stage 1; note that hash_stage2 is stored in the database */
   mysql_sha1_reset(&sha1_context);
   mysql_sha1_input(&sha1_context, hash_stage1, SHA1_HASH_SIZE);
   mysql_sha1_result(&sha1_context, hash_stage2);
   /* create crypt string as sha1(message, hash_stage2) */;
   mysql_sha1_reset(&sha1_context);
   mysql_sha1_input(&sha1_context, (const uint8 *) message, SCRAMBLE_LENGTH);
   mysql_sha1_input(&sha1_context, hash_stage2, SHA1_HASH_SIZE);
   /* xor allows 'from' and 'to' overlap: lets take advantage of it */
   mysql_sha1_result(&sha1_context, (uint8 *) to);
   my_crypt(to, (const uchar *) to, hash_stage1, SCRAMBLE_LENGTH);
 }
References message(), my_crypt(), mysql_sha1_input(), mysql_sha1_reset(), mysql_sha1_result(), SCRAMBLE_LENGTH, and SHA1_HASH_SIZE.
Referenced by native_password_auth_client().
scramble_323()
void scramble_323 (char * to, const char * message, const char * password)
Definition at line 185 of file password.c.
 {
   struct rand_struct rand_st;
   ulong hash_pass[2], hash_message[2];
   if (password && password[0])
   {
     char extra, *to_start=to;
     const char *message_end= message + SCRAMBLE_LENGTH_323;
     hash_password(hash_pass,password, (uint) strlen(password));
     hash_password(hash_message, message, SCRAMBLE_LENGTH_323);
     randominit(&rand_st,hash_pass[0] ^ hash_message[0],
                hash_pass[1] ^ hash_message[1]);
     for (; message < message_end; message++)
       *to++= (char) (floor(my_rnd(&rand_st)*31)+64);
     extra=(char) (floor(my_rnd(&rand_st)*31));
     while (to_start != to)
       *(to_start++)^=extra;
   }
   *to= 0;
 }
References G3D::floor(), hash_password(), message(), my_rnd(), randominit(), and SCRAMBLE_LENGTH_323.
Referenced by old_password_auth_client().