Azerotcore-wotlk: boss_garaxxas::boss_garaxxasAI Struct Reference
boss_garaxxas::boss_garaxxasAI Struct Reference
Public Member Functions
boss_garaxxasAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *who) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from boss_priestess_lackey_commonAI
boss_priestess_lackey_commonAI (Creature *creature, uint32 type)
float GetThreatMod (float dist, float, uint32 health, uint32, Unit *target)
void RecalculateThreat ()
void JustSummoned (Creature *summon) override
void EnterEvadeMode () override
void JustDied (Unit *) override
void KilledUnit (Unit *victim) override
void AttackStart (Unit *victim) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from boss_priestess_lackey_commonAI
InstanceScript * instance
EventMap events
SummonList summons
uint32 actualEventId
uint8 aiType
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 879 of file boss_priestess_delrissa.cpp.
Constructor & Destructor Documentation
boss_garaxxasAI()
boss_garaxxas::boss_garaxxasAI::boss_garaxxasAI (Creature * creature) inline
Definition at line 881 of file boss_priestess_delrissa.cpp.
 : boss_priestess_lackey_commonAI(creature, AI_TYPE_RANGED) {}
Member Function Documentation
EnterCombat()
void boss_garaxxas::boss_garaxxasAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from boss_priestess_lackey_commonAI.
Definition at line 889 of file boss_priestess_delrissa.cpp.
         {
             boss_priestess_lackey_commonAI::EnterCombat(who);
             me->CastSpell(me, SPELL_FREEZING_TRAP, true);
             events.ScheduleEvent(EVENT_SPELL_AIMED_SHOT, 8000);
             events.ScheduleEvent(EVENT_SPELL_SHOOT, 0);
             events.ScheduleEvent(EVENT_SPELL_CONCUSSIVE_SHOT, 6000);
             events.ScheduleEvent(EVENT_SPELL_MULTI_SHOT, 10000);
             events.ScheduleEvent(EVENT_SPELL_WING_CLIP, 4000);
         }
References Unit::CastSpell(), boss_priestess_lackey_commonAI::EnterCombat(), EVENT_SPELL_AIMED_SHOT, EVENT_SPELL_CONCUSSIVE_SHOT, EVENT_SPELL_MULTI_SHOT, EVENT_SPELL_SHOOT, EVENT_SPELL_WING_CLIP, ScriptedAI::me, and SPELL_FREEZING_TRAP.
Reset()
void boss_garaxxas::boss_garaxxasAI::Reset () inline override virtual
Reimplemented from boss_priestess_lackey_commonAI.
Definition at line 883 of file boss_priestess_delrissa.cpp.
         {
             boss_priestess_lackey_commonAI::Reset();
             me->SummonCreature(NPC_SLIVER, 0.0f, 0.0f, 0.0f, 0.0f, TEMPSUMMON_CORPSE_DESPAWN, 0);
         }
References ScriptedAI::me, NPC_SLIVER, boss_priestess_lackey_commonAI::Reset(), WorldObject::SummonCreature(), and TEMPSUMMON_CORPSE_DESPAWN.
UpdateAI()
void boss_garaxxas::boss_garaxxasAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from boss_priestess_lackey_commonAI.
Definition at line 901 of file boss_priestess_delrissa.cpp.
         {
             if (!UpdateVictim())
                 return;
             boss_priestess_lackey_commonAI::UpdateAI(diff);
             switch (actualEventId)
             {
                 case EVENT_SPELL_WING_CLIP:
                     me->CastSpell(me->GetVictim(), SPELL_WING_CLIP, false);
                     events.ScheduleEvent(EVENT_SPELL_WING_CLIP, 4000);
                     break;
                 case EVENT_SPELL_AIMED_SHOT:
                     me->CastSpell(me->GetVictim(), SPELL_AIMED_SHOT, false);
                     events.ScheduleEvent(EVENT_SPELL_AIMED_SHOT, 15000);
                     break;
                 case EVENT_SPELL_CONCUSSIVE_SHOT:
                     me->CastSpell(me->GetVictim(), SPELL_CONCUSSIVE_SHOT, false);
                     events.ScheduleEvent(EVENT_SPELL_CONCUSSIVE_SHOT, 15000);
                     break;
                 case EVENT_SPELL_MULTI_SHOT:
                     me->CastSpell(me->GetVictim(), SPELL_MULTI_SHOT, false);
                     events.ScheduleEvent(EVENT_SPELL_MULTI_SHOT, 10000);
                     break;
                 case EVENT_SPELL_SHOOT:
                     me->CastSpell(me->GetVictim(), DUNGEON_MODE(SPELL_SHOOT_N, SPELL_SHOOT_H), false);
                     events.ScheduleEvent(EVENT_SPELL_SHOOT, 2500);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References boss_priestess_lackey_commonAI::actualEventId, Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DUNGEON_MODE(), EVENT_SPELL_AIMED_SHOT, EVENT_SPELL_CONCUSSIVE_SHOT, EVENT_SPELL_MULTI_SHOT, EVENT_SPELL_SHOOT, EVENT_SPELL_WING_CLIP, Unit::GetVictim(), ScriptedAI::me, SPELL_AIMED_SHOT, SPELL_CONCUSSIVE_SHOT, SPELL_MULTI_SHOT, SPELL_SHOOT_H, SPELL_SHOOT_N, SPELL_WING_CLIP, boss_priestess_lackey_commonAI::UpdateAI(), and CreatureAI::UpdateVictim().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/MagistersTerrace/boss_priestess_delrissa.cpp