Azerotcore-wotlk: src/common/Utilities/Geometry.h File Reference
Geometry.h File Reference
#include "Define.h"
#include <cstdlib>
#include <iostream>
#include <math.h>
Functions
float getAngle (float startX, float startY, float destX, float destY)
float getSlopeAngle (float startX, float startY, float startZ, float destX, float destY, float destZ)
float getSlopeAngleAbs (float startX, float startY, float startZ, float destX, float destY, float destZ)
double getCircleAreaByRadius (double radius)
double getCirclePerimeterByRadius (double radius)
double getCylinderVolume (double height, double radius)
Function Documentation
getAngle()
float getAngle (float startX, float startY, float destX, float destY) inline
Utility library to define some global function for geometric calculations
Definition at line 32 of file Geometry.h.
 {
     auto dx = destX - startX;
     auto dy = destY - startY;
     auto ang = atan2(dy, dx);
     ang = (ang >= 0) ? ang : 2 * float(M_PI) + ang;
     return ang;
 }
Referenced by Position::GetAngle().
getCircleAreaByRadius()
double getCircleAreaByRadius (double radius) inline
Definition at line 53 of file Geometry.h.
 {
     return radius * radius * M_PI;
 }
Referenced by getCylinderVolume(), and getOutOfWater().
getCirclePerimeterByRadius()
double getCirclePerimeterByRadius (double radius) inline
Definition at line 58 of file Geometry.h.
 {
     return radius * M_PI;
 }
getCylinderVolume()
double getCylinderVolume (double height, double radius) inline
Definition at line 63 of file Geometry.h.
 {
     return height * getCircleAreaByRadius(radius);
 }
References getCircleAreaByRadius().
Referenced by getWeight().
getSlopeAngle()
float getSlopeAngle (float startX, float startY, float startZ, float destX, float destY, float destZ) inline
Definition at line 42 of file Geometry.h.
 {
     float floorDist = sqrt(pow(startY - destY, 2.0f) + pow(startX - destX, 2.0f));
     return atan(abs(destZ - startZ) / abs(floorDist));
 }
Referenced by dtQueryFilterExt::getCost(), and getSlopeAngleAbs().
getSlopeAngleAbs()
float getSlopeAngleAbs (float startX, float startY, float startZ, float destX, float destY, float destZ) inline
Definition at line 48 of file Geometry.h.
 {
     return abs(getSlopeAngle(startX, startY, startZ, destX, destY, destZ));
 }
References getSlopeAngle().
Referenced by PathGenerator::GetRequiredHeightToClimb().