Azerotcore-wotlk: deps/argon2/argon2/encoding.c File Reference
encoding.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include "encoding.h"
#include "core.h"
Macros
#define EQ(x, y) ((((0U - ((unsigned)(x) ^ (unsigned)(y))) >> 8) & 0xFF) ^ 0xFF)
#define GT(x, y) ((((unsigned)(y) - (unsigned)(x)) >> 8) & 0xFF)
#define GE(x, y) (GT(y, x) ^ 0xFF)
#define LT(x, y) GT(y, x)
#define LE(x, y) GE(y, x)
#define CC(prefix)
#define CC_opt(prefix, code)
#define DECIMAL(x)
#define DECIMAL_U32(x)
#define BIN(buf, max_len, len)
#define SS(str)
#define SX(x)
#define SB(buf, len)
Functions
static int b64_byte_to_char (unsigned x)
static unsigned b64_char_to_byte (int c)
static size_t to_base64 (char *dst, size_t dst_len, const void *src, size_t src_len)
static const char * from_base64 (void *dst, size_t *dst_len, const char *src)
static const char * decode_decimal (const char *str, unsigned long *v)
int decode_string (argon2_context *ctx, const char *str, argon2_type type)
int encode_string (char *dst, size_t dst_len, argon2_context *ctx, argon2_type type)
size_t b64len (uint32_t len)
size_t numlen (uint32_t num)
Macro Definition Documentation
BIN
#define BIN (buf, max_len, len)
Value:
    do {                                                                       \
        size_t bin_len = (max_len);                                            \
        str = from_base64(buf, &bin_len, str);                                 \
        if (str == NULL || bin_len > UINT32_MAX) {                             \
            return ARGON2_DECODING_FAIL;                                       \
        }                                                                      \
        (len) = (uint32_t)bin_len;                                             \
    } while ((void)0, 0)
CC
#define CC (prefix)
Value:
    do {                                                                       \
        size_t cc_len = strlen(prefix);                                        \
        if (strncmp(str, prefix, cc_len) != 0) {                               \
            return ARGON2_DECODING_FAIL;                                       \
        }                                                                      \
        str += cc_len;                                                         \
    } while ((void)0, 0)
CC_opt
#define CC_opt (prefix, code)
Value:
    do {                                                                       \
        size_t cc_len = strlen(prefix);                                        \
        if (strncmp(str, prefix, cc_len) == 0) {                               \
            str += cc_len;                                                     \
            { code; }                                                          \
        }                                                                      \
    } while ((void)0, 0)
DECIMAL
#define DECIMAL (x)
Value:
    do {                                                                       \
        unsigned long dec_x;                                                   \
        str = decode_decimal(str, &dec_x);                                     \
        if (str == NULL) {                                                     \
            return ARGON2_DECODING_FAIL;                                       \
        }                                                                      \
        (x) = dec_x;                                                           \
    } while ((void)0, 0)
DECIMAL_U32
#define DECIMAL_U32 (x)
Value:
    do {                                                                       \
        unsigned long dec_x;                                                   \
        str = decode_decimal(str, &dec_x);                                     \
        if (str == NULL || dec_x > UINT32_MAX) {                               \
            return ARGON2_DECODING_FAIL;                                       \
        }                                                                      \
        (x) = (uint32_t)dec_x;                                                 \
    } while ((void)0, 0)
EQ
#define EQ (x, y) ((((0U - ((unsigned)(x) ^ (unsigned)(y))) >> 8) & 0xFF) ^ 0xFF)
Definition at line 74 of file encoding.c.
GE
#define GE (x, y) (GT(y, x) ^ 0xFF)
Definition at line 76 of file encoding.c.
GT
#define GT (x, y) ((((unsigned)(y) - (unsigned)(x)) >> 8) & 0xFF)
Definition at line 75 of file encoding.c.
LE
#define LE (x, y) GE(y, x)
Definition at line 78 of file encoding.c.
LT
#define LT (x, y) GT(y, x)
Definition at line 77 of file encoding.c.
SB
#define SB (buf, len)
Value:
    do {                                                                       \
        size_t sb_len = to_base64(dst, dst_len, buf, len);                     \
        if (sb_len == (size_t)-1) {                                            \
            return ARGON2_ENCODING_FAIL;                                       \
        }                                                                      \
        dst += sb_len;                                                         \
        dst_len -= sb_len;                                                     \
    } while ((void)0, 0)
SS
#define SS (str)
Value:
    do {                                                                       \
        size_t pp_len = strlen(str);                                           \
        if (pp_len >= dst_len) {                                               \
            return ARGON2_ENCODING_FAIL;                                       \
        }                                                                      \
        memcpy(dst, str, pp_len + 1);                                          \
        dst += pp_len;                                                         \
        dst_len -= pp_len;                                                     \
    } while ((void)0, 0)
SX
#define SX (x)
Value:
    do {                                                                       \
        char tmp[30];                                                          \
        sprintf(tmp, "%lu", (unsigned long)(x));                               \
        SS(tmp);                                                               \
    } while ((void)0, 0)
Function Documentation
b64_byte_to_char()
static int b64_byte_to_char (unsigned x) static
Definition at line 83 of file encoding.c.
{
     return (LT(x, 26) & (x + 'A')) |
            (GE(x, 26) & LT(x, 52) & (x + ('a' - 26))) |
            (GE(x, 52) & LT(x, 62) & (x + ('0' - 52))) | (EQ(x, 62) & '+') |
            (EQ(x, 63) & '/');
 }
References EQ, GE, LT, and G3D::x.
Referenced by to_base64().
b64_char_to_byte()
static unsigned b64_char_to_byte (int c) static
Definition at line 94 of file encoding.c.
{
     unsigned x;
     x = (GE(c, 'A') & LE(c, 'Z') & (c - 'A')) |
         (GE(c, 'a') & LE(c, 'z') & (c - ('a' - 26))) |
         (GE(c, '0') & LE(c, '9') & (c - ('0' - 52))) | (EQ(c, '+') & 62) |
         (EQ(c, '/') & 63);
     return x | (EQ(x, 0) & (EQ(c, 'A') ^ 0xFF));
 }
References mpq::c, EQ, GE, LE, and G3D::x.
Referenced by from_base64().
b64len()
size_t b64len (uint32_t len)
Definition at line 440 of file encoding.c.
{
     size_t olen = ((size_t)len / 3) << 2;
     switch (len % 3) {
     case 2:
         olen++;
     /* fall through */
     case 1:
         olen += 2;
         break;
     }
     return olen;
 }
Referenced by argon2_encodedlen().
decode_decimal()
static const char* decode_decimal (const char * str, unsigned long * v) static
Definition at line 209 of file encoding.c.
{
     const char *orig;
     unsigned long acc;
     acc = 0;
     for (orig = str;; str++) {
         int c;
         c = *str;
         if (c < '0' || c > '9') {
             break;
         }
         c -= '0';
         if (acc > (ULONG_MAX / 10)) {
             return NULL;
         }
         acc *= 10;
         if ((unsigned long)c > (ULONG_MAX - acc)) {
             return NULL;
         }
         acc += (unsigned long)c;
     }
     if (str == orig || (*orig == '0' && str != (orig + 1))) {
         return NULL;
     }
     *v = acc;
     return str;
 }
References mpq::c, and NULL.
decode_string()
int decode_string (argon2_context * ctx, const char * str, argon2_type type)
Definition at line 258 of file encoding.c.
{
 /* check for prefix */
 #define CC(prefix)                                                             \
     do {                                                                       \
         size_t cc_len = strlen(prefix);                                        \
         if (strncmp(str, prefix, cc_len) != 0) {                               \
             return ARGON2_DECODING_FAIL;                                       \
         }                                                                      \
         str += cc_len;                                                         \
     } while ((void)0, 0)
 /* optional prefix checking with supplied code */
 #define CC_opt(prefix, code)                                                   \
     do {                                                                       \
         size_t cc_len = strlen(prefix);                                        \
         if (strncmp(str, prefix, cc_len) == 0) {                               \
             str += cc_len;                                                     \
             { code; }                                                          \
         }                                                                      \
     } while ((void)0, 0)
 /* Decoding prefix into decimal */
 #define DECIMAL(x)                                                             \
     do {                                                                       \
         unsigned long dec_x;                                                   \
         str = decode_decimal(str, &dec_x);                                     \
         if (str == NULL) {                                                     \
             return ARGON2_DECODING_FAIL;                                       \
         }                                                                      \
         (x) = dec_x;                                                           \
     } while ((void)0, 0)
 /* Decoding prefix into uint32_t decimal */
 #define DECIMAL_U32(x)                                                         \
     do {                                                                       \
         unsigned long dec_x;                                                   \
         str = decode_decimal(str, &dec_x);                                     \
         if (str == NULL || dec_x > UINT32_MAX) {                               \
             return ARGON2_DECODING_FAIL;                                       \
         }                                                                      \
         (x) = (uint32_t)dec_x;                                                 \
     } while ((void)0, 0)
 /* Decoding base64 into a binary buffer */
 #define BIN(buf, max_len, len)                                                 \
     do {                                                                       \
         size_t bin_len = (max_len);                                            \
         str = from_base64(buf, &bin_len, str);                                 \
         if (str == NULL || bin_len > UINT32_MAX) {                             \
             return ARGON2_DECODING_FAIL;                                       \
         }                                                                      \
         (len) = (uint32_t)bin_len;                                             \
     } while ((void)0, 0)
     size_t maxsaltlen = ctx->saltlen;
     size_t maxoutlen = ctx->outlen;
     int validation_result;
     const char* type_string;
     /* We should start with the argon2_type we are using */
     type_string = argon2_type2string(type, 0);
     if (!type_string) {
         return ARGON2_INCORRECT_TYPE;
     }
     CC("$");
     CC(type_string);
     /* Reading the version number if the default is suppressed */
     ctx->version = ARGON2_VERSION_10;
     CC_opt("$v=", DECIMAL_U32(ctx->version));
     CC("$m=");
     DECIMAL_U32(ctx->m_cost);
     CC(",t=");
     DECIMAL_U32(ctx->t_cost);
     CC(",p=");
     DECIMAL_U32(ctx->lanes);
     ctx->threads = ctx->lanes;
     CC("$");
     BIN(ctx->salt, maxsaltlen, ctx->saltlen);
     CC("$");
     BIN(ctx->out, maxoutlen, ctx->outlen);
     /* The rest of the fields get the default values */
     ctx->secret = NULL;
     ctx->secretlen = 0;
     ctx->ad = NULL;
     ctx->adlen = 0;
     ctx->allocate_cbk = NULL;
     ctx->free_cbk = NULL;
     ctx->flags = ARGON2_DEFAULT_FLAGS;
     /* On return, must have valid context */
     validation_result = validate_inputs(ctx);
     if (validation_result != ARGON2_OK) {
         return validation_result;
     }
     /* Can't have any additional characters */
     if (*str == 0) {
         return ARGON2_OK;
     } else {
         return ARGON2_DECODING_FAIL;
     }
 #undef CC
 #undef CC_opt
 #undef DECIMAL
 #undef BIN
 }
References Argon2_Context::ad, Argon2_Context::adlen, Argon2_Context::allocate_cbk, ARGON2_DECODING_FAIL, ARGON2_DEFAULT_FLAGS, ARGON2_INCORRECT_TYPE, ARGON2_OK, argon2_type2string(), ARGON2_VERSION_10, BIN, CC, CC_opt, DECIMAL_U32, Argon2_Context::flags, Argon2_Context::free_cbk, Argon2_Context::lanes, Argon2_Context::m_cost, NULL, Argon2_Context::out, Argon2_Context::outlen, Argon2_Context::salt, Argon2_Context::saltlen, Argon2_Context::secret, Argon2_Context::secretlen, Argon2_Context::t_cost, Argon2_Context::threads, validate_inputs(), and Argon2_Context::version.
Referenced by argon2_verify().
encode_string()
int encode_string (char * dst, size_t dst_len, argon2_context * ctx, argon2_type type)
Definition at line 373 of file encoding.c.
{
 #define SS(str)                                                                \
     do {                                                                       \
         size_t pp_len = strlen(str);                                           \
         if (pp_len >= dst_len) {                                               \
             return ARGON2_ENCODING_FAIL;                                       \
         }                                                                      \
         memcpy(dst, str, pp_len + 1);                                          \
         dst += pp_len;                                                         \
         dst_len -= pp_len;                                                     \
     } while ((void)0, 0)
 #define SX(x)                                                                  \
     do {                                                                       \
         char tmp[30];                                                          \
         sprintf(tmp, "%lu", (unsigned long)(x));                               \
         SS(tmp);                                                               \
     } while ((void)0, 0)
 #define SB(buf, len)                                                           \
     do {                                                                       \
         size_t sb_len = to_base64(dst, dst_len, buf, len);                     \
         if (sb_len == (size_t)-1) {                                            \
             return ARGON2_ENCODING_FAIL;                                       \
         }                                                                      \
         dst += sb_len;                                                         \
         dst_len -= sb_len;                                                     \
     } while ((void)0, 0)
     const char* type_string = argon2_type2string(type, 0);
     int validation_result = validate_inputs(ctx);
     if (!type_string) {
       return ARGON2_ENCODING_FAIL;
     }
     if (validation_result != ARGON2_OK) {
       return validation_result;
     }
     SS("$");
     SS(type_string);
     SS("$v=");
     SX(ctx->version);
     SS("$m=");
     SX(ctx->m_cost);
     SS(",t=");
     SX(ctx->t_cost);
     SS(",p=");
     SX(ctx->lanes);
     SS("$");
     SB(ctx->salt, ctx->saltlen);
     SS("$");
     SB(ctx->out, ctx->outlen);
     return ARGON2_OK;
 #undef SS
 #undef SX
 #undef SB
 }
References ARGON2_ENCODING_FAIL, ARGON2_OK, argon2_type2string(), Argon2_Context::lanes, Argon2_Context::m_cost, Argon2_Context::out, Argon2_Context::outlen, Argon2_Context::salt, Argon2_Context::saltlen, SB, SS, SX, Argon2_Context::t_cost, validate_inputs(), and Argon2_Context::version.
Referenced by argon2_hash().
from_base64()
static const char* from_base64 (void * dst, size_t * dst_len, const char * src) static
Definition at line 161 of file encoding.c.
{
     size_t len;
     unsigned char *buf;
     unsigned acc, acc_len;
     buf = (unsigned char *)dst;
     len = 0;
     acc = 0;
     acc_len = 0;
     for (;;) {
         unsigned d;
         d = b64_char_to_byte(*src);
         if (d == 0xFF) {
             break;
         }
         src++;
         acc = (acc << 6) + d;
         acc_len += 6;
         if (acc_len >= 8) {
             acc_len -= 8;
             if ((len++) >= *dst_len) {
                 return NULL;
             }
             *buf++ = (acc >> acc_len) & 0xFF;
         }
     }
     /*
      * If the input length is equal to 1 modulo 4 (which is
      * invalid), then there will remain 6 unprocessed bits;
      * otherwise, only 0, 2 or 4 bits are buffered. The buffered
      * bits must also all be zero.
      */
     if (acc_len > 4 || (acc & (((unsigned)1 << acc_len) - 1)) != 0) {
         return NULL;
     }
     *dst_len = len;
     return src;
 }
References b64_char_to_byte(), mpq::d, and NULL.
numlen()
size_t numlen (uint32_t num)
Definition at line 455 of file encoding.c.
{
     size_t len = 1;
     while (num >= 10) {
         ++len;
         num = num / 10;
     }
     return len;
 }
Referenced by argon2_encodedlen().
to_base64()
static size_t to_base64 (char * dst, size_t dst_len, const void * src, size_t src_len) static
Definition at line 112 of file encoding.c.
{
     size_t olen;
     const unsigned char *buf;
     unsigned acc, acc_len;
     olen = (src_len / 3) << 2;
     switch (src_len % 3) {
     case 2:
         olen++;
     /* fall through */
     case 1:
         olen += 2;
         break;
     }
     if (dst_len <= olen) {
         return (size_t)-1;
     }
     acc = 0;
     acc_len = 0;
     buf = (const unsigned char *)src;
     while (src_len-- > 0) {
         acc = (acc << 8) + (*buf++);
         acc_len += 8;
         while (acc_len >= 6) {
             acc_len -= 6;
             *dst++ = (char)b64_byte_to_char((acc >> acc_len) & 0x3F);
         }
     }
     if (acc_len > 0) {
         *dst++ = (char)b64_byte_to_char((acc << (6 - acc_len)) & 0x3F);
     }
     *dst++ = 0;
     return olen;
 }
References b64_byte_to_char().