Azerotcore-wotlk: npc_halion_controller::npc_halion_controllerAI Struct Reference
npc_halion_controller::npc_halion_controllerAI Struct Reference
Public Member Functions
npc_halion_controllerAI (Creature *creature)
void Reset () override
void SetData (uint32 id, uint32 value) override
void DoAction (int32 action) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Member Functions
void UpdateCorporeality ()
Private Attributes
EventMap _events
InstanceScript * _instance
uint8 _corporeality
uint32 _materialDamage
uint32 _twilightDamage
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 589 of file boss_halion.cpp.
Constructor & Destructor Documentation
npc_halion_controllerAI()
npc_halion_controller::npc_halion_controllerAI::npc_halion_controllerAI (Creature * creature) inline
Definition at line 591 of file boss_halion.cpp.
                                                     : NullCreatureAI(creature), _instance(creature->GetInstanceScript())
         {
         }
Member Function Documentation
DoAction()
void npc_halion_controller::npc_halion_controllerAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 611 of file boss_halion.cpp.
         {
             if (action == ACTION_INTRO_HALION)
                 _events.ScheduleEvent(EVENT_START_INTRO, 2000);
             else if (action == ACTION_CHECK_CORPOREALITY)
             {
                 _materialDamage = 1;
                 _twilightDamage = 1;
                 _corporeality = 5;
                 _events.ScheduleEvent(EVENT_CHECK_CORPOREALITY, 7000);
             }
             else if (action == ACTION_RESET_ENCOUNTER)
             {
                 _events.Reset();
                 _materialDamage = 1;
                 _twilightDamage = 1;
                 _corporeality = 5;
             }
         }
References _corporeality, _events, _materialDamage, _twilightDamage, ACTION_CHECK_CORPOREALITY, ACTION_INTRO_HALION, ACTION_RESET_ENCOUNTER, EVENT_CHECK_CORPOREALITY, EVENT_START_INTRO, EventMap::Reset(), and EventMap::ScheduleEvent().
Referenced by UpdateCorporeality().
Reset()
void npc_halion_controller::npc_halion_controllerAI::Reset () inline override virtual
Reimplemented from UnitAI.
Definition at line 595 of file boss_halion.cpp.
         {
             _events.Reset();
         }
References _events, and EventMap::Reset().
SetData()
void npc_halion_controller::npc_halion_controllerAI::SetData (uint32 id, uint32 value) inline override virtual
Reimplemented from UnitAI.
Definition at line 600 of file boss_halion.cpp.
         {
             if (_events.GetNextEventTime(EVENT_CHECK_CORPOREALITY) == 0)
                 return;
             if (id == DATA_MATERIAL_DAMAGE_TAKEN)
                 _materialDamage += value;
             else
                 _twilightDamage += value;
         }
References _events, _materialDamage, _twilightDamage, DATA_MATERIAL_DAMAGE_TAKEN, EVENT_CHECK_CORPOREALITY, and EventMap::GetNextEventTime().
UpdateAI()
void npc_halion_controller::npc_halion_controllerAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 631 of file boss_halion.cpp.
         {
             _events.Update(diff);
             switch (_events.ExecuteEvent())
             {
                 // Intro
                 case EVENT_START_INTRO:
                     me->CastSpell(me, SPELL_COSMETIC_FIRE_PILLAR, false);
                     _events.ScheduleEvent(EVENT_INTRO_PROGRESS_1, 5000);
                     break;
                 case EVENT_INTRO_PROGRESS_1:
                     _instance->SetBossState(DATA_HALION_INTRO1, NOT_STARTED);
                     _instance->SetBossState(DATA_HALION_INTRO1, DONE);
                     _events.ScheduleEvent(EVENT_INTRO_PROGRESS_2, 5000);
                     break;
                 case EVENT_INTRO_PROGRESS_2:
                     _instance->SetBossState(DATA_HALION_INTRO2, NOT_STARTED);
                     _instance->SetBossState(DATA_HALION_INTRO2, DONE);
                     _events.ScheduleEvent(EVENT_INTRO_PROGRESS_3, 4000);
                     break;
                 case EVENT_INTRO_PROGRESS_3:
                     _instance->SetBossState(DATA_HALION_INTRO_DONE, NOT_STARTED);
                     _instance->SetBossState(DATA_HALION_INTRO_DONE, DONE);
                     me->CastSpell(me, SPELL_FIERY_EXPLOSION, false);
                     _events.ScheduleEvent(EVENT_INTRO_PROGRESS_4, 500);
                     break;
                 case EVENT_INTRO_PROGRESS_4:
                     if (Creature* halion = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(NPC_HALION)))
                     {
                         halion->SetVisible(true);
                         halion->SetReactState(REACT_AGGRESSIVE);
                         halion->AI()->Talk(SAY_INTRO);
                     }
                     break;
                 case EVENT_TWILIGHT_MENDING:
                     me->CastSpell((Unit*)nullptr, SPELL_TWILIGHT_MENDING, true);
                     break;
                 case EVENT_CHECK_CORPOREALITY:
                     UpdateCorporeality();
                     _events.ScheduleEvent(EVENT_CHECK_CORPOREALITY, 10000);
                     break;
             }
         }
References _events, _instance, Unit::CastSpell(), DATA_HALION_INTRO1, DATA_HALION_INTRO2, DATA_HALION_INTRO_DONE, diff(), DONE, EVENT_CHECK_CORPOREALITY, EVENT_INTRO_PROGRESS_1, EVENT_INTRO_PROGRESS_2, EVENT_INTRO_PROGRESS_3, EVENT_INTRO_PROGRESS_4, EVENT_START_INTRO, EVENT_TWILIGHT_MENDING, EventMap::ExecuteEvent(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), CreatureAI::me, NOT_STARTED, NPC_HALION, REACT_AGGRESSIVE, SAY_INTRO, EventMap::ScheduleEvent(), InstanceScript::SetBossState(), SPELL_COSMETIC_FIRE_PILLAR, SPELL_FIERY_EXPLOSION, SPELL_TWILIGHT_MENDING, EventMap::Update(), and UpdateCorporeality().
UpdateCorporeality()
void npc_halion_controller::npc_halion_controllerAI::UpdateCorporeality () inline private
Definition at line 676 of file boss_halion.cpp.
         {
             if (!_instance->IsEncounterInProgress())
             {
                 DoAction(ACTION_RESET_ENCOUNTER);
                 return;
             }
             uint8 oldValue = _corporeality;
             float damageRatio = float(_materialDamage) / float(_twilightDamage);
             if (_twilightDamage == 1 || _materialDamage == 1)
                 _events.ScheduleEvent(EVENT_TWILIGHT_MENDING, 4000);
             _twilightDamage = 1;
             _materialDamage = 1;
             CorporealityEvent action = CORPOREALITY_NONE;
             if (damageRatio < 0.98f)
                 action = CORPOREALITY_INCREASE;
             else if (1.02f < damageRatio)
                 action = CORPOREALITY_DECREASE;
             else
                 return;
             switch (action)
             {
                 case CORPOREALITY_INCREASE:
                     {
                         if (_corporeality == (MAX_CORPOREALITY_STATE - 1))
                             return;
                         ++_corporeality;
                         break;
                     }
                 case CORPOREALITY_DECREASE:
                     {
                         if (_corporeality == 0)
                             return;
                         --_corporeality;
                         break;
                     }
                 default:
                     break;
             }
             _instance->DoUpdateWorldState(WORLDSTATE_CORPOREALITY_MATERIAL, _corporeality * 10);
             _instance->DoUpdateWorldState(WORLDSTATE_CORPOREALITY_TWILIGHT, 100 - _corporeality * 10);
             if (Creature* twilightHalion = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(NPC_TWILIGHT_HALION)))
             {
                 twilightHalion->RemoveAurasDueToSpell(_corporealityReference[MAX_CORPOREALITY_STATE - 1 - oldValue]);
                 twilightHalion->CastSpell(twilightHalion, _corporealityReference[MAX_CORPOREALITY_STATE - 1 - _corporeality], true);
                 twilightHalion->AI()->Talk(oldValue < _corporeality ? EMOTE_CORPOREALITY_TOT : EMOTE_CORPOREALITY_TIT);
             }
             if (Creature* halion = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(NPC_HALION)))
             {
                 halion->RemoveAurasDueToSpell(_corporealityReference[oldValue]);
                 halion->CastSpell(halion, _corporealityReference[_corporeality], true);
                 halion->AI()->Talk(oldValue > _corporeality ? EMOTE_CORPOREALITY_POT : EMOTE_CORPOREALITY_PIP);
             }
         }
References _corporeality, _corporealityReference, _events, _instance, _materialDamage, _twilightDamage, ACTION_RESET_ENCOUNTER, CORPOREALITY_DECREASE, CORPOREALITY_INCREASE, CORPOREALITY_NONE, DoAction(), InstanceScript::DoUpdateWorldState(), EMOTE_CORPOREALITY_PIP, EMOTE_CORPOREALITY_POT, EMOTE_CORPOREALITY_TIT, EMOTE_CORPOREALITY_TOT, EVENT_TWILIGHT_MENDING, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), InstanceScript::IsEncounterInProgress(), MAX_CORPOREALITY_STATE, CreatureAI::me, NPC_HALION, NPC_TWILIGHT_HALION, EventMap::ScheduleEvent(), WORLDSTATE_CORPOREALITY_MATERIAL, and WORLDSTATE_CORPOREALITY_TWILIGHT.
Referenced by UpdateAI().
Member Data Documentation
_corporeality
uint8 npc_halion_controller::npc_halion_controllerAI::_corporeality private
Definition at line 741 of file boss_halion.cpp.
Referenced by DoAction(), and UpdateCorporeality().
_events
EventMap npc_halion_controller::npc_halion_controllerAI::_events private
Definition at line 739 of file boss_halion.cpp.
Referenced by DoAction(), Reset(), SetData(), UpdateAI(), and UpdateCorporeality().
_instance
InstanceScript* npc_halion_controller::npc_halion_controllerAI::_instance private
Definition at line 740 of file boss_halion.cpp.
Referenced by UpdateAI(), and UpdateCorporeality().
_materialDamage
uint32 npc_halion_controller::npc_halion_controllerAI::_materialDamage private
Definition at line 742 of file boss_halion.cpp.
Referenced by DoAction(), SetData(), and UpdateCorporeality().
_twilightDamage
uint32 npc_halion_controller::npc_halion_controllerAI::_twilightDamage private
Definition at line 743 of file boss_halion.cpp.
Referenced by DoAction(), SetData(), and UpdateCorporeality().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/ChamberOfAspects/RubySanctum/boss_halion.cpp