Azerotcore-wotlk: deps/zlib/example.c File Reference
example.c File Reference
#include "zlib.h"
#include <stdio.h>
Macros
#define TESTFILE "foo.gz"
#define CHECK_ERR(err, msg)
Functions
void test_compress OF ((Byte *compr, uLong comprLen, Byte *uncompr, uLong uncomprLen))
void test_gzio OF ((const char *fname, Byte *uncompr, uLong uncomprLen))
void test_deflate OF ((Byte *compr, uLong comprLen))
void test_flush OF ((Byte *compr, uLong *comprLen))
int main OF ((int argc, char *argv[]))
void test_compress (Byte *compr, uLong comprLen, Byte *uncompr, uLong uncomprLen)
void test_gzio (char *fname, Byte *uncompr, uLong uncomprLen) const
void test_deflate (Byte *compr, uLong comprLen)
void test_inflate (Byte *compr, uLong comprLen, Byte *uncompr, uLong uncomprLen)
void test_large_deflate (Byte *compr, uLong comprLen, Byte *uncompr, uLong uncomprLen)
void test_large_inflate (Byte *compr, uLong comprLen, Byte *uncompr, uLong uncomprLen)
void test_flush (Byte *compr, uLong *comprLen)
void test_sync (Byte *compr, uLong comprLen, Byte *uncompr, uLong uncomprLen)
void test_dict_deflate (Byte *compr, uLong comprLen)
void test_dict_inflate (Byte *compr, uLong comprLen, Byte *uncompr, uLong uncomprLen)
int main (int argc, argv)
Variables
const char hello [] = "hello, hello!"
const char dictionary [] = "hello"
uLong dictId
Macro Definition Documentation
CHECK_ERR
#define CHECK_ERR (err, msg)
Value:
    { \
    if (err != Z_OK) { \
        fprintf(stderr, "%s error: %d\n", msg, err); \
        exit(1); \
    } \
}
Definition at line 22 of file example.c.
TESTFILE
#define TESTFILE "foo.gz"
Definition at line 19 of file example.c.
Function Documentation
main()
int main (int argc, argv)
Definition at line 514 of file example.c.
 {
     Byte *compr, *uncompr;
     uLong comprLen = 10000*sizeof(int); /* don't overflow on MSDOS */
     uLong uncomprLen = comprLen;
     static const char* myVersion = ZLIB_VERSION;
     if (zlibVersion()[0] != myVersion[0]) {
         fprintf(stderr, "incompatible zlib version\n");
         exit(1);
     } else if (strcmp(zlibVersion(), ZLIB_VERSION) != 0) {
         fprintf(stderr, "warning: different zlib version\n");
     }
     printf("zlib version %s = 0x%04x, compile flags = 0x%lx\n",
             ZLIB_VERSION, ZLIB_VERNUM, zlibCompileFlags());
     compr    = (Byte*)calloc((uInt)comprLen, 1);
     uncompr  = (Byte*)calloc((uInt)uncomprLen, 1);
     /* compr and uncompr are cleared to avoid reading uninitialized
      * data and to ensure that uncompr compresses well.
      */
     if (compr == Z_NULL || uncompr == Z_NULL) {
         printf("out of memory\n");
         exit(1);
     }
     test_compress(compr, comprLen, uncompr, uncomprLen);
     test_gzio((argc > 1 ? argv[1] : TESTFILE),
               uncompr, uncomprLen);
     test_deflate(compr, comprLen);
     test_inflate(compr, comprLen, uncompr, uncomprLen);
     test_large_deflate(compr, comprLen, uncompr, uncomprLen);
     test_large_inflate(compr, comprLen, uncompr, uncomprLen);
     test_flush(compr, &comprLen);
     test_sync(compr, comprLen, uncompr, uncomprLen);
     comprLen = uncomprLen;
     test_dict_deflate(compr, comprLen);
     test_dict_inflate(compr, comprLen, uncompr, uncomprLen);
     free(compr);
     free(uncompr);
     return 0;
 }
References fprintf(), printf(), test_compress(), test_deflate(), test_dict_deflate(), test_dict_inflate(), test_flush(), test_gzio(), test_inflate(), test_large_deflate(), test_large_inflate(), test_sync(), TESTFILE, Z_NULL, ZLIB_VERNUM, ZLIB_VERSION, zlibCompileFlags(), and zlibVersion().
OF() [1/5]
void test_flush OF ((Byte *compr, uLong *comprLen))
OF() [2/5]
void test_deflate OF ((Byte *compr, uLong comprLen))
OF() [3/5]
void test_compress OF ((Byte *compr, uLong comprLen, Byte *uncompr, uLong uncomprLen))
OF() [4/5]
void test_gzio OF ((const char *fname, Byte *uncompr, uLong uncomprLen))
OF() [5/5]
int main OF ((int argc, char *argv[]))
test_compress()
void test_compress (Byte * compr, uLong comprLen, Byte * uncompr, uLong uncomprLen)
Definition at line 59 of file example.c.
 {
     int err;
     uLong len = (uLong)strlen(hello)+1;
     err = compress(compr, &comprLen, (const Bytef*)hello, len);
     CHECK_ERR(err, "compress");
     strcpy((char*)uncompr, "garbage");
     err = uncompress(uncompr, &uncomprLen, compr, comprLen);
     CHECK_ERR(err, "uncompress");
     if (strcmp((char*)uncompr, hello)) {
         fprintf(stderr, "bad uncompress\n");
         exit(1);
     } else {
         printf("uncompress(): %s\n", (char *)uncompr);
     }
 }
References CHECK_ERR, compress(), fprintf(), hello, printf(), and uncompress().
Referenced by main().
test_deflate()
void test_deflate (Byte * compr, uLong comprLen)
Definition at line 169 of file example.c.
 {
     z_stream c_stream; /* compression stream */
     int err;
     uLong len = (uLong)strlen(hello)+1;
     c_stream.zalloc = (alloc_func)0;
     c_stream.zfree = (free_func)0;
     c_stream.opaque = (voidpf)0;
     err = deflateInit(&c_stream, Z_DEFAULT_COMPRESSION);
     CHECK_ERR(err, "deflateInit");
     c_stream.next_in  = (Bytef*)hello;
     c_stream.next_out = compr;
     while (c_stream.total_in != len && c_stream.total_out < comprLen) {
         c_stream.avail_in = c_stream.avail_out = 1; /* force small buffers */
         err = deflate(&c_stream, Z_NO_FLUSH);
         CHECK_ERR(err, "deflate");
     }
     /* Finish the stream, still forcing small buffers: */
     for (;;) {
         c_stream.avail_out = 1;
         err = deflate(&c_stream, Z_FINISH);
         if (err == Z_STREAM_END) break;
         CHECK_ERR(err, "deflate");
     }
     err = deflateEnd(&c_stream);
     CHECK_ERR(err, "deflateEnd");
 }
References z_stream_s::avail_in, z_stream_s::avail_out, CHECK_ERR, deflate(), deflateEnd(), deflateInit, hello, z_stream_s::next_in, z_stream_s::next_out, z_stream_s::opaque, z_stream_s::total_in, z_stream_s::total_out, Z_DEFAULT_COMPRESSION, Z_FINISH, Z_NO_FLUSH, Z_STREAM_END, z_stream_s::zalloc, and z_stream_s::zfree.
Referenced by main().
test_dict_deflate()
void test_dict_deflate (Byte * compr, uLong comprLen)
Definition at line 426 of file example.c.
 {
     z_stream c_stream; /* compression stream */
     int err;
     c_stream.zalloc = (alloc_func)0;
     c_stream.zfree = (free_func)0;
     c_stream.opaque = (voidpf)0;
     err = deflateInit(&c_stream, Z_BEST_COMPRESSION);
     CHECK_ERR(err, "deflateInit");
     err = deflateSetDictionary(&c_stream,
                                (const Bytef*)dictionary, sizeof(dictionary));
     CHECK_ERR(err, "deflateSetDictionary");
     dictId = c_stream.adler;
     c_stream.next_out = compr;
     c_stream.avail_out = (uInt)comprLen;
     c_stream.next_in = (Bytef*)hello;
     c_stream.avail_in = (uInt)strlen(hello)+1;
     err = deflate(&c_stream, Z_FINISH);
     if (err != Z_STREAM_END) {
         fprintf(stderr, "deflate should report Z_STREAM_END\n");
         exit(1);
     }
     err = deflateEnd(&c_stream);
     CHECK_ERR(err, "deflateEnd");
 }
References z_stream_s::adler, z_stream_s::avail_in, z_stream_s::avail_out, CHECK_ERR, deflate(), deflateEnd(), deflateInit, deflateSetDictionary(), dictId, dictionary, fprintf(), hello, z_stream_s::next_in, z_stream_s::next_out, z_stream_s::opaque, Z_BEST_COMPRESSION, Z_FINISH, Z_STREAM_END, z_stream_s::zalloc, and z_stream_s::zfree.
Referenced by main().
test_dict_inflate()
void test_dict_inflate (Byte * compr, uLong comprLen, Byte * uncompr, uLong uncomprLen)
Definition at line 463 of file example.c.
 {
     int err;
     z_stream d_stream; /* decompression stream */
     strcpy((char*)uncompr, "garbage");
     d_stream.zalloc = (alloc_func)0;
     d_stream.zfree = (free_func)0;
     d_stream.opaque = (voidpf)0;
     d_stream.next_in  = compr;
     d_stream.avail_in = (uInt)comprLen;
     err = inflateInit(&d_stream);
     CHECK_ERR(err, "inflateInit");
     d_stream.next_out = uncompr;
     d_stream.avail_out = (uInt)uncomprLen;
     for (;;) {
         err = inflate(&d_stream, Z_NO_FLUSH);
         if (err == Z_STREAM_END) break;
         if (err == Z_NEED_DICT) {
             if (d_stream.adler != dictId) {
                 fprintf(stderr, "unexpected dictionary");
                 exit(1);
             }
             err = inflateSetDictionary(&d_stream, (const Bytef*)dictionary,
                                        sizeof(dictionary));
         }
         CHECK_ERR(err, "inflate with dict");
     }
     err = inflateEnd(&d_stream);
     CHECK_ERR(err, "inflateEnd");
     if (strcmp((char*)uncompr, hello)) {
         fprintf(stderr, "bad inflate with dict\n");
         exit(1);
     } else {
         printf("inflate with dictionary: %s\n", (char *)uncompr);
     }
 }
References z_stream_s::adler, z_stream_s::avail_in, z_stream_s::avail_out, CHECK_ERR, dictId, dictionary, fprintf(), hello, inflate(), inflateEnd(), inflateInit, inflateSetDictionary(), z_stream_s::next_in, z_stream_s::next_out, z_stream_s::opaque, printf(), Z_NEED_DICT, Z_NO_FLUSH, Z_STREAM_END, z_stream_s::zalloc, and z_stream_s::zfree.
Referenced by main().
test_flush()
void test_flush (Byte * compr, uLong * comprLen)
Definition at line 344 of file example.c.
 {
     z_stream c_stream; /* compression stream */
     int err;
     uInt len = (uInt)strlen(hello)+1;
     c_stream.zalloc = (alloc_func)0;
     c_stream.zfree = (free_func)0;
     c_stream.opaque = (voidpf)0;
     err = deflateInit(&c_stream, Z_DEFAULT_COMPRESSION);
     CHECK_ERR(err, "deflateInit");
     c_stream.next_in  = (Bytef*)hello;
     c_stream.next_out = compr;
     c_stream.avail_in = 3;
     c_stream.avail_out = (uInt)*comprLen;
     err = deflate(&c_stream, Z_FULL_FLUSH);
     CHECK_ERR(err, "deflate");
     compr[3]++; /* force an error in first compressed block */
     c_stream.avail_in = len - 3;
     err = deflate(&c_stream, Z_FINISH);
     if (err != Z_STREAM_END) {
         CHECK_ERR(err, "deflate");
     }
     err = deflateEnd(&c_stream);
     CHECK_ERR(err, "deflateEnd");
     *comprLen = c_stream.total_out;
 }
References z_stream_s::avail_in, z_stream_s::avail_out, CHECK_ERR, deflate(), deflateEnd(), deflateInit, hello, z_stream_s::next_in, z_stream_s::next_out, z_stream_s::opaque, z_stream_s::total_out, Z_DEFAULT_COMPRESSION, Z_FINISH, Z_FULL_FLUSH, Z_STREAM_END, z_stream_s::zalloc, and z_stream_s::zfree.
Referenced by main().
test_gzio()
void test_gzio (char * fname, Byte * uncompr, uLong uncomprLen) const
Definition at line 85 of file example.c.
 {
 #ifdef NO_GZCOMPRESS
     fprintf(stderr, "NO_GZCOMPRESS -- gz* functions cannot compress\n");
 #else
     int err;
     int len = (int)strlen(hello)+1;
     gzFile file;
     z_off_t pos;
     file = gzopen(fname, "wb");
     if (file == NULL) {
         fprintf(stderr, "gzopen error\n");
         exit(1);
     }
     gzputc(file, 'h');
     if (gzputs(file, "ello") != 4) {
         fprintf(stderr, "gzputs err: %s\n", gzerror(file, &err));
         exit(1);
     }
     if (gzprintf(file, ", %s!", "hello") != 8) {
         fprintf(stderr, "gzprintf err: %s\n", gzerror(file, &err));
         exit(1);
     }
     gzseek(file, 1L, SEEK_CUR); /* add one zero byte */
     gzclose(file);
     file = gzopen(fname, "rb");
     if (file == NULL) {
         fprintf(stderr, "gzopen error\n");
         exit(1);
     }
     strcpy((char*)uncompr, "garbage");
     if (gzread(file, uncompr, (unsigned)uncomprLen) != len) {
         fprintf(stderr, "gzread err: %s\n", gzerror(file, &err));
         exit(1);
     }
     if (strcmp((char*)uncompr, hello)) {
         fprintf(stderr, "bad gzread: %s\n", (char*)uncompr);
         exit(1);
     } else {
         printf("gzread(): %s\n", (char*)uncompr);
     }
     pos = gzseek(file, -8L, SEEK_CUR);
     if (pos != 6 || gztell(file) != pos) {
         fprintf(stderr, "gzseek error, pos=%ld, gztell=%ld\n",
                 (long)pos, (long)gztell(file));
         exit(1);
     }
     if (gzgetc(file) != ' ') {
         fprintf(stderr, "gzgetc error\n");
         exit(1);
     }
     if (gzungetc(' ', file) != ' ') {
         fprintf(stderr, "gzungetc error\n");
         exit(1);
     }
     gzgets(file, (char*)uncompr, (int)uncomprLen);
     if (strlen((char*)uncompr) != 7) { /* " hello!" */
         fprintf(stderr, "gzgets err after gzseek: %s\n", gzerror(file, &err));
         exit(1);
     }
     if (strcmp((char*)uncompr, hello + 6)) {
         fprintf(stderr, "bad gzgets after gzseek\n");
         exit(1);
     } else {
         printf("gzgets() after gzseek: %s\n", (char*)uncompr);
     }
     gzclose(file);
 #endif
 }
References mpq::file, fprintf(), gzclose(), gzerror(), gzgetc(), gzgets(), gzopen(), gzprintf(), gzputc(), gzputs(), gzread(), gzseek(), gztell(), gzungetc(), hello, NULL, pos(), printf(), SEEK_CUR, and z_off_t.
Referenced by main().
test_inflate()
void test_inflate (Byte * compr, uLong comprLen, Byte * uncompr, uLong uncomprLen)
Definition at line 207 of file example.c.
 {
     int err;
     z_stream d_stream; /* decompression stream */
     strcpy((char*)uncompr, "garbage");
     d_stream.zalloc = (alloc_func)0;
     d_stream.zfree = (free_func)0;
     d_stream.opaque = (voidpf)0;
     d_stream.next_in  = compr;
     d_stream.avail_in = 0;
     d_stream.next_out = uncompr;
     err = inflateInit(&d_stream);
     CHECK_ERR(err, "inflateInit");
     while (d_stream.total_out < uncomprLen && d_stream.total_in < comprLen) {
         d_stream.avail_in = d_stream.avail_out = 1; /* force small buffers */
         err = inflate(&d_stream, Z_NO_FLUSH);
         if (err == Z_STREAM_END) break;
         CHECK_ERR(err, "inflate");
     }
     err = inflateEnd(&d_stream);
     CHECK_ERR(err, "inflateEnd");
     if (strcmp((char*)uncompr, hello)) {
         fprintf(stderr, "bad inflate\n");
         exit(1);
     } else {
         printf("inflate(): %s\n", (char *)uncompr);
     }
 }
References z_stream_s::avail_in, z_stream_s::avail_out, CHECK_ERR, fprintf(), hello, inflate(), inflateEnd(), inflateInit, z_stream_s::next_in, z_stream_s::next_out, z_stream_s::opaque, printf(), z_stream_s::total_in, z_stream_s::total_out, Z_NO_FLUSH, Z_STREAM_END, z_stream_s::zalloc, and z_stream_s::zfree.
Referenced by main().
test_large_deflate()
void test_large_deflate (Byte * compr, uLong comprLen, Byte * uncompr, uLong uncomprLen)
Definition at line 248 of file example.c.
 {
     z_stream c_stream; /* compression stream */
     int err;
     c_stream.zalloc = (alloc_func)0;
     c_stream.zfree = (free_func)0;
     c_stream.opaque = (voidpf)0;
     err = deflateInit(&c_stream, Z_BEST_SPEED);
     CHECK_ERR(err, "deflateInit");
     c_stream.next_out = compr;
     c_stream.avail_out = (uInt)comprLen;
     /* At this point, uncompr is still mostly zeroes, so it should compress
      * very well:
      */
     c_stream.next_in = uncompr;
     c_stream.avail_in = (uInt)uncomprLen;
     err = deflate(&c_stream, Z_NO_FLUSH);
     CHECK_ERR(err, "deflate");
     if (c_stream.avail_in != 0) {
         fprintf(stderr, "deflate not greedy\n");
         exit(1);
     }
     /* Feed in already compressed data and switch to no compression: */
     deflateParams(&c_stream, Z_NO_COMPRESSION, Z_DEFAULT_STRATEGY);
     c_stream.next_in = compr;
     c_stream.avail_in = (uInt)comprLen/2;
     err = deflate(&c_stream, Z_NO_FLUSH);
     CHECK_ERR(err, "deflate");
     /* Switch back to compressing mode: */
     deflateParams(&c_stream, Z_BEST_COMPRESSION, Z_FILTERED);
     c_stream.next_in = uncompr;
     c_stream.avail_in = (uInt)uncomprLen;
     err = deflate(&c_stream, Z_NO_FLUSH);
     CHECK_ERR(err, "deflate");
     err = deflate(&c_stream, Z_FINISH);
     if (err != Z_STREAM_END) {
         fprintf(stderr, "deflate should report Z_STREAM_END\n");
         exit(1);
     }
     err = deflateEnd(&c_stream);
     CHECK_ERR(err, "deflateEnd");
 }
References z_stream_s::avail_in, z_stream_s::avail_out, CHECK_ERR, deflate(), deflateEnd(), deflateInit, deflateParams(), fprintf(), z_stream_s::next_in, z_stream_s::next_out, z_stream_s::opaque, Z_BEST_COMPRESSION, Z_BEST_SPEED, Z_DEFAULT_STRATEGY, Z_FILTERED, Z_FINISH, Z_NO_COMPRESSION, Z_NO_FLUSH, Z_STREAM_END, z_stream_s::zalloc, and z_stream_s::zfree.
Referenced by main().
test_large_inflate()
void test_large_inflate (Byte * compr, uLong comprLen, Byte * uncompr, uLong uncomprLen)
Definition at line 303 of file example.c.
 {
     int err;
     z_stream d_stream; /* decompression stream */
     strcpy((char*)uncompr, "garbage");
     d_stream.zalloc = (alloc_func)0;
     d_stream.zfree = (free_func)0;
     d_stream.opaque = (voidpf)0;
     d_stream.next_in  = compr;
     d_stream.avail_in = (uInt)comprLen;
     err = inflateInit(&d_stream);
     CHECK_ERR(err, "inflateInit");
     for (;;) {
         d_stream.next_out = uncompr;            /* discard the output */
         d_stream.avail_out = (uInt)uncomprLen;
         err = inflate(&d_stream, Z_NO_FLUSH);
         if (err == Z_STREAM_END) break;
         CHECK_ERR(err, "large inflate");
     }
     err = inflateEnd(&d_stream);
     CHECK_ERR(err, "inflateEnd");
     if (d_stream.total_out != 2*uncomprLen + comprLen/2) {
         fprintf(stderr, "bad large inflate: %ld\n", d_stream.total_out);
         exit(1);
     } else {
         printf("large_inflate(): OK\n");
     }
 }
References z_stream_s::avail_in, z_stream_s::avail_out, CHECK_ERR, fprintf(), inflate(), inflateEnd(), inflateInit, z_stream_s::next_in, z_stream_s::next_out, z_stream_s::opaque, printf(), z_stream_s::total_out, Z_NO_FLUSH, Z_STREAM_END, z_stream_s::zalloc, and z_stream_s::zfree.
Referenced by main().
test_sync()
void test_sync (Byte * compr, uLong comprLen, Byte * uncompr, uLong uncomprLen)
Definition at line 382 of file example.c.
 {
     int err;
     z_stream d_stream; /* decompression stream */
     strcpy((char*)uncompr, "garbage");
     d_stream.zalloc = (alloc_func)0;
     d_stream.zfree = (free_func)0;
     d_stream.opaque = (voidpf)0;
     d_stream.next_in  = compr;
     d_stream.avail_in = 2; /* just read the zlib header */
     err = inflateInit(&d_stream);
     CHECK_ERR(err, "inflateInit");
     d_stream.next_out = uncompr;
     d_stream.avail_out = (uInt)uncomprLen;
     inflate(&d_stream, Z_NO_FLUSH);
     CHECK_ERR(err, "inflate");
     d_stream.avail_in = (uInt)comprLen-2;   /* read all compressed data */
     err = inflateSync(&d_stream);           /* but skip the damaged part */
     CHECK_ERR(err, "inflateSync");
     err = inflate(&d_stream, Z_FINISH);
     if (err != Z_DATA_ERROR) {
         fprintf(stderr, "inflate should report DATA_ERROR\n");
         /* Because of incorrect adler32 */
         exit(1);
     }
     err = inflateEnd(&d_stream);
     CHECK_ERR(err, "inflateEnd");
     printf("after inflateSync(): hel%s\n", (char *)uncompr);
 }
References z_stream_s::avail_in, z_stream_s::avail_out, CHECK_ERR, fprintf(), inflate(), inflateEnd(), inflateInit, inflateSync(), z_stream_s::next_in, z_stream_s::next_out, z_stream_s::opaque, printf(), Z_DATA_ERROR, Z_FINISH, Z_NO_FLUSH, z_stream_s::zalloc, and z_stream_s::zfree.
Referenced by main().
Variable Documentation
dictId
uLong dictId
Definition at line 35 of file example.c.
Referenced by test_dict_deflate(), and test_dict_inflate().
dictionary
const char dictionary[] = "hello"
Definition at line 34 of file example.c.
Referenced by deflateSetDictionary(), inflateSetDictionary(), test_dict_deflate(), and test_dict_inflate().
hello
const char hello[] = "hello, hello!"
Definition at line 29 of file example.c.
Referenced by test_compress(), test_deflate(), test_dict_deflate(), test_dict_inflate(), test_flush(), test_gzio(), and test_inflate().