Azerotcore-wotlk: Acore::Impl::MPSCQueueIntrusive< T, IntrusiveLink > Class Template Reference
Acore::Impl::MPSCQueueIntrusive< T, IntrusiveLink > Class Template Reference
#include <MPSCQueue.h>
Public Member Functions
MPSCQueueIntrusive ()
~MPSCQueueIntrusive ()
void Enqueue (T *input)
bool Dequeue (T *&result)
Private Member Functions
MPSCQueueIntrusive (MPSCQueueIntrusive const &)=delete
MPSCQueueIntrusive & operator= (MPSCQueueIntrusive const &)=delete
Private Attributes
std::aligned_storage_t< sizeof(T), alignof(T)> _dummy
T * _dummyPtr
std::atomic< T * > _head
std::atomic< T * > _tail
Detailed Description
template<typename T, std::atomic< T * > T::* IntrusiveLink>
class Acore::Impl::MPSCQueueIntrusive< T, IntrusiveLink >
Definition at line 91 of file MPSCQueue.h.
Constructor & Destructor Documentation
MPSCQueueIntrusive() [1/2]
template<typename T , std::atomic< T * > T::* IntrusiveLink> Acore::Impl::MPSCQueueIntrusive< T, IntrusiveLink >::MPSCQueueIntrusive () inline
Definition at line 94 of file MPSCQueue.h.
                              : _dummyPtr(reinterpret_cast<T*>(std::addressof(_dummy))), _head(_dummyPtr), _tail(_dummyPtr)
         {
             // _dummy is constructed from aligned_storage and is intentionally left uninitialized (it might not be default constructible)
             // so we init only its IntrusiveLink here
             std::atomic<T*>* dummyNext = new (&(_dummyPtr->*IntrusiveLink)) std::atomic<T*>();
             dummyNext->store(nullptr, std::memory_order_relaxed);
         }
References Acore::Impl::MPSCQueueIntrusive< T, IntrusiveLink >::_dummyPtr.
~MPSCQueueIntrusive()
template<typename T , std::atomic< T * > T::* IntrusiveLink> Acore::Impl::MPSCQueueIntrusive< T, IntrusiveLink >::~MPSCQueueIntrusive () inline
Definition at line 102 of file MPSCQueue.h.
         {
             T* output;
             while (Dequeue(output))
                 delete output;
         }
References Acore::Impl::MPSCQueueIntrusive< T, IntrusiveLink >::Dequeue().
MPSCQueueIntrusive() [2/2]
template<typename T , std::atomic< T * > T::* IntrusiveLink> Acore::Impl::MPSCQueueIntrusive< T, IntrusiveLink >::MPSCQueueIntrusive (MPSCQueueIntrusive< T, IntrusiveLink > const &) private delete
Member Function Documentation
Dequeue()
template<typename T , std::atomic< T * > T::* IntrusiveLink> bool Acore::Impl::MPSCQueueIntrusive< T, IntrusiveLink >::Dequeue (T *& result) inline
Definition at line 116 of file MPSCQueue.h.
         {
             T* tail = _tail.load(std::memory_order_relaxed);
             T* next = (tail->*IntrusiveLink).load(std::memory_order_acquire);
             if (tail == _dummyPtr)
             {
                 if (!next)
                     return false;
                 _tail.store(next, std::memory_order_release);
                 tail = next;
                 next = (next->*IntrusiveLink).load(std::memory_order_acquire);
             }
             if (next)
             {
                 _tail.store(next, std::memory_order_release);
                 result = tail;
                 return true;
             }
             T* head = _head.load(std::memory_order_acquire);
             if (tail != head)
                 return false;
             Enqueue(_dummyPtr);
             next = (tail->*IntrusiveLink).load(std::memory_order_acquire);
             if (next)
             {
                 _tail.store(next, std::memory_order_release);
                 result = tail;
                 return true;
             }
             return false;
         }
References Acore::Impl::MPSCQueueIntrusive< T, IntrusiveLink >::_dummyPtr, Acore::Impl::MPSCQueueIntrusive< T, IntrusiveLink >::_head, Acore::Impl::MPSCQueueIntrusive< T, IntrusiveLink >::_tail, Acore::Impl::MPSCQueueIntrusive< T, IntrusiveLink >::Enqueue(), and next().
Referenced by Acore::Impl::MPSCQueueIntrusive< T, IntrusiveLink >::~MPSCQueueIntrusive().
Enqueue()
template<typename T , std::atomic< T * > T::* IntrusiveLink> void Acore::Impl::MPSCQueueIntrusive< T, IntrusiveLink >::Enqueue (T * input) inline
Definition at line 109 of file MPSCQueue.h.
         {
             (input->*IntrusiveLink).store(nullptr, std::memory_order_release);
             T* prevHead = _head.exchange(input, std::memory_order_acq_rel);
             (prevHead->*IntrusiveLink).store(input, std::memory_order_release);
         }
References Acore::Impl::MPSCQueueIntrusive< T, IntrusiveLink >::_head.
Referenced by Acore::Impl::MPSCQueueIntrusive< T, IntrusiveLink >::Dequeue().
operator=()
template<typename T , std::atomic< T * > T::* IntrusiveLink> MPSCQueueIntrusive& Acore::Impl::MPSCQueueIntrusive< T, IntrusiveLink >::operator= (MPSCQueueIntrusive< T, IntrusiveLink > const &) private delete
Member Data Documentation
_dummy
template<typename T , std::atomic< T * > T::* IntrusiveLink> std::aligned_storage_t<sizeof(T), alignof(T)> Acore::Impl::MPSCQueueIntrusive< T, IntrusiveLink >::_dummy private
Definition at line 153 of file MPSCQueue.h.
_dummyPtr
template<typename T , std::atomic< T * > T::* IntrusiveLink> T* Acore::Impl::MPSCQueueIntrusive< T, IntrusiveLink >::_dummyPtr private
Definition at line 154 of file MPSCQueue.h.
Referenced by Acore::Impl::MPSCQueueIntrusive< T, IntrusiveLink >::Dequeue(), and Acore::Impl::MPSCQueueIntrusive< T, IntrusiveLink >::MPSCQueueIntrusive().
_head
template<typename T , std::atomic< T * > T::* IntrusiveLink> std::atomic<T*> Acore::Impl::MPSCQueueIntrusive< T, IntrusiveLink >::_head private
Definition at line 155 of file MPSCQueue.h.
Referenced by Acore::Impl::MPSCQueueIntrusive< T, IntrusiveLink >::Dequeue(), and Acore::Impl::MPSCQueueIntrusive< T, IntrusiveLink >::Enqueue().
_tail
template<typename T , std::atomic< T * > T::* IntrusiveLink> std::atomic<T*> Acore::Impl::MPSCQueueIntrusive< T, IntrusiveLink >::_tail private
Definition at line 156 of file MPSCQueue.h.
Referenced by Acore::Impl::MPSCQueueIntrusive< T, IntrusiveLink >::Dequeue().
The documentation for this class was generated from the following file:
src/common/Threading/MPSCQueue.h