Azerotcore-wotlk: Acore::NearestGameObjectTypeInObjectRangeCheck Class Reference
Acore::NearestGameObjectTypeInObjectRangeCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
NearestGameObjectTypeInObjectRangeCheck (WorldObject const &obj, GameobjectTypes type, float range)
bool operator() (GameObject *go)
Private Member Functions
NearestGameObjectTypeInObjectRangeCheck (NearestGameObjectTypeInObjectRangeCheck const &)
Private Attributes
WorldObject const & i_obj
GameobjectTypes i_type
float i_range
Detailed Description
Definition at line 716 of file GridNotifiers.h.
Constructor & Destructor Documentation
NearestGameObjectTypeInObjectRangeCheck() [1/2]
Acore::NearestGameObjectTypeInObjectRangeCheck::NearestGameObjectTypeInObjectRangeCheck (WorldObject const & obj, GameobjectTypes type, float range) inline
Definition at line 719 of file GridNotifiers.h.
 : i_obj(obj), i_type(type), i_range(range) {}
NearestGameObjectTypeInObjectRangeCheck() [2/2]
Acore::NearestGameObjectTypeInObjectRangeCheck::NearestGameObjectTypeInObjectRangeCheck (NearestGameObjectTypeInObjectRangeCheck const &) private
Member Function Documentation
operator()()
bool Acore::NearestGameObjectTypeInObjectRangeCheck::operator() (GameObject * go) inline
Definition at line 720 of file GridNotifiers.h.
         {
             if (go->GetGoType() == i_type && i_obj.IsWithinDistInMap(go, i_range))
             {
                 i_range = i_obj.GetDistance(go);        // use found GO range as new range limit for next check
                 return true;
             }
             return false;
         }
References WorldObject::GetDistance(), GameObject::GetGoType(), i_obj, i_range, i_type, and WorldObject::IsWithinDistInMap().
Member Data Documentation
i_obj
WorldObject const& Acore::NearestGameObjectTypeInObjectRangeCheck::i_obj private
Definition at line 730 of file GridNotifiers.h.
Referenced by operator()().
i_range
float Acore::NearestGameObjectTypeInObjectRangeCheck::i_range private
Definition at line 732 of file GridNotifiers.h.
Referenced by operator()().
i_type
GameobjectTypes Acore::NearestGameObjectTypeInObjectRangeCheck::i_type private
Definition at line 731 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/game/Grids/Notifiers/GridNotifiers.h