Azerotcore-wotlk: npc_spiritual_insight::npc_spiritual_insightAI Struct Reference
npc_spiritual_insight::npc_spiritual_insightAI Struct Reference
Public Member Functions
npc_spiritual_insightAI (Creature *c)
uint8 GetSpeachId ()
void IsSummonedBy (Unit *summoner) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void UpdateAI (uint32) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1356 of file zone_dragonblight.cpp.
Constructor & Destructor Documentation
npc_spiritual_insightAI()
npc_spiritual_insight::npc_spiritual_insightAI::npc_spiritual_insightAI (Creature * c) inline
Definition at line 1358 of file zone_dragonblight.cpp.
 : NullCreatureAI(c) {}
Member Function Documentation
GetSpeachId()
uint8 npc_spiritual_insight::npc_spiritual_insightAI::GetSpeachId () inline
Definition at line 1360 of file zone_dragonblight.cpp.
         {
             if (me->GetDistance2d(2686, 934) < 2.0f)
                 return 0;
             if (me->GetDistance2d(3097, 1037) < 2.0f)
                 return 1;
             if (me->GetDistance2d(3014, 1321) < 2.0f)
                 return 2;
             if (me->GetDistance2d(2854, 1514) < 2.0f)
                 return 3;
             if (me->GetDistance2d(3129, 1556) < 2.0f)
                 return 4;
             return 5;
         }
References WorldObject::GetDistance2d(), and CreatureAI::me.
Referenced by IsSummonedBy().
IsSummonedBy()
void npc_spiritual_insight::npc_spiritual_insightAI::IsSummonedBy (Unit * summoner) inline override virtual
Reimplemented from CreatureAI.
Definition at line 1376 of file zone_dragonblight.cpp.
         {
             if (!summoner || summoner->GetTypeId() != TYPEID_PLAYER)
                 return;
             uint8 id = GetSpeachId();
             std::string const& text = sCreatureTextMgr->GetLocalizedChatString(me->GetEntry(), 0, id, 0, LOCALE_enUS);
             WorldPacket data;
             ChatHandler::BuildChatPacket(data, CHAT_MSG_MONSTER_WHISPER, LANG_UNIVERSAL, me->GetGUID(), summoner->GetGUID(), text, CHAT_TAG_NONE, "Toalu'u the Mystic");
             summoner->ToPlayer()->SendDirectMessage(&data);
             if (id == 1)
                 if (Aura* aura = summoner->GetAura(47189)) // Transform Aura
                     aura->SetDuration(aura->GetDuration() - MINUTE * IN_MILLISECONDS);
         }
References ChatHandler::BuildChatPacket(), CHAT_MSG_MONSTER_WHISPER, CHAT_TAG_NONE, Unit::GetAura(), Object::GetEntry(), Object::GetGUID(), GetSpeachId(), Object::GetTypeId(), IN_MILLISECONDS, LANG_UNIVERSAL, LOCALE_enUS, CreatureAI::me, MINUTE, sCreatureTextMgr, Player::SendDirectMessage(), Object::ToPlayer(), and TYPEID_PLAYER.
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/zone_dragonblight.cpp