Azerotcore-wotlk: ObjectGridLoader Class Reference
ObjectGridLoader Class Reference
#include <ObjectGridLoader.h>
Public Member Functions
ObjectGridLoader (NGridType &grid, Map *map, const Cell &cell)
void Visit (GameObjectMapType &m)
void Visit (CreatureMapType &m)
void Visit (CorpseMapType &) const
void Visit (DynamicObjectMapType &) const
void LoadN (void)
template<>
void SetObjectCell (Creature *obj, CellCoord const &cellCoord)
template<>
void SetObjectCell (GameObject *obj, CellCoord const &cellCoord)
Static Public Member Functions
template<class T >
static void SetObjectCell (T *obj, CellCoord const &cellCoord)
Private Attributes
Cell i_cell
NGridType & i_grid
Map * i_map
uint32 i_gameObjects
uint32 i_creatures
uint32 i_corpses
Friends
class ObjectWorldLoader
Detailed Description
Definition at line 29 of file ObjectGridLoader.h.
Constructor & Destructor Documentation
ObjectGridLoader()
ObjectGridLoader::ObjectGridLoader (NGridType & grid, Map * map, const Cell & cell) inline
Definition at line 34 of file ObjectGridLoader.h.
         : i_cell(cell), i_grid(grid), i_map(map), i_gameObjects(0), i_creatures(0), i_corpses (0)
     {}
Member Function Documentation
LoadN()
void ObjectGridLoader::LoadN (void)
Definition at line 170 of file ObjectGridLoader.cpp.
 {
     i_gameObjects = 0;
     i_creatures = 0;
     i_corpses = 0;
     i_cell.data.Part.cell_y = 0;
     for (uint32 x = 0; x < MAX_NUMBER_OF_CELLS; ++x)
     {
         i_cell.data.Part.cell_x = x;
         for (uint32 y = 0; y < MAX_NUMBER_OF_CELLS; ++y)
         {
             i_cell.data.Part.cell_y = y;
             //Load creatures and game objects
             {
                 TypeContainerVisitor<ObjectGridLoader, GridTypeMapContainer> visitor(*this);
                 i_grid.VisitGrid(x, y, visitor);
             }
             //Load corpses (not bones)
             {
                 ObjectWorldLoader worker(*this);
                 TypeContainerVisitor<ObjectWorldLoader, WorldTypeMapContainer> visitor(worker);
                 i_grid.VisitGrid(x, y, visitor);
             }
         }
     }
     LOG_DEBUG("maps", "%u GameObjects, %u Creatures, and %u Corpses/Bones loaded for grid %u on map %u", i_gameObjects, i_creatures, i_corpses, i_grid.GetGridId(), i_map->GetId());
 }
References Cell::data, NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::GetGridId(), Map::GetId(), i_cell, i_corpses, i_creatures, i_gameObjects, i_grid, i_map, LOG_DEBUG, MAX_NUMBER_OF_CELLS, Cell::Part, NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::VisitGrid(), G3D::x, and G3D::y.
Referenced by Map::EnsureGridLoaded().
SetObjectCell() [1/3]
template<> void ObjectGridLoader::SetObjectCell (Creature * obj, CellCoord const & cellCoord)
Definition at line 55 of file ObjectGridLoader.cpp.
 {
     Cell cell(cellCoord);
     obj->SetCurrentCell(cell);
 }
References MovableMapObject::SetCurrentCell().
SetObjectCell() [2/3]
template<> void ObjectGridLoader::SetObjectCell (GameObject * obj, CellCoord const & cellCoord)
Definition at line 61 of file ObjectGridLoader.cpp.
 {
     Cell cell(cellCoord);
     obj->SetCurrentCell(cell);
 }
References MovableMapObject::SetCurrentCell().
SetObjectCell() [3/3]
template<class T > void ObjectGridLoader::SetObjectCell (T * obj, CellCoord const & cellCoord) static
Definition at line 51 of file ObjectGridLoader.cpp.
 {
 }
Referenced by AddObjectHelper().
Visit() [1/4]
void ObjectGridLoader::Visit (CorpseMapType &) const inline
Definition at line 40 of file ObjectGridLoader.h.
 {}
Visit() [2/4]
void ObjectGridLoader::Visit (CreatureMapType & m)
Definition at line 144 of file ObjectGridLoader.cpp.
 {
     CellCoord cellCoord = i_cell.GetCellCoord();
     CellObjectGuids const& cell_guids = sObjectMgr->GetCellObjectGuids(i_map->GetId(), i_map->GetSpawnMode(), cellCoord.GetId());
     LoadHelper(cell_guids.creatures, cellCoord, m, i_creatures, i_map);
 }
References CellObjectGuids::creatures, Cell::GetCellCoord(), CoordPair< LIMIT >::GetId(), Map::GetId(), Map::GetSpawnMode(), i_cell, i_creatures, i_map, LoadHelper(), and sObjectMgr.
Visit() [3/4]
void ObjectGridLoader::Visit (DynamicObjectMapType &) const inline
Definition at line 41 of file ObjectGridLoader.h.
 {}
Visit() [4/4]
void ObjectGridLoader::Visit (GameObjectMapType & m)
Definition at line 137 of file ObjectGridLoader.cpp.
 {
     CellCoord cellCoord = i_cell.GetCellCoord();
     CellObjectGuids const& cell_guids = sObjectMgr->GetCellObjectGuids(i_map->GetId(), i_map->GetSpawnMode(), cellCoord.GetId());
     LoadHelper(cell_guids.gameobjects, cellCoord, m, i_gameObjects, i_map);
 }
References CellObjectGuids::gameobjects, Cell::GetCellCoord(), CoordPair< LIMIT >::GetId(), Map::GetId(), Map::GetSpawnMode(), i_cell, i_gameObjects, i_map, LoadHelper(), and sObjectMgr.
Friends And Related Function Documentation
ObjectWorldLoader
friend class ObjectWorldLoader friend
Definition at line 31 of file ObjectGridLoader.h.
Member Data Documentation
i_cell
Cell ObjectGridLoader::i_cell private
Definition at line 48 of file ObjectGridLoader.h.
Referenced by LoadN(), and Visit().
i_corpses
uint32 ObjectGridLoader::i_corpses private
Definition at line 53 of file ObjectGridLoader.h.
Referenced by LoadN().
i_creatures
uint32 ObjectGridLoader::i_creatures private
Definition at line 52 of file ObjectGridLoader.h.
Referenced by LoadN(), and Visit().
i_gameObjects
uint32 ObjectGridLoader::i_gameObjects private
Definition at line 51 of file ObjectGridLoader.h.
Referenced by LoadN(), and Visit().
i_grid
NGridType& ObjectGridLoader::i_grid private
Definition at line 49 of file ObjectGridLoader.h.
Referenced by LoadN().
i_map
Map* ObjectGridLoader::i_map private
Definition at line 50 of file ObjectGridLoader.h.
Referenced by LoadN(), and Visit().
The documentation for this class was generated from the following files:
src/server/game/Grids/ObjectGridLoader.h
src/server/game/Grids/ObjectGridLoader.cpp