Azerotcore-wotlk: BgEmptinessComp Struct Reference
BgEmptinessComp Struct Reference
Public Member Functions
bool operator() (Battleground *const &bg1, Battleground *const &bg2) const
Detailed Description
Definition at line 678 of file BattlegroundQueue.cpp.
Member Function Documentation
operator()()
bool BgEmptinessComp::operator() (Battleground *const & bg1, Battleground *const & bg2) const inline
Definition at line 678 of file BattlegroundQueue.cpp.
 { bool operator()(Battleground* const& bg1, Battleground* const& bg2) const { return ((float)bg1->GetMaxFreeSlots() / (float)bg1->GetMaxPlayersPerTeam()) > ((float)bg2->GetMaxFreeSlots() / (float)bg2->GetMaxPlayersPerTeam()); } };
References Battleground::GetMaxFreeSlots(), Battleground::GetMaxPlayersPerTeam(), and operator()().
Referenced by operator()().
The documentation for this struct was generated from the following file:
src/server/game/Battlegrounds/BattlegroundQueue.cpp