Azerotcore-wotlk: npc_wild_wyrm::npc_wild_wyrmAI Struct Reference
npc_wild_wyrm::npc_wild_wyrmAI Struct Reference
Public Member Functions
npc_wild_wyrmAI (Creature *creature)
void EnterEvadeMode () override
void Reset () override
void PassengerBoarded (Unit *, int8, bool apply) override
== Fields =======================================
void MovementInform (uint32 type, uint32 pointId) override
void DamageTaken (Unit *who, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void AttackStart (Unit *) override
void MoveInLineOfSight (Unit *) override
void OnCharmed (bool apply) override
void SpellHit (Unit *caster, const SpellInfo *spellInfo) override
Player * GetValidPlayer ()
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
ObjectGuid playerGUID
uint32 checkTimer
uint32 announceAttackTimer
uint32 attackTimer
bool setCharm
bool switching
bool startPath
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 339 of file zone_storm_peaks.cpp.
Constructor & Destructor Documentation
npc_wild_wyrmAI()
npc_wild_wyrm::npc_wild_wyrmAI::npc_wild_wyrmAI (Creature * creature) inline
Definition at line 341 of file zone_storm_peaks.cpp.
 : ScriptedAI(creature) {}
Member Function Documentation
AttackStart()
void npc_wild_wyrm::npc_wild_wyrmAI::AttackStart (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 407 of file zone_storm_peaks.cpp.
 { }
DamageTaken()
void npc_wild_wyrm::npc_wild_wyrmAI::DamageTaken (Unit * who, uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 397 of file zone_storm_peaks.cpp.
         {
             if (who != me)
             {
                 damage = 0;
                 if (!GetValidPlayer())
                     setCharm = true; // will enter evade on next update
             }
         }
References GetValidPlayer(), ScriptedAI::me, and setCharm.
EnterEvadeMode()
void npc_wild_wyrm::npc_wild_wyrmAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 351 of file zone_storm_peaks.cpp.
         {
             if (switching || me->HasAuraType(SPELL_AURA_CONTROL_VEHICLE))
                 return;
             ScriptedAI::EnterEvadeMode();
         }
References CreatureAI::EnterEvadeMode(), Unit::HasAuraType(), ScriptedAI::me, SPELL_AURA_CONTROL_VEHICLE, and switching.
Referenced by UpdateAI().
GetValidPlayer()
Player* npc_wild_wyrm::npc_wild_wyrmAI::GetValidPlayer () inline
Definition at line 455 of file zone_storm_peaks.cpp.
         {
             Player* charmer = ObjectAccessor::GetPlayer(*me, playerGUID);
             if (charmer && charmer->IsAlive() && me->GetDistance(charmer) < 20.0f)
                 return charmer;
             return nullptr;
         }
References WorldObject::GetDistance(), ObjectAccessor::GetPlayer(), Unit::IsAlive(), ScriptedAI::me, and playerGUID.
Referenced by DamageTaken(), MovementInform(), SpellHit(), and UpdateAI().
MoveInLineOfSight()
void npc_wild_wyrm::npc_wild_wyrmAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 408 of file zone_storm_peaks.cpp.
 { }
MovementInform()
void npc_wild_wyrm::npc_wild_wyrmAI::MovementInform (uint32 type, uint32 pointId) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 378 of file zone_storm_peaks.cpp.
         {
             if (type == POINT_MOTION_TYPE && pointId == 1 && !me->GetCharmerGUID())
             {
                 if (Player* player = GetValidPlayer())
                 {
                     checkTimer = 1;
                     me->SetFullHealth();
                     player->CastSpell(me, SPELL_FIGHT_WYRM_BASE, true);
                     me->CastSpell(me, SPELL_WYRM_GRIP, true);
                     me->SetRegeneratingHealth(false);
                 }
             }
             else if (type == ESCORT_MOTION_TYPE && me->movespline->Finalized())
                 startPath = true;
             else if (type == EFFECT_MOTION_TYPE && pointId == me->GetEntry())
                 Unit::Kill(me, me);
         }
References Unit::CastSpell(), checkTimer, EFFECT_MOTION_TYPE, ESCORT_MOTION_TYPE, Movement::MoveSpline::Finalized(), Unit::GetCharmerGUID(), Object::GetEntry(), GetValidPlayer(), Unit::Kill(), ScriptedAI::me, Unit::movespline, POINT_MOTION_TYPE, Unit::SetFullHealth(), Creature::SetRegeneratingHealth(), SPELL_FIGHT_WYRM_BASE, SPELL_WYRM_GRIP, and startPath.
OnCharmed()
void npc_wild_wyrm::npc_wild_wyrmAI::OnCharmed (bool apply) inline override virtual
Reimplemented from CreatureAI.
Definition at line 410 of file zone_storm_peaks.cpp.
         {
             if (apply)
                 setCharm = true;
         }
References ByteConverter::apply(), and setCharm.
PassengerBoarded()
void npc_wild_wyrm::npc_wild_wyrmAI::PassengerBoarded (Unit * , int8 , bool) inline override virtual
== Fields =======================================
Reimplemented from CreatureAI.
Definition at line 372 of file zone_storm_peaks.cpp.
         {
             if (!apply && me->IsAlive() && me->HasAura(SPELL_WYRM_GRIP))
                 me->RemoveAurasDueToSpell(SPELL_WYRM_GRIP);
         }
References ByteConverter::apply(), Unit::HasAura(), Unit::IsAlive(), ScriptedAI::me, Unit::RemoveAurasDueToSpell(), and SPELL_WYRM_GRIP.
Reset()
void npc_wild_wyrm::npc_wild_wyrmAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 358 of file zone_storm_peaks.cpp.
         {
             me->SetRegeneratingHealth(true);
             me->SetSpeed(MOVE_RUN, 1.14f, true); // ZOMG!
             setCharm = false;
             switching = false;
             startPath = false;
             checkTimer = 0;
             playerGUID.Clear();
             attackTimer = 0;
             announceAttackTimer = 0;
             me->AddUnitState(UNIT_STATE_NO_ENVIRONMENT_UPD);
         }
References Unit::AddUnitState(), announceAttackTimer, attackTimer, checkTimer, ObjectGuid::Clear(), ScriptedAI::me, MOVE_RUN, playerGUID, setCharm, Creature::SetRegeneratingHealth(), Unit::SetSpeed(), startPath, switching, and UNIT_STATE_NO_ENVIRONMENT_UPD.
SpellHit()
void npc_wild_wyrm::npc_wild_wyrmAI::SpellHit (Unit * caster, const SpellInfo * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 416 of file zone_storm_peaks.cpp.
         {
             if (!playerGUID && spellInfo->Id == SPELL_SPEAR_OF_HODIR)
             {
                 me->GetMotionMaster()->MovePoint(1, caster->GetPositionX(), caster->GetPositionY(), caster->GetPositionZ() + 12.0f);
                 playerGUID = caster->GetGUID();
             }
             else if (spellInfo->Id == SPELL_GRAB_ON)
             {
                 if (Aura* aura = me->GetAura(SPELL_WYRM_GRIP))
                     aura->ModStackAmount(10);
             }
             else if (spellInfo->Id == SPELL_THRUST_SPEAR)
             {
                 if (Aura* aura = me->GetAura(SPELL_WYRM_GRIP))
                     aura->ModStackAmount(-5);
             }
             else if (spellInfo->Id == SPELL_MIGHTY_SPEAR_THRUST)
             {
                 if (Aura* aura = me->GetAura(SPELL_WYRM_GRIP))
                     aura->ModStackAmount(-15);
             }
             else if (spellInfo->Id == SPELL_FATAL_STRIKE)
             {
                 if (roll_chance_i(me->GetAuraCount(SPELL_PRY_JAWS_OPEN) * 10))
                 {
                     if (Player* player = GetValidPlayer())
                     {
                         player->KilledMonsterCredit(30415);
                         player->RemoveAurasDueToSpell(SPELL_JAWS_OF_DEATH);
                     }
                     me->SetStandState(UNIT_STAND_STATE_DEAD);
                     me->GetMotionMaster()->MoveFall(me->GetEntry());
                 }
                 else
                     Talk(2);
             }
         }
References Unit::GetAura(), Unit::GetAuraCount(), Object::GetEntry(), Object::GetGUID(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GetValidPlayer(), SpellInfo::Id, ScriptedAI::me, MotionMaster::MoveFall(), MotionMaster::MovePoint(), playerGUID, roll_chance_i(), Unit::SetStandState(), SPELL_FATAL_STRIKE, SPELL_GRAB_ON, SPELL_JAWS_OF_DEATH, SPELL_MIGHTY_SPEAR_THRUST, SPELL_PRY_JAWS_OPEN, SPELL_SPEAR_OF_HODIR, SPELL_THRUST_SPEAR, SPELL_WYRM_GRIP, CreatureAI::Talk(), and UNIT_STAND_STATE_DEAD.
UpdateAI()
void npc_wild_wyrm::npc_wild_wyrmAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 463 of file zone_storm_peaks.cpp.
         {
             if (startPath)
             {
                 startPath = false;
                 Movement::PointsArray pathPoints;
                 pathPoints.push_back(G3D::Vector3(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()));
                 WaypointPath const* i_path = sWaypointMgr->GetPath(me->GetWaypointPath());
                 for (uint8 i = 0; i < i_path->size(); ++i)
                 {
                     WaypointData const* node = i_path->at(i);
                     pathPoints.push_back(G3D::Vector3(node->x, node->y, node->z));
                 }
                 me->GetMotionMaster()->MoveSplinePath(&pathPoints);
             }
             if (setCharm)
             {
                 setCharm = false;
                 if (Player* charmer = GetValidPlayer())
                 {
                     me->SetFaction(FACTION_MONSTER_2);
                     charmer->SetClientControl(me, 0, true);
                     me->SetSpeed(MOVE_RUN, 2.0f, true);
                     startPath = true;
                 }
                 else
                 {
                     me->RemoveAllAuras();
                     EnterEvadeMode();
                 }
                 return;
             }
             if (!checkTimer)
                 return;
             if (checkTimer < 10000)
             {
                 checkTimer += diff;
                 if (checkTimer >= 2000)
                 {
                     checkTimer = 1;
                     if (me->HealthBelowPct(25))
                     {
                         if (Player* player = GetValidPlayer())
{
                             Talk(3);
                             switching = true;
                             me->RemoveAllAuras();
                             me->CastSpell(me, SPELL_JAWS_OF_DEATH, true);
                             player->CastSpell(me, SPELL_FIGHT_WYRM_NEXT, true);
                             checkTimer = 10000;
                             return;
                         }
                         else
{
                             me->RemoveAllAuras();
                             EnterEvadeMode();
                             return;
                         }
                     }
                 }
             }
             else if (checkTimer < 20000)
             {
                 checkTimer += diff;
                 if (checkTimer >= 13000)
                 {
                     switching = false;
                     checkTimer = 20000;
                 }
             }
             else if (checkTimer < 30000)
             {
                 checkTimer += diff;
                 if (checkTimer >= 22000)
                 {
                     checkTimer = 20000;
                     Player* player = GetValidPlayer();
                     if (!player)
                     {
                         me->RemoveAllAuras();
                         EnterEvadeMode();
                     }
                 }
                 return;
             }
             announceAttackTimer += diff;
             if (announceAttackTimer >= 7000)
             {
                 announceAttackTimer = urand(0, 3000);
                 Talk(0);
                 attackTimer = 1;
             }
             if (attackTimer)
             {
                 attackTimer += diff;
                 if (attackTimer > 2000)
                 {
                     attackTimer = 0;
                     Player* player = ObjectAccessor::GetPlayer(*me, playerGUID);
                     if (player && player->HasAura(SPELL_DODGE_CLAWS))
                         Talk(1);
                     else if (player)
                         me->AttackerStateUpdate(player);
                     else
                     {
                         me->RemoveAllAuras();
                         EnterEvadeMode();
                     }
                 }
             }
         }
References announceAttackTimer, Unit::AttackerStateUpdate(), attackTimer, Unit::CastSpell(), checkTimer, diff(), EnterEvadeMode(), FACTION_MONSTER_2, Unit::GetMotionMaster(), ObjectAccessor::GetPlayer(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GetValidPlayer(), Creature::GetWaypointPath(), Unit::HasAura(), Unit::HealthBelowPct(), ScriptedAI::me, MOVE_RUN, MotionMaster::MoveSplinePath(), playerGUID, Unit::RemoveAllAuras(), setCharm, Unit::SetFaction(), Unit::SetSpeed(), SPELL_DODGE_CLAWS, SPELL_FIGHT_WYRM_NEXT, SPELL_JAWS_OF_DEATH, startPath, sWaypointMgr, switching, CreatureAI::Talk(), urand(), WaypointData::x, WaypointData::y, and WaypointData::z.
Member Data Documentation
announceAttackTimer
uint32 npc_wild_wyrm::npc_wild_wyrmAI::announceAttackTimer
Definition at line 345 of file zone_storm_peaks.cpp.
Referenced by Reset(), and UpdateAI().
attackTimer
uint32 npc_wild_wyrm::npc_wild_wyrmAI::attackTimer
Definition at line 346 of file zone_storm_peaks.cpp.
Referenced by Reset(), and UpdateAI().
checkTimer
uint32 npc_wild_wyrm::npc_wild_wyrmAI::checkTimer
Definition at line 344 of file zone_storm_peaks.cpp.
Referenced by MovementInform(), Reset(), and UpdateAI().
playerGUID
ObjectGuid npc_wild_wyrm::npc_wild_wyrmAI::playerGUID
Definition at line 343 of file zone_storm_peaks.cpp.
Referenced by GetValidPlayer(), Reset(), SpellHit(), and UpdateAI().
setCharm
bool npc_wild_wyrm::npc_wild_wyrmAI::setCharm
Definition at line 347 of file zone_storm_peaks.cpp.
Referenced by DamageTaken(), OnCharmed(), Reset(), and UpdateAI().
startPath
bool npc_wild_wyrm::npc_wild_wyrmAI::startPath
Definition at line 349 of file zone_storm_peaks.cpp.
Referenced by MovementInform(), Reset(), and UpdateAI().
switching
bool npc_wild_wyrm::npc_wild_wyrmAI::switching
Definition at line 348 of file zone_storm_peaks.cpp.
Referenced by EnterEvadeMode(), Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/zone_storm_peaks.cpp