Azerotcore-wotlk: instance_sunken_temple::instance_sunken_temple_InstanceMapScript Struct Reference
instance_sunken_temple::instance_sunken_temple_InstanceMapScript Struct Reference
Public Member Functions
instance_sunken_temple_InstanceMapScript (Map *map)
void Initialize () override
void OnCreatureCreate (Creature *creature) override
void OnUnitDeath (Unit *unit) override
void OnGameObjectCreate (GameObject *gameobject) override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 type) const override
void Update (uint32 diff) override
std::string GetSaveData () override
void Load (const char *in) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void CreatureLooted (Creature *, LootType)
void SaveToDB ()
virtual bool IsEncounterInProgress () const
void OnCreatureRemove (Creature *creature) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual void ProcessEvent (WorldObject *, uint32)
Private Attributes
uint32 _statuePhase
uint32 _defendersKilled
uint32 _encounters [MAX_ENCOUNTERS]
ObjectGuid _forcefieldGUID
ObjectGuid _jammalanGUID
GuidList _dragonkinList
EventMap _events
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Definition at line 30 of file instance_sunken_temple.cpp.
Constructor & Destructor Documentation
instance_sunken_temple_InstanceMapScript()
instance_sunken_temple::instance_sunken_temple_InstanceMapScript::instance_sunken_temple_InstanceMapScript (Map * map) inline
Definition at line 32 of file instance_sunken_temple.cpp.
                                                            : InstanceScript(map)
         {
         }
Member Function Documentation
GetData()
uint32 instance_sunken_temple::instance_sunken_temple_InstanceMapScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
Definition at line 129 of file instance_sunken_temple.cpp.
         {
             switch (type)
             {
                 case DATA_STATUES:
                     return _statuePhase;
                 case DATA_DEFENDER_KILLED:
                     return _defendersKilled;
                 case TYPE_ATAL_ALARION:
                 case TYPE_JAMMAL_AN:
                 case TYPE_HAKKAR_EVENT:
                     return _encounters[type];
             }
             return 0;
         }
References _defendersKilled, _encounters, _statuePhase, DATA_DEFENDER_KILLED, DATA_STATUES, TYPE_ATAL_ALARION, TYPE_HAKKAR_EVENT, and TYPE_JAMMAL_AN.
GetSaveData()
std::string instance_sunken_temple::instance_sunken_temple_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
Definition at line 159 of file instance_sunken_temple.cpp.
         {
             std::ostringstream saveStream;
             saveStream << "T A " << _encounters[0] << ' ' << _encounters[1] << ' ' << _encounters[2] << ' ' << _statuePhase << ' ' << _defendersKilled;
             return saveStream.str();
         }
References _defendersKilled, _encounters, and _statuePhase.
Initialize()
void instance_sunken_temple::instance_sunken_temple_InstanceMapScript::Initialize (void) inline override virtual
Reimplemented from InstanceScript.
Definition at line 36 of file instance_sunken_temple.cpp.
         {
             _statuePhase = 0;
             _defendersKilled = 0;
             memset(&_encounters, 0, sizeof(_encounters));
         }
References _defendersKilled, _encounters, and _statuePhase.
Load()
void instance_sunken_temple::instance_sunken_temple_InstanceMapScript::Load (const char * in) inline override virtual
Reimplemented from InstanceScript.
Definition at line 166 of file instance_sunken_temple.cpp.
         {
             if (!in)
                 return;
             char dataHead1, dataHead2;
             std::istringstream loadStream(in);
             loadStream >> dataHead1 >> dataHead2;
             if (dataHead1 == 'T' && dataHead2 == 'A')
             {
                 for (uint8 i = 0; i < MAX_ENCOUNTERS; ++i)
                 {
                     loadStream >> _encounters[i];
                     if (_encounters[i] == IN_PROGRESS)
                         _encounters[i] = NOT_STARTED;
                 }
                 loadStream >> _statuePhase;
                 loadStream >> _defendersKilled;
             }
         }
References _defendersKilled, _encounters, _statuePhase, IN_PROGRESS, MAX_ENCOUNTERS, and NOT_STARTED.
OnCreatureCreate()
void instance_sunken_temple::instance_sunken_temple_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 43 of file instance_sunken_temple.cpp.
         {
             switch (creature->GetEntry())
             {
                 case NPC_JAMMAL_AN_THE_PROPHET:
                     _jammalanGUID = creature->GetGUID();
                     break;
             }
             if (creature->IsAlive() && creature->GetSpawnId() && creature->GetCreatureType() == CREATURE_TYPE_DRAGONKIN && creature->GetEntry() != NPC_SHADE_OF_ERANIKUS)
                 _dragonkinList.push_back(creature->GetGUID());
         }
References _dragonkinList, _jammalanGUID, CREATURE_TYPE_DRAGONKIN, Unit::GetCreatureType(), Object::GetEntry(), Object::GetGUID(), Creature::GetSpawnId(), Unit::IsAlive(), NPC_JAMMAL_AN_THE_PROPHET, and NPC_SHADE_OF_ERANIKUS.
OnGameObjectCreate()
void instance_sunken_temple::instance_sunken_temple_InstanceMapScript::OnGameObjectCreate (GameObject * gameobject) inline override virtual
Reimplemented from InstanceScript.
Definition at line 62 of file instance_sunken_temple.cpp.
         {
             switch (gameobject->GetEntry())
             {
                 case GO_ATALAI_STATUE1:
                 case GO_ATALAI_STATUE2:
                 case GO_ATALAI_STATUE3:
                 case GO_ATALAI_STATUE4:
                 case GO_ATALAI_STATUE5:
                 case GO_ATALAI_STATUE6:
                     if (gameobject->GetEntry() < GO_ATALAI_STATUE1 + _statuePhase)
                     {
                         instance->SummonGameObject(GO_ATALAI_LIGHT2, gameobject->GetPositionX(), gameobject->GetPositionY(), gameobject->GetPositionZ(), 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f);
                         gameobject->SetUInt32Value(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                     }
                     break;
                 case GO_ATALAI_IDOL:
                     if (_statuePhase == MAX_STATUE_PHASE)
                         gameobject->SummonGameObject(GO_IDOL_OF_HAKKAR, -480.08f, 94.29f, -189.72f, 1.571f, 0.0f, 0.0f, 0.0f, 0.0f, 0);
                     break;
                 case GO_IDOL_OF_HAKKAR:
                     if (_encounters[TYPE_ATAL_ALARION] == DONE)
                         gameobject->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                     break;
                 case GO_FORCEFIELD:
                     _forcefieldGUID = gameobject->GetGUID();
                     if (_defendersKilled == DEFENDERS_COUNT)
                         gameobject->SetGoState(GO_STATE_ACTIVE);
             }
         }
References _defendersKilled, _encounters, _forcefieldGUID, _statuePhase, DEFENDERS_COUNT, DONE, GAMEOBJECT_FLAGS, Object::GetEntry(), Object::GetGUID(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GO_ATALAI_IDOL, GO_ATALAI_LIGHT2, GO_ATALAI_STATUE1, GO_ATALAI_STATUE2, GO_ATALAI_STATUE3, GO_ATALAI_STATUE4, GO_ATALAI_STATUE5, GO_ATALAI_STATUE6, GO_FLAG_NOT_SELECTABLE, GO_FORCEFIELD, GO_IDOL_OF_HAKKAR, GO_STATE_ACTIVE, InstanceScript::instance, MAX_STATUE_PHASE, Object::RemoveFlag(), GameObject::SetGoState(), Object::SetUInt32Value(), WorldObject::SummonGameObject(), Map::SummonGameObject(), and TYPE_ATAL_ALARION.
OnUnitDeath()
void instance_sunken_temple::instance_sunken_temple_InstanceMapScript::OnUnitDeath (Unit * unit) inline override virtual
Reimplemented from ZoneScript.
Definition at line 56 of file instance_sunken_temple.cpp.
         {
             if (unit->GetTypeId() == TYPEID_UNIT && unit->GetCreatureType() == CREATURE_TYPE_DRAGONKIN && unit->GetEntry() != NPC_SHADE_OF_ERANIKUS)
                 _dragonkinList.remove(unit->GetGUID());
         }
References _dragonkinList, CREATURE_TYPE_DRAGONKIN, Unit::GetCreatureType(), Object::GetEntry(), Object::GetGUID(), Object::GetTypeId(), NPC_SHADE_OF_ERANIKUS, and TYPEID_UNIT.
SetData()
void instance_sunken_temple::instance_sunken_temple_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
Definition at line 93 of file instance_sunken_temple.cpp.
         {
             switch (type)
             {
                 case DATA_STATUES:
                     _events.ScheduleEvent(DATA_STATUES, 0);
                     break;
                 case DATA_DEFENDER_KILLED:
                     ++_defendersKilled;
                     if (_defendersKilled == DEFENDERS_COUNT)
                     {
                         instance->LoadGrid(-425.89f, -86.07f);
                         if (Creature* jammal = instance->GetCreature(_jammalanGUID))
                             jammal->AI()->Talk(0);
                         if (GameObject* forcefield = instance->GetGameObject(_forcefieldGUID))
                             forcefield->SetGoState(GO_STATE_ACTIVE);
                     }
                     break;
                 case DATA_ERANIKUS_FIGHT:
                     for (ObjectGuid const& guid : _dragonkinList)
                     {
                         if (Creature* creature = instance->GetCreature(guid))
                             if (instance->IsGridLoaded(creature->GetPositionX(), creature->GetPositionY()))
                                 creature->SetInCombatWithZone();
                     }
                     break;
                 case TYPE_ATAL_ALARION:
                 case TYPE_JAMMAL_AN:
                 case TYPE_HAKKAR_EVENT:
                     _encounters[type] = data;
                     break;
             }
             SaveToDB();
         }
References _defendersKilled, _dragonkinList, _encounters, _events, _forcefieldGUID, _jammalanGUID, DATA_DEFENDER_KILLED, DATA_ERANIKUS_FIGHT, DATA_STATUES, DEFENDERS_COUNT, Map::GetCreature(), Map::GetGameObject(), GO_STATE_ACTIVE, InstanceScript::instance, Map::IsGridLoaded(), Map::LoadGrid(), InstanceScript::SaveToDB(), EventMap::ScheduleEvent(), TYPE_ATAL_ALARION, TYPE_HAKKAR_EVENT, and TYPE_JAMMAL_AN.
Update()
void instance_sunken_temple::instance_sunken_temple_InstanceMapScript::Update (uint32 diff) inline override virtual
Reimplemented from InstanceScript.
Definition at line 146 of file instance_sunken_temple.cpp.
         {
             _events.Update(diff);
             switch (_events.ExecuteEvent())
             {
                 case DATA_STATUES:
                     ++_statuePhase;
                     if (_statuePhase == MAX_STATUE_PHASE)
                         instance->SummonGameObject(GO_IDOL_OF_HAKKAR, -480.08f, 94.29f, -189.72f, 1.571f, 0.0f, 0.0f, 0.0f, 0.0f, 0);
                     break;
             }
         }
References _events, _statuePhase, DATA_STATUES, EventMap::ExecuteEvent(), GO_IDOL_OF_HAKKAR, InstanceScript::instance, MAX_STATUE_PHASE, Map::SummonGameObject(), and EventMap::Update().
Member Data Documentation
_defendersKilled
uint32 instance_sunken_temple::instance_sunken_temple_InstanceMapScript::_defendersKilled private
Definition at line 190 of file instance_sunken_temple.cpp.
Referenced by GetData(), GetSaveData(), Initialize(), Load(), OnGameObjectCreate(), and SetData().
_dragonkinList
GuidList instance_sunken_temple::instance_sunken_temple_InstanceMapScript::_dragonkinList private
Definition at line 195 of file instance_sunken_temple.cpp.
Referenced by OnCreatureCreate(), OnUnitDeath(), and SetData().
_encounters
uint32 instance_sunken_temple::instance_sunken_temple_InstanceMapScript::_encounters[MAX_ENCOUNTERS] private
Definition at line 191 of file instance_sunken_temple.cpp.
Referenced by GetData(), GetSaveData(), Initialize(), Load(), OnGameObjectCreate(), and SetData().
_events
EventMap instance_sunken_temple::instance_sunken_temple_InstanceMapScript::_events private
Definition at line 196 of file instance_sunken_temple.cpp.
Referenced by SetData(), and Update().
_forcefieldGUID
ObjectGuid instance_sunken_temple::instance_sunken_temple_InstanceMapScript::_forcefieldGUID private
Definition at line 193 of file instance_sunken_temple.cpp.
Referenced by OnGameObjectCreate(), and SetData().
_jammalanGUID
ObjectGuid instance_sunken_temple::instance_sunken_temple_InstanceMapScript::_jammalanGUID private
Definition at line 194 of file instance_sunken_temple.cpp.
Referenced by OnCreatureCreate(), and SetData().
_statuePhase
uint32 instance_sunken_temple::instance_sunken_temple_InstanceMapScript::_statuePhase private
Definition at line 189 of file instance_sunken_temple.cpp.
Referenced by GetData(), GetSaveData(), Initialize(), Load(), OnGameObjectCreate(), and Update().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/SunkenTemple/instance_sunken_temple.cpp