Azerotcore-wotlk: spell_q11919_q11940_drake_hunt::spell_q11919_q11940_drake_hunt_AuraScript Class Reference
spell_q11919_q11940_drake_hunt::spell_q11919_q11940_drake_hunt_AuraScript Class Reference
Private Member Functions
PrepareAuraScript (spell_q11919_q11940_drake_hunt_AuraScript) bool Load() override
void HandleEffectRemove (AuraEffect const *, AuraEffectHandleModes)
void Register () override
Additional Inherited Members
Public Member Functions inherited from AuraScript
AuraScript ()
bool _Validate (SpellInfo const *entry) override
bool _Load (Aura *aura)
void _PrepareScriptCall (AuraScriptHookType hookType, AuraApplication const *aurApp=nullptr)
void _FinishScriptCall ()
bool _IsDefaultActionPrevented ()
void PreventDefaultAction ()
SpellInfo const * GetSpellInfo () const
uint32 GetId () const
ObjectGuid GetCasterGUID () const
Unit * GetCaster () const
WorldObject * GetOwner () const
Unit * GetUnitOwner () const
DynamicObject * GetDynobjOwner () const
void Remove (uint32 removeMode=0)
Aura * GetAura () const
AuraObjectType GetType () const
int32 GetDuration () const
void SetDuration (int32 duration, bool withMods=false)
void RefreshDuration ()
time_t GetApplyTime () const
int32 GetMaxDuration () const
void SetMaxDuration (int32 duration)
int32 CalcMaxDuration () const
bool IsExpired () const
bool IsPermanent () const
uint8 GetCharges () const
void SetCharges (uint8 charges)
uint8 CalcMaxCharges () const
bool ModCharges (int8 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool DropCharge (AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
uint8 GetStackAmount () const
void SetStackAmount (uint8 num)
bool ModStackAmount (int32 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool IsPassive () const
bool IsDeathPersistent () const
bool HasEffect (uint8 effIndex) const
AuraEffect * GetEffect (uint8 effIndex) const
bool HasEffectType (AuraType type) const
Unit * GetTarget () const
AuraApplication const * GetTargetApplication () const
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from AuraScript
HookList< CheckAreaTargetHandler > DoCheckAreaTarget
HookList< AuraDispelHandler > OnDispel
HookList< AuraDispelHandler > AfterDispel
HookList< EffectApplyHandler > OnEffectApply
HookList< EffectApplyHandler > AfterEffectApply
HookList< EffectApplyHandler > OnEffectRemove
HookList< EffectApplyHandler > AfterEffectRemove
HookList< EffectPeriodicHandler > OnEffectPeriodic
HookList< EffectUpdatePeriodicHandler > OnEffectUpdatePeriodic
HookList< EffectCalcAmountHandler > DoEffectCalcAmount
HookList< EffectCalcPeriodicHandler > DoEffectCalcPeriodic
HookList< EffectCalcSpellModHandler > DoEffectCalcSpellMod
HookList< EffectAbsorbHandler > OnEffectAbsorb
HookList< EffectAbsorbHandler > AfterEffectAbsorb
HookList< EffectManaShieldHandler > OnEffectManaShield
HookList< EffectManaShieldHandler > AfterEffectManaShield
HookList< EffectSplitHandler > OnEffectSplit
HookList< CheckProcHandler > DoCheckProc
HookList< AuraProcHandler > DoPrepareProc
HookList< AuraProcHandler > OnProc
HookList< AuraProcHandler > AfterProc
HookList< EffectProcHandler > OnEffectProc
HookList< EffectProcHandler > AfterEffectProc
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Definition at line 61 of file zone_borean_tundra.cpp.
Member Function Documentation
HandleEffectRemove()
void spell_q11919_q11940_drake_hunt::spell_q11919_q11940_drake_hunt_AuraScript::HandleEffectRemove (AuraEffect const * , AuraEffectHandleModes) inline private
Definition at line 70 of file zone_borean_tundra.cpp.
         {
             if (GetTargetApplication()->GetRemoveMode() != AURA_REMOVE_BY_EXPIRE || !GetCaster())
                 return;
             Creature* owner = GetOwner()->ToCreature();
             owner->RemoveAllAurasExceptType(SPELL_AURA_DUMMY);
             owner->CombatStop(true);
             owner->DeleteThreatList();
             owner->GetMotionMaster()->Clear(false);
             owner->GetMotionMaster()->MoveFollow(GetCaster(), 4.0f, M_PI, MOTION_SLOT_ACTIVE);
             owner->CastSpell(owner, SPELL_SUBDUED, true);
             GetCaster()->CastSpell(GetCaster(), SPELL_DRAKE_HATCHLING_SUBDUED, true);
             owner->SetFaction(FACTION_FRIENDLY);
             owner->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
             owner->DespawnOrUnsummon(3 * MINUTE * IN_MILLISECONDS);
         }
References AURA_REMOVE_BY_EXPIRE, Unit::CastSpell(), MotionMaster::Clear(), Unit::CombatStop(), Unit::DeleteThreatList(), Creature::DespawnOrUnsummon(), FACTION_FRIENDLY, AuraScript::GetCaster(), Unit::GetMotionMaster(), AuraScript::GetOwner(), AuraScript::GetTargetApplication(), IN_MILLISECONDS, M_PI, MINUTE, MOTION_SLOT_ACTIVE, MotionMaster::MoveFollow(), Unit::RemoveAllAurasExceptType(), Unit::SetFaction(), Object::SetFlag(), SPELL_AURA_DUMMY, SPELL_DRAKE_HATCHLING_SUBDUED, SPELL_SUBDUED, Object::ToCreature(), UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, and UNIT_FLAG_IMMUNE_TO_PC.
Referenced by Register().
PrepareAuraScript()
spell_q11919_q11940_drake_hunt::spell_q11919_q11940_drake_hunt_AuraScript::PrepareAuraScript (spell_q11919_q11940_drake_hunt_AuraScript) inline override private
Definition at line 63 of file zone_borean_tundra.cpp.
         {
             return GetOwner()->GetTypeId() == TYPEID_UNIT;
         }
References AuraScript::GetOwner(), Object::GetTypeId(), and TYPEID_UNIT.
Register()
void spell_q11919_q11940_drake_hunt::spell_q11919_q11940_drake_hunt_AuraScript::Register () inline override private virtual
Implements _SpellScript.
Definition at line 88 of file zone_borean_tundra.cpp.
         {
             AfterEffectRemove += AuraEffectRemoveFn(spell_q11919_q11940_drake_hunt_AuraScript::HandleEffectRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
         }
References AuraScript::AfterEffectRemove, AURA_EFFECT_HANDLE_REAL, AuraEffectRemoveFn, EFFECT_0, HandleEffectRemove(), and SPELL_AURA_DUMMY.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/zone_borean_tundra.cpp