Azerotcore-wotlk: go_crystalline_tear Class Reference
go_crystalline_tear Class Reference
Public Member Functions
go_crystalline_tear ()
bool OnQuestAccept (Player *player, GameObject *go, Quest const *quest) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, GameObject *)
virtual bool OnGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Definition at line 899 of file zone_silithus.cpp.
Constructor & Destructor Documentation
go_crystalline_tear()
go_crystalline_tear::go_crystalline_tear () inline
Definition at line 902 of file zone_silithus.cpp.
 : GameObjectScript("go_crystalline_tear") { }
Member Function Documentation
OnQuestAccept()
bool go_crystalline_tear::OnQuestAccept (Player * player, GameObject * go, Quest const * quest) inline override virtual
Reimplemented from GameObjectScript.
Definition at line 904 of file zone_silithus.cpp.
     {
         if (quest->GetQuestId() == QUEST_A_PAWN_ON_THE_ETERNAL_BOARD)
         {
             if (Creature* trigger = go->FindNearestCreature(15454, 100, player))
             {
                 Unit* Merithra = trigger->SummonCreature(15378, -8034.535f, 1535.14f, 2.61f, 0, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 220000);
                 Unit* Caelestrasz = trigger->SummonCreature(15379, -8032.767f, 1533.148f, 2.61f, 1.5f, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 220000);
                 Unit* Arygos = trigger->SummonCreature(15380, -8034.52f, 1537.843f, 2.61f, 5.7f, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 220000);
                 /* Unit* Fandral = */ trigger->SummonCreature(15382, -8028.462f, 1535.843f, 2.61f, 3.141592f, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 220000);
                 Creature* Anachronos = trigger->SummonCreature(15381, -8028.75f, 1538.795f, 2.61f, 4, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 220000);
                 if (Merithra)
                 {
                     Merithra->SetUInt32Value(UNIT_NPC_FLAGS, 0);
                     Merithra->SetUInt32Value(UNIT_FIELD_BYTES_1, 0);
                     Merithra->SetUInt32Value(UNIT_FIELD_DISPLAYID, 15420);
                     Merithra->SetFaction(FACTION_FRIENDLY);
                 }
                 if (Caelestrasz)
                 {
                     Caelestrasz->SetUInt32Value(UNIT_NPC_FLAGS, 0);
                     Caelestrasz->SetUInt32Value(UNIT_FIELD_BYTES_1, 0);
                     Caelestrasz->SetUInt32Value(UNIT_FIELD_DISPLAYID, 15419);
                     Caelestrasz->SetFaction(FACTION_FRIENDLY);
                 }
                 if (Arygos)
                 {
                     Arygos->SetUInt32Value(UNIT_NPC_FLAGS, 0);
                     Arygos->SetUInt32Value(UNIT_FIELD_BYTES_1, 0);
                     Arygos->SetUInt32Value(UNIT_FIELD_DISPLAYID, 15418);
                     Arygos->SetFaction(FACTION_FRIENDLY);
                 }
                 if (Anachronos)
                 {
                     if (npc_anachronos_the_ancient::npc_anachronos_the_ancientAI* anachronosAI = CAST_AI(npc_anachronos_the_ancient::npc_anachronos_the_ancientAI, Anachronos->AI()))
                         anachronosAI->PlayerGUID = player->GetGUID();
                     if (npc_anachronos_quest_trigger::npc_anachronos_quest_triggerAI* triggerAI = CAST_AI(npc_anachronos_quest_trigger::npc_anachronos_quest_triggerAI, trigger->AI()))
                     {
                         triggerAI->Failed = false;
                         triggerAI->PlayerGUID = player->GetGUID();
                         triggerAI->EventStarted = true;
                         triggerAI->Announced = true;
                     }
                 }
             }
         }
         return true;
     }
References Creature::AI(), CAST_AI, FACTION_FRIENDLY, WorldObject::FindNearestCreature(), Object::GetGUID(), Quest::GetQuestId(), QUEST_A_PAWN_ON_THE_ETERNAL_BOARD, Unit::SetFaction(), Object::SetUInt32Value(), WorldObject::SummonCreature(), TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, UNIT_FIELD_BYTES_1, UNIT_FIELD_DISPLAYID, and UNIT_NPC_FLAGS.
The documentation for this class was generated from the following file:
src/server/scripts/Kalimdor/zone_silithus.cpp