Azerotcore-wotlk: spell_mage_cold_snap Class Reference
spell_mage_cold_snap Class Reference
Private Member Functions
PrepareSpellScript (spell_mage_cold_snap)
bool Load () override
void HandleDummy (SpellEffIndex)
void Register () override
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual bool Validate (SpellInfo const *)
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Definition at line 469 of file spell_mage.cpp.
Member Function Documentation
HandleDummy()
void spell_mage_cold_snap::HandleDummy (SpellEffIndex) inline private
Definition at line 478 of file spell_mage.cpp.
     {
         Player* caster = GetCaster()->ToPlayer();
         // immediately finishes the cooldown on Frost spells
         PlayerSpellMap const& spellMap = caster->GetSpellMap();
         for (PlayerSpellMap::const_iterator itr = spellMap.begin(); itr != spellMap.end(); ++itr)
         {
             SpellInfo const* spellInfo = sSpellMgr->AssertSpellInfo(itr->first);
             if (spellInfo->SpellFamilyName == SPELLFAMILY_MAGE && (spellInfo->GetSchoolMask() & SPELL_SCHOOL_MASK_FROST) && spellInfo->Id != SPELL_MAGE_COLD_SNAP && spellInfo->GetRecoveryTime() > 0)
             {
                 SpellCooldowns::iterator citr = caster->GetSpellCooldownMap().find(spellInfo->Id);
                 if (citr != caster->GetSpellCooldownMap().end() && citr->second.needSendToClient)
                     caster->RemoveSpellCooldown(spellInfo->Id, true);
                 else
                     caster->RemoveSpellCooldown(spellInfo->Id, false);
             }
         }
     }
References SpellScript::GetCaster(), SpellInfo::GetRecoveryTime(), SpellInfo::GetSchoolMask(), Player::GetSpellCooldownMap(), Player::GetSpellMap(), SpellInfo::Id, Player::RemoveSpellCooldown(), SPELL_MAGE_COLD_SNAP, SPELL_SCHOOL_MASK_FROST, SPELLFAMILY_MAGE, SpellInfo::SpellFamilyName, sSpellMgr, and Object::ToPlayer().
Referenced by Register().
Load()
bool spell_mage_cold_snap::Load () inline override private virtual
Reimplemented from _SpellScript.
Definition at line 473 of file spell_mage.cpp.
     {
         return GetCaster()->GetTypeId() == TYPEID_PLAYER;
     }
References SpellScript::GetCaster(), Object::GetTypeId(), and TYPEID_PLAYER.
PrepareSpellScript()
spell_mage_cold_snap::PrepareSpellScript (spell_mage_cold_snap) private
Register()
void spell_mage_cold_snap::Register () inline override private virtual
Implements _SpellScript.
Definition at line 498 of file spell_mage.cpp.
     {
         OnEffectHit += SpellEffectFn(spell_mage_cold_snap::HandleDummy, EFFECT_0, SPELL_EFFECT_DUMMY);
     }
References EFFECT_0, HandleDummy(), SpellScript::OnEffectHit, SPELL_EFFECT_DUMMY, and SpellEffectFn.
The documentation for this class was generated from the following file:
src/server/scripts/Spells/spell_mage.cpp