Azerotcore-wotlk: TimeTracker Struct Reference
TimeTracker Struct Reference
#include <Timer.h>
Public Member Functions
TimeTracker (time_t expiry)
void Update (time_t diff)
bool Passed () const
void Reset (time_t interval)
time_t GetExpiry () const
Private Attributes
time_t i_expiryTime
Detailed Description
Definition at line 121 of file Timer.h.
Constructor & Destructor Documentation
TimeTracker()
TimeTracker::TimeTracker (time_t expiry) inline
Definition at line 124 of file Timer.h.
         : i_expiryTime(expiry)
     {
     }
Member Function Documentation
GetExpiry()
time_t TimeTracker::GetExpiry () const inline
Definition at line 144 of file Timer.h.
     {
         return i_expiryTime;
     }
References i_expiryTime.
Passed()
bool TimeTracker::Passed () const inline
Definition at line 134 of file Timer.h.
     {
         return i_expiryTime <= 0;
     }
References i_expiryTime.
Referenced by TimedFleeingMovementGenerator::Update().
Reset()
void TimeTracker::Reset (time_t interval) inline
Definition at line 139 of file Timer.h.
     {
         i_expiryTime = interval;
     }
References i_expiryTime.
Update()
void TimeTracker::Update (time_t diff) inline
Definition at line 129 of file Timer.h.
     {
         i_expiryTime -= diff;
     }
References diff(), and i_expiryTime.
Referenced by TimedFleeingMovementGenerator::Update().
Member Data Documentation
i_expiryTime
time_t TimeTracker::i_expiryTime private
Definition at line 150 of file Timer.h.
Referenced by GetExpiry(), Passed(), Reset(), and Update().
The documentation for this struct was generated from the following file:
src/common/Utilities/Timer.h