Azerotcore-wotlk: achievement_yogg_saron_he_waits_dreaming Class Reference
achievement_yogg_saron_he_waits_dreaming Class Reference
Public Member Functions
achievement_yogg_saron_he_waits_dreaming (char const *name, uint8 illusion)
bool OnCheck (Player *player, Unit *, uint32) override
Public Member Functions inherited from AchievementCriteriaScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Private Attributes
uint8 const _requiredIllusion
Additional Inherited Members
Protected Member Functions inherited from AchievementCriteriaScript
AchievementCriteriaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 3029 of file boss_yoggsaron.cpp.
Constructor & Destructor Documentation
achievement_yogg_saron_he_waits_dreaming()
achievement_yogg_saron_he_waits_dreaming::achievement_yogg_saron_he_waits_dreaming (char const * name, uint8 illusion) inline
Definition at line 3032 of file boss_yoggsaron.cpp.
                                                                                : AchievementCriteriaScript(name),
         _requiredIllusion(illusion)
     {
     }
Member Function Documentation
OnCheck()
bool achievement_yogg_saron_he_waits_dreaming::OnCheck (Player * player, Unit * , uint32) inline override virtual
Reimplemented from AchievementCriteriaScript.
Definition at line 3037 of file boss_yoggsaron.cpp.
     {
         if (player->GetInstanceScript())
             if (Creature* sara = ObjectAccessor::GetCreature(*player, player->GetInstanceScript()->GetGuidData(NPC_BRAIN_OF_YOGG_SARON)))
                 return sara->GetAI()->GetData(DATA_GET_CURRENT_ILLUSION) == _requiredIllusion;
         return false;
     }
References _requiredIllusion, DATA_GET_CURRENT_ILLUSION, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), and NPC_BRAIN_OF_YOGG_SARON.
Member Data Documentation
_requiredIllusion
uint8 const achievement_yogg_saron_he_waits_dreaming::_requiredIllusion private
Definition at line 3047 of file boss_yoggsaron.cpp.
Referenced by OnCheck().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_yoggsaron.cpp