Azerotcore-wotlk: src/tools/vmap4_extractor/adtfile.cpp File Reference
adtfile.cpp File Reference
#include "vmapexport.h"
#include "adtfile.h"
#include <algorithm>
#include <cstdio>
Functions
char const * GetPlainName (char const *FileName)
char * GetPlainName (char *FileName)
void fixnamen (char *name, size_t len)
void fixname2 (char *name, size_t len)
char * GetExtension (char *FileName)
Function Documentation
fixname2()
void fixname2 (char * name, size_t len)
Definition at line 63 of file adtfile.cpp.
 {
     if (len < 3)
         return;
     for (size_t i = 0; i < len - 3; i++)
         if (name[i] == ' ')
             name[i] = '_';
 }
Referenced by ExtractGameobjectModels(), Doodad::ExtractSet(), ExtractSingleModel(), ExtractSingleWmo(), ADTFile::init(), WDTFile::init(), and WMORoot::open().
fixnamen()
void fixnamen (char * name, size_t len)
Definition at line 45 of file adtfile.cpp.
 {
     if (len < 3)
         return;
     for (size_t i = 0; i < len - 3; i++)
     {
         if (i > 0 && name[i] >= 'A' && name[i] <= 'Z' && isalpha(name[i - 1]))
             name[i] |= 0x20;
         else if ((i == 0 || !isalpha(name[i - 1])) && name[i] >= 'a' && name[i] <= 'z')
             name[i] &= ~0x20;
     }
     //extension in lowercase
     for (size_t i = len - 3; i < len; i++)
         name[i] |= 0x20;
 }
Referenced by ExtractGameobjectModels(), Doodad::ExtractSet(), ExtractSingleModel(), ExtractSingleWmo(), ADTFile::init(), WDTFile::init(), and WMORoot::open().
GetExtension()
char* GetExtension (char * FileName)
Definition at line 73 of file adtfile.cpp.
 {
     if (char* szTemp = strrchr(FileName, '.'))
         return szTemp;
     return nullptr;
 }
Referenced by ExtractGameobjectModels().
GetPlainName() [1/2]
char* GetPlainName (char * FileName)
Definition at line 36 of file adtfile.cpp.
 {
     char* szTemp;
     if ((szTemp = strrchr(FileName, '\\')) != nullptr)
         FileName = szTemp + 1;
     return FileName;
 }
GetPlainName() [2/2]
char const* GetPlainName (char const * FileName)
Definition at line 27 of file adtfile.cpp.
 {
     const char* szTemp;
     if ((szTemp = strrchr(FileName, '\\')) != nullptr)
         FileName = szTemp + 1;
     return FileName;
 }
Referenced by ExtractGameobjectModels(), Doodad::ExtractSet(), ExtractSingleModel(), ExtractSingleWmo(), ADTFile::init(), and WMORoot::open().