Azerotcore-wotlk: QueryCallback Class Reference
QueryCallback Class Reference
#include <QueryCallback.h>
Classes
struct QueryCallbackData
Public Member Functions
QueryCallback (QueryResultFuture &&result)
QueryCallback (PreparedQueryResultFuture &&result)
QueryCallback (QueryCallback &&right)
QueryCallback & operator= (QueryCallback &&right)
~QueryCallback ()
QueryCallback && WithCallback (std::function< void(QueryResult)> &&callback)
QueryCallback && WithPreparedCallback (std::function< void(PreparedQueryResult)> &&callback)
QueryCallback && WithChainingCallback (std::function< void(QueryCallback &, QueryResult)> &&callback)
QueryCallback && WithChainingPreparedCallback (std::function< void(QueryCallback &, PreparedQueryResult)> &&callback)
void SetNextQuery (QueryCallback &&next)
bool InvokeIfReady ()
Private Member Functions
QueryCallback (QueryCallback const &right)=delete
QueryCallback & operator= (QueryCallback const &right)=delete
Private Attributes
union {
QueryResultFuture _string
PreparedQueryResultFuture _prepared
};
bool _isPrepared
std::queue< QueryCallbackData, std::list< QueryCallbackData > > _callbacks
Friends
template<typename T >
void ConstructActiveMember (T *obj)
template<typename T >
void DestroyActiveMember (T *obj)
template<typename T >
void MoveFrom (T *to, T &&from)
Detailed Description
Definition at line 29 of file QueryCallback.h.
Constructor & Destructor Documentation
QueryCallback() [1/4]
QueryCallback::QueryCallback (QueryResultFuture && result) explicit
QueryCallback() [2/4]
QueryCallback::QueryCallback (PreparedQueryResultFuture && result) explicit
QueryCallback() [3/4]
QueryCallback::QueryCallback (QueryCallback && right)
Definition at line 120 of file QueryCallback.cpp.
 {
     _isPrepared = right._isPrepared;
     ConstructActiveMember(this);
     MoveFrom(this, std::move(right));
     _callbacks = std::move(right._callbacks);
 }
References _callbacks, _isPrepared, ConstructActiveMember, MoveFrom, and align::right.
~QueryCallback()
QueryCallback::~QueryCallback ()
Definition at line 144 of file QueryCallback.cpp.
 {
     DestroyActiveMember(this);
 }
References DestroyActiveMember.
QueryCallback() [4/4]
QueryCallback::QueryCallback (QueryCallback const & right) private delete
Member Function Documentation
InvokeIfReady()
bool QueryCallback::InvokeIfReady ()
Definition at line 178 of file QueryCallback.cpp.
 {
     QueryCallbackData& callback = _callbacks.front();
     auto checkStateAndReturnCompletion = [this]()
     {
         _callbacks.pop();
         bool hasNext = !_isPrepared ? _string.valid() : _prepared.valid();
         if (_callbacks.empty())
         {
             ASSERT(!hasNext);
             return true;
         }
         // abort chain
         if (!hasNext)
             return true;
         ASSERT(_isPrepared == _callbacks.front()._isPrepared);
         return false;
     };
     if (!_isPrepared)
     {
         if (_string.valid() && _string.wait_for(std::chrono::seconds(0)) == std::future_status::ready)
         {
             QueryResultFuture f(std::move(_string));
             std::function<void(QueryCallback&, QueryResult)> cb(std::move(callback._string));
             cb(*this, f.get());
             return checkStateAndReturnCompletion();
         }
     }
     else
     {
         if (_prepared.valid() && _prepared.wait_for(std::chrono::seconds(0)) == std::future_status::ready)
         {
             PreparedQueryResultFuture f(std::move(_prepared));
             std::function<void(QueryCallback&, PreparedQueryResult)> cb(std::move(callback._prepared));
             cb(*this, f.get());
             return checkStateAndReturnCompletion();
         }
     }
     return false;
 }
References _callbacks, _isPrepared, QueryCallback::QueryCallbackData::_prepared, _prepared, QueryCallback::QueryCallbackData::_string, _string, ASSERT, f(), and G3D::units::seconds().
operator=() [1/2]
QueryCallback & QueryCallback::operator= (QueryCallback && right)
Definition at line 128 of file QueryCallback.cpp.
 {
     if (this != &right)
     {
         if (_isPrepared != right._isPrepared)
         {
             DestroyActiveMember(this);
             _isPrepared = right._isPrepared;
             ConstructActiveMember(this);
         }
         MoveFrom(this, std::move(right));
         _callbacks = std::move(right._callbacks);
     }
     return *this;
 }
References _callbacks, _isPrepared, ConstructActiveMember, DestroyActiveMember, MoveFrom, and align::right.
operator=() [2/2]
QueryCallback& QueryCallback::operator= (QueryCallback const & right) private delete
SetNextQuery()
void QueryCallback::SetNextQuery (QueryCallback && next)
Definition at line 173 of file QueryCallback.cpp.
 {
     MoveFrom(this, std::move(next));
 }
References MoveFrom, and next().
Referenced by WorldSession::HandleCharCreateOpcode().
WithCallback()
QueryCallback && QueryCallback::WithCallback (std::function< void(QueryResult)> && callback)
Definition at line 149 of file QueryCallback.cpp.
 {
     return WithChainingCallback([callback](QueryCallback& /*this*/, QueryResult result) { callback(std::move(result)); });
 }
References WithChainingCallback().
WithChainingCallback()
QueryCallback && QueryCallback::WithChainingCallback (std::function< void(QueryCallback &, QueryResult)> && callback)
Definition at line 159 of file QueryCallback.cpp.
 {
     ASSERT(!_callbacks.empty() || !_isPrepared, "Attempted to set callback function for string query on a prepared async query");
     _callbacks.emplace(std::move(callback));
     return std::move(*this);
 }
References _callbacks, _isPrepared, and ASSERT.
Referenced by WithCallback().
WithChainingPreparedCallback()
QueryCallback && QueryCallback::WithChainingPreparedCallback (std::function< void(QueryCallback &, PreparedQueryResult)> && callback)
Definition at line 166 of file QueryCallback.cpp.
 {
     ASSERT(!_callbacks.empty() || _isPrepared, "Attempted to set callback function for prepared query on a string async query");
     _callbacks.emplace(std::move(callback));
     return std::move(*this);
 }
References _callbacks, _isPrepared, and ASSERT.
Referenced by WithPreparedCallback().
WithPreparedCallback()
QueryCallback && QueryCallback::WithPreparedCallback (std::function< void(PreparedQueryResult)> && callback)
Definition at line 154 of file QueryCallback.cpp.
 {
     return WithChainingPreparedCallback([callback](QueryCallback& /*this*/, PreparedQueryResult result) { callback(std::move(result)); });
 }
References WithChainingPreparedCallback().
Friends And Related Function Documentation
ConstructActiveMember
template<typename T > void ConstructActiveMember (T * obj) friend
Definition at line 34 of file QueryCallback.cpp.
 {
     if (!obj->_isPrepared)
         Construct(obj->_string);
     else
         Construct(obj->_prepared);
 }
Referenced by operator=(), and QueryCallback().
DestroyActiveMember
template<typename T > void DestroyActiveMember (T * obj) friend
Definition at line 43 of file QueryCallback.cpp.
 {
     if (!obj->_isPrepared)
         Destroy(obj->_string);
     else
         Destroy(obj->_prepared);
 }
Referenced by operator=(), and ~QueryCallback().
MoveFrom
template<typename T > void MoveFrom (T * to, T && from) friend
Definition at line 52 of file QueryCallback.cpp.
 {
     ASSERT(to->_isPrepared == from._isPrepared);
     if (!to->_isPrepared)
         to->_string = std::move(from._string);
     else
         to->_prepared = std::move(from._prepared);
 }
Referenced by operator=(), QueryCallback(), and SetNextQuery().
Member Data Documentation
union { ... }
_callbacks
std::queue<QueryCallbackData, std::list<QueryCallbackData> > QueryCallback::_callbacks private
Definition at line 66 of file QueryCallback.h.
Referenced by InvokeIfReady(), operator=(), QueryCallback(), WithChainingCallback(), and WithChainingPreparedCallback().
_isPrepared
bool QueryCallback::_isPrepared private
Definition at line 63 of file QueryCallback.h.
Referenced by InvokeIfReady(), operator=(), QueryCallback(), WithChainingCallback(), and WithChainingPreparedCallback().
_prepared
PreparedQueryResultFuture QueryCallback::_prepared
Definition at line 61 of file QueryCallback.h.
Referenced by InvokeIfReady().
_string
QueryResultFuture QueryCallback::_string
Definition at line 60 of file QueryCallback.h.
Referenced by InvokeIfReady().
The documentation for this class was generated from the following files:
src/server/database/Database/QueryCallback.h
src/server/database/Database/QueryCallback.cpp