Azerotcore-wotlk: MessageBuffer Class Reference
MessageBuffer Class Reference
#include <MessageBuffer.h>
Public Member Functions
MessageBuffer ()
MessageBuffer (std::size_t initialSize)
MessageBuffer (MessageBuffer const &right)
MessageBuffer (MessageBuffer &&right) noexcept
void Reset ()
void Resize (size_type bytes)
uint8 * GetBasePointer ()
uint8 * GetReadPointer ()
uint8 * GetWritePointer ()
void ReadCompleted (size_type bytes)
void WriteCompleted (size_type bytes)
size_type GetActiveSize () const
size_type GetRemainingSpace () const
size_type GetBufferSize () const
void Normalize ()
void EnsureFreeSpace ()
void Write (void const *data, std::size_t size)
std::vector< uint8 > && Move ()
MessageBuffer & operator= (MessageBuffer const &right)
MessageBuffer & operator= (MessageBuffer &&right) noexcept
Private Types
using size_type = std::vector< uint8 >::size_type
Private Attributes
size_type _wpos
size_type _rpos
std::vector< uint8 > _storage
Detailed Description
Definition at line 25 of file MessageBuffer.h.
Member Typedef Documentation
size_type
using MessageBuffer::size_type = std::vector<uint8>::size_type private
Definition at line 27 of file MessageBuffer.h.
Constructor & Destructor Documentation
MessageBuffer() [1/4]
MessageBuffer::MessageBuffer () inline
Definition at line 30 of file MessageBuffer.h.
                     : _wpos(0), _rpos(0), _storage()
     {
         _storage.resize(4096);
     }
References _storage.
MessageBuffer() [2/4]
MessageBuffer::MessageBuffer (std::size_t initialSize) inline explicit
Definition at line 35 of file MessageBuffer.h.
                                                   : _wpos(0), _rpos(0), _storage()
     {
         _storage.resize(initialSize);
     }
References _storage.
MessageBuffer() [3/4]
MessageBuffer::MessageBuffer (MessageBuffer const & right) inline
Definition at line 40 of file MessageBuffer.h.
                                               :
         _wpos(right._wpos), _rpos(right._rpos), _storage(right._storage) { }
MessageBuffer() [4/4]
MessageBuffer::MessageBuffer (MessageBuffer && right) inline noexcept
Definition at line 43 of file MessageBuffer.h.
                                                   :
         _wpos(right._wpos), _rpos(right._rpos), _storage(right.Move()) { }
Member Function Documentation
EnsureFreeSpace()
void MessageBuffer::EnsureFreeSpace () inline
Definition at line 84 of file MessageBuffer.h.
     {
         // resize buffer if it's already full
         if (GetRemainingSpace() == 0)
         {
             _storage.resize(_storage.size() * 3 / 2);
         }
     }
References _storage, and GetRemainingSpace().
Referenced by Socket< T >::AsyncRead(), and Socket< T >::AsyncReadWithCallback().
GetActiveSize()
size_type MessageBuffer::GetActiveSize () const inline
Definition at line 64 of file MessageBuffer.h.
 { return _wpos - _rpos; }
References _rpos, and _wpos.
Referenced by Socket< T >::HandleQueue(), Normalize(), AuthSession::ReadHandler(), WorldSocket::ReadHandler(), and WorldSocket::ReadHeaderHandler().
GetBasePointer()
uint8* MessageBuffer::GetBasePointer () inline
Definition at line 57 of file MessageBuffer.h.
 { return _storage.data(); }
References _storage.
Referenced by GetReadPointer(), GetWritePointer(), and Normalize().
GetBufferSize()
size_type MessageBuffer::GetBufferSize () const inline
Definition at line 66 of file MessageBuffer.h.
 { return _storage.size(); }
References _storage.
GetReadPointer()
uint8* MessageBuffer::GetReadPointer () inline
Definition at line 58 of file MessageBuffer.h.
 { return GetBasePointer() + _rpos; }
References _rpos, and GetBasePointer().
Referenced by AuthSession::HandleLogonChallenge(), AuthSession::HandleLogonProof(), Socket< T >::HandleQueue(), AuthSession::HandleReconnectChallenge(), AuthSession::HandleReconnectProof(), Normalize(), WorldSocket::ReadDataHandler(), AuthSession::ReadHandler(), WorldSocket::ReadHandler(), and WorldSocket::ReadHeaderHandler().
GetRemainingSpace()
size_type MessageBuffer::GetRemainingSpace () const inline
Definition at line 65 of file MessageBuffer.h.
 { return _storage.size() - _wpos; }
References _storage, and _wpos.
Referenced by Socket< T >::AsyncRead(), Socket< T >::AsyncReadWithCallback(), EnsureFreeSpace(), and WorldSocket::ReadHandler().
GetWritePointer()
uint8* MessageBuffer::GetWritePointer () inline
Definition at line 59 of file MessageBuffer.h.
 { return GetBasePointer() + _wpos; }
References _wpos, and GetBasePointer().
Referenced by Socket< T >::AsyncRead(), Socket< T >::AsyncReadWithCallback(), and Write().
Move()
std::vector<uint8>&& MessageBuffer::Move () inline
Definition at line 102 of file MessageBuffer.h.
     {
         _wpos = 0;
         _rpos = 0;
         return std::move(_storage);
     }
References _rpos, _storage, and _wpos.
Normalize()
void MessageBuffer::Normalize () inline
Definition at line 69 of file MessageBuffer.h.
     {
         if (_rpos)
         {
             if (_rpos != _wpos)
             {
                 memmove(GetBasePointer(), GetReadPointer(), GetActiveSize());
             }
             _wpos -= _rpos;
             _rpos = 0;
         }
     }
References _rpos, _wpos, GetActiveSize(), GetBasePointer(), GetReadPointer(), and memmove.
Referenced by Socket< T >::AsyncRead(), and Socket< T >::AsyncReadWithCallback().
operator=() [1/2]
MessageBuffer& MessageBuffer::operator= (MessageBuffer && right) inline noexcept
Definition at line 122 of file MessageBuffer.h.
     {
         if (this != &right)
         {
             _wpos = right._wpos;
             _rpos = right._rpos;
             _storage = right.Move();
         }
         return *this;
     }
References _rpos, _storage, _wpos, and align::right.
operator=() [2/2]
MessageBuffer& MessageBuffer::operator= (MessageBuffer const & right) inline
Definition at line 110 of file MessageBuffer.h.
     {
         if (this != &right)
         {
             _wpos = right._wpos;
             _rpos = right._rpos;
             _storage = right._storage;
         }
         return *this;
     }
References _rpos, _storage, _wpos, and align::right.
ReadCompleted()
void MessageBuffer::ReadCompleted (size_type bytes) inline
Definition at line 61 of file MessageBuffer.h.
 { _rpos += bytes; }
References _rpos.
Referenced by AuthSession::HandleLogonProof(), Socket< T >::HandleQueue(), AuthSession::ReadHandler(), and WorldSocket::ReadHandler().
Reset()
void MessageBuffer::Reset () inline
Definition at line 46 of file MessageBuffer.h.
     {
         _wpos = 0;
         _rpos = 0;
     }
References _rpos, and _wpos.
Referenced by AuthSession::ReadHandler(), and WorldSocket::ReadHandler().
Resize()
void MessageBuffer::Resize (size_type bytes) inline
Definition at line 52 of file MessageBuffer.h.
     {
         _storage.resize(bytes);
     }
References _storage.
Referenced by WorldSocket::ReadHeaderHandler(), Socket< T >::Socket(), and WorldSocket::WorldSocket().
Write()
void MessageBuffer::Write (void const * data, std::size_t size) inline
Definition at line 93 of file MessageBuffer.h.
     {
         if (size)
         {
             memcpy(GetWritePointer(), data, size);
             WriteCompleted(size);
         }
     }
References GetWritePointer(), memcpy, and WriteCompleted().
Referenced by WorldSocket::ReadHandler(), and WorldSocket::Update().
WriteCompleted()
void MessageBuffer::WriteCompleted (size_type bytes) inline
Definition at line 62 of file MessageBuffer.h.
 { _wpos += bytes; }
References _wpos.
Referenced by Socket< T >::ReadHandlerInternal(), and Write().
Member Data Documentation
_rpos
size_type MessageBuffer::_rpos private
Definition at line 136 of file MessageBuffer.h.
Referenced by GetActiveSize(), GetReadPointer(), Move(), Normalize(), operator=(), ReadCompleted(), and Reset().
_storage
std::vector<uint8> MessageBuffer::_storage private
Definition at line 137 of file MessageBuffer.h.
Referenced by EnsureFreeSpace(), GetBasePointer(), GetBufferSize(), GetRemainingSpace(), MessageBuffer(), Move(), operator=(), and Resize().
_wpos
size_type MessageBuffer::_wpos private
Definition at line 135 of file MessageBuffer.h.
Referenced by GetActiveSize(), GetRemainingSpace(), GetWritePointer(), Move(), Normalize(), operator=(), Reset(), and WriteCompleted().
The documentation for this class was generated from the following file:
src/common/Utilities/MessageBuffer.h