Azerotcore-wotlk: boss_priestess_lackey_commonAI Struct Reference
boss_priestess_lackey_commonAI Struct Reference
Public Member Functions
boss_priestess_lackey_commonAI (Creature *creature, uint32 type)
float GetThreatMod (float dist, float, uint32 health, uint32, Unit *target)
void RecalculateThreat ()
void Reset () override
void JustSummoned (Creature *summon) override
void EnterEvadeMode () override
void EnterCombat (Unit *who) override
void JustDied (Unit *) override
void KilledUnit (Unit *victim) override
void AttackStart (Unit *victim) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * instance
EventMap events
SummonList summons
uint32 actualEventId
uint8 aiType
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 274 of file boss_priestess_delrissa.cpp.
Constructor & Destructor Documentation
boss_priestess_lackey_commonAI()
boss_priestess_lackey_commonAI::boss_priestess_lackey_commonAI (Creature * creature, uint32 type) inline
Definition at line 276 of file boss_priestess_delrissa.cpp.
                                                                     : ScriptedAI(creature), summons(me)
     {
         instance = creature->GetInstanceScript();
         aiType = type;
     }
References aiType, WorldObject::GetInstanceScript(), and instance.
Member Function Documentation
AttackStart()
void boss_priestess_lackey_commonAI::AttackStart (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 364 of file boss_priestess_delrissa.cpp.
     {
         if (victim && me->Attack(victim, true))
             me->GetMotionMaster()->MoveChase(victim, aiType == AI_TYPE_MELEE ? 0.0f : 20.0f);
     }
References AI_TYPE_MELEE, aiType, Unit::Attack(), Unit::GetMotionMaster(), ScriptedAI::me, and MotionMaster::MoveChase().
EnterCombat()
void boss_priestess_lackey_commonAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Reimplemented in boss_zelfan::boss_zelfanAI, boss_apoko::boss_apokoAI, boss_garaxxas::boss_garaxxasAI, boss_warlord_salaris::boss_warlord_salarisAI, boss_yazzai::boss_yazzaiAI, boss_eramas_brightblaze::boss_eramas_brightblazeAI, boss_ellris_duskhallow::boss_ellris_duskhallowAI, and boss_kagani_nightstrike::boss_kagani_nightstrikeAI.
Definition at line 339 of file boss_priestess_delrissa.cpp.
     {
         if (Creature* delrissa = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_DELRISSA)))
             if (delrissa->IsAlive() && !delrissa->IsInCombat())
                 delrissa->AI()->AttackStart(who);
         events.ScheduleEvent(EVENT_SPELL_HELPER_HEALING_POTION, 1000);
         events.ScheduleEvent(EVENT_HELPER_RESET_THREAT, urand(8000, 10000));
         if (IsHeroic())
             events.ScheduleEvent(EVENT_SPELL_HELPER_IMMUNITY, 2000, 1);
         RecalculateThreat();
     }
References EVENT_HELPER_RESET_THREAT, EVENT_SPELL_HELPER_HEALING_POTION, EVENT_SPELL_HELPER_IMMUNITY, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), instance, ScriptedAI::IsHeroic(), ScriptedAI::me, NPC_DELRISSA, RecalculateThreat(), and urand().
Referenced by boss_kagani_nightstrike::boss_kagani_nightstrikeAI::EnterCombat(), boss_ellris_duskhallow::boss_ellris_duskhallowAI::EnterCombat(), boss_eramas_brightblaze::boss_eramas_brightblazeAI::EnterCombat(), boss_yazzai::boss_yazzaiAI::EnterCombat(), boss_warlord_salaris::boss_warlord_salarisAI::EnterCombat(), boss_garaxxas::boss_garaxxasAI::EnterCombat(), boss_apoko::boss_apokoAI::EnterCombat(), and boss_zelfan::boss_zelfanAI::EnterCombat().
EnterEvadeMode()
void boss_priestess_lackey_commonAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 328 of file boss_priestess_delrissa.cpp.
     {
         if (Creature* delrissa = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_DELRISSA)))
             if (!delrissa->IsAlive())
             {
                 delrissa->Respawn();
                 return;
             }
         ScriptedAI::EnterEvadeMode();
     }
References CreatureAI::EnterEvadeMode(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), instance, ScriptedAI::me, and NPC_DELRISSA.
GetThreatMod()
float boss_priestess_lackey_commonAI::GetThreatMod (float dist, float , uint32 health, uint32 , Unit * target) inline
Definition at line 288 of file boss_priestess_delrissa.cpp.
     {
         float unimportant_dist = (aiType == AI_TYPE_MELEE ? 5.0f : 25.0f);
         if (dist > unimportant_dist) dist -= unimportant_dist;
         else dist = 0.0f;
         const float dist_factor = (aiType == AI_TYPE_MELEE ? 15.0f : 25.0f);
         float mod_dist = dist_factor / (dist_factor + dist); // 0.2 .. 1.0
         float mod_health = health > 20000 ? 2.0f : (40000 - health) / 10000.0f; // 2.0 .. 4.0
         float mod_armor = aiType == AI_TYPE_MELEE ? Unit::CalcArmorReducedDamage(me, target, 10000, nullptr) / 10000.0f : 1.0f;
         return mod_dist * mod_health * mod_armor;
     }
References AI_TYPE_MELEE, aiType, Unit::CalcArmorReducedDamage(), and ScriptedAI::me.
Referenced by RecalculateThreat().
JustDied()
void boss_priestess_lackey_commonAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 353 of file boss_priestess_delrissa.cpp.
     {
         summons.DespawnAll();
     }
References SummonList::DespawnAll(), and summons.
JustSummoned()
void boss_priestess_lackey_commonAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 323 of file boss_priestess_delrissa.cpp.
     {
         summons.Summon(summon);
     }
References SummonList::Summon(), and summons.
KilledUnit()
void boss_priestess_lackey_commonAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 358 of file boss_priestess_delrissa.cpp.
     {
         if (Creature* delrissa = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_DELRISSA)))
             delrissa->AI()->KilledUnit(victim);
     }
References ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), instance, ScriptedAI::me, and NPC_DELRISSA.
RecalculateThreat()
void boss_priestess_lackey_commonAI::RecalculateThreat () inline
Definition at line 300 of file boss_priestess_delrissa.cpp.
     {
         ThreatContainer::StorageType const& tList = me->getThreatMgr().getThreatList();
         for( ThreatContainer::StorageType::const_iterator itr = tList.begin(); itr != tList.end(); ++itr )
         {
             Unit* pUnit = ObjectAccessor::GetUnit(*me, (*itr)->getUnitGuid());
             if( pUnit && pUnit->GetTypeId() == TYPEID_PLAYER && me->getThreatMgr().getThreat(pUnit) )
             {
                 float threatMod = GetThreatMod(me->GetDistance2d(pUnit), (float)pUnit->GetArmor(), pUnit->GetHealth(), pUnit->GetMaxHealth(), pUnit);
                 me->getThreatMgr().modifyThreatPercent(pUnit, -100);
                 if (HostileReference* ref = me->getThreatMgr().getOnlineContainer().getReferenceByTarget(pUnit))
                     ref->addThreat(10000000.0f * threatMod);
             }
         }
     }
References Unit::GetArmor(), WorldObject::GetDistance2d(), Unit::GetHealth(), Unit::GetMaxHealth(), ThreatMgr::getOnlineContainer(), ThreatContainer::getReferenceByTarget(), ThreatMgr::getThreat(), ThreatMgr::getThreatList(), Unit::getThreatMgr(), GetThreatMod(), Object::GetTypeId(), ObjectAccessor::GetUnit(), ScriptedAI::me, ThreatMgr::modifyThreatPercent(), and TYPEID_PLAYER.
Referenced by EnterCombat(), and UpdateAI().
Reset()
void boss_priestess_lackey_commonAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Reimplemented in boss_garaxxas::boss_garaxxasAI.
Definition at line 316 of file boss_priestess_delrissa.cpp.
     {
         events.Reset();
         summons.DespawnAll();
         actualEventId = 0;
     }
References actualEventId, SummonList::DespawnAll(), and summons.
Referenced by boss_garaxxas::boss_garaxxasAI::Reset().
UpdateAI()
void boss_priestess_lackey_commonAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Reimplemented in boss_zelfan::boss_zelfanAI, boss_apoko::boss_apokoAI, boss_garaxxas::boss_garaxxasAI, boss_warlord_salaris::boss_warlord_salarisAI, boss_yazzai::boss_yazzaiAI, boss_eramas_brightblaze::boss_eramas_brightblazeAI, boss_ellris_duskhallow::boss_ellris_duskhallowAI, and boss_kagani_nightstrike::boss_kagani_nightstrikeAI.
Definition at line 370 of file boss_priestess_delrissa.cpp.
     {
         actualEventId = 0;
         events.Update(diff);
         if (me->HasUnitState(UNIT_STATE_CASTING))
             return;
         actualEventId = events.ExecuteEvent();
         switch (actualEventId)
         {
             case EVENT_SPELL_HELPER_IMMUNITY:
                 if (me->HasUnitState(UNIT_STATE_LOST_CONTROL))
                 {
                     me->CastSpell(me, SPELL_MEDALION_OF_IMMUNITY, false);
                     events.ScheduleEvent(EVENT_SPELL_HELPER_IMMUNITY, 60000);
                 }
                 else
                     events.ScheduleEvent(EVENT_SPELL_HELPER_IMMUNITY, 1000);
                 break;
             case EVENT_SPELL_HELPER_HEALING_POTION:
                 if (me->HealthBelowPct(25))
                 {
                     me->CastSpell(me, SPELL_HEALING_POTION, false);
                     break;
                 }
                 events.ScheduleEvent(EVENT_SPELL_HELPER_HEALING_POTION, 1000);
                 break;
             case EVENT_HELPER_RESET_THREAT:
                 RecalculateThreat();
                 events.ScheduleEvent(EVENT_HELPER_RESET_THREAT, urand(8000, 10000));
                 break;
         }
     }
References actualEventId, Unit::CastSpell(), EVENT_HELPER_RESET_THREAT, EVENT_SPELL_HELPER_HEALING_POTION, EVENT_SPELL_HELPER_IMMUNITY, Unit::HasUnitState(), Unit::HealthBelowPct(), ScriptedAI::me, RecalculateThreat(), SPELL_HEALING_POTION, SPELL_MEDALION_OF_IMMUNITY, UNIT_STATE_CASTING, UNIT_STATE_LOST_CONTROL, and urand().
Referenced by boss_kagani_nightstrike::boss_kagani_nightstrikeAI::UpdateAI(), boss_ellris_duskhallow::boss_ellris_duskhallowAI::UpdateAI(), boss_eramas_brightblaze::boss_eramas_brightblazeAI::UpdateAI(), boss_yazzai::boss_yazzaiAI::UpdateAI(), boss_warlord_salaris::boss_warlord_salarisAI::UpdateAI(), boss_garaxxas::boss_garaxxasAI::UpdateAI(), boss_apoko::boss_apokoAI::UpdateAI(), and boss_zelfan::boss_zelfanAI::UpdateAI().
Member Data Documentation
actualEventId
uint32 boss_priestess_lackey_commonAI::actualEventId
Definition at line 285 of file boss_priestess_delrissa.cpp.
Referenced by Reset(), UpdateAI(), boss_kagani_nightstrike::boss_kagani_nightstrikeAI::UpdateAI(), boss_ellris_duskhallow::boss_ellris_duskhallowAI::UpdateAI(), boss_eramas_brightblaze::boss_eramas_brightblazeAI::UpdateAI(), boss_yazzai::boss_yazzaiAI::UpdateAI(), boss_warlord_salaris::boss_warlord_salarisAI::UpdateAI(), boss_garaxxas::boss_garaxxasAI::UpdateAI(), boss_apoko::boss_apokoAI::UpdateAI(), and boss_zelfan::boss_zelfanAI::UpdateAI().
aiType
uint8 boss_priestess_lackey_commonAI::aiType
Definition at line 286 of file boss_priestess_delrissa.cpp.
Referenced by AttackStart(), boss_priestess_lackey_commonAI(), and GetThreatMod().
events
EventMap boss_priestess_lackey_commonAI::events
Definition at line 283 of file boss_priestess_delrissa.cpp.
instance
InstanceScript* boss_priestess_lackey_commonAI::instance
Definition at line 282 of file boss_priestess_delrissa.cpp.
Referenced by boss_priestess_lackey_commonAI(), EnterCombat(), EnterEvadeMode(), and KilledUnit().
summons
SummonList boss_priestess_lackey_commonAI::summons
Definition at line 284 of file boss_priestess_delrissa.cpp.
Referenced by JustDied(), JustSummoned(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/MagistersTerrace/boss_priestess_delrissa.cpp