Azerotcore-wotlk: detail Namespace Reference
detail Namespace Reference
Namespaces
digits
dragonbox
Classes
struct is_reference_wrapper
struct is_reference_wrapper< std::reference_wrapper< T > >
class dynamic_arg_list
struct null
class counting_iterator
class truncating_iterator_base
class truncating_iterator
class truncating_iterator< OutputIt, std::false_type >
class truncating_iterator< OutputIt, std::true_type >
class compiled_string
struct is_compiled_string
struct bits
struct boundaries
class fp
struct accumulator
class bigint
struct fixed_handler
struct uint128_wrapper
struct fallback_uintptr
struct is_locale
struct is_locale< T, void_t< decltype(T::classic())> >
class formatbuf
struct converter
struct test_stream
class is_streamable
struct fallback_formatter< T, Char, enable_if_t< is_streamable< T, Char >::value > >
class is_std_string_like
Return true value if T has std::string interface, like std::string_view.
struct is_std_string_like< fmt::basic_string_view< Char > >
struct conditional_helper
struct is_range_
struct has_member_fn_begin_end_t
struct has_member_fn_begin_end_t< T, void_t< decltype(std::declval< T >().begin()), decltype(std::declval< T >().end())> >
struct has_const_begin_end
struct has_mutable_begin_end
struct has_const_begin_end< T, void_t< decltype(detail::range_begin(std::declval< const remove_cvref_t< T > & >())), decltype(detail::range_begin(std::declval< const remove_cvref_t< T > & >()))> >
struct has_mutable_begin_end< T, void_t< decltype(detail::range_begin(std::declval< T >())), decltype(detail::range_begin(std::declval< T >())), enable_if_t< std::is_copy_constructible< T >::value > > >
struct is_range_< T, void >
struct range_to_view
struct range_to_view< T, enable_if_t< has_const_begin_end< T >::value > >
struct range_to_view< T, enable_if_t<!has_const_begin_end< T >::value &&has_mutable_begin_end< T >::value > >
class is_tuple_like_
tuple_size and tuple_element check.
struct integer_sequence
struct make_integer_sequence
struct make_integer_sequence< T, 0, Ns... >
Typedefs
using uintptr_t = fallback_uintptr
template<typename T >
using iterator_t = decltype(std::begin(std::declval< T & >()))
template<typename T >
using sentinel_t = decltype(std::end(std::declval< T & >()))
template<typename T >
using checked_ptr = T *
template<typename OutputIt >
using reserve_iterator = remove_reference_t< decltype(reserve(std::declval< OutputIt & >(), 0))>
template<typename T >
using is_fast_float = bool_constant< std::numeric_limits< T >::is_iec559 &&sizeof(T)<=sizeof(double)>
template<size_t... N>
using index_sequence = integer_sequence< size_t, N... >
template<size_t N>
using make_index_sequence = make_integer_sequence< size_t, N >
template<typename Range >
using value_type = remove_cvref_t< decltype(*detail::range_begin(std::declval< Range >()))>
template<typename T >
using is_exotic_char = bool_constant<!std::is_same< T, char >::value >
Enumerations
enum class round_direction { unknown , up , down }
enum char8_type : unsigned char
Functions
template<typename T >
const T & unwrap (const T &v)
template<typename T >
const T & unwrap (const std::reference_wrapper< T > &v)
null localtime_r FMT_NOMACRO (...)
null localtime_s (...)
null gmtime_r (...)
null gmtime_s (...)
auto do_write (const std::tm &time, const std::locale &loc, char format, char modifier) -> std::string
template<typename OutputIt >
auto write (OutputIt out, const std::tm &time, const std::locale &loc, char format, char modifier=0) -> OutputIt
template<typename Char , typename InputIt >
counting_iterator copy_str (InputIt begin, InputIt end, counting_iterator it)
template<typename T , typename... Tail>
const T & first (const T &value, const Tail &...)
FMT_FUNC void assert_fail (const char *file, int line, const char *message)
FMT_FUNC void format_error_code (detail::buffer< char > &out, int error_code, string_view message) FMT_NOEXCEPT
FMT_FUNC void report_error (format_func func, int error_code, const char *message) FMT_NOEXCEPT
void fwrite_fully (const void *ptr, size_t size, size_t count, FILE *stream)
template<typename Char >
FMT_FUNC auto thousands_sep_impl (locale_ref loc) -> thousands_sep_result< Char >
template<typename Char >
FMT_FUNC Char decimal_point_impl (locale_ref loc)
template<>
FMT_FUNC int count_digits< 4 > (detail::fallback_uintptr n)
template<int SHIFT = 0>
fp normalize (fp value)
bool operator== (fp x, fp y)
uint64_t multiply (uint64_t lhs, uint64_t rhs)
fp operator* (fp x, fp y)
fp get_cached_power (int min_exponent, int &pow10_exponent)
round_direction get_round_direction (uint64_t divisor, uint64_t remainder, uint64_t error)
uint64_t power_of_10_64 (int exp)
template<typename Handler >
FMT_INLINE digits::result grisu_gen_digits (fp value, uint64_t error, int &exp, Handler &handler)
template<typename Double >
void fallback_format (Double d, int num_digits, bool binary32, buffer< char > &buf, int &exp10)
template<typename T >
int format_float (T value, int precision, float_specs specs, buffer< char > &buf)
template<typename T >
int snprintf_float (T value, int precision, float_specs specs, buffer< char > &buf)
FMT_FUNC void print (std::FILE *f, string_view text)
template<typename Dest , typename Source >
auto bit_cast (const Source &source) -> Dest
auto is_big_endian () -> bool
auto to_uintptr (const void *p) -> fallback_uintptr
template<typename T >
constexpr auto max_value () -> T
template<typename T >
constexpr auto num_bits () -> int
template<>
constexpr auto num_bits< int128_t > () -> int
template<>
constexpr auto num_bits< uint128_t > () -> int
template<>
constexpr auto num_bits< fallback_uintptr > () -> int
FMT_INLINE void assume (bool condition)
template<typename Char >
auto get_data (std::basic_string< Char > &s) -> Char *
template<typename Container >
auto get_data (Container &c) -> typename Container::value_type *
template<typename T >
auto make_checked (T *p, size_t) -> T *
template<typename Container , FMT_ENABLE_IF(is_contiguous< Container >::value) >
auto reserve (std::back_insert_iterator< Container > it, size_t n) -> checked_ptr< typename Container::value_type >
template<typename T >
auto reserve (buffer_appender< T > it, size_t n) -> buffer_appender< T >
template<typename Iterator >
constexpr auto reserve (Iterator &it, size_t) -> Iterator &
template<typename T , typename OutputIt >
constexpr auto to_pointer (OutputIt, size_t) -> T *
template<typename T >
auto to_pointer (buffer_appender< T > it, size_t n) -> T *
template<typename Container , FMT_ENABLE_IF(is_contiguous< Container >::value) >
auto base_iterator (std::back_insert_iterator< Container > &it, checked_ptr< typename Container::value_type >) -> std::back_insert_iterator< Container >
template<typename Iterator >
constexpr auto base_iterator (Iterator, Iterator it) -> Iterator
template<typename OutputIt , typename Size , typename T >
FMT_CONSTEXPR auto fill_n (OutputIt out, Size count, const T &value) -> OutputIt
template<typename T , typename Size >
FMT_CONSTEXPR20 auto fill_n (T *out, Size count, char value) -> T *
template<typename OutChar , typename InputIt , typename OutputIt >
FMT_CONSTEXPR FMT_NOINLINE auto copy_str_noinline (InputIt begin, InputIt end, OutputIt out) -> OutputIt
FMT_CONSTEXPR auto utf8_decode (const char *s, uint32_t *c, int *e) -> const char *
template<typename F >
FMT_CONSTEXPR void for_each_codepoint (string_view s, F f)
template<typename Char >
auto compute_width (basic_string_view< Char > s) -> size_t
auto compute_width (basic_string_view< char8_type > s) -> size_t
template<typename Char >
auto code_point_index (basic_string_view< Char > s, size_t n) -> size_t
auto code_point_index (basic_string_view< char8_type > s, size_t n) -> size_t
template<typename Char , typename Traits >
void_t operator<< (std::basic_ostream< Char, Traits > &, Char)
template<typename Traits >
void_t operator<< (std::basic_ostream< char, Traits > &, char)
template<typename Traits >
void_t operator<< (std::basic_ostream< char, Traits > &, signed char)
template<typename Traits >
void_t operator<< (std::basic_ostream< char, Traits > &, unsigned char)
template<typename Char >
void write_buffer (std::basic_ostream< Char > &os, buffer< Char > &buf)
template<typename Char , typename T >
void format_value (buffer< Char > &buf, const T &value, locale_ref loc=locale_ref())
template<typename RangeT , typename OutputIterator >
OutputIterator copy (const RangeT &range, OutputIterator out)
template<typename OutputIterator >
OutputIterator copy (const char *str, OutputIterator out)
template<typename OutputIterator >
OutputIterator copy (char ch, OutputIterator out)
template<typename OutputIterator >
OutputIterator copy (wchar_t ch, OutputIterator out)
template<typename T , std::size_t N>
auto range_begin (const T(&arr)[N]) -> const T *
template<typename T , std::size_t N>
auto range_end (const T(&arr)[N]) -> const T *
template<typename T >
auto range_begin (T &&rng) FMT_DECLTYPE_RETURN(static_cast< T && >(rng).begin())
template<typename T >
auto range_end (T &&rng) FMT_DECLTYPE_RETURN(static_cast< T && >(rng).end())
template<typename T >
auto range_begin (T &&rng) -> enable_if_t<!has_member_fn_begin_end_t< T && >::value, decltype(begin(static_cast< T && >(rng)))>
template<typename T >
auto range_end (T &&rng) -> enable_if_t<!has_member_fn_begin_end_t< T && >::value, decltype(end(static_cast< T && >(rng)))>
template<class Tuple , class F , size_t... Is>
void for_each (index_sequence< Is... >, Tuple &&tup, F &&f) FMT_NOEXCEPT
template<class T >
FMT_CONSTEXPR make_index_sequence< std::tuple_size< T >::value > get_indexes (T const &)
template<class Tuple , class F >
void for_each (Tuple &&tup, F &&f)
template<typename OutputIt >
OutputIt write_delimiter (OutputIt out)
template<typename Char , typename OutputIt , typename Arg , FMT_ENABLE_IF(is_std_string_like< typename std::decay< Arg >::type >::value) >
OutputIt write_range_entry (OutputIt out, const Arg &v)
template<typename Char , typename OutputIt , typename Arg , FMT_ENABLE_IF(std::is_same< Arg, Char >::value) >
OutputIt write_range_entry (OutputIt out, const Arg v)
template<typename T >
int format_float (char *buf, std::size_t size, const char *format, int precision, T value)
Typedef Documentation
checked_ptr
template<typename T > using detail::checked_ptr = typedef T*
Definition at line 346 of file format.h.
index_sequence
template<size_t... N> using detail::index_sequence = typedef integer_sequence<size_t, N...>
Definition at line 214 of file ranges.h.
is_exotic_char
template<typename T > using detail::is_exotic_char = typedef bool_constant<!std::is_same<T, char>::value>
Definition at line 19 of file xchar.h.
is_fast_float
template<typename T > using detail::is_fast_float = typedef bool_constant<std::numeric_limits<T>::is_iec559 && sizeof(T) <= sizeof(double)>
Definition at line 568 of file format.h.
iterator_t
template<typename T > using detail::iterator_t = typedef decltype(std::begin(std::declval<T&>()))
Definition at line 326 of file format.h.
make_index_sequence
template<size_t N> using detail::make_index_sequence = typedef make_integer_sequence<size_t, N>
Definition at line 222 of file ranges.h.
reserve_iterator
template<typename OutputIt > using detail::reserve_iterator = typedef remove_reference_t<decltype(reserve(std::declval<OutputIt&>(), 0))>
Definition at line 378 of file format.h.
sentinel_t
template<typename T > using detail::sentinel_t = typedef decltype(std::end(std::declval<T&>()))
Definition at line 327 of file format.h.
uintptr_t
using detail::uintptr_t = typedef fallback_uintptr
Definition at line 295 of file format.h.
value_type
template<typename Range > using detail::value_type = typedef remove_cvref_t<decltype(*detail::range_begin(std::declval<Range>()))>
Definition at line 245 of file ranges.h.
Enumeration Type Documentation
char8_type
enum detail::char8_type : unsigned char
Definition at line 425 of file format.h.
 : unsigned char {};
round_direction
enum detail::round_direction strong
Enumerator
unknown
up
down
Definition at line 599 of file format-inl.h.
 { unknown, up, down };
Function Documentation
assert_fail()
FMT_FUNC void detail::assert_fail (const char * file, int line, const char * message)
Definition at line 34 of file format-inl.h.
{
   // Use unchecked std::fprintf to avoid triggering another assertion when
   // writing to stderr fails
   std::fprintf(stderr, "%s:%d: assertion failed: %s", file, line, message);
   // Chosen instead of std::abort to satisfy Clang in CUDA mode during device
   // code pass.
   std::terminate();
 }
References mpq::file, fprintf(), and message().
assume()
FMT_INLINE void detail::assume (bool condition)
Definition at line 317 of file format.h.
{
   (void)condition;
 #if FMT_HAS_BUILTIN(__builtin_assume)
   __builtin_assume(condition);
 #endif
 }
Referenced by to_string().
base_iterator() [1/2]
template<typename Iterator > constexpr auto detail::base_iterator (Iterator , Iterator it) -> Iterator constexpr
Definition at line 401 of file format.h.
{
   return it;
 }
Referenced by write(), write_float(), write_int(), write_padded(), and write_ptr().
base_iterator() [2/2]
template<typename Container , FMT_ENABLE_IF(is_contiguous< Container >::value) > auto detail::base_iterator (std::back_insert_iterator< Container > & it, checked_ptr< typename Container::value_type >) -> std::back_insert_iterator<Container> inline
Definition at line 394 of file format.h.
{
   return it;
 }
bit_cast()
template<typename Dest , typename Source > auto detail::bit_cast (const Source & source) -> Dest inline
Definition at line 261 of file format.h.
{
   static_assert(sizeof(Dest) == sizeof(Source), "size mismatch");
   Dest dest;
   std::memcpy(&dest, &source, sizeof(dest));
   return dest;
 }
References memcpy.
code_point_index() [1/2]
template<typename Char > auto detail::code_point_index (basic_string_view< Char > s, size_t n) -> size_t inline
Definition at line 551 of file format.h.
{
   size_t size = s.size();
   return n < size ? n : size;
 }
References basic_string_view< Char >::size().
code_point_index() [2/2]
auto detail::code_point_index (basic_string_view< char8_type > s, size_t n) -> size_t inline
Definition at line 557 of file format.h.
               {
   const char8_type* data = s.data();
   size_t num_code_points = 0;
   for (size_t i = 0, size = s.size(); i != size; ++i) {
     if ((data[i] & 0xc0) != 0x80 && ++num_code_points > n) return i;
   }
   return s.size();
 }
References basic_string_view< Char >::data(), and basic_string_view< Char >::size().
Referenced by write().
compute_width() [1/2]
template<typename Char > FMT_CONSTEXPR size_t detail::compute_width (basic_string_view< Char > s) -> size_t inline
Definition at line 508 of file format.h.
{
   return s.size();
 }
Referenced by compute_width().
compute_width() [2/2]
auto detail::compute_width (basic_string_view< char8_type > s) -> size_t inline
Definition at line 545 of file format.h.
{
   return compute_width(basic_string_view<char>(
       reinterpret_cast<const char*>(s.data()), s.size()));
 }
References compute_width(), basic_string_view< Char >::data(), and basic_string_view< Char >::size().
Referenced by write().
copy() [1/4]
template<typename OutputIterator > OutputIterator detail::copy (char ch, OutputIterator out)
Definition at line 63 of file ranges.h.
{
   *out++ = ch;
   return out;
 }
copy() [2/4]
template<typename OutputIterator > OutputIterator detail::copy (const char * str, OutputIterator out)
Definition at line 57 of file ranges.h.
{
   while (*str) *out++ = *str++;
   return out;
 }
copy() [3/4]
template<typename RangeT , typename OutputIterator > OutputIterator detail::copy (const RangeT & range, OutputIterator out)
Definition at line 50 of file ranges.h.
{
   for (auto it = range.begin(), end = range.end(); it != end; ++it)
     *out++ = *it;
   return out;
 }
Referenced by detail::bigint::assign(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::balance(), copy_unit(), Acore::CreateChildProcess(), formatter< std::tm, Char >::format(), detail::fallback_formatter< T, Char, enable_if_t< is_streamable< T, Char >::value > >::format(), formatter< T, Char, enable_if_t< fmt::is_range< T, Char >::value &&(has_formatter< detail::value_type< T >, format_context >::value||detail::has_fallback_formatter< detail::value_type< T >, Char >::value) > >::format(), formatter< TupleT, Char, enable_if_t< fmt::is_tuple_like< TupleT >::value > >::format(), HandleArgs(), inflate(), inflateBack(), inflateCopy(), init_tmpdir(), Battlefield::InvitePlayersInQueueToWar(), Movement::MoveSplineInit::Launch(), RealmList::LoadBuildInfo(), WardenCheckMgr::LoadWardenChecks(), G3D::md5_append(), chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_text(), ScriptMgr::OnPacketReceive(), ScriptMgr::OnPacketSend(), Motd::SetMotd(), soap_copy(), soap_copy_context(), soap_copy_stream(), lfg::LFGMgr::UpdateRaidBrowser(), updatewindow(), and write().
copy() [4/4]
template<typename OutputIterator > OutputIterator detail::copy (wchar_t ch, OutputIterator out)
Definition at line 69 of file ranges.h.
{
   *out++ = ch;
   return out;
 }
Referenced by formatter< tuple_join_view< Char, T... >, Char >::format_args().
copy_str()
template<typename Char , typename InputIt > counting_iterator detail::copy_str (InputIt begin, InputIt end, counting_iterator it) inline
Definition at line 56 of file compile.h.
{
   return it + (end - begin);
 }
copy_str_noinline()
template<typename OutChar , typename InputIt , typename OutputIt > FMT_CONSTEXPR FMT_NOINLINE auto detail::copy_str_noinline (InputIt begin, InputIt end, OutputIt out) -> OutputIt
Definition at line 429 of file format.h.
{
   return copy_str<OutChar>(begin, end, out);
 }
count_digits< 4 >()
template<> FMT_FUNC int detail::count_digits< 4 > (detail::fallback_uintptr n)
Definition at line 140 of file format-inl.h.
{
   // fallback_uintptr is always stored in little endian.
   int i = static_cast<int>(sizeof(void*)) - 1;
   while (i > 0 && n.value[i] == 0) --i;
   auto char_digits = std::numeric_limits<unsigned char>::digits / 4;
   return i >= 0 ? i * char_digits + count_digits<4, unsigned>(n.value[i]) : 1;
 }
References detail::fallback_uintptr::value.
decimal_point_impl()
template<typename Char > template FMT_API wchar_t detail::decimal_point_impl (locale_ref loc)
Definition at line 113 of file format-inl.h.
{
   return std::use_facet<std::numpunct<Char>>(loc.get<std::locale>())
       .decimal_point();
 }
References locale_ref::get().
do_write()
auto detail::do_write (const std::tm & time, const std::locale & loc, char format, char modifier) -> std::string inline
Definition at line 291 of file chrono.h.
{
   auto&& os = std::ostringstream();
   os.imbue(loc);
   using iterator = std::ostreambuf_iterator<char>;
   const auto& facet = std::use_facet<std::time_put<char, iterator>>(loc);
   auto end = facet.put(os, os, ' ', &time, format, modifier);
   if (end.failed()) FMT_THROW(format_error("failed to format time"));
   auto str = os.str();
   if (!detail::is_utf8() || loc == std::locale::classic()) return str;
     // char16_t and char32_t codecvts are broken in MSVC (linkage errors) and
     // gcc-4.
 #if FMT_MSC_VER != 0 || \
     (defined(__GLIBCXX__) && !defined(_GLIBCXX_USE_DUAL_ABI))
   // The _GLIBCXX_USE_DUAL_ABI macro is always defined in libstdc++ from gcc-5
   // and newer.
   using code_unit = wchar_t;
 #else
   using code_unit = char32_t;
 #endif
   auto& f = std::use_facet<std::codecvt<code_unit, char, std::mbstate_t>>(loc);
   auto mb = std::mbstate_t();
   const char* from_next = nullptr;
   code_unit* to_next = nullptr;
   constexpr size_t buf_size = 32;
   code_unit buf[buf_size] = {};
   auto result = f.in(mb, str.data(), str.data() + str.size(), from_next, buf,
                      buf + buf_size, to_next);
   if (result != std::codecvt_base::ok)
     FMT_THROW(format_error("failed to format time"));
   str.clear();
   for (code_unit* p = buf; p != to_next; ++p) {
     uint32_t c = static_cast<uint32_t>(*p);
     if (sizeof(code_unit) == 2 && c >= 0xd800 && c <= 0xdfff) {
       // surrogate pair
       ++p;
       if (p == to_next || (c & 0xfc00) != 0xd800 || (*p & 0xfc00) != 0xdc00) {
         FMT_THROW(format_error("failed to format time"));
       }
       c = (c << 10) + static_cast<uint32_t>(*p) - 0x35fdc00;
     }
     if (c < 0x80) {
       str.push_back(static_cast<char>(c));
     } else if (c < 0x800) {
       str.push_back(static_cast<char>(0xc0 | (c >> 6)));
       str.push_back(static_cast<char>(0x80 | (c & 0x3f)));
     } else if ((c >= 0x800 && c <= 0xd7ff) || (c >= 0xe000 && c <= 0xffff)) {
       str.push_back(static_cast<char>(0xe0 | (c >> 12)));
       str.push_back(static_cast<char>(0x80 | ((c & 0xfff) >> 6)));
       str.push_back(static_cast<char>(0x80 | (c & 0x3f)));
     } else if (c >= 0x10000 && c <= 0x10ffff) {
       str.push_back(static_cast<char>(0xf0 | (c >> 18)));
       str.push_back(static_cast<char>(0x80 | ((c & 0x3ffff) >> 12)));
       str.push_back(static_cast<char>(0x80 | ((c & 0xfff) >> 6)));
       str.push_back(static_cast<char>(0x80 | (c & 0x3f)));
     } else {
       FMT_THROW(format_error("failed to format time"));
     }
   }
   return str;
 }
References mpq::c, f(), FMT_THROW, format(), and is_utf8().
Referenced by write().
fallback_format()
template<typename Double > void detail::fallback_format (Double d, int num_digits, bool binary32, buffer< char > & buf, int & exp10)
Definition at line 2217 of file format-inl.h.
{
   bigint numerator;    // 2 * R in (FPP)^2.
   bigint denominator;  // 2 * S in (FPP)^2.
   // lower and upper are differences between value and corresponding boundaries.
   bigint lower;             // (M^- in (FPP)^2).
   bigint upper_store;       // upper's value if different from lower.
   bigint* upper = nullptr;  // (M^+ in (FPP)^2).
   fp value;
   // Shift numerator and denominator by an extra bit or two (if lower boundary
   // is closer) to make lower and upper integers. This eliminates multiplication
   // by 2 during later computations.
   const bool is_predecessor_closer =
       binary32 ? value.assign(static_cast<float>(d)) : value.assign(d);
   int shift = is_predecessor_closer ? 2 : 1;
   uint64_t significand = value.f << shift;
   if (value.e >= 0) {
     numerator.assign(significand);
     numerator <<= value.e;
     lower.assign(1);
     lower <<= value.e;
     if (shift != 1) {
       upper_store.assign(1);
       upper_store <<= value.e + 1;
       upper = &upper_store;
     }
     denominator.assign_pow10(exp10);
     denominator <<= shift;
   } else if (exp10 < 0) {
     numerator.assign_pow10(-exp10);
     lower.assign(numerator);
     if (shift != 1) {
       upper_store.assign(numerator);
       upper_store <<= 1;
       upper = &upper_store;
     }
     numerator *= significand;
     denominator.assign(1);
     denominator <<= shift - value.e;
   } else {
     numerator.assign(significand);
     denominator.assign_pow10(exp10);
     denominator <<= shift - value.e;
     lower.assign(1);
     if (shift != 1) {
       upper_store.assign(1ULL << 1);
       upper = &upper_store;
     }
   }
   // Invariant: value == (numerator / denominator) * pow(10, exp10).
   if (num_digits < 0) {
     // Generate the shortest representation.
     if (!upper) upper = &lower;
     bool even = (value.f & 1) == 0;
     num_digits = 0;
     char* data = buf.data();
     for (;;) {
       int digit = numerator.divmod_assign(denominator);
       bool low = compare(numerator, lower) - even < 0;  // numerator <[=] lower.
       // numerator + upper >[=] pow10:
       bool high = add_compare(numerator, *upper, denominator) + even > 0;
       data[num_digits++] = static_cast<char>('0' + digit);
       if (low || high) {
         if (!low) {
           ++data[num_digits - 1];
         } else if (high) {
           int result = add_compare(numerator, numerator, denominator);
           // Round half to even.
           if (result > 0 || (result == 0 && (digit % 2) != 0))
             ++data[num_digits - 1];
         }
         buf.try_resize(to_unsigned(num_digits));
         exp10 -= num_digits - 1;
         return;
       }
       numerator *= 10;
       lower *= 10;
       if (upper != &lower) *upper *= 10;
     }
   }
   // Generate the given number of digits.
   exp10 -= num_digits - 1;
   if (num_digits == 0) {
     buf.try_resize(1);
     denominator *= 10;
     buf[0] = add_compare(numerator, numerator, denominator) > 0 ? '1' : '0';
     return;
   }
   buf.try_resize(to_unsigned(num_digits));
   for (int i = 0; i < num_digits - 1; ++i) {
     int digit = numerator.divmod_assign(denominator);
     buf[i] = static_cast<char>('0' + digit);
     numerator *= 10;
   }
   int digit = numerator.divmod_assign(denominator);
   auto result = add_compare(numerator, numerator, denominator);
   if (result > 0 || (result == 0 && (digit % 2) != 0)) {
     if (digit == 9) {
       const auto overflow = '0' + 10;
       buf[num_digits - 1] = overflow;
       // Propagate the carry.
       for (int i = num_digits - 1; i > 0 && buf[i] == overflow; --i) {
         buf[i] = '0';
         ++buf[i - 1];
       }
       if (buf[0] == overflow) {
         buf[0] = '1';
         ++exp10;
       }
       return;
     }
     ++digit;
   }
   buf[num_digits - 1] = static_cast<char>('0' + digit);
 }
References detail::bigint::assign(), detail::bigint::assign_pow10(), mpq::d, buffer< T >::data(), detail::bigint::divmod_assign(), to_unsigned(), and buffer< T >::try_resize().
Referenced by format_float().
fill_n() [1/2]
template<typename OutputIt , typename Size , typename T > FMT_CONSTEXPR auto detail::fill_n (OutputIt out, Size count, const T & value) -> OutputIt
Definition at line 408 of file format.h.
                 {
   for (Size i = 0; i < count; ++i) *out++ = value;
   return out;
 }
References count(), and Acore::Size().
Referenced by fill(), chrono_formatter< FormatContext, OutputIt, Rep, Period >::write(), and write_float().
fill_n() [2/2]
template<typename T , typename Size > FMT_CONSTEXPR20 auto detail::fill_n (T * out, Size count, char value) -> T*
Definition at line 414 of file format.h.
{
   if (is_constant_evaluated()) {
     return fill_n<T*, Size, T>(out, count, value);
   }
   std::memset(out, value, to_unsigned(count));
   return out + count;
 }
References count(), is_constant_evaluated(), memset, and to_unsigned().
first()
template<typename T , typename... Tail> const T& detail::first (const T & value, const Tail & ...)
Definition at line 178 of file compile.h.
{
   return value;
 }
Referenced by _downheap(), _lf_pinbox_real_free(), alloc_free(), Coalesce(), utf8::distance(), utf8::unchecked::distance(), find(), find< false, char >(), formatter< detail::bigint >::format(), gz_zero(), handle_options(), gm_commandscript::HandleGMListIngameCommand(), SpellMgr::LoadSpellRanks(), G3D::Spinlock::lock(), my_error_register(), my_error_unregister(), my_hash_key(), ObjectPosSelector::NextPosibleAngle(), ObjectPosSelector::NextSmallStepAngle(), ptr_compare(), ptr_compare_0(), ptr_compare_1(), ptr_compare_2(), ptr_compare_3(), RAND(), soap_alloc_multipart(), PassengerController::SummonCreatures(), npc_medivh_bm::npc_medivh_bmAI::SummonOrcs(), Acore::String::Trim(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_kalecgos_kj::npc_kalecgos_kjAI::UpdateAI(), and G3D::wordWrap().
FMT_NOMACRO()
null localtime_r detail::FMT_NOMACRO (...) inline
Definition at line 286 of file chrono.h.
 { return null<>(); }
for_each() [1/2]
template<class Tuple , class F , size_t... Is> void detail::for_each (index_sequence< Is... > , Tuple && tup, F && f)
Definition at line 226 of file ranges.h.
{
   using std::get;
   // using free function get<I>(T) now.
   const int _[] = {0, ((void)f(get<Is>(tup)), 0)...};
   (void)_;  // blocks warnings
 }
References f().
Referenced by TaskScheduler::CancelGroupsOf(), for_each(), and formatter< TupleT, Char, enable_if_t< fmt::is_tuple_like< TupleT >::value > >::format().
for_each() [2/2]
template<class Tuple , class F > void detail::for_each (Tuple && tup, F && f)
Definition at line 239 of file ranges.h.
{
   const auto indexes = get_indexes(tup);
   for_each(indexes, std::forward<Tuple>(tup), std::forward<F>(f));
 }
References f(), for_each(), and get_indexes().
for_each_codepoint()
template<typename F > FMT_CONSTEXPR void detail::for_each_codepoint (string_view s, F f)
Definition at line 484 of file format.h.
{
   auto decode = [f](const char* p) {
     auto cp = uint32_t();
     auto error = 0;
     p = utf8_decode(p, &cp, &error);
     f(cp, error);
     return p;
   };
   auto p = s.data();
   const size_t block_size = 4;  // utf8_decode always reads blocks of 4 chars.
   if (s.size() >= block_size) {
     for (auto end = p + s.size() - block_size + 1; p < end;) p = decode(p);
   }
   if (auto num_chars_left = s.data() + s.size() - p) {
     char buf[2 * block_size - 1] = {};
     copy_str<char>(p, p + num_chars_left, buf);
     p = buf;
     do {
       p = decode(p);
     } while (p - buf < num_chars_left);
   }
 }
References basic_string_view< Char >::data(), error(), f(), basic_string_view< Char >::size(), and utf8_decode().
Referenced by utf8_to_utf16::utf8_to_utf16().
format_error_code()
FMT_FUNC void detail::format_error_code (detail::buffer< char > & out, int error_code, string_view message)
Definition at line 56 of file format-inl.h.
{
   // Report error code making sure that the output fits into
   // inline_buffer_size to avoid dynamic memory allocation and potential
   // bad_alloc.
   out.try_resize(0);
   static const char SEP[] = ": ";
   static const char ERROR_STR[] = "error ";
   // Subtract 2 to account for terminating null characters in SEP and ERROR_STR.
   size_t error_code_size = sizeof(SEP) + sizeof(ERROR_STR) - 2;
   auto abs_value = static_cast<uint32_or_64_or_128_t<int>>(error_code);
   if (detail::is_negative(error_code)) {
     abs_value = 0 - abs_value;
     ++error_code_size;
   }
   error_code_size += detail::to_unsigned(detail::count_digits(abs_value));
   auto it = buffer_appender<char>(out);
   if (message.size() <= inline_buffer_size - error_code_size)
     format_to(it, FMT_STRING("{}{}"), message, SEP);
   format_to(it, FMT_STRING("{}{}"), ERROR_STR, error_code);
   FMT_ASSERT(out.size() <= inline_buffer_size, "");
 }
References count_digits(), FMT_ASSERT, FMT_STRING, format_to(), inline_buffer_size, is_negative(), message(), and to_unsigned().
format_float() [1/2]
template<typename T > int detail::format_float (char * buf, std::size_t size, const char * format, int precision, T value)
Definition at line 14 of file format.cc.
{
 #ifdef FMT_FUZZ
   if (precision > 100000)
     throw std::runtime_error(
         "fuzz mode - avoid large allocation inside snprintf");
 #endif
   // Suppress the warning about nonliteral format string.
   int (*snprintf_ptr)(char*, size_t, const char*, ...) = FMT_SNPRINTF;
   return precision < 0 ? snprintf_ptr(buf, size, format, value)
                        : snprintf_ptr(buf, size, format, precision, value);
 }
References FMT_SNPRINTF, and format().
format_float() [2/2]
template<typename T > int detail::format_float (T value, int precision, float_specs specs, buffer< char > & buf)
Definition at line 2334 of file format-inl.h.
{
   static_assert(!std::is_same<T, float>::value, "");
   FMT_ASSERT(value >= 0, "value is negative");
   const bool fixed = specs.format == float_format::fixed;
   if (value <= 0) {  // <= instead of == to silence a warning.
     if (precision <= 0 || !fixed) {
       buf.push_back('0');
       return 0;
     }
     buf.try_resize(to_unsigned(precision));
     std::uninitialized_fill_n(buf.data(), precision, '0');
     return -precision;
   }
   if (!specs.use_grisu) return snprintf_float(value, precision, specs, buf);
   if (precision < 0) {
     // Use Dragonbox for the shortest format.
     if (specs.binary32) {
       auto dec = dragonbox::to_decimal(static_cast<float>(value));
       write<char>(buffer_appender<char>(buf), dec.significand);
       return dec.exponent;
     }
     auto dec = dragonbox::to_decimal(static_cast<double>(value));
     write<char>(buffer_appender<char>(buf), dec.significand);
     return dec.exponent;
   }
   // Use Grisu + Dragon4 for the given precision:
   // https://www.cs.tufts.edu/~nr/cs257/archive/florian-loitsch/printf.pdf.
   int exp = 0;
   const int min_exp = -60;  // alpha in Grisu.
   int cached_exp10 = 0;     // K in Grisu.
   fp normalized = normalize(fp(value));
   const auto cached_pow = get_cached_power(
       min_exp - (normalized.e + fp::significand_size), cached_exp10);
   normalized = normalized * cached_pow;
   // Limit precision to the maximum possible number of significant digits in an
   // IEEE754 double because we don't need to generate zeros.
   const int max_double_digits = 767;
   if (precision > max_double_digits) precision = max_double_digits;
   fixed_handler handler{buf.data(), 0, precision, -cached_exp10, fixed};
   if (grisu_gen_digits(normalized, 1, exp, handler) == digits::error) {
     exp += handler.size - cached_exp10 - 1;
     fallback_format(value, handler.precision, specs.binary32, buf, exp);
   } else {
     exp += handler.exp10;
     buf.try_resize(to_unsigned(handler.size));
   }
   if (!fixed && !specs.showpoint) {
     // Remove trailing zeros.
     auto num_digits = buf.size();
     while (num_digits > 0 && buf[num_digits - 1] == '0') {
       --num_digits;
       ++exp;
     }
     buf.try_resize(num_digits);
   }
   return exp;
 }  // namespace detail
References float_specs::binary32, buffer< T >::data(), detail::fp::e, detail::digits::error, fallback_format(), fixed, FMT_ASSERT, float_specs::format, get_cached_power(), grisu_gen_digits(), normalize(), buffer< T >::push_back(), float_specs::showpoint, detail::fp::significand_size, buffer< T >::size(), snprintf_float(), detail::dragonbox::to_decimal(), to_unsigned(), buffer< T >::try_resize(), and float_specs::use_grisu.
format_value()
template<typename Char , typename T > void detail::format_value (buffer< Char > & buf, const T & value, locale_ref loc = locale_ref())
Definition at line 109 of file ostream.h.
{
   formatbuf<Char> format_buf(buf);
   std::basic_ostream<Char> output(&format_buf);
 #if !defined(FMT_STATIC_THOUSANDS_SEPARATOR)
   if (loc) output.imbue(loc.get<std::locale>());
 #endif
   output << value;
   output.exceptions(std::ios_base::failbit | std::ios_base::badbit);
   buf.try_resize(buf.size());
 }
References buffer< T >::size(), and buffer< T >::try_resize().
Referenced by detail::fallback_formatter< T, Char, enable_if_t< is_streamable< T, Char >::value > >::format().
fwrite_fully()
void detail::fwrite_fully (const void * ptr, size_t size, size_t count, FILE * stream) inline
Definition at line 89 of file format-inl.h.
{
   size_t written = std::fwrite(ptr, size, count, stream);
   if (written < count) FMT_THROW(system_error(errno, "cannot write to file"));
 }
References count(), errno, FMT_THROW, ptr(), and system_error().
Referenced by print().
get_cached_power()
fp detail::get_cached_power (int min_exponent, int & pow10_exponent) inline
Definition at line 279 of file format-inl.h.
{
   // Normalized 64-bit significands of pow(10, k), for k = -348, -340, ..., 340.
   // These are generated by support/compute-powers.py.
   static constexpr const uint64_t pow10_significands[] = {
       0xfa8fd5a0081c0288, 0xbaaee17fa23ebf76, 0x8b16fb203055ac76,
       0xcf42894a5dce35ea, 0x9a6bb0aa55653b2d, 0xe61acf033d1a45df,
       0xab70fe17c79ac6ca, 0xff77b1fcbebcdc4f, 0xbe5691ef416bd60c,
       0x8dd01fad907ffc3c, 0xd3515c2831559a83, 0x9d71ac8fada6c9b5,
       0xea9c227723ee8bcb, 0xaecc49914078536d, 0x823c12795db6ce57,
       0xc21094364dfb5637, 0x9096ea6f3848984f, 0xd77485cb25823ac7,
       0xa086cfcd97bf97f4, 0xef340a98172aace5, 0xb23867fb2a35b28e,
       0x84c8d4dfd2c63f3b, 0xc5dd44271ad3cdba, 0x936b9fcebb25c996,
       0xdbac6c247d62a584, 0xa3ab66580d5fdaf6, 0xf3e2f893dec3f126,
       0xb5b5ada8aaff80b8, 0x87625f056c7c4a8b, 0xc9bcff6034c13053,
       0x964e858c91ba2655, 0xdff9772470297ebd, 0xa6dfbd9fb8e5b88f,
       0xf8a95fcf88747d94, 0xb94470938fa89bcf, 0x8a08f0f8bf0f156b,
       0xcdb02555653131b6, 0x993fe2c6d07b7fac, 0xe45c10c42a2b3b06,
       0xaa242499697392d3, 0xfd87b5f28300ca0e, 0xbce5086492111aeb,
       0x8cbccc096f5088cc, 0xd1b71758e219652c, 0x9c40000000000000,
       0xe8d4a51000000000, 0xad78ebc5ac620000, 0x813f3978f8940984,
       0xc097ce7bc90715b3, 0x8f7e32ce7bea5c70, 0xd5d238a4abe98068,
       0x9f4f2726179a2245, 0xed63a231d4c4fb27, 0xb0de65388cc8ada8,
       0x83c7088e1aab65db, 0xc45d1df942711d9a, 0x924d692ca61be758,
       0xda01ee641a708dea, 0xa26da3999aef774a, 0xf209787bb47d6b85,
       0xb454e4a179dd1877, 0x865b86925b9bc5c2, 0xc83553c5c8965d3d,
       0x952ab45cfa97a0b3, 0xde469fbd99a05fe3, 0xa59bc234db398c25,
       0xf6c69a72a3989f5c, 0xb7dcbf5354e9bece, 0x88fcf317f22241e2,
       0xcc20ce9bd35c78a5, 0x98165af37b2153df, 0xe2a0b5dc971f303a,
       0xa8d9d1535ce3b396, 0xfb9b7cd9a4a7443c, 0xbb764c4ca7a44410,
       0x8bab8eefb6409c1a, 0xd01fef10a657842c, 0x9b10a4e5e9913129,
       0xe7109bfba19c0c9d, 0xac2820d9623bf429, 0x80444b5e7aa7cf85,
       0xbf21e44003acdd2d, 0x8e679c2f5e44ff8f, 0xd433179d9c8cb841,
       0x9e19db92b4e31ba9, 0xeb96bf6ebadf77d9, 0xaf87023b9bf0ee6b,
   };
   // Binary exponents of pow(10, k), for k = -348, -340, ..., 340, corresponding
   // to significands above.
   static constexpr const int16_t pow10_exponents[] = {
       -1220, -1193, -1166, -1140, -1113, -1087, -1060, -1034, -1007, -980, -954,
       -927,  -901,  -874,  -847,  -821,  -794,  -768,  -741,  -715,  -688, -661,
       -635,  -608,  -582,  -555,  -529,  -502,  -475,  -449,  -422,  -396, -369,
       -343,  -316,  -289,  -263,  -236,  -210,  -183,  -157,  -130,  -103, -77,
       -50,   -24,   3,     30,    56,    83,    109,   136,   162,   189,  216,
       242,   269,   295,   322,   348,   375,   402,   428,   455,   481,  508,
       534,   561,   588,   614,   641,   667,   694,   720,   747,   774,  800,
       827,   853,   880,   907,   933,   960,   986,   1013,  1039,  1066};
   const int shift = 32;
   const auto significand = static_cast<int64_t>(data::log10_2_significand);
   int index = static_cast<int>(
       ((min_exponent + fp::significand_size - 1) * (significand >> shift) +
        ((int64_t(1) << shift) - 1))  // ceil
       >> 32                          // arithmetic shift
   );
   // Decimal exponent of the first (smallest) cached power of 10.
   const int first_dec_exp = -348;
   // Difference between 2 consecutive decimal exponents in cached powers of 10.
   const int dec_exp_step = 8;
   index = (index - first_dec_exp - 1) / dec_exp_step + 1;
   pow10_exponent = first_dec_exp + index * dec_exp_step;
   return {pow10_significands[index], pow10_exponents[index]};
 }
References index, basic_data< T >::log10_2_significand, and detail::fp::significand_size.
Referenced by format_float(), detail::dragonbox::shorter_interval_case(), and detail::dragonbox::to_decimal().
get_data() [1/2]
template<typename Container > auto detail::get_data (Container & c) -> typename Container::value_type* inline
Definition at line 335 of file format.h.
{
   return c.data();
 }
References mpq::c.
get_data() [2/2]
template<typename Char > auto detail::get_data (std::basic_string< Char > & s) -> Char* inline
Definition at line 331 of file format.h.
{
   return &s[0];
 }
Referenced by reserve().
get_indexes()
template<class T > FMT_CONSTEXPR make_index_sequence<std::tuple_size<T>::value> detail::get_indexes (T const &)
Definition at line 234 of file ranges.h.
               {
   return {};
 }
Referenced by for_each().
get_round_direction()
round_direction detail::get_round_direction (uint64_t divisor, uint64_t remainder, uint64_t error) inline
Definition at line 605 of file format-inl.h.
{
   FMT_ASSERT(remainder < divisor, "");  // divisor - remainder won't overflow.
   FMT_ASSERT(error < divisor, "");      // divisor - error won't overflow.
   FMT_ASSERT(error < divisor - error, "");  // error * 2 won't overflow.
   // Round down if (remainder + error) * 2 <= divisor.
   if (remainder <= divisor - remainder && error * 2 <= divisor - remainder * 2)
     return round_direction::down;
   // Round up if (remainder - error) * 2 >= divisor.
   if (remainder >= error &&
       remainder - error >= divisor - (remainder - error)) {
     return round_direction::up;
   }
   return round_direction::unknown;
 }
References down, error(), FMT_ASSERT, unknown, and up.
Referenced by detail::fixed_handler::on_digit(), and detail::fixed_handler::on_start().
gmtime_r()
null detail::gmtime_r (...) inline
Definition at line 288 of file chrono.h.
 { return null<>(); }
Referenced by get_date(), gmtime(), soap_dateTime2s(), and soap_timegm().
gmtime_s()
null detail::gmtime_s (...) inline
Definition at line 289 of file chrono.h.
 { return null<>(); }
Referenced by gmtime().
grisu_gen_digits()
template<typename Handler > FMT_INLINE digits::result detail::grisu_gen_digits (fp value, uint64_t error, int & exp, Handler & handler)
Definition at line 640 of file format-inl.h.
{
   const fp one(1ULL << -value.e, value.e);
   // The integral part of scaled value (p1 in Grisu) = value / one. It cannot be
   // zero because it contains a product of two 64-bit numbers with MSB set (due
   // to normalization) - 1, shifted right by at most 60 bits.
   auto integral = static_cast<uint32_t>(value.f >> -one.e);
   FMT_ASSERT(integral != 0, "");
   FMT_ASSERT(integral == value.f >> -one.e, "");
   // The fractional part of scaled value (p2 in Grisu) c = value % one.
   uint64_t fractional = value.f & (one.f - 1);
   exp = count_digits(integral);  // kappa in Grisu.
   // Divide by 10 to prevent overflow.
   auto result = handler.on_start(power_of_10_64(exp - 1) << -one.e,
                                  value.f / 10, error * 10, exp);
   if (result != digits::more) return result;
   // Generate digits for the integral part. This can produce up to 10 digits.
   do {
     uint32_t digit = 0;
     auto divmod_integral = [&](uint32_t divisor) {
       digit = integral / divisor;
       integral %= divisor;
     };
     // This optimization by Milo Yip reduces the number of integer divisions by
     // one per iteration.
     switch (exp) {
     case 10:
       divmod_integral(1000000000);
       break;
     case 9:
       divmod_integral(100000000);
       break;
     case 8:
       divmod_integral(10000000);
       break;
     case 7:
       divmod_integral(1000000);
       break;
     case 6:
       divmod_integral(100000);
       break;
     case 5:
       divmod_integral(10000);
       break;
     case 4:
       divmod_integral(1000);
       break;
     case 3:
       divmod_integral(100);
       break;
     case 2:
       divmod_integral(10);
       break;
     case 1:
       digit = integral;
       integral = 0;
       break;
     default:
       FMT_ASSERT(false, "invalid number of digits");
     }
     --exp;
     auto remainder = (static_cast<uint64_t>(integral) << -one.e) + fractional;
     result = handler.on_digit(static_cast<char>('0' + digit),
                               power_of_10_64(exp) << -one.e, remainder, error,
                               exp, true);
     if (result != digits::more) return result;
   } while (exp > 0);
   // Generate digits for the fractional part.
   for (;;) {
     fractional *= 10;
     error *= 10;
     char digit = static_cast<char>('0' + (fractional >> -one.e));
     fractional &= one.f - 1;
     --exp;
     result = handler.on_digit(digit, one.f, fractional, error, exp, false);
     if (result != digits::more) return result;
   }
 }
References count_digits(), error(), FMT_ASSERT, detail::digits::more, G3D::one(), and power_of_10_64().
Referenced by format_float().
is_big_endian()
auto detail::is_big_endian () -> bool inline
Definition at line 268 of file format.h.
{
   const auto u = 1u;
   struct bytes {
     char data[sizeof(u)];
   };
   return bit_cast<bytes>(u).data[0] == 0;
 }
Referenced by detail::fallback_uintptr::fallback_uintptr().
localtime_s()
null detail::localtime_s (...) inline
Definition at line 287 of file chrono.h.
 { return null<>(); }
Referenced by localtime().
make_checked()
template<typename T > auto detail::make_checked (T * p, size_t) -> T* inline
Definition at line 347 of file format.h.
 { return p; }
Referenced by buffer< T >::append(), detail::bigint::assign(), basic_memory_buffer< T, SIZE, Allocator >::grow(), basic_memory_buffer< T, SIZE, Allocator >::move(), reserve(), write_int_localized(), and write_significand().
max_value()
template<typename T > constexpr auto detail::max_value () -> T constexpr
Definition at line 303 of file format.h.
{
   return (std::numeric_limits<T>::max)();
 }
References max.
Referenced by AchievementMgr::SetCriteriaProgress().
multiply()
uint64_t detail::multiply (uint64_t lhs, uint64_t rhs) inline
Definition at line 258 of file format-inl.h.
{
 #if FMT_USE_INT128
   auto product = static_cast<__uint128_t>(lhs) * rhs;
   auto f = static_cast<uint64_t>(product >> 64);
   return (static_cast<uint64_t>(product) & (1ULL << 63)) != 0 ? f + 1 : f;
 #else
   // Multiply 32-bit parts of significands.
   uint64_t mask = (1ULL << 32) - 1;
   uint64_t a = lhs >> 32, b = lhs & mask;
   uint64_t c = rhs >> 32, d = rhs & mask;
   uint64_t ac = a * c, bc = b * c, ad = a * d, bd = b * d;
   // Compute mid 64-bit of result and round.
   uint64_t mid = (bd >> 32) + (ad & mask) + (bc & mask) + (1U << 31);
   return ac + (ad >> 32) + (bc >> 32) + (mid >> 32);
 #endif
 }
References mpq::a, b, mpq::c, mpq::d, f(), and product.
Referenced by operator*().
normalize()
template<int SHIFT = 0> fp detail::normalize (fp value)
Definition at line 240 of file format-inl.h.
{
   // Handle subnormals.
   const auto shifted_implicit_bit = fp::implicit_bit << SHIFT;
   while ((value.f & shifted_implicit_bit) == 0) {
     value.f <<= 1;
     --value.e;
   }
   // Subtract 1 to account for hidden bit.
   const auto offset =
       fp::significand_size - fp::double_significand_size - SHIFT - 1;
   value.f <<= offset;
   value.e -= offset;
   return value;
 }
References detail::fp::double_significand_size, detail::fp::implicit_bit, and detail::fp::significand_size.
Referenced by format_float().
num_bits()
template<typename T > constexpr auto detail::num_bits () -> int constexpr
Definition at line 306 of file format.h.
{
   return std::numeric_limits<T>::digits;
 }
num_bits< fallback_uintptr >()
template<> constexpr auto detail::num_bits< fallback_uintptr > () -> int constexpr
Definition at line 312 of file format.h.
{
   return static_cast<int>(sizeof(void*) *
                           std::numeric_limits<unsigned char>::digits);
 }
num_bits< int128_t >()
template<> constexpr auto detail::num_bits< int128_t > () -> int constexpr
Definition at line 310 of file format.h.
 { return 128; }
num_bits< uint128_t >()
template<> constexpr auto detail::num_bits< uint128_t > () -> int constexpr
Definition at line 311 of file format.h.
 { return 128; }
operator*()
fp detail::operator* (fp x, fp y) inline
Definition at line 275 of file format-inl.h.
 { return {multiply(x.f, y.f), x.e + y.e + 64}; }
References multiply(), G3D::x, and G3D::y.
operator<<() [1/4]
template<typename Traits > void_t detail::operator<< (std::basic_ostream< char, Traits > & , char)
operator<<() [2/4]
template<typename Char , typename Traits > void_t detail::operator<< (std::basic_ostream< Char, Traits > & , Char)
Referenced by ByteBuffer::operator<<().
operator<<() [3/4]
template<typename Traits > void_t detail::operator<< (std::basic_ostream< char, Traits > & , signed char)
operator<<() [4/4]
template<typename Traits > void_t detail::operator<< (std::basic_ostream< char, Traits > & , unsigned char)
operator==()
bool detail::operator== (fp x, fp y) inline
Definition at line 255 of file format-inl.h.
 { return x.f == y.f && x.e == y.e; }
References G3D::x, and G3D::y.
power_of_10_64()
uint64_t detail::power_of_10_64 (int exp) inline
Definition at line 629 of file format-inl.h.
{
   static constexpr const uint64_t data[] = {1, FMT_POWERS_OF_10(1),
                                             FMT_POWERS_OF_10(1000000000ULL),
                                             10000000000000000000ULL};
   return data[exp];
 }
References FMT_POWERS_OF_10.
Referenced by grisu_gen_digits().
print()
FMT_API void detail::print (std::FILE * f, string_view text)
Definition at line 2578 of file format-inl.h.
{
 #ifdef _WIN32
   auto fd = _fileno(f);
   if (_isatty(fd)) {
     detail::utf8_to_utf16 u16(string_view(text.data(), text.size()));
     auto written = detail::dword();
     if (detail::WriteConsoleW(reinterpret_cast<void*>(_get_osfhandle(fd)),
                               u16.c_str(), static_cast<uint32_t>(u16.size()),
                               &written, nullptr)) {
       return;
     }
     // Fallback to fwrite on failure. It can happen if the output has been
     // redirected to NUL.
   }
 #endif
   detail::fwrite_fully(text.data(), 1, text.size(), f);
 }
References basic_string_view< Char >::data(), f(), fwrite_fully(), and basic_string_view< Char >::size().
Referenced by vprint().
range_begin() [1/3]
template<typename T , std::size_t N> auto detail::range_begin (const T(&) arr[N]) -> const T*
Definition at line 103 of file ranges.h.
{
   return arr;
 }
range_begin() [2/3]
template<typename T > auto detail::range_begin (T && rng) -> enable_if_t<!has_member_fn_begin_end_t<T&&>::value, decltype(begin(static_cast<T&&>(rng)))>
Definition at line 128 of file ranges.h.
{
   return begin(static_cast<T&&>(rng));
 }
range_begin() [3/3]
template<typename T > auto detail::range_begin (T && rng) &&
range_end() [1/3]
template<typename T , std::size_t N> auto detail::range_end (const T(&) arr[N]) -> const T*
Definition at line 107 of file ranges.h.
{
   return arr + N;
 }
range_end() [2/3]
template<typename T > auto detail::range_end (T && rng) -> enable_if_t<!has_member_fn_begin_end_t<T&&>::value, decltype(end(static_cast<T&&>(rng)))>
Definition at line 134 of file ranges.h.
{
   return end(static_cast<T&&>(rng));
 }
range_end() [3/3]
template<typename T > auto detail::range_end (T && rng) &&
report_error()
FMT_FUNC void detail::report_error (format_func func, int error_code, const char * message)
Definition at line 79 of file format-inl.h.
{
   memory_buffer full_message;
   func(full_message, error_code, message);
   // Don't use fwrite_fully because the latter may throw.
   if (std::fwrite(full_message.data(), full_message.size(), 1, stderr) > 0)
     std::fputc('\n', stderr);
 }
References message().
reserve() [1/3]
template<typename T > auto detail::reserve (buffer_appender< T > it, size_t n) -> buffer_appender<T> inline
Definition at line 366 of file format.h.
{
   buffer<T>& buf = get_container(it);
   buf.try_reserve(buf.size() + n);
   return it;
 }
References get_container().
reserve() [2/3]
template<typename Iterator > constexpr auto detail::reserve (Iterator & it, size_t) -> Iterator& constexpr
Definition at line 373 of file format.h.
{
   return it;
 }
Referenced by write(), write_float(), write_int(), write_padded(), and write_ptr().
reserve() [3/3]
template<typename Container , FMT_ENABLE_IF(is_contiguous< Container >::value) > auto detail::reserve (std::back_insert_iterator< Container > it, size_t n) -> checked_ptr<typename Container::value_type> inline
Definition at line 357 of file format.h.
{
   Container& c = get_container(it);
   size_t size = c.size();
   c.resize(size + n);
   return make_checked(get_data(c) + size, n);
 }
References mpq::c, Container, get_container(), get_data(), and make_checked().
Referenced by rcVectorBase< T, H >::assign(), ByteBuffer::ByteBuffer(), and rcBuildRegions().
snprintf_float()
template<typename T > int detail::snprintf_float (T value, int precision, float_specs specs, buffer< char > & buf)
Definition at line 2397 of file format-inl.h.
{
   // Buffer capacity must be non-zero, otherwise MSVC's vsnprintf_s will fail.
   FMT_ASSERT(buf.capacity() > buf.size(), "empty buffer");
   static_assert(!std::is_same<T, float>::value, "");
   // Subtract 1 to account for the difference in precision since we use %e for
   // both general and exponent format.
   if (specs.format == float_format::general ||
       specs.format == float_format::exp)
     precision = (precision >= 0 ? precision : 6) - 1;
   // Build the format string.
   enum { max_format_size = 7 };  // The longest format is "%#.*Le".
   char format[max_format_size];
   char* format_ptr = format;
   *format_ptr++ = '%';
   if (specs.showpoint && specs.format == float_format::hex) *format_ptr++ = '#';
   if (precision >= 0) {
     *format_ptr++ = '.';
     *format_ptr++ = '*';
   }
   if (std::is_same<T, long double>()) *format_ptr++ = 'L';
   *format_ptr++ = specs.format != float_format::hex
                       ? (specs.format == float_format::fixed ? 'f' : 'e')
                       : (specs.upper ? 'A' : 'a');
   *format_ptr = '\0';
   // Format using snprintf.
   auto offset = buf.size();
   for (;;) {
     auto begin = buf.data() + offset;
     auto capacity = buf.capacity() - offset;
 #ifdef FMT_FUZZ
     if (precision > 100000)
       throw std::runtime_error(
           "fuzz mode - avoid large allocation inside snprintf");
 #endif
     // Suppress the warning about a nonliteral format string.
     // Cannot use auto because of a bug in MinGW (#1532).
     int (*snprintf_ptr)(char*, size_t, const char*, ...) = FMT_SNPRINTF;
     int result = precision >= 0
                      ? snprintf_ptr(begin, capacity, format, precision, value)
                      : snprintf_ptr(begin, capacity, format, value);
     if (result < 0) {
       // The buffer will grow exponentially.
       buf.try_reserve(buf.capacity() + 1);
       continue;
     }
     auto size = to_unsigned(result);
     // Size equal to capacity means that the last character was truncated.
     if (size >= capacity) {
       buf.try_reserve(size + offset + 1);  // Add 1 for the terminating '\0'.
       continue;
     }
     auto is_digit = [](char c) { return c >= '0' && c <= '9'; };
     if (specs.format == float_format::fixed) {
       if (precision == 0) {
         buf.try_resize(size);
         return 0;
       }
       // Find and remove the decimal point.
       auto end = begin + size, p = end;
       do {
         --p;
       } while (is_digit(*p));
       int fraction_size = static_cast<int>(end - p - 1);
       std::memmove(p, p + 1, to_unsigned(fraction_size));
       buf.try_resize(size - 1);
       return -fraction_size;
     }
     if (specs.format == float_format::hex) {
       buf.try_resize(size + offset);
       return 0;
     }
     // Find and parse the exponent.
     auto end = begin + size, exp_pos = end;
     do {
       --exp_pos;
     } while (*exp_pos != 'e');
     char sign = exp_pos[1];
     FMT_ASSERT(sign == '+' || sign == '-', "");
     int exp = 0;
     auto p = exp_pos + 2;  // Skip 'e' and sign.
     do {
       FMT_ASSERT(is_digit(*p), "");
       exp = exp * 10 + (*p++ - '0');
     } while (p != end);
     if (sign == '-') exp = -exp;
     int fraction_size = 0;
     if (exp_pos != begin + 1) {
       // Remove trailing zeros.
       auto fraction_end = exp_pos - 1;
       while (*fraction_end == '0') --fraction_end;
       // Move the fractional part left to get rid of the decimal point.
       fraction_size = static_cast<int>(fraction_end - begin - 1);
       std::memmove(begin + 1, begin + 2, to_unsigned(fraction_size));
     }
     buf.try_resize(to_unsigned(fraction_size) + offset + 1);
     return exp - fraction_size;
   }
 }
References mpq::c, buffer< T >::capacity(), buffer< T >::data(), exp, fixed, FMT_ASSERT, FMT_SNPRINTF, format(), float_specs::format, general, hex, memmove, float_specs::showpoint, buffer< T >::size(), to_unsigned(), buffer< T >::try_reserve(), buffer< T >::try_resize(), and float_specs::upper.
Referenced by format_float().
thousands_sep_impl()
template<typename Char > template FMT_API auto detail::thousands_sep_impl (locale_ref loc) -> thousands_sep_result< Char >
Definition at line 107 of file format-inl.h.
{
   auto& facet = std::use_facet<std::numpunct<Char>>(loc.get<std::locale>());
   auto grouping = facet.grouping();
   auto thousands_sep = grouping.empty() ? Char() : facet.thousands_sep();
   return {std::move(grouping), thousands_sep};
 }
References thousands_sep().
to_pointer() [1/2]
template<typename T > auto detail::to_pointer (buffer_appender< T > it, size_t n) -> T*
Definition at line 385 of file format.h.
{
   buffer<T>& buf = get_container(it);
   auto size = buf.size();
   if (buf.capacity() < size + n) return nullptr;
   buf.try_resize(size + n);
   return buf.data() + size;
 }
References get_container().
to_pointer() [2/2]
template<typename T , typename OutputIt > constexpr auto detail::to_pointer (OutputIt , size_t) -> T* constexpr
Definition at line 382 of file format.h.
{
   return nullptr;
 }
to_uintptr()
auto detail::to_uintptr (const void * p) -> fallback_uintptr inline
Definition at line 296 of file format.h.
{
   return fallback_uintptr(p);
 }
Referenced by write().
unwrap() [1/2]
template<typename T > const T& detail::unwrap (const std::reference_wrapper< T > & v)
Definition at line 26 of file args.h.
{
   return static_cast<const T&>(v);
 }
unwrap() [2/2]
template<typename T > const T& detail::unwrap (const T & v)
Definition at line 25 of file args.h.
 { return v; }
Referenced by dynamic_format_arg_store< Context >::emplace_arg(), and dynamic_format_arg_store< Context >::push_back().
utf8_decode()
FMT_CONSTEXPR auto detail::utf8_decode (const char * s, uint32_t * c, int * e) -> const char* inline
Definition at line 451 of file format.h.
                    {
   constexpr const int masks[] = {0x00, 0x7f, 0x1f, 0x0f, 0x07};
   constexpr const uint32_t mins[] = {4194304, 0, 128, 2048, 65536};
   constexpr const int shiftc[] = {0, 18, 12, 6, 0};
   constexpr const int shifte[] = {0, 6, 4, 2, 0};
   int len = code_point_length(s);
   const char* next = s + len;
   // Assume a four-byte character and load four bytes. Unused bits are
   // shifted out.
   *c = uint32_t(s[0] & masks[len]) << 18;
   *c |= uint32_t(s[1] & 0x3f) << 12;
   *c |= uint32_t(s[2] & 0x3f) << 6;
   *c |= uint32_t(s[3] & 0x3f) << 0;
   *c >>= shiftc[len];
   // Accumulate the various error conditions.
   using uchar = unsigned char;
   *e = (*c < mins[len]) << 6;       // non-canonical encoding
   *e |= ((*c >> 11) == 0x1b) << 7;  // surrogate half?
   *e |= (*c > 0x10FFFF) << 8;       // out of range?
   *e |= (uchar(s[1]) & 0xc0) >> 2;
   *e |= (uchar(s[2]) & 0xc0) >> 4;
   *e |= uchar(s[3]) >> 6;
   *e ^= 0x2a;  // top two bits of each tail byte correct?
   *e >>= shifte[len];
   return next;
 }
References mpq::c, code_point_length(), and next().
Referenced by for_each_codepoint().
write()
template<typename OutputIt > auto detail::write (OutputIt out, const std::tm & time, const std::locale & loc, char format, char modifier = 0) -> OutputIt
Definition at line 354 of file chrono.h.
{
   auto str = do_write(time, loc, format, modifier);
   return std::copy(str.begin(), str.end(), out);
 }
References copy(), do_write(), and format().
Referenced by formatter< std::chrono::duration< Rep, Period >, Char >::format(), formatter< weekday >::format(), chrono_formatter< FormatContext, OutputIt, Rep, Period >::format_localized(), chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_12_hour(), chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_24_hour(), chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_24_hour_time(), chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_iso_time(), chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_minute(), chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_second(), arg_formatter< Char >::operator()(), vformat_to(), and vprintf().
write_buffer()
template<typename Char > void detail::write_buffer (std::basic_ostream< Char > & os, buffer< Char > & buf)
Definition at line 95 of file ostream.h.
{
   const Char* buf_data = buf.data();
   using unsigned_streamsize = std::make_unsigned<std::streamsize>::type;
   unsigned_streamsize size = buf.size();
   unsigned_streamsize max_size = to_unsigned(max_value<std::streamsize>());
   do {
     unsigned_streamsize n = size <= max_size ? size : max_size;
     os.write(buf_data, static_cast<std::streamsize>(n));
     buf_data += n;
     size -= n;
   } while (size != 0);
 }
References buffer< T >::data(), buffer< T >::size(), and to_unsigned().
Referenced by copy_to_read_buffer(), and vprint().
write_delimiter()
template<typename OutputIt > OutputIt detail::write_delimiter (OutputIt out)
Definition at line 248 of file ranges.h.
{
   *out++ = ',';
   *out++ = ' ';
   return out;
 }
Referenced by formatter< T, Char, enable_if_t< fmt::is_range< T, Char >::value &&(has_formatter< detail::value_type< T >, format_context >::value||detail::has_fallback_formatter< detail::value_type< T >, Char >::value) > >::format(), and formatter< TupleT, Char, enable_if_t< fmt::is_tuple_like< TupleT >::value > >::format_each< FormatContext >::operator()().
write_range_entry() [1/2]
template<typename Char , typename OutputIt , typename Arg , FMT_ENABLE_IF(is_std_string_like< typename std::decay< Arg >::type >::value) > OutputIt detail::write_range_entry (OutputIt out, const Arg & v)
Definition at line 257 of file ranges.h.
{
   *out++ = '"';
   out = write<Char>(out, v);
   *out++ = '"';
   return out;
 }
write_range_entry() [2/2]
template<typename Char , typename OutputIt , typename Arg , FMT_ENABLE_IF(std::is_same< Arg, Char >::value) > OutputIt detail::write_range_entry (OutputIt out, const Arg v)
Definition at line 266 of file ranges.h.
{
   *out++ = '\'';
   *out++ = v;
   *out++ = '\'';
   return out;
 }