Azerotcore-wotlk: boss_jaraxxus::boss_jaraxxusAI Struct Reference
boss_jaraxxus::boss_jaraxxusAI Struct Reference
Public Member Functions
boss_jaraxxusAI (Creature *pCreature)
void Reset () override
void EnterCombat (Unit *) override
void SpellHit (Unit *caster, const SpellInfo *spell) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void JustReachedHome () override
void JustSummoned (Creature *summon) override
void EnterEvadeMode () override
void MoveInLineOfSight (Unit *) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
EventMap events
SummonList summons
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 102 of file boss_lord_jaraxxus.cpp.
Constructor & Destructor Documentation
boss_jaraxxusAI()
boss_jaraxxus::boss_jaraxxusAI::boss_jaraxxusAI (Creature * pCreature) inline
Definition at line 104 of file boss_lord_jaraxxus.cpp.
                                              : ScriptedAI(pCreature), summons(pCreature)
         {
             pInstance = pCreature->GetInstanceScript();
             me->AddUnitMovementFlag(MOVEMENTFLAG_WALKING);
             me->SetReactState(REACT_PASSIVE);
         }
References Unit::AddUnitMovementFlag(), WorldObject::GetInstanceScript(), ScriptedAI::me, MOVEMENTFLAG_WALKING, pInstance, REACT_PASSIVE, and Creature::SetReactState().
Member Function Documentation
EnterCombat()
void boss_jaraxxus::boss_jaraxxusAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 128 of file boss_lord_jaraxxus.cpp.
         {
             me->setActive(true);
             events.Reset();
             events.RescheduleEvent(EVENT_SPELL_FEL_FIREBALL, 5000);
             events.RescheduleEvent(EVENT_SPELL_FEL_LIGHTNING, urand(10000, 15000));
             events.RescheduleEvent(EVENT_SPELL_INCINERATE_FLESH, urand(24000, 26000));
             events.RescheduleEvent(EVENT_SPELL_NETHER_POWER, urand(25000, 45000));
             events.RescheduleEvent(EVENT_SPELL_LEGION_FLAME, 30000);
             //if( GetDifficulty() == RAID_DIFFICULTY_25MAN_HEROIC )
             //  events.RescheduleEvent(EVENT_SPELL_TOUCH_OF_JARAXXUS, urand(10000,15000));
             events.RescheduleEvent(EVENT_SUMMON_NETHER_PORTAL, 20000); // it schedules EVENT_SUMMON_VOLCANO
             me->RemoveAura(SPELL_CHAINS);
             Talk(SAY_AGGRO);
             DoZoneInCombat();
             if( pInstance )
                 pInstance->SetData(TYPE_JARAXXUS, IN_PROGRESS);
         }
References CreatureAI::DoZoneInCombat(), EVENT_SPELL_FEL_FIREBALL, EVENT_SPELL_FEL_LIGHTNING, EVENT_SPELL_INCINERATE_FLESH, EVENT_SPELL_LEGION_FLAME, EVENT_SPELL_NETHER_POWER, EVENT_SUMMON_NETHER_PORTAL, IN_PROGRESS, ScriptedAI::me, pInstance, Unit::RemoveAura(), SAY_AGGRO, WorldObject::setActive(), ZoneScript::SetData(), SPELL_CHAINS, CreatureAI::Talk(), TYPE_JARAXXUS, and urand().
EnterEvadeMode()
void boss_jaraxxus::boss_jaraxxusAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 282 of file boss_lord_jaraxxus.cpp.
         {
             events.Reset();
             summons.DespawnAll();
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
             if( pInstance )
                 pInstance->SetData(TYPE_FAILED, 1);
         }
References SummonList::DespawnAll(), ScriptedAI::me, pInstance, ZoneScript::SetData(), Object::SetFlag(), summons, TYPE_FAILED, UNIT_FIELD_FLAGS, and UNIT_FLAG_NON_ATTACKABLE.
JustDied()
void boss_jaraxxus::boss_jaraxxusAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 264 of file boss_lord_jaraxxus.cpp.
         {
             summons.DespawnAll();
             Talk(SAY_DEATH);
             if( pInstance )
                 pInstance->SetData(TYPE_JARAXXUS, DONE);
         }
References SummonList::DespawnAll(), DONE, pInstance, SAY_DEATH, ZoneScript::SetData(), summons, CreatureAI::Talk(), and TYPE_JARAXXUS.
JustReachedHome()
void boss_jaraxxus::boss_jaraxxusAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 272 of file boss_lord_jaraxxus.cpp.
         {
             me->setActive(false);
         }
References ScriptedAI::me, and WorldObject::setActive().
JustSummoned()
void boss_jaraxxus::boss_jaraxxusAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 277 of file boss_lord_jaraxxus.cpp.
         {
             summons.Summon(summon);
         }
References SummonList::Summon(), and summons.
MoveInLineOfSight()
void boss_jaraxxus::boss_jaraxxusAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 291 of file boss_lord_jaraxxus.cpp.
 {}
Reset()
void boss_jaraxxus::boss_jaraxxusAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 115 of file boss_lord_jaraxxus.cpp.
         {
             events.Reset();
             if( pInstance )
                 pInstance->SetData(TYPE_JARAXXUS, NOT_STARTED);
             // checked for safety
             while( Creature* c = me->FindNearestCreature(NPC_INFERNAL_VOLCANO, 500.0f, true) )
                 c->DespawnOrUnsummon();
             while( Creature* c = me->FindNearestCreature(NPC_NETHER_PORTAL, 500.0f, true) )
                 c->DespawnOrUnsummon();
         }
References WorldObject::FindNearestCreature(), ScriptedAI::me, NOT_STARTED, NPC_INFERNAL_VOLCANO, NPC_NETHER_PORTAL, pInstance, ZoneScript::SetData(), and TYPE_JARAXXUS.
SpellHit()
void boss_jaraxxus::boss_jaraxxusAI::SpellHit (Unit * caster, const SpellInfo * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 148 of file boss_lord_jaraxxus.cpp.
         {
             switch( spell->Id )
             {
                 case 66228:
                 case 67106:
                 case 67107:
                 case 67108:
                     if( Aura* a = me->GetAura(spell->Id) )
                         a->SetStackAmount(spell->StackAmount);
                     break;
                 case 30449:
                     {
                         if( !caster )
                             return;
                         uint32 id = 0;
                         switch( me->GetMap()->GetDifficulty() )
{
                             case 0:
                                 id = 66228;
                                 break;
                             case 1:
                                 id = 67106;
                                 break;
                             case 2:
                                 id = 67107;
                                 break;
                             case 3:
                                 id = 67108;
                                 break;
                         }
                         if( Aura* a = me->GetAura(id) )
{
                             if( a->GetStackAmount() > 1 )
                                 a->ModStackAmount(-1);
                             else
                                 a->Remove();
                             caster->CastSpell(caster, SPELL_NETHER_POWER, true);
                         }
                     }
                     break;
                 default:
                     break;
             }
         }
References Unit::CastSpell(), Unit::GetAura(), Map::GetDifficulty(), WorldObject::GetMap(), SpellInfo::Id, ScriptedAI::me, SPELL_NETHER_POWER, and SpellInfo::StackAmount.
UpdateAI()
void boss_jaraxxus::boss_jaraxxusAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 194 of file boss_lord_jaraxxus.cpp.
         {
             if( !UpdateVictim() )
                 return;
             events.Update(diff);
             if( me->HasUnitState(UNIT_STATE_CASTING) )
                 return;
             switch( events.ExecuteEvent() )
             {
                 case 0:
                     break;
                 case EVENT_SPELL_FEL_FIREBALL:
                     if( me->GetVictim() )
                         me->CastSpell(me->GetVictim(), SPELL_FEL_FIREBALL, false);
                     events.RepeatEvent(urand(10000, 15000));
                     break;
                 case EVENT_SPELL_FEL_LIGHTNING:
                     if( Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 0.0f, true) )
                         me->CastSpell(target, SPELL_FEL_LIGHTNING, false);
                     events.RepeatEvent(urand(10000, 15000));
                     break;
                 case EVENT_SPELL_INCINERATE_FLESH:
                     if( Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 0.0f, true) )
                     {
                         Talk(EMOTE_INCINERATE, target);
                         Talk(SAY_INCINERATE);
                         me->CastSpell(target, SPELL_INCINERATE_FLESH, false);
                     }
                     events.RepeatEvent(urand(20000, 25000));
                     break;
                 case EVENT_SPELL_NETHER_POWER:
                     me->CastSpell(me, SPELL_NETHER_POWER, false);
                     events.DelayEvents(5000);
                     events.RepeatEvent(urand(25000, 45000));
                     break;
                 case EVENT_SPELL_LEGION_FLAME:
                     if( Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 0.0f, true) )
                     {
                         Talk(EMOTE_LEGION_FLAME, target);
                         me->CastSpell(target, SPELL_LEGION_FLAME, false);
                     }
                     events.RepeatEvent(30000);
                     break;
                 case EVENT_SPELL_TOUCH_OF_JARAXXUS:
                     if( Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 0.0f, true) )
                         me->CastSpell(target, SPELL_TOUCH_OF_JARAXXUS, false);
                     events.RepeatEvent(urand(10000, 15000));
                     break;
                 case EVENT_SUMMON_NETHER_PORTAL:
                     Talk(EMOTE_NETHER_PORTAL);
                     Talk(SAY_MISTRESS_OF_PAIN);
                     me->CastSpell((Unit*)nullptr, SPELL_SUMMON_NETHER_PORTAL, false);
                     events.RescheduleEvent(EVENT_SUMMON_VOLCANO, 60000);
                     break;
                 case EVENT_SUMMON_VOLCANO:
                     Talk(EMOTE_INFERNAL_ERUPTION);
                     Talk(SAY_INFERNAL_ERUPTION);
                     me->CastSpell((Unit*)nullptr, SPELL_SUMMON_VOLCANO, false);
                     events.RescheduleEvent(EVENT_SUMMON_NETHER_PORTAL, 60000);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), EMOTE_INCINERATE, EMOTE_INFERNAL_ERUPTION, EMOTE_LEGION_FLAME, EMOTE_NETHER_PORTAL, EVENT_SPELL_FEL_FIREBALL, EVENT_SPELL_FEL_LIGHTNING, EVENT_SPELL_INCINERATE_FLESH, EVENT_SPELL_LEGION_FLAME, EVENT_SPELL_NETHER_POWER, EVENT_SPELL_TOUCH_OF_JARAXXUS, EVENT_SUMMON_NETHER_PORTAL, EVENT_SUMMON_VOLCANO, Unit::GetVictim(), Unit::HasUnitState(), ScriptedAI::me, SAY_INCINERATE, SAY_INFERNAL_ERUPTION, SAY_MISTRESS_OF_PAIN, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), SPELL_FEL_FIREBALL, SPELL_FEL_LIGHTNING, SPELL_INCINERATE_FLESH, SPELL_LEGION_FLAME, SPELL_NETHER_POWER, SPELL_SUMMON_NETHER_PORTAL, SPELL_SUMMON_VOLCANO, SPELL_TOUCH_OF_JARAXXUS, CreatureAI::Talk(), UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
events
EventMap boss_jaraxxus::boss_jaraxxusAI::events
Definition at line 112 of file boss_lord_jaraxxus.cpp.
pInstance
InstanceScript* boss_jaraxxus::boss_jaraxxusAI::pInstance
Definition at line 111 of file boss_lord_jaraxxus.cpp.
Referenced by boss_jaraxxusAI(), EnterCombat(), EnterEvadeMode(), JustDied(), and Reset().
summons
SummonList boss_jaraxxus::boss_jaraxxusAI::summons
Definition at line 113 of file boss_lord_jaraxxus.cpp.
Referenced by EnterEvadeMode(), JustDied(), and JustSummoned().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_lord_jaraxxus.cpp