Azerotcore-wotlk: npc_orb_carrier::npc_orb_carrierAI Struct Reference
npc_orb_carrier::npc_orb_carrierAI Struct Reference
Public Member Functions
npc_orb_carrierAI (Creature *creature)
void UpdateAI (uint32) override
void DoAction (int32 action) override
void TriggerCutter (Unit *caster, Unit *target)
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void Reset ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 757 of file boss_halion.cpp.
Constructor & Destructor Documentation
npc_orb_carrierAI()
npc_orb_carrier::npc_orb_carrierAI::npc_orb_carrierAI (Creature * creature) inline
Definition at line 759 of file boss_halion.cpp.
                                               : NullCreatureAI(creature)
         {
             ASSERT(creature->GetVehicleKit());
         }
References ASSERT, and Unit::GetVehicleKit().
Member Function Documentation
DoAction()
void npc_orb_carrier::npc_orb_carrierAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 770 of file boss_halion.cpp.
         {
             if (action == ACTION_SHOOT)
             {
                 Vehicle* vehicle = me->GetVehicleKit();
                 Unit* southOrb = vehicle->GetPassenger(SEAT_SOUTH);
                 Unit* northOrb = vehicle->GetPassenger(SEAT_NORTH);
                 if (southOrb && northOrb)
                     TriggerCutter(northOrb, southOrb);
                 if (!me->GetMap()->IsHeroic())
                     return;
                 Unit* eastOrb = vehicle->GetPassenger(SEAT_EAST);
                 Unit* westOrb = vehicle->GetPassenger(SEAT_WEST);
                 if (eastOrb && westOrb)
                     TriggerCutter(eastOrb, westOrb);
             }
         }
References ACTION_SHOOT, WorldObject::GetMap(), Vehicle::GetPassenger(), Unit::GetVehicleKit(), Map::IsHeroic(), CreatureAI::me, SEAT_EAST, SEAT_NORTH, SEAT_SOUTH, SEAT_WEST, and TriggerCutter().
TriggerCutter()
void npc_orb_carrier::npc_orb_carrierAI::TriggerCutter (Unit * caster, Unit * target) inline
Definition at line 790 of file boss_halion.cpp.
         {
             caster->CastSpell(caster, SPELL_TWILIGHT_PULSE_PERIODIC, true);
             target->CastSpell(target, SPELL_TWILIGHT_PULSE_PERIODIC, true);
             caster->CastSpell(target, SPELL_TWILIGHT_CUTTER, false);
         }
References Unit::CastSpell(), SPELL_TWILIGHT_CUTTER, and SPELL_TWILIGHT_PULSE_PERIODIC.
Referenced by DoAction().
UpdateAI()
void npc_orb_carrier::npc_orb_carrierAI::UpdateAI (uint32) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 764 of file boss_halion.cpp.
         {
             if (!me->HasUnitState(UNIT_STATE_CASTING))
                 me->CastSpell((Unit*)nullptr, SPELL_TRACK_ROTATION, false);
         }
References Unit::CastSpell(), Unit::HasUnitState(), CreatureAI::me, SPELL_TRACK_ROTATION, and UNIT_STATE_CASTING.
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/ChamberOfAspects/RubySanctum/boss_halion.cpp