Azerotcore-wotlk: npc_apothecary_hanes Class Reference
npc_apothecary_hanes Class Reference
Classes
struct npc_Apothecary_HanesAI
Public Member Functions
npc_apothecary_hanes ()
bool OnQuestAccept (Player *player, Creature *creature, Quest const *quest) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 163 of file zone_howling_fjord.cpp.
Constructor & Destructor Documentation
npc_apothecary_hanes()
npc_apothecary_hanes::npc_apothecary_hanes () inline
Definition at line 166 of file zone_howling_fjord.cpp.
 : CreatureScript("npc_apothecary_hanes") { }
Member Function Documentation
GetAI()
CreatureAI* npc_apothecary_hanes::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 260 of file zone_howling_fjord.cpp.
     {
         return new npc_Apothecary_HanesAI(creature);
     }
OnQuestAccept()
bool npc_apothecary_hanes::OnQuestAccept (Player * player, Creature * creature, Quest const * quest) inline override virtual
Reimplemented from CreatureScript.
Definition at line 168 of file zone_howling_fjord.cpp.
     {
         if (quest->GetQuestId() == QUEST_TRAIL_OF_FIRE)
         {
             creature->SetFaction(player->GetTeamId() == TEAM_ALLIANCE ? FACTION_ESCORTEE_A_PASSIVE : FACTION_ESCORTEE_H_PASSIVE);
             CAST_AI(npc_escortAI, (creature->AI()))->Start(true, false, player->GetGUID());
         }
         return true;
     }
References Creature::AI(), CAST_AI, FACTION_ESCORTEE_A_PASSIVE, FACTION_ESCORTEE_H_PASSIVE, Object::GetGUID(), Quest::GetQuestId(), Player::GetTeamId(), QUEST_TRAIL_OF_FIRE, Unit::SetFaction(), and TEAM_ALLIANCE.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/zone_howling_fjord.cpp