Azerotcore-wotlk: SummonList Class Reference
SummonList Class Reference
#include <ScriptedCreature.h>
Public Types
typedef GuidList StorageType
typedef StorageType::iterator iterator
typedef StorageType::const_iterator const_iterator
typedef StorageType::size_type size_type
typedef StorageType::value_type value_type
Public Member Functions
SummonList (Creature *creature)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
iterator erase (iterator i)
bool empty () const
size_type size () const
void clear ()
void Summon (Creature const *summon)
void Despawn (Creature const *summon)
void DespawnEntry (uint32 entry)
void DespawnAll ()
bool IsAnyCreatureAlive () const
bool IsAnyCreatureInCombat () const
template<typename T >
void DespawnIf (T const &predicate)
void DoAction (int32 info, uint16 max=0)
template<class Predicate >
void DoAction (int32 info, Predicate &&predicate, uint16 max=0)
void DoZoneInCombat (uint32 entry=0)
void RemoveNotExisting ()
bool HasEntry (uint32 entry) const
uint32 GetEntryCount (uint32 entry) const
void Respawn ()
Creature * GetCreatureWithEntry (uint32 entry) const
Private Attributes
Creature * me
StorageType storage_
Detailed Description
Definition at line 32 of file ScriptedCreature.h.
Member Typedef Documentation
const_iterator
typedef StorageType::const_iterator SummonList::const_iterator
Definition at line 37 of file ScriptedCreature.h.
iterator
typedef StorageType::iterator SummonList::iterator
Definition at line 36 of file ScriptedCreature.h.
size_type
typedef StorageType::size_type SummonList::size_type
Definition at line 38 of file ScriptedCreature.h.
StorageType
typedef GuidList SummonList::StorageType
Definition at line 35 of file ScriptedCreature.h.
value_type
typedef StorageType::value_type SummonList::value_type
Definition at line 39 of file ScriptedCreature.h.
Constructor & Destructor Documentation
SummonList()
SummonList::SummonList (Creature * creature) inline explicit
Definition at line 41 of file ScriptedCreature.h.
         : me(creature)
     { }
Member Function Documentation
begin() [1/2]
iterator SummonList::begin () inline
Definition at line 48 of file ScriptedCreature.h.
     {
         return storage_.begin();
     }
References storage_.
Referenced by boss_algalon_the_observer::boss_algalon_the_observerAI::CallConstellations(), boss_shade_of_akama::boss_shade_of_akamaAI::ChannelersAction(), npc_creature_generator_akama::npc_creature_generator_akamaAI::DoAction(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::DoSummonAction(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::EmpowerCultist(), boss_salramm::boss_salrammAI::ExplodeGhoul(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::GetEntryFromSummons(), npc_arthas::npc_arthasAI::GetEventNpc(), boss_moroes::boss_moroesAI::GetRandomGuest(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::InformCloud(), boss_infinite_corruptor::boss_infinite_corruptorAI::JustDied(), boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI::JustDied(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustDied(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::JustSummoned(), boss_captain_skarloc::boss_captain_skarlocAI::MovementInform(), boss_selin_fireheart::boss_selin_fireheartAI::SelectNearestCrystal(), npc_xt002_heart::npc_xt002_heartAI::SendEnergyToCorner(), boss_kaelthas::boss_kaelthasAI::SetData(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SpidersMoveDown(), boss_kaelthas::boss_kaelthasAI::SummonedCreatureDies(), npc_captain_saeed::npc_captain_saeedAI::SummonsAction(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_kalecgos_kj::npc_kalecgos_kjAI::UpdateAI(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), boss_captain_skarloc::boss_captain_skarlocAI::UpdateAI(), boss_black_knight::boss_black_knightAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), boss_anubrekhan::boss_anubrekhanAI::UpdateAI(), boss_faerlina::boss_faerlinaAI::UpdateAI(), boss_thaddius::boss_thaddiusAI::UpdateAI(), boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI::UpdateAI(), boss_vezax::boss_vezaxAI::UpdateAI(), npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::UpdateAI(), npc_akama_shade::npc_akamaAI::UpdateAI(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::UpdateAI(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::UpdateAI(), boss_kaelthas::boss_kaelthasAI::UpdateAI(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI(), and npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::WaypointReached().
begin() [2/2]
const_iterator SummonList::begin () const inline
Definition at line 53 of file ScriptedCreature.h.
     {
         return storage_.begin();
     }
References storage_.
clear()
void SummonList::clear () inline
Definition at line 83 of file ScriptedCreature.h.
     {
         storage_.clear();
     }
References storage_.
Referenced by boss_black_knight::boss_black_knightAI::DamageTaken(), boss_anubarak_trial::boss_anubarak_trialAI::EnterCombat(), boss_moroes::boss_moroesAI::JustDied(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::JustDied(), npc_captain_saeed::npc_captain_saeedAI::Reset(), and boss_midnight::boss_midnightAI::SummonedCreatureDies().
Despawn()
void SummonList::Despawn (Creature const * summon) inline
Definition at line 89 of file ScriptedCreature.h.
 { storage_.remove(summon->GetGUID()); }
References Object::GetGUID(), and storage_.
Referenced by npc_arthas::npc_arthasAI::DoAction(), npc_arthas::npc_arthasAI::SummonedCreatureDespawn(), boss_anubrekhan::boss_anubrekhanAI::SummonedCreatureDespawn(), boss_gothik::boss_gothikAI::SummonedCreatureDespawn(), boss_flame_leviathan::boss_flame_leviathanAI::SummonedCreatureDespawn(), boss_xt002::boss_xt002AI::SummonedCreatureDespawn(), boss_ichoron::boss_ichoronAI::SummonedCreatureDespawn(), boss_xevozz::boss_xevozzAI::SummonedCreatureDespawn(), boss_zuramat::boss_zuramatAI::SummonedCreatureDespawn(), boss_twin_valkyrAI::SummonedCreatureDespawn(), npc_hor_lich_king::npc_hor_lich_kingAI::SummonedCreatureDespawn(), npc_pos_leader::npc_pos_leaderAI::SummonedCreatureDespawn(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::SummonedCreatureDespawn(), boss_prince_taldaram_icc::boss_prince_taldaramAI::SummonedCreatureDespawn(), npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::SummonedCreatureDespawn(), boss_vezax::boss_vezaxAI::SummonedCreatureDespawn(), boss_hodir::boss_hodirAI::SummonedCreatureDespawn(), boss_mimiron::boss_mimironAI::SummonedCreatureDespawn(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::SummonedCreatureDespawn(), BossAI::SummonedCreatureDespawn(), WorldBossAI::SummonedCreatureDespawn(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::SummonedCreatureDespawn(), npc_necromancer::npc_necromancerAI::SummonedCreatureDespawn(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::SummonedCreatureDespawn(), boss_drakkari_colossus::boss_drakkari_colossusAI::SummonedCreatureDespawn(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::SummonedCreatureDespawn(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::SummonedCreatureDespawn(), npc_precious_icc::npc_precious_iccAI::SummonedCreatureDespawn(), boss_grobbulus::boss_grobbulusAI::SummonedCreatureDespawn(), npc_q24545_lich_king::npc_q24545_lich_kingAI::SummonedCreatureDespawn(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::SummonedCreatureDespawn(), boss_nexusprince_shaffar::boss_nexusprince_shaffarAI::SummonedCreatureDespawn(), boss_illidan_stormrage::boss_illidan_stormrageAI::SummonedCreatureDespawn(), boss_supremus::boss_supremusAI::SummonedCreatureDespawn(), boss_hydross_the_unstable::boss_hydross_the_unstableAI::SummonedCreatureDespawn(), boss_vazruden_the_herald::boss_vazruden_the_heraldAI::SummonedCreatureDespawn(), boss_gluth::boss_gluthAI::SummonedCreatureDies(), boss_emalon::boss_emalonAI::SummonedCreatureDies(), npc_daphne_stilwell::npc_daphne_stilwellAI::SummonedCreatureDies(), npc_grimstone::npc_grimstoneAI::SummonedCreatureDies(), boss_ragnaros::boss_ragnarosAI::SummonedCreatureDies(), boss_selin_fireheart::boss_selin_fireheartAI::SummonedCreatureDies(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::SummonedCreatureDies(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::SummonedCreatureDies(), boss_krik_thir::boss_krik_thirAI::SummonedCreatureDies(), boss_drakkari_colossus::boss_drakkari_colossusAI::SummonedCreatureDies(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonedCreatureDies(), npc_icc_putricades_trap::npc_icc_putricades_trapAI::SummonedCreatureDies(), boss_anzu::boss_anzuAI::SummonedCreatureDies(), boss_illidan_stormrage::boss_illidan_stormrageAI::SummonedCreatureDies(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::SummonedCreatureDies(), npc_creature_generator_akama::npc_creature_generator_akamaAI::SummonedCreatureDies(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::SummonedCreatureDies(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::SummonedCreatureDies(), boss_the_black_stalker::boss_the_black_stalkerAI::SummonedCreatureDies(), boss_vazruden_the_herald::boss_vazruden_the_heraldAI::SummonedCreatureDies(), boss_high_botanist_freywinn::boss_high_botanist_freywinnAI::SummonedCreatureDies(), boss_vexallus::boss_vexallusAI::SummonedCreatureDies(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::SummonedCreatureDies(), npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::SummonedMobDied(), and boss_kalecgos::boss_kalecgosAI::UpdateAI().
DespawnAll()
void SummonList::DespawnAll ()
Definition at line 65 of file ScriptedCreature.cpp.
 {
     while (!storage_.empty())
     {
         Creature* summon = ObjectAccessor::GetCreature(*me, storage_.front());
         storage_.pop_front();
         if (summon)
             summon->DespawnOrUnsummon();
     }
 }
References Creature::DespawnOrUnsummon(), ObjectAccessor::GetCreature(), me, and storage_.
Referenced by BossAI::_JustDied(), WorldBossAI::_JustDied(), BossAI::_Reset(), WorldBossAI::_Reset(), boss_yoggsaron::boss_yoggsaronAI::boss_yoggsaronAI(), boss_sartharion_dragonAI::ClearInstance(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ClearInstance(), npc_captain_saeed::npc_captain_saeedAI::CorpseRemoved(), boss_algalon_the_observer::boss_algalon_the_observerAI::DamageTaken(), boss_freya::boss_freyaAI::DamageTaken(), boss_hodir::boss_hodirAI::DamageTaken(), boss_the_lich_king::boss_the_lich_kingAI::DamageTaken(), npc_fiendish_portal::npc_fiendish_portalAI::DespawnAllImp(), boss_twin_valkyrAI::DoAction(), boss_algalon_the_observer::boss_algalon_the_observerAI::DoAction(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::DoAction(), boss_infinite_corruptor::boss_infinite_corruptorAI::DoAction(), npc_arthas::npc_arthasAI::DoAction(), npc_anub_ar_crusher::npc_anub_ar_crusherAI::DoAction(), boss_black_knight::boss_black_knightAI::DoAction(), boss_anubarak_trial::boss_anubarak_trialAI::DoAction(), boss_gormok::boss_gormokAI::DoAction(), npc_auriaya_feral_defender::npc_auriaya_feral_defenderAI::DoAction(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::DoAction(), boss_yoggsaron::boss_yoggsaronAI::DoAction(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::DoAction(), boss_dalronn_the_controller::boss_dalronn_the_controllerAI::DoAction(), npc_massive_jormungar::npc_massive_jormungarAI::DoAction(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::DoAction(), npc_akama_illidan::npc_akama_illidanAI::DoAction(), npc_creature_generator_akama::npc_creature_generator_akamaAI::DoAction(), npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::EnterCombat(), boss_sindragosa::boss_sindragosaAI::EnterCombat(), boss_illidan_stormrage::boss_illidan_stormrageAI::EnterCombat(), boss_ossirian::boss_ossirianAI::EnterEvadeMode(), boss_viscidus::boss_viscidusAI::EnterEvadeMode(), boss_anubarak_trial::boss_anubarak_trialAI::EnterEvadeMode(), boss_jaraxxus::boss_jaraxxusAI::EnterEvadeMode(), boss_gormok::boss_gormokAI::EnterEvadeMode(), boss_ahune::boss_ahuneAI::EnterEvadeMode(), boss_balinda::boss_balindaAI::JustDied(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::JustDied(), boss_priestess_lackey_commonAI::JustDied(), boss_selin_fireheart::boss_selin_fireheartAI::JustDied(), boss_vexallus::boss_vexallusAI::JustDied(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::JustDied(), boss_sacrolash::boss_sacrolashAI::JustDied(), boss_alythess::boss_alythessAI::JustDied(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::JustDied(), npc_coren_direbrew::npc_coren_direbrewAI::JustDied(), boss_headless_horseman::boss_headless_horsemanAI::JustDied(), boss_archimonde::boss_archimondeAI::JustDied(), boss_salramm::boss_salrammAI::JustDied(), boss_viscidus::boss_viscidusAI::JustDied(), boss_sartharion_dragonAI::JustDied(), boss_anubarak_trial::boss_anubarak_trialAI::JustDied(), boss_jaraxxus::boss_jaraxxusAI::JustDied(), boss_devourer_of_souls::boss_devourer_of_soulsAI::JustDied(), boss_prince_keleseth_icc::boss_prince_kelesethAI::JustDied(), boss_prince_taldaram_icc::boss_prince_taldaramAI::JustDied(), boss_prince_valanar_icc::boss_prince_valanarAI::JustDied(), npc_precious_icc::npc_precious_iccAI::JustDied(), boss_ionar::boss_ionarAI::JustDied(), boss_volkhan::boss_volkhanAI::JustDied(), boss_sjonnir::boss_sjonnirAI::JustDied(), boss_auriaya::boss_auriayaAI::JustDied(), boss_vezax::boss_vezaxAI::JustDied(), boss_kologarn::boss_kologarnAI::JustDied(), boss_razorscale::boss_razorscaleAI::JustDied(), boss_xt002::boss_xt002AI::JustDied(), boss_yoggsaron::boss_yoggsaronAI::JustDied(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::JustDied(), boss_skadi::boss_skadiAI::JustDied(), boss_svala::boss_svalaAI::JustDied(), boss_ymiron::boss_ymironAI::JustDied(), boss_emalon::boss_emalonAI::JustDied(), boss_toravon::boss_toravonAI::JustDied(), boss_ichoron::boss_ichoronAI::JustDied(), boss_xevozz::boss_xevozzAI::JustDied(), boss_zuramat::boss_zuramatAI::JustDied(), boss_nexusprince_shaffar::boss_nexusprince_shaffarAI::JustDied(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::JustDied(), boss_ahune::boss_ahuneAI::JustDied(), boss_the_black_stalker::boss_the_black_stalkerAI::JustDied(), boss_harbinger_skyriss::boss_harbinger_skyrissAI::JustDied(), npc_captain_saeed::npc_captain_saeedAI::JustDied(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::JustDied(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::JustDied(), boss_anubrekhan::boss_anubrekhanAI::JustDied(), boss_gluth::boss_gluthAI::JustDied(), boss_gothik::boss_gothikAI::JustDied(), boss_grobbulus::boss_grobbulusAI::JustDied(), boss_loatheb::boss_loathebAI::JustDied(), boss_maexxna::boss_maexxnaAI::JustDied(), boss_shade_of_akama::boss_shade_of_akamaAI::JustDied(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::JustRespawned(), npc_grimstone::npc_grimstoneAI::npc_grimstoneAI(), boss_skadi_grauf::boss_skadi_graufAI::RemoveSkadi(), boss_balinda::boss_balindaAI::Reset(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::Reset(), boss_gyth::boss_gythAI::Reset(), boss_rend_blackhand::boss_rend_blackhandAI::Reset(), boss_majordomo::boss_majordomoAI::Reset(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::Reset(), boss_priestess_lackey_commonAI::Reset(), boss_selin_fireheart::boss_selin_fireheartAI::Reset(), boss_vexallus::boss_vexallusAI::Reset(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::Reset(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::Reset(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::Reset(), npc_kalecgos_kj::npc_kalecgos_kjAI::Reset(), npc_eris_hevenfire::npc_eris_hevenfireAI::Reset(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::Reset(), npc_daphne_stilwell::npc_daphne_stilwellAI::Reset(), boss_halazzi::boss_halazziAI::Reset(), boss_mandokir::boss_mandokirAI::Reset(), npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::Reset(), npc_coren_direbrew::npc_coren_direbrewAI::Reset(), boss_headless_horseman::boss_headless_horsemanAI::Reset(), npc_love_in_air_hummel::npc_love_in_air_hummelAI::Reset(), boss_archimonde::boss_archimondeAI::Reset(), npc_necromancer::npc_necromancerAI::Reset(), boss_infinite_corruptor::boss_infinite_corruptorAI::Reset(), boss_salramm::boss_salrammAI::Reset(), npc_arthas::npc_arthasAI::Reset(), boss_captain_skarloc::boss_captain_skarlocAI::Reset(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::Reset(), npc_anub_ar_crusher::npc_anub_ar_crusherAI::Reset(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::Reset(), boss_black_knight::boss_black_knightAI::Reset(), boss_anubarak_trial::boss_anubarak_trialAI::Reset(), boss_gormok::boss_gormokAI::Reset(), boss_bronjahm::boss_bronjahmAI::Reset(), boss_devourer_of_souls::boss_devourer_of_soulsAI::Reset(), npc_pos_leader::npc_pos_leaderAI::Reset(), boss_prince_keleseth_icc::boss_prince_kelesethAI::Reset(), boss_prince_taldaram_icc::boss_prince_taldaramAI::Reset(), boss_prince_valanar_icc::boss_prince_valanarAI::Reset(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::Reset(), npc_precious_icc::npc_precious_iccAI::Reset(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::Reset(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::Reset(), npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::Reset(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::Reset(), npc_icc_putricades_trap::npc_icc_putricades_trapAI::Reset(), boss_anubrekhan::boss_anubrekhanAI::Reset(), boss_faerlina::boss_faerlinaAI::Reset(), boss_gluth::boss_gluthAI::Reset(), boss_gothik::boss_gothikAI::Reset(), boss_grobbulus::boss_grobbulusAI::Reset(), boss_kelthuzad::boss_kelthuzadAI::Reset(), boss_loatheb::boss_loathebAI::Reset(), boss_maexxna::boss_maexxnaAI::Reset(), boss_noth::boss_nothAI::Reset(), boss_razuvious::boss_razuviousAI::Reset(), boss_thaddius::boss_thaddiusAI::Reset(), boss_malygos::boss_malygosAI::Reset(), boss_bjarngrim::boss_bjarngrimAI::Reset(), boss_ionar::boss_ionarAI::Reset(), boss_volkhan::boss_volkhanAI::Reset(), boss_sjonnir::boss_sjonnirAI::Reset(), boss_algalon_the_observer::boss_algalon_the_observerAI::Reset(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::Reset(), boss_auriaya::boss_auriayaAI::Reset(), npc_auriaya_feral_defender::npc_auriaya_feral_defenderAI::Reset(), boss_flame_leviathan::boss_flame_leviathanAI::Reset(), boss_freya::boss_freyaAI::Reset(), boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI::Reset(), boss_vezax::boss_vezaxAI::Reset(), boss_hodir::boss_hodirAI::Reset(), boss_kologarn::boss_kologarnAI::Reset(), boss_mimiron::boss_mimironAI::Reset(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::Reset(), boss_razorscale::boss_razorscaleAI::Reset(), boss_thorim::boss_thorimAI::Reset(), boss_xt002::boss_xt002AI::Reset(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::Reset(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::Reset(), boss_dalronn_the_controller::boss_dalronn_the_controllerAI::Reset(), boss_palehoof::boss_palehoofAI::Reset(), npc_massive_jormungar::npc_massive_jormungarAI::Reset(), boss_skadi::boss_skadiAI::Reset(), boss_skadi_grauf::boss_skadi_graufAI::Reset(), boss_svala::boss_svalaAI::Reset(), boss_ymiron::boss_ymironAI::Reset(), boss_toravon::boss_toravonAI::Reset(), boss_ichoron::boss_ichoronAI::Reset(), boss_xevozz::boss_xevozzAI::Reset(), boss_zuramat::boss_zuramatAI::Reset(), npc_q24545_lich_king::npc_q24545_lich_kingAI::Reset(), npc_artruis_the_hearthless::npc_artruis_the_hearthlessAI::Reset(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::Reset(), boss_nexusprince_shaffar::boss_nexusprince_shaffarAI::Reset(), boss_anzu::boss_anzuAI::Reset(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::Reset(), npc_akama_illidan::npc_akama_illidanAI::Reset(), npc_creature_generator_akama::npc_creature_generator_akamaAI::Reset(), boss_the_lurker_below::boss_the_lurker_belowAI::Reset(), boss_the_black_stalker::boss_the_black_stalkerAI::Reset(), boss_olm_the_summoner::boss_olm_the_summonerAI::Reset(), boss_harbinger_skyriss::boss_harbinger_skyrissAI::Reset(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::ResetData(), brann_bronzebeard::brann_bronzebeardAI::ResetEvent(), boss_emalon::boss_emalonAI::ResetSummons(), npc_eris_hevenfire::npc_eris_hevenfireAI::SetGUID(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::SummonChannelers(), BossAI::SummonedCreatureDespawnAll(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), npc_hor_lich_king::npc_hor_lich_kingAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), boss_ymiron::boss_ymironAI::UpdateAI(), boss_xevozz::boss_xevozzAI::UpdateAI(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::UpdateAI(), boss_pathaleon_the_calculator::boss_pathaleon_the_calculatorAI::UpdateAI(), brann_bronzebeard::brann_bronzebeardAI::UpdateEscortAI(), npc_captain_saeed::npc_captain_saeedAI::WaypointReached(), npc_arthas::npc_arthasAI::WaypointReached(), and npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::WaypointReached().
DespawnEntry()
void SummonList::DespawnEntry (uint32 entry)
Definition at line 48 of file ScriptedCreature.cpp.
 {
     for (StorageType::iterator i = storage_.begin(); i != storage_.end();)
     {
         Creature* summon = ObjectAccessor::GetCreature(*me, *i);
         if (!summon)
             i = storage_.erase(i);
         else if (summon->GetEntry() == entry)
         {
             i = storage_.erase(i);
             summon->DespawnOrUnsummon();
         }
         else
             ++i;
     }
 }
References Creature::DespawnOrUnsummon(), ObjectAccessor::GetCreature(), Object::GetEntry(), me, and storage_.
Referenced by boss_algalon_the_observer::boss_algalon_the_observerAI::DamageTaken(), boss_taldaram::boss_taldaramAI::DoAction(), boss_prince_keleseth_icc::boss_prince_kelesethAI::DoAction(), boss_prince_taldaram_icc::boss_prince_taldaramAI::DoAction(), boss_prince_valanar_icc::boss_prince_valanarAI::DoAction(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::DoAction(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::DoAction(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::DoAction(), boss_algalon_the_observer::boss_algalon_the_observerAI::EnterCombat(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_illidan_stormrage::boss_illidan_stormrageAI::JustDied(), boss_the_lich_king::boss_the_lich_kingAI::MovementInform(), boss_the_lich_king::boss_the_lich_kingAI::SpellHitTarget(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::SummonedCreatureDies(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_kalecgos_kj::npc_kalecgos_kjAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::UpdateAI(), boss_sartharion::boss_sartharionAI::UpdateAI(), boss_anubarak_trial::boss_anubarak_trialAI::UpdateAI(), boss_vezax::boss_vezaxAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateAI(), and boss_kaelthas::boss_kaelthasAI::UpdateAI().
DespawnIf()
template<typename T > void SummonList::DespawnIf (T const & predicate) inline
Definition at line 96 of file ScriptedCreature.h.
     {
         storage_.remove_if(predicate);
     }
References storage_.
Referenced by npc_kiljaeden_controller::npc_kiljaeden_controllerAI::JustDied(), and boss_professor_putricide::boss_professor_putricideAI::UpdateAI().
DoAction() [1/2]
template<class Predicate > void SummonList::DoAction (int32 info, Predicate && predicate, uint16 max = 0) inline
Definition at line 116 of file ScriptedCreature.h.
     {
         if (max)
             RemoveNotExisting(); // pussywizard: when max is set, non existing can be chosen and nothing will happen
         // We need to use a copy of SummonList here, otherwise original SummonList would be modified
         StorageType listCopy = storage_;
         Acore::Containers::RandomResize<StorageType, Predicate>(listCopy, std::forward<Predicate>(predicate), max);
         for (auto const& guid : listCopy)
         {
             Creature* summon = ObjectAccessor::GetCreature(*me, guid);
             if (summon && summon->IsAIEnabled)
             {
                 summon->AI()->DoAction(info);
             }
             else if (!summon)
             {
                 storage_.remove(guid);
             }
         }
     }
References Creature::AI(), UnitAI::DoAction(), ObjectAccessor::GetCreature(), Unit::IsAIEnabled, me, RemoveNotExisting(), and storage_.
DoAction() [2/2]
void SummonList::DoAction (int32 info, uint16 max = 0) inline
Definition at line 101 of file ScriptedCreature.h.
     {
         if (max)
             RemoveNotExisting(); // pussywizard: when max is set, non existing can be chosen and nothing will happen
         StorageType listCopy = storage_;
         for (StorageType::const_iterator i = listCopy.begin(); i != listCopy.end(); ++i)
         {
             if (Creature* summon = ObjectAccessor::GetCreature(*me, *i))
                 if (summon->IsAIEnabled)
                     summon->AI()->DoAction(info);
         }
     }
References ObjectAccessor::GetCreature(), me, RemoveNotExisting(), and storage_.
Referenced by boss_yoggsaron_sara::boss_yoggsaron_saraAI::AddPortals(), boss_the_lich_king::boss_the_lich_kingAI::DamageTaken(), boss_thorim::boss_thorimAI::DamageTaken(), npc_coren_direbrew::npc_coren_direbrewAI::DoAction(), boss_prince_taldaram_icc::boss_prince_taldaramAI::DoAction(), boss_the_lich_king::boss_the_lich_kingAI::DoAction(), npc_anub_ar_crusher::npc_anub_ar_crusherAI::DoAction(), boss_drakkari_colossus::boss_drakkari_colossusAI::DoAction(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::DoAction(), boss_shade_of_akama::boss_shade_of_akamaAI::DoAction(), boss_the_lich_king::boss_the_lich_kingAI::EnterEvadeMode(), boss_mimiron::boss_mimironAI::EnterEvadeMode(), boss_shade_of_akama::boss_shade_of_akamaAI::EnterEvadeMode(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::JustDied(), boss_gormok::boss_gormokAI::JustDied(), boss_auriaya::boss_auriayaAI::JustDied(), boss_kelthuzad::boss_kelthuzadAI::JustDied(), boss_shade_of_akama::boss_shade_of_akamaAI::JustDied(), boss_illidan_stormrage::boss_illidan_stormrageAI::MovementInform(), boss_hadronox::boss_hadronoxAI::Reset(), boss_auriaya::boss_auriayaAI::Reset(), boss_flame_leviathan::boss_flame_leviathanAI::Reset(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::Reset(), boss_palehoof::boss_palehoofAI::Reset(), boss_taldaram::boss_taldaramAI::SpellHitTarget(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_coren_direbrew::npc_coren_direbrewAI::UpdateAI(), npc_love_in_air_hummel::npc_love_in_air_hummelAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::UpdateAI(), boss_kelthuzad::boss_kelthuzadAI::UpdateAI(), boss_thaddius::boss_thaddiusAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), boss_ionar::boss_ionarAI::UpdateAI(), boss_volkhan::boss_volkhanAI::UpdateAI(), boss_algalon_the_observer::boss_algalon_the_observerAI::UpdateAI(), boss_auriaya::boss_auriayaAI::UpdateAI(), boss_freya::boss_freyaAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), boss_thorim::boss_thorimAI::UpdateAI(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateAI(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::UpdateAI(), and boss_shade_of_akama::boss_shade_of_akamaAI::UpdateAI().
DoZoneInCombat()
void SummonList::DoZoneInCombat (uint32 entry = 0)
Definition at line 34 of file ScriptedCreature.cpp.
 {
     for (StorageType::iterator i = storage_.begin(); i != storage_.end();)
     {
         Creature* summon = ObjectAccessor::GetCreature(*me, *i);
         ++i;
         if (summon && summon->IsAIEnabled
                 && (!entry || summon->GetEntry() == entry))
         {
             summon->AI()->DoZoneInCombat();
         }
     }
 }
References Creature::AI(), CreatureAI::DoZoneInCombat(), ObjectAccessor::GetCreature(), Object::GetEntry(), Unit::IsAIEnabled, me, and storage_.
Referenced by boss_priestess_delrissa::boss_priestess_delrissaAI::EnterCombat(), boss_auriaya::boss_auriayaAI::EnterCombat(), boss_emalon::boss_emalonAI::EnterCombat(), boss_nexusprince_shaffar::boss_nexusprince_shaffarAI::EnterCombat(), boss_faerlina::boss_faerlinaAI::EnterCombat(), boss_razuvious::boss_razuviousAI::EnterCombat(), boss_thaddius::boss_thaddiusAI::EnterCombat(), boss_gothik::boss_gothikAI::JustSummoned(), boss_krik_thir::boss_krik_thirAI::UpdateAI(), and boss_gothik::boss_gothikAI::UpdateAI().
empty()
bool SummonList::empty () const inline
Definition at line 73 of file ScriptedCreature.h.
     {
         return storage_.empty();
     }
References storage_.
Referenced by boss_volazj::boss_volazjAI::CheckPhaseMinions(), boss_sartharion::boss_sartharionAI::DamageTaken(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::EmpowerCultist(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::MovementInform(), npc_captain_saeed::npc_captain_saeedAI::Reset(), boss_selin_fireheart::boss_selin_fireheartAI::SelectNearestCrystal(), boss_sartharion::boss_sartharionAI::SendLavaWaves(), npc_daphne_stilwell::npc_daphne_stilwellAI::SummonedCreatureDies(), npc_grimstone::npc_grimstoneAI::SummonedCreatureDies(), boss_anzu::boss_anzuAI::SummonedCreatureDies(), npc_artruis_the_hearthless::npc_artruis_the_hearthlessAI::SummonsAction(), boss_balinda::boss_balindaAI::UpdateAI(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), boss_viscidus::boss_viscidusAI::UpdateAI(), boss_sartharion::boss_sartharionAI::UpdateAI(), boss_black_knight::boss_black_knightAI::UpdateAI(), boss_emalon::boss_emalonAI::UpdateAI(), npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::UpdateAI(), and boss_ichoron::boss_ichoronAI::UpdateAI().
end() [1/2]
iterator SummonList::end () inline
Definition at line 58 of file ScriptedCreature.h.
     {
         return storage_.end();
     }
References storage_.
Referenced by boss_algalon_the_observer::boss_algalon_the_observerAI::CallConstellations(), boss_shade_of_akama::boss_shade_of_akamaAI::ChannelersAction(), npc_creature_generator_akama::npc_creature_generator_akamaAI::DoAction(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::DoSummonAction(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::EmpowerCultist(), boss_salramm::boss_salrammAI::ExplodeGhoul(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::GetEntryFromSummons(), npc_arthas::npc_arthasAI::GetEventNpc(), boss_moroes::boss_moroesAI::GetRandomGuest(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::InformCloud(), boss_infinite_corruptor::boss_infinite_corruptorAI::JustDied(), boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI::JustDied(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustDied(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::JustSummoned(), boss_captain_skarloc::boss_captain_skarlocAI::MovementInform(), boss_selin_fireheart::boss_selin_fireheartAI::SelectNearestCrystal(), npc_xt002_heart::npc_xt002_heartAI::SendEnergyToCorner(), boss_kaelthas::boss_kaelthasAI::SetData(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SpidersMoveDown(), boss_kaelthas::boss_kaelthasAI::SummonedCreatureDies(), npc_captain_saeed::npc_captain_saeedAI::SummonsAction(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_kalecgos_kj::npc_kalecgos_kjAI::UpdateAI(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), boss_captain_skarloc::boss_captain_skarlocAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), boss_anubrekhan::boss_anubrekhanAI::UpdateAI(), boss_faerlina::boss_faerlinaAI::UpdateAI(), boss_thaddius::boss_thaddiusAI::UpdateAI(), boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI::UpdateAI(), npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::UpdateAI(), npc_akama_shade::npc_akamaAI::UpdateAI(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::UpdateAI(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::UpdateAI(), boss_kaelthas::boss_kaelthasAI::UpdateAI(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI(), and npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::WaypointReached().
end() [2/2]
const_iterator SummonList::end () const inline
Definition at line 63 of file ScriptedCreature.h.
     {
         return storage_.end();
     }
References storage_.
erase()
iterator SummonList::erase (iterator i) inline
Definition at line 68 of file ScriptedCreature.h.
     {
         return storage_.erase(i);
     }
References storage_.
Referenced by npc_arthas::npc_arthasAI::GetEventNpc(), and npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI().
GetCreatureWithEntry()
Creature * SummonList::GetCreatureWithEntry (uint32 entry) const
Definition at line 126 of file ScriptedCreature.cpp.
 {
     for (StorageType::const_iterator i = storage_.begin(); i != storage_.end(); ++i)
     {
         if (Creature* summon = ObjectAccessor::GetCreature(*me, *i))
             if (summon->GetEntry() == entry)
                 return summon;
     }
     return nullptr;
 }
References ObjectAccessor::GetCreature(), me, and storage_.
Referenced by boss_illidan_stormrage::boss_illidan_stormrageAI::DamageTaken(), boss_warbringer_omrogg::boss_warbringer_omroggAI::GetLeftHead(), boss_warbringer_omrogg::boss_warbringer_omroggAI::GetRightHead(), boss_kelthuzad::boss_kelthuzadAI::JustDied(), boss_midnight::boss_midnightAI::KilledUnit(), npc_warden_mellichar::npc_warden_mellicharAI::SummonedCreatureDies(), boss_midnight::boss_midnightAI::UpdateAI(), npc_kalecgos_kj::npc_kalecgos_kjAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), boss_novos::boss_novosAI::UpdateAI(), boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI(), npc_akama_shade::npc_akamaAI::UpdateAI(), npc_warden_mellichar::npc_warden_mellicharAI::UpdateAI(), boss_kaelthas::boss_kaelthasAI::UpdateAI(), and npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::WaypointReached().
GetEntryCount()
uint32 SummonList::GetEntryCount (uint32 entry) const
Definition at line 99 of file ScriptedCreature.cpp.
 {
     uint32 count = 0;
     for (StorageType::const_iterator i = storage_.begin(); i != storage_.end(); ++i)
     {
         Creature* summon = ObjectAccessor::GetCreature(*me, *i);
         if (summon && summon->GetEntry() == entry)
             ++count;
     }
     return count;
 }
References ObjectAccessor::GetCreature(), Object::GetEntry(), me, and storage_.
Referenced by boss_halion::boss_halionAI::JustSummoned(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonedCreatureDies(), boss_halion::boss_halionAI::UpdateAI(), and npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::UpdateAI().
HasEntry()
bool SummonList::HasEntry (uint32 entry) const
Definition at line 87 of file ScriptedCreature.cpp.
 {
     for (StorageType::const_iterator i = storage_.begin(); i != storage_.end(); ++i)
     {
         Creature* summon = ObjectAccessor::GetCreature(*me, *i);
         if (summon && summon->GetEntry() == entry)
             return true;
     }
     return false;
 }
References ObjectAccessor::GetCreature(), Object::GetEntry(), me, and storage_.
Referenced by npc_xt002_heart::npc_xt002_heartAI::DoAction(), boss_anubrekhan::boss_anubrekhanAI::EnterCombat(), boss_krik_thir::boss_krik_thirAI::GetData(), deathblow_to_the_legion_trigger::deathblow_to_the_legion_triggerAI::MoveInLineOfSight(), boss_sartharion_shadron::boss_sartharion_shadronAI::SummonedCreatureDies(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::SummonedCreatureDies(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::SummonedCreatureDies(), boss_ragnaros::boss_ragnarosAI::UpdateAI(), boss_grobbulus::boss_grobbulusAI::UpdateAI(), boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI(), and boss_high_botanist_freywinn::boss_high_botanist_freywinnAI::UpdateAI().
IsAnyCreatureAlive()
bool SummonList::IsAnyCreatureAlive () const
Definition at line 138 of file ScriptedCreature.cpp.
 {
     for (auto const& guid : storage_)
     {
         if (Creature* summon = ObjectAccessor::GetCreature(*me, guid))
         {
             if (summon->IsAlive())
             {
                 return true;
             }
         }
     }
     return false;
 }
References ObjectAccessor::GetCreature(), me, and storage_.
Referenced by boss_rend_blackhand::boss_rend_blackhandAI::SummonedCreatureDies().
IsAnyCreatureInCombat()
bool SummonList::IsAnyCreatureInCombat () const
Definition at line 154 of file ScriptedCreature.cpp.
 {
     for (auto const& guid : storage_)
     {
         if (Creature* summon = ObjectAccessor::GetCreature(*me, guid))
         {
             if (summon->IsInCombat())
             {
                 return true;
             }
         }
     }
     return false;
 }
References ObjectAccessor::GetCreature(), me, and storage_.
Referenced by boss_rend_blackhand::boss_rend_blackhandAI::SummonedCreatureDespawn().
RemoveNotExisting()
void SummonList::RemoveNotExisting ()
Definition at line 76 of file ScriptedCreature.cpp.
 {
     for (StorageType::iterator i = storage_.begin(); i != storage_.end();)
     {
         if (ObjectAccessor::GetCreature(*me, *i))
             ++i;
         else
             i = storage_.erase(i);
     }
 }
References ObjectAccessor::GetCreature(), me, and storage_.
Referenced by boss_volazj::boss_volazjAI::CheckPhaseMinions(), boss_sartharion::boss_sartharionAI::DamageTaken(), DoAction(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), deathblow_to_the_legion_trigger::deathblow_to_the_legion_triggerAI::MoveInLineOfSight(), boss_anzu::boss_anzuAI::SummonedCreatureDies(), boss_sartharion::boss_sartharionAI::SummonLavaWaves(), boss_sartharion::boss_sartharionAI::UpdateAI(), and boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI().
Respawn()
void SummonList::Respawn ()
Definition at line 112 of file ScriptedCreature.cpp.
 {
     for (StorageType::iterator i = storage_.begin(); i != storage_.end();)
     {
         if (Creature* summon = ObjectAccessor::GetCreature(*me, *i))
         {
             summon->Respawn(true);
             ++i;
         }
         else
             i = storage_.erase(i);
     }
 }
References ObjectAccessor::GetCreature(), me, and storage_.
Referenced by boss_priestess_delrissa::boss_priestess_delrissaAI::Reset(), and boss_shade_of_akama::boss_shade_of_akamaAI::UpdateAI().
size()
size_type SummonList::size () const inline
Definition at line 78 of file ScriptedCreature.h.
     {
         return storage_.size();
     }
References storage_.
Referenced by boss_emalon::boss_emalonAI::EnterCombat(), boss_moroes::boss_moroesAI::InitializeGuests(), npc_kalecgos_kj::npc_kalecgos_kjAI::JustSummoned(), boss_captain_skarloc::boss_captain_skarlocAI::JustSummoned(), npc_anub_ar_crusher::npc_anub_ar_crusherAI::JustSummoned(), boss_hodir::boss_hodirAI::Reset(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::SummonedCreatureDespawn(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonedCreatureDies(), boss_vazruden_the_herald::boss_vazruden_the_heraldAI::SummonedCreatureDies(), npc_captain_saeed::npc_captain_saeedAI::SummonsAction(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), boss_flame_leviathan::boss_flame_leviathanAI::UpdateAI(), boss_vezax::boss_vezaxAI::UpdateAI(), and boss_vazruden_the_herald::boss_vazruden_the_heraldAI::UpdateAI().
Summon()
void SummonList::Summon (Creature const * summon) inline
Definition at line 88 of file ScriptedCreature.h.
 { storage_.push_back(summon->GetGUID()); }
References Object::GetGUID(), and storage_.
Referenced by npc_arthas::npc_arthasAI::DoAction(), boss_palehoof::boss_palehoofAI::DoAction(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::DoAction(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), npc_auriaya_feral_defender::npc_auriaya_feral_defenderAI::JustDied(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::JustSummoned(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::JustSummoned(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::JustSummoned(), boss_headless_horseman::boss_headless_horsemanAI::JustSummoned(), npc_love_in_air_hummel::npc_love_in_air_hummelAI::JustSummoned(), boss_infinite_corruptor::boss_infinite_corruptorAI::JustSummoned(), boss_salramm::boss_salrammAI::JustSummoned(), npc_arthas::npc_arthasAI::JustSummoned(), boss_anubrekhan::boss_anubrekhanAI::JustSummoned(), boss_faerlina::boss_faerlinaAI::JustSummoned(), boss_grobbulus::boss_grobbulusAI::JustSummoned(), boss_kelthuzad::boss_kelthuzadAI::JustSummoned(), boss_loatheb::boss_loathebAI::JustSummoned(), boss_maexxna::boss_maexxnaAI::JustSummoned(), boss_razuvious::boss_razuviousAI::JustSummoned(), boss_thaddius::boss_thaddiusAI::JustSummoned(), brann_bronzebeard::brann_bronzebeardAI::JustSummoned(), boss_auriaya::boss_auriayaAI::JustSummoned(), boss_flame_leviathan::boss_flame_leviathanAI::JustSummoned(), boss_freya::boss_freyaAI::JustSummoned(), boss_kologarn::boss_kologarnAI::JustSummoned(), boss_thorim::boss_thorimAI::JustSummoned(), boss_xt002::boss_xt002AI::JustSummoned(), npc_xt002_heart::npc_xt002_heartAI::JustSummoned(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::JustSummoned(), boss_yoggsaron::boss_yoggsaronAI::JustSummoned(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::JustSummoned(), boss_toravon::boss_toravonAI::JustSummoned(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::JustSummoned(), deathblow_to_the_legion_trigger::deathblow_to_the_legion_triggerAI::JustSummoned(), npc_eris_hevenfire::npc_eris_hevenfireAI::JustSummoned(), npc_daphne_stilwell::npc_daphne_stilwellAI::JustSummoned(), npc_coren_direbrew::npc_coren_direbrewAI::JustSummoned(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::JustSummoned(), boss_dalronn_the_controller::boss_dalronn_the_controllerAI::JustSummoned(), boss_ichoron::boss_ichoronAI::JustSummoned(), boss_xevozz::boss_xevozzAI::JustSummoned(), boss_zuramat::boss_zuramatAI::JustSummoned(), npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::JustSummoned(), boss_twin_valkyrAI::JustSummoned(), npc_hor_lich_king::npc_hor_lich_kingAI::JustSummoned(), npc_pos_leader::npc_pos_leaderAI::JustSummoned(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::JustSummoned(), npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::JustSummoned(), boss_hodir::boss_hodirAI::JustSummoned(), boss_mimiron::boss_mimironAI::JustSummoned(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::JustSummoned(), boss_razorscale::boss_razorscaleAI::JustSummoned(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::JustSummoned(), BossAI::JustSummoned(), WorldBossAI::JustSummoned(), npc_grimstone::npc_grimstoneAI::JustSummoned(), boss_gyth::boss_gythAI::JustSummoned(), boss_rend_blackhand::boss_rend_blackhandAI::JustSummoned(), boss_curator::boss_curatorAI::JustSummoned(), boss_midnight::boss_midnightAI::JustSummoned(), boss_moroes::boss_moroesAI::JustSummoned(), npc_fiendish_portal::npc_fiendish_portalAI::JustSummoned(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::JustSummoned(), boss_priestess_delrissa::boss_priestess_delrissaAI::JustSummoned(), boss_priestess_lackey_commonAI::JustSummoned(), boss_selin_fireheart::boss_selin_fireheartAI::JustSummoned(), boss_vexallus::boss_vexallusAI::JustSummoned(), boss_sacrolash::boss_sacrolashAI::JustSummoned(), boss_felmyst::boss_felmystAI::JustSummoned(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::JustSummoned(), npc_kalecgos_kj::npc_kalecgos_kjAI::JustSummoned(), boss_muru::boss_muruAI::JustSummoned(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::JustSummoned(), boss_halazzi::boss_halazziAI::JustSummoned(), npc_necromancer::npc_necromancerAI::JustSummoned(), boss_captain_skarloc::boss_captain_skarlocAI::JustSummoned(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::JustSummoned(), boss_amanitar::boss_amanitarAI::JustSummoned(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::JustSummoned(), boss_taldaram::boss_taldaramAI::JustSummoned(), boss_anub_arak::boss_anub_arakAI::JustSummoned(), boss_hadronox::boss_hadronoxAI::JustSummoned(), npc_anub_ar_crusher::npc_anub_ar_crusherAI::JustSummoned(), boss_krik_thir::boss_krik_thirAI::JustSummoned(), boss_sartharion::boss_sartharionAI::JustSummoned(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::JustSummoned(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::JustSummoned(), boss_general_zarithrian::boss_general_zarithrianAI::JustSummoned(), boss_halion::boss_halionAI::JustSummoned(), boss_black_knight::boss_black_knightAI::JustSummoned(), boss_anubarak_trial::boss_anubarak_trialAI::JustSummoned(), boss_jaraxxus::boss_jaraxxusAI::JustSummoned(), boss_gormok::boss_gormokAI::JustSummoned(), boss_novos::boss_novosAI::JustSummoned(), boss_trollgore::boss_trollgoreAI::JustSummoned(), boss_bronjahm::boss_bronjahmAI::JustSummoned(), boss_devourer_of_souls::boss_devourer_of_soulsAI::JustSummoned(), boss_drakkari_colossus::boss_drakkari_colossusAI::JustSummoned(), boss_slad_ran::boss_slad_ranAI::JustSummoned(), boss_prince_keleseth_icc::boss_prince_kelesethAI::JustSummoned(), boss_prince_taldaram_icc::boss_prince_taldaramAI::JustSummoned(), boss_prince_valanar_icc::boss_prince_valanarAI::JustSummoned(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustSummoned(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustSummoned(), boss_professor_putricide::boss_professor_putricideAI::JustSummoned(), boss_rotface::boss_rotfaceAI::JustSummoned(), npc_precious_icc::npc_precious_iccAI::JustSummoned(), boss_sindragosa::boss_sindragosaAI::JustSummoned(), boss_the_lich_king::boss_the_lich_kingAI::JustSummoned(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::JustSummoned(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::JustSummoned(), npc_icc_putricades_trap::npc_icc_putricades_trapAI::JustSummoned(), boss_gluth::boss_gluthAI::JustSummoned(), boss_gothik::boss_gothikAI::JustSummoned(), boss_noth::boss_nothAI::JustSummoned(), boss_malygos::boss_malygosAI::JustSummoned(), boss_anomalus::boss_anomalusAI::JustSummoned(), boss_magus_telestra::boss_magus_telestraAI::JustSummoned(), boss_ormorok::boss_ormorokAI::JustSummoned(), boss_volkhan::boss_volkhanAI::JustSummoned(), boss_algalon_the_observer::boss_algalon_the_observerAI::JustSummoned(), boss_vezax::boss_vezaxAI::JustSummoned(), boss_svala::boss_svalaAI::JustSummoned(), boss_emalon::boss_emalonAI::JustSummoned(), npc_q24545_lich_king::npc_q24545_lich_kingAI::JustSummoned(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::JustSummoned(), boss_nexusprince_shaffar::boss_nexusprince_shaffarAI::JustSummoned(), boss_anzu::boss_anzuAI::JustSummoned(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::JustSummoned(), boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI::JustSummoned(), boss_illidan_stormrage::boss_illidan_stormrageAI::JustSummoned(), npc_akama_illidan::npc_akama_illidanAI::JustSummoned(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::JustSummoned(), npc_akama_shade::npc_akamaAI::JustSummoned(), npc_creature_generator_akama::npc_creature_generator_akamaAI::JustSummoned(), boss_supremus::boss_supremusAI::JustSummoned(), boss_teron_gorefiend::boss_teron_gorefiendAI::JustSummoned(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::JustSummoned(), boss_hydross_the_unstable::boss_hydross_the_unstableAI::JustSummoned(), boss_lady_vashj::boss_lady_vashjAI::JustSummoned(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::JustSummoned(), boss_the_lurker_below::boss_the_lurker_belowAI::JustSummoned(), boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI::JustSummoned(), boss_ahune::boss_ahuneAI::JustSummoned(), boss_the_black_stalker::boss_the_black_stalkerAI::JustSummoned(), boss_olm_the_summoner::boss_olm_the_summonerAI::JustSummoned(), boss_omor_the_unscarred::boss_omor_the_unscarredAI::JustSummoned(), boss_vazruden_the_herald::boss_vazruden_the_heraldAI::JustSummoned(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::JustSummoned(), boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI::JustSummoned(), npc_warden_mellichar::npc_warden_mellicharAI::JustSummoned(), boss_harbinger_skyriss::boss_harbinger_skyrissAI::JustSummoned(), boss_alar::boss_alarAI::JustSummoned(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::JustSummoned(), boss_kaelthas::boss_kaelthasAI::JustSummoned(), boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI::JustSummoned(), boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI::JustSummoned(), boss_balinda::boss_balindaAI::JustSummoned(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::JustSummoned(), boss_archimonde::boss_archimondeAI::JustSummoned(), boss_warbringer_omrogg::boss_warbringer_omroggAI::JustSummoned(), boss_kaelthas::boss_kaelthasAI::PrepareAdvisors(), npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::PrepareEvent(), boss_bjarngrim::boss_bjarngrimAI::Reset(), boss_skadi::boss_skadiAI::Reset(), npc_artruis_the_hearthless::npc_artruis_the_hearthlessAI::Reset(), npc_captain_saeed::npc_captain_saeedAI::SetGUID(), boss_skadi_grauf::boss_skadi_graufAI::SpawnHelpers(), boss_ionar::boss_ionarAI::Split(), boss_sjonnir::boss_sjonnirAI::SummonDwarfes(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::SummonedCreatureDies(), boss_sjonnir::boss_sjonnirAI::UpdateAI(), boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI::UpdateAI(), npc_massive_jormungar::npc_massive_jormungarAI::UpdateAI(), boss_ymiron::boss_ymironAI::UpdateAI(), and boss_shade_of_akama::boss_shade_of_akamaAI::UpdateAI().
Member Data Documentation
me
Creature* SummonList::me private
Definition at line 147 of file ScriptedCreature.h.
Referenced by DespawnAll(), DespawnEntry(), DoAction(), DoZoneInCombat(), GetCreatureWithEntry(), GetEntryCount(), HasEntry(), IsAnyCreatureAlive(), IsAnyCreatureInCombat(), RemoveNotExisting(), and Respawn().
storage_
StorageType SummonList::storage_ private
Definition at line 148 of file ScriptedCreature.h.
Referenced by begin(), clear(), Despawn(), DespawnAll(), DespawnEntry(), DespawnIf(), DoAction(), DoZoneInCombat(), empty(), end(), erase(), GetCreatureWithEntry(), GetEntryCount(), HasEntry(), IsAnyCreatureAlive(), IsAnyCreatureInCombat(), RemoveNotExisting(), Respawn(), size(), and Summon().
The documentation for this class was generated from the following files:
src/server/game/AI/ScriptedAI/ScriptedCreature.h
src/server/game/AI/ScriptedAI/ScriptedCreature.cpp