Azerotcore-wotlk: deps/jemalloc/src/prof.c File Reference
prof.c File Reference
#include "jemalloc/internal/jemalloc_preamble.h"
#include "jemalloc/internal/jemalloc_internal_includes.h"
#include "jemalloc/internal/assert.h"
#include "jemalloc/internal/ckh.h"
#include "jemalloc/internal/hash.h"
#include "jemalloc/internal/malloc_io.h"
#include "jemalloc/internal/mutex.h"
#include "jemalloc/internal/emitter.h"
Classes
struct prof_bt_node_s
struct prof_thr_node_s
struct prof_alloc_node_s
struct prof_tctx_dump_iter_arg_s
struct prof_gctx_merge_iter_arg_s
struct prof_tdata_merge_iter_arg_s
struct prof_gctx_dump_iter_arg_s
struct prof_emitter_cb_arg_s
Macros
#define JEMALLOC_PROF_C_
#define DUMP_FILENAME_BUFSIZE (PATH_MAX + 1)
#define VSEQ_INVALID UINT64_C(0xffffffffffffffff)
Typedefs
typedef enum prof_logging_state_e prof_logging_state_t
typedef struct prof_bt_node_s prof_bt_node_t
typedef struct prof_thr_node_s prof_thr_node_t
typedef struct prof_alloc_node_s prof_alloc_node_t
Enumerations
enum prof_logging_state_e { prof_logging_state_stopped , prof_logging_state_started , prof_logging_state_dumping }
Functions
static bool prof_tctx_should_destroy (tsdn_t *tsdn, prof_tctx_t *tctx)
static void prof_tctx_destroy (tsd_t *tsd, prof_tctx_t *tctx)
static bool prof_tdata_should_destroy (tsdn_t *tsdn, prof_tdata_t *tdata, bool even_if_attached)
static void prof_tdata_destroy (tsd_t *tsd, prof_tdata_t *tdata, bool even_if_attached)
static char * prof_thread_name_alloc (tsdn_t *tsdn, const char *thread_name)
static void prof_thr_node_hash (const void *key, size_t r_hash[2])
static bool prof_thr_node_keycomp (const void *k1, const void *k2)
static void prof_bt_node_hash (const void *key, size_t r_hash[2])
static bool prof_bt_node_keycomp (const void *k1, const void *k2)
static int prof_tctx_comp (const prof_tctx_t *a, const prof_tctx_t *b)
rb_gen (static UNUSED, tctx_tree_, prof_tctx_tree_t, prof_tctx_t, tctx_link, prof_tctx_comp) static int prof_gctx_comp(const prof_gctx_t *a
if (ret==0)
rb_gen (static UNUSED, gctx_tree_, prof_gctx_tree_t, prof_gctx_t, dump_link, prof_gctx_comp) static int prof_tdata_comp(const prof_tdata_t *a
rb_gen (static UNUSED, tdata_tree_, prof_tdata_tree_t, prof_tdata_t, tdata_link, prof_tdata_comp) void prof_alloc_rollback(tsd_t *tsd
cassert (config_prof)
if (updated)
if ((uintptr_t) tctx >(uintptr_t) 1U)
void prof_malloc_sample_object (tsdn_t *tsdn, const void *ptr, size_t usize, prof_tctx_t *tctx)
static size_t prof_log_bt_index (tsd_t *tsd, prof_bt_t *bt)
static size_t prof_log_thr_index (tsd_t *tsd, uint64_t thr_uid, const char *name)
static void prof_try_log (tsd_t *tsd, const void *ptr, size_t usize, prof_tctx_t *tctx)
void prof_free_sampled_object (tsd_t *tsd, const void *ptr, size_t usize, prof_tctx_t *tctx)
void bt_init (prof_bt_t *bt, void **vec)
static void prof_enter (tsd_t *tsd, prof_tdata_t *tdata)
static void prof_leave (tsd_t *tsd, prof_tdata_t *tdata)
void prof_backtrace (prof_bt_t *bt)
static malloc_mutex_t * prof_gctx_mutex_choose (void)
static malloc_mutex_t * prof_tdata_mutex_choose (uint64_t thr_uid)
static prof_gctx_t * prof_gctx_create (tsdn_t *tsdn, prof_bt_t *bt)
static void prof_gctx_try_destroy (tsd_t *tsd, prof_tdata_t *tdata_self, prof_gctx_t *gctx, prof_tdata_t *tdata)
static bool prof_gctx_should_destroy (prof_gctx_t *gctx)
static bool prof_lookup_global (tsd_t *tsd, prof_bt_t *bt, prof_tdata_t *tdata, void **p_btkey, prof_gctx_t **p_gctx, bool *p_new_gctx)
prof_tctx_t * prof_lookup (tsd_t *tsd, prof_bt_t *bt)
void prof_sample_threshold_update (prof_tdata_t *tdata)
static int prof_dump_open_impl (bool propagate_err, const char *filename)
static bool prof_dump_flush (bool propagate_err)
static bool prof_dump_close (bool propagate_err)
static bool prof_dump_write (bool propagate_err, const char *s)
static bool prof_dump_printf (bool propagate_err, const char *format,...)
static void prof_tctx_merge_tdata (tsdn_t *tsdn, prof_tctx_t *tctx, prof_tdata_t *tdata)
static void prof_tctx_merge_gctx (tsdn_t *tsdn, prof_tctx_t *tctx, prof_gctx_t *gctx)
static prof_tctx_t * prof_tctx_merge_iter (prof_tctx_tree_t *tctxs, prof_tctx_t *tctx, void *arg)
static prof_tctx_t * prof_tctx_dump_iter (prof_tctx_tree_t *tctxs, prof_tctx_t *tctx, void *opaque)
static prof_tctx_t * prof_tctx_finish_iter (prof_tctx_tree_t *tctxs, prof_tctx_t *tctx, void *arg)
static void prof_dump_gctx_prep (tsdn_t *tsdn, prof_gctx_t *gctx, prof_gctx_tree_t *gctxs)
static prof_gctx_t * prof_gctx_merge_iter (prof_gctx_tree_t *gctxs, prof_gctx_t *gctx, void *opaque)
static void prof_gctx_finish (tsd_t *tsd, prof_gctx_tree_t *gctxs)
static prof_tdata_t * prof_tdata_merge_iter (prof_tdata_tree_t *tdatas, prof_tdata_t *tdata, void *opaque)
static prof_tdata_t * prof_tdata_dump_iter (prof_tdata_tree_t *tdatas, prof_tdata_t *tdata, void *arg)
static bool prof_dump_header_impl (tsdn_t *tsdn, bool propagate_err, const prof_cnt_t *cnt_all)
static bool prof_dump_gctx (tsdn_t *tsdn, bool propagate_err, prof_gctx_t *gctx, const prof_bt_t *bt, prof_gctx_tree_t *gctxs)
static int prof_open_maps (const char *format,...)
static int prof_getpid (void)
static bool prof_dump_maps (bool propagate_err)
static void prof_leakcheck (const prof_cnt_t *cnt_all, size_t leak_ngctx, const char *filename)
static prof_gctx_t * prof_gctx_dump_iter (prof_gctx_tree_t *gctxs, prof_gctx_t *gctx, void *opaque)
static void prof_dump_prep (tsd_t *tsd, prof_tdata_t *tdata, struct prof_tdata_merge_iter_arg_s *prof_tdata_merge_iter_arg, struct prof_gctx_merge_iter_arg_s *prof_gctx_merge_iter_arg, prof_gctx_tree_t *gctxs)
static bool prof_dump_file (tsd_t *tsd, bool propagate_err, const char *filename, bool leakcheck, prof_tdata_t *tdata, struct prof_tdata_merge_iter_arg_s *prof_tdata_merge_iter_arg, struct prof_gctx_merge_iter_arg_s *prof_gctx_merge_iter_arg, struct prof_gctx_dump_iter_arg_s *prof_gctx_dump_iter_arg, prof_gctx_tree_t *gctxs)
static bool prof_dump (tsd_t *tsd, bool propagate_err, const char *filename, bool leakcheck)
static void prof_dump_filename (char *filename, char v, uint64_t vseq)
static void prof_fdump (void)
bool prof_accum_init (tsdn_t *tsdn, prof_accum_t *prof_accum)
void prof_idump (tsdn_t *tsdn)
bool prof_mdump (tsd_t *tsd, const char *filename)
void prof_gdump (tsdn_t *tsdn)
static void prof_bt_hash (const void *key, size_t r_hash[2])
static bool prof_bt_keycomp (const void *k1, const void *k2)
static uint64_t prof_thr_uid_alloc (tsdn_t *tsdn)
static prof_tdata_t * prof_tdata_init_impl (tsd_t *tsd, uint64_t thr_uid, uint64_t thr_discrim, char *thread_name, bool active)
prof_tdata_t * prof_tdata_init (tsd_t *tsd)
static bool prof_tdata_should_destroy_unlocked (prof_tdata_t *tdata, bool even_if_attached)
static void prof_tdata_destroy_locked (tsd_t *tsd, prof_tdata_t *tdata, bool even_if_attached)
static void prof_tdata_detach (tsd_t *tsd, prof_tdata_t *tdata)
prof_tdata_t * prof_tdata_reinit (tsd_t *tsd, prof_tdata_t *tdata)
static bool prof_tdata_expire (tsdn_t *tsdn, prof_tdata_t *tdata)
static prof_tdata_t * prof_tdata_reset_iter (prof_tdata_tree_t *tdatas, prof_tdata_t *tdata, void *arg)
void prof_reset (tsd_t *tsd, size_t lg_sample)
void prof_tdata_cleanup (tsd_t *tsd)
bool prof_active_get (tsdn_t *tsdn)
bool prof_active_set (tsdn_t *tsdn, bool active)
bool prof_log_start (tsdn_t *tsdn, const char *filename)
static void prof_log_stop_final (void)
static void prof_emitter_write_cb (void *opaque, const char *to_write)
static void prof_log_emit_threads (tsd_t *tsd, emitter_t *emitter)
static void prof_log_emit_traces (tsd_t *tsd, emitter_t *emitter)
static void prof_log_emit_allocs (tsd_t *tsd, emitter_t *emitter)
static void prof_log_emit_metadata (emitter_t *emitter)
bool prof_log_stop (tsdn_t *tsdn)
const char * prof_thread_name_get (tsd_t *tsd)
int prof_thread_name_set (tsd_t *tsd, const char *thread_name)
bool prof_thread_active_get (tsd_t *tsd)
bool prof_thread_active_set (tsd_t *tsd, bool active)
bool prof_thread_active_init_get (tsdn_t *tsdn)
bool prof_thread_active_init_set (tsdn_t *tsdn, bool active_init)
bool prof_gdump_get (tsdn_t *tsdn)
bool prof_gdump_set (tsdn_t *tsdn, bool gdump)
void prof_boot0 (void)
void prof_boot1 (void)
bool prof_boot2 (tsd_t *tsd)
void prof_prefork0 (tsdn_t *tsdn)
void prof_prefork1 (tsdn_t *tsdn)
void prof_postfork_parent (tsdn_t *tsdn)
void prof_postfork_child (tsdn_t *tsdn)
Variables
bool opt_prof = false
bool opt_prof_active = true
bool opt_prof_thread_active_init = true
size_t opt_lg_prof_sample = LG_PROF_SAMPLE_DEFAULT
ssize_t opt_lg_prof_interval = LG_PROF_INTERVAL_DEFAULT
bool opt_prof_gdump = false
bool opt_prof_final = false
bool opt_prof_leak = false
bool opt_prof_accum = false
bool opt_prof_log = false
char opt_prof_prefix [1]
bool prof_active
static malloc_mutex_t prof_active_mtx
static bool prof_thread_active_init
static malloc_mutex_t prof_thread_active_init_mtx
bool prof_gdump_val
static malloc_mutex_t prof_gdump_mtx
uint64_t prof_interval = 0
size_t lg_prof_sample
prof_logging_state_t prof_logging_state = prof_logging_state_stopped
static uint64_t log_seq = 0
static char log_filename [1]
static nstime_t log_start_timestamp = NSTIME_ZERO_INITIALIZER
static size_t log_bt_index = 0
static size_t log_thr_index = 0
static bool log_tables_initialized = false
static ckh_t log_bt_node_set
static ckh_t log_thr_node_set
static prof_bt_node_t * log_bt_first = NULL
static prof_bt_node_t * log_bt_last = NULL
static prof_thr_node_t * log_thr_first = NULL
static prof_thr_node_t * log_thr_last = NULL
static prof_alloc_node_t * log_alloc_first = NULL
static prof_alloc_node_t * log_alloc_last = NULL
static malloc_mutex_t log_mtx
static malloc_mutex_t * gctx_locks
static atomic_u_t cum_gctxs
static malloc_mutex_t * tdata_locks
static ckh_t bt2gctx
malloc_mutex_t bt2gctx_mtx
static prof_tdata_tree_t tdatas
static malloc_mutex_t tdatas_mtx
static uint64_t next_thr_uid
static malloc_mutex_t next_thr_uid_mtx
static malloc_mutex_t prof_dump_seq_mtx
static uint64_t prof_dump_seq
static uint64_t prof_dump_iseq
static uint64_t prof_dump_mseq
static uint64_t prof_dump_useq
static malloc_mutex_t prof_dump_mtx
static char prof_dump_buf [1]
static size_t prof_dump_buf_end
static int prof_dump_fd
static bool prof_booted = false
const prof_gctx_t * b
unsigned b_len = b->bt.len
unsigned comp_len = (a_len < b_len) ? a_len : b_len
int ret = memcmp(a->bt.vec, b->bt.vec, comp_len * sizeof(void *))
uint64_t a_uid = a->thr_uid
uint64_t b_uid = b->thr_uid
prof_tctx_t * tctx
prof_tctx_t bool updated
prof_dump_open_t *JET_MUTABLE prof_dump_open = prof_dump_open_impl
prof_dump_header_t *JET_MUTABLE prof_dump_header = prof_dump_header_impl
Macro Definition Documentation
DUMP_FILENAME_BUFSIZE
#define DUMP_FILENAME_BUFSIZE (PATH_MAX + 1)
Definition at line 1991 of file prof.c.
JEMALLOC_PROF_C_
#define JEMALLOC_PROF_C_
Definition at line 1 of file prof.c.
VSEQ_INVALID
#define VSEQ_INVALID UINT64_C(0xffffffffffffffff)
Definition at line 1992 of file prof.c.
Typedef Documentation
prof_alloc_node_t
typedef struct prof_alloc_node_s prof_alloc_node_t
Definition at line 107 of file prof.c.
prof_bt_node_t
typedef struct prof_bt_node_s prof_bt_node_t
Definition at line 107 of file prof.c.
prof_logging_state_t
typedef enum prof_logging_state_e prof_logging_state_t
Definition at line 73 of file prof.c.
prof_thr_node_t
typedef struct prof_thr_node_s prof_thr_node_t
Definition at line 107 of file prof.c.
Enumeration Type Documentation
prof_logging_state_e
enum prof_logging_state_e
Enumerator
prof_logging_state_stopped
prof_logging_state_started
prof_logging_state_dumping
Definition at line 76 of file prof.c.
{
     prof_logging_state_stopped,
     prof_logging_state_started,
     prof_logging_state_dumping
 };
Function Documentation
bt_init()
void bt_init (prof_bt_t * bt, void ** vec)
Definition at line 540 of file prof.c.
{
     cassert(config_prof);
     bt->vec = vec;
     bt->len = 0;
 }
References cassert(), config_prof, prof_bt_s::len, and prof_bt_s::vec.
Referenced by prof_try_log().
cassert()
cassert (config_prof)
Referenced by arena_dalloc_promoted(), arena_large_dalloc_stats_update(), arena_large_malloc_stats_update(), arena_prof_accum(), arena_prof_alloc_time_get(), arena_prof_alloc_time_set(), arena_prof_demote(), arena_prof_promote(), arena_prof_tctx_get(), arena_prof_tctx_reset(), arena_prof_tctx_set(), arena_stats_merge(), base_stats_get(), bt_init(), chunk_alloc_dss(), chunk_dss_boot(), chunk_in_dss(), extent_alloc_dss(), extent_dss_boot(), extent_dss_mergeable(), extent_gdump_add(), extent_gdump_sub(), extent_in_dss(), prof_accum_add(), prof_accum_cancel(), prof_accum_init(), prof_alloc_time_get(), prof_alloc_time_set(), prof_backtrace(), prof_boot0(), prof_boot1(), prof_boot2(), prof_bt_hash(), prof_bt_keycomp(), prof_dump(), prof_dump_filename(), prof_dump_flush(), prof_dump_gctx(), prof_dump_gctx_prep(), prof_dump_maps(), prof_dump_write(), prof_enter(), prof_fdump(), prof_free(), prof_gctx_try_destroy(), prof_gdump(), prof_idump(), prof_leave(), prof_lookup(), prof_malloc(), prof_mdump(), prof_realloc(), prof_sample_accum_update(), prof_tctx_get(), prof_tctx_reset(), prof_tctx_set(), prof_tdata_get(), prof_tdata_init_impl(), quarantine(), quarantine_boot(), tcache_stats_merge(), and witness_owner().
if() [1/3]
if ((uintptr_t) tctx, (uintptr_t) 1U)
Definition at line 331 of file prof.c.
{
         malloc_mutex_lock(tsd_tsdn(tsd), tctx->tdata->lock);
         tctx->prepared = false;
         if (prof_tctx_should_destroy(tsd_tsdn(tsd), tctx)) {
             prof_tctx_destroy(tsd, tctx);
         } else {
             malloc_mutex_unlock(tsd_tsdn(tsd), tctx->tdata->lock);
         }
     }
References prof_tdata_s::lock, malloc_mutex_lock(), malloc_mutex_unlock(), prof_tctx_s::prepared, prof_tctx_destroy(), prof_tctx_should_destroy(), tctx, prof_tctx_s::tdata, and tsd_tsdn().
if() [2/3]
if (ret = = 0)
Definition at line 282 of file prof.c.
                   {
         ret = (a_len > b_len) - (a_len < b_len);
     }
References b_len, and ret.
if() [3/3]
if (updated)
Definition at line 318 of file prof.c.
                  {
         /*
          * Compute a new sample threshold.  This isn't very important in
          * practice, because this function is rarely executed, so the
          * potential for sample bias is minimal except in contrived
          * programs.
          */
         tdata = prof_tdata_get(tsd, true);
         if (tdata != NULL) {
             prof_sample_threshold_update(tdata);
         }
     }
References NULL, prof_sample_threshold_update(), and prof_tdata_get().
prof_accum_init()
bool prof_accum_init (tsdn_t * tsdn, prof_accum_t * prof_accum)
Definition at line 2033 of file prof.c.
{
     cassert(config_prof);
 #ifndef JEMALLOC_ATOMIC_U64
     if (malloc_mutex_init(&prof_accum->mtx, "prof_accum",
         WITNESS_RANK_PROF_ACCUM, malloc_mutex_rank_exclusive)) {
         return true;
     }
     prof_accum->accumbytes = 0;
 #else
     atomic_store_u64(&prof_accum->accumbytes, 0, ATOMIC_RELAXED);
 #endif
     return false;
 }
References prof_accum_s::accumbytes, ATOMIC_RELAXED, cassert(), config_prof, malloc_mutex_init, malloc_mutex_rank_exclusive, prof_accum_s::mtx, and WITNESS_RANK_PROF_ACCUM.
prof_active_get()
bool prof_active_get (tsdn_t * tsdn)
Definition at line 2400 of file prof.c.
{
     bool prof_active_current;
     malloc_mutex_lock(tsdn, &prof_active_mtx);
     prof_active_current = prof_active;
     malloc_mutex_unlock(tsdn, &prof_active_mtx);
     return prof_active_current;
 }
References malloc_mutex_lock(), malloc_mutex_unlock(), prof_active, prof_active_mtx, and prof_gctx_merge_iter_arg_s::tsdn.
prof_active_set()
bool prof_active_set (tsdn_t * tsdn, bool active)
Definition at line 2410 of file prof.c.
{
     bool prof_active_old;
     malloc_mutex_lock(tsdn, &prof_active_mtx);
     prof_active_old = prof_active;
     prof_active = active;
     malloc_mutex_unlock(tsdn, &prof_active_mtx);
     return prof_active_old;
 }
References malloc_mutex_lock(), malloc_mutex_unlock(), prof_active, prof_active_mtx, and prof_gctx_merge_iter_arg_s::tsdn.
prof_backtrace()
void prof_backtrace (prof_bt_t * bt)
Definition at line 802 of file prof.c.
{
     cassert(config_prof);
     not_reached();
 }
References cassert(), config_prof, and not_reached.
Referenced by prof_try_log().
prof_boot0()
void prof_boot0 (void)
Definition at line 2920 of file prof.c.
                  {
     cassert(config_prof);
     memcpy(opt_prof_prefix, PROF_PREFIX_DEFAULT,
         sizeof(PROF_PREFIX_DEFAULT));
 }
References cassert(), config_prof, memcpy, opt_prof_prefix, and PROF_PREFIX_DEFAULT.
prof_boot1()
void prof_boot1 (void)
Definition at line 2928 of file prof.c.
                  {
     cassert(config_prof);
     /*
      * opt_prof must be in its final state before any arenas are
      * initialized, so this function must be executed early.
      */
     if (opt_prof_leak && !opt_prof) {
         /*
          * Enable opt_prof, but in such a way that profiles are never
          * automatically dumped.
          */
         opt_prof = true;
         opt_prof_gdump = false;
     } else if (opt_prof) {
         if (opt_lg_prof_interval >= 0) {
             prof_interval = (((uint64_t)1U) <<
                 opt_lg_prof_interval);
         }
     }
 }
References cassert(), config_prof, opt_lg_prof_interval, opt_prof, opt_prof_gdump, opt_prof_leak, and prof_interval.
prof_boot2()
bool prof_boot2 (tsd_t * tsd)
Definition at line 2952 of file prof.c.
{
     cassert(config_prof);
     if (opt_prof) {
         unsigned i;
         lg_prof_sample = opt_lg_prof_sample;
         prof_active = opt_prof_active;
         if (malloc_mutex_init(&prof_active_mtx, "prof_active",
             WITNESS_RANK_PROF_ACTIVE, malloc_mutex_rank_exclusive)) {
             return true;
         }
         prof_gdump_val = opt_prof_gdump;
         if (malloc_mutex_init(&prof_gdump_mtx, "prof_gdump",
             WITNESS_RANK_PROF_GDUMP, malloc_mutex_rank_exclusive)) {
             return true;
         }
         prof_thread_active_init = opt_prof_thread_active_init;
         if (malloc_mutex_init(&prof_thread_active_init_mtx,
             "prof_thread_active_init",
             WITNESS_RANK_PROF_THREAD_ACTIVE_INIT,
             malloc_mutex_rank_exclusive)) {
             return true;
         }
         if (ckh_new(tsd, &bt2gctx, PROF_CKH_MINITEMS, prof_bt_hash,
             prof_bt_keycomp)) {
             return true;
         }
         if (malloc_mutex_init(&bt2gctx_mtx, "prof_bt2gctx",
             WITNESS_RANK_PROF_BT2GCTX, malloc_mutex_rank_exclusive)) {
             return true;
         }
         tdata_tree_new(&tdatas);
         if (malloc_mutex_init(&tdatas_mtx, "prof_tdatas",
             WITNESS_RANK_PROF_TDATAS, malloc_mutex_rank_exclusive)) {
             return true;
         }
         next_thr_uid = 0;
         if (malloc_mutex_init(&next_thr_uid_mtx, "prof_next_thr_uid",
             WITNESS_RANK_PROF_NEXT_THR_UID, malloc_mutex_rank_exclusive)) {
             return true;
         }
         if (malloc_mutex_init(&prof_dump_seq_mtx, "prof_dump_seq",
             WITNESS_RANK_PROF_DUMP_SEQ, malloc_mutex_rank_exclusive)) {
             return true;
         }
         if (malloc_mutex_init(&prof_dump_mtx, "prof_dump",
             WITNESS_RANK_PROF_DUMP, malloc_mutex_rank_exclusive)) {
             return true;
         }
         if (opt_prof_final && opt_prof_prefix[0] != '\0' &&
             atexit(prof_fdump) != 0) {
             malloc_write("<jemalloc>: Error in atexit()\n");
             if (opt_abort) {
                 abort();
             }
         }
         if (opt_prof_log) {
             prof_log_start(tsd_tsdn(tsd), NULL);
         }
         if (atexit(prof_log_stop_final) != 0) {
             malloc_write("<jemalloc>: Error in atexit() "
                      "for logging\n");
             if (opt_abort) {
                 abort();
             }
         }
         if (malloc_mutex_init(&log_mtx, "prof_log",
             WITNESS_RANK_PROF_LOG, malloc_mutex_rank_exclusive)) {
             return true;
         }
         if (ckh_new(tsd, &log_bt_node_set, PROF_CKH_MINITEMS,
             prof_bt_node_hash, prof_bt_node_keycomp)) {
             return true;
         }
         if (ckh_new(tsd, &log_thr_node_set, PROF_CKH_MINITEMS,
             prof_thr_node_hash, prof_thr_node_keycomp)) {
             return true;
         }
         log_tables_initialized = true;
         gctx_locks = (malloc_mutex_t *)base_alloc(tsd_tsdn(tsd),
             b0get(), PROF_NCTX_LOCKS * sizeof(malloc_mutex_t),
             CACHELINE);
         if (gctx_locks == NULL) {
             return true;
         }
         for (i = 0; i < PROF_NCTX_LOCKS; i++) {
             if (malloc_mutex_init(&gctx_locks[i], "prof_gctx",
                 WITNESS_RANK_PROF_GCTX,
                 malloc_mutex_rank_exclusive)) {
                 return true;
             }
         }
         tdata_locks = (malloc_mutex_t *)base_alloc(tsd_tsdn(tsd),
             b0get(), PROF_NTDATA_LOCKS * sizeof(malloc_mutex_t),
             CACHELINE);
         if (tdata_locks == NULL) {
             return true;
         }
         for (i = 0; i < PROF_NTDATA_LOCKS; i++) {
             if (malloc_mutex_init(&tdata_locks[i], "prof_tdata",
                 WITNESS_RANK_PROF_TDATA,
                 malloc_mutex_rank_exclusive)) {
                 return true;
             }
         }
 #ifdef JEMALLOC_PROF_LIBGCC
         /*
          * Cause the backtracing machinery to allocate its internal
          * state before enabling profiling.
          */
         _Unwind_Backtrace(prof_unwind_init_callback, NULL);
 #endif
     }
     prof_booted = true;
     return false;
 }
References _Unwind_Backtrace, b0get, base_alloc, bt2gctx, bt2gctx_mtx, CACHELINE, cassert(), ckh_new, config_prof, gctx_locks, lg_prof_sample, log_bt_node_set, log_mtx, log_tables_initialized, log_thr_node_set, malloc_mutex_init, malloc_mutex_rank_exclusive, malloc_write, next_thr_uid, next_thr_uid_mtx, NULL, opt_abort, opt_lg_prof_sample, opt_prof, opt_prof_active, opt_prof_final, opt_prof_gdump, opt_prof_log, opt_prof_prefix, opt_prof_thread_active_init, prof_active, prof_active_mtx, prof_booted, prof_bt_hash(), prof_bt_keycomp(), prof_bt_node_hash(), prof_bt_node_keycomp(), PROF_CKH_MINITEMS, prof_dump_mtx, prof_dump_seq_mtx, prof_fdump(), prof_gdump_mtx, prof_gdump_val, prof_log_start(), prof_log_stop_final(), PROF_NCTX_LOCKS, PROF_NTDATA_LOCKS, prof_thr_node_hash(), prof_thr_node_keycomp(), prof_thread_active_init, prof_thread_active_init_mtx, tdata_locks, tdatas, tdatas_mtx, tsd_tsdn(), WITNESS_RANK_PROF_ACTIVE, WITNESS_RANK_PROF_BT2GCTX, WITNESS_RANK_PROF_DUMP, WITNESS_RANK_PROF_DUMP_SEQ, WITNESS_RANK_PROF_GCTX, WITNESS_RANK_PROF_GDUMP, WITNESS_RANK_PROF_LOG, WITNESS_RANK_PROF_NEXT_THR_UID, WITNESS_RANK_PROF_TDATA, WITNESS_RANK_PROF_TDATAS, and WITNESS_RANK_PROF_THREAD_ACTIVE_INIT.
prof_bt_hash()
static void prof_bt_hash (const void * key, size_t r_hash[2]) static
Definition at line 2140 of file prof.c.
{
     prof_bt_t *bt = (prof_bt_t *)key;
     cassert(config_prof);
     hash(bt->vec, bt->len * sizeof(void *), 0x94122f33U, r_hash);
 }
References cassert(), config_prof, hash(), prof_bt_s::len, and prof_bt_s::vec.
Referenced by prof_boot2(), prof_bt_node_hash(), and prof_tdata_init_impl().
prof_bt_keycomp()
static bool prof_bt_keycomp (const void * k1, const void * k2) static
Definition at line 2149 of file prof.c.
{
     const prof_bt_t *bt1 = (prof_bt_t *)k1;
     const prof_bt_t *bt2 = (prof_bt_t *)k2;
     cassert(config_prof);
     if (bt1->len != bt2->len) {
         return false;
     }
     return (memcmp(bt1->vec, bt2->vec, bt1->len * sizeof(void *)) == 0);
 }
References cassert(), config_prof, prof_bt_s::len, and prof_bt_s::vec.
Referenced by prof_boot2(), prof_bt_node_keycomp(), and prof_tdata_init_impl().
prof_bt_node_hash()
static void prof_bt_node_hash (const void * key, size_t r_hash[2]) static
Definition at line 2162 of file prof.c.
{
     const prof_bt_node_t *bt_node = (prof_bt_node_t *)key;
     prof_bt_hash((void *)(&bt_node->bt), r_hash);
 }
References prof_bt_node_s::bt, and prof_bt_hash().
Referenced by prof_boot2(), and prof_try_log().
prof_bt_node_keycomp()
static bool prof_bt_node_keycomp (const void * k1, const void * k2) static
Definition at line 2168 of file prof.c.
{
     const prof_bt_node_t *bt_node1 = (prof_bt_node_t *)k1;
     const prof_bt_node_t *bt_node2 = (prof_bt_node_t *)k2;
     return prof_bt_keycomp((void *)(&bt_node1->bt),
         (void *)(&bt_node2->bt));
 }
References prof_bt_node_s::bt, and prof_bt_keycomp().
Referenced by prof_boot2(), and prof_try_log().
prof_dump()
static bool prof_dump (tsd_t * tsd, bool propagate_err, const char * filename, bool leakcheck) static
Definition at line 1906 of file prof.c.
                     {
     cassert(config_prof);
     assert(tsd_reentrancy_level_get(tsd) == 0);
     prof_tdata_t * tdata = prof_tdata_get(tsd, true);
     if (tdata == NULL) {
         return true;
     }
     pre_reentrancy(tsd, NULL);
     malloc_mutex_lock(tsd_tsdn(tsd), &prof_dump_mtx);
     prof_gctx_tree_t gctxs;
     struct prof_tdata_merge_iter_arg_s prof_tdata_merge_iter_arg;
     struct prof_gctx_merge_iter_arg_s prof_gctx_merge_iter_arg;
     struct prof_gctx_dump_iter_arg_s prof_gctx_dump_iter_arg;
     prof_dump_prep(tsd, tdata, &prof_tdata_merge_iter_arg,
         &prof_gctx_merge_iter_arg, &gctxs);
     bool err = prof_dump_file(tsd, propagate_err, filename, leakcheck, tdata,
         &prof_tdata_merge_iter_arg, &prof_gctx_merge_iter_arg,
         &prof_gctx_dump_iter_arg, &gctxs);
     prof_gctx_finish(tsd, &gctxs);
     malloc_mutex_unlock(tsd_tsdn(tsd), &prof_dump_mtx);
     post_reentrancy(tsd);
     if (err) {
         return true;
     }
     if (leakcheck) {
         prof_leakcheck(&prof_tdata_merge_iter_arg.cnt_all,
             prof_gctx_merge_iter_arg.leak_ngctx, filename);
     }
     return false;
 }
References assert(), cassert(), prof_tdata_merge_iter_arg_s::cnt_all, config_prof, prof_gctx_merge_iter_arg_s::leak_ngctx, malloc_mutex_lock(), malloc_mutex_unlock(), NULL, post_reentrancy(), pre_reentrancy(), prof_dump_file(), prof_dump_mtx, prof_dump_prep(), prof_gctx_finish(), prof_leakcheck(), prof_tdata_get(), prof_gctx_dump_iter_arg_s::propagate_err, and tsd_tsdn().
Referenced by prof_fdump(), prof_gdump(), prof_idump(), and prof_mdump().
prof_dump_close()
static bool prof_dump_close (bool propagate_err) static
Definition at line 1268 of file prof.c.
{
     bool ret;
     assert(prof_dump_fd != -1);
     ret = prof_dump_flush(propagate_err);
     close(prof_dump_fd);
     prof_dump_fd = -1;
     return ret;
 }
References assert(), close, prof_dump_fd, prof_dump_flush(), and ret.
Referenced by prof_dump_file().
prof_dump_file()
static bool prof_dump_file (tsd_t * tsd, bool propagate_err, const char * filename, bool leakcheck, prof_tdata_t * tdata, struct prof_tdata_merge_iter_arg_s * prof_tdata_merge_iter_arg, struct prof_gctx_merge_iter_arg_s * prof_gctx_merge_iter_arg, struct prof_gctx_dump_iter_arg_s * prof_gctx_dump_iter_arg, prof_gctx_tree_t * gctxs) static
Definition at line 1865 of file prof.c.
{
     /* Create dump file. */
     if ((prof_dump_fd = prof_dump_open(propagate_err, filename)) == -1) {
         return true;
     }
     /* Dump profile header. */
     if (prof_dump_header(tsd_tsdn(tsd), propagate_err,
         &prof_tdata_merge_iter_arg->cnt_all)) {
         goto label_write_error;
     }
     /* Dump per gctx profile stats. */
     prof_gctx_dump_iter_arg->tsdn = tsd_tsdn(tsd);
     prof_gctx_dump_iter_arg->propagate_err = propagate_err;
     if (gctx_tree_iter(gctxs, NULL, prof_gctx_dump_iter,
         (void *)prof_gctx_dump_iter_arg) != NULL) {
         goto label_write_error;
     }
     /* Dump /proc/<pid>/maps if possible. */
     if (prof_dump_maps(propagate_err)) {
         goto label_write_error;
     }
     if (prof_dump_close(propagate_err)) {
         return true;
     }
     return false;
 label_write_error:
     prof_dump_close(propagate_err);
     return true;
 }
References prof_tdata_merge_iter_arg_s::cnt_all, NULL, prof_dump_close(), prof_dump_fd, prof_dump_header, prof_dump_maps(), prof_dump_open, prof_gctx_dump_iter(), prof_gctx_dump_iter_arg_s::propagate_err, tsd_tsdn(), and prof_gctx_dump_iter_arg_s::tsdn.
Referenced by prof_dump().
prof_dump_filename()
static void prof_dump_filename (char * filename, char v, uint64_t vseq) static
Definition at line 1994 of file prof.c.
{
     cassert(config_prof);
     if (vseq != VSEQ_INVALID) {
             /* "<prefix>.<pid>.<seq>.v<vseq>.heap" */
         malloc_snprintf(filename, DUMP_FILENAME_BUFSIZE,
             "%s.%d.%"FMTu64".%c%"FMTu64".heap",
             opt_prof_prefix, prof_getpid(), prof_dump_seq, v, vseq);
     } else {
             /* "<prefix>.<pid>.<seq>.<v>.heap" */
         malloc_snprintf(filename, DUMP_FILENAME_BUFSIZE,
             "%s.%d.%"FMTu64".%c.heap",
             opt_prof_prefix, prof_getpid(), prof_dump_seq, v);
     }
     prof_dump_seq++;
 }
References cassert(), config_prof, DUMP_FILENAME_BUFSIZE, FMTu64, malloc_snprintf, opt_prof_prefix, prof_dump_seq, prof_getpid(), and VSEQ_INVALID.
Referenced by prof_fdump(), prof_gdump(), prof_idump(), and prof_mdump().
prof_dump_flush()
static bool prof_dump_flush (bool propagate_err) static
Definition at line 1245 of file prof.c.
{
     bool ret = false;
     ssize_t err;
     cassert(config_prof);
     err = malloc_write_fd(prof_dump_fd, prof_dump_buf, prof_dump_buf_end);
     if (err == -1) {
         if (!propagate_err) {
             malloc_write("<jemalloc>: write() failed during heap "
                 "profile flush\n");
             if (opt_abort) {
                 abort();
             }
         }
         ret = true;
     }
     prof_dump_buf_end = 0;
     return ret;
 }
References cassert(), config_prof, malloc_write, malloc_write_fd(), opt_abort, prof_dump_buf, prof_dump_buf_end, prof_dump_fd, and ret.
Referenced by prof_dump_close(), prof_dump_maps(), and prof_dump_write().
prof_dump_gctx()
static bool prof_dump_gctx (tsdn_t * tsdn, bool propagate_err, prof_gctx_t * gctx, const prof_bt_t * bt, prof_gctx_tree_t * gctxs) static
Definition at line 1618 of file prof.c.
{
     bool ret;
     unsigned i;
     struct prof_tctx_dump_iter_arg_s prof_tctx_dump_iter_arg;
     cassert(config_prof);
     malloc_mutex_assert_owner(tsdn, gctx->lock);
     /* Avoid dumping such gctx's that have no useful data. */
     if ((!opt_prof_accum && gctx->cnt_summed.curobjs == 0) ||
         (opt_prof_accum && gctx->cnt_summed.accumobjs == 0)) {
         assert(gctx->cnt_summed.curobjs == 0);
         assert(gctx->cnt_summed.curbytes == 0);
         assert(gctx->cnt_summed.accumobjs == 0);
         assert(gctx->cnt_summed.accumbytes == 0);
         ret = false;
         goto label_return;
     }
     if (prof_dump_printf(propagate_err, "@")) {
         ret = true;
         goto label_return;
     }
     for (i = 0; i < bt->len; i++) {
         if (prof_dump_printf(propagate_err, " %#"FMTxPTR,
             (uintptr_t)bt->vec[i])) {
             ret = true;
             goto label_return;
         }
     }
     if (prof_dump_printf(propagate_err,
         "\n"
         "  t*: %"FMTu64": %"FMTu64" [%"FMTu64": %"FMTu64"]\n",
         gctx->cnt_summed.curobjs, gctx->cnt_summed.curbytes,
         gctx->cnt_summed.accumobjs, gctx->cnt_summed.accumbytes)) {
         ret = true;
         goto label_return;
     }
     prof_tctx_dump_iter_arg.tsdn = tsdn;
     prof_tctx_dump_iter_arg.propagate_err = propagate_err;
     if (tctx_tree_iter(&gctx->tctxs, NULL, prof_tctx_dump_iter,
         (void *)&prof_tctx_dump_iter_arg) != NULL) {
         ret = true;
         goto label_return;
     }
     ret = false;
 label_return:
     return ret;
 }
References prof_cnt_s::accumbytes, prof_cnt_s::accumobjs, assert(), cassert(), prof_gctx_s::cnt_summed, config_prof, prof_cnt_s::curbytes, prof_cnt_s::curobjs, FMTu64, FMTxPTR, prof_bt_s::len, prof_gctx_s::lock, malloc_mutex_assert_owner(), NULL, opt_prof_accum, prof_dump_printf(), prof_tctx_dump_iter(), prof_tctx_dump_iter_arg_s::propagate_err, ret, prof_gctx_s::tctxs, prof_tctx_dump_iter_arg_s::tsdn, and prof_bt_s::vec.
Referenced by prof_gctx_dump_iter().
prof_dump_gctx_prep()
static void prof_dump_gctx_prep (tsdn_t * tsdn, prof_gctx_t * gctx, prof_gctx_tree_t * gctxs) static
Definition at line 1450 of file prof.c.
{
     cassert(config_prof);
     malloc_mutex_lock(tsdn, gctx->lock);
     /*
      * Increment nlimbo so that gctx won't go away before dump.
      * Additionally, link gctx into the dump list so that it is included in
      * prof_dump()'s second pass.
      */
     gctx->nlimbo++;
     gctx_tree_insert(gctxs, gctx);
     memset(&gctx->cnt_summed, 0, sizeof(prof_cnt_t));
     malloc_mutex_unlock(tsdn, gctx->lock);
 }
References cassert(), prof_gctx_s::cnt_summed, config_prof, prof_gctx_s::lock, malloc_mutex_lock(), malloc_mutex_unlock(), memset, prof_gctx_s::nlimbo, and prof_tctx_dump_iter_arg_s::tsdn.
Referenced by prof_dump_prep().
prof_dump_header_impl()
static bool prof_dump_header_impl (tsdn_t * tsdn, bool propagate_err, const prof_cnt_t * cnt_all) static
Definition at line 1597 of file prof.c.
{
     bool ret;
     if (prof_dump_printf(propagate_err,
         "heap_v2/%"FMTu64"\n"
         "  t*: %"FMTu64": %"FMTu64" [%"FMTu64": %"FMTu64"]\n",
         ((uint64_t)1U << lg_prof_sample), cnt_all->curobjs,
         cnt_all->curbytes, cnt_all->accumobjs, cnt_all->accumbytes)) {
         return true;
     }
     malloc_mutex_lock(tsdn, &tdatas_mtx);
     ret = (tdata_tree_iter(&tdatas, NULL, prof_tdata_dump_iter,
         (void *)&propagate_err) != NULL);
     malloc_mutex_unlock(tsdn, &tdatas_mtx);
     return ret;
 }
References prof_cnt_s::accumbytes, prof_cnt_s::accumobjs, prof_cnt_s::curbytes, prof_cnt_s::curobjs, FMTu64, lg_prof_sample, malloc_mutex_lock(), malloc_mutex_unlock(), NULL, prof_dump_printf(), prof_tdata_dump_iter(), ret, tdatas, and tdatas_mtx.
prof_dump_maps()
static bool prof_dump_maps (bool propagate_err) static
Definition at line 1707 of file prof.c.
{
     bool ret;
     int mfd;
     cassert(config_prof);
 #ifdef __FreeBSD__
     mfd = prof_open_maps("/proc/curproc/map");
 #elif defined(_WIN32)
     mfd = -1; // Not implemented
 #else
     {
         int pid = prof_getpid();
         mfd = prof_open_maps("/proc/%d/task/%d/maps", pid, pid);
         if (mfd == -1) {
             mfd = prof_open_maps("/proc/%d/maps", pid);
         }
     }
 #endif
     if (mfd != -1) {
         ssize_t nread;
         if (prof_dump_write(propagate_err, "\nMAPPED_LIBRARIES:\n") &&
             propagate_err) {
             ret = true;
             goto label_return;
         }
         nread = 0;
         do {
             prof_dump_buf_end += nread;
             if (prof_dump_buf_end == PROF_DUMP_BUFSIZE) {
                 /* Make space in prof_dump_buf before read(). */
                 if (prof_dump_flush(propagate_err) &&
                     propagate_err) {
                     ret = true;
                     goto label_return;
                 }
             }
             nread = malloc_read_fd(mfd,
                 &prof_dump_buf[prof_dump_buf_end], PROF_DUMP_BUFSIZE
                 - prof_dump_buf_end);
         } while (nread > 0);
     } else {
         ret = true;
         goto label_return;
     }
     ret = false;
 label_return:
     if (mfd != -1) {
         close(mfd);
     }
     return ret;
 }
References cassert(), close, config_prof, malloc_read_fd(), prof_dump_buf, prof_dump_buf_end, PROF_DUMP_BUFSIZE, prof_dump_flush(), prof_dump_write(), prof_getpid(), prof_open_maps(), prof_tctx_dump_iter_arg_s::propagate_err, and ret.
Referenced by prof_dump_file().
prof_dump_open_impl()
static int prof_dump_open_impl (bool propagate_err, const char * filename) static
Definition at line 1228 of file prof.c.
{
     int fd;
     fd = creat(filename, 0644);
     if (fd == -1 && !propagate_err) {
         malloc_printf("<jemalloc>: creat(\"%s\"), 0644) failed\n",
             filename);
         if (opt_abort) {
             abort();
         }
     }
     return fd;
 }
References creat, malloc_printf, and opt_abort.
prof_dump_prep()
static void prof_dump_prep (tsd_t * tsd, prof_tdata_t * tdata, struct prof_tdata_merge_iter_arg_s * prof_tdata_merge_iter_arg, struct prof_gctx_merge_iter_arg_s * prof_gctx_merge_iter_arg, prof_gctx_tree_t * gctxs) static
Definition at line 1823 of file prof.c.
{
     size_t tabind;
     union {
         prof_gctx_t *p;
         void        *v;
     } gctx;
     prof_enter(tsd, tdata);
     /*
      * Put gctx's in limbo and clear their counters in preparation for
      * summing.
      */
     gctx_tree_new(gctxs);
     for (tabind = 0; !ckh_iter(&bt2gctx, &tabind, NULL, &gctx.v);) {
         prof_dump_gctx_prep(tsd_tsdn(tsd), gctx.p, gctxs);
     }
     /*
      * Iterate over tdatas, and for the non-expired ones snapshot their tctx
      * stats and merge them into the associated gctx's.
      */
     prof_tdata_merge_iter_arg->tsdn = tsd_tsdn(tsd);
     memset(&prof_tdata_merge_iter_arg->cnt_all, 0, sizeof(prof_cnt_t));
     malloc_mutex_lock(tsd_tsdn(tsd), &tdatas_mtx);
     tdata_tree_iter(&tdatas, NULL, prof_tdata_merge_iter,
         (void *)prof_tdata_merge_iter_arg);
     malloc_mutex_unlock(tsd_tsdn(tsd), &tdatas_mtx);
     /* Merge tctx stats into gctx's. */
     prof_gctx_merge_iter_arg->tsdn = tsd_tsdn(tsd);
     prof_gctx_merge_iter_arg->leak_ngctx = 0;
     gctx_tree_iter(gctxs, NULL, prof_gctx_merge_iter,
         (void *)prof_gctx_merge_iter_arg);
     prof_leave(tsd, tdata);
 }
References bt2gctx, ckh_iter, prof_tdata_merge_iter_arg_s::cnt_all, prof_gctx_merge_iter_arg_s::leak_ngctx, malloc_mutex_lock(), malloc_mutex_unlock(), memset, NULL, prof_dump_gctx_prep(), prof_enter(), prof_gctx_merge_iter(), prof_leave(), prof_tdata_merge_iter(), tdatas, tdatas_mtx, tsd_tsdn(), prof_gctx_merge_iter_arg_s::tsdn, and prof_tdata_merge_iter_arg_s::tsdn.
Referenced by prof_dump().
prof_dump_printf()
static bool prof_dump_printf (bool propagate_err, const char * format, ...) static
Definition at line 1313 of file prof.c.
{
     bool ret;
     va_list ap;
     char buf[PROF_PRINTF_BUFSIZE];
     va_start(ap, format);
     malloc_vsnprintf(buf, sizeof(buf), format, ap);
     va_end(ap);
     ret = prof_dump_write(propagate_err, buf);
     return ret;
 }
References format(), malloc_vsnprintf, prof_dump_write(), PROF_PRINTF_BUFSIZE, and ret.
Referenced by prof_dump_gctx(), prof_dump_header_impl(), prof_tctx_dump_iter(), and prof_tdata_dump_iter().
prof_dump_write()
static bool prof_dump_write (bool propagate_err, const char * s) static
Definition at line 1280 of file prof.c.
{
     size_t i, slen, n;
     cassert(config_prof);
     i = 0;
     slen = strlen(s);
     while (i < slen) {
         /* Flush the buffer if it is full. */
         if (prof_dump_buf_end == PROF_DUMP_BUFSIZE) {
             if (prof_dump_flush(propagate_err) && propagate_err) {
                 return true;
             }
         }
         if (prof_dump_buf_end + slen - i <= PROF_DUMP_BUFSIZE) {
             /* Finish writing. */
             n = slen - i;
         } else {
             /* Write as much of s as will fit. */
             n = PROF_DUMP_BUFSIZE - prof_dump_buf_end;
         }
         memcpy(&prof_dump_buf[prof_dump_buf_end], &s[i], n);
         prof_dump_buf_end += n;
         i += n;
     }
     assert(i == slen);
     return false;
 }
References assert(), cassert(), config_prof, memcpy, prof_dump_buf, prof_dump_buf_end, PROF_DUMP_BUFSIZE, and prof_dump_flush().
Referenced by prof_dump_maps(), and prof_dump_printf().
prof_emitter_write_cb()
static void prof_emitter_write_cb (void * opaque, const char * to_write) static
Definition at line 2564 of file prof.c.
{
     struct prof_emitter_cb_arg_s *arg =
         (struct prof_emitter_cb_arg_s *)opaque;
     size_t bytes = strlen(to_write);
 #ifdef JEMALLOC_JET
     if (prof_log_dummy) {
         return;
     }
 #endif
     arg->ret = write(arg->fd, (void *)to_write, bytes);
 }
References arg(), and write.
Referenced by prof_log_stop().
prof_enter()
static void prof_enter (tsd_t * tsd, prof_tdata_t * tdata) static
Definition at line 548 of file prof.c.
{
     cassert(config_prof);
     assert(tdata == prof_tdata_get(tsd, false));
     if (tdata != NULL) {
         assert(!tdata->enq);
         tdata->enq = true;
     }
     malloc_mutex_lock(tsd_tsdn(tsd), &bt2gctx_mtx);
 }
References assert(), bt2gctx_mtx, cassert(), config_prof, prof_tdata_s::enq, malloc_mutex_lock(), NULL, prof_tdata_get(), and tsd_tsdn().
Referenced by prof_dump_prep(), prof_gctx_try_destroy(), and prof_lookup_global().
prof_fdump()
static void prof_fdump (void) static
Definition at line 2012 of file prof.c.
                  {
     tsd_t *tsd;
     char filename[DUMP_FILENAME_BUFSIZE];
     cassert(config_prof);
     assert(opt_prof_final);
     assert(opt_prof_prefix[0] != '\0');
     if (!prof_booted) {
         return;
     }
     tsd = tsd_fetch();
     assert(tsd_reentrancy_level_get(tsd) == 0);
     malloc_mutex_lock(tsd_tsdn(tsd), &prof_dump_seq_mtx);
     prof_dump_filename(filename, 'f', VSEQ_INVALID);
     malloc_mutex_unlock(tsd_tsdn(tsd), &prof_dump_seq_mtx);
     prof_dump(tsd, false, filename, opt_prof_leak);
 }
References assert(), cassert(), config_prof, DUMP_FILENAME_BUFSIZE, malloc_mutex_lock(), malloc_mutex_unlock(), opt_prof_final, opt_prof_leak, opt_prof_prefix, prof_booted, prof_dump(), prof_dump_filename(), prof_dump_seq_mtx, tsd_fetch(), tsd_tsdn(), and VSEQ_INVALID.
Referenced by prof_boot2().
prof_free_sampled_object()
void prof_free_sampled_object (tsd_t * tsd, const void * ptr, size_t usize, prof_tctx_t * tctx)
Definition at line 521 of file prof.c.
{
     malloc_mutex_lock(tsd_tsdn(tsd), tctx->tdata->lock);
     assert(tctx->cnts.curobjs > 0);
     assert(tctx->cnts.curbytes >= usize);
     tctx->cnts.curobjs--;
     tctx->cnts.curbytes -= usize;
     prof_try_log(tsd, ptr, usize, tctx);
     if (prof_tctx_should_destroy(tsd_tsdn(tsd), tctx)) {
         prof_tctx_destroy(tsd, tctx);
     } else {
         malloc_mutex_unlock(tsd_tsdn(tsd), tctx->tdata->lock);
     }
 }
References assert(), prof_tctx_s::cnts, prof_cnt_s::curbytes, prof_cnt_s::curobjs, prof_tdata_s::lock, malloc_mutex_lock(), malloc_mutex_unlock(), prof_tctx_destroy(), prof_tctx_should_destroy(), prof_try_log(), ptr(), tctx, prof_tctx_s::tdata, and tsd_tsdn().
prof_gctx_create()
static prof_gctx_t* prof_gctx_create (tsdn_t * tsdn, prof_bt_t * bt) static
Definition at line 821 of file prof.c.
{
     /*
      * Create a single allocation that has space for vec of length bt->len.
      */
     size_t size = offsetof(prof_gctx_t, vec) + (bt->len * sizeof(void *));
     prof_gctx_t *gctx = (prof_gctx_t *)iallocztm(tsdn, size,
         sz_size2index(size), false, NULL, true, arena_get(TSDN_NULL, 0, true),
         true);
     if (gctx == NULL) {
         return NULL;
     }
     gctx->lock = prof_gctx_mutex_choose();
     /*
      * Set nlimbo to 1, in order to avoid a race condition with
      * prof_tctx_destroy()/prof_gctx_try_destroy().
      */
     gctx->nlimbo = 1;
     tctx_tree_new(&gctx->tctxs);
     /* Duplicate bt. */
     memcpy(gctx->vec, bt->vec, bt->len * sizeof(void *));
     gctx->bt.vec = gctx->vec;
     gctx->bt.len = bt->len;
     return gctx;
 }
References arena_get(), prof_gctx_s::bt, iallocztm(), prof_bt_s::len, prof_gctx_s::lock, memcpy, prof_gctx_s::nlimbo, NULL, offsetof, prof_gctx_mutex_choose(), sz_size2index(), prof_gctx_s::tctxs, TSDN_NULL, prof_bt_s::vec, and prof_gctx_s::vec.
Referenced by prof_lookup_global().
prof_gctx_dump_iter()
static prof_gctx_t* prof_gctx_dump_iter (prof_gctx_tree_t * gctxs, prof_gctx_t * gctx, void * opaque) static
Definition at line 1803 of file prof.c.
{
     prof_gctx_t *ret;
     struct prof_gctx_dump_iter_arg_s *arg =
         (struct prof_gctx_dump_iter_arg_s *)opaque;
     malloc_mutex_lock(arg->tsdn, gctx->lock);
     if (prof_dump_gctx(arg->tsdn, arg->propagate_err, gctx, &gctx->bt,
         gctxs)) {
         ret = gctx;
         goto label_return;
     }
     ret = NULL;
 label_return:
     malloc_mutex_unlock(arg->tsdn, gctx->lock);
     return ret;
 }
References arg(), prof_gctx_s::bt, prof_gctx_s::lock, malloc_mutex_lock(), malloc_mutex_unlock(), NULL, prof_dump_gctx(), and ret.
Referenced by prof_dump_file().
prof_gctx_finish()
static void prof_gctx_finish (tsd_t * tsd, prof_gctx_tree_t * gctxs) static
Definition at line 1490 of file prof.c.
{
     prof_tdata_t *tdata = prof_tdata_get(tsd, false);
     prof_gctx_t *gctx;
     /*
      * Standard tree iteration won't work here, because as soon as we
      * decrement gctx->nlimbo and unlock gctx, another thread can
      * concurrently destroy it, which will corrupt the tree.  Therefore,
      * tear down the tree one node at a time during iteration.
      */
     while ((gctx = gctx_tree_first(gctxs)) != NULL) {
         gctx_tree_remove(gctxs, gctx);
         malloc_mutex_lock(tsd_tsdn(tsd), gctx->lock);
         {
             prof_tctx_t *next;
             next = NULL;
             do {
                 prof_tctx_t *to_destroy =
                     tctx_tree_iter(&gctx->tctxs, next,
                     prof_tctx_finish_iter,
                     (void *)tsd_tsdn(tsd));
                 if (to_destroy != NULL) {
                     next = tctx_tree_next(&gctx->tctxs,
                         to_destroy);
                     tctx_tree_remove(&gctx->tctxs,
                         to_destroy);
                     idalloctm(tsd_tsdn(tsd), to_destroy,
                         NULL, NULL, true, true);
                 } else {
                     next = NULL;
                 }
             } while (next != NULL);
         }
         gctx->nlimbo--;
         if (prof_gctx_should_destroy(gctx)) {
             gctx->nlimbo++;
             malloc_mutex_unlock(tsd_tsdn(tsd), gctx->lock);
             prof_gctx_try_destroy(tsd, tdata, gctx, tdata);
         } else {
             malloc_mutex_unlock(tsd_tsdn(tsd), gctx->lock);
         }
     }
 }
References idalloctm(), prof_gctx_s::lock, malloc_mutex_lock(), malloc_mutex_unlock(), next(), prof_gctx_s::nlimbo, NULL, prof_gctx_should_destroy(), prof_gctx_try_destroy(), prof_tctx_finish_iter(), prof_tdata_get(), prof_gctx_s::tctxs, and tsd_tsdn().
Referenced by prof_dump().
prof_gctx_merge_iter()
static prof_gctx_t* prof_gctx_merge_iter (prof_gctx_tree_t * gctxs, prof_gctx_t * gctx, void * opaque) static
Definition at line 1474 of file prof.c.
{
     struct prof_gctx_merge_iter_arg_s *arg =
         (struct prof_gctx_merge_iter_arg_s *)opaque;
     malloc_mutex_lock(arg->tsdn, gctx->lock);
     tctx_tree_iter(&gctx->tctxs, NULL, prof_tctx_merge_iter,
         (void *)arg->tsdn);
     if (gctx->cnt_summed.curobjs != 0) {
         arg->leak_ngctx++;
     }
     malloc_mutex_unlock(arg->tsdn, gctx->lock);
     return NULL;
 }
References arg(), prof_gctx_s::cnt_summed, prof_cnt_s::curobjs, prof_gctx_s::lock, malloc_mutex_lock(), malloc_mutex_unlock(), NULL, prof_tctx_merge_iter(), and prof_gctx_s::tctxs.
Referenced by prof_dump_prep().
prof_gctx_mutex_choose()
static malloc_mutex_t* prof_gctx_mutex_choose (void) static
Definition at line 809 of file prof.c.
{
     unsigned ngctxs = atomic_fetch_add_u(&cum_gctxs, 1, ATOMIC_RELAXED);
     return &gctx_locks[(ngctxs - 1) % PROF_NCTX_LOCKS];
 }
References ATOMIC_RELAXED, cum_gctxs, gctx_locks, and PROF_NCTX_LOCKS.
Referenced by prof_gctx_create().
prof_gctx_should_destroy()
static bool prof_gctx_should_destroy (prof_gctx_t * gctx) static
Definition at line 898 of file prof.c.
{
     if (opt_prof_accum) {
         return false;
     }
     if (!tctx_tree_empty(&gctx->tctxs)) {
         return false;
     }
     if (gctx->nlimbo != 0) {
         return false;
     }
     return true;
 }
References prof_gctx_s::nlimbo, opt_prof_accum, and prof_gctx_s::tctxs.
Referenced by prof_gctx_finish(), and prof_tctx_destroy().
prof_gctx_try_destroy()
static void prof_gctx_try_destroy (tsd_t * tsd, prof_tdata_t * tdata_self, prof_gctx_t * gctx, prof_tdata_t * tdata) static
Definition at line 847 of file prof.c.
{
     cassert(config_prof);
     /*
      * Check that gctx is still unused by any thread cache before destroying
      * it.  prof_lookup() increments gctx->nlimbo in order to avoid a race
      * condition with this function, as does prof_tctx_destroy() in order to
      * avoid a race between the main body of prof_tctx_destroy() and entry
      * into this function.
      */
     prof_enter(tsd, tdata_self);
     malloc_mutex_lock(tsd_tsdn(tsd), gctx->lock);
     assert(gctx->nlimbo != 0);
     if (tctx_tree_empty(&gctx->tctxs) && gctx->nlimbo == 1) {
         /* Remove gctx from bt2gctx. */
         if (ckh_remove(tsd, &bt2gctx, &gctx->bt, NULL, NULL)) {
             not_reached();
         }
         prof_leave(tsd, tdata_self);
         /* Destroy gctx. */
         malloc_mutex_unlock(tsd_tsdn(tsd), gctx->lock);
         idalloctm(tsd_tsdn(tsd), gctx, NULL, NULL, true, true);
     } else {
         /*
          * Compensate for increment in prof_tctx_destroy() or
          * prof_lookup().
          */
         gctx->nlimbo--;
         malloc_mutex_unlock(tsd_tsdn(tsd), gctx->lock);
         prof_leave(tsd, tdata_self);
     }
 }
References assert(), prof_gctx_s::bt, bt2gctx, cassert(), ckh_remove, config_prof, idalloctm(), prof_gctx_s::lock, malloc_mutex_lock(), malloc_mutex_unlock(), prof_gctx_s::nlimbo, not_reached, NULL, prof_enter(), prof_leave(), prof_gctx_s::tctxs, and tsd_tsdn().
Referenced by prof_gctx_finish(), prof_lookup(), and prof_tctx_destroy().
prof_gdump()
void prof_gdump (tsdn_t * tsdn)
Definition at line 2106 of file prof.c.
{
     tsd_t *tsd;
     prof_tdata_t *tdata;
     cassert(config_prof);
     if (!prof_booted || tsdn_null(tsdn) || !prof_active_get_unlocked()) {
         return;
     }
     tsd = tsdn_tsd(tsdn);
     if (tsd_reentrancy_level_get(tsd) > 0) {
         return;
     }
     tdata = prof_tdata_get(tsd, false);
     if (tdata == NULL) {
         return;
     }
     if (tdata->enq) {
         tdata->enq_gdump = true;
         return;
     }
     if (opt_prof_prefix[0] != '\0') {
         char filename[DUMP_FILENAME_BUFSIZE];
         malloc_mutex_lock(tsdn, &prof_dump_seq_mtx);
         prof_dump_filename(filename, 'u', prof_dump_useq);
         prof_dump_useq++;
         malloc_mutex_unlock(tsdn, &prof_dump_seq_mtx);
         prof_dump(tsd, false, filename, false);
     }
 }
References cassert(), config_prof, DUMP_FILENAME_BUFSIZE, prof_tdata_s::enq, prof_tdata_s::enq_gdump, malloc_mutex_lock(), malloc_mutex_unlock(), NULL, opt_prof_prefix, prof_active_get_unlocked(), prof_booted, prof_dump(), prof_dump_filename(), prof_dump_seq_mtx, prof_dump_useq, prof_tdata_get(), prof_gctx_merge_iter_arg_s::tsdn, tsdn_null(), and tsdn_tsd().
Referenced by prof_leave().
prof_gdump_get()
bool prof_gdump_get (tsdn_t * tsdn)
Definition at line 2899 of file prof.c.
{
     bool prof_gdump_current;
     malloc_mutex_lock(tsdn, &prof_gdump_mtx);
     prof_gdump_current = prof_gdump_val;
     malloc_mutex_unlock(tsdn, &prof_gdump_mtx);
     return prof_gdump_current;
 }
References malloc_mutex_lock(), malloc_mutex_unlock(), prof_gdump_mtx, and prof_gdump_val.
prof_gdump_set()
bool prof_gdump_set (tsdn_t * tsdn, bool gdump)
Definition at line 2909 of file prof.c.
{
     bool prof_gdump_old;
     malloc_mutex_lock(tsdn, &prof_gdump_mtx);
     prof_gdump_old = prof_gdump_val;
     prof_gdump_val = gdump;
     malloc_mutex_unlock(tsdn, &prof_gdump_mtx);
     return prof_gdump_old;
 }
References malloc_mutex_lock(), malloc_mutex_unlock(), prof_gdump_mtx, and prof_gdump_val.
prof_getpid()
static int prof_getpid (void) static
Definition at line 1698 of file prof.c.
                   {
 #ifdef _WIN32
     return GetCurrentProcessId();
 #else
     return getpid();
 #endif
 }
Referenced by prof_dump_filename(), prof_dump_maps(), prof_log_emit_metadata(), and prof_log_start().
prof_idump()
void prof_idump (tsdn_t * tsdn)
Definition at line 2049 of file prof.c.
{
     tsd_t *tsd;
     prof_tdata_t *tdata;
     cassert(config_prof);
     if (!prof_booted || tsdn_null(tsdn) || !prof_active_get_unlocked()) {
         return;
     }
     tsd = tsdn_tsd(tsdn);
     if (tsd_reentrancy_level_get(tsd) > 0) {
         return;
     }
     tdata = prof_tdata_get(tsd, false);
     if (tdata == NULL) {
         return;
     }
     if (tdata->enq) {
         tdata->enq_idump = true;
         return;
     }
     if (opt_prof_prefix[0] != '\0') {
         char filename[PATH_MAX + 1];
         malloc_mutex_lock(tsd_tsdn(tsd), &prof_dump_seq_mtx);
         prof_dump_filename(filename, 'i', prof_dump_iseq);
         prof_dump_iseq++;
         malloc_mutex_unlock(tsd_tsdn(tsd), &prof_dump_seq_mtx);
         prof_dump(tsd, false, filename, false);
     }
 }
References cassert(), config_prof, prof_tdata_s::enq, prof_tdata_s::enq_idump, malloc_mutex_lock(), malloc_mutex_unlock(), NULL, opt_prof_prefix, prof_active_get_unlocked(), prof_booted, prof_dump(), prof_dump_filename(), prof_dump_iseq, prof_dump_seq_mtx, prof_tdata_get(), tsd_tsdn(), prof_gctx_merge_iter_arg_s::tsdn, tsdn_null(), and tsdn_tsd().
Referenced by prof_leave().
prof_leakcheck()
static void prof_leakcheck (const prof_cnt_t * cnt_all, size_t leak_ngctx, const char * filename) static
Definition at line 1767 of file prof.c.
{
 #ifdef JEMALLOC_PROF
     /*
      * Scaling is equivalent AdjustSamples() in jeprof, but the result may
      * differ slightly from what jeprof reports, because here we scale the
      * summary values, whereas jeprof scales each context individually and
      * reports the sums of the scaled values.
      */
     if (cnt_all->curbytes != 0) {
         double sample_period = (double)((uint64_t)1 << lg_prof_sample);
         double ratio = (((double)cnt_all->curbytes) /
             (double)cnt_all->curobjs) / sample_period;
         double scale_factor = 1.0 / (1.0 - exp(-ratio));
         uint64_t curbytes = (uint64_t)round(((double)cnt_all->curbytes)
             * scale_factor);
         uint64_t curobjs = (uint64_t)round(((double)cnt_all->curobjs) *
             scale_factor);
         malloc_printf("<jemalloc>: Leak approximation summary: ~%"FMTu64
             " byte%s, ~%"FMTu64" object%s, >= %zu context%s\n",
             curbytes, (curbytes != 1) ? "s" : "", curobjs, (curobjs !=
             1) ? "s" : "", leak_ngctx, (leak_ngctx != 1) ? "s" : "");
         malloc_printf(
             "<jemalloc>: Run jeprof on \"%s\" for leak detail\n",
             filename);
     }
 #endif
 }
References prof_cnt_s::curbytes, prof_cnt_s::curobjs, exp, FMTu64, lg_prof_sample, malloc_printf, ratio(), and G3D::round().
Referenced by prof_dump().
prof_leave()
static void prof_leave (tsd_t * tsd, prof_tdata_t * tdata) static
Definition at line 561 of file prof.c.
{
     cassert(config_prof);
     assert(tdata == prof_tdata_get(tsd, false));
     malloc_mutex_unlock(tsd_tsdn(tsd), &bt2gctx_mtx);
     if (tdata != NULL) {
         bool idump, gdump;
         assert(tdata->enq);
         tdata->enq = false;
         idump = tdata->enq_idump;
         tdata->enq_idump = false;
         gdump = tdata->enq_gdump;
         tdata->enq_gdump = false;
         if (idump) {
             prof_idump(tsd_tsdn(tsd));
         }
         if (gdump) {
             prof_gdump(tsd_tsdn(tsd));
         }
     }
 }
References assert(), bt2gctx_mtx, cassert(), config_prof, prof_tdata_s::enq, prof_tdata_s::enq_gdump, prof_tdata_s::enq_idump, malloc_mutex_unlock(), NULL, prof_gdump(), prof_idump(), prof_tdata_get(), and tsd_tsdn().
Referenced by prof_dump_prep(), prof_gctx_try_destroy(), and prof_lookup_global().
prof_log_bt_index()
static size_t prof_log_bt_index (tsd_t * tsd, prof_bt_t * bt) static
Definition at line 365 of file prof.c.
{
     assert(prof_logging_state == prof_logging_state_started);
     malloc_mutex_assert_owner(tsd_tsdn(tsd), &log_mtx);
     prof_bt_node_t dummy_node;
     dummy_node.bt = *bt;
     prof_bt_node_t *node;
     /* See if this backtrace is already cached in the table. */
     if (ckh_search(&log_bt_node_set, (void *)(&dummy_node),
         (void **)(&node), NULL)) {
         size_t sz = offsetof(prof_bt_node_t, vec) +
                     (bt->len * sizeof(void *));
         prof_bt_node_t *new_node = (prof_bt_node_t *)
             iallocztm(tsd_tsdn(tsd), sz, sz_size2index(sz), false, NULL,
             true, arena_get(TSDN_NULL, 0, true), true);
         if (log_bt_first == NULL) {
             log_bt_first = new_node;
             log_bt_last = new_node;
         } else {
             log_bt_last->next = new_node;
             log_bt_last = new_node;
         }
         new_node->next = NULL;
         new_node->index = log_bt_index;
         /*
          * Copy the backtrace: bt is inside a tdata or gctx, which
          * might die before prof_log_stop is called.
          */
         new_node->bt.len = bt->len;
         memcpy(new_node->vec, bt->vec, bt->len * sizeof(void *));
         new_node->bt.vec = new_node->vec;
         log_bt_index++;
         ckh_insert(tsd, &log_bt_node_set, (void *)new_node, NULL);
         return new_node->index;
     } else {
         return node->index;
     }
 }
References arena_get(), assert(), prof_bt_node_s::bt, ckh_insert, ckh_search, iallocztm(), prof_bt_node_s::index, prof_bt_s::len, log_bt_first, log_bt_index, log_bt_last, log_bt_node_set, log_mtx, malloc_mutex_assert_owner(), memcpy, prof_bt_node_s::next, NULL, offsetof, prof_logging_state, prof_logging_state_started, sz_size2index(), tsd_tsdn(), TSDN_NULL, prof_bt_s::vec, and prof_bt_node_s::vec.
Referenced by prof_try_log().
prof_log_emit_allocs()
static void prof_log_emit_allocs (tsd_t * tsd, emitter_t * emitter) static
Definition at line 2634 of file prof.c.
{
     emitter_json_array_kv_begin(emitter, "allocations");
     prof_alloc_node_t *alloc_node = log_alloc_first;
     prof_alloc_node_t *alloc_old_node;
     while (alloc_node != NULL) {
         emitter_json_object_begin(emitter);
         emitter_json_kv(emitter, "alloc_thread", emitter_type_size,
             &alloc_node->alloc_thr_ind);
         emitter_json_kv(emitter, "free_thread", emitter_type_size,
             &alloc_node->free_thr_ind);
         emitter_json_kv(emitter, "alloc_trace", emitter_type_size,
             &alloc_node->alloc_bt_ind);
         emitter_json_kv(emitter, "free_trace", emitter_type_size,
             &alloc_node->free_bt_ind);
         emitter_json_kv(emitter, "alloc_timestamp",
             emitter_type_uint64, &alloc_node->alloc_time_ns);
         emitter_json_kv(emitter, "free_timestamp", emitter_type_uint64,
             &alloc_node->free_time_ns);
         emitter_json_kv(emitter, "usize", emitter_type_uint64,
             &alloc_node->usize);
         emitter_json_object_end(emitter);
         alloc_old_node = alloc_node;
         alloc_node = alloc_node->next;
         idalloc(tsd, alloc_old_node);
     }
     emitter_json_array_end(emitter);
 }
References prof_alloc_node_s::alloc_bt_ind, prof_alloc_node_s::alloc_thr_ind, prof_alloc_node_s::alloc_time_ns, emitter_json_array_end(), emitter_json_array_kv_begin(), emitter_json_kv(), emitter_json_object_begin(), emitter_json_object_end(), emitter_type_size, emitter_type_uint64, prof_alloc_node_s::free_bt_ind, prof_alloc_node_s::free_thr_ind, prof_alloc_node_s::free_time_ns, idalloc(), log_alloc_first, prof_alloc_node_s::next, NULL, and prof_alloc_node_s::usize.
Referenced by prof_log_stop().
prof_log_emit_metadata()
static void prof_log_emit_metadata (emitter_t * emitter) static
Definition at line 2672 of file prof.c.
{
     emitter_json_object_kv_begin(emitter, "info");
     nstime_t now = NSTIME_ZERO_INITIALIZER;
     nstime_update(&now);
     uint64_t ns = nstime_ns(&now) - nstime_ns(&log_start_timestamp);
     emitter_json_kv(emitter, "duration", emitter_type_uint64, &ns);
     char *vers = JEMALLOC_VERSION;
     emitter_json_kv(emitter, "version",
         emitter_type_string, &vers);
     emitter_json_kv(emitter, "lg_sample_rate",
         emitter_type_int, &lg_prof_sample);
     int pid = prof_getpid();
     emitter_json_kv(emitter, "pid", emitter_type_int, &pid);
     emitter_json_object_end(emitter);
 }
References emitter_json_kv(), emitter_json_object_end(), emitter_json_object_kv_begin(), emitter_type_int, emitter_type_string, emitter_type_uint64, JEMALLOC_VERSION, lg_prof_sample, log_start_timestamp, nstime_ns, nstime_update, NSTIME_ZERO_INITIALIZER, and prof_getpid().
Referenced by prof_log_stop().
prof_log_emit_threads()
static void prof_log_emit_threads (tsd_t * tsd, emitter_t * emitter) static
Definition at line 2581 of file prof.c.
{
     emitter_json_array_kv_begin(emitter, "threads");
     prof_thr_node_t *thr_node = log_thr_first;
     prof_thr_node_t *thr_old_node;
     while (thr_node != NULL) {
         emitter_json_object_begin(emitter);
         emitter_json_kv(emitter, "thr_uid", emitter_type_uint64,
             &thr_node->thr_uid);
         char *thr_name = thr_node->name;
         emitter_json_kv(emitter, "thr_name", emitter_type_string,
             &thr_name);
         emitter_json_object_end(emitter);
         thr_old_node = thr_node;
         thr_node = thr_node->next;
         idalloc(tsd, thr_old_node);
     }
     emitter_json_array_end(emitter);
 }
References emitter_json_array_end(), emitter_json_array_kv_begin(), emitter_json_kv(), emitter_json_object_begin(), emitter_json_object_end(), emitter_type_string, emitter_type_uint64, idalloc(), log_thr_first, prof_thr_node_s::name, prof_thr_node_s::next, NULL, and prof_thr_node_s::thr_uid.
Referenced by prof_log_stop().
prof_log_emit_traces()
static void prof_log_emit_traces (tsd_t * tsd, emitter_t * emitter) static
Definition at line 2605 of file prof.c.
{
     emitter_json_array_kv_begin(emitter, "stack_traces");
     prof_bt_node_t *bt_node = log_bt_first;
     prof_bt_node_t *bt_old_node;
     /*
      * Calculate how many hex digits we need: twice number of bytes, two for
      * "0x", and then one more for terminating '\0'.
      */
     char buf[2 * sizeof(intptr_t) + 3];
     size_t buf_sz = sizeof(buf);
     while (bt_node != NULL) {
         emitter_json_array_begin(emitter);
         size_t i;
         for (i = 0; i < bt_node->bt.len; i++) {
             malloc_snprintf(buf, buf_sz, "%p", bt_node->bt.vec[i]);
             char *trace_str = buf;
             emitter_json_value(emitter, emitter_type_string,
                 &trace_str);
         }
         emitter_json_array_end(emitter);
         bt_old_node = bt_node;
         bt_node = bt_node->next;
         idalloc(tsd, bt_old_node);
     }
     emitter_json_array_end(emitter);
 }
References prof_bt_node_s::bt, emitter_json_array_begin(), emitter_json_array_end(), emitter_json_array_kv_begin(), emitter_json_value(), emitter_type_string, idalloc(), prof_bt_s::len, log_bt_first, malloc_snprintf, prof_bt_node_s::next, NULL, and prof_bt_s::vec.
Referenced by prof_log_stop().
prof_log_start()
bool prof_log_start (tsdn_t * tsdn, const char * filename)
Definition at line 2517 of file prof.c.
{
     if (!opt_prof || !prof_booted) {
         return true;
     }
     bool ret = false;
     size_t buf_size = PATH_MAX + 1;
     malloc_mutex_lock(tsdn, &log_mtx);
     if (prof_logging_state != prof_logging_state_stopped) {
         ret = true;
     } else if (filename == NULL) {
         /* Make default name. */
         malloc_snprintf(log_filename, buf_size, "%s.%d.%"FMTu64".json",
             opt_prof_prefix, prof_getpid(), log_seq);
         log_seq++;
         prof_logging_state = prof_logging_state_started;
     } else if (strlen(filename) >= buf_size) {
         ret = true;
     } else {
         strcpy(log_filename, filename);
         prof_logging_state = prof_logging_state_started;
     }
     if (!ret) {
         nstime_update(&log_start_timestamp);
     }
     malloc_mutex_unlock(tsdn, &log_mtx);
     return ret;
 }
References FMTu64, log_filename, log_mtx, log_seq, log_start_timestamp, malloc_mutex_lock(), malloc_mutex_unlock(), malloc_snprintf, nstime_update, NULL, opt_prof, opt_prof_prefix, prof_booted, prof_getpid(), prof_logging_state, prof_logging_state_started, prof_logging_state_stopped, ret, and prof_gctx_merge_iter_arg_s::tsdn.
Referenced by prof_boot2().
prof_log_stop()
bool prof_log_stop (tsdn_t * tsdn)
Definition at line 2696 of file prof.c.
{
     if (!opt_prof || !prof_booted) {
         return true;
     }
     tsd_t *tsd = tsdn_tsd(tsdn);
     malloc_mutex_lock(tsdn, &log_mtx);
     if (prof_logging_state != prof_logging_state_started) {
         malloc_mutex_unlock(tsdn, &log_mtx);
         return true;
     }
     /*
      * Set the state to dumping. We'll set it to stopped when we're done.
      * Since other threads won't be able to start/stop/log when the state is
      * dumping, we don't have to hold the lock during the whole method.
      */
     prof_logging_state = prof_logging_state_dumping;
     malloc_mutex_unlock(tsdn, &log_mtx);
     emitter_t emitter;
     /* Create a file. */
     int fd;
 #ifdef JEMALLOC_JET
     if (prof_log_dummy) {
         fd = 0;
     } else {
         fd = creat(log_filename, 0644);
     }
 #else
     fd = creat(log_filename, 0644);
 #endif
     if (fd == -1) {
         malloc_printf("<jemalloc>: creat() for log file \"%s\" "
                   " failed with %d\n", log_filename, errno);
         if (opt_abort) {
             abort();
         }
         return true;
     }
     /* Emit to json. */
     struct prof_emitter_cb_arg_s arg;
     arg.fd = fd;
     emitter_init(&emitter, emitter_output_json, &prof_emitter_write_cb,
         (void *)(&arg));
     emitter_begin(&emitter);
     prof_log_emit_metadata(&emitter);
     prof_log_emit_threads(tsd, &emitter);
     prof_log_emit_traces(tsd, &emitter);
     prof_log_emit_allocs(tsd, &emitter);
     emitter_end(&emitter);
     /* Reset global state. */
     if (log_tables_initialized) {
         ckh_delete(tsd, &log_bt_node_set);
         ckh_delete(tsd, &log_thr_node_set);
     }
     log_tables_initialized = false;
     log_bt_index = 0;
     log_thr_index = 0;
     log_bt_first = NULL;
     log_bt_last = NULL;
     log_thr_first = NULL;
     log_thr_last = NULL;
     log_alloc_first = NULL;
     log_alloc_last = NULL;
     malloc_mutex_lock(tsdn, &log_mtx);
     prof_logging_state = prof_logging_state_stopped;
     malloc_mutex_unlock(tsdn, &log_mtx);
 #ifdef JEMALLOC_JET
     if (prof_log_dummy) {
         return false;
     }
 #endif
     return close(fd);
 }
References arg(), ckh_delete, close, creat, emitter_begin(), emitter_end(), emitter_init(), emitter_output_json, errno, prof_emitter_cb_arg_s::fd, log_alloc_first, log_alloc_last, log_bt_first, log_bt_index, log_bt_last, log_bt_node_set, log_filename, log_mtx, log_tables_initialized, log_thr_first, log_thr_index, log_thr_last, log_thr_node_set, malloc_mutex_lock(), malloc_mutex_unlock(), malloc_printf, NULL, opt_abort, opt_prof, prof_booted, prof_emitter_write_cb(), prof_log_emit_allocs(), prof_log_emit_metadata(), prof_log_emit_threads(), prof_log_emit_traces(), prof_logging_state, prof_logging_state_dumping, prof_logging_state_started, prof_logging_state_stopped, and tsdn_tsd().
Referenced by prof_log_stop_final().
prof_log_stop_final()
static void prof_log_stop_final (void) static
Definition at line 2553 of file prof.c.
{
     tsd_t *tsd = tsd_fetch();
     prof_log_stop(tsd_tsdn(tsd));
 }
References prof_log_stop(), tsd_fetch(), and tsd_tsdn().
Referenced by prof_boot2().
prof_log_thr_index()
static size_t prof_log_thr_index (tsd_t * tsd, uint64_t thr_uid, const char * name) static
Definition at line 407 of file prof.c.
{
     assert(prof_logging_state == prof_logging_state_started);
     malloc_mutex_assert_owner(tsd_tsdn(tsd), &log_mtx);
     prof_thr_node_t dummy_node;
     dummy_node.thr_uid = thr_uid;
     prof_thr_node_t *node;
     /* See if this thread is already cached in the table. */
     if (ckh_search(&log_thr_node_set, (void *)(&dummy_node),
         (void **)(&node), NULL)) {
         size_t sz = offsetof(prof_thr_node_t, name) + strlen(name) + 1;
         prof_thr_node_t *new_node = (prof_thr_node_t *)
             iallocztm(tsd_tsdn(tsd), sz, sz_size2index(sz), false, NULL,
             true, arena_get(TSDN_NULL, 0, true), true);
         if (log_thr_first == NULL) {
             log_thr_first = new_node;
             log_thr_last = new_node;
         } else {
             log_thr_last->next = new_node;
             log_thr_last = new_node;
         }
         new_node->next = NULL;
         new_node->index = log_thr_index;
         new_node->thr_uid = thr_uid;
         strcpy(new_node->name, name);
         log_thr_index++;
         ckh_insert(tsd, &log_thr_node_set, (void *)new_node, NULL);
         return new_node->index;
     } else {
         return node->index;
     }
 }
References arena_get(), assert(), ckh_insert, ckh_search, iallocztm(), prof_thr_node_s::index, log_mtx, log_thr_first, log_thr_index, log_thr_last, log_thr_node_set, malloc_mutex_assert_owner(), prof_thr_node_s::name, prof_thr_node_s::next, NULL, offsetof, prof_logging_state, prof_logging_state_started, sz_size2index(), prof_thr_node_s::thr_uid, tsd_tsdn(), and TSDN_NULL.
Referenced by prof_try_log().
prof_lookup()
prof_tctx_t* prof_lookup (tsd_t * tsd, prof_bt_t * bt)
Definition at line 1053 of file prof.c.
{
     union {
         prof_tctx_t *p;
         void        *v;
     } ret;
     prof_tdata_t *tdata;
     bool not_found;
     cassert(config_prof);
     tdata = prof_tdata_get(tsd, false);
     if (tdata == NULL) {
         return NULL;
     }
     malloc_mutex_lock(tsd_tsdn(tsd), tdata->lock);
     not_found = ckh_search(&tdata->bt2tctx, bt, NULL, &ret.v);
     if (!not_found) { /* Note double negative! */
         ret.p->prepared = true;
     }
     malloc_mutex_unlock(tsd_tsdn(tsd), tdata->lock);
     if (not_found) {
         void *btkey;
         prof_gctx_t *gctx;
         bool new_gctx, error;
         /*
          * This thread's cache lacks bt.  Look for it in the global
          * cache.
          */
         if (prof_lookup_global(tsd, bt, tdata, &btkey, &gctx,
             &new_gctx)) {
             return NULL;
         }
         /* Link a prof_tctx_t into gctx for this thread. */
         ret.v = iallocztm(tsd_tsdn(tsd), sizeof(prof_tctx_t),
             sz_size2index(sizeof(prof_tctx_t)), false, NULL, true,
             arena_ichoose(tsd, NULL), true);
         if (ret.p == NULL) {
             if (new_gctx) {
                 prof_gctx_try_destroy(tsd, tdata, gctx, tdata);
             }
             return NULL;
         }
         ret.p->tdata = tdata;
         ret.p->thr_uid = tdata->thr_uid;
         ret.p->thr_discrim = tdata->thr_discrim;
         memset(&ret.p->cnts, 0, sizeof(prof_cnt_t));
         ret.p->gctx = gctx;
         ret.p->tctx_uid = tdata->tctx_uid_next++;
         ret.p->prepared = true;
         ret.p->state = prof_tctx_state_initializing;
         malloc_mutex_lock(tsd_tsdn(tsd), tdata->lock);
         error = ckh_insert(tsd, &tdata->bt2tctx, btkey, ret.v);
         malloc_mutex_unlock(tsd_tsdn(tsd), tdata->lock);
         if (error) {
             if (new_gctx) {
                 prof_gctx_try_destroy(tsd, tdata, gctx, tdata);
             }
             idalloctm(tsd_tsdn(tsd), ret.v, NULL, NULL, true, true);
             return NULL;
         }
         malloc_mutex_lock(tsd_tsdn(tsd), gctx->lock);
         ret.p->state = prof_tctx_state_nominal;
         tctx_tree_insert(&gctx->tctxs, ret.p);
         gctx->nlimbo--;
         malloc_mutex_unlock(tsd_tsdn(tsd), gctx->lock);
     }
     return ret.p;
 }
References arena_ichoose(), prof_tdata_s::bt2tctx, cassert(), ckh_insert, ckh_search, config_prof, error(), iallocztm(), idalloctm(), prof_gctx_s::lock, prof_tdata_s::lock, malloc_mutex_lock(), malloc_mutex_unlock(), memset, prof_gctx_s::nlimbo, NULL, prof_gctx_try_destroy(), prof_lookup_global(), prof_tctx_state_initializing, prof_tctx_state_nominal, prof_tdata_get(), ret, sz_size2index(), prof_tdata_s::tctx_uid_next, prof_gctx_s::tctxs, prof_tdata_s::thr_discrim, prof_tdata_s::thr_uid, and tsd_tsdn().
prof_lookup_global()
static bool prof_lookup_global (tsd_t * tsd, prof_bt_t * bt, prof_tdata_t * tdata, void ** p_btkey, prof_gctx_t ** p_gctx, bool * p_new_gctx) static
Definition at line 988 of file prof.c.
{
     union {
         prof_gctx_t *p;
         void        *v;
     } gctx, tgctx;
     union {
         prof_bt_t   *p;
         void        *v;
     } btkey;
     bool new_gctx;
     prof_enter(tsd, tdata);
     if (ckh_search(&bt2gctx, bt, &btkey.v, &gctx.v)) {
         /* bt has never been seen before.  Insert it. */
         prof_leave(tsd, tdata);
         tgctx.p = prof_gctx_create(tsd_tsdn(tsd), bt);
         if (tgctx.v == NULL) {
             return true;
         }
         prof_enter(tsd, tdata);
         if (ckh_search(&bt2gctx, bt, &btkey.v, &gctx.v)) {
             gctx.p = tgctx.p;
             btkey.p = &gctx.p->bt;
             if (ckh_insert(tsd, &bt2gctx, btkey.v, gctx.v)) {
                 /* OOM. */
                 prof_leave(tsd, tdata);
                 idalloctm(tsd_tsdn(tsd), gctx.v, NULL, NULL,
                     true, true);
                 return true;
             }
             new_gctx = true;
         } else {
             new_gctx = false;
         }
     } else {
         tgctx.v = NULL;
         new_gctx = false;
     }
     if (!new_gctx) {
         /*
          * Increment nlimbo, in order to avoid a race condition with
          * prof_tctx_destroy()/prof_gctx_try_destroy().
          */
         malloc_mutex_lock(tsd_tsdn(tsd), gctx.p->lock);
         gctx.p->nlimbo++;
         malloc_mutex_unlock(tsd_tsdn(tsd), gctx.p->lock);
         new_gctx = false;
         if (tgctx.v != NULL) {
             /* Lost race to insert. */
             idalloctm(tsd_tsdn(tsd), tgctx.v, NULL, NULL, true,
                 true);
         }
     }
     prof_leave(tsd, tdata);
     *p_btkey = btkey.v;
     *p_gctx = gctx.p;
     *p_new_gctx = new_gctx;
     return false;
 }
References bt2gctx, ckh_insert, ckh_search, idalloctm(), malloc_mutex_lock(), malloc_mutex_unlock(), NULL, prof_enter(), prof_gctx_create(), prof_leave(), and tsd_tsdn().
Referenced by prof_lookup().
prof_malloc_sample_object()
void prof_malloc_sample_object (tsdn_t * tsdn, const void * ptr, size_t usize, prof_tctx_t * tctx)
Definition at line 343 of file prof.c.
{
     prof_tctx_set(tsdn, ptr, usize, NULL, tctx);
     /* Get the current time and set this in the extent_t. We'll read this
      * when free() is called. */
     nstime_t t = NSTIME_ZERO_INITIALIZER;
     nstime_update(&t);
     prof_alloc_time_set(tsdn, ptr, NULL, t);
     malloc_mutex_lock(tsdn, tctx->tdata->lock);
     tctx->cnts.curobjs++;
     tctx->cnts.curbytes += usize;
     if (opt_prof_accum) {
         tctx->cnts.accumobjs++;
         tctx->cnts.accumbytes += usize;
     }
     tctx->prepared = false;
     malloc_mutex_unlock(tsdn, tctx->tdata->lock);
 }
References prof_cnt_s::accumbytes, prof_cnt_s::accumobjs, prof_tctx_s::cnts, prof_cnt_s::curbytes, prof_cnt_s::curobjs, prof_tdata_s::lock, malloc_mutex_lock(), malloc_mutex_unlock(), nstime_update, NSTIME_ZERO_INITIALIZER, NULL, opt_prof_accum, prof_tctx_s::prepared, prof_alloc_time_set(), prof_tctx_set(), ptr(), tctx, and prof_tctx_s::tdata.
prof_mdump()
bool prof_mdump (tsd_t * tsd, const char * filename)
Definition at line 2083 of file prof.c.
{
     cassert(config_prof);
     assert(tsd_reentrancy_level_get(tsd) == 0);
     if (!opt_prof || !prof_booted) {
         return true;
     }
     char filename_buf[DUMP_FILENAME_BUFSIZE];
     if (filename == NULL) {
         /* No filename specified, so automatically generate one. */
         if (opt_prof_prefix[0] == '\0') {
             return true;
         }
         malloc_mutex_lock(tsd_tsdn(tsd), &prof_dump_seq_mtx);
         prof_dump_filename(filename_buf, 'm', prof_dump_mseq);
         prof_dump_mseq++;
         malloc_mutex_unlock(tsd_tsdn(tsd), &prof_dump_seq_mtx);
         filename = filename_buf;
     }
     return prof_dump(tsd, true, filename, false);
 }
References assert(), cassert(), config_prof, DUMP_FILENAME_BUFSIZE, malloc_mutex_lock(), malloc_mutex_unlock(), NULL, opt_prof, opt_prof_prefix, prof_booted, prof_dump(), prof_dump_filename(), prof_dump_mseq, prof_dump_seq_mtx, and tsd_tsdn().
prof_open_maps()
static int prof_open_maps (const char * format, ...) static
Definition at line 1675 of file prof.c.
{
     int mfd;
     va_list ap;
     char filename[PATH_MAX + 1];
     va_start(ap, format);
     malloc_vsnprintf(filename, sizeof(filename), format, ap);
     va_end(ap);
 #if defined(O_CLOEXEC)
     mfd = open(filename, O_RDONLY | O_CLOEXEC);
 #else
     mfd = open(filename, O_RDONLY);
     if (mfd != -1) {
         fcntl(mfd, F_SETFD, fcntl(mfd, F_GETFD) | FD_CLOEXEC);
     }
 #endif
     return mfd;
 }
References format(), malloc_vsnprintf, and open.
Referenced by prof_dump_maps().
prof_postfork_child()
void prof_postfork_child (tsdn_t * tsdn)
Definition at line 3139 of file prof.c.
{
     if (config_prof && opt_prof) {
         unsigned i;
         malloc_mutex_postfork_child(tsdn, &prof_thread_active_init_mtx);
         malloc_mutex_postfork_child(tsdn, &next_thr_uid_mtx);
         malloc_mutex_postfork_child(tsdn, &prof_gdump_mtx);
         malloc_mutex_postfork_child(tsdn, &prof_dump_seq_mtx);
         malloc_mutex_postfork_child(tsdn, &prof_active_mtx);
         for (i = 0; i < PROF_NCTX_LOCKS; i++) {
             malloc_mutex_postfork_child(tsdn, &gctx_locks[i]);
         }
         for (i = 0; i < PROF_NTDATA_LOCKS; i++) {
             malloc_mutex_postfork_child(tsdn, &tdata_locks[i]);
         }
         malloc_mutex_postfork_child(tsdn, &tdatas_mtx);
         malloc_mutex_postfork_child(tsdn, &bt2gctx_mtx);
         malloc_mutex_postfork_child(tsdn, &prof_dump_mtx);
     }
 }
References bt2gctx_mtx, config_prof, gctx_locks, malloc_mutex_postfork_child, next_thr_uid_mtx, opt_prof, prof_active_mtx, prof_dump_mtx, prof_dump_seq_mtx, prof_gdump_mtx, PROF_NCTX_LOCKS, PROF_NTDATA_LOCKS, prof_thread_active_init_mtx, tdata_locks, and tdatas_mtx.
prof_postfork_parent()
void prof_postfork_parent (tsdn_t * tsdn)
Definition at line 3116 of file prof.c.
{
     if (config_prof && opt_prof) {
         unsigned i;
         malloc_mutex_postfork_parent(tsdn,
             &prof_thread_active_init_mtx);
         malloc_mutex_postfork_parent(tsdn, &next_thr_uid_mtx);
         malloc_mutex_postfork_parent(tsdn, &prof_gdump_mtx);
         malloc_mutex_postfork_parent(tsdn, &prof_dump_seq_mtx);
         malloc_mutex_postfork_parent(tsdn, &prof_active_mtx);
         for (i = 0; i < PROF_NCTX_LOCKS; i++) {
             malloc_mutex_postfork_parent(tsdn, &gctx_locks[i]);
         }
         for (i = 0; i < PROF_NTDATA_LOCKS; i++) {
             malloc_mutex_postfork_parent(tsdn, &tdata_locks[i]);
         }
         malloc_mutex_postfork_parent(tsdn, &tdatas_mtx);
         malloc_mutex_postfork_parent(tsdn, &bt2gctx_mtx);
         malloc_mutex_postfork_parent(tsdn, &prof_dump_mtx);
     }
 }
References bt2gctx_mtx, config_prof, gctx_locks, malloc_mutex_postfork_parent, next_thr_uid_mtx, opt_prof, prof_active_mtx, prof_dump_mtx, prof_dump_seq_mtx, prof_gdump_mtx, PROF_NCTX_LOCKS, PROF_NTDATA_LOCKS, prof_thread_active_init_mtx, tdata_locks, and tdatas_mtx.
prof_prefork0()
void prof_prefork0 (tsdn_t * tsdn)
Definition at line 3088 of file prof.c.
{
     if (config_prof && opt_prof) {
         unsigned i;
         malloc_mutex_prefork(tsdn, &prof_dump_mtx);
         malloc_mutex_prefork(tsdn, &bt2gctx_mtx);
         malloc_mutex_prefork(tsdn, &tdatas_mtx);
         for (i = 0; i < PROF_NTDATA_LOCKS; i++) {
             malloc_mutex_prefork(tsdn, &tdata_locks[i]);
         }
         for (i = 0; i < PROF_NCTX_LOCKS; i++) {
             malloc_mutex_prefork(tsdn, &gctx_locks[i]);
         }
     }
 }
References bt2gctx_mtx, config_prof, gctx_locks, malloc_mutex_prefork, opt_prof, prof_dump_mtx, PROF_NCTX_LOCKS, PROF_NTDATA_LOCKS, tdata_locks, and tdatas_mtx.
prof_prefork1()
void prof_prefork1 (tsdn_t * tsdn)
Definition at line 3105 of file prof.c.
{
     if (config_prof && opt_prof) {
         malloc_mutex_prefork(tsdn, &prof_active_mtx);
         malloc_mutex_prefork(tsdn, &prof_dump_seq_mtx);
         malloc_mutex_prefork(tsdn, &prof_gdump_mtx);
         malloc_mutex_prefork(tsdn, &next_thr_uid_mtx);
         malloc_mutex_prefork(tsdn, &prof_thread_active_init_mtx);
     }
 }
References config_prof, malloc_mutex_prefork, next_thr_uid_mtx, opt_prof, prof_active_mtx, prof_dump_seq_mtx, prof_gdump_mtx, and prof_thread_active_init_mtx.
prof_reset()
void prof_reset (tsd_t * tsd, size_t lg_sample)
Definition at line 2359 of file prof.c.
{
     prof_tdata_t *next;
     assert(lg_sample < (sizeof(uint64_t) << 3));
     malloc_mutex_lock(tsd_tsdn(tsd), &prof_dump_mtx);
     malloc_mutex_lock(tsd_tsdn(tsd), &tdatas_mtx);
     lg_prof_sample = lg_sample;
     next = NULL;
     do {
         prof_tdata_t *to_destroy = tdata_tree_iter(&tdatas, next,
             prof_tdata_reset_iter, (void *)tsd);
         if (to_destroy != NULL) {
             next = tdata_tree_next(&tdatas, to_destroy);
             prof_tdata_destroy_locked(tsd, to_destroy, false);
         } else {
             next = NULL;
         }
     } while (next != NULL);
     malloc_mutex_unlock(tsd_tsdn(tsd), &tdatas_mtx);
     malloc_mutex_unlock(tsd_tsdn(tsd), &prof_dump_mtx);
 }
References assert(), lg_prof_sample, malloc_mutex_lock(), malloc_mutex_unlock(), next(), NULL, prof_dump_mtx, prof_tdata_destroy_locked(), prof_tdata_reset_iter(), tdatas, tdatas_mtx, and tsd_tsdn().
prof_sample_threshold_update()
void prof_sample_threshold_update (prof_tdata_t * tdata)
Definition at line 1140 of file prof.c.
{
 #ifdef JEMALLOC_PROF
     if (!config_prof) {
         return;
     }
     if (lg_prof_sample == 0) {
         tsd_bytes_until_sample_set(tsd_fetch(), 0);
         return;
     }
     /*
      * Compute sample interval as a geometrically distributed random
      * variable with mean (2^lg_prof_sample).
      *
      *                             __        __
      *                             |  log(u)  |                     1
      * tdata->bytes_until_sample = | -------- |, where p = ---------------
      *                             | log(1-p) |             lg_prof_sample
      *                                                     2
      *
      * For more information on the math, see:
      *
      *   Non-Uniform Random Variate Generation
      *   Luc Devroye
      *   Springer-Verlag, New York, 1986
      *   pp 500
      *   (http://luc.devroye.org/rnbookindex.html)
      */
     uint64_t r = prng_lg_range_u64(&tdata->prng_state, 53);
     double u = (double)r * (1.0/9007199254740992.0L);
     uint64_t bytes_until_sample = (uint64_t)(log(u) /
         log(1.0 - (1.0 / (double)((uint64_t)1U << lg_prof_sample))))
         + (uint64_t)1U;
     if (bytes_until_sample > SSIZE_MAX) {
         bytes_until_sample = SSIZE_MAX;
     }
     tsd_bytes_until_sample_set(tsd_fetch(), bytes_until_sample);
 #endif
 }
References config_prof, lg_prof_sample, G3D::log(), prng_lg_range_u64(), prof_tdata_s::prng_state, SSIZE_MAX, and tsd_fetch().
Referenced by if(), and prof_tdata_init_impl().
prof_tctx_comp()
static int prof_tctx_comp (const prof_tctx_t * a, const prof_tctx_t * b) static
Definition at line 254 of file prof.c.
{
     uint64_t a_thr_uid = a->thr_uid;
     uint64_t b_thr_uid = b->thr_uid;
     int ret = (a_thr_uid > b_thr_uid) - (a_thr_uid < b_thr_uid);
     if (ret == 0) {
         uint64_t a_thr_discrim = a->thr_discrim;
         uint64_t b_thr_discrim = b->thr_discrim;
         ret = (a_thr_discrim > b_thr_discrim) - (a_thr_discrim <
             b_thr_discrim);
         if (ret == 0) {
             uint64_t a_tctx_uid = a->tctx_uid;
             uint64_t b_tctx_uid = b->tctx_uid;
             ret = (a_tctx_uid > b_tctx_uid) - (a_tctx_uid <
                 b_tctx_uid);
         }
     }
     return ret;
 }
References mpq::a, b, and ret.
prof_tctx_destroy()
static void prof_tctx_destroy (tsd_t * tsd, prof_tctx_t * tctx) static
Definition at line 912 of file prof.c.
{
     prof_tdata_t *tdata = tctx->tdata;
     prof_gctx_t *gctx = tctx->gctx;
     bool destroy_tdata, destroy_tctx, destroy_gctx;
     malloc_mutex_assert_owner(tsd_tsdn(tsd), tctx->tdata->lock);
     assert(tctx->cnts.curobjs == 0);
     assert(tctx->cnts.curbytes == 0);
     assert(!opt_prof_accum);
     assert(tctx->cnts.accumobjs == 0);
     assert(tctx->cnts.accumbytes == 0);
     ckh_remove(tsd, &tdata->bt2tctx, &gctx->bt, NULL, NULL);
     destroy_tdata = prof_tdata_should_destroy(tsd_tsdn(tsd), tdata, false);
     malloc_mutex_unlock(tsd_tsdn(tsd), tdata->lock);
     malloc_mutex_lock(tsd_tsdn(tsd), gctx->lock);
     switch (tctx->state) {
     case prof_tctx_state_nominal:
         tctx_tree_remove(&gctx->tctxs, tctx);
         destroy_tctx = true;
         if (prof_gctx_should_destroy(gctx)) {
             /*
              * Increment gctx->nlimbo in order to keep another
              * thread from winning the race to destroy gctx while
              * this one has gctx->lock dropped.  Without this, it
              * would be possible for another thread to:
              *
              * 1) Sample an allocation associated with gctx.
              * 2) Deallocate the sampled object.
              * 3) Successfully prof_gctx_try_destroy(gctx).
              *
              * The result would be that gctx no longer exists by the
              * time this thread accesses it in
              * prof_gctx_try_destroy().
              */
             gctx->nlimbo++;
             destroy_gctx = true;
         } else {
             destroy_gctx = false;
         }
         break;
     case prof_tctx_state_dumping:
         /*
          * A dumping thread needs tctx to remain valid until dumping
          * has finished.  Change state such that the dumping thread will
          * complete destruction during a late dump iteration phase.
          */
         tctx->state = prof_tctx_state_purgatory;
         destroy_tctx = false;
         destroy_gctx = false;
         break;
     default:
         not_reached();
         destroy_tctx = false;
         destroy_gctx = false;
     }
     malloc_mutex_unlock(tsd_tsdn(tsd), gctx->lock);
     if (destroy_gctx) {
         prof_gctx_try_destroy(tsd, prof_tdata_get(tsd, false), gctx,
             tdata);
     }
     malloc_mutex_assert_not_owner(tsd_tsdn(tsd), tctx->tdata->lock);
     if (destroy_tdata) {
         prof_tdata_destroy(tsd, tdata, false);
     }
     if (destroy_tctx) {
         idalloctm(tsd_tsdn(tsd), tctx, NULL, NULL, true, true);
     }
 }
References prof_cnt_s::accumbytes, prof_cnt_s::accumobjs, assert(), prof_gctx_s::bt, prof_tdata_s::bt2tctx, ckh_remove, prof_tctx_s::cnts, prof_cnt_s::curbytes, prof_cnt_s::curobjs, prof_tctx_s::gctx, idalloctm(), prof_gctx_s::lock, prof_tdata_s::lock, malloc_mutex_assert_not_owner(), malloc_mutex_assert_owner(), malloc_mutex_lock(), malloc_mutex_unlock(), prof_gctx_s::nlimbo, not_reached, NULL, opt_prof_accum, prof_gctx_should_destroy(), prof_gctx_try_destroy(), prof_tctx_state_dumping, prof_tctx_state_nominal, prof_tctx_state_purgatory, prof_tdata_destroy(), prof_tdata_get(), prof_tdata_should_destroy(), prof_tctx_s::state, tctx, prof_gctx_s::tctxs, prof_tctx_s::tdata, and tsd_tsdn().
Referenced by if(), and prof_free_sampled_object().
prof_tctx_dump_iter()
static prof_tctx_t* prof_tctx_dump_iter (prof_tctx_tree_t * tctxs, prof_tctx_t * tctx, void * opaque) static
Definition at line 1396 of file prof.c.
{
     struct prof_tctx_dump_iter_arg_s *arg =
         (struct prof_tctx_dump_iter_arg_s *)opaque;
     malloc_mutex_assert_owner(arg->tsdn, tctx->gctx->lock);
     switch (tctx->state) {
     case prof_tctx_state_initializing:
     case prof_tctx_state_nominal:
         /* Not captured by this dump. */
         break;
     case prof_tctx_state_dumping:
     case prof_tctx_state_purgatory:
         if (prof_dump_printf(arg->propagate_err,
             "  t%"FMTu64": %"FMTu64": %"FMTu64" [%"FMTu64": "
             "%"FMTu64"]\n", tctx->thr_uid, tctx->dump_cnts.curobjs,
             tctx->dump_cnts.curbytes, tctx->dump_cnts.accumobjs,
             tctx->dump_cnts.accumbytes)) {
             return tctx;
         }
         break;
     default:
         not_reached();
     }
     return NULL;
 }
References prof_cnt_s::accumbytes, prof_cnt_s::accumobjs, arg(), prof_cnt_s::curbytes, prof_cnt_s::curobjs, prof_tctx_s::dump_cnts, FMTu64, prof_tctx_s::gctx, prof_gctx_s::lock, malloc_mutex_assert_owner(), not_reached, NULL, prof_dump_printf(), prof_tctx_state_dumping, prof_tctx_state_initializing, prof_tctx_state_nominal, prof_tctx_state_purgatory, prof_tctx_s::state, tctx, and prof_tctx_s::thr_uid.
Referenced by prof_dump_gctx().
prof_tctx_finish_iter()
static prof_tctx_t* prof_tctx_finish_iter (prof_tctx_tree_t * tctxs, prof_tctx_t * tctx, void * arg) static
Definition at line 1424 of file prof.c.
{
     tsdn_t *tsdn = (tsdn_t *)arg;
     prof_tctx_t *ret;
     malloc_mutex_assert_owner(tsdn, tctx->gctx->lock);
     switch (tctx->state) {
     case prof_tctx_state_nominal:
         /* New since dumping started; ignore. */
         break;
     case prof_tctx_state_dumping:
         tctx->state = prof_tctx_state_nominal;
         break;
     case prof_tctx_state_purgatory:
         ret = tctx;
         goto label_return;
     default:
         not_reached();
     }
     ret = NULL;
 label_return:
     return ret;
 }
References arg(), prof_tctx_s::gctx, prof_gctx_s::lock, malloc_mutex_assert_owner(), not_reached, NULL, prof_tctx_state_dumping, prof_tctx_state_nominal, prof_tctx_state_purgatory, ret, prof_tctx_s::state, tctx, and prof_tctx_dump_iter_arg_s::tsdn.
Referenced by prof_gctx_finish().
prof_tctx_merge_gctx()
static void prof_tctx_merge_gctx (tsdn_t * tsdn, prof_tctx_t * tctx, prof_gctx_t * gctx) static
Definition at line 1358 of file prof.c.
{
     malloc_mutex_assert_owner(tsdn, gctx->lock);
     gctx->cnt_summed.curobjs += tctx->dump_cnts.curobjs;
     gctx->cnt_summed.curbytes += tctx->dump_cnts.curbytes;
     if (opt_prof_accum) {
         gctx->cnt_summed.accumobjs += tctx->dump_cnts.accumobjs;
         gctx->cnt_summed.accumbytes += tctx->dump_cnts.accumbytes;
     }
 }
References prof_cnt_s::accumbytes, prof_cnt_s::accumobjs, prof_gctx_s::cnt_summed, prof_cnt_s::curbytes, prof_cnt_s::curobjs, prof_tctx_s::dump_cnts, prof_gctx_s::lock, malloc_mutex_assert_owner(), opt_prof_accum, and tctx.
Referenced by prof_tctx_merge_iter().
prof_tctx_merge_iter()
static prof_tctx_t* prof_tctx_merge_iter (prof_tctx_tree_t * tctxs, prof_tctx_t * tctx, void * arg) static
Definition at line 1370 of file prof.c.
{
     tsdn_t *tsdn = (tsdn_t *)arg;
     malloc_mutex_assert_owner(tsdn, tctx->gctx->lock);
     switch (tctx->state) {
     case prof_tctx_state_nominal:
         /* New since dumping started; ignore. */
         break;
     case prof_tctx_state_dumping:
     case prof_tctx_state_purgatory:
         prof_tctx_merge_gctx(tsdn, tctx, tctx->gctx);
         break;
     default:
         not_reached();
     }
     return NULL;
 }
References arg(), prof_tctx_s::gctx, prof_gctx_s::lock, malloc_mutex_assert_owner(), not_reached, NULL, prof_tctx_merge_gctx(), prof_tctx_state_dumping, prof_tctx_state_nominal, prof_tctx_state_purgatory, prof_tctx_s::state, and tctx.
Referenced by prof_gctx_merge_iter().
prof_tctx_merge_tdata()
static void prof_tctx_merge_tdata (tsdn_t * tsdn, prof_tctx_t * tctx, prof_tdata_t * tdata) static
Definition at line 1327 of file prof.c.
{
     malloc_mutex_assert_owner(tsdn, tctx->tdata->lock);
     malloc_mutex_lock(tsdn, tctx->gctx->lock);
     switch (tctx->state) {
     case prof_tctx_state_initializing:
         malloc_mutex_unlock(tsdn, tctx->gctx->lock);
         return;
     case prof_tctx_state_nominal:
         tctx->state = prof_tctx_state_dumping;
         malloc_mutex_unlock(tsdn, tctx->gctx->lock);
         memcpy(&tctx->dump_cnts, &tctx->cnts, sizeof(prof_cnt_t));
         tdata->cnt_summed.curobjs += tctx->dump_cnts.curobjs;
         tdata->cnt_summed.curbytes += tctx->dump_cnts.curbytes;
         if (opt_prof_accum) {
             tdata->cnt_summed.accumobjs +=
                 tctx->dump_cnts.accumobjs;
             tdata->cnt_summed.accumbytes +=
                 tctx->dump_cnts.accumbytes;
         }
         break;
     case prof_tctx_state_dumping:
     case prof_tctx_state_purgatory:
         not_reached();
     }
 }
References prof_cnt_s::accumbytes, prof_cnt_s::accumobjs, prof_tdata_s::cnt_summed, prof_tctx_s::cnts, prof_cnt_s::curbytes, prof_cnt_s::curobjs, prof_tctx_s::dump_cnts, prof_tctx_s::gctx, prof_gctx_s::lock, prof_tdata_s::lock, malloc_mutex_assert_owner(), malloc_mutex_lock(), malloc_mutex_unlock(), memcpy, not_reached, opt_prof_accum, prof_tctx_state_dumping, prof_tctx_state_initializing, prof_tctx_state_nominal, prof_tctx_state_purgatory, prof_tctx_s::state, tctx, and prof_tctx_s::tdata.
Referenced by prof_tdata_merge_iter().
prof_tctx_should_destroy()
static bool prof_tctx_should_destroy (tsdn_t * tsdn, prof_tctx_t * tctx) static
Definition at line 882 of file prof.c.
{
     malloc_mutex_assert_owner(tsdn, tctx->tdata->lock);
     if (opt_prof_accum) {
         return false;
     }
     if (tctx->cnts.curobjs != 0) {
         return false;
     }
     if (tctx->prepared) {
         return false;
     }
     return true;
 }
References prof_tctx_s::cnts, prof_cnt_s::curobjs, prof_tdata_s::lock, malloc_mutex_assert_owner(), opt_prof_accum, prof_tctx_s::prepared, tctx, and prof_tctx_s::tdata.
Referenced by if(), and prof_free_sampled_object().
prof_tdata_cleanup()
void prof_tdata_cleanup (tsd_t * tsd)
Definition at line 2386 of file prof.c.
{
     prof_tdata_t *tdata;
     if (!config_prof) {
         return;
     }
     tdata = tsd_prof_tdata_get(tsd);
     if (tdata != NULL) {
         prof_tdata_detach(tsd, tdata);
     }
 }
References config_prof, NULL, and prof_tdata_detach().
prof_tdata_destroy()
static void prof_tdata_destroy (tsd_t * tsd, prof_tdata_t * tdata, bool even_if_attached) static
Definition at line 2289 of file prof.c.
{
     malloc_mutex_lock(tsd_tsdn(tsd), &tdatas_mtx);
     prof_tdata_destroy_locked(tsd, tdata, even_if_attached);
     malloc_mutex_unlock(tsd_tsdn(tsd), &tdatas_mtx);
 }
References malloc_mutex_lock(), malloc_mutex_unlock(), prof_tdata_destroy_locked(), tdatas_mtx, and tsd_tsdn().
Referenced by prof_tctx_destroy(), and prof_tdata_detach().
prof_tdata_destroy_locked()
static void prof_tdata_destroy_locked (tsd_t * tsd, prof_tdata_t * tdata, bool even_if_attached) static
Definition at line 2272 of file prof.c.
{
     malloc_mutex_assert_owner(tsd_tsdn(tsd), &tdatas_mtx);
     tdata_tree_remove(&tdatas, tdata);
     assert(prof_tdata_should_destroy_unlocked(tdata, even_if_attached));
     if (tdata->thread_name != NULL) {
         idalloctm(tsd_tsdn(tsd), tdata->thread_name, NULL, NULL, true,
             true);
     }
     ckh_delete(tsd, &tdata->bt2tctx);
     idalloctm(tsd_tsdn(tsd), tdata, NULL, NULL, true, true);
 }
References assert(), prof_tdata_s::bt2tctx, ckh_delete, idalloctm(), malloc_mutex_assert_owner(), NULL, prof_tdata_should_destroy_unlocked(), tdatas, tdatas_mtx, prof_tdata_s::thread_name, and tsd_tsdn().
Referenced by prof_reset(), and prof_tdata_destroy().
prof_tdata_detach()
static void prof_tdata_detach (tsd_t * tsd, prof_tdata_t * tdata) static
Definition at line 2296 of file prof.c.
{
     bool destroy_tdata;
     malloc_mutex_lock(tsd_tsdn(tsd), tdata->lock);
     if (tdata->attached) {
         destroy_tdata = prof_tdata_should_destroy(tsd_tsdn(tsd), tdata,
             true);
         /*
          * Only detach if !destroy_tdata, because detaching would allow
          * another thread to win the race to destroy tdata.
          */
         if (!destroy_tdata) {
             tdata->attached = false;
         }
         tsd_prof_tdata_set(tsd, NULL);
     } else {
         destroy_tdata = false;
     }
     malloc_mutex_unlock(tsd_tsdn(tsd), tdata->lock);
     if (destroy_tdata) {
         prof_tdata_destroy(tsd, tdata, true);
     }
 }
References prof_tdata_s::attached, prof_tdata_s::lock, malloc_mutex_lock(), malloc_mutex_unlock(), NULL, prof_tdata_destroy(), prof_tdata_should_destroy(), and tsd_tsdn().
Referenced by prof_tdata_cleanup(), and prof_tdata_reinit().
prof_tdata_dump_iter()
static prof_tdata_t* prof_tdata_dump_iter (prof_tdata_tree_t * tdatas, prof_tdata_t * tdata, void * arg) static
Definition at line 1576 of file prof.c.
                {
     bool propagate_err = *(bool *)arg;
     if (!tdata->dumping) {
         return NULL;
     }
     if (prof_dump_printf(propagate_err,
         "  t%"FMTu64": %"FMTu64": %"FMTu64" [%"FMTu64": %"FMTu64"]%s%s\n",
         tdata->thr_uid, tdata->cnt_summed.curobjs,
         tdata->cnt_summed.curbytes, tdata->cnt_summed.accumobjs,
         tdata->cnt_summed.accumbytes,
         (tdata->thread_name != NULL) ? " " : "",
         (tdata->thread_name != NULL) ? tdata->thread_name : "")) {
         return tdata;
     }
     return NULL;
 }
References prof_cnt_s::accumbytes, prof_cnt_s::accumobjs, arg(), prof_tdata_s::cnt_summed, prof_cnt_s::curbytes, prof_cnt_s::curobjs, prof_tdata_s::dumping, FMTu64, NULL, prof_dump_printf(), prof_tdata_s::thr_uid, and prof_tdata_s::thread_name.
Referenced by prof_dump_header_impl().
prof_tdata_expire()
static bool prof_tdata_expire (tsdn_t * tsdn, prof_tdata_t * tdata) static
Definition at line 2334 of file prof.c.
{
     bool destroy_tdata;
     malloc_mutex_lock(tsdn, tdata->lock);
     if (!tdata->expired) {
         tdata->expired = true;
         destroy_tdata = tdata->attached ? false :
             prof_tdata_should_destroy(tsdn, tdata, false);
     } else {
         destroy_tdata = false;
     }
     malloc_mutex_unlock(tsdn, tdata->lock);
     return destroy_tdata;
 }
References prof_tdata_s::attached, prof_tdata_s::expired, false, prof_tdata_s::lock, malloc_mutex_lock(), malloc_mutex_unlock(), prof_tdata_should_destroy(), and prof_gctx_merge_iter_arg_s::tsdn.
Referenced by prof_tdata_reset_iter().
prof_tdata_init()
prof_tdata_t* prof_tdata_init (tsd_t * tsd)
Definition at line 2247 of file prof.c.
{
     return prof_tdata_init_impl(tsd, prof_thr_uid_alloc(tsd_tsdn(tsd)), 0,
         NULL, prof_thread_active_init_get(tsd_tsdn(tsd)));
 }
References NULL, prof_tdata_init_impl(), prof_thr_uid_alloc(), prof_thread_active_init_get(), and tsd_tsdn().
prof_tdata_init_impl()
static prof_tdata_t* prof_tdata_init_impl (tsd_t * tsd, uint64_t thr_uid, uint64_t thr_discrim, char * thread_name, bool active) static
Definition at line 2201 of file prof.c.
{
     prof_tdata_t *tdata;
     cassert(config_prof);
     /* Initialize an empty cache for this thread. */
     tdata = (prof_tdata_t *)iallocztm(tsd_tsdn(tsd), sizeof(prof_tdata_t),
         sz_size2index(sizeof(prof_tdata_t)), false, NULL, true,
         arena_get(TSDN_NULL, 0, true), true);
     if (tdata == NULL) {
         return NULL;
     }
     tdata->lock = prof_tdata_mutex_choose(thr_uid);
     tdata->thr_uid = thr_uid;
     tdata->thr_discrim = thr_discrim;
     tdata->thread_name = thread_name;
     tdata->attached = true;
     tdata->expired = false;
     tdata->tctx_uid_next = 0;
     if (ckh_new(tsd, &tdata->bt2tctx, PROF_CKH_MINITEMS, prof_bt_hash,
         prof_bt_keycomp)) {
         idalloctm(tsd_tsdn(tsd), tdata, NULL, NULL, true, true);
         return NULL;
     }
     tdata->prng_state = (uint64_t)(uintptr_t)tdata;
     prof_sample_threshold_update(tdata);
     tdata->enq = false;
     tdata->enq_idump = false;
     tdata->enq_gdump = false;
     tdata->dumping = false;
     tdata->active = active;
     malloc_mutex_lock(tsd_tsdn(tsd), &tdatas_mtx);
     tdata_tree_insert(&tdatas, tdata);
     malloc_mutex_unlock(tsd_tsdn(tsd), &tdatas_mtx);
     return tdata;
 }
References prof_tdata_s::active, arena_get(), prof_tdata_s::attached, prof_tdata_s::bt2tctx, cassert(), ckh_new, config_prof, prof_tdata_s::dumping, prof_tdata_s::enq, prof_tdata_s::enq_gdump, prof_tdata_s::enq_idump, prof_tdata_s::expired, iallocztm(), idalloctm(), prof_tdata_s::lock, malloc_mutex_lock(), malloc_mutex_unlock(), NULL, prof_tdata_s::prng_state, prof_bt_hash(), prof_bt_keycomp(), PROF_CKH_MINITEMS, prof_sample_threshold_update(), prof_tdata_mutex_choose(), sz_size2index(), prof_tdata_s::tctx_uid_next, tdatas, tdatas_mtx, prof_tdata_s::thr_discrim, prof_tdata_s::thr_uid, prof_tdata_s::thread_name, tsd_tsdn(), and TSDN_NULL.
Referenced by prof_tdata_init(), and prof_tdata_reinit().
prof_tdata_merge_iter()
static prof_tdata_t* prof_tdata_merge_iter (prof_tdata_tree_t * tdatas, prof_tdata_t * tdata, void * opaque) static
Definition at line 1541 of file prof.c.
                   {
     struct prof_tdata_merge_iter_arg_s *arg =
         (struct prof_tdata_merge_iter_arg_s *)opaque;
     malloc_mutex_lock(arg->tsdn, tdata->lock);
     if (!tdata->expired) {
         size_t tabind;
         union {
             prof_tctx_t *p;
             void        *v;
         } tctx;
         tdata->dumping = true;
         memset(&tdata->cnt_summed, 0, sizeof(prof_cnt_t));
         for (tabind = 0; !ckh_iter(&tdata->bt2tctx, &tabind, NULL,
             &tctx.v);) {
             prof_tctx_merge_tdata(arg->tsdn, tctx.p, tdata);
         }
         arg->cnt_all.curobjs += tdata->cnt_summed.curobjs;
         arg->cnt_all.curbytes += tdata->cnt_summed.curbytes;
         if (opt_prof_accum) {
             arg->cnt_all.accumobjs += tdata->cnt_summed.accumobjs;
             arg->cnt_all.accumbytes += tdata->cnt_summed.accumbytes;
         }
     } else {
         tdata->dumping = false;
     }
     malloc_mutex_unlock(arg->tsdn, tdata->lock);
     return NULL;
 }
References prof_cnt_s::accumbytes, prof_cnt_s::accumobjs, arg(), prof_tdata_s::bt2tctx, ckh_iter, prof_tdata_s::cnt_summed, prof_cnt_s::curbytes, prof_cnt_s::curobjs, prof_tdata_s::dumping, prof_tdata_s::expired, prof_tdata_s::lock, malloc_mutex_lock(), malloc_mutex_unlock(), memset, NULL, opt_prof_accum, prof_tctx_merge_tdata(), and tctx.
Referenced by prof_dump_prep().
prof_tdata_mutex_choose()
static malloc_mutex_t* prof_tdata_mutex_choose (uint64_t thr_uid) static
Definition at line 816 of file prof.c.
{
     return &tdata_locks[thr_uid % PROF_NTDATA_LOCKS];
 }
References PROF_NTDATA_LOCKS, and tdata_locks.
Referenced by prof_tdata_init_impl().
prof_tdata_reinit()
prof_tdata_t* prof_tdata_reinit (tsd_t * tsd, prof_tdata_t * tdata)
Definition at line 2321 of file prof.c.
{
     uint64_t thr_uid = tdata->thr_uid;
     uint64_t thr_discrim = tdata->thr_discrim + 1;
     char *thread_name = (tdata->thread_name != NULL) ?
         prof_thread_name_alloc(tsd_tsdn(tsd), tdata->thread_name) : NULL;
     bool active = tdata->active;
     prof_tdata_detach(tsd, tdata);
     return prof_tdata_init_impl(tsd, thr_uid, thr_discrim, thread_name,
         active);
 }
References prof_tdata_s::active, NULL, prof_tdata_detach(), prof_tdata_init_impl(), prof_thread_name_alloc(), prof_tdata_s::thr_discrim, prof_tdata_s::thr_uid, prof_tdata_s::thread_name, and tsd_tsdn().
prof_tdata_reset_iter()
static prof_tdata_t* prof_tdata_reset_iter (prof_tdata_tree_t * tdatas, prof_tdata_t * tdata, void * arg) static
Definition at line 2351 of file prof.c.
                {
     tsdn_t *tsdn = (tsdn_t *)arg;
     return (prof_tdata_expire(tsdn, tdata) ? tdata : NULL);
 }
References arg(), NULL, prof_tdata_expire(), and prof_gctx_merge_iter_arg_s::tsdn.
Referenced by prof_reset().
prof_tdata_should_destroy()
static bool prof_tdata_should_destroy (tsdn_t * tsdn, prof_tdata_t * tdata, bool even_if_attached) static
Definition at line 2264 of file prof.c.
{
     malloc_mutex_assert_owner(tsdn, tdata->lock);
     return prof_tdata_should_destroy_unlocked(tdata, even_if_attached);
 }
References prof_tdata_s::lock, malloc_mutex_assert_owner(), prof_tdata_should_destroy_unlocked(), and prof_gctx_merge_iter_arg_s::tsdn.
Referenced by prof_tctx_destroy(), prof_tdata_detach(), and prof_tdata_expire().
prof_tdata_should_destroy_unlocked()
static bool prof_tdata_should_destroy_unlocked (prof_tdata_t * tdata, bool even_if_attached) static
Definition at line 2253 of file prof.c.
{
     if (tdata->attached && !even_if_attached) {
         return false;
     }
     if (ckh_count(&tdata->bt2tctx) != 0) {
         return false;
     }
     return true;
 }
References prof_tdata_s::attached, prof_tdata_s::bt2tctx, and ckh_count.
Referenced by prof_tdata_destroy_locked(), and prof_tdata_should_destroy().
prof_thr_node_hash()
static void prof_thr_node_hash (const void * key, size_t r_hash[2]) static
Definition at line 2176 of file prof.c.
{
     const prof_thr_node_t *thr_node = (prof_thr_node_t *)key;
     hash(&thr_node->thr_uid, sizeof(uint64_t), 0x94122f35U, r_hash);
 }
References hash(), and prof_thr_node_s::thr_uid.
Referenced by prof_boot2(), and prof_try_log().
prof_thr_node_keycomp()
static bool prof_thr_node_keycomp (const void * k1, const void * k2) static
Definition at line 2182 of file prof.c.
{
     const prof_thr_node_t *thr_node1 = (prof_thr_node_t *)k1;
     const prof_thr_node_t *thr_node2 = (prof_thr_node_t *)k2;
     return thr_node1->thr_uid == thr_node2->thr_uid;
 }
References prof_thr_node_s::thr_uid.
Referenced by prof_boot2(), and prof_try_log().
prof_thr_uid_alloc()
static uint64_t prof_thr_uid_alloc (tsdn_t * tsdn) static
Definition at line 2189 of file prof.c.
{
     uint64_t thr_uid;
     malloc_mutex_lock(tsdn, &next_thr_uid_mtx);
     thr_uid = next_thr_uid;
     next_thr_uid++;
     malloc_mutex_unlock(tsdn, &next_thr_uid_mtx);
     return thr_uid;
 }
References malloc_mutex_lock(), malloc_mutex_unlock(), next_thr_uid, next_thr_uid_mtx, and prof_gctx_merge_iter_arg_s::tsdn.
Referenced by prof_tdata_init().
prof_thread_active_get()
bool prof_thread_active_get (tsd_t * tsd)
Definition at line 2855 of file prof.c.
{
     prof_tdata_t *tdata;
     tdata = prof_tdata_get(tsd, true);
     if (tdata == NULL) {
         return false;
     }
     return tdata->active;
 }
References prof_tdata_s::active, NULL, and prof_tdata_get().
prof_thread_active_init_get()
bool prof_thread_active_init_get (tsdn_t * tsdn)
Definition at line 2878 of file prof.c.
{
     bool active_init;
     malloc_mutex_lock(tsdn, &prof_thread_active_init_mtx);
     active_init = prof_thread_active_init;
     malloc_mutex_unlock(tsdn, &prof_thread_active_init_mtx);
     return active_init;
 }
References malloc_mutex_lock(), malloc_mutex_unlock(), prof_thread_active_init, and prof_thread_active_init_mtx.
Referenced by prof_tdata_init().
prof_thread_active_init_set()
bool prof_thread_active_init_set (tsdn_t * tsdn, bool active_init)
Definition at line 2888 of file prof.c.
{
     bool active_init_old;
     malloc_mutex_lock(tsdn, &prof_thread_active_init_mtx);
     active_init_old = prof_thread_active_init;
     prof_thread_active_init = active_init;
     malloc_mutex_unlock(tsdn, &prof_thread_active_init_mtx);
     return active_init_old;
 }
References malloc_mutex_lock(), malloc_mutex_unlock(), prof_thread_active_init, and prof_thread_active_init_mtx.
prof_thread_active_set()
bool prof_thread_active_set (tsd_t * tsd, bool active)
Definition at line 2866 of file prof.c.
{
     prof_tdata_t *tdata;
     tdata = prof_tdata_get(tsd, true);
     if (tdata == NULL) {
         return true;
     }
     tdata->active = active;
     return false;
 }
References prof_tdata_s::active, NULL, and prof_tdata_get().
prof_thread_name_alloc()
static char * prof_thread_name_alloc (tsdn_t * tsdn, const char * thread_name) static
Definition at line 2794 of file prof.c.
{
     char *ret;
     size_t size;
     if (thread_name == NULL) {
         return NULL;
     }
     size = strlen(thread_name) + 1;
     if (size == 1) {
         return "";
     }
     ret = iallocztm(tsdn, size, sz_size2index(size), false, NULL, true,
         arena_get(TSDN_NULL, 0, true), true);
     if (ret == NULL) {
         return NULL;
     }
     memcpy(ret, thread_name, size);
     return ret;
 }
References arena_get(), iallocztm(), memcpy, NULL, ret, sz_size2index(), and TSDN_NULL.
Referenced by prof_tdata_reinit(), and prof_thread_name_set().
prof_thread_name_get()
const char* prof_thread_name_get (tsd_t * tsd)
Definition at line 2783 of file prof.c.
{
     prof_tdata_t *tdata;
     tdata = prof_tdata_get(tsd, true);
     if (tdata == NULL) {
         return "";
     }
     return (tdata->thread_name != NULL ? tdata->thread_name : "");
 }
References NULL, prof_tdata_get(), and prof_tdata_s::thread_name.
Referenced by prof_try_log().
prof_thread_name_set()
int prof_thread_name_set (tsd_t * tsd, const char * thread_name)
Definition at line 2817 of file prof.c.
{
     prof_tdata_t *tdata;
     unsigned i;
     char *s;
     tdata = prof_tdata_get(tsd, true);
     if (tdata == NULL) {
         return EAGAIN;
     }
     /* Validate input. */
     if (thread_name == NULL) {
         return EFAULT;
     }
     for (i = 0; thread_name[i] != '\0'; i++) {
         char c = thread_name[i];
         if (!isgraph(c) && !isblank(c)) {
             return EFAULT;
         }
     }
     s = prof_thread_name_alloc(tsd_tsdn(tsd), thread_name);
     if (s == NULL) {
         return EAGAIN;
     }
     if (tdata->thread_name != NULL) {
         idalloctm(tsd_tsdn(tsd), tdata->thread_name, NULL, NULL, true,
             true);
         tdata->thread_name = NULL;
     }
     if (strlen(s) > 0) {
         tdata->thread_name = s;
     }
     return 0;
 }
References mpq::c, idalloctm(), NULL, prof_tdata_get(), prof_thread_name_alloc(), prof_tdata_s::thread_name, and tsd_tsdn().
prof_try_log()
static void prof_try_log (tsd_t * tsd, const void * ptr, size_t usize, prof_tctx_t * tctx) static
Definition at line 444 of file prof.c.
{
     malloc_mutex_assert_owner(tsd_tsdn(tsd), tctx->tdata->lock);
     prof_tdata_t *cons_tdata = prof_tdata_get(tsd, false);
     if (cons_tdata == NULL) {
         /*
          * We decide not to log these allocations. cons_tdata will be
          * NULL only when the current thread is in a weird state (e.g.
          * it's being destroyed).
          */
         return;
     }
     malloc_mutex_lock(tsd_tsdn(tsd), &log_mtx);
     if (prof_logging_state != prof_logging_state_started) {
         goto label_done;
     }
     if (!log_tables_initialized) {
         bool err1 = ckh_new(tsd, &log_bt_node_set, PROF_CKH_MINITEMS,
                 prof_bt_node_hash, prof_bt_node_keycomp);
         bool err2 = ckh_new(tsd, &log_thr_node_set, PROF_CKH_MINITEMS,
                 prof_thr_node_hash, prof_thr_node_keycomp);
         if (err1 || err2) {
             goto label_done;
         }
         log_tables_initialized = true;
     }
     nstime_t alloc_time = prof_alloc_time_get(tsd_tsdn(tsd), ptr,
                       (alloc_ctx_t *)NULL);
     nstime_t free_time = NSTIME_ZERO_INITIALIZER;
     nstime_update(&free_time);
     size_t sz = sizeof(prof_alloc_node_t);
     prof_alloc_node_t *new_node = (prof_alloc_node_t *)
         iallocztm(tsd_tsdn(tsd), sz, sz_size2index(sz), false, NULL, true,
         arena_get(TSDN_NULL, 0, true), true);
     const char *prod_thr_name = (tctx->tdata->thread_name == NULL)?
                         "" : tctx->tdata->thread_name;
     const char *cons_thr_name = prof_thread_name_get(tsd);
     prof_bt_t bt;
     /* Initialize the backtrace, using the buffer in tdata to store it. */
     bt_init(&bt, cons_tdata->vec);
     prof_backtrace(&bt);
     prof_bt_t *cons_bt = &bt;
     /* We haven't destroyed tctx yet, so gctx should be good to read. */
     prof_bt_t *prod_bt = &tctx->gctx->bt;
     new_node->next = NULL;
     new_node->alloc_thr_ind = prof_log_thr_index(tsd, tctx->tdata->thr_uid,
                       prod_thr_name);
     new_node->free_thr_ind = prof_log_thr_index(tsd, cons_tdata->thr_uid,
                      cons_thr_name);
     new_node->alloc_bt_ind = prof_log_bt_index(tsd, prod_bt);
     new_node->free_bt_ind = prof_log_bt_index(tsd, cons_bt);
     new_node->alloc_time_ns = nstime_ns(&alloc_time);
     new_node->free_time_ns = nstime_ns(&free_time);
     new_node->usize = usize;
     if (log_alloc_first == NULL) {
         log_alloc_first = new_node;
         log_alloc_last = new_node;
     } else {
         log_alloc_last->next = new_node;
         log_alloc_last = new_node;
     }
 label_done:
     malloc_mutex_unlock(tsd_tsdn(tsd), &log_mtx);
 }
References prof_alloc_node_s::alloc_bt_ind, prof_alloc_node_s::alloc_thr_ind, prof_alloc_node_s::alloc_time_ns, arena_get(), prof_gctx_s::bt, bt_init(), ckh_new, prof_alloc_node_s::free_bt_ind, prof_alloc_node_s::free_thr_ind, prof_alloc_node_s::free_time_ns, prof_tctx_s::gctx, iallocztm(), prof_tdata_s::lock, log_alloc_first, log_alloc_last, log_bt_node_set, log_mtx, log_tables_initialized, log_thr_node_set, malloc_mutex_assert_owner(), malloc_mutex_lock(), malloc_mutex_unlock(), prof_alloc_node_s::next, nstime_ns, nstime_update, NSTIME_ZERO_INITIALIZER, NULL, prof_alloc_time_get(), prof_backtrace(), prof_bt_node_hash(), prof_bt_node_keycomp(), PROF_CKH_MINITEMS, prof_log_bt_index(), prof_log_thr_index(), prof_logging_state, prof_logging_state_started, prof_tdata_get(), prof_thr_node_hash(), prof_thr_node_keycomp(), prof_thread_name_get(), ptr(), sz_size2index(), tctx, prof_tctx_s::tdata, prof_tdata_s::thr_uid, prof_tdata_s::thread_name, tsd_tsdn(), TSDN_NULL, prof_alloc_node_s::usize, and prof_tdata_s::vec.
Referenced by prof_free_sampled_object().
rb_gen() [1/3]
rb_gen (static UNUSED, gctx_tree_ , prof_gctx_tree_t , prof_gctx_t , dump_link , prof_gctx_comp) const
References ret.
rb_gen() [2/3]
rb_gen (static UNUSED, tctx_tree_ , prof_tctx_tree_t , prof_tctx_t , tctx_link , prof_tctx_comp) const
rb_gen() [3/3]
rb_gen (static UNUSED, tdata_tree_ , prof_tdata_tree_t , prof_tdata_t , tdata_link , prof_tdata_comp)
Variable Documentation
a_uid
uint64_t a_uid = a->thr_uid
Definition at line 294 of file prof.c.
b
const prof_tdata_t * b
Initial value:
{
    unsigned a_len = a->bt.len
Definition at line 277 of file prof.c.
Referenced by Acore::Crypto::SRP6::_B(), _lf_pinbox_real_free(), G3D::addAndCarry(), G3D::MeshBuilder::addQuad(), G3D::MeshBuilder::addTriangle(), area2(), G3D::Color3uint8::asUInt32(), G3D::Color4uint8::asUInt32(), base64_decode(), base_get_num_blocks(), between(), G3D::Color3uint8::bgr(), G3D::Color4uint8::bgr(), G3D::Box::Box(), G3D::Box2D::Box2D(), buferror(), G3D::System::build(), MMAP::MapBuilder::buildAllMaps(), buildPolyDetail(), BZ2_bzclose(), BZ2_bzerror(), BZ2_bzread(), BZ2_bzRead(), BZ2_bzReadClose(), BZ2_bzReadGetUnused(), BZ2_bzwrite(), BZ2_bzWrite(), BZ2_bzWriteClose(), BZ2_bzWriteClose64(), G3D::System::calloc(), canRemoveVertex(), G3D::Capsule::Capsule(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::checkIntegrity(), G3D::clamp(), G3D::CollisionDetection::closestPointsBetweenLineAndLine(), G3D::CollisionDetection::closestPointToRectangle(), cmp(), collinear(), G3D::CollisionDetection::collisionTimeForMovingSphereFixedTriangle(), comp_names(), compare_bin(), compare_ulong(), compareDiagDist(), G3D::Array< T, MIN_ELEMENTS >::compareGT(), compareHoles(), compareItemX(), compareItemY(), compareItemZ(), G3D::MeshAlg::computeTangentSpaceBasis(), G3D::CollisionDetection::conservativeBoxBoxTest(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::containsKey(), G3D::CoordinateFrame::CoordinateFrame(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::copyFrom(), G3D::MeshAlg::countBoundaryEdges(), G3D::Any::Data::create(), G3D::ConvexPolygon::cut(), G3D::ConvexPolyhedron::cut(), G3D::Cylinder::Cylinder(), d2b(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::debugGetAverageBucketSize(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::debugGetDeepestBucketSize(), G3D::GImage::decodeTGA(), G3D::AABox::deserialize(), G3D::Any::deserialize(), G3D::Box::deserialize(), G3D::Capsule::deserialize(), G3D::CoordinateFrame::deserialize(), G3D::MD5Hash::deserialize(), G3D::Cylinder::deserialize(), G3D::GUniqueID::deserialize(), G3D::Line::deserialize(), G3D::LineSegment::deserialize(), G3D::Matrix3::deserialize(), G3D::Matrix4::deserialize(), G3D::NetAddress::deserialize(), G3D::PhysicsFrame::deserialize(), G3D::Plane::deserialize(), G3D::Quat::deserialize(), G3D::Ray::deserialize(), G3D::Rect2D::deserialize(), G3D::Sphere::deserialize(), G3D::Triangle::deserialize(), G3D::UprightFrame::deserialize(), G3D::UprightSpline::deserialize(), G3D::Vector2::deserialize(), G3D::Vector3::deserialize(), G3D::Vector4::deserialize(), G3D::Vector4int8::deserialize(), G3D::Welder::Settings::deserialize(), G3D::deserialize(), diff(), distPtTri(), do_recursion(), G3D::dot(), dtClosestHeightPointTriangle(), dtClosestPtPointTriangle(), dtMax(), dtMin(), dtoa(), dtRandomPointInConvexPoly(), dtSwap(), dtSwapByte(), dtTriArea2D(), G3D::GLight::effectSphere(), G3D::AABox::empty(), Player::EnchantmentFitsRequirements(), G3D::GImage::encodePPMASCII(), G3D::eps(), EqualsTrait< G3D::_internal::VN >::equals(), EqualsTrait< G3D::_internal::VNTi >::equals(), EqualsTrait< Key >::equals(), extent_ad_comp(), extent_ead_comp(), extent_esn_comp(), extent_esnead_comp(), extent_head_no_merge(), extent_merge_default(), extent_merge_impl(), extent_merge_wrapper(), extent_sn_comp(), extent_snad_comp(), f(), fill_uchar(), fill_uint16(), G3D::CollisionDetection::fillSolidBoxSolidBoxInfo(), Chunk::FindSubChunkOffset(), G3D::CollisionDetection::fixedSolidBoxIntersectsFixedSolidBox(), G3D::CollisionDetection::fixedSolidSphereIntersectsFixedTriangle(), formatter< bytes >::format(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::freeMemory(), G3D::fromBits(), G3D::Plane::fromEquation(), G3D::Matrix3::fuzzyEq(), G3D::fuzzyEq(), G3D::fuzzyGe(), G3D::fuzzyGt(), G3D::fuzzyLe(), G3D::fuzzyLt(), G3D::fuzzyNe(), G3D::g3dfnmatch(), MMAP::IntermediateValues::generateObjFile(), BoundsTrait< class G3D::Box >::getBounds(), BoundsTrait< class G3D::Box * >::getBounds(), getCornerHeight(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::getCreateEntry(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::getEntryPointer(), G3D::Plane::getEquation(), GridMap::getHeightFromFloat(), GridMap::getHeightFromUint16(), GridMap::getHeightFromUint8(), G3D::Matrix4::getPerspectiveProjectionParameters(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::getPointer(), G3D::GCamera::getProjectUnitMatrix(), G3D::GImage::GImage(), ha_compare_text(), ha_key_cmp(), i2b(), G3D::AABox::inf(), init_block_value(), intersect(), intersectProp(), G3D::Cone::intersects(), G3D::FileSystem::inZipfile(), G3D::FileSystem::isDirectory(), G3D::FileSystem::isFile(), G3D::FileSystem::isNewer(), G3D::CollisionDetection::isPointInsideTriangle(), G3D::FileSystem::isZipfile(), G3D::AABox::large(), left(), leftOn(), G3D::lerp(), G3D::Line::Line(), G3D::LineSegment::LineSegment(), IpLocationStore::Load(), G3D::GImage::load(), ObjectMgr::LoadAccessRequirements(), lshift(), malloc_strtoumax(), G3D::Matrix3::Matrix3(), G3D::Color3uint8::max(), G3D::Color4uint8::max(), G3D::AABox::maxFinite(), G3D::md5_process(), G3D::MD5Hash::MD5Hash(), mean(), G3D::Color3uint8::min(), G3D::Color4uint8::min(), mm_recursion(), mmed3(), G3D::mul(), mult(), multadd(), detail::multiply(), G3D::multiplyAndCarry(), my_instr_bin(), my_instr_simple(), my_ismbchar_utf8(), my_MD5Transform(), my_numcells_8bit(), my_numchars_8bit(), my_strnncoll_latin1_de(), my_strnncollsp_8bit_bin(), my_strnncollsp_latin1_de(), my_strnncollsp_simple(), my_xml_parse(), neon_recursion(), net_real_write(), nstime_compare(), G3D::AABox::operator!=(), DBCFile::Iterator::operator!=(), G3D::operator!=(), SpellModPred::operator()(), MageSpellModPred::operator()(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::CenterComparator::operator()(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::BoundsComparator::operator()(), Acore::ThreatOrderPred::operator()(), StringCompareLessI_T::operator()(), Acore::PowerPctOrderPred::operator()(), Acore::HealthPctOrderPred::operator()(), G3D::Box::operator*(), Movement::operator<<(), operator<<(), G3D::AABox::operator==(), G3D::Color3uint8::operator==(), DBCFile::Iterator::operator==(), G3D::operator==(), Movement::operator>>(), overlapSegSeg2d(), G3D::CollisionDetection::penetrationDepthForFixedBoxFixedBox(), G3D::Matrix4::perspectiveProjection(), G3D::Matrix4float64::perspectiveProjection(), G3D::Plane::Plane(), std::pow(), pow5mult(), prof_tctx_comp(), G3D::CollisionDetection::projectedDistanceForSolidBoxSolidBox(), ptr_cmp(), ptr_compare(), ptr_compare_0(), ptr_compare_1(), ptr_compare_2(), ptr_compare_3(), putShortMSB(), G3D::pythag(), quorem(), ratio(), G3D::Ray::Ray(), dtNavMeshQuery::raycast(), rcMax(), rcMin(), rcOffsetPoly(), rcSwap(), VMAP::GroupModel_Raw::Read(), G3D::readBGR(), G3D::BinaryInput::readColor3(), G3D::BinaryInput::readColor4(), G3D::BinaryInput::readFloat32(), G3D::BinaryInput::readFloat64(), Utils::ReadString(), G3D::LightweightConduit::receive(), G3D::ReliableConduit::receive(), G3D::Rect2D::Rect2D(), G3D::reinterpretFrom(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::remove(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::resize(), G3D::GImage::resolveFormat(), G3D::Color4uint8::rgb(), G3D::rgb8_to_bayer_bggr8(), G3D::rgb8_to_bayer_gbrg8(), G3D::rgb8_to_bayer_grbg8(), G3D::rgb8_to_bayer_rggb8(), G3D::rgb8_to_yuv420p(), G3D::rgb8_to_yuv422(), G3D::rgb8_to_yuv444(), G3D::GImage::RGBtoBGR(), s2b(), G3D::GImage::save(), Spell::SelectImplicitTrajTargets(), G3D::ReliableConduit::sendBuffer(), G3D::LightweightConduit::sendBuffer(), Player::SendLoot(), G3D::Dummy::serialize(), G3D::Triangle::serialize(), G3D::AABox::serialize(), G3D::Any::serialize(), G3D::Box::serialize(), G3D::Capsule::serialize(), G3D::CoordinateFrame::serialize(), G3D::MD5Hash::serialize(), G3D::Cylinder::serialize(), G3D::GUniqueID::serialize(), G3D::Line::serialize(), G3D::LineSegment::serialize(), G3D::Matrix3::serialize(), G3D::Matrix4::serialize(), G3D::NetAddress::serialize(), G3D::PhysicsFrame::serialize(), G3D::Plane::serialize(), G3D::Quat::serialize(), G3D::Ray::serialize(), G3D::Rect2D::serialize(), G3D::Sphere::serialize(), G3D::UprightFrame::serialize(), G3D::UprightSpline::serialize(), G3D::Vector2::serialize(), G3D::Vector3::serialize(), G3D::Vector4::serialize(), G3D::Vector4int8::serialize(), G3D::Welder::Settings::serialize(), G3D::serialize(), G3D::AnyVal::serialize(), G3D::ReliableConduit::serializeMessage(), G3D::LightweightConduit::serializeMessage(), BattlegroundQueue::SetBgTypeIdAndArenaType(), Item::SetInTrade(), GameObject::SetSpawnedByDefault(), BattlefieldWG::SetupBattlefield(), ShutdownCLIThread(), G3D::signedPow(), soap_base642s(), soap_block_size(), soap_end_block(), soap_end_send_flush(), soap_fbase(), soap_first_block(), soap_getbase64(), soap_next_block(), soap_pop_block(), soap_push_block(), soap_push_block_max(), soap_QName(), soap_QName2s(), soap_save_block(), soap_size_block(), soap_tag_cmp(), G3D::Sphere::Sphere(), standard_deviation(), StringCompareLessI(), StringEqualI(), G3D::Array< T, MIN_ELEMENTS >::swap(), G3D::Box::toAny(), G3D::CoordinateFrame::toObjectSpace(), G3D::Triangle::Triangle(), uleft(), detail::dragonbox::umul128(), npc_fos_corrupted_soul_fragment::npc_fos_corrupted_soul_fragmentAI::UpdateAI(), npc_q24545_lich_king::npc_q24545_lich_kingAI::UpdateAI(), vdot2(), vec_recursion(), G3D::Vector2::Vector2(), G3D::Vector3::Vector3(), G3D::Vector4::Vector4(), G3D::Vector4int8::Vector4int8(), vequal(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Node::verifyNode(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::Node::verifyNode(), vperpXZ(), G3D::MeshAlg::weldBoundaryEdges(), G3D::BinaryOutput::writeBool8(), G3D::BinaryOutput::writeBytes(), G3D::BinaryOutput::writeFloat32(), G3D::BinaryOutput::writeFloat64(), G3D::TextOutput::writeSymbols(), and G3D::AABox::zero().
b_len
unsigned b_len = b->bt.len
Definition at line 279 of file prof.c.
Referenced by if().
b_uid
uint64_t b_uid = b->thr_uid
Definition at line 295 of file prof.c.
bt2gctx
ckh_t bt2gctx static
Definition at line 191 of file prof.c.
Referenced by prof_boot2(), prof_dump_prep(), prof_gctx_try_destroy(), and prof_lookup_global().
bt2gctx_mtx
malloc_mutex_t bt2gctx_mtx
Definition at line 193 of file prof.c.
Referenced by prof_boot2(), prof_enter(), prof_leave(), prof_postfork_child(), prof_postfork_parent(), and prof_prefork0().
comp_len
unsigned comp_len = (a_len < b_len) ? a_len : b_len
Definition at line 280 of file prof.c.
cum_gctxs
atomic_u_t cum_gctxs static
Definition at line 177 of file prof.c.
Referenced by prof_gctx_mutex_choose().
gctx_locks
malloc_mutex_t* gctx_locks static
Definition at line 176 of file prof.c.
Referenced by prof_boot2(), prof_gctx_mutex_choose(), prof_postfork_child(), prof_postfork_parent(), and prof_prefork0().
lg_prof_sample
size_t lg_prof_sample
Definition at line 73 of file prof.c.
Referenced by prof_boot2(), prof_dump_header_impl(), prof_leakcheck(), prof_log_emit_metadata(), prof_reset(), and prof_sample_threshold_update().
log_alloc_first
prof_alloc_node_t* log_alloc_first = NULL static
Definition at line 163 of file prof.c.
Referenced by prof_log_emit_allocs(), prof_log_stop(), and prof_try_log().
log_alloc_last
prof_alloc_node_t* log_alloc_last = NULL static
Definition at line 164 of file prof.c.
Referenced by prof_log_stop(), and prof_try_log().
log_bt_first
prof_bt_node_t* log_bt_first = NULL static
Definition at line 159 of file prof.c.
Referenced by prof_log_bt_index(), prof_log_emit_traces(), and prof_log_stop().
log_bt_index
size_t log_bt_index = 0 static
Definition at line 106 of file prof.c.
Referenced by prof_log_bt_index(), and prof_log_stop().
log_bt_last
prof_bt_node_t* log_bt_last = NULL static
Definition at line 160 of file prof.c.
Referenced by prof_log_bt_index(), and prof_log_stop().
log_bt_node_set
ckh_t log_bt_node_set static
Definition at line 155 of file prof.c.
Referenced by prof_boot2(), prof_log_bt_index(), prof_log_stop(), and prof_try_log().
log_filename
char log_filename[ 1] static
Definition at line 95 of file prof.c.
Referenced by prof_log_start(), and prof_log_stop().
log_mtx
malloc_mutex_t log_mtx static
Definition at line 167 of file prof.c.
Referenced by prof_boot2(), prof_log_bt_index(), prof_log_start(), prof_log_stop(), prof_log_thr_index(), and prof_try_log().
log_seq
uint64_t log_seq = 0 static
Definition at line 94 of file prof.c.
Referenced by prof_log_start().
log_start_timestamp
nstime_t log_start_timestamp = NSTIME_ZERO_INITIALIZER static
Definition at line 103 of file prof.c.
Referenced by prof_log_emit_metadata(), and prof_log_start().
log_tables_initialized
bool log_tables_initialized = false static
Definition at line 154 of file prof.c.
Referenced by prof_boot2(), prof_log_stop(), and prof_try_log().
log_thr_first
prof_thr_node_t* log_thr_first = NULL static
Definition at line 161 of file prof.c.
Referenced by prof_log_emit_threads(), prof_log_stop(), and prof_log_thr_index().
log_thr_index
size_t log_thr_index = 0 static
Definition at line 107 of file prof.c.
Referenced by prof_log_stop(), and prof_log_thr_index().
log_thr_last
prof_thr_node_t* log_thr_last = NULL static
Definition at line 162 of file prof.c.
Referenced by prof_log_stop(), and prof_log_thr_index().
log_thr_node_set
ckh_t log_thr_node_set static
Definition at line 156 of file prof.c.
Referenced by prof_boot2(), prof_log_stop(), prof_log_thr_index(), and prof_try_log().
next_thr_uid
uint64_t next_thr_uid static
Definition at line 202 of file prof.c.
Referenced by prof_boot2(), and prof_thr_uid_alloc().
next_thr_uid_mtx
malloc_mutex_t next_thr_uid_mtx static
Definition at line 203 of file prof.c.
Referenced by prof_boot2(), prof_postfork_child(), prof_postfork_parent(), prof_prefork1(), and prof_thr_uid_alloc().
opt_lg_prof_interval
ssize_t opt_lg_prof_interval = LG_PROF_INTERVAL_DEFAULT
Definition at line 37 of file prof.c.
Referenced by prof_boot1().
opt_lg_prof_sample
size_t opt_lg_prof_sample = LG_PROF_SAMPLE_DEFAULT
Definition at line 36 of file prof.c.
Referenced by prof_boot2().
opt_prof
bool opt_prof = false
Definition at line 33 of file prof.c.
Referenced by prof_boot1(), prof_boot2(), prof_log_start(), prof_log_stop(), prof_mdump(), prof_postfork_child(), prof_postfork_parent(), prof_prefork0(), and prof_prefork1().
opt_prof_accum
bool opt_prof_accum = false
Definition at line 41 of file prof.c.
Referenced by prof_dump_gctx(), prof_gctx_should_destroy(), prof_malloc_sample_object(), prof_tctx_destroy(), prof_tctx_merge_gctx(), prof_tctx_merge_tdata(), prof_tctx_should_destroy(), and prof_tdata_merge_iter().
opt_prof_active
bool opt_prof_active = true
Definition at line 34 of file prof.c.
Referenced by prof_boot2().
opt_prof_final
bool opt_prof_final = false
Definition at line 39 of file prof.c.
Referenced by prof_boot2(), and prof_fdump().
opt_prof_gdump
bool opt_prof_gdump = false
Definition at line 38 of file prof.c.
Referenced by prof_boot1(), and prof_boot2().
opt_prof_leak
bool opt_prof_leak = false
Definition at line 40 of file prof.c.
Referenced by prof_boot1(), and prof_fdump().
opt_prof_log
bool opt_prof_log = false
Definition at line 42 of file prof.c.
Referenced by prof_boot2().
opt_prof_prefix
char opt_prof_prefix[ 1]
Definition at line 43 of file prof.c.
Referenced by prof_boot0(), prof_boot2(), prof_dump_filename(), prof_fdump(), prof_gdump(), prof_idump(), prof_log_start(), and prof_mdump().
opt_prof_thread_active_init
bool opt_prof_thread_active_init = true
Definition at line 35 of file prof.c.
Referenced by prof_boot2().
prof_active
bool prof_active
Definition at line 54 of file prof.c.
Referenced by prof_active_get(), prof_active_set(), and prof_boot2().
prof_active_mtx
malloc_mutex_t prof_active_mtx static
Definition at line 55 of file prof.c.
Referenced by prof_active_get(), prof_active_set(), prof_boot2(), prof_postfork_child(), prof_postfork_parent(), and prof_prefork1().
prof_booted
bool prof_booted = false static
Definition at line 228 of file prof.c.
Referenced by prof_boot2(), prof_fdump(), prof_gdump(), prof_idump(), prof_log_start(), prof_log_stop(), and prof_mdump().
prof_dump_buf
char prof_dump_buf[ 1] static
Definition at line 216 of file prof.c.
Referenced by prof_dump_flush(), prof_dump_maps(), and prof_dump_write().
prof_dump_buf_end
size_t prof_dump_buf_end static
Definition at line 224 of file prof.c.
Referenced by prof_dump_flush(), prof_dump_maps(), and prof_dump_write().
prof_dump_fd
int prof_dump_fd static
Definition at line 225 of file prof.c.
Referenced by prof_dump_close(), prof_dump_file(), and prof_dump_flush().
prof_dump_header
prof_dump_header_t* JET_MUTABLE prof_dump_header = prof_dump_header_impl
Definition at line 1615 of file prof.c.
Referenced by prof_dump_file().
prof_dump_iseq
uint64_t prof_dump_iseq static
Definition at line 207 of file prof.c.
Referenced by prof_idump().
prof_dump_mseq
uint64_t prof_dump_mseq static
Definition at line 208 of file prof.c.
Referenced by prof_mdump().
prof_dump_mtx
malloc_mutex_t prof_dump_mtx static
Definition at line 215 of file prof.c.
Referenced by prof_boot2(), prof_dump(), prof_postfork_child(), prof_postfork_parent(), prof_prefork0(), and prof_reset().
prof_dump_open
prof_dump_open_t* JET_MUTABLE prof_dump_open = prof_dump_open_impl
Definition at line 1242 of file prof.c.
Referenced by prof_dump_file().
prof_dump_seq
uint64_t prof_dump_seq static
Definition at line 206 of file prof.c.
Referenced by prof_dump_filename().
prof_dump_seq_mtx
malloc_mutex_t prof_dump_seq_mtx static
Definition at line 205 of file prof.c.
Referenced by prof_boot2(), prof_fdump(), prof_gdump(), prof_idump(), prof_mdump(), prof_postfork_child(), prof_postfork_parent(), and prof_prefork1().
prof_dump_useq
uint64_t prof_dump_useq static
Definition at line 209 of file prof.c.
Referenced by prof_gdump().
prof_gdump_mtx
malloc_mutex_t prof_gdump_mtx static
Definition at line 69 of file prof.c.
Referenced by prof_boot2(), prof_gdump_get(), prof_gdump_set(), prof_postfork_child(), prof_postfork_parent(), and prof_prefork1().
prof_gdump_val
bool prof_gdump_val
Definition at line 68 of file prof.c.
Referenced by prof_boot2(), prof_gdump_get(), and prof_gdump_set().
prof_interval
uint64_t prof_interval = 0
Definition at line 71 of file prof.c.
Referenced by prof_boot1().
prof_logging_state
prof_logging_state_t prof_logging_state = prof_logging_state_stopped
Definition at line 87 of file prof.c.
Referenced by prof_log_bt_index(), prof_log_start(), prof_log_stop(), prof_log_thr_index(), and prof_try_log().
prof_thread_active_init
bool prof_thread_active_init static
Definition at line 61 of file prof.c.
Referenced by prof_boot2(), prof_thread_active_init_get(), and prof_thread_active_init_set().
prof_thread_active_init_mtx
malloc_mutex_t prof_thread_active_init_mtx static
Definition at line 62 of file prof.c.
Referenced by prof_boot2(), prof_postfork_child(), prof_postfork_parent(), prof_prefork1(), prof_thread_active_init_get(), and prof_thread_active_init_set().
ret
return ret = memcmp(a->bt.vec, b->bt.vec, comp_len * sizeof(void *))
Definition at line 281 of file prof.c.
Referenced by ScriptMgr::AnticheatCheckMovementInfo(), ScriptMgr::AnticheatHandleDoubleJump(), DBUpdater< T >::ApplyFile(), arena_bin_malloc_hard(), arena_choose_hard(), arena_choose_impl(), arena_get(), arena_i_decay_ctl(), arena_i_decay_ms_ctl_impl(), arena_i_destroy_ctl(), arena_i_dss_ctl(), arena_i_extent_hooks_ctl(), arena_i_index(), arena_i_initialized_ctl(), arena_i_purge_ctl(), arena_i_reset_ctl(), arena_i_reset_destroy_helper(), arena_i_retain_grow_limit_ctl(), arena_malloc_small(), arena_palloc(), arena_ralloc(), arena_ralloc_no_move(), arena_slab_reg_alloc(), arenas_create_ctl(), arenas_decay_ms_ctl_impl(), arenas_i(), arenas_i_impl(), arenas_lookup_ctl(), arenas_narenas_ctl(), argon2_verify(), argon2_verify_ctx(), BigNumber::AsDecStr(), BigNumber::AsHexStr(), background_thread_ctl(), base_alloc_impl(), base_extent_bump_alloc(), base_extent_bump_alloc_helper(), bitmap_is_prefix(), blake2b(), blake2b_long(), BZ2_bzBuffToBuffCompress(), BZ2_bzBuffToBuffDecompress(), BZ2_bzRead(), BZ2_bzReadOpen(), BZ2_bzWrite(), BZ2_bzWriteClose64(), BZ2_bzWriteOpen(), cache_bin_alloc_easy(), ScriptMgr::CanAddMember(), ScriptMgr::CanApplyEnchantment(), ScriptMgr::CanApplyEquipSpell(), ScriptMgr::CanApplyEquipSpellsItemSet(), ScriptMgr::CanApplySoulboundFlag(), ScriptMgr::CanApplyWeaponDependentAuraDamageMod(), ScriptMgr::CanAreaExploreAndOutdoor(), ScriptMgr::CanArmorDamageModifier(), ScriptMgr::CanBattleFieldPort(), ScriptMgr::CanCastItemCombatSpell(), ScriptMgr::CanCastItemUseSpell(), ScriptMgr::CanCheckCriteria(), canCreateExtraItems(), CanCreatePerfectItem(), ScriptMgr::CanEnterMap(), ScriptMgr::CanEquipItem(), ScriptMgr::CanFillPlayersToBG(), ScriptMgr::CanFillPlayersToBGWithSpecific(), ScriptMgr::CanGiveMailRewardAtGiveLevel(), ScriptMgr::CanGroupAccept(), ScriptMgr::CanGroupInvite(), ScriptMgr::CanGroupJoinBattlegroundQueue(), ScriptMgr::CanGuildSendBankList(), ScriptMgr::CanInitTrade(), ScriptMgr::CanItemApplyEquipSpell(), ScriptMgr::CanJoinInArenaQueue(), ScriptMgr::CanJoinInBattlegroundQueue(), ScriptMgr::CanJoinLfg(), ScriptMgr::CanModAuraEffectDamageDone(), ScriptMgr::CanModAuraEffectModDamagePercentDone(), ScriptMgr::CanPrepare(), ScriptMgr::CanRepopAtGraveyard(), ScriptMgr::CanResetTalents(), ScriptMgr::CanSaveEquipNewItem(), ScriptMgr::CanSaveToDB(), ScriptMgr::CanScalingEverything(), ScriptMgr::CanSelectSpecTalent(), ScriptMgr::CanSellItem(), ScriptMgr::CanSendAuctionHello(), ScriptMgr::CanSendMail(), ScriptMgr::CanSendMessageBGQueue(), ScriptMgr::CanSetPhaseMask(), ScriptMgr::CanUnequipItem(), ScriptMgr::CanUnlearnSpellDefault(), ScriptMgr::CanUnlearnSpellSet(), ScriptMgr::CanUseItem(), ScriptMgr::CheckItemInSlotAtLoadInventory(), choose_arena(), chunk_alloc(), chunk_alloc_dss(), chunk_alloc_mmap(), chunk_alloc_mmap_slow(), chunk_dss_prec_get(), chunk_in_dss(), chunk_recycle(), ckh_grow(), ckh_insert(), ckh_new(), G3D::AtomicInt32::compareAndSet(), G3D::GImage::copySubImage(), Guild::Create(), CreateDir(), ctl_bymib(), ctl_byname(), ctl_init(), ctl_lookup(), ctl_nametomib(), CTL_RO_NL_GEN(), CTL_TSD_RO_NL_CGEN(), G3D::System::currentProgramFilename(), deflateReset(), dtoa(), dynstr_append_os_quoted(), epoch_ctl(), Map::ExistMap(), BigNumber::Exp(), experimental_arenas_i_index(), experimental_arenas_i_pactivep_ctl(), experimental_hooks_install_ctl(), experimental_hooks_remove_ctl(), experimental_utilization_batch_query_ctl(), experimental_utilization_query_ctl(), extent_alloc_core(), extent_alloc_default_impl(), extent_alloc_dss(), extent_alloc_mmap(), extent_dss_prec_get(), extent_esnead_comp(), extent_hooks_set(), extent_lock_from_addr(), extent_size_quantize_ceil(), extent_size_quantize_floor(), extent_snad_comp(), extents_first_fit_locked(), ExtractSingleWmo(), fillArchiveNameVector(), Acore::Find(), floatToRawIntBits(), get_index_dynamic(), Vehicle::GetAvailableSeatCount(), BattlegroundSA::GetClosestGraveyard(), MPQMgr::GetFileFrom(), MySQLConnection::GetPreparedStatement(), G3D::GMutex::GMutex(), gz_comp(), gz_decomp(), gz_init(), gz_load(), gzclose_r(), gzclose_w(), gzgetc(), gzoffset(), gzputs(), gzseek(), gzseek64(), gztell(), hash_get_block_32(), hash_get_block_64(), hook_install(), huge_palloc(), huge_prof_ctx_get(), huge_ralloc(), huge_salloc(), iallocztm(), if(), ScriptMgr::IfNormalReaction(), imalloc_sample(), inflate(), inflateBack(), inflateInit2_(), inflateSetDictionary(), init_queue_ex(), Acore::Insert(), intBitsToFloat(), ipalloct(), ipallocztm(), isalloc(), ScriptMgr::IsCompletedCriteria(), ScriptMgr::IsCustomBuildValuesUpdate(), ScriptMgr::IsNeedModHealPercent(), ScriptMgr::IsNeedModMeleeDamagePercent(), ScriptMgr::IsNeedModSpellDamagePercent(), ScriptMgr::IsRealmCompleted(), je_mallctl(), je_mallctlbymib(), je_mallctlnametomib(), je_malloc_usable_size(), je_posix_memalign(), je_realloc(), JEMALLOC_ATTR(), large_ralloc(), G3D::BinaryInput::loadIntoMemory(), malloc_default(), malloc_init_hard_a0(), malloc_snprintf(), malloc_strtoumax(), malloc_vsnprintf(), max_background_threads_ctl(), BigNumber::ModExp(), my_realpath(), my_str_malloc_default(), my_strtod_int(), my_xml_scan(), ScriptMgr::NotAvoidSatisfy(), ScriptMgr::NotSetArenaTeamInfoField(), ScriptMgr::NotVisibleGloballyFor(), obtain_malloc_conf(), ScriptMgr::OnBeforeAchievementComplete(), ScriptMgr::OnBeforeCriteriaProgress(), ScriptMgr::OnBeforeLootEqualChanced(), ScriptMgr::OnBeforePlayerQuestComplete(), ScriptMgr::OnBeforePlayerTeleport(), ScriptMgr::OnBeforeSendExitMessageArenaQueue(), ScriptMgr::OnBeforeSendJoinMessageArenaQueue(), ScriptMgr::OnItemRoll(), AppenderFile::OpenFile(), UpdateMask::operator|(), os_pages_map(), os_pages_trim(), pages_map(), pages_map_slow(), pages_trim(), ScriptMgr::PassedQuestKilledMonsterCredit(), prng_lg_range_u32(), prng_lg_range_u64(), prng_lg_range_zu(), prng_range_u32(), prng_range_u64(), prng_range_zu(), prof_active_ctl(), prof_alloc_prep(), prof_dump_close(), prof_dump_ctl(), prof_dump_flush(), prof_dump_gctx(), prof_dump_header_impl(), prof_dump_maps(), prof_dump_printf(), prof_gctx_dump_iter(), prof_gdump_ctl(), prof_log_start(), prof_log_start_ctl(), prof_lookup(), prof_reset_ctl(), prof_tctx_comp(), prof_tctx_finish_iter(), prof_thread_active_init_ctl(), prof_thread_name_alloc(), pthread_dummy(), quarantine_grow(), DatabaseWorkerPool< T >::Query(), rb_gen(), Vector3::Read(), WorldModelDefinition::Read(), WorldModelHeader::Read(), DoodadInstance::Read(), DoodadSet::Read(), LiquidHeader::Read(), H2ORenderMask::Read(), H2OHeader::Read(), H2OInformation::Read(), WMOGroupHeader::Read(), LiquidData::Read(), Utils::ReadString(), G3D::readWaiting(), G3D::readWholeFile(), G3D::ReliableConduit::receiveHeader(), G3D::ReliableConduit::receiveIntoBuffer(), G3D::ReliableConduit::ReliableConduit(), Acore::Remove(), G3D::selectOneReadSocket(), G3D::ReliableConduit::sendBuffer(), setval(), ScriptMgr::ShouldBeRewardedWithMoneyInsteadOfExp(), Acore::Size(), soap_recv_raw(), stats_arenas_i_index(), G3D::Matrix::svd(), sz_index2size_lookup(), sz_pind2sz_lookup(), sz_s2u_lookup(), sz_size2index_lookup(), tcache_alloc_large(), tcache_alloc_small(), tcache_alloc_small_hard(), tcache_create_ctl(), tcache_dalloc_small(), tcache_destroy_ctl(), tcache_flush_ctl(), thread_prof_active_ctl(), thread_prof_name_ctl(), thread_tcache_flush_ctl(), TimeToTimestampStr(), Utils::TransformDoodadVertex(), Utils::TransformWmoDoodad(), u2rz(), Utils::VectorTransform(), G3D::LightweightConduit::waitingMessageType(), PlayerDumpWriter::WriteDump(), zone_memalign(), zone_valloc(), and G3D::GMutex::~GMutex().
tctx
prof_tctx_t* tctx
Definition at line 313 of file prof.c.
Referenced by arena_prof_tctx_set(), extent_prof_tctx_set(), if(), imalloc_body(), irallocx_prof(), irallocx_prof_sample(), irealloc_prof(), irealloc_prof_sample(), ixallocx_prof(), ixallocx_prof_sample(), large_prof_tctx_set(), prof_free(), prof_free_sampled_object(), prof_malloc(), prof_malloc_sample_object(), prof_realloc(), prof_tctx_destroy(), prof_tctx_dump_iter(), prof_tctx_finish_iter(), prof_tctx_merge_gctx(), prof_tctx_merge_iter(), prof_tctx_merge_tdata(), prof_tctx_reset(), prof_tctx_set(), prof_tctx_should_destroy(), prof_tdata_merge_iter(), and prof_try_log().
tdata_locks
malloc_mutex_t* tdata_locks static
Definition at line 185 of file prof.c.
Referenced by prof_boot2(), prof_postfork_child(), prof_postfork_parent(), prof_prefork0(), and prof_tdata_mutex_choose().
tdatas
prof_tdata_tree_t tdatas static
Definition at line 199 of file prof.c.
Referenced by prof_boot2(), prof_dump_header_impl(), prof_dump_prep(), prof_reset(), prof_tdata_destroy_locked(), and prof_tdata_init_impl().
tdatas_mtx
malloc_mutex_t tdatas_mtx static
Definition at line 200 of file prof.c.
Referenced by prof_boot2(), prof_dump_header_impl(), prof_dump_prep(), prof_postfork_child(), prof_postfork_parent(), prof_prefork0(), prof_reset(), prof_tdata_destroy(), prof_tdata_destroy_locked(), and prof_tdata_init_impl().
updated
prof_tctx_t bool updated
Initial value:
{
    prof_tdata_t *tdata
Definition at line 313 of file prof.c.
Referenced by ScriptMgr::OnAfterUpdateEncounterState(), prof_realloc(), and Map::UpdateEncounterState().