Azerotcore-wotlk: at_blackrock_stadium Class Reference
at_blackrock_stadium Class Reference
Public Member Functions
at_blackrock_stadium ()
bool OnTrigger (Player *player, const AreaTrigger *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 759 of file instance_blackrock_spire.cpp.
Constructor & Destructor Documentation
at_blackrock_stadium()
at_blackrock_stadium::at_blackrock_stadium () inline
Definition at line 762 of file instance_blackrock_spire.cpp.
 : AreaTriggerScript("at_blackrock_stadium") { }
Member Function Documentation
OnTrigger()
bool at_blackrock_stadium::OnTrigger (Player * player, const AreaTrigger *) inline override virtual
Reimplemented from AreaTriggerScript.
Definition at line 764 of file instance_blackrock_spire.cpp.
     {
         if (player && player->IsAlive())
         {
             InstanceScript* instance = player->GetInstanceScript();
             if (!instance)
                 return false;
             Creature* rend;
             if (instance->GetBossState(DATA_WARCHIEF_REND_BLACKHAND) == NOT_STARTED)
             {
                 if ((rend = player->FindNearestCreature(NPC_WARCHIEF_REND_BLACKHAND, 100.0f, false)))
                     rend->Respawn(true);
             }
             if ((rend = player->FindNearestCreature(NPC_WARCHIEF_REND_BLACKHAND, 100.0f)))
             {
                 rend->AI()->SetData(AREATRIGGER, AREATRIGGER_BLACKROCK_STADIUM);
                 return true;
             }
         }
         return false;
     }
References Creature::AI(), AREATRIGGER, AREATRIGGER_BLACKROCK_STADIUM, DATA_WARCHIEF_REND_BLACKHAND, WorldObject::FindNearestCreature(), InstanceScript::GetBossState(), WorldObject::GetInstanceScript(), Unit::IsAlive(), NOT_STARTED, NPC_WARCHIEF_REND_BLACKHAND, Creature::Respawn(), and UnitAI::SetData().
The documentation for this class was generated from the following file:
src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/instance_blackrock_spire.cpp