Azerotcore-wotlk: deps/mysqllite/strings/strxmov.c File Reference
strxmov.c File Reference
#include <my_global.h>
#include "m_string.h"
#include <stdarg.h>
Functions
char * strxmov (char *dst, const char *src,...)
Function Documentation
strxmov()
char* strxmov (char * dst, const char * src, ...)
Definition at line 37 of file strxmov.c.
 {
   va_list pvar;
   va_start(pvar,src);
   while (src != NullS) {
     while ((*dst++ = *src++)) ;
     dst--;
     src = va_arg(pvar, char *);
   }
   va_end(pvar);
   *dst = 0;         /* there might have been no sources! */
   return dst;
 }
References NullS.
Referenced by find_file_in_path(), get_charsets_dir(), get_internal_charset(), my_print_default_files(), and search_default_file_with_ext().