Azerotcore-wotlk: boss_festergut::boss_festergutAI Struct Reference
boss_festergut::boss_festergutAI Struct Reference
Public Member Functions
boss_festergutAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *who) override
void JustDied (Unit *) override
void JustReachedHome () override
void EnterEvadeMode () override
void KilledUnit (Unit *victim) override
void SpellHitTarget (Unit *target, SpellInfo const *spell) override
void RemoveBlight ()
void UpdateAI (uint32 diff) override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 type) const override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SpellHit (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
ObjectGuid _gasDummyGUID
uint32 _maxInoculatedStack
uint32 _inhaleCounter
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 86 of file boss_festergut.cpp.
Constructor & Destructor Documentation
boss_festergutAI()
boss_festergut::boss_festergutAI::boss_festergutAI (Creature * creature) inline
Definition at line 88 of file boss_festergut.cpp.
                                              : BossAI(creature, DATA_FESTERGUT)
         {
             _gasDummyGUID.Clear();
         }
References _gasDummyGUID, and ObjectGuid::Clear().
Member Function Documentation
EnterCombat()
void boss_festergut::boss_festergutAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from BossAI.
Definition at line 111 of file boss_festergut.cpp.
         {
             if (!instance->CheckRequiredBosses(DATA_FESTERGUT, who->ToPlayer()))
             {
                 EnterEvadeMode();
                 instance->DoCastSpellOnPlayers(LIGHT_S_HAMMER_TELEPORT);
                 return;
             }
             events.ScheduleEvent(EVENT_BERSERK, 300000);
             events.ScheduleEvent(EVENT_INHALE_BLIGHT, urand(25000, 30000));
             events.ScheduleEvent(EVENT_GAS_SPORE, urand(20000, 25000));
             events.ScheduleEvent(EVENT_VILE_GAS, urand(30000, 40000), 1);
             events.ScheduleEvent(EVENT_GASTRIC_BLOAT, urand(12500, 15000));
             if (IsHeroic())
                 events.ScheduleEvent(EVENT_FESTERGUT_GOO, urand(15000, 20000));
             me->setActive(true);
             Talk(SAY_AGGRO);
             DoZoneInCombat();
             if (Creature* gasDummy = me->FindNearestCreature(NPC_GAS_DUMMY, 100.0f, true))
                 _gasDummyGUID = gasDummy->GetGUID();
             if (Creature* professor = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_PROFESSOR_PUTRICIDE)))
                 professor->AI()->DoAction(ACTION_FESTERGUT_COMBAT);
         }
References _gasDummyGUID, ACTION_FESTERGUT_COMBAT, InstanceScript::CheckRequiredBosses(), DATA_FESTERGUT, DATA_PROFESSOR_PUTRICIDE, InstanceScript::DoCastSpellOnPlayers(), CreatureAI::DoZoneInCombat(), EnterEvadeMode(), EVENT_BERSERK, EVENT_FESTERGUT_GOO, EVENT_GAS_SPORE, EVENT_GASTRIC_BLOAT, EVENT_INHALE_BLIGHT, EVENT_VILE_GAS, WorldObject::FindNearestCreature(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), BossAI::instance, ScriptedAI::IsHeroic(), LIGHT_S_HAMMER_TELEPORT, ScriptedAI::me, NPC_GAS_DUMMY, SAY_AGGRO, WorldObject::setActive(), CreatureAI::Talk(), Object::ToPlayer(), and urand().
EnterEvadeMode()
void boss_festergut::boss_festergutAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 154 of file boss_festergut.cpp.
         {
             ScriptedAI::EnterEvadeMode();
             if (Creature* professor = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_PROFESSOR_PUTRICIDE)))
                 professor->AI()->EnterEvadeMode();
         }
References DATA_PROFESSOR_PUTRICIDE, CreatureAI::EnterEvadeMode(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), BossAI::instance, and ScriptedAI::me.
Referenced by EnterCombat().
GetData()
uint32 boss_festergut::boss_festergutAI::GetData (uint32 type) const inline override virtual
Reimplemented from UnitAI.
Definition at line 270 of file boss_festergut.cpp.
         {
             if (type == DATA_INOCULATED_STACK)
                 return _maxInoculatedStack;
             return 0;
         }
References _maxInoculatedStack, and DATA_INOCULATED_STACK.
JustDied()
void boss_festergut::boss_festergutAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 138 of file boss_festergut.cpp.
         {
             _JustDied();
             Talk(SAY_DEATH);
             if (Creature* professor = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_PROFESSOR_PUTRICIDE)))
                 professor->AI()->DoAction(ACTION_FESTERGUT_DEATH);
             RemoveBlight();
         }
References BossAI::_JustDied(), ACTION_FESTERGUT_DEATH, DATA_PROFESSOR_PUTRICIDE, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), BossAI::instance, ScriptedAI::me, RemoveBlight(), SAY_DEATH, and CreatureAI::Talk().
JustReachedHome()
void boss_festergut::boss_festergutAI::JustReachedHome () inline override virtual
Reimplemented from BossAI.
Definition at line 148 of file boss_festergut.cpp.
         {
             _JustReachedHome();
             instance->SetBossState(DATA_FESTERGUT, FAIL);
         }
References BossAI::_JustReachedHome(), DATA_FESTERGUT, FAIL, BossAI::instance, and InstanceScript::SetBossState().
KilledUnit()
void boss_festergut::boss_festergutAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 161 of file boss_festergut.cpp.
         {
             if (victim->GetTypeId() == TYPEID_PLAYER)
                 Talk(SAY_KILL);
         }
References Object::GetTypeId(), SAY_KILL, CreatureAI::Talk(), and TYPEID_PLAYER.
RemoveBlight()
void boss_festergut::boss_festergutAI::RemoveBlight () inline
Definition at line 180 of file boss_festergut.cpp.
         {
             if (Creature* gasDummy = ObjectAccessor::GetCreature(*me, _gasDummyGUID))
                 for (uint8 i = 0; i < 3; ++i)
                 {
                     me->RemoveAurasDueToSpell(gaseousBlight[i]);
                     gasDummy->RemoveAurasDueToSpell(gaseousBlightVisual[i]);
                 }
         }
References _gasDummyGUID, gaseousBlight, gaseousBlightVisual, ObjectAccessor::GetCreature(), ScriptedAI::me, and Unit::RemoveAurasDueToSpell().
Referenced by JustDied(), and UpdateAI().
Reset()
void boss_festergut::boss_festergutAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 97 of file boss_festergut.cpp.
         {
             _maxInoculatedStack = 0;
             _inhaleCounter = 0;
             _Reset();
             events.Reset();
             if (Creature* gasDummy = me->FindNearestCreature(NPC_GAS_DUMMY, 100.0f, true))
             {
                 _gasDummyGUID = gasDummy->GetGUID();
                 for (uint8 i = 0; i < 3; ++i)
                     gasDummy->RemoveAurasDueToSpell(gaseousBlightVisual[i]);
             }
         }
References _gasDummyGUID, _inhaleCounter, _maxInoculatedStack, BossAI::_Reset(), WorldObject::FindNearestCreature(), gaseousBlightVisual, ScriptedAI::me, and NPC_GAS_DUMMY.
SetData()
void boss_festergut::boss_festergutAI::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from UnitAI.
Definition at line 264 of file boss_festergut.cpp.
         {
             if (type == DATA_INOCULATED_STACK && data > _maxInoculatedStack)
                 _maxInoculatedStack = data;
         }
References _maxInoculatedStack, and DATA_INOCULATED_STACK.
SpellHitTarget()
void boss_festergut::boss_festergutAI::SpellHitTarget (Unit * target, SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 167 of file boss_festergut.cpp.
         {
             if (spell->Id == PUNGENT_BLIGHT_HELPER)
                 target->RemoveAurasDueToSpell(INOCULATED_HELPER);
             else if (Player* p = target->ToPlayer())
             {
                 // Gaseous Blight damage
                 if (((spell->Id == 69159 || spell->Id == 70136 || spell->Id == 69161 || spell->Id == 70139 || spell->Id == 69163 || spell->Id == 70469) && p->GetQuestStatus(QUEST_RESIDUE_RENDEZVOUS_10) == QUEST_STATUS_INCOMPLETE) ||
                         ((spell->Id == 70135 || spell->Id == 70138 || spell->Id == 70468 || spell->Id == 70137 || spell->Id == 70140 || spell->Id == 70470) && p->GetQuestStatus(QUEST_RESIDUE_RENDEZVOUS_25) == QUEST_STATUS_INCOMPLETE))
                     p->CastSpell(p, SPELL_ORANGE_BLIGHT_RESIDUE, true);
             }
         }
References SpellInfo::Id, INOCULATED_HELPER, PUNGENT_BLIGHT_HELPER, QUEST_RESIDUE_RENDEZVOUS_10, QUEST_RESIDUE_RENDEZVOUS_25, QUEST_STATUS_INCOMPLETE, Unit::RemoveAurasDueToSpell(), SPELL_ORANGE_BLIGHT_RESIDUE, and Object::ToPlayer().
UpdateAI()
void boss_festergut::boss_festergutAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 190 of file boss_festergut.cpp.
         {
             if (!UpdateVictim() || !CheckInRoom())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_BERSERK:
                     me->CastSpell(me, SPELL_BERSERK2, true);
                     Talk(SAY_BERSERK);
                     break;
                 case EVENT_INHALE_BLIGHT:
                     RemoveBlight();
                     if (_inhaleCounter == 3)
                     {
                         Talk(EMOTE_WARN_PUNGENT_BLIGHT);
                         Talk(SAY_PUNGENT_BLIGHT);
                         me->CastSpell(me, SPELL_PUNGENT_BLIGHT, false);
                         _inhaleCounter = 0;
                         events.RescheduleEvent(EVENT_GAS_SPORE, urand(20000, 25000));
                     }
                     else
                     {
                         me->CastSpell(me, SPELL_INHALE_BLIGHT, false);
                         // just cast and dont bother with target, conditions will handle it
                         ++_inhaleCounter;
                         if (_inhaleCounter < 3)
                             me->CastSpell(me, gaseousBlight[_inhaleCounter], true, nullptr, nullptr, me->GetGUID());
                     }
                     events.ScheduleEvent(EVENT_INHALE_BLIGHT, 34000);
                     break;
                 case EVENT_GAS_SPORE:
                     Talk(EMOTE_WARN_GAS_SPORE);
                     Talk(EMOTE_GAS_SPORE);
                     me->CastCustomSpell(SPELL_GAS_SPORE, SPELLVALUE_MAX_TARGETS, RAID_MODE<int32>(2, 3, 2, 3), me);
                     events.ScheduleEvent(EVENT_GAS_SPORE, urand(40000, 45000));
                     events.DelayEventsToMax(20000, 1); // delay EVENT_VILE_GAS
                     break;
                 case EVENT_VILE_GAS:
                     {
                         std::list<Unit*> targets;
                         uint32 minTargets = RAID_MODE<uint32>(3, 8, 3, 8);
                         SelectTargetList(targets, minTargets, SELECT_TARGET_RANDOM, -5.0f, true);
                         float minDist = 0.0f;
                         if (targets.size() >= minTargets)
                             minDist = -5.0f;
                         if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, minDist, true))
                             me->CastSpell(target, SPELL_VILE_GAS, false);
                         events.ScheduleEvent(EVENT_VILE_GAS, urand(28000, 35000), 1);
                         break;
                     }
                 case EVENT_GASTRIC_BLOAT:
                     me->CastSpell(me->GetVictim(), SPELL_GASTRIC_BLOAT, false);
                     events.ScheduleEvent(EVENT_GASTRIC_BLOAT, urand(15000, 17500));
                     break;
                 case EVENT_FESTERGUT_GOO:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, NonTankTargetSelector(me)))
                         if (Creature* professor = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_PROFESSOR_PUTRICIDE)))
                             professor->CastSpell(target, SPELL_MALLABLE_GOO_H, true);
                     events.ScheduleEvent(EVENT_FESTERGUT_GOO, urand(15000, 20000));
                 default:
                     break;
             }
             DoMeleeAttackIfReady();
         }
References _inhaleCounter, Unit::CastCustomSpell(), Unit::CastSpell(), BossAI::CheckInRoom(), DATA_PROFESSOR_PUTRICIDE, UnitAI::DoMeleeAttackIfReady(), EMOTE_GAS_SPORE, EMOTE_WARN_GAS_SPORE, EMOTE_WARN_PUNGENT_BLIGHT, EVENT_BERSERK, EVENT_FESTERGUT_GOO, EVENT_GAS_SPORE, EVENT_GASTRIC_BLOAT, EVENT_INHALE_BLIGHT, EVENT_VILE_GAS, gaseousBlight, ObjectAccessor::GetCreature(), Object::GetGUID(), InstanceScript::GetGuidData(), Unit::GetVictim(), Unit::HasUnitState(), BossAI::instance, ScriptedAI::me, RemoveBlight(), SAY_BERSERK, SAY_PUNGENT_BLIGHT, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), UnitAI::SelectTargetList(), SPELL_BERSERK2, SPELL_GAS_SPORE, SPELL_GASTRIC_BLOAT, SPELL_INHALE_BLIGHT, SPELL_MALLABLE_GOO_H, SPELL_PUNGENT_BLIGHT, SPELL_VILE_GAS, SPELLVALUE_MAX_TARGETS, CreatureAI::Talk(), UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
_gasDummyGUID
ObjectGuid boss_festergut::boss_festergutAI::_gasDummyGUID
Definition at line 93 of file boss_festergut.cpp.
Referenced by boss_festergutAI(), EnterCombat(), RemoveBlight(), and Reset().
_inhaleCounter
uint32 boss_festergut::boss_festergutAI::_inhaleCounter
Definition at line 95 of file boss_festergut.cpp.
Referenced by Reset(), and UpdateAI().
_maxInoculatedStack
uint32 boss_festergut::boss_festergutAI::_maxInoculatedStack
Definition at line 94 of file boss_festergut.cpp.
Referenced by GetData(), Reset(), and SetData().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_festergut.cpp