Azerotcore-wotlk: G3D::TextOutput Class Reference
G3D::TextOutput Class Reference
#include <TextOutput.h>
Classes
class Settings
Public Member Functions
TextOutput (const std::string &filename, const Settings &options=Settings())
TextOutput (const Settings &options=Settings())
int line () const
void commit (bool flush=true)
void commitString (std::string &string)
void pushIndent ()
void popIndent ()
std::string commitString ()
void writeString (const std::string &string)
void writeBoolean (bool b)
void writeNumber (double n)
void writeNumber (int n)
void writeNewline ()
void writeNewlines (int numLines)
bool deleteSpace ()
void writeSymbol (const std::string &string)
void writeSymbol (char s)
void writeSymbols (const std::string &a, const std::string &b="", const std::string &c="", const std::string &d="", const std::string &e="", const std::string &f="")
void __cdecl printf (const char *fmt,...) G3D_CHECK_PRINTF_METHOD_ARGS
void __cdecl printf (const std::string fmt,...)
void __cdecl vprintf (const char *fmt, va_list argPtr) G3D_CHECK_VPRINTF_METHOD_ARGS
Private Member Functions
void setIndentLevel (int i)
void setOptions (const Settings &_opt)
void convertNewlines (const std::string &in, std::string &out)
void wordWrapIndentAppend (const std::string &str)
void indentAppend (char c)
Private Attributes
bool startingNewLine
int currentColumn
bool inDQuote
std::string filename
Array< char > data
Settings option
int indentLevel
int indentSpaces
std::string newline
int m_currentLine
Detailed Description
Convenient formatting of ASCII text written to a file.
The core writeString, writeNumber, and writeSymbol methods map to TextInput's methods. Number and Symbol each print an additional space that is used to separate adjacent tokens.
TextOutput::printf allows arbitrary text to be conveniently dumped en-masse. Use [de]serialize(bool, TextOutput) and other overloads to read/write primitive types in a standardized manner and
When a word-wrap line break occurs, all whitespace between words is replaced with a single newline (the newline may be two characters– see G3D::TextOutput::Options::NewlineStyle). Word wrapping occurs against the number of columns specified by Options::numColumns, minus the current indent level.
Indenting adds the specified number of spaces immediately after a newline. If a newline was followed by spaces in the original string, these are added to the indent spaces. Indenting will indent blank lines and will leave indents after the last newline of a file (if the indent level is non-zero at the end).
Serialization/Marshalling
Text serialization is accomplished using TextOutput by defining the pair of methods:
void serialize(TextOutput& to) const;
void deserialize(TextInput& ti);
See also G3D::TextInput.
BETA API
This API is subject to change in future versions.
Definition at line 60 of file TextOutput.h.
Constructor & Destructor Documentation
TextOutput() [1/2]
G3D::TextOutput::TextOutput (const std::string & filename, const Settings & options = Settings()) explicit
Definition at line 31 of file TextOutput.cpp.
                                                                           :
     startingNewLine(true),
     currentColumn(0),
     inDQuote(false),
     filename(fil),
     indentLevel(0),
     m_currentLine(0)
 {
     setOptions(opt);
 }
References setOptions().
TextOutput() [2/2]
G3D::TextOutput::TextOutput (const Settings & options = Settings()) explicit
Constructs a text output that can later be commited to a string instead of a file.
Definition at line 19 of file TextOutput.cpp.
                                                     :
     startingNewLine(true),
     currentColumn(0),
     inDQuote(false),
     filename(""),
     indentLevel(0),
     m_currentLine(0)
 {
     setOptions(opt);
 }
References setOptions().
Member Function Documentation
commit()
void G3D::TextOutput::commit (bool flush = true)
Commit to the filename specified on the constructor. Not called from the destructor; you must call it yourself.
Parameters
flush If true (default) the file is ready for reading when the method returns, otherwise the method returns immediately and writes the file in the background.
Definition at line 419 of file TextOutput.cpp.
{
     std::string p = filenamePath(filename);
     if (! FileSystem::exists(p, false)) {
         FileSystem::createDirectory(p);
     }
     FILE* f = FileSystem::fopen(filename.c_str(), "wb");
     debugAssertM(f, "Could not open \"" + filename + "\"");
     fwrite(data.getCArray(), 1, data.size(), f);
     if (flush) {
         fflush(f);
     }
     FileSystem::fclose(f);
 }
References G3D::FileSystem::createDirectory(), debugAssertM, G3D::FileSystem::exists(), f(), G3D::FileSystem::fclose(), filename, G3D::filenamePath(), and G3D::FileSystem::fopen().
Referenced by G3D::Any::save(), and G3D::AnyVal::save().
commitString() [1/2]
std::string G3D::TextOutput::commitString ()
Produces a new string that contains the output
Definition at line 443 of file TextOutput.cpp.
{
     std::string str;
     commitString(str);
     return str;
 }
commitString() [2/2]
void G3D::TextOutput::commitString (std::string & string)
Commits to this string
Definition at line 435 of file TextOutput.cpp.
{
     // Null terminate
     data.push('\0');
     out = data.getCArray();
     data.pop();
 }
Referenced by G3D::NetworkDevice::describeSystem(), G3D::System::describeSystem(), G3D::GImage::encodePPMASCII(), G3D::AnyVal::toString(), G3D::Any::unparse(), G3D::XML::unparse(), and G3D::Any::unparseJSON().
convertNewlines()
void G3D::TextOutput::convertNewlines (const std::string & in, std::string & out) private
Converts to the desired newlines. Called from vprintf
Definition at line 193 of file TextOutput.cpp.
{
     // TODO: can be significantly optimized in cases where
     // single characters are copied in order by walking through
     // the array and copying substrings as needed.
     if (option.convertNewlines) {
         out = "";
         for (uint32 i = 0; i < in.size(); ++i) {
             if (in[i] == '\n') {
                 // Unix newline
                 out += newline;
             } else if ((in[i] == '\r') && (i + 1 < in.size()) && (in[i + 1] == '\n')) {
                 // Windows newline
                 out += newline;
                 ++i;
             } else {
                 out += in[i];
             }
         }
     } else {
         out = in;
     }
 }
References G3D::TextOutput::Settings::convertNewlines, newline, and option.
Referenced by vprintf().
deleteSpace()
bool G3D::TextOutput::deleteSpace ()
If the most recently written character was a space, remove it and return true. Can be called repeatedly to back up over multiple spaces.
Definition at line 182 of file TextOutput.cpp.
{
     if ((currentColumn > 0) && (data.last() == ' ')) {
         data.popDiscard();
         --currentColumn;
         return true;
     } else {
         return false;
     }
 }
References currentColumn.
Referenced by G3D::Any::serialize().
indentAppend()
void G3D::TextOutput::indentAppend (char c) private
Appends the character to data, indenting whenever a newline is encountered. Called from wordWrapIndentAppend
Definition at line 380 of file TextOutput.cpp.
{
     if (startingNewLine) {
         for (int j = 0; j < indentSpaces; ++j) {
             data.push(' ');
         }
         startingNewLine = false;
         currentColumn = indentSpaces;
     }
     data.push(c);
     // Don't increment the column count on return character
     // newline is taken care of below.
     if (c != '\r') {
         ++currentColumn;
     }
     if (c == '\"') {
         inDQuote = ! inDQuote;
     }
     startingNewLine = (c == '\n');
     if (startingNewLine) {
         currentColumn = 0;
         ++m_currentLine;
     }
 }
References mpq::c, currentColumn, indentSpaces, inDQuote, m_currentLine, and startingNewLine.
Referenced by wordWrapIndentAppend(), and writeNewline().
line()
int G3D::TextOutput::line () const inline
Returns one plus the number of newlines written since the output was created.
Definition at line 182 of file TextOutput.h.
                      {
         return m_currentLine;
     }
References m_currentLine.
Referenced by G3D::Any::serialize().
popIndent()
void G3D::TextOutput::popIndent ()
Definition at line 72 of file TextOutput.cpp.
{
     setIndentLevel(indentLevel - 1);
 }
References indentLevel, and setIndentLevel().
Referenced by G3D::NetworkDevice::EthernetAdapter::describe(), G3D::System::describeSystem(), G3D::NetworkDevice::describeSystem(), G3D::enumToJavaScriptDeclaration(), G3D::AnyVal::serialize(), G3D::Matrix::serialize(), G3D::XML::serialize(), and G3D::Any::serialize().
printf() [1/2]
void G3D::TextOutput::printf (const char * fmt, ...)
Normal printf conventions. Note that the output will be reformatted for word-wrapping and newlines
Definition at line 174 of file TextOutput.cpp.
{
     va_list argList;
     va_start(argList, formatString);
     this->vprintf(formatString, argList);
     va_end(argList);
 }
References vprintf().
Referenced by G3D::NetworkDevice::describeSystem(), G3D::GImage::encodePPMASCII(), G3D::enumToJavaScriptDeclaration(), G3D::AnyVal::serialize(), G3D::XML::serialize(), G3D::Any::serialize(), writeBoolean(), writeNumber(), writeString(), and writeSymbol().
printf() [2/2]
void G3D::TextOutput::printf (const std::string fmt, ...)
Definition at line 166 of file TextOutput.cpp.
{
     va_list argList;
     va_start(argList, formatString);
     this->vprintf(formatString.c_str(), argList);
     va_end(argList);
 }
References vprintf().
pushIndent()
void G3D::TextOutput::pushIndent ()
Increase indent level by 1
Definition at line 67 of file TextOutput.cpp.
{
     setIndentLevel(indentLevel + 1);
 }
References indentLevel, and setIndentLevel().
Referenced by G3D::NetworkDevice::EthernetAdapter::describe(), G3D::System::describeSystem(), G3D::NetworkDevice::describeSystem(), G3D::enumToJavaScriptDeclaration(), G3D::AnyVal::serialize(), G3D::Matrix::serialize(), G3D::XML::serialize(), and G3D::Any::serialize().
setIndentLevel()
void G3D::TextOutput::setIndentLevel (int i) private
Definition at line 44 of file TextOutput.cpp.
{
     indentLevel = i;
     // If there were more pops than pushes, don't let that take us below 0 indent.
     // Don't ever indent more than the number of columns.
     indentSpaces =
         iClamp(option.spacesPerIndent * indentLevel,
                0,
                option.numColumns - 1);
 }
References G3D::iClamp(), indentLevel, indentSpaces, G3D::TextOutput::Settings::numColumns, option, and G3D::TextOutput::Settings::spacesPerIndent.
Referenced by popIndent(), pushIndent(), and setOptions().
setOptions()
void G3D::TextOutput::setOptions (const Settings & _opt) private
Definition at line 56 of file TextOutput.cpp.
{
     option = _opt;
     debugAssert(option.numColumns > 1);
     setIndentLevel(indentLevel);
     newline = (option.newlineStyle == Settings::NEWLINE_WINDOWS) ? "\r\n" : "\n";
 }
References debugAssert, indentLevel, newline, G3D::TextOutput::Settings::NEWLINE_WINDOWS, G3D::TextOutput::Settings::newlineStyle, G3D::TextOutput::Settings::numColumns, option, and setIndentLevel().
Referenced by TextOutput().
vprintf()
void G3D::TextOutput::vprintf (const char * fmt, va_list argPtr)
Definition at line 410 of file TextOutput.cpp.
{
     const std::string& str = vformat(formatString, argPtr);
     std::string clean;
     convertNewlines(str, clean);
     wordWrapIndentAppend(clean);
 }
References convertNewlines(), G3D::vformat(), and wordWrapIndentAppend().
Referenced by printf().
wordWrapIndentAppend()
void G3D::TextOutput::wordWrapIndentAppend (const std::string & str) private
Called from vprintf
Definition at line 232 of file TextOutput.cpp.
{
     // TODO: keep track of the last space character we saw so we don't
     // have to always search.
     if ((option.wordWrap == Settings::WRAP_NONE) ||
         (currentColumn + (int)str.size() <= option.numColumns)) {
         // No word-wrapping is needed
         // Add one character at a time.
         // TODO: optimize for strings without newlines to add multiple
         // characters.
         for (uint32 i = 0; i < str.size(); ++i) {
             indentAppend(str[i]);
         }
         return;
     }
     // Number of columns to wrap against
     int cols = option.numColumns - indentSpaces;
     // Copy forward until we exceed the column size,
     // and then back up and try to insert newlines as needed.
     for (uint32 i = 0; i < str.size(); ++i) {
         indentAppend(str[i]);
         if ((str[i] == '\r') && (i + 1 < str.size()) && (str[i + 1] == '\n')) {
             // \r\n, we need to hit the \n to enter word wrapping.
             ++i;
             indentAppend(str[i]);
         }
         if (currentColumn >= cols) {
             debugAssertM(str[i] != '\n' && str[i] != '\r',
                 "Should never enter word-wrapping on a newline character");
             // True when we're allowed to treat a space as a space.
             bool unquotedSpace = option.allowWordWrapInsideDoubleQuotes || ! inDQuote;
             // Cases:
             //
             // 1. Currently in a series of spaces that ends with a newline
             //     strip all spaces and let the newline
             //     flow through.
             //
             // 2. Currently in a series of spaces that does not end with a newline
             //     strip all spaces and replace them with single newline
             //
             // 3. Not in a series of spaces
             //     search backwards for a space, then execute case 2.
             // Index of most recent space
             size_t lastSpace = data.size() - 1;
             // How far back we had to look for a space
             size_t k = 0;
             size_t maxLookBackward = currentColumn - indentSpaces;
             // Search backwards (from current character), looking for a space.
             while ((k < maxLookBackward) &&
                    (lastSpace > 0) &&
                    (! ((data[(int)lastSpace] == ' ') && unquotedSpace))) {
                 --lastSpace;
                 ++k;
                 if ((data[(int)lastSpace] == '\"') && !option.allowWordWrapInsideDoubleQuotes) {
                     unquotedSpace = ! unquotedSpace;
                 }
             }
             if (k == maxLookBackward) {
                 // We couldn't find a series of spaces
                 if (option.wordWrap == Settings::WRAP_ALWAYS) {
                     // Strip the last character we wrote, force a newline,
                     // and replace the last character;
                     data.pop();
                     writeNewline();
                     indentAppend(str[i]);
                 } else {
                     // Must be Settings::WRAP_WITHOUT_BREAKING
                     //
                     // Don't write the newline; we'll come back to
                     // the word wrap code after writing another character
                 }
             } else {
                 // We found a series of spaces.  If they continue
                 // to the new string, strip spaces off both.  Otherwise
                 // strip spaces from data only and insert a newline.
                 // Find the start of the spaces.  firstSpace is the index of the
                 // first non-space, looking backwards from lastSpace.
                 size_t firstSpace = lastSpace;
                 while ((k < maxLookBackward) &&
                     (firstSpace > 0) &&
                        (data[(int)firstSpace] == ' ')) {
                     --firstSpace;
                     ++k;
                 }
                 if (k == maxLookBackward) {
                     ++firstSpace;
                 }
                 if (lastSpace == (uint32)data.size() - 1) {
                     // Spaces continued up to the new string
                     data.resize(firstSpace + 1);
                     writeNewline();
                     // Delete the spaces from the new string
                     while ((i < str.size() - 1) && (str[i + 1] == ' ')) {
                         ++i;
                     }
                 } else {
                     // Spaces were somewhere in the middle of the old string.
                     // replace them with a newline.
                     // Copy over the characters that should be saved
                     Array<char> temp;
                     for (size_t j = lastSpace + 1; j < (uint32)data.size(); ++j) {
                         char c = data[(int)j];
                         if (c == '\"') {
                             // Undo changes to quoting (they will be re-done
                             // when we paste these characters back on).
                             inDQuote = !inDQuote;
                         }
                         temp.append(c);
                     }
                     // Remove those characters and replace with a newline.
                     data.resize(firstSpace + 1);
                     writeNewline();
                     // Write them back
                     for (size_t j = 0; j < (uint32)temp.size(); ++j) {
                         indentAppend(temp[(int)j]);
                     }
                     // We are now free to continue adding from the
                     // new string, which may or may not begin with spaces.
                 } // if spaces included new string
             } // if hit indent
         } // if line exceeded
     } // iterate over str
 }
References G3D::TextOutput::Settings::allowWordWrapInsideDoubleQuotes, G3D::Array< T, MIN_ELEMENTS >::append(), mpq::c, currentColumn, debugAssertM, indentAppend(), indentSpaces, inDQuote, G3D::TextOutput::Settings::numColumns, option, G3D::Array< T, MIN_ELEMENTS >::size(), G3D::TextOutput::Settings::wordWrap, G3D::TextOutput::Settings::WRAP_ALWAYS, G3D::TextOutput::Settings::WRAP_NONE, and writeNewline().
Referenced by vprintf().
writeBoolean()
void G3D::TextOutput::writeBoolean (bool b)
Definition at line 125 of file TextOutput.cpp.
{
     this->printf("%s ", b ? option.trueSymbol.c_str() : option.falseSymbol.c_str());
 }
References G3D::TextOutput::Settings::falseSymbol, option, printf(), and G3D::TextOutput::Settings::trueSymbol.
Referenced by G3D::AnyVal::serialize(), and G3D::Any::serialize().
writeNewline()
void G3D::TextOutput::writeNewline ()
Definition at line 218 of file TextOutput.cpp.
{
     for (uint32 i = 0; i < newline.size(); ++i) {
         indentAppend(newline[i]);
     }
 }
References indentAppend(), and newline.
Referenced by G3D::NetworkDevice::EthernetAdapter::describe(), G3D::System::describeSystem(), G3D::NetworkDevice::describeSystem(), G3D::enumToJavaScriptDeclaration(), G3D::Matrix::serialize(), G3D::XML::serialize(), G3D::Any::serialize(), G3D::var(), wordWrapIndentAppend(), and writeNewlines().
writeNewlines()
void G3D::TextOutput::writeNewlines (int numLines)
Definition at line 225 of file TextOutput.cpp.
{
     for (int i = 0; i < numLines; ++i) {
         writeNewline();
     }
 }
References writeNewline().
writeNumber() [1/2]
void G3D::TextOutput::writeNumber (double n)
Definition at line 129 of file TextOutput.cpp.
{
     this->printf("%g ", n);
 }
References printf().
Referenced by G3D::GUniqueID::serialize(), G3D::Vector2::serialize(), G3D::Vector3::serialize(), G3D::serialize(), G3D::Matrix::serialize(), G3D::Any::serialize(), and G3D::var().
writeNumber() [2/2]
void G3D::TextOutput::writeNumber (int n)
Definition at line 134 of file TextOutput.cpp.
{
     this->printf("%d ", n);
 }
References printf().
writeString()
void G3D::TextOutput::writeString (const std::string & string)
Writes a quoted string. Special characters in the string (e.g., \, \t, \n) are escaped so that TextInput will produce the identical string on reading.
Definition at line 112 of file TextOutput.cpp.
{
     // Never break a line in a string
     const Settings::WordWrapMode old = option.wordWrap;
     if (! option.allowWordWrapInsideDoubleQuotes) {
         option.wordWrap = Settings::WRAP_NONE;
     }
     // Convert special characters to escape sequences
     this->printf("\"%s\"", escape(string).c_str());
     option.wordWrap = old;
 }
References G3D::TextOutput::Settings::allowWordWrapInsideDoubleQuotes, G3D::escape(), option, printf(), G3D::TextOutput::Settings::wordWrap, and G3D::TextOutput::Settings::WRAP_NONE.
Referenced by G3D::NetworkDevice::EthernetAdapter::describe(), G3D::AnyVal::serialize(), G3D::Any::serialize(), and G3D::var().
writeSymbol() [1/2]
void G3D::TextOutput::writeSymbol (char s)
Definition at line 145 of file TextOutput.cpp.
{
     this->printf("%c ", c);
 }
References printf().
writeSymbol() [2/2]
void G3D::TextOutput::writeSymbol (const std::string & string)
The symbol is written without quotes. Symbols are required to begin with a letter or underscore and contain only letters, underscores, and numbers or be a C++ symbol (e.g. "{", "(", "++", etc.) so that they may be properly parsed by TextInput::readSymbol. Symbols are printed with a trailing space.
Definition at line 139 of file TextOutput.cpp.
{
     if (string.size() > 0) {
         this->printf("%s ", string.c_str());
     }
 }
References printf().
Referenced by G3D::NetworkDevice::EthernetAdapter::describe(), G3D::GUniqueID::serialize(), G3D::Vector2::serialize(), G3D::Vector3::serialize(), G3D::serialize(), G3D::AnyVal::serialize(), G3D::Matrix::serialize(), G3D::XML::serialize(), G3D::Any::serialize(), and writeSymbols().
writeSymbols()
void G3D::TextOutput::writeSymbols (const std::string & a, const std::string & b = "", const std::string & c = "", const std::string & d = "", const std::string & e = "", const std::string & f = "")
Convenient idiom for writing multiple symbols in a row, e.g. writeSymbols("name", "="); The empty symbols are not written.
Definition at line 149 of file TextOutput.cpp.
{
     writeSymbol(a);
     writeSymbol(b);
     writeSymbol(c);
     writeSymbol(d);
     writeSymbol(e);
     writeSymbol(f);
 }
References mpq::a, b, mpq::c, mpq::d, f(), and writeSymbol().
Referenced by G3D::NetworkDevice::EthernetAdapter::describe(), G3D::System::describeSystem(), G3D::NetworkDevice::describeSystem(), G3D::Any::serialize(), and G3D::var().
Member Data Documentation
currentColumn
int G3D::TextOutput::currentColumn private
Number of characters at the end of the buffer since the last newline
Definition at line 136 of file TextOutput.h.
Referenced by deleteSpace(), indentAppend(), and wordWrapIndentAppend().
data
Array<char> G3D::TextOutput::data private
Definition at line 144 of file TextOutput.h.
filename
std::string G3D::TextOutput::filename private
Empty if there is none
Definition at line 142 of file TextOutput.h.
Referenced by commit().
indentLevel
int G3D::TextOutput::indentLevel private
Number of indents to prepend before each line. Always set using setIndentLevel.
Definition at line 149 of file TextOutput.h.
Referenced by popIndent(), pushIndent(), setIndentLevel(), and setOptions().
indentSpaces
int G3D::TextOutput::indentSpaces private
Actual number of spaces to indent.
Definition at line 154 of file TextOutput.h.
Referenced by indentAppend(), setIndentLevel(), and wordWrapIndentAppend().
inDQuote
bool G3D::TextOutput::inDQuote private
True if we have seen an open " and no close ".
Definition at line 139 of file TextOutput.h.
Referenced by indentAppend(), and wordWrapIndentAppend().
m_currentLine
int G3D::TextOutput::m_currentLine private
Starts at 1
Definition at line 160 of file TextOutput.h.
Referenced by indentAppend(), and line().
newline
std::string G3D::TextOutput::newline private
the newline character(s)
Definition at line 157 of file TextOutput.h.
Referenced by convertNewlines(), setOptions(), and writeNewline().
option
Settings G3D::TextOutput::option private
Definition at line 146 of file TextOutput.h.
Referenced by convertNewlines(), setIndentLevel(), setOptions(), wordWrapIndentAppend(), writeBoolean(), and writeString().
startingNewLine
bool G3D::TextOutput::startingNewLine private
Used by indentAndAppend to tell when we are writing the first character of a new line.
So that push/popIndent work correctly, we cannot indent immediately after writing a newline. Instead we must indent on writing the first character after that newline.
Definition at line 133 of file TextOutput.h.
Referenced by indentAppend().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/TextOutput.h
deps/g3dlite/source/TextOutput.cpp