Azerotcore-wotlk: boss_headless_horseman::boss_headless_horsemanAI Struct Reference
boss_headless_horseman::boss_headless_horsemanAI Struct Reference
Public Member Functions
boss_headless_horsemanAI (Creature *creature)
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void DoAction (int32 param) override
void SpellHitTarget (Unit *target, const SpellInfo *spellInfo) override
void SpellHit (Unit *, const SpellInfo *spellInfo) override
void MovementInform (uint32 type, uint32 point) override
Player * GetRhymePlayer ()
void EnterCombat (Unit *) override
void MoveInLineOfSight (Unit *) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void JustSummoned (Creature *cr) override
void Reset () override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void SummonedCreatureDespawn (Creature *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
SummonList summons
ObjectGuid playerGUID
uint8 talkCount
bool inFight
uint8 phase
uint32 health
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1093 of file hallows_end.cpp.
Constructor & Destructor Documentation
boss_headless_horsemanAI()
boss_headless_horseman::boss_headless_horsemanAI::boss_headless_horsemanAI (Creature * creature) inline
Definition at line 1095 of file hallows_end.cpp.
                                                      : ScriptedAI(creature), summons(me)
         {
         }
Member Function Documentation
DamageTaken()
void boss_headless_horseman::boss_headless_horsemanAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1189 of file hallows_end.cpp.
         {
             // We die... :(
             if (damage >= me->GetHealth())
             {
                 damage = 0;
                 me->RemoveAura(SPELL_HEAD_VISUAL);
                 me->CastSpell(me, SPELL_HORSEMAN_IMMUNITY, true);
                 me->CastSpell(me, SPELL_HORSEMAN_BODY_REGEN, true);
                 me->CastSpell(me, SPELL_HORSEMAN_BODY_REGEN_CONFUSE, true);
                 events.CancelEvent(EVENT_HORSEMAN_CLEAVE);
                 // Summon Head
                 Position pos = me->GetNearPosition(15.0f, rand_norm() * 2 * M_PI);
                 if (Creature* cr = me->SummonCreature(NPC_HORSEMAN_HEAD, pos))
                 {
                     if (health)
                         cr->SetHealth(health);
                     me->CastSpell(cr, SPELL_THROW_HEAD, true);
                     cr->CastSpell(cr, SPELL_HORSEMAN_BODY_PHASE + phase, true);
                     if (phase < 2)
                         phase++;
                     events.ScheduleEvent(EVENT_HORSEMAN_WHIRLWIND, 6000);
                     events.ScheduleEvent(EVENT_HORSEMAN_CHECK_HEALTH, 1000);
                 }
             }
         }
References Unit::CastSpell(), EVENT_HORSEMAN_CHECK_HEALTH, EVENT_HORSEMAN_CLEAVE, EVENT_HORSEMAN_WHIRLWIND, Unit::GetHealth(), WorldObject::GetNearPosition(), health, ScriptedAI::me, NPC_HORSEMAN_HEAD, rand_norm(), Unit::RemoveAura(), SPELL_HEAD_VISUAL, SPELL_HORSEMAN_BODY_PHASE, SPELL_HORSEMAN_BODY_REGEN, SPELL_HORSEMAN_BODY_REGEN_CONFUSE, SPELL_HORSEMAN_IMMUNITY, SPELL_THROW_HEAD, and WorldObject::SummonCreature().
DoAction()
void boss_headless_horseman::boss_headless_horsemanAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 1128 of file hallows_end.cpp.
         {
             health = param;
         }
References health.
EnterCombat()
void boss_headless_horseman::boss_headless_horsemanAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1186 of file hallows_end.cpp.
 { me->SetInCombatWithZone(); }
References ScriptedAI::me, and Creature::SetInCombatWithZone().
GetRhymePlayer()
Player* boss_headless_horseman::boss_headless_horsemanAI::GetRhymePlayer () inline
Definition at line 1184 of file hallows_end.cpp.
 { return playerGUID ? ObjectAccessor::GetPlayer(*me, playerGUID) : nullptr; }
References ObjectAccessor::GetPlayer(), ScriptedAI::me, and playerGUID.
Referenced by UpdateAI().
JustDied()
void boss_headless_horseman::boss_headless_horsemanAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1107 of file hallows_end.cpp.
         {
             summons.DespawnAll();
             me->Say("This end have I reached before. What new adventure lies in store?", LANG_UNIVERSAL);
             me->PlayDirectSound(SOUND_DEATH);
             std::list<Creature*> unitList;
             me->GetCreaturesWithEntryInRange(unitList, 100.0f, NPC_PUMPKIN_FIEND);
             for (std::list<Creature*>::iterator itr = unitList.begin(); itr != unitList.end(); ++itr)
                 (*itr)->ToCreature()->DespawnOrUnsummon(500);
             Map::PlayerList const& players = me->GetMap()->GetPlayers();
             if (!players.isEmpty() && players.begin()->GetSource() && players.begin()->GetSource()->GetGroup())
                 sLFGMgr->FinishDungeon(players.begin()->GetSource()->GetGroup()->GetGUID(), lfg::LFG_DUNGEON_HEADLESS_HORSEMAN, me->FindMap());
         }
References MapRefMgr::begin(), SummonList::DespawnAll(), WorldObject::FindMap(), WorldObject::GetCreaturesWithEntryInRange(), WorldObject::GetMap(), Map::GetPlayers(), LinkedListHead::isEmpty(), LANG_UNIVERSAL, lfg::LFG_DUNGEON_HEADLESS_HORSEMAN, ScriptedAI::me, NPC_PUMPKIN_FIEND, WorldObject::PlayDirectSound(), Unit::Say(), sLFGMgr, SOUND_DEATH, and summons.
JustSummoned()
void boss_headless_horseman::boss_headless_horsemanAI::JustSummoned (Creature * cr) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1219 of file hallows_end.cpp.
 { summons.Summon(cr); }
References SummonList::Summon(), and summons.
KilledUnit()
void boss_headless_horseman::boss_headless_horsemanAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1122 of file hallows_end.cpp.
         {
             me->Yell("Your body lies beaten, battered and broken. Let my curse be your own, fate has spoken.", LANG_UNIVERSAL);
             me->PlayDirectSound(SOUND_SLAY);
         }
References LANG_UNIVERSAL, ScriptedAI::me, WorldObject::PlayDirectSound(), SOUND_SLAY, and Unit::Yell().
MoveInLineOfSight()
void boss_headless_horseman::boss_headless_horsemanAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 1187 of file hallows_end.cpp.
 {}
MovementInform()
void boss_headless_horseman::boss_headless_horsemanAI::MovementInform (uint32 type, uint32 point) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1165 of file hallows_end.cpp.
         {
             if (type == WAYPOINT_MOTION_TYPE)
             {
                 if (point == 0)
                     me->CastSpell(me, SPELL_HEAD_VISUAL, true);
                 else if (point == 11)
                 {
                     me->SetUInt32Value(UNIT_FIELD_FLAGS, 0);
                     me->StopMoving();
                     me->SetInCombatWithZone();
                     inFight = true;
                     events.ScheduleEvent(EVENT_HORSEMAN_FOLLOW, 500);
                     events.ScheduleEvent(EVENT_HORSEMAN_CLEAVE, 7000);
                 }
             }
         }
References Unit::CastSpell(), EVENT_HORSEMAN_CLEAVE, EVENT_HORSEMAN_FOLLOW, inFight, ScriptedAI::me, Creature::SetInCombatWithZone(), Object::SetUInt32Value(), SPELL_HEAD_VISUAL, Unit::StopMoving(), UNIT_FIELD_FLAGS, and WAYPOINT_MOTION_TYPE.
Reset()
void boss_headless_horseman::boss_headless_horsemanAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1221 of file hallows_end.cpp.
         {
             events.Reset();
             summons.DespawnAll();
             playerGUID.Clear();
             talkCount = 0;
             phase = 0;
             inFight = false;
             health = 0;
             me->SetDisableGravity(true);
             me->SetSpeed(MOVE_WALK, 5.0f, true);
         }
References ObjectGuid::Clear(), SummonList::DespawnAll(), health, inFight, ScriptedAI::me, MOVE_WALK, playerGUID, Creature::SetDisableGravity(), Unit::SetSpeed(), summons, and talkCount.
SpellHit()
void boss_headless_horseman::boss_headless_horsemanAI::SpellHit (Unit * , const SpellInfo * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1142 of file hallows_end.cpp.
         {
             if (spellInfo->Id == SPELL_THROW_HEAD_BACK)
             {
                 me->SetHealth(me->GetMaxHealth());
                 me->CastSpell(me, SPELL_HEAD_VISUAL, true);
                 me->RemoveAura(SPELL_HORSEMAN_IMMUNITY);
                 me->RemoveAura(SPELL_HORSEMAN_BODY_REGEN);
                 me->RemoveAura(SPELL_HORSEMAN_BODY_REGEN_CONFUSE);
                 me->RemoveAura(SPELL_HORSEMAN_WHIRLWIND);
                 events.CancelEvent(EVENT_HORSEMAN_CHECK_HEALTH);
                 events.CancelEvent(EVENT_HORSEMAN_WHIRLWIND);
                 events.CancelEvent(EVENT_HORSEMAN_CONFLAGRATION);
                 events.CancelEvent(EVENT_SUMMON_PUMPKIN);
                 me->Yell("Here's my body, fit and pure! Now, your blackened souls I'll cure!", LANG_UNIVERSAL);
                 if (phase == 1)
                     events.ScheduleEvent(EVENT_HORSEMAN_CONFLAGRATION, 6000);
                 else if (phase == 2)
                     events.ScheduleEvent(EVENT_SUMMON_PUMPKIN, 6000);
             }
         }
References Unit::CastSpell(), EVENT_HORSEMAN_CHECK_HEALTH, EVENT_HORSEMAN_CONFLAGRATION, EVENT_HORSEMAN_WHIRLWIND, EVENT_SUMMON_PUMPKIN, Unit::GetMaxHealth(), SpellInfo::Id, LANG_UNIVERSAL, ScriptedAI::me, Unit::RemoveAura(), Unit::SetHealth(), SPELL_HEAD_VISUAL, SPELL_HORSEMAN_BODY_REGEN, SPELL_HORSEMAN_BODY_REGEN_CONFUSE, SPELL_HORSEMAN_IMMUNITY, SPELL_HORSEMAN_WHIRLWIND, SPELL_THROW_HEAD_BACK, and Unit::Yell().
SpellHitTarget()
void boss_headless_horseman::boss_headless_horsemanAI::SpellHitTarget (Unit * target, const SpellInfo * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1133 of file hallows_end.cpp.
         {
             if (spellInfo->Id == SPELL_SUMMONING_RHYME_TARGET)
             {
                 playerGUID = target->GetGUID();
                 events.ScheduleEvent(EVENT_HH_PLAYER_TALK, 2000);
             }
         }
References EVENT_HH_PLAYER_TALK, Object::GetGUID(), SpellInfo::Id, playerGUID, and SPELL_SUMMONING_RHYME_TARGET.
UpdateAI()
void boss_headless_horseman::boss_headless_horsemanAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1235 of file hallows_end.cpp.
         {
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             if (inFight && !UpdateVictim())
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_HH_PLAYER_TALK:
                     {
                         talkCount++;
                         Player* player = GetRhymePlayer();
                         if (!player)
                             return;
                         switch (talkCount)
{
                             case 1:
                                 player->Say("Horseman rise...", LANG_UNIVERSAL);
                                 break;
                             case 2:
                                 player->Say("Your time is nigh...", LANG_UNIVERSAL);
                                 if (Creature* trigger = me->SummonTrigger(1765.28f, 1347.46f, 17.5514f, 0.0f, 15 * IN_MILLISECONDS))
                                     trigger->CastSpell(trigger, SPELL_EARTH_EXPLOSION, true);
                                 break;
                             case 3:
                                 me->GetMotionMaster()->MovePath(236820, false);
                                 me->CastSpell(me, SPELL_SHAKE_CAMERA_SMALL, true);
                                 player->Say("You felt death once...", LANG_UNIVERSAL);
                                 me->Say("It is over, your search is done. Let fate choose now, the righteous one.", LANG_UNIVERSAL);
                                 me->PlayDirectSound(SOUND_AGGRO);
                                 break;
                             case 4:
                                 me->CastSpell(me, SPELL_SHAKE_CAMERA_MEDIUM, true);
                                 player->Say("Now, know demise!", LANG_UNIVERSAL);
                                 talkCount = 0;
                                 return; // pop and return, skip repeat
                         }
                         events.RepeatEvent(2000);
                         break;
                     }
                 case EVENT_HORSEMAN_FOLLOW:
                     {
                         if (Player* player = GetRhymePlayer())
{
                             me->GetMotionMaster()->MoveIdle();
                             AttackStart(player);
                             me->GetMotionMaster()->MoveChase(player);
                         }
                         break;
                     }
                 case EVENT_HORSEMAN_CLEAVE:
                     {
                         me->CastSpell(me->GetVictim(), SPELL_HORSEMAN_CLEAVE, false);
                         events.RepeatEvent(8000);
                         break;
                     }
                 case EVENT_HORSEMAN_WHIRLWIND:
                     {
                         if (me->HasAuraEffect(SPELL_HORSEMAN_WHIRLWIND, EFFECT_0))
{
                             me->RemoveAura(SPELL_HORSEMAN_WHIRLWIND);
                             events.RepeatEvent(15000);
                             break;
                         }
                         me->CastSpell(me, SPELL_HORSEMAN_WHIRLWIND, true);
                         events.RepeatEvent(6000);
                         break;
                     }
                 case EVENT_HORSEMAN_CHECK_HEALTH:
                     {
                         if (me->GetHealth() == me->GetMaxHealth())
{
                             me->CastSpell(me, SPELL_BODY_RESTORED_INFO, true);
                             return;
                         }
                         events.RepeatEvent(1000);
                         break;
                     }
                 case EVENT_HORSEMAN_CONFLAGRATION:
                     {
                         if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
{
                             me->CastSpell(target, SPELL_HORSEMAN_CONFLAGRATION, false);
                             target->CastSpell(target, SPELL_HORSEMAN_CONFLAGRATION_SOUND, true);
                             me->Say("Harken, cur! Tis you I spurn! Now feel... the burn!", LANG_UNIVERSAL, target);
                         }
                         events.RepeatEvent(12500);
                         break;
                     }
                 case EVENT_SUMMON_PUMPKIN:
                     {
                         if (talkCount < 4)
{
                             events.RepeatEvent(1);
                             talkCount++;
                             me->CastSpell(me, SPELL_SUMMON_PUMPKIN, false);
                         }
                         else
{
                             me->Say("Soldiers arise, stand and fight! Bring victory at last to this fallen knight!", LANG_UNIVERSAL);
                             me->PlayDirectSound(SOUND_SPROUT);
                             events.RepeatEvent(15000);
                             talkCount = 0;
                         }
                         break;
                     }
             }
             if (inFight)
                 DoMeleeAttackIfReady();
         }
References ScriptedAI::AttackStart(), Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), EFFECT_0, EVENT_HH_PLAYER_TALK, EVENT_HORSEMAN_CHECK_HEALTH, EVENT_HORSEMAN_CLEAVE, EVENT_HORSEMAN_CONFLAGRATION, EVENT_HORSEMAN_FOLLOW, EVENT_HORSEMAN_WHIRLWIND, EVENT_SUMMON_PUMPKIN, Unit::GetHealth(), Unit::GetMaxHealth(), Unit::GetMotionMaster(), GetRhymePlayer(), Unit::GetVictim(), Unit::HasAuraEffect(), Unit::HasUnitState(), IN_MILLISECONDS, inFight, LANG_UNIVERSAL, ScriptedAI::me, MotionMaster::MoveChase(), MotionMaster::MoveIdle(), MotionMaster::MovePath(), WorldObject::PlayDirectSound(), Unit::RemoveAura(), Player::Say(), Unit::Say(), SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), SOUND_AGGRO, SOUND_SPROUT, SPELL_BODY_RESTORED_INFO, SPELL_EARTH_EXPLOSION, SPELL_HORSEMAN_CLEAVE, SPELL_HORSEMAN_CONFLAGRATION, SPELL_HORSEMAN_CONFLAGRATION_SOUND, SPELL_HORSEMAN_WHIRLWIND, SPELL_SHAKE_CAMERA_MEDIUM, SPELL_SHAKE_CAMERA_SMALL, SPELL_SUMMON_PUMPKIN, WorldObject::SummonTrigger(), talkCount, UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
events
EventMap boss_headless_horseman::boss_headless_horsemanAI::events
Definition at line 1099 of file hallows_end.cpp.
health
uint32 boss_headless_horseman::boss_headless_horsemanAI::health
Definition at line 1105 of file hallows_end.cpp.
Referenced by DamageTaken(), DoAction(), and Reset().
inFight
bool boss_headless_horseman::boss_headless_horsemanAI::inFight
Definition at line 1103 of file hallows_end.cpp.
Referenced by MovementInform(), Reset(), and UpdateAI().
phase
uint8 boss_headless_horseman::boss_headless_horsemanAI::phase
Definition at line 1104 of file hallows_end.cpp.
playerGUID
ObjectGuid boss_headless_horseman::boss_headless_horsemanAI::playerGUID
Definition at line 1101 of file hallows_end.cpp.
Referenced by GetRhymePlayer(), Reset(), and SpellHitTarget().
summons
SummonList boss_headless_horseman::boss_headless_horsemanAI::summons
Definition at line 1100 of file hallows_end.cpp.
Referenced by JustDied(), JustSummoned(), and Reset().
talkCount
uint8 boss_headless_horseman::boss_headless_horsemanAI::talkCount
Definition at line 1102 of file hallows_end.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Events/hallows_end.cpp