Azerotcore-wotlk: PreparedStatementData Struct Reference
PreparedStatementData Struct Reference
#include <PreparedStatement.h>
Static Public Member Functions
template<typename T >
static std::string ToString (T value)
static std::string ToString (bool value)
static std::string ToString (uint8 value)
static std::string ToString (int8 value)
static std::string ToString (std::string const &value)
static std::string ToString (std::vector< uint8 > const &value)
static std::string ToString (std::nullptr_t)
Public Attributes
std::variant< bool, uint8, uint16, uint32, uint64, int8, int16, int32, int64, float, double, std::string, std::vector< uint8 >, std::nullptr_t > data
Detailed Description
Definition at line 27 of file PreparedStatement.h.
Member Function Documentation
ToString() [1/7]
std::string PreparedStatementData::ToString (bool value) static
Definition at line 162 of file PreparedStatement.cpp.
 {
     return ToString<uint32>(value);
 }
ToString() [2/7]
std::string PreparedStatementData::ToString (int8 value) static
Definition at line 176 of file PreparedStatement.cpp.
 {
     return ToString<int32>(value);
 }
ToString() [3/7]
std::string PreparedStatementData::ToString (std::nullptr_t) static
Definition at line 197 of file PreparedStatement.cpp.
 {
     return "NULL";
 }
ToString() [4/7]
std::string PreparedStatementData::ToString (std::string const & value) static
Definition at line 187 of file PreparedStatement.cpp.
 {
     return fmt::format("'{}'", value);
 }
References format().
ToString() [5/7]
std::string PreparedStatementData::ToString (std::vector< uint8 > const & value) static
Definition at line 192 of file PreparedStatement.cpp.
 {
     return "BINARY";
 }
ToString() [6/7]
template<typename T > std::string PreparedStatementData::ToString (T value) static
Definition at line 157 of file PreparedStatement.cpp.
 {
     return fmt::format("{}", value);
 }
References format().
Referenced by MySQLPreparedStatement::getQueryString().
ToString() [7/7]
std::string PreparedStatementData::ToString (uint8 value) static
Definition at line 167 of file PreparedStatement.cpp.
 {
     return ToString<uint32>(value);
 }
Member Data Documentation
data
std::variant< bool, uint8, uint16, uint32, uint64, int8, int16, int32, int64, float, double, std::string, std::vector<uint8>, std::nullptr_t > PreparedStatementData::data
Definition at line 44 of file PreparedStatement.h.
The documentation for this struct was generated from the following files:
src/server/database/Database/PreparedStatement.h
src/server/database/Database/PreparedStatement.cpp