Azerotcore-wotlk: deps/argon2/argon2/blake2/blake2-impl.h File Reference
blake2-impl.h File Reference
#include <stdint.h>
#include <string.h>
Macros
#define BLAKE2_INLINE
Functions
static BLAKE2_INLINE uint32_t load32 (const void *src)
static BLAKE2_INLINE uint64_t load64 (const void *src)
static BLAKE2_INLINE void store32 (void *dst, uint32_t w)
static BLAKE2_INLINE void store64 (void *dst, uint64_t w)
static BLAKE2_INLINE uint64_t load48 (const void *src)
static BLAKE2_INLINE void store48 (void *dst, uint64_t w)
static BLAKE2_INLINE uint32_t rotr32 (const uint32_t w, const unsigned c)
static BLAKE2_INLINE uint64_t rotr64 (const uint64_t w, const unsigned c)
void clear_internal_memory (void *v, size_t n)
Macro Definition Documentation
BLAKE2_INLINE
#define BLAKE2_INLINE
Definition at line 29 of file blake2-impl.h.
Function Documentation
clear_internal_memory()
void clear_internal_memory (void * v, size_t n)
Definition at line 149 of file core.c.
{
   if (FLAG_clear_internal_memory && v) {
     secure_wipe_memory(v, n);
   }
 }
References FLAG_clear_internal_memory, and secure_wipe_memory().
Referenced by argon2_hash(), blake2b(), blake2b_final(), blake2b_init_key(), blake2b_invalidate_state(), and blake2b_long().
load32()
static BLAKE2_INLINE uint32_t load32 (const void * src) static
Definition at line 48 of file blake2-impl.h.
{
 #if defined(NATIVE_LITTLE_ENDIAN)
     uint32_t w;
     memcpy(&w, src, sizeof w);
     return w;
 #else
     const uint8_t *p = (const uint8_t *)src;
     uint32_t w = *p++;
     w |= (uint32_t)(*p++) << 8;
     w |= (uint32_t)(*p++) << 16;
     w |= (uint32_t)(*p++) << 24;
     return w;
 #endif
 }
References memcpy.
load48()
static BLAKE2_INLINE uint64_t load48 (const void * src) static
Definition at line 120 of file blake2-impl.h.
{
     const uint8_t *p = (const uint8_t *)src;
     uint64_t w = *p++;
     w |= (uint64_t)(*p++) << 8;
     w |= (uint64_t)(*p++) << 16;
     w |= (uint64_t)(*p++) << 24;
     w |= (uint64_t)(*p++) << 32;
     w |= (uint64_t)(*p++) << 40;
     return w;
 }
load64()
static BLAKE2_INLINE uint64_t load64 (const void * src) static
Definition at line 63 of file blake2-impl.h.
{
 #if defined(NATIVE_LITTLE_ENDIAN)
     uint64_t w;
     memcpy(&w, src, sizeof w);
     return w;
 #else
     const uint8_t *p = (const uint8_t *)src;
     uint64_t w = *p++;
     w |= (uint64_t)(*p++) << 8;
     w |= (uint64_t)(*p++) << 16;
     w |= (uint64_t)(*p++) << 24;
     w |= (uint64_t)(*p++) << 32;
     w |= (uint64_t)(*p++) << 40;
     w |= (uint64_t)(*p++) << 48;
     w |= (uint64_t)(*p++) << 56;
     return w;
 #endif
 }
References memcpy.
Referenced by blake2b_compress(), blake2b_init_param(), and load_block().
rotr32()
static BLAKE2_INLINE uint32_t rotr32 (const uint32_t w, const unsigned c) static
Definition at line 146 of file blake2-impl.h.
{
     return (w >> c) | (w << (32 - c));
 }
References mpq::c.
rotr64()
static BLAKE2_INLINE uint64_t rotr64 (const uint64_t w, const unsigned c) static
Definition at line 150 of file blake2-impl.h.
{
     return (w >> c) | (w << (64 - c));
 }
References mpq::c.
store32()
static BLAKE2_INLINE void store32 (void * dst, uint32_t w) static
Definition at line 82 of file blake2-impl.h.
{
 #if defined(NATIVE_LITTLE_ENDIAN)
     memcpy(dst, &w, sizeof w);
 #else
     uint8_t *p = (uint8_t *)dst;
     *p++ = (uint8_t)w;
     w >>= 8;
     *p++ = (uint8_t)w;
     w >>= 8;
     *p++ = (uint8_t)w;
     w >>= 8;
     *p++ = (uint8_t)w;
 #endif
 }
References memcpy.
Referenced by blake2b_long(), fill_first_blocks(), and initial_hash().
store48()
static BLAKE2_INLINE void store48 (void * dst, uint64_t w) static
Definition at line 131 of file blake2-impl.h.
{
     uint8_t *p = (uint8_t *)dst;
     *p++ = (uint8_t)w;
     w >>= 8;
     *p++ = (uint8_t)w;
     w >>= 8;
     *p++ = (uint8_t)w;
     w >>= 8;
     *p++ = (uint8_t)w;
     w >>= 8;
     *p++ = (uint8_t)w;
     w >>= 8;
     *p++ = (uint8_t)w;
 }
store64()
static BLAKE2_INLINE void store64 (void * dst, uint64_t w) static
Definition at line 97 of file blake2-impl.h.
{
 #if defined(NATIVE_LITTLE_ENDIAN)
     memcpy(dst, &w, sizeof w);
 #else
     uint8_t *p = (uint8_t *)dst;
     *p++ = (uint8_t)w;
     w >>= 8;
     *p++ = (uint8_t)w;
     w >>= 8;
     *p++ = (uint8_t)w;
     w >>= 8;
     *p++ = (uint8_t)w;
     w >>= 8;
     *p++ = (uint8_t)w;
     w >>= 8;
     *p++ = (uint8_t)w;
     w >>= 8;
     *p++ = (uint8_t)w;
     w >>= 8;
     *p++ = (uint8_t)w;
 #endif
 }
References memcpy.
Referenced by blake2b_final(), and store_block().