Azerotcore-wotlk: EscortMovementGenerator< T > Class Template Reference
EscortMovementGenerator< T > Class Template Reference
#include <EscortMovementGenerator.h>
Public Member Functions
EscortMovementGenerator (Movement::PointsArray *_path=nullptr)
void DoInitialize (T *)
void DoFinalize (T *)
void DoReset (T *)
bool DoUpdate (T *, uint32)
void unitSpeedChanged ()
MovementGeneratorType GetMovementGeneratorType ()
uint32 GetSplineId () const
Public Member Functions inherited from MovementGeneratorMedium< T, EscortMovementGenerator< T > >
void Initialize (Unit *u) override
void Finalize (Unit *u) override
void Reset (Unit *u) override
bool Update (Unit *u, uint32 time_diff) override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual bool GetResetPosition (float &, float &, float &)
Private Attributes
bool i_recalculateSpeed
Movement::PointsArray m_precomputedPath
uint32 _splineId
Detailed Description
template<class T>
class EscortMovementGenerator< T >
Definition at line 24 of file EscortMovementGenerator.h.
Constructor & Destructor Documentation
EscortMovementGenerator()
template<class T > EscortMovementGenerator< T >::EscortMovementGenerator (Movement::PointsArray * _path = nullptr) inline
Definition at line 27 of file EscortMovementGenerator.h.
                                                                   : i_recalculateSpeed(false)
     {
         if (_path)
             m_precomputedPath = *_path;
     }
References EscortMovementGenerator< T >::m_precomputedPath.
Member Function Documentation
DoFinalize()
template<class T > template void EscortMovementGenerator< T >::DoFinalize (T *)
Definition at line 94 of file EscortMovementGenerator.cpp.
 {
     unit->ClearUnitState(UNIT_STATE_ROAMING | UNIT_STATE_ROAMING_MOVE);
 }
References UNIT_STATE_ROAMING, and UNIT_STATE_ROAMING_MOVE.
DoInitialize()
template<class T > template void EscortMovementGenerator< T >::DoInitialize (T *)
Definition at line 28 of file EscortMovementGenerator.cpp.
 {
     if (!unit->IsStopped())
         unit->StopMoving();
     unit->AddUnitState(UNIT_STATE_ROAMING | UNIT_STATE_ROAMING_MOVE);
     i_recalculateSpeed = false;
     Movement::MoveSplineInit init(unit);
     if (m_precomputedPath.size() == 2) // xinef: simple case, just call move to
         init.MoveTo(m_precomputedPath[1].x, m_precomputedPath[1].y, m_precomputedPath[1].z, true);
     else if (m_precomputedPath.size())
         init.MovebyPath(m_precomputedPath);
     init.Launch();
     _splineId = unit->movespline->GetId();
 }
References Movement::MoveSplineInit::Launch(), Movement::MoveSplineInit::MovebyPath(), Movement::MoveSplineInit::MoveTo(), UNIT_STATE_ROAMING, and UNIT_STATE_ROAMING_MOVE.
DoReset()
template<class T > template void EscortMovementGenerator< T >::DoReset (T *)
Definition at line 100 of file EscortMovementGenerator.cpp.
 {
     if (!unit->IsStopped())
         unit->StopMoving();
     unit->AddUnitState(UNIT_STATE_ROAMING | UNIT_STATE_ROAMING_MOVE);
 }
References UNIT_STATE_ROAMING, and UNIT_STATE_ROAMING_MOVE.
DoUpdate()
template<class T > template bool EscortMovementGenerator< T >::DoUpdate (T * , uint32)
Definition at line 48 of file EscortMovementGenerator.cpp.
 {
     if (!unit)
         return false;
     if (unit->HasUnitState(UNIT_STATE_NOT_MOVE) || unit->IsMovementPreventedByCasting())
     {
         unit->StopMoving();
         return true;
     }
     unit->AddUnitState(UNIT_STATE_ROAMING_MOVE);
     bool arrived = unit->movespline->Finalized();
     if (i_recalculateSpeed && !arrived)
     {
         i_recalculateSpeed = false;
         Movement::MoveSplineInit init(unit);
         // xinef: speed changed during path execution, calculate remaining path and launch it once more
         if (m_precomputedPath.size())
         {
             uint32 offset = std::min(uint32(unit->movespline->_currentSplineIdx()), uint32(m_precomputedPath.size()));
             Movement::PointsArray::iterator offsetItr = m_precomputedPath.begin();
             std::advance(offsetItr, offset);
             m_precomputedPath.erase(m_precomputedPath.begin(), offsetItr);
             // restore 0 element (current position)
             m_precomputedPath.insert(m_precomputedPath.begin(), G3D::Vector3(unit->GetPositionX(), unit->GetPositionY(), unit->GetPositionZ()));
             if (m_precomputedPath.size() > 2)
                 init.MovebyPath(m_precomputedPath);
             else if (m_precomputedPath.size() == 2)
                 init.MoveTo(m_precomputedPath[1].x, m_precomputedPath[1].y, m_precomputedPath[1].z, true);
         }
         init.Launch();
         // Xinef: Override spline Id on recalculate launch
         _splineId = unit->movespline->GetId();
     }
     return !arrived;
 }
References Movement::MoveSplineInit::Launch(), Movement::MoveSplineInit::MovebyPath(), Movement::MoveSplineInit::MoveTo(), UNIT_STATE_NOT_MOVE, and UNIT_STATE_ROAMING_MOVE.
GetMovementGeneratorType()
template<class T > MovementGeneratorType EscortMovementGenerator< T >::GetMovementGeneratorType () inline virtual
Implements MovementGenerator.
Definition at line 40 of file EscortMovementGenerator.h.
 { return ESCORT_MOTION_TYPE; }
References ESCORT_MOTION_TYPE.
GetSplineId()
template<class T > uint32 EscortMovementGenerator< T >::GetSplineId () const inline virtual
Reimplemented from MovementGenerator.
Definition at line 42 of file EscortMovementGenerator.h.
 { return _splineId; }
References EscortMovementGenerator< T >::_splineId.
unitSpeedChanged()
template<class T > void EscortMovementGenerator< T >::unitSpeedChanged () inline virtual
Reimplemented from MovementGenerator.
Definition at line 38 of file EscortMovementGenerator.h.
 { i_recalculateSpeed = true; }
References EscortMovementGenerator< T >::i_recalculateSpeed.
Member Data Documentation
_splineId
template<class T > uint32 EscortMovementGenerator< T >::_splineId private
Definition at line 48 of file EscortMovementGenerator.h.
Referenced by EscortMovementGenerator< T >::GetSplineId().
i_recalculateSpeed
template<class T > bool EscortMovementGenerator< T >::i_recalculateSpeed private
Definition at line 45 of file EscortMovementGenerator.h.
Referenced by EscortMovementGenerator< T >::unitSpeedChanged().
m_precomputedPath
template<class T > Movement::PointsArray EscortMovementGenerator< T >::m_precomputedPath private
Definition at line 46 of file EscortMovementGenerator.h.
Referenced by EscortMovementGenerator< T >::EscortMovementGenerator().
The documentation for this class was generated from the following files:
src/server/game/Movement/MovementGenerators/EscortMovementGenerator.h
src/server/game/Movement/MovementGenerators/EscortMovementGenerator.cpp