Azerotcore-wotlk: src/server/scripts/World/world_script_loader.cpp File Reference
world_script_loader.cpp File Reference
Functions
void AddSC_areatrigger_scripts ()
void AddSC_emerald_dragons ()
void AddSC_generic_creature ()
void AddSC_go_scripts ()
void AddSC_guards ()
void AddSC_item_scripts ()
void AddSC_npc_professions ()
void AddSC_npc_innkeeper ()
void AddSC_npcs_special ()
void AddSC_npc_taxi ()
void AddSC_achievement_scripts ()
void AddSC_chat_log ()
void AddSC_character_creation ()
void AddSC_action_ip_logger ()
void AddSC_player_scripts ()
void AddSC_npc_stave_of_ancients ()
void AddWorldScripts ()
Function Documentation
AddSC_achievement_scripts()
void AddSC_achievement_scripts ()
Definition at line 254 of file achievement_scripts.cpp.
 {
     new achievement_resilient_victory();
     new achievement_bg_control_all_nodes();
     new achievement_save_the_day();
     new achievement_bg_ic_resource_glut();
     new achievement_bg_ic_glaive_grave();
     new achievement_bg_ic_mowed_down();
     new achievement_bg_sa_artillery();
     new achievement_sickly_gazelle();
     new achievement_everything_counts();
     new achievement_bg_av_perfection();
     new achievement_arena_by_type("achievement_arena_2v2_check", ARENA_TYPE_2v2);
     new achievement_arena_by_type("achievement_arena_3v3_check", ARENA_TYPE_3v3);
     new achievement_arena_by_type("achievement_arena_5v5_check", ARENA_TYPE_5v5);
     new achievement_sa_defense_of_the_ancients();
     new achievement_tilted();
     new achievement_not_even_a_scratch();
     new achievement_killed_exp_or_honor_target();
 }
References ARENA_TYPE_2v2, ARENA_TYPE_3v3, and ARENA_TYPE_5v5.
Referenced by AddWorldScripts().
AddSC_action_ip_logger()
void AddSC_action_ip_logger ()
Definition at line 316 of file action_ip_logger.cpp.
 {
     new AccountActionIpLogger();
     new CharacterActionIpLogger();
     new CharacterDeleteActionIpLogger();
 }
Referenced by AddWorldScripts().
AddSC_areatrigger_scripts()
void AddSC_areatrigger_scripts ()
Definition at line 481 of file areatrigger_scripts.cpp.
 {
     // Ours
     new AreaTrigger_at_voltarus_middle();
     // Theirs
     new AreaTrigger_at_coilfang_waterfall();
     new AreaTrigger_at_legion_teleporter();
     new AreaTrigger_at_stormwright_shelf();
     new AreaTrigger_at_scent_larkorwi();
     new AreaTrigger_at_last_rites();
     new AreaTrigger_at_sholazar_waygate();
     new AreaTrigger_at_nats_landing();
     new AreaTrigger_at_sentry_point();
     new AreaTrigger_at_brewfest();
     new AreaTrigger_at_area_52_entrance();
 }
Referenced by AddWorldScripts().
AddSC_character_creation()
void AddSC_character_creation ()
Definition at line 64 of file character_creation.cpp.
 {
     new CharacterCreationProcedures();
 }
Referenced by AddWorldScripts().
AddSC_chat_log()
void AddSC_chat_log ()
Definition at line 142 of file chat_log.cpp.
 {
     new ChatLogScript();
 }
Referenced by AddWorldScripts().
AddSC_emerald_dragons()
void AddSC_emerald_dragons ()
Definition at line 755 of file boss_emerald_dragons.cpp.
 {
     // helper NPC scripts
     new npc_dream_fog();
     new npc_spirit_shade();
     // dragons
     new boss_ysondre();
     new boss_taerar();
     new boss_emeriss();
     new boss_lethon();
     // dragon spellscripts
     new spell_dream_fog_sleep();
     new spell_mark_of_nature();
 };
Referenced by AddWorldScripts().
AddSC_generic_creature()
void AddSC_generic_creature ()
Definition at line 228 of file mob_generic_creature.cpp.
 {
     //new generic_creature;
     new trigger_periodic;
     //new trigger_death;
 }
Referenced by AddWorldScripts().
AddSC_go_scripts()
void AddSC_go_scripts ()
Definition at line 1812 of file go_scripts.cpp.
 {
     // Ours
     new go_noblegarden_colored_egg();
     new go_seer_of_zebhalak();
     new go_mistwhisper_treasure();
     new go_witherbark_totem_bundle();
     new go_arena_ready_marker();
     new go_ethereum_prison();
     new go_ethereum_stasis();
     new go_resonite_cask();
     new go_tadpole_cage();
     new go_flames();
     new go_heat();
     // Theirs
     new go_brewfest_music();
     new go_pirate_day_music();
     new go_darkmoon_faire_music();
     new go_midsummer_music();
     new go_gilded_brazier();
     //new go_shrine_of_the_birds();
     new go_southfury_moonstone();
     new go_tablet_of_madness();
     new go_tablet_of_the_seven();
     new go_jump_a_tron();
     new go_sacred_fire_of_life();
     new go_tele_to_dalaran_crystal();
     new go_tele_to_violet_stand();
     new go_fel_crystalforge();
     new go_bashir_crystalforge();
     new go_scourge_cage();
     new go_arcane_prison();
     new go_jotunheim_cage();
     new go_table_theka();
     new go_inconspicuous_landmark();
     new go_soulwell();
     new go_dragonflayer_cage();
     new go_amberpine_outhouse();
     new go_hive_pod();
     new go_massive_seaforium_charge();
     new go_veil_skith_cage();
     new go_bells();
 }
Referenced by AddWorldScripts().
AddSC_guards()
void AddSC_guards ()
Definition at line 178 of file guards.cpp.
 {
     new guard_shattrath_aldor();
     new guard_shattrath_scryer();
 }
Referenced by AddWorldScripts().
AddSC_item_scripts()
void AddSC_item_scripts ()
Definition at line 272 of file item_scripts.cpp.
 {
     new item_only_for_flight();
     new item_nether_wraith_beacon();
     new item_gor_dreks_ointment();
     new item_incendiary_explosives();
     new item_mysterious_egg();
     new item_disgusting_jar();
     new item_petrov_cluster_bombs();
     new item_captured_frog();
     new item_generic_limit_chance_above_60();
 }
Referenced by AddWorldScripts().
AddSC_npc_innkeeper()
void AddSC_npc_innkeeper ()
Definition at line 90 of file npc_innkeeper.cpp.
 {
     new npc_innkeeper;
 }
Referenced by AddWorldScripts().
AddSC_npc_professions()
void AddSC_npc_professions ()
Definition at line 1314 of file npc_professions.cpp.
 {
     new npc_prof_alchemy();
     new npc_prof_blacksmith();
     new npc_engineering_tele_trinket();
     new npc_prof_leather();
     new npc_prof_tailor();
     new go_evil_book_for_dummies();
 }
Referenced by AddWorldScripts().
AddSC_npc_stave_of_ancients()
void AddSC_npc_stave_of_ancients ()
Definition at line 1203 of file npc_stave_of_ancients.cpp.
 {
     new npc_artorius();
     new npc_precious();
     new npc_simone();
     new npc_nelson();
     new npc_franklin();
 }
Referenced by AddWorldScripts().
AddSC_npc_taxi()
void AddSC_npc_taxi ()
Definition at line 266 of file npc_taxi.cpp.
 {
     new npc_taxi;
 }
Referenced by AddWorldScripts().
AddSC_npcs_special()
void AddSC_npcs_special ()
Definition at line 2539 of file npcs_special.cpp.
 {
     // Ours
     new npc_elder_clearwater();
     new npc_riggle_bassbait();
     new npc_target_dummy();
     new npc_training_dummy();
     new npc_venomhide_hatchling();
     // Theirs
     new npc_air_force_bots();
     new npc_chicken_cluck();
     new npc_dancing_flames();
     new npc_doctor();
     new npc_injured_patient();
     new npc_garments_of_quests();
     new npc_guardian();
     new npc_sayge();
     new npc_steam_tonk();
     new npc_wormhole();
     new npc_pet_trainer();
     new npc_locksmith();
     new npc_experience();
     new npc_firework();
     new npc_spring_rabbit();
     new npc_stable_master();
 }
References npc_doctor::npc_doctor().
Referenced by AddWorldScripts().
AddSC_player_scripts()
void AddSC_player_scripts ()
Definition at line 69 of file player_scripts.cpp.
 {
     new QuestApprenticeAnglerPlayerScript();
 }
Referenced by AddWorldScripts().
AddWorldScripts()
void AddWorldScripts ()
Definition at line 38 of file world_script_loader.cpp.
 {
     AddSC_areatrigger_scripts();
     AddSC_emerald_dragons();
     AddSC_generic_creature();
     AddSC_go_scripts();
     AddSC_guards();
     AddSC_item_scripts();
     AddSC_npc_professions();
     AddSC_npc_innkeeper();
     AddSC_npcs_special();
     AddSC_npc_taxi();
     AddSC_achievement_scripts();
     AddSC_chat_log(); // location: scripts\World\chat_log.cpp
     AddSC_character_creation();
     AddSC_action_ip_logger(); // location: scripts\World\action_ip_logger.cpp
     AddSC_player_scripts();
     AddSC_npc_stave_of_ancients();
 }
References AddSC_achievement_scripts(), AddSC_action_ip_logger(), AddSC_areatrigger_scripts(), AddSC_character_creation(), AddSC_chat_log(), AddSC_emerald_dragons(), AddSC_generic_creature(), AddSC_go_scripts(), AddSC_guards(), AddSC_item_scripts(), AddSC_npc_innkeeper(), AddSC_npc_professions(), AddSC_npc_stave_of_ancients(), AddSC_npc_taxi(), AddSC_npcs_special(), and AddSC_player_scripts().