Azerotcore-wotlk: G3D::PointHashGrid< Value, PosFunc, EqualsFunc > Class Template Reference
G3D::PointHashGrid< Value, PosFunc, EqualsFunc > Class Template Reference
A sparse 3D grid of point-based data.
#include <PointHashGrid.h>
Classes
class BoxIterator
class CellIterator
class Entry
class Iterator
class SphereIterator
Public Member Functions
void getCellCoord (const Point3 &pos, Point3int32 &cellCoord) const
Compute the grid cell index of a real position. This is used extensively internally by PointHashGrid. It is useful to calling code to determine when an object is about to move between cells.
PointHashGrid (float radiusHint, const MemoryManager::Ref &m=MemoryManager::create())
float radiusHint () const
void clear (float radiusHint)
void clearAndSetRadiusHint (float radiusHint)
PointHashGrid (const Array< Value > &init, float radiusHint=-1.0f, const MemoryManager::Ref &m=MemoryManager::create())
int size () const
const AABox & conservativeBoxBounds () const
void debugPrintStatistics () const
void insert (const Value &v)
void insert (const Array< Value > &v)
bool remove (const Value &v, bool shrinkIfNecessary=true)
void remove (const Array< Value > &v, bool shrink=true)
Iterator begin () const
const Iterator & end () const
BoxIterator beginBoxIntersection (const AABox &box, bool exact=true) const
const BoxIterator & endBoxIntersection () const
SphereIterator begin (const Sphere &sphere) const
SphereIterator G3D_DEPRECATED beginSphereIntersection (const Sphere &sphere) const
const SphereIterator & endSphereIntersection () const
void getIntersectingMembers (const Sphere &sphere, Array< Value > &result) const
CellIterator beginCells () const
const CellIterator & endCells () const
bool contains (const Value &v) const
void deleteAll ()
void clearAndSetMemoryManager (const MemoryManager::Ref &m)
void clear (bool shrink=true)
int debugGetDeepestBucketSize () const
float debugGetAverageBucketSize () const
Protected Member Functions
void initOffsetArray ()
Private Types
typedef SmallArray< Entry, expectedCellSize > Cell
typedef Table< Point3int32, Cell > CellTable
Private Member Functions
PointHashGrid (const ThisType &)
PointHashGrid & operator= (const ThisType &)
bool find (const Value &v, Point3int32 &foundCellCoord, Cell *&foundCell, int &index)
Private Attributes
Vector3int32 m_offsetArray [3 *3 *3]
int m_epoch
float m_cellWidth
float m_invCellWidth
AABox m_bounds
int m_size
CellTable m_data
MemoryManager::Ref m_memoryManager
Detailed Description
template<class Value, class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>>
class G3D::PointHashGrid< Value, PosFunc, EqualsFunc >
A sparse 3D grid of point-based data.
The space cost for n elements is O(n). For data with approximately uniform density (with respect to the radius hint), the time cost of searching for neighbors is O(1).
You can move members of the data set by first removing them and then adding them with a new location.
Template argument PosFunc must provide a static getPosition method and EqualsFunc must provide a static equals method, as described below.
You can either write classes that support these yourself, provide template specializations of G3D::PositionTrait and G3D::EqualsTrait, or rely on the default template specializations, which already exist for common G3D classes like G3D::Point3. For example:
class PosFunc {
public:
    static void getPosition(const Data& d, Vector3& pos) {
        pos = d.location;
    }
};
class EqualsFunc {
public:
    static bool equals(const Data& p, const Data& q) {
        return p == q;
    }
};
PointHashGrid<Data, Data::PosFunc, Data::EqualsFunc> grid;
If the Value class defines operator==, then the Equalsfunc is optional, so you can just write:
PointHashGrid<Data, Data::PosFunc> grid;
The simplest way to define these is often to make them both methods of the parameter class itself, e.g.,
 class Data {
 public:
     Point3     location;
     ...
     bool operator==(const Data& other) const {
         return (location == other.location) && ...;
     }
     static void getPosition(const Data& p, Vector3& pos) {
         pos = p.location;
     }
};
typedef PointHashGrid<Data, Data> DataGrid;
Definition at line 94 of file PointHashGrid.h.
Member Typedef Documentation
Cell
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> typedef SmallArray<Entry, expectedCellSize> G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::Cell private
One cell of the grid.
Definition at line 109 of file PointHashGrid.h.
CellTable
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> typedef Table<Point3int32, Cell > G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::CellTable private
Definition at line 110 of file PointHashGrid.h.
Constructor & Destructor Documentation
PointHashGrid() [1/3]
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::PointHashGrid (const ThisType &) private
Intentionally unimplemented: prevent copy construction.
PointHashGrid() [2/3]
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::PointHashGrid (float radiusHint, const MemoryManager::Ref & m = MemoryManager::create()) inline
Parameters
radiusHint the radius that will typically be used with beginBallIntersection and beginBoxIntersection. If two Values are equal, their positions must be within this radius as well. You can later change this value with clearAndSetRadiusHint().
Definition at line 224 of file PointHashGrid.h.
                                                                                        : m_size(0), m_memoryManager(m) {
         initOffsetArray();
         m_data.clearAndSetMemoryManager(m_memoryManager);
         debugAssertM(radiusHint > 0, "Cell radius must be positive");
         m_cellWidth = radiusHint;
         m_invCellWidth = 1.0f / m_cellWidth;
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::clearAndSetMemoryManager(), debugAssertM, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::initOffsetArray(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_cellWidth, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_data, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_invCellWidth, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_memoryManager, and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::radiusHint().
PointHashGrid() [3/3]
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::PointHashGrid (const Array< Value > & init, float radiusHint = -1.0f, const MemoryManager::Ref & m = MemoryManager::create()) inline
If radiusHint is negative, it is automatically chosen to put about 5 values in each grid cell (which means about 27 * 5 values for each beginIntersection call).
See also
clearAndSetRadiusHint()
Definition at line 256 of file PointHashGrid.h.
                                                                                                                          : m_size(0), m_memoryManager(m) {
         initOffsetArray();
         m_data.clearAndSetMemoryManager(m_memoryManager);
         Point3 lo(Vector3::inf());
         Point3 hi(-lo);
         // Compute bounds
         Array<Entry> entry(init.size());
         for (int i = 0; i < entry.size(); ++i) {
             const Value& value = init[i];
             Point3 pos;
             entry[i].value     = value;
             entry[i].hashCode  = m_hashFunc(value);
             PosFunc::getPosition(value, entry[i].position);
             lo = lo.min(pos);
             hi = hi.max(pos);
         }
         m_bounds = AABox(lo, hi);
         if (radiusHint <= 0) {
             // Compute a good cell width based on the bounds.
             //
             //   N        numPerCell
             // -----   =  ---------
             // volume        r^3
             float numPerCell = 5;
             radiusHint =
                 (float)pow(numPerCell * m_bounds.volume() / init.size(), 1.0 / 3.0);
             if (radiusHint == 0) {
                 // Volume must have been zero because all points were colocated.
                 radiusHint = 0.1f;
             }
         }
         insert(init);
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::clearAndSetMemoryManager(), G3D::Vector3::inf(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::initOffsetArray(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::insert(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_bounds, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_data, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_memoryManager, G3D::Vector3::max(), G3D::Vector3::min(), pos(), pow(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::radiusHint(), G3D::Array< T, MIN_ELEMENTS >::size(), and G3D::AABox::volume().
Member Function Documentation
begin() [1/2]
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> Iterator G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::begin () const inline
Iterate through all members. It is an error to mutate the HashGrid while iterating through it. Each member can be accessed by "dereferencing" the iterator:
for (Grid::Iterator i = grid.begin(); i != grid.end(), ++i) {
const Value& = *i;
...
}
Definition at line 512 of file PointHashGrid.h.
{
         return Iterator(this);
     }
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::deleteAll(), and G3D::_internal::WeldHelper::smoothNormals().
begin() [2/2]
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> SphereIterator G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::begin (const Sphere & sphere) const inline
Finds all values whose positions are within sphere. It is an error to mutate the PointHashGrid while iterating through it.
Definition at line 821 of file PointHashGrid.h.
{
         return SphereIterator(this, sphere);
     }
beginBoxIntersection()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> BoxIterator G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::beginBoxIntersection (const AABox & box, bool exact = true) const inline
Finds all values whose positions are within box. It is an error to mutate the PointHashGrid while iterating through it.
Parameters
exact If false, the iterator will execute more quickly but will likely return some values that lie outside the box. Set exact = false if you are going to test the results against the yourself box anyway.
Definition at line 704 of file PointHashGrid.h.
{
         return BoxIterator(this, exact, box);
     }
beginCells()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> CellIterator G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::beginCells () const inline
Iterates through the non-empty cells. This is intended primarily for debugging and visualizing the data structure.
Definition at line 972 of file PointHashGrid.h.
{
         return CellIterator(this);
     }
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::clear().
beginSphereIntersection()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> SphereIterator G3D_DEPRECATED G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::beginSphereIntersection (const Sphere & sphere) const inline
Deprecated:
See also
beginIntersection
Definition at line 827 of file PointHashGrid.h.
{
         return SphereIterator(this, sphere);
     }
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::getIntersectingMembers().
clear() [1/2]
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> void G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::clear (bool shrink = true) inline
Removes all data.
Parameters
shrink If true, underlying structures are deallocated as they are freed.
Definition at line 1020 of file PointHashGrid.h.
{
         m_size = 0;
         m_bounds = AABox();
         if (! shrink) {
             // Remove all data
             for (CellIterator it = beginCells(); it.isValid(); ++it) {
                 it.cell().clear(true);
             }
         } else {
             m_data.clear();
         }
         ++m_epoch;
     }
References G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::beginCells(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::clear(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::CellIterator::isValid(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_bounds, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_data, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_epoch, and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_size.
clear() [2/2]
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> void G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::clear (float radiusHint) inline
Definition at line 238 of file PointHashGrid.h.
{
         debugAssertM(radiusHint > 0, "Cell radius must be positive");
         clear();
         m_cellWidth = radiusHint;
         m_invCellWidth = 1.0f / m_cellWidth;
     }
References debugAssertM, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_cellWidth, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_invCellWidth, and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::radiusHint().
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::clearAndSetRadiusHint(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::deleteAll().
clearAndSetMemoryManager()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> void G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::clearAndSetMemoryManager (const MemoryManager::Ref & m) inline
Definition at line 1008 of file PointHashGrid.h.
{
         ++m_epoch;
         m_size = 0;
         m_bounds = AABox();
         m_data.clearAndSetMemoryManager(m);
         m_memoryManager = m;
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::clearAndSetMemoryManager(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_bounds, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_data, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_epoch, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_memoryManager, and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_size.
clearAndSetRadiusHint()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> void G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::clearAndSetRadiusHint (float radiusHint) inline
Definition at line 245 of file PointHashGrid.h.
{
         return clear(radiusHint);
     }
References G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::clear(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::radiusHint().
conservativeBoxBounds()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> const AABox& G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::conservativeBoxBounds () const inline
Returns a conservative bounding box around the contents. This is conservative because it is not updated when elements are removed.
Definition at line 306 of file PointHashGrid.h.
{
         return m_bounds;
     }
References G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_bounds.
contains()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> bool G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::contains (const Value & v) const inline
Returns true if there is a value that is exactly equal to v. This will check all neighboring cells to avoid roundoff error at cell boundaries.
Definition at line 987 of file PointHashGrid.h.
{
         Cell* cell = NULL;
         int   index = 0;
         Vector3int32 cellCoord;
         return const_cast<ThisType*>(this)->find(v, cellCoord, cell, index);
     }
References G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::find(), index, NULL, ThisType, and G3D::Vector3int32.
debugGetAverageBucketSize()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> float G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::debugGetAverageBucketSize () const inline
Definition at line 1038 of file PointHashGrid.h.
{
         return m_data.debugGetAverageBucketSize();
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::debugGetAverageBucketSize(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_data.
debugGetDeepestBucketSize()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> int G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::debugGetDeepestBucketSize () const inline
Definition at line 1034 of file PointHashGrid.h.
{
         return (int)m_data.debugGetDeepestBucketSize();
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::debugGetDeepestBucketSize(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_data.
debugPrintStatistics()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> void G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::debugPrintStatistics () const inline
Definition at line 310 of file PointHashGrid.h.
{
         debugPrintf("Deepest bucket size    = %d\n", (int)m_data.debugGetDeepestBucketSize());
         debugPrintf("Average bucket size    = %g\n", m_data.debugGetAverageBucketSize());
         debugPrintf("Load factor            = %g\n", m_data.debugGetLoad());
     }
References G3D::Table< Key, Value, HashFunc, EqualsFunc >::debugGetAverageBucketSize(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::debugGetDeepestBucketSize(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::debugGetLoad(), G3D::debugPrintf(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_data.
deleteAll()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> void G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::deleteAll () inline
Calls delete on all of the values, which are assumed to be pointers. This is a helper to avoid requiring you to iterate through the data structure, removing and deleting each one. Clears the PointHashGrid at the end.
Using objects (instead of pointers) or reference counted pointers is recommended over using pointers and this deleteAll method.
Definition at line 1001 of file PointHashGrid.h.
                      {
         for (Iterator it = begin(); it.isValid(); ++it) {
             delete *it;
         }
         clear();
     }
References G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::begin(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::clear(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::Iterator::isValid().
end()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> const Iterator& G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::end () const inline
Definition at line 516 of file PointHashGrid.h.
{
         static const Iterator it;
         return it;
     }
endBoxIntersection()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> const BoxIterator& G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::endBoxIntersection () const inline
Definition at line 708 of file PointHashGrid.h.
{
         static const BoxIterator it;
         return it;
     }
endCells()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> const CellIterator& G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::endCells () const inline
Definition at line 976 of file PointHashGrid.h.
{
         static const CellIterator it;
         return it;
     }
endSphereIntersection()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> const SphereIterator& G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::endSphereIntersection () const inline
Deprecated:
See also
SphereIterator::hasMore
Definition at line 833 of file PointHashGrid.h.
{
         static const SphereIterator it;
         return it;
     }
find()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> bool G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::find (const Value & v, Point3int32 & foundCellCoord, Cell *& foundCell, int & index) inline private
Locate the cell and index within that cell containing v. Called by remove() and contains().
Definition at line 148 of file PointHashGrid.h.
{
         Point3 pos;
         PosFunc::getPosition(v, pos);
         Point3int32 cellCoord;
         getCellCoord(pos, cellCoord);
         for (int i = 0; i < 27; ++i) {
             Point3int32 c = cellCoord + m_offsetArray[i];
             Cell* cell = m_data.getPointer(c);
             if (cell != NULL) {
                 // The cell exists
                 for (int j = 0; j < cell->size(); ++j) {
                     if (EqualsFunc::equals((*cell)[j].value, v)) {
                         foundCell = cell;
                         index = j;
                         foundCellCoord = c;
                         return true;
                     }
                 }
             }
         }
         // Not found
         return false;
     }
References mpq::c, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::getCellCoord(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::getPointer(), index, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_data, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_offsetArray, NULL, pos(), and G3D::SmallArray< T, N >::size().
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::contains(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::remove().
getCellCoord()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> void G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::getCellCoord (const Point3 & pos, Point3int32 & cellCoord) const inline
Compute the grid cell index of a real position. This is used extensively internally by PointHashGrid. It is useful to calling code to determine when an object is about to move between cells.
Definition at line 186 of file PointHashGrid.h.
{
         for (int a = 0; a < 3; ++a) {
             cellCoord[a] = iFloor(pos[a] * m_invCellWidth);
         }
     }
References mpq::a, G3D::iFloor(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_invCellWidth, and pos().
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::find(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::insert().
getIntersectingMembers()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> void G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::getIntersectingMembers (const Sphere & sphere, Array< Value > & result) const inline
Appends results
Definition at line 840 of file PointHashGrid.h.
{
         for (SphereIterator it = beginSphereIntersection(sphere); it.isValid(); ++it) {
             result.append(*it);
         }
     }
References G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::beginSphereIntersection(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::isValid().
initOffsetArray()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> void G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::initOffsetArray () inline protected
Initializes m_offsetArray.
Definition at line 195 of file PointHashGrid.h.
{
         int i = 0;
         Point3int32 d;
         for (d.x = -1; d.x <= +1; ++d.x) {
             for (d.y = -1; d.y <= +1; ++d.y) {
                 for (d.z = -1; d.z <= +1; ++d.z) {
                     m_offsetArray[i] = d;
                     ++i;
                 }
             }
         }
         // Put (0, 0, 0) first, so that contains() is most likely to find
         // the value quickly.
         i = (1 * 3 + 1) * 3 + 1;
         debugAssert(m_offsetArray[i] == Vector3int32(0,0,0));
         Vector3int32 temp = m_offsetArray[0];
         m_offsetArray[0] = m_offsetArray[i];
         m_offsetArray[i] = temp;
     }
References mpq::d, debugAssert, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_offsetArray, and G3D::Vector3int32.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::PointHashGrid().
insert() [1/2]
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> void G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::insert (const Array< Value > & v) inline
Inserts all elements of the array.
Definition at line 350 of file PointHashGrid.h.
{
         for (int i = 0; i < v.size(); ++i) {
             insert(v[i]);
         }
     }
References G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::insert(), and G3D::Array< T, MIN_ELEMENTS >::size().
insert() [2/2]
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> void G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::insert (const Value & v) inline
Insert v at position p given by getPosition(v, p).
Multiple elements that are equal may be inserted; all copies will be in the data structure.
Definition at line 319 of file PointHashGrid.h.
{
         Point3 pos;
         PosFunc::getPosition(v, pos);
         Point3int32 cellCoord;
         getCellCoord(pos, cellCoord);
         // See if the cell already exists
         Cell& cell = m_data.getCreate(cellCoord);
         if (cell.size() == 0) {
             // Use the same memory manager as for the whole class
             cell.clearAndSetMemoryManager(m_memoryManager);
         }
         Entry& entry    = cell.next();
         entry.value     = v;
         entry.position  = pos;
         // Update the bounds
         if (size() == 0) {
             m_bounds = AABox(pos);
         } else {
             m_bounds.merge(pos);
         }
         ++m_size;
         ++m_epoch;
     }
References G3D::SmallArray< T, N >::clearAndSetMemoryManager(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::getCellCoord(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::getCreate(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_bounds, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_data, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_epoch, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_memoryManager, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_size, G3D::AABox::merge(), G3D::SmallArray< T, N >::next(), pos(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::Entry::position, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::size(), G3D::SmallArray< T, N >::size(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::Entry::value.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::insert(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::PointHashGrid(), and G3D::_internal::WeldHelper::smoothNormals().
operator=()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> PointHashGrid& G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::operator= (const ThisType &) private
Intentionally unimplemented: prevent assignment.
radiusHint()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> float G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::radiusHint () const inline
See also
clearAndSetRadiusHint()
Definition at line 234 of file PointHashGrid.h.
{
         return m_cellWidth;
     }
References G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_cellWidth.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::clear(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::clearAndSetRadiusHint(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::PointHashGrid().
remove() [1/2]
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> void G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::remove (const Array< Value > & v, bool shrink = true) inline
Removes all elements of v.
Definition at line 395 of file PointHashGrid.h.
{
         for (int i = 0; i < v.size(); ++i) {
             remove(v[i], shrink);
         }
     }
References G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::remove(), and G3D::Array< T, MIN_ELEMENTS >::size().
remove() [2/2]
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> bool G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::remove (const Value & v, bool shrinkIfNecessary = true) inline
If there are multiple copies of an element, you must delete them multiple times.
Parameters
shrinkIfNecessary If true, deallocate underlying data structures as they are emptied. False increases performace at the cost of memory overhead for dynamic structures.
Returns
true if the element was found.
Definition at line 366 of file PointHashGrid.h.
{
         Cell* cell = NULL;
         int   index = 0;
         Vector3int32 cellCoord;
         if (find(v, cellCoord, cell, index)) {
             cell->fastRemove(index, shrinkIfNecessary);
             --m_size;
             ++m_epoch;
             if ((cell->size() == 0) && shrinkIfNecessary) {
                 // Remove the cell itself
                 // Drop our pointer, which is about to dangle
                 cell = NULL;
                 const bool success = m_data.remove(cellCoord);
                 (void)success;
                 debugAssertM(success, "Data structure corrupt: "
                              "tried to remove a cell that doesn't exist.");
             }
             return true;
         } else {
             return false;
         }
     }
References debugAssertM, G3D::SmallArray< T, N >::fastRemove(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::find(), index, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_data, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_epoch, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_size, NULL, G3D::Table< Key, Value, HashFunc, EqualsFunc >::remove(), G3D::SmallArray< T, N >::size(), and G3D::Vector3int32.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::remove().
size()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> int G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::size () const inline
Returns the number of elements.
Definition at line 300 of file PointHashGrid.h.
                      {
         return m_size;
     }
References G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_size.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::insert().
Member Data Documentation
m_bounds
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> AABox G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_bounds private
Conservative bounds; the actual data may be smaller.
Definition at line 127 of file PointHashGrid.h.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::clear(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::clearAndSetMemoryManager(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::conservativeBoxBounds(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::insert(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::PointHashGrid().
m_cellWidth
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> float G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_cellWidth private
Extent of a cell along one dimension.
Definition at line 121 of file PointHashGrid.h.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::clear(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::PointHashGrid(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::radiusHint().
m_data
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> CellTable G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_data private
Non-empty cells indexed by grid position. Actual 3D position is position * m_cellWidth
Definition at line 134 of file PointHashGrid.h.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::clear(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::clearAndSetMemoryManager(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::debugGetAverageBucketSize(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::debugGetDeepestBucketSize(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::debugPrintStatistics(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::find(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::insert(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::PointHashGrid(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::remove().
m_epoch
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> int G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_epoch private
Incremented every time the data structure is mutated. Used by the iterators to determine if the data structure has changed since iteration began.
Definition at line 118 of file PointHashGrid.h.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::clear(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::clearAndSetMemoryManager(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::insert(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::remove().
m_invCellWidth
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> float G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_invCellWidth private
1.0 / cell width
Definition at line 124 of file PointHashGrid.h.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::clear(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::getCellCoord(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::PointHashGrid().
m_memoryManager
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> MemoryManager::Ref G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_memoryManager private
Definition at line 136 of file PointHashGrid.h.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::clearAndSetMemoryManager(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::insert(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::PointHashGrid().
m_offsetArray
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> Vector3int32 G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_offsetArray[3 *3 *3] private
The cube of +/-1 along each dimension. Initialized by initOffsetArray.
Definition at line 113 of file PointHashGrid.h.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::find(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::initOffsetArray().
m_size
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> int G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::m_size private
Number of elements.
Definition at line 130 of file PointHashGrid.h.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::clear(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::clearAndSetMemoryManager(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::insert(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::remove(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::size().
The documentation for this class was generated from the following file:
deps/g3dlite/include/G3D/PointHashGrid.h