Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/base_inlines.h File Reference
base_inlines.h File Reference
Functions
static unsigned base_ind_get (const base_t *base)
static bool metadata_thp_enabled (void)
Function Documentation
base_ind_get()
static unsigned base_ind_get (const base_t * base) inline static
Definition at line 5 of file base_inlines.h.
{
     return base->ind;
 }
References base_s::ind.
Referenced by arena_destroy(), arena_ind_get(), base_auto_thp_switch(), base_delete(), and base_extent_alloc().
metadata_thp_enabled()
static bool metadata_thp_enabled (void) inline static
Definition at line 10 of file base_inlines.h.
{
     return (opt_metadata_thp != metadata_thp_disabled);
 }
References metadata_thp_disabled, and opt_metadata_thp.
Referenced by init_thp_state(), and metadata_thp_madvise().