Azerotcore-wotlk: deps/fmt/include/fmt/ostream.h File Reference
ostream.h File Reference
#include <ostream>
#include "format.h"
Classes
class detail::formatbuf< Char >
struct detail::converter
struct detail::test_stream< Char >
class detail::is_streamable< T, Char >
struct detail::fallback_formatter< T, Char, enable_if_t< is_streamable< T, Char >::value > >
Namespaces
detail
Functions
template<typename Char , typename Traits >
void_t detail::operator<< (std::basic_ostream< Char, Traits > &, Char)
template<typename Traits >
void_t detail::operator<< (std::basic_ostream< char, Traits > &, char)
template<typename Traits >
void_t detail::operator<< (std::basic_ostream< char, Traits > &, signed char)
template<typename Traits >
void_t detail::operator<< (std::basic_ostream< char, Traits > &, unsigned char)
template<typename Char >
void detail::write_buffer (std::basic_ostream< Char > &os, buffer< Char > &buf)
template<typename Char , typename T >
void detail::format_value (buffer< Char > &buf, const T &value, locale_ref loc=locale_ref())
template<typename Char >
FMT_MODULE_EXPORT void vprint (std::basic_ostream< Char > &os, basic_string_view< Char > format_str, basic_format_args< buffer_context< type_identity_t< Char >>> args)
template<typename S , typename... Args, typename Char = enable_if_t<detail::is_string<S>::value, char_t<S>>>
FMT_MODULE_EXPORT void print (std::basic_ostream< Char > &os, const S &format_str, Args &&... args)
Function Documentation
print()
template<typename S , typename... Args, typename Char = enable_if_t<detail::is_string<S>::value, char_t<S>>> FMT_MODULE_EXPORT void print (std::basic_ostream< Char > & os, const S & format_str, Args &&... args)
\rst Prints formatted data to the stream os.
Example**::
fmt::print(cerr, "Don't {}!", "panic"); \endrst
Definition at line 175 of file ostream.h.
{
   vprint(os, to_string_view(format_str),
          fmt::make_args_checked<Args...>(format_str, args...));
 }
References to_string_view(), and vprint().
vprint()
template<typename Char > FMT_MODULE_EXPORT void vprint (std::basic_ostream< Char > & os, basic_string_view< Char > format_str, basic_format_args< buffer_context< type_identity_t< Char >>> args)
Definition at line 156 of file ostream.h.
{
   basic_memory_buffer<Char> buffer;
   detail::vformat_to(buffer, format_str, args);
   detail::write_buffer(os, buffer);
 }
References buffer, vformat_to(), and detail::write_buffer().
Referenced by print().