Azerotcore-wotlk: boss_freya::boss_freyaAI Struct Reference
boss_freya::boss_freyaAI Struct Reference
Public Member Functions
boss_freyaAI (Creature *pCreature)
void Reset () override
void KilledUnit (Unit *victim) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void JustSummoned (Creature *cr) override
void SpawnWave ()
void DoAction (int32 param) override
uint32 GetData (uint32 param) const override
void JustReachedHome () override
void EnterCombat (Unit *) override
void SpellHitTarget (Unit *target, const SpellInfo *spell) override
void UpdateAI (uint32 diff) override
bool CheckEvadeIfOutOfCombatArea () const override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void JustDied (Unit *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * m_pInstance
EventMap events
SummonList summons
uint8 _waveNumber
uint8 _trioKilled
uint8 _spawnedAmount
uint8 _lumberjacked
bool _respawningTrio
bool _backToNature
uint8 _deforestation
ObjectGuid _elderGUID [3]
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 268 of file boss_freya.cpp.
Constructor & Destructor Documentation
boss_freyaAI()
boss_freya::boss_freyaAI::boss_freyaAI (Creature * pCreature) inline
Definition at line 270 of file boss_freya.cpp.
                                           : ScriptedAI(pCreature), summons(me)
         {
             m_pInstance = pCreature->GetInstanceScript();
             if (!me->IsAlive())
                 if (m_pInstance)
                     m_pInstance->SetData(TYPE_FREYA, DONE);
         }
References DONE, WorldObject::GetInstanceScript(), Unit::IsAlive(), m_pInstance, ScriptedAI::me, ZoneScript::SetData(), and TYPE_FREYA.
Member Function Documentation
CheckEvadeIfOutOfCombatArea()
bool boss_freya::boss_freyaAI::CheckEvadeIfOutOfCombatArea () const inline override virtual
Reimplemented from ScriptedAI.
Definition at line 670 of file boss_freya.cpp.
         {
             return me->GetPositionX() < 2135.0f;
         }
References Position::GetPositionX(), and ScriptedAI::me.
DamageTaken()
void boss_freya::boss_freyaAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 337 of file boss_freya.cpp.
         {
             // kaboom!
             if (damage >= me->GetHealth())
             {
                 me->Yell("His hold on me dissipates. I can see clearly once more. Thank you, heroes.", LANG_UNIVERSAL);
                 me->PlayDirectSound(SOUND_DEATH);
                 damage = 0;
                 me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                 me->SetFaction(FACTION_FRIENDLY);
                 me->SetHealth(me->GetMaxHealth());
                 me->CombatStop();
                 me->RemoveAllAuras();
                 events.Reset();
                 summons.DespawnAll();
                 events.Reset();
                 uint8 _elderCount = 0;
                 for (uint8 i = 0; i < 3; ++i)
                 {
                     if (!_elderGUID[i])
                         continue;
                     if (Creature* e = ObjectAccessor::GetCreature(*me, _elderGUID[i]))
                         Unit::Kill(e, e);
                     ++_elderCount;
                 }
                 uint32 chestId = RAID_MODE(GO_FREYA_CHEST, GO_FREYA_CHEST_HERO);
                 chestId -= 2 * _elderCount; // offset
                 me->DespawnOrUnsummon(5000);
                 if (GameObject* go = me->SummonGameObject(chestId, 2345.61f, -71.20f, 425.104f, 3.0f, 0, 0, 0, 0, 0))
                     go->SetUInt32Value(GAMEOBJECT_FLAGS, 0);
                 // Defeat credit
                 if (m_pInstance)
                 {
                     me->CastSpell(me, 65074, true); // credit
                     m_pInstance->SetData(TYPE_FREYA, DONE);
                 }
             }
         }
References _elderGUID, Unit::CastSpell(), Unit::CombatStop(), SummonList::DespawnAll(), Creature::DespawnOrUnsummon(), DONE, FACTION_FRIENDLY, GAMEOBJECT_FLAGS, ObjectAccessor::GetCreature(), Unit::GetHealth(), Unit::GetMaxHealth(), GO_FREYA_CHEST, GO_FREYA_CHEST_HERO, Unit::Kill(), LANG_UNIVERSAL, m_pInstance, ScriptedAI::me, WorldObject::PlayDirectSound(), ScriptedAI::RAID_MODE(), Unit::RemoveAllAuras(), ZoneScript::SetData(), Unit::SetFaction(), Object::SetFlag(), Unit::SetHealth(), SOUND_DEATH, WorldObject::SummonGameObject(), summons, TYPE_FREYA, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and Unit::Yell().
DoAction()
void boss_freya::boss_freyaAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 424 of file boss_freya.cpp.
         {
             if (param == ACTION_LUMBERJACKED)
             {
                 if (!m_pInstance)
                     return;
                 ++_lumberjacked;
                 if (_lumberjacked == 1)
                     m_pInstance->DoStartTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, CRITERIA_LUMBERJACKED);
                 else if (_lumberjacked == 3)
                     m_pInstance->DoUpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, 65296 /*SPELL_LUMBERJACKED*/, 0, me);
                 return;
             }
             if (param == ACTION_RESPAWN_TRIO)
             {
                 if (!_respawningTrio)
                 {
                     _respawningTrio = true;
                     events.ScheduleEvent(EVENT_FREYA_RESPAWN_TRIO, 10000);
                 }
                 ++_trioKilled;
                 return;
             }
             // Deforestation Achievement Counter
             if (param == ACTION_REMOVE_10_STACK)
             {
                 ++_deforestation;
                 if (_deforestation >= 6 && m_pInstance)
                     m_pInstance->DoUpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, SPELL_DEFORESTATION_CREDIT, 0, me);
                 // do not return
             }
             if (Aura* aur = me->GetAura(SPELL_ATTUNED_TO_NATURE))
             {
                 // Back to Nature achievement
                 if (aur->GetStackAmount() - param < 25)
                     _backToNature = false;
                 if (aur->GetStackAmount() > param)
                     aur->SetStackAmount(aur->GetStackAmount() - param);
                 else // Aura out of stack
                 {
                     events.ScheduleEvent(EVENT_FREYA_NATURE_BOMB, 5000);
                     events.SetPhase(EVENT_PHASE_FINAL);
                     aur->Remove();
                     return;
                 }
             }
         }
References _backToNature, _deforestation, _lumberjacked, _respawningTrio, _trioKilled, ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, ACHIEVEMENT_TIMED_TYPE_EVENT, ACTION_LUMBERJACKED, ACTION_REMOVE_10_STACK, ACTION_RESPAWN_TRIO, CRITERIA_LUMBERJACKED, InstanceScript::DoStartTimedAchievement(), InstanceScript::DoUpdateAchievementCriteria(), EVENT_FREYA_NATURE_BOMB, EVENT_FREYA_RESPAWN_TRIO, EVENT_PHASE_FINAL, Unit::GetAura(), m_pInstance, ScriptedAI::me, SPELL_ATTUNED_TO_NATURE, and SPELL_DEFORESTATION_CREDIT.
EnterCombat()
void boss_freya::boss_freyaAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 497 of file boss_freya.cpp.
         {
             me->setActive(true);
             me->SetInCombatWithZone();
             me->CastSpell(me, SPELL_TOUCH_OF_EONAR, true);
             if (Aura* aur = me->AddAura(SPELL_ATTUNED_TO_NATURE, me))
                 aur->SetStackAmount(150);
             events.ScheduleEvent(EVENT_FREYA_ADDS_SPAM, 10000, 0, EVENT_PHASE_ADDS);
             events.ScheduleEvent(EVENT_FREYA_LIFEBINDER, 30000);
             events.ScheduleEvent(EVENT_FREYA_SUNBEAM, 17000);
             events.ScheduleEvent(EVENT_FREYA_BERSERK, 600000);
             events.SetPhase(EVENT_PHASE_ADDS);
             if( !m_pInstance )
                 return;
             if (m_pInstance->GetData(TYPE_FREYA) != DONE)
                 m_pInstance->SetData(TYPE_FREYA, IN_PROGRESS);
             // HARD MODE CHECKS
             Creature* elder = ObjectAccessor::GetCreature(*me, m_pInstance->GetGuidData(NPC_ELDER_STONEBARK));
             if (elder && elder->IsAlive())
             {
                 elder->CastSpell(elder, SPELL_DRAINED_OF_POWER, true);
                 elder->CastSpell(elder, SPELL_STONEBARK_ESSENCE, true);
                 elder->SetInCombatWithZone();
                 events.ScheduleEvent(EVENT_FREYA_GROUND_TREMOR, 35000);
                 _elderGUID[0] = elder->GetGUID();
             }
             elder = ObjectAccessor::GetCreature(*me, m_pInstance->GetGuidData(NPC_ELDER_IRONBRANCH));
             if (elder && elder->IsAlive())
             {
                 elder->CastSpell(elder, SPELL_DRAINED_OF_POWER, true);
                 elder->CastSpell(elder, SPELL_IRONBRANCH_ESSENCE, true);
                 elder->SetInCombatWithZone();
                 events.ScheduleEvent(EVENT_FREYA_IRON_ROOT, 20000);
                 _elderGUID[1] = elder->GetGUID();
             }
             elder = ObjectAccessor::GetCreature(*me, m_pInstance->GetGuidData(NPC_ELDER_BRIGHTLEAF));
             if (elder && elder->IsAlive())
             {
                 elder->CastSpell(elder, SPELL_DRAINED_OF_POWER, true);
                 elder->CastSpell(elder, SPELL_BRIGHTLEAF_ESSENCE, true);
                 elder->SetInCombatWithZone();
                 events.ScheduleEvent(EVENT_FREYA_UNSTABLE_SUN_BEAM, 60000);
                 _elderGUID[2] = elder->GetGUID();
             }
             if (_elderGUID[0] || _elderGUID[1] || _elderGUID[2])
             {
                 me->Yell("Elders, grant me your strength!", LANG_UNIVERSAL);
                 me->PlayDirectSound(SOUND_ELDERS);
             }
             else
             {
                 me->Yell("The Conservatory must be protected!", LANG_UNIVERSAL);
                 me->PlayDirectSound(SOUND_AGGRO);
             }
         }
References _elderGUID, Unit::AddAura(), Unit::CastSpell(), DONE, EVENT_FREYA_ADDS_SPAM, EVENT_FREYA_BERSERK, EVENT_FREYA_GROUND_TREMOR, EVENT_FREYA_IRON_ROOT, EVENT_FREYA_LIFEBINDER, EVENT_FREYA_SUNBEAM, EVENT_FREYA_UNSTABLE_SUN_BEAM, EVENT_PHASE_ADDS, ObjectAccessor::GetCreature(), ZoneScript::GetData(), Object::GetGUID(), InstanceScript::GetGuidData(), IN_PROGRESS, Unit::IsAlive(), LANG_UNIVERSAL, m_pInstance, ScriptedAI::me, NPC_ELDER_BRIGHTLEAF, NPC_ELDER_IRONBRANCH, NPC_ELDER_STONEBARK, WorldObject::PlayDirectSound(), WorldObject::setActive(), ZoneScript::SetData(), Creature::SetInCombatWithZone(), SOUND_AGGRO, SOUND_ELDERS, SPELL_ATTUNED_TO_NATURE, SPELL_BRIGHTLEAF_ESSENCE, SPELL_DRAINED_OF_POWER, SPELL_IRONBRANCH_ESSENCE, SPELL_STONEBARK_ESSENCE, SPELL_TOUCH_OF_EONAR, TYPE_FREYA, and Unit::Yell().
GetData()
uint32 boss_freya::boss_freyaAI::GetData (uint32 param) const inline override virtual
Reimplemented from UnitAI.
Definition at line 478 of file boss_freya.cpp.
         {
             if (param == DATA_GET_ELDER_COUNT)
             {
                 uint8 _count = 0;
                 for (uint8 i = 0; i < 3; ++i)
                     if (_elderGUID[i])
                         ++_count;
                 return _count;
             }
             if (param == DATA_BACK_TO_NATURE)
                 return _backToNature;
             return 0;
         }
References _backToNature, _elderGUID, DATA_BACK_TO_NATURE, and DATA_GET_ELDER_COUNT.
JustReachedHome()
void boss_freya::boss_freyaAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 495 of file boss_freya.cpp.
 { me->setActive(false); }
References ScriptedAI::me, and WorldObject::setActive().
JustSummoned()
void boss_freya::boss_freyaAI::JustSummoned (Creature * cr) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 384 of file boss_freya.cpp.
         {
             if (cr->GetEntry() == NPC_FREYA_UNSTABLE_SUN_BEAM)
             {
                 cr->CastSpell(cr, SPELL_UNSTABLE_SUN_VISUAL, true);
                 cr->CastSpell(cr, SPELL_UNSTABLE_SUN_FREYA_DAMAGE, true);
             }
             summons.Summon(cr);
         }
References Unit::CastSpell(), Object::GetEntry(), NPC_FREYA_UNSTABLE_SUN_BEAM, SPELL_UNSTABLE_SUN_FREYA_DAMAGE, SPELL_UNSTABLE_SUN_VISUAL, SummonList::Summon(), and summons.
KilledUnit()
void boss_freya::boss_freyaAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 320 of file boss_freya.cpp.
         {
             if (victim->GetTypeId() != TYPEID_PLAYER || urand(0, 2))
                 return;
             if (urand(0, 1))
             {
                 me->Yell("Forgive me.", LANG_UNIVERSAL);
                 me->PlayDirectSound(SOUND_SLAY1);
             }
             else
             {
                 me->Yell("From your death springs life anew!", LANG_UNIVERSAL);
                 me->PlayDirectSound(SOUND_SLAY2);
             }
         }
References Object::GetTypeId(), LANG_UNIVERSAL, ScriptedAI::me, WorldObject::PlayDirectSound(), SOUND_SLAY1, SOUND_SLAY2, TYPEID_PLAYER, urand(), and Unit::Yell().
Reset()
void boss_freya::boss_freyaAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 292 of file boss_freya.cpp.
         {
             if (m_pInstance && m_pInstance->GetData(TYPE_FREYA) != DONE)
                 m_pInstance->SetData(TYPE_FREYA, NOT_STARTED);
             events.Reset();
             summons.DespawnAll();
             for (uint8 i = 0; i < 3; ++i)
             {
                 if (!_elderGUID[i])
                     continue;
                 if (Creature* elder = ObjectAccessor::GetCreature(*me, _elderGUID[i]))
                     elder->AI()->EnterEvadeMode();
                 _elderGUID[i].Clear();
             }
             _lumberjacked = 0;
             _spawnedAmount = 0;
             _trioKilled = 0;
             _waveNumber = urand(1, 3);
             _respawningTrio = false;
             _backToNature = true;
             _deforestation = 0;
         }
References _backToNature, _deforestation, _elderGUID, _lumberjacked, _respawningTrio, _spawnedAmount, _trioKilled, _waveNumber, ObjectGuid::Clear(), SummonList::DespawnAll(), DONE, ObjectAccessor::GetCreature(), ZoneScript::GetData(), m_pInstance, ScriptedAI::me, NOT_STARTED, ZoneScript::SetData(), summons, TYPE_FREYA, and urand().
SpawnWave()
void boss_freya::boss_freyaAI::SpawnWave () inline
Definition at line 394 of file boss_freya.cpp.
         {
             _waveNumber = _waveNumber == 1 ? 3 : _waveNumber - 1;
             // Wave of three
             if (_waveNumber == 1)
             {
                 me->Yell("Children, assist me!", LANG_UNIVERSAL);
                 me->PlayDirectSound(SOUND_TRIO);
                 me->SummonCreature(NPC_ANCIENT_WATER_SPIRIT, me->GetPositionX() + urand(5, 15), me->GetPositionY() + urand(5, 15), me->GetMapHeight(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()));
                 me->SummonCreature(NPC_STORM_LASHER, me->GetPositionX() + urand(5, 15), me->GetPositionY() + urand(5, 15), me->GetMapHeight(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()));
                 me->SummonCreature(NPC_SNAPLASHER, me->GetPositionX() + urand(5, 15), me->GetPositionY() + urand(5, 15), me->GetMapHeight(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()));
             }
             // Ancient Conservator
             else if (_waveNumber == 2)
             {
                 me->Yell("Eonar, your servant requires aid!", LANG_UNIVERSAL);
                 me->PlayDirectSound(SOUND_CONSERVATOR);
                 me->SummonCreature(NPC_ANCIENT_CONSERVATOR, me->GetPositionX() + urand(5, 15), me->GetPositionY() + urand(5, 15), me->GetMapHeight(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()), 0, TEMPSUMMON_CORPSE_DESPAWN);
             }
             // Detonating Lashers
             else if (_waveNumber == 3)
             {
                 me->Yell("The swarm of the elements shall overtake you!", LANG_UNIVERSAL);
                 me->PlayDirectSound(SOUND_DETONATING);
                 for (uint8 i = 0; i < 10; ++i)
                     me->SummonCreature(NPC_DETONATING_LASHER, me->GetPositionX() + urand(5, 20), me->GetPositionY() + urand(5, 20), me->GetMapHeight(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()), 0, TEMPSUMMON_CORPSE_DESPAWN);
             }
         }
References _waveNumber, WorldObject::GetMapHeight(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), LANG_UNIVERSAL, ScriptedAI::me, NPC_ANCIENT_CONSERVATOR, NPC_ANCIENT_WATER_SPIRIT, NPC_DETONATING_LASHER, NPC_SNAPLASHER, NPC_STORM_LASHER, WorldObject::PlayDirectSound(), SOUND_CONSERVATOR, SOUND_DETONATING, SOUND_TRIO, WorldObject::SummonCreature(), TEMPSUMMON_CORPSE_DESPAWN, urand(), and Unit::Yell().
Referenced by UpdateAI().
SpellHitTarget()
void boss_freya::boss_freyaAI::SpellHitTarget (Unit * target, const SpellInfo * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 563 of file boss_freya.cpp.
         {
             if (spell->Id == SPELL_NATURE_BOMB_FLIGHT)
                 me->SummonCreature(NPC_NATURE_BOMB, target->GetPositionX(), target->GetPositionY(), target->GetPositionZ());
         }
References Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), SpellInfo::Id, ScriptedAI::me, NPC_NATURE_BOMB, SPELL_NATURE_BOMB_FLIGHT, and WorldObject::SummonCreature().
UpdateAI()
void boss_freya::boss_freyaAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 569 of file boss_freya.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_FREYA_ADDS_SPAM:
                     if (_spawnedAmount < 6)
                         SpawnWave();
                     else if (me->GetAura(SPELL_ATTUNED_TO_NATURE))
                     {
                         me->RemoveAura(SPELL_ATTUNED_TO_NATURE);
                         events.ScheduleEvent(EVENT_FREYA_NATURE_BOMB, 5000);
                         events.SetPhase(EVENT_PHASE_FINAL);
                         return;
                     }
                     _spawnedAmount++;
                     events.RepeatEvent(60000);
                     break;
                 case EVENT_FREYA_LIFEBINDER:
                     {
                         events.RepeatEvent(45000);
                         float x, y, z;
                         for (uint8 i = 0; i < 10; ++i)
{
                             x = me->GetPositionX() + urand(7, 25);
                             y = me->GetPositionY() + urand(7, 25);
                             z = me->GetMapHeight(x, y, me->GetPositionZ());
                             if (me->IsWithinLOS(x, y, z))
{
                                 me->CastSpell(x, y, z, SPELL_SUMMON_LIFEBINDER, true);
                                 return;
                             }
                         }
                         me->CastSpell(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), SPELL_SUMMON_LIFEBINDER, true);
                         break;
                     }
                 case EVENT_FREYA_SUNBEAM:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM))
                         me->CastSpell(target, SPELL_SUNBEAM, false);
                     events.RepeatEvent(15000 + urand(0, 5000));
                     break;
                 case EVENT_FREYA_RESPAWN_TRIO:
                     _deforestation = 0;
                     _respawningTrio = false;
                     if (_trioKilled < 3)
                         summons.DoAction(ACTION_RESPAWN_TRIO);
                     _trioKilled = 0;
                     break;
                 case EVENT_FREYA_NATURE_BOMB:
                     {
                         uint8 _minCount = me->GetMap()->Is25ManRaid() ? urand(7, 10) : urand(3, 4);
                         Map::PlayerList const& pList = me->GetMap()->GetPlayers();
                         for(Map::PlayerList::const_iterator itr = pList.begin(); itr != pList.end(); ++itr)
{
                             if (me->GetDistance(itr->GetSource()) > 70 || !itr->GetSource()->IsAlive())
                                 continue;
                             me->CastSpell(itr->GetSource(), SPELL_NATURE_BOMB_FLIGHT, true);
                             if (!(--_minCount))
                                 break;
                         }
                         events.RepeatEvent(18000);
                         break;
                     }
                 case EVENT_FREYA_BERSERK:
                     me->Yell("You have strayed too far, wasted too much time!", LANG_UNIVERSAL);
                     me->PlayDirectSound(SOUND_BERSERK);
                     me->CastSpell(me, SPELL_BERSERK, true);
                     break;
                 case EVENT_FREYA_GROUND_TREMOR:
                     me->CastSpell(me, SPELL_GROUND_TREMOR_FREYA, false);
                     events.RepeatEvent(25000 + urand(0, 10000));
                     break;
                 case EVENT_FREYA_IRON_ROOT:
                     me->CastCustomSpell(SPELL_IRON_ROOTS_FREYA, SPELLVALUE_MAX_TARGETS, 1, me, false);
                     events.RepeatEvent(45000 + urand(0, 10000));
                     break;
                 case EVENT_FREYA_UNSTABLE_SUN_BEAM:
                     me->SummonCreature(NPC_FREYA_UNSTABLE_SUN_BEAM, me->GetPositionX() + urand(7, 25), me->GetPositionY() + urand(7, 25), me->GetMapHeight(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()), 0, TEMPSUMMON_TIMED_DESPAWN, 10000);
                     if (Is25ManRaid())
                     {
                         me->SummonCreature(NPC_FREYA_UNSTABLE_SUN_BEAM, me->GetPositionX() + urand(7, 25), me->GetPositionY() + urand(7, 25), me->GetMapHeight(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()), 0, TEMPSUMMON_TIMED_DESPAWN, 10000);
                         me->SummonCreature(NPC_FREYA_UNSTABLE_SUN_BEAM, me->GetPositionX() + urand(7, 25), me->GetPositionY() + urand(7, 25), me->GetMapHeight(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()), 0, TEMPSUMMON_TIMED_DESPAWN, 10000);
                     }
                     events.RepeatEvent(38000 + urand(0, 10000));
                     break;
             }
             DoMeleeAttackIfReady();
             EnterEvadeIfOutOfCombatArea();
         }
References _deforestation, _respawningTrio, _spawnedAmount, _trioKilled, ACTION_RESPAWN_TRIO, MapRefMgr::begin(), Unit::CastCustomSpell(), Unit::CastSpell(), SummonList::DoAction(), UnitAI::DoMeleeAttackIfReady(), MapRefMgr::end(), ScriptedAI::EnterEvadeIfOutOfCombatArea(), EVENT_FREYA_ADDS_SPAM, EVENT_FREYA_BERSERK, EVENT_FREYA_GROUND_TREMOR, EVENT_FREYA_IRON_ROOT, EVENT_FREYA_LIFEBINDER, EVENT_FREYA_NATURE_BOMB, EVENT_FREYA_RESPAWN_TRIO, EVENT_FREYA_SUNBEAM, EVENT_FREYA_UNSTABLE_SUN_BEAM, EVENT_PHASE_FINAL, Unit::GetAura(), WorldObject::GetDistance(), WorldObject::GetMap(), WorldObject::GetMapHeight(), Map::GetPlayers(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::HasUnitState(), ScriptedAI::Is25ManRaid(), Map::Is25ManRaid(), WorldObject::IsWithinLOS(), LANG_UNIVERSAL, ScriptedAI::me, NPC_FREYA_UNSTABLE_SUN_BEAM, WorldObject::PlayDirectSound(), Unit::RemoveAura(), SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), SOUND_BERSERK, SpawnWave(), SPELL_ATTUNED_TO_NATURE, SPELL_BERSERK, SPELL_GROUND_TREMOR_FREYA, SPELL_IRON_ROOTS_FREYA, SPELL_NATURE_BOMB_FLIGHT, SPELL_SUMMON_LIFEBINDER, SPELL_SUNBEAM, SPELLVALUE_MAX_TARGETS, WorldObject::SummonCreature(), summons, TEMPSUMMON_TIMED_DESPAWN, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), urand(), and Unit::Yell().
Member Data Documentation
_backToNature
bool boss_freya::boss_freyaAI::_backToNature
Definition at line 287 of file boss_freya.cpp.
Referenced by DoAction(), GetData(), and Reset().
_deforestation
uint8 boss_freya::boss_freyaAI::_deforestation
Definition at line 288 of file boss_freya.cpp.
Referenced by DoAction(), Reset(), and UpdateAI().
_elderGUID
ObjectGuid boss_freya::boss_freyaAI::_elderGUID[3]
Definition at line 290 of file boss_freya.cpp.
Referenced by DamageTaken(), EnterCombat(), GetData(), and Reset().
_lumberjacked
uint8 boss_freya::boss_freyaAI::_lumberjacked
Definition at line 285 of file boss_freya.cpp.
Referenced by DoAction(), and Reset().
_respawningTrio
bool boss_freya::boss_freyaAI::_respawningTrio
Definition at line 286 of file boss_freya.cpp.
Referenced by DoAction(), Reset(), and UpdateAI().
_spawnedAmount
uint8 boss_freya::boss_freyaAI::_spawnedAmount
Definition at line 284 of file boss_freya.cpp.
Referenced by Reset(), and UpdateAI().
_trioKilled
uint8 boss_freya::boss_freyaAI::_trioKilled
Definition at line 283 of file boss_freya.cpp.
Referenced by DoAction(), Reset(), and UpdateAI().
_waveNumber
uint8 boss_freya::boss_freyaAI::_waveNumber
Definition at line 282 of file boss_freya.cpp.
Referenced by Reset(), and SpawnWave().
events
EventMap boss_freya::boss_freyaAI::events
Definition at line 279 of file boss_freya.cpp.
m_pInstance
InstanceScript* boss_freya::boss_freyaAI::m_pInstance
Definition at line 278 of file boss_freya.cpp.
Referenced by boss_freyaAI(), DamageTaken(), DoAction(), EnterCombat(), and Reset().
summons
SummonList boss_freya::boss_freyaAI::summons
Definition at line 280 of file boss_freya.cpp.
Referenced by DamageTaken(), JustSummoned(), Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_freya.cpp