Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/sc.h File Reference
sc.h File Reference
#include "jemalloc/internal/jemalloc_internal_types.h"
Classes
struct sc_s
struct sc_data_s
Macros
#define SC_LG_NGROUP 2
#define SC_LG_TINY_MIN 3
#define SC_NGROUP (1ULL << SC_LG_NGROUP)
#define SC_PTR_BITS ((1ULL << LG_SIZEOF_PTR) * 8)
#define SC_NTINY (LG_QUANTUM - SC_LG_TINY_MIN)
#define SC_LG_TINY_MAXCLASS (LG_QUANTUM > SC_LG_TINY_MIN ? LG_QUANTUM - 1 : -1)
#define SC_NPSEUDO SC_NGROUP
#define SC_LG_FIRST_REGULAR_BASE (LG_QUANTUM + SC_LG_NGROUP)
#define SC_LG_BASE_MAX (SC_PTR_BITS - 2)
#define SC_NREGULAR
#define SC_NSIZES (SC_NTINY + SC_NPSEUDO + SC_NREGULAR)
#define SC_NPSIZES
#define SC_NBINS
#define SC_LOOKUP_MAXCLASS ((size_t)1 << 12)
#define SC_SMALL_MAX_BASE ((size_t)1 << (LG_PAGE + SC_LG_NGROUP - 1))
#define SC_SMALL_MAX_DELTA ((size_t)1 << (LG_PAGE - 1))
#define SC_SMALL_MAXCLASS
#define SC_LARGE_MINCLASS ((size_t)1ULL << (LG_PAGE + SC_LG_NGROUP))
#define SC_LG_LARGE_MINCLASS (LG_PAGE + SC_LG_NGROUP)
#define SC_MAX_BASE ((size_t)1 << (SC_PTR_BITS - 2))
#define SC_MAX_DELTA ((size_t)1 << (SC_PTR_BITS - 2 - SC_LG_NGROUP))
#define SC_LARGE_MAXCLASS (SC_MAX_BASE + (SC_NGROUP - 1) * SC_MAX_DELTA)
Typedefs
typedef struct sc_s sc_t
typedef struct sc_data_s sc_data_t
Functions
void sc_data_init (sc_data_t *data)
void sc_data_update_slab_size (sc_data_t *data, size_t begin, size_t end, int pgs)
void sc_boot (sc_data_t *data)
Macro Definition Documentation
SC_LARGE_MAXCLASS
#define SC_LARGE_MAXCLASS (SC_MAX_BASE + (SC_NGROUP - 1) * SC_MAX_DELTA)
Definition at line 265 of file sc.h.
SC_LARGE_MINCLASS
#define SC_LARGE_MINCLASS ((size_t)1ULL << (LG_PAGE + SC_LG_NGROUP))
Definition at line 257 of file sc.h.
SC_LG_BASE_MAX
#define SC_LG_BASE_MAX (SC_PTR_BITS - 2)
Definition at line 195 of file sc.h.
SC_LG_FIRST_REGULAR_BASE
#define SC_LG_FIRST_REGULAR_BASE (LG_QUANTUM + SC_LG_NGROUP)
Definition at line 188 of file sc.h.
SC_LG_LARGE_MINCLASS
#define SC_LG_LARGE_MINCLASS (LG_PAGE + SC_LG_NGROUP)
Definition at line 258 of file sc.h.
SC_LG_NGROUP
#define SC_LG_NGROUP 2
Definition at line 171 of file sc.h.
SC_LG_TINY_MAXCLASS
#define SC_LG_TINY_MAXCLASS (LG_QUANTUM > SC_LG_TINY_MIN ? LG_QUANTUM - 1 : -1)
Definition at line 186 of file sc.h.
SC_LG_TINY_MIN
#define SC_LG_TINY_MIN 3
Definition at line 172 of file sc.h.
SC_LOOKUP_MAXCLASS
#define SC_LOOKUP_MAXCLASS ((size_t)1 << 12)
Definition at line 246 of file sc.h.
SC_MAX_BASE
#define SC_MAX_BASE ((size_t)1 << (SC_PTR_BITS - 2))
Definition at line 261 of file sc.h.
SC_MAX_DELTA
#define SC_MAX_DELTA ((size_t)1 << (SC_PTR_BITS - 2 - SC_LG_NGROUP))
Definition at line 262 of file sc.h.
SC_NBINS
#define SC_NBINS
Value:
    (                           \
    /* Sub-regular size classes. */                 \
    SC_NTINY + SC_NPSEUDO                       \
    /* Groups with lg_regular_min_base <= lg_base <= lg_base_max */ \
    + SC_NGROUP * (LG_PAGE + SC_LG_NGROUP - SC_LG_FIRST_REGULAR_BASE)   \
    /* Last SC of the last group hits the bound exactly; exclude it. */ \
    - 1)
Definition at line 229 of file sc.h.
SC_NGROUP
#define SC_NGROUP (1ULL << SC_LG_NGROUP)
Definition at line 183 of file sc.h.
SC_NPSEUDO
#define SC_NPSEUDO SC_NGROUP
Definition at line 187 of file sc.h.
SC_NPSIZES
#define SC_NPSIZES
Value:
    (                           \
    /* Start with all the size classes. */              \
    SC_NSIZES                               \
    /* Subtract out those groups with too small a base. */      \
    - (LG_PAGE - 1 - SC_LG_FIRST_REGULAR_BASE) * SC_NGROUP      \
    /* And the pseudo-group. */                     \
    - SC_NPSEUDO                            \
    /* And the tiny group. */                       \
    - SC_NTINY                              \
    /* Sizes where ndelta*delta is not a multiple of the page size. */  \
    - (SC_LG_NGROUP * SC_NGROUP))
Definition at line 201 of file sc.h.
SC_NREGULAR
#define SC_NREGULAR
Value:
    (SC_NGROUP *                    \
    (SC_LG_BASE_MAX - SC_LG_FIRST_REGULAR_BASE + 1) - 1)
Definition at line 196 of file sc.h.
SC_NSIZES
#define SC_NSIZES (SC_NTINY + SC_NPSEUDO + SC_NREGULAR)
Definition at line 198 of file sc.h.
SC_NTINY
#define SC_NTINY (LG_QUANTUM - SC_LG_TINY_MIN)
Definition at line 185 of file sc.h.
SC_PTR_BITS
#define SC_PTR_BITS ((1ULL << LG_SIZEOF_PTR) * 8)
Definition at line 184 of file sc.h.
SC_SMALL_MAX_BASE
#define SC_SMALL_MAX_BASE ((size_t)1 << (LG_PAGE + SC_LG_NGROUP - 1))
Definition at line 249 of file sc.h.
SC_SMALL_MAX_DELTA
#define SC_SMALL_MAX_DELTA ((size_t)1 << (LG_PAGE - 1))
Definition at line 250 of file sc.h.
SC_SMALL_MAXCLASS
#define SC_SMALL_MAXCLASS
Value:
    (SC_SMALL_MAX_BASE              \
    + (SC_NGROUP - 1) * SC_SMALL_MAX_DELTA)
Definition at line 253 of file sc.h.
Typedef Documentation
sc_data_t
typedef struct sc_data_s sc_data_t
Definition at line 1 of file sc.h.
sc_t
typedef struct sc_s sc_t
Definition at line 1 of file sc.h.
Function Documentation
sc_boot()
void sc_boot (sc_data_t * data)
Definition at line 311 of file sc.c.
{
     sc_data_init(data);
 }
References sc_data_init().
sc_data_init()
void sc_data_init (sc_data_t * data)
Definition at line 259 of file sc.c.
{
     assert(!sc_data->initialized);
     int lg_max_lookup = 12;
     size_classes(sc_data, LG_SIZEOF_PTR, LG_QUANTUM, SC_LG_TINY_MIN,
         lg_max_lookup, LG_PAGE, 2);
     sc_data->initialized = true;
 }
References assert(), sc_data_s::initialized, LG_PAGE, SC_LG_TINY_MIN, and size_classes().
Referenced by sc_boot().
sc_data_update_slab_size()
void sc_data_update_slab_size (sc_data_t * data, size_t begin, size_t end, int pgs)
Definition at line 295 of file sc.c.
{
     assert(data->initialized);
     for (int i = 0; i < data->nsizes; i++) {
         sc_t *sc = &data->sc[i];
         if (!sc->bin) {
             break;
         }
         size_t reg_size = reg_size_compute(sc->lg_base, sc->lg_delta,
             sc->ndelta);
         if (begin <= reg_size && reg_size <= end) {
             sc_data_update_sc_slab_size(sc, reg_size, pgs);
         }
     }
 }
References assert(), sc_s::bin, sc_s::lg_base, sc_s::lg_delta, sc_s::ndelta, reg_size_compute(), and sc_data_update_sc_slab_size().