Azerotcore-wotlk: src/server/game/Events/GameEventMgr.cpp File Reference
GameEventMgr.cpp File Reference
#include "BattlegroundMgr.h"
#include "DisableMgr.h"
#include "GameEventMgr.h"
#include "GameObjectAI.h"
#include "GossipDef.h"
#include "Language.h"
#include "Log.h"
#include "MapMgr.h"
#include "ObjectMgr.h"
#include "Player.h"
#include "PoolMgr.h"
#include "ScriptMgr.h"
#include "Transport.h"
#include "UnitAI.h"
#include "Util.h"
#include "World.h"
#include "WorldPacket.h"
#include <time.h>
Classes
class GameEventAIHookWorker
Functions
bool IsHolidayActive (HolidayIds id)
bool IsEventActive (uint16 event_id)
Function Documentation
IsEventActive()
bool IsEventActive (uint16 event_id)
Definition at line 1892 of file GameEventMgr.cpp.
 {
     GameEventMgr::ActiveEvents const& ae = sGameEventMgr->GetActiveEventList();
     return ae.find(event_id) != ae.end();
 }
References sGameEventMgr.
Referenced by Player::_LoadBrewOfTheMonth(), npc_innkeeper::OnGossipHello(), and npc_innkeeper::OnGossipSelect().
IsHolidayActive()
bool IsHolidayActive (HolidayIds id)
Definition at line 1877 of file GameEventMgr.cpp.
 {
     if (id == HOLIDAY_NONE)
         return false;
     GameEventMgr::GameEventDataMap const& events = sGameEventMgr->GetEventMap();
     GameEventMgr::ActiveEvents const& ae = sGameEventMgr->GetActiveEventList();
     for (GameEventMgr::ActiveEvents::const_iterator itr = ae.begin(); itr != ae.end(); ++itr)
         if (events[*itr].holiday_id == id)
             return true;
     return false;
 }
References HOLIDAY_NONE, and sGameEventMgr.
Referenced by Player::CanUseItem(), BattlegroundMgr::IsBGWeekend(), lfg::LFGMgr::IsSeasonActive(), AchievementCriteriaData::Meets(), BattlegroundAV::SetupBattleground(), go_brewfest_music::go_brewfest_musicAI::UpdateAI(), go_pirate_day_music::go_pirate_day_musicAI::UpdateAI(), go_darkmoon_faire_music::go_darkmoon_faire_musicAI::UpdateAI(), and go_midsummer_music::go_midsummer_musicAI::UpdateAI().