Azerotcore-wotlk: G3D::ThreadSet Class Reference
G3D::ThreadSet Class Reference
#include <ThreadSet.h>
Public Types
typedef GThread Thread
typedef shared_ptr< Thread > ThreadRef
typedef shared_ptr< ThreadSet > Ref
typedef Array< ThreadRef >::Iterator Iterator
typedef Array< ThreadRef >::ConstIterator ConstIterator
Public Member Functions
int size () const
int numStarted () const
void start (SpawnBehavior lastThreadBehavior=USE_NEW_THREAD) const
void terminate () const
void waitForCompletion () const
void clear ()
int removeCompleted ()
int insert (const ThreadRef &t)
bool remove (const ThreadRef &t)
bool contains (const ThreadRef &t) const
Iterator begin ()
Iterator end ()
ConstIterator begin () const
ConstIterator end () const
Public Member Functions inherited from G3D::ReferenceCountedObject
virtual ~ReferenceCountedObject ()
Private Attributes
GMutex m_lock
Array< ThreadRef > m_thread
Detailed Description
Manages a set of threads. All methods are threadsafe except for the iterator begin/end.
@beta
Definition at line 18 of file ThreadSet.h.
Member Typedef Documentation
ConstIterator
typedef Array<ThreadRef>::ConstIterator G3D::ThreadSet::ConstIterator
Definition at line 26 of file ThreadSet.h.
Iterator
typedef Array<ThreadRef>::Iterator G3D::ThreadSet::Iterator
Definition at line 25 of file ThreadSet.h.
Ref
typedef shared_ptr<ThreadSet> G3D::ThreadSet::Ref
Definition at line 24 of file ThreadSet.h.
Thread
typedef GThread G3D::ThreadSet::Thread
Intended to allow future use with a template parameter.
Definition at line 21 of file ThreadSet.h.
ThreadRef
typedef shared_ptr<Thread> G3D::ThreadSet::ThreadRef
Definition at line 23 of file ThreadSet.h.
Member Function Documentation
begin() [1/2]
ThreadSet::Iterator G3D::ThreadSet::begin ()
It is an error to mutate the ThreadSet while iterating through it.
Definition at line 150 of file ThreadSet.cpp.
{
     return m_thread.begin();
 }
References G3D::Array< T, MIN_ELEMENTS >::begin(), and m_thread.
begin() [2/2]
ThreadSet::ConstIterator G3D::ThreadSet::begin () const
Definition at line 160 of file ThreadSet.cpp.
{
     return m_thread.begin();
 }
References G3D::Array< T, MIN_ELEMENTS >::begin(), and m_thread.
clear()
void G3D::ThreadSet::clear ()
Remove all (not stopping them)
Definition at line 102 of file ThreadSet.cpp.
                       {
     m_lock.lock();
     m_thread.clear();
     m_lock.unlock();
 }
References G3D::Array< T, MIN_ELEMENTS >::clear(), G3D::GMutex::lock(), m_lock, m_thread, and G3D::GMutex::unlock().
contains()
bool G3D::ThreadSet::contains (const ThreadRef & t) const
Definition at line 138 of file ThreadSet.cpp.
{
     ThreadSet* me = const_cast<ThreadSet*>(this);
     me->m_lock.lock();
     bool found = false;
     for (int i = 0; i < m_thread.size() && ! found; ++i) {
         found = (m_thread[i] == t);
     }
     me->m_lock.unlock();
     return found;
 }
References G3D::GMutex::lock(), m_lock, m_thread, G3D::Array< T, MIN_ELEMENTS >::size(), and G3D::GMutex::unlock().
end() [1/2]
ThreadSet::Iterator G3D::ThreadSet::end ()
Definition at line 155 of file ThreadSet.cpp.
{
     return m_thread.end();
 }
References G3D::Array< T, MIN_ELEMENTS >::end(), and m_thread.
end() [2/2]
ThreadSet::ConstIterator G3D::ThreadSet::end () const
Definition at line 165 of file ThreadSet.cpp.
{
     return m_thread.end();
 }
References G3D::Array< T, MIN_ELEMENTS >::end(), and m_thread.
insert()
int G3D::ThreadSet::insert (const ThreadRef & t)
Inserts a new thread, if it is not already present, and returns the new number of threads.
Definition at line 109 of file ThreadSet.cpp.
{
     m_lock.lock();
     bool found = false;
     for (int i = 0; i < m_thread.size() && ! found; ++i) {
         found = (m_thread[i] == t);
     }
     if (! found) {
         m_thread.append(t);
     }
     int s = m_thread.size();
     m_lock.unlock();
     return s;
 }
References G3D::Array< T, MIN_ELEMENTS >::append(), G3D::GMutex::lock(), m_lock, m_thread, G3D::Array< T, MIN_ELEMENTS >::size(), and G3D::GMutex::unlock().
Referenced by G3D::_internal_runConcurrently2DHelper().
numStarted()
int G3D::ThreadSet::numStarted () const
Number of threads that have been started
Definition at line 15 of file ThreadSet.cpp.
{
     ThreadSet* me = const_cast<ThreadSet*>(this);
     me->m_lock.lock();
     int count = 0;
     for (int i = 0; i < m_thread.size(); ++i) {
         if (m_thread[i]->started()) {
             ++count;
         }
     }
     me->m_lock.unlock();
     return count;
 }
References count(), G3D::GMutex::lock(), m_lock, m_thread, G3D::Array< T, MIN_ELEMENTS >::size(), and G3D::GMutex::unlock().
remove()
bool G3D::ThreadSet::remove (const ThreadRef & t)
Removes a thread. Returns true if the thread was present and removed.
Definition at line 124 of file ThreadSet.cpp.
{
     m_lock.lock();
     bool found = false;
     for (int i = 0; i < m_thread.size() && ! found; ++i) {
         found = (m_thread[i] == t);
         if (found) {
             m_thread.fastRemove(i);
         }
     }
     m_lock.unlock();
     return found;
 }
References G3D::Array< T, MIN_ELEMENTS >::fastRemove(), G3D::GMutex::lock(), m_lock, m_thread, G3D::Array< T, MIN_ELEMENTS >::size(), and G3D::GMutex::unlock().
removeCompleted()
int G3D::ThreadSet::removeCompleted ()
Removes completed threads and returns the new size.
Definition at line 87 of file ThreadSet.cpp.
{
     m_lock.lock();
     for (int i = 0; i < m_thread.size(); ++i) {
         if (m_thread[i]->completed()) {
             m_thread.fastRemove(i);
             --i;
         }
     }
     int s = m_thread.size();
     m_lock.unlock();
     return s;
 }
References G3D::Array< T, MIN_ELEMENTS >::fastRemove(), G3D::GMutex::lock(), m_lock, m_thread, G3D::Array< T, MIN_ELEMENTS >::size(), and G3D::GMutex::unlock().
size()
int G3D::ThreadSet::size () const
Total number of threads (some of which may be completed).
Definition at line 6 of file ThreadSet.cpp.
{
     ThreadSet* me = const_cast<ThreadSet*>(this);
     me->m_lock.lock();
     int s = m_thread.size();
     me->m_lock.unlock();
     return s;
 }
References G3D::GMutex::lock(), m_lock, m_thread, G3D::Array< T, MIN_ELEMENTS >::size(), and G3D::GMutex::unlock().
start()
void G3D::ThreadSet::start (SpawnBehavior lastThreadBehavior = USE_NEW_THREAD) const
Start all threads that are not currently started.
Parameters
lastThreadBehavior If USE_CURRENT_THREAD, takes the last unstarted thread and executes it manually on the current thread. This helps to take full advantage of the machine when running a large number of jobs and avoids the overhead of a thread start for single-thread groups. Note that this forces start() to block until that thread is complete.
Definition at line 29 of file ThreadSet.cpp.
{
     ThreadSet* me = const_cast<ThreadSet*>(this);
     Array<GThreadRef> unstarted;
     me->m_lock.lock();
     // Find the unstarted threads
     for (int i = 0; i < m_thread.size(); ++i) {
         if (! m_thread[i]->started()) {
             unstarted.append(m_thread[i]);
         }
     }
     int last = unstarted.size();
     if (lastBehavior == USE_CURRENT_THREAD) {
         // Save the last unstarted for the current thread
         --last;
     }
     // Start all threads
     for (int i = 0; i < last; ++i) {
         unstarted[i]->start(USE_NEW_THREAD);
     }
     me->m_lock.unlock();
     // Start the last one on my thread
     if ((unstarted.size() > 0) && (lastBehavior == USE_CURRENT_THREAD)) {
         unstarted.last()->start(USE_CURRENT_THREAD);
         debugAssert(unstarted.last()->completed());
     }
 }
References G3D::Array< T, MIN_ELEMENTS >::append(), debugAssert, G3D::Array< T, MIN_ELEMENTS >::last(), G3D::GMutex::lock(), m_lock, m_thread, G3D::Array< T, MIN_ELEMENTS >::size(), G3D::GMutex::unlock(), G3D::USE_CURRENT_THREAD, and G3D::USE_NEW_THREAD.
Referenced by G3D::_internal_runConcurrently2DHelper().
terminate()
void G3D::ThreadSet::terminate () const
Terminate all threads that are currently started
Definition at line 62 of file ThreadSet.cpp.
{
     ThreadSet* me = const_cast<ThreadSet*>(this);
     me->m_lock.lock();
     for (int i = 0; i < m_thread.size(); ++i) {
         if (m_thread[i]->started()) {
             m_thread[i]->terminate();
         }
     }
     me->m_lock.unlock();
 }
References G3D::GMutex::lock(), m_lock, m_thread, G3D::Array< T, MIN_ELEMENTS >::size(), and G3D::GMutex::unlock().
waitForCompletion()
void G3D::ThreadSet::waitForCompletion () const
Waits until all started threads have completed.
Definition at line 74 of file ThreadSet.cpp.
{
     ThreadSet* me = const_cast<ThreadSet*>(this);
     me->m_lock.lock();
     for (int i = 0; i < m_thread.size(); ++i) {
         if (m_thread[i]->started()) {
             m_thread[i]->waitForCompletion();
         }
     }
     me->m_lock.unlock();
 }
References G3D::GMutex::lock(), m_lock, m_thread, G3D::Array< T, MIN_ELEMENTS >::size(), and G3D::GMutex::unlock().
Referenced by G3D::_internal_runConcurrently2DHelper().
Member Data Documentation
m_lock
GMutex G3D::ThreadSet::m_lock private
Protects m_thread
Definition at line 31 of file ThreadSet.h.
Referenced by clear(), contains(), insert(), numStarted(), remove(), removeCompleted(), size(), start(), terminate(), and waitForCompletion().
m_thread
Array<ThreadRef> G3D::ThreadSet::m_thread private
Threads in the set
Definition at line 34 of file ThreadSet.h.
Referenced by begin(), clear(), contains(), end(), insert(), numStarted(), remove(), removeCompleted(), size(), start(), terminate(), and waitForCompletion().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/ThreadSet.h
deps/g3dlite/source/ThreadSet.cpp