Azerotcore-wotlk: npc_natrualist_bite Class Reference
npc_natrualist_bite Class Reference
Classes
struct npc_natrualist_biteAI
Public Member Functions
npc_natrualist_bite ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 48 of file zone_zangarmarsh.cpp.
Constructor & Destructor Documentation
npc_natrualist_bite()
npc_natrualist_bite::npc_natrualist_bite () inline
Definition at line 51 of file zone_zangarmarsh.cpp.
 : CreatureScript("npc_natrualist_bite") { }
Member Function Documentation
GetAI()
CreatureAI* npc_natrualist_bite::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 120 of file zone_zangarmarsh.cpp.
     {
         return new npc_natrualist_biteAI (creature);
     }
OnGossipHello()
bool npc_natrualist_bite::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 53 of file zone_zangarmarsh.cpp.
     {
         uint32 menuId = creature->AI()->GetData(1) ? 7540 : 7520;
         player->PrepareGossipMenu(creature, menuId, false);
         player->SendPreparedGossip(creature);
         return true;
     }
References Creature::AI(), UnitAI::GetData(), Player::PrepareGossipMenu(), and Player::SendPreparedGossip().
OnGossipSelect()
bool npc_natrualist_bite::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32) inline override virtual
Reimplemented from CreatureScript.
Definition at line 61 of file zone_zangarmarsh.cpp.
     {
         ClearGossipMenuFor(player);
         CloseGossipMenuFor(player);
         if (creature->AI()->GetData(1))
         {
             creature->CastSpell(player, SPELL_MARK_OF_BITE, true);
             player->KilledMonsterCredit(creature->GetEntry());
             creature->DespawnOrUnsummon(1000);
         }
         else
         {
             creature->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
             Creature* cr;
             if ((cr = creature->SummonCreature(17957, -186, -790, 43.8f, 4.2f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 30000)))
                 cr->AI()->AttackStart(creature);
             if ((cr = creature->SummonCreature(17960, -188, -783, 43.8f, 4.2f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 30000)))
                 cr->AI()->AttackStart(player);
             if ((cr = creature->SummonCreature(17957, -196, -783, 43.8f, 4.4f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 30000)))
                 cr->AI()->AttackStart(player);
             GameObject* cage = creature->FindNearestGameObject(GO_CAGE_ENTRY, 20.0f);
             if (cage)
                 cage->SetGoState(GO_STATE_ACTIVE);
             creature->SetHomePosition(-195.39f, -795.91f, 43.8f, 1.0f);
             creature->AI()->Talk(1);
         }
         return true;
     }
References Creature::AI(), UnitAI::AttackStart(), Unit::CastSpell(), ClearGossipMenuFor(), CloseGossipMenuFor(), Creature::DespawnOrUnsummon(), WorldObject::FindNearestGameObject(), UnitAI::GetData(), Object::GetEntry(), GO_CAGE_ENTRY, GO_STATE_ACTIVE, Player::KilledMonsterCredit(), Object::RemoveFlag(), GameObject::SetGoState(), Creature::SetHomePosition(), SPELL_MARK_OF_BITE, WorldObject::SummonCreature(), CreatureAI::Talk(), TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, and UNIT_FLAG_IMMUNE_TO_PC.
The documentation for this class was generated from the following file:
src/server/scripts/Outland/zone_zangarmarsh.cpp