Azerotcore-wotlk: EnumUtils::Iterator< Enum > Class Template Reference
EnumUtils::Iterator< Enum > Class Template Reference
#include <SmartEnum.h>
Public Types
using iterator_category = std::random_access_iterator_tag
using value_type = Enum
using pointer = Enum *
using reference = Enum &
using difference_type = std::ptrdiff_t
Public Member Functions
Iterator ()
Iterator (size_t index)
bool operator== (const Iterator &other) const
bool operator!= (const Iterator &other) const
difference_type operator- (Iterator const &other) const
bool operator< (const Iterator &other) const
bool operator<= (const Iterator &other) const
bool operator> (const Iterator &other) const
bool operator>= (const Iterator &other) const
value_type operator[] (difference_type d) const
value_type operator* () const
Iterator & operator+= (difference_type d)
Iterator & operator++ ()
Iterator operator++ (int)
Iterator operator+ (difference_type d) const
Iterator & operator-= (difference_type d)
Iterator & operator-- ()
Iterator operator-- (int)
Iterator operator- (difference_type d) const
Private Attributes
difference_type _index
Detailed Description
template<typename Enum>
class EnumUtils::Iterator< Enum >
Definition at line 77 of file SmartEnum.h.
Member Typedef Documentation
difference_type
template<typename Enum > using EnumUtils::Iterator< Enum >::difference_type = std::ptrdiff_t
Definition at line 84 of file SmartEnum.h.
iterator_category
template<typename Enum > using EnumUtils::Iterator< Enum >::iterator_category = std::random_access_iterator_tag
Definition at line 80 of file SmartEnum.h.
pointer
template<typename Enum > using EnumUtils::Iterator< Enum >::pointer = Enum*
Definition at line 82 of file SmartEnum.h.
reference
template<typename Enum > using EnumUtils::Iterator< Enum >::reference = Enum&
Definition at line 83 of file SmartEnum.h.
value_type
template<typename Enum > using EnumUtils::Iterator< Enum >::value_type = Enum
Definition at line 81 of file SmartEnum.h.
Constructor & Destructor Documentation
Iterator() [1/2]
template<typename Enum > EnumUtils::Iterator< Enum >::Iterator () inline
Definition at line 86 of file SmartEnum.h.
 : _index(EnumUtils::Count<Enum>()) {}
Iterator() [2/2]
template<typename Enum > EnumUtils::Iterator< Enum >::Iterator (size_t index) inline explicit
Definition at line 87 of file SmartEnum.h.
 : _index(index) { }
Member Function Documentation
operator!=()
template<typename Enum > bool EnumUtils::Iterator< Enum >::operator!= (const Iterator< Enum > & other) const inline
Definition at line 90 of file SmartEnum.h.
 { return !operator==(other); }
References EnumUtils::Iterator< Enum >::operator==().
operator*()
template<typename Enum > value_type EnumUtils::Iterator< Enum >::operator* () const inline
Definition at line 98 of file SmartEnum.h.
 { return operator[](0); }
References EnumUtils::Iterator< Enum >::operator[]().
operator+()
template<typename Enum > Iterator EnumUtils::Iterator< Enum >::operator+ (difference_type d) const inline
Definition at line 103 of file SmartEnum.h.
 { Iterator i = *this; i += d; return i; }
operator++() [1/2]
template<typename Enum > Iterator& EnumUtils::Iterator< Enum >::operator++ () inline
Definition at line 101 of file SmartEnum.h.
 { return operator+=(1); }
References EnumUtils::Iterator< Enum >::operator+=().
operator++() [2/2]
template<typename Enum > Iterator EnumUtils::Iterator< Enum >::operator++ (int) inline
Definition at line 102 of file SmartEnum.h.
 { Iterator i = *this; operator++(); return i; }
References EnumUtils::Iterator< Enum >::operator++().
Referenced by EnumUtils::Iterator< Enum >::operator++().
operator+=()
template<typename Enum > Iterator& EnumUtils::Iterator< Enum >::operator+= (difference_type d) inline
Definition at line 100 of file SmartEnum.h.
 { _index += d; return *this; }
References EnumUtils::Iterator< Enum >::_index.
Referenced by EnumUtils::Iterator< Enum >::operator++().
operator-() [1/2]
template<typename Enum > Iterator EnumUtils::Iterator< Enum >::operator- (difference_type d) const inline
Definition at line 108 of file SmartEnum.h.
 { Iterator i = *this; i -= d; return i; }
operator-() [2/2]
template<typename Enum > difference_type EnumUtils::Iterator< Enum >::operator- (Iterator< Enum > const & other) const inline
Definition at line 91 of file SmartEnum.h.
 { return _index - other._index; }
References EnumUtils::Iterator< Enum >::_index.
operator--() [1/2]
template<typename Enum > Iterator& EnumUtils::Iterator< Enum >::operator-- () inline
Definition at line 106 of file SmartEnum.h.
 { return operator-=(1); }
References EnumUtils::Iterator< Enum >::operator-=().
operator--() [2/2]
template<typename Enum > Iterator EnumUtils::Iterator< Enum >::operator-- (int) inline
Definition at line 107 of file SmartEnum.h.
 { Iterator i = *this; operator--(); return i; }
References EnumUtils::Iterator< Enum >::operator--().
Referenced by EnumUtils::Iterator< Enum >::operator--().
operator-=()
template<typename Enum > Iterator& EnumUtils::Iterator< Enum >::operator-= (difference_type d) inline
Definition at line 105 of file SmartEnum.h.
 { _index -= d; return *this; }
References EnumUtils::Iterator< Enum >::_index.
Referenced by EnumUtils::Iterator< Enum >::operator--().
operator<()
template<typename Enum > bool EnumUtils::Iterator< Enum >::operator< (const Iterator< Enum > & other) const inline
Definition at line 92 of file SmartEnum.h.
 { return _index < other._index; }
References EnumUtils::Iterator< Enum >::_index.
operator<=()
template<typename Enum > bool EnumUtils::Iterator< Enum >::operator<= (const Iterator< Enum > & other) const inline
Definition at line 93 of file SmartEnum.h.
 { return _index <= other._index; }
References EnumUtils::Iterator< Enum >::_index.
operator==()
template<typename Enum > bool EnumUtils::Iterator< Enum >::operator== (const Iterator< Enum > & other) const inline
Definition at line 89 of file SmartEnum.h.
 { return other._index == _index; }
References EnumUtils::Iterator< Enum >::_index.
Referenced by EnumUtils::Iterator< Enum >::operator!=().
operator>()
template<typename Enum > bool EnumUtils::Iterator< Enum >::operator> (const Iterator< Enum > & other) const inline
Definition at line 94 of file SmartEnum.h.
 { return _index > other._index; }
References EnumUtils::Iterator< Enum >::_index.
operator>=()
template<typename Enum > bool EnumUtils::Iterator< Enum >::operator>= (const Iterator< Enum > & other) const inline
Definition at line 95 of file SmartEnum.h.
 { return _index >= other._index; }
References EnumUtils::Iterator< Enum >::_index.
operator[]()
template<typename Enum > value_type EnumUtils::Iterator< Enum >::operator[] (difference_type d) const inline
Definition at line 97 of file SmartEnum.h.
 { return FromIndex<Enum>(_index + d); }
References EnumUtils::Iterator< Enum >::_index.
Referenced by EnumUtils::Iterator< Enum >::operator*().
Member Data Documentation
_index
template<typename Enum > difference_type EnumUtils::Iterator< Enum >::_index private
Definition at line 111 of file SmartEnum.h.
Referenced by EnumUtils::Iterator< Enum >::operator+=(), EnumUtils::Iterator< Enum >::operator-(), EnumUtils::Iterator< Enum >::operator-=(), EnumUtils::Iterator< Enum >::operator<(), EnumUtils::Iterator< Enum >::operator<=(), EnumUtils::Iterator< Enum >::operator==(), EnumUtils::Iterator< Enum >::operator>(), EnumUtils::Iterator< Enum >::operator>=(), and EnumUtils::Iterator< Enum >::operator[]().
The documentation for this class was generated from the following file:
src/common/Utilities/SmartEnum.h