Azerotcore-wotlk: spell_the_lich_king_defile::spell_the_lich_king_defile_SpellScript Class Reference
spell_the_lich_king_defile::spell_the_lich_king_defile_SpellScript Class Reference
Private Member Functions
PrepareSpellScript (spell_the_lich_king_defile_SpellScript)
void CorrectRange (std::list< WorldObject * > &targets)
void ChangeDamageAndGrow ()
void Register () override
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Definition at line 2445 of file boss_the_lich_king.cpp.
Member Function Documentation
ChangeDamageAndGrow()
void spell_the_lich_king_defile::spell_the_lich_king_defile_SpellScript::ChangeDamageAndGrow () inline private
Definition at line 2457 of file boss_the_lich_king.cpp.
         {
             SetHitDamage(int32(GetHitDamage() * GetCaster()->GetFloatValue(OBJECT_FIELD_SCALE_X)));
             // HACK: target player should cast this spell on defile
             // however with current aura handling auras cast by different units
             // cannot stack on the same aura object increasing the stack count
             GetCaster()->CastSpell(GetCaster(), SPELL_DEFILE_GROW, true);
         }
References Unit::CastSpell(), SpellScript::GetCaster(), SpellScript::GetHitDamage(), OBJECT_FIELD_SCALE_X, SpellScript::SetHitDamage(), and SPELL_DEFILE_GROW.
Referenced by Register().
CorrectRange()
void spell_the_lich_king_defile::spell_the_lich_king_defile_SpellScript::CorrectRange (std::list< WorldObject * > & targets) inline private
Definition at line 2449 of file boss_the_lich_king.cpp.
         {
             targets.remove_if(VehicleCheck());
             targets.remove_if(Acore::AllWorldObjectsInExactRange(GetCaster(), 10.0f * GetCaster()->GetFloatValue(OBJECT_FIELD_SCALE_X), true));
             uint32 strangulatedAura[4] = {68980, 74325, 74296, 74297};
             targets.remove_if(Acore::UnitAuraCheck(true, strangulatedAura[GetCaster()->GetMap()->GetDifficulty()]));
         }
References SpellScript::GetCaster(), and OBJECT_FIELD_SCALE_X.
Referenced by Register().
PrepareSpellScript()
spell_the_lich_king_defile::spell_the_lich_king_defile_SpellScript::PrepareSpellScript (spell_the_lich_king_defile_SpellScript) private
Register()
void spell_the_lich_king_defile::spell_the_lich_king_defile_SpellScript::Register () inline override private virtual
Implements _SpellScript.
Definition at line 2466 of file boss_the_lich_king.cpp.
         {
             OnObjectAreaTargetSelect += SpellObjectAreaTargetSelectFn(spell_the_lich_king_defile_SpellScript::CorrectRange, EFFECT_0, TARGET_UNIT_SRC_AREA_ENEMY);
             OnObjectAreaTargetSelect += SpellObjectAreaTargetSelectFn(spell_the_lich_king_defile_SpellScript::CorrectRange, EFFECT_1, TARGET_UNIT_SRC_AREA_ENEMY);
             OnHit += SpellHitFn(spell_the_lich_king_defile_SpellScript::ChangeDamageAndGrow);
         }
References ChangeDamageAndGrow(), CorrectRange(), EFFECT_0, EFFECT_1, SpellScript::OnHit, SpellScript::OnObjectAreaTargetSelect, SpellHitFn, SpellObjectAreaTargetSelectFn, and TARGET_UNIT_SRC_AREA_ENEMY.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp