Azerotcore-wotlk: FlightPathMovementGenerator Class Reference
FlightPathMovementGenerator Class Reference
#include <WaypointMovementGenerator.h>
Public Member Functions
FlightPathMovementGenerator (uint32 startNode=0)
void LoadPath (Player *player)
void DoInitialize (Player *)
void DoReset (Player *)
void DoFinalize (Player *)
bool DoUpdate (Player *, uint32)
MovementGeneratorType GetMovementGeneratorType ()
TaxiPathNodeList const & GetPath ()
uint32 GetPathAtMapEnd () const
bool HasArrived () const
void SetCurrentNodeAfterTeleport ()
void SkipCurrentNode ()
void DoEventIfAny (Player *player, TaxiPathNodeEntry const *node, bool departure)
void InitEndGridInfo ()
void PreloadEndGrid ()
Public Member Functions inherited from MovementGeneratorMedium< Player, FlightPathMovementGenerator >
void Initialize (Unit *u) override
void Finalize (Unit *u) override
void Reset (Unit *u) override
bool Update (Unit *u, uint32 time_diff) override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual uint32 GetSplineId () const
virtual void unitSpeedChanged ()
virtual bool GetResetPosition (float &, float &, float &)
Public Member Functions inherited from PathMovementBase< Player, TaxiPathNodeList >
PathMovementBase ()
PathMovementBase (TaxiPathNodeList path)
virtual ~PathMovementBase ()
uint32 GetCurrentNode () const
Private Attributes
float _endGridX
float _endGridY
X coord of last node location.
uint32 _endMapId
Y coord of last node location.
uint32 _preloadTargetNode
map Id of last node location
bool _mapSwitch
node index where preloading starts
std::deque< uint32 > _pointsForPathSwitch
Additional Inherited Members
Protected Attributes inherited from PathMovementBase< Player, TaxiPathNodeList >
TaxiPathNodeList i_path
uint32 i_currentNode
Detailed Description
FlightPathMovementGenerator generates movement of the player for the paths and hence generates ground and activities for the player.
Definition at line 101 of file WaypointMovementGenerator.h.
Constructor & Destructor Documentation
FlightPathMovementGenerator()
FlightPathMovementGenerator::FlightPathMovementGenerator (uint32 startNode = 0) inline explicit
Definition at line 105 of file WaypointMovementGenerator.h.
     {
         i_currentNode = startNode;
         _endGridX = 0.0f;
         _endGridY = 0.0f;
         _endMapId = 0;
         _preloadTargetNode = 0;
         _mapSwitch = false;
     }
References _endGridX, _endGridY, _endMapId, _mapSwitch, _preloadTargetNode, and PathMovementBase< Player, TaxiPathNodeList >::i_currentNode.
Member Function Documentation
DoEventIfAny()
void FlightPathMovementGenerator::DoEventIfAny (Player * player, TaxiPathNodeEntry const * node, bool departure)
Definition at line 437 of file WaypointMovementGenerator.cpp.
 {
     if (uint32 eventid = departure ? node->departureEventID : node->arrivalEventID)
     {
         LOG_DEBUG("maps.script", "Taxi %s event %u of node %u of path %u for player %s", departure ? "departure" : "arrival", eventid, node->index, node->path, player->GetName().c_str());
         player->GetMap()->ScriptsStart(sEventScripts, eventid, player, player);
     }
 }
References TaxiPathNodeEntry::arrivalEventID, TaxiPathNodeEntry::departureEventID, WorldObject::GetMap(), WorldObject::GetName(), TaxiPathNodeEntry::index, LOG_DEBUG, TaxiPathNodeEntry::path, Map::ScriptsStart(), and sEventScripts.
Referenced by DoUpdate().
DoFinalize()
void FlightPathMovementGenerator::DoFinalize (Player * player)
Definition at line 300 of file WaypointMovementGenerator.cpp.
 {
     // remove flag to prevent send object build movement packets for flight state and crash (movement generator already not at top of stack)
     player->ClearUnitState(UNIT_STATE_IN_FLIGHT);
     // xinef: this should be cleaned by CleanupAfterTaxiFlight(); function!
     player->Dismount();
     player->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE | UNIT_FLAG_TAXI_FLIGHT);
     if (player->m_taxi.empty())
     {
         player->getHostileRefMgr().setOnlineOfflineState(true);
         // update z position to ground and orientation for landing point
         // this prevent cheating with landing  point at lags
         // when client side flight end early in comparison server side
         player->StopMoving();
         player->SetFallInformation(time(nullptr), player->GetPositionZ());
     }
     player->RemoveFlag(PLAYER_FLAGS, PLAYER_FLAGS_TAXI_BENCHMARK);
 }
References Unit::ClearUnitState(), Unit::Dismount(), PlayerTaxi::empty(), Unit::getHostileRefMgr(), Position::GetPositionZ(), Player::m_taxi, PLAYER_FLAGS, PLAYER_FLAGS_TAXI_BENCHMARK, Object::RemoveFlag(), Player::SetFallInformation(), HostileRefMgr::setOnlineOfflineState(), Unit::StopMoving(), UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE, UNIT_FLAG_TAXI_FLIGHT, and UNIT_STATE_IN_FLIGHT.
DoInitialize()
void FlightPathMovementGenerator::DoInitialize (Player * player)
Definition at line 294 of file WaypointMovementGenerator.cpp.
 {
     Reset(player);
     InitEndGridInfo();
 }
References InitEndGridInfo(), and MovementGeneratorMedium< Player, FlightPathMovementGenerator >::Reset().
Referenced by DoUpdate().
DoReset()
void FlightPathMovementGenerator::DoReset (Player * player)
Definition at line 324 of file WaypointMovementGenerator.cpp.
 {
     player->getHostileRefMgr().setOnlineOfflineState(false);
     player->AddUnitState(UNIT_STATE_IN_FLIGHT);
     player->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE | UNIT_FLAG_TAXI_FLIGHT);
     Movement::MoveSplineInit init(player);
     uint32 end = GetPathAtMapEnd();
     for (uint32 i = GetCurrentNode(); i < end; ++i)
     {
         G3D::Vector3 vertice(i_path[i]->x, i_path[i]->y, i_path[i]->z);
         init.Path().push_back(vertice);
     }
     init.SetFirstPointId(GetCurrentNode());
     init.SetFly();
     init.SetVelocity(PLAYER_FLIGHT_SPEED);
     init.Launch();
 }
References Unit::AddUnitState(), PathMovementBase< Player, TaxiPathNodeList >::GetCurrentNode(), Unit::getHostileRefMgr(), GetPathAtMapEnd(), PathMovementBase< Player, TaxiPathNodeList >::i_path, Movement::MoveSplineInit::Launch(), Movement::MoveSplineInit::Path(), PLAYER_FLIGHT_SPEED, Movement::MoveSplineInit::SetFirstPointId(), Object::SetFlag(), Movement::MoveSplineInit::SetFly(), HostileRefMgr::setOnlineOfflineState(), Movement::MoveSplineInit::SetVelocity(), UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE, UNIT_FLAG_TAXI_FLIGHT, UNIT_STATE_IN_FLIGHT, G3D::x, G3D::y, and G3D::z.
DoUpdate()
bool FlightPathMovementGenerator::DoUpdate (Player * player, uint32)
Definition at line 343 of file WaypointMovementGenerator.cpp.
 {
     if (!player)
         return false;
     // xinef: map was switched
     if (_mapSwitch)
     {
         DoInitialize(player);
         _mapSwitch = false;
         return true;
     }
     uint32 pointId = (uint32)player->movespline->currentPathIdx();
     if (pointId > i_currentNode)
     {
         bool departureEvent = true;
         do
         {
             if (i_currentNode >= i_path.size())
             {
                 LOG_INFO("misc", "TAXI NODE WAS GREATER THAN PATH SIZE, %s, POINTID: %u, NODESIZE: %lu, CURRENT: %u",
                     player->GetGUID().ToString().c_str(), pointId, i_path.size(), i_currentNode);
                 player->CleanupAfterTaxiFlight();
                 return false;
             }
             if (i_path[i_currentNode]->mapid != player->GetMapId())
             {
                 LOG_INFO("misc", "Player on different map, curmap: %u, pointmap: %u, nodesize: %lu, currentnode: %u", player->GetMapId(), i_path[i_currentNode]->mapid, i_path.size(), i_currentNode);
                 player->CleanupAfterTaxiFlight();
                 return false;
             }
             DoEventIfAny(player, i_path[i_currentNode], departureEvent);
             // xinef: erase any previous points
             uint32 curSize = _pointsForPathSwitch.size();
             while (!_pointsForPathSwitch.empty() && _pointsForPathSwitch.front() <= i_currentNode)
                 _pointsForPathSwitch.pop_front();
             // xinef: switch destination only once
             if (curSize != _pointsForPathSwitch.size())
                 player->m_taxi.NextTaxiDestination();
             if (pointId == i_currentNode)
                 break;
             if (i_currentNode == _preloadTargetNode && player->GetMapId() == _endMapId)
                 PreloadEndGrid();
             i_currentNode += (uint32)departureEvent;
             departureEvent = !departureEvent;
             // xinef: map should be switched, do not rely on client packets QQ
             if (i_currentNode + 1 < i_path.size() && i_path[i_currentNode + 1]->mapid != player->GetMapId())
             {
                 ++i_currentNode;
                 _mapSwitch = true;
                 player->TeleportTo(i_path[i_currentNode]->mapid, i_path[i_currentNode]->x, i_path[i_currentNode]->y, i_path[i_currentNode]->z, player->GetOrientation(), TELE_TO_NOT_LEAVE_TAXI);
                 return true;
             }
             // xinef: reached the end
             if (i_currentNode >= i_path.size() - 1)
             {
                 player->CleanupAfterTaxiFlight();
                 player->SetFallInformation(time(nullptr), player->GetPositionZ());
                 if (player->pvpInfo.IsHostile)
                     player->CastSpell(player, 2479, true);
                 return false;
             }
         } while (true);
     }
     return i_currentNode < (i_path.size() - 1);
 }
References _endMapId, _mapSwitch, _pointsForPathSwitch, _preloadTargetNode, Unit::CastSpell(), Player::CleanupAfterTaxiFlight(), Movement::MoveSpline::currentPathIdx(), DoEventIfAny(), DoInitialize(), Object::GetGUID(), WorldLocation::GetMapId(), Position::GetOrientation(), Position::GetPositionZ(), PathMovementBase< Player, TaxiPathNodeList >::i_currentNode, PathMovementBase< Player, TaxiPathNodeList >::i_path, PvPInfo::IsHostile, LOG_INFO, Player::m_taxi, Unit::movespline, PlayerTaxi::NextTaxiDestination(), PreloadEndGrid(), Player::pvpInfo, Player::SetFallInformation(), TELE_TO_NOT_LEAVE_TAXI, Player::TeleportTo(), ObjectGuid::ToString(), G3D::x, G3D::y, and G3D::z.
GetMovementGeneratorType()
MovementGeneratorType FlightPathMovementGenerator::GetMovementGeneratorType () inline virtual
Implements MovementGenerator.
Definition at line 119 of file WaypointMovementGenerator.h.
 { return FLIGHT_MOTION_TYPE; }
References FLIGHT_MOTION_TYPE.
GetPath()
TaxiPathNodeList const& FlightPathMovementGenerator::GetPath () inline
Definition at line 121 of file WaypointMovementGenerator.h.
 { return i_path; }
References PathMovementBase< Player, TaxiPathNodeList >::i_path.
GetPathAtMapEnd()
uint32 FlightPathMovementGenerator::GetPathAtMapEnd () const
Definition at line 259 of file WaypointMovementGenerator.cpp.
 {
     if (i_currentNode >= i_path.size())
         return i_path.size();
     uint32 curMapId = i_path[i_currentNode]->mapid;
     for (uint32 i = i_currentNode; i < i_path.size(); ++i)
         if (i_path[i]->mapid != curMapId)
             return i;
     return i_path.size();
 }
References PathMovementBase< Player, TaxiPathNodeList >::i_currentNode, and PathMovementBase< Player, TaxiPathNodeList >::i_path.
Referenced by DoReset().
HasArrived()
bool FlightPathMovementGenerator::HasArrived () const inline
Definition at line 123 of file WaypointMovementGenerator.h.
 { return (i_currentNode >= i_path.size()); }
References PathMovementBase< Player, TaxiPathNodeList >::i_currentNode, and PathMovementBase< Player, TaxiPathNodeList >::i_path.
InitEndGridInfo()
void FlightPathMovementGenerator::InitEndGridInfo ()
Storage to preload flightmaster grid at end of flight. For multi-stop flights, this will be reinitialized for each flightmaster at the end of each spline (or stop) in the flight.
Number of nodes in path.
MapId of last node
Definition at line 446 of file WaypointMovementGenerator.cpp.
 {
     uint32 nodeCount = i_path.size();
     _endMapId = i_path[nodeCount - 1]->mapid;
     // pussywizard:
     {
         _preloadTargetNode = nodeCount - 1;
         for (uint8 i = 3; i > 0; --i)
             if (nodeCount >= i && _endMapId == i_path[nodeCount - i]->mapid)
             {
                 _preloadTargetNode = nodeCount - i;
                 break;
             }
         //_preloadTargetNode = nodeCount - 3; // pussywizard: this can be on other map
     }
     _endGridX = i_path[nodeCount - 1]->x;
     _endGridY = i_path[nodeCount - 1]->y;
 }
References _endGridX, _endGridY, _endMapId, _preloadTargetNode, and PathMovementBase< Player, TaxiPathNodeList >::i_path.
Referenced by DoInitialize().
LoadPath()
void FlightPathMovementGenerator::LoadPath (Player * player)
Definition at line 272 of file WaypointMovementGenerator.cpp.
 {
     _pointsForPathSwitch.clear();
     std::vector<uint32> const& taxi = player->m_taxi.GetPath();
     for (uint32 src = player->m_taxi.GetTaxiSegment(), dst = player->m_taxi.GetTaxiSegment() + 1; dst < taxi.size(); src = dst++)
     {
         uint32 path, cost;
         sObjectMgr->GetTaxiPath(taxi[src], taxi[dst], path, cost);
         if (path > sTaxiPathNodesByPath.size())
             return;
         TaxiPathNodeList const& nodes = sTaxiPathNodesByPath[path];
         if (!nodes.empty())
         {
             for (uint32 i = 0; i < nodes.size(); ++i)
                 i_path.push_back(nodes[i]);
         }
         _pointsForPathSwitch.push_back(uint32(i_path.size() - 1));
     }
 }
References _pointsForPathSwitch, PlayerTaxi::GetPath(), PlayerTaxi::GetTaxiSegment(), PathMovementBase< Player, TaxiPathNodeList >::i_path, Player::m_taxi, sObjectMgr, and sTaxiPathNodesByPath.
Referenced by MotionMaster::MoveTaxiFlight().
PreloadEndGrid()
void FlightPathMovementGenerator::PreloadEndGrid ()
Definition at line 469 of file WaypointMovementGenerator.cpp.
 {
     // used to preload the final grid where the flightmaster is
     Map* endMap = sMapMgr->FindBaseNonInstanceMap(_endMapId);
     // Load the grid
     if (endMap)
     {
         LOG_DEBUG("movement", "Preloading rid (%f, %f) for map %u at node index %u/%u", _endGridX, _endGridY, _endMapId, _preloadTargetNode, (uint32)(i_path.size() - 1));
         endMap->LoadGrid(_endGridX, _endGridY);
     }
     else
     {
         LOG_DEBUG("movement", "Unable to determine map to preload flightmaster grid");
     }
 }
References _endGridX, _endGridY, _endMapId, _preloadTargetNode, PathMovementBase< Player, TaxiPathNodeList >::i_path, Map::LoadGrid(), LOG_DEBUG, and sMapMgr.
Referenced by DoUpdate().
SetCurrentNodeAfterTeleport()
void FlightPathMovementGenerator::SetCurrentNodeAfterTeleport ()
Definition at line 421 of file WaypointMovementGenerator.cpp.
 {
     if (i_path.empty() || i_currentNode >= i_path.size())
         return;
     uint32 map0 = i_path[i_currentNode]->mapid;
     for (size_t i = i_currentNode + 1; i < i_path.size(); ++i)
     {
         if (i_path[i]->mapid != map0)
         {
             i_currentNode = i;
             return;
         }
     }
 }
References PathMovementBase< Player, TaxiPathNodeList >::i_currentNode, and PathMovementBase< Player, TaxiPathNodeList >::i_path.
SkipCurrentNode()
void FlightPathMovementGenerator::SkipCurrentNode () inline
Definition at line 125 of file WaypointMovementGenerator.h.
 { ++i_currentNode; }
References PathMovementBase< Player, TaxiPathNodeList >::i_currentNode.
Member Data Documentation
_endGridX
float FlightPathMovementGenerator::_endGridX private
Definition at line 132 of file WaypointMovementGenerator.h.
Referenced by FlightPathMovementGenerator(), InitEndGridInfo(), and PreloadEndGrid().
_endGridY
float FlightPathMovementGenerator::_endGridY private
X coord of last node location.
Definition at line 133 of file WaypointMovementGenerator.h.
Referenced by FlightPathMovementGenerator(), InitEndGridInfo(), and PreloadEndGrid().
_endMapId
uint32 FlightPathMovementGenerator::_endMapId private
Y coord of last node location.
Definition at line 134 of file WaypointMovementGenerator.h.
Referenced by DoUpdate(), FlightPathMovementGenerator(), InitEndGridInfo(), and PreloadEndGrid().
_mapSwitch
bool FlightPathMovementGenerator::_mapSwitch private
node index where preloading starts
Definition at line 136 of file WaypointMovementGenerator.h.
Referenced by DoUpdate(), and FlightPathMovementGenerator().
_pointsForPathSwitch
std::deque<uint32> FlightPathMovementGenerator::_pointsForPathSwitch private
Definition at line 138 of file WaypointMovementGenerator.h.
Referenced by DoUpdate(), and LoadPath().
_preloadTargetNode
uint32 FlightPathMovementGenerator::_preloadTargetNode private
map Id of last node location
Definition at line 135 of file WaypointMovementGenerator.h.
Referenced by DoUpdate(), FlightPathMovementGenerator(), InitEndGridInfo(), and PreloadEndGrid().
The documentation for this class was generated from the following files:
src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.h
src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.cpp