Azerotcore-wotlk: go_ethereum_stasis Class Reference
go_ethereum_stasis Class Reference
Public Member Functions
go_ethereum_stasis ()
bool OnGossipHello (Player *player, GameObject *go) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Definition at line 228 of file go_scripts.cpp.
Constructor & Destructor Documentation
go_ethereum_stasis()
go_ethereum_stasis::go_ethereum_stasis () inline
Definition at line 231 of file go_scripts.cpp.
 : GameObjectScript("go_ethereum_stasis") { }
Member Function Documentation
OnGossipHello()
bool go_ethereum_stasis::OnGossipHello (Player * player, GameObject * go) inline override virtual
Reimplemented from GameObjectScript.
Definition at line 233 of file go_scripts.cpp.
     {
         int Random = rand() % (sizeof(NpcStasisEntry) / sizeof(uint32));
         player->SummonCreature(NpcStasisEntry[Random], go->GetPositionX(), go->GetPositionY(), go->GetPositionZ(), go->GetAngle(player),
                                TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 30000);
         return false;
     }
References Position::GetAngle(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), NpcStasisEntry, WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT.
The documentation for this class was generated from the following file:
src/server/scripts/World/go_scripts.cpp