Azerotcore-wotlk: deps/mysqllite/mysys/my_file.c File Reference
my_file.c File Reference
#include "mysys_priv.h"
#include "my_static.h"
#include <m_string.h>
Functions
static uint set_max_open_files (uint max_file_limit)
uint my_set_max_open_files (uint files)
void my_free_open_file_info ()
Function Documentation
my_free_open_file_info()
void my_free_open_file_info (void)
Definition at line 122 of file my_file.c.
 {
   DBUG_ENTER("my_free_file_info");
   if (my_file_info != my_file_info_default)
   {
     /* Copy data back for my_print_open_files */
     memcpy((char*) my_file_info_default, my_file_info,
            sizeof(*my_file_info_default)* MY_NFILE);
     my_free(my_file_info);
     my_file_info= my_file_info_default;
     my_file_limit= MY_NFILE;
   }
   DBUG_VOID_RETURN;
 }
References DBUG_ENTER, DBUG_VOID_RETURN, memcpy, my_file_info, my_file_info_default, my_file_limit, my_free(), and MY_NFILE.
Referenced by my_set_max_open_files().
my_set_max_open_files()
uint my_set_max_open_files (uint files)
Definition at line 94 of file my_file.c.
 {
   struct st_my_file_info *tmp;
   DBUG_ENTER("my_set_max_open_files");
   DBUG_PRINT("enter",("files: %u  my_file_limit: %u", files, my_file_limit));
   files+= MY_FILE_MIN;
   files= set_max_open_files(min(files, OS_FILE_LIMIT));
   if (files <= MY_NFILE)
     DBUG_RETURN(files);
   if (!(tmp= (struct st_my_file_info*) my_malloc(sizeof(*tmp) * files,
                          MYF(MY_WME))))
     DBUG_RETURN(MY_NFILE);
   /* Copy any initialized files */
   memcpy((char*) tmp, (char*) my_file_info,
          sizeof(*tmp) * min(my_file_limit, files));
   bzero((char*) (tmp + my_file_limit),
         max((int) (files- my_file_limit), 0)*sizeof(*tmp));
   my_free_open_file_info();         /* Free if already allocated */
   my_file_info= tmp;
   my_file_limit= files;
   DBUG_PRINT("exit",("files: %u", files));
   DBUG_RETURN(files);
 }
References bzero, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, files, max, memcpy, min, my_file_info, my_file_limit, MY_FILE_MIN, my_free_open_file_info(), my_malloc(), MY_NFILE, MY_WME, MYF, OS_FILE_LIMIT, and set_max_open_files().
set_max_open_files()
static uint set_max_open_files (uint max_file_limit) static
Definition at line 75 of file my_file.c.
 {
   /* We don't know the limit. Return best guess */
   return min(max_file_limit, OS_FILE_LIMIT);
 }
References min, and OS_FILE_LIMIT.
Referenced by my_set_max_open_files().