Azerotcore-wotlk: src/server/worldserver/ACSoap/ACSoap.cpp File Reference
ACSoap.cpp File Reference
#include "ACSoap.h"
#include "AccountMgr.h"
#include "Log.h"
#include "soapH.h"
#include "soapStub.h"
#include "World.h"
Functions
void ACSoapThread (const std::string &host, uint16 port)
void process_message (struct soap *soap_message)
int ns1__executeCommand (soap *soap, char *command, char **result)
Variables
struct Namespace namespaces []
Function Documentation
ACSoapThread()
void ACSoapThread (const std::string & host, uint16 port)
Definition at line 25 of file ACSoap.cpp.
 {
     struct soap soap;
     soap_init(&soap);
     soap_set_imode(&soap, SOAP_C_UTFSTRING);
     soap_set_omode(&soap, SOAP_C_UTFSTRING);
     // check every 3 seconds if world ended
     soap.accept_timeout = 3;
     soap.recv_timeout = 5;
     soap.send_timeout = 5;
     if (!soap_valid_socket(soap_bind(&soap, host.c_str(), port, 100)))
     {
         LOG_ERROR("network.soap", "ACSoap: couldn't bind to %s:%d", host.c_str(), port);
         exit(-1);
     }
     LOG_INFO("network.soap", "ACSoap: bound to http://%s:%d", host.c_str(), port);
     while (!World::IsStopped())
     {
         if (!soap_valid_socket(soap_accept(&soap)))
             continue;   // ran into an accept timeout
         LOG_DEBUG("network.soap", "ACSoap: accepted connection from IP=%d.%d.%d.%d", (int)(soap.ip >> 24) & 0xFF, (int)(soap.ip >> 16) & 0xFF, (int)(soap.ip >> 8) & 0xFF, (int)soap.ip & 0xFF);
         struct soap* thread_soap = soap_copy(&soap);// make a safe copy
         process_message(thread_soap);
     }
     soap_destroy(&soap);
     soap_end(&soap);
     soap_done(&soap);
 }
References soap::accept_timeout, soap::host, soap::ip, World::IsStopped(), LOG_DEBUG, LOG_ERROR, LOG_INFO, soap::port, process_message(), soap::recv_timeout, soap::send_timeout, soap_accept(), soap_bind(), SOAP_C_UTFSTRING, soap_copy(), soap_destroy, soap_done(), soap_end(), soap_init, soap_set_imode, soap_set_omode, and soap_valid_socket.
Referenced by main().
ns1__executeCommand()
int ns1__executeCommand (struct soap * soap, char * command, char ** result)
Web service operation 'ns1__executeCommand' implementation, should return SOAP_OK or error code
Definition at line 75 of file ACSoap.cpp.
 {
     // security check
     if (!soap->userid || !soap->passwd)
     {
         LOG_DEBUG("network.soap", "ACSoap: Client didn't provide login information");
         return 401;
     }
     uint32 accountId = AccountMgr::GetId(soap->userid);
     if (!accountId)
     {
         LOG_DEBUG("network", "ACSoap: Client used invalid username '%s'", soap->userid);
         return 401;
     }
     if (!AccountMgr::CheckPassword(accountId, soap->passwd))
     {
         LOG_DEBUG("network.soap", "ACSoap: invalid password for account '%s'", soap->userid);
         return 401;
     }
     if (AccountMgr::GetSecurity(accountId) < SEC_ADMINISTRATOR)
     {
         LOG_DEBUG("network.soap", "ACSoap: %s's gmlevel is too low", soap->userid);
         return 403;
     }
     if (!command || !*command)
         return soap_sender_fault(soap, "Command can not be empty", "The supplied command was an empty string");
     LOG_DEBUG("network.soap", "ACSoap: got command '%s'", command);
     SOAPCommand connection;
     // commands are executed in the world thread. We have to wait for them to be completed
     {
         // CliCommandHolder will be deleted from world, accessing after queueing is NOT save
         CliCommandHolder* cmd = new CliCommandHolder(&connection, command, &SOAPCommand::print, &SOAPCommand::commandFinished);
         sWorld->QueueCliCommand(cmd);
     }
     // Wait until the command has finished executing
     connection.finishedPromise.get_future().wait();
     // The command has finished executing already
     char* printBuffer = soap_strdup(soap, connection.m_printBuffer.c_str());
     if (connection.hasCommandSucceeded())
     {
         *result = printBuffer;
         return SOAP_OK;
     }
     else
         return soap_sender_fault(soap, printBuffer, printBuffer);
 }
References AccountMgr::CheckPassword(), SOAPCommand::commandFinished(), SOAPCommand::finishedPromise, AccountMgr::GetId(), AccountMgr::GetSecurity(), SOAPCommand::hasCommandSucceeded(), LOG_DEBUG, SOAPCommand::m_printBuffer, soap::passwd, SOAPCommand::print(), SEC_ADMINISTRATOR, SOAP_OK, soap_sender_fault(), soap_strdup(), sWorld, and soap::userid.
Referenced by soap_serve_ns1__executeCommand().
process_message()
void process_message (struct soap * soap_message)
Definition at line 61 of file ACSoap.cpp.
 {
     LOG_TRACE("network.soap", "SOAPWorkingThread::process_message");
     soap_serve(soap_message);
     soap_destroy(soap_message); // dealloc C++ data
     soap_end(soap_message); // dealloc data and clean up
     soap_free(soap_message); // detach soap struct and fre up the memory
 }
References LOG_TRACE, soap_destroy, soap_end(), soap_free(), and soap_serve().
Referenced by ACSoapThread().
Variable Documentation
namespaces
struct Namespace namespaces[]
Initial value:
=
{
    { "SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", nullptr, nullptr },
    { "SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", nullptr, nullptr },
    { "xsi", "http://www.w3.org/1999/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", nullptr },
    { "xsd", "http://www.w3.org/1999/XMLSchema",          "http://www.w3.org/*/XMLSchema", nullptr },
    { "ns1", "urn:AC", nullptr, nullptr },
    { nullptr, nullptr, nullptr, nullptr }
}
Definition at line 130 of file ACSoap.cpp.
Referenced by soap_init().