Azerotcore-wotlk: EmblemInfo Class Reference
EmblemInfo Class Reference
#include <Guild.h>
Public Member Functions
EmblemInfo ()
void LoadFromDB (Field *fields)
void SaveToDB (uint32 guildId) const
void ReadPacket (WorldPacket &recv)
void WritePacket (WorldPacket &data) const
uint32 GetStyle () const
uint32 GetColor () const
uint32 GetBorderStyle () const
uint32 GetBorderColor () const
uint32 GetBackgroundColor () const
Private Attributes
uint32 m_style
uint32 m_color
uint32 m_borderStyle
uint32 m_borderColor
uint32 m_backgroundColor
Detailed Description
Definition at line 225 of file Guild.h.
Constructor & Destructor Documentation
EmblemInfo()
EmblemInfo::EmblemInfo () inline
Definition at line 228 of file Guild.h.
 : m_style(0), m_color(0), m_borderStyle(0), m_borderColor(0), m_backgroundColor(0) { }
Member Function Documentation
GetBackgroundColor()
uint32 EmblemInfo::GetBackgroundColor () const inline
Definition at line 239 of file Guild.h.
 { return m_backgroundColor; }
References m_backgroundColor.
Referenced by Guild::Create(), and WorldSession::HandleSaveGuildEmblemOpcode().
GetBorderColor()
uint32 EmblemInfo::GetBorderColor () const inline
Definition at line 238 of file Guild.h.
 { return m_borderColor; }
References m_borderColor.
Referenced by Guild::Create(), and WorldSession::HandleSaveGuildEmblemOpcode().
GetBorderStyle()
uint32 EmblemInfo::GetBorderStyle () const inline
Definition at line 237 of file Guild.h.
 { return m_borderStyle; }
References m_borderStyle.
Referenced by Guild::Create(), and WorldSession::HandleSaveGuildEmblemOpcode().
GetColor()
uint32 EmblemInfo::GetColor () const inline
Definition at line 236 of file Guild.h.
 { return m_color; }
References m_color.
Referenced by Guild::Create(), and WorldSession::HandleSaveGuildEmblemOpcode().
GetStyle()
uint32 EmblemInfo::GetStyle () const inline
Definition at line 235 of file Guild.h.
 { return m_style; }
References m_style.
Referenced by Guild::Create(), and WorldSession::HandleSaveGuildEmblemOpcode().
LoadFromDB()
void EmblemInfo::LoadFromDB (Field * fields)
Definition at line 775 of file Guild.cpp.
 {
     m_style             = fields[3].GetUInt8();
     m_color             = fields[4].GetUInt8();
     m_borderStyle       = fields[5].GetUInt8();
     m_borderColor       = fields[6].GetUInt8();
     m_backgroundColor   = fields[7].GetUInt8();
 }
References Field::GetUInt8().
Referenced by Guild::LoadFromDB().
ReadPacket()
void EmblemInfo::ReadPacket (WorldPacket & recv)
Definition at line 770 of file Guild.cpp.
 {
     recv >> m_style >> m_color >> m_borderStyle >> m_borderColor >> m_backgroundColor;
 }
Referenced by WorldSession::HandleSaveGuildEmblemOpcode().
SaveToDB()
void EmblemInfo::SaveToDB (uint32 guildId) const
Definition at line 793 of file Guild.cpp.
 {
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_GUILD_EMBLEM_INFO);
     stmt->setUInt32(0, m_style);
     stmt->setUInt32(1, m_color);
     stmt->setUInt32(2, m_borderStyle);
     stmt->setUInt32(3, m_borderColor);
     stmt->setUInt32(4, m_backgroundColor);
     stmt->setUInt32(5, guildId);
     CharacterDatabase.Execute(stmt);
 }
References CHAR_UPD_GUILD_EMBLEM_INFO, CharacterDatabase, and PreparedStatementBase::setUInt32().
Referenced by Guild::HandleSetEmblem().
WritePacket()
void EmblemInfo::WritePacket (WorldPacket & data) const
Definition at line 784 of file Guild.cpp.
 {
     data << uint32(m_style);
     data << uint32(m_color);
     data << uint32(m_borderStyle);
     data << uint32(m_borderColor);
     data << uint32(m_backgroundColor);
 }
Referenced by Guild::HandleQuery().
Member Data Documentation
m_backgroundColor
uint32 EmblemInfo::m_backgroundColor private
Definition at line 246 of file Guild.h.
Referenced by GetBackgroundColor().
m_borderColor
uint32 EmblemInfo::m_borderColor private
Definition at line 245 of file Guild.h.
Referenced by GetBorderColor().
m_borderStyle
uint32 EmblemInfo::m_borderStyle private
Definition at line 244 of file Guild.h.
Referenced by GetBorderStyle().
m_color
uint32 EmblemInfo::m_color private
Definition at line 243 of file Guild.h.
Referenced by GetColor().
m_style
uint32 EmblemInfo::m_style private
Definition at line 242 of file Guild.h.
Referenced by GetStyle().
The documentation for this class was generated from the following files:
src/server/game/Guilds/Guild.h
src/server/game/Guilds/Guild.cpp