Azerotcore-wotlk: deps/jemalloc/src/bitmap.c File Reference
bitmap.c File Reference
#include "jemalloc/internal/jemalloc_preamble.h"
#include "jemalloc/internal/jemalloc_internal_includes.h"
#include "jemalloc/internal/assert.h"
Macros
#define JEMALLOC_BITMAP_C_
Functions
void bitmap_info_init (bitmap_info_t *binfo, size_t nbits)
static size_t bitmap_info_ngroups (const bitmap_info_t *binfo)
void bitmap_init (bitmap_t *bitmap, const bitmap_info_t *binfo, bool fill)
size_t bitmap_size (const bitmap_info_t *binfo)
Macro Definition Documentation
JEMALLOC_BITMAP_C_
#define JEMALLOC_BITMAP_C_
Definition at line 1 of file bitmap.c.
Function Documentation
bitmap_info_init()
void bitmap_info_init (bitmap_info_t * binfo, size_t nbits)
Definition at line 86 of file bitmap.c.
{
     assert(nbits > 0);
     assert(nbits <= (ZU(1) << LG_BITMAP_MAXBITS));
     binfo->ngroups = BITMAP_BITS2GROUPS(nbits);
     binfo->nbits = nbits;
 }
References assert(), BITMAP_BITS2GROUPS, LG_BITMAP_MAXBITS, bitmap_info_s::nbits, bitmap_info_s::ngroups, and ZU.
bitmap_info_ngroups()
static size_t bitmap_info_ngroups (const bitmap_info_t * binfo) static
Definition at line 95 of file bitmap.c.
{
     return binfo->ngroups;
 }
References bitmap_info_s::ngroups.
Referenced by bitmap_size().
bitmap_init()
void bitmap_init (bitmap_t * bitmap, const bitmap_info_t * binfo, bool fill)
Definition at line 100 of file bitmap.c.
{
     size_t extra;
     if (fill) {
         memset(bitmap, 0, bitmap_size(binfo));
         return;
     }
     memset(bitmap, 0xffU, bitmap_size(binfo));
     extra = (BITMAP_GROUP_NBITS - (binfo->nbits & BITMAP_GROUP_NBITS_MASK))
         & BITMAP_GROUP_NBITS_MASK;
     if (extra != 0) {
         bitmap[binfo->ngroups - 1] >>= extra;
     }
 }
References BITMAP_GROUP_NBITS, BITMAP_GROUP_NBITS_MASK, bitmap_size(), fill(), memset, bitmap_info_s::nbits, and bitmap_info_s::ngroups.
bitmap_size()
size_t bitmap_size (const bitmap_info_t * binfo)
Definition at line 119 of file bitmap.c.
{
     return (bitmap_info_ngroups(binfo) << LG_SIZEOF_BITMAP);
 }
References bitmap_info_ngroups(), and LG_SIZEOF_BITMAP.
Referenced by bitmap_init().