Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/rtree.h File Reference
rtree.h File Reference
#include "jemalloc/internal/atomic.h"
#include "jemalloc/internal/mutex.h"
#include "jemalloc/internal/rtree_tsd.h"
#include "jemalloc/internal/sc.h"
#include "jemalloc/internal/tsd.h"
Classes
struct rtree_node_elm_s
struct rtree_leaf_elm_s
struct rtree_level_s
struct rtree_s
Macros
#define RTREE_NHIB ((1U << (LG_SIZEOF_PTR+3)) - LG_VADDR)
#define RTREE_NLIB LG_PAGE
#define RTREE_NSB (LG_VADDR - RTREE_NLIB)
#define RTREE_HEIGHT 1
#define RTREE_LEAF_COMPACT
#define RTREE_LEAFKEY_INVALID ((uintptr_t)1)
#define RTREE_CACHE_CHECK_L2(i)
Typedefs
typedef struct rtree_node_elm_s rtree_node_elm_t
typedef struct rtree_level_s rtree_level_t
typedef struct rtree_s rtree_t
typedef rtree_node_elm_t *() rtree_node_alloc_t(tsdn_t *, rtree_t *, size_t)
typedef rtree_leaf_elm_t *() rtree_leaf_alloc_t(tsdn_t *, rtree_t *, size_t)
typedef void() rtree_node_dalloc_t(tsdn_t *, rtree_t *, rtree_node_elm_t *)
typedef void() rtree_leaf_dalloc_t(tsdn_t *, rtree_t *, rtree_leaf_elm_t *)
Functions
bool rtree_new (rtree_t *rtree, bool zeroed)
rtree_leaf_elm_t * rtree_leaf_elm_lookup_hard (tsdn_t *tsdn, rtree_t *rtree, rtree_ctx_t *rtree_ctx, uintptr_t key, bool dependent, bool init_missing)
JEMALLOC_ALWAYS_INLINE uintptr_t rtree_leafkey (uintptr_t key)
JEMALLOC_ALWAYS_INLINE size_t rtree_cache_direct_map (uintptr_t key)
JEMALLOC_ALWAYS_INLINE uintptr_t rtree_subkey (uintptr_t key, unsigned level)
JEMALLOC_ALWAYS_INLINE uintptr_t rtree_leaf_elm_bits_read (tsdn_t *tsdn, rtree_t *rtree, rtree_leaf_elm_t *elm, bool dependent)
JEMALLOC_ALWAYS_INLINE extent_t * rtree_leaf_elm_bits_extent_get (uintptr_t bits)
JEMALLOC_ALWAYS_INLINE szind_t rtree_leaf_elm_bits_szind_get (uintptr_t bits)
JEMALLOC_ALWAYS_INLINE bool rtree_leaf_elm_bits_slab_get (uintptr_t bits)
JEMALLOC_ALWAYS_INLINE extent_t * rtree_leaf_elm_extent_read (tsdn_t *tsdn, rtree_t *rtree, rtree_leaf_elm_t *elm, bool dependent)
JEMALLOC_ALWAYS_INLINE szind_t rtree_leaf_elm_szind_read (tsdn_t *tsdn, rtree_t *rtree, rtree_leaf_elm_t *elm, bool dependent)
JEMALLOC_ALWAYS_INLINE bool rtree_leaf_elm_slab_read (tsdn_t *tsdn, rtree_t *rtree, rtree_leaf_elm_t *elm, bool dependent)
static void rtree_leaf_elm_extent_write (tsdn_t *tsdn, rtree_t *rtree, rtree_leaf_elm_t *elm, extent_t *extent)
static void rtree_leaf_elm_szind_write (tsdn_t *tsdn, rtree_t *rtree, rtree_leaf_elm_t *elm, szind_t szind)
static void rtree_leaf_elm_slab_write (tsdn_t *tsdn, rtree_t *rtree, rtree_leaf_elm_t *elm, bool slab)
static void rtree_leaf_elm_write (tsdn_t *tsdn, rtree_t *rtree, rtree_leaf_elm_t *elm, extent_t *extent, szind_t szind, bool slab)
static void rtree_leaf_elm_szind_slab_update (tsdn_t *tsdn, rtree_t *rtree, rtree_leaf_elm_t *elm, szind_t szind, bool slab)
JEMALLOC_ALWAYS_INLINE rtree_leaf_elm_t * rtree_leaf_elm_lookup (tsdn_t *tsdn, rtree_t *rtree, rtree_ctx_t *rtree_ctx, uintptr_t key, bool dependent, bool init_missing)
static bool rtree_write (tsdn_t *tsdn, rtree_t *rtree, rtree_ctx_t *rtree_ctx, uintptr_t key, extent_t *extent, szind_t szind, bool slab)
JEMALLOC_ALWAYS_INLINE rtree_leaf_elm_t * rtree_read (tsdn_t *tsdn, rtree_t *rtree, rtree_ctx_t *rtree_ctx, uintptr_t key, bool dependent)
JEMALLOC_ALWAYS_INLINE extent_t * rtree_extent_read (tsdn_t *tsdn, rtree_t *rtree, rtree_ctx_t *rtree_ctx, uintptr_t key, bool dependent)
JEMALLOC_ALWAYS_INLINE szind_t rtree_szind_read (tsdn_t *tsdn, rtree_t *rtree, rtree_ctx_t *rtree_ctx, uintptr_t key, bool dependent)
JEMALLOC_ALWAYS_INLINE bool rtree_extent_szind_read (tsdn_t *tsdn, rtree_t *rtree, rtree_ctx_t *rtree_ctx, uintptr_t key, bool dependent, extent_t **r_extent, szind_t *r_szind)
JEMALLOC_ALWAYS_INLINE bool rtree_szind_slab_read_fast (tsdn_t *tsdn, rtree_t *rtree, rtree_ctx_t *rtree_ctx, uintptr_t key, szind_t *r_szind, bool *r_slab)
JEMALLOC_ALWAYS_INLINE bool rtree_szind_slab_read (tsdn_t *tsdn, rtree_t *rtree, rtree_ctx_t *rtree_ctx, uintptr_t key, bool dependent, szind_t *r_szind, bool *r_slab)
static void rtree_szind_slab_update (tsdn_t *tsdn, rtree_t *rtree, rtree_ctx_t *rtree_ctx, uintptr_t key, szind_t szind, bool slab)
static void rtree_clear (tsdn_t *tsdn, rtree_t *rtree, rtree_ctx_t *rtree_ctx, uintptr_t key)
Variables
static const rtree_level_t rtree_levels []
rtree_node_alloc_t *JET_MUTABLE rtree_node_alloc
rtree_leaf_alloc_t *JET_MUTABLE rtree_leaf_alloc
rtree_node_dalloc_t *JET_MUTABLE rtree_node_dalloc
rtree_leaf_dalloc_t *JET_MUTABLE rtree_leaf_dalloc
Macro Definition Documentation
RTREE_CACHE_CHECK_L2
#define RTREE_CACHE_CHECK_L2 (i)
Value:
    do {                    \
    if (likely(rtree_ctx->l2_cache[i].leafkey == leafkey)) {    \
        rtree_leaf_elm_t *leaf = rtree_ctx->l2_cache[i].leaf;   \
        assert(leaf != NULL);                   \
        if (i > 0) {                        \
            /* Bubble up by one. */             \
            rtree_ctx->l2_cache[i].leafkey =        \
                rtree_ctx->l2_cache[i - 1].leafkey; \
            rtree_ctx->l2_cache[i].leaf =           \
                rtree_ctx->l2_cache[i - 1].leaf;    \
            rtree_ctx->l2_cache[i - 1].leafkey =        \
                rtree_ctx->cache[slot].leafkey;     \
            rtree_ctx->l2_cache[i - 1].leaf =       \
                rtree_ctx->cache[slot].leaf;        \
        } else {                        \
            rtree_ctx->l2_cache[0].leafkey =        \
                rtree_ctx->cache[slot].leafkey;     \
            rtree_ctx->l2_cache[0].leaf =           \
                rtree_ctx->cache[slot].leaf;        \
        }                           \
        rtree_ctx->cache[slot].leafkey = leafkey;       \
        rtree_ctx->cache[slot].leaf = leaf;         \
        uintptr_t subkey = rtree_subkey(key, RTREE_HEIGHT-1);   \
        return &leaf[subkey];                   \
    }                               \
} while (0)
RTREE_HEIGHT
#define RTREE_HEIGHT 1
Definition at line 25 of file rtree.h.
RTREE_LEAF_COMPACT
#define RTREE_LEAF_COMPACT
Definition at line 35 of file rtree.h.
RTREE_LEAFKEY_INVALID
#define RTREE_LEAFKEY_INVALID ((uintptr_t)1)
Definition at line 39 of file rtree.h.
RTREE_NHIB
#define RTREE_NHIB ((1U << (LG_SIZEOF_PTR+3)) - LG_VADDR)
Definition at line 18 of file rtree.h.
RTREE_NLIB
#define RTREE_NLIB LG_PAGE
Definition at line 20 of file rtree.h.
RTREE_NSB
#define RTREE_NSB (LG_VADDR - RTREE_NLIB)
Definition at line 22 of file rtree.h.
Typedef Documentation
rtree_leaf_alloc_t
typedef rtree_leaf_elm_t*() rtree_leaf_alloc_t(tsdn_t *, rtree_t *, size_t)
Definition at line 117 of file rtree.h.
rtree_leaf_dalloc_t
typedef void() rtree_leaf_dalloc_t(tsdn_t *, rtree_t *, rtree_leaf_elm_t *)
Definition at line 123 of file rtree.h.
rtree_level_t
typedef struct rtree_level_s rtree_level_t
Definition at line 1 of file rtree.h.
rtree_node_alloc_t
typedef rtree_node_elm_t*() rtree_node_alloc_t(tsdn_t *, rtree_t *, size_t)
Definition at line 114 of file rtree.h.
rtree_node_dalloc_t
typedef void() rtree_node_dalloc_t(tsdn_t *, rtree_t *, rtree_node_elm_t *)
Definition at line 120 of file rtree.h.
rtree_node_elm_t
typedef struct rtree_node_elm_s rtree_node_elm_t
Definition at line 1 of file rtree.h.
rtree_t
typedef struct rtree_s rtree_t
Definition at line 1 of file rtree.h.
Function Documentation
rtree_cache_direct_map()
JEMALLOC_ALWAYS_INLINE size_t rtree_cache_direct_map (uintptr_t key)
Definition at line 142 of file rtree.h.
{
     unsigned ptrbits = ZU(1) << (LG_SIZEOF_PTR+3);
     unsigned cumbits = (rtree_levels[RTREE_HEIGHT-1].cumbits -
         rtree_levels[RTREE_HEIGHT-1].bits);
     unsigned maskbits = ptrbits - cumbits;
     return (size_t)((key >> maskbits) & (RTREE_CTX_NCACHE - 1));
 }
References rtree_level_s::bits, rtree_level_s::cumbits, RTREE_CTX_NCACHE, RTREE_HEIGHT, rtree_levels, and ZU.
Referenced by rtree_leaf_elm_lookup(), and rtree_szind_slab_read_fast().
rtree_clear()
static void rtree_clear (tsdn_t * tsdn, rtree_t * rtree, rtree_ctx_t * rtree_ctx, uintptr_t key) inline static
Definition at line 520 of file rtree.h.
                    {
     rtree_leaf_elm_t *elm = rtree_read(tsdn, rtree, rtree_ctx, key, true);
     assert(rtree_leaf_elm_extent_read(tsdn, rtree, elm, false) !=
         NULL);
     rtree_leaf_elm_write(tsdn, rtree, elm, NULL, SC_NSIZES, false);
 }
References assert(), NULL, rtree_leaf_elm_extent_read(), rtree_leaf_elm_write(), rtree_read(), and SC_NSIZES.
Referenced by extent_interior_deregister().
rtree_extent_read()
JEMALLOC_ALWAYS_INLINE extent_t* rtree_extent_read (tsdn_t * tsdn, rtree_t * rtree, rtree_ctx_t * rtree_ctx, uintptr_t key, bool dependent)
Definition at line 416 of file rtree.h.
{
     rtree_leaf_elm_t *elm = rtree_read(tsdn, rtree, rtree_ctx, key,
         dependent);
     if (!dependent && elm == NULL) {
         return NULL;
     }
     return rtree_leaf_elm_extent_read(tsdn, rtree, elm, dependent);
 }
References NULL, rtree_leaf_elm_extent_read(), and rtree_read().
Referenced by arena_dalloc(), arena_dalloc_no_tcache(), arena_prof_promote(), arena_sdalloc(), arena_sdalloc_no_tcache(), extent_record(), and iealloc().
rtree_extent_szind_read()
JEMALLOC_ALWAYS_INLINE bool rtree_extent_szind_read (tsdn_t * tsdn, rtree_t * rtree, rtree_ctx_t * rtree_ctx, uintptr_t key, bool dependent, extent_t ** r_extent, szind_t * r_szind)
Definition at line 443 of file rtree.h.
{
     rtree_leaf_elm_t *elm = rtree_read(tsdn, rtree, rtree_ctx, key,
         dependent);
     if (!dependent && elm == NULL) {
         return true;
     }
     *r_extent = rtree_leaf_elm_extent_read(tsdn, rtree, elm, dependent);
     *r_szind = rtree_leaf_elm_szind_read(tsdn, rtree, elm, dependent);
     return false;
 }
References NULL, rtree_leaf_elm_extent_read(), rtree_leaf_elm_szind_read(), and rtree_read().
Referenced by arena_vsalloc(), and tbin_extents_lookup_size_check().
rtree_leaf_elm_bits_extent_get()
JEMALLOC_ALWAYS_INLINE extent_t* rtree_leaf_elm_bits_extent_get (uintptr_t bits)
Definition at line 180 of file rtree.h.
{
 #    ifdef __aarch64__
     /*
      * aarch64 doesn't sign extend the highest virtual address bit to set
      * the higher ones.  Instead, the high bits gets zeroed.
      */
     uintptr_t high_bit_mask = ((uintptr_t)1 << LG_VADDR) - 1;
     /* Mask off the slab bit. */
     uintptr_t low_bit_mask = ~(uintptr_t)1;
     uintptr_t mask = high_bit_mask & low_bit_mask;
     return (extent_t *)(bits & mask);
 #    else
     /* Restore sign-extended high bits, mask slab bit. */
     return (extent_t *)((uintptr_t)((intptr_t)(bits << RTREE_NHIB) >>
         RTREE_NHIB) & ~((uintptr_t)0x1));
 #    endif
 }
References G3D::bits(), RTREE_NHIB, and uintptr_t.
Referenced by rtree_leaf_elm_extent_read(), rtree_leaf_elm_slab_write(), and rtree_leaf_elm_szind_write().
rtree_leaf_elm_bits_read()
JEMALLOC_ALWAYS_INLINE uintptr_t rtree_leaf_elm_bits_read (tsdn_t * tsdn, rtree_t * rtree, rtree_leaf_elm_t * elm, bool dependent)
Definition at line 173 of file rtree.h.
{
     return (uintptr_t)atomic_load_p(&elm->le_bits, dependent
         ? ATOMIC_RELAXED : ATOMIC_ACQUIRE);
 }
References ATOMIC_ACQUIRE, ATOMIC_RELAXED, and rtree_leaf_elm_s::le_bits.
Referenced by rtree_leaf_elm_extent_read(), rtree_leaf_elm_extent_write(), rtree_leaf_elm_slab_read(), rtree_leaf_elm_slab_write(), rtree_leaf_elm_szind_read(), rtree_leaf_elm_szind_write(), rtree_szind_slab_read(), and rtree_szind_slab_read_fast().
rtree_leaf_elm_bits_slab_get()
JEMALLOC_ALWAYS_INLINE bool rtree_leaf_elm_bits_slab_get (uintptr_t bits)
Definition at line 204 of file rtree.h.
{
     return (bool)(bits & (uintptr_t)0x1);
 }
References G3D::bits(), and uintptr_t.
Referenced by rtree_leaf_elm_extent_write(), rtree_leaf_elm_slab_read(), rtree_leaf_elm_szind_write(), rtree_szind_slab_read(), and rtree_szind_slab_read_fast().
rtree_leaf_elm_bits_szind_get()
JEMALLOC_ALWAYS_INLINE szind_t rtree_leaf_elm_bits_szind_get (uintptr_t bits)
Definition at line 199 of file rtree.h.
{
     return (szind_t)(bits >> LG_VADDR);
 }
References G3D::bits().
Referenced by rtree_leaf_elm_extent_write(), rtree_leaf_elm_slab_write(), rtree_leaf_elm_szind_read(), rtree_szind_slab_read(), and rtree_szind_slab_read_fast().
rtree_leaf_elm_extent_read()
JEMALLOC_ALWAYS_INLINE extent_t* rtree_leaf_elm_extent_read (tsdn_t * tsdn, rtree_t * rtree, rtree_leaf_elm_t * elm, bool dependent)
Definition at line 211 of file rtree.h.
{
 #ifdef RTREE_LEAF_COMPACT
     uintptr_t bits = rtree_leaf_elm_bits_read(tsdn, rtree, elm, dependent);
     return rtree_leaf_elm_bits_extent_get(bits);
 #else
     extent_t *extent = (extent_t *)atomic_load_p(&elm->le_extent, dependent
         ? ATOMIC_RELAXED : ATOMIC_ACQUIRE);
     return extent;
 #endif
 }
References ATOMIC_ACQUIRE, ATOMIC_RELAXED, G3D::bits(), rtree_leaf_elm_bits_extent_get(), and rtree_leaf_elm_bits_read().
Referenced by extent_rtree_leaf_elm_try_lock(), rtree_clear(), rtree_extent_read(), rtree_extent_szind_read(), and rtree_write().
rtree_leaf_elm_extent_write()
static void rtree_leaf_elm_extent_write (tsdn_t * tsdn, rtree_t * rtree, rtree_leaf_elm_t * elm, extent_t * extent) inline static
Definition at line 248 of file rtree.h.
{
 #ifdef RTREE_LEAF_COMPACT
     uintptr_t old_bits = rtree_leaf_elm_bits_read(tsdn, rtree, elm, true);
     uintptr_t bits = ((uintptr_t)rtree_leaf_elm_bits_szind_get(old_bits) <<
         LG_VADDR) | ((uintptr_t)extent & (((uintptr_t)0x1 << LG_VADDR) - 1))
         | ((uintptr_t)rtree_leaf_elm_bits_slab_get(old_bits));
     atomic_store_p(&elm->le_bits, (void *)bits, ATOMIC_RELEASE);
 #else
     atomic_store_p(&elm->le_extent, extent, ATOMIC_RELEASE);
 #endif
 }
References ATOMIC_RELEASE, G3D::bits(), rtree_leaf_elm_s::le_bits, rtree_leaf_elm_bits_read(), rtree_leaf_elm_bits_slab_get(), rtree_leaf_elm_bits_szind_get(), and uintptr_t.
Referenced by rtree_leaf_elm_write().
rtree_leaf_elm_lookup()
JEMALLOC_ALWAYS_INLINE rtree_leaf_elm_t* rtree_leaf_elm_lookup (tsdn_t * tsdn, rtree_t * rtree, rtree_ctx_t * rtree_ctx, uintptr_t key, bool dependent, bool init_missing)
Definition at line 327 of file rtree.h.
{
     assert(key != 0);
     assert(!dependent || !init_missing);
     size_t slot = rtree_cache_direct_map(key);
     uintptr_t leafkey = rtree_leafkey(key);
     assert(leafkey != RTREE_LEAFKEY_INVALID);
     /* Fast path: L1 direct mapped cache. */
     if (likely(rtree_ctx->cache[slot].leafkey == leafkey)) {
         rtree_leaf_elm_t *leaf = rtree_ctx->cache[slot].leaf;
         assert(leaf != NULL);
         uintptr_t subkey = rtree_subkey(key, RTREE_HEIGHT-1);
         return &leaf[subkey];
     }
     /*
      * Search the L2 LRU cache.  On hit, swap the matching element into the
      * slot in L1 cache, and move the position in L2 up by 1.
      */
 #define RTREE_CACHE_CHECK_L2(i) do {                    \
     if (likely(rtree_ctx->l2_cache[i].leafkey == leafkey)) {    \
         rtree_leaf_elm_t *leaf = rtree_ctx->l2_cache[i].leaf;   \
         assert(leaf != NULL);                   \
         if (i > 0) {                        \
             /* Bubble up by one. */             \
             rtree_ctx->l2_cache[i].leafkey =        \
                 rtree_ctx->l2_cache[i - 1].leafkey; \
             rtree_ctx->l2_cache[i].leaf =           \
                 rtree_ctx->l2_cache[i - 1].leaf;    \
             rtree_ctx->l2_cache[i - 1].leafkey =        \
                 rtree_ctx->cache[slot].leafkey;     \
             rtree_ctx->l2_cache[i - 1].leaf =       \
                 rtree_ctx->cache[slot].leaf;        \
         } else {                        \
             rtree_ctx->l2_cache[0].leafkey =        \
                 rtree_ctx->cache[slot].leafkey;     \
             rtree_ctx->l2_cache[0].leaf =           \
                 rtree_ctx->cache[slot].leaf;        \
         }                           \
         rtree_ctx->cache[slot].leafkey = leafkey;       \
         rtree_ctx->cache[slot].leaf = leaf;         \
         uintptr_t subkey = rtree_subkey(key, RTREE_HEIGHT-1);   \
         return &leaf[subkey];                   \
     }                               \
 } while (0)
     /* Check the first cache entry. */
     RTREE_CACHE_CHECK_L2(0);
     /* Search the remaining cache elements. */
     for (unsigned i = 1; i < RTREE_CTX_NCACHE_L2; i++) {
         RTREE_CACHE_CHECK_L2(i);
     }
 #undef RTREE_CACHE_CHECK_L2
     return rtree_leaf_elm_lookup_hard(tsdn, rtree, rtree_ctx, key,
         dependent, init_missing);
 }
References assert(), rtree_ctx_s::cache, rtree_ctx_cache_elm_s::leaf, rtree_ctx_cache_elm_s::leafkey, likely, NULL, RTREE_CACHE_CHECK_L2, rtree_cache_direct_map(), RTREE_CTX_NCACHE_L2, RTREE_HEIGHT, rtree_leaf_elm_lookup_hard(), rtree_leafkey(), RTREE_LEAFKEY_INVALID, and rtree_subkey().
Referenced by extent_lock_from_addr(), extent_rtree_leaf_elms_lookup(), rtree_read(), and rtree_write().
rtree_leaf_elm_lookup_hard()
rtree_leaf_elm_t* rtree_leaf_elm_lookup_hard (tsdn_t * tsdn, rtree_t * rtree, rtree_ctx_t * rtree_ctx, uintptr_t key, bool dependent, bool init_missing)
Definition at line 223 of file rtree.c.
{
     rtree_node_elm_t *node;
     rtree_leaf_elm_t *leaf;
 #if RTREE_HEIGHT > 1
     node = rtree->root;
 #else
     leaf = rtree->root;
 #endif
     if (config_debug) {
         uintptr_t leafkey = rtree_leafkey(key);
         for (unsigned i = 0; i < RTREE_CTX_NCACHE; i++) {
             assert(rtree_ctx->cache[i].leafkey != leafkey);
         }
         for (unsigned i = 0; i < RTREE_CTX_NCACHE_L2; i++) {
             assert(rtree_ctx->l2_cache[i].leafkey != leafkey);
         }
     }
 #define RTREE_GET_CHILD(level) {                    \
         assert(level < RTREE_HEIGHT-1);             \
         if (level != 0 && !dependent &&             \
             unlikely(!rtree_node_valid(node))) {        \
             return NULL;                    \
         }                           \
         uintptr_t subkey = rtree_subkey(key, level);        \
         if (level + 2 < RTREE_HEIGHT) {             \
             node = init_missing ?               \
                 rtree_child_node_read(tsdn, rtree,      \
                 &node[subkey], level, dependent) :      \
                 rtree_child_node_tryread(&node[subkey], \
                 dependent);                 \
         } else {                        \
             leaf = init_missing ?               \
                 rtree_child_leaf_read(tsdn, rtree,      \
                 &node[subkey], level, dependent) :      \
                 rtree_child_leaf_tryread(&node[subkey], \
                 dependent);                 \
         }                           \
     }
     /*
      * Cache replacement upon hard lookup (i.e. L1 & L2 rtree cache miss):
      * (1) evict last entry in L2 cache; (2) move the collision slot from L1
      * cache down to L2; and 3) fill L1.
      */
 #define RTREE_GET_LEAF(level) {                     \
         assert(level == RTREE_HEIGHT-1);            \
         if (!dependent && unlikely(!rtree_leaf_valid(leaf))) {  \
             return NULL;                    \
         }                           \
         if (RTREE_CTX_NCACHE_L2 > 1) {              \
             memmove(&rtree_ctx->l2_cache[1],        \
                 &rtree_ctx->l2_cache[0],            \
                 sizeof(rtree_ctx_cache_elm_t) *     \
                 (RTREE_CTX_NCACHE_L2 - 1));         \
         }                           \
         size_t slot = rtree_cache_direct_map(key);      \
         rtree_ctx->l2_cache[0].leafkey =            \
             rtree_ctx->cache[slot].leafkey;         \
         rtree_ctx->l2_cache[0].leaf =               \
             rtree_ctx->cache[slot].leaf;            \
         uintptr_t leafkey = rtree_leafkey(key);         \
         rtree_ctx->cache[slot].leafkey = leafkey;       \
         rtree_ctx->cache[slot].leaf = leaf;         \
         uintptr_t subkey = rtree_subkey(key, level);        \
         return &leaf[subkey];                   \
     }
     if (RTREE_HEIGHT > 1) {
         RTREE_GET_CHILD(0)
     }
     if (RTREE_HEIGHT > 2) {
         RTREE_GET_CHILD(1)
     }
     if (RTREE_HEIGHT > 3) {
         for (unsigned i = 2; i < RTREE_HEIGHT-1; i++) {
             RTREE_GET_CHILD(i)
         }
     }
     RTREE_GET_LEAF(RTREE_HEIGHT-1)
 #undef RTREE_GET_CHILD
 #undef RTREE_GET_LEAF
     not_reached();
 }
References assert(), rtree_ctx_s::cache, config_debug, rtree_ctx_s::l2_cache, rtree_ctx_cache_elm_s::leafkey, not_reached, rtree_s::root, RTREE_CTX_NCACHE, RTREE_CTX_NCACHE_L2, RTREE_GET_CHILD, RTREE_GET_LEAF, RTREE_HEIGHT, and rtree_leafkey().
Referenced by rtree_leaf_elm_lookup().
rtree_leaf_elm_slab_read()
JEMALLOC_ALWAYS_INLINE bool rtree_leaf_elm_slab_read (tsdn_t * tsdn, rtree_t * rtree, rtree_leaf_elm_t * elm, bool dependent)
Definition at line 236 of file rtree.h.
{
 #ifdef RTREE_LEAF_COMPACT
     uintptr_t bits = rtree_leaf_elm_bits_read(tsdn, rtree, elm, dependent);
     return rtree_leaf_elm_bits_slab_get(bits);
 #else
     return atomic_load_b(&elm->le_slab, dependent ? ATOMIC_RELAXED :
         ATOMIC_ACQUIRE);
 #endif
 }
References ATOMIC_ACQUIRE, ATOMIC_RELAXED, G3D::bits(), rtree_leaf_elm_bits_read(), and rtree_leaf_elm_bits_slab_get().
Referenced by extent_rtree_leaf_elm_try_lock(), rtree_szind_slab_read(), and rtree_szind_slab_read_fast().
rtree_leaf_elm_slab_write()
static void rtree_leaf_elm_slab_write (tsdn_t * tsdn, rtree_t * rtree, rtree_leaf_elm_t * elm, bool slab) inline static
Definition at line 280 of file rtree.h.
{
 #ifdef RTREE_LEAF_COMPACT
     uintptr_t old_bits = rtree_leaf_elm_bits_read(tsdn, rtree, elm,
         true);
     uintptr_t bits = ((uintptr_t)rtree_leaf_elm_bits_szind_get(old_bits) <<
         LG_VADDR) | ((uintptr_t)rtree_leaf_elm_bits_extent_get(old_bits) &
         (((uintptr_t)0x1 << LG_VADDR) - 1)) | ((uintptr_t)slab);
     atomic_store_p(&elm->le_bits, (void *)bits, ATOMIC_RELEASE);
 #else
     atomic_store_b(&elm->le_slab, slab, ATOMIC_RELEASE);
 #endif
 }
References ATOMIC_RELEASE, G3D::bits(), rtree_leaf_elm_s::le_bits, rtree_leaf_elm_bits_extent_get(), rtree_leaf_elm_bits_read(), rtree_leaf_elm_bits_szind_get(), and uintptr_t.
Referenced by rtree_leaf_elm_szind_slab_update(), and rtree_leaf_elm_write().
rtree_leaf_elm_szind_read()
JEMALLOC_ALWAYS_INLINE szind_t rtree_leaf_elm_szind_read (tsdn_t * tsdn, rtree_t * rtree, rtree_leaf_elm_t * elm, bool dependent)
Definition at line 224 of file rtree.h.
{
 #ifdef RTREE_LEAF_COMPACT
     uintptr_t bits = rtree_leaf_elm_bits_read(tsdn, rtree, elm, dependent);
     return rtree_leaf_elm_bits_szind_get(bits);
 #else
     return (szind_t)atomic_load_u(&elm->le_szind, dependent ? ATOMIC_RELAXED
         : ATOMIC_ACQUIRE);
 #endif
 }
References ATOMIC_ACQUIRE, ATOMIC_RELAXED, G3D::bits(), rtree_leaf_elm_bits_read(), and rtree_leaf_elm_bits_szind_get().
Referenced by rtree_extent_szind_read(), rtree_szind_read(), rtree_szind_slab_read(), and rtree_szind_slab_read_fast().
rtree_leaf_elm_szind_slab_update()
static void rtree_leaf_elm_szind_slab_update (tsdn_t * tsdn, rtree_t * rtree, rtree_leaf_elm_t * elm, szind_t szind, bool slab) inline static
Definition at line 314 of file rtree.h.
{
     assert(!slab || szind < SC_NBINS);
     /*
      * The caller implicitly assures that it is the only writer to the szind
      * and slab fields, and that the extent field cannot currently change.
      */
     rtree_leaf_elm_slab_write(tsdn, rtree, elm, slab);
     rtree_leaf_elm_szind_write(tsdn, rtree, elm, szind);
 }
References assert(), rtree_leaf_elm_slab_write(), rtree_leaf_elm_szind_write(), and SC_NBINS.
Referenced by rtree_szind_slab_update().
rtree_leaf_elm_szind_write()
static void rtree_leaf_elm_szind_write (tsdn_t * tsdn, rtree_t * rtree, rtree_leaf_elm_t * elm, szind_t szind) inline static
Definition at line 262 of file rtree.h.
{
     assert(szind <= SC_NSIZES);
 #ifdef RTREE_LEAF_COMPACT
     uintptr_t old_bits = rtree_leaf_elm_bits_read(tsdn, rtree, elm,
         true);
     uintptr_t bits = ((uintptr_t)szind << LG_VADDR) |
         ((uintptr_t)rtree_leaf_elm_bits_extent_get(old_bits) &
         (((uintptr_t)0x1 << LG_VADDR) - 1)) |
         ((uintptr_t)rtree_leaf_elm_bits_slab_get(old_bits));
     atomic_store_p(&elm->le_bits, (void *)bits, ATOMIC_RELEASE);
 #else
     atomic_store_u(&elm->le_szind, szind, ATOMIC_RELEASE);
 #endif
 }
References assert(), ATOMIC_RELEASE, G3D::bits(), rtree_leaf_elm_s::le_bits, rtree_leaf_elm_bits_extent_get(), rtree_leaf_elm_bits_read(), rtree_leaf_elm_bits_slab_get(), SC_NSIZES, and uintptr_t.
Referenced by rtree_leaf_elm_szind_slab_update(), and rtree_leaf_elm_write().
rtree_leaf_elm_write()
static void rtree_leaf_elm_write (tsdn_t * tsdn, rtree_t * rtree, rtree_leaf_elm_t * elm, extent_t * extent, szind_t szind, bool slab) inline static
Definition at line 295 of file rtree.h.
{
 #ifdef RTREE_LEAF_COMPACT
     uintptr_t bits = ((uintptr_t)szind << LG_VADDR) |
         ((uintptr_t)extent & (((uintptr_t)0x1 << LG_VADDR) - 1)) |
         ((uintptr_t)slab);
     atomic_store_p(&elm->le_bits, (void *)bits, ATOMIC_RELEASE);
 #else
     rtree_leaf_elm_slab_write(tsdn, rtree, elm, slab);
     rtree_leaf_elm_szind_write(tsdn, rtree, elm, szind);
     /*
      * Write extent last, since the element is atomically considered valid
      * as soon as the extent field is non-NULL.
      */
     rtree_leaf_elm_extent_write(tsdn, rtree, elm, extent);
 #endif
 }
References ATOMIC_RELEASE, G3D::bits(), rtree_leaf_elm_s::le_bits, rtree_leaf_elm_extent_write(), rtree_leaf_elm_slab_write(), rtree_leaf_elm_szind_write(), and uintptr_t.
Referenced by extent_merge_impl(), extent_rtree_write_acquired(), rtree_clear(), and rtree_write().
rtree_leafkey()
JEMALLOC_ALWAYS_INLINE uintptr_t rtree_leafkey (uintptr_t key)
Definition at line 132 of file rtree.h.
{
     unsigned ptrbits = ZU(1) << (LG_SIZEOF_PTR+3);
     unsigned cumbits = (rtree_levels[RTREE_HEIGHT-1].cumbits -
         rtree_levels[RTREE_HEIGHT-1].bits);
     unsigned maskbits = ptrbits - cumbits;
     uintptr_t mask = ~((ZU(1) << maskbits) - 1);
     return (key & mask);
 }
References rtree_level_s::bits, rtree_level_s::cumbits, RTREE_HEIGHT, rtree_levels, and ZU.
Referenced by rtree_leaf_elm_lookup(), rtree_leaf_elm_lookup_hard(), and rtree_szind_slab_read_fast().
rtree_new()
bool rtree_new (rtree_t * rtree, bool zeroed)
Definition at line 13 of file rtree.c.
{
 #ifdef JEMALLOC_JET
     if (!zeroed) {
         memset(rtree, 0, sizeof(rtree_t)); /* Clear root. */
     }
 #else
     assert(zeroed);
 #endif
     if (malloc_mutex_init(&rtree->init_lock, "rtree", WITNESS_RANK_RTREE,
         malloc_mutex_rank_exclusive)) {
         return true;
     }
     return false;
 }
References assert(), rtree_s::init_lock, malloc_mutex_init, malloc_mutex_rank_exclusive, memset, and WITNESS_RANK_RTREE.
rtree_read()
JEMALLOC_ALWAYS_INLINE rtree_leaf_elm_t* rtree_read (tsdn_t * tsdn, rtree_t * rtree, rtree_ctx_t * rtree_ctx, uintptr_t key, bool dependent)
Definition at line 404 of file rtree.h.
                     {
     rtree_leaf_elm_t *elm = rtree_leaf_elm_lookup(tsdn, rtree, rtree_ctx,
         key, dependent, false);
     if (!dependent && elm == NULL) {
         return NULL;
     }
     assert(elm != NULL);
     return elm;
 }
References assert(), NULL, and rtree_leaf_elm_lookup().
Referenced by rtree_clear(), rtree_extent_read(), rtree_extent_szind_read(), rtree_szind_read(), rtree_szind_slab_read(), and rtree_szind_slab_update().
rtree_subkey()
JEMALLOC_ALWAYS_INLINE uintptr_t rtree_subkey (uintptr_t key, unsigned level)
Definition at line 151 of file rtree.h.
{
     unsigned ptrbits = ZU(1) << (LG_SIZEOF_PTR+3);
     unsigned cumbits = rtree_levels[level].cumbits;
     unsigned shiftbits = ptrbits - cumbits;
     unsigned maskbits = rtree_levels[level].bits;
     uintptr_t mask = (ZU(1) << maskbits) - 1;
     return ((key >> shiftbits) & mask);
 }
References rtree_level_s::bits, rtree_level_s::cumbits, rtree_levels, and ZU.
Referenced by rtree_leaf_elm_lookup(), and rtree_szind_slab_read_fast().
rtree_szind_read()
JEMALLOC_ALWAYS_INLINE szind_t rtree_szind_read (tsdn_t * tsdn, rtree_t * rtree, rtree_ctx_t * rtree_ctx, uintptr_t key, bool dependent)
Definition at line 427 of file rtree.h.
{
     rtree_leaf_elm_t *elm = rtree_read(tsdn, rtree, rtree_ctx, key,
         dependent);
     if (!dependent && elm == NULL) {
         return SC_NSIZES;
     }
     return rtree_leaf_elm_szind_read(tsdn, rtree, elm, dependent);
 }
References NULL, rtree_leaf_elm_szind_read(), rtree_read(), and SC_NSIZES.
Referenced by arena_salloc().
rtree_szind_slab_read()
JEMALLOC_ALWAYS_INLINE bool rtree_szind_slab_read (tsdn_t * tsdn, rtree_t * rtree, rtree_ctx_t * rtree_ctx, uintptr_t key, bool dependent, szind_t * r_szind, bool * r_slab)
Definition at line 492 of file rtree.h.
{
     rtree_leaf_elm_t *elm = rtree_read(tsdn, rtree, rtree_ctx, key,
         dependent);
     if (!dependent && elm == NULL) {
         return true;
     }
 #ifdef RTREE_LEAF_COMPACT
     uintptr_t bits = rtree_leaf_elm_bits_read(tsdn, rtree, elm, dependent);
     *r_szind = rtree_leaf_elm_bits_szind_get(bits);
     *r_slab = rtree_leaf_elm_bits_slab_get(bits);
 #else
     *r_szind = rtree_leaf_elm_szind_read(tsdn, rtree, elm, dependent);
     *r_slab = rtree_leaf_elm_slab_read(tsdn, rtree, elm, dependent);
 #endif
     return false;
 }
References G3D::bits(), NULL, rtree_leaf_elm_bits_read(), rtree_leaf_elm_bits_slab_get(), rtree_leaf_elm_bits_szind_get(), rtree_leaf_elm_slab_read(), rtree_leaf_elm_szind_read(), and rtree_read().
Referenced by arena_dalloc(), arena_dalloc_no_tcache(), arena_reset(), arena_sdalloc(), arena_sdalloc_no_tcache(), ifree(), isfree(), je_rallocx(), je_realloc(), and je_xallocx().
rtree_szind_slab_read_fast()
JEMALLOC_ALWAYS_INLINE bool rtree_szind_slab_read_fast (tsdn_t * tsdn, rtree_t * rtree, rtree_ctx_t * rtree_ctx, uintptr_t key, szind_t * r_szind, bool * r_slab)
Definition at line 463 of file rtree.h.
{
     rtree_leaf_elm_t *elm;
     size_t slot = rtree_cache_direct_map(key);
     uintptr_t leafkey = rtree_leafkey(key);
     assert(leafkey != RTREE_LEAFKEY_INVALID);
     if (likely(rtree_ctx->cache[slot].leafkey == leafkey)) {
         rtree_leaf_elm_t *leaf = rtree_ctx->cache[slot].leaf;
         assert(leaf != NULL);
         uintptr_t subkey = rtree_subkey(key, RTREE_HEIGHT-1);
         elm = &leaf[subkey];
 #ifdef RTREE_LEAF_COMPACT
         uintptr_t bits = rtree_leaf_elm_bits_read(tsdn, rtree,
                               elm, true);
         *r_szind = rtree_leaf_elm_bits_szind_get(bits);
         *r_slab = rtree_leaf_elm_bits_slab_get(bits);
 #else
         *r_szind = rtree_leaf_elm_szind_read(tsdn, rtree, elm, true);
         *r_slab = rtree_leaf_elm_slab_read(tsdn, rtree, elm, true);
 #endif
         return true;
     } else {
         return false;
     }
 }
References assert(), G3D::bits(), rtree_ctx_s::cache, rtree_ctx_cache_elm_s::leaf, rtree_ctx_cache_elm_s::leafkey, likely, NULL, rtree_cache_direct_map(), RTREE_HEIGHT, rtree_leaf_elm_bits_read(), rtree_leaf_elm_bits_slab_get(), rtree_leaf_elm_bits_szind_get(), rtree_leaf_elm_slab_read(), rtree_leaf_elm_szind_read(), rtree_leafkey(), RTREE_LEAFKEY_INVALID, and rtree_subkey().
Referenced by free_fastpath().
rtree_szind_slab_update()
static void rtree_szind_slab_update (tsdn_t * tsdn, rtree_t * rtree, rtree_ctx_t * rtree_ctx, uintptr_t key, szind_t szind, bool slab) inline static
Definition at line 511 of file rtree.h.
{
     assert(!slab || szind < SC_NBINS);
     rtree_leaf_elm_t *elm = rtree_read(tsdn, rtree, rtree_ctx, key, true);
     rtree_leaf_elm_szind_slab_update(tsdn, rtree, elm, szind, slab);
 }
References assert(), rtree_leaf_elm_szind_slab_update(), rtree_read(), and SC_NBINS.
Referenced by arena_prof_demote(), arena_prof_promote(), extent_split_interior(), and large_ralloc_no_move_expand().
rtree_write()
static bool rtree_write (tsdn_t * tsdn, rtree_t * rtree, rtree_ctx_t * rtree_ctx, uintptr_t key, extent_t * extent, szind_t szind, bool slab) inline static
Definition at line 386 of file rtree.h.
{
     /* Use rtree_clear() to set the extent to NULL. */
     assert(extent != NULL);
     rtree_leaf_elm_t *elm = rtree_leaf_elm_lookup(tsdn, rtree, rtree_ctx,
         key, false, true);
     if (elm == NULL) {
         return true;
     }
     assert(rtree_leaf_elm_extent_read(tsdn, rtree, elm, false) == NULL);
     rtree_leaf_elm_write(tsdn, rtree, elm, extent, szind, slab);
     return false;
 }
References assert(), NULL, rtree_leaf_elm_extent_read(), rtree_leaf_elm_lookup(), and rtree_leaf_elm_write().
Referenced by extent_interior_register().
Variable Documentation
rtree_leaf_alloc
rtree_leaf_alloc_t* JET_MUTABLE rtree_leaf_alloc extern
Definition at line 50 of file rtree.c.
Referenced by rtree_leaf_init().
rtree_leaf_dalloc
rtree_leaf_dalloc_t* JET_MUTABLE rtree_leaf_dalloc extern
Definition at line 57 of file rtree.c.
rtree_levels
const rtree_level_t rtree_levels[] static
Initial value:
= {
    {RTREE_NSB, RTREE_NHIB + RTREE_NSB}
}
Definition at line 96 of file rtree.h.
Referenced by rtree_cache_direct_map(), rtree_leaf_init(), rtree_leafkey(), rtree_node_init(), and rtree_subkey().
rtree_node_alloc
rtree_node_alloc_t* JET_MUTABLE rtree_node_alloc extern
Definition at line 35 of file rtree.c.
Referenced by rtree_node_init().
rtree_node_dalloc
rtree_node_dalloc_t* JET_MUTABLE rtree_node_dalloc extern
Definition at line 42 of file rtree.c.