Azerotcore-wotlk: go_darkmoon_faire_music::go_darkmoon_faire_musicAI Struct Reference
go_darkmoon_faire_music::go_darkmoon_faire_musicAI Struct Reference
Public Member Functions
go_darkmoon_faire_musicAI (GameObject *go)
void UpdateAI (uint32 diff) override
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32)
virtual ObjectGuid GetGUID (int32) const
virtual bool GossipHello (Player *, bool)
virtual bool GossipSelect (Player *, uint32, uint32)
virtual bool GossipSelectCode (Player *, uint32, uint32, char const *)
virtual bool QuestAccept (Player *, Quest const *)
virtual bool QuestReward (Player *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *)
virtual void Destroyed (Player *, uint32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void OnGameEvent (bool, uint16)
virtual void OnStateChanged (uint32, Unit *)
virtual void EventInform (uint32)
virtual void SpellHit (Unit *, const SpellInfo *)
virtual bool CanBeSeen (Player const *)
Public Attributes
uint32 rnd
Private Attributes
EventMap _events
Additional Inherited Members
Static Public Member Functions inherited from GameObjectAI
static int Permissible (GameObject const *go)
Protected Attributes inherited from GameObjectAI
GameObject *const me
Detailed Description
Definition at line 688 of file go_scripts.cpp.
Constructor & Destructor Documentation
go_darkmoon_faire_musicAI()
go_darkmoon_faire_music::go_darkmoon_faire_musicAI::go_darkmoon_faire_musicAI (GameObject * go) inline
Definition at line 692 of file go_scripts.cpp.
                                                   : GameObjectAI(go)
         {
             _events.ScheduleEvent(EVENT_DFM_START_MUSIC, 1000);
         }
References _events, EVENT_DFM_START_MUSIC, and EventMap::ScheduleEvent().
Member Function Documentation
UpdateAI()
void go_darkmoon_faire_music::go_darkmoon_faire_musicAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from GameObjectAI.
Definition at line 697 of file go_scripts.cpp.
         {
             _events.Update(diff);
             while (uint32 eventId = _events.ExecuteEvent())
             {
                 switch (eventId)
                 {
                     case EVENT_DFM_START_MUSIC:
                         if (!IsHolidayActive(HOLIDAY_DARKMOON_FAIRE_ELWYNN) || !IsHolidayActive(HOLIDAY_DARKMOON_FAIRE_THUNDER) || !IsHolidayActive(HOLIDAY_DARKMOON_FAIRE_SHATTRATH))
                             break;
                         me->PlayDirectMusic(MUSIC_DARKMOON_FAIRE_MUSIC);
                         _events.ScheduleEvent(EVENT_DFM_START_MUSIC, 5000);  // Every 5 second's SMSG_PLAY_MUSIC packet (PlayDirectMusic) is pushed to the client (sniffed value)
                         break;
                     default:
                         break;
                 }
             }
         }
References _events, EVENT_DFM_START_MUSIC, EventMap::ExecuteEvent(), HOLIDAY_DARKMOON_FAIRE_ELWYNN, HOLIDAY_DARKMOON_FAIRE_SHATTRATH, HOLIDAY_DARKMOON_FAIRE_THUNDER, IsHolidayActive(), GameObjectAI::me, MUSIC_DARKMOON_FAIRE_MUSIC, WorldObject::PlayDirectMusic(), EventMap::ScheduleEvent(), and EventMap::Update().
Member Data Documentation
_events
EventMap go_darkmoon_faire_music::go_darkmoon_faire_musicAI::_events private
Definition at line 716 of file go_scripts.cpp.
Referenced by go_darkmoon_faire_musicAI(), and UpdateAI().
rnd
uint32 go_darkmoon_faire_music::go_darkmoon_faire_musicAI::rnd
Definition at line 690 of file go_scripts.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/World/go_scripts.cpp