Azerotcore-wotlk: boss_novos::boss_novosAI Struct Reference
boss_novos::boss_novosAI Struct Reference
Public Member Functions
boss_novosAI (Creature *creature)
void Reset () override
uint32 GetData (uint32 data) const override
void SetData (uint32 type, uint32) override
void MoveInLineOfSight (Unit *) override
void EnterCombat (Unit *who) override
void JustDied (Unit *killer) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *summon) override
void UpdateAI (uint32 diff) override
bool CheckEvadeIfOutOfCombatArea () const override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
uint8 _crystalCounter
uint8 _stage
ObjectGuid _summonTargetRightGUID
ObjectGuid _summonTargetLeftGUID
bool _achievement
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 82 of file boss_novos.cpp.
Constructor & Destructor Documentation
boss_novosAI()
boss_novos::boss_novosAI::boss_novosAI (Creature * creature) inline
Definition at line 84 of file boss_novos.cpp.
                                          : BossAI(creature, DATA_NOVOS)
         {
         }
Member Function Documentation
CheckEvadeIfOutOfCombatArea()
bool boss_novos::boss_novosAI::CheckEvadeIfOutOfCombatArea () const inline override virtual
Reimplemented from ScriptedAI.
Definition at line 251 of file boss_novos.cpp.
         {
             return !SelectTargetFromPlayerList(80.0f);
         }
References ScriptedAI::SelectTargetFromPlayerList().
EnterCombat()
void boss_novos::boss_novosAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from BossAI.
Definition at line 120 of file boss_novos.cpp.
         {
             Talk(SAY_AGGRO);
             BossAI::EnterCombat(who);
             events.ScheduleEvent(EVENT_SUMMON_FETID_TROLL, 3000);
             events.ScheduleEvent(EVENT_SUMMON_SHADOWCASTER, 9000);
             events.ScheduleEvent(EVENT_SUMMON_HULKING_CORPSE, 30000);
             events.ScheduleEvent(EVENT_SUMMON_CRYSTAL_HANDLER, 20000);
             events.ScheduleEvent(EVENT_CHECK_PHASE, 80000);
             me->CastSpell(me, SPELL_ARCANE_BLAST, true);
             me->CastSpell(me, SPELL_ARCANE_FIELD, true);
             me->CastSpell(me, SPELL_DESPAWN_CRYSTAL_HANDLER, true);
             for (auto itr : npcSummon)
             {
                 uint32 summonEntry;
                 Position summonPos;
                 std::tie(summonEntry, summonPos) = itr.second;
                 if (Creature* creature = me->SummonCreature(summonEntry, summonPos))
                     switch (itr.first)
                     {
                         case ROOM_LEFT:
                             _summonTargetLeftGUID = creature->GetGUID();
                             break;
                         case ROOM_RIGHT:
                             _summonTargetRightGUID = creature->GetGUID();
                             break;
                     }
             }
             me->SetGuidValue(UNIT_FIELD_TARGET, ObjectGuid::Empty);
             me->RemoveAllAuras();
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
         }
References _summonTargetLeftGUID, _summonTargetRightGUID, Unit::CastSpell(), ObjectGuid::Empty, BossAI::EnterCombat(), EVENT_CHECK_PHASE, EVENT_SUMMON_CRYSTAL_HANDLER, EVENT_SUMMON_FETID_TROLL, EVENT_SUMMON_HULKING_CORPSE, EVENT_SUMMON_SHADOWCASTER, ScriptedAI::me, npcSummon, Unit::RemoveAllAuras(), ROOM_LEFT, ROOM_RIGHT, SAY_AGGRO, Object::SetFlag(), Object::SetGuidValue(), SPELL_ARCANE_BLAST, SPELL_ARCANE_FIELD, SPELL_DESPAWN_CRYSTAL_HANDLER, WorldObject::SummonCreature(), CreatureAI::Talk(), UNIT_FIELD_FLAGS, UNIT_FIELD_TARGET, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
GetData()
uint32 boss_novos::boss_novosAI::GetData (uint32 data) const inline override virtual
Reimplemented from UnitAI.
Definition at line 105 of file boss_novos.cpp.
         {
             if (data == me->GetEntry())
                 return uint32(_achievement);
             return 0;
         }
References _achievement, Object::GetEntry(), and ScriptedAI::me.
JustDied()
void boss_novos::boss_novosAI::JustDied (Unit * killer) inline override virtual
Reimplemented from BossAI.
Definition at line 158 of file boss_novos.cpp.
         {
             Talk(SAY_DEATH);
             BossAI::JustDied(killer);
             instance->SetBossState(DATA_NOVOS_CRYSTALS, DONE);
         }
References DATA_NOVOS_CRYSTALS, DONE, BossAI::instance, BossAI::JustDied(), SAY_DEATH, InstanceScript::SetBossState(), and CreatureAI::Talk().
JustSummoned()
void boss_novos::boss_novosAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
Definition at line 174 of file boss_novos.cpp.
         {
             summons.Summon(summon);
             if (me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE) && summon->GetEntry() != NPC_CRYSTAL_CHANNEL_TARGET && summon->GetEntry() != NPC_CRYSTAL_HANDLER)
                 summon->SetReactState(REACT_DEFENSIVE);
             else if (summon->GetEntry() != NPC_CRYSTAL_CHANNEL_TARGET)
                 summon->SetInCombatWithZone();
         }
References Object::GetEntry(), Object::HasFlag(), ScriptedAI::me, NPC_CRYSTAL_CHANNEL_TARGET, NPC_CRYSTAL_HANDLER, REACT_DEFENSIVE, Creature::SetInCombatWithZone(), Creature::SetReactState(), SummonList::Summon(), BossAI::summons, UNIT_FIELD_FLAGS, and UNIT_FLAG_NOT_SELECTABLE.
KilledUnit()
void boss_novos::boss_novosAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 165 of file boss_novos.cpp.
         {
             if (events.GetNextEventTime(EVENT_KILL_TALK) == 0)
             {
                 Talk(SAY_KILL);
                 events.ScheduleEvent(EVENT_KILL_TALK, 6000);
             }
         }
References EVENT_KILL_TALK, SAY_KILL, and CreatureAI::Talk().
MoveInLineOfSight()
void boss_novos::boss_novosAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 118 of file boss_novos.cpp.
 { }
Reset()
void boss_novos::boss_novosAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 88 of file boss_novos.cpp.
         {
             BossAI::Reset();
             instance->SetBossState(DATA_NOVOS_CRYSTALS, IN_PROGRESS);
             instance->SetBossState(DATA_NOVOS_CRYSTALS, NOT_STARTED);
             _crystalCounter = 0;
             _summonTargetRightGUID.Clear();
             _summonTargetLeftGUID.Clear();
             _stage = 0;
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE);
             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
             _achievement = true;
         }
References _achievement, _crystalCounter, _stage, _summonTargetLeftGUID, _summonTargetRightGUID, ObjectGuid::Clear(), DATA_NOVOS_CRYSTALS, IN_PROGRESS, BossAI::instance, ScriptedAI::me, NOT_STARTED, Object::RemoveFlag(), BossAI::Reset(), InstanceScript::SetBossState(), Object::SetFlag(), UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
SetData()
void boss_novos::boss_novosAI::SetData (uint32 type, uint32) inline override virtual
Reimplemented from UnitAI.
Definition at line 112 of file boss_novos.cpp.
         {
             if (type == me->GetEntry())
                 _achievement = false;
         }
References _achievement, Object::GetEntry(), and ScriptedAI::me.
UpdateAI()
void boss_novos::boss_novosAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 183 of file boss_novos.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             switch (events.ExecuteEvent())
             {
                 case EVENT_SUMMON_FETID_TROLL:
                     if (Creature* trigger = summons.GetCreatureWithEntry(NPC_CRYSTAL_CHANNEL_TARGET))
                         trigger->CastSpell(trigger, SPELL_SUMMON_FETID_TROLL_CORPSE, true, nullptr, nullptr, me->GetGUID());
                     events.ScheduleEvent(EVENT_SUMMON_FETID_TROLL, 3000);
                     break;
                 case EVENT_SUMMON_HULKING_CORPSE:
                     if (Creature* trigger = summons.GetCreatureWithEntry(NPC_CRYSTAL_CHANNEL_TARGET))
                         trigger->CastSpell(trigger, SPELL_SUMMON_HULKING_CORPSE, true, nullptr, nullptr, me->GetGUID());
                     events.ScheduleEvent(EVENT_SUMMON_HULKING_CORPSE, 30000);
                     break;
                 case EVENT_SUMMON_SHADOWCASTER:
                     if (Creature* trigger = summons.GetCreatureWithEntry(NPC_CRYSTAL_CHANNEL_TARGET))
                         trigger->CastSpell(trigger, SPELL_SUMMON_RISEN_SHADOWCASTER, true, nullptr, nullptr, me->GetGUID());
                     events.ScheduleEvent(EVENT_SUMMON_SHADOWCASTER, 10000);
                     break;
                 case EVENT_SUMMON_CRYSTAL_HANDLER:
                     if (_crystalCounter++ < 4)
                     {
                         Talk(SAY_SUMMONING_ADDS);
                         Talk(EMOTE_SUMMONING_ADDS);
                         if (Creature* target = ObjectAccessor::GetCreature(*me, _stage ? _summonTargetLeftGUID : _summonTargetRightGUID))
                             target->CastSpell(target, SPELL_SUMMON_CRYSTAL_HANDLER, true, nullptr, nullptr, me->GetGUID());
                         _stage = _stage ? 0 : 1;
                         events.ScheduleEvent(EVENT_SUMMON_CRYSTAL_HANDLER, 20000);
                     }
                     break;
                 case EVENT_CHECK_PHASE:
                     if (me->HasAura(SPELL_BEAM_CHANNEL))
                     {
                         events.ScheduleEvent(EVENT_CHECK_PHASE, 2000);
                         break;
                     }
                     events.Reset();
                     events.ScheduleEvent(EVENT_CAST_OFFENSIVE_SPELL, 3000);
                     events.ScheduleEvent(EVENT_SPELL_SUMMON_MINIONS, 10000);
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                     me->InterruptNonMeleeSpells(false);
                     break;
                 case EVENT_CAST_OFFENSIVE_SPELL:
                     if (!me->HasUnitState(UNIT_STATE_CASTING))
                         if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 100, true))
                             me->CastSpell(target, RAND(SPELL_BLIZZARD, SPELL_FROSTBOLT, SPELL_TOUCH_OF_MISERY), false);
                     events.ScheduleEvent(EVENT_CAST_OFFENSIVE_SPELL, 500);
                     break;
                 case EVENT_SPELL_SUMMON_MINIONS:
                     if (me->HasUnitState(UNIT_STATE_CASTING))
                     {
                         me->CastSpell(me, SPELL_SUMMON_MINIONS, false);
                         events.ScheduleEvent(EVENT_SPELL_SUMMON_MINIONS, 15000);
                         break;
                     }
                     events.ScheduleEvent(EVENT_SPELL_SUMMON_MINIONS, 500);
                     break;
             }
             EnterEvadeIfOutOfCombatArea();
         }
References _crystalCounter, _stage, _summonTargetLeftGUID, _summonTargetRightGUID, Unit::CastSpell(), diff(), EMOTE_SUMMONING_ADDS, ScriptedAI::EnterEvadeIfOutOfCombatArea(), EVENT_CAST_OFFENSIVE_SPELL, EVENT_CHECK_PHASE, EVENT_SPELL_SUMMON_MINIONS, EVENT_SUMMON_CRYSTAL_HANDLER, EVENT_SUMMON_FETID_TROLL, EVENT_SUMMON_HULKING_CORPSE, EVENT_SUMMON_SHADOWCASTER, ObjectAccessor::GetCreature(), SummonList::GetCreatureWithEntry(), Object::GetGUID(), Unit::HasAura(), Unit::HasUnitState(), Unit::InterruptNonMeleeSpells(), ScriptedAI::me, NPC_CRYSTAL_CHANNEL_TARGET, RAND(), Object::RemoveFlag(), SAY_SUMMONING_ADDS, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), SPELL_BEAM_CHANNEL, SPELL_BLIZZARD, SPELL_FROSTBOLT, SPELL_SUMMON_CRYSTAL_HANDLER, SPELL_SUMMON_FETID_TROLL_CORPSE, SPELL_SUMMON_HULKING_CORPSE, SPELL_SUMMON_MINIONS, SPELL_SUMMON_RISEN_SHADOWCASTER, SPELL_TOUCH_OF_MISERY, BossAI::summons, CreatureAI::Talk(), UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
_achievement
bool boss_novos::boss_novosAI::_achievement private
Definition at line 262 of file boss_novos.cpp.
Referenced by GetData(), Reset(), and SetData().
_crystalCounter
uint8 boss_novos::boss_novosAI::_crystalCounter private
Definition at line 257 of file boss_novos.cpp.
Referenced by Reset(), and UpdateAI().
_stage
uint8 boss_novos::boss_novosAI::_stage private
Definition at line 258 of file boss_novos.cpp.
Referenced by Reset(), and UpdateAI().
_summonTargetLeftGUID
ObjectGuid boss_novos::boss_novosAI::_summonTargetLeftGUID private
Definition at line 260 of file boss_novos.cpp.
Referenced by EnterCombat(), Reset(), and UpdateAI().
_summonTargetRightGUID
ObjectGuid boss_novos::boss_novosAI::_summonTargetRightGUID private
Definition at line 259 of file boss_novos.cpp.
Referenced by EnterCombat(), Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/DraktharonKeep/boss_novos.cpp