Azerotcore-wotlk: safe_duration_cast Namespace Reference
safe_duration_cast Namespace Reference
Functions
template<typename To , typename From , FMT_ENABLE_IF(!std::is_same< From, To >::value && std::numeric_limits< From >::is_signed== std::numeric_limits< To >::is_signed) >
FMT_CONSTEXPR To lossless_integral_conversion (const From from, int &ec)
template<typename To , typename From , FMT_ENABLE_IF(!std::is_same< From, To >::value) >
FMT_CONSTEXPR To safe_float_conversion (const From from, int &ec)
template<typename To , typename FromRep , typename FromPeriod , FMT_ENABLE_IF(std::is_integral< FromRep >::value) , FMT_ENABLE_IF(std::is_integral< typename To::rep >::value) >
To safe_duration_cast (std::chrono::duration< FromRep, FromPeriod > from, int &ec)
Function Documentation
lossless_integral_conversion()
template<typename To , typename From , FMT_ENABLE_IF(!std::is_same< From, To >::value && std::numeric_limits< From >::is_signed== std::numeric_limits< To >::is_signed) > FMT_CONSTEXPR To safe_duration_cast::lossless_integral_conversion (const From from, int & ec)
converts From to To, without loss. If the dynamic value of from can't be converted to To without loss, ec is set.
Definition at line 39 of file chrono.h.
{
   ec = 0;
   using F = std::numeric_limits<From>;
   using T = std::numeric_limits<To>;
   static_assert(F::is_integer, "From must be integral");
   static_assert(T::is_integer, "To must be integral");
   // A and B are both signed, or both unsigned.
   if (F::digits <= T::digits) {
     // From fits in To without any problem.
   } else {
     // From does not always fit in To, resort to a dynamic check.
     if (from < (T::min)() || from > (T::max)()) {
       // outside range.
       ec = 1;
       return {};
     }
   }
   return static_cast<To>(from);
 }
References F, max, and min.
safe_duration_cast()
template<typename To , typename FromRep , typename FromPeriod , FMT_ENABLE_IF(std::is_integral< FromRep >::value) , FMT_ENABLE_IF(std::is_integral< typename To::rep >::value) > To safe_duration_cast::safe_duration_cast (std::chrono::duration< FromRep, FromPeriod > from, int & ec)
safe duration cast between integral durations
safe duration_cast between floating point durations
Definition at line 154 of file chrono.h.
{
   using From = std::chrono::duration<FromRep, FromPeriod>;
   ec = 0;
   // the basic idea is that we need to convert from count() in the from type
   // to count() in the To type, by multiplying it with this:
   struct Factor
       : std::ratio_divide<typename From::period, typename To::period> {};
   static_assert(Factor::num > 0, "num must be positive");
   static_assert(Factor::den > 0, "den must be positive");
   // the conversion is like this: multiply from.count() with Factor::num
   // /Factor::den and convert it to To::rep, all this without
   // overflow/underflow. let's start by finding a suitable type that can hold
   // both To, From and Factor::num
   using IntermediateRep =
       typename std::common_type<typename From::rep, typename To::rep,
                                 decltype(Factor::num)>::type;
   // safe conversion to IntermediateRep
   IntermediateRep count =
       lossless_integral_conversion<IntermediateRep>(from.count(), ec);
   if (ec) return {};
   // multiply with Factor::num without overflow or underflow
   if (detail::const_check(Factor::num != 1)) {
     const auto max1 = detail::max_value<IntermediateRep>() / Factor::num;
     if (count > max1) {
       ec = 1;
       return {};
     }
     const auto min1 =
         (std::numeric_limits<IntermediateRep>::min)() / Factor::num;
     if (count < min1) {
       ec = 1;
       return {};
     }
     count *= Factor::num;
   }
   if (detail::const_check(Factor::den != 1)) count /= Factor::den;
   auto tocount = lossless_integral_conversion<typename To::rep>(count, ec);
   return ec ? To() : To(tocount);
 }
References const_check(), count(), and min.
safe_float_conversion()
template<typename To , typename From , FMT_ENABLE_IF(!std::is_same< From, To >::value) > FMT_CONSTEXPR To safe_duration_cast::safe_float_conversion (const From from, int & ec)
converts From to To if possible, otherwise ec is set.
input output
NaN NaN
Inf Inf
normal, fits in output converted (possibly lossy)
normal, does not fit in output ec is set
subnormal best effort
-Inf -Inf
Definition at line 120 of file chrono.h.
{
   ec = 0;
   using T = std::numeric_limits<To>;
   static_assert(std::is_floating_point<From>::value, "From must be floating");
   static_assert(std::is_floating_point<To>::value, "To must be floating");
   // catch the only happy case
   if (std::isfinite(from)) {
     if (from >= T::lowest() && from <= (T::max)()) {
       return static_cast<To>(from);
     }
     // not within range.
     ec = 1;
     return {};
   }
   // nan and inf will be preserved
   return static_cast<To>(from);
 }  // function
References isfinite(), and max.