Azerotcore-wotlk: Doodad Namespace Reference
Doodad Namespace Reference
Functions
void Extract (ADT::MDDF const &doodadDef, char const *ModelInstName, uint32 mapID, uint32 tileX, uint32 tileY, FILE *pDirfile)
void ExtractSet (WMODoodadData const &doodadData, ADT::MODF const &wmo, uint32 mapID, uint32 tileX, uint32 tileY, FILE *pDirfile)
Function Documentation
Extract()
void Doodad::Extract (ADT::MDDF const & doodadDef, char const * ModelInstName, uint32 mapID, uint32 tileX, uint32 tileY, FILE * pDirfile)
Definition at line 139 of file model.cpp.
 {
     char tempname[1036];
     sprintf(tempname, "%s/%s", szWorkDirWmo, ModelInstName);
     FILE* input = fopen(tempname, "r+b");
     if (!input)
         return;
     fseek(input, 8, SEEK_SET); // get the correct no of vertices
     int nVertices;
     int count = fread(&nVertices, sizeof (int), 1, input);
     fclose(input);
     if (count != 1 || nVertices == 0)
         return;
     // scale factor - divide by 1024. blizzard devs must be on crack, why not just use a float?
     float sc = doodadDef.Scale / 1024.0f;
     Vec3D position = fixCoords(doodadDef.Position);
     uint16 nameSet = 0;// not used for models
     uint32 uniqueId = GenerateUniqueObjectId(doodadDef.UniqueId, 0);
     uint32 tcflags = MOD_M2;
     if (tileX == 65 && tileY == 65)
         tcflags |= MOD_WORLDSPAWN;
     //write mapID, tileX, tileY, Flags, NameSet, UniqueId, Pos, Rot, Scale, name
     fwrite(&mapID, sizeof(uint32), 1, pDirfile);
     fwrite(&tileX, sizeof(uint32), 1, pDirfile);
     fwrite(&tileY, sizeof(uint32), 1, pDirfile);
     fwrite(&tcflags, sizeof(uint32), 1, pDirfile);
     fwrite(&nameSet, sizeof(uint16), 1, pDirfile);
     fwrite(&uniqueId, sizeof(uint32), 1, pDirfile);
     fwrite(&position, sizeof(Vec3D), 1, pDirfile);
     fwrite(&doodadDef.Rotation, sizeof(Vec3D), 1, pDirfile);
     fwrite(&sc, sizeof(float), 1, pDirfile);
     uint32 nlen = strlen(ModelInstName);
     fwrite(&nlen, sizeof(uint32), 1, pDirfile);
     fwrite(ModelInstName, sizeof(char), nlen, pDirfile);
 }
References count(), fixCoords(), GenerateUniqueObjectId(), MOD_M2, MOD_WORLDSPAWN, ADT::MDDF::Position, ADT::MDDF::Rotation, ADT::MDDF::Scale, SEEK_SET, sprintf(), szWorkDirWmo, and ADT::MDDF::UniqueId.
Referenced by ADTFile::init().
ExtractSet()
void Doodad::ExtractSet (WMODoodadData const & doodadData, ADT::MODF const & wmo, uint32 mapID, uint32 tileX, uint32 tileY, FILE * pDirfile)
Definition at line 182 of file model.cpp.
 {
     if (wmo.DoodadSet >= doodadData.Sets.size())
         return;
     G3D::Vector3 wmoPosition(wmo.Position.z, wmo.Position.x, wmo.Position.y);
     G3D::Matrix3 wmoRotation = G3D::Matrix3::fromEulerAnglesZYX(G3D::toRadians(wmo.Rotation.y), G3D::toRadians(wmo.Rotation.x), G3D::toRadians(wmo.Rotation.z));
     uint16 doodadId = 0;
     WMO::MODS const& doodadSetData = doodadData.Sets[wmo.DoodadSet];
     for (uint16 doodadIndex : doodadData.References)
     {
         if (doodadIndex < doodadSetData.StartIndex ||
             doodadIndex >= doodadSetData.StartIndex + doodadSetData.Count)
             continue;
         WMO::MODD const& doodad = doodadData.Spawns[doodadIndex];
         char ModelInstName[1024];
         sprintf(ModelInstName, "%s", GetPlainName(&doodadData.Paths[doodad.NameIndex]));
         uint32 nlen = strlen(ModelInstName);
         fixnamen(ModelInstName, nlen);
         fixname2(ModelInstName, nlen);
         if (nlen > 3)
         {
             char const* extension = &ModelInstName[nlen - 4];
             if (!strcmp(extension, ".mdx") || !strcmp(extension, ".mdl"))
             {
                 ModelInstName[nlen - 2] = '2';
                 ModelInstName[nlen - 1] = '\0';
             }
         }
         char tempname[1036];
         sprintf(tempname, "%s/%s", szWorkDirWmo, ModelInstName);
         FILE* input = fopen(tempname, "r+b");
         if (!input)
             continue;
         fseek(input, 8, SEEK_SET); // get the correct no of vertices
         int nVertices;
         int count = fread(&nVertices, sizeof(int), 1, input);
         fclose(input);
         if (count != 1 || nVertices == 0)
             continue;
         assert(doodadId < std::numeric_limits<uint16>::max());
         ++doodadId;
         G3D::Vector3 position = wmoPosition + (wmoRotation * G3D::Vector3(doodad.Position.x, doodad.Position.y, doodad.Position.z));
         Vec3D rotation;
         (G3D::Quat(doodad.Rotation.X, doodad.Rotation.Y, doodad.Rotation.Z, doodad.Rotation.W)
             .toRotationMatrix() * wmoRotation)
             .toEulerAnglesXYZ(rotation.z, rotation.x, rotation.y);
         rotation.z = G3D::toDegrees(rotation.z);
         rotation.x = G3D::toDegrees(rotation.x);
         rotation.y = G3D::toDegrees(rotation.y);
         uint16 nameSet = 0;     // not used for models
         uint32 uniqueId = GenerateUniqueObjectId(wmo.UniqueId, doodadId);
         uint32 tcflags = MOD_M2;
         if (tileX == 65 && tileY == 65)
             tcflags |= MOD_WORLDSPAWN;
         //write mapID, tileX, tileY, Flags, NameSet, UniqueId, Pos, Rot, Scale, name
         fwrite(&mapID, sizeof(uint32), 1, pDirfile);
         fwrite(&tileX, sizeof(uint32), 1, pDirfile);
         fwrite(&tileY, sizeof(uint32), 1, pDirfile);
         fwrite(&tcflags, sizeof(uint32), 1, pDirfile);
         fwrite(&nameSet, sizeof(uint16), 1, pDirfile);
         fwrite(&uniqueId, sizeof(uint32), 1, pDirfile);
         fwrite(&position, sizeof(Vec3D), 1, pDirfile);
         fwrite(&rotation, sizeof(Vec3D), 1, pDirfile);
         fwrite(&doodad.Scale, sizeof(float), 1, pDirfile);
         fwrite(&nlen, sizeof(uint32), 1, pDirfile);
         fwrite(ModelInstName, sizeof(char), nlen, pDirfile);
     }
 }
References assert(), count(), WMO::MODS::Count, ADT::MODF::DoodadSet, fixname2(), fixnamen(), G3D::Matrix3::fromEulerAnglesZYX(), GenerateUniqueObjectId(), GetPlainName(), max, MOD_M2, MOD_WORLDSPAWN, WMO::MODD::NameIndex, WMODoodadData::Paths, ADT::MODF::Position, WMO::MODD::Position, WMODoodadData::References, ADT::MODF::Rotation, WMO::MODD::Rotation, WMO::MODD::Scale, SEEK_SET, WMODoodadData::Sets, WMODoodadData::Spawns, sprintf(), WMO::MODS::StartIndex, szWorkDirWmo, G3D::toDegrees(), G3D::toRadians(), G3D::Quat::toRotationMatrix(), ADT::MODF::UniqueId, Quaternion::W, Vec3D::x, Quaternion::X, Vec3D::y, Quaternion::Y, Vec3D::z, and Quaternion::Z.
Referenced by ADTFile::init(), and WDTFile::init().