Azerotcore-wotlk: DBCStorage< T > Class Template Reference
DBCStorage< T > Class Template Reference
#include <DBCStore.h>
Public Types
typedef DBCStorageIterator< T > iterator
Public Member Functions
DBCStorage (char const *fmt)
~DBCStorage () override
T const * LookupEntry (uint32 id) const
T const * AssertEntry (uint32 id) const
uint32 GetNumRows () const
bool Load (char const *path) override
bool LoadStringsFrom (char const *path) override
void LoadFromDB (char const *table, char const *format) override
iterator begin ()
iterator end ()
Public Member Functions inherited from DBCStorageBase
DBCStorageBase (char const *fmt)
virtual ~DBCStorageBase ()
char const * GetFormat () const
uint32 GetFieldCount () const
Private Member Functions
DBCStorage (DBCStorage const &right)=delete
DBCStorage & operator= (DBCStorage const &right)=delete
Private Attributes
union {
T ** AsT
char ** AsChar
} _indexTable
Additional Inherited Members
Protected Member Functions inherited from DBCStorageBase
bool Load (char const *path, char **&indexTable)
bool LoadStringsFrom (char const *path, char **indexTable)
void LoadFromDB (char const *table, char const *format, char **&indexTable)
Protected Attributes inherited from DBCStorageBase
uint32 _fieldCount
char const * _fileFormat
char * _dataTable
std::vector< char * > _stringPool
uint32 _indexTableSize
Detailed Description
template<class T>
class DBCStorage< T >
Definition at line 169 of file DBCStore.h.
Member Typedef Documentation
iterator
template<class T > typedef DBCStorageIterator<T> DBCStorage< T >::iterator
Definition at line 172 of file DBCStore.h.
Constructor & Destructor Documentation
DBCStorage() [1/2]
template<class T > DBCStorage< T >::DBCStorage (char const * fmt) inline explicit
Definition at line 174 of file DBCStore.h.
                                          : DBCStorageBase(fmt)
     {
         _indexTable.AsT = nullptr;
     }
References DBCStorage< T >::_indexTable.
~DBCStorage()
template<class T > DBCStorage< T >::~DBCStorage () inline override
Definition at line 179 of file DBCStore.h.
     {
         delete[] reinterpret_cast<char*>(_indexTable.AsT);
     }
References DBCStorage< T >::_indexTable.
DBCStorage() [2/2]
template<class T > DBCStorage< T >::DBCStorage (DBCStorage< T > const & right) private delete
Member Function Documentation
AssertEntry()
template<class T > T const* DBCStorage< T >::AssertEntry (uint32 id) const inline
Definition at line 185 of file DBCStore.h.
 { return ASSERT_NOTNULL(LookupEntry(id)); }
References ASSERT_NOTNULL, and DBCStorage< T >::LookupEntry().
begin()
template<class T > iterator DBCStorage< T >::begin () inline
Definition at line 225 of file DBCStore.h.
 { return iterator(_indexTable.AsT, _indexTableSize); }
References DBCStorage< T >::_indexTable, and DBCStorageBase::_indexTableSize.
end()
template<class T > iterator DBCStorage< T >::end () inline
Definition at line 226 of file DBCStore.h.
 { return iterator(_indexTable.AsT, _indexTableSize, _indexTableSize); }
References DBCStorage< T >::_indexTable, and DBCStorageBase::_indexTableSize.
GetNumRows()
template<class T > uint32 DBCStorage< T >::GetNumRows () const inline
Definition at line 208 of file DBCStore.h.
 { return _indexTableSize; }
References DBCStorageBase::_indexTableSize.
Referenced by LoadDBC().
Load()
template<class T > bool DBCStorage< T >::Load (char const * path) inline override virtual
Implements DBCStorageBase.
Definition at line 210 of file DBCStore.h.
     {
         return DBCStorageBase::Load(path, _indexTable.AsChar);
     }
References DBCStorage< T >::_indexTable, and DBCStorageBase::Load().
Referenced by LoadDBC().
LoadFromDB()
template<class T > void DBCStorage< T >::LoadFromDB (char const * table, char const * format) inline override virtual
Implements DBCStorageBase.
Definition at line 220 of file DBCStore.h.
     {
         DBCStorageBase::LoadFromDB(table, format, _indexTable.AsChar);
     }
References DBCStorage< T >::_indexTable, and DBCStorageBase::LoadFromDB().
Referenced by LoadDBC().
LoadStringsFrom()
template<class T > bool DBCStorage< T >::LoadStringsFrom (char const * path) inline override virtual
Implements DBCStorageBase.
Definition at line 215 of file DBCStore.h.
     {
         return DBCStorageBase::LoadStringsFrom(path, _indexTable.AsChar);
     }
References DBCStorage< T >::_indexTable, and DBCStorageBase::LoadStringsFrom().
Referenced by LoadDBC().
LookupEntry()
template<class T > T const* DBCStorage< T >::LookupEntry (uint32 id) const inline
Definition at line 184 of file DBCStore.h.
 { return (id >= _indexTableSize) ? nullptr : _indexTable.AsT[id]; }
References DBCStorage< T >::_indexTable, and DBCStorageBase::_indexTableSize.
Referenced by DBCStorage< T >::AssertEntry().
operator=()
template<class T > DBCStorage& DBCStorage< T >::operator= (DBCStorage< T > const & right) private delete
Member Data Documentation
union { ... } DBCStorage< T >::_indexTable
Referenced by DBCStorage< T >::begin(), DBCStorage< T >::DBCStorage(), DBCStorage< T >::end(), DBCStorage< T >::Load(), DBCStorage< T >::LoadFromDB(), DBCStorage< T >::LoadStringsFrom(), DBCStorage< T >::LookupEntry(), and DBCStorage< T >::~DBCStorage().
AsChar
template<class T > char** DBCStorage< T >::AsChar
Definition at line 232 of file DBCStore.h.
AsT
template<class T > T** DBCStorage< T >::AsT
Definition at line 231 of file DBCStore.h.
The documentation for this class was generated from the following file:
src/server/shared/DataStores/DBCStore.h