Azerotcore-wotlk: SmartGameObjectAI Class Reference
SmartGameObjectAI Class Reference
#include <SmartAI.h>
Public Member Functions
SmartGameObjectAI (GameObject *g)
~SmartGameObjectAI () override
void UpdateAI (uint32 diff) override
void InitializeAI () override
void Reset () override
SmartScript * GetScript ()
bool GossipHello (Player *player, bool reportUse) override
bool GossipSelect (Player *player, uint32 sender, uint32 action) override
bool GossipSelectCode (Player *, uint32, uint32, const char *) override
bool QuestAccept (Player *player, Quest const *quest) override
bool QuestReward (Player *player, Quest const *quest, uint32 opt) override
void Destroyed (Player *player, uint32 eventId) override
void SetData (uint32 id, uint32 value) override
void SetScript9 (SmartScriptHolder &e, uint32 entry, Unit *invoker)
void OnGameEvent (bool start, uint16 eventId) override
void OnStateChanged (uint32 state, Unit *unit) override
void EventInform (uint32 eventId) override
void SpellHit (Unit *unit, const SpellInfo *spellInfo) override
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32)
virtual ObjectGuid GetGUID (int32) const
virtual uint32 GetDialogStatus (Player *)
virtual uint32 GetData (uint32) const
virtual bool CanBeSeen (Player const *)
Static Public Member Functions
static int32 Permissible (const GameObject *g)
Static Public Member Functions inherited from GameObjectAI
static int Permissible (GameObject const *go)
Protected Attributes
SmartScript mScript
Protected Attributes inherited from GameObjectAI
GameObject *const me
Detailed Description
Definition at line 245 of file SmartAI.h.
Constructor & Destructor Documentation
SmartGameObjectAI()
SmartGameObjectAI::SmartGameObjectAI (GameObject * g) inline
Definition at line 248 of file SmartAI.h.
 : GameObjectAI(g) {}
~SmartGameObjectAI()
SmartGameObjectAI::~SmartGameObjectAI () inline override
Definition at line 249 of file SmartAI.h.
 {}
Member Function Documentation
Destroyed()
void SmartGameObjectAI::Destroyed (Player * player, uint32 eventId) override virtual
Reimplemented from GameObjectAI.
Definition at line 1144 of file SmartAI.cpp.
 {
     GetScript()->ProcessEventsFor(SMART_EVENT_DEATH, player, eventId, 0, false, nullptr, me);
 }
References GetScript(), GameObjectAI::me, SmartScript::ProcessEventsFor(), and SMART_EVENT_DEATH.
EventInform()
void SmartGameObjectAI::EventInform (uint32 eventId) override virtual
Reimplemented from GameObjectAI.
Definition at line 1171 of file SmartAI.cpp.
 {
     GetScript()->ProcessEventsFor(SMART_EVENT_GO_EVENT_INFORM, nullptr, eventId);
 }
References GetScript(), SmartScript::ProcessEventsFor(), and SMART_EVENT_GO_EVENT_INFORM.
GetScript()
SmartScript* SmartGameObjectAI::GetScript () inline
Definition at line 254 of file SmartAI.h.
 { return &mScript; }
References mScript.
Referenced by Destroyed(), EventInform(), GossipHello(), GossipSelect(), InitializeAI(), OnGameEvent(), OnStateChanged(), QuestAccept(), QuestReward(), Reset(), SetData(), SetScript9(), SpellHit(), and UpdateAI().
GossipHello()
bool SmartGameObjectAI::GossipHello (Player * player, bool reportUse) override virtual
Reimplemented from GameObjectAI.
Definition at line 1109 of file SmartAI.cpp.
 {
     LOG_DEBUG("sql.sql", "SmartGameObjectAI::GossipHello");
     GetScript()->ProcessEventsFor(SMART_EVENT_GOSSIP_HELLO, player, (uint32)reportUse, 0, false, nullptr, me);
     return false;
 }
References GetScript(), LOG_DEBUG, GameObjectAI::me, SmartScript::ProcessEventsFor(), and SMART_EVENT_GOSSIP_HELLO.
GossipSelect()
bool SmartGameObjectAI::GossipSelect (Player * player, uint32 sender, uint32 action) override virtual
Reimplemented from GameObjectAI.
Definition at line 1117 of file SmartAI.cpp.
 {
     GetScript()->ProcessEventsFor(SMART_EVENT_GOSSIP_SELECT, player, sender, action, false, nullptr, me);
     return false;
 }
References GetScript(), GameObjectAI::me, SmartScript::ProcessEventsFor(), and SMART_EVENT_GOSSIP_SELECT.
GossipSelectCode()
bool SmartGameObjectAI::GossipSelectCode (Player * , uint32 , uint32 , const char *) override virtual
Reimplemented from GameObjectAI.
Definition at line 1124 of file SmartAI.cpp.
 {
     return false;
 }
InitializeAI()
void SmartGameObjectAI::InitializeAI () override virtual
Reimplemented from GameObjectAI.
Definition at line 1090 of file SmartAI.cpp.
 {
     GetScript()->OnInitialize(me);
     // Xinef: do not call respawn event if go is not spawned
     if (me->isSpawned())
         GetScript()->ProcessEventsFor(SMART_EVENT_RESPAWN);
     //Reset();
 }
References GetScript(), GameObject::isSpawned(), GameObjectAI::me, SmartScript::OnInitialize(), SmartScript::ProcessEventsFor(), and SMART_EVENT_RESPAWN.
OnGameEvent()
void SmartGameObjectAI::OnGameEvent (bool start, uint16 eventId) override virtual
Reimplemented from GameObjectAI.
Definition at line 1161 of file SmartAI.cpp.
 {
     GetScript()->ProcessEventsFor(start ? SMART_EVENT_GAME_EVENT_START : SMART_EVENT_GAME_EVENT_END, nullptr, eventId);
 }
References GetScript(), SmartScript::ProcessEventsFor(), SMART_EVENT_GAME_EVENT_END, and SMART_EVENT_GAME_EVENT_START.
OnStateChanged()
void SmartGameObjectAI::OnStateChanged (uint32 state, Unit * unit) override virtual
Reimplemented from GameObjectAI.
Definition at line 1166 of file SmartAI.cpp.
 {
     GetScript()->ProcessEventsFor(SMART_EVENT_GO_STATE_CHANGED, unit, state);
 }
References GetScript(), SmartScript::ProcessEventsFor(), and SMART_EVENT_GO_STATE_CHANGED.
Permissible()
int SmartGameObjectAI::Permissible (const GameObject * g) static
Definition at line 1078 of file SmartAI.cpp.
 {
     if (g->GetAIName() == "SmartGameObjectAI")
         return PERMIT_BASE_SPECIAL;
     return PERMIT_BASE_NO;
 }
References GameObject::GetAIName(), PERMIT_BASE_NO, and PERMIT_BASE_SPECIAL.
QuestAccept()
bool SmartGameObjectAI::QuestAccept (Player * player, Quest const * quest) override virtual
Reimplemented from GameObjectAI.
Definition at line 1130 of file SmartAI.cpp.
 {
     GetScript()->ProcessEventsFor(SMART_EVENT_ACCEPTED_QUEST, player, quest->GetQuestId(), 0, false, nullptr, me);
     return false;
 }
References Quest::GetQuestId(), GetScript(), GameObjectAI::me, SmartScript::ProcessEventsFor(), and SMART_EVENT_ACCEPTED_QUEST.
QuestReward()
bool SmartGameObjectAI::QuestReward (Player * player, Quest const * quest, uint32 opt) override virtual
Reimplemented from GameObjectAI.
Definition at line 1137 of file SmartAI.cpp.
 {
     GetScript()->ProcessEventsFor(SMART_EVENT_REWARD_QUEST, player, quest->GetQuestId(), opt, false, nullptr, me);
     return false;
 }
References Quest::GetQuestId(), GetScript(), GameObjectAI::me, SmartScript::ProcessEventsFor(), and SMART_EVENT_REWARD_QUEST.
Reset()
void SmartGameObjectAI::Reset () override virtual
Reimplemented from GameObjectAI.
Definition at line 1100 of file SmartAI.cpp.
 {
     // Xinef: call respawn event on reset
     GetScript()->ProcessEventsFor(SMART_EVENT_RESPAWN);
     GetScript()->OnReset();
 }
References GetScript(), SmartScript::OnReset(), SmartScript::ProcessEventsFor(), and SMART_EVENT_RESPAWN.
SetData()
void SmartGameObjectAI::SetData (uint32 id, uint32 value) override virtual
Reimplemented from GameObjectAI.
Definition at line 1149 of file SmartAI.cpp.
 {
     GetScript()->ProcessEventsFor(SMART_EVENT_DATA_SET, nullptr, id, value);
 }
References GetScript(), SmartScript::ProcessEventsFor(), and SMART_EVENT_DATA_SET.
SetScript9()
void SmartGameObjectAI::SetScript9 (SmartScriptHolder & e, uint32 entry, Unit * invoker)
Definition at line 1154 of file SmartAI.cpp.
 {
     if (invoker)
         GetScript()->mLastInvoker = invoker->GetGUID();
     GetScript()->SetScript9(e, entry);
 }
References Object::GetGUID(), GetScript(), SmartScript::mLastInvoker, and SmartScript::SetScript9().
SpellHit()
void SmartGameObjectAI::SpellHit (Unit * unit, const SpellInfo * spellInfo) override virtual
Reimplemented from GameObjectAI.
Definition at line 1176 of file SmartAI.cpp.
 {
     GetScript()->ProcessEventsFor(SMART_EVENT_SPELLHIT, unit, 0, 0, false, spellInfo);
 }
References GetScript(), SmartScript::ProcessEventsFor(), and SMART_EVENT_SPELLHIT.
UpdateAI()
void SmartGameObjectAI::UpdateAI (uint32 diff) override virtual
Reimplemented from GameObjectAI.
Definition at line 1085 of file SmartAI.cpp.
 {
     GetScript()->OnUpdate(diff);
 }
References diff(), GetScript(), and SmartScript::OnUpdate().
Member Data Documentation
mScript
SmartScript SmartGameObjectAI::mScript protected
Definition at line 271 of file SmartAI.h.
Referenced by GetScript().
The documentation for this class was generated from the following files:
src/server/game/AI/SmartScripts/SmartAI.h
src/server/game/AI/SmartScripts/SmartAI.cpp