Azerotcore-wotlk: npc_dragonmaw_peon::npc_dragonmaw_peonAI Struct Reference
npc_dragonmaw_peon::npc_dragonmaw_peonAI Struct Reference
Public Member Functions
npc_dragonmaw_peonAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *) override
void SpellHit (Unit *caster, const SpellInfo *spell) override
void MovementInform (uint32, uint32 id) override
void CreditPlayer ()
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
ObjectGuid PlayerGUID
bool Tapped
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Private Attributes
float x
float y
float z
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 595 of file zone_shadowmoon_valley.cpp.
Constructor & Destructor Documentation
npc_dragonmaw_peonAI()
npc_dragonmaw_peon::npc_dragonmaw_peonAI::npc_dragonmaw_peonAI (Creature * creature) inline
Definition at line 597 of file zone_shadowmoon_valley.cpp.
 : ScriptedAI(creature) { }
Member Function Documentation
CreditPlayer()
void npc_dragonmaw_peon::npc_dragonmaw_peonAI::CreditPlayer () inline
Definition at line 643 of file zone_shadowmoon_valley.cpp.
         {
             if (PlayerGUID)
             {
                 Player* player = ObjectAccessor::GetPlayer(*me, PlayerGUID);
                 if (player && player->GetQuestStatus(QUEST_A_SLOW_DEATH) == QUEST_STATUS_INCOMPLETE)
                     player->KilledMonsterCredit(DRAGONMAW_PEON_KILL_CREDIT);
             }
         }
References DRAGONMAW_PEON_KILL_CREDIT, ObjectAccessor::GetPlayer(), Player::GetQuestStatus(), Player::KilledMonsterCredit(), ScriptedAI::me, PlayerGUID, QUEST_A_SLOW_DEATH, and QUEST_STATUS_INCOMPLETE.
Referenced by UpdateAI().
EnterCombat()
void npc_dragonmaw_peon::npc_dragonmaw_peonAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 610 of file zone_shadowmoon_valley.cpp.
         {
             events.ScheduleEvent(EVENT_KICK, urand(5000, 10000));
             events.ScheduleEvent(EVENT_SUNDER, urand(5000, 10000));
         }
References EVENT_KICK, EVENT_SUNDER, and urand().
MovementInform()
void npc_dragonmaw_peon::npc_dragonmaw_peonAI::MovementInform (uint32 , uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 632 of file zone_shadowmoon_valley.cpp.
         {
             if (id == 1)
             {
                 if (GameObject* food = me->FindNearestGameObject(DELICIOUS_MUTTON, 5.0f))
                     me->SetFacingToObject(food);
                 me->HandleEmoteCommand(EMOTE_ONESHOT_EAT);
                 events.ScheduleEvent(EVENT_POISONED, 5000);
             }
         }
References DELICIOUS_MUTTON, EMOTE_ONESHOT_EAT, EVENT_POISONED, WorldObject::FindNearestGameObject(), Unit::HandleEmoteCommand(), ScriptedAI::me, and Unit::SetFacingToObject().
Reset()
void npc_dragonmaw_peon::npc_dragonmaw_peonAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 603 of file zone_shadowmoon_valley.cpp.
         {
             events.Reset();
             PlayerGUID.Clear();
             Tapped = false;
         }
References ObjectGuid::Clear(), PlayerGUID, and Tapped.
SpellHit()
void npc_dragonmaw_peon::npc_dragonmaw_peonAI::SpellHit (Unit * caster, const SpellInfo * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 616 of file zone_shadowmoon_valley.cpp.
         {
             if (!caster)
                 return;
             PlayerGUID = caster->GetGUID();
             if (caster->GetTypeId() == TYPEID_PLAYER && spell->Id == SPELL_POISON && !Tapped)
             {
                 Tapped = true;
                 caster->GetClosePoint(x, y, z, me->GetObjectSize());
                 Talk(SAY_1);
                 events.ScheduleEvent(EVENT_WALK_TO_MUTTON, 0);
             }
         }
References EVENT_WALK_TO_MUTTON, WorldObject::GetClosePoint(), Object::GetGUID(), WorldObject::GetObjectSize(), Object::GetTypeId(), SpellInfo::Id, ScriptedAI::me, PlayerGUID, SAY_1, SPELL_POISON, CreatureAI::Talk(), Tapped, TYPEID_PLAYER, x, y, and z.
UpdateAI()
void npc_dragonmaw_peon::npc_dragonmaw_peonAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 653 of file zone_shadowmoon_valley.cpp.
         {
             events.Update(diff);
             if (!UpdateVictim())
             {
                 switch (events.ExecuteEvent())
                 {
                     case EVENT_WALK_TO_MUTTON:
                         me->SetWalk(true);
                         me->GetMotionMaster()->MovePoint(1, x, y, z, true);
                         me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_NONE);
                         me->HandleEmoteCommand(EMOTE_ONESHOT_CHEER);
                         break;
                     case EVENT_POISONED:
                         if (GameObject* food = me->FindNearestGameObject(DELICIOUS_MUTTON, 5.0f))
                             food->RemoveFromWorld();
                         if (roll_chance_i(20))
                             Talk(SAY_POISONED_1);
                         CreditPlayer();
                         me->CastSpell(me, SPELL_VOMIT);
                         events.ScheduleEvent(EVENT_KILL, 5000);
                         break;
                     case EVENT_KILL:
                         Unit::DealDamage(me, me, me->GetHealth(), nullptr, DIRECT_DAMAGE, SPELL_SCHOOL_MASK_NORMAL, nullptr, false);
                         break;
                 }
                 return;
             }
             switch (events.ExecuteEvent())
             {
                 case EVENT_KICK:
                     if (me->GetVictim()->HasUnitState(SPELL_STATE_CASTING))
                         DoCastVictim(SPELL_KICK);
                     events.RepeatEvent(urand(5000, 10000));
                     break;
                 case EVENT_SUNDER:
                     DoCastVictim(SPELL_SUNDER);
                     events.RepeatEvent(urand(5000, 10000));
                     break;
             }
             DoMeleeAttackIfReady();
         }
References Unit::CastSpell(), CreditPlayer(), Unit::DealDamage(), DELICIOUS_MUTTON, DIRECT_DAMAGE, UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), EMOTE_ONESHOT_CHEER, EMOTE_STATE_NONE, EVENT_KICK, EVENT_KILL, EVENT_POISONED, EVENT_SUNDER, EVENT_WALK_TO_MUTTON, WorldObject::FindNearestGameObject(), Unit::GetHealth(), Unit::GetMotionMaster(), Unit::GetVictim(), Unit::HandleEmoteCommand(), Unit::HasUnitState(), ScriptedAI::me, MotionMaster::MovePoint(), roll_chance_i(), SAY_POISONED_1, Object::SetUInt32Value(), Creature::SetWalk(), SPELL_KICK, SPELL_SCHOOL_MASK_NORMAL, SPELL_STATE_CASTING, SPELL_SUNDER, SPELL_VOMIT, CreatureAI::Talk(), UNIT_NPC_EMOTESTATE, CreatureAI::UpdateVictim(), urand(), x, y, and z.
Member Data Documentation
events
EventMap npc_dragonmaw_peon::npc_dragonmaw_peonAI::events
Definition at line 599 of file zone_shadowmoon_valley.cpp.
PlayerGUID
ObjectGuid npc_dragonmaw_peon::npc_dragonmaw_peonAI::PlayerGUID
Definition at line 600 of file zone_shadowmoon_valley.cpp.
Referenced by CreditPlayer(), Reset(), and SpellHit().
Tapped
bool npc_dragonmaw_peon::npc_dragonmaw_peonAI::Tapped
Definition at line 601 of file zone_shadowmoon_valley.cpp.
Referenced by Reset(), and SpellHit().
x
float npc_dragonmaw_peon::npc_dragonmaw_peonAI::x private
Definition at line 699 of file zone_shadowmoon_valley.cpp.
Referenced by SpellHit(), and UpdateAI().
y
float npc_dragonmaw_peon::npc_dragonmaw_peonAI::y private
Definition at line 699 of file zone_shadowmoon_valley.cpp.
Referenced by SpellHit(), and UpdateAI().
z
float npc_dragonmaw_peon::npc_dragonmaw_peonAI::z private
Definition at line 699 of file zone_shadowmoon_valley.cpp.
Referenced by SpellHit(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/zone_shadowmoon_valley.cpp