Azerotcore-wotlk: npc_mcmanus Class Reference
npc_mcmanus Class Reference
Public Member Functions
npc_mcmanus ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 uiAction) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 472 of file zone_sholazar_basin.cpp.
Constructor & Destructor Documentation
npc_mcmanus()
npc_mcmanus::npc_mcmanus () inline
Definition at line 475 of file zone_sholazar_basin.cpp.
 : CreatureScript("npc_mcmanus") {}
Member Function Documentation
OnGossipHello()
bool npc_mcmanus::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 477 of file zone_sholazar_basin.cpp.
     {
         if (!player)
             return true;
         if (creature->IsQuestGiver())
             player->PrepareQuestMenu(creature->GetGUID());
         if (player->GetQuestStatus(12644) == QUEST_STATUS_INCOMPLETE)
             AddGossipItemFor(player, GOSSIP_ICON_CHAT, "I'm ready to start the distillation, uh, Tipsy.", GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
         SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), Player::GetGossipTextId(), Object::GetGUID(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, Unit::IsQuestGiver(), Player::PrepareQuestMenu(), QUEST_STATUS_INCOMPLETE, and SendGossipMenuFor().
OnGossipSelect()
bool npc_mcmanus::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 uiAction) inline override virtual
Reimplemented from CreatureScript.
Definition at line 492 of file zone_sholazar_basin.cpp.
     {
         if (!player)
             return true;
         if (uiAction == GOSSIP_ACTION_INFO_DEF + 1)
         {
             Creature* trigger = creature->FindNearestCreature(NPC_WANTS_BANANAS, 20.0f, true);
             if (trigger && trigger->AI())
                 if (!CAST_AI(npc_still_at_it_trigger::npc_still_at_it_triggerAI, trigger->AI())->running)
                 {
                     CAST_AI(npc_still_at_it_trigger::npc_still_at_it_triggerAI, trigger->AI())->playerGUID = player->GetGUID();
                     CAST_AI(npc_still_at_it_trigger::npc_still_at_it_triggerAI, trigger->AI())->thunderbrewGUID = creature->GetGUID();
                     CAST_AI(npc_still_at_it_trigger::npc_still_at_it_triggerAI, trigger->AI())->Start();
                 }
         }
         CloseGossipMenuFor(player);
         return true;
     }
References Creature::AI(), CAST_AI, CloseGossipMenuFor(), WorldObject::FindNearestCreature(), Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, and NPC_WANTS_BANANAS.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/zone_sholazar_basin.cpp