Azerotcore-wotlk: at_twilight_grove Class Reference
at_twilight_grove Class Reference
Public Member Functions
at_twilight_grove ()
bool OnTrigger (Player *player, const AreaTrigger *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 156 of file zone_duskwood.cpp.
Constructor & Destructor Documentation
at_twilight_grove()
at_twilight_grove::at_twilight_grove () inline
Definition at line 159 of file zone_duskwood.cpp.
 : AreaTriggerScript("at_twilight_grove") { }
Member Function Documentation
OnTrigger()
bool at_twilight_grove::OnTrigger (Player * player, const AreaTrigger *) inline override virtual
Reimplemented from AreaTriggerScript.
Definition at line 161 of file zone_duskwood.cpp.
     {
         if (player->HasQuestForItem(ITEM_FRAGMENT) && !player->HasItemCount(ITEM_FRAGMENT))
             player->SummonCreature(NPC_TWILIGHT_CORRUPTER, -10328.16f, -489.57f, 49.95f, 0, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 240000);
         return false;
     };
References Player::HasItemCount(), Player::HasQuestForItem(), ITEM_FRAGMENT, NPC_TWILIGHT_CORRUPTER, WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT.
The documentation for this class was generated from the following file:
src/server/scripts/EasternKingdoms/zone_duskwood.cpp