Azerotcore-wotlk: quest_commandscript Class Reference
quest_commandscript Class Reference
Public Member Functions
quest_commandscript ()
ChatCommandTable GetCommands () const override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Static Public Member Functions
static bool HandleQuestAdd (ChatHandler *handler, const char *args)
static bool HandleQuestRemove (ChatHandler *handler, const char *args)
static bool HandleQuestComplete (ChatHandler *handler, const char *args)
static bool HandleQuestReward (ChatHandler *handler, char const *args)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 37 of file cs_quest.cpp.
Constructor & Destructor Documentation
quest_commandscript()
quest_commandscript::quest_commandscript () inline
Definition at line 40 of file cs_quest.cpp.
 : CommandScript("quest_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable quest_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
Definition at line 42 of file cs_quest.cpp.
     {
         static ChatCommandTable questCommandTable =
         {
             { "add",            SEC_GAMEMASTER,  false, &HandleQuestAdd,                    "" },
             { "complete",       SEC_GAMEMASTER,  false, &HandleQuestComplete,               "" },
             { "remove",         SEC_GAMEMASTER,  false, &HandleQuestRemove,                 "" },
             { "reward",         SEC_GAMEMASTER,  false, &HandleQuestReward,                 "" },
         };
         static ChatCommandTable commandTable =
         {
             { "quest",          SEC_GAMEMASTER,  false, nullptr, "", questCommandTable },
         };
         return commandTable;
     }
References SEC_GAMEMASTER.
HandleQuestAdd()
static bool quest_commandscript::HandleQuestAdd (ChatHandler * handler, const char * args) inline static
Definition at line 58 of file cs_quest.cpp.
     {
         Player* player = handler->getSelectedPlayer();
         if (!player)
         {
             handler->SendSysMessage(LANG_NO_CHAR_SELECTED);
             handler->SetSentErrorMessage(true);
             return false;
         }
         // .addquest #entry'
         // number or [name] Shift-click form |color|Hquest:quest_id:quest_level|h[name]|h|r
         char* cId = handler->extractKeyFromLink((char*)args, "Hquest");
         if (!cId)
             return false;
         uint32 entry = atol(cId);
         Quest const* quest = sObjectMgr->GetQuestTemplate(entry);
         if (!quest)
         {
             handler->PSendSysMessage(LANG_COMMAND_QUEST_NOTFOUND, entry);
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (player->IsActiveQuest(entry))
         {
             handler->PSendSysMessage("This quest is already active!");
             return false;
         }
         // check item starting quest (it can work incorrectly if added without item in inventory)
         ItemTemplateContainer const* itc = sObjectMgr->GetItemTemplateStore();
         ItemTemplateContainer::const_iterator result = find_if(itc->begin(), itc->end(), Finder<uint32, ItemTemplate>(entry, &ItemTemplate::StartQuest));
         if (result != itc->end())
         {
             handler->PSendSysMessage(LANG_COMMAND_QUEST_STARTFROMITEM, entry, result->second.ItemId);
             handler->SetSentErrorMessage(true);
             return false;
         }
         // ok, normal (creature/GO starting) quest
         if (player->CanAddQuest(quest, true))
             player->AddQuestAndCheckCompletion(quest, nullptr);
         return true;
     }
References Player::AddQuestAndCheckCompletion(), Player::CanAddQuest(), ChatHandler::extractKeyFromLink(), ChatHandler::getSelectedPlayer(), Player::IsActiveQuest(), LANG_COMMAND_QUEST_NOTFOUND, LANG_COMMAND_QUEST_STARTFROMITEM, LANG_NO_CHAR_SELECTED, ChatHandler::PSendSysMessage(), ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), sObjectMgr, and ItemTemplate::StartQuest.
HandleQuestComplete()
static bool quest_commandscript::HandleQuestComplete (ChatHandler * handler, const char * args) inline static
Definition at line 162 of file cs_quest.cpp.
     {
         Player* player = handler->getSelectedPlayer();
         if (!player)
         {
             handler->SendSysMessage(LANG_NO_CHAR_SELECTED);
             handler->SetSentErrorMessage(true);
             return false;
         }
         // .quest complete #entry
         // number or [name] Shift-click form |color|Hquest:quest_id:quest_level|h[name]|h|r
         char* cId = handler->extractKeyFromLink((char*)args, "Hquest");
         if (!cId)
             return false;
         uint32 entry = atol(cId);
         Quest const* quest = sObjectMgr->GetQuestTemplate(entry);
         // If player doesn't have the quest
         if (!quest || player->GetQuestStatus(entry) == QUEST_STATUS_NONE)
         {
             handler->PSendSysMessage(LANG_COMMAND_QUEST_NOTFOUND, entry);
             handler->SetSentErrorMessage(true);
             return false;
         }
         // Add quest items for quests that require items
         for (uint8 x = 0; x < QUEST_ITEM_OBJECTIVES_COUNT; ++x)
         {
             uint32 id = quest->RequiredItemId[x];
             uint32 count = quest->RequiredItemCount[x];
             if (!id || !count)
                 continue;
             uint32 curItemCount = player->GetItemCount(id, true);
             ItemPosCountVec dest;
             uint8 msg = player->CanStoreNewItem(NULL_BAG, NULL_SLOT, dest, id, count - curItemCount);
             if (msg == EQUIP_ERR_OK)
             {
                 Item* item = player->StoreNewItem(dest, id, true);
                 player->SendNewItem(item, count - curItemCount, true, false);
             }
         }
         // All creature/GO slain/casted (not required, but otherwise it will display "Creature slain 0/10")
         for (uint8 i = 0; i < QUEST_OBJECTIVES_COUNT; ++i)
         {
             int32 creature = quest->RequiredNpcOrGo[i];
             uint32 creatureCount = quest->RequiredNpcOrGoCount[i];
             if (creature > 0)
             {
                 if (CreatureTemplate const* creatureInfo = sObjectMgr->GetCreatureTemplate(creature))
                     for (uint16 z = 0; z < creatureCount; ++z)
                         player->KilledMonster(creatureInfo, ObjectGuid::Empty);
             }
             else if (creature < 0)
                 for (uint16 z = 0; z < creatureCount; ++z)
                     player->KillCreditGO(creature);
         }
         // If the quest requires reputation to complete
         if (uint32 repFaction = quest->GetRepObjectiveFaction())
         {
             uint32 repValue = quest->GetRepObjectiveValue();
             uint32 curRep = player->GetReputationMgr().GetReputation(repFaction);
             if (curRep < repValue)
                 if (FactionEntry const* factionEntry = sFactionStore.LookupEntry(repFaction))
                     player->GetReputationMgr().SetReputation(factionEntry, repValue);
         }
         // If the quest requires a SECOND reputation to complete
         if (uint32 repFaction = quest->GetRepObjectiveFaction2())
         {
             uint32 repValue2 = quest->GetRepObjectiveValue2();
             uint32 curRep = player->GetReputationMgr().GetReputation(repFaction);
             if (curRep < repValue2)
                 if (FactionEntry const* factionEntry = sFactionStore.LookupEntry(repFaction))
                     player->GetReputationMgr().SetReputation(factionEntry, repValue2);
         }
         // If the quest requires money
         int32 ReqOrRewMoney = quest->GetRewOrReqMoney(player);
         if (ReqOrRewMoney < 0)
             player->ModifyMoney(-ReqOrRewMoney);
         // check if Quest Tracker is enabled
         if (sWorld->getBoolConfig(CONFIG_QUEST_ENABLE_QUEST_TRACKER))
         {
             // prepare Quest Tracker datas
             auto stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_QUEST_TRACK_GM_COMPLETE);
             stmt->setUInt32(0, quest->GetQuestId());
             stmt->setUInt32(1, player->GetGUID().GetCounter());
             // add to Quest Tracker
             CharacterDatabase.Execute(stmt);
         }
         player->CompleteQuest(entry);
         return true;
     }
References Player::CanStoreNewItem(), CHAR_UPD_QUEST_TRACK_GM_COMPLETE, CharacterDatabase, Player::CompleteQuest(), CONFIG_QUEST_ENABLE_QUEST_TRACKER, ObjectGuid::Empty, EQUIP_ERR_OK, ChatHandler::extractKeyFromLink(), ObjectGuid::GetCounter(), Object::GetGUID(), Player::GetItemCount(), Quest::GetQuestId(), Player::GetQuestStatus(), Quest::GetRepObjectiveFaction(), Quest::GetRepObjectiveFaction2(), Quest::GetRepObjectiveValue(), Quest::GetRepObjectiveValue2(), ReputationMgr::GetReputation(), Player::GetReputationMgr(), Quest::GetRewOrReqMoney(), ChatHandler::getSelectedPlayer(), Player::KillCreditGO(), Player::KilledMonster(), LANG_COMMAND_QUEST_NOTFOUND, LANG_NO_CHAR_SELECTED, Player::ModifyMoney(), NULL_BAG, NULL_SLOT, ChatHandler::PSendSysMessage(), QUEST_ITEM_OBJECTIVES_COUNT, QUEST_OBJECTIVES_COUNT, QUEST_STATUS_NONE, Quest::RequiredItemCount, Quest::RequiredItemId, Quest::RequiredNpcOrGo, Quest::RequiredNpcOrGoCount, Player::SendNewItem(), ChatHandler::SendSysMessage(), ReputationMgr::SetReputation(), ChatHandler::SetSentErrorMessage(), sFactionStore, sObjectMgr, Player::StoreNewItem(), and sWorld.
HandleQuestRemove()
static bool quest_commandscript::HandleQuestRemove (ChatHandler * handler, const char * args) inline static
Definition at line 109 of file cs_quest.cpp.
     {
         Player* player = handler->getSelectedPlayer();
         if (!player)
         {
             handler->SendSysMessage(LANG_NO_CHAR_SELECTED);
             handler->SetSentErrorMessage(true);
             return false;
         }
         // .removequest #entry'
         // number or [name] Shift-click form |color|Hquest:quest_id:quest_level|h[name]|h|r
         char* cId = handler->extractKeyFromLink((char*)args, "Hquest");
         if (!cId)
             return false;
         uint32 entry = atol(cId);
         Quest const* quest = sObjectMgr->GetQuestTemplate(entry);
         if (!quest)
         {
             handler->PSendSysMessage(LANG_COMMAND_QUEST_NOTFOUND, entry);
             handler->SetSentErrorMessage(true);
             return false;
         }
         // remove all quest entries for 'entry' from quest log
         for (uint8 slot = 0; slot < MAX_QUEST_LOG_SIZE; ++slot)
         {
             uint32 logQuest = player->GetQuestSlotQuestId(slot);
             if (logQuest == entry)
             {
                 player->SetQuestSlot(slot, 0);
                 // we ignore unequippable quest items in this case, its' still be equipped
                 player->TakeQuestSourceItem(logQuest, false);
                 if (quest->HasFlag(QUEST_FLAGS_FLAGS_PVP))
                 {
                     player->pvpInfo.IsHostile = player->pvpInfo.IsInHostileArea || player->HasPvPForcingQuest();
                     player->UpdatePvPState();
                 }
             }
         }
         player->RemoveRewardedQuest(entry);
         player->RemoveActiveQuest(entry, false);
         handler->SendSysMessage(LANG_COMMAND_QUEST_REMOVED);
         return true;
     }
References ChatHandler::extractKeyFromLink(), Player::GetQuestSlotQuestId(), ChatHandler::getSelectedPlayer(), Quest::HasFlag(), Player::HasPvPForcingQuest(), PvPInfo::IsHostile, PvPInfo::IsInHostileArea, LANG_COMMAND_QUEST_NOTFOUND, LANG_COMMAND_QUEST_REMOVED, LANG_NO_CHAR_SELECTED, MAX_QUEST_LOG_SIZE, ChatHandler::PSendSysMessage(), Player::pvpInfo, QUEST_FLAGS_FLAGS_PVP, Player::RemoveActiveQuest(), Player::RemoveRewardedQuest(), ChatHandler::SendSysMessage(), Player::SetQuestSlot(), ChatHandler::SetSentErrorMessage(), sObjectMgr, Player::TakeQuestSourceItem(), and Player::UpdatePvPState().
HandleQuestReward()
static bool quest_commandscript::HandleQuestReward (ChatHandler * handler, char const * args) inline static
Definition at line 267 of file cs_quest.cpp.
     {
         Player* player = handler->getSelectedPlayer();
         if (!player)
         {
             handler->SendSysMessage(LANG_NO_CHAR_SELECTED);
             handler->SetSentErrorMessage(true);
             return false;
         }
         // .quest reward #entry
         // number or [name] Shift-click form |color|Hquest:quest_id:quest_level|h[name]|h|r
         char* cId = handler->extractKeyFromLink((char*)args, "Hquest");
         if (!cId)
             return false;
         uint32 entry = atol(cId);
         Quest const* quest = sObjectMgr->GetQuestTemplate(entry);
         // If player doesn't have the quest
         if (!quest || player->GetQuestStatus(entry) != QUEST_STATUS_COMPLETE)
         {
             handler->PSendSysMessage(LANG_COMMAND_QUEST_NOTFOUND, entry);
             handler->SetSentErrorMessage(true);
             return false;
         }
         player->RewardQuest(quest, 0, player);
         return true;
     }
References ChatHandler::extractKeyFromLink(), Player::GetQuestStatus(), ChatHandler::getSelectedPlayer(), LANG_COMMAND_QUEST_NOTFOUND, LANG_NO_CHAR_SELECTED, ChatHandler::PSendSysMessage(), QUEST_STATUS_COMPLETE, Player::RewardQuest(), ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), and sObjectMgr.
The documentation for this class was generated from the following file:
src/server/scripts/Commands/cs_quest.cpp