Azerotcore-wotlk: npc_plucky Class Reference
npc_plucky Class Reference
Classes
struct npc_pluckyAI
Public Member Functions
npc_plucky ()
bool OnGossipSelect (Player *player, Creature *, uint32, uint32 action) override
bool OnGossipHello (Player *player, Creature *creature) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 218 of file zone_thousand_needles.cpp.
Constructor & Destructor Documentation
npc_plucky()
npc_plucky::npc_plucky () inline
Definition at line 221 of file zone_thousand_needles.cpp.
 : CreatureScript("npc_plucky") { }
Member Function Documentation
GetAI()
CreatureAI* npc_plucky::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 246 of file zone_thousand_needles.cpp.
     {
         return new npc_pluckyAI(creature);
     }
OnGossipHello()
bool npc_plucky::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 236 of file zone_thousand_needles.cpp.
     {
         if (player->GetQuestStatus(QUEST_SCOOP) == QUEST_STATUS_INCOMPLETE)
             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_P, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
         SendGossipMenuFor(player, 738, creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), Object::GetGUID(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_P, GOSSIP_SENDER_MAIN, QUEST_SCOOP, QUEST_STATUS_INCOMPLETE, and SendGossipMenuFor().
OnGossipSelect()
bool npc_plucky::OnGossipSelect (Player * player, Creature * , uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 223 of file zone_thousand_needles.cpp.
     {
         ClearGossipMenuFor(player);
         switch (action)
         {
             case GOSSIP_ACTION_INFO_DEF+1:
                 CloseGossipMenuFor(player);
                 player->CompleteQuest(QUEST_SCOOP);
                 break;
         }
         return true;
     }
References ClearGossipMenuFor(), CloseGossipMenuFor(), Player::CompleteQuest(), GOSSIP_ACTION_INFO_DEF, and QUEST_SCOOP.
The documentation for this class was generated from the following file:
src/server/scripts/Kalimdor/zone_thousand_needles.cpp