Azerotcore-wotlk: src/server/game/Chat/ChatCommands/ChatCommand.cpp File Reference
ChatCommand.cpp File Reference
#include "ChatCommand.h"
#include "AccountMgr.h"
#include "Chat.h"
#include "DBCStores.h"
#include "DatabaseEnv.h"
#include "Log.h"
#include "Player.h"
#include "ScriptMgr.h"
#include "StringFormat.h"
#include "Tokenize.h"
#include "WorldSession.h"
Classes
struct Acore::Impl::ChatCommands::FilteredCommandListIterator
Namespaces
Acore
Acore::Impl
Acore::Impl::ChatCommands
Typedefs
using ChatSubCommandMap = std::map< std::string_view, Acore::Impl::ChatCommands::ChatCommandNode, StringCompareLessI_T >
Functions
static void LogCommandUsage (WorldSession const &session, std::string_view cmdStr)
Variables
static ChatSubCommandMap COMMAND_MAP
Typedef Documentation
ChatSubCommandMap
using ChatSubCommandMap = std::map<std::string_view, Acore::Impl::ChatCommands::ChatCommandNode, StringCompareLessI_T>
Definition at line 34 of file ChatCommand.cpp.
Function Documentation
LogCommandUsage()
static void LogCommandUsage (WorldSession const & session, std::string_view cmdStr) static
Definition at line 159 of file ChatCommand.cpp.
 {
     if (AccountMgr::IsPlayerAccount(session.GetSecurity()))
         return;
     Player* player = session.GetPlayer();
     ObjectGuid targetGuid = player->GetTarget();
     uint32 areaId = player->GetAreaId();
     uint32 zoneId = player->GetZoneId();
     std::string areaName = "Unknown";
     std::string zoneName = "Unknown";
     LocaleConstant locale = sWorld->GetDefaultDbcLocale();
     if (AreaTableEntry const* area = sAreaTableStore.LookupEntry(areaId))
     {
         areaName = area->area_name[locale];
     }
     if (AreaTableEntry const* zone = sAreaTableStore.LookupEntry(zoneId))
     {
         zoneName = zone->area_name[locale];
     }
     std::string logMessage = Acore::StringFormatFmt("Command: {} [Player: {} ({}) (Account: {}) X: {} Y: {} Z: {} Map: {} ({}) Area: {} ({}) Zone: {} ({}) Selected: {} ({})]",
         cmdStr, player->GetName(), player->GetGUID().ToString(),
         session.GetAccountId(),
         player->GetPositionX(), player->GetPositionY(), player->GetPositionZ(), player->GetMapId(),
         player->FindMap() ? player->FindMap()->GetMapName() : "Unknown",
         areaId, areaName, zoneId, zoneName,
         (player->GetSelectedUnit()) ? player->GetSelectedUnit()->GetName() : "",
         targetGuid.ToString());
     LOG_GM(session.GetAccountId(), logMessage);
 }
References WorldObject::FindMap(), WorldSession::GetAccountId(), WorldObject::GetAreaId(), Object::GetGUID(), WorldLocation::GetMapId(), Map::GetMapName(), WorldObject::GetName(), WorldSession::GetPlayer(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), WorldSession::GetSecurity(), Player::GetSelectedUnit(), Unit::GetTarget(), WorldObject::GetZoneId(), AccountMgr::IsPlayerAccount(), LOG_GM, sAreaTableStore, Acore::StringFormatFmt(), sWorld, and ObjectGuid::ToString().
Referenced by Acore::Impl::ChatCommands::ChatCommandNode::TryExecuteCommand().
Variable Documentation
COMMAND_MAP
ChatSubCommandMap COMMAND_MAP static
Definition at line 72 of file ChatCommand.cpp.
Referenced by Acore::Impl::ChatCommands::ChatCommandNode::GetTopLevelMap(), Acore::Impl::ChatCommands::ChatCommandNode::InvalidateCommandMap(), and Acore::Impl::ChatCommands::ChatCommandNode::LoadCommandMap().