Azerotcore-wotlk: npc_shay_leafrunner::npc_shay_leafrunnerAI Struct Reference
npc_shay_leafrunner::npc_shay_leafrunnerAI Struct Reference
Public Member Functions
npc_shay_leafrunnerAI (Creature *creature)
void InitializeAI () override
void JustRespawned () override
void MoveInLineOfSight (Unit *target) override
void EnterEvadeMode () override
void FailQuest (Player *player, bool despawn)
void JustDied (Unit *) override
void sQuestAccept (Player *player, Quest const *quest) override
void SpellHit (Unit *caster, SpellInfo const *spellInfo) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
ObjectGuid _playerGUID
ObjectGuid _rockbiterGUID
EventMap _events
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 95 of file zone_feralas.cpp.
Constructor & Destructor Documentation
npc_shay_leafrunnerAI()
npc_shay_leafrunner::npc_shay_leafrunnerAI::npc_shay_leafrunnerAI (Creature * creature) inline
Definition at line 97 of file zone_feralas.cpp.
 : ScriptedAI(creature) {}
Member Function Documentation
EnterEvadeMode()
void npc_shay_leafrunner::npc_shay_leafrunnerAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 152 of file zone_feralas.cpp.
         {
             _EnterEvadeMode();
             if (Player* player = ObjectAccessor::GetPlayer(*me, _playerGUID))
             {
                 me->GetMotionMaster()->MoveFollow(player, 3.f, M_PI);
             }
         }
References CreatureAI::_EnterEvadeMode(), _playerGUID, Unit::GetMotionMaster(), ObjectAccessor::GetPlayer(), ScriptedAI::me, and MotionMaster::MoveFollow().
FailQuest()
void npc_shay_leafrunner::npc_shay_leafrunnerAI::FailQuest (Player * player, bool despawn) inline
Definition at line 162 of file zone_feralas.cpp.
         {
             if (player)
             {
                 player->FailQuest(QUEST_WANDERING_SHAY);
                 if (Group* group = player->GetGroup())
                 {
                     for (GroupReference* groupRef = group->GetFirstMember(); groupRef != nullptr; groupRef = groupRef->next())
                     {
                         if (Player* member = groupRef->GetSource())
{
                             if (member->GetGUID() != player->GetGUID())
{
                                 member->FailQuest(QUEST_WANDERING_SHAY);
                             }
                         }
                     }
                 }
             }
             if (despawn)
             {
                 me->DespawnOrUnsummon(1);
             }
         }
References Creature::DespawnOrUnsummon(), Player::FailQuest(), Player::GetGroup(), Object::GetGUID(), ScriptedAI::me, GroupReference::next(), and QUEST_WANDERING_SHAY.
Referenced by JustDied(), and UpdateAI().
InitializeAI()
void npc_shay_leafrunner::npc_shay_leafrunnerAI::InitializeAI () inline override virtual
Reimplemented from UnitAI.
Definition at line 99 of file zone_feralas.cpp.
         {
             me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_QUESTGIVER);
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
             me->RestoreFaction();
             _events.Reset();
             _playerGUID.Clear();
             _rockbiterGUID.Clear();
         }
References _events, _playerGUID, _rockbiterGUID, ObjectGuid::Clear(), ScriptedAI::me, EventMap::Reset(), Unit::RestoreFaction(), Object::SetFlag(), UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, UNIT_NPC_FLAG_QUESTGIVER, and UNIT_NPC_FLAGS.
Referenced by JustRespawned().
JustDied()
void npc_shay_leafrunner::npc_shay_leafrunnerAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 189 of file zone_feralas.cpp.
         {
             if (Player* player = ObjectAccessor::GetPlayer(*me, _playerGUID))
             {
                 FailQuest(player, false);
             }
         }
References _playerGUID, FailQuest(), ObjectAccessor::GetPlayer(), and ScriptedAI::me.
JustRespawned()
void npc_shay_leafrunner::npc_shay_leafrunnerAI::JustRespawned () inline override virtual
Reimplemented from CreatureAI.
Definition at line 110 of file zone_feralas.cpp.
         {
             InitializeAI();
             me->SetHomePosition(me->GetPosition());
         }
References Position::GetPosition(), InitializeAI(), ScriptedAI::me, and Creature::SetHomePosition().
MoveInLineOfSight()
void npc_shay_leafrunner::npc_shay_leafrunnerAI::MoveInLineOfSight (Unit * target) inline override virtual
Reimplemented from CreatureAI.
Definition at line 116 of file zone_feralas.cpp.
         {
             if (!_playerGUID || target->GetEntry() != NPC_ROCKBITER || !me->IsInRange(target, 0.f, 10.f))
             {
                 if (!me->IsInCombat() && !me->GetVictim())
                 {
                     if (Player* player = ObjectAccessor::GetPlayer(*me, _playerGUID))
                     {
                         if (Unit* victim = player->GetVictim())
{
                             if (me->CanStartAttack(victim))
{
                                 AttackStart(victim);
                             }
                         }
                     }
                 }
                 return;
             }
             _rockbiterGUID = target->GetGUID();
             Talk(TALK_4, target);
             me->SetControlled(true, UNIT_STATE_ROOT);
             if (Player* player = ObjectAccessor::GetPlayer(*me, _playerGUID))
             {
                 player->GroupEventHappens(QUEST_WANDERING_SHAY, me);
             }
             _events.CancelEvent(EVENT_WANDERING_START);
             _events.ScheduleEvent(EVENT_FINAL_TALK, 5 * IN_MILLISECONDS);
         }
References _events, _playerGUID, _rockbiterGUID, ScriptedAI::AttackStart(), EventMap::CancelEvent(), Creature::CanStartAttack(), EVENT_FINAL_TALK, EVENT_WANDERING_START, Object::GetEntry(), Object::GetGUID(), ObjectAccessor::GetPlayer(), Unit::GetVictim(), IN_MILLISECONDS, Unit::IsInCombat(), WorldObject::IsInRange(), ScriptedAI::me, NPC_ROCKBITER, QUEST_WANDERING_SHAY, EventMap::ScheduleEvent(), Unit::SetControlled(), CreatureAI::Talk(), TALK_4, and UNIT_STATE_ROOT.
SpellHit()
void npc_shay_leafrunner::npc_shay_leafrunnerAI::SpellHit (Unit * caster, SpellInfo const * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 215 of file zone_feralas.cpp.
         {
             if (spellInfo->Id == SPELL_SHAY_BELL)
             {
                 _playerGUID = caster->GetGUID();
                 Talk(TALK_1, caster);
                 me->GetMotionMaster()->MoveIdle();
                 me->GetMotionMaster()->MoveFollow(caster, 3.f, M_PI);
             }
         }
References _playerGUID, Object::GetGUID(), Unit::GetMotionMaster(), SpellInfo::Id, ScriptedAI::me, MotionMaster::MoveFollow(), MotionMaster::MoveIdle(), SPELL_SHAY_BELL, CreatureAI::Talk(), and TALK_1.
sQuestAccept()
void npc_shay_leafrunner::npc_shay_leafrunnerAI::sQuestAccept (Player * player, Quest const * quest) inline override virtual
Reimplemented from UnitAI.
Definition at line 197 of file zone_feralas.cpp.
         {
             if (quest->GetQuestId() == QUEST_WANDERING_SHAY)
             {
                 _playerGUID = player->GetGUID();
                 Talk(TALK_0, player);
                 me->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_QUESTGIVER);
                 me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
                 me->SetFaction(FACTION_ESCORT_N_NEUTRAL_ACTIVE);
                 me->GetMotionMaster()->MoveFollow(player, 3.f, M_PI);
                 _events.ScheduleEvent(EVENT_WANDERING_START, urand(40 * IN_MILLISECONDS, 70 * IN_MILLISECONDS));
                 _events.ScheduleEvent(EVENT_CHECK_FOLLOWER, 30 * IN_MILLISECONDS);
             }
         }
References _events, _playerGUID, EVENT_CHECK_FOLLOWER, EVENT_WANDERING_START, FACTION_ESCORT_N_NEUTRAL_ACTIVE, Object::GetGUID(), Unit::GetMotionMaster(), Quest::GetQuestId(), IN_MILLISECONDS, ScriptedAI::me, MotionMaster::MoveFollow(), QUEST_WANDERING_SHAY, Object::RemoveFlag(), EventMap::ScheduleEvent(), Unit::SetFaction(), CreatureAI::Talk(), TALK_0, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, UNIT_NPC_FLAG_QUESTGIVER, UNIT_NPC_FLAGS, and urand().
UpdateAI()
void npc_shay_leafrunner::npc_shay_leafrunnerAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 228 of file zone_feralas.cpp.
         {
             if (UpdateVictim())
             {
                 DoMeleeAttackIfReady();
                 return;
             }
             _events.Update(diff);
             while (uint32 eventId = _events.ExecuteEvent())
             {
                 switch (eventId)
                 {
                     case EVENT_WANDERING_START:
                     {
                         Position pos = me->GetFirstCollisionPosition(15.f, rand_norm() * static_cast<float>(2 * M_PI));
                         me->GetMotionMaster()->MovePoint(0, pos);
                         Talk(TALK_2);
                         _events.ScheduleEvent(EVENT_WANDERING_START, urand(60 * IN_MILLISECONDS, 70 * IN_MILLISECONDS));
                         _events.ScheduleEvent(EVENT_WANDERING_TALK, 3 * IN_MILLISECONDS);
                         _events.ScheduleEvent(EVENT_WANDERING_RANDOM, 8 * IN_MILLISECONDS);
                         break;
                     }
                     case EVENT_WANDERING_TALK:
                         Talk(TALK_3);
                         break;
                     case EVENT_WANDERING_RANDOM:
                         me->SetHomePosition(me->GetPosition());
                         me->GetMotionMaster()->MoveRandom(15.f);
                         break;
                     case EVENT_FINAL_TALK:
                         if (Creature* robckbiter = ObjectAccessor::GetCreature(*me, _rockbiterGUID))
{
                             robckbiter->AI()->Talk(TALK_0, me);
                         }
                         me->DespawnOrUnsummon(10 * IN_MILLISECONDS);
                         break;
                     case EVENT_CHECK_FOLLOWER:
                     {
                         Player* player = ObjectAccessor::GetPlayer(*me, _playerGUID);
                         if (!player || !player->IsAlive() || !me->IsInRange(player, 0.f, 50.f))
{
                             FailQuest(player, true);
                         }
                         break;
                     }
                     default:
                         break;
                 }
             }
         }
References _events, _playerGUID, _rockbiterGUID, Creature::DespawnOrUnsummon(), UnitAI::DoMeleeAttackIfReady(), EVENT_CHECK_FOLLOWER, EVENT_FINAL_TALK, EVENT_WANDERING_RANDOM, EVENT_WANDERING_START, EVENT_WANDERING_TALK, EventMap::ExecuteEvent(), FailQuest(), ObjectAccessor::GetCreature(), WorldObject::GetFirstCollisionPosition(), Unit::GetMotionMaster(), ObjectAccessor::GetPlayer(), Position::GetPosition(), IN_MILLISECONDS, Unit::IsAlive(), WorldObject::IsInRange(), ScriptedAI::me, MotionMaster::MovePoint(), MotionMaster::MoveRandom(), rand_norm(), EventMap::ScheduleEvent(), Creature::SetHomePosition(), CreatureAI::Talk(), TALK_0, TALK_2, TALK_3, EventMap::Update(), CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
_events
EventMap npc_shay_leafrunner::npc_shay_leafrunnerAI::_events private
Definition at line 283 of file zone_feralas.cpp.
Referenced by InitializeAI(), MoveInLineOfSight(), sQuestAccept(), and UpdateAI().
_playerGUID
ObjectGuid npc_shay_leafrunner::npc_shay_leafrunnerAI::_playerGUID private
Definition at line 281 of file zone_feralas.cpp.
Referenced by EnterEvadeMode(), InitializeAI(), JustDied(), MoveInLineOfSight(), SpellHit(), sQuestAccept(), and UpdateAI().
_rockbiterGUID
ObjectGuid npc_shay_leafrunner::npc_shay_leafrunnerAI::_rockbiterGUID private
Definition at line 282 of file zone_feralas.cpp.
Referenced by InitializeAI(), MoveInLineOfSight(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/zone_feralas.cpp