Azerotcore-wotlk: boss_malygos::boss_malygosAI Struct Reference
boss_malygos::boss_malygosAI Struct Reference
Public Member Functions
boss_malygosAI (Creature *c)
void InitializeAI () override
void Reset () override
void MovementInform (uint32 type, uint32 id) override
void SpellHit (Unit *, const SpellInfo *spell) override
void EnterCombat (Unit *) override
void AttackStart (Unit *victim) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *victim) override
void JustSummoned (Creature *summon) override
void MoveInLineOfSight (Unit *) override
void EnterEvadeMode () override
void HandleIntroSpeech (const uint32 diff)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
EventMap events
SummonList summons
uint32 timer1
uint32 timer2
uint8 IntroCounter
bool bLockHealthCheck
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 207 of file boss_malygos.cpp.
Constructor & Destructor Documentation
boss_malygosAI()
boss_malygos::boss_malygosAI::boss_malygosAI (Creature * c) inline
Definition at line 209 of file boss_malygos.cpp.
                                     : ScriptedAI(c), summons(me)
         {
             pInstance = me->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), ScriptedAI::me, and pInstance.
Member Function Documentation
AttackStart()
void boss_malygos::boss_malygosAI::AttackStart (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 338 of file boss_malygos.cpp.
         {
             if (!victim)
                 return;
             if (me->GetVictim() && me->GetVictim()->GetGUID() == victim->GetGUID() && !me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_PACIFIED))
             {
                 if (!me->GetGuidValue(UNIT_FIELD_TARGET))
                     me->SetTarget(victim->GetGUID());
             }
             else if (me->Attack(victim, true))
             {
                 if (!me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_PACIFIED))
                     me->GetMotionMaster()->MoveChase(victim);
                 else
                     me->SetTarget();
             }
         }
References Unit::Attack(), Object::GetGUID(), Object::GetGuidValue(), Unit::GetMotionMaster(), Unit::GetVictim(), Object::HasFlag(), ScriptedAI::me, MotionMaster::MoveChase(), Creature::SetTarget(), UNIT_FIELD_FLAGS, UNIT_FIELD_TARGET, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_PACIFIED.
Referenced by UpdateAI().
DamageTaken()
void boss_malygos::boss_malygosAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 357 of file boss_malygos.cpp.
         {
             if (damage >= me->GetHealth() && !me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE)) // allow dying only in phase 3!
             {
                 damage = 0;
                 return;
             }
             if (!bLockHealthCheck && me->HealthBelowPctDamaged(50, damage))
             {
                 bLockHealthCheck = true;
                 events.RescheduleEvent(EVENT_START_PHASE_2, 0, 1);
             }
         }
References bLockHealthCheck, EVENT_START_PHASE_2, Unit::GetHealth(), Object::HasFlag(), Unit::HealthBelowPctDamaged(), ScriptedAI::me, UNIT_FIELD_FLAGS, and UNIT_FLAG_DISABLE_MOVE.
EnterCombat()
void boss_malygos::boss_malygosAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 326 of file boss_malygos.cpp.
         {
             events.Reset();
             DoZoneInCombat();
             Talk(SAY_PHASE_1);
             events.RescheduleEvent(EVENT_INTRO_MOVE_CENTER, 0, 1);
             if (pInstance)
                 pInstance->SetData(DATA_ENCOUNTER_STATUS, IN_PROGRESS);
         }
References DATA_ENCOUNTER_STATUS, CreatureAI::DoZoneInCombat(), EVENT_INTRO_MOVE_CENTER, IN_PROGRESS, pInstance, SAY_PHASE_1, ZoneScript::SetData(), and CreatureAI::Talk().
EnterEvadeMode()
void boss_malygos::boss_malygosAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 817 of file boss_malygos.cpp.
         {
             me->SetDisableGravity(true);
             me->GetMap()->SetZoneOverrideLight(AREA_EYE_OF_ETERNITY, LIGHT_GET_DEFAULT_FOR_MAP, 1s);
             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE);
             ScriptedAI::EnterEvadeMode();
         }
References AREA_EYE_OF_ETERNITY, CreatureAI::EnterEvadeMode(), WorldObject::GetMap(), LIGHT_GET_DEFAULT_FOR_MAP, ScriptedAI::me, Object::RemoveFlag(), Creature::SetDisableGravity(), Map::SetZoneOverrideLight(), UNIT_FIELD_FLAGS, and UNIT_FLAG_DISABLE_MOVE.
HandleIntroSpeech()
void boss_malygos::boss_malygosAI::HandleIntroSpeech (const uint32 diff) inline
Definition at line 825 of file boss_malygos.cpp.
         {
             if (me->IsInCombat() || me->isDead())
                 return;
             // speech timer
             if (timer1 <= diff)
             {
                 Talk(SAY_INTRO);
                 timer1 = MalygosIntroIntervals[IntroCounter];
                 if (++IntroCounter >= 5)
                     IntroCounter = 0;
             }
             else
                 timer1 -= diff;
             // movement timer
             if (timer2)
             {
                 if (timer2 <= diff)
                 {
                     timer2 = 0;
                     uint32 tmp = urand(0, 3);
                     me->RemoveUnitMovementFlag(MOVEMENTFLAG_WALKING);
                     me->GetMotionMaster()->MovePoint(MI_POINT_INTRO_SIDE_0 + tmp, FourSidesPos[tmp]);
                 }
                 else
                     timer2 -= diff;
             }
         }
References FourSidesPos, Unit::GetMotionMaster(), IntroCounter, Unit::isDead(), Unit::IsInCombat(), MalygosIntroIntervals, ScriptedAI::me, MI_POINT_INTRO_SIDE_0, MOVEMENTFLAG_WALKING, MotionMaster::MovePoint(), Unit::RemoveUnitMovementFlag(), SAY_INTRO, CreatureAI::Talk(), timer1, timer2, and urand().
Referenced by UpdateAI().
InitializeAI()
void boss_malygos::boss_malygosAI::InitializeAI () inline override virtual
Reimplemented from UnitAI.
Definition at line 222 of file boss_malygos.cpp.
         {
             me->SetDisableGravity(true);
             Reset();
         }
References ScriptedAI::me, Reset(), and Creature::SetDisableGravity().
JustDied()
void boss_malygos::boss_malygosAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 775 of file boss_malygos.cpp.
         {
             Talk(SAY_DEATH);
             if (pInstance)
             {
                 pInstance->DoUpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, NPC_MALYGOS, 1);
                 pInstance->SetData(DATA_ENCOUNTER_STATUS, DONE);
             }
         }
References ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, DATA_ENCOUNTER_STATUS, DONE, InstanceScript::DoUpdateAchievementCriteria(), NPC_MALYGOS, pInstance, SAY_DEATH, ZoneScript::SetData(), and CreatureAI::Talk().
JustSummoned()
void boss_malygos::boss_malygosAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 798 of file boss_malygos.cpp.
         {
             if (!summon)
                 return;
             summons.Summon(summon);
             switch(summon->GetEntry())
             {
                 case NPC_ARCANE_OVERLOAD:
                     summon->CastSpell(summon, SPELL_ARCANE_OVERLOAD_DMG, true);
                     summon->DespawnOrUnsummon(45000);
                     break;
                 case NPC_STATIC_FIELD:
                     summon->DespawnOrUnsummon(20000);
                     break;
             }
         }
References Unit::CastSpell(), Creature::DespawnOrUnsummon(), Object::GetEntry(), NPC_ARCANE_OVERLOAD, NPC_STATIC_FIELD, SPELL_ARCANE_OVERLOAD_DMG, SummonList::Summon(), and summons.
KilledUnit()
void boss_malygos::boss_malygosAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 785 of file boss_malygos.cpp.
         {
             if (victim && victim->GetGUID() == me->GetGUID())
                 return;
             if (events.IsInPhase(PHASE_ONE))
                 Talk(SAY_SLAY_P1);
             else if (events.IsInPhase(PHASE_TWO))
                 Talk(SAY_SLAY_P2);
             else
                 Talk(SAY_SLAY_P3);
         }
References Object::GetGUID(), ScriptedAI::me, PHASE_ONE, PHASE_TWO, SAY_SLAY_P1, SAY_SLAY_P2, SAY_SLAY_P3, and CreatureAI::Talk().
MoveInLineOfSight()
void boss_malygos::boss_malygosAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 815 of file boss_malygos.cpp.
 {}
MovementInform()
void boss_malygos::boss_malygosAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 250 of file boss_malygos.cpp.
         {
             if (type == POINT_MOTION_TYPE)
             {
                 switch (id)
                 {
                     case MI_POINT_INTRO_SIDE_0:
                     case MI_POINT_INTRO_SIDE_1:
                     case MI_POINT_INTRO_SIDE_2:
                     case MI_POINT_INTRO_SIDE_3:
{
                             float angle = me->GetOrientation();
                             float dist = 75.0f;
                             if (Creature* c = me->SummonCreature(NPC_PORTAL, me->GetPositionX() + cos(angle) * dist, me->GetPositionY() + sin(angle) * dist, me->GetPositionZ(), FourSidesPos[id].GetOrientation(), TEMPSUMMON_TIMED_DESPAWN, 13000))
                                 me->CastSpell(c, SPELL_PORTAL_BEAM, false);
                             timer2 = INTRO_MOVEMENT_INTERVAL - 10000;
                         }
                         break;
                     case MI_POINT_INTRO_CENTER_AIR:
                         events.RescheduleEvent(EVENT_INTRO_LAND, 0, 1);
                         break;
                     case MI_POINT_VORTEX_CENTER:
                         if (Creature* c = me->SummonCreature(NPC_WORLD_TRIGGER_LAOI, CenterPos, TEMPSUMMON_TIMED_DESPAWN, 15000))
                             c->CastSpell(c, SPELL_VORTEX_VISUAL, true);
                         events.RescheduleEvent(EVENT_START_VORTEX_REAL, 1000, 1);
                         break;
                     case MI_POINT_CENTER_GROUND_PH_2:
                         events.RescheduleEvent(EVENT_START_PHASE_2_FLY_UP, 0, 1);
                         break;
                     case MI_POINT_CIRCLE_OUTSIDE_PH_2:
                         events.RescheduleEvent(EVENT_RESUME_FLYING_CIRCLES_PH_2, 0, 1);
                         break;
                     case MI_POINT_SURGE_OF_POWER_CENTER:
                         events.RescheduleEvent(EVENT_SURGE_OF_POWER_WARNING, 0, 1);
                         break;
                 }
             }
             else if (type == EFFECT_MOTION_TYPE)
             {
                 switch (id)
                 {
                     case MI_POINT_INTRO_LAND:
                         me->SetDisableGravity(false);
                         events.RescheduleEvent(EVENT_START_FIGHT, 0, 1);
                         break;
                     case MI_POINT_VORTEX_TAKEOFF:
                         events.RescheduleEvent(EVENT_VORTEX_FLY_TO_CENTER, 0, 1);
                         break;
                     case MI_POINT_VORTEX_LAND:
                         me->SetDisableGravity(false);
                         events.RescheduleEvent(EVENT_VORTEX_LAND_1, 0, 1);
                         break;
                     case MI_POINT_CENTER_AIR_PH_2:
                         me->GetMap()->SetZoneOverrideLight(AREA_EYE_OF_ETERNITY, LIGHT_ARCANE_RUNES, 5s);
                         break;
                     case MI_POINT_PH_3_FIGHT_POSITION:
                         events.RescheduleEvent(EVENT_START_PHASE_3, 6000, 1);
                         break;
                 }
             }
         }
References AREA_EYE_OF_ETERNITY, Unit::CastSpell(), CenterPos, EFFECT_MOTION_TYPE, EVENT_INTRO_LAND, EVENT_RESUME_FLYING_CIRCLES_PH_2, EVENT_START_FIGHT, EVENT_START_PHASE_2_FLY_UP, EVENT_START_PHASE_3, EVENT_START_VORTEX_REAL, EVENT_SURGE_OF_POWER_WARNING, EVENT_VORTEX_FLY_TO_CENTER, EVENT_VORTEX_LAND_1, FourSidesPos, WorldObject::GetMap(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), INTRO_MOVEMENT_INTERVAL, LIGHT_ARCANE_RUNES, ScriptedAI::me, MI_POINT_CENTER_AIR_PH_2, MI_POINT_CENTER_GROUND_PH_2, MI_POINT_CIRCLE_OUTSIDE_PH_2, MI_POINT_INTRO_CENTER_AIR, MI_POINT_INTRO_LAND, MI_POINT_INTRO_SIDE_0, MI_POINT_INTRO_SIDE_1, MI_POINT_INTRO_SIDE_2, MI_POINT_INTRO_SIDE_3, MI_POINT_PH_3_FIGHT_POSITION, MI_POINT_SURGE_OF_POWER_CENTER, MI_POINT_VORTEX_CENTER, MI_POINT_VORTEX_LAND, MI_POINT_VORTEX_TAKEOFF, NPC_PORTAL, NPC_WORLD_TRIGGER_LAOI, POINT_MOTION_TYPE, Creature::SetDisableGravity(), Map::SetZoneOverrideLight(), SPELL_PORTAL_BEAM, SPELL_VORTEX_VISUAL, WorldObject::SummonCreature(), TEMPSUMMON_TIMED_DESPAWN, and timer2.
Reset()
void boss_malygos::boss_malygosAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 228 of file boss_malygos.cpp.
         {
             events.Reset();
             events.SetPhase(PHASE_NONE);
             summons.DespawnAll();
             timer1 = MalygosIntroIntervals[4];
             timer2 = INTRO_MOVEMENT_INTERVAL;
             IntroCounter = 0;
             bLockHealthCheck = false;
             me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_PACIFIED);
             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE);
             if (pInstance)
             {
                 pInstance->SetData(DATA_ENCOUNTER_STATUS, NOT_STARTED);
                 pInstance->DoStopTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, ACHIEV_YOU_DONT_HAVE_AN_ENTERNITY_EVENT);
             }
         }
References ACHIEV_YOU_DONT_HAVE_AN_ENTERNITY_EVENT, ACHIEVEMENT_TIMED_TYPE_EVENT, bLockHealthCheck, DATA_ENCOUNTER_STATUS, SummonList::DespawnAll(), InstanceScript::DoStopTimedAchievement(), EMOTE_ONESHOT_NONE, INTRO_MOVEMENT_INTERVAL, IntroCounter, MalygosIntroIntervals, ScriptedAI::me, NOT_STARTED, PHASE_NONE, pInstance, Object::RemoveFlag(), ZoneScript::SetData(), Object::SetFlag(), Object::SetUInt32Value(), summons, timer1, timer2, UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_PACIFIED, and UNIT_NPC_EMOTESTATE.
Referenced by InitializeAI().
SpellHit()
void boss_malygos::boss_malygosAI::SpellHit (Unit * , const SpellInfo * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 313 of file boss_malygos.cpp.
         {
             if (spell->Id == SPELL_POWER_SPARK_MALYGOS_BUFF)
             {
                 if (!bLockHealthCheck)
                 {
                     Talk(SAY_BUFFED_BY_SPARK);
                 }
                 else
                     me->RemoveAura(SPELL_POWER_SPARK_MALYGOS_BUFF);
             }
         }
References bLockHealthCheck, SpellInfo::Id, ScriptedAI::me, Unit::RemoveAura(), SAY_BUFFED_BY_SPARK, SPELL_POWER_SPARK_MALYGOS_BUFF, and CreatureAI::Talk().
UpdateAI()
void boss_malygos::boss_malygosAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 372 of file boss_malygos.cpp.
         {
             HandleIntroSpeech(diff);
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch(events.ExecuteEvent())
             {
                 case 0:
                     break;
                 case EVENT_BERSERK:
                     me->CastSpell(me, SPELL_BERSERK, true);
                     Talk(EMOTE_BERSERK);
                     break;
                 case EVENT_INTRO_MOVE_CENTER:
                     {
                         if (pInstance)
                             pInstance->SetData(DATA_SET_IRIS_INACTIVE, 0);
                         summons.DespawnAll();
                         me->InterruptNonMeleeSpells(true);
                         me->RemoveAllAuras();
                         float angle = CenterPos.GetAngle(me);
                         float x = CenterPos.GetPositionX() + cos(angle) * 35.0f;
                         float y = CenterPos.GetPositionY() + sin(angle) * 35.0f;
                         float z = FourSidesPos[0].GetPositionZ();
                         me->RemoveUnitMovementFlag(MOVEMENTFLAG_WALKING);
                         me->GetMotionMaster()->MovePoint(MI_POINT_INTRO_CENTER_AIR, x, y, z);
                         break;
                     }
                 case EVENT_INTRO_LAND:
                     {
                         me->GetMotionMaster()->MoveLand(MI_POINT_INTRO_LAND, me->GetPositionX(), me->GetPositionY(), CenterPos.GetPositionZ(), 7.0f);
                         break;
                     }
                 case EVENT_START_FIGHT:
                     {
                         if (pInstance)
{
                             pInstance->SetData(DATA_HIDE_IRIS_AND_PORTAL, 0);
                             pInstance->DoStartTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, ACHIEV_YOU_DONT_HAVE_AN_ENTERNITY_EVENT);
                         }
                         me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_PACIFIED);
                         if (Unit* target = me->SelectNearestTarget(250.0f))
{
                             AttackStart(target);
                             me->GetMotionMaster()->MoveChase(target);
                         }
                         events.SetPhase(PHASE_ONE);
                         events.RescheduleEvent(EVENT_BERSERK, 600000, 0);
                         events.RescheduleEvent(EVENT_SPELL_ARCANE_BREATH, urand(9000, 12000), 1);
                         events.RescheduleEvent(EVENT_SPELL_ARCANE_STORM, urand(2000, 5000), 1);
                         events.RescheduleEvent(EVENT_SUMMON_POWER_SPARK, urand(10000, 15000), 1);
                         events.RescheduleEvent(EVENT_START_VORTEX_0, 30000, 1);
                         break;
                     }
                 case EVENT_SPELL_ARCANE_BREATH:
                     me->CastSpell(me->GetVictim(), SPELL_ARCANE_BREATH, false);
                     events.RepeatEvent(urand(12000, 15000));
                     break;
                 case EVENT_SPELL_ARCANE_STORM:
                     me->CastCustomSpell(SPELL_ARCANE_STORM, SPELLVALUE_MAX_TARGETS, DUNGEON_MODE(5, 12), me, true);
                     events.RepeatEvent(urand(10000, 15000));
                     break;
                 case EVENT_SUMMON_POWER_SPARK:
                     {
                         uint8 random = urand(0, 3);
                         if (Creature* c = me->SummonCreature(NPC_PORTAL, FourSidesPos[random], TEMPSUMMON_TIMED_DESPAWN, 6000))
                             c->CastSpell(c, SPELL_PORTAL_BEAM, false);
                         if (Creature* c = me->SummonCreature(NPC_POWER_SPARK, FourSidesPos[random], TEMPSUMMON_MANUAL_DESPAWN, 0))
{
                             c->AI()->DoAction(1);
                             c->AI()->Talk(EMOTE_POWER_SPARK);
                         }
                         events.RepeatEvent(urand(20000, 30000));
                     }
                     break;
                 case EVENT_START_VORTEX_0:
                     {
                         bLockHealthCheck = true;
                         Talk(SAY_MAGIC_BLAST);
                         EntryCheckPredicate pred(NPC_POWER_SPARK);
                         summons.DoAction(2, pred); // stop following
                         me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PACIFIED);
                         me->SendMeleeAttackStop(me->GetVictim());
                         me->SetTarget();
                         me->GetMotionMaster()->MoveIdle();
                         me->StopMoving();
                         me->SetDisableGravity(true);
                         me->GetMotionMaster()->MoveTakeoff(MI_POINT_VORTEX_TAKEOFF, me->GetPositionX(), me->GetPositionY(), CenterPos.GetPositionZ() + 20.0f, 7.0f);
                         events.DelayEvents(25000, 1); // don't delay berserk (group 0)
                     }
                     break;
                 case EVENT_VORTEX_FLY_TO_CENTER:
                     me->GetMotionMaster()->MovePoint(MI_POINT_VORTEX_CENTER, CenterPos.GetPositionX(), CenterPos.GetPositionY(), CenterPos.GetPositionZ() + 20.0f);
                     break;
                 case EVENT_START_VORTEX_REAL:
                     {
                         me->SendMeleeAttackStop(me->GetVictim());
                         me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_CUSTOM_SPELL_01);
                         me->HandleEmoteCommand(EMOTE_STATE_CUSTOM_SPELL_01);
                         Position pos;
                         float angle = (me->GetOrientation() >= M_PI / 4 ? me->GetOrientation() - M_PI / 4 : 7 * M_PI / 4 + me->GetOrientation());
                         pos.m_positionX = CenterPos.GetPositionX() + cos(angle) * 40.0f;
                         pos.m_positionY = CenterPos.GetPositionY() + sin(angle) * 40.0f;
                         pos.m_positionZ = CenterPos.GetPositionZ() + 20.0f;
                         pos.m_orientation = pos.GetAngle(&CenterPos);
                         if (Creature* vp = me->SummonCreature(NPC_WORLD_TRIGGER_LAOI, pos, TEMPSUMMON_TIMED_DESPAWN, 14000))
{
                             vp->SetDisableGravity(true);
                             Map::PlayerList const& PlayerList = me->GetMap()->GetPlayers();
                             if (!PlayerList.isEmpty())
                                 for (Map::PlayerList::const_iterator i = PlayerList.begin(); i != PlayerList.end(); ++i)
                                     if (Player* pPlayer = i->GetSource())
{
                                         if (!pPlayer->IsAlive() || pPlayer->IsGameMaster())
                                             continue;
                                         Position plrpos;
                                         float playerAngle = CenterPos.GetAngle(pPlayer);
                                         plrpos.m_positionX = CenterPos.GetPositionX() + cos(playerAngle) * 5.0f;
                                         plrpos.m_positionY = CenterPos.GetPositionY() + sin(playerAngle) * 5.0f;
                                         plrpos.m_positionZ = CenterPos.GetPositionZ() + 18.0f;
                                         plrpos.m_orientation = plrpos.GetAngle(&CenterPos);
                                         if (Creature* c = me->SummonCreature(NPC_VORTEX, plrpos, TEMPSUMMON_TIMED_DESPAWN, 15000))
{
                                             pPlayer->CastSpell(pPlayer, SPELL_FREEZE_ANIM, true);
                                             pPlayer->CastSpell(c, SPELL_VORTEX_CONTROL_VEHICLE, true);
                                             if (!pPlayer->GetVehicle()) // didn't work somehow, try again with a different way, if fails - break
{
                                                 pPlayer->EnterVehicle(c, 0);
                                                 if (!pPlayer->GetVehicle())
                                                     continue;
                                             }
                                             //pPlayer->ClearUnitState(UNIT_STATE_ONVEHICLE);
                                             Movement::MoveSplineInit init(pPlayer);
                                             init.MoveTo(CenterPos.GetPositionX(), CenterPos.GetPositionY(), CenterPos.GetPositionZ());
                                             init.SetFacing(pPlayer->GetOrientation());
                                             init.SetTransportExit();
                                             init.Launch();
                                             pPlayer->SetUnitMovementFlags(MOVEMENTFLAG_NONE);
                                             pPlayer->SetDisableGravity(true, true);
                                             sScriptMgr->AnticheatSetCanFlybyServer(pPlayer, true);
                                             WorldPacket data(SMSG_SPLINE_MOVE_UNROOT, 8);
                                             data << pPlayer->GetPackGUID();
                                             pPlayer->SendMessageToSet(&data, true);
                                             sScriptMgr->AnticheatSetUnderACKmount(pPlayer);
                                             sScriptMgr->AnticheatSetSkipOnePacketForASH(pPlayer, true);
                                             pPlayer->SetGuidValue(PLAYER_FARSIGHT, vp->GetGUID());
                                             c->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                                         }
                                     }
                         }
                         events.RescheduleEvent(EVENT_VORTEX_LAND_0, 11000, 1);
                         break;
                     }
                 case EVENT_VORTEX_LAND_0:
                     me->GetMotionMaster()->MoveLand(MI_POINT_VORTEX_LAND, CenterPos, 7.0f);
                     break;
                 case EVENT_VORTEX_LAND_1:
                     {
                         bLockHealthCheck = false;
                         EntryCheckPredicate pred(NPC_POWER_SPARK);
                         summons.DoAction(1, pred); // resume following
                         me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PACIFIED);
                         if (Unit* target = me->GetVictim())
{
                             AttackStart(target);
                             me->GetMotionMaster()->MoveChase(target);
                         }
                         events.RescheduleEvent(EVENT_START_VORTEX_0, 60000, 1);
                         break;
                     }
                 case EVENT_START_PHASE_2:
                     events.SetPhase(PHASE_TWO);
                     Talk(SAY_END_P1);
                     me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PACIFIED);
                     me->SendMeleeAttackStop();
                     me->SetTarget();
                     me->GetMotionMaster()->MoveIdle();
                     me->DisableSpline();
                     me->GetMotionMaster()->MovePoint(MI_POINT_CENTER_GROUND_PH_2, CenterPos);
                     events.CancelEventGroup(1); // don't cancel berserk (group 0)
                     break;
                 case EVENT_START_PHASE_2_FLY_UP:
                     {
                         me->SendMeleeAttackStop(me->GetVictim());
                         me->GetMotionMaster()->MoveIdle();
                         me->DisableSpline();
                         me->SetDisableGravity(true);
                         me->GetMotionMaster()->MoveTakeoff(MI_POINT_CENTER_AIR_PH_2, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ() + 32.0f, 7.0f);
                         events.RescheduleEvent(EVENT_START_PHASE_2_MOVE_TO_SIDE, 22500, 1);
                         break;
                     }
                 case EVENT_START_PHASE_2_MOVE_TO_SIDE:
                     Talk(SAY_PHASE_2);
                     me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_PACIFIED);
                     me->GetMotionMaster()->MovePoint(MI_POINT_CIRCLE_OUTSIDE_PH_2, Phase2NorthPos);
                     events.RescheduleEvent(EVENT_SPELL_ARCANE_STORM, urand(12000, 15000), 1);
                     events.RescheduleEvent(EVENT_SPELL_ARCANE_OVERLOAD, 8000, 1);
                     events.RescheduleEvent(EVENT_MOVE_TO_SURGE_OF_POWER, 55000, 1);
                     events.RescheduleEvent(EVENT_CHECK_TRASH_DEAD, 3000, 1);
                     for (int i = 0; i < MAX_NEXUS_LORDS; i++)
                     {
                         float dist = 22.0f;
                         float angle = M_PI / 2 + ((float)i / MAX_NEXUS_LORDS) * 2 * M_PI;
                         if (Creature* disk = me->SummonCreature(NPC_HOVER_DISK, CenterPos.GetPositionX() + cos(angle) * dist, CenterPos.GetPositionY() + sin(angle) * dist, CenterPos.GetPositionZ() + 30.0f, 0.0f, TEMPSUMMON_MANUAL_DESPAWN, 0))
                             if (Creature* c = me->SummonCreature(NPC_NEXUS_LORD, *disk, TEMPSUMMON_MANUAL_DESPAWN, 0))
{
                                 c->EnterVehicle(disk, 0);
                                 disk->AI()->DoAction(1); // start moving
                             }
                     }
                     for (int i = 0; i < MAX_SCIONS_OF_ETERNITY; i++)
                     {
                         float dist = 30.0f;
                         float angle = 0.0f + ((float)i / MAX_SCIONS_OF_ETERNITY) * 2 * M_PI;
                         if (Creature* disk = me->SummonCreature(NPC_HOVER_DISK, CenterPos.GetPositionX() + cos(angle) * dist, CenterPos.GetPositionY() + sin(angle) * dist, CenterPos.GetPositionZ() + 30.0f, 0.0f, TEMPSUMMON_MANUAL_DESPAWN, 0))
                             if (Creature* c = me->SummonCreature(NPC_SCION_OF_ETERNITY, *disk, TEMPSUMMON_MANUAL_DESPAWN, 0))
{
                                 c->EnterVehicle(disk, 0);
                                 disk->AI()->DoAction(1); // start moving
                             }
                     }
                     break;
                 case EVENT_SPELL_ARCANE_OVERLOAD:
                     {
                         me->GetMotionMaster()->MoveIdle();
                         me->StopMoving();
                         float dist = urand(5, 30);
                         float angle = rand_norm() * 2 * M_PI;
                         float posx = CenterPos.GetPositionX() + cos(angle) * dist;
                         float posy = CenterPos.GetPositionY() + sin(angle) * dist;
                         me->SetFacingTo(me->GetAngle(posx, posy));
                         me->CastSpell(posx, posy, CenterPos.GetPositionZ() + 1.5f, SPELL_ARCANE_OVERLOAD, true);
                         events.RepeatEvent(15000);
                         events.RescheduleEvent(EVENT_RESUME_FLYING_CIRCLES_PH_2, 3000, 1);
                     }
                     break;
                 case EVENT_RESUME_FLYING_CIRCLES_PH_2:
                     {
                         float angle = CenterPos.GetAngle(me);
                         float dist = Phase2NorthPos.GetExactDist2d(&CenterPos);
                         float newangle = angle + 0.5f;
                         if (newangle >= 2 * M_PI) newangle -= 2 * M_PI;
                         me->GetMotionMaster()->MovePoint(MI_POINT_CIRCLE_OUTSIDE_PH_2, CenterPos.GetPositionX() + cos(newangle)*dist, CenterPos.GetPositionY() + sin(newangle)*dist, Phase2NorthPos.GetPositionZ());
                     }
                     break;
                 case EVENT_MOVE_TO_SURGE_OF_POWER:
                     {
                         Talk(SAY_DEEP_BREATH);
                         float angle = CenterPos.GetAngle(me);
                         me->GetMotionMaster()->MoveIdle();
                         me->StopMoving();
                         me->GetMotionMaster()->MovePoint(MI_POINT_SURGE_OF_POWER_CENTER, CenterPos.GetPositionX() + cos(angle) * 10.0f, CenterPos.GetPositionY() + sin(angle) * 10.0f, Phase2NorthPos.GetPositionZ());
                         events.CancelEventGroup(1); // everything beside berserk
                     }
                     break;
                 case EVENT_SURGE_OF_POWER_WARNING:
                     Talk(EMOTE_SURGE_OF_POWER_WARNING_P2);
                     events.RescheduleEvent(EVENT_SPELL_SURGE_OF_POWER, 1500, 1);
                     break;
                 case EVENT_SPELL_SURGE_OF_POWER:
                     if (Creature* c = me->SummonCreature(NPC_SURGE_OF_POWER, CenterPos, TEMPSUMMON_TIMED_DESPAWN, 10000))
                         me->CastSpell(c, SPELL_SURGE_OF_POWER, false);
                     Talk(SAY_SURGE_OF_POWER);
                     events.RescheduleEvent(EVENT_CLEAR_TARGET, 10000, 1);
                     events.RescheduleEvent(EVENT_RESUME_FLYING_CIRCLES_PH_2, 10000, 1);
                     events.RescheduleEvent(EVENT_SPELL_ARCANE_STORM, urand(17000, 25000), 1);
                     events.RescheduleEvent(EVENT_SPELL_ARCANE_OVERLOAD, 16000, 1);
                     events.RescheduleEvent(EVENT_MOVE_TO_SURGE_OF_POWER, 55000 + 10000, 1);
                     events.RescheduleEvent(EVENT_CHECK_TRASH_DEAD, 3000, 1);
                     break;
                 case EVENT_CLEAR_TARGET:
                     me->SendMeleeAttackStop();
                     me->SetTarget();
                     break;
                 case EVENT_CHECK_TRASH_DEAD:
                     {
                         if (me->FindNearestCreature(NPC_SCION_OF_ETERNITY, 250.0f, true) || me->FindNearestCreature(NPC_NEXUS_LORD, 250.0f, true))
                             events.RepeatEvent(3000);
                         else
{
                             me->SendMeleeAttackStop();
                             me->SetTarget();
                             events.CancelEventGroup(1);
                             summons.DespawnAll();
                             // start phase 3
                             Talk(SAY_END_P2);
                             me->GetMotionMaster()->Clear();
                             me->GetMotionMaster()->MoveIdle();
                             me->StopMoving();
                             me->GetMotionMaster()->MovePoint(MI_POINT_START_PH_3, CenterPos.GetPositionX(), CenterPos.GetPositionY(), CenterPos.GetPositionZ() + 70.0f);
                             events.RescheduleEvent(EVENT_LIGHT_DIMENSION_CHANGE, 1000, 1);
                             events.RescheduleEvent(EVENT_DESTROY_PLATFORM_0, 10000, 1);
                         }
                     }
                     break;
                 case EVENT_LIGHT_DIMENSION_CHANGE:
                     me->GetMap()->SetZoneOverrideLight(AREA_EYE_OF_ETERNITY, LIGHT_CHANGE_DIMENSIONS, 2s);
                     break;
                 case EVENT_DESTROY_PLATFORM_0:
                     if (Creature* c = me->SummonCreature(NPC_WORLD_TRIGGER_LAOI, CenterPos, TEMPSUMMON_TIMED_DESPAWN, 3000))
                     {
                         c->SetFaction(me->GetFaction());
                         c->CastSpell(c, SPELL_DESTROY_PLATFORM_VISUAL, true);
                         c->CastSpell(c, SPELL_DESTROY_PLATFORM_EFFECT, false);
                     }
                     me->GetMap()->SetZoneOverrideLight(AREA_EYE_OF_ETERNITY, LIGHT_OBSCURE_SPACE, 1s);
                     events.RescheduleEvent(EVENT_MOVE_TO_PHASE_3_POSITION, 2000, 1);
                     break;
                 case EVENT_MOVE_TO_PHASE_3_POSITION:
                     {
                         me->SendMeleeAttackStop(me->GetVictim());
                         me->GetMotionMaster()->MoveTakeoff(MI_POINT_PH_3_FIGHT_POSITION, CenterPos.GetPositionX(), CenterPos.GetPositionY(), CenterPos.GetPositionZ() - 5.0f, me->GetSpeed(MOVE_RUN));
                         me->DeleteThreatList(); // players on vehicle are unattackable -> leads to EnterEvadeMode() because target is not acceptable!
                         // mount players:
                         Map::PlayerList const& PlayerList = me->GetMap()->GetPlayers();
                         if (!PlayerList.isEmpty())
                             for (Map::PlayerList::const_iterator i = PlayerList.begin(); i != PlayerList.end(); ++i)
                                 if (Player* pPlayer = i->GetSource())
{
                                     sScriptMgr->AnticheatSetUnderACKmount(pPlayer);
                                     sScriptMgr->AnticheatSetSkipOnePacketForASH(pPlayer, true);
                                     if (!pPlayer->IsAlive() || pPlayer->IsGameMaster())
                                         continue;
                                     if (Creature* c = me->SummonCreature(NPC_WYRMREST_SKYTALON, pPlayer->GetPositionX(), pPlayer->GetPositionY(), pPlayer->GetPositionZ() - 20.0f, 0.0f, TEMPSUMMON_MANUAL_DESPAWN, 0))
{
                                         c->SetFaction(pPlayer->GetFaction());
                                         //pPlayer->CastCustomSpell(60683, SPELLVALUE_BASE_POINT0, 1, c, true);
                                         c->m_Events.AddEvent(new EoEDrakeEnterVehicleEvent(*c, pPlayer->GetGUID()), c->m_Events.CalculateTime(500));
                                         AttackStart(c);
                                     }
                                 }
                         events.RescheduleEvent(EVENT_SAY_PHASE_3_INTRO, 3000, 1);
                     }
                     break;
                 case EVENT_SAY_PHASE_3_INTRO:
                     Talk(SAY_INTRO_PHASE_3);
                     break;
                 case EVENT_START_PHASE_3:
                     events.SetPhase(PHASE_THREE);
                     me->GetMap()->SetZoneOverrideLight(AREA_EYE_OF_ETERNITY, LIGHT_OBSCURE_ARCANE_RUNES, 1s);
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                     me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PACIFIED | UNIT_FLAG_DISABLE_MOVE);
                     if (Unit* target = me->GetVictim())
                         AttackStart(target);
                     events.RescheduleEvent(EVENT_SPELL_ARCANE_PULSE, 0, 1);
                     events.RescheduleEvent(EVENT_SPELL_STATIC_FIELD, urand(1000, 4000), 1);
                     events.RescheduleEvent(EVENT_SPELL_PH3_SURGE_OF_POWER, urand(4000, 7000), 1);
                     events.RescheduleEvent(EVENT_SPELL_ARCANE_STORM, urand(12000, 15000), 1);
                     break;
                 case EVENT_SPELL_ARCANE_PULSE:
                     me->CastSpell(me, SPELL_ARCANE_PULSE, true);
                     events.RepeatEvent(3000);
                     break;
                 case EVENT_SPELL_STATIC_FIELD:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 200.0f, false))
                     {
                         me->SetFacingToObject(target);
                         me->CastSpell(target, SPELL_STATIC_FIELD_MAIN, true);
                     }
                     events.RepeatEvent(12000);
                     break;
                 case EVENT_SPELL_PH3_SURGE_OF_POWER:
                     me->CastSpell((Unit*)nullptr, SPELL_PH3_SURGE_OF_POWER, false);
                     events.RepeatEvent(7000);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References ACHIEV_YOU_DONT_HAVE_AN_ENTERNITY_EVENT, ACHIEVEMENT_TIMED_TYPE_EVENT, AREA_EYE_OF_ETERNITY, AttackStart(), MapRefMgr::begin(), bLockHealthCheck, Unit::CastCustomSpell(), Unit::CastSpell(), CenterPos, MotionMaster::Clear(), DATA_HIDE_IRIS_AND_PORTAL, DATA_SET_IRIS_INACTIVE, Unit::DeleteThreatList(), SummonList::DespawnAll(), Unit::DisableSpline(), SummonList::DoAction(), UnitAI::DoMeleeAttackIfReady(), InstanceScript::DoStartTimedAchievement(), ScriptedAI::DUNGEON_MODE(), EMOTE_BERSERK, EMOTE_POWER_SPARK, EMOTE_STATE_CUSTOM_SPELL_01, EMOTE_SURGE_OF_POWER_WARNING_P2, MapRefMgr::end(), EVENT_BERSERK, EVENT_CHECK_TRASH_DEAD, EVENT_CLEAR_TARGET, EVENT_DESTROY_PLATFORM_0, EVENT_INTRO_LAND, EVENT_INTRO_MOVE_CENTER, EVENT_LIGHT_DIMENSION_CHANGE, EVENT_MOVE_TO_PHASE_3_POSITION, EVENT_MOVE_TO_SURGE_OF_POWER, EVENT_RESUME_FLYING_CIRCLES_PH_2, EVENT_SAY_PHASE_3_INTRO, EVENT_SPELL_ARCANE_BREATH, EVENT_SPELL_ARCANE_OVERLOAD, EVENT_SPELL_ARCANE_PULSE, EVENT_SPELL_ARCANE_STORM, EVENT_SPELL_PH3_SURGE_OF_POWER, EVENT_SPELL_STATIC_FIELD, EVENT_SPELL_SURGE_OF_POWER, EVENT_START_FIGHT, EVENT_START_PHASE_2, EVENT_START_PHASE_2_FLY_UP, EVENT_START_PHASE_2_MOVE_TO_SIDE, EVENT_START_PHASE_3, EVENT_START_VORTEX_0, EVENT_START_VORTEX_REAL, EVENT_SUMMON_POWER_SPARK, EVENT_SURGE_OF_POWER_WARNING, EVENT_VORTEX_FLY_TO_CENTER, EVENT_VORTEX_LAND_0, EVENT_VORTEX_LAND_1, WorldObject::FindNearestCreature(), FourSidesPos, Position::GetAngle(), Position::GetExactDist2d(), Unit::GetFaction(), WorldObject::GetMap(), Unit::GetMotionMaster(), Position::GetOrientation(), Map::GetPlayers(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetSpeed(), Unit::GetVictim(), Unit::HandleEmoteCommand(), HandleIntroSpeech(), Unit::HasUnitState(), Unit::InterruptNonMeleeSpells(), LinkedListHead::isEmpty(), Movement::MoveSplineInit::Launch(), LIGHT_CHANGE_DIMENSIONS, LIGHT_OBSCURE_ARCANE_RUNES, LIGHT_OBSCURE_SPACE, Position::m_orientation, Position::m_positionX, Position::m_positionY, Position::m_positionZ, MAX_NEXUS_LORDS, MAX_SCIONS_OF_ETERNITY, ScriptedAI::me, MI_POINT_CENTER_AIR_PH_2, MI_POINT_CENTER_GROUND_PH_2, MI_POINT_CIRCLE_OUTSIDE_PH_2, MI_POINT_INTRO_CENTER_AIR, MI_POINT_INTRO_LAND, MI_POINT_PH_3_FIGHT_POSITION, MI_POINT_START_PH_3, MI_POINT_SURGE_OF_POWER_CENTER, MI_POINT_VORTEX_CENTER, MI_POINT_VORTEX_LAND, MI_POINT_VORTEX_TAKEOFF, MOVE_RUN, MotionMaster::MoveChase(), MotionMaster::MoveIdle(), MotionMaster::MoveLand(), MOVEMENTFLAG_NONE, MOVEMENTFLAG_WALKING, MotionMaster::MovePoint(), MotionMaster::MoveTakeoff(), Movement::MoveSplineInit::MoveTo(), NPC_HOVER_DISK, NPC_NEXUS_LORD, NPC_PORTAL, NPC_POWER_SPARK, NPC_SCION_OF_ETERNITY, NPC_SURGE_OF_POWER, NPC_VORTEX, NPC_WORLD_TRIGGER_LAOI, NPC_WYRMREST_SKYTALON, Phase2NorthPos, PHASE_ONE, PHASE_THREE, PHASE_TWO, pInstance, PLAYER_FARSIGHT, rand_norm(), Unit::RemoveAllAuras(), Object::RemoveFlag(), Unit::RemoveUnitMovementFlag(), SAY_DEEP_BREATH, SAY_END_P1, SAY_END_P2, SAY_INTRO_PHASE_3, SAY_MAGIC_BLAST, SAY_PHASE_2, SAY_SURGE_OF_POWER, SELECT_TARGET_RANDOM, Creature::SelectNearestTarget(), UnitAI::SelectTarget(), Unit::SendMeleeAttackStop(), ZoneScript::SetData(), Creature::SetDisableGravity(), Movement::MoveSplineInit::SetFacing(), Unit::SetFacingTo(), Unit::SetFacingToObject(), Object::SetFlag(), Creature::SetTarget(), Movement::MoveSplineInit::SetTransportExit(), Object::SetUInt32Value(), Map::SetZoneOverrideLight(), SMSG_SPLINE_MOVE_UNROOT, SPELL_ARCANE_BREATH, SPELL_ARCANE_OVERLOAD, SPELL_ARCANE_PULSE, SPELL_ARCANE_STORM, SPELL_BERSERK, SPELL_DESTROY_PLATFORM_EFFECT, SPELL_DESTROY_PLATFORM_VISUAL, SPELL_FREEZE_ANIM, SPELL_PH3_SURGE_OF_POWER, SPELL_PORTAL_BEAM, SPELL_STATIC_FIELD_MAIN, SPELL_SURGE_OF_POWER, SPELL_VORTEX_CONTROL_VEHICLE, SPELLVALUE_MAX_TARGETS, sScriptMgr, Unit::StopMoving(), WorldObject::SummonCreature(), summons, CreatureAI::Talk(), TEMPSUMMON_MANUAL_DESPAWN, TEMPSUMMON_TIMED_DESPAWN, UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, UNIT_FLAG_PACIFIED, UNIT_NPC_EMOTESTATE, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
bLockHealthCheck
bool boss_malygos::boss_malygosAI::bLockHealthCheck
Definition at line 220 of file boss_malygos.cpp.
Referenced by DamageTaken(), Reset(), SpellHit(), and UpdateAI().
events
EventMap boss_malygos::boss_malygosAI::events
Definition at line 215 of file boss_malygos.cpp.
IntroCounter
uint8 boss_malygos::boss_malygosAI::IntroCounter
Definition at line 219 of file boss_malygos.cpp.
Referenced by HandleIntroSpeech(), and Reset().
pInstance
InstanceScript* boss_malygos::boss_malygosAI::pInstance
Definition at line 214 of file boss_malygos.cpp.
Referenced by boss_malygosAI(), EnterCombat(), JustDied(), Reset(), and UpdateAI().
summons
SummonList boss_malygos::boss_malygosAI::summons
Definition at line 216 of file boss_malygos.cpp.
Referenced by JustSummoned(), Reset(), and UpdateAI().
timer1
uint32 boss_malygos::boss_malygosAI::timer1
Definition at line 218 of file boss_malygos.cpp.
Referenced by HandleIntroSpeech(), and Reset().
timer2
uint32 boss_malygos::boss_malygosAI::timer2
Definition at line 218 of file boss_malygos.cpp.
Referenced by HandleIntroSpeech(), MovementInform(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Nexus/EyeOfEternity/boss_malygos.cpp