Azerotcore-wotlk: boss_yoggsaron_llane::boss_yoggsaron_llaneAI Struct Reference
boss_yoggsaron_llane::boss_yoggsaron_llaneAI Struct Reference
Public Member Functions
boss_yoggsaron_llaneAI (Creature *c)
void Reset () override
void NextStep (const uint32 time)
void Say (std::string text, ObjectGuid guid, bool yell, uint32 soundId)
void PlaySound (uint32 soundId)
void UpdateAI (uint32 diff) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
bool _running
int32 _checkTimer
uint8 _step
ObjectGuid _garonaGUID
ObjectGuid _yoggGUID
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 2003 of file boss_yoggsaron.cpp.
Constructor & Destructor Documentation
boss_yoggsaron_llaneAI()
boss_yoggsaron_llane::boss_yoggsaron_llaneAI::boss_yoggsaron_llaneAI (Creature * c) inline
Definition at line 2005 of file boss_yoggsaron.cpp.
 : NullCreatureAI(c) { }
Member Function Documentation
NextStep()
void boss_yoggsaron_llane::boss_yoggsaron_llaneAI::NextStep (const uint32 time) inline
Definition at line 2023 of file boss_yoggsaron.cpp.
         {
             _step++;
             _checkTimer = time;
         }
References _checkTimer, and _step.
Referenced by UpdateAI().
PlaySound()
void boss_yoggsaron_llane::boss_yoggsaron_llaneAI::PlaySound (uint32 soundId) inline
Definition at line 2052 of file boss_yoggsaron.cpp.
         {
             WorldPacket data(SMSG_PLAY_SOUND, 4);
             data << uint32(soundId);
             me->SendMessageToSetInRange(&data, 90, false);
         }
References CreatureAI::me, WorldObject::SendMessageToSetInRange(), and SMSG_PLAY_SOUND.
Referenced by Say(), and UpdateAI().
Reset()
void boss_yoggsaron_llane::boss_yoggsaron_llaneAI::Reset () inline override virtual
Reimplemented from UnitAI.
Definition at line 2013 of file boss_yoggsaron.cpp.
         {
             _running = true;
             _checkTimer = 0;
             _step = 0;
             _garonaGUID.Clear();
             if (me->GetInstanceScript())
                 _yoggGUID = me->GetInstanceScript()->GetGuidData(TYPE_YOGGSARON);
         }
References _checkTimer, _garonaGUID, _running, _step, _yoggGUID, ObjectGuid::Clear(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), CreatureAI::me, and TYPE_YOGGSARON.
Say()
void boss_yoggsaron_llane::boss_yoggsaron_llaneAI::Say (std::string text, ObjectGuid guid, bool yell, uint32 soundId) inline
Definition at line 2029 of file boss_yoggsaron.cpp.
         {
             Creature* creature = guid ? ObjectAccessor::GetCreature(*me, guid) : me;
             if (!creature)
                 return;
             WorldPacket data;
             if (creature->GetGUID() != _yoggGUID)
             {
                 ChatHandler::BuildChatPacket(data, yell ? CHAT_MSG_MONSTER_YELL : CHAT_MSG_MONSTER_SAY, LANG_UNIVERSAL, creature, nullptr, text);
                 creature->SendMessageToSetInRange(&data, 90, true);
             }
             else if (Creature* cr = me->SummonTrigger(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ() - 5, 0, 5000))
             {
                 ChatHandler::BuildChatPacket(data, yell ? CHAT_MSG_MONSTER_YELL : CHAT_MSG_MONSTER_SAY, LANG_UNIVERSAL, creature, nullptr, text);
                 cr->SendMessageToSetInRange(&data, 90, true);
             }
             else
                 return;
             PlaySound(soundId);
         }
References _yoggGUID, ChatHandler::BuildChatPacket(), CHAT_MSG_MONSTER_SAY, CHAT_MSG_MONSTER_YELL, ObjectAccessor::GetCreature(), Object::GetGUID(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), LANG_UNIVERSAL, CreatureAI::me, PlaySound(), WorldObject::SendMessageToSetInRange(), and WorldObject::SummonTrigger().
Referenced by UpdateAI().
UpdateAI()
void boss_yoggsaron_llane::boss_yoggsaron_llaneAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 2059 of file boss_yoggsaron.cpp.
         {
             if (!_running)
                 return;
             if (_checkTimer != 0)
             {
                 _checkTimer -= diff;
                 if (_checkTimer < 0 )
                     _checkTimer = 0;
             }
             else
                 switch (_step)
                 {
                     case 0:
                         NextStep(5000);
                         break;
                     case 1:
                         if (Creature* cr = me->FindNearestCreature(NPC_GARONA, 50))
                             _garonaGUID = cr->GetGUID();
                         Say("Bad news sire. The clans are united under Blackhand in this assault. They will stand together until Stormwind has fallen.", _garonaGUID, false, GAR_1);
                         NextStep(2000);
                         break;
                     case 2:
                         PlaySound(GAR_2);
                         NextStep(6500);
                         break;
                     case 3:
                         Say("Gul'dan is bringing up his warlocks by nightfall. Until then, the Blackrock clan will be trying to take the Eastern Wall.", _garonaGUID, false, GAR_3);
                         NextStep(11000);
                         break;
                     case 4:
                         Say("A thousand deaths... or one murder.", _yoggGUID, false, YS_V1_1);
                         NextStep(2500);
                         break;
                     case 5:
                         PlaySound(YS_V1_2);
                         NextStep(2500);
                         break;
                     case 6:
                         Say("We will hold until the reinforcements come. As long as men with stout hearts are manning the walls and throne Stormwind will hold.", ObjectGuid::Empty, false, LL_1);
                         NextStep(10000);
                         break;
                     case 7:
                         Say("The orc leaders agree with your assessment.", _garonaGUID, false, GAR_4);
                         NextStep(5000);
                         break;
                     case 8:
                         Say("Your petty quarrels only make me stronger!", _yoggGUID, false, YS_V1_3);
                         _running = false;
                         break;
                 }
         }
References _checkTimer, _garonaGUID, _running, _step, _yoggGUID, ObjectGuid::Empty, WorldObject::FindNearestCreature(), GAR_1, GAR_2, GAR_3, GAR_4, LL_1, CreatureAI::me, NextStep(), NPC_GARONA, PlaySound(), Say(), YS_V1_1, YS_V1_2, and YS_V1_3.
Member Data Documentation
_checkTimer
int32 boss_yoggsaron_llane::boss_yoggsaron_llaneAI::_checkTimer
Definition at line 2008 of file boss_yoggsaron.cpp.
Referenced by NextStep(), Reset(), and UpdateAI().
_garonaGUID
ObjectGuid boss_yoggsaron_llane::boss_yoggsaron_llaneAI::_garonaGUID
Definition at line 2010 of file boss_yoggsaron.cpp.
Referenced by Reset(), and UpdateAI().
_running
bool boss_yoggsaron_llane::boss_yoggsaron_llaneAI::_running
Definition at line 2007 of file boss_yoggsaron.cpp.
Referenced by Reset(), and UpdateAI().
_step
uint8 boss_yoggsaron_llane::boss_yoggsaron_llaneAI::_step
Definition at line 2009 of file boss_yoggsaron.cpp.
Referenced by NextStep(), Reset(), and UpdateAI().
_yoggGUID
ObjectGuid boss_yoggsaron_llane::boss_yoggsaron_llaneAI::_yoggGUID
Definition at line 2011 of file boss_yoggsaron.cpp.
Referenced by Reset(), Say(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_yoggsaron.cpp