Azerotcore-wotlk: Acore::WorldObjectLastSearcher< Check > Struct Template Reference
Acore::WorldObjectLastSearcher< Check > Struct Template Reference
#include <GridNotifiers.h>
Public Member Functions
WorldObjectLastSearcher (WorldObject const *searcher, WorldObject *&result, Check &check, uint32 mapTypeMask=GRID_MAP_TYPE_MASK_ALL)
void Visit (GameObjectMapType &m)
void Visit (PlayerMapType &m)
void Visit (CreatureMapType &m)
void Visit (CorpseMapType &m)
void Visit (DynamicObjectMapType &m)
template<class NOT_INTERESTED >
void Visit (GridRefMgr< NOT_INTERESTED > &)
Public Attributes
uint32 i_mapTypeMask
uint32 i_phaseMask
WorldObject *& i_object
Check & i_check
Detailed Description
template<class Check>
struct Acore::WorldObjectLastSearcher< Check >
Definition at line 189 of file GridNotifiers.h.
Constructor & Destructor Documentation
WorldObjectLastSearcher()
template<class Check > Acore::WorldObjectLastSearcher< Check >::WorldObjectLastSearcher (WorldObject const * searcher, WorldObject *& result, Check & check, uint32 mapTypeMask = GRID_MAP_TYPE_MASK_ALL) inline
Definition at line 196 of file GridNotifiers.h.
             :  i_mapTypeMask(mapTypeMask), i_phaseMask(searcher->GetPhaseMask()), i_object(result), i_check(check) {}
Member Function Documentation
Visit() [1/6]
template<class Check > void Acore::WorldObjectLastSearcher< Check >::Visit (CorpseMapType & m)
Definition at line 215 of file GridNotifiersImpl.h.
 {
     if (!(i_mapTypeMask & GRID_MAP_TYPE_MASK_CORPSE))
         return;
     for (CorpseMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
     {
         if (!itr->GetSource()->InSamePhase(i_phaseMask))
             continue;
         if (i_check(itr->GetSource()))
             i_object = itr->GetSource();
     }
 }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), and GRID_MAP_TYPE_MASK_CORPSE.
Visit() [2/6]
template<class Check > void Acore::WorldObjectLastSearcher< Check >::Visit (CreatureMapType & m)
Definition at line 199 of file GridNotifiersImpl.h.
 {
     if (!(i_mapTypeMask & GRID_MAP_TYPE_MASK_CREATURE))
         return;
     for (CreatureMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
     {
         if (!itr->GetSource()->InSamePhase(i_phaseMask))
             continue;
         if (i_check(itr->GetSource()))
             i_object = itr->GetSource();
     }
 }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), and GRID_MAP_TYPE_MASK_CREATURE.
Visit() [3/6]
template<class Check > void Acore::WorldObjectLastSearcher< Check >::Visit (DynamicObjectMapType & m)
Definition at line 231 of file GridNotifiersImpl.h.
 {
     if (!(i_mapTypeMask & GRID_MAP_TYPE_MASK_DYNAMICOBJECT))
         return;
     for (DynamicObjectMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
     {
         if (!itr->GetSource()->InSamePhase(i_phaseMask))
             continue;
         if (i_check(itr->GetSource()))
             i_object = itr->GetSource();
     }
 }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), and GRID_MAP_TYPE_MASK_DYNAMICOBJECT.
Visit() [4/6]
template<class Check > void Acore::WorldObjectLastSearcher< Check >::Visit (GameObjectMapType & m)
Definition at line 167 of file GridNotifiersImpl.h.
 {
     if (!(i_mapTypeMask & GRID_MAP_TYPE_MASK_GAMEOBJECT))
         return;
     for (GameObjectMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
     {
         if (!itr->GetSource()->InSamePhase(i_phaseMask))
             continue;
         if (i_check(itr->GetSource()))
             i_object = itr->GetSource();
     }
 }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), and GRID_MAP_TYPE_MASK_GAMEOBJECT.
Visit() [5/6]
template<class Check > template<class NOT_INTERESTED > void Acore::WorldObjectLastSearcher< Check >::Visit (GridRefMgr< NOT_INTERESTED > &) inline
Definition at line 205 of file GridNotifiers.h.
 {}
Visit() [6/6]
template<class Check > void Acore::WorldObjectLastSearcher< Check >::Visit (PlayerMapType & m)
Definition at line 183 of file GridNotifiersImpl.h.
 {
     if (!(i_mapTypeMask & GRID_MAP_TYPE_MASK_PLAYER))
         return;
     for (PlayerMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
     {
         if (!itr->GetSource()->InSamePhase(i_phaseMask))
             continue;
         if (i_check(itr->GetSource()))
             i_object = itr->GetSource();
     }
 }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), and GRID_MAP_TYPE_MASK_PLAYER.
Member Data Documentation
i_check
template<class Check > Check& Acore::WorldObjectLastSearcher< Check >::i_check
Definition at line 194 of file GridNotifiers.h.
i_mapTypeMask
template<class Check > uint32 Acore::WorldObjectLastSearcher< Check >::i_mapTypeMask
Definition at line 191 of file GridNotifiers.h.
i_object
template<class Check > WorldObject*& Acore::WorldObjectLastSearcher< Check >::i_object
Definition at line 193 of file GridNotifiers.h.
i_phaseMask
template<class Check > uint32 Acore::WorldObjectLastSearcher< Check >::i_phaseMask
Definition at line 192 of file GridNotifiers.h.
The documentation for this struct was generated from the following files:
src/server/game/Grids/Notifiers/GridNotifiers.h
src/server/game/Grids/Notifiers/GridNotifiersImpl.h