Azerotcore-wotlk: spell_igb_on_gunship_deck::spell_igb_on_gunship_deck_AuraScript Class Reference
spell_igb_on_gunship_deck::spell_igb_on_gunship_deck_AuraScript Class Reference
Private Member Functions
PrepareAuraScript (spell_igb_on_gunship_deck_AuraScript)
bool Load () override
bool CheckAreaTarget (Unit *unit)
void HandleApply (AuraEffect const *, AuraEffectHandleModes)
void Register () override
Private Attributes
TeamId _teamIdInInstance
Additional Inherited Members
Public Member Functions inherited from AuraScript
AuraScript ()
bool _Validate (SpellInfo const *entry) override
bool _Load (Aura *aura)
void _PrepareScriptCall (AuraScriptHookType hookType, AuraApplication const *aurApp=nullptr)
void _FinishScriptCall ()
bool _IsDefaultActionPrevented ()
void PreventDefaultAction ()
SpellInfo const * GetSpellInfo () const
uint32 GetId () const
ObjectGuid GetCasterGUID () const
Unit * GetCaster () const
WorldObject * GetOwner () const
Unit * GetUnitOwner () const
DynamicObject * GetDynobjOwner () const
void Remove (uint32 removeMode=0)
Aura * GetAura () const
AuraObjectType GetType () const
int32 GetDuration () const
void SetDuration (int32 duration, bool withMods=false)
void RefreshDuration ()
time_t GetApplyTime () const
int32 GetMaxDuration () const
void SetMaxDuration (int32 duration)
int32 CalcMaxDuration () const
bool IsExpired () const
bool IsPermanent () const
uint8 GetCharges () const
void SetCharges (uint8 charges)
uint8 CalcMaxCharges () const
bool ModCharges (int8 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool DropCharge (AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
uint8 GetStackAmount () const
void SetStackAmount (uint8 num)
bool ModStackAmount (int32 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool IsPassive () const
bool IsDeathPersistent () const
bool HasEffect (uint8 effIndex) const
AuraEffect * GetEffect (uint8 effIndex) const
bool HasEffectType (AuraType type) const
Unit * GetTarget () const
AuraApplication const * GetTargetApplication () const
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual bool Validate (SpellInfo const *)
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from AuraScript
HookList< CheckAreaTargetHandler > DoCheckAreaTarget
HookList< AuraDispelHandler > OnDispel
HookList< AuraDispelHandler > AfterDispel
HookList< EffectApplyHandler > OnEffectApply
HookList< EffectApplyHandler > AfterEffectApply
HookList< EffectApplyHandler > OnEffectRemove
HookList< EffectApplyHandler > AfterEffectRemove
HookList< EffectPeriodicHandler > OnEffectPeriodic
HookList< EffectUpdatePeriodicHandler > OnEffectUpdatePeriodic
HookList< EffectCalcAmountHandler > DoEffectCalcAmount
HookList< EffectCalcPeriodicHandler > DoEffectCalcPeriodic
HookList< EffectCalcSpellModHandler > DoEffectCalcSpellMod
HookList< EffectAbsorbHandler > OnEffectAbsorb
HookList< EffectAbsorbHandler > AfterEffectAbsorb
HookList< EffectManaShieldHandler > OnEffectManaShield
HookList< EffectManaShieldHandler > AfterEffectManaShield
HookList< EffectSplitHandler > OnEffectSplit
HookList< CheckProcHandler > DoCheckProc
HookList< AuraProcHandler > DoPrepareProc
HookList< AuraProcHandler > OnProc
HookList< AuraProcHandler > AfterProc
HookList< EffectProcHandler > OnEffectProc
HookList< EffectProcHandler > AfterEffectProc
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Definition at line 2669 of file boss_icecrown_gunship_battle.cpp.
Member Function Documentation
CheckAreaTarget()
bool spell_igb_on_gunship_deck::spell_igb_on_gunship_deck_AuraScript::CheckAreaTarget (Unit * unit) inline private
Definition at line 2682 of file boss_icecrown_gunship_battle.cpp.
         {
             return unit->GetTypeId() == TYPEID_PLAYER;
         }
References Object::GetTypeId(), and TYPEID_PLAYER.
Referenced by Register().
HandleApply()
void spell_igb_on_gunship_deck::spell_igb_on_gunship_deck_AuraScript::HandleApply (AuraEffect const * , AuraEffectHandleModes) inline private
Definition at line 2687 of file boss_icecrown_gunship_battle.cpp.
         {
             bool enemy = GetSpellInfo()->Id == uint32(_teamIdInInstance == TEAM_HORDE ? SPELL_ON_SKYBREAKER_DECK : SPELL_ON_ORGRIMS_HAMMER_DECK);
             if (Creature* gunship = GetOwner()->FindNearestCreature(_teamIdInInstance == TEAM_HORDE ? NPC_ORGRIMS_HAMMER : NPC_THE_SKYBREAKER, 200.0f))
                 gunship->AI()->SetGUID(GetTarget()->GetGUID(), enemy ? ACTION_SHIP_VISITS_ENEMY : ACTION_SHIP_VISITS_SELF);
         }
References _teamIdInInstance, ACTION_SHIP_VISITS_ENEMY, ACTION_SHIP_VISITS_SELF, AuraScript::GetOwner(), AuraScript::GetSpellInfo(), AuraScript::GetTarget(), SpellInfo::Id, NPC_ORGRIMS_HAMMER, NPC_THE_SKYBREAKER, SPELL_ON_ORGRIMS_HAMMER_DECK, SPELL_ON_SKYBREAKER_DECK, and TEAM_HORDE.
Referenced by Register().
Load()
bool spell_igb_on_gunship_deck::spell_igb_on_gunship_deck_AuraScript::Load () inline override private virtual
Reimplemented from _SpellScript.
Definition at line 2673 of file boss_icecrown_gunship_battle.cpp.
         {
             if (InstanceScript* instance = GetOwner()->GetInstanceScript())
                 _teamIdInInstance = TeamId(instance->GetData(DATA_TEAMID_IN_INSTANCE));
             else
                 _teamIdInInstance = TEAM_ALLIANCE;
             return true;
         }
References _teamIdInInstance, DATA_TEAMID_IN_INSTANCE, AuraScript::GetOwner(), and TEAM_ALLIANCE.
PrepareAuraScript()
spell_igb_on_gunship_deck::spell_igb_on_gunship_deck_AuraScript::PrepareAuraScript (spell_igb_on_gunship_deck_AuraScript) private
Register()
void spell_igb_on_gunship_deck::spell_igb_on_gunship_deck_AuraScript::Register () inline override private virtual
Implements _SpellScript.
Definition at line 2694 of file boss_icecrown_gunship_battle.cpp.
         {
             DoCheckAreaTarget += AuraCheckAreaTargetFn(spell_igb_on_gunship_deck_AuraScript::CheckAreaTarget);
             AfterEffectApply += AuraEffectApplyFn(spell_igb_on_gunship_deck_AuraScript::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
         }
References AuraScript::AfterEffectApply, AURA_EFFECT_HANDLE_REAL, AuraCheckAreaTargetFn, AuraEffectApplyFn, CheckAreaTarget(), AuraScript::DoCheckAreaTarget, EFFECT_0, HandleApply(), and SPELL_AURA_DUMMY.
Member Data Documentation
_teamIdInInstance
TeamId spell_igb_on_gunship_deck::spell_igb_on_gunship_deck_AuraScript::_teamIdInInstance private
Definition at line 2700 of file boss_icecrown_gunship_battle.cpp.
Referenced by HandleApply(), and Load().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp