Azerotcore-wotlk: src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/instance_blackrock_spire.cpp File Reference
instance_blackrock_spire.cpp File Reference
#include "blackrock_spire.h"
#include "Cell.h"
#include "CellImpl.h"
#include "GridNotifiers.h"
#include "GridNotifiersImpl.h"
#include "InstanceScript.h"
#include "ObjectDefines.h"
#include "ObjectMgr.h"
#include "ScriptedCreature.h"
#include "ScriptMgr.h"
Classes
class instance_blackrock_spire
struct instance_blackrock_spire::instance_blackrock_spireMapScript
class at_dragonspire_hall
class at_blackrock_stadium
class go_father_flame
Enumerations
enum EventIds {
EVENT_DARGONSPIRE_ROOM_STORE = 1 , EVENT_DARGONSPIRE_ROOM_CHECK = 2 , EVENT_SOLAKAR_WAVE = 3 , EVENT_AWAKEN_WARD_1 = 22900 ,
EVENT_AWAKEN_WARD_2 = 22907 , EVENT_AWAKEN_WARD_3 = 22908 , EVENT_AWAKEN_WARD_4 = 22909 , EVENT_PLAYERS_GUNSHIP_SPAWN = 22663 ,
EVENT_PLAYERS_GUNSHIP_COMBAT = 22664 , EVENT_PLAYERS_GUNSHIP_SAURFANG = 22665 , EVENT_ENEMY_GUNSHIP_COMBAT = 22860 , EVENT_ENEMY_GUNSHIP_DESPAWN = 22861 ,
EVENT_QUAKE = 23437 , EVENT_SECOND_REMORSELESS_WINTER = 23507 , EVENT_TELEPORT_TO_FROSMOURNE = 23617 , EVENT_FESTERGUT_VALVE_USED = 23438 ,
EVENT_ROTFACE_VALVE_USED = 23426
}
enum Timers {
TIMER_TOMBOFTHESEVEN = 30000 , TIMER_TOMB_START = 1000 , TIMER_TOMB_RESET = 15000 , TIMER_SOLAKAR_WAVE = 30000 ,
TIMER_ARCANE_MIN = 8000 , TIMER_ARCANE_MAX = 14000 , TIMER_CURSE_MIN = 20000 , TIMER_CURSE_MAX = 30000 ,
TIMER_SHIELD_MIN = 30000 , TIMER_SHIELD_MAX = 40000 , TIMER_PORTAL = 25000
}
enum SolakarWaves { MAX_WAVE_COUNT = 5 }
enum Texts {
SAY_NEFARIUS_REND_WIPE = 11 , SAY_SOLAKAR_FIRST_HATCHER = 0 , EMOTE_MASS_ERRUPTION = 0 , EMOTE_LOWHP = 0 ,
EMOTE_FRENZY = 0 , SAY_AGGRO = 0 , SAY_SPAWN = 1 , SAY_SLAY = 2 ,
SAY_DEFEAT = 3 , SAY_SUMMON_MAJ = 4 , SAY_ARRIVAL2_MAJ = 5 , SAY_LAST_ADD = 6 ,
SAY_DEFEAT_2 = 7 , SAY_DEFEAT_3 = 8 , SAY_RAG_SUM_1 = 9 , SAY_RAG_SUM_2 = 10 ,
SAY_ARRIVAL1_RAG = 1 , SAY_ARRIVAL3_RAG = 3 , SAY_SUMMON_MAJ = 0 , SAY_ARRIVAL1_RAG = 1 ,
SAY_ARRIVAL2_MAJ = 2 , SAY_ARRIVAL3_RAG = 3 , SAY_ARRIVAL5_RAG = 4 , SAY_REINFORCEMENTS1 = 5 ,
SAY_REINFORCEMENTS2 = 6 , SAY_HAND = 7 , SAY_WRATH = 8 , SAY_KILL = 9 ,
SAY_MAGMABURST = 10 , EMOTE_SMOLDERING = 0 , EMOTE_IGNITE = 1 , TEXT_ORACLE_ORPHAN_1 = 1 ,
TEXT_ORACLE_ORPHAN_2 = 2 , TEXT_ORACLE_ORPHAN_3 = 3 , TEXT_ORACLE_ORPHAN_4 = 4 , TEXT_ORACLE_ORPHAN_5 = 5 ,
TEXT_ORACLE_ORPHAN_6 = 6 , TEXT_ORACLE_ORPHAN_7 = 7 , TEXT_ORACLE_ORPHAN_8 = 8 , TEXT_ORACLE_ORPHAN_9 = 9 ,
TEXT_ORACLE_ORPHAN_10 = 10 , TEXT_ORACLE_ORPHAN_11 = 11 , TEXT_ORACLE_ORPHAN_12 = 12 , TEXT_ORACLE_ORPHAN_13 = 13 ,
TEXT_ORACLE_ORPHAN_14 = 14 , TEXT_WOLVAR_ORPHAN_1 = 1 , TEXT_WOLVAR_ORPHAN_2 = 2 , TEXT_WOLVAR_ORPHAN_3 = 3 ,
TEXT_WOLVAR_ORPHAN_4 = 4 , TEXT_WOLVAR_ORPHAN_5 = 5 , TEXT_WOLVAR_ORPHAN_10 = 10 , TEXT_WOLVAR_ORPHAN_11 = 11 ,
TEXT_WOLVAR_ORPHAN_12 = 12 , TEXT_WOLVAR_ORPHAN_13 = 13 , TEXT_WINTERFIN_PLAYMATE_1 = 1 , TEXT_WINTERFIN_PLAYMATE_2 = 2 ,
TEXT_SNOWFALL_GLADE_PLAYMATE_1 = 1 , TEXT_SNOWFALL_GLADE_PLAYMATE_2 = 2 , TEXT_SOO_ROO_1 = 1 , TEXT_ELDER_KEKEK_1 = 1 ,
TEXT_ALEXSTRASZA_2 = 2 , TEXT_KRASUS_8 = 8 , SAY_ONDEATH = 0 , SAY_ONSLAY = 1 ,
SAY_SWARM = 2 , SAY_SLEEP = 3 , SAY_INFERNO = 4 , SAY_ONAGGRO = 5 ,
SAY_AGGRO = 1 , SAY_DOOMFIRE = 2 , SAY_AIR_BURST = 3 , SAY_SLAY = 4 ,
SAY_ENRAGE = 5 , SAY_DEATH = 6 , SAY_SOUL_CHARGE = 7 , SAY_ONDEATH = 0 ,
SAY_ONSLAY = 1 , SAY_DOOM = 2 , SAY_ONAGGRO = 3 , SAY_ONSLAY = 0 ,
SAY_MARK = 1 , SAY_ONAGGRO = 2 , SAY_ONDEATH = 0 , SAY_ONSLAY = 1 ,
SAY_DECAY = 2 , SAY_NOVA = 3 , SAY_ONAGGRO = 4 , SAY_KURINAXX_DEATH = 5 ,
EMOTE_AGGRO = 0 , EMOTE_MANA_FULL = 1 , SAY_SUPREME = 0 , SAY_INTRO = 1 ,
SAY_AGGRO = 2 , SAY_SLAY = 3 , SAY_DEATH = 4 , SAY_MATRIARCH_AGGRO = 0 ,
SAY_VOLUNTEER_START = 0 , SAY_VOLUNTEER_END = 1 , SAY_AGGRO = 0 , SAY_INSANITY = 1 ,
SAY_SLAY_1 = 2 , SAY_SLAY_2 = 3 , SAY_SLAY_3 = 4 , SAY_DEATH_1 = 5 ,
SAY_DEATH_2 = 6 , WHISPER_AGGRO = 7 , WHISPER_INSANITY = 8 , WHISPER_SLAY_1 = 9 ,
WHISPER_SLAY_2 = 10 , WHISPER_SLAY_3 = 11 , WHISPER_DEATH_1 = 12 , WHISPER_DEATH_2 = 13 ,
SAY_BALTHARUS_INTRO = 0 , SAY_AGGRO = 1 , SAY_KILL = 2 , SAY_CLONE = 3 ,
SAY_DEATH = 4 , SAY_XERESTRASZA_EVENT = 0 , SAY_XERESTRASZA_EVENT_1 = 1 , SAY_XERESTRASZA_EVENT_2 = 2 ,
SAY_XERESTRASZA_EVENT_3 = 3 , SAY_XERESTRASZA_EVENT_4 = 4 , SAY_XERESTRASZA_EVENT_5 = 5 , SAY_XERESTRASZA_EVENT_6 = 6 ,
SAY_XERESTRASZA_EVENT_7 = 7 , SAY_XERESTRASZA_INTRO = 8 , SAY_AGGRO = 0 , SAY_KILL = 1 ,
SAY_ADDS = 2 , SAY_DEATH = 3 , SAY_REGENERATE = 0 , SAY_INTRO = 1 ,
SAY_AGGRO = 2 , SAY_METEOR_STRIKE = 3 , SAY_PHASE_TWO = 4 , SAY_DEATH = 5 ,
SAY_KILL = 6 , SAY_BERSERK = 7 , EMOTE_CORPOREALITY_POT = 8 , EMOTE_CORPOREALITY_PIP = 9 ,
SAY_SPHERE_PULSE = 1 , SAY_PHASE_THREE = 2 , EMOTE_CORPOREALITY_TIT = 3 , EMOTE_CORPOREALITY_TOT = 4 ,
EMOTE_WARN_LASER = 5 , SAY_AGGRO = 0 , SAY_CONFLAGRATION = 1 , EMOTE_ENRAGED = 2 ,
SAY_KILL = 3 , SAY_AGGRO = 53 , SAY_SLAY_1 = 54 , SAY_SLAY_2 = 55 ,
SAY_DEATH = 56 , SAY_MARK = 57 , SAY_SMASH = 58 , EMOTE_RIMEFANG_ICEBOLT = 59 ,
EMOTE_SMASH = 60 , SAY_INTRO_1 = 0 , SAY_INTRO_2 = 1 , SAY_KELESETH_INVOCATION = 0 ,
EMOTE_KELESETH_INVOCATION = 1 , SAY_KELESETH_SPECIAL = 2 , SAY_KELESETH_KILL = 3 , EMOTE_KELESETH_BERSERK = 4 ,
SAY_KELESETH_DEATH = 5 , SAY_TALDARAM_INVOCATION = 0 , EMOTE_TALDARAM_INVOCATION = 1 , SAY_TALDARAM_SPECIAL = 2 ,
EMOTE_TALDARAM_FLAME = 3 , SAY_TALDARAM_KILL = 4 , EMOTE_TALDARAM_BERSERK = 5 , EMOTE_TALDARAM_DEATH = 6 ,
SAY_VALANAR_INVOCATION = 0 , EMOTE_VALANAR_INVOCATION = 1 , SAY_VALANAR_SPECIAL = 2 , EMOTE_VALANAR_SHOCK_VORTEX = 3 ,
SAY_VALANAR_KILL = 4 , SAY_VALANAR_BERSERK = 5 , SAY_VALANAR_DEATH = 6 , SAY_AGGRO = 0 ,
SAY_VAMPIRIC_BITE = 1 , SAY_MIND_CONTROL = 2 , EMOTE_BLOODTHIRST = 3 , SAY_SWARMING_SHADOWS = 4 ,
EMOTE_SWARMING_SHADOWS = 5 , SAY_PACT_OF_THE_DARKFALLEN = 6 , SAY_AIR_PHASE = 7 , SAY_KILL = 8 ,
SAY_WIPE = 9 , SAY_BERSERK = 10 , SAY_DEATH = 11 , EMOTE_BERSERK_RAID = 12 ,
SAY_SAURFANG_INTRO_1 = 0 , SAY_SAURFANG_INTRO_2 = 1 , SAY_SAURFANG_INTRO_3 = 2 , SAY_SAURFANG_INTRO_4 = 3 ,
SAY_SAURFANG_INTRO_5 = 4 , SAY_SAURFANG_INTRO_6 = 5 , SAY_SAURFANG_INTRO_A = 6 , SAY_SAURFANG_BOARD = 7 ,
SAY_SAURFANG_ENTER_SKYBREAKER = 8 , SAY_SAURFANG_AXETHROWERS = 9 , SAY_SAURFANG_ROCKETEERS = 10 , SAY_SAURFANG_MAGES = 11 ,
SAY_SAURFANG_VICTORY = 12 , SAY_SAURFANG_WIPE = 13 , SAY_MURADIN_INTRO_1 = 0 , SAY_MURADIN_INTRO_2 = 1 ,
SAY_MURADIN_INTRO_3 = 2 , SAY_MURADIN_INTRO_4 = 3 , SAY_MURADIN_INTRO_5 = 4 , SAY_MURADIN_INTRO_6 = 5 ,
SAY_MURADIN_INTRO_7 = 6 , SAY_MURADIN_INTRO_H = 7 , SAY_MURADIN_BOARD = 8 , SAY_MURADIN_ENTER_ORGRIMMS_HAMMER = 9 ,
SAY_MURADIN_RIFLEMAN = 10 , SAY_MURADIN_MORTAR = 11 , SAY_MURADIN_SORCERERS = 12 , SAY_MURADIN_VICTORY = 13 ,
SAY_MURADIN_WIPE = 14 , SAY_ZAFOD_ROCKET_PACK_ACTIVE = 0 , SAY_ZAFOD_ROCKET_PACK_DISABLED = 1 , SAY_OVERHEAT = 0 ,
SAY_PRECIOUS_DIES = 0 , SAY_AGGRO = 1 , EMOTE_SLIME_SPRAY = 2 , SAY_SLIME_SPRAY = 3 ,
EMOTE_UNSTABLE_EXPLOSION = 4 , SAY_UNSTABLE_EXPLOSION = 5 , SAY_KILL = 6 , SAY_BERSERK = 7 ,
SAY_DEATH = 8 , EMOTE_MUTATED_INFECTION = 9 , SAY_ROTFACE_OOZE_FLOOD = 2 , EMOTE_PRECIOUS_ZOMBIES = 0 ,
SAY_AGGRO = 0 , SAY_UNCHAINED_MAGIC = 1 , EMOTE_WARN_BLISTERING_COLD = 2 , SAY_BLISTERING_COLD = 3 ,
SAY_RESPITE_FOR_A_TORMENTED_SOUL = 4 , SAY_AIR_PHASE = 5 , SAY_PHASE_2 = 6 , EMOTE_WARN_FROZEN_ORB = 7 ,
SAY_KILL = 8 , SAY_BERSERK = 9 , SAY_DEATH = 10 , EMOTE_BERSERK_RAID = 11 ,
EMOTE_WEAKENING = 101 , SAY_LK_INTRO_1 = 0 , SAY_LK_INTRO_2 = 1 , SAY_LK_INTRO_3 = 2 ,
SAY_LK_REMORSELESS_WINTER = 4 , SAY_LK_QUAKE = 5 , SAY_LK_SUMMON_VALKYR = 6 , SAY_LK_HARVEST_SOUL = 7 ,
SAY_LK_FROSTMOURNE_ESCAPE = 8 , SAY_LK_FROSTMOURNE_KILL = 9 , SAY_LK_KILL = 10 , SAY_LK_BERSERK = 11 ,
EMOTE_DEFILE_WARNING = 12 , EMOTE_NECROTIC_PLAGUE_WARNING = 13 , SAY_LK_OUTRO_1 = 14 , SAY_LK_OUTRO_2 = 15 ,
SAY_LK_OUTRO_3 = 16 , SAY_LK_OUTRO_4 = 17 , SAY_LK_OUTRO_5 = 18 , SAY_LK_OUTRO_6 = 19 ,
SAY_LK_OUTRO_7 = 20 , SAY_LK_OUTRO_8 = 21 , SAY_TIRION_INTRO_1 = 0 , SAY_TIRION_INTRO_2 = 1 ,
SAY_TIRION_OUTRO_1 = 2 , SAY_TIRION_OUTRO_2 = 3 , SAY_TERENAS_OUTRO_1 = 0 , SAY_TERENAS_OUTRO_2 = 1 ,
SAY_TERENAS_INTRO_1 = 0 , SAY_TERENAS_INTRO_2 = 1 , SAY_TERENAS_INTRO_3 = 2 , SAY_LICH_KING_INTRO = 0 ,
SAY_VALITHRIA_ENTER_COMBAT = 0 , SAY_VALITHRIA_DREAM_PORTAL = 1 , SAY_VALITHRIA_75_PERCENT = 2 , SAY_VALITHRIA_25_PERCENT = 3 ,
SAY_VALITHRIA_DEATH = 4 , SAY_VALITHRIA_PLAYER_DEATH = 5 , SAY_VALITHRIA_BERSERK = 6 , SAY_VALITHRIA_SUCCESS = 7 ,
SAY_TIRION_INTRO_1 = 0 , SAY_TIRION_INTRO_2 = 1 , SAY_TIRION_INTRO_3 = 2 , SAY_TIRION_INTRO_4 = 3 ,
SAY_TIRION_INTRO_H_5 = 4 , SAY_TIRION_INTRO_A_5 = 5 , SAY_LK_INTRO_1 = 0 , SAY_LK_INTRO_2 = 1 ,
SAY_LK_INTRO_3 = 2 , SAY_LK_INTRO_4 = 3 , SAY_LK_INTRO_5 = 4 , SAY_BOLVAR_INTRO_1 = 0 ,
SAY_SAURFANG_INTRO_1 = 15 , SAY_SAURFANG_INTRO_2 = 16 , SAY_SAURFANG_INTRO_3 = 17 , SAY_SAURFANG_INTRO_4 = 18 ,
SAY_MURADIN_INTRO_1 = 13 , SAY_MURADIN_INTRO_2 = 14 , SAY_MURADIN_INTRO_3 = 15 , SAY_TRAP_ACTIVATE = 0 ,
EMOTE_DEATH_PLAGUE_WARNING = 0 , SAY_SVALNA_KILL_CAPTAIN = 1 , SAY_SVALNA_KILL = 4 , SAY_SVALNA_CAPTAIN_DEATH = 5 ,
SAY_SVALNA_DEATH = 6 , EMOTE_SVALNA_IMPALE = 7 , EMOTE_SVALNA_BROKEN_SHIELD = 8 , SAY_CROK_INTRO_1 = 0 ,
SAY_ARNATH_INTRO_2 = 5 , SAY_CROK_INTRO_3 = 1 , SAY_SVALNA_EVENT_START = 0 , SAY_CROK_COMBAT_WP_0 = 2 ,
SAY_CROK_COMBAT_WP_1 = 3 , SAY_CROK_FINAL_WP = 4 , SAY_SVALNA_RESURRECT_CAPTAINS = 2 , SAY_CROK_COMBAT_SVALNA = 5 ,
SAY_SVALNA_AGGRO = 3 , SAY_CAPTAIN_DEATH = 0 , SAY_CAPTAIN_RESURRECTED = 1 , SAY_CAPTAIN_KILL = 2 ,
SAY_CAPTAIN_SECOND_DEATH = 3 , SAY_CAPTAIN_SURVIVE_TALK = 4 , SAY_CROK_WEAKENING_GAUNTLET = 6 , SAY_CROK_WEAKENING_SVALNA = 7 ,
SAY_CROK_DEATH = 8 , SAY_ONBOARD = 0 , SAY_NECROTIC_AURA_APPLIED = 0 , SAY_NECROTIC_AURA_REMOVED = 1 ,
SAY_NECROTIC_AURA_FADING = 2 , SAY_INTRO = 0 , SAY_PHASE_1 , SAY_DEEP_BREATH ,
SAY_SLAY_P1 , SAY_END_P1 , SAY_PHASE_2 , SAY_ANTIMAGIC_SHELL ,
SAY_MAGIC_BLAST , SAY_SLAY_P2 , SAY_END_P2 , SAY_INTRO_PHASE_3 ,
SAY_PHASE_3 , EMOTE_SURGE_OF_POWER_WARNING_P2 , SAY_SURGE_OF_POWER , SAY_BUFFED_BY_SPARK ,
SAY_SLAY_P3 , SAY_SPELL_CASTING_P3 , SAY_DEATH , EMOTE_SURGE_OF_POWER_WARNING_P3 ,
EMOTE_BERSERK , EMOTE_POWER_SPARK = 0 , SAY_ALEXSTRASZA_ONE = 0 , SAY_ALEXSTRASZA_TWO = 1 ,
SAY_ALEXSTRASZA_THREE = 2 , SAY_ALEXSTRASZA_FOUR = 3 , SAY_BRANN_ALGALON_INTRO_1 = 0 , SAY_BRANN_ALGALON_INTRO_2 = 1 ,
SAY_BRANN_ALGALON_OUTRO = 2 , SAY_ALGALON_INTRO_1 = 0 , SAY_ALGALON_INTRO_2 = 1 , SAY_ALGALON_INTRO_3 = 2 ,
SAY_ALGALON_START_TIMER = 3 , SAY_ALGALON_AGGRO = 4 , SAY_ALGALON_COLLAPSING_STAR = 5 , EMOTE_ALGALON_COLLAPSING_STAR = 6 ,
SAY_ALGALON_BIG_BANG = 7 , EMOTE_ALGALON_BIG_BANG = 8 , SAY_ALGALON_ASCEND = 9 , EMOTE_ALGALON_COSMIC_SMASH = 10 ,
SAY_ALGALON_PHASE_TWO = 11 , SAY_ALGALON_OUTRO_1 = 12 , SAY_ALGALON_OUTRO_2 = 13 , SAY_ALGALON_OUTRO_3 = 14 ,
SAY_ALGALON_OUTRO_4 = 15 , SAY_ALGALON_OUTRO_5 = 16 , SAY_ALGALON_DESPAWN_1 = 17 , SAY_ALGALON_DESPAWN_2 = 18 ,
SAY_ALGALON_DESPAWN_3 = 19 , SAY_ALGALON_KILL = 20 , FLAME_LEVIATHAN_SAY_AGGRO = 0 , FLAME_LEVIATHAN_SAY_SLAY ,
FLAME_LEVIATHAN_SAY_DEATH , FLAME_LEVIATHAN_SAY_PURSUE , FLAME_LEVIATHAN_SAY_HARDMODE , FLAME_LEVIATHAN_SAY_TOWER_NONE ,
FLAME_LEVIATHAN_SAY_TOWER_FROST , FLAME_LEVIATHAN_SAY_TOWER_FLAME , FLAME_LEVIATHAN_SAY_TOWER_NATURE , FLAME_LEVIATHAN_SAY_TOWER_STORM ,
FLAME_LEVIATHAN_SAY_PLAYER_RIDING , FLAME_LEVIATHAN_SAY_OVERLOAD , FLAME_LEVIATHAN_EMOTE_PURSUE , FLAME_LEVIATHAN_EMOTE_OVERLOAD ,
FLAME_LEVIATHAN_EMOTE_REPAIR , SAY_AGGRO = 0 , SAY_KILL = 1 , SAY_DEATH = 2 ,
EMOTE_DARK_SHELL = 3 , SAY_INTRO = 0 , SAY_AGGRO = 1 , SAY_SURPREME = 2 ,
SAY_KILL = 3 , SAY_DEATH = 4 , EMOTE_FRENZY = 5 , SAY_RAND = 6 ,
SAY_AGGRO = 0 , SAY_EARTHQUAKE = 1 , SAY_OVERRUN = 2 , SAY_SLAY = 3 ,
SAY_DEATH = 4
}
Functions
void AddSC_instance_blackrock_spire ()
Variables
uint32 const DragonspireMobs [3] = { NPC_BLACKHAND_DREADWEAVER, NPC_BLACKHAND_SUMMONER, NPC_BLACKHAND_VETERAN }
Position SolakarPosLeft = Position(78.0f, -280.0f, 93.0f, 3.0f * M_PI / 2.0)
Position SolakarPosRight = Position(84.0f, -280.0f, 93.0f, 3.0f * M_PI / 2.0)
Position SolakarPosBoss = Position(80.0f, -280.0f, 93.0f, 3.0f * M_PI / 2.0)
MinionData const minionData []
DoorData const doorData []
Enumeration Type Documentation
EventIds
enum EventIds
Enumerator
EVENT_DARGONSPIRE_ROOM_STORE
EVENT_DARGONSPIRE_ROOM_CHECK
EVENT_SOLAKAR_WAVE
EVENT_AWAKEN_WARD_1
EVENT_AWAKEN_WARD_2
EVENT_AWAKEN_WARD_3
EVENT_AWAKEN_WARD_4
EVENT_PLAYERS_GUNSHIP_SPAWN
EVENT_PLAYERS_GUNSHIP_COMBAT
EVENT_PLAYERS_GUNSHIP_SAURFANG
EVENT_ENEMY_GUNSHIP_COMBAT
EVENT_ENEMY_GUNSHIP_DESPAWN
EVENT_QUAKE
EVENT_SECOND_REMORSELESS_WINTER
EVENT_TELEPORT_TO_FROSMOURNE
EVENT_FESTERGUT_VALVE_USED
EVENT_ROTFACE_VALVE_USED
Definition at line 31 of file instance_blackrock_spire.cpp.
 {
     EVENT_DARGONSPIRE_ROOM_STORE           = 1,
     EVENT_DARGONSPIRE_ROOM_CHECK           = 2,
     EVENT_SOLAKAR_WAVE                     = 3
 };
SolakarWaves
enum SolakarWaves
Enumerator
MAX_WAVE_COUNT
Definition at line 44 of file instance_blackrock_spire.cpp.
 {
     MAX_WAVE_COUNT = 5
 };
Texts
enum Texts
Enumerator
SAY_NEFARIUS_REND_WIPE
SAY_SOLAKAR_FIRST_HATCHER
EMOTE_MASS_ERRUPTION
EMOTE_LOWHP
EMOTE_FRENZY
SAY_AGGRO
SAY_SPAWN
SAY_SLAY
SAY_DEFEAT
SAY_SUMMON_MAJ
SAY_ARRIVAL2_MAJ
SAY_LAST_ADD
SAY_DEFEAT_2
SAY_DEFEAT_3
SAY_RAG_SUM_1
SAY_RAG_SUM_2
SAY_ARRIVAL1_RAG
SAY_ARRIVAL3_RAG
SAY_SUMMON_MAJ
SAY_ARRIVAL1_RAG
SAY_ARRIVAL2_MAJ
SAY_ARRIVAL3_RAG
SAY_ARRIVAL5_RAG
SAY_REINFORCEMENTS1
SAY_REINFORCEMENTS2
SAY_HAND
SAY_WRATH
SAY_KILL
SAY_MAGMABURST
EMOTE_SMOLDERING
EMOTE_IGNITE
TEXT_ORACLE_ORPHAN_1
TEXT_ORACLE_ORPHAN_2
TEXT_ORACLE_ORPHAN_3
TEXT_ORACLE_ORPHAN_4
TEXT_ORACLE_ORPHAN_5
TEXT_ORACLE_ORPHAN_6
TEXT_ORACLE_ORPHAN_7
TEXT_ORACLE_ORPHAN_8
TEXT_ORACLE_ORPHAN_9
TEXT_ORACLE_ORPHAN_10
TEXT_ORACLE_ORPHAN_11
TEXT_ORACLE_ORPHAN_12
TEXT_ORACLE_ORPHAN_13
TEXT_ORACLE_ORPHAN_14
TEXT_WOLVAR_ORPHAN_1
TEXT_WOLVAR_ORPHAN_2
TEXT_WOLVAR_ORPHAN_3
TEXT_WOLVAR_ORPHAN_4
TEXT_WOLVAR_ORPHAN_5
TEXT_WOLVAR_ORPHAN_10
TEXT_WOLVAR_ORPHAN_11
TEXT_WOLVAR_ORPHAN_12
TEXT_WOLVAR_ORPHAN_13
TEXT_WINTERFIN_PLAYMATE_1
TEXT_WINTERFIN_PLAYMATE_2
TEXT_SNOWFALL_GLADE_PLAYMATE_1
TEXT_SNOWFALL_GLADE_PLAYMATE_2
TEXT_SOO_ROO_1
TEXT_ELDER_KEKEK_1
TEXT_ALEXSTRASZA_2
TEXT_KRASUS_8
SAY_ONDEATH
SAY_ONSLAY
SAY_SWARM
SAY_SLEEP
SAY_INFERNO
SAY_ONAGGRO
SAY_AGGRO
SAY_DOOMFIRE
SAY_AIR_BURST
SAY_SLAY
SAY_ENRAGE
SAY_DEATH
SAY_SOUL_CHARGE
SAY_ONDEATH
SAY_ONSLAY
SAY_DOOM
SAY_ONAGGRO
SAY_ONSLAY
SAY_MARK
SAY_ONAGGRO
SAY_ONDEATH
SAY_ONSLAY
SAY_DECAY
SAY_NOVA
SAY_ONAGGRO
SAY_KURINAXX_DEATH
EMOTE_AGGRO
EMOTE_MANA_FULL
SAY_SUPREME
SAY_INTRO
SAY_AGGRO
SAY_SLAY
SAY_DEATH
SAY_MATRIARCH_AGGRO
SAY_VOLUNTEER_START
SAY_VOLUNTEER_END
SAY_AGGRO
SAY_INSANITY
SAY_SLAY_1
SAY_SLAY_2
SAY_SLAY_3
SAY_DEATH_1
SAY_DEATH_2
WHISPER_AGGRO
WHISPER_INSANITY
WHISPER_SLAY_1
WHISPER_SLAY_2
WHISPER_SLAY_3
WHISPER_DEATH_1
WHISPER_DEATH_2
SAY_BALTHARUS_INTRO
SAY_AGGRO
SAY_KILL
SAY_CLONE
SAY_DEATH
SAY_XERESTRASZA_EVENT
SAY_XERESTRASZA_EVENT_1
SAY_XERESTRASZA_EVENT_2
SAY_XERESTRASZA_EVENT_3
SAY_XERESTRASZA_EVENT_4
SAY_XERESTRASZA_EVENT_5
SAY_XERESTRASZA_EVENT_6
SAY_XERESTRASZA_EVENT_7
SAY_XERESTRASZA_INTRO
SAY_AGGRO
SAY_KILL
SAY_ADDS
SAY_DEATH
SAY_REGENERATE
SAY_INTRO
SAY_AGGRO
SAY_METEOR_STRIKE
SAY_PHASE_TWO
SAY_DEATH
SAY_KILL
SAY_BERSERK
EMOTE_CORPOREALITY_POT
EMOTE_CORPOREALITY_PIP
SAY_SPHERE_PULSE
SAY_PHASE_THREE
EMOTE_CORPOREALITY_TIT
EMOTE_CORPOREALITY_TOT
EMOTE_WARN_LASER
SAY_AGGRO
SAY_CONFLAGRATION
EMOTE_ENRAGED
SAY_KILL
SAY_AGGRO
SAY_SLAY_1
SAY_SLAY_2
SAY_DEATH
SAY_MARK
SAY_SMASH
EMOTE_RIMEFANG_ICEBOLT
EMOTE_SMASH
SAY_INTRO_1
SAY_INTRO_2
SAY_KELESETH_INVOCATION
EMOTE_KELESETH_INVOCATION
SAY_KELESETH_SPECIAL
SAY_KELESETH_KILL
EMOTE_KELESETH_BERSERK
SAY_KELESETH_DEATH
SAY_TALDARAM_INVOCATION
EMOTE_TALDARAM_INVOCATION
SAY_TALDARAM_SPECIAL
EMOTE_TALDARAM_FLAME
SAY_TALDARAM_KILL
EMOTE_TALDARAM_BERSERK
EMOTE_TALDARAM_DEATH
SAY_VALANAR_INVOCATION
EMOTE_VALANAR_INVOCATION
SAY_VALANAR_SPECIAL
EMOTE_VALANAR_SHOCK_VORTEX
SAY_VALANAR_KILL
SAY_VALANAR_BERSERK
SAY_VALANAR_DEATH
SAY_AGGRO
SAY_VAMPIRIC_BITE
SAY_MIND_CONTROL
EMOTE_BLOODTHIRST
SAY_SWARMING_SHADOWS
EMOTE_SWARMING_SHADOWS
SAY_PACT_OF_THE_DARKFALLEN
SAY_AIR_PHASE
SAY_KILL
SAY_WIPE
SAY_BERSERK
SAY_DEATH
EMOTE_BERSERK_RAID
SAY_SAURFANG_INTRO_1
SAY_SAURFANG_INTRO_2
SAY_SAURFANG_INTRO_3
SAY_SAURFANG_INTRO_4
SAY_SAURFANG_INTRO_5
SAY_SAURFANG_INTRO_6
SAY_SAURFANG_INTRO_A
SAY_SAURFANG_BOARD
SAY_SAURFANG_ENTER_SKYBREAKER
SAY_SAURFANG_AXETHROWERS
SAY_SAURFANG_ROCKETEERS
SAY_SAURFANG_MAGES
SAY_SAURFANG_VICTORY
SAY_SAURFANG_WIPE
SAY_MURADIN_INTRO_1
SAY_MURADIN_INTRO_2
SAY_MURADIN_INTRO_3
SAY_MURADIN_INTRO_4
SAY_MURADIN_INTRO_5
SAY_MURADIN_INTRO_6
SAY_MURADIN_INTRO_7
SAY_MURADIN_INTRO_H
SAY_MURADIN_BOARD
SAY_MURADIN_ENTER_ORGRIMMS_HAMMER
SAY_MURADIN_RIFLEMAN
SAY_MURADIN_MORTAR
SAY_MURADIN_SORCERERS
SAY_MURADIN_VICTORY
SAY_MURADIN_WIPE
SAY_ZAFOD_ROCKET_PACK_ACTIVE
SAY_ZAFOD_ROCKET_PACK_DISABLED
SAY_OVERHEAT
SAY_PRECIOUS_DIES
SAY_AGGRO
EMOTE_SLIME_SPRAY
SAY_SLIME_SPRAY
EMOTE_UNSTABLE_EXPLOSION
SAY_UNSTABLE_EXPLOSION
SAY_KILL
SAY_BERSERK
SAY_DEATH
EMOTE_MUTATED_INFECTION
SAY_ROTFACE_OOZE_FLOOD
EMOTE_PRECIOUS_ZOMBIES
SAY_AGGRO
SAY_UNCHAINED_MAGIC
EMOTE_WARN_BLISTERING_COLD
SAY_BLISTERING_COLD
SAY_RESPITE_FOR_A_TORMENTED_SOUL
SAY_AIR_PHASE
SAY_PHASE_2
EMOTE_WARN_FROZEN_ORB
SAY_KILL
SAY_BERSERK
SAY_DEATH
EMOTE_BERSERK_RAID
EMOTE_WEAKENING
SAY_LK_INTRO_1
SAY_LK_INTRO_2
SAY_LK_INTRO_3
SAY_LK_REMORSELESS_WINTER
SAY_LK_QUAKE
SAY_LK_SUMMON_VALKYR
SAY_LK_HARVEST_SOUL
SAY_LK_FROSTMOURNE_ESCAPE
SAY_LK_FROSTMOURNE_KILL
SAY_LK_KILL
SAY_LK_BERSERK
EMOTE_DEFILE_WARNING
EMOTE_NECROTIC_PLAGUE_WARNING
SAY_LK_OUTRO_1
SAY_LK_OUTRO_2
SAY_LK_OUTRO_3
SAY_LK_OUTRO_4
SAY_LK_OUTRO_5
SAY_LK_OUTRO_6
SAY_LK_OUTRO_7
SAY_LK_OUTRO_8
SAY_TIRION_INTRO_1
SAY_TIRION_INTRO_2
SAY_TIRION_OUTRO_1
SAY_TIRION_OUTRO_2
SAY_TERENAS_OUTRO_1
SAY_TERENAS_OUTRO_2
SAY_TERENAS_INTRO_1
SAY_TERENAS_INTRO_2
SAY_TERENAS_INTRO_3
SAY_LICH_KING_INTRO
SAY_VALITHRIA_ENTER_COMBAT
SAY_VALITHRIA_DREAM_PORTAL
SAY_VALITHRIA_75_PERCENT
SAY_VALITHRIA_25_PERCENT
SAY_VALITHRIA_DEATH
SAY_VALITHRIA_PLAYER_DEATH
SAY_VALITHRIA_BERSERK
SAY_VALITHRIA_SUCCESS
SAY_TIRION_INTRO_1
SAY_TIRION_INTRO_2
SAY_TIRION_INTRO_3
SAY_TIRION_INTRO_4
SAY_TIRION_INTRO_H_5
SAY_TIRION_INTRO_A_5
SAY_LK_INTRO_1
SAY_LK_INTRO_2
SAY_LK_INTRO_3
SAY_LK_INTRO_4
SAY_LK_INTRO_5
SAY_BOLVAR_INTRO_1
SAY_SAURFANG_INTRO_1
SAY_SAURFANG_INTRO_2
SAY_SAURFANG_INTRO_3
SAY_SAURFANG_INTRO_4
SAY_MURADIN_INTRO_1
SAY_MURADIN_INTRO_2
SAY_MURADIN_INTRO_3
SAY_TRAP_ACTIVATE
EMOTE_DEATH_PLAGUE_WARNING
SAY_SVALNA_KILL_CAPTAIN
SAY_SVALNA_KILL
SAY_SVALNA_CAPTAIN_DEATH
SAY_SVALNA_DEATH
EMOTE_SVALNA_IMPALE
EMOTE_SVALNA_BROKEN_SHIELD
SAY_CROK_INTRO_1
SAY_ARNATH_INTRO_2
SAY_CROK_INTRO_3
SAY_SVALNA_EVENT_START
SAY_CROK_COMBAT_WP_0
SAY_CROK_COMBAT_WP_1
SAY_CROK_FINAL_WP
SAY_SVALNA_RESURRECT_CAPTAINS
SAY_CROK_COMBAT_SVALNA
SAY_SVALNA_AGGRO
SAY_CAPTAIN_DEATH
SAY_CAPTAIN_RESURRECTED
SAY_CAPTAIN_KILL
SAY_CAPTAIN_SECOND_DEATH
SAY_CAPTAIN_SURVIVE_TALK
SAY_CROK_WEAKENING_GAUNTLET
SAY_CROK_WEAKENING_SVALNA
SAY_CROK_DEATH
SAY_ONBOARD
SAY_NECROTIC_AURA_APPLIED
SAY_NECROTIC_AURA_REMOVED
SAY_NECROTIC_AURA_FADING
SAY_INTRO
SAY_PHASE_1
SAY_DEEP_BREATH
SAY_SLAY_P1
SAY_END_P1
SAY_PHASE_2
SAY_ANTIMAGIC_SHELL
SAY_MAGIC_BLAST
SAY_SLAY_P2
SAY_END_P2
SAY_INTRO_PHASE_3
SAY_PHASE_3
EMOTE_SURGE_OF_POWER_WARNING_P2
SAY_SURGE_OF_POWER
SAY_BUFFED_BY_SPARK
SAY_SLAY_P3
SAY_SPELL_CASTING_P3
SAY_DEATH
EMOTE_SURGE_OF_POWER_WARNING_P3
EMOTE_BERSERK
EMOTE_POWER_SPARK
SAY_ALEXSTRASZA_ONE
SAY_ALEXSTRASZA_TWO
SAY_ALEXSTRASZA_THREE
SAY_ALEXSTRASZA_FOUR
SAY_BRANN_ALGALON_INTRO_1
SAY_BRANN_ALGALON_INTRO_2
SAY_BRANN_ALGALON_OUTRO
SAY_ALGALON_INTRO_1
SAY_ALGALON_INTRO_2
SAY_ALGALON_INTRO_3
SAY_ALGALON_START_TIMER
SAY_ALGALON_AGGRO
SAY_ALGALON_COLLAPSING_STAR
EMOTE_ALGALON_COLLAPSING_STAR
SAY_ALGALON_BIG_BANG
EMOTE_ALGALON_BIG_BANG
SAY_ALGALON_ASCEND
EMOTE_ALGALON_COSMIC_SMASH
SAY_ALGALON_PHASE_TWO
SAY_ALGALON_OUTRO_1
SAY_ALGALON_OUTRO_2
SAY_ALGALON_OUTRO_3
SAY_ALGALON_OUTRO_4
SAY_ALGALON_OUTRO_5
SAY_ALGALON_DESPAWN_1
SAY_ALGALON_DESPAWN_2
SAY_ALGALON_DESPAWN_3
SAY_ALGALON_KILL
FLAME_LEVIATHAN_SAY_AGGRO
FLAME_LEVIATHAN_SAY_SLAY
FLAME_LEVIATHAN_SAY_DEATH
FLAME_LEVIATHAN_SAY_PURSUE
FLAME_LEVIATHAN_SAY_HARDMODE
FLAME_LEVIATHAN_SAY_TOWER_NONE
FLAME_LEVIATHAN_SAY_TOWER_FROST
FLAME_LEVIATHAN_SAY_TOWER_FLAME
FLAME_LEVIATHAN_SAY_TOWER_NATURE
FLAME_LEVIATHAN_SAY_TOWER_STORM
FLAME_LEVIATHAN_SAY_PLAYER_RIDING
FLAME_LEVIATHAN_SAY_OVERLOAD
FLAME_LEVIATHAN_EMOTE_PURSUE
FLAME_LEVIATHAN_EMOTE_OVERLOAD
FLAME_LEVIATHAN_EMOTE_REPAIR
SAY_AGGRO
SAY_KILL
SAY_DEATH
EMOTE_DARK_SHELL
SAY_INTRO
SAY_AGGRO
SAY_SURPREME
SAY_KILL
SAY_DEATH
EMOTE_FRENZY
SAY_RAND
SAY_AGGRO
SAY_EARTHQUAKE
SAY_OVERRUN
SAY_SLAY
SAY_DEATH
Definition at line 53 of file instance_blackrock_spire.cpp.
 {
     SAY_NEFARIUS_REND_WIPE      = 11,
     SAY_SOLAKAR_FIRST_HATCHER   = 0
 };
Timers
enum Timers
Enumerator
TIMER_TOMBOFTHESEVEN
TIMER_TOMB_START
TIMER_TOMB_RESET
TIMER_SOLAKAR_WAVE
TIMER_ARCANE_MIN
TIMER_ARCANE_MAX
TIMER_CURSE_MIN
TIMER_CURSE_MAX
TIMER_SHIELD_MIN
TIMER_SHIELD_MAX
TIMER_PORTAL
Definition at line 39 of file instance_blackrock_spire.cpp.
 {
     TIMER_SOLAKAR_WAVE = 30000
 };
Function Documentation
AddSC_instance_blackrock_spire()
void AddSC_instance_blackrock_spire ()
Definition at line 812 of file instance_blackrock_spire.cpp.
 {
     new instance_blackrock_spire();
     new at_dragonspire_hall();
     new at_blackrock_stadium();
     new go_father_flame();
 }
Referenced by AddEasternKingdomsScripts().
Variable Documentation
doorData
DoorData const doorData[]
Initial value:
=
{
    { GO_GYTH_EXIT_DOOR,    DATA_WARCHIEF_REND_BLACKHAND,  DOOR_TYPE_PASSAGE, BOUNDARY_NONE },
    { GO_DRAKKISATH_DOOR_1, DATA_GENERAL_DRAKKISATH,       DOOR_TYPE_PASSAGE, BOUNDARY_NONE },
    { GO_DRAKKISATH_DOOR_2, DATA_GENERAL_DRAKKISATH,       DOOR_TYPE_PASSAGE, BOUNDARY_NONE },
    { 0,                 0,          DOOR_TYPE_ROOM,                          BOUNDARY_NONE }
}
Definition at line 64 of file instance_blackrock_spire.cpp.
Referenced by instance_blackrock_spire::instance_blackrock_spireMapScript::instance_blackrock_spireMapScript().
DragonspireMobs
uint32 const DragonspireMobs[3] = { NPC_BLACKHAND_DREADWEAVER, NPC_BLACKHAND_SUMMONER, NPC_BLACKHAND_VETERAN }
Definition at line 29 of file instance_blackrock_spire.cpp.
Referenced by instance_blackrock_spire::instance_blackrock_spireMapScript::Dragonspireroomstore().
minionData
MinionData const minionData[]
Initial value:
=
{
    { NPC_CHROMATIC_ELITE_GUARD, DATA_GENERAL_DRAKKISATH }
}
Definition at line 59 of file instance_blackrock_spire.cpp.
Referenced by instance_blackrock_spire::instance_blackrock_spireMapScript::instance_blackrock_spireMapScript().
SolakarPosBoss
Position SolakarPosBoss = Position(80.0f, -280.0f, 93.0f, 3.0f * M_PI / 2.0)
Definition at line 51 of file instance_blackrock_spire.cpp.
Referenced by instance_blackrock_spire::instance_blackrock_spireMapScript::SummonSolakarWave().
SolakarPosLeft
Position SolakarPosLeft = Position(78.0f, -280.0f, 93.0f, 3.0f * M_PI / 2.0)
Definition at line 49 of file instance_blackrock_spire.cpp.
Referenced by instance_blackrock_spire::instance_blackrock_spireMapScript::SummonSolakarWave().
SolakarPosRight
Position SolakarPosRight = Position(84.0f, -280.0f, 93.0f, 3.0f * M_PI / 2.0)
Definition at line 50 of file instance_blackrock_spire.cpp.
Referenced by instance_blackrock_spire::instance_blackrock_spireMapScript::SummonSolakarWave().