Azerotcore-wotlk: npc_power_spark::npc_power_sparkAI Struct Reference
npc_power_spark::npc_power_sparkAI Struct Reference
Public Member Functions
npc_power_sparkAI (Creature *pCreature)
void DoAction (int32 param) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void Reset ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
uint16 CheckTimer
uint16 MoveTimer
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 978 of file boss_malygos.cpp.
Constructor & Destructor Documentation
npc_power_sparkAI()
npc_power_spark::npc_power_sparkAI::npc_power_sparkAI (Creature * pCreature) inline
Definition at line 980 of file boss_malygos.cpp.
                                                : NullCreatureAI(pCreature)
         {
             pInstance = me->GetInstanceScript();
             me->CastSpell(me, SPELL_POWER_SPARK_VISUAL, false);
             CheckTimer = 1000;
             MoveTimer = 0;
         }
References Unit::CastSpell(), CheckTimer, WorldObject::GetInstanceScript(), CreatureAI::me, MoveTimer, pInstance, and SPELL_POWER_SPARK_VISUAL.
Member Function Documentation
DamageTaken()
void npc_power_spark::npc_power_sparkAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from UnitAI.
Definition at line 1008 of file boss_malygos.cpp.
         {
             if (damage >= me->GetHealth())
             {
                 damage = 0;
                 if (!me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE))
                 {
                     MoveTimer = 0;
                     me->GetMotionMaster()->MoveIdle();
                     me->DisableSpline();
                     me->MonsterMoveWithSpeed(me->GetPositionX(), me->GetPositionY(), CenterPos.GetPositionZ(), 100.0f);
                     me->SetPosition(me->GetPositionX(), me->GetPositionY(), CenterPos.GetPositionZ(), me->GetOrientation());
                     me->SetUInt32Value(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_DISABLE_MOVE);
                     me->RemoveAura(SPELL_POWER_SPARK_VISUAL);
                     me->CastSpell(me, SPELL_POWER_SPARK_GROUND_BUFF, true);
                     me->DespawnOrUnsummon(60000);
                 }
             }
         }
References Unit::CastSpell(), CenterPos, Creature::DespawnOrUnsummon(), Unit::DisableSpline(), Unit::GetHealth(), Unit::GetMotionMaster(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Object::HasFlag(), CreatureAI::me, Unit::MonsterMoveWithSpeed(), MotionMaster::MoveIdle(), MoveTimer, Unit::RemoveAura(), Creature::SetPosition(), Object::SetUInt32Value(), SPELL_POWER_SPARK_GROUND_BUFF, SPELL_POWER_SPARK_VISUAL, UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
DoAction()
void npc_power_spark::npc_power_sparkAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 992 of file boss_malygos.cpp.
         {
             switch(param)
             {
                 case 1:
                     MoveTimer = 1;
                     break;
                 case 2:
                     MoveTimer = 0;
                     me->GetMotionMaster()->MoveIdle();
                     me->DisableSpline();
                     me->MonsterMoveWithSpeed(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ() + 0.05f, 7.0f);
                     break;
             }
         }
References Unit::DisableSpline(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), CreatureAI::me, Unit::MonsterMoveWithSpeed(), MotionMaster::MoveIdle(), and MoveTimer.
UpdateAI()
void npc_power_spark::npc_power_sparkAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 1028 of file boss_malygos.cpp.
         {
             if (me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE))
                 return;
             if (CheckTimer <= diff)
             {
                 if (pInstance)
                     if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_MALYGOS_GUID)))
                         if (me->IsWithinDist3d(c, 12.0f))
{
                             me->CastSpell(c, SPELL_POWER_SPARK_MALYGOS_BUFF, true);
                             me->DespawnOrUnsummon();
                             return;
                         }
                 CheckTimer = 1000;
             }
             else
                 CheckTimer -= diff;
             if (MoveTimer)
             {
                 if (MoveTimer <= diff)
                 {
                     if (pInstance)
                         if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(DATA_MALYGOS_GUID)))
                             me->GetMotionMaster()->MovePoint(0, *c);
                     MoveTimer = 2000;
                 }
                 else
                     MoveTimer -= diff;
             }
         }
References Unit::CastSpell(), CheckTimer, DATA_MALYGOS_GUID, Creature::DespawnOrUnsummon(), Map::GetCreature(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), Object::HasFlag(), InstanceScript::instance, WorldObject::IsWithinDist3d(), CreatureAI::me, MotionMaster::MovePoint(), MoveTimer, pInstance, SPELL_POWER_SPARK_MALYGOS_BUFF, UNIT_FIELD_FLAGS, and UNIT_FLAG_NON_ATTACKABLE.
Member Data Documentation
CheckTimer
uint16 npc_power_spark::npc_power_sparkAI::CheckTimer
Definition at line 989 of file boss_malygos.cpp.
Referenced by npc_power_sparkAI(), and UpdateAI().
MoveTimer
uint16 npc_power_spark::npc_power_sparkAI::MoveTimer
Definition at line 990 of file boss_malygos.cpp.
Referenced by DamageTaken(), DoAction(), npc_power_sparkAI(), and UpdateAI().
pInstance
InstanceScript* npc_power_spark::npc_power_sparkAI::pInstance
Definition at line 988 of file boss_malygos.cpp.
Referenced by npc_power_sparkAI(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Nexus/EyeOfEternity/boss_malygos.cpp