Azerotcore-wotlk: npc_kiljaeden_controller::npc_kiljaeden_controllerAI Struct Reference
npc_kiljaeden_controller::npc_kiljaeden_controllerAI Struct Reference
Public Member Functions
npc_kiljaeden_controllerAI (Creature *creature)
void ResetOrbs ()
void Reset () override
void JustDied (Unit *) override
void JustSummoned (Creature *summon) override
void SummonedCreatureDies (Creature *summon, Unit *) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void KilledUnit (Unit *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
InstanceScript * instance
SummonList summons
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 172 of file boss_kiljaeden.cpp.
Constructor & Destructor Documentation
npc_kiljaeden_controllerAI()
npc_kiljaeden_controller::npc_kiljaeden_controllerAI::npc_kiljaeden_controllerAI (Creature * creature) inline
Definition at line 174 of file boss_kiljaeden.cpp.
                                                        : NullCreatureAI(creature), summons(me)
         {
             instance = creature->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), and instance.
Member Function Documentation
JustDied()
void npc_kiljaeden_controller::npc_kiljaeden_controllerAI::JustDied (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 207 of file boss_kiljaeden.cpp.
         {
             EntryCheckPredicate kilCheck(NPC_KILJAEDEN);
             EntryCheckPredicate kalCheck(NPC_KALECGOS_KJ);
             summons.DespawnIf(kilCheck);
             summons.DoAction(ACTION_START_POST_EVENT, kalCheck);
             summons.DespawnIf(kalCheck);
             me->CastSpell(me, SPELL_DESTROY_ALL_DRAKES, true);
             summons.DespawnAll();
         }
References ACTION_START_POST_EVENT, Unit::CastSpell(), SummonList::DespawnAll(), SummonList::DespawnIf(), SummonList::DoAction(), CreatureAI::me, NPC_KALECGOS_KJ, NPC_KILJAEDEN, SPELL_DESTROY_ALL_DRAKES, and summons.
JustSummoned()
void npc_kiljaeden_controller::npc_kiljaeden_controllerAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from CreatureAI.
Definition at line 219 of file boss_kiljaeden.cpp.
         {
             summons.Summon(summon);
             if (summon->GetEntry() == NPC_SINISTER_REFLECTION)
                 summon->SetInCombatWithZone();
             else if (summon->GetEntry() == NPC_KALECGOS_KJ)
                 summon->setActive(true);
         }
References Object::GetEntry(), NPC_KALECGOS_KJ, NPC_SINISTER_REFLECTION, WorldObject::setActive(), Creature::SetInCombatWithZone(), SummonList::Summon(), and summons.
Reset()
void npc_kiljaeden_controller::npc_kiljaeden_controllerAI::Reset () inline override virtual
Reimplemented from UnitAI.
Definition at line 190 of file boss_kiljaeden.cpp.
         {
             instance->SetBossState(DATA_KILJAEDEN, NOT_STARTED);
             events.Reset();
             summons.DespawnAll();
             ResetOrbs();
             me->SummonCreature(NPC_HAND_OF_THE_DECEIVER, 1702.62f, 611.19f, 27.66f, 1.81f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30000);
             me->SummonCreature(NPC_HAND_OF_THE_DECEIVER, 1684.099f, 618.848f, 27.67f, 0.589f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30000);
             me->SummonCreature(NPC_HAND_OF_THE_DECEIVER, 1688.38f, 641.10f, 27.50f, 5.43f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 30000);
             me->SummonCreature(NPC_ANVEENA, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ() + 40.0f, 0.0f);
             me->CastSpell(me, SPELL_DESTROY_ALL_DRAKES, true);
             me->CastSpell(me, SPELL_ANVEENA_ENERGY_DRAIN, true);
             events.ScheduleEvent(EVENT_RANDOM_TALK, 60000);
         }
References Unit::CastSpell(), DATA_KILJAEDEN, SummonList::DespawnAll(), EVENT_RANDOM_TALK, Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), instance, CreatureAI::me, NOT_STARTED, NPC_ANVEENA, NPC_HAND_OF_THE_DECEIVER, ResetOrbs(), InstanceScript::SetBossState(), SPELL_ANVEENA_ENERGY_DRAIN, SPELL_DESTROY_ALL_DRAKES, WorldObject::SummonCreature(), summons, and TEMPSUMMON_CORPSE_TIMED_DESPAWN.
ResetOrbs()
void npc_kiljaeden_controller::npc_kiljaeden_controllerAI::ResetOrbs () inline
Definition at line 183 of file boss_kiljaeden.cpp.
         {
             for (uint8 i = 0; i < 4; ++i)
                 if (GameObject* orb = ObjectAccessor::GetGameObject(*me, instance->GetGuidData(DATA_ORB_OF_THE_BLUE_DRAGONFLIGHT_1 + i)))
                     orb->SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
         }
References DATA_ORB_OF_THE_BLUE_DRAGONFLIGHT_1, GAMEOBJECT_FLAGS, ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), GO_FLAG_NOT_SELECTABLE, instance, and CreatureAI::me.
Referenced by Reset().
SummonedCreatureDies()
void npc_kiljaeden_controller::npc_kiljaeden_controllerAI::SummonedCreatureDies (Creature * summon, Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 228 of file boss_kiljaeden.cpp.
         {
             summons.Despawn(summon);
             if (summon->GetEntry() == NPC_HAND_OF_THE_DECEIVER)
             {
                 instance->SetBossState(DATA_KILJAEDEN, IN_PROGRESS);
                 events.ScheduleEvent(EVENT_CHECK_PLAYERS, 1000);
                 if (!summons.HasEntry(NPC_HAND_OF_THE_DECEIVER))
                 {
                     me->RemoveAurasDueToSpell(SPELL_ANVEENA_ENERGY_DRAIN);
                     me->SummonCreature(NPC_KILJAEDEN, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ() + 1.5f, 4.3f, TEMPSUMMON_MANUAL_DESPAWN);
                     me->SummonCreature(NPC_KALECGOS_KJ, 1726.80f, 661.43f, 138.65f, 3.95f, TEMPSUMMON_MANUAL_DESPAWN);
                 }
             }
         }
References DATA_KILJAEDEN, SummonList::Despawn(), EVENT_CHECK_PLAYERS, Object::GetEntry(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), SummonList::HasEntry(), IN_PROGRESS, instance, CreatureAI::me, NPC_HAND_OF_THE_DECEIVER, NPC_KALECGOS_KJ, NPC_KILJAEDEN, Unit::RemoveAurasDueToSpell(), InstanceScript::SetBossState(), SPELL_ANVEENA_ENERGY_DRAIN, WorldObject::SummonCreature(), summons, and TEMPSUMMON_MANUAL_DESPAWN.
UpdateAI()
void npc_kiljaeden_controller::npc_kiljaeden_controllerAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 246 of file boss_kiljaeden.cpp.
         {
             events.Update(diff);
             switch (events.ExecuteEvent())
             {
                 case EVENT_RANDOM_TALK:
                     if (instance->GetBossState(DATA_KILJAEDEN) == NOT_STARTED)
                         Talk(SAY_KJ_OFFCOMBAT);
                     events.ScheduleEvent(EVENT_RANDOM_TALK, urand(90000, 180000));
                     break;
                 case EVENT_CHECK_PLAYERS:
                     {
                         Map::PlayerList const& players = me->GetMap()->GetPlayers();
                         for (Map::PlayerList::const_iterator itr = players.begin(); itr != players.end(); ++itr)
                             if (Player* player = itr->GetSource())
                                 if (!player->IsGameMaster() && me->GetDistance2d(player) < 60.0f && player->IsAlive())
{
                                     events.ScheduleEvent(EVENT_CHECK_PLAYERS, 1000);
                                     return;
                                 }
                         CreatureAI::EnterEvadeMode();
                         break;
                     }
             }
         }
References MapRefMgr::begin(), DATA_KILJAEDEN, diff(), MapRefMgr::end(), CreatureAI::EnterEvadeMode(), EVENT_CHECK_PLAYERS, EVENT_RANDOM_TALK, InstanceScript::GetBossState(), WorldObject::GetDistance2d(), WorldObject::GetMap(), Map::GetPlayers(), instance, CreatureAI::me, NOT_STARTED, SAY_KJ_OFFCOMBAT, CreatureAI::Talk(), and urand().
Member Data Documentation
events
EventMap npc_kiljaeden_controller::npc_kiljaeden_controllerAI::events
Definition at line 179 of file boss_kiljaeden.cpp.
instance
InstanceScript* npc_kiljaeden_controller::npc_kiljaeden_controllerAI::instance
Definition at line 180 of file boss_kiljaeden.cpp.
Referenced by npc_kiljaeden_controllerAI(), Reset(), ResetOrbs(), SummonedCreatureDies(), and UpdateAI().
summons
SummonList npc_kiljaeden_controller::npc_kiljaeden_controllerAI::summons
Definition at line 181 of file boss_kiljaeden.cpp.
Referenced by JustDied(), JustSummoned(), Reset(), and SummonedCreatureDies().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/SunwellPlateau/boss_kiljaeden.cpp