Azerotcore-wotlk: G3D::NetAddress Class Reference
G3D::NetAddress Class Reference
#include <NetAddress.h>
Public Types
enum { DEFAULT_ADAPTER_HOST = 0 }
Public Member Functions
NetAddress (uint32 host, uint16 port=0)
NetAddress (const std::string &hostname, uint16 port)
NetAddress (const std::string &hostnameAndPort)
NetAddress ()
void serialize (class BinaryOutput &b) const
void deserialize (class BinaryInput &b)
bool ok () const
Returns true if this is not an illegal address.
uint32 ip () const
Returns a value in host format (i.e., don't worry about endian issues)
uint16 port () const
std::string ipString () const
std::string toString () const
std::string hostname () const
Static Public Member Functions
static NetAddress broadcastAddress (uint16 port)
Creates a UDP broadcast address for use with a G3D::LightweightConduit.
static void localHostAddresses (Array< NetAddress > &array)
static std::string localHostname ()
Private Member Functions
void init (uint32 host, uint16 port)
void init (const std::string &hostname, uint16 port)
NetAddress (const SOCKADDR_IN &a)
NetAddress (const struct in_addr &addr, uint16 port=0)
Private Attributes
SOCKADDR_IN addr
Friends
class NetworkDevice
class LightweightConduit
class ReliableConduit
Detailed Description
Definition at line 18 of file NetAddress.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
DEFAULT_ADAPTER_HOST
Use the host portion of the IP address of the default adapter on this machine.
Definition at line 34 of file NetAddress.h.
          {
         // Must match ENET_HOST_ANY
         DEFAULT_ADAPTER_HOST = 0
     };
Constructor & Destructor Documentation
NetAddress() [1/6]
G3D::NetAddress::NetAddress (const SOCKADDR_IN & a) private
Definition at line 122 of file NetAddress.cpp.
{
     addr = a;
 }
References mpq::a, and addr.
NetAddress() [2/6]
G3D::NetAddress::NetAddress (const struct in_addr & addr, uint16 port = 0) private
Definition at line 127 of file NetAddress.cpp.
{
     #ifdef G3D_WINDOWS
         init(ntohl(addr.S_un.S_addr), port);
     #else
         init(htonl(addr.s_addr), port);
     #endif
 }
References addr, init(), and port().
NetAddress() [3/6]
G3D::NetAddress::NetAddress (uint32 host, uint16 port = 0) explicit
In host byte order.
See also
DEFAULT_ADAPTER_HOST
Definition at line 103 of file NetAddress.cpp.
{
     init(hostip, port);
 }
References init(), and port().
NetAddress() [4/6]
G3D::NetAddress::NetAddress (const std::string & hostname, uint16 port)
Parameters
port Specified in host byte order (i.e., don't worry about endian issues)
Definition at line 64 of file NetAddress.cpp.
{
     init(hostname, port);
 }
References hostname(), init(), and port().
NetAddress() [5/6]
G3D::NetAddress::NetAddress (const std::string & hostnameAndPort) explicit
Parameters
hostnameAndPort in the form "hostname:port" or "ip:port"
Definition at line 113 of file NetAddress.cpp.
{
     Array<std::string> part = stringSplit(hostnameAndPort, ':');
     debugAssert(part.length() == 2);
     init(part[0], atoi(part[1].c_str()));
 }
References debugAssert, init(), G3D::Array< T, MIN_ELEMENTS >::length(), and G3D::stringSplit().
NetAddress() [6/6]
G3D::NetAddress::NetAddress ()
Definition at line 46 of file NetAddress.cpp.
{
     System::memset(&addr, 0, sizeof(addr));
 }
References addr, and G3D::System::memset().
Referenced by broadcastAddress(), and localHostAddresses().
Member Function Documentation
broadcastAddress()
NetAddress G3D::NetAddress::broadcastAddress (uint16 port) static
Creates a UDP broadcast address for use with a G3D::LightweightConduit.
Deprecated:
Use G3D::NetworkDevice::broadcastAddressArray()
UDP broadcast allows one machine to send a packet to all machines on the same local network. The IP portion of the address is 0xFFFFFFFF, which indicates "broadcast" to the underlying socket API. This feature is not available with the connection-based TCP protocol abstracted by G3D::ReliableConduit; use multisend instead.
Definition at line 108 of file NetAddress.cpp.
{
     return NetAddress(NetworkDevice::instance()->broadcastAddressArray()[0], port);
 }
References G3D::NetworkDevice::instance(), NetAddress(), and port().
deserialize()
void G3D::NetAddress::deserialize (class BinaryInput & b)
Definition at line 164 of file NetAddress.cpp.
{
     uint32 i;
     uint16 p;
     i = b.readUInt32();
     p = b.readUInt16();
     init(i, p);
 }
References b, and init().
hostname()
std::string G3D::NetAddress::hostname () const
Name of this address, without the domain. Performs reverse DNS lookup on this address. This may make a network connection to a DNS server and block until that communication completes if the address is one that has not been recently checked.
Referenced by init(), and NetAddress().
init() [1/2]
void G3D::NetAddress::init (const std::string & hostname, uint16 port) private
Definition at line 71 of file NetAddress.cpp.
{
     uint32 addr;
     if (hostname == "") {
         addr = INADDR_NONE;
     } else {
         addr = inet_addr(hostname.c_str());
     }
     // The address wasn't in numeric form, resolve it
     if (addr == INADDR_NONE) {
         // Get the IP address of the server and store it in host
         struct hostent* host = gethostbyname(hostname.c_str());
         if (host == NULL) {
             init(0, 0);
             return;
         }
         System::memcpy(&addr, host->h_addr_list[0], host->h_length);
     }
     if (addr != INADDR_NONE) {
         addr = ntohl(addr);
     }
     init(addr, port);
 }
References addr, hostname(), INADDR_NONE, init(), G3D::System::memcpy(), NULL, and port().
init() [2/2]
void G3D::NetAddress::init (uint32 host, uint16 port) private
Host byte order
Definition at line 50 of file NetAddress.cpp.
{
     if ((host != 0) || (port != 0)) {
         addr.sin_family      = AF_INET;
         addr.sin_port        = htons(port);
         if (host == 0) {
             host = INADDR_ANY;
         }
         addr.sin_addr.s_addr = htonl(host);
     } else {
         System::memset(&addr, 0, sizeof(addr));
     }
 }
References addr, G3D::System::memset(), and port().
Referenced by deserialize(), init(), and NetAddress().
ip()
uint32 G3D::NetAddress::ip () const inline
Returns a value in host format (i.e., don't worry about endian issues)
Definition at line 86 of file NetAddress.h.
{
         return ntohl(addr.sin_addr.s_addr);
         //return ntohl(addr.sin_addr.S_un.S_addr);
     }
References addr.
Referenced by HashTrait< G3D::NetAddress >::hashCode(), and serialize().
ipString()
std::string G3D::NetAddress::ipString () const
Definition at line 180 of file NetAddress.cpp.
{
     return format("%s", inet_ntoa(*(in_addr*)&(addr.sin_addr)));
 }
References addr, and G3D::format().
Referenced by toString().
localHostAddresses()
void G3D::NetAddress::localHostAddresses (Array< NetAddress > & array) static
Definition at line 135 of file NetAddress.cpp.
{
     array.resize(0);
     char ac[256];
     if (gethostname(ac, sizeof(ac)) == SOCKET_ERROR) {
         Log::common()->printf("Error while getting local host name\n");
         return;
     }
     struct hostent* phe = gethostbyname(ac);
     if (phe == 0) {
         Log::common()->printf("Error while getting local host address\n");
         return;
     }
     for (int i = 0; (phe->h_addr_list[i] != 0); ++i) {
         struct in_addr addr;
         memcpy(&addr, phe->h_addr_list[i], sizeof(struct in_addr));
         array.append(NetAddress(addr));
     }
 }
References addr, array, G3D::Log::common(), memcpy, NetAddress(), G3D::Log::printf(), and SOCKET_ERROR.
localHostname()
static std::string G3D::NetAddress::localHostname () static
Name of the local machine machine, without the domain. The value is cached after the first call.
ok()
bool G3D::NetAddress::ok () const
Returns true if this is not an illegal address.
Definition at line 175 of file NetAddress.cpp.
{
     return addr.sin_family != 0;
 }
References addr.
port()
uint16 G3D::NetAddress::port () const inline
Definition at line 91 of file NetAddress.h.
{
         return ntohs(addr.sin_port);
     }
References addr.
Referenced by broadcastAddress(), HashTrait< G3D::NetAddress >::hashCode(), init(), NetAddress(), and serialize().
serialize()
void G3D::NetAddress::serialize (class BinaryOutput & b) const
Definition at line 158 of file NetAddress.cpp.
{
     b.writeUInt32(ip());
     b.writeUInt16(port());
 }
References b, ip(), and port().
toString()
std::string G3D::NetAddress::toString () const
Definition at line 185 of file NetAddress.cpp.
{
     return ipString() + format(":%d", ntohs(addr.sin_port));
 }
References addr, G3D::format(), and ipString().
Referenced by G3D::ReliableConduit::ReliableConduit().
Friends And Related Function Documentation
LightweightConduit
friend class LightweightConduit friend
Definition at line 21 of file NetAddress.h.
NetworkDevice
friend class NetworkDevice friend
Definition at line 20 of file NetAddress.h.
ReliableConduit
friend class ReliableConduit friend
Definition at line 22 of file NetAddress.h.
Member Data Documentation
addr
SOCKADDR_IN G3D::NetAddress::addr private
Definition at line 30 of file NetAddress.h.
Referenced by G3D::NetworkDevice::bind(), init(), ip(), ipString(), localHostAddresses(), NetAddress(), ok(), port(), G3D::ReliableConduit::ReliableConduit(), and toString().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/NetAddress.h
deps/g3dlite/source/NetAddress.cpp