Azerotcore-wotlk: deps/jemalloc/src/sz.c File Reference
sz.c File Reference
#include "jemalloc/internal/jemalloc_preamble.h"
#include "jemalloc/internal/sz.h"
Functions
static void sz_boot_pind2sz_tab (const sc_data_t *sc_data)
static void sz_boot_index2size_tab (const sc_data_t *sc_data)
static void sz_boot_size2index_tab (const sc_data_t *sc_data)
void sz_boot (const sc_data_t *sc_data)
Variables
size_t sz_pind2sz_tab [SC_NPSIZES+1]
size_t sz_index2size_tab [SC_NSIZES]
uint8_t sz_size2index_tab [(SC_LOOKUP_MAXCLASS >> SC_LG_TINY_MIN)+1]
Function Documentation
sz_boot()
void sz_boot (const sc_data_t * sc_data)
Definition at line 60 of file sz.c.
{
     sz_boot_pind2sz_tab(sc_data);
     sz_boot_index2size_tab(sc_data);
     sz_boot_size2index_tab(sc_data);
 }
References sz_boot_index2size_tab(), sz_boot_pind2sz_tab(), and sz_boot_size2index_tab().
sz_boot_index2size_tab()
static void sz_boot_index2size_tab (const sc_data_t * sc_data) static
Definition at line 27 of file sz.c.
{
     for (unsigned i = 0; i < SC_NSIZES; i++) {
         const sc_t *sc = &sc_data->sc[i];
         sz_index2size_tab[i] = (ZU(1) << sc->lg_base)
             + (ZU(sc->ndelta) << (sc->lg_delta));
     }
 }
References sc_s::lg_base, sc_s::lg_delta, sc_s::ndelta, SC_NSIZES, sz_index2size_tab, and ZU.
Referenced by sz_boot().
sz_boot_pind2sz_tab()
static void sz_boot_pind2sz_tab (const sc_data_t * sc_data) static
Definition at line 8 of file sz.c.
{
     int pind = 0;
     for (unsigned i = 0; i < SC_NSIZES; i++) {
         const sc_t *sc = &sc_data->sc[i];
         if (sc->psz) {
             sz_pind2sz_tab[pind] = (ZU(1) << sc->lg_base)
                 + (ZU(sc->ndelta) << sc->lg_delta);
             pind++;
         }
     }
     for (int i = pind; i <= (int)SC_NPSIZES; i++) {
         sz_pind2sz_tab[pind] = sc_data->large_maxclass + PAGE;
     }
 }
References sc_s::lg_base, sc_s::lg_delta, sc_s::ndelta, PAGE, sc_s::psz, SC_NPSIZES, SC_NSIZES, sz_pind2sz_tab, and ZU.
Referenced by sz_boot().
sz_boot_size2index_tab()
static void sz_boot_size2index_tab (const sc_data_t * sc_data) static
Definition at line 43 of file sz.c.
{
     size_t dst_max = (SC_LOOKUP_MAXCLASS >> SC_LG_TINY_MIN) + 1;
     size_t dst_ind = 0;
     for (unsigned sc_ind = 0; sc_ind < SC_NSIZES && dst_ind < dst_max;
         sc_ind++) {
         const sc_t *sc = &sc_data->sc[sc_ind];
         size_t sz = (ZU(1) << sc->lg_base)
             + (ZU(sc->ndelta) << sc->lg_delta);
         size_t max_ind = ((sz + (ZU(1) << SC_LG_TINY_MIN) - 1)
                    >> SC_LG_TINY_MIN);
         for (; dst_ind <= max_ind && dst_ind < dst_max; dst_ind++) {
             sz_size2index_tab[dst_ind] = sc_ind;
         }
     }
 }
References sc_s::lg_base, sc_s::lg_delta, sc_s::ndelta, SC_LG_TINY_MIN, SC_LOOKUP_MAXCLASS, SC_NSIZES, sz_size2index_tab, and ZU.
Referenced by sz_boot().
Variable Documentation
sz_index2size_tab
size_t sz_index2size_tab[SC_NSIZES]
Definition at line 24 of file sz.c.
Referenced by sz_boot_index2size_tab(), and sz_index2size_lookup().
sz_pind2sz_tab
size_t sz_pind2sz_tab[SC_NPSIZES+1]
Definition at line 5 of file sz.c.
Referenced by sz_boot_pind2sz_tab(), and sz_pind2sz_lookup().
sz_size2index_tab
uint8_t sz_size2index_tab[(SC_LOOKUP_MAXCLASS >> SC_LG_TINY_MIN)+1]
Definition at line 40 of file sz.c.
Referenced by sz_boot_size2index_tab(), and sz_size2index_lookup().