Azerotcore-wotlk: AuctionListItemsDelayEvent Class Reference
AuctionListItemsDelayEvent Class Reference
#include <AsyncAuctionListing.h>
Public Member Functions
AuctionListItemsDelayEvent (uint32 msTimer, ObjectGuid playerguid, ObjectGuid creatureguid, std::string searchedname, uint32 listfrom, uint8 levelmin, uint8 levelmax, uint8 usable, uint32 auctionSlotID, uint32 auctionMainCategory, uint32 auctionSubCategory, uint32 quality, uint8 getAll, AuctionSortOrderVector sortOrder)
bool Execute ()
Public Attributes
uint32 _msTimer
ObjectGuid _playerguid
ObjectGuid _creatureguid
std::string _searchedname
uint32 _listfrom
uint8 _levelmin
uint8 _levelmax
uint8 _usable
uint32 _auctionSlotID
uint32 _auctionMainCategory
uint32 _auctionSubCategory
uint32 _quality
uint8 _getAll
AuctionSortOrderVector _sortOrder
Detailed Description
Definition at line 41 of file AsyncAuctionListing.h.
Constructor & Destructor Documentation
AuctionListItemsDelayEvent()
AuctionListItemsDelayEvent::AuctionListItemsDelayEvent (uint32 msTimer, ObjectGuid playerguid, ObjectGuid creatureguid, std::string searchedname, uint32 listfrom, uint8 levelmin, uint8 levelmax, uint8 usable, uint32 auctionSlotID, uint32 auctionMainCategory, uint32 auctionSubCategory, uint32 quality, uint8 getAll, AuctionSortOrderVector sortOrder) inline
Definition at line 44 of file AsyncAuctionListing.h.
                                                                                                                                                                    :
         _msTimer(msTimer), _playerguid(playerguid), _creatureguid(creatureguid), _searchedname(searchedname), _listfrom(listfrom), _levelmin(levelmin), _levelmax(levelmax),_usable(usable),
         _auctionSlotID(auctionSlotID), _auctionMainCategory(auctionMainCategory), _auctionSubCategory(auctionSubCategory), _quality(quality), _getAll(getAll), _sortOrder(sortOrder) { }
Member Function Documentation
Execute()
bool AuctionListItemsDelayEvent::Execute ()
Definition at line 39 of file AsyncAuctionListing.cpp.
 {
     Player* plr = ObjectAccessor::FindPlayer(_playerguid);
     if (!plr || !plr->IsInWorld() || plr->IsDuringRemoveFromWorld() || plr->IsBeingTeleported())
         return true;
     Creature* creature = plr->GetNPCIfCanInteractWith(_creatureguid, UNIT_NPC_FLAG_AUCTIONEER);
     if (!creature)
         return true;
     AuctionHouseObject* auctionHouse = sAuctionMgr->GetAuctionsMap(creature->GetFaction());
     WorldPacket data(SMSG_AUCTION_LIST_RESULT, (4 + 4 + 4) + 50 * ((16 + MAX_INSPECTED_ENCHANTMENT_SLOT * 3) * 4));
     uint32 count = 0;
     uint32 totalcount = 0;
     data << (uint32) 0;
     // converting string that we try to find to lower case
     std::wstring wsearchedname;
     if (!Utf8toWStr(_searchedname, wsearchedname))
         return true;
     wstrToLower(wsearchedname);
     bool result = auctionHouse->BuildListAuctionItems(data, plr,
                   wsearchedname, _listfrom, _levelmin, _levelmax, _usable,
                   _auctionSlotID, _auctionMainCategory, _auctionSubCategory, _quality,
                   count, totalcount, _getAll, _sortOrder);
     if (!result)
         return false;
     data.put<uint32>(0, count);
     data << (uint32) totalcount;
     data << (uint32) 300; // clientside search cooldown [ms] (gray search button)
     plr->GetSession()->SendPacket(&data);
     return true;
 }
References _auctionMainCategory, _auctionSlotID, _auctionSubCategory, _creatureguid, _getAll, _levelmax, _levelmin, _listfrom, _playerguid, _quality, _searchedname, _sortOrder, _usable, AuctionHouseObject::BuildListAuctionItems(), ObjectAccessor::FindPlayer(), Unit::GetFaction(), Player::GetNPCIfCanInteractWith(), Player::GetSession(), Player::IsBeingTeleported(), Unit::IsDuringRemoveFromWorld(), Object::IsInWorld(), MAX_INSPECTED_ENCHANTMENT_SLOT, ByteBuffer::put(), sAuctionMgr, WorldSession::SendPacket(), SMSG_AUCTION_LIST_RESULT, UNIT_NPC_FLAG_AUCTIONEER, Utf8toWStr(), and wstrToLower().
Member Data Documentation
_auctionMainCategory
uint32 AuctionListItemsDelayEvent::_auctionMainCategory
Definition at line 60 of file AsyncAuctionListing.h.
Referenced by Execute().
_auctionSlotID
uint32 AuctionListItemsDelayEvent::_auctionSlotID
Definition at line 59 of file AsyncAuctionListing.h.
Referenced by Execute().
_auctionSubCategory
uint32 AuctionListItemsDelayEvent::_auctionSubCategory
Definition at line 61 of file AsyncAuctionListing.h.
Referenced by Execute().
_creatureguid
ObjectGuid AuctionListItemsDelayEvent::_creatureguid
Definition at line 53 of file AsyncAuctionListing.h.
Referenced by Execute().
_getAll
uint8 AuctionListItemsDelayEvent::_getAll
Definition at line 63 of file AsyncAuctionListing.h.
Referenced by Execute().
_levelmax
uint8 AuctionListItemsDelayEvent::_levelmax
Definition at line 57 of file AsyncAuctionListing.h.
Referenced by Execute().
_levelmin
uint8 AuctionListItemsDelayEvent::_levelmin
Definition at line 56 of file AsyncAuctionListing.h.
Referenced by Execute().
_listfrom
uint32 AuctionListItemsDelayEvent::_listfrom
Definition at line 55 of file AsyncAuctionListing.h.
Referenced by Execute().
_msTimer
uint32 AuctionListItemsDelayEvent::_msTimer
Definition at line 51 of file AsyncAuctionListing.h.
_playerguid
ObjectGuid AuctionListItemsDelayEvent::_playerguid
Definition at line 52 of file AsyncAuctionListing.h.
Referenced by Execute().
_quality
uint32 AuctionListItemsDelayEvent::_quality
Definition at line 62 of file AsyncAuctionListing.h.
Referenced by Execute().
_searchedname
std::string AuctionListItemsDelayEvent::_searchedname
Definition at line 54 of file AsyncAuctionListing.h.
Referenced by Execute().
_sortOrder
AuctionSortOrderVector AuctionListItemsDelayEvent::_sortOrder
Definition at line 64 of file AsyncAuctionListing.h.
Referenced by Execute().
_usable
uint8 AuctionListItemsDelayEvent::_usable
Definition at line 58 of file AsyncAuctionListing.h.
Referenced by Execute().
The documentation for this class was generated from the following files:
src/server/game/Misc/AsyncAuctionListing.h
src/server/game/Misc/AsyncAuctionListing.cpp