Azerotcore-wotlk: npc_thrall_old_hillsbrad Class Reference
npc_thrall_old_hillsbrad Class Reference
Classes
struct npc_thrall_old_hillsbradAI
Public Member Functions
npc_thrall_old_hillsbrad ()
CreatureAI * GetAI (Creature *creature) const override
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 192 of file old_hillsbrad.cpp.
Constructor & Destructor Documentation
npc_thrall_old_hillsbrad()
npc_thrall_old_hillsbrad::npc_thrall_old_hillsbrad () inline
Definition at line 195 of file old_hillsbrad.cpp.
 : CreatureScript("npc_thrall_old_hillsbrad") { }
Member Function Documentation
GetAI()
CreatureAI* npc_thrall_old_hillsbrad::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 197 of file old_hillsbrad.cpp.
     {
         return GetOldHillsbradAI<npc_thrall_old_hillsbradAI>(creature);
     }
OnGossipHello()
bool npc_thrall_old_hillsbrad::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 202 of file old_hillsbrad.cpp.
     {
         InstanceScript* instance = creature->GetInstanceScript();
         if (!instance)
             return true;
         uint32 menuId = creature->GetCreatureTemplate()->GossipMenuId;
         if (instance->GetData(DATA_ESCORT_PROGRESS) == ENCOUNTER_PROGRESS_SKARLOC_KILLED)
             menuId = 7830;
         else if (instance->GetData(DATA_ESCORT_PROGRESS) == ENCOUNTER_PROGRESS_TARREN_MILL)
             menuId = 7840;
         else if (instance->GetData(DATA_ESCORT_PROGRESS) == ENCOUNTER_PROGRESS_TARETHA_MEET)
             menuId = 7853;
         player->PrepareGossipMenu(creature, menuId, true);
         player->SendPreparedGossip(creature);
         return true;
     }
References DATA_ESCORT_PROGRESS, ENCOUNTER_PROGRESS_SKARLOC_KILLED, ENCOUNTER_PROGRESS_TARETHA_MEET, ENCOUNTER_PROGRESS_TARREN_MILL, Creature::GetCreatureTemplate(), ZoneScript::GetData(), WorldObject::GetInstanceScript(), CreatureTemplate::GossipMenuId, Player::PrepareGossipMenu(), and Player::SendPreparedGossip().
OnGossipSelect()
bool npc_thrall_old_hillsbrad::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32) inline override virtual
Reimplemented from CreatureScript.
Definition at line 221 of file old_hillsbrad.cpp.
     {
         GossipMenuItemData const* gossipMenuItemData = player->PlayerTalkClass->GetGossipMenu().GetItemData(0);
         InstanceScript* instance = creature->GetInstanceScript();
         if (!instance || (gossipMenuItemData && gossipMenuItemData->GossipActionMenuId != 0))
             return false;
         ClearGossipMenuFor(player);
         CloseGossipMenuFor(player);
         creature->AI()->DoAction(instance->GetData(DATA_ESCORT_PROGRESS));
         creature->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP | UNIT_NPC_FLAG_QUESTGIVER);
         return true;
     }
References Creature::AI(), ClearGossipMenuFor(), CloseGossipMenuFor(), DATA_ESCORT_PROGRESS, UnitAI::DoAction(), ZoneScript::GetData(), PlayerMenu::GetGossipMenu(), WorldObject::GetInstanceScript(), GossipMenu::GetItemData(), GossipMenuItemData::GossipActionMenuId, Player::PlayerTalkClass, Object::RemoveFlag(), UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAG_QUESTGIVER, and UNIT_NPC_FLAGS.
The documentation for this class was generated from the following file:
src/server/scripts/Kalimdor/CavernsOfTime/EscapeFromDurnholdeKeep/old_hillsbrad.cpp