Azerotcore-wotlk: Chunk Class Reference
Chunk Class Reference
#include <Chunk.h>
Public Member Functions
Chunk (const char *name, uint32 length, uint32 offset, FILE *stream)
int32 FindSubChunkOffset (std::string name)
FILE * GetStream ()
Public Attributes
std::string Name
uint32 Length
uint32 Offset
FILE * Stream
Detailed Description
Definition at line 24 of file Chunk.h.
Constructor & Destructor Documentation
Chunk()
Chunk::Chunk (const char * name, uint32 length, uint32 offset, FILE * stream) inline
Definition at line 27 of file Chunk.h.
 : Name(name), Length(length), Offset(offset), Stream(stream) {}
Member Function Documentation
FindSubChunkOffset()
int32 Chunk::FindSubChunkOffset (std::string name)
Definition at line 21 of file Chunk.cpp.
 {
     // Reverse the name
     name = std::string(name.rbegin(), name.rend());
     if (name.size() != 4)
         return -1;
     FILE* stream = GetStream();
     uint32 matched = 0;
     while (uint32(ftell(stream)) < Utils::Size(stream))
     {
         char b = 0;
         if (fread(&b, sizeof(char), 1, stream) != 1 || b != name[matched])
             matched = 0;
         else
             ++matched;
         if (matched == 4)
             return ftell(stream) - 4;
     }
     return -1;
 }
References b, GetStream(), name, and Utils::Size().
Referenced by WorldModelGroup::WorldModelGroup().
GetStream()
FILE * Chunk::GetStream ()
Definition at line 44 of file Chunk.cpp.
 {
     fseek(Stream, Offset, SEEK_SET);
     return Stream;
 }
References Offset, SEEK_SET, and Stream.
Referenced by FindSubChunkOffset(), DoodadHandler::ProcessInternal(), WorldModelHandler::ProcessInternal(), WorldModelRoot::ReadDoodadInstances(), WDT::ReadGlobalModel(), WorldModelHandler::ReadModelPaths(), and WorldModelGroup::WorldModelGroup().
Member Data Documentation
Length
uint32 Chunk::Length
Definition at line 32 of file Chunk.h.
Referenced by WorldModelRoot::ReadDoodadInstances(), WorldModelHandler::ReadModelPaths(), and WorldModelGroup::WorldModelGroup().
Name
std::string Chunk::Name
Definition at line 31 of file Chunk.h.
Offset
uint32 Chunk::Offset
Definition at line 33 of file Chunk.h.
Referenced by MapChunk::GenerateVertices(), GetStream(), DoodadHandler::ProcessInternal(), WorldModelHandler::ProcessInternal(), and WorldModelHandler::ReadModelPaths().
Stream
FILE* Chunk::Stream
Definition at line 34 of file Chunk.h.
Referenced by GetStream().
The documentation for this class was generated from the following files:
src/tools/mesh_extractor/Chunk.h
src/tools/mesh_extractor/Chunk.cpp