Azerotcore-wotlk: deps/mysqllite/mysys/mf_loadpath.c File Reference
mf_loadpath.c File Reference
#include "mysys_priv.h"
#include <m_string.h>
Functions
char * my_load_path (char *to, const char *path, const char *own_path_prefix)
Function Documentation
my_load_path()
char* my_load_path (char * to, const char * path, const char * own_path_prefix)
Definition at line 26 of file mf_loadpath.c.
 {
   char buff[FN_REFLEN];
   int is_cur;
   DBUG_ENTER("my_load_path");
   DBUG_PRINT("enter",("path: %s  prefix: %s",path,
               own_path_prefix ? own_path_prefix : ""));
   if ((path[0] == FN_HOMELIB && path[1] == FN_LIBCHAR) ||
       test_if_hard_path(path))
     (void) strnmov(buff, path, FN_REFLEN);
   else if ((is_cur=(path[0] == FN_CURLIB && path[1] == FN_LIBCHAR)) ||
        (is_prefix(path,FN_PARENTDIR)) ||
        ! own_path_prefix)
   {
     if (is_cur)
       is_cur=2;                 /* Remove current dir */
     if (! my_getwd(buff,(uint) (FN_REFLEN-strlen(path)+is_cur),MYF(0)))
       (void) strncat(buff, path+is_cur, FN_REFLEN-1);
     else
       (void) strnmov(buff, path, FN_REFLEN);            /* Return org file name */
   }
   else
     (void) strxnmov(buff, FN_REFLEN, own_path_prefix, path, NullS);
   strnmov(to, buff, FN_REFLEN);
   to[FN_REFLEN-1]= '\0';
   DBUG_PRINT("exit",("to: %s",to));
   DBUG_RETURN(to);
 } /* my_load_path */
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, FN_CURLIB, FN_HOMELIB, FN_LIBCHAR, FN_PARENTDIR, FN_REFLEN, is_prefix(), my_getwd(), MYF, NullS, strnmov(), strxnmov(), and test_if_hard_path().
Referenced by my_realpath().