Azerotcore-wotlk: src/server/scripts/OutdoorPvP/outdoorpvp_script_loader.cpp File Reference
outdoorpvp_script_loader.cpp File Reference
Functions
void AddSC_outdoorpvp_ep ()
void AddSC_outdoorpvp_hp ()
void AddSC_outdoorpvp_na ()
void AddSC_outdoorpvp_si ()
void AddSC_outdoorpvp_tf ()
void AddSC_outdoorpvp_zm ()
void AddSC_outdoorpvp_gh ()
void AddOutdoorPvPScripts ()
Function Documentation
AddOutdoorPvPScripts()
void AddOutdoorPvPScripts ()
Definition at line 29 of file outdoorpvp_script_loader.cpp.
 {
     AddSC_outdoorpvp_ep();
     AddSC_outdoorpvp_hp();
     AddSC_outdoorpvp_na();
     AddSC_outdoorpvp_si();
     AddSC_outdoorpvp_tf();
     AddSC_outdoorpvp_zm();
     AddSC_outdoorpvp_gh();
 }
References AddSC_outdoorpvp_ep(), AddSC_outdoorpvp_gh(), AddSC_outdoorpvp_hp(), AddSC_outdoorpvp_na(), AddSC_outdoorpvp_si(), AddSC_outdoorpvp_tf(), and AddSC_outdoorpvp_zm().
AddSC_outdoorpvp_ep()
void AddSC_outdoorpvp_ep ()
Definition at line 774 of file OutdoorPvPEP.cpp.
 {
     new OutdoorPvP_eastern_plaguelands();
 }
Referenced by AddOutdoorPvPScripts().
AddSC_outdoorpvp_gh()
void AddSC_outdoorpvp_gh ()
Definition at line 130 of file OutdoorPvPGH.cpp.
 {
     new OutdoorPvP_grizzly_hills();
 }
Referenced by AddOutdoorPvPScripts().
AddSC_outdoorpvp_hp()
void AddSC_outdoorpvp_hp ()
Definition at line 377 of file OutdoorPvPHP.cpp.
 {
     new OutdoorPvP_hellfire_peninsula();
 }
Referenced by AddOutdoorPvPScripts().
AddSC_outdoorpvp_na()
void AddSC_outdoorpvp_na ()
Definition at line 678 of file OutdoorPvPNA.cpp.
 {
     new OutdoorPvP_nagrand();
 }
Referenced by AddOutdoorPvPScripts().
AddSC_outdoorpvp_si()
void AddSC_outdoorpvp_si ()
Definition at line 262 of file OutdoorPvPSI.cpp.
 {
     new OutdoorPvP_silithus();
 }
Referenced by AddOutdoorPvPScripts().
AddSC_outdoorpvp_tf()
void AddSC_outdoorpvp_tf ()
Definition at line 378 of file OutdoorPvPTF.cpp.
 {
     new OutdoorPvP_terokkar_forest();
 }
Referenced by AddOutdoorPvPScripts().
AddSC_outdoorpvp_zm()
void AddSC_outdoorpvp_zm ()
Definition at line 469 of file OutdoorPvPZM.cpp.
 {
     new OutdoorPvP_zangarmarsh();
 }
Referenced by AddOutdoorPvPScripts().