Azerotcore-wotlk: Acore::Impl Namespace Reference
Acore::Impl Namespace Reference
Namespaces
ChatCommands
EnumUtilsImpl
StringConvertImpl
Classes
struct CryptoGenericsImpl
struct GenericHashImpl
class GenericHash
struct HMACImpl
class GenericHMAC
struct GenericBaseEncoding
class MPSCQueueNonIntrusive
class MPSCQueueIntrusive
struct CastToVisitor
struct CurrentServerProcessHolder
Functions
template<class T , class Tuple , size_t... I>
T * new_from_tuple (Tuple &&args, std::index_sequence< I... >)
AC_COMMON_API std::string ByteArrayToHexStr (uint8 const *bytes, size_t length, bool reverse=false)
AC_COMMON_API void HexStrToByteArray (std::string_view str, uint8 *out, size_t outlen, bool reverse=false)
Function Documentation
ByteArrayToHexStr()
std::string Acore::Impl::ByteArrayToHexStr (uint8 const * bytes, size_t length, bool reverse = false)
Definition at line 636 of file Util.cpp.
 {
     int32 init = 0;
     int32 end = arrayLen;
     int8 op = 1;
     if (reverse)
     {
         init = arrayLen - 1;
         end = -1;
         op = -1;
     }
     std::ostringstream ss;
     for (int32 i = init; i != end; i += op)
     {
         char buffer[4];
         sprintf(buffer, "%02X", bytes[i]);
         ss << buffer;
     }
     return ss.str();
 }
References buffer, and sprintf().
Referenced by ByteArrayToHexStr(), Guild::HandleMemberDepositMoney(), Guild::HandleMemberWithdrawMoney(), WardenMac::Init(), and WardenWin::Init().
HexStrToByteArray()
void Acore::Impl::HexStrToByteArray (std::string_view str, uint8 * out, size_t outlen, bool reverse = false)
Definition at line 660 of file Util.cpp.
 {
     ASSERT(str.size() == (2 * outlen));
     int32 init = 0;
     int32 end = int32(str.length());
     int8 op = 1;
     if (reverse)
     {
         init = int32(str.length() - 2);
         end = -2;
         op = -1;
     }
     uint32 j = 0;
     for (int32 i = init; i != end; i += 2 * op)
     {
         char buffer[3] = { str[i], str[i + 1], '\0' };
         out[j++] = uint8(strtoul(buffer, nullptr, 16));
     }
 }
References ASSERT, and strtoul().
Referenced by HexStrToByteArray(), and RealmList::LoadBuildInfo().
new_from_tuple()
template<class T , class Tuple , size_t... I> T* Acore::Impl::new_from_tuple (Tuple && args, std::index_sequence< I... >)
Definition at line 52 of file Tuples.h.
         {
             return new T(std::get<I>(std::forward<Tuple>(args))...);
         }