Azerotcore-wotlk: iterator_buffer< OutputIt, T, Traits > Class Template Reference
iterator_buffer< OutputIt, T, Traits > Class Template Reference final
#include <core.h>
Public Member Functions
iterator_buffer (OutputIt out, size_t n=buffer_size)
iterator_buffer (iterator_buffer &&other)
~iterator_buffer ()
auto out () -> OutputIt
auto count () const -> size_t
Public Member Functions inherited from buffer_traits
buffer_traits (size_t)
auto count () const -> size_t
auto limit (size_t size) -> size_t
Public Member Functions inherited from buffer< T >
buffer (const buffer &)=delete
void operator= (const buffer &)=delete
auto begin () FMT_NOEXCEPT -> T *
auto end () FMT_NOEXCEPT -> T *
auto begin () const FMT_NOEXCEPT -> const T *
auto end () const FMT_NOEXCEPT -> const T *
auto size () const FMT_NOEXCEPT -> size_t
auto capacity () const FMT_NOEXCEPT -> size_t
auto data () FMT_NOEXCEPT -> T *
auto data () const FMT_NOEXCEPT -> const T *
void clear ()
void try_resize (size_t count)
void try_reserve (size_t new_capacity)
void push_back (const T &value)
template<typename U >
void append (const U *begin, const U *end)
template<typename I >
auto operator[] (I index) -> T &
template<typename I >
auto operator[] (I index) const -> const T &
template<typename U >
void append (const U *begin, const U *end)
Protected Member Functions
void grow (size_t) final FMT_OVERRIDE
void flush ()
Protected Member Functions inherited from buffer< T >
buffer (size_t sz) FMT_NOEXCEPT
buffer (T *p=nullptr, size_t sz=0, size_t cap=0) FMT_NOEXCEPT
~buffer ()=default
buffer (buffer &&)=default
void set (T *buf_data, size_t buf_capacity) FMT_NOEXCEPT
Private Types
enum { buffer_size = 256 }
Private Attributes
OutputIt out_
T data_ [buffer_size]
Additional Inherited Members
Public Types inherited from buffer< T >
using value_type = T
using const_reference = const T &
Detailed Description
template<typename OutputIt, typename T, typename Traits = buffer_traits>
class iterator_buffer< OutputIt, T, Traits >
Definition at line 857 of file core.h.
Member Enumeration Documentation
anonymous enum
template<typename OutputIt , typename T , typename Traits = buffer_traits> anonymous enum private
Enumerator
buffer_size
Definition at line 860 of file core.h.
 { buffer_size = 256 };
Constructor & Destructor Documentation
iterator_buffer() [1/2]
template<typename OutputIt , typename T , typename Traits = buffer_traits> iterator_buffer< OutputIt, T, Traits >::iterator_buffer (OutputIt out, size_t n = buffer_size) inline explicit
Definition at line 875 of file core.h.
       : Traits(n), buffer<T>(data_, 0, buffer_size), out_(out) {}
iterator_buffer() [2/2]
template<typename OutputIt , typename T , typename Traits = buffer_traits> iterator_buffer< OutputIt, T, Traits >::iterator_buffer (iterator_buffer< OutputIt, T, Traits > && other) inline
Definition at line 877 of file core.h.
       : Traits(other), buffer<T>(data_, 0, buffer_size), out_(other.out_) {}
~iterator_buffer()
template<typename OutputIt , typename T , typename Traits = buffer_traits> iterator_buffer< OutputIt, T, Traits >::~iterator_buffer () inline
Definition at line 879 of file core.h.
 { flush(); }
References iterator_buffer< OutputIt, T, Traits >::flush().
Member Function Documentation
count()
template<typename OutputIt , typename T , typename Traits = buffer_traits> auto iterator_buffer< OutputIt, T, Traits >::count () const -> size_t inline
Definition at line 885 of file core.h.
 { return Traits::count() + this->size(); }
References count(), and buffer< T >::size().
flush()
template<typename OutputIt , typename T , typename Traits = buffer_traits> void iterator_buffer< OutputIt, T, Traits >::flush () inline protected
Definition at line 868 of file core.h.
                {
     auto size = this->size();
     this->clear();
     out_ = copy_str<T>(data_, data_ + this->limit(size), out_);
   }
References buffer< T >::clear(), iterator_buffer< OutputIt, T, Traits >::data_, buffer_traits::limit(), and buffer< T >::size().
Referenced by iterator_buffer< OutputIt, T, Traits >::grow(), iterator_buffer< OutputIt, T, Traits >::out(), and iterator_buffer< OutputIt, T, Traits >::~iterator_buffer().
grow()
template<typename OutputIt , typename T , typename Traits = buffer_traits> void iterator_buffer< OutputIt, T, Traits >::grow (size_t capacity) inline final protected virtual
Increases the buffer capacity to hold at least capacity elements.
Implements buffer< T >.
Definition at line 864 of file core.h.
{
     if (this->size() == buffer_size) flush();
   }
References iterator_buffer< OutputIt, T, Traits >::buffer_size, iterator_buffer< OutputIt, T, Traits >::flush(), and buffer< T >::size().
out()
template<typename OutputIt , typename T , typename Traits = buffer_traits> auto iterator_buffer< OutputIt, T, Traits >::out () -> OutputIt inline
Definition at line 881 of file core.h.
{
     flush();
     return out_;
   }
References iterator_buffer< OutputIt, T, Traits >::flush(), and iterator_buffer< OutputIt, T, Traits >::out_.
Member Data Documentation
data_
template<typename OutputIt , typename T , typename Traits = buffer_traits> T iterator_buffer< OutputIt, T, Traits >::data_[buffer_size] private
Definition at line 861 of file core.h.
Referenced by iterator_buffer< OutputIt, T, Traits >::flush().
out_
template<typename OutputIt , typename T , typename Traits = buffer_traits> OutputIt iterator_buffer< OutputIt, T, Traits >::out_ private
Definition at line 859 of file core.h.
Referenced by iterator_buffer< OutputIt, T, Traits >::out().
The documentation for this class was generated from the following file:
deps/fmt/include/fmt/core.h