Azerotcore-wotlk: boss_twilight_halion::boss_twilight_halionAI Struct Reference
boss_twilight_halion::boss_twilight_halionAI Struct Reference
Public Member Functions
boss_twilight_halionAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *) override
void EnterEvadeMode () override
void KilledUnit (Unit *victim) override
void JustDied (Unit *killer) override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
EventMap _events
InstanceScript * _instance
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 436 of file boss_halion.cpp.
Constructor & Destructor Documentation
boss_twilight_halionAI()
boss_twilight_halion::boss_twilight_halionAI::boss_twilight_halionAI (Creature * creature) inline
Definition at line 438 of file boss_halion.cpp.
                                                    : ScriptedAI(creature), _instance(creature->GetInstanceScript())
         {
             Creature* halion = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(NPC_HALION));
             if (!halion)
                 return;
             halion->AddAura(SPELL_COPY_DAMAGE, me);
             me->AddAura(SPELL_COPY_DAMAGE, halion);
             me->AddAura(SPELL_DUSK_SHROUD, me);
             me->SetHealth(halion->GetHealth());
             me->setActive(true);
         }
References _instance, Unit::AddAura(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Unit::GetHealth(), ScriptedAI::me, NPC_HALION, WorldObject::setActive(), Unit::SetHealth(), SPELL_COPY_DAMAGE, and SPELL_DUSK_SHROUD.
Member Function Documentation
DamageTaken()
void boss_twilight_halion::boss_twilight_halionAI::DamageTaken (Unit * attacker, uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 508 of file boss_halion.cpp.
         {
             if (!attacker || !me->InSamePhase(attacker))
                 return;
             if (Creature* controller = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(NPC_HALION_CONTROLLER)))
                 controller->AI()->SetData(DATA_TWILIGHT_DAMAGE_TAKEN, damage);
         }
References _instance, DATA_TWILIGHT_DAMAGE_TAKEN, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), WorldObject::InSamePhase(), ScriptedAI::me, and NPC_HALION_CONTROLLER.
EnterCombat()
void boss_twilight_halion::boss_twilight_halionAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 461 of file boss_halion.cpp.
         {
             _events.Reset();
             _events.ScheduleEvent(EVENT_CLEAVE, urand(8000, 10000));
             _events.ScheduleEvent(EVENT_TAIL_LASH, 10000);
             _events.ScheduleEvent(EVENT_BREATH, urand(10000, 15000));
             _events.ScheduleEvent(EVENT_SOUL_CONSUMPTION, 20000);
             _events.ScheduleEvent(EVENT_SHADOW_PULSARS, 16000);
             _events.ScheduleEvent(EVENT_SEND_ENCOUNTER_UNIT, 2000);
             _events.ScheduleEvent(EVENT_CHECK_HEALTH, 1000);
             me->SetInCombatWithZone();
         }
References _events, EVENT_BREATH, EVENT_CHECK_HEALTH, EVENT_CLEAVE, EVENT_SEND_ENCOUNTER_UNIT, EVENT_SHADOW_PULSARS, EVENT_SOUL_CONSUMPTION, EVENT_TAIL_LASH, ScriptedAI::me, EventMap::Reset(), EventMap::ScheduleEvent(), Creature::SetInCombatWithZone(), and urand().
EnterEvadeMode()
void boss_twilight_halion::boss_twilight_halionAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 475 of file boss_halion.cpp.
         {
         }
JustDied()
void boss_twilight_halion::boss_twilight_halionAI::JustDied (Unit * killer) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 488 of file boss_halion.cpp.
         {
             if (Creature* halion = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(NPC_HALION)))
             {
                 // Ensure looting
                 if (me->IsDamageEnoughForLootingAndReward())
                     halion->LowerPlayerDamageReq(halion->GetMaxHealth());
                 if (halion->IsAlive())
                     Unit::Kill(killer, halion);
             }
             if (Creature* controller = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(NPC_HALION_CONTROLLER)))
                 if (controller->IsAlive())
                     Unit::Kill(controller, controller);
             _instance->SendEncounterUnit(ENCOUNTER_FRAME_DISENGAGE, me);
             me->CastSpell(me, SPELL_CLEAR_DEBUFFS, false);
         }
References _instance, Unit::CastSpell(), ENCOUNTER_FRAME_DISENGAGE, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Creature::IsDamageEnoughForLootingAndReward(), Unit::Kill(), ScriptedAI::me, NPC_HALION, NPC_HALION_CONTROLLER, InstanceScript::SendEncounterUnit(), and SPELL_CLEAR_DEBUFFS.
KilledUnit()
void boss_twilight_halion::boss_twilight_halionAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 479 of file boss_halion.cpp.
         {
             if (victim->GetTypeId() == TYPEID_PLAYER && _events.GetNextEventTime(EVENT_KILL_TALK) == 0)
             {
                 Talk(SAY_KILL);
                 _events.ScheduleEvent(EVENT_KILL_TALK, 6000);
             }
         }
References _events, EVENT_KILL_TALK, EventMap::GetNextEventTime(), Object::GetTypeId(), SAY_KILL, EventMap::ScheduleEvent(), CreatureAI::Talk(), and TYPEID_PLAYER.
Reset()
void boss_twilight_halion::boss_twilight_halionAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 452 of file boss_halion.cpp.
         {
             _events.Reset();
             me->SetPhaseMask(0x21, true);
             me->SetInCombatWithZone();
             me->SetPhaseMask(0x20, true);
             me->SetReactState(REACT_DEFENSIVE);
         }
References _events, ScriptedAI::me, REACT_DEFENSIVE, EventMap::Reset(), Creature::SetInCombatWithZone(), Unit::SetPhaseMask(), and Creature::SetReactState().
UpdateAI()
void boss_twilight_halion::boss_twilight_halionAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 517 of file boss_halion.cpp.
         {
             if (!UpdateVictim())
                 return;
             _events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (_events.ExecuteEvent())
             {
                 case EVENT_SEND_ENCOUNTER_UNIT:
                     _instance->SendEncounterUnit(ENCOUNTER_FRAME_ENGAGE, me, 2);
                     break;
                 case EVENT_CLEAVE:
                     me->CastSpell(me->GetVictim(), SPELL_CLEAVE, false);
                     _events.ScheduleEvent(EVENT_CLEAVE, urand(8000, 10000));
                     break;
                 case EVENT_TAIL_LASH:
                     me->CastSpell(me, SPELL_TAIL_LASH, false);
                     _events.ScheduleEvent(EVENT_TAIL_LASH, 10000);
                     break;
                 case EVENT_BREATH:
                     me->CastSpell(me->GetVictim(), SPELL_DARK_BREATH, false);
                     _events.ScheduleEvent(EVENT_BREATH, urand(10000, 12000));
                     break;
                 case EVENT_SOUL_CONSUMPTION:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 1, 100.0f, true, SPELL_TWILIGHT_REALM))
                         me->CastSpell(target, SPELL_SOUL_CONSUMPTION, false);
                     _events.ScheduleEvent(EVENT_SOUL_CONSUMPTION, 20000);
                     break;
                 case EVENT_CHECK_HEALTH:
                     if (me->HealthBelowPct(50))
                     {
                         me->CastStop();
                         me->CastSpell(me, SPELL_TWILIGHT_DIVISION, false);
                         Talk(SAY_PHASE_THREE);
                         return;
                     }
                     _events.ScheduleEvent(EVENT_CHECK_HEALTH, 1000);
                     break;
                 case EVENT_SHADOW_PULSARS:
                     Talk(SAY_SPHERE_PULSE);
                     Talk(EMOTE_WARN_LASER);
                     _events.ScheduleEvent(EVENT_SHADOW_PULSARS, 29000);
                     _events.ScheduleEvent(EVENT_SHADOW_PULSARS_SHOOT, 5000);
                     break;
                 case EVENT_SHADOW_PULSARS_SHOOT:
                     if (Creature* orbCarrier = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(NPC_ORB_CARRIER)))
                         orbCarrier->AI()->DoAction(ACTION_SHOOT);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References _events, _instance, ACTION_SHOOT, Unit::CastSpell(), Unit::CastStop(), UnitAI::DoMeleeAttackIfReady(), EMOTE_WARN_LASER, ENCOUNTER_FRAME_ENGAGE, EVENT_BREATH, EVENT_CHECK_HEALTH, EVENT_CLEAVE, EVENT_SEND_ENCOUNTER_UNIT, EVENT_SHADOW_PULSARS, EVENT_SHADOW_PULSARS_SHOOT, EVENT_SOUL_CONSUMPTION, EVENT_TAIL_LASH, EventMap::ExecuteEvent(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Unit::GetVictim(), Unit::HasUnitState(), Unit::HealthBelowPct(), ScriptedAI::me, NPC_ORB_CARRIER, SAY_PHASE_THREE, SAY_SPHERE_PULSE, EventMap::ScheduleEvent(), SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), InstanceScript::SendEncounterUnit(), SPELL_CLEAVE, SPELL_DARK_BREATH, SPELL_SOUL_CONSUMPTION, SPELL_TAIL_LASH, SPELL_TWILIGHT_DIVISION, SPELL_TWILIGHT_REALM, CreatureAI::Talk(), UNIT_STATE_CASTING, EventMap::Update(), CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
_events
EventMap boss_twilight_halion::boss_twilight_halionAI::_events private
Definition at line 574 of file boss_halion.cpp.
Referenced by EnterCombat(), KilledUnit(), Reset(), and UpdateAI().
_instance
InstanceScript* boss_twilight_halion::boss_twilight_halionAI::_instance private
Definition at line 575 of file boss_halion.cpp.
Referenced by boss_twilight_halionAI(), DamageTaken(), JustDied(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/ChamberOfAspects/RubySanctum/boss_halion.cpp