Azerotcore-wotlk: LinkedListElement Class Reference
LinkedListElement Class Reference
#include <LinkedList.h>
Public Member Functions
LinkedListElement ()
~LinkedListElement ()
bool hasNext () const
bool hasPrev () const
bool isInList () const
LinkedListElement * next ()
LinkedListElement const * next () const
LinkedListElement * prev ()
LinkedListElement const * prev () const
LinkedListElement * nocheck_next ()
LinkedListElement const * nocheck_next () const
LinkedListElement * nocheck_prev ()
LinkedListElement const * nocheck_prev () const
void delink ()
void insertBefore (LinkedListElement *pElem)
void insertAfter (LinkedListElement *pElem)
Private Attributes
LinkedListElement * iNext
LinkedListElement * iPrev
Friends
class LinkedListHead
Detailed Description
Definition at line 27 of file LinkedList.h.
Constructor & Destructor Documentation
LinkedListElement()
LinkedListElement::LinkedListElement () inline
Definition at line 35 of file LinkedList.h.
 : iNext(nullptr), iPrev(nullptr) { }
~LinkedListElement()
LinkedListElement::~LinkedListElement () inline
Definition at line 36 of file LinkedList.h.
 { delink(); }
References delink().
Member Function Documentation
delink()
void LinkedListElement::delink () inline
Definition at line 52 of file LinkedList.h.
     {
         if (isInList())
         {
             iNext->iPrev = iPrev;
             iPrev->iNext = iNext;
             iNext = nullptr;
             iPrev = nullptr;
         }
     }
References iNext, iPrev, and isInList().
Referenced by RefMgr< TO, FROM >::clearReferences(), Reference< TO, FROM >::invalidate(), Reference< TO, FROM >::unlink(), and ~LinkedListElement().
hasNext()
bool LinkedListElement::hasNext () const inline
Definition at line 38 of file LinkedList.h.
 { return (iNext && iNext->iNext != nullptr); }
References iNext.
Referenced by next().
hasPrev()
bool LinkedListElement::hasPrev () const inline
Definition at line 39 of file LinkedList.h.
 { return (iPrev && iPrev->iPrev != nullptr); }
References iPrev.
Referenced by prev().
insertAfter()
void LinkedListElement::insertAfter (LinkedListElement * pElem) inline
Definition at line 71 of file LinkedList.h.
     {
         pElem->iPrev = this;
         pElem->iNext = iNext;
         iNext->iPrev = pElem;
         iNext = pElem;
     }
References iNext, and iPrev.
Referenced by LinkedListHead::insertFirst().
insertBefore()
void LinkedListElement::insertBefore (LinkedListElement * pElem) inline
Definition at line 63 of file LinkedList.h.
     {
         pElem->iNext = this;
         pElem->iPrev = iPrev;
         iPrev->iNext = pElem;
         iPrev = pElem;
     }
References iNext, and iPrev.
Referenced by LinkedListHead::insertLast().
isInList()
bool LinkedListElement::isInList () const inline
Definition at line 40 of file LinkedList.h.
 { return (iNext != nullptr && iPrev != nullptr); }
References iNext, and iPrev.
Referenced by delink(), and LinkedListHead::isEmpty().
next() [1/2]
LinkedListElement* LinkedListElement::next () inline
Definition at line 42 of file LinkedList.h.
 { return hasNext() ? iNext : nullptr; }
References hasNext(), and iNext.
Referenced by LinkedListHead::getSize(), and Reference< TO, FROM >::next().
next() [2/2]
LinkedListElement const* LinkedListElement::next () const inline
Definition at line 43 of file LinkedList.h.
 { return hasNext() ? iNext : nullptr; }
References hasNext(), and iNext.
nocheck_next() [1/2]
LinkedListElement* LinkedListElement::nocheck_next () inline
Definition at line 47 of file LinkedList.h.
 { return iNext; }
References iNext.
Referenced by Reference< TO, FROM >::nocheck_next().
nocheck_next() [2/2]
LinkedListElement const* LinkedListElement::nocheck_next () const inline
Definition at line 48 of file LinkedList.h.
 { return iNext; }
References iNext.
nocheck_prev() [1/2]
LinkedListElement* LinkedListElement::nocheck_prev () inline
Definition at line 49 of file LinkedList.h.
 { return iPrev; }
References iPrev.
Referenced by Reference< TO, FROM >::nocheck_prev().
nocheck_prev() [2/2]
LinkedListElement const* LinkedListElement::nocheck_prev () const inline
Definition at line 50 of file LinkedList.h.
 { return iPrev; }
References iPrev.
prev() [1/2]
LinkedListElement* LinkedListElement::prev () inline
Definition at line 44 of file LinkedList.h.
 { return hasPrev() ? iPrev : nullptr; }
References hasPrev(), and iPrev.
Referenced by Reference< TO, FROM >::prev().
prev() [2/2]
LinkedListElement const* LinkedListElement::prev () const inline
Definition at line 45 of file LinkedList.h.
 { return hasPrev() ? iPrev : nullptr; }
References hasPrev(), and iPrev.
Friends And Related Function Documentation
LinkedListHead
friend class LinkedListHead friend
Definition at line 30 of file LinkedList.h.
Member Data Documentation
iNext
LinkedListElement* LinkedListElement::iNext private
Definition at line 32 of file LinkedList.h.
Referenced by delink(), LinkedListHead::getFirst(), hasNext(), insertAfter(), insertBefore(), LinkedListHead::isEmpty(), isInList(), LinkedListHead::LinkedListHead(), next(), and nocheck_next().
iPrev
LinkedListElement* LinkedListElement::iPrev private
Definition at line 33 of file LinkedList.h.
Referenced by delink(), LinkedListHead::getLast(), hasPrev(), insertAfter(), insertBefore(), isInList(), LinkedListHead::LinkedListHead(), nocheck_prev(), and prev().
The documentation for this class was generated from the following file:
src/common/Dynamic/LinkedList.h