Azerotcore-wotlk: anonymous_namespace{Recast.cpp} Namespace Reference
anonymous_namespace{Recast.cpp} Namespace Reference
Functions
template<typename T >
T * rcNew (rcAllocHint hint)
template<typename T >
void rcDelete (T *ptr)
Function Documentation
rcDelete()
template<typename T > void anonymous_namespace{Recast.cpp}::rcDelete (T * ptr)
Destroys and frees an object allocated with rcNew.
Parameters
[in] ptr The object pointer to delete.
Definition at line 45 of file Recast.cpp.
                       {
     if (ptr) {
         ptr->~T();
         rcFree((void*)ptr);
     }
 }
References ptr(), and rcFree().
Referenced by rcFreeCompactHeightfield(), rcFreeContourSet(), rcFreeHeightField(), rcFreeHeightfieldLayerSet(), and rcFreePolyMesh().
rcNew()
template<typename T > T* anonymous_namespace{Recast.cpp}::rcNew (rcAllocHint hint)
Allocates and constructs an object of the given type, returning a pointer. TODO: Support constructor args.
Parameters
[in] hint Hint to the allocator.
Definition at line 36 of file Recast.cpp.
{
     T* ptr = (T*)rcAlloc(sizeof(T), hint);
     ::new(rcNewTag(), (void*)ptr) T();
     return ptr;
 }
References ptr(), and rcAlloc().