Azerotcore-wotlk: deps/g3dlite/include/G3D/networkHelpers.h File Reference
networkHelpers.h File Reference
#include <cstring>
#include <stdlib.h>
#include <time.h>
Functions
static std::string socketErrorCode (int code)
static std::string socketErrorCode ()
Function Documentation
socketErrorCode() [1/2]
static std::string socketErrorCode () static
Definition at line 80 of file networkHelpers.h.
{
         return socketErrorCode(GetLastError());
     }
References socketErrorCode().
socketErrorCode() [2/2]
static std::string socketErrorCode (int code) static
Definition at line 64 of file networkHelpers.h.
{
         LPTSTR formatMsg = NULL;
         FormatMessage(FORMAT_MESSAGE_ALLOCATE_BUFFER |
                       FORMAT_MESSAGE_IGNORE_INSERTS |
                       FORMAT_MESSAGE_FROM_SYSTEM,
                         NULL,
                         code,
                         0,
                         (LPTSTR)&formatMsg,
                         0,
                         NULL);
         return G3D::format("CODE %d: %s\n", code, formatMsg);
     }
References G3D::format(), and NULL.
Referenced by G3D::NetworkDevice::bind(), G3D::increaseBufferSize(), G3D::LightweightConduit::LightweightConduit(), G3D::NetListener::NetListener(), G3D::readWaiting(), G3D::ReliableConduit::receiveHeader(), G3D::ReliableConduit::receiveIntoBuffer(), G3D::ReliableConduit::ReliableConduit(), G3D::ReliableConduit::sendBuffer(), G3D::LightweightConduit::sendBuffer(), socketErrorCode(), G3D::NetListener::waitForConnection(), and G3D::LightweightConduit::waitingMessageType().