Azerotcore-wotlk: go_celestial_planetarium_access::go_celestial_planetarium_accessAI Struct Reference
go_celestial_planetarium_access::go_celestial_planetarium_accessAI Struct Reference
Public Member Functions
go_celestial_planetarium_accessAI (GameObject *go)
bool GossipHello (Player *player, bool) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32)
virtual ObjectGuid GetGUID (int32) const
virtual bool GossipSelect (Player *, uint32, uint32)
virtual bool GossipSelectCode (Player *, uint32, uint32, char const *)
virtual bool QuestAccept (Player *, Quest const *)
virtual bool QuestReward (Player *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *)
virtual void Destroyed (Player *, uint32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void OnGameEvent (bool, uint16)
virtual void OnStateChanged (uint32, Unit *)
virtual void EventInform (uint32)
virtual void SpellHit (Unit *, const SpellInfo *)
virtual bool CanBeSeen (Player const *)
Public Attributes
EventMap events
bool _locked
Additional Inherited Members
Static Public Member Functions inherited from GameObjectAI
static int Permissible (GameObject const *go)
Protected Attributes inherited from GameObjectAI
GameObject *const me
Detailed Description
Definition at line 1091 of file boss_algalon_the_observer.cpp.
Constructor & Destructor Documentation
go_celestial_planetarium_accessAI()
go_celestial_planetarium_access::go_celestial_planetarium_accessAI::go_celestial_planetarium_accessAI (GameObject * go) inline
Definition at line 1093 of file boss_algalon_the_observer.cpp.
                                                           : GameObjectAI(go)
         {
             _locked = false;
         }
References _locked.
Member Function Documentation
GossipHello()
bool go_celestial_planetarium_access::go_celestial_planetarium_accessAI::GossipHello (Player * player, bool) inline override virtual
Reimplemented from GameObjectAI.
Definition at line 1101 of file boss_algalon_the_observer.cpp.
         {
             bool hasKey = true;
             if (LockEntry const* lock = sLockStore.LookupEntry(me->GetGOInfo()->goober.lockId))
             {
                 hasKey = false;
                 for (uint32 i = 0; i < MAX_LOCK_CASE; ++i)
                 {
                     if (!lock->Index[i])
                         continue;
                     if (player->HasItemCount(lock->Index[i]))
                     {
                         hasKey = true;
                         break;
                     }
                 }
             }
             if (!hasKey)
                 return false;
             if (_locked)
                 return false;
             _locked = true;
             // Start Algalon event
             me->SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_IN_USE);
             events.ScheduleEvent(EVENT_DESPAWN_CONSOLE, 5000);
             if (Creature* brann = me->SummonCreature(NPC_BRANN_BRONZBEARD_ALG, BrannIntroSpawnPos))
                 brann->AI()->DoAction(ACTION_START_INTRO);
             if (InstanceScript* instance = me->GetInstanceScript())
             {
                 instance->SetData(DATA_ALGALON_SUMMON_STATE, 1);
                 if (GameObject* sigil = ObjectAccessor::GetGameObject(*me, instance->GetGuidData(GO_DOODAD_UL_SIGILDOOR_01)))
                     sigil->SetGoState(GO_STATE_ACTIVE);
                 if (GameObject* sigil = ObjectAccessor::GetGameObject(*me, instance->GetGuidData(GO_DOODAD_UL_SIGILDOOR_02)))
                     sigil->SetGoState(GO_STATE_ACTIVE);
             }
             return false;
         }
References _locked, ACTION_START_INTRO, BrannIntroSpawnPos, DATA_ALGALON_SUMMON_STATE, EVENT_DESPAWN_CONSOLE, GAMEOBJECT_FLAGS, ObjectAccessor::GetGameObject(), GameObject::GetGOInfo(), WorldObject::GetInstanceScript(), GO_DOODAD_UL_SIGILDOOR_01, GO_DOODAD_UL_SIGILDOOR_02, GO_FLAG_IN_USE, GO_STATE_ACTIVE, GameObjectTemplate::goober, Player::HasItemCount(), MAX_LOCK_CASE, GameObjectAI::me, NPC_BRANN_BRONZBEARD_ALG, Object::SetFlag(), sLockStore, and WorldObject::SummonCreature().
UpdateAI()
void go_celestial_planetarium_access::go_celestial_planetarium_accessAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from GameObjectAI.
Definition at line 1145 of file boss_algalon_the_observer.cpp.
         {
             if (events.Empty())
                 return;
             events.Update(diff);
             switch (events.ExecuteEvent())
             {
                 case EVENT_DESPAWN_CONSOLE:
                     me->Delete();
                     break;
             }
         }
References GameObject::Delete(), diff(), EVENT_DESPAWN_CONSOLE, and GameObjectAI::me.
Member Data Documentation
_locked
bool go_celestial_planetarium_access::go_celestial_planetarium_accessAI::_locked
Definition at line 1099 of file boss_algalon_the_observer.cpp.
Referenced by go_celestial_planetarium_accessAI(), and GossipHello().
events
EventMap go_celestial_planetarium_access::go_celestial_planetarium_accessAI::events
Definition at line 1098 of file boss_algalon_the_observer.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_algalon_the_observer.cpp