Azerotcore-wotlk: G3D::Box Class Reference
G3D::Box Class Reference
An arbitrary (oriented) 3D box, useful as a bounding box.
#include <Box.h>
Public Member Functions
Box ()
Box (const Any &a)
Box (const Vector3 &min, const Vector3 &max)
Box (const Vector3 &osMin, const Vector3 &osMax, const CoordinateFrame &frame)
Box (class BinaryInput &b)
Box (const class AABox &b)
Box (const Point3 &p)
Any toAny () const
void serialize (class BinaryOutput &b) const
void deserialize (class BinaryInput &b)
CoordinateFrame localFrame () const
void getLocalFrame (CoordinateFrame &frame) const
Box operator* (float f) const
Vector3 center () const
Vector3 corner (int i) const
Vector3 axis (int a) const
float extent (int a) const
Vector3 extent () const
void getFaceCorners (int f, Vector3 &v0, Vector3 &v1, Vector3 &v2, Vector3 &v3) const
bool culledBy (const Array< Plane > &plane, int32 &cullingPlaneIndex, const uint32 testMask, uint32 &childMask) const
bool culledBy (const Array< Plane > &plane, int32 &cullingPlaneIndex=dummy, const uint32 testMask=-1) const
bool contains (const Vector3 &point) const
float area () const
float volume () const
void getRandomSurfacePoint (Vector3 &P, Vector3 &N=Vector3::ignore()) const
Vector3 randomInteriorPoint () const
void getBounds (class AABox &) const
bool isFinite () const
Static Public Member Functions
static Box inf ()
Private Member Functions
void init (const Vector3 &min, const Vector3 &max)
Private Attributes
Vector3 _edgeVector [3]
Point3 _center
float _area
float _volume
Static Private Attributes
static int32 dummy = 0
Friends
class CoordinateFrame
Detailed Description
An arbitrary (oriented) 3D box, useful as a bounding box.
To construct a box from a coordinate frame, center and extent, use the idiom: Box box = cframe.toObjectSpace(Box(center - extent/2, center + extent/2));
Definition at line 35 of file Box.h.
Constructor & Destructor Documentation
Box() [1/7]
G3D::Box::Box ()
Definition at line 21 of file Box.cpp.
          : _area(0), _volume(0) {
 }
Referenced by Box(), and inf().
Box() [2/7]
G3D::Box::Box (const Any & a) explicit
Definition at line 57 of file Box.cpp.
                      {
     if (a.name() == "Box::inf") {
         *this = Box::inf();
     } else {
         a.verifyName("Box", "AABox", "Point3");
         if (a.name() == "Point3") {
             *this = Box(Point3(a));
         } else if (a.size() == 1) {
             // Single point
             *this = Box(Point3(a[0]));
         } else if (a.size() == 2) {
             *this = Box(Point3(a[0]), Point3(a[1]));
         } else {
             // Oriented box
             a.verifySize(2);
             a.verifyName("Box");
             *this = Box(Point3(a[0]), Point3(a[1]), CFrame(a[2]));
         }
     }
 }
References mpq::a, Box(), and inf().
Box() [3/7]
G3D::Box::Box (const Vector3 & min, const Vector3 & max)
Constructs a box from two opposite corners.
Definition at line 25 of file Box.cpp.
{
     init(min.min(max), min.max(max));
 }
References init(), G3D::max(), and G3D::min().
Box() [4/7]
G3D::Box::Box (const Vector3 & osMin, const Vector3 & osMax, const CoordinateFrame & frame)
Box() [5/7]
G3D::Box::Box (class BinaryInput & b)
Definition at line 52 of file Box.cpp.
{
     deserialize(b);
 }
References b, and deserialize().
Box() [6/7]
G3D::Box::Box (const class AABox & b)
Box() [7/7]
G3D::Box::Box (const Point3 & p) explicit
Definition at line 32 of file Box.cpp.
{
     init(min, min);
 }
References init(), and G3D::min().
Member Function Documentation
area()
float G3D::Box::area () const
Definition at line 222 of file Box.cpp.
                       {
     return _area;
 }
References _area.
axis()
Vector3 G3D::Box::axis (int a) const inline
Unit length.
Definition at line 137 of file Box.h.
{
         debugAssert(a < 3);
         return _edgeVector[a].direction();
     }
References _edgeVector, mpq::a, debugAssert, and G3D::Vector3::direction().
Referenced by G3D::CollisionDetection::fillSolidBoxSolidBoxInfo(), getLocalFrame(), getRandomSurfacePoint(), G3D::CollisionDetection::penetrationDepthForFixedBoxFixedBox(), and G3D::CollisionDetection::separatingAxisForSolidBoxSolidBox().
center()
Vector3 G3D::Box::center () const inline
Returns the centroid of the box.
Definition at line 103 of file Box.h.
{
         return _center;
     }
References _center.
Referenced by G3D::CollisionDetection::fillSolidBoxSolidBoxInfo(), and G3D::CollisionDetection::penetrationDepthForFixedBoxFixedBox().
contains()
bool G3D::Box::contains (const Vector3 & point) const
Definition at line 385 of file Box.cpp.
{
     // Form axes from three edges, transform the point into that
     // space, and perform 3 interval tests
     // TODO: Write in a more intuitive way. I left it as it was before after figuring it out, but
     // this should make no sense to someone who is just starting to read this code.
     const Vector3& u = _edgeVector[2];
     const Vector3& v = _edgeVector[1];
     const Vector3& w = _edgeVector[0];
     Matrix3 M = Matrix3(u.x, v.x, w.x,
                         u.y, v.y, w.y,
                         u.z, v.z, w.z);
     // M^-1 * (point - _corner[0]) = point in unit cube's object space
     // compute the inverse of M
     Vector3 osPoint = M.inverse() * (point - corner(0));
     return
         (osPoint.x >= 0) &&
         (osPoint.y >= 0) &&
         (osPoint.z >= 0) &&
         (osPoint.x <= 1) &&
         (osPoint.y <= 1) &&
         (osPoint.z <= 1);
 }
References _edgeVector, corner(), G3D::Matrix3::inverse(), G3D::Vector3::x, G3D::Vector3::y, and G3D::Vector3::z.
Referenced by G3D::CollisionDetection::fixedSolidSphereIntersectsFixedSolidBox(), and G3D::Ray::intersectionTime().
corner()
Vector3 G3D::Box::corner (int i) const
 \htmlonly
<PRE>
2--------3
/ : /| / : / | 6-----—7 | | : | | | 0....|..1 | / | / |/ |/ 4-----—5
y
^ | |-->x z/
</PRE>
\endhtmlonly
Definition at line 189 of file Box.cpp.
{
     debugAssert(i < 8);
     // The corner forms a bit mask (xyz), where a one indicates we should
     // add half of the corresponding edge vector from center, and a zero indicates
     // we should subtract it. Note:
     // 1 = 001
     // 2 = 010
     // 4 = 100
     //
     // The following bit-hacky code shows this directly:
     // return _center + ((_edgeVector[0] * ((i&1) - 0.5) +
     //                  _edgeVector[1] * (((i>>1)&1) - 0.5) +
     //                  _edgeVector[2] * (((i>>2)&1) - 0.5)));
     // This method is implemented as a swtich statement due to being marginally faster than the bit-hack method
     // Also, the _center + 0.5f * (...) is repeated every time for similarly speed-based reasons.
     switch(i) {
         case 0:  return _center + (0.5f * (-_edgeVector[0]  - _edgeVector[1] - _edgeVector[2]));
         case 1:  return _center + (0.5f * ( _edgeVector[0]  - _edgeVector[1] - _edgeVector[2]));
         case 2:  return _center + (0.5f * (-_edgeVector[0]  + _edgeVector[1] - _edgeVector[2]));
         case 3:  return _center + (0.5f * ( _edgeVector[0]  + _edgeVector[1] - _edgeVector[2]));
         case 4:  return _center + (0.5f * (-_edgeVector[0]  - _edgeVector[1] + _edgeVector[2]));
         case 5:  return _center + (0.5f * ( _edgeVector[0]  - _edgeVector[1] + _edgeVector[2]));
         case 6:  return _center + (0.5f * (-_edgeVector[0]  + _edgeVector[1] + _edgeVector[2]));
         default: return _center + (0.5f * ( _edgeVector[0]  + _edgeVector[1] + _edgeVector[2]));//case 7
     }
 }
References _center, _edgeVector, and debugAssert.
Referenced by contains(), getBounds(), getFaceCorners(), G3D::CollisionDetection::penetrationDepthForFixedBoxFixedBox(), and G3D::CollisionDetection::penetrationDepthForFixedBoxFixedPlane().
culledBy() [1/2]
bool G3D::Box::culledBy (const Array< Plane > & plane, int32 & cullingPlaneIndex, const uint32 testMask, uint32 & childMask) const
See AABox::culledBy
culledBy() [2/2]
bool G3D::Box::culledBy (const Array< Plane > & plane, int32 & cullingPlaneIndex = dummy, const uint32 testMask = -1) const
Conservative culling test that does not produce a mask for children.
deserialize()
void G3D::Box::deserialize (class BinaryInput & b)
Definition at line 129 of file Box.cpp.
{
     int i;
     for (i = 0; i < 3; ++i) {
         _edgeVector[i].deserialize(b);
     }
     _center.deserialize(b);
     float extent0 = extent(0);
     float extent1 = extent(1);
     float extent2 = extent(2);
     _volume = extent0 * extent1 * extent2;
     _area = 2 *
         (extent0 * extent1 +
          extent1 * extent2 +
          extent2 * extent0);
 }
References _area, _center, _edgeVector, _volume, b, G3D::Vector3::deserialize(), and extent().
Referenced by Box().
extent() [1/2]
Vector3 G3D::Box::extent () const inline
Definition at line 151 of file Box.h.
{
         return Vector3(_edgeVector[0].length(), _edgeVector[1].length(), _edgeVector[2].length());
     }
References _edgeVector, and G3D::length().
Referenced by deserialize(), getRandomSurfacePoint(), and init().
extent() [2/2]
float G3D::Box::extent (int a) const inline
Distance from corner(0) to the next corner along the box's local axis a.
Definition at line 146 of file Box.h.
{
         debugAssert(a < 3);
         return _edgeVector[a].length();
     }
References _edgeVector, mpq::a, debugAssert, and G3D::Vector3::length().
Referenced by G3D::CollisionDetection::fillSolidBoxSolidBoxInfo(), and G3D::CollisionDetection::penetrationDepthForFixedSphereFixedBox().
getBounds()
void G3D::Box::getBounds (class AABox & aabb) const
Definition at line 463 of file Box.cpp.
{
     debugAssert(! _edgeVector[0].isNaN());
     debugAssert(! _center.isNaN());
     aabb = AABox::empty();
     for (int i = 0; i < 8; ++i) {
         aabb.merge(corner(i));
     }
 }
References _center, _edgeVector, corner(), debugAssert, G3D::AABox::empty(), G3D::Vector3::isNaN(), G3D::isNaN(), and G3D::AABox::merge().
Referenced by toAny().
getFaceCorners()
void G3D::Box::getFaceCorners (int f, Vector3 & v0, Vector3 & v1, Vector3 & v2, Vector3 & v3) const
 Returns the four corners of a face (0 <= f < 6).
 The corners are returned to form a clockwise quad facing outwards.
  +--------+
 / :      /|
/  :     / |
+-----—+ | | : | | | +....|..+ | / | / |/ |/ +-----—+
y
^ | |-->x z/
Faces are in the following order: 0: -Z 1: X 2: Z 3: Y 4: -X 5: -Y
Definition at line 248 of file Box.cpp.
{
     switch (f) {
     case 0:
         v0 = corner(0); v1 = corner(2); v2 = corner(3); v3 = corner(1);
         break;
     case 1:
         v0 = corner(1); v1 = corner(3); v2 = corner(7); v3 = corner(5);
         break;
     case 2:
         v0 = corner(6); v1 = corner(4); v2 = corner(5); v3 = corner(7);
         break;
     case 3:
         v0 = corner(3); v1 = corner(2); v2 = corner(6); v3 = corner(7);
         break;
     case 4:
         v0 = corner(2); v1 = corner(0); v2 = corner(4); v3 = corner(6);
         break;
     case 5:
         v0 = corner(1); v1 = corner(5); v2 = corner(4); v3 = corner(0);
         break;
     default:
         debugAssert((f >= 0) && (f < 6));
     }
 }
References corner(), debugAssert, and f().
Referenced by G3D::CollisionDetection::collisionTimeForMovingPointFixedBox(), G3D::CollisionDetection::collisionTimeForMovingSphereFixedBox(), and G3D::CollisionDetection::fixedSolidSphereIntersectsFixedSolidBox().
getLocalFrame()
void G3D::Box::getLocalFrame (CoordinateFrame & frame) const
See also
localFrame
Definition at line 227 of file Box.cpp.
{
     const Vector3& axis0 = axis(0);
     const Vector3& axis1 = axis(1);
     const Vector3& axis2 = axis(2);
     frame.rotation = Matrix3(
         axis0[0], axis1[0], axis2[0],
         axis0[1], axis1[1], axis2[1],
         axis0[2], axis1[2], axis2[2]);
     frame.translation = _center;
 }
References _center, axis(), G3D::CoordinateFrame::rotation, and G3D::CoordinateFrame::translation.
Referenced by localFrame(), G3D::CollisionDetection::penetrationDepthForFixedSphereFixedBox(), and toAny().
getRandomSurfacePoint()
void G3D::Box::getRandomSurfacePoint (Vector3 & P, Vector3 & N = Vector3::ignore()) const
Definition at line 416 of file Box.cpp.
{
     float aXY = extent(0) * extent(1);
     float aYZ = extent(1) * extent(2);
     float aZX = extent(2) * extent(0);
     float r = (float)uniformRandom(0, aXY + aYZ + aZX);
     // Choose evenly between positive and negative face planes
     float d = (uniformRandom(0, 1) < 0.5f) ? -1.0f : 1.0f;
     // The probability of choosing a given face is proportional to
     // its area.
     if (r < aXY) {
         P = _edgeVector[0] * (float)uniformRandom(-0.5, 0.5) +
             _edgeVector[1] * (float)uniformRandom(-0.5, 0.5) +
             _center + _edgeVector[2] * d  * 0.5f;
         N = axis(2) * d;
     } else if (r < aYZ) {
         P = _edgeVector[1] * (float)uniformRandom(-0.5, 0.5) +
             _edgeVector[2] * (float)uniformRandom(-0.5, 0.5) +
             _center + _edgeVector[0] * d  * 0.5f;
         N = axis(0) * d;
     } else {
         P = _edgeVector[2] * (float)uniformRandom(-0.5, 0.5) +
             _edgeVector[0] *(float) uniformRandom(-0.5, 0.5) +
             _center + _edgeVector[1] * d * 0.5f;
         N = axis(1) * d;
     }
 }
References _center, _edgeVector, axis(), mpq::d, extent(), P, and G3D::uniformRandom().
inf()
Box G3D::Box::inf () static
Definition at line 458 of file Box.cpp.
              {
     return Box(-Vector3::inf(), Vector3::inf());
 }
References Box(), and G3D::Vector3::inf().
Referenced by Box().
init()
void G3D::Box::init (const Vector3 & min, const Vector3 & max) private
Definition at line 148 of file Box.cpp.
{
     debugAssert(
         (min.x <= max.x) &&
         (min.y <= max.y) &&
         (min.z <= max.z));
     _center = (max + min) * 0.5f;
     Vector3 bounds = Vector3(max.x - min.x, max.y - min.y, max.z - min.z);
     _edgeVector[0] = Vector3(bounds.x, 0, 0);
     _edgeVector[1] = Vector3(0, bounds.y, 0);
     _edgeVector[2] = Vector3(0, 0, bounds.z);
     bool finiteExtent = true;
     for (int i = 0; i < 3; ++i) {
         if (! G3D::isFinite(extent(i))) {
             finiteExtent = false;
             // If the extent is infinite along an axis, make the center zero to avoid NaNs
             _center[i] = 0.0f;
         }
     }
     if (finiteExtent) {
         _volume = bounds.x * bounds.y * bounds.z;
     } else {
         _volume = G3D::finf();
     }
     debugAssert(! _edgeVector[0].isNaN());
     _area = 2 *
         (bounds.x * bounds.y +
          bounds.y * bounds.z +
          bounds.z * bounds.x);
 }
References _area, _center, _edgeVector, _volume, debugAssert, extent(), G3D::finf(), G3D::isFinite(), G3D::isNaN(), G3D::max(), G3D::min(), G3D::Vector3::x, G3D::Vector3::y, and G3D::Vector3::z.
Referenced by Box().
isFinite()
bool G3D::Box::isFinite () const inline
Definition at line 228 of file Box.h.
{
         return G3D::isFinite(_volume);
     }
References _volume, and G3D::isFinite().
Referenced by toAny().
localFrame()
CoordinateFrame G3D::Box::localFrame () const
Returns the object to world transformation for this box, where the origin is the center of the box. localFrame().worldToObject(...) takes objects into the space where the box axes are (1,0,0), (0,1,0), (0,0,1). Note that there is no scaling in this transformation.
Definition at line 241 of file Box.cpp.
{
     CoordinateFrame out;
     getLocalFrame(out);
     return out;
 }
References getLocalFrame().
operator*()
Box G3D::Box::operator* (float f) const
Definition at line 104 of file Box.cpp.
{
     Box b;
     for (int i = 0; i < 3; ++i) {
         b._edgeVector[i] = _edgeVector[i] * f;
         b._center = _center * f;
         b._area = _area * square(f * f);
         b._volume = _area * (f * f * f);
     }
     return b;
 }
References _area, _center, _edgeVector, b, f(), and G3D::square().
randomInteriorPoint()
Vector3 G3D::Box::randomInteriorPoint () const
Uniformly distributed on the interior (includes surface)
Definition at line 447 of file Box.cpp.
{
     Vector3 sum = _center;
     for (int a = 0; a < 3; ++a) {
         sum += _edgeVector[a] * (float)uniformRandom(-0.5, 0.5);
     }
     return sum;
 }
References _center, _edgeVector, mpq::a, and G3D::uniformRandom().
serialize()
void G3D::Box::serialize (class BinaryOutput & b) const
Definition at line 118 of file Box.cpp.
{
     int i;
     for (i = 0; i < 3; ++i) {
         _edgeVector[i].serialize(b);
     }
     _center.serialize(b);
     // Other state can be reconstructed
 }
References _center, _edgeVector, b, and G3D::Vector3::serialize().
toAny()
Any G3D::Box::toAny () const
Definition at line 80 of file Box.cpp.
                      {
     if (! isFinite()) {
         return Any(Any::ARRAY, "Box::inf");
     } else {
         CFrame c;
         getLocalFrame(c);
         if (c.rotation == Matrix3::identity()) {
             // Aligned box
             AABox b;
             getBounds(b);
             return b.toAny();
         } else {
             // Oriented box
             Any a(Any::ARRAY, "Box");
             AABox b;
             c.toObjectSpace(*this).getBounds(b);
             a.append(b.low(), b.high(), c);
             return a;
         }
     }
 }
References mpq::a, G3D::Any::ARRAY, b, mpq::c, getBounds(), getLocalFrame(), G3D::Matrix3::identity(), and isFinite().
volume()
float G3D::Box::volume () const
Definition at line 217 of file Box.cpp.
{
     return _volume;
 }
References _volume.
Friends And Related Function Documentation
CoordinateFrame
friend class CoordinateFrame friend
Definition at line 40 of file Box.h.
Member Data Documentation
_area
float G3D::Box::_area private
Definition at line 49 of file Box.h.
Referenced by area(), deserialize(), init(), and operator*().
_center
Point3 G3D::Box::_center private
Definition at line 47 of file Box.h.
Referenced by center(), corner(), deserialize(), getBounds(), getLocalFrame(), getRandomSurfacePoint(), init(), operator*(), randomInteriorPoint(), and serialize().
_edgeVector
Vector3 G3D::Box::_edgeVector[3] private
Axes with length equal to the 4 edges that run along each of them
Definition at line 45 of file Box.h.
Referenced by axis(), contains(), corner(), deserialize(), extent(), getBounds(), getRandomSurfacePoint(), init(), operator*(), randomInteriorPoint(), and serialize().
_volume
float G3D::Box::_volume private
Definition at line 51 of file Box.h.
Referenced by deserialize(), init(), isFinite(), and volume().
dummy
int G3D::Box::dummy = 0 static private
Definition at line 38 of file Box.h.
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/Box.h
deps/g3dlite/source/Box.cpp