Azerotcore-wotlk: AreaTrigger_at_area_52_entrance Class Reference
AreaTrigger_at_area_52_entrance Class Reference
Public Member Functions
AreaTrigger_at_area_52_entrance ()
bool OnTrigger (Player *player, AreaTrigger const *trigger) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Private Attributes
std::map< uint32, time_t > _triggerTimes
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 428 of file areatrigger_scripts.cpp.
Constructor & Destructor Documentation
AreaTrigger_at_area_52_entrance()
AreaTrigger_at_area_52_entrance::AreaTrigger_at_area_52_entrance () inline
Definition at line 431 of file areatrigger_scripts.cpp.
                                       : AreaTriggerScript("at_area_52_entrance")
     {
         _triggerTimes[AT_AREA_52_SOUTH] = _triggerTimes[AT_AREA_52_NORTH] = _triggerTimes[AT_AREA_52_WEST] = _triggerTimes[AT_AREA_52_EAST] = 0;
     }
References _triggerTimes, AT_AREA_52_EAST, AT_AREA_52_NORTH, AT_AREA_52_SOUTH, and AT_AREA_52_WEST.
Member Function Documentation
OnTrigger()
bool AreaTrigger_at_area_52_entrance::OnTrigger (Player * player, AreaTrigger const * trigger) inline override virtual
Reimplemented from AreaTriggerScript.
Definition at line 436 of file areatrigger_scripts.cpp.
     {
         float x = 0.0f, y = 0.0f, z = 0.0f;
         if (!player->IsAlive())
             return false;
         uint32 triggerId = trigger->entry;
         if (sWorld->GetGameTime() - _triggerTimes[trigger->entry] < SUMMON_COOLDOWN)
             return false;
         switch (triggerId)
         {
             case AT_AREA_52_EAST:
                 x = 3044.176f;
                 y = 3610.692f;
                 z = 143.61f;
                 break;
             case AT_AREA_52_NORTH:
                 x = 3114.87f;
                 y = 3687.619f;
                 z = 143.62f;
                 break;
             case AT_AREA_52_WEST:
                 x = 3017.79f;
                 y = 3746.806f;
                 z = 144.27f;
                 break;
             case AT_AREA_52_SOUTH:
                 x = 2950.63f;
                 y = 3719.905f;
                 z = 143.33f;
                 break;
         }
         player->SummonCreature(NPC_SPOTLIGHT, x, y, z, 0.0f, TEMPSUMMON_TIMED_DESPAWN, 5000);
         player->AddAura(SPELL_A52_NEURALYZER, player);
         _triggerTimes[trigger->entry] = sWorld->GetGameTime();
         return false;
     }
References _triggerTimes, Unit::AddAura(), AT_AREA_52_EAST, AT_AREA_52_NORTH, AT_AREA_52_SOUTH, AT_AREA_52_WEST, AreaTrigger::entry, Unit::IsAlive(), NPC_SPOTLIGHT, SPELL_A52_NEURALYZER, SUMMON_COOLDOWN, WorldObject::SummonCreature(), sWorld, TEMPSUMMON_TIMED_DESPAWN, G3D::x, G3D::y, and G3D::z.
Member Data Documentation
_triggerTimes
std::map<uint32, time_t> AreaTrigger_at_area_52_entrance::_triggerTimes private
Definition at line 478 of file areatrigger_scripts.cpp.
Referenced by AreaTrigger_at_area_52_entrance(), and OnTrigger().
The documentation for this class was generated from the following file:
src/server/scripts/World/areatrigger_scripts.cpp