Azerotcore-wotlk: deps/mysqllite/mysys/my_lock.c File Reference
my_lock.c File Reference
#include "mysys_priv.h"
#include "mysys_err.h"
#include <errno.h>
#include <my_alarm.h>
Macros
#define MY_HOW_OFTEN_TO_ALARM ((int) my_time_to_wait_for_lock)
Functions
int my_lock (File fd, int locktype, my_off_t start, my_off_t length, myf MyFlags)
Macro Definition Documentation
MY_HOW_OFTEN_TO_ALARM
#define MY_HOW_OFTEN_TO_ALARM ((int) my_time_to_wait_for_lock)
Definition at line 20 of file my_lock.c.
Function Documentation
my_lock()
int my_lock (File fd, int locktype, my_off_t start, my_off_t length, myf MyFlags)
Definition at line 138 of file my_lock.c.
 {
 #ifdef HAVE_FCNTL
   int value;
   ALARM_VARIABLES;
 #endif
   DBUG_ENTER("my_lock");
   DBUG_PRINT("my",("fd: %d  Op: %d  start: %ld  Length: %ld  MyFlags: %d",
            fd,locktype,(long) start,(long) length,MyFlags));
   if (my_disable_locking)
     DBUG_RETURN(0);
 #if defined(_WIN32)
   {
     int timeout_sec;
     if (MyFlags & MY_DONT_WAIT)
       timeout_sec= 0;
     else
       timeout_sec= WIN_LOCK_INFINITE;
     if (win_lock(fd, locktype, start, length, timeout_sec) == 0)
       DBUG_RETURN(0);
   }
 #else
 #if defined(HAVE_FCNTL)
   {
     struct flock lock;
     lock.l_type=   (short) locktype;
     lock.l_whence= SEEK_SET;
     lock.l_start=  (off_t) start;
     lock.l_len=    (off_t) length;
     if (MyFlags & MY_DONT_WAIT)
     {
       if (fcntl(fd,F_SETLK,&lock) != -1)    /* Check if we can lock */
     DBUG_RETURN(0);         /* Ok, file locked */
       DBUG_PRINT("info",("Was locked, trying with alarm"));
       ALARM_INIT;
       while ((value=fcntl(fd,F_SETLKW,&lock)) && ! ALARM_TEST &&
          errno == EINTR)
       {         /* Setup again so we don`t miss it */
     ALARM_REINIT;
       }
       ALARM_END;
       if (value != -1)
     DBUG_RETURN(0);
       if (errno == EINTR)
     errno=EAGAIN;
     }
     else if (fcntl(fd,F_SETLKW,&lock) != -1) /* Wait until a lock */
       DBUG_RETURN(0);
   }
 #else
   if (MyFlags & MY_SEEK_NOT_DONE)
   {
     if (my_seek(fd,start,MY_SEEK_SET,MYF(MyFlags & ~MY_SEEK_NOT_DONE))
         == MY_FILEPOS_ERROR)
     {
       /*
         If an error has occured in my_seek then we will already
         have an error code in my_errno; Just return error code.
       */
       DBUG_RETURN(-1);
     }
   }
   if (lockf(fd,locktype,length) != -1)
     DBUG_RETURN(0);
 #endif /* HAVE_FCNTL */
 #endif /* HAVE_LOCKING */
   /* We got an error. We don't want EACCES errors */
   my_errno=(errno == EACCES) ? EAGAIN : errno ? errno : -1;
   if (MyFlags & MY_WME)
   {
     if (locktype == F_UNLCK)
       my_error(EE_CANTUNLOCK,MYF(ME_BELL+ME_WAITTANG),my_errno);
     else
       my_error(EE_CANTLOCK,MYF(ME_BELL+ME_WAITTANG),my_errno);
   }
   DBUG_PRINT("error",("my_errno: %d (%d)",my_errno,errno));
   DBUG_RETURN(-1);
 } /* my_lock */
References ALARM_END, ALARM_INIT, ALARM_REINIT, ALARM_TEST, ALARM_VARIABLES, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_CANTLOCK, EE_CANTUNLOCK, errno, G3D::length(), ME_BELL, ME_WAITTANG, my_disable_locking, MY_DONT_WAIT, my_errno, my_error(), MY_FILEPOS_ERROR, my_seek(), MY_SEEK_NOT_DONE, MY_SEEK_SET, MY_WME, MYF, mpq::off_t, and SEEK_SET.