Azerotcore-wotlk: NPCStaveQuestAI Struct Reference
NPCStaveQuestAI Struct Reference
#include <npc_stave_of_ancients.h>
Public Member Functions
NPCStaveQuestAI (Creature *creature)
uint32 GetFormEntry (std::string)
bool InNormalForm ()
void RevealForm ()
void StorePlayerGUID ()
Player * GetGossipPlayer ()
bool IsAllowedEntry (uint32)
bool UnitIsUnfair (Unit *unit)
bool IsFairFight ()
bool ValidThreatlist ()
void SetHomePosition ()
void PrepareForEncounter ()
void ClearLootIfUnfair (Unit *killer)
bool PlayerEligibleForReward (Unit *killer)
void StoreAttackerGuidValue (Unit *attacker)
bool QuestIncomplete (Unit *unit, uint32 questItem)
void ResetState (uint32)
void EvadeOnFeignDeath ()
virtual void AttackStart (Unit *)
virtual void AttackedBy (Unit *)
virtual void JustDied (Unit *)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
ObjectGuid gossipPlayerGUID
ObjectGuid playerGUID
bool encounterStarted
ThreatContainer::StorageType const & threatList = me->getThreatMgr().getThreatList()
std::map< int, int > entryKeys
std::map< int, std::map< std::string, int > > entryList
std::vector< uint64 > attackerGuids
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 134 of file npc_stave_of_ancients.h.
Constructor & Destructor Documentation
NPCStaveQuestAI()
NPCStaveQuestAI::NPCStaveQuestAI (Creature * creature) inline
Definition at line 136 of file npc_stave_of_ancients.h.
 : ScriptedAI(creature) { }
Member Function Documentation
AttackedBy()
void NPCStaveQuestAI::AttackedBy (Unit * attacker) virtual
Reimplemented from CreatureAI.
Definition at line 260 of file npc_stave_of_ancients.cpp.
 {
     StoreAttackerGuidValue(attacker);
 }
References StoreAttackerGuidValue().
AttackStart()
void NPCStaveQuestAI::AttackStart (Unit * target) virtual
Reimplemented from ScriptedAI.
Definition at line 250 of file npc_stave_of_ancients.cpp.
 {
     if (playerGUID.IsEmpty() && !InNormalForm())
     {
         StorePlayerGUID();
     }
     ScriptedAI::AttackStart(target);
 }
References ScriptedAI::AttackStart(), InNormalForm(), ObjectGuid::IsEmpty(), playerGUID, and StorePlayerGUID().
ClearLootIfUnfair()
void NPCStaveQuestAI::ClearLootIfUnfair (Unit * killer)
Definition at line 162 of file npc_stave_of_ancients.cpp.
 {
     // Remove loot if there is more than 1 attacker or Player doesn't have the quest
     // this should prevent party kills and looting the quest item without putting any effort
     if (attackerGuids.size() > 1 || !PlayerEligibleForReward(killer))
     {
         me->loot.clear();
         return;
     }
 }
References attackerGuids, Loot::clear(), Creature::loot, ScriptedAI::me, and PlayerEligibleForReward().
Referenced by JustDied().
EvadeOnFeignDeath()
void NPCStaveQuestAI::EvadeOnFeignDeath ()
Definition at line 241 of file npc_stave_of_ancients.cpp.
 {
     Player* player = ObjectAccessor::GetPlayer(*me, playerGUID);
     if (player && player->HasAura(SPELL_FEIGN_DEATH))
     {
         EnterEvadeMode();
     }
 }
References CreatureAI::EnterEvadeMode(), ObjectAccessor::GetPlayer(), Unit::HasAura(), ScriptedAI::me, playerGUID, and SPELL_FEIGN_DEATH.
Referenced by npc_artorius::npc_artoriusAI::UpdateAI(), npc_simone::npc_simoneAI::UpdateAI(), npc_nelson::npc_nelsonAI::UpdateAI(), npc_franklin::npc_franklinAI::UpdateAI(), and npc_precious::npc_preciousAI::UpdateAI().
GetFormEntry()
uint32 NPCStaveQuestAI::GetFormEntry (std::string type)
Definition at line 26 of file npc_stave_of_ancients.cpp.
 {
     uint32 currentEntry = me->GetEntry();
     uint32 entryKey = entryKeys[currentEntry];
     return entryList[entryKey][type];
 }
References entryKeys, entryList, Object::GetEntry(), and ScriptedAI::me.
Referenced by InNormalForm(), and RevealForm().
GetGossipPlayer()
Player * NPCStaveQuestAI::GetGossipPlayer ()
Definition at line 64 of file npc_stave_of_ancients.cpp.
 {
     return ObjectAccessor::GetPlayer(*me, gossipPlayerGUID);
 }
References ObjectAccessor::GetPlayer(), gossipPlayerGUID, and ScriptedAI::me.
Referenced by npc_simone::npc_simoneAI::UpdateAI(), and npc_franklin::npc_franklinAI::UpdateAI().
InNormalForm()
bool NPCStaveQuestAI::InNormalForm ()
Definition at line 33 of file npc_stave_of_ancients.cpp.
 {
     return me->GetEntry() == GetFormEntry("normal");
 }
References Object::GetEntry(), GetFormEntry(), and ScriptedAI::me.
Referenced by AttackStart(), npc_artorius::npc_artoriusAI::EnterCombat(), npc_simone::npc_simoneAI::EnterCombat(), npc_nelson::npc_nelsonAI::EnterCombat(), npc_franklin::npc_franklinAI::EnterCombat(), ResetState(), RevealForm(), npc_artorius::npc_artoriusAI::SpellHit(), npc_simone::npc_simoneAI::SpellHit(), npc_nelson::npc_nelsonAI::SpellHit(), npc_franklin::npc_franklinAI::SpellHit(), npc_simone::npc_simoneAI::UpdateAI(), and npc_franklin::npc_franklinAI::UpdateAI().
IsAllowedEntry()
bool NPCStaveQuestAI::IsAllowedEntry (uint32 entry)
Definition at line 69 of file npc_stave_of_ancients.cpp.
 {
     uint32 allowedEntries[4] = { 0, 12999, 19833, 19921 }; //player, World Invisible Trigger(traps) and snake trap snakes
     bool isAllowed = std::find(std::begin(allowedEntries), std::end(allowedEntries), entry) != std::end(allowedEntries);
     return isAllowed;
 }
References find().
Referenced by StoreAttackerGuidValue(), and UnitIsUnfair().
IsFairFight()
bool NPCStaveQuestAI::IsFairFight ()
Definition at line 107 of file npc_stave_of_ancients.cpp.
 {
     for (ThreatContainer::StorageType::const_iterator itr = threatList.begin(); itr != threatList.end(); ++itr)
     {
         Unit* unit = ObjectAccessor::GetUnit(*me, (*itr)->getUnitGuid());
         if (!(*itr)->getThreat())
         {
             // if target threat is 0 its fair, this prevents despawn in the case when
             // there is a bystander since UpdateVictim adds nearby enemies to the threatlist
             continue;
         }
         if (UnitIsUnfair(unit))
         {
             return false;
         }
     }
     return true;
 }
References ObjectAccessor::GetUnit(), ScriptedAI::me, threatList, and UnitIsUnfair().
Referenced by ValidThreatlist().
JustDied()
void NPCStaveQuestAI::JustDied (Unit * killer) virtual
Reimplemented from ScriptedAI.
Reimplemented in npc_simone::npc_simoneAI.
Definition at line 265 of file npc_stave_of_ancients.cpp.
 {
     // Prevent looting if killer doesn't have the quest
     ClearLootIfUnfair(killer);
 }
References ClearLootIfUnfair().
Referenced by npc_simone::npc_simoneAI::JustDied().
PlayerEligibleForReward()
bool NPCStaveQuestAI::PlayerEligibleForReward (Unit * killer)
Definition at line 173 of file npc_stave_of_ancients.cpp.
 {
     if (!killer)
     {
         return true;
     }
     if (Player* player = killer->ToPlayer())
     {
         if (player->GetQuestStatus(QUEST_STAVE_OF_THE_ANCIENTS) != QUEST_STATUS_INCOMPLETE)
         {
             return false;
         }
     }
     return true;
 }
References QUEST_STATUS_INCOMPLETE, QUEST_STAVE_OF_THE_ANCIENTS, and Object::ToPlayer().
Referenced by ClearLootIfUnfair().
PrepareForEncounter()
void NPCStaveQuestAI::PrepareForEncounter ()
Definition at line 151 of file npc_stave_of_ancients.cpp.
 {
     encounterStarted = true;
     me->GetMotionMaster()->MoveIdle();
     me->GetMotionMaster()->Clear();
     SetHomePosition();
     me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
     me->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
 }
References MotionMaster::Clear(), encounterStarted, Unit::GetMotionMaster(), ScriptedAI::me, MotionMaster::MoveIdle(), Object::RemoveFlag(), Object::SetFlag(), SetHomePosition(), UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
Referenced by npc_artorius::npc_artoriusAI::DoAction(), npc_nelson::npc_nelsonAI::DoAction(), npc_simone::npc_simoneAI::ScheduleEncounterStart(), and npc_franklin::npc_franklinAI::ScheduleEncounterStart().
QuestIncomplete()
bool NPCStaveQuestAI::QuestIncomplete (Unit * unit, uint32 questItem)
Definition at line 212 of file npc_stave_of_ancients.cpp.
 {
     if (!unit || !unit->IsPlayer())
     {
         return true;
     }
     QuestStatus questStatus = unit->ToPlayer()->GetQuestStatus(QUEST_STAVE_OF_THE_ANCIENTS);
     bool hasQuestItem = unit->ToPlayer()->HasItemCount(questItem, 1, true);
     bool isIncomplete = questStatus == QUEST_STATUS_INCOMPLETE && !hasQuestItem;
     return isIncomplete;
 }
References Player::GetQuestStatus(), Player::HasItemCount(), Object::IsPlayer(), QUEST_STATUS_INCOMPLETE, QUEST_STAVE_OF_THE_ANCIENTS, and Object::ToPlayer().
Referenced by npc_artorius::npc_artoriusAI::EnterCombat(), npc_simone::npc_simoneAI::EnterCombat(), npc_nelson::npc_nelsonAI::EnterCombat(), npc_franklin::npc_franklinAI::EnterCombat(), npc_artorius::npc_artoriusAI::UpdateAI(), npc_simone::npc_simoneAI::UpdateAI(), npc_nelson::npc_nelsonAI::UpdateAI(), and npc_franklin::npc_franklinAI::UpdateAI().
ResetState()
void NPCStaveQuestAI::ResetState (uint32 aura = 0)
Definition at line 226 of file npc_stave_of_ancients.cpp.
 {
     encounterStarted = false;
     playerGUID.Clear();
     attackerGuids.clear();
     if (InNormalForm())
     {
         me->m_Events.KillAllEvents(true);
         me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
     }
     me->RemoveAura(aura);
 }
References attackerGuids, ObjectGuid::Clear(), encounterStarted, InNormalForm(), EventProcessor::KillAllEvents(), Unit::m_Events, ScriptedAI::me, playerGUID, Unit::RemoveAura(), Object::SetFlag(), UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
Referenced by npc_artorius::npc_artoriusAI::Reset(), npc_precious::npc_preciousAI::Reset(), npc_simone::npc_simoneAI::Reset(), npc_nelson::npc_nelsonAI::Reset(), and npc_franklin::npc_franklinAI::Reset().
RevealForm()
void NPCStaveQuestAI::RevealForm ()
Definition at line 38 of file npc_stave_of_ancients.cpp.
 {
     if (encounterStarted && InNormalForm())
     {
         me->UpdateEntry(GetFormEntry("evil"));
         me->SetFullHealth();
         me->DespawnOrUnsummon(900000);
     }
 }
References Creature::DespawnOrUnsummon(), encounterStarted, GetFormEntry(), InNormalForm(), ScriptedAI::me, Unit::SetFullHealth(), and Creature::UpdateEntry().
Referenced by npc_precious::npc_preciousAI::EnterCombat(), npc_artorius::npc_artoriusAI::EnterCombat(), npc_simone::npc_simoneAI::EnterCombat(), npc_nelson::npc_nelsonAI::EnterCombat(), npc_franklin::npc_franklinAI::EnterCombat(), npc_artorius::npc_artoriusAI::UpdateAI(), npc_simone::npc_simoneAI::UpdateAI(), npc_nelson::npc_nelsonAI::UpdateAI(), and npc_franklin::npc_franklinAI::UpdateAI().
SetHomePosition()
void NPCStaveQuestAI::SetHomePosition ()
Definition at line 141 of file npc_stave_of_ancients.cpp.
 {
     Position homePosition = me->GetPosition();
     if (homePosition.IsPositionValid())
     {
         me->SetHomePosition(homePosition);
     }
 }
References Position::GetPosition(), Position::IsPositionValid(), ScriptedAI::me, and Creature::SetHomePosition().
Referenced by PrepareForEncounter(), npc_artorius::npc_artoriusAI::UpdateAI(), npc_simone::npc_simoneAI::UpdateAI(), npc_nelson::npc_nelsonAI::UpdateAI(), and npc_franklin::npc_franklinAI::UpdateAI().
StoreAttackerGuidValue()
void NPCStaveQuestAI::StoreAttackerGuidValue (Unit * attacker)
Definition at line 191 of file npc_stave_of_ancients.cpp.
 {
     if (!attacker)
     {
         return;
     }
     uint64 guidValue = attacker->GetGUID().GetRawValue();
     bool isGUIDPresent = std::find(attackerGuids.begin(), attackerGuids.end(), guidValue) != attackerGuids.end();
     // don't store snaketrap's snakes and trap triggers
     if (isGUIDPresent || (IsAllowedEntry(attacker->GetEntry()) && attacker->GetTypeId() != TYPEID_PLAYER))
     {
         return;
     }
     else
     {
         attackerGuids.push_back(guidValue);
     }
 }
References attackerGuids, find(), Object::GetEntry(), Object::GetGUID(), ObjectGuid::GetRawValue(), Object::GetTypeId(), IsAllowedEntry(), and TYPEID_PLAYER.
Referenced by AttackedBy().
StorePlayerGUID()
void NPCStaveQuestAI::StorePlayerGUID ()
Definition at line 48 of file npc_stave_of_ancients.cpp.
 {
     if (!playerGUID.IsEmpty())
     {
         return;
     }
     for (ThreatContainer::StorageType::const_iterator itr = threatList.begin(); itr != threatList.end(); ++itr)
     {
         if ((*itr)->getTarget()->GetTypeId() == TYPEID_PLAYER)
         {
             playerGUID = (*itr)->getUnitGuid();
         }
     }
 }
References ObjectGuid::IsEmpty(), playerGUID, threatList, and TYPEID_PLAYER.
Referenced by AttackStart().
UnitIsUnfair()
bool NPCStaveQuestAI::UnitIsUnfair (Unit * unit)
Definition at line 76 of file npc_stave_of_ancients.cpp.
 {
     if (!unit || playerGUID.IsEmpty())
     {
         return false;
     }
     if (unit->IsPlayer())
     {
         if (playerGUID != unit->GetGUID())
         {
             return true;
         }
     }
     else
     {
         if (unit->GetOwnerGUID() != playerGUID)
         {
             // if a creature attacking isn't owned by the player its unfair
             return true;
         }
         else if (!IsAllowedEntry(unit->GetEntry()))
         {
             // if not in the whitelist its unfair
             return true;
         }
     }
     return false;
 }
References Object::GetEntry(), Object::GetGUID(), Unit::GetOwnerGUID(), IsAllowedEntry(), ObjectGuid::IsEmpty(), Object::IsPlayer(), and playerGUID.
Referenced by npc_artorius::npc_artoriusAI::EnterCombat(), npc_simone::npc_simoneAI::EnterCombat(), npc_nelson::npc_nelsonAI::EnterCombat(), npc_franklin::npc_franklinAI::EnterCombat(), IsFairFight(), npc_nelson::npc_nelsonAI::SummonedCreatureDies(), npc_artorius::npc_artoriusAI::UpdateAI(), npc_simone::npc_simoneAI::UpdateAI(), npc_nelson::npc_nelsonAI::UpdateAI(), and npc_franklin::npc_franklinAI::UpdateAI().
ValidThreatlist()
bool NPCStaveQuestAI::ValidThreatlist ()
Definition at line 129 of file npc_stave_of_ancients.cpp.
 {
     if (threatList.size() == 1)
     {
         return true;
     }
     bool isFair = IsFairFight();
     return isFair;
 }
References IsFairFight(), and threatList.
Referenced by npc_artorius::npc_artoriusAI::UpdateAI(), npc_simone::npc_simoneAI::UpdateAI(), npc_nelson::npc_nelsonAI::UpdateAI(), and npc_franklin::npc_franklinAI::UpdateAI().
Member Data Documentation
attackerGuids
std::vector<uint64> NPCStaveQuestAI::attackerGuids
Definition at line 187 of file npc_stave_of_ancients.h.
Referenced by ClearLootIfUnfair(), ResetState(), and StoreAttackerGuidValue().
encounterStarted
bool NPCStaveQuestAI::encounterStarted
Definition at line 140 of file npc_stave_of_ancients.h.
Referenced by npc_nelson::npc_nelsonAI::EnterCombat(), PrepareForEncounter(), ResetState(), and RevealForm().
entryKeys
std::map<int, int> NPCStaveQuestAI::entryKeys
Initial value:
= {
        { ARTORIUS_NORMAL_ENTRY, 1 },
        { ARTORIUS_EVIL_ENTRY,   1 },
        { SIMONE_NORMAL_ENTRY,   2 },
        { SIMONE_EVIL_ENTRY,     2 },
        { PRECIOUS_NORMAL_ENTRY, 3 },
        { PRECIOUS_EVIL_ENTRY,   3 },
        { NELSON_NORMAL_ENTRY,   4 },
        { NELSON_EVIL_ENTRY,     4 },
        { FRANKLIN_NORMAL_ENTRY, 5 },
        { FRANKLIN_EVIL_ENTRY,   5 }
    }
Definition at line 143 of file npc_stave_of_ancients.h.
Referenced by GetFormEntry().
entryList
std::map<int, std::map<std::string, int> > NPCStaveQuestAI::entryList
Definition at line 155 of file npc_stave_of_ancients.h.
Referenced by GetFormEntry().
gossipPlayerGUID
ObjectGuid NPCStaveQuestAI::gossipPlayerGUID
Definition at line 138 of file npc_stave_of_ancients.h.
Referenced by GetGossipPlayer(), npc_simone::npc_simoneAI::ScheduleEncounterStart(), and npc_franklin::npc_franklinAI::ScheduleEncounterStart().
playerGUID
ObjectGuid NPCStaveQuestAI::playerGUID
Definition at line 139 of file npc_stave_of_ancients.h.
Referenced by AttackStart(), EvadeOnFeignDeath(), ResetState(), npc_simone::npc_simoneAI::ScheduleEncounterStart(), npc_franklin::npc_franklinAI::ScheduleEncounterStart(), StorePlayerGUID(), and UnitIsUnfair().
threatList
ThreatContainer::StorageType const& NPCStaveQuestAI::threatList = me->getThreatMgr().getThreatList()
Definition at line 141 of file npc_stave_of_ancients.h.
Referenced by IsFairFight(), StorePlayerGUID(), and ValidThreatlist().
The documentation for this struct was generated from the following files:
src/server/scripts/World/npc_stave_of_ancients.h
src/server/scripts/World/npc_stave_of_ancients.cpp