Azerotcore-wotlk: instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript Struct Reference
instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript Struct Reference
Public Member Functions
instance_blackwing_lair_InstanceMapScript (Map *map)
void Initialize () override
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
bool CheckRequiredBosses (uint32 bossId, Player const *) const override
bool SetBossState (uint32 type, EncounterState state) override
void SetData (uint32 type, uint32 data) override
ObjectGuid GetGuidData (uint32 type) const override
void OnUnitDeath (Unit *unit) override
void Update (uint32 diff) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Load (char const *data)
virtual void CreatureLooted (Creature *, LootType)
virtual std::string GetSaveData ()
void SaveToDB ()
virtual bool IsEncounterInProgress () const
void OnCreatureRemove (Creature *creature) override
ObjectGuid GetObjectGuid (uint32 type) const
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void ProcessEvent (WorldObject *, uint32)
Protected Attributes
EventMap _events
ObjectGuid razorgoreGUID
uint8 EggCount
uint32 EggEvent
GuidList EggList
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Definition at line 62 of file instance_blackwing_lair.cpp.
Constructor & Destructor Documentation
instance_blackwing_lair_InstanceMapScript()
instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::instance_blackwing_lair_InstanceMapScript (Map * map) inline
Definition at line 64 of file instance_blackwing_lair.cpp.
                                                             : InstanceScript(map)
         {
             //SetHeaders(DataHeader);
             SetBossNumber(EncounterCount);
             LoadDoorData(doorData);
             //LoadObjectData(creatureData, gameObjectData);
         }
References doorData, EncounterCount, InstanceScript::LoadDoorData(), and InstanceScript::SetBossNumber().
Member Function Documentation
CheckRequiredBosses()
bool instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::CheckRequiredBosses (uint32 bossId, Player const *) const inline override virtual
Reimplemented from InstanceScript.
Definition at line 149 of file instance_blackwing_lair.cpp.
         {
             switch (bossId)
             {
                 case DATA_BROODLORD_LASHLAYER:
                     if (GetBossState(DATA_VAELASTRAZ_THE_CORRUPT) != DONE)
                         return false;
                     break;
                 case DATA_CHROMAGGUS:
                     if (GetBossState(DATA_FIREMAW) != DONE
                         || GetBossState(DATA_EBONROC) != DONE
                         || GetBossState(DATA_FLAMEGOR) != DONE)
                         return false;
                     break;
                 default:
                     break;
             }
             return true;
         }
References DATA_BROODLORD_LASHLAYER, DATA_CHROMAGGUS, DATA_EBONROC, DATA_FIREMAW, DATA_FLAMEGOR, DATA_VAELASTRAZ_THE_CORRUPT, DONE, and InstanceScript::GetBossState().
GetGuidData()
ObjectGuid instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::GetGuidData (uint32 type) const inline override virtual
Reimplemented from InstanceScript.
Definition at line 240 of file instance_blackwing_lair.cpp.
         {
             switch (type)
             {
                 case DATA_RAZORGORE_THE_UNTAMED:
                     return razorgoreGUID;
                 default:
                     break;
             }
             return ObjectGuid::Empty;
         }
References DATA_RAZORGORE_THE_UNTAMED, ObjectGuid::Empty, and razorgoreGUID.
Referenced by SetBossState(), and Update().
Initialize()
void instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::Initialize (void) inline override virtual
Reimplemented from InstanceScript.
Definition at line 72 of file instance_blackwing_lair.cpp.
         {
             // Razorgore
             EggCount = 0;
             EggEvent = 0;
         }
References EggCount, and EggEvent.
OnCreatureCreate()
void instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 79 of file instance_blackwing_lair.cpp.
         {
             InstanceScript::OnCreatureCreate(creature);
             switch (creature->GetEntry())
             {
                 case NPC_RAZORGORE:
                     razorgoreGUID = creature->GetGUID();
                     break;
                 case NPC_BLACKWING_DRAGON:
                 case NPC_BLACKWING_TASKMASTER:
                 case NPC_BLACKWING_LEGIONAIRE:
                 case NPC_BLACKWING_WARLOCK:
                     if (Creature* razor = instance->GetCreature(razorgoreGUID))
                         if (CreatureAI* razorAI = razor->AI())
                             razorAI->JustSummoned(creature);
                     break;
                 default:
                     break;
             }
         }
References Map::GetCreature(), Object::GetEntry(), Object::GetGUID(), InstanceScript::instance, NPC_BLACKWING_DRAGON, NPC_BLACKWING_LEGIONAIRE, NPC_BLACKWING_TASKMASTER, NPC_BLACKWING_WARLOCK, NPC_RAZORGORE, InstanceScript::OnCreatureCreate(), and razorgoreGUID.
OnGameObjectCreate()
void instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
Definition at line 101 of file instance_blackwing_lair.cpp.
         {
             InstanceScript::OnGameObjectCreate(go);
             switch(go->GetEntry())
             {
                 case GO_BLACK_DRAGON_EGG:
                     if (GetBossState(DATA_FIREMAW) == DONE)
                         go->SetPhaseMask(2, true);
                     else
                         EggList.push_back(go->GetGUID());
                     break;
                 case GO_PORTCULLIS_RAZORGORE:
                 case GO_PORTCULLIS_VAELASTRASZ:
                 case GO_PORTCULLIS_BROODLORD:
                 case GO_PORTCULLIS_THREEDRAGONS:
                 case GO_PORTCULLIS_CHROMAGGUS:
                 case GO_PORTCULLIS_NEFARIAN:
                     AddDoor(go, true);
                     break;
                 default:
                     break;
             }
         }
References InstanceScript::AddDoor(), DATA_FIREMAW, DONE, EggList, InstanceScript::GetBossState(), Object::GetEntry(), Object::GetGUID(), GO_BLACK_DRAGON_EGG, GO_PORTCULLIS_BROODLORD, GO_PORTCULLIS_CHROMAGGUS, GO_PORTCULLIS_NEFARIAN, GO_PORTCULLIS_RAZORGORE, GO_PORTCULLIS_THREEDRAGONS, GO_PORTCULLIS_VAELASTRASZ, InstanceScript::OnGameObjectCreate(), and GameObject::SetPhaseMask().
OnGameObjectRemove()
void instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::OnGameObjectRemove (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
Definition at line 127 of file instance_blackwing_lair.cpp.
         {
             InstanceScript::OnGameObjectRemove(go);
             if (go->GetEntry() == GO_BLACK_DRAGON_EGG)
                 EggList.remove(go->GetGUID());
             switch (go->GetEntry())
             {
             case GO_PORTCULLIS_RAZORGORE:
             case GO_PORTCULLIS_VAELASTRASZ:
             case GO_PORTCULLIS_BROODLORD:
             case GO_PORTCULLIS_THREEDRAGONS:
             case GO_PORTCULLIS_CHROMAGGUS:
             case GO_PORTCULLIS_NEFARIAN:
                 AddDoor(go, false);
                 break;
             default:
                 break;
             }
         }
References InstanceScript::AddDoor(), EggList, Object::GetEntry(), Object::GetGUID(), GO_BLACK_DRAGON_EGG, GO_PORTCULLIS_BROODLORD, GO_PORTCULLIS_CHROMAGGUS, GO_PORTCULLIS_NEFARIAN, GO_PORTCULLIS_RAZORGORE, GO_PORTCULLIS_THREEDRAGONS, GO_PORTCULLIS_VAELASTRASZ, and InstanceScript::OnGameObjectRemove().
OnUnitDeath()
void instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::OnUnitDeath (Unit * unit) inline override virtual
HACK, needed because of buggy CreatureAI after charm
Reimplemented from ZoneScript.
Definition at line 253 of file instance_blackwing_lair.cpp.
         {
             if (unit->GetEntry() == NPC_RAZORGORE && GetBossState(DATA_RAZORGORE_THE_UNTAMED) != DONE)
                 SetBossState(DATA_RAZORGORE_THE_UNTAMED, DONE);
         }
References DATA_RAZORGORE_THE_UNTAMED, DONE, InstanceScript::GetBossState(), Object::GetEntry(), NPC_RAZORGORE, and SetBossState().
SetBossState()
bool instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::SetBossState (uint32 type, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
Definition at line 170 of file instance_blackwing_lair.cpp.
         {
             if (!InstanceScript::SetBossState(type, state))
                 return false;
             switch (type)
             {
                 case DATA_RAZORGORE_THE_UNTAMED:
                     if (state == DONE)
                     {
                         for (ObjectGuid const& guid : EggList)
                             if (GameObject* egg = instance->GetGameObject(guid))
                                 egg->SetPhaseMask(2, true);
                     }
                     SetData(DATA_EGG_EVENT, NOT_STARTED);
                     break;
                 case DATA_NEFARIAN:
                     switch (state)
                     {
                         case NOT_STARTED:
                             if (Creature* nefarian = instance->GetCreature(GetGuidData(DATA_NEFARIAN)))
                                 nefarian->DespawnOrUnsummon();
                             break;
                         case FAIL:
                             _events.ScheduleEvent(EVENT_RESPAWN_NEFARIUS, 15 * 60 * IN_MILLISECONDS); //15min
                             SetBossState(DATA_NEFARIAN, NOT_STARTED);
                             break;
                         default:
                             break;
                     }
                     break;
             }
             return true;
         }
References _events, DATA_EGG_EVENT, DATA_NEFARIAN, DATA_RAZORGORE_THE_UNTAMED, DONE, EggList, EVENT_RESPAWN_NEFARIUS, FAIL, Map::GetCreature(), Map::GetGameObject(), GetGuidData(), IN_MILLISECONDS, InstanceScript::instance, NOT_STARTED, EventMap::ScheduleEvent(), InstanceScript::SetBossState(), and SetData().
Referenced by OnUnitDeath().
SetData()
void instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
Definition at line 205 of file instance_blackwing_lair.cpp.
         {
             if (type == DATA_EGG_EVENT)
             {
                 switch (data)
                 {
                     case IN_PROGRESS:
                         _events.ScheduleEvent(EVENT_RAZOR_SPAWN, 45000);
                         EggEvent = data;
                         EggCount = 0;
                         break;
                     case NOT_STARTED:
                         _events.CancelEvent(EVENT_RAZOR_SPAWN);
                         EggEvent = data;
                         EggCount = 0;
                         break;
                     case SPECIAL:
                         if (++EggCount == 15)
{
                             if (Creature* razor = instance->GetCreature(razorgoreGUID))
{
                                 SetData(DATA_EGG_EVENT, DONE);
                                 razor->RemoveAurasDueToSpell(42013); // MindControl
                                 DoRemoveAurasDueToSpellOnPlayers(42013);
                             }
                             _events.ScheduleEvent(EVENT_RAZOR_PHASE_TWO, 1000);
                             _events.CancelEvent(EVENT_RAZOR_SPAWN);
                         }
                         if (EggEvent == NOT_STARTED)
                             SetData(DATA_EGG_EVENT, IN_PROGRESS);
                         break;
                 }
             }
         }
References _events, EventMap::CancelEvent(), DATA_EGG_EVENT, DONE, InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), EggCount, EggEvent, EVENT_RAZOR_PHASE_TWO, EVENT_RAZOR_SPAWN, Map::GetCreature(), IN_PROGRESS, InstanceScript::instance, NOT_STARTED, razorgoreGUID, EventMap::ScheduleEvent(), and SPECIAL.
Referenced by SetBossState().
Update()
void instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::Update (uint32 diff) inline override virtual
Reimplemented from InstanceScript.
Definition at line 260 of file instance_blackwing_lair.cpp.
         {
             if (_events.Empty())
                 return;
             _events.Update(diff);
             while (uint32 eventId = _events.ExecuteEvent())
             {
                 switch (eventId)
                 {
                     case EVENT_RAZOR_SPAWN:
                         for (uint8 i = urand(2, 5); i > 0; --i)
                             if (Creature* summon = instance->SummonCreature(Entry[urand(0, 4)], SummonPosition[urand(0, 7)]))
                                 summon->AI()->DoZoneInCombat();
                         _events.ScheduleEvent(EVENT_RAZOR_SPAWN, 12000, 17000);
                         break;
                     case EVENT_RAZOR_PHASE_TWO:
                         _events.CancelEvent(EVENT_RAZOR_SPAWN);
                         if (Creature* razor = instance->GetCreature(razorgoreGUID))
                             razor->AI()->DoAction(ACTION_PHASE_TWO);
                         break;
                     case EVENT_RESPAWN_NEFARIUS:
                         if (Creature* nefarius = instance->GetCreature(GetGuidData(DATA_LORD_VICTOR_NEFARIUS)))
{
                             nefarius->SetPhaseMask(1, true);
                             nefarius->setActive(true);
                             nefarius->Respawn();
                             nefarius->GetMotionMaster()->MoveTargetedHome();
                         }
                         break;
                 }
             }
         }
References _events, ACTION_PHASE_TWO, EventMap::CancelEvent(), DATA_LORD_VICTOR_NEFARIUS, EventMap::Empty(), Entry, EVENT_RAZOR_PHASE_TWO, EVENT_RAZOR_SPAWN, EVENT_RESPAWN_NEFARIUS, EventMap::ExecuteEvent(), Map::GetCreature(), GetGuidData(), InstanceScript::instance, razorgoreGUID, EventMap::ScheduleEvent(), Map::SummonCreature(), SummonPosition, EventMap::Update(), and urand().
Member Data Documentation
_events
EventMap instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::_events protected
Definition at line 297 of file instance_blackwing_lair.cpp.
Referenced by SetBossState(), SetData(), and Update().
EggCount
uint8 instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::EggCount protected
Definition at line 301 of file instance_blackwing_lair.cpp.
Referenced by Initialize(), and SetData().
EggEvent
uint32 instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::EggEvent protected
Definition at line 302 of file instance_blackwing_lair.cpp.
Referenced by Initialize(), and SetData().
EggList
GuidList instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::EggList protected
Definition at line 303 of file instance_blackwing_lair.cpp.
Referenced by OnGameObjectCreate(), OnGameObjectRemove(), and SetBossState().
razorgoreGUID
ObjectGuid instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::razorgoreGUID protected
Definition at line 300 of file instance_blackwing_lair.cpp.
Referenced by GetGuidData(), OnCreatureCreate(), SetData(), and Update().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/instance_blackwing_lair.cpp