Azerotcore-wotlk: deps/mysqllite/include/sql_common.h File Reference
sql_common.h File Reference
#include <mysql.h>
Classes
struct st_mysql_options_extention
struct st_mysql_methods
Macros
#define SQL_COMMON_INCLUDED
#define simple_command(mysql, command, arg, length, skip_check)
#define stmt_command(mysql, command, arg, length, stmt)
#define protocol_41(A) ((A)->server_capabilities & CLIENT_PROTOCOL_41)
Typedefs
typedef struct st_mysql_methods MYSQL_METHODS
Functions
MYSQL_FIELD * unpack_fields (MYSQL_DATA *data, MEM_ROOT *alloc, uint fields, my_bool default_value, uint server_capabilities)
void free_rows (MYSQL_DATA *cur)
void free_old_query (MYSQL *mysql)
void end_server (MYSQL *mysql)
my_bool mysql_reconnect (MYSQL *mysql)
void mysql_read_default_options (struct st_mysql_options *options, const char *filename, const char *group)
my_bool cli_advanced_command (MYSQL *mysql, enum enum_server_command command, const unsigned char *header, ulong header_length, const unsigned char *arg, ulong arg_length, my_bool skip_check, MYSQL_STMT *stmt)
unsigned long cli_safe_read (MYSQL *mysql)
void net_clear_error (NET *net)
void set_stmt_errmsg (MYSQL_STMT *stmt, NET *net)
void set_stmt_error (MYSQL_STMT *stmt, int errcode, const char *sqlstate, const char *err)
void set_mysql_error (MYSQL *mysql, int errcode, const char *sqlstate)
void set_mysql_extended_error (MYSQL *mysql, int errcode, const char *sqlstate, const char *format,...)
void mpvio_info (Vio *vio, struct st_plugin_vio_info *info)
int run_plugin_auth (MYSQL *mysql, char *data, uint data_len, const char *data_plugin, const char *db)
int mysql_client_plugin_init ()
void mysql_client_plugin_deinit ()
Variables
const char * unknown_sqlstate
const char * cant_connect_sqlstate
const char * not_error_sqlstate
CHARSET_INFO * default_client_charset_info
struct st_mysql_client_plugin * mysql_client_builtins []
Macro Definition Documentation
protocol_41
#define protocol_41 (A) ((A)->server_capabilities & CLIENT_PROTOCOL_41)
Definition at line 111 of file sql_common.h.
simple_command
#define simple_command (mysql, command, arg, length, skip_check)
Value:
  (*(mysql)->methods->advanced_command)(mysql, command, 0,  \
                                        0, arg, length, skip_check, NULL)
Definition at line 67 of file sql_common.h.
SQL_COMMON_INCLUDED
#define SQL_COMMON_INCLUDED
Definition at line 19 of file sql_common.h.
stmt_command
#define stmt_command (mysql, command, arg, length, stmt)
Value:
  (*(mysql)->methods->advanced_command)(mysql, command, 0,  \
                                        0, arg, length, 1, stmt)
Definition at line 70 of file sql_common.h.
Typedef Documentation
MYSQL_METHODS
typedef struct st_mysql_methods MYSQL_METHODS
Function Documentation
cli_advanced_command()
my_bool cli_advanced_command (MYSQL * mysql, enum enum_server_command command, const unsigned char * header, ulong header_length, const unsigned char * arg, ulong arg_length, my_bool skip_check, MYSQL_STMT * stmt)
Definition at line 808 of file client.c.
 {
   NET *net= &mysql->net;
   my_bool result= 1;
   my_bool stmt_skip= stmt ? stmt->state != MYSQL_STMT_INIT_DONE : FALSE;
   DBUG_ENTER("cli_advanced_command");
   if (mysql->net.vio == 0)
   {                     /* Do reconnect if possible */
     if (mysql_reconnect(mysql) || stmt_skip)
       DBUG_RETURN(1);
   }
   if (mysql->status != MYSQL_STATUS_READY ||
       mysql->server_status & SERVER_MORE_RESULTS_EXISTS)
   {
     DBUG_PRINT("error",("state: %d", mysql->status));
     set_mysql_error(mysql, CR_COMMANDS_OUT_OF_SYNC, unknown_sqlstate);
     DBUG_RETURN(1);
   }
   net_clear_error(net);
   mysql->info=0;
   mysql->affected_rows= ~(my_ulonglong) 0;
   /*
     We don't want to clear the protocol buffer on COM_QUIT, because if
     the previous command was a shutdown command, we may have the
     response for the COM_QUIT already in the communication buffer
   */
   net_clear(&mysql->net, (command != COM_QUIT));
   if (net_write_command(net,(uchar) command, header, header_length,
             arg, arg_length))
   {
     DBUG_PRINT("error",("Can't send command to server. Error: %d",
             socket_errno));
     if (net->last_errno == ER_NET_PACKET_TOO_LARGE)
     {
       set_mysql_error(mysql, CR_NET_PACKET_TOO_LARGE, unknown_sqlstate);
       goto end;
     }
     end_server(mysql);
     if (mysql_reconnect(mysql) || stmt_skip)
       goto end;
     if (net_write_command(net,(uchar) command, header, header_length,
               arg, arg_length))
     {
       set_mysql_error(mysql, CR_SERVER_GONE_ERROR, unknown_sqlstate);
       goto end;
     }
   }
   result=0;
   if (!skip_check)
     result= ((mysql->packet_length=cli_safe_read(mysql)) == packet_error ?
          1 : 0);
 end:
   DBUG_PRINT("exit",("result: %d", result));
   DBUG_RETURN(result);
 }
References st_mysql::affected_rows, arg(), cli_safe_read(), COM_QUIT, CR_COMMANDS_OUT_OF_SYNC, CR_NET_PACKET_TOO_LARGE, CR_SERVER_GONE_ERROR, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, end_server(), ER_NET_PACKET_TOO_LARGE, FALSE, st_mysql::info, st_net::last_errno, mysql_reconnect(), MYSQL_STATUS_READY, MYSQL_STMT_INIT_DONE, st_mysql::net, net_clear(), net_clear_error(), net_write_command(), packet_error, st_mysql::packet_length, SERVER_MORE_RESULTS_EXISTS, st_mysql::server_status, set_mysql_error(), socket_errno, st_mysql_stmt::state, st_mysql::status, unknown_sqlstate, and st_net::vio.
Referenced by execute(), and mysql_stmt_store_result().
cli_safe_read()
unsigned long cli_safe_read (MYSQL * mysql)
Read a packet from server. Give error message if socket was down or packet is an error message
Return values
packet_error An error occurred during reading. Error message is set.
<br>
Definition at line 729 of file client.c.
 {
   NET *net= &mysql->net;
   ulong len=0;
   if (net->vio != 0)
     len=my_net_read(net);
   if (len == packet_error || len == 0)
   {
     DBUG_PRINT("error",("Wrong connection or packet. fd: %s  len: %lu",
             vio_description(net->vio),len));
 #ifdef MYSQL_SERVER
     if (net->vio && vio_was_interrupted(net->vio))
       return (packet_error);
 #endif /*MYSQL_SERVER*/
     end_server(mysql);
     set_mysql_error(mysql, net->last_errno == ER_NET_PACKET_TOO_LARGE ?
                     CR_NET_PACKET_TOO_LARGE: CR_SERVER_LOST, unknown_sqlstate);
     return (packet_error);
   }
   if (net->read_pos[0] == 255)
   {
     if (len > 3)
     {
       char *pos=(char*) net->read_pos+1;
       net->last_errno=uint2korr(pos);
       pos+=2;
       len-=2;
       if (protocol_41(mysql) && pos[0] == '#')
       {
     strmake(net->sqlstate, pos+1, SQLSTATE_LENGTH);
     pos+= SQLSTATE_LENGTH+1;
       }
       else
       {
         /*
           The SQL state hasn't been received -- it should be reset to HY000
           (unknown error sql state).
         */
         strmov(net->sqlstate, unknown_sqlstate);
       }
       (void) strmake(net->last_error,(char*) pos,
              min((uint) len,(uint) sizeof(net->last_error)-1));
     }
     else
       set_mysql_error(mysql, CR_UNKNOWN_ERROR, unknown_sqlstate);
     /*
       Cover a protocol design error: error packet does not
       contain the server status. Therefore, the client has no way
       to find out whether there are more result sets of
       a multiple-result-set statement pending. Luckily, in 5.0 an
       error always aborts execution of a statement, wherever it is
       a multi-statement or a stored procedure, so it should be
       safe to unconditionally turn off the flag here.
     */
     mysql->server_status&= ~SERVER_MORE_RESULTS_EXISTS;
     DBUG_PRINT("error",("Got error: %d/%s (%s)",
                         net->last_errno,
                         net->sqlstate,
                         net->last_error));
     return(packet_error);
   }
   return len;
 }
References CR_NET_PACKET_TOO_LARGE, CR_SERVER_LOST, CR_UNKNOWN_ERROR, DBUG_PRINT, end_server(), ER_NET_PACKET_TOO_LARGE, st_net::last_errno, st_net::last_error, min, my_net_read(), st_mysql::net, packet_error, pos(), protocol_41, st_net::read_pos, SERVER_MORE_RESULTS_EXISTS, st_mysql::server_status, set_mysql_error(), st_net::sqlstate, SQLSTATE_LENGTH, strmake(), strmov(), uint2korr, unknown_sqlstate, st_net::vio, vio_description(), and vio_was_interrupted.
Referenced by cli_advanced_command(), CLI_MYSQL_REAL_CONNECT(), cli_read_binary_rows(), cli_read_change_user_result(), cli_read_prepare_result(), cli_read_query_result(), cli_read_rows(), cli_unbuffered_fetch(), flush_one_result(), opt_flush_ok_packet(), read_one_row(), and run_plugin_auth().
end_server()
void end_server (MYSQL * mysql)
Definition at line 1076 of file client.c.
 {
   int save_errno= errno;
   DBUG_ENTER("end_server");
   if (mysql->net.vio != 0)
   {
     DBUG_PRINT("info",("Net: %s", vio_description(mysql->net.vio)));
 #ifdef MYSQL_SERVER
     slave_io_thread_detach_vio();
 #endif
     vio_delete(mysql->net.vio);
     mysql->net.vio= 0;          /* Marker */
     mysql_prune_stmt_list(mysql);
   }
   net_end(&mysql->net);
   free_old_query(mysql);
   errno= save_errno;
   DBUG_VOID_RETURN;
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, errno, free_old_query(), mysql_prune_stmt_list(), st_mysql::net, net_end(), st_net::vio, vio_delete, and vio_description().
Referenced by cli_advanced_command(), CLI_MYSQL_REAL_CONNECT(), cli_safe_read(), and mysql_close().
free_old_query()
void free_old_query (MYSQL * mysql)
Definition at line 870 of file client.c.
 {
   DBUG_ENTER("free_old_query");
   if (mysql->fields)
     free_root(&mysql->field_alloc,MYF(0));
   init_alloc_root(&mysql->field_alloc,8192,0); /* Assume rowlength < 8192 */
   mysql->fields= 0;
   mysql->field_count= 0;            /* For API */
   mysql->warning_count= 0;
   mysql->info= 0;
   DBUG_VOID_RETURN;
 }
References DBUG_ENTER, DBUG_VOID_RETURN, st_mysql::field_alloc, st_mysql::field_count, st_mysql::fields, free_root(), st_mysql::info, init_alloc_root(), MYF, and st_mysql::warning_count.
Referenced by cli_read_query_result(), end_server(), mysql_close(), mysql_list_fields(), and mysql_list_processes().
free_rows()
void free_rows (MYSQL_DATA * cur)
Definition at line 798 of file client.c.
 {
   if (cur)
   {
     free_root(&cur->alloc,MYF(0));
     my_free(cur);
   }
 }
References st_mysql_data::alloc, free_root(), my_free(), and MYF.
Referenced by cli_read_prepare_result(), cli_read_rows(), mysql_free_result(), and unpack_fields().
mpvio_info()
void mpvio_info (Vio * vio, MYSQL_PLUGIN_VIO_INFO * info)
fills MYSQL_PLUGIN_VIO_INFO structure with the information about the connection
Definition at line 2689 of file client.c.
 {
   bzero(info, sizeof(*info));
   switch (vio->type) {
   case VIO_TYPE_TCPIP:
     info->protocol= MYSQL_VIO_TCP;
     info->socket= vio->sd;
     return;
   case VIO_TYPE_SOCKET:
     info->protocol= MYSQL_VIO_SOCKET;
     info->socket= vio->sd;
     return;
   case VIO_TYPE_SSL:
     {
       struct sockaddr addr;
       socklen_t addrlen= sizeof(addr);
       if (getsockname(vio->sd, &addr, &addrlen))
         return;
       info->protocol= addr.sa_family == AF_UNIX ?
         MYSQL_VIO_SOCKET : MYSQL_VIO_TCP;
       info->socket= vio->sd;
       return;
     }
 #ifdef _WIN32
   case VIO_TYPE_NAMEDPIPE:
     info->protocol= MYSQL_VIO_PIPE;
     info->handle= vio->hPipe;
     return;
 #ifdef HAVE_SMEM
   case VIO_TYPE_SHARED_MEMORY:
     info->protocol= MYSQL_VIO_MEMORY;
     info->handle= vio->handle_file_map; /* or what ? */
     return;
 #endif
 #endif
   default: DBUG_ASSERT(0);
   }
 }
References bzero, DBUG_ASSERT, st_vio::hPipe, st_plugin_vio_info::protocol, st_vio::sd, st_plugin_vio_info::socket, st_vio::type, VIO_TYPE_NAMEDPIPE, VIO_TYPE_SHARED_MEMORY, VIO_TYPE_SOCKET, VIO_TYPE_SSL, and VIO_TYPE_TCPIP.
Referenced by client_mpvio_info().
mysql_client_plugin_deinit()
void mysql_client_plugin_deinit ()
Deinitializes the client plugin layer.
Unloades all client plugins and frees any associated resources.
Definition at line 260 of file client_plugin.c.
 {
   int i;
   struct st_client_plugin_int *p;
   if (!initialized)
     return;
   for (i=0; i < MYSQL_CLIENT_MAX_PLUGINS; i++)
     for (p= plugin_list[i]; p; p= p->next)
     {
       if (p->plugin->deinit)
         p->plugin->deinit();
       if (p->dlhandle)
         dlclose(p->dlhandle);
     }
   bzero(&plugin_list, sizeof(plugin_list));
   initialized= 0;
   free_root(&mem_root, MYF(0));
   pthread_mutex_destroy(&LOCK_load_client_plugin);
 }
References bzero, st_client_plugin_int::dlhandle, free_root(), initialized, LOCK_load_client_plugin, mem_root, MYF, MYSQL_CLIENT_MAX_PLUGINS, st_client_plugin_int::next, st_client_plugin_int::plugin, and plugin_list.
Referenced by mysql_server_end().
mysql_client_plugin_init()
int mysql_client_plugin_init ()
Initializes the client plugin layer.
This function must be called before any other client plugin function.
Return values
0 successful
!= 0 error occured
Definition at line 226 of file client_plugin.c.
 {
   MYSQL mysql;
   struct st_mysql_client_plugin **builtin;
   if (initialized)
     return 0;
   bzero(&mysql, sizeof(mysql)); /* dummy mysql for set_mysql_extended_error */
   pthread_mutex_init(&LOCK_load_client_plugin, MY_MUTEX_INIT_SLOW);
   init_alloc_root(&mem_root, 128, 128);
   bzero(&plugin_list, sizeof(plugin_list));
   initialized= 1;
   pthread_mutex_lock(&LOCK_load_client_plugin);
   for (builtin= mysql_client_builtins; *builtin; builtin++)
     add_plugin(&mysql, *builtin, 0, 0, 0);
   pthread_mutex_unlock(&LOCK_load_client_plugin);
   load_env_plugins(&mysql);
   return 0;
 }
References add_plugin(), bzero, init_alloc_root(), initialized, load_env_plugins(), LOCK_load_client_plugin, mem_root, MY_MUTEX_INIT_SLOW, mysql_client_builtins, and plugin_list.
Referenced by mysql_server_init().
mysql_read_default_options()
void mysql_read_default_options (struct st_mysql_options * options, const char * filename, const char * group)
Definition at line 1192 of file client.c.
 {
   int argc;
   char *argv_buff[1],**argv;
   const char *groups[3];
   DBUG_ENTER("mysql_read_default_options");
   DBUG_PRINT("enter",("file: %s  group: %s",filename,group ? group :"NULL"));
   argc=1; argv=argv_buff; argv_buff[0]= (char*) "client";
   groups[0]= (char*) "client"; groups[1]= (char*) group; groups[2]=0;
   my_load_defaults(filename, groups, &argc, &argv, NULL);
   if (argc != 1)                /* If some default option */
   {
     char **option=argv;
     while (*++option)
     {
       if (option[0] == args_separator)          /* skip arguments separator */
         continue;
       /* DBUG_PRINT("info",("option: %s",option[0])); */
       if (option[0][0] == '-' && option[0][1] == '-')
       {
     char *end=strcend(*option,'=');
     char *opt_arg=0;
     if (*end)
     {
       opt_arg=end+1;
       *end=0;               /* Remove '=' */
     }
     /* Change all '_' in variable name to '-' */
     for (end= *option ; *(end= strcend(end,'_')) ; )
       *end= '-';
     switch (find_type(*option+2,&option_types,2)) {
     case OPT_port:
       if (opt_arg)
         options->port=atoi(opt_arg);
       break;
     case OPT_socket:
       if (opt_arg)
       {
         my_free(options->unix_socket);
         options->unix_socket=my_strdup(opt_arg,MYF(MY_WME));
       }
       break;
     case OPT_compress:
       options->compress=1;
       options->client_flag|= CLIENT_COMPRESS;
       break;
         case OPT_password:
       if (opt_arg)
       {
         my_free(options->password);
         options->password=my_strdup(opt_arg,MYF(MY_WME));
       }
       break;
         case OPT_pipe:
           options->protocol = MYSQL_PROTOCOL_PIPE;
     case OPT_connect_timeout:
     case OPT_timeout:
       if (opt_arg)
         options->connect_timeout=atoi(opt_arg);
       break;
     case OPT_user:
       if (opt_arg)
       {
         my_free(options->user);
         options->user=my_strdup(opt_arg,MYF(MY_WME));
       }
       break;
     case OPT_init_command:
       add_init_command(options,opt_arg);
       break;
     case OPT_host:
       if (opt_arg)
       {
         my_free(options->host);
         options->host=my_strdup(opt_arg,MYF(MY_WME));
       }
       break;
     case OPT_database:
       if (opt_arg)
       {
         my_free(options->db);
         options->db=my_strdup(opt_arg,MYF(MY_WME));
       }
       break;
     case OPT_debug:
 #ifdef MYSQL_CLIENT
       mysql_debug(opt_arg ? opt_arg : "d:t:o,/tmp/client.trace");
       break;
 #endif
     case OPT_return_found_rows:
       options->client_flag|=CLIENT_FOUND_ROWS;
       break;
 #if defined(HAVE_OPENSSL) && !defined(EMBEDDED_LIBRARY)
     case OPT_ssl_key:
       my_free(options->ssl_key);
           options->ssl_key = my_strdup(opt_arg, MYF(MY_WME));
           break;
     case OPT_ssl_cert:
       my_free(options->ssl_cert);
           options->ssl_cert = my_strdup(opt_arg, MYF(MY_WME));
           break;
     case OPT_ssl_ca:
       my_free(options->ssl_ca);
           options->ssl_ca = my_strdup(opt_arg, MYF(MY_WME));
           break;
     case OPT_ssl_capath:
       my_free(options->ssl_capath);
           options->ssl_capath = my_strdup(opt_arg, MYF(MY_WME));
           break;
         case OPT_ssl_cipher:
           my_free(options->ssl_cipher);
           options->ssl_cipher= my_strdup(opt_arg, MYF(MY_WME));
           break;
 #else
     case OPT_ssl_key:
     case OPT_ssl_cert:
     case OPT_ssl_ca:
     case OPT_ssl_capath:
         case OPT_ssl_cipher:
       break;
 #endif /* HAVE_OPENSSL && !EMBEDDED_LIBRARY */
     case OPT_character_sets_dir:
       my_free(options->charset_dir);
           options->charset_dir = my_strdup(opt_arg, MYF(MY_WME));
       break;
     case OPT_default_character_set:
       my_free(options->charset_name);
           options->charset_name = my_strdup(opt_arg, MYF(MY_WME));
       break;
     case OPT_interactive_timeout:
       options->client_flag|= CLIENT_INTERACTIVE;
       break;
     case OPT_local_infile:
       if (!opt_arg || atoi(opt_arg) != 0)
         options->client_flag|= CLIENT_LOCAL_FILES;
       else
         options->client_flag&= ~CLIENT_LOCAL_FILES;
       break;
     case OPT_disable_local_infile:
       options->client_flag&= ~CLIENT_LOCAL_FILES;
           break;
     case OPT_max_allowed_packet:
           if (opt_arg)
         options->max_allowed_packet= atoi(opt_arg);
       break;
         case OPT_protocol:
           if ((options->protocol= find_type(opt_arg,
                         &sql_protocol_typelib,0)) <= 0)
           {
             fprintf(stderr, "Unknown option to protocol: %s\n", opt_arg);
             exit(1);
           }
           break;
         case OPT_shared_memory_base_name:
 #ifdef HAVE_SMEM
           if (options->shared_memory_base_name != def_shared_memory_base_name)
             my_free(options->shared_memory_base_name);
           options->shared_memory_base_name=my_strdup(opt_arg,MYF(MY_WME));
 #endif
           break;
     case OPT_multi_results:
       options->client_flag|= CLIENT_MULTI_RESULTS;
       break;
     case OPT_multi_statements:
     case OPT_multi_queries:
       options->client_flag|= CLIENT_MULTI_STATEMENTS | CLIENT_MULTI_RESULTS;
       break;
         case OPT_secure_auth:
           options->secure_auth= TRUE;
           break;
         case OPT_report_data_truncation:
           options->report_data_truncation= opt_arg ? test(atoi(opt_arg)) : 1;
           break;
         case OPT_plugin_dir:
           {
             char buff[FN_REFLEN], buff2[FN_REFLEN];
             if (strlen(opt_arg) >= FN_REFLEN)
               opt_arg[FN_REFLEN]= '\0';
             if (my_realpath(buff, opt_arg, 0))
             {
               DBUG_PRINT("warning",("failed to normalize the plugin path: %s",
                                     opt_arg));
               break;
             }
             convert_dirname(buff, buff2, NULL);
             EXTENSION_SET_STRING(options, plugin_dir, buff2);
           }
           break;
         case OPT_default_auth:
           EXTENSION_SET_STRING(options, default_auth, opt_arg);
           break;
     default:
       DBUG_PRINT("warning",("unknown option: %s",option[0]));
     }
       }
     }
   }
   free_defaults(argv);
   DBUG_VOID_RETURN;
 }
References add_init_command(), args_separator, st_mysql_options::charset_dir, st_mysql_options::charset_name, CLIENT_COMPRESS, st_mysql_options::client_flag, CLIENT_FOUND_ROWS, CLIENT_INTERACTIVE, CLIENT_LOCAL_FILES, CLIENT_MULTI_RESULTS, CLIENT_MULTI_STATEMENTS, st_mysql_options::compress, st_mysql_options::connect_timeout, convert_dirname(), st_mysql_options::db, DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, EXTENSION_SET_STRING, find_type(), FN_REFLEN, fprintf(), free_defaults(), st_mysql_options::host, st_mysql_options::max_allowed_packet, my_free(), my_load_defaults(), my_realpath(), my_strdup(), MY_WME, MYF, mysql_debug(), MYSQL_PROTOCOL_PIPE, NULL, OPT_character_sets_dir, OPT_compress, OPT_connect_timeout, OPT_database, OPT_debug, OPT_default_auth, OPT_default_character_set, OPT_disable_local_infile, OPT_host, OPT_init_command, OPT_interactive_timeout, OPT_local_infile, OPT_max_allowed_packet, OPT_multi_queries, OPT_multi_results, OPT_multi_statements, OPT_password, OPT_pipe, OPT_plugin_dir, OPT_port, OPT_protocol, OPT_report_data_truncation, OPT_return_found_rows, OPT_secure_auth, OPT_shared_memory_base_name, OPT_socket, OPT_ssl_ca, OPT_ssl_capath, OPT_ssl_cert, OPT_ssl_cipher, OPT_ssl_key, OPT_timeout, OPT_user, option_types, st_mysql_options::password, st_mysql_options::port, st_mysql_options::protocol, st_mysql_options::report_data_truncation, st_mysql_options::secure_auth, st_mysql_options::shared_memory_base_name, sql_protocol_typelib, st_mysql_options::ssl_ca, st_mysql_options::ssl_capath, st_mysql_options::ssl_cert, st_mysql_options::ssl_cipher, st_mysql_options::ssl_key, strcend(), test, TRUE, st_mysql_options::unix_socket, and st_mysql_options::user.
mysql_reconnect()
my_bool mysql_reconnect (MYSQL * mysql)
Definition at line 3470 of file client.c.
 {
   MYSQL tmp_mysql;
   DBUG_ENTER("mysql_reconnect");
   DBUG_ASSERT(mysql);
   DBUG_PRINT("enter", ("mysql->reconnect: %d", mysql->reconnect));
   if (!mysql->reconnect ||
       (mysql->server_status & SERVER_STATUS_IN_TRANS) || !mysql->host_info)
   {
     /* Allow reconnect next time */
     mysql->server_status&= ~SERVER_STATUS_IN_TRANS;
     set_mysql_error(mysql, CR_SERVER_GONE_ERROR, unknown_sqlstate);
     DBUG_RETURN(1);
   }
   mysql_init(&tmp_mysql);
   tmp_mysql.options= mysql->options;
   tmp_mysql.options.my_cnf_file= tmp_mysql.options.my_cnf_group= 0;
   if (!mysql_real_connect(&tmp_mysql,mysql->host,mysql->user,mysql->passwd,
               mysql->db, mysql->port, mysql->unix_socket,
               mysql->client_flag | CLIENT_REMEMBER_OPTIONS))
   {
     mysql->net.last_errno= tmp_mysql.net.last_errno;
     strmov(mysql->net.last_error, tmp_mysql.net.last_error);
     strmov(mysql->net.sqlstate, tmp_mysql.net.sqlstate);
     DBUG_RETURN(1);
   }
   if (mysql_set_character_set(&tmp_mysql, mysql->charset->csname))
   {
     DBUG_PRINT("error", ("mysql_set_character_set() failed"));
     bzero((char*) &tmp_mysql.options,sizeof(tmp_mysql.options));
     mysql_close(&tmp_mysql);
     mysql->net.last_errno= tmp_mysql.net.last_errno;
     strmov(mysql->net.last_error, tmp_mysql.net.last_error);
     strmov(mysql->net.sqlstate, tmp_mysql.net.sqlstate);
     DBUG_RETURN(1);
   }
   DBUG_PRINT("info", ("reconnect succeded"));
   tmp_mysql.reconnect= 1;
   tmp_mysql.free_me= mysql->free_me;
   /* Move prepared statements (if any) over to the new mysql object */
   tmp_mysql.stmts= mysql->stmts;
   mysql->stmts= 0;
   /* Don't free options as these are now used in tmp_mysql */
   bzero((char*) &mysql->options,sizeof(mysql->options));
   mysql->free_me=0;
   mysql_close(mysql);
   *mysql=tmp_mysql;
   net_clear(&mysql->net, 1);
   mysql->affected_rows= ~(my_ulonglong) 0;
   DBUG_RETURN(0);
 }
References st_mysql::affected_rows, bzero, st_mysql::charset, st_mysql::client_flag, CLIENT_REMEMBER_OPTIONS, CR_SERVER_GONE_ERROR, charset_info_st::csname, st_mysql::db, DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, st_mysql::free_me, st_mysql::host, st_mysql::host_info, st_net::last_errno, st_net::last_error, st_mysql_options::my_cnf_file, st_mysql_options::my_cnf_group, mysql_close(), mysql_init(), mysql_real_connect(), mysql_set_character_set(), st_mysql::net, net_clear(), st_mysql::options, st_mysql::passwd, st_mysql::port, st_mysql::reconnect, st_mysql::server_status, SERVER_STATUS_IN_TRANS, set_mysql_error(), st_net::sqlstate, st_mysql::stmts, strmov(), st_mysql::unix_socket, unknown_sqlstate, and st_mysql::user.
Referenced by cli_advanced_command().
net_clear_error()
void net_clear_error (NET * net)
Clear possible error state of struct NET
Parameters
net clear the state of the argument
Definition at line 361 of file client.c.
 {
   net->last_errno= 0;
   net->last_error[0]= '\0';
   strmov(net->sqlstate, not_error_sqlstate);
 }
References st_net::last_errno, st_net::last_error, not_error_sqlstate, st_net::sqlstate, and strmov().
Referenced by cli_advanced_command(), CLI_MYSQL_REAL_CONNECT(), mysql_next_result(), and mysql_stmt_close().
run_plugin_auth()
int run_plugin_auth (MYSQL * mysql, char * data, uint data_len, const char * data_plugin, const char * db)
Client side of the plugin driver authentication.
Note
this is used by both the mysql_real_connect and mysql_change_user
Parameters
mysql mysql
data pointer to the plugin auth data (scramble) in the handshake packet
data_len the length of the data
data_plugin a plugin that data were prepared for or 0 if it's mysql_change_user()
db initial db to use, can be 0
Return values
0 ok
1 error
Definition at line 2751 of file client.c.
 {
   const char    *auth_plugin_name;
   auth_plugin_t *auth_plugin;
   MCPVIO_EXT    mpvio;
   ulong     pkt_length;
   int           res;
   DBUG_ENTER ("run_plugin_auth");
   /* determine the default/initial plugin to use */
   if (mysql->options.extension && mysql->options.extension->default_auth &&
       mysql->server_capabilities & CLIENT_PLUGIN_AUTH)
   {
     auth_plugin_name= mysql->options.extension->default_auth;
     if (!(auth_plugin= (auth_plugin_t*) mysql_client_find_plugin(mysql,
                        auth_plugin_name, MYSQL_CLIENT_AUTHENTICATION_PLUGIN)))
       DBUG_RETURN (1); /* oops, not found */
   }
   else
   {
     auth_plugin= mysql->server_capabilities & CLIENT_PROTOCOL_41 ?
       &native_password_client_plugin : &old_password_client_plugin;
     auth_plugin_name= auth_plugin->name;
   }
   DBUG_PRINT ("info", ("using plugin %s", auth_plugin_name));
   mysql->net.last_errno= 0; /* just in case */
   if (data_plugin && strcmp(data_plugin, auth_plugin_name))
   {
     /* data was prepared for a different plugin, don't show it to this one */
     data= 0;
     data_len= 0;
   }
   mpvio.mysql_change_user= data_plugin == 0;
   mpvio.cached_server_reply.pkt= (uchar*)data;
   mpvio.cached_server_reply.pkt_len= data_len;
   mpvio.read_packet= client_mpvio_read_packet;
   mpvio.write_packet= client_mpvio_write_packet;
   mpvio.info= client_mpvio_info;
   mpvio.mysql= mysql;
   mpvio.packets_read= mpvio.packets_written= 0;
   mpvio.db= db;
   mpvio.plugin= auth_plugin;
   res= auth_plugin->authenticate_user((struct st_plugin_vio *)&mpvio, mysql);
   DBUG_PRINT ("info", ("authenticate_user returned %s",
                        res == CR_OK ? "CR_OK" :
                        res == CR_ERROR ? "CR_ERROR" :
                        res == CR_OK_HANDSHAKE_COMPLETE ?
                          "CR_OK_HANDSHAKE_COMPLETE" : "error"));
   compile_time_assert(CR_OK == -1);
   compile_time_assert(CR_ERROR == 0);
   if (res > CR_OK && mysql->net.read_pos[0] != 254)
   {
     /*
       the plugin returned an error. write it down in mysql,
       unless the error code is CR_ERROR and mysql->net.last_errno
       is already set (the plugin has done it)
     */
     DBUG_PRINT ("info", ("res=%d", res));
     if (res > CR_ERROR)
       set_mysql_error(mysql, res, unknown_sqlstate);
     else
       if (!mysql->net.last_errno)
         set_mysql_error(mysql, CR_UNKNOWN_ERROR, unknown_sqlstate);
     DBUG_RETURN (1);
   }
   /* read the OK packet (or use the cached value in mysql->net.read_pos */
   if (res == CR_OK)
     pkt_length= (*mysql->methods->read_change_user_result)(mysql);
   else /* res == CR_OK_HANDSHAKE_COMPLETE */
     pkt_length= mpvio.last_read_packet_len;
   DBUG_PRINT ("info", ("OK packet length=%lu", pkt_length));
   if (pkt_length == packet_error)
   {
     if (mysql->net.last_errno == CR_SERVER_LOST)
       set_mysql_extended_error(mysql, CR_SERVER_LOST, unknown_sqlstate,
                                ER(CR_SERVER_LOST_EXTENDED),
                                "reading authorization packet",
                                errno);
     DBUG_RETURN (1);
   }
   if (mysql->net.read_pos[0] == 254)
   {
     /* The server asked to use a different authentication plugin */
     if (pkt_length == 1)
     {
       /* old "use short scramble" packet */
       DBUG_PRINT ("info", ("old use short scramble packet from server"));
       auth_plugin_name= old_password_plugin_name;
       mpvio.cached_server_reply.pkt= (uchar*)mysql->scramble;
       mpvio.cached_server_reply.pkt_len= SCRAMBLE_LENGTH + 1;
     }
     else
     {
       /* new "use different plugin" packet */
       uint len;
       auth_plugin_name= (char*)mysql->net.read_pos + 1;
       len= strlen(auth_plugin_name); /* safe as my_net_read always appends \0 */
       mpvio.cached_server_reply.pkt_len= pkt_length - len - 2;
       mpvio.cached_server_reply.pkt= mysql->net.read_pos + len + 2;
       DBUG_PRINT ("info", ("change plugin packet from server for plugin %s",
                            auth_plugin_name));
     }
     if (!(auth_plugin= (auth_plugin_t *) mysql_client_find_plugin(mysql,
                          auth_plugin_name, MYSQL_CLIENT_AUTHENTICATION_PLUGIN)))
       DBUG_RETURN (1);
     mpvio.plugin= auth_plugin;
     res= auth_plugin->authenticate_user((struct st_plugin_vio *)&mpvio, mysql);
     DBUG_PRINT ("info", ("second authenticate_user returned %s",
                          res == CR_OK ? "CR_OK" :
                          res == CR_ERROR ? "CR_ERROR" :
                          res == CR_OK_HANDSHAKE_COMPLETE ?
                          "CR_OK_HANDSHAKE_COMPLETE" : "error"));
     if (res > CR_OK)
     {
       if (res > CR_ERROR)
         set_mysql_error(mysql, res, unknown_sqlstate);
       else
         if (!mysql->net.last_errno)
           set_mysql_error(mysql, CR_UNKNOWN_ERROR, unknown_sqlstate);
       DBUG_RETURN (1);
     }
     if (res != CR_OK_HANDSHAKE_COMPLETE)
     {
       /* Read what server thinks about out new auth message report */
       if (cli_safe_read(mysql) == packet_error)
       {
         if (mysql->net.last_errno == CR_SERVER_LOST)
           set_mysql_extended_error(mysql, CR_SERVER_LOST, unknown_sqlstate,
                                    ER(CR_SERVER_LOST_EXTENDED),
                                    "reading final connect information",
                                    errno);
         DBUG_RETURN (1);
       }
     }
   }
   /*
     net->read_pos[0] should always be 0 here if the server implements
     the protocol correctly
   */
   DBUG_RETURN (mysql->net.read_pos[0] != 0);
 }
References MCPVIO_EXT::cached_server_reply, cli_safe_read(), client_mpvio_info(), client_mpvio_read_packet(), client_mpvio_write_packet(), CLIENT_PLUGIN_AUTH, CLIENT_PROTOCOL_41, compile_time_assert, CR_ERROR, CR_OK, CR_OK_HANDSHAKE_COMPLETE, CR_SERVER_LOST, CR_SERVER_LOST_EXTENDED, CR_UNKNOWN_ERROR, MCPVIO_EXT::db, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, st_mysql_options_extention::default_auth, ER, errno, st_mysql_options::extension, MCPVIO_EXT::info, st_net::last_errno, MCPVIO_EXT::last_read_packet_len, st_mysql::methods, MCPVIO_EXT::mysql, MCPVIO_EXT::mysql_change_user, MYSQL_CLIENT_AUTHENTICATION_PLUGIN, mysql_client_find_plugin(), native_password_client_plugin, st_mysql::net, old_password_client_plugin, old_password_plugin_name, st_mysql::options, packet_error, MCPVIO_EXT::packets_read, MCPVIO_EXT::packets_written, MCPVIO_EXT::pkt, MCPVIO_EXT::pkt_len, MCPVIO_EXT::plugin, st_mysql_methods::read_change_user_result, MCPVIO_EXT::read_packet, st_net::read_pos, st_mysql::scramble, SCRAMBLE_LENGTH, st_mysql::server_capabilities, set_mysql_error(), set_mysql_extended_error(), unknown_sqlstate, and MCPVIO_EXT::write_packet.
Referenced by CLI_MYSQL_REAL_CONNECT(), and mysql_change_user().
set_mysql_error()
void set_mysql_error (MYSQL * mysql, int errcode, const char * sqlstate)
Set the internal error message to mysql handler
Parameters
mysql connection handle (client side)
errcode CR_ error code, passed to ER macro to get error text @parma sqlstate SQL standard sqlstate
Definition at line 333 of file client.c.
 {
   NET *net;
   DBUG_ENTER("set_mysql_error");
   DBUG_PRINT("enter", ("error :%d '%s'", errcode, ER(errcode)));
   DBUG_ASSERT(mysql != 0);
   if (mysql)
   {
     net= &mysql->net;
     net->last_errno= errcode;
     strmov(net->last_error, ER(errcode));
     strmov(net->sqlstate, sqlstate);
   }
   else
   {
     mysql_server_last_errno= errcode;
     strmov(mysql_server_last_error, ER(errcode));
   }
   DBUG_VOID_RETURN;
 }
References DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, ER, st_net::last_errno, st_net::last_error, mysql_server_last_errno, mysql_server_last_error, st_mysql::net, st_net::sqlstate, and strmov().
Referenced by cli_advanced_command(), CLI_MYSQL_REAL_CONNECT(), cli_read_query_result(), cli_read_rows(), cli_read_statistics(), cli_safe_read(), cli_use_result(), handle_local_infile(), mysql_fetch_row(), mysql_init(), mysql_next_result(), mysql_reconnect(), mysql_stmt_init(), mysql_store_result(), read_one_row(), run_plugin_auth(), send_change_user_packet(), and send_client_reply_packet().
set_mysql_extended_error()
void set_mysql_extended_error (MYSQL * mysql, int errcode, const char * sqlstate, const char * format, ...)
Set an error message on the client.
Parameters
mysql connection handle
errcode CR_* errcode, for client errors
sqlstate SQL standard sql state, unknown_sqlstate for the majority of client errors.
format error message template, in sprintf format
... variable number of arguments
Definition at line 379 of file client.c.
 {
   NET *net;
   va_list args;
   DBUG_ENTER("set_mysql_extended_error");
   DBUG_PRINT("enter", ("error :%d '%s'", errcode, format));
   DBUG_ASSERT(mysql != 0);
   net= &mysql->net;
   net->last_errno= errcode;
   va_start(args, format);
   my_vsnprintf(net->last_error, sizeof(net->last_error)-1,
                format, args);
   va_end(args);
   strmov(net->sqlstate, sqlstate);
   DBUG_VOID_RETURN;
 }
References DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, format(), st_net::last_errno, st_net::last_error, my_vsnprintf(), st_mysql::net, st_net::sqlstate, and strmov().
Referenced by add_plugin(), CLI_MYSQL_REAL_CONNECT(), client_mpvio_write_packet(), is_not_initialized(), mysql_client_find_plugin(), mysql_client_register_plugin(), mysql_init_character_set(), mysql_load_plugin_v(), mysql_set_character_set(), run_plugin_auth(), and send_client_reply_packet().
set_stmt_errmsg()
void set_stmt_errmsg (MYSQL_STMT * stmt, NET * net)
Set statement error code, sqlstate, and error message from NET.
Parameters
stmt a statement handle. Copy the error here.
net mysql->net. Source of the error.
Definition at line 1363 of file libmysql.c.
 {
   DBUG_ENTER("set_stmt_errmsg");
   DBUG_PRINT("enter", ("error: %d/%s '%s'",
                        net->last_errno,
                        net->sqlstate,
                        net->last_error));
   DBUG_ASSERT(stmt != 0);
   stmt->last_errno= net->last_errno;
   if (net->last_error && net->last_error[0])
     strmov(stmt->last_error, net->last_error);
   strmov(stmt->sqlstate, net->sqlstate);
   DBUG_VOID_RETURN;
 }
References DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, st_mysql_stmt::last_errno, st_net::last_errno, st_mysql_stmt::last_error, st_net::last_error, st_mysql_stmt::sqlstate, st_net::sqlstate, and strmov().
Referenced by cli_read_binary_rows(), cli_stmt_execute(), execute(), mysql_stmt_close(), mysql_stmt_next_result(), mysql_stmt_prepare(), mysql_stmt_send_long_data(), mysql_stmt_store_result(), reset_stmt_handle(), stmt_read_row_from_cursor(), stmt_read_row_unbuffered(), and store_param().
set_stmt_error()
void set_stmt_error (MYSQL_STMT * stmt, int errcode, const char * sqlstate, const char * err)
Set statement error code, sqlstate, and error message from given errcode and sqlstate.
Definition at line 1338 of file libmysql.c.
 {
   DBUG_ENTER("set_stmt_error");
   DBUG_PRINT("enter", ("error: %d '%s'", errcode, ER(errcode)));
   DBUG_ASSERT(stmt != 0);
   if (err == 0)
     err= ER(errcode);
   stmt->last_errno= errcode;
   strmov(stmt->last_error, ER(errcode));
   strmov(stmt->sqlstate, sqlstate);
   DBUG_VOID_RETURN;
 }
References DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, ER, st_mysql_stmt::last_errno, st_mysql_stmt::last_error, st_mysql_stmt::sqlstate, and strmov().
Referenced by alloc_stmt_fields(), cli_read_binary_rows(), cli_stmt_execute(), mysql_detach_stmt_list(), mysql_stmt_attr_set(), mysql_stmt_bind_param(), mysql_stmt_bind_result(), mysql_stmt_fetch_column(), mysql_stmt_prepare(), mysql_stmt_reset(), mysql_stmt_result_metadata(), mysql_stmt_send_long_data(), mysql_stmt_store_result(), stmt_read_row_no_result_set(), stmt_read_row_unbuffered(), and update_stmt_fields().
unpack_fields()
MYSQL_FIELD* unpack_fields (MYSQL_DATA * data, MEM_ROOT * alloc, uint fields, my_bool default_value, uint server_capabilities)
Definition at line 1430 of file client.c.
 {
   MYSQL_ROWS    *row;
   MYSQL_FIELD   *field,*result;
   ulong lengths[9];             /* Max of fields */
   DBUG_ENTER("unpack_fields");
   field= result= (MYSQL_FIELD*) alloc_root(alloc,
                        (uint) sizeof(*field)*fields);
   if (!result)
   {
     free_rows(data);                /* Free old data */
     DBUG_RETURN(0);
   }
   bzero((char*) field, (uint) sizeof(MYSQL_FIELD)*fields);
   if (server_capabilities & CLIENT_PROTOCOL_41)
   {
     /* server is 4.1, and returns the new field result format */
     for (row=data->data; row ; row = row->next,field++)
     {
       uchar *pos;
       /* fields count may be wrong */
       DBUG_ASSERT((uint) (field - result) < fields);
       cli_fetch_lengths(&lengths[0], row->data, default_value ? 8 : 7);
       field->catalog=   strmake_root(alloc,(char*) row->data[0], lengths[0]);
       field->db=        strmake_root(alloc,(char*) row->data[1], lengths[1]);
       field->table=     strmake_root(alloc,(char*) row->data[2], lengths[2]);
       field->org_table= strmake_root(alloc,(char*) row->data[3], lengths[3]);
       field->name=      strmake_root(alloc,(char*) row->data[4], lengths[4]);
       field->org_name=  strmake_root(alloc,(char*) row->data[5], lengths[5]);
       field->catalog_length=    lengths[0];
       field->db_length=     lengths[1];
       field->table_length=  lengths[2];
       field->org_table_length=  lengths[3];
       field->name_length=   lengths[4];
       field->org_name_length=   lengths[5];
       /* Unpack fixed length parts */
       pos= (uchar*) row->data[6];
       field->charsetnr= uint2korr(pos);
       field->length=    (uint) uint4korr(pos+2);
       field->type=  (enum enum_field_types) pos[6];
       field->flags= uint2korr(pos+7);
       field->decimals=  (uint) pos[9];
       if (IS_NUM(field->type))
         field->flags|= NUM_FLAG;
       if (default_value && row->data[7])
       {
         field->def=strmake_root(alloc,(char*) row->data[7], lengths[7]);
     field->def_length= lengths[7];
       }
       else
         field->def=0;
       field->max_length= 0;
     }
   }
 #ifndef DELETE_SUPPORT_OF_4_0_PROTOCOL
   else
   {
     /* old protocol, for backward compatibility */
     for (row=data->data; row ; row = row->next,field++)
     {
       cli_fetch_lengths(&lengths[0], row->data, default_value ? 6 : 5);
       field->org_table= field->table=  strdup_root(alloc,(char*) row->data[0]);
       field->name=   strdup_root(alloc,(char*) row->data[1]);
       field->length= (uint) uint3korr(row->data[2]);
       field->type=   (enum enum_field_types) (uchar) row->data[3][0];
       field->catalog=(char*)  "";
       field->db=     (char*)  "";
       field->catalog_length= 0;
       field->db_length= 0;
       field->org_table_length=  field->table_length=    lengths[0];
       field->name_length=   lengths[1];
       if (server_capabilities & CLIENT_LONG_FLAG)
       {
         field->flags=   uint2korr(row->data[4]);
         field->decimals=(uint) (uchar) row->data[4][2];
       }
       else
       {
         field->flags=   (uint) (uchar) row->data[4][0];
         field->decimals=(uint) (uchar) row->data[4][1];
       }
       if (IS_NUM(field->type))
         field->flags|= NUM_FLAG;
       if (default_value && row->data[5])
       {
         field->def=strdup_root(alloc,(char*) row->data[5]);
     field->def_length= lengths[5];
       }
       else
         field->def=0;
       field->max_length= 0;
     }
   }
 #endif /* DELETE_SUPPORT_OF_4_0_PROTOCOL */
   free_rows(data);              /* Free old data */
   DBUG_RETURN(result);
 }
References alloc_root(), bzero, st_mysql_field::catalog, st_mysql_field::catalog_length, st_mysql_field::charsetnr, cli_fetch_lengths(), CLIENT_LONG_FLAG, CLIENT_PROTOCOL_41, st_mysql_rows::data, st_mysql_field::db, st_mysql_field::db_length, DBUG_ASSERT, DBUG_ENTER, DBUG_RETURN, st_mysql_field::decimals, st_mysql_field::def, st_mysql_field::def_length, st_mysql_field::flags, free_rows(), if(), IS_NUM, st_mysql_field::length, st_mysql_field::max_length, st_mysql_field::name, st_mysql_field::name_length, st_mysql_rows::next, NUM_FLAG, st_mysql_field::org_name, st_mysql_field::org_name_length, st_mysql_field::org_table, st_mysql_field::org_table_length, pos(), strdup_root(), strmake_root(), st_mysql_field::table, st_mysql_field::table_length, st_mysql_field::type, uint2korr, uint3korr, and uint4korr.
Referenced by cli_list_fields(), cli_read_prepare_result(), cli_read_query_result(), and mysql_list_processes().
Variable Documentation
cant_connect_sqlstate
const char* cant_connect_sqlstate extern
Definition at line 122 of file client.c.
Referenced by mysql_sqlstate().
default_client_charset_info
CHARSET_INFO* default_client_charset_info extern
Definition at line 136 of file client.c.
Referenced by mysql_init().
mysql_client_builtins
struct st_mysql_client_plugin* mysql_client_builtins[] extern
Definition at line 2297 of file client.c.
Referenced by mysql_client_plugin_init().
not_error_sqlstate
const char* not_error_sqlstate extern
Definition at line 121 of file client.c.
Referenced by mysql_init(), mysql_stmt_init(), net_clear_error(), and stmt_clear_error().
unknown_sqlstate
const char* unknown_sqlstate extern
Definition at line 120 of file client.c.
Referenced by add_plugin(), alloc_stmt_fields(), cli_advanced_command(), CLI_MYSQL_REAL_CONNECT(), cli_read_binary_rows(), cli_read_query_result(), cli_read_rows(), cli_read_statistics(), cli_safe_read(), cli_stmt_execute(), cli_use_result(), client_mpvio_write_packet(), handle_local_infile(), is_not_initialized(), my_realloc_str(), mysql_client_find_plugin(), mysql_client_register_plugin(), mysql_detach_stmt_list(), mysql_fetch_row(), mysql_init(), mysql_init_character_set(), mysql_load_plugin_v(), mysql_next_result(), mysql_prune_stmt_list(), mysql_reconnect(), mysql_set_character_set(), mysql_stmt_attr_set(), mysql_stmt_bind_param(), mysql_stmt_bind_result(), mysql_stmt_fetch_column(), mysql_stmt_init(), mysql_stmt_prepare(), mysql_stmt_reset(), mysql_stmt_result_metadata(), mysql_stmt_send_long_data(), mysql_stmt_store_result(), mysql_store_result(), read_one_row(), run_plugin_auth(), send_change_user_packet(), send_client_reply_packet(), stmt_read_row_no_result_set(), stmt_read_row_unbuffered(), and update_stmt_fields().