Azerotcore-wotlk: Acore::NearestAssistCreatureInCreatureRangeCheck Class Reference
Acore::NearestAssistCreatureInCreatureRangeCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
NearestAssistCreatureInCreatureRangeCheck (Creature *obj, Unit *enemy, float range)
bool operator() (Creature *u)
Private Member Functions
NearestAssistCreatureInCreatureRangeCheck (NearestAssistCreatureInCreatureRangeCheck const &)
Private Attributes
Creature *const i_obj
Unit *const i_enemy
float i_range
Detailed Description
Definition at line 1176 of file GridNotifiers.h.
Constructor & Destructor Documentation
NearestAssistCreatureInCreatureRangeCheck() [1/2]
Acore::NearestAssistCreatureInCreatureRangeCheck::NearestAssistCreatureInCreatureRangeCheck (Creature * obj, Unit * enemy, float range) inline
Definition at line 1179 of file GridNotifiers.h.
             : i_obj(obj), i_enemy(enemy), i_range(range) {}
NearestAssistCreatureInCreatureRangeCheck() [2/2]
Acore::NearestAssistCreatureInCreatureRangeCheck::NearestAssistCreatureInCreatureRangeCheck (NearestAssistCreatureInCreatureRangeCheck const &) private
Member Function Documentation
operator()()
bool Acore::NearestAssistCreatureInCreatureRangeCheck::operator() (Creature * u) inline
Definition at line 1182 of file GridNotifiers.h.
         {
             if (u == i_obj)
                 return false;
             if (!u->CanAssistTo(i_obj, i_enemy))
                 return false;
             if (!i_obj->IsWithinDistInMap(u, i_range))
                 return false;
             if (!i_obj->IsWithinLOSInMap(u))
                 return false;
             i_range = i_obj->GetDistance(u);            // use found unit range as new range limit for next check
             return true;
         }
References Creature::CanAssistTo(), WorldObject::GetDistance(), i_enemy, i_obj, i_range, WorldObject::IsWithinDistInMap(), and WorldObject::IsWithinLOSInMap().
Member Data Documentation
i_enemy
Unit* const Acore::NearestAssistCreatureInCreatureRangeCheck::i_enemy private
Definition at line 1200 of file GridNotifiers.h.
Referenced by operator()().
i_obj
Creature* const Acore::NearestAssistCreatureInCreatureRangeCheck::i_obj private
Definition at line 1199 of file GridNotifiers.h.
Referenced by operator()().
i_range
float Acore::NearestAssistCreatureInCreatureRangeCheck::i_range private
Definition at line 1201 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/game/Grids/Notifiers/GridNotifiers.h