Azerotcore-wotlk: npc_barnes Class Reference
npc_barnes Class Reference
Classes
struct npc_barnesAI
Public Member Functions
npc_barnes ()
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
bool OnGossipHello (Player *player, Creature *creature) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 124 of file karazhan.cpp.
Constructor & Destructor Documentation
npc_barnes()
npc_barnes::npc_barnes () inline
Definition at line 127 of file karazhan.cpp.
 : CreatureScript("npc_barnes") { }
Member Function Documentation
GetAI()
CreatureAI* npc_barnes::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 405 of file karazhan.cpp.
     {
         return GetKarazhanAI<npc_barnesAI>(creature);
     }
OnGossipHello()
bool npc_barnes::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 373 of file karazhan.cpp.
     {
         if (InstanceScript* instance = creature->GetInstanceScript())
         {
             // Check for death of Moroes and if opera event is not done already
             if (instance->GetBossState(DATA_MOROES) == DONE &&  instance->GetBossState(DATA_OPERA_PERFORMANCE) != DONE)
             {
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, OZ_GOSSIP1, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
                 if (player->IsGameMaster())
                 {
                     AddGossipItemFor(player, GOSSIP_ICON_DOT, OZ_GM_GOSSIP1, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 3);
                     AddGossipItemFor(player, GOSSIP_ICON_DOT, OZ_GM_GOSSIP2, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 4);
                     AddGossipItemFor(player, GOSSIP_ICON_DOT, OZ_GM_GOSSIP3, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 5);
                 }
                 if (npc_barnesAI* pBarnesAI = CAST_AI(npc_barnes::npc_barnesAI, creature->AI()))
                 {
                     if (!pBarnesAI->RaidWiped)
                         SendGossipMenuFor(player, 8970, creature->GetGUID());
                     else
                         SendGossipMenuFor(player, 8975, creature->GetGUID());
                     return true;
                 }
             }
         }
         SendGossipMenuFor(player, 8978, creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), Creature::AI(), CAST_AI, DATA_MOROES, DATA_OPERA_PERFORMANCE, DONE, Object::GetGUID(), WorldObject::GetInstanceScript(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ICON_DOT, GOSSIP_SENDER_MAIN, Player::IsGameMaster(), OZ_GM_GOSSIP1, OZ_GM_GOSSIP2, OZ_GM_GOSSIP3, OZ_GOSSIP1, and SendGossipMenuFor().
OnGossipSelect()
bool npc_barnes::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 340 of file karazhan.cpp.
     {
         ClearGossipMenuFor(player);
         npc_barnesAI* pBarnesAI = CAST_AI(npc_barnes::npc_barnesAI, creature->AI());
         switch (action)
         {
             case GOSSIP_ACTION_INFO_DEF+1:
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, OZ_GOSSIP2, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
                 SendGossipMenuFor(player, 8971, creature->GetGUID());
                 break;
             case GOSSIP_ACTION_INFO_DEF+2:
                 CloseGossipMenuFor(player);
                 pBarnesAI->m_uiEventId = urand(EVENT_OZ, EVENT_RAJ);
                 pBarnesAI->StartEvent();
                 break;
             case GOSSIP_ACTION_INFO_DEF+3:
                 CloseGossipMenuFor(player);
                 pBarnesAI->m_uiEventId = EVENT_OZ;
                 break;
             case GOSSIP_ACTION_INFO_DEF+4:
                 CloseGossipMenuFor(player);
                 pBarnesAI->m_uiEventId = EVENT_HOOD;
                 break;
             case GOSSIP_ACTION_INFO_DEF+5:
                 CloseGossipMenuFor(player);
                 pBarnesAI->m_uiEventId = EVENT_RAJ;
                 break;
         }
         return true;
     }
References AddGossipItemFor(), Creature::AI(), CAST_AI, ClearGossipMenuFor(), CloseGossipMenuFor(), EVENT_HOOD, EVENT_OZ, EVENT_RAJ, Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, npc_barnes::npc_barnesAI::m_uiEventId, OZ_GOSSIP2, SendGossipMenuFor(), npc_barnes::npc_barnesAI::StartEvent(), and urand().
The documentation for this class was generated from the following file:
src/server/scripts/EasternKingdoms/Karazhan/karazhan.cpp