Azerotcore-wotlk: IgbArtilleryCheck Class Reference
IgbArtilleryCheck Class Reference
Public Member Functions
IgbArtilleryCheck (uint32 entry)
bool operator() (WorldObject *unit)
Private Attributes
uint32 _entry
Detailed Description
Definition at line 2545 of file boss_icecrown_gunship_battle.cpp.
Constructor & Destructor Documentation
IgbArtilleryCheck()
IgbArtilleryCheck::IgbArtilleryCheck (uint32 entry) inline
Definition at line 2548 of file boss_icecrown_gunship_battle.cpp.
 : _entry(entry) {}
Member Function Documentation
operator()()
bool IgbArtilleryCheck::operator() (WorldObject * unit) inline
Definition at line 2550 of file boss_icecrown_gunship_battle.cpp.
     {
         return unit->GetTypeId() != TYPEID_PLAYER || unit->GetPositionZ() > 478.0f || !unit->GetTransport() || unit->GetTransport()->GetEntry() != _entry
         || unit->GetMapHeight(unit->GetPhaseMask(), unit->GetPositionX(), unit->GetPositionY(), unit->GetPositionZ()) < 465.0f;
     }
References _entry, Object::GetEntry(), WorldObject::GetMapHeight(), WorldObject::GetPhaseMask(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), WorldObject::GetTransport(), Object::GetTypeId(), and TYPEID_PLAYER.
Member Data Documentation
_entry
uint32 IgbArtilleryCheck::_entry private
Definition at line 2557 of file boss_icecrown_gunship_battle.cpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp