Azerotcore-wotlk: at_lady_deathwhisper_entrance Class Reference
at_lady_deathwhisper_entrance Class Reference
Public Member Functions
at_lady_deathwhisper_entrance ()
bool OnTrigger (Player *player, AreaTrigger const *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 1172 of file boss_lady_deathwhisper.cpp.
Constructor & Destructor Documentation
at_lady_deathwhisper_entrance()
at_lady_deathwhisper_entrance::at_lady_deathwhisper_entrance () inline
Definition at line 1175 of file boss_lady_deathwhisper.cpp.
 : AreaTriggerScript("at_lady_deathwhisper_entrance") { }
Member Function Documentation
OnTrigger()
bool at_lady_deathwhisper_entrance::OnTrigger (Player * player, AreaTrigger const *) inline override virtual
Reimplemented from AreaTriggerScript.
Definition at line 1177 of file boss_lady_deathwhisper.cpp.
     {
         if (InstanceScript* instance = player->GetInstanceScript())
             if (instance->GetBossState(DATA_LADY_DEATHWHISPER) != DONE)
                 if (!player->IsGameMaster())
                     if (Creature* ladyDeathwhisper = ObjectAccessor::GetCreature(*player, instance->GetGuidData(DATA_LADY_DEATHWHISPER)))
                         ladyDeathwhisper->AI()->DoAction(ACTION_START_INTRO);
         return true;
     }
References ACTION_START_INTRO, DATA_LADY_DEATHWHISPER, DONE, ObjectAccessor::GetCreature(), WorldObject::GetInstanceScript(), and Player::IsGameMaster().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_lady_deathwhisper.cpp