Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/jemalloc_internal_inlines_a.h File Reference
jemalloc_internal_inlines_a.h File Reference
#include "jemalloc/internal/atomic.h"
#include "jemalloc/internal/bit_util.h"
#include "jemalloc/internal/jemalloc_internal_types.h"
#include "jemalloc/internal/sc.h"
#include "jemalloc/internal/ticker.h"
Functions
JEMALLOC_ALWAYS_INLINE malloc_cpuid_t malloc_getcpu (void)
JEMALLOC_ALWAYS_INLINE unsigned percpu_arena_choose (void)
JEMALLOC_ALWAYS_INLINE unsigned percpu_arena_ind_limit (percpu_arena_mode_t mode)
static arena_tdata_t * arena_tdata_get (tsd_t *tsd, unsigned ind, bool refresh_if_missing)
static arena_t * arena_get (tsdn_t *tsdn, unsigned ind, bool init_if_missing)
static ticker_t * decay_ticker_get (tsd_t *tsd, unsigned ind)
JEMALLOC_ALWAYS_INLINE cache_bin_t * tcache_small_bin_get (tcache_t *tcache, szind_t binind)
JEMALLOC_ALWAYS_INLINE cache_bin_t * tcache_large_bin_get (tcache_t *tcache, szind_t binind)
JEMALLOC_ALWAYS_INLINE bool tcache_available (tsd_t *tsd)
JEMALLOC_ALWAYS_INLINE tcache_t * tcache_get (tsd_t *tsd)
static void pre_reentrancy (tsd_t *tsd, arena_t *arena)
static void post_reentrancy (tsd_t *tsd)
Function Documentation
arena_get()
static arena_t* arena_get (tsdn_t * tsdn, unsigned ind, bool init_if_missing) inline static
Definition at line 85 of file jemalloc_internal_inlines_a.h.
{
     arena_t *ret;
     assert(ind < MALLOCX_ARENA_LIMIT);
     ret = (arena_t *)atomic_load_p(&arenas[ind], ATOMIC_ACQUIRE);
     if (unlikely(ret == NULL)) {
         if (init_if_missing) {
             ret = arena_init(tsdn, ind,
                 (extent_hooks_t *)&extent_hooks_default);
         }
     }
     return ret;
 }
References arena_init, arenas, assert(), ATOMIC_ACQUIRE, extent_hooks_default, MALLOCX_ARENA_LIMIT, NULL, ret, and unlikely.
Referenced by a0ialloc(), arena_bind(), arena_choose_hard(), arena_choose_huge(), arena_choose_impl(), arena_i_decay(), arena_i_decay_ms_ctl_impl(), arena_i_dss_ctl(), arena_i_extent_hooks_ctl(), arena_i_reset_destroy_helper(), arena_i_retain_grow_limit_ctl(), arena_init_locked(), arena_migrate(), arena_unbind(), arenas_i(), ctl_refresh(), CTL_RO_NL_GEN(), experimental_arenas_i_pactivep_ctl(), extent_alloc_default(), extent_hook_pre_reentrancy(), imalloc_no_sample(), je_rallocx(), jemalloc_postfork_child(), jemalloc_postfork_parent(), jemalloc_prefork(), malloc_init_hard_a0_locked(), percpu_arena_update(), pre_reentrancy(), prof_gctx_create(), prof_log_bt_index(), prof_log_thr_index(), prof_tdata_init_impl(), prof_thread_name_alloc(), prof_try_log(), stats_print_atexit(), tcache_bin_flush_large(), tcache_bin_flush_small(), tcache_create_explicit(), tcache_destroy(), and tsd_tcache_data_init().
arena_tdata_get()
static arena_tdata_t* arena_tdata_get (tsd_t * tsd, unsigned ind, bool refresh_if_missing) inline static
Definition at line 60 of file jemalloc_internal_inlines_a.h.
{
     arena_tdata_t *tdata;
     arena_tdata_t *arenas_tdata = tsd_arenas_tdata_get(tsd);
     if (unlikely(arenas_tdata == NULL)) {
         /* arenas_tdata hasn't been initialized yet. */
         return arena_tdata_get_hard(tsd, ind);
     }
     if (unlikely(ind >= tsd_narenas_tdata_get(tsd))) {
         /*
          * ind is invalid, cache is old (too small), or tdata to be
          * initialized.
          */
         return (refresh_if_missing ? arena_tdata_get_hard(tsd, ind) :
             NULL);
     }
     tdata = &arenas_tdata[ind];
     if (likely(tdata != NULL) || !refresh_if_missing) {
         return tdata;
     }
     return arena_tdata_get_hard(tsd, ind);
 }
References arena_tdata_get_hard, likely, NULL, and unlikely.
Referenced by decay_ticker_get().
decay_ticker_get()
static ticker_t* decay_ticker_get (tsd_t * tsd, unsigned ind) inline static
Definition at line 101 of file jemalloc_internal_inlines_a.h.
{
     arena_tdata_t *tdata;
     tdata = arena_tdata_get(tsd, ind, true);
     if (unlikely(tdata == NULL)) {
         return NULL;
     }
     return &tdata->decay_ticker;
 }
References arena_tdata_get(), arena_tdata_s::decay_ticker, NULL, and unlikely.
Referenced by arena_decay_ticks().
malloc_getcpu()
JEMALLOC_ALWAYS_INLINE malloc_cpuid_t malloc_getcpu (void)
Definition at line 11 of file jemalloc_internal_inlines_a.h.
                     {
     assert(have_percpu_arena);
 #if defined(_WIN32)
     return GetCurrentProcessorNumber();
 #elif defined(JEMALLOC_HAVE_SCHED_GETCPU)
     return (malloc_cpuid_t)sched_getcpu();
 #else
     not_reached();
     return -1;
 #endif
 }
References assert(), have_percpu_arena, and not_reached.
Referenced by malloc_init_narenas(), and percpu_arena_choose().
percpu_arena_choose()
JEMALLOC_ALWAYS_INLINE unsigned percpu_arena_choose (void)
Definition at line 25 of file jemalloc_internal_inlines_a.h.
{
     assert(have_percpu_arena && PERCPU_ARENA_ENABLED(opt_percpu_arena));
     malloc_cpuid_t cpuid = malloc_getcpu();
     assert(cpuid >= 0);
     unsigned arena_ind;
     if ((opt_percpu_arena == percpu_arena) || ((unsigned)cpuid < ncpus /
         2)) {
         arena_ind = cpuid;
     } else {
         assert(opt_percpu_arena == per_phycpu_arena);
         /* Hyper threads on the same physical CPU share arena. */
         arena_ind = cpuid - ncpus / 2;
     }
     return arena_ind;
 }
References assert(), have_percpu_arena, malloc_getcpu(), ncpus, opt_percpu_arena, per_phycpu_arena, percpu_arena, and PERCPU_ARENA_ENABLED.
Referenced by arena_choose_hard(), and arena_choose_impl().
percpu_arena_ind_limit()
JEMALLOC_ALWAYS_INLINE unsigned percpu_arena_ind_limit (percpu_arena_mode_t mode)
Definition at line 46 of file jemalloc_internal_inlines_a.h.
{
     assert(have_percpu_arena && PERCPU_ARENA_ENABLED(mode));
     if (mode == per_phycpu_arena && ncpus > 1) {
         if (ncpus % 2) {
             /* This likely means a misconfig. */
             return ncpus / 2 + 1;
         }
         return ncpus / 2;
     } else {
         return ncpus;
     }
 }
References assert(), have_percpu_arena, ncpus, per_phycpu_arena, and PERCPU_ARENA_ENABLED.
Referenced by arena_choose_impl(), CTL_RO_NL_GEN(), and malloc_init_narenas().
post_reentrancy()
static void post_reentrancy (tsd_t * tsd) inline static
Definition at line 166 of file jemalloc_internal_inlines_a.h.
{
     int8_t *reentrancy_level = tsd_reentrancy_levelp_get(tsd);
     assert(*reentrancy_level > 0);
     if (--*reentrancy_level == 0) {
         tsd_slow_update(tsd);
     }
 }
References assert(), and tsd_slow_update.
Referenced by arena_new(), base_map(), base_unmap(), extent_hook_post_reentrancy(), malloc_init_hard(), malloc_init_hard_cleanup(), and prof_dump().
pre_reentrancy()
static void pre_reentrancy (tsd_t * tsd, arena_t * arena) inline static
Definition at line 151 of file jemalloc_internal_inlines_a.h.
{
     /* arena is the current context.  Reentry from a0 is not allowed. */
     assert(arena != arena_get(tsd_tsdn(tsd), 0, false));
     bool fast = tsd_fast(tsd);
     assert(tsd_reentrancy_level_get(tsd) < INT8_MAX);
     ++*tsd_reentrancy_levelp_get(tsd);
     if (fast) {
         /* Prepare slow path for reentrancy. */
         tsd_slow_update(tsd);
         assert(tsd_state_get(tsd) == tsd_state_nominal_slow);
     }
 }
References arena, arena_get(), assert(), INT8_MAX, tsd_fast(), tsd_slow_update, tsd_state_get(), tsd_state_nominal_slow, and tsd_tsdn().
Referenced by arena_new(), base_map(), base_unmap(), extent_hook_pre_reentrancy(), malloc_init_hard(), and prof_dump().
tcache_available()
JEMALLOC_ALWAYS_INLINE bool tcache_available (tsd_t * tsd)
Definition at line 124 of file jemalloc_internal_inlines_a.h.
{
     /*
      * Thread specific auto tcache might be unavailable if: 1) during tcache
      * initialization, or 2) disabled through thread.tcache.enabled mallctl
      * or config options.  This check covers all cases.
      */
     if (likely(tsd_tcache_enabled_get(tsd))) {
         /* Associated arena == NULL implies tcache init in progress. */
         assert(tsd_tcachep_get(tsd)->arena == NULL ||
             tcache_small_bin_get(tsd_tcachep_get(tsd), 0)->avail !=
             NULL);
         return true;
     }
     return false;
 }
References arena, assert(), likely, NULL, and tcache_small_bin_get().
Referenced by arena_choose_impl(), CTL_RO_NL_GEN(), tcache_cleanup(), tcache_flush(), tcache_get(), and thread_tcache_flush_ctl().
tcache_get()
JEMALLOC_ALWAYS_INLINE tcache_t* tcache_get (tsd_t * tsd)
Definition at line 142 of file jemalloc_internal_inlines_a.h.
{
     if (!tcache_available(tsd)) {
         return NULL;
     }
     return tsd_tcachep_get(tsd);
 }
References NULL, and tcache_available().
Referenced by arena_choose_impl(), arena_postfork_child(), free_default(), ialloc(), idalloc(), imalloc_no_sample(), ipalloc(), iralloc(), je_dallocx(), je_rallocx(), je_realloc(), percpu_arena_update(), and sdallocx_default().
tcache_large_bin_get()
JEMALLOC_ALWAYS_INLINE cache_bin_t* tcache_large_bin_get (tcache_t * tcache, szind_t binind)
Definition at line 118 of file jemalloc_internal_inlines_a.h.
{
     assert(binind >= SC_NBINS &&binind < nhbins);
     return &tcache->bins_large[binind - SC_NBINS];
 }
References assert(), tcache_s::bins_large, nhbins, and SC_NBINS.
Referenced by tcache_alloc_large(), tcache_dalloc_large(), tcache_event_hard(), tcache_flush_cache(), tcache_init(), and tcache_stats_merge().
tcache_small_bin_get()
JEMALLOC_ALWAYS_INLINE cache_bin_t* tcache_small_bin_get (tcache_t * tcache, szind_t binind)
Definition at line 112 of file jemalloc_internal_inlines_a.h.
{
     assert(binind < SC_NBINS);
     return &tcache->bins_small[binind];
 }
References assert(), tcache_s::bins_small, and SC_NBINS.
Referenced by free_fastpath(), JEMALLOC_ATTR(), tcache_alloc_small(), tcache_available(), tcache_cleanup(), tcache_dalloc_small(), tcache_destroy(), tcache_event_hard(), tcache_flush_cache(), tcache_init(), tcache_stats_merge(), and tsd_tcache_data_init().