Azerotcore-wotlk: deps/libmpq/libmpq/wave.h File Reference
wave.h File Reference
Classes
union byte_and_int16_t
Functions
int32_t libmpq__do_decompress_wave (uint8_t *out_buf, int32_t out_length, uint8_t *in_buf, int32_t in_length, int32_t channels)
Function Documentation
libmpq__do_decompress_wave()
int32_t libmpq__do_decompress_wave (uint8_t * out_buf, int32_t out_length, uint8_t * in_buf, int32_t in_length, int32_t channels)
Definition at line 59 of file wave.c.
{
     /* some common variables. */
     byte_and_int16_t out;
     byte_and_int16_t in;
     uint32_t index;
     int32_t nr_array1[2];
     int32_t nr_array2[2];
     int32_t count = 0;
     /* end on input buffer. */
     uint8_t *in_end = in_buf + in_length;
     /* assign default values. */
     out.pb       = out_buf;
     in.pb        = in_buf;
     nr_array1[0] = 0x2C;
     nr_array1[1] = 0x2C;
     /* increase. */
     in.pw++;
     /* 15007AD7 */
     for (count = 0; count < channels; count++) {
         /* some common variables. */
         int32_t temp;
         /* save pointer. */
         temp = *(int16_t *)in.pw++;
         nr_array2[count] = temp;
         /* check if should break. */
         if (out_length < 2) {
             return out.pb - out_buf;
         }
         /* return values. */
         *out.pw++   = (uint16_t)temp;
         out_length -= 2;
     }
     /* decrease channels. */
     index = channels - 1;
     /* loop through input buffer until end reached. */
     while (in.pb < in_end) {
         /* save the byte. */
         uint8_t one_byte = *in.pb++;
         /* check how many channels and set index. */
         if (channels == 2) {
             index = (index == 0) ? 1 : 0;
         }
         /* 15007B25 - get one byte from input buffer. */
         if (one_byte & 0x80) {
             /* 15007B32 */
             switch (one_byte & 0x7F) {
                 case 0:
                     /* 15007B8E */
                     if (nr_array1[index] != 0) {
                         nr_array1[index]--;
                     }
                     /* check if should break. */
                     if (out_length < 2) {
                         break;
                     }
                     /* return values. */
                     *out.pw++ = (uint16_t)nr_array2[index];
                     out_length -= 2;
                     /* continue loop. */
                     continue;
                 case 1:
                     /* 15007B72 and EBX. */
                     nr_array1[index] += 8;
                     /* check index. */
                     if (nr_array1[index] > 0x58) {
                         nr_array1[index] = 0x58;
                     }
                     /* check how many channels and set index. */
                     if (channels == 2) {
                         index = (index == 0) ? 1 : 0;
                     }
                     /* continue loop. */
                     continue;
                 case 2:
                     /* nothing todo, so continue. */
                     continue;
                 default:
                     /* decrease index. */
                     nr_array1[index] -= 8;
                     /* check index. */
                     if (nr_array1[index] < 0) {
                         nr_array1[index] = 0;
                     }
                     /* check if two channels left. */
                     if (channels != 2) {
                         continue;
                     }
                     index = (index == 0) ? 1 : 0;
                     /* continue loop. */
                     continue;
             }
         } else {
             /* EDI */
             uint32_t temp1 = wave_table_1503f1a0[nr_array1[index]];
             /* ESI */
             uint32_t temp2 = temp1 >> in_buf[1];
             /* ECX */
             int32_t temp3 = nr_array2[index];
             /* EBX = one byte. */
             if (one_byte & 0x01) {
                 temp2 += (temp1 >> 0);
             }
             if (one_byte & 0x02) {
                 temp2 += (temp1 >> 1);
             }
             if (one_byte & 0x04) {
                 temp2 += (temp1 >> 2);
             }
             if (one_byte & 0x08) {
                 temp2 += (temp1 >> 3);
             }
             if (one_byte & 0x10) {
                 temp2 += (temp1 >> 4);
             }
             if (one_byte & 0x20) {
                 temp2 += (temp1 >> 5);
             }
             if (one_byte & 0x40) {
                 temp3 -= temp2;
                 if (temp3 <= (int32_t)0xFFFF8000) {
                     temp3 = (int32_t)0xFFFF8000;
                 }
             } else {
                 temp3 += temp2;
                 if (temp3 >= 0x7FFF) {
                     temp3 = 0x7FFF;
                 }
             }
             /* restore index. */
             nr_array2[index] = temp3;
             /* check if should break. */
             if (out_length < 2) {
                 break;
             }
             /* assign values. */
             temp2             = nr_array1[index];
             one_byte         &= 0x1F;
             *out.pw++         = (uint16_t)temp3;
             out_length       -= 2;
             temp2            += wave_table_1503f120[one_byte];
             nr_array1[index]  = temp2;
             /* check index. */
             if (nr_array1[index] < 0) {
                 nr_array1[index] = 0;
             } else {
                 /* check index. */
                 if (nr_array1[index] > 0x58) {
                     nr_array1[index] = 0x58;
                 }
             }
         }
     }
     /* return copied bytes. */
     return (out.pb - out_buf);
 }
References count(), if(), index, byte_and_int16_t::pb, byte_and_int16_t::pw, wave_table_1503f120, and wave_table_1503f1a0.
Referenced by libmpq__decompress_wave_mono(), and libmpq__decompress_wave_stereo().