Azerotcore-wotlk: instance_shattered_halls::instance_shattered_halls_InstanceMapScript Struct Reference
instance_shattered_halls::instance_shattered_halls_InstanceMapScript Struct Reference
Public Member Functions
instance_shattered_halls_InstanceMapScript (Map *map)
void Initialize () override
void OnPlayerEnter (Player *player) override
void OnGameObjectCreate (GameObject *go) override
void OnCreatureCreate (Creature *creature) override
bool SetBossState (uint32 type, EncounterState state) override
void SetData (uint32 type, uint32 data) override
ObjectGuid GetGuidData (uint32 data) const override
void Update (uint32 diff) override
std::string GetSaveData () override
void Load (const char *strIn) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void CreatureLooted (Creature *, LootType)
void SaveToDB ()
virtual bool IsEncounterInProgress () const
void OnCreatureRemove (Creature *creature) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void ProcessEvent (WorldObject *, uint32)
Protected Attributes
ObjectGuid warchiefKargathGUID
ObjectGuid nethekurseDoor1GUID
ObjectGuid nethekurseDoor2GUID
ObjectGuid executionerGUID
ObjectGuid prisonerGUID [3]
uint32 RescueTimer
TeamId TeamIdInInstance
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Definition at line 33 of file instance_shattered_halls.cpp.
Constructor & Destructor Documentation
instance_shattered_halls_InstanceMapScript()
instance_shattered_halls::instance_shattered_halls_InstanceMapScript::instance_shattered_halls_InstanceMapScript (Map * map) inline
Definition at line 35 of file instance_shattered_halls.cpp.
 : InstanceScript(map) { }
Member Function Documentation
GetGuidData()
ObjectGuid instance_shattered_halls::instance_shattered_halls_InstanceMapScript::GetGuidData (uint32 data) const inline override virtual
Reimplemented from InstanceScript.
Definition at line 143 of file instance_shattered_halls.cpp.
         {
             switch (data)
             {
                 case DATA_PRISONER_1:
                 case DATA_PRISONER_2:
                 case DATA_PRISONER_3:
                     return prisonerGUID[data - DATA_PRISONER_1];
                 case DATA_EXECUTIONER:
                     return executionerGUID;
             }
             return ObjectGuid::Empty;
         }
References DATA_EXECUTIONER, DATA_PRISONER_1, DATA_PRISONER_2, DATA_PRISONER_3, ObjectGuid::Empty, executionerGUID, and prisonerGUID.
GetSaveData()
std::string instance_shattered_halls::instance_shattered_halls_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
Definition at line 189 of file instance_shattered_halls.cpp.
         {
             OUT_SAVE_INST_DATA;
             std::ostringstream saveStream;
             saveStream << "S H " << GetBossSaveData() << ' ' << RescueTimer;
             OUT_SAVE_INST_DATA_COMPLETE;
             return saveStream.str();
         }
References InstanceScript::GetBossSaveData(), OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, and RescueTimer.
Initialize()
void instance_shattered_halls::instance_shattered_halls_InstanceMapScript::Initialize (void) inline override virtual
Reimplemented from InstanceScript.
Definition at line 37 of file instance_shattered_halls.cpp.
         {
             SetBossNumber(ENCOUNTER_COUNT);
             TeamIdInInstance = TEAM_NEUTRAL;
             RescueTimer = 100 * MINUTE * IN_MILLISECONDS;
         }
References ENCOUNTER_COUNT, IN_MILLISECONDS, MINUTE, RescueTimer, InstanceScript::SetBossNumber(), TEAM_NEUTRAL, and TeamIdInInstance.
Load()
void instance_shattered_halls::instance_shattered_halls_InstanceMapScript::Load (const char * strIn) inline override virtual
Reimplemented from InstanceScript.
Definition at line 200 of file instance_shattered_halls.cpp.
         {
             if (!strIn)
             {
                 OUT_LOAD_INST_DATA_FAIL;
                 return;
             }
             OUT_LOAD_INST_DATA(strIn);
             char dataHead1, dataHead2;
             std::istringstream loadStream(strIn);
             loadStream >> dataHead1 >> dataHead2;
             if (dataHead1 == 'S' && dataHead2 == 'H')
             {
                 for (uint8 i = 0; i < ENCOUNTER_COUNT; ++i)
                 {
                     uint32 tmpState;
                     loadStream >> tmpState;
                     if (tmpState == IN_PROGRESS || tmpState > SPECIAL)
                         tmpState = NOT_STARTED;
                     SetBossState(i, EncounterState(tmpState));
                 }
                 loadStream >> RescueTimer;
             }
             else
                 OUT_LOAD_INST_DATA_FAIL;
             OUT_LOAD_INST_DATA_COMPLETE;
         }
References ENCOUNTER_COUNT, IN_PROGRESS, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, OUT_LOAD_INST_DATA_FAIL, RescueTimer, SetBossState(), and SPECIAL.
OnCreatureCreate()
void instance_shattered_halls::instance_shattered_halls_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 68 of file instance_shattered_halls.cpp.
         {
             if (TeamIdInInstance == TEAM_NEUTRAL)
             {
                 Map::PlayerList const& players = instance->GetPlayers();
                 if (!players.isEmpty())
                     if (Player* player = players.begin()->GetSource())
                         TeamIdInInstance = player->GetTeamId();
             }
             switch (creature->GetEntry())
             {
                 case NPC_WARCHIEF_KARGATH:
                     warchiefKargathGUID = creature->GetGUID();
                     break;
                 case NPC_SHATTERED_EXECUTIONER:
                     if (RescueTimer > 25 * MINUTE * IN_MILLISECONDS)
                         creature->AddLootMode(2);
                     executionerGUID = creature->GetGUID();
                     break;
                 case NPC_RIFLEMAN_BROWNBEARD:
                     if (TeamIdInInstance == TEAM_HORDE)
                         creature->UpdateEntry(NPC_KORAG_PROUDMANE);
                     prisonerGUID[0] = creature->GetGUID();
                     break;
                 case NPC_CAPTAIN_ALINA:
                     if (TeamIdInInstance == TEAM_HORDE)
                         creature->UpdateEntry(NPC_CAPTAIN_BONESHATTER);
                     prisonerGUID[1] = creature->GetGUID();
                     break;
                 case NPC_PRIVATE_JACINT:
                     if (TeamIdInInstance == TEAM_HORDE)
                         creature->UpdateEntry(NPC_SCOUT_ORGARR);
                     prisonerGUID[2] = creature->GetGUID();
                     break;
             }
         }
References Creature::AddLootMode(), MapRefMgr::begin(), executionerGUID, Object::GetEntry(), Object::GetGUID(), Map::GetPlayers(), IN_MILLISECONDS, InstanceScript::instance, LinkedListHead::isEmpty(), MINUTE, NPC_CAPTAIN_ALINA, NPC_CAPTAIN_BONESHATTER, NPC_KORAG_PROUDMANE, NPC_PRIVATE_JACINT, NPC_RIFLEMAN_BROWNBEARD, NPC_SCOUT_ORGARR, NPC_SHATTERED_EXECUTIONER, NPC_WARCHIEF_KARGATH, prisonerGUID, RescueTimer, TEAM_HORDE, TEAM_NEUTRAL, TeamIdInInstance, Creature::UpdateEntry(), and warchiefKargathGUID.
OnGameObjectCreate()
void instance_shattered_halls::instance_shattered_halls_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
Definition at line 51 of file instance_shattered_halls.cpp.
         {
             switch (go->GetEntry())
             {
                 case GO_GRAND_WARLOCK_CHAMBER_DOOR_1:
                     nethekurseDoor1GUID = go->GetGUID();
                     if (GetBossState(DATA_NETHEKURSE) == DONE)
                         HandleGameObject(ObjectGuid::Empty, true, go);
                     break;
                 case GO_GRAND_WARLOCK_CHAMBER_DOOR_2:
                     nethekurseDoor2GUID = go->GetGUID();
                     if (GetBossState(DATA_NETHEKURSE) == DONE)
                         HandleGameObject(ObjectGuid::Empty, true, go);
                     break;
             }
         }
References DATA_NETHEKURSE, DONE, ObjectGuid::Empty, InstanceScript::GetBossState(), Object::GetEntry(), Object::GetGUID(), GO_GRAND_WARLOCK_CHAMBER_DOOR_1, GO_GRAND_WARLOCK_CHAMBER_DOOR_2, InstanceScript::HandleGameObject(), nethekurseDoor1GUID, and nethekurseDoor2GUID.
OnPlayerEnter()
void instance_shattered_halls::instance_shattered_halls_InstanceMapScript::OnPlayerEnter (Player * player) inline override virtual
Reimplemented from InstanceScript.
Definition at line 45 of file instance_shattered_halls.cpp.
         {
             if (TeamIdInInstance == TEAM_NEUTRAL)
                 TeamIdInInstance = player->GetTeamId();
         }
References Player::GetTeamId(), TEAM_NEUTRAL, and TeamIdInInstance.
SetBossState()
bool instance_shattered_halls::instance_shattered_halls_InstanceMapScript::SetBossState (uint32 type, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
Definition at line 106 of file instance_shattered_halls.cpp.
         {
             if (!InstanceScript::SetBossState(type, state))
                 return false;
             switch (type)
             {
                 case DATA_NETHEKURSE:
                     if (state == IN_PROGRESS)
                     {
                         HandleGameObject(nethekurseDoor1GUID, false);
                         HandleGameObject(nethekurseDoor2GUID, false);
                     }
                     else
                     {
                         HandleGameObject(nethekurseDoor1GUID, true);
                         HandleGameObject(nethekurseDoor2GUID, true);
                     }
                     break;
             }
             return true;
         }
References DATA_NETHEKURSE, InstanceScript::HandleGameObject(), IN_PROGRESS, nethekurseDoor1GUID, nethekurseDoor2GUID, and InstanceScript::SetBossState().
Referenced by Load().
SetData()
void instance_shattered_halls::instance_shattered_halls_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
Definition at line 129 of file instance_shattered_halls.cpp.
         {
             if (type == DATA_ENTERED_ROOM && data == DATA_ENTERED_ROOM && RescueTimer == 100 * MINUTE * IN_MILLISECONDS)
             {
                 DoCastSpellOnPlayers(SPELL_KARGATHS_EXECUTIONER_1);
                 instance->LoadGrid(230, -80);
                 if (Creature* kargath = instance->GetCreature(warchiefKargathGUID))
                     sCreatureTextMgr->SendChat(kargath, TeamIdInInstance == TEAM_ALLIANCE ? 3 : 4, nullptr, CHAT_MSG_ADDON, LANG_ADDON, TEXT_RANGE_MAP);
                 RescueTimer = 80 * MINUTE * IN_MILLISECONDS;
             }
         }
References CHAT_MSG_ADDON, DATA_ENTERED_ROOM, InstanceScript::DoCastSpellOnPlayers(), Map::GetCreature(), IN_MILLISECONDS, InstanceScript::instance, LANG_ADDON, Map::LoadGrid(), MINUTE, RescueTimer, sCreatureTextMgr, SPELL_KARGATHS_EXECUTIONER_1, TEAM_ALLIANCE, TeamIdInInstance, TEXT_RANGE_MAP, and warchiefKargathGUID.
Update()
void instance_shattered_halls::instance_shattered_halls_InstanceMapScript::Update (uint32 diff) inline override virtual
Reimplemented from InstanceScript.
Definition at line 158 of file instance_shattered_halls.cpp.
         {
             if (RescueTimer && RescueTimer < 100 * MINUTE * IN_MILLISECONDS)
             {
                 RescueTimer -= std::min(RescueTimer, diff);
                 if ((RescueTimer / IN_MILLISECONDS) == 25 * MINUTE)
                 {
                     DoRemoveAurasDueToSpellOnPlayers(SPELL_KARGATHS_EXECUTIONER_1);
                     DoCastSpellOnPlayers(SPELL_KARGATHS_EXECUTIONER_2);
                     if (Creature* prisoner = instance->GetCreature(prisonerGUID[0]))
                         Unit::Kill(prisoner, prisoner);
                     if (Creature* executioner = instance->GetCreature(executionerGUID))
                         executioner->RemoveLootMode(2);
                 }
                 else if ((RescueTimer / IN_MILLISECONDS) == 15 * MINUTE)
                 {
                     DoRemoveAurasDueToSpellOnPlayers(SPELL_KARGATHS_EXECUTIONER_2);
                     DoCastSpellOnPlayers(SPELL_KARGATHS_EXECUTIONER_3);
                     if (Creature* prisoner = instance->GetCreature(prisonerGUID[1]))
                         Unit::Kill(prisoner, prisoner);
                 }
                 else if ((RescueTimer / IN_MILLISECONDS) == 0)
                 {
                     DoRemoveAurasDueToSpellOnPlayers(SPELL_KARGATHS_EXECUTIONER_3);
                     if (Creature* prisoner = instance->GetCreature(prisonerGUID[2]))
                         Unit::Kill(prisoner, prisoner);
                 }
             }
         }
References InstanceScript::DoCastSpellOnPlayers(), InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), executionerGUID, Map::GetCreature(), IN_MILLISECONDS, InstanceScript::instance, Unit::Kill(), MINUTE, prisonerGUID, RescueTimer, SPELL_KARGATHS_EXECUTIONER_1, SPELL_KARGATHS_EXECUTIONER_2, and SPELL_KARGATHS_EXECUTIONER_3.
Member Data Documentation
executionerGUID
ObjectGuid instance_shattered_halls::instance_shattered_halls_InstanceMapScript::executionerGUID protected
Definition at line 239 of file instance_shattered_halls.cpp.
Referenced by GetGuidData(), OnCreatureCreate(), and Update().
nethekurseDoor1GUID
ObjectGuid instance_shattered_halls::instance_shattered_halls_InstanceMapScript::nethekurseDoor1GUID protected
Definition at line 236 of file instance_shattered_halls.cpp.
Referenced by OnGameObjectCreate(), and SetBossState().
nethekurseDoor2GUID
ObjectGuid instance_shattered_halls::instance_shattered_halls_InstanceMapScript::nethekurseDoor2GUID protected
Definition at line 237 of file instance_shattered_halls.cpp.
Referenced by OnGameObjectCreate(), and SetBossState().
prisonerGUID
ObjectGuid instance_shattered_halls::instance_shattered_halls_InstanceMapScript::prisonerGUID[3] protected
Definition at line 240 of file instance_shattered_halls.cpp.
Referenced by GetGuidData(), OnCreatureCreate(), and Update().
RescueTimer
uint32 instance_shattered_halls::instance_shattered_halls_InstanceMapScript::RescueTimer protected
Definition at line 241 of file instance_shattered_halls.cpp.
Referenced by GetSaveData(), Initialize(), Load(), OnCreatureCreate(), SetData(), and Update().
TeamIdInInstance
TeamId instance_shattered_halls::instance_shattered_halls_InstanceMapScript::TeamIdInInstance protected
Definition at line 242 of file instance_shattered_halls.cpp.
Referenced by Initialize(), OnCreatureCreate(), OnPlayerEnter(), and SetData().
warchiefKargathGUID
ObjectGuid instance_shattered_halls::instance_shattered_halls_InstanceMapScript::warchiefKargathGUID protected
Definition at line 235 of file instance_shattered_halls.cpp.
Referenced by OnCreatureCreate(), and SetData().
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/HellfireCitadel/ShatteredHalls/instance_shattered_halls.cpp