Azerotcore-wotlk: Acore::WorldObjectSpellAreaTargetCheck Struct Reference
Acore::WorldObjectSpellAreaTargetCheck Struct Reference
#include <Spell.h>
Public Member Functions
WorldObjectSpellAreaTargetCheck (float range, Position const *position, Unit *caster, Unit *referer, SpellInfo const *spellInfo, SpellTargetCheckTypes selectionType, ConditionList *condList)
bool operator() (WorldObject *target)
Public Member Functions inherited from Acore::WorldObjectSpellTargetCheck
WorldObjectSpellTargetCheck (Unit *caster, Unit *referer, SpellInfo const *spellInfo, SpellTargetCheckTypes selectionType, ConditionList *condList)
~WorldObjectSpellTargetCheck ()
bool operator() (WorldObject *target)
Public Attributes
float _range
Position const * _position
Public Attributes inherited from Acore::WorldObjectSpellTargetCheck
Unit * _caster
Unit * _referer
SpellInfo const * _spellInfo
SpellTargetCheckTypes _targetSelectionType
ConditionSourceInfo * _condSrcInfo
ConditionList * _condList
Detailed Description
Definition at line 798 of file Spell.h.
Constructor & Destructor Documentation
WorldObjectSpellAreaTargetCheck()
Acore::WorldObjectSpellAreaTargetCheck::WorldObjectSpellAreaTargetCheck (float range, Position const * position, Unit * caster, Unit * referer, SpellInfo const * spellInfo, SpellTargetCheckTypes selectionType, ConditionList * condList)
Definition at line 8513 of file Spell.cpp.
         : WorldObjectSpellTargetCheck(caster, referer, spellInfo, selectionType, condList), _range(range), _position(position)
     {
     }
Member Function Documentation
operator()()
bool Acore::WorldObjectSpellAreaTargetCheck::operator() (WorldObject * target)
Definition at line 8519 of file Spell.cpp.
     {
         if (target->GetTypeId() == TYPEID_GAMEOBJECT)
         {
             if (!target->ToGameObject()->IsInRange(_position->GetPositionX(), _position->GetPositionY(), _position->GetPositionZ(), _range))
                 return false;
         }
         else if (!target->IsWithinDist3d(_position, _range))
             return false;
         else if (target->GetTypeId() == TYPEID_UNIT && target->ToCreature()->IsAvoidingAOE()) // pussywizard
             return false;
         return WorldObjectSpellTargetCheck::operator ()(target);
     }
References _position, _range, Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Object::GetTypeId(), Creature::IsAvoidingAOE(), GameObject::IsInRange(), WorldObject::IsWithinDist3d(), Acore::WorldObjectSpellTargetCheck::operator()(), Object::ToCreature(), Object::ToGameObject(), TYPEID_GAMEOBJECT, and TYPEID_UNIT.
Referenced by Acore::WorldObjectSpellConeTargetCheck::operator()(), and Acore::WorldObjectSpellTrajTargetCheck::operator()().
Member Data Documentation
_position
Position const* Acore::WorldObjectSpellAreaTargetCheck::_position
Definition at line 801 of file Spell.h.
Referenced by operator()().
_range
float Acore::WorldObjectSpellAreaTargetCheck::_range
Definition at line 800 of file Spell.h.
Referenced by operator()().
The documentation for this struct was generated from the following files:
src/server/game/Spells/Spell.h
src/server/game/Spells/Spell.cpp