Azerotcore-wotlk: npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI Struct Reference
npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI Struct Reference
Public Member Functions
npc_ulduar_leviathan_mkiiAI (Creature *pCreature)
void Reset () override
void SetData (uint32 id, uint32 value) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void MoveInLineOfSight (Unit *) override
void KilledUnit (Unit *who) override
void EnterEvadeMode () override
void PassengerBoarded (Unit *p, int8, bool apply) override
== Fields =======================================
Unit * GetS3 ()
void SpellHit (Unit *, const SpellInfo *spell) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void JustDied (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
EventMap events
bool bIsEvading
uint8 Phase
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1007 of file boss_mimiron.cpp.
Constructor & Destructor Documentation
npc_ulduar_leviathan_mkiiAI()
npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::npc_ulduar_leviathan_mkiiAI (Creature * pCreature) inline
Definition at line 1009 of file boss_mimiron.cpp.
                                                          : ScriptedAI(pCreature)
         {
             pInstance = me->GetInstanceScript();
             bIsEvading = false;
         }
References bIsEvading, WorldObject::GetInstanceScript(), ScriptedAI::me, and pInstance.
Member Function Documentation
DamageTaken()
void npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1076 of file boss_mimiron.cpp.
         {
             if (damage >= me->GetHealth() || me->GetHealth() < 15000)
             {
                 damage = 0;
                 if (me->GetReactState() == REACT_PASSIVE)
                     return;
                 me->SetReactState(REACT_PASSIVE);
                 if (Phase == 1)
                 {
                     if (!me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE))
                     {
                         me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                         me->GetMotionMaster()->Clear();
                         me->AttackStop();
                         me->SetReactState(REACT_PASSIVE);
                         SetData(1, 0);
                         me->InterruptNonMeleeSpells(false);
                         me->RemoveAllAurasExceptType(SPELL_AURA_CONTROL_VEHICLE);
                         if (Unit* cannon = GetS3())
                             cannon->ExitVehicle();
                         me->GetMotionMaster()->MoveCharge(2795.076f, 2598.616f, 364.32f, 21.0f);
                         if (Creature* c = GetMimiron())
                             c->AI()->SetData(0, 1);
                     }
                 }
                 else if (Phase == 4)
                 {
                     if (!me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE))
                     {
                         me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                         me->InterruptNonMeleeSpells(false);
                         me->RemoveAllAurasExceptType(SPELL_AURA_CONTROL_VEHICLE);
                         me->CastSpell(me, SPELL_SELF_REPAIR, false);
                         if (Creature* c = GetMimiron())
{
                             if (c->AI()->GetData(1))
                                 me->CastSpell(me, SPELL_EMERGENCY_MODE, true);
                             if (c->AI()->GetData(2))
                                 me->CastSpell(me, SPELL_BERSERK, true);
                             c->AI()->SetData(0, 4);
                         }
                     }
                 }
             }
         }
References Unit::AttackStop(), Unit::CastSpell(), MotionMaster::Clear(), Unit::GetHealth(), GetMimiron, Unit::GetMotionMaster(), Creature::GetReactState(), GetS3(), Object::HasFlag(), Unit::InterruptNonMeleeSpells(), ScriptedAI::me, MotionMaster::MoveCharge(), REACT_PASSIVE, Unit::RemoveAllAurasExceptType(), SetData(), Object::SetFlag(), Creature::SetReactState(), SPELL_AURA_CONTROL_VEHICLE, SPELL_BERSERK, SPELL_EMERGENCY_MODE, SPELL_SELF_REPAIR, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
EnterEvadeMode()
void npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 1223 of file boss_mimiron.cpp.
         {
             if (bIsEvading)
                 return;
             bIsEvading = true;
             me->RemoveAllAuras();
             me->ExitVehicle();
             ScriptedAI::EnterEvadeMode();
             if (Creature* mimiron = GetMimiron())
                 mimiron->AI()->EnterEvadeMode();
             bIsEvading = false;
         }
References bIsEvading, CreatureAI::EnterEvadeMode(), Unit::ExitVehicle(), GetMimiron, ScriptedAI::me, and Unit::RemoveAllAuras().
GetS3()
Unit* npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::GetS3 () inline
Definition at line 1248 of file boss_mimiron.cpp.
         {
             if (Vehicle* vk = me->GetVehicleKit())
                 if (Unit* cannon = vk->GetPassenger(3))
                     return cannon;
             return 0;
         }
References Unit::GetVehicleKit(), and ScriptedAI::me.
Referenced by DamageTaken(), Reset(), and UpdateAI().
KilledUnit()
void npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1189 of file boss_mimiron.cpp.
         {
             if( who->GetTypeId() == TYPEID_PLAYER )
                 if (Creature* c = GetMimiron())
                 {
                     if( Phase == 1 )
                     {
                         if( rand() % 2 )
{
                             c->Yell(TEXT_LMK2_SLAIN_1, LANG_UNIVERSAL);
                             c->PlayDirectSound(SOUND_TANK_SLAY_1);
                         }
                         else
{
                             c->Yell(TEXT_LMK2_SLAIN_2, LANG_UNIVERSAL);
                             c->PlayDirectSound(SOUND_TANK_SLAY_2);
                         }
                     }
                     else
                     {
                         if( rand() % 2 )
{
                             c->Yell(TEXT_VOLTRON_SLAIN_1, LANG_UNIVERSAL);
                             c->PlayDirectSound(SOUND_VOLTRON_SLAY_1);
                         }
                         else
{
                             c->Yell(TEXT_VOLTRON_SLAIN_2, LANG_UNIVERSAL);
                             c->PlayDirectSound(SOUND_VOLTRON_SLAY_2);
                         }
                     }
                 }
         }
References GetMimiron, Object::GetTypeId(), LANG_UNIVERSAL, SOUND_TANK_SLAY_1, SOUND_TANK_SLAY_2, SOUND_VOLTRON_SLAY_1, SOUND_VOLTRON_SLAY_2, TEXT_LMK2_SLAIN_1, TEXT_LMK2_SLAIN_2, TEXT_VOLTRON_SLAIN_1, TEXT_VOLTRON_SLAIN_2, and TYPEID_PLAYER.
MoveInLineOfSight()
void npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 1187 of file boss_mimiron.cpp.
 {}
PassengerBoarded()
void npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::PassengerBoarded (Unit * , int8 , bool) inline override virtual
== Fields =======================================
Reimplemented from CreatureAI.
Definition at line 1239 of file boss_mimiron.cpp.
         {
             if (p->GetEntry() == NPC_LEVIATHAN_MKII_CANNON && !apply)
             {
                 Unit::Kill(p, p);
                 p->ToCreature()->DespawnOrUnsummon(6000);
             }
         }
References ByteConverter::apply(), Creature::DespawnOrUnsummon(), Object::GetEntry(), Unit::Kill(), NPC_LEVIATHAN_MKII_CANNON, and Object::ToCreature().
Reset()
void npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1020 of file boss_mimiron.cpp.
         {
             Phase = 0;
             if (Unit* c = GetS3())
                 c->ExitVehicle(); // this should never happen!
             if (Creature* c = me->SummonCreature(NPC_LEVIATHAN_MKII_CANNON, *me, TEMPSUMMON_MANUAL_DESPAWN))
                 c->EnterVehicle(me, 3);
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
             me->SetReactState(REACT_AGGRESSIVE);
             me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
             events.Reset();
         }
References EMOTE_ONESHOT_NONE, GetS3(), ScriptedAI::me, NPC_LEVIATHAN_MKII_CANNON, REACT_AGGRESSIVE, Object::RemoveFlag(), Object::SetFlag(), Creature::SetReactState(), Object::SetUInt32Value(), WorldObject::SummonCreature(), TEMPSUMMON_MANUAL_DESPAWN, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, and UNIT_NPC_EMOTESTATE.
SetData()
void npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::SetData (uint32 id, uint32 value) inline override virtual
Reimplemented from UnitAI.
Definition at line 1035 of file boss_mimiron.cpp.
         {
             if (id == 1) // setting phase to start fighting
             {
                 switch (value)
                 {
                     case 0:
                         Phase = 0;
                         events.Reset();
                         break;
                     case 1:
                         Phase = 1;
                         me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                         if (Unit* target = SelectTargetFromPlayerList(75.0f))
                             AttackStart(target);
                         DoZoneInCombat();
                         events.Reset();
                         events.ScheduleEvent(EVENT_SPELL_NAPALM_SHELL, 3000);
                         events.ScheduleEvent(EVENT_SPELL_PLASMA_BLAST, 10000);
                         events.ScheduleEvent(EVENT_SPELL_SHOCK_BLAST, 20000);
                         events.ScheduleEvent(EVENT_PROXIMITY_MINES_1, 6000);
                         if (Creature* c = GetMimiron())
                             if (c->AI()->GetData(1))
                                 events.ScheduleEvent(EVENT_FLAME_SUPPRESSION_50000, 60000);
                         break;
                     case 4:
                         me->SetReactState(REACT_AGGRESSIVE);
                         DoResetThreat();
                         Phase = 4;
                         me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                         if (Unit* target = SelectTargetFromPlayerList(75.0f))
                             AttackStart(target);
                         DoZoneInCombat();
                         events.Reset();
                         events.ScheduleEvent(EVENT_SPELL_SHOCK_BLAST, 20000);
                         events.ScheduleEvent(EVENT_PROXIMITY_MINES_1, 6000);
                         break;
                 }
             }
         }
References ScriptedAI::AttackStart(), ScriptedAI::DoResetThreat(), CreatureAI::DoZoneInCombat(), EVENT_FLAME_SUPPRESSION_50000, EVENT_PROXIMITY_MINES_1, EVENT_SPELL_NAPALM_SHELL, EVENT_SPELL_PLASMA_BLAST, EVENT_SPELL_SHOCK_BLAST, GetMimiron, ScriptedAI::me, REACT_AGGRESSIVE, Object::RemoveFlag(), ScriptedAI::SelectTargetFromPlayerList(), Creature::SetReactState(), UNIT_FIELD_FLAGS, and UNIT_FLAG_NOT_SELECTABLE.
Referenced by DamageTaken().
SpellHit()
void npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::SpellHit (Unit * , const SpellInfo * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1257 of file boss_mimiron.cpp.
         {
             if( spell->Id == SPELL_SELF_REPAIR )
             {
                 me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                 me->SetReactState(REACT_AGGRESSIVE);
             }
         }
References SpellInfo::Id, ScriptedAI::me, REACT_AGGRESSIVE, Object::RemoveFlag(), Creature::SetReactState(), SPELL_SELF_REPAIR, UNIT_FIELD_FLAGS, and UNIT_FLAG_NON_ATTACKABLE.
UpdateAI()
void npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1123 of file boss_mimiron.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (!me->HasUnitState(UNIT_STATE_CASTING))
                 DoMeleeAttackIfReady();
             Unit* cannon = GetS3();
             if (!cannon || cannon->HasUnitState(UNIT_STATE_CASTING) || me->HasUnitState(UNIT_STATE_CASTING) || me->HasAuraType(SPELL_AURA_MOD_SILENCE))
                 return;
             switch (events.ExecuteEvent())
             {
                 case 0:
                     break;
                 case EVENT_SPELL_NAPALM_SHELL:
                     {
                         Player* pTarget = nullptr;
                         std::vector<Player*> pList;
                         Map::PlayerList const& pl = me->GetMap()->GetPlayers();
                         for( Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr )
                             if (Player* plr = itr->GetSource())
                                 if( plr->IsAlive() && plr->GetDistance2d(me) > 15.0f )
                                     pList.push_back(plr);
                         if (!pList.empty())
                             pTarget = pList[urand(0, pList.size() - 1)];
                         else
                             pTarget = (Player*)SelectTarget(SELECT_TARGET_RANDOM, 0, 100.0f, true);
                         if( pTarget )
                             cannon->CastSpell(pTarget, SPELL_NAPALM_SHELL, false);
                         events.RepeatEvent(14000);
                     }
                     break;
                 case EVENT_SPELL_PLASMA_BLAST:
                     if (Unit* victim = me->GetVictim())
                     {
                         me->TextEmote("Leviathan Mk II begins to cast Plasma Blast!", nullptr, true);
                         cannon->CastSpell(victim, SPELL_PLASMA_BLAST, false);
                     }
                     events.RepeatEvent(22000);
                     break;
                 case EVENT_SPELL_SHOCK_BLAST:
                     me->CastSpell(me->GetVictim(), SPELL_SHOCK_BLAST, false);
                     events.RepeatEvent(30000);
                     events.ScheduleEvent(EVENT_PROXIMITY_MINES_1, 8000);
                     break;
                 case EVENT_PROXIMITY_MINES_1:
                     for (uint8 i = 0; i < 10; ++i)
                     {
                         me->CastSpell(me, SPELL_SUMMON_PROXIMITY_MINE, true);
                     }
                     break;
                 case EVENT_FLAME_SUPPRESSION_50000:
                     me->CastSpell(me, SPELL_FLAME_SUPPRESSANT_50000yd, false);
                     break;
             }
         }
References MapRefMgr::begin(), Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), MapRefMgr::end(), EVENT_FLAME_SUPPRESSION_50000, EVENT_PROXIMITY_MINES_1, EVENT_SPELL_NAPALM_SHELL, EVENT_SPELL_PLASMA_BLAST, EVENT_SPELL_SHOCK_BLAST, WorldObject::GetMap(), Map::GetPlayers(), GetS3(), Unit::GetVictim(), Unit::HasAuraType(), Unit::HasUnitState(), ScriptedAI::me, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), SPELL_AURA_MOD_SILENCE, SPELL_FLAME_SUPPRESSANT_50000yd, SPELL_NAPALM_SHELL, SPELL_PLASMA_BLAST, SPELL_SHOCK_BLAST, SPELL_SUMMON_PROXIMITY_MINE, Unit::TextEmote(), UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
bIsEvading
bool npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::bIsEvading
Definition at line 1017 of file boss_mimiron.cpp.
Referenced by EnterEvadeMode(), and npc_ulduar_leviathan_mkiiAI().
events
EventMap npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::events
Definition at line 1016 of file boss_mimiron.cpp.
Phase
uint8 npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::Phase
Definition at line 1018 of file boss_mimiron.cpp.
pInstance
InstanceScript* npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::pInstance
Definition at line 1015 of file boss_mimiron.cpp.
Referenced by npc_ulduar_leviathan_mkiiAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_mimiron.cpp