Azerotcore-wotlk: npc_stone_watcher_of_norgannon Class Reference
npc_stone_watcher_of_norgannon Class Reference
Public Member Functions
npc_stone_watcher_of_norgannon ()
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
bool OnGossipHello (Player *player, Creature *creature) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 339 of file zone_tanaris.cpp.
Constructor & Destructor Documentation
npc_stone_watcher_of_norgannon()
npc_stone_watcher_of_norgannon::npc_stone_watcher_of_norgannon () inline
Definition at line 342 of file zone_tanaris.cpp.
 : CreatureScript("npc_stone_watcher_of_norgannon") { }
Member Function Documentation
OnGossipHello()
bool npc_stone_watcher_of_norgannon::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 377 of file zone_tanaris.cpp.
     {
         if (creature->IsQuestGiver())
             player->PrepareQuestMenu(creature->GetGUID());
         if (player->GetQuestStatus(2954) == QUEST_STATUS_INCOMPLETE)
             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ITEM_NORGANNON_1, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF);
         SendGossipMenuFor(player, 1674, creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), Object::GetGUID(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_NORGANNON_1, GOSSIP_SENDER_MAIN, Unit::IsQuestGiver(), Player::PrepareQuestMenu(), QUEST_STATUS_INCOMPLETE, and SendGossipMenuFor().
OnGossipSelect()
bool npc_stone_watcher_of_norgannon::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 344 of file zone_tanaris.cpp.
     {
         ClearGossipMenuFor(player);
         switch (action)
         {
             case GOSSIP_ACTION_INFO_DEF:
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ITEM_NORGANNON_2, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
                 SendGossipMenuFor(player, 1675, creature->GetGUID());
                 break;
             case GOSSIP_ACTION_INFO_DEF+1:
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ITEM_NORGANNON_3, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
                 SendGossipMenuFor(player, 1676, creature->GetGUID());
                 break;
             case GOSSIP_ACTION_INFO_DEF+2:
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ITEM_NORGANNON_4, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 3);
                 SendGossipMenuFor(player, 1677, creature->GetGUID());
                 break;
             case GOSSIP_ACTION_INFO_DEF+3:
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ITEM_NORGANNON_5, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 4);
                 SendGossipMenuFor(player, 1678, creature->GetGUID());
                 break;
             case GOSSIP_ACTION_INFO_DEF+4:
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ITEM_NORGANNON_6, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 5);
                 SendGossipMenuFor(player, 1679, creature->GetGUID());
                 break;
             case GOSSIP_ACTION_INFO_DEF+5:
                 CloseGossipMenuFor(player);
                 player->AreaExploredOrEventHappens(2954);
                 break;
         }
         return true;
     }
References AddGossipItemFor(), Player::AreaExploredOrEventHappens(), ClearGossipMenuFor(), CloseGossipMenuFor(), Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_NORGANNON_2, GOSSIP_ITEM_NORGANNON_3, GOSSIP_ITEM_NORGANNON_4, GOSSIP_ITEM_NORGANNON_5, GOSSIP_ITEM_NORGANNON_6, GOSSIP_SENDER_MAIN, and SendGossipMenuFor().
The documentation for this class was generated from the following file:
src/server/scripts/Kalimdor/zone_tanaris.cpp