Azerotcore-wotlk: npc_madrigosa::npc_madrigosaAI Struct Reference
npc_madrigosa::npc_madrigosaAI Struct Reference
Public Member Functions
npc_madrigosaAI (Creature *creature)
void DoAction (int32 param) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void Reset ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
InstanceScript * instance
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 211 of file boss_brutallus.cpp.
Constructor & Destructor Documentation
npc_madrigosaAI()
npc_madrigosa::npc_madrigosaAI::npc_madrigosaAI (Creature * creature) inline
Definition at line 213 of file boss_brutallus.cpp.
                                             : NullCreatureAI(creature)
         {
             instance = creature->GetInstanceScript();
             bool appear = instance->GetBossState(DATA_BRUTALLUS) != DONE && instance->GetBossState(DATA_MADRIGOSA) == DONE;
             creature->SetVisible(appear);
             creature->SetStandState(UNIT_STAND_STATE_DEAD);
             creature->SetFlag(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_DEAD);
         }
References DATA_BRUTALLUS, DATA_MADRIGOSA, DONE, InstanceScript::GetBossState(), WorldObject::GetInstanceScript(), instance, Object::SetFlag(), Unit::SetStandState(), Unit::SetVisible(), UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_DEAD, and UNIT_STAND_STATE_DEAD.
Member Function Documentation
DoAction()
void npc_madrigosa::npc_madrigosaAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 225 of file boss_brutallus.cpp.
         {
             if (param == ACTION_START_EVENT)
             {
                 me->SetDisableGravity(true);
                 me->SetStandState(UNIT_STAND_STATE_STAND);
                 me->RemoveFlag(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_DEAD);
                 me->NearTeleportTo(1570.97f, 725.51f, 79.77f, 3.82f);
                 events.ScheduleEvent(EVENT_MAD_1, 2000);
             }
             else if (param == ACTION_SPAWN_FELMYST)
                 events.ScheduleEvent(EVENT_SPAWN_FELMYST, 60000);
         }
References ACTION_SPAWN_FELMYST, ACTION_START_EVENT, EVENT_MAD_1, EVENT_SPAWN_FELMYST, CreatureAI::me, Unit::NearTeleportTo(), Object::RemoveFlag(), Creature::SetDisableGravity(), Unit::SetStandState(), UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_DEAD, and UNIT_STAND_STATE_STAND.
UpdateAI()
void npc_madrigosa::npc_madrigosaAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 239 of file boss_brutallus.cpp.
         {
             events.Update(diff);
             switch (events.ExecuteEvent())
             {
                 case EVENT_MAD_1:
                     me->SetVisible(true);
                     if (Creature* brutallus = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_BRUTALLUS)))
                     {
                         me->SetTarget(brutallus->GetGUID());
                         brutallus->SetReactState(REACT_PASSIVE);
                         brutallus->setActive(true);
                     }
                     me->GetMotionMaster()->MovePoint(1, 1477.94f, 643.22f, 21.21f);
                     me->AddUnitState(UNIT_STATE_NO_ENVIRONMENT_UPD);
                     events.ScheduleEvent(EVENT_MAD_2, 6000);
                     break;
                 case EVENT_MAD_2:
                     Talk(SAY_MAD_1);
                     me->CastSpell(me, SPELL_MADRIGOSA_FREEZE, false);
                     events.ScheduleEvent(EVENT_MAD_2_1, 1000);
                     break;
                 case EVENT_MAD_2_1:
                     me->HandleEmoteCommand(EMOTE_ONESHOT_LAND);
                     me->SetDisableGravity(false);
                     me->CastSpell(me, SPELL_MADRIGOSA_FROST_BREATH, false);
                     events.ScheduleEvent(EVENT_MAD_3, 7000);
                     break;
                 case EVENT_MAD_3:
                     Talk(SAY_MAD_2);
                     events.ScheduleEvent(EVENT_MAD_4, 7000);
                     break;
                 case EVENT_MAD_4:
                     if (Creature* brutallus = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_BRUTALLUS)))
                         brutallus->AI()->Talk(YELL_INTRO);
                     events.ScheduleEvent(EVENT_MAD_5, 5000);
                     break;
                 case EVENT_MAD_5:
                     if (Creature* brutallus = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_BRUTALLUS)))
                     {
                         brutallus->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_ATTACK1H);
                         me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_ATTACK1H);
                     }
                     events.ScheduleEvent(EVENT_MAD_6, 10000);
                     break;
                 case EVENT_MAD_6:
                     if (Creature* brutallus = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_BRUTALLUS)))
                     {
                         brutallus->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                         me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                     }
                     me->HandleEmoteCommand(EMOTE_ONESHOT_LIFTOFF);
                     me->SetDisableGravity(true);
                     events.ScheduleEvent(EVENT_MAD_7, 4000);
                     break;
                 case EVENT_MAD_7:
                     Talk(SAY_MAD_3);
                     me->CastSpell(me, SPELL_MADRIGOSA_FROST_BLAST, false);
                     events.ScheduleEvent(EVENT_MAD_8, 3000);
                     events.ScheduleEvent(EVENT_MAD_8, 5000);
                     events.ScheduleEvent(EVENT_MAD_8, 6500);
                     events.ScheduleEvent(EVENT_MAD_8, 7500);
                     events.ScheduleEvent(EVENT_MAD_8, 8500);
                     events.ScheduleEvent(EVENT_MAD_8, 9500);
                     events.ScheduleEvent(EVENT_MAD_9, 11000);
                     events.ScheduleEvent(EVENT_MAD_8, 12000);
                     events.ScheduleEvent(EVENT_MAD_8, 14000);
                     break;
                 case EVENT_MAD_8:
                     if (Creature* brutallus = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_BRUTALLUS)))
                         me->CastSpell(brutallus, SPELL_MADRIGOSA_FROSTBOLT, false);
                     break;
                 case EVENT_MAD_9:
                     if (Creature* brutallus = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_BRUTALLUS)))
                     {
                         brutallus->CastSpell(brutallus, SPELL_BRUTALLUS_FLAME_RING, true);
                         brutallus->RemoveAllAuras();
                         brutallus->CastSpell(brutallus, SPELL_BRUTALLUS_FEL_FIREBALL, false);
                         brutallus->AI()->Talk(YELL_INTRO_BREAK_ICE);
                     }
                     events.ScheduleEvent(EVENT_MAD_11, 6000);
                     break;
                 //case EVENT_MAD_10:
                 case EVENT_MAD_11:
                     me->SetDisableGravity(false);
                     me->HandleEmoteCommand(EMOTE_ONESHOT_LAND);
                     events.ScheduleEvent(EVENT_MAD_13, 2500);
                     break;
                 case EVENT_MAD_13:
                     Talk(SAY_MAD_4);
                     me->RemoveAllAuras();
                     me->CastSpell(me, SPELL_MADRIGOSA_ENCAPSULATE, false);
                     events.ScheduleEvent(EVENT_MAD_14, 2000);
                     break;
                 case EVENT_MAD_14:
                     if (Creature* brutallus = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_BRUTALLUS)))
                     {
                         brutallus->SetDisableGravity(true);
                         brutallus->GetMotionMaster()->MovePoint(0, brutallus->GetPositionX(), brutallus->GetPositionY() - 30.0f, brutallus->GetPositionZ() + 15.0f, false, true);
                     }
                     events.ScheduleEvent(EVENT_MAD_15, 10000);
                     break;
                 case EVENT_MAD_15:
                     if (Creature* brutallus = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_BRUTALLUS)))
                     {
                         brutallus->RemoveAllAuras();
                         brutallus->SetDisableGravity(false);
                         brutallus->GetMotionMaster()->MoveFall();
                         brutallus->AI()->Talk(YELL_INTRO_CHARGE);
                     }
                     events.ScheduleEvent(EVENT_MAD_16, 1400);
                     break;
                 case EVENT_MAD_16:
                     if (Creature* brutallus = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_BRUTALLUS)))
                         brutallus->CastSpell(me, SPELL_BRUTALLUS_CHARGE, true);
                     events.ScheduleEvent(EVENT_MAD_17, 1200);
                     break;
                 case EVENT_MAD_17:
                     if (Creature* brutallus = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_BRUTALLUS)))
                         brutallus->HandleEmoteCommand(EMOTE_ONESHOT_ATTACK1H);
                     events.ScheduleEvent(EVENT_MAD_18, 500);
                     break;
                 case EVENT_MAD_18:
                     Talk(SAY_MAD_5);
                     me->SetFlag(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_DEAD);
                     me->SetStandState(UNIT_STAND_STATE_DEAD);
                     events.ScheduleEvent(EVENT_MAD_19, 6000);
                     break;
                 case EVENT_MAD_19:
                     if (Creature* brutallus = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_BRUTALLUS)))
                         brutallus->AI()->Talk(YELL_INTRO_KILL_MADRIGOSA);
                     events.ScheduleEvent(EVENT_MAD_20, 7000);
                     break;
                 case EVENT_MAD_20:
                     me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                     me->SetFaction(FACTION_FRIENDLY);
                     if (Creature* brutallus = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_BRUTALLUS)))
                     {
                         brutallus->AI()->Talk(YELL_INTRO_TAUNT);
                         brutallus->CastSpell(brutallus, SPELL_BRUTALLUS_BREAK_ICE, false);
                     }
                     events.ScheduleEvent(EVENT_MAD_21, 4000);
                     break;
                 case EVENT_MAD_21:
                     if (Creature* brutallus = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_BRUTALLUS)))
                     {
                         brutallus->SetReactState(REACT_AGGRESSIVE);
                         brutallus->SetHealth(brutallus->GetMaxHealth());
                         brutallus->AI()->EnterEvadeMode();
                         brutallus->setActive(false);
                     }
                     break;
                 case EVENT_SPAWN_FELMYST:
                     me->DespawnOrUnsummon(1);
                     if (Creature* felmyst = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_FELMYST)))
                         felmyst->AI()->DoAction(ACTION_START_EVENT);
                     break;
             }
         }
References ACTION_START_EVENT, Unit::AddUnitState(), Unit::CastSpell(), Creature::DespawnOrUnsummon(), EMOTE_ONESHOT_ATTACK1H, EMOTE_ONESHOT_LAND, EMOTE_ONESHOT_LIFTOFF, EMOTE_ONESHOT_NONE, EVENT_MAD_1, EVENT_MAD_11, EVENT_MAD_13, EVENT_MAD_14, EVENT_MAD_15, EVENT_MAD_16, EVENT_MAD_17, EVENT_MAD_18, EVENT_MAD_19, EVENT_MAD_2, EVENT_MAD_20, EVENT_MAD_21, EVENT_MAD_2_1, EVENT_MAD_3, EVENT_MAD_4, EVENT_MAD_5, EVENT_MAD_6, EVENT_MAD_7, EVENT_MAD_8, EVENT_MAD_9, EVENT_SPAWN_FELMYST, FACTION_FRIENDLY, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), Unit::HandleEmoteCommand(), instance, CreatureAI::me, MotionMaster::MovePoint(), NPC_BRUTALLUS, NPC_FELMYST, REACT_AGGRESSIVE, REACT_PASSIVE, Unit::RemoveAllAuras(), SAY_MAD_1, SAY_MAD_2, SAY_MAD_3, SAY_MAD_4, SAY_MAD_5, Creature::SetDisableGravity(), Unit::SetFaction(), Object::SetFlag(), Unit::SetStandState(), Creature::SetTarget(), Object::SetUInt32Value(), Unit::SetVisible(), SPELL_BRUTALLUS_BREAK_ICE, SPELL_BRUTALLUS_CHARGE, SPELL_BRUTALLUS_FEL_FIREBALL, SPELL_BRUTALLUS_FLAME_RING, SPELL_MADRIGOSA_ENCAPSULATE, SPELL_MADRIGOSA_FREEZE, SPELL_MADRIGOSA_FROST_BLAST, SPELL_MADRIGOSA_FROST_BREATH, SPELL_MADRIGOSA_FROSTBOLT, CreatureAI::Talk(), UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_DEAD, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, UNIT_NPC_EMOTESTATE, UNIT_STAND_STATE_DEAD, UNIT_STATE_NO_ENVIRONMENT_UPD, YELL_INTRO, YELL_INTRO_BREAK_ICE, YELL_INTRO_CHARGE, YELL_INTRO_KILL_MADRIGOSA, and YELL_INTRO_TAUNT.
Member Data Documentation
events
EventMap npc_madrigosa::npc_madrigosaAI::events
Definition at line 222 of file boss_brutallus.cpp.
instance
InstanceScript* npc_madrigosa::npc_madrigosaAI::instance
Definition at line 223 of file boss_brutallus.cpp.
Referenced by npc_madrigosaAI(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/SunwellPlateau/boss_brutallus.cpp