Azerotcore-wotlk: instance_mechanar::instance_mechanar_InstanceMapScript Struct Reference
instance_mechanar::instance_mechanar_InstanceMapScript Struct Reference
Public Member Functions
instance_mechanar_InstanceMapScript (Map *map)
void OnGameObjectCreate (GameObject *gameObject) override
void OnGameObjectRemove (GameObject *gameObject) override
void OnCreatureCreate (Creature *creature) override
void OnUnitDeath (Unit *unit) override
Player * GetPassagePlayer (float x)
void DoSummonAction (Creature *summon, Player *player)
void Update (uint32 diff) override
bool SetBossState (uint32 type, EncounterState state) override
std::string GetSaveData () override
void Load (const char *str) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void CreatureLooted (Creature *, LootType)
void SaveToDB ()
virtual bool IsEncounterInProgress () const
void OnCreatureRemove (Creature *creature) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Private Attributes
ObjectGuid _pathaleonGUID
uint32 _passageTimer
uint32 _passageEncounter
GuidSet _passageGUIDs
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Definition at line 35 of file instance_mechanar.cpp.
Constructor & Destructor Documentation
instance_mechanar_InstanceMapScript()
instance_mechanar::instance_mechanar_InstanceMapScript::instance_mechanar_InstanceMapScript (Map * map) inline
Definition at line 37 of file instance_mechanar.cpp.
                                                       : InstanceScript(map)
         {
             SetBossNumber(MAX_ENCOUNTER);
             LoadDoorData(doorData);
             _passageEncounter = 0;
             _passageTimer = 0;
             _passageGUIDs.clear();
         }
References _passageEncounter, _passageGUIDs, _passageTimer, doorData, InstanceScript::LoadDoorData(), MAX_ENCOUNTER, and InstanceScript::SetBossNumber().
Member Function Documentation
DoSummonAction()
void instance_mechanar::instance_mechanar_InstanceMapScript::DoSummonAction (Creature * summon, Player * player) inline
Definition at line 99 of file instance_mechanar.cpp.
         {
             summon->CastSpell(summon, SPELL_TELEPORT_VISUAL, true);
             summon->AI()->AttackStart(player);
             _passageGUIDs.insert(summon->GetGUID());
         }
References _passageGUIDs, Creature::AI(), UnitAI::AttackStart(), Unit::CastSpell(), Object::GetGUID(), and SPELL_TELEPORT_VISUAL.
Referenced by Update().
GetPassagePlayer()
Player* instance_mechanar::instance_mechanar_InstanceMapScript::GetPassagePlayer (float x) inline
Definition at line 89 of file instance_mechanar.cpp.
         {
             Map::PlayerList const& pl = instance->GetPlayers();
             for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                 if (Player* player = itr->GetSource())
                     if (player->GetPositionX() < x && player->GetPositionZ() > 24.0f && player->GetPositionY() > -30.0f)
                         return player;
             return nullptr;
         }
References MapRefMgr::begin(), MapRefMgr::end(), Map::GetPlayers(), and InstanceScript::instance.
Referenced by Update().
GetSaveData()
std::string instance_mechanar::instance_mechanar_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
Definition at line 203 of file instance_mechanar.cpp.
         {
             OUT_SAVE_INST_DATA;
             std::ostringstream saveStream;
             // Xinef: no space needed
             saveStream << "M E " << GetBossSaveData() << _passageEncounter;
             OUT_SAVE_INST_DATA_COMPLETE;
             return saveStream.str();
         }
References _passageEncounter, InstanceScript::GetBossSaveData(), OUT_SAVE_INST_DATA, and OUT_SAVE_INST_DATA_COMPLETE.
Load()
void instance_mechanar::instance_mechanar_InstanceMapScript::Load (const char * str) inline override virtual
Reimplemented from InstanceScript.
Definition at line 215 of file instance_mechanar.cpp.
         {
             if (!str)
             {
                 OUT_LOAD_INST_DATA_FAIL;
                 return;
             }
             OUT_LOAD_INST_DATA(str);
             char dataHead1, dataHead2;
             std::istringstream loadStream(str);
             loadStream >> dataHead1 >> dataHead2;
             if (dataHead1 == 'M' && dataHead2 == 'E')
             {
                 for (uint32 i = 0; i < MAX_ENCOUNTER; ++i)
                 {
                     uint32 tmpState;
                     loadStream >> tmpState;
                     if (tmpState == IN_PROGRESS || tmpState > SPECIAL)
                         tmpState = NOT_STARTED;
                     SetBossState(i, EncounterState(tmpState));
                 }
                 loadStream >> _passageEncounter;
                 if (_passageEncounter == ENCOUNTER_PASSAGE_DONE)
                     _passageEncounter = ENCOUNTER_PASSAGE_PHASE6;
             }
             else
                 OUT_LOAD_INST_DATA_FAIL;
             OUT_LOAD_INST_DATA_COMPLETE;
         }
References _passageEncounter, ENCOUNTER_PASSAGE_DONE, ENCOUNTER_PASSAGE_PHASE6, IN_PROGRESS, MAX_ENCOUNTER, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, OUT_LOAD_INST_DATA_FAIL, SetBossState(), and SPECIAL.
OnCreatureCreate()
void instance_mechanar::instance_mechanar_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 75 of file instance_mechanar.cpp.
         {
             if (creature->GetEntry() == NPC_PATHALEON_THE_CALCULATOR)
                 _pathaleonGUID = creature->GetGUID();
         }
References _pathaleonGUID, Object::GetEntry(), Object::GetGUID(), and NPC_PATHALEON_THE_CALCULATOR.
OnGameObjectCreate()
void instance_mechanar::instance_mechanar_InstanceMapScript::OnGameObjectCreate (GameObject * gameObject) inline override virtual
Reimplemented from InstanceScript.
Definition at line 47 of file instance_mechanar.cpp.
         {
             switch (gameObject->GetEntry())
             {
                 case GO_DOOR_MOARG_1:
                 case GO_DOOR_MOARG_2:
                 case GO_DOOR_NETHERMANCER:
                     AddDoor(gameObject, true);
                     break;
                 default:
                     break;
             }
         }
References InstanceScript::AddDoor(), Object::GetEntry(), GO_DOOR_MOARG_1, GO_DOOR_MOARG_2, and GO_DOOR_NETHERMANCER.
OnGameObjectRemove()
void instance_mechanar::instance_mechanar_InstanceMapScript::OnGameObjectRemove (GameObject * gameObject) inline override virtual
Reimplemented from InstanceScript.
Definition at line 61 of file instance_mechanar.cpp.
         {
             switch (gameObject->GetEntry())
             {
                 case GO_DOOR_MOARG_1:
                 case GO_DOOR_MOARG_2:
                 case GO_DOOR_NETHERMANCER:
                     AddDoor(gameObject, false);
                     break;
                 default:
                     break;
             }
         }
References InstanceScript::AddDoor(), Object::GetEntry(), GO_DOOR_MOARG_1, GO_DOOR_MOARG_2, and GO_DOOR_NETHERMANCER.
OnUnitDeath()
void instance_mechanar::instance_mechanar_InstanceMapScript::OnUnitDeath (Unit * unit) inline override virtual
Reimplemented from ZoneScript.
Definition at line 81 of file instance_mechanar.cpp.
         {
             if (unit->GetTypeId() == TYPEID_UNIT)
                 if (_passageEncounter > ENCOUNTER_PASSAGE_NOT_STARTED && _passageEncounter < ENCOUNTER_PASSAGE_DONE)
                     if (_passageGUIDs.find(unit->GetGUID()) != _passageGUIDs.end())
                         _passageGUIDs.erase(unit->GetGUID());
         }
References _passageEncounter, _passageGUIDs, ENCOUNTER_PASSAGE_DONE, ENCOUNTER_PASSAGE_NOT_STARTED, Object::GetGUID(), Object::GetTypeId(), and TYPEID_UNIT.
SetBossState()
bool instance_mechanar::instance_mechanar_InstanceMapScript::SetBossState (uint32 type, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
Definition at line 195 of file instance_mechanar.cpp.
         {
             if (!InstanceScript::SetBossState(type, state))
                 return false;
             return true;
         }
References InstanceScript::SetBossState().
Referenced by Load().
Update()
void instance_mechanar::instance_mechanar_InstanceMapScript::Update (uint32 diff) inline override virtual
Reimplemented from InstanceScript.
Definition at line 106 of file instance_mechanar.cpp.
         {
             if (_passageEncounter == ENCOUNTER_PASSAGE_DONE)
                 return;
             _passageTimer += diff;
             if (_passageTimer >= 1000)
             {
                 _passageTimer = 0;
                 if (_passageEncounter == ENCOUNTER_PASSAGE_NOT_STARTED)
                 {
                     if (Player* player = GetPassagePlayer(250.0f))
                     {
                         _passageEncounter++;
                         for (uint8 i = 0; i < 4; ++i)
{
                             Position pos = {238.0f, -27.0f + 3.0f * i, 26.328f, 0.0f};
                             if (Creature* creature = instance->SummonCreature(i == 1 || i == 2 ? NPC_SUNSEEKER_ASTROMAGE : NPC_BLOODWARDER_CENTURION, pos))
                                 DoSummonAction(creature, player);
                         }
                     }
                 }
                 if (!_passageGUIDs.empty())
                     return;
                 if (_passageEncounter < ENCOUNTER_PASSAGE_PHASE3)
                 {
                     if (Player* player = GetPassagePlayer(250.0f))
                     {
                         if (_passageEncounter == ENCOUNTER_PASSAGE_PHASE1)
{
                             Position pos = {214.37f, -23.5f, 24.88f, 0.0f};
                             if (Creature* creature = instance->SummonCreature(NPC_TEMPEST_KEEPER_DESTROYER, pos))
                                 DoSummonAction(creature, player);
                         }
                         else if (_passageEncounter == ENCOUNTER_PASSAGE_PHASE2)
{
                             for (uint8 i = 0; i < 3; ++i)
{
                                 Position pos = {199.76f, -26.0f + 2.5f * i, 24.88f, 0.0f};
                                 if (Creature* creature = instance->SummonCreature(i == 1 ? NPC_SUNSEEKER_ENGINEER : NPC_BLOODWARDER_PHYSICIAN, pos))
                                     DoSummonAction(creature, player);
                             }
                         }
                         _passageEncounter++;
                         SaveToDB();
                     }
                 }
                 else
                 {
                     if (Player* player = GetPassagePlayer(148.0f))
                     {
                         if (_passageEncounter == ENCOUNTER_PASSAGE_PHASE3)
{
                             for (uint8 i = 0; i < 3; ++i)
{
                                 Position pos = {135.0f + 2.5f * i, 36.76f, 24.88f, M_PI * 1.5f};
                                 if (Creature* creature = instance->SummonCreature(i == 1 ? NPC_SUNSEEKER_ASTROMAGE : NPC_BLOODWARDER_PHYSICIAN, pos))
                                     DoSummonAction(creature, player);
                             }
                         }
                         else if (_passageEncounter == ENCOUNTER_PASSAGE_PHASE4)
{
                             Position pos = {137.62f, 62.23f, 24.88f, M_PI * 1.5f};
                             if (Creature* creature = instance->SummonCreature(NPC_TEMPEST_KEEPER_DESTROYER, pos))
                                 DoSummonAction(creature, player);
                         }
                         else if (_passageEncounter == ENCOUNTER_PASSAGE_PHASE5)
{
                             for (uint8 i = 0; i < 4; ++i)
{
                                 Position pos = {133.0f + 3.5f * i, 92.88f, 26.38f, M_PI * 1.5f};
                                 if (Creature* creature = instance->SummonCreature(i == 1 || i == 2 ? NPC_SUNSEEKER_ASTROMAGE : NPC_SUNSEEKER_ENGINEER, pos))
                                     DoSummonAction(creature, player);
                             }
                         }
                         else if (_passageEncounter == ENCOUNTER_PASSAGE_PHASE6)
{
                             if (Creature* creature = instance->GetCreature(_pathaleonGUID))
                                 creature->AI()->DoAction(1);
                         }
                         _passageEncounter++;
                         SaveToDB();
                     }
                 }
             }
         }
References _passageEncounter, _passageGUIDs, _passageTimer, _pathaleonGUID, DoSummonAction(), ENCOUNTER_PASSAGE_DONE, ENCOUNTER_PASSAGE_NOT_STARTED, ENCOUNTER_PASSAGE_PHASE1, ENCOUNTER_PASSAGE_PHASE2, ENCOUNTER_PASSAGE_PHASE3, ENCOUNTER_PASSAGE_PHASE4, ENCOUNTER_PASSAGE_PHASE5, ENCOUNTER_PASSAGE_PHASE6, Map::GetCreature(), GetPassagePlayer(), InstanceScript::instance, NPC_BLOODWARDER_CENTURION, NPC_BLOODWARDER_PHYSICIAN, NPC_SUNSEEKER_ASTROMAGE, NPC_SUNSEEKER_ENGINEER, NPC_TEMPEST_KEEPER_DESTROYER, InstanceScript::SaveToDB(), and Map::SummonCreature().
Member Data Documentation
_passageEncounter
uint32 instance_mechanar::instance_mechanar_InstanceMapScript::_passageEncounter private
Definition at line 254 of file instance_mechanar.cpp.
Referenced by GetSaveData(), instance_mechanar_InstanceMapScript(), Load(), OnUnitDeath(), and Update().
_passageGUIDs
GuidSet instance_mechanar::instance_mechanar_InstanceMapScript::_passageGUIDs private
Definition at line 255 of file instance_mechanar.cpp.
Referenced by DoSummonAction(), instance_mechanar_InstanceMapScript(), OnUnitDeath(), and Update().
_passageTimer
uint32 instance_mechanar::instance_mechanar_InstanceMapScript::_passageTimer private
Definition at line 253 of file instance_mechanar.cpp.
Referenced by instance_mechanar_InstanceMapScript(), and Update().
_pathaleonGUID
ObjectGuid instance_mechanar::instance_mechanar_InstanceMapScript::_pathaleonGUID private
Definition at line 252 of file instance_mechanar.cpp.
Referenced by OnCreatureCreate(), and Update().
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/TempestKeep/Mechanar/instance_mechanar.cpp