Azerotcore-wotlk: npc_pet_gen_plump_turkey Struct Reference
npc_pet_gen_plump_turkey Struct Reference
Public Member Functions
npc_pet_gen_plump_turkey (Creature *c)
void MovementInform (uint32 type, uint32 id) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from PassiveAI
PassiveAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
ObjectGuid goGUID
uint32 jumpTimer
uint32 checkTimer
bool jumping
Additional Inherited Members
Static Public Member Functions inherited from PassiveAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 674 of file pet_generic.cpp.
Constructor & Destructor Documentation
npc_pet_gen_plump_turkey()
npc_pet_gen_plump_turkey::npc_pet_gen_plump_turkey (Creature * c) inline
Definition at line 676 of file pet_generic.cpp.
                                           : PassiveAI(c)
     {
         goGUID.Clear();
         jumpTimer = 0;
         checkTimer = 0;
         jumping = false;
     }
References checkTimer, ObjectGuid::Clear(), goGUID, jumping, and jumpTimer.
Member Function Documentation
MovementInform()
void npc_pet_gen_plump_turkey::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from CreatureAI.
Definition at line 689 of file pet_generic.cpp.
     {
         if (type == EFFECT_MOTION_TYPE && id == 1)
         {
             Unit::Kill(me, me);
             me->AddAura(SPELL_TURKEY_STARTS_TO_BURN, me);
         }
     }
References Unit::AddAura(), EFFECT_MOTION_TYPE, Unit::Kill(), CreatureAI::me, and SPELL_TURKEY_STARTS_TO_BURN.
UpdateAI()
void npc_pet_gen_plump_turkey::UpdateAI (uint32 diff) inline override virtual
Reimplemented from PassiveAI.
Definition at line 698 of file pet_generic.cpp.
     {
         if (jumping)
             return;
         if (jumpTimer)
         {
             jumpTimer += diff;
             if (jumpTimer >= 2000)
             {
                 if (GameObject* go = me->GetMap()->GetGameObject(goGUID))
                     me->GetMotionMaster()->MoveJump(*go, 5.0f, 10.0f, 1);
                 jumping = true;
             }
             return;
         }
         checkTimer += diff;
         if (checkTimer > 3000)
         {
             checkTimer = 0;
             if (GameObject* go = me->FindNearestGameObject(GO_BASIC_CAMPFIRE, 7.0f))
             {
                 goGUID = go->GetGUID();
                 me->StopMoving();
                 me->GetMotionMaster()->Clear(false);
                 me->SetFacingTo(me->GetAngle(go));
                 Talk(0);
                 jumpTimer = 1;
             }
         }
     }
References checkTimer, MotionMaster::Clear(), WorldObject::FindNearestGameObject(), Position::GetAngle(), Map::GetGameObject(), WorldObject::GetMap(), Unit::GetMotionMaster(), GO_BASIC_CAMPFIRE, goGUID, jumping, jumpTimer, CreatureAI::me, MotionMaster::MoveJump(), Unit::SetFacingTo(), Unit::StopMoving(), and CreatureAI::Talk().
Member Data Documentation
checkTimer
uint32 npc_pet_gen_plump_turkey::checkTimer
Definition at line 686 of file pet_generic.cpp.
Referenced by npc_pet_gen_plump_turkey(), and UpdateAI().
goGUID
ObjectGuid npc_pet_gen_plump_turkey::goGUID
Definition at line 684 of file pet_generic.cpp.
Referenced by npc_pet_gen_plump_turkey(), and UpdateAI().
jumping
bool npc_pet_gen_plump_turkey::jumping
Definition at line 687 of file pet_generic.cpp.
Referenced by npc_pet_gen_plump_turkey(), and UpdateAI().
jumpTimer
uint32 npc_pet_gen_plump_turkey::jumpTimer
Definition at line 685 of file pet_generic.cpp.
Referenced by npc_pet_gen_plump_turkey(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Pet/pet_generic.cpp