Azerotcore-wotlk: SpellInfo Class Reference
SpellInfo Class Reference
#include <SpellInfo.h>
Public Member Functions
SpellInfo (SpellEntry const *spellEntry)
~SpellInfo ()
uint32 GetCategory () const
bool HasEffect (SpellEffects effect) const
bool HasAura (AuraType aura) const
bool HasAnyAura () const
bool HasAreaAuraEffect () const
bool HasAttribute (SpellAttr0 attribute) const
bool HasAttribute (SpellAttr1 attribute) const
bool HasAttribute (SpellAttr2 attribute) const
bool HasAttribute (SpellAttr3 attribute) const
bool HasAttribute (SpellAttr4 attribute) const
bool HasAttribute (SpellAttr5 attribute) const
bool HasAttribute (SpellAttr6 attribute) const
bool HasAttribute (SpellAttr7 attribute) const
bool HasAttribute (SpellCustomAttributes customAttribute) const
bool IsExplicitDiscovery () const
bool IsLootCrafting () const
bool IsQuestTame () const
bool IsProfessionOrRiding () const
bool IsProfession () const
bool IsPrimaryProfession () const
bool IsPrimaryProfessionFirstRank () const
bool IsAbilityLearnedWithProfession () const
bool IsAbilityOfSkillType (uint32 skillType) const
bool IsAffectingArea () const
bool IsTargetingArea () const
bool NeedsExplicitUnitTarget () const
bool NeedsToBeTriggeredByCaster (SpellInfo const *triggeringSpell, uint8 effIndex=MAX_SPELL_EFFECTS) const
bool IsChannelCategorySpell () const
bool IsSelfCast () const
bool IsPassive () const
bool IsAutocastable () const
bool ComputeIsCritCapable () const
bool IsCritCapable () const
bool RequireCooldownInfo () const
void SetCritCapable (bool val)
bool ComputeIsStackableWithRanks () const
bool IsStackableWithRanks () const
void SetStackableWithRanks (bool val)
bool IsSpellValid () const
void SetSpellValid (bool val)
bool IsPassiveStackableWithRanks () const
bool IsMultiSlotAura () const
bool IsCooldownStartedOnEvent () const
bool IsDeathPersistent () const
bool IsRequiringDeadTarget () const
bool IsAllowingDeadTarget () const
bool CanBeUsedInCombat () const
bool IsPositive () const
bool IsPositiveEffect (uint8 effIndex) const
bool IsChanneled () const
bool IsMoveAllowedChannel () const
bool NeedsComboPoints () const
bool IsBreakingStealth () const
bool IsRangedWeaponSpell () const
bool IsAutoRepeatRangedSpell () const
bool IsAffectedBySpellMods () const
bool IsAffectedBySpellMod (SpellModifier const *mod) const
bool CanPierceImmuneAura (SpellInfo const *aura) const
bool CanDispelAura (SpellInfo const *aura) const
bool IsSingleTarget () const
bool IsAuraExclusiveBySpecificWith (SpellInfo const *spellInfo) const
bool IsAuraExclusiveBySpecificPerCasterWith (SpellInfo const *spellInfo) const
SpellCastResult CheckShapeshift (uint32 form) const
SpellCastResult CheckLocation (uint32 map_id, uint32 zone_id, uint32 area_id, Player const *player=nullptr, bool strict=true) const
SpellCastResult CheckTarget (Unit const *caster, WorldObject const *target, bool implicit=true) const
SpellCastResult CheckExplicitTarget (Unit const *caster, WorldObject const *target, Item const *itemTarget=nullptr) const
bool CheckTargetCreatureType (Unit const *target) const
bool IsStrongerAuraActive (Unit const *caster, Unit const *target) const
bool IsAuraEffectEqual (SpellInfo const *otherSpellInfo) const
bool ValidateAttribute6SpellDamageMods (const Unit *caster, const AuraEffect *auraEffect, bool isDot) const
SpellSchoolMask GetSchoolMask () const
uint32 GetAllEffectsMechanicMask () const
uint32 GetEffectMechanicMask (uint8 effIndex) const
uint32 GetSpellMechanicMaskByEffectMask (uint32 effectMask) const
Mechanics GetEffectMechanic (uint8 effIndex) const
bool HasAnyEffectMechanic () const
uint32 GetDispelMask () const
uint32 GetExplicitTargetMask () const
AuraStateType GetAuraState () const
SpellSpecificType GetSpellSpecific () const
float GetMinRange (bool positive=false) const
float GetMaxRange (bool positive=false, Unit *caster=nullptr, Spell *spell=nullptr) const
int32 GetDuration () const
int32 GetMaxDuration () const
uint32 GetMaxTicks () const
uint32 CalcCastTime (Unit *caster=nullptr, Spell *spell=nullptr) const
uint32 GetRecoveryTime () const
int32 CalcPowerCost (Unit const *caster, SpellSchoolMask schoolMask, Spell *spell=nullptr) const
bool IsRanked () const
uint8 GetRank () const
SpellInfo const * GetFirstRankSpell () const
SpellInfo const * GetLastRankSpell () const
SpellInfo const * GetNextRankSpell () const
SpellInfo const * GetPrevRankSpell () const
SpellInfo const * GetAuraRankForLevel (uint8 level) const
bool IsRankOf (SpellInfo const *spellInfo) const
bool IsDifferentRankOf (SpellInfo const *spellInfo) const
bool IsHighRankOf (SpellInfo const *spellInfo) const
void _InitializeExplicitTargetMask ()
bool _IsPositiveEffect (uint8 effIndex, bool deep) const
bool _IsPositiveSpell () const
AuraStateType LoadAuraState () const
SpellSpecificType LoadSpellSpecific () const
void _UnloadImplicitTargetConditionLists ()
Static Public Member Functions
static uint32 GetDispelMask (DispelType type)
static bool _IsPositiveTarget (uint32 targetA, uint32 targetB)
Public Attributes
uint32 Id
SpellCategoryEntry const * CategoryEntry
uint32 Dispel
uint32 Mechanic
uint32 Attributes
uint32 AttributesEx
uint32 AttributesEx2
uint32 AttributesEx3
uint32 AttributesEx4
uint32 AttributesEx5
uint32 AttributesEx6
uint32 AttributesEx7
uint32 AttributesCu
uint32 Stances
uint32 StancesNot
uint32 Targets
uint32 TargetCreatureType
uint32 RequiresSpellFocus
uint32 FacingCasterFlags
uint32 CasterAuraState
uint32 TargetAuraState
uint32 CasterAuraStateNot
uint32 TargetAuraStateNot
uint32 CasterAuraSpell
uint32 TargetAuraSpell
uint32 ExcludeCasterAuraSpell
uint32 ExcludeTargetAuraSpell
SpellCastTimesEntry const * CastTimeEntry
uint32 RecoveryTime
uint32 CategoryRecoveryTime
uint32 StartRecoveryCategory
uint32 StartRecoveryTime
uint32 InterruptFlags
uint32 AuraInterruptFlags
uint32 ChannelInterruptFlags
uint32 ProcFlags
uint32 ProcChance
uint32 ProcCharges
uint32 MaxLevel
uint32 BaseLevel
uint32 SpellLevel
SpellDurationEntry const * DurationEntry
uint32 PowerType
uint32 ManaCost
uint32 ManaCostPerlevel
uint32 ManaPerSecond
uint32 ManaPerSecondPerLevel
uint32 ManaCostPercentage
uint32 RuneCostID
SpellRangeEntry const * RangeEntry
float Speed
uint32 StackAmount
std::array< uint32, 2 > Totem
std::array< int32, MAX_SPELL_REAGENTS > Reagent
std::array< uint32, MAX_SPELL_REAGENTS > ReagentCount
int32 EquippedItemClass
int32 EquippedItemSubClassMask
int32 EquippedItemInventoryTypeMask
std::array< uint32, 2 > TotemCategory
std::array< uint32, 2 > SpellVisual
uint32 SpellIconID
uint32 ActiveIconID
std::array< char const *, 16 > SpellName
std::array< char const *, 16 > Rank
uint32 MaxTargetLevel
uint32 MaxAffectedTargets
uint32 SpellFamilyName
flag96 SpellFamilyFlags
uint32 DmgClass
uint32 PreventionType
int32 AreaGroupId
uint32 SchoolMask
std::array< SpellEffectInfo, MAX_SPELL_EFFECTS > Effects
uint32 ExplicitTargetMask
SpellChainNode const * ChainEntry
AuraStateType _auraState
SpellSpecificType _spellSpecific
bool _isStackableWithRanks
bool _isSpellValid
bool _isCritCapable
bool _requireCooldownInfo
Detailed Description
Definition at line 312 of file SpellInfo.h.
Constructor & Destructor Documentation
SpellInfo()
SpellInfo::SpellInfo (SpellEntry const * spellEntry)
Definition at line 771 of file SpellInfo.cpp.
 {
     Id = spellEntry->Id;
     CategoryEntry = spellEntry->Category ? sSpellCategoryStore.LookupEntry(spellEntry->Category) : nullptr;
     Dispel = spellEntry->Dispel;
     Mechanic = spellEntry->Mechanic;
     Attributes = spellEntry->Attributes;
     AttributesEx = spellEntry->AttributesEx;
     AttributesEx2 = spellEntry->AttributesEx2;
     AttributesEx3 = spellEntry->AttributesEx3;
     AttributesEx4 = spellEntry->AttributesEx4;
     AttributesEx5 = spellEntry->AttributesEx5;
     AttributesEx6 = spellEntry->AttributesEx6;
     AttributesEx7 = spellEntry->AttributesEx7;
     AttributesCu = 0;
     Stances = spellEntry->Stances;
     StancesNot = spellEntry->StancesNot;
     Targets = spellEntry->Targets;
     TargetCreatureType = spellEntry->TargetCreatureType;
     RequiresSpellFocus = spellEntry->RequiresSpellFocus;
     FacingCasterFlags = spellEntry->FacingCasterFlags;
     CasterAuraState = spellEntry->CasterAuraState;
     TargetAuraState = spellEntry->TargetAuraState;
     CasterAuraStateNot = spellEntry->CasterAuraStateNot;
     TargetAuraStateNot = spellEntry->TargetAuraStateNot;
     CasterAuraSpell = spellEntry->CasterAuraSpell;
     TargetAuraSpell = spellEntry->TargetAuraSpell;
     ExcludeCasterAuraSpell = spellEntry->ExcludeCasterAuraSpell;
     ExcludeTargetAuraSpell = spellEntry->ExcludeTargetAuraSpell;
     CastTimeEntry = spellEntry->CastingTimeIndex ? sSpellCastTimesStore.LookupEntry(spellEntry->CastingTimeIndex) : nullptr;
     RecoveryTime = spellEntry->RecoveryTime;
     CategoryRecoveryTime = spellEntry->CategoryRecoveryTime;
     StartRecoveryCategory = spellEntry->StartRecoveryCategory;
     StartRecoveryTime = spellEntry->StartRecoveryTime;
     InterruptFlags = spellEntry->InterruptFlags;
     AuraInterruptFlags = spellEntry->AuraInterruptFlags;
     ChannelInterruptFlags = spellEntry->ChannelInterruptFlags;
     ProcFlags = spellEntry->ProcFlags;
     ProcChance = spellEntry->ProcChance;
     ProcCharges = spellEntry->ProcCharges;
     MaxLevel = spellEntry->MaxLevel;
     BaseLevel = spellEntry->BaseLevel;
     SpellLevel = spellEntry->SpellLevel;
     DurationEntry = spellEntry->DurationIndex ? sSpellDurationStore.LookupEntry(spellEntry->DurationIndex) : nullptr;
     PowerType = spellEntry->PowerType;
     ManaCost = spellEntry->ManaCost;
     ManaCostPerlevel = spellEntry->ManaCostPerlevel;
     ManaPerSecond = spellEntry->ManaPerSecond;
     ManaPerSecondPerLevel = spellEntry->ManaPerSecondPerLevel;
     ManaCostPercentage = spellEntry->ManaCostPercentage;
     RuneCostID = spellEntry->RuneCostID;
     RangeEntry = spellEntry->RangeIndex ? sSpellRangeStore.LookupEntry(spellEntry->RangeIndex) : nullptr;
     Speed = spellEntry->Speed;
     StackAmount = spellEntry->StackAmount;
     Totem = spellEntry->Totem;
     Reagent = spellEntry->Reagent;
     ReagentCount = spellEntry->ReagentCount;
     EquippedItemClass = spellEntry->EquippedItemClass;
     EquippedItemSubClassMask = spellEntry->EquippedItemSubClassMask;
     EquippedItemInventoryTypeMask = spellEntry->EquippedItemInventoryTypeMask;
     TotemCategory = spellEntry->TotemCategory;
     SpellVisual = spellEntry->SpellVisual;
     SpellIconID = spellEntry->SpellIconID;
     ActiveIconID = spellEntry->ActiveIconID;
     SpellName = spellEntry->SpellName;
     Rank = spellEntry->Rank;
     MaxTargetLevel = spellEntry->MaxTargetLevel;
     MaxAffectedTargets = spellEntry->MaxAffectedTargets;
     SpellFamilyName = spellEntry->SpellFamilyName;
     SpellFamilyFlags = spellEntry->SpellFamilyFlags;
     DmgClass = spellEntry->DmgClass;
     PreventionType = spellEntry->PreventionType;
     AreaGroupId = spellEntry->AreaGroupId;
     SchoolMask = spellEntry->SchoolMask;
     for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
         Effects[i] = SpellEffectInfo(spellEntry, this, i);
     ChainEntry = nullptr;
     ExplicitTargetMask = 0;
     // Mine
     _isStackableWithRanks = false;
     _isSpellValid = true;
     _isCritCapable = false;
     _requireCooldownInfo = false;
 }
References _isCritCapable, _isSpellValid, _isStackableWithRanks, _requireCooldownInfo, ActiveIconID, SpellEntry::ActiveIconID, AreaGroupId, SpellEntry::AreaGroupId, Attributes, SpellEntry::Attributes, AttributesCu, AttributesEx, SpellEntry::AttributesEx, AttributesEx2, SpellEntry::AttributesEx2, AttributesEx3, SpellEntry::AttributesEx3, AttributesEx4, SpellEntry::AttributesEx4, AttributesEx5, SpellEntry::AttributesEx5, AttributesEx6, SpellEntry::AttributesEx6, AttributesEx7, SpellEntry::AttributesEx7, AuraInterruptFlags, SpellEntry::AuraInterruptFlags, BaseLevel, SpellEntry::BaseLevel, CasterAuraSpell, SpellEntry::CasterAuraSpell, CasterAuraState, SpellEntry::CasterAuraState, CasterAuraStateNot, SpellEntry::CasterAuraStateNot, SpellEntry::CastingTimeIndex, CastTimeEntry, SpellEntry::Category, CategoryEntry, CategoryRecoveryTime, SpellEntry::CategoryRecoveryTime, ChainEntry, ChannelInterruptFlags, SpellEntry::ChannelInterruptFlags, Dispel, SpellEntry::Dispel, DmgClass, SpellEntry::DmgClass, DurationEntry, SpellEntry::DurationIndex, Effects, EquippedItemClass, SpellEntry::EquippedItemClass, EquippedItemInventoryTypeMask, SpellEntry::EquippedItemInventoryTypeMask, EquippedItemSubClassMask, SpellEntry::EquippedItemSubClassMask, ExcludeCasterAuraSpell, SpellEntry::ExcludeCasterAuraSpell, ExcludeTargetAuraSpell, SpellEntry::ExcludeTargetAuraSpell, ExplicitTargetMask, FacingCasterFlags, SpellEntry::FacingCasterFlags, Id, SpellEntry::Id, InterruptFlags, SpellEntry::InterruptFlags, ManaCost, SpellEntry::ManaCost, ManaCostPercentage, SpellEntry::ManaCostPercentage, ManaCostPerlevel, SpellEntry::ManaCostPerlevel, ManaPerSecond, SpellEntry::ManaPerSecond, ManaPerSecondPerLevel, SpellEntry::ManaPerSecondPerLevel, MAX_SPELL_EFFECTS, MaxAffectedTargets, SpellEntry::MaxAffectedTargets, MaxLevel, SpellEntry::MaxLevel, MaxTargetLevel, SpellEntry::MaxTargetLevel, Mechanic, SpellEntry::Mechanic, SpellEntry::PowerType, PreventionType, SpellEntry::PreventionType, ProcChance, SpellEntry::ProcChance, ProcCharges, SpellEntry::ProcCharges, SpellEntry::ProcFlags, RangeEntry, SpellEntry::RangeIndex, Rank, SpellEntry::Rank, Reagent, SpellEntry::Reagent, ReagentCount, SpellEntry::ReagentCount, RecoveryTime, SpellEntry::RecoveryTime, RequiresSpellFocus, SpellEntry::RequiresSpellFocus, RuneCostID, SpellEntry::RuneCostID, SchoolMask, SpellEntry::SchoolMask, Speed, SpellEntry::Speed, SpellFamilyFlags, SpellEntry::SpellFamilyFlags, SpellFamilyName, SpellEntry::SpellFamilyName, SpellIconID, SpellEntry::SpellIconID, SpellLevel, SpellEntry::SpellLevel, SpellName, SpellEntry::SpellName, SpellVisual, SpellEntry::SpellVisual, sSpellCastTimesStore, sSpellCategoryStore, sSpellDurationStore, sSpellRangeStore, StackAmount, SpellEntry::StackAmount, Stances, SpellEntry::Stances, StancesNot, SpellEntry::StancesNot, StartRecoveryCategory, SpellEntry::StartRecoveryCategory, StartRecoveryTime, SpellEntry::StartRecoveryTime, TargetAuraSpell, SpellEntry::TargetAuraSpell, TargetAuraState, SpellEntry::TargetAuraState, TargetAuraStateNot, SpellEntry::TargetAuraStateNot, TargetCreatureType, SpellEntry::TargetCreatureType, SpellEntry::Targets, SpellEntry::Totem, and SpellEntry::TotemCategory.
~SpellInfo()
SpellInfo::~SpellInfo ()
Definition at line 858 of file SpellInfo.cpp.
 {
     _UnloadImplicitTargetConditionLists();
 }
References _UnloadImplicitTargetConditionLists().
Member Function Documentation
_InitializeExplicitTargetMask()
void SpellInfo::_InitializeExplicitTargetMask ()
Definition at line 2533 of file SpellInfo.cpp.
 {
     bool srcSet = false;
     bool dstSet = false;
     uint32 targetMask = Targets;
     // prepare target mask using effect target entries
     for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
     {
         if (!Effects[i].IsEffect())
             continue;
         targetMask |= Effects[i].TargetA.GetExplicitTargetMask(srcSet, dstSet);
         targetMask |= Effects[i].TargetB.GetExplicitTargetMask(srcSet, dstSet);
         // add explicit target flags based on spell effects which have EFFECT_IMPLICIT_TARGET_EXPLICIT and no valid target provided
         if (Effects[i].GetImplicitTargetType() != EFFECT_IMPLICIT_TARGET_EXPLICIT)
             continue;
         // extend explicit target mask only if valid targets for effect could not be provided by target types
         uint32 effectTargetMask = Effects[i].GetMissingTargetMask(srcSet, dstSet, targetMask);
         // don't add explicit object/dest flags when spell has no max range
         if (GetMaxRange(true) == 0.0f && GetMaxRange(false) == 0.0f)
             effectTargetMask &= ~(TARGET_FLAG_UNIT_MASK | TARGET_FLAG_GAMEOBJECT | TARGET_FLAG_CORPSE_MASK | TARGET_FLAG_DEST_LOCATION);
         targetMask |= effectTargetMask;
     }
     ExplicitTargetMask = targetMask;
 }
References EFFECT_IMPLICIT_TARGET_EXPLICIT, Effects, ExplicitTargetMask, GetMaxRange(), MAX_SPELL_EFFECTS, TARGET_FLAG_CORPSE_MASK, TARGET_FLAG_DEST_LOCATION, TARGET_FLAG_GAMEOBJECT, TARGET_FLAG_UNIT_MASK, and Targets.
Referenced by SpellMgr::LoadSpellCustomAttr().
_IsPositiveEffect()
bool SpellInfo::_IsPositiveEffect (uint8 effIndex, bool deep) const
Definition at line 2561 of file SpellInfo.cpp.
 {
     // not found a single positive spell with this attribute
     if (HasAttribute(SPELL_ATTR0_AURA_IS_DEBUFF))
         return false;
     switch (Mechanic)
     {
         case MECHANIC_IMMUNE_SHIELD:
             return true;
         default:
             break;
     }
     // Special case: effects which determine positivity of whole spell
     for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
     {
         if (Effects[i].IsAura() && Effects[i].ApplyAuraName == SPELL_AURA_MOD_STEALTH)
             return true;
     }
     switch (Effects[effIndex].Effect)
     {
         case SPELL_EFFECT_DUMMY:
             // some explicitly required dummy effect sets
             switch (Id)
             {
                 case 28441:
                     return false; // AB Effect 000
                 default:
                     break;
             }
             break;
         // always positive effects (check before target checks that provided non-positive result in some case for positive effects)
         case SPELL_EFFECT_HEAL:
         case SPELL_EFFECT_LEARN_SPELL:
         case SPELL_EFFECT_SKILL_STEP:
         case SPELL_EFFECT_HEAL_PCT:
         case SPELL_EFFECT_ENERGIZE_PCT:
             return true;
         case SPELL_EFFECT_APPLY_AREA_AURA_ENEMY:
             return false;
         case SPELL_EFFECT_GAMEOBJECT_DAMAGE:
             return false;
         case SPELL_EFFECT_SCHOOL_DAMAGE:
             {
                 bool only = true;
                 for (int i = EFFECT_0; i <= EFFECT_2; ++i)
                 {
                     if (Effects[effIndex].Effect > 0 && Effects[effIndex].Effect != SPELL_EFFECT_SCHOOL_DAMAGE)
                         only = false;
                     if (Effects[effIndex].Effect == SPELL_EFFECT_GAMEOBJECT_DAMAGE)
                         return false;
                 }
                 // effects with school damage only cannot be positive...
                 if (only)
                     return false;
                 break;
             }
         case SPELL_EFFECT_KNOCK_BACK:
         case SPELL_EFFECT_KNOCK_BACK_DEST:
             {
                 for (int i = EFFECT_0; i <= EFFECT_2; ++i)
                     if (Effects[effIndex].Effect == SPELL_EFFECT_GAMEOBJECT_DAMAGE)
                         return false;
                 break;
             }
         // non-positive aura use
         case SPELL_EFFECT_APPLY_AURA:
         case SPELL_EFFECT_APPLY_AREA_AURA_FRIEND:
             {
                 switch (Effects[effIndex].ApplyAuraName)
                 {
                     case SPELL_AURA_MOD_DAMAGE_DONE:            // dependent from bas point sign (negative -> negative)
                     case SPELL_AURA_MOD_STAT:
                     case SPELL_AURA_MOD_SKILL:
                     case SPELL_AURA_MOD_DODGE_PERCENT:
                     case SPELL_AURA_MOD_HEALING_PCT:
                     case SPELL_AURA_MOD_HEALING_DONE:
                     case SPELL_AURA_MOD_DAMAGE_PERCENT_DONE:
                         if (Effects[effIndex].CalcValue() < 0)
                             return false;
                         break;
                     case SPELL_AURA_MOD_DAMAGE_TAKEN:           // dependent from bas point sign (positive -> negative)
                         if (Effects[effIndex].CalcValue() > 0)
                             return false;
                         break;
                     case SPELL_AURA_MOD_CRIT_PCT:
                     case SPELL_AURA_MOD_SPELL_CRIT_CHANCE:
                         if (Effects[effIndex].CalcValue() > 0)
                             return true;                        // some expected positive spells have SPELL_ATTR1_NEGATIVE
                         break;
                     case SPELL_AURA_ADD_TARGET_TRIGGER:
                         return true;
                     case SPELL_AURA_PERIODIC_TRIGGER_SPELL_WITH_VALUE:
                     case SPELL_AURA_PERIODIC_TRIGGER_SPELL:
                         if (!deep)
{
                             if (SpellInfo const* spellTriggeredProto = sSpellMgr->GetSpellInfo(Effects[effIndex].TriggerSpell))
{
                                 // negative targets of main spell return early
                                 for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
{
                                     if (!spellTriggeredProto->Effects[i].Effect)
                                         continue;
                                     // if non-positive trigger cast targeted to positive target this main cast is non-positive
                                     // this will place this spell auras as debuffs
                                     if (_IsPositiveTarget(spellTriggeredProto->Effects[i].TargetA.GetTarget(), spellTriggeredProto->Effects[i].TargetB.GetTarget()) && !spellTriggeredProto->_IsPositiveEffect(i, true))
                                         return false;
                                 }
                             }
                         }
                     case SPELL_AURA_PROC_TRIGGER_SPELL:
                         // many positive auras have negative triggered spells at damage for example and this not make it negative (it can be canceled for example)
                         break;
                     case SPELL_AURA_MOD_STUN:                   //have positive and negative spells, we can't sort its correctly at this moment.
                         if (effIndex == 0 && Effects[1].Effect == 0 && Effects[2].Effect == 0)
                             return false;                       // but all single stun aura spells is negative
                         break;
                     case SPELL_AURA_MOD_PACIFY_SILENCE:
                         if (Id == 24740)             // Wisp Costume
                             return true;
                         return false;
                     case SPELL_AURA_MOD_ROOT:
                     case SPELL_AURA_MOD_SILENCE:
                     case SPELL_AURA_GHOST:
                     case SPELL_AURA_PERIODIC_LEECH:
                     case SPELL_AURA_MOD_STALKED:
                     case SPELL_AURA_PERIODIC_DAMAGE_PERCENT:
                     case SPELL_AURA_PREVENT_RESURRECTION:
                         return false;
                     case SPELL_AURA_PERIODIC_DAMAGE:            // used in positive spells also.
                         // part of negative spell if casted at self (prevent cancel)
                         if (Effects[effIndex].TargetA.GetTarget() == TARGET_UNIT_CASTER)
                             return false;
                         break;
                     case SPELL_AURA_MOD_DECREASE_SPEED:         // used in positive spells also
                         // part of positive spell if casted at self
                         if (Effects[effIndex].TargetA.GetTarget() != TARGET_UNIT_CASTER)
                             return false;
                         // but not this if this first effect (didn't find better check)
                         if (HasAttribute(SPELL_ATTR0_AURA_IS_DEBUFF) && effIndex == 0)
                             return false;
                         break;
                     case SPELL_AURA_MECHANIC_IMMUNITY:
{
                             // non-positive immunities
                             switch (Effects[effIndex].MiscValue)
{
                                 case MECHANIC_BANDAGE:
                                 case MECHANIC_SHIELD:
                                 case MECHANIC_MOUNT:
                                 case MECHANIC_INVULNERABILITY:
                                     return false;
                                 default:
                                     break;
                             }
                             break;
                         }
                     case SPELL_AURA_ADD_FLAT_MODIFIER:          // mods
                     case SPELL_AURA_ADD_PCT_MODIFIER:
{
                             // non-positive mods
                             switch (Effects[effIndex].MiscValue)
{
                                 case SPELLMOD_COST:                 // dependent from bas point sign (negative -> positive)
                                     if (Effects[effIndex].CalcValue() > 0)
{
                                         if (!deep)
{
                                             bool negative = true;
                                             for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
{
                                                 if (i != effIndex)
                                                     if (_IsPositiveEffect(i, true))
{
                                                         negative = false;
                                                         break;
                                                     }
                                             }
                                             if (negative)
                                                 return false;
                                         }
                                     }
                                     break;
                                 default:
                                     break;
                             }
                             break;
                         }
                     default:
                         break;
                 }
                 break;
             }
         default:
             break;
     }
     // non-positive targets
     if (!_IsPositiveTarget(Effects[effIndex].TargetA.GetTarget(), Effects[effIndex].TargetB.GetTarget()))
         return false;
     // negative spell if triggered spell is negative
     if (!deep && !Effects[effIndex].ApplyAuraName && Effects[effIndex].TriggerSpell)
     {
         if (SpellInfo const* spellTriggeredProto = sSpellMgr->GetSpellInfo(Effects[effIndex].TriggerSpell))
             if (!spellTriggeredProto->_IsPositiveSpell())
                 return false;
     }
     // ok, positive
     return true;
 }
References _IsPositiveTarget(), EFFECT_0, EFFECT_2, Effects, HasAttribute(), Id, MAX_SPELL_EFFECTS, Mechanic, MECHANIC_BANDAGE, MECHANIC_IMMUNE_SHIELD, MECHANIC_INVULNERABILITY, MECHANIC_MOUNT, MECHANIC_SHIELD, SPELL_ATTR0_AURA_IS_DEBUFF, SPELL_AURA_ADD_FLAT_MODIFIER, SPELL_AURA_ADD_PCT_MODIFIER, SPELL_AURA_ADD_TARGET_TRIGGER, SPELL_AURA_GHOST, SPELL_AURA_MECHANIC_IMMUNITY, SPELL_AURA_MOD_CRIT_PCT, SPELL_AURA_MOD_DAMAGE_DONE, SPELL_AURA_MOD_DAMAGE_PERCENT_DONE, SPELL_AURA_MOD_DAMAGE_TAKEN, SPELL_AURA_MOD_DECREASE_SPEED, SPELL_AURA_MOD_DODGE_PERCENT, SPELL_AURA_MOD_HEALING_DONE, SPELL_AURA_MOD_HEALING_PCT, SPELL_AURA_MOD_PACIFY_SILENCE, SPELL_AURA_MOD_ROOT, SPELL_AURA_MOD_SILENCE, SPELL_AURA_MOD_SKILL, SPELL_AURA_MOD_SPELL_CRIT_CHANCE, SPELL_AURA_MOD_STALKED, SPELL_AURA_MOD_STAT, SPELL_AURA_MOD_STEALTH, SPELL_AURA_MOD_STUN, SPELL_AURA_PERIODIC_DAMAGE, SPELL_AURA_PERIODIC_DAMAGE_PERCENT, SPELL_AURA_PERIODIC_LEECH, SPELL_AURA_PERIODIC_TRIGGER_SPELL, SPELL_AURA_PERIODIC_TRIGGER_SPELL_WITH_VALUE, SPELL_AURA_PREVENT_RESURRECTION, SPELL_AURA_PROC_TRIGGER_SPELL, SPELL_EFFECT_APPLY_AREA_AURA_ENEMY, SPELL_EFFECT_APPLY_AREA_AURA_FRIEND, SPELL_EFFECT_APPLY_AURA, SPELL_EFFECT_DUMMY, SPELL_EFFECT_ENERGIZE_PCT, SPELL_EFFECT_GAMEOBJECT_DAMAGE, SPELL_EFFECT_HEAL, SPELL_EFFECT_HEAL_PCT, SPELL_EFFECT_KNOCK_BACK, SPELL_EFFECT_KNOCK_BACK_DEST, SPELL_EFFECT_LEARN_SPELL, SPELL_EFFECT_SCHOOL_DAMAGE, SPELL_EFFECT_SKILL_STEP, SPELLMOD_COST, sSpellMgr, and TARGET_UNIT_CASTER.
Referenced by _IsPositiveSpell(), WorldSession::HandlePetActionHelper(), and SpellMgr::LoadSpellCustomAttr().
_IsPositiveSpell()
bool SpellInfo::_IsPositiveSpell () const
Definition at line 2779 of file SpellInfo.cpp.
 {
     // spells with at least one negative effect are considered negative
     // some self-applied spells have negative effects but in self casting case negative check ignored.
     for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
         if (!_IsPositiveEffect(i, true))
             return false;
     return true;
 }
References _IsPositiveEffect(), and MAX_SPELL_EFFECTS.
Referenced by Spell::HandleThreatSpells().
_IsPositiveTarget()
bool SpellInfo::_IsPositiveTarget (uint32 targetA, uint32 targetB) static
Definition at line 2789 of file SpellInfo.cpp.
 {
     // non-positive targets
     switch (targetA)
     {
         case TARGET_UNIT_NEARBY_ENEMY:
         case TARGET_UNIT_TARGET_ENEMY:
         case TARGET_UNIT_SRC_AREA_ENEMY:
         case TARGET_UNIT_DEST_AREA_ENEMY:
         case TARGET_UNIT_CONE_ENEMY_24:
         case TARGET_UNIT_CONE_ENEMY_54:
         case TARGET_UNIT_CONE_ENEMY_104:
         case TARGET_DEST_DYNOBJ_ENEMY:
         case TARGET_DEST_TARGET_ENEMY:
             return false;
         default:
             break;
     }
     if (targetB)
         return _IsPositiveTarget(targetB, 0);
     return true;
 }
References TARGET_DEST_DYNOBJ_ENEMY, TARGET_DEST_TARGET_ENEMY, TARGET_UNIT_CONE_ENEMY_104, TARGET_UNIT_CONE_ENEMY_24, TARGET_UNIT_CONE_ENEMY_54, TARGET_UNIT_DEST_AREA_ENEMY, TARGET_UNIT_NEARBY_ENEMY, TARGET_UNIT_SRC_AREA_ENEMY, and TARGET_UNIT_TARGET_ENEMY.
Referenced by _IsPositiveEffect().
_UnloadImplicitTargetConditionLists()
void SpellInfo::_UnloadImplicitTargetConditionLists ()
Definition at line 2812 of file SpellInfo.cpp.
 {
     // find the same instances of ConditionList and delete them.
     for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
     {
         ConditionList* cur = Effects[i].ImplicitTargetConditions;
         if (!cur)
             continue;
         for (uint8 j = i; j < MAX_SPELL_EFFECTS; ++j)
         {
             if (Effects[j].ImplicitTargetConditions == cur)
                 Effects[j].ImplicitTargetConditions = nullptr;
         }
         delete cur;
     }
 }
References Effects, and MAX_SPELL_EFFECTS.
Referenced by ~SpellInfo().
CalcCastTime()
uint32 SpellInfo::CalcCastTime (Unit * caster = nullptr, Spell * spell = nullptr) const
Definition at line 2294 of file SpellInfo.cpp.
 {
     // not all spells have cast time index and this is all is pasiive abilities
     if (!CastTimeEntry)
         return 0;
     int32 castTime = CastTimeEntry->CastTime;
     if (HasAttribute(SPELL_ATTR0_USES_RANGED_SLOT) && (!IsAutoRepeatRangedSpell()))
         castTime += 500;
     if (caster)
         caster->ModSpellCastTime(this, castTime, spell);
     return (castTime > 0) ? uint32(castTime) : 0;
 }
References SpellCastTimesEntry::CastTime, CastTimeEntry, HasAttribute(), IsAutoRepeatRangedSpell(), Unit::ModSpellCastTime(), and SPELL_ATTR0_USES_RANGED_SLOT.
Referenced by Unit::CalculateDefaultCoefficient(), GameObject::CastSpell(), Spell::finish(), Unit::GetCastingTimeForBonus(), Spell::prepare(), Player::PrepareCharmAISpells(), and Unit::ProcDamageAndSpellFor().
CalcPowerCost()
int32 SpellInfo::CalcPowerCost (Unit const * caster, SpellSchoolMask schoolMask, Spell * spell = nullptr) const
Definition at line 2342 of file SpellInfo.cpp.
 {
     // Spell drain all exist power on cast (Only paladin lay of Hands)
     if (AttributesEx & SPELL_ATTR1_USE_ALL_MANA)
     {
         // If power type - health drain all
         if (PowerType == POWER_HEALTH)
             return caster->GetHealth();
         // Else drain all power
         if (PowerType < MAX_POWERS)
             return caster->GetPower(Powers(PowerType));
         LOG_ERROR("spells", "SpellInfo::CalcPowerCost: Unknown power type '%d' in spell %d", PowerType, Id);
         return 0;
     }
     // Base powerCost
     int32 powerCost = ManaCost;
     // PCT cost from total amount
     if (ManaCostPercentage)
     {
         switch (PowerType)
         {
             // health as power used
             case POWER_HEALTH:
                 powerCost += int32(CalculatePct(caster->GetCreateHealth(), ManaCostPercentage));
                 break;
             case POWER_MANA:
                 powerCost += int32(CalculatePct(caster->GetCreateMana(), ManaCostPercentage));
                 break;
             case POWER_RAGE:
             case POWER_FOCUS:
             case POWER_ENERGY:
             case POWER_HAPPINESS:
                 powerCost += int32(CalculatePct(caster->GetMaxPower(Powers(PowerType)), ManaCostPercentage));
                 break;
             case POWER_RUNE:
             case POWER_RUNIC_POWER:
                 LOG_DEBUG("spells.aura", "CalculateManaCost: Not implemented yet!");
                 break;
             default:
                 LOG_ERROR("spells", "CalculateManaCost: Unknown power type '%d' in spell %d", PowerType, Id);
                 return 0;
         }
     }
     SpellSchools school = GetFirstSchoolInMask(schoolMask);
     // Flat mod from caster auras by spell school
     powerCost += caster->GetInt32Value(static_cast<uint16>(UNIT_FIELD_POWER_COST_MODIFIER) + school);
     // Shiv - costs 20 + weaponSpeed*10 energy (apply only to non-triggered spell with energy cost)
     if (AttributesEx4 & SPELL_ATTR4_WEAPON_SPEED_COST_SCALING)
     {
         uint32 speed = 0;
         if (SpellShapeshiftEntry const* ss = sSpellShapeshiftStore.LookupEntry(caster->GetShapeshiftForm()))
             speed = ss->attackSpeed;
         else
         {
             WeaponAttackType slot = BASE_ATTACK;
             if (AttributesEx3 & SPELL_ATTR3_REQUIRES_OFF_HAND_WEAPON)
                 slot = OFF_ATTACK;
             speed = caster->GetAttackTime(slot);
         }
         powerCost += speed / 100;
     }
     // Apply cost mod by spell
     if (Player* modOwner = caster->GetSpellModOwner())
         modOwner->ApplySpellMod(Id, SPELLMOD_COST, powerCost, spell);
     if (!caster->IsControlledByPlayer())
     {
         if (HasAttribute(SPELL_ATTR0_SCALES_WITH_CREATURE_LEVEL))
         {
             GtNPCManaCostScalerEntry const* spellScaler = sGtNPCManaCostScalerStore.LookupEntry(SpellLevel - 1);
             GtNPCManaCostScalerEntry const* casterScaler = sGtNPCManaCostScalerStore.LookupEntry(caster->getLevel() - 1);
             if (spellScaler && casterScaler)
                 powerCost *= casterScaler->ratio / spellScaler->ratio;
         }
     }
     // PCT mod from user auras by school
     powerCost = int32(powerCost * (1.0f + caster->GetFloatValue(static_cast<uint16>(UNIT_FIELD_POWER_COST_MULTIPLIER) + school)));
     if (powerCost < 0)
         powerCost = 0;
     return powerCost;
 }
References AttributesEx, AttributesEx3, AttributesEx4, BASE_ATTACK, CalculatePct(), Unit::GetAttackTime(), Unit::GetCreateHealth(), Unit::GetCreateMana(), GetFirstSchoolInMask(), Object::GetFloatValue(), Unit::GetHealth(), Object::GetInt32Value(), Unit::getLevel(), Unit::GetMaxPower(), Unit::GetPower(), Unit::GetShapeshiftForm(), Unit::GetSpellModOwner(), HasAttribute(), Id, Unit::IsControlledByPlayer(), LOG_DEBUG, LOG_ERROR, ManaCost, ManaCostPercentage, MAX_POWERS, OFF_ATTACK, POWER_ENERGY, POWER_FOCUS, POWER_HAPPINESS, POWER_HEALTH, POWER_MANA, POWER_RAGE, POWER_RUNE, POWER_RUNIC_POWER, GtNPCManaCostScalerEntry::ratio, sGtNPCManaCostScalerStore, SPELL_ATTR0_SCALES_WITH_CREATURE_LEVEL, SPELL_ATTR1_USE_ALL_MANA, SPELL_ATTR3_REQUIRES_OFF_HAND_WEAPON, SPELL_ATTR4_WEAPON_SPEED_COST_SCALING, SpellLevel, SPELLMOD_COST, sSpellShapeshiftStore, UNIT_FIELD_POWER_COST_MODIFIER, and UNIT_FIELD_POWER_COST_MULTIPLIER.
Referenced by PetAI::_canMeleeAttack(), Spell::CheckPetCast(), Spell::EffectCastButtons(), Unit::HandleDummyAuraProc(), spell_warr_execute::HandleEffect(), spell_hun_glyph_of_arcane_shot::HandleProc(), spell_mage_burnout::HandleProc(), spell_mage_master_of_elements::HandleProc(), spell_sha_item_mana_surge::HandleProc(), and Spell::prepare().
CanBeUsedInCombat()
bool SpellInfo::CanBeUsedInCombat () const
Definition at line 1215 of file SpellInfo.cpp.
 {
     return !(HasAttribute(SPELL_ATTR0_NOT_IN_COMBAT_ONLY_PEACEFUL));
 }
References HasAttribute(), and SPELL_ATTR0_NOT_IN_COMBAT_ONLY_PEACEFUL.
Referenced by Spell::CheckCast(), and PetAI::UpdateAI().
CanDispelAura()
bool SpellInfo::CanDispelAura (SpellInfo const * aura) const
Definition at line 1322 of file SpellInfo.cpp.
 {
     // Xinef: Passive auras cannot be dispelled
     if (aura->IsPassive())
         return false;
     // These auras (like Divine Shield) can't be dispelled
     if (aura->HasAttribute(SPELL_ATTR0_NO_IMMUNITIES))
         return false;
     // These spells (like Mass Dispel) can dispell all auras
     if (HasAttribute(SPELL_ATTR0_NO_IMMUNITIES))
         return true;
     // These auras (Cyclone for example) are not dispelable
     if ((aura->HasAttribute(SPELL_ATTR1_IMMUNITY_TO_HOSTILE_AND_FRIENDLY_EFFECTS) && aura->Mechanic != MECHANIC_NONE)
         || aura->HasAttribute(SPELL_ATTR2_NO_SCHOOL_IMMUNITIES))
     {
         return false;
     }
     return true;
 }
References HasAttribute(), IsPassive(), Mechanic, MECHANIC_NONE, SPELL_ATTR0_NO_IMMUNITIES, SPELL_ATTR1_IMMUNITY_TO_HOSTILE_AND_FRIENDLY_EFFECTS, and SPELL_ATTR2_NO_SCHOOL_IMMUNITIES.
CanPierceImmuneAura()
bool SpellInfo::CanPierceImmuneAura (SpellInfo const * aura) const
Definition at line 1295 of file SpellInfo.cpp.
 {
     // aura can't be pierced
     if (!aura || aura->HasAttribute(SPELL_ATTR0_NO_IMMUNITIES))
     {
         return false;
     }
     // these spells pierce all avalible spells (Resurrection Sickness for example)
     if (HasAttribute(SPELL_ATTR0_NO_IMMUNITIES))
         return true;
     // these spells (Cyclone for example) can pierce all...
     if (HasAttribute(SPELL_ATTR1_IMMUNITY_TO_HOSTILE_AND_FRIENDLY_EFFECTS) || HasAttribute(SPELL_ATTR2_NO_SCHOOL_IMMUNITIES))
     {
         if (aura->Mechanic != MECHANIC_IMMUNE_SHIELD &&
                aura->Mechanic != MECHANIC_INVULNERABILITY &&
                aura->Mechanic != MECHANIC_BANISH)
         {
             return true;
         }
     }
     return false;
 }
References HasAttribute(), Mechanic, MECHANIC_BANISH, MECHANIC_IMMUNE_SHIELD, MECHANIC_INVULNERABILITY, SPELL_ATTR0_NO_IMMUNITIES, SPELL_ATTR1_IMMUNITY_TO_HOSTILE_AND_FRIENDLY_EFFECTS, and SPELL_ATTR2_NO_SCHOOL_IMMUNITIES.
Referenced by Unit::IsImmunedToSchool(), and Unit::IsImmunedToSpell().
CheckExplicitTarget()
SpellCastResult SpellInfo::CheckExplicitTarget (Unit const * caster, WorldObject const * target, Item const * itemTarget = nullptr) const
Definition at line 1881 of file SpellInfo.cpp.
 {
     uint32 neededTargets = GetExplicitTargetMask();
     if (!target)
     {
         if (neededTargets & (TARGET_FLAG_UNIT_MASK | TARGET_FLAG_GAMEOBJECT_MASK | TARGET_FLAG_CORPSE_MASK))
             if (!(neededTargets & TARGET_FLAG_GAMEOBJECT_ITEM) || !itemTarget)
                 return SPELL_FAILED_BAD_TARGETS;
         return SPELL_CAST_OK;
     }
     if (Unit const* unitTarget = target->ToUnit())
     {
         if (neededTargets & (TARGET_FLAG_UNIT_ENEMY | TARGET_FLAG_UNIT_ALLY | TARGET_FLAG_UNIT_RAID | TARGET_FLAG_UNIT_PARTY | TARGET_FLAG_UNIT_MINIPET | TARGET_FLAG_UNIT_PASSENGER))
         {
             if (neededTargets & TARGET_FLAG_UNIT_ENEMY)
                 if (caster->_IsValidAttackTarget(unitTarget, this))
                     return SPELL_CAST_OK;
             if (neededTargets & TARGET_FLAG_UNIT_ALLY
                     || (neededTargets & TARGET_FLAG_UNIT_PARTY && caster->IsInPartyWith(unitTarget))
                     || (neededTargets & TARGET_FLAG_UNIT_RAID && caster->IsInRaidWith(unitTarget)))
                 if (caster->_IsValidAssistTarget(unitTarget, this))
                     return SPELL_CAST_OK;
             if (neededTargets & TARGET_FLAG_UNIT_MINIPET)
                 if (unitTarget->GetGUID() == caster->GetCritterGUID())
                     return SPELL_CAST_OK;
             if (neededTargets & TARGET_FLAG_UNIT_PASSENGER)
                 if (unitTarget->IsOnVehicle(caster))
                     return SPELL_CAST_OK;
             return SPELL_FAILED_BAD_TARGETS;
         }
     }
     return SPELL_CAST_OK;
 }
References Unit::_IsValidAssistTarget(), Unit::_IsValidAttackTarget(), Unit::GetCritterGUID(), GetExplicitTargetMask(), Unit::IsInPartyWith(), Unit::IsInRaidWith(), SPELL_CAST_OK, SPELL_FAILED_BAD_TARGETS, TARGET_FLAG_CORPSE_MASK, TARGET_FLAG_GAMEOBJECT_ITEM, TARGET_FLAG_GAMEOBJECT_MASK, TARGET_FLAG_UNIT_ALLY, TARGET_FLAG_UNIT_ENEMY, TARGET_FLAG_UNIT_MASK, TARGET_FLAG_UNIT_MINIPET, TARGET_FLAG_UNIT_PARTY, TARGET_FLAG_UNIT_PASSENGER, TARGET_FLAG_UNIT_RAID, and Object::ToUnit().
Referenced by Spell::CheckCast(), Unit::GetMagicHitRedirectTarget(), Unit::GetMeleeHitRedirectTarget(), and Spell::InitExplicitTargets().
CheckLocation()
SpellCastResult SpellInfo::CheckLocation (uint32 map_id, uint32 zone_id, uint32 area_id, Player const * player = nullptr, bool strict = true) const
Definition at line 1469 of file SpellInfo.cpp.
 {
     // normal case
     if (AreaGroupId > 0)
     {
         bool found = false;
         AreaGroupEntry const* groupEntry = sAreaGroupStore.LookupEntry(AreaGroupId);
         while (groupEntry)
         {
             for (uint8 i = 0; i < MAX_GROUP_AREA_IDS; ++i)
                 if (groupEntry->AreaId[i] == zone_id || groupEntry->AreaId[i] == area_id)
                     found = true;
             if (found || !groupEntry->nextGroup)
                 break;
             // Try search in next group
             groupEntry = sAreaGroupStore.LookupEntry(groupEntry->nextGroup);
         }
         if (!found)
             return SPELL_FAILED_INCORRECT_AREA;
     }
     // continent limitation (virtual continent)
     if (HasAttribute(SPELL_ATTR4_ONLY_FLYING_AREAS))
     {
         AreaTableEntry const* areaEntry = sAreaTableStore.LookupEntry(area_id);
         if (!areaEntry)
         {
             areaEntry = sAreaTableStore.LookupEntry(zone_id);
         }
         if (!areaEntry || !areaEntry->IsFlyable() || (strict && (areaEntry->flags & AREA_FLAG_NO_FLY_ZONE) != 0) || !player->canFlyInZone(map_id, zone_id, this))
         {
             return SPELL_FAILED_INCORRECT_AREA;
         }
     }
     // raid instance limitation
     if (HasAttribute(SPELL_ATTR6_NOT_IN_RAID_INSTANCES))
     {
         MapEntry const* mapEntry = sMapStore.LookupEntry(map_id);
         if (!mapEntry || mapEntry->IsRaid())
             return SPELL_FAILED_NOT_IN_RAID_INSTANCE;
     }
     // DB base check (if non empty then must fit at least single for allow)
     SpellAreaMapBounds saBounds = sSpellMgr->GetSpellAreaMapBounds(Id);
     if (saBounds.first != saBounds.second)
     {
         for (SpellAreaMap::const_iterator itr = saBounds.first; itr != saBounds.second; ++itr)
         {
             if (itr->second.IsFitToRequirements(player, zone_id, area_id))
                 return SPELL_CAST_OK;
         }
         return SPELL_FAILED_INCORRECT_AREA;
     }
     // bg spell checks
     switch (Id)
     {
         case 23333:                                         // Warsong Flag
         case 23335:                                         // Silverwing Flag
             return map_id == 489 && player && player->InBattleground() ? SPELL_CAST_OK : SPELL_FAILED_REQUIRES_AREA;
         case 34976:                                         // Netherstorm Flag
             return map_id == 566 && player && player->InBattleground() ? SPELL_CAST_OK : SPELL_FAILED_REQUIRES_AREA;
         case 2584:                                          // Waiting to Resurrect
         case 22011:                                         // Spirit Heal Channel
         case 22012:                                         // Spirit Heal
         case 24171:                                         // Resurrection Impact Visual
         case 42792:                                         // Recently Dropped Flag
         case 43681:                                         // Inactive
         case 44535:                                         // Spirit Heal (mana)
             {
                 MapEntry const* mapEntry = sMapStore.LookupEntry(map_id);
                 if (!mapEntry)
                     return SPELL_FAILED_INCORRECT_AREA;
                 return zone_id == 4197 || (mapEntry->IsBattleground() && player && player->InBattleground()) ? SPELL_CAST_OK : SPELL_FAILED_REQUIRES_AREA;
             }
         case 32724:                                         // Gold Team (Alliance)
         case 32725:                                         // Green Team (Alliance)
         case 35774:                                         // Gold Team (Horde)
         case 35775:                                         // Green Team (Horde)
             {
                 MapEntry const* mapEntry = sMapStore.LookupEntry(map_id);
                 if (!mapEntry)
                     return SPELL_FAILED_INCORRECT_AREA;
                 return mapEntry->IsBattleArena() && player && player->InBattleground() ? SPELL_CAST_OK : SPELL_FAILED_REQUIRES_AREA;
             }
     }
     return SPELL_CAST_OK;
 }
References AREA_FLAG_NO_FLY_ZONE, AreaGroupId, AreaGroupEntry::AreaId, Player::canFlyInZone(), AreaTableEntry::flags, HasAttribute(), Id, Player::InBattleground(), MapEntry::IsBattleArena(), MapEntry::IsBattleground(), AreaTableEntry::IsFlyable(), MapEntry::IsRaid(), MAX_GROUP_AREA_IDS, AreaGroupEntry::nextGroup, sAreaGroupStore, sAreaTableStore, sMapStore, SPELL_ATTR4_ONLY_FLYING_AREAS, SPELL_ATTR6_NOT_IN_RAID_INSTANCES, SPELL_CAST_OK, SPELL_FAILED_INCORRECT_AREA, SPELL_FAILED_NOT_IN_RAID_INSTANCE, SPELL_FAILED_REQUIRES_AREA, and sSpellMgr.
Referenced by Spell::CheckCast().
CheckShapeshift()
SpellCastResult SpellInfo::CheckShapeshift (uint32 form) const
Definition at line 1414 of file SpellInfo.cpp.
 {
     // talents that learn spells can have stance requirements that need ignore
     // (this requirement only for client-side stance show in talent description)
     if (GetTalentSpellCost(Id) > 0 &&
             (Effects[0].Effect == SPELL_EFFECT_LEARN_SPELL || Effects[1].Effect == SPELL_EFFECT_LEARN_SPELL || Effects[2].Effect == SPELL_EFFECT_LEARN_SPELL))
         return SPELL_CAST_OK;
     uint32 stanceMask = (form ? 1 << (form - 1) : 0);
     if (stanceMask & StancesNot)                 // can explicitly not be casted in this stance
         return SPELL_FAILED_NOT_SHAPESHIFT;
     if (stanceMask & Stances)                    // can explicitly be casted in this stance
         return SPELL_CAST_OK;
     bool actAsShifted = false;
     SpellShapeshiftEntry const* shapeInfo = nullptr;
     if (form > 0)
     {
         shapeInfo = sSpellShapeshiftStore.LookupEntry(form);
         if (!shapeInfo)
         {
             LOG_ERROR("spells", "GetErrorAtShapeshiftedCast: unknown shapeshift %u", form);
             return SPELL_CAST_OK;
         }
         actAsShifted = !(shapeInfo->flags1 & 1);            // shapeshift acts as normal form for spells
     }
     if (actAsShifted)
     {
         if (HasAttribute(SPELL_ATTR0_NOT_SHAPESHIFTED)) // not while shapeshifted
             return SPELL_FAILED_NOT_SHAPESHIFT;
         else if (Stances != 0)                   // needs other shapeshift
             return SPELL_FAILED_ONLY_SHAPESHIFT;
     }
     else
     {
         // needs shapeshift
         if (!(AttributesEx2 & SPELL_ATTR2_ALLOW_WHILE_NOT_SHAPESHIFTED) && Stances != 0)
             return SPELL_FAILED_ONLY_SHAPESHIFT;
     }
     // Check if stance disables cast of not-stance spells
     // Example: cannot cast any other spells in zombie or ghoul form
     // TODO: Find a way to disable use of these spells clientside
     if (shapeInfo && shapeInfo->flags1 & 0x400)
     {
         if (!(stanceMask & Stances))
             return SPELL_FAILED_ONLY_SHAPESHIFT;
     }
     return SPELL_CAST_OK;
 }
References AttributesEx2, Effects, SpellShapeshiftEntry::flags1, GetTalentSpellCost(), HasAttribute(), Id, LOG_ERROR, SPELL_ATTR0_NOT_SHAPESHIFTED, SPELL_ATTR2_ALLOW_WHILE_NOT_SHAPESHIFTED, SPELL_CAST_OK, SPELL_EFFECT_LEARN_SPELL, SPELL_FAILED_NOT_SHAPESHIFT, SPELL_FAILED_ONLY_SHAPESHIFT, sSpellShapeshiftStore, Stances, and StancesNot.
Referenced by Player::ApplyEquipSpell(), and Spell::CheckCast().
CheckTarget()
SpellCastResult SpellInfo::CheckTarget (Unit const * caster, WorldObject const * target, bool implicit = true) const
Definition at line 1733 of file SpellInfo.cpp.
 {
     if (AttributesEx & SPELL_ATTR1_EXCLUDE_CASTER && caster == target)
         return SPELL_FAILED_BAD_TARGETS;
     // check visibility - ignore stealth for implicit (area) targets
     if (!(AttributesEx6 & SPELL_ATTR6_IGNORE_PHASE_SHIFT) && !caster->CanSeeOrDetect(target, implicit))
         return SPELL_FAILED_BAD_TARGETS;
     Unit const* unitTarget = target->ToUnit();
     // creature/player specific target checks
     if (unitTarget)
     {
         // xinef: spells cannot be cast if player is in fake combat also
         if (AttributesEx & SPELL_ATTR1_ONLY_PEACEFUL_TARGETS && (unitTarget->IsInCombat() || unitTarget->IsPetInCombat()))
             return SPELL_FAILED_TARGET_AFFECTING_COMBAT;
         // only spells with SPELL_ATTR3_ONLY_ON_GHOSTS can target ghosts
         if (((IsRequiringDeadTarget() != 0) != unitTarget->HasAuraType(SPELL_AURA_GHOST)) && !(IsDeathPersistent() && IsAllowingDeadTarget()))
         {
             if (AttributesEx3 & SPELL_ATTR3_ONLY_ON_GHOSTS)
                 return SPELL_FAILED_TARGET_NOT_GHOST;
             else
                 return SPELL_FAILED_BAD_TARGETS;
         }
         if (caster != unitTarget)
         {
             if (caster->GetTypeId() == TYPEID_PLAYER)
             {
                 // Do not allow these spells to target creatures not tapped by us (Banish, Polymorph, many quest spells)
                 if (AttributesEx2 & SPELL_ATTR2_CANNOT_CAST_ON_TAPPED)
                     if (Creature const* targetCreature = unitTarget->ToCreature())
                         if (targetCreature->hasLootRecipient() && !targetCreature->isTappedBy(caster->ToPlayer()))
                             return SPELL_FAILED_CANT_CAST_ON_TAPPED;
                 if (AttributesCu & SPELL_ATTR0_CU_PICKPOCKET)
                 {
                     if (unitTarget->GetTypeId() == TYPEID_PLAYER)
                         return SPELL_FAILED_BAD_TARGETS;
                     else if ((unitTarget->GetCreatureTypeMask() & CREATURE_TYPEMASK_HUMANOID_OR_UNDEAD) == 0)
                         return SPELL_FAILED_TARGET_NO_POCKETS;
                 }
                 // Not allow disarm unarmed player
                 if (Mechanic == MECHANIC_DISARM)
                 {
                     if (unitTarget->GetTypeId() == TYPEID_PLAYER)
                     {
                         Player const* player = unitTarget->ToPlayer();
                         if (!player->GetWeaponForAttack(BASE_ATTACK, true))
                             return SPELL_FAILED_TARGET_NO_WEAPONS;
                     }
                     else if (!unitTarget->GetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID))
                         return SPELL_FAILED_TARGET_NO_WEAPONS;
                 }
             }
         }
     }
     // corpse specific target checks
     else if (Corpse const* corpseTarget = target->ToCorpse())
     {
         // cannot target bare bones
         if (corpseTarget->GetType() == CORPSE_BONES)
             return SPELL_FAILED_BAD_TARGETS;
         // we have to use owner for some checks (aura preventing resurrection for example)
         if (Player* owner = ObjectAccessor::FindPlayer(corpseTarget->GetOwnerGUID()))
             unitTarget = owner;
         // we're not interested in corpses without owner
         else
             return SPELL_FAILED_BAD_TARGETS;
     }
     // other types of objects - always valid
     else return SPELL_CAST_OK;
     // corpseOwner and unit specific target checks
     if (AttributesEx3 & SPELL_ATTR3_ONLY_ON_PLAYER && !unitTarget->ToPlayer())
         return SPELL_FAILED_TARGET_NOT_PLAYER;
     if (!IsAllowingDeadTarget() && !unitTarget->IsAlive())
         return SPELL_FAILED_TARGETS_DEAD;
     // check this flag only for implicit targets (chain and area), allow to explicitly target units for spells like Shield of Righteousness
     if (implicit && AttributesEx6 & SPELL_ATTR6_DO_NOT_CHAIN_TO_CROWD_CONTROLLED_TARGETS && !unitTarget->CanFreeMove())
         return SPELL_FAILED_BAD_TARGETS;
     // checked in Unit::IsValidAttack/AssistTarget, shouldn't be checked for ENTRY targets
     //if (!(AttributesEx6 & SPELL_ATTR6_CAN_TARGET_UNTARGETABLE) && target->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE))
     //    return SPELL_FAILED_BAD_TARGETS;
     //if (!(AttributesEx6 & SPELL_ATTR6_NO_AURA_LOG)
     if (!CheckTargetCreatureType(unitTarget))
     {
         if (target->GetTypeId() == TYPEID_PLAYER)
             return SPELL_FAILED_TARGET_IS_PLAYER;
         else
             return SPELL_FAILED_BAD_TARGETS;
     }
     // check GM mode and GM invisibility - only for player casts (npc casts are controlled by AI) and negative spells
     if (unitTarget != caster && (caster->IsControlledByPlayer() || !IsPositive()) && unitTarget->GetTypeId() == TYPEID_PLAYER)
     {
         if (!unitTarget->ToPlayer()->IsVisible())
             return SPELL_FAILED_BM_OR_INVISGOD;
         if (unitTarget->ToPlayer()->IsGameMaster())
             return SPELL_FAILED_BM_OR_INVISGOD;
     }
     // not allow casting on flying player
     if (unitTarget->IsInFlight() && !HasAttribute(SPELL_ATTR0_CU_ALLOW_INFLIGHT_TARGET))
         return SPELL_FAILED_BAD_TARGETS;
     /* TARGET_UNIT_MASTER gets blocked here for passengers, because the whole idea of this check is to
     not allow passengers to be implicitly hit by spells, however this target type should be an exception,
     if this is left it kills spells that award kill credit from vehicle to master (few spells),
     the use of these 2 covers passenger target check, logically, if vehicle cast this to master it should always hit
     him, because it would be it's passenger, there's no such case where this gets to fail legitimacy, this problem
     cannot be solved from within the check in other way since target type cannot be called for the spell currently
     Spell examples: [ID - 52864 Devour Water, ID - 52862 Devour Wind, ID - 49370 Wyrmrest Defender: Destabilize Azure Dragonshrine Effect] */
     if (!caster->IsVehicle() && caster->GetCharmerOrOwner() != target)
     {
         if (TargetAuraState && !unitTarget->HasAuraState(AuraStateType(TargetAuraState), this, caster))
             return SPELL_FAILED_TARGET_AURASTATE;
         if (TargetAuraStateNot && unitTarget->HasAuraState(AuraStateType(TargetAuraStateNot), this, caster))
             return SPELL_FAILED_TARGET_AURASTATE;
     }
     if (TargetAuraSpell && !unitTarget->HasAura(sSpellMgr->GetSpellIdForDifficulty(TargetAuraSpell, caster)))
         return SPELL_FAILED_TARGET_AURASTATE;
     if (ExcludeTargetAuraSpell && unitTarget->HasAura(sSpellMgr->GetSpellIdForDifficulty(ExcludeTargetAuraSpell, caster)))
         return SPELL_FAILED_TARGET_AURASTATE;
     if (unitTarget->HasAuraType(SPELL_AURA_PREVENT_RESURRECTION) && !HasAttribute(SPELL_ATTR7_BYPASS_NO_RESURRECTION_AURA))
         if (HasEffect(SPELL_EFFECT_SELF_RESURRECT) || HasEffect(SPELL_EFFECT_RESURRECT) || HasEffect(SPELL_EFFECT_RESURRECT_NEW))
             return SPELL_FAILED_TARGET_CANNOT_BE_RESURRECTED;
     // xinef: check if stronger aura is active
     if (IsStrongerAuraActive(caster, unitTarget))
         return SPELL_FAILED_AURA_BOUNCED;
     return SPELL_CAST_OK;
 }
References AttributesCu, AttributesEx, AttributesEx2, AttributesEx3, AttributesEx6, BASE_ATTACK, Unit::CanFreeMove(), WorldObject::CanSeeOrDetect(), CheckTargetCreatureType(), CORPSE_BONES, CREATURE_TYPEMASK_HUMANOID_OR_UNDEAD, ExcludeTargetAuraSpell, ObjectAccessor::FindPlayer(), Unit::GetCharmerOrOwner(), Unit::GetCreatureTypeMask(), Object::GetTypeId(), Object::GetUInt32Value(), Player::GetWeaponForAttack(), HasAttribute(), Unit::HasAura(), Unit::HasAuraState(), Unit::HasAuraType(), HasEffect(), Unit::IsAlive(), IsAllowingDeadTarget(), Unit::IsControlledByPlayer(), IsDeathPersistent(), Player::IsGameMaster(), Unit::IsInCombat(), Unit::IsInFlight(), Unit::IsPetInCombat(), IsPositive(), IsRequiringDeadTarget(), IsStrongerAuraActive(), Unit::IsVehicle(), Unit::IsVisible(), Mechanic, MECHANIC_DISARM, SPELL_ATTR0_CU_ALLOW_INFLIGHT_TARGET, SPELL_ATTR0_CU_PICKPOCKET, SPELL_ATTR1_EXCLUDE_CASTER, SPELL_ATTR1_ONLY_PEACEFUL_TARGETS, SPELL_ATTR2_CANNOT_CAST_ON_TAPPED, SPELL_ATTR3_ONLY_ON_GHOSTS, SPELL_ATTR3_ONLY_ON_PLAYER, SPELL_ATTR6_DO_NOT_CHAIN_TO_CROWD_CONTROLLED_TARGETS, SPELL_ATTR6_IGNORE_PHASE_SHIFT, SPELL_ATTR7_BYPASS_NO_RESURRECTION_AURA, SPELL_AURA_GHOST, SPELL_AURA_PREVENT_RESURRECTION, SPELL_CAST_OK, SPELL_EFFECT_RESURRECT, SPELL_EFFECT_RESURRECT_NEW, SPELL_EFFECT_SELF_RESURRECT, SPELL_FAILED_AURA_BOUNCED, SPELL_FAILED_BAD_TARGETS, SPELL_FAILED_BM_OR_INVISGOD, SPELL_FAILED_CANT_CAST_ON_TAPPED, SPELL_FAILED_TARGET_AFFECTING_COMBAT, SPELL_FAILED_TARGET_AURASTATE, SPELL_FAILED_TARGET_CANNOT_BE_RESURRECTED, SPELL_FAILED_TARGET_IS_PLAYER, SPELL_FAILED_TARGET_NO_POCKETS, SPELL_FAILED_TARGET_NO_WEAPONS, SPELL_FAILED_TARGET_NOT_GHOST, SPELL_FAILED_TARGET_NOT_PLAYER, SPELL_FAILED_TARGETS_DEAD, sSpellMgr, TargetAuraSpell, TargetAuraState, TargetAuraStateNot, Object::ToCorpse(), Object::ToCreature(), Object::ToPlayer(), Object::ToUnit(), TYPEID_PLAYER, and UNIT_VIRTUAL_ITEM_SLOT_ID.
Referenced by Spell::AddUnitTarget(), Spell::CheckCast(), Unit::GetMeleeHitRedirectTarget(), SpellTargetSelector::operator()(), and Acore::WorldObjectSpellTargetCheck::operator()().
CheckTargetCreatureType()
bool SpellInfo::CheckTargetCreatureType (Unit const * target) const
Definition at line 1916 of file SpellInfo.cpp.
 {
     // Curse of Doom & Exorcism: not find another way to fix spell target check :/
     if (SpellFamilyName == SPELLFAMILY_WARLOCK && GetCategory() == 1179)
     {
         // not allow cast at player
         if (target->GetTypeId() == TYPEID_PLAYER)
             return false;
         else
             return true;
     }
     uint32 creatureType = target->GetCreatureTypeMask();
     return !TargetCreatureType || !creatureType || (creatureType & TargetCreatureType);
 }
References GetCategory(), Unit::GetCreatureTypeMask(), Object::GetTypeId(), SPELLFAMILY_WARLOCK, SpellFamilyName, TargetCreatureType, and TYPEID_PLAYER.
Referenced by CheckTarget().
ComputeIsCritCapable()
bool SpellInfo::ComputeIsCritCapable () const
Definition at line 1138 of file SpellInfo.cpp.
 {
     for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
     {
         switch (Effects[i].Effect)
         {
             case SPELL_EFFECT_SCHOOL_DAMAGE:
             case SPELL_EFFECT_HEALTH_LEECH:
             case SPELL_EFFECT_HEAL:
             case SPELL_EFFECT_WEAPON_DAMAGE_NOSCHOOL:
             case SPELL_EFFECT_WEAPON_PERCENT_DAMAGE:
             case SPELL_EFFECT_WEAPON_DAMAGE:
             case SPELL_EFFECT_POWER_BURN:
             case SPELL_EFFECT_HEAL_MECHANICAL:
             case SPELL_EFFECT_NORMALIZED_WEAPON_DMG:
             case SPELL_EFFECT_HEAL_PCT:
                 return true;
         }
     }
     return false;
 }
References Effects, MAX_SPELL_EFFECTS, SPELL_EFFECT_HEAL, SPELL_EFFECT_HEAL_MECHANICAL, SPELL_EFFECT_HEAL_PCT, SPELL_EFFECT_HEALTH_LEECH, SPELL_EFFECT_NORMALIZED_WEAPON_DMG, SPELL_EFFECT_POWER_BURN, SPELL_EFFECT_SCHOOL_DAMAGE, SPELL_EFFECT_WEAPON_DAMAGE, SPELL_EFFECT_WEAPON_DAMAGE_NOSCHOOL, and SPELL_EFFECT_WEAPON_PERCENT_DAMAGE.
ComputeIsStackableWithRanks()
bool SpellInfo::ComputeIsStackableWithRanks () const
Definition at line 1095 of file SpellInfo.cpp.
 {
     if (IsPassive())
         return false;
     if (PowerType != POWER_MANA && PowerType != POWER_HEALTH)
         return false;
     if (IsProfessionOrRiding())
         return false;
     if (IsAbilityLearnedWithProfession())
         return false;
     // All stance spells. if any better way, change it.
     for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
     {
         switch (SpellFamilyName)
         {
             case SPELLFAMILY_PALADIN:
                 // Paladin aura Spell
                 if (Effects[i].Effect == SPELL_EFFECT_APPLY_AREA_AURA_RAID)
                     return false;
                 break;
             case SPELLFAMILY_DRUID:
                 // Druid form Spell
                 if (Effects[i].Effect == SPELL_EFFECT_APPLY_AURA &&
                         Effects[i].ApplyAuraName == SPELL_AURA_MOD_SHAPESHIFT)
                     return false;
                 break;
         }
     }
     return true;
 }
References Effects, IsAbilityLearnedWithProfession(), IsPassive(), IsProfessionOrRiding(), MAX_SPELL_EFFECTS, POWER_HEALTH, POWER_MANA, SPELL_AURA_MOD_SHAPESHIFT, SPELL_EFFECT_APPLY_AREA_AURA_RAID, SPELL_EFFECT_APPLY_AURA, SPELLFAMILY_DRUID, SPELLFAMILY_PALADIN, and SpellFamilyName.
GetAllEffectsMechanicMask()
uint32 SpellInfo::GetAllEffectsMechanicMask () const
Definition at line 1936 of file SpellInfo.cpp.
 {
     uint32 mask = 0;
     if (Mechanic)
         mask |= 1 << Mechanic;
     for (int i = 0; i < MAX_SPELL_EFFECTS; ++i)
         if (Effects[i].IsEffect() && Effects[i].Mechanic)
             mask |= 1 << Effects[i].Mechanic;
     return mask;
 }
References Effects, MAX_SPELL_EFFECTS, and Mechanic.
Referenced by Spell::CheckCasterAuras(), spell_mage_burning_determination::CheckProc(), Spell::EffectDispelMechanic(), Spell::EffectTriggerSpell(), GetDiminishingReturnsGroupForSpell(), Unit::HandleDummyAuraProc(), Unit::HandleProcTriggerSpell(), LoadAuraState(), Unit::MeleeDamageBonusTaken(), Unit::RemoveAurasByShapeShift(), Unit::RemoveAurasWithMechanic(), and Unit::SpellDamageBonusTaken().
GetAuraRankForLevel()
SpellInfo const * SpellInfo::GetAuraRankForLevel (uint8 level) const
Definition at line 2467 of file SpellInfo.cpp.
 {
     // ignore passive spells
     //if (IsPassive())
     //    return this;
     bool needRankSelection = false;
     for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
     {
         if (IsPositiveEffect(i) &&
                 (Effects[i].Effect == SPELL_EFFECT_APPLY_AURA ||
                  Effects[i].Effect == SPELL_EFFECT_APPLY_AREA_AURA_PARTY ||
                  Effects[i].Effect == SPELL_EFFECT_APPLY_AREA_AURA_RAID))
         {
             needRankSelection = true;
             break;
         }
     }
     // not required
     if (!needRankSelection)
         return this;
     SpellInfo const* nextSpellInfo = nullptr;
     sScriptMgr->OnBeforeAuraRankForLevel(this, nextSpellInfo, level);
     if (nextSpellInfo != nullptr)
         return nextSpellInfo;
     for (nextSpellInfo = this; nextSpellInfo != nullptr; nextSpellInfo = nextSpellInfo->GetPrevRankSpell())
     {
         // if found appropriate level
         if (uint32(level + 10) >= nextSpellInfo->SpellLevel)
             return nextSpellInfo;
         // one rank less then
     }
     // not found
     return nullptr;
 }
References Effects, GetPrevRankSpell(), IsPositiveEffect(), MAX_SPELL_EFFECTS, SPELL_EFFECT_APPLY_AREA_AURA_PARTY, SPELL_EFFECT_APPLY_AREA_AURA_RAID, SPELL_EFFECT_APPLY_AURA, SpellLevel, and sScriptMgr.
Referenced by Pet::_LoadAuras(), Spell::DoSpellHitOnUnit(), and WorldSession::HandleCastSpellOpcode().
GetAuraState()
AuraStateType SpellInfo::GetAuraState () const
Definition at line 2004 of file SpellInfo.cpp.
 {
     return _auraState;
 }
References _auraState.
Referenced by Unit::_ApplyAura(), Unit::_CreateAuraApplication(), and Unit::_UnapplyAura().
GetCategory()
uint32 SpellInfo::GetCategory () const
Definition at line 863 of file SpellInfo.cpp.
 {
     return CategoryEntry ? CategoryEntry->Id : 0;
 }
References CategoryEntry, and SpellCategoryEntry::Id.
Referenced by Player::AddSpellAndCategoryCooldowns(), Creature::AddSpellCooldown(), CheckTargetCreatureType(), Spell::EffectDispel(), Spell::EffectSchoolDMG(), Spell::EffectTriggerMissileSpell(), Spell::EffectTriggerSpell(), WorldSession::HandleItemQuerySingleOpcode(), ItemTemplate::InitializeQueryData(), Unit::IsTriggeredAtSpellProcEvent(), LoadAuraState(), SpellMgr::LoadSpellCustomAttr(), Acore::AbsorbAuraOrderPred::operator()(), and Unit::SpellTakenCritChance().
GetDispelMask() [1/2]
uint32 SpellInfo::GetDispelMask () const
Definition at line 1985 of file SpellInfo.cpp.
 {
     return GetDispelMask(DispelType(Dispel));
 }
References Dispel.
Referenced by Unit::ApplySpellDispelImmunity(), Spell::CheckCast(), Spell::CheckCasterAuras(), Spell::EffectDispel(), Spell::EffectStealBeneficialBuff(), Spell::EffectTriggerSpell(), and Unit::GetDispellableAuraList().
GetDispelMask() [2/2]
uint32 SpellInfo::GetDispelMask (DispelType type) static
Definition at line 1990 of file SpellInfo.cpp.
 {
     // If dispel all
     if (type == DISPEL_ALL)
         return DISPEL_ALL_MASK;
     else
         return uint32(1 << type);
 }
References DISPEL_ALL, and DISPEL_ALL_MASK.
GetDuration()
int32 SpellInfo::GetDuration () const
Definition at line 2280 of file SpellInfo.cpp.
 {
     if (!DurationEntry)
         return 0;
     return (DurationEntry->Duration[0] == -1) ? -1 : abs(DurationEntry->Duration[0]);
 }
References abs(), SpellDurationEntry::Duration, and DurationEntry.
Referenced by Aura::CalcMaxDuration(), Unit::CalcSpellDuration(), Unit::CalculateDefaultCoefficient(), AuraEffect::CleanupTriggeredSpells(), Spell::DelayedChannel(), Spell::EffectAddFarsight(), Spell::EffectDuel(), Spell::EffectEnchantHeldItem(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectSummonPet(), Spell::EffectSummonType(), Spell::EffectTransmitted(), UnitAI::FillAISpellInfo(), Unit::GetCastingTimeForBonus(), GetMaxTicks(), Spell::handle_immediate(), WorldSession::HandleLoadPetFromDBFirstCallback(), WorldSession::HandleLoadPetFromDBSecondCallback(), spell_wintergrasp_create_vehicle::spell_wintergrasp_create_vehicle_SpellScript::HandleSummon(), Player::IsAffectedBySpellmod(), Spell::SummonGuardian(), and Pet::TryLoadFromDB().
GetEffectMechanic()
Mechanics SpellInfo::GetEffectMechanic (uint8 effIndex) const
Definition at line 1968 of file SpellInfo.cpp.
 {
     if (Effects[effIndex].IsEffect() && Effects[effIndex].Mechanic)
         return Mechanics(Effects[effIndex].Mechanic);
     if (Mechanic)
         return Mechanics(Mechanic);
     return MECHANIC_NONE;
 }
References Effects, Mechanic, and MECHANIC_NONE.
Referenced by Unit::GetMechanicResistChance().
GetEffectMechanicMask()
uint32 SpellInfo::GetEffectMechanicMask (uint8 effIndex) const
Definition at line 1947 of file SpellInfo.cpp.
 {
     uint32 mask = 0;
     if (Mechanic)
         mask |= 1 << Mechanic;
     if (Effects[effIndex].IsEffect() && Effects[effIndex].Mechanic)
         mask |= 1 << Effects[effIndex].Mechanic;
     return mask;
 }
References Effects, and Mechanic.
Referenced by Unit::IsDamageReducedByArmor().
GetExplicitTargetMask()
uint32 SpellInfo::GetExplicitTargetMask () const
Definition at line 1999 of file SpellInfo.cpp.
 {
     return ExplicitTargetMask;
 }
References ExplicitTargetMask.
Referenced by Spell::CheckCast(), CheckExplicitTarget(), Spell::EffectTriggerMissileSpell(), Spell::EffectTriggerSpell(), Spell::InitExplicitTargets(), NeedsExplicitUnitTarget(), and Spell::SelectExplicitTargets().
GetFirstRankSpell()
SpellInfo const * SpellInfo::GetFirstRankSpell () const
Definition at line 2442 of file SpellInfo.cpp.
 {
     if (!ChainEntry)
         return this;
     return ChainEntry->first;
 }
References ChainEntry, and SpellChainNode::first.
Referenced by CharmInfo::AddSpellToActionBar(), Spell::AddUnitTarget(), SpellMgr::CheckSpellGroupStackRules(), Acore::PlayerCommand::HandleLearnSpellCommand(), IsRankOf(), SpellMgr::LoadSpellProcEvents(), SpellMgr::LoadSpellProcs(), and LoadSpellSpecific().
GetLastRankSpell()
SpellInfo const * SpellInfo::GetLastRankSpell () const
Definition at line 2448 of file SpellInfo.cpp.
 {
     if (!ChainEntry)
         return nullptr;
     return ChainEntry->last;
 }
References ChainEntry, and SpellChainNode::last.
GetMaxDuration()
int32 SpellInfo::GetMaxDuration () const
Definition at line 2287 of file SpellInfo.cpp.
 {
     if (!DurationEntry)
         return 0;
     return (DurationEntry->Duration[2] == -1) ? -1 : abs(DurationEntry->Duration[2]);
 }
References abs(), SpellDurationEntry::Duration, and DurationEntry.
Referenced by Unit::CalcSpellDuration(), Unit::HandleDummyAuraProc(), Unit::HandleProcTriggerSpell(), spell_dru_glyph_of_starfire::HandleScriptEffect(), IsStrongerAuraActive(), Spell::prepare(), Aura::RefreshDuration(), and PetAI::UpdateAI().
GetMaxRange()
float SpellInfo::GetMaxRange (bool positive = false, Unit * caster = nullptr, Spell * spell = nullptr) const
Definition at line 2265 of file SpellInfo.cpp.
 {
     if (!RangeEntry)
         return 0.0f;
     float range;
     if (positive)
         range = RangeEntry->maxRangeFriend;
     else
         range = RangeEntry->maxRangeHostile;
     if (caster)
         if (Player* modOwner = caster->GetSpellModOwner())
             modOwner->ApplySpellMod(Id, SPELLMOD_RANGE, range, spell);
     return range;
 }
References Unit::GetSpellModOwner(), Id, SpellRangeEntry::maxRangeFriend, SpellRangeEntry::maxRangeHostile, RangeEntry, and SPELLMOD_RANGE.
Referenced by PetAI::_canMeleeAttack(), _InitializeExplicitTargetMask(), ArcherAI::ArcherAI(), Unit::CalcAbsorbResist(), spell_gen_cannibalize::CheckIfCorpseNear(), spell_hun_pet_carrion_feeder::CheckIfCorpseNear(), UnitAI::DoCast(), UnitAI::DoGetSpellMaxRange(), Spell::EffectTransmitted(), UnitAI::FillAISpellInfo(), Unit::GetSpellMaxRangeForTarget(), spell_warl_demonic_circle_summon::HandleDummyTick(), AuraEffect::HandleFarSight(), GameObject::IsAtInteractDistance(), SmartScript::OnInitialize(), Creature::reachWithSpellAttack(), Creature::reachWithSpellCure(), Spell::SelectImplicitCasterDestTargets(), Spell::SelectImplicitNearbyTargets(), Spell::SelectImplicitTrajTargets(), TurretAI::TurretAI(), TotemAI::UpdateAI(), and Spell::UpdateChanneledTargetList().
GetMaxTicks()
uint32 SpellInfo::GetMaxTicks () const
Definition at line 2310 of file SpellInfo.cpp.
 {
     int32 DotDuration = GetDuration();
     if (DotDuration == 0)
         return 1;
     // 200% limit
     if (DotDuration > 30000)
         DotDuration = 30000;
     for (uint8 x = 0; x < MAX_SPELL_EFFECTS; x++)
     {
         if (Effects[x].Effect == SPELL_EFFECT_APPLY_AURA)
             switch (Effects[x].ApplyAuraName)
             {
                 case SPELL_AURA_PERIODIC_DAMAGE:
                 case SPELL_AURA_PERIODIC_HEAL:
                 case SPELL_AURA_PERIODIC_LEECH:
                     if (Effects[x].Amplitude != 0)
                         return DotDuration / Effects[x].Amplitude;
                     break;
             }
     }
     return 6;
 }
References Effects, GetDuration(), MAX_SPELL_EFFECTS, SPELL_AURA_PERIODIC_DAMAGE, SPELL_AURA_PERIODIC_HEAL, SPELL_AURA_PERIODIC_LEECH, SPELL_EFFECT_APPLY_AURA, and G3D::x.
Referenced by Unit::CalculateDefaultCoefficient(), spell_mage_ignite::HandleProc(), spell_dru_t10_balance_4p_bonus::HandleProc(), spell_pri_glyph_of_prayer_of_healing::HandleProc(), and spell_sha_t10_restoration_4p_bonus::HandleProc().
GetMinRange()
float SpellInfo::GetMinRange (bool positive = false) const
Definition at line 2256 of file SpellInfo.cpp.
 {
     if (!RangeEntry)
         return 0.0f;
     if (positive)
         return RangeEntry->minRangeFriend;
     return RangeEntry->minRangeHostile;
 }
References SpellRangeEntry::minRangeFriend, SpellRangeEntry::minRangeHostile, and RangeEntry.
Referenced by ArcherAI::ArcherAI(), Spell::EffectTransmitted(), Unit::GetSpellMinRangeForTarget(), SmartScript::OnInitialize(), Creature::reachWithSpellAttack(), Creature::reachWithSpellCure(), Spell::SelectImplicitCasterDestTargets(), and TurretAI::TurretAI().
GetNextRankSpell()
SpellInfo const * SpellInfo::GetNextRankSpell () const
Definition at line 2454 of file SpellInfo.cpp.
 {
     if (!ChainEntry)
         return nullptr;
     return ChainEntry->next;
 }
References ChainEntry, and SpellChainNode::next.
Referenced by Player::addSpell(), SpellMgr::LoadSpellProcEvents(), SpellMgr::LoadSpellProcs(), and ObjectMgr::LoadSpellScriptNames().
GetPrevRankSpell()
SpellInfo const * SpellInfo::GetPrevRankSpell () const
Definition at line 2460 of file SpellInfo.cpp.
 {
     if (!ChainEntry)
         return nullptr;
     return ChainEntry->prev;
 }
References ChainEntry, and SpellChainNode::prev.
Referenced by GetAuraRankForLevel().
GetRank()
uint8 SpellInfo::GetRank () const
Definition at line 2435 of file SpellInfo.cpp.
 {
     if (!ChainEntry)
         return 1;
     return ChainEntry->rank;
 }
References ChainEntry, and SpellChainNode::rank.
Referenced by spell_dk_will_of_the_necropolis::Absorb(), Player::addSpell(), spell_warl_create_healthstone::CheckCast(), spell_pal_holy_shock::HandleDummy(), spell_pri_penance::HandleDummy(), spell_sha_fire_nova::HandleDummy(), Unit::HandleDummyAuraProc(), lookup_commandscript::HandleLookupSpellCommand(), lookup_commandscript::HandleLookupSpellIdCommand(), spell_mage_ignite::HandleProc(), Unit::HandleProcTriggerSpell(), spell_warl_create_healthstone::HandleScriptEffect(), IsPrimaryProfessionFirstRank(), SpellMgr::LoadSpellGroups(), spell_dk_will_of_the_necropolis::Validate(), spell_pal_holy_shock::Validate(), spell_pri_penance::Validate(), and spell_sha_fire_nova::Validate().
GetRecoveryTime()
uint32 SpellInfo::GetRecoveryTime () const
Definition at line 2337 of file SpellInfo.cpp.
 {
     return RecoveryTime > CategoryRecoveryTime ? RecoveryTime : CategoryRecoveryTime;
 }
References CategoryRecoveryTime, and RecoveryTime.
Referenced by Spell::CheckCast(), spell_hun_readiness::HandleDummy(), and spell_mage_cold_snap::HandleDummy().
GetSchoolMask()
SpellSchoolMask SpellInfo::GetSchoolMask () const
Definition at line 1931 of file SpellInfo.cpp.
 {
     return SpellSchoolMask(SchoolMask);
 }
References SchoolMask.
Referenced by PetAI::_canMeleeAttack(), Unit::CalcArmorReducedDamage(), spell_pal_sacred_shield_base::CalculateAmount(), spell_mage_ice_barrier_aura::CalculateSpellAmount(), spell_mage_ice_barrier::CalculateSpellAmount(), CalculateSpellAmount(), Unit::CalculateSpellDamageTaken(), Spell::CheckCast(), Spell::CheckCasterAuras(), spell_hun_lock_and_load::CheckTrapProc(), Unit::DealMeleeDamage(), Spell::DoAllEffectOnTarget(), Spell::EffectCastButtons(), Spell::EffectEnvironmentalDMG(), Spell::EffectInterruptCast(), Spell::EffectWeaponDmg(), AuraEffect::HandleAuraModSchoolImmunity(), spell_mage_cold_snap::HandleDummy(), Unit::HandleDummyAuraProc(), AuraEffect::HandlePeriodicTriggerSpellAuraTick(), spell_hun_glyph_of_arcane_shot::HandleProc(), spell_hun_lock_and_load::HandleProcs(), Unit::HandleProcTriggerSpell(), Spell::HandleThreatSpells(), Unit::IsImmunedToDamage(), Unit::IsImmunedToSchool(), Unit::IsImmunedToSpell(), Unit::IsImmunedToSpellEffect(), spell_hun_lock_and_load::IsTargetValid(), LoadAuraState(), Unit::MagicSpellHitResult(), Unit::MeleeDamageBonusDone(), Unit::MeleeDamageBonusTaken(), SmartScript::ProcessAction(), Player::ProhibitSpellSchool(), Unit::SendPeriodicAuraLog(), Spell::Spell(), Unit::SpellCriticalDamageBonus(), Unit::SpellDamageBonusDone(), Unit::SpellDamageBonusTaken(), Unit::SpellHealingBonusDone(), Unit::SpellHealingBonusTaken(), boss_viscidus::boss_viscidusAI::SpellHit(), Unit::SpellHitResult(), Unit::SpellPctDamageModsDone(), and HostileRefMgr::threatAssist().
GetSpellMechanicMaskByEffectMask()
uint32 SpellInfo::GetSpellMechanicMaskByEffectMask (uint32 effectMask) const
Definition at line 1957 of file SpellInfo.cpp.
 {
     uint32 mask = 0;
     if (Mechanic)
         mask |= 1 << Mechanic;
     for (int i = 0; i < MAX_SPELL_EFFECTS; ++i)
         if ((effectMask & (1 << i)) && Effects[i].Mechanic)
             mask |= 1 << Effects[i].Mechanic;
     return mask;
 }
References Effects, MAX_SPELL_EFFECTS, and Mechanic.
Referenced by Unit::ModSpellDuration().
GetSpellSpecific()
SpellSpecificType SpellInfo::GetSpellSpecific () const
Definition at line 2079 of file SpellInfo.cpp.
 {
     return _spellSpecific;
 }
References _spellSpecific.
Referenced by IsAuraExclusiveBySpecificPerCasterWith(), IsAuraExclusiveBySpecificWith(), Unit::IsPolymorphed(), IsSingleTarget(), Aura::IsSingleTargetWith(), and LoadAuraState().
HasAnyAura()
bool SpellInfo::HasAnyAura () const
Definition at line 884 of file SpellInfo.cpp.
 {
     for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
         if (Effects[i].IsAura())
             return true;
     return false;
 }
References Effects, and MAX_SPELL_EFFECTS.
Referenced by Player::_addSpell(), and Player::removeSpell().
HasAnyEffectMechanic()
bool SpellInfo::HasAnyEffectMechanic () const
Definition at line 1977 of file SpellInfo.cpp.
 {
     for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
         if (Effects[i].Mechanic)
             return true;
     return false;
 }
References Effects, MAX_SPELL_EFFECTS, and Mechanic.
HasAreaAuraEffect()
bool SpellInfo::HasAreaAuraEffect () const
Definition at line 892 of file SpellInfo.cpp.
 {
     for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
         if (Effects[i].IsAreaAuraEffect())
             return true;
     return false;
 }
References Effects, and MAX_SPELL_EFFECTS.
Referenced by AuraApplication::_HandleEffect(), AuraScript::_Validate(), and Aura::CanBeSentToClient().
HasAttribute() [1/9]
bool SpellInfo::HasAttribute (SpellAttr0 attribute) const inline
Definition at line 408 of file SpellInfo.h.
 { return (Attributes & attribute) != 0; }
References Attributes.
Referenced by Player::_addSpell(), Player::_addTalentAurasAndSpells(), Spell::_cast(), _IsPositiveEffect(), Unit::_IsValidAssistTarget(), Unit::_IsValidAttackTarget(), Player::_LoadAuras(), Pet::_SaveAuras(), Unit::_TryStackingOrRefreshingExistingAura(), Unit::AddAura(), Player::AddSpellAndCategoryCooldowns(), Player::addTalent(), Player::ApplyEquipCooldown(), Unit::ApplySpellDispelImmunity(), Aura::Aura(), AuraApplication::BuildUpdatePacket(), Unit::CalcAbsorbResist(), CalcCastTime(), CalcPowerCost(), AuraEffect::CalculatePeriodic(), SpellEffectInfo::CalcValue(), PetAI::CanAttack(), Aura::CanBeSaved(), CanBeUsedInCombat(), CanDispelAura(), Spell::CanExecuteTriggersOnHit(), Player::canFlyInZone(), Player::CanNoReagentCast(), CanPierceImmuneAura(), Aura::CanStackWith(), Spell::CheckCast(), Spell::CheckCasterAuras(), Spell::CheckEffectTarget(), Spell::CheckItems(), CheckLocation(), spell_dru_omen_of_clarity::CheckProc(), CheckShapeshift(), CheckTarget(), createProcFlags(), Unit::DealDamage(), Spell::DoAllEffectOnTarget(), UnitAI::DoCast(), Spell::DoSpellHitOnUnit(), Spell::EffectCastButtons(), Spell::EffectEnergize(), Spell::EffectEnergizePct(), Spell::EffectForceDeselect(), Spell::EffectSanctuary(), Spell::EffectSchoolDMG(), Spell::EffectStealBeneficialBuff(), Spell::EffectTriggerSpell(), Spell::EffectWeaponDmg(), UnitAI::FillAISpellInfo(), Spell::finish(), Creature::FocusTarget(), Unit::GetDispellableAuraList(), Unit::GetMagicHitRedirectTarget(), Spell::GetSearcherTypeMask(), Spell::handle_immediate(), WorldSession::HandleCancelAuraOpcode(), AuraEffect::HandleFeignDeath(), Spell::HandleLaunchPhase(), AuraEffect::HandleModStateImmunityMask(), AuraEffect::HandleModTotalPercentStat(), AuraEffect::HandlePeriodicEnergizeAuraTick(), WorldSession::HandlePetAction(), AuraEffect::HandleShapeshiftBoosts(), Spell::HandleThreatSpells(), Spell::IsAutoActionResetSpell(), IsAutocastable(), IsCooldownStartedOnEvent(), Unit::IsDamageReducedByArmor(), Unit::IsImmunedToDamage(), Unit::IsImmunedToSchool(), Unit::IsImmunedToSpell(), Unit::IsImmunedToSpellEffect(), IsMoveAllowedChannel(), Player::IsNeedCastPassiveSpellAtLearn(), Spell::IsNextMeleeSwingSpell(), IsPassive(), Aura::IsProcTriggeredOnEvent(), IsRangedWeaponSpell(), Aura::IsRemovedOnShapeLost(), Unit::isSpellBlocked(), Unit::IsTriggeredAtSpellProcEvent(), ThreatCalcHelper::isValidProcess(), Player::LearnTalent(), SpellMgr::LoadEnchantCustomAttr(), LoadLootTemplates_Spell(), SpellMgr::LoadSpellCustomAttr(), Unit::MagicSpellHitResult(), Unit::MeleeDamageBonusDone(), Unit::MeleeDamageBonusTaken(), Unit::MeleeSpellHitResult(), Unit::MeleeSpellMissChance(), Unit::ModSpellDuration(), Aura::ModStackAmount(), Acore::WorldObjectSpellConeTargetCheck::operator()(), Player::PrepareCharmAISpells(), Spell::prepareDataForTriggerSystem(), Aura::PrepareProcToTrigger(), Unit::ProcDamageAndSpellFor(), Aura::RefreshDuration(), Creature::ReleaseFocus(), Unit::RemoveAllAurasOnDeath(), Unit::RemoveArenaAuras(), Player::RemoveArenaSpellCooldowns(), Unit::RemoveAurasByShapeShift(), Unit::RemoveAurasDueToSpellByDispel(), Unit::RemoveAurasDueToSpellBySteal(), Player::removeSpell(), Player::resetTalents(), Player::RestoreBaseRune(), Spell::SearchChainTargets(), Spell::SendResurrectRequest(), Spell::SendSpellGo(), Spell::SendSpellStart(), ArenaSpectator::ShouldSendAura(), Spell::Spell(), Unit::SpellDamageBonusDone(), Unit::SpellDamageBonusTaken(), Unit::SpellDoneCritChance(), Unit::SpellPctDamageModsDone(), Unit::SpellPctHealingModsDone(), Unit::SpellTakenCritChance(), Acore::Hyperlinks::LinkTags::enchant::StoreTo(), and Spell::UpdateChanneledTargetList().
HasAttribute() [2/9]
bool SpellInfo::HasAttribute (SpellAttr1 attribute) const inline
Definition at line 409 of file SpellInfo.h.
 { return (AttributesEx & attribute) != 0; }
References AttributesEx.
HasAttribute() [3/9]
bool SpellInfo::HasAttribute (SpellAttr2 attribute) const inline
Definition at line 410 of file SpellInfo.h.
 { return (AttributesEx2 & attribute) != 0; }
References AttributesEx2.
HasAttribute() [4/9]
bool SpellInfo::HasAttribute (SpellAttr3 attribute) const inline
Definition at line 411 of file SpellInfo.h.
 { return (AttributesEx3 & attribute) != 0; }
References AttributesEx3.
HasAttribute() [5/9]
bool SpellInfo::HasAttribute (SpellAttr4 attribute) const inline
Definition at line 412 of file SpellInfo.h.
 { return (AttributesEx4 & attribute) != 0; }
References AttributesEx4.
HasAttribute() [6/9]
bool SpellInfo::HasAttribute (SpellAttr5 attribute) const inline
Definition at line 413 of file SpellInfo.h.
 { return (AttributesEx5 & attribute) != 0; }
References AttributesEx5.
HasAttribute() [7/9]
bool SpellInfo::HasAttribute (SpellAttr6 attribute) const inline
Definition at line 414 of file SpellInfo.h.
 { return (AttributesEx6 & attribute) != 0; }
References AttributesEx6.
HasAttribute() [8/9]
bool SpellInfo::HasAttribute (SpellAttr7 attribute) const inline
Definition at line 415 of file SpellInfo.h.
 { return (AttributesEx7 & attribute) != 0; }
References AttributesEx7.
HasAttribute() [9/9]
bool SpellInfo::HasAttribute (SpellCustomAttributes customAttribute) const inline
Definition at line 416 of file SpellInfo.h.
 { return (AttributesCu & customAttribute) != 0; }
References AttributesCu.
HasAura()
bool SpellInfo::HasAura (AuraType aura) const
Definition at line 876 of file SpellInfo.cpp.
 {
     for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
         if (Effects[i].IsAura(aura))
             return true;
     return false;
 }
References Effects, and MAX_SPELL_EFFECTS.
Referenced by Spell::_cast(), Player::_LoadAuras(), Pet::_SaveAuras(), AuraEffect::CalculateAmount(), AuraEffect::CalculatePeriodicData(), Spell::CheckCast(), Unit::DealDamage(), Spell::EffectSummonType(), Spell::EffectTaunt(), Unit::HandleSpellClick(), Unit::IsImmunedToSpell(), SpellMgr::LoadSpellCustomAttr(), Unit::ModSpellCastTime(), Unit::ProcDamageAndSpellFor(), Unit::RemoveAllAurasExceptType(), Unit::RemoveEvadeAuras(), PetAI::SpellHit(), and Unit::SpellHitResult().
HasEffect()
bool SpellInfo::HasEffect (SpellEffects effect) const
Definition at line 868 of file SpellInfo.cpp.
 {
     for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
         if (Effects[i].IsEffect(effect))
             return true;
     return false;
 }
References Effects, and MAX_SPELL_EFFECTS.
Referenced by Player::_addSpell(), Player::_addTalentAurasAndSpells(), Spell::_cast(), AuraScript::_Validate(), Player::addTalent(), Player::CastItemCombatSpell(), Spell::CheckCast(), spell_dk_dancing_rune_weapon::CheckProc(), spell_gen_allow_proc_from_spells_with_cost::CheckProc(), spell_item_essence_of_life::CheckProc(), CheckTarget(), Spell::DoAllEffectOnTarget(), Unit::HandleProcTriggerSpell(), AuraEffect::HandleShapeshiftBoosts(), IsPassiveStackableWithRanks(), Player::LearnTalent(), spell_gen_mounted_charge::Register(), Player::removeSpell(), Player::resetTalents(), Player::RewardQuest(), Spell::SelectExplicitTargets(), Spell::SelectImplicitCasterDestTargets(), Spell::SendSpellGo(), Spell::Spell(), and Unit::SpellHitResult().
IsAbilityLearnedWithProfession()
bool SpellInfo::IsAbilityLearnedWithProfession () const
Definition at line 971 of file SpellInfo.cpp.
 {
     SkillLineAbilityMapBounds bounds = sSpellMgr->GetSkillLineAbilityMapBounds(Id);
     for (SkillLineAbilityMap::const_iterator _spell_idx = bounds.first; _spell_idx != bounds.second; ++_spell_idx)
     {
         SkillLineAbilityEntry const* pAbility = _spell_idx->second;
         if (!pAbility || pAbility->AcquireMethod != SKILL_LINE_ABILITY_LEARNED_ON_SKILL_VALUE)
             continue;
         if (pAbility->MinSkillLineRank > 0)
             return true;
     }
     return false;
 }
References SkillLineAbilityEntry::AcquireMethod, Id, SkillLineAbilityEntry::MinSkillLineRank, SKILL_LINE_ABILITY_LEARNED_ON_SKILL_VALUE, and sSpellMgr.
Referenced by ComputeIsStackableWithRanks().
IsAbilityOfSkillType()
bool SpellInfo::IsAbilityOfSkillType (uint32 skillType) const
Definition at line 988 of file SpellInfo.cpp.
 {
     SkillLineAbilityMapBounds bounds = sSpellMgr->GetSkillLineAbilityMapBounds(Id);
     for (SkillLineAbilityMap::const_iterator _spell_idx = bounds.first; _spell_idx != bounds.second; ++_spell_idx)
         if (_spell_idx->second->SkillLine == uint32(skillType))
             return true;
     return false;
 }
References Id, and sSpellMgr.
Referenced by Spell::CanOpenLock(), learn_commandscript::HandleLearnAllGMCommand(), and Item::IsFitToSpellRequirements().
IsAffectedBySpellMod()
bool SpellInfo::IsAffectedBySpellMod (SpellModifier const * mod) const
Definition at line 1276 of file SpellInfo.cpp.
 {
     // xinef: dont check duration mod
     if (mod->op != SPELLMOD_DURATION)
         if (!IsAffectedBySpellMods())
             return false;
     SpellInfo const* affectSpell = sSpellMgr->GetSpellInfo(mod->spellId);
     // False if affect_spell == nullptr or spellFamily not equal
     if (!affectSpell || affectSpell->SpellFamilyName != SpellFamilyName)
         return false;
     // true
     if (mod->mask & SpellFamilyFlags)
         return true;
     return false;
 }
References IsAffectedBySpellMods(), mod(), SpellFamilyFlags, SpellFamilyName, SPELLMOD_DURATION, and sSpellMgr.
Referenced by AuraEffect::ApplySpellMod(), and Player::IsAffectedBySpellmod().
IsAffectedBySpellMods()
bool SpellInfo::IsAffectedBySpellMods () const
Definition at line 1271 of file SpellInfo.cpp.
 {
     return !(AttributesEx3 & SPELL_ATTR3_IGNORE_CASTER_MODIFIERS);
 }
References AttributesEx3, and SPELL_ATTR3_IGNORE_CASTER_MODIFIERS.
Referenced by IsAffectedBySpellMod().
IsAffectingArea()
bool SpellInfo::IsAffectingArea () const
Definition at line 999 of file SpellInfo.cpp.
 {
     for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
         if (Effects[i].IsEffect() && (Effects[i].IsTargetingArea() || Effects[i].IsEffect(SPELL_EFFECT_PERSISTENT_AREA_AURA) || Effects[i].IsAreaAuraEffect()))
             return true;
     return false;
 }
References Effects, IsTargetingArea(), MAX_SPELL_EFFECTS, and SPELL_EFFECT_PERSISTENT_AREA_AURA.
Referenced by Unit::_IsValidAssistTarget(), Unit::_IsValidAttackTarget(), and Unit::MagicSpellHitResult().
IsAllowingDeadTarget()
bool SpellInfo::IsAllowingDeadTarget () const
Definition at line 1210 of file SpellInfo.cpp.
 {
     return AttributesEx2 & SPELL_ATTR2_ALLOW_DEAD_TARGET || Targets & (TARGET_FLAG_CORPSE_ALLY | TARGET_FLAG_CORPSE_ENEMY | TARGET_FLAG_UNIT_DEAD);
 }
References AttributesEx2, SPELL_ATTR2_ALLOW_DEAD_TARGET, TARGET_FLAG_CORPSE_ALLY, TARGET_FLAG_CORPSE_ENEMY, and TARGET_FLAG_UNIT_DEAD.
Referenced by Unit::_CreateAuraApplication(), Unit::_IsValidAssistTarget(), Unit::_IsValidAttackTarget(), CheckTarget(), and Spell::IsValidDeadOrAliveTarget().
IsAuraEffectEqual()
bool SpellInfo::IsAuraEffectEqual (SpellInfo const * otherSpellInfo) const
Definition at line 1672 of file SpellInfo.cpp.
 {
     uint8 matchCount = 0;
     uint8 auraCount = 0;
     for (uint8 i = EFFECT_0; i < MAX_SPELL_EFFECTS; ++i)
     {
         // xinef: skip non-aura efects
         if (!Effects[i].IsAura())
             continue;
         bool effectFound = false;
         for (uint8 j = EFFECT_0; j < MAX_SPELL_EFFECTS; ++j)
         {
             if (!otherSpellInfo->Effects[j].IsAura())
                 continue;
             if (Effects[i].ApplyAuraName != otherSpellInfo->Effects[j].ApplyAuraName || Effects[i].MiscValue != otherSpellInfo->Effects[j].MiscValue)
                 continue;
             effectFound = true;
             break;
         }
         if (!effectFound)
             return false;
         ++matchCount;
     }
     for (uint8 i = EFFECT_0; i < MAX_SPELL_EFFECTS; ++i)
     {
         if (Effects[i].IsAura())
             ++auraCount;
         if (otherSpellInfo->Effects[i].IsAura())
             ++auraCount;
     }
     return matchCount * 2 == auraCount;
 }
References EFFECT_0, Effects, and MAX_SPELL_EFFECTS.
Referenced by IsStrongerAuraActive().
IsAuraExclusiveBySpecificPerCasterWith()
bool SpellInfo::IsAuraExclusiveBySpecificPerCasterWith (SpellInfo const * spellInfo) const
Definition at line 1395 of file SpellInfo.cpp.
 {
     SpellSpecificType spellSpec = GetSpellSpecific();
     switch (spellSpec)
     {
         case SPELL_SPECIFIC_SEAL:
         case SPELL_SPECIFIC_HAND:
         case SPELL_SPECIFIC_AURA:
         case SPELL_SPECIFIC_STING:
         case SPELL_SPECIFIC_CURSE:
         case SPELL_SPECIFIC_ASPECT:
         case SPELL_SPECIFIC_JUDGEMENT:
         case SPELL_SPECIFIC_WARLOCK_CORRUPTION:
             return spellSpec == spellInfo->GetSpellSpecific();
         default:
             return false;
     }
 }
References GetSpellSpecific(), SPELL_SPECIFIC_ASPECT, SPELL_SPECIFIC_AURA, SPELL_SPECIFIC_CURSE, SPELL_SPECIFIC_HAND, SPELL_SPECIFIC_JUDGEMENT, SPELL_SPECIFIC_SEAL, SPELL_SPECIFIC_STING, and SPELL_SPECIFIC_WARLOCK_CORRUPTION.
Referenced by Aura::CanStackWith().
IsAuraExclusiveBySpecificWith()
bool SpellInfo::IsAuraExclusiveBySpecificWith (SpellInfo const * spellInfo) const
Definition at line 1363 of file SpellInfo.cpp.
 {
     SpellSpecificType spellSpec1 = GetSpellSpecific();
     SpellSpecificType spellSpec2 = spellInfo->GetSpellSpecific();
     switch (spellSpec1)
     {
         case SPELL_SPECIFIC_TRACKER:
         case SPELL_SPECIFIC_WARLOCK_ARMOR:
         case SPELL_SPECIFIC_MAGE_ARMOR:
         case SPELL_SPECIFIC_ELEMENTAL_SHIELD:
         case SPELL_SPECIFIC_MAGE_POLYMORPH:
         case SPELL_SPECIFIC_PRESENCE:
         case SPELL_SPECIFIC_CHARM:
         case SPELL_SPECIFIC_SCROLL:
         case SPELL_SPECIFIC_MAGE_ARCANE_BRILLANCE:
         case SPELL_SPECIFIC_PRIEST_DIVINE_SPIRIT:
             return spellSpec1 == spellSpec2;
         case SPELL_SPECIFIC_FOOD:
             return spellSpec2 == SPELL_SPECIFIC_FOOD
                    || spellSpec2 == SPELL_SPECIFIC_FOOD_AND_DRINK;
         case SPELL_SPECIFIC_DRINK:
             return spellSpec2 == SPELL_SPECIFIC_DRINK
                    || spellSpec2 == SPELL_SPECIFIC_FOOD_AND_DRINK;
         case SPELL_SPECIFIC_FOOD_AND_DRINK:
             return spellSpec2 == SPELL_SPECIFIC_FOOD
                    || spellSpec2 == SPELL_SPECIFIC_DRINK
                    || spellSpec2 == SPELL_SPECIFIC_FOOD_AND_DRINK;
         default:
             return false;
     }
 }
References GetSpellSpecific(), SPELL_SPECIFIC_CHARM, SPELL_SPECIFIC_DRINK, SPELL_SPECIFIC_ELEMENTAL_SHIELD, SPELL_SPECIFIC_FOOD, SPELL_SPECIFIC_FOOD_AND_DRINK, SPELL_SPECIFIC_MAGE_ARCANE_BRILLANCE, SPELL_SPECIFIC_MAGE_ARMOR, SPELL_SPECIFIC_MAGE_POLYMORPH, SPELL_SPECIFIC_PRESENCE, SPELL_SPECIFIC_PRIEST_DIVINE_SPIRIT, SPELL_SPECIFIC_SCROLL, SPELL_SPECIFIC_TRACKER, and SPELL_SPECIFIC_WARLOCK_ARMOR.
Referenced by Aura::CanStackWith().
IsAutocastable()
bool SpellInfo::IsAutocastable () const
Definition at line 1086 of file SpellInfo.cpp.
 {
     if (HasAttribute(SPELL_ATTR0_PASSIVE))
         return false;
     if (HasAttribute(SPELL_ATTR1_NO_AUTOCAST_AI))
         return false;
     return true;
 }
References HasAttribute(), SPELL_ATTR0_PASSIVE, and SPELL_ATTR1_NO_AUTOCAST_AI.
Referenced by Pet::addSpell(), CharmInfo::AddSpellToActionBar(), WorldSession::HandlePetSpellAutocastOpcode(), CharmInfo::InitCharmCreateSpells(), CharmInfo::LoadPetActionBar(), and Pet::ToggleAutocast().
IsAutoRepeatRangedSpell()
bool SpellInfo::IsAutoRepeatRangedSpell () const
Definition at line 1266 of file SpellInfo.cpp.
 {
     return AttributesEx2 & SPELL_ATTR2_AUTO_REPEAT;
 }
References AttributesEx2, and SPELL_ATTR2_AUTO_REPEAT.
Referenced by Player::AddSpellAndCategoryCooldowns(), CalcCastTime(), WorldSession::HandleCastSpellOpcode(), Spell::SendSpellGo(), Spell::SendSpellStart(), and Spell::Spell().
IsBreakingStealth()
bool SpellInfo::IsBreakingStealth () const
Definition at line 1254 of file SpellInfo.cpp.
 {
     return !(AttributesEx & SPELL_ATTR1_ALLOW_WHILE_STEALTHED);
 }
References AttributesEx, and SPELL_ATTR1_ALLOW_WHILE_STEALTHED.
Referenced by Spell::prepare().
IsChannelCategorySpell()
bool SpellInfo::IsChannelCategorySpell () const
Definition at line 1066 of file SpellInfo.cpp.
 {
     for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
         if (Effects[i].TargetA.GetSelectionCategory() == TARGET_SELECT_CATEGORY_CHANNEL || Effects[i].TargetB.GetSelectionCategory() == TARGET_SELECT_CATEGORY_CHANNEL)
             return true;
     return false;
 }
References Effects, MAX_SPELL_EFFECTS, and TARGET_SELECT_CATEGORY_CHANNEL.
Referenced by AuraEffect::HandlePeriodicTriggerSpellAuraTick().
IsChanneled()
bool SpellInfo::IsChanneled () const
Definition at line 1239 of file SpellInfo.cpp.
 {
     return (AttributesEx & (SPELL_ATTR1_IS_CHANNELED | SPELL_ATTR1_IS_SELF_CHANNELED));
 }
References AttributesEx, SPELL_ATTR1_IS_CHANNELED, and SPELL_ATTR1_IS_SELF_CHANNELED.
Referenced by Spell::_cast(), Unit::CalculateDefaultCoefficient(), Spell::cancel(), Aura::CanStackWith(), Spell::finish(), Unit::GetCastingTimeForBonus(), Spell::GetCurrentContainer(), Spell::handle_immediate(), WorldSession::HandleCancelAuraOpcode(), IsMoveAllowedChannel(), Spell::IsNeedSendToClient(), Unit::ModSpellCastTime(), NeedsToBeTriggeredByCaster(), Spell::prepare(), Spell::SelectSpellTargets(), Spell::SendSpellGo(), and Spell::SendSpellStart().
IsCooldownStartedOnEvent()
bool SpellInfo::IsCooldownStartedOnEvent () const
Definition at line 1195 of file SpellInfo.cpp.
 {
     return HasAttribute(SPELL_ATTR0_COOLDOWN_ON_EVENT) || (CategoryEntry && CategoryEntry->Flags & SPELL_CATEGORY_FLAG_COOLDOWN_STARTS_ON_EVENT);
 }
References CategoryEntry, SpellCategoryEntry::Flags, HasAttribute(), SPELL_ATTR0_COOLDOWN_ON_EVENT, and SPELL_CATEGORY_FLAG_COOLDOWN_STARTS_ON_EVENT.
Referenced by Aura::_ApplyForTarget(), Spell::_handle_finish_phase(), Unit::AddGameObject(), Player::AddSpellAndCategoryCooldowns(), Spell::CheckCast(), Spell::finish(), WorldSession::HandlePetActionHelper(), WorldSession::HandlePetCancelAuraOpcode(), Player::ProhibitSpellSchool(), Unit::RemoveGameObject(), Spell::SendSpellCooldown(), and Unit::SetMinion().
IsCritCapable()
bool SpellInfo::IsCritCapable () const
Definition at line 1160 of file SpellInfo.cpp.
 {
     return _isCritCapable;
 }
References _isCritCapable.
Referenced by Unit::SpellDoneCritChance(), and Unit::SpellTakenCritChance().
IsDeathPersistent()
bool SpellInfo::IsDeathPersistent () const
Definition at line 1200 of file SpellInfo.cpp.
 {
     return AttributesEx3 & SPELL_ATTR3_ALLOW_AURA_WHILE_DEAD;
 }
References AttributesEx3, and SPELL_ATTR3_ALLOW_AURA_WHILE_DEAD.
Referenced by Unit::_CreateAuraApplication(), CheckTarget(), and Aura::IsDeathPersistent().
IsDifferentRankOf()
bool SpellInfo::IsDifferentRankOf (SpellInfo const * spellInfo) const
Definition at line 2515 of file SpellInfo.cpp.
 {
     if (Id == spellInfo->Id)
         return false;
     return IsRankOf(spellInfo);
 }
References Id, and IsRankOf().
Referenced by Pet::addSpell(), and Aura::CanStackWith().
IsExplicitDiscovery()
bool SpellInfo::IsExplicitDiscovery () const
Definition at line 900 of file SpellInfo.cpp.
 {
     return ((Effects[0].Effect == SPELL_EFFECT_CREATE_RANDOM_ITEM
              || Effects[0].Effect == SPELL_EFFECT_CREATE_ITEM_2)
             && Effects[1].Effect == SPELL_EFFECT_SCRIPT_EFFECT)
            || Id == 64323;
 }
References Effects, Id, SPELL_EFFECT_CREATE_ITEM_2, SPELL_EFFECT_CREATE_RANDOM_ITEM, and SPELL_EFFECT_SCRIPT_EFFECT.
Referenced by LoadSkillDiscoveryTable().
IsHighRankOf()
bool SpellInfo::IsHighRankOf (SpellInfo const * spellInfo) const
Definition at line 2522 of file SpellInfo.cpp.
 {
     if (ChainEntry && spellInfo->ChainEntry)
     {
         if (ChainEntry->first == spellInfo->ChainEntry->first)
             if (ChainEntry->rank > spellInfo->ChainEntry->rank)
                 return true;
     }
     return false;
 }
References ChainEntry, SpellChainNode::first, and SpellChainNode::rank.
Referenced by Pet::addSpell(), and Player::PrepareCharmAISpells().
IsLootCrafting()
bool SpellInfo::IsLootCrafting () const
Definition at line 908 of file SpellInfo.cpp.
 {
     return (Effects[0].Effect == SPELL_EFFECT_CREATE_RANDOM_ITEM ||
             // different random cards from Inscription (121==Virtuoso Inking Set category) r without explicit item
             (Effects[0].Effect == SPELL_EFFECT_CREATE_ITEM_2 &&
              ((TotemCategory[0] != 0 || (Totem[0] != 0 && SpellIconID == 1)) || Effects[0].ItemType == 0)));
 }
References Effects, SPELL_EFFECT_CREATE_ITEM_2, SPELL_EFFECT_CREATE_RANDOM_ITEM, and SpellIconID.
Referenced by SpellMgr::ComputeIsSpellValid(), Spell::EffectCreateItem2(), and LoadLootTemplates_Spell().
IsMoveAllowedChannel()
bool SpellInfo::IsMoveAllowedChannel () const
Definition at line 1244 of file SpellInfo.cpp.
 {
     return IsChanneled() && HasAttribute(SPELL_ATTR5_ALLOW_ACTION_DURING_CHANNEL);
 }
References HasAttribute(), IsChanneled(), and SPELL_ATTR5_ALLOW_ACTION_DURING_CHANNEL.
Referenced by Creature::IsMovementPreventedByCasting().
IsMultiSlotAura()
bool SpellInfo::IsMultiSlotAura () const
Definition at line 1190 of file SpellInfo.cpp.
 {
     return IsPassive() || Id == 40075; // No other way to make 40075 have more than 1 copy of aura
 }
References Id, and IsPassive().
Referenced by Unit::_TryStackingOrRefreshingExistingAura(), and Aura::CanStackWith().
IsPassive()
bool SpellInfo::IsPassive () const
Definition at line 1081 of file SpellInfo.cpp.
 {
     return HasAttribute(SPELL_ATTR0_PASSIVE);
 }
References HasAttribute(), and SPELL_ATTR0_PASSIVE.
Referenced by Player::_addSpell(), Player::_addTalentAurasAndSpells(), Pet::addSpell(), CanDispelAura(), Spell::CheckCast(), ComputeIsStackableWithRanks(), UnitAI::FillAISpellInfo(), WorldSession::HandleCancelAuraOpcode(), WorldSession::HandleCastSpellOpcode(), lookup_commandscript::HandleLookupSpellCommand(), lookup_commandscript::HandleLookupSpellIdCommand(), WorldSession::HandlePetActionHelper(), WorldSession::HandlePetCastSpellOpcode(), spell_gen_clear_debuffs::HandleScript(), CharmInfo::InitCharmCreateSpells(), CharmInfo::InitPossessCreateSpells(), IsMultiSlotAura(), Aura::IsPassive(), IsPassiveStackableWithRanks(), Spell::prepare(), Player::PrepareCharmAISpells(), Spell::SendSpellCooldown(), Spell::Spell(), CharmInfo::ToggleCreatureAutocast(), and Player::VehicleSpellInitialize().
IsPassiveStackableWithRanks()
bool SpellInfo::IsPassiveStackableWithRanks () const
Definition at line 1185 of file SpellInfo.cpp.
 {
     return IsPassive() && !HasEffect(SPELL_EFFECT_APPLY_AURA);
 }
References HasEffect(), IsPassive(), and SPELL_EFFECT_APPLY_AURA.
IsPositive()
bool SpellInfo::IsPositive () const
Definition at line 1220 of file SpellInfo.cpp.
 {
     return !(AttributesCu & SPELL_ATTR0_CU_NEGATIVE) || (AttributesCu & SPELL_ATTR0_CU_POSITIVE);
 }
References AttributesCu, SPELL_ATTR0_CU_NEGATIVE, and SPELL_ATTR0_CU_POSITIVE.
Referenced by Spell::_cast(), Pet::_LoadAuras(), Player::_LoadAuras(), Pet::_SaveAuras(), Unit::CalcAbsorbResist(), Player::CastItemCombatSpell(), Spell::CheckCast(), spell_dk_dancing_rune_weapon::CheckProc(), CheckTarget(), Spell::DoAllEffectOnTarget(), Spell::DoSpellHitOnUnit(), Spell::EffectCharge(), UnitAI::FillAISpellInfo(), GetDiminishingReturnsGroupForSpell(), spell_rog_deadly_poison::HandleAfterHit(), AuraEffect::HandleAuraModSchoolImmunity(), AuraEffect::HandleAuraTransform(), WorldSession::HandleCancelAuraOpcode(), Unit::HandleDummyAuraProc(), WorldSession::HandlePetActionHelper(), Unit::HandleProcTriggerSpell(), ArenaSpectator::HandleResetCommand(), spell_gen_clear_debuffs::HandleScript(), GameObject::IsAtInteractDistance(), Unit::IsImmunedToSpell(), Unit::IsImmunedToSpellEffect(), Totem::IsImmunedToSpellEffect(), Unit::MagicSpellHitResult(), SmartScript::OnInitialize(), Unit::PetSpellFail(), Spell::prepare(), Spell::PrepareTriggersExecutedOnHit(), Spell::SelectExplicitTargets(), Spell::SelectImplicitNearbyTargets(), ArenaSpectator::ShouldSendAura(), Spell::Spell(), Unit::SpellHitResult(), Unit::SpellTakenCritChance(), PetAI::UpdateAI(), and Spell::UpdateChanneledTargetList().
IsPositiveEffect()
bool SpellInfo::IsPositiveEffect (uint8 effIndex) const
Definition at line 1225 of file SpellInfo.cpp.
 {
     switch (effIndex)
     {
         default:
         case 0:
             return !(AttributesCu & SPELL_ATTR0_CU_NEGATIVE_EFF0) || (AttributesCu & SPELL_ATTR0_CU_POSITIVE_EFF0);
         case 1:
             return !(AttributesCu & SPELL_ATTR0_CU_NEGATIVE_EFF1) || (AttributesCu & SPELL_ATTR0_CU_POSITIVE_EFF1);
         case 2:
             return !(AttributesCu & SPELL_ATTR0_CU_NEGATIVE_EFF2) || (AttributesCu & SPELL_ATTR0_CU_POSITIVE_EFF2);
     }
 }
References AttributesCu, SPELL_ATTR0_CU_NEGATIVE_EFF0, SPELL_ATTR0_CU_NEGATIVE_EFF1, SPELL_ATTR0_CU_NEGATIVE_EFF2, SPELL_ATTR0_CU_POSITIVE_EFF0, SPELL_ATTR0_CU_POSITIVE_EFF1, and SPELL_ATTR0_CU_POSITIVE_EFF2.
Referenced by AuraApplication::_InitFlags(), Spell::DoAllEffectOnTarget(), GetAuraRankForLevel(), Unit::IsImmunedToSpellEffect(), and Spell::prepare().
IsPrimaryProfession()
bool SpellInfo::IsPrimaryProfession () const
Definition at line 951 of file SpellInfo.cpp.
 {
     for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
     {
         if (Effects[i].Effect == SPELL_EFFECT_SKILL)
         {
             uint32 skill = Effects[i].MiscValue;
             if (IsPrimaryProfessionSkill(skill))
                 return true;
         }
     }
     return false;
 }
References Effects, IsPrimaryProfessionSkill(), MAX_SPELL_EFFECTS, and SPELL_EFFECT_SKILL.
Referenced by IsPrimaryProfessionFirstRank().
IsPrimaryProfessionFirstRank()
bool SpellInfo::IsPrimaryProfessionFirstRank () const
Definition at line 966 of file SpellInfo.cpp.
 {
     return IsPrimaryProfession() && GetRank() == 1;
 }
References GetRank(), and IsPrimaryProfession().
Referenced by Player::_addSpell(), Player::GetTrainerSpellState(), Player::removeSpell(), and WorldSession::SendTrainerList().
IsProfession()
bool SpellInfo::IsProfession () const
Definition at line 936 of file SpellInfo.cpp.
 {
     for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
     {
         if (Effects[i].Effect == SPELL_EFFECT_SKILL)
         {
             uint32 skill = Effects[i].MiscValue;
             if (IsProfessionSkill(skill))
                 return true;
         }
     }
     return false;
 }
References Effects, IsProfessionSkill(), MAX_SPELL_EFFECTS, and SPELL_EFFECT_SKILL.
Referenced by ObjectMgr::AddSpellToTrainer().
IsProfessionOrRiding()
bool SpellInfo::IsProfessionOrRiding () const
Definition at line 921 of file SpellInfo.cpp.
 {
     for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
     {
         if (Effects[i].Effect == SPELL_EFFECT_SKILL)
         {
             uint32 skill = Effects[i].MiscValue;
             if (IsProfessionOrRidingSkill(skill))
                 return true;
         }
     }
     return false;
 }
References Effects, IsProfessionOrRidingSkill(), MAX_SPELL_EFFECTS, and SPELL_EFFECT_SKILL.
Referenced by ComputeIsStackableWithRanks().
IsQuestTame()
bool SpellInfo::IsQuestTame () const
Definition at line 916 of file SpellInfo.cpp.
 {
     return Effects[0].Effect == SPELL_EFFECT_THREAT && Effects[1].Effect == SPELL_EFFECT_APPLY_AURA && Effects[1].ApplyAuraName == SPELL_AURA_DUMMY;
 }
References Effects, SPELL_AURA_DUMMY, SPELL_EFFECT_APPLY_AURA, and SPELL_EFFECT_THREAT.
IsRangedWeaponSpell()
bool SpellInfo::IsRangedWeaponSpell () const
Definition at line 1259 of file SpellInfo.cpp.
 {
     return (SpellFamilyName == SPELLFAMILY_HUNTER && !(SpellFamilyFlags[1] & 0x10000000)) // for 53352, cannot find better way
            || (EquippedItemSubClassMask & ITEM_SUBCLASS_MASK_WEAPON_RANGED)
            || (HasAttribute(SPELL_ATTR0_USES_RANGED_SLOT)); // Xinef: added
 }
References EquippedItemSubClassMask, HasAttribute(), ITEM_SUBCLASS_MASK_WEAPON_RANGED, SPELL_ATTR0_USES_RANGED_SLOT, SPELLFAMILY_HUNTER, SpellFamilyFlags, and SpellFamilyName.
Referenced by Spell::handle_immediate(), Unit::MeleeSpellHitResult(), Spell::Spell(), Unit::SpellDamageBonusDone(), and Unit::SpellHealingBonusDone().
IsRanked()
bool SpellInfo::IsRanked () const
Definition at line 2430 of file SpellInfo.cpp.
 {
     return ChainEntry != nullptr;
 }
References ChainEntry.
Referenced by Pet::addSpell(), Player::addSpell(), and SpellMgr::LoadSpellProcEvents().
IsRankOf()
bool SpellInfo::IsRankOf (SpellInfo const * spellInfo) const
Definition at line 2510 of file SpellInfo.cpp.
 {
     return GetFirstRankSpell() == spellInfo->GetFirstRankSpell();
 }
References GetFirstRankSpell().
Referenced by Aura::CanStackWith(), Unit::HandleDummyAuraProc(), IsDifferentRankOf(), IsStrongerAuraActive(), spell_dk_will_of_the_necropolis::Validate(), spell_pal_holy_shock::Validate(), spell_pri_penance::Validate(), and spell_sha_fire_nova::Validate().
IsRequiringDeadTarget()
bool SpellInfo::IsRequiringDeadTarget () const
Definition at line 1205 of file SpellInfo.cpp.
 {
     return AttributesEx3 & SPELL_ATTR3_ONLY_ON_GHOSTS;
 }
References AttributesEx3, and SPELL_ATTR3_ONLY_ON_GHOSTS.
Referenced by CheckTarget(), Spell::IsValidDeadOrAliveTarget(), and Unit::RemoveAllAurasRequiringDeadTarget().
IsSelfCast()
bool SpellInfo::IsSelfCast () const
Definition at line 1073 of file SpellInfo.cpp.
 {
     for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
         if (Effects[i].Effect && Effects[i].TargetA.GetTarget() != TARGET_UNIT_CASTER)
             return false;
     return true;
 }
References Effects, MAX_SPELL_EFFECTS, and TARGET_UNIT_CASTER.
Referenced by Spell::CheckCast(), and Player::RewardQuest().
IsSingleTarget()
bool SpellInfo::IsSingleTarget () const
Definition at line 1346 of file SpellInfo.cpp.
 {
     // all other single target spells have if it has AttributesEx5
     if (AttributesEx5 & SPELL_ATTR5_LIMIT_N)
         return true;
     switch (GetSpellSpecific())
     {
         case SPELL_SPECIFIC_JUDGEMENT:
             return true;
         default:
             break;
     }
     return false;
 }
References AttributesEx5, GetSpellSpecific(), SPELL_ATTR5_LIMIT_N, and SPELL_SPECIFIC_JUDGEMENT.
Referenced by Unit::_AddAura(), and Aura::Create().
IsSpellValid()
bool SpellInfo::IsSpellValid () const
Definition at line 1175 of file SpellInfo.cpp.
 {
     return _isSpellValid;
 }
References _isSpellValid.
Referenced by SpellMgr::IsSpellValid().
IsStackableWithRanks()
bool SpellInfo::IsStackableWithRanks () const
Definition at line 1128 of file SpellInfo.cpp.
 {
     return _isStackableWithRanks;
 }
References _isStackableWithRanks.
Referenced by Player::addSpell().
IsStrongerAuraActive()
bool SpellInfo::IsStrongerAuraActive (Unit const * caster, Unit const * target) const
Definition at line 1564 of file SpellInfo.cpp.
 {
     if (!target)
         return false;
     // xinef: check spell group
     uint32 groupId = sSpellMgr->GetSpellGroup(Id);
     if (!groupId)
         return false;
     SpellGroupSpecialFlags sFlag = sSpellMgr->GetSpellGroupSpecialFlags(Id);
     if (sFlag & SPELL_GROUP_SPECIAL_FLAG_SKIP_STRONGER_CHECK)
         return false;
     for (uint8 i = EFFECT_0; i < MAX_SPELL_EFFECTS; ++i)
     {
         // xinef: Skip Empty effects
         if (!Effects[i].IsEffect())
             continue;
         // xinef: if non-aura effect is preset - return false
         if (!Effects[i].IsAura())
             return false;
         // xinef: aura is periodic - return false
         if (Effects[i].Amplitude)
             return false;
         // xinef: exclude dummy auras
         if (Effects[i].ApplyAuraName == SPELL_AURA_DUMMY)
             return false;
     }
     for (uint8 i = EFFECT_0; i < MAX_SPELL_EFFECTS; ++i)
     {
         // xinef: skip non-aura efects
         if (!Effects[i].IsAura())
             return false;
         Unit::AuraEffectList const& auraList = target->GetAuraEffectsByType((AuraType)Effects[i].ApplyAuraName);
         for (Unit::AuraEffectList::const_iterator iter = auraList.begin(); iter != auraList.end(); ++iter)
         {
             // xinef: aura is not groupped or in different group
             uint32 auraGroup = (*iter)->GetAuraGroup();
             if (!auraGroup || auraGroup != groupId)
                 continue;
             // xinef: check priority before effect mask
             if (sFlag >= SPELL_GROUP_SPECIAL_FLAG_PRIORITY1)
             {
                 SpellGroupSpecialFlags sFlagCurr = sSpellMgr->GetSpellGroupSpecialFlags((*iter)->GetId());
                 if (sFlagCurr >= SPELL_GROUP_SPECIAL_FLAG_PRIORITY1 && sFlagCurr < sFlag)
                     return true;
             }
             // xinef: check aura effect equal auras only, some auras have different effects on different ranks - check rank also
             if (!IsAuraEffectEqual((*iter)->GetSpellInfo()) && !IsRankOf((*iter)->GetSpellInfo()))
                 continue;
             // xinef: misc value mismatches
             // xinef: commented, checked above
             //if (Effects[i].MiscValue != (*iter)->GetMiscValue())
             //  continue;
             // xinef: should not happen, or effect is not active - stronger one is present
             AuraApplication* aurApp = (*iter)->GetBase()->GetApplicationOfTarget(target->GetGUID());
             if (!aurApp || !aurApp->IsActive((*iter)->GetEffIndex()))
                 continue;
             // xinef: assume that all spells are either positive or negative, otherwise they should not be in one group
             // xinef: take custom values into account
             int32 basePoints = Effects[i].BasePoints;
             int32 duration = GetMaxDuration();
             // xinef: should have the same id, can be different if spell is triggered
             // xinef: have to fix spell mods for triggered spell, turn off current spellmodtakingspell for preparing and restore after
             if (Player const* player = caster->GetSpellModOwner())
                 if (player->m_spellModTakingSpell && player->m_spellModTakingSpell->m_spellInfo->Id == Id)
                     basePoints = player->m_spellModTakingSpell->GetSpellValue()->EffectBasePoints[i];
             int32 curValue = abs(Effects[i].CalcValue(caster, &basePoints));
             int32 auraValue = (sFlag & SPELL_GROUP_SPECIAL_FLAG_BASE_AMOUNT_CHECK) ?
                               abs((*iter)->GetSpellInfo()->Effects[(*iter)->GetEffIndex()].CalcValue((*iter)->GetCaster())) :
                               abs((*iter)->GetAmount());
             // xinef: for same spells, divide amount by stack amount
             if (Id == (*iter)->GetId())
                 auraValue /= (*iter)->GetBase()->GetStackAmount();
             if (curValue < auraValue)
                 return true;
             // xinef: little hack, if current spell is the same as aura spell, asume it is not stronger
             // xinef: if values are the same, duration mods should be taken into account but they are almost always passive
             if (curValue == auraValue)
             {
                 if (Id == (*iter)->GetId())
                     continue;
                 if (!(*iter)->GetBase()->IsPassive() && duration < (*iter)->GetBase()->GetDuration())
                     return true;
             }
         }
     }
     return false;
 }
References abs(), EFFECT_0, Effects, Aura::GetApplicationOfTarget(), Unit::GetAuraEffectsByType(), AuraApplication::GetBase(), Object::GetGUID(), GetMaxDuration(), Unit::GetSpellModOwner(), Id, AuraApplication::IsActive(), IsAuraEffectEqual(), IsRankOf(), MAX_SPELL_EFFECTS, SPELL_AURA_DUMMY, SPELL_GROUP_SPECIAL_FLAG_BASE_AMOUNT_CHECK, SPELL_GROUP_SPECIAL_FLAG_PRIORITY1, SPELL_GROUP_SPECIAL_FLAG_SKIP_STRONGER_CHECK, and sSpellMgr.
Referenced by CheckTarget().
IsTargetingArea()
bool SpellInfo::IsTargetingArea () const
Definition at line 1008 of file SpellInfo.cpp.
 {
     for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
         if (Effects[i].IsEffect() && Effects[i].IsTargetingArea())
             return true;
     return false;
 }
References Effects, and MAX_SPELL_EFFECTS.
Referenced by spell_dk_dancing_rune_weapon::CheckProc(), spell_gen_proc_from_direct_damage::CheckProc(), Spell::DoAllEffectOnTarget(), Spell::HandleLaunchPhase(), spell_dk_bone_shield::HandleProc(), IsAffectingArea(), and npc_oculus_drake::npc_oculus_drakeAI::SpellHitTarget().
LoadAuraState()
AuraStateType SpellInfo::LoadAuraState () const
Definition at line 2009 of file SpellInfo.cpp.
 {
     // Seals
     if (GetSpellSpecific() == SPELL_SPECIFIC_SEAL)
         return AURA_STATE_JUDGEMENT;
     // Conflagrate aura state on Immolate and Shadowflame
     if (SpellFamilyName == SPELLFAMILY_WARLOCK &&
             // Immolate
             ((SpellFamilyFlags[0] & 4) ||
              // Shadowflame
              (SpellFamilyFlags[2] & 2)))
         return AURA_STATE_CONFLAGRATE;
     // Faerie Fire (druid versions)
     if (SpellFamilyName == SPELLFAMILY_DRUID && SpellFamilyFlags[0] & 0x400)
         return AURA_STATE_FAERIE_FIRE;
     // Sting (hunter's pet ability)
     if (GetCategory() == 1133)
         return AURA_STATE_FAERIE_FIRE;
     // Victorious
     if (SpellFamilyName == SPELLFAMILY_WARRIOR &&  SpellFamilyFlags[1] & 0x00040000)
         return AURA_STATE_WARRIOR_VICTORY_RUSH;
     // Swiftmend state on Regrowth & Rejuvenation
     if (SpellFamilyName == SPELLFAMILY_DRUID && SpellFamilyFlags[0] & 0x50)
         return AURA_STATE_SWIFTMEND;
     // Deadly poison aura state
     if (SpellFamilyName == SPELLFAMILY_ROGUE && SpellFamilyFlags[0] & 0x10000)
         return AURA_STATE_DEADLY_POISON;
     // Enrage aura state
     if (Dispel == DISPEL_ENRAGE)
         return AURA_STATE_ENRAGE;
     // Bleeding aura state
     if (GetAllEffectsMechanicMask() & 1 << MECHANIC_BLEED)
         return AURA_STATE_BLEEDING;
     if (GetSchoolMask() & SPELL_SCHOOL_MASK_FROST)
         for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
             if (Effects[i].IsAura() && (Effects[i].ApplyAuraName == SPELL_AURA_MOD_STUN
                                         || Effects[i].ApplyAuraName == SPELL_AURA_MOD_ROOT))
                 return AURA_STATE_FROZEN;
     switch (Id)
     {
         case 71465: // Divine Surge
         case 50241: // Oculus, Drake spell Evasive Maneuvers
             return AURA_STATE_UNKNOWN22;
         case 9991:  // Touch of Zanzil
         case 35331: // Black Blood
         case 9806:  // Phantom Strike
         case 35325: // Glowing Blood
         case 16498: // Faerie Fire
         case 6950:
         case 20656:
         case 25602:
         case 32129:
             return AURA_STATE_FAERIE_FIRE;
         default:
             break;
     }
     return AURA_STATE_NONE;
 }
References AURA_STATE_BLEEDING, AURA_STATE_CONFLAGRATE, AURA_STATE_DEADLY_POISON, AURA_STATE_ENRAGE, AURA_STATE_FAERIE_FIRE, AURA_STATE_FROZEN, AURA_STATE_JUDGEMENT, AURA_STATE_NONE, AURA_STATE_SWIFTMEND, AURA_STATE_UNKNOWN22, AURA_STATE_WARRIOR_VICTORY_RUSH, Dispel, DISPEL_ENRAGE, Effects, GetAllEffectsMechanicMask(), GetCategory(), GetSchoolMask(), GetSpellSpecific(), Id, MAX_SPELL_EFFECTS, MECHANIC_BLEED, SPELL_AURA_MOD_ROOT, SPELL_AURA_MOD_STUN, SPELL_SCHOOL_MASK_FROST, SPELL_SPECIFIC_SEAL, SPELLFAMILY_DRUID, SPELLFAMILY_ROGUE, SPELLFAMILY_WARLOCK, SPELLFAMILY_WARRIOR, SpellFamilyFlags, and SpellFamilyName.
Referenced by SpellMgr::LoadSpellSpecificAndAuraState().
LoadSpellSpecific()
SpellSpecificType SpellInfo::LoadSpellSpecific () const
@workaround For non-stacking tracking spells (We need generic solution)
Definition at line 2084 of file SpellInfo.cpp.
 {
     switch (SpellFamilyName)
     {
         case SPELLFAMILY_GENERIC:
             {
                 // Food / Drinks (mostly)
                 if (AuraInterruptFlags & AURA_INTERRUPT_FLAG_NOT_SEATED)
                 {
                     bool food = false;
                     bool drink = false;
                     for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
                     {
                         if (!Effects[i].IsAura())
                             continue;
                         switch (Effects[i].ApplyAuraName)
{
                             // Food
                             case SPELL_AURA_MOD_REGEN:
                             case SPELL_AURA_OBS_MOD_HEALTH:
                                 food = true;
                                 break;
                             // Drink
                             case SPELL_AURA_MOD_POWER_REGEN:
                             case SPELL_AURA_OBS_MOD_POWER:
                                 drink = true;
                                 break;
                             default:
                                 break;
                         }
                     }
                     if (food && drink)
                         return SPELL_SPECIFIC_FOOD_AND_DRINK;
                     else if (food)
                         return SPELL_SPECIFIC_FOOD;
                     else if (drink)
                         return SPELL_SPECIFIC_DRINK;
                 }
                 // scrolls effects
                 else
                 {
                     SpellInfo const* firstRankSpellInfo = GetFirstRankSpell();
                     switch (firstRankSpellInfo->Id)
                     {
                         case 8118: // Strength
                         case 8099: // Stamina
                         case 8112: // Spirit
                         case 8096: // Intellect
                         case 8115: // Agility
                         case 8091: // Armor
                             return SPELL_SPECIFIC_SCROLL;
                     }
                 }
                 break;
             }
         case SPELLFAMILY_MAGE:
             {
                 // family flags 18(Molten), 25(Frost/Ice), 28(Mage)
                 if (SpellFamilyFlags[0] & 0x12040000)
                     return SPELL_SPECIFIC_MAGE_ARMOR;
                 // Arcane brillance and Arcane intelect (normal check fails because of flags difference)
                 if (SpellFamilyFlags[0] & 0x400)
                     return SPELL_SPECIFIC_MAGE_ARCANE_BRILLANCE;
                 if ((SpellFamilyFlags[0] & 0x1000000) && Effects[0].ApplyAuraName == SPELL_AURA_MOD_CONFUSE)
                     return SPELL_SPECIFIC_MAGE_POLYMORPH;
                 break;
             }
         case SPELLFAMILY_WARLOCK:
             {
                 // only warlock curses have this
                 if (Dispel == DISPEL_CURSE)
                     return SPELL_SPECIFIC_CURSE;
                 // Warlock (Demon Armor | Demon Skin | Fel Armor)
                 if (SpellFamilyFlags[1] & 0x20000020 || SpellFamilyFlags[2] & 0x00000010)
                     return SPELL_SPECIFIC_WARLOCK_ARMOR;
                 //seed of corruption and corruption
                 if (SpellFamilyFlags[1] & 0x10 || SpellFamilyFlags[0] & 0x2)
                     return SPELL_SPECIFIC_WARLOCK_CORRUPTION;
                 break;
             }
         case SPELLFAMILY_PRIEST:
             {
                 // Divine Spirit and Prayer of Spirit
                 if (SpellFamilyFlags[0] & 0x20)
                     return SPELL_SPECIFIC_PRIEST_DIVINE_SPIRIT;
                 break;
             }
         case SPELLFAMILY_HUNTER:
             {
                 // only hunter stings have this
                 if (Dispel == DISPEL_POISON)
                     return SPELL_SPECIFIC_STING;
                 // only hunter aspects have this (but not all aspects in hunter family)
                 if (SpellFamilyFlags.HasFlag(0x00380000, 0x00440000, 0x00001010))
                     return SPELL_SPECIFIC_ASPECT;
                 break;
             }
         case SPELLFAMILY_PALADIN:
             {
                 // Collection of all the seal family flags. No other paladin spell has any of those.
                 if (SpellFamilyFlags[1] & 0x26000C00
                         || SpellFamilyFlags[0] & 0x0A000000)
                     return SPELL_SPECIFIC_SEAL;
                 if (SpellFamilyFlags[0] & 0x00002190)
                     return SPELL_SPECIFIC_HAND;
                 // Judgement of Wisdom, Judgement of Light, Judgement of Justice
                 if (Id == 20184 || Id == 20185 || Id == 20186)
                     return SPELL_SPECIFIC_JUDGEMENT;
                 // only paladin auras have this (for palaldin class family)
                 if (SpellFamilyFlags[2] & 0x00000020)
                     return SPELL_SPECIFIC_AURA;
                 // Illidari Council Paladin (Gathios the Shatterer)
                 if (Id == 41459 || Id == 41469)
                     return SPELL_SPECIFIC_SEAL;
                 break;
             }
         case SPELLFAMILY_SHAMAN:
             {
                 // family flags 10 (Lightning), 42 (Earth), 37 (Water), proc shield from T2 8 pieces bonus
                 if (SpellFamilyFlags[1] & 0x420
                         || SpellFamilyFlags[0] & 0x00000400
                         || Id == 23552)
                     return SPELL_SPECIFIC_ELEMENTAL_SHIELD;
                 break;
             }
         case SPELLFAMILY_DEATHKNIGHT:
             if (Id == 48266 || Id == 48263 || Id == 48265)
                 return SPELL_SPECIFIC_PRESENCE;
             break;
     }
     for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
     {
         if (Effects[i].Effect == SPELL_EFFECT_APPLY_AURA)
         {
             switch (Effects[i].ApplyAuraName)
             {
                 case SPELL_AURA_MOD_CHARM:
                 case SPELL_AURA_MOD_POSSESS_PET:
                 case SPELL_AURA_MOD_POSSESS:
                 case SPELL_AURA_AOE_CHARM:
                     return SPELL_SPECIFIC_CHARM;
                 case SPELL_AURA_TRACK_CREATURES:
                     if (Id == 30645) // Gas Cloud Tracking
                         return SPELL_SPECIFIC_NORMAL;
                     [[fallthrough]]; // TODO: Not sure whether the fallthrough was a mistake (forgetting a break) or intended. This should be double-checked.
                 case SPELL_AURA_TRACK_RESOURCES:
                 case SPELL_AURA_TRACK_STEALTHED:
                     return SPELL_SPECIFIC_TRACKER;
             }
         }
     }
     return SPELL_SPECIFIC_NORMAL;
 }
References AURA_INTERRUPT_FLAG_NOT_SEATED, AuraInterruptFlags, Dispel, DISPEL_CURSE, DISPEL_POISON, Effects, GetFirstRankSpell(), flag96::HasFlag(), Id, MAX_SPELL_EFFECTS, SPELL_AURA_AOE_CHARM, SPELL_AURA_MOD_CHARM, SPELL_AURA_MOD_CONFUSE, SPELL_AURA_MOD_POSSESS, SPELL_AURA_MOD_POSSESS_PET, SPELL_AURA_MOD_POWER_REGEN, SPELL_AURA_MOD_REGEN, SPELL_AURA_OBS_MOD_HEALTH, SPELL_AURA_OBS_MOD_POWER, SPELL_AURA_TRACK_CREATURES, SPELL_AURA_TRACK_RESOURCES, SPELL_AURA_TRACK_STEALTHED, SPELL_EFFECT_APPLY_AURA, SPELL_SPECIFIC_ASPECT, SPELL_SPECIFIC_AURA, SPELL_SPECIFIC_CHARM, SPELL_SPECIFIC_CURSE, SPELL_SPECIFIC_DRINK, SPELL_SPECIFIC_ELEMENTAL_SHIELD, SPELL_SPECIFIC_FOOD, SPELL_SPECIFIC_FOOD_AND_DRINK, SPELL_SPECIFIC_HAND, SPELL_SPECIFIC_JUDGEMENT, SPELL_SPECIFIC_MAGE_ARCANE_BRILLANCE, SPELL_SPECIFIC_MAGE_ARMOR, SPELL_SPECIFIC_MAGE_POLYMORPH, SPELL_SPECIFIC_NORMAL, SPELL_SPECIFIC_PRESENCE, SPELL_SPECIFIC_PRIEST_DIVINE_SPIRIT, SPELL_SPECIFIC_SCROLL, SPELL_SPECIFIC_SEAL, SPELL_SPECIFIC_STING, SPELL_SPECIFIC_TRACKER, SPELL_SPECIFIC_WARLOCK_ARMOR, SPELL_SPECIFIC_WARLOCK_CORRUPTION, SPELLFAMILY_DEATHKNIGHT, SPELLFAMILY_GENERIC, SPELLFAMILY_HUNTER, SPELLFAMILY_MAGE, SPELLFAMILY_PALADIN, SPELLFAMILY_PRIEST, SPELLFAMILY_SHAMAN, SPELLFAMILY_WARLOCK, SpellFamilyFlags, and SpellFamilyName.
Referenced by SpellMgr::LoadSpellSpecificAndAuraState().
NeedsComboPoints()
bool SpellInfo::NeedsComboPoints () const
Definition at line 1249 of file SpellInfo.cpp.
 {
     return (AttributesEx & (SPELL_ATTR1_FINISHING_MOVE_DAMAGE | SPELL_ATTR1_FINISHING_MOVE_DURATION));
 }
References AttributesEx, SPELL_ATTR1_FINISHING_MOVE_DAMAGE, and SPELL_ATTR1_FINISHING_MOVE_DURATION.
Referenced by Player::PrepareCharmAISpells(), and Spell::Spell().
NeedsExplicitUnitTarget()
bool SpellInfo::NeedsExplicitUnitTarget () const
Definition at line 1016 of file SpellInfo.cpp.
 {
     return GetExplicitTargetMask() & TARGET_FLAG_UNIT_MASK;
 }
References GetExplicitTargetMask(), and TARGET_FLAG_UNIT_MASK.
Referenced by Spell::CheckCast(), Spell::CheckPetCast(), WorldSession::HandlePetCastSpellOpcode(), CharmInfo::InitCharmCreateSpells(), NeedsToBeTriggeredByCaster(), and Spell::SendChannelStart().
NeedsToBeTriggeredByCaster()
bool SpellInfo::NeedsToBeTriggeredByCaster (SpellInfo const * triggeringSpell, uint8 effIndex = MAX_SPELL_EFFECTS) const
Definition at line 1021 of file SpellInfo.cpp.
 {
     if (NeedsExplicitUnitTarget())
         return true;
     // pussywizard:
     if (effIndex < MAX_SPELL_EFFECTS && (triggeringSpell->Effects[effIndex].TargetA.GetCheckType() == TARGET_CHECK_ENTRY || triggeringSpell->Effects[effIndex].TargetB.GetCheckType() == TARGET_CHECK_ENTRY))
     {
         // xinef:
         if (Id == 60563)
             return true;
         for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
             if (Effects[i].IsEffect() && (Effects[i].TargetA.GetCheckType() == TARGET_CHECK_ENTRY || Effects[i].TargetB.GetCheckType() == TARGET_CHECK_ENTRY))
                 return true;
     }
     /*
     for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
     {
         if (Effects[i].IsEffect())
         {
             if (Effects[i].TargetA.GetSelectionCategory() == TARGET_SELECT_CATEGORY_CHANNEL
                 || Effects[i].TargetB.GetSelectionCategory() == TARGET_SELECT_CATEGORY_CHANNEL)
                 return true;
         }
     }
     */
     if (triggeringSpell->IsChanneled())
     {
         uint32 mask = 0;
         for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
         {
             if (Effects[i].TargetA.GetTarget() != TARGET_UNIT_CASTER && Effects[i].TargetA.GetTarget() != TARGET_DEST_CASTER)
                 mask |= Effects[i].GetProvidedTargetMask();
         }
         if (mask & TARGET_FLAG_UNIT_MASK)
             return true;
     }
     return false;
 }
References Effects, Id, IsChanneled(), MAX_SPELL_EFFECTS, NeedsExplicitUnitTarget(), TARGET_CHECK_ENTRY, TARGET_DEST_CASTER, TARGET_FLAG_UNIT_MASK, and TARGET_UNIT_CASTER.
Referenced by Spell::EffectTriggerMissileSpell(), Spell::EffectTriggerSpell(), AuraEffect::HandleAuraLinked(), spell_hun_sniper_training::HandlePeriodic(), and AuraEffect::HandlePeriodicTriggerSpellAuraTick().
RequireCooldownInfo()
bool SpellInfo::RequireCooldownInfo () const
Definition at line 1165 of file SpellInfo.cpp.
 {
     return _requireCooldownInfo;
 }
References _requireCooldownInfo.
Referenced by Spell::SendSpellCooldown().
SetCritCapable()
void SpellInfo::SetCritCapable (bool val)
Definition at line 1170 of file SpellInfo.cpp.
 {
     _isCritCapable = val;
 }
References _isCritCapable.
SetSpellValid()
void SpellInfo::SetSpellValid (bool val)
Definition at line 1180 of file SpellInfo.cpp.
 {
     _isSpellValid = val;
 }
References _isSpellValid.
SetStackableWithRanks()
void SpellInfo::SetStackableWithRanks (bool val)
Definition at line 1133 of file SpellInfo.cpp.
 {
     _isStackableWithRanks = val;
 }
References _isStackableWithRanks.
ValidateAttribute6SpellDamageMods()
bool SpellInfo::ValidateAttribute6SpellDamageMods (const Unit * caster, const AuraEffect * auraEffect, bool isDot) const
Definition at line 1711 of file SpellInfo.cpp.
 {
     // Xinef: no attribute
     if (!(AttributesEx6 & SPELL_ATTR6_IGNORE_CASTER_DAMAGE_MODIFIERS))
         return true;
     // Xinef we have a hook to decide which auras should profit to the spell, by default no profits
     // Xinef: Scourge Strike - Trigger
     if (Id == 70890 && auraEffect)
     {
         const SpellInfo* auraInfo = auraEffect->GetSpellInfo();
         return auraInfo->SpellIconID == 3086 ||
                (auraInfo->SpellFamilyName == SPELLFAMILY_DEATHKNIGHT && (auraInfo->SpellFamilyFlags & flag96(8388608, 64, 16) || auraInfo->SpellIconID == 235 || auraInfo->SpellIconID == 154));
     }
     // Xinef: Necrosis, no profits for done and taken
     else if (Id == 51460)
         return false;
     // Xinef: Do not affect dots and auras obtained from items, only affected by self casted auras
     return !isDot && auraEffect && (auraEffect->GetAmount() < 0 || (auraEffect->GetCasterGUID() == caster->GetGUID() && auraEffect->GetSpellInfo()->SpellFamilyName == SpellFamilyName)) && !auraEffect->GetBase()->GetCastItemGUID();
 }
References AttributesEx6, AuraEffect::GetAmount(), AuraEffect::GetBase(), AuraEffect::GetCasterGUID(), Aura::GetCastItemGUID(), Object::GetGUID(), AuraEffect::GetSpellInfo(), Id, SPELL_ATTR6_IGNORE_CASTER_DAMAGE_MODIFIERS, SPELLFAMILY_DEATHKNIGHT, SpellFamilyFlags, SpellFamilyName, and SpellIconID.
Referenced by Unit::MeleeDamageBonusDone(), Unit::SpellDamageBonusTaken(), and Unit::SpellPctDamageModsDone().
Member Data Documentation
_auraState
AuraStateType SpellInfo::_auraState
Definition at line 392 of file SpellInfo.h.
Referenced by GetAuraState(), and SpellMgr::LoadSpellSpecificAndAuraState().
_isCritCapable
bool SpellInfo::_isCritCapable
Definition at line 396 of file SpellInfo.h.
Referenced by IsCritCapable(), SetCritCapable(), and SpellInfo().
_isSpellValid
bool SpellInfo::_isSpellValid
Definition at line 395 of file SpellInfo.h.
Referenced by IsSpellValid(), SetSpellValid(), and SpellInfo().
_isStackableWithRanks
bool SpellInfo::_isStackableWithRanks
Definition at line 394 of file SpellInfo.h.
Referenced by IsStackableWithRanks(), SetStackableWithRanks(), and SpellInfo().
_requireCooldownInfo
bool SpellInfo::_requireCooldownInfo
Definition at line 397 of file SpellInfo.h.
Referenced by SpellMgr::LoadSpellCustomAttr(), RequireCooldownInfo(), and SpellInfo().
_spellSpecific
SpellSpecificType SpellInfo::_spellSpecific
Definition at line 393 of file SpellInfo.h.
Referenced by GetSpellSpecific(), and SpellMgr::LoadSpellSpecificAndAuraState().
ActiveIconID
uint32 SpellInfo::ActiveIconID
Definition at line 376 of file SpellInfo.h.
Referenced by SpellInfo().
AreaGroupId
int32 SpellInfo::AreaGroupId
Definition at line 385 of file SpellInfo.h.
Referenced by Spell::CheckCast(), CheckLocation(), and SpellInfo().
Attributes
uint32 SpellInfo::Attributes
Definition at line 319 of file SpellInfo.h.
Referenced by HasAttribute(), Unit::HasNegativeAuraWithAttribute(), Spell::prepare(), Unit::RemoveAurasWithAttribute(), and SpellInfo().
AttributesCu
uint32 SpellInfo::AttributesCu
Definition at line 327 of file SpellInfo.h.
Referenced by CheckTarget(), HasAttribute(), IsPositive(), IsPositiveEffect(), SpellMgr::LoadSpellCustomAttr(), and SpellInfo().
AttributesEx
uint32 SpellInfo::AttributesEx
Definition at line 320 of file SpellInfo.h.
Referenced by CalcPowerCost(), CheckTarget(), HasAttribute(), IsBreakingStealth(), IsChanneled(), NeedsComboPoints(), and SpellInfo().
AttributesEx2
uint32 SpellInfo::AttributesEx2
Definition at line 321 of file SpellInfo.h.
Referenced by CheckShapeshift(), CheckTarget(), HasAttribute(), IsAllowingDeadTarget(), IsAutoRepeatRangedSpell(), DisableMgr::LoadDisables(), and SpellInfo().
AttributesEx3
uint32 SpellInfo::AttributesEx3
Definition at line 322 of file SpellInfo.h.
Referenced by CalcPowerCost(), CheckTarget(), Spell::DoAllEffectOnTarget(), HasAttribute(), IsAffectedBySpellMods(), IsDeathPersistent(), IsRequiringDeadTarget(), and SpellInfo().
AttributesEx4
uint32 SpellInfo::AttributesEx4
Definition at line 323 of file SpellInfo.h.
Referenced by CalcPowerCost(), HasAttribute(), and SpellInfo().
AttributesEx5
uint32 SpellInfo::AttributesEx5
Definition at line 324 of file SpellInfo.h.
Referenced by HasAttribute(), IsSingleTarget(), Unit::ModSpellCastTime(), and SpellInfo().
AttributesEx6
uint32 SpellInfo::AttributesEx6
Definition at line 325 of file SpellInfo.h.
Referenced by CheckTarget(), HasAttribute(), SpellInfo(), and ValidateAttribute6SpellDamageMods().
AttributesEx7
uint32 SpellInfo::AttributesEx7
Definition at line 326 of file SpellInfo.h.
Referenced by HasAttribute(), and SpellInfo().
AuraInterruptFlags
uint32 SpellInfo::AuraInterruptFlags
Definition at line 348 of file SpellInfo.h.
Referenced by Unit::_ApplyAura(), Unit::_CreateAuraApplication(), Pet::_SaveAuras(), Unit::_UnapplyAura(), Spell::CheckCast(), UnitAI::DoCast(), SpellMgr::LoadSpellCustomAttr(), LoadSpellSpecific(), Spell::prepare(), Unit::RemoveAurasWithInterruptFlags(), and SpellInfo().
BaseLevel
uint32 SpellInfo::BaseLevel
Definition at line 354 of file SpellInfo.h.
Referenced by SpellEffectInfo::CalcValue(), Spell::CheckItems(), and SpellInfo().
CasterAuraSpell
uint32 SpellInfo::CasterAuraSpell
Definition at line 338 of file SpellInfo.h.
Referenced by Spell::CheckCast(), and SpellInfo().
CasterAuraState
uint32 SpellInfo::CasterAuraState
Definition at line 334 of file SpellInfo.h.
Referenced by Spell::CheckCast(), Spell::finish(), Pet::HandleAsynchLoadSucceed(), Player::LoadFromDB(), and SpellInfo().
CasterAuraStateNot
uint32 SpellInfo::CasterAuraStateNot
Definition at line 336 of file SpellInfo.h.
Referenced by Spell::CheckCast(), and SpellInfo().
CastTimeEntry
SpellCastTimesEntry const* SpellInfo::CastTimeEntry
Definition at line 342 of file SpellInfo.h.
Referenced by CalcCastTime(), and SpellInfo().
CategoryEntry
SpellCategoryEntry const* SpellInfo::CategoryEntry
Definition at line 316 of file SpellInfo.h.
Referenced by GetCategory(), IsCooldownStartedOnEvent(), and SpellInfo().
CategoryRecoveryTime
uint32 SpellInfo::CategoryRecoveryTime
Definition at line 344 of file SpellInfo.h.
Referenced by Player::AddSpellAndCategoryCooldowns(), Creature::AddSpellCooldown(), Player::ApplyEquipCooldown(), Spell::EffectTriggerMissileSpell(), Spell::EffectTriggerSpell(), GetRecoveryTime(), WorldSession::HandleItemQuerySingleOpcode(), ItemTemplate::InitializeQueryData(), Player::RemoveArenaSpellCooldowns(), SpellInfo(), and Spell::TriggerGlobalCooldown().
ChainEntry
SpellChainNode const* SpellInfo::ChainEntry
Definition at line 389 of file SpellInfo.h.
Referenced by GetFirstRankSpell(), GetLastRankSpell(), GetNextRankSpell(), GetPrevRankSpell(), GetRank(), IsHighRankOf(), IsRanked(), and SpellInfo().
ChannelInterruptFlags
uint32 SpellInfo::ChannelInterruptFlags
Definition at line 349 of file SpellInfo.h.
Referenced by Spell::EffectInterruptCast(), Spell::handle_immediate(), and SpellInfo().
Dispel
uint32 SpellInfo::Dispel
Definition at line 317 of file SpellInfo.h.
Referenced by Unit::GetDispellableAuraList(), GetDispelMask(), spell_rog_deadly_poison::HandleAfterHit(), spell_item_powerful_anti_venom::HandleDummy(), spell_item_strong_anti_venom::HandleDummy(), spell_item_anti_venom::HandleDummy(), spell_dk_hungering_cold::HandleProc(), ArenaSpectator::HandleResetCommand(), Unit::IsImmunedToSpell(), LoadAuraState(), LoadSpellSpecific(), Unit::MagicSpellHitResult(), Unit::ModSpellDuration(), and SpellInfo().
DmgClass
uint32 SpellInfo::DmgClass
Definition at line 383 of file SpellInfo.h.
Referenced by Unit::CalculateSpellDamageTaken(), Spell::CheckItems(), Spell::CheckRange(), createProcFlags(), Spell::DoAllEffectOnLaunchTarget(), Spell::DoAllEffectOnTarget(), Spell::EffectTriggerSpell(), Unit::MeleeSpellHitResult(), Unit::ModSpellCastTime(), Spell::prepareDataForTriggerSystem(), Spell::SearchChainTargets(), Spell::SelectExplicitTargets(), Spell::Spell(), Unit::SpellCriticalDamageBonus(), Unit::SpellCriticalHealingBonus(), Unit::SpellDamageBonusDone(), Unit::SpellDoneCritChance(), Unit::SpellHealingBonusDone(), Unit::SpellHealingBonusTaken(), Unit::SpellHitResult(), SpellInfo(), and Unit::SpellTakenCritChance().
DurationEntry
SpellDurationEntry const* SpellInfo::DurationEntry
Definition at line 356 of file SpellInfo.h.
Referenced by Aura::CalcMaxDuration(), GetDuration(), GetMaxDuration(), boss_onyxia::boss_onyxiaAI::SpellHitTarget(), and SpellInfo().
Effects
std::array<SpellEffectInfo, MAX_SPELL_EFFECTS> SpellInfo::Effects
Definition at line 387 of file SpellInfo.h.
Referenced by Player::_addSpell(), Player::_addTalentAurasAndSpells(), Spell::_handle_immediate_phase(), _InitializeExplicitTargetMask(), _IsPositiveEffect(), Player::_removeTalentAurasAndSpells(), _UnloadImplicitTargetConditionLists(), spell_dk_will_of_the_necropolis::Absorb(), Spell::AddGOTarget(), Spell::AddItemTarget(), ObjectMgr::AddSpellToTrainer(), ConditionMgr::addToSpellImplicitTargetConditions(), Spell::AddUnitTarget(), Player::ApplyEquipSpell(), Aura::BuildEffectMaskForOwner(), Unit::CalcAbsorbResist(), ThreatCalcHelper::calcThreat(), spell_dk_anti_magic_zone::CalculateAmount(), spell_pal_sacred_shield_base::CalculateAmount(), AuraEffect::CalculateAmount(), spell_krystallus_shatter_effect::spell_krystallus_shatter_effect_SpellScript::CalculateDamage(), spell_gruul_shatter_effect::spell_gruul_shatter_effect_SpellScript::CalculateDamage(), spell_igb_incinerating_blast::spell_igb_incinerating_blast_SpellScript::CalculateDamage(), Spell::CalculateJumpSpeeds(), AuraEffect::CalculatePeriodic(), spell_dru_treant_scaling::CalculateResistanceAmount(), spell_hun_generic_scaling::CalculateResistanceAmount(), spell_mage_pet_scaling::CalculateResistanceAmount(), spell_pri_shadowfiend_scaling::CalculateResistanceAmount(), spell_sha_feral_spirit_scaling::CalculateResistanceAmount(), spell_sha_fire_elemental_scaling::CalculateResistanceAmount(), spell_warl_generic_scaling::CalculateResistanceAmount(), spell_warl_infernal_scaling::CalculateResistanceAmount(), Unit::CalculateSpellDamage(), AuraEffect::CalculateSpellMod(), spell_dk_pet_scaling::CalculateStatAmount(), spell_dru_treant_scaling::CalculateStatAmount(), spell_hun_generic_scaling::CalculateStatAmount(), spell_mage_pet_scaling::CalculateStatAmount(), spell_pri_shadowfiend_scaling::CalculateStatAmount(), spell_sha_feral_spirit_scaling::CalculateStatAmount(), spell_sha_fire_elemental_scaling::CalculateStatAmount(), spell_warl_generic_scaling::CalculateStatAmount(), spell_warl_infernal_scaling::CalculateStatAmount(), Spell::CanAutoCast(), Spell::CanExecuteTriggersOnHit(), Spell::CanOpenLock(), Aura::CanStackWith(), GameObject::CastSpell(), _SpellScript::EffectNameCheck::Check(), _SpellScript::EffectAuraNameCheck::Check(), spell_mage_ice_barrier::CheckCast(), spell_pri_power_word_shield::CheckCast(), Spell::CheckCast(), Spell::CheckCasterAuras(), SpellScript::TargetHook::CheckEffect(), Spell::CheckEffectTarget(), Spell::CheckItems(), spell_hun_ascpect_of_the_viper::CheckProc(), CheckShapeshift(), spell_rotface_unstable_ooze_explosion::spell_rotface_unstable_ooze_explosion_SpellScript::CheckTarget(), spell_hun_lock_and_load::CheckTrapProc(), AuraEffect::CleanupTriggeredSpells(), ComputeIsCritCapable(), SpellMgr::ComputeIsSpellValid(), ComputeIsStackableWithRanks(), Spell::DoAllEffectOnLaunchTarget(), Spell::DoAllEffectOnTarget(), Spell::DoSpellHitOnUnit(), Spell::EffectActivateRune(), Spell::EffectAddFarsight(), Spell::EffectApplyGlyph(), Spell::EffectBind(), Spell::EffectCastButtons(), Spell::EffectCreateItem(), Spell::EffectCreateItem2(), Spell::EffectCreateTamedPet(), Spell::EffectDiscoverTaxi(), Spell::EffectDispel(), Spell::EffectDispelMechanic(), Spell::EffectDuel(), Spell::EffectDurabilityDamage(), Spell::EffectDurabilityDamagePCT(), Spell::EffectEnchantHeldItem(), Spell::EffectEnchantItemPerm(), Spell::EffectEnchantItemPrismatic(), Spell::EffectEnchantItemTmp(), Spell::EffectEnergize(), Spell::EffectEnergizePct(), Spell::EffectFeedPet(), Spell::EffectForceCast(), Spell::EffectForceDeselect(), Spell::EffectGameObjectSetDestructionState(), Spell::EffectInterruptCast(), Spell::EffectKillCredit(), Spell::EffectKillCreditPersonal(), Spell::EffectKnockBack(), Spell::EffectLeapBack(), Spell::EffectLearnPetSpell(), Spell::EffectLearnSkill(), Spell::EffectLearnSpell(), Spell::EffectPersistentAA(), Spell::EffectPlayMusic(), Spell::EffectPlaySound(), Spell::EffectPowerBurn(), Spell::EffectPowerDrain(), Spell::EffectPullTowards(), Spell::EffectQuestClear(), Spell::EffectQuestComplete(), Spell::EffectQuestFail(), Spell::EffectQuestStart(), Spell::EffectRechargeManaGem(), Spell::EffectRemoveAura(), Spell::EffectReputation(), Spell::EffectResurrectNew(), Spell::EffectSanctuary(), Spell::EffectSchoolDMG(), Spell::EffectScriptEffect(), Spell::EffectSelfResurrect(), Spell::EffectSendEvent(), Spell::EffectSendTaxi(), Spell::EffectStealBeneficialBuff(), Spell::EffectSummonChangeItem(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectSummonPet(), Spell::EffectSummonType(), Spell::EffectTransmitted(), Spell::EffectTriggerMissileSpell(), Spell::EffectTriggerRitualOfSummoning(), Spell::EffectTriggerSpell(), Spell::EffectUnlearnSpecialization(), Spell::EffectWeaponDmg(), EquippedOk(), UnitAI::FillAISpellInfo(), ScriptMgr::FillSpellSummary(), UnitAura::FillTargetMap(), GetAllEffectsMechanicMask(), GetAuraRankForLevel(), AuraEffect::GetAuraType(), Unit::GetCastingTimeForBonus(), GetDiminishingReturnsGroupForSpell(), GetEffectMechanic(), GetEffectMechanicMask(), npc_firework::npc_fireworkAI::GetFireworkGameObjectId(), spell_dk_raise_dead::GetGhoulSpellId(), GetMaxTicks(), Unit::GetMechanicResistChance(), AuraEffect::GetMiscValue(), AuraEffect::GetMiscValueB(), GetSpellMechanicMaskByEffectMask(), go_soulwell::go_soulwellAI::go_soulwellAI(), AuraEffect::HandleAuraLinked(), Unit::HandleAuraProc(), Unit::HandleAuraRaidProcFromCharge(), Unit::HandleAuraRaidProcFromChargeWithValue(), WorldSession::HandleCastSpellOpcode(), spell_dru_lifebloom::HandleDispel(), spell_gen_oracle_wolvar_reputation::HandleDummy(), spell_q13086_last_line_of_defence::HandleDummy(), spell_dk_raise_ally::HandleDummy(), spell_q12683_take_sputum_sample::HandleDummy(), Unit::HandleDummyAuraProc(), spell_warr_execute::HandleEffect(), spell_dk_improved_unholy_presence::HandleEffectApply(), spell_dru_idol_lifebloom::HandleEffectCalcSpellMod(), spell_warr_glyph_of_sunder_armor::HandleEffectCalcSpellMod(), spell_rog_prey_on_the_weak::HandleEffectPeriodic(), Spell::HandleEffects(), AuraEffect::HandleFeignDeath(), Spell::HandleLaunchPhase(), lookup_commandscript::HandleLookupSpellCommand(), lookup_commandscript::HandleLookupSpellIdCommand(), spell_putricide_unbound_plague_dmg::spell_putricide_unbound_plague_dmg_AuraScript::HandlePeriodic(), AuraEffect::HandlePeriodicDamageAurasTick(), AuraEffect::HandlePeriodicHealAurasTick(), AuraEffect::HandlePeriodicHealthFunnelAuraTick(), AuraEffect::HandlePeriodicHealthLeechAuraTick(), AuraEffect::HandlePeriodicManaLeechAuraTick(), AuraEffect::HandlePeriodicPowerBurnAuraTick(), AuraEffect::HandlePeriodicTriggerSpellAuraTick(), AuraEffect::HandlePeriodicTriggerSpellWithValueAuraTick(), WorldSession::HandlePetActionHelper(), spell_item_blood_draining_enchant::HandleProc(), spell_dk_blood_caked_blade::HandleProc(), spell_gen_blade_warding::HandleProc(), spell_pal_seal_of_command_aura::HandleProc(), spell_pal_sacred_shield_base::HandleProc(), spell_hun_lock_and_load::HandleProcs(), Unit::HandleProcTriggerSpell(), AuraEffect::HandleProcTriggerSpellAuraProc(), AuraEffect::HandleProcTriggerSpellWithValueAuraProc(), AuraEffect::HandleRaidProcFromChargeAuraProc(), AuraEffect::HandleRaidProcFromChargeWithValueAuraProc(), spell_igb_rocket_pack::spell_igb_rocket_pack_AuraScript::HandleRemove(), Unit::HandleSpellClick(), spell_wintergrasp_create_vehicle::spell_wintergrasp_create_vehicle_SpellScript::HandleSummon(), spell_item_draenic_pale_ale::HandleSummon(), spell_putricide_mutated_plague::spell_putricide_mutated_plague_AuraScript::HandleTriggerSpell(), spell_mage_arcane_blast::HandleTriggerSpell(), Player::Has310Flyer(), HasAnyAura(), HasAnyEffectMechanic(), HasAreaAuraEffect(), HasAura(), Unit::HasAuraWithMechanic(), HasEffect(), AuraEffect::HasSpellClassMask(), ItemTemplate::HasSpellPowerStat(), AuraEffect::IsAffectedOnSpell(), IsAffectingArea(), IsAuraEffectEqual(), IsChannelCategorySpell(), Unit::IsDamageReducedByArmor(), IsExplicitDiscovery(), Unit::IsImmunedToSpell(), Creature::IsImmunedToSpell(), Unit::IsImmunedToSpellEffect(), Creature::IsImmunedToSpellEffect(), Totem::IsImmunedToSpellEffect(), IsLootCrafting(), IsPrimaryProfession(), IsProfession(), IsProfessionOrRiding(), IsQuestTame(), IsSelfCast(), ConditionMgr::isSourceTypeValid(), IsStrongerAuraActive(), IsTargetingArea(), AchievementCriteriaData::IsValid(), Player::learnQuestRewardedSpells(), Player::LearnTalent(), spell_dk_anti_magic_shell_raid::Load(), spell_dk_anti_magic_shell_self::Load(), spell_dk_anti_magic_zone::Load(), spell_dk_spell_deflection::Load(), spell_dk_will_of_the_necropolis::Load(), spell_dru_moonkin_form_passive::Load(), spell_dru_primal_tenacity::Load(), spell_dru_savage_defense::Load(), spell_gen_absorb0_hitlimit1::Load(), spell_pal_ardent_defender::Load(), spell_pal_divine_sacrifice::Load(), spell_pal_divine_storm::Load(), spell_pri_guardian_spirit::Load(), spell_rog_cheat_death::Load(), spell_rog_nerves_of_steel::Load(), spell_sha_astral_shift::Load(), LoadAuraState(), SpellMgr::LoadEnchantCustomAttr(), SpellMgr::LoadPetDefaultSpells(), ObjectMgr::LoadQuests(), SpellMgr::LoadSpellCustomAttr(), SpellMgr::LoadSpellLearnSkills(), SpellMgr::LoadSpellPetAuras(), ObjectMgr::LoadSpellScripts(), LoadSpellSpecific(), SpellMgr::LoadSpellTargetPositions(), Unit::MagicSpellHitResult(), Unit::MeleeDamageBonusDone(), spell_gen_random_target32::ModDest(), spell_q12308_escape_from_silverbrook_summon_worgen::ModDest(), NeedsToBeTriggeredByCaster(), spell_kologarn_stone_shout::spell_kologarn_stone_shout_AuraScript::OnPeriodic(), spell_deathwhisper_dark_reckoning::OnPeriodic(), spell_putricide_mutated_plague::spell_putricide_mutated_plague_AuraScript::OnRemove(), spell_blood_queen_pact_of_the_darkfallen_dmg::spell_blood_queen_pact_of_the_darkfallen_dmg_AuraScript::PeriodicTick(), spell_broggok_poison_cloud::spell_broggok_poison_cloud_AuraScript::PeriodicTick(), Spell::prepare(), spell_optic_link::spell_optic_linkAuraScript::PrepareAuraScript(), Player::PrepareCharmAISpells(), Spell::PrepareTriggersExecutedOnHit(), Unit::ProcDamageAndSpellFor(), Creature::reachWithSpellAttack(), Creature::reachWithSpellCure(), spell_wg_reduce_damage_by_distance::spell_wg_reduce_damage_by_distance_SpellScript::RecalculateDamage(), spell_gen_mounted_charge::Register(), spell_gen_defend::Register(), Unit::RemoveMovementImpairingAuras(), Player::removeSpell(), Player::resetTalents(), Spell::SelectEffectImplicitTargets(), Spell::SelectEffectTypeImplicitTargets(), Spell::SelectImplicitAreaTargets(), Spell::SelectImplicitCasterDestTargets(), Spell::SelectImplicitChainTargets(), Spell::SelectImplicitConeTargets(), Spell::SelectImplicitDestDestTargets(), Spell::SelectImplicitNearbyTargets(), Spell::SelectImplicitTargetDestTargets(), Spell::SelectImplicitTrajTargets(), Spell::SelectSpellTargets(), Spell::SendLogExecute(), Spell::SetSpellValue(), Unit::SpellHealingBonusDone(), Unit::SpellHitResult(), boss_onyxia::boss_onyxiaAI::SpellHitTarget(), boss_rotface::boss_rotfaceAI::SpellHitTarget(), SpellInfo(), SpellValue::SpellValue(), Acore::Hyperlinks::LinkTags::trade::StoreTo(), boss_anub_arak::boss_anub_arakAI::SummonHelpers(), go_wind_stone::go_wind_stoneAI::SummonNPC(), Spell::update(), Player::UpdateAttackPowerAndDamage(), Spell::UpdateChanneledTargetList(), spell_deathwhisper_dark_reckoning::Validate(), spell_mage_living_bomb::Validate(), spell_broggok_poison_cloud::spell_broggok_poison_cloud_AuraScript::Validate(), spell_dru_wild_growth::Validate(), spell_gen_eject_passenger::Validate(), and Spell::WriteCastResultInfo().
EquippedItemClass
int32 SpellInfo::EquippedItemClass
Definition at line 370 of file SpellInfo.h.
Referenced by Player::_ApplyWeaponDependentAuraCritMod(), Player::_ApplyWeaponDependentAuraDamageMod(), Spell::CheckItems(), createProcFlags(), Spell::EffectProficiency(), Unit::HandleDummyAuraProc(), Player::HasItemFitToSpellRequirements(), Item::IsFitToSpellRequirements(), Aura::IsProcTriggeredOnEvent(), Unit::IsTriggeredAtSpellProcEvent(), Spell::prepareDataForTriggerSystem(), SpellInfo(), Unit::SpellPctDamageModsDone(), and Spell::WriteCastResultInfo().
EquippedItemInventoryTypeMask
int32 SpellInfo::EquippedItemInventoryTypeMask
Definition at line 372 of file SpellInfo.h.
Referenced by Item::IsFitToSpellRequirements(), and SpellInfo().
EquippedItemSubClassMask
int32 SpellInfo::EquippedItemSubClassMask
Definition at line 371 of file SpellInfo.h.
Referenced by createProcFlags(), Spell::EffectProficiency(), Item::IsFitToSpellRequirements(), IsRangedWeaponSpell(), Unit::IsTriggeredAtSpellProcEvent(), Spell::prepareDataForTriggerSystem(), SpellInfo(), and Spell::WriteCastResultInfo().
ExcludeCasterAuraSpell
uint32 SpellInfo::ExcludeCasterAuraSpell
Definition at line 340 of file SpellInfo.h.
Referenced by Spell::CheckCast(), Spell::PrepareTriggersExecutedOnHit(), and SpellInfo().
ExcludeTargetAuraSpell
uint32 SpellInfo::ExcludeTargetAuraSpell
Definition at line 341 of file SpellInfo.h.
Referenced by CheckTarget(), spell_valkyr_touch::spell_valkyr_touchAuraScript::PrepareAuraScript(), Spell::PrepareTriggersExecutedOnHit(), SpellInfo(), and spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript::Validate().
ExplicitTargetMask
uint32 SpellInfo::ExplicitTargetMask
Definition at line 388 of file SpellInfo.h.
Referenced by _InitializeExplicitTargetMask(), GetExplicitTargetMask(), and SpellInfo().
FacingCasterFlags
uint32 SpellInfo::FacingCasterFlags
Definition at line 333 of file SpellInfo.h.
Referenced by Spell::CheckRange(), and SpellInfo().
Id
uint32 SpellInfo::Id
Definition at line 315 of file SpellInfo.h.
Referenced by Player::_addSpell(), Spell::_cast(), Unit::_CreateAuraApplication(), _IsPositiveEffect(), Pet::_LoadAuras(), Player::_LoadAuras(), Unit::_TryStackingOrRefreshingExistingAura(), Aura::_UnapplyForTarget(), Unit::_UpdateAutoRepeatSpell(), _SpellScript::_Validate(), SpellScript::_Validate(), AuraScript::_Validate(), boss_grand_champion::boss_grand_championAI::AddCreatureAddonAuras(), AddItemsSetItem(), Player::addSpell(), Player::AddSpellAndCategoryCooldowns(), Creature::AddSpellCooldown(), CharmInfo::AddSpellToActionBar(), Unit::ApplyEffectModifiers(), Player::ApplyEquipSpell(), Unit::ApplySpellDispelImmunity(), Unit::CalcAbsorbResist(), Unit::CalcArmorReducedDamage(), SpellEffectInfo::CalcDamageMultiplier(), CalcPowerCost(), SpellEffectInfo::CalcRadius(), ThreatCalcHelper::calcThreat(), AuraEffect::CalculateAmount(), Unit::CalculateSpellDamageTaken(), SpellEffectInfo::CalcValueMultiplier(), Spell::CanAutoCast(), Spell::cancel(), Spell::CanOpenLock(), Aura::CanStackWith(), Player::CastItemCombatSpell(), Player::CastItemUseSpell(), spell_yogg_saron_in_the_maws_of_the_old_god::spell_yogg_saron_in_the_maws_of_the_old_god_SpellScript::CheckCast(), Spell::CheckCast(), Spell::CheckCasterAuras(), Spell::CheckEffectTarget(), CheckLocation(), Spell::CheckPetCast(), spell_sindragosa_unchained_magic::spell_sindragosa_unchained_magic_AuraScript::CheckProc(), spell_dk_dancing_rune_weapon::CheckProc(), spell_mage_brain_freeze::CheckProc(), spell_mage_master_of_elements::CheckProc(), spell_warr_improved_spell_reflection::CheckProc(), Spell::CheckRange(), Spell::CheckRuneCost(), CheckShapeshift(), cast_commandscript::CheckSpellExistsAndIsValid(), SpellMgr::CheckSpellGroupStackRules(), SpellMgr::ComputeIsSpellValid(), Unit::DealDamage(), Unit::DealMeleeDamage(), Spell::Delayed(), Spell::DelayedChannel(), Spell::DoAllEffectOnLaunchTarget(), Spell::DoAllEffectOnTarget(), Spell::DoCreateItem(), Spell::DoSpellHitOnUnit(), Spell::DoTriggersOnSpellHit(), Spell::EffectActivateRune(), Spell::EffectAddComboPoints(), Spell::EffectAddFarsight(), Spell::EffectAddHonor(), Spell::EffectCreateItem2(), Spell::EffectCreateRandomItem(), Spell::EffectCreateTamedPet(), Spell::EffectDisEnchant(), Spell::EffectDispel(), Spell::EffectDuel(), Spell::EffectDummy(), Spell::EffectEnchantHeldItem(), Spell::EffectEnchantItemPerm(), Spell::EffectEnchantItemPrismatic(), Spell::EffectEnchantItemTmp(), Spell::EffectEnergize(), Spell::EffectEnergizePct(), Spell::EffectForceCast(), Spell::EffectForceDeselect(), Spell::EffectHeal(), Spell::EffectInstaKill(), Spell::EffectInterruptCast(), Spell::EffectJumpDest(), Spell::EffectKillCredit(), Spell::EffectLearnPetSpell(), Spell::EffectLearnSpell(), Spell::EffectOpenLock(), Spell::EffectPersistentAA(), Spell::EffectPlayMusic(), Spell::EffectPlaySound(), Spell::EffectPowerBurn(), Spell::EffectPowerDrain(), Spell::EffectSanctuary(), Spell::EffectSchoolDMG(), Spell::EffectScriptEffect(), Spell::EffectSendEvent(), Spell::EffectSendTaxi(), Spell::EffectStealBeneficialBuff(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectSummonPet(), Spell::EffectSummonType(), Spell::EffectTameCreature(), Spell::EffectTaunt(), Spell::EffectTeleportUnits(), Spell::EffectTransmitted(), Spell::EffectTriggerMissileSpell(), Spell::EffectTriggerRitualOfSummoning(), Spell::EffectTriggerSpell(), Spell::EffectWeaponDmg(), Spell::finish(), GetDiminishingReturnsGroupForSpell(), AuraEffect::GetId(), Aura::GetId(), GetMaxRange(), Unit::GetPPMProcChance(), SpellMgr::GetSpellForDifficultyFromSpell(), Spell::handle_immediate(), spell_igb_on_gunship_deck::spell_igb_on_gunship_deck_AuraScript::HandleApply(), AuraEffect::HandleAuraDummy(), AuraEffect::HandleAuraModSchoolImmunity(), Unit::HandleAuraProc(), Unit::HandleAuraRaidProcFromCharge(), Unit::HandleAuraRaidProcFromChargeWithValue(), Aura::HandleAuraSpecificMods(), cast_commandscript::HandleCastBackCommand(), cast_commandscript::HandleCastCommand(), cast_commandscript::HandleCastDestCommand(), cast_commandscript::HandleCastDistCommand(), cast_commandscript::HandleCastSelfCommand(), cast_commandscript::HandleCastTargetCommad(), spell_hun_readiness::HandleDummy(), spell_mage_cold_snap::HandleDummy(), spell_rog_preparation::HandleDummy(), Unit::HandleDummyAuraProc(), Spell::HandleEffects(), learn_commandscript::HandleLearnAllMySpellsCommand(), Acore::PlayerCommand::HandleLearnSpellCommand(), lookup_commandscript::HandleLookupSpellIdCommand(), AuraEffect::HandlePeriodicDummyAuraTick(), AuraEffect::HandlePeriodicTriggerSpellAuraTick(), WorldSession::HandlePetCancelAuraOpcode(), spell_deathbringer_blood_link_aura::spell_deathbringer_blood_link_AuraScript::HandleProc(), spell_item_blood_draining_enchant::HandleProc(), Unit::HandleProcTriggerSpell(), ArenaSpectator::HandleResetCommand(), spell_dreamwalker_summon_portal::spell_dreamwalker_summon_portal_SpellScript::HandleScript(), spell_gen_profession_research::HandleScript(), spell_gen_dalaran_disguise::HandleScript(), spell_item_book_of_glyph_mastery::HandleScript(), spell_capacitus_polarity_charge::spell_capacitus_polarity_charge_SpellScript::HandleTargets(), spell_thaddius_pos_neg_charge::spell_thaddius_pos_neg_charge_SpellScript::HandleTargets(), Spell::HandleThreatSpells(), Acore::PlayerCommand::HandleUnlearnSpellCommand(), WorldSession::HandleUpdateMissileTrajectory(), Unit::HealBySpell(), Pet::InitLevelupSpellsForLevel(), IsAbilityLearnedWithProfession(), IsAbilityOfSkillType(), IsDifferentRankOf(), IsExplicitDiscovery(), Unit::IsImmunedToSchool(), Unit::IsImmunedToSpell(), Totem::IsImmunedToSpellEffect(), IsMultiSlotAura(), IsStrongerAuraActive(), LinkValidator< LinkTags::enchant >::IsTextValid(), Unit::IsTriggeredAtSpellProcEvent(), LoadAuraState(), LoadLootTemplates_Spell(), SpellMgr::LoadPetLevelupSpellMap(), ObjectMgr::LoadQuests(), Aura::LoadScripts(), Spell::LoadScripts(), SpellMgr::LoadSpellCustomAttr(), SpellMgr::LoadSpellProcEvents(), SpellMgr::LoadSpellProcs(), ObjectMgr::LoadSpellScriptNames(), LoadSpellSpecific(), Unit::MagicSpellHitResult(), Unit::MeleeDamageBonusDone(), Unit::MeleeSpellHitResult(), Unit::ModSpellCastTime(), NeedsToBeTriggeredByCaster(), spell_xt002_gravity_bomb_aura::spell_xt002_gravity_bomb_aura_AuraScript::OnRemove(), Spell::OnSpellLaunch(), Acore::AbsorbAuraOrderPred::operator()(), Unit::PetSpellFail(), Spell::prepare(), Player::PrepareCharmAISpells(), Spell::prepareDataForTriggerSystem(), Spell::PrepareTriggersExecutedOnHit(), Unit::ProcDamageAndSpellFor(), SmartScript::ProcessEvent(), spell_pri_power_word_shield_aura::ReflectDamage(), RemoveItemsSetItem(), Spell::SelectEffectImplicitTargets(), Spell::SelectImplicitCasterDestTargets(), Spell::SelectImplicitChainTargets(), Spell::SelectImplicitChannelTargets(), Spell::SelectImplicitNearbyTargets(), Spell::SendChannelStart(), Player::SendCooldownEvent(), Spell::SendInterrupted(), Spell::SendLogExecute(), Spell::SendSpellCooldown(), Spell::SendSpellGo(), Spell::SendSpellStart(), AuraEffect::SendTickImmune(), Unit::SetCurrentCastedSpell(), boss_mimiron::boss_mimironAI::SetData(), CharmInfo::SetSpellAutocast(), Player::SetSpellModTakingSpell(), list_commandscript::ShouldListAura(), Unit::SpellCriticalDamageBonus(), Unit::SpellCriticalHealingBonus(), Unit::SpellDamageBonusDone(), Unit::SpellDamageBonusTaken(), Unit::SpellDoneCritChance(), Unit::SpellHealingBonusDone(), Unit::SpellHealingBonusTaken(), npc_kerlonian::npc_kerlonianAI::SpellHit(), npc_ringo::npc_ringoAI::SpellHit(), netherspite_infernal::netherspite_infernalAI::SpellHit(), npc_mograine::npc_mograineAI::SpellHit(), boss_halazzi::boss_halazziAI::SpellHit(), npc_janalai_firebomb::npc_janalai_firebombAI::SpellHit(), npc_janalai_egg::npc_janalai_eggAI::SpellHit(), npc_harrison_jones::npc_harrison_jonesAI::SpellHit(), npc_omen::npc_omenAI::SpellHit(), npc_taskmaster_fizzule::npc_taskmaster_fizzuleAI::SpellHit(), boss_eadric::boss_eadricAI::SpellHit(), npc_black_knight_ghoul::npc_black_knight_ghoulAI::SpellHit(), boss_grand_champion::boss_grand_championAI::SpellHit(), npc_frost_sphere::npc_frost_sphereAI::SpellHit(), boss_malygos::boss_malygosAI::SpellHit(), boss_urom::boss_uromAI::SpellHit(), boss_ionar::boss_ionarAI::SpellHit(), npc_ulduar_toasty_fire::npc_ulduar_toasty_fireAI::SpellHit(), npc_ulduar_hodir_priest::npc_ulduar_hodir_priestAI::SpellHit(), npc_ulduar_hodir_druid::npc_ulduar_hodir_druidAI::SpellHit(), npc_ulduar_hodir_shaman::npc_ulduar_hodir_shamanAI::SpellHit(), npc_ulduar_hodir_mage::npc_ulduar_hodir_mageAI::SpellHit(), npc_ulduar_iron_construct::npc_ulduar_iron_constructAI::SpellHit(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::SpellHit(), npc_ulduar_vx001::npc_ulduar_vx001AI::SpellHit(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::SpellHit(), npc_ulduar_flames_spread::npc_ulduar_flames_spreadAI::SpellHit(), npc_ichor_globule::npc_ichor_globuleAI::SpellHit(), npc_captured_rageclaw::npc_captured_rageclawAI::SpellHit(), npc_infernal_attacker::npc_infernal_attackerAI::SpellHit(), npc_shadowmoon_tuber_node::npc_shadowmoon_tuber_nodeAI::SpellHit(), boss_attumen::boss_attumenAI::SpellHit(), npc_balance_of_light_and_shadow::npc_balance_of_light_and_shadowAI::SpellHit(), npc_dark_iron_guzzler::npc_dark_iron_guzzlerAI::SpellHit(), boss_headless_horseman::boss_headless_horsemanAI::SpellHit(), boss_headless_horseman_pumpkin::boss_headless_horseman_pumpkinAI::SpellHit(), npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::SpellHit(), npc_pilgrims_bounty_plate::npc_pilgrims_bounty_plateAI::SpellHit(), boss_gothik::boss_gothikAI::SpellHit(), boss_steelbreaker::boss_steelbreakerAI::SpellHit(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::SpellHit(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::SpellHit(), boss_thorim_pillar::boss_thorim_pillarAI::SpellHit(), boss_thorim_runic_colossus::boss_thorim_runic_colossusAI::SpellHit(), boss_yoggsaron::boss_yoggsaronAI::SpellHit(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::SpellHit(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::SpellHit(), npc_crate_helper::npc_crate_helperAI::SpellHit(), boss_prince_keleseth_icc::boss_prince_kelesethAI::SpellHit(), boss_prince_taldaram_icc::boss_prince_taldaramAI::SpellHit(), boss_prince_valanar_icc::boss_prince_valanarAI::SpellHit(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::SpellHit(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::SpellHit(), npc_saurfang_event::npc_saurfang_eventAI::SpellHit(), npc_cult_fanatic::npc_cult_fanaticAI::SpellHit(), npc_cult_adherent::npc_cult_adherentAI::SpellHit(), npc_putricide_oozeAI::SpellHit(), boss_the_lich_king::boss_the_lich_kingAI::SpellHit(), npc_tirion_fordring_tft::npc_tirion_fordringAI::SpellHit(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::SpellHit(), npc_argent_captainAI::SpellHit(), npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::SpellHit(), npc_vics_flying_machine::npc_vics_flying_machineAI::SpellHit(), npc_venomhide_hatchling::npc_venomhide_hatchlingAI::SpellHit(), boss_majordomo::boss_majordomoAI::SpellHit(), npc_midsummer_bonfire::npc_midsummer_bonfireAI::SpellHit(), npc_isle_of_conquest_turret::npc_isle_of_conquest_turretAI::SpellHit(), boss_twinemperorsAI::SpellHit(), npc_death_knight_initiate::npc_death_knight_initiateAI::SpellHit(), npc_crusade_persuaded::npc_crusade_persuadedAI::SpellHit(), npc_yenniku::npc_yennikuAI::SpellHit(), npc_zuljin_vortex::npc_zuljin_vortexAI::SpellHit(), boss_jaraxxus::boss_jaraxxusAI::SpellHit(), boss_faerlina::boss_faerlinaAI::SpellHit(), boss_ignis::boss_ignisAI::SpellHit(), boss_razorscale::boss_razorscaleAI::SpellHit(), npc_sinkhole_kill_credit::npc_sinkhole_kill_creditAI::SpellHit(), npc_torturer_lecraft::npc_torturer_lecraftAI::SpellHit(), npc_wounded_skirmisher::npc_wounded_skirmisherAI::SpellHit(), npc_brunnhildar_prisoner::npc_brunnhildar_prisonerAI::SpellHit(), npc_drakuru_shackles::npc_drakuru_shacklesAI::SpellHit(), npc_storm_cloud::npc_storm_cloudAI::SpellHit(), npc_nether_drake::npc_nether_drakeAI::SpellHit(), npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI::SpellHit(), npc_dragonmaw_peon::npc_dragonmaw_peonAI::SpellHit(), npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::SpellHit(), npc_soh_fire_trigger::npc_soh_fire_triggerAI::SpellHit(), npc_hallows_end_train_fire::npc_hallows_end_train_fireAI::SpellHit(), boss_headless_horseman_head::boss_headless_horseman_headAI::SpellHit(), npc_cos_stratholme_citizien::npc_cos_stratholme_citizienAI::SpellHit(), boss_magus_telestra::boss_magus_telestraAI::SpellHit(), boss_flame_leviathan::boss_flame_leviathanAI::SpellHit(), boss_thorim::boss_thorimAI::SpellHit(), boss_yoggsaron_immortal_guardian::boss_yoggsaron_immortal_guardianAI::SpellHit(), npc_attracted_reef_bull::npc_attracted_reef_bullAI::SpellHit(), npc_iron_watcher::npc_iron_watcherAI::SpellHit(), npc_wild_wyrm::npc_wild_wyrmAI::SpellHit(), npc_forest_frog::npc_forest_frogAI::SpellHit(), npc_zulian_prowler::npc_zulian_prowlerAI::SpellHit(), boss_ossirian::boss_ossirianAI::SpellHit(), npc_aged_dying_ancient_kodo::npc_aged_dying_ancient_kodoAI::SpellHit(), npc_troll_volunteer::npc_troll_volunteerAI::SpellHit(), boss_sister_svalna::boss_sister_svalnaAI::SpellHit(), boss_razuvious::boss_razuviousAI::SpellHit(), npc_living_constellation::npc_living_constellationAI::SpellHit(), npc_venture_co_straggler::npc_venture_co_stragglerAI::SpellHit(), npc_tournament_training_dummy::npc_tournament_training_dummyAI::SpellHit(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::SpellHit(), npc_injured_patient::npc_injured_patientAI::SpellHit(), npc_garments_of_quests::npc_garments_of_questsAI::SpellHit(), npc_greengill_slave::npc_greengill_slaveAI::SpellHit(), npc_midsummer_torch_target::npc_midsummer_torch_targetAI::SpellHit(), npc_shay_leafrunner::npc_shay_leafrunnerAI::SpellHit(), npc_jungle_punch_target::npc_jungle_punch_targetAI::SpellHit(), npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::SpellHit(), npc_spitelashes::npc_spitelashesAI::SpellHit(), npc_beryl_sorcerer::npc_beryl_sorcererAI::SpellHit(), npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI::SpellHit(), boss_black_knight::boss_black_knightAI::SpellHitTarget(), boss_bronjahm::boss_bronjahmAI::SpellHitTarget(), boss_garfrost::boss_garfrostAI::SpellHitTarget(), npc_maghar_captive::npc_maghar_captiveAI::SpellHitTarget(), npc_kurenai_captive::npc_kurenai_captiveAI::SpellHitTarget(), boss_quartermaster_zigris::SpellHitTarget(), npc_demonic_vapor_trail::npc_demonic_vapor_trailAI::SpellHitTarget(), boss_headless_horseman_head::boss_headless_horseman_headAI::SpellHitTarget(), boss_taldaram::boss_taldaramAI::SpellHitTarget(), boss_moorabi::boss_moorabiAI::SpellHitTarget(), boss_volkhan::boss_volkhanAI::SpellHitTarget(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::SpellHitTarget(), boss_ymiron::boss_ymironAI::SpellHitTarget(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::SpellHitTarget(), npc_vengeful_shade::npc_vengeful_shadeAI::SpellHitTarget(), npc_putricide_oozeAI::SpellHitTarget(), boss_the_lich_king::boss_the_lich_kingAI::SpellHitTarget(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::SpellHitTarget(), npc_black_knight_ghoul::npc_black_knight_ghoulAI::SpellHitTarget(), npc_nerubian_burrower::npc_nerubian_burrowerAI::SpellHitTarget(), boss_devourer_of_souls::boss_devourer_of_soulsAI::SpellHitTarget(), npc_hor_lich_king::npc_hor_lich_kingAI::SpellHitTarget(), boss_ick::boss_ickAI::SpellHitTarget(), npc_pos_collapsing_icicle::npc_pos_collapsing_icicleAI::SpellHitTarget(), npc_pos_leader_second::npc_pos_leader_secondAI::SpellHitTarget(), boss_lord_marrowgar::SpellHitTarget(), npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::SpellHitTarget(), boss_freya::boss_freyaAI::SpellHitTarget(), boss_vezax::boss_vezaxAI::SpellHitTarget(), boss_hodir::boss_hodirAI::SpellHitTarget(), npc_ulduar_hodir_shaman::npc_ulduar_hodir_shamanAI::SpellHitTarget(), npc_ulduar_proximity_mine::npc_ulduar_proximity_mineAI::SpellHitTarget(), npc_ulduar_rocket_strike_trigger::npc_ulduar_rocket_strike_triggerAI::SpellHitTarget(), boss_cyanigosa::boss_cyanigosaAI::SpellHitTarget(), npc_simon_bunny::npc_simon_bunnyAI::SpellHitTarget(), boss_attumen::boss_attumenAI::SpellHitTarget(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::SpellHitTarget(), boss_headless_horseman::boss_headless_horsemanAI::SpellHitTarget(), npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::SpellHitTarget(), boss_epoch::boss_epochAI::SpellHitTarget(), boss_grobbulus::boss_grobbulusAI::SpellHitTarget(), boss_sapphiron::boss_sapphironAI::SpellHitTarget(), boss_thorim::boss_thorimAI::SpellHitTarget(), npc_xt002_heart::npc_xt002_heartAI::SpellHitTarget(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::SpellHitTarget(), boss_yoggsaron_voice::boss_yoggsaron_voiceAI::SpellHitTarget(), boss_skadi_grauf::boss_skadi_graufAI::SpellHitTarget(), boss_emalon::boss_emalonAI::SpellHitTarget(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::SpellHitTarget(), boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI::SpellHitTarget(), npc_pet_gen_soul_trader_beacon::SpellHitTarget(), npc_pet_gen_fetch_ball::SpellHitTarget(), boss_festergut::boss_festergutAI::SpellHitTarget(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::SpellHitTarget(), boss_rotface::boss_rotfaceAI::SpellHitTarget(), boss_sindragosa::boss_sindragosaAI::SpellHitTarget(), boss_sister_svalna::boss_sister_svalnaAI::SpellHitTarget(), npc_oculus_drake::npc_oculus_drakeAI::SpellHitTarget(), boss_flame_leviathan::boss_flame_leviathanAI::SpellHitTarget(), npc_q24545_lich_king::npc_q24545_lich_kingAI::SpellHitTarget(), boss_lethon::boss_lethonAI::SpellHitTarget(), SpellInfo(), Unit::SpellPctHealingModsDone(), Spell::SummonGuardian(), go_wind_stone::go_wind_stoneAI::SummonNPC(), Spell::TakePower(), Spell::TakeRunePower(), Pet::ToggleAutocast(), CharmInfo::ToggleCreatureAutocast(), Spell::TriggerGlobalCooldown(), Spell::update(), PetAI::UpdateAI(), Spell::UpdateChanneledTargetList(), spell_gen_dalaran_disguise::Validate(), ValidateAttribute6SpellDamageMods(), ObjectMgr::ValidateSpellScripts(), Spell::WriteCastResultInfo(), Spell::~Spell(), and SpellEvent::~SpellEvent().
InterruptFlags
uint32 SpellInfo::InterruptFlags
Definition at line 347 of file SpellInfo.h.
Referenced by Spell::EffectInterruptCast(), Spell::IsAutoActionResetSpell(), Spell::prepare(), SpellInfo(), and Spell::update().
ManaCost
uint32 SpellInfo::ManaCost
Definition at line 358 of file SpellInfo.h.
Referenced by CalcPowerCost(), spell_dru_omen_of_clarity::CheckProc(), spell_gen_allow_proc_from_spells_with_cost::CheckProc(), spell_item_essence_of_life::CheckProc(), Spell::EffectDestroyAllTotems(), Unit::HandleDummyAuraProc(), Unit::HandleProcTriggerSpell(), Unit::ProcDamageAndSpellFor(), Creature::reachWithSpellAttack(), Creature::reachWithSpellCure(), ScriptedAI::SelectSpell(), and SpellInfo().
ManaCostPercentage
uint32 SpellInfo::ManaCostPercentage
Definition at line 362 of file SpellInfo.h.
Referenced by spell_dru_lifebloom::AfterRemove(), CalcPowerCost(), spell_dru_omen_of_clarity::CheckProc(), spell_gen_allow_proc_from_spells_with_cost::CheckProc(), spell_item_essence_of_life::CheckProc(), Spell::EffectDestroyAllTotems(), AuraEffect::HandlePeriodicManaLeechAuraTick(), Unit::HandleProcTriggerSpell(), Unit::ProcDamageAndSpellFor(), and SpellInfo().
ManaCostPerlevel
uint32 SpellInfo::ManaCostPerlevel
Definition at line 359 of file SpellInfo.h.
Referenced by Unit::HandleProcTriggerSpell(), and SpellInfo().
ManaPerSecond
uint32 SpellInfo::ManaPerSecond
Definition at line 360 of file SpellInfo.h.
Referenced by Aura::Aura(), AuraEffect::HandlePeriodicHealAurasTick(), Aura::RefreshDuration(), SpellInfo(), and Aura::Update().
ManaPerSecondPerLevel
uint32 SpellInfo::ManaPerSecondPerLevel
Definition at line 361 of file SpellInfo.h.
Referenced by Aura::Aura(), Aura::RefreshDuration(), SpellInfo(), and Aura::Update().
MaxAffectedTargets
uint32 SpellInfo::MaxAffectedTargets
Definition at line 380 of file SpellInfo.h.
Referenced by spell_pal_glyph_of_holy_light::FilterTargets(), SpellInfo(), and SpellValue::SpellValue().
MaxLevel
uint32 SpellInfo::MaxLevel
Definition at line 353 of file SpellInfo.h.
Referenced by Unit::CalculateLevelPenalty(), SpellEffectInfo::CalcValue(), Spell::CheckItems(), and SpellInfo().
MaxTargetLevel
uint32 SpellInfo::MaxTargetLevel
Definition at line 379 of file SpellInfo.h.
Referenced by SpellInfo().
Mechanic
uint32 SpellInfo::Mechanic
Definition at line 318 of file SpellInfo.h.
Referenced by _IsPositiveEffect(), CanDispelAura(), CanPierceImmuneAura(), Spell::CheckCast(), CheckTarget(), GetAllEffectsMechanicMask(), GetEffectMechanic(), GetEffectMechanicMask(), GetSpellMechanicMaskByEffectMask(), HasAnyEffectMechanic(), Unit::HasAuraWithMechanic(), Unit::IsImmunedToSpell(), Creature::IsImmunedToSpell(), LoadSkillDiscoveryTable(), Unit::ProcDamageAndSpellFor(), Unit::RemoveMovementImpairingAuras(), ScriptedAI::SelectSpell(), boss_attumen::boss_attumenAI::SpellHit(), boss_attumen_midnight::boss_attumen_midnightAI::SpellHit(), SpellInfo(), Player::UpdateCraftSkill(), and Spell::WriteCastResultInfo().
PowerType
uint32 SpellInfo::PowerType
Definition at line 357 of file SpellInfo.h.
Referenced by Spell::CheckPower(), Spell::CheckRuneCost(), Unit::HandleProcTriggerSpell(), SmartScript::OnInitialize(), ScriptedAI::SelectSpell(), Spell::SendSpellGo(), Spell::SendSpellStart(), Spell::TakePower(), and Aura::Update().
PreventionType
uint32 SpellInfo::PreventionType
Definition at line 384 of file SpellInfo.h.
Referenced by Spell::CheckCast(), Spell::CheckCasterAuras(), Spell::EffectInterruptCast(), Player::ProhibitSpellSchool(), Creature::reachWithSpellAttack(), Creature::reachWithSpellCure(), and SpellInfo().
ProcChance
uint32 SpellInfo::ProcChance
Definition at line 351 of file SpellInfo.h.
Referenced by Player::CastItemCombatSpell(), Unit::HandleDummyAuraProc(), Unit::IsTriggeredAtSpellProcEvent(), SpellMgr::LoadSpellProcs(), and SpellInfo().
ProcCharges
uint32 SpellInfo::ProcCharges
Definition at line 352 of file SpellInfo.h.
Referenced by Pet::_LoadAuras(), Player::_LoadAuras(), Aura::CalcMaxCharges(), SpellMgr::LoadSpellProcs(), and SpellInfo().
ProcFlags
uint32 SpellInfo::ProcFlags
Definition at line 350 of file SpellInfo.h.
Referenced by AuraEffect::CalculateAmount(), Unit::IsTriggeredAtSpellProcEvent(), SpellMgr::LoadSpellProcEvents(), and SpellMgr::LoadSpellProcs().
RangeEntry
SpellRangeEntry const* SpellInfo::RangeEntry
Definition at line 364 of file SpellInfo.h.
Referenced by Spell::CheckRange(), GetMaxRange(), GetMinRange(), Unit::GetSpellMaxRangeForTarget(), Unit::GetSpellMinRangeForTarget(), SpellTargetSelector::operator()(), SpellInfo(), and Pet::Update().
Rank
std::array<char const*, 16> SpellInfo::Rank
Definition at line 378 of file SpellInfo.h.
Referenced by SpellInfo().
Reagent
std::array<int32, MAX_SPELL_REAGENTS> SpellInfo::Reagent
Definition at line 368 of file SpellInfo.h.
Referenced by Spell::CheckItems(), spell_dk_raise_dead::CheckReagents(), SpellMgr::ComputeIsSpellValid(), Player::RemovePet(), SpellInfo(), Spell::TakeReagents(), and Spell::WriteCastResultInfo().
ReagentCount
std::array<uint32, MAX_SPELL_REAGENTS> SpellInfo::ReagentCount
Definition at line 369 of file SpellInfo.h.
Referenced by Spell::CheckItems(), spell_dk_raise_dead::CheckReagents(), Player::RemovePet(), SpellInfo(), Spell::TakeReagents(), and Spell::WriteCastResultInfo().
RecoveryTime
uint32 SpellInfo::RecoveryTime
Definition at line 343 of file SpellInfo.h.
Referenced by Player::AddSpellAndCategoryCooldowns(), Creature::AddSpellCooldown(), Player::ApplyEquipCooldown(), UnitAI::FillAISpellInfo(), GetRecoveryTime(), WorldSession::HandleItemQuerySingleOpcode(), ItemTemplate::InitializeQueryData(), SpellMgr::LoadSpellCustomAttr(), Player::RemoveArenaSpellCooldowns(), Spell::SendSpellCooldown(), SpellInfo(), and Spell::TriggerGlobalCooldown().
RequiresSpellFocus
uint32 SpellInfo::RequiresSpellFocus
Definition at line 332 of file SpellInfo.h.
Referenced by Spell::CheckSpellFocus(), Spell::SelectImplicitNearbyTargets(), SpellInfo(), and Spell::WriteCastResultInfo().
RuneCostID
uint32 SpellInfo::RuneCostID
Definition at line 363 of file SpellInfo.h.
Referenced by Spell::CheckPower(), Spell::SendSpellGo(), Spell::SendSpellStart(), SpellInfo(), and Spell::TakeRunePower().
SchoolMask
uint32 SpellInfo::SchoolMask
Definition at line 386 of file SpellInfo.h.
Referenced by Unit::CalcHealAbsorb(), spell_gen_allow_proc_from_spells_with_cost::CheckProc(), Spell::DoAllEffectOnLaunchTarget(), Spell::EffectWeaponDmg(), GetSchoolMask(), Unit::HandleDummyAuraProc(), spell_warr_execute::HandleEffect(), AuraEffect::HandlePeriodicPowerBurnAuraTick(), SmartAIMgr::IsEventValid(), SpellMgr::IsSpellProcEventCanTriggeredBy(), SpellMgr::LoadSpellCustomAttr(), Unit::ProcDamageAndSpellFor(), SmartScript::ProcessEvent(), ScriptedAI::SelectSpell(), Unit::SpellDamageBonusTaken(), npc_pool_of_tar::npc_pool_of_tarAI::SpellHit(), and SpellInfo().
Speed
float SpellInfo::Speed
Definition at line 365 of file SpellInfo.h.
Referenced by Spell::_cast(), Spell::AddGOTarget(), Spell::AddUnitTarget(), Spell::CalculateDelayMomentForDst(), Spell::DoSpellHitOnUnit(), Spell::EffectTransmitted(), Unit::GetMagicHitRedirectTarget(), Spell::IsNeedSendToClient(), SpellMgr::LoadSpellCustomAttr(), and SpellInfo().
SpellFamilyFlags
flag96 SpellInfo::SpellFamilyFlags
Definition at line 382 of file SpellInfo.h.
Referenced by Player::CanNoReagentCast(), SpellMgr::CanSpellTriggerProcOnEvent(), Spell::CheckItems(), spell_dk_dancing_rune_weapon::CheckProc(), spell_gen_black_magic_enchant::CheckProc(), spell_mage_brain_freeze::CheckProc(), spell_pal_seal_of_light::CheckProc(), spell_hun_ascpect_of_the_viper::CheckProc(), Spell::EffectEnchantItemTmp(), Spell::EffectHeal(), Spell::EffectSanctuary(), Spell::EffectSchoolDMG(), Spell::EffectWeaponDmg(), Unit::GetAuraEffect(), GetDiminishingReturnsGroupForSpell(), GetDiminishingReturnsLimitDuration(), spell_rog_deadly_poison::HandleAfterHit(), Unit::HandleAuraRaidProcFromChargeWithValue(), Aura::HandleAuraSpecificMods(), spell_rog_preparation::HandleDummy(), Unit::HandleDummyAuraProc(), AuraEffect::HandlePeriodicDummyAuraTick(), AuraEffect::HandlePeriodicManaLeechAuraTick(), spell_pal_sacred_shield_base::HandleProc(), Unit::HandleProcTriggerSpell(), spell_hun_chimera_shot::HandleScriptEffect(), IsAffectedBySpellMod(), AuraEffect::IsAffectedOnSpell(), IsRangedWeaponSpell(), SpellMgr::IsSpellProcEventCanTriggeredBy(), LoadAuraState(), SpellMgr::LoadSpellCustomAttr(), LoadSpellSpecific(), Unit::MeleeDamageBonusDone(), Unit::MeleeDamageBonusTaken(), Unit::ModSpellDuration(), Spell::prepareDataForTriggerSystem(), Spell::PrepareTriggersExecutedOnHit(), Unit::ProcDamageAndSpellFor(), spell_dru_enrage::RecalculateBaseArmor(), Unit::RemoveAurasByShapeShift(), Unit::RemoveAurasDueToSpellByDispel(), Unit::RemoveAurasWithFamily(), Player::RestoreSpellMods(), Unit::SpellDamageBonusDone(), Unit::SpellHealingBonusTaken(), SpellInfo(), Unit::SpellPctDamageModsDone(), Unit::SpellTakenCritChance(), and ValidateAttribute6SpellDamageMods().
SpellFamilyName
uint32 SpellInfo::SpellFamilyName
Definition at line 381 of file SpellInfo.h.
Referenced by Player::AddSpellAndCategoryCooldowns(), SpellMgr::CanSpellTriggerProcOnEvent(), Aura::CanStackWith(), Spell::CheckCast(), Spell::CheckItems(), spell_gen_allow_proc_from_spells_with_cost::CheckProc(), spell_gen_black_magic_enchant::CheckProc(), spell_item_essence_of_life::CheckProc(), CheckTargetCreatureType(), ComputeIsStackableWithRanks(), Spell::EffectDispel(), Spell::EffectDummy(), Spell::EffectEnchantItemTmp(), Spell::EffectEnergize(), Spell::EffectHeal(), Spell::EffectLeapBack(), Spell::EffectSanctuary(), Spell::EffectSchoolDMG(), Spell::EffectScriptEffect(), Spell::EffectTeleportUnits(), Spell::EffectTriggerSpell(), Spell::EffectWeaponDmg(), Unit::GetAuraEffect(), GetDiminishingReturnsGroupForSpell(), GetDiminishingReturnsLimitDuration(), Unit::GetEffectiveResistChance(), spell_rog_deadly_poison::HandleAfterHit(), AuraEffect::HandleAuraDummy(), AuraEffect::HandleAuraModShapeshift(), Unit::HandleAuraProc(), Unit::HandleAuraRaidProcFromChargeWithValue(), spell_hun_readiness::HandleDummy(), spell_mage_cold_snap::HandleDummy(), spell_rog_preparation::HandleDummy(), Unit::HandleDummyAuraProc(), Spell::HandleLaunchPhase(), learn_commandscript::HandleLearnAllMySpellsCommand(), AuraEffect::HandlePeriodicManaLeechAuraTick(), AuraEffect::HandlePeriodicTriggerSpellAuraTick(), spell_pal_sacred_shield_base::HandleProc(), Unit::HandleProcTriggerSpell(), IsAffectedBySpellMod(), AuraEffect::IsAffectedOnSpell(), IsRangedWeaponSpell(), SpellMgr::IsSpellProcEventCanTriggeredBy(), Unit::IsTriggeredAtSpellProcEvent(), LoadAuraState(), SpellMgr::LoadSpellCustomAttr(), LoadSpellSpecific(), Unit::MeleeDamageBonusDone(), Unit::MeleeDamageBonusTaken(), Unit::ModSpellDuration(), Acore::AbsorbAuraOrderPred::operator()(), Player::PrepareCharmAISpells(), Spell::prepareDataForTriggerSystem(), Spell::PrepareTriggersExecutedOnHit(), Unit::ProcDamageAndSpellFor(), spell_dru_enrage::RecalculateBaseArmor(), Unit::RemoveAurasByShapeShift(), Unit::RemoveAurasDueToSpellByDispel(), Unit::RemoveAurasWithFamily(), Player::RemoveSpellMods(), ArenaSpectator::ShouldSendAura(), Unit::SpellDamageBonusDone(), Unit::SpellHealingBonusDone(), Unit::SpellHealingBonusTaken(), Unit::SpellHitResult(), SpellInfo(), Unit::SpellPctDamageModsDone(), Unit::SpellPctHealingModsDone(), Unit::SpellTakenCritChance(), and ValidateAttribute6SpellDamageMods().
SpellIconID
uint32 SpellInfo::SpellIconID
Definition at line 375 of file SpellInfo.h.
Referenced by spell_mage_fire_frost_ward::Absorb(), Spell::AddUnitTarget(), Spell::CanExecuteTriggersOnHit(), spell_deathbringer_blood_link_aura::spell_deathbringer_blood_link_AuraScript::CheckProc(), spell_deathbringer_blood_link_blood_beast_aura::spell_deathbringer_blood_link_blood_beast_aura_AuraScript::CheckProc(), spell_gen_allow_proc_from_spells_with_cost::CheckProc(), spell_gen_black_magic_enchant::CheckProc(), spell_item_essence_of_life::CheckProc(), Spell::EffectSchoolDMG(), Spell::EffectWeaponDmg(), Spell::finish(), Unit::GetAuraEffect(), GetDiminishingReturnsGroupForSpell(), Unit::GetEffectiveResistChance(), AuraEffect::HandleAuraModShapeshift(), Unit::HandleAuraProc(), Unit::HandleDummyAuraProc(), Unit::HandleProcTriggerSpell(), IsLootCrafting(), Unit::ModSpellDuration(), Acore::AbsorbAuraOrderPred::operator()(), spell_gen_break_shield::PrepareSpellScript(), spell_gen_mounted_charge::PrepareSpellScript(), Player::RemoveSpellMods(), ArenaSpectator::ShouldSendAura(), SpellInfo(), Unit::SpellPctDamageModsDone(), Unit::SpellTakenCritChance(), Player::UpdateAttackPowerAndDamage(), and ValidateAttribute6SpellDamageMods().
SpellLevel
uint32 SpellInfo::SpellLevel
Definition at line 355 of file SpellInfo.h.
Referenced by ObjectMgr::AddSpellToTrainer(), Spell::AddUnitTarget(), CalcPowerCost(), Unit::CalculateLevelPenalty(), SpellEffectInfo::CalcValue(), Spell::CheckCast(), Spell::EffectEnergize(), GetAuraRankForLevel(), spell_item_powerful_anti_venom::HandleDummy(), spell_item_strong_anti_venom::HandleDummy(), spell_item_anti_venom::HandleDummy(), learn_commandscript::HandleLearnAllMySpellsCommand(), Spell::HandleThreatSpells(), Pet::InitLevelupSpellsForLevel(), SpellMgr::LoadPetLevelupSpellMap(), Unit::MagicSpellHitResult(), Spell::prepare(), and SpellInfo().
SpellName
std::array<char const*, 16> SpellInfo::SpellName
Definition at line 377 of file SpellInfo.h.
Referenced by lookup_commandscript::HandleLookupSpellCommand(), lookup_commandscript::HandleLookupSpellIdCommand(), LinkValidator< LinkTags::spell >::IsTextValid(), LinkValidator< LinkTags::enchant >::IsTextValid(), list_commandscript::ListAurasCommand(), list_commandscript::ShouldListAura(), and SpellInfo().
SpellVisual
std::array<uint32, 2> SpellInfo::SpellVisual
Definition at line 374 of file SpellInfo.h.
Referenced by Spell::EffectEnchantItemTmp(), Spell::EffectSchoolDMG(), GetDiminishingReturnsGroupForSpell(), Unit::HandleDummyAuraProc(), Unit::HandleOverrideClassScriptAuraProc(), Spell::IsNeedSendToClient(), SpellMgr::LoadSpellCustomAttr(), Unit::ModSpellCastTime(), and SpellInfo().
StackAmount
uint32 SpellInfo::StackAmount
Definition at line 366 of file SpellInfo.h.
Referenced by AuraApplication::BuildUpdatePacket(), Spell::CanAutoCast(), Spell::EffectTriggerSpell(), AuraEffect::HandleAuraDummy(), Aura::ModStackAmount(), spell_gen_defend::RefreshVisualShields(), spell_gen_defend::RemoveVisualShields(), boss_jaraxxus::boss_jaraxxusAI::SpellHit(), npc_ulduar_hodir_shaman::npc_ulduar_hodir_shamanAI::SpellHitTarget(), and SpellInfo().
Stances
uint32 SpellInfo::Stances
Definition at line 328 of file SpellInfo.h.
Referenced by Player::_addSpell(), Player::_addTalentAurasAndSpells(), Player::_LoadGlyphAuras(), Aura::CanBeSaved(), CheckShapeshift(), AuraEffect::HandleShapeshiftBoosts(), Player::IsNeedCastPassiveSpellAtLearn(), Aura::IsRemovedOnShapeLost(), Player::PrepareCharmAISpells(), and SpellInfo().
StancesNot
uint32 SpellInfo::StancesNot
Definition at line 329 of file SpellInfo.h.
Referenced by CheckShapeshift(), and SpellInfo().
StartRecoveryCategory
uint32 SpellInfo::StartRecoveryCategory
Definition at line 345 of file SpellInfo.h.
Referenced by GlobalCooldownMgr::AddGlobalCooldown(), GlobalCooldownMgr::CancelGlobalCooldown(), Spell::CheckPetCast(), GlobalCooldownMgr::HasGlobalCooldown(), and SpellInfo().
StartRecoveryTime
uint32 SpellInfo::StartRecoveryTime
Definition at line 346 of file SpellInfo.h.
Referenced by Spell::CancelGlobalCooldown(), Player::EquipItem(), UnitAI::FillAISpellInfo(), Spell::SendSpellGo(), SpellInfo(), and Spell::TriggerGlobalCooldown().
TargetAuraSpell
uint32 SpellInfo::TargetAuraSpell
Definition at line 339 of file SpellInfo.h.
Referenced by CheckTarget(), and SpellInfo().
TargetAuraState
uint32 SpellInfo::TargetAuraState
Definition at line 335 of file SpellInfo.h.
Referenced by CheckTarget(), Spell::EffectHeal(), Spell::EffectSchoolDMG(), and SpellInfo().
TargetAuraStateNot
uint32 SpellInfo::TargetAuraStateNot
Definition at line 337 of file SpellInfo.h.
Referenced by CheckTarget(), and SpellInfo().
TargetCreatureType
uint32 SpellInfo::TargetCreatureType
Definition at line 331 of file SpellInfo.h.
Referenced by CheckTargetCreatureType(), and SpellInfo().
Targets
uint32 SpellInfo::Targets
Definition at line 330 of file SpellInfo.h.
Referenced by _InitializeExplicitTargetMask(), and WorldSession::HandleCastSpellOpcode().
Totem
std::array<uint32, 2> SpellInfo::Totem
Definition at line 367 of file SpellInfo.h.
Referenced by Spell::CheckItems(), and Spell::WriteCastResultInfo().
TotemCategory
std::array<uint32, 2> SpellInfo::TotemCategory
Definition at line 373 of file SpellInfo.h.
Referenced by Spell::CheckItems(), and Spell::WriteCastResultInfo().
The documentation for this class was generated from the following files:
src/server/game/Spells/SpellInfo.h
src/server/game/Spells/SpellInfo.cpp