Azerotcore-wotlk: DynamicMapTree Class Reference
DynamicMapTree Class Reference
#include <DynamicTree.h>
Public Member Functions
DynamicMapTree ()
~DynamicMapTree ()
bool isInLineOfSight (float x1, float y1, float z1, float x2, float y2, float z2, uint32 phasemask) const
bool GetIntersectionTime (uint32 phasemask, const G3D::Ray &ray, const G3D::Vector3 &endPos, float &maxDist) const
bool GetAreaInfo (float x, float y, float &z, uint32 phasemask, uint32 &flags, int32 &adtId, int32 &rootId, int32 &groupId) const
void GetAreaAndLiquidData (float x, float y, float z, uint32 phasemask, uint8 reqLiquidType, VMAP::AreaAndLiquidData &data) const
bool GetObjectHitPos (uint32 phasemask, const G3D::Vector3 &pPos1, const G3D::Vector3 &pPos2, G3D::Vector3 &pResultHitPos, float pModifyDist) const
float getHeight (float x, float y, float z, float maxSearchDist, uint32 phasemask) const
void insert (const GameObjectModel &)
void remove (const GameObjectModel &)
bool contains (const GameObjectModel &) const
int size () const
void balance ()
void update (uint32 diff)
Private Attributes
DynTreeImpl * impl
Detailed Description
Definition at line 37 of file DynamicTree.h.
Constructor & Destructor Documentation
DynamicMapTree()
DynamicMapTree::DynamicMapTree ()
Definition at line 110 of file DynamicTree.cpp.
 : impl(new DynTreeImpl()) { }
~DynamicMapTree()
DynamicMapTree::~DynamicMapTree ()
Definition at line 112 of file DynamicTree.cpp.
 {
     delete impl;
 }
References impl.
Member Function Documentation
balance()
void DynamicMapTree::balance ()
Definition at line 132 of file DynamicTree.cpp.
 {
     impl->balance();
 }
References DynTreeImpl::balance(), and impl.
Referenced by Map::Balance().
contains()
bool DynamicMapTree::contains (const GameObjectModel & mdl) const
Definition at line 127 of file DynamicTree.cpp.
 {
     return impl->contains(mdl);
 }
References RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::contains(), and impl.
Referenced by Map::ContainsGameObjectModel().
GetAreaAndLiquidData()
void DynamicMapTree::GetAreaAndLiquidData (float x, float y, float z, uint32 phasemask, uint8 reqLiquidType, VMAP::AreaAndLiquidData & data) const
Definition at line 321 of file DynamicTree.cpp.
 {
     G3D::Vector3 v(x, y, z + 0.5f);
     DynamicTreeLocationInfoCallback intersectionCallBack(phasemask);
     impl->intersectPoint(v, intersectionCallBack);
     if (intersectionCallBack.GetLocationInfo().hitModel)
     {
         data.floorZ = intersectionCallBack.GetLocationInfo().ground_Z;
         uint32 liquidType = intersectionCallBack.GetLocationInfo().hitModel->GetLiquidType();
         float liquidLevel;
         if (!reqLiquidType || (dynamic_cast<VMAP::VMapMgr2*>(VMAP::VMapFactory::createOrGetVMapMgr())->GetLiquidFlagsPtr(liquidType) & reqLiquidType))
             if (intersectionCallBack.GetHitModel()->GetLiquidLevel(v, intersectionCallBack.GetLocationInfo(), liquidLevel))
                 data.liquidInfo.emplace(liquidType, liquidLevel);
         data.areaInfo.emplace(0,
             intersectionCallBack.GetLocationInfo().rootId,
             intersectionCallBack.GetLocationInfo().hitModel->GetWmoID(),
             intersectionCallBack.GetLocationInfo().hitModel->GetMogpFlags());
     }
 }
References VMAP::AreaAndLiquidData::areaInfo, VMAP::VMapFactory::createOrGetVMapMgr(), VMAP::AreaAndLiquidData::floorZ, DynamicTreeLocationInfoCallback::GetHitModel(), GameObjectModel::GetLiquidLevel(), VMAP::GroupModel::GetLiquidType(), DynamicTreeLocationInfoCallback::GetLocationInfo(), VMAP::GroupModel::GetMogpFlags(), VMAP::GroupModel::GetWmoID(), VMAP::LocationInfo::ground_Z, VMAP::LocationInfo::hitModel, impl, RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::intersectPoint(), VMAP::AreaAndLiquidData::liquidInfo, and VMAP::LocationInfo::rootId.
GetAreaInfo()
bool DynamicMapTree::GetAreaInfo (float x, float y, float & z, uint32 phasemask, uint32 & flags, int32 & adtId, int32 & rootId, int32 & groupId) const
Definition at line 304 of file DynamicTree.cpp.
 {
     G3D::Vector3 v(x, y, z + 0.5f);
     DynamicTreeAreaInfoCallback intersectionCallBack(phasemask);
     impl->intersectPoint(v, intersectionCallBack);
     if (intersectionCallBack.GetAreaInfo().result)
     {
         flags = intersectionCallBack.GetAreaInfo().flags;
         adtId = intersectionCallBack.GetAreaInfo().adtId;
         rootId = intersectionCallBack.GetAreaInfo().rootId;
         groupId = intersectionCallBack.GetAreaInfo().groupId;
         z = intersectionCallBack.GetAreaInfo().ground_Z;
         return true;
     }
     return false;
 }
References VMAP::AreaInfo::adtId, VMAP::AreaInfo::flags, DynamicTreeAreaInfoCallback::GetAreaInfo(), VMAP::AreaInfo::ground_Z, VMAP::AreaInfo::groupId, impl, RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::intersectPoint(), VMAP::AreaInfo::result, and VMAP::AreaInfo::rootId.
Referenced by Map::GetAreaInfo().
getHeight()
float DynamicMapTree::getHeight (float x, float y, float z, float maxSearchDist, uint32 phasemask) const
Definition at line 287 of file DynamicTree.cpp.
 {
     G3D::Vector3 v(x, y, z);
     G3D::Ray r(v, G3D::Vector3(0, 0, -1));
     DynamicTreeIntersectionCallback callback(phasemask);
     impl->intersectZAllignedRay(r, callback, maxSearchDist);
     if (callback.didHit())
     {
         return v.z - maxSearchDist;
     }
     else
     {
         return -G3D::finf();
     }
 }
References DynamicTreeIntersectionCallback::didHit(), impl, and RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::intersectZAllignedRay().
Referenced by BattlegroundRV::CheckPositionForUnit(), Map::GetGameObjectFloor(), and Map::GetHeight().
GetIntersectionTime()
bool DynamicMapTree::GetIntersectionTime (uint32 phasemask, const G3D::Ray & ray, const G3D::Vector3 & endPos, float & maxDist) const
Definition at line 210 of file DynamicTree.cpp.
 {
     float distance = maxDist;
     DynamicTreeIntersectionCallback callback(phasemask);
     impl->intersectRay(ray, callback, distance, endPos, false);
     if (callback.didHit())
     {
         maxDist = distance;
     }
     return callback.didHit();
 }
References DynamicTreeIntersectionCallback::didHit(), impl, and RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::intersectRay().
Referenced by GetObjectHitPos().
GetObjectHitPos()
bool DynamicMapTree::GetObjectHitPos (uint32 phasemask, const G3D::Vector3 & pPos1, const G3D::Vector3 & pPos2, G3D::Vector3 & pResultHitPos, float pModifyDist) const
Definition at line 223 of file DynamicTree.cpp.
 {
     bool result = false;
     float maxDist = (endPos - startPos).magnitude();
     // valid map coords should *never ever* produce float overflow, but this would produce NaNs too
     ASSERT(maxDist < std::numeric_limits<float>::max());
     // prevent NaN values which can cause BIH intersection to enter infinite loop
     if (maxDist < 1e-10f)
     {
         resultHit = endPos;
         return false;
     }
     G3D::Vector3 dir = (endPos - startPos) / maxDist;            // direction with length of 1
     G3D::Ray ray(startPos, dir);
     float dist = maxDist;
     if (GetIntersectionTime(phasemask, ray, endPos, dist))
     {
         resultHit = startPos + dir * dist;
         if (modifyDist < 0)
         {
             if ((resultHit - startPos).magnitude() > -modifyDist)
             {
                 resultHit = resultHit + dir * modifyDist;
             }
             else
             {
                 resultHit = startPos;
             }
         }
         else
         {
             resultHit = resultHit + dir * modifyDist;
         }
         result = true;
     }
     else
     {
         resultHit = endPos;
         result = false;
     }
     return result;
 }
References ASSERT, and GetIntersectionTime().
Referenced by Map::GetObjectHitPos().
insert()
void DynamicMapTree::insert (const GameObjectModel & mdl)
Definition at line 117 of file DynamicTree.cpp.
 {
     impl->insert(mdl);
 }
References impl, and DynTreeImpl::insert().
Referenced by Map::InsertGameObjectModel().
isInLineOfSight()
bool DynamicMapTree::isInLineOfSight (float x1, float y1, float z1, float x2, float y2, float z2, uint32 phasemask) const
Definition at line 269 of file DynamicTree.cpp.
 {
     G3D::Vector3 v1(x1, y1, z1), v2(x2, y2, z2);
     float maxDist = (v2 - v1).magnitude();
     if (!G3D::fuzzyGt(maxDist, 0) )
     {
         return true;
     }
     G3D::Ray r(v1, (v2 - v1) / maxDist);
     DynamicTreeIntersectionCallback callback(phasemask);
     impl->intersectRay(r, callback, maxDist, v2, true);
     return !callback.did_hit;
 }
References DynamicTreeIntersectionCallback::did_hit, impl, and RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::intersectRay().
Referenced by Map::isInLineOfSight(), and MysticBuffetTargetFilter::operator()().
remove()
void DynamicMapTree::remove (const GameObjectModel & mdl)
Definition at line 122 of file DynamicTree.cpp.
 {
     impl->remove(mdl);
 }
References impl, and DynTreeImpl::remove().
Referenced by Map::RemoveGameObjectModel().
size()
int DynamicMapTree::size () const
Definition at line 137 of file DynamicTree.cpp.
 {
     return impl->size();
 }
References impl, and RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::size().
update()
void DynamicMapTree::update (uint32 diff)
Definition at line 142 of file DynamicTree.cpp.
 {
     impl->update(t_diff);
 }
References impl, and DynTreeImpl::update().
Referenced by Map::Update().
Member Data Documentation
impl
DynTreeImpl* DynamicMapTree::impl private
Definition at line 39 of file DynamicTree.h.
Referenced by balance(), contains(), GetAreaAndLiquidData(), GetAreaInfo(), getHeight(), GetIntersectionTime(), insert(), isInLineOfSight(), remove(), size(), update(), and ~DynamicMapTree().
The documentation for this class was generated from the following files:
src/common/Collision/DynamicTree.h
src/common/Collision/DynamicTree.cpp