Azerotcore-wotlk: npc_ranshalla::npc_ranshallaAI Struct Reference
npc_ranshalla::npc_ranshallaAI Struct Reference
Public Member Functions
npc_ranshallaAI (Creature *creature)
void Reset () override
void DoContinueEscort (bool isAltarWaypoint=false)
void DoChannelTorchSpell (bool isAltarWaypoint=false)
void DoSummonPriestess ()
void SummonedMovementInform (Creature *summoned, uint32 type, uint32 pointId)
void WaypointReached (uint32 pointId) override
void JustDidDialogueStep (int32 entry) override
Will be called when a dialogue step was done.
Creature * GetSpeakerByEntry (int32 entry) override
Will be called to get a speaker, MUST be implemented if not used in instances.
void UpdateEscortAI (uint32 diff) override
Public Member Functions inherited from npc_escortAI
npc_escortAI (Creature *creature)
~npc_escortAI () override
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void JustDied (Unit *) override
void JustRespawned () override
void ReturnToLastPoint ()
void EnterEvadeMode () override
void UpdateAI (uint32 diff) override
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
virtual void WaypointStart (uint32)
void Start (bool isActiveAttacker=true, bool run=false, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetRun (bool on=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
uint32 _delayTimer
ObjectGuid _firstPriestessGUID
ObjectGuid _secondPriestessGUID
ObjectGuid _guardEluneGUID
ObjectGuid _voiceEluneGUID
ObjectGuid _altarGUID
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Private Attributes
EventMap events
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from npc_escortAI
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Private Member Functions inherited from DialogueHelper
DialogueHelper (DialogueEntry const *dialogueArray)
void StartNextDialogueText (int32 textEntry)
void DialogueUpdate (uint32 diff)
Detailed Description
Definition at line 315 of file zone_winterspring.cpp.
Constructor & Destructor Documentation
npc_ranshallaAI()
npc_ranshalla::npc_ranshallaAI::npc_ranshallaAI (Creature * creature) inline
Definition at line 317 of file zone_winterspring.cpp.
                                             : npc_escortAI(creature),
             DialogueHelper(introDialogue)
         {
             Reset();
         }
References Reset().
Member Function Documentation
DoChannelTorchSpell()
void npc_ranshalla::npc_ranshallaAI::DoChannelTorchSpell (bool isAltarWaypoint = false) inline
Definition at line 350 of file zone_winterspring.cpp.
         {
             // Check if we are using the fire or the altar and remove the no_interact flag
             if (isAltarWaypoint)
             {
                 if (GameObject* go = GetClosestGameObjectWithEntry(me, GO_ELUNE_ALTAR, 10.0f))
                 {
                     go->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                     me->SetFacingToObject(go);
                     _altarGUID = go->GetGUID();
                 }
             }
             else if (GameObject* go = GetClosestGameObjectWithEntry(me, GO_ELUNE_FIRE, 10.0f))
                 go->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
             // Yell and set escort to pause
             Talk(SAY_REACH_TORCH);
             Talk(EMOTE_CHANT_SPELL);
             SetEscortPaused(true);
             DoCast(me, SPELL_LIGHT_TORCH);
         }
References _altarGUID, UnitAI::DoCast(), EMOTE_CHANT_SPELL, GAMEOBJECT_FLAGS, GetClosestGameObjectWithEntry(), GO_ELUNE_ALTAR, GO_ELUNE_FIRE, GO_FLAG_NOT_SELECTABLE, ScriptedAI::me, SAY_REACH_TORCH, npc_escortAI::SetEscortPaused(), Unit::SetFacingToObject(), SPELL_LIGHT_TORCH, and CreatureAI::Talk().
Referenced by JustDidDialogueStep(), and WaypointReached().
DoContinueEscort()
void npc_ranshalla::npc_ranshallaAI::DoContinueEscort (bool isAltarWaypoint = false) inline
Definition at line 337 of file zone_winterspring.cpp.
         {
             me->InterruptNonMeleeSpells(false);
             if (isAltarWaypoint)
                 Talk(SAY_RANSHALLA_ALTAR_1);
             else
                 Talk(SAY_AFTER_TORCH);
             _delayTimer = 2000;
         }
References _delayTimer, Unit::InterruptNonMeleeSpells(), ScriptedAI::me, SAY_AFTER_TORCH, SAY_RANSHALLA_ALTAR_1, and CreatureAI::Talk().
DoSummonPriestess()
void npc_ranshalla::npc_ranshallaAI::DoSummonPriestess () inline
Definition at line 372 of file zone_winterspring.cpp.
         {
             // Summon 2 Elune priestess and make each of them move to a different spot
             if (Creature* priestess = me->SummonCreature(NPC_PRIESTESS_ELUNE, wingThicketLocations[0].m_positionX, wingThicketLocations[0].m_positionY, wingThicketLocations[0].m_positionZ, wingThicketLocations[0].m_orientation, TEMPSUMMON_CORPSE_DESPAWN, 0))
             {
                 priestess->GetMotionMaster()->MovePoint(0, wingThicketLocations[3].m_positionX, wingThicketLocations[3].m_positionY, wingThicketLocations[3].m_positionZ);
                 _firstPriestessGUID = priestess->GetGUID();
             }
             if (Creature* priestess = me->SummonCreature(NPC_PRIESTESS_ELUNE, wingThicketLocations[1].m_positionX, wingThicketLocations[1].m_positionY, wingThicketLocations[1].m_positionZ, wingThicketLocations[1].m_orientation, TEMPSUMMON_CORPSE_DESPAWN, 0))
             {
                 // Left priestess should have a distinct move point because she is the one who starts the dialogue at point reach
                 priestess->GetMotionMaster()->MovePoint(1, wingThicketLocations[4].m_positionX, wingThicketLocations[4].m_positionY, wingThicketLocations[4].m_positionZ);
                 _secondPriestessGUID = priestess->GetGUID();
             }
         }
References _firstPriestessGUID, _secondPriestessGUID, Position::m_orientation, Position::m_positionX, Position::m_positionY, Position::m_positionZ, ScriptedAI::me, NPC_PRIESTESS_ELUNE, WorldObject::SummonCreature(), TEMPSUMMON_CORPSE_DESPAWN, and wingThicketLocations.
Referenced by WaypointReached().
GetSpeakerByEntry()
Creature* npc_ranshalla::npc_ranshallaAI::GetSpeakerByEntry (int32) inline override virtual
Will be called to get a speaker, MUST be implemented if not used in instances.
Reimplemented from DialogueHelper.
Definition at line 548 of file zone_winterspring.cpp.
         {
             switch (entry)
             {
                 case NPC_RANSHALLA:
                     return me;
                 case NPC_VOICE_ELUNE:
                     return me->GetMap()->GetCreature(_voiceEluneGUID);
                 case NPC_PRIESTESS_DATA_1:
                     return me->GetMap()->GetCreature(_firstPriestessGUID);
                 case NPC_PRIESTESS_DATA_2:
                     return me->GetMap()->GetCreature(_secondPriestessGUID);
                 default:
                     return nullptr;
             }
         }
References _firstPriestessGUID, _secondPriestessGUID, _voiceEluneGUID, Map::GetCreature(), WorldObject::GetMap(), ScriptedAI::me, NPC_PRIESTESS_DATA_1, NPC_PRIESTESS_DATA_2, NPC_RANSHALLA, and NPC_VOICE_ELUNE.
JustDidDialogueStep()
void npc_ranshalla::npc_ranshallaAI::JustDidDialogueStep (int32) inline override virtual
Will be called when a dialogue step was done.
Reimplemented from DialogueHelper.
Definition at line 449 of file zone_winterspring.cpp.
         {
             switch (entry)
             {
                 case NPC_RANSHALLA:
                     // Start the altar channeling
                     DoChannelTorchSpell(true);
                     break;
                 case SAY_RANSHALLA_ALTAR_6:
                     SetEscortPaused(false);
                     break;
                 case SAY_PRIESTESS_ALTAR_8:
                     // make the gem respawn
                     if (GameObject* gem = GetClosestGameObjectWithEntry(me, GO_ELUNE_GEM, 10.0f))
                     {
                         if (gem->isSpawned())
                             break;
                         gem->SetRespawnTime(90);
                         gem->Refresh();
                     }
                     break;
                 case SAY_PRIESTESS_ALTAR_9:
                     // move near the escort npc
                     if (Creature* priestess = me->GetMap()->GetCreature(_firstPriestessGUID))
                         priestess->GetMotionMaster()->MovePoint(0, wingThicketLocations[6].m_positionX, wingThicketLocations[6].m_positionY, wingThicketLocations[6].m_positionZ);
                     break;
                 case SAY_PRIESTESS_ALTAR_13:
                     // summon the Guardian of Elune
                     if (Creature* guard = me->SummonCreature(NPC_GUARDIAN_ELUNE, wingThicketLocations[2].m_positionX, wingThicketLocations[2].m_positionY, wingThicketLocations[2].m_positionZ, wingThicketLocations[2].m_orientation, TEMPSUMMON_CORPSE_DESPAWN, 0))
                     {
                         guard->GetMotionMaster()->MovePoint(0, wingThicketLocations[5].m_positionX, wingThicketLocations[5].m_positionY, wingThicketLocations[5].m_positionZ);
                         _guardEluneGUID = guard->GetGUID();
                     }
                     // summon the Voice of Elune
                     if (GameObject* altar = me->GetMap()->GetGameObject(_altarGUID))
                     {
                         if (Creature* voice = me->SummonCreature(NPC_VOICE_ELUNE, altar->GetPositionX(), altar->GetPositionY(), altar->GetPositionZ(), 0, TEMPSUMMON_TIMED_DESPAWN, 30000))
                             _voiceEluneGUID = voice->GetGUID();
                     }
                     break;
                 case SAY_VOICE_ALTAR_15:
                     // move near the escort npc and continue dialogue
                     if (Creature* priestess = me->GetMap()->GetCreature(_secondPriestessGUID))
                     {
                         priestess->AI()->Talk(SAY_PRIESTESS_ALTAR_14);
                         priestess->GetMotionMaster()->MovePoint(0, wingThicketLocations[7].m_positionX, wingThicketLocations[7].m_positionY, wingThicketLocations[7].m_positionZ);
                     }
                     break;
                 case SAY_PRIESTESS_ALTAR_19:
                     // make the voice of elune leave
                     if (Creature* guard = me->GetMap()->GetCreature(_guardEluneGUID))
                     {
                         guard->GetMotionMaster()->MovePoint(0, wingThicketLocations[2].m_positionX, wingThicketLocations[2].m_positionY, wingThicketLocations[2].m_positionZ);
                         guard->DespawnOrUnsummon(4000);
                     }
                     break;
                 case SAY_PRIESTESS_ALTAR_20:
                     // make the first priestess leave
                     if (Creature* priestess = me->GetMap()->GetCreature(_firstPriestessGUID))
                     {
                         priestess->GetMotionMaster()->MovePoint(0, wingThicketLocations[0].m_positionX, wingThicketLocations[0].m_positionY, wingThicketLocations[0].m_positionZ);
                         priestess->DespawnOrUnsummon(4000);
                     }
                     break;
                 case SAY_PRIESTESS_ALTAR_21:
                     // make the second priestess leave
                     if (Creature* priestess = me->GetMap()->GetCreature(_secondPriestessGUID))
                     {
                         priestess->GetMotionMaster()->MovePoint(0, wingThicketLocations[1].m_positionX, wingThicketLocations[1].m_positionY, wingThicketLocations[1].m_positionZ);
                         priestess->DespawnOrUnsummon(4000);
                     }
                     break;
                 case DATA_EVENT_END:
                     // Turn towards the player
                     if (Player* player = GetPlayerForEscort())
                     {
                         me->SetFacingToObject(player);
                         Talk(SAY_RANSHALLA_END_1, player);
                     }
                     break;
                 case SAY_RANSHALLA_END_2:
                     // Turn towards the altar and kneel - quest complete
                     if (GameObject* altar = me->GetMap()->GetGameObject(_altarGUID))
                     {
                         me->SetFacingToObject(altar);
                         altar->ResetDoorOrButton();
                     }
                     me->SetStandState(UNIT_STAND_STATE_KNEEL);
                     if (Player* player = GetPlayerForEscort())
                     {
                         player->GroupEventHappens(QUEST_GUARDIANS_ALTAR, me);
                         Talk(SAY_RANSHALLA_END_2, player);
                     }
                     me->DespawnOrUnsummon(4000);
                     break;
             }
         }
References _altarGUID, _firstPriestessGUID, _guardEluneGUID, _secondPriestessGUID, _voiceEluneGUID, DATA_EVENT_END, Creature::DespawnOrUnsummon(), DoChannelTorchSpell(), GetClosestGameObjectWithEntry(), Map::GetCreature(), Map::GetGameObject(), WorldObject::GetMap(), npc_escortAI::GetPlayerForEscort(), GO_ELUNE_GEM, Position::m_orientation, Position::m_positionX, Position::m_positionY, Position::m_positionZ, ScriptedAI::me, NPC_GUARDIAN_ELUNE, NPC_RANSHALLA, NPC_VOICE_ELUNE, QUEST_GUARDIANS_ALTAR, SAY_PRIESTESS_ALTAR_13, SAY_PRIESTESS_ALTAR_14, SAY_PRIESTESS_ALTAR_19, SAY_PRIESTESS_ALTAR_20, SAY_PRIESTESS_ALTAR_21, SAY_PRIESTESS_ALTAR_8, SAY_PRIESTESS_ALTAR_9, SAY_RANSHALLA_ALTAR_6, SAY_RANSHALLA_END_1, SAY_RANSHALLA_END_2, SAY_VOICE_ALTAR_15, npc_escortAI::SetEscortPaused(), Unit::SetFacingToObject(), Unit::SetStandState(), WorldObject::SummonCreature(), CreatureAI::Talk(), TEMPSUMMON_CORPSE_DESPAWN, TEMPSUMMON_TIMED_DESPAWN, UNIT_STAND_STATE_KNEEL, and wingThicketLocations.
Reset()
void npc_ranshalla::npc_ranshallaAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 331 of file zone_winterspring.cpp.
         {
             _delayTimer = 0;
         }
References _delayTimer.
Referenced by npc_ranshallaAI().
SummonedMovementInform()
void npc_ranshalla::npc_ranshallaAI::SummonedMovementInform (Creature * summoned, uint32 type, uint32 pointId) inline
Definition at line 388 of file zone_winterspring.cpp.
         {
             if (type != POINT_MOTION_TYPE || summoned->GetEntry() != NPC_PRIESTESS_ELUNE || pointId != 1)
                 return;
             // Start the dialogue when the priestess reach the altar (they should both reach the point in the same time)
             StartNextDialogueText(SAY_PRIESTESS_ALTAR_3);
         }
References Object::GetEntry(), NPC_PRIESTESS_ELUNE, POINT_MOTION_TYPE, SAY_PRIESTESS_ALTAR_3, and DialogueHelper::StartNextDialogueText().
UpdateEscortAI()
void npc_ranshalla::npc_ranshallaAI::UpdateEscortAI (uint32 diff) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 565 of file zone_winterspring.cpp.
         {
             DialogueUpdate(diff);
             if (_delayTimer)
             {
                 if (_delayTimer <= diff)
                 {
                     SetEscortPaused(false);
                     _delayTimer = 0;
                 }
                 else
                     _delayTimer -= diff;
             }
             events.Update(diff);
             if (events.ExecuteEvent() == EVENT_RESUME)
                 StartNextDialogueText(SAY_PRIESTESS_ALTAR_3);
             npc_escortAI::UpdateEscortAI(diff);
         }
References _delayTimer, DialogueHelper::DialogueUpdate(), diff(), EVENT_RESUME, SAY_PRIESTESS_ALTAR_3, npc_escortAI::SetEscortPaused(), DialogueHelper::StartNextDialogueText(), and npc_escortAI::UpdateEscortAI().
WaypointReached()
void npc_ranshalla::npc_ranshallaAI::WaypointReached (uint32 pointId) inline override virtual
Implements npc_escortAI.
Definition at line 397 of file zone_winterspring.cpp.
         {
             switch (pointId)
             {
                 case 3:
                     Talk(SAY_ENTER_OWL_THICKET);
                     break;
                 case 10: // Cavern 1
                 case 15: // Cavern 2
                 case 20: // Cavern 3
                 case 25: // Cavern 4
                 case 36: // Cavern 5
                     DoChannelTorchSpell();
                     break;
                 case 39:
                     StartNextDialogueText(SAY_REACH_ALTAR_1);
                     SetEscortPaused(true);
                     break;
                 case 41:
                     {
                         // Search for all nearest lights and respawn them
                         std::list<GameObject*> eluneLights;
                         GetGameObjectListWithEntryInGrid(eluneLights, me, GO_ELUNE_LIGHT, 20.0f);
                         for (std::list<GameObject*>::const_iterator itr = eluneLights.begin(); itr != eluneLights.end(); ++itr)
{
                             if ((*itr)->isSpawned())
                                 continue;
                             (*itr)->SetRespawnTime(115);
                             (*itr)->Refresh();
                         }
                         if (GameObject* altar = me->GetMap()->GetGameObject(_altarGUID))
                             me->SetFacingToObject(altar);
                         break;
                     }
                 case 42:
                     // Summon the 2 priestess
                     SetEscortPaused(true);
                     DoSummonPriestess();
                     Talk(SAY_RANSHALLA_ALTAR_2);
                     events.ScheduleEvent(EVENT_RESUME, 2000);
                     break;
                 case 44:
                     // Stop the escort and turn towards the altar
                     SetEscortPaused(true);
                     if (GameObject* altar = me->GetMap()->GetGameObject(_altarGUID))
                         me->SetFacingToObject(altar);
                     break;
             }
         }
References _altarGUID, DoChannelTorchSpell(), DoSummonPriestess(), EVENT_RESUME, Map::GetGameObject(), GetGameObjectListWithEntryInGrid(), WorldObject::GetMap(), GO_ELUNE_LIGHT, ScriptedAI::me, SAY_ENTER_OWL_THICKET, SAY_RANSHALLA_ALTAR_2, SAY_REACH_ALTAR_1, npc_escortAI::SetEscortPaused(), Unit::SetFacingToObject(), DialogueHelper::StartNextDialogueText(), and CreatureAI::Talk().
Member Data Documentation
_altarGUID
ObjectGuid npc_ranshalla::npc_ranshallaAI::_altarGUID
Definition at line 329 of file zone_winterspring.cpp.
Referenced by DoChannelTorchSpell(), JustDidDialogueStep(), and WaypointReached().
_delayTimer
uint32 npc_ranshalla::npc_ranshallaAI::_delayTimer
Definition at line 323 of file zone_winterspring.cpp.
Referenced by DoContinueEscort(), Reset(), and UpdateEscortAI().
_firstPriestessGUID
ObjectGuid npc_ranshalla::npc_ranshallaAI::_firstPriestessGUID
Definition at line 325 of file zone_winterspring.cpp.
Referenced by DoSummonPriestess(), GetSpeakerByEntry(), and JustDidDialogueStep().
_guardEluneGUID
ObjectGuid npc_ranshalla::npc_ranshallaAI::_guardEluneGUID
Definition at line 327 of file zone_winterspring.cpp.
Referenced by JustDidDialogueStep().
_secondPriestessGUID
ObjectGuid npc_ranshalla::npc_ranshallaAI::_secondPriestessGUID
Definition at line 326 of file zone_winterspring.cpp.
Referenced by DoSummonPriestess(), GetSpeakerByEntry(), and JustDidDialogueStep().
_voiceEluneGUID
ObjectGuid npc_ranshalla::npc_ranshallaAI::_voiceEluneGUID
Definition at line 328 of file zone_winterspring.cpp.
Referenced by GetSpeakerByEntry(), and JustDidDialogueStep().
events
EventMap npc_ranshalla::npc_ranshallaAI::events private
Definition at line 586 of file zone_winterspring.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/zone_winterspring.cpp