Azerotcore-wotlk: G3D::GUniqueID Class Reference
G3D::GUniqueID Class Reference
#include <GUniqueID.h>
Public Member Functions
GUniqueID ()
GUniqueID & operator= (const Any &a)
GUniqueID (const Any &a)
Any toAny () const
std::string toString16 () const
bool uninitialized () const
uint16 tag () const
operator uint64 () const
bool operator== (const GUniqueID &other) const
bool operator!= (const GUniqueID &other) const
void serialize (class BinaryOutput &b) const
void deserialize (class BinaryInput &b)
void serialize (class TextOutput &t) const
void deserialize (class TextInput &t)
Static Public Member Functions
static GUniqueID fromString16 (const std::string &s)
static GUniqueID NONE (uint16 tag)
static GUniqueID create (uint16 tag=0)
Private Attributes
uint64 id
Detailed Description
Globally unique identifiers. The probability of two different programs generating the same value from UniqueID::create is vanishingly small.
UniqueIDs optionally contain a 10-bit application specific tag that distinguishes their type.
Definition at line 23 of file GUniqueID.h.
Constructor & Destructor Documentation
GUniqueID() [1/2]
G3D::GUniqueID::GUniqueID () inline
See also
create
Definition at line 31 of file GUniqueID.h.
 : id(0) {}
Referenced by fromString16().
GUniqueID() [2/2]
G3D::GUniqueID::GUniqueID (const Any & a) inline
See also
create
Definition at line 36 of file GUniqueID.h.
{
         *this = a;
     }
References mpq::a.
Member Function Documentation
create()
GUniqueID G3D::GUniqueID::create (uint16 tag = 0) static
Create a new ID
Definition at line 83 of file GUniqueID.cpp.
{
     static uint64 counter = 0;
     static uint64 systemID = 0;
     if (systemID == 0) {
         // Create a unique ID for this machine/program instance
         // TODO: see ioctl(skfd, SIOCGIFHWADDR, &if_hwaddr)
         Array<NetAddress> addr;
         NetworkDevice::instance()->localHostAddresses(addr);
         if (addr.size() > 0) {
             systemID |= addr[0].ip();
         }
         union {
             float64 ft;
             uint64 ut;
         };
         ft = System::time();
         systemID = ut << 22;
         systemID ^= ((uint64)iRandom(0, 32768)) << 8;
         systemID &= ~((uint64)1023 << 54);
         // Ensure that the systemID is non-zero (vanishingly small probability)
         if (systemID == 0) {
             systemID = 1;
         }
     }
     // No need for modulo; we'll all be dead before this counter
     // overflows 54 bits
     ++counter;
     GUniqueID i;
     i.id = (((uint64)(tag & 1023)) << 54) | (counter ^ systemID);
     return i;
 }
References id, G3D::NetworkDevice::instance(), G3D::iRandom(), G3D::NetworkDevice::localHostAddresses(), G3D::Array< T, MIN_ELEMENTS >::size(), tag(), and G3D::System::time().
deserialize() [1/2]
void G3D::GUniqueID::deserialize (class BinaryInput & b)
Definition at line 38 of file GUniqueID.cpp.
{
     id = b.readUInt64();
 }
References b.
deserialize() [2/2]
void G3D::GUniqueID::deserialize (class TextInput & t)
Definition at line 49 of file GUniqueID.cpp.
{
     t.readSymbol("(");
     id = (((uint64)t.readNumber()) << 32) + (uint64)t.readNumber();
     t.readSymbol(")");
 }
References G3D::TextInput::readNumber(), and G3D::TextInput::readSymbol().
fromString16()
GUniqueID G3D::GUniqueID::fromString16 (const std::string & s) static
Definition at line 69 of file GUniqueID.cpp.
{
     if (s.length() != 16) {
         debugAssertM(false, "Corrupt 16-character string");
         return GUniqueID();
     }
     uint32 high = 0, low = 0;
     sscanf(s.c_str(), "%08x%08x", &high, &low);
     GUniqueID i;
     i.id = (uint64(high) << 32) | low;
     return i;
 }
References debugAssertM, GUniqueID(), and id.
Referenced by operator=().
NONE()
GUniqueID G3D::GUniqueID::NONE (uint16 tag) static
Returns the ID that has the specified tag (so that it is not uninitialized), but which is a common sentinel "none" value.
Definition at line 56 of file GUniqueID.cpp.
{
     GUniqueID i;
     uint64 t = tag;
     i.id = (t << 54);
     return i;
 }
References id, and tag().
operator uint64()
G3D::GUniqueID::operator uint64 () const inline
Definition at line 59 of file GUniqueID.h.
{
         return id;
     }
References id.
operator!=()
bool G3D::GUniqueID::operator!= (const GUniqueID & other) const inline
Definition at line 67 of file GUniqueID.h.
{
         return id != other.id;
     }
References id.
operator=()
GUniqueID & G3D::GUniqueID::operator= (const Any & a)
Definition at line 15 of file GUniqueID.cpp.
{
     a.verifyName("GUniqueID");
     a.verifyType(Any::ARRAY);
     a.verifySize(1);
     std::string s = a[0];
     a.verify(s.length() == 16);
     id = GUniqueID::fromString16(s);
     return *this;
 }
References mpq::a, G3D::Any::ARRAY, and fromString16().
operator==()
bool G3D::GUniqueID::operator== (const GUniqueID & other) const inline
Definition at line 63 of file GUniqueID.h.
{
         return id == other.id;
     }
References id.
serialize() [1/2]
void G3D::GUniqueID::serialize (class BinaryOutput & b) const
Definition at line 33 of file GUniqueID.cpp.
{
     b.writeUInt64(id);
 }
References b.
serialize() [2/2]
void G3D::GUniqueID::serialize (class TextOutput & t) const
Definition at line 42 of file GUniqueID.cpp.
{
     t.writeSymbol("(");
     t.writeNumber((double)(id >> 32));
     t.writeNumber((double)(id & 0xFFFFFFFF));
     t.writeSymbol(")");
 }
References G3D::TextOutput::writeNumber(), and G3D::TextOutput::writeSymbol().
tag()
uint16 G3D::GUniqueID::tag () const inline
Definition at line 55 of file GUniqueID.h.
{
         return id >> 54;
     }
Referenced by create(), and NONE().
toAny()
Any G3D::GUniqueID::toAny () const
Definition at line 26 of file GUniqueID.cpp.
{
     Any a(Any::ARRAY, "GUniqueID");
     a.append(toString16());
     return a;
 }
References mpq::a, G3D::Any::ARRAY, and toString16().
toString16()
std::string G3D::GUniqueID::toString16 () const
Returns a 16-character string equivalent to this GUniqueID's uint64 value.
Definition at line 64 of file GUniqueID.cpp.
{
     return format("%08x%08x", uint32(id >> 32), uint32(id & 0xFFFFFFFF));
 }
References G3D::format().
Referenced by toAny().
uninitialized()
bool G3D::GUniqueID::uninitialized () const inline
Definition at line 51 of file GUniqueID.h.
{
         return id == 0;
     }
Member Data Documentation
id
uint64 G3D::GUniqueID::id private
Definition at line 26 of file GUniqueID.h.
Referenced by create(), fromString16(), NONE(), operator uint64(), operator!=(), and operator==().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/GUniqueID.h
deps/g3dlite/source/GUniqueID.cpp