Azerotcore-wotlk: SpectralBlastCheck Class Reference
SpectralBlastCheck Class Reference
Public Member Functions
SpectralBlastCheck (Unit *victim)
bool operator() (WorldObject *unit)
Private Attributes
Unit * _victim
Detailed Description
Definition at line 622 of file boss_kalecgos.cpp.
Constructor & Destructor Documentation
SpectralBlastCheck()
SpectralBlastCheck::SpectralBlastCheck (Unit * victim) inline
Definition at line 625 of file boss_kalecgos.cpp.
 : _victim(victim) { }
Member Function Documentation
operator()()
bool SpectralBlastCheck::operator() (WorldObject * unit) inline
Definition at line 627 of file boss_kalecgos.cpp.
     {
         return unit->GetPositionZ() < 50.0f || unit->ToUnit()->HasAura(SPELL_SPECTRAL_EXHAUSTION) || unit->GetGUID() == _victim->GetGUID();
     }
References _victim, Object::GetGUID(), Position::GetPositionZ(), Unit::HasAura(), SPELL_SPECTRAL_EXHAUSTION, and Object::ToUnit().
Member Data Documentation
_victim
Unit* SpectralBlastCheck::_victim private
Definition at line 632 of file boss_kalecgos.cpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/scripts/EasternKingdoms/SunwellPlateau/boss_kalecgos.cpp