Azerotcore-wotlk: deps/jemalloc/src/zone.c File Reference
zone.c File Reference
#include "jemalloc/internal/jemalloc_preamble.h"
#include "jemalloc/internal/jemalloc_internal_includes.h"
#include "jemalloc/internal/assert.h"
Classes
struct _malloc_zone_t
struct vm_range_t
struct malloc_statistics_t
struct malloc_introspection_t
Typedefs
typedef struct _malloc_zone_t malloc_zone_t
typedef struct malloc_statistics_t malloc_statistics_t
typedef kern_return_t memory_reader_t(task_t, vm_address_t, vm_size_t, void **)
typedef void vm_range_recorder_t(task_t, void *, unsigned type, vm_range_t *, unsigned)
typedef struct malloc_introspection_t malloc_introspection_t
Functions
kern_return_t malloc_get_all_zones (task_t, memory_reader_t, vm_address_t **, unsigned *)
malloc_zone_t * malloc_default_zone (void)
void malloc_zone_register (malloc_zone_t *zone)
void malloc_zone_unregister (malloc_zone_t *zone)
malloc_zone_t * malloc_default_purgeable_zone (void)
static void * zone_malloc (malloc_zone_t *zone, size_t size)
static void * zone_calloc (malloc_zone_t *zone, size_t num, size_t size)
static void * zone_valloc (malloc_zone_t *zone, size_t size)
static void zone_free (malloc_zone_t *zone, void *ptr)
static void * zone_realloc (malloc_zone_t *zone, void *ptr, size_t size)
static void * zone_memalign (malloc_zone_t *zone, size_t alignment, size_t size)
static void zone_free_definite_size (malloc_zone_t *zone, void *ptr, size_t size)
static void zone_destroy (malloc_zone_t *zone)
static unsigned zone_batch_malloc (struct _malloc_zone_t *zone, size_t size, void **results, unsigned num_requested)
static void zone_batch_free (struct _malloc_zone_t *zone, void **to_be_freed, unsigned num_to_be_freed)
static size_t zone_pressure_relief (struct _malloc_zone_t *zone, size_t goal)
static size_t zone_good_size (malloc_zone_t *zone, size_t size)
static kern_return_t zone_enumerator (task_t task, void *data, unsigned type_mask, vm_address_t zone_address, memory_reader_t reader, vm_range_recorder_t recorder)
static boolean_t zone_check (malloc_zone_t *zone)
static void zone_print (malloc_zone_t *zone, boolean_t verbose)
static void zone_log (malloc_zone_t *zone, void *address)
static void zone_force_lock (malloc_zone_t *zone)
static void zone_force_unlock (malloc_zone_t *zone)
static void zone_statistics (malloc_zone_t *zone, malloc_statistics_t *stats)
static boolean_t zone_locked (malloc_zone_t *zone)
static void zone_reinit_lock (malloc_zone_t *zone)
static void zone_init (void)
static malloc_zone_t * zone_default_get (void)
static void zone_promote (void)
void zone_register (void)
Typedef Documentation
malloc_introspection_t
typedef struct malloc_introspection_t malloc_introspection_t
malloc_statistics_t
typedef struct malloc_statistics_t malloc_statistics_t
malloc_zone_t
typedef struct _malloc_zone_t malloc_zone_t
memory_reader_t
typedef kern_return_t memory_reader_t(task_t, vm_address_t, vm_size_t, void **)
Definition at line 46 of file zone.c.
vm_range_recorder_t
typedef void vm_range_recorder_t(task_t, void *, unsigned type, vm_range_t *, unsigned)
Definition at line 48 of file zone.c.
Function Documentation
malloc_default_purgeable_zone()
malloc_zone_t* malloc_default_purgeable_zone (void)
Definition at line 83 of file zone.c.
{
     /*
      * There appear to be places within Darwin (such as setenv(3)) that
      * cause calls to this function with pointers that *no* zone owns.  If
      * we knew that all pointers were owned by *some* zone, we could split
      * our zone into two parts, and use one as the default allocator and
      * the other as the default deallocator/reallocator.  Since that will
      * not work in practice, we must check all pointers to assure that they
      * reside within a mapped extent before determining size.
      */
     return ivsalloc(tsdn_fetch(), ptr);
 }
Referenced by zone_register().
malloc_default_zone()
malloc_zone_t* malloc_default_zone (void)
Referenced by zone_default_get().
malloc_get_all_zones()
kern_return_t malloc_get_all_zones (task_t , memory_reader_t , vm_address_t ** , unsigned *)
Referenced by zone_default_get().
malloc_zone_register()
void malloc_zone_register (malloc_zone_t * zone)
Referenced by zone_promote(), and zone_register().
malloc_zone_unregister()
void malloc_zone_unregister (malloc_zone_t * zone)
Referenced by zone_promote().
zone_batch_free()
static void zone_batch_free (struct _malloc_zone_t * zone, void ** to_be_freed, unsigned num_to_be_freed) static
Definition at line 228 of file zone.c.
{
     unsigned i;
     for (i = 0; i < num_to_be_freed; i++) {
         zone_free(zone, to_be_freed[i]);
         to_be_freed[i] = NULL;
     }
 }
References NULL, and zone_free().
Referenced by zone_init().
zone_batch_malloc()
static unsigned zone_batch_malloc (struct _malloc_zone_t * zone, size_t size, void ** results, unsigned num_requested) static
Definition at line 214 of file zone.c.
{
     unsigned i;
     for (i = 0; i < num_requested; i++) {
         results[i] = je_malloc(size);
         if (!results[i])
             break;
     }
     return i;
 }
References je_malloc().
Referenced by zone_init().
zone_calloc()
static void* zone_calloc (malloc_zone_t * zone, size_t num, size_t size) static
Definition at line 152 of file zone.c.
{
     return je_calloc(num, size);
 }
References je_calloc().
Referenced by zone_init().
zone_check()
static boolean_t zone_check (malloc_zone_t * zone) static
Definition at line 259 of file zone.c.
{
     return true;
 }
Referenced by zone_init().
zone_default_get()
static malloc_zone_t* zone_default_get (void) static
Definition at line 370 of file zone.c.
{
     malloc_zone_t **zones = NULL;
     unsigned int num_zones = 0;
     /*
      * On OSX 10.12, malloc_default_zone returns a special zone that is not
      * present in the list of registered zones. That zone uses a "lite zone"
      * if one is present (apparently enabled when malloc stack logging is
      * enabled), or the first registered zone otherwise. In practice this
      * means unless malloc stack logging is enabled, the first registered
      * zone is the default.  So get the list of zones to get the first one,
      * instead of relying on malloc_default_zone.
      */
     if (KERN_SUCCESS != malloc_get_all_zones(0, NULL,
         (vm_address_t**)&zones, &num_zones)) {
         /*
          * Reset the value in case the failure happened after it was
          * set.
          */
         num_zones = 0;
     }
     if (num_zones) {
         return zones[0];
     }
     return malloc_default_zone();
 }
References malloc_default_zone(), malloc_get_all_zones(), and NULL.
Referenced by zone_promote(), and zone_register().
zone_destroy()
static void zone_destroy (malloc_zone_t * zone) static
Definition at line 208 of file zone.c.
{
     /* This function should never be called. */
     not_reached();
 }
References not_reached.
Referenced by zone_init().
zone_enumerator()
static kern_return_t zone_enumerator (task_t task, void * data, unsigned type_mask, vm_address_t zone_address, memory_reader_t reader, vm_range_recorder_t recorder) static
Definition at line 252 of file zone.c.
{
     return KERN_SUCCESS;
 }
Referenced by zone_init().
zone_force_lock()
static void zone_force_lock (malloc_zone_t * zone) static
Definition at line 272 of file zone.c.
{
     if (isthreaded) {
         /*
          * See the note in zone_force_unlock, below, to see why we need
          * this.
          */
         assert(zone_force_lock_pid == -1);
         zone_force_lock_pid = getpid();
         jemalloc_prefork();
     }
 }
References assert(), isthreaded, and jemalloc_prefork.
Referenced by zone_init().
zone_force_unlock()
static void zone_force_unlock (malloc_zone_t * zone) static
Definition at line 285 of file zone.c.
{
     /*
      * zone_force_lock and zone_force_unlock are the entry points to the
      * forking machinery on OS X.  The tricky thing is, the child is not
      * allowed to unlock mutexes locked in the parent, even if owned by the
      * forking thread (and the mutex type we use in OS X will fail an assert
      * if we try).  In the child, we can get away with reinitializing all
      * the mutexes, which has the effect of unlocking them.  In the parent,
      * doing this would mean we wouldn't wake any waiters blocked on the
      * mutexes we unlock.  So, we record the pid of the current thread in
      * zone_force_lock, and use that to detect if we're in the parent or
      * child here, to decide which unlock logic we need.
      */
     if (isthreaded) {
         assert(zone_force_lock_pid != -1);
         if (getpid() == zone_force_lock_pid) {
             jemalloc_postfork_parent();
         } else {
             jemalloc_postfork_child();
         }
         zone_force_lock_pid = -1;
     }
 }
References assert(), isthreaded, jemalloc_postfork_child, and jemalloc_postfork_parent.
Referenced by zone_init(), and zone_reinit_lock().
zone_free()
static void zone_free (malloc_zone_t * zone, void * ptr) static
Definition at line 166 of file zone.c.
{
     if (ivsalloc(tsdn_fetch(), ptr) != 0) {
         je_free(ptr);
         return;
     }
     free(ptr);
 }
References ivsalloc(), je_free, ptr(), and tsdn_fetch().
Referenced by zone_batch_free(), and zone_init().
zone_free_definite_size()
static void zone_free_definite_size (malloc_zone_t * zone, void * ptr, size_t size) static
Definition at line 194 of file zone.c.
{
     size_t alloc_size;
     alloc_size = ivsalloc(tsdn_fetch(), ptr);
     if (alloc_size != 0) {
         assert(alloc_size == size);
         je_free(ptr);
         return;
     }
     free(ptr);
 }
References assert(), ivsalloc(), je_free, ptr(), and tsdn_fetch().
Referenced by zone_init().
zone_good_size()
static size_t zone_good_size (malloc_zone_t * zone, size_t size) static
Definition at line 244 of file zone.c.
{
     if (size == 0) {
         size = 1;
     }
     return sz_s2u(size);
 }
References sz_s2u().
Referenced by zone_init().
zone_init()
static void zone_init (void) static
Definition at line 332 of file zone.c.
                 {
     jemalloc_zone.size = zone_size;
     jemalloc_zone.malloc = zone_malloc;
     jemalloc_zone.calloc = zone_calloc;
     jemalloc_zone.valloc = zone_valloc;
     jemalloc_zone.free = zone_free;
     jemalloc_zone.realloc = zone_realloc;
     jemalloc_zone.destroy = zone_destroy;
     jemalloc_zone.zone_name = "jemalloc_zone";
     jemalloc_zone.batch_malloc = zone_batch_malloc;
     jemalloc_zone.batch_free = zone_batch_free;
     jemalloc_zone.introspect = &jemalloc_zone_introspect;
     jemalloc_zone.version = 9;
     jemalloc_zone.memalign = zone_memalign;
     jemalloc_zone.free_definite_size = zone_free_definite_size;
     jemalloc_zone.pressure_relief = zone_pressure_relief;
     jemalloc_zone_introspect.enumerator = zone_enumerator;
     jemalloc_zone_introspect.good_size = zone_good_size;
     jemalloc_zone_introspect.check = zone_check;
     jemalloc_zone_introspect.print = zone_print;
     jemalloc_zone_introspect.log = zone_log;
     jemalloc_zone_introspect.force_lock = zone_force_lock;
     jemalloc_zone_introspect.force_unlock = zone_force_unlock;
     jemalloc_zone_introspect.statistics = zone_statistics;
     jemalloc_zone_introspect.zone_locked = zone_locked;
     jemalloc_zone_introspect.enable_discharge_checking = NULL;
     jemalloc_zone_introspect.disable_discharge_checking = NULL;
     jemalloc_zone_introspect.discharge = NULL;
 #ifdef __BLOCKS__
     jemalloc_zone_introspect.enumerate_discharged_pointers = NULL;
 #else
     jemalloc_zone_introspect.enumerate_unavailable_without_blocks = NULL;
 #endif
     jemalloc_zone_introspect.reinit_lock = zone_reinit_lock;
 }
References _malloc_zone_t::batch_free, _malloc_zone_t::batch_malloc, _malloc_zone_t::calloc, _malloc_zone_t::destroy, _malloc_zone_t::free, _malloc_zone_t::free_definite_size, _malloc_zone_t::introspect, _malloc_zone_t::malloc, _malloc_zone_t::memalign, NULL, _malloc_zone_t::pressure_relief, _malloc_zone_t::realloc, _malloc_zone_t::size, _malloc_zone_t::valloc, _malloc_zone_t::version, zone_batch_free(), zone_batch_malloc(), zone_calloc(), zone_check(), zone_destroy(), zone_enumerator(), zone_force_lock(), zone_force_unlock(), zone_free(), zone_free_definite_size(), zone_good_size(), zone_locked(), zone_log(), zone_malloc(), zone_memalign(), _malloc_zone_t::zone_name, zone_pressure_relief(), zone_print(), zone_realloc(), zone_reinit_lock(), zone_statistics(), and zone_valloc().
Referenced by zone_register().
zone_locked()
static boolean_t zone_locked (malloc_zone_t * zone) static
Definition at line 319 of file zone.c.
{
     /* Pretend no lock is being held */
     return false;
 }
Referenced by zone_init().
zone_log()
static void zone_log (malloc_zone_t * zone, void * address) static
Definition at line 268 of file zone.c.
{
 }
Referenced by zone_init().
zone_malloc()
static void* zone_malloc (malloc_zone_t * zone, size_t size) static
Definition at line 147 of file zone.c.
{
     return je_malloc(size);
 }
References je_malloc().
Referenced by zone_init().
zone_memalign()
static void* zone_memalign (malloc_zone_t * zone, size_t alignment, size_t size) static
Definition at line 185 of file zone.c.
{
     void *ret = NULL; /* Assignment avoids useless compiler warning. */
     je_posix_memalign(&ret, alignment, size);
     return ret;
 }
References je_posix_memalign, NULL, and ret.
Referenced by zone_init().
zone_pressure_relief()
static size_t zone_pressure_relief (struct _malloc_zone_t * zone, size_t goal) static
Definition at line 239 of file zone.c.
{
     return 0;
 }
Referenced by zone_init().
zone_print()
static void zone_print (malloc_zone_t * zone, boolean_t verbose) static
Definition at line 264 of file zone.c.
{
 }
Referenced by zone_init().
zone_promote()
static void zone_promote (void) static
Definition at line 401 of file zone.c.
                    {
     malloc_zone_t *zone;
     do {
         /*
          * Unregister and reregister the default zone.  On OSX >= 10.6,
          * unregistering takes the last registered zone and places it
          * at the location of the specified zone.  Unregistering the
          * default zone thus makes the last registered one the default.
          * On OSX < 10.6, unregistering shifts all registered zones.
          * The first registered zone then becomes the default.
          */
         malloc_zone_unregister(default_zone);
         malloc_zone_register(default_zone);
         /*
          * On OSX 10.6, having the default purgeable zone appear before
          * the default zone makes some things crash because it thinks it
          * owns the default zone allocated pointers.  We thus
          * unregister/re-register it in order to ensure it's always
          * after the default zone.  On OSX < 10.6, there is no purgeable
          * zone, so this does nothing.  On OSX >= 10.6, unregistering
          * replaces the purgeable zone with the last registered zone
          * above, i.e. the default zone.  Registering it again then puts
          * it at the end, obviously after the default zone.
          */
         if (purgeable_zone != NULL) {
             malloc_zone_unregister(purgeable_zone);
             malloc_zone_register(purgeable_zone);
         }
         zone = zone_default_get();
     } while (zone != &jemalloc_zone);
 }
References malloc_zone_register(), malloc_zone_unregister(), NULL, and zone_default_get().
Referenced by zone_register().
zone_realloc()
static void* zone_realloc (malloc_zone_t * zone, void * ptr, size_t size) static
Definition at line 176 of file zone.c.
{
     if (ivsalloc(tsdn_fetch(), ptr) != 0) {
         return je_realloc(ptr, size);
     }
     return realloc(ptr, size);
 }
References ivsalloc(), je_realloc, ptr(), and tsdn_fetch().
Referenced by zone_init().
zone_register()
void zone_register (void)
Definition at line 438 of file zone.c.
                     {
     /*
      * If something else replaced the system default zone allocator, don't
      * register jemalloc's.
      */
     default_zone = zone_default_get();
     if (!default_zone->zone_name || strcmp(default_zone->zone_name,
         "DefaultMallocZone") != 0) {
         return;
     }
     /*
      * The default purgeable zone is created lazily by OSX's libc.  It uses
      * the default zone when it is created for "small" allocations
      * (< 15 KiB), but assumes the default zone is a scalable_zone.  This
      * obviously fails when the default zone is the jemalloc zone, so
      * malloc_default_purgeable_zone() is called beforehand so that the
      * default purgeable zone is created when the default zone is still
      * a scalable_zone.  As purgeable zones only exist on >= 10.6, we need
      * to check for the existence of malloc_default_purgeable_zone() at
      * run time.
      */
     purgeable_zone = (malloc_default_purgeable_zone == NULL) ? NULL :
         malloc_default_purgeable_zone();
     /* Register the custom zone.  At this point it won't be the default. */
     zone_init();
     malloc_zone_register(&jemalloc_zone);
     /* Promote the custom zone to be default. */
     zone_promote();
 }
References malloc_default_purgeable_zone(), malloc_zone_register(), NULL, zone_default_get(), zone_init(), _malloc_zone_t::zone_name, and zone_promote().
zone_reinit_lock()
static void zone_reinit_lock (malloc_zone_t * zone) static
Definition at line 325 of file zone.c.
{
     /* As of OSX 10.12, this function is only used when force_unlock would
      * be used if the zone version were < 9. So just use force_unlock. */
     zone_force_unlock(zone);
 }
References zone_force_unlock().
Referenced by zone_init().
zone_statistics()
static void zone_statistics (malloc_zone_t * zone, malloc_statistics_t * stats) static
Definition at line 310 of file zone.c.
{
     /* We make no effort to actually fill the values */
     stats->blocks_in_use = 0;
     stats->size_in_use = 0;
     stats->max_size_in_use = 0;
     stats->size_allocated = 0;
 }
References malloc_statistics_t::blocks_in_use, malloc_statistics_t::max_size_in_use, malloc_statistics_t::size_allocated, and malloc_statistics_t::size_in_use.
Referenced by zone_init().
zone_valloc()
static void* zone_valloc (malloc_zone_t * zone, size_t size) static
Definition at line 157 of file zone.c.
{
     void *ret = NULL; /* Assignment avoids useless compiler warning. */
     je_posix_memalign(&ret, PAGE, size);
     return ret;
 }
References je_posix_memalign, NULL, PAGE, and ret.
Referenced by zone_init().