Azerotcore-wotlk: AreaTrigger_at_voltarus_middle Class Reference
AreaTrigger_at_voltarus_middle Class Reference
Public Member Functions
AreaTrigger_at_voltarus_middle ()
bool OnTrigger (Player *player, AreaTrigger const *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 43 of file areatrigger_scripts.cpp.
Constructor & Destructor Documentation
AreaTrigger_at_voltarus_middle()
AreaTrigger_at_voltarus_middle::AreaTrigger_at_voltarus_middle () inline
Definition at line 46 of file areatrigger_scripts.cpp.
         : AreaTriggerScript("at_voltarus_middle")
     {
     }
Member Function Documentation
OnTrigger()
bool AreaTrigger_at_voltarus_middle::OnTrigger (Player * player, AreaTrigger const *) inline override virtual
Reimplemented from AreaTriggerScript.
Definition at line 51 of file areatrigger_scripts.cpp.
     {
         if (player->IsAlive() && !player->IsInCombat())
             if (player->HasItemCount(39319)) // Scepter of Domination
             {
                 player->TeleportTo(571, 6242.67f, -1972.10f, 484.783f, 0.6f);
                 return true;
             }
         return false;
     }
References Player::HasItemCount(), Unit::IsAlive(), Unit::IsInCombat(), and Player::TeleportTo().
The documentation for this class was generated from the following file:
src/server/scripts/World/areatrigger_scripts.cpp