Azerotcore-wotlk: boss_taldaram::boss_taldaramAI Struct Reference
boss_taldaram::boss_taldaramAI Struct Reference
Public Member Functions
boss_taldaramAI (Creature *pCreature)
void InitializeAI () override
void Reset () override
void DoAction (int32 action) override
void MovementInform (uint32 type, uint32 id) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *victim) override
void EnterCombat (Unit *) override
void SpellHitTarget (Unit *, const SpellInfo *spellInfo) override
void JustSummoned (Creature *summon) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void SpellHit (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Member Functions
void ScheduleCombatEvents ()
Private Attributes
Position victimSperePos
ObjectGuid vanishTarget_GUID
uint32 vanishDamage
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 221 of file boss_prince_taldaram.cpp.
Constructor & Destructor Documentation
boss_taldaramAI()
boss_taldaram::boss_taldaramAI::boss_taldaramAI (Creature * pCreature) inline
Definition at line 223 of file boss_prince_taldaram.cpp.
                                              : BossAI(pCreature, DATA_PRINCE_TALDARAM),
             vanishDamage(0)
         {
         }
Member Function Documentation
DamageTaken()
void boss_taldaram::boss_taldaramAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 299 of file boss_prince_taldaram.cpp.
         {
             if (vanishTarget_GUID)
             {
                 if (me->FindCurrentSpellBySpellId(SPELL_EMBRACE_OF_THE_VAMPYR))
                 {
                     vanishDamage += damage;
                     if (vanishDamage >= DUNGEON_MODE<uint32>(MAX_EMBRACE_DMG, MAX_EMBRACE_DMG_H))
                     {
                         ScheduleCombatEvents();
                         me->CastStop();
                         vanishTarget_GUID.Clear();
                         vanishDamage = 0;
                     }
                 }
             }
         }
References Unit::CastStop(), ObjectGuid::Clear(), Unit::FindCurrentSpellBySpellId(), MAX_EMBRACE_DMG, MAX_EMBRACE_DMG_H, ScriptedAI::me, ScheduleCombatEvents(), SPELL_EMBRACE_OF_THE_VAMPYR, vanishDamage, and vanishTarget_GUID.
DoAction()
void boss_taldaram::boss_taldaramAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 261 of file boss_prince_taldaram.cpp.
         {
             if (action == ACTION_REMOVE_PRISON || action == ACTION_REMOVE_PRISON_AT_RESET)
             {
                 me->SetHomePosition(me->GetPositionX(), me->GetPositionY(), DATA_GROUND_POSITION_Z, me->GetOrientation());
                 instance->HandleGameObject(instance->GetGuidData(DATA_PRINCE_TALDARAM_PLATFORM), true);
                 if (action == ACTION_REMOVE_PRISON)
                 {
                     DoCastSelf(SPELL_HOVER_FALL);
                     me->GetMotionMaster()->Clear();
                     me->GetMotionMaster()->MoveLand(POINT_LAND, me->GetHomePosition(), 8.0f);
                     Talk(SAY_REMOVE_PRISON);
                 }
                 // Teleport instantly
                 else
                 {
                     me->SetDisableGravity(false);
                     me->SetHover(false);
                     me->RemoveAllAuras();
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC | UNIT_FLAG_NOT_SELECTABLE);
                     me->UpdatePosition(me->GetHomePosition(), true);
                 }
                 summons.DespawnEntry(NPC_JEDOGA_CONTROLLER);
             }
         }
References ACTION_REMOVE_PRISON, ACTION_REMOVE_PRISON_AT_RESET, MotionMaster::Clear(), DATA_GROUND_POSITION_Z, DATA_PRINCE_TALDARAM_PLATFORM, SummonList::DespawnEntry(), UnitAI::DoCastSelf(), InstanceScript::GetGuidData(), Creature::GetHomePosition(), Unit::GetMotionMaster(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), InstanceScript::HandleGameObject(), BossAI::instance, ScriptedAI::me, MotionMaster::MoveLand(), NPC_JEDOGA_CONTROLLER, POINT_LAND, Unit::RemoveAllAuras(), Object::RemoveFlag(), SAY_REMOVE_PRISON, Creature::SetDisableGravity(), Creature::SetHomePosition(), Creature::SetHover(), SPELL_HOVER_FALL, BossAI::summons, CreatureAI::Talk(), UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, and Unit::UpdatePosition().
Referenced by InitializeAI().
EnterCombat()
void boss_taldaram::boss_taldaramAI::EnterCombat (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 339 of file boss_prince_taldaram.cpp.
         {
             _EnterCombat();
             Talk(SAY_AGGRO);
             ScheduleCombatEvents();
             me->RemoveAllAuras();
             me->InterruptNonMeleeSpells(true);
         }
References BossAI::_EnterCombat(), Unit::InterruptNonMeleeSpells(), ScriptedAI::me, Unit::RemoveAllAuras(), SAY_AGGRO, ScheduleCombatEvents(), and CreatureAI::Talk().
InitializeAI()
void boss_taldaram::boss_taldaramAI::InitializeAI () inline override virtual
Reimplemented from UnitAI.
Definition at line 228 of file boss_prince_taldaram.cpp.
         {
             BossAI::InitializeAI();
             // Event not started
             if (instance->GetData(DATA_TELDRAM_SPHERE1) != DONE || instance->GetData(DATA_TELDRAM_SPHERE2) != DONE)
             {
                 me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
                 me->SetDisableGravity(true);
                 me->SetHover(true);
                 if (!me->HasAura(SPELL_BEAM_VISUAL))
                 {
                     DoCastSelf(SPELL_BEAM_VISUAL, true);
                 }
                 me->SummonCreatureGroup(SUMMON_GROUP_TRIGGERS);
                 return;
             }
             if (instance->GetData(DATA_TELDRAM_SPHERE1) == DONE && instance->GetData(DATA_TELDRAM_SPHERE2) == DONE)
             {
                 DoAction(ACTION_REMOVE_PRISON_AT_RESET);
             }
         }
References ACTION_REMOVE_PRISON_AT_RESET, DATA_TELDRAM_SPHERE1, DATA_TELDRAM_SPHERE2, DoAction(), UnitAI::DoCastSelf(), DONE, ZoneScript::GetData(), Unit::HasAura(), UnitAI::InitializeAI(), BossAI::instance, ScriptedAI::me, Creature::SetDisableGravity(), Object::SetFlag(), Creature::SetHover(), SPELL_BEAM_VISUAL, SUMMON_GROUP_TRIGGERS, WorldObject::SummonCreatureGroup(), UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, and UNIT_FLAG_IMMUNE_TO_PC.
JustDied()
void boss_taldaram::boss_taldaramAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 317 of file boss_prince_taldaram.cpp.
         {
             _JustDied();
             Talk(SAY_DEATH);
         }
References BossAI::_JustDied(), SAY_DEATH, and CreatureAI::Talk().
JustSummoned()
void boss_taldaram::boss_taldaramAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
Definition at line 357 of file boss_prince_taldaram.cpp.
         {
             summons.Summon(summon);
             switch (summon->GetEntry())
             {
                 case NPC_FLAME_SPHERE_1:
                 case NPC_FLAME_SPHERE_2:
                 case NPC_FLAME_SPHERE_3:
                 {
                     if (npc_taldaram_flamesphere::npc_taldaram_flamesphereAI* summonAI = dynamic_cast<npc_taldaram_flamesphere::npc_taldaram_flamesphereAI*>(summon->AI()))
                     {
                         summonAI->SetVictimPos(victimSperePos);
                     }
                     break;
                 }
                 case NPC_JEDOGA_CONTROLLER:
                 {
                     summon->CastSpell(nullptr, SPELL_BEAM_VISUAL);
                     break;
                 }
             }
         }
References Creature::AI(), Unit::CastSpell(), Object::GetEntry(), NPC_FLAME_SPHERE_1, NPC_FLAME_SPHERE_2, NPC_FLAME_SPHERE_3, NPC_JEDOGA_CONTROLLER, SPELL_BEAM_VISUAL, SummonList::Summon(), BossAI::summons, and victimSperePos.
KilledUnit()
void boss_taldaram::boss_taldaramAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 323 of file boss_prince_taldaram.cpp.
         {
             if (victim->GetTypeId() != TYPEID_PLAYER)
             {
                 return;
             }
             Talk(SAY_SLAY);
             if (vanishTarget_GUID && victim->GetGUID() == vanishTarget_GUID)
             {
                 vanishTarget_GUID.Clear();
                 vanishDamage = 0;
             }
         }
References ObjectGuid::Clear(), Object::GetGUID(), Object::GetTypeId(), SAY_SLAY, CreatureAI::Talk(), TYPEID_PLAYER, vanishDamage, and vanishTarget_GUID.
MovementInform()
void boss_taldaram::boss_taldaramAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 288 of file boss_prince_taldaram.cpp.
         {
             if (type == EFFECT_MOTION_TYPE && id == POINT_LAND)
             {
                 me->SetDisableGravity(false);
                 me->SetHover(false);
                 me->RemoveAllAuras();
                 me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC | UNIT_FLAG_NOT_SELECTABLE);
             }
         }
References EFFECT_MOTION_TYPE, ScriptedAI::me, POINT_LAND, Unit::RemoveAllAuras(), Object::RemoveFlag(), Creature::SetDisableGravity(), Creature::SetHover(), UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
Reset()
void boss_taldaram::boss_taldaramAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 253 of file boss_prince_taldaram.cpp.
         {
             _Reset();
             vanishDamage = 0;
             vanishTarget_GUID.Clear();
         }
References BossAI::_Reset(), ObjectGuid::Clear(), vanishDamage, and vanishTarget_GUID.
ScheduleCombatEvents()
void boss_taldaram::boss_taldaramAI::ScheduleCombatEvents () inline private
Definition at line 499 of file boss_prince_taldaram.cpp.
         {
             events.Reset();
             events.RescheduleEvent(EVENT_PRINCE_FLAME_SPHERES, 10000);
             events.RescheduleEvent(EVENT_PRINCE_BLOODTHIRST, 10000);
             vanishTarget_GUID.Clear();
             vanishDamage = 0;
         }
References ObjectGuid::Clear(), EVENT_PRINCE_BLOODTHIRST, EVENT_PRINCE_FLAME_SPHERES, vanishDamage, and vanishTarget_GUID.
Referenced by DamageTaken(), EnterCombat(), and UpdateAI().
SpellHitTarget()
void boss_taldaram::boss_taldaramAI::SpellHitTarget (Unit * , const SpellInfo * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 349 of file boss_prince_taldaram.cpp.
         {
             if (spellInfo->Id == SPELL_CONJURE_FLAME_SPHERE)
             {
                 summons.DoAction(ACTION_SPHERE);
             }
         }
References ACTION_SPHERE, SummonList::DoAction(), SpellInfo::Id, SPELL_CONJURE_FLAME_SPHERE, and BossAI::summons.
UpdateAI()
void boss_taldaram::boss_taldaramAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 381 of file boss_prince_taldaram.cpp.
         {
             if (!UpdateVictim())
             {
                 return;
             }
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
             {
                 return;
             }
             while (uint32 const eventId = events.ExecuteEvent())
             {
                 switch (eventId)
                 {
                     case EVENT_PRINCE_BLOODTHIRST:
                     {
                         DoCastSelf(SPELL_BLOODTHIRST);
                         events.RepeatEvent(10000);
                         break;
                     }
                     case EVENT_PRINCE_FLAME_SPHERES:
                     {
                         if (Unit* victim = me->GetVictim())
{
                             DoCast(victim, SPELL_CONJURE_FLAME_SPHERE);
                             victimSperePos = *victim;
                         }
                         if (!events.GetNextEventTime(EVENT_PRINCE_VANISH))
{
                             events.RescheduleEvent(EVENT_PRINCE_VANISH, 14000);
                         }
                         else
{
                             // Make sure that Vanish won't get triggered at same time as sphere summon
                             events.DelayEvents(4000);
                         }
                         events.RepeatEvent(15000);
                         break;
                     }
                     case EVENT_PRINCE_VANISH:
                     {
                         //Count alive players
                         uint8 count = 0;
                         std::list<HostileReference*> const t_list = me->getThreatMgr().getThreatList();
                         if (!t_list.empty())
{
                             for (HostileReference const* reference : t_list)
{
                                 if (reference)
{
                                     Unit const* pTarget = ObjectAccessor::GetUnit(*me, reference->getUnitGuid());
                                     if (pTarget && pTarget->GetTypeId() == TYPEID_PLAYER && pTarget->IsAlive())
{
                                         ++count;
                                     }
                                 }
                             }
                         }
                         // He only vanishes if there are 3 or more alive players
                         if (count > 2)
{
                             Talk(SAY_VANISH);
                             DoCastSelf(SPELL_VANISH, false);
                             if (Unit* pEmbraceTarget = SelectTarget(SELECT_TARGET_RANDOM, 0, 100, true))
{
                                 vanishTarget_GUID = pEmbraceTarget->GetGUID();
                             }
                             events.CancelEvent(EVENT_PRINCE_FLAME_SPHERES);
                             events.CancelEvent(EVENT_PRINCE_BLOODTHIRST);
                             events.ScheduleEvent(EVENT_PRINCE_VANISH_RUN, 2499);
                         }
                         break;
                     }
                     case EVENT_PRINCE_VANISH_RUN:
                     {
                         if (Unit* _vanishTarget = ObjectAccessor::GetUnit(*me, vanishTarget_GUID))
{
                             vanishDamage = 0;
                             DoCast(_vanishTarget, SPELL_SHADOWSTEP);
                             me->CastSpell(_vanishTarget, SPELL_EMBRACE_OF_THE_VAMPYR, false);
                             me->RemoveAura(SPELL_VANISH);
                         }
                         events.ScheduleEvent(EVENT_PRINCE_RESCHEDULE, 20000);
                         break;
                     }
                     case EVENT_PRINCE_RESCHEDULE:
                     {
                         ScheduleCombatEvents();
                         break;
                     }
                 }
                 if (me->HasUnitState(UNIT_STATE_CASTING))
                 {
                     return;
                 }
             }
             if (me->IsVisible())
             {
                 DoMeleeAttackIfReady();
             }
         }
References Unit::CastSpell(), UnitAI::DoCast(), UnitAI::DoCastSelf(), UnitAI::DoMeleeAttackIfReady(), EVENT_PRINCE_BLOODTHIRST, EVENT_PRINCE_FLAME_SPHERES, EVENT_PRINCE_RESCHEDULE, EVENT_PRINCE_VANISH, EVENT_PRINCE_VANISH_RUN, ThreatMgr::getThreatList(), Unit::getThreatMgr(), Object::GetTypeId(), ObjectAccessor::GetUnit(), Unit::GetVictim(), Unit::HasUnitState(), Unit::IsAlive(), Unit::IsVisible(), ScriptedAI::me, Unit::RemoveAura(), SAY_VANISH, ScheduleCombatEvents(), SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), SPELL_BLOODTHIRST, SPELL_CONJURE_FLAME_SPHERE, SPELL_EMBRACE_OF_THE_VAMPYR, SPELL_SHADOWSTEP, SPELL_VANISH, CreatureAI::Talk(), TYPEID_PLAYER, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), vanishDamage, vanishTarget_GUID, and victimSperePos.
Member Data Documentation
vanishDamage
uint32 boss_taldaram::boss_taldaramAI::vanishDamage private
Definition at line 497 of file boss_prince_taldaram.cpp.
Referenced by DamageTaken(), KilledUnit(), Reset(), ScheduleCombatEvents(), and UpdateAI().
vanishTarget_GUID
ObjectGuid boss_taldaram::boss_taldaramAI::vanishTarget_GUID private
Definition at line 496 of file boss_prince_taldaram.cpp.
Referenced by DamageTaken(), KilledUnit(), Reset(), ScheduleCombatEvents(), and UpdateAI().
victimSperePos
Position boss_taldaram::boss_taldaramAI::victimSperePos private
Definition at line 495 of file boss_prince_taldaram.cpp.
Referenced by JustSummoned(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/AzjolNerub/ahnkahet/boss_prince_taldaram.cpp