Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/arena_stats.h File Reference
arena_stats.h File Reference
#include "jemalloc/internal/atomic.h"
#include "jemalloc/internal/mutex.h"
#include "jemalloc/internal/mutex_prof.h"
#include "jemalloc/internal/sc.h"
Classes
struct arena_stats_large_s
struct arena_stats_decay_s
struct arena_stats_extents_s
struct arena_stats_s
Typedefs
typedef struct arena_stats_large_s arena_stats_large_t
typedef struct arena_stats_decay_s arena_stats_decay_t
typedef struct arena_stats_extents_s arena_stats_extents_t
typedef struct arena_stats_s arena_stats_t
Functions
static bool arena_stats_init (tsdn_t *tsdn, arena_stats_t *arena_stats)
static void arena_stats_lock (tsdn_t *tsdn, arena_stats_t *arena_stats)
static void arena_stats_unlock (tsdn_t *tsdn, arena_stats_t *arena_stats)
static uint64_t arena_stats_read_u64 (tsdn_t *tsdn, arena_stats_t *arena_stats, arena_stats_u64_t *p)
static void arena_stats_add_u64 (tsdn_t *tsdn, arena_stats_t *arena_stats, arena_stats_u64_t *p, uint64_t x)
static void arena_stats_sub_u64 (tsdn_t *tsdn, arena_stats_t *arena_stats, arena_stats_u64_t *p, uint64_t x)
static void arena_stats_accum_u64 (arena_stats_u64_t *dst, uint64_t src)
static size_t arena_stats_read_zu (tsdn_t *tsdn, arena_stats_t *arena_stats, atomic_zu_t *p)
static void arena_stats_add_zu (tsdn_t *tsdn, arena_stats_t *arena_stats, atomic_zu_t *p, size_t x)
static void arena_stats_sub_zu (tsdn_t *tsdn, arena_stats_t *arena_stats, atomic_zu_t *p, size_t x)
static void arena_stats_accum_zu (atomic_zu_t *dst, size_t src)
static void arena_stats_large_flush_nrequests_add (tsdn_t *tsdn, arena_stats_t *arena_stats, szind_t szind, uint64_t nrequests)
static void arena_stats_mapped_add (tsdn_t *tsdn, arena_stats_t *arena_stats, size_t size)
Variables
JEMALLOC_DIAGNOSTIC_DISABLE_SPURIOUS typedef uint64_t arena_stats_u64_t
Typedef Documentation
arena_stats_decay_t
typedef struct arena_stats_decay_s arena_stats_decay_t
Definition at line 20 of file arena_stats.h.
arena_stats_extents_t
typedef struct arena_stats_extents_s arena_stats_extents_t
Definition at line 20 of file arena_stats.h.
arena_stats_large_t
typedef struct arena_stats_large_s arena_stats_large_t
Definition at line 20 of file arena_stats.h.
arena_stats_t
typedef struct arena_stats_s arena_stats_t
Definition at line 20 of file arena_stats.h.
Function Documentation
arena_stats_accum_u64()
static void arena_stats_accum_u64 (arena_stats_u64_t * dst, uint64_t src) inline static
Definition at line 202 of file arena_stats.h.
{
 #ifdef JEMALLOC_ATOMIC_U64
     uint64_t cur_dst = atomic_load_u64(dst, ATOMIC_RELAXED);
     atomic_store_u64(dst, src + cur_dst, ATOMIC_RELAXED);
 #else
     *dst += src;
 #endif
 }
References ATOMIC_RELAXED.
Referenced by arena_stats_merge().
arena_stats_accum_zu()
static void arena_stats_accum_zu (atomic_zu_t * dst, size_t src) inline static
Definition at line 249 of file arena_stats.h.
{
     size_t cur_dst = atomic_load_zu(dst, ATOMIC_RELAXED);
     atomic_store_zu(dst, src + cur_dst, ATOMIC_RELAXED);
 }
References ATOMIC_RELAXED.
Referenced by arena_stats_merge(), and extents_abandon_vm().
arena_stats_add_u64()
static void arena_stats_add_u64 (tsdn_t * tsdn, arena_stats_t * arena_stats, arena_stats_u64_t * p, uint64_t x) inline static
Definition at line 173 of file arena_stats.h.
{
 #ifdef JEMALLOC_ATOMIC_U64
     atomic_fetch_add_u64(p, x, ATOMIC_RELAXED);
 #else
     malloc_mutex_assert_owner(tsdn, &arena_stats->mtx);
     *p += x;
 #endif
 }
References ATOMIC_RELAXED, malloc_mutex_assert_owner(), arena_stats_s::mtx, and G3D::x.
Referenced by arena_decay_extent(), arena_decay_stashed(), arena_large_dalloc_stats_update(), arena_large_malloc_stats_update(), and arena_stats_large_flush_nrequests_add().
arena_stats_add_zu()
static void arena_stats_add_zu (tsdn_t * tsdn, arena_stats_t * arena_stats, atomic_zu_t * p, size_t x) inline static
Definition at line 223 of file arena_stats.h.
{
 #ifdef JEMALLOC_ATOMIC_U64
     atomic_fetch_add_zu(p, x, ATOMIC_RELAXED);
 #else
     malloc_mutex_assert_owner(tsdn, &arena_stats->mtx);
     size_t cur = atomic_load_zu(p, ATOMIC_RELAXED);
     atomic_store_zu(p, cur + x, ATOMIC_RELAXED);
 #endif
 }
References ATOMIC_RELAXED, malloc_mutex_assert_owner(), arena_stats_s::mtx, and G3D::x.
Referenced by arena_extent_alloc_large(), and arena_stats_mapped_add().
arena_stats_init()
static bool arena_stats_init (tsdn_t * tsdn, arena_stats_t * arena_stats) inline static
Definition at line 131 of file arena_stats.h.
{
     if (config_debug) {
         for (size_t i = 0; i < sizeof(arena_stats_t); i++) {
             assert(((char *)arena_stats)[i] == 0);
         }
     }
 #ifndef JEMALLOC_ATOMIC_U64
     if (malloc_mutex_init(&arena_stats->mtx, "arena_stats",
         WITNESS_RANK_ARENA_STATS, malloc_mutex_rank_exclusive)) {
         return true;
     }
 #endif
     /* Memory is zeroed, so there is no need to clear stats. */
     return false;
 }
References assert(), config_debug, malloc_mutex_init, malloc_mutex_rank_exclusive, arena_stats_s::mtx, and WITNESS_RANK_ARENA_STATS.
Referenced by arena_new().
arena_stats_large_flush_nrequests_add()
static void arena_stats_large_flush_nrequests_add (tsdn_t * tsdn, arena_stats_t * arena_stats, szind_t szind, uint64_t nrequests) inline static
Definition at line 255 of file arena_stats.h.
{
     arena_stats_lock(tsdn, arena_stats);
     arena_stats_large_t *lstats = &arena_stats->lstats[szind - SC_NBINS];
     arena_stats_add_u64(tsdn, arena_stats, &lstats->nrequests, nrequests);
     arena_stats_add_u64(tsdn, arena_stats, &lstats->nflushes, 1);
     arena_stats_unlock(tsdn, arena_stats);
 }
References arena_stats_add_u64(), arena_stats_lock(), arena_stats_unlock(), arena_stats_s::lstats, arena_stats_large_s::nflushes, arena_stats_large_s::nrequests, and SC_NBINS.
Referenced by tcache_bin_flush_large(), and tcache_stats_merge().
arena_stats_lock()
static void arena_stats_lock (tsdn_t * tsdn, arena_stats_t * arena_stats) inline static
Definition at line 148 of file arena_stats.h.
{
 #ifndef JEMALLOC_ATOMIC_U64
     malloc_mutex_lock(tsdn, &arena_stats->mtx);
 #endif
 }
References malloc_mutex_lock(), and arena_stats_s::mtx.
Referenced by arena_decay_extent(), arena_decay_stashed(), arena_extent_alloc_large(), arena_extent_dalloc_large_prep(), arena_extent_ralloc_large_expand(), arena_extent_ralloc_large_shrink(), arena_stats_large_flush_nrequests_add(), arena_stats_mapped_add(), and arena_stats_merge().
arena_stats_mapped_add()
static void arena_stats_mapped_add (tsdn_t * tsdn, arena_stats_t * arena_stats, size_t size) inline static
Definition at line 265 of file arena_stats.h.
{
     arena_stats_lock(tsdn, arena_stats);
     arena_stats_add_zu(tsdn, arena_stats, &arena_stats->mapped, size);
     arena_stats_unlock(tsdn, arena_stats);
 }
References arena_stats_add_zu(), arena_stats_lock(), arena_stats_unlock(), and arena_stats_s::mapped.
Referenced by arena_slab_alloc_hard(), and large_ralloc_no_move_expand().
arena_stats_read_u64()
static uint64_t arena_stats_read_u64 (tsdn_t * tsdn, arena_stats_t * arena_stats, arena_stats_u64_t * p) inline static
Definition at line 162 of file arena_stats.h.
{
 #ifdef JEMALLOC_ATOMIC_U64
     return atomic_load_u64(p, ATOMIC_RELAXED);
 #else
     malloc_mutex_assert_owner(tsdn, &arena_stats->mtx);
     return *p;
 #endif
 }
References ATOMIC_RELAXED, malloc_mutex_assert_owner(), and arena_stats_s::mtx.
Referenced by arena_stats_merge().
arena_stats_read_zu()
static size_t arena_stats_read_zu (tsdn_t * tsdn, arena_stats_t * arena_stats, atomic_zu_t * p) inline static
Definition at line 212 of file arena_stats.h.
                     {
 #ifdef JEMALLOC_ATOMIC_U64
     return atomic_load_zu(p, ATOMIC_RELAXED);
 #else
     malloc_mutex_assert_owner(tsdn, &arena_stats->mtx);
     return atomic_load_zu(p, ATOMIC_RELAXED);
 #endif
 }
References ATOMIC_RELAXED, malloc_mutex_assert_owner(), and arena_stats_s::mtx.
Referenced by arena_stats_merge().
arena_stats_sub_u64()
static void arena_stats_sub_u64 (tsdn_t * tsdn, arena_stats_t * arena_stats, arena_stats_u64_t * p, uint64_t x) inline static
Definition at line 184 of file arena_stats.h.
{
 #ifdef JEMALLOC_ATOMIC_U64
     uint64_t r = atomic_fetch_sub_u64(p, x, ATOMIC_RELAXED);
     assert(r - x <= r);
 #else
     malloc_mutex_assert_owner(tsdn, &arena_stats->mtx);
     *p -= x;
     assert(*p + x >= *p);
 #endif
 }
References assert(), ATOMIC_RELAXED, malloc_mutex_assert_owner(), arena_stats_s::mtx, and G3D::x.
arena_stats_sub_zu()
static void arena_stats_sub_zu (tsdn_t * tsdn, arena_stats_t * arena_stats, atomic_zu_t * p, size_t x) inline static
Definition at line 235 of file arena_stats.h.
{
 #ifdef JEMALLOC_ATOMIC_U64
     size_t r = atomic_fetch_sub_zu(p, x, ATOMIC_RELAXED);
     assert(r - x <= r);
 #else
     malloc_mutex_assert_owner(tsdn, &arena_stats->mtx);
     size_t cur = atomic_load_zu(p, ATOMIC_RELAXED);
     atomic_store_zu(p, cur - x, ATOMIC_RELAXED);
 #endif
 }
References assert(), ATOMIC_RELAXED, malloc_mutex_assert_owner(), arena_stats_s::mtx, and G3D::x.
Referenced by arena_decay_extent(), and arena_decay_stashed().
arena_stats_unlock()
static void arena_stats_unlock (tsdn_t * tsdn, arena_stats_t * arena_stats) inline static
Definition at line 155 of file arena_stats.h.
{
 #ifndef JEMALLOC_ATOMIC_U64
     malloc_mutex_unlock(tsdn, &arena_stats->mtx);
 #endif
 }
References malloc_mutex_unlock(), and arena_stats_s::mtx.
Referenced by arena_decay_extent(), arena_decay_stashed(), arena_extent_alloc_large(), arena_extent_dalloc_large_prep(), arena_extent_ralloc_large_expand(), arena_extent_ralloc_large_shrink(), arena_stats_large_flush_nrequests_add(), arena_stats_mapped_add(), and arena_stats_merge().
Variable Documentation
arena_stats_u64_t
JEMALLOC_DIAGNOSTIC_DISABLE_SPURIOUS typedef uint64_t arena_stats_u64_t
Definition at line 20 of file arena_stats.h.