Azerotcore-wotlk: npc_captain_saeed::npc_captain_saeedAI Struct Reference
npc_captain_saeed::npc_captain_saeedAI Struct Reference
Public Member Functions
npc_captain_saeedAI (Creature *creature)
void Reset () override
void MoveInLineOfSight (Unit *who) override
void SetGUID (ObjectGuid playerGUID, int32 type) override
void EnterEvadeMode () override
void SummonsAction (Unit *who)
void WaypointReached (uint32 i) override
void EnterCombat (Unit *who) override
void JustDied (Unit *) override
void CorpseRemoved (uint32 &) override
== Triggered Actions Requested ==================
uint32 GetData (uint32 data) const override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from npc_escortAI
npc_escortAI (Creature *creature)
~npc_escortAI () override
void AttackStart (Unit *who) override
void JustRespawned () override
void ReturnToLastPoint ()
virtual void UpdateEscortAI (uint32 diff)
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
virtual void WaypointStart (uint32)
void Start (bool isActiveAttacker=true, bool run=false, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetRun (bool on=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual void SetData (uint32, uint32)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
SummonList summons
EventMap events
bool started
bool fight
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from npc_escortAI
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1096 of file zone_netherstorm.cpp.
Constructor & Destructor Documentation
npc_captain_saeedAI()
npc_captain_saeed::npc_captain_saeedAI::npc_captain_saeedAI (Creature * creature) inline
Definition at line 1098 of file zone_netherstorm.cpp.
 : npc_escortAI(creature), summons(me) {}
Member Function Documentation
CorpseRemoved()
void npc_captain_saeed::npc_captain_saeedAI::CorpseRemoved (uint32 &) inline override virtual
== Triggered Actions Requested ==================
== State checks =================================
Reimplemented from CreatureAI.
Definition at line 1238 of file zone_netherstorm.cpp.
         {
             summons.DespawnAll();
         }
References SummonList::DespawnAll(), and summons.
EnterCombat()
void npc_captain_saeed::npc_captain_saeedAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1224 of file zone_netherstorm.cpp.
         {
             SummonsAction(who);
         }
References SummonsAction().
EnterEvadeMode()
void npc_captain_saeed::npc_captain_saeedAI::EnterEvadeMode () inline override virtual
Reimplemented from npc_escortAI.
Definition at line 1173 of file zone_netherstorm.cpp.
         {
             if (fight)
                 SetEscortPaused(false);
             SummonsAction(nullptr);
             npc_escortAI::EnterEvadeMode();
         }
References npc_escortAI::EnterEvadeMode(), fight, npc_escortAI::SetEscortPaused(), and SummonsAction().
GetData()
uint32 npc_captain_saeed::npc_captain_saeedAI::GetData (uint32 data) const inline override virtual
Reimplemented from UnitAI.
Definition at line 1243 of file zone_netherstorm.cpp.
         {
             if (data == 1)
                 return (uint32)started;
             return 0;
         }
References started.
JustDied()
void npc_captain_saeed::npc_captain_saeedAI::JustDied (Unit *) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 1229 of file zone_netherstorm.cpp.
         {
             Player* player = GetPlayerForEscort();
             if (player)
                 player->FailQuest(QUEST_DIMENSIUS_DEVOURING);
             summons.DespawnAll();
         }
References SummonList::DespawnAll(), Player::FailQuest(), npc_escortAI::GetPlayerForEscort(), QUEST_DIMENSIUS_DEVOURING, and summons.
MoveInLineOfSight()
void npc_captain_saeed::npc_captain_saeedAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 1123 of file zone_netherstorm.cpp.
         {
             if (Player* player = GetPlayerForEscort())
                 if (me->GetDistance(who) < 10.0f && !me->GetVictim())
                     if (player->IsValidAttackTarget(who))
                     {
                         AttackStart(who);
                         return;
                     }
             npc_escortAI::MoveInLineOfSight(who);
         }
References npc_escortAI::AttackStart(), WorldObject::GetDistance(), npc_escortAI::GetPlayerForEscort(), Unit::GetVictim(), ScriptedAI::me, and npc_escortAI::MoveInLineOfSight().
Reset()
void npc_captain_saeed::npc_captain_saeedAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1104 of file zone_netherstorm.cpp.
         {
             if (!summons.empty())
             {
                 for (ObjectGuid const& guid : summons)
                     if (Creature* cr = ObjectAccessor::GetCreature(*me, guid))
                     {
                         float x, y, z, o;
                         cr->GetRespawnPosition(x, y, z, &o);
                         cr->SetHomePosition(x, y, z, o);
                     }
             }
             events.Reset();
             summons.clear();
             started = false;
             fight = false;
             me->RestoreFaction();
         }
References SummonList::clear(), SummonList::empty(), fight, ObjectAccessor::GetCreature(), ScriptedAI::me, Unit::RestoreFaction(), started, and summons.
SetGUID()
void npc_captain_saeed::npc_captain_saeedAI::SetGUID (ObjectGuid playerGUID, int32 type) inline override virtual
Reimplemented from UnitAI.
Definition at line 1136 of file zone_netherstorm.cpp.
         {
             if (type == DATA_START_ENCOUNTER)
             {
                 Start(true, true, playerGUID);
                 SetEscortPaused(true);
                 started = true;
                 std::list<Creature*> cl;
                 me->GetCreaturesWithEntryInRange(cl, 20.0f, NPC_PROTECTORATE_AVENGER);
                 for (std::list<Creature*>::iterator itr = cl.begin(); itr != cl.end(); ++itr)
                 {
                     summons.Summon(*itr);
                     (*itr)->HandleEmoteCommand(EMOTE_ONESHOT_ROAR);
                     (*itr)->SetFaction(FACTION_ESCORTEE_N_NEUTRAL_ACTIVE);
                 }
                 cl.clear();
                 me->GetCreaturesWithEntryInRange(cl, 20.0f, NPC_PROTECTORATE_DEFENDER);
                 for (std::list<Creature*>::iterator itr = cl.begin(); itr != cl.end(); ++itr)
                 {
                     summons.Summon(*itr);
                     (*itr)->HandleEmoteCommand(EMOTE_ONESHOT_ROAR);
                     (*itr)->SetFaction(FACTION_ESCORTEE_N_NEUTRAL_ACTIVE);
                 }
                 me->SetFaction(FACTION_ESCORTEE_N_NEUTRAL_ACTIVE);
                 Talk(SAY_SAEED_0);
                 events.ScheduleEvent(EVENT_START_WALK, 3000);
             }
             else if (type == DATA_START_FIGHT)
             {
                 Talk(SAY_SAEED_2);
                 SetEscortPaused(false);
                 me->SetUInt32Value(UNIT_NPC_FLAGS, 0);
             }
         }
References DATA_START_ENCOUNTER, DATA_START_FIGHT, EMOTE_ONESHOT_ROAR, EVENT_START_WALK, FACTION_ESCORTEE_N_NEUTRAL_ACTIVE, WorldObject::GetCreaturesWithEntryInRange(), ScriptedAI::me, NPC_PROTECTORATE_AVENGER, NPC_PROTECTORATE_DEFENDER, SAY_SAEED_0, SAY_SAEED_2, npc_escortAI::SetEscortPaused(), Unit::SetFaction(), Object::SetUInt32Value(), npc_escortAI::Start(), started, SummonList::Summon(), summons, CreatureAI::Talk(), and UNIT_NPC_FLAGS.
SummonsAction()
void npc_captain_saeed::npc_captain_saeedAI::SummonsAction (Unit * who) inline
Definition at line 1182 of file zone_netherstorm.cpp.
         {
             float i = 0;
             for (GuidList::iterator itr = summons.begin(); itr != summons.end(); ++itr, i += 1.0f)
                 if (Creature* cr = ObjectAccessor::GetCreature(*me, *itr))
                 {
                     if (who == nullptr)
                     {
                         cr->GetMotionMaster()->Clear(false);
                         cr->GetMotionMaster()->MoveFollow(me, 2.0f, M_PI / 2.0f + (i / summons.size() * M_PI));
                     }
                     else
                     {
                         cr->SetHomePosition(cr->GetPositionX(), cr->GetPositionY(), cr->GetPositionZ(), cr->GetOrientation());
                         cr->AI()->AttackStart(who);
                     }
                 }
         }
References SummonList::begin(), SummonList::end(), ObjectAccessor::GetCreature(), ScriptedAI::me, SummonList::size(), and summons.
Referenced by EnterCombat(), EnterEvadeMode(), and UpdateAI().
UpdateAI()
void npc_captain_saeed::npc_captain_saeedAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 1251 of file zone_netherstorm.cpp.
         {
             npc_escortAI::UpdateAI(diff);
             events.Update(diff);
             switch (events.ExecuteEvent())
             {
                 case EVENT_START_WALK:
                     SummonsAction(nullptr);
                     SetEscortPaused(false);
                     break;
                 case EVENT_START_FIGHT1:
                     Talk(SAY_SAEED_3);
                     events.ScheduleEvent(EVENT_START_FIGHT2, 3000);
                     break;
                 case EVENT_START_FIGHT2:
                     if (Creature* dimensius = me->FindNearestCreature(NPC_DIMENSIUS, 50.0f))
                     {
                         dimensius->RemoveAurasDueToSpell(SPELL_DIMENSIUS_TRANSFORM);
                         dimensius->SetUInt32Value(UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE);
                         AttackStart(dimensius);
                         fight = true;
                     }
                     break;
             }
             if (!UpdateVictim())
                 return;
             DoMeleeAttackIfReady();
         }
References npc_escortAI::AttackStart(), UnitAI::DoMeleeAttackIfReady(), EVENT_START_FIGHT1, EVENT_START_FIGHT2, EVENT_START_WALK, fight, WorldObject::FindNearestCreature(), ScriptedAI::me, NPC_DIMENSIUS, SAY_SAEED_3, npc_escortAI::SetEscortPaused(), SPELL_DIMENSIUS_TRANSFORM, SummonsAction(), CreatureAI::Talk(), UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE, npc_escortAI::UpdateAI(), and CreatureAI::UpdateVictim().
WaypointReached()
void npc_captain_saeed::npc_captain_saeedAI::WaypointReached (uint32 i) inline override virtual
Implements npc_escortAI.
Definition at line 1201 of file zone_netherstorm.cpp.
         {
             Player* player = GetPlayerForEscort();
             if (!player)
                 return;
             switch (i)
             {
                 case 16:
                     Talk(SAY_SAEED_1);
                     me->SetUInt32Value(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
                     SetEscortPaused(true);
                     break;
                 case 18:
                     events.ScheduleEvent(EVENT_START_FIGHT1, 0);
                     SetEscortPaused(true);
                     break;
                 case 19:
                     summons.DespawnAll();
                     break;
             }
         }
References SummonList::DespawnAll(), EVENT_START_FIGHT1, npc_escortAI::GetPlayerForEscort(), ScriptedAI::me, SAY_SAEED_1, npc_escortAI::SetEscortPaused(), Object::SetUInt32Value(), summons, CreatureAI::Talk(), UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
Member Data Documentation
events
EventMap npc_captain_saeed::npc_captain_saeedAI::events
Definition at line 1101 of file zone_netherstorm.cpp.
fight
bool npc_captain_saeed::npc_captain_saeedAI::fight
Definition at line 1102 of file zone_netherstorm.cpp.
Referenced by EnterEvadeMode(), Reset(), and UpdateAI().
started
bool npc_captain_saeed::npc_captain_saeedAI::started
Definition at line 1102 of file zone_netherstorm.cpp.
Referenced by GetData(), Reset(), and SetGUID().
summons
SummonList npc_captain_saeed::npc_captain_saeedAI::summons
Definition at line 1100 of file zone_netherstorm.cpp.
Referenced by CorpseRemoved(), JustDied(), Reset(), SetGUID(), SummonsAction(), and WaypointReached().
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/zone_netherstorm.cpp