Azerotcore-wotlk: npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI Struct Reference
npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI Struct Reference
Public Member Functions
npc_pilgrims_bounty_chairAI (Creature *creature)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void PassengerBoarded (Unit *who, int8, bool apply) override
== Fields =======================================
Creature * GetPlate ()
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void DoAction (int32 param) override
void SpellHitTarget (Unit *target, const SpellInfo *spellInfo) override
void SpellHit (Unit *, const SpellInfo *spellInfo) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from VehicleAI
VehicleAI (Creature *creature)
void OnCharmed (bool apply) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void Reset ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
ObjectGuid plateGUID
uint32 timerSpawnPlate
uint32 timerRotateChair
Additional Inherited Members
Static Public Member Functions inherited from VehicleAI
static int Permissible (Creature const *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 110 of file pilgrims_bounty.cpp.
Constructor & Destructor Documentation
npc_pilgrims_bounty_chairAI()
npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::npc_pilgrims_bounty_chairAI (Creature * creature) inline
Definition at line 112 of file pilgrims_bounty.cpp.
                                                         : VehicleAI(creature)
         {
             plateGUID.Clear();
             timerSpawnPlate = 1;
             timerRotateChair = 0;
             me->SetReactState(REACT_PASSIVE);
         }
References ObjectGuid::Clear(), CreatureAI::me, plateGUID, REACT_PASSIVE, Creature::SetReactState(), timerRotateChair, and timerSpawnPlate.
Member Function Documentation
AttackStart()
void npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::AttackStart (Unit *) inline override virtual
Reimplemented from VehicleAI.
Definition at line 121 of file pilgrims_bounty.cpp.
 {}
DamageTaken()
void npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from UnitAI.
Definition at line 135 of file pilgrims_bounty.cpp.
         {
             damage = 0;
         }
DoAction()
void npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 140 of file pilgrims_bounty.cpp.
         {
             switch (param)
             {
                 case SPELL_VISUAL_THROW_TURKEY:
                 case SPELL_VISUAL_BOUNCE_TURKEY:
                     me->CastSpell(me, SPELL_STORE_TURKEY, true);
                     me->CastSpell(me, SPELL_CAN_EAT_TURKEY, true);
                     if (Unit* plate = GetPlate())
                         plate->CastSpell(plate, SPELL_PLATE_TURKEY, true);
                     break;
                 case SPELL_VISUAL_THROW_STUFFING:
                 case SPELL_VISUAL_BOUNCE_STUFFING:
                     me->CastSpell(me, SPELL_STORE_STUFFING, true);
                     me->CastSpell(me, SPELL_CAN_EAT_STUFFING, true);
                     if (Unit* plate = GetPlate())
                         plate->CastSpell(plate, SPELL_PLATE_STUFFING, true);
                     break;
                 case SPELL_VISUAL_THROW_PIE:
                 case SPELL_VISUAL_BOUNCE_PIE:
                     me->CastSpell(me, SPELL_STORE_PIE, true);
                     me->CastSpell(me, SPELL_CAN_EAT_PIE, true);
                     if (Unit* plate = GetPlate())
                         plate->CastSpell(plate, SPELL_PLATE_PIE, true);
                     break;
                 case SPELL_VISUAL_THROW_CRANBERRY:
                 case SPELL_VISUAL_BOUNCE_CRANBERRY:
                     me->CastSpell(me, SPELL_STORE_CRANBERRY, true);
                     me->CastSpell(me, SPELL_CAN_EAT_CRANBERRY, true);
                     if (Unit* plate = GetPlate())
                         plate->CastSpell(plate, SPELL_PLATE_CRANBERRY, true);
                     break;
                 case SPELL_VISUAL_THROW_SWEET_POTATO:
                 case SPELL_VISUAL_BOUNCE_SWEET_POTATO:
                     me->CastSpell(me, SPELL_STORE_SWEET_POTATO, true);
                     me->CastSpell(me, SPELL_CAN_EAT_SWEET_POTATO, true);
                     if (Unit* plate = GetPlate())
                         plate->CastSpell(plate, SPELL_PLATE_SWEET_POTATO, true);
                     break;
                 // AURA REMOVAL
                 case SPELL_STORE_SWEET_POTATO:
                     me->RemoveAura(SPELL_CAN_EAT_SWEET_POTATO);
                     if (Unit* plate = GetPlate())
                         plate->RemoveAura(SPELL_PLATE_SWEET_POTATO);
                     break;
                 case SPELL_STORE_TURKEY:
                     me->RemoveAura(SPELL_CAN_EAT_TURKEY);
                     if (Unit* plate = GetPlate())
                         plate->RemoveAura(SPELL_PLATE_TURKEY);
                     break;
                 case SPELL_STORE_PIE:
                     me->RemoveAura(SPELL_CAN_EAT_PIE);
                     if (Unit* plate = GetPlate())
                         plate->RemoveAura(SPELL_PLATE_PIE);
                     break;
                 case SPELL_STORE_STUFFING:
                     me->RemoveAura(SPELL_CAN_EAT_STUFFING);
                     if (Unit* plate = GetPlate())
                         plate->RemoveAura(SPELL_PLATE_STUFFING);
                     break;
                 case SPELL_STORE_CRANBERRY:
                     me->RemoveAura(SPELL_CAN_EAT_CRANBERRY);
                     if (Unit* plate = GetPlate())
                         plate->RemoveAura(SPELL_PLATE_CRANBERRY);
                     break;
             }
         }
References Unit::CastSpell(), GetPlate(), CreatureAI::me, Unit::RemoveAura(), SPELL_CAN_EAT_CRANBERRY, SPELL_CAN_EAT_PIE, SPELL_CAN_EAT_STUFFING, SPELL_CAN_EAT_SWEET_POTATO, SPELL_CAN_EAT_TURKEY, SPELL_PLATE_CRANBERRY, SPELL_PLATE_PIE, SPELL_PLATE_STUFFING, SPELL_PLATE_SWEET_POTATO, SPELL_PLATE_TURKEY, SPELL_STORE_CRANBERRY, SPELL_STORE_PIE, SPELL_STORE_STUFFING, SPELL_STORE_SWEET_POTATO, SPELL_STORE_TURKEY, SPELL_VISUAL_BOUNCE_CRANBERRY, SPELL_VISUAL_BOUNCE_PIE, SPELL_VISUAL_BOUNCE_STUFFING, SPELL_VISUAL_BOUNCE_SWEET_POTATO, SPELL_VISUAL_BOUNCE_TURKEY, SPELL_VISUAL_THROW_CRANBERRY, SPELL_VISUAL_THROW_PIE, SPELL_VISUAL_THROW_STUFFING, SPELL_VISUAL_THROW_SWEET_POTATO, and SPELL_VISUAL_THROW_TURKEY.
GetPlate()
Creature* npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::GetPlate () inline
Definition at line 133 of file pilgrims_bounty.cpp.
 { return plateGUID ? ObjectAccessor::GetCreature(*me, plateGUID) : nullptr; }
References ObjectAccessor::GetCreature(), CreatureAI::me, and plateGUID.
Referenced by DoAction(), and UpdateAI().
MoveInLineOfSight()
void npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from VehicleAI.
Definition at line 120 of file pilgrims_bounty.cpp.
 {}
PassengerBoarded()
void npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::PassengerBoarded (Unit * , int8 , bool) inline override virtual
== Fields =======================================
Reimplemented from CreatureAI.
Definition at line 123 of file pilgrims_bounty.cpp.
         {
             if (apply && who->GetTypeId() == TYPEID_PLAYER)
                 who->ToPlayer()->SetClientControl(me, 0, true);
         }
References ByteConverter::apply(), Object::GetTypeId(), CreatureAI::me, Player::SetClientControl(), Object::ToPlayer(), and TYPEID_PLAYER.
SpellHit()
void npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::SpellHit (Unit * , const SpellInfo * spellInfo) inline override virtual
Reimplemented from CreatureAI.
Definition at line 218 of file pilgrims_bounty.cpp.
         {
             switch (spellInfo->Id)
             {
                 case SPELL_FEAST_ON_SWEET_POTATOES:
                     if (Aura* aur = me->GetAura(SPELL_STORE_SWEET_POTATO))
                         aur->ModStackAmount(-1);
                     break;
                 case SPELL_FEAST_ON_TURKEY:
                     if (Aura* aur = me->GetAura(SPELL_STORE_TURKEY))
                         aur->ModStackAmount(-1);
                     break;
                 case SPELL_FEAST_ON_PIE:
                     if (Aura* aur = me->GetAura(SPELL_STORE_PIE))
                         aur->ModStackAmount(-1);
                     break;
                 case SPELL_FEAST_ON_STUFFING:
                     if (Aura* aur = me->GetAura(SPELL_STORE_STUFFING))
                         aur->ModStackAmount(-1);
                     break;
                 case SPELL_FEAST_ON_CRANBERRY:
                     if (Aura* aur = me->GetAura(SPELL_STORE_CRANBERRY))
                         aur->ModStackAmount(-1);
                     break;
             }
         }
References Unit::GetAura(), SpellInfo::Id, CreatureAI::me, SPELL_FEAST_ON_CRANBERRY, SPELL_FEAST_ON_PIE, SPELL_FEAST_ON_STUFFING, SPELL_FEAST_ON_SWEET_POTATOES, SPELL_FEAST_ON_TURKEY, SPELL_STORE_CRANBERRY, SPELL_STORE_PIE, SPELL_STORE_STUFFING, SPELL_STORE_SWEET_POTATO, and SPELL_STORE_TURKEY.
SpellHitTarget()
void npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::SpellHitTarget (Unit * target, const SpellInfo * spellInfo) inline override virtual
Reimplemented from CreatureAI.
Definition at line 209 of file pilgrims_bounty.cpp.
         {
             Unit* charm = target->GetCharm();
             if (!charm || !charm->ToCreature())
                 return;
             charm->ToCreature()->AI()->DoAction(spellInfo->Id);
         }
References Creature::AI(), UnitAI::DoAction(), Unit::GetCharm(), SpellInfo::Id, and Object::ToCreature().
UpdateAI()
void npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from VehicleAI.
Definition at line 245 of file pilgrims_bounty.cpp.
         {
             if (timerSpawnPlate)
             {
                 timerSpawnPlate += diff;
                 if (timerSpawnPlate >= 1000)
                 {
                     if (Vehicle* table = me->GetVehicle())
                         if (Unit* plateHolder = table->GetPassenger(6))
{
                             SeatMap::const_iterator itr = table->GetSeatIteratorForPassenger(me);
                             if (itr == table->Seats.end())
                                 return;
                             uint8 vehicleSeatId = itr->first;
                             Creature* plate = me->SummonCreature(NPC_STRUDY_PLATE, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), 0.0f);
                             if (!plate)
                                 return;
                             plateGUID = plate->GetGUID();
                             plate->EnterVehicle(plateHolder, vehicleSeatId);
                             timerSpawnPlate = 0;
                             timerRotateChair = 1;
                         }
                 }
             }
             if (timerRotateChair)
             {
                 timerRotateChair += diff;
                 if (timerRotateChair >= 1000)
                 {
                     if (Creature* plate = GetPlate())
                         me->SetFacingToObject(plate);
                     timerRotateChair = 0;
                 }
             }
         }
References Unit::EnterVehicle(), Object::GetGUID(), GetPlate(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetVehicle(), CreatureAI::me, NPC_STRUDY_PLATE, plateGUID, Unit::SetFacingToObject(), WorldObject::SummonCreature(), timerRotateChair, and timerSpawnPlate.
Member Data Documentation
plateGUID
ObjectGuid npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::plateGUID
Definition at line 129 of file pilgrims_bounty.cpp.
Referenced by GetPlate(), npc_pilgrims_bounty_chairAI(), and UpdateAI().
timerRotateChair
uint32 npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::timerRotateChair
Definition at line 131 of file pilgrims_bounty.cpp.
Referenced by npc_pilgrims_bounty_chairAI(), and UpdateAI().
timerSpawnPlate
uint32 npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::timerSpawnPlate
Definition at line 130 of file pilgrims_bounty.cpp.
Referenced by npc_pilgrims_bounty_chairAI(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Events/pilgrims_bounty.cpp