Azerotcore-wotlk: TicketMgr Class Reference
TicketMgr Class Reference
#include <TicketMgr.h>
Public Member Functions
void LoadTickets ()
void LoadSurveys ()
GmTicket * GetTicket (uint32 ticketId)
GmTicket * GetTicketByPlayer (ObjectGuid playerGuid)
GmTicket * GetOldestOpenTicket ()
void AddTicket (GmTicket *ticket)
void CloseTicket (uint32 ticketId, ObjectGuid source=ObjectGuid::Empty)
void ResolveAndCloseTicket (uint32 ticketId, ObjectGuid source)
void RemoveTicket (uint32 ticketId)
bool GetStatus () const
void SetStatus (bool status)
uint64 GetLastChange () const
void UpdateLastChange ()
uint32 GenerateTicketId ()
uint32 GetOpenTicketCount () const
uint32 GetNextSurveyID ()
void Initialize ()
void ResetTickets ()
void ShowList (ChatHandler &handler, bool onlineOnly) const
void ShowClosedList (ChatHandler &handler) const
void ShowEscalatedList (ChatHandler &handler) const
void SendTicket (WorldSession *session, GmTicket *ticket) const
Static Public Member Functions
static TicketMgr * instance ()
Protected Member Functions
void _RemoveTicket (uint32 ticketId, int64 source=-1, bool permanently=false)
Protected Attributes
GmTicketList _ticketList
bool _status
uint32 _lastTicketId
uint32 _lastSurveyId
uint32 _openTicketCount
uint64 _lastChange
Private Member Functions
TicketMgr ()
~TicketMgr ()
Detailed Description
Definition at line 184 of file TicketMgr.h.
Constructor & Destructor Documentation
TicketMgr()
TicketMgr::TicketMgr () private
Definition at line 254 of file TicketMgr.cpp.
 : _status(true), _lastTicketId(0), _lastSurveyId(0), _openTicketCount(0), _lastChange(time(nullptr)) { }
~TicketMgr()
TicketMgr::~TicketMgr () private
Definition at line 256 of file TicketMgr.cpp.
 {
     for (GmTicketList::const_iterator itr = _ticketList.begin(); itr != _ticketList.end(); ++itr)
         delete itr->second;
 }
References _ticketList.
Member Function Documentation
_RemoveTicket()
void TicketMgr::_RemoveTicket (uint32 ticketId, int64 source = -1, bool permanently = false) protected
AddTicket()
void TicketMgr::AddTicket (GmTicket * ticket)
Definition at line 350 of file TicketMgr.cpp.
 {
     _ticketList[ticket->GetId()] = ticket;
     if (!ticket->IsClosed())
         ++_openTicketCount;
     CharacterDatabaseTransaction trans = CharacterDatabaseTransaction(nullptr);
     ticket->SaveToDB(trans);
 }
References _openTicketCount, _ticketList, GmTicket::GetId(), GmTicket::IsClosed(), and GmTicket::SaveToDB().
CloseTicket()
void TicketMgr::CloseTicket (uint32 ticketId, ObjectGuid source = ObjectGuid::Empty)
Definition at line 359 of file TicketMgr.cpp.
 {
     if (GmTicket* ticket = GetTicket(ticketId))
     {
         CharacterDatabaseTransaction trans = CharacterDatabaseTransaction(nullptr);
         ticket->SetClosedBy(source);
         if (source)
             --_openTicketCount;
         ticket->SaveToDB(trans);
     }
 }
References _openTicketCount, and GetTicket().
GenerateTicketId()
uint32 TicketMgr::GenerateTicketId () inline
Definition at line 234 of file TicketMgr.h.
 { return ++_lastTicketId; }
References _lastTicketId.
GetLastChange()
uint64 TicketMgr::GetLastChange () const inline
Definition at line 231 of file TicketMgr.h.
 { return _lastChange; }
References _lastChange.
GetNextSurveyID()
uint32 TicketMgr::GetNextSurveyID () inline
Definition at line 236 of file TicketMgr.h.
 { return ++_lastSurveyId; }
References _lastSurveyId.
GetOldestOpenTicket()
GmTicket* TicketMgr::GetOldestOpenTicket () inline
Definition at line 214 of file TicketMgr.h.
     {
         for (GmTicketList::const_iterator itr = _ticketList.begin(); itr != _ticketList.end(); ++itr)
             if (itr->second && !itr->second->IsClosed() && !itr->second->IsCompleted())
                 return itr->second;
         return nullptr;
     }
References _ticketList.
GetOpenTicketCount()
uint32 TicketMgr::GetOpenTicketCount () const inline
Definition at line 235 of file TicketMgr.h.
 { return _openTicketCount; }
References _openTicketCount.
GetStatus()
bool TicketMgr::GetStatus () const inline
Definition at line 228 of file TicketMgr.h.
 { return _status; }
References _status.
GetTicket()
GmTicket* TicketMgr::GetTicket (uint32 ticketId) inline
Definition at line 196 of file TicketMgr.h.
     {
         GmTicketList::iterator itr = _ticketList.find(ticketId);
         if (itr != _ticketList.end())
             return itr->second;
         return nullptr;
     }
References _ticketList.
Referenced by CloseTicket(), RemoveTicket(), and ResolveAndCloseTicket().
GetTicketByPlayer()
GmTicket* TicketMgr::GetTicketByPlayer (ObjectGuid playerGuid) inline
Definition at line 205 of file TicketMgr.h.
     {
         for (GmTicketList::const_iterator itr = _ticketList.begin(); itr != _ticketList.end(); ++itr)
             if (itr->second && itr->second->IsFromPlayer(playerGuid) && !itr->second->IsClosed())
                 return itr->second;
         return nullptr;
     }
References _ticketList.
Initialize()
void TicketMgr::Initialize (void)
Definition at line 268 of file TicketMgr.cpp.
 { SetStatus(sWorld->getBoolConfig(CONFIG_ALLOW_TICKETS)); }
References CONFIG_ALLOW_TICKETS, SetStatus(), and sWorld.
instance()
TicketMgr * TicketMgr::instance () static
Definition at line 262 of file TicketMgr.cpp.
 {
     static TicketMgr instance;
     return &instance;
 }
LoadSurveys()
void TicketMgr::LoadSurveys ()
Definition at line 337 of file TicketMgr.cpp.
 {
     // we don't actually load anything into memory here as there's no reason to
     _lastSurveyId = 0;
     uint32 oldMSTime = getMSTime();
     if (QueryResult result = CharacterDatabase.Query("SELECT MAX(surveyId) FROM gm_survey"))
         _lastSurveyId = (*result)[0].GetUInt32();
     LOG_INFO("server.loading", ">> Loaded GM Survey count from database in %u ms", GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
 }
References _lastSurveyId, CharacterDatabase, getMSTime(), GetMSTimeDiffToNow(), and LOG_INFO.
LoadTickets()
void TicketMgr::LoadTickets ()
Definition at line 291 of file TicketMgr.cpp.
 {
     uint32 oldMSTime = getMSTime();
     for (GmTicketList::const_iterator itr = _ticketList.begin(); itr != _ticketList.end(); ++itr)
         delete itr->second;
     _ticketList.clear();
     _lastTicketId = 0;
     _openTicketCount = 0;
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_GM_TICKETS);
     PreparedQueryResult result = CharacterDatabase.Query(stmt);
     if (!result)
     {
         LOG_INFO("server.loading", ">> Loaded 0 GM tickets. DB table `gm_ticket` is empty!");
         return;
     }
     uint32 count = 0;
     do
     {
         Field* fields = result->Fetch();
         GmTicket* ticket = new GmTicket();
         if (!ticket->LoadFromDB(fields))
         {
             delete ticket;
             continue;
         }
         if (!ticket->IsClosed())
             ++_openTicketCount;
         // Update max ticket id if necessary
         uint32 id = ticket->GetId();
         if (_lastTicketId < id)
             _lastTicketId = id;
         _ticketList[id] = ticket;
         ++count;
     } while (result->NextRow());
     LOG_INFO("server.loading", ">> Loaded %u GM tickets in %u ms", count, GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
 }
References _lastTicketId, _openTicketCount, _ticketList, CHAR_SEL_GM_TICKETS, CharacterDatabase, GmTicket::GetId(), getMSTime(), GetMSTimeDiffToNow(), GmTicket::IsClosed(), GmTicket::LoadFromDB(), and LOG_INFO.
RemoveTicket()
void TicketMgr::RemoveTicket (uint32 ticketId)
Definition at line 371 of file TicketMgr.cpp.
 {
     if (GmTicket* ticket = GetTicket(ticketId))
     {
         ticket->DeleteFromDB();
         _ticketList.erase(ticketId);
         delete ticket;
     }
 }
References _ticketList, and GetTicket().
ResetTickets()
void TicketMgr::ResetTickets ()
Definition at line 270 of file TicketMgr.cpp.
 {
     for (GmTicketList::const_iterator itr = _ticketList.begin(); itr != _ticketList.end();)
     {
         if (itr->second->IsClosed())
         {
             uint32 ticketId = itr->second->GetId();
             ++itr;
             sTicketMgr->RemoveTicket(ticketId);
         }
         else
             ++itr;
     }
     _lastTicketId = 0;
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_ALL_GM_TICKETS);
     CharacterDatabase.Execute(stmt);
 }
References _lastTicketId, _ticketList, CHAR_DEL_ALL_GM_TICKETS, CharacterDatabase, and sTicketMgr.
ResolveAndCloseTicket()
void TicketMgr::ResolveAndCloseTicket (uint32 ticketId, ObjectGuid source)
Definition at line 381 of file TicketMgr.cpp.
 {
     if (GmTicket* ticket = GetTicket(ticketId))
     {
         CharacterDatabaseTransaction trans = CharacterDatabaseTransaction(nullptr);
         ticket->SetClosedBy(source);
         ticket->SetResolvedBy(source);
         if (source)
             --_openTicketCount;
         ticket->SaveToDB(trans);
     }
 }
References _openTicketCount, and GetTicket().
SendTicket()
void TicketMgr::SendTicket (WorldSession * session, GmTicket * ticket) const
Definition at line 419 of file TicketMgr.cpp.
 {
     WorldPacket data(SMSG_GMTICKET_GETTICKET, (ticket ? (4 + 4 + 1 + 4 + 4 + 4 + 1 + 1) : 4));
     if (ticket)
         ticket->WritePacket(data);
     else
         data << uint32(GMTICKET_STATUS_DEFAULT);
     session->SendPacket(&data);
 }
References GMTICKET_STATUS_DEFAULT, WorldSession::SendPacket(), SMSG_GMTICKET_GETTICKET, and GmTicket::WritePacket().
SetStatus()
void TicketMgr::SetStatus (bool status) inline
Definition at line 229 of file TicketMgr.h.
 { _status = status; }
References _status.
Referenced by Initialize().
ShowClosedList()
void TicketMgr::ShowClosedList (ChatHandler & handler) const
Definition at line 403 of file TicketMgr.cpp.
 {
     handler.SendSysMessage(LANG_COMMAND_TICKETSHOWCLOSEDLIST);
     for (GmTicketList::const_iterator itr = _ticketList.begin(); itr != _ticketList.end(); ++itr)
         if (itr->second->IsClosed())
             handler.SendSysMessage(itr->second->FormatMessageString(handler).c_str());
 }
References _ticketList, LANG_COMMAND_TICKETSHOWCLOSEDLIST, and ChatHandler::SendSysMessage().
ShowEscalatedList()
void TicketMgr::ShowEscalatedList (ChatHandler & handler) const
Definition at line 411 of file TicketMgr.cpp.
 {
     handler.SendSysMessage(LANG_COMMAND_TICKETSHOWESCALATEDLIST);
     for (GmTicketList::const_iterator itr = _ticketList.begin(); itr != _ticketList.end(); ++itr)
         if (!itr->second->IsClosed() && itr->second->GetEscalatedStatus() == TICKET_IN_ESCALATION_QUEUE)
             handler.SendSysMessage(itr->second->FormatMessageString(handler).c_str());
 }
References _ticketList, LANG_COMMAND_TICKETSHOWESCALATEDLIST, ChatHandler::SendSysMessage(), and TICKET_IN_ESCALATION_QUEUE.
ShowList()
void TicketMgr::ShowList (ChatHandler & handler, bool onlineOnly) const
Definition at line 394 of file TicketMgr.cpp.
 {
     handler.SendSysMessage(onlineOnly ? LANG_COMMAND_TICKETSHOWONLINELIST : LANG_COMMAND_TICKETSHOWLIST);
     for (GmTicketList::const_iterator itr = _ticketList.begin(); itr != _ticketList.end(); ++itr)
         if (!itr->second->IsClosed() && !itr->second->IsCompleted())
             if (!onlineOnly || itr->second->GetPlayer())
                 handler.SendSysMessage(itr->second->FormatMessageString(handler).c_str());
 }
References _ticketList, LANG_COMMAND_TICKETSHOWLIST, LANG_COMMAND_TICKETSHOWONLINELIST, and ChatHandler::SendSysMessage().
UpdateLastChange()
void TicketMgr::UpdateLastChange () inline
Definition at line 232 of file TicketMgr.h.
 { _lastChange = uint64(time(nullptr)); }
References _lastChange.
Member Data Documentation
_lastChange
uint64 TicketMgr::_lastChange protected
Definition at line 256 of file TicketMgr.h.
Referenced by GetLastChange(), and UpdateLastChange().
_lastSurveyId
uint32 TicketMgr::_lastSurveyId protected
Definition at line 254 of file TicketMgr.h.
Referenced by GetNextSurveyID(), and LoadSurveys().
_lastTicketId
uint32 TicketMgr::_lastTicketId protected
Definition at line 253 of file TicketMgr.h.
Referenced by GenerateTicketId(), LoadTickets(), and ResetTickets().
_openTicketCount
uint32 TicketMgr::_openTicketCount protected
Definition at line 255 of file TicketMgr.h.
Referenced by AddTicket(), CloseTicket(), GetOpenTicketCount(), LoadTickets(), and ResolveAndCloseTicket().
_status
bool TicketMgr::_status protected
Definition at line 252 of file TicketMgr.h.
Referenced by GetStatus(), and SetStatus().
_ticketList
GmTicketList TicketMgr::_ticketList protected
Definition at line 250 of file TicketMgr.h.
Referenced by AddTicket(), GetOldestOpenTicket(), GetTicket(), GetTicketByPlayer(), LoadTickets(), RemoveTicket(), ResetTickets(), ShowClosedList(), ShowEscalatedList(), ShowList(), and ~TicketMgr().
The documentation for this class was generated from the following files:
src/server/game/Tickets/TicketMgr.h
src/server/game/Tickets/TicketMgr.cpp