Azerotcore-wotlk: go_chromaggus_lever::go_chromaggus_leverAI Struct Reference
go_chromaggus_lever::go_chromaggus_leverAI Struct Reference
Public Member Functions
go_chromaggus_leverAI (GameObject *go)
bool OnGossipHello (Player *player)
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void UpdateAI (uint32)
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32)
virtual ObjectGuid GetGUID (int32) const
virtual bool GossipHello (Player *, bool)
virtual bool GossipSelect (Player *, uint32, uint32)
virtual bool GossipSelectCode (Player *, uint32, uint32, char const *)
virtual bool QuestAccept (Player *, Quest const *)
virtual bool QuestReward (Player *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *)
virtual void Destroyed (Player *, uint32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void OnGameEvent (bool, uint16)
virtual void OnStateChanged (uint32, Unit *)
virtual void EventInform (uint32)
virtual void SpellHit (Unit *, const SpellInfo *)
virtual bool CanBeSeen (Player const *)
Private Attributes
InstanceScript * _instance
Additional Inherited Members
Static Public Member Functions inherited from GameObjectAI
static int Permissible (GameObject const *go)
Protected Attributes inherited from GameObjectAI
GameObject *const me
Detailed Description
Definition at line 304 of file boss_chromaggus.cpp.
Constructor & Destructor Documentation
go_chromaggus_leverAI()
go_chromaggus_lever::go_chromaggus_leverAI::go_chromaggus_leverAI (GameObject * go) inline
Definition at line 306 of file boss_chromaggus.cpp.
 : GameObjectAI(go), _instance(go->GetInstanceScript()) { }
Member Function Documentation
OnGossipHello()
bool go_chromaggus_lever::go_chromaggus_leverAI::OnGossipHello (Player * player) inline
Definition at line 308 of file boss_chromaggus.cpp.
             {
                 if (_instance->GetBossState(DATA_CHROMAGGUS) != DONE && _instance->GetBossState(DATA_CHROMAGGUS) != IN_PROGRESS)
                 {
                     _instance->SetBossState(DATA_CHROMAGGUS, IN_PROGRESS);
                     if (Creature* creature = _instance->instance->GetCreature(_instance->GetGuidData(DATA_CHROMAGGUS)))
                         creature->AI()->AttackStart(player);
                     if (GameObject* go = _instance->instance->GetGameObject(_instance->GetGuidData(DATA_GO_CHROMAGGUS_DOOR)))
                         _instance->HandleGameObject(ObjectGuid::Empty, true, go);
                 }
                 me->SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE | GO_FLAG_IN_USE);
                 me->SetGoState(GO_STATE_ACTIVE);
                 return true;
             }
References _instance, DATA_CHROMAGGUS, DATA_GO_CHROMAGGUS_DOOR, DONE, ObjectGuid::Empty, GAMEOBJECT_FLAGS, InstanceScript::GetBossState(), Map::GetCreature(), Map::GetGameObject(), InstanceScript::GetGuidData(), GO_FLAG_IN_USE, GO_FLAG_NOT_SELECTABLE, GO_STATE_ACTIVE, InstanceScript::HandleGameObject(), IN_PROGRESS, InstanceScript::instance, GameObjectAI::me, InstanceScript::SetBossState(), Object::SetFlag(), and GameObject::SetGoState().
Member Data Documentation
_instance
InstanceScript* go_chromaggus_lever::go_chromaggus_leverAI::_instance private
Definition at line 328 of file boss_chromaggus.cpp.
Referenced by OnGossipHello().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/BlackrockMountain/BlackwingLair/boss_chromaggus.cpp