Azerotcore-wotlk: AreaTrigger_at_celestial_planetarium_enterance Class Reference
AreaTrigger_at_celestial_planetarium_enterance Class Reference
Public Member Functions
AreaTrigger_at_celestial_planetarium_enterance ()
bool OnTrigger (Player *player, AreaTrigger const *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 381 of file ulduar.cpp.
Constructor & Destructor Documentation
AreaTrigger_at_celestial_planetarium_enterance()
AreaTrigger_at_celestial_planetarium_enterance::AreaTrigger_at_celestial_planetarium_enterance () inline
Definition at line 384 of file ulduar.cpp.
         : AreaTriggerScript("at_celestial_planetarium_enterance")
     {
     }
Member Function Documentation
OnTrigger()
bool AreaTrigger_at_celestial_planetarium_enterance::OnTrigger (Player * player, AreaTrigger const *) inline override virtual
Reimplemented from AreaTriggerScript.
Definition at line 389 of file ulduar.cpp.
     {
         if (player->IsAlive())
             if (uint32 questId = (player->GetMap()->Is25ManRaid() ? 13816 : 13607 /*QUEST_CELESTIAL_PLANETARIUM*/))
                 if (player->GetQuestStatus(questId) == QUEST_STATUS_INCOMPLETE)
                     player->AreaExploredOrEventHappens(questId);
         return false;
     }
References Player::AreaExploredOrEventHappens(), WorldObject::GetMap(), Player::GetQuestStatus(), Map::Is25ManRaid(), Unit::IsAlive(), and QUEST_STATUS_INCOMPLETE.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/ulduar.cpp