Azerotcore-wotlk: deps/fmt/include/fmt/xchar.h File Reference
xchar.h File Reference
#include <cwchar>
#include <tuple>
#include "format.h"
Classes
struct is_char< wchar_t >
struct is_char< detail::char8_type >
struct is_char< char16_t >
struct is_char< char32_t >
Namespaces
detail
literals
Typedefs
template<typename T >
using detail::is_exotic_char = bool_constant<!std::is_same< T, char >::value >
using wstring_view = basic_string_view< wchar_t >
using wformat_parse_context = basic_format_parse_context< wchar_t >
using wformat_context = buffer_context< wchar_t >
using wformat_args = basic_format_args< wformat_context >
using wmemory_buffer = basic_memory_buffer< wchar_t >
template<typename... Args>
using wformat_string = basic_format_string< wchar_t, type_identity_t< Args >... >
Functions
template<typename... Args>
constexpr format_arg_store< wformat_context, Args... > make_wformat_args (const Args &... args)
constexpr auto literals::operator""_format (const wchar_t *s, size_t n) -> detail::udl_formatter< wchar_t >
template<typename It , typename Sentinel >
auto join (It begin, Sentinel end, wstring_view sep) -> join_view< It, Sentinel, wchar_t >
template<typename Range >
auto join (Range &&range, wstring_view sep) -> join_view< detail::iterator_t< Range >, detail::sentinel_t< Range >, wchar_t >
template<typename T >
auto join (std::initializer_list< T > list, wstring_view sep) -> join_view< const T *, const T *, wchar_t >
template<typename Char , FMT_ENABLE_IF(!std::is_same< Char, char >::value) >
auto vformat (basic_string_view< Char > format_str, basic_format_args< buffer_context< type_identity_t< Char >>> args) -> std::basic_string< Char >
template<typename S , typename... Args, typename Char = char_t<S>, FMT_ENABLE_IF(!std::is_same< Char, char >::value) >
auto format (const S &format_str, Args &&... args) -> std::basic_string< Char >
template<typename Locale , typename S , typename Char = char_t<S>, FMT_ENABLE_IF(detail::is_locale< Locale >::value && detail::is_exotic_char< Char >::value) >
auto vformat (const Locale &loc, const S &format_str, basic_format_args< buffer_context< type_identity_t< Char >>> args) -> std::basic_string< Char >
template<typename Locale , typename S , typename... Args, typename Char = char_t<S>, FMT_ENABLE_IF(detail::is_locale< Locale >::value && detail::is_exotic_char< Char >::value) >
auto format (const Locale &loc, const S &format_str, Args &&... args) -> std::basic_string< Char >
template<typename OutputIt , typename S , typename Char = char_t<S>, FMT_ENABLE_IF(detail::is_output_iterator< OutputIt, Char >::value && detail::is_exotic_char< Char >::value) >
auto vformat_to (OutputIt out, const S &format_str, basic_format_args< buffer_context< type_identity_t< Char >>> args) -> OutputIt
template<typename OutputIt , typename S , typename... Args, typename Char = char_t<S>, FMT_ENABLE_IF(detail::is_output_iterator< OutputIt, Char >::value && detail::is_exotic_char< Char >::value) >
auto format_to (OutputIt out, const S &fmt, Args &&... args) -> OutputIt
template<typename S , typename... Args, typename Char , size_t SIZE, typename Allocator , FMT_ENABLE_IF(detail::is_string< S >::value) >
FMT_DEPRECATED auto format_to (basic_memory_buffer< Char, SIZE, Allocator > &buf, const S &format_str, Args &&... args) -> typename buffer_context< Char >::iterator
template<typename Locale , typename S , typename OutputIt , typename... Args, typename Char = char_t<S>, FMT_ENABLE_IF(detail::is_output_iterator< OutputIt, Char >::value && detail::is_locale< Locale >::value && detail::is_exotic_char< Char >::value) >
auto vformat_to (OutputIt out, const Locale &loc, const S &format_str, basic_format_args< buffer_context< type_identity_t< Char >>> args) -> OutputIt
template<typename OutputIt , typename Locale , typename S , typename... Args, typename Char = char_t<S>, bool enable = detail::is_output_iterator<OutputIt, Char>::value&& detail::is_locale<Locale>::value&& detail::is_exotic_char<Char>::value>
auto format_to (OutputIt out, const Locale &loc, const S &format_str, Args &&... args) -> typename std::enable_if< enable, OutputIt >::type
template<typename OutputIt , typename Char , typename... Args, FMT_ENABLE_IF(detail::is_output_iterator< OutputIt, Char >::value && detail::is_exotic_char< Char >::value) >
auto vformat_to_n (OutputIt out, size_t n, basic_string_view< Char > format_str, basic_format_args< buffer_context< type_identity_t< Char >>> args) -> format_to_n_result< OutputIt >
template<typename OutputIt , typename S , typename... Args, typename Char = char_t<S>, FMT_ENABLE_IF(detail::is_output_iterator< OutputIt, Char >::value && detail::is_exotic_char< Char >::value) >
auto format_to_n (OutputIt out, size_t n, const S &fmt, const Args &... args) -> format_to_n_result< OutputIt >
template<typename S , typename... Args, typename Char = char_t<S>, FMT_ENABLE_IF(detail::is_exotic_char< Char >::value) >
auto formatted_size (const S &fmt, Args &&... args) -> size_t
void vprint (std::FILE *f, wstring_view fmt, wformat_args args)
void vprint (wstring_view fmt, wformat_args args)
template<typename... T>
void print (std::FILE *f, wformat_string< T... > fmt, T &&... args)
template<typename... T>
void print (wformat_string< T... > fmt, T &&... args)
template<typename T >
auto to_wstring (const T &value) -> std::wstring
Typedef Documentation
wformat_args
using wformat_args = basic_format_args<wformat_context>
Definition at line 27 of file xchar.h.
wformat_context
using wformat_context = buffer_context<wchar_t>
Definition at line 26 of file xchar.h.
wformat_parse_context
using wformat_parse_context = basic_format_parse_context<wchar_t>
Definition at line 25 of file xchar.h.
wformat_string
template<typename... Args> using wformat_string = basic_format_string<wchar_t, type_identity_t<Args>...>
Definition at line 35 of file xchar.h.
wmemory_buffer
using wmemory_buffer = basic_memory_buffer<wchar_t>
Definition at line 28 of file xchar.h.
wstring_view
using wstring_view = basic_string_view<wchar_t>
Definition at line 24 of file xchar.h.
Function Documentation
format() [1/2]
template<typename Locale , typename S , typename... Args, typename Char = char_t<S>, FMT_ENABLE_IF(detail::is_locale< Locale >::value && detail::is_exotic_char< Char >::value) > auto format (const Locale & loc, const S & format_str, Args &&... args) -> std::basic_string<Char> inline
Definition at line 113 of file xchar.h.
{
   return detail::vformat(loc, to_string_view(format_str),
                          fmt::make_args_checked<Args...>(format_str, args...));
 }
References to_string_view(), and vformat().
format() [2/2]
template<typename S , typename... Args, typename Char = char_t<S>, FMT_ENABLE_IF(!std::is_same< Char, char >::value) > auto format (const S & format_str, Args &&... args) -> std::basic_string<Char>
Definition at line 94 of file xchar.h.
{
   const auto& vargs = fmt::make_args_checked<Args...>(format_str, args...);
   return vformat(to_string_view(format_str), vargs);
 }
References make_args_checked(), to_string_view(), and vformat().
Referenced by to_wstring().
format_to() [1/3]
template<typename S , typename... Args, typename Char , size_t SIZE, typename Allocator , FMT_ENABLE_IF(detail::is_string< S >::value) > FMT_DEPRECATED auto format_to (basic_memory_buffer< Char, SIZE, Allocator > & buf, const S & format_str, Args &&... args) -> typename buffer_context<Char>::iterator
Definition at line 141 of file xchar.h.
{
   const auto& vargs = fmt::make_args_checked<Args...>(format_str, args...);
   detail::vformat_to(buf, to_string_view(format_str), vargs, {});
   return detail::buffer_appender<Char>(buf);
 }
References make_args_checked(), to_string_view(), and vformat_to().
format_to() [2/3]
template<typename OutputIt , typename Locale , typename S , typename... Args, typename Char = char_t<S>, bool enable = detail::is_output_iterator<OutputIt, Char>::value&& detail::is_locale<Locale>::value&& detail::is_exotic_char<Char>::value> auto format_to (OutputIt out, const Locale & loc, const S & format_str, Args &&... args) -> typename std::enable_if<enable, OutputIt>::type inline
Definition at line 167 of file xchar.h.
{
   const auto& vargs = fmt::make_args_checked<Args...>(format_str, args...);
   return vformat_to(out, loc, to_string_view(format_str), vargs);
 }
References make_args_checked(), to_string_view(), and vformat_to().
format_to() [3/3]
template<typename OutputIt , typename S , typename... Args, typename Char = char_t<S>, FMT_ENABLE_IF(detail::is_output_iterator< OutputIt, Char >::value && detail::is_exotic_char< Char >::value) > auto format_to (OutputIt out, const S & fmt, Args &&... args) -> OutputIt inline
Definition at line 134 of file xchar.h.
{
   const auto& vargs = fmt::make_args_checked<Args...>(fmt, args...);
   return vformat_to(out, to_string_view(fmt), vargs);
 }
References fmt, make_args_checked(), to_string_view(), and vformat_to().
format_to_n()
template<typename OutputIt , typename S , typename... Args, typename Char = char_t<S>, FMT_ENABLE_IF(detail::is_output_iterator< OutputIt, Char >::value && detail::is_exotic_char< Char >::value) > auto format_to_n (OutputIt out, size_t n, const S & fmt, const Args &... args) -> format_to_n_result<OutputIt> inline
Definition at line 191 of file xchar.h.
{
   const auto& vargs = fmt::make_args_checked<Args...>(fmt, args...);
   return vformat_to_n(out, n, to_string_view(fmt), vargs);
 }
References fmt, make_args_checked(), to_string_view(), and vformat_to_n().
formatted_size()
template<typename S , typename... Args, typename Char = char_t<S>, FMT_ENABLE_IF(detail::is_exotic_char< Char >::value) > auto formatted_size (const S & fmt, Args &&... args) -> size_t inline
Definition at line 199 of file xchar.h.
{
   detail::counting_buffer<Char> buf;
   const auto& vargs = fmt::make_args_checked<Args...>(fmt, args...);
   detail::vformat_to(buf, to_string_view(fmt), vargs);
   return buf.count();
 }
References fmt, make_args_checked(), to_string_view(), and vformat_to().
join() [1/3]
template<typename It , typename Sentinel > auto join (It begin, Sentinel end, wstring_view sep) -> join_view<It, Sentinel, wchar_t>
Definition at line 63 of file xchar.h.
{
   return {begin, end, sep};
 }
Referenced by join().
join() [2/3]
template<typename Range > auto join (Range && range, wstring_view sep) -> join_view<detail::iterator_t<Range>, detail::sentinel_t<Range>, wchar_t>
Definition at line 69 of file xchar.h.
{
   return join(std::begin(range), std::end(range), sep);
 }
References join().
join() [3/3]
template<typename T > auto join (std::initializer_list< T > list, wstring_view sep) -> join_view<const T*, const T*, wchar_t>
Definition at line 76 of file xchar.h.
{
   return join(std::begin(list), std::end(list), sep);
 }
References join(), and list().
make_wformat_args()
template<typename... Args> constexpr format_arg_store<wformat_context, Args...> make_wformat_args (const Args &... args) constexpr
Definition at line 44 of file xchar.h.
{
   return {args...};
 }
Referenced by print().
print() [1/2]
template<typename... T> void print (std::FILE * f, wformat_string< T... > fmt, T &&... args)
Definition at line 219 of file xchar.h.
{
   return vprint(f, wstring_view(fmt), make_wformat_args(args...));
 }
References f(), fmt, make_wformat_args(), and vprint().
print() [2/2]
template<typename... T> void print (wformat_string< T... > fmt, T &&... args)
Definition at line 223 of file xchar.h.
{
   return vprint(wstring_view(fmt), make_wformat_args(args...));
 }
References fmt, make_wformat_args(), and vprint().
to_wstring()
template<typename T > auto to_wstring (const T & value) -> std::wstring inline
Converts value to std::wstring using the default format for type T.
Definition at line 230 of file xchar.h.
{
   return format(FMT_STRING(L"{}"), value);
 }
References FMT_STRING, and format().
vformat() [1/2]
template<typename Char , FMT_ENABLE_IF(!std::is_same< Char, char >::value) > auto vformat (basic_string_view< Char > format_str, basic_format_args< buffer_context< type_identity_t< Char >>> args) -> std::basic_string<Char>
Definition at line 82 of file xchar.h.
{
   basic_memory_buffer<Char> buffer;
   detail::vformat_to(buffer, format_str, args);
   return to_string(buffer);
 }
References buffer, to_string(), and vformat_to().
Referenced by format(), and vformat().
vformat() [2/2]
template<typename Locale , typename S , typename Char = char_t<S>, FMT_ENABLE_IF(detail::is_locale< Locale >::value && detail::is_exotic_char< Char >::value) > auto vformat (const Locale & loc, const S & format_str, basic_format_args< buffer_context< type_identity_t< Char >>> args) -> std::basic_string<Char> inline
Definition at line 102 of file xchar.h.
{
   return detail::vformat(loc, to_string_view(format_str), args);
 }
References to_string_view(), and vformat().
vformat_to() [1/2]
template<typename Locale , typename S , typename OutputIt , typename... Args, typename Char = char_t<S>, FMT_ENABLE_IF(detail::is_output_iterator< OutputIt, Char >::value && detail::is_locale< Locale >::value && detail::is_exotic_char< Char >::value) > auto vformat_to (OutputIt out, const Locale & loc, const S & format_str, basic_format_args< buffer_context< type_identity_t< Char >>> args) -> OutputIt inline
Definition at line 154 of file xchar.h.
{
   auto&& buf = detail::get_buffer<Char>(out);
   vformat_to(buf, to_string_view(format_str), args, detail::locale_ref(loc));
   return detail::get_iterator(buf);
 }
References get_iterator(), to_string_view(), and vformat_to().
vformat_to() [2/2]
template<typename OutputIt , typename S , typename Char = char_t<S>, FMT_ENABLE_IF(detail::is_output_iterator< OutputIt, Char >::value && detail::is_exotic_char< Char >::value) > auto vformat_to (OutputIt out, const S & format_str, basic_format_args< buffer_context< type_identity_t< Char >>> args) -> OutputIt
Definition at line 122 of file xchar.h.
                 {
   auto&& buf = detail::get_buffer<Char>(out);
   detail::vformat_to(buf, to_string_view(format_str), args);
   return detail::get_iterator(buf);
 }
References get_iterator(), and to_string_view().
Referenced by format_to(), formatted_size(), vformat(), vformat_to(), vformat_to_n(), and vprint().
vformat_to_n()
template<typename OutputIt , typename Char , typename... Args, FMT_ENABLE_IF(detail::is_output_iterator< OutputIt, Char >::value && detail::is_exotic_char< Char >::value) > auto vformat_to_n (OutputIt out, size_t n, basic_string_view< Char > format_str, basic_format_args< buffer_context< type_identity_t< Char >>> args) -> format_to_n_result<OutputIt> inline
Definition at line 177 of file xchar.h.
{
   detail::iterator_buffer<OutputIt, Char, detail::fixed_buffer_traits> buf(out,
                                                                            n);
   detail::vformat_to(buf, format_str, args);
   return {buf.out(), buf.count()};
 }
References vformat_to().
Referenced by format_to_n().
vprint() [1/2]
void vprint (std::FILE * f, wstring_view fmt, wformat_args args) inline
Definition at line 206 of file xchar.h.
{
   wmemory_buffer buffer;
   detail::vformat_to(buffer, fmt, args);
   buffer.push_back(L'\0');
   if (std::fputws(buffer.data(), f) == -1)
     FMT_THROW(system_error(errno, FMT_STRING("cannot write to file")));
 }
References buffer, buffer< T >::data(), errno, f(), fmt, FMT_STRING, FMT_THROW, buffer< T >::push_back(), system_error(), and vformat_to().
Referenced by print(), and vprint().
vprint() [2/2]
void vprint (wstring_view fmt, wformat_args args) inline
Definition at line 214 of file xchar.h.
{
   vprint(stdout, fmt, args);
 }
References fmt, and vprint().