Azerotcore-wotlk: G3D::NetworkDevice Class Reference
G3D::NetworkDevice Class Reference
Abstraction of network (socket) functionality.
#include <NetworkDevice.h>
Classes
class EthernetAdapter
Description of an ethernet or wireless ethernet adapter.
Public Member Functions
~NetworkDevice ()
const Array< EthernetAdapter > & adapterArray () const
const Array< uint32 > & broadcastAddressArray () const
void describeSystem (TextOutput &t)
void describeSystem (std::string &s)
std::string localHostName () const
void localHostAddresses (Array< NetAddress > &array) const
Static Public Member Functions
static std::string formatIP (uint32 ip)
static std::string formatMAC (const uint8 mac[6])
static NetworkDevice * instance ()
static void cleanup ()
Private Member Functions
void closesocket (SOCKET &sock) const
bool bind (SOCKET sock, const NetAddress &addr) const
NetworkDevice ()
bool init ()
void _cleanup ()
void addAdapter (const EthernetAdapter &a)
Private Attributes
bool initialized
Array< EthernetAdapter > m_adapterArray
Array< uint32 > m_broadcastAddresses
Static Private Attributes
static NetworkDevice * s_instance = NULL
Friends
class Conduit
class LightweightConduit
class ReliableConduit
class NetListener
Detailed Description
Abstraction of network (socket) functionality.
An abstraction over sockets that provides a message-based network infrastructure optimized for sending many small (~500 bytes) messages. All functions always return immediately.
Create only one NetworkDevice per process (a WinSock restriction).
NetworkDevice is technically not thread safe. However, as long as you use different conduits on different threads (or lock conduits before sending), you will encounter no problems sharing the single NetworkDevice across multiple threads. That is, do not invoke the same Conduit's send or receive method on two threads at once.
This assumes that the underlying WinSock/BSD sockets implementation is thread safe. That is not guaranteed, but in practice seems to always be true (see http://tangentsoft.net/wskfaq/intermediate.html#threadsafety)
IP networks use "network byte order" (big-endian) for communicating integers. "Host byte order" is the endian-ness of the local machine (typically little-endian; see System::endian). The C functions htonl() and ntohl() convert 32-bit values between these formats. G3D only ever exposes host byte order, so programmers rarely need to be aware of the distinction.
Deprecated:
Definition at line 608 of file NetworkDevice.h.
Constructor & Destructor Documentation
NetworkDevice()
G3D::NetworkDevice::NetworkDevice () private
Definition at line 130 of file NetworkDevice.cpp.
{
     initialized  = false;
 }
References initialized.
Referenced by instance().
~NetworkDevice()
G3D::NetworkDevice::~NetworkDevice ()
Definition at line 135 of file NetworkDevice.cpp.
{
 }
Member Function Documentation
_cleanup()
void G3D::NetworkDevice::_cleanup () private
Definition at line 475 of file NetworkDevice.cpp.
{
     debugAssert(initialized);
 #   ifdef G3D_WINDOWS
     // Now handled through enet
 //        WSACleanup();
 #   endif
 }
References debugAssert, and initialized.
Referenced by cleanup().
adapterArray()
const Array<EthernetAdapter>& G3D::NetworkDevice::adapterArray () const inline
Returns the available ethernet adapters for the current machine that are online. Does not include the loopback adapter for localhost.
Definition at line 686 of file NetworkDevice.h.
{
         return m_adapterArray;
     }
References m_adapterArray.
addAdapter()
void G3D::NetworkDevice::addAdapter (const EthernetAdapter & a) private
Called from init to update m_adapterArray and m_broadcastAddresses.
Definition at line 223 of file NetworkDevice.cpp.
{
     m_adapterArray.append(a);
     if (a.broadcast != 0) {
         int i = m_broadcastAddresses.findIndex(a.broadcast);
         if (i == -1) {
             m_broadcastAddresses.append(a.broadcast);
         }
     }
 }
References mpq::a, G3D::Array< T, MIN_ELEMENTS >::append(), G3D::Array< T, MIN_ELEMENTS >::findIndex(), m_adapterArray, and m_broadcastAddresses.
bind()
bool G3D::NetworkDevice::bind (SOCKET sock, const NetAddress & addr) const private
Utility method. Returns true on success.
Definition at line 484 of file NetworkDevice.cpp.
{
     Log::common()->printf("Binding socket %d on port %d ",
                      sock, htons(addr.addr.sin_port));
     if (::bind(sock, (struct sockaddr*)&(addr.addr), sizeof(addr.addr)) ==
         SOCKET_ERROR) {
         Log::common()->println("FAIL");
         Log::common()->println(socketErrorCode());
         closesocket(sock);
         return false;
     }
     Log::common()->println("Ok");
     return true;
 }
References G3D::NetAddress::addr, closesocket(), G3D::Log::common(), G3D::Log::printf(), G3D::Log::println(), SOCKET_ERROR, and socketErrorCode().
Referenced by G3D::LightweightConduit::LightweightConduit(), and G3D::NetListener::NetListener().
broadcastAddressArray()
const Array<uint32>& G3D::NetworkDevice::broadcastAddressArray () const inline
Returns the (unique) IP addresses for UDP broadcasting extracted from adapterArray(). All are in host byte order.
Definition at line 692 of file NetworkDevice.h.
{
         return m_broadcastAddresses;
     }
References m_broadcastAddresses.
cleanup()
void G3D::NetworkDevice::cleanup () static
Shuts down the network device (destroying the global instance).
Definition at line 121 of file NetworkDevice.cpp.
{
     if (s_instance) {
         s_instance->_cleanup();
         delete s_instance;
         s_instance = NULL;
     }
 }
References _cleanup(), NULL, and s_instance.
closesocket()
void G3D::NetworkDevice::closesocket (SOCKET & sock) const private
Utility method.
Definition at line 501 of file NetworkDevice.cpp.
{
     if (sock != 0) {
         #ifdef G3D_WINDOWS
             ::closesocket(sock);
         #else
             close(sock);
         #endif
         Log::common()->printf("Closed socket %d\n", sock);
         sock = 0;
     }
 }
References close, G3D::Log::common(), and G3D::Log::printf().
Referenced by bind(), G3D::LightweightConduit::LightweightConduit(), G3D::NetListener::NetListener(), G3D::ReliableConduit::receiveHeader(), G3D::ReliableConduit::receiveIntoBuffer(), G3D::ReliableConduit::ReliableConduit(), G3D::ReliableConduit::sendBuffer(), G3D::LightweightConduit::sendBuffer(), G3D::NetListener::waitForConnection(), G3D::LightweightConduit::waitingMessageType(), G3D::Conduit::~Conduit(), and G3D::NetListener::~NetListener().
describeSystem() [1/2]
void G3D::NetworkDevice::describeSystem (std::string & s)
Definition at line 1273 of file NetworkDevice.cpp.
{
     TextOutput t;
     describeSystem(t);
     t.commitString(s);
 }
References G3D::TextOutput::commitString(), and describeSystem().
describeSystem() [2/2]
void G3D::NetworkDevice::describeSystem (TextOutput & t)
Prints a human-readable description of this machine to the text output stream.
Definition at line 1254 of file NetworkDevice.cpp.
                    {
     t.writeSymbols("Network", "=", "{");
     t.writeNewline();
     t.pushIndent();
     for (int i = 0; i < m_adapterArray.size(); ++i) {
         t.printf("Adapter%d =", i);
         m_adapterArray[i].describe(t);
     }
     t.popIndent();
     t.writeSymbols("};");
     t.writeNewline();
     t.writeNewline();
 }
References m_adapterArray, G3D::TextOutput::popIndent(), G3D::TextOutput::printf(), G3D::TextOutput::pushIndent(), G3D::TextOutput::writeNewline(), and G3D::TextOutput::writeSymbols().
Referenced by describeSystem().
formatIP()
std::string G3D::NetworkDevice::formatIP (uint32 ip) static
Prints an IP address to a string.
Parameters
ip In host byte order.
Definition at line 234 of file NetworkDevice.cpp.
{
     return format("%3d.%3d.%3d.%3d", (addr >> 24) & 0xFF, (addr >> 16) & 0xFF,
            (addr >> 8) & 0xFF, addr & 0xFF);
 }
References G3D::format().
Referenced by G3D::NetworkDevice::EthernetAdapter::describe().
formatMAC()
std::string G3D::NetworkDevice::formatMAC (const uint8 mac[6]) static
Prints a MAC address to a string.
Definition at line 240 of file NetworkDevice.cpp.
{
     return format("%02x:%02x:%02x:%02x:%02x:%02x", MAC[0], MAC[1], MAC[2], MAC[3], MAC[4], MAC[5]);
 }
References G3D::format().
Referenced by G3D::NetworkDevice::EthernetAdapter::describe().
init()
bool G3D::NetworkDevice::init () private
Referenced by instance().
instance()
NetworkDevice * G3D::NetworkDevice::instance () static
Returns NULL if there was a problem initializing the network.
Definition at line 109 of file NetworkDevice.cpp.
{
     if (s_instance == NULL) {
         s_instance = new NetworkDevice();
         if (! s_instance->init()) {
             delete s_instance;
             s_instance = NULL;
         }
     }
     return s_instance;
 }
References init(), NetworkDevice(), NULL, and s_instance.
Referenced by G3D::NetAddress::broadcastAddress(), G3D::GUniqueID::create(), G3D::LightweightConduit::LightweightConduit(), G3D::NetListener::NetListener(), G3D::ReliableConduit::receiveHeader(), G3D::ReliableConduit::receiveIntoBuffer(), G3D::ReliableConduit::ReliableConduit(), G3D::ReliableConduit::sendBuffer(), G3D::LightweightConduit::sendBuffer(), G3D::NetListener::waitForConnection(), G3D::LightweightConduit::waitingMessageType(), G3D::Conduit::~Conduit(), and G3D::NetListener::~NetListener().
localHostAddresses()
void G3D::NetworkDevice::localHostAddresses (Array< NetAddress > & array) const
There is often more than one address for the local host. This returns all of them.
Deprecated:
Use adapterArray()
Definition at line 515 of file NetworkDevice.cpp.
{
     array.resize(0);
     char ac[256];
     if (gethostname(ac, sizeof(ac)) == SOCKET_ERROR) {
         Log::common()->printf("Error while getting local host name\n");
         return;
     }
     struct hostent* phe = gethostbyname(ac);
     if (phe == 0) {
         Log::common()->printf("Error while getting local host address\n");
         return;
     }
     for (int i = 0; (phe->h_addr_list[i] != 0); ++i) {
         struct in_addr addr;
         memcpy(&addr, phe->h_addr_list[i], sizeof(struct in_addr));
         array.append(NetAddress(addr));
     }
 }
References array, G3D::Log::common(), memcpy, G3D::Log::printf(), and SOCKET_ERROR.
Referenced by G3D::GUniqueID::create().
localHostName()
std::string G3D::NetworkDevice::localHostName () const
Returns the name (or one of the names) of this computer
Definition at line 139 of file NetworkDevice.cpp.
{
     char ac[128];
     if (gethostname(ac, sizeof(ac)) == -1) {
         Log::common()->printf("Error while getting local host name\n");
         return "localhost";
     }
     return gethostbyname(ac)->h_name;
 }
References G3D::Log::common(), and G3D::Log::printf().
Friends And Related Function Documentation
Conduit
friend class Conduit friend
Definition at line 640 of file NetworkDevice.h.
LightweightConduit
friend class LightweightConduit friend
Definition at line 641 of file NetworkDevice.h.
NetListener
friend class NetListener friend
Definition at line 643 of file NetworkDevice.h.
ReliableConduit
friend class ReliableConduit friend
Definition at line 642 of file NetworkDevice.h.
Member Data Documentation
initialized
bool G3D::NetworkDevice::initialized private
Definition at line 645 of file NetworkDevice.h.
Referenced by _cleanup(), and NetworkDevice().
m_adapterArray
Array<EthernetAdapter> G3D::NetworkDevice::m_adapterArray private
Definition at line 647 of file NetworkDevice.h.
Referenced by adapterArray(), addAdapter(), and describeSystem().
m_broadcastAddresses
Array<uint32> G3D::NetworkDevice::m_broadcastAddresses private
Broadcast addresses available on this machine, extracted from m_adapterArray.
Definition at line 651 of file NetworkDevice.h.
Referenced by addAdapter(), and broadcastAddressArray().
s_instance
NetworkDevice * G3D::NetworkDevice::s_instance = NULL static private
The global instance
Definition at line 660 of file NetworkDevice.h.
Referenced by cleanup(), and instance().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/NetworkDevice.h
deps/g3dlite/source/NetworkDevice.cpp