Azerotcore-wotlk: go_ulduar_working_harpoon Class Reference
go_ulduar_working_harpoon Class Reference
Public Member Functions
go_ulduar_working_harpoon ()
bool OnGossipHello (Player *user, GameObject *go) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Definition at line 899 of file boss_razorscale.cpp.
Constructor & Destructor Documentation
go_ulduar_working_harpoon()
go_ulduar_working_harpoon::go_ulduar_working_harpoon () inline
Definition at line 902 of file boss_razorscale.cpp.
 : GameObjectScript("go_ulduar_working_harpoon") { }
Member Function Documentation
OnGossipHello()
bool go_ulduar_working_harpoon::OnGossipHello (Player * user, GameObject * go) inline override virtual
Reimplemented from GameObjectScript.
Definition at line 904 of file boss_razorscale.cpp.
     {
         if( !user || !go )
             return true;
         InstanceScript* pInstance = go->GetInstanceScript();
         if( !pInstance )
             return true;
         Creature* rs = nullptr;
         if( ObjectGuid rsGUID = pInstance->GetGuidData(TYPE_RAZORSCALE) )
             rs = ObjectAccessor::GetCreature(*go, rsGUID);
         if( !rs || !rs->IsInCombat() )
         {
             go->SetRespawnTime(0);
             go->Delete();
             return true;
         }
         uint32 npc = 0;
         uint32 spell = 0;
         switch( go->GetEntry() )
         {
             case GO_HARPOON_GUN_1:
                 npc = DATA_HARPOON_FIRE_STATE_1;
                 spell = SPELL_CHAIN_1;
                 break;
             case GO_HARPOON_GUN_2:
                 npc = DATA_HARPOON_FIRE_STATE_2;
                 spell = SPELL_CHAIN_2;
                 break;
             case GO_HARPOON_GUN_3:
                 npc = DATA_HARPOON_FIRE_STATE_3;
                 spell = SPELL_CHAIN_3;
                 break;
             case GO_HARPOON_GUN_4:
                 npc = DATA_HARPOON_FIRE_STATE_4;
                 spell = SPELL_CHAIN_4;
                 break;
         }
         if( ObjectGuid g = pInstance->GetGuidData(npc) )
             if( Creature* hfs = ObjectAccessor::GetCreature(*go, g) )
                 hfs->AI()->SetData(3, spell);
         go->SetLootState(GO_JUST_DEACTIVATED);
         return true;
     }
References DATA_HARPOON_FIRE_STATE_1, DATA_HARPOON_FIRE_STATE_2, DATA_HARPOON_FIRE_STATE_3, DATA_HARPOON_FIRE_STATE_4, GameObject::Delete(), ObjectAccessor::GetCreature(), Object::GetEntry(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), GO_HARPOON_GUN_1, GO_HARPOON_GUN_2, GO_HARPOON_GUN_3, GO_HARPOON_GUN_4, GO_JUST_DEACTIVATED, Unit::IsInCombat(), GameObject::SetLootState(), GameObject::SetRespawnTime(), SPELL_CHAIN_1, SPELL_CHAIN_2, SPELL_CHAIN_3, SPELL_CHAIN_4, and TYPE_RAZORSCALE.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_razorscale.cpp