Azerotcore-wotlk: deps/mysqllite/sql-common/client_plugin.c File Reference
client_plugin.c File Reference
#include <my_global.h>
#include "mysql.h"
#include <my_sys.h>
#include <m_string.h>
#include <my_pthread.h>
#include <sql_common.h>
#include "errmsg.h"
#include <mysql/client_plugin.h>
Classes
struct st_client_plugin_int
Functions
static int is_not_initialized (MYSQL *mysql, const char *name)
static struct st_mysql_client_plugin * find_plugin (const char *name, int type)
static struct st_mysql_client_plugin * add_plugin (MYSQL *mysql, struct st_mysql_client_plugin *plugin, void *dlhandle, int argc, va_list args)
static void load_env_plugins (MYSQL *mysql)
int mysql_client_plugin_init ()
void mysql_client_plugin_deinit ()
struct st_mysql_client_plugin * mysql_client_register_plugin (MYSQL *mysql, struct st_mysql_client_plugin *plugin)
struct st_mysql_client_plugin * mysql_load_plugin_v (MYSQL *mysql, const char *name, int type, int argc, va_list args)
struct st_mysql_client_plugin * mysql_load_plugin (MYSQL *mysql, const char *name, int type, int argc,...)
struct st_mysql_client_plugin * mysql_client_find_plugin (MYSQL *mysql, const char *name, int type)
int STDCALL mysql_plugin_options (struct st_mysql_client_plugin *plugin, const char *option, const void *value)
Variables
static my_bool initialized = 0
static MEM_ROOT mem_root
static const char * plugin_declarations_sym = "_mysql_client_plugin_declaration_"
static uint plugin_version [MYSQL_CLIENT_MAX_PLUGINS]
struct st_client_plugin_int * plugin_list [MYSQL_CLIENT_MAX_PLUGINS]
static pthread_mutex_t LOCK_load_client_plugin
Detailed Description
Support code for the client side (libmysql) plugins
Client plugins are somewhat different from server plugins, they are simpler.
They do not need to be installed or in any way explicitly loaded on the client, they are loaded automatically on demand. One client plugin per shared object, soname must match the plugin name.
There is no reference counting and no unloading either.
Definition in file client_plugin.c.
Function Documentation
add_plugin()
static struct st_mysql_client_plugin* add_plugin (MYSQL * mysql, struct st_mysql_client_plugin * plugin, void * dlhandle, int argc, va_list args) static
verifies the plugin and adds it to the list
Parameters
mysql MYSQL structure (for error reporting)
plugin plugin to install
dlhandle a handle to the shared object (returned by dlopen) or 0 if the plugin was not dynamically loaded
argc number of arguments in the 'va_list args'
args arguments passed to the plugin initialization function
Return values
a pointer to an installed plugin or 0
Definition at line 120 of file client_plugin.c.
 {
   const char *errmsg;
   struct st_client_plugin_int plugin_int, *p;
   char errbuf[1024];
   DBUG_ASSERT(initialized);
   plugin_int.plugin= plugin;
   plugin_int.dlhandle= dlhandle;
   if (plugin->type >= MYSQL_CLIENT_MAX_PLUGINS)
   {
     errmsg= "Unknown client plugin type";
     goto err1;
   }
   if (plugin->interface_version < plugin_version[plugin->type] ||
       (plugin->interface_version >> 8) >
        (plugin_version[plugin->type] >> 8))
   {
     errmsg= "Incompatible client plugin interface";
     goto err1;
   }
   /* Call the plugin initialization function, if any */
   if (plugin->init && plugin->init(errbuf, sizeof(errbuf), argc, args))
   {
     errmsg= errbuf;
     goto err1;
   }
   p= (struct st_client_plugin_int *)
     memdup_root(&mem_root, &plugin_int, sizeof(plugin_int));
   if (!p)
   {
     errmsg= "Out of memory";
     goto err2;
   }
   safe_mutex_assert_owner(&LOCK_load_client_plugin);
   p->next= plugin_list[plugin->type];
   plugin_list[plugin->type]= p;
   return plugin;
 err2:
   if (plugin->deinit)
     plugin->deinit();
 err1:
   set_mysql_extended_error(mysql, CR_AUTH_PLUGIN_CANNOT_LOAD, unknown_sqlstate,
                            ER(CR_AUTH_PLUGIN_CANNOT_LOAD), plugin->name,
                            errmsg);
   if (dlhandle)
     dlclose(dlhandle);
   return NULL;
 }
References CR_AUTH_PLUGIN_CANNOT_LOAD, DBUG_ASSERT, st_client_plugin_int::dlhandle, ER, initialized, LOCK_load_client_plugin, mem_root, memdup_root(), MYSQL_CLIENT_MAX_PLUGINS, st_client_plugin_int::next, NULL, st_client_plugin_int::plugin, plugin_list, plugin_version, safe_mutex_assert_owner, set_mysql_extended_error(), and unknown_sqlstate.
Referenced by mysql_client_plugin_init(), mysql_client_register_plugin(), and mysql_load_plugin_v().
find_plugin()
static struct st_mysql_client_plugin* find_plugin (const char * name, int type) static
finds a plugin in the list
Parameters
name plugin name to search for
type plugin type
Note
this does NOT necessarily need a mutex, take care!
Return values
a pointer to a found plugin or 0
Definition at line 90 of file client_plugin.c.
 {
   struct st_client_plugin_int *p;
   DBUG_ASSERT(initialized);
   DBUG_ASSERT(type >= 0 && type < MYSQL_CLIENT_MAX_PLUGINS);
   if (type < 0 || type >= MYSQL_CLIENT_MAX_PLUGINS)
     return 0;
   for (p= plugin_list[type]; p; p= p->next)
   {
     if (strcmp(p->plugin->name, name) == 0)
       return p->plugin;
   }
   return NULL;
 }
References DBUG_ASSERT, initialized, MYSQL_CLIENT_MAX_PLUGINS, name, st_client_plugin_int::next, NULL, st_client_plugin_int::plugin, and plugin_list.
Referenced by mysql_client_find_plugin(), mysql_client_register_plugin(), and mysql_load_plugin_v().
is_not_initialized()
static int is_not_initialized (MYSQL * mysql, const char * name) static
Definition at line 68 of file client_plugin.c.
 {
   if (initialized)
     return 0;
   set_mysql_extended_error(mysql, CR_AUTH_PLUGIN_CANNOT_LOAD,
                            unknown_sqlstate, ER(CR_AUTH_PLUGIN_CANNOT_LOAD),
                            name, "not initialized");
   return 1;
 }
References CR_AUTH_PLUGIN_CANNOT_LOAD, ER, initialized, name, set_mysql_extended_error(), and unknown_sqlstate.
Referenced by mysql_client_find_plugin(), mysql_client_register_plugin(), and mysql_load_plugin_v().
load_env_plugins()
static void load_env_plugins (MYSQL * mysql) static
Loads plugins which are specified in the environment variable LIBMYSQL_PLUGINS.
Multiple plugins must be separated by semicolon. This function doesn't return or log an error.
The function is be called by mysql_client_plugin_init
Todo:
Support extended syntax, passing parameters to plugins, for example LIBMYSQL_PLUGINS="plugin1(param1,param2);plugin2;..." or LIBMYSQL_PLUGINS="plugin1=int:param1,str:param2;plugin2;..."
Definition at line 196 of file client_plugin.c.
 {
   char *plugs, *free_env, *s= getenv("LIBMYSQL_PLUGINS");
   /* no plugins to load */
   if(!s)
     return;
   free_env= plugs= my_strdup(s, MYF(MY_WME));
   do {
     if ((s= strchr(plugs, ';')))
       *s= '\0';
     mysql_load_plugin(mysql, plugs, -1, 0);
     plugs= s + 1;
   } while (s);
   my_free(free_env);
 }
References my_free(), my_strdup(), MY_WME, MYF, and mysql_load_plugin().
Referenced by mysql_client_plugin_init().
mysql_client_find_plugin()
struct st_mysql_client_plugin* mysql_client_find_plugin (struct st_mysql * mysql, const char * name, int type)
finds an already loaded plugin by name, or loads it, if necessary
Parameters
mysql MYSQL structure.
name a name of the plugin to load
type type of plugin that should be loaded
Return values
a pointer to the plugin, or NULL in case of a failure
Definition at line 432 of file client_plugin.c.
 {
   struct st_mysql_client_plugin *p;
   DBUG_ENTER ("mysql_client_find_plugin");
   DBUG_PRINT ("entry", ("name=%s, type=%d", name, type));
   if (is_not_initialized(mysql, name))
     DBUG_RETURN (NULL);
   if (type < 0 || type >= MYSQL_CLIENT_MAX_PLUGINS)
   {
     set_mysql_extended_error(mysql, CR_AUTH_PLUGIN_CANNOT_LOAD, unknown_sqlstate,
                              ER(CR_AUTH_PLUGIN_CANNOT_LOAD), name,
                              "invalid type");
   }
   if ((p= find_plugin(name, type)))
   {
     DBUG_PRINT ("leave", ("found %p", p));
     DBUG_RETURN (p);
   }
   /* not found, load it */
   p= mysql_load_plugin(mysql, name, type, 0);
   DBUG_PRINT ("leave", ("loaded %p", p));
   DBUG_RETURN (p);
 }
References CR_AUTH_PLUGIN_CANNOT_LOAD, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, ER, find_plugin(), is_not_initialized(), MYSQL_CLIENT_MAX_PLUGINS, mysql_load_plugin(), name, NULL, set_mysql_extended_error(), and unknown_sqlstate.
Referenced by run_plugin_auth().
mysql_client_plugin_deinit()
void mysql_client_plugin_deinit ()
Deinitializes the client plugin layer.
Unloades all client plugins and frees any associated resources.
Definition at line 260 of file client_plugin.c.
 {
   int i;
   struct st_client_plugin_int *p;
   if (!initialized)
     return;
   for (i=0; i < MYSQL_CLIENT_MAX_PLUGINS; i++)
     for (p= plugin_list[i]; p; p= p->next)
     {
       if (p->plugin->deinit)
         p->plugin->deinit();
       if (p->dlhandle)
         dlclose(p->dlhandle);
     }
   bzero(&plugin_list, sizeof(plugin_list));
   initialized= 0;
   free_root(&mem_root, MYF(0));
   pthread_mutex_destroy(&LOCK_load_client_plugin);
 }
References bzero, st_client_plugin_int::dlhandle, free_root(), initialized, LOCK_load_client_plugin, mem_root, MYF, MYSQL_CLIENT_MAX_PLUGINS, st_client_plugin_int::next, st_client_plugin_int::plugin, and plugin_list.
Referenced by mysql_server_end().
mysql_client_plugin_init()
int mysql_client_plugin_init ()
Initializes the client plugin layer.
This function must be called before any other client plugin function.
Return values
0 successful
!= 0 error occured
Definition at line 226 of file client_plugin.c.
 {
   MYSQL mysql;
   struct st_mysql_client_plugin **builtin;
   if (initialized)
     return 0;
   bzero(&mysql, sizeof(mysql)); /* dummy mysql for set_mysql_extended_error */
   pthread_mutex_init(&LOCK_load_client_plugin, MY_MUTEX_INIT_SLOW);
   init_alloc_root(&mem_root, 128, 128);
   bzero(&plugin_list, sizeof(plugin_list));
   initialized= 1;
   pthread_mutex_lock(&LOCK_load_client_plugin);
   for (builtin= mysql_client_builtins; *builtin; builtin++)
     add_plugin(&mysql, *builtin, 0, 0, 0);
   pthread_mutex_unlock(&LOCK_load_client_plugin);
   load_env_plugins(&mysql);
   return 0;
 }
References add_plugin(), bzero, init_alloc_root(), initialized, load_env_plugins(), LOCK_load_client_plugin, mem_root, MY_MUTEX_INIT_SLOW, mysql_client_builtins, and plugin_list.
Referenced by mysql_server_init().
mysql_client_register_plugin()
struct st_mysql_client_plugin* mysql_client_register_plugin (struct st_mysql * mysql, struct st_mysql_client_plugin * plugin)
adds a plugin structure to the list of loaded plugins
This is useful if an application has the necessary functionality (for example, a special load data handler) statically linked into the application binary. It can use this function to register the plugin directly, avoiding the need to factor it out into a shared object.
Parameters
mysql MYSQL structure. It is only used for error reporting
plugin an st_mysql_client_plugin structure to register
Return values
a pointer to the plugin, or NULL in case of a failure
Definition at line 287 of file client_plugin.c.
 {
   if (is_not_initialized(mysql, plugin->name))
     return NULL;
   pthread_mutex_lock(&LOCK_load_client_plugin);
   /* make sure the plugin wasn't loaded meanwhile */
   if (find_plugin(plugin->name, plugin->type))
   {
     set_mysql_extended_error(mysql, CR_AUTH_PLUGIN_CANNOT_LOAD,
                              unknown_sqlstate, ER(CR_AUTH_PLUGIN_CANNOT_LOAD),
                              plugin->name, "it is already loaded");
     plugin= NULL;
   }
   else
     plugin= add_plugin(mysql, plugin, 0, 0, 0);
   pthread_mutex_unlock(&LOCK_load_client_plugin);
   return plugin;
 }
References add_plugin(), CR_AUTH_PLUGIN_CANNOT_LOAD, ER, find_plugin(), is_not_initialized(), LOCK_load_client_plugin, NULL, set_mysql_extended_error(), and unknown_sqlstate.
mysql_load_plugin()
struct st_mysql_client_plugin* mysql_load_plugin (struct st_mysql * mysql, const char * name, int type, int argc, ...)
loads a plugin and initializes it
Parameters
mysql MYSQL structure.
name a name of the plugin to load
type type of plugin that should be loaded, -1 to disable type check
argc number of arguments to pass to the plugin initialization function
... arguments for the plugin initialization function
Return values
a pointer to the loaded plugin, or NULL in case of a failure
Definition at line 420 of file client_plugin.c.
 {
   struct st_mysql_client_plugin *p;
   va_list args;
   va_start(args, argc);
   p= mysql_load_plugin_v(mysql, name, type, argc, args);
   va_end(args);
   return p;
 }
References mysql_load_plugin_v(), and name.
Referenced by load_env_plugins(), and mysql_client_find_plugin().
mysql_load_plugin_v()
struct st_mysql_client_plugin* mysql_load_plugin_v (struct st_mysql * mysql, const char * name, int type, int argc, va_list args)
loads a plugin and initializes it, taking va_list as an argument
This is the same as mysql_load_plugin, but take va_list instead of a list of arguments.
Parameters
mysql MYSQL structure.
name a name of the plugin to load
type type of plugin that should be loaded, -1 to disable type check
argc number of arguments to pass to the plugin initialization function
args arguments for the plugin initialization function
Return values
a pointer to the loaded plugin, or NULL in case of a failure
Definition at line 312 of file client_plugin.c.
 {
   const char *errmsg;
   char dlpath[FN_REFLEN+1];
   void *sym, *dlhandle;
   struct st_mysql_client_plugin *plugin;
 #ifdef _WIN32
   char win_errormsg[2048];
 #endif
   DBUG_ENTER ("mysql_load_plugin_v");
   DBUG_PRINT ("entry", ("name=%s type=%d int argc=%d", name, type, argc));
   if (is_not_initialized(mysql, name))
   {
     DBUG_PRINT ("leave", ("mysql not initialized"));
     DBUG_RETURN (NULL);
   }
   pthread_mutex_lock(&LOCK_load_client_plugin);
   /* make sure the plugin wasn't loaded meanwhile */
   if (type >= 0 && find_plugin(name, type))
   {
     errmsg= "it is already loaded";
     goto err;
   }
   /* Compile dll path */
   strxnmov(dlpath, sizeof(dlpath) - 1,
            mysql->options.extension && mysql->options.extension->plugin_dir ?
            mysql->options.extension->plugin_dir : PLUGINDIR, "/",
            name, SO_EXT, NullS);
   DBUG_PRINT ("info", ("dlopeninig %s", dlpath));
   /* Open new dll handle */
   if (!(dlhandle= dlopen(dlpath, RTLD_NOW)))
   {
 #if defined(__APPLE__)
     /* Apple supports plugins with .so also, so try this as well */
     strxnmov(dlpath, sizeof(dlpath) - 1,
              mysql->options.extension && mysql->options.extension->plugin_dir ?
              mysql->options.extension->plugin_dir : PLUGINDIR, "/",
              name, ".so", NullS);
     if ((dlhandle= dlopen(dlpath, RTLD_NOW)))
       goto have_plugin;
 #endif
     DBUG_PRINT ("info", ("failed to dlopen"));
 #ifdef _WIN32
     if(FormatMessage(FORMAT_MESSAGE_FROM_SYSTEM,
                   0, GetLastError(), 0, win_errormsg, 2048, NULL))
       errmsg= win_errormsg;
     else
       errmsg= "";
 #else
     errmsg= dlerror();
 #endif
     goto err;
   }
 #if defined(__APPLE__)
 have_plugin:
 #endif
   if (!(sym= dlsym(dlhandle, plugin_declarations_sym)))
   {
     errmsg= "not a plugin";
     dlclose(dlhandle);
     goto err;
   }
   plugin= (struct st_mysql_client_plugin*)sym;
   if (type >=0 && type != plugin->type)
   {
     errmsg= "type mismatch";
     goto err;
   }
   if (strcmp(name, plugin->name))
   {
     errmsg= "name mismatch";
     goto err;
   }
   if (type < 0 && find_plugin(name, plugin->type))
   {
     errmsg= "it is already loaded";
     goto err;
   }
   plugin= add_plugin(mysql, plugin, dlhandle, argc, args);
   pthread_mutex_unlock(&LOCK_load_client_plugin);
   DBUG_PRINT ("leave", ("plugin loaded ok"));
   DBUG_RETURN (plugin);
 err:
   pthread_mutex_unlock(&LOCK_load_client_plugin);
   DBUG_PRINT ("leave", ("plugin load error : %s", errmsg));
   set_mysql_extended_error(mysql, CR_AUTH_PLUGIN_CANNOT_LOAD, unknown_sqlstate,
                            ER(CR_AUTH_PLUGIN_CANNOT_LOAD), name, errmsg);
   DBUG_RETURN (NULL);
 }
References add_plugin(), CR_AUTH_PLUGIN_CANNOT_LOAD, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, dlerror, ER, st_mysql_options::extension, find_plugin(), FN_REFLEN, is_not_initialized(), LOCK_load_client_plugin, name, NULL, NullS, st_mysql::options, plugin_declarations_sym, st_mysql_options_extention::plugin_dir, set_mysql_extended_error(), SO_EXT, strxnmov(), and unknown_sqlstate.
Referenced by mysql_load_plugin().
mysql_plugin_options()
int STDCALL mysql_plugin_options (struct st_mysql_client_plugin * plugin, const char * option, const void * value)
set plugin options
Can be used to set extra options and affect behavior for a plugin. This function may be called multiple times to set several options
Parameters
plugin an st_mysql_client_plugin structure
option a string which specifies the option to set
value value for the option.
Return values
0 on success, 1 in case of failure
Definition at line 462 of file client_plugin.c.
 {
   DBUG_ENTER("mysql_plugin_options");
   /* does the plugin support options call? */
   if (!plugin || !plugin->options)
     DBUG_RETURN(1);
   DBUG_RETURN(plugin->options(option, value));
 }
References DBUG_ENTER, and DBUG_RETURN.
Variable Documentation
initialized
my_bool initialized = 0 static
Definition at line 46 of file client_plugin.c.
Referenced by add_plugin(), arena_i_initialized_ctl(), G3D::System::consoleKeyPressed(), ctl_refresh(), find_plugin(), G3D::initMem(), is_not_initialized(), mysql_client_plugin_deinit(), mysql_client_plugin_init(), and stats_print_helper().
LOCK_load_client_plugin
pthread_mutex_t LOCK_load_client_plugin static
Definition at line 66 of file client_plugin.c.
Referenced by add_plugin(), mysql_client_plugin_deinit(), mysql_client_plugin_init(), mysql_client_register_plugin(), and mysql_load_plugin_v().
mem_root
MEM_ROOT mem_root static
Definition at line 47 of file client_plugin.c.
Referenced by add_plugin(), alloc_root(), init_alloc_root(), mysql_client_plugin_deinit(), mysql_client_plugin_init(), and reset_root_defaults().
plugin_declarations_sym
const char* plugin_declarations_sym = "_mysql_client_plugin_declaration_" static
Definition at line 49 of file client_plugin.c.
Referenced by mysql_load_plugin_v().
plugin_list
struct st_client_plugin_int* plugin_list[MYSQL_CLIENT_MAX_PLUGINS]
Definition at line 65 of file client_plugin.c.
Referenced by add_plugin(), find_plugin(), mysql_client_plugin_deinit(), and mysql_client_plugin_init().
plugin_version
uint plugin_version[MYSQL_CLIENT_MAX_PLUGINS] static
Initial value:
=
{
  0,
  0,
  MYSQL_CLIENT_AUTHENTICATION_PLUGIN_INTERFACE_VERSION
}
Definition at line 50 of file client_plugin.c.
Referenced by add_plugin().