Azerotcore-wotlk: src/server/worldserver/ACSoap/ACSoap.h File Reference
ACSoap.h File Reference
#include "Define.h"
#include <future>
#include <mutex>
Classes
class SOAPCommand
Functions
void process_message (struct soap *soap_message)
void ACSoapThread (const std::string &host, uint16 port)
Function Documentation
ACSoapThread()
void ACSoapThread (const std::string & host, uint16 port)
Definition at line 25 of file ACSoap.cpp.
 {
     struct soap soap;
     soap_init(&soap);
     soap_set_imode(&soap, SOAP_C_UTFSTRING);
     soap_set_omode(&soap, SOAP_C_UTFSTRING);
     // check every 3 seconds if world ended
     soap.accept_timeout = 3;
     soap.recv_timeout = 5;
     soap.send_timeout = 5;
     if (!soap_valid_socket(soap_bind(&soap, host.c_str(), port, 100)))
     {
         LOG_ERROR("network.soap", "ACSoap: couldn't bind to %s:%d", host.c_str(), port);
         exit(-1);
     }
     LOG_INFO("network.soap", "ACSoap: bound to http://%s:%d", host.c_str(), port);
     while (!World::IsStopped())
     {
         if (!soap_valid_socket(soap_accept(&soap)))
             continue;   // ran into an accept timeout
         LOG_DEBUG("network.soap", "ACSoap: accepted connection from IP=%d.%d.%d.%d", (int)(soap.ip >> 24) & 0xFF, (int)(soap.ip >> 16) & 0xFF, (int)(soap.ip >> 8) & 0xFF, (int)soap.ip & 0xFF);
         struct soap* thread_soap = soap_copy(&soap);// make a safe copy
         process_message(thread_soap);
     }
     soap_destroy(&soap);
     soap_end(&soap);
     soap_done(&soap);
 }
References soap::accept_timeout, soap::host, soap::ip, World::IsStopped(), LOG_DEBUG, LOG_ERROR, LOG_INFO, soap::port, process_message(), soap::recv_timeout, soap::send_timeout, soap_accept(), soap_bind(), SOAP_C_UTFSTRING, soap_copy(), soap_destroy, soap_done(), soap_end(), soap_init, soap_set_imode, soap_set_omode, and soap_valid_socket.
Referenced by main().
process_message()
void process_message (struct soap * soap_message)
Definition at line 61 of file ACSoap.cpp.
 {
     LOG_TRACE("network.soap", "SOAPWorkingThread::process_message");
     soap_serve(soap_message);
     soap_destroy(soap_message); // dealloc C++ data
     soap_end(soap_message); // dealloc data and clean up
     soap_free(soap_message); // detach soap struct and fre up the memory
 }
References LOG_TRACE, soap_destroy, soap_end(), soap_free(), and soap_serve().
Referenced by ACSoapThread().