Azerotcore-wotlk: npc_grand_magister_rommath::npc_grand_magister_rommathAI Struct Reference
npc_grand_magister_rommath::npc_grand_magister_rommathAI Struct Reference
Public Member Functions
npc_grand_magister_rommathAI (Creature *c)
void MoveInLineOfSight (Unit *who) override
void DoAction (int32 a) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void Reset ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
bool announced
ObjectGuid playerGUID
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 498 of file zone_isle_of_queldanas.cpp.
Constructor & Destructor Documentation
npc_grand_magister_rommathAI()
npc_grand_magister_rommath::npc_grand_magister_rommathAI::npc_grand_magister_rommathAI (Creature * c) inline
Definition at line 500 of file zone_isle_of_queldanas.cpp.
                                                   : NullCreatureAI(c)
         {
             announced = false;
             playerGUID.Clear();
             me->SetReactState(REACT_AGGRESSIVE);
         }
References announced, ObjectGuid::Clear(), CreatureAI::me, playerGUID, REACT_AGGRESSIVE, and Creature::SetReactState().
Member Function Documentation
DoAction()
void npc_grand_magister_rommath::npc_grand_magister_rommathAI::DoAction (int32 a) inline override virtual
Reimplemented from UnitAI.
Definition at line 522 of file zone_isle_of_queldanas.cpp.
         {
             if (a == -1 && !me->isActiveObject())
             {
                 me->SummonGameObject(GO_QUEL_DELAR, 1688.24f, 621.769f, 29.1745f, 0.523177f, 0.0f, 0.0f, 0.0f, 0.0f, 86400);
                 me->SummonCreature(NPC_SUNWELL_VISUAL_BUNNY, 1688.24f, 621.769f, 29.1745f, 0.523177f, TEMPSUMMON_MANUAL_DESPAWN);
                 me->setActive(true);
                 events.Reset();
                 events.ScheduleEvent(1, 1000); // guard talk
                 events.ScheduleEvent(2, 4000); // theron talk
                 events.ScheduleEvent(3, 10000); // npcs walk
                 events.ScheduleEvent(4, 17000); // rommath talk
                 events.ScheduleEvent(5, 20000); // theron talk
                 events.ScheduleEvent(6, 28000); // theron talk
                 events.ScheduleEvent(7, 37000); // rommath talk
                 events.ScheduleEvent(8, 44000); // rommath talk
                 events.ScheduleEvent(9, 52000); // rommath talk
                 events.ScheduleEvent(10, 60000); // auric talk
                 events.ScheduleEvent(11, 66000); // auric talk
                 events.ScheduleEvent(12, 76000); // rommath talk
                 events.ScheduleEvent(13, 80000); // move home
             }
         }
References mpq::a, GO_QUEL_DELAR, WorldObject::isActiveObject(), CreatureAI::me, NPC_SUNWELL_VISUAL_BUNNY, WorldObject::setActive(), WorldObject::SummonCreature(), WorldObject::SummonGameObject(), and TEMPSUMMON_MANUAL_DESPAWN.
MoveInLineOfSight()
void npc_grand_magister_rommath::npc_grand_magister_rommathAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 511 of file zone_isle_of_queldanas.cpp.
         {
             if (!announced && who->GetTypeId() == TYPEID_PLAYER && who->GetPositionZ() < 30.0f)
             {
                 announced = true;
                 playerGUID = who->GetGUID();
                 if (Creature* c = me->FindNearestCreature(NPC_GALIROS, 100.0f, true))
                     c->AI()->Talk(0, who);
             }
         }
References announced, mpq::c, WorldObject::FindNearestCreature(), Object::GetGUID(), Position::GetPositionZ(), Object::GetTypeId(), CreatureAI::me, NPC_GALIROS, playerGUID, and TYPEID_PLAYER.
UpdateAI()
void npc_grand_magister_rommath::npc_grand_magister_rommathAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 546 of file zone_isle_of_queldanas.cpp.
         {
             if (!me->isActiveObject())
                 return;
             events.Update(diff);
             switch (events.ExecuteEvent())
             {
                 case 1:
                     if (Creature* c = me->FindNearestCreature(NPC_SUNWELL_HONOR_GUARD, 60.0f, true))
                         c->AI()->Talk(0);
                     break;
                 case 2:
                     if (Creature* c = me->FindNearestCreature(NPC_THERON, 60.0f, true))
                         c->AI()->Talk(0);
                     break;
                 case 3:
                     me->SetWalk(true);
                     me->GetMotionMaster()->MovePath(me->GetEntry() * 100, false);
                     if (Creature* c = me->FindNearestCreature(NPC_THERON, 60.0f, true))
                     {
                         c->SetWalk(true);
                         c->GetMotionMaster()->MovePath(c->GetEntry() * 100, false);
                     }
                     if (Creature* c = me->FindNearestCreature(NPC_AURIC, 60.0f, true))
                     {
                         c->SetWalk(true);
                         c->GetMotionMaster()->MovePath(c->GetEntry() * 100, false);
                     }
                     break;
                 case 4:
                     Talk(0);
                     break;
                 case 5:
                     if (Creature* c = me->FindNearestCreature(NPC_THERON, 60.0f, true))
                         c->AI()->Talk(1);
                     break;
                 case 6:
                     if (Creature* c = me->FindNearestCreature(NPC_THERON, 60.0f, true))
                         c->AI()->Talk(2, ObjectAccessor::GetPlayer(*me, playerGUID));
                     break;
                 case 7:
                     Talk(1, ObjectAccessor::GetPlayer(*me, playerGUID));
                     break;
                 case 8:
                     Talk(2);
                     break;
                 case 9:
                     Talk(3);
                     break;
                 case 10:
                     if (Creature* c = me->FindNearestCreature(NPC_AURIC, 60.0f, true))
                         c->AI()->Talk(0);
                     break;
                 case 11:
                     if (Creature* c = me->FindNearestCreature(NPC_AURIC, 60.0f, true))
                         c->AI()->Talk(1);
                     break;
                 case 12:
                     if (Player* p = ObjectAccessor::GetPlayer(*me, playerGUID))
                         Talk(p->GetTeamId() == TEAM_ALLIANCE ? 5 : 4, p);
                     break;
                 case 13:
                     me->setActive(false);
                     if (Creature* c = me->FindNearestCreature(NPC_SUNWELL_VISUAL_BUNNY, 60.0f, true))
                         c->DespawnOrUnsummon(1);
                     if (GameObject* go = me->FindNearestGameObject(GO_QUEL_DELAR, 60.0f))
                         go->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                     me->SetWalk(true);
                     if (me->GetCreatureData())
                         me->GetMotionMaster()->MovePoint(0, me->GetCreatureData()->posX, me->GetCreatureData()->posY, me->GetCreatureData()->posZ);
                     if (Creature* c = me->FindNearestCreature(NPC_THERON, 60.0f, true))
                     {
                         c->SetWalk(true);
                         if (c->GetCreatureData())
                             c->GetMotionMaster()->MovePoint(0, c->GetCreatureData()->posX, c->GetCreatureData()->posY, c->GetCreatureData()->posZ);
                     }
                     if (Creature* c = me->FindNearestCreature(NPC_AURIC, 60.0f, true))
                     {
                         c->SetWalk(true);
                         if (c->GetCreatureData())
                             c->GetMotionMaster()->MovePoint(0, c->GetCreatureData()->posX, c->GetCreatureData()->posY, c->GetCreatureData()->posZ);
                     }
                     break;
             }
         }
References mpq::c, diff(), WorldObject::FindNearestCreature(), WorldObject::FindNearestGameObject(), GAMEOBJECT_FLAGS, Creature::GetCreatureData(), Object::GetEntry(), Unit::GetMotionMaster(), ObjectAccessor::GetPlayer(), GO_FLAG_NOT_SELECTABLE, GO_QUEL_DELAR, WorldObject::isActiveObject(), CreatureAI::me, MotionMaster::MovePath(), MotionMaster::MovePoint(), NPC_AURIC, NPC_SUNWELL_HONOR_GUARD, NPC_SUNWELL_VISUAL_BUNNY, NPC_THERON, playerGUID, CreatureData::posX, CreatureData::posY, CreatureData::posZ, WorldObject::setActive(), Creature::SetWalk(), CreatureAI::Talk(), and TEAM_ALLIANCE.
Member Data Documentation
announced
bool npc_grand_magister_rommath::npc_grand_magister_rommathAI::announced
Definition at line 508 of file zone_isle_of_queldanas.cpp.
Referenced by MoveInLineOfSight(), and npc_grand_magister_rommathAI().
events
EventMap npc_grand_magister_rommath::npc_grand_magister_rommathAI::events
Definition at line 507 of file zone_isle_of_queldanas.cpp.
playerGUID
ObjectGuid npc_grand_magister_rommath::npc_grand_magister_rommathAI::playerGUID
Definition at line 509 of file zone_isle_of_queldanas.cpp.
Referenced by MoveInLineOfSight(), npc_grand_magister_rommathAI(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/zone_isle_of_queldanas.cpp