Azerotcore-wotlk: achievement_once_bitten_twice_shy Class Reference
achievement_once_bitten_twice_shy Class Reference
Public Member Functions
achievement_once_bitten_twice_shy (const char *name, uint8 spawnMode, bool wasVampire)
bool OnCheck (Player *source, Unit *target, uint32) override
Public Member Functions inherited from AchievementCriteriaScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Attributes
uint8 _spawnMode
bool _wasVampire
Additional Inherited Members
Protected Member Functions inherited from AchievementCriteriaScript
AchievementCriteriaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 996 of file boss_blood_queen_lana_thel.cpp.
Constructor & Destructor Documentation
achievement_once_bitten_twice_shy()
achievement_once_bitten_twice_shy::achievement_once_bitten_twice_shy (const char * name, uint8 spawnMode, bool wasVampire) inline
Definition at line 999 of file boss_blood_queen_lana_thel.cpp.
 : AchievementCriteriaScript(name), _spawnMode(spawnMode), _wasVampire(wasVampire) { }
Member Function Documentation
OnCheck()
bool achievement_once_bitten_twice_shy::OnCheck (Player * source, Unit * target, uint32) inline override virtual
Reimplemented from AchievementCriteriaScript.
Definition at line 1001 of file boss_blood_queen_lana_thel.cpp.
     {
         if (!target || !target->FindMap())
             return false;
         if (LanaThelAI* lanaThelAI = CAST_AI(LanaThelAI, target->GetAI()))
             return (target->GetMap()->GetSpawnMode() % 2) == _spawnMode && lanaThelAI->WasVampire(source->GetGUID()) == _wasVampire;
         return false;
     }
References _spawnMode, _wasVampire, CAST_AI, WorldObject::FindMap(), Unit::GetAI(), Object::GetGUID(), WorldObject::GetMap(), and Map::GetSpawnMode().
Member Data Documentation
_spawnMode
uint8 achievement_once_bitten_twice_shy::_spawnMode
Definition at line 1011 of file boss_blood_queen_lana_thel.cpp.
Referenced by OnCheck().
_wasVampire
bool achievement_once_bitten_twice_shy::_wasVampire
Definition at line 1012 of file boss_blood_queen_lana_thel.cpp.
Referenced by OnCheck().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_blood_queen_lana_thel.cpp