Azerotcore-wotlk: src/server/game/Events/GameEventMgr.h File Reference
GameEventMgr.h File Reference
#include "Common.h"
#include "ObjectGuid.h"
#include "SharedDefines.h"
#include <map>
Classes
struct GameEventFinishCondition
struct GameEventQuestToEventConditionNum
struct GameEventData
struct ModelEquip
struct NPCVendorEntry
class GameEventMgr
Macros
#define max_ge_check_delay DAY
#define sGameEventMgr GameEventMgr::instance()
Typedefs
typedef std::map< uint32, GameEventFinishCondition > GameEventConditionMap
Enumerations
enum GameEventState {
GAMEEVENT_NORMAL = 0 , GAMEEVENT_WORLD_INACTIVE = 1 , GAMEEVENT_WORLD_CONDITIONS = 2 , GAMEEVENT_WORLD_NEXTPHASE = 3 ,
GAMEEVENT_WORLD_FINISHED = 4 , GAMEEVENT_INTERNAL = 5
}
Functions
bool IsHolidayActive (HolidayIds id)
bool IsEventActive (uint16 event_id)
Macro Definition Documentation
max_ge_check_delay
#define max_ge_check_delay DAY
Definition at line 26 of file GameEventMgr.h.
sGameEventMgr
#define sGameEventMgr GameEventMgr::instance()
Definition at line 183 of file GameEventMgr.h.
Typedef Documentation
GameEventConditionMap
typedef std::map<uint32 , GameEventFinishCondition> GameEventConditionMap
Definition at line 53 of file GameEventMgr.h.
Enumeration Type Documentation
GameEventState
enum GameEventState
Enumerator
GAMEEVENT_NORMAL
GAMEEVENT_WORLD_INACTIVE
GAMEEVENT_WORLD_CONDITIONS
GAMEEVENT_WORLD_NEXTPHASE
GAMEEVENT_WORLD_FINISHED
GAMEEVENT_INTERNAL
Definition at line 28 of file GameEventMgr.h.
 {
     GAMEEVENT_NORMAL = 0,   // standard game events
     GAMEEVENT_WORLD_INACTIVE = 1,   // not yet started
     GAMEEVENT_WORLD_CONDITIONS = 2,  // condition matching phase
     GAMEEVENT_WORLD_NEXTPHASE = 3,   // conditions are met, now 'length' timer to start next event
     GAMEEVENT_WORLD_FINISHED = 4,    // next events are started, unapply this one
     GAMEEVENT_INTERNAL = 5, // never handled in update
 };
Function Documentation
IsEventActive()
bool IsEventActive (uint16 event_id)
Definition at line 1892 of file GameEventMgr.cpp.
 {
     GameEventMgr::ActiveEvents const& ae = sGameEventMgr->GetActiveEventList();
     return ae.find(event_id) != ae.end();
 }
References sGameEventMgr.
Referenced by Player::_LoadBrewOfTheMonth(), npc_innkeeper::OnGossipHello(), and npc_innkeeper::OnGossipSelect().
IsHolidayActive()
bool IsHolidayActive (HolidayIds id)
Definition at line 1877 of file GameEventMgr.cpp.
 {
     if (id == HOLIDAY_NONE)
         return false;
     GameEventMgr::GameEventDataMap const& events = sGameEventMgr->GetEventMap();
     GameEventMgr::ActiveEvents const& ae = sGameEventMgr->GetActiveEventList();
     for (GameEventMgr::ActiveEvents::const_iterator itr = ae.begin(); itr != ae.end(); ++itr)
         if (events[*itr].holiday_id == id)
             return true;
     return false;
 }
References HOLIDAY_NONE, and sGameEventMgr.
Referenced by Player::CanUseItem(), BattlegroundMgr::IsBGWeekend(), lfg::LFGMgr::IsSeasonActive(), AchievementCriteriaData::Meets(), BattlegroundAV::SetupBattleground(), go_brewfest_music::go_brewfest_musicAI::UpdateAI(), go_pirate_day_music::go_pirate_day_musicAI::UpdateAI(), go_darkmoon_faire_music::go_darkmoon_faire_musicAI::UpdateAI(), and go_midsummer_music::go_midsummer_musicAI::UpdateAI().