Azerotcore-wotlk: deps/recastnavigation/Recast/Source/RecastFilter.cpp File Reference
RecastFilter.cpp File Reference
#include <math.h>
#include <stdio.h>
#include "Recast.h"
#include "RecastAssert.h"
Macros
#define _USE_MATH_DEFINES
Functions
void rcFilterLowHangingWalkableObstacles (rcContext *ctx, const int walkableClimb, rcHeightfield &solid)
void rcFilterLedgeSpans (rcContext *ctx, const int walkableHeight, const int walkableClimb, rcHeightfield &solid)
void rcFilterWalkableLowHeightSpans (rcContext *ctx, int walkableHeight, rcHeightfield &solid)
Macro Definition Documentation
_USE_MATH_DEFINES
#define _USE_MATH_DEFINES
Definition at line 19 of file RecastFilter.cpp.
Function Documentation
rcFilterLedgeSpans()
void rcFilterLedgeSpans (rcContext * ctx, const int walkableHeight, const int walkableClimb, rcHeightfield & solid)
A ledge is a span with one or more neighbors whose maximum is further away than walkableClimb from the current span's maximum. This method removes the impact of the overestimation of conservative voxelization so the resulting mesh will not have regions hanging in the air over ledges.
A span is a ledge if: rcAbs(currentSpan.smax - neighborSpan.smax) > walkableClimb
See also
rcHeightfield, rcConfig
Definition at line 82 of file RecastFilter.cpp.
 {
     rcAssert(ctx);
     rcScopedTimer timer(ctx, RC_TIMER_FILTER_BORDER);
     const int w = solid.width;
     const int h = solid.height;
     const int MAX_HEIGHT = 0xffff;
     // Mark border spans.
     for (int y = 0; y < h; ++y)
     {
         for (int x = 0; x < w; ++x)
         {
             for (rcSpan* s = solid.spans[x + y*w]; s; s = s->next)
             {
                 // Skip non walkable spans.
                 if (s->area == RC_NULL_AREA)
                     continue;
                 const int bot = (int)(s->smax);
                 const int top = s->next ? (int)(s->next->smin) : MAX_HEIGHT;
                 // Find neighbours minimum height.
                 int minh = MAX_HEIGHT;
                 // Min and max height of accessible neighbours.
                 int asmin = s->smax;
                 int asmax = s->smax;
                 for (int dir = 0; dir < 4; ++dir)
                 {
                     int dx = x + rcGetDirOffsetX(dir);
                     int dy = y + rcGetDirOffsetY(dir);
                     // Skip neighbours which are out of bounds.
                     if (dx < 0 || dy < 0 || dx >= w || dy >= h)
                     {
                         minh = rcMin(minh, -walkableClimb - bot);
                         continue;
                     }
                     // From minus infinity to the first span.
                     rcSpan* ns = solid.spans[dx + dy*w];
                     int nbot = -walkableClimb;
                     int ntop = ns ? (int)ns->smin : MAX_HEIGHT;
                     // Skip neightbour if the gap between the spans is too small.
                     if (rcMin(top,ntop) - rcMax(bot,nbot) > walkableHeight)
                         minh = rcMin(minh, nbot - bot);
                     // Rest of the spans.
                     for (ns = solid.spans[dx + dy*w]; ns; ns = ns->next)
                     {
                         nbot = (int)ns->smax;
                         ntop = ns->next ? (int)ns->next->smin : MAX_HEIGHT;
                         // Skip neightbour if the gap between the spans is too small.
                         if (rcMin(top,ntop) - rcMax(bot,nbot) > walkableHeight)
{
                             minh = rcMin(minh, nbot - bot);
                             // Find min/max accessible neighbour height.
                             if (rcAbs(nbot - bot) <= walkableClimb)
{
                                 if (nbot < asmin) asmin = nbot;
                                 if (nbot > asmax) asmax = nbot;
                             }
                         }
                     }
                 }
                 // The current span is close to a ledge if the drop to any
                 // neighbour span is less than the walkableClimb.
                 if (minh < -walkableClimb)
                 {
                     s->area = RC_NULL_AREA;
                 }
                 // If the difference between all neighbours is too large,
                 // we are at steep slope, mark the span as ledge.
                 else if ((asmax - asmin) > walkableClimb)
                 {
                     s->area = RC_NULL_AREA;
                 }
             }
         }
     }
 }
References rcHeightfield::height, if(), MAX_HEIGHT, rcSpan::next, RC_NULL_AREA, RC_TIMER_FILTER_BORDER, rcAbs(), rcAssert, rcGetDirOffsetX(), rcGetDirOffsetY(), rcMax(), rcMin(), rcSpan::smax, rcSpan::smin, rcHeightfield::spans, rcHeightfield::width, G3D::x, and G3D::y.
Referenced by TileBuilder::BuildInstance(), MMAP::MapBuilder::buildMoveMapTile(), and TileBuilder::BuildTiled().
rcFilterLowHangingWalkableObstacles()
void rcFilterLowHangingWalkableObstacles (rcContext * ctx, const int walkableClimb, rcHeightfield & solid)
Allows the formation of walkable regions that will flow over low lying objects such as curbs, and up structures such as stairways.
Two neighboring spans are walkable if: rcAbs(currentSpan.smax - neighborSpan.smax) < waklableClimb
Warning
Will override the effect of rcFilterLedgeSpans. So if both filters are used, call rcFilterLedgeSpans after calling this filter.
See also
rcHeightfield, rcConfig
Definition at line 36 of file RecastFilter.cpp.
 {
     rcAssert(ctx);
     rcScopedTimer timer(ctx, RC_TIMER_FILTER_LOW_OBSTACLES);
     const int w = solid.width;
     const int h = solid.height;
     for (int y = 0; y < h; ++y)
     {
         for (int x = 0; x < w; ++x)
         {
             rcSpan* ps = 0;
             bool previousWalkable = false;
             unsigned char previousArea = RC_NULL_AREA;
             for (rcSpan* s = solid.spans[x + y*w]; s; ps = s, s = s->next)
             {
                 const bool walkable = s->area != RC_NULL_AREA;
                 // If current span is not walkable, but there is walkable
                 // span just below it, mark the span above it walkable too.
                 if (!walkable && previousWalkable)
                 {
                     if (rcAbs((int)s->smax - (int)ps->smax) <= walkableClimb)
                         s->area = previousArea;
                 }
                 // Copy walkable flag so that it cannot propagate
                 // past multiple non-walkable objects.
                 previousWalkable = walkable;
                 previousArea = s->area;
             }
         }
     }
 }
References rcHeightfield::height, rcSpan::next, RC_NULL_AREA, RC_TIMER_FILTER_LOW_OBSTACLES, rcAbs(), rcAssert, rcSpan::smax, rcHeightfield::spans, rcHeightfield::width, G3D::x, and G3D::y.
Referenced by TileBuilder::BuildInstance(), MMAP::MapBuilder::buildMoveMapTile(), and TileBuilder::BuildTiled().
rcFilterWalkableLowHeightSpans()
void rcFilterWalkableLowHeightSpans (rcContext * ctx, int walkableHeight, rcHeightfield & solid)
For this filter, the clearance above the span is the distance from the span's maximum to the next higher span's minimum. (Same grid column.)
See also
rcHeightfield, rcConfig
Definition at line 177 of file RecastFilter.cpp.
 {
     rcAssert(ctx);
     rcScopedTimer timer(ctx, RC_TIMER_FILTER_WALKABLE);
     const int w = solid.width;
     const int h = solid.height;
     const int MAX_HEIGHT = 0xffff;
     // Remove walkable flag from spans which do not have enough
     // space above them for the agent to stand there.
     for (int y = 0; y < h; ++y)
     {
         for (int x = 0; x < w; ++x)
         {
             for (rcSpan* s = solid.spans[x + y*w]; s; s = s->next)
             {
                 const int bot = (int)(s->smax);
                 const int top = s->next ? (int)(s->next->smin) : MAX_HEIGHT;
                 if ((top - bot) <= walkableHeight)
                     s->area = RC_NULL_AREA;
             }
         }
     }
 }
References rcHeightfield::height, MAX_HEIGHT, rcSpan::next, RC_NULL_AREA, RC_TIMER_FILTER_WALKABLE, rcAssert, rcHeightfield::spans, rcHeightfield::width, G3D::x, and G3D::y.
Referenced by TileBuilder::BuildInstance(), MMAP::MapBuilder::buildMoveMapTile(), and TileBuilder::BuildTiled().