Azerotcore-wotlk: G3D::Pointer< ValueType >::Interface Class Reference
G3D::Pointer< ValueType >::Interface Class Reference abstract
Public Member Functions
virtual ~Interface ()
virtual void set (ValueType b)=0
virtual ValueType get () const =0
virtual Interface * clone () const =0
virtual bool isNull () const =0
Detailed Description
template<typename ValueType>
class G3D::Pointer< ValueType >::Interface
Definition at line 66 of file Pointer.h.
Constructor & Destructor Documentation
~Interface()
template<typename ValueType > virtual G3D::Pointer< ValueType >::Interface::~Interface () inline virtual
Definition at line 68 of file Pointer.h.
 {};
Member Function Documentation
clone()
template<typename ValueType > virtual Interface* G3D::Pointer< ValueType >::Interface::clone () const pure virtual
Implemented in G3D::Pointer< ValueType >::SharedAccessor< T, GetMethod, SetMethod >, G3D::Pointer< ValueType >::Accessor< T, GetMethod, SetMethod >, G3D::Pointer< ValueType >::FcnAccessor< GetMethod, SetMethod >, and G3D::Pointer< ValueType >::Memory.
Referenced by G3D::Pointer< ValueType >::operator=().
get()
template<typename ValueType > virtual ValueType G3D::Pointer< ValueType >::Interface::get () const pure virtual
Implemented in G3D::Pointer< ValueType >::SharedAccessor< T, GetMethod, SetMethod >, G3D::Pointer< ValueType >::Accessor< T, GetMethod, SetMethod >, G3D::Pointer< ValueType >::FcnAccessor< GetMethod, SetMethod >, and G3D::Pointer< ValueType >::Memory.
Referenced by G3D::Pointer< ValueType >::getValue().
isNull()
template<typename ValueType > virtual bool G3D::Pointer< ValueType >::Interface::isNull () const pure virtual
Implemented in G3D::Pointer< ValueType >::SharedAccessor< T, GetMethod, SetMethod >, G3D::Pointer< ValueType >::Accessor< T, GetMethod, SetMethod >, G3D::Pointer< ValueType >::FcnAccessor< GetMethod, SetMethod >, and G3D::Pointer< ValueType >::Memory.
Referenced by G3D::Pointer< ValueType >::isNull().
set()
template<typename ValueType > virtual void G3D::Pointer< ValueType >::Interface::set (ValueType b) pure virtual
Implemented in G3D::Pointer< ValueType >::SharedAccessor< T, GetMethod, SetMethod >, G3D::Pointer< ValueType >::Accessor< T, GetMethod, SetMethod >, G3D::Pointer< ValueType >::FcnAccessor< GetMethod, SetMethod >, and G3D::Pointer< ValueType >::Memory.
Referenced by G3D::Pointer< ValueType >::setValue().
The documentation for this class was generated from the following file:
deps/g3dlite/include/G3D/Pointer.h