Azerotcore-wotlk: deps/mysqllite/mysys/my_getwd.c File Reference
my_getwd.c File Reference
#include "mysys_priv.h"
#include <m_string.h>
#include "mysys_err.h"
Functions
int my_getwd (char *buf, size_t size, myf MyFlags)
int my_setwd (const char *dir, myf MyFlags)
int test_if_hard_path (register const char *dir_name)
my_bool has_path (const char *name)
Function Documentation
has_path()
my_bool has_path (const char * name)
Definition at line 157 of file my_getwd.c.
 {
   return test(strchr(name, FN_LIBCHAR))
 #if FN_LIBCHAR != '/'
     || test(strchr(name,'/'))
 #endif
 #ifdef FN_DEVCHAR
     || test(strchr(name, FN_DEVCHAR))
 #endif
     ;
 }
References FN_DEVCHAR, FN_LIBCHAR, and test.
my_getwd()
int my_getwd (char * buf, size_t size, myf MyFlags)
Definition at line 46 of file my_getwd.c.
 {
   char * pos;
   DBUG_ENTER("my_getwd");
   DBUG_PRINT("my",("buf: 0x%lx  size: %u  MyFlags %d",
                    (long) buf, (uint) size, MyFlags));
   if (size < 1)
     DBUG_RETURN(-1);
   if (curr_dir[0])              /* Current pos is saved here */
     (void) strmake(buf,&curr_dir[0],size-1);
   else
   {
 #if defined(HAVE_GETCWD)
     if (size < 2)
       DBUG_RETURN(-1);
     if (!getcwd(buf,(uint) (size-2)) && MyFlags & MY_WME)
     {
       my_errno=errno;
       my_error(EE_GETWD,MYF(ME_BELL+ME_WAITTANG),errno);
       DBUG_RETURN(-1);
     }
 #elif defined(HAVE_GETWD)
     {
       char pathname[MAXPATHLEN];
       getwd(pathname);
       strmake(buf,pathname,size-1);
     }
 #else
 #error "No way to get current directory"
 #endif
     if (*((pos=strend(buf))-1) != FN_LIBCHAR)  /* End with FN_LIBCHAR */
     {
       pos[0]= FN_LIBCHAR;
       pos[1]=0;
     }
     (void) strmake(&curr_dir[0],buf, (size_t) (FN_REFLEN-1));
   }
   DBUG_RETURN(0);
 } /* my_getwd */
References curr_dir, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_GETWD, errno, FN_LIBCHAR, FN_REFLEN, ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_WME, MYF, pos(), strend(), and strmake().
Referenced by cleanup_dirname(), fn_expand(), my_load_path(), my_path(), and pack_dirname().
my_setwd()
int my_setwd (const char * dir, myf MyFlags)
Definition at line 91 of file my_getwd.c.
 {
   int res;
   size_t length;
   char *start, *pos;
   DBUG_ENTER("my_setwd");
   DBUG_PRINT("my",("dir: '%s'  MyFlags %d", dir, MyFlags));
   start=(char *) dir;
   if (! dir[0] || (dir[0] == FN_LIBCHAR && dir[1] == 0))
     dir=FN_ROOTDIR;
   if ((res=chdir((char*) dir)) != 0)
   {
     my_errno=errno;
     if (MyFlags & MY_WME)
       my_error(EE_SETWD,MYF(ME_BELL+ME_WAITTANG),start,errno);
   }
   else
   {
     if (test_if_hard_path(start))
     {                       /* Hard pathname */
       pos= strmake(&curr_dir[0],start,(size_t) FN_REFLEN-1);
       if (pos[-1] != FN_LIBCHAR)
       {
     length=(uint) (pos-(char*) curr_dir);
     curr_dir[length]=FN_LIBCHAR;        /* must end with '/' */
     curr_dir[length+1]='\0';
       }
     }
     else
       curr_dir[0]='\0';             /* Don't save name */
   }
   DBUG_RETURN(res);
 } /* my_setwd */
References curr_dir, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_SETWD, errno, FN_LIBCHAR, FN_REFLEN, FN_ROOTDIR, G3D::length(), ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_WME, MYF, pos(), strmake(), and test_if_hard_path().
test_if_hard_path()
int test_if_hard_path (register const char * dir_name)
Definition at line 131 of file my_getwd.c.
 {
   if (dir_name[0] == FN_HOMELIB && dir_name[1] == FN_LIBCHAR)
     return (home_dir != NullS && test_if_hard_path(home_dir));
   if (dir_name[0] == FN_LIBCHAR)
     return (TRUE);
 #ifdef FN_DEVCHAR
   return (strchr(dir_name,FN_DEVCHAR) != 0);
 #else
   return FALSE;
 #endif
 } /* test_if_hard_path */
References FALSE, FN_DEVCHAR, FN_HOMELIB, FN_LIBCHAR, home_dir, NullS, and TRUE.
Referenced by my_setwd().