Azerotcore-wotlk: deps/readline/CMakeLists.txt File Reference
deps/readline/CMakeLists.txt File Reference
Functions
if (UNIX) find_path(READLINE_INCLUDE_DIR readline/readline.h) find_library(READLINE_LIBRARY NAMES readline) message(STATUS "Found Readline library
message (STATUS "Include dir is: ${READLINE_INCLUDE_DIR}") if(NOT READLINE_INCLUDE_DIR OR NOT READLINE_LIBRARY) message(FATAL_ERROR "** Readline library not found!\n** Your distro may provide a binary for Readline e.g. for ubuntuapt-get install libreadline5-dev") endif() add_library(readline SHARED IMPORTED GLOBAL) set_target_properties(readline PROPERTIES IMPORTED_LOCATION "$
Function Documentation
if()
if (UNIX)
Definition at line 13 of file CMakeLists.txt.
                                         : ${READLINE_LIBRARY}")
message()
message (STATUS "Include dir is: ${READLINE_INCLUDE_DIR}")
Definition at line 22 of file CMakeLists.txt.
                                 : ${READLINE_INCLUDE_DIR}")
   if (NOT READLINE_INCLUDE_DIR OR NOT READLINE_LIBRARY)
     message(FATAL_ERROR "** Readline library not found!\n** Your distro may provide a binary for Readline e.g. for ubuntu try apt-get install libreadline5-dev")
   endif ()
   add_library(readline SHARED IMPORTED GLOBAL)
   set_target_properties(readline
     PROPERTIES
       IMPORTED_LOCATION
         "${READLINE_LIBRARY}"
Referenced by G3D::_internal::_handleDebugAssert_(), G3D::_internal::_handleErrorCheck_(), Log::_outMessageFmt(), AppenderConsole::_write(), AppenderFile::_write(), AppenderDB::_write(), Acore::Abort(), GossipMenu::AddMenuItem(), Acore::Assert(), detail::assert_fail(), ChatHandler::BuildChatPacket(), MMAP::MapBuilder::buildMoveMapTile(), MMAP::MapBuilder::buildNavMesh(), check_scramble(), check_scramble_323(), G3D::_internal::createErrorMessage(), ArenaSpectator::CreatePacket(), Acore::Error(), BattlegroundAB::EventPlayerClickedOnFlag(), Acore::Fatal(), finish(), detail::format_error_code(), format_system_error(), MMAP::IntermediateValues::generateObjFile(), message_commandscript::HandleAnnounceCommand(), message_commandscript::HandleGMAnnounceCommand(), message_commandscript::HandleGMNameAnnounceCommand(), message_commandscript::HandleGMNotifyCommand(), WorldSession::HandleGMTicketCreateOpcode(), WorldSession::HandleGMTicketUpdateOpcode(), message_commandscript::HandleNameAnnounceCommand(), message_commandscript::HandleNotifyCommand(), WorldSession::HandleTextEmoteOpcode(), G3D::msgBox(), error_handler::on_error(), basic_format_parse_context< Char, ErrorHandler >::on_error(), basic_format_context< OutputIt, Char >::on_error(), dynamic_specs_handler< ParseContext >::on_error(), format_string_checker< Char, ErrorHandler, Args >::on_error(), specs_handler< Char >::on_error(), basic_printf_context< OutputIt, Char >::on_error(), Log::outCommand(), Log::outMessage(), WorldPackets::PacketArrayMaxCapacityException::PacketArrayMaxCapacityException(), parse_precision(), parse_replacement_field(), parse_width(), anonymous_namespace{Config.cpp}::PrintError(), G3D::LightweightConduit::receive(), G3D::ReliableConduit::receive(), detail::report_error(), report_system_error(), scramble(), scramble_323(), G3D::ReliableConduit::send(), AchievementMgr::SendAchievementEarned(), GmTicket::SetMessage(), throw_format_error(), G3D::Any::verify(), Acore::Warning(), Appender::write(), and Logger::write().