Azerotcore-wotlk: npc_brewfest_keg_reciver Class Reference
npc_brewfest_keg_reciver Class Reference
Classes
struct npc_brewfest_keg_reciverAI
Public Member Functions
npc_brewfest_keg_reciver ()
CreatureAI * GetAI (Creature *creature) const override
bool OnGossipSelect (Player *player, Creature *, uint32, uint32 uiAction) override
bool OnGossipHello (Player *player, Creature *creature) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 92 of file brewfest.cpp.
Constructor & Destructor Documentation
npc_brewfest_keg_reciver()
npc_brewfest_keg_reciver::npc_brewfest_keg_reciver () inline
Definition at line 95 of file brewfest.cpp.
 : CreatureScript("npc_brewfest_keg_reciver") { }
Member Function Documentation
GetAI()
CreatureAI* npc_brewfest_keg_reciver::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 133 of file brewfest.cpp.
     {
         return new npc_brewfest_keg_reciverAI(creature);
     }
OnGossipHello()
bool npc_brewfest_keg_reciver::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 152 of file brewfest.cpp.
     {
         if (creature->IsQuestGiver())
             player->PrepareQuestMenu(creature->GetGUID());
         if (!player->HasSpellCooldown(SPELL_COOLDOWN_CHECKER) && player->GetQuestRewardStatus(player->GetTeamId() == TEAM_ALLIANCE ? QUEST_THERE_AND_BACK_AGAIN_A : QUEST_THERE_AND_BACK_AGAIN_H))
             AddGossipItemFor(player, GOSSIP_ICON_CHAT, "Do you have additional work?", GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
         SendGossipMenuFor(player, (creature->GetEntry() == NPC_NEILL_RAMSTEIN ? 8934 : 8976), creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), Object::GetEntry(), Object::GetGUID(), Player::GetQuestRewardStatus(), Player::GetTeamId(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, Player::HasSpellCooldown(), Unit::IsQuestGiver(), NPC_NEILL_RAMSTEIN, Player::PrepareQuestMenu(), QUEST_THERE_AND_BACK_AGAIN_A, QUEST_THERE_AND_BACK_AGAIN_H, SendGossipMenuFor(), SPELL_COOLDOWN_CHECKER, and TEAM_ALLIANCE.
OnGossipSelect()
bool npc_brewfest_keg_reciver::OnGossipSelect (Player * player, Creature * , uint32 , uint32 uiAction) inline override virtual
Reimplemented from CreatureScript.
Definition at line 138 of file brewfest.cpp.
     {
         switch (uiAction)
         {
             case GOSSIP_ACTION_INFO_DEF+1:
                 CloseGossipMenuFor(player);
                 player->AddSpellCooldown(SPELL_COOLDOWN_CHECKER, 0, 18 * HOUR * IN_MILLISECONDS);
                 player->CastSpell(player, 43883, true);
                 player->CastSpell(player, 44262, true);
                 break;
         }
         return true;
     }
References Player::AddSpellCooldown(), Unit::CastSpell(), CloseGossipMenuFor(), GOSSIP_ACTION_INFO_DEF, HOUR, IN_MILLISECONDS, and SPELL_COOLDOWN_CHECKER.
The documentation for this class was generated from the following file:
src/server/scripts/Events/brewfest.cpp