Azerotcore-wotlk: boss_yoggsaron::boss_yoggsaronAI Struct Reference
boss_yoggsaron::boss_yoggsaronAI Struct Reference
Public Member Functions
boss_yoggsaronAI (Creature *pCreature)
void AttackStart (Unit *) override
void JustSummoned (Creature *cr) override
void SummonImmortalGuardian ()
void JustDied (Unit *) override
void DoAction (int32 param) override
uint32 GetData (uint32 param) const override
void SpellHit (Unit *, const SpellInfo *spellInfo) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * m_pInstance
EventMap events
SummonList summons
bool _thirdPhase
bool _usedInsane
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1036 of file boss_yoggsaron.cpp.
Constructor & Destructor Documentation
boss_yoggsaronAI()
boss_yoggsaron::boss_yoggsaronAI::boss_yoggsaronAI (Creature * pCreature) inline
Definition at line 1038 of file boss_yoggsaron.cpp.
                                               : ScriptedAI(pCreature), summons(pCreature)
         {
             m_pInstance = me->GetInstanceScript();
             _thirdPhase = false;
             _usedInsane = false;
             summons.DespawnAll();
             events.Reset();
             uint8 _count = 4;
             me->SetLootMode(31); // 1 + 2 + 4 + 8 + 16, remove with watchers addition
             if (m_pInstance)
             {
                 for (uint8 i = 0; i < 4; ++i)
                     if (m_pInstance->GetData(TYPE_WATCHERS) & (1 << i))
                     {
                         me->RemoveLootMode(1 << _count);
                         --_count;
                     }
             }
         }
References _thirdPhase, _usedInsane, SummonList::DespawnAll(), ZoneScript::GetData(), WorldObject::GetInstanceScript(), m_pInstance, ScriptedAI::me, Creature::RemoveLootMode(), Creature::SetLootMode(), summons, and TYPE_WATCHERS.
Member Function Documentation
AttackStart()
void boss_yoggsaron::boss_yoggsaronAI::AttackStart (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1065 of file boss_yoggsaron.cpp.
 { }
DoAction()
void boss_yoggsaron::boss_yoggsaronAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 1103 of file boss_yoggsaron.cpp.
         {
             if (param == ACTION_DESPAWN_ADDS)
                 summons.DespawnAll();
             else if (param == ACTION_YOGG_SARON_APPEAR)
             {
                 me->SetVisible(true);
                 me->CastSpell(me, SPELL_SHADOW_BARRIER, true);
                 me->CastSpell(me, SPELL_KNOCK_AWAY, true);
                 me->HandleEmoteCommand(EMOTE_ONESHOT_EMERGE);
                 me->SetInCombatWithZone();
                 me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE | UNIT_FLAG_PACIFIED);
             }
             else if (param == ACTION_YOGG_SARON_START_YELL)
             {
                 me->Yell("BOW DOWN BEFORE THE GOD OF DEATH!", LANG_UNIVERSAL);
             }
             else if (param == ACTION_YOGG_SARON_OPEN_PORTAL_YELL)
             {
                 me->Yell("MADNESS WILL CONSUME YOU!", LANG_UNIVERSAL);
                 me->PlayDirectSound(YS_OPEN_PORTALS);
             }
             else if (param == ACTION_YOGG_SARON_START_P3)
             {
                 me->SetHealth(me->GetMaxHealth() * 0.3f);
                 me->LowerPlayerDamageReq(me->GetMaxHealth() * 0.7f);
                 me->RemoveAura(SPELL_SHADOW_BARRIER);
                 events.ScheduleEvent(EVENT_YS_LUNATIC_GAZE, 7000);
                 events.ScheduleEvent(EVENT_YS_SHADOW_BEACON, 20000);
                 events.ScheduleEvent(EVENT_YS_SUMMON_GUARDIAN, 0);
                 _thirdPhase = true;
                 me->Yell("Look upon the true face of death and know that your end comes soon!", LANG_UNIVERSAL);
                 me->PlayDirectSound(YS_P3_START);
             }
             else if (param == ACTION_YOGG_SARON_HARD_MODE)
             {
                 events.ScheduleEvent(EVENT_YS_DEAFENING_ROAR, 50000);
             }
             else if (param == ACTION_YOGG_SARON_SHADOW_BEACON)
             {
                 events.RescheduleEvent(EVENT_YS_SHADOW_BEACON, 40000);
             }
             else if (param == ACTION_REMOVE_STUN)
             {
                 me->RemoveAura(SPELL_SHATTERED_ILLUSION);
                 me->SetControlled(true, UNIT_STATE_ROOT);
             }
             else if (param == ACTION_FAILED_DRIVE_ME_CRAZY)
                 _usedInsane = true;
         }
References _thirdPhase, _usedInsane, ACTION_DESPAWN_ADDS, ACTION_FAILED_DRIVE_ME_CRAZY, ACTION_REMOVE_STUN, ACTION_YOGG_SARON_APPEAR, ACTION_YOGG_SARON_HARD_MODE, ACTION_YOGG_SARON_OPEN_PORTAL_YELL, ACTION_YOGG_SARON_SHADOW_BEACON, ACTION_YOGG_SARON_START_P3, ACTION_YOGG_SARON_START_YELL, Unit::CastSpell(), SummonList::DespawnAll(), EMOTE_ONESHOT_EMERGE, EVENT_YS_DEAFENING_ROAR, EVENT_YS_LUNATIC_GAZE, EVENT_YS_SHADOW_BEACON, EVENT_YS_SUMMON_GUARDIAN, Unit::GetMaxHealth(), Unit::HandleEmoteCommand(), LANG_UNIVERSAL, Creature::LowerPlayerDamageReq(), ScriptedAI::me, WorldObject::PlayDirectSound(), Unit::RemoveAura(), Unit::SetControlled(), Object::SetFlag(), Unit::SetHealth(), Creature::SetInCombatWithZone(), Unit::SetVisible(), SPELL_KNOCK_AWAY, SPELL_SHADOW_BARRIER, SPELL_SHATTERED_ILLUSION, summons, UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE, UNIT_FLAG_PACIFIED, UNIT_STATE_ROOT, Unit::Yell(), YS_OPEN_PORTALS, and YS_P3_START.
GetData()
uint32 boss_yoggsaron::boss_yoggsaronAI::GetData (uint32 param) const inline override virtual
Reimplemented from UnitAI.
Definition at line 1158 of file boss_yoggsaron.cpp.
         {
             if (param == DATA_GET_DRIVE_ME_CRAZY)
                 return !_usedInsane;
             return 0;
         }
References _usedInsane, and DATA_GET_DRIVE_ME_CRAZY.
JustDied()
void boss_yoggsaron::boss_yoggsaronAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1077 of file boss_yoggsaron.cpp.
         {
             summons.DespawnAll();
             events.Reset();
             me->Yell("Your fate is sealed. The end of days is finally upon you and ALL who inhabit this miserable little seedling. Uulwi ifis halahs gag erh'ongg w'ssh.", LANG_UNIVERSAL);
             me->PlayDirectSound(YS_P3_DEATH);
             if (m_pInstance)
             {
                 m_pInstance->SetData(TYPE_YOGGSARON, DONE);
                 if (Creature* sara = ObjectAccessor::GetCreature(*me, m_pInstance->GetGuidData(NPC_SARA)))
                     sara->AI()->DoAction(ACTION_YOGG_SARON_DEATH);
                 if (GameObject* go = ObjectAccessor::GetGameObject(*me, m_pInstance->GetGuidData(GO_YOGG_SARON_DOORS)))
                     go->SetGoState(GO_STATE_ACTIVE);
             }
             Map::PlayerList const& pList = me->GetMap()->GetPlayers();
             for(Map::PlayerList::const_iterator itr = pList.begin(); itr != pList.end(); ++itr)
             {
                 itr->GetSource()->RemoveAura(SPELL_SANITY);
                 itr->GetSource()->RemoveAura(SPELL_INSANE1);
                 itr->GetSource()->RemoveAura(SPELL_INSANE2);
             }
         }
References ACTION_YOGG_SARON_DEATH, MapRefMgr::begin(), SummonList::DespawnAll(), DONE, MapRefMgr::end(), ObjectAccessor::GetCreature(), ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), Map::GetPlayers(), GO_STATE_ACTIVE, GO_YOGG_SARON_DOORS, LANG_UNIVERSAL, m_pInstance, ScriptedAI::me, NPC_SARA, WorldObject::PlayDirectSound(), ZoneScript::SetData(), SPELL_INSANE1, SPELL_INSANE2, SPELL_SANITY, summons, TYPE_YOGGSARON, Unit::Yell(), and YS_P3_DEATH.
JustSummoned()
void boss_yoggsaron::boss_yoggsaronAI::JustSummoned (Creature * cr) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1067 of file boss_yoggsaron.cpp.
 { summons.Summon(cr); }
References SummonList::Summon(), and summons.
SpellHit()
void boss_yoggsaron::boss_yoggsaronAI::SpellHit (Unit * , const SpellInfo * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1166 of file boss_yoggsaron.cpp.
         {
             if (spellInfo->Id == SPELL_IN_THE_MAWS_OF_THE_OLD_GOD)
                 me->AddLootMode(32);
         }
References Creature::AddLootMode(), SpellInfo::Id, ScriptedAI::me, and SPELL_IN_THE_MAWS_OF_THE_OLD_GOD.
SummonImmortalGuardian()
void boss_yoggsaron::boss_yoggsaronAI::SummonImmortalGuardian () inline
Definition at line 1069 of file boss_yoggsaron.cpp.
         {
             uint32 dist = urand(38, 48);
             float o = rand_norm() * M_PI * 2;
             float Zplus = (dist - 38) / 6.5f;
             me->SummonCreature(NPC_IMMORTAL_GUARDIAN, me->GetPositionX() + dist * cos(o), me->GetPositionY() + dist * sin(o), 327.2 + Zplus, 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 5000);
         }
References Position::GetPositionX(), Position::GetPositionY(), M_PI, ScriptedAI::me, NPC_IMMORTAL_GUARDIAN, rand_norm(), WorldObject::SummonCreature(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, and urand().
Referenced by UpdateAI().
UpdateAI()
void boss_yoggsaron::boss_yoggsaronAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1172 of file boss_yoggsaron.cpp.
         {
             if (!_thirdPhase)
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_YS_LUNATIC_GAZE:
                     me->Yell("Hoohehehahahaha... AHAHAHAHAHAHA!", LANG_UNIVERSAL);
                     me->PlayDirectSound(YS_P3_LUNATIC_GAZE);
                     me->CastSpell(me, SPELL_LUNATIC_GAZE_YS, true);
                     events.RepeatEvent(12000);
                     break;
                 case EVENT_YS_DEAFENING_ROAR:
                     me->TextEmote("Yogg-Saron opens his mouth wide!", nullptr, true);
                     me->Yell("Eternal suffering awaits!", LANG_UNIVERSAL);
                     me->PlayDirectSound(YS_P3_DEAFENING_ROAR);
                     me->CastSpell(me, SPELL_DEAFENING_ROAR, false);
                     events.RepeatEvent(50000);
                     break;
                 case EVENT_YS_SHADOW_BEACON:
                     events.RepeatEvent(5000);
                     me->CastCustomSpell(SPELL_SHADOW_BEACON, SPELLVALUE_MAX_TARGETS, RAID_MODE(1, 3), me, false);
                     break;
                 case EVENT_YS_SUMMON_GUARDIAN:
                     SummonImmortalGuardian();
                     events.RepeatEvent(10000);
                     break;
             }
         }
References _thirdPhase, Unit::CastCustomSpell(), Unit::CastSpell(), diff(), EVENT_YS_DEAFENING_ROAR, EVENT_YS_LUNATIC_GAZE, EVENT_YS_SHADOW_BEACON, EVENT_YS_SUMMON_GUARDIAN, Unit::HasUnitState(), LANG_UNIVERSAL, ScriptedAI::me, WorldObject::PlayDirectSound(), ScriptedAI::RAID_MODE(), SPELL_DEAFENING_ROAR, SPELL_LUNATIC_GAZE_YS, SPELL_SHADOW_BEACON, SPELLVALUE_MAX_TARGETS, SummonImmortalGuardian(), Unit::TextEmote(), UNIT_STATE_CASTING, Unit::Yell(), YS_P3_DEAFENING_ROAR, and YS_P3_LUNATIC_GAZE.
Member Data Documentation
_thirdPhase
bool boss_yoggsaron::boss_yoggsaronAI::_thirdPhase
Definition at line 1062 of file boss_yoggsaron.cpp.
Referenced by boss_yoggsaronAI(), DoAction(), and UpdateAI().
_usedInsane
bool boss_yoggsaron::boss_yoggsaronAI::_usedInsane
Definition at line 1063 of file boss_yoggsaron.cpp.
Referenced by boss_yoggsaronAI(), DoAction(), and GetData().
events
EventMap boss_yoggsaron::boss_yoggsaronAI::events
Definition at line 1060 of file boss_yoggsaron.cpp.
m_pInstance
InstanceScript* boss_yoggsaron::boss_yoggsaronAI::m_pInstance
Definition at line 1059 of file boss_yoggsaron.cpp.
Referenced by boss_yoggsaronAI(), and JustDied().
summons
SummonList boss_yoggsaron::boss_yoggsaronAI::summons
Definition at line 1061 of file boss_yoggsaron.cpp.
Referenced by boss_yoggsaronAI(), DoAction(), JustDied(), and JustSummoned().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_yoggsaron.cpp