Azerotcore-wotlk: npc_warden_mellichar::npc_warden_mellicharAI Struct Reference
npc_warden_mellichar::npc_warden_mellicharAI Struct Reference
Public Member Functions
npc_warden_mellicharAI (Creature *creature)
void JustSummoned (Creature *summon) override
void SummonedCreatureDies (Creature *summon, Unit *) override
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterCombat (Unit *) override
void JustDied (Unit *) override
void Reset () override
void DamageTaken (Unit *attacker, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void SetData (uint32 type, uint32 data) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void KilledUnit (Unit *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 328 of file arcatraz.cpp.
Constructor & Destructor Documentation
npc_warden_mellicharAI()
npc_warden_mellichar::npc_warden_mellicharAI::npc_warden_mellicharAI (Creature * creature) inline
Definition at line 330 of file arcatraz.cpp.
                                                    : BossAI(creature, DATA_WARDEN_MELLICHAR)
         {
         }
Member Function Documentation
AttackStart()
void npc_warden_mellichar::npc_warden_mellicharAI::AttackStart (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 356 of file arcatraz.cpp.
 { }
Referenced by UpdateAI().
DamageTaken()
void npc_warden_mellichar::npc_warden_mellicharAI::DamageTaken (Unit * attacker, uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 376 of file arcatraz.cpp.
         {
             if (attacker && attacker->GetCharmerOrOwnerOrOwnGUID().IsPlayer() && damage > 0 && !me->isActiveObject())
             {
                 me->setActive(true);
                 me->InterruptNonMeleeSpells(false);
                 me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
                 events.ScheduleEvent(EVENT_WARDEN_INTRO1, 1500);
                 events.ScheduleEvent(EVENT_WARDEN_CHECK_PLAYERS, 1000);
                 instance->SetBossState(DATA_WARDEN_MELLICHAR, IN_PROGRESS);
             }
             damage = 0;
         }
References DATA_WARDEN_MELLICHAR, EVENT_WARDEN_CHECK_PLAYERS, EVENT_WARDEN_INTRO1, Unit::GetCharmerOrOwnerOrOwnGUID(), IN_PROGRESS, BossAI::instance, Unit::InterruptNonMeleeSpells(), WorldObject::isActiveObject(), ObjectGuid::IsPlayer(), ScriptedAI::me, WorldObject::setActive(), InstanceScript::SetBossState(), Object::SetFlag(), UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, and UNIT_FLAG_IMMUNE_TO_PC.
EnterCombat()
void npc_warden_mellichar::npc_warden_mellicharAI::EnterCombat (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 357 of file arcatraz.cpp.
 { }
JustDied()
void npc_warden_mellichar::npc_warden_mellicharAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 359 of file arcatraz.cpp.
         {
             me->setActive(false);
         }
References ScriptedAI::me, and WorldObject::setActive().
JustSummoned()
void npc_warden_mellichar::npc_warden_mellicharAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
Definition at line 334 of file arcatraz.cpp.
         {
             summons.Summon(summon);
         }
References SummonList::Summon(), and BossAI::summons.
MoveInLineOfSight()
void npc_warden_mellichar::npc_warden_mellicharAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 355 of file arcatraz.cpp.
 { }
Reset()
void npc_warden_mellichar::npc_warden_mellicharAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 364 of file arcatraz.cpp.
         {
             _Reset();
             me->setActive(false);
             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
             me->RemoveFlag(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_DEAD);
             me->RemoveFlag(UNIT_FIELD_FLAGS_2, UNIT_FLAG2_FEIGN_DEATH);
             me->CastSpell((Unit*)nullptr, SPELL_TARGET_OMEGA, false);
             instance->HandleGameObject(instance->GetGuidData(DATA_WARDENS_SHIELD), true);
             instance->SetBossState(DATA_WARDEN_MELLICHAR, NOT_STARTED);
         }
References BossAI::_Reset(), Unit::CastSpell(), DATA_WARDEN_MELLICHAR, DATA_WARDENS_SHIELD, InstanceScript::GetGuidData(), InstanceScript::HandleGameObject(), BossAI::instance, ScriptedAI::me, NOT_STARTED, Object::RemoveFlag(), WorldObject::setActive(), InstanceScript::SetBossState(), SPELL_TARGET_OMEGA, UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_DEAD, UNIT_FIELD_FLAGS, UNIT_FIELD_FLAGS_2, UNIT_FLAG2_FEIGN_DEATH, UNIT_FLAG_IMMUNE_TO_NPC, and UNIT_FLAG_IMMUNE_TO_PC.
SetData()
void npc_warden_mellichar::npc_warden_mellicharAI::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from UnitAI.
Definition at line 390 of file arcatraz.cpp.
         {
             if (data == FAIL)
             {
                 CreatureAI::EnterEvadeMode();
                 return;
             }
             if (data != DONE)
                 return;
             switch (type)
             {
                 case DATA_WARDEN_1:
                     events.ScheduleEvent(EVENT_WARDEN_INTRO8, 2000);
                     break;
                 case DATA_WARDEN_3:
                     events.ScheduleEvent(EVENT_WARDEN_INTRO19, 2000);
                     break;
                 case DATA_WARDEN_4:
                     events.ScheduleEvent(EVENT_WARDEN_INTRO24, 2000);
                     break;
             }
         }
References DATA_WARDEN_1, DATA_WARDEN_3, DATA_WARDEN_4, DONE, CreatureAI::EnterEvadeMode(), EVENT_WARDEN_INTRO19, EVENT_WARDEN_INTRO24, EVENT_WARDEN_INTRO8, and FAIL.
SummonedCreatureDies()
void npc_warden_mellichar::npc_warden_mellicharAI::SummonedCreatureDies (Creature * summon, Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 339 of file arcatraz.cpp.
         {
             if (summon->GetEntry() == NPC_HARBINGER_SKYRISS)
             {
                 Unit::Kill(me, me);
                 me->setActive(false);
                 instance->SetBossState(DATA_WARDEN_MELLICHAR, DONE);
                 if (Creature* creature = summons.GetCreatureWithEntry(NPC_MILLHOUSE))
                 {
                     instance->DoCastSpellOnPlayers(SPELL_QID10886);
                     creature->AI()->Talk(SAY_COMPLETE);
                     creature->SetUInt32Value(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
                 }
             }
         }
References DATA_WARDEN_MELLICHAR, InstanceScript::DoCastSpellOnPlayers(), DONE, SummonList::GetCreatureWithEntry(), Object::GetEntry(), BossAI::instance, Unit::Kill(), ScriptedAI::me, NPC_HARBINGER_SKYRISS, NPC_MILLHOUSE, SAY_COMPLETE, WorldObject::setActive(), InstanceScript::SetBossState(), SPELL_QID10886, BossAI::summons, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
UpdateAI()
void npc_warden_mellichar::npc_warden_mellicharAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 414 of file arcatraz.cpp.
         {
             events.Update(diff);
             switch (events.ExecuteEvent())
             {
                 case EVENT_WARDEN_CHECK_PLAYERS:
                     if (!SelectTargetFromPlayerList(100.0f))
                     {
                         CreatureAI::EnterEvadeMode();
                         return;
                     }
                     events.ScheduleEvent(EVENT_WARDEN_CHECK_PLAYERS, 1000);
                     break;
                 case EVENT_WARDEN_INTRO1:
                     Talk(YELL_INTRO1);
                     me->SetFacingTo(M_PI / 2.0f);
                     me->CastSpell(me, SPELL_BUBBLE_VISUAL, false);
                     events.ScheduleEvent(EVENT_WARDEN_INTRO2, 1400);
                     break;
                 case EVENT_WARDEN_INTRO2:
                     instance->HandleGameObject(instance->GetGuidData(DATA_WARDENS_SHIELD), false);
                     events.ScheduleEvent(EVENT_WARDEN_INTRO3, 20000);
                     break;
                 case EVENT_WARDEN_INTRO3:
                     Talk(YELL_INTRO2);
                     events.ScheduleEvent(EVENT_WARDEN_INTRO4, 5000);
                     break;
                 case EVENT_WARDEN_INTRO4:
                     me->SetFacingTo(0.5f);
                     me->CastSpell((Unit*)nullptr, SPELL_TARGET_ALPHA, false);
                     events.ScheduleEvent(EVENT_WARDEN_INTRO5, 2000);
                     break;
                 case EVENT_WARDEN_INTRO5:
                     instance->SetData(DATA_WARDEN_1, IN_PROGRESS);
                     events.ScheduleEvent(EVENT_WARDEN_INTRO6, 3000);
                     break;
                 case EVENT_WARDEN_INTRO6:
                     me->SetFacingTo(M_PI * 1.5f);
                     me->CastSpell((Unit*)nullptr, SPELL_TARGET_OMEGA, false);
                     events.ScheduleEvent(EVENT_WARDEN_INTRO7, 5000);
                     break;
                 case EVENT_WARDEN_INTRO7:
                     me->SummonCreature(RAND(NPC_TRICKSTER, NPC_PH_HUNTER), 478.326f, -148.505f, 42.56f, 3.19f, TEMPSUMMON_MANUAL_DESPAWN);
                     // Wait for kill
                     break;
                 case EVENT_WARDEN_INTRO8:
                     Talk(YELL_RELEASE1);
                     me->InterruptNonMeleeSpells(false);
                     me->SetFacingTo(2.6f);
                     events.ScheduleEvent(EVENT_WARDEN_INTRO10, 4000);
                     break;
                 case EVENT_WARDEN_INTRO10:
                     me->CastSpell((Unit*)nullptr, SPELL_TARGET_BETA, false);
                     events.ScheduleEvent(EVENT_WARDEN_INTRO11, 2000);
                     break;
                 case EVENT_WARDEN_INTRO11:
                     Talk(YELL_RELEASE2A);
                     instance->SetData(DATA_WARDEN_2, IN_PROGRESS);
                     events.ScheduleEvent(EVENT_WARDEN_INTRO12, 2000);
                     break;
                 case EVENT_WARDEN_INTRO12:
                     me->SetFacingTo(M_PI * 1.5f);
                     me->CastSpell((Unit*)nullptr, SPELL_TARGET_OMEGA, false);
                     events.ScheduleEvent(EVENT_WARDEN_INTRO13, 6000);
                     break;
                 case EVENT_WARDEN_INTRO13:
                     me->SummonCreature(NPC_MILLHOUSE, 413.292f, -148.378f, 42.56f, 6.27f, TEMPSUMMON_MANUAL_DESPAWN);
                     events.ScheduleEvent(EVENT_WARDEN_INTRO14, 14000);
                     break;
                 case EVENT_WARDEN_INTRO14:
                     Talk(YELL_RELEASE2B);
                     me->InterruptNonMeleeSpells(false);
                     me->SetFacingTo(3.3f);
                     events.ScheduleEvent(EVENT_WARDEN_INTRO15, 5000);
                     break;
                 case EVENT_WARDEN_INTRO15:
                     me->CastSpell((Unit*)nullptr, SPELL_TARGET_DELTA, false);
                     events.ScheduleEvent(EVENT_WARDEN_INTRO16, 2000);
                     break;
                 case EVENT_WARDEN_INTRO16:
                     instance->SetData(DATA_WARDEN_3, IN_PROGRESS);
                     events.ScheduleEvent(EVENT_WARDEN_INTRO17, 2000);
                     break;
                 case EVENT_WARDEN_INTRO17:
                     me->SetFacingTo(M_PI * 1.5f);
                     me->CastSpell((Unit*)nullptr, SPELL_TARGET_OMEGA, false);
                     events.ScheduleEvent(EVENT_WARDEN_INTRO18, 6000);
                     break;
                 case EVENT_WARDEN_INTRO18:
                     me->SummonCreature(RAND(NPC_AKKIRIS, NPC_SULFURON), 420.179f, -174.396f, 42.58f, 0.02f, TEMPSUMMON_MANUAL_DESPAWN);
                     // Wait for kill
                     break;
                 case EVENT_WARDEN_INTRO19:
                     Talk(YELL_RELEASE3);
                     me->InterruptNonMeleeSpells(false);
                     me->SetFacingTo(6.05f);
                     events.ScheduleEvent(EVENT_WARDEN_INTRO20, 4000);
                     break;
                 case EVENT_WARDEN_INTRO20:
                     me->CastSpell((Unit*)nullptr, SPELL_TARGET_GAMMA, false);
                     events.ScheduleEvent(EVENT_WARDEN_INTRO21, 2000);
                     break;
                 case EVENT_WARDEN_INTRO21:
                     instance->SetData(DATA_WARDEN_4, IN_PROGRESS);
                     events.ScheduleEvent(EVENT_WARDEN_INTRO22, 2000);
                     break;
                 case EVENT_WARDEN_INTRO22:
                     me->SetFacingTo(M_PI * 1.5f);
                     me->CastSpell((Unit*)nullptr, SPELL_TARGET_OMEGA, false);
                     events.ScheduleEvent(EVENT_WARDEN_INTRO23, 6000);
                     break;
                 case EVENT_WARDEN_INTRO23:
                     me->SummonCreature(RAND(NPC_TW_DRAK, NPC_BL_DRAK), 471.795f, -174.58f, 42.58f, 3.06f, TEMPSUMMON_MANUAL_DESPAWN);
                     // Wait for kill
                     break;
                 case EVENT_WARDEN_INTRO24:
                     instance->SetData(DATA_WARDEN_5, IN_PROGRESS);
                     Talk(YELL_RELEASE4);
                     me->InterruptNonMeleeSpells(false);
                     events.ScheduleEvent(EVENT_WARDEN_INTRO25, 8000);
                     break;
                 case EVENT_WARDEN_INTRO25:
                     if (Creature* cr = me->SummonCreature(NPC_HARBINGER_SKYRISS, 445.763f, -191.639f, 44.64f, 1.60f, TEMPSUMMON_MANUAL_DESPAWN))
                     {
                         cr->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
                         cr->CastSpell(cr, SPELL_TELEPORT_VISUAL, true);
                     }
                     events.ScheduleEvent(EVENT_WARDEN_INTRO26, 1000);
                     break;
                 case EVENT_WARDEN_INTRO26:
                     if (Creature* creature = summons.GetCreatureWithEntry(NPC_HARBINGER_SKYRISS))
                         creature->AI()->Talk(SAY_HARBINGER_INTRO);
                     events.ScheduleEvent(EVENT_WARDEN_INTRO27, 23000);
                     break;
                 case EVENT_WARDEN_INTRO27:
                     Talk(YELL_WELCOME);
                     events.ScheduleEvent(EVENT_WARDEN_INTRO28, 5000);
                     break;
                 case EVENT_WARDEN_INTRO28:
                     instance->HandleGameObject(instance->GetGuidData(DATA_WARDENS_SHIELD), true);
                     if (Creature* creature = summons.GetCreatureWithEntry(NPC_HARBINGER_SKYRISS))
                         creature->CastSpell((Unit*)nullptr, SPELL_MIND_REND, false);
                     events.ScheduleEvent(EVENT_WARDEN_INTRO29, 4000);
                     break;
                 case EVENT_WARDEN_INTRO29:
                     events.Reset();
                     me->SetFlag(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_DEAD);
                     me->SetFlag(UNIT_FIELD_FLAGS_2, UNIT_FLAG2_FEIGN_DEATH);
                     if (Creature* creature = summons.GetCreatureWithEntry(NPC_HARBINGER_SKYRISS))
                     {
                         creature->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
                         if (Player* player = SelectTargetFromPlayerList(50.0f))
                             AttackStart(player);
                     }
                     break;
             }
         }
References AttackStart(), Unit::CastSpell(), DATA_WARDEN_1, DATA_WARDEN_2, DATA_WARDEN_3, DATA_WARDEN_4, DATA_WARDEN_5, DATA_WARDENS_SHIELD, CreatureAI::EnterEvadeMode(), EVENT_WARDEN_CHECK_PLAYERS, EVENT_WARDEN_INTRO1, EVENT_WARDEN_INTRO10, EVENT_WARDEN_INTRO11, EVENT_WARDEN_INTRO12, EVENT_WARDEN_INTRO13, EVENT_WARDEN_INTRO14, EVENT_WARDEN_INTRO15, EVENT_WARDEN_INTRO16, EVENT_WARDEN_INTRO17, EVENT_WARDEN_INTRO18, EVENT_WARDEN_INTRO19, EVENT_WARDEN_INTRO2, EVENT_WARDEN_INTRO20, EVENT_WARDEN_INTRO21, EVENT_WARDEN_INTRO22, EVENT_WARDEN_INTRO23, EVENT_WARDEN_INTRO24, EVENT_WARDEN_INTRO25, EVENT_WARDEN_INTRO26, EVENT_WARDEN_INTRO27, EVENT_WARDEN_INTRO28, EVENT_WARDEN_INTRO29, EVENT_WARDEN_INTRO3, EVENT_WARDEN_INTRO4, EVENT_WARDEN_INTRO5, EVENT_WARDEN_INTRO6, EVENT_WARDEN_INTRO7, EVENT_WARDEN_INTRO8, SummonList::GetCreatureWithEntry(), InstanceScript::GetGuidData(), InstanceScript::HandleGameObject(), IN_PROGRESS, BossAI::instance, Unit::InterruptNonMeleeSpells(), ScriptedAI::me, NPC_AKKIRIS, NPC_BL_DRAK, NPC_HARBINGER_SKYRISS, NPC_MILLHOUSE, NPC_PH_HUNTER, NPC_SULFURON, NPC_TRICKSTER, NPC_TW_DRAK, RAND(), SAY_HARBINGER_INTRO, ScriptedAI::SelectTargetFromPlayerList(), ZoneScript::SetData(), Unit::SetFacingTo(), Object::SetFlag(), SPELL_BUBBLE_VISUAL, SPELL_MIND_REND, SPELL_TARGET_ALPHA, SPELL_TARGET_BETA, SPELL_TARGET_DELTA, SPELL_TARGET_GAMMA, SPELL_TARGET_OMEGA, SPELL_TELEPORT_VISUAL, WorldObject::SummonCreature(), BossAI::summons, CreatureAI::Talk(), TEMPSUMMON_MANUAL_DESPAWN, UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_DEAD, UNIT_FIELD_FLAGS, UNIT_FIELD_FLAGS_2, UNIT_FLAG2_FEIGN_DEATH, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, YELL_INTRO1, YELL_INTRO2, YELL_RELEASE1, YELL_RELEASE2A, YELL_RELEASE2B, YELL_RELEASE3, YELL_RELEASE4, and YELL_WELCOME.
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/TempestKeep/arcatraz/arcatraz.cpp