Azerotcore-wotlk: Movement::MoveSplineInit Class Reference
Movement::MoveSplineInit Class Reference
#include <MoveSplineInit.h>
Public Member Functions
MoveSplineInit (Unit *m)
int32 Launch ()
void Stop ()
void SetParabolic (float amplitude, float start_time)
void SetAnimation (AnimType anim)
void SetFacing (float angle)
void SetFacing (Vector3 const &point)
void SetFacing (const Unit *target)
void MovebyPath (const PointsArray &path, int32 pointId=0)
void MoveTo (const Vector3 &destination, bool generatePath=false, bool forceDestination=false)
void MoveTo (float x, float y, float z, bool generatePath=false, bool forceDestination=false)
void SetFirstPointId (int32 pointId)
void SetSmooth ()
void SetFly ()
void SetWalk (bool enable)
void SetCyclic ()
void SetFall ()
void SetTransportEnter ()
void SetTransportExit ()
void SetOrientationInversed ()
void SetOrientationFixed (bool enable)
void SetVelocity (float velocity)
PointsArray & Path ()
void DisableTransportPathTransformations ()
Protected Attributes
MoveSplineInitArgs args
Unit * unit
Detailed Description
Definition at line 70 of file MoveSplineInit.h.
Constructor & Destructor Documentation
MoveSplineInit()
Movement::MoveSplineInit::MoveSplineInit (Unit * m) explicit
Definition at line 193 of file MoveSplineInit.cpp.
                                           : unit(m)
     {
         args.splineId = splineIdGen.NewId();
         args.TransformForTransport = unit->HasUnitMovementFlag(MOVEMENTFLAG_ONTRANSPORT) && unit->GetTransGUID();
         // mix existing state into new
         args.flags.walkmode = unit->m_movementInfo.HasMovementFlag(MOVEMENTFLAG_WALKING);
         args.flags.flying = unit->m_movementInfo.HasMovementFlag((MovementFlags)(MOVEMENTFLAG_CAN_FLY | MOVEMENTFLAG_DISABLE_GRAVITY));
     }
References args, Movement::MoveSplineInitArgs::flags, Movement::MoveSplineFlag::flying, Unit::GetTransGUID(), MovementInfo::HasMovementFlag(), Unit::HasUnitMovementFlag(), WorldObject::m_movementInfo, MOVEMENTFLAG_CAN_FLY, MOVEMENTFLAG_DISABLE_GRAVITY, MOVEMENTFLAG_ONTRANSPORT, MOVEMENTFLAG_WALKING, Movement::counter< T, limit >::NewId(), Movement::MoveSplineInitArgs::splineId, Movement::splineIdGen, Movement::MoveSplineInitArgs::TransformForTransport, unit, and Movement::MoveSplineFlag::walkmode.
Member Function Documentation
DisableTransportPathTransformations()
void Movement::MoveSplineInit::DisableTransportPathTransformations () inline
Definition at line 210 of file MoveSplineInit.h.
 { args.TransformForTransport = false; }
References args, and Movement::MoveSplineInitArgs::TransformForTransport.
Referenced by Vehicle::AddPassenger(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::DoAction(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::DoAction(), Unit::SetFacingTo(), and WaypointMovementGenerator< Creature >::StartMove().
Launch()
int32 Movement::MoveSplineInit::Launch ()
Definition at line 58 of file MoveSplineInit.cpp.
     {
         MoveSpline& move_spline = *unit->movespline;
         bool transport = unit->HasUnitMovementFlag(MOVEMENTFLAG_ONTRANSPORT) && unit->GetTransGUID();
         Location real_position;
         // there is a big chance that current position is unknown if current state is not finalized, need compute it
         // this also allows CalculatePath spline position and update map position in much greater intervals
         // Don't compute for transport movement if the unit is in a motion between two transports
         if (!move_spline.Finalized() && move_spline.onTransport == transport)
             real_position = move_spline.ComputePosition();
         else
         {
             Position const* pos;
             if (!transport)
                 pos = unit;
             else
                 pos = &unit->m_movementInfo.transport.pos;
             real_position.x = pos->GetPositionX();
             real_position.y = pos->GetPositionY();
             real_position.z = pos->GetPositionZ();
             real_position.orientation = unit->GetOrientation();
         }
         // should i do the things that user should do? - no.
         if (args.path.empty())
             return 0;
         // corrent first vertex
         args.path[0] = real_position;
         args.initialOrientation = real_position.orientation;
         move_spline.onTransport = transport;
         uint32 moveFlags = unit->m_movementInfo.GetMovementFlags();
         moveFlags |= MOVEMENTFLAG_SPLINE_ENABLED;
         if (!args.flags.orientationInversed)
         {
             moveFlags = (moveFlags & ~(MOVEMENTFLAG_BACKWARD)) | MOVEMENTFLAG_FORWARD;
         }
         else
         {
             moveFlags = (moveFlags & ~(MOVEMENTFLAG_FORWARD)) | MOVEMENTFLAG_BACKWARD;
         }
         if (moveFlags & MOVEMENTFLAG_ROOT)
             moveFlags &= ~MOVEMENTFLAG_MASK_MOVING;
         if (!args.HasVelocity)
         {
             // If spline is initialized with SetWalk method it only means we need to select
             // walk move speed for it but not add walk flag to unit
             uint32 moveFlagsForSpeed = moveFlags;
             if (args.flags.walkmode)
                 moveFlagsForSpeed |= MOVEMENTFLAG_WALKING;
             else
                 moveFlagsForSpeed &= ~MOVEMENTFLAG_WALKING;
             args.velocity = unit->GetSpeed(SelectSpeedType(moveFlagsForSpeed));
         }
         // limit the speed in the same way the client does
         args.velocity = std::min(args.velocity, args.flags.catmullrom || args.flags.flying ? 50.0f : std::max(28.0f, unit->GetSpeed(MOVE_RUN) * 4.0f));
         if (!args.Validate(unit))
             return 0;
         unit->m_movementInfo.SetMovementFlags(moveFlags);
         move_spline.Initialize(args);
         WorldPacket data(SMSG_MONSTER_MOVE, 64);
         data << unit->GetPackGUID();
         if (transport)
         {
             data.SetOpcode(SMSG_MONSTER_MOVE_TRANSPORT);
             data << unit->GetTransGUID().WriteAsPacked();
             data << int8(unit->GetTransSeat());
         }
         Movement::SplineBase::ControlArray* visualPoints = const_cast<Movement::SplineBase::ControlArray*>(move_spline._Spline().allocateVisualPoints());
         visualPoints->resize(move_spline._Spline().getPointCount());
         // Xinef: Apply hover in creature movement packet
         std::copy(move_spline._Spline().getPoints(false).begin(), move_spline._Spline().getPoints(false).end(), visualPoints->begin());
         PacketBuilder::WriteMonsterMove(move_spline, data);
         unit->SendMessageToSet(&data, true);
         return move_spline.Duration();
     }
References Movement::MoveSpline::_Spline(), Movement::SplineBase::allocateVisualPoints(), args, Movement::MoveSplineFlag::catmullrom, Movement::MoveSpline::ComputePosition(), detail::copy(), Movement::MoveSpline::Duration(), Movement::MoveSpline::Finalized(), Movement::MoveSplineInitArgs::flags, Movement::MoveSplineFlag::flying, MovementInfo::GetMovementFlags(), Position::GetOrientation(), Object::GetPackGUID(), Movement::SplineBase::getPointCount(), Movement::SplineBase::getPoints(), Unit::GetSpeed(), Unit::GetTransGUID(), WorldObject::GetTransSeat(), Unit::HasUnitMovementFlag(), Movement::MoveSplineInitArgs::HasVelocity, Movement::MoveSpline::Initialize(), Movement::MoveSplineInitArgs::initialOrientation, WorldObject::m_movementInfo, max, min, MOVE_RUN, MOVEMENTFLAG_BACKWARD, MOVEMENTFLAG_FORWARD, MOVEMENTFLAG_MASK_MOVING, MOVEMENTFLAG_ONTRANSPORT, MOVEMENTFLAG_ROOT, MOVEMENTFLAG_SPLINE_ENABLED, MOVEMENTFLAG_WALKING, Unit::movespline, Movement::MoveSpline::onTransport, Movement::Location::orientation, Movement::MoveSplineFlag::orientationInversed, Movement::MoveSplineInitArgs::path, pos(), MovementInfo::TransportInfo::pos, Movement::SelectSpeedType(), WorldObject::SendMessageToSet(), MovementInfo::SetMovementFlags(), SMSG_MONSTER_MOVE, SMSG_MONSTER_MOVE_TRANSPORT, MovementInfo::transport, unit, Movement::MoveSplineInitArgs::Validate(), Movement::MoveSplineInitArgs::velocity, Movement::MoveSplineFlag::walkmode, ObjectGuid::WriteAsPacked(), Movement::PacketBuilder::WriteMonsterMove(), G3D::Vector3::x, G3D::Vector3::y, and G3D::Vector3::z.
Referenced by Unit::_ExitVehicle(), RandomMovementGenerator< T >::_setRandomLocation(), HomeMovementGenerator< Creature >::_setTargetLocation(), Vehicle::AddPassenger(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::DoAction(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::DoAction(), boss_algalon_the_observer::boss_algalon_the_observerAI::DoAction(), EscortMovementGenerator< T >::DoInitialize(), FlightPathMovementGenerator::DoReset(), ConfusedMovementGenerator< T >::DoUpdate(), EscortMovementGenerator< T >::DoUpdate(), PointMovementGenerator< T >::DoUpdate(), ChaseMovementGenerator< T >::DoUpdate(), FollowMovementGenerator< T >::DoUpdate(), MoveDelayed::Execute(), boss_lieutenant_drake::boss_lieutenant_drakeAI::JustReachedHome(), npc_kalecgos_kj::npc_kalecgos_kjAI::JustSummoned(), npc_medivh_bm::npc_medivh_bmAI::JustSummoned(), Unit::MonsterMoveWithSpeed(), MotionMaster::MoveBackwards(), MotionMaster::MoveCircleTarget(), MotionMaster::MoveFall(), MotionMaster::MoveJump(), MotionMaster::MoveKnockbackFrom(), MotionMaster::MoveLand(), MotionMaster::MoveTakeoff(), Unit::SetFacingTo(), Unit::SetFacingToObject(), WaypointMovementGenerator< Creature >::StartMove(), Unit::StopMovingOnCurrentPos(), boss_kiljaeden::boss_kiljaedenAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), and npc_lord_arete::npc_lord_areteAI::UpdateAI().
MovebyPath()
void Movement::MoveSplineInit::MovebyPath (const PointsArray & path, int32 pointId = 0) inline
Definition at line 175 of file MoveSplineInit.h.
     {
         args.path_Idx_offset = path_offset;
         args.path.resize(controls.size());
         std::transform(controls.begin(), controls.end(), args.path.begin(), TransportPathTransform(unit, args.TransformForTransport));
     }
References args, Movement::MoveSplineInitArgs::path, Movement::MoveSplineInitArgs::path_Idx_offset, Movement::MoveSplineInitArgs::TransformForTransport, and unit.
Referenced by RandomMovementGenerator< T >::_setRandomLocation(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::DoAction(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::DoAction(), EscortMovementGenerator< T >::DoInitialize(), EscortMovementGenerator< T >::DoUpdate(), PointMovementGenerator< T >::DoUpdate(), ChaseMovementGenerator< T >::DoUpdate(), FollowMovementGenerator< T >::DoUpdate(), boss_lieutenant_drake::boss_lieutenant_drakeAI::JustReachedHome(), npc_medivh_bm::npc_medivh_bmAI::JustSummoned(), MoveTo(), and boss_kiljaeden::boss_kiljaedenAI::UpdateAI().
MoveTo() [1/2]
void Movement::MoveSplineInit::MoveTo (const Vector3 & destination, bool generatePath = false, bool forceDestination = false)
Definition at line 222 of file MoveSplineInit.cpp.
     {
         if (generatePath)
         {
             PathGenerator path(unit);
             bool result = path.CalculatePath(dest.x, dest.y, dest.z, forceDestination);
             if (result && !(path.GetPathType() & PATHFIND_NOPATH))
             {
                 MovebyPath(path.GetPath());
                 return;
             }
         }
         args.path_Idx_offset = 0;
         args.path.resize(2);
         TransportPathTransform transform(unit, args.TransformForTransport);
         args.path[1] = transform(dest);
     }
References args, PathGenerator::CalculatePath(), PathGenerator::GetPath(), PathGenerator::GetPathType(), MovebyPath(), Movement::MoveSplineInitArgs::path, Movement::MoveSplineInitArgs::path_Idx_offset, PATHFIND_NOPATH, Movement::MoveSplineInitArgs::TransformForTransport, unit, G3D::Vector3::x, G3D::Vector3::y, and G3D::Vector3::z.
Referenced by Unit::_ExitVehicle(), RandomMovementGenerator< T >::_setRandomLocation(), HomeMovementGenerator< Creature >::_setTargetLocation(), Vehicle::AddPassenger(), boss_algalon_the_observer::boss_algalon_the_observerAI::DoAction(), EscortMovementGenerator< T >::DoInitialize(), ConfusedMovementGenerator< T >::DoUpdate(), EscortMovementGenerator< T >::DoUpdate(), PointMovementGenerator< T >::DoUpdate(), MoveDelayed::Execute(), npc_kalecgos_kj::npc_kalecgos_kjAI::JustSummoned(), Unit::MonsterMoveWithSpeed(), MotionMaster::MoveBackwards(), MotionMaster::MoveCircleTarget(), MotionMaster::MoveFall(), MotionMaster::MoveJump(), MotionMaster::MoveKnockbackFrom(), MotionMaster::MoveLand(), MotionMaster::MoveTakeoff(), MoveTo(), Unit::SetFacingTo(), Unit::SetFacingToObject(), WaypointMovementGenerator< Creature >::StartMove(), Unit::StopMovingOnCurrentPos(), boss_malygos::boss_malygosAI::UpdateAI(), and npc_lord_arete::npc_lord_areteAI::UpdateAI().
MoveTo() [2/2]
void Movement::MoveSplineInit::MoveTo (float x, float y, float z, bool generatePath = false, bool forceDestination = false) inline
Definition at line 182 of file MoveSplineInit.h.
     {
         MoveTo(G3D::Vector3(x, y, z), generatePath, forceDestination);
     }
References MoveTo(), G3D::x, G3D::y, and G3D::z.
Path()
PointsArray& Movement::MoveSplineInit::Path () inline
Definition at line 154 of file MoveSplineInit.h.
 { return args.path; }
References args, and Movement::MoveSplineInitArgs::path.
Referenced by FlightPathMovementGenerator::DoReset().
SetAnimation()
void Movement::MoveSplineInit::SetAnimation (AnimType anim) inline
Definition at line 194 of file MoveSplineInit.h.
     {
         args.time_perc = 0.f;
         args.flags.EnableAnimation((uint8)anim);
     }
References args, Movement::MoveSplineFlag::EnableAnimation(), Movement::MoveSplineInitArgs::flags, and Movement::MoveSplineInitArgs::time_perc.
Referenced by MotionMaster::MoveLand(), MotionMaster::MoveTakeoff(), and WaypointMovementGenerator< Creature >::StartMove().
SetCyclic()
void Movement::MoveSplineInit::SetCyclic () inline
Definition at line 167 of file MoveSplineInit.h.
 { args.flags.cyclic = true; }
References args, Movement::MoveSplineFlag::cyclic, and Movement::MoveSplineInitArgs::flags.
Referenced by boss_lieutenant_drake::boss_lieutenant_drakeAI::JustReachedHome(), npc_medivh_bm::npc_medivh_bmAI::JustSummoned(), and boss_kiljaeden::boss_kiljaedenAI::UpdateAI().
SetFacing() [1/3]
void Movement::MoveSplineInit::SetFacing (const Unit * target)
Definition at line 202 of file MoveSplineInit.cpp.
     {
         args.flags.EnableFacingTarget();
         args.facing.target = target->GetGUID().GetRawValue();
     }
References args, Movement::MoveSplineFlag::EnableFacingTarget(), Movement::MoveSplineInitArgs::facing, Movement::MoveSplineInitArgs::flags, Object::GetGUID(), ObjectGuid::GetRawValue(), and Movement::FacingInfo::target.
SetFacing() [2/3]
void Movement::MoveSplineInit::SetFacing (float angle)
Definition at line 208 of file MoveSplineInit.cpp.
     {
         if (args.TransformForTransport)
         {
             if (Unit* vehicle = unit->GetVehicleBase())
                 angle -= vehicle->GetOrientation();
             else if (Transport* transport = unit->GetTransport())
                 angle -= transport->GetOrientation();
         }
         args.facing.angle = G3D::wrap(angle, 0.f, (float)G3D::twoPi());
         args.flags.EnableFacingAngle();
     }
References Movement::FacingInfo::angle, args, Movement::MoveSplineFlag::EnableFacingAngle(), Movement::MoveSplineInitArgs::facing, Movement::MoveSplineInitArgs::flags, WorldObject::GetTransport(), Unit::GetVehicleBase(), Movement::MoveSplineInitArgs::TransformForTransport, G3D::twoPi(), unit, and G3D::wrap().
Referenced by Unit::_ExitVehicle(), HomeMovementGenerator< Creature >::_setTargetLocation(), Vehicle::AddPassenger(), PointMovementGenerator< T >::DoUpdate(), ChaseMovementGenerator< T >::DoUpdate(), MoveDelayed::Execute(), npc_kalecgos_kj::npc_kalecgos_kjAI::JustSummoned(), MotionMaster::MoveBackwards(), MotionMaster::MoveCircleTarget(), MotionMaster::MoveJump(), Unit::SetFacingTo(), Unit::SetFacingToObject(), WaypointMovementGenerator< Creature >::StartMove(), Unit::StopMovingOnCurrentPos(), and boss_malygos::boss_malygosAI::UpdateAI().
SetFacing() [3/3]
void Movement::MoveSplineInit::SetFacing (Vector3 const & point) inline
Definition at line 200 of file MoveSplineInit.h.
     {
         TransportPathTransform transform(unit, args.TransformForTransport);
         Vector3 finalSpot = transform(spot);
         args.facing.f.x = finalSpot.x;
         args.facing.f.y = finalSpot.y;
         args.facing.f.z = finalSpot.z;
         args.flags.EnableFacingPoint();
     }
References args, Movement::MoveSplineFlag::EnableFacingPoint(), Movement::FacingInfo::f, Movement::MoveSplineInitArgs::facing, Movement::MoveSplineInitArgs::flags, Movement::MoveSplineInitArgs::TransformForTransport, unit, G3D::Vector3::x, Movement::FacingInfo::x, G3D::Vector3::y, Movement::FacingInfo::y, G3D::Vector3::z, and Movement::FacingInfo::z.
SetFall()
void Movement::MoveSplineInit::SetFall () inline
Definition at line 168 of file MoveSplineInit.h.
 { args.flags.EnableFalling(); }
References args, Movement::MoveSplineFlag::EnableFalling(), and Movement::MoveSplineInitArgs::flags.
Referenced by MotionMaster::MoveFall().
SetFirstPointId()
void Movement::MoveSplineInit::SetFirstPointId (int32 pointId) inline
Definition at line 116 of file MoveSplineInit.h.
 { args.path_Idx_offset = pointId; }
References args, and Movement::MoveSplineInitArgs::path_Idx_offset.
Referenced by FlightPathMovementGenerator::DoReset().
SetFly()
void Movement::MoveSplineInit::SetFly () inline
Definition at line 164 of file MoveSplineInit.h.
 { args.flags.EnableFlying(); }
References args, Movement::MoveSplineFlag::EnableFlying(), and Movement::MoveSplineInitArgs::flags.
Referenced by FlightPathMovementGenerator::DoReset().
SetOrientationFixed()
void Movement::MoveSplineInit::SetOrientationFixed (bool enable) inline
Definition at line 173 of file MoveSplineInit.h.
 { args.flags.orientationFixed = enable; }
References args, Movement::MoveSplineInitArgs::flags, and Movement::MoveSplineFlag::orientationFixed.
Referenced by boss_algalon_the_observer::boss_algalon_the_observerAI::DoAction(), and MotionMaster::MoveKnockbackFrom().
SetOrientationInversed()
void Movement::MoveSplineInit::SetOrientationInversed () inline
Definition at line 170 of file MoveSplineInit.h.
 { args.flags.orientationInversed = true;}
References args, Movement::MoveSplineInitArgs::flags, and Movement::MoveSplineFlag::orientationInversed.
Referenced by MotionMaster::MoveBackwards().
SetParabolic()
void Movement::MoveSplineInit::SetParabolic (float amplitude, float start_time) inline
Definition at line 187 of file MoveSplineInit.h.
     {
         args.time_perc = time_shift;
         args.parabolic_amplitude = amplitude;
         args.flags.EnableParabolic();
     }
References args, Movement::MoveSplineFlag::EnableParabolic(), Movement::MoveSplineInitArgs::flags, Movement::MoveSplineInitArgs::parabolic_amplitude, and Movement::MoveSplineInitArgs::time_perc.
Referenced by MotionMaster::MoveJump(), and MotionMaster::MoveKnockbackFrom().
SetSmooth()
void Movement::MoveSplineInit::SetSmooth () inline
Definition at line 166 of file MoveSplineInit.h.
 { args.flags.EnableCatmullRom(); }
References args, Movement::MoveSplineFlag::EnableCatmullRom(), and Movement::MoveSplineInitArgs::flags.
SetTransportEnter()
void Movement::MoveSplineInit::SetTransportEnter () inline
Definition at line 171 of file MoveSplineInit.h.
 { args.flags.EnableTransportEnter(); }
References args, Movement::MoveSplineFlag::EnableTransportEnter(), and Movement::MoveSplineInitArgs::flags.
Referenced by Vehicle::AddPassenger().
SetTransportExit()
void Movement::MoveSplineInit::SetTransportExit () inline
Definition at line 172 of file MoveSplineInit.h.
 { args.flags.EnableTransportExit(); }
References args, Movement::MoveSplineFlag::EnableTransportExit(), and Movement::MoveSplineInitArgs::flags.
Referenced by Unit::_ExitVehicle(), and boss_malygos::boss_malygosAI::UpdateAI().
SetVelocity()
void Movement::MoveSplineInit::SetVelocity (float velocity) inline
Definition at line 169 of file MoveSplineInit.h.
 { args.velocity = vel; args.HasVelocity = true; }
References args, Movement::MoveSplineInitArgs::HasVelocity, and Movement::MoveSplineInitArgs::velocity.
Referenced by FlightPathMovementGenerator::DoReset(), PointMovementGenerator< T >::DoUpdate(), FollowMovementGenerator< T >::DoUpdate(), Unit::MonsterMoveWithSpeed(), MotionMaster::MoveJump(), MotionMaster::MoveKnockbackFrom(), MotionMaster::MoveLand(), MotionMaster::MoveTakeoff(), and npc_lord_arete::npc_lord_areteAI::UpdateAI().
SetWalk()
void Movement::MoveSplineInit::SetWalk (bool enable) inline
Definition at line 165 of file MoveSplineInit.h.
 { args.flags.walkmode = enable; }
References args, Movement::MoveSplineInitArgs::flags, and Movement::MoveSplineFlag::walkmode.
Referenced by RandomMovementGenerator< T >::_setRandomLocation(), HomeMovementGenerator< Creature >::_setTargetLocation(), ChaseMovementGenerator< T >::DoUpdate(), FollowMovementGenerator< T >::DoUpdate(), MotionMaster::MoveCircleTarget(), and WaypointMovementGenerator< Creature >::StartMove().
Stop()
void Movement::MoveSplineInit::Stop ()
Definition at line 149 of file MoveSplineInit.cpp.
     {
         MoveSpline& move_spline = *unit->movespline;
         // No need to stop if we are not moving
         if (move_spline.Finalized())
             return;
         bool transport = unit->HasUnitMovementFlag(MOVEMENTFLAG_ONTRANSPORT) && unit->GetTransGUID();
         Location loc;
         if (move_spline.onTransport == transport)
             loc = move_spline.ComputePosition();
         else
         {
             Position const* pos;
             if (!transport)
                 pos = unit;
             else
                 pos = &unit->m_movementInfo.transport.pos;
             loc.x = pos->GetPositionX();
             loc.y = pos->GetPositionY();
             loc.z = pos->GetPositionZ();
             loc.orientation = unit->GetOrientation();
         }
         args.flags = MoveSplineFlag::Done;
         unit->m_movementInfo.RemoveMovementFlag(MOVEMENTFLAG_FORWARD | MOVEMENTFLAG_BACKWARD | MOVEMENTFLAG_SPLINE_ENABLED);
         move_spline.onTransport = transport;
         move_spline.Initialize(args);
         WorldPacket data(SMSG_MONSTER_MOVE, 64);
         data << unit->GetPackGUID();
         if (transport)
         {
             data.SetOpcode(SMSG_MONSTER_MOVE_TRANSPORT);
             data << unit->GetTransGUID().WriteAsPacked();
             data << int8(unit->GetTransSeat());
         }
         PacketBuilder::WriteStopMovement(loc, args.splineId, data);
         unit->SendMessageToSet(&data, true);
     }
References args, Movement::MoveSpline::ComputePosition(), Movement::MoveSplineFlag::Done, Movement::MoveSpline::Finalized(), Movement::MoveSplineInitArgs::flags, Position::GetOrientation(), Object::GetPackGUID(), Unit::GetTransGUID(), WorldObject::GetTransSeat(), Unit::HasUnitMovementFlag(), Movement::MoveSpline::Initialize(), WorldObject::m_movementInfo, MOVEMENTFLAG_BACKWARD, MOVEMENTFLAG_FORWARD, MOVEMENTFLAG_ONTRANSPORT, MOVEMENTFLAG_SPLINE_ENABLED, Unit::movespline, Movement::MoveSpline::onTransport, Movement::Location::orientation, pos(), MovementInfo::TransportInfo::pos, MovementInfo::RemoveMovementFlag(), WorldObject::SendMessageToSet(), SMSG_MONSTER_MOVE, SMSG_MONSTER_MOVE_TRANSPORT, Movement::MoveSplineInitArgs::splineId, MovementInfo::transport, unit, ObjectGuid::WriteAsPacked(), Movement::PacketBuilder::WriteStopMovement(), G3D::Vector3::x, G3D::Vector3::y, and G3D::Vector3::z.
Referenced by Unit::StopMoving().
Member Data Documentation
args
MoveSplineInitArgs Movement::MoveSplineInit::args protected
Definition at line 160 of file MoveSplineInit.h.
Referenced by DisableTransportPathTransformations(), Launch(), MovebyPath(), MoveSplineInit(), MoveTo(), Path(), SetAnimation(), SetCyclic(), SetFacing(), SetFall(), SetFirstPointId(), SetFly(), SetOrientationFixed(), SetOrientationInversed(), SetParabolic(), SetSmooth(), SetTransportEnter(), SetTransportExit(), SetVelocity(), SetWalk(), and Stop().
unit
Unit* Movement::MoveSplineInit::unit protected
Definition at line 161 of file MoveSplineInit.h.
Referenced by Launch(), MovebyPath(), MoveSplineInit(), MoveTo(), SetFacing(), and Stop().
The documentation for this class was generated from the following files:
src/server/game/Movement/Spline/MoveSplineInit.h
src/server/game/Movement/Spline/MoveSplineInit.cpp