Azerotcore-wotlk: CustomSpellValues Class Reference
CustomSpellValues Class Reference
#include <Unit.h>
Public Member Functions
void AddSpellMod (SpellValueMod mod, int32 value)
Detailed Description
Definition at line 133 of file Unit.h.
Member Function Documentation
AddSpellMod()
void CustomSpellValues::AddSpellMod (SpellValueMod mod, int32 value) inline
Definition at line 136 of file Unit.h.
     {
         push_back(std::make_pair(mod, value));
     }
Referenced by spell_the_lich_king_necrotic_plague_jump::spell_the_lich_king_necrotic_plague_AuraScript::AfterDispel(), spell_igb_incinerating_blast::spell_igb_incinerating_blast_SpellScript::CalculateDamage(), Unit::CastCustomSpell(), Spell::EffectForceCast(), Spell::EffectTriggerMissileSpell(), Spell::EffectTriggerSpell(), AuraEffect::HandlePeriodicTriggerSpellWithValueAuraTick(), spell_rog_blade_flurry::HandleProc(), spell_warr_improved_spell_reflection::OnProc(), spell_the_lich_king_necrotic_plague::spell_the_lich_king_necrotic_plague_AuraScript::OnRemove(), spell_the_lich_king_necrotic_plague_jump::spell_the_lich_king_necrotic_plague_AuraScript::OnRemove(), and spell_serpentshrine_cavern_infection::spell_serpentshrine_cavern_infection_AuraScript::PrepareAuraScript().
The documentation for this class was generated from the following file:
src/server/game/Entities/Unit/Unit.h