Azerotcore-wotlk: deps/recastnavigation/Recast/Source/RecastAlloc.cpp File Reference
RecastAlloc.cpp File Reference
#include <stdlib.h>
#include <string.h>
#include "RecastAlloc.h"
#include "RecastAssert.h"
Functions
static void * rcAllocDefault (size_t size, rcAllocHint)
static void rcFreeDefault (void *ptr)
void rcAllocSetCustom (rcAllocFunc *allocFunc, rcFreeFunc *freeFunc)
void * rcAlloc (size_t size, rcAllocHint hint)
void rcFree (void *ptr)
Variables
static rcAllocFunc * sRecastAllocFunc = rcAllocDefault
static rcFreeFunc * sRecastFreeFunc = rcFreeDefault
Function Documentation
rcAlloc()
void* rcAlloc (size_t size, rcAllocHint hint)
See also
rcAllocSetCustom
Definition at line 45 of file RecastAlloc.cpp.
 {
     return sRecastAllocFunc(size, hint);
 }
References sRecastAllocFunc.
Referenced by rcVectorBase< T, H >::allocate_and_copy(), allocSpan(), buildMeshAdjacency(), canRemoveVertex(), mergeContours(), mergeRegionHoles(), rcAllocPolyMeshDetail(), rcBuildCompactHeightfield(), rcBuildContours(), rcBuildDistanceField(), rcBuildHeightfieldLayers(), rcBuildLayerRegions(), rcBuildPolyMesh(), rcBuildPolyMeshDetail(), rcBuildRegions(), rcBuildRegionsMonotone(), rcCopyPolyMesh(), rcCreateHeightfield(), rcErodeWalkableArea(), rcMedianFilterWalkableArea(), rcMergePolyMeshDetails(), rcMergePolyMeshes(), anonymous_namespace{Recast.cpp}::rcNew(), and removeVertex().
rcAllocDefault()
static void* rcAllocDefault (size_t size, rcAllocHint) static
Definition at line 24 of file RecastAlloc.cpp.
 {
     return malloc(size);
 }
Referenced by rcAllocSetCustom().
rcAllocSetCustom()
void rcAllocSetCustom (rcAllocFunc * allocFunc, rcFreeFunc * freeFunc)
See also
rcAlloc, rcFree
Definition at line 38 of file RecastAlloc.cpp.
 {
     sRecastAllocFunc = allocFunc ? allocFunc : rcAllocDefault;
     sRecastFreeFunc = freeFunc ? freeFunc : rcFreeDefault;
 }
References rcAllocDefault(), rcFreeDefault(), sRecastAllocFunc, and sRecastFreeFunc.
rcFree()
void rcFree (void * ptr)
Warning
This function leaves the value of ptr unchanged. So it still points to the same (now invalid) location, and not to null.
See also
rcAllocSetCustom
Definition at line 56 of file RecastAlloc.cpp.
 {
     if (ptr)
         sRecastFreeFunc(ptr);
 }
References ptr(), and sRecastFreeFunc.
Referenced by buildMeshAdjacency(), mergeContours(), rcVectorBase< T, H >::push_back(), rcBuildContours(), rcBuildDistanceField(), rcBuildPolyMeshDetail(), anonymous_namespace{Recast.cpp}::rcDelete(), rcErodeWalkableArea(), rcFreePolyMeshDetail(), rcMedianFilterWalkableArea(), rcVectorBase< T, H >::reserve(), rcVectorBase< T, H >::resize_impl(), rcCompactHeightfield::~rcCompactHeightfield(), rcContourSet::~rcContourSet(), rcHeightfield::~rcHeightfield(), rcHeightfieldLayerSet::~rcHeightfieldLayerSet(), rcHeightPatch::~rcHeightPatch(), rcPolyMesh::~rcPolyMesh(), rcScopedDelete< T >::~rcScopedDelete(), and rcVectorBase< T, H >::~rcVectorBase().
rcFreeDefault()
static void rcFreeDefault (void * ptr) static
Definition at line 29 of file RecastAlloc.cpp.
 {
     free(ptr);
 }
References ptr().
Referenced by rcAllocSetCustom().
Variable Documentation
sRecastAllocFunc
rcAllocFunc* sRecastAllocFunc = rcAllocDefault static
Definition at line 34 of file RecastAlloc.cpp.
Referenced by rcAlloc(), and rcAllocSetCustom().
sRecastFreeFunc
rcFreeFunc* sRecastFreeFunc = rcFreeDefault static
Definition at line 35 of file RecastAlloc.cpp.
Referenced by rcAllocSetCustom(), and rcFree().