Azerotcore-wotlk: detail::fallback_formatter< T, Char, enable_if_t< is_streamable< T, Char >::value > > Struct Template Reference
detail::fallback_formatter< T, Char, enable_if_t< is_streamable< T, Char >::value > > Struct Template Reference
#include <ostream.h>
Public Member Functions
FMT_CONSTEXPR auto parse (basic_format_parse_context< Char > &ctx) -> decltype(ctx.begin())
template<typename ParseCtx , FMT_ENABLE_IF(std::is_same< ParseCtx, basic_printf_parse_context< Char >>::value) >
auto parse (ParseCtx &ctx) -> decltype(ctx.begin())
template<typename OutputIt >
auto format (const T &value, basic_format_context< OutputIt, Char > &ctx) -> OutputIt
template<typename OutputIt >
auto format (const T &value, basic_printf_context< OutputIt, Char > &ctx) -> OutputIt
Additional Inherited Members
Private Member Functions inherited from formatter< basic_string_view< Char >, Char >
formatter ()=delete
Detailed Description
template<typename T, typename Char>
struct detail::fallback_formatter< T, Char, enable_if_t< is_streamable< T, Char >::value > >
Definition at line 123 of file ostream.h.
Member Function Documentation
format() [1/2]
template<typename T , typename Char > template<typename OutputIt > auto detail::fallback_formatter< T, Char, enable_if_t< is_streamable< T, Char >::value > >::format (const T & value, basic_format_context< OutputIt, Char > & ctx) -> OutputIt inline
Definition at line 137 of file ostream.h.
                   {
     basic_memory_buffer<Char> buffer;
     format_value(buffer, value, ctx.locale());
     basic_string_view<Char> str(buffer.data(), buffer.size());
     return formatter<basic_string_view<Char>, Char>::format(str, ctx);
   }
References buffer, format(), and detail::format_value().
format() [2/2]
template<typename T , typename Char > template<typename OutputIt > auto detail::fallback_formatter< T, Char, enable_if_t< is_streamable< T, Char >::value > >::format (const T & value, basic_printf_context< OutputIt, Char > & ctx) -> OutputIt inline
Definition at line 145 of file ostream.h.
                   {
     basic_memory_buffer<Char> buffer;
     format_value(buffer, value, ctx.locale());
     return std::copy(buffer.begin(), buffer.end(), ctx.out());
   }
References buffer, detail::copy(), and detail::format_value().
parse() [1/2]
template<typename T , typename Char > FMT_CONSTEXPR auto detail::fallback_formatter< T, Char, enable_if_t< is_streamable< T, Char >::value > >::parse (basic_format_parse_context< Char > & ctx) -> decltype(ctx.begin()) inline
Definition at line 125 of file ostream.h.
{
     return formatter<basic_string_view<Char>, Char>::parse(ctx);
   }
parse() [2/2]
template<typename T , typename Char > template<typename ParseCtx , FMT_ENABLE_IF(std::is_same< ParseCtx, basic_printf_parse_context< Char >>::value) > auto detail::fallback_formatter< T, Char, enable_if_t< is_streamable< T, Char >::value > >::parse (ParseCtx & ctx) -> decltype(ctx.begin()) inline
Definition at line 132 of file ostream.h.
{
     return ctx.begin();
   }
The documentation for this struct was generated from the following file:
deps/fmt/include/fmt/ostream.h