Azerotcore-wotlk: FileLoader Class Reference
FileLoader Class Reference
#include <loadlib.h>
Public Member Functions
virtual bool prepareLoadedData ()
uint8 * GetData ()
uint32 GetDataSize ()
FileLoader ()
~FileLoader ()
bool loadFile (std::string const &filename, bool log=true)
virtual void free ()
virtual bool prepareLoadedData ()
uint8 * GetData ()
uint32 GetDataSize ()
FileLoader ()
~FileLoader ()
bool loadFile (std::string const &filename, bool log=true)
virtual void free ()
Public Attributes
file_MVER * version
Private Attributes
uint8 * data
uint32 data_size
Detailed Description
Definition at line 71 of file loadlib.h.
Constructor & Destructor Documentation
FileLoader() [1/2]
FileLoader::FileLoader ()
Definition at line 28 of file loadlib.cpp.
 {
     data = nullptr;
     data_size = 0;
     version = nullptr;
 }
References data_size, and version.
~FileLoader() [1/2]
FileLoader::~FileLoader ()
Definition at line 35 of file loadlib.cpp.
 {
     free();
 }
References free().
FileLoader() [2/2]
FileLoader::FileLoader ()
~FileLoader() [2/2]
FileLoader::~FileLoader ()
Member Function Documentation
free() [1/2]
void FileLoader::free () virtual
Reimplemented in WDT_file, and ADT_file.
Definition at line 76 of file loadlib.cpp.
 {
     delete[] data;
     data = nullptr;
     data_size = 0;
     version = nullptr;
 }
References data, data_size, and version.
Referenced by ADT_file::free(), WDT_file::free(), loadFile(), and ~FileLoader().
free() [2/2]
virtual void FileLoader::free () virtual
Reimplemented in WDT_file, and ADT_file.
GetData() [1/2]
uint8* FileLoader::GetData () inline
Definition at line 77 of file loadlib.h.
 {return data;}
References data.
Referenced by ADT_file::prepareLoadedData().
GetData() [2/2]
uint8* FileLoader::GetData () inline
Definition at line 71 of file loadlib.h.
 {return data;}
References data.
GetDataSize() [1/2]
uint32 FileLoader::GetDataSize () inline
Definition at line 78 of file loadlib.h.
 {return data_size;}
References data_size.
GetDataSize() [2/2]
uint32 FileLoader::GetDataSize () inline
Definition at line 72 of file loadlib.h.
 {return data_size;}
References data_size.
loadFile() [1/2]
bool FileLoader::loadFile (std::string const & filename, bool log = true)
Definition at line 40 of file loadlib.cpp.
 {
     free();
     MPQFile mf(fileName.c_str());
     if (mf.isEof())
     {
         if (log)
             printf("No such file %s\n", fileName.c_str());
         return false;
     }
     data_size = mf.getSize();
     data = new uint8 [data_size];
     mf.read(data, data_size);
     mf.close();
     if (prepareLoadedData())
         return true;
     printf("Error loading %s", fileName.c_str());
     mf.close();
     free();
     return false;
 }
References MPQFile::close(), data_size, free(), MPQFile::getSize(), MPQFile::isEof(), G3D::log(), prepareLoadedData(), printf(), and MPQFile::read().
Referenced by ConvertADT(), and ExtractMapsFromMpq().
loadFile() [2/2]
bool FileLoader::loadFile (std::string const & filename, bool log = true)
prepareLoadedData() [1/2]
bool FileLoader::prepareLoadedData () virtual
Reimplemented in WDT_file, and ADT_file.
Definition at line 65 of file loadlib.cpp.
 {
     // Check version
     version = (file_MVER*) data;
     if (version->fcc != MverMagic.fcc)
         return false;
     if (version->ver != FILE_FORMAT_VERSION)
         return false;
     return true;
 }
References u_map_fcc::fcc, file_MVER::fcc, FILE_FORMAT_VERSION, MverMagic, file_MVER::ver, and version.
Referenced by loadFile(), ADT_file::prepareLoadedData(), and WDT_file::prepareLoadedData().
prepareLoadedData() [2/2]
virtual bool FileLoader::prepareLoadedData () virtual
Reimplemented in WDT_file, and ADT_file.
Member Data Documentation
data
uint8 * FileLoader::data private
Definition at line 73 of file loadlib.h.
Referenced by free(), and GetData().
data_size
uint32 FileLoader::data_size private
Definition at line 74 of file loadlib.h.
Referenced by FileLoader(), free(), GetDataSize(), and loadFile().
version
file_MVER * FileLoader::version
Definition at line 80 of file loadlib.h.
Referenced by FileLoader(), free(), prepareLoadedData(), ADT_file::prepareLoadedData(), and WDT_file::prepareLoadedData().
The documentation for this class was generated from the following files:
src/tools/map_extractor/loadlib/loadlib.h
src/tools/map_extractor/loadlib.cpp