Azerotcore-wotlk: npc_pet_gen_imp_in_a_bottle Struct Reference
npc_pet_gen_imp_in_a_bottle Struct Reference
Public Member Functions
npc_pet_gen_imp_in_a_bottle (Creature *c)
void InitializeAI () override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void Reset ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
WorldPacket _data
uint32 _talkTimer
ObjectGuid _ownerGUID
bool _hasParty
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 561 of file pet_generic.cpp.
Constructor & Destructor Documentation
npc_pet_gen_imp_in_a_bottle()
npc_pet_gen_imp_in_a_bottle::npc_pet_gen_imp_in_a_bottle (Creature * c) inline
Definition at line 563 of file pet_generic.cpp.
                                              : NullCreatureAI(c)
     {
         _talkTimer = 0;
         _ownerGUID.Clear();
         _hasParty = false;
     }
References _hasParty, _ownerGUID, _talkTimer, and ObjectGuid::Clear().
Member Function Documentation
InitializeAI()
void npc_pet_gen_imp_in_a_bottle::InitializeAI () inline override virtual
Reimplemented from UnitAI.
Definition at line 575 of file pet_generic.cpp.
     {
         NullCreatureAI::InitializeAI();
         if (TempSummon* summon = me->ToTempSummon())
             if (Unit* owner = summon->GetSummonerUnit())
                 if (owner->GetTypeId() == TYPEID_PLAYER)
                 {
                     _ownerGUID = owner->GetGUID();
                     if (owner->ToPlayer()->GetGroup())
                     {
                         _hasParty = true;
                         std::string const& text = sCreatureTextMgr->GetLocalizedChatString(me->GetEntry(), 0, 0 /*text group*/, urand(0, 60) /*text id*/, LOCALE_enUS);
                         _data.Initialize(SMSG_MESSAGECHAT, 200);                // guess size
                         _data << uint8(CHAT_MSG_MONSTER_PARTY);
                         _data << uint32(LANG_UNIVERSAL);
                         _data << me->GetGUID();
                         _data << uint32(0);
                         _data << uint32(me->GetName().size() + 1);
                         _data << me->GetName();
                         _data << uint64(0);
                         _data << uint32(text.size() + 1);
                         _data << text.c_str();
                         _data << uint8(0);
                     }
                 }
     }
References _data, _hasParty, _ownerGUID, CHAT_MSG_MONSTER_PARTY, Object::GetEntry(), Object::GetGUID(), WorldObject::GetName(), WorldPacket::Initialize(), UnitAI::InitializeAI(), LANG_UNIVERSAL, LOCALE_enUS, CreatureAI::me, sCreatureTextMgr, SMSG_MESSAGECHAT, Unit::ToTempSummon(), TYPEID_PLAYER, and urand().
UpdateAI()
void npc_pet_gen_imp_in_a_bottle::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 604 of file pet_generic.cpp.
     {
         _talkTimer += diff;
         if (_talkTimer >= 5000)
         {
             _talkTimer = 0;
             me->DespawnOrUnsummon(1);
             if (!_hasParty)
                 Talk(0, ObjectAccessor::GetPlayer(*me, _ownerGUID));
             else if (Player* player = ObjectAccessor::GetPlayer(*me, _ownerGUID))
             {
                 uint8 limit = 0;
                 if (player->GetGroup())
                     for (GroupReference* itr = player->GetGroup()->GetFirstMember(); itr != nullptr && limit < 4; itr = itr->next(), ++limit)
                         if (Player* groupPlayer = itr->GetSource())
                             if (groupPlayer != player)
                                 groupPlayer->GetSession()->SendPacket(&_data);
                 player->GetSession()->SendPacket(&_data);
             }
         }
     }
References _data, _hasParty, _ownerGUID, _talkTimer, Creature::DespawnOrUnsummon(), diff(), ObjectAccessor::GetPlayer(), CreatureAI::me, next(), and CreatureAI::Talk().
Member Data Documentation
_data
WorldPacket npc_pet_gen_imp_in_a_bottle::_data
Definition at line 570 of file pet_generic.cpp.
Referenced by InitializeAI(), and UpdateAI().
_hasParty
bool npc_pet_gen_imp_in_a_bottle::_hasParty
Definition at line 573 of file pet_generic.cpp.
Referenced by InitializeAI(), npc_pet_gen_imp_in_a_bottle(), and UpdateAI().
_ownerGUID
ObjectGuid npc_pet_gen_imp_in_a_bottle::_ownerGUID
Definition at line 572 of file pet_generic.cpp.
Referenced by InitializeAI(), npc_pet_gen_imp_in_a_bottle(), and UpdateAI().
_talkTimer
uint32 npc_pet_gen_imp_in_a_bottle::_talkTimer
Definition at line 571 of file pet_generic.cpp.
Referenced by npc_pet_gen_imp_in_a_bottle(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Pet/pet_generic.cpp