Azerotcore-wotlk: src/server/game/Skills/SkillDiscovery.cpp File Reference
SkillDiscovery.cpp File Reference
#include "DatabaseEnv.h"
#include "Log.h"
#include "Player.h"
#include "SkillDiscovery.h"
#include "SpellInfo.h"
#include "SpellMgr.h"
#include "Util.h"
#include "World.h"
#include <map>
Classes
struct SkillDiscoveryEntry
Typedefs
typedef std::list< SkillDiscoveryEntry > SkillDiscoveryList
typedef std::unordered_map< int32, SkillDiscoveryList > SkillDiscoveryMap
Functions
void LoadSkillDiscoveryTable ()
uint32 GetExplicitDiscoverySpell (uint32 spellId, Player *player)
bool HasDiscoveredAllSpells (uint32 spellId, Player *player)
uint32 GetSkillDiscoverySpell (uint32 skillId, uint32 spellId, Player *player)
Variables
static SkillDiscoveryMap SkillDiscoveryStore
Typedef Documentation
SkillDiscoveryList
typedef std::list<SkillDiscoveryEntry> SkillDiscoveryList
Definition at line 41 of file SkillDiscovery.cpp.
SkillDiscoveryMap
typedef std::unordered_map<int32, SkillDiscoveryList> SkillDiscoveryMap
Definition at line 42 of file SkillDiscovery.cpp.
Function Documentation
GetExplicitDiscoverySpell()
uint32 GetExplicitDiscoverySpell (uint32 spellId, Player * player)
Definition at line 158 of file SkillDiscovery.cpp.
 {
     // explicit discovery spell chances (always success if case exist)
     // in this case we have both skill and spell
     SkillDiscoveryMap::const_iterator tab = SkillDiscoveryStore.find(int32(spellId));
     if (tab == SkillDiscoveryStore.end())
         return 0;
     SkillLineAbilityMapBounds bounds = sSpellMgr->GetSkillLineAbilityMapBounds(spellId);
     uint32 skillvalue = bounds.first != bounds.second ? player->GetSkillValue(bounds.first->second->SkillLine) : uint32(0);
     float full_chance = 0;
     for (SkillDiscoveryList::const_iterator item_iter = tab->second.begin(); item_iter != tab->second.end(); ++item_iter)
         if (item_iter->reqSkillValue <= skillvalue)
             if (!player->HasSpell(item_iter->spellId))
                 full_chance += item_iter->chance;
     float rate = full_chance / 100.0f;
     float roll = (float)rand_chance() * rate;                      // roll now in range 0..full_chance
     for (SkillDiscoveryList::const_iterator item_iter = tab->second.begin(); item_iter != tab->second.end(); ++item_iter)
     {
         if (item_iter->reqSkillValue > skillvalue)
             continue;
         if (player->HasSpell(item_iter->spellId))
             continue;
         if (item_iter->chance > roll)
         {
             // Update skill, not Book of Glyph Mastery
             if (spellId != 64323)
                 player->UpdateGatherSkill(SKILL_INSCRIPTION, player->GetPureSkillValue(SKILL_INSCRIPTION), item_iter->reqSkillValue);
             return item_iter->spellId;
         }
         roll -= item_iter->chance;
     }
     return 0;
 }
References Player::GetPureSkillValue(), Player::GetSkillValue(), Player::HasSpell(), rand_chance(), SKILL_INSCRIPTION, SkillDiscoveryStore, sSpellMgr, and Player::UpdateGatherSkill().
Referenced by spell_gen_profession_research::HandleScript(), and spell_item_book_of_glyph_mastery::HandleScript().
GetSkillDiscoverySpell()
uint32 GetSkillDiscoverySpell (uint32 skillId, uint32 spellId, Player * player)
Definition at line 213 of file SkillDiscovery.cpp.
 {
     uint32 skillvalue = skillId ? player->GetSkillValue(skillId) : uint32(0);
     // check spell case
     SkillDiscoveryMap::const_iterator tab = SkillDiscoveryStore.find(int32(spellId));
     if (tab != SkillDiscoveryStore.end())
     {
         for (SkillDiscoveryList::const_iterator item_iter = tab->second.begin(); item_iter != tab->second.end(); ++item_iter)
         {
             if (roll_chance_f(item_iter->chance * sWorld->getRate(RATE_SKILL_DISCOVERY)) &&
                     item_iter->reqSkillValue <= skillvalue &&
                     !player->HasSpell(item_iter->spellId))
                 return item_iter->spellId;
         }
         return 0;
     }
     if (!skillId)
         return 0;
     // check skill line case
     tab = SkillDiscoveryStore.find(-(int32)skillId);
     if (tab != SkillDiscoveryStore.end())
     {
         for (SkillDiscoveryList::const_iterator item_iter = tab->second.begin(); item_iter != tab->second.end(); ++item_iter)
         {
             if (roll_chance_f(item_iter->chance * sWorld->getRate(RATE_SKILL_DISCOVERY)) &&
                     item_iter->reqSkillValue <= skillvalue &&
                     !player->HasSpell(item_iter->spellId))
                 return item_iter->spellId;
         }
         return 0;
     }
     return 0;
 }
References Player::GetSkillValue(), Player::HasSpell(), RATE_SKILL_DISCOVERY, roll_chance_f(), SkillDiscoveryStore, and sWorld.
Referenced by Player::UpdateCraftSkill().
HasDiscoveredAllSpells()
bool HasDiscoveredAllSpells (uint32 spellId, Player * player)
Definition at line 200 of file SkillDiscovery.cpp.
 {
     SkillDiscoveryMap::const_iterator tab = SkillDiscoveryStore.find(int32(spellId));
     if (tab == SkillDiscoveryStore.end())
         return true;
     for (SkillDiscoveryList::const_iterator item_iter = tab->second.begin(); item_iter != tab->second.end(); ++item_iter)
         if (!player->HasSpell(item_iter->spellId))
             return false;
     return true;
 }
References Player::HasSpell(), and SkillDiscoveryStore.
Referenced by spell_gen_profession_research::CheckRequirement(), and spell_item_book_of_glyph_mastery::CheckRequirement().
LoadSkillDiscoveryTable()
void LoadSkillDiscoveryTable ()
Definition at line 46 of file SkillDiscovery.cpp.
 {
     uint32 oldMSTime = getMSTime();
     SkillDiscoveryStore.clear();                            // need for reload
     //                                                0        1         2              3
     QueryResult result = WorldDatabase.Query("SELECT spellId, reqSpell, reqSkillValue, chance FROM skill_discovery_template");
     if (!result)
     {
         LOG_ERROR("sql.sql", ">> Loaded 0 skill discovery definitions. DB table `skill_discovery_template` is empty.");
         LOG_INFO("server.loading", " ");
         return;
     }
     uint32 count = 0;
     std::ostringstream ssNonDiscoverableEntries;
     std::set<uint32> reportedReqSpells;
     do
     {
         Field* fields = result->Fetch();
         uint32 spellId         = fields[0].GetUInt32();
         int32  reqSkillOrSpell = fields[1].GetInt32();
         uint32 reqSkillValue   = fields[2].GetUInt16();
         float  chance          = fields[3].GetFloat();
         if (chance <= 0)                                    // chance
         {
             ssNonDiscoverableEntries << "spellId = " << spellId << " reqSkillOrSpell = " << reqSkillOrSpell
                                      << " reqSkillValue = " << reqSkillValue << " chance = " << chance << "(chance problem)\n";
             continue;
         }
         if (reqSkillOrSpell > 0)                            // spell case
         {
             uint32 absReqSkillOrSpell = uint32(reqSkillOrSpell);
             SpellInfo const* reqSpellInfo = sSpellMgr->GetSpellInfo(absReqSkillOrSpell);
             if (!reqSpellInfo)
             {
                 if (reportedReqSpells.find(absReqSkillOrSpell) == reportedReqSpells.end())
                 {
                     LOG_ERROR("sql.sql", "Spell (ID: %u) have not existed spell (ID: %i) in `reqSpell` field in `skill_discovery_template` table", spellId, reqSkillOrSpell);
                     reportedReqSpells.insert(absReqSkillOrSpell);
                 }
                 continue;
             }
             // mechanic discovery
             if (reqSpellInfo->Mechanic != MECHANIC_DISCOVERY &&
                     // explicit discovery ability
                     !reqSpellInfo->IsExplicitDiscovery())
             {
                 if (reportedReqSpells.find(absReqSkillOrSpell) == reportedReqSpells.end())
                 {
                     LOG_ERROR("sql.sql", "Spell (ID: %u) not have MECHANIC_DISCOVERY (28) value in Mechanic field in spell.dbc"
                                      " and not 100%% chance random discovery ability but listed for spellId %u (and maybe more) in `skill_discovery_template` table",
                                      absReqSkillOrSpell, spellId);
                     reportedReqSpells.insert(absReqSkillOrSpell);
                 }
                 continue;
             }
             SkillDiscoveryStore[reqSkillOrSpell].push_back(SkillDiscoveryEntry(spellId, reqSkillValue, chance));
         }
         else if (reqSkillOrSpell == 0)                      // skill case
         {
             SkillLineAbilityMapBounds bounds = sSpellMgr->GetSkillLineAbilityMapBounds(spellId);
             if (bounds.first == bounds.second)
             {
                 LOG_ERROR("sql.sql", "Spell (ID: %u) not listed in `SkillLineAbility.dbc` but listed with `reqSpell`=0 in `skill_discovery_template` table", spellId);
                 continue;
             }
             for (SkillLineAbilityMap::const_iterator _spell_idx = bounds.first; _spell_idx != bounds.second; ++_spell_idx)
                 SkillDiscoveryStore[-int32(_spell_idx->second->SkillLine)].push_back(SkillDiscoveryEntry(spellId, reqSkillValue, chance));
         }
         else
         {
             LOG_ERROR("sql.sql", "Spell (ID: %u) have negative value in `reqSpell` field in `skill_discovery_template` table", spellId);
             continue;
         }
         ++count;
     } while (result->NextRow());
     if (!ssNonDiscoverableEntries.str().empty())
         LOG_ERROR("sql.sql", "Some items can't be successfully discovered: have in chance field value < 0.000001 in `skill_discovery_template` DB table . List:\n%s", ssNonDiscoverableEntries.str().c_str());
     // report about empty data for explicit discovery spells
     for (uint32 spell_id = 1; spell_id < sSpellMgr->GetSpellInfoStoreSize(); ++spell_id)
     {
         SpellInfo const* spellEntry = sSpellMgr->GetSpellInfo(spell_id);
         if (!spellEntry)
             continue;
         // skip not explicit discovery spells
         if (!spellEntry->IsExplicitDiscovery())
             continue;
         if (SkillDiscoveryStore.find(int32(spell_id)) == SkillDiscoveryStore.end())
             LOG_ERROR("sql.sql", "Spell (ID: %u) is 100%% chance random discovery ability but not have data in `skill_discovery_template` table", spell_id);
     }
     LOG_INFO("server.loading", ">> Loaded %u skill discovery definitions in %u ms", count, GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
 }
References count(), Field::GetFloat(), Field::GetInt32(), getMSTime(), GetMSTimeDiffToNow(), Field::GetUInt16(), Field::GetUInt32(), SpellInfo::IsExplicitDiscovery(), LOG_ERROR, LOG_INFO, SpellInfo::Mechanic, MECHANIC_DISCOVERY, SkillDiscoveryStore, sSpellMgr, and WorldDatabase.
Referenced by reload_commandscript::HandleReloadSkillDiscoveryTemplateCommand(), and World::SetInitialWorldSettings().
Variable Documentation
SkillDiscoveryStore
SkillDiscoveryMap SkillDiscoveryStore static
Definition at line 44 of file SkillDiscovery.cpp.
Referenced by GetExplicitDiscoverySpell(), GetSkillDiscoverySpell(), HasDiscoveredAllSpells(), and LoadSkillDiscoveryTable().