Azerotcore-wotlk: boss_yoggsaron_descend_portal Class Reference
boss_yoggsaron_descend_portal Class Reference
Public Member Functions
boss_yoggsaron_descend_portal ()
bool OnGossipHello (Player *player, Creature *creature) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 1731 of file boss_yoggsaron.cpp.
Constructor & Destructor Documentation
boss_yoggsaron_descend_portal()
boss_yoggsaron_descend_portal::boss_yoggsaron_descend_portal () inline
Definition at line 1734 of file boss_yoggsaron.cpp.
 : CreatureScript("boss_yoggsaron_descend_portal") { }
Member Function Documentation
OnGossipHello()
bool boss_yoggsaron_descend_portal::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 1736 of file boss_yoggsaron.cpp.
     {
         if (!creature->GetUInt32Value(UNIT_NPC_FLAGS))
             return true;
         switch (creature->GetArmor())
         {
             case ACTION_ILLUSION_DRAGONS:
                 player->CastSpell(player, SPELL_TELEPORT_TO_CHAMBER, true);
                 break;
             case ACTION_ILLUSION_ICECROWN:
                 player->CastSpell(player, SPELL_TELEPORT_TO_ICECROWN, true);
                 break;
             case ACTION_ILLUSION_STORMWIND:
                 player->CastSpell(player, SPELL_TELEPORT_TO_STORMWIND, true);
                 break;
         }
         creature->SetUInt32Value(UNIT_NPC_FLAGS, 0);
         creature->DespawnOrUnsummon(1000);
         return true;
     }
References ACTION_ILLUSION_DRAGONS, ACTION_ILLUSION_ICECROWN, ACTION_ILLUSION_STORMWIND, Unit::CastSpell(), Creature::DespawnOrUnsummon(), Unit::GetArmor(), Object::GetUInt32Value(), Object::SetUInt32Value(), SPELL_TELEPORT_TO_CHAMBER, SPELL_TELEPORT_TO_ICECROWN, SPELL_TELEPORT_TO_STORMWIND, and UNIT_NPC_FLAGS.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_yoggsaron.cpp