Azerotcore-wotlk: ConfigMgr Class Reference
ConfigMgr Class Reference
#include <Config.h>
Public Member Functions
bool LoadAppConfigs ()
bool LoadModulesConfigs ()
void Configure (std::string const &initFileName, std::vector< std::string > args, std::string const &modulesConfigList="")
bool Reload ()
std::string const & GetFilename ()
std::string const GetConfigPath ()
std::vector< std::string > const & GetArguments () const
std::vector< std::string > GetKeysByString (std::string const &name)
template<class T >
T GetOption (std::string const &name, T const &def, bool showLogs=true) const
std::string GetStringDefault (std::string const &name, const std::string &def, bool showLogs=true)
bool GetBoolDefault (std::string const &name, bool def, bool showLogs=true)
int GetIntDefault (std::string const &name, int def, bool showLogs=true)
float GetFloatDefault (std::string const &name, float def, bool showLogs=true)
bool isDryRun ()
void setDryRun (bool mode)
void PrintLoadedModulesConfigs ()
template<>
bool GetOption (std::string const &name, bool const &def, bool showLogs) const
Static Public Member Functions
static ConfigMgr * instance ()
Private Member Functions
ConfigMgr ()=default
ConfigMgr (ConfigMgr const &)=delete
ConfigMgr & operator= (ConfigMgr const &)=delete
~ConfigMgr ()=default
bool LoadInitial (std::string const &file)
Method used only for loading main configuration files (authserver.conf and worldserver.conf)
bool LoadAdditionalFile (std::string file)
template<class T >
T GetValueDefault (std::string const &name, T const &def, bool showLogs=true) const
Private Attributes
bool dryRun = false
std::vector< std::string > _moduleConfigFiles
Detailed Description
Definition at line 26 of file Config.h.
Constructor & Destructor Documentation
ConfigMgr() [1/2]
ConfigMgr::ConfigMgr () private default
ConfigMgr() [2/2]
ConfigMgr::ConfigMgr (ConfigMgr const &) private delete
~ConfigMgr()
ConfigMgr::~ConfigMgr () private default
Member Function Documentation
Configure()
void ConfigMgr::Configure (std::string const & initFileName, std::vector< std::string > args, std::string const & modulesConfigList = "")
Definition at line 335 of file Config.cpp.
 {
     _filename = initFileName;
     _args = std::move(args);
     // Add modules config if exist
     if (!modulesConfigList.empty())
     {
         Tokenizer configFileList(modulesConfigList, ',');
         for (auto const& itr : configFileList)
         {
             _additonalFiles.emplace_back(std::string(itr));
         }
     }
 }
References anonymous_namespace{Config.cpp}::_additonalFiles, anonymous_namespace{Config.cpp}::_args, and anonymous_namespace{Config.cpp}::_filename.
GetArguments()
std::vector< std::string > const & ConfigMgr::GetArguments () const
Definition at line 319 of file Config.cpp.
 {
     return _args;
 }
References anonymous_namespace{Config.cpp}::_args.
GetBoolDefault()
bool ConfigMgr::GetBoolDefault (std::string const & name, bool def, bool showLogs = true)
Definition at line 440 of file Config.cpp.
 {
     return GetOption<bool>(name, def, showLogs);
 }
GetConfigPath()
std::string const ConfigMgr::GetConfigPath ()
Definition at line 324 of file Config.cpp.
 {
     std::lock_guard<std::mutex> lock(_configLock);
 #if AC_PLATFORM == AC_PLATFORM_WINDOWS
     return "configs/";
 #else
     return std::string(_CONF_DIR) + "/";
 #endif
 }
References anonymous_namespace{Config.cpp}::_configLock.
Referenced by LoadModulesConfigs().
GetFilename()
std::string const & ConfigMgr::GetFilename ()
Definition at line 313 of file Config.cpp.
 {
     std::lock_guard<std::mutex> lock(_configLock);
     return _filename;
 }
References anonymous_namespace{Config.cpp}::_configLock, and anonymous_namespace{Config.cpp}::_filename.
GetFloatDefault()
float ConfigMgr::GetFloatDefault (std::string const & name, float def, bool showLogs = true)
Definition at line 452 of file Config.cpp.
 {
     return GetOption<float>(name, def, showLogs);
 }
GetIntDefault()
int ConfigMgr::GetIntDefault (std::string const & name, int def, bool showLogs = true)
Definition at line 446 of file Config.cpp.
 {
     return GetOption<int32>(name, def, showLogs);
 }
GetKeysByString()
std::vector< std::string > ConfigMgr::GetKeysByString (std::string const & name)
Definition at line 298 of file Config.cpp.
 {
     std::lock_guard<std::mutex> lock(_configLock);
     std::vector<std::string> keys;
     for (auto const& [optionName, key] : _configOptions)
         if (!optionName.compare(0, name.length(), name))
         {
             keys.emplace_back(optionName);
         }
     return keys;
 }
References anonymous_namespace{Config.cpp}::_configLock, and anonymous_namespace{Config.cpp}::_configOptions.
GetOption() [1/2]
template<> bool ConfigMgr::GetOption (std::string const & name, bool const & def, bool showLogs) const
Definition at line 279 of file Config.cpp.
 {
     std::string val = GetValueDefault(name, std::string(def ? "1" : "0"), showLogs);
     auto boolVal = Acore::StringTo<bool>(val);
     if (!boolVal)
     {
         if (showLogs)
         {
             LOG_ERROR("server.loading", "> Config: Bad value defined for name '%s', going to use '%s' instead",
                 name.c_str(), def ? "true" : "false");
         }
         return def;
     }
     return *boolVal;
 }
References GetValueDefault(), and LOG_ERROR.
GetOption() [2/2]
template<class T > T ConfigMgr::GetOption (std::string const & name, T const & def, bool showLogs = true) const
Definition at line 273 of file Config.cpp.
 {
     return GetValueDefault<T>(name, def, showLogs);
 }
GetStringDefault()
std::string ConfigMgr::GetStringDefault (std::string const & name, const std::string & def, bool showLogs = true)
Definition at line 434 of file Config.cpp.
 {
     return GetOption<std::string>(name, def, showLogs);
 }
GetValueDefault()
template<class T > T ConfigMgr::GetValueDefault (std::string const & name, T const & def, bool showLogs = true) const private
Definition at line 225 of file Config.cpp.
 {
     auto const& itr = _configOptions.find(name);
     if (itr == _configOptions.end())
     {
         if (showLogs)
         {
             LOG_ERROR("server.loading", "> Config: Missing name %s in config, add \"%s = %s\"",
                 name.c_str(), name.c_str(), Acore::ToString(def).c_str());
         }
         return def;
     }
     auto value = Acore::StringTo<T>(itr->second);
     if (!value)
     {
         if (showLogs)
         {
             LOG_ERROR("server.loading", "> Config: Bad value defined for name '%s', going to use '%s' instead",
                 name.c_str(), Acore::ToString(def).c_str());
         }
         return def;
     }
     return *value;
 }
References anonymous_namespace{Config.cpp}::_configOptions, LOG_ERROR, and Acore::ToString().
Referenced by GetOption().
instance()
ConfigMgr * ConfigMgr::instance () static
Definition at line 208 of file Config.cpp.
 {
     static ConfigMgr instance;
     return &instance;
 }
isDryRun()
bool ConfigMgr::isDryRun () inline
Definition at line 70 of file Config.h.
 { return dryRun; }
References dryRun.
LoadAdditionalFile()
bool ConfigMgr::LoadAdditionalFile (std::string file) private
Definition at line 202 of file Config.cpp.
 {
     std::lock_guard<std::mutex> lock(_configLock);
     return LoadFile(file);
 }
References anonymous_namespace{Config.cpp}::_configLock, and anonymous_namespace{Config.cpp}::LoadFile().
Referenced by LoadAppConfigs(), and LoadModulesConfigs().
LoadAppConfigs()
bool ConfigMgr::LoadAppConfigs ()
Definition at line 351 of file Config.cpp.
 {
     // #1 - Load init config file .conf.dist
     if (!LoadInitial(_filename + ".dist"))
     {
         return false;
     }
     // #2 - Load .conf file
     if (!LoadAdditionalFile(_filename))
     {
         return false;
     }
     return true;
 }
References anonymous_namespace{Config.cpp}::_filename, LoadAdditionalFile(), and LoadInitial().
Referenced by Reload().
LoadInitial()
bool ConfigMgr::LoadInitial (std::string const & file) private
Method used only for loading main configuration files (authserver.conf and worldserver.conf)
Definition at line 195 of file Config.cpp.
 {
     std::lock_guard<std::mutex> lock(_configLock);
     _configOptions.clear();
     return LoadFile(file);
 }
References anonymous_namespace{Config.cpp}::_configLock, anonymous_namespace{Config.cpp}::_configOptions, and anonymous_namespace{Config.cpp}::LoadFile().
Referenced by LoadAppConfigs().
LoadModulesConfigs()
bool ConfigMgr::LoadModulesConfigs ()
Definition at line 368 of file Config.cpp.
 {
     if (_additonalFiles.empty())
     {
         return true;
     }
     // Start loading module configs
     std::string const& moduleConfigPath = GetConfigPath() + "modules/";
     bool isExistDefaultConfig = true;
     bool isExistDistConfig = true;
     for (auto const& distFileName : _additonalFiles)
     {
         std::string defaultFileName = distFileName;
         if (!defaultFileName.empty())
         {
             defaultFileName.erase(defaultFileName.end() - 5, defaultFileName.end());
         }
         // Load .conf.dist config
         if (!LoadAdditionalFile(moduleConfigPath + distFileName))
         {
             isExistDistConfig = false;
         }
         // Load .conf config
         if (!LoadAdditionalFile(moduleConfigPath + defaultFileName))
         {
             isExistDefaultConfig = false;
         }
         if (isExistDefaultConfig && isExistDistConfig)
         {
             _moduleConfigFiles.emplace_back(defaultFileName);
         }
         else if (!isExistDefaultConfig && isExistDistConfig)
         {
             _moduleConfigFiles.emplace_back(distFileName);
         }
     }
     // If module configs not exist - no load
     return !_moduleConfigFiles.empty();
 }
References anonymous_namespace{Config.cpp}::_additonalFiles, _moduleConfigFiles, GetConfigPath(), and LoadAdditionalFile().
Referenced by Reload().
operator=()
ConfigMgr& ConfigMgr::operator= (ConfigMgr const &) private delete
PrintLoadedModulesConfigs()
void ConfigMgr::PrintLoadedModulesConfigs ()
Definition at line 415 of file Config.cpp.
 {
     // Print modules configurations
     LOG_INFO("server.loading", " ");
     LOG_INFO("server.loading", "Using modules configuration:");
     for (auto const& itr : _moduleConfigFiles)
     {
         LOG_INFO("server.loading", "> %s", itr.c_str());
     }
     LOG_INFO("server.loading", " ");
 }
References _moduleConfigFiles, and LOG_INFO.
Reload()
bool ConfigMgr::Reload ()
Definition at line 214 of file Config.cpp.
 {
     if (!LoadAppConfigs())
     {
         return false;
     }
     return LoadModulesConfigs();
 }
References LoadAppConfigs(), and LoadModulesConfigs().
setDryRun()
void ConfigMgr::setDryRun (bool mode) inline
Definition at line 71 of file Config.h.
 { dryRun = mode; }
References dryRun.
Member Data Documentation
_moduleConfigFiles
std::vector<std::string > ConfigMgr::_moduleConfigFiles private
Definition at line 85 of file Config.h.
Referenced by LoadModulesConfigs(), and PrintLoadedModulesConfigs().
dryRun
bool ConfigMgr::dryRun = false private
Definition at line 83 of file Config.h.
Referenced by isDryRun(), and setDryRun().
The documentation for this class was generated from the following files:
src/common/Configuration/Config.h
src/common/Configuration/Config.cpp