Azerotcore-wotlk: boss_thorim::boss_thorimAI Struct Reference
boss_thorim::boss_thorimAI Struct Reference
Public Member Functions
boss_thorimAI (Creature *pCreature)
void DisableThorim (bool apply)
GameObject * GetThorimObject (uint32 entry)
void JustSummoned (Creature *cr) override
void SpawnAllNPCs ()
void CloseDoors ()
void EnterEvadeMode () override
void Reset () override
uint32 GetData (uint32 param) const override
void DoAction (int32 param) override
void KilledUnit (Unit *) override
void JustReachedHome () override
void EnterCombat (Unit *) override
void DamageTaken (Unit *who, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void SpawnArenaNPCs ()
void SpellHit (Unit *caster, const SpellInfo *spellInfo) override
void SpellHitTarget (Unit *target, const SpellInfo *spellInfo) override
void PlaySpecial ()
Player * GetArenaPlayer ()
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void JustDied (Unit *) override
void SummonedCreatureDespawn (Creature *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
bool _isArenaEmpty
bool _encounterFinished
bool _spawnCommoners
bool _hardMode
bool _isHitAllowed
bool _isAlly
uint8 _trashCounter
InstanceScript * m_pInstance
EventMap events
SummonList summons
bool _hitByLightning
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 327 of file boss_thorim.cpp.
Constructor & Destructor Documentation
boss_thorimAI()
boss_thorim::boss_thorimAI::boss_thorimAI (Creature * pCreature) inline
Definition at line 329 of file boss_thorim.cpp.
                                            : ScriptedAI(pCreature), summons(me)
         {
             m_pInstance = pCreature->GetInstanceScript();
             if ((_encounterFinished = (!me->IsAlive())))
                 if (m_pInstance)
                     m_pInstance->SetData(TYPE_THORIM, DONE);
         }
References _encounterFinished, DONE, WorldObject::GetInstanceScript(), Unit::IsAlive(), m_pInstance, ScriptedAI::me, ZoneScript::SetData(), and TYPE_THORIM.
Member Function Documentation
CloseDoors()
void boss_thorim::boss_thorimAI::CloseDoors () inline
Definition at line 418 of file boss_thorim.cpp.
         {
             GameObject* go;
             if ((go = GetThorimObject(DATA_THORIM_LEVER)))
             {
                 go->SetUInt32Value(GAMEOBJECT_FLAGS, 48);
                 go->SetGoState(GO_STATE_READY);
             }
             if ((go = GetThorimObject(DATA_THORIM_FIRST_DOORS)))
                 go->SetGoState(GO_STATE_READY);
             if ((go = GetThorimObject(DATA_THORIM_SECOND_DOORS)))
                 go->SetGoState(GO_STATE_READY);
             if ((go = GetThorimObject(DATA_THORIM_FENCE)))
                 go->SetGoState(GO_STATE_ACTIVE);
         }
References DATA_THORIM_FENCE, DATA_THORIM_FIRST_DOORS, DATA_THORIM_LEVER, DATA_THORIM_SECOND_DOORS, GAMEOBJECT_FLAGS, GetThorimObject(), GO_STATE_ACTIVE, GO_STATE_READY, GameObject::SetGoState(), and Object::SetUInt32Value().
Referenced by Reset().
DamageTaken()
void boss_thorim::boss_thorimAI::DamageTaken (Unit * who, uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 530 of file boss_thorim.cpp.
         {
             if (who && _isHitAllowed && who->GetPositionZ() > 430 && who->GetTypeId() == TYPEID_PLAYER)
             {
                 _isHitAllowed = false;
                 DisableThorim(false);
                 events.SetPhase(EVENT_PHASE_RING);
                 events.ScheduleEvent(EVENT_THORIM_UNBALANCING_STRIKE, 8000, 0, EVENT_PHASE_RING);
                 events.ScheduleEvent(EVENT_THORIM_LIGHTNING_CHARGE, 12500, 0, EVENT_PHASE_RING);
                 events.ScheduleEvent(EVENT_THORIM_CHAIN_LIGHTNING, 13000, 0, EVENT_PHASE_RING);
                 events.ScheduleEvent(EVENT_THORIM_BERSERK, 300000, 0, EVENT_PHASE_RING);
                 me->GetMotionMaster()->MoveChase(me->GetVictim());
                 me->GetMotionMaster()->MoveJump(Middle.GetPositionX(), Middle.GetPositionY(), Middle.GetPositionZ(), 20, 20);
                 me->RemoveAura(SPELL_SHEATH_OF_LIGHTNING);
                 me->Yell("Impertinent whelps! You dare challenge me atop my pedestal! I will crush you myself!", LANG_UNIVERSAL);
                 me->PlayDirectSound(SOUND_JUMPDOWN);
                 // Hard Mode
                 if (!me->HasAura(62565 /*TOUCH OF DOMINION TRIGGER*/))
                 {
                     if (m_pInstance)
                         m_pInstance->DoUpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, 64980 /*SIFFED ACHIEVEMENT*/);
                     _hardMode = true;
                     EntryCheckPredicate pred(NPC_SIF);
                     summons.DoAction(ACTION_SIF_JOIN_FIGHT, pred);
                 }
                 DoResetThreat();
                 if (Player* player = GetArenaPlayer())
                     me->AddThreat(player, 1000.0f);
             }
             if (damage >= me->GetHealth())
             {
                 damage = 0;
                 if (!_encounterFinished)
                 {
                     _encounterFinished = true;
                     me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                     me->SetFaction(FACTION_FRIENDLY);
                     me->SetHealth(me->GetMaxHealth());
                     me->CombatStop();
                     me->RemoveAllAuras();
                     events.Reset();
                     DisableThorim(true);
                     me->Yell("Stay your arms! I yield!", LANG_UNIVERSAL);
                     me->PlayDirectSound(SOUND_DEFEATED);
                     events.SetPhase(EVENT_PHASE_OUTRO);
                     events.ScheduleEvent(EVENT_THORIM_OUTRO1, 2000, 0, EVENT_PHASE_OUTRO);
                     GameObject* go = nullptr;
                     if ((go = GetThorimObject(DATA_THORIM_FENCE)))
                         go->SetGoState(GO_STATE_ACTIVE);
                     uint32 chestId = me->GetMap()->Is25ManRaid() ? GO_THORIM_CHEST_HERO : GO_THORIM_CHEST;
                     if (_hardMode)
                         chestId += 1; // hard mode offset
                     if ((go = me->SummonGameObject(chestId, 2134.73f, -286.32f, 419.51f, 0.0f, 0, 0, 0, 0, 0)))
                         go->SetUInt32Value(GAMEOBJECT_FLAGS, 0);
                     // Defeat credit
                     if (m_pInstance)
                     {
                         me->CastSpell(me, 64985, true); // credit
                         m_pInstance->SetData(TYPE_THORIM, DONE);
                     }
                 }
             }
         }
References _encounterFinished, _hardMode, _isHitAllowed, ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, ACTION_SIF_JOIN_FIGHT, Unit::AddThreat(), Unit::CastSpell(), Unit::CombatStop(), DATA_THORIM_FENCE, DisableThorim(), SummonList::DoAction(), DONE, ScriptedAI::DoResetThreat(), InstanceScript::DoUpdateAchievementCriteria(), EVENT_PHASE_OUTRO, EVENT_PHASE_RING, EVENT_THORIM_BERSERK, EVENT_THORIM_CHAIN_LIGHTNING, EVENT_THORIM_LIGHTNING_CHARGE, EVENT_THORIM_OUTRO1, EVENT_THORIM_UNBALANCING_STRIKE, FACTION_FRIENDLY, GAMEOBJECT_FLAGS, GetArenaPlayer(), Unit::GetHealth(), WorldObject::GetMap(), Unit::GetMaxHealth(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GetThorimObject(), Object::GetTypeId(), Unit::GetVictim(), GO_STATE_ACTIVE, GO_THORIM_CHEST, GO_THORIM_CHEST_HERO, Unit::HasAura(), Map::Is25ManRaid(), LANG_UNIVERSAL, m_pInstance, ScriptedAI::me, Middle, MotionMaster::MoveChase(), MotionMaster::MoveJump(), NPC_SIF, WorldObject::PlayDirectSound(), Unit::RemoveAllAuras(), Unit::RemoveAura(), ZoneScript::SetData(), Unit::SetFaction(), Object::SetFlag(), GameObject::SetGoState(), Unit::SetHealth(), Object::SetUInt32Value(), SOUND_DEFEATED, SOUND_JUMPDOWN, SPELL_SHEATH_OF_LIGHTNING, WorldObject::SummonGameObject(), summons, TYPE_THORIM, TYPEID_PLAYER, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and Unit::Yell().
DisableThorim()
void boss_thorim::boss_thorimAI::DisableThorim (bool apply) inline
Definition at line 351 of file boss_thorim.cpp.
         {
             if (apply)
             {
                 me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE | UNIT_FLAG_PACIFIED);
                 me->DisableRotate(true);
                 me->AddUnitState(UNIT_STATE_ROOT);
             }
             else
             {
                 me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE | UNIT_FLAG_PACIFIED);
                 me->DisableRotate(false);
                 me->ClearUnitState(UNIT_STATE_ROOT);
                 me->resetAttackTimer(BASE_ATTACK);
             }
         }
References Unit::AddUnitState(), ByteConverter::apply(), BASE_ATTACK, Unit::ClearUnitState(), Unit::DisableRotate(), ScriptedAI::me, Object::RemoveFlag(), Unit::resetAttackTimer(), Object::SetFlag(), UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE, UNIT_FLAG_PACIFIED, and UNIT_STATE_ROOT.
Referenced by DamageTaken(), EnterCombat(), EnterEvadeMode(), and Reset().
DoAction()
void boss_thorim::boss_thorimAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 479 of file boss_thorim.cpp.
         {
             if (param == ACTION_START_TRASH_DIED)
             {
                 _trashCounter++;
                 // activate levar
                 if (_trashCounter >= 6)
                 {
                     if (GameObject* go = GetThorimObject(DATA_THORIM_LEVER))
                         go->RemoveFlag(GAMEOBJECT_FLAGS, 48);
                     events.SetPhase(EVENT_PHASE_START);
                     events.ScheduleEvent(EVENT_THORIM_START_PHASE1, 20000);
                     _trashCounter = 0;
                 }
                 else if (_trashCounter == 5)
                     events.ScheduleEvent(EVENT_THORIM_AGGRO, 0);
             }
             else if (param == ACTION_ALLOW_HIT)
                 _isHitAllowed = true;
         }
References _isHitAllowed, _trashCounter, ACTION_ALLOW_HIT, ACTION_START_TRASH_DIED, DATA_THORIM_LEVER, EVENT_PHASE_START, EVENT_THORIM_AGGRO, EVENT_THORIM_START_PHASE1, GAMEOBJECT_FLAGS, and GetThorimObject().
EnterCombat()
void boss_thorim::boss_thorimAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 520 of file boss_thorim.cpp.
         {
             if (m_pInstance && !_encounterFinished)
                 m_pInstance->SetData(TYPE_THORIM, IN_PROGRESS);
             me->setActive(true);
             DisableThorim(true);
             me->CastSpell(me, SPELL_SHEATH_OF_LIGHTNING, true);
             //me->CastSpell(me, SPELL_TOUCH_OF_DOMINION, true);
         }
References _encounterFinished, Unit::CastSpell(), DisableThorim(), IN_PROGRESS, m_pInstance, ScriptedAI::me, WorldObject::setActive(), ZoneScript::SetData(), SPELL_SHEATH_OF_LIGHTNING, and TYPE_THORIM.
EnterEvadeMode()
void boss_thorim::boss_thorimAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 436 of file boss_thorim.cpp.
         {
             DisableThorim(false);
             CreatureAI::EnterEvadeMode();
         }
References DisableThorim(), and CreatureAI::EnterEvadeMode().
GetArenaPlayer()
Player* boss_thorim::boss_thorimAI::GetArenaPlayer () inline
Definition at line 664 of file boss_thorim.cpp.
         {
             Map::PlayerList const& pList = me->GetMap()->GetPlayers();
             for(Map::PlayerList::const_iterator itr = pList.begin(); itr != pList.end(); ++itr)
                 if (Player* p = itr->GetSource())
                     if (p->GetPositionX() > 2085 && p->GetPositionX() < 2185 && p->GetPositionY() < -214 && p->GetPositionY() > -305 && p->IsAlive() && p->GetPositionZ() < 425)
                         return p;
             return nullptr;
         }
References MapRefMgr::begin(), MapRefMgr::end(), WorldObject::GetMap(), Map::GetPlayers(), and ScriptedAI::me.
Referenced by DamageTaken(), and UpdateAI().
GetData()
uint32 boss_thorim::boss_thorimAI::GetData (uint32 param) const inline override virtual
Reimplemented from UnitAI.
Definition at line 469 of file boss_thorim.cpp.
         {
             if (param == DATA_HIT_BY_LIGHTNING)
                 return !_hitByLightning;
             if (param == DATA_LOSE_YOUR_ILLUSION)
                 return _hardMode;
             return 0;
         }
References _hardMode, _hitByLightning, DATA_HIT_BY_LIGHTNING, and DATA_LOSE_YOUR_ILLUSION.
GetThorimObject()
GameObject* boss_thorim::boss_thorimAI::GetThorimObject (uint32 entry) inline
Definition at line 368 of file boss_thorim.cpp.
         {
             if (m_pInstance)
                 return ObjectAccessor::GetGameObject(*me, m_pInstance->GetGuidData(entry));
             return nullptr;
         }
References ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), m_pInstance, and ScriptedAI::me.
Referenced by CloseDoors(), DamageTaken(), DoAction(), and UpdateAI().
JustReachedHome()
void boss_thorim::boss_thorimAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 518 of file boss_thorim.cpp.
 { me->setActive(false); }
References ScriptedAI::me, and WorldObject::setActive().
JustSummoned()
void boss_thorim::boss_thorimAI::JustSummoned (Creature * cr) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 375 of file boss_thorim.cpp.
 { summons.Summon(cr); }
References SummonList::Summon(), and summons.
KilledUnit()
void boss_thorim::boss_thorimAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 501 of file boss_thorim.cpp.
         {
             if (urand(0, 2))
                 return;
             if (urand(0, 1))
             {
                 me->Yell("Can't you at least put up a fight!?", LANG_UNIVERSAL);
                 me->PlayDirectSound(SOUND_SLAY1);
             }
             else
             {
                 me->Yell("Pathetic!", LANG_UNIVERSAL);
                 me->PlayDirectSound(SOUND_SLAY2);
             }
         }
References LANG_UNIVERSAL, ScriptedAI::me, WorldObject::PlayDirectSound(), SOUND_SLAY1, SOUND_SLAY2, urand(), and Unit::Yell().
PlaySpecial()
void boss_thorim::boss_thorimAI::PlaySpecial () inline
Definition at line 642 of file boss_thorim.cpp.
         {
             if (urand(0, 9))
                 return;
             switch (urand(0, 2))
             {
                 case 0:
                     me->Yell("Behold the power of the storms and despair!", LANG_UNIVERSAL);
                     me->PlayDirectSound(SOUND_SPECIAL1);
                     break;
                 case 1:
                     me->Yell("Do not hold back! Destroy them!", LANG_UNIVERSAL);
                     me->PlayDirectSound(SOUND_SPECIAL2);
                     break;
                 case 2:
                     me->Yell("Have you begun to regret your intrusion? ", LANG_UNIVERSAL);
                     me->PlayDirectSound(SOUND_SPECIAL3);
                     break;
             }
         }
References LANG_UNIVERSAL, ScriptedAI::me, WorldObject::PlayDirectSound(), SOUND_SPECIAL1, SOUND_SPECIAL2, SOUND_SPECIAL3, urand(), and Unit::Yell().
Referenced by UpdateAI().
Reset()
void boss_thorim::boss_thorimAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 442 of file boss_thorim.cpp.
         {
             if (m_pInstance && !_encounterFinished)
                 m_pInstance->SetData(TYPE_THORIM, NOT_STARTED);
             events.Reset();
             events.SetPhase(0);
             summons.DespawnAll();
             _trashCounter = 0;
             _isAlly = true;
             _isHitAllowed = false;
             _spawnCommoners = false;
             _hardMode = false;
             _isArenaEmpty = false;
             _hitByLightning = false;
             if (Player* t = SelectTargetFromPlayerList(1000))
                 if (t->GetTeamId() == TEAM_HORDE)
                     _isAlly = false;
             SpawnAllNPCs();
             CloseDoors();
             DisableThorim(false);
         }
References _encounterFinished, _hardMode, _hitByLightning, _isAlly, _isArenaEmpty, _isHitAllowed, _spawnCommoners, _trashCounter, CloseDoors(), SummonList::DespawnAll(), DisableThorim(), m_pInstance, NOT_STARTED, ScriptedAI::SelectTargetFromPlayerList(), ZoneScript::SetData(), SpawnAllNPCs(), summons, TEAM_HORDE, and TYPE_THORIM.
SpawnAllNPCs()
void boss_thorim::boss_thorimAI::SpawnAllNPCs () inline
Definition at line 377 of file boss_thorim.cpp.
         {
             // Jormungar Behemoth 32882
             me->SummonCreature(NPC_JORMUNGAR_BEHEMOT, 2149.68f, -263.477f, 419.679f, 3.12102f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 5000);
             // Captured Mercenary Soldier 32885
             me->SummonCreature(_isAlly ? NPC_CAPTURED_MERCENARY_SOLDIER_ALLY : NPC_CAPTURED_MERCENARY_SOLDIER_HORDE, 2127.24f, -251.309f, 419.793f, 5.89921f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 5000);
             me->SummonCreature(_isAlly ? NPC_CAPTURED_MERCENARY_SOLDIER_ALLY : NPC_CAPTURED_MERCENARY_SOLDIER_HORDE, 2120.1f, -258.99f, 419.764f, 6.24828f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 5000);
             me->SummonCreature(_isAlly ? NPC_CAPTURED_MERCENARY_SOLDIER_ALLY : NPC_CAPTURED_MERCENARY_SOLDIER_HORDE, 2123.32f, -254.771f, 419.789f, 6.17846f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 5000);
             // Captured Mercenary Captain 32908
             me->SummonCreature(_isAlly ? NPC_CAPTURED_MERCENARY_CAPTAIN_ALLY : NPC_CAPTURED_MERCENARY_CAPTAIN_HORDE, 2131.31f, -259.182f, 419.974f, 5.91667f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 5000);
             // Dark Rune Acolyte (arena) 32886
             me->SummonCreature(NPC_DARK_RUNE_ACOLYTE_I, 2129.09f, -277.142f, 419.756f, 1.22173f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 5000);
             // Iron Ring Guard 32874
             me->SummonCreature(NPC_IRON_RING_GUARD, 2217.69f, -337.394f, 412.177f, 1.23918f);
             me->SummonCreature(NPC_IRON_RING_GUARD, 2218.38f, -297.505f, 412.176f, 1.02974f);
             me->SummonCreature(NPC_IRON_RING_GUARD, 2235.26f, -338.345f, 412.134f, 1.58979f);
             me->SummonCreature(NPC_IRON_RING_GUARD, 2235.07f, -297.985f, 412.134f, 1.61336f);
             // Dark Rune Acolyte (gauntlet) 33110
             me->SummonCreature(NPC_DARK_RUNE_ACOLYTE_G, 2198.29f, -436.92f, 419.985f, 0.261799f);
             me->SummonCreature(NPC_DARK_RUNE_ACOLYTE_G, 2227.58f, -308.303f, 412.134f, 1.59372f);
             me->SummonCreature(NPC_DARK_RUNE_ACOLYTE_G, 2227.47f, -345.375f, 412.134f, 1.56622f);
             // Iron Honor Guard 32875
             me->SummonCreature(NPC_IRON_HONOR_GUARD, 2198.05f, -428.769f, 419.985f, 6.05629f);
             me->SummonCreature(NPC_IRON_HONOR_GUARD, 2220.31f, -436.22f, 412.26f, 1.06465f);
             // Runic Colossus 32872
             me->SummonCreature(NPC_RUNIC_COLOSSUS, 2227.5f, -396.179f, 412.176f, 1.79769f);
             // Ancient Rune Giant 32873
             me->SummonCreature(NPC_ANCIENT_RUNE_GIANT, 2134.57f, -440.318f, 438.331f, 0.226893f);
             // Sif 33196
             me->SummonCreature(NPC_SIF, 2147.86f, -301.2f, 438.246f, 2.488f);
         }
References _isAlly, ScriptedAI::me, NPC_ANCIENT_RUNE_GIANT, NPC_CAPTURED_MERCENARY_CAPTAIN_ALLY, NPC_CAPTURED_MERCENARY_CAPTAIN_HORDE, NPC_CAPTURED_MERCENARY_SOLDIER_ALLY, NPC_CAPTURED_MERCENARY_SOLDIER_HORDE, NPC_DARK_RUNE_ACOLYTE_G, NPC_DARK_RUNE_ACOLYTE_I, NPC_IRON_HONOR_GUARD, NPC_IRON_RING_GUARD, NPC_JORMUNGAR_BEHEMOT, NPC_RUNIC_COLOSSUS, NPC_SIF, WorldObject::SummonCreature(), and TEMPSUMMON_CORPSE_TIMED_DESPAWN.
Referenced by Reset().
SpawnArenaNPCs()
void boss_thorim::boss_thorimAI::SpawnArenaNPCs () inline
Definition at line 607 of file boss_thorim.cpp.
         {
             Creature* cr;
             uint8 rnd;
             if (_spawnCommoners || urand(0, 2))
                 _spawnCommoners = !_spawnCommoners;
             for (uint8 i = 0; i < (_spawnCommoners ? 7 : 2); ++i)
             {
                 rnd = urand(0, 13);
                 if ((cr = me->SummonCreature((_spawnCommoners ? NPC_DARK_RUNE_COMMONER : RollTable[urand(0, 2)]), ArenaNPCs[rnd], TEMPSUMMON_CORPSE_TIMED_DESPAWN, 5000)))
                     cr->GetMotionMaster()->MoveJump(
                         Middle.GetPositionX() + urand(19, 24) * cos(Middle.GetAngle(cr)),
                         Middle.GetPositionY() + urand(19, 24) * sin(Middle.GetAngle(cr)),
                         Middle.GetPositionZ(), 20, 20);
             }
         }
References _spawnCommoners, ArenaNPCs, Position::GetAngle(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ScriptedAI::me, Middle, MotionMaster::MoveJump(), NPC_DARK_RUNE_COMMONER, RollTable, WorldObject::SummonCreature(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, and urand().
Referenced by UpdateAI().
SpellHit()
void boss_thorim::boss_thorimAI::SpellHit (Unit * caster, const SpellInfo * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 625 of file boss_thorim.cpp.
         {
             if (spellInfo->Id == SPELL_LIGHTNING_ORB_CHARGER)
             {
                 me->SetOrientation(me->GetAngle(caster));
                 me->CastSpell(caster, SPELL_LIGHTNING_CHARGE_DAMAGE, true);
                 me->CastSpell(me, SPELL_LIGHTNING_CHARGE_BUFF, true);
                 events.RescheduleEvent(EVENT_THORIM_LIGHTNING_CHARGE, 10000, 0, EVENT_PHASE_RING);
             }
         }
References Unit::CastSpell(), EVENT_PHASE_RING, EVENT_THORIM_LIGHTNING_CHARGE, Position::GetAngle(), SpellInfo::Id, ScriptedAI::me, Position::SetOrientation(), SPELL_LIGHTNING_CHARGE_BUFF, SPELL_LIGHTNING_CHARGE_DAMAGE, and SPELL_LIGHTNING_ORB_CHARGER.
SpellHitTarget()
void boss_thorim::boss_thorimAI::SpellHitTarget (Unit * target, const SpellInfo * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 636 of file boss_thorim.cpp.
         {
             if (spellInfo->Id == SPELL_LIGHTNING_CHARGE_DAMAGE && target->GetTypeId() == TYPEID_PLAYER)
                 _hitByLightning = true;
         }
References _hitByLightning, Object::GetTypeId(), SpellInfo::Id, SPELL_LIGHTNING_CHARGE_DAMAGE, and TYPEID_PLAYER.
UpdateAI()
void boss_thorim::boss_thorimAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 674 of file boss_thorim.cpp.
         {
             if (!_encounterFinished && !UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_THORIM_AGGRO:
                     me->Yell("Interlopers! You mortals who dare to interfere with my sport will pay... Wait--you...", LANG_UNIVERSAL);
                     me->PlayDirectSound(SOUND_AGGRO1);
                     events.ScheduleEvent(EVENT_THORIM_AGGRO2, 9000);
                     if (GameObject* go = GetThorimObject(DATA_THORIM_FENCE))
                         go->SetGoState(GO_STATE_READY);
                     break;
                 case EVENT_THORIM_AGGRO2:
                     {
                         me->Yell("I remember you... In the mountains... But you... what is this? Where am--", LANG_UNIVERSAL);
                         me->PlayDirectSound(SOUND_AGGRO2);
                         EntryCheckPredicate pred(NPC_SIF);
                         summons.DoAction(ACTION_SIF_START_TALK, pred);
                         break;
                     }
                 case EVENT_THORIM_START_PHASE1:
                     {
                         events.ScheduleEvent(EVENT_THORIM_STORMHAMMER, 8000, 0, EVENT_PHASE_START);
                         events.ScheduleEvent(EVENT_THORIM_CHARGE_ORB, 14000, 0, EVENT_PHASE_START);
                         events.ScheduleEvent(EVENT_THORIM_FILL_ARENA, 0, 0, EVENT_PHASE_START);
                         events.ScheduleEvent(EVENT_THORIM_LIGHTNING_ORB, 5000, 0, EVENT_PHASE_START); // checked every 5 secs if there are players on arena
                         events.ScheduleEvent(EVENT_THORIM_NOT_REACH_IN_TIME, 300000, 0, EVENT_PHASE_START);
                         EntryCheckPredicate pred(NPC_SIF);
                         summons.DoAction(ACTION_SIF_START_DOMINION, pred);
                         break;
                     }
                 case EVENT_THORIM_STORMHAMMER:
                     me->CastCustomSpell(SPELL_STORMHAMMER, SPELLVALUE_MAX_TARGETS, 1, me->GetVictim(), false);
                     events.RepeatEvent(16000);
                     PlaySpecial();
                     break;
                 case EVENT_THORIM_CHARGE_ORB:
                     me->CastCustomSpell(SPELL_CHARGE_ORB, SPELLVALUE_MAX_TARGETS, 1, me, false);
                     events.RepeatEvent(16000);
                     PlaySpecial();
                     break;
                 case EVENT_THORIM_LIGHTNING_ORB:
                     {
                         if (GetArenaPlayer())
{
                             // Player found, repeat and return
                             events.RepeatEvent(5000);
                             return;
                         }
                         // No players found
                         me->Yell("Failures! Weaklings!", LANG_UNIVERSAL);
                         me->PlayDirectSound(SOUND_AWIPE);
                         me->SummonCreature(NPC_LIGHTNING_ORB, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ());
                         _isArenaEmpty = true;
                         events.CancelEvent(EVENT_THORIM_NOT_REACH_IN_TIME);
                         break;
                     }
                 case EVENT_THORIM_NOT_REACH_IN_TIME:
                     _isArenaEmpty = true;
                     events.CancelEvent(EVENT_THORIM_LIGHTNING_ORB);
                     me->CastSpell(me, SPELL_BERSERK_FRIENDS, true);
                     me->SummonCreature(NPC_LIGHTNING_ORB, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ());
                     break;
                 case EVENT_THORIM_FILL_ARENA:
                     SpawnArenaNPCs();
                     events.RepeatEvent(10000);
                     PlaySpecial();
                     break;
                 case EVENT_THORIM_UNBALANCING_STRIKE:
                     me->CastSpell(me->GetVictim(), SPELL_UNBALANCING_STRIKE, false);
                     events.RepeatEvent(20000);
                     break;
                 case EVENT_THORIM_LIGHTNING_CHARGE:
                     me->CastSpell(me, SPELL_LIGHTNING_PILLAR_P2, true);
                     break;
                 case EVENT_THORIM_CHAIN_LIGHTNING:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
                         me->CastSpell(target, SPELL_CHAIN_LIGHTNING, false);
                     events.RepeatEvent(15000);
                     break;
                 case EVENT_THORIM_BERSERK:
                     me->CastSpell(me, SPELL_BERSERK, true);
                     me->Yell("My patience has reached its limit!", LANG_UNIVERSAL);
                     me->PlayDirectSound(SOUND_BERSERK);
                     break;
                 case EVENT_THORIM_OUTRO1:
                     if (_hardMode)
                     {
                         me->Yell("You! Fiend! You are not my beloved! Be gone!", LANG_UNIVERSAL);
                         me->PlayDirectSound(SOUND_HARD1);
                         events.ScheduleEvent(EVENT_THORIM_OUTRO2, 5000, 0, 3);
                         EntryCheckPredicate pred(NPC_SIF);
                         summons.DoAction(ACTION_SIF_TRANSFORM, pred);
                     }
                     else
                     {
                         me->Yell("I feel as though I am awakening from a nightmare, but the shadows in this place yet linger.", LANG_UNIVERSAL);
                         me->PlayDirectSound(SOUND_NORM1);
                         events.ScheduleEvent(EVENT_THORIM_OUTRO2, 9000, 0, 3);
                     }
                     break;
                 case EVENT_THORIM_OUTRO2:
                     if (_hardMode)
                     {
                         me->Yell("Behold the hand behind all the evil that has befallen Ulduar! Left my kingdom in ruins, corrupted my brother and slain my wife!", LANG_UNIVERSAL);
                         me->PlayDirectSound(SOUND_HARD2);
                         events.ScheduleEvent(EVENT_THORIM_OUTRO3, 12000, 0, 3);
                     }
                     else
                     {
                         me->Yell("Sif... was Sif here? Impossible--she died by my brother's hand. A dark nightmare indeed....", LANG_UNIVERSAL);
                         me->PlayDirectSound(SOUND_NORM2);
                         events.ScheduleEvent(EVENT_THORIM_OUTRO3, 10000, 0, 3);
                     }
                     break;
                 case EVENT_THORIM_OUTRO3:
                     if (_hardMode)
                     {
                         me->Yell("And now it falls to you, champions, to avenge us all! The task before you is great, but I will lend you my aid as I am able. You must prevail!", LANG_UNIVERSAL);
                         me->PlayDirectSound(SOUND_HARD3);
                     }
                     else
                     {
                         me->Yell("I need time to reflect.... I will aid your cause if you should require it. I owe you at least that much. Farewell.", LANG_UNIVERSAL);
                         me->PlayDirectSound(SOUND_NORM3);
                     }
                     // Defeat credit
                     if (m_pInstance)
                         m_pInstance->SetData(TYPE_THORIM, DONE);
                     me->DespawnOrUnsummon(8000);
                     break;
             }
             if (!_encounterFinished)
                 DoMeleeAttackIfReady();
         }
References _encounterFinished, _hardMode, _isArenaEmpty, ACTION_SIF_START_DOMINION, ACTION_SIF_START_TALK, ACTION_SIF_TRANSFORM, Unit::CastCustomSpell(), Unit::CastSpell(), DATA_THORIM_FENCE, Creature::DespawnOrUnsummon(), SummonList::DoAction(), UnitAI::DoMeleeAttackIfReady(), DONE, EVENT_PHASE_START, EVENT_THORIM_AGGRO, EVENT_THORIM_AGGRO2, EVENT_THORIM_BERSERK, EVENT_THORIM_CHAIN_LIGHTNING, EVENT_THORIM_CHARGE_ORB, EVENT_THORIM_FILL_ARENA, EVENT_THORIM_LIGHTNING_CHARGE, EVENT_THORIM_LIGHTNING_ORB, EVENT_THORIM_NOT_REACH_IN_TIME, EVENT_THORIM_OUTRO1, EVENT_THORIM_OUTRO2, EVENT_THORIM_OUTRO3, EVENT_THORIM_START_PHASE1, EVENT_THORIM_STORMHAMMER, EVENT_THORIM_UNBALANCING_STRIKE, GetArenaPlayer(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GetThorimObject(), Unit::GetVictim(), GO_STATE_READY, Unit::HasUnitState(), LANG_UNIVERSAL, m_pInstance, ScriptedAI::me, NPC_LIGHTNING_ORB, NPC_SIF, WorldObject::PlayDirectSound(), PlaySpecial(), SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), ZoneScript::SetData(), SOUND_AGGRO1, SOUND_AGGRO2, SOUND_AWIPE, SOUND_BERSERK, SOUND_HARD1, SOUND_HARD2, SOUND_HARD3, SOUND_NORM1, SOUND_NORM2, SOUND_NORM3, SpawnArenaNPCs(), SPELL_BERSERK, SPELL_BERSERK_FRIENDS, SPELL_CHAIN_LIGHTNING, SPELL_CHARGE_ORB, SPELL_LIGHTNING_PILLAR_P2, SPELL_STORMHAMMER, SPELL_UNBALANCING_STRIKE, SPELLVALUE_MAX_TARGETS, WorldObject::SummonCreature(), summons, TYPE_THORIM, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and Unit::Yell().
Member Data Documentation
_encounterFinished
bool boss_thorim::boss_thorimAI::_encounterFinished
Definition at line 338 of file boss_thorim.cpp.
Referenced by boss_thorimAI(), DamageTaken(), EnterCombat(), Reset(), and UpdateAI().
_hardMode
bool boss_thorim::boss_thorimAI::_hardMode
Definition at line 340 of file boss_thorim.cpp.
Referenced by DamageTaken(), GetData(), Reset(), and UpdateAI().
_hitByLightning
bool boss_thorim::boss_thorimAI::_hitByLightning
Definition at line 349 of file boss_thorim.cpp.
Referenced by GetData(), Reset(), and SpellHitTarget().
_isAlly
bool boss_thorim::boss_thorimAI::_isAlly
Definition at line 342 of file boss_thorim.cpp.
Referenced by Reset(), and SpawnAllNPCs().
_isArenaEmpty
bool boss_thorim::boss_thorimAI::_isArenaEmpty
Definition at line 337 of file boss_thorim.cpp.
Referenced by Reset(), and UpdateAI().
_isHitAllowed
bool boss_thorim::boss_thorimAI::_isHitAllowed
Definition at line 341 of file boss_thorim.cpp.
Referenced by DamageTaken(), DoAction(), and Reset().
_spawnCommoners
bool boss_thorim::boss_thorimAI::_spawnCommoners
Definition at line 339 of file boss_thorim.cpp.
Referenced by Reset(), and SpawnArenaNPCs().
_trashCounter
uint8 boss_thorim::boss_thorimAI::_trashCounter
Definition at line 343 of file boss_thorim.cpp.
Referenced by DoAction(), and Reset().
events
EventMap boss_thorim::boss_thorimAI::events
Definition at line 346 of file boss_thorim.cpp.
m_pInstance
InstanceScript* boss_thorim::boss_thorimAI::m_pInstance
Definition at line 345 of file boss_thorim.cpp.
Referenced by boss_thorimAI(), DamageTaken(), EnterCombat(), GetThorimObject(), Reset(), and UpdateAI().
summons
SummonList boss_thorim::boss_thorimAI::summons
Definition at line 347 of file boss_thorim.cpp.
Referenced by DamageTaken(), JustSummoned(), Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_thorim.cpp