Azerotcore-wotlk: boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI Struct Reference
boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI Struct Reference
Public Member Functions
boss_flame_leviathan_defense_turretAI (Creature *creature)
void DamageTaken (Unit *who, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *who) override
bool CanAIAttack (Unit const *who) const override
void UpdateAI (uint32 diff) override
void KilledUnit (Unit *who) override
Public Member Functions inherited from TurretAI
TurretAI (Creature *c)
void AttackStart (Unit *who) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void EnterCombat (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * _instance
bool _setHealth
Additional Inherited Members
Static Public Member Functions inherited from TurretAI
static int Permissible (Creature const *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from TurretAI
float m_minRange
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 787 of file boss_flame_leviathan.cpp.
Constructor & Destructor Documentation
boss_flame_leviathan_defense_turretAI()
boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI::boss_flame_leviathan_defense_turretAI (Creature * creature) inline
Definition at line 789 of file boss_flame_leviathan.cpp.
                                                                   : TurretAI(creature)
         {
             _setHealth = false;
             _instance = creature->GetInstanceScript();
         }
References WorldObject::GetInstanceScript().
Member Function Documentation
CanAIAttack()
bool boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI::CanAIAttack (Unit const * who) const inline override virtual
Reimplemented from TurretAI.
Definition at line 820 of file boss_flame_leviathan.cpp.
         {
             if (!who || who->GetTypeId() != TYPEID_PLAYER || !who->GetVehicle() || who->GetVehicleBase()->GetEntry() != NPC_SEAT)
                 return false;
             return true;
         }
References Object::GetEntry(), Object::GetTypeId(), Unit::GetVehicle(), Unit::GetVehicleBase(), NPC_SEAT, and TYPEID_PLAYER.
DamageTaken()
void boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI::DamageTaken (Unit * who, uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from UnitAI.
Definition at line 798 of file boss_flame_leviathan.cpp.
         {
             if (!CanAIAttack(who))
             {
                 _setHealth = true;
                 damage = 0;
             }
         }
JustDied()
void boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI::JustDied (Unit * who) inline override virtual
Reimplemented from CreatureAI.
Definition at line 807 of file boss_flame_leviathan.cpp.
         {
             if (Player* killer = who->ToPlayer())
                 killer->UpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_GET_KILLING_BLOWS, 1, 0, me);
             if (Vehicle* vehicle = me->GetVehicle())
                 if (Unit* device = vehicle->GetPassenger(SEAT_DEVICE))
                     device->SetUInt32Value(UNIT_FIELD_FLAGS, 0); // unselectable
             if (Creature* leviathan = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(TYPE_LEVIATHAN)))
                 leviathan->AI()->DoAction(ACTION_DESTROYED_TURRET);
         }
References ACHIEVEMENT_CRITERIA_TYPE_GET_KILLING_BLOWS, ACTION_DESTROYED_TURRET, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), SEAT_DEVICE, Object::ToPlayer(), TYPE_LEVIATHAN, and UNIT_FIELD_FLAGS.
KilledUnit()
void boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from CreatureAI.
Definition at line 838 of file boss_flame_leviathan.cpp.
         {
             if (Player* plr = who->ToPlayer()) // make sure that there's no death player on the seat.
                 if (plr->GetVehicle())
                     plr->ExitVehicle();
         }
References Object::ToPlayer().
UpdateAI()
void boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from TurretAI.
Definition at line 827 of file boss_flame_leviathan.cpp.
         {
             if (_setHealth)
             {
                 me->SetHealth(std::min(me->GetHealth() + 1, me->GetMaxHealth()));
                 _setHealth = false;
             }
             TurretAI::UpdateAI(diff);
         }
References diff(), min, and TurretAI::UpdateAI().
Member Data Documentation
_instance
InstanceScript* boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI::_instance
Definition at line 795 of file boss_flame_leviathan.cpp.
_setHealth
bool boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI::_setHealth
Definition at line 797 of file boss_flame_leviathan.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_flame_leviathan.cpp