Azerotcore-wotlk: boss_kologarn::boss_kologarnAI Struct Reference
boss_kologarn::boss_kologarnAI Struct Reference
Public Member Functions
boss_kologarnAI (Creature *pCreature)
void MoveInLineOfSight (Unit *who) override
void EnterEvadeMode () override
void AttachLeftArm ()
void AttachRightArm ()
void Reset () override
void DoAction (int32 param) override
uint32 GetData (uint32 param) const override
void AttackStart (Unit *who) override
void JustSummoned (Creature *cr) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void PassengerBoarded (Unit *who, int8, bool apply) override
== Fields =======================================
void DamageTaken (Unit *who, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void EnterCombat (Unit *) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * m_pInstance
Vehicle * vehicle
ObjectGuid _left
ObjectGuid _right
EventMap events
SummonList summons
Unit * eyebeamTarget
bool _looksAchievement
bool breathReady
uint8 _rubbleAchievement
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 151 of file boss_kologarn.cpp.
Constructor & Destructor Documentation
boss_kologarnAI()
boss_kologarn::boss_kologarnAI::boss_kologarnAI (Creature * pCreature) inline
Definition at line 153 of file boss_kologarn.cpp.
                                              : ScriptedAI(pCreature), vehicle(me->GetVehicleKit()), summons(me), breathReady(false)
         {
             m_pInstance = me->GetInstanceScript();
             eyebeamTarget = nullptr;
             assert(vehicle);
             me->SetStandState(UNIT_STAND_STATE_SUBMERGED);
         }
References assert(), eyebeamTarget, WorldObject::GetInstanceScript(), m_pInstance, ScriptedAI::me, Unit::SetStandState(), UNIT_STAND_STATE_SUBMERGED, and vehicle.
Member Function Documentation
AttachLeftArm()
void boss_kologarn::boss_kologarnAI::AttachLeftArm () inline
Definition at line 196 of file boss_kologarn.cpp.
         {
             if (Unit* arm = ObjectAccessor::GetCreature(*me, _left))
                 arm->SetHealth(arm->GetMaxHealth());
             else if (Creature* accessory = me->SummonCreature(NPC_LEFT_ARM, *me, TEMPSUMMON_MANUAL_DESPAWN))
             {
                 accessory->AddUnitTypeMask(UNIT_MASK_ACCESSORY);
                 if (!me->HandleSpellClick(accessory, 0))
                     accessory->DespawnOrUnsummon();
                 else
                 {
                     _left = accessory->GetGUID();
                     accessory->SetOrientation(M_PI);
                     accessory->CastSpell(accessory, SPELL_ARM_RESPAWN_VISUAL, true);
                 }
             }
         }
References _left, ObjectAccessor::GetCreature(), Unit::HandleSpellClick(), M_PI, ScriptedAI::me, NPC_LEFT_ARM, SPELL_ARM_RESPAWN_VISUAL, WorldObject::SummonCreature(), TEMPSUMMON_MANUAL_DESPAWN, and UNIT_MASK_ACCESSORY.
Referenced by Reset(), and UpdateAI().
AttachRightArm()
void boss_kologarn::boss_kologarnAI::AttachRightArm () inline
Definition at line 214 of file boss_kologarn.cpp.
         {
             if (Unit* arm = ObjectAccessor::GetCreature(*me, _right))
                 arm->SetHealth(arm->GetMaxHealth());
             else if (Creature* accessory = me->SummonCreature(NPC_RIGHT_ARM, *me, TEMPSUMMON_MANUAL_DESPAWN))
             {
                 accessory->AddUnitTypeMask(UNIT_MASK_ACCESSORY);
                 if (!me->HandleSpellClick(accessory, 1))
                     accessory->DespawnOrUnsummon();
                 else
                 {
                     _right = accessory->GetGUID();
                     accessory->SetOrientation(M_PI);
                     accessory->CastSpell(accessory, SPELL_ARM_RESPAWN_VISUAL, true);
                 }
             }
         }
References _right, ObjectAccessor::GetCreature(), Unit::HandleSpellClick(), M_PI, ScriptedAI::me, NPC_RIGHT_ARM, SPELL_ARM_RESPAWN_VISUAL, WorldObject::SummonCreature(), TEMPSUMMON_MANUAL_DESPAWN, and UNIT_MASK_ACCESSORY.
Referenced by Reset(), and UpdateAI().
AttackStart()
void boss_kologarn::boss_kologarnAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 284 of file boss_kologarn.cpp.
         {
             me->Attack(who, true);
         }
References Unit::Attack(), and ScriptedAI::me.
DamageTaken()
void boss_kologarn::boss_kologarnAI::DamageTaken (Unit * who, uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 361 of file boss_kologarn.cpp.
         {
             if (who && who->GetEntry() == me->GetEntry() && me->GetHealth())
             {
                 damage = std::min(damage, me->GetHealth() - 1);
                 me->LowerPlayerDamageReq(damage);
             }
         }
References Object::GetEntry(), Unit::GetHealth(), Creature::LowerPlayerDamageReq(), ScriptedAI::me, and min.
DoAction()
void boss_kologarn::boss_kologarnAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 258 of file boss_kologarn.cpp.
         {
             if (param == DATA_KOLOGARN_LOOKS_ACHIEV)
                 _looksAchievement = false;
             if (param == DATA_KOLOGARN_RUBBLE_ACHIEV)
             {
                 // Means arm died
                 if (m_pInstance && (!_left || !_right))
                     m_pInstance->DoStartTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, ACHIEVEMENT_DISARMED_CRITERIA);
                 ++_rubbleAchievement;
             }
         }
References _left, _looksAchievement, _right, _rubbleAchievement, ACHIEVEMENT_DISARMED_CRITERIA, ACHIEVEMENT_TIMED_TYPE_EVENT, DATA_KOLOGARN_LOOKS_ACHIEV, DATA_KOLOGARN_RUBBLE_ACHIEV, InstanceScript::DoStartTimedAchievement(), and m_pInstance.
EnterCombat()
void boss_kologarn::boss_kologarnAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 370 of file boss_kologarn.cpp.
         {
             if (m_pInstance)
                 m_pInstance->SetData(TYPE_KOLOGARN, IN_PROGRESS);
             events.ScheduleEvent(EVENT_SMASH, 8000);
             events.ScheduleEvent(EVENT_SWEEP, 17000);
             events.ScheduleEvent(EVENT_GRIP, 15000);
             events.ScheduleEvent(EVENT_FOCUSED_EYEBEAM, 10000);
             events.ScheduleEvent(EVENT_PREPARE_BREATH, 3000);
             //events.ScheduleEvent(EVENT_ENRAGE, x); no info
             Talk(SAY_AGGRO);
             me->setActive(true);
             // Close the door inside Kologarn chamber
             if (GameObject* door = me->FindNearestGameObject(GO_KOLOGARN_DOORS, 100.0f))
                 door->SetGoState(GO_STATE_READY);
         }
References EVENT_FOCUSED_EYEBEAM, EVENT_GRIP, EVENT_PREPARE_BREATH, EVENT_SMASH, EVENT_SWEEP, WorldObject::FindNearestGameObject(), GO_KOLOGARN_DOORS, GO_STATE_READY, IN_PROGRESS, m_pInstance, ScriptedAI::me, SAY_AGGRO, WorldObject::setActive(), ZoneScript::SetData(), CreatureAI::Talk(), and TYPE_KOLOGARN.
EnterEvadeMode()
void boss_kologarn::boss_kologarnAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 188 of file boss_kologarn.cpp.
         {
             if (!_EnterEvadeMode())
                 return;
             Reset();
             me->setActive(false);
         }
References CreatureAI::_EnterEvadeMode(), ScriptedAI::me, Reset(), and WorldObject::setActive().
Referenced by UpdateAI().
GetData()
uint32 boss_kologarn::boss_kologarnAI::GetData (uint32 param) const inline override virtual
Reimplemented from UnitAI.
Definition at line 272 of file boss_kologarn.cpp.
         {
             if (param == DATA_KOLOGARN_LOOKS_ACHIEV)
                 return _looksAchievement;
             else if (param == DATA_KOLOGARN_RUBBLE_ACHIEV)
                 return (_rubbleAchievement >= 5);
             else if (param == DATA_KOLOGARN_ARMS_ACHIEV)
                 return !_rubbleAchievement;
             return 0;
         }
References _looksAchievement, _rubbleAchievement, DATA_KOLOGARN_ARMS_ACHIEV, DATA_KOLOGARN_LOOKS_ACHIEV, and DATA_KOLOGARN_RUBBLE_ACHIEV.
JustDied()
void boss_kologarn::boss_kologarnAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 295 of file boss_kologarn.cpp.
         {
             summons.DespawnAll();
             me->StopMoving();
             if (m_pInstance)
                 m_pInstance->SetData(TYPE_KOLOGARN, DONE);
             Talk(SAY_DEATH);
             if (GameObject* bridge = me->FindNearestGameObject(GO_KOLOGARN_BRIDGE, 100))
                 bridge->SetGoState(GO_STATE_READY);
             // Summon Chest
             if (GameObject* go = me->SummonGameObject(RAID_MODE(GO_KOLOGARN_CHEST, GO_KOLOGARN_CHEST_HERO), 1839.62f, -35.98f, 448.81f, 3.6f, 0, 0, 0, 0, 7 * 86400))
             {
                 me->RemoveGameObject(go, false);
                 go->SetSpellId(1); // hack to make it despawn
                 go->SetUInt32Value(GAMEOBJECT_FLAGS, 0);
             }
             if (Creature* arm = ObjectAccessor::GetCreature(*me, _left))
                 arm->DespawnOrUnsummon(3000); // visual
             if (Creature* arm = ObjectAccessor::GetCreature(*me, _right))
                 arm->DespawnOrUnsummon(3000); // visual
         }
References _left, _right, SummonList::DespawnAll(), DONE, WorldObject::FindNearestGameObject(), GAMEOBJECT_FLAGS, ObjectAccessor::GetCreature(), GO_KOLOGARN_BRIDGE, GO_KOLOGARN_CHEST, GO_KOLOGARN_CHEST_HERO, GO_STATE_READY, m_pInstance, ScriptedAI::me, ScriptedAI::RAID_MODE(), Unit::RemoveGameObject(), SAY_DEATH, ZoneScript::SetData(), Unit::StopMoving(), WorldObject::SummonGameObject(), summons, CreatureAI::Talk(), and TYPE_KOLOGARN.
JustSummoned()
void boss_kologarn::boss_kologarnAI::JustSummoned (Creature * cr) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 289 of file boss_kologarn.cpp.
         {
             if (cr->GetEntry() != NPC_LEFT_ARM && cr->GetEntry() != NPC_RIGHT_ARM)
                 summons.Summon(cr);
         }
References Object::GetEntry(), NPC_LEFT_ARM, NPC_RIGHT_ARM, SummonList::Summon(), and summons.
KilledUnit()
void boss_kologarn::boss_kologarnAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 320 of file boss_kologarn.cpp.
         {
             if (!urand(0, 2))
                 return;
             Talk(SAY_SLAY);
         }
References SAY_SLAY, CreatureAI::Talk(), and urand().
MoveInLineOfSight()
void boss_kologarn::boss_kologarnAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
Definition at line 173 of file boss_kologarn.cpp.
         {
             if (who->GetTypeId() == TYPEID_PLAYER && me->GetExactDist2d(who) < 45.0f && me->getStandState() == UNIT_STAND_STATE_SUBMERGED)
             {
                 me->SetStandState(UNIT_STAND_STATE_STAND);
                 if (Unit* arm = ObjectAccessor::GetCreature(*me, _left))
                     arm->CastSpell(arm, SPELL_ARM_RESPAWN_VISUAL, true);
                 if (Unit* arm = ObjectAccessor::GetCreature(*me, _right))
                     arm->CastSpell(arm, SPELL_ARM_RESPAWN_VISUAL, true);
             }
             if (me->GetExactDist2d(who) < 30.0f)
                 ScriptedAI::MoveInLineOfSight(who);
         }
References _left, _right, ObjectAccessor::GetCreature(), Position::GetExactDist2d(), Unit::getStandState(), Object::GetTypeId(), ScriptedAI::me, CreatureAI::MoveInLineOfSight(), Unit::SetStandState(), SPELL_ARM_RESPAWN_VISUAL, TYPEID_PLAYER, UNIT_STAND_STATE_STAND, and UNIT_STAND_STATE_SUBMERGED.
PassengerBoarded()
void boss_kologarn::boss_kologarnAI::PassengerBoarded (Unit * , int8 , bool) inline override virtual
== Fields =======================================
Reimplemented from CreatureAI.
Definition at line 328 of file boss_kologarn.cpp.
         {
             if (!me->IsAlive())
                 return;
             if (!apply)
             {
                 // left arm
                 if (who->GetGUID() == _left)
                 {
                     _left.Clear();
                     if (me->IsInCombat())
                     {
                         Talk(SAY_LEFT_ARM_GONE);
                         events.ScheduleEvent(EVENT_RESTORE_ARM_LEFT, 50000);
                     }
                 }
                 else
                 {
                     _right.Clear();
                     if (me->IsInCombat())
                     {
                         Talk(SAY_RIGHT_ARM_GONE);
                         events.ScheduleEvent(EVENT_RESTORE_ARM_RIGHT, 50000);
                     }
                 }
                 me->CastSpell(me, SPELL_ARM_DEAD, true);
                 if (!_right && !_left)
                     events.ScheduleEvent(EVENT_STONE_SHOUT, 5000);
             }
         }
References _left, _right, ByteConverter::apply(), Unit::CastSpell(), ObjectGuid::Clear(), EVENT_RESTORE_ARM_LEFT, EVENT_RESTORE_ARM_RIGHT, EVENT_STONE_SHOUT, Object::GetGUID(), Unit::IsAlive(), Unit::IsInCombat(), ScriptedAI::me, SAY_LEFT_ARM_GONE, SAY_RIGHT_ARM_GONE, SPELL_ARM_DEAD, and CreatureAI::Talk().
Reset()
void boss_kologarn::boss_kologarnAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 232 of file boss_kologarn.cpp.
         {
             _rubbleAchievement = 0;
             _looksAchievement = true;
             me->SetDisableGravity(true);
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE);
             me->DisableRotate(true);
             events.Reset();
             summons.DespawnAll();
             if (m_pInstance)
                 m_pInstance->SetData(TYPE_KOLOGARN, NOT_STARTED);
             AttachLeftArm();
             AttachRightArm();
             // Reset breath on pull
             breathReady = false;
             // Open the door inside Kologarn chamber
             if (GameObject* door = me->FindNearestGameObject(GO_KOLOGARN_DOORS, 100.0f))
                 door->SetGoState(GO_STATE_ACTIVE);
         }
References _looksAchievement, _rubbleAchievement, AttachLeftArm(), AttachRightArm(), breathReady, SummonList::DespawnAll(), Unit::DisableRotate(), WorldObject::FindNearestGameObject(), GO_KOLOGARN_DOORS, GO_STATE_ACTIVE, m_pInstance, ScriptedAI::me, NOT_STARTED, ZoneScript::SetData(), Creature::SetDisableGravity(), Object::SetFlag(), summons, TYPE_KOLOGARN, UNIT_FIELD_FLAGS, and UNIT_FLAG_DISABLE_MOVE.
Referenced by EnterEvadeMode().
UpdateAI()
void boss_kologarn::boss_kologarnAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 390 of file boss_kologarn.cpp.
         {
             if (!UpdateVictim())
             {
                 EnterEvadeMode();
                 return;
             }
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_PREPARE_BREATH:
                     breathReady = true;
                     break;
                 case EVENT_STONE_SHOUT:
                     if (_left || _right)
                     {
                         return;
                     }
                     me->CastSpell(me->GetVictim(), SPELL_STONE_SHOUT, false);
                     events.ScheduleEvent(EVENT_STONE_SHOUT, 2000);
                     break;
                 case EVENT_SMASH:
                     if (_left && _right)
                         me->CastSpell(me->GetVictim(), SPELL_OVERHEAD_SMASH, false);
                     else if (_left || _right)
                         me->CastSpell(me->GetVictim(), SPELL_ONEARMED_OVERHEAD_SMASH, false);
                     events.DelayEvents(1000);
                     events.ScheduleEvent(EVENT_SMASH, 14000);
                     return;
                 case EVENT_SWEEP:
                     if (_left)
                     {
                         if (Creature* cr = me->FindNearestCreature(NPC_SWEEP_TRIGGER, 300))
                             cr->CastSpell(cr, SPELL_ARM_SWEEP, false);
                         if (urand(0, 1))
                             Talk(SAY_SHOCKWAVE);
                     }
                     events.DelayEvents(1000);
                     events.ScheduleEvent(EVENT_SWEEP, 17000);
                     return;
                 case EVENT_GRIP:
                     events.ScheduleEvent(EVENT_GRIP, 25000);
                     if (!_right)
                         break;
                     me->CastSpell(me, SPELL_STONE_GRIP, false);
                     Talk(SAY_GRAB_PLAYER);
                     Talk(EMOTE_STONE_GRIP);
                     return;
                 case EVENT_FOCUSED_EYEBEAM:
                 {
                     events.ScheduleEvent(EVENT_FOCUSED_EYEBEAM, 20000);
                     if ((eyebeamTarget = SelectTarget(SELECT_TARGET_FARTHEST, 0, 0, true)))
                     {
                         me->CastSpell(eyebeamTarget, SPELL_FOCUSED_EYEBEAM_SUMMON, false);
                     }
                     Talk(EMOTE_EYES);
                     return;
                 }
                 case EVENT_RESTORE_ARM_LEFT:
                     // shouldn't happen
                     AttachLeftArm();
                     return;
                 case EVENT_RESTORE_ARM_RIGHT:
                     // shouldn't happen
                     AttachRightArm();
                     return;
             }
             //Make sure our attack is ready and we aren't currently casting before checking distance
             if (me->isAttackReady() && me->GetVictim()) // victim could die by a spell (IMPORTANT!!!) and kologarn entered evade mode
             {
                 //If we are within range melee the target
                 if (me->IsWithinMeleeRange(me->GetVictim()))
                 {
                     me->AttackerStateUpdate(me->GetVictim());
                     me->resetAttackTimer();
                     return;
                 }
                 else if (Unit* tgt = me->SelectNearbyTarget())
                 {
                     me->AttackerStateUpdate(tgt);
                     me->resetAttackTimer();
                     return;
                 }
                 if (breathReady)
                     me->CastSpell(me->GetVictim(), SPELL_PETRIFYING_BREATH, false);
                 me->resetAttackTimer();
             }
         }
References _left, _right, AttachLeftArm(), AttachRightArm(), Unit::AttackerStateUpdate(), breathReady, Unit::CastSpell(), diff(), EMOTE_EYES, EMOTE_STONE_GRIP, EnterEvadeMode(), EVENT_FOCUSED_EYEBEAM, EVENT_GRIP, EVENT_PREPARE_BREATH, EVENT_RESTORE_ARM_LEFT, EVENT_RESTORE_ARM_RIGHT, EVENT_SMASH, EVENT_STONE_SHOUT, EVENT_SWEEP, eyebeamTarget, WorldObject::FindNearestCreature(), Unit::GetVictim(), Unit::HasUnitState(), Unit::isAttackReady(), Unit::IsWithinMeleeRange(), ScriptedAI::me, NPC_SWEEP_TRIGGER, Unit::resetAttackTimer(), SAY_GRAB_PLAYER, SAY_SHOCKWAVE, SELECT_TARGET_FARTHEST, Unit::SelectNearbyTarget(), UnitAI::SelectTarget(), SPELL_ARM_SWEEP, SPELL_FOCUSED_EYEBEAM_SUMMON, SPELL_ONEARMED_OVERHEAD_SMASH, SPELL_OVERHEAD_SMASH, SPELL_PETRIFYING_BREATH, SPELL_STONE_GRIP, SPELL_STONE_SHOUT, CreatureAI::Talk(), UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
_left
ObjectGuid boss_kologarn::boss_kologarnAI::_left
Definition at line 164 of file boss_kologarn.cpp.
Referenced by AttachLeftArm(), DoAction(), JustDied(), MoveInLineOfSight(), PassengerBoarded(), and UpdateAI().
_looksAchievement
bool boss_kologarn::boss_kologarnAI::_looksAchievement
Definition at line 170 of file boss_kologarn.cpp.
Referenced by DoAction(), GetData(), and Reset().
_right
ObjectGuid boss_kologarn::boss_kologarnAI::_right
Definition at line 164 of file boss_kologarn.cpp.
Referenced by AttachRightArm(), DoAction(), JustDied(), MoveInLineOfSight(), PassengerBoarded(), and UpdateAI().
_rubbleAchievement
uint8 boss_kologarn::boss_kologarnAI::_rubbleAchievement
Definition at line 171 of file boss_kologarn.cpp.
Referenced by DoAction(), GetData(), and Reset().
breathReady
bool boss_kologarn::boss_kologarnAI::breathReady
Definition at line 170 of file boss_kologarn.cpp.
Referenced by Reset(), and UpdateAI().
events
EventMap boss_kologarn::boss_kologarnAI::events
Definition at line 165 of file boss_kologarn.cpp.
eyebeamTarget
Unit* boss_kologarn::boss_kologarnAI::eyebeamTarget
Definition at line 168 of file boss_kologarn.cpp.
Referenced by boss_kologarnAI(), and UpdateAI().
m_pInstance
InstanceScript* boss_kologarn::boss_kologarnAI::m_pInstance
Definition at line 161 of file boss_kologarn.cpp.
Referenced by boss_kologarnAI(), DoAction(), EnterCombat(), JustDied(), and Reset().
summons
SummonList boss_kologarn::boss_kologarnAI::summons
Definition at line 166 of file boss_kologarn.cpp.
Referenced by JustDied(), JustSummoned(), and Reset().
vehicle
Vehicle* boss_kologarn::boss_kologarnAI::vehicle
Definition at line 163 of file boss_kologarn.cpp.
Referenced by boss_kologarnAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_kologarn.cpp