Azerotcore-wotlk: BattlefieldMgr Class Reference
BattlefieldMgr Class Reference
#include <BattlefieldMgr.h>
Public Types
typedef std::vector< Battlefield * > BattlefieldSet
typedef std::map< uint32, Battlefield * > BattlefieldMap
Public Member Functions
BattlefieldMgr ()
~BattlefieldMgr ()
void InitBattlefield ()
void HandlePlayerEnterZone (Player *player, uint32 areaflag)
void HandlePlayerLeaveZone (Player *player, uint32 areaflag)
void HandlePlayerResurrects (Player *player, uint32 areaflag)
Battlefield * GetBattlefieldToZoneId (uint32 zoneid)
Battlefield * GetBattlefieldByBattleId (uint32 battleid)
ZoneScript * GetZoneScript (uint32 zoneId)
void AddZone (uint32 zoneid, Battlefield *handle)
void Update (uint32 diff)
void HandleGossipOption (Player *player, ObjectGuid guid, uint32 gossipid)
bool CanTalkTo (Player *player, Creature *creature, GossipMenuItems gso)
void HandleDropFlag (Player *player, uint32 spellId)
Static Public Member Functions
static BattlefieldMgr * instance ()
Private Attributes
BattlefieldSet m_BattlefieldSet
BattlefieldMap m_BattlefieldMap
uint32 m_UpdateTimer
Detailed Description
Definition at line 30 of file BattlefieldMgr.h.
Member Typedef Documentation
BattlefieldMap
typedef std::map< uint32 , Battlefield* > BattlefieldMgr::BattlefieldMap
Definition at line 65 of file BattlefieldMgr.h.
BattlefieldSet
typedef std::vector< Battlefield* > BattlefieldMgr::BattlefieldSet
Definition at line 64 of file BattlefieldMgr.h.
Constructor & Destructor Documentation
BattlefieldMgr()
BattlefieldMgr::BattlefieldMgr ()
Definition at line 23 of file BattlefieldMgr.cpp.
 {
     m_UpdateTimer = 0;
     //LOG_DEBUG("bg.battlefield", "Instantiating BattlefieldMgr");
 }
References m_UpdateTimer.
~BattlefieldMgr()
BattlefieldMgr::~BattlefieldMgr ()
Definition at line 29 of file BattlefieldMgr.cpp.
 {
     //LOG_DEBUG("bg.battlefield", "Deleting BattlefieldMgr");
     for (BattlefieldSet::iterator itr = m_BattlefieldSet.begin(); itr != m_BattlefieldSet.end(); ++itr)
         delete *itr;
 }
References m_BattlefieldSet.
Member Function Documentation
AddZone()
void BattlefieldMgr::AddZone (uint32 zoneid, Battlefield * handle)
Definition at line 74 of file BattlefieldMgr.cpp.
 {
     m_BattlefieldMap[zoneid] = handle;
 }
References m_BattlefieldMap.
CanTalkTo()
bool BattlefieldMgr::CanTalkTo (Player * player, Creature * creature, GossipMenuItems gso)
GetBattlefieldByBattleId()
Battlefield * BattlefieldMgr::GetBattlefieldByBattleId (uint32 battleid)
Definition at line 118 of file BattlefieldMgr.cpp.
 {
     for (BattlefieldSet::iterator itr = m_BattlefieldSet.begin(); itr != m_BattlefieldSet.end(); ++itr)
     {
         if ((*itr)->GetBattleId() == battleid)
             return (*itr);
     }
     return nullptr;
 }
References m_BattlefieldSet.
GetBattlefieldToZoneId()
Battlefield * BattlefieldMgr::GetBattlefieldToZoneId (uint32 zoneid)
Definition at line 105 of file BattlefieldMgr.cpp.
 {
     BattlefieldMap::iterator itr = m_BattlefieldMap.find(zoneid);
     if (itr == m_BattlefieldMap.end())
     {
         // no handle for this zone, return
         return nullptr;
     }
     if (!itr->second->IsEnabled())
         return nullptr;
     return itr->second;
 }
References m_BattlefieldMap.
GetZoneScript()
ZoneScript * BattlefieldMgr::GetZoneScript (uint32 zoneId)
Definition at line 140 of file BattlefieldMgr.cpp.
 {
     BattlefieldMap::iterator itr = m_BattlefieldMap.find(zoneId);
     if (itr != m_BattlefieldMap.end())
         return itr->second;
     else
         return nullptr;
 }
References m_BattlefieldMap.
HandleDropFlag()
void BattlefieldMgr::HandleDropFlag (Player * player, uint32 spellId)
HandleGossipOption()
void BattlefieldMgr::HandleGossipOption (Player * player, ObjectGuid guid, uint32 gossipid)
HandlePlayerEnterZone()
void BattlefieldMgr::HandlePlayerEnterZone (Player * player, uint32 areaflag)
Definition at line 79 of file BattlefieldMgr.cpp.
 {
     BattlefieldMap::iterator itr = m_BattlefieldMap.find(zoneid);
     if (itr == m_BattlefieldMap.end())
         return;
     if (itr->second->HasPlayer(player) || !itr->second->IsEnabled())
         return;
     itr->second->HandlePlayerEnterZone(player, zoneid);
     LOG_DEBUG("bg.battlefield", "Player %s entered outdoorpvp id %u", player->GetGUID().ToString().c_str(), itr->second->GetTypeId());
 }
References Object::GetGUID(), LOG_DEBUG, m_BattlefieldMap, and ObjectGuid::ToString().
HandlePlayerLeaveZone()
void BattlefieldMgr::HandlePlayerLeaveZone (Player * player, uint32 areaflag)
Definition at line 92 of file BattlefieldMgr.cpp.
 {
     BattlefieldMap::iterator itr = m_BattlefieldMap.find(zoneid);
     if (itr == m_BattlefieldMap.end())
         return;
     // teleport: remove once in removefromworld, once in updatezone
     if (!itr->second->HasPlayer(player))
         return;
     itr->second->HandlePlayerLeaveZone(player, zoneid);
     LOG_DEBUG("bg.battlefield", "Player %s left outdoorpvp id %u", player->GetGUID().ToString().c_str(), itr->second->GetTypeId());
 }
References Object::GetGUID(), LOG_DEBUG, m_BattlefieldMap, and ObjectGuid::ToString().
HandlePlayerResurrects()
void BattlefieldMgr::HandlePlayerResurrects (Player * player, uint32 areaflag)
InitBattlefield()
void BattlefieldMgr::InitBattlefield ()
Definition at line 42 of file BattlefieldMgr.cpp.
 {
     Battlefield* pBf = new BattlefieldWG;
     // respawn, init variables
     if (!pBf->SetupBattlefield())
     {
         LOG_ERROR("server.loading", "Battlefield: Wintergrasp init failed.");
         LOG_INFO("server.loading", " ");
         delete pBf;
     }
     else
     {
         m_BattlefieldSet.push_back(pBf);
         LOG_INFO("server.loading", "Battlefield: Wintergrasp successfully initiated.");
         LOG_INFO("server.loading", " ");
     }
     /* For Cataclysm: Tol Barad
        pBf = new BattlefieldTB;
        // respawn, init variables
        if(!pBf->SetupBattlefield())
        {
        LOG_DEBUG("bg.battlefield", "Battlefield : Tol Barad init failed.");
        delete pBf;
        }
        else
        {
        m_BattlefieldSet.push_back(pBf);
        LOG_DEBUG("bg.battlefield", "Battlefield : Tol Barad successfully initiated.");
        } */
 }
References LOG_ERROR, LOG_INFO, m_BattlefieldSet, and Battlefield::SetupBattlefield().
instance()
BattlefieldMgr * BattlefieldMgr::instance () static
Definition at line 36 of file BattlefieldMgr.cpp.
 {
     static BattlefieldMgr instance;
     return &instance;
 }
References instance().
Referenced by instance().
Update()
void BattlefieldMgr::Update (uint32 diff)
Definition at line 128 of file BattlefieldMgr.cpp.
 {
     m_UpdateTimer += diff;
     if (m_UpdateTimer > BATTLEFIELD_OBJECTIVE_UPDATE_INTERVAL)
     {
         for (BattlefieldSet::iterator itr = m_BattlefieldSet.begin(); itr != m_BattlefieldSet.end(); ++itr)
             //if ((*itr)->IsEnabled())
             (*itr)->Update(m_UpdateTimer);
         m_UpdateTimer = 0;
     }
 }
References BATTLEFIELD_OBJECTIVE_UPDATE_INTERVAL, m_BattlefieldSet, and m_UpdateTimer.
Member Data Documentation
m_BattlefieldMap
BattlefieldMap BattlefieldMgr::m_BattlefieldMap private
Definition at line 72 of file BattlefieldMgr.h.
Referenced by AddZone(), GetBattlefieldToZoneId(), GetZoneScript(), HandlePlayerEnterZone(), and HandlePlayerLeaveZone().
m_BattlefieldSet
BattlefieldSet BattlefieldMgr::m_BattlefieldSet private
Definition at line 69 of file BattlefieldMgr.h.
Referenced by GetBattlefieldByBattleId(), InitBattlefield(), Update(), and ~BattlefieldMgr().
m_UpdateTimer
uint32 BattlefieldMgr::m_UpdateTimer private
Definition at line 74 of file BattlefieldMgr.h.
Referenced by BattlefieldMgr(), and Update().
The documentation for this class was generated from the following files:
src/server/game/Battlefield/BattlefieldMgr.h
src/server/game/Battlefield/BattlefieldMgr.cpp