Azerotcore-wotlk: spell_quest_test_flight_charging Class Reference
spell_quest_test_flight_charging Class Reference
Private Member Functions
PrepareAuraScript (spell_quest_test_flight_charging) void OnApplySelf(AuraEffect const *
GetTarget () -> CastSpell(GetTarget(), SPELL_CANNON_CHARGING_PORT, true)
void PerformKick ()
void HandleEffectPeriodicSelf (AuraEffect const *aurEff)
void HandleEffectPeriodicPlatform (AuraEffect const *aurEff)
void Register () override
Private Attributes
AuraEffectHandleModes
Additional Inherited Members
Public Member Functions inherited from AuraScript
AuraScript ()
bool _Validate (SpellInfo const *entry) override
bool _Load (Aura *aura)
void _PrepareScriptCall (AuraScriptHookType hookType, AuraApplication const *aurApp=nullptr)
void _FinishScriptCall ()
bool _IsDefaultActionPrevented ()
void PreventDefaultAction ()
SpellInfo const * GetSpellInfo () const
uint32 GetId () const
ObjectGuid GetCasterGUID () const
Unit * GetCaster () const
WorldObject * GetOwner () const
Unit * GetUnitOwner () const
DynamicObject * GetDynobjOwner () const
void Remove (uint32 removeMode=0)
Aura * GetAura () const
AuraObjectType GetType () const
int32 GetDuration () const
void SetDuration (int32 duration, bool withMods=false)
void RefreshDuration ()
time_t GetApplyTime () const
int32 GetMaxDuration () const
void SetMaxDuration (int32 duration)
int32 CalcMaxDuration () const
bool IsExpired () const
bool IsPermanent () const
uint8 GetCharges () const
void SetCharges (uint8 charges)
uint8 CalcMaxCharges () const
bool ModCharges (int8 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool DropCharge (AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
uint8 GetStackAmount () const
void SetStackAmount (uint8 num)
bool ModStackAmount (int32 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool IsPassive () const
bool IsDeathPersistent () const
bool HasEffect (uint8 effIndex) const
AuraEffect * GetEffect (uint8 effIndex) const
bool HasEffectType (AuraType type) const
Unit * GetTarget () const
AuraApplication const * GetTargetApplication () const
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from AuraScript
HookList< CheckAreaTargetHandler > DoCheckAreaTarget
HookList< AuraDispelHandler > OnDispel
HookList< AuraDispelHandler > AfterDispel
HookList< EffectApplyHandler > OnEffectApply
HookList< EffectApplyHandler > AfterEffectApply
HookList< EffectApplyHandler > OnEffectRemove
HookList< EffectApplyHandler > AfterEffectRemove
HookList< EffectPeriodicHandler > OnEffectPeriodic
HookList< EffectUpdatePeriodicHandler > OnEffectUpdatePeriodic
HookList< EffectCalcAmountHandler > DoEffectCalcAmount
HookList< EffectCalcPeriodicHandler > DoEffectCalcPeriodic
HookList< EffectCalcSpellModHandler > DoEffectCalcSpellMod
HookList< EffectAbsorbHandler > OnEffectAbsorb
HookList< EffectAbsorbHandler > AfterEffectAbsorb
HookList< EffectManaShieldHandler > OnEffectManaShield
HookList< EffectManaShieldHandler > AfterEffectManaShield
HookList< EffectSplitHandler > OnEffectSplit
HookList< CheckProcHandler > DoCheckProc
HookList< AuraProcHandler > DoPrepareProc
HookList< AuraProcHandler > OnProc
HookList< AuraProcHandler > AfterProc
HookList< EffectProcHandler > OnEffectProc
HookList< EffectProcHandler > AfterEffectProc
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Definition at line 573 of file spell_quest.cpp.
Member Function Documentation
GetTarget()
spell_quest_test_flight_charging::GetTarget () -> CastSpell(GetTarget(), SPELL_CANNON_CHARGING_PORT, true) private
Referenced by HandleEffectPeriodicPlatform(), HandleEffectPeriodicSelf(), and PerformKick().
HandleEffectPeriodicPlatform()
void spell_quest_test_flight_charging::HandleEffectPeriodicPlatform (AuraEffect const * aurEff) inline private
Definition at line 630 of file spell_quest.cpp.
     {
         if (aurEff->GetTickNumber() == 1)
             GetTarget()->CastSpell(GetTarget(), SPELL_CANNON_CHARGING_STATE2, true);
         else if (aurEff->GetTickNumber() == 2)
             GetTarget()->CastSpell(GetTarget(), SPELL_CANNON_CHARGING_STATE3, true);
         else if (aurEff->GetTickNumber() == 3)
             GetTarget()->CastSpell(GetTarget(), SPELL_CANNON_CHARGING_STATE4, true);
         else if (aurEff->GetTickNumber() == 5)
             GetTarget()->CastSpell(GetTarget(), SPELL_TELEPORT_VISUAL, true);
     }
References GetTarget(), AuraEffect::GetTickNumber(), SPELL_CANNON_CHARGING_STATE2, SPELL_CANNON_CHARGING_STATE3, SPELL_CANNON_CHARGING_STATE4, and SPELL_TELEPORT_VISUAL.
Referenced by Register().
HandleEffectPeriodicSelf()
void spell_quest_test_flight_charging::HandleEffectPeriodicSelf (AuraEffect const * aurEff) inline private
Definition at line 618 of file spell_quest.cpp.
     {
         if (aurEff->GetTickNumber() == 1)
         {
             GetTarget()->SummonCreature(NPC_CANNON_TARGET, 1919.99f, 5581.97f, 272.30f, 5.27f, TEMPSUMMON_TIMED_DESPAWN, 12000);
             if (Creature* cannon = GetTarget()->FindNearestCreature(NPC_CANNON, 40.0f))
                 cannon->CastSpell(cannon, SPELL_CANNON_CHANNEL, false);
         }
         if (aurEff->GetTickNumber() == 6)
             PerformKick();
     }
References GetTarget(), AuraEffect::GetTickNumber(), NPC_CANNON, NPC_CANNON_TARGET, PerformKick(), SPELL_CANNON_CHANNEL, and TEMPSUMMON_TIMED_DESPAWN.
Referenced by Register().
PerformKick()
void spell_quest_test_flight_charging::PerformKick () inline private
Definition at line 583 of file spell_quest.cpp.
     {
         if (Player* player = GetTarget()->ToPlayer())
         {
             Creature* shooter = player->FindNearestCreature(NPC_GNOME_SHOOTER, 20.0f);
             if (!shooter)
                 return;
             uint8 task = 0;
             uint32 spellId = 0;
             for (; task < 4; ++task)
                 if (shooter->GetDistance(ShooterPos[task]) < 1.0f)
                     break;
             switch (task)
             {
                 case 0:
                     spellId = SPELL_SOARING_10557;
                     break;
                 case 1:
                     spellId = SPELL_SOARING_10710;
                     break;
                 case 2:
                     spellId = SPELL_SOARING_10711;
                     break;
                 case 3:
                     spellId = SPELL_SOARING_10712;
                     break;
             }
             player->RemoveAurasDueToSpell(SPELL_CANNON_CHARGING_PORT);
             shooter->CastSpell(player, spellId, true);
         }
     }
References Unit::CastSpell(), WorldObject::FindNearestCreature(), WorldObject::GetDistance(), GetTarget(), NPC_GNOME_SHOOTER, ShooterPos, SPELL_CANNON_CHARGING_PORT, SPELL_SOARING_10557, SPELL_SOARING_10710, SPELL_SOARING_10711, and SPELL_SOARING_10712.
Referenced by HandleEffectPeriodicSelf().
PrepareAuraScript()
spell_quest_test_flight_charging::PrepareAuraScript (spell_quest_test_flight_charging) const private
Register()
void spell_quest_test_flight_charging::Register () inline override private virtual
Implements _SpellScript.
Definition at line 642 of file spell_quest.cpp.
     {
         if (m_scriptSpellId == SPELL_CANNON_CHARGING_SELF)
         {
             OnEffectApply += AuraEffectApplyFn(spell_quest_test_flight_charging::OnApplySelf, EFFECT_0, SPELL_AURA_PERIODIC_TRIGGER_SPELL, AURA_EFFECT_HANDLE_REAL);
             OnEffectPeriodic += AuraEffectPeriodicFn(spell_quest_test_flight_charging::HandleEffectPeriodicSelf, EFFECT_0, SPELL_AURA_PERIODIC_TRIGGER_SPELL);
         }
         else
             OnEffectPeriodic += AuraEffectPeriodicFn(spell_quest_test_flight_charging::HandleEffectPeriodicPlatform, EFFECT_0, SPELL_AURA_PERIODIC_TRIGGER_SPELL);
     }
References AURA_EFFECT_HANDLE_REAL, AuraEffectApplyFn, AuraEffectPeriodicFn, EFFECT_0, HandleEffectPeriodicPlatform(), HandleEffectPeriodicSelf(), _SpellScript::m_scriptSpellId, AuraScript::OnEffectApply, AuraScript::OnEffectPeriodic, SPELL_AURA_PERIODIC_TRIGGER_SPELL, and SPELL_CANNON_CHARGING_SELF.
Member Data Documentation
AuraEffectHandleModes
spell_quest_test_flight_charging::AuraEffectHandleModes private
Initial value:
{
        GetTarget()->CastSpell(GetTarget(), SPELL_TELEPORT_VISUAL, true)
Definition at line 577 of file spell_quest.cpp.
The documentation for this class was generated from the following file:
src/server/scripts/Spells/spell_quest.cpp