Azerotcore-wotlk: boss_twin_valkyrAI Struct Reference
boss_twin_valkyrAI Struct Reference
Public Member Functions
boss_twin_valkyrAI (Creature *pCreature)
void DoAction (int32 a) override
Creature * GetSister ()
void EnterCombat (Unit *) override
void JustReachedHome () override
void myDoMeleeAttackIfReady ()
void UpdateSharedHealth ()
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void JustSummoned (Creature *s) override
void SummonedCreatureDespawn (Creature *s) override
void KilledUnit (Unit *who) override
void EnterEvadeMode () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
SummonList summons
EventMap events
int32 LastSynchroHP
uint8 SpecialMask
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 107 of file boss_twin_valkyr.cpp.
Constructor & Destructor Documentation
boss_twin_valkyrAI()
boss_twin_valkyrAI::boss_twin_valkyrAI (Creature * pCreature) inline
Definition at line 109 of file boss_twin_valkyr.cpp.
                                             : ScriptedAI(pCreature), summons(me)
     {
         pInstance = pCreature->GetInstanceScript();
         me->SetReactState(REACT_PASSIVE);
         me->SetModifierValue(UNIT_MOD_DAMAGE_OFFHAND, TOTAL_PCT, 1.0f);
         me->UpdateDamagePhysical(OFF_ATTACK);
         LastSynchroHP = (int32)me->GetMaxHealth();
         SpecialMask = 0;
         me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_HASTE_SPELLS, true);
         events.Reset();
         if( me->GetEntry() == NPC_LIGHTBANE )
         {
             if( pInstance )
                 pInstance->DoStopTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, 21853);
             // special events here
             events.RescheduleEvent(EVENT_BERSERK, IsHeroic() ? 360000 : 600000);
             events.RescheduleEvent(EVENT_SUMMON_BALLS_1, urand(10000, 15000));
             events.RescheduleEvent(EVENT_SPECIAL, 45000);
         }
         events.RescheduleEvent(EVENT_SPELL_SPIKE, urand(5000, 8000));
         if( IsHeroic() )
             events.RescheduleEvent(EVENT_SPELL_TOUCH, urand(10000, 25000), 1);
         me->SetCanFly(true);
         me->SetDisableGravity(true);
     }
References ACHIEVEMENT_TIMED_TYPE_EVENT, Unit::ApplySpellImmune(), InstanceScript::DoStopTimedAchievement(), EVENT_BERSERK, EVENT_SPECIAL, EVENT_SPELL_SPIKE, EVENT_SPELL_TOUCH, EVENT_SUMMON_BALLS_1, Object::GetEntry(), WorldObject::GetInstanceScript(), Unit::GetMaxHealth(), IMMUNITY_STATE, ScriptedAI::IsHeroic(), LastSynchroHP, ScriptedAI::me, NPC_LIGHTBANE, OFF_ATTACK, pInstance, REACT_PASSIVE, Creature::SetCanFly(), Creature::SetDisableGravity(), Unit::SetModifierValue(), Creature::SetReactState(), SpecialMask, SPELL_AURA_HASTE_SPELLS, TOTAL_PCT, UNIT_MOD_DAMAGE_OFFHAND, Unit::UpdateDamagePhysical(), and urand().
Member Function Documentation
DoAction()
void boss_twin_valkyrAI::DoAction (int32 a) inline override virtual
Reimplemented from UnitAI.
Definition at line 144 of file boss_twin_valkyr.cpp.
     {
         switch( a )
         {
             case -1:
                 summons.DespawnAll();
                 if( pInstance && me->GetEntry() == NPC_LIGHTBANE )
                 {
                     uint32 essenceId1 = 0, empoweredId1 = 0, touchId1 = 0, essenceId2 = 0, empoweredId2 = 0, touchId2 = 0;
                     switch( me->GetMap()->GetDifficulty() )
                     {
                         case 0:
                             essenceId1 = 65684;
                             empoweredId1 = 65724;
                             touchId1 = 65950;
                             essenceId2 = 65686;
                             empoweredId2 = 65748;
                             touchId2 = 66001;
                             break;
                         case 1:
                             essenceId1 = 67176;
                             empoweredId1 = 67213;
                             touchId1 = 67296;
                             essenceId2 = 67222;
                             empoweredId2 = 67216;
                             touchId2 = 67281;
                             break;
                         case 2:
                             essenceId1 = 67177;
                             empoweredId1 = 67214;
                             touchId1 = 67297;
                             essenceId2 = 67223;
                             empoweredId2 = 67217;
                             touchId2 = 67282;
                             break;
                         case 3:
                             essenceId1 = 67178;
                             empoweredId1 = 67215;
                             touchId1 = 67298;
                             essenceId2 = 67224;
                             empoweredId2 = 67218;
                             touchId2 = 67283;
                             break;
                     }
                     pInstance->DoRemoveAurasDueToSpellOnPlayers(essenceId1);
                     pInstance->DoRemoveAurasDueToSpellOnPlayers(empoweredId1);
                     pInstance->DoRemoveAurasDueToSpellOnPlayers(touchId1);
                     pInstance->DoRemoveAurasDueToSpellOnPlayers(essenceId2);
                     pInstance->DoRemoveAurasDueToSpellOnPlayers(empoweredId2);
                     pInstance->DoRemoveAurasDueToSpellOnPlayers(touchId2);
                 }
                 break;
             case -3:
                 me->SetCanDualWield(true);
                 me->CastSpell(me, SPELL_TWIN_POWER, true);
                 events.RescheduleEvent(EVENT_REMOVE_DUAL_WIELD, 15000);
                 break;
         }
     }
References Unit::CastSpell(), SummonList::DespawnAll(), InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), EVENT_REMOVE_DUAL_WIELD, Map::GetDifficulty(), Object::GetEntry(), WorldObject::GetMap(), ScriptedAI::me, NPC_LIGHTBANE, pInstance, Creature::SetCanDualWield(), SPELL_TWIN_POWER, and summons.
Referenced by JustDied(), and UpdateAI().
EnterCombat()
void boss_twin_valkyrAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 215 of file boss_twin_valkyr.cpp.
     {
         me->setActive(true);
         me->LowerPlayerDamageReq(me->GetMaxHealth());
         DoZoneInCombat();
         if( Creature* twin = GetSister() )
             if( !twin->IsInCombat() )
                 if( Unit* target = twin->SelectNearestTarget(200.0f) )
                     twin->AI()->AttackStart(target);
         Talk(SAY_AGGRO);
         me->CastSpell(me, me->GetEntry() == NPC_LIGHTBANE ? SPELL_LIGHT_SURGE : SPELL_DARK_SURGE, true);
         if( pInstance && me->GetEntry() == NPC_LIGHTBANE )
             pInstance->DoStartTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, 21853);
     }
References ACHIEVEMENT_TIMED_TYPE_EVENT, Unit::CastSpell(), InstanceScript::DoStartTimedAchievement(), CreatureAI::DoZoneInCombat(), Object::GetEntry(), Unit::GetMaxHealth(), GetSister(), Creature::LowerPlayerDamageReq(), ScriptedAI::me, NPC_LIGHTBANE, pInstance, SAY_AGGRO, WorldObject::setActive(), SPELL_DARK_SURGE, SPELL_LIGHT_SURGE, and CreatureAI::Talk().
EnterEvadeMode()
void boss_twin_valkyrAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 512 of file boss_twin_valkyr.cpp.
     {
         if( pInstance )
             pInstance->SetData(TYPE_FAILED, 0);
     }
References pInstance, ZoneScript::SetData(), and TYPE_FAILED.
GetSister()
Creature* boss_twin_valkyrAI::GetSister () inline
Definition at line 204 of file boss_twin_valkyr.cpp.
     {
         return ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(me->GetEntry() == NPC_DARKBANE ? NPC_LIGHTBANE : NPC_DARKBANE));
     }
References ObjectAccessor::GetCreature(), Object::GetEntry(), InstanceScript::GetGuidData(), ScriptedAI::me, NPC_DARKBANE, NPC_LIGHTBANE, and pInstance.
Referenced by EnterCombat(), JustDied(), KilledUnit(), UpdateAI(), and UpdateSharedHealth().
JustDied()
void boss_twin_valkyrAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 474 of file boss_twin_valkyr.cpp.
     {
         DoAction(-1);
         Talk(SAY_DEATH);
         if( pInstance )
         {
             pInstance->SetData(TYPE_VALKYR, DONE);
             pInstance->DoRemoveAurasDueToSpellOnPlayers(SPELL_POWERING_UP);
         }
         if( Creature* twin = GetSister() )
             if( twin->IsAlive() )
             {
                 twin->SetHealth(1);
                 Unit::Kill(twin, twin);
             }
     }
References DoAction(), DONE, InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), GetSister(), Unit::Kill(), pInstance, SAY_DEATH, ZoneScript::SetData(), SPELL_POWERING_UP, CreatureAI::Talk(), and TYPE_VALKYR.
JustReachedHome()
void boss_twin_valkyrAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 232 of file boss_twin_valkyr.cpp.
     {
         me->setActive(false);
     }
References ScriptedAI::me, and WorldObject::setActive().
JustSummoned()
void boss_twin_valkyrAI::JustSummoned (Creature * s) inline override virtual
Reimplemented from ScriptedAI.
Reimplemented in boss_fjola::boss_fjolaAI, and boss_eydis::boss_eydisAI.
Definition at line 491 of file boss_twin_valkyr.cpp.
     {
         summons.Summon(s);
     }
References SummonList::Summon(), and summons.
Referenced by boss_eydis::boss_eydisAI::boss_eydisAI(), boss_fjola::boss_fjolaAI::boss_fjolaAI(), and UpdateAI().
KilledUnit()
void boss_twin_valkyrAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 501 of file boss_twin_valkyr.cpp.
     {
         if( who->GetTypeId() == TYPEID_PLAYER )
         {
             int32 id = urand(0, 1) ? SAY_KILL_PLAYER_1 : SAY_KILL_PLAYER_2;
             Talk(id);
             if( Creature* twin = GetSister() )
                 twin->AI()->Talk(id);
         }
     }
References GetSister(), Object::GetTypeId(), SAY_KILL_PLAYER_1, SAY_KILL_PLAYER_2, CreatureAI::Talk(), TYPEID_PLAYER, and urand().
myDoMeleeAttackIfReady()
void boss_twin_valkyrAI::myDoMeleeAttackIfReady () inline
Definition at line 237 of file boss_twin_valkyr.cpp.
     {
         DoMeleeAttackIfReady();
         return;
         if (me->HasUnitState(UNIT_STATE_CASTING))
             return;
         Unit* victim = me->GetVictim();
         if (!victim || !victim->IsInWorld())
             return;
         float allowedDist = sqrt(MELEE_RANGE * MELEE_RANGE + 6.0f * 6.0f);
         if (!me->IsWithinMeleeRange(victim, allowedDist))
             return;
         if (me->isAttackReady())
         {
             me->AttackerStateUpdate(victim);
             me->resetAttackTimer();
         }
         if (me->haveOffhandWeapon() && me->isAttackReady(OFF_ATTACK))
         {
             me->AttackerStateUpdate(victim, OFF_ATTACK);
             me->resetAttackTimer(OFF_ATTACK);
         }
     }
References Unit::AttackerStateUpdate(), UnitAI::DoMeleeAttackIfReady(), Unit::GetVictim(), Unit::HasUnitState(), Unit::haveOffhandWeapon(), Unit::isAttackReady(), Object::IsInWorld(), Unit::IsWithinMeleeRange(), ScriptedAI::me, MELEE_RANGE, OFF_ATTACK, Unit::resetAttackTimer(), and UNIT_STATE_CASTING.
Referenced by UpdateAI().
SummonedCreatureDespawn()
void boss_twin_valkyrAI::SummonedCreatureDespawn (Creature * s) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 496 of file boss_twin_valkyr.cpp.
     {
         summons.Despawn(s);
     }
References SummonList::Despawn(), and summons.
UpdateAI()
void boss_twin_valkyrAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 283 of file boss_twin_valkyr.cpp.
     {
         if( !UpdateVictim() )
             return;
         UpdateSharedHealth();
         events.Update(diff);
         if( me->HasUnitState(UNIT_STATE_CASTING) )
             return;
         uint8 eventId = events.ExecuteEvent();
         switch(eventId)
         {
             case 0:
                 break;
             case EVENT_BERSERK:
                 me->CastSpell(me, SPELL_BERSERK, true);
                 Talk(SAY_BERSERK);
                 if( Creature* twin = GetSister() )
                 {
                     twin->CastSpell(twin, SPELL_BERSERK, true);
                     twin->AI()->Talk(SAY_BERSERK);
                 }
                 break;
             case EVENT_SUMMON_BALLS_1:
             case EVENT_SUMMON_BALLS_2:
             case EVENT_SUMMON_BALLS_3:
                 {
                     uint8 count = 0;
                     if( IsHeroic() )
                         count = eventId == EVENT_SUMMON_BALLS_3 ? 36 : 6;
                     else
                         count = eventId == EVENT_SUMMON_BALLS_3 ? 24 : 4;
                     for( uint8 i = 0; i < count; ++i )
                     {
                         float angle = rand_norm() * 2 * M_PI;
                         if( Creature* ball = me->SummonCreature((i % 2) ? NPC_CONCENTRATED_DARK : NPC_CONCENTRATED_LIGHT, Locs[LOC_CENTER].GetPositionX() + cos(angle) * 47.0f, Locs[LOC_CENTER].GetPositionY() + sin(angle) * 47.0f, Locs[LOC_CENTER].GetPositionZ() + 1.5f, 0.0f, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 1500) )
                             boss_twin_valkyrAI::JustSummoned(ball);
                     }
                     switch( eventId )
                     {
                         case EVENT_SUMMON_BALLS_1:
                             events.RescheduleEvent(EVENT_SUMMON_BALLS_2, 8000);
                             break;
                         case EVENT_SUMMON_BALLS_2:
                             events.RescheduleEvent(EVENT_SUMMON_BALLS_3, 8000);
                             break;
                         case EVENT_SUMMON_BALLS_3:
                             events.RescheduleEvent(EVENT_SUMMON_BALLS_1, 15000);
                             break;
                     }
                 }
                 break;
             case EVENT_SPELL_SPIKE:
                 me->CastSpell(me->GetVictim(), me->GetEntry() == NPC_LIGHTBANE ? SPELL_LIGHT_TWIN_SPIKE : SPELL_DARK_TWIN_SPIKE, false);
                 events.RepeatEvent(urand(7000, 10000));
                 break;
             case EVENT_SPELL_TOUCH:
                 {
                     uint32 essenceId = 0;
                     switch( me->GetEntry() )
                     {
                         case NPC_LIGHTBANE:
                             switch( GetDifficulty() )
{
                                 case 0:
                                     essenceId = 65684;
                                     break;
                                 case 1:
                                     essenceId = 67176;
                                     break;
                                 case 2:
                                     essenceId = 67177;
                                     break;
                                 case 3:
                                     essenceId = 67178;
                                     break;
                             }
                             break;
                         case NPC_DARKBANE:
                             switch( GetDifficulty() )
{
                                 case 0:
                                     essenceId = 65686;
                                     break;
                                 case 1:
                                     essenceId = 67222;
                                     break;
                                 case 2:
                                     essenceId = 67223;
                                     break;
                                 case 3:
                                     essenceId = 67224;
                                     break;
                             }
                             break;
                     }
                     /*
                     if( Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 0.0f, true, essenceId) )
                         me->CastSpell(target, me->GetEntry()==NPC_LIGHTBANE ? SPELL_LIGHT_TOUCH : SPELL_DARK_TOUCH, false);
                     events.RepeatEvent(urand(45000,50000));
                     */
                     GuidVector tList;
                     Map::PlayerList const& pList = me->GetMap()->GetPlayers();
                     if (pList.getSize())
                     {
                         for (Map::PlayerList::const_iterator itr = pList.begin(); itr != pList.end(); ++itr)
                             if (Player* plr = itr->GetSource())
                                 if (Creature* sister = GetSister())
                                     if ((!me->GetVictim() || me->GetVictim()->GetGUID() != plr->GetGUID()) && (!sister->GetVictim() || sister->GetVictim()->GetGUID() != plr->GetGUID()) && plr->HasAura(essenceId))
                                         tList.push_back(plr->GetGUID());
                         if (!tList.empty())
                             if (Player* target = ObjectAccessor::GetPlayer(*me, tList[urand(0, tList.size() - 1)]))
{
                                 me->CastSpell(target, me->GetEntry() == NPC_LIGHTBANE ? SPELL_LIGHT_TOUCH : SPELL_DARK_TOUCH, false);
                                 events.RepeatEvent(urand(45000, 50000));
                                 break;
                             }
                     }
                     events.RepeatEvent(10000);
                 }
                 break;
             case EVENT_SPECIAL:
                 {
                     uint8 s;
                     do s = urand(0, 3);
                     while( SpecialMask & (1 << s) && (SpecialMask & 0xF) != 0xF );
                     SpecialMask |= (1 << s);
                     switch( s )
                     {
                         case 0: // light vortex
                             me->CastSpell((Unit*)nullptr, SPELL_LIGHT_VORTEX, false);
                             Talk(EMOTE_VORTEX);
                             Talk(SAY_LIGHT);
                             if( Creature* twin = GetSister() )
                                 twin->AI()->Talk(SAY_LIGHT);
                             break;
                         case 1: // dark vortex
                             if( Creature* twin = GetSister() )
{
                                 twin->CastSpell((Unit*)nullptr, SPELL_DARK_VORTEX, false);
                                 twin->AI()->Talk(EMOTE_VORTEX);
                                 twin->AI()->Talk(SAY_NIGHT);
                                 Talk(SAY_NIGHT);
                             }
                             break;
                         case 2: // light pact
                             Talk(EMOTE_TWINK_PACT);
                             Talk(SAY_TWINK_PACT);
                             if( Creature* twin = GetSister() )
{
                                 twin->AI()->Talk(SAY_TWINK_PACT);
                                 twin->AI()->DoAction(-3);
                             }
                             me->CastSpell(me, SPELL_LIGHT_SHIELD, true);
                             me->CastSpell(me, SPELL_LIGHT_TWIN_PACT, false);
                             break;
                         case 3: // dark pact
                             if( Creature* twin = GetSister() )
{
                                 twin->AI()->Talk(EMOTE_TWINK_PACT);
                                 twin->AI()->Talk(SAY_TWINK_PACT);
                                 Talk(SAY_TWINK_PACT);
                                 twin->CastSpell(twin, SPELL_DARK_SHIELD, true);
                                 twin->CastSpell(twin, SPELL_DARK_TWIN_PACT, false);
                                 DoAction(-3);
                             }
                             break;
                     }
                     if( (SpecialMask & 0xF) == 0xF )
                         SpecialMask = 0;
                     events.RepeatEvent(45000);
                     events.DelayEventsToMax(15000, 1); // no touch of light/darkness during special abilities!
                 }
                 break;
             case EVENT_REMOVE_DUAL_WIELD:
                 me->SetCanDualWield(false);
                 break;
         }
         myDoMeleeAttackIfReady();
     }
References MapRefMgr::begin(), Unit::CastSpell(), DoAction(), EMOTE_TWINK_PACT, EMOTE_VORTEX, MapRefMgr::end(), EVENT_BERSERK, EVENT_REMOVE_DUAL_WIELD, EVENT_SPECIAL, EVENT_SPELL_SPIKE, EVENT_SPELL_TOUCH, EVENT_SUMMON_BALLS_1, EVENT_SUMMON_BALLS_2, EVENT_SUMMON_BALLS_3, ScriptedAI::GetDifficulty(), Object::GetEntry(), Object::GetGUID(), WorldObject::GetMap(), ObjectAccessor::GetPlayer(), Map::GetPlayers(), Position::GetPositionX(), GetSister(), LinkedListHead::getSize(), Unit::GetVictim(), Unit::HasUnitState(), ScriptedAI::IsHeroic(), JustSummoned(), LOC_CENTER, Locs, ScriptedAI::me, myDoMeleeAttackIfReady(), NPC_CONCENTRATED_DARK, NPC_CONCENTRATED_LIGHT, NPC_DARKBANE, NPC_LIGHTBANE, rand_norm(), SAY_BERSERK, SAY_LIGHT, SAY_NIGHT, SAY_TWINK_PACT, Creature::SetCanDualWield(), SpecialMask, SPELL_BERSERK, SPELL_DARK_SHIELD, SPELL_DARK_TOUCH, SPELL_DARK_TWIN_PACT, SPELL_DARK_TWIN_SPIKE, SPELL_DARK_VORTEX, SPELL_LIGHT_SHIELD, SPELL_LIGHT_TOUCH, SPELL_LIGHT_TWIN_PACT, SPELL_LIGHT_TWIN_SPIKE, SPELL_LIGHT_VORTEX, WorldObject::SummonCreature(), CreatureAI::Talk(), TEMPSUMMON_CORPSE_TIMED_DESPAWN, UNIT_STATE_CASTING, UpdateSharedHealth(), CreatureAI::UpdateVictim(), and urand().
UpdateSharedHealth()
void boss_twin_valkyrAI::UpdateSharedHealth () inline
Definition at line 266 of file boss_twin_valkyr.cpp.
     {
         // lightbane synchronizes
         if( me->GetEntry() == NPC_LIGHTBANE )
             if( Creature* twin = GetSister() )
                 if( twin->IsAlive() && me->IsAlive() )
                 {
                     int32 d = CAST_AI(boss_twin_valkyrAI, twin->AI())->LastSynchroHP - (int32)twin->GetHealth();
                     int32 newhealth = (int32)me->GetHealth() - d;
                     if( newhealth <= 0 )
                         newhealth = 1;
                     me->SetHealth( (uint32)newhealth );
                     twin->SetHealth(me->GetHealth());
                     CAST_AI(boss_twin_valkyrAI, twin->AI())->LastSynchroHP = (int32)twin->GetHealth();
                 }
     }
References CAST_AI, Object::GetEntry(), Unit::GetHealth(), GetSister(), Unit::IsAlive(), ScriptedAI::me, NPC_LIGHTBANE, and Unit::SetHealth().
Referenced by UpdateAI().
Member Data Documentation
events
EventMap boss_twin_valkyrAI::events
Definition at line 140 of file boss_twin_valkyr.cpp.
LastSynchroHP
int32 boss_twin_valkyrAI::LastSynchroHP
Definition at line 141 of file boss_twin_valkyr.cpp.
Referenced by boss_twin_valkyrAI().
pInstance
InstanceScript* boss_twin_valkyrAI::pInstance
Definition at line 138 of file boss_twin_valkyr.cpp.
Referenced by boss_twin_valkyrAI(), DoAction(), EnterCombat(), EnterEvadeMode(), GetSister(), and JustDied().
SpecialMask
uint8 boss_twin_valkyrAI::SpecialMask
Definition at line 142 of file boss_twin_valkyr.cpp.
Referenced by boss_twin_valkyrAI(), and UpdateAI().
summons
SummonList boss_twin_valkyrAI::summons
Definition at line 139 of file boss_twin_valkyr.cpp.
Referenced by DoAction(), JustSummoned(), and SummonedCreatureDespawn().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_twin_valkyr.cpp