Azerotcore-wotlk: cast_commandscript Class Reference
cast_commandscript Class Reference
Public Member Functions
cast_commandscript ()
ChatCommandTable GetCommands () const override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Static Public Member Functions
static bool CheckSpellExistsAndIsValid (ChatHandler *handler, SpellInfo const *spell)
static Optional< TriggerCastFlags > GetTriggerFlags (Optional< std::string > triggeredStr)
static bool HandleCastCommand (ChatHandler *handler, SpellInfo const *spell, Optional< std::string > triggeredStr)
static bool HandleCastBackCommand (ChatHandler *handler, SpellInfo const *spell, Optional< std::string > triggeredStr)
static bool HandleCastDistCommand (ChatHandler *handler, SpellInfo const *spell, float dist, Optional< std::string > triggeredStr)
static bool HandleCastSelfCommand (ChatHandler *handler, SpellInfo const *spell, Optional< std::string > triggeredStr)
static bool HandleCastTargetCommad (ChatHandler *handler, SpellInfo const *spell, Optional< std::string > triggeredStr)
static bool HandleCastDestCommand (ChatHandler *handler, SpellInfo const *spell, float x, float y, float z, Optional< std::string > triggeredStr)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 36 of file cs_cast.cpp.
Constructor & Destructor Documentation
cast_commandscript()
cast_commandscript::cast_commandscript () inline
Definition at line 39 of file cs_cast.cpp.
 : CommandScript("cast_commandscript") { }
Member Function Documentation
CheckSpellExistsAndIsValid()
static bool cast_commandscript::CheckSpellExistsAndIsValid (ChatHandler * handler, SpellInfo const * spell) inline static
Definition at line 59 of file cs_cast.cpp.
     {
         if (!spell)
         {
             handler->PSendSysMessage(LANG_COMMAND_NOSPELLFOUND);
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (!SpellMgr::IsSpellValid(spell))
         {
             handler->PSendSysMessage(LANG_COMMAND_SPELL_BROKEN, spell->Id);
             handler->SetSentErrorMessage(true);
             return false;
         }
         return true;
     }
References SpellInfo::Id, SpellMgr::IsSpellValid(), LANG_COMMAND_NOSPELLFOUND, LANG_COMMAND_SPELL_BROKEN, ChatHandler::PSendSysMessage(), and ChatHandler::SetSentErrorMessage().
GetCommands()
ChatCommandTable cast_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
Definition at line 41 of file cs_cast.cpp.
     {
         static ChatCommandTable castCommandTable =
         {
             { "back",   HandleCastBackCommand,  SEC_GAMEMASTER, Console::No },
             { "dist",   HandleCastDistCommand,  SEC_GAMEMASTER, Console::No },
             { "self",   HandleCastSelfCommand,  SEC_GAMEMASTER, Console::No },
             { "target", HandleCastTargetCommad, SEC_GAMEMASTER, Console::No },
             { "dest",   HandleCastDestCommand,  SEC_GAMEMASTER, Console::No },
             { "",       HandleCastCommand,      SEC_GAMEMASTER, Console::No }
         };
         static ChatCommandTable commandTable =
         {
             { "cast", castCommandTable }
         };
         return commandTable;
     }
References Acore::ChatCommands::No, and SEC_GAMEMASTER.
GetTriggerFlags()
static Optional<TriggerCastFlags> cast_commandscript::GetTriggerFlags (Optional< std::string > triggeredStr) inline static
Definition at line 77 of file cs_cast.cpp.
     {
         if (triggeredStr)
         {
             if (StringStartsWith("triggered", *triggeredStr)) // check if "triggered" starts with *triggeredStr (e.g. "trig", "trigger", etc.)
                 return TRIGGERED_FULL_DEBUG_MASK;
             else
                 return std::nullopt;
         }
         return TRIGGERED_NONE;
     }
References StringStartsWith(), TRIGGERED_FULL_DEBUG_MASK, and TRIGGERED_NONE.
HandleCastBackCommand()
static bool cast_commandscript::HandleCastBackCommand (ChatHandler * handler, SpellInfo const * spell, Optional< std::string > triggeredStr) inline static
Definition at line 111 of file cs_cast.cpp.
     {
         Creature* caster = handler->getSelectedCreature();
         if (!caster)
         {
             handler->SendSysMessage(LANG_SELECT_CHAR_OR_CREATURE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (!CheckSpellExistsAndIsValid(handler, spell))
             return false;
         Optional<TriggerCastFlags> triggerFlags = GetTriggerFlags(triggeredStr);
         if (!triggerFlags)
             return false;
         caster->CastSpell(handler->GetSession()->GetPlayer(), spell->Id, *triggerFlags);
         return true;
     }
References Unit::CastSpell(), WorldSession::GetPlayer(), ChatHandler::getSelectedCreature(), ChatHandler::GetSession(), SpellInfo::Id, LANG_SELECT_CHAR_OR_CREATURE, ChatHandler::SendSysMessage(), and ChatHandler::SetSentErrorMessage().
HandleCastCommand()
static bool cast_commandscript::HandleCastCommand (ChatHandler * handler, SpellInfo const * spell, Optional< std::string > triggeredStr) inline static
Definition at line 89 of file cs_cast.cpp.
     {
         Unit* target = handler->getSelectedUnit();
         if (!target)
         {
             handler->SendSysMessage(LANG_SELECT_CHAR_OR_CREATURE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (!CheckSpellExistsAndIsValid(handler, spell))
             return false;
         Optional<TriggerCastFlags> triggerFlags = GetTriggerFlags(triggeredStr);
         if (!triggerFlags)
             return false;
         handler->GetSession()->GetPlayer()->CastSpell(target, spell->Id, *triggerFlags);
         return true;
     }
References Unit::CastSpell(), WorldSession::GetPlayer(), ChatHandler::getSelectedUnit(), ChatHandler::GetSession(), SpellInfo::Id, LANG_SELECT_CHAR_OR_CREATURE, ChatHandler::SendSysMessage(), and ChatHandler::SetSentErrorMessage().
HandleCastDestCommand()
static bool cast_commandscript::HandleCastDestCommand (ChatHandler * handler, SpellInfo const * spell, float x, float y, float z, Optional< std::string > triggeredStr) inline static
Definition at line 200 of file cs_cast.cpp.
     {
         Unit* caster = handler->getSelectedUnit();
         if (!caster)
         {
             handler->SendSysMessage(LANG_SELECT_CHAR_OR_CREATURE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (!CheckSpellExistsAndIsValid(handler, spell))
             return false;
         Optional<TriggerCastFlags> triggerFlags = GetTriggerFlags(triggeredStr);
         if (!triggerFlags)
             return false;
         caster->CastSpell(x, y, z, spell->Id, *triggerFlags);
         return true;
     }
References Unit::CastSpell(), ChatHandler::getSelectedUnit(), SpellInfo::Id, LANG_SELECT_CHAR_OR_CREATURE, ChatHandler::SendSysMessage(), and ChatHandler::SetSentErrorMessage().
HandleCastDistCommand()
static bool cast_commandscript::HandleCastDistCommand (ChatHandler * handler, SpellInfo const * spell, float dist, Optional< std::string > triggeredStr) inline static
Definition at line 133 of file cs_cast.cpp.
     {
         if (!CheckSpellExistsAndIsValid(handler, spell))
             return false;
         Optional<TriggerCastFlags> triggerFlags = GetTriggerFlags(triggeredStr);
         if (!triggerFlags)
             return false;
         float x, y, z;
         handler->GetSession()->GetPlayer()->GetClosePoint(x, y, z, dist);
         handler->GetSession()->GetPlayer()->CastSpell(x, y, z, spell->Id, *triggerFlags);
         return true;
     }
References Unit::CastSpell(), WorldObject::GetClosePoint(), WorldSession::GetPlayer(), ChatHandler::GetSession(), and SpellInfo::Id.
HandleCastSelfCommand()
static bool cast_commandscript::HandleCastSelfCommand (ChatHandler * handler, SpellInfo const * spell, Optional< std::string > triggeredStr) inline static
Definition at line 149 of file cs_cast.cpp.
     {
         Unit* target = handler->getSelectedUnit();
         if (!target)
         {
             handler->SendSysMessage(LANG_SELECT_CHAR_OR_CREATURE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (!CheckSpellExistsAndIsValid(handler, spell))
             return false;
         Optional<TriggerCastFlags> triggerFlags = GetTriggerFlags(triggeredStr);
         if (!triggerFlags)
             return false;
         target->CastSpell(target, spell->Id, *triggerFlags);
         return true;
     }
References Unit::CastSpell(), ChatHandler::getSelectedUnit(), SpellInfo::Id, LANG_SELECT_CHAR_OR_CREATURE, ChatHandler::SendSysMessage(), and ChatHandler::SetSentErrorMessage().
HandleCastTargetCommad()
static bool cast_commandscript::HandleCastTargetCommad (ChatHandler * handler, SpellInfo const * spell, Optional< std::string > triggeredStr) inline static
Definition at line 171 of file cs_cast.cpp.
     {
         Creature* caster = handler->getSelectedCreature();
         if (!caster)
         {
             handler->SendSysMessage(LANG_SELECT_CHAR_OR_CREATURE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (!caster->GetVictim())
         {
             handler->SendSysMessage(LANG_SELECTED_TARGET_NOT_HAVE_VICTIM);
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (!CheckSpellExistsAndIsValid(handler, spell))
             return false;
         Optional<TriggerCastFlags> triggerFlags = GetTriggerFlags(triggeredStr);
         if (!triggerFlags)
             return false;
         caster->CastSpell(caster->GetVictim(), spell->Id, *triggerFlags);
         return true;
     }
References Unit::CastSpell(), ChatHandler::getSelectedCreature(), Unit::GetVictim(), SpellInfo::Id, LANG_SELECT_CHAR_OR_CREATURE, LANG_SELECTED_TARGET_NOT_HAVE_VICTIM, ChatHandler::SendSysMessage(), and ChatHandler::SetSentErrorMessage().
The documentation for this class was generated from the following file:
src/server/scripts/Commands/cs_cast.cpp