Azerotcore-wotlk: SpellClickInfo Struct Reference
SpellClickInfo Struct Reference
#include <ObjectMgr.h>
Public Member Functions
bool IsFitToRequirements (Unit const *clicker, Unit const *clickee) const
Public Attributes
uint32 spellId
uint8 castFlags
SpellClickUserTypes userType
Detailed Description
Definition at line 397 of file ObjectMgr.h.
Member Function Documentation
IsFitToRequirements()
bool SpellClickInfo::IsFitToRequirements (Unit const * clicker, Unit const * clickee) const
Definition at line 255 of file ObjectMgr.cpp.
 {
     Player const* playerClicker = clicker->ToPlayer();
     if (!playerClicker)
         return true;
     Unit const* summoner = nullptr;
     // Check summoners for party
     if (clickee->IsSummon())
         summoner = clickee->ToTempSummon()->GetSummonerUnit();
     if (!summoner)
         summoner = clickee;
     // This only applies to players
     switch (userType)
     {
         case SPELL_CLICK_USER_FRIEND:
             if (!playerClicker->IsFriendlyTo(summoner))
                 return false;
             break;
         case SPELL_CLICK_USER_RAID:
             if (!playerClicker->IsInRaidWith(summoner))
                 return false;
             break;
         case SPELL_CLICK_USER_PARTY:
             if (!playerClicker->IsInPartyWith(summoner))
                 return false;
             break;
         default:
             break;
     }
     return true;
 }
References TempSummon::GetSummonerUnit(), Unit::IsFriendlyTo(), Unit::IsInPartyWith(), Unit::IsInRaidWith(), Unit::IsSummon(), SPELL_CLICK_USER_FRIEND, SPELL_CLICK_USER_PARTY, SPELL_CLICK_USER_RAID, Object::ToPlayer(), Unit::ToTempSummon(), and userType.
Member Data Documentation
castFlags
uint8 SpellClickInfo::castFlags
Definition at line 400 of file ObjectMgr.h.
Referenced by ObjectMgr::LoadNPCSpellClickSpells().
spellId
uint32 SpellClickInfo::spellId
Definition at line 399 of file ObjectMgr.h.
Referenced by ObjectMgr::LoadNPCSpellClickSpells().
userType
SpellClickUserTypes SpellClickInfo::userType
Definition at line 401 of file ObjectMgr.h.
Referenced by IsFitToRequirements(), and ObjectMgr::LoadNPCSpellClickSpells().
The documentation for this struct was generated from the following files:
src/server/game/Globals/ObjectMgr.h
src/server/game/Globals/ObjectMgr.cpp