Azerotcore-wotlk: ByteBufferException Class Reference
ByteBufferException Class Reference
#include <ByteBuffer.h>
Public Member Functions
~ByteBufferException () noexcept=default
char const * what () const noexcept override
Protected Member Functions
std::string & message () noexcept
Private Attributes
std::string msg_
Detailed Description
Definition at line 31 of file ByteBuffer.h.
Constructor & Destructor Documentation
~ByteBufferException()
ByteBufferException::~ByteBufferException () default noexcept
Member Function Documentation
message()
std::string& ByteBufferException::message () inline protected noexcept
Definition at line 39 of file ByteBuffer.h.
 { return msg_; }
Referenced by ByteBufferInvalidValueException::ByteBufferInvalidValueException(), ByteBufferPositionException::ByteBufferPositionException(), and ByteBufferSourceException::ByteBufferSourceException().
what()
char const* ByteBufferException::what () const inline override noexcept
Definition at line 36 of file ByteBuffer.h.
 { return msg_.c_str(); }
Referenced by WorldSession::Update().
Member Data Documentation
msg_
std::string ByteBufferException::msg_ private
Definition at line 42 of file ByteBuffer.h.
The documentation for this class was generated from the following file:
src/server/shared/Packets/ByteBuffer.h