Azerotcore-wotlk: WDT Class Reference
WDT Class Reference
#include <WDT.h>
Public Member Functions
WDT (std::string file)
bool HasTile (int x, int y)
Public Attributes
ChunkedData * Data
std::vector< TilePos > TileTable
bool IsGlobalModel
bool IsValid
std::string ModelFile
WorldModelDefinition ModelDefinition
WorldModelRoot * Model
Private Member Functions
void ReadGlobalModel ()
void ReadTileTable ()
Detailed Description
Definition at line 28 of file WDT.h.
Constructor & Destructor Documentation
WDT()
WDT::WDT (std::string file)
Definition at line 24 of file WDT.cpp.
                        : IsGlobalModel(false), IsValid(false), Model(nullptr)
 {
     Data = new ChunkedData(file, 2);
     ReadTileTable();
     ReadGlobalModel();
 }
References ReadGlobalModel(), and ReadTileTable().
Member Function Documentation
HasTile()
bool WDT::HasTile (int x, int y)
Definition at line 71 of file WDT.cpp.
 {
     for (std::vector<TilePos>::iterator itr = TileTable.begin(); itr != TileTable.end(); ++itr)
         if (itr->X == x && itr->Y == y)
             return true;
     return false;
 }
References TileTable.
ReadGlobalModel()
void WDT::ReadGlobalModel () private
Definition at line 31 of file WDT.cpp.
 {
     Chunk* fileChunk = Data->GetChunkByName("MWMO");
     Chunk* defChunk = Data->GetChunkByName("MODF");
     if (!fileChunk || !defChunk)
         return;
     IsGlobalModel = true;
     ModelDefinition = WorldModelDefinition::Read(defChunk->GetStream());
     ModelFile = Utils::ReadString(fileChunk->GetStream());
     Model = new WorldModelRoot(ModelFile);
 }
References Chunk::GetStream(), IsGlobalModel, ModelDefinition, ModelFile, WorldModelDefinition::Read(), and Utils::ReadString().
Referenced by WDT().
ReadTileTable()
void WDT::ReadTileTable () private
Definition at line 44 of file WDT.cpp.
 {
     Chunk* chunk = Data->GetChunkByName("MAIN");
     if (!chunk)
         return;
     IsValid = true;
     FILE* stream = chunk->GetStream();
     for (int y = 0; y < 64; ++y)
     {
         for (int x = 0; x < 64; ++x)
         {
             const uint32 hasTileFlag = 0x1;
             uint32 flags;
             uint32 discard;
             int count = 0;
             count += fread(&flags, sizeof(uint32), 1, stream);
             count += fread(&discard, sizeof(uint32), 1, stream);
             if (count != 2)
                 printf("WDT::ReadTileTable: Failed to read some data expected 2, read %d\n", count);
             if (flags & hasTileFlag)
                 TileTable.push_back(TilePos(x, y));
         }
     }
 }
References IsValid, and TileTable.
Referenced by WDT().
Member Data Documentation
Data
ChunkedData* WDT::Data
Definition at line 33 of file WDT.h.
IsGlobalModel
bool WDT::IsGlobalModel
Definition at line 35 of file WDT.h.
Referenced by ContinentBuilder::Build(), and ReadGlobalModel().
IsValid
bool WDT::IsValid
Definition at line 36 of file WDT.h.
Referenced by ExtractMMaps(), and ReadTileTable().
Model
WorldModelRoot* WDT::Model
Definition at line 39 of file WDT.h.
Referenced by ContinentBuilder::Build().
ModelDefinition
WorldModelDefinition WDT::ModelDefinition
Definition at line 38 of file WDT.h.
Referenced by ContinentBuilder::Build(), and ReadGlobalModel().
ModelFile
std::string WDT::ModelFile
Definition at line 37 of file WDT.h.
Referenced by ReadGlobalModel().
TileTable
std::vector<TilePos> WDT::TileTable
Definition at line 34 of file WDT.h.
Referenced by ContinentBuilder::Build(), ContinentBuilder::CalculateTileBounds(), HasTile(), and ReadTileTable().
The documentation for this class was generated from the following files:
src/tools/mesh_extractor/WDT.h
src/tools/mesh_extractor/WDT.cpp