Azerotcore-wotlk: flag96 Class Reference
flag96 Class Reference
#include <Util.h>
Public Member Functions
flag96 (uint32 p1=0, uint32 p2=0, uint32 p3=0)
bool IsEqual (uint32 p1=0, uint32 p2=0, uint32 p3=0) const
bool HasFlag (uint32 p1=0, uint32 p2=0, uint32 p3=0) const
void Set (uint32 p1=0, uint32 p2=0, uint32 p3=0)
bool operator< (flag96 const &right) const
bool operator== (flag96 const &right) const
bool operator!= (flag96 const &right) const
flag96 & operator= (flag96 const &right)
flag96 operator& (flag96 const &right) const
flag96 & operator&= (flag96 const &right)
flag96 operator| (flag96 const &right) const
flag96 & operator|= (flag96 const &right)
flag96 operator~ () const
flag96 operator^ (flag96 const &right) const
flag96 & operator^= (flag96 const &right)
operator bool () const
bool operator! () const
uint32 & operator[] (uint8 el)
uint32 const & operator[] (uint8 el) const
Private Attributes
uint32 part [3]
Detailed Description
Definition at line 482 of file Util.h.
Constructor & Destructor Documentation
flag96()
flag96::flag96 (uint32 p1 = 0, uint32 p2 = 0, uint32 p3 = 0) inline
Definition at line 488 of file Util.h.
     {
         part[0] = p1;
         part[1] = p2;
         part[2] = p3;
     }
References part.
Referenced by operator&(), operator^(), operator|(), and operator~().
Member Function Documentation
HasFlag()
bool flag96::HasFlag (uint32 p1 = 0, uint32 p2 = 0, uint32 p3 = 0) const inline
Definition at line 500 of file Util.h.
     {
         return (part[0] & p1 || part[1] & p2 || part[2] & p3);
     }
References part.
Referenced by spell_dk_dancing_rune_weapon::CheckProc(), spell_pal_seal_of_light::CheckProc(), Unit::GetAuraEffect(), spell_pal_sacred_shield_base::HandleProc(), SpellInfo::LoadSpellSpecific(), spell_dru_enrage::RecalculateBaseArmor(), Unit::RemoveAurasWithFamily(), and Unit::SpellHealingBonusTaken().
IsEqual()
bool flag96::IsEqual (uint32 p1 = 0, uint32 p2 = 0, uint32 p3 = 0) const inline
Definition at line 495 of file Util.h.
     {
         return (part[0] == p1 && part[1] == p2 && part[2] == p3);
     }
References part.
Referenced by spell_rog_deadly_poison::HandleAfterHit(), and Unit::HandleDummyAuraProc().
operator bool()
flag96::operator bool () const inline
Definition at line 600 of file Util.h.
     {
         return (part[0] != 0 || part[1] != 0 || part[2] != 0);
     }
References part.
operator!()
bool flag96::operator! () const inline
Definition at line 605 of file Util.h.
     {
         return !(bool(*this));
     }
operator!=()
bool flag96::operator!= (flag96 const & right) const inline
Definition at line 538 of file Util.h.
     {
         return !(*this == right);
     }
operator&()
flag96 flag96::operator& (flag96 const & right) const inline
Definition at line 556 of file Util.h.
     {
         return flag96(part[0] & right.part[0], part[1] & right.part[1], part[2] & right.part[2]);
     }
References flag96(), and part.
operator&=()
flag96& flag96::operator&= (flag96 const & right) inline
Definition at line 561 of file Util.h.
     {
         part[0] &= right.part[0];
         part[1] &= right.part[1];
         part[2] &= right.part[2];
         return *this;
     }
References part.
operator<()
bool flag96::operator< (flag96 const & right) const inline
Definition at line 512 of file Util.h.
     {
         for (uint8 i = 3; i > 0; --i)
         {
             if (part[i - 1] < right.part[i - 1])
             {
                 return true;
             }
             else if (part[i - 1] > right.part[i - 1])
             {
                 return false;
             }
         }
         return false;
     }
References part.
operator=()
flag96& flag96::operator= (flag96 const & right) inline
Definition at line 543 of file Util.h.
     {
         part[0] = right.part[0];
         part[1] = right.part[1];
         part[2] = right.part[2];
         return *this;
     }
References part.
operator==()
bool flag96::operator== (flag96 const & right) const inline
Definition at line 528 of file Util.h.
     {
         return
             (
                 part[0] == right.part[0] &&
                 part[1] == right.part[1] &&
                 part[2] == right.part[2]
             );
     }
References part.
operator[]() [1/2]
uint32& flag96::operator[] (uint8 el) inline
Definition at line 610 of file Util.h.
     {
         return part[el];
     }
References part.
operator[]() [2/2]
uint32 const& flag96::operator[] (uint8 el) const inline
Definition at line 615 of file Util.h.
     {
         return part[el];
     }
References part.
operator^()
flag96 flag96::operator^ (flag96 const & right) const inline
Definition at line 587 of file Util.h.
     {
         return flag96(part[0] ^ right.part[0], part[1] ^ right.part[1], part[2] ^ right.part[2]);
     }
References flag96(), and part.
operator^=()
flag96& flag96::operator^= (flag96 const & right) inline
Definition at line 592 of file Util.h.
     {
         part[0] ^= right.part[0];
         part[1] ^= right.part[1];
         part[2] ^= right.part[2];
         return *this;
     }
References part.
operator|()
flag96 flag96::operator| (flag96 const & right) const inline
Definition at line 569 of file Util.h.
     {
         return flag96(part[0] | right.part[0], part[1] | right.part[1], part[2] | right.part[2]);
     }
References flag96(), and part.
operator|=()
flag96& flag96::operator|= (flag96 const & right) inline
Definition at line 574 of file Util.h.
     {
         part[0] |= right.part[0];
         part[1] |= right.part[1];
         part[2] |= right.part[2];
         return *this;
     }
References part.
operator~()
flag96 flag96::operator~ () const inline
Definition at line 582 of file Util.h.
     {
         return flag96(~part[0], ~part[1], ~part[2]);
     }
References flag96(), and part.
Set()
void flag96::Set (uint32 p1 = 0, uint32 p2 = 0, uint32 p3 = 0) inline
Definition at line 505 of file Util.h.
     {
         part[0] = p1;
         part[1] = p2;
         part[2] = p3;
     }
References part.
Member Data Documentation
part
uint32 flag96::part[3] private
Definition at line 485 of file Util.h.
Referenced by flag96(), HasFlag(), IsEqual(), operator bool(), operator&(), operator&=(), operator<(), operator=(), operator==(), operator[](), operator^(), operator^=(), operator|(), operator|=(), operator~(), and Set().
The documentation for this class was generated from the following file:
src/common/Utilities/Util.h