Azerotcore-wotlk: my_collation_handler_st Struct Reference
my_collation_handler_st Struct Reference
#include <m_ctype.h>
Public Attributes
my_bool(* init)(struct charset_info_st *, void *(*alloc)(size_t))
int(* strnncoll)(struct charset_info_st *, const uchar *, size_t, const uchar *, size_t, my_bool)
int(* strnncollsp)(struct charset_info_st *, const uchar *, size_t, const uchar *, size_t, my_bool diff_if_only_endspace_difference)
size_t(* strnxfrm)(struct charset_info_st *, uchar *, size_t, const uchar *, size_t)
size_t(* strnxfrmlen)(struct charset_info_st *, size_t)
my_bool(* like_range)(struct charset_info_st *, const char *s, size_t s_length, pchar w_prefix, pchar w_one, pchar w_many, size_t res_length, char *min_str, char *max_str, size_t *min_len, size_t *max_len)
int(* wildcmp)(struct charset_info_st *, const char *str, const char *str_end, const char *wildstr, const char *wildend, int escape, int w_one, int w_many)
int(* strcasecmp)(struct charset_info_st *, const char *, const char *)
uint(* instr)(struct charset_info_st *, const char *b, size_t b_length, const char *s, size_t s_length, my_match_t *match, uint nmatch)
void(* hash_sort)(struct charset_info_st *cs, const uchar *key, size_t len, ulong *nr1, ulong *nr2)
my_bool(* propagate)(struct charset_info_st *cs, const uchar *str, size_t len)
Detailed Description
Definition at line 151 of file m_ctype.h.
Member Data Documentation
hash_sort
void(* my_collation_handler_st::hash_sort) (struct charset_info_st *cs, const uchar *key, size_t len, ulong *nr1, ulong *nr2)
Definition at line 182 of file m_ctype.h.
init
my_bool(* my_collation_handler_st::init) (struct charset_info_st *, void *(*alloc)(size_t))
Definition at line 153 of file m_ctype.h.
Referenced by get_internal_charset().
instr
uint(* my_collation_handler_st::instr) (struct charset_info_st *, const char *b, size_t b_length, const char *s, size_t s_length, my_match_t *match, uint nmatch)
Definition at line 176 of file m_ctype.h.
like_range
my_bool(* my_collation_handler_st::like_range) (struct charset_info_st *, const char *s, size_t s_length, pchar w_prefix, pchar w_one, pchar w_many, size_t res_length, char *min_str, char *max_str, size_t *min_len, size_t *max_len)
Definition at line 163 of file m_ctype.h.
propagate
my_bool(* my_collation_handler_st::propagate) (struct charset_info_st *cs, const uchar *str, size_t len)
Definition at line 184 of file m_ctype.h.
strcasecmp
int(* my_collation_handler_st::strcasecmp) (struct charset_info_st *, const char *, const char *)
Definition at line 174 of file m_ctype.h.
strnncoll
int(* my_collation_handler_st::strnncoll) (struct charset_info_st *, const uchar *, size_t, const uchar *, size_t, my_bool)
Definition at line 155 of file m_ctype.h.
Referenced by ha_compare_text().
strnncollsp
int(* my_collation_handler_st::strnncollsp) (struct charset_info_st *, const uchar *, size_t, const uchar *, size_t, my_bool diff_if_only_endspace_difference)
Definition at line 157 of file m_ctype.h.
Referenced by ha_compare_text().
strnxfrm
size_t(* my_collation_handler_st::strnxfrm) (struct charset_info_st *, uchar *, size_t, const uchar *, size_t)
Definition at line 160 of file m_ctype.h.
strnxfrmlen
size_t(* my_collation_handler_st::strnxfrmlen) (struct charset_info_st *, size_t)
Definition at line 162 of file m_ctype.h.
wildcmp
int(* my_collation_handler_st::wildcmp) (struct charset_info_st *, const char *str, const char *str_end, const char *wildstr, const char *wildend, int escape, int w_one, int w_many)
Definition at line 169 of file m_ctype.h.
The documentation for this struct was generated from the following file:
deps/mysqllite/include/m_ctype.h