Azerotcore-wotlk: deps/mysqllite/mysys/my_redel.c File Reference
my_redel.c File Reference
#include "mysys_priv.h"
#include <my_dir.h>
#include <m_string.h>
#include "mysys_err.h"
Classes
struct utimbuf
Macros
#define REDEL_EXT ".BAK"
Functions
int my_redel (const char *org_name, const char *tmp_name, myf MyFlags)
int my_copystat (const char *from, const char *to, int MyFlags)
Macro Definition Documentation
REDEL_EXT
#define REDEL_EXT ".BAK"
Definition at line 40 of file my_redel.c.
Function Documentation
my_copystat()
int my_copystat (const char * from, const char * to, int MyFlags)
Definition at line 76 of file my_redel.c.
 {
   struct stat statbuf;
   if (stat(from, &statbuf))
   {
     my_errno=errno;
     if (MyFlags & (MY_FAE+MY_WME))
       my_error(EE_STAT, MYF(ME_BELL+ME_WAITTANG),from,errno);
     return -1;              /* Can't get stat on input file */
   }
   if ((statbuf.st_mode & S_IFMT) != S_IFREG)
     return 1;
   /* Copy modes */
   if (chmod(to, statbuf.st_mode & 07777))
   {
     my_errno= errno;
     if (MyFlags & (MY_FAE+MY_WME))
       my_error(EE_CHANGE_PERMISSIONS, MYF(ME_BELL+ME_WAITTANG), from, errno);
     return -1;
   }
 #if !defined(__WIN__)
   if (statbuf.st_nlink > 1 && MyFlags & MY_LINK_WARNING)
   {
     if (MyFlags & MY_LINK_WARNING)
       my_error(EE_LINK_WARNING,MYF(ME_BELL+ME_WAITTANG),from,statbuf.st_nlink);
   }
   /* Copy ownership */
   if (chown(to, statbuf.st_uid, statbuf.st_gid))
   {
     my_errno= errno;
     if (MyFlags & (MY_FAE+MY_WME))
       my_error(EE_CHANGE_OWNERSHIP, MYF(ME_BELL+ME_WAITTANG), from, errno);
     return -1;
   }
 #endif /* !__WIN__ */
   if (MyFlags & MY_COPYTIME)
   {
     struct utimbuf timep;
     timep.actime  = statbuf.st_atime;
     timep.modtime = statbuf.st_mtime;
     (void) utime((char*) to, &timep);/* Update last accessed and modified times */
   }
   return 0;
 } /* my_copystat */
References utimbuf::actime, EE_CHANGE_OWNERSHIP, EE_CHANGE_PERMISSIONS, EE_LINK_WARNING, EE_STAT, errno, ME_BELL, ME_WAITTANG, utimbuf::modtime, MY_COPYTIME, my_errno, my_error(), MY_FAE, MY_LINK_WARNING, MY_WME, and MYF.
Referenced by my_redel().
my_redel()
int my_redel (const char * org_name, const char * tmp_name, myf MyFlags)
Definition at line 42 of file my_redel.c.
 {
   int error=1;
   DBUG_ENTER("my_redel");
   DBUG_PRINT("my",("org_name: '%s' tmp_name: '%s'  MyFlags: %d",
            org_name,tmp_name,MyFlags));
   if (my_copystat(org_name,tmp_name,MyFlags) < 0)
     goto end;
   if (MyFlags & MY_REDEL_MAKE_BACKUP)
   {
     char name_buff[FN_REFLEN+20];
     char ext[20];
     ext[0]='-';
     get_date(ext+1,2+4,(time_t) 0);
     strmov(strend(ext),REDEL_EXT);
     if (my_rename(org_name, fn_format(name_buff, org_name, "", ext, 2),
           MyFlags))
       goto end;
   }
   else if (my_delete_allow_opened(org_name, MyFlags))
       goto end;
   if (my_rename(tmp_name,org_name,MyFlags))
     goto end;
   error=0;
 end:
   DBUG_RETURN(error);
 } /* my_redel */
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, error(), fn_format(), FN_REFLEN, get_date(), my_copystat(), my_delete_allow_opened, MY_REDEL_MAKE_BACKUP, my_rename(), REDEL_EXT, strend(), and strmov().