Azerotcore-wotlk: MapRefMgr Class Reference
MapRefMgr Class Reference
#include <MapRefMgr.h>
Public Types
typedef LinkedListHead::Iterator< MapReference > iterator
typedef LinkedListHead::Iterator< MapReference const > const_iterator
Public Types inherited from RefMgr< Map, Player >
typedef LinkedListHead::Iterator< Reference< Map, Player > > iterator
Public Types inherited from LinkedListHead
typedef Iterator< LinkedListElement > iterator
Public Member Functions
MapReference * getFirst ()
MapReference const * getFirst () const
MapReference * getLast ()
MapReference const * getLast () const
iterator begin ()
iterator end ()
iterator rbegin ()
iterator rend ()
const_iterator begin () const
const_iterator end () const
Public Member Functions inherited from RefMgr< Map, Player >
RefMgr ()=default
virtual ~RefMgr ()
Reference< Map, Player > * getFirst ()
Reference< Map, Player > const * getFirst () const
Reference< Map, Player > * getLast ()
Reference< Map, Player > const * getLast () const
iterator begin ()
iterator end ()
iterator rbegin ()
iterator rend ()
void clearReferences ()
Public Member Functions inherited from LinkedListHead
LinkedListHead ()
bool isEmpty () const
LinkedListElement * getFirst ()
LinkedListElement const * getFirst () const
LinkedListElement * getLast ()
LinkedListElement const * getLast () const
void insertFirst (LinkedListElement *pElem)
void insertLast (LinkedListElement *pElem)
uint32 getSize () const
void incSize ()
void decSize ()
Detailed Description
Definition at line 25 of file MapRefMgr.h.
Member Typedef Documentation
const_iterator
typedef LinkedListHead::Iterator< MapReference const > MapRefMgr::const_iterator
Definition at line 29 of file MapRefMgr.h.
iterator
typedef LinkedListHead::Iterator< MapReference > MapRefMgr::iterator
Definition at line 28 of file MapRefMgr.h.
Member Function Documentation
begin() [1/2]
iterator MapRefMgr::begin () inline
Definition at line 36 of file MapRefMgr.h.
 { return iterator(getFirst()); }
References getFirst().
Referenced by boss_hadronox::boss_hadronoxAI::AnyPlayerValid(), MotionTransport::BuildUpdate(), StaticTransport::BuildUpdate(), InstanceMap::CannotEnter(), boss_professor_putricide::boss_professor_putricideAI::ChangePhase(), boss_skadi_grauf::boss_skadi_graufAI::CheckPlayers(), brann_bronzebeard::brann_bronzebeardAI::DoAction(), InstanceScript::DoCastSpellOnPlayers(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::DoCheckDedicatedInsanity(), boss_algalon_the_observer::boss_algalon_the_observerAI::DoCheckHeraldOfTheTitans(), instance_violet_hold::instance_violet_hold_InstanceMapScript::DoNeedCleanup(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::DoNeedCleanup(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::DoNeedCleanup(), ScriptedAI::DoPlayMusic(), InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), InstanceScript::DoSendNotifyToInstance(), InstanceScript::DoStartTimedAchievement(), InstanceScript::DoStopTimedAchievement(), ScriptedAI::DoTeleportAll(), boss_icehowl::boss_icehowlAI::DoTrampleIfValid(), InstanceScript::DoUpdateAchievementCriteria(), InstanceScript::DoUpdateWorldState(), CreatureAI::DoZoneInCombat(), boss_devourer_of_souls::boss_devourer_of_soulsAI::EnterCombat(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::EnterEvadeMode(), boss_sindragosa::boss_sindragosaAI::EnterEvadeMode(), boss_thorim::boss_thorimAI::GetArenaPlayer(), instance_pit_of_saron::instance_pit_of_saron_InstanceScript::GetCreatureEntry(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::GetCreatureEntry(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::GetGameObjectEntry(), instance_mechanar::instance_mechanar_InstanceMapScript::GetPassagePlayer(), instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::GetPlayerInMap(), Map::GetPlayersCountExceptGMs(), spell_madrigosa_activate_barrier::spell_madrigosa_activate_barrier_SpellScript::HandleActivateObject(), spell_madrigosa_deactivate_barrier::spell_madrigosa_deactivate_barrier_SpellScript::HandleActivateObject(), spell_teron_gorefiend_shadowy_construct::spell_teron_gorefiend_shadowy_construct_AuraScript::HandleEffectApply(), spell_yogg_saron_brain_link::spell_yogg_saron_brain_link_AuraScript::HandleOnEffectApply(), spell_krick_explosive_barrage::spell_krick_explosive_barrage_AuraScript::HandlePeriodicTick(), WorldSession::HandleSetRaidDifficultyOpcode(), spell_marrowgar_bone_spike_graveyard::spell_marrowgar_bone_spike_graveyard_SpellScript::HandleSpikes(), boss_ichoron::boss_ichoronAI::IchoronDoCastToAllHostilePlayers(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::InstanceCleanup(), boss_halion::boss_halionAI::IsAnyPlayerValid(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::IsEncounterInProgress(), npc_coren_direbrew::npc_coren_direbrewAI::JustDied(), boss_headless_horseman::boss_headless_horsemanAI::JustDied(), npc_love_in_air_hummel::npc_love_in_air_hummelAI::JustDied(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::JustDied(), boss_yoggsaron::boss_yoggsaronAI::JustDied(), boss_ahune::boss_ahuneAI::JustDied(), boss_alar::boss_alarAI::JustDied(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustSummoned(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::LapseAction(), Map::LogEncounterFinished(), npc_image_of_medivh::npc_image_of_medivhAI::NextStep(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::OnCreatureCreate(), instance_forge_of_souls::instance_forge_of_souls_InstanceScript::OnCreatureCreate(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::OnCreatureCreate(), instance_pit_of_saron::instance_pit_of_saron_InstanceScript::OnCreatureCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), instance_nexus::instance_nexus_InstanceMapScript::OnCreatureCreate(), instance_shattered_halls::instance_shattered_halls_InstanceMapScript::OnCreatureCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectCreate(), spell_illidan_tear_of_azzinoth_summon_channel::spell_illidan_tear_of_azzinoth_summon_channel_AuraScript::OnPeriodic(), spell_hor_shared_suffering::spell_hor_shared_sufferingAuraScript::OnRemove(), InstanceMap::PermBindAllPlayers(), Map::PlayDirectSoundToMap(), spell_valkyr_touch::spell_valkyr_touchAuraScript::PrepareAuraScript(), SmartScript::ProcessAction(), Map::RemoveAllPlayers(), BattlegroundMap::RemoveAllPlayers(), Map::RemoveFromMap(), boss_krystallus::boss_krystallusAI::RemoveStonedEffect(), InstanceMap::Reset(), boss_yoggsaron_constrictor_tentacle::boss_yoggsaron_constrictor_tentacleAI::SelectConstrictTarget(), boss_yoggsaron_corruptor_tentacle::boss_yoggsaron_corruptor_tentacleAI::SelectCorruptionTarget(), spell_tsh_shadow_bolt::spell_tsh_shadow_bolt_SpellScript::SelectRandomPlayer(), boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::SelectT(), spell_gen_rallying_cry_of_the_dragonslayer::SelectTarget(), spell_gen_adals_song_of_battle::SelectTarget(), ScriptedAI::SelectTargetFromPlayerList(), npc_minigob_manabonk::npc_minigob_manabonkAI::SelectTargetInDalaran(), CreatureTextMgr::SendChatPacket(), CreatureTextMgr::SendNonChatPacket(), SendPacketToPlayers(), InstanceMap::SendResetWarnings(), Map::SendToPlayers(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::SendUpdateWorldState(), instance_hyjal::instance_mount_hyjal_InstanceMapScript::SetData(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::SetData(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::SetData(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::SetData(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SetData(), instance_ulduar::instance_ulduar_InstanceMapScript::SetData(), instance_the_black_morass::instance_the_black_morass_InstanceMapScript::SetData(), GameObject::SetLootRecipient(), Creature::SetLootRecipient(), Map::SetZoneMusic(), Map::SetZoneOverrideLight(), Map::SetZoneWeather(), boss_hodir::boss_hodirAI::SpawnHelpers(), instance_zulaman::instance_zulaman_InstanceMapScript::SummonHostage(), npc_arthas::npc_arthasAI::SummonNextWave(), Map::Update(), instance_stratholme::instance_stratholme_InstanceMapScript::Update(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::Update(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::Update(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::Update(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::Update(), instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::Update(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::UpdateAI(), boss_chromaggus::boss_chromaggusAI::UpdateAI(), npc_barnes::npc_barnesAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::UpdateAI(), npc_singularity::npc_singularityAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), boss_janalai::boss_janalaiAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), boss_cthun::cthunAI::UpdateAI(), npc_toc5_grand_champion_minion::npc_toc5_grand_champion_minionAI::UpdateAI(), boss_grand_champion::boss_grand_championAI::UpdateAI(), npc_snobold_vassal::npc_snobold_vassalAI::UpdateAI(), boss_gormok::boss_gormokAI::UpdateAI(), boss_twin_valkyrAI::UpdateAI(), npc_hor_lich_king::npc_hor_lich_kingAI::UpdateAI(), npc_hor_leader_second::npc_hor_leader_secondAI::UpdateAI(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::UpdateAI(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), npc_gunship_boarding_addAI::UpdateAI(), npc_gunship_gunner::npc_gunship_gunnerAI::UpdateAI(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::UpdateAI(), npc_icc_putricades_trap::npc_icc_putricades_trapAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_scion_of_eternity::npc_scion_of_eternityAI::UpdateAI(), boss_keristrasza::boss_keristraszaAI::UpdateAI(), boss_freya::boss_freyaAI::UpdateAI(), boss_vezax::boss_vezaxAI::UpdateAI(), boss_hodir::boss_hodirAI::UpdateAI(), boss_ignis::boss_ignisAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::UpdateAI(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::UpdateAI(), boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI::UpdateAI(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::UpdateAI(), go_midsummer_music::go_midsummer_musicAI::UpdateAI(), npc_demonic_vapor::npc_demonic_vaporAI::UpdateAI(), Map::UpdateEncounterState(), npc_grimstone::npc_grimstoneAI::UpdateEscortAI(), boss_netherspite::boss_netherspiteAI::UpdatePortals(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateWorldState(), and npc_thrall_bfu::npc_thrall_bfuAI::UpdateWorldState().
begin() [2/2]
const_iterator MapRefMgr::begin () const inline
Definition at line 40 of file MapRefMgr.h.
 { return const_iterator(getFirst()); }
References getFirst().
end() [1/2]
iterator MapRefMgr::end () inline
Definition at line 37 of file MapRefMgr.h.
 { return iterator(nullptr); }
Referenced by Map::AddToMap(), boss_hadronox::boss_hadronoxAI::AnyPlayerValid(), MotionTransport::BuildUpdate(), StaticTransport::BuildUpdate(), InstanceMap::CannotEnter(), boss_professor_putricide::boss_professor_putricideAI::ChangePhase(), boss_skadi_grauf::boss_skadi_graufAI::CheckPlayers(), brann_bronzebeard::brann_bronzebeardAI::DoAction(), InstanceScript::DoCastSpellOnPlayers(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::DoCheckDedicatedInsanity(), boss_algalon_the_observer::boss_algalon_the_observerAI::DoCheckHeraldOfTheTitans(), instance_violet_hold::instance_violet_hold_InstanceMapScript::DoNeedCleanup(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::DoNeedCleanup(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::DoNeedCleanup(), ScriptedAI::DoPlayMusic(), InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), InstanceScript::DoSendNotifyToInstance(), InstanceScript::DoStartTimedAchievement(), InstanceScript::DoStopTimedAchievement(), ScriptedAI::DoTeleportAll(), boss_icehowl::boss_icehowlAI::DoTrampleIfValid(), InstanceScript::DoUpdateAchievementCriteria(), InstanceScript::DoUpdateWorldState(), CreatureAI::DoZoneInCombat(), boss_devourer_of_souls::boss_devourer_of_soulsAI::EnterCombat(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::EnterEvadeMode(), boss_sindragosa::boss_sindragosaAI::EnterEvadeMode(), boss_thorim::boss_thorimAI::GetArenaPlayer(), instance_mechanar::instance_mechanar_InstanceMapScript::GetPassagePlayer(), instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::GetPlayerInMap(), Map::GetPlayersCountExceptGMs(), spell_madrigosa_activate_barrier::spell_madrigosa_activate_barrier_SpellScript::HandleActivateObject(), spell_madrigosa_deactivate_barrier::spell_madrigosa_deactivate_barrier_SpellScript::HandleActivateObject(), spell_teron_gorefiend_shadowy_construct::spell_teron_gorefiend_shadowy_construct_AuraScript::HandleEffectApply(), spell_yogg_saron_brain_link::spell_yogg_saron_brain_link_AuraScript::HandleOnEffectApply(), spell_krick_explosive_barrage::spell_krick_explosive_barrage_AuraScript::HandlePeriodicTick(), WorldSession::HandleSetRaidDifficultyOpcode(), spell_marrowgar_bone_spike_graveyard::spell_marrowgar_bone_spike_graveyard_SpellScript::HandleSpikes(), boss_ichoron::boss_ichoronAI::IchoronDoCastToAllHostilePlayers(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::InstanceCleanup(), boss_halion::boss_halionAI::IsAnyPlayerValid(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::IsEncounterInProgress(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::JustDied(), boss_yoggsaron::boss_yoggsaronAI::JustDied(), boss_ahune::boss_ahuneAI::JustDied(), boss_alar::boss_alarAI::JustDied(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustSummoned(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::LapseAction(), Map::LogEncounterFinished(), npc_image_of_medivh::npc_image_of_medivhAI::NextStep(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::OnCreatureCreate(), spell_illidan_tear_of_azzinoth_summon_channel::spell_illidan_tear_of_azzinoth_summon_channel_AuraScript::OnPeriodic(), spell_hor_shared_suffering::spell_hor_shared_sufferingAuraScript::OnRemove(), InstanceMap::PermBindAllPlayers(), Map::PlayDirectSoundToMap(), spell_valkyr_touch::spell_valkyr_touchAuraScript::PrepareAuraScript(), SmartScript::ProcessAction(), Map::RemoveAllPlayers(), BattlegroundMap::RemoveAllPlayers(), Map::RemoveFromMap(), boss_krystallus::boss_krystallusAI::RemoveStonedEffect(), InstanceMap::Reset(), boss_yoggsaron_constrictor_tentacle::boss_yoggsaron_constrictor_tentacleAI::SelectConstrictTarget(), boss_yoggsaron_corruptor_tentacle::boss_yoggsaron_corruptor_tentacleAI::SelectCorruptionTarget(), spell_tsh_shadow_bolt::spell_tsh_shadow_bolt_SpellScript::SelectRandomPlayer(), boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::SelectT(), spell_gen_rallying_cry_of_the_dragonslayer::SelectTarget(), spell_gen_adals_song_of_battle::SelectTarget(), ScriptedAI::SelectTargetFromPlayerList(), npc_minigob_manabonk::npc_minigob_manabonkAI::SelectTargetInDalaran(), CreatureTextMgr::SendChatPacket(), CreatureTextMgr::SendNonChatPacket(), SendPacketToPlayers(), InstanceMap::SendResetWarnings(), Map::SendToPlayers(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::SendUpdateWorldState(), instance_hyjal::instance_mount_hyjal_InstanceMapScript::SetData(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::SetData(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::SetData(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::SetData(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SetData(), instance_ulduar::instance_ulduar_InstanceMapScript::SetData(), instance_the_black_morass::instance_the_black_morass_InstanceMapScript::SetData(), GameObject::SetLootRecipient(), Creature::SetLootRecipient(), Map::SetZoneMusic(), Map::SetZoneOverrideLight(), Map::SetZoneWeather(), boss_hodir::boss_hodirAI::SpawnHelpers(), npc_arthas::npc_arthasAI::SummonNextWave(), Map::Update(), instance_stratholme::instance_stratholme_InstanceMapScript::Update(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::Update(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::Update(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::Update(), instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::Update(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::UpdateAI(), boss_chromaggus::boss_chromaggusAI::UpdateAI(), npc_barnes::npc_barnesAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::UpdateAI(), npc_singularity::npc_singularityAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), boss_janalai::boss_janalaiAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), boss_cthun::cthunAI::UpdateAI(), npc_toc5_grand_champion_minion::npc_toc5_grand_champion_minionAI::UpdateAI(), boss_grand_champion::boss_grand_championAI::UpdateAI(), npc_snobold_vassal::npc_snobold_vassalAI::UpdateAI(), boss_gormok::boss_gormokAI::UpdateAI(), boss_twin_valkyrAI::UpdateAI(), npc_hor_lich_king::npc_hor_lich_kingAI::UpdateAI(), npc_hor_leader_second::npc_hor_leader_secondAI::UpdateAI(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::UpdateAI(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), npc_gunship_boarding_addAI::UpdateAI(), npc_gunship_gunner::npc_gunship_gunnerAI::UpdateAI(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::UpdateAI(), npc_icc_putricades_trap::npc_icc_putricades_trapAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_scion_of_eternity::npc_scion_of_eternityAI::UpdateAI(), boss_keristrasza::boss_keristraszaAI::UpdateAI(), boss_freya::boss_freyaAI::UpdateAI(), boss_vezax::boss_vezaxAI::UpdateAI(), boss_hodir::boss_hodirAI::UpdateAI(), boss_ignis::boss_ignisAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::UpdateAI(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::UpdateAI(), boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI::UpdateAI(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::UpdateAI(), go_midsummer_music::go_midsummer_musicAI::UpdateAI(), npc_demonic_vapor::npc_demonic_vaporAI::UpdateAI(), Map::UpdateEncounterState(), npc_grimstone::npc_grimstoneAI::UpdateEscortAI(), boss_netherspite::boss_netherspiteAI::UpdatePortals(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateWorldState(), and npc_thrall_bfu::npc_thrall_bfuAI::UpdateWorldState().
end() [2/2]
const_iterator MapRefMgr::end () const inline
Definition at line 41 of file MapRefMgr.h.
 { return const_iterator(nullptr); }
getFirst() [1/2]
MapReference* MapRefMgr::getFirst () inline
Definition at line 31 of file MapRefMgr.h.
 { return (MapReference*)RefMgr<Map, Player>::getFirst(); }
References RefMgr< TO, FROM >::getFirst().
Referenced by begin(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::ChromieWhisper(), npc_arthas::npc_arthasAI::DoAction(), boss_four_horsemen::boss_four_horsemenAI::JustDied(), and npc_arthas::npc_arthasAI::UpdateAI().
getFirst() [2/2]
MapReference const* MapRefMgr::getFirst () const inline
Definition at line 32 of file MapRefMgr.h.
 { return (MapReference const*)RefMgr<Map, Player>::getFirst(); }
References RefMgr< TO, FROM >::getFirst().
getLast() [1/2]
MapReference* MapRefMgr::getLast () inline
Definition at line 33 of file MapRefMgr.h.
 { return (MapReference*)RefMgr<Map, Player>::getLast(); }
References RefMgr< TO, FROM >::getLast().
Referenced by rbegin().
getLast() [2/2]
MapReference const* MapRefMgr::getLast () const inline
Definition at line 34 of file MapRefMgr.h.
 { return (MapReference const*)RefMgr<Map, Player>::getLast(); }
References RefMgr< TO, FROM >::getLast().
rbegin()
iterator MapRefMgr::rbegin () inline
Definition at line 38 of file MapRefMgr.h.
 { return iterator(getLast()); }
References getLast().
rend()
iterator MapRefMgr::rend () inline
Definition at line 39 of file MapRefMgr.h.
 { return iterator(nullptr); }
The documentation for this class was generated from the following file:
src/server/game/Maps/MapRefMgr.h