Azerotcore-wotlk: npc_love_in_air_hummel::npc_love_in_air_hummelAI Struct Reference
npc_love_in_air_hummel::npc_love_in_air_hummelAI Struct Reference
Public Member Functions
npc_love_in_air_hummelAI (Creature *creature)
bool CanBeSeen (Player const *player) override
void Reset () override
void DoAction (int32 param) override
void JustDied (Unit *) override
void JustSummoned (Creature *cr) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
SummonList summons
EventMap events
uint32 speachTimer
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 338 of file love_in_air.cpp.
Constructor & Destructor Documentation
npc_love_in_air_hummelAI()
npc_love_in_air_hummel::npc_love_in_air_hummelAI::npc_love_in_air_hummelAI (Creature * creature) inline
Definition at line 340 of file love_in_air.cpp.
                                                      : ScriptedAI(creature), summons(me)
         {
         }
Member Function Documentation
CanBeSeen()
bool npc_love_in_air_hummel::npc_love_in_air_hummelAI::CanBeSeen (Player const * player) inline override virtual
Reimplemented from CreatureAI.
Definition at line 348 of file love_in_air.cpp.
         {
             if (player->IsGameMaster())
             {
                 return true;
             }
             Group const* group = player->GetGroup();
             return group && sLFGMgr->GetDungeon(group->GetGUID()) == lfg::LFG_DUNGEON_CROWN_CHEMICAL_CO;
         }
References Player::GetGroup(), Group::GetGUID(), Player::IsGameMaster(), lfg::LFG_DUNGEON_CROWN_CHEMICAL_CO, and sLFGMgr.
DoAction()
void npc_love_in_air_hummel::npc_love_in_air_hummelAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 369 of file love_in_air.cpp.
         {
             if (param == ACTION_START_EVENT)
                 speachTimer = 1;
         }
References ACTION_START_EVENT, and speachTimer.
JustDied()
void npc_love_in_air_hummel::npc_love_in_air_hummelAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 375 of file love_in_air.cpp.
         {
             me->AI()->Talk(SAY_HUMMEL_5);
             Map::PlayerList const& players = me->GetMap()->GetPlayers();
             if (!players.isEmpty() && players.begin()->GetSource() && players.begin()->GetSource()->GetGroup())
                 sLFGMgr->FinishDungeon(players.begin()->GetSource()->GetGroup()->GetGUID(), lfg::LFG_DUNGEON_CROWN_CHEMICAL_CO, me->FindMap());
         }
References Creature::AI(), MapRefMgr::begin(), WorldObject::FindMap(), WorldObject::GetMap(), Map::GetPlayers(), LinkedListHead::isEmpty(), lfg::LFG_DUNGEON_CROWN_CHEMICAL_CO, ScriptedAI::me, SAY_HUMMEL_5, sLFGMgr, and CreatureAI::Talk().
JustSummoned()
void npc_love_in_air_hummel::npc_love_in_air_hummelAI::JustSummoned (Creature * cr) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 383 of file love_in_air.cpp.
         {
             summons.Summon(cr);
             cr->SetFaction(FACTION_FRIENDLY);
             cr->SetControlled(true, UNIT_STATE_STUNNED);
             cr->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
         }
References FACTION_FRIENDLY, Unit::SetControlled(), Unit::SetFaction(), Object::SetFlag(), SummonList::Summon(), summons, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and UNIT_STATE_STUNNED.
Reset()
void npc_love_in_air_hummel::npc_love_in_air_hummelAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 359 of file love_in_air.cpp.
         {
             speachTimer = 0;
             me->SetFaction(FACTION_FRIENDLY);
             summons.DespawnAll();
             events.Reset();
             me->SummonCreature(NPC_APOTHECARY_FRYE, -205.449f, 2219.56f, 79.7633f, 0.7f);
             me->SummonCreature(NPC_APOTHECARY_BAXTER, -209.602f, 2215.42f, 79.7633f, 0.723503f);
         }
References SummonList::DespawnAll(), FACTION_FRIENDLY, ScriptedAI::me, NPC_APOTHECARY_BAXTER, NPC_APOTHECARY_FRYE, Unit::SetFaction(), speachTimer, WorldObject::SummonCreature(), and summons.
UpdateAI()
void npc_love_in_air_hummel::npc_love_in_air_hummelAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 391 of file love_in_air.cpp.
         {
             if (speachTimer)
             {
                 speachTimer += diff;
                 if (speachTimer < 10000)
                 {
                     me->AI()->Talk(SAY_HUMMEL_0);
                     speachTimer = 10000;
                 }
                 else if (speachTimer >= 16000 && speachTimer < 20000)
                 {
                     me->AI()->Talk(SAY_HUMMEL_1);
                     speachTimer = 20000;
                 }
                 else if (speachTimer >= 26000 && speachTimer < 30000)
                 {
                     me->AI()->Talk(SAY_HUMMEL_2);
                     speachTimer = 0;
                     me->SetFaction(FACTION_MONSTER_2);
                     me->SetInCombatWithZone();
                     if (Unit* target = SelectTargetFromPlayerList(40.0f))
                     {
                         AttackStart(target);
                         events.ScheduleEvent(EVENT_CALL_BAXTER, 10000);
                         events.ScheduleEvent(EVENT_CALL_FRYE, 20000);
                         events.ScheduleEvent(EVENT_SPELL_PERFUME_SPRAY, 7000);
                         events.ScheduleEvent(EVENT_SPELL_CHAIN_REACTION, 12000);
                     }
                     else
                         EnterEvadeMode();
                 }
                 return;
             }
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_CALL_BAXTER:
                     {
                         EntryCheckPredicate pred(NPC_APOTHECARY_BAXTER);
                         summons.DoAction(ACTION_RELEASE_HELPER, pred);
                         break;
                     }
                 case EVENT_CALL_FRYE:
                     {
                         EntryCheckPredicate pred(NPC_APOTHECARY_FRYE);
                         summons.DoAction(ACTION_RELEASE_HELPER, pred);
                         break;
                     }
                 case EVENT_SPELL_PERFUME_SPRAY:
                     me->CastSpell(me->GetVictim(), SPELL_ALLURING_PERFUME_SPRAY, false);
                     events.RepeatEvent(6000);
                     break;
                 case EVENT_SPELL_CHAIN_REACTION:
                     me->CastSpell(me->GetVictim(), SPELL_CHAIN_REACTION, false);
                     events.RepeatEvent(12000);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References ACTION_RELEASE_HELPER, Creature::AI(), ScriptedAI::AttackStart(), Unit::CastSpell(), SummonList::DoAction(), UnitAI::DoMeleeAttackIfReady(), CreatureAI::EnterEvadeMode(), EVENT_CALL_BAXTER, EVENT_CALL_FRYE, EVENT_SPELL_CHAIN_REACTION, EVENT_SPELL_PERFUME_SPRAY, FACTION_MONSTER_2, Unit::GetVictim(), Unit::HasUnitState(), ScriptedAI::me, NPC_APOTHECARY_BAXTER, NPC_APOTHECARY_FRYE, SAY_HUMMEL_0, SAY_HUMMEL_1, SAY_HUMMEL_2, ScriptedAI::SelectTargetFromPlayerList(), Unit::SetFaction(), Creature::SetInCombatWithZone(), speachTimer, SPELL_ALLURING_PERFUME_SPRAY, SPELL_CHAIN_REACTION, summons, CreatureAI::Talk(), UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
events
EventMap npc_love_in_air_hummel::npc_love_in_air_hummelAI::events
Definition at line 345 of file love_in_air.cpp.
speachTimer
uint32 npc_love_in_air_hummel::npc_love_in_air_hummelAI::speachTimer
Definition at line 346 of file love_in_air.cpp.
Referenced by DoAction(), Reset(), and UpdateAI().
summons
SummonList npc_love_in_air_hummel::npc_love_in_air_hummelAI::summons
Definition at line 344 of file love_in_air.cpp.
Referenced by JustSummoned(), Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Events/love_in_air.cpp