Azerotcore-wotlk: npc_toc_rogue::npc_toc_rogueAI Struct Reference
npc_toc_rogue::npc_toc_rogueAI Struct Reference
Public Member Functions
npc_toc_rogueAI (Creature *pCreature)
bool myCanCast ()
void UpdateAI (uint32 diff) override
Public Member Functions inherited from boss_faction_championsAI
boss_faction_championsAI (Creature *pCreature, uint32 aitype)
void EnterCombat (Unit *) override
void AttackStart (Unit *who) override
float GetThreatMod (float dist, float, uint32 health, uint32, Unit *target)
void RecalculateThreat ()
void EventMapGCD (EventMap &e, uint32 delay, uint32 gcd=0)
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void EnterEvadeMode () override
bool IsCCed ()
Creature * SelectTarget_MostHPLostFriendlyMissingBuff (uint32 spell, float range)
uint32 EnemiesInRange (float distance)
Unit * SelectEnemyCaster (bool casting, float range)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
Public Attributes inherited from boss_faction_championsAI
InstanceScript * pInstance
uint32 mAIType
uint32 threatTimer
uint32 powerTimer
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1875 of file boss_faction_champions.cpp.
Constructor & Destructor Documentation
npc_toc_rogueAI()
npc_toc_rogue::npc_toc_rogueAI::npc_toc_rogueAI (Creature * pCreature) inline
Definition at line 1877 of file boss_faction_champions.cpp.
                                              : boss_faction_championsAI(pCreature, AI_MELEE)
         {
             SetEquipmentSlots(false, 47422, 49982, EQUIP_NO_CHANGE);
             me->setPowerType(POWER_ENERGY);
             events.Reset();
             events.RescheduleEvent(EVENT_SPELL_FAN_OF_KNIVES, 10000);
             events.RescheduleEvent(EVENT_SPELL_BLIND, urand(10000, 15000));
             events.RescheduleEvent(EVENT_SPELL_CLOAK, 10000);
             events.RescheduleEvent(EVENT_SPELL_BLADE_FLURRY, urand(20000, 40000));
             //events.RescheduleEvent(EVENT_SPELL_SHADOWSTEP, urand(15000,25000));
             events.RescheduleEvent(EVENT_SPELL_HEMORRHAGE, urand(3000, 5000));
             events.RescheduleEvent(EVENT_SPELL_EVISCERATE, urand(20000, 25000));
         }
References EQUIP_NO_CHANGE, EVENT_SPELL_BLADE_FLURRY, EVENT_SPELL_BLIND, EVENT_SPELL_CLOAK, EVENT_SPELL_EVISCERATE, EVENT_SPELL_FAN_OF_KNIVES, EVENT_SPELL_HEMORRHAGE, ScriptedAI::me, POWER_ENERGY, ScriptedAI::SetEquipmentSlots(), Unit::setPowerType(), and urand().
Member Function Documentation
myCanCast()
bool npc_toc_rogue::npc_toc_rogueAI::myCanCast () inline
Definition at line 1893 of file boss_faction_champions.cpp.
         {
             return !(me->HasUnitState(UNIT_STATE_CASTING) || IsCCed());
         }
References Unit::HasUnitState(), boss_faction_championsAI::IsCCed(), ScriptedAI::me, and UNIT_STATE_CASTING.
Referenced by UpdateAI().
UpdateAI()
void npc_toc_rogue::npc_toc_rogueAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from boss_faction_championsAI.
Definition at line 1898 of file boss_faction_champions.cpp.
         {
             boss_faction_championsAI::UpdateAI(diff);
             if( !UpdateVictim() )
                 return;
             events.Update(diff);
             if( !myCanCast() )
                 return;
             switch( events.ExecuteEvent() )
             {
                 case 0:
                     break;
                 case EVENT_SPELL_FAN_OF_KNIVES:
                     if( me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISARMED) )
                     {
                         events.RepeatEvent(5000);
                         break;
                     }
                     if( EnemiesInRange(10.0f) >= 3 )
                     {
                         me->CastSpell(me->GetVictim(), SPELL_FAN_OF_KNIVES, false);
                         events.RepeatEvent(urand(6000, 10000));
                         EventMapGCD(events, 1500);
                     }
                     else
                         events.RepeatEvent(5000);
                     break;
                 case EVENT_SPELL_BLIND:
                     if( Unit* target = SelectTarget(SELECT_TARGET_BOTTOMAGGRO, 0, 20.0f, true) )
                     {
                         me->CastSpell(target, SPELL_BLIND, false);
                         events.RepeatEvent(120000);
                         EventMapGCD(events, 1500);
                     }
                     else
                         events.RepeatEvent(5000);
                     break;
                 case EVENT_SPELL_CLOAK:
                     if( HealthBelowPct(50) )
                     {
                         me->CastSpell(me, SPELL_CLOAK, false);
                         events.RepeatEvent(90000);
                         EventMapGCD(events, 1500);
                     }
                     else
                         events.RepeatEvent(6000);
                     break;
                 case EVENT_SPELL_BLADE_FLURRY:
                     if( me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISARMED) )
                         events.RepeatEvent(5000);
                     else
                     {
                         me->CastSpell(me, SPELL_BLADE_FLURRY, false);
                         events.RepeatEvent(120000);
                         EventMapGCD(events, 1500);
                     }
                     break;
                 case EVENT_SPELL_SHADOWSTEP:
                     if( me->GetVictim() && me->GetDistance2d(me->GetVictim()) < 40.0f && me->GetDistance2d(me->GetVictim()) > 10.0f )
                     {
                         me->CastSpell(me->GetVictim(), SPELL_SHADOWSTEP, false);
                         events.RepeatEvent(30000);
                         EventMapGCD(events, 1500);
                     }
                     else
                         events.RepeatEvent(5000);
                     break;
                 case EVENT_SPELL_HEMORRHAGE:
                     if( me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISARMED) )
                     {
                         events.RepeatEvent(5000);
                         break;
                     }
                     if( me->GetVictim() && me->GetDistance2d(me->GetVictim()) <= 5.0f )
                     {
                         me->CastSpell(me->GetVictim(), SPELL_HEMORRHAGE, false);
                         events.RepeatEvent(5000);
                         EventMapGCD(events, 1500);
                     }
                     else
                         events.RepeatEvent(5000);
                     break;
                 case EVENT_SPELL_EVISCERATE:
                     if( me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISARMED) )
                     {
                         events.RepeatEvent(5000);
                         break;
                     }
                     if( me->GetVictim() && me->GetDistance2d(me->GetVictim()) <= 5.0f )
                     {
                         me->CastSpell(me->GetVictim(), SPELL_EVISCERATE, false);
                         events.RepeatEvent(urand(15000, 25000));
                         EventMapGCD(events, 1500);
                     }
                     else
                         events.RepeatEvent(5000);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), boss_faction_championsAI::EnemiesInRange(), EVENT_SPELL_BLADE_FLURRY, EVENT_SPELL_BLIND, EVENT_SPELL_CLOAK, EVENT_SPELL_EVISCERATE, EVENT_SPELL_FAN_OF_KNIVES, EVENT_SPELL_HEMORRHAGE, EVENT_SPELL_SHADOWSTEP, boss_faction_championsAI::EventMapGCD(), WorldObject::GetDistance2d(), Unit::GetVictim(), Object::HasFlag(), ScriptedAI::HealthBelowPct(), ScriptedAI::me, myCanCast(), SELECT_TARGET_BOTTOMAGGRO, UnitAI::SelectTarget(), SPELL_BLADE_FLURRY, SPELL_BLIND, SPELL_CLOAK, SPELL_EVISCERATE, SPELL_FAN_OF_KNIVES, SPELL_HEMORRHAGE, SPELL_SHADOWSTEP, UNIT_FIELD_FLAGS, UNIT_FLAG_DISARMED, boss_faction_championsAI::UpdateAI(), CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
events
EventMap npc_toc_rogue::npc_toc_rogueAI::events
Definition at line 1891 of file boss_faction_champions.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_faction_champions.cpp