Azerotcore-wotlk: npc_grandmother Class Reference
npc_grandmother Class Reference
Public Member Functions
npc_grandmother ()
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
bool OnGossipHello (Player *player, Creature *creature) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 810 of file bosses_opera.cpp.
Constructor & Destructor Documentation
npc_grandmother()
npc_grandmother::npc_grandmother () inline
Definition at line 813 of file bosses_opera.cpp.
 : CreatureScript("npc_grandmother") { }
Member Function Documentation
OnGossipHello()
bool npc_grandmother::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 829 of file bosses_opera.cpp.
     {
         AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_GRANDMA, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF);
         SendGossipMenuFor(player, 8990, creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, GOSSIP_GRANDMA, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, and SendGossipMenuFor().
OnGossipSelect()
bool npc_grandmother::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 815 of file bosses_opera.cpp.
     {
         ClearGossipMenuFor(player);
         if (action == GOSSIP_ACTION_INFO_DEF)
         {
             if (Creature* pBigBadWolf = creature->SummonCreature(CREATURE_BIG_BAD_WOLF, 0.0f, 0.0f, 0.0f, 0.0f, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, HOUR * 2 * IN_MILLISECONDS))
                 pBigBadWolf->AI()->AttackStart(player);
             creature->DespawnOrUnsummon();
         }
         return true;
     }
References ClearGossipMenuFor(), CREATURE_BIG_BAD_WOLF, Creature::DespawnOrUnsummon(), GOSSIP_ACTION_INFO_DEF, HOUR, IN_MILLISECONDS, WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_OR_DEAD_DESPAWN.
The documentation for this class was generated from the following file:
src/server/scripts/EasternKingdoms/Karazhan/bosses_opera.cpp