Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/util.h File Reference
util.h File Reference
Macros
#define UTIL_INLINE static inline
#define JEMALLOC_ALLOC_JUNK ((uint8_t)0xa5)
#define JEMALLOC_FREE_JUNK ((uint8_t)0x5a)
#define JEMALLOC_ARG_CONCAT(...) __VA_ARGS__
#define STRINGIFY_HELPER(x) #x
#define STRINGIFY(x) STRINGIFY_HELPER(x)
#define JEMALLOC_CC_SILENCE_INIT(v) = v
#define likely(x) !!(x)
#define unlikely(x) !!(x)
#define unreachable() JEMALLOC_INTERNAL_UNREACHABLE()
Functions
UTIL_INLINE void set_errno (int errnum)
UTIL_INLINE int get_errno (void)
Macro Definition Documentation
JEMALLOC_ALLOC_JUNK
#define JEMALLOC_ALLOC_JUNK ((uint8_t)0xa5)
Definition at line 8 of file util.h.
JEMALLOC_ARG_CONCAT
#define JEMALLOC_ARG_CONCAT (...) __VA_ARGS__
Definition at line 18 of file util.h.
JEMALLOC_CC_SILENCE_INIT
#define JEMALLOC_CC_SILENCE_INIT (v) = v
Definition at line 29 of file util.h.
JEMALLOC_FREE_JUNK
#define JEMALLOC_FREE_JUNK ((uint8_t)0x5a)
Definition at line 11 of file util.h.
likely
#define likely (x) !!(x)
Definition at line 35 of file util.h.
STRINGIFY
#define STRINGIFY (x) STRINGIFY_HELPER(x)
Definition at line 22 of file util.h.
STRINGIFY_HELPER
#define STRINGIFY_HELPER (x) #x
Definition at line 21 of file util.h.
unlikely
#define unlikely (x) !!(x)
Definition at line 36 of file util.h.
unreachable
#define unreachable () JEMALLOC_INTERNAL_UNREACHABLE()
Definition at line 43 of file util.h.
UTIL_INLINE
#define UTIL_INLINE static inline
Definition at line 4 of file util.h.
Function Documentation
get_errno()
UTIL_INLINE int get_errno (void)
Definition at line 57 of file util.h.
                 {
 #ifdef _WIN32
     return GetLastError();
 #else
     return errno;
 #endif
 }
References errno.
Referenced by huge_ralloc(), malloc_conf_multi_sizes_next(), malloc_vsnprintf(), os_pages_unmap(), pages_map(), and pages_unmap().
set_errno()
UTIL_INLINE void set_errno (int errnum)
Definition at line 47 of file util.h.
                       {
 #ifdef _WIN32
     SetLastError(errnum);
 #else
     errno = errnum;
 #endif
 }
References errno.
Referenced by imalloc_body(), imalloc_init_check(), je_realloc(), malloc_conf_multi_sizes_next(), malloc_strtoumax(), malloc_vsnprintf(), and obtain_malloc_conf().