Azerotcore-wotlk: boss_magus_telestra::boss_magus_telestraAI Struct Reference
boss_magus_telestra::boss_magus_telestraAI Struct Reference
Public Member Functions
boss_magus_telestraAI (Creature *creature)
void Reset () override
uint32 GetData (uint32 data) const override
void EnterCombat (Unit *who) override
void AttackStart (Unit *who) override
void JustDied (Unit *killer) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *summon) override
void SpellHit (Unit *caster, const SpellInfo *spellInfo) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
uint8 copiesDied
bool achievement
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 86 of file boss_magus_telestra.cpp.
Constructor & Destructor Documentation
boss_magus_telestraAI()
boss_magus_telestra::boss_magus_telestraAI::boss_magus_telestraAI (Creature * creature) inline
Definition at line 88 of file boss_magus_telestra.cpp.
                                                   : BossAI(creature, DATA_MAGUS_TELESTRA_EVENT)
         {
         }
Member Function Documentation
AttackStart()
void boss_magus_telestra::boss_magus_telestraAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 125 of file boss_magus_telestra.cpp.
         {
             if (who && me->Attack(who, true))
                 me->GetMotionMaster()->MoveChase(who, 20.0f);
         }
References Unit::Attack(), Unit::GetMotionMaster(), ScriptedAI::me, and MotionMaster::MoveChase().
EnterCombat()
void boss_magus_telestra::boss_magus_telestraAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from BossAI.
Definition at line 112 of file boss_magus_telestra.cpp.
         {
             BossAI::EnterCombat(who);
             Talk(SAY_AGGRO);
             events.ScheduleEvent(EVENT_MAGUS_ICE_NOVA, 10000);
             events.ScheduleEvent(EVENT_MAGUS_FIREBOMB, 0);
             events.ScheduleEvent(EVENT_MAGUS_GRAVITY_WELL, 20000);
             events.ScheduleEvent(EVENT_MAGUS_HEALTH1, 1000);
             if (IsHeroic())
                 events.ScheduleEvent(EVENT_MAGUS_HEALTH2, 1000);
         }
References BossAI::EnterCombat(), EVENT_MAGUS_FIREBOMB, EVENT_MAGUS_GRAVITY_WELL, EVENT_MAGUS_HEALTH1, EVENT_MAGUS_HEALTH2, EVENT_MAGUS_ICE_NOVA, ScriptedAI::IsHeroic(), SAY_AGGRO, and CreatureAI::Talk().
GetData()
uint32 boss_magus_telestra::boss_magus_telestraAI::GetData (uint32 data) const inline override virtual
Reimplemented from UnitAI.
Definition at line 105 of file boss_magus_telestra.cpp.
         {
             if (data == me->GetEntry())
                 return achievement;
             return 0;
         }
References achievement, Object::GetEntry(), and ScriptedAI::me.
JustDied()
void boss_magus_telestra::boss_magus_telestraAI::JustDied (Unit * killer) inline override virtual
Reimplemented from BossAI.
Definition at line 131 of file boss_magus_telestra.cpp.
         {
             BossAI::JustDied(killer);
             Talk(SAY_DEATH);
         }
References BossAI::JustDied(), SAY_DEATH, and CreatureAI::Talk().
JustSummoned()
void boss_magus_telestra::boss_magus_telestraAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
Definition at line 146 of file boss_magus_telestra.cpp.
         {
             summons.Summon(summon);
             summon->SetInCombatWithZone();
         }
References Creature::SetInCombatWithZone(), SummonList::Summon(), and BossAI::summons.
KilledUnit()
void boss_magus_telestra::boss_magus_telestraAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 137 of file boss_magus_telestra.cpp.
         {
             if (events.GetNextEventTime(EVENT_KILL_TALK) == 0)
             {
                 Talk(SAY_KILL);
                 events.ScheduleEvent(EVENT_KILL_TALK, 6000);
             }
         }
References EVENT_KILL_TALK, SAY_KILL, and CreatureAI::Talk().
Reset()
void boss_magus_telestra::boss_magus_telestraAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 95 of file boss_magus_telestra.cpp.
         {
             BossAI::Reset();
             copiesDied = 0;
             achievement = true;
             if (IsHeroic() && sGameEventMgr->IsActiveEvent(GAME_EVENT_WINTER_VEIL) && !me->HasAura(SPELL_WEAR_CHRISTMAS_HAT))
                 me->AddAura(SPELL_WEAR_CHRISTMAS_HAT, me);
         }
References achievement, Unit::AddAura(), copiesDied, GAME_EVENT_WINTER_VEIL, Unit::HasAura(), ScriptedAI::IsHeroic(), ScriptedAI::me, BossAI::Reset(), sGameEventMgr, and SPELL_WEAR_CHRISTMAS_HAT.
SpellHit()
void boss_magus_telestra::boss_magus_telestraAI::SpellHit (Unit * caster, const SpellInfo * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 152 of file boss_magus_telestra.cpp.
         {
             if (spellInfo->Id >= SPELL_FIRE_MAGUS_DEATH && spellInfo->Id <= SPELL_ARCANE_MAGUS_DEATH && caster->ToCreature())
             {
                 events.ScheduleEvent(EVENT_MAGUS_FAIL_ACHIEVEMENT, 5000);
                 caster->ToCreature()->DespawnOrUnsummon(1000);
                 if (++copiesDied >= 3)
                 {
                     copiesDied = 0;
                     events.CancelEvent(EVENT_MAGUS_FAIL_ACHIEVEMENT);
                     events.ScheduleEvent(EVENT_MAGUS_MERGED, 5000);
                     me->CastSpell(me, SPELL_BURNING_WINDS, true);
                 }
             }
         }
References Unit::CastSpell(), copiesDied, Creature::DespawnOrUnsummon(), EVENT_MAGUS_FAIL_ACHIEVEMENT, EVENT_MAGUS_MERGED, SpellInfo::Id, ScriptedAI::me, SPELL_ARCANE_MAGUS_DEATH, SPELL_BURNING_WINDS, SPELL_FIRE_MAGUS_DEATH, and Object::ToCreature().
UpdateAI()
void boss_magus_telestra::boss_magus_telestraAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 169 of file boss_magus_telestra.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_MAGUS_HEALTH1:
                     if (me->HealthBelowPct(51))
                     {
                         me->CastSpell(me, SPELL_START_SUMMON_CLONES, false);
                         events.ScheduleEvent(EVENT_MAGUS_RELOCATE, 3500);
                         Talk(SAY_SPLIT);
                         break;
                     }
                     events.ScheduleEvent(EVENT_MAGUS_HEALTH1, 1000);
                     break;
                 case EVENT_MAGUS_HEALTH2:
                     if (me->HealthBelowPct(11))
                     {
                         me->CastSpell(me, SPELL_START_SUMMON_CLONES, false);
                         events.ScheduleEvent(EVENT_MAGUS_RELOCATE, 3500);
                         Talk(SAY_SPLIT);
                         break;
                     }
                     events.ScheduleEvent(EVENT_MAGUS_HEALTH2, 1000);
                     break;
                 case EVENT_MAGUS_FIREBOMB:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
                         me->CastSpell(target, SPELL_FIREBOMB, false);
                     events.ScheduleEvent(EVENT_MAGUS_FIREBOMB, 3000);
                     break;
                 case EVENT_MAGUS_ICE_NOVA:
                     me->CastSpell(me, SPELL_ICE_NOVA, false);
                     events.ScheduleEvent(EVENT_MAGUS_ICE_NOVA, 15000);
                     break;
                 case EVENT_MAGUS_GRAVITY_WELL:
                     me->CastSpell(me, SPELL_GRAVITY_WELL, false);
                     events.ScheduleEvent(EVENT_MAGUS_GRAVITY_WELL, 15000);
                     break;
                 case EVENT_MAGUS_FAIL_ACHIEVEMENT:
                     achievement = false;
                     break;
                 case EVENT_MAGUS_RELOCATE:
                     me->NearTeleportTo(505.04f, 88.915f, -16.13f, 2.98f);
                     break;
                 case EVENT_MAGUS_MERGED:
                     me->CastSpell(me, SPELL_TELESTRA_BACK, true);
                     me->RemoveAllAuras();
                     Talk(SAY_MERGE);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References achievement, Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), EVENT_MAGUS_FAIL_ACHIEVEMENT, EVENT_MAGUS_FIREBOMB, EVENT_MAGUS_GRAVITY_WELL, EVENT_MAGUS_HEALTH1, EVENT_MAGUS_HEALTH2, EVENT_MAGUS_ICE_NOVA, EVENT_MAGUS_MERGED, EVENT_MAGUS_RELOCATE, Unit::HasUnitState(), Unit::HealthBelowPct(), ScriptedAI::me, Unit::NearTeleportTo(), Unit::RemoveAllAuras(), SAY_MERGE, SAY_SPLIT, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), SPELL_FIREBOMB, SPELL_GRAVITY_WELL, SPELL_ICE_NOVA, SPELL_START_SUMMON_CLONES, SPELL_TELESTRA_BACK, CreatureAI::Talk(), UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
achievement
bool boss_magus_telestra::boss_magus_telestraAI::achievement
Definition at line 93 of file boss_magus_telestra.cpp.
Referenced by GetData(), Reset(), and UpdateAI().
copiesDied
uint8 boss_magus_telestra::boss_magus_telestraAI::copiesDied
Definition at line 92 of file boss_magus_telestra.cpp.
Referenced by Reset(), and SpellHit().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Nexus/Nexus/boss_magus_telestra.cpp