Azerotcore-wotlk: Acore::LocalizedPacketListDo< Builder > Class Template Reference
Acore::LocalizedPacketListDo< Builder > Class Template Reference
#include <GridNotifiers.h>
Public Types
typedef std::vector< WorldPacket * > WorldPacketList
Public Member Functions
LocalizedPacketListDo (Builder &builder)
~LocalizedPacketListDo ()
void operator() (Player *p)
Private Attributes
Builder & i_builder
std::vector< WorldPacketList > i_data_cache
Detailed Description
template<class Builder>
class Acore::LocalizedPacketListDo< Builder >
Definition at line 1605 of file GridNotifiers.h.
Member Typedef Documentation
WorldPacketList
template<class Builder > typedef std::vector<WorldPacket*> Acore::LocalizedPacketListDo< Builder >::WorldPacketList
Definition at line 1608 of file GridNotifiers.h.
Constructor & Destructor Documentation
LocalizedPacketListDo()
template<class Builder > Acore::LocalizedPacketListDo< Builder >::LocalizedPacketListDo (Builder & builder) inline explicit
Definition at line 1609 of file GridNotifiers.h.
 : i_builder(builder) {}
~LocalizedPacketListDo()
template<class Builder > Acore::LocalizedPacketListDo< Builder >::~LocalizedPacketListDo () inline
Definition at line 1611 of file GridNotifiers.h.
         {
             for (size_t i = 0; i < i_data_cache.size(); ++i)
                 for (size_t j = 0; j < i_data_cache[i].size(); ++j)
                     delete i_data_cache[i][j];
         }
References Acore::LocalizedPacketListDo< Builder >::i_data_cache.
Member Function Documentation
operator()()
template<class Builder > void Acore::LocalizedPacketListDo< Builder >::operator() (Player * p)
Definition at line 562 of file GridNotifiersImpl.h.
 {
     LocaleConstant loc_idx = p->GetSession()->GetSessionDbLocaleIndex();
     uint32 cache_idx = loc_idx + 1;
     WorldPacketList* data_list;
     // create if not cached yet
     if (i_data_cache.size() < cache_idx + 1 || i_data_cache[cache_idx].empty())
     {
         if (i_data_cache.size() < cache_idx + 1)
             i_data_cache.resize(cache_idx + 1);
         data_list = &i_data_cache[cache_idx];
         i_builder(*data_list, loc_idx);
     }
     else
         data_list = &i_data_cache[cache_idx];
     for (size_t i = 0; i < data_list->size(); ++i)
         p->SendDirectMessage((*data_list)[i]);
 }
References Player::GetSession(), WorldSession::GetSessionDbLocaleIndex(), and Player::SendDirectMessage().
Member Data Documentation
i_builder
template<class Builder > Builder& Acore::LocalizedPacketListDo< Builder >::i_builder private
Definition at line 1620 of file GridNotifiers.h.
i_data_cache
template<class Builder > std::vector<WorldPacketList> Acore::LocalizedPacketListDo< Builder >::i_data_cache private
Definition at line 1621 of file GridNotifiers.h.
Referenced by Acore::LocalizedPacketListDo< Builder >::~LocalizedPacketListDo().
The documentation for this class was generated from the following files:
src/server/game/Grids/Notifiers/GridNotifiers.h
src/server/game/Grids/Notifiers/GridNotifiersImpl.h