Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/bin.h File Reference
bin.h File Reference
#include "jemalloc/internal/bin_stats.h"
#include "jemalloc/internal/bin_types.h"
#include "jemalloc/internal/extent_types.h"
#include "jemalloc/internal/extent_structs.h"
#include "jemalloc/internal/mutex.h"
#include "jemalloc/internal/sc.h"
Classes
struct bin_info_s
struct bin_s
struct bins_s
Typedefs
typedef struct bin_info_s bin_info_t
typedef struct bin_s bin_t
typedef struct bins_s bins_t
Functions
void bin_shard_sizes_boot (unsigned bin_shards[SC_NBINS])
bool bin_update_shard_size (unsigned bin_shards[SC_NBINS], size_t start_size, size_t end_size, size_t nshards)
void bin_boot (sc_data_t *sc_data, unsigned bin_shard_sizes[SC_NBINS])
bool bin_init (bin_t *bin)
void bin_prefork (tsdn_t *tsdn, bin_t *bin)
void bin_postfork_parent (tsdn_t *tsdn, bin_t *bin)
void bin_postfork_child (tsdn_t *tsdn, bin_t *bin)
static void bin_stats_merge (tsdn_t *tsdn, bin_stats_t *dst_bin_stats, bin_t *bin)
Variables
bin_info_t bin_infos [SC_NBINS]
Typedef Documentation
bin_info_t
typedef struct bin_info_s bin_info_t
Definition at line 1 of file bin.h.
bin_t
typedef struct bin_s bin_t
Definition at line 56 of file bin.h.
bins_t
typedef struct bins_s bins_t
Definition at line 56 of file bin.h.
Function Documentation
bin_boot()
void bin_boot (sc_data_t * sc_data, unsigned bin_shard_sizes[SC_NBINS])
Definition at line 62 of file bin.c.
{
     assert(sc_data->initialized);
     bin_infos_init(sc_data, bin_shard_sizes, bin_infos);
 }
References assert(), bin_infos, bin_infos_init(), and sc_data_s::initialized.
bin_init()
bool bin_init (bin_t * bin)
Definition at line 68 of file bin.c.
                      {
     if (malloc_mutex_init(&bin->lock, "bin", WITNESS_RANK_BIN,
         malloc_mutex_rank_exclusive)) {
         return true;
     }
     bin->slabcur = NULL;
     extent_heap_new(&bin->slabs_nonfull);
     extent_list_init(&bin->slabs_full);
     if (config_stats) {
         memset(&bin->stats, 0, sizeof(bin_stats_t));
     }
     return false;
 }
References config_stats, extent_heap_new, extent_list_init(), bin_s::lock, malloc_mutex_init, malloc_mutex_rank_exclusive, memset, NULL, bin_s::slabcur, bin_s::slabs_full, bin_s::slabs_nonfull, bin_s::stats, and WITNESS_RANK_BIN.
bin_postfork_child()
void bin_postfork_child (tsdn_t * tsdn, bin_t * bin)
Definition at line 93 of file bin.c.
{
     malloc_mutex_postfork_child(tsdn, &bin->lock);
 }
References bin_s::lock, and malloc_mutex_postfork_child.
bin_postfork_parent()
void bin_postfork_parent (tsdn_t * tsdn, bin_t * bin)
Definition at line 88 of file bin.c.
{
     malloc_mutex_postfork_parent(tsdn, &bin->lock);
 }
References bin_s::lock, and malloc_mutex_postfork_parent.
bin_prefork()
void bin_prefork (tsdn_t * tsdn, bin_t * bin)
Definition at line 83 of file bin.c.
{
     malloc_mutex_prefork(tsdn, &bin->lock);
 }
References bin_s::lock, and malloc_mutex_prefork.
bin_shard_sizes_boot()
void bin_shard_sizes_boot (unsigned bin_shards[SC_NBINS])
Definition at line 54 of file bin.c.
{
     /* Load the default number of shards. */
     for (unsigned i = 0; i < SC_NBINS; i++) {
         bin_shard_sizes[i] = N_BIN_SHARDS_DEFAULT;
     }
 }
References N_BIN_SHARDS_DEFAULT, and SC_NBINS.
bin_stats_merge()
static void bin_stats_merge (tsdn_t * tsdn, bin_stats_t * dst_bin_stats, bin_t * bin) inline static
Definition at line 107 of file bin.h.
{
     malloc_mutex_lock(tsdn, &bin->lock);
     malloc_mutex_prof_accum(tsdn, &dst_bin_stats->mutex_data, &bin->lock);
     dst_bin_stats->nmalloc += bin->stats.nmalloc;
     dst_bin_stats->ndalloc += bin->stats.ndalloc;
     dst_bin_stats->nrequests += bin->stats.nrequests;
     dst_bin_stats->curregs += bin->stats.curregs;
     dst_bin_stats->nfills += bin->stats.nfills;
     dst_bin_stats->nflushes += bin->stats.nflushes;
     dst_bin_stats->nslabs += bin->stats.nslabs;
     dst_bin_stats->reslabs += bin->stats.reslabs;
     dst_bin_stats->curslabs += bin->stats.curslabs;
     dst_bin_stats->nonfull_slabs += bin->stats.nonfull_slabs;
     malloc_mutex_unlock(tsdn, &bin->lock);
 }
References bin_stats_s::curregs, bin_stats_s::curslabs, bin_s::lock, malloc_mutex_lock(), malloc_mutex_prof_accum(), malloc_mutex_unlock(), bin_stats_s::mutex_data, bin_stats_s::ndalloc, bin_stats_s::nfills, bin_stats_s::nflushes, bin_stats_s::nmalloc, bin_stats_s::nonfull_slabs, bin_stats_s::nrequests, bin_stats_s::nslabs, bin_stats_s::reslabs, and bin_s::stats.
Referenced by arena_stats_merge().
bin_update_shard_size()
bool bin_update_shard_size (unsigned bin_shards[SC_NBINS], size_t start_size, size_t end_size, size_t nshards)
Definition at line 30 of file bin.c.
{
     if (nshards > BIN_SHARDS_MAX || nshards == 0) {
         return true;
     }
     if (start_size > SC_SMALL_MAXCLASS) {
         return false;
     }
     if (end_size > SC_SMALL_MAXCLASS) {
         end_size = SC_SMALL_MAXCLASS;
     }
     /* Compute the index since this may happen before sz init. */
     szind_t ind1 = sz_size2index_compute(start_size);
     szind_t ind2 = sz_size2index_compute(end_size);
     for (unsigned i = ind1; i <= ind2; i++) {
         bin_shard_sizes[i] = (unsigned)nshards;
     }
     return false;
 }
References BIN_SHARDS_MAX, SC_SMALL_MAXCLASS, and sz_size2index_compute().
Variable Documentation
bin_infos
bin_info_t bin_infos[SC_NBINS] extern
Definition at line 9 of file bin.c.
Referenced by bin_boot(), and bin_infos_init().