Azerotcore-wotlk: TimeTrackerSmall Struct Reference
TimeTrackerSmall Struct Reference
#include <Timer.h>
Public Member Functions
TimeTrackerSmall (uint32 expiry=0)
void Update (int32 diff)
bool Passed () const
void Reset (uint32 interval)
int32 GetExpiry () const
Private Attributes
int32 i_expiryTime
Detailed Description
Definition at line 153 of file Timer.h.
Constructor & Destructor Documentation
TimeTrackerSmall()
TimeTrackerSmall::TimeTrackerSmall (uint32 expiry = 0) inline
Definition at line 156 of file Timer.h.
         : i_expiryTime(expiry)
     {
     }
Member Function Documentation
GetExpiry()
int32 TimeTrackerSmall::GetExpiry () const inline
Definition at line 176 of file Timer.h.
     {
         return i_expiryTime;
     }
References i_expiryTime.
Passed()
bool TimeTrackerSmall::Passed () const inline
Definition at line 166 of file Timer.h.
     {
         return i_expiryTime <= 0;
     }
References i_expiryTime.
Referenced by MotionTransport::Update(), and DynTreeImpl::update().
Reset()
void TimeTrackerSmall::Reset (uint32 interval) inline
Definition at line 171 of file Timer.h.
     {
         i_expiryTime = interval;
     }
References i_expiryTime.
Referenced by MotionTransport::Update(), and DynTreeImpl::update().
Update()
void TimeTrackerSmall::Update (int32 diff) inline
Definition at line 161 of file Timer.h.
     {
         i_expiryTime -= diff;
     }
References i_expiryTime.
Referenced by MotionTransport::Update(), and DynTreeImpl::update().
Member Data Documentation
i_expiryTime
int32 TimeTrackerSmall::i_expiryTime private
Definition at line 182 of file Timer.h.
Referenced by GetExpiry(), Passed(), Reset(), and Update().
The documentation for this struct was generated from the following file:
src/common/Utilities/Timer.h