Azerotcore-wotlk: G3D::FileSystem::Dir Class Reference
G3D::FileSystem::Dir Class Reference
Public Member Functions
bool contains (const std::string &child, bool caseSensitive=true) const
void computeZipListing (const std::string &zipfile, const std::string &pathInsideZipfile)
Dir ()
Public Attributes
bool exists
bool isZipfile
bool inZipfile
Array< Entry > nodeArray
double lastChecked
Detailed Description
Definition at line 102 of file FileSystem.h.
Constructor & Destructor Documentation
Dir()
G3D::FileSystem::Dir::Dir () inline
Definition at line 128 of file FileSystem.h.
 : exists(false), isZipfile(false), inZipfile(false), lastChecked(0) {}
Member Function Documentation
computeZipListing()
void G3D::FileSystem::Dir::computeZipListing (const std::string & zipfile, const std::string & pathInsideZipfile)
Compute the contents of nodeArray from this zipfile.
Definition at line 88 of file FileSystem.cpp.
{
 #if _HAVE_ZIP /* G3DFIX: Use ZIP-library only if defined */
     const std::string& pathInsideZipfile = FilePath::canonicalize(_pathInsideZipfile);
     struct zip* z = zip_open( FilePath::removeTrailingSlash(zipfile).c_str(), ZIP_CHECKCONS, NULL );
     debugAssert(z);
     int count = zip_get_num_files( z );
     Set<std::string> alreadyAdded;
     for (int i = 0; i < count; ++i) {
         struct zip_stat info;
         zip_stat_init( &info );    // TODO: Docs unclear if zip_stat_init is required.
         zip_stat_index( z, i, ZIP_FL_NOCASE, &info );
         // Fully-qualified name of a file inside zipfile
         std::string name = FilePath::canonicalize(info.name);
         if (beginsWith(name, pathInsideZipfile)) {
             // We found something inside the directory we were looking for,
             // so the directory itself must exist
             exists = true;
             // For building the cached directory listing, extract only elements that do not contain
             // additional subdirectories.
             size_t start = pathInsideZipfile.size();
             if ((name.length() > start) && isSlash(name[start])) {
                 ++start;
             }
             size_t end = findSlash(name, start);
             if (end == std::string::npos) {
                 // There are no more slashes; add this name
                 name = name.substr(start);
                 if (alreadyAdded.insert(name)) {
                     Entry& e = nodeArray.next();
                     e.name = name;
                     e.type = FILE_TYPE;
                 }
             } else {
                 // There are more slashes, indicating that this is a directory
                 name = name.substr(start, end);
                 if (alreadyAdded.insert(name)) {
                     Entry& e = nodeArray.next();
                     e.name = FilePath::removeTrailingSlash(name);
                     e.type = DIR_TYPE;
                 }
             }
         }
     }
     zip_close(z);
     z = NULL;
 #else
     (void)zipfile;
     (void)_pathInsideZipfile;
 #endif
 }
References G3D::beginsWith(), G3D::FilePath::canonicalize(), count(), debugAssert, G3D::FileSystem::DIR_TYPE, G3D::FileSystem::exists(), G3D::FileSystem::FILE_TYPE, G3D::findSlash(), G3D::Set< T, HashFunc, EqualsFunc >::insert(), G3D::isSlash(), name, G3D::FileSystem::Entry::name, NULL, G3D::FilePath::removeTrailingSlash(), G3D::FileSystem::Entry::type, and G3D::z.
Referenced by G3D::FileSystem::getContents().
contains()
bool G3D::FileSystem::Dir::contains (const std::string & child, bool caseSensitive = true) const
Definition at line 73 of file FileSystem.cpp.
{
     for (int i = 0; i < nodeArray.size(); ++i) {
         if (caseSensitive) {
             if (f == nodeArray[i].name) {
                 return true;
             }
         } else if (stricmp(f.c_str(), nodeArray[i].name.c_str()) == 0) {
             return true;
         }
     }
     return false;
 }
References f(), nodeArray, and stricmp.
Referenced by G3D::FileSystem::_exists().
Member Data Documentation
exists
bool G3D::FileSystem::Dir::exists
If false, this path did not exist (even inside a zipfile) when last checked, or it is not a directory.
Definition at line 106 of file FileSystem.h.
Referenced by G3D::FileSystem::_exists(), G3D::FileSystem::getContents(), and G3D::FileSystem::listHelper().
inZipfile
bool G3D::FileSystem::Dir::inZipfile
Definition at line 109 of file FileSystem.h.
Referenced by G3D::FileSystem::getContents().
isZipfile
bool G3D::FileSystem::Dir::isZipfile
Definition at line 108 of file FileSystem.h.
Referenced by G3D::FileSystem::getContents().
lastChecked
double G3D::FileSystem::Dir::lastChecked
When this entry was last updated
Definition at line 115 of file FileSystem.h.
Referenced by G3D::FileSystem::getContents().
nodeArray
Array<Entry> G3D::FileSystem::Dir::nodeArray
Files and directories
Definition at line 112 of file FileSystem.h.
Referenced by G3D::FileSystem::_exists(), contains(), G3D::FileSystem::getContents(), and G3D::FileSystem::listHelper().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/FileSystem.h
deps/g3dlite/source/FileSystem.cpp