Azerotcore-wotlk: deps/mysqllite/strings/my_strtoll10.c File Reference
my_strtoll10.c File Reference
#include <my_global.h>
#include <my_sys.h>
#include <m_string.h>
Macros
#define MAX_NEGATIVE_NUMBER ((ulonglong) LL(0x8000000000000000))
#define INIT_CNT 9
#define LFACTOR ULL(1000000000)
#define LFACTOR1 ULL(10000000000)
#define LFACTOR2 ULL(100000000000)
Functions
longlong my_strtoll10 (const char *nptr, char **endptr, int *error)
Variables
static unsigned long lfactor [9]
Macro Definition Documentation
INIT_CNT
#define INIT_CNT 9
Definition at line 21 of file my_strtoll10.c.
LFACTOR
#define LFACTOR ULL(1000000000)
Definition at line 22 of file my_strtoll10.c.
LFACTOR1
#define LFACTOR1 ULL(10000000000)
Definition at line 23 of file my_strtoll10.c.
LFACTOR2
#define LFACTOR2 ULL(100000000000)
Definition at line 24 of file my_strtoll10.c.
MAX_NEGATIVE_NUMBER
#define MAX_NEGATIVE_NUMBER ((ulonglong) LL(0x8000000000000000))
Definition at line 20 of file my_strtoll10.c.
Function Documentation
my_strtoll10()
longlong my_strtoll10 (const char * nptr, char ** endptr, int * error)
Definition at line 74 of file my_strtoll10.c.
 {
   const char *s, *end, *start, *n_end, *true_end;
   char *dummy;
   uchar c;
   unsigned long i, j, k;
   ulonglong li;
   int negative;
   ulong cutoff, cutoff2, cutoff3;
   s= nptr;
   /* If fixed length string */
   if (endptr)
   {
     end= *endptr;
     while (s != end && (*s == ' ' || *s == '\t'))
       s++;
     if (s == end)
       goto no_conv;
   }
   else
   {
     endptr= &dummy;             /* Easier end test */
     while (*s == ' ' || *s == '\t')
       s++;
     if (!*s)
       goto no_conv;
     /* This number must be big to guard against a lot of pre-zeros */
     end= s+65535;               /* Can't be longer than this */
   }
   /* Check for a sign.  */
   negative= 0;
   if (*s == '-')
   {
     *error= -1;                 /* Mark as negative number */
     negative= 1;
     if (++s == end)
       goto no_conv;
     cutoff=  MAX_NEGATIVE_NUMBER / LFACTOR2;
     cutoff2= (MAX_NEGATIVE_NUMBER % LFACTOR2) / 100;
     cutoff3=  MAX_NEGATIVE_NUMBER % 100;
   }
   else
   {
     *error= 0;
     if (*s == '+')
     {
       if (++s == end)
     goto no_conv;
     }
     cutoff=  ULONGLONG_MAX / LFACTOR2;
     cutoff2= ULONGLONG_MAX % LFACTOR2 / 100;
     cutoff3=  ULONGLONG_MAX % 100;
   }
   /* Handle case where we have a lot of pre-zero */
   if (*s == '0')
   {
     i= 0;
     do
     {
       if (++s == end)
     goto end_i;             /* Return 0 */
     }
     while (*s == '0');
     n_end= s+ INIT_CNT;
   }
   else
   {
     /* Read first digit to check that it's a valid number */
     if ((c= (*s-'0')) > 9)
       goto no_conv;
     i= c;
     n_end= ++s+ INIT_CNT-1;
   }
   /* Handle first 9 digits and store them in i */
   if (n_end > end)
     n_end= end;
   for (; s != n_end ; s++)
   {
     if ((c= (*s-'0')) > 9)
       goto end_i;
     i= i*10+c;
   }
   if (s == end)
     goto end_i;
   /* Handle next 9 digits and store them in j */
   j= 0;
   start= s;             /* Used to know how much to shift i */
   n_end= true_end= s + INIT_CNT;
   if (n_end > end)
     n_end= end;
   do
   {
     if ((c= (*s-'0')) > 9)
       goto end_i_and_j;
     j= j*10+c;
   } while (++s != n_end);
   if (s == end)
   {
     if (s != true_end)
       goto end_i_and_j;
     goto end3;
   }
   if ((c= (*s-'0')) > 9)
     goto end3;
   /* Handle the next 1 or 2 digits and store them in k */
   k=c;
   if (++s == end || (c= (*s-'0')) > 9)
     goto end4;
   k= k*10+c;
   *endptr= (char*) ++s;
   /* number string should have ended here */
   if (s != end && (c= (*s-'0')) <= 9)
     goto overflow;
   /* Check that we didn't get an overflow with the last digit */
   if (i > cutoff || (i == cutoff && ((j > cutoff2 || j == cutoff2) &&
                                      k > cutoff3)))
     goto overflow;
   li=i*LFACTOR2+ (ulonglong) j*100 + k;
   return (longlong) li;
 overflow:                   /* *endptr is set here */
   *error= MY_ERRNO_ERANGE;
   return negative ? LONGLONG_MIN : (longlong) ULONGLONG_MAX;
 end_i:
   *endptr= (char*) s;
   return (negative ? ((longlong) -(long) i) : (longlong) i);
 end_i_and_j:
   li= (ulonglong) i * lfactor[(uint) (s-start)] + j;
   *endptr= (char*) s;
   return (negative ? -((longlong) li) : (longlong) li);
 end3:
   li=(ulonglong) i*LFACTOR+ (ulonglong) j;
   *endptr= (char*) s;
   return (negative ? -((longlong) li) : (longlong) li);
 end4:
   li=(ulonglong) i*LFACTOR1+ (ulonglong) j * 10 + k;
   *endptr= (char*) s;
   if (negative)
   {
    if (li > MAX_NEGATIVE_NUMBER)
      goto overflow;
    return -((longlong) li);
   }
   return (longlong) li;
 no_conv:
   /* There was no number to convert.  */
   *error= MY_ERRNO_EDOM;
   *endptr= (char *) nptr;
   return 0;
 }
References mpq::c, error(), INIT_CNT, LFACTOR, lfactor, LFACTOR1, LFACTOR2, MAX_NEGATIVE_NUMBER, MY_ERRNO_EDOM, MY_ERRNO_ERANGE, and ULONGLONG_MAX.
Referenced by fetch_string_with_conversion(), internal_str2dec(), and my_strtoll10_8bit().
Variable Documentation
lfactor
unsigned long lfactor[9] static
Initial value:
=
{
  1L, 10L, 100L, 1000L, 10000L, 100000L, 1000000L, 10000000L, 100000000L
}
Definition at line 26 of file my_strtoll10.c.
Referenced by my_strtoll10().