Azerotcore-wotlk: npc_barnes::npc_barnesAI Struct Reference
npc_barnes::npc_barnesAI Struct Reference
Public Member Functions
npc_barnesAI (Creature *creature)
void Reset () override
void StartEvent ()
void EnterCombat (Unit *) override
void WaypointReached (uint32 waypointId) override
void Talk (uint32 count)
void PrepareEncounter ()
void UpdateAI (uint32 diff) override
Public Member Functions inherited from npc_escortAI
npc_escortAI (Creature *creature)
~npc_escortAI () override
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void JustDied (Unit *) override
void JustRespawned () override
void ReturnToLastPoint ()
void EnterEvadeMode () override
virtual void UpdateEscortAI (uint32 diff)
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
virtual void WaypointStart (uint32)
void Start (bool isActiveAttacker=true, bool run=false, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetRun (bool on=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * instance
ObjectGuid m_uiSpotlightGUID
uint32 TalkCount
uint32 TalkTimer
uint32 WipeTimer
uint32 m_uiEventId
bool PerformanceReady
bool RaidWiped
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from npc_escortAI
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 129 of file karazhan.cpp.
Constructor & Destructor Documentation
npc_barnesAI()
npc_barnes::npc_barnesAI::npc_barnesAI (Creature * creature) inline
Definition at line 131 of file karazhan.cpp.
                                          : npc_escortAI(creature)
         {
             RaidWiped = false;
             m_uiEventId = 0;
             instance = creature->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), instance, m_uiEventId, and RaidWiped.
Member Function Documentation
EnterCombat()
void npc_barnes::npc_barnesAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 174 of file karazhan.cpp.
 { }
PrepareEncounter()
void npc_barnes::npc_barnesAI::PrepareEncounter () inline
Definition at line 240 of file karazhan.cpp.
         {
             LOG_DEBUG("scripts.ai", "Barnes Opera Event - Introduction complete - preparing encounter %d", m_uiEventId);
             uint8 index = 0;
             uint8 count = 0;
             switch (m_uiEventId)
             {
                 case EVENT_OZ:
                     index = 0;
                     count = 4;
                     break;
                 case EVENT_HOOD:
                     index = 4;
                     count = index + 1;
                     break;
                 case EVENT_RAJ:
                     index = 5;
                     count = index + 1;
                     break;
             }
             for (; index < count; ++index)
             {
                 uint32 entry = ((uint32)Spawns[index][0]);
                 float PosX = Spawns[index][1];
                 if (Creature* creature = me->SummonCreature(entry, PosX, SPAWN_Y, SPAWN_Z, SPAWN_O, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, HOUR * 2 * IN_MILLISECONDS))
                 {
                     // In case database has bad flags
                     creature->SetUInt32Value(UNIT_FIELD_FLAGS, 0);
                     creature->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                 }
             }
             RaidWiped = false;
         }
References EVENT_HOOD, EVENT_OZ, EVENT_RAJ, HOUR, IN_MILLISECONDS, LOG_DEBUG, m_uiEventId, ScriptedAI::me, RaidWiped, SPAWN_O, SPAWN_Y, SPAWN_Z, WorldObject::SummonCreature(), TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, UNIT_FIELD_FLAGS, and UNIT_FLAG_NON_ATTACKABLE.
Referenced by WaypointReached().
Reset()
void npc_barnes::npc_barnesAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 150 of file karazhan.cpp.
         {
             m_uiSpotlightGUID.Clear();
             TalkCount = 0;
             TalkTimer = 2000;
             WipeTimer = 5000;
             PerformanceReady = false;
             m_uiEventId = instance->GetData(DATA_OPERA_PERFORMANCE);
         }
References ObjectGuid::Clear(), DATA_OPERA_PERFORMANCE, ZoneScript::GetData(), instance, m_uiEventId, m_uiSpotlightGUID, PerformanceReady, TalkCount, TalkTimer, and WipeTimer.
StartEvent()
void npc_barnes::npc_barnesAI::StartEvent () inline
Definition at line 163 of file karazhan.cpp.
         {
             instance->SetBossState(DATA_OPERA_PERFORMANCE, IN_PROGRESS);
             //resets count for this event, in case earlier failed
             if (m_uiEventId == EVENT_OZ)
                 instance->SetData(DATA_OPERA_OZ_DEATHCOUNT, IN_PROGRESS);
             Start(false, false);
         }
References DATA_OPERA_OZ_DEATHCOUNT, DATA_OPERA_PERFORMANCE, EVENT_OZ, IN_PROGRESS, instance, m_uiEventId, InstanceScript::SetBossState(), ZoneScript::SetData(), and npc_escortAI::Start().
Referenced by npc_barnes::OnGossipSelect().
Talk()
void npc_barnes::npc_barnesAI::Talk (uint32 count) inline
Definition at line 208 of file karazhan.cpp.
         {
             int32 text = 0;
             switch (m_uiEventId)
             {
                 case EVENT_OZ:
                     if (OzDialogue[count].textid)
                         text = OzDialogue[count].textid;
                     if (OzDialogue[count].timer)
                         TalkTimer = OzDialogue[count].timer;
                     break;
                 case EVENT_HOOD:
                     if (HoodDialogue[count].textid)
                         text = HoodDialogue[count].textid;
                     if (HoodDialogue[count].timer)
                         TalkTimer = HoodDialogue[count].timer;
                     break;
                 case EVENT_RAJ:
                     if (RAJDialogue[count].textid)
                         text = RAJDialogue[count].textid;
                     if (RAJDialogue[count].timer)
                         TalkTimer = RAJDialogue[count].timer;
                     break;
             }
             if (text)
                 CreatureAI::Talk(text);
         }
References EVENT_HOOD, EVENT_OZ, EVENT_RAJ, HoodDialogue, m_uiEventId, OzDialogue, RAJDialogue, CreatureAI::Talk(), TalkTimer, Dialogue::textid, and Dialogue::timer.
Referenced by UpdateAI().
UpdateAI()
void npc_barnes::npc_barnesAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 278 of file karazhan.cpp.
         {
             npc_escortAI::UpdateAI(diff);
             if (HasEscortState(STATE_ESCORT_PAUSED))
             {
                 if (TalkTimer <= diff)
                 {
                     if (TalkCount > 3)
                     {
                         if (Creature* pSpotlight = ObjectAccessor::GetCreature(*me, m_uiSpotlightGUID))
                             pSpotlight->DespawnOrUnsummon();
                         SetEscortPaused(false);
                         return;
                     }
                     Talk(TalkCount);
                     ++TalkCount;
                 }
                 else TalkTimer -= diff;
             }
             if (PerformanceReady)
             {
                 if (!RaidWiped)
                 {
                     if (WipeTimer <= diff)
                     {
                         Map* map = me->GetMap();
                         if (!map->IsDungeon())
                             return;
                         Map::PlayerList const& PlayerList = map->GetPlayers();
                         if (PlayerList.isEmpty())
                             return;
                         RaidWiped = true;
                         for (Map::PlayerList::const_iterator i = PlayerList.begin(); i != PlayerList.end(); ++i)
{
                             if (i->GetSource()->IsAlive() && !i->GetSource()->IsGameMaster())
{
                                 RaidWiped = false;
                                 break;
                             }
                         }
                         if (RaidWiped)
{
                             RaidWiped = true;
                             EnterEvadeMode();
                             return;
                         }
                         WipeTimer = 15000;
                     }
                     else WipeTimer -= diff;
                 }
             }
         }
References MapRefMgr::begin(), MapRefMgr::end(), npc_escortAI::EnterEvadeMode(), ObjectAccessor::GetCreature(), WorldObject::GetMap(), Map::GetPlayers(), npc_escortAI::HasEscortState(), Map::IsDungeon(), LinkedListHead::isEmpty(), m_uiSpotlightGUID, ScriptedAI::me, PerformanceReady, RaidWiped, npc_escortAI::SetEscortPaused(), STATE_ESCORT_PAUSED, Talk(), TalkCount, TalkTimer, npc_escortAI::UpdateAI(), and WipeTimer.
WaypointReached()
void npc_barnes::npc_barnesAI::WaypointReached (uint32 waypointId) inline override virtual
Implements npc_escortAI.
Definition at line 176 of file karazhan.cpp.
         {
             switch (waypointId)
             {
                 case 0:
                     DoCast(me, SPELL_TUXEDO, false);
                     instance->DoUseDoorOrButton(instance->GetGuidData(DATA_GO_STAGEDOORLEFT));
                     break;
                 case 4:
                     TalkCount = 0;
                     SetEscortPaused(true);
                     if (Creature* spotlight = me->SummonCreature(NPC_SPOTLIGHT,
                                               me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), 0.0f,
                                               TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 60000))
                     {
                         spotlight->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                         spotlight->CastSpell(spotlight, SPELL_SPOTLIGHT, false);
                         m_uiSpotlightGUID = spotlight->GetGUID();
                     }
                     break;
                 case 8:
                     instance->DoUseDoorOrButton(instance->GetGuidData(DATA_GO_STAGEDOORLEFT));
                     PerformanceReady = true;
                     break;
                 case 9:
                     PrepareEncounter();
                     instance->DoUseDoorOrButton(instance->GetGuidData(DATA_GO_CURTAINS));
                     break;
             }
         }
References DATA_GO_CURTAINS, DATA_GO_STAGEDOORLEFT, UnitAI::DoCast(), InstanceScript::DoUseDoorOrButton(), InstanceScript::GetGuidData(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), instance, m_uiSpotlightGUID, ScriptedAI::me, NPC_SPOTLIGHT, PerformanceReady, PrepareEncounter(), npc_escortAI::SetEscortPaused(), SPELL_SPOTLIGHT, SPELL_TUXEDO, WorldObject::SummonCreature(), TalkCount, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, UNIT_FIELD_FLAGS, and UNIT_FLAG_NOT_SELECTABLE.
Member Data Documentation
instance
InstanceScript* npc_barnes::npc_barnesAI::instance
Definition at line 138 of file karazhan.cpp.
Referenced by npc_barnesAI(), Reset(), StartEvent(), and WaypointReached().
m_uiEventId
uint32 npc_barnes::npc_barnesAI::m_uiEventId
Definition at line 145 of file karazhan.cpp.
Referenced by npc_barnesAI(), npc_barnes::OnGossipSelect(), PrepareEncounter(), Reset(), StartEvent(), and Talk().
m_uiSpotlightGUID
ObjectGuid npc_barnes::npc_barnesAI::m_uiSpotlightGUID
Definition at line 140 of file karazhan.cpp.
Referenced by Reset(), UpdateAI(), and WaypointReached().
PerformanceReady
bool npc_barnes::npc_barnesAI::PerformanceReady
Definition at line 147 of file karazhan.cpp.
Referenced by Reset(), UpdateAI(), and WaypointReached().
RaidWiped
bool npc_barnes::npc_barnesAI::RaidWiped
Definition at line 148 of file karazhan.cpp.
Referenced by npc_barnesAI(), PrepareEncounter(), and UpdateAI().
TalkCount
uint32 npc_barnes::npc_barnesAI::TalkCount
Definition at line 142 of file karazhan.cpp.
Referenced by Reset(), UpdateAI(), and WaypointReached().
TalkTimer
uint32 npc_barnes::npc_barnesAI::TalkTimer
Definition at line 143 of file karazhan.cpp.
Referenced by Reset(), Talk(), and UpdateAI().
WipeTimer
uint32 npc_barnes::npc_barnesAI::WipeTimer
Definition at line 144 of file karazhan.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/Karazhan/karazhan.cpp