Azerotcore-wotlk: formatter< std::chrono::duration< Rep, Period >, Char > Struct Template Reference
formatter< std::chrono::duration< Rep, Period >, Char > Struct Template Reference
#include <chrono.h>
Classes
struct parse_range
struct spec_handler
Public Member Functions
FMT_CONSTEXPR auto parse (basic_format_parse_context< Char > &ctx) -> decltype(ctx.begin())
template<typename FormatContext >
auto format (const duration &d, FormatContext &ctx) const -> decltype(ctx.out())
Private Types
using arg_ref_type = detail::arg_ref< Char >
using duration = std::chrono::duration< Rep, Period >
using iterator = typename basic_format_parse_context< Char >::iterator
Private Member Functions
FMT_CONSTEXPR parse_range do_parse (basic_format_parse_context< Char > &ctx)
Private Attributes
basic_format_specs< Char > specs
int precision = -1
arg_ref_type width_ref
arg_ref_type precision_ref
bool localized = false
basic_string_view< Char > format_str
Detailed Description
template<typename Rep, typename Period, typename Char>
struct formatter< std::chrono::duration< Rep, Period >, Char >
Definition at line 1189 of file chrono.h.
Member Typedef Documentation
arg_ref_type
template<typename Rep , typename Period , typename Char > using formatter< std::chrono::duration< Rep, Period >, Char >::arg_ref_type = detail::arg_ref<Char> private
Definition at line 1193 of file chrono.h.
duration
template<typename Rep , typename Period , typename Char > using formatter< std::chrono::duration< Rep, Period >, Char >::duration = std::chrono::duration<Rep, Period> private
Definition at line 1198 of file chrono.h.
iterator
template<typename Rep , typename Period , typename Char > using formatter< std::chrono::duration< Rep, Period >, Char >::iterator = typename basic_format_parse_context<Char>::iterator private
Definition at line 1239 of file chrono.h.
Member Function Documentation
do_parse()
template<typename Rep , typename Period , typename Char > FMT_CONSTEXPR parse_range formatter< std::chrono::duration< Rep, Period >, Char >::do_parse (basic_format_parse_context< Char > & ctx) inline private
Definition at line 1245 of file chrono.h.
{
     auto begin = ctx.begin(), end = ctx.end();
     if (begin == end || *begin == '}') return {begin, begin};
     spec_handler handler{*this, ctx, format_str};
     begin = detail::parse_align(begin, end, handler);
     if (begin == end) return {begin, begin};
     begin = detail::parse_width(begin, end, handler);
     if (begin == end) return {begin, begin};
     if (*begin == '.') {
       if (std::is_floating_point<Rep>::value)
         begin = detail::parse_precision(begin, end, handler);
       else
         handler.on_error("precision not allowed for this argument type");
     }
     if (begin != end && *begin == 'L') {
       ++begin;
       localized = true;
     }
     end = parse_chrono_format(begin, end, detail::chrono_format_checker());
     return {begin, end};
   }
References basic_format_parse_context< Char, ErrorHandler >::begin(), basic_format_parse_context< Char, ErrorHandler >::end(), parse_align(), parse_chrono_format(), parse_precision(), and parse_width().
format()
template<typename Rep , typename Period , typename Char > template<typename FormatContext > auto formatter< std::chrono::duration< Rep, Period >, Char >::format (const duration & d, FormatContext & ctx) const -> decltype(ctx.out()) inline
Definition at line 1277 of file chrono.h.
{
     auto specs_copy = specs;
     auto precision_copy = precision;
     auto begin = format_str.begin(), end = format_str.end();
     // As a possible future optimization, we could avoid extra copying if width
     // is not specified.
     basic_memory_buffer<Char> buf;
     auto out = std::back_inserter(buf);
     detail::handle_dynamic_spec<detail::width_checker>(specs_copy.width,
                                                        width_ref, ctx);
     detail::handle_dynamic_spec<detail::precision_checker>(precision_copy,
                                                            precision_ref, ctx);
     if (begin == end || *begin == '}') {
       out = detail::format_duration_value<Char>(out, d.count(), precision_copy);
       detail::format_duration_unit<Char, Period>(out);
     } else {
       detail::chrono_formatter<FormatContext, decltype(out), Rep, Period> f(
           ctx, out, d);
       f.precision = precision_copy;
       f.localized = localized;
       detail::parse_chrono_format(begin, end, f);
     }
     return detail::write(
         ctx.out(), basic_string_view<Char>(buf.data(), buf.size()), specs_copy);
   }
References basic_string_view< Char >::begin(), mpq::d, basic_string_view< Char >::end(), f(), parse_chrono_format(), and detail::write().
parse()
template<typename Rep , typename Period , typename Char > FMT_CONSTEXPR auto formatter< std::chrono::duration< Rep, Period >, Char >::parse (basic_format_parse_context< Char > & ctx) -> decltype(ctx.begin()) inline
Definition at line 1268 of file chrono.h.
{
     auto range = do_parse(ctx);
     format_str = basic_string_view<Char>(
         &*range.begin, detail::to_unsigned(range.end - range.begin));
     return range.end;
   }
References to_unsigned().
Member Data Documentation
format_str
template<typename Rep , typename Period , typename Char > basic_string_view<Char> formatter< std::chrono::duration< Rep, Period >, Char >::format_str private
Definition at line 1197 of file chrono.h.
localized
template<typename Rep , typename Period , typename Char > bool formatter< std::chrono::duration< Rep, Period >, Char >::localized = false private
Definition at line 1196 of file chrono.h.
precision
template<typename Rep , typename Period , typename Char > int formatter< std::chrono::duration< Rep, Period >, Char >::precision = -1 private
Definition at line 1192 of file chrono.h.
precision_ref
template<typename Rep , typename Period , typename Char > arg_ref_type formatter< std::chrono::duration< Rep, Period >, Char >::precision_ref private
Definition at line 1195 of file chrono.h.
specs
template<typename Rep , typename Period , typename Char > basic_format_specs<Char> formatter< std::chrono::duration< Rep, Period >, Char >::specs private
Definition at line 1191 of file chrono.h.
width_ref
template<typename Rep , typename Period , typename Char > arg_ref_type formatter< std::chrono::duration< Rep, Period >, Char >::width_ref private
Definition at line 1194 of file chrono.h.
The documentation for this struct was generated from the following file:
deps/fmt/include/fmt/chrono.h