Azerotcore-wotlk: boss_nightbane::boss_nightbaneAI Struct Reference
boss_nightbane::boss_nightbaneAI Struct Reference
Public Member Functions
boss_nightbaneAI (Creature *creature)
void Reset () override
void HandleTerraceDoors (bool open)
void EnterCombat (Unit *) override
void AttackStart (Unit *who) override
void JustDied (Unit *) override
void MoveInLineOfSight (Unit *who) override
void MovementInform (uint32 type, uint32 id) override
void JustSummoned (Creature *summoned) override
void TakeOff ()
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * instance
uint32 Phase
bool RainBones
bool Skeletons
uint32 BellowingRoarTimer
uint32 CharredEarthTimer
uint32 DistractingAshTimer
uint32 SmolderingBreathTimer
uint32 TailSweepTimer
uint32 RainofBonesTimer
uint32 SmokingBlastTimer
uint32 FireballBarrageTimer
uint32 SearingCindersTimer
uint32 FlyCount
uint32 FlyTimer
bool Intro
bool Flying
bool Movement
uint32 MovePhase
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 77 of file boss_nightbane.cpp.
Constructor & Destructor Documentation
boss_nightbaneAI()
boss_nightbane::boss_nightbaneAI::boss_nightbaneAI (Creature * creature) inline
Definition at line 79 of file boss_nightbane.cpp.
                                              : ScriptedAI(creature)
         {
             instance = creature->GetInstanceScript();
             Intro = true;
         }
References WorldObject::GetInstanceScript(), instance, and Intro.
Member Function Documentation
AttackStart()
void boss_nightbane::boss_nightbaneAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 170 of file boss_nightbane.cpp.
         {
             if (!Intro && !Flying)
                 ScriptedAI::AttackStart(who);
         }
References ScriptedAI::AttackStart(), Flying, and Intro.
EnterCombat()
void boss_nightbane::boss_nightbaneAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 161 of file boss_nightbane.cpp.
         {
             if (instance)
                 instance->SetData(DATA_NIGHTBANE, IN_PROGRESS);
             HandleTerraceDoors(false);
             Talk(YELL_AGGRO);
         }
References DATA_NIGHTBANE, HandleTerraceDoors(), IN_PROGRESS, instance, ZoneScript::SetData(), CreatureAI::Talk(), and YELL_AGGRO.
HandleTerraceDoors()
void boss_nightbane::boss_nightbaneAI::HandleTerraceDoors (bool open) inline
Definition at line 152 of file boss_nightbane.cpp.
         {
             if (instance)
             {
                 instance->HandleGameObject(instance->GetGuidData(DATA_MASTERS_TERRACE_DOOR_1), open);
                 instance->HandleGameObject(instance->GetGuidData(DATA_MASTERS_TERRACE_DOOR_2), open);
             }
         }
References DATA_MASTERS_TERRACE_DOOR_1, DATA_MASTERS_TERRACE_DOOR_2, InstanceScript::GetGuidData(), InstanceScript::HandleGameObject(), instance, and open.
Referenced by EnterCombat(), JustDied(), and Reset().
JustDied()
void boss_nightbane::boss_nightbaneAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 176 of file boss_nightbane.cpp.
         {
             if (instance)
                 instance->SetData(DATA_NIGHTBANE, DONE);
             HandleTerraceDoors(true);
         }
References DATA_NIGHTBANE, DONE, HandleTerraceDoors(), instance, and ZoneScript::SetData().
JustSummoned()
void boss_nightbane::boss_nightbaneAI::JustSummoned (Creature * summoned) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 230 of file boss_nightbane.cpp.
         {
             summoned->AI()->AttackStart(me->GetVictim());
         }
References Creature::AI(), UnitAI::AttackStart(), Unit::GetVictim(), and ScriptedAI::me.
MoveInLineOfSight()
void boss_nightbane::boss_nightbaneAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
Definition at line 184 of file boss_nightbane.cpp.
         {
             if (!Intro && !Flying)
                 ScriptedAI::MoveInLineOfSight(who);
         }
References Flying, Intro, and CreatureAI::MoveInLineOfSight().
MovementInform()
void boss_nightbane::boss_nightbaneAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 190 of file boss_nightbane.cpp.
         {
             if (type != POINT_MOTION_TYPE)
                 return;
             if (Intro)
             {
                 if (id >= 8)
                 {
                     Intro = false;
                     me->SetHomePosition(IntroWay[7][0], IntroWay[7][1], IntroWay[7][2], 0);
                     return;
                 }
                 MovePhase = id + 1;
                 return;
             }
             if (Flying)
             {
                 if (id == 0)
                 {
                     Talk(EMOTE_BREATH);
                     Flying = false;
                     Phase = 2;
                     return;
                 }
                 if (id < 8)
                     MovePhase = id + 1;
                 else
                 {
                     Phase = 1;
                     Flying = false;
                     Movement = true;
                     return;
                 }
             }
         }
References EMOTE_BREATH, Flying, Intro, IntroWay, ScriptedAI::me, MovePhase, POINT_MOTION_TYPE, Creature::SetHomePosition(), and CreatureAI::Talk().
Reset()
void boss_nightbane::boss_nightbaneAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 111 of file boss_nightbane.cpp.
         {
             BellowingRoarTimer = 30000;
             CharredEarthTimer = 15000;
             DistractingAshTimer = 20000;
             SmolderingBreathTimer = 10000;
             TailSweepTimer = 12000;
             RainofBonesTimer = 10000;
             SmokingBlastTimer = 20000;
             FireballBarrageTimer = 13000;
             SearingCindersTimer = 14000;
             Phase = 1;
             FlyCount = 0;
             MovePhase = 0;
             me->SetSpeed(MOVE_RUN, 2.0f);
             me->SetDisableGravity(Intro);
             me->SetWalk(false);
             me->setActive(true);
             if (instance)
             {
                 if (instance->GetData(DATA_NIGHTBANE) == DONE)
                     me->DisappearAndDie();
                 else
                     instance->SetData(DATA_NIGHTBANE, NOT_STARTED);
             }
             HandleTerraceDoors(true);
             Flying = false;
             Movement = false;
             if (!Intro)
             {
                 me->SetHomePosition(IntroWay[7][0], IntroWay[7][1], IntroWay[7][2], 0);
                 me->GetMotionMaster()->MoveTargetedHome();
             }
         }
References BellowingRoarTimer, CharredEarthTimer, DATA_NIGHTBANE, Creature::DisappearAndDie(), DistractingAshTimer, DONE, FireballBarrageTimer, FlyCount, Flying, ZoneScript::GetData(), Unit::GetMotionMaster(), HandleTerraceDoors(), instance, Intro, IntroWay, ScriptedAI::me, MOVE_RUN, MovePhase, MotionMaster::MoveTargetedHome(), NOT_STARTED, RainofBonesTimer, SearingCindersTimer, WorldObject::setActive(), ZoneScript::SetData(), Creature::SetDisableGravity(), Creature::SetHomePosition(), Unit::SetSpeed(), Creature::SetWalk(), SmokingBlastTimer, SmolderingBreathTimer, and TailSweepTimer.
TakeOff()
void boss_nightbane::boss_nightbaneAI::TakeOff () inline
Definition at line 235 of file boss_nightbane.cpp.
         {
             Talk(YELL_FLY_PHASE);
             me->InterruptSpell(CURRENT_GENERIC_SPELL);
             me->HandleEmoteCommand(EMOTE_ONESHOT_LIFTOFF);
             me->SetDisableGravity(true);
             me->GetMotionMaster()->Clear(false);
             me->GetMotionMaster()->MovePoint(0, IntroWay[2][0], IntroWay[2][1], IntroWay[2][2]);
             Flying = true;
             FlyTimer = urand(45000, 60000); //timer wrong between 45 and 60 seconds
             ++FlyCount;
             RainofBonesTimer = 5000; //timer wrong (maybe)
             RainBones = false;
             Skeletons = false;
         }
References MotionMaster::Clear(), CURRENT_GENERIC_SPELL, EMOTE_ONESHOT_LIFTOFF, FlyCount, Flying, FlyTimer, Unit::GetMotionMaster(), Unit::HandleEmoteCommand(), Unit::InterruptSpell(), IntroWay, ScriptedAI::me, MotionMaster::MovePoint(), RainBones, RainofBonesTimer, Creature::SetDisableGravity(), Skeletons, CreatureAI::Talk(), urand(), and YELL_FLY_PHASE.
Referenced by UpdateAI().
UpdateAI()
void boss_nightbane::boss_nightbaneAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 255 of file boss_nightbane.cpp.
         {
             if (Intro)
             {
                 if (MovePhase)
                 {
                     if (MovePhase >= 7)
                     {
                         me->SetDisableGravity(false);
                         me->HandleEmoteCommand(EMOTE_ONESHOT_LAND);
                         me->GetMotionMaster()->MovePoint(8, IntroWay[7][0], IntroWay[7][1], IntroWay[7][2]);
                     }
                     else
                     {
                         me->GetMotionMaster()->MovePoint(MovePhase, IntroWay[MovePhase][0], IntroWay[MovePhase][1], IntroWay[MovePhase][2]);
                     }
                     MovePhase = 0;
                 }
                 return;
             }
             if (Flying && MovePhase)
             {
                 if (MovePhase >= 7)
                 {
                     me->SetDisableGravity(false);
                     me->HandleEmoteCommand(EMOTE_ONESHOT_LAND);
                     me->GetMotionMaster()->MovePoint(8, IntroWay[7][0], IntroWay[7][1], IntroWay[7][2]);
                 }
                 else
                     me->GetMotionMaster()->MovePoint(MovePhase, IntroWay[MovePhase][0], IntroWay[MovePhase][1], IntroWay[MovePhase][2]);
                 MovePhase = 0;
             }
             if (!UpdateVictim())
                 return;
             if (Flying)
                 return;
             //  Phase 1 "GROUND FIGHT"
             if (Phase == 1)
             {
                 if (Movement)
                 {
                     DoStartMovement(me->GetVictim());
                     Movement = false;
                 }
                 if (BellowingRoarTimer <= diff)
                 {
                     DoCastVictim(SPELL_BELLOWING_ROAR);
                     BellowingRoarTimer = urand(30000, 40000);
                 }
                 else
                     BellowingRoarTimer -= diff;
                 if (SmolderingBreathTimer <= diff)
                 {
                     DoCastVictim(SPELL_SMOLDERING_BREATH);
                     SmolderingBreathTimer = 20000;
                 }
                 else
                     SmolderingBreathTimer -= diff;
                 if (CharredEarthTimer <= diff)
                 {
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 100, true))
                         DoCast(target, SPELL_CHARRED_EARTH);
                     CharredEarthTimer = 20000;
                 }
                 else
                     CharredEarthTimer -= diff;
                 if (TailSweepTimer <= diff)
                 {
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 100, true))
                         if (!me->HasInArc(M_PI, target))
                             DoCast(target, SPELL_TAIL_SWEEP);
                     TailSweepTimer = 15000;
                 }
                 else
                     TailSweepTimer -= diff;
                 if (SearingCindersTimer <= diff)
                 {
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 100, true))
                         DoCast(target, SPELL_SEARING_CINDERS);
                     SearingCindersTimer = 10000;
                 }
                 else
                     SearingCindersTimer -= diff;
                 uint32 Prozent = uint32(me->GetHealthPct());
                 if (Prozent < 75 && FlyCount == 0) // first take off 75%
                     TakeOff();
                 if (Prozent < 50 && FlyCount == 1) // secound take off 50%
                     TakeOff();
                 if (Prozent < 25 && FlyCount == 2) // third take off 25%
                     TakeOff();
                 DoMeleeAttackIfReady();
             }
             //Phase 2 "FLYING FIGHT"
             if (Phase == 2)
             {
                 if (!RainBones)
                 {
                     if (!Skeletons)
                     {
                         for (uint8 i = 0; i <= 3; ++i)
{
                             DoCastVictim(SPELL_SUMMON_SKELETON);
                             Skeletons = true;
                         }
                     }
                     if (RainofBonesTimer < diff && !RainBones) // only once at the beginning of phase 2
                     {
                         DoCastVictim(SPELL_RAIN_OF_BONES);
                         RainBones = true;
                         SmokingBlastTimer = 20000;
                     }
                     else
                         RainofBonesTimer -= diff;
                     if (DistractingAshTimer <= diff)
                     {
                         if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 100, true))
                             DoCast(target, SPELL_DISTRACTING_ASH);
                         DistractingAshTimer = 2000; //timer wrong
                     }
                     else
                         DistractingAshTimer -= diff;
                 }
                 if (RainBones)
                 {
                     if (SmokingBlastTimer <= diff)
                     {
                         DoCastVictim(SPELL_SMOKING_BLAST);
                         SmokingBlastTimer = 1500; //timer wrong
                     }
                     else
                         SmokingBlastTimer -= diff;
                 }
                 if (FireballBarrageTimer <= diff)
                 {
                     if (Unit* target = SelectTarget(SELECT_TARGET_FARTHEST, 0))
                         DoCast(target, SPELL_FIREBALL_BARRAGE);
                     FireballBarrageTimer = 20000;
                 }
                 else
                     FireballBarrageTimer -= diff;
                 if (FlyTimer <= diff) //landing
                 {
                     Talk(YELL_LAND_PHASE);
                     me->GetMotionMaster()->Clear(false);
                     me->GetMotionMaster()->MovePoint(3, IntroWay[3][0], IntroWay[3][1], IntroWay[3][2]);
                     Flying = true;
                 }
                 else
                     FlyTimer -= diff;
             }
         }
References BellowingRoarTimer, CharredEarthTimer, MotionMaster::Clear(), diff(), DistractingAshTimer, UnitAI::DoCast(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DoStartMovement(), EMOTE_ONESHOT_LAND, FireballBarrageTimer, FlyCount, Flying, FlyTimer, Unit::GetHealthPct(), Unit::GetMotionMaster(), Unit::GetVictim(), Unit::HandleEmoteCommand(), Position::HasInArc(), Intro, IntroWay, M_PI, ScriptedAI::me, MovePhase, MotionMaster::MovePoint(), RainBones, RainofBonesTimer, SearingCindersTimer, SELECT_TARGET_FARTHEST, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Creature::SetDisableGravity(), Skeletons, SmokingBlastTimer, SmolderingBreathTimer, SPELL_BELLOWING_ROAR, SPELL_CHARRED_EARTH, SPELL_DISTRACTING_ASH, SPELL_FIREBALL_BARRAGE, SPELL_RAIN_OF_BONES, SPELL_SEARING_CINDERS, SPELL_SMOKING_BLAST, SPELL_SMOLDERING_BREATH, SPELL_SUMMON_SKELETON, SPELL_TAIL_SWEEP, TailSweepTimer, TakeOff(), CreatureAI::Talk(), CreatureAI::UpdateVictim(), urand(), and YELL_LAND_PHASE.
Member Data Documentation
BellowingRoarTimer
uint32 boss_nightbane::boss_nightbaneAI::BellowingRoarTimer
Definition at line 92 of file boss_nightbane.cpp.
Referenced by Reset(), and UpdateAI().
CharredEarthTimer
uint32 boss_nightbane::boss_nightbaneAI::CharredEarthTimer
Definition at line 93 of file boss_nightbane.cpp.
Referenced by Reset(), and UpdateAI().
DistractingAshTimer
uint32 boss_nightbane::boss_nightbaneAI::DistractingAshTimer
Definition at line 94 of file boss_nightbane.cpp.
Referenced by Reset(), and UpdateAI().
FireballBarrageTimer
uint32 boss_nightbane::boss_nightbaneAI::FireballBarrageTimer
Definition at line 99 of file boss_nightbane.cpp.
Referenced by Reset(), and UpdateAI().
FlyCount
uint32 boss_nightbane::boss_nightbaneAI::FlyCount
Definition at line 102 of file boss_nightbane.cpp.
Referenced by Reset(), TakeOff(), and UpdateAI().
Flying
bool boss_nightbane::boss_nightbaneAI::Flying
Definition at line 106 of file boss_nightbane.cpp.
Referenced by AttackStart(), MoveInLineOfSight(), MovementInform(), Reset(), TakeOff(), and UpdateAI().
FlyTimer
uint32 boss_nightbane::boss_nightbaneAI::FlyTimer
Definition at line 103 of file boss_nightbane.cpp.
Referenced by TakeOff(), and UpdateAI().
instance
InstanceScript* boss_nightbane::boss_nightbaneAI::instance
Definition at line 85 of file boss_nightbane.cpp.
Referenced by boss_nightbaneAI(), EnterCombat(), HandleTerraceDoors(), JustDied(), and Reset().
Intro
bool boss_nightbane::boss_nightbaneAI::Intro
Definition at line 105 of file boss_nightbane.cpp.
Referenced by AttackStart(), boss_nightbaneAI(), MoveInLineOfSight(), MovementInform(), Reset(), and UpdateAI().
Movement
bool boss_nightbane::boss_nightbaneAI::Movement
Definition at line 107 of file boss_nightbane.cpp.
MovePhase
uint32 boss_nightbane::boss_nightbaneAI::MovePhase
Definition at line 109 of file boss_nightbane.cpp.
Referenced by MovementInform(), Reset(), and UpdateAI().
Phase
uint32 boss_nightbane::boss_nightbaneAI::Phase
Definition at line 87 of file boss_nightbane.cpp.
RainBones
bool boss_nightbane::boss_nightbaneAI::RainBones
Definition at line 89 of file boss_nightbane.cpp.
Referenced by TakeOff(), and UpdateAI().
RainofBonesTimer
uint32 boss_nightbane::boss_nightbaneAI::RainofBonesTimer
Definition at line 97 of file boss_nightbane.cpp.
Referenced by Reset(), TakeOff(), and UpdateAI().
SearingCindersTimer
uint32 boss_nightbane::boss_nightbaneAI::SearingCindersTimer
Definition at line 100 of file boss_nightbane.cpp.
Referenced by Reset(), and UpdateAI().
Skeletons
bool boss_nightbane::boss_nightbaneAI::Skeletons
Definition at line 90 of file boss_nightbane.cpp.
Referenced by TakeOff(), and UpdateAI().
SmokingBlastTimer
uint32 boss_nightbane::boss_nightbaneAI::SmokingBlastTimer
Definition at line 98 of file boss_nightbane.cpp.
Referenced by Reset(), and UpdateAI().
SmolderingBreathTimer
uint32 boss_nightbane::boss_nightbaneAI::SmolderingBreathTimer
Definition at line 95 of file boss_nightbane.cpp.
Referenced by Reset(), and UpdateAI().
TailSweepTimer
uint32 boss_nightbane::boss_nightbaneAI::TailSweepTimer
Definition at line 96 of file boss_nightbane.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/Karazhan/boss_nightbane.cpp