Azerotcore-wotlk: boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI Struct Reference
boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI Struct Reference
Public Member Functions
boss_jedoga_shadowseekerAI (Creature *pCreature)
void MoveInLineOfSight (Unit *) override
void Reset () override
void JustSummoned (Creature *summon) override
void SummonedCreatureDies (Creature *summon, Unit *killer) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void DoAction (int32 action) override
void EnterCombat (Unit *) override
void KilledUnit (Unit *who) override
void JustDied (Unit *) override
void MovementInform (uint32 type, uint32 pointId) override
void UpdateAI (uint32 diff) override
uint32 GetData (uint32 type) const override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Member Functions
void ReschedulleCombatEvents ()
void DespawnOOCSummons ()
Private Attributes
GuidList oocSummons
GuidList oocTriggers
ObjectGuid sacraficeTarget_GUID
uint32 sayPreachTimer
bool combatSummonsSummoned
bool ritualTriggered
bool volunteerWork
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 158 of file boss_jedoga_shadowseeker.cpp.
Constructor & Destructor Documentation
boss_jedoga_shadowseekerAI()
boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::boss_jedoga_shadowseekerAI (Creature * pCreature) inline
Definition at line 160 of file boss_jedoga_shadowseeker.cpp.
                                                         : BossAI(pCreature, DATA_JEDOGA_SHADOWSEEKER),
             sayPreachTimer(120000),
             combatSummonsSummoned(false),
             ritualTriggered(false),
             volunteerWork(true)
         {
         }
Member Function Documentation
DamageTaken()
void boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 295 of file boss_jedoga_shadowseeker.cpp.
         {
             if (!ritualTriggered && me->HealthBelowPctDamaged(55, damage) && events.IsInPhase(PHASE_NORMAL))
             {
                 SetCombatMovement(false);
                 me->InterruptNonMeleeSpells(false);
                 me->AttackStop();
                 me->SetReactState(REACT_PASSIVE);
                 me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
                 events.SetPhase(PHASE_RITUAL);
                 events.ScheduleEvent(EVENT_JEDOGA_PREPARE_RITUAL, 1000, 0, PHASE_RITUAL);
                 ritualTriggered = true;
                 return;
             }
             if (events.IsInPhase(PHASE_RITUAL))
             {
                 damage = 0;
             }
         }
References Unit::AttackStop(), EVENT_JEDOGA_PREPARE_RITUAL, Unit::HealthBelowPctDamaged(), Unit::InterruptNonMeleeSpells(), ScriptedAI::me, PHASE_NORMAL, PHASE_RITUAL, REACT_PASSIVE, ritualTriggered, ScriptedAI::SetCombatMovement(), Object::SetFlag(), Creature::SetReactState(), UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
DespawnOOCSummons()
void boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::DespawnOOCSummons () inline private
Definition at line 545 of file boss_jedoga_shadowseeker.cpp.
         {
             if (!oocTriggers.empty())
             {
                 for (ObjectGuid const& guid : oocTriggers)
                 {
                     if (Creature* summon = ObjectAccessor::GetCreature(*me, guid))
                     {
                         summon->DespawnOrUnsummon();
                     }
                 }
                 oocTriggers.clear();
             }
             if (!oocSummons.empty())
             {
                 for (ObjectGuid const& guid : oocSummons)
                 {
                     if (Creature* summon = ObjectAccessor::GetCreature(*me, guid))
                     {
                         summon->DespawnOrUnsummon();
                     }
                 }
                 oocSummons.clear();
             }
         }
References ObjectAccessor::GetCreature(), ScriptedAI::me, oocSummons, and oocTriggers.
Referenced by JustDied(), Reset(), and SummonedCreatureDies().
DoAction()
void boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 317 of file boss_jedoga_shadowseeker.cpp.
         {
             if (action == ACTION_SACRAFICE)
             {
                 if (Creature* target = ObjectAccessor::GetCreature(*me, sacraficeTarget_GUID))
                 {
                     Unit::Kill(me, target);
                 }
             }
         }
References ACTION_SACRAFICE, ObjectAccessor::GetCreature(), Unit::Kill(), ScriptedAI::me, and sacraficeTarget_GUID.
EnterCombat()
void boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::EnterCombat (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 328 of file boss_jedoga_shadowseeker.cpp.
         {
             _EnterCombat();
             Talk(SAY_AGGRO);
             ReschedulleCombatEvents();
         }
References BossAI::_EnterCombat(), ReschedulleCombatEvents(), SAY_AGGRO, and CreatureAI::Talk().
GetData()
uint32 boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::GetData (uint32 type) const inline override virtual
Reimplemented from UnitAI.
Definition at line 518 of file boss_jedoga_shadowseeker.cpp.
         {
             if (type == DATA_VOLUNTEER_WORK)
             {
                 return volunteerWork ? 1 : 0;
             }
             return 0;
         }
References DATA_VOLUNTEER_WORK, and volunteerWork.
JustDied()
void boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 345 of file boss_jedoga_shadowseeker.cpp.
         {
             _JustDied();
             DespawnOOCSummons();
             Talk(SAY_DEATH);
         }
References BossAI::_JustDied(), DespawnOOCSummons(), SAY_DEATH, and CreatureAI::Talk().
JustSummoned()
void boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
Definition at line 223 of file boss_jedoga_shadowseeker.cpp.
         {
             if (summon->GetEntry() == NPC_JEDOGA_CONTROLLER)
             {
                 summons.Summon(summon);
             }
         }
References Object::GetEntry(), NPC_JEDOGA_CONTROLLER, SummonList::Summon(), and BossAI::summons.
KilledUnit()
void boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 335 of file boss_jedoga_shadowseeker.cpp.
         {
             if (who->GetTypeId() != TYPEID_PLAYER)
             {
                 return;
             }
             Talk(SAY_SLAY);
         }
References Object::GetTypeId(), SAY_SLAY, CreatureAI::Talk(), and TYPEID_PLAYER.
MoveInLineOfSight()
void boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 169 of file boss_jedoga_shadowseeker.cpp.
 {}
MovementInform()
void boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::MovementInform (uint32 type, uint32 pointId) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 352 of file boss_jedoga_shadowseeker.cpp.
         {
             if (!(type == POINT_MOTION_TYPE || type == EFFECT_MOTION_TYPE))
             {
                 return;
             }
             switch (pointId)
             {
                 case POINT_DOWN:
                 {
                     me->ClearUnitState(UNIT_STATE_NO_ENVIRONMENT_UPD);
                     ReschedulleCombatEvents();
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
                     me->SetReactState(REACT_AGGRESSIVE);
                     me->RemoveAurasDueToSpell(SPELL_SPHERE_VISUAL);
                     me->RemoveAurasDueToSpell(SPELL_LIGHTNING_BOLTS);
                     me->RemoveAurasDueToSpell(SPELL_HOVER_FALL);
                     SetCombatMovement(true);
                     me->SetDisableGravity(false);
                     me->SetHover(false);
                     me->SetInCombatWithZone();
                     if (Unit* victim = me->GetVictim())
                     {
                         me->StopMoving();
                         AttackStart(victim);
                     }
                     break;
                 }
                 case POINT_UP:
                 {
                     me->SetFacingTo(5.66f);
                     if (!summons.empty())
                     {
                         sacraficeTarget_GUID = Acore::Containers::SelectRandomContainerElement(summons);
                         if (Creature* volunteer = ObjectAccessor::GetCreature(*me, sacraficeTarget_GUID))
{
                             Talk(SAY_SACRIFICE_1);
                             sacraficeTarget_GUID = volunteer->GetGUID();
                             volunteer->AI()->DoAction(ACTION_RITUAL_BEGIN);
                         }
                         // Something failed, let players continue but do not grant achievement
                         else
{
                             volunteerWork = false;
                             me->GetMotionMaster()->Clear();
                             DoCastSelf(SPELL_HOVER_FALL);
                             me->GetMotionMaster()->MovePoint(POINT_DOWN, JedogaPosition[1], false);
                         }
                     }
                     break;
                 }
                 case POINT_RITUAL:
                 {
                     me->SetFacingTo(5.66f);
                     DoCastSelf(SPELL_HOVER_FALL);
                     events.ScheduleEvent(EVENT_JEDOGA_MOVE_UP, 1000, 0, PHASE_RITUAL);
                     break;
                 }
                 case POINT_INITIAL:
                 {
                     me->SetFacingTo(5.66f);
                     DoCastSelf(SPELL_SPHERE_VISUAL, true);
                     DoCastSelf(SPELL_LIGHTNING_BOLTS, true);
                     if (!oocTriggers.empty())
                     {
                         for (ObjectGuid const& guid : oocTriggers)
{
                             if (Creature* trigger = ObjectAccessor::GetCreature(*me, guid))
{
                                 trigger->CastSpell(nullptr, SPELL_BEAM_VISUAL_JEDOGA);
                             }
                         }
                     }
                     break;
                 }
             }
         }
References ACTION_RITUAL_BEGIN, ScriptedAI::AttackStart(), MotionMaster::Clear(), Unit::ClearUnitState(), UnitAI::DoCastSelf(), EFFECT_MOTION_TYPE, SummonList::empty(), EVENT_JEDOGA_MOVE_UP, ObjectAccessor::GetCreature(), Unit::GetMotionMaster(), Unit::GetVictim(), JedogaPosition, ScriptedAI::me, MotionMaster::MovePoint(), oocTriggers, PHASE_RITUAL, POINT_DOWN, POINT_INITIAL, POINT_MOTION_TYPE, POINT_RITUAL, POINT_UP, REACT_AGGRESSIVE, Unit::RemoveAurasDueToSpell(), Object::RemoveFlag(), ReschedulleCombatEvents(), sacraficeTarget_GUID, SAY_SACRIFICE_1, Acore::Containers::SelectRandomContainerElement(), ScriptedAI::SetCombatMovement(), Creature::SetDisableGravity(), Unit::SetFacingTo(), Creature::SetHover(), Creature::SetInCombatWithZone(), Creature::SetReactState(), SPELL_BEAM_VISUAL_JEDOGA, SPELL_HOVER_FALL, SPELL_LIGHTNING_BOLTS, SPELL_SPHERE_VISUAL, Unit::StopMoving(), BossAI::summons, CreatureAI::Talk(), UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, UNIT_STATE_NO_ENVIRONMENT_UPD, and volunteerWork.
ReschedulleCombatEvents()
void boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::ReschedulleCombatEvents () inline private
Definition at line 537 of file boss_jedoga_shadowseeker.cpp.
         {
             events.SetPhase(PHASE_NORMAL);
             events.RescheduleEvent(EVENT_JEDOGA_CYCLONE, 3000, 0, PHASE_NORMAL);
             events.RescheduleEvent(EVENT_JEDOGA_LIGHTNING_BOLT, 7000, 0, PHASE_NORMAL);
             events.RescheduleEvent(EVENT_JEDOGA_THUNDERSHOCK, 12000, 0, PHASE_NORMAL);
         }
References EVENT_JEDOGA_CYCLONE, EVENT_JEDOGA_LIGHTNING_BOLT, EVENT_JEDOGA_THUNDERSHOCK, and PHASE_NORMAL.
Referenced by EnterCombat(), and MovementInform().
Reset()
void boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 171 of file boss_jedoga_shadowseeker.cpp.
         {
             me->SetReactState(REACT_PASSIVE);
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_IMMUNE_TO_NPC | UNIT_FLAG_IMMUNE_TO_PC);
             me->AddUnitState(UNIT_STATE_NO_ENVIRONMENT_UPD);
             me->SetDisableGravity(true);
             me->SetHover(true);
             me->GetMotionMaster()->MovePoint(POINT_INITIAL, JedogaPosition[0], false);
             _Reset();
             events.SetPhase(PHASE_NORMAL);
             DespawnOOCSummons();
             std::list<TempSummon*> tempOOCSummons;
             me->SummonCreatureGroup(SUMMON_GROUP_OOC, &tempOOCSummons);
             if (!tempOOCSummons.empty())
             {
                 for (TempSummon* summon : tempOOCSummons)
                 {
                     if (summon)
                     {
                         summon->ApplySpellImmune(0, IMMUNITY_DAMAGE, SPELL_SCHOOL_MASK_NORMAL, false);
                         summon->ApplySpellImmune(0, IMMUNITY_DAMAGE, SPELL_SCHOOL_MASK_MAGIC, false);
                         summon->RemoveAurasDueToSpell(SPELL_WHITE_SPHERE);
                         summon->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
                         summon->SetStandState(UNIT_STAND_STATE_KNEEL);
                         oocSummons.push_back(summon->GetGUID());
                     }
                 }
             }
             tempOOCSummons.clear();
             me->SummonCreatureGroup(SUMMON_GROUP_OOC_TRIGGERS, &tempOOCSummons);
             if (!tempOOCSummons.empty())
             {
                 for (TempSummon* trigger : tempOOCSummons)
                 {
                     if (trigger)
                     {
                         oocTriggers.push_back(trigger->GetGUID());
                     }
                 }
             }
             sacraficeTarget_GUID.Clear();
             sayPreachTimer = 120000;
             ritualTriggered = false;
             volunteerWork = true;
             combatSummonsSummoned = false;
         }
References BossAI::_Reset(), Unit::AddUnitState(), ObjectGuid::Clear(), combatSummonsSummoned, DespawnOOCSummons(), Unit::GetMotionMaster(), IMMUNITY_DAMAGE, JedogaPosition, ScriptedAI::me, MotionMaster::MovePoint(), oocSummons, oocTriggers, PHASE_NORMAL, POINT_INITIAL, REACT_PASSIVE, ritualTriggered, sacraficeTarget_GUID, sayPreachTimer, Creature::SetDisableGravity(), Object::SetFlag(), Creature::SetHover(), Creature::SetReactState(), SPELL_SCHOOL_MASK_MAGIC, SPELL_SCHOOL_MASK_NORMAL, SPELL_WHITE_SPHERE, SUMMON_GROUP_OOC, SUMMON_GROUP_OOC_TRIGGERS, WorldObject::SummonCreatureGroup(), UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, UNIT_STAND_STATE_KNEEL, UNIT_STATE_NO_ENVIRONMENT_UPD, and volunteerWork.
SummonedCreatureDies()
void boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::SummonedCreatureDies (Creature * summon, Unit * killer) inline override virtual
Reimplemented from CreatureAI.
Definition at line 231 of file boss_jedoga_shadowseeker.cpp.
         {
             switch (summon->GetEntry())
             {
                 case NPC_TWILIGHT_INITIATE:
                 {
                     GuidList::iterator itr = std::find(oocSummons.begin(), oocSummons.end(), summon->GetGUID());
                     if (itr == oocSummons.end())
                     {
                         break;
                     }
                     oocSummons.erase(itr);
                     if (!oocSummons.empty())
                     {
                         break;
                     }
                     DespawnOOCSummons();
                     DoCastSelf(SPELL_HOVER_FALL);
                     me->GetMotionMaster()->MoveIdle();
                     me->GetMotionMaster()->MovePoint(POINT_DOWN, JedogaPosition[1], false);
                     if (!combatSummonsSummoned)
                     {
                         summons.DespawnEntry(NPC_TWILIGHT_VOLUNTEER);
                         for (uint8 i = 0; i < MAX_COMBAT_INITIATES; ++i)
{
                             if (TempSummon* summon = me->SummonCreature(NPC_TWILIGHT_VOLUNTEER, VolunteerSpotPositions[i][0], TEMPSUMMON_CORPSE_TIMED_DESPAWN, 5000))
{
                                 summon->GetMotionMaster()->MovePoint(POINT_INITIAL, VolunteerSpotPositions[i][1]);
                                 summon->SetReactState(REACT_PASSIVE);
                                 summon->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC );
                                 summons.Summon(summon);
                             }
                         }
                         combatSummonsSummoned = true;
                     }
                     break;
                 }
                 case NPC_TWILIGHT_VOLUNTEER:
                 {
                     if (sacraficeTarget_GUID && summon->GetGUID() != sacraficeTarget_GUID)
                     {
                         break;
                     }
                     if (killer != me && killer->GetGUID() != sacraficeTarget_GUID)
                     {
                         volunteerWork = false;
                     }
                     else
                     {
                         DoCastSelf(SPELL_GIFT_OF_THE_HERALD, true);
                     }
                     events.ScheduleEvent(EVENT_JEDOGA_MOVE_DOWN, 1000, 0, PHASE_RITUAL);
                     break;
                 }
             }
             summons.Despawn(summon);
         }
References combatSummonsSummoned, SummonList::Despawn(), SummonList::DespawnEntry(), DespawnOOCSummons(), UnitAI::DoCastSelf(), EVENT_JEDOGA_MOVE_DOWN, find(), Object::GetEntry(), Object::GetGUID(), Unit::GetMotionMaster(), JedogaPosition, MAX_COMBAT_INITIATES, ScriptedAI::me, MotionMaster::MoveIdle(), MotionMaster::MovePoint(), NPC_TWILIGHT_INITIATE, NPC_TWILIGHT_VOLUNTEER, oocSummons, PHASE_RITUAL, POINT_DOWN, POINT_INITIAL, REACT_PASSIVE, sacraficeTarget_GUID, Object::SetFlag(), Creature::SetReactState(), SPELL_GIFT_OF_THE_HERALD, SPELL_HOVER_FALL, SummonList::Summon(), WorldObject::SummonCreature(), BossAI::summons, TEMPSUMMON_CORPSE_TIMED_DESPAWN, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, VolunteerSpotPositions, and volunteerWork.
UpdateAI()
void boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 434 of file boss_jedoga_shadowseeker.cpp.
         {
             if (!UpdateVictim())
             {
                 if (instance->GetBossState(DATA_PRINCE_TALDARAM) == DONE)
                 {
                     if (sayPreachTimer <= diff)
                     {
                         Talk(SAY_PREACHING);
                         sayPreachTimer = 120000;    // 2 min
                     }
                     else
                     {
                         sayPreachTimer -= diff;
                     }
                 }
                 return;
             }
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
             {
                 return;
             }
             while (uint32 const eventId = events.ExecuteEvent())
             {
                 switch (eventId)
                 {
                     // Normal phase
                     case EVENT_JEDOGA_CYCLONE:
                     {
                         DoCastSelf(DUNGEON_MODE(SPELL_CYCLONE_STRIKE, SPELL_CYCLONE_STRIKE_H), false);
                         events.RepeatEvent(urand(10000, 14000));
                         break;
                     }
                     case EVENT_JEDOGA_LIGHTNING_BOLT:
                     {
                         if (Unit* pTarget = SelectTarget(SELECT_TARGET_RANDOM, 0, 100, true))
{
                             DoCast(pTarget, DUNGEON_MODE(SPELL_LIGHTNING_BOLT, SPELL_LIGHTNING_BOLT_H), false);
                         }
                         events.RepeatEvent(urand(11000, 15000));
                         break;
                     }
                     case EVENT_JEDOGA_THUNDERSHOCK:
                     {
                         if (Unit* pTarget = SelectTarget(SELECT_TARGET_RANDOM, 0, 100, true))
{
                             DoCast(pTarget, DUNGEON_MODE(SPELL_THUNDERSHOCK, SPELL_THUNDERSHOCK_H), false);
                         }
                         events.RepeatEvent(urand(16000, 22000));
                         break;
                     }
                     // Ritual phase
                     case EVENT_JEDOGA_PREPARE_RITUAL:
                     {
                         me->GetMotionMaster()->Clear(true);
                         me->GetMotionMaster()->MovePoint(POINT_RITUAL, JedogaPosition[1]);
                         break;
                     }
                     case EVENT_JEDOGA_MOVE_UP:
                     {
                         me->GetMotionMaster()->Clear(true);
                         me->SetDisableGravity(true);
                         me->SetHover(true);
                         me->GetMotionMaster()->MoveTakeoff(POINT_UP, JedogaPosition[0], 7.0f);
                         break;
                     }
                     case EVENT_JEDOGA_MOVE_DOWN:
                     {
                         summons.DespawnEntry(NPC_JEDOGA_CONTROLLER);
                         DoCastSelf(SPELL_HOVER_FALL);
                         me->GetMotionMaster()->Clear();
                         me->GetMotionMaster()->MovePoint(POINT_DOWN, JedogaPosition[1], false);
                         break;
                     }
                 }
             }
             DoMeleeAttackIfReady();
         }
References MotionMaster::Clear(), DATA_PRINCE_TALDARAM, SummonList::DespawnEntry(), diff(), UnitAI::DoCast(), UnitAI::DoCastSelf(), UnitAI::DoMeleeAttackIfReady(), DONE, ScriptedAI::DUNGEON_MODE(), EVENT_JEDOGA_CYCLONE, EVENT_JEDOGA_LIGHTNING_BOLT, EVENT_JEDOGA_MOVE_DOWN, EVENT_JEDOGA_MOVE_UP, EVENT_JEDOGA_PREPARE_RITUAL, EVENT_JEDOGA_THUNDERSHOCK, InstanceScript::GetBossState(), Unit::GetMotionMaster(), Unit::HasUnitState(), BossAI::instance, JedogaPosition, ScriptedAI::me, MotionMaster::MovePoint(), MotionMaster::MoveTakeoff(), NPC_JEDOGA_CONTROLLER, POINT_DOWN, POINT_RITUAL, POINT_UP, SAY_PREACHING, sayPreachTimer, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Creature::SetDisableGravity(), Creature::SetHover(), SPELL_CYCLONE_STRIKE, SPELL_CYCLONE_STRIKE_H, SPELL_HOVER_FALL, SPELL_LIGHTNING_BOLT, SPELL_LIGHTNING_BOLT_H, SPELL_THUNDERSHOCK, SPELL_THUNDERSHOCK_H, BossAI::summons, CreatureAI::Talk(), UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
combatSummonsSummoned
bool boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::combatSummonsSummoned private
Definition at line 533 of file boss_jedoga_shadowseeker.cpp.
Referenced by Reset(), and SummonedCreatureDies().
oocSummons
GuidList boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::oocSummons private
Definition at line 529 of file boss_jedoga_shadowseeker.cpp.
Referenced by DespawnOOCSummons(), Reset(), and SummonedCreatureDies().
oocTriggers
GuidList boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::oocTriggers private
Definition at line 530 of file boss_jedoga_shadowseeker.cpp.
Referenced by DespawnOOCSummons(), MovementInform(), and Reset().
ritualTriggered
bool boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::ritualTriggered private
Definition at line 534 of file boss_jedoga_shadowseeker.cpp.
Referenced by DamageTaken(), and Reset().
sacraficeTarget_GUID
ObjectGuid boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::sacraficeTarget_GUID private
Definition at line 531 of file boss_jedoga_shadowseeker.cpp.
Referenced by DoAction(), MovementInform(), Reset(), and SummonedCreatureDies().
sayPreachTimer
uint32 boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::sayPreachTimer private
Definition at line 532 of file boss_jedoga_shadowseeker.cpp.
Referenced by Reset(), and UpdateAI().
volunteerWork
bool boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::volunteerWork private
Definition at line 535 of file boss_jedoga_shadowseeker.cpp.
Referenced by GetData(), MovementInform(), Reset(), and SummonedCreatureDies().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/AzjolNerub/ahnkahet/boss_jedoga_shadowseeker.cpp