Azerotcore-wotlk: ChaseMovementGenerator< T > Class Template Reference
ChaseMovementGenerator< T > Class Template Reference
#include <TargetedMovementGenerator.h>
Public Member Functions
ChaseMovementGenerator (Unit *target, Optional< ChaseRange > range={}, Optional< ChaseAngle > angle={})
~ChaseMovementGenerator ()
MovementGeneratorType GetMovementGeneratorType ()
bool DoUpdate (T *, uint32)
void DoInitialize (T *)
void DoFinalize (T *)
void DoReset (T *)
void MovementInform (T *)
bool PositionOkay (T *owner, Unit *target, Optional< float > maxDistance, Optional< ChaseAngle > angle)
void unitSpeedChanged ()
Unit * GetTarget () const
bool EnableWalking () const
bool HasLostTarget (Unit *unit) const
void DoInitialize (Player *owner)
void DoInitialize (Creature *owner)
Public Member Functions inherited from MovementGeneratorMedium< T, ChaseMovementGenerator< T > >
void Initialize (Unit *u) override
void Finalize (Unit *u) override
void Reset (Unit *u) override
bool Update (Unit *u, uint32 time_diff) override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual uint32 GetSplineId () const
virtual bool GetResetPosition (float &, float &, float &)
Public Member Functions inherited from TargetedMovementGeneratorBase
TargetedMovementGeneratorBase (Unit *target)
void stopFollowing ()
Private Attributes
std::unique_ptr< PathGenerator > i_path
TimeTrackerSmall i_recheckDistance
bool i_recalculateTravel
Optional< Position > _lastTargetPosition
Optional< ChaseRange > const _range
Optional< ChaseAngle > const _angle
bool _movingTowards = true
bool _mutualChase = true
Additional Inherited Members
Protected Attributes inherited from TargetedMovementGeneratorBase
FollowerReference i_target
Detailed Description
template<class T>
class ChaseMovementGenerator< T >
Definition at line 38 of file TargetedMovementGenerator.h.
Constructor & Destructor Documentation
ChaseMovementGenerator()
template<class T > ChaseMovementGenerator< T >::ChaseMovementGenerator (Unit * target, Optional< ChaseRange > range = {}, Optional< ChaseAngle > angle = {}) inline
Definition at line 41 of file TargetedMovementGenerator.h.
                                                                       {}, Optional<ChaseAngle> angle = {})
         : TargetedMovementGeneratorBase(target), i_path(nullptr), i_recheckDistance(0), i_recalculateTravel(true), _range(range), _angle(angle) {}
~ChaseMovementGenerator()
template<class T > ChaseMovementGenerator< T >::~ChaseMovementGenerator () inline
Definition at line 43 of file TargetedMovementGenerator.h.
 { }
Member Function Documentation
DoFinalize()
template<class T > template void ChaseMovementGenerator< T >::DoFinalize (T *)
Definition at line 225 of file TargetedMovementGenerator.cpp.
 {
     owner->ClearUnitState(UNIT_STATE_CHASE | UNIT_STATE_CHASE_MOVE);
     if (Creature* cOwner = owner->ToCreature())
         cOwner->SetCannotReachTarget(false);
 }
References Object::ToCreature(), UNIT_STATE_CHASE, and UNIT_STATE_CHASE_MOVE.
DoInitialize() [1/3]
void ChaseMovementGenerator< Creature >::DoInitialize (Creature * owner)
Definition at line 216 of file TargetedMovementGenerator.cpp.
 {
     i_path = nullptr;
     _lastTargetPosition.reset();
     owner->SetWalk(false);
     owner->AddUnitState(UNIT_STATE_CHASE);
 }
References Unit::AddUnitState(), Creature::SetWalk(), and UNIT_STATE_CHASE.
DoInitialize() [2/3]
void ChaseMovementGenerator< Player >::DoInitialize (Player * owner)
Definition at line 208 of file TargetedMovementGenerator.cpp.
 {
     i_path = nullptr;
     _lastTargetPosition.reset();
     owner->AddUnitState(UNIT_STATE_CHASE);
 }
References Unit::AddUnitState(), and UNIT_STATE_CHASE.
DoInitialize() [3/3]
template<class T > void ChaseMovementGenerator< T >::DoInitialize (T *)
DoReset()
template<class T > template void ChaseMovementGenerator< T >::DoReset (T *)
Definition at line 233 of file TargetedMovementGenerator.cpp.
 {
     DoInitialize(owner);
 }
DoUpdate()
template<class T > template bool ChaseMovementGenerator< T >::DoUpdate (T * , uint32)
Definition at line 49 of file TargetedMovementGenerator.cpp.
 {
     if (!i_target.isValid() || !i_target->IsInWorld() || !owner->IsInMap(i_target.getTarget()))
         return false;
     if (!owner || !owner->IsAlive())
         return false;
     Creature* cOwner = owner->ToCreature();
     // the owner might be unable to move (rooted or casting), or we have lost the target, pause movement
     if (owner->HasUnitState(UNIT_STATE_NOT_MOVE) || HasLostTarget(owner) || (cOwner && cOwner->IsMovementPreventedByCasting()))
     {
         owner->StopMoving();
         _lastTargetPosition.reset();
         if (Creature* cOwner2 = owner->ToCreature())
         {
             cOwner2->SetCannotReachTarget(false);
         }
         return true;
     }
     bool forceDest =
         //(cOwner && (cOwner->isWorldBoss() || cOwner->IsDungeonBoss())) || // force for all bosses, even not in instances
         (i_target->GetTypeId() == TYPEID_PLAYER && i_target->ToPlayer()->IsGameMaster()) || // for .npc follow
         (owner->CanFly())
         ; // closes "bool forceDest", that way it is more appropriate, so we can comment out crap whenever we need to
     Unit* target = i_target.getTarget();
     bool const mutualChase = IsMutualChase(owner, target);
     float const hitboxSum = owner->GetCombatReach() + target->GetCombatReach();
     float const minTarget = (_range ? _range->MinTolerance : 0.0f) + hitboxSum;
     float const maxRange = _range ? _range->MaxRange + hitboxSum : owner->GetMeleeRange(target); // melee range already includes hitboxes
     float const maxTarget = _range ? _range->MaxTolerance + hitboxSum : CONTACT_DISTANCE + hitboxSum;
     Optional<ChaseAngle> angle = mutualChase ? Optional<ChaseAngle>() : _angle;
     i_recheckDistance.Update(time_diff);
     if (i_recheckDistance.Passed())
     {
         i_recheckDistance.Reset(100);
         if (i_recalculateTravel && PositionOkay(owner, target, _movingTowards ? maxTarget : Optional<float>(), angle))
         {
             i_recalculateTravel = false;
             i_path = nullptr;
             if (Creature* cOwner2 = owner->ToCreature())
             {
                 cOwner2->SetCannotReachTarget(false);
             }
             owner->StopMoving();
             owner->SetInFront(target);
             MovementInform(owner);
             return true;
         }
     }
     if (owner->HasUnitState(UNIT_STATE_CHASE_MOVE) && owner->movespline->Finalized())
     {
         i_recalculateTravel = false;
         i_path = nullptr;
         owner->ClearUnitState(UNIT_STATE_CHASE_MOVE);
         owner->SetInFront(target);
         MovementInform(owner);
         if (owner->IsWithinMeleeRange(this->i_target.getTarget()))
             owner->Attack(this->i_target.getTarget(), true);
     }
     if (_lastTargetPosition && i_target->GetPosition() == _lastTargetPosition.value() && mutualChase == _mutualChase)
         return true;
     _lastTargetPosition = i_target->GetPosition();
     if (PositionOkay(owner, target, maxRange, angle) && !owner->HasUnitState(UNIT_STATE_CHASE_MOVE))
         return true;
     float tarX, tarY, tarZ;
     target->GetPosition(tarX, tarY, tarZ);
     bool withinRange = owner->IsInDist(target, maxRange);
     bool withinLOS   = owner->IsWithinLOS(tarX, tarY, tarZ);
     bool moveToward  = !(withinRange && withinLOS);
     _mutualChase = mutualChase;
     if (owner->HasUnitState(UNIT_STATE_CHASE_MOVE))
     {
         // can we get to the target?
         if (cOwner && !target->isInAccessiblePlaceFor(cOwner))
         {
             cOwner->SetCannotReachTarget(true);
             cOwner->StopMoving();
             i_path = nullptr;
             return true;
         }
     }
     if (!i_path || moveToward != _movingTowards)
         i_path = std::make_unique<PathGenerator>(owner);
     else
         i_path->Clear();
     float x, y, z;
     bool shortenPath;
     // if we want to move toward the target and there's no fixed angle...
     if (moveToward && !angle)
     {
         // ...we'll pathfind to the center, then shorten the path
         target->GetPosition(x, y, z);
         shortenPath = true;
     }
     else
     {
         // otherwise, we fall back to nearpoint finding
         target->GetNearPoint(owner, x, y, z, (moveToward ? maxTarget : minTarget) - hitboxSum, 0, angle ? target->ToAbsoluteAngle(angle->RelativeAngle) : target->GetAngle(owner));
         shortenPath = false;
     }
     if (owner->IsHovering())
         owner->UpdateAllowedPositionZ(x, y, z);
     i_recalculateTravel = true;
     bool success = i_path->CalculatePath(x, y, z, forceDest);
     if (!success || i_path->GetPathType() & PATHFIND_NOPATH)
     {
         if (cOwner)
             cOwner->SetCannotReachTarget(true);
         return true;
     }
     if (shortenPath)
         i_path->ShortenPathUntilDist(G3D::Vector3(target->GetPositionX(), target->GetPositionY(), target->GetPositionZ()), maxTarget);
     if (cOwner)
         cOwner->SetCannotReachTarget(false);
     bool walk = false;
     if (cOwner && !cOwner->IsPet())
     {
         walk = owner->IsWalking();
     }
     owner->AddUnitState(UNIT_STATE_CHASE_MOVE);
     Movement::MoveSplineInit init(owner);
     init.MovebyPath(i_path->GetPath());
     init.SetFacing(target);
     init.SetWalk(walk);
     init.Launch();
     return true;
 }
References CONTACT_DISTANCE, Position::GetAngle(), Unit::GetCombatReach(), WorldObject::GetNearPoint(), Position::GetPosition(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::isInAccessiblePlaceFor(), Creature::IsMovementPreventedByCasting(), IsMutualChase(), Unit::IsPet(), Movement::MoveSplineInit::Launch(), Movement::MoveSplineInit::MovebyPath(), PATHFIND_NOPATH, Creature::SetCannotReachTarget(), Movement::MoveSplineInit::SetFacing(), Movement::MoveSplineInit::SetWalk(), Unit::StopMoving(), Position::ToAbsoluteAngle(), Object::ToCreature(), TYPEID_PLAYER, UNIT_STATE_CHASE_MOVE, and UNIT_STATE_NOT_MOVE.
EnableWalking()
template<class T > bool ChaseMovementGenerator< T >::EnableWalking () const inline
Definition at line 58 of file TargetedMovementGenerator.h.
 { return false; }
GetMovementGeneratorType()
template<class T > MovementGeneratorType ChaseMovementGenerator< T >::GetMovementGeneratorType () inline virtual
Implements MovementGenerator.
Definition at line 45 of file TargetedMovementGenerator.h.
 { return CHASE_MOTION_TYPE; }
References CHASE_MOTION_TYPE.
GetTarget()
template<class T > Unit* ChaseMovementGenerator< T >::GetTarget () const inline
Definition at line 56 of file TargetedMovementGenerator.h.
 { return i_target.getTarget(); }
References Reference< TO, FROM >::getTarget(), and TargetedMovementGeneratorBase::i_target.
Referenced by ChaseMovementGenerator< T >::HasLostTarget().
HasLostTarget()
template<class T > bool ChaseMovementGenerator< T >::HasLostTarget (Unit * unit) const inline
Definition at line 59 of file TargetedMovementGenerator.h.
 { return unit->GetVictim() != this->GetTarget(); }
References ChaseMovementGenerator< T >::GetTarget(), and Unit::GetVictim().
MovementInform()
template<class T > template void ChaseMovementGenerator< T >::MovementInform (T *)
Definition at line 239 of file TargetedMovementGenerator.cpp.
 {
     if (owner->GetTypeId() != TYPEID_UNIT)
         return;
     // Pass back the GUIDLow of the target. If it is pet's owner then PetAI will handle
     if (CreatureAI* AI = owner->ToCreature()->AI())
         AI->MovementInform(CHASE_MOTION_TYPE, i_target.getTarget()->GetGUID().GetCounter());
 }
References CHASE_MOTION_TYPE, and TYPEID_UNIT.
PositionOkay()
template<class T > bool ChaseMovementGenerator< T >::PositionOkay (T * owner, Unit * target, Optional< float > maxDistance, Optional< ChaseAngle > angle)
Definition at line 36 of file TargetedMovementGenerator.cpp.
 {
     float const distSq = owner->GetExactDistSq(target);
     if (maxDistance && distSq > G3D::square(*maxDistance))
         return false;
     if (angle && !angle->IsAngleOkay(target->GetRelativeAngle(owner)))
         return false;
     if (!owner->IsWithinLOSInMap(target))
         return false;
     return true;
 }
References Position::GetRelativeAngle().
unitSpeedChanged()
template<class T > void ChaseMovementGenerator< T >::unitSpeedChanged () inline virtual
Reimplemented from MovementGenerator.
Definition at line 55 of file TargetedMovementGenerator.h.
 { _lastTargetPosition.reset(); }
References ChaseMovementGenerator< T >::_lastTargetPosition.
Member Data Documentation
_angle
template<class T > Optional<ChaseAngle> const ChaseMovementGenerator< T >::_angle private
Definition at line 68 of file TargetedMovementGenerator.h.
_lastTargetPosition
template<class T > Optional<Position> ChaseMovementGenerator< T >::_lastTargetPosition private
Definition at line 66 of file TargetedMovementGenerator.h.
Referenced by ChaseMovementGenerator< T >::unitSpeedChanged().
_movingTowards
template<class T > bool ChaseMovementGenerator< T >::_movingTowards = true private
Definition at line 69 of file TargetedMovementGenerator.h.
_mutualChase
template<class T > bool ChaseMovementGenerator< T >::_mutualChase = true private
Definition at line 70 of file TargetedMovementGenerator.h.
_range
template<class T > Optional<ChaseRange> const ChaseMovementGenerator< T >::_range private
Definition at line 67 of file TargetedMovementGenerator.h.
i_path
template<class T > std::unique_ptr<PathGenerator> ChaseMovementGenerator< T >::i_path private
Definition at line 62 of file TargetedMovementGenerator.h.
i_recalculateTravel
template<class T > bool ChaseMovementGenerator< T >::i_recalculateTravel private
Definition at line 64 of file TargetedMovementGenerator.h.
i_recheckDistance
template<class T > TimeTrackerSmall ChaseMovementGenerator< T >::i_recheckDistance private
Definition at line 63 of file TargetedMovementGenerator.h.
The documentation for this class was generated from the following files:
src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.h
src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp