Azerotcore-wotlk: deps/mysqllite/mysys/mf_cache.c File Reference
mf_cache.c File Reference
#include "mysys_priv.h"
#include <m_string.h>
#include "my_static.h"
#include "mysys_err.h"
Functions
static my_bool cache_remove_open_tmp (IO_CACHE *cache __attribute__((unused)), const char *name)
my_bool open_cached_file (IO_CACHE *cache, const char *dir, const char *prefix, size_t cache_size, myf cache_myflags)
my_bool real_open_cached_file (IO_CACHE *cache)
void close_cached_file (IO_CACHE *cache)
Function Documentation
cache_remove_open_tmp()
static my_bool cache_remove_open_tmp (IO_CACHE *cache __attribute__(unused), const char * name) static
Definition at line 29 of file mf_cache.c.
 {
 #if O_TEMPORARY == 0
 #if !defined(CANT_DELETE_OPEN_FILES)
   /* The following should always succeed */
   (void) my_delete(name,MYF(MY_WME | ME_NOINPUT));
 #else
   int length;
   if (!(cache->file_name=
     (char*) my_malloc((length=strlen(name)+1),MYF(MY_WME))))
   {
     my_close(cache->file,MYF(0));
     cache->file = -1;
     errno=my_errno=ENOMEM;
     return 1;
   }
   memcpy(cache->file_name,name,length);
 #endif
 #endif /* O_TEMPORARY == 0 */
   return 0;
 }
References errno, G3D::length(), ME_NOINPUT, memcpy, my_close(), my_delete(), my_errno, my_malloc(), MY_WME, and MYF.
Referenced by real_open_cached_file().
close_cached_file()
void close_cached_file (IO_CACHE * cache)
Definition at line 98 of file mf_cache.c.
 {
   DBUG_ENTER("close_cached_file");
   if (my_b_inited(cache))
   {
     File file=cache->file;
     cache->file= -1;                /* Don't flush data */
     (void) end_io_cache(cache);
     if (file >= 0)
     {
       (void) my_close(file,MYF(0));
 #ifdef CANT_DELETE_OPEN_FILES
       if (cache->file_name)
       {
     (void) my_delete(cache->file_name,MYF(MY_WME | ME_NOINPUT));
     my_free(cache->file_name);
       }
 #endif
     }
     my_free(cache->dir);
     my_free(cache->prefix);
   }
   DBUG_VOID_RETURN;
 }
References DBUG_ENTER, DBUG_VOID_RETURN, st_io_cache::dir, end_io_cache(), mpq::file, st_io_cache::file, st_io_cache::file_name, ME_NOINPUT, my_b_inited, my_close(), my_delete(), my_free(), MY_WME, MYF, and st_io_cache::prefix.
open_cached_file()
my_bool open_cached_file (IO_CACHE * cache, const char * dir, const char * prefix, size_t cache_size, myf cache_myflags)
Definition at line 60 of file mf_cache.c.
 {
   DBUG_ENTER("open_cached_file");
   cache->dir=    dir ? my_strdup(dir,MYF(cache_myflags & MY_WME)) : (char*) 0;
   cache->prefix= (prefix ? my_strdup(prefix,MYF(cache_myflags & MY_WME)) :
          (char*) 0);
   cache->file_name=0;
   cache->buffer=0;              /* Mark that not open */
   if (!init_io_cache(cache,-1,cache_size,WRITE_CACHE,0L,0,
              MYF(cache_myflags | MY_NABP)))
   {
     DBUG_RETURN(0);
   }
   my_free(cache->dir);
   my_free(cache->prefix);
   DBUG_RETURN(1);
 }
References st_io_cache::buffer, DBUG_ENTER, DBUG_RETURN, st_io_cache::dir, st_io_cache::file_name, init_io_cache(), my_free(), MY_NABP, my_strdup(), MY_WME, MYF, st_io_cache::prefix, and WRITE_CACHE.
real_open_cached_file()
my_bool real_open_cached_file (IO_CACHE * cache)
Definition at line 81 of file mf_cache.c.
 {
   char name_buff[FN_REFLEN];
   int error=1;
   DBUG_ENTER("real_open_cached_file");
   if ((cache->file=create_temp_file(name_buff, cache->dir, cache->prefix,
                     (O_RDWR | O_BINARY | O_TRUNC |
                      O_TEMPORARY | O_SHORT_LIVED),
                     MYF(MY_WME))) >= 0)
   {
     error=0;
     cache_remove_open_tmp(cache, name_buff);
   }
   DBUG_RETURN(error);
 }
References cache_remove_open_tmp(), create_temp_file(), DBUG_ENTER, DBUG_RETURN, st_io_cache::dir, error(), st_io_cache::file, FN_REFLEN, MY_WME, MYF, O_BINARY, O_SHORT_LIVED, O_TEMPORARY, and st_io_cache::prefix.
Referenced by my_b_flush_io_cache().