Azerotcore-wotlk: Acore::Honor Namespace Reference
Acore::Honor Namespace Reference
Functions
float hk_honor_at_level_f (uint8 level, float multiplier=1.0f)
uint32 hk_honor_at_level (uint8 level, float multiplier=1.0f)
Function Documentation
hk_honor_at_level()
uint32 Acore::Honor::hk_honor_at_level (uint8 level, float multiplier = 1.0f) inline
Definition at line 33 of file Formulas.h.
     {
         return uint32(ceil(hk_honor_at_level_f(level, multiplier)));
     }
References hk_honor_at_level_f().
Referenced by BattlegroundMgr::BuildBattlegroundListPacket(), Spell::EffectAddHonor(), Battleground::GetBonusHonorFromKill(), and TEST().
hk_honor_at_level_f()
float Acore::Honor::hk_honor_at_level_f (uint8 level, float multiplier = 1.0f) inline
Definition at line 26 of file Formulas.h.
     {
         float honor = multiplier * level * 1.55f;
         //sScriptMgr->OnHonorCalculation(honor, level, multiplier); // pussywizard: optimization
         return honor;
     }
Referenced by hk_honor_at_level(), and Player::RewardHonor().