Azerotcore-wotlk: CreatureTextLocalizer< Builder > Class Template Reference
CreatureTextLocalizer< Builder > Class Template Reference
#include <CreatureTextMgr.h>
Public Member Functions
CreatureTextLocalizer (Builder const &builder, ChatMsg msgType)
~CreatureTextLocalizer ()
void operator() (Player *player)
Private Attributes
std::vector< std::pair< WorldPacket *, size_t > * > _packetCache
Builder const & _builder
ChatMsg _msgType
Detailed Description
template<class Builder>
class CreatureTextLocalizer< Builder >
Definition at line 121 of file CreatureTextMgr.h.
Constructor & Destructor Documentation
CreatureTextLocalizer()
template<class Builder > CreatureTextLocalizer< Builder >::CreatureTextLocalizer (Builder const & builder, ChatMsg msgType) inline
Definition at line 124 of file CreatureTextMgr.h.
                                                                    : _builder(builder), _msgType(msgType)
     {
         _packetCache.resize(TOTAL_LOCALES, nullptr);
     }
References CreatureTextLocalizer< Builder >::_packetCache, and TOTAL_LOCALES.
~CreatureTextLocalizer()
template<class Builder > CreatureTextLocalizer< Builder >::~CreatureTextLocalizer () inline
Definition at line 129 of file CreatureTextMgr.h.
     {
         for (size_t i = 0; i < _packetCache.size(); ++i)
         {
             if (_packetCache[i])
                 delete _packetCache[i]->first;
             delete _packetCache[i];
         }
     }
References CreatureTextLocalizer< Builder >::_packetCache.
Member Function Documentation
operator()()
template<class Builder > void CreatureTextLocalizer< Builder >::operator() (Player * player) inline
Definition at line 139 of file CreatureTextMgr.h.
     {
         LocaleConstant loc_idx = player->GetSession()->GetSessionDbLocaleIndex();
         WorldPacket* messageTemplate;
         size_t whisperGUIDpos;
         // create if not cached yet
         if (!_packetCache[loc_idx])
         {
             messageTemplate = new WorldPacket();
             whisperGUIDpos = _builder(messageTemplate, loc_idx);
             _packetCache[loc_idx] = new std::pair<WorldPacket*, size_t>(messageTemplate, whisperGUIDpos);
         }
         else
         {
             messageTemplate = _packetCache[loc_idx]->first;
             whisperGUIDpos = _packetCache[loc_idx]->second;
         }
         WorldPacket data(*messageTemplate);
         switch (_msgType)
         {
             case CHAT_MSG_MONSTER_WHISPER:
             case CHAT_MSG_RAID_BOSS_WHISPER:
                 data.put<uint64>(whisperGUIDpos, player->GetGUID().GetRawValue());
                 break;
             default:
                 break;
         }
         player->SendDirectMessage(&data);
     }
References CreatureTextLocalizer< Builder >::_builder, CreatureTextLocalizer< Builder >::_msgType, CreatureTextLocalizer< Builder >::_packetCache, CHAT_MSG_MONSTER_WHISPER, CHAT_MSG_RAID_BOSS_WHISPER, Object::GetGUID(), ObjectGuid::GetRawValue(), Player::GetSession(), WorldSession::GetSessionDbLocaleIndex(), and Player::SendDirectMessage().
Member Data Documentation
_builder
template<class Builder > Builder const& CreatureTextLocalizer< Builder >::_builder private
Definition at line 174 of file CreatureTextMgr.h.
Referenced by CreatureTextLocalizer< Builder >::operator()().
_msgType
template<class Builder > ChatMsg CreatureTextLocalizer< Builder >::_msgType private
Definition at line 175 of file CreatureTextMgr.h.
Referenced by CreatureTextLocalizer< Builder >::operator()().
_packetCache
template<class Builder > std::vector<std::pair<WorldPacket*, size_t>* > CreatureTextLocalizer< Builder >::_packetCache private
Definition at line 173 of file CreatureTextMgr.h.
Referenced by CreatureTextLocalizer< Builder >::CreatureTextLocalizer(), CreatureTextLocalizer< Builder >::operator()(), and CreatureTextLocalizer< Builder >::~CreatureTextLocalizer().
The documentation for this class was generated from the following file:
src/server/game/Texts/CreatureTextMgr.h