Azerotcore-wotlk: Creature Class Reference
Creature Class Reference
#include <Creature.h>
Public Member Functions
Creature (bool isWorldObject=false)
~Creature () override
void AddToWorld () override
void RemoveFromWorld () override
void SetObjectScale (float scale) override
void SetDisplayId (uint32 modelId) override
void DisappearAndDie ()
bool isVendorWithIconSpeak () const
bool Create (ObjectGuid::LowType guidlow, Map *map, uint32 phaseMask, uint32 Entry, uint32 vehId, float x, float y, float z, float ang, const CreatureData *data=nullptr)
bool LoadCreaturesAddon (bool reload=false)
void SelectLevel (bool changelevel=true)
void LoadEquipment (int8 id=1, bool force=false)
ObjectGuid::LowType GetSpawnId () const
void Update (uint32 time) override
void GetRespawnPosition (float &x, float &y, float &z, float *ori=nullptr, float *dist=nullptr) const
void SetCorpseDelay (uint32 delay)
uint32 GetCorpseDelay () const
bool IsRacialLeader () const
bool IsCivilian () const
bool IsTrigger () const
bool IsGuard () const
bool CanWalk () const
bool CanSwim () const override
This method check the current flag/status of a creature and its inhabit type.
bool CanEnterWater () const override
bool CanFly () const override
bool CanHover () const
void SetReactState (ReactStates st)
ReactStates GetReactState () const
bool HasReactState (ReactStates state) const
void InitializeReactState ()
bool isCanInteractWithBattleMaster (Player *player, bool msg) const
bool isCanTrainingAndResetTalentsOf (Player *player) const
bool IsValidTrainerForPlayer (Player *player, uint32 *npcFlags=nullptr) const
bool CanCreatureAttack (Unit const *victim, bool skipDistCheck=false) const
void LoadSpellTemplateImmunity ()
bool IsImmunedToSpell (SpellInfo const *spellInfo) override
bool HasMechanicTemplateImmunity (uint32 mask) const
bool IsImmunedToSpellEffect (SpellInfo const *spellInfo, uint32 index) const override
bool isElite () const
bool isWorldBoss () const
bool IsDungeonBoss () const
bool IsImmuneToKnockback () const
bool IsAvoidingAOE () const
uint8 getLevelForTarget (WorldObject const *target) const override
bool IsInEvadeMode () const
bool IsEvadingAttacks () const
bool AIM_Initialize (CreatureAI *ai=nullptr)
void Motion_Initialize ()
CreatureAI * AI () const
bool SetWalk (bool enable) override
bool SetDisableGravity (bool disable, bool packetOnly=false) override
bool SetSwim (bool enable) override
bool SetCanFly (bool enable, bool packetOnly=false) override
bool SetWaterWalking (bool enable, bool packetOnly=false) override
bool SetFeatherFall (bool enable, bool packetOnly=false) override
bool SetHover (bool enable, bool packetOnly=false) override
bool HasSpellFocus (Spell const *focusSpell=nullptr) const
uint32 GetShieldBlockValue () const override
SpellSchoolMask GetMeleeDamageSchoolMask () const override
void SetMeleeDamageSchool (SpellSchools school)
void _AddCreatureSpellCooldown (uint32 spell_id, uint16 categoryId, uint32 end_time)
void AddSpellCooldown (uint32 spell_id, uint32, uint32 end_time, bool needSendToClient=false, bool forceSendToSpectator=false) override
bool HasSpellCooldown (uint32 spell_id) const override
uint32 GetSpellCooldown (uint32 spell_id) const
void ProhibitSpellSchool (SpellSchoolMask idSchoolMask, uint32 unTimeMs) override
bool IsSpellProhibited (SpellSchoolMask idSchoolMask) const
bool HasSpell (uint32 spellID) const override
void UpdateMovementFlags ()
bool UpdateEntry (uint32 entry, const CreatureData *data=nullptr, bool changelevel=true)
bool UpdateStats (Stats stat) override
bool UpdateAllStats () override
void UpdateResistances (uint32 school) override
void UpdateArmor () override
void UpdateMaxHealth () override
void UpdateMaxPower (Powers power) override
void UpdateAttackPowerAndDamage (bool ranged=false) override
void CalculateMinMaxDamage (WeaponAttackType attType, bool normalized, bool addTotalPct, float &minDamage, float &maxDamage) override
void SetCanDualWield (bool value) override
int8 GetOriginalEquipmentId () const
uint8 GetCurrentEquipmentId ()
void SetCurrentEquipmentId (uint8 id)
float GetSpellDamageMod (int32 Rank)
VendorItemData const * GetVendorItems () const
uint32 GetVendorItemCurrentCount (VendorItem const *vItem)
uint32 UpdateVendorItemCurrentCount (VendorItem const *vItem, uint32 used_count)
TrainerSpellData const * GetTrainerSpells () const
CreatureTemplate const * GetCreatureTemplate () const
CreatureData const * GetCreatureData () const
void SetDetectionDistance (float dist)
CreatureAddon const * GetCreatureAddon () const
std::string GetAIName () const
std::string GetScriptName () const
uint32 GetScriptId () const
std::string const & GetNameForLocaleIdx (LocaleConstant locale_idx) const override
void setDeathState (DeathState s, bool despawn=false) override
bool LoadFromDB (ObjectGuid::LowType guid, Map *map, bool allowDuplicate=false)
bool LoadCreatureFromDB (ObjectGuid::LowType guid, Map *map, bool addToMap=true, bool gridLoad=false, bool allowDuplicate=false)
void SaveToDB ()
virtual void SaveToDB (uint32 mapid, uint8 spawnMask, uint32 phaseMask)
virtual void DeleteFromDB ()
ObjectGuid GetLootRecipientGUID () const
Player * GetLootRecipient () const
ObjectGuid::LowType GetLootRecipientGroupGUID () const
Group * GetLootRecipientGroup () const
bool hasLootRecipient () const
bool isTappedBy (Player const *player) const
bool CanGeneratePickPocketLoot () const
void SetPickPocketLootTime ()
void ResetPickPocketLootTime ()
void SetLootRecipient (Unit *unit, bool withGroup=true)
void AllLootRemovedFromCorpse ()
uint16 GetLootMode () const
bool HasLootMode (uint16 lootMode) const
void SetLootMode (uint16 lootMode)
void AddLootMode (uint16 lootMode)
void RemoveLootMode (uint16 lootMode)
void ResetLootMode ()
SpellInfo const * reachWithSpellAttack (Unit *victim)
SpellInfo const * reachWithSpellCure (Unit *victim)
bool CanStartAttack (Unit const *u) const
float GetAggroRange (Unit const *target) const
float GetAttackDistance (Unit const *player) const
float GetDetectionRange () const
void SendAIReaction (AiReaction reactionType)
Unit * SelectNearestTarget (float dist=0, bool playerOnly=false) const
Unit * SelectNearestTargetInAttackDistance (float dist) const
void DoFleeToGetAssistance ()
void CallForHelp (float fRadius)
void CallAssistance (Unit *target=nullptr)
void SetNoCallAssistance (bool val)
void SetNoSearchAssistance (bool val)
bool HasSearchedAssistance ()
bool CanAssistTo (const Unit *u, const Unit *enemy, bool checkfaction=true) const
bool _IsTargetAcceptable (const Unit *target) const
bool CanIgnoreFeignDeath () const
bool _CanDetectFeignDeathOf (const Unit *target) const
void UpdateMoveInLineOfSightState ()
bool IsMoveInLineOfSightDisabled ()
bool IsMoveInLineOfSightStrictlyDisabled ()
MovementGeneratorType GetDefaultMovementType () const
void SetDefaultMovementType (MovementGeneratorType mgt)
void RemoveCorpse (bool setSpawnTime=true, bool skipVisibility=false)
void DespawnOrUnsummon (Milliseconds msTimeToDespawn, Seconds forcedRespawnTimer)
void DespawnOrUnsummon (uint32 msTimeToDespawn=0)
void DespawnOnEvade ()
void RespawnOnEvade ()
time_t const & GetRespawnTime () const
time_t GetRespawnTimeEx () const
void SetRespawnTime (uint32 respawn)
void Respawn (bool force=false)
void SaveRespawnTime () override
uint32 GetRespawnDelay () const
void SetRespawnDelay (uint32 delay)
float GetWanderDistance () const
void SetWanderDistance (float dist)
void SendZoneUnderAttackMessage (Player *attacker)
Send a message to LocalDefense channel for players opposition team in the zone.
void SetInCombatWithZone ()
bool hasQuest (uint32 quest_id) const override
bool hasInvolvedQuest (uint32 quest_id) const override
bool isRegeneratingHealth ()
void SetRegeneratingHealth (bool c)
virtual uint8 GetPetAutoSpellSize () const
virtual uint32 GetPetAutoSpellOnPos (uint8 pos) const
void SetCannotReachTarget (bool cannotReach)
bool CanNotReachTarget () const
bool IsNotReachable () const
bool IsNotReachableAndNeedRegen () const
void SetPosition (float x, float y, float z, float o)
void SetPosition (const Position &pos)
void SetHomePosition (float x, float y, float z, float o)
void SetHomePosition (const Position &pos)
void GetHomePosition (float &x, float &y, float &z, float &ori) const
Position const & GetHomePosition () const
void SetTransportHomePosition (float x, float y, float z, float o)
void SetTransportHomePosition (const Position &pos)
void GetTransportHomePosition (float &x, float &y, float &z, float &ori) const
Position const & GetTransportHomePosition () const
uint32 GetWaypointPath () const
void LoadPath (uint32 pathid)
uint32 GetCurrentWaypointID () const
void UpdateWaypointID (uint32 wpID)
void SearchFormation ()
CreatureGroup const * GetFormation () const
CreatureGroup * GetFormation ()
void SetFormation (CreatureGroup *formation)
Unit * SelectVictim ()
void SetDisableReputationGain (bool disable)
bool IsReputationGainDisabled () const
bool IsDamageEnoughForLootingAndReward () const
void LowerPlayerDamageReq (uint32 unDamage)
void ResetPlayerDamageReq ()
uint32 GetOriginalEntry () const
void SetOriginalEntry (uint32 entry)
void SetTarget (ObjectGuid guid=ObjectGuid::Empty) override
void FocusTarget (Spell const *focusSpell, WorldObject const *target)
void ReleaseFocus (Spell const *focusSpell)
bool IsMovementPreventedByCasting () const override
time_t GetLastDamagedTime () const
std::shared_ptr< time_t > const & GetLastDamagedTimePtr () const
void SetLastDamagedTime (time_t val)
void SetLastDamagedTimePtr (std::shared_ptr< time_t > const &val)
bool IsFreeToMove ()
bool HasSwimmingFlagOutOfCombat () const
void RefreshSwimmingFlag (bool recheck=false)
void SetAssistanceTimer (uint32 value)
Public Member Functions inherited from Unit
~Unit () override
UnitAI * GetAI ()
void SetAI (UnitAI *newAI)
void AddToWorld () override
void RemoveFromWorld () override
void CleanupBeforeRemoveFromMap (bool finalCleanup)
void CleanupsBeforeDelete (bool finalCleanup=true) override
DiminishingLevels GetDiminishing (DiminishingGroup group)
void IncrDiminishing (DiminishingGroup group)
float ApplyDiminishingToDuration (DiminishingGroup group, int32 &duration, Unit *caster, DiminishingLevels Level, int32 limitduration)
void ApplyDiminishingAura (DiminishingGroup group, bool apply)
void ClearDiminishings ()
float GetSpellMaxRangeForTarget (Unit const *target, SpellInfo const *spellInfo) const
float GetSpellMinRangeForTarget (Unit const *target, SpellInfo const *spellInfo) const
void Update (uint32 time) override
void setAttackTimer (WeaponAttackType type, int32 time)
void resetAttackTimer (WeaponAttackType type=BASE_ATTACK)
int32 getAttackTimer (WeaponAttackType type) const
bool isAttackReady (WeaponAttackType type=BASE_ATTACK) const
bool haveOffhandWeapon () const
bool CanDualWield () const
float GetCombatReach () const override
float GetMeleeReach () const
bool IsWithinRange (Unit const *obj, float dist) const
bool IsWithinCombatRange (const Unit *obj, float dist2compare) const
bool IsWithinMeleeRange (const Unit *obj, float dist=0.f) const
float GetMeleeRange (Unit const *target) const
bool GetRandomContactPoint (const Unit *target, float &x, float &y, float &z, bool force=false) const
void _addAttacker (Unit *pAttacker)
void _removeAttacker (Unit *pAttacker)
Unit * getAttackerForHelper () const
bool Attack (Unit *victim, bool meleeAttack)
void CastStop (uint32 except_spellid=0, bool withInstant=true)
bool AttackStop ()
void RemoveAllAttackers ()
AttackerSet const & getAttackers () const
bool GetMeleeAttackPoint (Unit *attacker, Position &pos)
bool isAttackingPlayer () const
Unit * GetVictim () const
void CombatStop (bool includingCast=false)
void CombatStopWithPets (bool includingCast=false)
void StopAttackFaction (uint32 faction_id)
Unit * SelectNearbyTarget (Unit *exclude=nullptr, float dist=NOMINAL_MELEE_RANGE) const
Unit * SelectNearbyNoTotemTarget (Unit *exclude=nullptr, float dist=NOMINAL_MELEE_RANGE) const
void SendMeleeAttackStop (Unit *victim=nullptr)
void SendMeleeAttackStart (Unit *victim, Player *sendTo=nullptr)
void AddUnitState (uint32 f)
bool HasUnitState (const uint32 f) const
void ClearUnitState (uint32 f)
uint32 GetUnitState () const
bool CanFreeMove () const
uint32 HasUnitTypeMask (uint32 mask) const
void AddUnitTypeMask (uint32 mask)
uint32 GetUnitTypeMask () const
bool IsSummon () const
bool IsGuardian () const
bool IsControllableGuardian () const
bool IsPet () const
bool IsHunterPet () const
bool IsTotem () const
bool IsVehicle () const
uint8 getLevel () const
uint8 getLevelForTarget (WorldObject const *) const override
void SetLevel (uint8 lvl, bool showLevelChange=true)
uint8 getRace (bool original=false) const
void setRace (uint8 race)
uint32 getRaceMask () const
uint8 getClass () const
uint32 getClassMask () const
uint8 getGender () const
float GetStat (Stats stat) const
void SetStat (Stats stat, int32 val)
uint32 GetArmor () const
void SetArmor (int32 val)
uint32 GetResistance (SpellSchools school) const
uint32 GetResistance (SpellSchoolMask mask) const
void SetResistance (SpellSchools school, int32 val)
uint32 GetHealth () const
uint32 GetMaxHealth () const
bool IsFullHealth () const
bool HealthBelowPct (int32 pct) const
bool HealthBelowPctDamaged (int32 pct, uint32 damage) const
bool HealthAbovePct (int32 pct) const
bool HealthAbovePctHealed (int32 pct, uint32 heal) const
float GetHealthPct () const
uint32 CountPctFromMaxHealth (int32 pct) const
uint32 CountPctFromCurHealth (int32 pct) const
float GetPowerPct (Powers power) const
void SetHealth (uint32 val)
void SetMaxHealth (uint32 val)
void SetFullHealth ()
int32 ModifyHealth (int32 val)
int32 GetHealthGain (int32 dVal)
Powers getPowerType () const
void setPowerType (Powers power)
uint32 GetPower (Powers power) const
uint32 GetMaxPower (Powers power) const
void SetPower (Powers power, uint32 val)
void SetMaxPower (Powers power, uint32 val)
int32 ModifyPower (Powers power, int32 val)
int32 ModifyPowerPct (Powers power, float pct, bool apply=true)
uint32 GetAttackTime (WeaponAttackType att) const
void SetAttackTime (WeaponAttackType att, uint32 val)
void ApplyAttackTimePercentMod (WeaponAttackType att, float val, bool apply)
void ApplyCastTimePercentMod (float val, bool apply)
SheathState GetSheath () const
virtual void SetSheath (SheathState sheathed)
uint32 GetFaction () const
void SetFaction (uint32 faction)
FactionTemplateEntry const * GetFactionTemplateEntry () const
ReputationRank GetReactionTo (Unit const *target) const
ReputationRank GetFactionReactionTo (FactionTemplateEntry const *factionTemplateEntry, Unit const *target) const
bool IsHostileTo (Unit const *unit) const
bool IsHostileToPlayers () const
bool IsFriendlyTo (Unit const *unit) const
bool IsNeutralToAll () const
bool IsInPartyWith (Unit const *unit) const
bool IsInRaidWith (Unit const *unit) const
void GetPartyMembers (std::list< Unit * > &units)
bool IsContestedGuard () const
bool IsInSanctuary () const
bool IsPvP () const
bool IsFFAPvP () const
void SetPvP (bool state)
uint32 GetCreatureType () const
uint32 GetCreatureTypeMask () const
uint8 getStandState () const
bool IsSitState () const
bool IsStandState () const
void SetStandState (uint8 state)
void SetStandFlags (uint8 flags)
void RemoveStandFlags (uint8 flags)
bool IsMounted () const
uint32 GetMountID () const
void Mount (uint32 mount, uint32 vehicleId=0, uint32 creatureEntry=0)
void Dismount ()
uint16 GetMaxSkillValueForLevel (Unit const *target=nullptr) const
void ProcDamageAndSpell (Unit *victim, uint32 procAttacker, uint32 procVictim, uint32 procEx, uint32 amount, WeaponAttackType attType=BASE_ATTACK, SpellInfo const *procSpellInfo=nullptr, SpellInfo const *procAura=nullptr, int8 procAuraEffectIndex=-1, Spell const *procSpell=nullptr, DamageInfo *damageInfo=nullptr, HealInfo *healInfo=nullptr)
void ProcDamageAndSpellFor (bool isVictim, Unit *target, uint32 procFlag, uint32 procExtra, WeaponAttackType attType, SpellInfo const *procSpellInfo, uint32 damage, SpellInfo const *procAura=nullptr, int8 procAuraEffectIndex=-1, Spell const *procSpell=nullptr, DamageInfo *damageInfo=nullptr, HealInfo *healInfo=nullptr)
void GetProcAurasTriggeredOnEvent (std::list< AuraApplication * > &aurasTriggeringProc, std::list< AuraApplication * > *procAuras, ProcEventInfo eventInfo)
void TriggerAurasProcOnEvent (CalcDamageInfo &damageInfo)
void TriggerAurasProcOnEvent (std::list< AuraApplication * > *myProcAuras, std::list< AuraApplication * > *targetProcAuras, Unit *actionTarget, uint32 typeMaskActor, uint32 typeMaskActionTarget, uint32 spellTypeMask, uint32 spellPhaseMask, uint32 hitMask, Spell *spell, DamageInfo *damageInfo, HealInfo *healInfo)
void TriggerAurasProcOnEvent (ProcEventInfo &eventInfo, std::list< AuraApplication * > &procAuras)
void HandleEmoteCommand (uint32 anim_id)
void AttackerStateUpdate (Unit *victim, WeaponAttackType attType=BASE_ATTACK, bool extra=false)
void CalculateMeleeDamage (Unit *victim, uint32 damage, CalcDamageInfo *damageInfo, WeaponAttackType attackType=BASE_ATTACK, const bool sittingVictim=false)
void DealMeleeDamage (CalcDamageInfo *damageInfo, bool durabilityLoss)
void HandleProcExtraAttackFor (Unit *victim)
void CalculateSpellDamageTaken (SpellNonMeleeDamage *damageInfo, int32 damage, SpellInfo const *spellInfo, WeaponAttackType attackType=BASE_ATTACK, bool crit=false)
void DealSpellDamage (SpellNonMeleeDamage *damageInfo, bool durabilityLoss)
float GetMeleeCritChanceReduction () const
float GetRangedCritChanceReduction () const
float GetSpellCritChanceReduction () const
uint32 GetMeleeCritDamageReduction (uint32 damage) const
uint32 GetRangedCritDamageReduction (uint32 damage) const
uint32 GetSpellCritDamageReduction (uint32 damage) const
uint32 GetMeleeDamageReduction (uint32 damage) const
uint32 GetRangedDamageReduction (uint32 damage) const
uint32 GetSpellDamageReduction (uint32 damage) const
float MeleeSpellMissChance (const Unit *victim, WeaponAttackType attType, int32 skillDiff, uint32 spellId) const
SpellMissInfo MeleeSpellHitResult (Unit *victim, SpellInfo const *spell)
SpellMissInfo MagicSpellHitResult (Unit *victim, SpellInfo const *spell)
SpellMissInfo SpellHitResult (Unit *victim, SpellInfo const *spell, bool canReflect=false)
float GetUnitDodgeChance () const
float GetUnitParryChance () const
float GetUnitBlockChance () const
float GetUnitMissChance (WeaponAttackType attType) const
float GetUnitCriticalChance (WeaponAttackType attackType, const Unit *victim) const
int32 GetMechanicResistChance (const SpellInfo *spell)
bool CanUseAttackType (uint8 attacktype) const
uint32 GetShieldBlockValue (uint32 soft_cap, uint32 hard_cap) const
uint32 GetUnitMeleeSkill (Unit const *target=nullptr) const
uint32 GetDefenseSkillValue (Unit const *target=nullptr) const
uint32 GetWeaponSkillValue (WeaponAttackType attType, Unit const *target=nullptr) const
float GetWeaponProcChance () const
float GetPPMProcChance (uint32 WeaponSpeed, float PPM, const SpellInfo *spellProto) const
MeleeHitOutcome RollMeleeOutcomeAgainst (const Unit *victim, WeaponAttackType attType) const
MeleeHitOutcome RollMeleeOutcomeAgainst (const Unit *victim, WeaponAttackType attType, int32 crit_chance, int32 miss_chance, int32 dodge_chance, int32 parry_chance, int32 block_chance) const
bool IsVendor () const
bool IsTrainer () const
bool IsQuestGiver () const
bool IsGossip () const
bool IsTaxi () const
bool IsGuildMaster () const
bool IsBattleMaster () const
bool IsBanker () const
bool IsInnkeeper () const
bool IsSpiritHealer () const
bool IsSpiritGuide () const
bool IsTabardDesigner () const
bool IsAuctioner () const
bool IsArmorer () const
bool IsServiceProvider () const
bool IsSpiritService () const
bool IsCritter () const
bool IsInFlight () const
bool IsInCombat () const
bool IsInCombatWith (Unit const *who) const
bool IsPetInCombat () const
void CombatStart (Unit *target, bool initialAggro=true)
void CombatStartOnCast (Unit *target, bool initialAggro=true, uint32 duration=0)
void SetInCombatState (bool PvP, Unit *enemy=nullptr, uint32 duration=0)
void SetInCombatWith (Unit *enemy, uint32 duration=0)
void ClearInCombat ()
void ClearInPetCombat ()
uint32 GetCombatTimer () const
bool HasAuraTypeWithFamilyFlags (AuraType auraType, uint32 familyName, uint32 familyFlags) const
bool HasBreakableByDamageAuraType (AuraType type, uint32 excludeAura=0) const
bool HasBreakableByDamageCrowdControlAura (Unit *excludeCasterChannel=nullptr) const
bool HasStealthAura () const
bool HasInvisibilityAura () const
bool isFeared () const
bool isInRoots () const
bool IsPolymorphed () const
bool isFrozen () const
bool isTargetableForAttack (bool checkFakeDeath=true, Unit const *byWho=nullptr) const
bool IsValidAttackTarget (Unit const *target) const
bool _IsValidAttackTarget (Unit const *target, SpellInfo const *bySpell, WorldObject const *obj=nullptr) const
bool IsValidAssistTarget (Unit const *target) const
bool _IsValidAssistTarget (Unit const *target, SpellInfo const *bySpell) const
virtual bool IsInWater () const
virtual bool IsUnderWater () const
bool isInAccessiblePlaceFor (Creature const *c) const
void SendHealSpellLog (Unit *victim, uint32 SpellID, uint32 Damage, uint32 OverHeal, uint32 Absorb, bool critical=false)
int32 HealBySpell (HealInfo &healInfo, bool critical=false)
void SendEnergizeSpellLog (Unit *victim, uint32 SpellID, uint32 Damage, Powers powertype)
void EnergizeBySpell (Unit *victim, uint32 SpellID, uint32 Damage, Powers powertype)
SpellCastResult CastSpell (SpellCastTargets const &targets, SpellInfo const *spellInfo, CustomSpellValues const *value, TriggerCastFlags triggerFlags=TRIGGERED_NONE, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastSpell (Unit *victim, uint32 spellId, bool triggered, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastSpell (Unit *victim, uint32 spellId, TriggerCastFlags triggerFlags=TRIGGERED_NONE, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastSpell (Unit *victim, SpellInfo const *spellInfo, bool triggered, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastSpell (Unit *victim, SpellInfo const *spellInfo, TriggerCastFlags triggerFlags=TRIGGERED_NONE, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastSpell (float x, float y, float z, uint32 spellId, bool triggered, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastSpell (GameObject *go, uint32 spellId, bool triggered, Item *castItem=nullptr, AuraEffect *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastCustomSpell (Unit *victim, uint32 spellId, int32 const *bp0, int32 const *bp1, int32 const *bp2, bool triggered, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastCustomSpell (uint32 spellId, SpellValueMod mod, int32 value, Unit *victim, bool triggered, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastCustomSpell (uint32 spellId, SpellValueMod mod, int32 value, Unit *victim=nullptr, TriggerCastFlags triggerFlags=TRIGGERED_NONE, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
SpellCastResult CastCustomSpell (uint32 spellId, CustomSpellValues const &value, Unit *victim=nullptr, TriggerCastFlags triggerFlags=TRIGGERED_NONE, Item *castItem=nullptr, AuraEffect const *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid::Empty)
Aura * AddAura (uint32 spellId, Unit *target)
Aura * AddAura (SpellInfo const *spellInfo, uint8 effMask, Unit *target)
void SetAuraStack (uint32 spellId, Unit *target, uint32 stack)
void SendPlaySpellVisual (uint32 id)
void SendPlaySpellImpact (ObjectGuid guid, uint32 id)
void BuildCooldownPacket (WorldPacket &data, uint8 flags, uint32 spellId, uint32 cooldown)
void BuildCooldownPacket (WorldPacket &data, uint8 flags, PacketCooldowns const &cooldowns)
void DeMorph ()
void SendAttackStateUpdate (CalcDamageInfo *damageInfo)
void SendAttackStateUpdate (uint32 HitInfo, Unit *target, uint8 SwingType, SpellSchoolMask damageSchoolMask, uint32 Damage, uint32 AbsorbDamage, uint32 Resist, VictimState TargetState, uint32 BlockedAmount)
void SendSpellNonMeleeDamageLog (SpellNonMeleeDamage *log)
void SendSpellNonMeleeReflectLog (SpellNonMeleeDamage *log, Unit *attacker)
void SendSpellNonMeleeDamageLog (Unit *target, SpellInfo const *spellInfo, uint32 Damage, SpellSchoolMask damageSchoolMask, uint32 AbsorbedDamage, uint32 Resist, bool PhysicalDamage, uint32 Blocked, bool CriticalHit=false)
void SendPeriodicAuraLog (SpellPeriodicAuraLogInfo *pInfo)
void SendSpellMiss (Unit *target, uint32 spellID, SpellMissInfo missInfo)
void SendSpellDamageResist (Unit *target, uint32 spellId)
void SendSpellDamageImmune (Unit *target, uint32 spellId)
void NearTeleportTo (float x, float y, float z, float orientation, bool casting=false, bool vehicleTeleport=false, bool withPet=false, bool removeTransport=false)
void SendTameFailure (uint8 result)
void SendTeleportPacket (Position &pos)
virtual bool UpdatePosition (float x, float y, float z, float ang, bool teleport=false)
bool UpdatePosition (const Position &pos, bool teleport=false)
void UpdateOrientation (float orientation)
Only server-side orientation update, does not broadcast to client.
void UpdateHeight (float newZ)
Only server-side height update, does not broadcast to client.
void KnockbackFrom (float x, float y, float speedXY, float speedZ)
void JumpTo (float speedXY, float speedZ, bool forward=true)
void JumpTo (WorldObject *obj, float speedZ)
void SendMonsterMove (float NewPosX, float NewPosY, float NewPosZ, uint32 TransitTime, SplineFlags sf=SPLINEFLAG_WALK_MODE)
void MonsterMoveWithSpeed (float x, float y, float z, float speed)
void SendMovementFlagUpdate (bool self=false)
void SendMovementWaterWalking (Player *sendTo)
void SendMovementFeatherFall (Player *sendTo)
void SendMovementHover (Player *sendTo)
void SetInFront (WorldObject const *target)
void SetFacingTo (float ori)
void SetFacingToObject (WorldObject *object)
void SendChangeCurrentVictimOpcode (HostileReference *pHostileReference)
void SendClearThreatListOpcode ()
void SendRemoveFromThreatListOpcode (HostileReference *pHostileReference)
void SendThreatListUpdate ()
void SendClearTarget ()
void BuildHeartBeatMsg (WorldPacket *data) const
bool IsAlive () const
bool isDying () const
bool isDead () const
DeathState getDeathState ()
ObjectGuid GetOwnerGUID () const
void SetOwnerGUID (ObjectGuid owner)
ObjectGuid GetCreatorGUID () const
void SetCreatorGUID (ObjectGuid creator)
ObjectGuid GetMinionGUID () const
void SetMinionGUID (ObjectGuid guid)
ObjectGuid GetCharmerGUID () const
void SetCharmerGUID (ObjectGuid owner)
ObjectGuid GetCharmGUID () const
void SetPetGUID (ObjectGuid guid)
ObjectGuid GetPetGUID () const
void SetCritterGUID (ObjectGuid guid)
ObjectGuid GetCritterGUID () const
bool IsControlledByPlayer () const
bool IsCreatedByPlayer () const
ObjectGuid GetCharmerOrOwnerGUID () const
ObjectGuid GetCharmerOrOwnerOrOwnGUID () const
bool IsCharmedOwnedByPlayerOrPlayer () const
Player * GetSpellModOwner () const
Unit * GetOwner () const
Guardian * GetGuardianPet () const
Minion * GetFirstMinion () const
Unit * GetCharmer () const
Unit * GetCharm () const
Unit * GetCharmerOrOwner () const
Unit * GetCharmerOrOwnerOrSelf () const
Player * GetCharmerOrOwnerPlayerOrPlayerItself () const
Player * GetAffectingPlayer () const
void SetMinion (Minion *minion, bool apply)
void GetAllMinionsByEntry (std::list< Creature * > &Minions, uint32 entry)
void RemoveAllMinionsByEntry (uint32 entry)
void SetCharm (Unit *target, bool apply)
Unit * GetNextRandomRaidMemberOrPet (float radius)
bool SetCharmedBy (Unit *charmer, CharmType type, AuraApplication const *aurApp=nullptr)
void RemoveCharmedBy (Unit *charmer)
void RestoreFaction ()
Unit * GetFirstControlled () const
void RemoveAllControlled (bool onDeath=false)
bool IsCharmed () const
bool isPossessed () const
bool isPossessedByPlayer () const
bool isPossessing () const
bool isPossessing (Unit *u) const
CharmInfo * GetCharmInfo ()
CharmInfo * InitCharmInfo ()
void DeleteCharmInfo ()
void UpdateCharmAI ()
SharedVisionList const & GetSharedVisionList ()
void AddPlayerToVision (Player *player)
void RemovePlayerFromVision (Player *player)
bool HasSharedVision () const
void RemoveBindSightAuras ()
void RemoveCharmAuras ()
Pet * CreateTamedPetFrom (Creature *creatureTarget, uint32 spell_id=0)
Pet * CreateTamedPetFrom (uint32 creatureEntry, uint32 spell_id=0)
bool InitTamedPet (Pet *pet, uint8 level, uint32 spell_id)
Aura * _TryStackingOrRefreshingExistingAura (SpellInfo const *newAura, uint8 effMask, Unit *caster, int32 *baseAmount=nullptr, Item *castItem=nullptr, ObjectGuid casterGUID=ObjectGuid::Empty, bool periodicReset=false)
void _AddAura (UnitAura *aura, Unit *caster)
AuraApplication * _CreateAuraApplication (Aura *aura, uint8 effMask)
void _ApplyAuraEffect (Aura *aura, uint8 effIndex)
void _ApplyAura (AuraApplication *aurApp, uint8 effMask)
void _UnapplyAura (AuraApplicationMap::iterator &i, AuraRemoveMode removeMode)
void _UnapplyAura (AuraApplication *aurApp, AuraRemoveMode removeMode)
void _RemoveNoStackAuraApplicationsDueToAura (Aura *aura)
void _RemoveNoStackAurasDueToAura (Aura *aura)
bool _IsNoStackAuraDueToAura (Aura *appliedAura, Aura *existingAura) const
void _RegisterAuraEffect (AuraEffect *aurEff, bool apply)
AuraMap & GetOwnedAuras ()
AuraMap const & GetOwnedAuras () const
void RemoveOwnedAura (AuraMap::iterator &i, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
void RemoveOwnedAura (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, uint8 reqEffMask=0, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
void RemoveOwnedAura (Aura *aura, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
Aura * GetOwnedAura (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, ObjectGuid itemCasterGUID=ObjectGuid::Empty, uint8 reqEffMask=0, Aura *except=nullptr) const
AuraApplicationMap & GetAppliedAuras ()
AuraApplicationMap const & GetAppliedAuras () const
void RemoveAura (AuraApplicationMap::iterator &i, AuraRemoveMode mode=AURA_REMOVE_BY_DEFAULT)
void RemoveAura (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, uint8 reqEffMask=0, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
void RemoveAura (AuraApplication *aurApp, AuraRemoveMode mode=AURA_REMOVE_BY_DEFAULT)
void RemoveAura (Aura *aur, AuraRemoveMode mode=AURA_REMOVE_BY_DEFAULT)
void RemoveAppliedAuras (std::function< bool(AuraApplication const *)> const &check)
void RemoveOwnedAuras (std::function< bool(Aura const *)> const &check)
void RemoveAppliedAuras (uint32 spellId, std::function< bool(AuraApplication const *)> const &check)
void RemoveOwnedAuras (uint32 spellId, std::function< bool(Aura const *)> const &check)
void RemoveAurasDueToSpell (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, uint8 reqEffMask=0, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
void RemoveAuraFromStack (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
void RemoveAurasDueToSpellByDispel (uint32 spellId, uint32 dispellerSpellId, ObjectGuid casterGUID, Unit *dispeller, uint8 chargesRemoved=1)
void RemoveAurasDueToSpellBySteal (uint32 spellId, ObjectGuid casterGUID, Unit *stealer)
void RemoveAurasDueToItemSpell (uint32 spellId, ObjectGuid castItemGuid)
void RemoveAurasByType (AuraType auraType, ObjectGuid casterGUID=ObjectGuid::Empty, Aura *except=nullptr, bool negative=true, bool positive=true)
void RemoveNotOwnSingleTargetAuras ()
void RemoveAurasWithInterruptFlags (uint32 flag, uint32 except=0)
void RemoveAurasWithAttribute (uint32 flags)
void RemoveAurasWithFamily (SpellFamilyNames family, uint32 familyFlag1, uint32 familyFlag2, uint32 familyFlag3, ObjectGuid casterGUID)
void RemoveAurasWithMechanic (uint32 mechanic_mask, AuraRemoveMode removemode=AURA_REMOVE_BY_DEFAULT, uint32 except=0)
void RemoveMovementImpairingAuras (bool withRoot)
void RemoveAurasByShapeShift ()
void RemoveAreaAurasDueToLeaveWorld ()
void RemoveAllAuras ()
void RemoveArenaAuras ()
void RemoveAllAurasOnDeath ()
void RemoveAllAurasRequiringDeadTarget ()
void RemoveAllAurasExceptType (AuraType type)
void RemoveEvadeAuras ()
void DelayOwnedAuras (uint32 spellId, ObjectGuid caster, int32 delaytime)
void _RemoveAllAuraStatMods ()
void _ApplyAllAuraStatMods ()
AuraEffectList const & GetAuraEffectsByType (AuraType type) const
AuraList & GetSingleCastAuras ()
AuraList const & GetSingleCastAuras () const
AuraEffect * GetAuraEffect (uint32 spellId, uint8 effIndex, ObjectGuid casterGUID=ObjectGuid::Empty) const
AuraEffect * GetAuraEffectOfRankedSpell (uint32 spellId, uint8 effIndex, ObjectGuid casterGUID=ObjectGuid::Empty) const
AuraEffect * GetAuraEffect (AuraType type, SpellFamilyNames name, uint32 iconId, uint8 effIndex) const
AuraEffect * GetAuraEffect (AuraType type, SpellFamilyNames family, uint32 familyFlag1, uint32 familyFlag2, uint32 familyFlag3, ObjectGuid casterGUID=ObjectGuid::Empty) const
AuraEffect * GetAuraEffectDummy (uint32 spellid) const
AuraEffect * GetDummyAuraEffect (SpellFamilyNames name, uint32 iconId, uint8 effIndex) const
AuraApplication * GetAuraApplication (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, ObjectGuid itemCasterGUID=ObjectGuid::Empty, uint8 reqEffMask=0, AuraApplication *except=nullptr) const
Aura * GetAura (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, ObjectGuid itemCasterGUID=ObjectGuid::Empty, uint8 reqEffMask=0) const
AuraApplication * GetAuraApplicationOfRankedSpell (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, ObjectGuid itemCasterGUID=ObjectGuid::Empty, uint8 reqEffMask=0, AuraApplication *except=nullptr) const
Aura * GetAuraOfRankedSpell (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, ObjectGuid itemCasterGUID=ObjectGuid::Empty, uint8 reqEffMask=0) const
void GetDispellableAuraList (Unit *caster, uint32 dispelMask, DispelChargesList &dispelList)
bool HasAuraEffect (uint32 spellId, uint8 effIndex, ObjectGuid caster=ObjectGuid::Empty) const
uint32 GetAuraCount (uint32 spellId) const
bool HasAura (uint32 spellId, ObjectGuid casterGUID=ObjectGuid::Empty, ObjectGuid itemCasterGUID=ObjectGuid::Empty, uint8 reqEffMask=0) const
bool HasAuraType (AuraType auraType) const
bool HasAuraTypeWithCaster (AuraType auratype, ObjectGuid caster) const
bool HasAuraTypeWithMiscvalue (AuraType auratype, int32 miscvalue) const
bool HasAuraTypeWithAffectMask (AuraType auratype, SpellInfo const *affectedSpell) const
bool HasAuraTypeWithValue (AuraType auratype, int32 value) const
bool HasNegativeAuraWithInterruptFlag (uint32 flag, ObjectGuid guid=ObjectGuid::Empty)
bool HasVisibleAuraType (AuraType auraType) const
bool HasNegativeAuraWithAttribute (uint32 flag, ObjectGuid guid=ObjectGuid::Empty)
bool HasAuraWithMechanic (uint32 mechanicMask) const
AuraEffect * IsScriptOverriden (SpellInfo const *spell, int32 script) const
uint32 GetDiseasesByCaster (ObjectGuid casterGUID, uint8 mode=0)
uint32 GetDoTsByCaster (ObjectGuid casterGUID) const
int32 GetTotalAuraModifierAreaExclusive (AuraType auratype) const
int32 GetTotalAuraModifier (AuraType auratype) const
float GetTotalAuraMultiplier (AuraType auratype) const
int32 GetMaxPositiveAuraModifier (AuraType auratype)
int32 GetMaxNegativeAuraModifier (AuraType auratype) const
int32 GetTotalAuraModifierByMiscMask (AuraType auratype, uint32 misc_mask) const
float GetTotalAuraMultiplierByMiscMask (AuraType auratype, uint32 misc_mask) const
int32 GetMaxPositiveAuraModifierByMiscMask (AuraType auratype, uint32 misc_mask, const AuraEffect *except=nullptr) const
int32 GetMaxNegativeAuraModifierByMiscMask (AuraType auratype, uint32 misc_mask) const
int32 GetTotalAuraModifierByMiscValue (AuraType auratype, int32 misc_value) const
float GetTotalAuraMultiplierByMiscValue (AuraType auratype, int32 misc_value) const
int32 GetMaxPositiveAuraModifierByMiscValue (AuraType auratype, int32 misc_value) const
int32 GetMaxNegativeAuraModifierByMiscValue (AuraType auratype, int32 misc_value) const
int32 GetTotalAuraModifierByAffectMask (AuraType auratype, SpellInfo const *affectedSpell) const
float GetTotalAuraMultiplierByAffectMask (AuraType auratype, SpellInfo const *affectedSpell) const
int32 GetMaxPositiveAuraModifierByAffectMask (AuraType auratype, SpellInfo const *affectedSpell) const
int32 GetMaxNegativeAuraModifierByAffectMask (AuraType auratype, SpellInfo const *affectedSpell) const
float GetResistanceBuffMods (SpellSchools school, bool positive) const
void SetResistanceBuffMods (SpellSchools school, bool positive, float val)
void ApplyResistanceBuffModsMod (SpellSchools school, bool positive, float val, bool apply)
void ApplyResistanceBuffModsPercentMod (SpellSchools school, bool positive, float val, bool apply)
void InitStatBuffMods ()
void ApplyStatBuffMod (Stats stat, float val, bool apply)
void ApplyStatPercentBuffMod (Stats stat, float val, bool apply)
void SetCreateStat (Stats stat, float val)
void SetCreateHealth (uint32 val)
uint32 GetCreateHealth () const
void SetCreateMana (uint32 val)
uint32 GetCreateMana () const
uint32 GetCreatePowers (Powers power) const
float GetPosStat (Stats stat) const
float GetNegStat (Stats stat) const
float GetCreateStat (Stats stat) const
void SetCurrentCastedSpell (Spell *pSpell)
void InterruptSpell (CurrentSpellTypes spellType, bool withDelayed=true, bool withInstant=true, bool bySelf=false)
void FinishSpell (CurrentSpellTypes spellType, bool ok=true)
bool IsNonMeleeSpellCast (bool withDelayed, bool skipChanneled=false, bool skipAutorepeat=false, bool isAutoshoot=false, bool skipInstant=true) const
void InterruptNonMeleeSpells (bool withDelayed, uint32 spellid=0, bool withInstant=true, bool bySelf=false)
bool CanMoveDuringChannel () const
Spell * GetCurrentSpell (CurrentSpellTypes spellType) const
Spell * GetCurrentSpell (uint32 spellType) const
Spell * FindCurrentSpellBySpellId (uint32 spell_id) const
int32 GetCurrentSpellCastTime (uint32 spell_id) const
ShapeshiftForm GetShapeshiftForm () const
void SetShapeshiftForm (ShapeshiftForm form)
bool IsInFeralForm () const
bool IsInDisallowedMountForm () const
bool HandleStatModifier (UnitMods unitMod, UnitModifierType modifierType, float amount, bool apply)
void SetModifierValue (UnitMods unitMod, UnitModifierType modifierType, float value)
float GetModifierValue (UnitMods unitMod, UnitModifierType modifierType) const
float GetTotalStatValue (Stats stat, float additionalValue=0.0f) const
float GetTotalAuraModValue (UnitMods unitMod) const
SpellSchools GetSpellSchoolByAuraGroup (UnitMods unitMod) const
Stats GetStatByAuraGroup (UnitMods unitMod) const
Powers GetPowerTypeByAuraGroup (UnitMods unitMod) const
bool CanModifyStats () const
void SetCanModifyStats (bool modifyStats)
virtual void UpdateAllResistances ()
virtual void UpdateDamagePhysical (WeaponAttackType attType)
float GetTotalAttackPowerValue (WeaponAttackType attType, Unit *pVictim=nullptr) const
float GetWeaponDamageRange (WeaponAttackType attType, WeaponDamageRange type) const
void SetBaseWeaponDamage (WeaponAttackType attType, WeaponDamageRange damageRange, float value)
uint32 CalculateDamage (WeaponAttackType attType, bool normalized, bool addTotalPct)
float GetAPMultiplier (WeaponAttackType attType, bool normalized)
bool isInFrontInMap (Unit const *target, float distance, float arc=M_PI) const
bool isInBackInMap (Unit const *target, float distance, float arc=M_PI) const
bool IsVisible () const
void SetVisible (bool x)
void SetModelVisible (bool on)
uint32 GetPhaseByAuras () const
void SetPhaseMask (uint32 newPhaseMask, bool update) override
void UpdateObjectVisibility (bool forced=true, bool fromUpdate=false) override
bool CanHaveThreatList () const
void AddThreat (Unit *victim, float fThreat, SpellSchoolMask schoolMask=SPELL_SCHOOL_MASK_NORMAL, SpellInfo const *threatSpell=nullptr)
float ApplyTotalThreatModifier (float fThreat, SpellSchoolMask schoolMask=SPELL_SCHOOL_MASK_NORMAL)
void DeleteThreatList ()
void TauntApply (Unit *victim)
void TauntFadeOut (Unit *taunter)
ThreatMgr & getThreatMgr ()
void addHatedBy (HostileReference *pHostileReference)
void removeHatedBy (HostileReference *)
HostileRefMgr & getHostileRefMgr ()
VisibleAuraMap const * GetVisibleAuras ()
AuraApplication * GetVisibleAura (uint8 slot)
void SetVisibleAura (uint8 slot, AuraApplication *aur)
void RemoveVisibleAura (uint8 slot)
uint32 GetInterruptMask () const
void AddInterruptMask (uint32 mask)
void UpdateInterruptMask ()
uint32 GetDisplayId ()
uint32 GetNativeDisplayId () const
void RestoreDisplayId ()
void SetNativeDisplayId (uint32 modelId)
void setTransForm (uint32 spellid)
uint32 getTransForm () const
void _RegisterDynObject (DynamicObject *dynObj)
void _UnregisterDynObject (DynamicObject *dynObj)
DynamicObject * GetDynObject (uint32 spellId)
void RemoveDynObject (uint32 spellId)
void RemoveAllDynObjects ()
GameObject * GetGameObject (uint32 spellId) const
void AddGameObject (GameObject *gameObj)
void RemoveGameObject (GameObject *gameObj, bool del)
void RemoveGameObject (uint32 spellid, bool del)
void RemoveAllGameObjects ()
void ModifyAuraState (AuraStateType flag, bool apply)
uint32 BuildAuraStateUpdateForTarget (Unit *target) const
bool HasAuraState (AuraStateType flag, SpellInfo const *spellProto=nullptr, Unit const *Caster=nullptr) const
void UnsummonAllTotems (bool onDeath=false)
Unit * GetMagicHitRedirectTarget (Unit *victim, SpellInfo const *spellInfo)
Unit * GetMeleeHitRedirectTarget (Unit *victim, SpellInfo const *spellInfo=nullptr)
int32 SpellBaseDamageBonusDone (SpellSchoolMask schoolMask)
int32 SpellBaseDamageBonusTaken (SpellSchoolMask schoolMask, bool isDoT=false)
float SpellPctDamageModsDone (Unit *victim, SpellInfo const *spellProto, DamageEffectType damagetype)
uint32 SpellDamageBonusDone (Unit *victim, SpellInfo const *spellProto, uint32 pdamage, DamageEffectType damagetype, float TotalMod=0.0f, uint32 stack=1)
uint32 SpellDamageBonusTaken (Unit *caster, SpellInfo const *spellProto, uint32 pdamage, DamageEffectType damagetype, uint32 stack=1)
int32 SpellBaseHealingBonusDone (SpellSchoolMask schoolMask)
int32 SpellBaseHealingBonusTaken (SpellSchoolMask schoolMask)
float SpellPctHealingModsDone (Unit *victim, SpellInfo const *spellProto, DamageEffectType damagetype)
uint32 SpellHealingBonusDone (Unit *victim, SpellInfo const *spellProto, uint32 healamount, DamageEffectType damagetype, float TotalMod=0.0f, uint32 stack=1)
uint32 SpellHealingBonusTaken (Unit *caster, SpellInfo const *spellProto, uint32 healamount, DamageEffectType damagetype, uint32 stack=1)
uint32 MeleeDamageBonusDone (Unit *pVictim, uint32 damage, WeaponAttackType attType, SpellInfo const *spellProto=nullptr)
uint32 MeleeDamageBonusTaken (Unit *attacker, uint32 pdamage, WeaponAttackType attType, SpellInfo const *spellProto=nullptr)
bool isSpellBlocked (Unit *victim, SpellInfo const *spellProto, WeaponAttackType attackType=BASE_ATTACK)
bool isBlockCritical ()
float SpellDoneCritChance (Unit const *, SpellInfo const *spellProto, SpellSchoolMask schoolMask, WeaponAttackType attackType, bool skipEffectCheck) const
float SpellTakenCritChance (Unit const *caster, SpellInfo const *spellProto, SpellSchoolMask schoolMask, float doneChance, WeaponAttackType attackType, bool skipEffectCheck) const
void SetLastManaUse (uint32 spellCastTime)
bool IsUnderLastManaUseEffect () const
void SetContestedPvP (Player *attackedPlayer=nullptr, bool lookForNearContestedGuards=true)
uint32 GetCastingTimeForBonus (SpellInfo const *spellProto, DamageEffectType damagetype, uint32 CastingTime) const
float CalculateDefaultCoefficient (SpellInfo const *spellInfo, DamageEffectType damagetype) const
void CastDelayedSpellWithPeriodicAmount (Unit *caster, uint32 spellId, AuraType auraType, int32 addAmount, uint8 effectIndex=0)
void ApplySpellImmune (uint32 spellId, uint32 op, uint32 type, bool apply, SpellImmuneBlockType blockType=SPELL_BLOCK_TYPE_ALL)
void ApplySpellDispelImmunity (const SpellInfo *spellProto, DispelType type, bool apply)
bool IsImmunedToDamage (SpellSchoolMask meleeSchoolMask) const
bool IsImmunedToDamage (SpellInfo const *spellInfo) const
bool IsImmunedToSchool (SpellSchoolMask meleeSchoolMask) const
bool IsImmunedToSchool (SpellInfo const *spellInfo) const
bool IsImmunedToDamageOrSchool (SpellSchoolMask meleeSchoolMask) const
bool IsImmunedToDamageOrSchool (SpellInfo const *spellInfo) const
void UpdateSpeed (UnitMoveType mtype, bool forced)
float GetSpeed (UnitMoveType mtype) const
float GetSpeedRate (UnitMoveType mtype) const
void SetSpeed (UnitMoveType mtype, float rate, bool forced=false)
void SetSpeedRate (UnitMoveType mtype, float rate)
float ApplyEffectModifiers (SpellInfo const *spellProto, uint8 effect_index, float value) const
int32 CalculateSpellDamage (Unit const *target, SpellInfo const *spellProto, uint8 effect_index, int32 const *basePoints=nullptr) const
int32 CalcSpellDuration (SpellInfo const *spellProto)
int32 ModSpellDuration (SpellInfo const *spellProto, Unit const *target, int32 duration, bool positive, uint32 effectMask)
void ModSpellCastTime (SpellInfo const *spellProto, int32 &castTime, Spell *spell=nullptr)
float CalculateLevelPenalty (SpellInfo const *spellProto) const
void addFollower (FollowerReference *pRef)
void removeFollower (FollowerReference *)
MotionMaster * GetMotionMaster ()
const MotionMaster * GetMotionMaster () const
bool IsStopped () const
void StopMoving ()
-------—End of Pet responses methods-------—
void StopMovingOnCurrentPos ()
void AddUnitMovementFlag (uint32 f)
void RemoveUnitMovementFlag (uint32 f)
bool HasUnitMovementFlag (uint32 f) const
uint32 GetUnitMovementFlags () const
void SetUnitMovementFlags (uint32 f)
void AddExtraUnitMovementFlag (uint16 f)
void RemoveExtraUnitMovementFlag (uint16 f)
uint16 HasExtraUnitMovementFlag (uint16 f) const
uint16 GetExtraUnitMovementFlags () const
void SetExtraUnitMovementFlags (uint16 f)
void SetControlled (bool apply, UnitState state)
void DisableRotate (bool apply)
void DisableSpline ()
void AddComboPointHolder (ObjectGuid lowguid)
void RemoveComboPointHolder (ObjectGuid lowguid)
void ClearComboPointHolders ()
void SendPetActionFeedback (uint8 msg)
-------—Pet responses methods--------------—
void SendPetTalk (uint32 pettalk)
void SendPetAIReaction (ObjectGuid guid)
void propagateSpeedChange ()
-------—End of Pet responses methods-------—
void ClearAllReactives ()
void StartReactiveTimer (ReactiveType reactive)
void UpdateReactives (uint32 p_time)
void UpdateAuraForGroup (uint8 slot)
bool CanProc ()
void SetCantProc (bool apply)
void AddPetAura (PetAura const *petSpell)
void RemovePetAura (PetAura const *petSpell)
void CastPetAura (PetAura const *aura)
bool IsPetAura (Aura const *aura)
uint32 GetModelForForm (ShapeshiftForm form) const
uint32 GetModelForTotem (PlayerTotemType totemType)
void SetRedirectThreat (ObjectGuid guid, uint32 pct)
void ResetRedirectThreat ()
void ModifyRedirectThreat (int32 amount)
uint32 GetRedirectThreatPercent ()
Unit * GetRedirectThreatTarget () const
bool CreateVehicleKit (uint32 id, uint32 creatureEntry)
void RemoveVehicleKit ()
Vehicle * GetVehicleKit () const
Vehicle * GetVehicle () const
bool IsOnVehicle (const Unit *vehicle) const
Unit * GetVehicleBase () const
Creature * GetVehicleCreatureBase () const
ObjectGuid GetTransGUID () const override
TransportBase * GetDirectTransport () const
Returns the transport this unit is on directly (if on vehicle and transport, return vehicle)
bool HandleSpellClick (Unit *clicker, int8 seatId=-1)
void EnterVehicle (Unit *base, int8 seatId=-1)
void EnterVehicleUnattackable (Unit *base, int8 seatId=-1)
void ExitVehicle (Position const *exitPosition=nullptr)
void ChangeSeat (int8 seatId, bool next=true)
void _ExitVehicle (Position const *exitPosition=nullptr)
void _EnterVehicle (Vehicle *vehicle, int8 seatId, AuraApplication const *aurApp=nullptr)
void BuildMovementPacket (ByteBuffer *data) const
bool IsLevitating () const
bool IsWalking () const
bool isMoving () const
bool isTurning () const
bool IsHovering () const
bool isSwimming () const
bool IsFlying () const
bool IsFalling () const
float GetHoverHeight () const
void RewardRage (uint32 damage, uint32 weaponSpeedHitFactor, bool attacker)
virtual float GetFollowAngle () const
void OutDebugInfo () const
virtual bool isBeingLoaded () const
bool IsDuringRemoveFromWorld () const
Pet * ToPet ()
Totem * ToTotem ()
TempSummon * ToTempSummon ()
const TempSummon * ToTempSummon () const
void AddPointedBy (SafeUnitPointer *sup)
void RemovePointedBy (SafeUnitPointer *sup)
void ExecuteDelayedUnitRelocationEvent ()
void ExecuteDelayedUnitAINotifyEvent ()
virtual bool HasSpellItemCooldown (uint32, uint32) const
bool CanApplyResilience () const
void PetSpellFail (const SpellInfo *spellInfo, Unit *target, uint32 result)
int32 CalculateAOEDamageReduction (int32 damage, uint32 schoolMask, Unit *caster) const
ObjectGuid GetTarget () const
void SetInstantCast (bool set)
bool CanInstantCast () const
virtual void Talk (std::string_view text, ChatMsg msgType, Language language, float textRange, WorldObject const *target)
virtual void Say (std::string_view text, Language language, WorldObject const *target=nullptr)
virtual void Yell (std::string_view text, Language language, WorldObject const *target=nullptr)
virtual void TextEmote (std::string_view text, WorldObject const *target=nullptr, bool isBossEmote=false)
virtual void Whisper (std::string_view text, Language language, Player *target, bool isBossWhisper=false)
virtual void Talk (uint32 textId, ChatMsg msgType, float textRange, WorldObject const *target)
virtual void Say (uint32 textId, WorldObject const *target=nullptr)
virtual void Yell (uint32 textId, WorldObject const *target=nullptr)
virtual void TextEmote (uint32 textId, WorldObject const *target=nullptr, bool isBossEmote=false)
virtual void Whisper (uint32 textId, Player *target, bool isBossWhisper=false)
float GetCollisionHeight () const override
Return collision height sent to client.
float GetCollisionWidth () const override
this method gets the diameter of a Unit by DB if any value is defined, otherwise it gets the value by the DBC
float GetCollisionRadius () const override
this method gets the radius of a Unit by DB if any value is defined, otherwise it gets the value by the DBC
void ProcessPositionDataChanged (PositionFullTerrainStatus const &data) override
virtual void ProcessTerrainStatusUpdate ()
Public Member Functions inherited from WorldObject
~WorldObject () override
void _Create (ObjectGuid::LowType guidlow, HighGuid guidhigh, uint32 phaseMask)
void GetNearPoint2D (WorldObject const *searcher, float &x, float &y, float distance, float absAngle, Position const *startPos=nullptr) const
void GetNearPoint2D (float &x, float &y, float distance, float absAngle, Position const *startPos=nullptr) const
void GetNearPoint (WorldObject const *searcher, float &x, float &y, float &z, float searcher_size, float distance2d, float absAngle, float controlZ=0, Position const *startPos=nullptr) const
void GetVoidClosePoint (float &x, float &y, float &z, float size, float distance2d=0, float relAngle=0, float controlZ=0) const
bool GetClosePoint (float &x, float &y, float &z, float size, float distance2d=0, float angle=0, const WorldObject *forWho=nullptr, bool force=false) const
void MovePosition (Position &pos, float dist, float angle)
Position GetNearPosition (float dist, float angle)
void MovePositionToFirstCollision (Position &pos, float dist, float angle)
Position GetFirstCollisionPosition (float startX, float startY, float startZ, float destX, float destY)
Position GetFirstCollisionPosition (float destX, float destY, float destZ)
Position GetFirstCollisionPosition (float dist, float angle)
Position GetRandomNearPosition (float radius)
void GetContactPoint (const WorldObject *obj, float &x, float &y, float &z, float distance2d=CONTACT_DISTANCE) const
void GetChargeContactPoint (const WorldObject *obj, float &x, float &y, float &z, float distance2d=CONTACT_DISTANCE) const
float GetObjectSize () const
void UpdateGroundPositionZ (float x, float y, float &z) const
void UpdateAllowedPositionZ (float x, float y, float &z, float *groundZ=nullptr) const
void GetRandomPoint (const Position &srcPos, float distance, float &rand_x, float &rand_y, float &rand_z) const
Position GetRandomPoint (const Position &srcPos, float distance) const
uint32 GetInstanceId () const
uint32 GetPhaseMask () const
bool InSamePhase (WorldObject const *obj) const
bool InSamePhase (uint32 phasemask) const
uint32 GetZoneId () const
uint32 GetAreaId () const
void GetZoneAndAreaId (uint32 &zoneid, uint32 &areaid) const
bool IsOutdoors () const
LiquidData const & GetLiquidData () const
InstanceScript * GetInstanceScript () const
std::string const & GetName () const
void SetName (std::string const &newname)
float GetDistance (const WorldObject *obj) const
float GetDistance (const Position &pos) const
float GetDistance (float x, float y, float z) const
float GetDistance2d (const WorldObject *obj) const
float GetDistance2d (float x, float y) const
float GetDistanceZ (const WorldObject *obj) const
bool IsSelfOrInSameMap (const WorldObject *obj) const
bool IsInMap (const WorldObject *obj) const
bool IsWithinDist3d (float x, float y, float z, float dist) const
bool IsWithinDist3d (const Position *pos, float dist) const
bool IsWithinDist2d (float x, float y, float dist) const
bool IsWithinDist2d (const Position *pos, float dist) const
bool IsWithinDist (WorldObject const *obj, float dist2compare, bool is3D=true, bool useBoundingRadius=true) const
bool IsWithinDistInMap (WorldObject const *obj, float dist2compare, bool is3D=true, bool useBoundingRadius=true) const
bool IsWithinLOS (float x, float y, float z, LineOfSightChecks checks=LINEOFSIGHT_ALL_CHECKS) const
bool IsWithinLOSInMap (WorldObject const *obj, LineOfSightChecks checks=LINEOFSIGHT_ALL_CHECKS) const
Position GetHitSpherePointFor (Position const &dest) const
void GetHitSpherePointFor (Position const &dest, float &x, float &y, float &z) const
bool GetDistanceOrder (WorldObject const *obj1, WorldObject const *obj2, bool is3D=true) const
bool IsInRange (WorldObject const *obj, float minRange, float maxRange, bool is3D=true) const
bool IsInRange2d (float x, float y, float minRange, float maxRange) const
bool IsInRange3d (float x, float y, float z, float minRange, float maxRange) const
bool isInFront (WorldObject const *target, float arc=M_PI) const
bool isInBack (WorldObject const *target, float arc=M_PI) const
bool IsInBetween (const WorldObject *obj1, const WorldObject *obj2, float size=0) const
virtual void SendMessageToSet (WorldPacket *data, bool self)
virtual void SendMessageToSetInRange (WorldPacket *data, float dist, bool, bool includeMargin=false, Player const *skipped_rcvr=nullptr)
virtual void SendMessageToSet (WorldPacket *data, Player const *skipped_rcvr)
void PlayDistanceSound (uint32 sound_id, Player *target=nullptr)
void PlayDirectSound (uint32 sound_id, Player *target=nullptr)
void PlayDirectMusic (uint32 music_id, Player *target=nullptr)
void SendObjectDeSpawnAnim (ObjectGuid guid)
void AddObjectToRemoveList ()
float GetGridActivationRange () const
float GetVisibilityRange () const
virtual float GetSightRange (const WorldObject *target=nullptr) const
bool CanSeeOrDetect (WorldObject const *obj, bool ignoreStealth=false, bool distanceCheck=false, bool checkAlert=false) const
void SendPlayMusic (uint32 Music, bool OnlySelf)
virtual void SetMap (Map *map)
virtual void ResetMap ()
Map * GetMap () const
Map * FindMap () const
void SetZoneScript ()
void ClearZoneScript ()
ZoneScript * GetZoneScript () const
TempSummon * SummonCreature (uint32 id, const Position &pos, TempSummonType spwtype=TEMPSUMMON_MANUAL_DESPAWN, uint32 despwtime=0, uint32 vehId=0, SummonPropertiesEntry const *properties=nullptr) const
TempSummon * SummonCreature (uint32 id, float x, float y, float z, float ang=0, TempSummonType spwtype=TEMPSUMMON_MANUAL_DESPAWN, uint32 despwtime=0, SummonPropertiesEntry const *properties=nullptr)
GameObject * SummonGameObject (uint32 entry, float x, float y, float z, float ang, float rotation0, float rotation1, float rotation2, float rotation3, uint32 respawnTime, bool checkTransport=true)
Creature * SummonTrigger (float x, float y, float z, float ang, uint32 dur, bool setLevel=false, CreatureAI *(*GetAI)(Creature *)=nullptr)
void SummonCreatureGroup (uint8 group, std::list< TempSummon * > *list=nullptr)
Creature * FindNearestCreature (uint32 entry, float range, bool alive=true) const
GameObject * FindNearestGameObject (uint32 entry, float range, bool onlySpawned=false) const
GameObject * FindNearestGameObjectOfType (GameobjectTypes type, float range) const
Player * SelectNearestPlayer (float distance=0) const
void GetGameObjectListWithEntryInGrid (std::list< GameObject * > &lList, uint32 uiEntry, float fMaxSearchRange) const
void GetCreatureListWithEntryInGrid (std::list< Creature * > &lList, uint32 uiEntry, float fMaxSearchRange) const
void GetDeadCreatureListInGrid (std::list< Creature * > &lList, float maxSearchRange, bool alive=false) const
void DestroyForNearbyPlayers ()
void BuildUpdate (UpdateDataMapType &data_map, UpdatePlayerSet &player_set) override
void GetCreaturesWithEntryInRange (std::list< Creature * > &creatureList, float radius, uint32 entry)
void SetPositionDataUpdate ()
void UpdatePositionData ()
void AddToObjectUpdate () override
void RemoveFromObjectUpdate () override
void AddToNotify (uint16 f)
void RemoveFromNotify (uint16 f)
bool isNeedNotify (uint16 f) const
uint16 GetNotifyFlags () const
bool NotifyExecuted (uint16 f) const
void SetNotified (uint16 f)
void ResetAllNotifies ()
bool isActiveObject () const
void setActive (bool isActiveObject)
bool IsVisibilityOverridden () const
void SetVisibilityDistanceOverride (bool isVisibilityDistanceOverride)
void SetWorldObject (bool apply)
bool IsPermanentWorldObject () const
bool IsWorldObject () const
bool IsInWintergrasp () const
Transport * GetTransport () const
float GetTransOffsetX () const
float GetTransOffsetY () const
float GetTransOffsetZ () const
float GetTransOffsetO () const
uint32 GetTransTime () const
int8 GetTransSeat () const
void SetTransport (Transport *t)
virtual float GetStationaryX () const
virtual float GetStationaryY () const
virtual float GetStationaryZ () const
virtual float GetStationaryO () const
float GetMapWaterOrGroundLevel (float x, float y, float z, float *ground=nullptr) const
float GetMapHeight (float x, float y, float z, bool vmap=true, float distanceToSearch=50.0f) const
float GetFloorZ () const
float GetMinHeightInWater () const
Get the minimum height of a object that should be in water to start floating/swim.
void AddAllowedLooter (ObjectGuid guid)
void ResetAllowedLooters ()
void SetAllowedLooters (GuidUnorderedSet const looters)
bool HasAllowedLooter (ObjectGuid guid) const
GuidUnorderedSet const & GetAllowedLooters () const
Public Member Functions inherited from Object
virtual ~Object ()
bool IsInWorld () const
ObjectGuid GetGUID () const
PackedGuid const & GetPackGUID () const
uint32 GetEntry () const
void SetEntry (uint32 entry)
float GetObjectScale () const
TypeID GetTypeId () const
bool isType (uint16 mask) const
virtual void BuildCreateUpdateBlockForPlayer (UpdateData *data, Player *target) const
void SendUpdateToPlayer (Player *player)
void BuildValuesUpdateBlockForPlayer (UpdateData *data, Player *target) const
void BuildOutOfRangeUpdateBlock (UpdateData *data) const
void BuildMovementUpdateBlock (UpdateData *data, uint32 flags=0) const
virtual void DestroyForPlayer (Player *target, bool onDeath=false) const
int32 GetInt32Value (uint16 index) const
uint32 GetUInt32Value (uint16 index) const
uint64 GetUInt64Value (uint16 index) const
float GetFloatValue (uint16 index) const
uint8 GetByteValue (uint16 index, uint8 offset) const
uint16 GetUInt16Value (uint16 index, uint8 offset) const
ObjectGuid GetGuidValue (uint16 index) const
void SetInt32Value (uint16 index, int32 value)
void SetUInt32Value (uint16 index, uint32 value)
void UpdateUInt32Value (uint16 index, uint32 value)
void SetUInt64Value (uint16 index, uint64 value)
void SetFloatValue (uint16 index, float value)
void SetByteValue (uint16 index, uint8 offset, uint8 value)
void SetUInt16Value (uint16 index, uint8 offset, uint16 value)
void SetInt16Value (uint16 index, uint8 offset, int16 value)
void SetGuidValue (uint16 index, ObjectGuid value)
void SetStatFloatValue (uint16 index, float value)
void SetStatInt32Value (uint16 index, int32 value)
bool AddGuidValue (uint16 index, ObjectGuid value)
bool RemoveGuidValue (uint16 index, ObjectGuid value)
void ApplyModUInt32Value (uint16 index, int32 val, bool apply)
void ApplyModInt32Value (uint16 index, int32 val, bool apply)
void ApplyModUInt64Value (uint16 index, int32 val, bool apply)
void ApplyModPositiveFloatValue (uint16 index, float val, bool apply)
void ApplyModSignedFloatValue (uint16 index, float val, bool apply)
void ApplyPercentModFloatValue (uint16 index, float val, bool apply)
void SetFlag (uint16 index, uint32 newFlag)
void RemoveFlag (uint16 index, uint32 oldFlag)
void ToggleFlag (uint16 index, uint32 flag)
bool HasFlag (uint16 index, uint32 flag) const
void ApplyModFlag (uint16 index, uint32 flag, bool apply)
void SetByteFlag (uint16 index, uint8 offset, uint8 newFlag)
void RemoveByteFlag (uint16 index, uint8 offset, uint8 newFlag)
bool HasByteFlag (uint16 index, uint8 offset, uint8 flag) const
void SetFlag64 (uint16 index, uint64 newFlag)
void RemoveFlag64 (uint16 index, uint64 oldFlag)
void ToggleFlag64 (uint16 index, uint64 flag)
bool HasFlag64 (uint16 index, uint64 flag) const
void ApplyModFlag64 (uint16 index, uint64 flag, bool apply)
void ClearUpdateMask (bool remove)
uint16 GetValuesCount () const
void BuildFieldsUpdate (Player *, UpdateDataMapType &) const
void SetFieldNotifyFlag (uint16 flag)
void RemoveFieldNotifyFlag (uint16 flag)
void ForceValuesUpdateAtIndex (uint32)
bool IsPlayer () const
Player * ToPlayer ()
Player const * ToPlayer () const
Creature * ToCreature ()
Creature const * ToCreature () const
Unit * ToUnit ()
Unit const * ToUnit () const
GameObject * ToGameObject ()
GameObject const * ToGameObject () const
Corpse * ToCorpse ()
Corpse const * ToCorpse () const
DynamicObject * ToDynObject ()
DynamicObject const * ToDynObject () const
Public Member Functions inherited from WorldLocation
WorldLocation (uint32 _mapId=MAPID_INVALID, float x=0.f, float y=0.f, float z=0.f, float o=0.f)
WorldLocation (uint32 mapId, Position const &position)
void WorldRelocate (const WorldLocation &loc)
void WorldRelocate (uint32 mapId=MAPID_INVALID, float x=0.f, float y=0.f, float z=0.f, float o=0.f)
void SetMapId (uint32 mapId)
uint32 GetMapId () const
void GetWorldLocation (uint32 &mapId, float &x, float &y) const
void GetWorldLocation (uint32 &mapId, float &x, float &y, float &z) const
void GetWorldLocation (uint32 &mapId, float &x, float &y, float &z, float &o) const
void GetWorldLocation (WorldLocation *location) const
WorldLocation GetWorldLocation () const
Public Member Functions inherited from Position
Position (float x=0, float y=0, float z=0, float o=0)
Position (Position const &loc)
bool operator== (Position const &a) const
bool operator!= (Position const &a)
operator G3D::Vector3 () const
void Relocate (float x, float y)
void Relocate (float x, float y, float z)
void Relocate (float x, float y, float z, float orientation)
void Relocate (const Position &pos)
void Relocate (const Position *pos)
void RelocatePolarOffset (float angle, float dist, float z=0.0f)
void RelocateOffset (const Position &offset)
void SetOrientation (float orientation)
float GetPositionX () const
float GetPositionY () const
float GetPositionZ () const
float GetOrientation () const
void GetPosition (float &x, float &y) const
void GetPosition (float &x, float &y, float &z) const
void GetPosition (float &x, float &y, float &z, float &o) const
Position GetPosition () const
Position::PositionXYZStreamer PositionXYZStream ()
Position::PositionXYZOStreamer PositionXYZOStream ()
bool IsPositionValid () const
float GetExactDist2dSq (const float x, const float y) const
float GetExactDist2dSq (Position const &pos) const
float GetExactDist2dSq (Position const *pos) const
float GetExactDist2d (const float x, const float y) const
float GetExactDist2d (Position const &pos) const
float GetExactDist2d (Position const *pos) const
float GetExactDistSq (float x, float y, float z) const
float GetExactDistSq (Position const &pos) const
float GetExactDistSq (Position const *pos) const
float GetExactDist (float x, float y, float z) const
float GetExactDist (Position const &pos) const
float GetExactDist (Position const *pos) const
void GetPositionOffsetTo (const Position &endPos, Position &retOffset) const
Position GetPositionWithOffset (Position const &offset) const
float GetAngle (const Position *pos) const
float GetAngle (float x, float y) const
float GetAbsoluteAngle (float x, float y) const
float GetAbsoluteAngle (Position const &pos) const
float GetAbsoluteAngle (Position const *pos) const
float GetRelativeAngle (const Position *pos) const
float GetRelativeAngle (float x, float y) const
float ToAbsoluteAngle (float relAngle) const
void GetSinCos (float x, float y, float &vsin, float &vcos) const
bool IsInDist2d (float x, float y, float dist) const
bool IsInDist2d (const Position *pos, float dist) const
bool IsInDist (float x, float y, float z, float dist) const
bool IsInDist (const Position *pos, float dist) const
bool IsWithinBox (const Position &center, float xradius, float yradius, float zradius) const
bool HasInArc (float arcangle, const Position *pos, float targetRadius=0.0f) const
bool HasInLine (WorldObject const *target, float width) const
std::string ToString () const
Public Member Functions inherited from GridObject< Creature >
bool IsInGrid () const
void AddToGrid (GridRefMgr< Creature > &m)
void RemoveFromGrid ()
Static Public Member Functions
static float _GetDamageMod (int32 Rank)
Static Public Member Functions inherited from Unit
static float GetEffectiveResistChance (Unit const *owner, SpellSchoolMask schoolMask, Unit const *victim, SpellInfo const *spellInfo=nullptr)
static void DealDamageMods (Unit const *victim, uint32 &damage, uint32 *absorb)
static uint32 DealDamage (Unit *attacker, Unit *victim, uint32 damage, CleanDamage const *cleanDamage=nullptr, DamageEffectType damagetype=DIRECT_DAMAGE, SpellSchoolMask damageSchoolMask=SPELL_SCHOOL_MASK_NORMAL, SpellInfo const *spellProto=nullptr, bool durabilityLoss=true, bool allowGM=false)
static void Kill (Unit *killer, Unit *victim, bool durabilityLoss=true, WeaponAttackType attackType=BASE_ATTACK, SpellInfo const *spellProto=nullptr)
static int32 DealHeal (Unit *healer, Unit *victim, uint32 addhealth)
static void ApplyResilience (const Unit *victim, float *crit, int32 *damage, bool isCrit, CombatRating type)
static uint32 SpellCriticalDamageBonus (Unit const *caster, SpellInfo const *spellProto, uint32 damage, Unit const *victim)
static uint32 SpellCriticalHealingBonus (Unit const *caster, SpellInfo const *spellProto, uint32 damage, Unit const *victim)
static bool IsDamageReducedByArmor (SpellSchoolMask damageSchoolMask, SpellInfo const *spellInfo=nullptr, uint8 effIndex=MAX_SPELL_EFFECTS)
static uint32 CalcArmorReducedDamage (Unit const *attacker, Unit const *victim, const uint32 damage, SpellInfo const *spellInfo, uint8 attackerLevel=0, WeaponAttackType attackType=MAX_ATTACK)
static void CalcAbsorbResist (DamageInfo &dmgInfo, bool Splited=false)
static void CalcHealAbsorb (HealInfo &healInfo)
static void HandleSafeUnitPointersOnDelete (Unit *thisUnit)
Static Public Member Functions inherited from Object
static ObjectGuid GetGUID (Object const *o)
Static Public Member Functions inherited from Position
static float NormalizeOrientation (float o)
Public Attributes
struct {
::Spell const * Spell = nullptr
uint32 Delay = 0
ObjectGuid Target
float Orientation = 0.0f
} _spellFocusInfo
Loot loot
uint32 m_spells [MAX_CREATURE_SPELLS]
CreatureSpellCooldowns m_CreatureSpellCooldowns
uint32 m_ProhibitSchoolTime [7]
uint32 m_groupLootTimer
uint32 lootingGroupLowGUID
uint32 m_PlayerDamageReq
float m_SightDistance
float m_CombatDistance
bool m_isTempWorldObject
uint32 m_moveCircleMovementTime = MOVE_CIRCLE_CHECK_INTERVAL
uint32 m_moveBackwardsMovementTime = MOVE_BACKWARDS_CHECK_INTERVAL
Public Attributes inherited from Unit
uint32 m_extraAttacks
bool m_canDualWield
ControlSet m_Controlled
SafeUnitPointer m_movedByPlayer
ObjectGuid m_SummonSlot [MAX_SUMMON_SLOT]
ObjectGuid m_ObjectSlot [MAX_GAMEOBJECT_SLOT]
float m_modMeleeHitChance
float m_modRangedHitChance
float m_modSpellHitChance
int32 m_baseSpellCritChance
float m_threatModifier [MAX_SPELL_SCHOOL]
float m_modAttackSpeedPct [3]
EventProcessor m_Events
SpellImmuneList m_spellImmune [MAX_SPELL_IMMUNITY]
uint32 m_lastSanctuaryTime
PetAuraSet m_petAuras
bool IsAIEnabled
bool NeedChangeAI
bool m_ControlledByPlayer
bool m_CreatedByPlayer
std::set< SafeUnitPointer * > SafeUnitPointerSet
Position m_last_notify_position
uint32 m_last_notify_mstime
uint16 m_delayed_unit_relocation_timer
uint16 m_delayed_unit_ai_notify_timer
bool bRequestForcedVisibilityUpdate
Movement::MoveSpline * movespline
Public Attributes inherited from WorldObject
FlaggedValuesArray32< int32, uint32, StealthType, TOTAL_STEALTH_TYPES > m_stealth
FlaggedValuesArray32< int32, uint32, StealthType, TOTAL_STEALTH_TYPES > m_stealthDetect
FlaggedValuesArray32< int32, uint32, InvisibilityType, TOTAL_INVISIBILITY_TYPES > m_invisibility
FlaggedValuesArray32< int32, uint32, InvisibilityType, TOTAL_INVISIBILITY_TYPES > m_invisibilityDetect
FlaggedValuesArray32< int32, uint32, ServerSideVisibilityType, TOTAL_SERVERSIDE_VISIBILITY_TYPES > m_serverSideVisibility
FlaggedValuesArray32< int32, uint32, ServerSideVisibilityType, TOTAL_SERVERSIDE_VISIBILITY_TYPES > m_serverSideVisibilityDetect
uint32 LastUsedScriptID
MovementInfo m_movementInfo
Public Attributes inherited from Object
DataMap CustomData
Public Attributes inherited from WorldLocation
uint32 m_mapId
Public Attributes inherited from Position
float m_positionX = 0
float m_positionY = 0
float m_positionZ = 0
float m_orientation = 0
Static Public Attributes
static constexpr uint32 MOVE_CIRCLE_CHECK_INTERVAL = 3000
static constexpr uint32 MOVE_BACKWARDS_CHECK_INTERVAL = 2000
Protected Member Functions
bool CreateFromProto (ObjectGuid::LowType guidlow, uint32 Entry, uint32 vehId, const CreatureData *data=nullptr)
bool InitEntry (uint32 entry, const CreatureData *data=nullptr)
void RegenerateHealth ()
void Regenerate (Powers power)
bool IsInvisibleDueToDespawn () const override
bool CanAlwaysSee (WorldObject const *obj) const override
Protected Member Functions inherited from Unit
Unit (bool isWorldObject)
void BuildValuesUpdate (uint8 updatetype, ByteBuffer *data, Player *target) const override
void _UpdateSpells (uint32 time)
void _DeleteRemovedAuras ()
void _UpdateAutoRepeatSpell ()
bool IsAlwaysVisibleFor (WorldObject const *seer) const override
bool IsAlwaysDetectableFor (WorldObject const *seer) const override
Protected Member Functions inherited from WorldObject
WorldObject (bool isWorldObject)
void SetLocationMapId (uint32 _mapId)
void SetLocationInstanceId (uint32 _instanceId)
virtual bool IsNeverVisible () const
Protected Member Functions inherited from Object
Object ()
void _InitValues ()
void _Create (ObjectGuid::LowType guidlow, uint32 entry, HighGuid guidhigh)
std::string _ConcatFields (uint16 startIndex, uint16 size) const
void _LoadIntoDataField (std::string const &data, uint32 startOffset, uint32 count)
uint32 GetUpdateFieldData (Player const *target, uint32 *&flags) const
void BuildMovementUpdate (ByteBuffer *data, uint16 flags) const
void AddToObjectUpdateIfNeeded ()
Protected Member Functions inherited from MovableMapObject
MovableMapObject ()
Static Protected Member Functions
static float _GetHealthMod (int32 Rank)
Protected Attributes
VendorItemCounts m_vendorItemCounts
ObjectGuid m_lootRecipient
ObjectGuid::LowType m_lootRecipientGroup
time_t m_corpseRemoveTime
Timers.
time_t m_respawnTime
time_t m_respawnedTime
uint32 m_respawnDelay
uint32 m_corpseDelay
float m_wanderDistance
uint16 m_transportCheckTimer
uint32 lootPickPocketRestoreTime
ReactStates m_reactState
MovementGeneratorType m_defaultMovementType
ObjectGuid::LowType m_spawnId
For new or temporary creatures is 0 for saved it is lowguid.
uint8 m_equipmentId
int8 m_originalEquipmentId
uint8 m_originalAnimTier
bool m_AlreadyCallAssistance
bool m_AlreadySearchedAssistance
bool m_regenHealth
bool m_AI_locked
SpellSchoolMask m_meleeDamageSchoolMask
uint32 m_originalEntry
bool m_moveInLineOfSightDisabled
bool m_moveInLineOfSightStrictlyDisabled
Position m_homePosition
Position m_transportHomePosition
bool DisableReputationGain
CreatureTemplate const * m_creatureInfo
CreatureData const * m_creatureData
float m_detectionDistance
uint16 m_LootMode
Protected Attributes inherited from Unit
UnitAI * i_AI
UnitAI * i_disabledAI
uint8 m_realRace
uint8 m_race
bool m_AutoRepeatFirstCast
int32 m_attackTimer [MAX_ATTACK]
float m_createStats [MAX_STATS]
AttackerSet m_attackers
Unit * m_attacking
DeathState m_deathState
int32 m_procDeep
DynObjectList m_dynObj
GameObjectList m_gameObj
uint32 m_transform
Spell * m_currentSpells [CURRENT_MAX_SPELL]
AuraMap m_ownedAuras
AuraApplicationMap m_appliedAuras
AuraList m_removedAuras
AuraMap::iterator m_auraUpdateIterator
uint32 m_removedAurasCount
AuraEffectList m_modAuras [TOTAL_AURAS]
AuraList m_scAuras
AuraApplicationList m_interruptableAuras
AuraStateAurasMap m_auraStateAuras
uint32 m_interruptMask
float m_auraModifiersGroup [UNIT_MOD_END][MODIFIER_TYPE_END]
float m_weaponDamage [MAX_ATTACK][2]
bool m_canModifyStats
VisibleAuraMap m_visibleAuras
float m_speed_rate [MAX_MOVE_TYPE]
CharmInfo * m_charmInfo
SharedVisionList m_sharedVision
MotionMaster * i_motionMaster
uint32 m_reactiveTimer [MAX_REACTIVE]
int32 m_regenTimer
ThreatMgr m_ThreatMgr
CharmThreatMap _charmThreatInfo
Vehicle * m_vehicle
Vehicle * m_vehicleKit
uint32 m_unitTypeMask
LiquidTypeEntry const * _lastLiquid
bool m_applyResilience
bool _instantCast
Protected Attributes inherited from WorldObject
std::string m_name
bool m_isActive
bool m_isVisibilityDistanceOverride
const bool m_isWorldObject
ZoneScript * m_zoneScript
uint32 _zoneId
uint32 _areaId
float _floorZ
bool _outdoors
LiquidData _liquidData
bool _updatePositionData
Transport * m_transport
Protected Attributes inherited from Object
uint16 m_objectType
TypeID m_objectTypeId
uint16 m_updateFlag
union {
int32 * m_int32Values
uint32 * m_uint32Values
float * m_floatValues
};
UpdateMask _changesMask
uint16 m_valuesCount
uint16 _fieldNotifyFlags
bool m_objectUpdated
Private Member Functions
void ForcedDespawn (uint32 timeMSToDespawn=0, Seconds forcedRespawnTimer=0s)
bool CanPeriodicallyCallForAssistance () const
void applyInhabitFlags ()
Private Attributes
uint32 m_waypointID
uint32 m_path_id
CreatureGroup * m_formation
bool TriggerJustRespawned
std::shared_ptr< time_t > _lastDamagedTime
bool m_cannotReachTarget
uint32 m_cannotReachTimer
Spell const * _focusSpell
bool _isMissingSwimmingFlagOutOfCombat
Locks the target during spell cast for proper facing
uint32 m_assistanceTimer
Additional Inherited Members
Public Types inherited from Unit
typedef std::unordered_set< Unit * > AttackerSet
typedef std::set< Unit * > ControlSet
typedef std::multimap< uint32, Aura * > AuraMap
typedef std::pair< AuraMap::const_iterator, AuraMap::const_iterator > AuraMapBounds
typedef std::pair< AuraMap::iterator, AuraMap::iterator > AuraMapBoundsNonConst
typedef std::multimap< uint32, AuraApplication * > AuraApplicationMap
typedef std::pair< AuraApplicationMap::const_iterator, AuraApplicationMap::const_iterator > AuraApplicationMapBounds
typedef std::pair< AuraApplicationMap::iterator, AuraApplicationMap::iterator > AuraApplicationMapBoundsNonConst
typedef std::multimap< AuraStateType, AuraApplication * > AuraStateAurasMap
typedef std::pair< AuraStateAurasMap::const_iterator, AuraStateAurasMap::const_iterator > AuraStateAurasMapBounds
typedef std::list< AuraEffect * > AuraEffectList
typedef std::list< Aura * > AuraList
typedef std::list< AuraApplication * > AuraApplicationList
typedef std::list< DiminishingReturn > Diminishing
typedef GuidUnorderedSet ComboPointHolderSet
typedef std::map< uint8, AuraApplication * > VisibleAuraMap
typedef std::set< PetAura const * > PetAuraSet
Protected Types inherited from Unit
typedef std::list< DynamicObject * > DynObjectList
typedef GuidList GameObjectList
typedef std::map< ObjectGuid, float > CharmThreatMap
Detailed Description
Definition at line 45 of file Creature.h.
Constructor & Destructor Documentation
Creature()
Creature::Creature (bool isWorldObject = false) explicit
Definition at line 177 of file Creature.cpp.
                                     : Unit(isWorldObject), MovableMapObject(), m_groupLootTimer(0), lootingGroupLowGUID(0), m_PlayerDamageReq(0), m_lootRecipientGroup(0),
     m_corpseRemoveTime(0), m_respawnTime(0), m_respawnDelay(300), m_corpseDelay(60), m_wanderDistance(0.0f),
     m_transportCheckTimer(1000), lootPickPocketRestoreTime(0),  m_reactState(REACT_AGGRESSIVE), m_defaultMovementType(IDLE_MOTION_TYPE),
     m_spawnId(0), m_equipmentId(0), m_originalEquipmentId(0), m_originalAnimTier(UNIT_BYTE1_FLAG_GROUND), m_AlreadyCallAssistance(false),
     m_AlreadySearchedAssistance(false), m_regenHealth(true), m_AI_locked(false), m_meleeDamageSchoolMask(SPELL_SCHOOL_MASK_NORMAL), m_originalEntry(0), m_moveInLineOfSightDisabled(false), m_moveInLineOfSightStrictlyDisabled(false),
     m_homePosition(), m_transportHomePosition(), m_creatureInfo(nullptr), m_creatureData(nullptr), m_detectionDistance(20.0f), m_waypointID(0), m_path_id(0), m_formation(nullptr), _lastDamagedTime(nullptr), m_cannotReachTarget(false), m_cannotReachTimer(0),
     _isMissingSwimmingFlagOutOfCombat(false), m_assistanceTimer(0)
 {
     m_regenTimer = CREATURE_REGEN_INTERVAL;
     m_valuesCount = UNIT_END;
     for (uint8 i = 0; i < MAX_CREATURE_SPELLS; ++i)
         m_spells[i] = 0;
     for (uint8 i = SPELL_SCHOOL_NORMAL; i < MAX_SPELL_SCHOOL; ++i)
         m_ProhibitSchoolTime[i] = 0;
     m_CreatureSpellCooldowns.clear();
     DisableReputationGain = false;
     m_SightDistance = sWorld->getFloatConfig(CONFIG_SIGHT_MONSTER);
     m_CombatDistance = 0.0f;
     ResetLootMode(); // restore default loot mode
     TriggerJustRespawned = false;
     m_isTempWorldObject = false;
     _focusSpell = nullptr;
     m_respawnedTime = time_t(0);
 }
References _focusSpell, CONFIG_SIGHT_MONSTER, CREATURE_REGEN_INTERVAL, DisableReputationGain, m_CombatDistance, m_CreatureSpellCooldowns, m_isTempWorldObject, m_ProhibitSchoolTime, Unit::m_regenTimer, m_respawnedTime, m_SightDistance, m_spells, Object::m_valuesCount, MAX_CREATURE_SPELLS, MAX_SPELL_SCHOOL, ResetLootMode(), SPELL_SCHOOL_NORMAL, sWorld, TriggerJustRespawned, and UNIT_END.
~Creature()
Creature::~Creature () override
Definition at line 208 of file Creature.cpp.
 {
     m_vendorItemCounts.clear();
     delete i_AI;
     i_AI = nullptr;
 }
References Unit::i_AI, and m_vendorItemCounts.
Member Function Documentation
_AddCreatureSpellCooldown()
void Creature::_AddCreatureSpellCooldown (uint32 spell_id, uint16 categoryId, uint32 end_time)
Definition at line 2582 of file Creature.cpp.
 {
     CreatureSpellCooldown spellCooldown;
     spellCooldown.category = categoryId;
     spellCooldown.end = World::GetGameTimeMS() + end_time;
     m_CreatureSpellCooldowns[spell_id] = std::move(spellCooldown);
 }
References CreatureSpellCooldown::category, CreatureSpellCooldown::end, World::GetGameTimeMS(), and m_CreatureSpellCooldowns.
Referenced by Pet::_LoadSpellCooldowns(), AddSpellCooldown(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::UpdateAI(), and npc_gunship_rocketeer::npc_gunship_rocketeerAI::UpdateAI().
_CanDetectFeignDeathOf()
bool Creature::_CanDetectFeignDeathOf (const Unit * target) const
Definition at line 2343 of file Creature.cpp.
 {
     if (target->HasFlag(UNIT_FIELD_FLAGS_2, UNIT_FLAG2_FEIGN_DEATH))
         return IsGuard();
     return true;
 }
References Object::HasFlag(), IsGuard(), UNIT_FIELD_FLAGS_2, and UNIT_FLAG2_FEIGN_DEATH.
Referenced by PetAI::_needToStop(), boss_hadronox::boss_hadronoxAI::AnyPlayerValid(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustSummoned(), boss_twinemperorsAI::MoveInLineOfSight(), PetAI::SelectNextTarget(), ThreatContainer::selectNextVictim(), SelectVictim(), npc_pet_shaman_earth_elemental::UpdateAI(), and npc_pet_shaman_fire_elemental::UpdateAI().
_GetDamageMod()
float Creature::_GetDamageMod (int32 Rank) static
Definition at line 1428 of file Creature.cpp.
 {
     switch (Rank)                                           // define rates for each elite rank
     {
         case CREATURE_ELITE_NORMAL:
             return sWorld->getRate(RATE_CREATURE_NORMAL_DAMAGE);
         case CREATURE_ELITE_ELITE:
             return sWorld->getRate(RATE_CREATURE_ELITE_ELITE_DAMAGE);
         case CREATURE_ELITE_RAREELITE:
             return sWorld->getRate(RATE_CREATURE_ELITE_RAREELITE_DAMAGE);
         case CREATURE_ELITE_WORLDBOSS:
             return sWorld->getRate(RATE_CREATURE_ELITE_WORLDBOSS_DAMAGE);
         case CREATURE_ELITE_RARE:
             return sWorld->getRate(RATE_CREATURE_ELITE_RARE_DAMAGE);
         default:
             return sWorld->getRate(RATE_CREATURE_ELITE_ELITE_DAMAGE);
     }
 }
References CREATURE_ELITE_ELITE, CREATURE_ELITE_NORMAL, CREATURE_ELITE_RARE, CREATURE_ELITE_RAREELITE, CREATURE_ELITE_WORLDBOSS, RATE_CREATURE_ELITE_ELITE_DAMAGE, RATE_CREATURE_ELITE_RARE_DAMAGE, RATE_CREATURE_ELITE_RAREELITE_DAMAGE, RATE_CREATURE_ELITE_WORLDBOSS_DAMAGE, RATE_CREATURE_NORMAL_DAMAGE, and sWorld.
Referenced by ObjectMgr::CheckCreatureTemplate().
_GetHealthMod()
float Creature::_GetHealthMod (int32 Rank) static protected
Definition at line 1409 of file Creature.cpp.
 {
     switch (Rank)                                           // define rates for each elite rank
     {
         case CREATURE_ELITE_NORMAL:
             return sWorld->getRate(RATE_CREATURE_NORMAL_HP);
         case CREATURE_ELITE_ELITE:
             return sWorld->getRate(RATE_CREATURE_ELITE_ELITE_HP);
         case CREATURE_ELITE_RAREELITE:
             return sWorld->getRate(RATE_CREATURE_ELITE_RAREELITE_HP);
         case CREATURE_ELITE_WORLDBOSS:
             return sWorld->getRate(RATE_CREATURE_ELITE_WORLDBOSS_HP);
         case CREATURE_ELITE_RARE:
             return sWorld->getRate(RATE_CREATURE_ELITE_RARE_HP);
         default:
             return sWorld->getRate(RATE_CREATURE_ELITE_ELITE_HP);
     }
 }
References CREATURE_ELITE_ELITE, CREATURE_ELITE_NORMAL, CREATURE_ELITE_RARE, CREATURE_ELITE_RAREELITE, CREATURE_ELITE_WORLDBOSS, RATE_CREATURE_ELITE_ELITE_HP, RATE_CREATURE_ELITE_RARE_HP, RATE_CREATURE_ELITE_RAREELITE_HP, RATE_CREATURE_ELITE_WORLDBOSS_HP, RATE_CREATURE_NORMAL_HP, and sWorld.
Referenced by LoadCreatureFromDB(), and SelectLevel().
_IsTargetAcceptable()
bool Creature::_IsTargetAcceptable (const Unit * target) const
Definition at line 2311 of file Creature.cpp.
 {
     ASSERT(target);
     // if the target cannot be attacked, the target is not acceptable
     if (IsFriendlyTo(target) || !target->isTargetableForAttack(false, this) || (m_vehicle && (IsOnVehicle(target) || m_vehicle->GetBase()->IsOnVehicle(target))))
         return false;
     if (target->HasUnitState(UNIT_STATE_DIED))
     {
         // some creatures can detect fake death
         if (CanIgnoreFeignDeath() && target->HasFlag(UNIT_FIELD_FLAGS_2, UNIT_FLAG2_FEIGN_DEATH))
             return true;
         else
             return false;
     }
     const Unit* myVictim = getAttackerForHelper();
     const Unit* targetVictim = target->getAttackerForHelper();
     // if I'm already fighting target, or I'm hostile towards the target, the target is acceptable
     if (myVictim == target || targetVictim == this || IsHostileTo(target))
         return true;
     // if the target's victim is friendly, and the target is neutral, the target is acceptable
     if (targetVictim && !IsNeutralToAll() && IsFriendlyTo(targetVictim))
         return true;
     // if the target's victim is not friendly, or the target is friendly, the target is not acceptable
     return false;
 }
References ASSERT, CanIgnoreFeignDeath(), Unit::getAttackerForHelper(), Vehicle::GetBase(), Object::HasFlag(), Unit::HasUnitState(), Unit::IsFriendlyTo(), Unit::IsHostileTo(), Unit::IsNeutralToAll(), Unit::IsOnVehicle(), Unit::isTargetableForAttack(), Unit::m_vehicle, UNIT_FIELD_FLAGS_2, UNIT_FLAG2_FEIGN_DEATH, and UNIT_STATE_DIED.
Referenced by CanStartAttack(), and CreatureAI::TriggerAlert().
AddLootMode()
void Creature::AddLootMode (uint16 lootMode) inline
Definition at line 228 of file Creature.h.
 { m_LootMode |= lootMode; }
References m_LootMode.
Referenced by boss_sartharion::boss_sartharionAI::EnterCombat(), instance_shattered_halls::instance_shattered_halls_InstanceMapScript::OnCreatureCreate(), and boss_yoggsaron::boss_yoggsaronAI::SpellHit().
AddSpellCooldown()
void Creature::AddSpellCooldown (uint32 spell_id, uint32 , uint32 end_time, bool needSendToClient = false, bool forceSendToSpectator = false) override virtual
Reimplemented from Unit.
Definition at line 2590 of file Creature.cpp.
 {
     SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(spell_id);
     if (!spellInfo)
         return;
     // used in proc system, otherwise normal creature cooldown
     if (end_time)
     {
         _AddCreatureSpellCooldown(spellInfo->Id, 0, end_time);
         return;
     }
     uint32 spellcooldown = spellInfo->RecoveryTime;
     uint32 categoryId = spellInfo->GetCategory();
     uint32 categorycooldown = categoryId ? spellInfo->CategoryRecoveryTime : 0;
     if (Player* modOwner = GetSpellModOwner())
     {
         modOwner->ApplySpellMod(spellInfo->Id, SPELLMOD_COOLDOWN, spellcooldown);
         modOwner->ApplySpellMod(spellInfo->Id, SPELLMOD_COOLDOWN, categorycooldown);
     }
     SpellCategoryStore::const_iterator i_scstore = sSpellsByCategoryStore.find(categoryId);
     if (categorycooldown && i_scstore != sSpellsByCategoryStore.end())
     {
         for (SpellCategorySet::const_iterator i_scset = i_scstore->second.begin(); i_scset != i_scstore->second.end(); ++i_scset)
         {
             _AddCreatureSpellCooldown(i_scset->second, categoryId, categorycooldown);
         }
     }
     else if (spellcooldown)
     {
         _AddCreatureSpellCooldown(spellInfo->Id, 0, spellcooldown);
     }
 }
References _AddCreatureSpellCooldown(), SpellInfo::CategoryRecoveryTime, SpellInfo::GetCategory(), Unit::GetSpellModOwner(), SpellInfo::Id, SpellInfo::RecoveryTime, SPELLMOD_COOLDOWN, sSpellMgr, and sSpellsByCategoryStore.
Referenced by WorldSession::HandlePetActionHelper(), WorldSession::HandlePetCancelAuraOpcode(), boss_faction_championsAI::IsCCed(), and PetAI::UpdateAI().
AddToWorld()
void Creature::AddToWorld () override virtual
Register the creature for guid lookup
Reimplemented from Object.
Reimplemented in Pet.
Definition at line 216 of file Creature.cpp.
 {
     if (!IsInWorld())
     {
         // pussywizard: motion master needs to be initialized before OnCreatureCreate, which may set death state to JUST_DIED, to prevent crash
         // it's also initialized in AIM_Initialize(), few lines below, but it's not a problem
         Motion_Initialize();
         GetMap()->GetObjectsStore().Insert<Creature>(GetGUID(), this);
         if (m_spawnId)
         {
             GetMap()->GetCreatureBySpawnIdStore().insert(std::make_pair(m_spawnId, this));
         }
         Unit::AddToWorld();
         SearchFormation();
         AIM_Initialize();
         if (IsVehicle())
         {
             GetVehicleKit()->Install();
         }
         if (GetZoneScript())
         {
             GetZoneScript()->OnCreatureCreate(this);
         }
 #ifdef ELUNA
         sEluna->OnAddToWorld(this);
     if (IsGuardian() && ToTempSummon() && ToTempSummon()->GetSummonerGUID().IsPlayer())
         sEluna->OnPetAddedToWorld(ToTempSummon()->GetSummonerUnit()->ToPlayer(), this);
 #endif
     }
 }
References Unit::AddToWorld(), AIM_Initialize(), Map::GetCreatureBySpawnIdStore(), Object::GetGUID(), WorldObject::GetMap(), Map::GetObjectsStore(), Unit::GetVehicleKit(), WorldObject::GetZoneScript(), TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::Insert(), Vehicle::Install(), Unit::IsGuardian(), Object::IsInWorld(), Object::IsPlayer(), Unit::IsVehicle(), m_spawnId, Motion_Initialize(), ZoneScript::OnCreatureCreate(), SearchFormation(), Object::ToPlayer(), and Unit::ToTempSummon().
Referenced by AddObjectHelper().
AI()
CreatureAI* Creature::AI () const inline
Definition at line 129 of file Creature.h.
 { return (CreatureAI*)i_AI; }
References Unit::i_AI.
Referenced by Vehicle::AddPassenger(), Player::AddQuestAndCheckCompletion(), npc_mograine::npc_mograineAI::AshbringerEvent(), boss_algalon_the_observer::boss_algalon_the_observerAI::CallConstellations(), CanAlwaysSee(), CanCreatureAttack(), boss_veknilash::boss_veknilashAI::CastSpellOnBug(), instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::CheckAchievementCriteriaMeet(), spell_putricide_mutation_init::spell_putricide_mutation_init_SpellScript::CheckRequirementInternal(), spell_the_lich_king_ice_burst_target_search::spell_the_lich_king_ice_burst_target_search_SpellScript::CheckTargetCount(), Unit::CombatStart(), Unit::DealDamage(), DespawnOnEvade(), hyjalAI::DeSpawnVeins(), SummonList::DoAction(), boss_illidari_council::boss_illidari_councilAI::DoAction(), Spell::DoAllEffectOnTarget(), HomeMovementGenerator< Creature >::DoFinalize(), hyjalAI::DoOverrun(), instance_stratholme::instance_stratholme_InstanceMapScript::DoSpawnPlaguedCritters(), instance_mechanar::instance_mechanar_InstanceMapScript::DoSummonAction(), SummonList::DoZoneInCombat(), Spell::EffectTaunt(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::EnterCombat(), boss_twinemperorsAI::EnterCombat(), boss_zuljin::boss_zuljinAI::EnterPhase(), AssistDelayEvent::Execute(), RestoreAttack::Execute(), DelayedTalk::Execute(), UtherBatteredHiltEvent::Execute(), StartMovementEvent::Execute(), ValithriaDespawner::Execute(), CaptainSurviveTalk::Execute(), ChargeRifts::Execute(), spell_kiljaeden_sinister_reflection_clone::spell_kiljaeden_sinister_reflection_clone_SpellScript::FilterTargets(), spell_sapphiron_frost_explosion::spell_sapphiron_frost_explosion_SpellScript::FilterTargets(), RotateMovementGenerator::Finalize(), EffectMovementGenerator::Finalize(), npc_anubisath_sentinel::aqsentinelAI::GetOtherSentinels(), SmartScript::GetTargets(), spell_herald_volzaj_insanity::spell_herald_volzaj_insanity_SpellScript::HandleAfterCast(), spell_illidari_council_empyreal_balance::spell_illidari_council_empyreal_balance_SpellScript::HandleAfterCast(), npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::HandleAnimation(), spell_item_lil_xt::HandleDummy(), spell_halion_twilight_division::spell_halion_twilight_division_SpellScript::HandleDummy(), spell_q12096_q12092_dummy::spell_q12096_q12092_dummy_SpellScript::HandleDummy(), spell_q12096_q12092_bark::spell_q12096_q12092_bark_SpellScript::HandleDummy(), spell_q12589_shoot_rjr::spell_q12589_shoot_rjr_SpellScript::HandleDummy(), spell_algalon_trigger_3_adds::spell_algalon_trigger_3_adds_SpellScript::HandleDummyEffect(), spell_herald_volzaj_insanity::spell_herald_volzaj_insanity_SpellScript::HandleDummyEffect(), spell_mc_play_dead::spell_mc_play_dead_AuraScript::HandleEffectRemove(), WorldSession::HandleGossipHelloOpcode(), WorldSession::HandleGossipSelectOptionOpcode(), npc_commandscript::HandleNpcSetDataCommand(), WorldSession::HandlePetActionHelper(), WorldSession::HandleQuestgiverChooseRewardOpcode(), WorldSession::HandleQuestgiverHelloOpcode(), spell_jedoga_sacrafice_beam::spell_jedoga_sacrafice_beam_AuraScript::HandleRemoval(), spell_kiljaeden_darkness::spell_kiljaeden_darkness_AuraScript::HandleRemove(), spell_taldaram_summon_flame_ball::spell_taldaram_summon_flame_ball_SpellScript::HandleScript(), spell_putricide_unstable_experiment::spell_putricide_unstable_experiment_SpellScript::HandleScript(), spell_the_lich_king_vile_spirit_move_target_search::spell_the_lich_king_vile_spirit_move_target_search_SpellScript::HandleScript(), spell_festergut_pungent_blight::spell_festergut_pungent_blight_SpellScript::HandleScript(), spell_rotface_large_ooze_combine::spell_rotface_large_ooze_combine_SpellScript::HandleScript(), spell_rotface_large_ooze_buff_combine::spell_rotface_large_ooze_buff_combine_SpellScript::HandleScript(), spell_q13011_bear_flank_master::HandleScript(), spell_volazj_whisper::spell_volazj_whisper_SpellScript::HandleScriptEffect(), Unit::HandleSpellClick(), spell_putricide_mutated_transformation::spell_putricide_mutated_transformation_SpellScript::HandleSummon(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::InformCloud(), TempSummon::InitSummon(), npc_tito::npc_titoAI::JustDied(), npc_love_in_air_hummel::npc_love_in_air_hummelAI::JustDied(), npc_love_in_air_hummel_helper::npc_love_in_air_hummel_helperAI::JustDied(), boss_twinemperorsAI::JustDied(), npc_anubisath_sentinel::aqsentinelAI::JustDied(), boss_warbringer_omrogg::boss_warbringer_omroggAI::JustDied(), boss_anubrekhan::boss_anubrekhanAI::JustSummoned(), boss_maexxna::boss_maexxnaAI::JustSummoned(), npc_frosthound::npc_frosthoundAI::JustSummoned(), npc_eye_of_acherus::npc_eye_of_acherusAI::JustSummoned(), npc_eris_hevenfire::npc_eris_hevenfireAI::JustSummoned(), npc_daphne_stilwell::npc_daphne_stilwellAI::JustSummoned(), boss_skeram::boss_skeramAI::JustSummoned(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::JustSummoned(), boss_urom::boss_uromAI::JustSummoned(), boss_onyxia::boss_onyxiaAI::JustSummoned(), npc_hor_lich_king::npc_hor_lich_kingAI::JustSummoned(), WorldBossAI::JustSummoned(), npc_grimstone::npc_grimstoneAI::JustSummoned(), boss_gyth::boss_gythAI::JustSummoned(), boss_rend_blackhand::boss_rend_blackhandAI::JustSummoned(), boss_curator::boss_curatorAI::JustSummoned(), boss_sacrolash::boss_sacrolashAI::JustSummoned(), npc_demonic_vapor_trail::npc_demonic_vapor_trailAI::JustSummoned(), boss_muru::boss_muruAI::JustSummoned(), boss_halazzi::boss_halazziAI::JustSummoned(), boss_taldaram::boss_taldaramAI::JustSummoned(), boss_black_knight::boss_black_knightAI::JustSummoned(), boss_devourer_of_souls::boss_devourer_of_soulsAI::JustSummoned(), boss_drakkari_colossus::boss_drakkari_colossusAI::JustSummoned(), boss_prince_taldaram_icc::boss_prince_taldaramAI::JustSummoned(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustSummoned(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustSummoned(), npc_precious_icc::npc_precious_iccAI::JustSummoned(), npc_the_lich_king_controller::npc_the_lich_king_controllerAI::JustSummoned(), npc_gluttonous_abomination::npc_gluttonous_abominationAI::JustSummoned(), boss_gluth::boss_gluthAI::JustSummoned(), boss_volkhan::boss_volkhanAI::JustSummoned(), boss_nexusprince_shaffar::boss_nexusprince_shaffarAI::JustSummoned(), boss_anzu::boss_anzuAI::JustSummoned(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::JustSummoned(), npc_akama_illidan::npc_akama_illidanAI::JustSummoned(), npc_creature_generator_akama::npc_creature_generator_akamaAI::JustSummoned(), boss_the_black_stalker::boss_the_black_stalkerAI::JustSummoned(), boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI::JustSummoned(), boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI::JustSummoned(), npc_nelson::npc_nelsonAI::JustSummoned(), boss_balinda::boss_balindaAI::JustSummoned(), boss_nightbane::boss_nightbaneAI::JustSummoned(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::JustSummoned(), npc_professor_phizzlethorpe::npc_professor_phizzlethorpeAI::JustSummoned(), npc_thrall_bfu::npc_thrall_bfuAI::JustSummoned(), npc_tapoke_slim_jahn::npc_tapoke_slim_jahnAI::JustSummoned(), boss_archimonde::boss_archimondeAI::JustSummoned(), npc_muglash::npc_muglashAI::JustSummoned(), npc_kaya_flathoof::npc_kaya_flathoofAI::JustSummoned(), npc_wizzlecrank_shredder::npc_wizzlecrank_shredderAI::JustSummoned(), npc_ame::npc_ameAI::JustSummoned(), npc_emily::npc_emilyAI::JustSummoned(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::JustSummoned(), npc_wounded_blood_elf::npc_wounded_blood_elfAI::JustSummoned(), npc_maghar_captive::npc_maghar_captiveAI::JustSummoned(), npc_kurenai_captive::npc_kurenai_captiveAI::JustSummoned(), npc_bessy::npc_bessyAI::JustSummoned(), npc_earthmender_wilda::npc_earthmender_wildaAI::JustSummoned(), boss_ayamiss::boss_ayamissAI::JustSummoned(), npc_buru_egg::npc_buru_eggAI::JustSummoned(), Unit::Kill(), boss_warbringer_omrogg::boss_warbringer_omroggAI::KilledUnit(), CreatureGroup::MemberAttackStart(), CreatureGroup::MemberEvaded(), npc_brew_bubble::npc_brew_bubbleAI::MoveInLineOfSight(), npc_dkc1_gothik::npc_dkc1_gothikAI::MoveInLineOfSight(), npc_love_in_air_supply_sentry::npc_love_in_air_supply_sentryAI::MoveInLineOfSight(), npc_air_force_bots::npc_air_force_botsAI::MoveInLineOfSight(), WaypointMovementGenerator< Creature >::MovementInform(), spell_pilgrims_bounty_serve_generic::spell_pilgrims_bounty_serve_generic_AuraScript::OnAuraRemove(), achievement_flu_shot_shortage::OnCheck(), achievement_smell_saronite::OnCheck(), achievement_shadowdodger::OnCheck(), achievement_cheese_the_freeze::OnCheck(), achievement_getting_cold_in_here::OnCheck(), achievement_i_could_say_that_this_cache_was_rare::OnCheck(), achievement_i_have_the_coolest_friends::OnCheck(), achievement_ignis_shattered::OnCheck(), achievement_mimiron_firefighter::OnCheck(), achievement_mimiron_set_up_us_the_bomb_11::OnCheck(), achievement_mimiron_set_up_us_the_bomb_12::OnCheck(), achievement_mimiron_set_up_us_the_bomb_13::OnCheck(), achievement_quick_shave::OnCheck(), instance_blackrock_spire::instance_blackrock_spireMapScript::OnCreatureCreate(), go_palehoof_sphere::OnGossipHello(), npc_pet_gen_argent_pony_bridle::OnGossipHello(), npc_barnes::OnGossipHello(), npc_death_knight_initiate::OnGossipHello(), npc_highlord_darion_mograine::OnGossipHello(), npc_costumed_orphan_matron::OnGossipHello(), npc_jaina_proudmoore::OnGossipHello(), npc_thrall::OnGossipHello(), npc_tyrande_whisperwind::OnGossipHello(), npc_finklestein::OnGossipHello(), npc_captain_saeed::OnGossipHello(), npc_salsalabim::OnGossipHello(), npc_natrualist_bite::OnGossipHello(), npc_elder_clearwater::OnGossipHello(), npc_riggle_bassbait::OnGossipHello(), npc_wormhole::OnGossipHello(), go_ossirian_crystal::OnGossipHello(), go_the_pearl_of_the_depths::OnGossipHello(), go_pressure_valve::OnGossipHello(), go_brazier::OnGossipHello(), go_finklestein_cauldron::OnGossipHello(), go_prince_taldaram_sphere::OnGossipHello(), npc_pet_gen_argent_pony_bridle::OnGossipSelect(), boss_doomrel::OnGossipSelect(), boss_majordomo::OnGossipSelect(), npc_barnes::OnGossipSelect(), npc_death_knight_initiate::OnGossipSelect(), npc_highlord_darion_mograine::OnGossipSelect(), npc_varian_wrynn::OnGossipSelect(), npc_thrall_bfu::OnGossipSelect(), npc_jaina_proudmoore::OnGossipSelect(), npc_thrall::OnGossipSelect(), npc_arthas::OnGossipSelect(), npc_high_overlord_saurfang_icc::OnGossipSelect(), npc_muradin_bronzebeard_icc::OnGossipSelect(), brann_bronzebeard::OnGossipSelect(), npc_shandy_dalaran::OnGossipSelect(), npc_vekjik::OnGossipSelect(), npc_adventurous_dwarf::OnGossipSelect(), adyen_the_lightbringer::OnGossipSelect(), npc_raliq_the_drunk::OnGossipSelect(), npc_floon::OnGossipSelect(), npcs_ashyen_and_keleth::OnGossipSelect(), npc_cooshcoosh::OnGossipSelect(), npc_fos_leader::OnGossipSelect(), npc_hor_leader::OnGossipSelect(), npc_ulduar_expedition_commander::OnGossipSelect(), npc_mcmanus::OnGossipSelect(), npc_finklestein::OnGossipSelect(), npc_captain_saeed::OnGossipSelect(), npc_thrall_old_hillsbrad::OnGossipSelect(), npc_hor_leader_second::OnGossipSelect(), npc_tirions_gambit_tirion::OnGossipSelect(), npc_natrualist_bite::OnGossipSelect(), npc_artorius::OnGossipSelect(), npc_simone::OnGossipSelect(), npc_nelson::OnGossipSelect(), npc_franklin::OnGossipSelect(), go_amberpine_outhouse::OnGossipSelect(), instance_ulduar::instance_ulduar_InstanceMapScript::OnPlayerEnter(), npc_costumed_orphan_matron::OnQuestAccept(), npc_chicken_cluck::OnQuestAccept(), npc_kernobee::OnQuestAccept(), npc_koltira_deathweaver::OnQuestAccept(), pyrewood_ambush::OnQuestAccept(), npc_daphne_stilwell::OnQuestAccept(), npc_mikhail::OnQuestAccept(), npc_kerlonian::OnQuestAccept(), npc_prospector_remtravel::OnQuestAccept(), npc_tooga::OnQuestAccept(), npc_gilthares::OnQuestAccept(), npc_lakota_windsong::OnQuestAccept(), npc_paoka_swiftmountain::OnQuestAccept(), npc_ringo::OnQuestAccept(), npc_engineer_helice::OnQuestAccept(), npc_maghar_captive::OnQuestAccept(), npc_kurenai_captive::OnQuestAccept(), npc_maxx_a_million_escort::OnQuestAccept(), npc_earthmender_wilda::OnQuestAccept(), npc_eris_hevenfire::OnQuestAccept(), npc_ranger_lilatha::OnQuestAccept(), npc_deathstalker_erland::OnQuestAccept(), npc_bartleby::OnQuestAccept(), npc_calvin_montague::OnQuestAccept(), npc_cork_gizelton::OnQuestAccept(), npc_shenthul::OnQuestAccept(), npc_kaya_flathoof::OnQuestAccept(), npc_wizzlecrank_shredder::OnQuestAccept(), npc_ame::OnQuestAccept(), npc_ranshalla::OnQuestAccept(), npc_lurgglbr::OnQuestAccept(), npc_mootoo_the_younger::OnQuestAccept(), npc_bonker_togglevolt::OnQuestAccept(), npc_emily::OnQuestAccept(), npc_apothecary_hanes::OnQuestAccept(), npc_battle_at_valhalas::OnQuestAccept(), npc_finklestein::OnQuestAccept(), npc_bessy::OnQuestAccept(), npc_isla_starmane::OnQuestAccept(), npc_kayra_longmane::OnQuestAccept(), npc_doctor::OnQuestAccept(), go_crystal_prison::OnQuestAccept(), go_crystalline_tear::OnQuestAccept(), npc_chicken_cluck::OnQuestComplete(), npc_love_in_air_hummel::OnQuestReward(), npc_rocknot::OnQuestReward(), npc_lady_sylvanas_windrunner::OnQuestReward(), npc_elder_clearwater::OnQuestReward(), npc_riggle_bassbait::OnQuestReward(), at_blackrock_stadium::OnTrigger(), at_commander_dawnforge::OnTrigger(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath(), OrderWhelpTargetSelector::operator()(), FrostwingGauntletRespawner::operator()(), ValithriaDespawner::operator()(), Acore::CallOfHelpCreatureInRangeDo::operator()(), SplineHandler::operator()(), Unit::PetSpellFail(), spell_hodir_flash_freeze::spell_hodir_flash_freeze_AuraScript::PrepareAuraScript(), npc_jungle_punch_target::npc_jungle_punch_targetAI::proceedCwEvent(), SmartScript::ProcessAction(), instance_stratholme::instance_stratholme_InstanceMapScript::ProcessSlaughterEvent(), RemoveCorpse(), Vehicle::RemovePassenger(), boss_illidari_council::boss_illidari_councilAI::Reset(), Respawn(), RespawnOnEvade(), Resurrect(), hyjalAI::Retreat(), spell_the_lich_king_valkyr_target_search::spell_the_lich_king_valkyr_target_search_SpellScript::SelectTarget(), SelectVictim(), instance_naxxramas::instance_naxxramas_InstanceMapScript::SetBossState(), Unit::SetCharmedBy(), instance_ahnkahet::instance_ahnkahet_InstanceScript::SetData(), SetInCombatWithZone(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::SpawnAdds(), boss_cthun::cthunAI::SpawnEyeTentacle(), npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::SpellHitTarget(), spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript::StartAttack(), hyjalAI::SummonCreature(), brann_bronzebeard::brann_bronzebeardAI::SummonCreatures(), boss_zuramat::boss_zuramatAI::SummonedCreatureDespawn(), boss_sindragosa::boss_sindragosaAI::SummonedCreatureDespawn(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::SummonedCreatureDespawn(), boss_anubrekhan::boss_anubrekhanAI::SummonedCreatureDies(), npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::SummonNextWave(), instance_the_black_morass::instance_the_black_morass_InstanceMapScript::SummonPortalKeeper(), npc_artruis_the_hearthless::npc_artruis_the_hearthlessAI::SummonsAction(), boss_fankriss::boss_fankrissAI::SummonSpawn(), npc_love_in_air_snivel_real::npc_love_in_air_snivel_realAI::Talk(), Unit::TauntApply(), Unit::TauntFadeOut(), boss_twinemperorsAI::TeleportToMyBrother(), spell_igb_check_for_players::spell_igb_check_for_players_SpellScript::TriggerWipe(), TempSummon::UnSummon(), Pet::Update(), instance_stratholme::instance_stratholme_InstanceMapScript::Update(), instance_naxxramas::instance_naxxramas_InstanceMapScript::Update(), Update(), boss_julianne::boss_julianneAI::UpdateAI(), boss_romulo::boss_romuloAI::UpdateAI(), pyrewood_ambush::pyrewood_ambushAI::UpdateAI(), boss_akilzon::boss_akilzonAI::UpdateAI(), boss_hazzarah::boss_hazzarahAI::UpdateAI(), boss_jindo::boss_jindoAI::UpdateAI(), boss_marli::boss_marliAI::UpdateAI(), npc_winterfin_playmate::npc_winterfin_playmateAI::UpdateAI(), npc_snowfall_glade_playmate::npc_snowfall_glade_playmateAI::UpdateAI(), npc_the_biggest_tree::npc_the_biggest_treeAI::UpdateAI(), npc_high_oracle_soo_roo::npc_high_oracle_soo_rooAI::UpdateAI(), npc_elder_kekek::npc_elder_kekekAI::UpdateAI(), npc_the_etymidian::npc_the_etymidianAI::UpdateAI(), npc_alexstraza_the_lifebinder::npc_alexstraza_the_lifebinderAI::UpdateAI(), npc_love_in_air_hummel::npc_love_in_air_hummelAI::UpdateAI(), npc_frost_wyrm::npc_frost_wyrmAI::UpdateAI(), npc_gargoyle::npc_gargoyleAI::UpdateAI(), boss_eye_of_cthun::eye_of_cthunAI::UpdateAI(), boss_fankriss::boss_fankrissAI::UpdateAI(), npc_twiggy_flathead::npc_twiggy_flatheadAI::UpdateAI(), boss_prince_valanar_icc::boss_prince_valanarAI::UpdateAI(), npc_freya_ward::npc_freya_wardAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), boss_razorscale::boss_razorscaleAI::UpdateAI(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::UpdateAI(), socrethar::socretharAI::UpdateAI(), npc_commander_dawnforge::npc_commander_dawnforgeAI::UpdateAI(), npc_tooga::npc_toogaAI::UpdateFollowerAI(), npc_ringo::npc_ringoAI::UpdateFollowerAI(), InstanceScript::UpdateMinionState(), npc_ranger_lilatha::npc_ranger_lilathaAI::WaypointReached(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::WaypointReached(), npc_cork_gizelton::npc_cork_gizeltonAI::WaypointReached(), npc_ancestral_wolf::npc_ancestral_wolfAI::WaypointReached(), and npc_bessy::npc_bessyAI::WaypointReached().
AIM_Initialize()
bool Creature::AIM_Initialize (CreatureAI * ai = nullptr)
Definition at line 928 of file Creature.cpp.
 {
     // make sure nothing can change the AI during AI update
     if (m_AI_locked)
     {
         LOG_DEBUG("scripts.ai", "AIM_Initialize: failed to init, locked.");
         return false;
     }
     UnitAI* oldAI = i_AI;
     // Xinef: called in add to world
     //Motion_Initialize();
     i_AI = ai ? ai : FactorySelector::selectAI(this);
     delete oldAI;
     IsAIEnabled = true;
     i_AI->InitializeAI();
     // Xinef: Initialize vehicle if it is not summoned!
     if (GetVehicleKit() && m_spawnId)
         GetVehicleKit()->Reset();
     return true;
 }
References Unit::GetVehicleKit(), Unit::i_AI, UnitAI::InitializeAI(), Unit::IsAIEnabled, LOG_DEBUG, m_AI_locked, m_spawnId, Vehicle::Reset(), and FactorySelector::selectAI().
Referenced by AddToWorld(), Pet::AddToWorld(), and WorldObject::SummonTrigger().
AllLootRemovedFromCorpse()
void Creature::AllLootRemovedFromCorpse ()
Definition at line 2700 of file Creature.cpp.
 {
     if (!HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_SKINNABLE))
     {
         time_t now = time(nullptr);
         if (m_corpseRemoveTime <= now)
             return;
         float decayRate;
         CreatureTemplate const* cinfo = GetCreatureTemplate();
         decayRate = sWorld->getRate(RATE_CORPSE_DECAY_LOOTED);
         uint32 diff = uint32((m_corpseRemoveTime - now) * decayRate);
         m_respawnTime -= diff;
         // corpse skinnable, but without skinning flag, and then skinned, corpse will despawn next update
         if (cinfo && cinfo->SkinLootId)
             m_corpseRemoveTime = time(nullptr);
         else
             m_corpseRemoveTime -= diff;
     }
 }
References diff(), GetCreatureTemplate(), Object::HasFlag(), m_corpseRemoveTime, m_respawnTime, RATE_CORPSE_DECAY_LOOTED, CreatureTemplate::SkinLootId, sWorld, UNIT_FIELD_FLAGS, and UNIT_FLAG_SKINNABLE.
Referenced by WorldSession::DoLootRelease().
applyInhabitFlags()
void Creature::applyInhabitFlags () private
Definition at line 2923 of file Creature.cpp.
 {
     if (IsAlive() && !HasUnitState(UNIT_STATE_ROOT) && !HasUnitMovementFlag(MOVEMENTFLAG_ROOT))
     {
         if (IsLevitating())
         {
             SetByteValue(UNIT_FIELD_BYTES_1, UNIT_BYTES_1_OFFSET_ANIM_TIER, UNIT_BYTE1_FLAG_FLY);
         }
         else if (IsHovering())
         {
             SetByteValue(UNIT_FIELD_BYTES_1, UNIT_BYTES_1_OFFSET_ANIM_TIER, UNIT_BYTE1_FLAG_HOVER);
         }
         else
             SetByteValue(UNIT_FIELD_BYTES_1, UNIT_BYTES_1_OFFSET_ANIM_TIER, UNIT_BYTE1_FLAG_GROUND);
     }
 }
References Unit::HasUnitMovementFlag(), Unit::HasUnitState(), Unit::IsAlive(), Unit::IsHovering(), Unit::IsLevitating(), MOVEMENTFLAG_ROOT, Object::SetByteValue(), UNIT_BYTE1_FLAG_FLY, UNIT_BYTE1_FLAG_GROUND, UNIT_BYTE1_FLAG_HOVER, UNIT_BYTES_1_OFFSET_ANIM_TIER, UNIT_FIELD_BYTES_1, and UNIT_STATE_ROOT.
Referenced by SetDisableGravity(), and SetHover().
CalculateMinMaxDamage()
void Creature::CalculateMinMaxDamage (WeaponAttackType attType, bool normalized, bool addTotalPct, float & minDamage, float & maxDamage) override virtual
Implements Unit.
Definition at line 1055 of file StatSystem.cpp.
 {
     UnitMods unitMod;
     float variance = 1.0f;
     switch (attType)
     {
         case BASE_ATTACK:
         default:
             variance = GetCreatureTemplate()->BaseVariance;
             unitMod = UNIT_MOD_DAMAGE_MAINHAND;
             break;
         case OFF_ATTACK:
             variance = GetCreatureTemplate()->BaseVariance;
             unitMod = UNIT_MOD_DAMAGE_OFFHAND;
             break;
         case RANGED_ATTACK:
             variance = GetCreatureTemplate()->RangeVariance;
             unitMod = UNIT_MOD_DAMAGE_RANGED;
             break;
     }
     if (attType == OFF_ATTACK && !haveOffhandWeapon())
     {
         minDamage = 0.0f;
         maxDamage = 0.0f;
         return;
     }
     float weaponMinDamage = GetWeaponDamageRange(attType, MINDAMAGE);
     float weaponMaxDamage = GetWeaponDamageRange(attType, MAXDAMAGE);
     if (!CanUseAttackType(attType)) // disarm case
     {
         weaponMinDamage = 0.0f;
         weaponMaxDamage = 0.0f;
     }
     float attackPower      = GetTotalAttackPowerValue(attType);
     float attackSpeedMulti = GetAPMultiplier(attType, normalized);
     float baseValue        = GetModifierValue(unitMod, BASE_VALUE) + (attackPower / 14.0f) * variance;
     float basePct          = GetModifierValue(unitMod, BASE_PCT) * attackSpeedMulti;
     float totalValue       = GetModifierValue(unitMod, TOTAL_VALUE);
     float totalPct         = addTotalPct ? GetModifierValue(unitMod, TOTAL_PCT) : 1.0f;
     float dmgMultiplier    = GetCreatureTemplate()->DamageModifier; // = DamageModifier * _GetDamageMod(rank);
     minDamage = ((weaponMinDamage + baseValue) * dmgMultiplier * basePct + totalValue) * totalPct;
     maxDamage = ((weaponMaxDamage + baseValue) * dmgMultiplier * basePct + totalValue) * totalPct;
     // pussywizard: crashfix (casting negative to uint => min > max => assertion in urand)
     if (minDamage < 0.0f || minDamage > 1000000000.0f)
         minDamage = 0.0f;
     if (maxDamage < 0.0f || maxDamage > 1000000000.0f)
         maxDamage = 0.0f;
     if (minDamage > maxDamage)
         minDamage = maxDamage;
 }
References BASE_ATTACK, BASE_PCT, BASE_VALUE, CreatureTemplate::BaseVariance, Unit::CanUseAttackType(), CreatureTemplate::DamageModifier, Unit::GetAPMultiplier(), GetCreatureTemplate(), Unit::GetModifierValue(), Unit::GetTotalAttackPowerValue(), Unit::GetWeaponDamageRange(), Unit::haveOffhandWeapon(), MAXDAMAGE, MINDAMAGE, OFF_ATTACK, RANGED_ATTACK, CreatureTemplate::RangeVariance, TOTAL_PCT, TOTAL_VALUE, UNIT_MOD_DAMAGE_MAINHAND, UNIT_MOD_DAMAGE_OFFHAND, and UNIT_MOD_DAMAGE_RANGED.
CallAssistance()
void Creature::CallAssistance (Unit * target = nullptr)
Definition at line 2204 of file Creature.cpp.
 {
     if (!target)
     {
         target = GetVictim();
     }
     if (!m_AlreadyCallAssistance && target && !IsPet() && !IsCharmed())
     {
         SetNoCallAssistance(true);
         float radius = sWorld->getFloatConfig(CONFIG_CREATURE_FAMILY_ASSISTANCE_RADIUS);
         if (radius > 0)
         {
             std::list<Creature*> assistList;
             Acore::AnyAssistCreatureInRangeCheck u_check(this, target, radius);
             Acore::CreatureListSearcher<Acore::AnyAssistCreatureInRangeCheck> searcher(this, assistList, u_check);
             Cell::VisitGridObjects(this, searcher, radius);
             if (!assistList.empty())
             {
                 AssistDelayEvent* e = new AssistDelayEvent(target->GetGUID(), this);
                 while (!assistList.empty())
                 {
                     // Pushing guids because in delay can happen some creature gets despawned => invalid pointer
                     e->AddAssistant((*assistList.begin())->GetGUID());
                     assistList.pop_front();
                 }
                 m_Events.AddEvent(e, m_Events.CalculateTime(sWorld->getIntConfig(CONFIG_CREATURE_FAMILY_ASSISTANCE_DELAY)));
             }
         }
     }
 }
References AssistDelayEvent::AddAssistant(), EventProcessor::AddEvent(), EventProcessor::CalculateTime(), CONFIG_CREATURE_FAMILY_ASSISTANCE_DELAY, CONFIG_CREATURE_FAMILY_ASSISTANCE_RADIUS, Object::GetGUID(), Unit::GetVictim(), Unit::IsCharmed(), Unit::IsPet(), m_AlreadyCallAssistance, Unit::m_Events, SetNoCallAssistance(), sWorld, and Cell::VisitGridObjects().
Referenced by Unit::Attack(), AssistanceMovementGenerator::Finalize(), and Update().
CallForHelp()
void Creature::CallForHelp (float fRadius)
Definition at line 2240 of file Creature.cpp.
 {
     if (radius <= 0.0f || !GetVictim() || IsPet() || IsCharmed())
         return;
     Acore::CallOfHelpCreatureInRangeDo u_do(this, GetVictim(), radius);
     Acore::CreatureWorker<Acore::CallOfHelpCreatureInRangeDo> worker(this, u_do);
     Cell::VisitGridObjects(this, worker, radius);
 }
References Unit::GetVictim(), Unit::IsCharmed(), Unit::IsPet(), and Cell::VisitGridObjects().
Referenced by npc_boss_gothik_minion::npc_boss_gothik_minionAI::DamageTaken(), boss_thorim_start_npcs::boss_thorim_start_npcsAI::DamageTaken(), boss_emperor_dagran_thaurissan::boss_draganthaurissanAI::EnterCombat(), npc_mograine::npc_mograineAI::EnterCombat(), boss_grand_champion::boss_grand_championAI::EnterCombat(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::EnterCombat(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::EnterCombat(), boss_thorim_start_npcs::boss_thorim_start_npcsAI::EnterCombat(), boss_thorim_gauntlet_npcs::boss_thorim_gauntlet_npcsAI::EnterCombat(), boss_xt002::boss_xt002AI::EnterCombat(), boss_sartharion::boss_sartharionAI::EnterCombat(), boss_moroes::boss_moroesAI::EnterCombat(), npc_sindragosa_trash::npc_sindragosa_trashAI::EnterCombat(), boss_anubrekhan::boss_anubrekhanAI::EnterCombat(), boss_faerlina::boss_faerlinaAI::EnterCombat(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::EnterCombat(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::EnterCombat(), boss_void_reaver::boss_void_reaverAI::EnterCombat(), and npc_cork_gizelton::npc_cork_gizeltonAI::WaypointReached().
CanAlwaysSee()
bool Creature::CanAlwaysSee (WorldObject const * obj) const override protected virtual
Reimplemented from WorldObject.
Definition at line 1728 of file Creature.cpp.
 {
     if (IsAIEnabled && AI()->CanSeeAlways(obj))
         return true;
     return false;
 }
References AI(), and Unit::IsAIEnabled.
CanAssistTo()
bool Creature::CanAssistTo (const Unit * u, const Unit * enemy, bool checkfaction = true) const
Definition at line 2251 of file Creature.cpp.
 {
     // is it true?
     if (!HasReactState(REACT_AGGRESSIVE))
         return false;
     // we don't need help from zombies :)
     if (!IsAlive())
         return false;
     // Xinef: we cannot assist in evade mode
     if (IsInEvadeMode())
         return false;
     // pussywizard: or if enemy is in evade mode
     if (enemy->GetTypeId() == TYPEID_UNIT && enemy->ToCreature()->IsInEvadeMode())
         return false;
     // we don't need help from non-combatant ;)
     if (IsCivilian())
         return false;
     if (HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_IMMUNE_TO_NPC))
         return false;
     // skip fighting creature
     if (IsInCombat())
         return false;
     // only free creature
     if (GetCharmerOrOwnerGUID())
         return false;
     // only from same creature faction
     if (checkfaction)
     {
         if (GetFaction() != u->GetFaction())
             return false;
     }
     else
     {
         if (!IsFriendlyTo(u))
             return false;
     }
     // skip non hostile to caster enemy creatures
     if (!IsHostileTo(enemy))
         return false;
     // Check if can see the enemy
     if (!CanSeeOrDetect(enemy))
     {
         return false;
     }
     return true;
 }
References WorldObject::CanSeeOrDetect(), Unit::GetCharmerOrOwnerGUID(), Unit::GetFaction(), Object::GetTypeId(), Object::HasFlag(), HasReactState(), Unit::IsAlive(), IsCivilian(), Unit::IsFriendlyTo(), Unit::IsHostileTo(), Unit::IsInCombat(), IsInEvadeMode(), REACT_AGGRESSIVE, Object::ToCreature(), TYPEID_UNIT, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
Referenced by AssistDelayEvent::Execute(), Acore::CallOfHelpCreatureInRangeDo::operator()(), Acore::AnyAssistCreatureInRangeCheck::operator()(), and Acore::NearestAssistCreatureInCreatureRangeCheck::operator()().
CanCreatureAttack()
bool Creature::CanCreatureAttack (Unit const * victim, bool skipDistCheck = false) const
Definition at line 2387 of file Creature.cpp.
 {
     if (!victim->IsInMap(this))
         return false;
     if (!IsValidAttackTarget(victim))
         return false;
     if (!victim->isInAccessiblePlaceFor(this))
         return false;
     if (IsAIEnabled && !AI()->CanAIAttack(victim))
         return false;
     // pussywizard: we cannot attack in evade mode
     if (IsInEvadeMode())
         return false;
     // pussywizard: or if enemy is in evade mode
     if (victim->GetTypeId() == TYPEID_UNIT && victim->ToCreature()->IsInEvadeMode())
         return false;
     // cannot attack if is during 5 second grace period, unless being attacked
     if (m_respawnedTime && (sWorld->GetGameTime() - m_respawnedTime) < 5 && victim->getAttackers().empty())
     {
         return false;
     }
     if (!GetCharmerOrOwnerGUID().IsPlayer())
     {
         if (GetMap()->IsDungeon())
             return true;
         // pussywizard: don't check distance to home position if recently damaged (allow kiting away from spawnpoint!)
         // xinef: this should include taunt auras
         if (!isWorldBoss() && (GetLastDamagedTime() > sWorld->GetGameTime() || HasAuraType(SPELL_AURA_MOD_TAUNT)))
             return true;
     }
     if (skipDistCheck)
         return true;
     // xinef: added size factor for huge npcs
     float dist = std::min<float>(GetMap()->GetVisibilityRange() + GetObjectSize() * 2, 150.0f);
     if (Unit* unit = GetCharmerOrOwner())
         return victim->IsWithinDist(unit, dist);
     else
     {
         // to prevent creatures in air ignore attacks because distance is already too high...
         if (GetCreatureTemplate()->InhabitType & INHABIT_AIR)
             return victim->IsInDist2d(&m_homePosition, dist);
         else
             return victim->IsInDist(&m_homePosition, dist);
     }
 }
References AI(), Unit::getAttackers(), Unit::GetCharmerOrOwner(), Unit::GetCharmerOrOwnerGUID(), GetCreatureTemplate(), GetLastDamagedTime(), WorldObject::GetMap(), WorldObject::GetObjectSize(), Object::GetTypeId(), WorldObject::GetVisibilityRange(), Unit::HasAuraType(), INHABIT_AIR, Unit::IsAIEnabled, Unit::isInAccessiblePlaceFor(), Position::IsInDist(), Position::IsInDist2d(), IsInEvadeMode(), WorldObject::IsInMap(), Object::IsPlayer(), Unit::IsValidAttackTarget(), WorldObject::IsWithinDist(), isWorldBoss(), m_homePosition, m_respawnedTime, SPELL_AURA_MOD_TAUNT, sWorld, Object::ToCreature(), and TYPEID_UNIT.
Referenced by PetAI::_needToStop(), boss_hadronox::boss_hadronoxAI::AnyPlayerValid(), CanStartAttack(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustSummoned(), boss_twinemperorsAI::MoveInLineOfSight(), PetAI::SelectNextTarget(), ThreatContainer::selectNextVictim(), SelectVictim(), npc_pet_shaman_earth_elemental::UpdateAI(), and npc_pet_shaman_fire_elemental::UpdateAI().
CanEnterWater()
bool Creature::CanEnterWater () const override virtual
Implements Unit.
Definition at line 2972 of file Creature.cpp.
 {
     if (CanSwim())
         return true;
     return GetCreatureTemplate()->InhabitType & INHABIT_WATER;
 }
References CanSwim(), GetCreatureTemplate(), INHABIT_WATER, and CreatureTemplate::InhabitType.
Referenced by ConfusedMovementGenerator< T >::_InitSpecific(), RandomMovementGenerator< T >::_setRandomLocation(), Map::CanReachPositionAndGetValidCoords(), PathGenerator::CreateFilter(), and RefreshSwimmingFlag().
CanFly()
bool Creature::CanFly () const override virtual
Implements Unit.
Definition at line 3024 of file Creature.cpp.
 {
     if (Unit::IsFlying())
         return true;
     return GetCreatureTemplate()->InhabitType & INHABIT_AIR;
 }
References GetCreatureTemplate(), INHABIT_AIR, CreatureTemplate::InhabitType, and Unit::IsFlying().
Referenced by RandomMovementGenerator< T >::_setRandomLocation(), PathGenerator::BuildPolyPath(), CanStartAttack(), RandomMovementGenerator< T >::DoInitialize(), and LoadCreatureFromDB().
CanGeneratePickPocketLoot()
bool Creature::CanGeneratePickPocketLoot () const inline
Definition at line 218 of file Creature.h.
 { return lootPickPocketRestoreTime == 0 || lootPickPocketRestoreTime < time(nullptr); }
References lootPickPocketRestoreTime.
Referenced by Player::SendLoot().
CanHover()
bool Creature::CanHover () const inline
Definition at line 81 of file Creature.h.
 { return m_originalAnimTier & UNIT_BYTE1_FLAG_HOVER || IsHovering(); }
References Unit::IsHovering(), m_originalAnimTier, and UNIT_BYTE1_FLAG_HOVER.
Referenced by UpdateMovementFlags().
CanIgnoreFeignDeath()
bool Creature::CanIgnoreFeignDeath () const inline
Definition at line 257 of file Creature.h.
 { return (GetCreatureTemplate()->flags_extra & CREATURE_FLAG_EXTRA_IGNORE_FEIGN_DEATH) != 0; }
References CREATURE_FLAG_EXTRA_IGNORE_FEIGN_DEATH, and GetCreatureTemplate().
Referenced by _IsTargetAcceptable().
CanNotReachTarget()
bool Creature::CanNotReachTarget () const inline
Definition at line 309 of file Creature.h.
 { return m_cannotReachTarget; }
References m_cannotReachTarget.
Referenced by IsEvadingAttacks(), and Update().
CanPeriodicallyCallForAssistance()
bool Creature::CanPeriodicallyCallForAssistance () const private
Definition at line 3445 of file Creature.cpp.
 {
     if (!IsInCombat())
         return false;
     if (HasUnitState(UNIT_STATE_DIED | UNIT_STATE_POSSESSED))
         return false;
     if (!CanHaveThreatList())
         return false;
     if (IsSummon() && GetMap()->Instanceable())
         return false;
     return true;
 }
References Unit::CanHaveThreatList(), WorldObject::GetMap(), Unit::HasUnitState(), Unit::IsInCombat(), Unit::IsSummon(), UNIT_STATE_DIED, and UNIT_STATE_POSSESSED.
Referenced by Update().
CanStartAttack()
bool Creature::CanStartAttack (Unit const * u) const
Definition at line 1736 of file Creature.cpp.
 {
     if (IsCivilian())
         return false;
     // This set of checks is should be done only for creatures
     if ((HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC) && who->GetTypeId() != TYPEID_PLAYER) ||      // flag is valid only for non player characters
         (HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC) && who->GetTypeId() == TYPEID_PLAYER))         // immune to PC and target is a player, return false
     {
         return false;
     }
     if (Unit* owner = who->GetOwner())
         if (owner->GetTypeId() == TYPEID_PLAYER && HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC))     // immune to PC and target has player owner
             return false;
     // Do not attack non-combat pets
     if (who->GetTypeId() == TYPEID_UNIT && who->GetCreatureType() == CREATURE_TYPE_NON_COMBAT_PET)
         return false;
     if (!CanFly() && (GetDistanceZ(who) > CREATURE_Z_ATTACK_RANGE + m_CombatDistance))                    // too much Z difference, skip very costy vmap calculations here
         return false;
     if (!_IsTargetAcceptable(who))
         return false;
     // pussywizard: at this point we are either hostile to who or friendly to who->getAttackerForHelper()
     // pussywizard: if who is in combat and has an attacker, help him if the distance is right (help because who is hostile or help because attacker is friendly)
     bool assist = false;
     if (who->IsInCombat() && IsWithinDist(who, ATTACK_DISTANCE))
         if (Unit* victim = who->getAttackerForHelper())
             if (IsWithinDistInMap(victim, sWorld->getFloatConfig(CONFIG_CREATURE_FAMILY_ASSISTANCE_RADIUS)))
                 assist = true;
     if (!assist)
         if (IsNeutralToAll() || !IsWithinDistInMap(who, GetAggroRange(who) + m_CombatDistance, true, false)) // pussywizard: +m_combatDistance for turrets and similar
             return false;
     if (!CanCreatureAttack(who))
         return false;
     if (HasUnitState(UNIT_STATE_STUNNED))
         return false;
     return IsWithinLOSInMap(who);
 }
References _IsTargetAcceptable(), ATTACK_DISTANCE, CanCreatureAttack(), CanFly(), CONFIG_CREATURE_FAMILY_ASSISTANCE_RADIUS, CREATURE_TYPE_NON_COMBAT_PET, CREATURE_Z_ATTACK_RANGE, GetAggroRange(), Unit::getAttackerForHelper(), Unit::GetCreatureType(), WorldObject::GetDistanceZ(), Unit::GetOwner(), Object::GetTypeId(), Object::HasFlag(), Unit::HasUnitState(), IsCivilian(), Unit::IsInCombat(), Unit::IsNeutralToAll(), WorldObject::IsWithinDist(), WorldObject::IsWithinDistInMap(), WorldObject::IsWithinLOSInMap(), m_CombatDistance, sWorld, TYPEID_PLAYER, TYPEID_UNIT, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, and UNIT_STATE_STUNNED.
Referenced by CreatureAI::MoveInLineOfSight(), FollowerAI::MoveInLineOfSight(), npc_shay_leafrunner::npc_shay_leafrunnerAI::MoveInLineOfSight(), npc_escortAI::MoveInLineOfSight(), SmartAI::MoveInLineOfSight(), and Acore::NearestHostileUnitInAttackDistanceCheck::operator()().
CanSwim()
bool Creature::CanSwim () const override virtual
This method check the current flag/status of a creature and its inhabit type.
Pets should swim by default to properly follow the player NOTE: You can set the UNIT_FLAG_CANNOT_SWIM temporary to deny a creature to swim
Reimplemented from Unit.
Definition at line 2961 of file Creature.cpp.
 {
     if (Unit::CanSwim())
         return true;
     if (IsPet() || GetOwnerGUID().IsPlayer())
         return true;
     return false;
 }
References Unit::CanSwim(), Unit::GetOwnerGUID(), Unit::IsPet(), and Object::IsPlayer().
Referenced by PathGenerator::BuildPolyPath(), CanEnterWater(), PathGenerator::IsSwimmableSegment(), and UpdateMovementFlags().
CanWalk()
bool Creature::CanWalk () const inline
Definition at line 77 of file Creature.h.
 { return GetCreatureTemplate()->InhabitType & INHABIT_GROUND; }
References GetCreatureTemplate(), INHABIT_GROUND, and CreatureTemplate::InhabitType.
Referenced by ConfusedMovementGenerator< T >::_InitSpecific(), Map::CanReachPositionAndGetValidCoords(), and PathGenerator::CreateFilter().
Create()
bool Creature::Create (ObjectGuid::LowType guidlow, Map * map, uint32 phaseMask, uint32 Entry, uint32 vehId, float x, float y, float z, float ang, const CreatureData * data = nullptr)
Relocate before CreateFromProto, to initialize coords and allow returning correct zone id for selecting OutdoorPvP/Battlefield script
Need to be called after LoadCreaturesAddon - MOVEMENTFLAG_HOVER is set there
Definition at line 968 of file Creature.cpp.
 {
     ASSERT(map);
     SetMap(map);
     SetPhaseMask(phaseMask, false);
     CreatureTemplate const* cinfo = sObjectMgr->GetCreatureTemplate(Entry);
     if (!cinfo)
     {
         LOG_ERROR("sql.sql", "Creature::Create(): creature template (guidlow: %u, entry: %u) does not exist.", guidlow, Entry);
         return false;
     }
     Relocate(x, y, z, ang);
     if (!IsPositionValid())
     {
         LOG_ERROR("entities.unit", "Creature::Create(): given coordinates for creature (guidlow %d, entry %d) are not valid (X: %f, Y: %f, Z: %f, O: %f)", guidlow, Entry, x, y, z, ang);
         return false;
     }
     // area/zone id is needed immediately for ZoneScript::GetCreatureEntry hook before it is known which creature template to load (no model/scale available yet)
     PositionFullTerrainStatus terrainData;
     GetMap()->GetFullTerrainStatusForPosition(GetPhaseMask(), GetPositionX(), GetPositionY(), GetPositionZ(), DEFAULT_COLLISION_HEIGHT, terrainData);
     ProcessPositionDataChanged(terrainData);
     //oX = x;     oY = y;    dX = x;    dY = y;    m_moveTime = 0;    m_startMove = 0;
     if (!CreateFromProto(guidlow, Entry, vehId, data))
         return false;
     UpdateMovementFlags();
     switch (GetCreatureTemplate()->rank)
     {
         case CREATURE_ELITE_RARE:
             m_corpseDelay = sWorld->getIntConfig(CONFIG_CORPSE_DECAY_RARE);
             break;
         case CREATURE_ELITE_ELITE:
             m_corpseDelay = sWorld->getIntConfig(CONFIG_CORPSE_DECAY_ELITE);
             break;
         case CREATURE_ELITE_RAREELITE:
             m_corpseDelay = sWorld->getIntConfig(CONFIG_CORPSE_DECAY_RAREELITE);
             break;
         case CREATURE_ELITE_WORLDBOSS:
             // Xinef: Reduce corpse delay for bossess outside of instance
             if (!GetInstanceId())
                 m_corpseDelay = sWorld->getIntConfig(CONFIG_CORPSE_DECAY_ELITE) * 2;
             else
                 m_corpseDelay = sWorld->getIntConfig(CONFIG_CORPSE_DECAY_WORLDBOSS);
             break;
         default:
             m_corpseDelay = sWorld->getIntConfig(CONFIG_CORPSE_DECAY_NORMAL);
             break;
     }
     LoadCreaturesAddon();
     uint32 displayID = GetNativeDisplayId();
     CreatureModelInfo const* minfo = sObjectMgr->GetCreatureModelRandomGender(&displayID);
     if (minfo && !IsTotem())                               // Cancel load if no model defined or if totem
     {
         SetDisplayId(displayID);
         SetNativeDisplayId(displayID);
         SetByteValue(UNIT_FIELD_BYTES_0, 2, minfo->gender);
     }
     m_positionZ += GetHoverHeight();
     LastUsedScriptID = GetScriptId();
     if (IsSpiritHealer() || IsSpiritGuide() || (GetCreatureTemplate()->flags_extra & CREATURE_FLAG_EXTRA_GHOST_VISIBILITY))
     {
         m_serverSideVisibility.SetValue(SERVERSIDE_VISIBILITY_GHOST, GHOST_VISIBILITY_GHOST);
         m_serverSideVisibilityDetect.SetValue(SERVERSIDE_VISIBILITY_GHOST, GHOST_VISIBILITY_GHOST);
     }
     else if (cinfo->type_flags & CREATURE_TYPE_FLAG_VISIBLE_TO_GHOSTS) // Xinef: Add ghost visibility for ghost units
         m_serverSideVisibility.SetValue(SERVERSIDE_VISIBILITY_GHOST, GHOST_VISIBILITY_ALIVE | GHOST_VISIBILITY_GHOST);
     if (Entry == VISUAL_WAYPOINT)
         SetVisible(false);
     if (GetCreatureTemplate()->flags_extra & CREATURE_FLAG_EXTRA_IGNORE_PATHFINDING)
         AddUnitState(UNIT_STATE_IGNORE_PATHFINDING);
     return true;
 }
References Unit::AddUnitState(), ASSERT, CONFIG_CORPSE_DECAY_ELITE, CONFIG_CORPSE_DECAY_NORMAL, CONFIG_CORPSE_DECAY_RARE, CONFIG_CORPSE_DECAY_RAREELITE, CONFIG_CORPSE_DECAY_WORLDBOSS, CreateFromProto(), CREATURE_ELITE_ELITE, CREATURE_ELITE_RARE, CREATURE_ELITE_RAREELITE, CREATURE_ELITE_WORLDBOSS, CREATURE_FLAG_EXTRA_GHOST_VISIBILITY, CREATURE_FLAG_EXTRA_IGNORE_PATHFINDING, CREATURE_TYPE_FLAG_VISIBLE_TO_GHOSTS, DEFAULT_COLLISION_HEIGHT, Entry, CreatureModelInfo::gender, GetCreatureTemplate(), Map::GetFullTerrainStatusForPosition(), Unit::GetHoverHeight(), WorldObject::GetInstanceId(), WorldObject::GetMap(), Unit::GetNativeDisplayId(), WorldObject::GetPhaseMask(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GetScriptId(), GHOST_VISIBILITY_ALIVE, GHOST_VISIBILITY_GHOST, Position::IsPositionValid(), Unit::IsSpiritGuide(), Unit::IsSpiritHealer(), Unit::IsTotem(), WorldObject::LastUsedScriptID, LoadCreaturesAddon(), LOG_ERROR, m_corpseDelay, Position::m_positionZ, WorldObject::m_serverSideVisibility, WorldObject::m_serverSideVisibilityDetect, Unit::ProcessPositionDataChanged(), Position::Relocate(), SERVERSIDE_VISIBILITY_GHOST, Object::SetByteValue(), SetDisplayId(), WorldObject::SetMap(), Unit::SetNativeDisplayId(), Unit::SetPhaseMask(), FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::SetValue(), Unit::SetVisible(), sObjectMgr, sWorld, CreatureTemplate::type_flags, UNIT_FIELD_BYTES_0, UNIT_STATE_IGNORE_PATHFINDING, UpdateMovementFlags(), VISUAL_WAYPOINT, G3D::x, G3D::y, and G3D::z.
Referenced by Battleground::AddCreature(), debug_commandscript::HandleDebugSpawnVehicleCommand(), npc_commandscript::HandleNpcAddCommand(), wp_commandscript::HandleWpModifyCommand(), wp_commandscript::HandleWpShowCommand(), LoadCreatureFromDB(), Battlefield::SpawnCreature(), and Map::SummonCreature().
CreateFromProto()
bool Creature::CreateFromProto (ObjectGuid::LowType guidlow, uint32 Entry, uint32 vehId, const CreatureData * data = nullptr) protected
Definition at line 1466 of file Creature.cpp.
 {
     SetZoneScript();
     if (GetZoneScript() && data)
     {
         Entry = GetZoneScript()->GetCreatureEntry(guidlow, data);
         if (!Entry)
             return false;
     }
     CreatureTemplate const* normalInfo = sObjectMgr->GetCreatureTemplate(Entry);
     if (!normalInfo)
     {
         LOG_ERROR("sql.sql", "Creature::CreateFromProto(): creature template (guidlow: %u, entry: %u) does not exist.", guidlow, Entry);
         return false;
     }
     SetOriginalEntry(Entry);
     Object::_Create(guidlow, Entry, (vehId || normalInfo->VehicleId) ? HighGuid::Vehicle : HighGuid::Unit);
     // Xinef: select proper vehicle id
     if (!vehId)
     {
         CreatureTemplate const* cinfo = normalInfo;
         for (uint8 diff = uint8(GetMap()->GetSpawnMode()); diff > 0 && !IsPet();)
         {
             // we already have valid Map pointer for current creature!
             if (cinfo->DifficultyEntry[diff - 1])
             {
                 cinfo = sObjectMgr->GetCreatureTemplate(normalInfo->DifficultyEntry[diff - 1]);
                 if (cinfo && cinfo->VehicleId)
                     break;                                      // template found
                 // check and reported at startup, so just ignore (restore normalInfo)
                 cinfo = normalInfo;
             }
             // for instances heroic to normal, other cases attempt to retrieve previous difficulty
             if (diff >= RAID_DIFFICULTY_10MAN_HEROIC && GetMap()->IsRaid())
                 diff -= 2;                                      // to normal raid difficulty cases
             else
                 --diff;
         }
         if (cinfo->VehicleId)
             CreateVehicleKit(cinfo->VehicleId, (cinfo->VehicleId != normalInfo->VehicleId ? cinfo->Entry : normalInfo->Entry));
     }
     else
         CreateVehicleKit(vehId, Entry);
     if (!UpdateEntry(Entry, data))
         return false;
     return true;
 }
References Object::_Create(), Unit::CreateVehicleKit(), diff(), CreatureTemplate::DifficultyEntry, CreatureTemplate::Entry, Entry, ZoneScript::GetCreatureEntry(), WorldObject::GetMap(), WorldObject::GetZoneScript(), Unit::IsPet(), Map::IsRaid(), LOG_ERROR, RAID_DIFFICULTY_10MAN_HEROIC, SetOriginalEntry(), WorldObject::SetZoneScript(), sObjectMgr, Unit, UpdateEntry(), Vehicle, and CreatureTemplate::VehicleId.
Referenced by Create().
DeleteFromDB()
void Creature::DeleteFromDB () virtual
Reimplemented in Pet.
Definition at line 1685 of file Creature.cpp.
 {
     if (!m_spawnId)
     {
         LOG_ERROR("entities.unit", "Trying to delete not saved creature: %s", GetGUID().ToString().c_str());
         return;
     }
     GetMap()->RemoveCreatureRespawnTime(m_spawnId);
     sObjectMgr->DeleteCreatureData(m_spawnId);
     WorldDatabaseTransaction trans = WorldDatabase.BeginTransaction();
     WorldDatabasePreparedStatement* stmt = WorldDatabase.GetPreparedStatement(WORLD_DEL_CREATURE);
     stmt->setUInt32(0, m_spawnId);
     trans->Append(stmt);
     stmt = WorldDatabase.GetPreparedStatement(WORLD_DEL_CREATURE_ADDON);
     stmt->setUInt32(0, m_spawnId);
     trans->Append(stmt);
     stmt = WorldDatabase.GetPreparedStatement(WORLD_DEL_GAME_EVENT_CREATURE);
     stmt->setUInt32(0, m_spawnId);
     trans->Append(stmt);
     stmt = WorldDatabase.GetPreparedStatement(WORLD_DEL_GAME_EVENT_MODEL_EQUIP);
     stmt->setUInt32(0, m_spawnId);
     trans->Append(stmt);
     WorldDatabase.CommitTransaction(trans);
 }
References Object::GetGUID(), WorldObject::GetMap(), LOG_ERROR, m_spawnId, Map::RemoveCreatureRespawnTime(), PreparedStatementBase::setUInt32(), sObjectMgr, Position::ToString(), WORLD_DEL_CREATURE, WORLD_DEL_CREATURE_ADDON, WORLD_DEL_GAME_EVENT_CREATURE, WORLD_DEL_GAME_EVENT_MODEL_EQUIP, and WorldDatabase.
Referenced by npc_commandscript::HandleNpcDeleteCommand(), and wp_commandscript::HandleWpShowCommand().
DespawnOnEvade()
void Creature::DespawnOnEvade ()
Definition at line 1953 of file Creature.cpp.
 {
     SetVisible(false);
     AI()->SummonedCreatureDespawnAll();
     RemoveEvadeAuras();
     float x, y, z, o;
     GetRespawnPosition(x, y, z, &o);
     SetHomePosition(x, y, z, o);
     SetPosition(x, y, z, o);
     if (IsFalling())
     {
         RemoveUnitMovementFlag(MOVEMENTFLAG_FALLING);
     }
     StopMoving();
 }
References AI(), GetRespawnPosition(), Unit::IsFalling(), MOVEMENTFLAG_FALLING, Unit::RemoveEvadeAuras(), Unit::RemoveUnitMovementFlag(), SetHomePosition(), SetPosition(), Unit::SetVisible(), Unit::StopMoving(), CreatureAI::SummonedCreatureDespawnAll(), G3D::x, G3D::y, and G3D::z.
Referenced by CreatureAI::EnterEvadeMode().
DespawnOrUnsummon() [1/2]
void Creature::DespawnOrUnsummon (Milliseconds msTimeToDespawn, Seconds forcedRespawnTimer)
Definition at line 1945 of file Creature.cpp.
 {
     if (TempSummon* summon = this->ToTempSummon())
         summon->UnSummon(msTimeToDespawn.count());
     else
         ForcedDespawn(msTimeToDespawn.count(), forcedRespawnTimer);
 }
References ForcedDespawn(), and Unit::ToTempSummon().
Referenced by npc_mograine::npc_mograineAI::AshbringerEvent(), spell_the_lich_king_shadow_trap_periodic::spell_the_lich_king_shadow_trap_periodic_SpellScript::CheckTargetCount(), npc_simone::npc_simoneAI::CorpseRemoved(), boss_headless_horseman_head::boss_headless_horseman_headAI::DamageTaken(), npc_terenas_menethil::npc_terenas_menethilAI::DamageTaken(), npc_power_spark::npc_power_sparkAI::DamageTaken(), boss_freya::boss_freyaAI::DamageTaken(), boss_hodir::boss_hodirAI::DamageTaken(), npc_tiger_matriarch::npc_tiger_matriarchAI::DamageTaken(), MotionTransport::DelayedTeleportTransport(), SummonList::DespawnAll(), SummonList::DespawnEntry(), brann_bronzebeard::brann_bronzebeardAI::DespawnHeads(), spell_rotface_unstable_ooze_explosion_suicide::spell_rotface_unstable_ooze_explosion_suicide_AuraScript::DespawnSelf(), Vehicle::Dismiss(), npc_icc_ice_sphere::npc_icc_ice_sphereAI::DoAction(), npc_ulduar_toasty_fire::npc_ulduar_toasty_fireAI::DoAction(), npc_ball_of_flame::npc_ball_of_flameAI::DoAction(), npc_saurfang_event::npc_saurfang_eventAI::DoAction(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::DoAction(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::DoAction(), npc_bone_spike::npc_bone_spikeAI::DoAction(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::DoAction(), npc_terenas_menethil::npc_terenas_menethilAI::DoAction(), boss_algalon_the_observer::boss_algalon_the_observerAI::DoAction(), boss_infinite_corruptor::boss_infinite_corruptorAI::DoAction(), npc_twilight_summon::npc_twilight_summonAI::DoAction(), npc_snobold_vassal::npc_snobold_vassalAI::DoAction(), npc_living_mojo::npc_living_mojoAI::DoAction(), boss_kelthuzad_minion::boss_kelthuzad_minionAI::DoAction(), npc_spark_of_ionar::npc_spark_of_ionarAI::DoAction(), npc_molten_golem::npc_molten_golemAI::DoAction(), npc_auriaya_feral_defender::npc_auriaya_feral_defenderAI::DoAction(), boss_thorim_sif::boss_thorim_sifAI::DoAction(), adyen_the_lightbringer::adyen_the_lightbringerAI::DoAction(), anchorite_karja::anchorite_karjaAI::DoAction(), exarch_orelis::exarch_orelisAI::DoAction(), Spell::EffectScriptEffect(), Spell::EffectTameCreature(), boss_rend_blackhand::boss_rend_blackhandAI::EnterEvadeMode(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::EnterEvadeMode(), boss_entropius::boss_entropiusAI::EnterEvadeMode(), boss_arlokk::boss_arlokkAI::EnterEvadeMode(), npc_hallows_end_soh::npc_hallows_end_sohAI::EnterEvadeMode(), boss_black_knight::boss_black_knightAI::EnterEvadeMode(), npc_toc_pet_warlock::npc_toc_pet_warlockAI::EnterEvadeMode(), npc_toc_pet_hunter::npc_toc_pet_hunterAI::EnterEvadeMode(), npc_fel_infernal::npc_fel_infernalAI::EnterEvadeMode(), npc_mistress_of_pain::npc_mistress_of_painAI::EnterEvadeMode(), npc_phantom_hallucination::npc_phantom_hallucinationAI::EnterEvadeMode(), npc_inner_demon::npc_inner_demonAI::EnterEvadeMode(), boss_ahune::boss_ahuneAI::EnterEvadeMode(), boss_nazan::boss_nazanAI::EnterEvadeMode(), boss_vazruden::boss_vazrudenAI::EnterEvadeMode(), ForcedDespawnDelayEvent::Execute(), VehicleDespawnEvent::Execute(), DelayedCastEvent::Execute(), EoEDrakeEnterVehicleEvent::Execute(), SuckBackEvent::Execute(), npc_shay_leafrunner::npc_shay_leafrunnerAI::FailQuest(), npc_hallows_end_soh::npc_hallows_end_sohAI::FinishEvent(), spell_gen_despawn_self::HandleDummy(), spell_item_lil_xt::HandleDummy(), spell_q12096_q12092_dummy::spell_q12096_q12092_dummy_SpellScript::HandleDummy(), spell_q12096_q12092_bark::spell_q12096_q12092_bark_SpellScript::HandleDummy(), spell_item_complete_raptor_capture::HandleDummy(), spell_item_rocket_chicken::HandleDummyTick(), spell_dtk_raise_dead::spell_dtk_raise_dead_AuraScript::HandleEffectRemove(), spell_q11919_q11940_drake_hunt::spell_q11919_q11940_drake_hunt_AuraScript::HandleEffectRemove(), AuraEffect::HandlePeriodicTriggerSpellAuraTick(), spell_putricide_eat_ooze::spell_putricide_eat_ooze_SpellScript::HandleScript(), spell_rotface_little_ooze_combine::spell_rotface_little_ooze_combine_SpellScript::HandleScript(), spell_rotface_large_ooze_combine::spell_rotface_large_ooze_combine_SpellScript::HandleScript(), spell_rotface_large_ooze_buff_combine::spell_rotface_large_ooze_buff_combine_SpellScript::HandleScript(), spell_shredder_delivery::spell_shredder_delivery_SpellScript::HandleScript(), spell_q12690_burst_at_the_seams::HandleScript(), spell_illidan_cage_trap::spell_illidan_cage_trap_SpellScript::HandleScriptEffect(), spell_winter_veil_racer_slam_hit::spell_winter_veil_racer_slam_hit_SpellScript::HandleScriptEffect(), spell_q11065_wrangle_some_aether_rays_aura::if(), boss_twilight_corrupter::boss_twilight_corrupterAI::InitializeAI(), npc_preparations_for_war_vehicle::npc_preparations_for_war_vehicleAI::InitializeAI(), Guardian::InitStatsForLevel(), npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::IsSummonedBy(), npc_putricide_oozeAI::IsSummonedBy(), npc_ranshalla::npc_ranshallaAI::JustDidDialogueStep(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::JustDied(), npc_zulian_prowler::npc_zulian_prowlerAI::JustDied(), npc_belnistrasz::npc_belnistraszAI::JustDied(), npc_living_inferno::npc_living_infernoAI::JustDied(), npc_memory::npc_memoryAI::JustDied(), npc_argent_soldier::npc_argent_soldierAI::JustDied(), npc_toc5_grand_champion_minion::npc_toc5_grand_champion_minionAI::JustDied(), npc_fel_infernal::npc_fel_infernalAI::JustDied(), npc_mistress_of_pain::npc_mistress_of_painAI::JustDied(), npc_dark_nucleus::npc_dark_nucleusAI::JustDied(), npc_little_ooze::npc_little_oozeAI::JustDied(), npc_big_ooze::npc_big_oozeAI::JustDied(), npc_ice_tomb::npc_ice_tombAI::JustDied(), npc_eoe_wyrmrest_skytalon::npc_eoe_wyrmrest_skytalonAI::JustDied(), npc_ulduar_saronite_animus::npc_ulduar_saronite_animusAI::JustDied(), npc_ichor_globule::npc_ichor_globuleAI::JustDied(), npc_vh_void_sentry::npc_vh_void_sentryAI::JustDied(), npc_thassarian2::npc_thassarian2AI::JustDied(), npc_q24545_vegard::npc_q24545_vegardAI::JustDied(), npc_blessed_banner::npc_blessed_bannerAI::JustDied(), boss_ahune::boss_ahuneAI::JustDied(), npc_ahune_frozen_core::npc_ahune_frozen_coreAI::JustDied(), boss_warbringer_omrogg::boss_warbringer_omroggAI::JustDied(), socrethar::socretharAI::JustDied(), npc_frost_tomb::npc_frost_tombAI::JustDied(), boss_dorothee::boss_dorotheeAI::JustReachedHome(), boss_kelthuzad_minion::boss_kelthuzad_minionAI::JustReachedHome(), npc_precious::npc_preciousAI::JustReachedHome(), boss_rend_blackhand::boss_rend_blackhandAI::JustSummoned(), boss_kiljaeden::boss_kiljaedenAI::JustSummoned(), npc_medivh_bm::npc_medivh_bmAI::JustSummoned(), boss_gal_darah::boss_gal_darahAI::JustSummoned(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustSummoned(), boss_professor_putricide::boss_professor_putricideAI::JustSummoned(), boss_rotface::boss_rotfaceAI::JustSummoned(), boss_the_lich_king::boss_the_lich_kingAI::JustSummoned(), npc_risen_archmage::npc_risen_archmageAI::JustSummoned(), npc_gluttonous_abomination::npc_gluttonous_abominationAI::JustSummoned(), boss_malygos::boss_malygosAI::JustSummoned(), npc_tiger_matriarch::npc_tiger_matriarchAI::KilledUnit(), npc_brew_bubble::npc_brew_bubbleAI::MoveInLineOfSight(), npc_khunok_the_behemoth::npc_khunok_the_behemothAI::MoveInLineOfSight(), npc_captured_beryl_sorcerer::npc_captured_beryl_sorcererAI::MoveInLineOfSight(), FollowerAI::MovementInform(), npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI::MovementInform(), npc_spirit_shade::npc_spirit_shadeAI::MovementInform(), npc_forest_frog::npc_forest_frogAI::MovementInform(), npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI::MovementInform(), npc_troll_volunteer::npc_troll_volunteerAI::MovementInform(), boss_grand_champion::boss_grand_championAI::MovementInform(), npc_concentrated_ball::npc_concentrated_ballAI::MovementInform(), npc_darnavan::npc_darnavanAI::MovementInform(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::MovementInform(), npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI::MovementInform(), npc_scarlet_ghoul::npc_scarlet_ghoulAI::MovementInform(), npc_injured_7th_legion_soldier::npc_injured_7th_legion_soldierAI::MovementInform(), npc_balance_of_light_and_shadow::npc_balance_of_light_and_shadowAI::MovementInform(), npc_ball_of_flame::npc_ball_of_flameAI::MovementInform(), npc_assembly_lightning::npc_assembly_lightningAI::MovementInform(), npc_xt002_scrapbot::npc_xt002_scrapbotAI::MovementInform(), npc_released_offspring_harkoa::npc_released_offspring_harkoaAI::MovementInform(), npc_wounded_skirmisher::npc_wounded_skirmisherAI::MovementInform(), npc_attracted_reef_bull::npc_attracted_reef_bullAI::MovementInform(), npc_image_of_medivh::npc_image_of_medivhAI::NextStep(), npc_lk_spirit_bomb::npc_lk_spirit_bombAI::npc_lk_spirit_bombAI(), BattlefieldWG::OnCreatureCreate(), instance_dire_maul::instance_dire_maul_InstanceMapScript::OnCreatureCreate(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::OnCreatureCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), instance_sethekk_halls::instance_sethekk_halls_InstanceMapScript::OnCreatureCreate(), boss_yoggsaron_descend_portal::OnGossipHello(), go_scourge_enclosure::OnGossipHello(), go_jotunheim_cage::OnGossipHello(), npc_ulduar_keeper::OnGossipSelect(), npc_pet_gen_argent_pony_bridle::OnGossipSelect(), npc_grandmother::OnGossipSelect(), npc_adventurous_dwarf::OnGossipSelect(), npc_natrualist_bite::OnGossipSelect(), spell_kaelthas_flame_strike::spell_kaelthas_flame_strike_AuraScript::OnRemove(), npc_valithria_portal::npc_valithria_portalAI::OnSpellClick(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath(), FrostwingGauntletRespawner::operator()(), ValithriaDespawner::operator()(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::PassengerBoarded(), npc_ulduar_vx001::npc_ulduar_vx001AI::PassengerBoarded(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::PassengerBoarded(), npc_eoe_wyrmrest_skytalon::npc_eoe_wyrmrest_skytalonAI::PassengerBoarded(), npc_oculus_drake::npc_oculus_drakeAI::PassengerBoarded(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::RemoveAll(), boss_gyth::boss_gythAI::Reset(), boss_servant_quarters::boss_servant_quartersAI::Reset(), npc_image_of_medivh::npc_image_of_medivhAI::Reset(), npc_singularity::npc_singularityAI::Reset(), boss_infinite_corruptor::boss_infinite_corruptorAI::Reset(), boss_mal_ganis::boss_mal_ganisAI::Reset(), npc_time_rift::npc_time_riftAI::Reset(), npc_xerestrasza::npc_xerestraszaAI::Reset(), npc_raging_spirit::npc_raging_spiritAI::Reset(), npc_assembly_lightning::npc_assembly_lightningAI::Reset(), npc_xt002_pummeller::npc_xt002_pummellerAI::Reset(), npc_xt002_life_spark::npc_xt002_life_sparkAI::Reset(), npc_oscillating_frequency_scanner_master_bunny::npc_oscillating_frequency_scanner_master_bunnyAI::Reset(), kaylaan_the_lost::kaylaan_the_lostAI::ResetDeathblowEvent(), npc_simon_bunny::npc_simon_bunnyAI::ResetNode(), NPCStaveQuestAI::RevealForm(), spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript::SelectTarget(), npc_frost_sphere::npc_frost_sphereAI::SpellHit(), npc_ulduar_flames_spread::npc_ulduar_flames_spreadAI::SpellHit(), npc_captured_rageclaw::npc_captured_rageclawAI::SpellHit(), boss_headless_horseman_pumpkin::boss_headless_horseman_pumpkinAI::SpellHit(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::SpellHit(), npc_vics_flying_machine::npc_vics_flying_machineAI::SpellHit(), npc_wounded_skirmisher::npc_wounded_skirmisherAI::SpellHit(), npc_drakuru_shackles::npc_drakuru_shacklesAI::SpellHit(), boss_magus_telestra::boss_magus_telestraAI::SpellHit(), npc_iron_watcher::npc_iron_watcherAI::SpellHit(), npc_aged_dying_ancient_kodo::npc_aged_dying_ancient_kodoAI::SpellHit(), npc_living_constellation::npc_living_constellationAI::SpellHit(), npc_midsummer_torch_target::npc_midsummer_torch_targetAI::SpellHit(), boss_headless_horseman_head::boss_headless_horseman_headAI::SpellHitTarget(), npc_vengeful_shade::npc_vengeful_shadeAI::SpellHitTarget(), npc_q24545_lich_king::npc_q24545_lich_kingAI::SpellHitTarget(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::SummonChannelers(), npc_artruis_the_hearthless::npc_artruis_the_hearthlessAI::SummonedCreatureDies(), npc_creature_generator_akama::npc_creature_generator_akamaAI::SummonedCreatureDies(), boss_vexallus::boss_vexallusAI::SummonedCreatureDies(), npc_artruis_the_hearthless::npc_artruis_the_hearthlessAI::SummonsAction(), npc_drakuru_shackles::npc_drakuru_shacklesAI::UnlockRageclaw(), VehicleAI::UpdateAI(), npc_escortAI::UpdateAI(), boss_victor_nefarius::boss_victor_nefariusAI::UpdateAI(), npc_kernobee::npc_kernobeeAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_madrigosa::npc_madrigosaAI::UpdateAI(), boss_kalec::boss_kalecAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), npc_dark_iron_attack_mole_machine::npc_dark_iron_attack_mole_machineAI::UpdateAI(), npc_brew_bubble::npc_brew_bubbleAI::UpdateAI(), npc_love_in_air_snivel_real::npc_love_in_air_snivel_realAI::UpdateAI(), npc_time_rift::npc_time_riftAI::UpdateAI(), npc_belnistrasz::npc_belnistraszAI::UpdateAI(), boss_eye_of_cthun::eye_of_cthunAI::UpdateAI(), npc_spitelashes::npc_spitelashesAI::UpdateAI(), npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI::UpdateAI(), npc_depth_charge::npc_depth_chargeAI::UpdateAI(), npc_draenei_survivor::npc_draenei_survivorAI::UpdateAI(), npc_stillpine_capitive::npc_stillpine_capitiveAI::UpdateAI(), npc_shay_leafrunner::npc_shay_leafrunnerAI::UpdateAI(), npc_giant_spotlight::npc_giant_spotlightAI::UpdateAI(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::UpdateAI(), npc_fos_corrupted_soul_fragment::npc_fos_corrupted_soul_fragmentAI::UpdateAI(), boss_drakkari_elemental::boss_drakkari_elementalAI::UpdateAI(), npc_kinetic_bomb::npc_kinetic_bombAI::UpdateAI(), npc_vengeful_shade::npc_vengeful_shadeAI::UpdateAI(), npc_bone_spike::npc_bone_spikeAI::UpdateAI(), npc_ice_tomb::npc_ice_tombAI::UpdateAI(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::UpdateAI(), npc_lk_spirit_bomb::npc_lk_spirit_bombAI::UpdateAI(), npc_valithria_cloud::npc_valithria_cloudAI::UpdateAI(), npc_blistering_zombie::npc_blistering_zombieAI::UpdateAI(), npc_impaling_spear::npc_impaling_spearAI::UpdateAI(), npc_vortex_ride::npc_vortex_rideAI::UpdateAI(), npc_power_spark::npc_power_sparkAI::UpdateAI(), npc_oculus_drake::npc_oculus_drakeAI::UpdateAI(), boss_algalon_the_observer::boss_algalon_the_observerAI::UpdateAI(), boss_freya_lifebinder::boss_freya_lifebinderAI::UpdateAI(), boss_freya_healthy_spore::boss_freya_healthy_sporeAI::UpdateAI(), boss_freya_summons::boss_freya_summonsAI::UpdateAI(), boss_freya_nature_bomb::boss_freya_nature_bombAI::UpdateAI(), npc_ulduar_flash_freeze::npc_ulduar_flash_freezeAI::UpdateAI(), boss_kologarn_eyebeam::boss_kologarn_eyebeamAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_ulduar_magnetic_core::npc_ulduar_magnetic_coreAI::UpdateAI(), npc_ulduar_bot_summon_trigger::npc_ulduar_bot_summon_triggerAI::UpdateAI(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::UpdateAI(), boss_thorim::boss_thorimAI::UpdateAI(), boss_thorim_sif::boss_thorim_sifAI::UpdateAI(), boss_skadi_grauf::boss_skadi_graufAI::UpdateAI(), npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::UpdateAI(), npc_azure_saboteur::npc_azure_saboteurAI::UpdateAI(), npc_lurgglbr::npc_lurgglbrAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_preparations_for_war_vehicle::npc_preparations_for_war_vehicleAI::UpdateAI(), npc_minigob_manabonk::npc_minigob_manabonkAI::UpdateAI(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::UpdateAI(), npc_lake_frog::npc_lake_frogAI::UpdateAI(), npc_lord_arete::npc_lord_areteAI::UpdateAI(), npc_infra_green_bomber_generic::npc_infra_green_bomber_genericAI::UpdateAI(), npc_blessed_banner::npc_blessed_bannerAI::UpdateAI(), npc_feedin_da_goolz::npc_feedin_da_goolzAI::UpdateAI(), npc_crusade_recruit::npc_crusade_recruitAI::UpdateAI(), npc_voidtraveler::npc_voidtravelerAI::UpdateAI(), npc_corki::npc_corkiAI::UpdateAI(), socrethar::socretharAI::UpdateAI(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::UpdateAI(), npc_pet_gen_target_following_bomb::UpdateAI(), npc_pet_gen_imp_in_a_bottle::UpdateAI(), npc_pet_gen_fetch_ball::UpdateAI(), npc_artorius::npc_artoriusAI::UpdateAI(), npc_simone::npc_simoneAI::UpdateAI(), npc_nelson::npc_nelsonAI::UpdateAI(), npc_franklin::npc_franklinAI::UpdateAI(), npc_elder_clearwater::npc_elder_clearwaterAI::UpdateAI(), npc_riggle_bassbait::npc_riggle_bassbaitAI::UpdateAI(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::UpdateAI(), npc_ichor_globule::npc_ichor_globuleAI::UpdateAI(), FollowerAI::UpdateAI(), npc_brunnhildar_prisoner::npc_brunnhildar_prisonerAI::UpdateAI(), SmartAI::UpdateDespawn(), npc_rinji::npc_rinjiAI::UpdateEscortAI(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI(), SmartAI::UpdatePath(), npc_daphne_stilwell::npc_daphne_stilwellAI::WaypointReached(), npc_apothecary_hanes::npc_Apothecary_HanesAI::WaypointReached(), and npc_plaguehound_tracker::npc_plaguehound_trackerAI::WaypointReached().
DespawnOrUnsummon() [2/2]
void Creature::DespawnOrUnsummon (uint32 msTimeToDespawn = 0) inline
Definition at line 271 of file Creature.h.
 { DespawnOrUnsummon(Milliseconds(msTimeToDespawn), 0s); };
References DespawnOrUnsummon().
Referenced by DespawnOrUnsummon().
DisappearAndDie()
void Creature::DisappearAndDie ()
Definition at line 279 of file Creature.cpp.
 {
     DestroyForNearbyPlayers();
     //SetVisibility(VISIBILITY_OFF);
     //ObjectAccessor::UpdateObjectVisibility(this);
     if (IsAlive())
         setDeathState(JUST_DIED, true);
     RemoveCorpse(false, true);
 }
References WorldObject::DestroyForNearbyPlayers(), Unit::IsAlive(), JUST_DIED, RemoveCorpse(), and setDeathState().
Referenced by npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI::EnterEvadeMode(), npc_marzon_silent_blade::npc_marzon_silent_bladeAI::EnterEvadeMode(), npc_dark_iron_guzzler::npc_dark_iron_guzzlerAI::FindNextKeg(), Battlefield::HideNpc(), npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::MovementInform(), instance_blackrock_spire::instance_blackrock_spireMapScript::OnCreatureCreate(), go_ulduar_tower::OnDestroyed(), go_dragonflayer_cage::OnGossipHello(), boss_nightbane::boss_nightbaneAI::Reset(), npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::UpdateAI(), npc_janalai_hatcher::npc_janalai_hatcherAI::UpdateAI(), npc_janalai_hatchling::npc_janalai_hatchlingAI::UpdateAI(), npc_amanitar_mushrooms::npc_amanitar_mushroomsAI::UpdateAI(), npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::UpdateAI(), npc_swarm_scarab::npc_swarm_scarabAI::UpdateAI(), npc_beryl_sorcerer::npc_beryl_sorcererAI::UpdateAI(), npc_venture_co_straggler::npc_venture_co_stragglerAI::UpdateAI(), npc_tyrion_spybot::npc_tyrion_spybotAI::UpdateAI(), and npc_emily::npc_emilyAI::WaypointReached().
DoFleeToGetAssistance()
void Creature::DoFleeToGetAssistance ()
Definition at line 898 of file Creature.cpp.
 {
     if (!GetVictim())
         return;
     if (HasAuraType(SPELL_AURA_PREVENTS_FLEEING))
         return;
     float radius = sWorld->getFloatConfig(CONFIG_CREATURE_FAMILY_FLEE_ASSISTANCE_RADIUS);
     if (radius > 0)
     {
         Creature* creature = nullptr;
         Acore::NearestAssistCreatureInCreatureRangeCheck u_check(this, GetVictim(), radius);
         Acore::CreatureLastSearcher<Acore::NearestAssistCreatureInCreatureRangeCheck> searcher(this, creature, u_check);
         Cell::VisitGridObjects(this, searcher, radius);
         SetNoSearchAssistance(true);
         UpdateSpeed(MOVE_RUN, false);
         if (!creature)
             //SetFeared(true, GetVictim()->GetGUID(), 0, sWorld->getIntConfig(CONFIG_CREATURE_FAMILY_FLEE_DELAY));
             //TODO: use 31365
             SetControlled(true, UNIT_STATE_FLEEING);
         else
             GetMotionMaster()->MoveSeekAssistance(creature->GetPositionX(), creature->GetPositionY(), creature->GetPositionZ());
     }
 }
References CONFIG_CREATURE_FAMILY_FLEE_ASSISTANCE_RADIUS, Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetVictim(), Unit::HasAuraType(), MOVE_RUN, MotionMaster::MoveSeekAssistance(), Unit::SetControlled(), SetNoSearchAssistance(), SPELL_AURA_PREVENTS_FLEEING, sWorld, UNIT_STATE_FLEEING, Unit::UpdateSpeed(), and Cell::VisitGridObjects().
Referenced by npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::DamageTaken(), and SmartScript::ProcessAction().
FocusTarget()
void Creature::FocusTarget (Spell const * focusSpell, WorldObject const * target)
Definition at line 3294 of file Creature.cpp.
 {
     // already focused
     if (_focusSpell)
         return;
     _focusSpell = focusSpell;
     SetGuidValue(UNIT_FIELD_TARGET, this == target ? ObjectGuid::Empty : target->GetGUID());
     if (focusSpell->GetSpellInfo()->HasAttribute(SPELL_ATTR5_AI_DOESNT_FACE_TARGET))
         AddUnitState(UNIT_STATE_ROTATING);
     // Set serverside orientation if needed (needs to be after attribute check)
     if (this == target && (movespline->Finalized() || GetMotionMaster()->GetCurrentMovementGeneratorType() == CHASE_MOTION_TYPE))
         SetFacingTo(GetOrientation());
     else
         SetInFront(target);
 }
References _focusSpell, Unit::AddUnitState(), CHASE_MOTION_TYPE, ObjectGuid::Empty, Movement::MoveSpline::Finalized(), Object::GetGUID(), Unit::GetMotionMaster(), Position::GetOrientation(), Spell::GetSpellInfo(), SpellInfo::HasAttribute(), Unit::movespline, Unit::SetFacingTo(), Object::SetGuidValue(), Unit::SetInFront(), SPELL_ATTR5_AI_DOESNT_FACE_TARGET, UNIT_FIELD_TARGET, and UNIT_STATE_ROTATING.
Referenced by Spell::prepare().
ForcedDespawn()
void Creature::ForcedDespawn (uint32 timeMSToDespawn = 0, Seconds forcedRespawnTimer = 0s) private
Definition at line 1923 of file Creature.cpp.
 {
     if (timeMSToDespawn)
     {
         ForcedDespawnDelayEvent* pEvent = new ForcedDespawnDelayEvent(*this, forceRespawnTimer);
         m_Events.AddEvent(pEvent, m_Events.CalculateTime(timeMSToDespawn));
         return;
     }
     if (IsAlive())
         setDeathState(JUST_DIED, true);
     // Xinef: set new respawn time, ignore corpse decay time...
     RemoveCorpse(true);
     if (forceRespawnTimer > Seconds::zero())
     {
         m_respawnTime = time(nullptr) + forceRespawnTimer.count();
         m_respawnDelay = forceRespawnTimer.count();
     }
 }
References EventProcessor::AddEvent(), EventProcessor::CalculateTime(), Unit::IsAlive(), JUST_DIED, Unit::m_Events, m_respawnDelay, m_respawnTime, RemoveCorpse(), setDeathState(), and G3D::zero().
Referenced by DespawnOrUnsummon().
GetAggroRange()
float Creature::GetAggroRange (Unit const * target) const
Definition at line 3119 of file Creature.cpp.
 {
     // Determines the aggro range for creatures
     // Based on data from wowwiki due to lack of 3.3.5a data
     float aggroRate = sWorld->getRate(RATE_CREATURE_AGGRO);
     if (aggroRate == 0)
         return 0.0f;
     auto creatureLevel = target->getLevelForTarget(this);
     auto playerLevel  = getLevelForTarget(target);
     int32 levelDiff = int32(creatureLevel) - int32(playerLevel);
     // The maximum Aggro Radius is capped at 45 yards (25 level difference)
     if (levelDiff < -25)
         levelDiff = -25;
     // The base aggro radius for mob of same level
     auto aggroRadius = GetDetectionRange();
     if (aggroRadius < 1)
     {
         return 0.0f;
     }
     // Aggro Radius varies with level difference at a rate of roughly 1 yard/level
     aggroRadius -= (float)levelDiff;
     // detect range auras
     aggroRadius += GetTotalAuraModifier(SPELL_AURA_MOD_DETECT_RANGE);
     // detected range auras
     aggroRadius += target->GetTotalAuraModifier(SPELL_AURA_MOD_DETECTED_RANGE);
     // Just in case, we don't want pets running all over the map
     if (aggroRadius > MAX_AGGRO_RADIUS)
         aggroRadius = MAX_AGGRO_RADIUS;
     // Minimum Aggro Radius for a mob seems to be combat range (5 yards)
     // hunter pets seem to ignore minimum aggro radius so we'll default it a little higher
     float minRange = IsPet() ? 10.0f : 5.0f;
     if (aggroRadius < minRange)
         aggroRadius = minRange;
     return (aggroRadius * aggroRate);
 }
References GetDetectionRange(), Unit::getLevelForTarget(), getLevelForTarget(), Unit::GetTotalAuraModifier(), Unit::IsPet(), MAX_AGGRO_RADIUS, RATE_CREATURE_AGGRO, SPELL_AURA_MOD_DETECT_RANGE, SPELL_AURA_MOD_DETECTED_RANGE, and sWorld.
Referenced by CanStartAttack().
GetAIName()
std::string Creature::GetAIName () const
Definition at line 2737 of file Creature.cpp.
 {
     return sObjectMgr->GetCreatureTemplate(GetEntry())->AIName;
 }
References Object::GetEntry(), and sObjectMgr.
Referenced by npc_commandscript::HandleNpcInfoCommand(), npc_commandscript::HandleNpcSetDataCommand(), InitializeReactState(), SmartScript::IsSmart(), SmartAI::Permissible(), FactorySelector::selectAI(), and UpdateMoveInLineOfSightState().
GetAttackDistance()
float Creature::GetAttackDistance (Unit const * player) const
Definition at line 3339 of file Creature.cpp.
 {
     float aggroRate = sWorld->getRate(RATE_CREATURE_AGGRO);
     if (aggroRate == 0)
         return 0.0f;
     if (!player)
         return 0.0f;
     uint32 playerLevel = player->getLevelForTarget(this);
     uint32 creatureLevel = getLevelForTarget(player);
     int32 levelDiff = static_cast<int32>(playerLevel) - static_cast<int32>(creatureLevel);
     // "The maximum Aggro Radius has a cap of 25 levels under. Example: A level 30 char has the same Aggro Radius of a level 5 char on a level 60 mob."
     if (levelDiff < -25)
         levelDiff = -25;
     // "The aggro radius of a mob having the same level as the player is roughly 20 yards"
     float retDistance = 20.0f;
     // "Aggro Radius varies with level difference at a rate of roughly 1 yard/level"
     // radius grow if playlevel < creaturelevel
     retDistance -= static_cast<float>(levelDiff);
     if (creatureLevel + 5 <= sWorld->getIntConfig(CONFIG_MAX_PLAYER_LEVEL))
     {
         // detect range auras
         retDistance += static_cast<float>( GetTotalAuraModifier(SPELL_AURA_MOD_DETECT_RANGE) );
         // detected range auras
         retDistance += static_cast<float>( player->GetTotalAuraModifier(SPELL_AURA_MOD_DETECTED_RANGE) );
     }
     // "Minimum Aggro Radius for a mob seems to be combat range (5 yards)"
     if (retDistance < 5.0f)
         retDistance = 5.0f;
     return (retDistance * aggroRate);
 }
References CONFIG_MAX_PLAYER_LEVEL, Unit::getLevelForTarget(), getLevelForTarget(), Unit::GetTotalAuraModifier(), RATE_CREATURE_AGGRO, SPELL_AURA_MOD_DETECT_RANGE, SPELL_AURA_MOD_DETECTED_RANGE, and sWorld.
Referenced by WorldObject::CanDetectStealthOf().
GetCorpseDelay()
uint32 Creature::GetCorpseDelay () const inline
Definition at line 72 of file Creature.h.
 { return m_corpseDelay; }
References m_corpseDelay.
Referenced by ValithriaDespawner::operator()(), and SetPickPocketLootTime().
GetCreatureAddon()
CreatureAddon const * Creature::GetCreatureAddon () const
Definition at line 2444 of file Creature.cpp.
 {
     if (m_spawnId)
     {
         if (CreatureAddon const* addon = sObjectMgr->GetCreatureAddon(m_spawnId))
             return addon;
     }
     // dependent from difficulty mode entry
     return sObjectMgr->GetCreatureTemplateAddon(GetCreatureTemplate()->Entry);
 }
References Entry, GetCreatureTemplate(), m_spawnId, and sObjectMgr.
Referenced by boss_grand_champion::boss_grand_championAI::AddCreatureAddonAuras(), wp_commandscript::HandleWpUnLoadCommand(), LoadCreaturesAddon(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::OnCreatureCreate(), and UpdateEntry().
GetCreatureData()
CreatureData const* Creature::GetCreatureData () const inline
Definition at line 191 of file Creature.h.
 { return m_creatureData; }
References m_creatureData.
Referenced by GetScriptId(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), FrostwingGauntletRespawner::operator()(), ValithriaDespawner::operator()(), npc_argent_captainAI::Reset(), setDeathState(), npc_argent_captainAI::SpellHit(), and npc_grand_magister_rommath::npc_grand_magister_rommathAI::UpdateAI().
GetCreatureTemplate()
CreatureTemplate const* Creature::GetCreatureTemplate () const inline
Definition at line 190 of file Creature.h.
 { return m_creatureInfo; }
References m_creatureInfo.
Referenced by KillRewarder::_InitXP(), Unit::_IsValidAttackTarget(), AllLootRemovedFromCorpse(), Vehicle::ApplyAllImmunities(), Unit::ApplyDiminishingToDuration(), npc_escortAI::AssistPlayerInCombat(), FollowerAI::AssistPlayerInCombat(), SmartAI::AssistPlayerInCombat(), Player::BuildPetTalentsInfoData(), Unit::BuildValuesUpdate(), CalculateMinMaxDamage(), CanCreatureAttack(), CanEnterWater(), CanFly(), CanIgnoreFeignDeath(), CanWalk(), Spell::CheckCast(), Create(), Pet::CreateBaseAtCreature(), boss_high_king_maulgar::boss_high_king_maulgarAI::DoAction(), Spell::DoSpellHitOnUnit(), Spell::EffectSkinning(), Spell::EffectSummonType(), Acore::XP::Gain(), GetCreatureAddon(), Unit::GetCreatureType(), Player::GetDefaultGossipMenuForSource(), Player::GetNPCIfCanInteractWith(), Pet::HandleAsynchLoadFailed(), Pet::HandleAsynchLoadSucceed(), WorldSession::HandleGossipHelloOpcode(), learn_commandscript::HandleLearnAllMyPetTalentsCommand(), npc_commandscript::HandleNpcInfoCommand(), npc_commandscript::HandleNpcSetFactionIdCommand(), npc_commandscript::HandleNpcTameCommand(), AuraEffect::HandlePeriodicTriggerSpellAuraTick(), WorldSession::HandleQuestgiverHelloOpcode(), ArenaSpectator::HandleResetCommand(), WorldSession::HandleSellItemOpcode(), HasMechanicTemplateImmunity(), Pet::HaveInDiet(), InitEntry(), Pet::InitLevelupSpellsForLevel(), Guardian::InitStatsForLevel(), IsAvoidingAOE(), isCanTrainingAndResetTalentsOf(), IsCivilian(), isElite(), IsGuard(), Player::isHonorOrXPTarget(), IsImmunedToSpellEffect(), Unit::IsInPartyWith(), Unit::IsInRaidWith(), Pet::IsPermanentPetFor(), IsRacialLeader(), Unit::isSpellBlocked(), IsSpellProhibited(), IsTrigger(), isWorldBoss(), npc_escortAI::JustRespawned(), FollowerAI::JustRespawned(), SmartAI::JustRespawned(), Unit::Kill(), Pet::LearnPetPassives(), Player::LearnPetTalent(), LoadCreatureFromDB(), LoadSpellTemplateImmunity(), Unit::MeleeSpellHitResult(), boss_onyxia::boss_onyxiaAI::MovementInform(), boss_sindragosa::boss_sindragosaAI::MovementInform(), npc_scarlet_miner_cart::npc_scarlet_miner_cartAI::npc_scarlet_miner_cartAI(), npc_thrall_old_hillsbrad::OnGossipHello(), npc_artorius::OnGossipHello(), npc_simone::OnGossipHello(), npc_nelson::OnGossipHello(), npc_franklin::OnGossipHello(), Player::PetSpellInitialize(), Unit::RemoveCharmedBy(), Player::RemovePet(), boss_onyxia::boss_onyxiaAI::Reset(), boss_sindragosa::boss_sindragosaAI::Reset(), Pet::resetTalents(), Player::RewardReputation(), Unit::RollMeleeOutcomeAgainst(), SaveToDB(), SelectLevel(), FactorySelector::selectMovementGenerator(), Player::SendLoot(), WorldSession::SendPetNameQuery(), WorldSession::SendTrainerList(), Unit::SetCharmedBy(), setDeathState(), npc_tirion_fordring_tft::npc_tirion_fordringAI::sGossipSelect(), npc_harrison_jones::npc_harrison_jonesAI::sGossipSelect(), npc_captured_rageclaw::npc_captured_rageclawAI::SpellHit(), boss_priestess_delrissa::boss_priestess_delrissaAI::SummonedCreatureDies(), npc_hor_lich_king::npc_hor_lich_kingAI::UpdateAI(), npc_sinkhole_kill_credit::npc_sinkhole_kill_creditAI::UpdateAI(), npc_pet_gen_valkyr_guardian::UpdateAI(), npc_pet_hunter_snake_trap::UpdateAI(), generic_creature::generic_creatureAI::UpdateAI(), UpdateEntry(), UpdateMovementFlags(), Unit::UpdateSpeed(), and Player::UpdateWeaponSkill().
GetCurrentEquipmentId()
uint8 Creature::GetCurrentEquipmentId () inline
Definition at line 179 of file Creature.h.
 { return m_equipmentId; }
References m_equipmentId.
Referenced by AuraEffect::HandleAuraModDisarm(), npc_commandscript::HandleNpcInfoCommand(), npc_unworthy_initiate::npc_unworthy_initiateAI::npc_unworthy_initiateAI(), and SaveToDB().
GetCurrentWaypointID()
uint32 Creature::GetCurrentWaypointID () const inline
Definition at line 329 of file Creature.h.
 { return m_waypointID; }
References m_waypointID.
GetDefaultMovementType()
MovementGeneratorType Creature::GetDefaultMovementType () const inline
Definition at line 265 of file Creature.h.
 { return m_defaultMovementType; }
References m_defaultMovementType.
Referenced by SaveToDB(), and FactorySelector::selectMovementGenerator().
GetDetectionRange()
float Creature::GetDetectionRange () const inline
Definition at line 242 of file Creature.h.
 { return m_detectionDistance; }
References m_detectionDistance.
Referenced by GetAggroRange().
GetFormation() [1/2]
CreatureGroup* Creature::GetFormation () inline
Definition at line 334 of file Creature.h.
 { return m_formation; }
References m_formation.
GetFormation() [2/2]
CreatureGroup const* Creature::GetFormation () const inline
Definition at line 333 of file Creature.h.
 { return m_formation; }
References m_formation.
Referenced by CreatureAI::_EnterEvadeMode(), RandomMovementGenerator< T >::_setRandomLocation(), npc_commandscript::HandleNpcAddFormationCommand(), npc_simone::npc_simoneAI::SetPreciousGUID(), WaypointMovementGenerator< Creature >::StartMove(), and boss_garfrost::boss_garfrostAI::UpdateAI().
GetHomePosition() [1/2]
Position const& Creature::GetHomePosition () const inline
Definition at line 319 of file Creature.h.
 { return m_homePosition; }
References m_homePosition.
Referenced by GetRespawnPosition().
GetHomePosition() [2/2]
void Creature::GetHomePosition (float & x, float & y, float & z, float & ori) const inline
Definition at line 318 of file Creature.h.
 { m_homePosition.GetPosition(x, y, z, ori); }
References Position::GetPosition(), m_homePosition, G3D::x, G3D::y, and G3D::z.
Referenced by HomeMovementGenerator< Creature >::_setTargetLocation(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::AttackStart(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::AttackStart(), npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::CanAIAttack(), boss_halion::boss_halionAI::CanAIAttack(), npc_icc_spire_frostwyrm::npc_icc_spire_frostwyrmAI::CanAIAttack(), boss_midnight::boss_midnightAI::CheckEvadeIfOutOfCombatArea(), boss_trollgore::boss_trollgoreAI::CheckEvadeIfOutOfCombatArea(), boss_anomalus::boss_anomalusAI::CheckEvadeIfOutOfCombatArea(), boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI::CheckEvadeIfOutOfCombatArea(), boss_illidan_stormrage::boss_illidan_stormrageAI::CheckEvadeIfOutOfCombatArea(), boss_teron_gorefiend::boss_teron_gorefiendAI::CheckEvadeIfOutOfCombatArea(), boss_lady_vashj::boss_lady_vashjAI::CheckEvadeIfOutOfCombatArea(), boss_kaelthas::boss_kaelthasAI::CheckEvadeIfOutOfCombatArea(), boss_isle_of_conquest::boss_isle_of_conquestAI::CheckRageBuff(), boss_essence_of_suffering::boss_essence_of_sufferingAI::DamageTaken(), boss_essence_of_desire::boss_essence_of_desireAI::DamageTaken(), npc_icc_spire_frostwyrm::npc_icc_spire_frostwyrmAI::DoAction(), boss_taldaram::boss_taldaramAI::DoAction(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction(), boss_kelthuzad_minion::boss_kelthuzad_minionAI::DoAction(), boss_professor_putricide::boss_professor_putricideAI::EnterCombat(), boss_rotface::boss_rotfaceAI::EnterCombat(), npc_hor_spiritual_reflection::npc_hor_spiritual_reflectionAI::EnterEvadeMode(), boss_professor_putricide::boss_professor_putricideAI::EnterEvadeMode(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::EnterEvadeMode(), UtherBatteredHiltEvent::Execute(), DistractMovementGenerator::Finalize(), npc_arthas_teleport_visual::GetAI(), boss_prince_keleseth_icc::boss_prince_kelesethAI::InitializeAI(), boss_prince_taldaram_icc::boss_prince_taldaramAI::InitializeAI(), boss_prince_valanar_icc::boss_prince_valanarAI::InitializeAI(), npc_sindragosa_trash::npc_sindragosa_trashAI::InitializeAI(), boss_halion::boss_halionAI::IsAnyPlayerValid(), boss_loatheb::boss_loathebAI::IsInRoom(), boss_algalon_the_observer::boss_algalon_the_observerAI::IsInRoom(), boss_prince_keleseth_icc::boss_prince_kelesethAI::JustDied(), boss_prince_taldaram_icc::boss_prince_taldaramAI::JustDied(), boss_prince_valanar_icc::boss_prince_valanarAI::JustDied(), npc_daphne_stilwell::npc_daphne_stilwellAI::JustSummoned(), npc_mageguard_dalaran::npc_mageguard_dalaranAI::MoveInLineOfSight(), boss_lady_vashj::boss_lady_vashjAI::MovementInform(), npc_dragonflayer_forge_master::npc_dragonflayer_forge_masterAI::npc_dragonflayer_forge_masterAI(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::npc_icc_vengeful_fleshreaperAI(), instance_ulduar::instance_ulduar_InstanceMapScript::OnCreatureCreate(), spell_halion_twilight_phasing::spell_halion_twilight_phasing_SpellScript::Phase(), SmartScript::ProcessAction(), boss_four_horsemen::boss_four_horsemenAI::Reset(), boss_thaddius::boss_thaddiusAI::Reset(), npc_q24545_lich_king::npc_q24545_lich_kingAI::Reset(), boss_nexusprince_shaffar::boss_nexusprince_shaffarAI::Reset(), SmartAI::ReturnToLastOOCPos(), npc_escortAI::ReturnToLastPoint(), instance_naxxramas::instance_naxxramas_InstanceMapScript::SetBossState(), Player::SetClientControl(), npc_alexstraza_the_lifebinder::npc_alexstraza_the_lifebinderAI::SetData(), npc_pet_gen_fetch_ball::SpellHitTarget(), npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI::UpdateAI(), boss_balinda::boss_balindaAI::UpdateAI(), boss_drekthar::boss_drektharAI::UpdateAI(), boss_galvangar::boss_galvangarAI::UpdateAI(), boss_vanndar::boss_vanndarAI::UpdateAI(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::UpdateAI(), boss_broodlord::boss_broodlordAI::UpdateAI(), boss_priestess_delrissa::boss_priestess_delrissaAI::UpdateAI(), npc_scarlet_cannon::npc_scarlet_cannonAI::UpdateAI(), boss_kalecgos::boss_kalecgosAI::UpdateAI(), npc_alexstraza_the_lifebinder::npc_alexstraza_the_lifebinderAI::UpdateAI(), boss_elder_nadox::boss_elder_nadoxAI::UpdateAI(), boss_frostsworn_general::boss_frostsworn_generalAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), boss_sapphiron::boss_sapphironAI::UpdateAI(), boss_thaddius_summon::boss_thaddius_summonAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_bloodmage_laurith::npc_bloodmage_laurithAI::UpdateAI(), boss_lady_vashj::boss_lady_vashjAI::UpdateAI(), boss_the_black_stalker::boss_the_black_stalkerAI::UpdateAI(), and boss_kaelthas::boss_kaelthasAI::UpdateAI().
GetLastDamagedTime()
time_t Creature::GetLastDamagedTime () const
Definition at line 3414 of file Creature.cpp.
 {
     if (!_lastDamagedTime)
         return time_t(0);
     return *_lastDamagedTime;
 }
References _lastDamagedTime.
Referenced by CanCreatureAttack().
GetLastDamagedTimePtr()
std::shared_ptr< time_t > const & Creature::GetLastDamagedTimePtr () const
Definition at line 3422 of file Creature.cpp.
 {
     return _lastDamagedTime;
 }
References _lastDamagedTime.
Referenced by AssistDelayEvent::Execute().
getLevelForTarget()
uint8 Creature::getLevelForTarget (WorldObject const * target) const override virtual
Reimplemented from WorldObject.
Definition at line 2724 of file Creature.cpp.
 {
     if (!isWorldBoss() || !target->ToUnit())
         return Unit::getLevelForTarget(target);
     uint16 level = target->ToUnit()->getLevel() + sWorld->getIntConfig(CONFIG_WORLD_BOSS_LEVEL_DIFF);
     if (level < 1)
         return 1;
     if (level > 255)
         return 255;
     return uint8(level);
 }
References CONFIG_WORLD_BOSS_LEVEL_DIFF, Unit::getLevel(), Unit::getLevelForTarget(), isWorldBoss(), sWorld, and Object::ToUnit().
Referenced by GetAggroRange(), and GetAttackDistance().
GetLootMode()
uint16 Creature::GetLootMode () const inline
Definition at line 225 of file Creature.h.
 { return m_LootMode; }
References m_LootMode.
Referenced by boss_vezax::boss_vezaxAI::GetData(), and Unit::Kill().
GetLootRecipient()
Player * Creature::GetLootRecipient () const
Definition at line 1147 of file Creature.cpp.
 {
     if (!m_lootRecipient)
         return nullptr;
     return ObjectAccessor::FindConnectedPlayer(m_lootRecipient);
 }
References ObjectAccessor::FindConnectedPlayer(), and m_lootRecipient.
Referenced by boss_high_king_maulgar::boss_high_king_maulgarAI::DoAction(), debug_commandscript::HandleDebugGetLootRecipientCommand(), Player::isAllowedToLoot(), Unit::Kill(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath(), SmartScript::ProcessAction(), Player::SendLoot(), and boss_priestess_delrissa::boss_priestess_delrissaAI::SummonedCreatureDies().
GetLootRecipientGroup()
Group * Creature::GetLootRecipientGroup () const
Definition at line 1154 of file Creature.cpp.
 {
     if (!m_lootRecipientGroup)
         return nullptr;
     return sGroupMgr->GetGroupByGUID(m_lootRecipientGroup);
 }
References m_lootRecipientGroup, and sGroupMgr.
Referenced by Player::isAllowedToLoot(), isTappedBy(), Unit::Kill(), and Player::SendLoot().
GetLootRecipientGroupGUID()
ObjectGuid::LowType Creature::GetLootRecipientGroupGUID () const inline
Definition at line 214 of file Creature.h.
 { return m_lootRecipientGroup; }
References m_lootRecipientGroup.
Referenced by GameObject::SetLootRecipient().
GetLootRecipientGUID()
ObjectGuid Creature::GetLootRecipientGUID () const inline
Definition at line 212 of file Creature.h.
 { return m_lootRecipient; }
References m_lootRecipient.
Referenced by Player::SendLoot(), and GameObject::SetLootRecipient().
GetMeleeDamageSchoolMask()
SpellSchoolMask Creature::GetMeleeDamageSchoolMask () const inline override virtual
Reimplemented from Unit.
Definition at line 153 of file Creature.h.
 { return m_meleeDamageSchoolMask; }
References m_meleeDamageSchoolMask.
Referenced by ThreatContainer::selectNextVictim().
GetNameForLocaleIdx()
std::string const & Creature::GetNameForLocaleIdx (LocaleConstant locale_idx) const override virtual
Reimplemented from WorldObject.
Definition at line 2838 of file Creature.cpp.
 {
     if (loc_idx != DEFAULT_LOCALE)
     {
         uint8 uloc_idx = uint8(loc_idx);
         CreatureLocale const* cl = sObjectMgr->GetCreatureLocale(GetEntry());
         if (cl)
         {
             if (cl->Name.size() > uloc_idx && !cl->Name[uloc_idx].empty())
                 return cl->Name[uloc_idx];
         }
     }
     return GetName();
 }
References DEFAULT_LOCALE, Object::GetEntry(), WorldObject::GetName(), CreatureLocale::Name, and sObjectMgr.
Referenced by Pet::CreateBaseAtCreature(), and WorldSession::SendPetNameQuery().
GetOriginalEntry()
uint32 Creature::GetOriginalEntry () const inline
Definition at line 350 of file Creature.h.
 { return m_originalEntry; }
References m_originalEntry.
Referenced by FrostwingGauntletRespawner::operator()().
GetOriginalEquipmentId()
int8 Creature::GetOriginalEquipmentId () const inline
Definition at line 178 of file Creature.h.
 { return m_originalEquipmentId; }
References m_originalEquipmentId.
Referenced by npc_commandscript::HandleNpcInfoCommand(), npc_unworthy_initiate::npc_unworthy_initiateAI::npc_unworthy_initiateAI(), and ScriptedAI::SetEquipmentSlots().
GetPetAutoSpellOnPos()
virtual uint32 Creature::GetPetAutoSpellOnPos (uint8 pos) const inline virtual
Reimplemented in Pet.
Definition at line 300 of file Creature.h.
     {
         if (pos >= MAX_SPELL_CHARM || m_charmInfo->GetCharmSpell(pos)->GetType() != ACT_ENABLED)
             return 0;
         else
             return m_charmInfo->GetCharmSpell(pos)->GetAction();
     }
References ACT_ENABLED, UnitActionBarEntry::GetAction(), CharmInfo::GetCharmSpell(), UnitActionBarEntry::GetType(), Unit::m_charmInfo, MAX_SPELL_CHARM, and pos().
Referenced by PetAI::_canMeleeAttack(), and PetAI::UpdateAI().
GetPetAutoSpellSize()
virtual uint8 Creature::GetPetAutoSpellSize () const inline virtual
Reimplemented in Pet.
Definition at line 299 of file Creature.h.
 { return MAX_SPELL_CHARM; }
References MAX_SPELL_CHARM.
Referenced by PetAI::_canMeleeAttack(), and PetAI::UpdateAI().
GetReactState()
ReactStates Creature::GetReactState () const inline
Definition at line 84 of file Creature.h.
 { return m_reactState; }
References m_reactState.
Referenced by boss_kiljaeden::boss_kiljaedenAI::AttackStart(), boss_icehowl::boss_icehowlAI::AttackStart(), boss_the_lurker_below::boss_the_lurker_belowAI::AttackStart(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::CanAIAttack(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::CanAIAttack(), SmartAI::CanAIAttack(), npc_lk_wicked_spirit::npc_lk_wicked_spiritAI::CanAIAttack(), CharmInfo::CharmInfo(), Player::CharmSpellInitialize(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::DamageTaken(), npc_ulduar_vx001::npc_ulduar_vx001AI::DamageTaken(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::DamageTaken(), boss_brutallus::boss_brutallusAI::DamageTaken(), boss_kiljaeden::boss_kiljaedenAI::EnterEvadeMode(), boss_ick::boss_ickAI::KilledUnit(), npc_scarlet_ghoul::npc_scarlet_ghoulAI::OwnerAttackedBy(), Player::PetSpellInitialize(), npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI::Reset(), Pet::SavePetToDB(), boss_kiljaeden::boss_kiljaedenAI::UpdateAI(), boss_icehowl::boss_icehowlAI::UpdateAI(), npc_gunship_boarding_leader::npc_gunship_boarding_leaderAI::UpdateAI(), npc_gunship_boarding_add::npc_gunship_boarding_add_realAI::UpdateAI(), npc_gunship_mage::npc_gunship_mageAI::UpdateAI(), npc_gunship_gunner::npc_gunship_gunnerAI::UpdateAI(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI(), boss_lady_vashj::boss_lady_vashjAI::UpdateAI(), boss_the_lurker_below::boss_the_lurker_belowAI::UpdateAI(), npc_gunship_rocketeer::npc_gunship_rocketeerAI::UpdateAI(), and Player::VehicleSpellInitialize().
GetRespawnDelay()
uint32 Creature::GetRespawnDelay () const inline
Definition at line 281 of file Creature.h.
 { return m_respawnDelay; }
References m_respawnDelay.
Referenced by npc_the_scourge_cauldron::npc_the_scourge_cauldronAI::DoDie(), npc_commandscript::HandleNpcInfoCommand(), and ValithriaDespawner::operator()().
GetRespawnPosition()
void Creature::GetRespawnPosition (float & x, float & y, float & z, float * ori = nullptr, float * dist = nullptr) const
Definition at line 2660 of file Creature.cpp.
 {
     if (m_spawnId)
     {
         if (CreatureData const* data = sObjectMgr->GetCreatureData(m_spawnId))
         {
             x = data->posX;
             y = data->posY;
             z = data->posZ;
             if (ori)
                 *ori = data->orientation;
             if (dist)
                 *dist = data->wander_distance;
             return;
         }
     }
     // xinef: changed this from current position to home position, fixes world summons with infinite duration
     if (GetTransport())
     {
         x = GetPositionX();
         y = GetPositionY();
         z = GetPositionZ();
         if (ori)
             *ori = GetOrientation();
     }
     else
     {
         Position homePos = GetHomePosition();
         x = homePos.GetPositionX();
         y = homePos.GetPositionY();
         z = homePos.GetPositionZ();
         if (ori)
             *ori = homePos.GetOrientation();
     }
     if (dist)
         *dist = 0;
 }
References GetHomePosition(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), WorldObject::GetTransport(), m_spawnId, sObjectMgr, G3D::x, G3D::y, and G3D::z.
Referenced by DespawnOnEvade(), RemoveCorpse(), and npc_escortAI::UpdateAI().
GetRespawnTime()
time_t const& Creature::GetRespawnTime () const inline
Definition at line 275 of file Creature.h.
 { return m_respawnTime; }
References m_respawnTime.
Referenced by npc_simone::npc_simoneAI::JustDied(), and SetPickPocketLootTime().
GetRespawnTimeEx()
time_t Creature::GetRespawnTimeEx () const
Definition at line 2650 of file Creature.cpp.
 {
     time_t now = time(nullptr);
     if (m_respawnTime > now)
         return m_respawnTime;
     else
         return now;
 }
References m_respawnTime.
Referenced by npc_commandscript::HandleNpcInfoCommand().
GetScriptId()
uint32 Creature::GetScriptId () const
Definition at line 2747 of file Creature.cpp.
 {
     if (CreatureData const* creatureData = GetCreatureData())
         return creatureData->ScriptId;
     return sObjectMgr->GetCreatureTemplate(GetEntry())->ScriptID;
 }
References creatureData, GetCreatureData(), Object::GetEntry(), and sObjectMgr.
Referenced by Create(), ScriptMgr::GetCreatureAI(), ScriptMgr::GetDialogStatus(), GetScriptName(), WorldSession::HandleGossipSelectOptionOpcode(), InitializeReactState(), ScriptMgr::OnAddPassenger(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), ScriptMgr::OnCreatureUpdate(), ScriptMgr::OnGossipHello(), ScriptMgr::OnGossipSelect(), ScriptMgr::OnGossipSelectCode(), ScriptMgr::OnInstall(), ScriptMgr::OnInstallAccessory(), ScriptMgr::OnQuestAccept(), ScriptMgr::OnQuestComplete(), ScriptMgr::OnQuestReward(), ScriptMgr::OnQuestSelect(), ScriptMgr::OnRemovePassenger(), ScriptMgr::OnReset(), ScriptMgr::OnUninstall(), and UpdateMoveInLineOfSightState().
GetScriptName()
std::string Creature::GetScriptName () const
Definition at line 2742 of file Creature.cpp.
 {
     return sObjectMgr->GetScriptName(GetScriptId());
 }
References GetScriptId(), and sObjectMgr.
Referenced by npc_commandscript::HandleNpcInfoCommand(), npc_commandscript::HandleNpcSetDataCommand(), and npc_escortAI::Start().
GetShieldBlockValue()
uint32 Creature::GetShieldBlockValue () const inline override virtual
Implements Unit.
Definition at line 148 of file Creature.h.
     {
         return (getLevel() / 2 + uint32(GetStat(STAT_STRENGTH) / 20));
     }
References Unit::getLevel(), Unit::GetStat(), and STAT_STRENGTH.
GetSpawnId()
ObjectGuid::LowType Creature::GetSpawnId () const inline
Definition at line 66 of file Creature.h.
 { return m_spawnId; }
References m_spawnId.
Referenced by BattlegroundAV::AddAVCreature(), CreatureGroup::AddMember(), Vehicle::ApplyAllImmunities(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::boss_valithria_dreamwalkerAI(), RandomMovementGenerator< T >::DoInitialize(), npc_risen_archmage::npc_risen_archmageAI::EnterCombat(), GameEventMgr::GetNPCFlag(), SmartScript::GetScript(), WorldSession::HandleAuctionSellItem(), debug_commandscript::HandleDebugGetLootRecipientCommand(), OPvPCapturePointZM_GraveYard::HandleGossipOption(), npc_commandscript::HandleNpcAddCommand(), npc_commandscript::HandleNpcAddFormationCommand(), npc_commandscript::HandleNpcInfoCommand(), npc_commandscript::HandleNpcMoveCommand(), npc_commandscript::HandleNpcSetLinkCommand(), npc_commandscript::HandleNpcSetMoveTypeCommand(), npc_commandscript::HandleNpcSetSpawnTimeCommand(), npc_commandscript::HandleNpcSetWanderDistanceCommand(), wp_commandscript::HandleWpLoadCommand(), wp_commandscript::HandleWpModifyCommand(), wp_commandscript::HandleWpShowCommand(), wp_commandscript::HandleWpUnLoadCommand(), npc_spinestalker::npc_spinestalkerAI::InitializeAI(), npc_rimefang::npc_rimefangAI::InitializeAI(), npc_sindragosa_trash::npc_sindragosa_trashAI::InitializeAI(), npc_spinestalker::npc_spinestalkerAI::JustRespawned(), npc_rimefang::npc_rimefangAI::JustRespawned(), npc_sindragosa_trash::npc_sindragosa_trashAI::JustRespawned(), CreatureGroup::MemberAttackStart(), CreatureGroup::MemberEvaded(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::OnCreatureCreate(), instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::OnCreatureCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath(), RisenArchmageCheck::operator()(), ValithriaDespawner::operator()(), DoorsGuidCheck::operator()(), FormationMgr::RemoveCreatureFromGroup(), Respawn(), SearchFormation(), boss_kaelthas::boss_kaelthasAI::SummonedCreatureDies(), and npc_risen_archmage::npc_risen_archmageAI::UpdateAI().
GetSpellCooldown()
uint32 Creature::GetSpellCooldown (uint32 spell_id) const
Definition at line 2626 of file Creature.cpp.
 {
     CreatureSpellCooldowns::const_iterator itr = m_CreatureSpellCooldowns.find(spell_id);
     if (itr == m_CreatureSpellCooldowns.end())
         return 0;
     return itr->second.end > World::GetGameTimeMS() ? itr->second.end - World::GetGameTimeMS() : 0;
 }
References World::GetGameTimeMS(), and m_CreatureSpellCooldowns.
GetSpellDamageMod()
float Creature::GetSpellDamageMod (int32 Rank)
Definition at line 1447 of file Creature.cpp.
 {
     switch (Rank)                                           // define rates for each elite rank
     {
         case CREATURE_ELITE_NORMAL:
             return sWorld->getRate(RATE_CREATURE_NORMAL_SPELLDAMAGE);
         case CREATURE_ELITE_ELITE:
             return sWorld->getRate(RATE_CREATURE_ELITE_ELITE_SPELLDAMAGE);
         case CREATURE_ELITE_RAREELITE:
             return sWorld->getRate(RATE_CREATURE_ELITE_RAREELITE_SPELLDAMAGE);
         case CREATURE_ELITE_WORLDBOSS:
             return sWorld->getRate(RATE_CREATURE_ELITE_WORLDBOSS_SPELLDAMAGE);
         case CREATURE_ELITE_RARE:
             return sWorld->getRate(RATE_CREATURE_ELITE_RARE_SPELLDAMAGE);
         default:
             return sWorld->getRate(RATE_CREATURE_ELITE_ELITE_SPELLDAMAGE);
     }
 }
References CREATURE_ELITE_ELITE, CREATURE_ELITE_NORMAL, CREATURE_ELITE_RARE, CREATURE_ELITE_RAREELITE, CREATURE_ELITE_WORLDBOSS, RATE_CREATURE_ELITE_ELITE_SPELLDAMAGE, RATE_CREATURE_ELITE_RARE_SPELLDAMAGE, RATE_CREATURE_ELITE_RAREELITE_SPELLDAMAGE, RATE_CREATURE_ELITE_WORLDBOSS_SPELLDAMAGE, RATE_CREATURE_NORMAL_SPELLDAMAGE, and sWorld.
Referenced by Unit::SpellDamageBonusDone().
GetTrainerSpells()
TrainerSpellData const * Creature::GetTrainerSpells () const
Definition at line 2832 of file Creature.cpp.
 {
     return sObjectMgr->GetNpcTrainerSpells(GetEntry());
 }
References Object::GetEntry(), and sObjectMgr.
Referenced by WorldSession::HandleTrainerBuySpellOpcode(), and WorldSession::SendTrainerList().
GetTransportHomePosition() [1/2]
Position const& Creature::GetTransportHomePosition () const inline
Definition at line 324 of file Creature.h.
 { return m_transportHomePosition; }
References m_transportHomePosition.
GetTransportHomePosition() [2/2]
void Creature::GetTransportHomePosition (float & x, float & y, float & z, float & ori) const inline
Definition at line 323 of file Creature.h.
 { m_transportHomePosition.GetPosition(x, y, z, ori); }
References Position::GetPosition(), m_transportHomePosition, G3D::x, G3D::y, and G3D::z.
Referenced by SmartScript::ProcessAction(), Player::SetClientControl(), and MotionTransport::UpdatePassengerPositions().
GetVendorItemCurrentCount()
uint32 Creature::GetVendorItemCurrentCount (VendorItem const * vItem)
Definition at line 2760 of file Creature.cpp.
 {
     if (!vItem->maxcount)
         return vItem->maxcount;
     VendorItemCounts::iterator itr = m_vendorItemCounts.begin();
     for (; itr != m_vendorItemCounts.end(); ++itr)
         if (itr->itemId == vItem->item)
             break;
     if (itr == m_vendorItemCounts.end())
         return vItem->maxcount;
     VendorItemCount* vCount = &*itr;
     time_t ptime = time(nullptr);
     if (time_t(vCount->lastIncrementTime + vItem->incrtime) <= ptime)
     {
         ItemTemplate const* pProto = sObjectMgr->GetItemTemplate(vItem->item);
         uint32 diff = uint32((ptime - vCount->lastIncrementTime) / vItem->incrtime);
         if ((vCount->count + diff * pProto->BuyCount) >= vItem->maxcount)
         {
             m_vendorItemCounts.erase(itr);
             return vItem->maxcount;
         }
         vCount->count += diff * pProto->BuyCount;
         vCount->lastIncrementTime = ptime;
     }
     return vCount->count;
 }
References ItemTemplate::BuyCount, VendorItemCount::count, diff(), VendorItem::incrtime, VendorItem::item, VendorItemCount::lastIncrementTime, m_vendorItemCounts, VendorItem::maxcount, and sObjectMgr.
Referenced by Player::BuyItemFromVendorSlot(), and WorldSession::SendListInventory().
GetVendorItems()
VendorItemData const * Creature::GetVendorItems () const
Definition at line 2755 of file Creature.cpp.
 {
     return sObjectMgr->GetNpcVendorItemList(GetEntry());
 }
References Object::GetEntry(), and sObjectMgr.
Referenced by Player::BuyItemFromVendorSlot(), and WorldSession::SendListInventory().
GetWanderDistance()
float Creature::GetWanderDistance () const inline
Definition at line 284 of file Creature.h.
 { return m_wanderDistance; }
References m_wanderDistance.
Referenced by RandomMovementGenerator< T >::DoInitialize().
GetWaypointPath()
uint32 Creature::GetWaypointPath () const inline
Definition at line 326 of file Creature.h.
 { return m_path_id; }
References m_path_id.
Referenced by wp_commandscript::HandleWpAddCommand(), wp_commandscript::HandleWpShowCommand(), SmartAI::JustReachedHome(), WaypointMovementGenerator< Creature >::LoadPath(), boss_razorscale::boss_razorscaleAI::UpdateAI(), npc_wild_wyrm::npc_wild_wyrmAI::UpdateAI(), and boss_alar::boss_alarAI::UpdateAI().
hasInvolvedQuest()
bool Creature::hasInvolvedQuest (uint32 quest_id) const override virtual
Reimplemented from Object.
Definition at line 1674 of file Creature.cpp.
 {
     QuestRelationBounds qir = sObjectMgr->GetCreatureQuestInvolvedRelationBounds(GetEntry());
     for (QuestRelations::const_iterator itr = qir.first; itr != qir.second; ++itr)
     {
         if (itr->second == quest_id)
             return true;
     }
     return false;
 }
References Object::GetEntry(), and sObjectMgr.
HasLootMode()
bool Creature::HasLootMode (uint16 lootMode) const inline
Definition at line 226 of file Creature.h.
 { return m_LootMode & lootMode; }
References m_LootMode.
hasLootRecipient()
bool Creature::hasLootRecipient () const inline
Definition at line 216 of file Creature.h.
 { return m_lootRecipient || m_lootRecipientGroup; }
References m_lootRecipient, and m_lootRecipientGroup.
Referenced by Unit::BuildValuesUpdate(), Unit::DealDamage(), boss_prince_keleseth_icc::boss_prince_kelesethAI::EnterCombat(), boss_prince_taldaram_icc::boss_prince_taldaramAI::EnterCombat(), boss_prince_valanar_icc::boss_prince_valanarAI::EnterCombat(), Player::GiveXP(), debug_commandscript::HandleDebugGetLootRecipientCommand(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::HealReceived(), and setDeathState().
HasMechanicTemplateImmunity()
bool Creature::HasMechanicTemplateImmunity (uint32 mask) const
Definition at line 1993 of file Creature.cpp.
 {
     return !GetOwnerGUID().IsPlayer() && (GetCreatureTemplate()->MechanicImmuneMask & mask);
 }
References GetCreatureTemplate(), Unit::GetOwnerGUID(), ObjectGuid::IsPlayer(), and CreatureTemplate::MechanicImmuneMask.
Referenced by IsImmunedToSpell(), IsImmunedToSpellEffect(), and Unit::UpdateSpeed().
hasQuest()
bool Creature::hasQuest (uint32 quest_id) const override virtual
Reimplemented from Object.
Definition at line 1663 of file Creature.cpp.
 {
     QuestRelationBounds qr = sObjectMgr->GetCreatureQuestRelationBounds(GetEntry());
     for (QuestRelations::const_iterator itr = qr.first; itr != qr.second; ++itr)
     {
         if (itr->second == quest_id)
             return true;
     }
     return false;
 }
References Object::GetEntry(), qr, and sObjectMgr.
HasReactState()
bool Creature::HasReactState (ReactStates state) const inline
Definition at line 85 of file Creature.h.
 { return (m_reactState == state); }
References m_reactState.
Referenced by npc_escortAI::AssistPlayerInCombat(), PetAI::AttackedBy(), boss_sister_svalna::boss_sister_svalnaAI::AttackStart(), CanAssistTo(), PetAI::CanAttack(), Unit::CombatStart(), PetAI::DoAttack(), Spell::EffectTaunt(), boss_sister_svalna::boss_sister_svalnaAI::EnterCombat(), WorldSession::HandlePetActionHelper(), CreatureAI::MoveInLineOfSight(), SmartAI::MoveInLineOfSight(), PetAI::OwnerAttacked(), PetAI::OwnerAttackedBy(), boss_tyrannus::boss_tyrannusAI::Reset(), PetAI::SelectNextTarget(), SelectVictim(), Unit::SetInCombatState(), PetAI::SpellHit(), Unit::TauntApply(), Unit::TauntFadeOut(), CreatureAI::TriggerAlert(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), npc_raging_spirit::npc_raging_spiritAI::UpdateAI(), boss_noth::boss_nothAI::UpdateAI(), PetAI::UpdateAI(), CreatureAI::UpdateVictim(), and CreatureAI::UpdateVictimWithGaze().
HasSearchedAssistance()
bool Creature::HasSearchedAssistance () inline
Definition at line 254 of file Creature.h.
 { return m_AlreadySearchedAssistance; }
References m_AlreadySearchedAssistance.
Referenced by setDeathState().
HasSpell()
bool Creature::HasSpell (uint32 spellID) const override virtual
Reimplemented from Unit.
Reimplemented in Pet.
Definition at line 2641 of file Creature.cpp.
 {
     uint8 i;
     for (i = 0; i < MAX_CREATURE_SPELLS; ++i)
         if (spellID == m_spells[i])
             break;
     return i < MAX_CREATURE_SPELLS;                         //broke before end of iteration of known spells
 }
References m_spells, and MAX_CREATURE_SPELLS.
Referenced by WorldSession::HandleCastSpellOpcode().
HasSpellCooldown()
bool Creature::HasSpellCooldown (uint32 spell_id) const override virtual
Reimplemented from Unit.
Definition at line 2635 of file Creature.cpp.
 {
     CreatureSpellCooldowns::const_iterator itr = m_CreatureSpellCooldowns.find(spell_id);
     return (itr != m_CreatureSpellCooldowns.end() && itr->second.end > World::GetGameTimeMS());
 }
References World::GetGameTimeMS(), and m_CreatureSpellCooldowns.
Referenced by WorldSession::HandlePetActionHelper(), WorldSession::HandlePetCastSpellOpcode(), boss_faction_championsAI::IsCCed(), Pet::Update(), PetAI::UpdateAI(), and npc_gunship_rocketeer::npc_gunship_rocketeerAI::UpdateAI().
HasSpellFocus()
bool Creature::HasSpellFocus (Spell const * focusSpell = nullptr) const
Definition at line 3313 of file Creature.cpp.
 {
     if (isDead()) // dead creatures cannot focus
     {
         return false;
     }
     return focusSpell ? (focusSpell == _spellFocusInfo.Spell) : (_spellFocusInfo.Spell || _spellFocusInfo.Delay);
 }
References _spellFocusInfo, and Unit::isDead().
Referenced by IsMovementPreventedByCasting().
HasSwimmingFlagOutOfCombat()
bool Creature::HasSwimmingFlagOutOfCombat () const inline
Definition at line 377 of file Creature.h.
     {
         return !_isMissingSwimmingFlagOutOfCombat;
     }
References _isMissingSwimmingFlagOutOfCombat.
Referenced by HomeMovementGenerator< Creature >::DoFinalize().
InitEntry()
bool Creature::InitEntry (uint32 Entry, const CreatureData * data = nullptr) protected
change the entry of creature until respawn
Definition at line 347 of file Creature.cpp.
 {
     CreatureTemplate const* normalInfo = sObjectMgr->GetCreatureTemplate(Entry);
     if (!normalInfo)
     {
         LOG_ERROR("sql.sql", "Creature::InitEntry creature entry %u does not exist.", Entry);
         return false;
     }
     // get difficulty 1 mode entry
     // Xinef: Skip for pets!
     CreatureTemplate const* cinfo = normalInfo;
     for (uint8 diff = uint8(GetMap()->GetSpawnMode()); diff > 0 && !IsPet();)
     {
         // we already have valid Map pointer for current creature!
         if (normalInfo->DifficultyEntry[diff - 1])
         {
             cinfo = sObjectMgr->GetCreatureTemplate(normalInfo->DifficultyEntry[diff - 1]);
             if (cinfo)
                 break;                                      // template found
             // check and reported at startup, so just ignore (restore normalInfo)
             cinfo = normalInfo;
         }
         // for instances heroic to normal, other cases attempt to retrieve previous difficulty
         if (diff >= RAID_DIFFICULTY_10MAN_HEROIC && GetMap()->IsRaid())
             diff -= 2;                                      // to normal raid difficulty cases
         else
             --diff;
     }
     SetEntry(Entry);                                        // normal entry always
     m_creatureInfo = cinfo;                                 // map mode related always
     // equal to player Race field, but creature does not have race
     SetByteValue(UNIT_FIELD_BYTES_0, 0, 0);
     // known valid are: CLASS_WARRIOR, CLASS_PALADIN, CLASS_ROGUE, CLASS_MAGE
     SetByteValue(UNIT_FIELD_BYTES_0, 1, uint8(cinfo->unit_class));
     // Cancel load if no model defined
     if (!(cinfo->GetFirstValidModelId()))
     {
         LOG_ERROR("sql.sql", "Creature (Entry: %u) has no model defined in table `creature_template`, can't load. ", Entry);
         return false;
     }
     uint32 displayID = ObjectMgr::ChooseDisplayId(GetCreatureTemplate(), data);
     CreatureModelInfo const* minfo = sObjectMgr->GetCreatureModelRandomGender(&displayID);
     if (!minfo)                                             // Cancel load if no model defined
     {
         LOG_ERROR("sql.sql", "Creature (Entry: %u) has no model defined in table `creature_template`, can't load. ", Entry);
         return false;
     }
     SetDisplayId(displayID);
     SetNativeDisplayId(displayID);
     SetByteValue(UNIT_FIELD_BYTES_0, 2, minfo->gender);
     // Load creature equipment
     if (!data || data->equipmentId == 0)                    // use default from the template
         LoadEquipment();
     else
     {
         m_originalEquipmentId = data->equipmentId;
         LoadEquipment(data->equipmentId);
     }
     SetName(normalInfo->Name);                              // at normal entry always
     SetFloatValue(UNIT_MOD_CAST_SPEED, 1.0f);
     SetSpeed(MOVE_WALK,     cinfo->speed_walk);
     SetSpeed(MOVE_RUN,      cinfo->speed_run);
     SetSpeed(MOVE_SWIM, 1.0f);      // using 1.0 rate
     SetSpeed(MOVE_FLIGHT, 1.0f);    // using 1.0 rate
     // Will set UNIT_FIELD_BOUNDINGRADIUS and UNIT_FIELD_COMBATREACH
     SetObjectScale(cinfo->scale);
     SetFloatValue(UNIT_FIELD_HOVERHEIGHT, cinfo->HoverHeight);
     // checked at loading
     m_defaultMovementType = MovementGeneratorType(cinfo->MovementType);
     if (!m_wanderDistance && m_defaultMovementType == RANDOM_MOTION_TYPE)
         m_defaultMovementType = IDLE_MOTION_TYPE;
     for (uint8 i = 0; i < MAX_CREATURE_SPELLS; ++i)
         m_spells[i] = GetCreatureTemplate()->spells[i];
     return true;
 }
References ObjectMgr::ChooseDisplayId(), diff(), CreatureTemplate::DifficultyEntry, Entry, CreatureModelInfo::gender, GetCreatureTemplate(), CreatureTemplate::GetFirstValidModelId(), WorldObject::GetMap(), CreatureTemplate::HoverHeight, IDLE_MOTION_TYPE, Unit::IsPet(), Map::IsRaid(), LoadEquipment(), LOG_ERROR, m_creatureInfo, m_defaultMovementType, m_originalEquipmentId, m_spells, m_wanderDistance, MAX_CREATURE_SPELLS, MOVE_FLIGHT, MOVE_RUN, MOVE_SWIM, MOVE_WALK, CreatureTemplate::MovementType, CreatureTemplate::Name, RAID_DIFFICULTY_10MAN_HEROIC, RANDOM_MOTION_TYPE, CreatureTemplate::scale, Object::SetByteValue(), SetDisplayId(), Object::SetEntry(), Object::SetFloatValue(), WorldObject::SetName(), Unit::SetNativeDisplayId(), SetObjectScale(), Unit::SetSpeed(), sObjectMgr, CreatureTemplate::speed_run, CreatureTemplate::speed_walk, CreatureTemplate::spells, CreatureTemplate::unit_class, UNIT_FIELD_BYTES_0, UNIT_FIELD_HOVERHEIGHT, and UNIT_MOD_CAST_SPEED.
Referenced by Pet::Create(), and UpdateEntry().
InitializeReactState()
void Creature::InitializeReactState ()
Definition at line 1983 of file Creature.cpp.
 {
     if ((IsTotem() || IsTrigger() || IsCritter() || IsSpiritService()) && GetAIName() != "SmartAI" && !GetScriptId())
         SetReactState(REACT_PASSIVE);
     else
         SetReactState(REACT_AGGRESSIVE);
     /*else if (IsCivilian())
     SetReactState(REACT_DEFENSIVE);*/
 }
References GetAIName(), GetScriptId(), Unit::IsCritter(), Unit::IsSpiritService(), Unit::IsTotem(), IsTrigger(), REACT_AGGRESSIVE, REACT_PASSIVE, and SetReactState().
Referenced by Respawn(), and UpdateEntry().
IsAvoidingAOE()
bool Creature::IsAvoidingAOE () const inline
Definition at line 119 of file Creature.h.
 { return GetCreatureTemplate()->flags_extra & CREATURE_FLAG_EXTRA_AVOID_AOE; }
References CREATURE_FLAG_EXTRA_AVOID_AOE, CreatureTemplate::flags_extra, and GetCreatureTemplate().
Referenced by Acore::AnyUnfriendlyUnitInObjectRangeCheck::operator()(), Acore::AnyUnfriendlyNoTotemUnitInObjectRangeCheck::operator()(), and Acore::WorldObjectSpellAreaTargetCheck::operator()().
isCanInteractWithBattleMaster()
bool Creature::isCanInteractWithBattleMaster (Player * player, bool msg) const
Definition at line 1058 of file Creature.cpp.
 {
     if (!IsBattleMaster())
         return false;
     BattlegroundTypeId bgTypeId = sBattlegroundMgr->GetBattleMasterBG(GetEntry());
     if (!msg)
         return player->GetBGAccessByLevel(bgTypeId);
     if (!player->GetBGAccessByLevel(bgTypeId))
     {
         ClearGossipMenuFor(player);
         switch (bgTypeId)
         {
             case BATTLEGROUND_AV:
                 SendGossipMenuFor(player, 7616, this);
                 break;
             case BATTLEGROUND_WS:
                 SendGossipMenuFor(player, 7599, this);
                 break;
             case BATTLEGROUND_AB:
                 SendGossipMenuFor(player, 7642, this);
                 break;
             case BATTLEGROUND_EY:
             case BATTLEGROUND_NA:
             case BATTLEGROUND_BE:
             case BATTLEGROUND_AA:
             case BATTLEGROUND_RL:
             case BATTLEGROUND_SA:
             case BATTLEGROUND_DS:
             case BATTLEGROUND_RV:
                 SendGossipMenuFor(player, 10024, this);
                 break;
             default:
                 break;
         }
         return false;
     }
     return true;
 }
References BATTLEGROUND_AA, BATTLEGROUND_AB, BATTLEGROUND_AV, BATTLEGROUND_BE, BATTLEGROUND_DS, BATTLEGROUND_EY, BATTLEGROUND_NA, BATTLEGROUND_RL, BATTLEGROUND_RV, BATTLEGROUND_SA, BATTLEGROUND_WS, ClearGossipMenuFor(), Player::GetBGAccessByLevel(), Object::GetEntry(), Unit::IsBattleMaster(), sBattlegroundMgr, and SendGossipMenuFor().
isCanTrainingAndResetTalentsOf()
bool Creature::isCanTrainingAndResetTalentsOf (Player * player) const
Definition at line 1099 of file Creature.cpp.
 {
     return player->getLevel() >= 10
            && GetCreatureTemplate()->trainer_type == TRAINER_TYPE_CLASS
            && player->getClass() == GetCreatureTemplate()->trainer_class;
 }
References Unit::getClass(), GetCreatureTemplate(), Unit::getLevel(), CreatureTemplate::trainer_class, CreatureTemplate::trainer_type, and TRAINER_TYPE_CLASS.
Referenced by WorldSession::HandleTalentWipeConfirmOpcode().
IsCivilian()
bool Creature::IsCivilian () const inline
Definition at line 74 of file Creature.h.
 { return GetCreatureTemplate()->flags_extra & CREATURE_FLAG_EXTRA_CIVILIAN; }
References CREATURE_FLAG_EXTRA_CIVILIAN, CreatureTemplate::flags_extra, and GetCreatureTemplate().
Referenced by CanAssistTo(), CanStartAttack(), AggressorAI::Permissible(), ReactorAI::Permissible(), CreatureAI::TriggerAlert(), and UpdateMoveInLineOfSightState().
IsDamageEnoughForLootingAndReward()
bool Creature::IsDamageEnoughForLootingAndReward () const inline
Definition at line 341 of file Creature.h.
 { return (m_creatureInfo->flags_extra & CREATURE_FLAG_EXTRA_NO_PLAYER_DAMAGE_REQ) || (m_PlayerDamageReq == 0); }
References CREATURE_FLAG_EXTRA_NO_PLAYER_DAMAGE_REQ, CreatureTemplate::flags_extra, m_creatureInfo, and m_PlayerDamageReq.
Referenced by Player::isAllowedToLoot(), boss_twilight_halion::boss_twilight_halionAI::JustDied(), and Unit::Kill().
IsDungeonBoss()
bool Creature::IsDungeonBoss () const
Definition at line 2862 of file Creature.cpp.
 {
     if (GetOwnerGUID().IsPlayer())
         return false;
     CreatureTemplate const* cinfo = sObjectMgr->GetCreatureTemplate(GetEntry());
     return cinfo && (cinfo->flags_extra & CREATURE_FLAG_EXTRA_DUNGEON_BOSS);
 }
References CREATURE_FLAG_EXTRA_DUNGEON_BOSS, CreatureTemplate::flags_extra, Object::GetEntry(), Unit::GetOwnerGUID(), Object::IsPlayer(), and sObjectMgr.
Referenced by spell_dk_death_grip::HandleBaseDummy(), WorldSession::HandlePetActionHelper(), IsSpellProhibited(), SetLootRecipient(), and Unit::UpdateSpeed().
isElite()
bool Creature::isElite () const inline
Definition at line 100 of file Creature.h.
     {
         if (IsPet())
             return false;
         uint32 rank = GetCreatureTemplate()->rank;
         return rank != CREATURE_ELITE_NORMAL && rank != CREATURE_ELITE_RARE;
     }
References CREATURE_ELITE_NORMAL, CREATURE_ELITE_RARE, GetCreatureTemplate(), Unit::IsPet(), and CreatureTemplate::rank.
Referenced by Spell::EffectSkinning(), and Acore::XP::Gain().
IsEvadingAttacks()
bool Creature::IsEvadingAttacks () const inline
Definition at line 124 of file Creature.h.
 { return IsInEvadeMode() || CanNotReachTarget(); }
References CanNotReachTarget(), and IsInEvadeMode().
Referenced by Unit::Attack(), Unit::DealDamageMods(), Unit::DealMeleeDamage(), Unit::DealSpellDamage(), Unit::RollMeleeOutcomeAgainst(), and Unit::SpellHitResult().
IsFreeToMove()
bool Creature::IsFreeToMove ()
Definition at line 782 of file Creature.cpp.
 {
     uint32 moveFlags = m_movementInfo.GetMovementFlags();
     // Do not reposition ourself when we are not allowed to move
     if ((IsMovementPreventedByCasting() || isMoving() || !CanFreeMove()) &&
         (GetMotionMaster()->GetCurrentMovementGeneratorType() != CHASE_MOTION_TYPE ||
         moveFlags & MOVEMENTFLAG_SPLINE_ENABLED))
     {
         return false;
     }
     return true;
 }
References Unit::CanFreeMove(), CHASE_MOTION_TYPE, Unit::GetMotionMaster(), MovementInfo::GetMovementFlags(), IsMovementPreventedByCasting(), Unit::isMoving(), WorldObject::m_movementInfo, and MOVEMENTFLAG_SPLINE_ENABLED.
Referenced by CreatureAI::MoveBackwardsChecks(), and CreatureAI::MoveCircleChecks().
IsGuard()
bool Creature::IsGuard () const inline
Definition at line 76 of file Creature.h.
 { return GetCreatureTemplate()->flags_extra & CREATURE_FLAG_EXTRA_GUARD; }
References CREATURE_FLAG_EXTRA_GUARD, CreatureTemplate::flags_extra, and GetCreatureTemplate().
Referenced by _CanDetectFeignDeathOf(), GuardAI::Permissible(), and FactorySelector::selectAI().
IsImmunedToSpell()
bool Creature::IsImmunedToSpell (SpellInfo const * spellInfo) override virtual
Reimplemented from Unit.
Definition at line 2028 of file Creature.cpp.
 {
     if (!spellInfo)
         return false;
     // Xinef: this should exclude self casts...
     // Spells that don't have effectMechanics.
     if (spellInfo->Mechanic > MECHANIC_NONE && HasMechanicTemplateImmunity(1 << (spellInfo->Mechanic - 1)))
         return true;
     // This check must be done instead of 'if (GetCreatureTemplate()->MechanicImmuneMask & (1 << (spellInfo->Mechanic - 1)))' for not break
     // the check of mechanic immunity on DB (tested) because GetCreatureTemplate()->MechanicImmuneMask and m_spellImmune[IMMUNITY_MECHANIC] don't have same data.
     bool immunedToAllEffects = true;
     for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
         if (spellInfo->Effects[i].IsEffect() && !IsImmunedToSpellEffect(spellInfo, i))
         {
             immunedToAllEffects = false;
             break;
         }
     if (immunedToAllEffects)
         return true;
     return Unit::IsImmunedToSpell(spellInfo);
 }
References SpellInfo::Effects, HasMechanicTemplateImmunity(), Unit::IsImmunedToSpell(), IsImmunedToSpellEffect(), MAX_SPELL_EFFECTS, SpellInfo::Mechanic, and MECHANIC_NONE.
IsImmunedToSpellEffect()
bool Creature::IsImmunedToSpellEffect (SpellInfo const * spellInfo, uint32 index) const override virtual
Reimplemented from Unit.
Reimplemented in Totem.
Definition at line 2053 of file Creature.cpp.
 {
     // Xinef: this should exclude self casts...
     if (spellInfo->Effects[index].Mechanic > MECHANIC_NONE && HasMechanicTemplateImmunity(1 << (spellInfo->Effects[index].Mechanic - 1)))
         return true;
     if (GetCreatureTemplate()->type == CREATURE_TYPE_MECHANICAL && spellInfo->Effects[index].Effect == SPELL_EFFECT_HEAL)
         return true;
     return Unit::IsImmunedToSpellEffect(spellInfo, index);
 }
References CREATURE_TYPE_MECHANICAL, SpellInfo::Effects, GetCreatureTemplate(), HasMechanicTemplateImmunity(), index, Unit::IsImmunedToSpellEffect(), MECHANIC_NONE, and SPELL_EFFECT_HEAL.
Referenced by IsImmunedToSpell(), and Totem::IsImmunedToSpellEffect().
IsImmuneToKnockback()
bool Creature::IsImmuneToKnockback () const
Definition at line 2871 of file Creature.cpp.
 {
     if (GetOwnerGUID().IsPlayer())
         return false;
     CreatureTemplate const* cinfo = sObjectMgr->GetCreatureTemplate(GetEntry());
     return cinfo && (cinfo->flags_extra & CREATURE_FLAG_EXTRA_IMMUNITY_KNOCKBACK);
 }
References CREATURE_FLAG_EXTRA_IMMUNITY_KNOCKBACK, CreatureTemplate::flags_extra, Object::GetEntry(), Unit::GetOwnerGUID(), Object::IsPlayer(), and sObjectMgr.
IsInEvadeMode()
bool Creature::IsInEvadeMode () const inline
Definition at line 123 of file Creature.h.
 { return HasUnitState(UNIT_STATE_EVADE); }
References Unit::HasUnitState(), and UNIT_STATE_EVADE.
Referenced by CreatureAI::_EnterEvadeMode(), npc_escortAI::AssistPlayerInCombat(), Unit::Attack(), CanAssistTo(), CanCreatureAttack(), boss_sindragosa::boss_sindragosaAI::DamageTaken(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction(), Spell::DoSpellHitOnUnit(), CreatureAI::DoZoneInCombat(), ScriptedAI::EnterEvadeIfOutOfCombatArea(), SmartAI::EnterEvadeMode(), npc_pos_freed_slave::npc_pos_freed_slaveAI::EnterEvadeMode(), npc_pet_mage_mirror_image::EnterEvadeMode(), Vehicle::InstallAccessory(), IsEvadingAttacks(), boss_professor_putricide::boss_professor_putricideAI::JustSummoned(), boss_rotface::boss_rotfaceAI::JustSummoned(), boss_the_lich_king::boss_the_lich_kingAI::KilledUnit(), CreatureGroup::MemberEvaded(), Spell::prepare(), npc_tirion_fordring_tft::npc_tirion_fordringAI::sGossipSelect(), boss_prince_keleseth_icc::boss_prince_kelesethAI::SpellHit(), boss_prince_taldaram_icc::boss_prince_taldaramAI::SpellHit(), boss_prince_valanar_icc::boss_prince_valanarAI::SpellHit(), Update(), SimpleCharmedAI::UpdateAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::UpdateAI(), npc_simone::npc_simoneAI::UpdateAI(), and Player::UpdateCharmedAI().
IsInvisibleDueToDespawn()
bool Creature::IsInvisibleDueToDespawn () const override protected virtual
Reimplemented from WorldObject.
Definition at line 1717 of file Creature.cpp.
 {
     if (Unit::IsInvisibleDueToDespawn())
         return true;
     if (IsAlive() || m_corpseRemoveTime > time(nullptr))
         return false;
     return true;
 }
References Unit::IsAlive(), WorldObject::IsInvisibleDueToDespawn(), and m_corpseRemoveTime.
IsMoveInLineOfSightDisabled()
bool Creature::IsMoveInLineOfSightDisabled () inline
Definition at line 262 of file Creature.h.
 { return m_moveInLineOfSightDisabled; }
References m_moveInLineOfSightDisabled.
Referenced by CreatureAI::MoveInLineOfSight().
IsMoveInLineOfSightStrictlyDisabled()
bool Creature::IsMoveInLineOfSightStrictlyDisabled () inline
Definition at line 263 of file Creature.h.
 { return m_moveInLineOfSightStrictlyDisabled; }
References m_moveInLineOfSightStrictlyDisabled.
Referenced by Acore::CreatureRelocationNotifier::Visit().
IsMovementPreventedByCasting()
bool Creature::IsMovementPreventedByCasting () const override virtual
Reimplemented from Unit.
Definition at line 3381 of file Creature.cpp.
 {
     Spell* spell = m_currentSpells[CURRENT_CHANNELED_SPELL];
     // first check if currently a movement allowed channel is active and we're not casting
     if (spell && spell->getState() != SPELL_STATE_FINISHED && spell->IsChannelActive() && spell->GetSpellInfo()->IsMoveAllowedChannel())
     {
         return false;
     }
     if (HasSpellFocus())
     {
         return true;
     }
     if (HasUnitState(UNIT_STATE_CASTING))
     {
         return true;
     }
     return false;
 }
References CURRENT_CHANNELED_SPELL, Spell::GetSpellInfo(), Spell::getState(), HasSpellFocus(), Unit::HasUnitState(), Spell::IsChannelActive(), SpellInfo::IsMoveAllowedChannel(), Unit::m_currentSpells, SPELL_STATE_FINISHED, and UNIT_STATE_CASTING.
Referenced by WaypointMovementGenerator< Creature >::DoUpdate(), RandomMovementGenerator< T >::DoUpdate(), ChaseMovementGenerator< T >::DoUpdate(), FollowMovementGenerator< T >::DoUpdate(), IsFreeToMove(), and WaypointMovementGenerator< Creature >::StartMove().
IsNotReachable()
bool Creature::IsNotReachable () const inline
Definition at line 310 of file Creature.h.
 { return (m_cannotReachTimer >= (sWorld->getIntConfig(CONFIG_NPC_EVADE_IF_NOT_REACHABLE) * IN_MILLISECONDS)) && m_cannotReachTarget; }
References CONFIG_NPC_EVADE_IF_NOT_REACHABLE, IN_MILLISECONDS, m_cannotReachTarget, m_cannotReachTimer, and sWorld.
Referenced by Update().
IsNotReachableAndNeedRegen()
bool Creature::IsNotReachableAndNeedRegen () const inline
Definition at line 311 of file Creature.h.
 { return (m_cannotReachTimer >= (sWorld->getIntConfig(CONFIG_NPC_REGEN_TIME_IF_NOT_REACHABLE_IN_RAID) * IN_MILLISECONDS)) && m_cannotReachTarget; }
References CONFIG_NPC_REGEN_TIME_IF_NOT_REACHABLE_IN_RAID, IN_MILLISECONDS, m_cannotReachTarget, m_cannotReachTimer, and sWorld.
Referenced by Update().
IsRacialLeader()
bool Creature::IsRacialLeader () const inline
Definition at line 73 of file Creature.h.
 { return GetCreatureTemplate()->RacialLeader; }
References GetCreatureTemplate(), and CreatureTemplate::RacialLeader.
Referenced by Player::RewardHonor().
isRegeneratingHealth()
bool Creature::isRegeneratingHealth () inline
Definition at line 297 of file Creature.h.
 { return m_regenHealth; }
References m_regenHealth.
Referenced by boss_felblood_kaelthas::boss_felblood_kaelthasAI::DamageTaken(), npc_crystalline_frayer::npc_crystalline_frayerAI::EnterEvadeMode(), and RegenerateHealth().
IsReputationGainDisabled()
bool Creature::IsReputationGainDisabled () const inline
Definition at line 340 of file Creature.h.
 { return DisableReputationGain; }
References DisableReputationGain.
Referenced by Player::RewardReputation().
IsSpellProhibited()
bool Creature::IsSpellProhibited (SpellSchoolMask idSchoolMask) const
Definition at line 2568 of file Creature.cpp.
 {
     const CreatureTemplate* cinfo = GetCreatureTemplate();
     if (!(cinfo && cinfo->flags_extra & CREATURE_FLAG_EXTRA_ALL_DIMINISH) && (isWorldBoss() || IsDungeonBoss()))
         return false;
     for (uint8 i = SPELL_SCHOOL_NORMAL; i < MAX_SPELL_SCHOOL; ++i)
         if (idSchoolMask & (1 << i))
             if (m_ProhibitSchoolTime[i] >= World::GetGameTimeMS())
                 return true;
     return false;
 }
References CREATURE_FLAG_EXTRA_ALL_DIMINISH, CreatureTemplate::flags_extra, GetCreatureTemplate(), World::GetGameTimeMS(), IsDungeonBoss(), isWorldBoss(), m_ProhibitSchoolTime, MAX_SPELL_SCHOOL, and SPELL_SCHOOL_NORMAL.
Referenced by Spell::CheckCast(), and SmartScript::ProcessAction().
isTappedBy()
bool Creature::isTappedBy (Player const * player) const
Definition at line 1222 of file Creature.cpp.
 {
     if (player->GetGUID() == m_lootRecipient)
         return true;
     Group const* playerGroup = player->GetGroup();
     if (!playerGroup || playerGroup != GetLootRecipientGroup()) // if we dont have a group we arent the recipient
         return false;                                           // if creature doesnt have group bound it means it was solo killed by someone else
     return true;
 }
References Player::GetGroup(), Object::GetGUID(), GetLootRecipientGroup(), and m_lootRecipient.
Referenced by Unit::BuildValuesUpdate().
IsTrigger()
bool Creature::IsTrigger () const inline
Definition at line 75 of file Creature.h.
 { return GetCreatureTemplate()->flags_extra & CREATURE_FLAG_EXTRA_TRIGGER; }
References CREATURE_FLAG_EXTRA_TRIGGER, CreatureTemplate::flags_extra, and GetCreatureTemplate().
Referenced by Unit::CombatStart(), Unit::CombatStartOnCast(), InitializeReactState(), TempSummon::InitStats(), boss_muru::boss_muruAI::JustSummoned(), boss_anub_arak::boss_anub_arakAI::JustSummoned(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::JustSummoned(), Acore::AnyUnfriendlyNoTotemUnitInObjectRangeCheck::operator()(), FactorySelector::selectAI(), Unit::SetInCombatWith(), Spell::SummonGuardian(), UpdateEntry(), UpdateMoveInLineOfSightState(), and Player::UpdateTriggerVisibility().
IsValidTrainerForPlayer()
bool Creature::IsValidTrainerForPlayer (Player * player, uint32 * npcFlags = nullptr) const
Definition at line 1106 of file Creature.cpp.
 {
     if (!IsTrainer())
     {
         return false;
     }
     switch (m_creatureInfo->trainer_type)
     {
         case TRAINER_TYPE_CLASS:
         case TRAINER_TYPE_PETS:
             if (m_creatureInfo->trainer_class && m_creatureInfo->trainer_class != player->getClass())
             {
                 if (npcFlags)
                     *npcFlags &= ~UNIT_NPC_FLAG_TRAINER_CLASS;
                 return false;
             }
             break;
         case TRAINER_TYPE_MOUNTS:
             if (m_creatureInfo->trainer_race && m_creatureInfo->trainer_race != player->getRace())
             {
                 return false;
             }
             break;
         case TRAINER_TYPE_TRADESKILLS:
             if (m_creatureInfo->trainer_spell && !player->HasSpell(m_creatureInfo->trainer_spell))
             {
                 if (npcFlags)
                     *npcFlags &= ~UNIT_NPC_FLAG_TRAINER_PROFESSION;
                 return false;
             }
             break;
         default:
             break;
     }
     return true;
 }
References Unit::getClass(), Unit::getRace(), Player::HasSpell(), Unit::IsTrainer(), m_creatureInfo, CreatureTemplate::trainer_class, CreatureTemplate::trainer_race, CreatureTemplate::trainer_spell, CreatureTemplate::trainer_type, TRAINER_TYPE_CLASS, TRAINER_TYPE_MOUNTS, TRAINER_TYPE_PETS, TRAINER_TYPE_TRADESKILLS, UNIT_NPC_FLAG_TRAINER_CLASS, and UNIT_NPC_FLAG_TRAINER_PROFESSION.
Referenced by Unit::BuildValuesUpdate().
isVendorWithIconSpeak()
bool Creature::isVendorWithIconSpeak () const
Definition at line 1523 of file Creature.cpp.
 {
     return m_creatureInfo->IconName == "Speak" && m_creatureData->npcflag & UNIT_NPC_FLAG_VENDOR;
 }
References CreatureTemplate::IconName, m_creatureData, m_creatureInfo, CreatureData::npcflag, and UNIT_NPC_FLAG_VENDOR.
isWorldBoss()
bool Creature::isWorldBoss () const inline
Definition at line 109 of file Creature.h.
     {
         if (IsPet())
             return false;
         return GetCreatureTemplate()->type_flags & CREATURE_TYPE_FLAG_BOSS_MOB;
     }
References CREATURE_TYPE_FLAG_BOSS_MOB, GetCreatureTemplate(), Unit::IsPet(), and CreatureTemplate::type_flags.
Referenced by Vehicle::ApplyAllImmunities(), CanCreatureAttack(), spell_item_lil_phylactery::CheckProc(), Unit::DealMeleeDamage(), Spell::DoSpellHitOnUnit(), getLevelForTarget(), Unit::GetUnitDodgeChance(), spell_dk_death_grip::HandleBaseDummy(), WorldSession::HandlePetActionHelper(), IsSpellProhibited(), hyjal_trashAI::JustDied(), setDeathState(), SetLootRecipient(), and hyjalAI::SummonCreature().
LoadCreatureFromDB()
bool Creature::LoadCreatureFromDB (ObjectGuid::LowType guid, Map * map, bool addToMap = true, bool gridLoad = false, bool allowDuplicate = false)
Definition at line 1528 of file Creature.cpp.
 {
     if (!allowDuplicate)
     {
         // If an alive instance of this spawnId is already found, skip creation
         // If only dead instance(s) exist, despawn them and spawn a new (maybe also dead) version
         const auto creatureBounds = map->GetCreatureBySpawnIdStore().equal_range(spawnId);
         std::vector <Creature*> despawnList;
         if (creatureBounds.first != creatureBounds.second)
         {
             for (auto itr = creatureBounds.first; itr != creatureBounds.second; ++itr)
             {
                 if (itr->second->IsAlive())
                 {
                     LOG_DEBUG("maps", "Would have spawned %u but %s already exists", spawnId, creatureBounds.first->second->GetGUID().ToString().c_str());
                     return false;
                 }
                 else
                 {
                     despawnList.push_back(itr->second);
                     LOG_DEBUG("maps", "Despawned dead instance of spawn %u (%s)", spawnId, itr->second->GetGUID().ToString().c_str());
                 }
             }
             for (Creature* despawnCreature : despawnList)
             {
                 despawnCreature->AddObjectToRemoveList();
             }
         }
     }
     CreatureData const* data = sObjectMgr->GetCreatureData(spawnId);
     if (!data)
     {
         LOG_ERROR("sql.sql", "Creature (SpawnId: %u) not found in table `creature`, can't load. ", spawnId);
         return false;
     }
     // xinef: fix shitness from db
     if ((addToMap || gridLoad) && !data->overwrittenZ)
     {
         float tz = map->GetHeight(data->posX, data->posY, data->posZ + 1.0f, true);
         if (tz >= data->posZ && tz - data->posZ <= 1.0f)
             const_cast<CreatureData*>(data)->posZ = tz + 0.1f;
         const_cast<CreatureData*>(data)->overwrittenZ = true;
     }
     // xinef: this has to be assigned before Create function, properly loads equipment id from DB
     m_creatureData = data;
     m_spawnId = spawnId;
     if (!Create(map->GenerateLowGuid<HighGuid::Unit>(), map, data->phaseMask, data->id, 0, data->posX, data->posY, data->posZ, data->orientation, data))
         return false;
     //We should set first home position, because then AI calls home movement
     SetHomePosition(data->posX, data->posY, data->posZ, data->orientation);
     m_wanderDistance = data->wander_distance;
     m_respawnDelay = data->spawntimesecs;
     m_deathState = ALIVE;
     m_respawnTime  = GetMap()->GetCreatureRespawnTime(m_spawnId);
     if (m_respawnTime)                          // respawn on Update
     {
         m_deathState = DEAD;
         if (CanFly())
         {
             float tz = map->GetHeight(GetPhaseMask(), data->posX, data->posY, data->posZ, true, MAX_FALL_DISTANCE);
             if (data->posZ - tz > 0.1f && Acore::IsValidMapCoord(tz))
             {
                 Relocate(data->posX, data->posY, tz);
             }
         }
     }
     uint32 curhealth;
     if (!m_regenHealth)
     {
         curhealth = data->curhealth;
         if (curhealth)
         {
             curhealth = uint32(curhealth * _GetHealthMod(GetCreatureTemplate()->rank));
             if (curhealth < 1)
                 curhealth = 1;
         }
         SetPower(POWER_MANA, data->curmana);
     }
     else
     {
         curhealth = GetMaxHealth();
         SetPower(POWER_MANA, GetMaxPower(POWER_MANA));
     }
     SetHealth(m_deathState == ALIVE ? curhealth : 0);
     // checked at creature_template loading
     m_defaultMovementType = MovementGeneratorType(data->movementType);
     if (addToMap && !GetMap()->AddToMap(this))
         return false;
     return true;
 }
References _GetHealthMod(), ALIVE, CanFly(), Create(), DEAD, Map::GenerateLowGuid(), Map::GetCreatureBySpawnIdStore(), Map::GetCreatureRespawnTime(), GetCreatureTemplate(), Map::GetHeight(), WorldObject::GetMap(), Unit::GetMaxHealth(), Unit::GetMaxPower(), WorldObject::GetPhaseMask(), Acore::IsValidMapCoord(), LOG_DEBUG, LOG_ERROR, m_creatureData, Unit::m_deathState, m_defaultMovementType, m_regenHealth, m_respawnDelay, m_respawnTime, m_spawnId, m_wanderDistance, MAX_FALL_DISTANCE, POWER_MANA, Position::Relocate(), Unit::SetHealth(), SetHomePosition(), Unit::SetPower(), sObjectMgr, and Unit.
Referenced by ObjectMgr::AddCreData(), MotionTransport::CreateNPCPassenger(), GameEventMgr::GameEventSpawn(), npc_commandscript::HandleNpcAddCommand(), wp_commandscript::HandleWpModifyCommand(), wp_commandscript::HandleWpShowCommand(), LoadFromDB(), and PoolGroup< T >::Spawn1Object().
LoadCreaturesAddon()
bool Creature::LoadCreaturesAddon (bool reload = false)
Suspected correlation between UNIT_FIELD_BYTES_1, offset 3, value 0x2: If no inhabittype_fly (if no MovementFlag_DisableGravity or MovementFlag_CanFly flag found in sniffs) Check using InhabitType as movement flags are assigned dynamically basing on whether the creature is in air or not Set MovementFlag_Hover. Otherwise do nothing.
Definition at line 2457 of file Creature.cpp.
 {
     CreatureAddon const* cainfo = GetCreatureAddon();
     if (!cainfo)
         return false;
     if (cainfo->mount != 0)
         Mount(cainfo->mount);
     if (cainfo->bytes1 != 0)
     {
         // 0 StandState
         // 1 FreeTalentPoints   Pet only, so always 0 for default creature
         // 2 StandFlags
         // 3 StandMiscFlags
         SetByteValue(UNIT_FIELD_BYTES_1, UNIT_BYTES_1_OFFSET_STAND_STATE, uint8(cainfo->bytes1 & 0xFF));
         //SetByteValue(UNIT_FIELD_BYTES_1, UNIT_BYTES_1_OFFSET_PET_TALENTS, uint8((cainfo->bytes1 >> 8) & 0xFF));
         SetByteValue(UNIT_FIELD_BYTES_1, UNIT_BYTES_1_OFFSET_PET_TALENTS, 0);
         SetByteValue(UNIT_FIELD_BYTES_1, UNIT_BYTES_1_OFFSET_VIS_FLAG, uint8((cainfo->bytes1 >> 16) & 0xFF));
         m_originalAnimTier =  uint8((cainfo->bytes1 >> 24) & 0xFF);
         SetByteValue(UNIT_FIELD_BYTES_1, UNIT_BYTES_1_OFFSET_ANIM_TIER, m_originalAnimTier);
         if (GetByteValue(UNIT_FIELD_BYTES_1, 3) & UNIT_BYTE1_FLAG_HOVER /*&& !(GetCreatureTemplate()->InhabitType & INHABIT_AIR)*/)
             AddUnitMovementFlag(MOVEMENTFLAG_HOVER);
     }
     if (cainfo->bytes2 != 0)
     {
         // 0 SheathState
         // 1 Bytes2Flags
         // 2 UnitRename         Pet only, so always 0 for default creature
         // 3 ShapeshiftForm     Must be determined/set by shapeshift spell/aura
         SetByteValue(UNIT_FIELD_BYTES_2, 0, uint8(cainfo->bytes2 & 0xFF));
         //SetByteValue(UNIT_FIELD_BYTES_2, 1, uint8((cainfo->bytes2 >> 8) & 0xFF));
         //SetByteValue(UNIT_FIELD_BYTES_2, 2, uint8((cainfo->bytes2 >> 16) & 0xFF));
         SetByteValue(UNIT_FIELD_BYTES_2, 2, 0);
         //SetByteValue(UNIT_FIELD_BYTES_2, 3, uint8((cainfo->bytes2 >> 24) & 0xFF));
         SetByteValue(UNIT_FIELD_BYTES_2, 3, 0);
     }
     // Check if Creature is Large
     if (cainfo->isLarge)
         SetVisibilityDistanceOverride(true);
     if (cainfo->emote != 0)
         SetUInt32Value(UNIT_NPC_EMOTESTATE, cainfo->emote);
     //Load Path
     if (cainfo->path_id != 0)
     {
         if (sWorld->getBoolConfig(CONFIG_SET_ALL_CREATURES_WITH_WAYPOINT_MOVEMENT_ACTIVE))
             setActive(true);
         m_path_id = cainfo->path_id;
     }
     if (!cainfo->auras.empty())
     {
         for (std::vector<uint32>::const_iterator itr = cainfo->auras.begin(); itr != cainfo->auras.end(); ++itr)
         {
             SpellInfo const* AdditionalSpellInfo = sSpellMgr->GetSpellInfo(*itr);
             if (!AdditionalSpellInfo)
             {
                 LOG_ERROR("sql.sql", "Creature (%s) has wrong spell %u defined in `auras` field.", GetGUID().ToString().c_str(), *itr);
                 continue;
             }
             // skip already applied aura
             if (HasAura(*itr))
             {
                 if (!reload)
                     LOG_ERROR("sql.sql", "Creature (%s) has duplicate aura (spell %u) in `auras` field.", GetGUID().ToString().c_str(), *itr);
                 continue;
             }
             AddAura(*itr, this);
             LOG_DEBUG("entities.unit", "Spell: %u added to creature (%s)", *itr, GetGUID().ToString().c_str());
         }
     }
     return true;
 }
References Unit::AddAura(), Unit::AddUnitMovementFlag(), CreatureAddon::auras, CreatureAddon::bytes1, CreatureAddon::bytes2, CONFIG_SET_ALL_CREATURES_WITH_WAYPOINT_MOVEMENT_ACTIVE, CreatureAddon::emote, Object::GetByteValue(), GetCreatureAddon(), Object::GetGUID(), Unit::HasAura(), CreatureAddon::isLarge, LOG_DEBUG, LOG_ERROR, m_originalAnimTier, m_path_id, CreatureAddon::mount, Unit::Mount(), MOVEMENTFLAG_HOVER, CreatureAddon::path_id, WorldObject::setActive(), Object::SetByteValue(), Object::SetUInt32Value(), WorldObject::SetVisibilityDistanceOverride(), sSpellMgr, sWorld, Position::ToString(), UNIT_BYTE1_FLAG_HOVER, UNIT_BYTES_1_OFFSET_ANIM_TIER, UNIT_BYTES_1_OFFSET_PET_TALENTS, UNIT_BYTES_1_OFFSET_STAND_STATE, UNIT_BYTES_1_OFFSET_VIS_FLAG, UNIT_FIELD_BYTES_1, UNIT_FIELD_BYTES_2, and UNIT_NPC_EMOTESTATE.
Referenced by CreatureAI::_EnterEvadeMode(), Create(), HomeMovementGenerator< Creature >::DoFinalize(), boss_doomrel::boss_doomrelAI::EnterEvadeMode(), hyjalAI::EnterEvadeMode(), npc_pos_freed_slave::npc_pos_freed_slaveAI::EnterEvadeMode(), npc_pet_hunter_snake_trap::EnterEvadeMode(), boss_urom::boss_uromAI::LeaveCombat(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::Reset(), npc_valithria_cloud::npc_valithria_cloudAI::Reset(), and setDeathState().
LoadEquipment()
void Creature::LoadEquipment (int8 id = 1, bool force = false)
Definition at line 1641 of file Creature.cpp.
 {
     if (id == 0)
     {
         if (force)
         {
             for (uint8 i = 0; i < MAX_EQUIPMENT_ITEMS; ++i)
                 SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + i, 0);
             m_equipmentId = 0;
         }
         return;
     }
     EquipmentInfo const* einfo = sObjectMgr->GetEquipmentInfo(GetEntry(), id);
     if (!einfo)
         return;
     m_equipmentId = id;
     for (uint8 i = 0; i < 3; ++i)
         SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + i, einfo->ItemEntry[i]);
 }
References Object::GetEntry(), EquipmentInfo::ItemEntry, m_equipmentId, MAX_EQUIPMENT_ITEMS, Object::SetUInt32Value(), sObjectMgr, and UNIT_VIRTUAL_ITEM_SLOT_ID.
Referenced by Spell::EffectScriptEffect(), spell_boss_magus_telestra_summon_telestra_clones::spell_boss_magus_telestra_summon_telestra_clones_AuraScript::HandleApply(), spell_boss_magus_telestra_summon_telestra_clones::spell_boss_magus_telestra_summon_telestra_clones_AuraScript::HandleRemove(), InitEntry(), npc_unworthy_initiate::npc_unworthy_initiateAI::MovementInform(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), spell_illidan_demon_transform1::spell_illidan_demon_transform1_AuraScript::OnPeriodic(), spell_illidan_demon_transform2::spell_illidan_demon_transform2_AuraScript::OnPeriodic(), boss_mr_smite::boss_mr_smiteAI::Reset(), npc_unworthy_initiate::npc_unworthy_initiateAI::Reset(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::Reset(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::Reset(), boss_illidan_stormrage::boss_illidan_stormrageAI::Reset(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::Reset(), ScriptedAI::SetEquipmentSlots(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::SummonedCreatureDies(), boss_mr_smite::boss_mr_smiteAI::UpdateAI(), npc_forest_frog::npc_forest_frogAI::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::UpdateAI(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI(), and npc_koltira_deathweaver::npc_koltira_deathweaverAI::WaypointReached().
LoadFromDB()
bool Creature::LoadFromDB (ObjectGuid::LowType guid, Map * map, bool allowDuplicate = false) inline
Definition at line 204 of file Creature.h.
 { return LoadCreatureFromDB(guid, map, false, true, allowDuplicate); }
References LoadCreatureFromDB().
LoadPath()
void Creature::LoadPath (uint32 pathid) inline
Definition at line 327 of file Creature.h.
 { m_path_id = pathid; }
References m_path_id.
Referenced by npc_commandscript::HandleNpcSetMoveTypeCommand(), wp_commandscript::HandleWpLoadCommand(), and wp_commandscript::HandleWpUnLoadCommand().
LoadSpellTemplateImmunity()
void Creature::LoadSpellTemplateImmunity ()
Definition at line 1998 of file Creature.cpp.
 {
     // uint32 max used for "spell id", the immunity system will not perform SpellInfo checks against invalid spells
     // used so we know which immunities were loaded from template
     static uint32 const placeholderSpellId = std::numeric_limits<uint32>::max();
     // unapply template immunities (in case we're updating entry)
     for (uint8 i = SPELL_SCHOOL_NORMAL; i <= SPELL_SCHOOL_ARCANE; ++i)
     {
         ApplySpellImmune(placeholderSpellId, IMMUNITY_SCHOOL, i, false);
     }
     // don't inherit immunities for hunter pets
     if (GetOwnerGUID().IsPlayer() && IsHunterPet())
     {
         return;
     }
     if (uint8 mask = GetCreatureTemplate()->SpellSchoolImmuneMask)
     {
         for (uint8 i = SPELL_SCHOOL_NORMAL; i <= SPELL_SCHOOL_ARCANE; ++i)
         {
             if (mask & (1 << i))
             {
                 ApplySpellImmune(placeholderSpellId, IMMUNITY_SCHOOL, 1 << i, true);
             }
         }
     }
 }
References Unit::ApplySpellImmune(), GetCreatureTemplate(), Unit::GetOwnerGUID(), IMMUNITY_SCHOOL, Unit::IsHunterPet(), Object::IsPlayer(), max, SPELL_SCHOOL_ARCANE, and SPELL_SCHOOL_NORMAL.
Referenced by UpdateEntry().
LowerPlayerDamageReq()
void Creature::LowerPlayerDamageReq (uint32 unDamage) inline
Definition at line 342 of file Creature.h.
     {
         if (m_PlayerDamageReq)
             m_PlayerDamageReq > unDamage ? m_PlayerDamageReq -= unDamage : m_PlayerDamageReq = 0;
     }
References m_PlayerDamageReq.
Referenced by npc_heated_battle::npc_heated_battleAI::DamageTaken(), boss_razuvious::boss_razuviousAI::DamageTaken(), boss_kologarn::boss_kologarnAI::DamageTaken(), Unit::DealDamage(), boss_xt002::boss_xt002AI::DoAction(), boss_yoggsaron::boss_yoggsaronAI::DoAction(), boss_ichoron::boss_ichoronAI::DoAction(), Spell::DoAllEffectOnTarget(), boss_twin_valkyrAI::EnterCombat(), boss_sister_svalna::boss_sister_svalnaAI::EnterCombat(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::EnterCombat(), boss_prince_keleseth_icc::boss_prince_kelesethAI::EnterCombat(), boss_prince_taldaram_icc::boss_prince_taldaramAI::EnterCombat(), boss_prince_valanar_icc::boss_prince_valanarAI::EnterCombat(), misc_commandscript::HandleDamageCommand(), misc_commandscript::HandleDieCommand(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::HealReceived(), boss_drakkari_colossus::boss_drakkari_colossusAI::JustSummoned(), npc_boneguard_footman::npc_boneguard_footmanAI::UpdateAI(), npc_phase_hunter::npc_phase_hunterAI::UpdateAI(), and npc_target_dummy::npc_target_dummyAI::UpdateAI().
Motion_Initialize()
void Creature::Motion_Initialize ()
Definition at line 953 of file Creature.cpp.
 {
     if (!m_formation)
         GetMotionMaster()->Initialize();
     else if (m_formation->getLeader() == this)
     {
         m_formation->FormationReset(false, true);
         GetMotionMaster()->Initialize();
     }
     else if (m_formation->isFormed())
         GetMotionMaster()->MoveIdle(); //wait the order of leader
     else
         GetMotionMaster()->Initialize();
 }
References CreatureGroup::FormationReset(), CreatureGroup::getLeader(), Unit::GetMotionMaster(), MotionMaster::Initialize(), CreatureGroup::isFormed(), m_formation, and MotionMaster::MoveIdle().
Referenced by AddToWorld(), Pet::AddToWorld(), and setDeathState().
ProhibitSpellSchool()
void Creature::ProhibitSpellSchool (SpellSchoolMask idSchoolMask, uint32 unTimeMs) override virtual
Reimplemented from Unit.
Definition at line 2561 of file Creature.cpp.
 {
     for (uint8 i = SPELL_SCHOOL_NORMAL; i < MAX_SPELL_SCHOOL; ++i)
         if (idSchoolMask & (1 << i))
             m_ProhibitSchoolTime[i] = World::GetGameTimeMS() + unTimeMs;
 }
References World::GetGameTimeMS(), m_ProhibitSchoolTime, MAX_SPELL_SCHOOL, and SPELL_SCHOOL_NORMAL.
reachWithSpellAttack()
SpellInfo const * Creature::reachWithSpellAttack (Unit * victim)
Definition at line 2065 of file Creature.cpp.
 {
     if (!victim)
         return nullptr;
     for (uint32 i = 0; i < MAX_CREATURE_SPELLS; ++i)
     {
         if (!m_spells[i])
             continue;
         SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(m_spells[i]);
         if (!spellInfo)
         {
             LOG_ERROR("entities.unit", "WORLD: unknown spell id %i", m_spells[i]);
             continue;
         }
         bool bcontinue = true;
         for (uint32 j = 0; j < MAX_SPELL_EFFECTS; j++)
         {
             if ((spellInfo->Effects[j].Effect == SPELL_EFFECT_SCHOOL_DAMAGE)       ||
                     (spellInfo->Effects[j].Effect == SPELL_EFFECT_INSTAKILL)            ||
                     (spellInfo->Effects[j].Effect == SPELL_EFFECT_ENVIRONMENTAL_DAMAGE) ||
                     (spellInfo->Effects[j].Effect == SPELL_EFFECT_HEALTH_LEECH)
                )
             {
                 bcontinue = false;
                 break;
             }
         }
         if (bcontinue)
             continue;
         if (spellInfo->ManaCost > GetPower(POWER_MANA))
             continue;
         float range = spellInfo->GetMaxRange(false);
         float minrange = spellInfo->GetMinRange(false);
         float dist = GetDistance(victim);
         if (dist > range || dist < minrange)
             continue;
         if (spellInfo->PreventionType == SPELL_PREVENTION_TYPE_SILENCE && HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_SILENCED))
             continue;
         if (spellInfo->PreventionType == SPELL_PREVENTION_TYPE_PACIFY && HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PACIFIED))
             continue;
         return spellInfo;
     }
     return nullptr;
 }
References SpellInfo::Effects, WorldObject::GetDistance(), SpellInfo::GetMaxRange(), SpellInfo::GetMinRange(), Unit::GetPower(), Object::HasFlag(), LOG_ERROR, m_spells, SpellInfo::ManaCost, MAX_CREATURE_SPELLS, MAX_SPELL_EFFECTS, POWER_MANA, SpellInfo::PreventionType, SPELL_EFFECT_ENVIRONMENTAL_DAMAGE, SPELL_EFFECT_HEALTH_LEECH, SPELL_EFFECT_INSTAKILL, SPELL_EFFECT_SCHOOL_DAMAGE, SPELL_PREVENTION_TYPE_PACIFY, SPELL_PREVENTION_TYPE_SILENCE, sSpellMgr, UNIT_FIELD_FLAGS, UNIT_FLAG_PACIFIED, and UNIT_FLAG_SILENCED.
reachWithSpellCure()
SpellInfo const * Creature::reachWithSpellCure (Unit * victim)
Definition at line 2113 of file Creature.cpp.
 {
     if (!victim)
         return nullptr;
     for (uint32 i = 0; i < MAX_CREATURE_SPELLS; ++i)
     {
         if (!m_spells[i])
             continue;
         SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(m_spells[i]);
         if (!spellInfo)
         {
             LOG_ERROR("entities.unit", "WORLD: unknown spell id %i", m_spells[i]);
             continue;
         }
         bool bcontinue = true;
         for (uint32 j = 0; j < MAX_SPELL_EFFECTS; j++)
         {
             if ((spellInfo->Effects[j].Effect == SPELL_EFFECT_HEAL))
             {
                 bcontinue = false;
                 break;
             }
         }
         if (bcontinue)
             continue;
         if (spellInfo->ManaCost > GetPower(POWER_MANA))
             continue;
         float range = spellInfo->GetMaxRange(true);
         float minrange = spellInfo->GetMinRange(true);
         float dist = GetDistance(victim);
         //if (!isInFront(victim, range) && spellInfo->AttributesEx)
         //    continue;
         if (dist > range || dist < minrange)
             continue;
         if (spellInfo->PreventionType == SPELL_PREVENTION_TYPE_SILENCE && HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_SILENCED))
             continue;
         if (spellInfo->PreventionType == SPELL_PREVENTION_TYPE_PACIFY && HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PACIFIED))
             continue;
         return spellInfo;
     }
     return nullptr;
 }
References SpellInfo::Effects, WorldObject::GetDistance(), SpellInfo::GetMaxRange(), SpellInfo::GetMinRange(), Unit::GetPower(), Object::HasFlag(), LOG_ERROR, m_spells, SpellInfo::ManaCost, MAX_CREATURE_SPELLS, MAX_SPELL_EFFECTS, POWER_MANA, SpellInfo::PreventionType, SPELL_EFFECT_HEAL, SPELL_PREVENTION_TYPE_PACIFY, SPELL_PREVENTION_TYPE_SILENCE, sSpellMgr, UNIT_FIELD_FLAGS, UNIT_FLAG_PACIFIED, and UNIT_FLAG_SILENCED.
RefreshSwimmingFlag()
void Creature::RefreshSwimmingFlag (bool recheck = false)
Definition at line 2980 of file Creature.cpp.
 {
     if (!_isMissingSwimmingFlagOutOfCombat || recheck)
         _isMissingSwimmingFlagOutOfCombat = !HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_SWIMMING);
     // Check if the creature has UNIT_FLAG_SWIMMING and add it if it's missing
     // Creatures must be able to chase a target in water if they can enter water
     if (_isMissingSwimmingFlagOutOfCombat && CanEnterWater())
         SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_SWIMMING);
 }
References _isMissingSwimmingFlagOutOfCombat, CanEnterWater(), Object::HasFlag(), Object::SetFlag(), UNIT_FIELD_FLAGS, and UNIT_FLAG_SWIMMING.
Regenerate()
void Creature::Regenerate (Powers power) protected
Definition at line 796 of file Creature.cpp.
 {
     uint32 curValue = GetPower(power);
     uint32 maxValue = GetMaxPower(power);
     // Xinef: implement power regeneration flag
     if (!HasFlag(UNIT_FIELD_FLAGS_2, UNIT_FLAG2_REGENERATE_POWER) && !GetOwnerGUID().IsPlayer())
         return;
     if (curValue >= maxValue)
         return;
     float addvalue = 0.0f;
     switch (power)
     {
         case POWER_FOCUS:
             {
                 // For hunter pets.
                 addvalue = 24 * sWorld->getRate(RATE_POWER_FOCUS);
                 break;
             }
         case POWER_ENERGY:
             {
                 // For deathknight's ghoul.
                 addvalue = 20;
                 break;
             }
         case POWER_MANA:
             {
                 // Combat and any controlled creature
                 if (IsInCombat() || GetCharmerOrOwnerGUID())
                 {
                     if (GetEntry() == NPC_IMP || GetEntry() == NPC_WATER_ELEMENTAL_TEMP || GetEntry() == NPC_WATER_ELEMENTAL_PERM)
                     {
                         addvalue = uint32((GetStat(STAT_SPIRIT) / (IsUnderLastManaUseEffect() ? 8.0f : 5.0f) + 17.0f));
                     }
                     else if (!IsUnderLastManaUseEffect())
                     {
                         float ManaIncreaseRate = sWorld->getRate(RATE_POWER_MANA);
                         float Spirit = GetStat(STAT_SPIRIT);
                         addvalue = uint32((Spirit / 5.0f + 17.0f) * ManaIncreaseRate);
                     }
                 }
                 else
                     addvalue = maxValue / 3;
                 break;
             }
         default:
             return;
     }
     // Apply modifiers (if any).
     AuraEffectList const& ModPowerRegenPCTAuras = GetAuraEffectsByType(SPELL_AURA_MOD_POWER_REGEN_PERCENT);
     for (AuraEffectList::const_iterator i = ModPowerRegenPCTAuras.begin(); i != ModPowerRegenPCTAuras.end(); ++i)
         if (Powers((*i)->GetMiscValue()) == power)
             AddPct(addvalue, (*i)->GetAmount());
     addvalue += GetTotalAuraModifierByMiscValue(SPELL_AURA_MOD_POWER_REGEN, power) * (power == POWER_FOCUS ? PET_FOCUS_REGEN_INTERVAL : CREATURE_REGEN_INTERVAL) / (5 * IN_MILLISECONDS);
     ModifyPower(power, int32(addvalue));
 }
References AddPct(), CREATURE_REGEN_INTERVAL, Unit::GetAuraEffectsByType(), Unit::GetCharmerOrOwnerGUID(), Object::GetEntry(), Unit::GetMaxPower(), Unit::GetOwnerGUID(), Unit::GetPower(), Unit::GetStat(), Unit::GetTotalAuraModifierByMiscValue(), Object::HasFlag(), IN_MILLISECONDS, Unit::IsInCombat(), Object::IsPlayer(), Unit::IsUnderLastManaUseEffect(), Unit::ModifyPower(), NPC_IMP, NPC_WATER_ELEMENTAL_PERM, NPC_WATER_ELEMENTAL_TEMP, PET_FOCUS_REGEN_INTERVAL, POWER_ENERGY, POWER_FOCUS, POWER_MANA, RATE_POWER_FOCUS, RATE_POWER_MANA, SPELL_AURA_MOD_POWER_REGEN, SPELL_AURA_MOD_POWER_REGEN_PERCENT, STAT_SPIRIT, sWorld, UNIT_FIELD_FLAGS_2, and UNIT_FLAG2_REGENERATE_POWER.
Referenced by Pet::Update(), and Update().
RegenerateHealth()
void Creature::RegenerateHealth () protected
Definition at line 860 of file Creature.cpp.
 {
     if (!isRegeneratingHealth())
         return;
     uint32 curValue = GetHealth();
     uint32 maxValue = GetMaxHealth();
     if (curValue >= maxValue)
         return;
     uint32 addvalue = 0;
     // Not only pet, but any controlled creature
     // Xinef: fix polymorph rapid regen
     if (!GetCharmerOrOwnerGUID() || IsPolymorphed())
         addvalue = maxValue / 3;
     else //if (GetCharmerOrOwnerGUID())
     {
         float HealthIncreaseRate = sWorld->getRate(RATE_HEALTH);
         float Spirit = GetStat(STAT_SPIRIT);
         if (GetPower(POWER_MANA) > 0)
             addvalue = uint32(Spirit * 0.25 * HealthIncreaseRate);
         else
             addvalue = uint32(Spirit * 0.80 * HealthIncreaseRate);
     }
     // Apply modifiers (if any).
     AuraEffectList const& ModPowerRegenPCTAuras = GetAuraEffectsByType(SPELL_AURA_MOD_HEALTH_REGEN_PERCENT);
     for (AuraEffectList::const_iterator i = ModPowerRegenPCTAuras.begin(); i != ModPowerRegenPCTAuras.end(); ++i)
         AddPct(addvalue, (*i)->GetAmount());
     addvalue += GetTotalAuraModifier(SPELL_AURA_MOD_REGEN) * CREATURE_REGEN_INTERVAL  / (5 * IN_MILLISECONDS);
     ModifyHealth(addvalue);
 }
References AddPct(), CREATURE_REGEN_INTERVAL, Unit::GetAuraEffectsByType(), Unit::GetCharmerOrOwnerGUID(), Unit::GetHealth(), Unit::GetMaxHealth(), Unit::GetPower(), Unit::GetStat(), Unit::GetTotalAuraModifier(), IN_MILLISECONDS, Unit::IsPolymorphed(), isRegeneratingHealth(), Unit::ModifyHealth(), POWER_MANA, RATE_HEALTH, SPELL_AURA_MOD_HEALTH_REGEN_PERCENT, SPELL_AURA_MOD_REGEN, STAT_SPIRIT, and sWorld.
Referenced by Update().
ReleaseFocus()
void Creature::ReleaseFocus (Spell const * focusSpell)
Definition at line 3323 of file Creature.cpp.
 {
     // focused to something else
     if (focusSpell != _focusSpell)
         return;
     _focusSpell = nullptr;
     if (Unit* victim = GetVictim())
         SetGuidValue(UNIT_FIELD_TARGET, victim->GetGUID());
     else
         SetGuidValue(UNIT_FIELD_TARGET, ObjectGuid::Empty);
     if (focusSpell->GetSpellInfo()->HasAttribute(SPELL_ATTR5_AI_DOESNT_FACE_TARGET))
         ClearUnitState(UNIT_STATE_ROTATING);
 }
References _focusSpell, Unit::ClearUnitState(), ObjectGuid::Empty, Spell::GetSpellInfo(), Unit::GetVictim(), SpellInfo::HasAttribute(), Object::SetGuidValue(), SPELL_ATTR5_AI_DOESNT_FACE_TARGET, UNIT_FIELD_TARGET, and UNIT_STATE_ROTATING.
RemoveCorpse()
void Creature::RemoveCorpse (bool setSpawnTime = true, bool skipVisibility = false)
Definition at line 309 of file Creature.cpp.
 {
     if (getDeathState() != CORPSE)
         return;
     m_corpseRemoveTime = time(nullptr);
     setDeathState(DEAD);
     RemoveAllAuras();
     if (!skipVisibility) // pussywizard
         DestroyForNearbyPlayers(); // pussywizard: previous UpdateObjectVisibility()
     loot.clear();
     uint32 respawnDelay = m_respawnDelay;
     if (IsAIEnabled)
         AI()->CorpseRemoved(respawnDelay);
     // Should get removed later, just keep "compatibility" with scripts
     if (setSpawnTime)
     {
         m_respawnTime = time(nullptr) + respawnDelay;
         //SaveRespawnTime();
     }
     float x, y, z, o;
     GetRespawnPosition(x, y, z, &o);
     SetHomePosition(x, y, z, o);
     SetPosition(x, y, z, o);
     // xinef: relocate notifier
     m_last_notify_position.Relocate(-5000.0f, -5000.0f, -5000.0f, 0.0f);
     // pussywizard: if corpse was removed during falling then the falling will continue after respawn, so stop falling is such case
     if (IsFalling())
         StopMoving();
 }
References AI(), Loot::clear(), CORPSE, CreatureAI::CorpseRemoved(), DEAD, WorldObject::DestroyForNearbyPlayers(), Unit::getDeathState(), GetRespawnPosition(), Unit::IsAIEnabled, Unit::IsFalling(), loot, m_corpseRemoveTime, Unit::m_last_notify_position, m_respawnDelay, m_respawnTime, Position::Relocate(), Unit::RemoveAllAuras(), setDeathState(), SetHomePosition(), SetPosition(), Unit::StopMoving(), G3D::x, G3D::y, and G3D::z.
Referenced by DisappearAndDie(), RespawnEvent::Execute(), ForcedDespawn(), AuraEffect::HandleAuraControlVehicle(), misc_commandscript::HandleCreatePetCommand(), boss_skeram::boss_skeramAI::JustDied(), npc_qiraj_war_spawn::npc_qiraj_war_spawnAI::JustDied(), boss_prince_keleseth_icc::boss_prince_kelesethAI::JustDied(), boss_prince_taldaram_icc::boss_prince_taldaramAI::JustDied(), boss_prince_valanar_icc::boss_prince_valanarAI::JustDied(), npc_illidari_spawn::npc_illidari_spawnAI::JustDied(), npc_nether_drake::npc_nether_drakeAI::MovementInform(), npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI::MovementInform(), ValithriaDespawner::operator()(), Respawn(), npc_simone::npc_simoneAI::RespawnPet(), Update(), npc_towering_infernal::npc_towering_infernalAI::UpdateAI(), npc_lesser_doomguard::npc_lesser_doomguardAI::UpdateAI(), npc_abomination::npc_abominationAI::WaypointReached(), and npc_ghoul::npc_ghoulAI::WaypointReached().
RemoveFromWorld()
void Creature::RemoveFromWorld () override virtual
Reimplemented from Object.
Reimplemented in Pet, Puppet, Minion, and TempSummon.
Definition at line 254 of file Creature.cpp.
 {
     if (IsInWorld())
     {
 #ifdef ELUNA
         sEluna->OnRemoveFromWorld(this);
 #endif
         if (GetZoneScript())
             GetZoneScript()->OnCreatureRemove(this);
         if (m_formation)
             sFormationMgr->RemoveCreatureFromGroup(m_formation, this);
         if (Transport* transport = GetTransport())
             transport->RemovePassenger(this, true);
         Unit::RemoveFromWorld();
         if (m_spawnId)
             Acore::Containers::MultimapErasePair(GetMap()->GetCreatureBySpawnIdStore(), m_spawnId, this);
         GetMap()->GetObjectsStore().Remove<Creature>(GetGUID());
     }
 }
References Object::GetGUID(), WorldObject::GetMap(), Map::GetObjectsStore(), WorldObject::GetTransport(), WorldObject::GetZoneScript(), Object::IsInWorld(), m_formation, m_spawnId, Acore::Containers::MultimapErasePair(), ZoneScript::OnCreatureRemove(), TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::Remove(), Unit::RemoveFromWorld(), and sFormationMgr.
Referenced by TempSummon::RemoveFromWorld().
RemoveLootMode()
void Creature::RemoveLootMode (uint16 lootMode) inline
Definition at line 229 of file Creature.h.
 { m_LootMode &= ~lootMode; }
References m_LootMode.
Referenced by boss_yoggsaron::boss_yoggsaronAI::boss_yoggsaronAI().
ResetLootMode()
void Creature::ResetLootMode () inline
Definition at line 230 of file Creature.h.
 { m_LootMode = LOOT_MODE_DEFAULT; }
References LOOT_MODE_DEFAULT, and m_LootMode.
Referenced by BossAI::_Reset(), Creature(), boss_sacrolash::boss_sacrolashAI::DoAction(), boss_alythess::boss_alythessAI::DoAction(), boss_majordomo::boss_majordomoAI::Reset(), boss_sartharion_dragonAI::Reset(), boss_xt002::boss_xt002AI::Reset(), boss_steelbreaker::boss_steelbreakerAI::UpdatePhase(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::UpdatePhase(), and boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdatePhase().
ResetPickPocketLootTime()
void Creature::ResetPickPocketLootTime () inline
Definition at line 220 of file Creature.h.
 { lootPickPocketRestoreTime = 0; }
References lootPickPocketRestoreTime.
Referenced by Respawn().
ResetPlayerDamageReq()
void Creature::ResetPlayerDamageReq () inline
Definition at line 347 of file Creature.h.
 { m_PlayerDamageReq = GetHealth() / 2; }
References Unit::GetHealth(), and m_PlayerDamageReq.
Referenced by CreatureAI::_EnterEvadeMode(), boss_vaelastrasz::boss_vaelAI::EnterCombat(), npc_pos_freed_slave::npc_pos_freed_slaveAI::EnterEvadeMode(), npc_pet_hunter_snake_trap::EnterEvadeMode(), boss_urom::boss_uromAI::LeaveCombat(), boss_murmur::boss_murmurAI::Reset(), SelectLevel(), and setDeathState().
Respawn()
void Creature::Respawn (bool force = false)
Definition at line 1859 of file Creature.cpp.
 {
     //DestroyForNearbyPlayers(); // pussywizard: not needed
     if (force)
     {
         if (IsAlive())
             setDeathState(JUST_DIED);
         else if (getDeathState() != CORPSE)
             setDeathState(CORPSE);
     }
     RemoveCorpse(false, false);
     if (getDeathState() == DEAD)
     {
         if (m_spawnId)
             GetMap()->RemoveCreatureRespawnTime(m_spawnId);
         LOG_DEBUG("entities.unit", "Respawning creature %s (SpawnId: %u, %s)", GetName().c_str(), GetSpawnId(), GetGUID().ToString().c_str());
         m_respawnTime = 0;
         ResetPickPocketLootTime();
         if (m_originalEntry != GetEntry())
             UpdateEntry(m_originalEntry);
         SelectLevel();
         setDeathState(JUST_RESPAWNED);
         uint32 displayID = GetNativeDisplayId();
         CreatureModelInfo const* minfo = sObjectMgr->GetCreatureModelRandomGender(&displayID);
         if (minfo)                                             // Cancel load if no model defined
         {
             SetDisplayId(displayID);
             SetNativeDisplayId(displayID);
             SetByteValue(UNIT_FIELD_BYTES_0, 2, minfo->gender);
         }
         GetMotionMaster()->InitDefault();
         //Call AI respawn virtual function
         if (IsAIEnabled)
         {
             //reset the AI to be sure no dirty or uninitialized values will be used till next tick
             AI()->Reset();
             TriggerJustRespawned = true;//delay event to next tick so all creatures are created on the map before processing
         }
         uint32 poolid = m_spawnId ? sPoolMgr->IsPartOfAPool<Creature>(m_spawnId) : 0;
         if (poolid)
             sPoolMgr->UpdatePool<Creature>(poolid, m_spawnId);
         //Re-initialize reactstate that could be altered by movementgenerators
         InitializeReactState();
         m_respawnedTime = sWorld->GetGameTime();
     }
     m_respawnedTime = time(nullptr);
     // xinef: relocate notifier, fixes npc appearing in corpse position after forced respawn (instead of spawn)
     m_last_notify_position.Relocate(-5000.0f, -5000.0f, -5000.0f, 0.0f);
     UpdateObjectVisibility(false);
 }
References AI(), CORPSE, DEAD, CreatureModelInfo::gender, Unit::getDeathState(), Object::GetEntry(), Object::GetGUID(), WorldObject::GetMap(), Unit::GetMotionMaster(), WorldObject::GetName(), Unit::GetNativeDisplayId(), GetSpawnId(), MotionMaster::InitDefault(), InitializeReactState(), Unit::IsAIEnabled, Unit::IsAlive(), JUST_DIED, JUST_RESPAWNED, LOG_DEBUG, Unit::m_last_notify_position, m_originalEntry, m_respawnedTime, m_respawnTime, m_spawnId, Position::Relocate(), RemoveCorpse(), Map::RemoveCreatureRespawnTime(), UnitAI::Reset(), ResetPickPocketLootTime(), SelectLevel(), Object::SetByteValue(), setDeathState(), SetDisplayId(), Unit::SetNativeDisplayId(), sObjectMgr, sPoolMgr, sWorld, Position::ToString(), TriggerJustRespawned, UNIT_FIELD_BYTES_0, UpdateEntry(), and Unit::UpdateObjectVisibility().
Referenced by BattlegroundAV::AddAVCreature(), boss_thaddius_summon::boss_thaddius_summonAI::DoAction(), RespawnEvent::Execute(), npc_commandscript::HandleNpcMoveCommand(), npc_commandscript::HandleNpcSetMoveTypeCommand(), npc_commandscript::HandleNpcSetWanderDistanceCommand(), misc_commandscript::HandleRespawnCommand(), hyjalAI::JustDied(), npc_isle_of_conquest_turret::npc_isle_of_conquest_turretAI::JustDied(), npc_simone::npc_simoneAI::JustRespawned(), instance_uldaman::instance_uldaman_InstanceMapScript::OnCreatureCreate(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::OnCreatureCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), at_blackrock_stadium::OnTrigger(), Acore::RespawnDo::operator()(), instance_blood_furnace::instance_blood_furnace_InstanceMapScript::ResetPrisoner(), instance_molten_core::instance_molten_core_InstanceMapScript::SetBossState(), instance_naxxramas::instance_naxxramas_InstanceMapScript::SetBossState(), Battlefield::ShowNpc(), Update(), npc_escortAI::UpdateAI(), socrethar::socretharAI::UpdateAI(), and InstanceScript::UpdateMinionState().
RespawnOnEvade()
void Creature::RespawnOnEvade ()
Definition at line 1971 of file Creature.cpp.
 {
     SetVisible(true);
     UpdateMovementFlags();
     AI()->Reset();
     AI()->JustReachedHome();
     if (IsVehicle()) // use the same sequence of addtoworld, aireset may remove all summons!
     {
         GetVehicleKit()->Reset(true);
     }
 }
References AI(), Unit::GetVehicleKit(), Unit::IsVehicle(), CreatureAI::JustReachedHome(), UnitAI::Reset(), Vehicle::Reset(), Unit::SetVisible(), and UpdateMovementFlags().
Referenced by PhasedRespawn::Execute().
SaveRespawnTime()
void Creature::SaveRespawnTime () override virtual
Reimplemented from WorldObject.
Definition at line 2379 of file Creature.cpp.
 {
     if (IsSummon() || !m_spawnId || (m_creatureData && !m_creatureData->dbData))
         return;
     GetMap()->SaveCreatureRespawnTime(m_spawnId, m_respawnTime);
 }
References CreatureData::dbData, WorldObject::GetMap(), Unit::IsSummon(), m_creatureData, m_respawnTime, m_spawnId, and Map::SaveCreatureRespawnTime().
Referenced by boss_prince_keleseth_icc::boss_prince_kelesethAI::JustDied(), boss_prince_taldaram_icc::boss_prince_taldaramAI::JustDied(), boss_prince_valanar_icc::boss_prince_valanarAI::JustDied(), npc_dragonflayer_forge_master::npc_dragonflayer_forge_masterAI::JustDied(), setDeathState(), and Update().
SaveToDB() [1/2]
void Creature::SaveToDB ()
Definition at line 1234 of file Creature.cpp.
 {
     // this should only be used when the creature has already been loaded
     // preferably after adding to map, because mapid may not be valid otherwise
     CreatureData const* data = sObjectMgr->GetCreatureData(m_spawnId);
     if (!data)
     {
         LOG_ERROR("entities.unit", "Creature::SaveToDB failed, cannot get creature data!");
         return;
     }
     uint32 mapId = GetTransport() && GetTransport()->ToMotionTransport() ? GetTransport()->GetGOInfo()->moTransport.mapID : GetMapId();
     SaveToDB(mapId, data->spawnMask, GetPhaseMask());
 }
References GameObject::GetGOInfo(), WorldLocation::GetMapId(), WorldObject::GetPhaseMask(), WorldObject::GetTransport(), LOG_ERROR, m_spawnId, GameObjectTemplate::moTransport, sObjectMgr, and GameObject::ToMotionTransport().
Referenced by npc_commandscript::HandleNpcAddCommand(), npc_commandscript::HandleNpcSetLevelCommand(), npc_commandscript::HandleNpcSetModelCommand(), npc_commandscript::HandleNpcSetMoveTypeCommand(), npc_commandscript::HandleNpcSetPhaseCommand(), wp_commandscript::HandleWpModifyCommand(), and wp_commandscript::HandleWpShowCommand().
SaveToDB() [2/2]
void Creature::SaveToDB (uint32 mapid, uint8 spawnMask, uint32 phaseMask) virtual
Reimplemented in Pet, and TempSummon.
Definition at line 1249 of file Creature.cpp.
 {
     // update in loaded data
     if (!m_spawnId)
         m_spawnId = sObjectMgr->GenerateCreatureSpawnId();
     CreatureData& data = sObjectMgr->NewOrExistCreatureData(m_spawnId);
     uint32 displayId = GetNativeDisplayId();
     uint32 npcflag = GetUInt32Value(UNIT_NPC_FLAGS);
     uint32 unit_flags = GetUInt32Value(UNIT_FIELD_FLAGS);
     uint32 dynamicflags = GetUInt32Value(UNIT_DYNAMIC_FLAGS);
     // check if it's a custom model and if not, use 0 for displayId
     CreatureTemplate const* cinfo = GetCreatureTemplate();
     if (cinfo)
     {
         if (displayId == cinfo->Modelid1 || displayId == cinfo->Modelid2 ||
                 displayId == cinfo->Modelid3 || displayId == cinfo->Modelid4)
             displayId = 0;
         if (npcflag == cinfo->npcflag)
             npcflag = 0;
         if (unit_flags == cinfo->unit_flags)
             unit_flags = 0;
         if (dynamicflags == cinfo->dynamicflags)
             dynamicflags = 0;
     }
     data.id = GetEntry();
     data.mapid = mapid;
     data.phaseMask = phaseMask;
     data.displayid = displayId;
     data.equipmentId = GetCurrentEquipmentId();
     if (!GetTransport())
     {
         data.posX = GetPositionX();
         data.posY = GetPositionY();
         data.posZ = GetPositionZ();
         data.orientation = GetOrientation();
     }
     else
     {
         data.posX = GetTransOffsetX();
         data.posY = GetTransOffsetY();
         data.posZ = GetTransOffsetZ();
         data.orientation = GetTransOffsetO();
     }
     data.spawntimesecs = m_respawnDelay;
     // prevent add data integrity problems
     data.wander_distance = GetDefaultMovementType() == IDLE_MOTION_TYPE ? 0.0f : m_wanderDistance;
     data.currentwaypoint = 0;
     data.curhealth = GetHealth();
     data.curmana = GetPower(POWER_MANA);
     // prevent add data integrity problems
     data.movementType = !m_wanderDistance && GetDefaultMovementType() == RANDOM_MOTION_TYPE
                         ? IDLE_MOTION_TYPE : GetDefaultMovementType();
     data.spawnMask = spawnMask;
     data.npcflag = npcflag;
     data.unit_flags = unit_flags;
     data.dynamicflags = dynamicflags;
     // update in DB
     WorldDatabaseTransaction trans = WorldDatabase.BeginTransaction();
     WorldDatabasePreparedStatement* stmt = WorldDatabase.GetPreparedStatement(WORLD_DEL_CREATURE);
     stmt->setUInt32(0, m_spawnId);
     trans->Append(stmt);
     uint8 index = 0;
     stmt = WorldDatabase.GetPreparedStatement(WORLD_INS_CREATURE);
     stmt->setUInt32(index++, m_spawnId);
     stmt->setUInt32(index++, GetEntry());
     stmt->setUInt16(index++, uint16(mapid));
     stmt->setUInt8(index++, spawnMask);
     stmt->setUInt32(index++, GetPhaseMask());
     stmt->setUInt32(index++, displayId);
     stmt->setInt32(index++, int32(GetCurrentEquipmentId()));
     stmt->setFloat(index++, GetPositionX());
     stmt->setFloat(index++, GetPositionY());
     stmt->setFloat(index++, GetPositionZ());
     stmt->setFloat(index++, GetOrientation());
     stmt->setUInt32(index++, m_respawnDelay);
     stmt->setFloat(index++, m_wanderDistance);
     stmt->setUInt32(index++, 0);
     stmt->setUInt32(index++, GetHealth());
     stmt->setUInt32(index++, GetPower(POWER_MANA));
     stmt->setUInt8(index++, uint8(GetDefaultMovementType()));
     stmt->setUInt32(index++, npcflag);
     stmt->setUInt32(index++, unit_flags);
     stmt->setUInt32(index++, dynamicflags);
     trans->Append(stmt);
     WorldDatabase.CommitTransaction(trans);
 }
References CreatureTemplate::dynamicflags, GetCreatureTemplate(), GetCurrentEquipmentId(), GetDefaultMovementType(), Object::GetEntry(), Unit::GetHealth(), Unit::GetNativeDisplayId(), Position::GetOrientation(), WorldObject::GetPhaseMask(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetPower(), WorldObject::GetTransOffsetO(), WorldObject::GetTransOffsetX(), WorldObject::GetTransOffsetY(), WorldObject::GetTransOffsetZ(), WorldObject::GetTransport(), Object::GetUInt32Value(), IDLE_MOTION_TYPE, index, m_respawnDelay, m_spawnId, m_wanderDistance, CreatureTemplate::Modelid1, CreatureTemplate::Modelid2, CreatureTemplate::Modelid3, CreatureTemplate::Modelid4, CreatureTemplate::npcflag, POWER_MANA, RANDOM_MOTION_TYPE, PreparedStatementBase::setFloat(), PreparedStatementBase::setInt32(), PreparedStatementBase::setUInt16(), PreparedStatementBase::setUInt32(), PreparedStatementBase::setUInt8(), sObjectMgr, UNIT_DYNAMIC_FLAGS, UNIT_FIELD_FLAGS, CreatureTemplate::unit_flags, UNIT_NPC_FLAGS, WORLD_DEL_CREATURE, WORLD_INS_CREATURE, and WorldDatabase.
SearchFormation()
void Creature::SearchFormation ()
Definition at line 289 of file Creature.cpp.
 {
     if (IsSummon())
     {
         return;
     }
     ObjectGuid::LowType spawnId = GetSpawnId();
     if (!spawnId)
     {
         return;
     }
     CreatureGroupInfoType::const_iterator frmdata = sFormationMgr->CreatureGroupMap.find(spawnId);
     if (frmdata != sFormationMgr->CreatureGroupMap.end())
     {
         sFormationMgr->AddCreatureToGroup(frmdata->second.leaderGUID, this);
     }
 }
References GetSpawnId(), Unit::IsSummon(), and sFormationMgr.
Referenced by AddToWorld(), and npc_commandscript::HandleNpcAddFormationCommand().
SelectLevel()
void Creature::SelectLevel (bool changelevel = true)
Definition at line 1349 of file Creature.cpp.
 {
     CreatureTemplate const* cInfo = GetCreatureTemplate();
     uint32 rank = IsPet() ? 0 : cInfo->rank;
     // level
     uint8 minlevel = std::min(cInfo->maxlevel, cInfo->minlevel);
     uint8 maxlevel = std::max(cInfo->maxlevel, cInfo->minlevel);
     uint8 level = minlevel == maxlevel ? minlevel : urand(minlevel, maxlevel);
     if (changelevel)
         SetLevel(level);
     CreatureBaseStats const* stats = sObjectMgr->GetCreatureBaseStats(level, cInfo->unit_class);
     // health
     float healthmod = _GetHealthMod(rank);
     uint32 basehp = std::max<uint32>(1, stats->GenerateHealth(cInfo));
     uint32 health = uint32(basehp * healthmod);
     SetCreateHealth(health);
     SetMaxHealth(health);
     SetHealth(health);
     ResetPlayerDamageReq();
     // mana
     uint32 mana = stats->GenerateMana(cInfo);
     SetCreateMana(mana);
     SetMaxPower(POWER_MANA, mana);                          //MAX Mana
     SetPower(POWER_MANA, mana);
     // TODO: set UNIT_FIELD_POWER*, for some creature class case (energy, etc)
     SetModifierValue(UNIT_MOD_HEALTH, BASE_VALUE, (float)health);
     SetModifierValue(UNIT_MOD_MANA, BASE_VALUE, (float)mana);
     // damage
     float basedamage = stats->GenerateBaseDamage(cInfo);
     float weaponBaseMinDamage = basedamage;
     float weaponBaseMaxDamage = basedamage * 1.5;
     SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, weaponBaseMinDamage);
     SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, weaponBaseMaxDamage);
     SetBaseWeaponDamage(OFF_ATTACK, MINDAMAGE, weaponBaseMinDamage);
     SetBaseWeaponDamage(OFF_ATTACK, MAXDAMAGE, weaponBaseMaxDamage);
     SetBaseWeaponDamage(RANGED_ATTACK, MINDAMAGE, weaponBaseMinDamage);
     SetBaseWeaponDamage(RANGED_ATTACK, MAXDAMAGE, weaponBaseMaxDamage);
     SetModifierValue(UNIT_MOD_ATTACK_POWER, BASE_VALUE, stats->AttackPower);
     SetModifierValue(UNIT_MOD_ATTACK_POWER_RANGED, BASE_VALUE, stats->RangedAttackPower);
     sScriptMgr->Creature_SelectLevel(cInfo, this);
 }
References _GetHealthMod(), CreatureBaseStats::AttackPower, BASE_ATTACK, BASE_VALUE, CreatureBaseStats::GenerateBaseDamage(), CreatureBaseStats::GenerateHealth(), CreatureBaseStats::GenerateMana(), GetCreatureTemplate(), Unit::IsPet(), max, MAXDAMAGE, CreatureTemplate::maxlevel, min, MINDAMAGE, CreatureTemplate::minlevel, OFF_ATTACK, POWER_MANA, RANGED_ATTACK, CreatureBaseStats::RangedAttackPower, CreatureTemplate::rank, ResetPlayerDamageReq(), Unit::SetBaseWeaponDamage(), Unit::SetCreateHealth(), Unit::SetCreateMana(), Unit::SetHealth(), Unit::SetLevel(), Unit::SetMaxHealth(), Unit::SetMaxPower(), Unit::SetModifierValue(), Unit::SetPower(), sObjectMgr, sScriptMgr, CreatureTemplate::unit_class, UNIT_MOD_ATTACK_POWER, UNIT_MOD_ATTACK_POWER_RANGED, UNIT_MOD_HEALTH, UNIT_MOD_MANA, and urand().
Referenced by Spell::EffectSummonType(), npc_target_dummy::npc_target_dummyAI::Reset(), Respawn(), and UpdateEntry().
SelectNearestTarget()
Unit * Creature::SelectNearestTarget (float dist = 0, bool playerOnly = false) const
Definition at line 2161 of file Creature.cpp.
 {
     if (dist == 0.0f)
     {
         dist = MAX_VISIBILITY_DISTANCE;
     }
     Unit* target = nullptr;
     Acore::NearestHostileUnitCheck u_check(this, dist, playerOnly);
     Acore::UnitLastSearcher<Acore::NearestHostileUnitCheck> searcher(this, target, u_check);
     Cell::VisitAllObjects(this, searcher, dist);
     return target;
 }
References MAX_VISIBILITY_DISTANCE, and Cell::VisitAllObjects().
Referenced by SmartScript::GetTargets(), boss_onyxia::boss_onyxiaAI::JustSummoned(), boss_black_knight::boss_black_knightAI::JustSummoned(), boss_gothik::boss_gothikAI::JustSummoned(), boss_grand_champion::boss_grand_championAI::MovementInform(), npc_swarm_scarab::npc_swarm_scarabAI::Reset(), npc_nerubian_burrower::npc_nerubian_burrowerAI::Reset(), npc_fel_infernal::npc_fel_infernalAI::Reset(), npc_mistress_of_pain::npc_mistress_of_painAI::Reset(), boss_skarvald_the_constructor::boss_skarvald_the_constructorAI::Reset(), boss_dalronn_the_controller::boss_dalronn_the_controllerAI::Reset(), npc_heated_battle::npc_heated_battleAI::Reset(), npc_pet_hunter_snake_trap::Reset(), npc_pet_pri_shadowfiend::Reset(), boss_twinemperorsAI::TryActivateAfterTTelep(), npc_memory::npc_memoryAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_freya_ward::npc_freya_wardAI::UpdateAI(), npc_q24545_vegard::npc_q24545_vegardAI::UpdateAI(), and npc_pet_gen_target_following_bomb::UpdateAI().
SelectNearestTargetInAttackDistance()
Unit * Creature::SelectNearestTargetInAttackDistance (float dist) const
Definition at line 2177 of file Creature.cpp.
 {
     if (dist < ATTACK_DISTANCE)
         dist = ATTACK_DISTANCE;
     if (dist > MAX_SEARCHER_DISTANCE)
         dist = MAX_SEARCHER_DISTANCE;
     Unit* target = nullptr;
     Acore::NearestHostileUnitInAttackDistanceCheck u_check(this, dist);
     Acore::UnitLastSearcher<Acore::NearestHostileUnitInAttackDistanceCheck> searcher(this, target, u_check);
     Cell::VisitAllObjects(this, searcher, std::max(dist, ATTACK_DISTANCE));
     return target;
 }
References ATTACK_DISTANCE, max, MAX_SEARCHER_DISTANCE, and Cell::VisitAllObjects().
Referenced by PetAI::SelectNextTarget(), and SimpleCharmedAI::UpdateAI().
SelectVictim()
Unit * Creature::SelectVictim ()
Definition at line 13900 of file Unit.cpp.
 {
     // function provides main threat functionality
     // next-victim-selection algorithm and evade mode are called
     // threat list sorting etc.
     Unit* target = nullptr;
     // First checking if we have some taunt on us
     AuraEffectList const& tauntAuras = GetAuraEffectsByType(SPELL_AURA_MOD_TAUNT);
     if (!tauntAuras.empty())
         for (Unit::AuraEffectList::const_reverse_iterator itr = tauntAuras.rbegin(); itr != tauntAuras.rend(); ++itr)
             if (Unit* caster = (*itr)->GetCaster())
                 if (_CanDetectFeignDeathOf(caster) && CanCreatureAttack(caster) && !caster->HasAuraTypeWithCaster(SPELL_AURA_IGNORED, GetGUID()))
                 {
                     target = caster;
                     break;
                 }
     if (CanHaveThreatList())
     {
         if (!target && !m_ThreatMgr.isThreatListEmpty())
             target = m_ThreatMgr.getHostilTarget();
     }
     else if (!HasReactState(REACT_PASSIVE))
     {
         // we have player pet probably
         target = getAttackerForHelper();
         if (!target && IsSummon())
             if (Unit* owner = ToTempSummon()->GetOwner())
             {
                 if (owner->IsInCombat())
                     target = owner->getAttackerForHelper();
                 if (!target)
                     for (ControlSet::const_iterator itr = owner->m_Controlled.begin(); itr != owner->m_Controlled.end(); ++itr)
                         if ((*itr)->IsInCombat())
{
                             target = (*itr)->getAttackerForHelper();
                             if (target)
                                 break;
                         }
             }
     }
     else
         return nullptr;
     if (target && _CanDetectFeignDeathOf(target) && CanCreatureAttack(target))
     {
         SetInFront(target);
         return target;
     }
     // last case when creature must not go to evade mode:
     // it in combat but attacker not make any damage and not enter to aggro radius to have record in threat list
     // Note: creature does not have targeted movement generator but has attacker in this case
     for (AttackerSet::const_iterator itr = m_attackers.begin(); itr != m_attackers.end(); ++itr)
         if ((*itr) && CanCreatureAttack(*itr) && (*itr)->GetTypeId() != TYPEID_PLAYER && !(*itr)->ToCreature()->HasUnitTypeMask(UNIT_MASK_CONTROLABLE_GUARDIAN))
             return nullptr;
     if (GetVehicle())
         return nullptr;
     // pussywizard: not sure why it's here
     // pussywizard: can't evade when having invisibility aura with duration? o_O
     Unit::AuraEffectList const& iAuras = GetAuraEffectsByType(SPELL_AURA_MOD_INVISIBILITY);
     if (!iAuras.empty())
     {
         for (Unit::AuraEffectList::const_iterator itr = iAuras.begin(); itr != iAuras.end(); ++itr)
             if ((*itr)->GetBase()->IsPermanent())
             {
                 AI()->EnterEvadeMode();
                 break;
             }
         return nullptr;
     }
     // enter in evade mode in other case
     AI()->EnterEvadeMode();
     return nullptr;
 }
References _CanDetectFeignDeathOf(), AI(), CanCreatureAttack(), Unit::CanHaveThreatList(), CreatureAI::EnterEvadeMode(), Unit::getAttackerForHelper(), Unit::GetAuraEffectsByType(), Object::GetGUID(), ThreatMgr::getHostilTarget(), Unit::GetOwner(), Unit::GetVehicle(), HasReactState(), Unit::IsSummon(), ThreatMgr::isThreatListEmpty(), Unit::m_attackers, Unit::m_ThreatMgr, REACT_PASSIVE, Unit::SetInFront(), SPELL_AURA_IGNORED, SPELL_AURA_MOD_INVISIBILITY, SPELL_AURA_MOD_TAUNT, Unit::ToTempSummon(), TYPEID_PLAYER, and UNIT_MASK_CONTROLABLE_GUARDIAN.
Referenced by StartMovementEvent::Execute(), boss_urom::boss_uromAI::JustSummoned(), boss_gyth::boss_gythAI::JustSummoned(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::MovementInform(), boss_sindragosa::boss_sindragosaAI::MovementInform(), npc_rimefang::npc_rimefangAI::MovementInform(), Unit::TauntFadeOut(), Update(), npc_raging_spirit::npc_raging_spiritAI::UpdateAI(), npc_pet_gen_gnomish_flame_turret::UpdateAI(), CreatureAI::UpdateVictim(), and CreatureAI::UpdateVictimWithGaze().
SendAIReaction()
void Creature::SendAIReaction (AiReaction reactionType)
Definition at line 2192 of file Creature.cpp.
 {
     WorldPacket data(SMSG_AI_REACTION, 12);
     data << GetGUID();
     data << uint32(reactionType);
     ((WorldObject*)this)->SendMessageToSet(&data, true);
     LOG_DEBUG("network", "WORLD: Sent SMSG_AI_REACTION, type %u.", reactionType);
 }
References Object::GetGUID(), LOG_DEBUG, and SMSG_AI_REACTION.
Referenced by Unit::Attack(), and CreatureAI::TriggerAlert().
SendZoneUnderAttackMessage()
void Creature::SendZoneUnderAttackMessage (Player * attacker)
Send a message to LocalDefense channel for players opposition team in the zone.
Definition at line 2548 of file Creature.cpp.
 {
     WorldPacket data(SMSG_ZONE_UNDER_ATTACK, 4);
     data << (uint32)GetAreaId();
     sWorld->SendGlobalMessage(&data, nullptr, (attacker->GetTeamId() == TEAM_ALLIANCE ? TEAM_HORDE : TEAM_ALLIANCE));
 }
References WorldObject::GetAreaId(), Player::GetTeamId(), SMSG_ZONE_UNDER_ATTACK, sWorld, TEAM_ALLIANCE, and TEAM_HORDE.
Referenced by GuardAI::JustDied().
SetAssistanceTimer()
void Creature::SetAssistanceTimer (uint32 value) inline
Definition at line 383 of file Creature.h.
 { m_assistanceTimer = value; }
References m_assistanceTimer.
Referenced by Unit::Attack().
SetCanDualWield()
void Creature::SetCanDualWield (bool value) override virtual
Reimplemented from Unit.
Definition at line 1635 of file Creature.cpp.
 {
     Unit::SetCanDualWield(value);
     UpdateDamagePhysical(OFF_ATTACK);
 }
References OFF_ATTACK, Unit::SetCanDualWield(), and Unit::UpdateDamagePhysical().
Referenced by boss_malchezaar::boss_malchezaarAI::clearweapons(), boss_twin_valkyrAI::DoAction(), boss_veras_darkshadow::boss_veras_darkshadowAI::EnterCombat(), prince_axes::prince_axesAI::Initialize(), boss_malchezaar::boss_malchezaarAI::Phase2(), boss_mr_smite::boss_mr_smiteAI::Reset(), boss_mr_smite::boss_mr_smiteAI::UpdateAI(), and boss_twin_valkyrAI::UpdateAI().
SetCanFly()
bool Creature::SetCanFly (bool enable, bool packetOnly = false) override virtual
movement counter
Reimplemented from Unit.
Definition at line 2991 of file Creature.cpp.
 {
     if (!Unit::SetCanFly(enable))
         return false;
     if (m_movedByPlayer)
     {
         sScriptMgr->AnticheatSetCanFlybyServer(m_movedByPlayer->ToPlayer(), enable);
         if (!enable)
             m_movedByPlayer->ToPlayer()->SetFallInformation(time(nullptr), m_movedByPlayer->ToPlayer()->GetPositionZ());
         WorldPacket data(enable ? SMSG_MOVE_SET_CAN_FLY : SMSG_MOVE_UNSET_CAN_FLY, 12);
         data << GetPackGUID();
         data << uint32(0);
         m_movedByPlayer->ToPlayer()->SendDirectMessage(&data);
         data.Initialize(MSG_MOVE_UPDATE_CAN_FLY, 64);
         data << GetPackGUID();
         BuildMovementPacket(&data);
         m_movedByPlayer->ToPlayer()->SendMessageToSet(&data, false);
         return true;
     }
     if (!movespline->Initialized())
         return true;
     WorldPacket data(enable ? SMSG_SPLINE_MOVE_SET_FLYING : SMSG_SPLINE_MOVE_UNSET_FLYING, 9);
     data << GetPackGUID();
     SendMessageToSet(&data, false);
     return true;
 }
References Unit::BuildMovementPacket(), Object::GetPackGUID(), Position::GetPositionZ(), Movement::MoveSpline::Initialized(), Unit::m_movedByPlayer, Unit::movespline, MSG_MOVE_UPDATE_CAN_FLY, Player::SendDirectMessage(), WorldObject::SendMessageToSet(), Player::SendMessageToSet(), Unit::SetCanFly(), Player::SetFallInformation(), SMSG_MOVE_SET_CAN_FLY, SMSG_MOVE_UNSET_CAN_FLY, SMSG_SPLINE_MOVE_SET_FLYING, SMSG_SPLINE_MOVE_UNSET_FLYING, sScriptMgr, and Object::ToPlayer().
Referenced by boss_twin_valkyrAI::boss_twin_valkyrAI(), boss_jeklik::boss_jeklikAI::DamageTaken(), npc_ball_of_flame::npc_ball_of_flameAI::DoAction(), npc_kalecgos_kj::npc_kalecgos_kjAI::DoAction(), boss_sartharion_dragonAI::EnterCombat(), boss_jeklik::boss_jeklikAI::EnterCombat(), boss_ayamiss::boss_ayamissAI::EnterCombat(), boss_urom::boss_uromAI::EnterEvadeMode(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::FlyAway(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::GoToMinchar(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::HandleExtraEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::HandleExtraEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::HandleExtraEvent(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::InitializeAI(), npc_infra_green_bomber_generic::npc_infra_green_bomber_genericAI::IsSummonedBy(), boss_urom::boss_uromAI::JustDied(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::JustReachedHome(), brann_bronzebeard::brann_bronzebeardAI::JustSummoned(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::JustSummoned(), boss_kiljaeden::boss_kiljaedenAI::JustSummoned(), boss_onyxia::boss_onyxiaAI::MovementInform(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::MovementInform(), boss_sister_svalna::boss_sister_svalnaAI::MovementInform(), npc_icc_spire_frostwyrm::npc_icc_spire_frostwyrmAI::MovementInform(), npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI::MovementInform(), boss_nazan::boss_nazanAI::MovementInform(), npc_hallows_end_soh::npc_hallows_end_sohAI::MovementInform(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::MovementInform(), npc_alexstrasza::npc_alexstraszaAI::npc_alexstraszaAI(), npc_concentrated_ball::npc_concentrated_ballAI::npc_concentrated_ballAI(), npc_icc_spire_frostwyrm::npc_icc_spire_frostwyrmAI::npc_icc_spire_frostwyrmAI(), npc_pet_gen_moth::npc_pet_gen_moth(), npc_hover_disk::npc_hover_diskAI::PassengerBoarded(), npc_image_of_medivh::npc_image_of_medivhAI::Reset(), npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::Reset(), npc_hallows_end_soh::npc_hallows_end_sohAI::Reset(), boss_onyxia::boss_onyxiaAI::Reset(), boss_sartharion_dragonAI::Reset(), boss_sister_svalna::boss_sister_svalnaAI::Reset(), npc_ulduar_mimiron_rocket::npc_ulduar_mimiron_rocketAI::Reset(), boss_nazan::boss_nazanAI::Reset(), npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI::SetData(), SmartAI::SetFly(), npc_simon_bunny::npc_simon_bunnyAI::SetGUID(), boss_urom::boss_uromAI::SpellHit(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::UpdateAI(), boss_onyxia::boss_onyxiaAI::UpdateAI(), boss_ayamiss::boss_ayamissAI::UpdateAI(), npc_frost_sphere::npc_frost_sphereAI::UpdateAI(), boss_krick::boss_krickAI::UpdateAI(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::UpdateAI(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::UpdateAI(), boss_urom::boss_uromAI::UpdateAI(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI(), npc_pet_gen_wind_rider_cub::UpdateAI(), and UpdateMovementFlags().
SetCannotReachTarget()
void Creature::SetCannotReachTarget (bool cannotReach)
Definition at line 3403 of file Creature.cpp.
 {
     if (cannotReach == m_cannotReachTarget)
         return;
     m_cannotReachTarget = cannotReach;
     m_cannotReachTimer = 0;
     if (cannotReach)
         LOG_DEBUG("entities.unit", "Creature::SetCannotReachTarget() called with true. Details: %s", GetDebugInfo().c_str());
 }
References GetDebugInfo(), LOG_DEBUG, m_cannotReachTarget, and m_cannotReachTimer.
Referenced by CreatureAI::_EnterEvadeMode(), ChaseMovementGenerator< T >::DoUpdate(), and setDeathState().
SetCorpseDelay()
void Creature::SetCorpseDelay (uint32 delay) inline
Definition at line 71 of file Creature.h.
 { m_corpseDelay = delay; }
References m_corpseDelay.
Referenced by npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::JustDied(), npc_hor_raging_ghoul::npc_hor_raging_ghoulAI::JustDied(), npc_hor_risen_witch_doctor::npc_hor_risen_witch_doctorAI::JustDied(), npc_hor_lumbering_abomination::npc_hor_lumbering_abominationAI::JustDied(), npc_mindless_ghoul::npc_mindless_ghoulAI::JustDied(), npc_anubarak_spike::npc_anubarak_spikeAI::npc_anubarak_spikeAI(), npc_frost_sphere::npc_frost_sphereAI::npc_frost_sphereAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::npc_highlord_darion_mograineAI(), npc_mindless_ghoul::npc_mindless_ghoulAI::npc_mindless_ghoulAI(), instance_black_temple::instance_black_temple_InstanceMapScript::OnCreatureCreate(), ValithriaDespawner::operator()(), npc_varian_wrynn::npc_varian_wrynnAI::Reset(), npc_jaina_proudmoore_bfu::npc_jaina_proudmoore_bfuAI::Reset(), npc_thrall_bfu::npc_thrall_bfuAI::Reset(), npc_lady_sylvanas_windrunner_bfu::npc_lady_sylvanas_windrunner_bfuAI::Reset(), npc_swarm_scarab::npc_swarm_scarabAI::Reset(), npc_nerubian_burrower::npc_nerubian_burrowerAI::Reset(), npc_lk_wicked_spirit::npc_lk_wicked_spiritAI::Reset(), npc_valithria_cloud::npc_valithria_cloudAI::Reset(), npc_argent_captainAI::Reset(), npc_heated_battle::npc_heated_battleAI::Reset(), npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::Reset(), and boss_svala::boss_svalaAI::UpdateAI().
SetCurrentEquipmentId()
void Creature::SetCurrentEquipmentId (uint8 id) inline
Definition at line 180 of file Creature.h.
 { m_equipmentId = id; }
References m_equipmentId.
Referenced by npc_unworthy_initiate::npc_unworthy_initiateAI::npc_unworthy_initiateAI().
setDeathState()
void Creature::setDeathState (DeathState s, bool despawn = false) override virtual
Reimplemented from Unit.
Reimplemented in Pet, and Minion.
Definition at line 1783 of file Creature.cpp.
 {
     Unit::setDeathState(s, despawn);
     if (s == JUST_DIED)
     {
         _lastDamagedTime.reset();
         m_corpseRemoveTime = time(nullptr) + m_corpseDelay;
         m_respawnTime = time(nullptr) + m_respawnDelay + m_corpseDelay;
         // always save boss respawn time at death to prevent crash cheating
         if (GetMap()->IsDungeon() || isWorldBoss() || GetCreatureTemplate()->rank >= CREATURE_ELITE_ELITE)
             SaveRespawnTime();
         SetTarget();                // remove target selection in any cases (can be set at aura remove in Unit::setDeathState)
         SetUInt32Value(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_NONE);
         Dismount(); // if creature is mounted on a virtual mount, remove it at death
         setActive(false);
         if (!IsPet() && GetCreatureTemplate()->SkinLootId)
             if (LootTemplates_Skinning.HaveLootFor(GetCreatureTemplate()->SkinLootId))
                 if (hasLootRecipient())
                     SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_SKINNABLE);
         if (HasSearchedAssistance())
         {
             SetNoSearchAssistance(false);
         }
         //Dismiss group if is leader
         if (m_formation && m_formation->getLeader() == this)
             m_formation->FormationReset(true, false);
         bool needsFalling = !despawn && (IsFlying() || IsHovering()) && !IsUnderWater();
         SetHover(false);
         SetDisableGravity(false);
         if (needsFalling)
             GetMotionMaster()->MoveFall(0, true);
         Unit::setDeathState(CORPSE, despawn);
     }
     else if (s == JUST_RESPAWNED)
     {
         //if (IsPet())
         //    setActive(true);
         SetFullHealth();
         SetLootRecipient(nullptr);
         ResetPlayerDamageReq();
         SetCannotReachTarget(false);
         CreatureTemplate const* cinfo = GetCreatureTemplate();
         // Xinef: npc run by default
         //SetWalk(true);
         // pussywizard:
         if (HasUnitMovementFlag(MOVEMENTFLAG_FALLING))
             RemoveUnitMovementFlag(MOVEMENTFLAG_FALLING);
         UpdateMovementFlags();
         SetUInt32Value(UNIT_NPC_FLAGS, cinfo->npcflag);
         ClearUnitState(uint32(UNIT_STATE_ALL_STATE & ~(UNIT_STATE_IGNORE_PATHFINDING | UNIT_STATE_NO_ENVIRONMENT_UPD)));
         SetMeleeDamageSchool(SpellSchools(cinfo->dmgschool));
         Unit::setDeathState(ALIVE, despawn);
         Motion_Initialize();
         LoadCreaturesAddon(true);
         if (GetCreatureData() && GetPhaseMask() != GetCreatureData()->phaseMask)
             SetPhaseMask(GetCreatureData()->phaseMask, false);
     }
 }
References _lastDamagedTime, ALIVE, Unit::ClearUnitState(), CORPSE, CREATURE_ELITE_ELITE, Unit::Dismount(), CreatureTemplate::dmgschool, CreatureGroup::FormationReset(), GetCreatureData(), GetCreatureTemplate(), CreatureGroup::getLeader(), WorldObject::GetMap(), Unit::GetMotionMaster(), WorldObject::GetPhaseMask(), hasLootRecipient(), HasSearchedAssistance(), Unit::HasUnitMovementFlag(), LootStore::HaveLootFor(), Unit::IsFlying(), Unit::IsHovering(), Unit::IsPet(), Unit::IsUnderWater(), isWorldBoss(), JUST_DIED, JUST_RESPAWNED, LoadCreaturesAddon(), LootTemplates_Skinning, m_corpseDelay, m_corpseRemoveTime, m_formation, m_respawnDelay, m_respawnTime, Motion_Initialize(), MotionMaster::MoveFall(), MOVEMENTFLAG_FALLING, CreatureTemplate::npcflag, Unit::RemoveUnitMovementFlag(), ResetPlayerDamageReq(), SaveRespawnTime(), WorldObject::setActive(), SetCannotReachTarget(), Unit::setDeathState(), SetDisableGravity(), Object::SetFlag(), Unit::SetFullHealth(), SetHover(), SetLootRecipient(), SetMeleeDamageSchool(), SetNoSearchAssistance(), Unit::SetPhaseMask(), SetTarget(), Object::SetUInt32Value(), UNIT_FIELD_FLAGS, UNIT_FLAG_SKINNABLE, UNIT_NPC_FLAG_NONE, UNIT_NPC_FLAGS, UNIT_STATE_ALL_STATE, UNIT_STATE_IGNORE_PATHFINDING, UNIT_STATE_NO_ENVIRONMENT_UPD, and UpdateMovementFlags().
Referenced by BattlegroundAV::AddAVCreature(), DisappearAndDie(), npc_auriaya_feral_defender::npc_auriaya_feral_defenderAI::DoAction(), boss_freya_summons::boss_freya_summonsAI::DoAction(), ForcedDespawn(), misc_commandscript::HandleCreatePetCommand(), npc_commandscript::HandleNpcMoveCommand(), npc_commandscript::HandleNpcSetMoveTypeCommand(), npc_commandscript::HandleNpcSetWanderDistanceCommand(), boss_twinemperorsAI::JustDied(), npc_nether_drake::npc_nether_drakeAI::MovementInform(), instance_ulduar::instance_ulduar_InstanceMapScript::OnCreatureCreate(), RemoveCorpse(), Respawn(), npc_simone::npc_simoneAI::RespawnPet(), Minion::setDeathState(), Pet::setDeathState(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::SpawnAdds(), npc_argent_captainAI::SpellHit(), npc_drakuru_shackles::npc_drakuru_shacklesAI::SpellHit(), npc_escortAI::UpdateAI(), npc_a_special_surprise::npc_a_special_surpriseAI::UpdateAI(), npc_towering_infernal::npc_towering_infernalAI::UpdateAI(), npc_lesser_doomguard::npc_lesser_doomguardAI::UpdateAI(), npc_clintar_spirit::npc_clintar_spiritAI::UpdateAI(), npc_injured_patient::npc_injured_patientAI::UpdateAI(), npc_abomination::npc_abominationAI::WaypointReached(), and npc_ghoul::npc_ghoulAI::WaypointReached().
SetDefaultMovementType()
void Creature::SetDefaultMovementType (MovementGeneratorType mgt) inline
Definition at line 266 of file Creature.h.
 { m_defaultMovementType = mgt; }
References m_defaultMovementType.
Referenced by npc_spinestalker::npc_spinestalkerAI::DoAction(), npc_rimefang::npc_rimefangAI::DoAction(), npc_commandscript::HandleNpcSetMoveTypeCommand(), npc_commandscript::HandleNpcSetWanderDistanceCommand(), wp_commandscript::HandleWpLoadCommand(), and wp_commandscript::HandleWpUnLoadCommand().
SetDetectionDistance()
void Creature::SetDetectionDistance (float dist) inline
Definition at line 192 of file Creature.h.
 { m_detectionDistance = dist; }
References m_detectionDistance.
Referenced by UpdateEntry().
SetDisableGravity()
bool Creature::SetDisableGravity (bool disable, bool packetOnly = false) override virtual
It's possible only a packet is sent but moveflags are not updated Need more research on this
movement counter
Reimplemented from Unit.
Definition at line 2891 of file Creature.cpp.
 {
     if (!packetOnly && !Unit::SetDisableGravity(disable))
         return false;
     applyInhabitFlags();
     if (m_movedByPlayer)
     {
         WorldPacket data(disable ? SMSG_MOVE_GRAVITY_DISABLE : SMSG_MOVE_GRAVITY_ENABLE, 12);
         data << GetPackGUID();
         data << uint32(0);
         m_movedByPlayer->ToPlayer()->SendDirectMessage(&data);
         data.Initialize(MSG_MOVE_GRAVITY_CHNG, 64);
         data << GetPackGUID();
         BuildMovementPacket(&data);
         m_movedByPlayer->ToPlayer()->SendMessageToSet(&data, false);
         return true;
     }
     if (!movespline->Initialized())
         return true;
     WorldPacket data(disable ? SMSG_SPLINE_MOVE_GRAVITY_DISABLE : SMSG_SPLINE_MOVE_GRAVITY_ENABLE, 9);
     data << GetPackGUID();
     SendMessageToSet(&data, false);
     return true;
 }
References applyInhabitFlags(), Unit::BuildMovementPacket(), Object::GetPackGUID(), Movement::MoveSpline::Initialized(), Unit::m_movedByPlayer, Unit::movespline, MSG_MOVE_GRAVITY_CHNG, Player::SendDirectMessage(), WorldObject::SendMessageToSet(), Player::SendMessageToSet(), Unit::SetDisableGravity(), SMSG_MOVE_GRAVITY_DISABLE, SMSG_MOVE_GRAVITY_ENABLE, SMSG_SPLINE_MOVE_GRAVITY_DISABLE, SMSG_SPLINE_MOVE_GRAVITY_ENABLE, and Object::ToPlayer().
Referenced by boss_twin_valkyrAI::boss_twin_valkyrAI(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::boss_yoggsaron_brainAI(), boss_the_lich_king::boss_the_lich_kingAI::DamageTaken(), boss_taldaram::boss_taldaramAI::DoAction(), npc_ball_of_flame::npc_ball_of_flameAI::DoAction(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction(), boss_sindragosa::boss_sindragosaAI::DoAction(), boss_algalon_the_observer::boss_algalon_the_observerAI::DoAction(), npc_madrigosa::npc_madrigosaAI::DoAction(), npc_kalecgos_kj::npc_kalecgos_kjAI::DoAction(), boss_ayamiss::boss_ayamissAI::EnterCombat(), boss_malygos::boss_malygosAI::EnterEvadeMode(), boss_urom::boss_uromAI::EnterEvadeMode(), boss_razorscale::boss_razorscaleAI::EnterEvadeMode(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::FlyAway(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::GoToMinchar(), npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::HandleAnimation(), boss_taldaram::boss_taldaramAI::InitializeAI(), boss_malygos::boss_malygosAI::InitializeAI(), boss_razorscale::boss_razorscaleAI::InitializeAI(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::InitializeAI(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::IsSummonedBy(), boss_urom::boss_uromAI::JustDied(), boss_saviana_ragefire::boss_saviana_ragefireAI::JustReachedHome(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::JustReachedHome(), boss_sindragosa::boss_sindragosaAI::JustReachedHome(), npc_spinestalker::npc_spinestalkerAI::JustReachedHome(), npc_rimefang::npc_rimefangAI::JustReachedHome(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::JustReachedHome(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::JustSummoned(), boss_kiljaeden::boss_kiljaedenAI::JustSummoned(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::JustSummoned(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::JustSummoned(), boss_algalon_the_observer::boss_algalon_the_observerAI::MovementInform(), boss_onyxia::boss_onyxiaAI::MovementInform(), boss_taldaram::boss_taldaramAI::MovementInform(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::MovementInform(), boss_sister_svalna::boss_sister_svalnaAI::MovementInform(), npc_icc_spire_frostwyrm::npc_icc_spire_frostwyrmAI::MovementInform(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::MovementInform(), boss_malygos::boss_malygosAI::MovementInform(), npc_oculus_drake::npc_oculus_drakeAI::MovementInform(), boss_razorscale::boss_razorscaleAI::MovementInform(), npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI::MovementInform(), boss_nazan::boss_nazanAI::MovementInform(), npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI::MovementInform(), boss_felmyst::boss_felmystAI::MovementInform(), npc_hallows_end_soh::npc_hallows_end_sohAI::MovementInform(), boss_saviana_ragefire::boss_saviana_ragefireAI::MovementInform(), boss_sindragosa::boss_sindragosaAI::MovementInform(), npc_spinestalker::npc_spinestalkerAI::MovementInform(), npc_rimefang::npc_rimefangAI::MovementInform(), boss_kaelthas::boss_kaelthasAI::MovementInform(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::MovementInform(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::MovementInform(), npc_alexstrasza::npc_alexstraszaAI::npc_alexstraszaAI(), npc_attracted_reef_bull::npc_attracted_reef_bullAI::npc_attracted_reef_bullAI(), npc_concentrated_ball::npc_concentrated_ballAI::npc_concentrated_ballAI(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::npc_icc_nerubar_broodkeeperAI(), npc_icc_spire_frostwyrm::npc_icc_spire_frostwyrmAI::npc_icc_spire_frostwyrmAI(), npc_pet_gen_moth::npc_pet_gen_moth(), npc_pet_gen_valkyr_guardian::npc_pet_gen_valkyr_guardian(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::npc_ulduar_aerial_command_unitAI(), instance_ulduar::instance_ulduar_InstanceMapScript::OnCreatureCreate(), npc_eoe_wyrmrest_skytalon::npc_eoe_wyrmrest_skytalonAI::PassengerBoarded(), npc_oculus_drake::npc_oculus_drakeAI::PassengerBoarded(), SmartScript::ProcessAction(), boss_nightbane::boss_nightbaneAI::Reset(), boss_felmyst::boss_felmystAI::Reset(), boss_kalecgos::boss_kalecgosAI::Reset(), boss_kalec::boss_kalecAI::Reset(), npc_akilzon_eagle::npc_akilzon_eagleAI::Reset(), npc_janalai_hatchling::npc_janalai_hatchlingAI::Reset(), npc_soh_fire_trigger::npc_soh_fire_triggerAI::Reset(), npc_hallows_end_soh::npc_hallows_end_sohAI::Reset(), boss_headless_horseman::boss_headless_horsemanAI::Reset(), npc_frost_wyrm::npc_frost_wyrmAI::Reset(), npc_gargoyle::npc_gargoyleAI::Reset(), boss_onyxia::boss_onyxiaAI::Reset(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::Reset(), npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::Reset(), boss_sindragosa::boss_sindragosaAI::Reset(), npc_spinestalker::npc_spinestalkerAI::Reset(), npc_rimefang::npc_rimefangAI::Reset(), boss_sister_svalna::boss_sister_svalnaAI::Reset(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::Reset(), boss_kologarn::boss_kologarnAI::Reset(), boss_thorim_pillar::boss_thorim_pillarAI::Reset(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::Reset(), boss_illidan_stormrage::boss_illidan_stormrageAI::Reset(), boss_nazan::boss_nazanAI::Reset(), boss_kaelthas::boss_kaelthasAI::Reset(), npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI::Reset(), npc_dancing_flames::npc_dancing_flamesAI::Reset(), npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI::SetData(), setDeathState(), boss_urom::boss_uromAI::SpellHit(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::SpellHit(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::SpellHit(), npc_saurfang_event::npc_saurfang_eventAI::SpellHit(), boss_nightbane::boss_nightbaneAI::TakeOff(), boss_nightbane::boss_nightbaneAI::UpdateAI(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::UpdateAI(), npc_madrigosa::npc_madrigosaAI::UpdateAI(), boss_felmyst::boss_felmystAI::UpdateAI(), boss_kalecgos::boss_kalecgosAI::UpdateAI(), npc_highborne_lamenter::npc_highborne_lamenterAI::UpdateAI(), npc_giant_infernal::npc_giant_infernalAI::UpdateAI(), boss_onyxia::boss_onyxiaAI::UpdateAI(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::UpdateAI(), boss_saviana_ragefire::boss_saviana_ragefireAI::UpdateAI(), boss_krick::boss_krickAI::UpdateAI(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::UpdateAI(), boss_sindragosa::boss_sindragosaAI::UpdateAI(), npc_rimefang::npc_rimefangAI::UpdateAI(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::UpdateAI(), boss_sapphiron::boss_sapphironAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), boss_urom::boss_uromAI::UpdateAI(), npc_oculus_drake::npc_oculus_drakeAI::UpdateAI(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), boss_razorscale::boss_razorscaleAI::UpdateAI(), boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI(), boss_kaelthas::boss_kaelthasAI::UpdateAI(), npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI::UpdateAI(), npc_pet_gen_wind_rider_cub::UpdateAI(), and UpdateMovementFlags().
SetDisableReputationGain()
void Creature::SetDisableReputationGain (bool disable) inline
Definition at line 339 of file Creature.h.
 { DisableReputationGain = disable; }
References DisableReputationGain.
Referenced by hyjalAI::SummonCreature().
SetDisplayId()
void Creature::SetDisplayId (uint32 modelId) override virtual
Reimplemented from Unit.
Reimplemented in Pet.
Definition at line 3269 of file Creature.cpp.
 {
     Unit::SetDisplayId(modelId);
     float combatReach = DEFAULT_WORLD_OBJECT_SIZE;
     if (CreatureModelInfo const* minfo = sObjectMgr->GetCreatureModelInfo(modelId))
     {
         SetFloatValue(UNIT_FIELD_BOUNDINGRADIUS, (IsPet() ? 1.0f : minfo->bounding_radius) * GetObjectScale());
         if (minfo->combat_reach > 0)
             combatReach = minfo->combat_reach;
     }
     if (IsPet())
         combatReach = DEFAULT_COMBAT_REACH;
     SetFloatValue(UNIT_FIELD_COMBATREACH, combatReach * GetObjectScale());
 }
References DEFAULT_COMBAT_REACH, DEFAULT_WORLD_OBJECT_SIZE, Object::GetObjectScale(), Unit::IsPet(), Unit::SetDisplayId(), Object::SetFloatValue(), sObjectMgr, UNIT_FIELD_BOUNDINGRADIUS, and UNIT_FIELD_COMBATREACH.
Referenced by npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::Activate(), Create(), npc_terenas_menethil::npc_terenas_menethilAI::DamageTaken(), npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::Deactivate(), npc_icc_severed_essence::npc_icc_severed_essenceAI::DoAction(), boss_ichoron::boss_ichoronAI::DoExplodeCompleted(), boss_laj::boss_lajAI::DoTransform(), SACDeactivateEvent::Execute(), npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::HandleAnimation(), npc_commandscript::HandleNpcSetModelCommand(), wp_commandscript::HandleWpShowCommand(), InitEntry(), npc_troll_volunteer::npc_troll_volunteerAI::InitializeAI(), Totem::InitStats(), Guardian::InitStatsForLevel(), npc_eoe_wyrmrest_skytalon::npc_eoe_wyrmrest_skytalonAI::JustDied(), boss_ichoron::boss_ichoronAI::JustDied(), boss_tharon_ja::boss_tharon_jaAI::JustDied(), npc_scholomance_occultist::npc_scholomance_occultistAI::JustReachedHome(), npc_fairbanks::npc_fairbanksAI::MoveInLineOfSight(), npc_cw_area_trigger::npc_cw_area_triggerAI::npc_cw_area_triggerAI(), npc_giant_infernal::npc_giant_infernalAI::npc_giant_infernalAI(), npc_grizzlemaw_cw_trigger::npc_grizzlemaw_cw_triggerAI::npc_grizzlemaw_cw_triggerAI(), npc_scarlet_miner_cart::npc_scarlet_miner_cartAI::npc_scarlet_miner_cartAI(), npc_the_biggest_tree::npc_the_biggest_treeAI::npc_the_biggest_treeAI(), npc_eoe_wyrmrest_skytalon::npc_eoe_wyrmrest_skytalonAI::PassengerBoarded(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::ReorderInstance(), boss_kalec::boss_kalecAI::Reset(), boss_black_knight::boss_black_knightAI::Reset(), boss_tharon_ja::boss_tharon_jaAI::Reset(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::Reset(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::Reset(), boss_ichoron::boss_ichoronAI::Reset(), boss_laj::boss_lajAI::Reset(), npc_infernal_attacker::npc_infernal_attackerAI::Reset(), Respawn(), Pet::SetDisplayId(), netherspite_infernal::netherspite_infernalAI::SpellHit(), npc_harrison_jones::npc_harrison_jonesAI::SpellHit(), npc_infernal_attacker::npc_infernal_attackerAI::SpellHit(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::SpellHit(), boss_black_knight::boss_black_knightAI::SpellHitTarget(), boss_malchezaar::boss_malchezaarAI::SummonInfernal(), npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::SummonNextWave(), npc_harrison_jones::npc_harrison_jonesAI::UpdateAI(), boss_renataki::boss_renatakiAI::UpdateAI(), npc_giant_infernal::npc_giant_infernalAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), npc_frost_sphere::npc_frost_sphereAI::UpdateAI(), boss_tharon_ja::boss_tharon_jaAI::UpdateAI(), npc_pos_collapsing_icicle::npc_pos_collapsing_icicleAI::UpdateAI(), npc_terenas_menethil::npc_terenas_menethilAI::UpdateAI(), npc_blistering_zombie::npc_blistering_zombieAI::UpdateAI(), npc_ulduar_icicle::npc_ulduar_icicleAI::UpdateAI(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateAI(), npc_azure_saboteur::npc_azure_saboteurAI::UpdateAI(), and boss_ichoron::boss_ichoronAI::UpdateAI().
SetFeatherFall()
bool Creature::SetFeatherFall (bool enable, bool packetOnly = false) override virtual
movement counter
Reimplemented from Unit.
Definition at line 3060 of file Creature.cpp.
 {
     if (!packetOnly && !Unit::SetFeatherFall(enable))
         return false;
     if (m_movedByPlayer)
     {
         WorldPacket data(enable ? SMSG_MOVE_FEATHER_FALL : SMSG_MOVE_NORMAL_FALL, 12);
         data << GetPackGUID();
         data << uint32(0);
         m_movedByPlayer->ToPlayer()->SendDirectMessage(&data);
         data.Initialize(MSG_MOVE_FEATHER_FALL, 64);
         data << GetPackGUID();
         BuildMovementPacket(&data);
         m_movedByPlayer->ToPlayer()->SendMessageToSet(&data, false);
         return true;
     }
     if (!movespline->Initialized())
         return true;
     WorldPacket data(enable ? SMSG_SPLINE_MOVE_FEATHER_FALL : SMSG_SPLINE_MOVE_NORMAL_FALL, 9);
     data << GetPackGUID();
     SendMessageToSet(&data, true);
     return true;
 }
References Unit::BuildMovementPacket(), Object::GetPackGUID(), Movement::MoveSpline::Initialized(), Unit::m_movedByPlayer, Unit::movespline, MSG_MOVE_FEATHER_FALL, Player::SendDirectMessage(), WorldObject::SendMessageToSet(), Player::SendMessageToSet(), Unit::SetFeatherFall(), SMSG_MOVE_FEATHER_FALL, SMSG_MOVE_NORMAL_FALL, SMSG_SPLINE_MOVE_FEATHER_FALL, SMSG_SPLINE_MOVE_NORMAL_FALL, and Object::ToPlayer().
SetFormation()
void Creature::SetFormation (CreatureGroup * formation) inline
Definition at line 335 of file Creature.h.
 { m_formation = formation; }
References m_formation.
Referenced by CreatureGroup::AddMember(), and CreatureGroup::RemoveMember().
SetHomePosition() [1/2]
void Creature::SetHomePosition (const Position & pos) inline
Definition at line 317 of file Creature.h.
 { m_homePosition.Relocate(pos); }
References m_homePosition, pos(), and Position::Relocate().
SetHomePosition() [2/2]
void Creature::SetHomePosition (float x, float y, float z, float o) inline
Definition at line 316 of file Creature.h.
 { m_homePosition.Relocate(x, y, z, o); }
References m_homePosition, Position::Relocate(), G3D::x, G3D::y, and G3D::z.
Referenced by Battleground::AddCreature(), boss_loatheb::boss_loathebAI::boss_loathebAI(), MotionTransport::CreateNPCPassenger(), DespawnOnEvade(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::DestroyDoor(), npc_icc_spire_frostwyrm::npc_icc_spire_frostwyrmAI::DoAction(), boss_taldaram::boss_taldaramAI::DoAction(), brann_bronzebeard::brann_bronzebeardAI::DoAction(), boss_algalon_the_observer::boss_algalon_the_observerAI::DoAction(), boss_tyrannus::boss_tyrannusAI::DoAction(), hyjalAI::DoOverrun(), boss_mandokir::boss_mandokirAI::EnterCombat(), boss_urom::boss_uromAI::EnterCombat(), boss_flame_leviathan::boss_flame_leviathanAI::EnterCombat(), violet_hold_trashAI::EnterEvadeMode(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::GoSiphon(), spell_item_toxic_wasteling::HandleJump(), boss_aeonus::boss_aeonusAI::InitializeAI(), boss_eck::boss_eckAI::InitializeAI(), boss_flame_leviathan::boss_flame_leviathanAI::InitializeAI(), npc_simone::npc_simoneAI::JustDied(), npc_shay_leafrunner::npc_shay_leafrunnerAI::JustRespawned(), exarch_orelis::exarch_orelisAI::JustSummoned(), boss_kelthuzad::boss_kelthuzadAI::JustSummoned(), npc_daphne_stilwell::npc_daphne_stilwellAI::JustSummoned(), npc_hor_lich_king::npc_hor_lich_kingAI::JustSummoned(), boss_the_lich_king::boss_the_lich_kingAI::JustSummoned(), boss_algalon_the_observer::boss_algalon_the_observerAI::JustSummoned(), CreatureGroup::LeaderMoveTo(), LoadCreatureFromDB(), npc_aged_dying_ancient_kodo::npc_aged_dying_ancient_kodoAI::MoveInLineOfSight(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::MoveInLineOfSight(), boss_nightbane::boss_nightbaneAI::MovementInform(), boss_mandokir::boss_mandokirAI::MovementInform(), npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI::MovementInform(), boss_sindragosa::boss_sindragosaAI::MovementInform(), npc_spinestalker::npc_spinestalkerAI::MovementInform(), npc_rimefang::npc_rimefangAI::MovementInform(), adyen_the_lightbringer::adyen_the_lightbringerAI::MovementInform(), anchorite_karja::anchorite_karjaAI::MovementInform(), exarch_orelis::exarch_orelisAI::MovementInform(), kaylaan_the_lost::kaylaan_the_lostAI::MovementInform(), npc_omen::npc_omenAI::MovementInform(), npc_gunship_boarding_addAI::MovementInform(), npc_zelfrax::npc_zelfraxAI::MovementInform(), npc_escortAI::MovementInform(), SmartAI::MovepointReached(), npc_akama_illidan::npc_akama_illidanAI::npc_akama_illidanAI(), npc_natrualist_bite::OnGossipSelect(), RemoveCorpse(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::Reposition(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::Reposition(), boss_nightbane::boss_nightbaneAI::Reset(), npc_simone::npc_simoneAI::RespawnPet(), gunship_npc_AI::SetData(), NPCStaveQuestAI::SetHomePosition(), Battlefield::SpawnCreature(), boss_urom::boss_uromAI::SpellHit(), boss_majordomo::boss_majordomoAI::SpellHit(), boss_ionar::boss_ionarAI::Split(), WaypointMovementGenerator< Creature >::StartMove(), Map::SummonCreature(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), hyjal_trashAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), npc_shay_leafrunner::npc_shay_leafrunnerAI::UpdateAI(), npc_twilight_volunteer::npc_twilight_volunteerAI::UpdateAI(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::UpdateAI(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::UpdateAI(), violet_hold_trashAI::UpdateAI(), npc_azure_saboteur::npc_azure_saboteurAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::UpdateAI(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::UpdateAI(), socrethar::socretharAI::UpdateAI(), and MotionTransport::UpdatePassengerPositions().
SetHover()
bool Creature::SetHover (bool enable, bool packetOnly = false) override virtual
movement counter
Not always a packet is sent
Reimplemented from Unit.
Definition at line 3088 of file Creature.cpp.
 {
     if (!packetOnly && !Unit::SetHover(enable))
         return false;
    applyInhabitFlags();
    if (m_movedByPlayer)
    {
        WorldPacket data(enable ? SMSG_MOVE_SET_HOVER : SMSG_MOVE_UNSET_HOVER, 12);
        data << GetPackGUID();
        data << uint32(0);
        m_movedByPlayer->ToPlayer()->SendDirectMessage(&data);
        data.Initialize(MSG_MOVE_HOVER, 64);
        data << GetPackGUID();
        BuildMovementPacket(&data);
        m_movedByPlayer->ToPlayer()->SendMessageToSet(&data, false);
        return true;
    }
     if (!movespline->Initialized())
         return true;
     WorldPacket data(enable ? SMSG_SPLINE_MOVE_SET_HOVER : SMSG_SPLINE_MOVE_UNSET_HOVER, 9);
     data << GetPackGUID();
     SendMessageToSet(&data, false);
     return true;
 }
References applyInhabitFlags(), Unit::BuildMovementPacket(), Object::GetPackGUID(), Movement::MoveSpline::Initialized(), Unit::m_movedByPlayer, Unit::movespline, MSG_MOVE_HOVER, Player::SendDirectMessage(), WorldObject::SendMessageToSet(), Player::SendMessageToSet(), Unit::SetHover(), SMSG_MOVE_SET_HOVER, SMSG_MOVE_UNSET_HOVER, SMSG_SPLINE_MOVE_SET_HOVER, SMSG_SPLINE_MOVE_UNSET_HOVER, and Object::ToPlayer().
Referenced by boss_taldaram::boss_taldaramAI::DoAction(), npc_ball_of_flame::npc_ball_of_flameAI::DoAction(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::EnterCombat(), boss_taldaram::boss_taldaramAI::InitializeAI(), boss_saviana_ragefire::boss_saviana_ragefireAI::JustReachedHome(), boss_taldaram::boss_taldaramAI::MovementInform(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::MovementInform(), npc_depth_charge::npc_depth_chargeAI::Reset(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::Reset(), npc_dark_nucleus::npc_dark_nucleusAI::Reset(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::Reset(), boss_svala::boss_svalaAI::Reset(), setDeathState(), npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI::UpdateAI(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), and UpdateMovementFlags().
SetInCombatWithZone()
void Creature::SetInCombatWithZone ()
Definition at line 2555 of file Creature.cpp.
 {
     if (IsAIEnabled)
         AI()->DoZoneInCombat();
 }
References AI(), CreatureAI::DoZoneInCombat(), and Unit::IsAIEnabled.
Referenced by npc_mograine::npc_mograineAI::DamageTaken(), npc_ghostly_priest::npc_ghostly_priestAI::DoAction(), npc_phantom_mage::npc_phantom_mageAI::DoAction(), npc_shadowy_mercenary::npc_shadowy_mercenaryAI::DoAction(), npc_spectral_footman::npc_spectral_footmanAI::DoAction(), npc_tortured_rifleman::npc_tortured_riflemanAI::DoAction(), npc_ball_of_flame::npc_ball_of_flameAI::DoAction(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::DoAction(), npc_risen_archmage::npc_risen_archmageAI::DoAction(), npc_living_constellation::npc_living_constellationAI::DoAction(), boss_broggok::boss_broggokAI::DoAction(), npc_love_in_air_hummel_helper::npc_love_in_air_hummel_helperAI::DoAction(), boss_drakkari_colossus::boss_drakkari_colossusAI::DoAction(), boss_thaddius_summon::boss_thaddius_summonAI::DoAction(), boss_yoggsaron::boss_yoggsaronAI::DoAction(), boss_palehoof::boss_palehoofAI::DoAction(), npc_massive_jormungar::npc_massive_jormungarAI::DoAction(), npc_ferocious_rhino::npc_ferocious_rhinoAI::DoAction(), npc_ravenous_furbolg::npc_ravenous_furbolgAI::DoAction(), npc_frenzied_worgen::npc_frenzied_worgenAI::DoAction(), boss_skadi::boss_skadiAI::DoAction(), boss_essence_of_suffering::boss_essence_of_sufferingAI::DoAction(), boss_essence_of_desire::boss_essence_of_desireAI::DoAction(), boss_essence_of_anger::boss_essence_of_angerAI::DoAction(), boss_the_lurker_below::boss_the_lurker_belowAI::DoAction(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::DoAction(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::EnterCombat(), boss_headless_horseman::boss_headless_horsemanAI::EnterCombat(), boss_volazj::boss_volazjAI::EnterCombat(), boss_twilight_halion::boss_twilight_halionAI::EnterCombat(), boss_faction_championsAI::EnterCombat(), npc_risen_archmage::npc_risen_archmageAI::EnterCombat(), npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::EnterCombat(), boss_kelthuzad_minion::boss_kelthuzad_minionAI::EnterCombat(), boss_drakos::boss_drakosAI::EnterCombat(), boss_eregos::boss_eregosAI::EnterCombat(), boss_urom::boss_uromAI::EnterCombat(), boss_varos::boss_varosAI::EnterCombat(), boss_bjarngrim::boss_bjarngrimAI::EnterCombat(), boss_ionar::boss_ionarAI::EnterCombat(), boss_loken::boss_lokenAI::EnterCombat(), boss_volkhan::boss_volkhanAI::EnterCombat(), boss_algalon_the_observer::boss_algalon_the_observerAI::EnterCombat(), boss_flame_leviathan::boss_flame_leviathanAI::EnterCombat(), boss_freya::boss_freyaAI::EnterCombat(), boss_vezax::boss_vezaxAI::EnterCombat(), boss_razorscale::boss_razorscaleAI::EnterCombat(), boss_xt002::boss_xt002AI::EnterCombat(), boss_skadi::boss_skadiAI::EnterCombat(), boss_skadi_grauf::boss_skadi_graufAI::EnterCombat(), boss_svala::boss_svalaAI::EnterCombat(), npc_frozen_orb::npc_frozen_orbAI::EnterCombat(), boss_nexusprince_shaffar::boss_nexusprince_shaffarAI::EnterCombat(), boss_pandemonius::boss_pandemoniusAI::EnterCombat(), boss_olm_the_summoner::boss_olm_the_summonerAI::EnterCombat(), boss_kiggler_the_crazed::boss_kiggler_the_crazedAI::EnterCombat(), boss_blindeye_the_seer::boss_blindeye_the_seerAI::EnterCombat(), boss_krosh_firehand::boss_krosh_firehandAI::EnterCombat(), boss_harbinger_skyriss::boss_harbinger_skyrissAI::EnterCombat(), boss_thaddius_summon::boss_thaddius_summonAI::EnterCombat(), boss_the_lich_king::boss_the_lich_kingAI::EnterCombat(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::EnterCombat(), boss_sindragosa::boss_sindragosaAI::EnterCombat(), boss_trollgore::boss_trollgoreAI::EnterCombat(), boss_gluth::boss_gluthAI::EnterCombat(), boss_gothik::boss_gothikAI::EnterCombat(), boss_grobbulus::boss_grobbulusAI::EnterCombat(), boss_heigan::boss_heiganAI::EnterCombat(), boss_loatheb::boss_loathebAI::EnterCombat(), boss_maexxna::boss_maexxnaAI::EnterCombat(), boss_patchwerk::boss_patchwerkAI::EnterCombat(), boss_thaddius::boss_thaddiusAI::EnterCombat(), boss_steelbreaker::boss_steelbreakerAI::EnterCombat(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::EnterCombat(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::EnterCombat(), npc_little_ooze::npc_little_oozeAI::EnterEvadeMode(), npc_big_ooze::npc_big_oozeAI::EnterEvadeMode(), boss_algalon_the_observer::boss_algalon_the_observerAI::EnterEvadeMode(), RestoreFight::Execute(), spell_teron_gorefiend_shadowy_construct::spell_teron_gorefiend_shadowy_construct_AuraScript::HandleEffectApply(), spell_the_lich_king_vile_spirit_move_target_search::spell_the_lich_king_vile_spirit_move_target_search_SpellScript::HandleScript(), spell_putricide_mutated_transformation::spell_putricide_mutated_transformation_SpellScript::HandleSummon(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::InitFight(), brann_bronzebeard::brann_bronzebeardAI::InitializeEvent(), npc_living_inferno::npc_living_infernoAI::IsSummonedBy(), boss_anubrekhan::boss_anubrekhanAI::JustSummoned(), boss_grobbulus::boss_grobbulusAI::JustSummoned(), boss_loatheb::boss_loathebAI::JustSummoned(), boss_maexxna::boss_maexxnaAI::JustSummoned(), boss_auriaya::boss_auriayaAI::JustSummoned(), boss_dalronn_the_controller::boss_dalronn_the_controllerAI::JustSummoned(), boss_urom::boss_uromAI::JustSummoned(), npc_hor_lich_king::npc_hor_lich_kingAI::JustSummoned(), boss_curator::boss_curatorAI::JustSummoned(), boss_midnight::boss_midnightAI::JustSummoned(), npc_demonic_vapor_trail::npc_demonic_vapor_trailAI::JustSummoned(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::JustSummoned(), boss_muru::boss_muruAI::JustSummoned(), boss_anub_arak::boss_anub_arakAI::JustSummoned(), boss_novos::boss_novosAI::JustSummoned(), boss_slad_ran::boss_slad_ranAI::JustSummoned(), boss_professor_putricide::boss_professor_putricideAI::JustSummoned(), boss_noth::boss_nothAI::JustSummoned(), boss_magus_telestra::boss_magus_telestraAI::JustSummoned(), npc_creature_generator_akama::npc_creature_generator_akamaAI::JustSummoned(), boss_hydross_the_unstable::boss_hydross_the_unstableAI::JustSummoned(), boss_the_lurker_below::boss_the_lurker_belowAI::JustSummoned(), boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI::JustSummoned(), boss_ahune::boss_ahuneAI::JustSummoned(), boss_omor_the_unscarred::boss_omor_the_unscarredAI::JustSummoned(), boss_vazruden_the_herald::boss_vazruden_the_heraldAI::JustSummoned(), boss_harbinger_skyriss::boss_harbinger_skyrissAI::JustSummoned(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::JustSummoned(), boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI::JustSummoned(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::MoveInLineOfSight(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::MoveInLineOfSight(), boss_kaelthas::boss_kaelthasAI::MoveInLineOfSight(), boss_four_horsemen::boss_four_horsemenAI::MovementInform(), boss_headless_horseman::boss_headless_horsemanAI::MovementInform(), boss_sindragosa::boss_sindragosaAI::MovementInform(), boss_sartharion_dragonAI::MovementInform(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::MovementInform(), npc_gunship_mage::npc_gunship_mageAI::MovementInform(), npc_ulduar_saronite_animus::npc_ulduar_saronite_animusAI::npc_ulduar_saronite_animusAI(), boss_headless_horseman_head::boss_headless_horseman_headAI::Reset(), npc_twilight_summon::npc_twilight_summonAI::Reset(), boss_twilight_halion::boss_twilight_halionAI::Reset(), boss_yoggsaron_guardian_of_ys::boss_yoggsaron_guardian_of_ysAI::Reset(), boss_yoggsaron_crusher_tentacle::boss_yoggsaron_crusher_tentacleAI::Reset(), boss_yoggsaron_immortal_guardian::boss_yoggsaron_immortal_guardianAI::Reset(), instance_naxxramas::instance_naxxramas_InstanceMapScript::SetBossState(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::SetData(), npc_argent_captainAI::SpellHit(), spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript::StartAttack(), brann_bronzebeard::brann_bronzebeardAI::SummonCreatures(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::SummonedCreatureDies(), boss_shade_of_aran::boss_aranAI::UpdateAI(), boss_felmyst::boss_felmystAI::UpdateAI(), boss_kiljaeden::boss_kiljaedenAI::UpdateAI(), boss_entropius::boss_entropiusAI::UpdateAI(), npc_love_in_air_hummel::npc_love_in_air_hummelAI::UpdateAI(), boss_captain_skarloc::boss_captain_skarlocAI::UpdateAI(), boss_krik_thir::boss_krik_thirAI::UpdateAI(), boss_falric::boss_falricAI::UpdateAI(), boss_marwyn::boss_marwynAI::UpdateAI(), npc_phantom_hallucination::npc_phantom_hallucinationAI::UpdateAI(), npc_hor_lich_king::npc_hor_lich_kingAI::UpdateAI(), npc_vengeful_shade::npc_vengeful_shadeAI::UpdateAI(), npc_little_ooze::npc_little_oozeAI::UpdateAI(), npc_big_ooze::npc_big_oozeAI::UpdateAI(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::UpdateAI(), boss_sapphiron::boss_sapphironAI::UpdateAI(), boss_algalon_the_observer::boss_algalon_the_observerAI::UpdateAI(), boss_flame_leviathan::boss_flame_leviathanAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), boss_razorscale::boss_razorscaleAI::UpdateAI(), boss_ahune::boss_ahuneAI::UpdateAI(), and npc_onyx_flamecaller::npc_onyx_flamecallerAI::WaypointReached().
SetLastDamagedTime()
void Creature::SetLastDamagedTime (time_t val)
Definition at line 3427 of file Creature.cpp.
 {
     if (val > 0)
     {
         if (_lastDamagedTime)
             *_lastDamagedTime = val;
         else
             _lastDamagedTime = std::make_shared<time_t>(val);
     }
     else
         _lastDamagedTime.reset();
 }
References _lastDamagedTime.
Referenced by CreatureAI::_EnterEvadeMode(), Unit::DealDamage(), npc_pos_freed_slave::npc_pos_freed_slaveAI::EnterEvadeMode(), npc_pet_hunter_snake_trap::EnterEvadeMode(), and AssistDelayEvent::Execute().
SetLastDamagedTimePtr()
void Creature::SetLastDamagedTimePtr (std::shared_ptr< time_t > const & val)
Definition at line 3440 of file Creature.cpp.
 {
     _lastDamagedTime = val;
 }
References _lastDamagedTime.
Referenced by AssistDelayEvent::Execute().
SetLootMode()
void Creature::SetLootMode (uint16 lootMode) inline
Definition at line 227 of file Creature.h.
 { m_LootMode = lootMode; }
References m_LootMode.
Referenced by boss_yoggsaron::boss_yoggsaronAI::boss_yoggsaronAI(), boss_high_king_maulgar::boss_high_king_maulgarAI::DoAction(), boss_vezax::boss_vezaxAI::DoAction(), boss_xt002::boss_xt002AI::DoAction(), boss_sartharion_dragonAI::EnterCombat(), boss_priestess_delrissa::boss_priestess_delrissaAI::Reset(), boss_sacrolash::boss_sacrolashAI::Reset(), boss_alythess::boss_alythessAI::Reset(), boss_steelbreaker::boss_steelbreakerAI::Reset(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::Reset(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::Reset(), boss_vezax::boss_vezaxAI::Reset(), boss_skarvald_the_constructor::boss_skarvald_the_constructorAI::Reset(), boss_dalronn_the_controller::boss_dalronn_the_controllerAI::Reset(), boss_high_king_maulgar::boss_high_king_maulgarAI::Reset(), instance_violet_hold::instance_violet_hold_InstanceMapScript::StartBossEncounter(), and boss_priestess_delrissa::boss_priestess_delrissaAI::SummonedCreatureDies().
SetLootRecipient()
void Creature::SetLootRecipient (Unit * unit, bool withGroup = true)
Definition at line 1161 of file Creature.cpp.
 {
     // set the player whose group should receive the right
     // to loot the creature after it dies
     // should be set to nullptr after the loot disappears
     if (!unit)
     {
         m_lootRecipient.Clear();
         m_lootRecipientGroup = 0;
         RemoveFlag(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_LOOTABLE | UNIT_DYNFLAG_TAPPED);
         ResetAllowedLooters();
         return;
     }
     Player* player = unit->GetCharmerOrOwnerPlayerOrPlayerItself();
     if (!player)                                             // normal creature, no player involved
         return;
     m_lootRecipient = player->GetGUID();
     Map* map = GetMap();
     if (map && map->IsDungeon() && (isWorldBoss() || IsDungeonBoss()))
     {
         AddAllowedLooter(m_lootRecipient);
     }
     if (withGroup)
     {
         if (Group* group = player->GetGroup())
         {
             m_lootRecipientGroup = group->GetGUID().GetCounter();
             if (map && map->IsDungeon() && (isWorldBoss() || IsDungeonBoss()))
             {
                 Map::PlayerList const& PlayerList = map->GetPlayers();
                 for (Map::PlayerList::const_iterator i = PlayerList.begin(); i != PlayerList.end(); ++i)
                 {
                     if (Player* groupMember = i->GetSource())
                     {
                         if (groupMember->IsGameMaster() || groupMember->IsSpectator())
{
                             continue;
                         }
                         if (groupMember->GetGroup() == group)
{
                             AddAllowedLooter(groupMember->GetGUID());
                         }
                     }
                 }
             }
         }
     }
     else
         m_lootRecipientGroup = 0;
     SetFlag(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_TAPPED);
 }
References WorldObject::AddAllowedLooter(), MapRefMgr::begin(), ObjectGuid::Clear(), MapRefMgr::end(), Unit::GetCharmerOrOwnerPlayerOrPlayerItself(), Player::GetGroup(), Object::GetGUID(), WorldObject::GetMap(), Map::GetPlayers(), Map::IsDungeon(), IsDungeonBoss(), isWorldBoss(), m_lootRecipient, m_lootRecipientGroup, Object::RemoveFlag(), WorldObject::ResetAllowedLooters(), Object::SetFlag(), UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_LOOTABLE, and UNIT_DYNFLAG_TAPPED.
Referenced by CreatureAI::_EnterEvadeMode(), npc_heated_battle::npc_heated_battleAI::DamageTaken(), Unit::DealDamage(), boss_prince_keleseth_icc::boss_prince_kelesethAI::EnterCombat(), boss_prince_taldaram_icc::boss_prince_taldaramAI::EnterCombat(), boss_prince_valanar_icc::boss_prince_valanarAI::EnterCombat(), npc_escortAI::EnterEvadeMode(), FollowerAI::EnterEvadeMode(), boss_doomrel::boss_doomrelAI::EnterEvadeMode(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::EnterEvadeMode(), npc_varian_wrynn::npc_varian_wrynnAI::EnterEvadeMode(), npc_thrall_bfu::npc_thrall_bfuAI::EnterEvadeMode(), hyjalAI::EnterEvadeMode(), npc_pos_freed_slave::npc_pos_freed_slaveAI::EnterEvadeMode(), npc_pet_hunter_snake_trap::EnterEvadeMode(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::HealReceived(), Unit::Kill(), boss_urom::boss_uromAI::LeaveCombat(), npc_target_dummy::npc_target_dummyAI::Reset(), Player::SendLoot(), setDeathState(), and npc_target_dummy::npc_target_dummyAI::UpdateAI().
SetMeleeDamageSchool()
void Creature::SetMeleeDamageSchool (SpellSchools school) inline
Definition at line 154 of file Creature.h.
 { m_meleeDamageSchoolMask = SpellSchoolMask(1 << school); }
References m_meleeDamageSchoolMask.
Referenced by boss_amanitar::boss_amanitarAI::boss_amanitarAI(), Guardian::InitStatsForLevel(), setDeathState(), boss_hydross_the_unstable::boss_hydross_the_unstableAI::SetForm(), and UpdateEntry().
SetNoCallAssistance()
void Creature::SetNoCallAssistance (bool val) inline
Definition at line 252 of file Creature.h.
 { m_AlreadyCallAssistance = val; }
References m_AlreadyCallAssistance.
Referenced by CallAssistance(), AssistDelayEvent::Execute(), AssistanceMovementGenerator::Finalize(), boss_krik_thir::boss_krik_thirAI::JustSummoned(), npc_boss_gothik_minion::npc_boss_gothik_minionAI::Reset(), boss_kelthuzad_minion::boss_kelthuzad_minionAI::Reset(), and Update().
SetNoSearchAssistance()
void Creature::SetNoSearchAssistance (bool val) inline
Definition at line 253 of file Creature.h.
 { m_AlreadySearchedAssistance = val; }
References m_AlreadySearchedAssistance.
Referenced by DoFleeToGetAssistance(), and setDeathState().
SetObjectScale()
void Creature::SetObjectScale (float scale) override virtual
Reimplemented from Object.
Definition at line 3250 of file Creature.cpp.
 {
     Unit::SetObjectScale(scale);
     float combatReach = DEFAULT_WORLD_OBJECT_SIZE;
     if (CreatureModelInfo const* minfo = sObjectMgr->GetCreatureModelInfo(GetDisplayId()))
     {
         SetFloatValue(UNIT_FIELD_BOUNDINGRADIUS, (IsPet() ? 1.0f : minfo->bounding_radius) * scale);
         if (minfo->combat_reach > 0)
             combatReach = minfo->combat_reach;
     }
     if (IsPet())
         combatReach = DEFAULT_COMBAT_REACH;
     SetFloatValue(UNIT_FIELD_COMBATREACH, combatReach * scale);
 }
References DEFAULT_COMBAT_REACH, DEFAULT_WORLD_OBJECT_SIZE, Unit::GetDisplayId(), Unit::IsPet(), Object::SetFloatValue(), Object::SetObjectScale(), sObjectMgr, UNIT_FIELD_BOUNDINGRADIUS, and UNIT_FIELD_COMBATREACH.
Referenced by wp_commandscript::HandleWpShowCommand(), InitEntry(), Guardian::InitStatsForLevel(), npc_memory::npc_memoryAI::npc_memoryAI(), boss_freya_nature_bomb::boss_freya_nature_bombAI::Reset(), boss_sartharion::boss_sartharionAI::SendLavaWaves(), npc_soh_fire_trigger::npc_soh_fire_triggerAI::SpellHit(), npc_simon_bunny::npc_simon_bunnyAI::StartGame(), boss_thekal::boss_thekalAI::UpdateAI(), npc_memory::npc_memoryAI::UpdateAI(), and npc_frost_sphere::npc_frost_sphereAI::UpdateAI().
SetOriginalEntry()
void Creature::SetOriginalEntry (uint32 entry) inline
Definition at line 351 of file Creature.h.
 { m_originalEntry = entry; }
References m_originalEntry.
Referenced by CreateFromProto().
SetPickPocketLootTime()
void Creature::SetPickPocketLootTime () inline
Definition at line 219 of file Creature.h.
 { lootPickPocketRestoreTime = time(nullptr) + MINUTE + GetCorpseDelay() + GetRespawnTime(); }
References GetCorpseDelay(), GetRespawnTime(), lootPickPocketRestoreTime, and MINUTE.
Referenced by Player::SendLoot().
SetPosition() [1/2]
void Creature::SetPosition (const Position & pos) inline
Definition at line 314 of file Creature.h.
 { SetPosition(pos.GetPositionX(), pos.GetPositionY(), pos.GetPositionZ(), pos.GetOrientation()); }
References pos(), and SetPosition().
Referenced by SetPosition().
SetPosition() [2/2]
void Creature::SetPosition (float x, float y, float z, float o)
Definition at line 2854 of file Creature.cpp.
 {
     if (!Acore::IsValidMapCoord(x, y, z, o))
         return;
     GetMap()->CreatureRelocation(this, x, y, z, o);
 }
References Map::CreatureRelocation(), WorldObject::GetMap(), Acore::IsValidMapCoord(), G3D::x, G3D::y, and G3D::z.
Referenced by npc_power_spark::npc_power_sparkAI::DamageTaken(), DespawnOnEvade(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction(), boss_kelthuzad_minion::boss_kelthuzad_minionAI::DoAction(), Spell::EffectResurrectPet(), CastArmageddon::Execute(), npc_commandscript::HandleNpcMoveCommand(), npc_frost_wyrm::npc_frost_wyrmAI::JustDied(), npc_gargoyle::npc_gargoyleAI::JustDied(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::JustSummoned(), boss_kiljaeden::boss_kiljaedenAI::JustSummoned(), npc_escortAI::MovementInform(), SmartAI::MovepointReached(), npc_vortex_ride::npc_vortex_rideAI::npc_vortex_rideAI(), instance_pit_of_saron::instance_pit_of_saron_InstanceScript::OnCreatureCreate(), instance_ulduar::instance_ulduar_InstanceMapScript::OnCreatureCreate(), FrostwingGauntletRespawner::operator()(), ValithriaDespawner::operator()(), RemoveCorpse(), npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::Reset(), boss_four_horsemen::boss_four_horsemenAI::Reset(), boss_thaddius::boss_thaddiusAI::Reset(), npc_simone::npc_simoneAI::RespawnPet(), instance_naxxramas::instance_naxxramas_InstanceMapScript::SetBossState(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::SpawnAdds(), boss_twinemperorsAI::TeleportToMyBrother(), npc_highborne_lamenter::npc_highborne_lamenterAI::UpdateAI(), npc_claw_tentacle::claw_tentacleAI::UpdateAI(), npc_giant_claw_tentacle::giant_claw_tentacleAI::UpdateAI(), npc_oculus_drakegiver::npc_oculus_drakegiverAI::UpdateAI(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateAI(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::UpdateAI(), boss_alar::boss_alarAI::UpdateAI(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::UpdateAI(), and Unit::UpdateSplinePosition().
SetReactState()
void Creature::SetReactState (ReactStates st) inline
Definition at line 83 of file Creature.h.
 { m_reactState = st; }
References m_reactState.
Referenced by boss_halion::boss_halionAI::AttackStart(), boss_faction_championsAI::boss_faction_championsAI(), boss_felmyst::boss_felmystAI::boss_felmystAI(), boss_gormok::boss_gormokAI::boss_gormokAI(), boss_grand_champion::boss_grand_championAI::boss_grand_championAI(), boss_icehowl::boss_icehowlAI::boss_icehowlAI(), boss_jaraxxus::boss_jaraxxusAI::boss_jaraxxusAI(), boss_jormungarAI::boss_jormungarAI(), boss_kiljaeden::boss_kiljaedenAI::boss_kiljaedenAI(), boss_ragnaros::boss_ragnarosAI::boss_ragnarosAI(), boss_the_lich_king::boss_the_lich_kingAI::boss_the_lich_kingAI(), boss_twin_valkyrAI::boss_twin_valkyrAI(), boss_tyrannus::boss_tyrannusAI::boss_tyrannusAI(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::boss_valithria_dreamwalkerAI(), CharmInfo::CharmInfo(), boss_garfrost::boss_garfrostAI::DamageTaken(), boss_professor_putricide::boss_professor_putricideAI::DamageTaken(), socrethar::socretharAI::DamageTaken(), boss_taerar::boss_taerarAI::DamageTaken(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::DamageTaken(), boss_kiljaeden::boss_kiljaedenAI::DamageTaken(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::DamageTaken(), boss_grand_champion::boss_grand_championAI::DamageTaken(), npc_terenas_menethil::npc_terenas_menethilAI::DamageTaken(), npc_crystalline_frayer::npc_crystalline_frayerAI::DamageTaken(), boss_algalon_the_observer::boss_algalon_the_observerAI::DamageTaken(), boss_hodir::boss_hodirAI::DamageTaken(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::DamageTaken(), npc_ulduar_vx001::npc_ulduar_vx001AI::DamageTaken(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::DamageTaken(), npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI::DamageTaken(), boss_essence_of_suffering::boss_essence_of_sufferingAI::DamageTaken(), boss_essence_of_desire::boss_essence_of_desireAI::DamageTaken(), boss_alar::boss_alarAI::DamageTaken(), boss_the_lich_king::boss_the_lich_kingAI::DamageTaken(), boss_mal_ganis::boss_mal_ganisAI::DamageTaken(), npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::Deactivate(), boss_prince_keleseth_icc::boss_prince_kelesethAI::DoAction(), boss_prince_taldaram_icc::boss_prince_taldaramAI::DoAction(), boss_prince_valanar_icc::boss_prince_valanarAI::DoAction(), boss_algalon_the_observer::boss_algalon_the_observerAI::DoAction(), npc_living_constellation::npc_living_constellationAI::DoAction(), boss_broggok::boss_broggokAI::DoAction(), npc_living_mojo::npc_living_mojoAI::DoAction(), boss_essence_of_suffering::boss_essence_of_sufferingAI::DoAction(), boss_essence_of_desire::boss_essence_of_desireAI::DoAction(), boss_essence_of_anger::boss_essence_of_angerAI::DoAction(), boss_the_lurker_below::boss_the_lurker_belowAI::DoAction(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::DoAction(), boss_pathaleon_the_calculator::boss_pathaleon_the_calculatorAI::DoAction(), Spell::EffectSummonType(), boss_venoxis::boss_venoxisAI::EnterCombat(), boss_sister_svalna::boss_sister_svalnaAI::EnterCombat(), boss_prince_keleseth_icc::boss_prince_kelesethAI::EnterCombat(), boss_prince_taldaram_icc::boss_prince_taldaramAI::EnterCombat(), boss_prince_valanar_icc::boss_prince_valanarAI::EnterCombat(), boss_four_horsemen::boss_four_horsemenAI::EnterCombat(), boss_kelthuzad::boss_kelthuzadAI::EnterCombat(), boss_the_lich_king::boss_the_lich_kingAI::EnterEvadeMode(), RestoreAttack::Execute(), OrcMoveEvent::Execute(), RestoreFight::Execute(), UtherBatteredHiltEvent::Execute(), StartMovementEvent::Execute(), VileSpiritActivateEvent::Execute(), SACActivateEvent::Execute(), SACDeactivateEvent::Execute(), AssistanceDistractMovementGenerator::Finalize(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::FlyAway(), boss_volkhan::boss_volkhanAI::GoToAnvil(), Pet::HandleAsynchLoadFailed(), spell_mc_play_dead::spell_mc_play_dead_AuraScript::HandleEffectApply(), spell_uldaman_stoned::spell_uldaman_stoned_AuraScript::HandleEffectApply(), spell_gen_creature_permanent_feign_death::HandleEffectApply(), spell_mc_play_dead::spell_mc_play_dead_AuraScript::HandleEffectRemove(), spell_uldaman_stoned::spell_uldaman_stoned_AuraScript::HandleEffectRemove(), spell_gen_creature_permanent_feign_death::HandleEffectRemove(), npc_commandscript::HandleNpcTameCommand(), WorldSession::HandlePetActionHelper(), spell_item_draenic_pale_ale::HandleSummon(), Battlefield::HideNpc(), npc_scarlet_ghoul::npc_scarlet_ghoulAI::InitializeAI(), boss_eck::boss_eckAI::InitializeAI(), boss_prince_keleseth_icc::boss_prince_kelesethAI::InitializeAI(), boss_prince_taldaram_icc::boss_prince_taldaramAI::InitializeAI(), boss_prince_valanar_icc::boss_prince_valanarAI::InitializeAI(), boss_sapphiron::boss_sapphironAI::InitializeAI(), npc_lord_arete::npc_lord_areteAI::InitializeAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::InitializeAI(), boss_pathaleon_the_calculator::boss_pathaleon_the_calculatorAI::InitializeAI(), npc_pet_mage_mirror_image::InitializeAI(), InitializeReactState(), Minion::InitStats(), Guardian::InitStats(), Puppet::InitStats(), Guardian::InitStatsForLevel(), Totem::InitSummon(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::IsSummonedBy(), npc_lk_wicked_spirit::npc_lk_wicked_spiritAI::JustDied(), boss_the_lich_king::boss_the_lich_kingAI::JustReachedHome(), npc_lk_wicked_spirit::npc_lk_wicked_spiritAI::JustRespawned(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::JustSummoned(), boss_majordomo::boss_majordomoAI::JustSummoned(), boss_selin_fireheart::boss_selin_fireheartAI::JustSummoned(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::JustSummoned(), boss_novos::boss_novosAI::JustSummoned(), boss_bronjahm::boss_bronjahmAI::JustSummoned(), boss_drakkari_colossus::boss_drakkari_colossusAI::JustSummoned(), boss_prince_valanar_icc::boss_prince_valanarAI::JustSummoned(), boss_professor_putricide::boss_professor_putricideAI::JustSummoned(), boss_the_lich_king::boss_the_lich_kingAI::JustSummoned(), boss_illidan_stormrage::boss_illidan_stormrageAI::JustSummoned(), boss_reliquary_of_souls::boss_reliquary_of_soulsAI::JustSummoned(), npc_creature_generator_akama::npc_creature_generator_akamaAI::JustSummoned(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::JustSummoned(), boss_ick::boss_ickAI::KilledUnit(), boss_grand_champion::boss_grand_championAI::MovementInform(), boss_eck::boss_eckAI::MovementInform(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::MovementInform(), boss_sister_svalna::boss_sister_svalnaAI::MovementInform(), boss_four_horsemen::boss_four_horsemenAI::MovementInform(), boss_volkhan::boss_volkhanAI::MovementInform(), boss_sindragosa::boss_sindragosaAI::MovementInform(), npc_rimefang::npc_rimefangAI::MovementInform(), boss_kaelthas::boss_kaelthasAI::MovementInform(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::MovementInform(), gunship_npc_AI::MovementInform(), npc_gunship_boarding_addAI::MovementInform(), npc_ball_of_flame::npc_ball_of_flameAI::MovementInform(), boss_icehowl::boss_icehowlAI::MovementInform(), MotionMaster::MoveSeekAssistance(), npc_anubarak_spike::npc_anubarak_spikeAI::npc_anubarak_spikeAI(), npc_argent_soldier::npc_argent_soldierAI::npc_argent_soldierAI(), npc_concentrated_ball::npc_concentrated_ballAI::npc_concentrated_ballAI(), npc_dark_iron_guzzler::npc_dark_iron_guzzlerAI::npc_dark_iron_guzzlerAI(), npc_frost_freeze_trap::npc_frost_freeze_trapAI::npc_frost_freeze_trapAI(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::npc_grand_magister_rommathAI(), npc_icc_ice_sphere::npc_icc_ice_sphereAI::npc_icc_ice_sphereAI(), npc_ice_tomb::npc_ice_tombAI::npc_ice_tombAI(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::npc_koltira_deathweaverAI(), npc_living_constellation::npc_living_constellationAI::npc_living_constellationAI(), npc_lk_spirit_bomb::npc_lk_spirit_bombAI::npc_lk_spirit_bombAI(), npc_memory::npc_memoryAI::npc_memoryAI(), npc_nexus_lord::npc_nexus_lordAI::npc_nexus_lordAI(), npc_pet_gen_valkyr_guardian::npc_pet_gen_valkyr_guardian(), npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::npc_pilgrims_bounty_chairAI(), npc_putricide_oozeAI::npc_putricide_oozeAI(), npc_q24545_vegard::npc_q24545_vegardAI::npc_q24545_vegardAI(), npc_saurfang_event::npc_saurfang_eventAI::npc_saurfang_eventAI(), npc_scarlet_miner::npc_scarlet_minerAI::npc_scarlet_minerAI(), npc_scion_of_eternity::npc_scion_of_eternityAI::npc_scion_of_eternityAI(), npc_snobold_vassal::npc_snobold_vassalAI::npc_snobold_vassalAI(), npc_suppresser::npc_suppresserAI::npc_suppresserAI(), npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::npc_taldaram_flamesphereAI(), npc_the_lich_king_controller::npc_the_lich_king_controllerAI::npc_the_lich_king_controllerAI(), npc_ulduar_expedition_commander::npc_ulduar_expedition_commanderAI::npc_ulduar_expedition_commanderAI(), npc_ulduar_hodir_druid::npc_ulduar_hodir_druidAI::npc_ulduar_hodir_druidAI(), npc_ulduar_hodir_mage::npc_ulduar_hodir_mageAI::npc_ulduar_hodir_mageAI(), npc_ulduar_hodir_priest::npc_ulduar_hodir_priestAI::npc_ulduar_hodir_priestAI(), npc_ulduar_hodir_shaman::npc_ulduar_hodir_shamanAI::npc_ulduar_hodir_shamanAI(), npc_unworthy_initiate::npc_unworthy_initiateAI::npc_unworthy_initiateAI(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::npc_valkyr_shadowguardAI(), npc_zafod_boombox::npc_zafod_boomboxAI::npc_zafod_boomboxAI(), NullCreatureAI::NullCreatureAI(), spell_halion_twilight_phasing::spell_halion_twilight_phasing_AuraScript::OnApply(), instance_zulfarrak::instance_zulfarrak_InstanceMapScript::OnCreatureCreate(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::OnCreatureCreate(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::OnCreatureCreate(), spell_halion_twilight_phasing::spell_halion_twilight_phasing_AuraScript::OnRemove(), npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI::PassengerBoarded(), PassiveAI::PassiveAI(), PossessedAI::PossessedAI(), npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::PrepareEvent(), SmartScript::ProcessAction(), boss_vaelastrasz::boss_vaelAI::Reset(), boss_mr_smite::boss_mr_smiteAI::Reset(), boss_servant_quarters::boss_servant_quartersAI::Reset(), npc_crusade_persuaded::npc_crusade_persuadedAI::Reset(), boss_felmyst::boss_felmystAI::Reset(), boss_kalecgos::boss_kalecgosAI::Reset(), boss_muru::boss_muruAI::Reset(), boss_entropius::boss_entropiusAI::Reset(), boss_venoxis::boss_venoxisAI::Reset(), npc_brew_bubble::npc_brew_bubbleAI::Reset(), npc_hallows_end_soh::npc_hallows_end_sohAI::Reset(), npc_love_in_air_snivel::npc_love_in_air_snivelAI::Reset(), boss_onyxia::boss_onyxiaAI::Reset(), npc_belnistrasz::npc_belnistraszAI::Reset(), boss_eye_of_cthun::eye_of_cthunAI::Reset(), npc_death_ravager::npc_death_ravagerAI::Reset(), npc_murkdeep::npc_murkdeepAI::Reset(), npc_troll_volunteer::npc_troll_volunteerAI::Reset(), npc_enraged_panther::npc_enraged_pantherAI::Reset(), npc_amanitar_mushrooms::npc_amanitar_mushroomsAI::Reset(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::Reset(), boss_halion::boss_halionAI::Reset(), boss_twilight_halion::boss_twilight_halionAI::Reset(), boss_saviana_ragefire::boss_saviana_ragefireAI::Reset(), boss_eadric::boss_eadricAI::Reset(), boss_paletress::boss_paletressAI::Reset(), boss_black_knight::boss_black_knightAI::Reset(), npc_toc5_player_vehicle::npc_toc5_player_vehicleAI::Reset(), boss_grand_champion::boss_grand_championAI::Reset(), boss_devourer_of_souls::boss_devourer_of_soulsAI::Reset(), boss_garfrost::boss_garfrostAI::Reset(), boss_ick::boss_ickAI::Reset(), boss_prince_keleseth_icc::boss_prince_kelesethAI::Reset(), boss_prince_taldaram_icc::boss_prince_taldaramAI::Reset(), boss_prince_valanar_icc::boss_prince_valanarAI::Reset(), npc_dark_nucleus::npc_dark_nucleusAI::Reset(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::Reset(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::Reset(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::Reset(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::Reset(), boss_lord_marrowgar::Reset(), boss_professor_putricide::boss_professor_putricideAI::Reset(), boss_sindragosa::boss_sindragosaAI::Reset(), npc_spinestalker::npc_spinestalkerAI::Reset(), npc_rimefang::npc_rimefangAI::Reset(), npc_tirion_fordring_tft::npc_tirion_fordringAI::Reset(), npc_lk_wicked_spirit::npc_lk_wicked_spiritAI::Reset(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::Reset(), npc_crok_scourgebane::npc_crok_scourgebaneAI::Reset(), boss_sister_svalna::boss_sister_svalnaAI::Reset(), npc_impaling_spear::npc_impaling_spearAI::Reset(), boss_four_horsemen::boss_four_horsemenAI::Reset(), boss_gluth::boss_gluthAI::Reset(), boss_gothik::boss_gothikAI::Reset(), npc_boss_gothik_minion::npc_boss_gothik_minionAI::Reset(), boss_kelthuzad::boss_kelthuzadAI::Reset(), boss_noth::boss_nothAI::Reset(), boss_sapphiron::boss_sapphironAI::Reset(), npc_oculus_unstable_sphere::npc_oculus_unstable_sphereAI::Reset(), boss_volkhan::boss_volkhanAI::Reset(), brann_bronzebeard::brann_bronzebeardAI::Reset(), boss_algalon_the_observer::boss_algalon_the_observerAI::Reset(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::Reset(), npc_ulduar_iron_construct::npc_ulduar_iron_constructAI::Reset(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::Reset(), boss_thorim_sif::boss_thorim_sifAI::Reset(), npc_beryl_sorcerer::npc_beryl_sorcererAI::Reset(), npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI::Reset(), npc_venture_co_straggler::npc_venture_co_stragglerAI::Reset(), npc_akama_illidan::npc_akama_illidanAI::Reset(), boss_shade_of_akama::boss_shade_of_akamaAI::Reset(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::Reset(), boss_the_lurker_below::boss_the_lurker_belowAI::Reset(), boss_broggok::boss_broggokAI::Reset(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::Reset(), boss_vazruden_the_herald::boss_vazruden_the_heraldAI::Reset(), boss_magtheridon::boss_magtheridonAI::Reset(), boss_alar::boss_alarAI::Reset(), npc_ancestral_wolf::npc_ancestral_wolfAI::Reset(), socrethar::socretharAI::Reset(), npc_bessy::npc_bessyAI::Reset(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::Reset(), emerald_dragonAI::Reset(), Unit::SetCharmedBy(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::SetData(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::SetData(), gunship_npc_AI::SetData(), npc_gunship_boarding_addAI::SetData(), CreatureAI::SetGazeOn(), BfGraveyard::SetSpirit(), npc_akama_illidan::npc_akama_illidanAI::sGossipSelect(), Battlefield::ShowNpc(), npc_ulduar_iron_construct::npc_ulduar_iron_constructAI::SpellHit(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::SpellHit(), npc_ulduar_vx001::npc_ulduar_vx001AI::SpellHit(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::SpellHit(), npc_cult_fanatic::npc_cult_fanaticAI::SpellHit(), npc_cult_adherent::npc_cult_adherentAI::SpellHit(), npc_crusade_persuaded::npc_crusade_persuadedAI::SpellHit(), npc_venture_co_straggler::npc_venture_co_stragglerAI::SpellHit(), boss_garfrost::boss_garfrostAI::SpellHitTarget(), boss_devourer_of_souls::boss_devourer_of_soulsAI::SpellHitTarget(), boss_ick::boss_ickAI::SpellHitTarget(), boss_noth::boss_nothAI::StartBalconyPhase(), instance_violet_hold::instance_violet_hold_InstanceMapScript::StartBossEncounter(), boss_heigan::boss_heiganAI::StartFightPhase(), boss_noth::boss_nothAI::StartGroundPhase(), boss_victor_nefarius::boss_victor_nefariusAI::SummonedCreatureDies(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::SummonedCreatureDies(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::SummonedCreatureDies(), boss_ragnaros::boss_ragnarosAI::UpdateAI(), boss_mr_smite::boss_mr_smiteAI::UpdateAI(), boss_servant_quarters::boss_servant_quartersAI::UpdateAI(), npc_scarlet_ghoul::npc_scarlet_ghoulAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::UpdateAI(), boss_felmyst::boss_felmystAI::UpdateAI(), boss_kalecgos::boss_kalecgosAI::UpdateAI(), boss_kiljaeden::boss_kiljaedenAI::UpdateAI(), boss_entropius::boss_entropiusAI::UpdateAI(), boss_arlokk::boss_arlokkAI::UpdateAI(), npc_hallows_end_soh::npc_hallows_end_sohAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), boss_onyxia::boss_onyxiaAI::UpdateAI(), npc_belnistrasz::npc_belnistraszAI::UpdateAI(), boss_eye_of_cthun::eye_of_cthunAI::UpdateAI(), npc_murkdeep::npc_murkdeepAI::UpdateAI(), boss_halion::boss_halionAI::UpdateAI(), boss_saviana_ragefire::boss_saviana_ragefireAI::UpdateAI(), npc_memory::npc_memoryAI::UpdateAI(), boss_icehowl::boss_icehowlAI::UpdateAI(), boss_ick::boss_ickAI::UpdateAI(), boss_krick::boss_krickAI::UpdateAI(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::UpdateAI(), npc_cult_fanatic::npc_cult_fanaticAI::UpdateAI(), npc_cult_adherent::npc_cult_adherentAI::UpdateAI(), boss_lord_marrowgar::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), boss_sindragosa::boss_sindragosaAI::UpdateAI(), npc_rimefang::npc_rimefangAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), npc_terenas_menethil::npc_terenas_menethilAI::UpdateAI(), boss_gothik::boss_gothikAI::UpdateAI(), boss_kelthuzad::boss_kelthuzadAI::UpdateAI(), boss_sapphiron::boss_sapphironAI::UpdateAI(), boss_thaddius::boss_thaddiusAI::UpdateAI(), npc_crystalline_frayer::npc_crystalline_frayerAI::UpdateAI(), boss_algalon_the_observer::boss_algalon_the_observerAI::UpdateAI(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_lurgglbr::npc_lurgglbrAI::UpdateAI(), npc_q24545_vegard::npc_q24545_vegardAI::UpdateAI(), boss_shade_of_akama::boss_shade_of_akamaAI::UpdateAI(), boss_lady_vashj::boss_lady_vashjAI::UpdateAI(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::UpdateAI(), boss_the_lurker_below::boss_the_lurker_belowAI::UpdateAI(), boss_magtheridon::boss_magtheridonAI::UpdateAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::UpdateAI(), boss_alar::boss_alarAI::UpdateAI(), boss_kaelthas::boss_kaelthasAI::UpdateAI(), socrethar::socretharAI::UpdateAI(), boss_taerar::boss_taerarAI::UpdateAI(), CreatureAI::UpdateVictimWithGaze(), npc_akama_illidan::npc_akama_illidanAI::WaypointReached(), npc_arthas::npc_arthasAI::WaypointReached(), and npc_apothecary_hanes::npc_Apothecary_HanesAI::WaypointReached().
SetRegeneratingHealth()
void Creature::SetRegeneratingHealth (bool c) inline
Definition at line 298 of file Creature.h.
 { m_regenHealth = c; }
References mpq::c, and m_regenHealth.
Referenced by boss_yoggsaron_brain::boss_yoggsaron_brainAI::boss_yoggsaron_brainAI(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::DamageTaken(), boss_kiljaeden::boss_kiljaedenAI::DamageTaken(), boss_eadric::boss_eadricAI::DamageTaken(), boss_paletress::boss_paletressAI::DamageTaken(), boss_grand_champion::boss_grand_championAI::DamageTaken(), npc_crystalline_frayer::npc_crystalline_frayerAI::DamageTaken(), npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI::DamageTaken(), boss_mal_ganis::boss_mal_ganisAI::DamageTaken(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::DamageTaken(), npc_twilight_volunteer::npc_twilight_volunteerAI::DoAction(), boss_grand_champion::boss_grand_championAI::DoAction(), gunship_npc_AI::gunship_npc_AI(), boss_drakkari_colossus::boss_drakkari_colossusAI::JustSummoned(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::JustSummoned(), boss_grand_champion::boss_grand_championAI::MovementInform(), npc_wild_wyrm::npc_wild_wyrmAI::MovementInform(), npc_amanitar_mushrooms::npc_amanitar_mushroomsAI::npc_amanitar_mushroomsAI(), npc_gunship_boarding_addAI::npc_gunship_boarding_addAI(), npc_gunship::npc_gunshipAI::npc_gunshipAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::npc_high_overlord_saurfang_igbAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::npc_muradin_bronzebeard_igbAI(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::Reset(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::Reset(), npc_ulduar_vx001::npc_ulduar_vx001AI::Reset(), npc_blessed_banner::npc_blessed_bannerAI::Reset(), npc_wild_wyrm::npc_wild_wyrmAI::Reset(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::SetData(), boss_kalecgos::boss_kalecgosAI::UpdateAI(), npc_crystalline_frayer::npc_crystalline_frayerAI::UpdateAI(), and boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI().
SetRespawnDelay()
void Creature::SetRespawnDelay (uint32 delay) inline
Definition at line 282 of file Creature.h.
 { m_respawnDelay = delay; }
References m_respawnDelay.
Referenced by BattlegroundAV::AddAVCreature(), Battleground::AddCreature(), npc_the_scourge_cauldron::npc_the_scourge_cauldronAI::DoDie(), npc_commandscript::HandleNpcSetSpawnTimeCommand(), and ValithriaDespawner::operator()().
SetRespawnTime()
void Creature::SetRespawnTime (uint32 respawn) inline
Definition at line 277 of file Creature.h.
 { m_respawnTime = respawn ? time(nullptr) + respawn : 0; }
References m_respawnTime.
Referenced by npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::JustDied(), npc_medivh_bm::npc_medivh_bmAI::JustDied(), boss_prince_keleseth_icc::boss_prince_kelesethAI::JustDied(), boss_prince_taldaram_icc::boss_prince_taldaramAI::JustDied(), boss_prince_valanar_icc::boss_prince_valanarAI::JustDied(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::JustDied(), npc_simone::npc_simoneAI::JustDied(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::npc_highlord_darion_mograineAI(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::OnCreatureCreate(), FrostwingGauntletRespawner::operator()(), ValithriaDespawner::operator()(), npc_varian_wrynn::npc_varian_wrynnAI::Reset(), npc_jaina_proudmoore_bfu::npc_jaina_proudmoore_bfuAI::Reset(), npc_thrall_bfu::npc_thrall_bfuAI::Reset(), npc_lady_sylvanas_windrunner_bfu::npc_lady_sylvanas_windrunner_bfuAI::Reset(), and Update().
SetSwim()
bool Creature::SetSwim (bool enable) override virtual
Reimplemented from Unit.
Definition at line 2940 of file Creature.cpp.
 {
     if (!Unit::SetSwim(enable))
         return false;
     if (!movespline->Initialized())
         return true;
     WorldPacket data(enable ? SMSG_SPLINE_MOVE_START_SWIM : SMSG_SPLINE_MOVE_STOP_SWIM);
     data << GetPackGUID();
     SendMessageToSet(&data, true);
     return true;
 }
References Object::GetPackGUID(), Movement::MoveSpline::Initialized(), Unit::movespline, WorldObject::SendMessageToSet(), Unit::SetSwim(), SMSG_SPLINE_MOVE_START_SWIM, and SMSG_SPLINE_MOVE_STOP_SWIM.
Referenced by npc_depth_charge::npc_depth_chargeAI::Reset(), SmartAI::SetSwim(), npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI::UpdateAI(), and UpdateMovementFlags().
SetTarget()
void Creature::SetTarget (ObjectGuid guid = ObjectGuid::Empty) override virtual
Implements Unit.
Definition at line 3288 of file Creature.cpp.
 {
     if (!_focusSpell)
         SetGuidValue(UNIT_FIELD_TARGET, guid);
 }
References _focusSpell, Object::SetGuidValue(), and UNIT_FIELD_TARGET.
Referenced by boss_malygos::boss_malygosAI::AttackStart(), boss_garfrost::boss_garfrostAI::DamageTaken(), boss_kiljaeden::boss_kiljaedenAI::DamageTaken(), boss_eye_of_cthun::eye_of_cthunAI::DamageTaken(), ConfusedMovementGenerator< T >::DoFinalize(), boss_kelthuzad::boss_kelthuzadAI::EnterCombat(), RestoreAttack::Execute(), npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::HandleAnimation(), npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::HandleAnimation(), boss_illidan_stormrage::boss_illidan_stormrageAI::JustSummoned(), boss_essence_of_suffering::boss_essence_of_sufferingAI::MovementInform(), boss_essence_of_desire::boss_essence_of_desireAI::MovementInform(), boss_mr_smite::boss_mr_smiteAI::MovementInform(), boss_felmyst::boss_felmystAI::MovementInform(), boss_kaelthas::boss_kaelthasAI::MovementInform(), npc_arthas::OnGossipSelect(), npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::Reset(), setDeathState(), npc_harrison_jones::npc_harrison_jonesAI::SpellHit(), boss_razorscale::boss_razorscaleAI::SpellHit(), boss_garfrost::boss_garfrostAI::SpellHitTarget(), boss_mr_smite::boss_mr_smiteAI::UpdateAI(), npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::UpdateAI(), npc_madrigosa::npc_madrigosaAI::UpdateAI(), boss_felmyst::boss_felmystAI::UpdateAI(), boss_kiljaeden::boss_kiljaedenAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), boss_eye_of_cthun::eye_of_cthunAI::UpdateAI(), boss_cthun::cthunAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI(), boss_the_lurker_below::boss_the_lurker_belowAI::UpdateAI(), and boss_kaelthas::boss_kaelthasAI::UpdateAI().
SetTransportHomePosition() [1/2]
void Creature::SetTransportHomePosition (const Position & pos) inline
Definition at line 322 of file Creature.h.
 { m_transportHomePosition.Relocate(pos); }
References m_transportHomePosition, pos(), and Position::Relocate().
SetTransportHomePosition() [2/2]
void Creature::SetTransportHomePosition (float x, float y, float z, float o) inline
Definition at line 321 of file Creature.h.
 { m_transportHomePosition.Relocate(x, y, z, o); }
References m_transportHomePosition, Position::Relocate(), G3D::x, G3D::y, and G3D::z.
Referenced by MotionTransport::CreateNPCPassenger(), npc_gunship_boarding_addAI::MovementInform(), gunship_npc_AI::SetData(), and WaypointMovementGenerator< Creature >::StartMove().
SetWalk()
bool Creature::SetWalk (bool enable) override virtual
Reimplemented from Unit.
Definition at line 2880 of file Creature.cpp.
 {
     if (!Unit::SetWalk(enable))
         return false;
     WorldPacket data(enable ? SMSG_SPLINE_MOVE_SET_WALK_MODE : SMSG_SPLINE_MOVE_SET_RUN_MODE, 9);
     data << GetPackGUID();
     SendMessageToSet(&data, false);
     return true;
 }
References Object::GetPackGUID(), WorldObject::SendMessageToSet(), Unit::SetWalk(), SMSG_SPLINE_MOVE_SET_RUN_MODE, and SMSG_SPLINE_MOVE_SET_WALK_MODE.
Referenced by boss_the_lich_king::boss_the_lich_kingAI::DamageTaken(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::DestroyDoor(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction(), npc_saurfang_event::npc_saurfang_eventAI::DoAction(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::DoAction(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::DoAction(), npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI::DoAction(), npc_scarlet_miner_cart::npc_scarlet_miner_cartAI::DoAction(), WaypointMovementGenerator< Creature >::DoFinalize(), RandomMovementGenerator< T >::DoFinalize(), ChaseMovementGenerator< T >::DoInitialize(), UtherBatteredHiltEvent::Execute(), npc_lord_arete::npc_lord_areteAI::InitializeAI(), npc_lk_spirit_bomb::npc_lk_spirit_bombAI::IsSummonedBy(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::IsSummonedBy(), boss_lieutenant_drake::boss_lieutenant_drakeAI::JustReachedHome(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::JustReachedHome(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::JustRespawned(), npc_eris_hevenfire::npc_eris_hevenfireAI::JustSummoned(), npc_kalecgos_kj::npc_kalecgos_kjAI::JustSummoned(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::JustSummoned(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::JustSummoned(), npc_akama_shade::npc_akamaAI::JustSummoned(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::JustSummoned(), boss_lady_vashj::boss_lady_vashjAI::JustSummoned(), npc_rinji::npc_rinjiAI::JustSummoned(), npc_maghar_captive::npc_maghar_captiveAI::JustSummoned(), npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI::MovementInform(), boss_mandokir::boss_mandokirAI::MovementInform(), boss_captain_skarloc::boss_captain_skarlocAI::MovementInform(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::MovementInform(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::MovementInform(), npc_thassarian2::npc_thassarian2AI::MovementInform(), boss_kaelthas::boss_kaelthasAI::MovementInform(), npc_escortAI::MovementInform(), npc_marzon_silent_blade::npc_marzon_silent_bladeAI::npc_marzon_silent_bladeAI(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::npc_valkyr_shadowguardAI(), boss_nightbane::boss_nightbaneAI::Reset(), npc_janalai_hatcher::npc_janalai_hatcherAI::Reset(), boss_nalorakk::boss_nalorakkAI::Reset(), boss_arlokk::boss_arlokkAI::Reset(), npc_dark_iron_guzzler::npc_dark_iron_guzzlerAI::Reset(), npc_kinetic_bomb::npc_kinetic_bombAI::Reset(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::Reset(), npc_xt002_scrapbot::npc_xt002_scrapbotAI::Reset(), npc_injured_7th_legion_soldier::npc_injured_7th_legion_soldierAI::Reset(), npc_q24545_lich_king::npc_q24545_lich_kingAI::Reset(), npc_plaguehound_tracker::npc_plaguehound_trackerAI::Reset(), boss_shade_of_akama::boss_shade_of_akamaAI::Reset(), boss_kaelthas::boss_kaelthasAI::Reset(), SmartAI::ReturnToLastOOCPos(), npc_escortAI::ReturnToLastPoint(), npc_escortAI::SetRun(), SmartAI::SetRun(), npc_tirion_fordring_tft::npc_tirion_fordringAI::sGossipSelect(), npc_injured_patient::npc_injured_patientAI::SpellHit(), npc_escortAI::Start(), hyjalAI::SummonCreature(), boss_majordomo::boss_majordomoAI::UpdateAI(), npc_scarlet_courier::npc_scarlet_courierAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::UpdateAI(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::UpdateAI(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::UpdateAI(), boss_arlokk::boss_arlokkAI::UpdateAI(), npc_twilight_volunteer::npc_twilight_volunteerAI::UpdateAI(), npc_xerestrasza::npc_xerestraszaAI::UpdateAI(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::UpdateAI(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::UpdateAI(), npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI(), npc_oculus_drakegiver::npc_oculus_drakegiverAI::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_shandy_dalaran::npc_shandy_dalaranAI::UpdateAI(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::UpdateAI(), npc_crusade_recruit::npc_crusade_recruitAI::UpdateAI(), boss_shade_of_akama::boss_shade_of_akamaAI::UpdateAI(), npc_akama_shade::npc_akamaAI::UpdateAI(), boss_kaelthas::boss_kaelthasAI::UpdateAI(), npc_dragonmaw_peon::npc_dragonmaw_peonAI::UpdateAI(), npc_dream_fog::npc_dream_fogAI::UpdateAI(), npc_ranger_lilatha::npc_ranger_lilathaAI::WaypointReached(), npc_corporal_keeshan::npc_corporal_keeshanAI::WaypointReached(), npc_emily::npc_emilyAI::WaypointReached(), and npc_isla_starmane::npc_isla_starmaneAI::WaypointReached().
SetWanderDistance()
void Creature::SetWanderDistance (float dist) inline
Definition at line 285 of file Creature.h.
 { m_wanderDistance = dist; }
References m_wanderDistance.
Referenced by npc_commandscript::HandleNpcSetWanderDistanceCommand().
SetWaterWalking()
bool Creature::SetWaterWalking (bool enable, bool packetOnly = false) override virtual
movement counter
Reimplemented from Unit.
Definition at line 3032 of file Creature.cpp.
 {
     if (!packetOnly && !Unit::SetWaterWalking(enable))
         return false;
     if (m_movedByPlayer)
     {
         WorldPacket data(enable ? SMSG_MOVE_WATER_WALK : SMSG_MOVE_LAND_WALK, 12);
         data << GetPackGUID();
         data << uint32(0);
         m_movedByPlayer->ToPlayer()->SendDirectMessage(&data);
         data.Initialize(MSG_MOVE_WATER_WALK, 64);
         data << GetPackGUID();
         BuildMovementPacket(&data);
         m_movedByPlayer->ToPlayer()->SendMessageToSet(&data, false);
         return true;
     }
     if (!movespline->Initialized())
         return true;
     WorldPacket data(enable ? SMSG_SPLINE_MOVE_WATER_WALK : SMSG_SPLINE_MOVE_LAND_WALK, 9);
     data << GetPackGUID();
     SendMessageToSet(&data, true);
     return true;
 }
References Unit::BuildMovementPacket(), Object::GetPackGUID(), Movement::MoveSpline::Initialized(), Unit::m_movedByPlayer, Unit::movespline, MSG_MOVE_WATER_WALK, Player::SendDirectMessage(), WorldObject::SendMessageToSet(), Player::SendMessageToSet(), Unit::SetWaterWalking(), SMSG_MOVE_LAND_WALK, SMSG_MOVE_WATER_WALK, SMSG_SPLINE_MOVE_LAND_WALK, SMSG_SPLINE_MOVE_WATER_WALK, and Object::ToPlayer().
Update()
void Creature::Update (uint32 time) override virtual
Reimplemented from WorldObject.
Reimplemented in Totem, Puppet, TempSummon, and Pet.
Definition at line 553 of file Creature.cpp.
 {
     if (IsAIEnabled && TriggerJustRespawned)
     {
         TriggerJustRespawned = false;
         AI()->JustRespawned();
         if (m_vehicleKit)
             m_vehicleKit->Reset();
     }
     switch (m_deathState)
     {
         case JUST_RESPAWNED:
             // Must not be called, see Creature::setDeathState JUST_RESPAWNED -> ALIVE promoting.
             LOG_ERROR("entities.unit", "Creature (%s) in wrong state: JUST_RESPAWNED (4)", GetGUID().ToString().c_str());
             break;
         case JUST_DIED:
             // Must not be called, see Creature::setDeathState JUST_DIED -> CORPSE promoting.
             LOG_ERROR("entities.unit", "Creature (%s) in wrong state: JUST_DEAD (1)", GetGUID().ToString().c_str());
             break;
         case DEAD:
             {
                 time_t now = time(nullptr);
                 if (m_respawnTime <= now)
                 {
                     bool allowed = !IsAIEnabled || AI()->CanRespawn();     // First check if there are any scripts that object to us respawning
                     if (!allowed)                                               // Will be rechecked on next Update call
                         break;
                     ObjectGuid dbtableHighGuid = ObjectGuid::Create<HighGuid::Unit>(GetEntry(), m_spawnId);
                     time_t linkedRespawntime = GetMap()->GetLinkedRespawnTime(dbtableHighGuid);
                     if (!linkedRespawntime)             // Can respawn
                         Respawn();
                     else                                // the master is dead
                     {
                         ObjectGuid targetGuid = sObjectMgr->GetLinkedRespawnGuid(dbtableHighGuid);
                         if (targetGuid == dbtableHighGuid) // if linking self, never respawn (check delayed to next day)
                             SetRespawnTime(DAY);
                         else
                             m_respawnTime = (now > linkedRespawntime ? now : linkedRespawntime) + urand(5, MINUTE); // else copy time from master and add a little
                         SaveRespawnTime(); // also save to DB immediately
                     }
                 }
                 break;
             }
         case CORPSE:
             {
                 Unit::Update(diff);
                 // deathstate changed on spells update, prevent problems
                 if (m_deathState != CORPSE)
                     break;
                 if (m_groupLootTimer && lootingGroupLowGUID)
                 {
                     if (m_groupLootTimer <= diff)
                     {
                         Group* group = sGroupMgr->GetGroupByGUID(lootingGroupLowGUID);
                         if (group)
                             group->EndRoll(&loot, GetMap());
                         m_groupLootTimer = 0;
                         lootingGroupLowGUID = 0;
                     }
                     else m_groupLootTimer -= diff;
                 }
                 else if (m_corpseRemoveTime <= time(nullptr))
                 {
                     RemoveCorpse(false);
                     LOG_DEBUG("entities.unit", "Removing corpse... %u ", GetUInt32Value(OBJECT_FIELD_ENTRY));
                 }
                 break;
             }
         case ALIVE:
             {
                 Unit::Update(diff);
                 // creature can be dead after Unit::Update call
                 // CORPSE/DEAD state will processed at next tick (in other case death timer will be updated unexpectedly)
                 if (!IsAlive())
                     break;
                 // if creature is charmed, switch to charmed AI
                 if (NeedChangeAI)
                 {
                     UpdateCharmAI();
                     NeedChangeAI = false;
                     IsAIEnabled = true;
                     // xinef: update combat state, if npc is not in combat - return to spawn correctly by calling EnterEvadeMode
                     SelectVictim();
                 }
                 Unit* owner = GetCharmerOrOwner();
                 if (IsCharmed() && !IsWithinDistInMap(owner, GetMap()->GetVisibilityRange(), true, false))
                 {
                     RemoveCharmAuras();
                 }
                 if (Unit *victim = GetVictim())
                 {
                     // If we are closer than 50% of the combat reach we are going to reposition the victim
                     if (diff >= m_moveBackwardsMovementTime)
                     {
                         float MaxRange = GetCollisionRadius() + GetVictim()->GetCollisionRadius();
                         if (IsInDist(victim, MaxRange))
                             AI()->MoveBackwardsChecks();
                         m_moveBackwardsMovementTime = urand(MOVE_BACKWARDS_CHECK_INTERVAL, MOVE_BACKWARDS_CHECK_INTERVAL * 3);
                     }
                     else
                     {
                         m_moveBackwardsMovementTime -= diff;
                     }
                     // Circling the target
                     if (diff >= m_moveCircleMovementTime)
                     {
                         AI()->MoveCircleChecks();
                         m_moveCircleMovementTime = urand(MOVE_CIRCLE_CHECK_INTERVAL, MOVE_CIRCLE_CHECK_INTERVAL * 2);
                     }
                     else
                     {
                         m_moveCircleMovementTime -= diff;
                     }
                 }
                 // Call for assistance if not disabled
                 if (m_assistanceTimer)
                 {
                     if (m_assistanceTimer <= diff)
                     {
                         if (CanPeriodicallyCallForAssistance())
{
                             SetNoCallAssistance(false);
                             CallAssistance();
                         }
                         m_assistanceTimer = sWorld->getIntConfig(CONFIG_CREATURE_FAMILY_ASSISTANCE_PERIOD);
                     }
                     else
                     {
                         m_assistanceTimer -= diff;
                     }
                 }
                 if (!IsInEvadeMode() && IsAIEnabled)
                 {
                     // do not allow the AI to be changed during update
                     m_AI_locked = true;
                     i_AI->UpdateAI(diff);
                     m_AI_locked = false;
                 }
                 // creature can be dead after UpdateAI call
                 // CORPSE/DEAD state will processed at next tick (in other case death timer will be updated unexpectedly)
                 if (!IsAlive())
                     break;
                 m_regenTimer -= diff;
                 if (m_regenTimer <= 0)
                 {
                     if (!IsInEvadeMode())
                     {
                         // regenerate health if not in combat or if polymorphed)
                         if (!IsInCombat() || IsPolymorphed())
                             RegenerateHealth();
                         else if (IsNotReachableAndNeedRegen())
{
                             // regenerate health if cannot reach the target and the setting is set to do so.
                             // this allows to disable the health regen of raid bosses if pathfinding has issues for whatever reason
                             if (sWorld->getBoolConfig(CONFIG_REGEN_HP_CANNOT_REACH_TARGET_IN_RAID) || !GetMap()->IsRaid())
{
                                 RegenerateHealth();
                                 LOG_DEBUG("entities.unit", "RegenerateHealth() enabled because Creature cannot reach the target. Detail: %s", GetDebugInfo().c_str());
                             }
                             else
                                 LOG_DEBUG("entities.unit", "RegenerateHealth() disabled even if the Creature cannot reach the target. Detail: %s", GetDebugInfo().c_str());
                         }
                     }
                     if (getPowerType() == POWER_ENERGY)
                         Regenerate(POWER_ENERGY);
                     else
                         Regenerate(POWER_MANA);
                     m_regenTimer += CREATURE_REGEN_INTERVAL;
                 }
                 if (CanNotReachTarget() && !IsInEvadeMode() && !GetMap()->IsRaid())
                 {
                     m_cannotReachTimer += diff;
                     if (IsNotReachable() && IsAIEnabled)
                     {
                         AI()->EnterEvadeMode();
                     }
                 }
                 break;
             }
         default:
             break;
     }
     if (IsInWorld() && !IsDuringRemoveFromWorld())
     {
         // pussywizard:
         if (GetOwnerGUID().IsPlayer())
         {
             if (m_transportCheckTimer <= diff)
             {
                 m_transportCheckTimer = 1000;
                 Transport* newTransport = GetMap()->GetTransportForPos(GetPhaseMask(), GetPositionX(), GetPositionY(), GetPositionZ(), this);
                 if (newTransport != GetTransport())
                 {
                     if (GetTransport())
                         GetTransport()->RemovePassenger(this, true);
                     if (newTransport)
                         newTransport->AddPassenger(this, true);
                     this->StopMovingOnCurrentPos();
                     //SendMovementFlagUpdate();
                 }
             }
             else
                 m_transportCheckTimer -= diff;
         }
         sScriptMgr->OnCreatureUpdate(this, diff);
     }
 }
References Transport::AddPassenger(), AI(), ALIVE, CallAssistance(), CanNotReachTarget(), CanPeriodicallyCallForAssistance(), CreatureAI::CanRespawn(), CONFIG_CREATURE_FAMILY_ASSISTANCE_PERIOD, CONFIG_REGEN_HP_CANNOT_REACH_TARGET_IN_RAID, CORPSE, CREATURE_REGEN_INTERVAL, DAY, DEAD, diff(), Group::EndRoll(), CreatureAI::EnterEvadeMode(), Unit::GetCharmerOrOwner(), Unit::GetCollisionRadius(), GetDebugInfo(), Object::GetEntry(), Object::GetGUID(), Map::GetLinkedRespawnTime(), WorldObject::GetMap(), Unit::GetOwnerGUID(), WorldObject::GetPhaseMask(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::getPowerType(), WorldObject::GetTransport(), Map::GetTransportForPos(), Object::GetUInt32Value(), Unit::GetVictim(), WorldObject::GetVisibilityRange(), Unit::i_AI, Unit::IsAIEnabled, Unit::IsAlive(), Unit::IsCharmed(), Unit::IsDuringRemoveFromWorld(), Unit::IsInCombat(), Position::IsInDist(), IsInEvadeMode(), Object::IsInWorld(), IsNotReachable(), IsNotReachableAndNeedRegen(), Object::IsPlayer(), Unit::IsPolymorphed(), WorldObject::IsWithinDistInMap(), JUST_DIED, JUST_RESPAWNED, CreatureAI::JustRespawned(), LOG_DEBUG, LOG_ERROR, loot, lootingGroupLowGUID, m_AI_locked, m_assistanceTimer, m_cannotReachTimer, m_corpseRemoveTime, Unit::m_deathState, m_groupLootTimer, m_moveBackwardsMovementTime, m_moveCircleMovementTime, Unit::m_regenTimer, m_respawnTime, m_spawnId, m_transportCheckTimer, Unit::m_vehicleKit, MINUTE, MOVE_BACKWARDS_CHECK_INTERVAL, MOVE_CIRCLE_CHECK_INTERVAL, CreatureAI::MoveBackwardsChecks(), CreatureAI::MoveCircleChecks(), Unit::NeedChangeAI, OBJECT_FIELD_ENTRY, POWER_ENERGY, POWER_MANA, Regenerate(), RegenerateHealth(), Unit::RemoveCharmAuras(), RemoveCorpse(), Transport::RemovePassenger(), Vehicle::Reset(), Respawn(), SaveRespawnTime(), SelectVictim(), SetNoCallAssistance(), SetRespawnTime(), sGroupMgr, sObjectMgr, sScriptMgr, Unit::StopMovingOnCurrentPos(), sWorld, Position::ToString(), TriggerJustRespawned, Unit::Update(), UnitAI::UpdateAI(), Unit::UpdateCharmAI(), and urand().
Referenced by Pet::Update(), TempSummon::Update(), and Totem::Update().
UpdateAllStats()
bool Creature::UpdateAllStats () override virtual
Implements Unit.
Reimplemented in Totem, and Guardian.
Definition at line 977 of file StatSystem.cpp.
 {
     UpdateMaxHealth();
     UpdateAttackPowerAndDamage();
     UpdateAttackPowerAndDamage(true);
     for (uint8 i = POWER_MANA; i < MAX_POWERS; ++i)
         UpdateMaxPower(Powers(i));
     UpdateAllResistances();
     return true;
 }
References MAX_POWERS, POWER_MANA, Unit::UpdateAllResistances(), UpdateAttackPowerAndDamage(), UpdateMaxHealth(), and UpdateMaxPower().
Referenced by UpdateEntry().
UpdateArmor()
void Creature::UpdateArmor () override virtual
Implements Unit.
Reimplemented in Totem, and Guardian.
Definition at line 1002 of file StatSystem.cpp.
 {
     float value = GetTotalAuraModValue(UNIT_MOD_ARMOR);
     SetArmor(int32(value));
 }
References Unit::GetTotalAuraModValue(), Unit::SetArmor(), and UNIT_MOD_ARMOR.
Referenced by UpdateResistances().
UpdateAttackPowerAndDamage()
void Creature::UpdateAttackPowerAndDamage (bool ranged = false) override virtual
Implements Unit.
Reimplemented in Totem, and Guardian.
Definition at line 1022 of file StatSystem.cpp.
 {
     UnitMods unitMod = ranged ? UNIT_MOD_ATTACK_POWER_RANGED : UNIT_MOD_ATTACK_POWER;
     uint16 index = UNIT_FIELD_ATTACK_POWER;
     uint16 indexMod = UNIT_FIELD_ATTACK_POWER_MODS;
     uint16 indexMulti = UNIT_FIELD_ATTACK_POWER_MULTIPLIER;
     if (ranged)
     {
         index = UNIT_FIELD_RANGED_ATTACK_POWER;
         indexMod = UNIT_FIELD_RANGED_ATTACK_POWER_MODS;
         indexMulti = UNIT_FIELD_RANGED_ATTACK_POWER_MULTIPLIER;
     }
     float baseAttackPower       = GetModifierValue(unitMod, BASE_VALUE) * GetModifierValue(unitMod, BASE_PCT);
     float attackPowerMod        = GetModifierValue(unitMod, TOTAL_VALUE);
     float attackPowerMultiplier = GetModifierValue(unitMod, TOTAL_PCT) - 1.0f;
     SetInt32Value(index, uint32(baseAttackPower));      // UNIT_FIELD_(RANGED)_ATTACK_POWER
     SetInt32Value(indexMod, uint32(attackPowerMod));    // UNIT_FIELD_(RANGED)_ATTACK_POWER_MODS
     SetFloatValue(indexMulti, attackPowerMultiplier);   // UNIT_FIELD_(RANGED)_ATTACK_POWER_MULTIPLIER
     // automatically update weapon damage after attack power modification
     if (ranged)
         UpdateDamagePhysical(RANGED_ATTACK);
     else
     {
         UpdateDamagePhysical(BASE_ATTACK);
         UpdateDamagePhysical(OFF_ATTACK);
     }
 }
References BASE_ATTACK, BASE_PCT, BASE_VALUE, Unit::GetModifierValue(), index, OFF_ATTACK, RANGED_ATTACK, Object::SetFloatValue(), Object::SetInt32Value(), TOTAL_PCT, TOTAL_VALUE, UNIT_FIELD_ATTACK_POWER, UNIT_FIELD_ATTACK_POWER_MODS, UNIT_FIELD_ATTACK_POWER_MULTIPLIER, UNIT_FIELD_RANGED_ATTACK_POWER, UNIT_FIELD_RANGED_ATTACK_POWER_MODS, UNIT_FIELD_RANGED_ATTACK_POWER_MULTIPLIER, UNIT_MOD_ATTACK_POWER, UNIT_MOD_ATTACK_POWER_RANGED, and Unit::UpdateDamagePhysical().
Referenced by UpdateAllStats().
UpdateEntry()
bool Creature::UpdateEntry (uint32 entry, const CreatureData * data = nullptr, bool changelevel = true)
Definition at line 441 of file Creature.cpp.
 {
     if (!InitEntry(Entry, data))
         return false;
     CreatureTemplate const* cInfo = GetCreatureTemplate();
     m_regenHealth = cInfo->RegenHealth;
     // creatures always have melee weapon ready if any unless specified otherwise
     if (!GetCreatureAddon())
         SetSheath(SHEATH_STATE_MELEE);
     SetFaction(cInfo->faction);
     uint32 npcflag, unit_flags, dynamicflags;
     ObjectMgr::ChooseCreatureFlags(cInfo, npcflag, unit_flags, dynamicflags, data);
     if (cInfo->flags_extra & CREATURE_FLAG_EXTRA_WORLDEVENT)
         SetUInt32Value(UNIT_NPC_FLAGS, npcflag | sGameEventMgr->GetNPCFlag(this));
     else
         SetUInt32Value(UNIT_NPC_FLAGS, npcflag);
     // Xinef: NPC is in combat, keep this flag!
     unit_flags &= ~UNIT_FLAG_IN_COMBAT;
     if (IsInCombat())
         unit_flags |= UNIT_FLAG_IN_COMBAT;
     SetUInt32Value(UNIT_FIELD_FLAGS, unit_flags);
     SetUInt32Value(UNIT_FIELD_FLAGS_2, cInfo->unit_flags2);
     SetUInt32Value(UNIT_DYNAMIC_FLAGS, dynamicflags);
     SetAttackTime(BASE_ATTACK,   cInfo->BaseAttackTime);
     SetAttackTime(OFF_ATTACK,    cInfo->BaseAttackTime);
     SetAttackTime(RANGED_ATTACK, cInfo->RangeAttackTime);
     uint32 previousHealth = GetHealth();
     uint32 previousMaxHealth = GetMaxHealth();
     uint32 previousPlayerDamageReq = m_PlayerDamageReq;
     SelectLevel(changelevel);
     if (previousHealth > 0)
     {
         SetHealth(previousHealth);
         if (previousMaxHealth && previousMaxHealth > GetMaxHealth())
         {
             m_PlayerDamageReq = (uint32)(previousPlayerDamageReq * GetMaxHealth() / previousMaxHealth);
         }
         else
         {
             m_PlayerDamageReq = previousPlayerDamageReq;
         }
     }
     SetMeleeDamageSchool(SpellSchools(cInfo->dmgschool));
     CreatureBaseStats const* stats = sObjectMgr->GetCreatureBaseStats(getLevel(), cInfo->unit_class);
     float armor = (float)stats->GenerateArmor(cInfo); // TODO: Why is this treated as uint32 when it's a float?
     SetModifierValue(UNIT_MOD_ARMOR,             BASE_VALUE, armor);
     SetModifierValue(UNIT_MOD_RESISTANCE_HOLY,   BASE_VALUE, float(cInfo->resistance[SPELL_SCHOOL_HOLY]));
     SetModifierValue(UNIT_MOD_RESISTANCE_FIRE,   BASE_VALUE, float(cInfo->resistance[SPELL_SCHOOL_FIRE]));
     SetModifierValue(UNIT_MOD_RESISTANCE_NATURE, BASE_VALUE, float(cInfo->resistance[SPELL_SCHOOL_NATURE]));
     SetModifierValue(UNIT_MOD_RESISTANCE_FROST,  BASE_VALUE, float(cInfo->resistance[SPELL_SCHOOL_FROST]));
     SetModifierValue(UNIT_MOD_RESISTANCE_SHADOW, BASE_VALUE, float(cInfo->resistance[SPELL_SCHOOL_SHADOW]));
     SetModifierValue(UNIT_MOD_RESISTANCE_ARCANE, BASE_VALUE, float(cInfo->resistance[SPELL_SCHOOL_ARCANE]));
     SetCanModifyStats(true);
     UpdateAllStats();
     // checked and error show at loading templates
     if (FactionTemplateEntry const* factionTemplate = sFactionTemplateStore.LookupEntry(cInfo->faction))
     {
         if (factionTemplate->factionFlags & FACTION_TEMPLATE_FLAG_ASSIST_PLAYERS)
             SetPvP(true);
         else
             SetPvP(false);
     }
     // updates spell bars for vehicles and set player's faction - should be called here, to overwrite faction that is set from the new template
     if (IsVehicle())
     {
         if (Player* owner = Creature::GetCharmerOrOwnerPlayerOrPlayerItself()) // this check comes in case we don't have a player
         {
             SetFaction(owner->GetFaction()); // vehicles should have same as owner faction
             owner->VehicleSpellInitialize();
         }
     }
     // trigger creature is always not selectable and can not be attacked
     if (IsTrigger())
         SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
     InitializeReactState();
     if (!IsPet() && cInfo->flags_extra & CREATURE_FLAG_EXTRA_NO_TAUNT)
     {
         ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_MOD_TAUNT, true);
         ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_ATTACK_ME, true);
     }
     if (cInfo->InhabitType & INHABIT_ROOT)
     {
         SetControlled(true, UNIT_STATE_ROOT);
     }
     SetDetectionDistance(cInfo->detection_range);
     LoadSpellTemplateImmunity();
     return true;
 }
References Unit::ApplySpellImmune(), BASE_ATTACK, BASE_VALUE, CreatureTemplate::BaseAttackTime, ObjectMgr::ChooseCreatureFlags(), CREATURE_FLAG_EXTRA_NO_TAUNT, CREATURE_FLAG_EXTRA_WORLDEVENT, CreatureTemplate::detection_range, CreatureTemplate::dmgschool, Entry, CreatureTemplate::faction, FACTION_TEMPLATE_FLAG_ASSIST_PLAYERS, CreatureTemplate::flags_extra, CreatureBaseStats::GenerateArmor(), Unit::GetCharmerOrOwnerPlayerOrPlayerItself(), GetCreatureAddon(), GetCreatureTemplate(), Unit::GetHealth(), Unit::getLevel(), Unit::GetMaxHealth(), IMMUNITY_EFFECT, IMMUNITY_STATE, INHABIT_ROOT, CreatureTemplate::InhabitType, InitEntry(), InitializeReactState(), Unit::IsInCombat(), Unit::IsPet(), IsTrigger(), Unit::IsVehicle(), LoadSpellTemplateImmunity(), m_PlayerDamageReq, m_regenHealth, OFF_ATTACK, CreatureTemplate::RangeAttackTime, RANGED_ATTACK, CreatureTemplate::RegenHealth, CreatureTemplate::resistance, SelectLevel(), Unit::SetAttackTime(), Unit::SetCanModifyStats(), Unit::SetControlled(), SetDetectionDistance(), Unit::SetFaction(), Object::SetFlag(), Unit::SetHealth(), SetMeleeDamageSchool(), Unit::SetModifierValue(), Unit::SetPvP(), Unit::SetSheath(), Object::SetUInt32Value(), sFactionTemplateStore, sGameEventMgr, SHEATH_STATE_MELEE, sObjectMgr, SPELL_AURA_MOD_TAUNT, SPELL_EFFECT_ATTACK_ME, SPELL_SCHOOL_ARCANE, SPELL_SCHOOL_FIRE, SPELL_SCHOOL_FROST, SPELL_SCHOOL_HOLY, SPELL_SCHOOL_NATURE, SPELL_SCHOOL_SHADOW, CreatureTemplate::unit_class, UNIT_DYNAMIC_FLAGS, UNIT_FIELD_FLAGS, UNIT_FIELD_FLAGS_2, UNIT_FLAG_IN_COMBAT, UNIT_FLAG_NOT_SELECTABLE, CreatureTemplate::unit_flags2, UNIT_MOD_ARMOR, UNIT_MOD_RESISTANCE_ARCANE, UNIT_MOD_RESISTANCE_FIRE, UNIT_MOD_RESISTANCE_FROST, UNIT_MOD_RESISTANCE_HOLY, UNIT_MOD_RESISTANCE_NATURE, UNIT_MOD_RESISTANCE_SHADOW, UNIT_NPC_FLAGS, UNIT_STATE_ROOT, and UpdateAllStats().
Referenced by CreateFromProto(), boss_yoggsaron_influence_tentacle::boss_yoggsaron_influence_tentacleAI::DamageTaken(), npc_molten_golem::npc_molten_golemAI::DamageTaken(), npc_forest_frog::npc_forest_frogAI::DoSpawnRandom(), npc_commandscript::HandleNpcSetEntryCommand(), npc_isle_of_conquest_turret::npc_isle_of_conquest_turretAI::JustDied(), npc_scholomance_occultist::npc_scholomance_occultistAI::JustReachedHome(), npc_aged_dying_ancient_kodo::npc_aged_dying_ancient_kodoAI::JustRespawned(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::JustSummoned(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::OnCreatureCreate(), instance_forge_of_souls::instance_forge_of_souls_InstanceScript::OnCreatureCreate(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::OnCreatureCreate(), instance_pit_of_saron::instance_pit_of_saron_InstanceScript::OnCreatureCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), instance_nexus::instance_nexus_InstanceMapScript::OnCreatureCreate(), instance_shattered_halls::instance_shattered_halls_InstanceMapScript::OnCreatureCreate(), npc_announcer_toc5::npc_announcer_toc5AI::Reset(), npc_phase_hunter::npc_phase_hunterAI::Reset(), Respawn(), NPCStaveQuestAI::RevealForm(), npc_time_lost_proto_drake::npc_time_lost_proto_drakeAI::RollPath(), npc_cult_fanatic::npc_cult_fanaticAI::SpellHit(), npc_cult_adherent::npc_cult_adherentAI::SpellHit(), npc_argent_captainAI::SpellHit(), npc_isle_of_conquest_turret::npc_isle_of_conquest_turretAI::SpellHit(), npc_nether_drake::npc_nether_drakeAI::SpellHit(), npc_aged_dying_ancient_kodo::npc_aged_dying_ancient_kodoAI::SpellHit(), boss_victor_nefarius::boss_victor_nefariusAI::SummonedCreatureDies(), npc_scholomance_occultist::npc_scholomance_occultistAI::UpdateAI(), npc_cult_fanatic::npc_cult_fanaticAI::UpdateAI(), npc_cult_adherent::npc_cult_adherentAI::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), npc_phase_hunter::npc_phase_hunterAI::UpdateAI(), and npc_tyrion_spybot::npc_tyrion_spybotAI::UpdateAI().
UpdateMaxHealth()
void Creature::UpdateMaxHealth () override virtual
Implements Unit.
Reimplemented in Totem, and Guardian.
Definition at line 1008 of file StatSystem.cpp.
 {
     float value = GetTotalAuraModValue(UNIT_MOD_HEALTH);
     SetMaxHealth(uint32(value));
 }
References Unit::GetTotalAuraModValue(), Unit::SetMaxHealth(), and UNIT_MOD_HEALTH.
Referenced by UpdateAllStats().
UpdateMaxPower()
void Creature::UpdateMaxPower (Powers power) override virtual
Implements Unit.
Reimplemented in Totem, and Guardian.
Definition at line 1014 of file StatSystem.cpp.
 {
     UnitMods unitMod = UnitMods(static_cast<uint16>(UNIT_MOD_POWER_START) + power);
     float value  = GetTotalAuraModValue(unitMod);
     SetMaxPower(power, uint32(value));
 }
References Unit::GetTotalAuraModValue(), Unit::SetMaxPower(), and UNIT_MOD_POWER_START.
Referenced by UpdateAllStats().
UpdateMoveInLineOfSightState()
void Creature::UpdateMoveInLineOfSightState ()
Definition at line 2350 of file Creature.cpp.
 {
     // xinef: pets, guardians and units with scripts / smartAI should be skipped
     if (IsPet() || HasUnitTypeMask(UNIT_MASK_MINION | UNIT_MASK_SUMMON | UNIT_MASK_GUARDIAN | UNIT_MASK_CONTROLABLE_GUARDIAN) ||
             GetScriptId() || GetAIName() == "SmartAI")
     {
         m_moveInLineOfSightStrictlyDisabled = false;
         m_moveInLineOfSightDisabled = false;
         return;
     }
     if (IsTrigger() || IsCivilian() || GetCreatureType() == CREATURE_TYPE_NON_COMBAT_PET || IsCritter() || GetAIName() == "NullCreatureAI")
     {
         m_moveInLineOfSightDisabled = true;
         m_moveInLineOfSightStrictlyDisabled = true;
         return;
     }
     bool nonHostile = true;
     if (FactionTemplateEntry const* factionTemplate = sFactionTemplateStore.LookupEntry(GetFaction()))
         if (factionTemplate->hostileMask || factionTemplate->enemyFaction[0] || factionTemplate->enemyFaction[1] || factionTemplate->enemyFaction[2] || factionTemplate->enemyFaction[3])
             nonHostile = false;
     if (nonHostile)
         m_moveInLineOfSightDisabled = true;
     else
         m_moveInLineOfSightDisabled = false;
 }
References CREATURE_TYPE_NON_COMBAT_PET, GetAIName(), Unit::GetCreatureType(), Unit::GetFaction(), GetScriptId(), Unit::HasUnitTypeMask(), IsCivilian(), Unit::IsCritter(), Unit::IsPet(), IsTrigger(), m_moveInLineOfSightDisabled, m_moveInLineOfSightStrictlyDisabled, sFactionTemplateStore, UNIT_MASK_CONTROLABLE_GUARDIAN, UNIT_MASK_GUARDIAN, UNIT_MASK_MINION, and UNIT_MASK_SUMMON.
Referenced by Unit::SetFaction().
UpdateMovementFlags()
void Creature::UpdateMovementFlags ()
Definition at line 3164 of file Creature.cpp.
 {
     // Do not update movement flags if creature is controlled by a player (charm/vehicle)
     if (m_movedByPlayer)
         return;
     CreatureTemplate const* info = GetCreatureTemplate();
     if (!info)
         return;
     // Creatures with CREATURE_FLAG_EXTRA_NO_MOVE_FLAGS_UPDATE should control MovementFlags in your own scripts
     if (info->flags_extra & CREATURE_FLAG_EXTRA_NO_MOVE_FLAGS_UPDATE)
         return;
     float z = GetPositionZ();
     float ground = GetFloorZ();
     bool isInAir = false;
     bool Swim = false;
     bool canHover = CanHover();
     LiquidData const& liquidData = GetLiquidData();
     if (liquidData.Status == LIQUID_MAP_NO_WATER)
     {
         if (ground > INVALID_HEIGHT)
             isInAir = G3D::fuzzyGt(z, ground + (canHover ? GetFloatValue(UNIT_FIELD_HOVERHEIGHT) : 0.0f) + GROUND_HEIGHT_TOLERANCE) || G3D::fuzzyLt(z, ground - GROUND_HEIGHT_TOLERANCE); // Can be underground too, prevent the falling
         else
             isInAir = true;
     }
     else
     {
         switch (liquidData.Status)
         {
             case LIQUID_MAP_ABOVE_WATER:
                 isInAir = true;
                 break;
             case LIQUID_MAP_WATER_WALK:
                 isInAir = true;
                 [[fallthrough]];
             case LIQUID_MAP_IN_WATER:
                 Swim = z - liquidData.DepthLevel > GetCollisionHeight() * 0.75f; // Shallow water at ~75% of collision height
                 break;
             case LIQUID_MAP_UNDER_WATER:
                 Swim = true;
                 break;
             default:
                 break;
         }
     }
     SetSwim(CanSwim() && Swim);
     if (info->InhabitType & INHABIT_AIR)
     {
         if (isInAir && !IsFalling())
         {
             if (info->InhabitType & INHABIT_GROUND)
             {
                 SetCanFly(true);
                 SetByteValue(UNIT_FIELD_BYTES_1, UNIT_BYTES_1_OFFSET_ANIM_TIER, UNIT_BYTE1_FLAG_FLY);
             }
             else
                 SetDisableGravity(true);
             if (!HasAuraType(SPELL_AURA_HOVER))
                 SetHover(false);
         }
         else
         {
             SetCanFly(false);
             SetDisableGravity(false);
             if (info->InhabitType & INHABIT_GROUND)
             {
                 SetByteValue(UNIT_FIELD_BYTES_1, UNIT_BYTES_1_OFFSET_ANIM_TIER, UNIT_BYTE1_FLAG_GROUND);
             }
             if (IsAlive() && (CanHover() || HasAuraType(SPELL_AURA_HOVER)))
                 SetHover(true);
         }
     }
     else if (!HasUnitMovementFlag(MOVEMENTFLAG_CAN_FLY | MOVEMENTFLAG_DISABLE_GRAVITY) && IsAlive() && (CanHover() || HasAuraType(SPELL_AURA_HOVER)))
         SetHover(true);
 }
References CanHover(), CanSwim(), CREATURE_FLAG_EXTRA_NO_MOVE_FLAGS_UPDATE, LiquidData::DepthLevel, CreatureTemplate::flags_extra, G3D::fuzzyGt(), G3D::fuzzyLt(), Unit::GetCollisionHeight(), GetCreatureTemplate(), Object::GetFloatValue(), WorldObject::GetFloorZ(), WorldObject::GetLiquidData(), Position::GetPositionZ(), GROUND_HEIGHT_TOLERANCE, Unit::HasAuraType(), Unit::HasUnitMovementFlag(), INHABIT_AIR, INHABIT_GROUND, CreatureTemplate::InhabitType, INVALID_HEIGHT, Unit::IsAlive(), Unit::IsFalling(), LIQUID_MAP_ABOVE_WATER, LIQUID_MAP_IN_WATER, LIQUID_MAP_NO_WATER, LIQUID_MAP_UNDER_WATER, LIQUID_MAP_WATER_WALK, Unit::m_movedByPlayer, MOVEMENTFLAG_CAN_FLY, MOVEMENTFLAG_DISABLE_GRAVITY, Object::SetByteValue(), SetCanFly(), SetDisableGravity(), SetHover(), SetSwim(), SPELL_AURA_HOVER, LiquidData::Status, UNIT_BYTE1_FLAG_FLY, UNIT_BYTE1_FLAG_GROUND, UNIT_BYTES_1_OFFSET_ANIM_TIER, UNIT_FIELD_BYTES_1, UNIT_FIELD_HOVERHEIGHT, and G3D::z.
Referenced by Create(), Unit::ProcessTerrainStatusUpdate(), RespawnOnEvade(), and setDeathState().
UpdateResistances()
void Creature::UpdateResistances (uint32 school) override virtual
Implements Unit.
Reimplemented in Totem.
Definition at line 991 of file StatSystem.cpp.
 {
     if (school > SPELL_SCHOOL_NORMAL)
     {
         float value = GetTotalAuraModValue(UnitMods(UNIT_MOD_RESISTANCE_START + school));
         SetResistance(SpellSchools(school), int32(value));
     }
     else
         UpdateArmor();
 }
References Unit::GetTotalAuraModValue(), Unit::SetResistance(), SPELL_SCHOOL_NORMAL, UNIT_MOD_RESISTANCE_START, and UpdateArmor().
UpdateStats()
bool Creature::UpdateStats (Stats stat) override virtual
Implements Unit.
Reimplemented in Totem, and Guardian.
Definition at line 972 of file StatSystem.cpp.
 {
     return true;
 }
UpdateVendorItemCurrentCount()
uint32 Creature::UpdateVendorItemCurrentCount (VendorItem const * vItem, uint32 used_count)
Definition at line 2795 of file Creature.cpp.
 {
     if (!vItem->maxcount)
         return 0;
     VendorItemCounts::iterator itr = m_vendorItemCounts.begin();
     for (; itr != m_vendorItemCounts.end(); ++itr)
         if (itr->itemId == vItem->item)
             break;
     if (itr == m_vendorItemCounts.end())
     {
         uint32 new_count = vItem->maxcount > used_count ? vItem->maxcount - used_count : 0;
         m_vendorItemCounts.push_back(VendorItemCount(vItem->item, new_count));
         return new_count;
     }
     VendorItemCount* vCount = &*itr;
     time_t ptime = time(nullptr);
     if (time_t(vCount->lastIncrementTime + vItem->incrtime) <= ptime)
     {
         ItemTemplate const* pProto = sObjectMgr->GetItemTemplate(vItem->item);
         uint32 diff = uint32((ptime - vCount->lastIncrementTime) / vItem->incrtime);
         if ((vCount->count + diff * pProto->BuyCount) < vItem->maxcount)
             vCount->count += diff * pProto->BuyCount;
         else
             vCount->count = vItem->maxcount;
     }
     vCount->count = vCount->count > used_count ? vCount->count - used_count : 0;
     vCount->lastIncrementTime = ptime;
     return vCount->count;
 }
References ItemTemplate::BuyCount, VendorItemCount::count, diff(), VendorItem::incrtime, VendorItem::item, VendorItemCount::lastIncrementTime, m_vendorItemCounts, VendorItem::maxcount, and sObjectMgr.
Referenced by Player::_StoreOrEquipNewItem().
UpdateWaypointID()
void Creature::UpdateWaypointID (uint32 wpID) inline
Definition at line 330 of file Creature.h.
 { m_waypointID = wpID; }
References m_waypointID.
Referenced by wp_commandscript::HandleWpUnLoadCommand(), and WaypointMovementGenerator< Creature >::OnArrived().
Member Data Documentation
_focusSpell
Spell const* Creature::_focusSpell private
Definition at line 460 of file Creature.h.
Referenced by Creature(), FocusTarget(), ReleaseFocus(), and SetTarget().
_isMissingSwimmingFlagOutOfCombat
bool Creature::_isMissingSwimmingFlagOutOfCombat private
Locks the target during spell cast for proper facing
Definition at line 462 of file Creature.h.
Referenced by HasSwimmingFlagOutOfCombat(), and RefreshSwimmingFlag().
_lastDamagedTime
std::shared_ptr<time_t> Creature::_lastDamagedTime mutable private
Definition at line 455 of file Creature.h.
Referenced by GetLastDamagedTime(), GetLastDamagedTimePtr(), setDeathState(), SetLastDamagedTime(), and SetLastDamagedTimePtr().
struct { ... } Creature::_spellFocusInfo
Referenced by HasSpellFocus().
Delay
uint32 Creature::Delay = 0
Definition at line 143 of file Creature.h.
DisableReputationGain
bool Creature::DisableReputationGain protected
Definition at line 431 of file Creature.h.
Referenced by Creature(), IsReputationGainDisabled(), and SetDisableReputationGain().
loot
Loot Creature::loot
Definition at line 211 of file Creature.h.
Referenced by Spell::CheckCast(), NPCStaveQuestAI::ClearLootIfUnfair(), boss_high_king_maulgar::boss_high_king_maulgarAI::DoAction(), WorldSession::DoLootRelease(), WorldSession::HandleAutostoreLootItemOpcode(), WorldSession::HandleLootMasterGiveOpcode(), WorldSession::HandleLootMoneyOpcode(), Player::isAllowedToLoot(), Unit::Kill(), RemoveCorpse(), Player::SendLoot(), Group::SendLooter(), boss_priestess_delrissa::boss_priestess_delrissaAI::SummonedCreatureDies(), and Update().
lootingGroupLowGUID
uint32 Creature::lootingGroupLowGUID
Definition at line 288 of file Creature.h.
Referenced by Update().
lootPickPocketRestoreTime
uint32 Creature::lootPickPocketRestoreTime protected
Definition at line 405 of file Creature.h.
Referenced by CanGeneratePickPocketLoot(), ResetPickPocketLootTime(), and SetPickPocketLootTime().
m_AI_locked
bool Creature::m_AI_locked protected
Definition at line 420 of file Creature.h.
Referenced by AIM_Initialize(), and Update().
m_AlreadyCallAssistance
bool Creature::m_AlreadyCallAssistance protected
Definition at line 417 of file Creature.h.
Referenced by CallAssistance(), and SetNoCallAssistance().
m_AlreadySearchedAssistance
bool Creature::m_AlreadySearchedAssistance protected
Definition at line 418 of file Creature.h.
Referenced by HasSearchedAssistance(), and SetNoSearchAssistance().
m_assistanceTimer
uint32 Creature::m_assistanceTimer private
Definition at line 464 of file Creature.h.
Referenced by SetAssistanceTimer(), and Update().
m_cannotReachTarget
bool Creature::m_cannotReachTarget private
Definition at line 457 of file Creature.h.
Referenced by CanNotReachTarget(), IsNotReachable(), IsNotReachableAndNeedRegen(), and SetCannotReachTarget().
m_cannotReachTimer
uint32 Creature::m_cannotReachTimer private
Definition at line 458 of file Creature.h.
Referenced by IsNotReachable(), IsNotReachableAndNeedRegen(), SetCannotReachTarget(), and Update().
m_CombatDistance
float Creature::m_CombatDistance
Definition at line 355 of file Creature.h.
Referenced by ArcherAI::ArcherAI(), ArcherAI::AttackStart(), TurretAI::CanAIAttack(), WorldObject::CanDetectStealthOf(), CanStartAttack(), Creature(), npc_gunship_boarding_addAI::npc_gunship_boarding_addAI(), npc_gunship_gunner::npc_gunship_gunnerAI::npc_gunship_gunnerAI(), npc_gunship_mage::npc_gunship_mageAI::npc_gunship_mageAI(), npc_gunship_rocketeer::npc_gunship_rocketeerAI::npc_gunship_rocketeerAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::npc_high_overlord_saurfang_igbAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::npc_muradin_bronzebeard_igbAI(), TurretAI::TurretAI(), and HostileReference::updateOnlineStatus().
m_corpseDelay
uint32 Creature::m_corpseDelay protected
Definition at line 402 of file Creature.h.
Referenced by Create(), GetCorpseDelay(), SetCorpseDelay(), and setDeathState().
m_corpseRemoveTime
time_t Creature::m_corpseRemoveTime protected
Timers.
Definition at line 398 of file Creature.h.
Referenced by AllLootRemovedFromCorpse(), IsInvisibleDueToDespawn(), RemoveCorpse(), setDeathState(), Pet::Update(), and Update().
m_creatureData
CreatureData const* Creature::m_creatureData protected
Definition at line 434 of file Creature.h.
Referenced by GetCreatureData(), isVendorWithIconSpeak(), LoadCreatureFromDB(), and SaveRespawnTime().
m_creatureInfo
CreatureTemplate const* Creature::m_creatureInfo protected
Definition at line 433 of file Creature.h.
Referenced by GetCreatureTemplate(), InitEntry(), IsDamageEnoughForLootingAndReward(), IsValidTrainerForPlayer(), and isVendorWithIconSpeak().
m_CreatureSpellCooldowns
CreatureSpellCooldowns Creature::m_CreatureSpellCooldowns
Definition at line 236 of file Creature.h.
Referenced by _AddCreatureSpellCooldown(), Pet::_LoadSpellCooldowns(), Pet::_SaveSpellCooldowns(), Creature(), Spell::EffectSummonPet(), GetSpellCooldown(), Pet::HandleAsynchLoadFailed(), HasSpellCooldown(), Player::PetSpellInitialize(), Pet::RemoveSpellCooldown(), and Player::VehicleSpellInitialize().
m_defaultMovementType
MovementGeneratorType Creature::m_defaultMovementType protected
Definition at line 410 of file Creature.h.
Referenced by GetDefaultMovementType(), InitEntry(), LoadCreatureFromDB(), and SetDefaultMovementType().
m_detectionDistance
float Creature::m_detectionDistance protected
Definition at line 436 of file Creature.h.
Referenced by GetDetectionRange(), and SetDetectionDistance().
m_equipmentId
uint8 Creature::m_equipmentId protected
Definition at line 412 of file Creature.h.
Referenced by GetCurrentEquipmentId(), LoadEquipment(), and SetCurrentEquipmentId().
m_formation
CreatureGroup* Creature::m_formation private
Definition at line 452 of file Creature.h.
Referenced by GetFormation(), Motion_Initialize(), RemoveFromWorld(), setDeathState(), and SetFormation().
m_groupLootTimer
uint32 Creature::m_groupLootTimer
Definition at line 287 of file Creature.h.
Referenced by Update().
m_homePosition
Position Creature::m_homePosition protected
Definition at line 428 of file Creature.h.
Referenced by CanCreatureAttack(), GetHomePosition(), and SetHomePosition().
m_isTempWorldObject
bool Creature::m_isTempWorldObject
Definition at line 357 of file Creature.h.
Referenced by Creature(), and Map::SwitchGridContainers().
m_LootMode
uint16 Creature::m_LootMode protected
Definition at line 437 of file Creature.h.
Referenced by AddLootMode(), GetLootMode(), HasLootMode(), RemoveLootMode(), ResetLootMode(), and SetLootMode().
m_lootRecipient
ObjectGuid Creature::m_lootRecipient protected
Definition at line 394 of file Creature.h.
Referenced by GetLootRecipient(), GetLootRecipientGUID(), hasLootRecipient(), isTappedBy(), and SetLootRecipient().
m_lootRecipientGroup
ObjectGuid::LowType Creature::m_lootRecipientGroup protected
Definition at line 395 of file Creature.h.
Referenced by GetLootRecipientGroup(), GetLootRecipientGroupGUID(), hasLootRecipient(), and SetLootRecipient().
m_meleeDamageSchoolMask
SpellSchoolMask Creature::m_meleeDamageSchoolMask protected
Definition at line 422 of file Creature.h.
Referenced by GetMeleeDamageSchoolMask(), and SetMeleeDamageSchool().
m_moveBackwardsMovementTime
uint32 Creature::m_moveBackwardsMovementTime = MOVE_BACKWARDS_CHECK_INTERVAL
Definition at line 375 of file Creature.h.
Referenced by Update().
m_moveCircleMovementTime
uint32 Creature::m_moveCircleMovementTime = MOVE_CIRCLE_CHECK_INTERVAL
Definition at line 374 of file Creature.h.
Referenced by Update().
m_moveInLineOfSightDisabled
bool Creature::m_moveInLineOfSightDisabled protected
Definition at line 425 of file Creature.h.
Referenced by IsMoveInLineOfSightDisabled(), and UpdateMoveInLineOfSightState().
m_moveInLineOfSightStrictlyDisabled
bool Creature::m_moveInLineOfSightStrictlyDisabled protected
Definition at line 426 of file Creature.h.
Referenced by IsMoveInLineOfSightStrictlyDisabled(), and UpdateMoveInLineOfSightState().
m_originalAnimTier
uint8 Creature::m_originalAnimTier protected
Definition at line 415 of file Creature.h.
Referenced by CanHover(), and LoadCreaturesAddon().
m_originalEntry
uint32 Creature::m_originalEntry protected
Definition at line 423 of file Creature.h.
Referenced by Pet::Create(), GetOriginalEntry(), Respawn(), and SetOriginalEntry().
m_originalEquipmentId
int8 Creature::m_originalEquipmentId protected
Definition at line 413 of file Creature.h.
Referenced by GetOriginalEquipmentId(), and InitEntry().
m_path_id
uint32 Creature::m_path_id private
Definition at line 449 of file Creature.h.
Referenced by GetWaypointPath(), LoadCreaturesAddon(), and LoadPath().
m_PlayerDamageReq
uint32 Creature::m_PlayerDamageReq
Definition at line 348 of file Creature.h.
Referenced by Acore::XP::Gain(), IsDamageEnoughForLootingAndReward(), LowerPlayerDamageReq(), ResetPlayerDamageReq(), and UpdateEntry().
m_ProhibitSchoolTime
uint32 Creature::m_ProhibitSchoolTime[7]
Definition at line 237 of file Creature.h.
Referenced by Creature(), IsSpellProhibited(), and ProhibitSpellSchool().
m_reactState
ReactStates Creature::m_reactState protected
Definition at line 407 of file Creature.h.
Referenced by GetReactState(), HasReactState(), and SetReactState().
m_regenHealth
bool Creature::m_regenHealth protected
Definition at line 419 of file Creature.h.
Referenced by isRegeneratingHealth(), LoadCreatureFromDB(), SetRegeneratingHealth(), and UpdateEntry().
m_respawnDelay
uint32 Creature::m_respawnDelay protected
Definition at line 401 of file Creature.h.
Referenced by ForcedDespawn(), GetRespawnDelay(), LoadCreatureFromDB(), RemoveCorpse(), SaveToDB(), setDeathState(), and SetRespawnDelay().
m_respawnedTime
time_t Creature::m_respawnedTime protected
Definition at line 400 of file Creature.h.
Referenced by CanCreatureAttack(), Creature(), and Respawn().
m_respawnTime
time_t Creature::m_respawnTime protected
Definition at line 399 of file Creature.h.
Referenced by AllLootRemovedFromCorpse(), ForcedDespawn(), GetRespawnTime(), GetRespawnTimeEx(), LoadCreatureFromDB(), RemoveCorpse(), Respawn(), SaveRespawnTime(), setDeathState(), SetRespawnTime(), and Update().
m_SightDistance
float Creature::m_SightDistance
Definition at line 355 of file Creature.h.
Referenced by ArcherAI::ArcherAI(), boss_anub_arak::boss_anub_arakAI::boss_anub_arakAI(), boss_anubarak_trial::boss_anubarak_trialAI::boss_anubarak_trialAI(), boss_thorngrin_the_tender::boss_thorngrin_the_tenderAI::boss_thorngrin_the_tenderAI(), Creature(), WorldObject::GetGridActivationRange(), WorldObject::GetSightRange(), npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::npc_blood_queen_lana_thelAI(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::npc_icc_nerubar_broodkeeperAI(), and TurretAI::TurretAI().
m_spawnId
ObjectGuid::LowType Creature::m_spawnId protected
For new or temporary creatures is 0 for saved it is lowguid.
Definition at line 411 of file Creature.h.
Referenced by AddToWorld(), AIM_Initialize(), Pet::Create(), DeleteFromDB(), GetCreatureAddon(), GetRespawnPosition(), GetSpawnId(), LoadCreatureFromDB(), RemoveFromWorld(), Respawn(), SaveRespawnTime(), SaveToDB(), and Update().
m_spells
uint32 Creature::m_spells[MAX_CREATURE_SPELLS]
Definition at line 235 of file Creature.h.
Referenced by ArcherAI::ArcherAI(), Creature(), Totem::GetSpell(), spell_q13007_iron_colossus::spell_q13007_iron_colossus_SpellScript::HandleDummy(), HasSpell(), CharmInfo::InitCharmCreateSpells(), InitEntry(), CombatAI::InitializeAI(), CharmInfo::InitPossessCreateSpells(), TempSummon::InitStats(), TriggerAI::IsSummonedBy(), boss_maexxna_webwrap::boss_maexxna_webwrapAI::JustDied(), trigger_death::trigger_deathAI::JustDied(), reachWithSpellAttack(), reachWithSpellCure(), FactorySelector::selectAI(), ScriptedAI::SelectSpell(), boss_maexxna_webwrap::boss_maexxna_webwrapAI::SetGUID(), npc_oculus_drake::npc_oculus_drakeAI::SpellHitTarget(), trigger_periodic::trigger_periodicAI::trigger_periodicAI(), TurretAI::TurretAI(), ArcherAI::UpdateAI(), TurretAI::UpdateAI(), npc_oculus_drake::npc_oculus_drakeAI::UpdateAI(), npc_pet_gen_gnomish_flame_turret::UpdateAI(), and Player::VehicleSpellInitialize().
m_transportCheckTimer
uint16 Creature::m_transportCheckTimer protected
Definition at line 404 of file Creature.h.
Referenced by Update().
m_transportHomePosition
Position Creature::m_transportHomePosition protected
Definition at line 429 of file Creature.h.
Referenced by GetTransportHomePosition(), and SetTransportHomePosition().
m_vendorItemCounts
VendorItemCounts Creature::m_vendorItemCounts protected
Definition at line 390 of file Creature.h.
Referenced by GetVendorItemCurrentCount(), UpdateVendorItemCurrentCount(), and ~Creature().
m_wanderDistance
float Creature::m_wanderDistance protected
Definition at line 403 of file Creature.h.
Referenced by GetWanderDistance(), InitEntry(), LoadCreatureFromDB(), SaveToDB(), and SetWanderDistance().
m_waypointID
uint32 Creature::m_waypointID private
Definition at line 448 of file Creature.h.
Referenced by GetCurrentWaypointID(), and UpdateWaypointID().
MOVE_BACKWARDS_CHECK_INTERVAL
constexpr uint32 Creature::MOVE_BACKWARDS_CHECK_INTERVAL = 2000 static constexpr
Definition at line 373 of file Creature.h.
Referenced by Update().
MOVE_CIRCLE_CHECK_INTERVAL
constexpr uint32 Creature::MOVE_CIRCLE_CHECK_INTERVAL = 3000 static constexpr
Definition at line 372 of file Creature.h.
Referenced by Update().
Orientation
float Creature::Orientation = 0.0f
Definition at line 145 of file Creature.h.
Spell
::Spell const* Creature::Spell = nullptr
Definition at line 142 of file Creature.h.
Target
ObjectGuid Creature::Target
Definition at line 144 of file Creature.h.
TriggerJustRespawned
bool Creature::TriggerJustRespawned private
Definition at line 453 of file Creature.h.
Referenced by Creature(), Respawn(), and Update().
The documentation for this class was generated from the following files:
src/server/game/Entities/Creature/Creature.h
src/server/game/Entities/Creature/Creature.cpp
src/server/game/Entities/Unit/StatSystem.cpp
src/server/game/Entities/Unit/Unit.cpp