Azerotcore-wotlk: boss_lord_marrowgar Struct Reference
boss_lord_marrowgar Struct Reference
Public Member Functions
boss_lord_marrowgar (Creature *creature)
void Reset () override
void EnterCombat (Unit *) override
void SpellHitTarget (Unit *target, const SpellInfo *spell) override
ObjectGuid GetGUID (int32 id) const override
void UpdateAI (uint32 diff) override
void MovementInform (uint32 type, uint32 id) override
void JustDied (Unit *) override
void JustReachedHome () override
void KilledUnit (Unit *victim) override
void MoveInLineOfSight (Unit *who) override
bool CanAIAttack (Unit const *target) const override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SpellHit (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
bool _introDone
bool _boneSlice
ObjectGuid _lastBoneSliceTargets [3]
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 99 of file boss_lord_marrowgar.cpp.
Constructor & Destructor Documentation
boss_lord_marrowgar()
boss_lord_marrowgar::boss_lord_marrowgar (Creature * creature) inline
Definition at line 102 of file boss_lord_marrowgar.cpp.
                                             : BossAI(creature, DATA_LORD_MARROWGAR)
     {
         _introDone = false;
         _boneSlice = false;
     }
References _boneSlice, and _introDone.
Member Function Documentation
CanAIAttack()
bool boss_lord_marrowgar::CanAIAttack (Unit const * target) const inline override virtual
Reimplemented from UnitAI.
Definition at line 302 of file boss_lord_marrowgar.cpp.
     {
         return target->GetPositionX() < -337.0f; // main gate
     }
References Position::GetPositionX().
EnterCombat()
void boss_lord_marrowgar::EnterCombat (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 130 of file boss_lord_marrowgar.cpp.
     {
         Talk(SAY_AGGRO);
         me->setActive(true);
         DoZoneInCombat();
         instance->SetBossState(DATA_LORD_MARROWGAR, IN_PROGRESS);
     }
References DATA_LORD_MARROWGAR, CreatureAI::DoZoneInCombat(), IN_PROGRESS, BossAI::instance, ScriptedAI::me, SAY_AGGRO, WorldObject::setActive(), InstanceScript::SetBossState(), and CreatureAI::Talk().
GetGUID()
ObjectGuid boss_lord_marrowgar::GetGUID (int32 id) const inline override virtual
Reimplemented from UnitAI.
Definition at line 149 of file boss_lord_marrowgar.cpp.
     {
         if (id >= 0 && id <= 2)
             return _lastBoneSliceTargets[id];
         return ObjectGuid::Empty;
     }
References _lastBoneSliceTargets, and ObjectGuid::Empty.
JustDied()
void boss_lord_marrowgar::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 273 of file boss_lord_marrowgar.cpp.
     {
         Talk(SAY_DEATH);
         _JustDied();
     }
References BossAI::_JustDied(), SAY_DEATH, and CreatureAI::Talk().
JustReachedHome()
void boss_lord_marrowgar::JustReachedHome () inline override virtual
Reimplemented from BossAI.
Definition at line 279 of file boss_lord_marrowgar.cpp.
     {
         _JustReachedHome();
         instance->SetBossState(DATA_LORD_MARROWGAR, FAIL);
     }
References BossAI::_JustReachedHome(), DATA_LORD_MARROWGAR, FAIL, BossAI::instance, and InstanceScript::SetBossState().
KilledUnit()
void boss_lord_marrowgar::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 285 of file boss_lord_marrowgar.cpp.
     {
         if (victim->GetTypeId() == TYPEID_PLAYER)
             Talk(SAY_KILL);
     }
References Object::GetTypeId(), SAY_KILL, CreatureAI::Talk(), and TYPEID_PLAYER.
MoveInLineOfSight()
void boss_lord_marrowgar::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
Definition at line 291 of file boss_lord_marrowgar.cpp.
     {
         if (!_introDone && me->IsAlive() && who->GetTypeId() == TYPEID_PLAYER && me->GetExactDist2dSq(who) <= 10000.0f) // 100*100, moveinlineofsight limited to 60yd anyway
         {
             Talk(SAY_ENTER_ZONE);
             _introDone = true;
         }
         BossAI::MoveInLineOfSight(who);
     }
References _introDone, Position::GetExactDist2dSq(), Object::GetTypeId(), Unit::IsAlive(), ScriptedAI::me, CreatureAI::MoveInLineOfSight(), SAY_ENTER_ZONE, CreatureAI::Talk(), and TYPEID_PLAYER.
MovementInform()
void boss_lord_marrowgar::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 265 of file boss_lord_marrowgar.cpp.
     {
         if (type != POINT_MOTION_TYPE || id != 1337)
             return;
         events.ScheduleEvent(EVENT_SPELL_COLDFLAME_BONE_STORM, 0);
     }
References EVENT_SPELL_COLDFLAME_BONE_STORM, and POINT_MOTION_TYPE.
Reset()
void boss_lord_marrowgar::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 112 of file boss_lord_marrowgar.cpp.
     {
         me->SetReactState(REACT_AGGRESSIVE);
         _Reset();
         events.ScheduleEvent(EVENT_ENABLE_BONE_SLICE, 10000);
         events.ScheduleEvent(EVENT_SPELL_BONE_SPIKE_GRAVEYARD, urand(10000, 15000));
         events.ScheduleEvent(EVENT_SPELL_COLDFLAME, 5000);
         events.ScheduleEvent(EVENT_WARN_BONE_STORM, urand(45000, 50000));
         events.ScheduleEvent(EVENT_ENRAGE, 600000);
         _boneSlice = false;
         for (uint8 i = 0; i < 3; ++i)
             _lastBoneSliceTargets[i].Clear();
         instance->SetData(DATA_BONED_ACHIEVEMENT, uint32(true));
     }
References _boneSlice, _lastBoneSliceTargets, BossAI::_Reset(), DATA_BONED_ACHIEVEMENT, EVENT_ENABLE_BONE_SLICE, EVENT_ENRAGE, EVENT_SPELL_BONE_SPIKE_GRAVEYARD, EVENT_SPELL_COLDFLAME, EVENT_WARN_BONE_STORM, BossAI::instance, ScriptedAI::me, REACT_AGGRESSIVE, ZoneScript::SetData(), Creature::SetReactState(), and urand().
SpellHitTarget()
void boss_lord_marrowgar::SpellHitTarget (Unit * target, const SpellInfo * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 138 of file boss_lord_marrowgar.cpp.
     {
         if (target && (spell->Id == 69055 || spell->Id == 70814)) // Bone Slice (Saber Lash)
             for (uint8 i = 0; i < 3; ++i)
                 if (!_lastBoneSliceTargets[i])
                 {
                     _lastBoneSliceTargets[i] = target->GetGUID();
                     break;
                 }
     }
References _lastBoneSliceTargets, Object::GetGUID(), and SpellInfo::Id.
UpdateAI()
void boss_lord_marrowgar::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 157 of file boss_lord_marrowgar.cpp.
     {
         if (!UpdateVictim() || !CheckInRoom())
             return;
         events.Update(diff);
         if (me->HasUnitState(UNIT_STATE_CASTING))
             return;
         switch (events.ExecuteEvent())
         {
             case 0:
                 break;
             case EVENT_ENABLE_BONE_SLICE:
                 _boneSlice = true;
                 break;
             case EVENT_SPELL_BONE_SPIKE_GRAVEYARD:
                 {
                     bool a = me->HasAura(SPELL_BONE_STORM);
                     if (IsHeroic() || !a)
                         me->CastSpell(me, SPELL_BONE_SPIKE_GRAVEYARD, a);
                     events.RepeatEvent(urand(15000, 20000));
                 }
                 break;
             case EVENT_SPELL_COLDFLAME:
                 if (!me->HasAura(SPELL_BONE_STORM))
                     me->CastSpell((Unit*)nullptr, SPELL_COLDFLAME_NORMAL, false);
                 events.RepeatEvent(5000);
                 break;
             case EVENT_SPELL_COLDFLAME_BONE_STORM:
                 me->CastSpell(me, SPELL_COLDFLAME_BONE_STORM, false);
                 break;
             case EVENT_WARN_BONE_STORM:
                 _boneSlice = false;
                 Talk(EMOTE_BONE_STORM);
                 Talk(SAY_BONE_STORM);
                 me->FinishSpell(CURRENT_MELEE_SPELL, false);
                 me->CastSpell(me, SPELL_BONE_STORM, false);
                 me->SetReactState(REACT_PASSIVE); // to prevent chasing another target on UpdateVictim()
                 me->GetMotionMaster()->MoveIdle();
                 me->GetMotionMaster()->MovementExpired();
                 events.RepeatEvent(urand(90000, 95000));
                 events.ScheduleEvent(EVENT_BEGIN_BONE_STORM, 3050);
                 break;
             case EVENT_BEGIN_BONE_STORM:
                 {
                     uint32 _boneStormDuration = RAID_MODE<uint32>(20000, 30000, 20000, 30000);
                     if (Aura* pStorm = me->GetAura(SPELL_BONE_STORM))
                         pStorm->SetDuration(int32(_boneStormDuration));
                     events.ScheduleEvent(EVENT_BONE_STORM_MOVE, 0);
                     events.ScheduleEvent(EVENT_END_BONE_STORM, _boneStormDuration + 1);
                 }
                 break;
             case EVENT_BONE_STORM_MOVE:
                 {
                     if (me->GetMotionMaster()->GetCurrentMovementGeneratorType() == POINT_MOTION_TYPE)
                     {
                         events.RepeatEvent(1);
                         break;
                     }
                     events.RepeatEvent(5000);
                     Unit* unit = SelectTarget(SELECT_TARGET_RANDOM, 0, BoneStormMoveTargetSelector(me));
                     if (!unit)
                     {
                         if ((unit = SelectTarget(SELECT_TARGET_TOPAGGRO, 0, 175.0f, true)))
                             if (unit->GetPositionX() > -337.0f)
{
                                 EnterEvadeMode();
                                 return;
                             }
                     }
                     if (unit)
                         me->GetMotionMaster()->MoveCharge(unit->GetPositionX(), unit->GetPositionY(), unit->GetPositionZ(), 25.0f, 1337);
                     break;
                 }
                 break;
             case EVENT_END_BONE_STORM:
                 me->StopMoving();
                 me->GetMotionMaster()->MovementExpired();
                 me->SetReactState(REACT_AGGRESSIVE);
                 DoStartMovement(me->GetVictim());
                 events.CancelEvent(EVENT_BONE_STORM_MOVE);
                 events.ScheduleEvent(EVENT_ENABLE_BONE_SLICE, 10000);
                 if (!IsHeroic())
                     events.RescheduleEvent(EVENT_SPELL_BONE_SPIKE_GRAVEYARD, urand(15000, 20000));
                 break;
             case EVENT_ENRAGE:
                 me->CastSpell(me, SPELL_BERSERK, true);
                 Talk(SAY_BERSERK);
                 break;
         }
         if (me->HasAura(SPELL_BONE_STORM))
             return;
         if (_boneSlice && !me->GetCurrentSpell(CURRENT_MELEE_SPELL))
             DoCastVictim(SPELL_BONE_SLICE);
         if (_boneSlice && me->isAttackReady() && me->GetVictim() && !me->HasUnitState(UNIT_STATE_CASTING) && me->IsWithinMeleeRange(me->GetVictim()))
         {
             for (uint8 i = 0; i < 3; ++i)
                 _lastBoneSliceTargets[i].Clear();
         }
         DoMeleeAttackIfReady();
     }
References _boneSlice, _lastBoneSliceTargets, mpq::a, Unit::CastSpell(), BossAI::CheckInRoom(), CURRENT_MELEE_SPELL, diff(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DoStartMovement(), EMOTE_BONE_STORM, CreatureAI::EnterEvadeMode(), EVENT_BEGIN_BONE_STORM, EVENT_BONE_STORM_MOVE, EVENT_ENABLE_BONE_SLICE, EVENT_END_BONE_STORM, EVENT_ENRAGE, EVENT_SPELL_BONE_SPIKE_GRAVEYARD, EVENT_SPELL_COLDFLAME, EVENT_SPELL_COLDFLAME_BONE_STORM, EVENT_WARN_BONE_STORM, Unit::FinishSpell(), Unit::GetAura(), MotionMaster::GetCurrentMovementGeneratorType(), Unit::GetCurrentSpell(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetVictim(), Unit::HasAura(), Unit::HasUnitState(), Unit::isAttackReady(), ScriptedAI::IsHeroic(), Unit::IsWithinMeleeRange(), ScriptedAI::me, MotionMaster::MoveCharge(), MotionMaster::MoveIdle(), MotionMaster::MovementExpired(), POINT_MOTION_TYPE, REACT_AGGRESSIVE, REACT_PASSIVE, SAY_BERSERK, SAY_BONE_STORM, SELECT_TARGET_RANDOM, SELECT_TARGET_TOPAGGRO, UnitAI::SelectTarget(), Creature::SetReactState(), SPELL_BERSERK, SPELL_BONE_SLICE, SPELL_BONE_SPIKE_GRAVEYARD, SPELL_BONE_STORM, SPELL_COLDFLAME_BONE_STORM, SPELL_COLDFLAME_NORMAL, Unit::StopMoving(), CreatureAI::Talk(), UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
_boneSlice
bool boss_lord_marrowgar::_boneSlice
Definition at line 109 of file boss_lord_marrowgar.cpp.
Referenced by boss_lord_marrowgar(), Reset(), and UpdateAI().
_introDone
bool boss_lord_marrowgar::_introDone
Definition at line 108 of file boss_lord_marrowgar.cpp.
Referenced by boss_lord_marrowgar(), and MoveInLineOfSight().
_lastBoneSliceTargets
ObjectGuid boss_lord_marrowgar::_lastBoneSliceTargets[3]
Definition at line 110 of file boss_lord_marrowgar.cpp.
Referenced by GetGUID(), Reset(), SpellHitTarget(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_lord_marrowgar.cpp