Azerotcore-wotlk: npc_archmage_landalock::npc_archmage_landalockAI Struct Reference
npc_archmage_landalock::npc_archmage_landalockAI Struct Reference
Public Member Functions
npc_archmage_landalockAI (Creature *creature)
uint32 GetImageEntry (uint32 QuestId)
void JustSummoned (Creature *image) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
uint32 _switchImageTimer
ObjectGuid _summonGUID
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 320 of file zone_dalaran.cpp.
Constructor & Destructor Documentation
npc_archmage_landalockAI()
npc_archmage_landalock::npc_archmage_landalockAI::npc_archmage_landalockAI (Creature * creature) inline
Definition at line 322 of file zone_dalaran.cpp.
                                                      : ScriptedAI(creature)
         {
             _switchImageTimer = MINUTE * IN_MILLISECONDS;
             _summonGUID.Clear();
         }
References _summonGUID, _switchImageTimer, ObjectGuid::Clear(), IN_MILLISECONDS, and MINUTE.
Member Function Documentation
GetImageEntry()
uint32 npc_archmage_landalock::npc_archmage_landalockAI::GetImageEntry (uint32 QuestId) inline
Definition at line 328 of file zone_dalaran.cpp.
         {
             switch (QuestId)
             {
                 case QUEST_SARTHARION_MUST_DIE:
                     return NPC_SARTHARION_IMAGE;
                 case QUEST_ANUBREKHAN_MUST_DIE:
                     return NPC_ANUBREKHAN_IMAGE;
                 case QUEST_NOTH_THE_PLAGUEBINGER_MUST_DIE:
                     return NPC_NOTH_THE_PLAGUEBINGER_IMAGE;
                 case QUEST_INSTRUCTOR_RAZUVIOUS_MUST_DIE:
                     return NPC_INSTRUCTOR_RAZUVIOUS_IMAGE;
                 case QUEST_PATCHWERK_MUST_DIE:
                     return NPC_PATCHWERK_IMAGE;
                 case QUEST_MALYGOS_MUST_DIE:
                     return NPC_MALYGOS_IMAGE;
                 case QUEST_FLAME_LEVIATHAN_MUST_DIE:
                     return NPC_FLAME_LEVIATHAN_IMAGE;
                 case QUEST_RAZORSCALE_MUST_DIE:
                     return NPC_RAZORSCALE_IMAGE;
                 case QUEST_IGNIS_THE_FURNACE_MASTER_MUST_DIE:
                     return NPC_IGNIS_THE_FURNACE_MASTER_IMAGE;
                 case QUEST_XT_002_DECONSTRUCTOR_MUST_DIE:
                     return NPC_XT_002_DECONSTRUCTOR_IMAGE;
                 case QUEST_LORD_JARAXXUS_MUST_DIE:
                     return NPC_LORD_JARAXXUS_IMAGE;
                 default: //case QUEST_LORD_MARROWGAR_MUST_DIE:
                     return NPC_LORD_MARROWGAR_IMAGE;
             }
         }
References NPC_ANUBREKHAN_IMAGE, NPC_FLAME_LEVIATHAN_IMAGE, NPC_IGNIS_THE_FURNACE_MASTER_IMAGE, NPC_INSTRUCTOR_RAZUVIOUS_IMAGE, NPC_LORD_JARAXXUS_IMAGE, NPC_LORD_MARROWGAR_IMAGE, NPC_MALYGOS_IMAGE, NPC_NOTH_THE_PLAGUEBINGER_IMAGE, NPC_PATCHWERK_IMAGE, NPC_RAZORSCALE_IMAGE, NPC_SARTHARION_IMAGE, NPC_XT_002_DECONSTRUCTOR_IMAGE, QUEST_ANUBREKHAN_MUST_DIE, QUEST_FLAME_LEVIATHAN_MUST_DIE, QUEST_IGNIS_THE_FURNACE_MASTER_MUST_DIE, QUEST_INSTRUCTOR_RAZUVIOUS_MUST_DIE, QUEST_LORD_JARAXXUS_MUST_DIE, QUEST_MALYGOS_MUST_DIE, QUEST_NOTH_THE_PLAGUEBINGER_MUST_DIE, QUEST_PATCHWERK_MUST_DIE, QUEST_RAZORSCALE_MUST_DIE, QUEST_SARTHARION_MUST_DIE, and QUEST_XT_002_DECONSTRUCTOR_MUST_DIE.
Referenced by UpdateAI().
JustSummoned()
void npc_archmage_landalock::npc_archmage_landalockAI::JustSummoned (Creature * image) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 359 of file zone_dalaran.cpp.
         {
             // xinef: screams like a baby
             if (image->GetEntry() != NPC_ANUBREKHAN_IMAGE)
                 image->SetUnitMovementFlags(MOVEMENTFLAG_RIGHT);
             _summonGUID = image->GetGUID();
         }
References _summonGUID, Object::GetEntry(), Object::GetGUID(), MOVEMENTFLAG_RIGHT, NPC_ANUBREKHAN_IMAGE, and Unit::SetUnitMovementFlags().
UpdateAI()
void npc_archmage_landalock::npc_archmage_landalockAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 367 of file zone_dalaran.cpp.
         {
             ScriptedAI::UpdateAI(diff);
             _switchImageTimer += diff;
             if (_switchImageTimer > MINUTE * IN_MILLISECONDS)
             {
                 _switchImageTimer = 0;
                 QuestRelationBounds objectQR = sObjectMgr->GetCreatureQuestRelationBounds(me->GetEntry());
                 for (QuestRelations::const_iterator i = objectQR.first; i != objectQR.second; ++i)
                 {
                     uint32 questId = i->second;
                     Quest const* quest = sObjectMgr->GetQuestTemplate(questId);
                     if (!quest || !quest->IsWeekly())
                         continue;
                     uint32 newEntry = GetImageEntry(questId);
                     if (_summonGUID.GetEntry() != newEntry)
                     {
                         if (Creature* image = ObjectAccessor::GetCreature(*me, _summonGUID))
                             image->DespawnOrUnsummon();
                         float z = 653.622f;
                         if (newEntry == NPC_MALYGOS_IMAGE || newEntry == NPC_RAZORSCALE_IMAGE || newEntry == NPC_SARTHARION_IMAGE)
                             z += 3.0f;
                         me->SummonCreature(newEntry, 5703.077f, 583.9757f, z, 3.926991f);
                     }
                 }
             }
         }
References _summonGUID, _switchImageTimer, diff(), ObjectAccessor::GetCreature(), Object::GetEntry(), ObjectGuid::GetEntry(), GetImageEntry(), IN_MILLISECONDS, Quest::IsWeekly(), ScriptedAI::me, MINUTE, NPC_MALYGOS_IMAGE, NPC_RAZORSCALE_IMAGE, NPC_SARTHARION_IMAGE, sObjectMgr, WorldObject::SummonCreature(), ScriptedAI::UpdateAI(), and G3D::z.
Member Data Documentation
_summonGUID
ObjectGuid npc_archmage_landalock::npc_archmage_landalockAI::_summonGUID private
Definition at line 399 of file zone_dalaran.cpp.
Referenced by JustSummoned(), npc_archmage_landalockAI(), and UpdateAI().
_switchImageTimer
uint32 npc_archmage_landalock::npc_archmage_landalockAI::_switchImageTimer private
Definition at line 398 of file zone_dalaran.cpp.
Referenced by npc_archmage_landalockAI(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/zone_dalaran.cpp