Azerotcore-wotlk: server_commandscript Class Reference
server_commandscript Class Reference
Public Member Functions
server_commandscript ()
ChatCommandTable GetCommands () const override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Static Public Member Functions
static bool HandleServerCorpsesCommand (ChatHandler *)
static bool HandleServerDebugCommand (ChatHandler *handler)
static bool HandleServerInfoCommand (ChatHandler *handler)
static bool HandleServerMotdCommand (ChatHandler *handler)
static bool HandleServerShutDownCancelCommand (ChatHandler *)
static bool HandleServerShutDownCommand (ChatHandler *, int32 time, Optional< int32 > exitCode)
static bool HandleServerRestartCommand (ChatHandler *, int32 time, Optional< int32 > exitCode)
static bool HandleServerIdleRestartCommand (ChatHandler *, int32 time, Optional< int32 > exitCode)
static bool HandleServerIdleShutDownCommand (ChatHandler *, int32 time, Optional< int32 > exitCode)
static bool HandleServerExitCommand (ChatHandler *handler)
static bool HandleServerSetMotdCommand (ChatHandler *handler, std::string motd)
static bool HandleServerSetClosedCommand (ChatHandler *handler, Optional< std::string > args)
static bool HandleServerSetLogLevelCommand (ChatHandler *, bool isLogger, std::string const &name, int32 level)
static bool HandleServerSetDiffTimeCommand (ChatHandler *, int32 newTime)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 46 of file cs_server.cpp.
Constructor & Destructor Documentation
server_commandscript()
server_commandscript::server_commandscript () inline
Definition at line 49 of file cs_server.cpp.
 : CommandScript("server_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable server_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
Definition at line 51 of file cs_server.cpp.
     {
         static ChatCommandTable serverIdleRestartCommandTable =
         {
             { "cancel",       HandleServerShutDownCancelCommand, SEC_ADMINISTRATOR, Console::Yes },
             { "",             HandleServerIdleRestartCommand,    SEC_CONSOLE,       Console::Yes }
         };
         static ChatCommandTable serverIdleShutdownCommandTable =
         {
             { "cancel",       HandleServerShutDownCancelCommand, SEC_ADMINISTRATOR, Console::Yes },
             { "",             HandleServerIdleShutDownCommand,   SEC_CONSOLE,       Console::Yes }
         };
         static ChatCommandTable serverRestartCommandTable =
         {
             { "cancel",       HandleServerShutDownCancelCommand, SEC_ADMINISTRATOR, Console::Yes },
             { "",             HandleServerRestartCommand,        SEC_ADMINISTRATOR, Console::Yes }
         };
         static ChatCommandTable serverShutdownCommandTable =
         {
             { "cancel",       HandleServerShutDownCancelCommand, SEC_ADMINISTRATOR, Console::Yes },
             { "",             HandleServerShutDownCommand,       SEC_ADMINISTRATOR, Console::Yes }
         };
         static ChatCommandTable serverSetCommandTable =
         {
             { "difftime",     HandleServerSetDiffTimeCommand,    SEC_CONSOLE,       Console::Yes },
             { "loglevel",     HandleServerSetLogLevelCommand,    SEC_CONSOLE,       Console::Yes },
             { "motd",         HandleServerSetMotdCommand,        SEC_ADMINISTRATOR, Console::Yes },
             { "closed",       HandleServerSetClosedCommand,      SEC_CONSOLE,       Console::Yes },
         };
         static ChatCommandTable serverCommandTable =
         {
             { "corpses",      HandleServerCorpsesCommand,        SEC_GAMEMASTER,    Console::Yes },
             { "debug",        HandleServerDebugCommand,          SEC_ADMINISTRATOR, Console::Yes },
             { "exit",         HandleServerExitCommand,           SEC_CONSOLE,       Console::Yes },
             { "idlerestart",  serverIdleRestartCommandTable },
             { "idleshutdown", serverIdleShutdownCommandTable },
             { "info",         HandleServerInfoCommand,           SEC_PLAYER,        Console::Yes },
             { "motd",         HandleServerMotdCommand,           SEC_PLAYER,        Console::Yes },
             { "restart",      serverRestartCommandTable },
             { "shutdown",     serverShutdownCommandTable },
             { "set",          serverSetCommandTable }
         };
         static ChatCommandTable commandTable =
         {
             { "server", serverCommandTable }
         };
         return commandTable;
     }
References SEC_ADMINISTRATOR, SEC_CONSOLE, SEC_GAMEMASTER, SEC_PLAYER, and Acore::ChatCommands::Yes.
HandleServerCorpsesCommand()
static bool server_commandscript::HandleServerCorpsesCommand (ChatHandler *) inline static
Definition at line 108 of file cs_server.cpp.
     {
         sWorld->RemoveOldCorpses();
         return true;
     }
References sWorld.
HandleServerDebugCommand()
static bool server_commandscript::HandleServerDebugCommand (ChatHandler * handler) inline static
Definition at line 114 of file cs_server.cpp.
     {
         uint16 worldPort = uint16(sWorld->getIntConfig(CONFIG_PORT_WORLD));
         std::string dbPortOutput;
         {
             uint16 dbPort = 0;
             if (QueryResult res = LoginDatabase.PQuery("SELECT port FROM realmlist WHERE id = %u", realm.Id.Realm))
                 dbPort = (*res)[0].GetUInt16();
             if (dbPort)
                 dbPortOutput = Acore::StringFormat("Realmlist (Realm Id: %u) configured in port %" PRIu16, realm.Id.Realm, dbPort);
             else
                 dbPortOutput = Acore::StringFormat("Realm Id: %u not found in `realmlist` table. Please check your setup", realm.Id.Realm);
         }
         handler->PSendSysMessage("%s", GitRevision::GetFullVersion());
         handler->PSendSysMessage("Using SSL version: %s (library: %s)", OPENSSL_VERSION_TEXT, SSLeay_version(SSLEAY_VERSION));
         handler->PSendSysMessage("Using Boost version: %i.%i.%i", BOOST_VERSION / 100000, BOOST_VERSION / 100 % 1000, BOOST_VERSION % 100);
         handler->PSendSysMessage("Using MySQL version: %u", MySQL::GetLibraryVersion());
         handler->PSendSysMessage("Using CMake version: %s", GitRevision::GetCMakeVersion());
         handler->PSendSysMessage("Compiled on: %s", GitRevision::GetHostOSVersion());
         handler->PSendSysMessage("Worldserver listening connections on port %" PRIu16, worldPort);
         handler->PSendSysMessage("%s", dbPortOutput.c_str());
         bool vmapIndoorCheck = sWorld->getBoolConfig(CONFIG_VMAP_INDOOR_CHECK);
         bool vmapLOSCheck = VMAP::VMapFactory::createOrGetVMapMgr()->isLineOfSightCalcEnabled();
         bool vmapHeightCheck = VMAP::VMapFactory::createOrGetVMapMgr()->isHeightCalcEnabled();
         bool mmapEnabled = sWorld->getBoolConfig(CONFIG_ENABLE_MMAPS);
         std::string dataDir = sWorld->GetDataPath();
         std::vector<std::string> subDirs;
         subDirs.emplace_back("maps");
         if (vmapIndoorCheck || vmapLOSCheck || vmapHeightCheck)
         {
             handler->PSendSysMessage("VMAPs status: Enabled. LineOfSight: %i, getHeight: %i, indoorCheck: %i", vmapLOSCheck, vmapHeightCheck, vmapIndoorCheck);
             subDirs.emplace_back("vmaps");
         }
         else
             handler->SendSysMessage("VMAPs status: Disabled");
         if (mmapEnabled)
         {
             handler->SendSysMessage("MMAPs status: Enabled");
             subDirs.emplace_back("mmaps");
         }
         else
             handler->SendSysMessage("MMAPs status: Disabled");
         for (std::string const& subDir : subDirs)
         {
             std::filesystem::path mapPath(dataDir);
             mapPath /= subDir;
             if (!std::filesystem::exists(mapPath))
             {
                 handler->PSendSysMessage("%s directory doesn't exist!. Using path: %s", subDir.c_str(), mapPath.generic_string().c_str());
                 continue;
             }
             auto end = std::filesystem::directory_iterator();
             std::size_t folderSize = std::accumulate(std::filesystem::directory_iterator(mapPath), end, std::size_t(0), [](std::size_t val, std::filesystem::path const& mapFile)
             {
                 if (std::filesystem::is_regular_file(mapFile))
                     val += std::filesystem::file_size(mapFile);
                 return val;
             });
             handler->PSendSysMessage("%s directory located in %s. Total size: " SZFMTD " bytes", subDir.c_str(), mapPath.generic_string().c_str(), folderSize);
         }
         LocaleConstant defaultLocale = sWorld->GetDefaultDbcLocale();
         uint32 availableLocalesMask = (1 << defaultLocale);
         for (uint8 i = 0; i < TOTAL_LOCALES; ++i)
         {
             LocaleConstant locale = static_cast<LocaleConstant>(i);
             if (locale == defaultLocale)
                 continue;
             if (sWorld->GetAvailableDbcLocale(locale) != defaultLocale)
                 availableLocalesMask |= (1 << locale);
         }
         std::string availableLocales;
         for (uint8 i = 0; i < TOTAL_LOCALES; ++i)
         {
             if (!(availableLocalesMask & (1 << i)))
                 continue;
             availableLocales += localeNames[i];
             if (i != TOTAL_LOCALES - 1)
                 availableLocales += " ";
         }
         handler->PSendSysMessage("Using %s DBC Locale as default. All available DBC locales: %s", localeNames[defaultLocale], availableLocales.c_str());
         handler->PSendSysMessage("Using World DB: %s", sWorld->GetDBVersion());
         handler->PSendSysMessage("Using World DB Revision: %s", sWorld->GetWorldDBRevision());
         handler->PSendSysMessage("Using Character DB Revision: %s", sWorld->GetCharacterDBRevision());
         handler->PSendSysMessage("Using Auth DB Revision: %s", sWorld->GetAuthDBRevision());
         handler->PSendSysMessage("LoginDatabase queue size: %zu", LoginDatabase.QueueSize());
         handler->PSendSysMessage("CharacterDatabase queue size: %zu", CharacterDatabase.QueueSize());
         handler->PSendSysMessage("WorldDatabase queue size: %zu", WorldDatabase.QueueSize());
         return true;
     }
References CharacterDatabase, CONFIG_ENABLE_MMAPS, CONFIG_PORT_WORLD, CONFIG_VMAP_INDOOR_CHECK, VMAP::VMapFactory::createOrGetVMapMgr(), GitRevision::GetCMakeVersion(), GitRevision::GetFullVersion(), GitRevision::GetHostOSVersion(), MySQL::GetLibraryVersion(), Realm::Id, VMAP::IVMapMgr::isHeightCalcEnabled(), VMAP::IVMapMgr::isLineOfSightCalcEnabled(), localeNames, LoginDatabase, ChatHandler::PSendSysMessage(), realm, RealmHandle::Realm, ChatHandler::SendSysMessage(), Acore::StringFormat(), sWorld, SZFMTD, TOTAL_LOCALES, and WorldDatabase.
HandleServerExitCommand()
static bool server_commandscript::HandleServerExitCommand (ChatHandler * handler) inline static
Definition at line 327 of file cs_server.cpp.
     {
         handler->SendSysMessage(LANG_COMMAND_EXIT);
         World::StopNow(SHUTDOWN_EXIT_CODE);
         return true;
     }
References LANG_COMMAND_EXIT, ChatHandler::SendSysMessage(), SHUTDOWN_EXIT_CODE, and World::StopNow().
HandleServerIdleRestartCommand()
static bool server_commandscript::HandleServerIdleRestartCommand (ChatHandler * , int32 time, Optional< int32 > exitCode) inline static
Definition at line 298 of file cs_server.cpp.
     {
         if (exitCode && *exitCode >= 0 && *exitCode <= 125)
         {
             sWorld->ShutdownServ(time, SHUTDOWN_MASK_RESTART | SHUTDOWN_MASK_IDLE, *exitCode);
         }
         else
         {
             sWorld->ShutdownServ(time, SHUTDOWN_MASK_RESTART | SHUTDOWN_MASK_IDLE, RESTART_EXIT_CODE);
         }
         return true;
     }
References RESTART_EXIT_CODE, SHUTDOWN_MASK_IDLE, SHUTDOWN_MASK_RESTART, and sWorld.
HandleServerIdleShutDownCommand()
static bool server_commandscript::HandleServerIdleShutDownCommand (ChatHandler * , int32 time, Optional< int32 > exitCode) inline static
Definition at line 312 of file cs_server.cpp.
     {
         if (exitCode && *exitCode >= 0 && *exitCode <= 125)
         {
             sWorld->ShutdownServ(time, SHUTDOWN_MASK_IDLE, *exitCode);
         }
         else
         {
             sWorld->ShutdownServ(time, SHUTDOWN_MASK_IDLE, SHUTDOWN_EXIT_CODE);
         }
         return true;
     }
References SHUTDOWN_EXIT_CODE, SHUTDOWN_MASK_IDLE, and sWorld.
HandleServerInfoCommand()
static bool server_commandscript::HandleServerInfoCommand (ChatHandler * handler) inline static
Can't use sWorld->ShutdownMsg here in case of console command
Definition at line 225 of file cs_server.cpp.
     {
         std::string realmName = sWorld->GetRealmName();
         uint32 playerCount = sWorld->GetPlayerCount();
         uint32 activeSessionCount = sWorld->GetActiveSessionCount();
         uint32 queuedSessionCount = sWorld->GetQueuedSessionCount();
         uint32 connPeak = sWorld->GetMaxActiveSessionCount();
         std::string uptime = secsToTimeString(sWorld->GetUptime()).append(".");
         uint32 updateTime = sWorld->GetUpdateTime();
         uint32 avgUpdateTime = avgDiffTracker.getAverage();
         handler->PSendSysMessage("%s", GitRevision::GetFullVersion());
         if (!queuedSessionCount)
             handler->PSendSysMessage("Connected players: %u. Characters in world: %u.", activeSessionCount, playerCount);
         else
             handler->PSendSysMessage("Connected players: %u. Characters in world: %u. Queue: %u.", activeSessionCount, playerCount, queuedSessionCount);
         handler->PSendSysMessage("Connection peak: %u.", connPeak);
         handler->PSendSysMessage(LANG_UPTIME, uptime.c_str());
         handler->PSendSysMessage("Update time diff: %ums, average: %ums.", updateTime, avgUpdateTime);
         if (handler->GetSession())
             if (Player* p = handler->GetSession()->GetPlayer())
                 if (p->IsDeveloper())
                     handler->PSendSysMessage("DEV wavg: %ums, nsmax: %ums, nsavg: %ums. LFG avg: %ums, max: %ums.", avgDiffTracker.getTimeWeightedAverage(), devDiffTracker.getMax(), devDiffTracker.getAverage(), lfgDiffTracker.getAverage(), lfgDiffTracker.getMax());
         if (sWorld->IsShuttingDown())
             handler->PSendSysMessage(LANG_SHUTDOWN_TIMELEFT, secsToTimeString(sWorld->GetShutDownTimeLeft()).append(".").c_str());
         return true;
     }
References avgDiffTracker, devDiffTracker, AvgDiffTracker::getAverage(), GitRevision::GetFullVersion(), AvgDiffTracker::getMax(), WorldSession::GetPlayer(), ChatHandler::GetSession(), AvgDiffTracker::getTimeWeightedAverage(), LANG_SHUTDOWN_TIMELEFT, LANG_UPTIME, lfgDiffTracker, ChatHandler::PSendSysMessage(), secsToTimeString(), and sWorld.
HandleServerMotdCommand()
static bool server_commandscript::HandleServerMotdCommand (ChatHandler * handler) inline static
Definition at line 257 of file cs_server.cpp.
     {
         handler->PSendSysMessage(LANG_MOTD_CURRENT, Motd::GetMotd());
         return true;
     }
References Motd::GetMotd(), LANG_MOTD_CURRENT, and ChatHandler::PSendSysMessage().
HandleServerRestartCommand()
static bool server_commandscript::HandleServerRestartCommand (ChatHandler * , int32 time, Optional< int32 > exitCode) inline static
Definition at line 284 of file cs_server.cpp.
     {
         if (exitCode && *exitCode >= 0 && *exitCode <= 125)
         {
             sWorld->ShutdownServ(time, SHUTDOWN_MASK_RESTART, *exitCode);
         }
         else
         {
             sWorld->ShutdownServ(time, SHUTDOWN_MASK_RESTART, RESTART_EXIT_CODE);
         }
         return true;
     }
References RESTART_EXIT_CODE, SHUTDOWN_MASK_RESTART, and sWorld.
HandleServerSetClosedCommand()
static bool server_commandscript::HandleServerSetClosedCommand (ChatHandler * handler, Optional< std::string > args) inline static
Definition at line 343 of file cs_server.cpp.
     {
         if (StringStartsWith("on", *args))
         {
             handler->SendSysMessage(LANG_WORLD_CLOSED);
             sWorld->SetClosed(true);
             return true;
         }
         else if (StringStartsWith("off", *args))
         {
             handler->SendSysMessage(LANG_WORLD_OPENED);
             sWorld->SetClosed(false);
             return true;
         }
         handler->SendSysMessage(LANG_USE_BOL);
         handler->SetSentErrorMessage(true);
         return false;
     }
References LANG_USE_BOL, LANG_WORLD_CLOSED, LANG_WORLD_OPENED, ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), StringStartsWith(), and sWorld.
HandleServerSetDiffTimeCommand()
static bool server_commandscript::HandleServerSetDiffTimeCommand (ChatHandler * , int32 newTime) inline static
Definition at line 371 of file cs_server.cpp.
     {
         if (newTime < 0)
             return false;
         sWorld->SetRecordDiffInterval(newTime);
         printf("Record diff every %u ms\n", newTime);
         return true;
     }
References sWorld.
HandleServerSetLogLevelCommand()
static bool server_commandscript::HandleServerSetLogLevelCommand (ChatHandler * , bool isLogger, std::string const & name, int32 level) inline static
Definition at line 364 of file cs_server.cpp.
     {
         sLog->SetLogLevel(name, level, isLogger);
         return true;
     }
References sLog.
HandleServerSetMotdCommand()
static bool server_commandscript::HandleServerSetMotdCommand (ChatHandler * handler, std::string motd) inline static
Definition at line 335 of file cs_server.cpp.
     {
         Motd::SetMotd(motd);
         handler->PSendSysMessage(LANG_MOTD_NEW, motd);
         return true;
     }
References LANG_MOTD_NEW, ChatHandler::PSendSysMessage(), and Motd::SetMotd().
HandleServerShutDownCancelCommand()
static bool server_commandscript::HandleServerShutDownCancelCommand (ChatHandler *) inline static
Definition at line 263 of file cs_server.cpp.
     {
         sWorld->ShutdownCancel();
         return true;
     }
References sWorld.
HandleServerShutDownCommand()
static bool server_commandscript::HandleServerShutDownCommand (ChatHandler * , int32 time, Optional< int32 > exitCode) inline static
Definition at line 270 of file cs_server.cpp.
     {
         if (exitCode && *exitCode >= 0 && *exitCode <= 125)
         {
             sWorld->ShutdownServ(time, 0, *exitCode);
         }
         else
         {
             sWorld->ShutdownServ(time, 0, SHUTDOWN_EXIT_CODE);
         }
         return true;
     }
References SHUTDOWN_EXIT_CODE, and sWorld.
The documentation for this class was generated from the following file:
src/server/scripts/Commands/cs_server.cpp