Azerotcore-wotlk: Cell Struct Reference
Cell Struct Reference
#include <Cell.h>
Public Member Functions
Cell ()
Cell (Cell const &cell)
Cell (CellCoord const &p)
Cell (float x, float y)
void Compute (uint32 &x, uint32 &y) const
bool DiffCell (const Cell &cell) const
bool DiffGrid (const Cell &cell) const
uint32 CellX () const
uint32 CellY () const
uint32 GridX () const
uint32 GridY () const
bool NoCreate () const
void SetNoCreate ()
CellCoord GetCellCoord () const
Cell & operator= (Cell const &cell)
bool operator== (Cell const &cell) const
bool operator!= (Cell const &cell) const
template<class T , class CONTAINER >
void Visit (CellCoord const &, TypeContainerVisitor< T, CONTAINER > &visitor, Map &, WorldObject const &obj, float radius) const
template<class T , class CONTAINER >
void Visit (CellCoord const &, TypeContainerVisitor< T, CONTAINER > &visitor, Map &, float x, float y, float radius) const
Static Public Member Functions
static CellArea CalculateCellArea (float x, float y, float radius)
template<class T >
static void VisitGridObjects (WorldObject const *obj, T &visitor, float radius, bool dont_load=true)
template<class T >
static void VisitWorldObjects (WorldObject const *obj, T &visitor, float radius, bool dont_load=true)
template<class T >
static void VisitAllObjects (WorldObject const *obj, T &visitor, float radius, bool dont_load=true)
template<class T >
static void VisitGridObjects (float x, float y, Map *map, T &visitor, float radius, bool dont_load=true)
template<class T >
static void VisitWorldObjects (float x, float y, Map *map, T &visitor, float radius, bool dont_load=true)
template<class T >
static void VisitAllObjects (float x, float y, Map *map, T &visitor, float radius, bool dont_load=true)
Public Attributes
union {
struct {
unsigned grid_x: 6
unsigned grid_y: 6
unsigned cell_x: 6
unsigned cell_y: 6
unsigned nocreate: 1
unsigned reserved: 7
} Part
uint32 All
} data
float v9 [16 *8+1][16 *8+1]
float v8 [16 *8][16 *8]
Private Member Functions
template<class T , class CONTAINER >
void VisitCircle (TypeContainerVisitor< T, CONTAINER > &, Map &, CellCoord const &, CellCoord const &) const
Detailed Description
Definition at line 45 of file Cell.h.
Constructor & Destructor Documentation
Cell() [1/4]
Cell::Cell () inline
Definition at line 47 of file Cell.h.
 { data.All = 0; }
Cell() [2/4]
Cell::Cell (Cell const & cell) inline
Definition at line 48 of file Cell.h.
 { data.All = cell.data.All; }
References All, and data.
Cell() [3/4]
Cell::Cell (CellCoord const & p) inline explicit
Definition at line 26 of file CellImpl.h.
 {
     data.Part.grid_x = p.x_coord / MAX_NUMBER_OF_CELLS;
     data.Part.grid_y = p.y_coord / MAX_NUMBER_OF_CELLS;
     data.Part.cell_x = p.x_coord % MAX_NUMBER_OF_CELLS;
     data.Part.cell_y = p.y_coord % MAX_NUMBER_OF_CELLS;
     data.Part.nocreate = 0;
     data.Part.reserved = 0;
 }
References MAX_NUMBER_OF_CELLS, CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Cell() [4/4]
Cell::Cell (float x, float y) inline explicit
Definition at line 36 of file CellImpl.h.
 {
     CellCoord p = Acore::ComputeCellCoord(x, y);
     data.Part.grid_x = p.x_coord / MAX_NUMBER_OF_CELLS;
     data.Part.grid_y = p.y_coord / MAX_NUMBER_OF_CELLS;
     data.Part.cell_x = p.x_coord % MAX_NUMBER_OF_CELLS;
     data.Part.cell_y = p.y_coord % MAX_NUMBER_OF_CELLS;
     data.Part.nocreate = 0;
     data.Part.reserved = 0;
 }
References Acore::ComputeCellCoord(), MAX_NUMBER_OF_CELLS, G3D::x, CoordPair< LIMIT >::x_coord, G3D::y, and CoordPair< LIMIT >::y_coord.
Member Function Documentation
CalculateCellArea()
CellArea Cell::CalculateCellArea (float x, float y, float radius) inline static
Definition at line 47 of file CellImpl.h.
 {
     if (radius <= 0.0f)
     {
         CellCoord center = Acore::ComputeCellCoord(x, y).normalize();
         return CellArea(center, center);
     }
     CellCoord centerX = Acore::ComputeCellCoord(x - radius, y - radius).normalize();
     CellCoord centerY = Acore::ComputeCellCoord(x + radius, y + radius).normalize();
     return CellArea(centerX, centerY);
 }
References align::center, Acore::ComputeCellCoord(), CoordPair< LIMIT >::normalize(), G3D::x, and G3D::y.
Referenced by Visit(), Map::VisitNearbyCellsOf(), and Map::VisitNearbyCellsOfPlayer().
CellX()
uint32 Cell::CellX () const inline
Definition at line 70 of file Cell.h.
 { return data.Part.cell_x; }
Referenced by Map::AddToGrid(), GridMap::getMinHeight(), misc_commandscript::HandleGPSCommand(), Map::SwitchGridContainers(), Map::Visit(), and ObjectWorldLoader::Visit().
CellY()
uint32 Cell::CellY () const inline
Definition at line 71 of file Cell.h.
 { return data.Part.cell_y; }
Referenced by Map::AddToGrid(), GridMap::getMinHeight(), misc_commandscript::HandleGPSCommand(), Map::SwitchGridContainers(), Map::Visit(), and ObjectWorldLoader::Visit().
Compute()
void Cell::Compute (uint32 & x, uint32 & y) const inline
Definition at line 52 of file Cell.h.
     {
         x = data.Part.grid_x * MAX_NUMBER_OF_CELLS + data.Part.cell_x;
         y = data.Part.grid_y * MAX_NUMBER_OF_CELLS + data.Part.cell_y;
     }
References MAX_NUMBER_OF_CELLS, G3D::x, and G3D::y.
DiffCell()
bool Cell::DiffCell (const Cell & cell) const inline
Definition at line 58 of file Cell.h.
     {
         return(data.Part.cell_x != cell.data.Part.cell_x ||
                data.Part.cell_y != cell.data.Part.cell_y);
     }
References data, and Part.
Referenced by Map::CreatureRelocation(), Map::DynamicObjectRelocation(), Map::GameObjectRelocation(), and Map::PlayerRelocation().
DiffGrid()
bool Cell::DiffGrid (const Cell & cell) const inline
Definition at line 64 of file Cell.h.
     {
         return(data.Part.grid_x != cell.data.Part.grid_x ||
                data.Part.grid_y != cell.data.Part.grid_y);
     }
References data, and Part.
Referenced by Map::CreatureRelocation(), Map::DynamicObjectRelocation(), Map::GameObjectRelocation(), Map::MoveAllCreaturesInMoveList(), Map::MoveAllDynamicObjectsInMoveList(), Map::MoveAllGameObjectsInMoveList(), and Map::PlayerRelocation().
GetCellCoord()
CellCoord Cell::GetCellCoord () const inline
Definition at line 77 of file Cell.h.
     {
         return CellCoord(
                    data.Part.grid_x * MAX_NUMBER_OF_CELLS + data.Part.cell_x,
                    data.Part.grid_y * MAX_NUMBER_OF_CELLS + data.Part.cell_y);
     }
References MAX_NUMBER_OF_CELLS.
Referenced by ObjectWorldLoader::Visit(), and ObjectGridLoader::Visit().
GridX()
uint32 Cell::GridX () const inline
Definition at line 72 of file Cell.h.
 { return data.Part.grid_x; }
Referenced by Map::AddToGrid(), Map::AddToMap(), Map::EnsureGridLoaded(), GridMap::getMinHeight(), misc_commandscript::HandleGPSCommand(), WorldSession::HandleMoveWorldportAck(), Map::SwitchGridContainers(), and Map::Visit().
GridY()
uint32 Cell::GridY () const inline
Definition at line 73 of file Cell.h.
 { return data.Part.grid_y; }
Referenced by Map::AddToGrid(), Map::AddToMap(), Map::EnsureGridLoaded(), GridMap::getMinHeight(), misc_commandscript::HandleGPSCommand(), WorldSession::HandleMoveWorldportAck(), Map::SwitchGridContainers(), and Map::Visit().
NoCreate()
bool Cell::NoCreate () const inline
Definition at line 74 of file Cell.h.
 { return data.Part.nocreate; }
Referenced by Map::Visit().
operator!=()
bool Cell::operator!= (Cell const & cell) const inline
Definition at line 91 of file Cell.h.
 { return !operator == (cell); }
References operator==().
operator=()
Cell& Cell::operator= (Cell const & cell) inline
Definition at line 84 of file Cell.h.
     {
         this->data.All = cell.data.All;
         return *this;
     }
References All, and data.
operator==()
bool Cell::operator== (Cell const & cell) const inline
Definition at line 90 of file Cell.h.
 { return (data.All == cell.data.All); }
References All, and data.
Referenced by operator!=().
SetNoCreate()
void Cell::SetNoCreate () inline
Definition at line 75 of file Cell.h.
 { data.Part.nocreate = 1; }
Referenced by WorldObject::GetCreaturesWithEntryInRange(), misc_commandscript::HandleRespawnCommand(), WorldSession::HandleTextEmoteOpcode(), boss_nalorakk::boss_nalorakkAI::ResetMobs(), Spell::SearchTargets(), AchievementMgr::SendAchievementEarned(), boss_nalorakk::boss_nalorakkAI::SendAttacker(), VisitAllObjects(), VisitGridObjects(), and VisitWorldObjects().
Visit() [1/2]
template<class T , class CONTAINER > void Cell::Visit (CellCoord const & standing_cell, TypeContainerVisitor< T, CONTAINER > & visitor, Map & map, float x, float y, float radius) const inline
Definition at line 70 of file CellImpl.h.
{
     if (!standing_cell.IsCoordValid())
         return;
     // no jokes here... Actually placing ASSERT() here was good idea, but
     // we had some problems with DynamicObjects, which pass radius = 0.0f (DB issue?)
     // maybe it is better to just return when radius <= 0.0f?
     if (radius <= 0.0f)
     {
         map.Visit(*this, visitor);
         return;
     }
     //lets limit the upper value for search radius
     if (radius > SIZE_OF_GRIDS)
         radius = SIZE_OF_GRIDS;
     //lets calculate object coord offsets from cell borders.
     CellArea area = Cell::CalculateCellArea(x_off, y_off, radius);
     //if radius fits inside standing cell
     if (!area)
     {
         map.Visit(*this, visitor);
         return;
     }
     //visit all cells, found in CalculateCellArea()
     //if radius is known to reach cell area more than 4x4 then we should call optimized VisitCircle
     //currently this technique works with MAX_NUMBER_OF_CELLS 16 and higher, with lower values
     //there are nothing to optimize because SIZE_OF_GRID_CELL is too big...
     if ((area.high_bound.x_coord > (area.low_bound.x_coord + 4)) && (area.high_bound.y_coord > (area.low_bound.y_coord + 4)))
     {
         VisitCircle(visitor, map, area.low_bound, area.high_bound);
         return;
     }
     //ALWAYS visit standing cell first!!! Since we deal with small radiuses
     //it is very essential to call visitor for standing cell firstly...
     map.Visit(*this, visitor);
     // loop the cell range
     for (uint32 x = area.low_bound.x_coord; x <= area.high_bound.x_coord; ++x)
     {
         for (uint32 y = area.low_bound.y_coord; y <= area.high_bound.y_coord; ++y)
         {
             CellCoord cellCoord(x, y);
             //lets skip standing cell since we already visited it
             if (cellCoord != standing_cell)
             {
                 Cell r_zone(cellCoord);
                 r_zone.data.Part.nocreate = this->data.Part.nocreate;
                 map.Visit(r_zone, visitor);
             }
         }
     }
 }
References CalculateCellArea(), data, CellArea::high_bound, CoordPair< LIMIT >::IsCoordValid(), CellArea::low_bound, Part, SIZE_OF_GRIDS, Map::Visit(), VisitCircle(), G3D::x, CoordPair< LIMIT >::x_coord, G3D::y, and CoordPair< LIMIT >::y_coord.
Visit() [2/2]
template<class T , class CONTAINER > void Cell::Visit (CellCoord const & standing_cell, TypeContainerVisitor< T, CONTAINER > & visitor, Map & map, WorldObject const & obj, float radius) const inline
Definition at line 62 of file CellImpl.h.
 {
     //we should increase search radius by object's radius, otherwise
     //we could have problems with huge creatures, which won't attack nearest players etc
     Visit(standing_cell, visitor, map, obj.GetPositionX(), obj.GetPositionY(), radius + obj.GetCombatReach());
 }
References WorldObject::GetCombatReach(), Position::GetPositionX(), and Position::GetPositionY().
Referenced by Spell::CheckSpellFocus(), WorldObject::GetCreaturesWithEntryInRange(), WorldSession::HandleTextEmoteOpcode(), boss_nalorakk::boss_nalorakkAI::ResetMobs(), boss_nalorakk::boss_nalorakkAI::SendAttacker(), VisitAllObjects(), VisitGridObjects(), and VisitWorldObjects().
VisitAllObjects() [1/2]
template<class T > void Cell::VisitAllObjects (float x, float y, Map * map, T & visitor, float radius, bool dont_load = true) inline static
Definition at line 251 of file CellImpl.h.
 {
     CellCoord p(Acore::ComputeCellCoord(x, y));
     Cell cell(p);
     if (dont_load)
     {
         cell.SetNoCreate();
     }
     TypeContainerVisitor<T, WorldTypeMapContainer> wnotifier(visitor);
     cell.Visit(p, wnotifier, *map, x, y, radius);
     TypeContainerVisitor<T, GridTypeMapContainer> gnotifier(visitor);
     cell.Visit(p, gnotifier, *map, x, y, radius);
 }
References Acore::ComputeCellCoord(), SetNoCreate(), Visit(), G3D::x, and G3D::y.
VisitAllObjects() [2/2]
template<class T > void Cell::VisitAllObjects (WorldObject const * obj, T & visitor, float radius, bool dont_load = true) inline static
Definition at line 207 of file CellImpl.h.
 {
     CellCoord p(Acore::ComputeCellCoord(center_obj->GetPositionX(), center_obj->GetPositionY()));
     Cell cell(p);
     if (dont_load)
     {
         cell.SetNoCreate();
     }
     TypeContainerVisitor<T, WorldTypeMapContainer> wnotifier(visitor);
     cell.Visit(p, wnotifier, *center_obj->GetMap(), *center_obj, radius);
     TypeContainerVisitor<T, GridTypeMapContainer> gnotifier(visitor);
     cell.Visit(p, gnotifier, *center_obj->GetMap(), *center_obj, radius);
 }
References Acore::ComputeCellCoord(), WorldObject::GetMap(), Position::GetPositionX(), Position::GetPositionY(), SetNoCreate(), and Visit().
Referenced by SmartScript::DoFindClosestFriendlyInRange(), ScriptedAI::DoFindFriendlyCC(), ScriptedAI::DoFindFriendlyMissingBuff(), ScriptedAI::DoSelectLowestHpFriendly(), Spell::EffectForceDeselect(), Spell::EffectSanctuary(), Unit::ExecuteDelayedUnitAINotifyEvent(), Unit::ExecuteDelayedUnitRelocationEvent(), UnitAura::FillTargetMap(), DynObjAura::FillTargetMap(), WorldObject::FindNearestCreature(), SmartScript::GetWorldObjectsInDist(), debug_commandscript::HandleDebugEnterVehicleCommand(), AuraEffect::HandleFeignDeath(), spell_zulfarrak_unlocking::spell_zulfarrak_unlocking_SpellScript::HandleOpenLock(), AuraEffect::HandleRaidProcFromChargeWithValueAuraProc(), spell_vehicle_throw_passenger::spell_vehicle_throw_passenger_SpellScript::HandleScript(), boss_akilzon::boss_akilzonAI::HandleStormSequence(), Unit::SelectNearbyNoTotemTarget(), Unit::SelectNearbyTarget(), Creature::SelectNearestTarget(), Creature::SelectNearestTargetInAttackDistance(), Unit::SetContestedPvP(), npc_simon_bunny::npc_simon_bunnyAI::StartGame(), GameObject::Update(), TotemAI::UpdateAI(), npc_belnistrasz::npc_belnistraszAI::UpdateAI(), boss_naxxramas_misc::boss_naxxramas_miscAI::UpdateAI(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::UpdateAI(), Unit::UpdateObjectVisibility(), and Player::UpdateVisibilityForPlayer().
VisitCircle()
template<class T , class CONTAINER > void Cell::VisitCircle (TypeContainerVisitor< T, CONTAINER > & visitor, Map & map, CellCoord const & begin_cell, CellCoord const & end_cell) const inline private
Definition at line 127 of file CellImpl.h.
 {
     //here is an algorithm for 'filling' circum-squared octagon
     uint32 x_shift = (uint32)ceilf((end_cell.x_coord - begin_cell.x_coord) * 0.3f - 0.5f);
     //lets calculate x_start/x_end coords for central strip...
     const uint32 x_start = begin_cell.x_coord + x_shift;
     const uint32 x_end = end_cell.x_coord - x_shift;
     //visit central strip with constant width...
     for (uint32 x = x_start; x <= x_end; ++x)
     {
         for (uint32 y = begin_cell.y_coord; y <= end_cell.y_coord; ++y)
         {
             CellCoord cellCoord(x, y);
             Cell r_zone(cellCoord);
             r_zone.data.Part.nocreate = this->data.Part.nocreate;
             map.Visit(r_zone, visitor);
         }
     }
     //if x_shift == 0 then we have too small cell area, which were already
     //visited at previous step, so just return from procedure...
     if (x_shift == 0)
         return;
     uint32 y_start = end_cell.y_coord;
     uint32 y_end = begin_cell.y_coord;
     //now we are visiting borders of an octagon...
     for (uint32 step = 1; step <= (x_start - begin_cell.x_coord); ++step)
     {
         //each step reduces strip height by 2 cells...
         y_end += 1;
         y_start -= 1;
         for (uint32 y = y_start; y >= y_end; --y)
         {
             //we visit cells symmetrically from both sides, heading from center to sides and from up to bottom
             //e.g. filling 2 trapezoids after filling central cell strip...
             CellCoord cellCoord_left(x_start - step, y);
             Cell r_zone_left(cellCoord_left);
             r_zone_left.data.Part.nocreate = this->data.Part.nocreate;
             map.Visit(r_zone_left, visitor);
             //right trapezoid cell visit
             CellCoord cellCoord_right(x_end + step, y);
             Cell r_zone_right(cellCoord_right);
             r_zone_right.data.Part.nocreate = this->data.Part.nocreate;
             map.Visit(r_zone_right, visitor);
         }
     }
 }
References data, Part, Map::Visit(), G3D::x, CoordPair< LIMIT >::x_coord, G3D::y, and CoordPair< LIMIT >::y_coord.
Referenced by Visit().
VisitGridObjects() [1/2]
template<class T > void Cell::VisitGridObjects (float x, float y, Map * map, T & visitor, float radius, bool dont_load = true) inline static
Definition at line 223 of file CellImpl.h.
 {
     CellCoord p(Acore::ComputeCellCoord(x, y));
     Cell cell(p);
     if (dont_load)
     {
         cell.SetNoCreate();
     }
     TypeContainerVisitor<T, GridTypeMapContainer> gnotifier(visitor);
     cell.Visit(p, gnotifier, *map, x, y, radius);
 }
References Acore::ComputeCellCoord(), SetNoCreate(), Visit(), G3D::x, and G3D::y.
VisitGridObjects() [2/2]
template<class T > void Cell::VisitGridObjects (WorldObject const * obj, T & visitor, float radius, bool dont_load = true) inline static
Definition at line 179 of file CellImpl.h.
 {
     CellCoord p(Acore::ComputeCellCoord(center_obj->GetPositionX(), center_obj->GetPositionY()));
     Cell cell(p);
     if (dont_load)
     {
         cell.SetNoCreate();
     }
     TypeContainerVisitor<T, GridTypeMapContainer> gnotifier(visitor);
     cell.Visit(p, gnotifier, *center_obj->GetMap(), *center_obj, radius);
 }
References Acore::ComputeCellCoord(), WorldObject::GetMap(), Position::GetPositionX(), Position::GetPositionY(), SetNoCreate(), and Visit().
Referenced by boss_janalai::boss_janalaiAI::Boom(), Creature::CallAssistance(), Creature::CallForHelp(), spell_gen_cannibalize::CheckIfCorpseNear(), spell_hun_pet_carrion_feeder::CheckIfCorpseNear(), npc_q24545_lich_king::npc_q24545_lich_kingAI::CleanAll(), SmartScript::DoFindFriendlyCC(), SmartScript::DoFindFriendlyMissingBuff(), Creature::DoFleeToGetAssistance(), hyjalAI::DoOverrun(), SmartScript::DoSelectLowestHpFriendly(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::EnterCombat(), ValithriaDespawner::Execute(), npc_captain_arnath::npc_captain_arnathAI::FindFriendlyCreature(), WorldObject::FindNearestGameObject(), WorldObject::FindNearestGameObjectOfType(), WorldObject::GetCreatureListWithEntryInGrid(), WorldObject::GetDeadCreatureListInGrid(), WorldObject::GetGameObjectListWithEntryInGrid(), ChatHandler::GetNearbyGameObject(), mmaps_commandscript::HandleMmapTestArea(), misc_commandscript::HandleRespawnCommand(), boss_janalai::boss_janalaiAI::HatchAllEggs(), npc_janalai_hatcher::npc_janalai_hatcherAI::HatchEggs(), hyjalAI::HideNearPos(), boss_the_lich_king::boss_the_lich_kingAI::JustReachedHome(), GameObject::LookupFishingHoleAround(), at_icc_start_frostwing_gauntlet::OnTrigger(), hyjalAI::RespawnNearPos(), Spell::SearchTargets(), npc_shadowpriest_sezziz::npc_shadowpriest_sezzizAI::UpdateAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI(), npc_q24545_lich_king::npc_q24545_lich_kingAI::UpdateAI(), hyjalAI::WaypointReached(), and npc_crok_scourgebane::npc_crok_scourgebaneAI::WaypointStart().
VisitWorldObjects() [1/2]
template<class T > void Cell::VisitWorldObjects (float x, float y, Map * map, T & visitor, float radius, bool dont_load = true) inline static
Definition at line 237 of file CellImpl.h.
 {
     CellCoord p(Acore::ComputeCellCoord(x, y));
     Cell cell(p);
     if (dont_load)
     {
         cell.SetNoCreate();
     }
     TypeContainerVisitor<T, WorldTypeMapContainer> wnotifier(visitor);
     cell.Visit(p, wnotifier, *map, x, y, radius);
 }
References Acore::ComputeCellCoord(), SetNoCreate(), Visit(), G3D::x, and G3D::y.
VisitWorldObjects() [2/2]
template<class T > void Cell::VisitWorldObjects (WorldObject const * obj, T & visitor, float radius, bool dont_load = true) inline static
Definition at line 193 of file CellImpl.h.
 {
     CellCoord p(Acore::ComputeCellCoord(center_obj->GetPositionX(), center_obj->GetPositionY()));
     Cell cell(p);
     if (dont_load)
     {
         cell.SetNoCreate();
     }
     TypeContainerVisitor<T, WorldTypeMapContainer> wnotifier(visitor);
     cell.Visit(p, wnotifier, *center_obj->GetMap(), *center_obj, radius);
 }
References Acore::ComputeCellCoord(), WorldObject::GetMap(), Position::GetPositionX(), Position::GetPositionY(), SetNoCreate(), and Visit().
Referenced by WorldObject::BuildUpdate(), npc_hallows_end_soh::npc_hallows_end_sohAI::CastFires(), spell_gen_cannibalize::CheckIfCorpseNear(), spell_hun_pet_carrion_feeder::CheckIfCorpseNear(), npc_hallows_end_soh::npc_hallows_end_sohAI::CompleteQuest(), WorldObject::DestroyForNearbyPlayers(), Spell::EffectForceDeselect(), ScriptedAI::GetPlayerAtMinimumRange(), AuraEffect::HandleAuraDummy(), spell_q11010_q11102_q11023_choose_loc::HandleDummy(), npc_clintar_spirit::npc_clintar_spiritAI::IsSummonedBy(), spell_love_is_in_the_air_romantic_picnic::spell_love_is_in_the_air_romantic_picnic_AuraScript::OnPeriodic(), Spell::SearchTargets(), WorldObject::SelectNearestPlayer(), AchievementMgr::SendAchievementEarned(), CreatureTextMgr::SendChatPacket(), Player::SendMessageToSetInRange(), WorldObject::SendMessageToSetInRange(), GameObject::SendMessageToSetInRange(), Player::SendMessageToSetInRange_OwnTeam(), Unit::Talk(), BfCapturePoint::Update(), OPvPCapturePoint::Update(), GameObject::Update(), npc_brewfest_super_brew_trigger::npc_brewfest_super_brew_triggerAI::UpdateAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI(), go_flames::go_flamesAI::UpdateAI(), go_heat::go_heatAI::UpdateAI(), and WorldObject::UpdateObjectVisibility().
Member Data Documentation
All
uint32 Cell::All
Definition at line 103 of file Cell.h.
Referenced by Cell(), operator=(), and operator==().
cell_x
unsigned Cell::cell_x
Definition at line 98 of file Cell.h.
cell_y
unsigned Cell::cell_y
Definition at line 99 of file Cell.h.
union { ... } Cell::data
Referenced by Cell(), DiffCell(), DiffGrid(), ObjectGridLoader::LoadN(), operator=(), operator==(), Map::SwitchGridContainers(), Visit(), and VisitCircle().
grid_x
unsigned Cell::grid_x
Definition at line 96 of file Cell.h.
grid_y
unsigned Cell::grid_y
Definition at line 97 of file Cell.h.
nocreate
unsigned Cell::nocreate
Definition at line 100 of file Cell.h.
struct { ... } Cell::Part
Referenced by DiffCell(), DiffGrid(), ObjectGridLoader::LoadN(), Map::SwitchGridContainers(), Visit(), and VisitCircle().
reserved
unsigned Cell::reserved
Definition at line 101 of file Cell.h.
v8
float Cell::v8[16 *8][16 *8]
Definition at line 53 of file adtfile.h.
v9
float Cell::v9[16 *8+1][16 *8+1]
Definition at line 52 of file adtfile.h.
The documentation for this struct was generated from the following files:
src/server/game/Grids/Cells/Cell.h
src/tools/vmap4_extractor/adtfile.h
src/server/game/Grids/Cells/CellImpl.h