Azerotcore-wotlk: UtherBatteredHiltEvent Class Reference
UtherBatteredHiltEvent Class Reference
Public Member Functions
UtherBatteredHiltEvent (Creature &owner, uint8 eventId)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()
virtual ~BasicEvent ()
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Creature & _owner
uint8 _eventId
Detailed Description
Definition at line 22 of file instance_halls_of_reflection.cpp.
Constructor & Destructor Documentation
UtherBatteredHiltEvent()
UtherBatteredHiltEvent::UtherBatteredHiltEvent (Creature & owner, uint8 eventId) inline
Definition at line 25 of file instance_halls_of_reflection.cpp.
 : _owner(owner), _eventId(eventId) { }
Referenced by Execute().
Member Function Documentation
Execute()
bool UtherBatteredHiltEvent::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
Definition at line 27 of file instance_halls_of_reflection.cpp.
     {
         switch (_eventId)
         {
             case 1:
                 _owner.UpdatePosition(5300.53f, 1987.80f, 707.70f, 3.89f, true);
                 _owner.StopMovingOnCurrentPos();
                 _owner.GetMotionMaster()->Clear();
                 _owner.SetVisible(true);
                 _owner.NearTeleportTo(5300.53f, 1987.80f, 707.70f, 3.89f);
                 _owner.m_Events.AddEvent(new UtherBatteredHiltEvent(_owner, 2), _owner.m_Events.CalculateTime(1000));
                 break;
             case 2:
                 _owner.AI()->Talk(SAY_BATTERED_HILT_HALT);
                 break;
             case 3:
                 _owner.CastSpell((Unit*)nullptr, 69966, true);
                 _owner.AI()->Talk(SAY_BATTERED_HILT_REALIZE);
                 if (InstanceScript* instance = _owner.GetInstanceScript())
                     instance->SetData(DATA_BATTERED_HILT, 4);
                 _owner.m_Events.AddEvent(new UtherBatteredHiltEvent(_owner, 4), _owner.m_Events.CalculateTime(3500));
                 break;
             case 4:
                 _owner.SetWalk(false);
                 _owner.GetMotionMaster()->MovePoint(0, 5337.53f, 1981.21f, 709.32f);
                 _owner.m_Events.AddEvent(new UtherBatteredHiltEvent(_owner, 5), _owner.m_Events.CalculateTime(6000));
                 break;
             case 5:
                 _owner.SetFacingTo(2.82f);
                 _owner.SetStandState(UNIT_STAND_STATE_KNEEL);
                 break;
             case 6:
                 if (InstanceScript* instance = _owner.GetInstanceScript())
                     instance->SetData(DATA_BATTERED_HILT, 6);
                 _owner.m_Events.AddEvent(new UtherBatteredHiltEvent(_owner, 7), _owner.m_Events.CalculateTime(2000));
                 break;
             case 7:
                 if (InstanceScript* instance = _owner.GetInstanceScript())
                     instance->SetData(DATA_BATTERED_HILT, 7);
                 _owner.AI()->Talk(SAY_BATTERED_HILT_PREPARE);
                 _owner.m_Events.AddEvent(new UtherBatteredHiltEvent(_owner, 8), _owner.m_Events.CalculateTime(4000));
                 break;
             case 8:
                 _owner.SetReactState(REACT_AGGRESSIVE);
                 _owner.RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
                 if (InstanceScript* instance = _owner.GetInstanceScript())
                     instance->SetData(DATA_BATTERED_HILT, 8);
                 break;
             case 9:
                 _owner.AI()->Talk(SAY_BATTERED_HILT_OUTRO1);
                 _owner.m_Events.AddEvent(new UtherBatteredHiltEvent(_owner, _eventId + 1), _owner.m_Events.CalculateTime(11000));
                 break;
             case 10:
                 _owner.AI()->Talk(SAY_BATTERED_HILT_OUTRO2);
                 _owner.m_Events.AddEvent(new UtherBatteredHiltEvent(_owner, _eventId + 1), _owner.m_Events.CalculateTime(7500));
                 break;
             case 11:
                 _owner.AI()->Talk(SAY_BATTERED_HILT_OUTRO3);
                 _owner.m_Events.AddEvent(new UtherBatteredHiltEvent(_owner, _eventId + 1), _owner.m_Events.CalculateTime(8000));
                 break;
             case 12:
                 _owner.AI()->Talk(SAY_BATTERED_HILT_OUTRO4);
                 _owner.m_Events.AddEvent(new UtherBatteredHiltEvent(_owner, _eventId + 1), _owner.m_Events.CalculateTime(5000));
                 break;
             case 13:
                 _owner.CastSpell((Unit*)nullptr, 73036, true);
                 _owner.m_Events.AddEvent(new UtherBatteredHiltEvent(_owner, _eventId + 1), _owner.m_Events.CalculateTime(3000));
                 break;
             case 14:
                 {
                     Position homePos = _owner.GetHomePosition();
                     _owner.SetReactState(REACT_PASSIVE);
                     _owner.SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_IMMUNE_TO_NPC);
                     _owner.SetVisible(false);
                     _owner.UpdatePosition(homePos.GetPositionX(), homePos.GetPositionY(), homePos.GetPositionZ(), homePos.GetOrientation(), true);
                     _owner.StopMovingOnCurrentPos();
                     _owner.GetMotionMaster()->Clear();
                     if (InstanceScript* instance = _owner.GetInstanceScript())
                         instance->SetData(DATA_BATTERED_HILT, 9);
                 }
                 break;
         }
         return true;
     }
References _eventId, _owner, EventProcessor::AddEvent(), Creature::AI(), EventProcessor::CalculateTime(), Unit::CastSpell(), MotionMaster::Clear(), DATA_BATTERED_HILT, Creature::GetHomePosition(), WorldObject::GetInstanceScript(), Unit::GetMotionMaster(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::m_Events, MotionMaster::MovePoint(), Unit::NearTeleportTo(), REACT_AGGRESSIVE, REACT_PASSIVE, Object::RemoveFlag(), SAY_BATTERED_HILT_HALT, SAY_BATTERED_HILT_OUTRO1, SAY_BATTERED_HILT_OUTRO2, SAY_BATTERED_HILT_OUTRO3, SAY_BATTERED_HILT_OUTRO4, SAY_BATTERED_HILT_PREPARE, SAY_BATTERED_HILT_REALIZE, Unit::SetFacingTo(), Object::SetFlag(), Creature::SetReactState(), Unit::SetStandState(), Unit::SetVisible(), Creature::SetWalk(), Unit::StopMovingOnCurrentPos(), CreatureAI::Talk(), UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, UNIT_STAND_STATE_KNEEL, Unit::UpdatePosition(), and UtherBatteredHiltEvent().
Member Data Documentation
_eventId
uint8 UtherBatteredHiltEvent::_eventId private
Definition at line 114 of file instance_halls_of_reflection.cpp.
Referenced by Execute().
_owner
Creature& UtherBatteredHiltEvent::_owner private
Definition at line 113 of file instance_halls_of_reflection.cpp.
Referenced by Execute().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/instance_halls_of_reflection.cpp