Azerotcore-wotlk: deps/mysqllite/mysys/checksum.c File Reference
checksum.c File Reference
#include <my_global.h>
#include <my_sys.h>
#include <zlib.h>
Functions
ha_checksum my_checksum (ha_checksum crc, const uchar *pos, size_t length)
Function Documentation
my_checksum()
ha_checksum my_checksum (ha_checksum crc, const uchar * pos, size_t length)
Definition at line 31 of file checksum.c.
 {
   return (ha_checksum)crc32((uint)crc, pos, (uint)length);
 }
References crc32(), G3D::length(), and pos().