Azerotcore-wotlk: src/server/game/AI/CreatureAI.cpp File Reference
CreatureAI.cpp File Reference
#include "Creature.h"
#include "CreatureAI.h"
#include "CreatureAIImpl.h"
#include "CreatureGroups.h"
#include "CreatureTextMgr.h"
#include "Log.h"
#include "MapReference.h"
#include "Player.h"
#include "SpellMgr.h"
#include "Vehicle.h"
Classes
class PhasedRespawn
Functions
AISpellInfoType * GetAISpellInfo (uint32 i)
bool IsValidCombatTarget (Creature *source, Player *target)
Function Documentation
GetAISpellInfo()
AISpellInfoType* GetAISpellInfo (uint32 i)
Definition at line 53 of file CreatureAI.cpp.
 { return &CreatureAI::AISpellInfo[i]; }
References UnitAI::AISpellInfo.
Referenced by CasterAI::EnterCombat(), CasterAI::InitializeAI(), and CasterAI::UpdateAI().
IsValidCombatTarget()
bool IsValidCombatTarget (Creature * source, Player * target) inline
Definition at line 60 of file CreatureAI.cpp.
 {
     if (target->IsGameMaster())
     {
         return false;
     }
     if (!source->IsInWorld() || !target->IsInWorld())
     {
         return false;
     }
     if (!source->IsAlive() || !target->IsAlive())
     {
         return false;
     }
     if (!source->InSamePhase(target))
     {
         return false;
     }
     if (source->HasUnitState(UNIT_STATE_IN_FLIGHT) || target->HasUnitState(UNIT_STATE_IN_FLIGHT))
     {
         return false;
     }
     return true;
 }
References Unit::HasUnitState(), WorldObject::InSamePhase(), Unit::IsAlive(), Player::IsGameMaster(), Object::IsInWorld(), and UNIT_STATE_IN_FLIGHT.
Referenced by CreatureAI::DoZoneInCombat().