Azerotcore-wotlk: AccountMgr Namespace Reference
AccountMgr Namespace Reference
Functions
AccountOpResult CreateAccount (std::string username, std::string password)
AccountOpResult DeleteAccount (uint32 accountId)
AccountOpResult ChangeUsername (uint32 accountId, std::string newUsername, std::string newPassword)
AccountOpResult ChangePassword (uint32 accountId, std::string newPassword)
uint32 GetId (std::string const &username)
uint32 GetSecurity (uint32 accountId)
uint32 GetSecurity (uint32 accountId, int32 realmId)
bool GetName (uint32 accountId, std::string &name)
bool CheckPassword (uint32 accountId, std::string password)
uint32 GetCharactersCount (uint32 accountId)
bool IsPlayerAccount (uint32 gmlevel)
bool IsGMAccount (uint32 gmlevel)
bool IsAdminAccount (uint32 gmlevel)
bool IsConsoleAccount (uint32 gmlevel)
Function Documentation
ChangePassword()
AccountOpResult AccountMgr::ChangePassword (uint32 accountId, std::string newPassword)
Definition at line 169 of file AccountMgr.cpp.
     {
         std::string username;
         if (!GetName(accountId, username))
         {
             sScriptMgr->OnFailedPasswordChange(accountId);
             return AOR_NAME_NOT_EXIST;                          // account doesn't exist
         }
         if (utf8length(newPassword) > MAX_PASS_STR)
         {
             sScriptMgr->OnFailedEmailChange(accountId);
             return AOR_PASS_TOO_LONG;                           // password's too long
         }
         Utf8ToUpperOnlyLatin(username);
         Utf8ToUpperOnlyLatin(newPassword);
         auto [salt, verifier] = Acore::Crypto::SRP6::MakeRegistrationData(username, newPassword);
         LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_UPD_LOGON);
         stmt->setBinary(0, salt);
         stmt->setBinary(1, verifier);
         stmt->setUInt32(2, accountId);
         LoginDatabase.Execute(stmt);
         sScriptMgr->OnPasswordChange(accountId);
         return AOR_OK;
     }
References AOR_NAME_NOT_EXIST, AOR_OK, AOR_PASS_TOO_LONG, GetName(), LOGIN_UPD_LOGON, LoginDatabase, Acore::Crypto::SRP6::MakeRegistrationData(), MAX_PASS_STR, PreparedStatementBase::setBinary(), PreparedStatementBase::setUInt32(), sScriptMgr, utf8length(), and Utf8ToUpperOnlyLatin().
Referenced by account_commandscript::HandleAccountPasswordCommand(), and account_commandscript::HandleAccountSetPasswordCommand().
ChangeUsername()
AccountOpResult AccountMgr::ChangeUsername (uint32 accountId, std::string newUsername, std::string newPassword)
Definition at line 135 of file AccountMgr.cpp.
     {
         // Check if accounts exists
         LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_SEL_ACCOUNT_BY_ID);
         stmt->setUInt32(0, accountId);
         PreparedQueryResult result = LoginDatabase.Query(stmt);
         if (!result)
             return AOR_NAME_NOT_EXIST;
         if (utf8length(newUsername) > MAX_ACCOUNT_STR)
             return AOR_NAME_TOO_LONG;
         if (utf8length(newPassword) > MAX_PASS_STR)
             return AOR_PASS_TOO_LONG;                           // password's too long
         Utf8ToUpperOnlyLatin(newUsername);
         Utf8ToUpperOnlyLatin(newPassword);
         stmt = LoginDatabase.GetPreparedStatement(LOGIN_UPD_USERNAME);
         stmt->setString(0, newUsername);
         stmt->setUInt32(1, accountId);
         LoginDatabase.Execute(stmt);
         auto [salt, verifier] = Acore::Crypto::SRP6::MakeRegistrationData(newUsername, newPassword);
         stmt = LoginDatabase.GetPreparedStatement(LOGIN_UPD_LOGON);
         stmt->setBinary(0, salt);
         stmt->setBinary(1, verifier);
         stmt->setUInt32(2, accountId);
         LoginDatabase.Execute(stmt);
         return AOR_OK;
     }
References AOR_NAME_NOT_EXIST, AOR_NAME_TOO_LONG, AOR_OK, AOR_PASS_TOO_LONG, LOGIN_SEL_ACCOUNT_BY_ID, LOGIN_UPD_LOGON, LOGIN_UPD_USERNAME, LoginDatabase, Acore::Crypto::SRP6::MakeRegistrationData(), MAX_ACCOUNT_STR, MAX_PASS_STR, PreparedStatementBase::setBinary(), PreparedStatementBase::setString(), PreparedStatementBase::setUInt32(), utf8length(), and Utf8ToUpperOnlyLatin().
CheckPassword()
bool AccountMgr::CheckPassword (uint32 accountId, std::string password)
Definition at line 243 of file AccountMgr.cpp.
     {
         std::string username;
         if (!GetName(accountId, username))
             return false;
         Utf8ToUpperOnlyLatin(username);
         Utf8ToUpperOnlyLatin(password);
         LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_SEL_CHECK_PASSWORD);
         stmt->setUInt32(0, accountId);
         if (PreparedQueryResult result = LoginDatabase.Query(stmt))
         {
             Acore::Crypto::SRP6::Salt salt = (*result)[0].GetBinary<Acore::Crypto::SRP6::SALT_LENGTH>();
             Acore::Crypto::SRP6::Verifier verifier = (*result)[1].GetBinary<Acore::Crypto::SRP6::VERIFIER_LENGTH>();
             if (Acore::Crypto::SRP6::CheckLogin(username, password, salt, verifier))
                 return true;
         }
         return false;
     }
References Acore::Crypto::SRP6::CheckLogin(), GetName(), LOGIN_SEL_CHECK_PASSWORD, LoginDatabase, Acore::Crypto::SRP6::SALT_LENGTH, PreparedStatementBase::setUInt32(), Utf8ToUpperOnlyLatin(), and Acore::Crypto::SRP6::VERIFIER_LENGTH.
Referenced by account_commandscript::HandleAccountPasswordCommand(), and ns1__executeCommand().
CreateAccount()
AccountOpResult AccountMgr::CreateAccount (std::string username, std::string password)
Definition at line 30 of file AccountMgr.cpp.
     {
         if (utf8length(username) > MAX_ACCOUNT_STR)
             return AOR_NAME_TOO_LONG;                           // username's too long
         if (utf8length(password) > MAX_PASS_STR)
             return AOR_PASS_TOO_LONG;                           // password's too long
         Utf8ToUpperOnlyLatin(username);
         Utf8ToUpperOnlyLatin(password);
         if (GetId(username))
             return AOR_NAME_ALREADY_EXIST;                      // username does already exist
         LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_INS_ACCOUNT);
         stmt->setString(0, username);
         auto [salt, verifier] = Acore::Crypto::SRP6::MakeRegistrationData(username, password);
         stmt->setBinary(1, salt);
         stmt->setBinary(2, verifier);
         stmt->setInt8(3, uint8(sWorld->getIntConfig(CONFIG_EXPANSION)));
         LoginDatabase.Execute(stmt);
         stmt = LoginDatabase.GetPreparedStatement(LOGIN_INS_REALM_CHARACTERS_INIT);
         LoginDatabase.Execute(stmt);
         return AOR_OK;                                          // everything's fine
     }
References AOR_NAME_ALREADY_EXIST, AOR_NAME_TOO_LONG, AOR_OK, AOR_PASS_TOO_LONG, CONFIG_EXPANSION, GetId(), LOGIN_INS_ACCOUNT, LOGIN_INS_REALM_CHARACTERS_INIT, LoginDatabase, Acore::Crypto::SRP6::MakeRegistrationData(), MAX_ACCOUNT_STR, MAX_PASS_STR, PreparedStatementBase::setBinary(), PreparedStatementBase::setInt8(), PreparedStatementBase::setString(), sWorld, utf8length(), and Utf8ToUpperOnlyLatin().
Referenced by account_commandscript::HandleAccountCreateCommand().
DeleteAccount()
AccountOpResult AccountMgr::DeleteAccount (uint32 accountId)
Definition at line 61 of file AccountMgr.cpp.
     {
         // Check if accounts exists
         LoginDatabasePreparedStatement* loginStmt = LoginDatabase.GetPreparedStatement(LOGIN_SEL_ACCOUNT_BY_ID);
         loginStmt->setUInt32(0, accountId);
         PreparedQueryResult result = LoginDatabase.Query(loginStmt);
         if (!result)
             return AOR_NAME_NOT_EXIST;
         // Obtain accounts characters
         CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_CHARS_BY_ACCOUNT_ID);
         stmt->setUInt32(0, accountId);
         result = CharacterDatabase.Query(stmt);
         if (result)
         {
             do
             {
                 ObjectGuid guid = ObjectGuid::Create<HighGuid::Player>((*result)[0].GetUInt32());
                 // Kick if player is online
                 if (Player* p = ObjectAccessor::FindPlayer(guid))
                 {
                     WorldSession* s = p->GetSession();
                     s->KickPlayer("Delete account");            // mark session to remove at next session list update
                     s->LogoutPlayer(false);                     // logout player without waiting next session list update
                 }
                 Player::DeleteFromDB(guid.GetCounter(), accountId, false, true);       // no need to update realm characters
             } while (result->NextRow());
         }
         // table realm specific but common for all characters of account for realm
         stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_TUTORIALS);
         stmt->setUInt32(0, accountId);
         CharacterDatabase.Execute(stmt);
         stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_ACCOUNT_DATA);
         stmt->setUInt32(0, accountId);
         CharacterDatabase.Execute(stmt);
         stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_CHARACTER_BAN);
         stmt->setUInt32(0, accountId);
         CharacterDatabase.Execute(stmt);
         LoginDatabaseTransaction trans = LoginDatabase.BeginTransaction();
         loginStmt = LoginDatabase.GetPreparedStatement(LOGIN_DEL_ACCOUNT);
         loginStmt->setUInt32(0, accountId);
         trans->Append(loginStmt);
         loginStmt = LoginDatabase.GetPreparedStatement(LOGIN_DEL_ACCOUNT_ACCESS);
         loginStmt->setUInt32(0, accountId);
         trans->Append(loginStmt);
         loginStmt = LoginDatabase.GetPreparedStatement(LOGIN_DEL_REALM_CHARACTERS);
         loginStmt->setUInt32(0, accountId);
         trans->Append(loginStmt);
         loginStmt = LoginDatabase.GetPreparedStatement(LOGIN_DEL_ACCOUNT_BANNED);
         loginStmt->setUInt32(0, accountId);
         trans->Append(loginStmt);
         loginStmt = LoginDatabase.GetPreparedStatement(LOGIN_DEL_ACCOUNT_MUTED);
         loginStmt->setUInt32(0, accountId);
         trans->Append(loginStmt);
         LoginDatabase.CommitTransaction(trans);
         return AOR_OK;
     }
References AOR_NAME_NOT_EXIST, AOR_OK, CHAR_DEL_ACCOUNT_DATA, CHAR_DEL_CHARACTER_BAN, CHAR_DEL_TUTORIALS, CHAR_SEL_CHARS_BY_ACCOUNT_ID, CharacterDatabase, Player::DeleteFromDB(), ObjectAccessor::FindPlayer(), ObjectGuid::GetCounter(), WorldSession::KickPlayer(), LOGIN_DEL_ACCOUNT, LOGIN_DEL_ACCOUNT_ACCESS, LOGIN_DEL_ACCOUNT_BANNED, LOGIN_DEL_ACCOUNT_MUTED, LOGIN_DEL_REALM_CHARACTERS, LOGIN_SEL_ACCOUNT_BY_ID, LoginDatabase, WorldSession::LogoutPlayer(), and PreparedStatementBase::setUInt32().
Referenced by account_commandscript::HandleAccountDeleteCommand().
GetCharactersCount()
uint32 AccountMgr::GetCharactersCount (uint32 accountId)
Definition at line 266 of file AccountMgr.cpp.
     {
         // check character count
         CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_SUM_CHARS);
         stmt->setUInt32(0, accountId);
         PreparedQueryResult result = CharacterDatabase.Query(stmt);
         return (result) ? (*result)[0].GetUInt64() : 0;
     }
References CHAR_SEL_SUM_CHARS, CharacterDatabase, and PreparedStatementBase::setUInt32().
Referenced by character_commandscript::HandleCharacterDeletedRestoreHelper(), and PlayerDumpReader::LoadDump().
GetId()
uint32 AccountMgr::GetId (std::string const & username)
Definition at line 200 of file AccountMgr.cpp.
     {
         LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_GET_ACCOUNT_ID_BY_USERNAME);
         stmt->setString(0, username);
         PreparedQueryResult result = LoginDatabase.Query(stmt);
         return (result) ? (*result)[0].GetUInt32() : 0;
     }
References LOGIN_GET_ACCOUNT_ID_BY_USERNAME, LoginDatabase, and PreparedStatementBase::setString().
Referenced by AuraApplication::_Remove(), AuraApplication::AuraApplication(), BanMgr::BanAccount(), Player::CheckInstanceLoginValid(), CreateAccount(), account_commandscript::HandleAccountDeleteCommand(), account_commandscript::HandleAccountRemoveLockCountryCommand(), account_commandscript::HandleAccountSet2FACommand(), account_commandscript::HandleAccountSetAddonCommand(), account_commandscript::HandleAccountSetGmLevelCommand(), account_commandscript::HandleAccountSetPasswordCommand(), ban_commandscript::HandleBanInfoAccountCommand(), misc_commandscript::HandleMuteInfoCommand(), ns1__executeCommand(), BanMgr::RemoveBanAccount(), Player::SetEntryPoint(), Player::SetMover(), Acore::ChatCommands::AccountIdentifier::TryConsume(), and Player::Update().
GetName()
bool AccountMgr::GetName (uint32 accountId, std::string & name)
Definition at line 228 of file AccountMgr.cpp.
     {
         LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_GET_USERNAME_BY_ID);
         stmt->setUInt32(0, accountId);
         PreparedQueryResult result = LoginDatabase.Query(stmt);
         if (result)
         {
             name = (*result)[0].GetString();
             return true;
         }
         return false;
     }
References LOGIN_GET_USERNAME_BY_ID, LoginDatabase, and PreparedStatementBase::setUInt32().
Referenced by Warden::ApplyPenalty(), BanMgr::BanAccountByPlayerName(), ChangePassword(), CheckPassword(), WorldSession::DisallowHyperlinksAndMaybeKick(), WorldSession::DosProtection::EvaluateOpcode(), character_commandscript::GetDeletedCharacterInfoList(), account_commandscript::HandleAccountSetAddonCommand(), WorldSession::HandleAddFriendOpcode(), WorldSession::HandleAddIgnoreOpcode(), WorldSession::HandleArenaTeamInviteOpcode(), ban_commandscript::HandleBanListHelper(), character_commandscript::HandleCharacterEraseCommand(), WorldSession::HandleChatIgnoredOpcode(), WorldSession::HandleDismissCritter(), WorldSession::HandleGMTicketCreateOpcode(), WorldSession::HandleGMTicketDeleteOpcode(), WorldSession::HandleGMTicketUpdateOpcode(), WorldSession::HandleGroupAcceptOpcode(), WorldSession::HandleGroupDeclineOpcode(), WorldSession::HandleGroupDisbandOpcode(), WorldSession::HandleGroupUninviteGuidOpcode(), WorldSession::HandleGroupUninviteOpcode(), WorldSession::HandleGuildAcceptOpcode(), WorldSession::HandleLootMasterGiveOpcode(), WorldSession::HandleMessagechatOpcode(), WorldSession::HandleMoveWorldportAck(), WorldSession::HandlePetAction(), WorldSession::HandlePetCancelAuraOpcode(), WorldSession::HandlePetCastSpellOpcode(), WorldSession::HandlePetitionSignOpcode(), WorldSession::HandlePetSpellAutocastOpcode(), WorldSession::HandlePetStopAttack(), WorldSession::HandleRepopRequestOpcode(), WorldSession::HandleWhoisOpcode(), WorldSession::HandleWorldTeleportOpcode(), go_ulduar_pure_saronite_deposit::OnGossipHello(), AchievementMgr::SendAchievementEarned(), go_wind_stone::go_wind_stoneAI::SummonNPC(), Acore::ChatCommands::AccountIdentifier::TryConsume(), Aura::UnregisterSingleTarget(), Aura::UpdateTargetMap(), and WorldSession::ValidateHyperlinksAndMaybeKick().
GetSecurity() [1/2]
uint32 AccountMgr::GetSecurity (uint32 accountId)
Definition at line 209 of file AccountMgr.cpp.
     {
         LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_GET_ACCOUNT_ACCESS_GMLEVEL);
         stmt->setUInt32(0, accountId);
         PreparedQueryResult result = LoginDatabase.Query(stmt);
         return (result) ? (*result)[0].GetUInt8() : uint32(SEC_PLAYER);
     }
References LOGIN_GET_ACCOUNT_ACCESS_GMLEVEL, LoginDatabase, SEC_PLAYER, and PreparedStatementBase::setUInt32().
Referenced by Player::Create(), Player::getMaxTimer(), account_commandscript::HandleAccountSetGmLevelCommand(), WorldSession::HandleAddFriendOpcode(), ticket_commandscript::HandleGMTicketAssignToCommand(), ticket_commandscript::HandleGMTicketUnAssignCommand(), ChatHandler::HasLowerSecurityAccount(), Player::LoadFromDB(), ns1__executeCommand(), Player::Player(), Player::SetGameMaster(), Player::SetGMVisible(), Player::TeleportTo(), and Player::UpdateSpeakTime().
GetSecurity() [2/2]
uint32 AccountMgr::GetSecurity (uint32 accountId, int32 realmId)
Definition at line 218 of file AccountMgr.cpp.
     {
         LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_GET_GMLEVEL_BY_REALMID);
         stmt->setUInt32(0, accountId);
         stmt->setInt32(1, realmId);
         PreparedQueryResult result = LoginDatabase.Query(stmt);
         return (result) ? (*result)[0].GetUInt8() : uint32(SEC_PLAYER);
     }
References LOGIN_GET_GMLEVEL_BY_REALMID, LoginDatabase, SEC_PLAYER, PreparedStatementBase::setInt32(), and PreparedStatementBase::setUInt32().
IsAdminAccount()
bool AccountMgr::IsAdminAccount (uint32 gmlevel)
Definition at line 286 of file AccountMgr.cpp.
     {
         return gmlevel >= SEC_ADMINISTRATOR && gmlevel <= SEC_CONSOLE;
     }
References SEC_ADMINISTRATOR, and SEC_CONSOLE.
Referenced by ticket_commandscript::HandleGMTicketAssignToCommand(), WorldSession::HandleWhoisOpcode(), and WorldSession::HandleWorldTeleportOpcode().
IsConsoleAccount()
bool AccountMgr::IsConsoleAccount (uint32 gmlevel)
Definition at line 291 of file AccountMgr.cpp.
     {
         return gmlevel == SEC_CONSOLE;
     }
References SEC_CONSOLE.
Referenced by account_commandscript::HandleAccountSetGmLevelCommand().
IsGMAccount()
bool AccountMgr::IsGMAccount (uint32 gmlevel)
Definition at line 281 of file AccountMgr.cpp.
     {
         return gmlevel >= SEC_MODERATOR && gmlevel <= SEC_CONSOLE;
     }
References SEC_CONSOLE, and SEC_MODERATOR.
Referenced by Channel::Announce(), GameObject::BuildValuesUpdate(), Unit::BuildValuesUpdate(), SocialMgr::GetFriendInfo(), WorldSession::HandleAddFriendOpcode(), modify_commandscript::HandleModifyASpeedCommand(), modify_commandscript::HandleModifyBWalkCommand(), modify_commandscript::HandleModifyFlyCommand(), modify_commandscript::HandleModifySpeedCommand(), modify_commandscript::HandleModifySwimCommand(), Channel::JoinChannel(), Channel::KickOrBan(), Channel::LeaveChannel(), Channel::Password(), Player::SetGameMaster(), Channel::SetMode(), Channel::SetOwner(), and Channel::UnBan().
IsPlayerAccount()
bool AccountMgr::IsPlayerAccount (uint32 gmlevel)
Definition at line 276 of file AccountMgr.cpp.
     {
         return gmlevel == SEC_PLAYER;
     }
References SEC_PLAYER.
Referenced by ChatHandler::_ParseCommands(), World::AddSession_(), SocialMgr::BroadcastToFriendListers(), AchievementMgr::CompletedAchievement(), Player::Create(), Channel::FlagsNotify(), SocialMgr::GetFriendInfo(), WorldSession::HandleAddFriendOpcode(), WorldSession::HandleCharCreateOpcode(), WorldSession::HandleCharCustomizeCallback(), WorldSession::HandleCharFactionOrRaceChangeCallback(), WorldSession::HandleCharRenameOpcode(), gm_commandscript::HandleGMChatCommand(), gm_commandscript::HandleGMListIngameCommand(), ticket_commandscript::HandleGMTicketAssignToCommand(), WorldSession::HandleMessagechatOpcode(), WorldSocket::HandlePing(), misc_commandscript::HandleReviveCommand(), WorldSession::HandleSendMail(), misc_commandscript::HandleUnstuckCommand(), WorldSession::HandleWhoOpcode(), ChatHandler::HasLowerSecurityAccount(), Player::IsVisibleGloballyFor(), Channel::JoinChannel(), Channel::JoinNotify(), Channel::LeaveNotify(), Channel::List(), Player::LoadFromDB(), LogCommandUsage(), Player::Player(), World::SendGlobalGMMessage(), World::SendGMText(), Player::TeleportTo(), and Player::UpdateSpeakTime().