Azerotcore-wotlk: anonymous_namespace{QueryResult.cpp} Namespace Reference
anonymous_namespace{QueryResult.cpp} Namespace Reference
Functions
static uint32 SizeForType (MYSQL_FIELD *field)
DatabaseFieldTypes MysqlTypeToFieldType (enum_field_types type)
static char const * FieldTypeToString (enum_field_types type)
void InitializeDatabaseFieldMetadata (QueryResultFieldMetadata *meta, MySQLField const *field, uint32 fieldIndex)
Function Documentation
FieldTypeToString()
static char const* anonymous_namespace{QueryResult.cpp}::FieldTypeToString (enum_field_types type) static
Definition at line 121 of file QueryResult.cpp.
 {
     switch (type)
     {
         case MYSQL_TYPE_BIT:         return "BIT";
         case MYSQL_TYPE_BLOB:        return "BLOB";
         case MYSQL_TYPE_DATE:        return "DATE";
         case MYSQL_TYPE_DATETIME:    return "DATETIME";
         case MYSQL_TYPE_NEWDECIMAL:  return "NEWDECIMAL";
         case MYSQL_TYPE_DECIMAL:     return "DECIMAL";
         case MYSQL_TYPE_DOUBLE:      return "DOUBLE";
         case MYSQL_TYPE_ENUM:        return "ENUM";
         case MYSQL_TYPE_FLOAT:       return "FLOAT";
         case MYSQL_TYPE_GEOMETRY:    return "GEOMETRY";
         case MYSQL_TYPE_INT24:       return "INT24";
         case MYSQL_TYPE_LONG:        return "LONG";
         case MYSQL_TYPE_LONGLONG:    return "LONGLONG";
         case MYSQL_TYPE_LONG_BLOB:   return "LONG_BLOB";
         case MYSQL_TYPE_MEDIUM_BLOB: return "MEDIUM_BLOB";
         case MYSQL_TYPE_NEWDATE:     return "NEWDATE";
         case MYSQL_TYPE_NULL:        return "NULL";
         case MYSQL_TYPE_SET:         return "SET";
         case MYSQL_TYPE_SHORT:       return "SHORT";
         case MYSQL_TYPE_STRING:      return "STRING";
         case MYSQL_TYPE_TIME:        return "TIME";
         case MYSQL_TYPE_TIMESTAMP:   return "TIMESTAMP";
         case MYSQL_TYPE_TINY:        return "TINY";
         case MYSQL_TYPE_TINY_BLOB:   return "TINY_BLOB";
         case MYSQL_TYPE_VAR_STRING:  return "VAR_STRING";
         case MYSQL_TYPE_YEAR:        return "YEAR";
         default:                     return "-Unknown-";
     }
 }
References MYSQL_TYPE_BIT, MYSQL_TYPE_BLOB, MYSQL_TYPE_DATE, MYSQL_TYPE_DATETIME, MYSQL_TYPE_DECIMAL, MYSQL_TYPE_DOUBLE, MYSQL_TYPE_ENUM, MYSQL_TYPE_FLOAT, MYSQL_TYPE_GEOMETRY, MYSQL_TYPE_INT24, MYSQL_TYPE_LONG, MYSQL_TYPE_LONG_BLOB, MYSQL_TYPE_LONGLONG, MYSQL_TYPE_MEDIUM_BLOB, MYSQL_TYPE_NEWDATE, MYSQL_TYPE_NEWDECIMAL, MYSQL_TYPE_NULL, MYSQL_TYPE_SET, MYSQL_TYPE_SHORT, MYSQL_TYPE_STRING, MYSQL_TYPE_TIME, MYSQL_TYPE_TIMESTAMP, MYSQL_TYPE_TINY, MYSQL_TYPE_TINY_BLOB, MYSQL_TYPE_VAR_STRING, and MYSQL_TYPE_YEAR.
Referenced by InitializeDatabaseFieldMetadata().
InitializeDatabaseFieldMetadata()
void anonymous_namespace{QueryResult.cpp}::InitializeDatabaseFieldMetadata (QueryResultFieldMetadata * meta, MySQLField const * field, uint32 fieldIndex)
Definition at line 155 of file QueryResult.cpp.
 {
     meta->TableName = field->org_table;
     meta->TableAlias = field->table;
     meta->Name = field->org_name;
     meta->Alias = field->name;
     meta->TypeName = FieldTypeToString(field->type);
     meta->Index = fieldIndex;
     meta->Type = MysqlTypeToFieldType(field->type);
 }
References QueryResultFieldMetadata::Alias, FieldTypeToString(), QueryResultFieldMetadata::Index, MysqlTypeToFieldType(), st_mysql_field::name, QueryResultFieldMetadata::Name, st_mysql_field::org_name, st_mysql_field::org_table, st_mysql_field::table, QueryResultFieldMetadata::TableAlias, QueryResultFieldMetadata::TableName, st_mysql_field::type, QueryResultFieldMetadata::Type, and QueryResultFieldMetadata::TypeName.
Referenced by PreparedResultSet::PreparedResultSet(), and ResultSet::ResultSet().
MysqlTypeToFieldType()
DatabaseFieldTypes anonymous_namespace{QueryResult.cpp}::MysqlTypeToFieldType (enum_field_types type)
Definition at line 77 of file QueryResult.cpp.
 {
     switch (type)
     {
         case MYSQL_TYPE_NULL:
             return DatabaseFieldTypes::Null;
         case MYSQL_TYPE_TINY:
             return DatabaseFieldTypes::Int8;
         case MYSQL_TYPE_YEAR:
         case MYSQL_TYPE_SHORT:
             return DatabaseFieldTypes::Int16;
         case MYSQL_TYPE_INT24:
         case MYSQL_TYPE_LONG:
             return DatabaseFieldTypes::Int32;
         case MYSQL_TYPE_LONGLONG:
         case MYSQL_TYPE_BIT:
             return DatabaseFieldTypes::Int64;
         case MYSQL_TYPE_FLOAT:
             return DatabaseFieldTypes::Float;
         case MYSQL_TYPE_DOUBLE:
             return DatabaseFieldTypes::Double;
         case MYSQL_TYPE_DECIMAL:
         case MYSQL_TYPE_NEWDECIMAL:
             return DatabaseFieldTypes::Decimal;
         case MYSQL_TYPE_TIMESTAMP:
         case MYSQL_TYPE_DATE:
         case MYSQL_TYPE_TIME:
         case MYSQL_TYPE_DATETIME:
             return DatabaseFieldTypes::Date;
         case MYSQL_TYPE_TINY_BLOB:
         case MYSQL_TYPE_MEDIUM_BLOB:
         case MYSQL_TYPE_LONG_BLOB:
         case MYSQL_TYPE_BLOB:
         case MYSQL_TYPE_STRING:
         case MYSQL_TYPE_VAR_STRING:
             return DatabaseFieldTypes::Binary;
         default:
             LOG_WARN("sql.sql", "MysqlTypeToFieldType(): invalid field type %u", uint32(type));
             break;
     }
     return DatabaseFieldTypes::Null;
 }
References Binary, Date, Decimal, Double, Float, Int16, Int32, Int64, Int8, LOG_WARN, MYSQL_TYPE_BIT, MYSQL_TYPE_BLOB, MYSQL_TYPE_DATE, MYSQL_TYPE_DATETIME, MYSQL_TYPE_DECIMAL, MYSQL_TYPE_DOUBLE, MYSQL_TYPE_FLOAT, MYSQL_TYPE_INT24, MYSQL_TYPE_LONG, MYSQL_TYPE_LONG_BLOB, MYSQL_TYPE_LONGLONG, MYSQL_TYPE_MEDIUM_BLOB, MYSQL_TYPE_NEWDECIMAL, MYSQL_TYPE_NULL, MYSQL_TYPE_SHORT, MYSQL_TYPE_STRING, MYSQL_TYPE_TIME, MYSQL_TYPE_TIMESTAMP, MYSQL_TYPE_TINY, MYSQL_TYPE_TINY_BLOB, MYSQL_TYPE_VAR_STRING, MYSQL_TYPE_YEAR, and Null.
Referenced by InitializeDatabaseFieldMetadata().
SizeForType()
static uint32 anonymous_namespace{QueryResult.cpp}::SizeForType (MYSQL_FIELD * field) static
Definition at line 27 of file QueryResult.cpp.
 {
     switch (field->type)
     {
         case MYSQL_TYPE_NULL:
             return 0;
         case MYSQL_TYPE_TINY:
             return 1;
         case MYSQL_TYPE_YEAR:
         case MYSQL_TYPE_SHORT:
             return 2;
         case MYSQL_TYPE_INT24:
         case MYSQL_TYPE_LONG:
         case MYSQL_TYPE_FLOAT:
             return 4;
         case MYSQL_TYPE_DOUBLE:
         case MYSQL_TYPE_LONGLONG:
         case MYSQL_TYPE_BIT:
             return 8;
         case MYSQL_TYPE_TIMESTAMP:
         case MYSQL_TYPE_DATE:
         case MYSQL_TYPE_TIME:
         case MYSQL_TYPE_DATETIME:
             return sizeof(MYSQL_TIME);
         case MYSQL_TYPE_TINY_BLOB:
         case MYSQL_TYPE_MEDIUM_BLOB:
         case MYSQL_TYPE_LONG_BLOB:
         case MYSQL_TYPE_BLOB:
         case MYSQL_TYPE_STRING:
         case MYSQL_TYPE_VAR_STRING:
             return field->max_length + 1;
         case MYSQL_TYPE_DECIMAL:
         case MYSQL_TYPE_NEWDECIMAL:
             return 64;
         case MYSQL_TYPE_GEOMETRY:
             /*
             Following types are not sent over the wire:
             MYSQL_TYPE_ENUM:
             MYSQL_TYPE_SET:
             */
         default:
             LOG_WARN("sql.sql", "SQL::SizeForType(): invalid field type %u", uint32(field->type));
             return 0;
     }
 }
References LOG_WARN, st_mysql_field::max_length, MYSQL_TYPE_BIT, MYSQL_TYPE_BLOB, MYSQL_TYPE_DATE, MYSQL_TYPE_DATETIME, MYSQL_TYPE_DECIMAL, MYSQL_TYPE_DOUBLE, MYSQL_TYPE_FLOAT, MYSQL_TYPE_GEOMETRY, MYSQL_TYPE_INT24, MYSQL_TYPE_LONG, MYSQL_TYPE_LONG_BLOB, MYSQL_TYPE_LONGLONG, MYSQL_TYPE_MEDIUM_BLOB, MYSQL_TYPE_NEWDECIMAL, MYSQL_TYPE_NULL, MYSQL_TYPE_SHORT, MYSQL_TYPE_STRING, MYSQL_TYPE_TIME, MYSQL_TYPE_TIMESTAMP, MYSQL_TYPE_TINY, MYSQL_TYPE_TINY_BLOB, MYSQL_TYPE_VAR_STRING, MYSQL_TYPE_YEAR, and st_mysql_field::type.
Referenced by PreparedResultSet::PreparedResultSet().