Azerotcore-wotlk: TransportMgr Class Reference
TransportMgr Class Reference
#include <TransportMgr.h>
Public Member Functions
void Unload ()
void LoadTransportTemplates ()
MotionTransport * CreateTransport (uint32 entry, ObjectGuid::LowType guid=0, Map *map=nullptr)
void SpawnContinentTransports ()
void CreateInstanceTransports (Map *map)
TransportTemplate const * GetTransportTemplate (uint32 entry) const
TransportAnimation const * GetTransportAnimInfo (uint32 entry) const
void GeneratePath (GameObjectTemplate const *goInfo, TransportTemplate *transport)
void AddPathNodeToTransport (uint32 transportEntry, uint32 timeSeg, TransportAnimationEntry const *node)
void AddPathRotationToTransport (uint32 transportEntry, uint32 timeSeg, TransportRotationEntry const *node)
Static Public Member Functions
static TransportMgr * instance ()
Private Member Functions
TransportMgr ()
~TransportMgr ()
TransportMgr (TransportMgr const &)
TransportMgr & operator= (TransportMgr const &)
Private Attributes
TransportTemplates _transportTemplates
TransportInstanceMap _instanceTransports
TransportAnimationContainer _transportAnimations
Friends
void LoadDBCStores (std::string const &)
Detailed Description
Definition at line 100 of file TransportMgr.h.
Constructor & Destructor Documentation
TransportMgr() [1/2]
TransportMgr::TransportMgr () private
Definition at line 35 of file TransportMgr.cpp.
 { }
~TransportMgr()
TransportMgr::~TransportMgr () private
Definition at line 37 of file TransportMgr.cpp.
 { }
TransportMgr() [2/2]
TransportMgr::TransportMgr (TransportMgr const &) private
Member Function Documentation
AddPathNodeToTransport()
void TransportMgr::AddPathNodeToTransport (uint32 transportEntry, uint32 timeSeg, TransportAnimationEntry const * node)
Definition at line 349 of file TransportMgr.cpp.
 {
     TransportAnimation& animNode = _transportAnimations[transportEntry];
     if (animNode.TotalTime < timeSeg)
         animNode.TotalTime = timeSeg;
     animNode.Path[timeSeg] = node;
 }
References _transportAnimations, TransportAnimation::Path, and TransportAnimation::TotalTime.
AddPathRotationToTransport()
void TransportMgr::AddPathRotationToTransport (uint32 transportEntry, uint32 timeSeg, TransportRotationEntry const * node) inline
Definition at line 142 of file TransportMgr.h.
     {
         _transportAnimations[transportEntry].Rotations[timeSeg] = node;
     }
References _transportAnimations.
CreateInstanceTransports()
void TransportMgr::CreateInstanceTransports (Map * map)
Definition at line 481 of file TransportMgr.cpp.
 {
     TransportInstanceMap::const_iterator mapTransports = _instanceTransports.find(map->GetId());
     // no transports here
     if (mapTransports == _instanceTransports.end() || mapTransports->second.empty())
         return;
     // create transports
     for (std::set<uint32>::const_iterator itr = mapTransports->second.begin(); itr != mapTransports->second.end(); ++itr)
         CreateTransport(*itr, 0, map);
 }
References _instanceTransports, CreateTransport(), and Map::GetId().
CreateTransport()
MotionTransport * TransportMgr::CreateTransport (uint32 entry, ObjectGuid::LowType guid = 0, Map * map = nullptr)
Definition at line 358 of file TransportMgr.cpp.
 {
     // instance case, execute GetGameObjectEntry hook
     if (map)
     {
         // SetZoneScript() is called after adding to map, so fetch the script using map
         if (map->IsDungeon())
             if (InstanceScript* instance = static_cast<InstanceMap*>(map)->GetInstanceScript())
                 entry = instance->GetGameObjectEntry(0, entry);
         if (!entry)
             return nullptr;
     }
     TransportTemplate const* tInfo = GetTransportTemplate(entry);
     if (!tInfo)
     {
         LOG_ERROR("entities.transport", "Transport %u will not be loaded, `transport_template` missing", entry);
         return nullptr;
     }
     // create transport...
     MotionTransport* trans = new MotionTransport();
     // ...at first waypoint
     TaxiPathNodeEntry const* startNode = tInfo->keyFrames.begin()->Node;
     uint32 mapId = startNode->mapid;
     float x = startNode->x;
     float y = startNode->y;
     float z = startNode->z;
     float o = tInfo->keyFrames.begin()->InitialOrientation;
     // initialize the gameobject base
     ObjectGuid::LowType guidLow = guid ? guid : sObjectMgr->GetGenerator<HighGuid::Mo_Transport>().Generate();
     if (!trans->CreateMoTrans(guidLow, entry, mapId, x, y, z, o, 255))
     {
         delete trans;
         return nullptr;
     }
     if (MapEntry const* mapEntry = sMapStore.LookupEntry(mapId))
     {
         if (mapEntry->Instanceable() != tInfo->inInstance)
         {
             LOG_ERROR("entities.transport", "Transport %u (name: %s) attempted creation in instance map (id: %u) but it is not an instanced transport!", entry, trans->GetName().c_str(), mapId);
             delete trans;
             return nullptr;
         }
     }
     // use preset map for instances (need to know which instance)
     trans->SetMap(map ? map : sMapMgr->CreateMap(mapId, nullptr));
     if (map && map->IsDungeon())
         trans->m_zoneScript = map->ToInstanceMap()->GetInstanceScript();
     // xinef: transports are active so passengers can be relocated (grids must be loaded)
     trans->setActive(true);
     HashMapHolder<MotionTransport>::Insert(trans);
     trans->GetMap()->AddToMap<MotionTransport>(trans);
     return trans;
 }
References Map::AddToMap(), MotionTransport::CreateMoTrans(), InstanceMap::GetInstanceScript(), WorldObject::GetMap(), WorldObject::GetName(), GetTransportTemplate(), TransportTemplate::inInstance, HashMapHolder< T >::Insert(), instance(), Map::IsDungeon(), TransportTemplate::keyFrames, LOG_ERROR, WorldObject::m_zoneScript, TaxiPathNodeEntry::mapid, Mo_Transport, WorldObject::setActive(), WorldObject::SetMap(), sMapMgr, sMapStore, sObjectMgr, Map::ToInstanceMap(), G3D::x, TaxiPathNodeEntry::x, G3D::y, TaxiPathNodeEntry::y, G3D::z, and TaxiPathNodeEntry::z.
Referenced by CreateInstanceTransports(), and SpawnContinentTransports().
GeneratePath()
void TransportMgr::GeneratePath (GameObjectTemplate const * goInfo, TransportTemplate * transport)
Definition at line 114 of file TransportMgr.cpp.
 {
     uint32 pathId = goInfo->moTransport.taxiPathId;
     TaxiPathNodeList const& path = sTaxiPathNodesByPath[pathId];
     std::vector<KeyFrame>& keyFrames = transport->keyFrames;
     Movement::PointsArray splinePath, allPoints;
     bool mapChange = false;
     for (size_t i = 0; i < path.size(); ++i)
         allPoints.push_back(G3D::Vector3(path[i]->x, path[i]->y, path[i]->z));
     // Add extra points to allow derivative calculations for all path nodes
     allPoints.insert(allPoints.begin(), allPoints.front().lerp(allPoints[1], -0.2f));
     allPoints.push_back(allPoints.back().lerp(allPoints[allPoints.size() - 2], -0.2f));
     allPoints.push_back(allPoints.back().lerp(allPoints[allPoints.size() - 2], -1.0f));
     SplineRawInitializer initer(allPoints);
     TransportSpline orientationSpline;
     orientationSpline.init_spline_custom(initer);
     orientationSpline.initLengths();
     for (size_t i = 0; i < path.size(); ++i)
     {
         if (!mapChange)
         {
             TaxiPathNodeEntry const* node_i = path[i];
             if (i != path.size() - 1 && (node_i->actionFlag & 1 || node_i->mapid != path[i + 1]->mapid))
             {
                 keyFrames.back().Teleport = true;
                 mapChange = true;
             }
             else
             {
                 KeyFrame k(node_i);
                 G3D::Vector3 h;
                 orientationSpline.evaluate_derivative(i + 1, 0.0f, h);
                 k.InitialOrientation = Position::NormalizeOrientation(atan2(h.y, h.x) + M_PI);
                 keyFrames.push_back(k);
                 splinePath.push_back(G3D::Vector3(node_i->x, node_i->y, node_i->z));
                 transport->mapsUsed.insert(k.Node->mapid);
             }
         }
         else
             mapChange = false;
     }
     if (splinePath.size() >= 2)
     {
         // Remove special catmull-rom spline points
         //if (!keyFrames.front().IsStopFrame() && !keyFrames.front().Node->arrivalEventID && !keyFrames.front().Node->departureEventID)
         {
             splinePath.erase(splinePath.begin());
             keyFrames.erase(keyFrames.begin());
         }
         //if (!keyFrames.back().IsStopFrame() && !keyFrames.back().Node->arrivalEventID && !keyFrames.back().Node->departureEventID)
         {
             splinePath.pop_back();
             keyFrames.pop_back();
         }
     }
     ASSERT(!keyFrames.empty());
     if (transport->mapsUsed.size() > 1)
     {
         for (std::set<uint32>::const_iterator itr = transport->mapsUsed.begin(); itr != transport->mapsUsed.end(); ++itr)
             ASSERT(!sMapStore.LookupEntry(*itr)->Instanceable());
         transport->inInstance = false;
     }
     else
         transport->inInstance = sMapStore.LookupEntry(*transport->mapsUsed.begin())->Instanceable();
     // last to first is always "teleport", even for closed paths
     keyFrames.back().Teleport = true;
     const float speed = float(goInfo->moTransport.moveSpeed);
     const float accel = float(goInfo->moTransport.accelRate);
     const float accel_dist = 0.5f * speed * speed / accel;
     transport->accelTime = speed / accel;
     transport->accelDist = accel_dist;
     int32 firstStop = -1;
     int32 lastStop = -1;
     // first cell is arrived at by teleportation :S
     keyFrames[0].DistFromPrev = 0;
     keyFrames[0].Index = 1;
     if (keyFrames[0].IsStopFrame())
     {
         firstStop = 0;
         lastStop = 0;
     }
     // find the rest of the distances between key points
     // Every path segment has its own spline
     size_t start = 0;
     for (size_t i = 1; i < keyFrames.size(); ++i)
     {
         if (keyFrames[i - 1].Teleport || i + 1 == keyFrames.size())
         {
             size_t extra = !keyFrames[i - 1].Teleport ? 1 : 0;
             TransportSpline* spline = new TransportSpline();
             spline->init_spline(&splinePath[start], i - start + extra, Movement::SplineBase::ModeCatmullrom);
             spline->initLengths();
             for (size_t j = start; j < i + extra; ++j)
             {
                 keyFrames[j].Index = j - start + 1;
                 keyFrames[j].DistFromPrev = spline->length(j - start, j + 1 - start);
                 if (j > 0)
                     keyFrames[j - 1].NextDistFromPrev = keyFrames[j].DistFromPrev;
                 keyFrames[j].Spline = spline;
             }
             if (keyFrames[i - 1].Teleport)
             {
                 keyFrames[i].Index = i - start + 1;
                 keyFrames[i].DistFromPrev = 0.0f;
                 keyFrames[i - 1].NextDistFromPrev = 0.0f;
                 keyFrames[i].Spline = spline;
             }
             start = i;
         }
         if (keyFrames[i].IsStopFrame())
         {
             // remember first stop frame
             if (firstStop == -1)
                 firstStop = i;
             lastStop = i;
         }
     }
     keyFrames.back().NextDistFromPrev = keyFrames.front().DistFromPrev;
     if (firstStop == -1 || lastStop == -1)
         firstStop = lastStop = 0;
     // at stopping keyframes, we define distSinceStop == 0,
     // and distUntilStop is to the next stopping keyframe.
     // this is required to properly handle cases of two stopping frames in a row (yes they do exist)
     float tmpDist = 0.0f;
     for (size_t i = 0; i < keyFrames.size(); ++i)
     {
         int32 j = (i + lastStop) % keyFrames.size();
         if (keyFrames[j].IsStopFrame() || j == lastStop)
             tmpDist = 0.0f;
         else
             tmpDist += keyFrames[j].DistFromPrev;
         keyFrames[j].DistSinceStop = tmpDist;
     }
     tmpDist = 0.0f;
     for (int32 i = int32(keyFrames.size()) - 1; i >= 0; i--)
     {
         int32 j = (i + firstStop) % keyFrames.size();
         tmpDist += keyFrames[(j + 1) % keyFrames.size()].DistFromPrev;
         keyFrames[j].DistUntilStop = tmpDist;
         if (keyFrames[j].IsStopFrame() || j == firstStop)
             tmpDist = 0.0f;
     }
     for (size_t i = 0; i < keyFrames.size(); ++i)
     {
         float total_dist = keyFrames[i].DistSinceStop + keyFrames[i].DistUntilStop;
         if (total_dist < 2 * accel_dist) // won't reach full speed
         {
             if (keyFrames[i].DistSinceStop < keyFrames[i].DistUntilStop) // is still accelerating
             {
                 // calculate accel+brake time for this short segment
                 float segment_time = 2.0f * sqrt((keyFrames[i].DistUntilStop + keyFrames[i].DistSinceStop) / accel);
                 // substract acceleration time
                 keyFrames[i].TimeTo = segment_time - sqrt(2 * keyFrames[i].DistSinceStop / accel);
             }
             else // slowing down
                 keyFrames[i].TimeTo = sqrt(2 * keyFrames[i].DistUntilStop / accel);
         }
         else if (keyFrames[i].DistSinceStop < accel_dist) // still accelerating (but will reach full speed)
         {
             // calculate accel + cruise + brake time for this long segment
             float segment_time = (keyFrames[i].DistUntilStop + keyFrames[i].DistSinceStop) / speed + (speed / accel);
             // substract acceleration time
             keyFrames[i].TimeTo = segment_time - sqrt(2 * keyFrames[i].DistSinceStop / accel);
         }
         else if (keyFrames[i].DistUntilStop < accel_dist) // already slowing down (but reached full speed)
             keyFrames[i].TimeTo = sqrt(2 * keyFrames[i].DistUntilStop / accel);
         else // at full speed
             keyFrames[i].TimeTo = (keyFrames[i].DistUntilStop / speed) + (0.5f * speed / accel);
     }
     // calculate tFrom times from tTo times
     float segmentTime = 0.0f;
     for (size_t i = 0; i < keyFrames.size(); ++i)
     {
         int32 j = (i + lastStop) % keyFrames.size();
         if (keyFrames[j].IsStopFrame() || j == lastStop)
             segmentTime = keyFrames[j].TimeTo;
         keyFrames[j].TimeFrom = segmentTime - keyFrames[j].TimeTo;
     }
     // calculate path times
     keyFrames[0].ArriveTime = 0;
     float curPathTime = 0.0f;
     if (keyFrames[0].IsStopFrame())
     {
         curPathTime = float(keyFrames[0].Node->delay);
         keyFrames[0].DepartureTime = uint32(curPathTime * IN_MILLISECONDS);
     }
     for (size_t i = 1; i < keyFrames.size(); ++i)
     {
         curPathTime += keyFrames[i - 1].TimeTo;
         if (keyFrames[i].IsStopFrame())
         {
             keyFrames[i].ArriveTime = uint32(curPathTime * IN_MILLISECONDS);
             keyFrames[i - 1].NextArriveTime = keyFrames[i].ArriveTime;
             curPathTime += float(keyFrames[i].Node->delay);
             keyFrames[i].DepartureTime = uint32(curPathTime * IN_MILLISECONDS);
         }
         else
         {
             curPathTime -= keyFrames[i].TimeTo;
             keyFrames[i].ArriveTime = uint32(curPathTime * IN_MILLISECONDS);
             keyFrames[i - 1].NextArriveTime = keyFrames[i].ArriveTime;
             keyFrames[i].DepartureTime = keyFrames[i].ArriveTime;
         }
     }
     keyFrames.back().NextArriveTime = keyFrames.back().DepartureTime;
     transport->pathTime = keyFrames.back().DepartureTime;
 }
References TransportTemplate::accelDist, TransportTemplate::accelTime, TaxiPathNodeEntry::actionFlag, ASSERT, Movement::Spline< length_type >::evaluate_derivative(), IN_MILLISECONDS, TransportTemplate::inInstance, Movement::Spline< length_type >::init_spline(), Movement::SplineBase::init_spline_custom(), KeyFrame::InitialOrientation, Movement::Spline< length_type >::initLengths(), TransportTemplate::keyFrames, Movement::Spline< length_type >::length(), M_PI, TaxiPathNodeEntry::mapid, TransportTemplate::mapsUsed, Movement::SplineBase::ModeCatmullrom, GameObjectTemplate::moTransport, KeyFrame::Node, Position::NormalizeOrientation(), TransportTemplate::pathTime, sMapStore, Movement::Spline< length_type >::Spline(), sTaxiPathNodesByPath, G3D::Vector3::x, TaxiPathNodeEntry::x, G3D::Vector3::y, TaxiPathNodeEntry::y, and TaxiPathNodeEntry::z.
Referenced by LoadTransportTemplates().
GetTransportAnimInfo()
TransportAnimation const* TransportMgr::GetTransportAnimInfo (uint32 entry) const inline
Definition at line 128 of file TransportMgr.h.
     {
         TransportAnimationContainer::const_iterator itr = _transportAnimations.find(entry);
         if (itr != _transportAnimations.end())
             return &itr->second;
         return nullptr;
     }
References _transportAnimations.
GetTransportTemplate()
TransportTemplate const* TransportMgr::GetTransportTemplate (uint32 entry) const inline
Definition at line 120 of file TransportMgr.h.
     {
         TransportTemplates::const_iterator itr = _transportTemplates.find(entry);
         if (itr != _transportTemplates.end())
             return &itr->second;
         return nullptr;
     }
References _transportTemplates.
Referenced by CreateTransport(), and SpawnContinentTransports().
instance()
TransportMgr * TransportMgr::instance () static
Definition at line 39 of file TransportMgr.cpp.
 {
     static TransportMgr instance;
     return &instance;
 }
Referenced by CreateTransport().
LoadTransportTemplates()
void TransportMgr::LoadTransportTemplates ()
Definition at line 50 of file TransportMgr.cpp.
 {
     uint32 oldMSTime = getMSTime();
     QueryResult result = WorldDatabase.Query("SELECT entry FROM gameobject_template WHERE type = 15 ORDER BY entry ASC");
     if (!result)
     {
         LOG_INFO("server.loading", ">> Loaded 0 transport templates. DB table `gameobject_template` has no transports!");
         return;
     }
     uint32 count = 0;
     do
     {
         Field* fields = result->Fetch();
         uint32 entry = fields[0].GetUInt32();
         GameObjectTemplate const* goInfo = sObjectMgr->GetGameObjectTemplate(entry);
         if (goInfo == nullptr)
         {
             LOG_ERROR("entities.transport", "Transport %u has no associated GameObjectTemplate from `gameobject_template` , skipped.", entry);
             continue;
         }
         if (goInfo->moTransport.taxiPathId >= sTaxiPathNodesByPath.size())
         {
             LOG_ERROR("entities.transport", "Transport %u (name: %s) has an invalid path specified in `gameobject_template`.`data0` (%u) field, skipped.", entry, goInfo->name.c_str(), goInfo->moTransport.taxiPathId);
             continue;
         }
         // paths are generated per template, saves us from generating it again in case of instanced transports
         TransportTemplate& transport = _transportTemplates[entry];
         transport.entry = entry;
         GeneratePath(goInfo, &transport);
         // transports in instance are only on one map
         if (transport.inInstance)
             _instanceTransports[*transport.mapsUsed.begin()].insert(entry);
         ++count;
     } while (result->NextRow());
     LOG_INFO("server.loading", ">> Loaded %u transport templates in %u ms", count, GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
 }
References _instanceTransports, _transportTemplates, count(), TransportTemplate::entry, GeneratePath(), getMSTime(), GetMSTimeDiffToNow(), Field::GetUInt32(), TransportTemplate::inInstance, LOG_ERROR, LOG_INFO, TransportTemplate::mapsUsed, GameObjectTemplate::moTransport, GameObjectTemplate::name, sObjectMgr, sTaxiPathNodesByPath, and WorldDatabase.
operator=()
TransportMgr& TransportMgr::operator= (TransportMgr const &) private
SpawnContinentTransports()
void TransportMgr::SpawnContinentTransports ()
Definition at line 421 of file TransportMgr.cpp.
 {
     if (_transportTemplates.empty())
         return;
     uint32 oldMSTime, count = 0;
     oldMSTime = getMSTime();
     QueryResult result;
     if (sWorld->getBoolConfig(CONFIG_ENABLE_CONTINENT_TRANSPORT))
     {
         result = WorldDatabase.Query("SELECT guid, entry FROM transports");
         if (result)
         {
             do
             {
                 Field* fields = result->Fetch();
                 ObjectGuid::LowType guid = fields[0].GetUInt32();
                 uint32 entry = fields[1].GetUInt32();
                 if (TransportTemplate const* tInfo = GetTransportTemplate(entry))
                     if (!tInfo->inInstance)
                         if (CreateTransport(entry, guid))
                             ++count;
             } while (result->NextRow());
         }
         LOG_INFO("server.loading", ">> Spawned %u continent motion transports in %u ms", count, GetMSTimeDiffToNow(oldMSTime));
         LOG_INFO("server.loading", " ");
         if (sWorld->getBoolConfig(CONFIG_ENABLE_CONTINENT_TRANSPORT_PRELOADING))
         {
             // pussywizard: preload grids for continent static transports
             oldMSTime = getMSTime();
             result = WorldDatabase.Query("SELECT map, position_x, position_y FROM gameobject g JOIN gameobject_template t ON g.id = t.entry WHERE t.type = 11");
             count = 0;
             if (result)
             {
                 do
                 {
                     Field* fields = result->Fetch();
                     uint16 mapId = fields[0].GetUInt16();
                     float x = fields[1].GetFloat();
                     float y = fields[2].GetFloat();
                     MapEntry const* mapEntry = sMapStore.LookupEntry(mapId);
                     if (mapEntry && !mapEntry->Instanceable())
                         if (Map* map = sMapMgr->CreateBaseMap(mapId))
{
                             map->LoadGrid(x, y);
                             ++count;
                         }
                 } while (result->NextRow());
             }
             LOG_INFO("server.loading", ">> Preloaded grids for %u continent static transports in %u ms", count, GetMSTimeDiffToNow(oldMSTime));
         }
     }
 }
References _transportTemplates, CONFIG_ENABLE_CONTINENT_TRANSPORT, CONFIG_ENABLE_CONTINENT_TRANSPORT_PRELOADING, count(), CreateTransport(), Field::GetFloat(), getMSTime(), GetMSTimeDiffToNow(), GetTransportTemplate(), Field::GetUInt16(), Field::GetUInt32(), MapEntry::Instanceable(), LOG_INFO, sMapMgr, sMapStore, sWorld, WorldDatabase, G3D::x, and G3D::y.
Unload()
void TransportMgr::Unload ()
Definition at line 45 of file TransportMgr.cpp.
 {
     _transportTemplates.clear();
 }
References _transportTemplates.
Friends And Related Function Documentation
LoadDBCStores
void LoadDBCStores (std::string const &) friend
Definition at line 256 of file DBCStores.cpp.
 {
     uint32 oldMSTime = getMSTime();
     std::string dbcPath = dataPath + "dbc/";
     StoreProblemList bad_dbc_files;
     uint32 availableDbcLocales = 0xFFFFFFFF;
 #define LOAD_DBC(store, file, dbtable) LoadDBC(availableDbcLocales, bad_dbc_files, store, dbcPath, file, dbtable)
     LOAD_DBC(sAreaTableStore,                       "AreaTable.dbc",                        "areatable_dbc");
     LOAD_DBC(sAchievementStore,                     "Achievement.dbc",                      "achievement_dbc");
     LOAD_DBC(sAchievementCategoryStore,             "Achievement_Category.dbc",             "achievement_category_dbc");
     LOAD_DBC(sAchievementCriteriaStore,             "Achievement_Criteria.dbc",             "achievement_criteria_dbc");
     LOAD_DBC(sAreaGroupStore,                       "AreaGroup.dbc",                        "areagroup_dbc");
     LOAD_DBC(sAreaPOIStore,                         "AreaPOI.dbc",                          "areapoi_dbc");
     LOAD_DBC(sAuctionHouseStore,                    "AuctionHouse.dbc",                     "auctionhouse_dbc");
     LOAD_DBC(sBankBagSlotPricesStore,               "BankBagSlotPrices.dbc",                "bankbagslotprices_dbc");
     LOAD_DBC(sBattlemasterListStore,                "BattlemasterList.dbc",                 "battlemasterlist_dbc");
     LOAD_DBC(sBarberShopStyleStore,                 "BarberShopStyle.dbc",                  "barbershopstyle_dbc");
     LOAD_DBC(sCharStartOutfitStore,                 "CharStartOutfit.dbc",                  "charstartoutfit_dbc");
     LOAD_DBC(sCharTitlesStore,                      "CharTitles.dbc",                       "chartitles_dbc");
     LOAD_DBC(sChatChannelsStore,                    "ChatChannels.dbc",                     "chatchannels_dbc");
     LOAD_DBC(sChrClassesStore,                      "ChrClasses.dbc",                       "chrclasses_dbc");
     LOAD_DBC(sChrRacesStore,                        "ChrRaces.dbc",                         "chrraces_dbc");
     LOAD_DBC(sCinematicCameraStore,                 "CinematicCamera.dbc",                  "cinematiccamera_dbc");
     LOAD_DBC(sCinematicSequencesStore,              "CinematicSequences.dbc",               "cinematicsequences_dbc");
     LOAD_DBC(sCreatureDisplayInfoStore,             "CreatureDisplayInfo.dbc",              "creaturedisplayinfo_dbc");
     LOAD_DBC(sCreatureFamilyStore,                  "CreatureFamily.dbc",                   "creaturefamily_dbc");
     LOAD_DBC(sCreatureModelDataStore,               "CreatureModelData.dbc",                "creaturemodeldata_dbc");
     LOAD_DBC(sCreatureSpellDataStore,               "CreatureSpellData.dbc",                "creaturespelldata_dbc");
     LOAD_DBC(sCreatureTypeStore,                    "CreatureType.dbc",                     "creaturetype_dbc");
     LOAD_DBC(sCurrencyTypesStore,                   "CurrencyTypes.dbc",                    "currencytypes_dbc");
     LOAD_DBC(sDestructibleModelDataStore,           "DestructibleModelData.dbc",            "destructiblemodeldata_dbc");
     LOAD_DBC(sDungeonEncounterStore,                "DungeonEncounter.dbc",                 "dungeonencounter_dbc");
     LOAD_DBC(sDurabilityCostsStore,                 "DurabilityCosts.dbc",                  "durabilitycosts_dbc");
     LOAD_DBC(sDurabilityQualityStore,               "DurabilityQuality.dbc",                "durabilityquality_dbc");
     LOAD_DBC(sEmotesStore,                          "Emotes.dbc",                           "emotes_dbc");
     LOAD_DBC(sEmotesTextStore,                      "EmotesText.dbc",                       "emotestext_dbc");
     LOAD_DBC(sFactionStore,                         "Faction.dbc",                          "faction_dbc");
     LOAD_DBC(sFactionTemplateStore,                 "FactionTemplate.dbc",                  "factiontemplate_dbc");
     LOAD_DBC(sGameObjectDisplayInfoStore,           "GameObjectDisplayInfo.dbc",            "gameobjectdisplayinfo_dbc");
     LOAD_DBC(sGemPropertiesStore,                   "GemProperties.dbc",                    "gemproperties_dbc");
     LOAD_DBC(sGlyphPropertiesStore,                 "GlyphProperties.dbc",                  "glyphproperties_dbc");
     LOAD_DBC(sGlyphSlotStore,                       "GlyphSlot.dbc",                        "glyphslot_dbc");
     LOAD_DBC(sGtBarberShopCostBaseStore,            "gtBarberShopCostBase.dbc",             "gtbarbershopcostbase_dbc");
     LOAD_DBC(sGtCombatRatingsStore,                 "gtCombatRatings.dbc",                  "gtcombatratings_dbc");
     LOAD_DBC(sGtChanceToMeleeCritBaseStore,         "gtChanceToMeleeCritBase.dbc",          "gtchancetomeleecritbase_dbc");
     LOAD_DBC(sGtChanceToMeleeCritStore,             "gtChanceToMeleeCrit.dbc",              "gtchancetomeleecrit_dbc");
     LOAD_DBC(sGtChanceToSpellCritBaseStore,         "gtChanceToSpellCritBase.dbc",          "gtchancetospellcritbase_dbc");
     LOAD_DBC(sGtChanceToSpellCritStore,             "gtChanceToSpellCrit.dbc",              "gtchancetospellcrit_dbc");
     LOAD_DBC(sGtNPCManaCostScalerStore,             "gtNPCManaCostScaler.dbc",              "gtnpcmanacostscaler_dbc");
     LOAD_DBC(sGtOCTClassCombatRatingScalarStore,    "gtOCTClassCombatRatingScalar.dbc",     "gtoctclasscombatratingscalar_dbc");
     LOAD_DBC(sGtOCTRegenHPStore,                    "gtOCTRegenHP.dbc",                     "gtoctregenhp_dbc");
     //LOAD_DBC(sGtOCTRegenMPStore,                  "gtOCTRegenMP.dbc",                     "gtoctregenmp_dbc");       -- not used currently
     LOAD_DBC(sGtRegenHPPerSptStore,                 "gtRegenHPPerSpt.dbc",                  "gtregenhpperspt_dbc");
     LOAD_DBC(sGtRegenMPPerSptStore,                 "gtRegenMPPerSpt.dbc",                  "gtregenmpperspt_dbc");
     LOAD_DBC(sHolidaysStore,                        "Holidays.dbc",                         "holidays_dbc");
     LOAD_DBC(sItemBagFamilyStore,                   "ItemBagFamily.dbc",                    "itembagfamily_dbc");
     LOAD_DBC(sItemDisplayInfoStore,                 "ItemDisplayInfo.dbc",                  "itemdisplayinfo_dbc");
     //LOAD_DBC(sItemCondExtCostsStore,              "ItemCondExtCosts.dbc",                 "itemcondextcosts_dbc");
     LOAD_DBC(sItemExtendedCostStore,                "ItemExtendedCost.dbc",                 "itemextendedcost_dbc");
     LOAD_DBC(sItemLimitCategoryStore,               "ItemLimitCategory.dbc",                "itemlimitcategory_dbc");
     LOAD_DBC(sItemRandomPropertiesStore,            "ItemRandomProperties.dbc",             "itemrandomproperties_dbc");
     LOAD_DBC(sItemRandomSuffixStore,                "ItemRandomSuffix.dbc",                 "itemrandomsuffix_dbc");
     LOAD_DBC(sItemSetStore,                         "ItemSet.dbc",                          "itemset_dbc");
     LOAD_DBC(sLFGDungeonStore,                      "LFGDungeons.dbc",                      "lfgdungeons_dbc");
     LOAD_DBC(sLightStore,                           "Light.dbc",                            "light_dbc");
     LOAD_DBC(sLiquidTypeStore,                      "LiquidType.dbc",                       "liquidtype_dbc");
     LOAD_DBC(sLockStore,                            "Lock.dbc",                             "lock_dbc");
     LOAD_DBC(sMailTemplateStore,                    "MailTemplate.dbc",                     "mailtemplate_dbc");
     LOAD_DBC(sMapStore,                             "Map.dbc",                              "map_dbc");
     LOAD_DBC(sMapDifficultyStore,                   "MapDifficulty.dbc",                    "mapdifficulty_dbc");
     LOAD_DBC(sMovieStore,                           "Movie.dbc",                            "movie_dbc");
     LOAD_DBC(sOverrideSpellDataStore,               "OverrideSpellData.dbc",                "overridespelldata_dbc");
     LOAD_DBC(sPowerDisplayStore,                    "PowerDisplay.dbc",                     "powerdisplay_dbc");
     LOAD_DBC(sPvPDifficultyStore,                   "PvpDifficulty.dbc",                    "pvpdifficulty_dbc");
     LOAD_DBC(sQuestXPStore,                         "QuestXP.dbc",                          "questxp_dbc");
     LOAD_DBC(sQuestFactionRewardStore,              "QuestFactionReward.dbc",               "questfactionreward_dbc");
     LOAD_DBC(sQuestSortStore,                       "QuestSort.dbc",                        "questsort_dbc");
     LOAD_DBC(sRandomPropertiesPointsStore,          "RandPropPoints.dbc",                   "randproppoints_dbc");
     LOAD_DBC(sScalingStatDistributionStore,         "ScalingStatDistribution.dbc",          "scalingstatdistribution_dbc");
     LOAD_DBC(sScalingStatValuesStore,               "ScalingStatValues.dbc",                "scalingstatvalues_dbc");
     LOAD_DBC(sSkillLineStore,                       "SkillLine.dbc",                        "skillline_dbc");
     LOAD_DBC(sSkillLineAbilityStore,                "SkillLineAbility.dbc",                 "skilllineability_dbc");
     LOAD_DBC(sSkillRaceClassInfoStore,              "SkillRaceClassInfo.dbc",               "skillraceclassinfo_dbc");
     LOAD_DBC(sSkillTiersStore,                      "SkillTiers.dbc",                       nullptr); // TODO: add the SQL table!
     LOAD_DBC(sSoundEntriesStore,                    "SoundEntries.dbc",                     "soundentries_dbc");
     LOAD_DBC(sSpellStore,                           "Spell.dbc",                            "spell_dbc");
     LOAD_DBC(sSpellCastTimesStore,                  "SpellCastTimes.dbc",                   "spellcasttimes_dbc");
     LOAD_DBC(sSpellCategoryStore,                   "SpellCategory.dbc",                    "spellcategory_dbc");
     LOAD_DBC(sSpellDifficultyStore,                 "SpellDifficulty.dbc",                  "spelldifficulty_dbc");
     LOAD_DBC(sSpellDurationStore,                   "SpellDuration.dbc",                    "spellduration_dbc");
     LOAD_DBC(sSpellFocusObjectStore,                "SpellFocusObject.dbc",                 "spellfocusobject_dbc");
     LOAD_DBC(sSpellItemEnchantmentStore,            "SpellItemEnchantment.dbc",             "spellitemenchantment_dbc");
     LOAD_DBC(sSpellItemEnchantmentConditionStore,   "SpellItemEnchantmentCondition.dbc",    "spellitemenchantmentcondition_dbc");
     LOAD_DBC(sSpellRadiusStore,                     "SpellRadius.dbc",                      "spellradius_dbc");
     LOAD_DBC(sSpellRangeStore,                      "SpellRange.dbc",                       "spellrange_dbc");
     LOAD_DBC(sSpellRuneCostStore,                   "SpellRuneCost.dbc",                    "spellrunecost_dbc");
     LOAD_DBC(sSpellShapeshiftStore,                 "SpellShapeshiftForm.dbc",              "spellshapeshiftform_dbc");
     LOAD_DBC(sSpellVisualStore,                     "SpellVisual.dbc",                      "spellvisual_dbc");
     LOAD_DBC(sStableSlotPricesStore,                "StableSlotPrices.dbc",                 "stableslotprices_dbc");
     LOAD_DBC(sSummonPropertiesStore,                "SummonProperties.dbc",                 "summonproperties_dbc");
     LOAD_DBC(sTalentStore,                          "Talent.dbc",                           "talent_dbc");
     LOAD_DBC(sTalentTabStore,                       "TalentTab.dbc",                        "talenttab_dbc");
     LOAD_DBC(sTaxiNodesStore,                       "TaxiNodes.dbc",                        "taxinodes_dbc");
     LOAD_DBC(sTaxiPathStore,                        "TaxiPath.dbc",                         "taxipath_dbc");
     LOAD_DBC(sTaxiPathNodeStore,                    "TaxiPathNode.dbc",                     "taxipathnode_dbc");
     LOAD_DBC(sTeamContributionPointsStore,          "TeamContributionPoints.dbc",           "teamcontributionpoints_dbc");
     LOAD_DBC(sTotemCategoryStore,                   "TotemCategory.dbc",                    "totemcategory_dbc");
     LOAD_DBC(sTransportAnimationStore,              "TransportAnimation.dbc",               "transportanimation_dbc");
     LOAD_DBC(sTransportRotationStore,               "TransportRotation.dbc",                "transportrotation_dbc");
     LOAD_DBC(sVehicleStore,                         "Vehicle.dbc",                          "vehicle_dbc");
     LOAD_DBC(sVehicleSeatStore,                     "VehicleSeat.dbc",                      "vehicleseat_dbc");
     LOAD_DBC(sWMOAreaTableStore,                    "WMOAreaTable.dbc",                     "wmoareatable_dbc");
     LOAD_DBC(sWorldMapAreaStore,                    "WorldMapArea.dbc",                     "worldmaparea_dbc");
     LOAD_DBC(sWorldMapOverlayStore,                 "WorldMapOverlay.dbc",                  "worldmapoverlay_dbc");
 #undef LOAD_DBC
     for (CharStartOutfitEntry const* outfit : sCharStartOutfitStore)
         sCharStartOutfitMap[outfit->Race | (outfit->Class << 8) | (outfit->Gender << 16)] = outfit;
     for (FactionEntry const* faction : sFactionStore)
     {
         if (faction->team)
         {
             SimpleFactionsList& flist = sFactionTeamMap[faction->team];
             flist.push_back(faction->ID);
         }
     }
     for (GameObjectDisplayInfoEntry const* info : sGameObjectDisplayInfoStore)
     {
         if (info->maxX < info->minX)
             std::swap(*(float*)(&info->maxX), *(float*)(&info->minX));
         if (info->maxY < info->minY)
             std::swap(*(float*)(&info->maxY), *(float*)(&info->minY));
         if (info->maxZ < info->minZ)
             std::swap(*(float*)(&info->maxZ), *(float*)(&info->minZ));
     }
     // fill data
     for (MapDifficultyEntry const* entry : sMapDifficultyStore)
         sMapDifficultyMap[MAKE_PAIR32(entry->MapId, entry->Difficulty)] = MapDifficulty(entry->resetTime, entry->maxPlayers, entry->areaTriggerText[0] != '\0');
     for (PvPDifficultyEntry const* entry : sPvPDifficultyStore)
         if (entry->bracketId > MAX_BATTLEGROUND_BRACKETS)
             ASSERT(false && "Need update MAX_BATTLEGROUND_BRACKETS by DBC data");
     for (auto i : sSpellStore)
         if (i->Category)
             sSpellsByCategoryStore[i->Category].emplace(false, i->Id);
     for (SkillRaceClassInfoEntry const* entry : sSkillRaceClassInfoStore)
     {
         if (sSkillLineStore.LookupEntry(entry->SkillID))
         {
             SkillRaceClassInfoBySkill.emplace(entry->SkillID, entry);
         }
     }
     for (SkillLineAbilityEntry const* skillLine : sSkillLineAbilityStore)
     {
         SpellEntry const* spellInfo = sSpellStore.LookupEntry(skillLine->Spell);
         if (spellInfo && spellInfo->Attributes & SPELL_ATTR0_PASSIVE)
         {
             for (CreatureFamilyEntry const* cFamily : sCreatureFamilyStore)
             {
                 if (skillLine->SkillLine != cFamily->skillLine[0] && skillLine->SkillLine != cFamily->skillLine[1])
                 {
                     continue;
                 }
                 if (spellInfo->SpellLevel)
                 {
                     continue;
                 }
                 if (skillLine->AcquireMethod != SKILL_LINE_ABILITY_LEARNED_ON_SKILL_LEARN)
                 {
                     continue;
                 }
                 sPetFamilySpellsStore[cFamily->ID].insert(spellInfo->Id);
             }
         }
     }
     // Create Spelldifficulty searcher
     for (SpellDifficultyEntry const* spellDiff : sSpellDifficultyStore)
     {
         SpellDifficultyEntry newEntry;
         memset(newEntry.SpellID, 0, 4 * sizeof(uint32));
         for (uint8 x = 0; x < MAX_DIFFICULTY; ++x)
         {
             if (spellDiff->SpellID[x] <= 0 || !sSpellStore.LookupEntry(spellDiff->SpellID[x]))
             {
                 if (spellDiff->SpellID[x] > 0) //don't show error if spell is <= 0, not all modes have spells and there are unknown negative values
                     LOG_ERROR("sql.sql", "spelldifficulty_dbc: spell %i at field id: %u at spellid %i does not exist in SpellStore (spell.dbc), loaded as 0", spellDiff->SpellID[x], spellDiff->ID, x);
                 newEntry.SpellID[x] = 0; // spell was <= 0 or invalid, set to 0
             }
             else
                 newEntry.SpellID[x] = spellDiff->SpellID[x];
         }
         if (newEntry.SpellID[0] <= 0 || newEntry.SpellID[1] <= 0) // id0-1 must be always set!
             continue;
         for (uint8 x = 0; x < MAX_DIFFICULTY; ++x)
             if (newEntry.SpellID[x])
                 sSpellMgr->SetSpellDifficultyId(uint32(newEntry.SpellID[x]), spellDiff->ID);
     }
     // create talent spells set
     for (TalentEntry const* talentInfo : sTalentStore)
         for (uint8 j = 0; j < MAX_TALENT_RANK; ++j)
             if (talentInfo->RankID[j])
                 sTalentSpellPosMap[talentInfo->RankID[j]] = TalentSpellPos(talentInfo->TalentID, j);
     // prepare fast data access to bit pos of talent ranks for use at inspecting
     {
         // now have all max ranks (and then bit amount used for store talent ranks in inspect)
         for (uint32 talentTabId = 1; talentTabId < sTalentTabStore.GetNumRows(); ++talentTabId)
         {
             TalentTabEntry const* talentTabInfo = sTalentTabStore.LookupEntry(talentTabId);
             if (!talentTabInfo)
                 continue;
             // prevent memory corruption; otherwise cls will become 12 below
             if ((talentTabInfo->ClassMask & CLASSMASK_ALL_PLAYABLE) == 0)
                 continue;
             // store class talent tab pages
             for (uint32 cls = 1; cls < MAX_CLASSES; ++cls)
                 if (talentTabInfo->ClassMask & (1 << (cls - 1)))
                     sTalentTabPages[cls][talentTabInfo->tabpage] = talentTabId;
         }
     }
     for (uint32 i = 1; i < sTaxiPathStore.GetNumRows(); ++i)
         if (TaxiPathEntry const* entry = sTaxiPathStore.LookupEntry(i))
             sTaxiPathSetBySource[entry->from][entry->to] = TaxiPathBySourceAndDestination(entry->ID, entry->price);
     // Calculate path nodes count
     uint32 pathCount = sTaxiPathStore.GetNumRows();
     std::vector<uint32> pathLength;
     pathLength.resize(pathCount);                           // 0 and some other indexes not used
     for (uint32 i = 1; i < sTaxiPathNodeStore.GetNumRows(); ++i)
         if (TaxiPathNodeEntry const* entry = sTaxiPathNodeStore.LookupEntry(i))
             if (pathLength[entry->path] < entry->index + 1)
                 pathLength[entry->path] = entry->index + 1;
     // Set path length
     sTaxiPathNodesByPath.resize(pathCount);                 // 0 and some other indexes not used
     for (uint32 i = 1; i < sTaxiPathNodesByPath.size(); ++i)
         sTaxiPathNodesByPath[i].resize(pathLength[i]);
     // fill data
     for (TaxiPathNodeEntry const* entry : sTaxiPathNodeStore)
         sTaxiPathNodesByPath[entry->path][entry->index] = entry;
     // Initialize global taxinodes mask
     // include existed nodes that have at least single not spell base (scripted) path
     {
         std::set<uint32> spellPaths;
         for (SpellEntry const* sInfo : sSpellStore)
             for (uint8 j = 0; j < MAX_SPELL_EFFECTS; ++j)
                 if (sInfo->Effect[j] == SPELL_EFFECT_SEND_TAXI)
                     spellPaths.insert(sInfo->EffectMiscValue[j]);
         memset(sTaxiNodesMask, 0, sizeof(sTaxiNodesMask));
         memset(sOldContinentsNodesMask, 0, sizeof(sOldContinentsNodesMask));
         memset(sHordeTaxiNodesMask, 0, sizeof(sHordeTaxiNodesMask));
         memset(sAllianceTaxiNodesMask, 0, sizeof(sAllianceTaxiNodesMask));
         memset(sDeathKnightTaxiNodesMask, 0, sizeof(sDeathKnightTaxiNodesMask));
         for (uint32 i = 1; i < sTaxiNodesStore.GetNumRows(); ++i)
         {
             TaxiNodesEntry const* node = sTaxiNodesStore.LookupEntry(i);
             if (!node)
                 continue;
             TaxiPathSetBySource::const_iterator src_i = sTaxiPathSetBySource.find(i);
             if (src_i != sTaxiPathSetBySource.end() && !src_i->second.empty())
             {
                 bool ok = false;
                 for (TaxiPathSetForSource::const_iterator dest_i = src_i->second.begin(); dest_i != src_i->second.end(); ++dest_i)
                 {
                     // not spell path
                     if (dest_i->second.price || spellPaths.find(dest_i->second.ID) == spellPaths.end())
                     {
                         ok = true;
                         break;
                     }
                 }
                 if (!ok)
                     continue;
             }
             // valid taxi network node
             uint8  field   = (uint8)((i - 1) / 32);
             uint32 submask = 1 << ((i - 1) % 32);
             sTaxiNodesMask[field] |= submask;
             if (node->MountCreatureID[0] && node->MountCreatureID[0] != 32981)
                 sHordeTaxiNodesMask[field] |= submask;
             if (node->MountCreatureID[1] && node->MountCreatureID[1] != 32981)
                 sAllianceTaxiNodesMask[field] |= submask;
             if (node->MountCreatureID[0] == 32981 || node->MountCreatureID[1] == 32981)
                 sDeathKnightTaxiNodesMask[field] |= submask;
             // old continent node (+ nodes virtually at old continents, check explicitly to avoid loading map files for zone info)
             if (node->map_id < 2 || i == 82 || i == 83 || i == 93 || i == 94)
                 sOldContinentsNodesMask[field] |= submask;
             // fix DK node at Ebon Hold and Shadow Vault flight master
             if (i == 315 || i == 333)
                 ((TaxiNodesEntry*)node)->MountCreatureID[1] = 32981;
         }
     }
     for (TransportAnimationEntry const* anim : sTransportAnimationStore)
         sTransportMgr->AddPathNodeToTransport(anim->TransportEntry, anim->TimeSeg, anim);
     for (TransportRotationEntry const* rot : sTransportRotationStore)
         sTransportMgr->AddPathRotationToTransport(rot->TransportEntry, rot->TimeSeg, rot);
     for (WMOAreaTableEntry const* entry : sWMOAreaTableStore)
         sWMOAreaInfoByTripple[WMOAreaTableKey(entry->rootId, entry->adtId, entry->groupId)] = entry;
     // error checks
     if (bad_dbc_files.size() >= DBCFileCount)
     {
         LOG_ERROR("dbc", "Incorrect DataDir value in worldserver.conf or ALL required *.dbc files (%d) not found by path: %sdbc", DBCFileCount, dataPath.c_str());
         exit(1);
     }
     else if (!bad_dbc_files.empty())
     {
         std::string str;
         for (StoreProblemList::iterator i = bad_dbc_files.begin(); i != bad_dbc_files.end(); ++i)
             str += *i + "\n";
         LOG_ERROR("dbc", "Some required *.dbc files (%u from %d) not found or not compatible:\n%s", (uint32)bad_dbc_files.size(), DBCFileCount, str.c_str());
         exit(1);
     }
     // Check loaded DBC files proper version
     if (!sAreaTableStore.LookupEntry(4987)         ||       // last area added in 3.3.5a
             !sCharTitlesStore.LookupEntry(177)         ||       // last char title added in 3.3.5a
             !sGemPropertiesStore.LookupEntry(1629)     ||       // last added spell in 3.3.5a
             !sItemExtendedCostStore.LookupEntry(2997)  ||       // last item extended cost added in 3.3.5a
             !sMapStore.LookupEntry(724)                ||       // last map added in 3.3.5a
             !sSpellStore.LookupEntry(80864)            )        // last client known item added in 3.3.5a
     {
         LOG_ERROR("dbc", "You have _outdated_ DBC data. Please extract correct versions from current using client.");
         exit(1);
     }
     LoadM2Cameras(dataPath);
     LOG_INFO("server.loading", ">> Initialized %d data stores in %u ms", DBCFileCount, GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
 }
Member Data Documentation
_instanceTransports
TransportInstanceMap TransportMgr::_instanceTransports private
Definition at line 157 of file TransportMgr.h.
Referenced by CreateInstanceTransports(), and LoadTransportTemplates().
_transportAnimations
TransportAnimationContainer TransportMgr::_transportAnimations private
Definition at line 159 of file TransportMgr.h.
Referenced by AddPathNodeToTransport(), AddPathRotationToTransport(), and GetTransportAnimInfo().
_transportTemplates
TransportTemplates TransportMgr::_transportTemplates private
Definition at line 154 of file TransportMgr.h.
Referenced by GetTransportTemplate(), LoadTransportTemplates(), SpawnContinentTransports(), and Unload().
The documentation for this class was generated from the following files:
src/server/game/Maps/TransportMgr.h
src/server/game/Maps/TransportMgr.cpp