Azerotcore-wotlk: OPvPCapturePointHP Class Reference
OPvPCapturePointHP Class Reference
#include <OutdoorPvPHP.h>
Public Member Functions
OPvPCapturePointHP (OutdoorPvP *pvp, OutdoorPvPHPTowerType type)
void ChangeState () override
void SendChangePhase () override
void FillInitialWorldStates (WorldPacket &data) override
bool HandlePlayerEnter (Player *player) override
void HandlePlayerLeave (Player *player) override
Public Member Functions inherited from OPvPCapturePoint
OPvPCapturePoint (OutdoorPvP *pvp)
virtual ~OPvPCapturePoint ()
void SendUpdateWorldState (uint32 field, uint32 value)
void SendObjectiveComplete (uint32 id, ObjectGuid guid=ObjectGuid::Empty)
bool IsInsideObjective (Player *player) const
virtual bool HandleCustomSpell (Player *player, uint32 spellId, GameObject *go)
virtual int32 HandleOpenGo (Player *player, GameObject *go)
virtual bool Update (uint32 diff)
virtual void ChangeTeam (TeamId)
virtual bool HandleGossipOption (Player *player, Creature *creature, uint32 gossipid)
virtual bool CanTalkTo (Player *player, Creature *c, GossipMenuItems const &gso)
virtual bool HandleDropFlag (Player *player, uint32 spellId)
virtual void DeleteSpawns ()
void AddGO (uint32 type, ObjectGuid::LowType guid, uint32 entry=0)
void AddCre (uint32 type, ObjectGuid::LowType guid, uint32 entry=0)
bool SetCapturePointData (uint32 entry, uint32 map, float x, float y, float z, float o=0, float rotation0=0, float rotation1=0, float rotation2=0, float rotation3=0)
Private Attributes
OutdoorPvPHPTowerType m_TowerType
Additional Inherited Members
Public Attributes inherited from OPvPCapturePoint
ObjectGuid::LowType m_capturePointSpawnId
GameObject * m_capturePoint
Protected Member Functions inherited from OPvPCapturePoint
bool AddObject (uint32 type, uint32 entry, uint32 map, float x, float y, float z, float o, float rotation0, float rotation1, float rotation2, float rotation3)
bool AddCreature (uint32 type, uint32 entry, uint32 map, float x, float y, float z, float o, uint32 spawntimedelay=0)
bool DelCreature (uint32 type)
bool DelObject (uint32 type)
bool DelCapturePoint ()
Protected Attributes inherited from OPvPCapturePoint
PlayerSet m_activePlayers [2]
float m_maxValue
float m_minValue
float m_maxSpeed
float m_value
TeamId m_team
ObjectiveStates m_OldState
ObjectiveStates m_State
uint32 m_neutralValuePct
OutdoorPvP * m_PvP
std::map< uint32, ObjectGuid::LowType > m_Objects
std::map< uint32, ObjectGuid::LowType > m_Creatures
std::map< ObjectGuid::LowType, uint32 > m_ObjectTypes
std::map< ObjectGuid::LowType, uint32 > m_CreatureTypes
Detailed Description
Definition at line 88 of file OutdoorPvPHP.h.
Constructor & Destructor Documentation
OPvPCapturePointHP()
OPvPCapturePointHP::OPvPCapturePointHP (OutdoorPvP * pvp, OutdoorPvPHPTowerType type)
Definition at line 37 of file OutdoorPvPHP.cpp.
     : OPvPCapturePoint(pvp), m_TowerType(type)
 {
     SetCapturePointData(HPCapturePoints[type].entry,
                         HPCapturePoints[type].map,
                         HPCapturePoints[type].x,
                         HPCapturePoints[type].y,
                         HPCapturePoints[type].z,
                         HPCapturePoints[type].o,
                         HPCapturePoints[type].rot0,
                         HPCapturePoints[type].rot1,
                         HPCapturePoints[type].rot2,
                         HPCapturePoints[type].rot3);
     AddObject(type,
               HPTowerFlags[type].entry,
               HPTowerFlags[type].map,
               HPTowerFlags[type].x,
               HPTowerFlags[type].y,
               HPTowerFlags[type].z,
               HPTowerFlags[type].o,
               HPTowerFlags[type].rot0,
               HPTowerFlags[type].rot1,
               HPTowerFlags[type].rot2,
               HPTowerFlags[type].rot3);
 }
References OPvPCapturePoint::AddObject(), HPCapturePoints, HPTowerFlags, and OPvPCapturePoint::SetCapturePointData().
Member Function Documentation
ChangeState()
void OPvPCapturePointHP::ChangeState () override virtual
Implements OPvPCapturePoint.
Definition at line 171 of file OutdoorPvPHP.cpp.
 {
     uint32 field = 0;
     switch (m_OldState)
     {
         case OBJECTIVESTATE_NEUTRAL:
             field = HP_MAP_N[m_TowerType];
             break;
         case OBJECTIVESTATE_ALLIANCE:
             field = HP_MAP_A[m_TowerType];
             if (uint32 alliance_towers = ((OutdoorPvPHP*)m_PvP)->GetAllianceTowersControlled())
                 ((OutdoorPvPHP*)m_PvP)->SetAllianceTowersControlled(--alliance_towers);
             sWorld->SendZoneText(OutdoorPvPHPBuffZones[0], sObjectMgr->GetAcoreStringForDBCLocale(HP_LANG_LOSE_A[m_TowerType]));
             break;
         case OBJECTIVESTATE_HORDE:
             field = HP_MAP_H[m_TowerType];
             if (uint32 horde_towers = ((OutdoorPvPHP*)m_PvP)->GetHordeTowersControlled())
                 ((OutdoorPvPHP*)m_PvP)->SetHordeTowersControlled(--horde_towers);
             sWorld->SendZoneText(OutdoorPvPHPBuffZones[0], sObjectMgr->GetAcoreStringForDBCLocale(HP_LANG_LOSE_H[m_TowerType]));
             break;
         case OBJECTIVESTATE_NEUTRAL_ALLIANCE_CHALLENGE:
             field = HP_MAP_N[m_TowerType];
             break;
         case OBJECTIVESTATE_NEUTRAL_HORDE_CHALLENGE:
             field = HP_MAP_N[m_TowerType];
             break;
         case OBJECTIVESTATE_ALLIANCE_HORDE_CHALLENGE:
             field = HP_MAP_A[m_TowerType];
             break;
         case OBJECTIVESTATE_HORDE_ALLIANCE_CHALLENGE:
             field = HP_MAP_H[m_TowerType];
             break;
     }
     // send world state update
     if (field)
     {
         m_PvP->SendUpdateWorldState(field, 0);
         field = 0;
     }
     uint32 artkit = 21;
     uint32 artkit2 = HP_TowerArtKit_N[m_TowerType];
     switch (m_State)
     {
         case OBJECTIVESTATE_NEUTRAL:
             field = HP_MAP_N[m_TowerType];
             break;
         case OBJECTIVESTATE_ALLIANCE:
             {
                 field = HP_MAP_A[m_TowerType];
                 artkit = 2;
                 artkit2 = HP_TowerArtKit_A[m_TowerType];
                 uint32 alliance_towers = ((OutdoorPvPHP*)m_PvP)->GetAllianceTowersControlled();
                 if (alliance_towers < 3)
                     ((OutdoorPvPHP*)m_PvP)->SetAllianceTowersControlled(++alliance_towers);
                 sWorld->SendZoneText(OutdoorPvPHPBuffZones[0], sObjectMgr->GetAcoreStringForDBCLocale(HP_LANG_CAPTURE_A[m_TowerType]));
                 break;
             }
         case OBJECTIVESTATE_HORDE:
             {
                 field = HP_MAP_H[m_TowerType];
                 artkit = 1;
                 artkit2 = HP_TowerArtKit_H[m_TowerType];
                 uint32 horde_towers = ((OutdoorPvPHP*)m_PvP)->GetHordeTowersControlled();
                 if (horde_towers < 3)
                     ((OutdoorPvPHP*)m_PvP)->SetHordeTowersControlled(++horde_towers);
                 sWorld->SendZoneText(OutdoorPvPHPBuffZones[0], sObjectMgr->GetAcoreStringForDBCLocale(HP_LANG_CAPTURE_H[m_TowerType]));
                 break;
             }
         case OBJECTIVESTATE_NEUTRAL_ALLIANCE_CHALLENGE:
             field = HP_MAP_N[m_TowerType];
             break;
         case OBJECTIVESTATE_NEUTRAL_HORDE_CHALLENGE:
             field = HP_MAP_N[m_TowerType];
             break;
         case OBJECTIVESTATE_ALLIANCE_HORDE_CHALLENGE:
             field = HP_MAP_A[m_TowerType];
             artkit = 2;
             artkit2 = HP_TowerArtKit_A[m_TowerType];
             break;
         case OBJECTIVESTATE_HORDE_ALLIANCE_CHALLENGE:
             field = HP_MAP_H[m_TowerType];
             artkit = 1;
             artkit2 = HP_TowerArtKit_H[m_TowerType];
             break;
     }
     Map* map = sMapMgr->FindMap(530, 0);
     auto bounds = map->GetGameObjectBySpawnIdStore().equal_range(m_capturePointSpawnId);
     for (auto itr = bounds.first; itr != bounds.second; ++itr)
         itr->second->SetGoArtKit(artkit);
     bounds = map->GetGameObjectBySpawnIdStore().equal_range(m_Objects[m_TowerType]);
     for (auto itr = bounds.first; itr != bounds.second; ++itr)
         itr->second->SetGoArtKit(artkit2);
     // send world state update
     if (field)
         m_PvP->SendUpdateWorldState(field, 1);
     // complete quest objective
     if (m_State == OBJECTIVESTATE_ALLIANCE || m_State == OBJECTIVESTATE_HORDE)
         SendObjectiveComplete(HP_CREDITMARKER[m_TowerType]);
 }
References Map::GetGameObjectBySpawnIdStore(), HP_CREDITMARKER, HP_LANG_CAPTURE_A, HP_LANG_CAPTURE_H, HP_LANG_LOSE_A, HP_LANG_LOSE_H, HP_MAP_A, HP_MAP_H, HP_MAP_N, HP_TowerArtKit_A, HP_TowerArtKit_H, HP_TowerArtKit_N, OPvPCapturePoint::m_capturePointSpawnId, OPvPCapturePoint::m_Objects, OPvPCapturePoint::m_OldState, OPvPCapturePoint::m_PvP, OPvPCapturePoint::m_State, m_TowerType, OBJECTIVESTATE_ALLIANCE, OBJECTIVESTATE_ALLIANCE_HORDE_CHALLENGE, OBJECTIVESTATE_HORDE, OBJECTIVESTATE_HORDE_ALLIANCE_CHALLENGE, OBJECTIVESTATE_NEUTRAL, OBJECTIVESTATE_NEUTRAL_ALLIANCE_CHALLENGE, OBJECTIVESTATE_NEUTRAL_HORDE_CHALLENGE, OutdoorPvPHPBuffZones, OPvPCapturePoint::SendObjectiveComplete(), OutdoorPvP::SendUpdateWorldState(), sMapMgr, sObjectMgr, and sWorld.
FillInitialWorldStates()
void OPvPCapturePointHP::FillInitialWorldStates (WorldPacket & data) override virtual
Reimplemented from OPvPCapturePoint.
Definition at line 286 of file OutdoorPvPHP.cpp.
 {
     switch (m_State)
     {
         case OBJECTIVESTATE_ALLIANCE:
         case OBJECTIVESTATE_ALLIANCE_HORDE_CHALLENGE:
             data << uint32(HP_MAP_N[m_TowerType]) << uint32(0);
             data << uint32(HP_MAP_A[m_TowerType]) << uint32(1);
             data << uint32(HP_MAP_H[m_TowerType]) << uint32(0);
             break;
         case OBJECTIVESTATE_HORDE:
         case OBJECTIVESTATE_HORDE_ALLIANCE_CHALLENGE:
             data << uint32(HP_MAP_N[m_TowerType]) << uint32(0);
             data << uint32(HP_MAP_A[m_TowerType]) << uint32(0);
             data << uint32(HP_MAP_H[m_TowerType]) << uint32(1);
             break;
         case OBJECTIVESTATE_NEUTRAL:
         case OBJECTIVESTATE_NEUTRAL_ALLIANCE_CHALLENGE:
         case OBJECTIVESTATE_NEUTRAL_HORDE_CHALLENGE:
         default:
             data << uint32(HP_MAP_N[m_TowerType]) << uint32(1);
             data << uint32(HP_MAP_A[m_TowerType]) << uint32(0);
             data << uint32(HP_MAP_H[m_TowerType]) << uint32(0);
             break;
     }
 }
References HP_MAP_A, HP_MAP_H, HP_MAP_N, OPvPCapturePoint::m_State, m_TowerType, OBJECTIVESTATE_ALLIANCE, OBJECTIVESTATE_ALLIANCE_HORDE_CHALLENGE, OBJECTIVESTATE_HORDE, OBJECTIVESTATE_HORDE_ALLIANCE_CHALLENGE, OBJECTIVESTATE_NEUTRAL, OBJECTIVESTATE_NEUTRAL_ALLIANCE_CHALLENGE, and OBJECTIVESTATE_NEUTRAL_HORDE_CHALLENGE.
HandlePlayerEnter()
bool OPvPCapturePointHP::HandlePlayerEnter (Player * player) override virtual
Reimplemented from OPvPCapturePoint.
Definition at line 313 of file OutdoorPvPHP.cpp.
 {
     if (OPvPCapturePoint::HandlePlayerEnter(player))
     {
         player->SendUpdateWorldState(HP_UI_TOWER_SLIDER_DISPLAY, 1);
         uint32 phase = (uint32)ceil((m_value + m_maxValue) / (2 * m_maxValue) * 100.0f);
         player->SendUpdateWorldState(HP_UI_TOWER_SLIDER_POS, phase);
         player->SendUpdateWorldState(HP_UI_TOWER_SLIDER_N, m_neutralValuePct);
         return true;
     }
     return false;
 }
References OPvPCapturePoint::HandlePlayerEnter(), HP_UI_TOWER_SLIDER_DISPLAY, HP_UI_TOWER_SLIDER_N, HP_UI_TOWER_SLIDER_POS, OPvPCapturePoint::m_maxValue, OPvPCapturePoint::m_neutralValuePct, OPvPCapturePoint::m_value, and Player::SendUpdateWorldState().
HandlePlayerLeave()
void OPvPCapturePointHP::HandlePlayerLeave (Player * player) override virtual
Reimplemented from OPvPCapturePoint.
Definition at line 326 of file OutdoorPvPHP.cpp.
 {
     player->SendUpdateWorldState(HP_UI_TOWER_SLIDER_DISPLAY, 0);
     OPvPCapturePoint::HandlePlayerLeave(player);
 }
References OPvPCapturePoint::HandlePlayerLeave(), HP_UI_TOWER_SLIDER_DISPLAY, and Player::SendUpdateWorldState().
SendChangePhase()
void OPvPCapturePointHP::SendChangePhase () override virtual
Reimplemented from OPvPCapturePoint.
Definition at line 276 of file OutdoorPvPHP.cpp.
 {
     SendUpdateWorldState(HP_UI_TOWER_SLIDER_N, m_neutralValuePct);
     // send these updates to only the ones in this objective
     uint32 phase = (uint32)ceil((m_value + m_maxValue) / (2 * m_maxValue) * 100.0f);
     SendUpdateWorldState(HP_UI_TOWER_SLIDER_POS, phase);
     // send this too, sometimes the slider disappears, dunno why :(
     SendUpdateWorldState(HP_UI_TOWER_SLIDER_DISPLAY, 1);
 }
References HP_UI_TOWER_SLIDER_DISPLAY, HP_UI_TOWER_SLIDER_N, HP_UI_TOWER_SLIDER_POS, OPvPCapturePoint::m_maxValue, OPvPCapturePoint::m_neutralValuePct, OPvPCapturePoint::m_value, and OPvPCapturePoint::SendUpdateWorldState().
Member Data Documentation
m_TowerType
OutdoorPvPHPTowerType OPvPCapturePointHP::m_TowerType private
Definition at line 104 of file OutdoorPvPHP.h.
Referenced by ChangeState(), and FillInitialWorldStates().
The documentation for this class was generated from the following files:
src/server/scripts/OutdoorPvP/OutdoorPvPHP.h
src/server/scripts/OutdoorPvP/OutdoorPvPHP.cpp