Azerotcore-wotlk: boss_yoggsaron_voice::boss_yoggsaron_voiceAI Struct Reference
boss_yoggsaron_voice::boss_yoggsaron_voiceAI Struct Reference
Public Member Functions
boss_yoggsaron_voiceAI (Creature *pCreature)
void Reset () override
void SpellHitTarget (Unit *target, const SpellInfo *spellInfo) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
GuidVector _targets
uint32 _current
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 2233 of file boss_yoggsaron.cpp.
Constructor & Destructor Documentation
boss_yoggsaron_voiceAI()
boss_yoggsaron_voice::boss_yoggsaron_voiceAI::boss_yoggsaron_voiceAI (Creature * pCreature) inline
Definition at line 2235 of file boss_yoggsaron.cpp.
                                                     : NullCreatureAI(pCreature)
         {
             _targets.clear();
             _current = 0;
         }
References _current, and _targets.
Member Function Documentation
Reset()
void boss_yoggsaron_voice::boss_yoggsaron_voiceAI::Reset () inline override virtual
Reimplemented from UnitAI.
Definition at line 2245 of file boss_yoggsaron.cpp.
         {
             me->CastSpell(me, SPELL_INSANE_PERIODIC, true);
         }
References Unit::CastSpell(), CreatureAI::me, and SPELL_INSANE_PERIODIC.
SpellHitTarget()
void boss_yoggsaron_voice::boss_yoggsaron_voiceAI::SpellHitTarget (Unit * target, const SpellInfo * spellInfo) inline override virtual
Reimplemented from CreatureAI.
Definition at line 2250 of file boss_yoggsaron.cpp.
         {
             if (spellInfo->Id == SPELL_INSANE1)
             {
                 // Drive Me Crazy achievement failed
                 if (me->GetInstanceScript())
                     if (Creature* yogg = ObjectAccessor::GetCreature(*me, me->GetInstanceScript()->GetGuidData(TYPE_YOGGSARON)))
                         yogg->AI()->DoAction(ACTION_FAILED_DRIVE_ME_CRAZY);
                 events.ScheduleEvent(40, 8000);
                 _targets.push_back(target->GetGUID());
             }
         }
References _targets, ACTION_FAILED_DRIVE_ME_CRAZY, ObjectAccessor::GetCreature(), Object::GetGUID(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), SpellInfo::Id, CreatureAI::me, SPELL_INSANE1, and TYPE_YOGGSARON.
UpdateAI()
void boss_yoggsaron_voice::boss_yoggsaron_voiceAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 2264 of file boss_yoggsaron.cpp.
         {
             events.Update(diff);
             switch (events.ExecuteEvent())
             {
                 case 40:
                     {
                         ObjectGuid _guid = _targets.at(_current);
                         ++_current;
                         if (Player* player = ObjectAccessor::GetPlayer(*me, _guid))
{
                             me->PlayDirectSound(15760, player);
                             me->Whisper("Destroy them minion, your master commands it!", LANG_UNIVERSAL, player);
                         }
                         break;
                     }
             }
         }
References _current, _targets, ObjectAccessor::GetPlayer(), LANG_UNIVERSAL, CreatureAI::me, WorldObject::PlayDirectSound(), and Unit::Whisper().
Member Data Documentation
_current
uint32 boss_yoggsaron_voice::boss_yoggsaron_voiceAI::_current
Definition at line 2243 of file boss_yoggsaron.cpp.
Referenced by boss_yoggsaron_voiceAI(), and UpdateAI().
_targets
GuidVector boss_yoggsaron_voice::boss_yoggsaron_voiceAI::_targets
Definition at line 2242 of file boss_yoggsaron.cpp.
Referenced by boss_yoggsaron_voiceAI(), SpellHitTarget(), and UpdateAI().
events
EventMap boss_yoggsaron_voice::boss_yoggsaron_voiceAI::events
Definition at line 2241 of file boss_yoggsaron.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_yoggsaron.cpp