Azerotcore-wotlk: WGWorkshop Struct Reference
WGWorkshop Struct Reference
#include <BattlefieldWG.h>
Public Member Functions
WGWorkshop (BattlefieldWG *_bf, uint8 _workshopId)
void GiveControlTo (TeamId team, bool init)
void UpdateGraveyardAndWorkshop ()
void Save ()
Public Attributes
BattlefieldWG * bf
uint8 workshopId
TeamId teamControl
uint32 state
Detailed Description
Definition at line 1441 of file BattlefieldWG.h.
Constructor & Destructor Documentation
WGWorkshop()
WGWorkshop::WGWorkshop (BattlefieldWG * _bf, uint8 _workshopId) inline
Definition at line 1452 of file BattlefieldWG.h.
     {
         ASSERT(_bf || _workshopId < WG_MAX_WORKSHOP);
         bf = _bf;
         workshopId = _workshopId;
         teamControl = TEAM_NEUTRAL;
         state = BATTLEFIELD_WG_OBJECTSTATE_NONE;
     }
References ASSERT, BATTLEFIELD_WG_OBJECTSTATE_NONE, bf, state, TEAM_NEUTRAL, teamControl, WG_MAX_WORKSHOP, and workshopId.
Member Function Documentation
GiveControlTo()
void WGWorkshop::GiveControlTo (TeamId team, bool init) inline
Definition at line 1462 of file BattlefieldWG.h.
     {
         switch (team)
         {
             case TEAM_NEUTRAL:
                 {
                     // Send warning message to all player to inform a faction attack to a workshop
                     // alliance / horde attacking a workshop
                     bf->SendWarningToAllInZone(teamControl ? WorkshopsData[workshopId].attackText : (WorkshopsData[workshopId].attackText + 2));
                     break;
                 }
             case TEAM_ALLIANCE:
             case TEAM_HORDE:
                 {
                     // Updating worldstate
                     state = team == TEAM_ALLIANCE ? BATTLEFIELD_WG_OBJECTSTATE_ALLIANCE_INTACT : BATTLEFIELD_WG_OBJECTSTATE_HORDE_INTACT;
                     bf->SendUpdateWorldState(WorkshopsData[workshopId].worldstate, state);
                     // Warning message
                     if (!init)                              // workshop taken - alliance
                         bf->SendWarningToAllInZone(team == TEAM_ALLIANCE ? WorkshopsData[workshopId].takenText : (WorkshopsData[workshopId].takenText + 2));
                     // Found associate graveyard and update it
                     if (workshopId < BATTLEFIELD_WG_WORKSHOP_KEEP_WEST)
                         if (bf->GetGraveyardById(workshopId))
                             bf->GetGraveyardById(workshopId)->GiveControlTo(team);
                     teamControl = team;
                     break;
                 }
         }
         if (!init)
         {
             bf->UpdateCounterVehicle(false);
             bf->CapturePointTaken(bf->GetAreaByGraveyardId(workshopId));
         }
     }
References BATTLEFIELD_WG_OBJECTSTATE_ALLIANCE_INTACT, BATTLEFIELD_WG_OBJECTSTATE_HORDE_INTACT, BATTLEFIELD_WG_WORKSHOP_KEEP_WEST, bf, BattlefieldWG::CapturePointTaken(), BattlefieldWG::GetAreaByGraveyardId(), Battlefield::GetGraveyardById(), BfGraveyard::GiveControlTo(), Battlefield::SendUpdateWorldState(), Battlefield::SendWarningToAllInZone(), state, TEAM_ALLIANCE, TEAM_HORDE, TEAM_NEUTRAL, teamControl, BattlefieldWG::UpdateCounterVehicle(), workshopId, and WorkshopsData.
Referenced by WintergraspCapturePoint::ChangeTeam(), BattlefieldWG::SetupBattlefield(), and UpdateGraveyardAndWorkshop().
Save()
void WGWorkshop::Save () inline
Definition at line 1509 of file BattlefieldWG.h.
     {
         sWorld->setWorldState(WorkshopsData[workshopId].worldstate, state);
     }
References state, sWorld, workshopId, and WorkshopsData.
UpdateGraveyardAndWorkshop()
void WGWorkshop::UpdateGraveyardAndWorkshop () inline
Definition at line 1501 of file BattlefieldWG.h.
     {
         if (workshopId < BATTLEFIELD_WG_WORKSHOP_KEEP_WEST)
             bf->GetGraveyardById(workshopId)->GiveControlTo(TeamId(teamControl));
         else
             GiveControlTo(bf->GetDefenderTeam(), true);
     }
References BATTLEFIELD_WG_WORKSHOP_KEEP_WEST, bf, Battlefield::GetDefenderTeam(), Battlefield::GetGraveyardById(), BfGraveyard::GiveControlTo(), GiveControlTo(), teamControl, and workshopId.
Member Data Documentation
bf
BattlefieldWG* WGWorkshop::bf
Definition at line 1444 of file BattlefieldWG.h.
Referenced by GiveControlTo(), UpdateGraveyardAndWorkshop(), and WGWorkshop().
state
uint32 WGWorkshop::state
Definition at line 1450 of file BattlefieldWG.h.
Referenced by GiveControlTo(), Save(), and WGWorkshop().
teamControl
TeamId WGWorkshop::teamControl
Definition at line 1448 of file BattlefieldWG.h.
Referenced by GiveControlTo(), UpdateGraveyardAndWorkshop(), and WGWorkshop().
workshopId
uint8 WGWorkshop::workshopId
Definition at line 1446 of file BattlefieldWG.h.
Referenced by GiveControlTo(), Save(), UpdateGraveyardAndWorkshop(), and WGWorkshop().
The documentation for this struct was generated from the following file:
src/server/game/Battlefield/Zones/BattlefieldWG.h