Azerotcore-wotlk: HasInLineCheck Class Reference
HasInLineCheck Class Reference
Public Member Functions
HasInLineCheck (Unit *caster)
bool operator() (WorldObject *unit)
Private Attributes
Unit * _caster
Detailed Description
Definition at line 276 of file boss_lurker_below.cpp.
Constructor & Destructor Documentation
HasInLineCheck()
HasInLineCheck::HasInLineCheck (Unit * caster) inline
Definition at line 279 of file boss_lurker_below.cpp.
 : _caster(caster) { }
Member Function Documentation
operator()()
bool HasInLineCheck::operator() (WorldObject * unit) inline
Definition at line 281 of file boss_lurker_below.cpp.
     {
         return !_caster->HasInLine(unit, 5.0f) || (unit->GetTypeId() == TYPEID_UNIT && unit->ToUnit()->IsUnderWater());
     }
References _caster, Object::GetTypeId(), Position::HasInLine(), Unit::IsUnderWater(), Object::ToUnit(), and TYPEID_UNIT.
Member Data Documentation
_caster
Unit* HasInLineCheck::_caster private
Definition at line 287 of file boss_lurker_below.cpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_lurker_below.cpp