Azerotcore-wotlk: deps/fmt/include/fmt/core.h File Reference
core.h File Reference
#include <cstdio>
#include <cstring>
#include <iterator>
#include <limits>
#include <string>
#include <type_traits>
Classes
struct type_identity< T >
struct monostate
struct std_string_view< T >
class basic_string_view< Char >
struct is_char< T >
struct is_char< char >
struct compile_string
struct is_compile_string< S >
struct is_string< S >
struct char_t_impl< S, typename >
struct char_t_impl< S, enable_if_t< is_string< S >::value > >
struct error_handler
class basic_format_parse_context< Char, ErrorHandler >
struct formatter< T, Char, Enable >
struct is_contiguous< T >
struct is_contiguous< std::basic_string< Char > >
class buffer< T >
struct buffer_traits
class fixed_buffer_traits
class iterator_buffer< OutputIt, T, Traits >
class iterator_buffer< T *, T >
class iterator_buffer< std::back_insert_iterator< Container >, enable_if_t< is_contiguous< Container >::value, typename Container::value_type > >
class counting_buffer< T >
struct fallback_formatter< T, Char, Enable >
struct view
struct named_arg< Char, T >
struct named_arg_info< Char >
struct arg_data< T, Char, NUM_ARGS, NUM_NAMED_ARGS >
struct arg_data< T, Char, NUM_ARGS, 0 >
struct is_named_arg< T >
struct is_statically_named_arg< T >
struct is_named_arg< named_arg< Char, T > >
struct type_constant< T, Char >
struct string_value< Char >
struct named_arg_value< Char >
struct custom_value< Context >
class value< Context >
struct unformattable
struct arg_mapper< Context >
class appender
class basic_format_arg< Context >
class basic_format_arg< Context >::handle
struct is_output_iterator< It, T, Enable >
struct is_output_iterator< It, T, void_t< typename std::iterator_traits< It >::iterator_category, decltype(*std::declval< It >()=std::declval< T >())> >
struct is_back_insert_iterator< OutputIt >
struct is_back_insert_iterator< std::back_insert_iterator< Container > >
struct is_contiguous_back_insert_iterator< OutputIt >
struct is_contiguous_back_insert_iterator< std::back_insert_iterator< Container > >
struct is_contiguous_back_insert_iterator< appender >
class locale_ref
class basic_format_context< OutputIt, Char >
class format_arg_store< Context, Args >
class basic_format_args< Context >
struct fill_t< Char >
struct basic_format_specs< Char >
struct arg_ref< Char >
union arg_ref< Char >::value
struct dynamic_format_specs< Char >
struct auto_id
class specs_setter< Char >
class dynamic_specs_handler< ParseContext >
class compile_parse_context< Char, ErrorHandler >
struct float_specs
class specs_checker< Handler >
class format_string_checker< Char, ErrorHandler, Args >
struct formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > >
struct basic_runtime< Char >
class basic_format_string< Char, Args >
struct format_to_n_result< OutputIt >
Namespaces
align
sign
Macros
#define FMT_VERSION 80001
#define FMT_CLANG_VERSION 0
#define FMT_GCC_VERSION 0
#define FMT_GCC_PRAGMA(arg)
#define FMT_HAS_GXX_CXX11 0
#define FMT_ICC_VERSION 0
#define FMT_NVCC 0
#define FMT_MSC_VER 0
#define FMT_MSC_WARNING(...)
#define FMT_HAS_FEATURE(x) 0
#define FMT_HAS_INCLUDE(x) 0
#define FMT_HAS_CPP_ATTRIBUTE(x) 0
#define FMT_HAS_CPP14_ATTRIBUTE(attribute) (__cplusplus >= 201402L && FMT_HAS_CPP_ATTRIBUTE(attribute))
#define FMT_HAS_CPP17_ATTRIBUTE(attribute) (__cplusplus >= 201703L && FMT_HAS_CPP_ATTRIBUTE(attribute))
#define FMT_USE_CONSTEXPR
#define FMT_CONSTEXPR
#define FMT_CONSTEXPR_DECL
#define FMT_CONSTEXPR_CHAR_TRAITS
#define FMT_OVERRIDE
#define FMT_EXCEPTIONS 1
#define FMT_USE_NOEXCEPT 0
#define FMT_DETECTED_NOEXCEPT throw()
#define FMT_HAS_CXX11_NOEXCEPT 0
#define FMT_NOEXCEPT FMT_DETECTED_NOEXCEPT
#define FMT_NORETURN
#define FMT_MAYBE_UNUSED
#define FMT_FALLTHROUGH
#define FMT_USE_FLOAT 1
#define FMT_USE_DOUBLE 1
#define FMT_USE_LONG_DOUBLE 1
#define FMT_INLINE inline
#define FMT_USE_INLINE_NAMESPACES 0
#define FMT_INLINE_NAMESPACE namespace
#define FMT_END_NAMESPACE
#define FMT_BEGIN_NAMESPACE
#define FMT_MODULE_EXPORT
#define FMT_MODULE_EXPORT_BEGIN
#define FMT_MODULE_EXPORT_END
#define FMT_BEGIN_DETAIL_NAMESPACE namespace detail {
#define FMT_END_DETAIL_NAMESPACE }
#define FMT_CLASS_API
#define FMT_API
#define FMT_GCC_VISIBILITY_HIDDEN
#define FMT_UNICODE !FMT_MSC_VER
#define FMT_CONSTEVAL
#define FMT_USE_NONTYPE_TEMPLATE_PARAMETERS 0
#define FMT_ENABLE_IF(...) enable_if_t<(__VA_ARGS__), int> = 0
#define FMT_ASSERT(condition, message)
#define FMT_USE_INT128 0
#define FMT_TYPE_CONSTANT(Type, constant)
#define FMT_BUFFER_CONTEXT(Char) basic_format_context<detail::buffer_appender<Char>, Char>
Typedefs
template<bool B, typename T = void>
using enable_if_t = typename std::enable_if< B, T >::type
template<bool B, typename T , typename F >
using conditional_t = typename std::conditional< B, T, F >::type
template<bool B>
using bool_constant = std::integral_constant< bool, B >
template<typename T >
using remove_reference_t = typename std::remove_reference< T >::type
template<typename T >
using remove_cvref_t = typename std::remove_cv< remove_reference_t< T > >::type
template<typename T >
using type_identity_t = typename type_identity< T >::type
using string_view = basic_string_view< char >
template<typename S >
using char_t = typename detail::char_t_impl< S >::type
using format_parse_context = basic_format_parse_context< char >
template<typename T , typename Context >
using has_formatter = std::is_constructible< typename Context::template formatter_type< T > >
template<typename T >
using buffer_appender = conditional_t< std::is_same< T, char >::value, appender, std::back_insert_iterator< buffer< T > >>
template<typename T , typename Char >
using has_fallback_formatter = std::is_constructible< fallback_formatter< T, Char > >
using long_type = conditional_t< long_short, int, long long >
using ulong_type = conditional_t< long_short, unsigned, unsigned long long >
template<typename T , typename Context >
using mapped_type_constant = type_constant< decltype(arg_mapper< Context >().map(std::declval< const T & >())), typename Context::char_type >
template<typename... >
using void_t = void
template<typename Char >
using buffer_context = basic_format_context< detail::buffer_appender< Char >, Char >
using format_context = buffer_context< char >
template<typename T , typename Char = char>
using is_formattable = bool_constant< !std::is_same< decltype(detail::arg_mapper< buffer_context< Char > >().map(std::declval< T >())), detail::unformattable >::value &&!detail::has_fallback_formatter< T, Char >::value >
using format_args = basic_format_args< format_context >
using align_t = align::type
using sign_t = sign::type
using format_specs = basic_format_specs< char >
template<typename... Args>
using format_string = basic_format_string< char, type_identity_t< Args >... >
Enumerations
enum class int128_t
enum class uint128_t
enum class type {
none_type , int_type , uint_type , long_long_type ,
ulong_long_type , int128_type , uint128_type , bool_type ,
char_type , last_integer_type = char_type , float_type , double_type ,
long_double_type , last_numeric_type = long_double_type , cstring_type , string_type ,
pointer_type , custom_type
}
enum { long_short = sizeof(long) == sizeof(int) }
enum { packed_arg_bits = 4 }
enum { max_packed_args = 62 / packed_arg_bits }
enum : unsigned long long { is_unpacked_bit = 1ULL << 63 }
enum : unsigned long long { has_named_args_bit = 1ULL << 62 }
enum align::type {
align::none , align::left , align::right , align::center ,
align::numeric
}
enum sign::type { sign::none , sign::minus , sign::plus , sign::space }
enum class arg_id_kind { none , index , name }
enum class float_format : unsigned char { general , exp , fixed , hex }
Functions
template<typename... T>
FMT_CONSTEXPR void ignore_unused (const T &...)
constexpr FMT_BEGIN_DETAIL_NAMESPACE FMT_INLINE auto is_constant_evaluated () FMT_NOEXCEPT -> bool
template<typename T >
constexpr auto const_check (T value) -> T
FMT_NORETURN FMT_API void assert_fail (const char *file, int line, const char *message)
template<typename T >
auto convert_for_visit (T) -> monostate
template<typename Int >
FMT_CONSTEXPR auto to_unsigned (Int value) -> typename std::make_unsigned< Int >::type
FMT_MSC_WARNING (suppress :4566) const expr unsigned char micro[]
constexpr auto is_utf8 () -> bool
template<typename Char , FMT_ENABLE_IF(is_char< Char >::value) >
FMT_INLINE auto to_string_view (const Char *s) -> basic_string_view< Char >
template<typename Char , typename Traits , typename Alloc >
auto to_string_view (const std::basic_string< Char, Traits, Alloc > &s) -> basic_string_view< Char >
template<typename Char >
constexpr auto to_string_view (basic_string_view< Char > s) -> basic_string_view< Char >
template<typename Char , FMT_ENABLE_IF(!std::is_empty< detail::std_string_view< Char >>::value) >
auto to_string_view (detail::std_string_view< Char > s) -> basic_string_view< Char >
template<typename S , FMT_ENABLE_IF(is_compile_string< S >::value) >
constexpr auto to_string_view (const S &s) -> basic_string_view< typename S::char_type >
FMT_BEGIN_DETAIL_NAMESPACE void to_string_view (...)
template<typename... , typename S , FMT_ENABLE_IF(!is_compile_string< S >::value) >
FMT_INLINE void check_format_string (const S &)
template<typename... , typename S , FMT_ENABLE_IF(is_compile_string< S >::value) >
void check_format_string (S)
template<typename Container >
FMT_BEGIN_DETAIL_NAMESPACE auto get_container (std::back_insert_iterator< Container > it) -> Container &
template<typename Char , typename InputIt , typename OutputIt >
FMT_CONSTEXPR auto copy_str (InputIt begin, InputIt end, OutputIt out) -> OutputIt
template<typename Char , FMT_ENABLE_IF(std::is_same< Char, char >::value) >
FMT_CONSTEXPR auto copy_str (const Char *begin, const Char *end, Char *out) -> Char *
template<typename T , typename OutputIt >
auto get_buffer (OutputIt out) -> iterator_buffer< OutputIt, T >
template<typename Buffer >
auto get_iterator (Buffer &buf) -> decltype(buf.out())
template<typename T >
auto get_iterator (buffer< T > &buf) -> buffer_appender< T >
template<typename Char >
void init_named_args (named_arg_info< Char > *, int, int)
template<typename Char , typename T , typename... Tail, FMT_ENABLE_IF(!is_named_arg< T >::value) >
void init_named_args (named_arg_info< Char > *named_args, int arg_count, int named_arg_count, const T &, const Tail &... args)
template<typename... Args>
FMT_CONSTEXPR FMT_INLINE void init_named_args (std::nullptr_t, int, int, const Args &...)
template<bool B = false>
constexpr auto count () -> size_t
template<bool B1, bool B2, bool... Tail>
constexpr auto count () -> size_t
template<typename... Args>
constexpr auto count_named_args () -> size_t
FMT_TYPE_CONSTANT (int, int_type)
FMT_TYPE_CONSTANT (unsigned, uint_type)
FMT_TYPE_CONSTANT (long long, long_long_type)
FMT_TYPE_CONSTANT (unsigned long long, ulong_long_type)
FMT_TYPE_CONSTANT (int128_t, int128_type)
FMT_TYPE_CONSTANT (uint128_t, uint128_type)
FMT_TYPE_CONSTANT (bool, bool_type)
FMT_TYPE_CONSTANT (Char, char_type)
FMT_TYPE_CONSTANT (float, float_type)
FMT_TYPE_CONSTANT (double, double_type)
FMT_TYPE_CONSTANT (long double, long_double_type)
FMT_TYPE_CONSTANT (const Char *, cstring_type)
FMT_TYPE_CONSTANT (basic_string_view< Char >, string_type)
FMT_TYPE_CONSTANT (const void *, pointer_type)
constexpr bool is_integral_type (type t)
constexpr bool is_arithmetic_type (type t)
template<typename Context , typename T >
FMT_CONSTEXPR auto make_arg (const T &value) -> basic_format_arg< Context >
template<typename Visitor , typename Context >
FMT_CONSTEXPR FMT_INLINE auto visit_format_arg (Visitor &&vis, const basic_format_arg< Context > &arg) -> decltype(vis(0))
template<typename Char , typename InputIt >
FMT_BEGIN_DETAIL_NAMESPACE auto copy_str (InputIt begin, InputIt end, appender out) -> appender
template<typename >
constexpr auto encode_types () -> unsigned long long
template<typename Context , typename Arg , typename... Args>
constexpr auto encode_types () -> unsigned long long
template<bool IS_PACKED, typename Context , type , typename T , FMT_ENABLE_IF(IS_PACKED) >
FMT_CONSTEXPR FMT_INLINE auto make_arg (const T &val) -> value< Context >
template<bool IS_PACKED, typename Context , type , typename T , FMT_ENABLE_IF(!IS_PACKED) >
auto make_arg (const T &value) -> basic_format_arg< Context >
template<typename Context = format_context, typename... Args>
constexpr auto make_format_args (const Args &... args) -> format_arg_store< Context, Args... >
template<typename Char , typename T >
auto arg (const Char *name, const T &arg) -> detail::named_arg< Char, T >
FMT_BEGIN_DETAIL_NAMESPACE void throw_format_error (const char *message)
template<typename Char >
constexpr bool is_ascii_letter (Char c)
template<typename Char , FMT_ENABLE_IF(std::is_integral< Char >::value) >
constexpr auto to_ascii (Char value) -> Char
template<typename Char >
FMT_CONSTEXPR auto code_point_length (const Char *begin) -> int
template<bool IS_CONSTEXPR, typename T , typename Ptr = const T*>
FMT_CONSTEXPR auto find (Ptr first, Ptr last, T value, Ptr &out) -> bool
template<>
auto find< false, char > (const char *first, const char *last, char value, const char *&out) -> bool
template<typename Char >
FMT_CONSTEXPR auto parse_nonnegative_int (const Char *&begin, const Char *end, int error_value) noexcept -> int
template<typename Char , typename Handler >
FMT_CONSTEXPR auto parse_align (const Char *begin, const Char *end, Handler &&handler) -> const Char *
template<typename Char >
FMT_CONSTEXPR bool is_name_start (Char c)
template<typename Char , typename IDHandler >
FMT_CONSTEXPR auto do_parse_arg_id (const Char *begin, const Char *end, IDHandler &&handler) -> const Char *
template<typename Char , typename IDHandler >
FMT_CONSTEXPR FMT_INLINE auto parse_arg_id (const Char *begin, const Char *end, IDHandler &&handler) -> const Char *
template<typename Char , typename Handler >
FMT_CONSTEXPR auto parse_width (const Char *begin, const Char *end, Handler &&handler) -> const Char *
template<typename Char , typename Handler >
FMT_CONSTEXPR auto parse_precision (const Char *begin, const Char *end, Handler &&handler) -> const Char *
template<typename Char , typename SpecHandler >
FMT_CONSTEXPR FMT_INLINE auto parse_format_specs (const Char *begin, const Char *end, SpecHandler &&handler) -> const Char *
template<typename Char , typename Handler >
FMT_CONSTEXPR auto parse_replacement_field (const Char *begin, const Char *end, Handler &&handler) -> const Char *
template<bool IS_CONSTEXPR, typename Char , typename Handler >
FMT_CONSTEXPR FMT_INLINE void parse_format_string (basic_string_view< Char > format_str, Handler &&handler)
template<typename T , typename ParseContext >
FMT_CONSTEXPR auto parse_format_specs (ParseContext &ctx) -> decltype(ctx.begin())
template<typename ErrorHandler >
FMT_CONSTEXPR void check_int_type_spec (char spec, ErrorHandler &&eh)
template<typename Char , typename ErrorHandler = error_handler>
FMT_CONSTEXPR auto check_char_specs (const basic_format_specs< Char > &specs, ErrorHandler &&eh={}) -> bool
template<typename ErrorHandler = error_handler, typename Char >
FMT_CONSTEXPR auto parse_float_type_spec (const basic_format_specs< Char > &specs, ErrorHandler &&eh={}) -> float_specs
template<typename Char , typename ErrorHandler = error_handler>
FMT_CONSTEXPR auto check_cstring_type_spec (Char spec, ErrorHandler &&eh={}) -> bool
template<typename Char , typename ErrorHandler = error_handler>
FMT_CONSTEXPR void check_string_type_spec (Char spec, ErrorHandler &&eh={})
template<typename Char , typename ErrorHandler >
FMT_CONSTEXPR void check_pointer_type_spec (Char spec, ErrorHandler &&eh)
template<typename... Args, typename Char >
FMT_CONSTEXPR auto get_arg_index_by_name (basic_string_view< Char > name) -> int
template<typename Char >
void vformat_to (buffer< Char > &buf, basic_string_view< Char > fmt, basic_format_args< FMT_BUFFER_CONTEXT(type_identity_t< Char >)> args, locale_ref loc={})
FMT_API void vprint_mojibake (std::FILE *, string_view, format_args)
template<typename S >
auto runtime (const S &s) -> basic_runtime< char_t< S >>
FMT_API auto vformat (string_view fmt, format_args args) -> std::string
template<typename... T>
FMT_INLINE auto format (format_string< T... > fmt, T &&... args) -> std::string
template<typename OutputIt , FMT_ENABLE_IF(detail::is_output_iterator< OutputIt, char >::value) >
auto vformat_to (OutputIt out, string_view fmt, format_args args) -> OutputIt
template<typename OutputIt , typename... T, FMT_ENABLE_IF(detail::is_output_iterator< OutputIt, char >::value) >
FMT_INLINE auto format_to (OutputIt out, format_string< T... > fmt, T &&... args) -> OutputIt
template<typename OutputIt , typename... T, FMT_ENABLE_IF(detail::is_output_iterator< OutputIt, char >::value) >
auto vformat_to_n (OutputIt out, size_t n, string_view fmt, format_args args) -> format_to_n_result< OutputIt >
template<typename OutputIt , typename... T, FMT_ENABLE_IF(detail::is_output_iterator< OutputIt, char >::value) >
FMT_INLINE auto format_to_n (OutputIt out, size_t n, format_string< T... > fmt, const T &... args) -> format_to_n_result< OutputIt >
template<typename... T>
FMT_INLINE auto formatted_size (format_string< T... > fmt, T &&... args) -> size_t
FMT_API void vprint (string_view fmt, format_args args)
FMT_API void vprint (std::FILE *f, string_view fmt, format_args args)
template<typename... T>
FMT_INLINE void print (format_string< T... > fmt, T &&... args)
template<typename... T>
FMT_INLINE void print (std::FILE *f, format_string< T... > fmt, T &&... args)
Variables
constexpr int invalid_arg_index = -1
Macro Definition Documentation
FMT_API
#define FMT_API
Definition at line 264 of file core.h.
FMT_ASSERT
#define FMT_ASSERT (condition, message)
Value:
      ((condition) /* void() fails with -Winvalid-constexpr on clang 4.0.1 */ \
           ? (void)0                                                          \
           : ::fmt::detail::assert_fail(__FILE__, __LINE__, (message)))
Definition at line 372 of file core.h.
FMT_BEGIN_DETAIL_NAMESPACE
#define FMT_BEGIN_DETAIL_NAMESPACE namespace detail {
Definition at line 244 of file core.h.
FMT_BEGIN_NAMESPACE
#define FMT_BEGIN_NAMESPACE
Value:
    namespace fmt {           \
    FMT_INLINE_NAMESPACE v8 {
Definition at line 235 of file core.h.
FMT_BUFFER_CONTEXT
#define FMT_BUFFER_CONTEXT (Char) basic_format_context<detail::buffer_appender<Char>, Char>
Definition at line 1641 of file core.h.
FMT_CLANG_VERSION
#define FMT_CLANG_VERSION 0
Definition at line 24 of file core.h.
FMT_CLASS_API
#define FMT_CLASS_API
Definition at line 256 of file core.h.
FMT_CONSTEVAL
#define FMT_CONSTEVAL
Definition at line 296 of file core.h.
FMT_CONSTEXPR
#define FMT_CONSTEXPR
Definition at line 99 of file core.h.
FMT_CONSTEXPR_CHAR_TRAITS
#define FMT_CONSTEXPR_CHAR_TRAITS
Definition at line 116 of file core.h.
FMT_CONSTEXPR_DECL
#define FMT_CONSTEXPR_DECL
Definition at line 100 of file core.h.
FMT_DETECTED_NOEXCEPT
#define FMT_DETECTED_NOEXCEPT throw()
Definition at line 148 of file core.h.
FMT_ENABLE_IF
#define FMT_ENABLE_IF (...) enable_if_t<(__VA_ARGS__), int> = 0
Definition at line 347 of file core.h.
FMT_END_DETAIL_NAMESPACE
#define FMT_END_DETAIL_NAMESPACE }
Definition at line 245 of file core.h.
FMT_END_NAMESPACE
#define FMT_END_NAMESPACE
Value:
      }                       \
      using namespace v8;     \
      }
Definition at line 230 of file core.h.
FMT_EXCEPTIONS
#define FMT_EXCEPTIONS 1
Definition at line 134 of file core.h.
FMT_FALLTHROUGH
#define FMT_FALLTHROUGH
Definition at line 192 of file core.h.
FMT_GCC_PRAGMA
#define FMT_GCC_PRAGMA (arg)
Definition at line 32 of file core.h.
FMT_GCC_VERSION
#define FMT_GCC_VERSION 0
Definition at line 31 of file core.h.
FMT_GCC_VISIBILITY_HIDDEN
#define FMT_GCC_VISIBILITY_HIDDEN
Definition at line 270 of file core.h.
FMT_HAS_CPP14_ATTRIBUTE
#define FMT_HAS_CPP14_ATTRIBUTE (attribute) (__cplusplus >= 201402L && FMT_HAS_CPP_ATTRIBUTE(attribute))
Definition at line 81 of file core.h.
FMT_HAS_CPP17_ATTRIBUTE
#define FMT_HAS_CPP17_ATTRIBUTE (attribute) (__cplusplus >= 201703L && FMT_HAS_CPP_ATTRIBUTE(attribute))
Definition at line 84 of file core.h.
FMT_HAS_CPP_ATTRIBUTE
#define FMT_HAS_CPP_ATTRIBUTE (x) 0
Definition at line 78 of file core.h.
FMT_HAS_CXX11_NOEXCEPT
#define FMT_HAS_CXX11_NOEXCEPT 0
Definition at line 149 of file core.h.
FMT_HAS_FEATURE
#define FMT_HAS_FEATURE (x) 0
Definition at line 64 of file core.h.
FMT_HAS_GXX_CXX11
#define FMT_HAS_GXX_CXX11 0
Definition at line 38 of file core.h.
FMT_HAS_INCLUDE
#define FMT_HAS_INCLUDE (x) 0
Definition at line 72 of file core.h.
FMT_ICC_VERSION
#define FMT_ICC_VERSION 0
Definition at line 44 of file core.h.
FMT_INLINE
#define FMT_INLINE inline
Definition at line 209 of file core.h.
FMT_INLINE_NAMESPACE
#define FMT_INLINE_NAMESPACE namespace
Definition at line 229 of file core.h.
FMT_MAYBE_UNUSED
#define FMT_MAYBE_UNUSED
Definition at line 173 of file core.h.
FMT_MODULE_EXPORT
#define FMT_MODULE_EXPORT
Definition at line 241 of file core.h.
FMT_MODULE_EXPORT_BEGIN
#define FMT_MODULE_EXPORT_BEGIN
Definition at line 242 of file core.h.
FMT_MODULE_EXPORT_END
#define FMT_MODULE_EXPORT_END
Definition at line 243 of file core.h.
FMT_MSC_VER
#define FMT_MSC_VER 0
Definition at line 57 of file core.h.
FMT_MSC_WARNING
#define FMT_MSC_WARNING (...)
Definition at line 58 of file core.h.
FMT_NOEXCEPT
#define FMT_NOEXCEPT FMT_DETECTED_NOEXCEPT
Definition at line 154 of file core.h.
FMT_NORETURN
#define FMT_NORETURN
Definition at line 166 of file core.h.
FMT_NVCC
#define FMT_NVCC 0
Definition at line 50 of file core.h.
FMT_OVERRIDE
#define FMT_OVERRIDE
Definition at line 124 of file core.h.
FMT_TYPE_CONSTANT
#define FMT_TYPE_CONSTANT (Type, constant)
Value:
  template <typename Char>                \
  struct type_constant<Type, Char>        \
      : std::integral_constant<type, type::constant> {}
Definition at line 1075 of file core.h.
FMT_UNICODE
#define FMT_UNICODE !FMT_MSC_VER
Definition at line 285 of file core.h.
FMT_USE_CONSTEXPR
#define FMT_USE_CONSTEXPR
Value:
    (FMT_HAS_FEATURE(cxx_relaxed_constexpr) || FMT_MSC_VER >= 1910 || \
     (FMT_GCC_VERSION >= 600 && __cplusplus >= 201402L)) &&           \
        !FMT_NVCC && !FMT_ICC_VERSION
Definition at line 90 of file core.h.
FMT_USE_DOUBLE
#define FMT_USE_DOUBLE 1
Definition at line 199 of file core.h.
FMT_USE_FLOAT
#define FMT_USE_FLOAT 1
Definition at line 196 of file core.h.
FMT_USE_INLINE_NAMESPACES
#define FMT_USE_INLINE_NAMESPACES 0
Definition at line 218 of file core.h.
FMT_USE_INT128
#define FMT_USE_INT128 0
Definition at line 399 of file core.h.
FMT_USE_LONG_DOUBLE
#define FMT_USE_LONG_DOUBLE 1
Definition at line 202 of file core.h.
FMT_USE_NOEXCEPT
#define FMT_USE_NOEXCEPT 0
Definition at line 140 of file core.h.
FMT_USE_NONTYPE_TEMPLATE_PARAMETERS
#define FMT_USE_NONTYPE_TEMPLATE_PARAMETERS 0
Definition at line 306 of file core.h.
FMT_VERSION
#define FMT_VERSION 80001
Definition at line 19 of file core.h.
Typedef Documentation
align_t
using align_t = align::type
Definition at line 1861 of file core.h.
bool_constant
template<bool B> using bool_constant = std::integral_constant<bool, B>
Definition at line 324 of file core.h.
buffer_appender
template<typename T > using buffer_appender = conditional_t<std::is_same<T, char>::value, appender, std::back_insert_iterator<buffer<T> >>
Definition at line 944 of file core.h.
buffer_context
template<typename Char > using buffer_context = basic_format_context<detail::buffer_appender<Char>, Char>
Definition at line 1636 of file core.h.
char_t
template<typename S > using char_t = typename detail::char_t_impl<S>::type
String's character type.
Definition at line 610 of file core.h.
conditional_t
template<bool B, typename T , typename F > using conditional_t = typename std::conditional<B, T, F>::type
Definition at line 323 of file core.h.
enable_if_t
template<bool B, typename T = void> using enable_if_t = typename std::enable_if<B, T>::type
Definition at line 321 of file core.h.
format_args
using format_args = basic_format_args<format_context>
An alias to basic_format_args<format_context>.
Definition at line 1854 of file core.h.
format_context
using format_context = buffer_context<char>
Definition at line 1638 of file core.h.
format_parse_context
using format_parse_context = basic_format_parse_context<char>
Definition at line 686 of file core.h.
format_specs
using format_specs = basic_format_specs<char>
Definition at line 1917 of file core.h.
format_string
template<typename... Args> using format_string = basic_format_string<char, type_identity_t<Args>...>
Definition at line 2864 of file core.h.
has_fallback_formatter
template<typename T , typename Char > using has_fallback_formatter = std::is_constructible<fallback_formatter<T, Char> >
Definition at line 968 of file core.h.
has_formatter
template<typename T , typename Context > using has_formatter = std::is_constructible<typename Context::template formatter_type<T> >
Definition at line 702 of file core.h.
is_formattable
template<typename T , typename Char = char> using is_formattable = bool_constant< !std::is_same<decltype(detail::arg_mapper<buffer_context<Char> >().map(std::declval<T>())), detail::unformattable>::value && !detail::has_fallback_formatter<T, Char>::value>
Definition at line 1645 of file core.h.
long_type
using long_type = conditional_t<long_short, int, long long>
Definition at line 1196 of file core.h.
mapped_type_constant
template<typename T , typename Context > using mapped_type_constant = type_constant<decltype(arg_mapper<Context>().map(std::declval<const T&>())), typename Context::char_type>
Definition at line 1345 of file core.h.
remove_cvref_t
template<typename T > using remove_cvref_t = typename std::remove_cv<remove_reference_t<T> >::type
Definition at line 328 of file core.h.
remove_reference_t
template<typename T > using remove_reference_t = typename std::remove_reference<T>::type
Definition at line 326 of file core.h.
sign_t
using sign_t = sign::type
Definition at line 1865 of file core.h.
string_view
using string_view = basic_string_view<char>
Definition at line 529 of file core.h.
type_identity_t
template<typename T > using type_identity_t = typename type_identity<T>::type
Definition at line 330 of file core.h.
ulong_type
using ulong_type = conditional_t<long_short, unsigned, unsigned long long>
Definition at line 1197 of file core.h.
void_t
template<typename... > using void_t = void
Definition at line 1501 of file core.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
long_short
Definition at line 1195 of file core.h.
 { long_short = sizeof(long) == sizeof(int) };
anonymous enum
anonymous enum
Enumerator
packed_arg_bits
Definition at line 1349 of file core.h.
 { packed_arg_bits = 4 };
anonymous enum
anonymous enum
Enumerator
max_packed_args
Definition at line 1351 of file core.h.
 { max_packed_args = 62 / packed_arg_bits };
anonymous enum
anonymous enum : unsigned long long
Enumerator
is_unpacked_bit
Definition at line 1352 of file core.h.
 : unsigned long long { is_unpacked_bit = 1ULL << 63 };
anonymous enum
anonymous enum : unsigned long long
Enumerator
has_named_args_bit
Definition at line 1353 of file core.h.
 : unsigned long long { has_named_args_bit = 1ULL << 62 };
arg_id_kind
enum arg_id_kind strong
Enumerator
none
index
name
Definition at line 1921 of file core.h.
 { none, index, name };
float_format
enum float_format : unsigned char strong
Enumerator
general
exp
fixed
hex
Definition at line 2510 of file core.h.
                         : unsigned char {
   general,  // General: exponent notation or fixed point based on magnitude.
   exp,      // Exponent notation with the default precision of 6, e.g. 1.2e-3.
   fixed,    // Fixed point with the default precision of 6, e.g. 0.0012.
   hex
 };
int128_t
enum int128_t strong
Definition at line 402 of file core.h.
 {};
type
enum type strong
Enumerator
none_type
int_type
uint_type
long_long_type
ulong_long_type
int128_type
uint128_type
bool_type
char_type
last_integer_type
float_type
double_type
long_double_type
last_numeric_type
cstring_type
string_type
pointer_type
custom_type
Definition at line 1048 of file core.h.
                 {
   none_type,
   // Integer types should go first,
   int_type,
   uint_type,
   long_long_type,
   ulong_long_type,
   int128_type,
   uint128_type,
   bool_type,
   char_type,
   last_integer_type = char_type,
   // followed by floating-point types.
   float_type,
   double_type,
   long_double_type,
   last_numeric_type = long_double_type,
   cstring_type,
   string_type,
   pointer_type,
   custom_type
 };
uint128_t
enum uint128_t strong
Definition at line 403 of file core.h.
 {};
Function Documentation
arg()
template<typename Char , typename T > auto arg (const Char * name, const T & arg) -> detail::named_arg<Char, T> inline
\rst Returns a named argument to be used in a formatting function. It should only be used in a call to a formatting function or dynamic_format_arg_store::push_back.
Example**::
fmt::print("Elapsed time: {s:.2f} seconds", fmt::arg("s", 1.23)); \endrst
Definition at line 1725 of file core.h.
{
   static_assert(!detail::is_named_arg<T>(), "nested named arguments");
   return {name, arg};
 }
References name.
Referenced by _lf_dynarray_iterate(), cli_advanced_command(), convert_arg(), cs_value(), dynamic_format_arg_store< Context >::emplace_arg(), ChatHandler::extractQuotedArg(), formatter< tuple_join_view< Char, T... >, Char >::format_args(), value< Context >::format_custom_arg(), basic_format_args< Context >::get(), get_arg(), get_dynamic_spec(), getopt_double(), getopt_ll(), getopt_ull(), HandleArgs(), main(), make_arg(), mysql_options(), Acore::ChatCommands::Variant< T1, Ts >::operator=(), prof_emitter_write_cb(), prof_gctx_dump_iter(), prof_gctx_merge_iter(), prof_log_stop(), prof_tctx_dump_iter(), prof_tctx_finish_iter(), prof_tctx_merge_iter(), prof_tdata_dump_iter(), prof_tdata_merge_iter(), prof_tdata_reset_iter(), detail::dynamic_arg_list::push(), dynamic_format_arg_store< Context >::push_back(), quarantine_cleanup(), recursive_iterate(), Player::SendTransferAborted(), setval(), soap_register_plugin_arg(), tsd_cleanup(), tsd_cleanup_wrapper(), vformat_to(), vio_blocking(), vio_new(), Acore::ChatCommands::Variant< T1, Ts >::visit(), visit_format_arg(), vprintf(), and write_int().
assert_fail()
FMT_NORETURN FMT_API void assert_fail (const char * file, int line, const char * message)
check_char_specs()
template<typename Char , typename ErrorHandler = error_handler> FMT_CONSTEXPR auto check_char_specs (const basic_format_specs< Char > & specs, ErrorHandler && eh = {}) -> bool
Definition at line 2498 of file core.h.
                                                         {}) -> bool {
   if (specs.type && specs.type != 'c') {
     check_int_type_spec(specs.type, eh);
     return false;
   }
   if (specs.align == align::numeric || specs.sign != sign::none || specs.alt)
     eh.on_error("invalid format specifier for char");
   return true;
 }
Referenced by formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > >::parse().
check_cstring_type_spec()
template<typename Char , typename ErrorHandler = error_handler> FMT_CONSTEXPR auto check_cstring_type_spec (Char spec, ErrorHandler && eh = {}) -> bool
Definition at line 2573 of file core.h.
                                                                           {})
     -> bool {
   if (spec == 0 || spec == 's') return true;
   if (spec != 'p') eh.on_error("invalid type specifier");
   return false;
 }
Referenced by formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > >::parse(), and write().
check_format_string() [1/2]
template<typename... , typename S , FMT_ENABLE_IF(!is_compile_string< S >::value) > FMT_INLINE void check_format_string (const S &)
Definition at line 590 of file core.h.
{
 #ifdef FMT_ENFORCE_COMPILE_STRING
   static_assert(is_compile_string<S>::value,
                 "FMT_ENFORCE_COMPILE_STRING requires all format strings to use "
                 "FMT_STRING.");
 #endif
 }
Referenced by basic_format_string< Char, Args >::basic_format_string(), and make_args_checked().
check_format_string() [2/2]
template<typename... , typename S , FMT_ENABLE_IF(is_compile_string< S >::value) > void check_format_string (S format_str)
Definition at line 2724 of file core.h.
{
   FMT_CONSTEXPR auto s = to_string_view(format_str);
   using checker = format_string_checker<typename S::char_type, error_handler,
                                         remove_cvref_t<Args>...>;
   FMT_CONSTEXPR bool invalid_format =
       (parse_format_string<true>(s, checker(s, {})), true);
   ignore_unused(invalid_format);
 }
References FMT_CONSTEXPR, ignore_unused(), and to_string_view().
check_int_type_spec()
template<typename ErrorHandler > FMT_CONSTEXPR void check_int_type_spec (char spec, ErrorHandler && eh)
Definition at line 2479 of file core.h.
{
   switch (spec) {
   case 0:
   case 'd':
   case 'x':
   case 'X':
   case 'b':
   case 'B':
   case 'o':
   case 'c':
     break;
   default:
     eh.on_error("invalid type specifier");
     break;
   }
 }
Referenced by formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > >::parse().
check_pointer_type_spec()
template<typename Char , typename ErrorHandler > FMT_CONSTEXPR void check_pointer_type_spec (Char spec, ErrorHandler && eh)
Definition at line 2586 of file core.h.
{
   if (spec != 0 && spec != 'p') eh.on_error("invalid type specifier");
 }
Referenced by formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > >::parse().
check_string_type_spec()
template<typename Char , typename ErrorHandler = error_handler> FMT_CONSTEXPR void check_string_type_spec (Char spec, ErrorHandler && eh = {})
Definition at line 2581 of file core.h.
                                                                          {}) {
   if (spec != 0 && spec != 's') eh.on_error("invalid type specifier");
 }
Referenced by formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > >::parse(), formatter< bytes >::parse(), and write().
code_point_length()
template<typename Char > FMT_CONSTEXPR auto code_point_length (const Char * begin) -> int
Definition at line 2064 of file core.h.
{
   if (const_check(sizeof(Char) != 1)) return 1;
   constexpr char lengths[] = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                               0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 3, 3, 4, 0};
   int len = lengths[static_cast<unsigned char>(*begin) >> 3];
   // Compute the pointer to the next character early so that the next
   // iteration can start working on the next character. Neither Clang
   // nor GCC figure out this reordering on their own.
   return len + !len;
 }
References const_check().
Referenced by parse_align(), and detail::utf8_decode().
const_check()
template<typename T > constexpr auto const_check (T value) -> T constexpr
Definition at line 361 of file core.h.
 { return value; }
Referenced by basic_string_view< Char >::basic_string_view(), code_point_length(), format_duration_unit(), arg_converter< T, Context >::operator()(), formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > >::parse(), dynamic_format_arg_store< Context >::push_back(), safe_duration_cast::safe_duration_cast(), and write().
convert_for_visit()
template<typename T > auto convert_for_visit (T) -> monostate inline
Definition at line 405 of file core.h.
{
   return {};
 }
Referenced by visit_format_arg().
copy_str() [1/3]
template<typename Char , FMT_ENABLE_IF(std::is_same< Char, char >::value) > FMT_CONSTEXPR auto copy_str (const Char * begin, const Char * end, Char * out) -> Char*
Definition at line 734 of file core.h.
              {
   if (is_constant_evaluated())
     return copy_str<Char, const Char*, Char*>(begin, end, out);
   auto size = to_unsigned(end - begin);
   memcpy(out, begin, size);
   return out + size;
 }
References is_constant_evaluated(), memcpy, and to_unsigned().
copy_str() [2/3]
template<typename Char , typename InputIt > FMT_BEGIN_DETAIL_NAMESPACE auto copy_str (InputIt begin, InputIt end, appender out) -> appender
Definition at line 1490 of file core.h.
{
   get_container(out).append(begin, end);
   return out;
 }
References get_container().
copy_str() [3/3]
template<typename Char , typename InputIt , typename OutputIt > FMT_CONSTEXPR auto copy_str (InputIt begin, InputIt end, OutputIt out) -> OutputIt
Definition at line 727 of file core.h.
                 {
   while (begin != end) *out++ = static_cast<Char>(*begin++);
   return out;
 }
count() [1/2]
template<bool B = false> constexpr auto count () -> size_t constexpr
Definition at line 1039 of file core.h.
 { return B ? 1 : 0; }
Referenced by Guild::_BroadcastEvent(), Player::_LoadEquipmentSets(), Object::_LoadIntoDataField(), Player::_LoadSkills(), Guild::BankMoveItemData::_ReserveSpace(), Guild::BankMoveItemData::_StoreItem(), Player::_StoreItem(), Player::_StoreOrEquipNewItem(), Player::AddComboPoints(), Loot::AddItem(), Player::AddItem(), AddObjectHelper(), BattlegroundEY::AllNodesConrolledByTeam(), BattlegroundIC::AllNodesConrolledByTeam(), buffer< T >::append(), UpdateFetcher::Apply(), rcVectorBase< T, H >::assign(), basic_format_string< Char, Args >::basic_format_string(), AddonHandler::BuildAddonPacket(), BattlegroundMgr::BuildBattlegroundListPacket(), AuctionHouseObject::BuildListAuctionItems(), AuctionHouseObject::BuildListBidderItems(), AuctionHouseObject::BuildListOwnerItems(), Player::BuyItemFromVendorSlot(), Player::CalculateCorpseReclaimDelay(), Player::CanAddQuest(), Player::CanBankItem(), Guild::BankMoveItemData::CanStore(), Player::CanStoreItem(), Player::CanStoreItem_InBag(), Player::CanStoreItem_InInventorySlots(), Player::CanStoreItem_InSpecificSlot(), Guild::BankMoveItemData::CanStoreItemInTab(), Player::CanStoreItems(), Player::CanStoreNewItem(), Player::CanTakeMoreSimilarItems(), Player::CanUnequipItems(), Player::CastItemUseSpell(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::CheckAchievementCriteriaMeet(), instance_forge_of_souls::instance_forge_of_souls_InstanceScript::CheckAchievementCriteriaMeet(), instance_naxxramas::instance_naxxramas_InstanceMapScript::CheckAchievementCriteriaMeet(), DisableMgr::CheckQuestDisables(), ckh_rebuild(), MMAP::TerrainBuilder::cleanVertices(), Guild::MoveItemData::CloneItem(), Item::CloneItem(), G3D::FileSystem::Dir::computeZipListing(), ConvertADT(), count(), iterator_buffer< OutputIt, T, Traits >::count(), count_digits_fallback(), spell_ruby_sanctum_rallying_shout::spell_ruby_sanctum_rallying_shout_SpellScript::CountAllies(), Player::Create(), BattlegroundMgr::CreateInitialBattlegrounds(), Item::CreateItem(), G3D::ConvexPolygon::cut(), G3D::ConvexPolyhedron::cut(), boss_taerar::boss_taerarAI::DamageTaken(), DBC::DBC(), G3D::Table< Key, Value, HashFunc, EqualsFunc >::debugGetDeepestBucketSize(), G3D::GImage::decodeICO(), ScriptMgr::DecreaseScheduledScriptCount(), default_local_infile_read(), Player::DestroyItemCount(), MMAP::MapBuilder::discoverTiles(), WorldSession::DoLootRelease(), Spell::EffectActivateRune(), Spell::EffectCreateItem2(), Spell::EffectDispel(), Spell::EffectEnchantItemPerm(), Spell::EffectFeedPet(), Spell::EffectSchoolDMG(), Spell::EffectStealBeneficialBuff(), Spell::EffectSummonType(), Spell::EffectWeaponDmg(), boss_faction_championsAI::EnemiesInRange(), CasterAI::EnterCombat(), AuctionListItemsDelayEvent::Execute(), Doodad::Extract(), MapObject::Extract(), ExtractCameraFiles(), ExtractDBCFiles(), Doodad::ExtractSet(), detail::fill_n(), findopt(), lfg::LFGMgr::FinishDungeon(), floodRegion(), flush_cached_blocks(), flush_key_blocks_int(), formatter< std::tm, Char >::format(), Metric::FormatInfluxDBValue(), detail::fwrite_fully(), generate_tables_ascii(), generate_tables_decode(), Battleground::GetAlivePlayersCountByTeam(), AuctionHouseMgr::GetAuctionDeposit(), Unit::GetAuraCount(), Player::GetAverageItemLevel(), Player::GetAverageItemLevelForDF(), Player::GetCorpseReclaimDelay(), SummonList::GetEntryCount(), G3D::getFileOrDirListZip(), Item::GetGemCountWithID(), Item::GetGemCountWithLimitCategory(), Player::GetItemCount(), Bag::GetItemCount(), Bag::GetItemCountWithLimitCategory(), Player::GetItemCountWithLimitCategory(), VMAP::StaticMapTree::GetModelInstances(), getMSTime(), getMSTimeDiff(), Map::GetPlayersCountExceptGMs(), Player::GiveQuestSourceItem(), misc_commandscript::HandleAddItemCommand(), WorldSession::HandleAuctionListBidderItems(), WorldSession::HandleAuctionListOwnerItemsEvent(), WorldSession::HandleAuctionListPendingSales(), WorldSession::HandleAuctionSellItem(), WorldSession::HandleAutoStoreBankItemOpcode(), WorldSession::HandleBuyItemInSlotOpcode(), WorldSession::HandleBuyItemOpcode(), AuraEffect::HandleChannelDeathItem(), OPvPCapturePointNA::HandleCustomSpell(), debug_commandscript::HandleDebugHostileRefListCommand(), debug_commandscript::HandleDebugPlayCinematicCommand(), debug_commandscript::HandleDebugThreatListCommand(), WorldSession::HandleDestroyItemOpcode(), spell_pilgrims_bounty_feast_on_generic::spell_pilgrims_bounty_feast_on_generic_SpellScript::HandleDummy(), spell_dk_death_strike::HandleDummy(), gobject_commandscript::HandleGameObjectNearCommand(), WorldSession::HandleGMTicketCreateOpcode(), spell_q12690_burst_at_the_seams::HandleKnockBack(), list_commandscript::HandleListCreatureCommand(), list_commandscript::HandleListItemCommand(), list_commandscript::HandleListObjectCommand(), lookup_commandscript::HandleLookupAreaCommand(), lookup_commandscript::HandleLookupCreatureCommand(), lookup_commandscript::HandleLookupEventCommand(), lookup_commandscript::HandleLookupFactionCommand(), lookup_commandscript::HandleLookupItemCommand(), lookup_commandscript::HandleLookupItemSetCommand(), lookup_commandscript::HandleLookupObjectCommand(), lookup_commandscript::HandleLookupQuestCommand(), lookup_commandscript::HandleLookupSkillCommand(), lookup_commandscript::HandleLookupSpellCommand(), lookup_commandscript::HandleLookupSpellIdCommand(), lookup_commandscript::HandleLookupTaxiNodeCommand(), lookup_commandscript::HandleLookupTeleCommand(), WorldSession::HandleMailTakeItem(), npc_commandscript::HandleNpcNearCommand(), WorldSession::HandlePetSetAction(), WorldSession::HandleQueryNextMailTime(), quest_commandscript::HandleQuestComplete(), WorldSession::HandleQuestPOIQuery(), spell_midsummer_fling_torch::spell_midsummer_fling_torch_SpellScript::HandleScript(), WorldSession::HandleSellItemOpcode(), misc_commandscript::HandleSkirmishCommand(), WorldSession::HandleSplitItemOpcode(), spell_item_draenic_pale_ale::HandleSummon(), spell_capacitus_polarity_charge::spell_capacitus_polarity_charge_SpellScript::HandleTargets(), spell_thaddius_pos_neg_charge::spell_thaddius_pos_neg_charge_SpellScript::HandleTargets(), WorldSession::HandleWrapItemOpcode(), Player::HasItemCount(), Player::HasItemOrGemWithIdEquipped(), Player::HasItemOrGemWithLimitCategoryEquipped(), http_post(), http_response(), spell_valkyr_essence::spell_valkyr_essence_auraAuraScript::if(), Indent(), inflate_table(), Movement::SplineBase::init_cyclic_spline(), Movement::Spline< length_type >::init_cyclic_spline(), Movement::SplineBase::init_spline(), Movement::Spline< length_type >::init_spline(), Movement::SplineBase::InitBezier3(), Movement::SplineBase::InitCatmullRom(), Spell::InitEffectExecuteData(), Movement::SplineBase::InitLinear(), OutdoorPvPMgr::InitOutdoorPvP(), inline_mysql_file_fread(), inline_mysql_file_fwrite(), inline_mysql_file_pread(), inline_mysql_file_pwrite(), inline_mysql_file_read(), inline_mysql_file_write(), AchievementMgr::IsCompletedAchievement(), Player::ItemAddedQuestCheck(), Player::ItemRemovedQuestCheck(), DatabaseWorkerPool< T >::KeepAlive(), libmpq__archive_open(), libmpq__decompress_multi(), libmpq__do_decompress_wave(), libmpq__huffman_tree_init(), Channel::List(), list_length(), WaypointMgr::Load(), ObjectMgr::LoadAccessRequirements(), AchievementGlobalMgr::LoadAchievementCriteriaData(), AchievementGlobalMgr::LoadAchievementReferenceList(), LootStore::LoadAndCollectLootIds(), ObjectMgr::LoadAreaTriggers(), ObjectMgr::LoadAreaTriggerScripts(), ObjectMgr::LoadAreaTriggerTeleports(), ArenaTeamMgr::LoadArenaTeams(), AuctionHouseMgr::LoadAuctionItems(), AuctionHouseMgr::LoadAuctions(), World::LoadAutobroadcasts(), BattlegroundMgr::LoadBattleMastersEntry(), ChannelMgr::LoadChannelRights(), ChannelMgr::LoadChannels(), LoadCommonMPQFiles(), ConditionMgr::LoadConditions(), ObjectMgr::LoadCreatureAddons(), ObjectMgr::LoadCreatureClassLevelStats(), FormationMgr::LoadCreatureFormations(), ObjectMgr::LoadCreatureModelInfo(), ObjectMgr::LoadCreatureQuestItems(), ObjectMgr::LoadCreatures(), ObjectMgr::LoadCreatureTemplateAddons(), ObjectMgr::LoadCreatureTemplateResistances(), ObjectMgr::LoadCreatureTemplates(), ObjectMgr::LoadCreatureTemplateSpells(), SpellMgr::LoadEnchantCustomAttr(), ObjectMgr::LoadEquipmentTemplates(), ObjectMgr::LoadExplorationBaseXP(), ObjectMgr::LoadFactionChangeAchievements(), ObjectMgr::LoadFactionChangeItems(), ObjectMgr::LoadFactionChangeQuests(), ObjectMgr::LoadFactionChangeReputations(), ObjectMgr::LoadFactionChangeSpells(), ObjectMgr::LoadFactionChangeTitles(), ObjectMgr::LoadFishingBaseSkillLevel(), AddonMgr::LoadFromDB(), SmartWaypointMgr::LoadFromDB(), CalendarMgr::LoadFromDB(), GameEventMgr::LoadFromDB(), PoolMgr::LoadFromDB(), ObjectMgr::LoadGameObjectAddons(), ObjectMgr::LoadGameObjectForQuests(), ObjectMgr::LoadGameObjectQuestItems(), ObjectMgr::LoadGameobjects(), ObjectMgr::LoadGameObjectTemplate(), ObjectMgr::LoadGameObjectTemplateAddons(), ObjectMgr::LoadGameTele(), World::LoadGlobalPlayerDataStore(), ObjectMgr::LoadGossipText(), Graveyard::LoadGraveyardZones(), GroupMgr::LoadGroups(), GuildMgr::LoadGuilds(), LoadHelper(), GameEventMgr::LoadHolidayDates(), ObjectMgr::LoadInstanceEncounters(), ObjectMgr::LoadInstanceTemplate(), ObjectMgr::LoadItemSetNames(), ObjectMgr::LoadItemTemplates(), lfg::LFGMgr::LoadLFGDungeons(), LootStore::LoadLootTable(), LoadLootTemplates_Creature(), LoadLootTemplates_Disenchant(), LoadLootTemplates_Fishing(), LoadLootTemplates_Gameobject(), LoadLootTemplates_Item(), LoadLootTemplates_Mail(), LoadLootTemplates_Milling(), LoadLootTemplates_Pickpocketing(), LoadLootTemplates_Prospecting(), LoadLootTemplates_Skinning(), LoadLootTemplates_Spell(), ObjectMgr::LoadMailLevelRewards(), MMAP::TerrainBuilder::loadMap(), MMAP::MMapMgr::loadMapData(), ObjectMgr::LoadNPCSpellClickSpells(), ObjectMgr::LoadPageTexts(), PetitionMgr::LoadPetitions(), ObjectMgr::LoadPetLevelInfo(), SpellMgr::LoadPetLevelupSpellMap(), ObjectMgr::LoadPetNames(), ObjectMgr::LoadPlayerInfo(), ObjectMgr::LoadPointsOfInterest(), ObjectMgr::LoadQuestAreaTriggers(), ObjectMgr::LoadQuestMoneyRewards(), ObjectMgr::LoadQuestPOI(), ObjectMgr::LoadQuestRelationsHelper(), LoadRandomEnchantmentsTable(), ObjectMgr::LoadReferenceVendor(), ObjectMgr::LoadReputationOnKill(), ObjectMgr::LoadReputationRewardRate(), ObjectMgr::LoadReputationSpilloverTemplate(), ObjectMgr::LoadReservedPlayersNames(), AchievementGlobalMgr::LoadRewards(), lfg::LFGMgr::LoadRewards(), ObjectMgr::LoadScripts(), SystemMgr::LoadScriptWaypoints(), PetitionMgr::LoadSignatures(), LoadSkillDiscoveryTable(), LoadSkillExtraItemTable(), SpellMgr::LoadSkillLineAbilityMap(), LoadSkillPerfectItemTable(), SmartAIMgr::LoadSmartAIFromDB(), SpellMgr::LoadSpellAreas(), SpellMgr::LoadSpellBonusess(), SpellMgr::LoadSpellCustomAttr(), SpellMgr::LoadSpellEnchantProcData(), SpellMgr::LoadSpellGroups(), SpellMgr::LoadSpellGroupStackRules(), SpellMgr::LoadSpellLinked(), SpellMgr::LoadSpellMixology(), SpellMgr::LoadSpellPetAuras(), SpellMgr::LoadSpellProcEvents(), SpellMgr::LoadSpellProcs(), SpellMgr::LoadSpellRanks(), SpellMgr::LoadSpellRequired(), ObjectMgr::LoadSpellScriptNames(), SpellMgr::LoadSpellTargetPositions(), SpellMgr::LoadSpellThreats(), LootItemStorage::LoadStorageFromDB(), ObjectMgr::LoadTavernAreaTriggers(), ObjectMgr::LoadTempSummons(), TicketMgr::LoadTickets(), ObjectMgr::LoadTrainerSpell(), TransportMgr::LoadTransportTemplates(), ObjectMgr::LoadVehicleAccessories(), ObjectMgr::LoadVehicleTemplateAccessories(), ObjectMgr::LoadVendors(), MMAP::TerrainBuilder::loadVMap(), WardenCheckMgr::LoadWardenChecks(), WardenCheckMgr::LoadWardenOverrides(), WeatherMgr::LoadWeatherData(), World::LoadWorldStates(), lock_wrap(), Guild::PlayerMoveItemData::LogBankEvent(), Guild::BankMoveItemData::LogBankEvent(), lookup_commandscript::LookupPlayerSearchCommand(), main(), make_args_checked(), malloc_read_fd(), malloc_write_fd(), Guild::MassInviteToEvent(), Player::MoneyChanged(), MoneyStringToMoney(), npc_ulduar_snow_mound::npc_ulduar_snow_moundAI::MoveInLineOfSight(), my_MD5Final(), my_qsort(), my_uni_utf8(), my_uni_utf8_no_range(), mysql_stmt_bind_param(), net_clear(), G3D::ThreadSet::numStarted(), ScriptMgr::OnAfterStoreOrEquipNewItem(), spell_valithria_suppression::spell_valithria_suppression_AuraScript::OnApply(), ScriptMgr::OnBeforeBuyItemFromVendor(), ScriptMgr::OnBeforeStoreOrEquipNewItem(), ScriptMgr::OnCreateItem(), go_harpoon_canon::OnGossipHello(), ScriptMgr::OnGroupRateCalculation(), ScriptMgr::OnLootItem(), ScriptMgr::OnQuestRewardItem(), spell_valithria_suppression::spell_valithria_suppression_AuraScript::OnRemove(), spell_hor_shared_suffering::spell_hor_shared_sufferingAuraScript::OnRemove(), anonymous_namespace{Config.cpp}::ParseFile(), ObjectMgr::PlayerCreateInfoAddItemHelper(), npc_barnes::npc_barnesAI::PrepareEncounter(), dtFindNearestPolyQuery::process(), dtCollectPolysQuery::process(), SmartScript::ProcessAction(), SmartScript::ProcessEvent(), DoodadHandler::ProcessInternal(), radixsort_for_str_ptr(), rcVectorBase< T, H >::rcVectorBase(), WorldModelDefinition::Read(), DoodadDefinition::Read(), MapChunkHeader::Read(), MHDR::Read(), ModelHeader::Read(), WorldModelHeader::Read(), DoodadInstance::Read(), DoodadSet::Read(), LiquidHeader::Read(), H2ORenderMask::Read(), H2OHeader::Read(), H2OInformation::Read(), WMOGroupHeader::Read(), WorldModelGroup::ReadBatches(), Model::ReadBoundingTriangles(), DoodadHandler::ReadDoodadDefinitions(), VMAP::WorldModel::readFile(), BIH::readFromFile(), VMAP::GroupModel::readFromFile(), WDT::ReadTileTable(), WorldModelGroup::ReadTriangles(), Battleground::ReadyMarkerClicked(), G3D::ReliableConduit::receiveIntoBuffer(), Player::RefundItem(), reg_requests(), G3D::Array< T, MIN_ELEMENTS >::remove(), LootItemStorage::RemoveEntryFromDB(), LootItemStorage::RemoveStoredLootItem(), rcVectorBase< T, H >::reserve(), G3D::BinaryOutput::reserveBytesWhenOutOfMemory(), basic_memory_buffer< T, SIZE, Allocator >::resize(), Player::ResyncRunes(), Player::RewardHonor(), safe_duration_cast::safe_duration_cast(), scan_tree(), boss_yoggsaron_constrictor_tentacle::boss_yoggsaron_constrictor_tentacleAI::SelectConstrictTarget(), boss_yoggsaron_corruptor_tentacle::boss_yoggsaron_corruptor_tentacleAI::SelectCorruptionTarget(), boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::SelectT(), send_tree(), instance_zulfarrak::instance_zulfarrak_InstanceMapScript::SendAddsUpStairs(), Unit::SendAttackStateUpdate(), Unit::SendChangeCurrentVictimOpcode(), CreatureTextMgr::SendChat(), Player::SendEquipmentSetList(), PlayerMenu::SendGossipMenu(), Player::SendItemRetrievalMail(), WorldSession::SendListInventory(), Player::SendNewItem(), PlayerMenu::SendQuestGiverQuestList(), Player::SendQuestGiverStatusMultiple(), ReputationMgr::SendState(), Unit::SendThreatListUpdate(), WorldSession::SendTrainerList(), OutdoorPvPHP::SetAllianceTowersControlled(), OutdoorPvPTF::SetAllianceTowersControlled(), OutdoorPvPZM::SetAllianceTowersControlled(), Player::SetBankBagSlotCount(), OutdoorPvPHP::SetHordeTowersControlled(), OutdoorPvPTF::SetHordeTowersControlled(), OutdoorPvPZM::SetHordeTowersControlled(), BattlegroundDS::setPipeKnockBackCount(), Player::SetQuestSlotCounter(), lfg::LFGMgr::SetRandomPlayersCount(), lfg::LfgPlayerData::SetRandomPlayersCount(), Player::SetSpecsCount(), sfmt_init_by_array(), MMAP::MapBuilder::shouldSkipTile(), soap_count_attachments(), soap_puthttphdr(), soap_recv_raw(), soap_response(), soap_try_connect_command(), sort_locks(), TransportMgr::SpawnContinentTransports(), PoolGroup< T >::SpawnObject(), boss_razorscale::boss_razorscaleAI::SpellHit(), Unit::SpellPctDamageModsDone(), Player::SplitItem(), Player::StoreItem(), Player::StoreNewItem(), strftime(), brann_bronzebeard::brann_bronzebeardAI::SummonCreatures(), Spell::SummonGuardian(), boss_kelthuzad::boss_kelthuzadAI::SummonHelper(), boss_noth::boss_nothAI::SummonHelper(), npc_anachronos_quest_trigger::npc_anachronos_quest_triggerAI::SummonNextWave(), npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::SummonNextWave(), go_tadpole_cage::go_tadpole_cageAI::SummonTadpoles(), Player::SwapItem(), Spell::TakeAmmo(), Spell::TakeCastItem(), Player::TakeQuestSourceItem(), npc_barnes::npc_barnesAI::Talk(), tcp_connect(), thr_lock_merge_status(), thr_multi_unlock(), thr_print_lock(), thr_print_locks(), Movement::SplineBase::ToString(), buffer< T >::try_resize(), spell_black_temple_spell_absorption::spell_black_temple_spell_absorption_AuraScript::Update(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), boss_taldaram::boss_taldaramAI::UpdateAI(), boss_twin_valkyrAI::UpdateAI(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::UpdateAI(), npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::UpdateAI(), Player::UpdateCorpseReclaimDelay(), World::UpdateGlobalPlayerMails(), Player::UpdateSpecCount(), urandweighted(), ObjectMgr::ValidateSpellScripts(), G3D::BinaryOutput::writeBytes(), Movement::WriteCatmullRomCyclicPath(), Movement::WriteCatmullRomPath(), VMAP::WorldModel::writeFile(), Guild::BankTab::WritePacket(), VMAP::GroupModel::writeToFile(), BIH::writeToFile(), Acore::XP::xp_in_group_rate(), and detail::formatbuf< Char >::xsputn().
count() [2/2]
template<bool B1, bool B2, bool... Tail> constexpr auto count () -> size_t constexpr
Definition at line 1040 of file core.h.
{
   return (B1 ? 1 : 0) + count<B2, Tail...>();
 }
References count().
count_named_args()
template<typename... Args> constexpr auto count_named_args () -> size_t constexpr
Definition at line 1044 of file core.h.
{
   return count<is_named_arg<Args>::value...>();
 }
do_parse_arg_id()
template<typename Char , typename IDHandler > FMT_CONSTEXPR auto do_parse_arg_id (const Char * begin, const Char * end, IDHandler && handler) -> const Char*
Definition at line 2164 of file core.h.
{
   FMT_ASSERT(begin != end, "");
   Char c = *begin;
   if (c >= '0' && c <= '9') {
     int index = 0;
     if (c != '0')
       index =
           parse_nonnegative_int(begin, end, (std::numeric_limits<int>::max)());
     else
       ++begin;
     if (begin == end || (*begin != '}' && *begin != ':'))
       handler.on_error("invalid format string");
     else
       handler(index);
     return begin;
   }
   if (!is_name_start(c)) {
     handler.on_error("invalid format string");
     return begin;
   }
   auto it = begin;
   do {
     ++it;
   } while (it != end && (is_name_start(c = *it) || ('0' <= c && c <= '9')));
   handler(basic_string_view<Char>(begin, to_unsigned(it - begin)));
   return it;
 }
References mpq::c, FMT_ASSERT, index, is_name_start(), max, parse_nonnegative_int(), and to_unsigned().
Referenced by parse_arg_id().
encode_types() [1/2]
template<typename > constexpr auto encode_types () -> unsigned long long constexpr
Definition at line 1542 of file core.h.
{
   return 0;
 }
encode_types() [2/2]
template<typename Context , typename Arg , typename... Args> constexpr auto encode_types () -> unsigned long long constexpr
Definition at line 1547 of file core.h.
{
   return static_cast<unsigned>(mapped_type_constant<Arg, Context>::value) |
          (encode_types<Context, Args...>() << packed_arg_bits);
 }
References packed_arg_bits.
find()
template<bool IS_CONSTEXPR, typename T , typename Ptr = const T*> FMT_CONSTEXPR auto find (Ptr first, Ptr last, T value, Ptr & out) -> bool
Definition at line 2078 of file core.h.
{
   for (out = first; out != last; ++out) {
     if (*out == value) return true;
   }
   return false;
 }
References detail::first().
Referenced by Player::_LoadInventory(), Player::ApplyItemEquipSpell(), BattlegroundMgr::BGArenaType(), BattlegroundMgr::BGQueueTypeId(), BattlegroundMgr::BGTemplateId(), BattlegroundMgr::BuildPvpLogDataPacket(), ObjectMgr::CheckCreatureTemplate(), spell_sha_flurry_proc::CheckProc(), BattlegroundMgr::CreateNewBattleground(), MMAP::MapBuilder::discoverTiles(), find_type(), find_typeset(), BattlefieldWG::FindAndRemoveVehicleFromList(), lfg::LFGQueue::FindGroups(), AchievementGlobalMgr::GetAchievementCriteriaByCondition(), boss_sartharion::boss_sartharionAI::GetData(), SmartAIMgr::GetScript(), AchievementGlobalMgr::GetSpecialAchievementCriteriaByType(), MMAP::MapBuilder::getTileList(), NPCStaveQuestAI::IsAllowedEntry(), ObjectMgr::LoadCreatures(), SmartAIMgr::LoadSmartAIFromDB(), movelink(), parse_format_string(), parse_name(), instance_blood_furnace::instance_blood_furnace_InstanceMapScript::PrisonerDied(), Unit::ProcDamageAndSpellFor(), InstanceMap::Reset(), BattlegroundMgr::ScheduleArenaQueueUpdate(), CreatureTextMgr::SendChat(), Player::SendInitWorldStates(), boss_sartharion::boss_sartharionAI::SetData(), CreatureTextMgr::SetRepeatId(), npc_artorius::npc_artoriusAI::SpellHit(), NPCStaveQuestAI::StoreAttackerGuidValue(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::SummonedCreatureDies(), boss_elder_nadox::boss_elder_nadoxAI::SummonHelpers(), GameObject::Use(), and vprintf().
find< false, char >()
template<> auto find< false, char > (const char * first, const char * last, char value, const char *& out) -> bool inline
Definition at line 2086 of file core.h.
{
   out = static_cast<const char*>(
       std::memchr(first, value, to_unsigned(last - first)));
   return out != nullptr;
 }
References detail::first(), and to_unsigned().
FMT_MSC_WARNING()
FMT_MSC_WARNING (suppress :4566) const
FMT_TYPE_CONSTANT() [1/14]
FMT_TYPE_CONSTANT (basic_string_view< Char > , string_type)
FMT_TYPE_CONSTANT() [2/14]
FMT_TYPE_CONSTANT (bool , bool_type)
FMT_TYPE_CONSTANT() [3/14]
FMT_TYPE_CONSTANT (Char , char_type)
FMT_TYPE_CONSTANT() [4/14]
FMT_TYPE_CONSTANT (const Char * , cstring_type)
FMT_TYPE_CONSTANT() [5/14]
FMT_TYPE_CONSTANT (const void * , pointer_type)
FMT_TYPE_CONSTANT() [6/14]
FMT_TYPE_CONSTANT (double , double_type)
FMT_TYPE_CONSTANT() [7/14]
FMT_TYPE_CONSTANT (float , float_type)
FMT_TYPE_CONSTANT() [8/14]
FMT_TYPE_CONSTANT (int , int_type)
FMT_TYPE_CONSTANT() [9/14]
FMT_TYPE_CONSTANT (int128_t , int128_type)
FMT_TYPE_CONSTANT() [10/14]
FMT_TYPE_CONSTANT (long double , long_double_type)
FMT_TYPE_CONSTANT() [11/14]
FMT_TYPE_CONSTANT (long long , long_long_type)
FMT_TYPE_CONSTANT() [12/14]
FMT_TYPE_CONSTANT (uint128_t , uint128_type)
FMT_TYPE_CONSTANT() [13/14]
FMT_TYPE_CONSTANT (unsigned long long , ulong_long_type)
FMT_TYPE_CONSTANT() [14/14]
FMT_TYPE_CONSTANT (unsigned , uint_type)
format()
template<typename... T> FMT_INLINE auto format (format_string< T... > fmt, T &&... args) -> std::string
\rst Formats args according to specifications in fmt and returns the result as a string.
Example**::
include <fmt/core.h> std::string message = fmt::format("The answer is {}", 42); \endrst
Definition at line 2885 of file core.h.
{
   return vformat(fmt, fmt::make_format_args(args...));
 }
References fmt, make_format_args(), and vformat().
format_to()
template<typename OutputIt , typename... T, FMT_ENABLE_IF(detail::is_output_iterator< OutputIt, char >::value) > FMT_INLINE auto format_to (OutputIt out, format_string< T... > fmt, T &&... args) -> OutputIt
\rst Formats args according to specifications in fmt, writes the result to the output iterator out and returns the iterator past the end of the output range.
Example**::
auto out = std::vector<char>(); fmt::format_to(std::back_inserter(out), "{}", 42); \endrst
Definition at line 2913 of file core.h.
                 {
   return vformat_to(out, fmt, fmt::make_format_args(args...));
 }
References fmt, make_format_args(), and vformat_to().
format_to_n()
template<typename OutputIt , typename... T, FMT_ENABLE_IF(detail::is_output_iterator< OutputIt, char >::value) > FMT_INLINE auto format_to_n (OutputIt out, size_t n, format_string< T... > fmt, const T &... args) -> format_to_n_result<OutputIt>
\rst Formats args according to specifications in fmt, writes up to n characters of the result to the output iterator out and returns the total (not truncated) output size and the iterator past the end of the output range. \endrst
Definition at line 2945 of file core.h.
{
   return vformat_to_n(out, n, fmt, fmt::make_format_args(args...));
 }
References fmt, make_format_args(), and vformat_to_n().
formatted_size()
template<typename... T> FMT_INLINE auto formatted_size (format_string< T... > fmt, T &&... args) -> size_t
Returns the number of chars in the output of format(fmt, args...).
Definition at line 2952 of file core.h.
{
   auto buf = detail::counting_buffer<>();
   detail::vformat_to(buf, string_view(fmt), fmt::make_format_args(args...), {});
   return buf.count();
 }
References fmt, make_format_args(), and vformat_to().
get_arg_index_by_name()
template<typename... Args, typename Char > FMT_CONSTEXPR auto get_arg_index_by_name (basic_string_view< Char > name) -> int
Definition at line 2658 of file core.h.
{
 #if FMT_USE_NONTYPE_TEMPLATE_PARAMETERS
   if constexpr (sizeof...(Args) > 0) {
     return get_arg_index_by_name<0, Args...>(name);
   } else {
     (void)name;
     return invalid_arg_index;
   }
 #else
   (void)name;
   return invalid_arg_index;
 #endif
 }
References invalid_arg_index, and name.
Referenced by format_string_checker< Char, ErrorHandler, Args >::on_arg_id().
get_buffer()
template<typename T , typename OutputIt > auto get_buffer (OutputIt out) -> iterator_buffer<OutputIt, T>
Definition at line 949 of file core.h.
{
   return iterator_buffer<OutputIt, T>(out);
 }
Referenced by vformat_to().
get_container()
template<typename Container > FMT_BEGIN_DETAIL_NAMESPACE auto get_container (std::back_insert_iterator< Container > it) -> Container& inline
Definition at line 716 of file core.h.
                   {
   using bi_iterator = std::back_insert_iterator<Container>;
   struct accessor : bi_iterator {
     accessor(bi_iterator iter) : bi_iterator(iter) {}
     using bi_iterator::container;
   };
   return *accessor(it).container;
 }
Referenced by copy_str(), detail::reserve(), and detail::to_pointer().
get_iterator() [1/2]
template<typename Buffer > auto get_iterator (Buffer & buf) -> decltype(buf.out())
Definition at line 954 of file core.h.
{
   return buf.out();
 }
Referenced by vformat_to().
get_iterator() [2/2]
template<typename T > auto get_iterator (buffer< T > & buf) -> buffer_appender<T>
Definition at line 957 of file core.h.
{
   return buffer_appender<T>(buf);
 }
ignore_unused()
template<typename... T> FMT_CONSTEXPR void ignore_unused (const T & ...)
Definition at line 339 of file core.h.
 {}
Referenced by check_format_string().
init_named_args() [1/3]
template<typename Char > void init_named_args (named_arg_info< Char > * , int , int) inline
Definition at line 1012 of file core.h.
 {}
Referenced by format_arg_store< Context, Args >::format_arg_store(), and init_named_args().
init_named_args() [2/3]
template<typename Char , typename T , typename... Tail, FMT_ENABLE_IF(!is_named_arg< T >::value) > void init_named_args (named_arg_info< Char > * named_args, int arg_count, int named_arg_count, const T & arg, const Tail &... args)
Definition at line 1022 of file core.h.
{
   init_named_args(named_args, arg_count + 1, named_arg_count, args...);
 }
References init_named_args().
init_named_args() [3/3]
template<typename... Args> FMT_CONSTEXPR FMT_INLINE void init_named_args (std::nullptr_t , int , int , const Args & ...)
Definition at line 1036 of file core.h.
                                                               {}
is_arithmetic_type()
constexpr bool is_arithmetic_type (type t) constexpr
Definition at line 1099 of file core.h.
{
   return t > type::none_type && t <= type::last_numeric_type;
 }
References last_numeric_type, and none_type.
Referenced by basic_format_arg< Context >::is_arithmetic(), and specs_checker< Handler >::require_numeric_argument().
is_ascii_letter()
template<typename Char > constexpr bool is_ascii_letter (Char c) constexpr
Definition at line 2048 of file core.h.
{
   return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z');
 }
References mpq::c.
Referenced by parse_format_specs().
is_constant_evaluated()
constexpr FMT_BEGIN_DETAIL_NAMESPACE FMT_INLINE auto is_constant_evaluated () -> bool constexpr
Definition at line 352 of file core.h.
{
 #ifdef __cpp_lib_is_constant_evaluated
   return std::is_constant_evaluated();
 #else
   return false;
 #endif
 }
Referenced by basic_string_view< Char >::basic_string_view(), copy_str(), count_digits(), detail::fill_n(), format_decimal(), and value< Context >::value().
is_integral_type()
constexpr bool is_integral_type (type t) constexpr
Definition at line 1095 of file core.h.
{
   return t > type::none_type && t <= type::last_integer_type;
 }
References last_integer_type, and none_type.
Referenced by specs_checker< Handler >::end_precision(), basic_format_arg< Context >::is_integral(), and specs_checker< Handler >::on_sign().
is_name_start()
template<typename Char > FMT_CONSTEXPR bool is_name_start (Char c)
Definition at line 2159 of file core.h.
{
   return ('a' <= c && c <= 'z') || ('A' <= c && c <= 'Z') || '_' == c;
 }
References mpq::c.
Referenced by do_parse_arg_id().
is_utf8()
constexpr auto is_utf8 () -> bool constexpr
Definition at line 420 of file core.h.
{
   // Avoid buggy sign extensions in MSVC's constant evaluation mode.
   // https://developercommunity.visualstudio.com/t/C-difference-in-behavior-for-unsigned/1233612
   using uchar = unsigned char;
   return FMT_UNICODE || (sizeof(micro) == 3 && uchar(micro[0]) == 0xC2 &&
                          uchar(micro[1]) == 0xB5);
 }
References FMT_UNICODE.
Referenced by detail::do_write(), and print().
make_arg() [1/3]
template<bool IS_PACKED, typename Context , type , typename T , FMT_ENABLE_IF(IS_PACKED) > FMT_CONSTEXPR FMT_INLINE auto make_arg (const T & val) -> value<Context>
Definition at line 1565 of file core.h.
{
   const auto& arg = arg_mapper<Context>().map(val);
   static_assert(
       !std::is_same<decltype(arg), const unformattable&>::value,
       "Cannot format an argument. To make type T formattable provide a "
       "formatter<T> specialization: https://fmt.dev/latest/api.html#udt");
   return {arg};
 }
References arg(), and arg_mapper< Context >::map().
make_arg() [2/3]
template<typename Context , typename T > FMT_CONSTEXPR auto make_arg (const T & value) -> basic_format_arg<Context>
Definition at line 1553 of file core.h.
{
   basic_format_arg<Context> arg;
   arg.type_ = mapped_type_constant<T, Context>::value;
   arg.value_ = arg_mapper<Context>().map(value);
   return arg;
 }
References arg(), and arg_mapper< Context >::map().
make_arg() [3/3]
template<bool IS_PACKED, typename Context , type , typename T , FMT_ENABLE_IF(!IS_PACKED) > auto make_arg (const T & value) -> basic_format_arg<Context> inline
Definition at line 1576 of file core.h.
{
   return make_arg<Context>(value);
 }
make_format_args()
template<typename Context = format_context, typename... Args> constexpr auto make_format_args (const Args &... args) -> format_arg_store<Context, Args...> constexpr
\rst Constructs a ~fmtformat_arg_store object that contains references to arguments and can be implicitly converted to ~fmtformat_args. Context can be omitted in which case it defaults to ~fmt::context. See ~fmtarg for lifetime considerations. \endrst
Definition at line 1708 of file core.h.
{
   return {args...};
 }
Referenced by format(), format_to(), format_to_n(), formatted_size(), fprintf(), print(), buffered_file::print(), printf(), and system_error().
parse_align()
template<typename Char , typename Handler > FMT_CONSTEXPR auto parse_align (const Char * begin, const Char * end, Handler && handler) -> const Char*
Definition at line 2120 of file core.h.
{
   FMT_ASSERT(begin != end, "");
   auto align = align::none;
   auto p = begin + code_point_length(begin);
   if (p >= end) p = begin;
   for (;;) {
     switch (to_ascii(*p)) {
     case '<':
       align = align::left;
       break;
     case '>':
       align = align::right;
       break;
     case '^':
       align = align::center;
       break;
     default:
       break;
     }
     if (align != align::none) {
       if (p != begin) {
         auto c = *begin;
         if (c == '{')
           return handler.on_error("invalid fill character '{'"), begin;
         handler.on_fill(basic_string_view<Char>(begin, to_unsigned(p - begin)));
         begin = p + 1;
       } else
         ++begin;
       handler.on_align(align);
       break;
     } else if (p == begin) {
       break;
     }
     p = begin;
   }
   return begin;
 }
References mpq::c, align::center, code_point_length(), FMT_ASSERT, align::left, align::none, align::right, to_ascii(), and to_unsigned().
Referenced by formatter< std::chrono::duration< Rep, Period >, Char >::do_parse(), and parse_format_specs().
parse_arg_id()
template<typename Char , typename IDHandler > FMT_CONSTEXPR FMT_INLINE auto parse_arg_id (const Char * begin, const Char * end, IDHandler && handler) -> const Char*
Definition at line 2194 of file core.h.
{
   Char c = *begin;
   if (c != '}' && c != ':') return do_parse_arg_id(begin, end, handler);
   handler();
   return begin;
 }
References mpq::c, and do_parse_arg_id().
Referenced by parse_precision(), parse_replacement_field(), and parse_width().
parse_float_type_spec()
template<typename ErrorHandler = error_handler, typename Char > FMT_CONSTEXPR auto parse_float_type_spec (const basic_format_specs< Char > & specs, ErrorHandler && eh = {}) -> float_specs
Definition at line 2529 of file core.h.
                                                              {})
     -> float_specs {
   auto result = float_specs();
   result.showpoint = specs.alt;
   result.locale = specs.localized;
   switch (specs.type) {
   case 0:
     result.format = float_format::general;
     break;
   case 'G':
     result.upper = true;
     FMT_FALLTHROUGH;
   case 'g':
     result.format = float_format::general;
     break;
   case 'E':
     result.upper = true;
     FMT_FALLTHROUGH;
   case 'e':
     result.format = float_format::exp;
     result.showpoint |= specs.precision != 0;
     break;
   case 'F':
     result.upper = true;
     FMT_FALLTHROUGH;
   case 'f':
     result.format = float_format::fixed;
     result.showpoint |= specs.precision != 0;
     break;
   case 'A':
     result.upper = true;
     FMT_FALLTHROUGH;
   case 'a':
     result.format = float_format::hex;
     break;
   default:
     eh.on_error("invalid type specifier");
     break;
   }
   return result;
 }
Referenced by formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > >::parse().
parse_format_specs() [1/2]
template<typename Char , typename SpecHandler > FMT_CONSTEXPR FMT_INLINE auto parse_format_specs (const Char * begin, const Char * end, SpecHandler && handler) -> const Char*
Definition at line 2277 of file core.h.
                    {
   if (begin + 1 < end && begin[1] == '}' && is_ascii_letter(*begin) &&
       *begin != 'L') {
     handler.on_type(*begin++);
     return begin;
   }
   if (begin == end) return begin;
   begin = parse_align(begin, end, handler);
   if (begin == end) return begin;
   // Parse sign.
   switch (to_ascii(*begin)) {
   case '+':
     handler.on_sign(sign::plus);
     ++begin;
     break;
   case '-':
     handler.on_sign(sign::minus);
     ++begin;
     break;
   case ' ':
     handler.on_sign(sign::space);
     ++begin;
     break;
   default:
     break;
   }
   if (begin == end) return begin;
   if (*begin == '#') {
     handler.on_hash();
     if (++begin == end) return begin;
   }
   // Parse zero flag.
   if (*begin == '0') {
     handler.on_zero();
     if (++begin == end) return begin;
   }
   begin = parse_width(begin, end, handler);
   if (begin == end) return begin;
   // Parse precision.
   if (*begin == '.') {
     begin = parse_precision(begin, end, handler);
     if (begin == end) return begin;
   }
   if (*begin == 'L') {
     handler.on_localized();
     ++begin;
   }
   // Parse type.
   if (begin != end && *begin != '}') handler.on_type(*begin++);
   return begin;
 }
References is_ascii_letter(), sign::minus, parse_align(), parse_precision(), parse_width(), sign::plus, sign::space, and to_ascii().
Referenced by formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > >::parse(), dynamic_formatter< Char >::parse(), formatter< bytes >::parse(), and vformat_to().
parse_format_specs() [2/2]
template<typename T , typename ParseContext > FMT_CONSTEXPR auto parse_format_specs (ParseContext & ctx) -> decltype(ctx.begin())
Definition at line 2435 of file core.h.
{
   using char_type = typename ParseContext::char_type;
   using context = buffer_context<char_type>;
   using mapped_type = conditional_t<
       mapped_type_constant<T, context>::value != type::custom_type,
       decltype(arg_mapper<context>().map(std::declval<const T&>())), T>;
   auto f = conditional_t<has_formatter<mapped_type, context>::value,
                          formatter<mapped_type, char_type>,
                          fallback_formatter<T, char_type>>();
   return f.parse(ctx);
 }
References char_type, custom_type, and f().
parse_format_string()
template<bool IS_CONSTEXPR, typename Char , typename Handler > FMT_CONSTEXPR FMT_INLINE void parse_format_string (basic_string_view< Char > format_str, Handler && handler)
Definition at line 2382 of file core.h.
{
   // this is most likely a name-lookup defect in msvc's modules implementation
   using detail::find;
   auto begin = format_str.data();
   auto end = begin + format_str.size();
   if (end - begin < 32) {
     // Use a simple loop instead of memchr for small strings.
     const Char* p = begin;
     while (p != end) {
       auto c = *p++;
       if (c == '{') {
         handler.on_text(begin, p - 1);
         begin = p = parse_replacement_field(p - 1, end, handler);
       } else if (c == '}') {
         if (p == end || *p != '}')
           return handler.on_error("unmatched '}' in format string");
         handler.on_text(begin, p);
         begin = ++p;
       }
     }
     handler.on_text(begin, end);
     return;
   }
   struct writer {
     FMT_CONSTEXPR void operator()(const Char* pbegin, const Char* pend) {
       if (pbegin == pend) return;
       for (;;) {
         const Char* p = nullptr;
         if (!find<IS_CONSTEXPR>(pbegin, pend, Char('}'), p))
           return handler_.on_text(pbegin, pend);
         ++p;
         if (p == pend || *p != '}')
           return handler_.on_error("unmatched '}' in format string");
         handler_.on_text(pbegin, p);
         pbegin = p + 1;
       }
     }
     Handler& handler_;
   } write{handler};
   while (begin != end) {
     // Doing two passes with memchr (one for '{' and another for '}') is up to
     // 2.5x faster than the naive one-pass implementation on big format strings.
     const Char* p = begin;
     if (*begin != '{' && !find<IS_CONSTEXPR>(begin + 1, end, Char('{'), p))
       return write(begin, end);
     write(begin, p);
     begin = parse_replacement_field(p, end, handler);
   }
 }
References mpq::c, basic_string_view< Char >::data(), find(), FMT_CONSTEXPR, parse_replacement_field(), basic_string_view< Char >::size(), and write.
parse_nonnegative_int()
template<typename Char > FMT_CONSTEXPR auto parse_nonnegative_int (const Char *& begin, const Char * end, int error_value) -> int noexcept
Definition at line 2096 of file core.h.
{
   FMT_ASSERT(begin != end && '0' <= *begin && *begin <= '9', "");
   unsigned value = 0, prev = 0;
   auto p = begin;
   do {
     prev = value;
     value = value * 10 + unsigned(*p - '0');
     ++p;
   } while (p != end && '0' <= *p && *p <= '9');
   auto num_digits = p - begin;
   begin = p;
   if (num_digits <= std::numeric_limits<int>::digits10)
     return static_cast<int>(value);
   // Check for overflow.
   const unsigned max = to_unsigned((std::numeric_limits<int>::max)());
   return num_digits == std::numeric_limits<int>::digits10 + 1 &&
                  prev * 10ull + unsigned(p[-1] - '0') <= max
              ? static_cast<int>(value)
              : error_value;
 }
References digits10(), FMT_ASSERT, max, prev(), and to_unsigned().
Referenced by do_parse_arg_id(), parse_header(), parse_precision(), parse_width(), and vprintf().
parse_precision()
template<typename Char , typename Handler > FMT_CONSTEXPR auto parse_precision (const Char * begin, const Char * end, Handler && handler) -> const Char*
Definition at line 2237 of file core.h.
{
   using detail::auto_id;
   struct precision_adapter {
     Handler& handler;
     FMT_CONSTEXPR void operator()() { handler.on_dynamic_precision(auto_id()); }
     FMT_CONSTEXPR void operator()(int id) { handler.on_dynamic_precision(id); }
     FMT_CONSTEXPR void operator()(basic_string_view<Char> id) {
       handler.on_dynamic_precision(id);
     }
     FMT_CONSTEXPR void on_error(const char* message) {
       if (message) handler.on_error(message);
     }
   };
   ++begin;
   auto c = begin != end ? *begin : Char();
   if ('0' <= c && c <= '9') {
     auto precision = parse_nonnegative_int(begin, end, -1);
     if (precision != -1)
       handler.on_precision(precision);
     else
       handler.on_error("number is too big");
   } else if (c == '{') {
     ++begin;
     if (begin != end)
       begin = parse_arg_id(begin, end, precision_adapter{handler});
     if (begin == end || *begin++ != '}')
       return handler.on_error("invalid format string"), begin;
   } else {
     return handler.on_error("missing precision specifier"), begin;
   }
   handler.end_precision();
   return begin;
 }
References mpq::c, FMT_CONSTEXPR, message(), parse_arg_id(), and parse_nonnegative_int().
Referenced by formatter< std::chrono::duration< Rep, Period >, Char >::do_parse(), and parse_format_specs().
parse_replacement_field()
template<typename Char , typename Handler > FMT_CONSTEXPR auto parse_replacement_field (const Char * begin, const Char * end, Handler && handler) -> const Char*
Definition at line 2342 of file core.h.
{
   struct id_adapter {
     Handler& handler;
     int arg_id;
     FMT_CONSTEXPR void operator()() { arg_id = handler.on_arg_id(); }
     FMT_CONSTEXPR void operator()(int id) { arg_id = handler.on_arg_id(id); }
     FMT_CONSTEXPR void operator()(basic_string_view<Char> id) {
       arg_id = handler.on_arg_id(id);
     }
     FMT_CONSTEXPR void on_error(const char* message) {
       if (message) handler.on_error(message);
     }
   };
   ++begin;
   if (begin == end) return handler.on_error("invalid format string"), end;
   if (*begin == '}') {
     handler.on_replacement_field(handler.on_arg_id(), begin);
   } else if (*begin == '{') {
     handler.on_text(begin, begin + 1);
   } else {
     auto adapter = id_adapter{handler, 0};
     begin = parse_arg_id(begin, end, adapter);
     Char c = begin != end ? *begin : Char();
     if (c == '}') {
       handler.on_replacement_field(adapter.arg_id, begin);
     } else if (c == ':') {
       begin = handler.on_format_specs(adapter.arg_id, begin + 1, end);
       if (begin == end || *begin != '}')
         return handler.on_error("unknown format specifier"), end;
     } else {
       return handler.on_error("missing '}' in format string"), end;
     }
   }
   return begin + 1;
 }
References mpq::c, FMT_CONSTEXPR, message(), and parse_arg_id().
Referenced by parse_format_string().
parse_width()
template<typename Char , typename Handler > FMT_CONSTEXPR auto parse_width (const Char * begin, const Char * end, Handler && handler) -> const Char*
Definition at line 2203 of file core.h.
{
   using detail::auto_id;
   struct width_adapter {
     Handler& handler;
     FMT_CONSTEXPR void operator()() { handler.on_dynamic_width(auto_id()); }
     FMT_CONSTEXPR void operator()(int id) { handler.on_dynamic_width(id); }
     FMT_CONSTEXPR void operator()(basic_string_view<Char> id) {
       handler.on_dynamic_width(id);
     }
     FMT_CONSTEXPR void on_error(const char* message) {
       if (message) handler.on_error(message);
     }
   };
   FMT_ASSERT(begin != end, "");
   if ('0' <= *begin && *begin <= '9') {
     int width = parse_nonnegative_int(begin, end, -1);
     if (width != -1)
       handler.on_width(width);
     else
       handler.on_error("number is too big");
   } else if (*begin == '{') {
     ++begin;
     if (begin != end) begin = parse_arg_id(begin, end, width_adapter{handler});
     if (begin == end || *begin != '}')
       return handler.on_error("invalid format string"), begin;
     ++begin;
   }
   return begin;
 }
References FMT_ASSERT, FMT_CONSTEXPR, message(), parse_arg_id(), parse_nonnegative_int(), and width.
Referenced by formatter< std::chrono::duration< Rep, Period >, Char >::do_parse(), and parse_format_specs().
print() [1/2]
template<typename... T> FMT_INLINE void print (format_string< T... > fmt, T &&... args)
\rst Formats args according to specifications in fmt and writes the output to stdout.
Example**::
fmt::print("Elapsed time: {0:.2f} seconds", 1.23); \endrst
Definition at line 2972 of file core.h.
{
   const auto& vargs = fmt::make_format_args(args...);
   return detail::is_utf8() ? vprint(fmt, vargs)
                            : detail::vprint_mojibake(stdout, fmt, vargs);
 }
References fmt, is_utf8(), make_format_args(), vprint(), and vprint_mojibake().
print() [2/2]
template<typename... T> FMT_INLINE void print (std::FILE * f, format_string< T... > fmt, T &&... args)
\rst Formats args according to specifications in fmt and writes the output to the file f.
Example**::
fmt::print(stderr, "Don't {}!", "panic"); \endrst
Definition at line 2989 of file core.h.
{
   const auto& vargs = fmt::make_format_args(args...);
   return detail::is_utf8() ? vprint(f, fmt, vargs)
                            : detail::vprint_mojibake(f, fmt, vargs);
 }
References f(), fmt, is_utf8(), make_format_args(), vprint(), and vprint_mojibake().
runtime()
template<typename S > auto runtime (const S & s) -> basic_runtime<char_t<S>>
Definition at line 2866 of file core.h.
{
   return {{s}};
 }
throw_format_error()
FMT_BEGIN_DETAIL_NAMESPACE void throw_format_error (const char * message) inline
Definition at line 810 of file format.h.
{
   FMT_THROW(format_error(message));
 }
References FMT_THROW, and message().
Referenced by fill_t< Char >::operator=().
to_ascii()
template<typename Char , FMT_ENABLE_IF(std::is_integral< Char >::value) > constexpr auto to_ascii (Char value) -> Char constexpr
Definition at line 2054 of file core.h.
{
   return value;
 }
Referenced by parse_align(), and parse_format_specs().
to_string_view() [1/6]
FMT_BEGIN_DETAIL_NAMESPACE void to_string_view (...)
to_string_view() [2/6]
template<typename Char > constexpr auto to_string_view (basic_string_view< Char > s) -> basic_string_view<Char> constexpr
Definition at line 546 of file core.h.
{
   return s;
 }
to_string_view() [3/6]
template<typename Char , FMT_ENABLE_IF(is_char< Char >::value) > FMT_INLINE auto to_string_view (const Char * s) -> basic_string_view<Char>
Definition at line 537 of file core.h.
{
   return s;
 }
Referenced by check_format_string(), format(), format_to(), format_to_n(), formatted_size(), fprintf(), arg_mapper< Context >::map(), print(), printf(), sprintf(), vformat(), vformat_to(), vfprintf(), vprint(), vprintf(), vsprintf(), and write().
to_string_view() [4/6]
template<typename S , FMT_ENABLE_IF(is_compile_string< S >::value) > constexpr auto to_string_view (const S & s) -> basic_string_view<typename S::char_type> constexpr
Definition at line 565 of file core.h.
{
   return basic_string_view<typename S::char_type>(s);
 }
to_string_view() [5/6]
template<typename Char , typename Traits , typename Alloc > auto to_string_view (const std::basic_string< Char, Traits, Alloc > & s) -> basic_string_view<Char> inline
Definition at line 541 of file core.h.
{
   return s;
 }
to_string_view() [6/6]
template<typename Char , FMT_ENABLE_IF(!std::is_empty< detail::std_string_view< Char >>::value) > auto to_string_view (detail::std_string_view< Char > s) -> basic_string_view<Char> inline
Definition at line 552 of file core.h.
{
   return s;
 }
to_unsigned()
template<typename Int > FMT_CONSTEXPR auto to_unsigned (Int value) -> typename std::make_unsigned<Int>::type
Definition at line 412 of file core.h.
{
   FMT_ASSERT(value >= 0, "negative value");
   return static_cast<typename std::make_unsigned<Int>::type>(value);
 }
References FMT_ASSERT.
Referenced by basic_format_parse_context< Char, ErrorHandler >::advance_to(), detail::bigint::align(), buffer< T >::append(), copy_str(), do_parse_arg_id(), detail::fallback_format(), detail::fill_n(), find< false, char >(), detail::format_error_code(), detail::format_float(), format_uint(), get_dynamic_spec(), dynamic_specs_handler< ParseContext >::make_arg_ref(), detail::bigint::operator[](), formatter< std::chrono::duration< Rep, Period >, Char >::parse(), formatter< std::chrono::time_point< std::chrono::system_clock, Duration >, Char >::parse(), formatter< std::tm, Char >::parse(), parse_align(), parse_nonnegative_int(), detail::bigint::remove_leading_zeros(), format_int::size(), detail::snprintf_float(), detail::bigint::square(), to_nonnegative_int(), vformat_to(), vprintf(), write(), chrono_formatter< FormatContext, OutputIt, Rep, Period >::write(), detail::write_buffer(), write_float(), write_int(), write_int_data< Char >::write_int_data(), write_int_localized(), write_padded(), write_ptr(), and write_significand().
vformat()
FMT_API auto vformat (string_view fmt, format_args args) -> std::string
Definition at line 2561 of file format-inl.h.
{
   // Don't optimize the "{}" case to keep the binary size small and because it
   // can be better optimized in fmt::format anyway.
   auto buffer = memory_buffer();
   detail::vformat_to(buffer, fmt, args);
   return to_string(buffer);
 }
References fmt, to_string(), and vformat_to().
Referenced by format(), and vsystem_error().
vformat_to() [1/2]
template<typename Char > void vformat_to (buffer< Char > & buf, basic_string_view< Char > fmt, basic_format_args< FMT_BUFFER_CONTEXT(type_identity_t< Char >)> args, locale_ref loc = {})
Definition at line 2627 of file format.h.
                     {
   // workaround for msvc bug regarding name-lookup in module
   // link names into function scope
   using detail::arg_formatter;
   using detail::buffer_appender;
   using detail::custom_formatter;
   using detail::default_arg_formatter;
   using detail::get_arg;
   using detail::locale_ref;
   using detail::parse_format_specs;
   using detail::specs_checker;
   using detail::specs_handler;
   using detail::to_unsigned;
   using detail::type;
   using detail::write;
   auto out = buffer_appender<Char>(buf);
   if (fmt.size() == 2 && equal2(fmt.data(), "{}")) {
     auto arg = args.get(0);
     if (!arg) error_handler().on_error("argument not found");
     visit_format_arg(default_arg_formatter<Char>{out, args, loc}, arg);
     return;
   }
   struct format_handler : error_handler {
     basic_format_parse_context<Char> parse_context;
     buffer_context<Char> context;
     format_handler(buffer_appender<Char> out, basic_string_view<Char> str,
                    basic_format_args<buffer_context<Char>> args, locale_ref loc)
         : parse_context(str), context(out, args, loc) {}
     void on_text(const Char* begin, const Char* end) {
       auto text = basic_string_view<Char>(begin, to_unsigned(end - begin));
       context.advance_to(write<Char>(context.out(), text));
     }
     FMT_CONSTEXPR auto on_arg_id() -> int {
       return parse_context.next_arg_id();
     }
     FMT_CONSTEXPR auto on_arg_id(int id) -> int {
       return parse_context.check_arg_id(id), id;
     }
     FMT_CONSTEXPR auto on_arg_id(basic_string_view<Char> id) -> int {
       int arg_id = context.arg_id(id);
       if (arg_id < 0) on_error("argument not found");
       return arg_id;
     }
     FMT_INLINE void on_replacement_field(int id, const Char*) {
       auto arg = get_arg(context, id);
       context.advance_to(visit_format_arg(
           default_arg_formatter<Char>{context.out(), context.args(),
                                       context.locale()},
           arg));
     }
     auto on_format_specs(int id, const Char* begin, const Char* end)
         -> const Char* {
       auto arg = get_arg(context, id);
       if (arg.type() == type::custom_type) {
         parse_context.advance_to(parse_context.begin() +
                                  (begin - &*parse_context.begin()));
         visit_format_arg(custom_formatter<Char>{parse_context, context}, arg);
         return parse_context.begin();
       }
       auto specs = basic_format_specs<Char>();
       specs_checker<specs_handler<Char>> handler(
           specs_handler<Char>(specs, parse_context, context), arg.type());
       begin = parse_format_specs(begin, end, handler);
       if (begin == end || *begin != '}')
         on_error("missing '}' in format string");
       auto f = arg_formatter<Char>{context.out(), specs, context.locale()};
       context.advance_to(visit_format_arg(f, arg));
       return begin;
     }
   };
   detail::parse_format_string<false>(fmt, format_handler(out, fmt, args, loc));
 }
References basic_format_parse_context< Char, ErrorHandler >::advance_to(), basic_format_context< OutputIt, Char >::advance_to(), arg(), basic_format_context< OutputIt, Char >::arg_id(), basic_format_context< OutputIt, Char >::args(), basic_format_parse_context< Char, ErrorHandler >::begin(), basic_format_parse_context< Char, ErrorHandler >::check_arg_id(), custom_type, equal2(), f(), fmt, FMT_CONSTEXPR, FMT_INLINE, get_arg(), basic_format_context< OutputIt, Char >::locale(), basic_format_parse_context< Char, ErrorHandler >::next_arg_id(), error_handler::on_error(), basic_format_context< OutputIt, Char >::out(), parse_format_specs(), to_unsigned(), visit_format_arg(), and detail::write().
Referenced by format_to(), formatted_size(), vformat(), vformat_to(), and vformat_to_n().
vformat_to() [2/2]
template<typename OutputIt , FMT_ENABLE_IF(detail::is_output_iterator< OutputIt, char >::value) > auto vformat_to (OutputIt out, string_view fmt, format_args args) -> OutputIt
Formats a string and writes the output to out.
Definition at line 2892 of file core.h.
{
   using detail::get_buffer;
   auto&& buf = get_buffer<char>(out);
   detail::vformat_to(buf, string_view(fmt), args, {});
   return detail::get_iterator(buf);
 }
References fmt, get_buffer(), get_iterator(), and vformat_to().
vformat_to_n()
template<typename OutputIt , typename... T, FMT_ENABLE_IF(detail::is_output_iterator< OutputIt, char >::value) > auto vformat_to_n (OutputIt out, size_t n, string_view fmt, format_args args) -> format_to_n_result<OutputIt>
Definition at line 2927 of file core.h.
{
   using buffer =
       detail::iterator_buffer<OutputIt, char, detail::fixed_buffer_traits>;
   auto buf = buffer(out, n);
   detail::vformat_to(buf, fmt, args, {});
   return {buf.out(), buf.count()};
 }
References buffer, fmt, and vformat_to().
Referenced by format_to_n().
visit_format_arg()
template<typename Visitor , typename Context > FMT_CONSTEXPR FMT_INLINE auto visit_format_arg (Visitor && vis, const basic_format_arg< Context > & arg) -> decltype(vis(0))
\rst Visits an argument dispatching to the appropriate visit method based on the argument type. For example, if the argument type is double then vis(value) will be called with the value of type double. \endrst
Definition at line 1447 of file core.h.
{
   switch (arg.type_) {
   case detail::type::none_type:
     break;
   case detail::type::int_type:
     return vis(arg.value_.int_value);
   case detail::type::uint_type:
     return vis(arg.value_.uint_value);
   case detail::type::long_long_type:
     return vis(arg.value_.long_long_value);
   case detail::type::ulong_long_type:
     return vis(arg.value_.ulong_long_value);
   case detail::type::int128_type:
     return vis(detail::convert_for_visit(arg.value_.int128_value));
   case detail::type::uint128_type:
     return vis(detail::convert_for_visit(arg.value_.uint128_value));
   case detail::type::bool_type:
     return vis(arg.value_.bool_value);
   case detail::type::char_type:
     return vis(arg.value_.char_value);
   case detail::type::float_type:
     return vis(arg.value_.float_value);
   case detail::type::double_type:
     return vis(arg.value_.double_value);
   case detail::type::long_double_type:
     return vis(arg.value_.long_double_value);
   case detail::type::cstring_type:
     return vis(arg.value_.string.data);
   case detail::type::string_type:
     using sv = basic_string_view<typename Context::char_type>;
     return vis(sv(arg.value_.string.data, arg.value_.string.size));
   case detail::type::pointer_type:
     return vis(arg.value_.pointer);
   case detail::type::custom_type:
     return vis(typename basic_format_arg<Context>::handle(arg.value_.custom));
   }
   return vis(monostate());
 }
References arg(), and convert_for_visit().
Referenced by convert_arg(), get_dynamic_spec(), parse_header(), vformat_to(), and vprintf().
vprint() [1/2]
FMT_API void vprint (std::FILE * f, string_view fmt, format_args args)
Definition at line 2597 of file format-inl.h.
{
   memory_buffer buffer;
   detail::vformat_to(buffer, format_str, args);
   detail::print(f, {buffer.data(), buffer.size()});
 }
References buffer, buffer< T >::data(), f(), detail::print(), buffer< T >::size(), and vformat_to().
Referenced by vprint().
vprint() [2/2]
FMT_API void vprint (string_view fmt, format_args args)
Definition at line 2614 of file format-inl.h.
{
   vprint(stdout, format_str, args);
 }
References vprint().
Referenced by print().
vprint_mojibake()
void vprint_mojibake (std::FILE * , string_view , format_args) inline
Definition at line 2741 of file core.h.
 {}
Referenced by print().
Variable Documentation
invalid_arg_index
constexpr int invalid_arg_index = -1 constexpr
Definition at line 2640 of file core.h.
Referenced by get_arg_index_by_name(), and format_string_checker< Char, ErrorHandler, Args >::on_arg_id().