Azerotcore-wotlk: npc_ishanah Class Reference
npc_ishanah Class Reference
Classes
struct ishanahAI
Public Member Functions
npc_ishanah ()
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
bool OnGossipHello (Player *player, Creature *creature) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 446 of file zone_shattrath_city.cpp.
Constructor & Destructor Documentation
npc_ishanah()
npc_ishanah::npc_ishanah () inline
Definition at line 449 of file zone_shattrath_city.cpp.
 : CreatureScript("npc_ishanah") { }
Member Function Documentation
GetAI()
CreatureAI* npc_ishanah::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 534 of file zone_shattrath_city.cpp.
     {
         return new ishanahAI(creature);
     }
OnGossipHello()
bool npc_ishanah::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 462 of file zone_shattrath_city.cpp.
     {
         if (creature->IsQuestGiver())
             player->PrepareQuestMenu(creature->GetGUID());
         AddGossipItemFor(player, GOSSIP_ICON_CHAT, ISANAH_GOSSIP_1, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
         AddGossipItemFor(player, GOSSIP_ICON_CHAT, ISANAH_GOSSIP_2, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
         SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), Player::GetGossipTextId(), Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, ISANAH_GOSSIP_1, ISANAH_GOSSIP_2, Unit::IsQuestGiver(), Player::PrepareQuestMenu(), and SendGossipMenuFor().
OnGossipSelect()
bool npc_ishanah::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 451 of file zone_shattrath_city.cpp.
     {
         ClearGossipMenuFor(player);
         if (action == GOSSIP_ACTION_INFO_DEF + 1)
             SendGossipMenuFor(player, 9458, creature->GetGUID());
         else if (action == GOSSIP_ACTION_INFO_DEF + 2)
             SendGossipMenuFor(player, 9459, creature->GetGUID());
         return true;
     }
References ClearGossipMenuFor(), Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, and SendGossipMenuFor().
The documentation for this class was generated from the following file:
src/server/scripts/Outland/zone_shattrath_city.cpp