Azerotcore-wotlk: Acore Daemon
Acore Daemon
Files
file CliRunnable.cpp
file CliRunnable.h
file Main.cpp
Classes
class FreezeDetector
Macros
#define _ACORE_CORE_CONFIG "worldserver.conf"
#define WORLD_SLEEP_CONST 10
Functions
static void PrintCliPrefix ()
void utf8print (void *, std::string_view str)
void commandFinished (void *, bool)
void CliThread ()
Thread start
FreezeDetector::FreezeDetector (Acore::Asio::IoContext &ioContext, uint32 maxCoreStuckTime)
static void FreezeDetector::Start (std::shared_ptr< FreezeDetector > const &freezeDetector)
static void FreezeDetector::Handler (std::weak_ptr< FreezeDetector > freezeDetectorRef, boost::system::error_code const &error)
void SignalHandler (boost::system::error_code const &error, int signalNumber)
void ClearOnlineAccounts ()
Clear 'online' status for all accounts with characters in this realm.
bool StartDB ()
Initialize connection to the databases.
void StopDB ()
bool LoadRealmInfo (Acore::Asio::IoContext &ioContext)
AsyncAcceptor * StartRaSocketAcceptor (Acore::Asio::IoContext &ioContext)
void ShutdownCLIThread (std::thread *cliThread)
void AuctionListingRunnable ()
void ShutdownAuctionListingThread (std::thread *thread)
void WorldUpdateLoop ()
void usage (const char *prog)
Print out the usage string for this program on the console.
int main (int argc, char **argv)
Launch the Azeroth server.
Variables
static constexpr char CLI_PREFIX [] = "AC> "
Acore::Asio::DeadlineTimer FreezeDetector::_timer
uint32 FreezeDetector::_worldLoopCounter
uint32 FreezeDetector::_lastChangeMsTime
uint32 FreezeDetector::_maxCoreStuckTimeInMs
Detailed Description
Macro Definition Documentation
_ACORE_CORE_CONFIG
#define _ACORE_CORE_CONFIG "worldserver.conf"
Definition at line 83 of file Main.cpp.
WORLD_SLEEP_CONST
#define WORLD_SLEEP_CONST 10
Definition at line 86 of file Main.cpp.
Function Documentation
AuctionListingRunnable()
void AuctionListingRunnable ()
Definition at line 720 of file Main.cpp.
 {
     LOG_INFO("server", "Starting up Auction House Listing thread...");
     while (!World::IsStopped())
     {
         if (AsyncAuctionListingMgr::IsAuctionListingAllowed())
         {
             uint32 diff = AsyncAuctionListingMgr::GetDiff();
             AsyncAuctionListingMgr::ResetDiff();
             if (AsyncAuctionListingMgr::GetTempList().size() || AsyncAuctionListingMgr::GetList().size())
             {
                 std::lock_guard<std::mutex> guard(AsyncAuctionListingMgr::GetLock());
                 {
                     std::lock_guard<std::mutex> guard(AsyncAuctionListingMgr::GetTempLock());
                     for (auto const& delayEvent : AsyncAuctionListingMgr::GetTempList())
                         AsyncAuctionListingMgr::GetList().emplace_back(delayEvent);
                     AsyncAuctionListingMgr::GetTempList().clear();
                 }
                 for (auto& itr : AsyncAuctionListingMgr::GetList())
                 {
                     if (itr._msTimer <= diff)
                         itr._msTimer = 0;
                     else
                         itr._msTimer -= diff;
                 }
                 for (std::list<AuctionListItemsDelayEvent>::iterator itr = AsyncAuctionListingMgr::GetList().begin(); itr != AsyncAuctionListingMgr::GetList().end(); ++itr)
                 {
                     if ((*itr)._msTimer != 0)
                         continue;
                     if ((*itr).Execute())
                         AsyncAuctionListingMgr::GetList().erase(itr);
                     break;
                 }
             }
         }
         std::this_thread::sleep_for(1ms);
     }
     LOG_INFO("server", "Auction House Listing thread exiting without problems.");
 }
References diff(), AsyncAuctionListingMgr::GetDiff(), AsyncAuctionListingMgr::GetList(), AsyncAuctionListingMgr::GetLock(), AsyncAuctionListingMgr::GetTempList(), AsyncAuctionListingMgr::GetTempLock(), AsyncAuctionListingMgr::IsAuctionListingAllowed(), World::IsStopped(), LOG_INFO, and AsyncAuctionListingMgr::ResetDiff().
Referenced by main().
ClearOnlineAccounts()
void ClearOnlineAccounts ()
Clear 'online' status for all accounts with characters in this realm.
Definition at line 507 of file Main.cpp.
 {
     // Reset online status for all accounts with characters on the current realm
     // pussywizard: tc query would set online=0 even if logged in on another realm >_>
     LoginDatabase.DirectPExecute("UPDATE account SET online = 0 WHERE online = %u", realm.Id.Realm);
     // Reset online status for all characters
     CharacterDatabase.DirectExecute("UPDATE characters SET online = 0 WHERE online <> 0");
 }
References CharacterDatabase, Realm::Id, LoginDatabase, realm, and RealmHandle::Realm.
Referenced by main(), and StartDB().
CliThread()
void CliThread ()
Thread start
Command Line Interface handling thread.
As long as the World is running (no World::m_stopEvent), get the command line and handle it
Definition at line 115 of file CliRunnable.cpp.
 {
 #if AC_PLATFORM == AC_PLATFORM_WINDOWS
     // print this here the first time
     // later it will be printed after command queue updates
     PrintCliPrefix();
 #else
     ::rl_attempted_completion_function = &Acore::Impl::Readline::cli_completion;
     {
         static char BLANK = '\0';
         ::rl_completer_word_break_characters = &BLANK;
     }
     ::rl_event_hook = &Acore::Impl::Readline::cli_hook_func;
 #endif
     if (sConfigMgr->GetOption<bool>("BeepAtStart", true))
         printf("\a"); // \a = Alert
 #if AC_PLATFORM == AC_PLATFORM_WINDOWS
     if (sConfigMgr->GetOption<bool>("FlashAtStart", true))
     {
         FLASHWINFO fInfo;
         fInfo.cbSize = sizeof(FLASHWINFO);
         fInfo.dwFlags = FLASHW_TRAY | FLASHW_TIMERNOFG;
         fInfo.hwnd = GetConsoleWindow();
         fInfo.uCount = 0;
         fInfo.dwTimeout = 0;
         FlashWindowEx(&fInfo);
     }
 #endif
     while (!World::IsStopped())
     {
         fflush(stdout);
         std::string command;
 #if AC_PLATFORM == AC_PLATFORM_WINDOWS
         wchar_t commandbuf[256];
         if (fgetws(commandbuf, sizeof(commandbuf), stdin))
         {
             if (!WStrToUtf8(commandbuf, wcslen(commandbuf), command))
             {
                 PrintCliPrefix();
                 continue;
             }
         }
 #else
         char* command_str = readline(CLI_PREFIX);
         ::rl_bind_key('\t', ::rl_complete);
         if (command_str != nullptr)
         {
             command = command_str;
             free(command_str);
         }
 #endif
         if (!command.empty())
         {
             std::size_t nextLineIndex = command.find_first_of("\r\n");
             if (nextLineIndex != std::string::npos)
             {
                 if (nextLineIndex == 0)
                 {
 #if AC_PLATFORM == AC_PLATFORM_WINDOWS
                     PrintCliPrefix();
 #endif
                     continue;
                 }
                 command.erase(nextLineIndex);
             }
             fflush(stdout);
             sWorld->QueueCliCommand(new CliCommandHolder(nullptr, command.c_str(), &utf8print, &commandFinished));
 #if AC_PLATFORM != AC_PLATFORM_WINDOWS
             add_history(command.c_str());
 #endif
         }
         else if (feof(stdin))
         {
             World::StopNow(SHUTDOWN_EXIT_CODE);
         }
     }
 }
References CLI_PREFIX, commandFinished(), World::IsStopped(), PrintCliPrefix(), printf(), sConfigMgr, SHUTDOWN_EXIT_CODE, World::StopNow(), sWorld, utf8print(), and WStrToUtf8().
Referenced by main().
commandFinished()
void commandFinished (void * , bool)
Definition at line 93 of file CliRunnable.cpp.
 {
     PrintCliPrefix();
     fflush(stdout);
 }
References PrintCliPrefix().
Referenced by CliThread().
FreezeDetector()
FreezeDetector::FreezeDetector (Acore::Asio::IoContext & ioContext, uint32 maxCoreStuckTime) inline
Definition at line 91 of file Main.cpp.
         : _timer(ioContext), _worldLoopCounter(0), _lastChangeMsTime(getMSTime()), _maxCoreStuckTimeInMs(maxCoreStuckTime) { }
Handler()
void FreezeDetector::Handler (std::weak_ptr< FreezeDetector > freezeDetectorRef, boost::system::error_code const & error) static
Definition at line 628 of file Main.cpp.
 {
     if (!error)
     {
         if (std::shared_ptr<FreezeDetector> freezeDetector = freezeDetectorRef.lock())
         {
             uint32 curtime = getMSTime();
             uint32 worldLoopCounter = World::m_worldLoopCounter;
             if (freezeDetector->_worldLoopCounter != worldLoopCounter)
             {
                 freezeDetector->_lastChangeMsTime = curtime;
                 freezeDetector->_worldLoopCounter = worldLoopCounter;
             }
             // possible freeze
             else if (getMSTimeDiff(freezeDetector->_lastChangeMsTime, curtime) > freezeDetector->_maxCoreStuckTimeInMs)
             {
                 LOG_ERROR("server.worldserver", "World Thread hangs, kicking out server!");
                 ABORT();
             }
             freezeDetector->_timer.expires_from_now(boost::posix_time::seconds(1));
             freezeDetector->_timer.async_wait(std::bind(&FreezeDetector::Handler, freezeDetectorRef, std::placeholders::_1));
         }
     }
 }
References ABORT, error(), getMSTime(), getMSTimeDiff(), LOG_ERROR, World::m_worldLoopCounter, and G3D::units::seconds().
Referenced by FreezeDetector::Start().
LoadRealmInfo()
bool LoadRealmInfo (Acore::Asio::IoContext & ioContext)
Definition at line 672 of file Main.cpp.
 {
     QueryResult result = LoginDatabase.PQuery("SELECT id, name, address, localAddress, localSubnetMask, port, icon, flag, timezone, allowedSecurityLevel, population, gamebuild FROM realmlist WHERE id = %u", realm.Id.Realm);
     if (!result)
         return false;
     Acore::Asio::Resolver resolver(ioContext);
     Field* fields = result->Fetch();
     realm.Name = fields[1].GetString();
     Optional<boost::asio::ip::tcp::endpoint> externalAddress = resolver.Resolve(boost::asio::ip::tcp::v4(), fields[2].GetString(), "");
     if (!externalAddress)
     {
         LOG_ERROR("server.worldserver", "Could not resolve address %s", fields[2].GetString().c_str());
         return false;
     }
     realm.ExternalAddress = std::make_unique<boost::asio::ip::address>(externalAddress->address());
     Optional<boost::asio::ip::tcp::endpoint> localAddress = resolver.Resolve(boost::asio::ip::tcp::v4(), fields[3].GetString(), "");
     if (!localAddress)
     {
         LOG_ERROR("server.worldserver", "Could not resolve address %s", fields[3].GetString().c_str());
         return false;
     }
     realm.LocalAddress = std::make_unique<boost::asio::ip::address>(localAddress->address());
     Optional<boost::asio::ip::tcp::endpoint> localSubmask = resolver.Resolve(boost::asio::ip::tcp::v4(), fields[4].GetString(), "");
     if (!localSubmask)
     {
         LOG_ERROR("server.worldserver", "Could not resolve address %s", fields[4].GetString().c_str());
         return false;
     }
     realm.LocalSubnetMask = std::make_unique<boost::asio::ip::address>(localSubmask->address());
     realm.Port = fields[5].GetUInt16();
     realm.Type = fields[6].GetUInt8();
     realm.Flags = RealmFlags(fields[7].GetUInt8());
     realm.Timezone = fields[8].GetUInt8();
     realm.AllowedSecurityLevel = AccountTypes(fields[9].GetUInt8());
     realm.PopulationLevel = fields[10].GetFloat();
     realm.Build = fields[11].GetUInt32();
     return true;
 }
References Realm::AllowedSecurityLevel, Realm::Build, Realm::ExternalAddress, Realm::Flags, Field::GetFloat(), Field::GetString(), Field::GetUInt16(), Field::GetUInt32(), Field::GetUInt8(), Realm::Id, Realm::LocalAddress, Realm::LocalSubnetMask, LOG_ERROR, LoginDatabase, Realm::Name, Realm::PopulationLevel, Realm::Port, realm, RealmHandle::Realm, Acore::Asio::Resolver::Resolve(), Realm::Timezone, and Realm::Type.
Referenced by main().
main()
int main (int argc, char ** argv)
Launch the Azeroth server.
Command line parsing to get the configuration file name
worldserver PID file creation
Initialize the World
Clean database before leaving
Definition at line 135 of file Main.cpp.
 {
     Acore::Impl::CurrentServerProcessHolder::_type = SERVER_PROCESS_WORLDSERVER;
     signal(SIGABRT, &Acore::AbortHandler);
     std::string configFile = sConfigMgr->GetConfigPath() + std::string(_ACORE_CORE_CONFIG);
     int c = 1;
     while (c < argc)
     {
         if (strcmp(argv[c], "--dry-run") == 0)
         {
             sConfigMgr->setDryRun(true);
         }
         if (!strcmp(argv[c], "-c"))
         {
             if (++c >= argc)
             {
                 printf("Runtime-Error: -c option requires an input argument");
                 usage(argv[0]);
                 return 1;
             }
             else
                 configFile = argv[c];
         }
 #ifdef _WIN32
         if (strcmp(argv[c], "-s") == 0) // Services
         {
             if (++c >= argc)
             {
                 printf("Runtime-Error: -s option requires an input argument");
                 usage(argv[0]);
                 return 1;
             }
             if (strcmp(argv[c], "install") == 0)
             {
                 if (WinServiceInstall())
                     printf("Installing service\n");
                 return 1;
             }
             else if (strcmp(argv[c], "uninstall") == 0)
             {
                 if (WinServiceUninstall())
                     printf("Uninstalling service\n");
                 return 1;
             }
             else
             {
                 printf("Runtime-Error: unsupported option %s", argv[c]);
                 usage(argv[0]);
                 return 1;
             }
         }
         if (strcmp(argv[c], "--service") == 0)
             WinServiceRun();
 #endif
         ++c;
     }
     // Add file and args in config
     sConfigMgr->Configure(configFile, std::vector<std::string>(argv, argv + argc), CONFIG_FILE_LIST);
     if (!sConfigMgr->LoadAppConfigs())
         return 1;
     // Loading modules configs
     sConfigMgr->LoadModulesConfigs();
     std::shared_ptr<Acore::Asio::IoContext> ioContext = std::make_shared<Acore::Asio::IoContext>();
     // Init all logs
     sLog->RegisterAppender<AppenderDB>();
     sLog->Initialize();
     Acore::Banner::Show("worldserver-daemon",
         [](std::string_view text)
         {
             FMT_LOG_INFO("server.worldserver", text);
         },
         []()
         {
             FMT_LOG_INFO("server.worldserver", "> Using configuration file       {}", sConfigMgr->GetFilename());
             FMT_LOG_INFO("server.worldserver", "> Using SSL version:             {} (library: {})", OPENSSL_VERSION_TEXT, SSLeay_version(SSLEAY_VERSION));
             FMT_LOG_INFO("server.worldserver", "> Using Boost version:           {}.{}.{}", BOOST_VERSION / 100000, BOOST_VERSION / 100 % 1000, BOOST_VERSION % 100);
         });
     OpenSSLCrypto::threadsSetup();
     std::shared_ptr<void> opensslHandle(nullptr, [](void*) { OpenSSLCrypto::threadsCleanup(); });
     // Seed the OpenSSL's PRNG here.
     // That way it won't auto-seed when calling BigNumber::SetRand and slow down the first world login
     BigNumber seed;
     seed.SetRand(16 * 8);
     std::string pidFile = sConfigMgr->GetOption<std::string>("PidFile", "");
     if (!pidFile.empty())
     {
         if (uint32 pid = CreatePIDFile(pidFile))
             LOG_ERROR("server", "Daemon PID: %u\n", pid); // outError for red color in console
         else
         {
             LOG_ERROR("server", "Cannot create PID file %s (possible error: permission)\n", pidFile.c_str());
             return 1;
         }
     }
     // Set signal handlers (this must be done before starting IoContext threads, because otherwise they would unblock and exit)
     boost::asio::signal_set signals(*ioContext, SIGINT, SIGTERM);
 #if AC_PLATFORM == AC_PLATFORM_WINDOWS
     signals.add(SIGBREAK);
 #endif
     signals.async_wait(SignalHandler);
     // Start the Boost based thread pool
     int numThreads = sConfigMgr->GetOption<int32>("ThreadPool", 1);
     std::shared_ptr<std::vector<std::thread>> threadPool(new std::vector<std::thread>(), [ioContext](std::vector<std::thread>* del)
     {
         ioContext->stop();
         for (std::thread& thr : *del)
             thr.join();
         delete del;
     });
     if (numThreads < 1)
     {
         numThreads = 1;
     }
     for (int i = 0; i < numThreads; ++i)
     {
         threadPool->push_back(std::thread([ioContext]()
         {
             ioContext->run();
         }));
     }
     // Set process priority according to configuration settings
     SetProcessPriority("server.worldserver", sConfigMgr->GetOption<int32>(CONFIG_PROCESSOR_AFFINITY, 0), sConfigMgr->GetOption<bool>(CONFIG_HIGH_PRIORITY, false));
     sScriptMgr->SetScriptLoader(AddScripts);
     std::shared_ptr<void> sScriptMgrHandle(nullptr, [](void*)
     {
         sScriptMgr->Unload();
         //sScriptReloadMgr->Unload();
     });
     LOG_INFO("server.loading", "Initializing Scripts...");
     sScriptMgr->Initialize();
     // Start the databases
     if (!StartDB())
         return 1;
     std::shared_ptr<void> dbHandle(nullptr, [](void*) { StopDB(); });
     // set server offline (not connectable)
     LoginDatabase.DirectPExecute("UPDATE realmlist SET flag = (flag & ~%u) | %u WHERE id = '%d'", REALM_FLAG_OFFLINE, REALM_FLAG_VERSION_MISMATCH, realm.Id.Realm);
     LoadRealmInfo(*ioContext);
     sMetric->Initialize(realm.Name, *ioContext, []()
     {
         METRIC_VALUE("online_players", sWorld->GetPlayerCount());
         METRIC_VALUE("db_queue_login", uint64(LoginDatabase.QueueSize()));
         METRIC_VALUE("db_queue_character", uint64(CharacterDatabase.QueueSize()));
         METRIC_VALUE("db_queue_world", uint64(WorldDatabase.QueueSize()));
     });
     METRIC_EVENT("events", "Worldserver started", "");
     std::shared_ptr<void> sMetricHandle(nullptr, [](void*)
     {
         METRIC_EVENT("events", "Worldserver shutdown", "");
         sMetric->Unload();
     });
     // Loading modules configs
     sConfigMgr->PrintLoadedModulesConfigs();
     sSecretMgr->Initialize();
     sWorld->SetInitialWorldSettings();
     std::shared_ptr<void> mapManagementHandle(nullptr, [](void*)
     {
         // unload battleground templates before different singletons destroyed
         sBattlegroundMgr->DeleteAllBattlegrounds();
         sOutdoorPvPMgr->Die();                     // unload it before MapMgr
         sMapMgr->UnloadAll();                      // unload all grids (including locked in memory)
 #ifdef ELUNA
         Eluna::Uninitialize();
 #endif
     });
     // Start the Remote Access port (acceptor) if enabled
     std::unique_ptr<AsyncAcceptor> raAcceptor;
     if (sConfigMgr->GetOption<bool>("Ra.Enable", false))
     {
         raAcceptor.reset(StartRaSocketAcceptor(*ioContext));
     }
     // Start soap serving thread if enabled
     std::shared_ptr<std::thread> soapThread;
     if (sConfigMgr->GetOption<bool>("SOAP.Enabled", false))
     {
         soapThread.reset(new std::thread(ACSoapThread, sConfigMgr->GetOption<std::string>("SOAP.IP", "127.0.0.1"), uint16(sConfigMgr->GetOption<int32>("SOAP.Port", 7878))),
             [](std::thread* thr)
         {
             thr->join();
             delete thr;
         });
     }
     // Launch the worldserver listener socket
     uint16 worldPort = uint16(sWorld->getIntConfig(CONFIG_PORT_WORLD));
     std::string worldListener = sConfigMgr->GetOption<std::string>("BindIP", "0.0.0.0");
     int networkThreads = sConfigMgr->GetOption<int32>("Network.Threads", 1);
     if (networkThreads <= 0)
     {
         LOG_ERROR("server.worldserver", "Network.Threads must be greater than 0");
         World::StopNow(ERROR_EXIT_CODE);
         return 1;
     }
     if (!sWorldSocketMgr.StartWorldNetwork(*ioContext, worldListener, worldPort, networkThreads))
     {
         LOG_ERROR("server.worldserver", "Failed to initialize network");
         World::StopNow(ERROR_EXIT_CODE);
         return 1;
     }
     std::shared_ptr<void> sWorldSocketMgrHandle(nullptr, [](void*)
     {
         sWorld->KickAll();              // save and kick all players
         sWorld->UpdateSessions(1);      // real players unload required UpdateSessions call
         sWorldSocketMgr.StopNetwork();
         ClearOnlineAccounts();
     });
     // Set server online (allow connecting now)
     LoginDatabase.DirectPExecute("UPDATE realmlist SET flag = flag & ~%u, population = 0 WHERE id = '%u'", REALM_FLAG_VERSION_MISMATCH, realm.Id.Realm);
     realm.PopulationLevel = 0.0f;
     realm.Flags = RealmFlags(realm.Flags & ~uint32(REALM_FLAG_VERSION_MISMATCH));
     // Start the freeze check callback cycle in 5 seconds (cycle itself is 1 sec)
     std::shared_ptr<FreezeDetector> freezeDetector;
     if (int32 coreStuckTime = sConfigMgr->GetOption<int32>("MaxCoreStuckTime", 60))
     {
         freezeDetector = std::make_shared<FreezeDetector>(*ioContext, coreStuckTime * 1000);
         FreezeDetector::Start(freezeDetector);
         LOG_INFO("server.worldserver", "Starting up anti-freeze thread (%u seconds max stuck time)...", coreStuckTime);
     }
     LOG_INFO("server.worldserver", "%s (worldserver-daemon) ready...", GitRevision::GetFullVersion());
     sScriptMgr->OnStartup();
     // Launch CliRunnable thread
     std::shared_ptr<std::thread> cliThread;
 #ifdef _WIN32
     if (sConfigMgr->GetOption<bool>("Console.Enable", true) && (m_ServiceStatus == -1)/* need disable console in service mode*/)
 #else
     if (sConfigMgr->GetOption<bool>("Console.Enable", true))
 #endif
     {
         cliThread.reset(new std::thread(CliThread), &ShutdownCLIThread);
     }
     // Launch CliRunnable thread
     std::shared_ptr<std::thread> auctionLisingThread;
     auctionLisingThread.reset(new std::thread(AuctionListingRunnable),
         [](std::thread* thr)
     {
         thr->join();
         delete thr;
     });
     WorldUpdateLoop();
     // Shutdown starts here
     threadPool.reset();
     sScriptMgr->OnShutdown();
     // set server offline
     LoginDatabase.DirectPExecute("UPDATE realmlist SET flag = flag | %u WHERE id = '%d'", REALM_FLAG_OFFLINE, realm.Id.Realm);
     LOG_INFO("server.worldserver", "Halting process...");
     // 0 - normal shutdown
     // 1 - shutdown at error
     // 2 - restart command used, this code can be used by restarter for restart Warheadd
     return World::GetExitCode();
 }
References _ACORE_CORE_CONFIG, Acore::Impl::CurrentServerProcessHolder::_type, Acore::AbortHandler(), ACSoapThread(), AddScripts(), AuctionListingRunnable(), mpq::c, ClearOnlineAccounts(), CliThread(), CONFIG_HIGH_PRIORITY, CONFIG_PORT_WORLD, CONFIG_PROCESSOR_AFFINITY, CreatePIDFile(), ERROR_EXIT_CODE, Realm::Flags, FMT_LOG_INFO, World::GetExitCode(), GitRevision::GetFullVersion(), Realm::Id, LoadRealmInfo(), LOG_ERROR, LOG_INFO, LoginDatabase, METRIC_EVENT, Realm::Name, Realm::PopulationLevel, printf(), realm, RealmHandle::Realm, REALM_FLAG_OFFLINE, REALM_FLAG_VERSION_MISMATCH, sBattlegroundMgr, sConfigMgr, SERVER_PROCESS_WORLDSERVER, SetProcessPriority(), BigNumber::SetRand(), Acore::Banner::Show(), ShutdownCLIThread(), SignalHandler(), sLog, sMapMgr, sMetric, sOutdoorPvPMgr, sScriptMgr, sSecretMgr, FreezeDetector::Start(), StartDB(), StartRaSocketAcceptor(), StopDB(), World::StopNow(), sWorld, sWorldSocketMgr, OpenSSLCrypto::threadsCleanup(), OpenSSLCrypto::threadsSetup(), usage(), and WorldUpdateLoop().
PrintCliPrefix()
static void PrintCliPrefix () inline static
Definition at line 41 of file CliRunnable.cpp.
 {
     printf("%s", CLI_PREFIX);
 }
References CLI_PREFIX, and printf().
Referenced by CliThread(), and commandFinished().
ShutdownAuctionListingThread()
void ShutdownAuctionListingThread (std::thread * thread)
Definition at line 770 of file Main.cpp.
 {
     if (thread != nullptr)
     {
         thread->join();
         delete thread;
     }
 }
ShutdownCLIThread()
void ShutdownCLIThread (std::thread * cliThread)
Definition at line 517 of file Main.cpp.
 {
     if (cliThread != nullptr)
     {
 #ifdef _WIN32
         // First try to cancel any I/O in the CLI thread
         if (!CancelSynchronousIo(cliThread->native_handle()))
         {
             // if CancelSynchronousIo() fails, print the error and try with old way
             DWORD errorCode = GetLastError();
             LPCSTR errorBuffer;
             DWORD formatReturnCode = FormatMessage(FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_IGNORE_INSERTS,
                 nullptr, errorCode, 0, (LPTSTR)&errorBuffer, 0, nullptr);
             if (!formatReturnCode)
                 errorBuffer = "Unknown error";
             LOG_DEBUG("server.worldserver", "Error cancelling I/O of CliThread, error code %u, detail: %s", uint32(errorCode), errorBuffer);
             if (!formatReturnCode)
                 LocalFree((LPSTR)errorBuffer);
             // send keyboard input to safely unblock the CLI thread
             INPUT_RECORD b[4];
             HANDLE hStdIn = GetStdHandle(STD_INPUT_HANDLE);
             b[0].EventType = KEY_EVENT;
             b[0].Event.KeyEvent.bKeyDown = TRUE;
             b[0].Event.KeyEvent.uChar.AsciiChar = 'X';
             b[0].Event.KeyEvent.wVirtualKeyCode = 'X';
             b[0].Event.KeyEvent.wRepeatCount = 1;
             b[1].EventType = KEY_EVENT;
             b[1].Event.KeyEvent.bKeyDown = FALSE;
             b[1].Event.KeyEvent.uChar.AsciiChar = 'X';
             b[1].Event.KeyEvent.wVirtualKeyCode = 'X';
             b[1].Event.KeyEvent.wRepeatCount = 1;
             b[2].EventType = KEY_EVENT;
             b[2].Event.KeyEvent.bKeyDown = TRUE;
             b[2].Event.KeyEvent.dwControlKeyState = 0;
             b[2].Event.KeyEvent.uChar.AsciiChar = '\r';
             b[2].Event.KeyEvent.wVirtualKeyCode = VK_RETURN;
             b[2].Event.KeyEvent.wRepeatCount = 1;
             b[2].Event.KeyEvent.wVirtualScanCode = 0x1c;
             b[3].EventType = KEY_EVENT;
             b[3].Event.KeyEvent.bKeyDown = FALSE;
             b[3].Event.KeyEvent.dwControlKeyState = 0;
             b[3].Event.KeyEvent.uChar.AsciiChar = '\r';
             b[3].Event.KeyEvent.wVirtualKeyCode = VK_RETURN;
             b[3].Event.KeyEvent.wVirtualScanCode = 0x1c;
             b[3].Event.KeyEvent.wRepeatCount = 1;
             DWORD numb;
             WriteConsoleInput(hStdIn, b, 4, &numb);
         }
 #endif
         cliThread->join();
         delete cliThread;
     }
 }
References b, FALSE, HANDLE, LOG_DEBUG, and TRUE.
Referenced by main().
SignalHandler()
void SignalHandler (boost::system::error_code const & error, int signalNumber)
Definition at line 622 of file Main.cpp.
 {
     if (!error)
         World::StopNow(SHUTDOWN_EXIT_CODE);
 }
References error(), SHUTDOWN_EXIT_CODE, and World::StopNow().
Start()
static void FreezeDetector::Start (std::shared_ptr< FreezeDetector > const & freezeDetector) inline static
Definition at line 94 of file Main.cpp.
     {
         freezeDetector->_timer.expires_from_now(boost::posix_time::seconds(5));
         freezeDetector->_timer.async_wait(std::bind(&FreezeDetector::Handler, std::weak_ptr<FreezeDetector>(freezeDetector), std::placeholders::_1));
     }
References FreezeDetector::Handler(), and G3D::units::seconds().
Referenced by main().
StartDB()
bool StartDB ()
Initialize connection to the databases.
Get the realm Id from the configuration file
Clean the database before starting
Insert version info into DB
Definition at line 446 of file Main.cpp.
 {
     MySQL::Library_Init();
     // Load databases
     DatabaseLoader loader("server.worldserver");
     loader
         .AddDatabase(LoginDatabase, "Login")
         .AddDatabase(CharacterDatabase, "Character")
         .AddDatabase(WorldDatabase, "World");
     if (!loader.Load())
         return false;
     realm.Id.Realm = sConfigMgr->GetIntDefault("RealmID", 0);
     if (!realm.Id.Realm)
     {
         LOG_ERROR("server.worldserver", "Realm ID not defined in configuration file");
         return false;
     }
     else if (realm.Id.Realm > 255)
     {
         /*
          * Due to the client only being able to read a realm.Id.Realm
          * with a size of uint8 we can "only" store up to 255 realms
          * anything further the client will behave anormaly
         */
         LOG_ERROR("server.worldserver", "Realm ID must range from 1 to 255");
         return false;
     }
     LOG_INFO("server.loading", "Loading world information...");
     LOG_INFO("server.loading", "> RealmID:              %u", realm.Id.Realm);
     ClearOnlineAccounts();
     WorldDatabase.PExecute("UPDATE version SET core_version = '%s', core_revision = '%s'", GitRevision::GetFullVersion(), GitRevision::GetHash());        // One-time query
     sWorld->LoadDBVersion();
     sWorld->LoadDBRevision();
     LOG_INFO("server.loading", "> Version DB world:     %s", sWorld->GetDBVersion());
     sScriptMgr->OnAfterDatabasesLoaded(loader.GetUpdateFlags());
     return true;
 }
References DatabaseLoader::AddDatabase(), CharacterDatabase, ClearOnlineAccounts(), GitRevision::GetFullVersion(), GitRevision::GetHash(), DatabaseLoader::GetUpdateFlags(), Realm::Id, MySQL::Library_Init(), DatabaseLoader::Load(), LOG_ERROR, LOG_INFO, LoginDatabase, realm, RealmHandle::Realm, sConfigMgr, sScriptMgr, sWorld, and WorldDatabase.
StartRaSocketAcceptor()
AsyncAcceptor * StartRaSocketAcceptor (Acore::Asio::IoContext & ioContext)
Definition at line 655 of file Main.cpp.
 {
     uint16 raPort = uint16(sConfigMgr->GetOption<int32>("Ra.Port", 3443));
     std::string raListener = sConfigMgr->GetOption<std::string>("Ra.IP", "0.0.0.0");
     AsyncAcceptor* acceptor = new AsyncAcceptor(ioContext, raListener, raPort);
     if (!acceptor->Bind())
     {
         LOG_ERROR("server.worldserver", "Failed to bind RA socket acceptor");
         delete acceptor;
         return nullptr;
     }
     acceptor->AsyncAccept<RASession>();
     return acceptor;
 }
References LOG_ERROR, and sConfigMgr.
Referenced by main().
StopDB()
void StopDB ()
Definition at line 497 of file Main.cpp.
 {
     CharacterDatabase.Close();
     WorldDatabase.Close();
     LoginDatabase.Close();
     MySQL::Library_End();
 }
References CharacterDatabase, MySQL::Library_End(), LoginDatabase, and WorldDatabase.
usage()
void usage (const char * prog)
Print out the usage string for this program on the console.
Definition at line 121 of file Main.cpp.
 {
     printf("Usage:\n");
     printf(" %s [<options>]\n", prog);
     printf("    -c config_file           use config_file as configuration file\n");
 #ifdef _WIN32
     printf("    Running as service functions:\n");
     printf("    --service                run as service\n");
     printf("    -s install               install service\n");
     printf("    -s uninstall             uninstall service\n");
 #endif
 }
References printf(), and prog.
utf8print()
void utf8print (void * , std::string_view str)
Definition at line 77 of file CliRunnable.cpp.
 {
 #if AC_PLATFORM == AC_PLATFORM_WINDOWS
     std::wstring wbuf;
     if (!Utf8toWStr(str, wbuf))
         return;
     wprintf(L"%s", wbuf.c_str());
 #else
 {
     printf(STRING_VIEW_FMT, STRING_VIEW_FMT_ARG(str));
     fflush(stdout);
 }
 #endif
 }
References printf(), STRING_VIEW_FMT, STRING_VIEW_FMT_ARG, and Utf8toWStr().
Referenced by CliThread().
WorldUpdateLoop()
void WorldUpdateLoop ()
While we have not World::m_stopEvent, update the world
Definition at line 578 of file Main.cpp.
 {
     uint32 realCurrTime = 0;
     uint32 realPrevTime = getMSTime();
     LoginDatabase.WarnAboutSyncQueries(true);
     CharacterDatabase.WarnAboutSyncQueries(true);
     WorldDatabase.WarnAboutSyncQueries(true);
     while (!World::IsStopped())
     {
         ++World::m_worldLoopCounter;
         realCurrTime = getMSTime();
         uint32 diff = getMSTimeDiff(realPrevTime, realCurrTime);
         sWorld->Update(diff);
         realPrevTime = realCurrTime;
         uint32 executionTimeDiff = getMSTimeDiff(realCurrTime, getMSTime());
         devDiffTracker.Update(executionTimeDiff);
         avgDiffTracker.Update(executionTimeDiff > WORLD_SLEEP_CONST ? executionTimeDiff : WORLD_SLEEP_CONST);
         // we know exactly how long it took to update the world, if the update took less than WORLD_SLEEP_CONST, sleep for WORLD_SLEEP_CONST - world update time
         if (executionTimeDiff < WORLD_SLEEP_CONST)
         {
             std::this_thread::sleep_for(Milliseconds(WORLD_SLEEP_CONST - executionTimeDiff));
         }
 #ifdef _WIN32
         if (m_ServiceStatus == 0)
             World::StopNow(SHUTDOWN_EXIT_CODE);
         while (m_ServiceStatus == 2)
             Sleep(1000);
 #endif
     }
     LoginDatabase.WarnAboutSyncQueries(false);
     CharacterDatabase.WarnAboutSyncQueries(false);
     WorldDatabase.WarnAboutSyncQueries(false);
 }
References avgDiffTracker, CharacterDatabase, devDiffTracker, diff(), getMSTime(), getMSTimeDiff(), World::IsStopped(), LoginDatabase, World::m_worldLoopCounter, SHUTDOWN_EXIT_CODE, World::StopNow(), sWorld, AvgDiffTracker::Update(), WORLD_SLEEP_CONST, and WorldDatabase.
Referenced by main().
Variable Documentation
_lastChangeMsTime
uint32 FreezeDetector::_lastChangeMsTime private
Definition at line 105 of file Main.cpp.
_maxCoreStuckTimeInMs
uint32 FreezeDetector::_maxCoreStuckTimeInMs private
Definition at line 106 of file Main.cpp.
_timer
Acore::Asio::DeadlineTimer FreezeDetector::_timer private
Definition at line 103 of file Main.cpp.
_worldLoopCounter
uint32 FreezeDetector::_worldLoopCounter private
Definition at line 104 of file Main.cpp.
CLI_PREFIX
constexpr char CLI_PREFIX[] = "AC> " static constexpr
Definition at line 39 of file CliRunnable.cpp.
Referenced by CliThread(), and PrintCliPrefix().