Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/tcache_inlines.h File Reference
tcache_inlines.h File Reference
#include "jemalloc/internal/bin.h"
#include "jemalloc/internal/jemalloc_internal_types.h"
#include "jemalloc/internal/sc.h"
#include "jemalloc/internal/sz.h"
#include "jemalloc/internal/ticker.h"
#include "jemalloc/internal/util.h"
Functions
static bool tcache_enabled_get (tsd_t *tsd)
static void tcache_enabled_set (tsd_t *tsd, bool enabled)
JEMALLOC_ALWAYS_INLINE void tcache_event (tsd_t *tsd, tcache_t *tcache)
JEMALLOC_ALWAYS_INLINE void * tcache_alloc_small (tsd_t *tsd, arena_t *arena, tcache_t *tcache, size_t size, szind_t binind, bool zero, bool slow_path)
JEMALLOC_ALWAYS_INLINE void * tcache_alloc_large (tsd_t *tsd, arena_t *arena, tcache_t *tcache, size_t size, szind_t binind, bool zero, bool slow_path)
JEMALLOC_ALWAYS_INLINE void tcache_dalloc_small (tsd_t *tsd, tcache_t *tcache, void *ptr, szind_t binind, bool slow_path)
JEMALLOC_ALWAYS_INLINE void tcache_dalloc_large (tsd_t *tsd, tcache_t *tcache, void *ptr, szind_t binind, bool slow_path)
JEMALLOC_ALWAYS_INLINE tcache_t * tcaches_get (tsd_t *tsd, unsigned ind)
Function Documentation
tcache_alloc_large()
JEMALLOC_ALWAYS_INLINE void* tcache_alloc_large (tsd_t * tsd, arena_t * arena, tcache_t * tcache, size_t size, szind_t binind, bool zero, bool slow_path)
Definition at line 104 of file tcache_inlines.h.
{
     void *ret;
     cache_bin_t *bin;
     bool tcache_success;
     assert(binind >= SC_NBINS &&binind < nhbins);
     bin = tcache_large_bin_get(tcache, binind);
     ret = cache_bin_alloc_easy(bin, &tcache_success);
     assert(tcache_success == (ret != NULL));
     if (unlikely(!tcache_success)) {
         /*
          * Only allocate one large object at a time, because it's quite
          * expensive to create one and not use it.
          */
         arena = arena_choose(tsd, arena);
         if (unlikely(arena == NULL)) {
             return NULL;
         }
         ret = large_malloc(tsd_tsdn(tsd), arena, sz_s2u(size), zero);
         if (ret == NULL) {
             return NULL;
         }
     } else {
         size_t usize JEMALLOC_CC_SILENCE_INIT(0);
         /* Only compute usize on demand */
         if (config_prof || (slow_path && config_fill) ||
             unlikely(zero)) {
             usize = sz_index2size(binind);
             assert(usize <= tcache_maxclass);
         }
         if (likely(!zero)) {
             if (slow_path && config_fill) {
                 if (unlikely(opt_junk_alloc)) {
                     memset(ret, JEMALLOC_ALLOC_JUNK,
                         usize);
                 } else if (unlikely(opt_zero)) {
                     memset(ret, 0, usize);
                 }
             }
         } else {
             memset(ret, 0, usize);
         }
         if (config_stats) {
             bin->tstats.nrequests++;
         }
         if (config_prof) {
             tcache->prof_accumbytes += usize;
         }
     }
     tcache_event(tsd, tcache);
     return ret;
 }
References arena, arena_choose(), assert(), cache_bin_alloc_easy(), config_fill, config_prof, config_stats, JEMALLOC_ALLOC_JUNK, JEMALLOC_CC_SILENCE_INIT, large_malloc, likely, memset, nhbins, cache_bin_stats_s::nrequests, NULL, opt_junk_alloc, opt_zero, tcache_s::prof_accumbytes, ret, SC_NBINS, sz_index2size(), sz_s2u(), tcache_event(), tcache_large_bin_get(), tcache_maxclass, tsd_tsdn(), cache_bin_s::tstats, unlikely, and G3D::zero().
Referenced by arena_malloc().
tcache_alloc_small()
JEMALLOC_ALWAYS_INLINE void* tcache_alloc_small (tsd_t * tsd, arena_t * arena, tcache_t * tcache, size_t size, szind_t binind, bool zero, bool slow_path)
Definition at line 42 of file tcache_inlines.h.
{
     void *ret;
     cache_bin_t *bin;
     bool tcache_success;
     size_t usize JEMALLOC_CC_SILENCE_INIT(0);
     assert(binind < SC_NBINS);
     bin = tcache_small_bin_get(tcache, binind);
     ret = cache_bin_alloc_easy(bin, &tcache_success);
     assert(tcache_success == (ret != NULL));
     if (unlikely(!tcache_success)) {
         bool tcache_hard_success;
         arena = arena_choose(tsd, arena);
         if (unlikely(arena == NULL)) {
             return NULL;
         }
         ret = tcache_alloc_small_hard(tsd_tsdn(tsd), arena, tcache,
             bin, binind, &tcache_hard_success);
         if (tcache_hard_success == false) {
             return NULL;
         }
     }
     assert(ret);
     /*
      * Only compute usize if required.  The checks in the following if
      * statement are all static.
      */
     if (config_prof || (slow_path && config_fill) || unlikely(zero)) {
         usize = sz_index2size(binind);
         assert(tcache_salloc(tsd_tsdn(tsd), ret) == usize);
     }
     if (likely(!zero)) {
         if (slow_path && config_fill) {
             if (unlikely(opt_junk_alloc)) {
                 arena_alloc_junk_small(ret, &bin_infos[binind],
                     false);
             } else if (unlikely(opt_zero)) {
                 memset(ret, 0, usize);
             }
         }
     } else {
         if (slow_path && config_fill && unlikely(opt_junk_alloc)) {
             arena_alloc_junk_small(ret, &bin_infos[binind], true);
         }
         memset(ret, 0, usize);
     }
     if (config_stats) {
         bin->tstats.nrequests++;
     }
     if (config_prof) {
         tcache->prof_accumbytes += usize;
     }
     tcache_event(tsd, tcache);
     return ret;
 }
References arena, arena_alloc_junk_small, arena_choose(), assert(), bin_infos, cache_bin_alloc_easy(), config_fill, config_prof, config_stats, JEMALLOC_CC_SILENCE_INIT, likely, memset, cache_bin_stats_s::nrequests, NULL, opt_junk_alloc, opt_zero, tcache_s::prof_accumbytes, ret, SC_NBINS, sz_index2size(), tcache_alloc_small_hard, tcache_event(), tcache_salloc, tcache_small_bin_get(), tsd_tsdn(), cache_bin_s::tstats, unlikely, and G3D::zero().
Referenced by arena_malloc().
tcache_dalloc_large()
JEMALLOC_ALWAYS_INLINE void tcache_dalloc_large (tsd_t * tsd, tcache_t * tcache, void * ptr, szind_t binind, bool slow_path)
Definition at line 189 of file tcache_inlines.h.
                     {
     cache_bin_t *bin;
     cache_bin_info_t *bin_info;
     assert(tcache_salloc(tsd_tsdn(tsd), ptr)
         > SC_SMALL_MAXCLASS);
     assert(tcache_salloc(tsd_tsdn(tsd), ptr) <= tcache_maxclass);
     if (slow_path && config_fill && unlikely(opt_junk_free)) {
         large_dalloc_junk(ptr, sz_index2size(binind));
     }
     bin = tcache_large_bin_get(tcache, binind);
     bin_info = &tcache_bin_info[binind];
     if (unlikely(bin->ncached == bin_info->ncached_max)) {
         tcache_bin_flush_large(tsd, bin, binind,
             (bin_info->ncached_max >> 1), tcache);
     }
     assert(bin->ncached < bin_info->ncached_max);
     bin->ncached++;
     *(bin->avail - bin->ncached) = ptr;
     tcache_event(tsd, tcache);
 }
References assert(), cache_bin_s::avail, config_fill, large_dalloc_junk, cache_bin_s::ncached, cache_bin_info_s::ncached_max, opt_junk_free, ptr(), SC_SMALL_MAXCLASS, sz_index2size(), tcache_bin_flush_large, tcache_bin_info, tcache_event(), tcache_large_bin_get(), tcache_maxclass, tcache_salloc, tsd_tsdn(), and unlikely.
Referenced by arena_dalloc_large(), and arena_dalloc_promoted().
tcache_dalloc_small()
JEMALLOC_ALWAYS_INLINE void tcache_dalloc_small (tsd_t * tsd, tcache_t * tcache, void * ptr, szind_t binind, bool slow_path)
Definition at line 164 of file tcache_inlines.h.
                     {
     cache_bin_t *bin;
     cache_bin_info_t *bin_info;
     assert(tcache_salloc(tsd_tsdn(tsd), ptr)
         <= SC_SMALL_MAXCLASS);
     if (slow_path && config_fill && unlikely(opt_junk_free)) {
         arena_dalloc_junk_small(ptr, &bin_infos[binind]);
     }
     bin = tcache_small_bin_get(tcache, binind);
     bin_info = &tcache_bin_info[binind];
     if (unlikely(!cache_bin_dalloc_easy(bin, bin_info, ptr))) {
         tcache_bin_flush_small(tsd, tcache, bin, binind,
             (bin_info->ncached_max >> 1));
         bool ret = cache_bin_dalloc_easy(bin, bin_info, ptr);
         assert(ret);
     }
     tcache_event(tsd, tcache);
 }
References arena_dalloc_junk_small, assert(), bin_infos, cache_bin_dalloc_easy(), config_fill, cache_bin_info_s::ncached_max, opt_junk_free, ptr(), ret, SC_SMALL_MAXCLASS, tcache_bin_flush_small, tcache_bin_info, tcache_event(), tcache_salloc, tcache_small_bin_get(), tsd_tsdn(), and unlikely.
Referenced by arena_dalloc(), and arena_sdalloc().
tcache_enabled_get()
static bool tcache_enabled_get (tsd_t * tsd) inline static
Definition at line 12 of file tcache_inlines.h.
{
     return tsd_tcache_enabled_get(tsd);
 }
Referenced by CTL_TSD_RO_NL_CGEN().
tcache_enabled_set()
static void tcache_enabled_set (tsd_t * tsd, bool enabled) inline static
Definition at line 17 of file tcache_inlines.h.
{
     bool was_enabled = tsd_tcache_enabled_get(tsd);
     if (!was_enabled && enabled) {
         tsd_tcache_data_init(tsd);
     } else if (was_enabled && !enabled) {
         tcache_cleanup(tsd);
     }
     /* Commit the state last.  Above calls check current state. */
     tsd_tcache_enabled_set(tsd, enabled);
     tsd_slow_update(tsd);
 }
References tcache_cleanup, tsd_slow_update, and tsd_tcache_data_init.
Referenced by CTL_TSD_RO_NL_CGEN().
tcache_event()
JEMALLOC_ALWAYS_INLINE void tcache_event (tsd_t * tsd, tcache_t * tcache)
Definition at line 31 of file tcache_inlines.h.
{
     if (TCACHE_GC_INCR == 0) {
         return;
     }
     if (unlikely(ticker_tick(&tcache->gc_ticker))) {
         tcache_event_hard(tsd, tcache);
     }
 }
References tcache_s::gc_ticker, tcache_event_hard, TCACHE_GC_INCR, ticker_tick(), and unlikely.
Referenced by tcache_alloc_large(), tcache_alloc_small(), tcache_dalloc_large(), and tcache_dalloc_small().
tcaches_get()
JEMALLOC_ALWAYS_INLINE tcache_t* tcaches_get (tsd_t * tsd, unsigned ind)
Definition at line 216 of file tcache_inlines.h.
{
     tcaches_t *elm = &tcaches[ind];
     if (unlikely(elm->tcache == NULL)) {
         malloc_printf("<jemalloc>: invalid tcache id (%u).\n", ind);
         abort();
     } else if (unlikely(elm->tcache == TCACHES_ELM_NEED_REINIT)) {
         elm->tcache = tcache_create_explicit(tsd);
     }
     return elm->tcache;
 }
References malloc_printf, NULL, tcaches_s::tcache, tcache_create_explicit, tcaches, TCACHES_ELM_NEED_REINIT, and unlikely.
Referenced by imalloc_no_sample(), je_dallocx(), je_rallocx(), and sdallocx_default().