Azerotcore-wotlk: boss_shade_of_aran::boss_aranAI Struct Reference
boss_shade_of_aran::boss_aranAI Struct Reference
Public Member Functions
boss_aranAI (Creature *creature)
void Reset () override
void KilledUnit (Unit *) override
void JustDied (Unit *) override
void EnterCombat (Unit *) override
void FlameWreathEffect ()
void UpdateAI (uint32 diff) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void SpellHit (Unit *, const SpellInfo *Spell) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
uint32 SecondarySpellTimer
uint32 NormalCastTimer
uint32 SuperCastTimer
uint32 BerserkTimer
uint32 CloseDoorTimer
uint8 LastSuperSpell
uint32 FlameWreathTimer
uint32 FlameWreathCheckTime
ObjectGuid FlameWreathTarget [3]
float FWTargPosX [3]
float FWTargPosY [3]
uint32 CurrentNormalSpell
uint32 ArcaneCooldown
uint32 FireCooldown
uint32 FrostCooldown
uint32 DrinkInterruptTimer
bool ElementalsSpawned
bool Drinking
bool DrinkInturrupted
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 78 of file boss_shade_of_aran.cpp.
Constructor & Destructor Documentation
boss_aranAI()
boss_shade_of_aran::boss_aranAI::boss_aranAI (Creature * creature) inline
Definition at line 80 of file boss_shade_of_aran.cpp.
                                         : BossAI(creature, DATA_ARAN)
         {
         }
Member Function Documentation
DamageTaken()
void boss_shade_of_aran::boss_aranAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 523 of file boss_shade_of_aran.cpp.
         {
             if (!DrinkInturrupted && Drinking && damage)
                 DrinkInturrupted = true;
         }
References Drinking, and DrinkInturrupted.
EnterCombat()
void boss_shade_of_aran::boss_aranAI::EnterCombat (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 153 of file boss_shade_of_aran.cpp.
         {
             Talk(SAY_AGGRO);
             instance->SetData(DATA_ARAN, IN_PROGRESS);
             instance->HandleGameObject(instance->GetGuidData(DATA_GO_LIBRARY_DOOR), false);
             DoZoneInCombat();
         }
References DATA_ARAN, DATA_GO_LIBRARY_DOOR, CreatureAI::DoZoneInCombat(), InstanceScript::GetGuidData(), InstanceScript::HandleGameObject(), IN_PROGRESS, BossAI::instance, SAY_AGGRO, ZoneScript::SetData(), and CreatureAI::Talk().
FlameWreathEffect()
void boss_shade_of_aran::boss_aranAI::FlameWreathEffect () inline
Definition at line 162 of file boss_shade_of_aran.cpp.
         {
             std::vector<Unit*> targets;
             ThreatContainer::StorageType const& t_list = me->getThreatMgr().getThreatList();
             if (t_list.empty())
                 return;
             //store the threat list in a different container
             for (ThreatContainer::StorageType::const_iterator itr = t_list.begin(); itr != t_list.end(); ++itr)
             {
                 Unit* target = ObjectAccessor::GetUnit(*me, (*itr)->getUnitGuid());
                 //only on alive players
                 if (target && target->IsAlive() && target->GetTypeId() == TYPEID_PLAYER)
                     targets.push_back(target);
             }
             //cut down to size if we have more than 3 targets
             while (targets.size() > 3)
                 targets.erase(targets.begin() + rand() % targets.size());
             uint32 i = 0;
             for (std::vector<Unit*>::const_iterator itr = targets.begin(); itr != targets.end(); ++itr)
             {
                 if (*itr)
                 {
                     FlameWreathTarget[i] = (*itr)->GetGUID();
                     FWTargPosX[i] = (*itr)->GetPositionX();
                     FWTargPosY[i] = (*itr)->GetPositionY();
                     DoCast((*itr), SPELL_FLAME_WREATH, true);
                     ++i;
                 }
             }
         }
References UnitAI::DoCast(), FlameWreathTarget, FWTargPosX, FWTargPosY, ThreatMgr::getThreatList(), Unit::getThreatMgr(), Object::GetTypeId(), ObjectAccessor::GetUnit(), Unit::IsAlive(), ScriptedAI::me, SPELL_FLAME_WREATH, and TYPEID_PLAYER.
Referenced by UpdateAI().
JustDied()
void boss_shade_of_aran::boss_aranAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 145 of file boss_shade_of_aran.cpp.
         {
             Talk(SAY_DEATH);
             instance->SetData(DATA_ARAN, DONE);
             instance->HandleGameObject(instance->GetGuidData(DATA_GO_LIBRARY_DOOR), true);
         }
References DATA_ARAN, DATA_GO_LIBRARY_DOOR, DONE, InstanceScript::GetGuidData(), InstanceScript::HandleGameObject(), BossAI::instance, SAY_DEATH, ZoneScript::SetData(), and CreatureAI::Talk().
KilledUnit()
void boss_shade_of_aran::boss_aranAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 140 of file boss_shade_of_aran.cpp.
         {
             Talk(SAY_KILL);
         }
References SAY_KILL, and CreatureAI::Talk().
Reset()
void boss_shade_of_aran::boss_aranAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 108 of file boss_shade_of_aran.cpp.
         {
             SecondarySpellTimer = 5000;
             NormalCastTimer = 0;
             SuperCastTimer = 35000;
             BerserkTimer = 720000;
             CloseDoorTimer = 15000;
             LastSuperSpell = rand() % 3;
             FlameWreathTimer = 0;
             FlameWreathCheckTime = 0;
             for (uint8 i = 0; i < 3; ++i)
                 FlameWreathTarget[i].Clear();
             CurrentNormalSpell = 0;
             ArcaneCooldown = 0;
             FireCooldown = 0;
             FrostCooldown = 0;
             DrinkInterruptTimer = 10000;
             ElementalsSpawned = false;
             Drinking = false;
             DrinkInturrupted = false;
             // Not in progress
             instance->SetData(DATA_ARAN, NOT_STARTED);
             instance->HandleGameObject(instance->GetGuidData(DATA_GO_LIBRARY_DOOR), true);
         }
References ArcaneCooldown, BerserkTimer, CloseDoorTimer, CurrentNormalSpell, DATA_ARAN, DATA_GO_LIBRARY_DOOR, Drinking, DrinkInterruptTimer, DrinkInturrupted, ElementalsSpawned, FireCooldown, FlameWreathCheckTime, FlameWreathTarget, FlameWreathTimer, FrostCooldown, InstanceScript::GetGuidData(), InstanceScript::HandleGameObject(), BossAI::instance, LastSuperSpell, NormalCastTimer, NOT_STARTED, SecondarySpellTimer, ZoneScript::SetData(), and SuperCastTimer.
SpellHit()
void boss_shade_of_aran::boss_aranAI::SpellHit (Unit * , const SpellInfo * Spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 529 of file boss_shade_of_aran.cpp.
         {
             //We only care about interrupt effects and only if they are durring a spell currently being cast
             if ((Spell->Effects[0].Effect != SPELL_EFFECT_INTERRUPT_CAST &&
                     Spell->Effects[1].Effect != SPELL_EFFECT_INTERRUPT_CAST &&
                     Spell->Effects[2].Effect != SPELL_EFFECT_INTERRUPT_CAST) || !me->IsNonMeleeSpellCast(false))
                 return;
             //Interrupt effect
             me->InterruptNonMeleeSpells(false);
             //Normally we would set the cooldown equal to the spell duration
             //but we do not have access to the DurationStore
             switch (CurrentNormalSpell)
             {
                 case SPELL_ARCMISSLE:
                     ArcaneCooldown = 5000;
                     break;
                 case SPELL_FIREBALL:
                     FireCooldown = 5000;
                     break;
                 case SPELL_FROSTBOLT:
                     FrostCooldown = 5000;
                     break;
             }
         }
References ArcaneCooldown, CurrentNormalSpell, FireCooldown, FrostCooldown, Unit::InterruptNonMeleeSpells(), Unit::IsNonMeleeSpellCast(), ScriptedAI::me, SPELL_ARCMISSLE, SPELL_EFFECT_INTERRUPT_CAST, SPELL_FIREBALL, and SPELL_FROSTBOLT.
UpdateAI()
void boss_shade_of_aran::boss_aranAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 197 of file boss_shade_of_aran.cpp.
         {
             if (!UpdateVictim())
                 return;
             if (CloseDoorTimer)
             {
                 if (CloseDoorTimer <= diff)
                 {
                     instance->HandleGameObject(instance->GetGuidData(DATA_GO_LIBRARY_DOOR), false);
                     CloseDoorTimer = 0;
                 }
                 else
                     CloseDoorTimer -= diff;
             }
             //Cooldowns for casts
             if (ArcaneCooldown)
             {
                 if (ArcaneCooldown >= diff)
                     ArcaneCooldown -= diff;
                 else
                     ArcaneCooldown = 0;
             }
             if (FireCooldown)
             {
                 if (FireCooldown >= diff)
                     FireCooldown -= diff;
                 else
                     FireCooldown = 0;
             }
             if (FrostCooldown)
             {
                 if (FrostCooldown >= diff)
                     FrostCooldown -= diff;
                 else
                     FrostCooldown = 0;
             }
             if (!Drinking && me->GetMaxPower(POWER_MANA) && (me->GetPower(POWER_MANA) * 100 / me->GetMaxPower(POWER_MANA)) < 20)
             {
                 Drinking = true;
                 me->InterruptNonMeleeSpells(false);
                 Talk(SAY_DRINK);
                 if (!DrinkInturrupted)
                 {
                     DoCast(me, SPELL_MASS_POLY, true);
                     DoCast(me, SPELL_CONJURE, false);
                     DoCast(me, SPELL_DRINK, false);
                     me->SetStandState(UNIT_STAND_STATE_SIT);
                     DrinkInterruptTimer = 10000;
                 }
             }
             //Drink Interrupt
             if (Drinking && DrinkInturrupted)
             {
                 Drinking = false;
                 me->RemoveAurasDueToSpell(SPELL_DRINK);
                 me->SetStandState(UNIT_STAND_STATE_STAND);
                 me->SetPower(POWER_MANA, me->GetMaxPower(POWER_MANA) - 32000);
                 DoCast(me, SPELL_POTION, false);
             }
             //Drink Interrupt Timer
             if (Drinking && !DrinkInturrupted)
             {
                 if (DrinkInterruptTimer >= diff)
                     DrinkInterruptTimer -= diff;
                 else
                 {
                     me->SetStandState(UNIT_STAND_STATE_STAND);
                     DoCast(me, SPELL_POTION, true);
                     DoCast(me, SPELL_AOE_PYROBLAST, false);
                     DrinkInturrupted = true;
                     Drinking = false;
                 }
             }
             //Don't execute any more code if we are drinking
             if (Drinking)
                 return;
             //Normal casts
             if (NormalCastTimer <= diff)
             {
                 if (!me->IsNonMeleeSpellCast(false))
                 {
                     Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 100, true);
                     if (!target)
                         return;
                     uint32 Spells[3];
                     uint8 AvailableSpells = 0;
                     //Check for what spells are not on cooldown
                     if (!ArcaneCooldown)
                     {
                         Spells[AvailableSpells] = SPELL_ARCMISSLE;
                         ++AvailableSpells;
                     }
                     if (!FireCooldown)
                     {
                         Spells[AvailableSpells] = SPELL_FIREBALL;
                         ++AvailableSpells;
                     }
                     if (!FrostCooldown)
                     {
                         Spells[AvailableSpells] = SPELL_FROSTBOLT;
                         ++AvailableSpells;
                     }
                     //If no available spells wait 1 second and try again
                     if (AvailableSpells)
                     {
                         CurrentNormalSpell = Spells[rand() % AvailableSpells];
                         DoCast(target, CurrentNormalSpell);
                     }
                 }
                 NormalCastTimer = 1000;
             }
             else
                 NormalCastTimer -= diff;
             if (SecondarySpellTimer <= diff)
             {
                 switch (urand(0, 1))
                 {
                     case 0:
                         DoCast(me, SPELL_AOE_CS);
                         break;
                     case 1:
                         if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 100, true))
                             DoCast(target, SPELL_CHAINSOFICE);
                         break;
                 }
                 SecondarySpellTimer = urand(5000, 20000);
             }
             else
                 SecondarySpellTimer -= diff;
             if (SuperCastTimer <= diff)
             {
                 uint8 Available[2];
                 switch (LastSuperSpell)
                 {
                     case SUPER_AE:
                         Available[0] = SUPER_FLAME;
                         Available[1] = SUPER_BLIZZARD;
                         break;
                     case SUPER_FLAME:
                         Available[0] = SUPER_AE;
                         Available[1] = SUPER_BLIZZARD;
                         break;
                     case SUPER_BLIZZARD:
                         Available[0] = SUPER_FLAME;
                         Available[1] = SUPER_AE;
                         break;
                 }
                 LastSuperSpell = Available[urand(0, 1)];
                 switch (LastSuperSpell)
                 {
                     case SUPER_AE:
                         Talk(SAY_EXPLOSION);
                         DoCast(me, SPELL_BLINK_CENTER, true);
                         DoCast(me, SPELL_PLAYERPULL, true);
                         DoCast(me, SPELL_MASSSLOW, true);
                         DoCast(me, SPELL_AEXPLOSION, false);
                         break;
                     case SUPER_FLAME:
                         Talk(SAY_FLAMEWREATH);
                         FlameWreathTimer = 20000;
                         FlameWreathCheckTime = 500;
                         FlameWreathTarget[0].Clear();
                         FlameWreathTarget[1].Clear();
                         FlameWreathTarget[2].Clear();
                         FlameWreathEffect();
                         break;
                     case SUPER_BLIZZARD:
                         Talk(SAY_BLIZZARD);
                         if (Creature* pSpawn = me->SummonCreature(CREATURE_ARAN_BLIZZARD, 0.0f, 0.0f, 0.0f, 0.0f, TEMPSUMMON_TIMED_DESPAWN, 25000))
{
                             pSpawn->SetFaction(me->GetFaction());
                             pSpawn->CastSpell(pSpawn, SPELL_CIRCULAR_BLIZZARD, false);
                         }
                         break;
                 }
                 SuperCastTimer = urand(35000, 40000);
             }
             else
                 SuperCastTimer -= diff;
             if (!ElementalsSpawned && HealthBelowPct(40))
             {
                 ElementalsSpawned = true;
                 Creature* ElementalOne = me->SummonCreature(CREATURE_WATER_ELEMENTAL, -11168.1f, -1939.29f, 232.092f, 1.46f, TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN, 90000);
                 Creature* ElementalTwo = me->SummonCreature(CREATURE_WATER_ELEMENTAL, -11138.2f, -1915.38f, 232.092f, 3.00f, TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN, 90000);
                 Creature* ElementalThree = me->SummonCreature(CREATURE_WATER_ELEMENTAL, -11161.7f, -1885.36f, 232.092f, 4.59f, TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN, 90000);
                 Creature* ElementalFour = me->SummonCreature(CREATURE_WATER_ELEMENTAL, -11192.4f, -1909.36f, 232.092f, 6.19f, TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN, 90000);
                 if (ElementalOne)
                 {
                     Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 1, 100, true);
                     if (!target)
                         return;
                     DoStartNoMovement(target);
                     ElementalOne->SetInCombatWithZone();
                     ElementalOne->CombatStart(target);
                     ElementalOne->SetFaction(me->GetFaction());
                     ElementalOne->SetUnitMovementFlags(MOVEMENTFLAG_ROOT);
                     ElementalOne->SetModifierValue(UNIT_MOD_RESISTANCE_FROST, BASE_VALUE, 0);
                 }
                 if (ElementalTwo)
                 {
                     Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 1, 100, true);
                     if (!target)
                         return;
                     DoStartNoMovement(target);
                     ElementalTwo->SetInCombatWithZone();
                     ElementalTwo->CombatStart(target);
                     ElementalTwo->SetFaction(me->GetFaction());
                     ElementalTwo->SetUnitMovementFlags(MOVEMENTFLAG_ROOT);
                     ElementalTwo->SetModifierValue(UNIT_MOD_RESISTANCE_FROST, BASE_VALUE, 0);
                 }
                 if (ElementalThree)
                 {
                     Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 1, 100, true);
                     if (!target)
                         return;
                     DoStartNoMovement(target);
                     ElementalThree->SetInCombatWithZone();
                     ElementalThree->CombatStart(target);
                     ElementalThree->SetFaction(me->GetFaction());
                     ElementalThree->SetUnitMovementFlags(MOVEMENTFLAG_ROOT);
                     ElementalThree->SetModifierValue(UNIT_MOD_RESISTANCE_FROST, BASE_VALUE, 0);
                 }
                 if (ElementalFour)
                 {
                     Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 1, 100, true);
                     if (!target)
                         return;
                     DoStartNoMovement(target);
                     ElementalFour->SetInCombatWithZone();
                     ElementalFour->CombatStart(target);
                     ElementalFour->SetFaction(me->GetFaction());
                     ElementalFour->SetUnitMovementFlags(MOVEMENTFLAG_ROOT);
                     ElementalFour->SetModifierValue(UNIT_MOD_RESISTANCE_FROST, BASE_VALUE, 0);
                 }
                 Talk(SAY_ELEMENTALS);
             }
             if (BerserkTimer <= diff)
             {
                 for (uint32 i = 0; i < 5; ++i)
                 {
                     if (Creature* unit = me->SummonCreature(CREATURE_SHADOW_OF_ARAN, 0.0f, 0.0f, 0.0f, 0.0f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 5000))
                     {
                         unit->Attack(me->GetVictim(), true);
                         unit->SetFaction(me->GetFaction());
                     }
                 }
                 Talk(SAY_TIMEOVER);
                 BerserkTimer = 60000;
             }
             else
                 BerserkTimer -= diff;
             //Flame Wreath check
             if (FlameWreathTimer)
             {
                 if (FlameWreathTimer >= diff)
                     FlameWreathTimer -= diff;
                 else
                     FlameWreathTimer = 0;
                 if (FlameWreathCheckTime <= diff)
                 {
                     for (uint8 i = 0; i < 3; ++i)
                     {
                         if (!FlameWreathTarget[i])
                             continue;
                         Unit* unit = ObjectAccessor::GetUnit(*me, FlameWreathTarget[i]);
                         if (unit && !unit->IsWithinDist2d(FWTargPosX[i], FWTargPosY[i], 3))
{
                             unit->CastSpell(unit, 20476, true, 0, 0, me->GetGUID());
                             unit->CastSpell(unit, 11027, true);
                             FlameWreathTarget[i].Clear();
                         }
                     }
                     FlameWreathCheckTime = 500;
                 }
                 else
                     FlameWreathCheckTime -= diff;
             }
             if (ArcaneCooldown && FireCooldown && FrostCooldown)
                 DoMeleeAttackIfReady();
         }
References ArcaneCooldown, BASE_VALUE, BerserkTimer, Unit::CastSpell(), ObjectGuid::Clear(), CloseDoorTimer, Unit::CombatStart(), CREATURE_ARAN_BLIZZARD, CREATURE_SHADOW_OF_ARAN, CREATURE_WATER_ELEMENTAL, CurrentNormalSpell, DATA_GO_LIBRARY_DOOR, diff(), UnitAI::DoCast(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DoStartNoMovement(), Drinking, DrinkInterruptTimer, DrinkInturrupted, ElementalsSpawned, FireCooldown, FlameWreathCheckTime, FlameWreathEffect(), FlameWreathTarget, FlameWreathTimer, FrostCooldown, FWTargPosX, FWTargPosY, Unit::GetFaction(), Object::GetGUID(), InstanceScript::GetGuidData(), Unit::GetMaxPower(), Unit::GetPower(), ObjectAccessor::GetUnit(), Unit::GetVictim(), InstanceScript::HandleGameObject(), ScriptedAI::HealthBelowPct(), BossAI::instance, Unit::InterruptNonMeleeSpells(), Unit::IsNonMeleeSpellCast(), WorldObject::IsWithinDist2d(), LastSuperSpell, ScriptedAI::me, MOVEMENTFLAG_ROOT, NormalCastTimer, POWER_MANA, Unit::RemoveAurasDueToSpell(), SAY_BLIZZARD, SAY_DRINK, SAY_ELEMENTALS, SAY_EXPLOSION, SAY_FLAMEWREATH, SAY_TIMEOVER, SecondarySpellTimer, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Unit::SetFaction(), Creature::SetInCombatWithZone(), Unit::SetModifierValue(), Unit::SetPower(), Unit::SetStandState(), Unit::SetUnitMovementFlags(), SPELL_AEXPLOSION, SPELL_AOE_CS, SPELL_AOE_PYROBLAST, SPELL_ARCMISSLE, SPELL_BLINK_CENTER, SPELL_CHAINSOFICE, SPELL_CIRCULAR_BLIZZARD, SPELL_CONJURE, SPELL_DRINK, SPELL_FIREBALL, SPELL_FROSTBOLT, SPELL_MASS_POLY, SPELL_MASSSLOW, SPELL_PLAYERPULL, SPELL_POTION, WorldObject::SummonCreature(), SUPER_AE, SUPER_BLIZZARD, SUPER_FLAME, SuperCastTimer, CreatureAI::Talk(), TEMPSUMMON_TIMED_DESPAWN, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, TEMPSUMMON_TIMED_OR_CORPSE_DESPAWN, UNIT_MOD_RESISTANCE_FROST, UNIT_STAND_STATE_SIT, UNIT_STAND_STATE_STAND, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
ArcaneCooldown
uint32 boss_shade_of_aran::boss_aranAI::ArcaneCooldown
Definition at line 99 of file boss_shade_of_aran.cpp.
Referenced by Reset(), SpellHit(), and UpdateAI().
BerserkTimer
uint32 boss_shade_of_aran::boss_aranAI::BerserkTimer
Definition at line 87 of file boss_shade_of_aran.cpp.
Referenced by Reset(), and UpdateAI().
CloseDoorTimer
uint32 boss_shade_of_aran::boss_aranAI::CloseDoorTimer
Definition at line 88 of file boss_shade_of_aran.cpp.
Referenced by Reset(), and UpdateAI().
CurrentNormalSpell
uint32 boss_shade_of_aran::boss_aranAI::CurrentNormalSpell
Definition at line 98 of file boss_shade_of_aran.cpp.
Referenced by Reset(), SpellHit(), and UpdateAI().
Drinking
bool boss_shade_of_aran::boss_aranAI::Drinking
Definition at line 106 of file boss_shade_of_aran.cpp.
Referenced by DamageTaken(), Reset(), and UpdateAI().
DrinkInterruptTimer
uint32 boss_shade_of_aran::boss_aranAI::DrinkInterruptTimer
Definition at line 103 of file boss_shade_of_aran.cpp.
Referenced by Reset(), and UpdateAI().
DrinkInturrupted
bool boss_shade_of_aran::boss_aranAI::DrinkInturrupted
Definition at line 107 of file boss_shade_of_aran.cpp.
Referenced by DamageTaken(), Reset(), and UpdateAI().
ElementalsSpawned
bool boss_shade_of_aran::boss_aranAI::ElementalsSpawned
Definition at line 105 of file boss_shade_of_aran.cpp.
Referenced by Reset(), and UpdateAI().
FireCooldown
uint32 boss_shade_of_aran::boss_aranAI::FireCooldown
Definition at line 100 of file boss_shade_of_aran.cpp.
Referenced by Reset(), SpellHit(), and UpdateAI().
FlameWreathCheckTime
uint32 boss_shade_of_aran::boss_aranAI::FlameWreathCheckTime
Definition at line 93 of file boss_shade_of_aran.cpp.
Referenced by Reset(), and UpdateAI().
FlameWreathTarget
ObjectGuid boss_shade_of_aran::boss_aranAI::FlameWreathTarget[3]
Definition at line 94 of file boss_shade_of_aran.cpp.
Referenced by FlameWreathEffect(), Reset(), and UpdateAI().
FlameWreathTimer
uint32 boss_shade_of_aran::boss_aranAI::FlameWreathTimer
Definition at line 92 of file boss_shade_of_aran.cpp.
Referenced by Reset(), and UpdateAI().
FrostCooldown
uint32 boss_shade_of_aran::boss_aranAI::FrostCooldown
Definition at line 101 of file boss_shade_of_aran.cpp.
Referenced by Reset(), SpellHit(), and UpdateAI().
FWTargPosX
float boss_shade_of_aran::boss_aranAI::FWTargPosX[3]
Definition at line 95 of file boss_shade_of_aran.cpp.
Referenced by FlameWreathEffect(), and UpdateAI().
FWTargPosY
float boss_shade_of_aran::boss_aranAI::FWTargPosY[3]
Definition at line 96 of file boss_shade_of_aran.cpp.
Referenced by FlameWreathEffect(), and UpdateAI().
LastSuperSpell
uint8 boss_shade_of_aran::boss_aranAI::LastSuperSpell
Definition at line 90 of file boss_shade_of_aran.cpp.
Referenced by Reset(), and UpdateAI().
NormalCastTimer
uint32 boss_shade_of_aran::boss_aranAI::NormalCastTimer
Definition at line 85 of file boss_shade_of_aran.cpp.
Referenced by Reset(), and UpdateAI().
SecondarySpellTimer
uint32 boss_shade_of_aran::boss_aranAI::SecondarySpellTimer
Definition at line 84 of file boss_shade_of_aran.cpp.
Referenced by Reset(), and UpdateAI().
SuperCastTimer
uint32 boss_shade_of_aran::boss_aranAI::SuperCastTimer
Definition at line 86 of file boss_shade_of_aran.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/Karazhan/boss_shade_of_aran.cpp