Azerotcore-wotlk: OutdoorPvPSI Class Reference
OutdoorPvPSI Class Reference
#include <OutdoorPvPSI.h>
Public Member Functions
OutdoorPvPSI ()
bool SetupOutdoorPvP () override
void HandlePlayerEnterZone (Player *player, uint32 zone) override
void HandlePlayerLeaveZone (Player *player, uint32 zone) override
bool Update (uint32 diff) override
void FillInitialWorldStates (WorldPacket &data) override
void SendRemoveWorldStates (Player *player) override
bool HandleAreaTrigger (Player *player, uint32 trigger) override
bool HandleDropFlag (Player *player, uint32 spellId) override
bool HandleCustomSpell (Player *player, uint32 spellId, GameObject *go) override
void UpdateWorldState ()
Public Member Functions inherited from OutdoorPvP
OutdoorPvP ()
~OutdoorPvP () override
void DeleteSpawns ()
virtual bool HandleOpenGo (Player *player, GameObject *go)
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void SendUpdateWorldState (uint32 field, uint32 value)
virtual void HandleKill (Player *killer, Unit *killed)
virtual void HandleKillImpl (Player *, Unit *)
bool IsInsideObjective (Player *player) const
virtual void AwardKillBonus (Player *)
uint32 GetTypeId ()
virtual bool HandleGossipOption (Player *player, Creature *creature, uint32 gossipid)
virtual bool CanTalkTo (Player *player, Creature *c, GossipMenuItems const &gso)
void TeamApplyBuff (TeamId teamId, uint32 spellId, uint32 spellId2=0, Player *sameMapPlr=nullptr)
Map * GetMap () const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Private Attributes
uint32 m_Gathered_A
uint32 m_Gathered_H
TeamId m_LastController
Additional Inherited Members
Public Types inherited from OutdoorPvP
typedef std::map< ObjectGuid::LowType, OPvPCapturePoint * > OPvPCapturePointMap
typedef std::pair< ObjectGuid::LowType, GameObject * > GoScriptPair
typedef std::pair< ObjectGuid::LowType, Creature * > CreatureScriptPair
Protected Member Functions inherited from OutdoorPvP
void BroadcastPacket (WorldPacket &data) const
virtual void HandlePlayerResurrects (Player *player, uint32 zone)
void AddCapturePoint (OPvPCapturePoint *cp)
OPvPCapturePoint * GetCapturePoint (ObjectGuid::LowType spawnId) const
void RegisterZone (uint32 zoneid)
bool HasPlayer (Player const *player) const
void TeamCastSpell (TeamId team, int32 spellId, Player *sameMapPlr=nullptr)
void SetMapFromZone (uint32 zone)
Protected Attributes inherited from OutdoorPvP
OPvPCapturePointMap m_capturePoints
PlayerSet m_players [2]
uint32 m_TypeId
bool m_sendUpdate
std::map< ObjectGuid::LowType, GameObject * > m_GoScriptStore
std::map< ObjectGuid::LowType, Creature * > m_CreatureScriptStore
Map * m_map
Detailed Description
Definition at line 54 of file OutdoorPvPSI.h.
Constructor & Destructor Documentation
OutdoorPvPSI()
OutdoorPvPSI::OutdoorPvPSI ()
Definition at line 31 of file OutdoorPvPSI.cpp.
 {
     m_TypeId = OUTDOOR_PVP_SI;
     m_Gathered_A = 0;
     m_Gathered_H = 0;
     m_LastController = TEAM_NEUTRAL;
 }
References m_Gathered_A, m_Gathered_H, m_LastController, OutdoorPvP::m_TypeId, OUTDOOR_PVP_SI, and TEAM_NEUTRAL.
Member Function Documentation
FillInitialWorldStates()
void OutdoorPvPSI::FillInitialWorldStates (WorldPacket & data) override virtual
Reimplemented from OutdoorPvP.
Definition at line 39 of file OutdoorPvPSI.cpp.
 {
     data << SI_GATHERED_A << m_Gathered_A;
     data << SI_GATHERED_H << m_Gathered_H;
     data << SI_SILITHYST_MAX << SI_MAX_RESOURCES;
 }
References m_Gathered_A, m_Gathered_H, SI_GATHERED_A, SI_GATHERED_H, SI_MAX_RESOURCES, and SI_SILITHYST_MAX.
HandleAreaTrigger()
bool OutdoorPvPSI::HandleAreaTrigger (Player * player, uint32 trigger) override virtual
Reimplemented from OutdoorPvP.
Definition at line 89 of file OutdoorPvPSI.cpp.
 {
     std::lock_guard<std::mutex> guard(sOutdoorPvPMgr->_lock);
     switch (trigger)
     {
         case SI_AREATRIGGER_A:
             if (player->GetTeamId() == TEAM_ALLIANCE && player->HasAura(SI_SILITHYST_FLAG))
             {
                 // remove aura
                 player->RemoveAurasDueToSpell(SI_SILITHYST_FLAG);
                 ++ m_Gathered_A;
                 if (m_Gathered_A >= SI_MAX_RESOURCES)
                 {
                     TeamApplyBuff(TEAM_ALLIANCE, SI_CENARION_FAVOR, 0, player);
                     sWorld->SendZoneText(OutdoorPvPSIBuffZones[0], sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_SI_CAPTURE_A));
                     m_LastController = TEAM_ALLIANCE;
                     m_Gathered_A = 0;
                     m_Gathered_H = 0;
                 }
                 UpdateWorldState();
                 // reward player, xinef: has no effect on characters above level 70
                 if (player->getLevel() < 70)
                     player->CastSpell(player, SI_TRACES_OF_SILITHYST, true);
                 // add 19 honor
                 player->RewardHonor(nullptr, 1, 19);
                 // add 20 cenarion circle repu
                 player->GetReputationMgr().ModifyReputation(sFactionStore.LookupEntry(609), 20);
                 // complete quest
                 player->KilledMonsterCredit(SI_TURNIN_QUEST_CM_A);
             }
             return true;
         case SI_AREATRIGGER_H:
             if (player->GetTeamId() == TEAM_HORDE && player->HasAura(SI_SILITHYST_FLAG))
             {
                 // remove aura
                 player->RemoveAurasDueToSpell(SI_SILITHYST_FLAG);
                 ++ m_Gathered_H;
                 if (m_Gathered_H >= SI_MAX_RESOURCES)
                 {
                     TeamApplyBuff(TEAM_HORDE, SI_CENARION_FAVOR, 0, player);
                     sWorld->SendZoneText(OutdoorPvPSIBuffZones[0], sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_SI_CAPTURE_H));
                     m_LastController = TEAM_HORDE;
                     m_Gathered_A = 0;
                     m_Gathered_H = 0;
                 }
                 UpdateWorldState();
                 // reward player, xinef: has no effect on characters above level 70
                 if (player->getLevel() < 70)
                     player->CastSpell(player, SI_TRACES_OF_SILITHYST, true);
                 // add 19 honor
                 player->RewardHonor(nullptr, 1, 19);
                 // add 20 cenarion circle repu
                 player->GetReputationMgr().ModifyReputation(sFactionStore.LookupEntry(609), 20);
                 // complete quest
                 player->KilledMonsterCredit(SI_TURNIN_QUEST_CM_H);
             }
             return true;
     }
     return false;
 }
References Unit::CastSpell(), Unit::getLevel(), Player::GetReputationMgr(), Player::GetTeamId(), Unit::HasAura(), Player::KilledMonsterCredit(), LANG_OPVP_SI_CAPTURE_A, LANG_OPVP_SI_CAPTURE_H, m_Gathered_A, m_Gathered_H, m_LastController, ReputationMgr::ModifyReputation(), OutdoorPvPSIBuffZones, Unit::RemoveAurasDueToSpell(), Player::RewardHonor(), sFactionStore, SI_AREATRIGGER_A, SI_AREATRIGGER_H, SI_CENARION_FAVOR, SI_MAX_RESOURCES, SI_SILITHYST_FLAG, SI_TRACES_OF_SILITHYST, SI_TURNIN_QUEST_CM_A, SI_TURNIN_QUEST_CM_H, sObjectMgr, sOutdoorPvPMgr, sWorld, TEAM_ALLIANCE, TEAM_HORDE, OutdoorPvP::TeamApplyBuff(), and UpdateWorldState().
HandleCustomSpell()
bool OutdoorPvPSI::HandleCustomSpell (Player * player, uint32 spellId, GameObject * go) override virtual
Reimplemented from OutdoorPvP.
Definition at line 234 of file OutdoorPvPSI.cpp.
 {
     if (!go || spellId != SI_SILITHYST_FLAG_GO_SPELL)
         return false;
     player->CastSpell(player, SI_SILITHYST_FLAG, true);
     if (go->GetGOInfo()->entry == SI_SILITHYST_MOUND)
     {
         // despawn go
         go->SetRespawnTime(0);
         go->Delete();
     }
     return true;
 }
References Unit::CastSpell(), GameObject::Delete(), GameObjectTemplate::entry, GameObject::GetGOInfo(), GameObject::SetRespawnTime(), SI_SILITHYST_FLAG, SI_SILITHYST_FLAG_GO_SPELL, and SI_SILITHYST_MOUND.
HandleDropFlag()
bool OutdoorPvPSI::HandleDropFlag (Player * player, uint32 spellId) override virtual
Reimplemented from OutdoorPvP.
Definition at line 151 of file OutdoorPvPSI.cpp.
 {
     if (spellId == SI_SILITHYST_FLAG)
     {
         // if it was dropped away from the player's turn-in point, then create a silithyst mound, if it was dropped near the areatrigger, then it was dispelled by the outdoorpvp, so do nothing
         switch (player->GetTeamId())
         {
             case TEAM_ALLIANCE:
                 {
                     AreaTrigger const* atEntry = sObjectMgr->GetAreaTrigger(SI_AREATRIGGER_A);
                     if (atEntry)
                     {
                         // 5.0f is safe-distance
                         if (player->GetDistance(atEntry->x, atEntry->y, atEntry->z) > 5.0f + atEntry->radius)
{
                             // he dropped it further, summon mound
                             GameObject* go = sObjectMgr->IsGameObjectStaticTransport(SI_SILITHYST_MOUND) ? new StaticTransport() : new GameObject();
                             Map* map = player->GetMap();
                             if (!map)
{
                                 delete go;
                                 return true;
                             }
                             if (!go->Create(map->GenerateLowGuid<HighGuid::GameObject>(), SI_SILITHYST_MOUND, map, player->GetPhaseMask(), player->GetPositionX(), player->GetPositionY(), player->GetPositionZ(), player->GetOrientation(), G3D::Quat(), 100, GO_STATE_READY))
{
                                 delete go;
                                 return true;
                             }
                             go->SetRespawnTime(0);
                             if (!map->AddToMap(go))
{
                                 delete go;
                                 return true;
                             }
                         }
                     }
                 }
                 break;
             case TEAM_HORDE:
                 {
                     AreaTrigger const* atEntry = sObjectMgr->GetAreaTrigger(SI_AREATRIGGER_H);
                     if (atEntry)
                     {
                         // 5.0f is safe-distance
                         if (player->GetDistance(atEntry->x, atEntry->y, atEntry->z) > 5.0f + atEntry->radius)
{
                             // he dropped it further, summon mound
                             GameObject* go = sObjectMgr->IsGameObjectStaticTransport(SI_SILITHYST_MOUND) ? new StaticTransport() : new GameObject();
                             Map* map = player->GetMap();
                             if (!map)
{
                                 delete go;
                                 return true;
                             }
                             if (!go->Create(map->GenerateLowGuid<HighGuid::GameObject>(), SI_SILITHYST_MOUND, map, player->GetPhaseMask(), player->GetPositionX(), player->GetPositionY(), player->GetPositionZ(), player->GetOrientation(), G3D::Quat(), 100, GO_STATE_READY))
{
                                 delete go;
                                 return true;
                             }
                             go->SetRespawnTime(0);
                             if (!map->AddToMap(go))
{
                                 delete go;
                                 return true;
                             }
                         }
                     }
                 }
                 break;
             default:
                 break;
         }
         return true;
     }
     return false;
 }
References Map::AddToMap(), GameObject::Create(), GameObject, Map::GenerateLowGuid(), WorldObject::GetDistance(), WorldObject::GetMap(), Position::GetOrientation(), WorldObject::GetPhaseMask(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Player::GetTeamId(), GO_STATE_READY, AreaTrigger::radius, GameObject::SetRespawnTime(), SI_AREATRIGGER_A, SI_AREATRIGGER_H, SI_SILITHYST_FLAG, SI_SILITHYST_MOUND, sObjectMgr, TEAM_ALLIANCE, TEAM_HORDE, AreaTrigger::x, AreaTrigger::y, and AreaTrigger::z.
HandlePlayerEnterZone()
void OutdoorPvPSI::HandlePlayerEnterZone (Player * player, uint32 zone) override virtual
Reimplemented from OutdoorPvP.
Definition at line 75 of file OutdoorPvPSI.cpp.
 {
     if (player->GetTeamId() == m_LastController)
         player->CastSpell(player, SI_CENARION_FAVOR, true);
     OutdoorPvP::HandlePlayerEnterZone(player, zone);
 }
References Unit::CastSpell(), Player::GetTeamId(), OutdoorPvP::HandlePlayerEnterZone(), m_LastController, and SI_CENARION_FAVOR.
HandlePlayerLeaveZone()
void OutdoorPvPSI::HandlePlayerLeaveZone (Player * player, uint32 zone) override virtual
Reimplemented from OutdoorPvP.
Definition at line 82 of file OutdoorPvPSI.cpp.
 {
     // remove buffs
     player->RemoveAurasDueToSpell(SI_CENARION_FAVOR);
     OutdoorPvP::HandlePlayerLeaveZone(player, zone);
 }
References OutdoorPvP::HandlePlayerLeaveZone(), Unit::RemoveAurasDueToSpell(), and SI_CENARION_FAVOR.
SendRemoveWorldStates()
void OutdoorPvPSI::SendRemoveWorldStates (Player * player) override virtual
Reimplemented from OutdoorPvP.
Definition at line 46 of file OutdoorPvPSI.cpp.
 {
     player->SendUpdateWorldState(SI_GATHERED_A, 0);
     player->SendUpdateWorldState(SI_GATHERED_H, 0);
     player->SendUpdateWorldState(SI_SILITHYST_MAX, 0);
 }
References Player::SendUpdateWorldState(), SI_GATHERED_A, SI_GATHERED_H, and SI_SILITHYST_MAX.
SetupOutdoorPvP()
bool OutdoorPvPSI::SetupOutdoorPvP () override virtual
Reimplemented from OutdoorPvP.
Definition at line 60 of file OutdoorPvPSI.cpp.
 {
     for (uint8 i = 0; i < OutdoorPvPSIBuffZonesNum; ++i)
         RegisterZone(OutdoorPvPSIBuffZones[i]);
     SetMapFromZone(OutdoorPvPSIBuffZones[0]);
     return true;
 }
References OutdoorPvPSIBuffZones, OutdoorPvPSIBuffZonesNum, OutdoorPvP::RegisterZone(), and OutdoorPvP::SetMapFromZone().
Update()
bool OutdoorPvPSI::Update (uint32 diff) override virtual
Reimplemented from OutdoorPvP.
Definition at line 70 of file OutdoorPvPSI.cpp.
 {
     return false;
 }
UpdateWorldState()
void OutdoorPvPSI::UpdateWorldState ()
Definition at line 53 of file OutdoorPvPSI.cpp.
 {
     SendUpdateWorldState(SI_GATHERED_A, m_Gathered_A);
     SendUpdateWorldState(SI_GATHERED_H, m_Gathered_H);
     SendUpdateWorldState(SI_SILITHYST_MAX, SI_MAX_RESOURCES);
 }
References m_Gathered_A, m_Gathered_H, OutdoorPvP::SendUpdateWorldState(), SI_GATHERED_A, SI_GATHERED_H, SI_MAX_RESOURCES, and SI_SILITHYST_MAX.
Referenced by HandleAreaTrigger().
Member Data Documentation
m_Gathered_A
uint32 OutdoorPvPSI::m_Gathered_A private
Definition at line 79 of file OutdoorPvPSI.h.
Referenced by FillInitialWorldStates(), HandleAreaTrigger(), OutdoorPvPSI(), and UpdateWorldState().
m_Gathered_H
uint32 OutdoorPvPSI::m_Gathered_H private
Definition at line 80 of file OutdoorPvPSI.h.
Referenced by FillInitialWorldStates(), HandleAreaTrigger(), OutdoorPvPSI(), and UpdateWorldState().
m_LastController
TeamId OutdoorPvPSI::m_LastController private
Definition at line 82 of file OutdoorPvPSI.h.
Referenced by HandleAreaTrigger(), HandlePlayerEnterZone(), and OutdoorPvPSI().
The documentation for this class was generated from the following files:
src/server/scripts/OutdoorPvP/OutdoorPvPSI.h
src/server/scripts/OutdoorPvP/OutdoorPvPSI.cpp