Azerotcore-wotlk: deps/mysqllite/mysys/my_sync.c File Reference
my_sync.c File Reference
#include "mysys_priv.h"
#include "mysys_err.h"
#include <errno.h>
Functions
int my_sync (File fd, myf my_flags)
int my_sync_dir (const char *dir_name __attribute__((unused)), myf my_flags __attribute__((unused)))
int my_sync_dir_by_file (const char *file_name __attribute__((unused)), myf my_flags __attribute__((unused)))
Variables
static const char cur_dir_name [] = {FN_CURLIB, 0}
Function Documentation
my_sync()
int my_sync (File fd, myf my_flags)
Definition at line 43 of file my_sync.c.
 {
   int res;
   DBUG_ENTER("my_sync");
   DBUG_PRINT("my",("Fd: %d  my_flags: %d", fd, my_flags));
   do
   {
 #if defined(F_FULLFSYNC)
     /*
       In Mac OS X >= 10.3 this call is safer than fsync() (it forces the
       disk's cache and guarantees ordered writes).
     */
     if (!(res= fcntl(fd, F_FULLFSYNC, 0)))
       break; /* ok */
     /* Some file systems don't support F_FULLFSYNC and fail above: */
     DBUG_PRINT("info",("fcntl(F_FULLFSYNC) failed, falling back"));
 #endif
 #if defined(HAVE_FDATASYNC) && HAVE_DECL_FDATASYNC
     res= fdatasync(fd);
 #elif defined(HAVE_FSYNC)
     res= fsync(fd);
 #elif defined(_WIN32)
     res= my_win_fsync(fd);
 #else
 #error Cannot find a way to sync a file, durability in danger
     res= 0;                 /* No sync (strange OS) */
 #endif
   } while (res == -1 && errno == EINTR);
   if (res)
   {
     int er= errno;
     if (!(my_errno= er))
       my_errno= -1;                             /* Unknown error */
     if ((my_flags & MY_IGNORE_BADFD) &&
         (er == EBADF || er == EINVAL || er == EROFS))
     {
       DBUG_PRINT("info", ("ignoring errno %d", er));
       res= 0;
     }
     else if (my_flags & MY_WME)
       my_error(EE_SYNC, MYF(ME_BELL+ME_WAITTANG), my_filename(fd), my_errno);
   }
   DBUG_RETURN(res);
 } /* my_sync */
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_SYNC, errno, ME_BELL, ME_WAITTANG, my_errno, my_error(), my_filename(), MY_IGNORE_BADFD, MY_WME, and MYF.
Referenced by inline_mysql_file_sync(), and my_copy().
my_sync_dir()
int my_sync_dir (const char *dir_name __attribute__(unused), myf my_flags __attribute__(unused))
Definition at line 135 of file my_sync.c.
 {
   return 0;
 }
my_sync_dir_by_file()
int my_sync_dir_by_file (const char *file_name __attribute__(unused), myf my_flags __attribute__(unused))
Definition at line 168 of file my_sync.c.
 {
   return 0;
 }
Variable Documentation
cur_dir_name
const char cur_dir_name[] = {FN_CURLIB, 0} static
Definition at line 91 of file my_sync.c.