Azerotcore-wotlk: deps/mysqllite/vio/viosocket.c File Reference
viosocket.c File Reference
#include "vio_priv.h"
Macros
#define VIO_UNBUFFERED_READ_MIN_SIZE 2048
Functions
int vio_errno (Vio *vio __attribute__((unused)))
size_t vio_read (Vio *vio, uchar *buf, size_t size)
size_t vio_read_buff (Vio *vio, uchar *buf, size_t size)
my_bool vio_buff_has_data (Vio *vio)
size_t vio_write (Vio *vio, const uchar *buf, size_t size)
int vio_blocking (Vio *vio __attribute__((unused)), my_bool set_blocking_mode, my_bool *old_mode)
my_bool vio_is_blocking (Vio *vio)
int vio_fastsend (Vio *vio __attribute__((unused)))
int vio_keepalive (Vio *vio, my_bool set_keep_alive)
my_bool vio_should_retry (Vio *vio)
my_bool vio_was_interrupted (Vio *vio __attribute__((unused)))
int vio_close (Vio *vio)
const char * vio_description (Vio *vio)
enum enum_vio_type vio_type (Vio *vio)
my_socket vio_fd (Vio *vio)
static void vio_get_normalized_ip (const struct sockaddr *src, int src_length, struct sockaddr *dst, int *dst_length)
my_bool vio_get_normalized_ip_string (const struct sockaddr *addr, int addr_length, char *ip_string, size_t ip_string_size)
my_bool vio_peer_addr (Vio *vio, char *ip_buffer, uint16 *port, size_t ip_buffer_size)
static my_bool socket_poll_read (my_socket sd, uint timeout)
static my_bool socket_peek_read (Vio *vio, uint *bytes)
my_bool vio_poll_read (Vio *vio, uint timeout)
my_bool vio_is_connected (Vio *vio)
void vio_timeout (Vio *vio, uint which, uint timeout)
ssize_t vio_pending (Vio *vio)
int vio_getnameinfo (const struct sockaddr *sa, char *hostname, size_t hostname_size, char *port, size_t port_size, int flags)
Macro Definition Documentation
VIO_UNBUFFERED_READ_MIN_SIZE
#define VIO_UNBUFFERED_READ_MIN_SIZE 2048
Function Documentation
socket_peek_read()
static my_bool socket_peek_read (Vio * vio, uint * bytes) static
Retrieve the amount of data that can be read from a socket.
Parameters
vio A VIO object.
bytes[out] The amount of bytes available.
Return values
FALSE Success.
TRUE Failure.
Definition at line 584 of file viosocket.c.
 {
 #ifdef __WIN__
   int len;
   if (ioctlsocket(vio->sd, FIONREAD, &len))
     return TRUE;
   *bytes= len;
   return FALSE;
 #elif FIONREAD_IN_SYS_IOCTL
   int len;
   if (ioctl(vio->sd, FIONREAD, &len) < 0)
     return TRUE;
   *bytes= len;
   return FALSE;
 #else
   char buf[1024];
   ssize_t res= recv(vio->sd, &buf, sizeof(buf), MSG_PEEK);
   if (res < 0)
     return TRUE;
   *bytes= res;
   return FALSE;
 #endif
 }
References FALSE, st_vio::sd, and TRUE.
Referenced by vio_is_connected().
socket_poll_read()
static my_bool socket_poll_read (my_socket sd, uint timeout) static
Indicate whether there is data to read on a given socket.
Note
An exceptional condition event and/or errors are interpreted as if there is data to read.
Parameters
sd A connected socket.
timeout Maximum time in seconds to poll.
Return values
FALSE There is data to read.
TRUE There is no data to read.
Definition at line 535 of file viosocket.c.
 {
 #ifdef __WIN__
   int res;
   my_socket fd= sd;
   fd_set readfds, errorfds;
   struct timeval tm;
   DBUG_ENTER("socket_poll_read");
   tm.tv_sec= timeout;
   tm.tv_usec= 0;
   FD_ZERO(&readfds);
   FD_ZERO(&errorfds);
   FD_SET(fd, &readfds);
   FD_SET(fd, &errorfds);
   /* The first argument is ignored on Windows, so a conversion to int is OK */
   if ((res= select((int) fd, &readfds, NULL, &errorfds, &tm) <= 0))
   {
     DBUG_RETURN(res < 0 ? 0 : 1);
   }
   res= FD_ISSET(fd, &readfds) || FD_ISSET(fd, &errorfds);
   DBUG_RETURN(!res);
 #elif defined(HAVE_POLL)
   struct pollfd fds;
   int res;
   DBUG_ENTER("socket_poll_read");
   fds.fd=sd;
   fds.events=POLLIN;
   fds.revents=0;
   if ((res=poll(&fds,1,(int) timeout*1000)) <= 0)
   {
     DBUG_RETURN(res < 0 ? 0 : 1);       /* Don't return 1 on errors */
   }
   DBUG_RETURN(fds.revents & (POLLIN | POLLERR | POLLHUP) ? 0 : 1);
 #else
   return 0;
 #endif
 }
References DBUG_ENTER, DBUG_RETURN, and NULL.
Referenced by vio_poll_read().
vio_blocking()
int vio_blocking (Vio *vio __attribute__(unused), my_bool set_blocking_mode, my_bool * old_mode)
Definition at line 127 of file viosocket.c.
 {
   int r=0;
   DBUG_ENTER("vio_blocking");
   *old_mode= test(!(vio->fcntl_mode & O_NONBLOCK));
   DBUG_PRINT("enter", ("set_blocking_mode: %d  old_mode: %d",
                (int) set_blocking_mode, (int) *old_mode));
 #if !defined(__WIN__)
 #if !defined(NO_FCNTL_NONBLOCK)
   if (vio->sd >= 0)
   {
     int old_fcntl=vio->fcntl_mode;
     if (set_blocking_mode)
       vio->fcntl_mode &= ~O_NONBLOCK; /* clear bit */
     else
       vio->fcntl_mode |= O_NONBLOCK; /* set bit */
     if (old_fcntl != vio->fcntl_mode)
     {
       r= fcntl(vio->sd, F_SETFL, vio->fcntl_mode);
       if (r == -1)
       {
         DBUG_PRINT("info", ("fcntl failed, errno %d", errno));
         vio->fcntl_mode= old_fcntl;
       }
     }
   }
 #else
   r= set_blocking_mode ? 0 : 1;
 #endif /* !defined(NO_FCNTL_NONBLOCK) */
 #else /* !defined(__WIN__) */
   if (vio->type != VIO_TYPE_NAMEDPIPE && vio->type != VIO_TYPE_SHARED_MEMORY)
   {
     ulong arg;
     int old_fcntl=vio->fcntl_mode;
     if (set_blocking_mode)
     {
       arg = 0;
       vio->fcntl_mode &= ~O_NONBLOCK; /* clear bit */
     }
     else
     {
       arg = 1;
       vio->fcntl_mode |= O_NONBLOCK; /* set bit */
     }
     if (old_fcntl != vio->fcntl_mode)
       r = ioctlsocket(vio->sd,FIONBIO,(void*) &arg);
   }
   else
     r=  test(!(vio->fcntl_mode & O_NONBLOCK)) != set_blocking_mode;
 #endif /* !defined(__WIN__) */
   DBUG_PRINT("exit", ("%d", r));
   DBUG_RETURN(r);
 }
References arg(), DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, errno, test, VIO_TYPE_NAMEDPIPE, and VIO_TYPE_SHARED_MEMORY.
vio_buff_has_data()
my_bool vio_buff_has_data (Vio * vio)
Definition at line 101 of file viosocket.c.
 {
   return (vio->read_pos != vio->read_end);
 }
References st_vio::read_end, and st_vio::read_pos.
Referenced by vio_init().
vio_close()
int vio_close (Vio * vio)
Definition at line 273 of file viosocket.c.
 {
   int r=0;
   DBUG_ENTER("vio_close");
  if (vio->type != VIO_CLOSED)
   {
     DBUG_ASSERT(vio->type ==  VIO_TYPE_TCPIP ||
       vio->type == VIO_TYPE_SOCKET ||
       vio->type == VIO_TYPE_SSL);
     DBUG_ASSERT(vio->sd >= 0);
     if (shutdown(vio->sd, SHUT_RDWR))
       r= -1;
     if (closesocket(vio->sd))
       r= -1;
   }
   if (r)
   {
     DBUG_PRINT("vio_error", ("close() failed, error: %d",socket_errno));
     /* FIXME: error handling (not critical for MySQL) */
   }
   vio->type= VIO_CLOSED;
   vio->sd=   -1;
   DBUG_RETURN(r);
 }
References closesocket, DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, st_vio::sd, socket_errno, st_vio::type, VIO_CLOSED, VIO_TYPE_SOCKET, VIO_TYPE_SSL, and VIO_TYPE_TCPIP.
vio_description()
const char* vio_description (Vio * vio)
Definition at line 301 of file viosocket.c.
 {
   return vio->desc;
 }
References st_vio::desc.
Referenced by cli_safe_read(), end_server(), and net_clear().
vio_errno()
int vio_errno (Vio *vio __attribute__(unused))
Definition at line 25 of file viosocket.c.
 {
   return socket_errno;      /* On Win32 this mapped to WSAGetLastError() */
 }
References socket_errno.
vio_fastsend()
int vio_fastsend (Vio *vio __attribute__(unused))
Definition at line 195 of file viosocket.c.
 {
   int r=0;
   DBUG_ENTER("vio_fastsend");
 #if defined(IPTOS_THROUGHPUT)
   {
     int tos = IPTOS_THROUGHPUT;
     r= setsockopt(vio->sd, IPPROTO_IP, IP_TOS, (void *) &tos, sizeof(tos));
   }
 #endif                                    /* IPTOS_THROUGHPUT */
   if (!r)
   {
 #ifdef __WIN__
     BOOL nodelay= 1;
 #else
     int nodelay = 1;
 #endif
     r= setsockopt(vio->sd, IPPROTO_TCP, TCP_NODELAY,
                   IF_WIN((const char*), (void*)) &nodelay,
                   sizeof(nodelay));
   }
   if (r)
   {
     DBUG_PRINT("warning", ("Couldn't set socket option for fast send"));
     r= -1;
   }
   DBUG_PRINT("exit", ("%d", r));
   DBUG_RETURN(r);
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, and IF_WIN.
vio_fd()
my_socket vio_fd (Vio * vio)
Definition at line 311 of file viosocket.c.
 {
   return vio->sd;
 }
References st_vio::sd.
Referenced by my_net_init().
vio_get_normalized_ip()
static void vio_get_normalized_ip (const struct sockaddr * src, int src_length, struct sockaddr * dst, int * dst_length) static
Convert a sock-address (AF_INET or AF_INET6) into the "normalized" form, which is the IPv4 form for IPv4-mapped or IPv4-compatible IPv6 addresses.
Note
Background: when IPv4 and IPv6 are used simultaneously, IPv4 addresses may be written in a form of IPv4-mapped or IPv4-compatible IPv6 addresses. That means, one address (a.b.c.d) can be written in three forms:
IPv4: a.b.c.d;
IPv4-compatible IPv6: ::a.b.c.d;
IPv4-mapped IPv4: ::ffff:a.b.c.d;
Having three forms of one address makes it a little difficult to compare addresses with each other (the IPv4-compatible IPv6-address of foo.bar will be different from the IPv4-mapped IPv6-address of foo.bar).
Note
This function can be made public when it's needed.
Parameters
src [in] source IP address (AF_INET or AF_INET6).
src_length [in] length of the src.
dst [out] a buffer to store normalized IP address (sockaddr_storage).
dst_length [out] actual length of the normalized IP address.
Definition at line 339 of file viosocket.c.
 {
   switch (src->sa_family) {
   case AF_INET:
     memcpy(dst, src, src_length);
     *dst_length= src_length;
     break;
 #ifdef HAVE_IPV6
   case AF_INET6:
   {
     const struct sockaddr_in6 *src_addr6= (const struct sockaddr_in6 *) src;
     const struct in6_addr *src_ip6= &(src_addr6->sin6_addr);
     const uint32 *src_ip6_int32= (uint32 *) src_ip6->s6_addr;
     if (IN6_IS_ADDR_V4MAPPED(src_ip6) || IN6_IS_ADDR_V4COMPAT(src_ip6))
     {
       struct sockaddr_in *dst_ip4= (struct sockaddr_in *) dst;
       /*
         This is an IPv4-mapped or IPv4-compatible IPv6 address. It should
         be converted to the IPv4 form.
       */
       *dst_length= sizeof (struct sockaddr_in);
       memset(dst_ip4, 0, *dst_length);
       dst_ip4->sin_family= AF_INET;
       dst_ip4->sin_port= src_addr6->sin6_port;
       /*
         In an IPv4 mapped or compatible address, the last 32 bits represent
         the IPv4 address. The byte orders for IPv6 and IPv4 addresses are
         the same, so a simple copy is possible.
       */
       dst_ip4->sin_addr.s_addr= src_ip6_int32[3];
     }
     else
     {
       /* This is a "native" IPv6 address. */
       memcpy(dst, src, src_length);
       *dst_length= src_length;
     }
     break;
   }
 #endif /* HAVE_IPV6 */
   }
 }
References if(), memcpy, and memset.
Referenced by vio_get_normalized_ip_string(), and vio_peer_addr().
vio_get_normalized_ip_string()
my_bool vio_get_normalized_ip_string (const struct sockaddr * addr, int addr_length, char * ip_string, size_t ip_string_size)
Return the normalized IP address string for a sock-address.
The idea is to return an IPv4-address for an IPv4-mapped and IPv4-compatible IPv6 address.
The function writes the normalized IP address to the given buffer. The buffer should have enough space, otherwise error flag is returned. The system constant INET6_ADDRSTRLEN can be used to reserve buffers of the right size.
Parameters
addr [in] sockaddr object (AF_INET or AF_INET6).
addr_length [in] length of the addr.
ip_string [out] buffer to write normalized IP address.
ip_string_size [in] size of the ip_string.
Returns
Error status.
Return values
TRUE in case of error (the ip_string buffer is not enough).
FALSE on success.
Definition at line 415 of file viosocket.c.
 {
   struct sockaddr_storage norm_addr_storage;
   struct sockaddr *norm_addr= (struct sockaddr *) &norm_addr_storage;
   int norm_addr_length;
   int err_code;
   vio_get_normalized_ip(addr, addr_length, norm_addr, &norm_addr_length);
   err_code= vio_getnameinfo(norm_addr, ip_string, ip_string_size, NULL, 0,
                             NI_NUMERICHOST);
   if (!err_code)
     return FALSE;
   DBUG_PRINT("error", ("getnameinfo() failed with %d (%s).",
                        (int) err_code,
                        (const char *) gai_strerror(err_code)));
   return TRUE;
 }
References DBUG_PRINT, FALSE, NULL, TRUE, vio_get_normalized_ip(), and vio_getnameinfo().
vio_getnameinfo()
int vio_getnameinfo (const struct sockaddr * sa, char * hostname, size_t hostname_size, char * port, size_t port_size, int flags)
This is a wrapper for the system getnameinfo(), because different OS differ in the getnameinfo() implementation:
Solaris 10 requires that the 2nd argument (salen) must match the actual size of the struct sockaddr_storage passed to it;
Mac OS X has sockaddr_in::sin_len and sockaddr_in6::sin6_len and requires them to be filled.
Definition at line 1071 of file viosocket.c.
 {
   int sa_length= 0;
   switch (sa->sa_family) {
   case AF_INET:
     sa_length= sizeof (struct sockaddr_in);
 #ifdef HAVE_SOCKADDR_IN_SIN_LEN
     ((struct sockaddr_in *) sa)->sin_len= sa_length;
 #endif /* HAVE_SOCKADDR_IN_SIN_LEN */
     break;
 #ifdef HAVE_IPV6
   case AF_INET6:
     sa_length= sizeof (struct sockaddr_in6);
 # ifdef HAVE_SOCKADDR_IN6_SIN6_LEN
     ((struct sockaddr_in6 *) sa)->sin6_len= sa_length;
 # endif /* HAVE_SOCKADDR_IN6_SIN6_LEN */
     break;
 #endif /* HAVE_IPV6 */
   }
   return getnameinfo(sa, sa_length,
                      hostname, hostname_size,
                      port, port_size,
                      flags);
 }
Referenced by vio_get_normalized_ip_string(), and vio_peer_addr().
vio_is_blocking()
my_bool vio_is_blocking (Vio * vio)
Definition at line 185 of file viosocket.c.
 {
   my_bool r;
   DBUG_ENTER("vio_is_blocking");
   r = !(vio->fcntl_mode & O_NONBLOCK);
   DBUG_PRINT("exit", ("%d", (int) r));
   DBUG_RETURN(r);
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, and st_vio::fcntl_mode.
Referenced by vio_should_retry().
vio_is_connected()
my_bool vio_is_connected (Vio * vio)
Determine if the endpoint of a connection is still available.
Remarks
The socket is assumed to be disconnected if an EOF condition is encountered.
Parameters
vio The VIO object.
Return values
TRUE EOF condition not found.
FALSE EOF condition is signaled.
Definition at line 645 of file viosocket.c.
 {
   uint bytes= 0;
   DBUG_ENTER("vio_is_connected");
   /* In the presence of errors the socket is assumed to be connected. */
   /*
     The first step of detecting a EOF condition is veryfing
     whether there is data to read. Data in this case would
     be the EOF.
   */
   if (vio_poll_read(vio, 0))
     DBUG_RETURN(TRUE);
   /*
     The second step is read() or recv() from the socket returning
     0 (EOF). Unfortunelly, it's not possible to call read directly
     as we could inadvertently read meaningful connection data.
     Simulate a read by retrieving the number of bytes available to
     read -- 0 meaning EOF.
   */
   if (socket_peek_read(vio, &bytes))
     DBUG_RETURN(TRUE);
 #ifdef HAVE_OPENSSL
   /* There might be buffered data at the SSL layer. */
   if (!bytes && vio->type == VIO_TYPE_SSL)
     bytes= SSL_pending((SSL*) vio->ssl_arg);
 #endif
   DBUG_RETURN(bytes ? TRUE : FALSE);
 }
References DBUG_ENTER, DBUG_RETURN, FALSE, socket_peek_read(), TRUE, st_vio::type, vio_poll_read(), and VIO_TYPE_SSL.
vio_keepalive()
int vio_keepalive (Vio * vio, my_bool set_keep_alive)
Definition at line 228 of file viosocket.c.
 {
   int r=0;
   uint opt = 0;
   DBUG_ENTER("vio_keepalive");
   DBUG_PRINT("enter", ("sd: %d  set_keep_alive: %d", vio->sd, (int)
                set_keep_alive));
   if (vio->type != VIO_TYPE_NAMEDPIPE)
   {
     if (set_keep_alive)
       opt = 1;
     r = setsockopt(vio->sd, SOL_SOCKET, SO_KEEPALIVE, (char *) &opt,
            sizeof(opt));
   }
   DBUG_RETURN(r);
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, st_vio::sd, st_vio::type, and VIO_TYPE_NAMEDPIPE.
vio_peer_addr()
my_bool vio_peer_addr (Vio * vio, char * ip_buffer, uint16 * port, size_t ip_buffer_size)
Return IP address and port of a VIO client socket.
The function returns an IPv4 address if IPv6 support is disabled.
The function returns an IPv4 address if the client socket is associated with an IPv4-compatible or IPv4-mapped IPv6 address. Otherwise, the native IPv6 address is returned.
Definition at line 450 of file viosocket.c.
 {
   DBUG_ENTER("vio_peer_addr");
   DBUG_PRINT("enter", ("Client socked fd: %d", (int) vio->sd));
   if (vio->localhost)
   {
     /*
       Initialize vio->remote and vio->addLen. Set vio->remote to IPv4 loopback
       address.
     */
     struct in_addr *ip4= &((struct sockaddr_in *) &(vio->remote))->sin_addr;
     vio->remote.ss_family= AF_INET;
     vio->addrLen= sizeof (struct sockaddr_in);
     ip4->s_addr= htonl(INADDR_LOOPBACK);
     /* Initialize ip_buffer and port. */
     strmov(ip_buffer, "127.0.0.1");
     *port= 0;
   }
   else
   {
     int err_code;
     char port_buffer[NI_MAXSERV];
     struct sockaddr_storage addr_storage;
     struct sockaddr *addr= (struct sockaddr *) &addr_storage;
     size_socket addr_length= sizeof (addr_storage);
     /* Get sockaddr by socked fd. */
     err_code= getpeername(vio->sd, addr, &addr_length);
     if (err_code)
     {
       DBUG_PRINT("exit", ("getpeername() gave error: %d", socket_errno));
       DBUG_RETURN(TRUE);
     }
     /* Normalize IP address. */
     vio_get_normalized_ip(addr, addr_length,
                           (struct sockaddr *) &vio->remote, &vio->addrLen);
     /* Get IP address & port number. */
     err_code= vio_getnameinfo((struct sockaddr *) &vio->remote,
                               ip_buffer, ip_buffer_size,
                               port_buffer, NI_MAXSERV,
                               NI_NUMERICHOST | NI_NUMERICSERV);
     if (err_code)
     {
       DBUG_PRINT("exit", ("getnameinfo() gave error: %s",
                           gai_strerror(err_code)));
       DBUG_RETURN(TRUE);
     }
     *port= (uint16) strtol(port_buffer, NULL, 10);
   }
   DBUG_PRINT("exit", ("Client IP address: %s; port: %d",
                       (const char *) ip_buffer,
                       (int) *port));
   DBUG_RETURN(FALSE);
 }
References st_vio::addrLen, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, FALSE, st_vio::localhost, NULL, st_vio::remote, st_vio::sd, socket_errno, strmov(), strtol(), TRUE, vio_get_normalized_ip(), and vio_getnameinfo().
vio_pending()
ssize_t vio_pending (Vio * vio)
Number of bytes in the read buffer.
Returns
number of bytes in the read buffer or < 0 if error.
Definition at line 1044 of file viosocket.c.
 {
 #ifdef HAVE_OPENSSL
   SSL *ssl= (SSL*) vio->ssl_arg;
 #endif
   if (vio->read_pos < vio->read_end)
     return vio->read_end - vio->read_pos;
 #ifdef HAVE_OPENSSL
   if (ssl)
     return SSL_pending(ssl);
 #endif
   return 0;
 }
References endif(), if(), st_vio::read_end, and st_vio::read_pos.
vio_poll_read()
my_bool vio_poll_read (Vio * vio, uint timeout)
Indicate whether there is data to read on a given socket.
Remarks
Errors are interpreted as if there is data to read.
Parameters
sd A connected socket.
timeout Maximum time in seconds to wait.
Return values
FALSE There is data (or EOF) to read. Also FALSE if error.
TRUE There is NO data to read or timed out.
Definition at line 621 of file viosocket.c.
 {
   my_socket sd= vio->sd;
   DBUG_ENTER("vio_poll_read");
 #ifdef HAVE_OPENSSL
   if (vio->type == VIO_TYPE_SSL)
     sd= SSL_get_fd((SSL*) vio->ssl_arg);
 #endif
   DBUG_RETURN(socket_poll_read(sd, timeout));
 }
References DBUG_ENTER, DBUG_RETURN, st_vio::sd, socket_poll_read(), st_vio::type, and VIO_TYPE_SSL.
Referenced by vio_is_connected().
vio_read()
size_t vio_read (Vio * vio, uchar * buf, size_t size)
Definition at line 31 of file viosocket.c.
 {
   size_t r;
   DBUG_ENTER("vio_read");
   DBUG_PRINT("enter", ("sd: %d  buf: 0x%lx  size: %u", vio->sd, (long) buf,
                        (uint) size));
   /* Ensure nobody uses vio_read_buff and vio_read simultaneously */
   DBUG_ASSERT(vio->read_end == vio->read_pos);
 #ifdef __WIN__
   r = recv(vio->sd, buf, size,0);
 #else
   errno=0;                  /* For linux */
   r = read(vio->sd, buf, size);
 #endif /* __WIN__ */
 #ifndef DBUG_OFF
   if (r == (size_t) -1)
   {
     DBUG_PRINT("vio_error", ("Got error %d during read",errno));
   }
 #endif /* DBUG_OFF */
   DBUG_PRINT("exit", ("%ld", (long) r));
   DBUG_RETURN(r);
 }
References DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, errno, read, st_vio::read_end, st_vio::read_pos, and st_vio::sd.
Referenced by vio_read_buff().
vio_read_buff()
size_t vio_read_buff (Vio * vio, uchar * buf, size_t size)
Definition at line 62 of file viosocket.c.
 {
   size_t rc;
 #define VIO_UNBUFFERED_READ_MIN_SIZE 2048
   DBUG_ENTER("vio_read_buff");
   DBUG_PRINT("enter", ("sd: %d  buf: 0x%lx  size: %u", vio->sd, (long) buf,
                        (uint) size));
   if (vio->read_pos < vio->read_end)
   {
     rc= min((size_t) (vio->read_end - vio->read_pos), size);
     memcpy(buf, vio->read_pos, rc);
     vio->read_pos+= rc;
     /*
       Do not try to read from the socket now even if rc < size:
       vio_read can return -1 due to an error or non-blocking mode, and
       the safest way to handle it is to move to a separate branch.
     */
   }
   else if (size < VIO_UNBUFFERED_READ_MIN_SIZE)
   {
     rc= vio_read(vio, (uchar*) vio->read_buffer, VIO_READ_BUFFER_SIZE);
     if (rc != 0 && rc != (size_t) -1)
     {
       if (rc > size)
       {
         vio->read_pos= vio->read_buffer + size;
         vio->read_end= vio->read_buffer + rc;
         rc= size;
       }
       memcpy(buf, vio->read_buffer, rc);
     }
   }
   else
     rc= vio_read(vio, buf, size);
   DBUG_RETURN(rc);
 #undef VIO_UNBUFFERED_READ_MIN_SIZE
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, memcpy, min, st_vio::read_buffer, st_vio::read_end, st_vio::read_pos, st_vio::sd, vio_read(), VIO_READ_BUFFER_SIZE, and VIO_UNBUFFERED_READ_MIN_SIZE.
Referenced by vio_init().
vio_should_retry()
my_bool vio_should_retry (Vio * vio)
Definition at line 247 of file viosocket.c.
 {
   int en = socket_errno;
   /*
     man 2 read write
       EAGAIN or EWOULDBLOCK when a socket is a non-blocking mode means
       that the read/write would block.
     man 7 socket
       EAGAIN or EWOULDBLOCK when a socket is in a blocking mode means
       that the corresponding receiving or sending timeout was reached.
   */
   return  en == SOCKET_EINTR ||
           (!vio_is_blocking(vio) &&
             (en == SOCKET_EAGAIN || en == SOCKET_EWOULDBLOCK));
 }
References SOCKET_EAGAIN, SOCKET_EINTR, socket_errno, SOCKET_EWOULDBLOCK, and vio_is_blocking().
vio_timeout()
void vio_timeout (Vio * vio, uint which, uint timeout)
Definition at line 680 of file viosocket.c.
 {
 #if defined(SO_SNDTIMEO) && defined(SO_RCVTIMEO)
   int r;
   DBUG_ENTER("vio_timeout");
   {
 #ifdef __WIN__
   /* Windows expects time in milliseconds as int */
   int wait_timeout= (int) timeout * 1000;
 #else
   /* POSIX specifies time as struct timeval. */
   struct timeval wait_timeout;
   wait_timeout.tv_sec= timeout;
   wait_timeout.tv_usec= 0;
 #endif
   r= setsockopt(vio->sd, SOL_SOCKET, which ? SO_SNDTIMEO : SO_RCVTIMEO,
                 IF_WIN((const char*), (const void*))&wait_timeout,
                 sizeof(wait_timeout));
   }
   if (r != 0)
     DBUG_PRINT("error", ("setsockopt failed: %d, errno: %d", r, socket_errno));
   DBUG_VOID_RETURN;
 #else
 /*
   Platforms not suporting setting of socket timeout should either use
   thr_alarm or just run without read/write timeout(s)
 */
 #endif
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, IF_WIN, st_vio::sd, and socket_errno.
vio_type()
enum enum_vio_type vio_type (Vio * vio)
Definition at line 301 of file viosocket.c.
 {
   return vio->type;
 }
vio_was_interrupted()
my_bool vio_was_interrupted (Vio *vio __attribute__(unused))
Definition at line 265 of file viosocket.c.
 {
   int en= socket_errno;
   return (en == SOCKET_EAGAIN || en == SOCKET_EINTR ||
       en == SOCKET_EWOULDBLOCK || en == SOCKET_ETIMEDOUT);
 }
References SOCKET_EAGAIN, SOCKET_EINTR, socket_errno, SOCKET_ETIMEDOUT, and SOCKET_EWOULDBLOCK.
vio_write()
size_t vio_write (Vio * vio, const uchar * buf, size_t size)
Definition at line 106 of file viosocket.c.
 {
   size_t r;
   DBUG_ENTER("vio_write");
   DBUG_PRINT("enter", ("sd: %d  buf: 0x%lx  size: %u", vio->sd, (long) buf,
                        (uint) size));
 #ifdef __WIN__
   r = send(vio->sd, buf, size,0);
 #else
   r = write(vio->sd, buf, size);
 #endif /* __WIN__ */
 #ifndef DBUG_OFF
   if (r == (size_t) -1)
   {
     DBUG_PRINT("vio_error", ("Got error on write: %d",socket_errno));
   }
 #endif /* DBUG_OFF */
   DBUG_PRINT("exit", ("%u", (uint) r));
   DBUG_RETURN(r);
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, st_vio::sd, socket_errno, and write.