Azerotcore-wotlk: npc_hor_leader_second Class Reference
npc_hor_leader_second Class Reference
Classes
struct npc_hor_leader_secondAI
Public Member Functions
npc_hor_leader_second ()
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 1615 of file halls_of_reflection.cpp.
Constructor & Destructor Documentation
npc_hor_leader_second()
npc_hor_leader_second::npc_hor_leader_second () inline
Definition at line 1618 of file halls_of_reflection.cpp.
 : CreatureScript("npc_hor_leader_second") { }
Member Function Documentation
GetAI()
CreatureAI* npc_hor_leader_second::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 1638 of file halls_of_reflection.cpp.
     {
         return GetHallsOfReflectionAI<npc_hor_leader_secondAI>(creature);
     }
OnGossipSelect()
bool npc_hor_leader_second::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32) inline override virtual
Reimplemented from CreatureScript.
Definition at line 1620 of file halls_of_reflection.cpp.
     {
         if (!creature->HasFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP))
             return true;
         ClearGossipMenuFor(player);
         if (InstanceScript* pInstance = creature->GetInstanceScript())
             if (!pInstance->GetData(DATA_LICH_KING))
             {
                 creature->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP | UNIT_NPC_FLAG_QUESTGIVER);
                 creature->AI()->DoAction(ACTION_START_LK_FIGHT_REAL);
                 return true;
             }
         return true;
     }
References ACTION_START_LK_FIGHT_REAL, Creature::AI(), ClearGossipMenuFor(), DATA_LICH_KING, UnitAI::DoAction(), WorldObject::GetInstanceScript(), Object::HasFlag(), Object::RemoveFlag(), UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAG_QUESTGIVER, and UNIT_NPC_FLAGS.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/halls_of_reflection.cpp