Azerotcore-wotlk: boss_sapphiron::boss_sapphironAI Struct Reference
boss_sapphiron::boss_sapphironAI Struct Reference
Public Member Functions
boss_sapphironAI (Creature *c)
void InitializeAI () override
bool IsInRoom ()
void Reset () override
void EnterCombatSelfFunction ()
void EnterCombat (Unit *who) override
void JustDied (Unit *killer) override
void DoAction (int32 param) override
void MovementInform (uint32 type, uint32 id) override
void SpellHitTarget (Unit *target, const SpellInfo *spellInfo) override
bool IsValidExplosionTarget (WorldObject *target)
void KilledUnit (Unit *who) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SpellHit (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
InstanceScript * pInstance
uint8 iceboltCount {}
uint32 spawnTimer {}
GuidList blockList
ObjectGuid currentTarget
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 91 of file boss_sapphiron.cpp.
Constructor & Destructor Documentation
boss_sapphironAI()
boss_sapphiron::boss_sapphironAI::boss_sapphironAI (Creature * c) inline explicit
Definition at line 93 of file boss_sapphiron.cpp.
                                                : BossAI(c, BOSS_SAPPHIRON)
         {
             pInstance = me->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), ScriptedAI::me, and pInstance.
Member Function Documentation
DoAction()
void boss_sapphiron::boss_sapphironAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 181 of file boss_sapphiron.cpp.
         {
             if (param == ACTION_SAPPHIRON_BIRTH)
             {
                 spawnTimer = 1;
             }
         }
References ACTION_SAPPHIRON_BIRTH, and spawnTimer.
EnterCombat()
void boss_sapphiron::boss_sapphironAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from BossAI.
Definition at line 161 of file boss_sapphiron.cpp.
         {
             BossAI::EnterCombat(who);
             EnterCombatSelfFunction();
             me->CastSpell(me, RAID_MODE(SPELL_FROST_AURA_10, SPELL_FROST_AURA_25), true);
             events.ScheduleEvent(EVENT_BERSERK, 900000);
             events.ScheduleEvent(EVENT_CLEAVE, 5000);
             events.ScheduleEvent(EVENT_TAIL_SWEEP, 10000);
             events.ScheduleEvent(EVENT_LIFE_DRAIN, 17000);
             events.ScheduleEvent(EVENT_BLIZZARD, 17000);
             events.ScheduleEvent(EVENT_FLIGHT_START, 45000);
             events.ScheduleEvent(EVENT_HUNDRED_CLUB, 5000);
         }
References Unit::CastSpell(), BossAI::EnterCombat(), EnterCombatSelfFunction(), EVENT_BERSERK, EVENT_BLIZZARD, EVENT_CLEAVE, EVENT_FLIGHT_START, EVENT_HUNDRED_CLUB, EVENT_LIFE_DRAIN, EVENT_TAIL_SWEEP, ScriptedAI::me, ScriptedAI::RAID_MODE(), SPELL_FROST_AURA_10, and SPELL_FROST_AURA_25.
EnterCombatSelfFunction()
void boss_sapphiron::boss_sapphironAI::EnterCombatSelfFunction () inline
Definition at line 138 of file boss_sapphiron.cpp.
         {
             Map::PlayerList const& PlList = me->GetMap()->GetPlayers();
             if (PlList.isEmpty())
                 return;
             for (const auto& i : PlList)
             {
                 if (Player* player = i.GetSource())
                 {
                     if (player->IsGameMaster())
                         continue;
                     if (player->IsAlive() && me->GetDistance(player) < 80.0f)
                     {
                         me->SetInCombatWith(player);
                         player->SetInCombatWith(me);
                         me->AddThreat(player, 0.0f);
                     }
                 }
             }
         }
References Unit::AddThreat(), WorldObject::GetDistance(), WorldObject::GetMap(), Map::GetPlayers(), LinkedListHead::isEmpty(), ScriptedAI::me, and Unit::SetInCombatWith().
Referenced by EnterCombat().
InitializeAI()
void boss_sapphiron::boss_sapphironAI::InitializeAI () inline override virtual
Reimplemented from UnitAI.
Definition at line 105 of file boss_sapphiron.cpp.
         {
             me->SummonGameObject(GO_SAPPHIRON_BIRTH, me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), 0, 0, 0, 0, 0, 0);
             me->SetVisible(false);
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
             me->SetReactState(REACT_PASSIVE);
             ScriptedAI::InitializeAI();
         }
References Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GO_SAPPHIRON_BIRTH, UnitAI::InitializeAI(), ScriptedAI::me, REACT_PASSIVE, Object::SetFlag(), Creature::SetReactState(), Unit::SetVisible(), WorldObject::SummonGameObject(), UNIT_FIELD_FLAGS, and UNIT_FLAG_NON_ATTACKABLE.
IsInRoom()
bool boss_sapphiron::boss_sapphironAI::IsInRoom () inline
Definition at line 114 of file boss_sapphiron.cpp.
         {
             if (me->GetExactDist(3523.5f, -5235.3f, 137.6f) > 100.0f)
             {
                 EnterEvadeMode();
                 return false;
             }
             return true;
         }
References CreatureAI::EnterEvadeMode(), Position::GetExactDist(), and ScriptedAI::me.
Referenced by UpdateAI().
IsValidExplosionTarget()
bool boss_sapphiron::boss_sapphironAI::IsValidExplosionTarget (WorldObject * target) inline
Definition at line 205 of file boss_sapphiron.cpp.
         {
             for (ObjectGuid const& guid : blockList)
             {
                 if (target->GetGUID() == guid)
                     return false;
                 if (Unit* block = ObjectAccessor::GetUnit(*me, guid))
                 {
                     if (block->IsInBetween(me, target, 2.0f) && block->IsWithinDist(target, 10.0f))
                         return false;
                 }
             }
             return true;
         }
References blockList, Object::GetGUID(), ObjectAccessor::GetUnit(), and ScriptedAI::me.
JustDied()
void boss_sapphiron::boss_sapphironAI::JustDied (Unit * killer) inline override virtual
Reimplemented from BossAI.
Definition at line 175 of file boss_sapphiron.cpp.
         {
             BossAI::JustDied(killer);
             me->CastSpell(me, SPELL_SAPPHIRON_DIES, true);
         }
References Unit::CastSpell(), BossAI::JustDied(), ScriptedAI::me, and SPELL_SAPPHIRON_DIES.
KilledUnit()
void boss_sapphiron::boss_sapphironAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 221 of file boss_sapphiron.cpp.
         {
             if (who->GetTypeId() == TYPEID_PLAYER && pInstance)
             {
                 pInstance->SetData(DATA_IMMORTAL_FAIL, 0);
             }
         }
References DATA_IMMORTAL_FAIL, Object::GetTypeId(), pInstance, ZoneScript::SetData(), and TYPEID_PLAYER.
MovementInform()
void boss_sapphiron::boss_sapphironAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 189 of file boss_sapphiron.cpp.
         {
             if (type == POINT_MOTION_TYPE && id == POINT_CENTER)
             {
                 events.ScheduleEvent(EVENT_FLIGHT_LIFTOFF, 500);
             }
         }
References EVENT_FLIGHT_LIFTOFF, POINT_CENTER, and POINT_MOTION_TYPE.
Reset()
void boss_sapphiron::boss_sapphironAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 124 of file boss_sapphiron.cpp.
         {
             BossAI::Reset();
             if (me->IsVisible())
             {
                 me->SetReactState(REACT_AGGRESSIVE);
             }
             events.Reset();
             iceboltCount = 0;
             spawnTimer = 0;
             currentTarget.Clear();
             blockList.clear();
         }
References blockList, ObjectGuid::Clear(), currentTarget, iceboltCount, Unit::IsVisible(), ScriptedAI::me, REACT_AGGRESSIVE, BossAI::Reset(), Creature::SetReactState(), and spawnTimer.
SpellHitTarget()
void boss_sapphiron::boss_sapphironAI::SpellHitTarget (Unit * target, const SpellInfo * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 197 of file boss_sapphiron.cpp.
         {
             if (spellInfo->Id == SPELL_ICEBOLT_CAST)
             {
                 me->CastSpell(target, SPELL_ICEBOLT_TRIGGER, true);
             }
         }
References Unit::CastSpell(), SpellInfo::Id, ScriptedAI::me, SPELL_ICEBOLT_CAST, and SPELL_ICEBOLT_TRIGGER.
UpdateAI()
void boss_sapphiron::boss_sapphironAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 229 of file boss_sapphiron.cpp.
         {
             if (spawnTimer)
             {
                 spawnTimer += diff;
                 if (spawnTimer >= 21500)
                 {
                     me->SetVisible(true);
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                     me->SetReactState(REACT_AGGRESSIVE);
                     spawnTimer = 0;
                 }
                 return;
             }
             if (!IsInRoom())
                 return;
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_BERSERK:
                     Talk(EMOTE_ENRAGE);
                     me->CastSpell(me, SPELL_BERSERK, true);
                     return;
                 case EVENT_CLEAVE:
                     me->CastSpell(me->GetVictim(), SPELL_CLEAVE, false);
                     events.RepeatEvent(10000);
                     return;
                 case EVENT_TAIL_SWEEP:
                     me->CastSpell(me, RAID_MODE(SPELL_TAIL_SWEEP_10, SPELL_TAIL_SWEEP_25), false);
                     events.RepeatEvent(10000);
                     return;
                 case EVENT_LIFE_DRAIN:
                     me->CastCustomSpell(RAID_MODE(SPELL_LIFE_DRAIN_10, SPELL_LIFE_DRAIN_25), SPELLVALUE_MAX_TARGETS, RAID_MODE(2, 5), me, false);
                     events.RepeatEvent(24000);
                     return;
                 case EVENT_BLIZZARD:
                     {
                         Creature* cr;
                         if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 40.0f, true))
{
                             cr = me->SummonCreature(NPC_BLIZZARD, *target, TEMPSUMMON_TIMED_DESPAWN, 16000);
                         }
                         else
{
                             cr = me->SummonCreature(NPC_BLIZZARD, *me, TEMPSUMMON_TIMED_DESPAWN, 16000);
                         }
                         if (cr)
{
                             cr->GetMotionMaster()->MoveRandom(40);
                         }
                         events.RepeatEvent(RAID_MODE(8000, 6500));
                         return;
                     }
                 case EVENT_FLIGHT_START:
                     if (me->HealthBelowPct(11))
                     {
                         return;
                     }
                     events.RepeatEvent(45000);
                     events.DelayEvents(35000);
                     me->SetReactState(REACT_PASSIVE);
                     me->AttackStop();
                     float x, y, z, o;
                     me->GetHomePosition(x, y, z, o);
                     me->GetMotionMaster()->MovePoint(POINT_CENTER, x, y, z);
                     return;
                 case EVENT_FLIGHT_LIFTOFF:
                     Talk(EMOTE_AIR_PHASE);
                     me->GetMotionMaster()->MoveIdle();
                     me->SendMeleeAttackStop(me->GetVictim());
                     me->HandleEmoteCommand(EMOTE_ONESHOT_LIFTOFF);
                     me->SetDisableGravity(true);
                     currentTarget.Clear();
                     events.ScheduleEvent(EVENT_FLIGHT_ICEBOLT, 3000);
                     iceboltCount = RAID_MODE(2, 3);
                     return;
                 case EVENT_FLIGHT_ICEBOLT:
                     {
                         if (currentTarget)
{
                             if (Unit* target = ObjectAccessor::GetUnit(*me, currentTarget))
{
                                 me->SummonGameObject(GO_ICE_BLOCK, target->GetPositionX(), target->GetPositionY(), target->GetPositionZ(), target->GetOrientation(), 0.0f, 0.0f, 0.0f, 0.0f, 0);
                             }
                         }
                         std::vector<Unit*> targets;
                         auto i = me->getThreatMgr().getThreatList().begin();
                         for (; i != me->getThreatMgr().getThreatList().end(); ++i)
{
                             if ((*i)->getTarget()->GetTypeId() == TYPEID_PLAYER)
{
                                 bool inList = false;
                                 if (!blockList.empty())
{
                                     for (GuidList::const_iterator itr = blockList.begin(); itr != blockList.end(); ++itr)
{
                                         if ((*i)->getTarget()->GetGUID() == *itr)
{
                                             inList = true;
                                             break;
                                         }
                                     }
                                 }
                                 if (!inList)
{
                                     targets.push_back((*i)->getTarget());
                                 }
                             }
                         }
                         if (!targets.empty() && iceboltCount)
{
                             auto itr = targets.begin();
                             advance(itr, urand(0, targets.size() - 1));
                             me->CastSpell(*itr, SPELL_ICEBOLT_CAST, false);
                             blockList.push_back((*itr)->GetGUID());
                             currentTarget = (*itr)->GetGUID();
                             --iceboltCount;
                             events.ScheduleEvent(EVENT_FLIGHT_ICEBOLT, (me->GetExactDist(*itr) / 13.0f)*IN_MILLISECONDS);
                         }
                         else
{
                             events.ScheduleEvent(EVENT_FLIGHT_BREATH, 1000);
                         }
                         return;
                     }
                 case EVENT_FLIGHT_BREATH:
                     currentTarget.Clear();
                     Talk(EMOTE_BREATH);
                     me->CastSpell(me, SPELL_FROST_MISSILE, false);
                     events.ScheduleEvent(EVENT_FLIGHT_SPELL_EXPLOSION, 8500);
                     return;
                 case EVENT_FLIGHT_SPELL_EXPLOSION:
                     me->CastSpell(me, SPELL_FROST_EXPLOSION, true);
                     events.ScheduleEvent(EVENT_FLIGHT_START_LAND, 3000);
                     return;
                 case EVENT_FLIGHT_START_LAND:
                     if (!blockList.empty())
                     {
                         for (GuidList::const_iterator itr = blockList.begin(); itr != blockList.end(); ++itr)
{
                             if (Unit* block = ObjectAccessor::GetUnit(*me, *itr))
{
                                 block->RemoveAurasDueToSpell(SPELL_ICEBOLT_TRIGGER);
                             }
                         }
                     }
                     blockList.clear();
                     me->RemoveAllGameObjects();
                     events.ScheduleEvent(EVENT_LAND, 1000);
                     return;
                 case EVENT_LAND:
                     me->HandleEmoteCommand(EMOTE_ONESHOT_LAND);
                     me->SetDisableGravity(false);
                     events.ScheduleEvent(EVENT_GROUND, 1500);
                     return;
                 case EVENT_GROUND:
                     Talk(EMOTE_GROUND_PHASE);
                     me->SetReactState(REACT_AGGRESSIVE);
                     me->SetInCombatWithZone();
                     return;
                 case EVENT_HUNDRED_CLUB:
                     {
                         Map::PlayerList const& pList = me->GetMap()->GetPlayers();
                         for (const auto& itr : pList)
{
                             if (itr.GetSource()->GetResistance(SPELL_SCHOOL_FROST) > 100 && pInstance)
{
                                 pInstance->SetData(DATA_HUNDRED_CLUB, 0);
                                 return;
                             }
                         }
                         events.RepeatEvent(5000);
                         return;
                     }
             }
             DoMeleeAttackIfReady();
         }
References Unit::AttackStop(), blockList, Unit::CastCustomSpell(), Unit::CastSpell(), ObjectGuid::Clear(), currentTarget, DATA_HUNDRED_CLUB, UnitAI::DoMeleeAttackIfReady(), EMOTE_AIR_PHASE, EMOTE_BREATH, EMOTE_ENRAGE, EMOTE_GROUND_PHASE, EMOTE_ONESHOT_LAND, EMOTE_ONESHOT_LIFTOFF, EVENT_BERSERK, EVENT_BLIZZARD, EVENT_CLEAVE, EVENT_FLIGHT_BREATH, EVENT_FLIGHT_ICEBOLT, EVENT_FLIGHT_LIFTOFF, EVENT_FLIGHT_SPELL_EXPLOSION, EVENT_FLIGHT_START, EVENT_FLIGHT_START_LAND, EVENT_GROUND, EVENT_HUNDRED_CLUB, EVENT_LAND, EVENT_LIFE_DRAIN, EVENT_TAIL_SWEEP, Position::GetExactDist(), Creature::GetHomePosition(), WorldObject::GetMap(), Unit::GetMotionMaster(), Map::GetPlayers(), ThreatMgr::getThreatList(), Unit::getThreatMgr(), ObjectAccessor::GetUnit(), Unit::GetVictim(), GO_ICE_BLOCK, Unit::HandleEmoteCommand(), Unit::HasUnitState(), Unit::HealthBelowPct(), iceboltCount, IN_MILLISECONDS, IsInRoom(), ScriptedAI::me, MotionMaster::MoveIdle(), MotionMaster::MovePoint(), MotionMaster::MoveRandom(), NPC_BLIZZARD, pInstance, POINT_CENTER, ScriptedAI::RAID_MODE(), REACT_AGGRESSIVE, REACT_PASSIVE, Unit::RemoveAllGameObjects(), Object::RemoveFlag(), SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Unit::SendMeleeAttackStop(), ZoneScript::SetData(), Creature::SetDisableGravity(), Creature::SetInCombatWithZone(), Creature::SetReactState(), Unit::SetVisible(), spawnTimer, SPELL_BERSERK, SPELL_CLEAVE, SPELL_FROST_EXPLOSION, SPELL_FROST_MISSILE, SPELL_ICEBOLT_CAST, SPELL_ICEBOLT_TRIGGER, SPELL_LIFE_DRAIN_10, SPELL_LIFE_DRAIN_25, SPELL_SCHOOL_FROST, SPELL_TAIL_SWEEP_10, SPELL_TAIL_SWEEP_25, SPELLVALUE_MAX_TARGETS, WorldObject::SummonCreature(), WorldObject::SummonGameObject(), CreatureAI::Talk(), TEMPSUMMON_TIMED_DESPAWN, TYPEID_PLAYER, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
blockList
GuidList boss_sapphiron::boss_sapphironAI::blockList
Definition at line 102 of file boss_sapphiron.cpp.
Referenced by IsValidExplosionTarget(), Reset(), and UpdateAI().
currentTarget
ObjectGuid boss_sapphiron::boss_sapphironAI::currentTarget
Definition at line 103 of file boss_sapphiron.cpp.
Referenced by Reset(), and UpdateAI().
events
EventMap boss_sapphiron::boss_sapphironAI::events
Definition at line 98 of file boss_sapphiron.cpp.
iceboltCount
uint8 boss_sapphiron::boss_sapphironAI::iceboltCount {}
Definition at line 100 of file boss_sapphiron.cpp.
Referenced by Reset(), and UpdateAI().
pInstance
InstanceScript* boss_sapphiron::boss_sapphironAI::pInstance
Definition at line 99 of file boss_sapphiron.cpp.
Referenced by boss_sapphironAI(), KilledUnit(), and UpdateAI().
spawnTimer
uint32 boss_sapphiron::boss_sapphironAI::spawnTimer {}
Definition at line 101 of file boss_sapphiron.cpp.
Referenced by DoAction(), Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Naxxramas/boss_sapphiron.cpp