Azerotcore-wotlk: instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript Struct Reference
instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript Struct Reference
Public Member Functions
instance_serpentshrine_cavern_InstanceMapScript (Map *map)
void Initialize () override
bool SetBossState (uint32 type, EncounterState state) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
void OnCreatureCreate (Creature *creature) override
ObjectGuid GetGuidData (uint32 identifier) const override
void SetData (uint32 type, uint32) override
uint32 GetData (uint32 type) const override
std::string GetSaveData () override
void Load (char const *str) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void CreatureLooted (Creature *, LootType)
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureRemove (Creature *creature) override
ObjectGuid GetObjectGuid (uint32 type) const
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual void ProcessEvent (WorldObject *, uint32)
Private Attributes
ObjectGuid LadyVashjGUID
ObjectGuid ShieldGeneratorGUID [4]
ObjectGuid LurkerBelowGUID
ObjectGuid LeotherasTheBlindGUID
int32 AliveKeepersCount
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Definition at line 37 of file instance_serpent_shrine.cpp.
Constructor & Destructor Documentation
instance_serpentshrine_cavern_InstanceMapScript()
instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::instance_serpentshrine_cavern_InstanceMapScript (Map * map) inline
Definition at line 39 of file instance_serpent_shrine.cpp.
                                                                   : InstanceScript(map)
         {
         }
Member Function Documentation
GetData()
uint32 instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
Definition at line 168 of file instance_serpent_shrine.cpp.
         {
             if (type == DATA_ALIVE_KEEPERS)
                 return AliveKeepersCount;
             return 0;
         }
References AliveKeepersCount, and DATA_ALIVE_KEEPERS.
GetGuidData()
ObjectGuid instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::GetGuidData (uint32 identifier) const inline override virtual
Reimplemented from InstanceScript.
Definition at line 127 of file instance_serpent_shrine.cpp.
         {
             switch (identifier)
             {
                 case NPC_THE_LURKER_BELOW:
                     return LurkerBelowGUID;
                 case NPC_LEOTHERAS_THE_BLIND:
                     return LeotherasTheBlindGUID;
                 case NPC_LADY_VASHJ:
                     return LadyVashjGUID;
             }
             return ObjectGuid::Empty;
         }
References ObjectGuid::Empty, LadyVashjGUID, LeotherasTheBlindGUID, LurkerBelowGUID, NPC_LADY_VASHJ, NPC_LEOTHERAS_THE_BLIND, and NPC_THE_LURKER_BELOW.
GetSaveData()
std::string instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
Definition at line 176 of file instance_serpent_shrine.cpp.
         {
             OUT_SAVE_INST_DATA;
             std::ostringstream saveStream;
             saveStream << "S C " << GetBossSaveData();
             OUT_SAVE_INST_DATA_COMPLETE;
             return saveStream.str();
         }
References InstanceScript::GetBossSaveData(), OUT_SAVE_INST_DATA, and OUT_SAVE_INST_DATA_COMPLETE.
Initialize()
void instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::Initialize (void) inline override virtual
Reimplemented from InstanceScript.
Definition at line 43 of file instance_serpent_shrine.cpp.
         {
             SetBossNumber(MAX_ENCOUNTERS);
             LoadDoorData(doorData);
             AliveKeepersCount = 0;
         }
References AliveKeepersCount, doorData, InstanceScript::LoadDoorData(), MAX_ENCOUNTERS, and InstanceScript::SetBossNumber().
Load()
void instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::Load (char const * str) inline override virtual
Reimplemented from InstanceScript.
Definition at line 187 of file instance_serpent_shrine.cpp.
         {
             if (!str)
             {
                 OUT_LOAD_INST_DATA_FAIL;
                 return;
             }
             OUT_LOAD_INST_DATA(str);
             char dataHead1, dataHead2;
             std::istringstream loadStream(str);
             loadStream >> dataHead1 >> dataHead2;
             if (dataHead1 == 'S' && dataHead2 == 'C')
             {
                 for (uint8 i = 0; i < MAX_ENCOUNTERS; ++i)
                 {
                     uint32 tmpState;
                     loadStream >> tmpState;
                     if (tmpState == IN_PROGRESS || tmpState > SPECIAL)
                         tmpState = NOT_STARTED;
                     SetBossState(i, EncounterState(tmpState));
                 }
             }
             else
                 OUT_LOAD_INST_DATA_FAIL;
             OUT_LOAD_INST_DATA_COMPLETE;
         }
References IN_PROGRESS, MAX_ENCOUNTERS, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, OUT_LOAD_INST_DATA_FAIL, SetBossState(), and SPECIAL.
OnCreatureCreate()
void instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 96 of file instance_serpent_shrine.cpp.
         {
             switch (creature->GetEntry())
             {
                 case NPC_COILFANG_SHATTERER:
                 case NPC_COILFANG_PRIESTESS:
                     if (creature->GetPositionX() > -110.0f && creature->GetPositionX() < 155.0f && creature->GetPositionY() > -610.0f && creature->GetPositionY() < -280.0f)
                         AliveKeepersCount += creature->IsAlive() ? 0 : -1; // retarded SmartAI calls JUST_RESPAWNED in AIInit...
                     break;
                 case NPC_THE_LURKER_BELOW:
                     LurkerBelowGUID = creature->GetGUID();
                     break;
                 case NPC_LEOTHERAS_THE_BLIND:
                     LeotherasTheBlindGUID = creature->GetGUID();
                     break;
                 case NPC_CYCLONE_KARATHRESS:
                     creature->GetMotionMaster()->MoveRandom(50.0f);
                     break;
                 case NPC_LADY_VASHJ:
                     LadyVashjGUID = creature->GetGUID();
                     break;
                 case NPC_ENCHANTED_ELEMENTAL:
                 case NPC_COILFANG_ELITE:
                 case NPC_COILFANG_STRIDER:
                 case NPC_TAINTED_ELEMENTAL:
                     if (Creature* vashj = instance->GetCreature(LadyVashjGUID))
                         vashj->AI()->JustSummoned(creature);
                     break;
             }
         }
References AliveKeepersCount, Map::GetCreature(), Object::GetEntry(), Object::GetGUID(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), InstanceScript::instance, Unit::IsAlive(), LadyVashjGUID, LeotherasTheBlindGUID, LurkerBelowGUID, MotionMaster::MoveRandom(), NPC_COILFANG_ELITE, NPC_COILFANG_PRIESTESS, NPC_COILFANG_SHATTERER, NPC_COILFANG_STRIDER, NPC_CYCLONE_KARATHRESS, NPC_ENCHANTED_ELEMENTAL, NPC_LADY_VASHJ, NPC_LEOTHERAS_THE_BLIND, NPC_TAINTED_ELEMENTAL, and NPC_THE_LURKER_BELOW.
OnGameObjectCreate()
void instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
Definition at line 64 of file instance_serpent_shrine.cpp.
         {
             switch (go->GetEntry())
             {
                 case GO_LADY_VASHJ_BRIDGE_CONSOLE:
                 case GO_COILFANG_BRIDGE1:
                 case GO_COILFANG_BRIDGE2:
                 case GO_COILFANG_BRIDGE3:
                     AddDoor(go, true);
                     break;
                 case GO_SHIELD_GENERATOR1:
                 case GO_SHIELD_GENERATOR2:
                 case GO_SHIELD_GENERATOR3:
                 case GO_SHIELD_GENERATOR4:
                     ShieldGeneratorGUID[go->GetEntry() - GO_SHIELD_GENERATOR1] = go->GetGUID();
                     break;
             }
         }
References InstanceScript::AddDoor(), Object::GetEntry(), Object::GetGUID(), GO_COILFANG_BRIDGE1, GO_COILFANG_BRIDGE2, GO_COILFANG_BRIDGE3, GO_LADY_VASHJ_BRIDGE_CONSOLE, GO_SHIELD_GENERATOR1, GO_SHIELD_GENERATOR2, GO_SHIELD_GENERATOR3, GO_SHIELD_GENERATOR4, and ShieldGeneratorGUID.
OnGameObjectRemove()
void instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::OnGameObjectRemove (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
Definition at line 83 of file instance_serpent_shrine.cpp.
         {
             switch (go->GetEntry())
             {
                 case GO_LADY_VASHJ_BRIDGE_CONSOLE:
                 case GO_COILFANG_BRIDGE1:
                 case GO_COILFANG_BRIDGE2:
                 case GO_COILFANG_BRIDGE3:
                     AddDoor(go, false);
                     break;
             }
         }
References InstanceScript::AddDoor(), Object::GetEntry(), GO_COILFANG_BRIDGE1, GO_COILFANG_BRIDGE2, GO_COILFANG_BRIDGE3, and GO_LADY_VASHJ_BRIDGE_CONSOLE.
SetBossState()
bool instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::SetBossState (uint32 type, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
Definition at line 51 of file instance_serpent_shrine.cpp.
         {
             if (!InstanceScript::SetBossState(type, state))
                 return false;
             if (type == DATA_LADY_VASHJ)
                 for (uint8 i = 0; i < 4; ++i)
                     if (GameObject* gobject = instance->GetGameObject(ShieldGeneratorGUID[i]))
                         gobject->SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
             return true;
         }
References DATA_LADY_VASHJ, GAMEOBJECT_FLAGS, Map::GetGameObject(), GO_FLAG_NOT_SELECTABLE, InstanceScript::instance, InstanceScript::SetBossState(), and ShieldGeneratorGUID.
Referenced by Load(), and SetData().
SetData()
void instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::SetData (uint32 type, uint32) inline override virtual
Reimplemented from ZoneScript.
Definition at line 142 of file instance_serpent_shrine.cpp.
         {
             switch (type)
             {
                 case DATA_PLATFORM_KEEPER_RESPAWNED:
                     ++AliveKeepersCount;
                     break;
                 case DATA_PLATFORM_KEEPER_DIED:
                     --AliveKeepersCount;
                     break;
                 case DATA_BRIDGE_ACTIVATED:
                     SetBossState(DATA_BRIDGE_EMERGED, NOT_STARTED);
                     SetBossState(DATA_BRIDGE_EMERGED, DONE);
                     break;
                 case DATA_ACTIVATE_SHIELD:
                     if (Creature* vashj = instance->GetCreature(LadyVashjGUID))
                         for (uint8 i = 0; i < 4; ++i)
                             if (GameObject* gobject = instance->GetGameObject(ShieldGeneratorGUID[i]))
{
                                 gobject->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                                 vashj->SummonTrigger(gobject->GetPositionX(), gobject->GetPositionY(), gobject->GetPositionZ(), 0.0f, 0);
                             }
                     break;
             }
         }
References AliveKeepersCount, DATA_ACTIVATE_SHIELD, DATA_BRIDGE_ACTIVATED, DATA_BRIDGE_EMERGED, DATA_PLATFORM_KEEPER_DIED, DATA_PLATFORM_KEEPER_RESPAWNED, DONE, GAMEOBJECT_FLAGS, Map::GetCreature(), Map::GetGameObject(), GO_FLAG_NOT_SELECTABLE, InstanceScript::instance, LadyVashjGUID, NOT_STARTED, SetBossState(), and ShieldGeneratorGUID.
Member Data Documentation
AliveKeepersCount
int32 instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::AliveKeepersCount private
Definition at line 224 of file instance_serpent_shrine.cpp.
Referenced by GetData(), Initialize(), OnCreatureCreate(), and SetData().
LadyVashjGUID
ObjectGuid instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::LadyVashjGUID private
Definition at line 220 of file instance_serpent_shrine.cpp.
Referenced by GetGuidData(), OnCreatureCreate(), and SetData().
LeotherasTheBlindGUID
ObjectGuid instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::LeotherasTheBlindGUID private
Definition at line 223 of file instance_serpent_shrine.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
LurkerBelowGUID
ObjectGuid instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::LurkerBelowGUID private
Definition at line 222 of file instance_serpent_shrine.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
ShieldGeneratorGUID
ObjectGuid instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::ShieldGeneratorGUID[4] private
Definition at line 221 of file instance_serpent_shrine.cpp.
Referenced by OnGameObjectCreate(), SetBossState(), and SetData().
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/instance_serpent_shrine.cpp