Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/bitmap.h File Reference
bitmap.h File Reference
#include "jemalloc/internal/arena_types.h"
#include "jemalloc/internal/bit_util.h"
#include "jemalloc/internal/sc.h"
Classes
struct bitmap_level_s
struct bitmap_info_s
Macros
#define LG_SIZEOF_BITMAP LG_SIZEOF_LONG
#define LG_BITMAP_MAXBITS LG_CEIL(SC_NSIZES)
#define BITMAP_MAXBITS (ZU(1) << LG_BITMAP_MAXBITS)
#define LG_BITMAP_GROUP_NBITS (LG_SIZEOF_BITMAP + 3)
#define BITMAP_GROUP_NBITS (1U << LG_BITMAP_GROUP_NBITS)
#define BITMAP_GROUP_NBITS_MASK (BITMAP_GROUP_NBITS-1)
#define BITMAP_BITS2GROUPS(nbits) (((nbits) + BITMAP_GROUP_NBITS_MASK) >> LG_BITMAP_GROUP_NBITS)
#define BITMAP_GROUPS_L0(nbits) BITMAP_BITS2GROUPS(nbits)
#define BITMAP_GROUPS_L1(nbits) BITMAP_BITS2GROUPS(BITMAP_BITS2GROUPS(nbits))
#define BITMAP_GROUPS_L2(nbits) BITMAP_BITS2GROUPS(BITMAP_BITS2GROUPS(BITMAP_BITS2GROUPS((nbits))))
#define BITMAP_GROUPS_L3(nbits)
#define BITMAP_GROUPS_L4(nbits)
#define BITMAP_GROUPS_1_LEVEL(nbits) BITMAP_GROUPS_L0(nbits)
#define BITMAP_GROUPS_2_LEVEL(nbits) (BITMAP_GROUPS_1_LEVEL(nbits) + BITMAP_GROUPS_L1(nbits))
#define BITMAP_GROUPS_3_LEVEL(nbits) (BITMAP_GROUPS_2_LEVEL(nbits) + BITMAP_GROUPS_L2(nbits))
#define BITMAP_GROUPS_4_LEVEL(nbits) (BITMAP_GROUPS_3_LEVEL(nbits) + BITMAP_GROUPS_L3(nbits))
#define BITMAP_GROUPS_5_LEVEL(nbits) (BITMAP_GROUPS_4_LEVEL(nbits) + BITMAP_GROUPS_L4(nbits))
#define BITMAP_GROUPS(nbits) BITMAP_BITS2GROUPS(nbits)
#define BITMAP_GROUPS_MAX BITMAP_BITS2GROUPS(BITMAP_MAXBITS)
#define BITMAP_INFO_INITIALIZER(nbits)
Typedefs
typedef unsigned long bitmap_t
typedef struct bitmap_level_s bitmap_level_t
typedef struct bitmap_info_s bitmap_info_t
Functions
void bitmap_info_init (bitmap_info_t *binfo, size_t nbits)
void bitmap_init (bitmap_t *bitmap, const bitmap_info_t *binfo, bool fill)
size_t bitmap_size (const bitmap_info_t *binfo)
static bool bitmap_full (bitmap_t *bitmap, const bitmap_info_t *binfo)
static bool bitmap_get (bitmap_t *bitmap, const bitmap_info_t *binfo, size_t bit)
static void bitmap_set (bitmap_t *bitmap, const bitmap_info_t *binfo, size_t bit)
static size_t bitmap_ffu (const bitmap_t *bitmap, const bitmap_info_t *binfo, size_t min_bit)
static size_t bitmap_sfu (bitmap_t *bitmap, const bitmap_info_t *binfo)
static void bitmap_unset (bitmap_t *bitmap, const bitmap_info_t *binfo, size_t bit)
Macro Definition Documentation
BITMAP_BITS2GROUPS
#define BITMAP_BITS2GROUPS (nbits) (((nbits) + BITMAP_GROUP_NBITS_MASK) >> LG_BITMAP_GROUP_NBITS)
Definition at line 36 of file bitmap.h.
BITMAP_GROUP_NBITS
#define BITMAP_GROUP_NBITS (1U << LG_BITMAP_GROUP_NBITS)
Definition at line 23 of file bitmap.h.
BITMAP_GROUP_NBITS_MASK
#define BITMAP_GROUP_NBITS_MASK (BITMAP_GROUP_NBITS-1)
Definition at line 24 of file bitmap.h.
BITMAP_GROUPS
#define BITMAP_GROUPS (nbits) BITMAP_BITS2GROUPS(nbits)
Definition at line 135 of file bitmap.h.
BITMAP_GROUPS_1_LEVEL
#define BITMAP_GROUPS_1_LEVEL (nbits) BITMAP_GROUPS_L0(nbits)
Definition at line 59 of file bitmap.h.
BITMAP_GROUPS_2_LEVEL
#define BITMAP_GROUPS_2_LEVEL (nbits) (BITMAP_GROUPS_1_LEVEL(nbits) + BITMAP_GROUPS_L1(nbits))
Definition at line 61 of file bitmap.h.
BITMAP_GROUPS_3_LEVEL
#define BITMAP_GROUPS_3_LEVEL (nbits) (BITMAP_GROUPS_2_LEVEL(nbits) + BITMAP_GROUPS_L2(nbits))
Definition at line 63 of file bitmap.h.
BITMAP_GROUPS_4_LEVEL
#define BITMAP_GROUPS_4_LEVEL (nbits) (BITMAP_GROUPS_3_LEVEL(nbits) + BITMAP_GROUPS_L3(nbits))
Definition at line 65 of file bitmap.h.
BITMAP_GROUPS_5_LEVEL
#define BITMAP_GROUPS_5_LEVEL (nbits) (BITMAP_GROUPS_4_LEVEL(nbits) + BITMAP_GROUPS_L4(nbits))
Definition at line 67 of file bitmap.h.
BITMAP_GROUPS_L0
#define BITMAP_GROUPS_L0 (nbits) BITMAP_BITS2GROUPS(nbits)
Definition at line 42 of file bitmap.h.
BITMAP_GROUPS_L1
#define BITMAP_GROUPS_L1 (nbits) BITMAP_BITS2GROUPS(BITMAP_BITS2GROUPS(nbits))
Definition at line 44 of file bitmap.h.
BITMAP_GROUPS_L2
#define BITMAP_GROUPS_L2 (nbits) BITMAP_BITS2GROUPS(BITMAP_BITS2GROUPS(BITMAP_BITS2GROUPS((nbits))))
Definition at line 46 of file bitmap.h.
BITMAP_GROUPS_L3
#define BITMAP_GROUPS_L3 (nbits)
Value:
    BITMAP_BITS2GROUPS(BITMAP_BITS2GROUPS(BITMAP_BITS2GROUPS(       \
    BITMAP_BITS2GROUPS((nbits)))))
Definition at line 48 of file bitmap.h.
BITMAP_GROUPS_L4
#define BITMAP_GROUPS_L4 (nbits)
Value:
    BITMAP_BITS2GROUPS(BITMAP_BITS2GROUPS(BITMAP_BITS2GROUPS(       \
    BITMAP_BITS2GROUPS(BITMAP_BITS2GROUPS((nbits))))))
Definition at line 51 of file bitmap.h.
BITMAP_GROUPS_MAX
#define BITMAP_GROUPS_MAX BITMAP_BITS2GROUPS(BITMAP_MAXBITS)
Definition at line 136 of file bitmap.h.
BITMAP_INFO_INITIALIZER
#define BITMAP_INFO_INITIALIZER (nbits)
Value:
    {               \
    /* nbits. */                            \
    nbits,                              \
    /* ngroups. */                          \
    BITMAP_BITS2GROUPS(nbits)                   \
}
Definition at line 138 of file bitmap.h.
BITMAP_MAXBITS
#define BITMAP_MAXBITS (ZU(1) << LG_BITMAP_MAXBITS)
Definition at line 19 of file bitmap.h.
LG_BITMAP_GROUP_NBITS
#define LG_BITMAP_GROUP_NBITS (LG_SIZEOF_BITMAP + 3)
Definition at line 22 of file bitmap.h.
LG_BITMAP_MAXBITS
#define LG_BITMAP_MAXBITS LG_CEIL(SC_NSIZES)
Definition at line 17 of file bitmap.h.
LG_SIZEOF_BITMAP
#define LG_SIZEOF_BITMAP LG_SIZEOF_LONG
Definition at line 9 of file bitmap.h.
Typedef Documentation
bitmap_info_t
typedef struct bitmap_info_s bitmap_info_t
bitmap_level_t
typedef struct bitmap_level_s bitmap_level_t
bitmap_t
typedef unsigned long bitmap_t
Definition at line 8 of file bitmap.h.
Function Documentation
bitmap_ffu()
static size_t bitmap_ffu (const bitmap_t * bitmap, const bitmap_info_t * binfo, size_t min_bit) inline static
Definition at line 242 of file bitmap.h.
{
     assert(min_bit < binfo->nbits);
 #ifdef BITMAP_USE_TREE
     size_t bit = 0;
     for (unsigned level = binfo->nlevels; level--;) {
         size_t lg_bits_per_group = (LG_BITMAP_GROUP_NBITS * (level +
             1));
         bitmap_t group = bitmap[binfo->levels[level].group_offset + (bit
             >> lg_bits_per_group)];
         unsigned group_nmask = (unsigned)(((min_bit > bit) ? (min_bit -
             bit) : 0) >> (lg_bits_per_group - LG_BITMAP_GROUP_NBITS));
         assert(group_nmask <= BITMAP_GROUP_NBITS);
         bitmap_t group_mask = ~((1LU << group_nmask) - 1);
         bitmap_t group_masked = group & group_mask;
         if (group_masked == 0LU) {
             if (group == 0LU) {
                 return binfo->nbits;
             }
             /*
              * min_bit was preceded by one or more unset bits in
              * this group, but there are no other unset bits in this
              * group.  Try again starting at the first bit of the
              * next sibling.  This will recurse at most once per
              * non-root level.
              */
             size_t sib_base = bit + (ZU(1) << lg_bits_per_group);
             assert(sib_base > min_bit);
             assert(sib_base > bit);
             if (sib_base >= binfo->nbits) {
                 return binfo->nbits;
             }
             return bitmap_ffu(bitmap, binfo, sib_base);
         }
         bit += ((size_t)(ffs_lu(group_masked) - 1)) <<
             (lg_bits_per_group - LG_BITMAP_GROUP_NBITS);
     }
     assert(bit >= min_bit);
     assert(bit < binfo->nbits);
     return bit;
 #else
     size_t i = min_bit >> LG_BITMAP_GROUP_NBITS;
     bitmap_t g = bitmap[i] & ~((1LU << (min_bit & BITMAP_GROUP_NBITS_MASK))
         - 1);
     size_t bit;
     do {
         bit = ffs_lu(g);
         if (bit != 0) {
             return (i << LG_BITMAP_GROUP_NBITS) + (bit - 1);
         }
         i++;
         g = bitmap[i];
     } while (i < binfo->ngroups);
     return binfo->nbits;
 #endif
 }
References assert(), BITMAP_GROUP_NBITS, BITMAP_GROUP_NBITS_MASK, ffs_lu(), LG_BITMAP_GROUP_NBITS, bitmap_info_s::nbits, and ZU.
Referenced by extents_first_fit_locked(), and extents_fit_alignment().
bitmap_full()
static bool bitmap_full (bitmap_t * bitmap, const bitmap_info_t * binfo) inline static
Definition at line 176 of file bitmap.h.
{
 #ifdef BITMAP_USE_TREE
     size_t rgoff = binfo->levels[binfo->nlevels].group_offset - 1;
     bitmap_t rg = bitmap[rgoff];
     /* The bitmap is full iff the root group is 0. */
     return (rg == 0);
 #else
     size_t i;
     for (i = 0; i < binfo->ngroups; i++) {
         if (bitmap[i] != 0) {
             return false;
         }
     }
     return true;
 #endif
 }
References bitmap_info_s::ngroups.
Referenced by arena_slab_reg_alloc(), arena_slab_reg_alloc_batch(), and bitmap_sfu().
bitmap_get()
static bool bitmap_get (bitmap_t * bitmap, const bitmap_info_t * binfo, size_t bit) inline static
Definition at line 195 of file bitmap.h.
{
     size_t goff;
     bitmap_t g;
     assert(bit < binfo->nbits);
     goff = bit >> LG_BITMAP_GROUP_NBITS;
     g = bitmap[goff];
     return !(g & (ZU(1) << (bit & BITMAP_GROUP_NBITS_MASK)));
 }
References assert(), BITMAP_GROUP_NBITS_MASK, LG_BITMAP_GROUP_NBITS, and ZU.
Referenced by arena_slab_reg_dalloc(), bitmap_set(), and bitmap_unset().
bitmap_info_init()
void bitmap_info_init (bitmap_info_t * binfo, size_t nbits)
Definition at line 86 of file bitmap.c.
{
     assert(nbits > 0);
     assert(nbits <= (ZU(1) << LG_BITMAP_MAXBITS));
     binfo->ngroups = BITMAP_BITS2GROUPS(nbits);
     binfo->nbits = nbits;
 }
References assert(), BITMAP_BITS2GROUPS, LG_BITMAP_MAXBITS, bitmap_info_s::nbits, bitmap_info_s::ngroups, and ZU.
bitmap_init()
void bitmap_init (bitmap_t * bitmap, const bitmap_info_t * binfo, bool fill)
Definition at line 100 of file bitmap.c.
{
     size_t extra;
     if (fill) {
         memset(bitmap, 0, bitmap_size(binfo));
         return;
     }
     memset(bitmap, 0xffU, bitmap_size(binfo));
     extra = (BITMAP_GROUP_NBITS - (binfo->nbits & BITMAP_GROUP_NBITS_MASK))
         & BITMAP_GROUP_NBITS_MASK;
     if (extra != 0) {
         bitmap[binfo->ngroups - 1] >>= extra;
     }
 }
References BITMAP_GROUP_NBITS, BITMAP_GROUP_NBITS_MASK, bitmap_size(), fill(), memset, bitmap_info_s::nbits, and bitmap_info_s::ngroups.
bitmap_set()
static void bitmap_set (bitmap_t * bitmap, const bitmap_info_t * binfo, size_t bit) inline static
Definition at line 206 of file bitmap.h.
{
     size_t goff;
     bitmap_t *gp;
     bitmap_t g;
     assert(bit < binfo->nbits);
     assert(!bitmap_get(bitmap, binfo, bit));
     goff = bit >> LG_BITMAP_GROUP_NBITS;
     gp = &bitmap[goff];
     g = *gp;
     assert(g & (ZU(1) << (bit & BITMAP_GROUP_NBITS_MASK)));
     g ^= ZU(1) << (bit & BITMAP_GROUP_NBITS_MASK);
     *gp = g;
     assert(bitmap_get(bitmap, binfo, bit));
 #ifdef BITMAP_USE_TREE
     /* Propagate group state transitions up the tree. */
     if (g == 0) {
         unsigned i;
         for (i = 1; i < binfo->nlevels; i++) {
             bit = goff;
             goff = bit >> LG_BITMAP_GROUP_NBITS;
             gp = &bitmap[binfo->levels[i].group_offset + goff];
             g = *gp;
             assert(g & (ZU(1) << (bit & BITMAP_GROUP_NBITS_MASK)));
             g ^= ZU(1) << (bit & BITMAP_GROUP_NBITS_MASK);
             *gp = g;
             if (g != 0) {
                 break;
             }
         }
     }
 #endif
 }
References assert(), bitmap_get(), BITMAP_GROUP_NBITS_MASK, LG_BITMAP_GROUP_NBITS, and ZU.
Referenced by bitmap_sfu(), and extents_remove_locked().
bitmap_sfu()
static size_t bitmap_sfu (bitmap_t * bitmap, const bitmap_info_t * binfo) inline static
Definition at line 301 of file bitmap.h.
{
     size_t bit;
     bitmap_t g;
     unsigned i;
     assert(!bitmap_full(bitmap, binfo));
 #ifdef BITMAP_USE_TREE
     i = binfo->nlevels - 1;
     g = bitmap[binfo->levels[i].group_offset];
     bit = ffs_lu(g) - 1;
     while (i > 0) {
         i--;
         g = bitmap[binfo->levels[i].group_offset + bit];
         bit = (bit << LG_BITMAP_GROUP_NBITS) + (ffs_lu(g) - 1);
     }
 #else
     i = 0;
     g = bitmap[0];
     while ((bit = ffs_lu(g)) == 0) {
         i++;
         g = bitmap[i];
     }
     bit = (i << LG_BITMAP_GROUP_NBITS) + (bit - 1);
 #endif
     bitmap_set(bitmap, binfo, bit);
     return bit;
 }
References assert(), bitmap_full(), bitmap_set(), ffs_lu(), and LG_BITMAP_GROUP_NBITS.
Referenced by arena_slab_reg_alloc(), and arena_slab_reg_alloc_batch().
bitmap_size()
size_t bitmap_size (const bitmap_info_t * binfo)
Definition at line 119 of file bitmap.c.
{
     return (bitmap_info_ngroups(binfo) << LG_SIZEOF_BITMAP);
 }
References bitmap_info_ngroups(), and LG_SIZEOF_BITMAP.
Referenced by bitmap_init().
bitmap_unset()
static void bitmap_unset (bitmap_t * bitmap, const bitmap_info_t * binfo, size_t bit) inline static
Definition at line 331 of file bitmap.h.
{
     size_t goff;
     bitmap_t *gp;
     bitmap_t g;
     UNUSED bool propagate;
     assert(bit < binfo->nbits);
     assert(bitmap_get(bitmap, binfo, bit));
     goff = bit >> LG_BITMAP_GROUP_NBITS;
     gp = &bitmap[goff];
     g = *gp;
     propagate = (g == 0);
     assert((g & (ZU(1) << (bit & BITMAP_GROUP_NBITS_MASK))) == 0);
     g ^= ZU(1) << (bit & BITMAP_GROUP_NBITS_MASK);
     *gp = g;
     assert(!bitmap_get(bitmap, binfo, bit));
 #ifdef BITMAP_USE_TREE
     /* Propagate group state transitions up the tree. */
     if (propagate) {
         unsigned i;
         for (i = 1; i < binfo->nlevels; i++) {
             bit = goff;
             goff = bit >> LG_BITMAP_GROUP_NBITS;
             gp = &bitmap[binfo->levels[i].group_offset + goff];
             g = *gp;
             propagate = (g == 0);
             assert((g & (ZU(1) << (bit & BITMAP_GROUP_NBITS_MASK)))
                 == 0);
             g ^= ZU(1) << (bit & BITMAP_GROUP_NBITS_MASK);
             *gp = g;
             if (!propagate) {
                 break;
             }
         }
     }
 #endif /* BITMAP_USE_TREE */
 }
References assert(), bitmap_get(), BITMAP_GROUP_NBITS_MASK, LG_BITMAP_GROUP_NBITS, UNUSED, and ZU.
Referenced by arena_slab_reg_dalloc(), and extents_insert_locked().