Azerotcore-wotlk: npc_crystalline_frayer::npc_crystalline_frayerAI Struct Reference
npc_crystalline_frayer::npc_crystalline_frayerAI Struct Reference
Public Member Functions
npc_crystalline_frayerAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *) override
void EnterEvadeMode () override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
bool _allowDeath
uint32 restoreTimer
uint32 abilityTimer1
uint32 abilityTimer2
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 204 of file instance_nexus.cpp.
Constructor & Destructor Documentation
npc_crystalline_frayerAI()
npc_crystalline_frayer::npc_crystalline_frayerAI::npc_crystalline_frayerAI (Creature * creature) inline
Definition at line 206 of file instance_nexus.cpp.
                                                      : ScriptedAI(creature)
         {
         }
Member Function Documentation
DamageTaken()
void npc_crystalline_frayer::npc_crystalline_frayerAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 235 of file instance_nexus.cpp.
         {
             if (damage >= me->GetHealth())
             {
                 if (!_allowDeath)
                 {
                     me->RemoveAllAuras();
                     me->DeleteThreatList();
                     me->CombatStop(true);
                     damage = 0;
                     me->SetReactState(REACT_PASSIVE);
                     me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                     me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                     me->SetRegeneratingHealth(false);
                     me->CastSpell(me, SPELL_SUMMON_SEED_POD, true);
                     me->CastSpell(me, SPELL_SEED_POD, true);
                     me->CastSpell(me, SPELL_AURA_OF_REGENERATION, false);
                     restoreTimer = 1;
                 }
             }
         }
References _allowDeath, Unit::CastSpell(), Unit::CombatStop(), Unit::DeleteThreatList(), Unit::GetHealth(), ScriptedAI::me, REACT_PASSIVE, Unit::RemoveAllAuras(), restoreTimer, Object::SetFlag(), Creature::SetReactState(), Creature::SetRegeneratingHealth(), SPELL_AURA_OF_REGENERATION, SPELL_SEED_POD, SPELL_SUMMON_SEED_POD, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
EnterCombat()
void npc_crystalline_frayer::npc_crystalline_frayerAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 224 of file instance_nexus.cpp.
         {
             _allowDeath = me->GetInstanceScript()->GetBossState(DATA_ORMOROK_EVENT) == DONE;
         }
References _allowDeath, DATA_ORMOROK_EVENT, DONE, InstanceScript::GetBossState(), WorldObject::GetInstanceScript(), and ScriptedAI::me.
EnterEvadeMode()
void npc_crystalline_frayer::npc_crystalline_frayerAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 229 of file instance_nexus.cpp.
         {
             if (me->isRegeneratingHealth())
                 ScriptedAI::EnterEvadeMode();
         }
References CreatureAI::EnterEvadeMode(), Creature::isRegeneratingHealth(), and ScriptedAI::me.
Reset()
void npc_crystalline_frayer::npc_crystalline_frayerAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 215 of file instance_nexus.cpp.
         {
             restoreTimer = 0;
             abilityTimer1 = 0;
             abilityTimer2 = 30000;
             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
         }
References abilityTimer1, abilityTimer2, ScriptedAI::me, Object::RemoveFlag(), restoreTimer, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
UpdateAI()
void npc_crystalline_frayer::npc_crystalline_frayerAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 258 of file instance_nexus.cpp.
         {
             if (restoreTimer)
             {
                 restoreTimer += diff;
                 if (restoreTimer >= 90 * IN_MILLISECONDS)
                 {
                     Talk(0);
                     me->SetRegeneratingHealth(true);
                     restoreTimer = 0;
                     me->SetReactState(REACT_AGGRESSIVE);
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                 }
                 return;
             }
             if (!UpdateVictim())
                 return;
             abilityTimer1 += diff;
             abilityTimer2 += diff;
             if (abilityTimer1 >= 5000)
             {
                 me->CastSpell(me->GetVictim(), SPELL_ENSNARE, false);
                 abilityTimer1 = 0;
             }
             if (abilityTimer2 >= 30000)
             {
                 me->CastSpell(me->GetVictim(), SPELL_CRYSTAL_BLOOM, false);
                 abilityTimer2 = 0;
             }
         }
References abilityTimer1, abilityTimer2, Unit::CastSpell(), Unit::GetVictim(), IN_MILLISECONDS, ScriptedAI::me, REACT_AGGRESSIVE, Object::RemoveFlag(), restoreTimer, Creature::SetReactState(), Creature::SetRegeneratingHealth(), SPELL_CRYSTAL_BLOOM, SPELL_ENSNARE, CreatureAI::Talk(), UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, and CreatureAI::UpdateVictim().
Member Data Documentation
_allowDeath
bool npc_crystalline_frayer::npc_crystalline_frayerAI::_allowDeath
Definition at line 210 of file instance_nexus.cpp.
Referenced by DamageTaken(), and EnterCombat().
abilityTimer1
uint32 npc_crystalline_frayer::npc_crystalline_frayerAI::abilityTimer1
Definition at line 212 of file instance_nexus.cpp.
Referenced by Reset(), and UpdateAI().
abilityTimer2
uint32 npc_crystalline_frayer::npc_crystalline_frayerAI::abilityTimer2
Definition at line 213 of file instance_nexus.cpp.
Referenced by Reset(), and UpdateAI().
restoreTimer
uint32 npc_crystalline_frayer::npc_crystalline_frayerAI::restoreTimer
Definition at line 211 of file instance_nexus.cpp.
Referenced by DamageTaken(), Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Nexus/Nexus/instance_nexus.cpp