Azerotcore-wotlk: npc_innkeeper Class Reference
npc_innkeeper Class Reference
Public Member Functions
npc_innkeeper ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 31 of file npc_innkeeper.cpp.
Constructor & Destructor Documentation
npc_innkeeper()
npc_innkeeper::npc_innkeeper () inline
Definition at line 34 of file npc_innkeeper.cpp.
 : CreatureScript("npc_innkeeper") { }
Member Function Documentation
OnGossipHello()
bool npc_innkeeper::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 36 of file npc_innkeeper.cpp.
     {
         if (IsEventActive(HALLOWEEN_EVENTID) && !player->HasAura(SPELL_TRICKED_OR_TREATED))
         {
             AddGossipItemFor(player, GOSSIP_MENU_EVENT, 0, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + HALLOWEEN_EVENTID);
         }
         if (creature->IsQuestGiver())
         {
             player->PrepareQuestMenu(creature->GetGUID());
         }
         if (creature->IsVendor())
         {
             AddGossipItemFor(player, GOSSIP_MENU, 2, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_TRADE);
         }
         if (creature->IsInnkeeper())
         {
             AddGossipItemFor(player, GOSSIP_MENU, 1, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INN);
         }
         player->TalkedToCreature(creature->GetEntry(), creature->GetGUID());
         SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), Object::GetEntry(), Player::GetGossipTextId(), Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ACTION_INN, GOSSIP_ACTION_TRADE, GOSSIP_MENU, GOSSIP_MENU_EVENT, GOSSIP_SENDER_MAIN, HALLOWEEN_EVENTID, Unit::HasAura(), IsEventActive(), Unit::IsInnkeeper(), Unit::IsQuestGiver(), Unit::IsVendor(), Player::PrepareQuestMenu(), SendGossipMenuFor(), SPELL_TRICKED_OR_TREATED, and Player::TalkedToCreature().
OnGossipSelect()
bool npc_innkeeper::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 63 of file npc_innkeeper.cpp.
     {
         ClearGossipMenuFor(player);
         if (action == GOSSIP_ACTION_INFO_DEF + HALLOWEEN_EVENTID && IsEventActive(HALLOWEEN_EVENTID) && !player->HasAura(SPELL_TRICKED_OR_TREATED))
         {
             player->CastSpell(player, SPELL_TRICKED_OR_TREATED, true);
             creature->CastSpell(player, roll_chance_i(50) ? SPELL_TRICK : SPELL_TREAT, true);
             CloseGossipMenuFor(player);
             return true;
         }
         CloseGossipMenuFor(player);
         switch (action)
         {
             case GOSSIP_ACTION_TRADE:
                 player->GetSession()->SendListInventory(creature->GetGUID());
                 break;
             case GOSSIP_ACTION_INN:
                 player->SetBindPoint(creature->GetGUID());
                 break;
         }
         return true;
     }
References Unit::CastSpell(), ClearGossipMenuFor(), CloseGossipMenuFor(), Object::GetGUID(), Player::GetSession(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ACTION_INN, GOSSIP_ACTION_TRADE, HALLOWEEN_EVENTID, Unit::HasAura(), IsEventActive(), roll_chance_i(), WorldSession::SendListInventory(), Player::SetBindPoint(), SPELL_TREAT, SPELL_TRICK, and SPELL_TRICKED_OR_TREATED.
The documentation for this class was generated from the following file:
src/server/scripts/World/npc_innkeeper.cpp