Azerotcore-wotlk: npc_death_knight_initiate Class Reference
npc_death_knight_initiate Class Reference
Classes
struct npc_death_knight_initiateAI
Public Member Functions
npc_death_knight_initiate ()
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
bool OnGossipHello (Player *player, Creature *creature) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 183 of file chapter1.cpp.
Constructor & Destructor Documentation
npc_death_knight_initiate()
npc_death_knight_initiate::npc_death_knight_initiate () inline
Definition at line 186 of file chapter1.cpp.
 : CreatureScript("npc_death_knight_initiate") { }
Member Function Documentation
GetAI()
CreatureAI* npc_death_knight_initiate::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 228 of file chapter1.cpp.
     {
         return new npc_death_knight_initiateAI(creature);
     }
OnGossipHello()
bool npc_death_knight_initiate::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 210 of file chapter1.cpp.
     {
         if (player->GetQuestStatus(QUEST_DEATH_CHALLENGE) == QUEST_STATUS_INCOMPLETE && creature->IsFullHealth())
         {
             if (player->HealthBelowPct(10))
                 return true;
             if (player->IsInCombat() || creature->IsInCombat())
                 return true;
             if (!creature->AI()->GetGUID(player->GetGUID().GetCounter()))
                 AddGossipItemFor(player, 9765, 0, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF);
             SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
         }
         return true;
     }
References AddGossipItemFor(), Creature::AI(), ObjectGuid::GetCounter(), Player::GetGossipTextId(), UnitAI::GetGUID(), Object::GetGUID(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_SENDER_MAIN, Unit::HealthBelowPct(), Unit::IsFullHealth(), Unit::IsInCombat(), QUEST_DEATH_CHALLENGE, QUEST_STATUS_INCOMPLETE, and SendGossipMenuFor().
OnGossipSelect()
bool npc_death_knight_initiate::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 188 of file chapter1.cpp.
     {
         ClearGossipMenuFor(player);
         if (action == GOSSIP_ACTION_INFO_DEF)
         {
             CloseGossipMenuFor(player);
             if (player->IsInCombat() || creature->IsInCombat())
                 return true;
             if (creature->AI()->GetData(DATA_IN_PROGRESS))
                 return true;
             creature->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
             creature->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_SWIMMING);
             player->CastSpell(creature, SPELL_DUEL, false);
             player->CastSpell(player, SPELL_DUEL_FLAG, true);
         }
         return true;
     }
References Creature::AI(), Unit::CastSpell(), ClearGossipMenuFor(), CloseGossipMenuFor(), DATA_IN_PROGRESS, UnitAI::GetData(), GOSSIP_ACTION_INFO_DEF, Unit::IsInCombat(), Object::RemoveFlag(), SPELL_DUEL, SPELL_DUEL_FLAG, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC, and UNIT_FLAG_SWIMMING.
The documentation for this class was generated from the following file:
src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp