Azerotcore-wotlk: anonymous_namespace{DetourNavMesh.cpp} Namespace Reference
anonymous_namespace{DetourNavMesh.cpp} Namespace Reference
Functions
template<bool onlyBoundary>
void closestPointOnDetailEdges (const dtMeshTile *tile, const dtPoly *poly, const float *pos, float *closest)
Function Documentation
closestPointOnDetailEdges()
template<bool onlyBoundary> void anonymous_namespace{DetourNavMesh.cpp}::closestPointOnDetailEdges (const dtMeshTile * tile, const dtPoly * poly, const float * pos, float * closest)
Definition at line 622 of file DetourNavMesh.cpp.
     {
         const unsigned int ip = (unsigned int)(poly - tile->polys);
         const dtPolyDetail* pd = &tile->detailMeshes[ip];
         float dmin = FLT_MAX;
         float tmin = 0;
         const float* pmin = 0;
         const float* pmax = 0;
         for (int i = 0; i < pd->triCount; i++)
         {
             const unsigned char* tris = &tile->detailTris[(pd->triBase + i) * 4];
             const int ANY_BOUNDARY_EDGE =
                 (DT_DETAIL_EDGE_BOUNDARY << 0) |
                 (DT_DETAIL_EDGE_BOUNDARY << 2) |
                 (DT_DETAIL_EDGE_BOUNDARY << 4);
             if (onlyBoundary && (tris[3] & ANY_BOUNDARY_EDGE) == 0)
                 continue;
             const float* v[3];
             for (int j = 0; j < 3; ++j)
             {
                 if (tris[j] < poly->vertCount)
                     v[j] = &tile->verts[poly->verts[tris[j]] * 3];
                 else
                     v[j] = &tile->detailVerts[(pd->vertBase + (tris[j] - poly->vertCount)) * 3];
             }
             for (int k = 0, j = 2; k < 3; j = k++)
             {
                 if ((dtGetDetailTriEdgeFlags(tris[3], j) & DT_DETAIL_EDGE_BOUNDARY) == 0 &&
                     (onlyBoundary || tris[j] < tris[k]))
                 {
                     // Only looking at boundary edges and this is internal, or
                     // this is an inner edge that we will see again or have already seen.
                     continue;
                 }
                 float t;
                 float d = dtDistancePtSegSqr2D(pos, v[j], v[k], t);
                 if (d < dmin)
                 {
                     dmin = d;
                     tmin = t;
                     pmin = v[j];
                     pmax = v[k];
                 }
             }
         }
         dtVlerp(closest, pmin, pmax, tmin);
     }
References mpq::d, dtMeshTile::detailMeshes, dtMeshTile::detailTris, dtMeshTile::detailVerts, DT_DETAIL_EDGE_BOUNDARY, dtDistancePtSegSqr2D(), dtGetDetailTriEdgeFlags(), dtVlerp(), FLT_MAX, dtMeshTile::polys, pos(), dtPolyDetail::triBase, dtPolyDetail::triCount, dtPolyDetail::vertBase, dtPoly::vertCount, dtPoly::verts, and dtMeshTile::verts.