Azerotcore-wotlk: st_plugin_vio Struct Reference
st_plugin_vio Struct Reference
#include <plugin_auth_common.h>
Public Attributes
int(* read_packet)(struct st_plugin_vio *vio, unsigned char **buf)
int(* write_packet)(struct st_plugin_vio *vio, const unsigned char *packet, int packet_len)
void(* info)(struct st_plugin_vio *vio, struct st_plugin_vio_info *info)
Detailed Description
Provides plugin access to communication channel
Definition at line 78 of file plugin_auth_common.h.
Member Data Documentation
info
void(* st_plugin_vio::info) (struct st_plugin_vio *vio, struct st_plugin_vio_info *info)
Fills in a st_plugin_vio_info structure, providing the information about the connection.
Definition at line 100 of file plugin_auth_common.h.
read_packet
int(* st_plugin_vio::read_packet) (struct st_plugin_vio *vio, unsigned char **buf)
Plugin provides a pointer reference and this function sets it to the contents of any incoming packet. Returns the packet length, or -1 if the plugin should terminate.
Definition at line 85 of file plugin_auth_common.h.
Referenced by native_password_auth_client(), and old_password_auth_client().
write_packet
int(* st_plugin_vio::write_packet) (struct st_plugin_vio *vio, const unsigned char *packet, int packet_len)
Plugin provides a buffer with data and the length and this function sends it as a packet. Returns 0 on success, 1 on failure.
Definition at line 92 of file plugin_auth_common.h.
Referenced by native_password_auth_client(), and old_password_auth_client().
The documentation for this struct was generated from the following file:
deps/mysqllite/include/mysql/plugin_auth_common.h