Azerotcore-wotlk: guild_commandscript Class Reference
guild_commandscript Class Reference
Public Member Functions
guild_commandscript ()
ChatCommandTable GetCommands () const override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Static Public Member Functions
static bool HandleGuildCreateCommand (ChatHandler *handler, char const *args)
GM command level 3 - Create a guild.
static bool HandleGuildDeleteCommand (ChatHandler *handler, char const *args)
static bool HandleGuildInviteCommand (ChatHandler *handler, char const *args)
static bool HandleGuildUninviteCommand (ChatHandler *handler, char const *args)
static bool HandleGuildRankCommand (ChatHandler *handler, Optional< PlayerIdentifier > player, uint8 rank)
static bool HandleGuildInfoCommand (ChatHandler *handler, char const *args)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 38 of file cs_guild.cpp.
Constructor & Destructor Documentation
guild_commandscript()
guild_commandscript::guild_commandscript () inline
Definition at line 41 of file cs_guild.cpp.
 : CommandScript("guild_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable guild_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
Definition at line 43 of file cs_guild.cpp.
     {
         static ChatCommandTable guildCommandTable =
         {
             { "create",         SEC_GAMEMASTER,     true,  &HandleGuildCreateCommand,           "" },
             { "delete",         SEC_GAMEMASTER,     true,  &HandleGuildDeleteCommand,           "" },
             { "invite",         SEC_GAMEMASTER,     true,  &HandleGuildInviteCommand,           "" },
             { "uninvite",       SEC_GAMEMASTER,     true,  &HandleGuildUninviteCommand,         "" },
             { "rank",           SEC_GAMEMASTER,     true,  &HandleGuildRankCommand,             "" },
             { "info",           SEC_GAMEMASTER,     true,  &HandleGuildInfoCommand,             "" }
         };
         static ChatCommandTable commandTable =
         {
             { "guild",          SEC_GAMEMASTER,  true, nullptr,                                 "", guildCommandTable }
         };
         return commandTable;
     }
References SEC_GAMEMASTER.
HandleGuildCreateCommand()
static bool guild_commandscript::HandleGuildCreateCommand (ChatHandler * handler, char const * args) inline static
GM command level 3 - Create a guild.
This command allows a GM (level 3) to create a guild.
The "args" parameter contains the name of the guild leader and then the name of the guild.
Definition at line 69 of file cs_guild.cpp.
     {
         if (!*args)
             return false;
         // if not guild name only (in "") then player name
         Player* target;
         if (!handler->extractPlayerTarget(*args != '"' ? (char*)args : nullptr, &target))
             return false;
         char* tailStr = *args != '"' ? strtok(nullptr, "") : (char*)args;
         if (!tailStr)
             return false;
         char* guildStr = handler->extractQuotedArg(tailStr);
         if (!guildStr)
             return false;
         std::string guildName = guildStr;
         if (target->GetGuildId())
         {
             handler->SendSysMessage(LANG_PLAYER_IN_GUILD);
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (sGuildMgr->GetGuildByName(guildName))
         {
             handler->SendSysMessage(LANG_GUILD_RENAME_ALREADY_EXISTS);
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (sObjectMgr->IsReservedName(guildName) || !sObjectMgr->IsValidCharterName(guildName))
         {
             handler->SendSysMessage(LANG_BAD_VALUE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         Guild* guild = new Guild;
         if (!guild->Create(target, guildName))
         {
             delete guild;
             handler->SendSysMessage(LANG_GUILD_NOT_CREATED);
             handler->SetSentErrorMessage(true);
             return false;
         }
         sGuildMgr->AddGuild(guild);
         return true;
     }
References Guild::Create(), ChatHandler::extractPlayerTarget(), ChatHandler::extractQuotedArg(), Player::GetGuildId(), LANG_BAD_VALUE, LANG_GUILD_NOT_CREATED, LANG_GUILD_RENAME_ALREADY_EXISTS, LANG_PLAYER_IN_GUILD, ChatHandler::SendSysMessage(), ChatHandler::SetSentErrorMessage(), sGuildMgr, and sObjectMgr.
HandleGuildDeleteCommand()
static bool guild_commandscript::HandleGuildDeleteCommand (ChatHandler * handler, char const * args) inline static
Definition at line 124 of file cs_guild.cpp.
     {
         if (!*args)
             return false;
         char* guildStr = handler->extractQuotedArg((char*)args);
         if (!guildStr)
             return false;
         std::string guildName = guildStr;
         Guild* targetGuild = sGuildMgr->GetGuildByName(guildName);
         if (!targetGuild)
             return false;
         targetGuild->Disband();
         delete targetGuild;
         return true;
     }
References Guild::Disband(), ChatHandler::extractQuotedArg(), and sGuildMgr.
HandleGuildInfoCommand()
static bool guild_commandscript::HandleGuildInfoCommand (ChatHandler * handler, char const * args) inline static
Definition at line 210 of file cs_guild.cpp.
     {
         Guild* guild = nullptr;
         if (args && args[0] != '\0')
         {
             if (isNumeric(args))
                 guild = sGuildMgr->GetGuildById(strtoull(args, nullptr, 10));
             else
                 guild = sGuildMgr->GetGuildByName(args);
         }
         else if (Player* target = handler->getSelectedPlayerOrSelf())
             guild = target->GetGuild();
         if (!guild)
             return false;
         // Display Guild Information
         handler->PSendSysMessage(LANG_GUILD_INFO_NAME, guild->GetName().c_str(), guild->GetId()); // Guild Id + Name
         std::string guildMasterName;
         if (sObjectMgr->GetPlayerNameByGUID(guild->GetLeaderGUID().GetCounter(), guildMasterName))
             handler->PSendSysMessage(LANG_GUILD_INFO_GUILD_MASTER, guildMasterName.c_str(), guild->GetLeaderGUID().GetCounter()); // Guild Master
         // Format creation date
         char createdDateStr[20];
         time_t createdDate = guild->GetCreatedDate();
         tm localTm;
         localtime_r(&createdDate, &localTm);
         strftime(createdDateStr, 20, "%Y-%m-%d %H:%M:%S", &localTm);
         handler->PSendSysMessage(LANG_GUILD_INFO_CREATION_DATE, createdDateStr); // Creation Date
         handler->PSendSysMessage(LANG_GUILD_INFO_MEMBER_COUNT, guild->GetMemberCount()); // Number of Members
         handler->PSendSysMessage(LANG_GUILD_INFO_BANK_GOLD, guild->GetTotalBankMoney() / 100 / 100); // Bank Gold (in gold coins)
         handler->PSendSysMessage(LANG_GUILD_INFO_MOTD, guild->GetMOTD().c_str()); // Message of the day
         handler->PSendSysMessage(LANG_GUILD_INFO_EXTRA_INFO, guild->GetInfo().c_str()); // Extra Information
         return true;
     }
References ObjectGuid::GetCounter(), Guild::GetCreatedDate(), Guild::GetId(), Guild::GetInfo(), Guild::GetLeaderGUID(), Guild::GetMemberCount(), Guild::GetMOTD(), Guild::GetName(), ChatHandler::getSelectedPlayerOrSelf(), Guild::GetTotalBankMoney(), isNumeric(), LANG_GUILD_INFO_BANK_GOLD, LANG_GUILD_INFO_CREATION_DATE, LANG_GUILD_INFO_EXTRA_INFO, LANG_GUILD_INFO_GUILD_MASTER, LANG_GUILD_INFO_MEMBER_COUNT, LANG_GUILD_INFO_MOTD, LANG_GUILD_INFO_NAME, localtime_r(), ChatHandler::PSendSysMessage(), sGuildMgr, sObjectMgr, strftime(), and strtoull.
HandleGuildInviteCommand()
static bool guild_commandscript::HandleGuildInviteCommand (ChatHandler * handler, char const * args) inline static
Definition at line 145 of file cs_guild.cpp.
     {
         if (!*args)
             return false;
         // if not guild name only (in "") then player name
         ObjectGuid targetGuid;
         if (!handler->extractPlayerTarget(*args != '"' ? (char*)args : nullptr, nullptr, &targetGuid))
             return false;
         char* tailStr = *args != '"' ? strtok(nullptr, "") : (char*)args;
         if (!tailStr)
             return false;
         char* guildStr = handler->extractQuotedArg(tailStr);
         if (!guildStr)
             return false;
         std::string guildName = guildStr;
         Guild* targetGuild = sGuildMgr->GetGuildByName(guildName);
         if (!targetGuild)
             return false;
         // player's guild membership checked in AddMember before add
         return targetGuild->AddMember(targetGuid);
     }
References Guild::AddMember(), ChatHandler::extractPlayerTarget(), ChatHandler::extractQuotedArg(), and sGuildMgr.
HandleGuildRankCommand()
static bool guild_commandscript::HandleGuildRankCommand (ChatHandler * handler, Optional< PlayerIdentifier > player, uint8 rank) inline static
Definition at line 191 of file cs_guild.cpp.
     {
         if (!player)
             player = PlayerIdentifier::FromTargetOrSelf(handler);
         if (!player)
             return false;
         uint32 guildId = player->IsConnected() ? player->GetConnectedPlayer()->GetGuildId() : Player::GetGuildIdFromStorage(player->GetGUID().GetCounter());
         if (!guildId)
             return false;
         Guild* targetGuild = sGuildMgr->GetGuildById(guildId);
         if (!targetGuild)
             return false;
         return targetGuild->ChangeMemberRank(player->GetGUID(), rank);
     }
References Guild::ChangeMemberRank(), Acore::ChatCommands::PlayerIdentifier::FromTargetOrSelf(), Player::GetGuildIdFromStorage(), and sGuildMgr.
HandleGuildUninviteCommand()
static bool guild_commandscript::HandleGuildUninviteCommand (ChatHandler * handler, char const * args) inline static
Definition at line 172 of file cs_guild.cpp.
     {
         Player* target;
         ObjectGuid targetGuid;
         if (!handler->extractPlayerTarget((char*)args, &target, &targetGuid))
             return false;
         uint32 guildId = target ? target->GetGuildId() : Player::GetGuildIdFromStorage(targetGuid.GetCounter());
         if (!guildId)
             return false;
         Guild* targetGuild = sGuildMgr->GetGuildById(guildId);
         if (!targetGuild)
             return false;
         targetGuild->DeleteMember(targetGuid, false, true, true);
         return true;
     }
References Guild::DeleteMember(), ChatHandler::extractPlayerTarget(), ObjectGuid::GetCounter(), Player::GetGuildId(), Player::GetGuildIdFromStorage(), and sGuildMgr.
The documentation for this class was generated from the following file:
src/server/scripts/Commands/cs_guild.cpp