Azerotcore-wotlk: npc_hor_leader Class Reference
npc_hor_leader Class Reference
Classes
struct npc_hor_leaderAI
Public Member Functions
npc_hor_leader ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 uiAction) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 87 of file halls_of_reflection.cpp.
Constructor & Destructor Documentation
npc_hor_leader()
npc_hor_leader::npc_hor_leader () inline
Definition at line 90 of file halls_of_reflection.cpp.
 : CreatureScript("npc_hor_leader") { }
Member Function Documentation
GetAI()
CreatureAI* npc_hor_leader::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 170 of file halls_of_reflection.cpp.
     {
         return GetHallsOfReflectionAI<npc_hor_leaderAI>(creature);
     }
OnGossipHello()
bool npc_hor_leader::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 92 of file halls_of_reflection.cpp.
     {
         if (!creature->HasFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP))
             return true;
         if (creature->IsQuestGiver())
             player->PrepareQuestMenu(creature->GetGUID());
         bool canStart = true;
         if (InstanceScript* instance = creature->GetInstanceScript())
             if (uint32 bhd = instance->GetData(DATA_BATTERED_HILT))
                 if ((bhd & BHSF_FINISHED) == 0)
                     canStart = false;
         if (canStart)
         {
             QuestStatus status = player->GetQuestStatus(creature->GetEntry() == NPC_SYLVANAS_PART1 ? QUEST_DELIVRANCE_FROM_THE_PIT_H2 : QUEST_DELIVRANCE_FROM_THE_PIT_A2);
             if (status == QUEST_STATUS_COMPLETE || status == QUEST_STATUS_REWARDED)
                 AddGossipItemFor(player, 0, "Can you remove the sword?", GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
             // once last quest is completed, she offers this shortcut of the starting event
             status = player->GetQuestStatus(creature->GetEntry() == NPC_SYLVANAS_PART1 ? QUEST_WRATH_OF_THE_LICH_KING_H2 : QUEST_WRATH_OF_THE_LICH_KING_A2);
             if (status == QUEST_STATUS_COMPLETE || status == QUEST_STATUS_REWARDED)
             {
                 if (creature->GetEntry() == NPC_SYLVANAS_PART1)
                     AddGossipItemFor(player, 0, "Dark Lady, I think I hear Arthas coming. Whatever you're going to do, do it quickly.", GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
                 else
                     AddGossipItemFor(player, 0, "My Lady, I think I hear Arthas coming. Whatever you're going to do, do it quickly.", GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
             }
         }
         if (creature->GetEntry() == NPC_SYLVANAS_PART1)
         {
             SendGossipMenuFor(player, 15215, creature->GetGUID());
         }
         else if (creature->GetEntry() == NPC_JAINA_PART1)
         {
             SendGossipMenuFor(player, 15339, creature->GetGUID());
         }
         return true;
     }
References AddGossipItemFor(), BHSF_FINISHED, DATA_BATTERED_HILT, Object::GetEntry(), Object::GetGUID(), WorldObject::GetInstanceScript(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_SENDER_MAIN, Object::HasFlag(), Unit::IsQuestGiver(), NPC_JAINA_PART1, NPC_SYLVANAS_PART1, Player::PrepareQuestMenu(), QUEST_DELIVRANCE_FROM_THE_PIT_A2, QUEST_DELIVRANCE_FROM_THE_PIT_H2, QUEST_STATUS_COMPLETE, QUEST_STATUS_REWARDED, QUEST_WRATH_OF_THE_LICH_KING_A2, QUEST_WRATH_OF_THE_LICH_KING_H2, SendGossipMenuFor(), UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
OnGossipSelect()
bool npc_hor_leader::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 uiAction) inline override virtual
Reimplemented from CreatureScript.
Definition at line 135 of file halls_of_reflection.cpp.
     {
         if (!creature->HasFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP))
             return true;
         InstanceScript* instance = creature->GetInstanceScript();
         if (!instance)
             return true;
         if (uint32 bhd = instance->GetData(DATA_BATTERED_HILT))
             if ((bhd & BHSF_FINISHED) == 0)
                 return true;
         instance->SetData(DATA_BATTERED_HILT, 1);
         ClearGossipMenuFor(player);
         switch (uiAction)
         {
             case GOSSIP_ACTION_INFO_DEF+1:
                 CloseGossipMenuFor(player);
                 if (creature->AI())
                     creature->AI()->DoAction(ACTION_START_INTRO);
                 creature->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP | UNIT_NPC_FLAG_QUESTGIVER);
                 break;
             case GOSSIP_ACTION_INFO_DEF+2:
                 CloseGossipMenuFor(player);
                 if (creature->AI())
                     creature->AI()->DoAction(ACTION_SKIP_INTRO);
                 creature->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP | UNIT_NPC_FLAG_QUESTGIVER);
                 break;
         }
         return true;
     }
References ACTION_SKIP_INTRO, ACTION_START_INTRO, Creature::AI(), BHSF_FINISHED, ClearGossipMenuFor(), CloseGossipMenuFor(), DATA_BATTERED_HILT, UnitAI::DoAction(), ZoneScript::GetData(), WorldObject::GetInstanceScript(), GOSSIP_ACTION_INFO_DEF, Object::HasFlag(), Object::RemoveFlag(), ZoneScript::SetData(), UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAG_QUESTGIVER, and UNIT_NPC_FLAGS.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/halls_of_reflection.cpp