Azerotcore-wotlk: npc_calvin_montague Class Reference
npc_calvin_montague Class Reference
Classes
struct npc_calvin_montagueAI
Public Member Functions
npc_calvin_montague ()
bool OnQuestAccept (Player *player, Creature *creature, Quest const *quest) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 46 of file zone_tirisfal_glades.cpp.
Constructor & Destructor Documentation
npc_calvin_montague()
npc_calvin_montague::npc_calvin_montague () inline
Definition at line 49 of file zone_tirisfal_glades.cpp.
 : CreatureScript("npc_calvin_montague") { }
Member Function Documentation
GetAI()
CreatureAI* npc_calvin_montague::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 62 of file zone_tirisfal_glades.cpp.
     {
         return new npc_calvin_montagueAI(creature);
     }
OnQuestAccept()
bool npc_calvin_montague::OnQuestAccept (Player * player, Creature * creature, Quest const * quest) inline override virtual
Reimplemented from CreatureScript.
Definition at line 51 of file zone_tirisfal_glades.cpp.
     {
         if (quest->GetQuestId() == QUEST_590)
         {
             creature->SetFaction(FACTION_ENEMY);
             creature->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
             CAST_AI(npc_calvin_montague::npc_calvin_montagueAI, creature->AI())->AttackStart(player);
         }
         return true;
     }
References Creature::AI(), CAST_AI, FACTION_ENEMY, Quest::GetQuestId(), QUEST_590, Object::RemoveFlag(), Unit::SetFaction(), UNIT_FIELD_FLAGS, and UNIT_FLAG_IMMUNE_TO_PC.
The documentation for this class was generated from the following file:
src/server/scripts/EasternKingdoms/zone_tirisfal_glades.cpp