Azerotcore-wotlk: GridReference< OBJECT > Class Template Reference
GridReference< OBJECT > Class Template Reference
#include <GridReference.h>
Public Member Functions
GridReference ()
~GridReference () override
GridReference * next ()
Public Member Functions inherited from Reference< GridRefMgr< OBJECT >, OBJECT >
Reference ()
virtual ~Reference ()=default
void link (GridRefMgr< OBJECT > *toObj, OBJECT *fromObj)
void unlink ()
void invalidate ()
bool isValid () const
Reference< GridRefMgr< OBJECT >, OBJECT > * next ()
Reference< GridRefMgr< OBJECT >, OBJECT > const * next () const
Reference< GridRefMgr< OBJECT >, OBJECT > * prev ()
Reference< GridRefMgr< OBJECT >, OBJECT > const * prev () const
Reference< GridRefMgr< OBJECT >, OBJECT > * nocheck_next ()
Reference< GridRefMgr< OBJECT >, OBJECT > const * nocheck_next () const
Reference< GridRefMgr< OBJECT >, OBJECT > * nocheck_prev ()
Reference< GridRefMgr< OBJECT >, OBJECT > const * nocheck_prev () const
GridRefMgr< OBJECT > * operator-> () const
GridRefMgr< OBJECT > * getTarget () const
OBJECT * GetSource () const
Public Member Functions inherited from LinkedListElement
LinkedListElement ()
~LinkedListElement ()
bool hasNext () const
bool hasPrev () const
bool isInList () const
LinkedListElement * next ()
LinkedListElement const * next () const
LinkedListElement * prev ()
LinkedListElement const * prev () const
LinkedListElement * nocheck_next ()
LinkedListElement const * nocheck_next () const
LinkedListElement * nocheck_prev ()
LinkedListElement const * nocheck_prev () const
void delink ()
void insertBefore (LinkedListElement *pElem)
void insertAfter (LinkedListElement *pElem)
Protected Member Functions
void targetObjectBuildLink () override
void targetObjectDestroyLink () override
void sourceObjectDestroyLink () override
Detailed Description
template<class OBJECT>
class GridReference< OBJECT >
Definition at line 27 of file GridReference.h.
Constructor & Destructor Documentation
GridReference()
template<class OBJECT > GridReference< OBJECT >::GridReference () inline
Definition at line 47 of file GridReference.h.
 : Reference<GridRefMgr<OBJECT>, OBJECT>() {}
~GridReference()
template<class OBJECT > GridReference< OBJECT >::~GridReference () inline override
Definition at line 48 of file GridReference.h.
 { this->unlink(); }
References Reference< GridRefMgr< OBJECT >, OBJECT >::unlink().
Member Function Documentation
next()
template<class OBJECT > GridReference* GridReference< OBJECT >::next () inline
Definition at line 49 of file GridReference.h.
 { return (GridReference*)Reference<GridRefMgr<OBJECT>, OBJECT>::next(); }
sourceObjectDestroyLink()
template<class OBJECT > void GridReference< OBJECT >::sourceObjectDestroyLink () inline override protected virtual
Implements Reference< GridRefMgr< OBJECT >, OBJECT >.
Definition at line 41 of file GridReference.h.
     {
         // called from invalidate()
         this->getTarget()->decSize();
     }
References Reference< GridRefMgr< OBJECT >, OBJECT >::getTarget().
targetObjectBuildLink()
template<class OBJECT > void GridReference< OBJECT >::targetObjectBuildLink () inline override protected virtual
Implements Reference< GridRefMgr< OBJECT >, OBJECT >.
Definition at line 30 of file GridReference.h.
     {
         // called from link()
         this->getTarget()->insertFirst(this);
         this->getTarget()->incSize();
     }
References Reference< GridRefMgr< OBJECT >, OBJECT >::getTarget().
targetObjectDestroyLink()
template<class OBJECT > void GridReference< OBJECT >::targetObjectDestroyLink () inline override protected virtual
Implements Reference< GridRefMgr< OBJECT >, OBJECT >.
Definition at line 36 of file GridReference.h.
     {
         // called from unlink()
         if (this->isValid()) this->getTarget()->decSize();
     }
References Reference< GridRefMgr< OBJECT >, OBJECT >::getTarget(), and Reference< GridRefMgr< OBJECT >, OBJECT >::isValid().
The documentation for this class was generated from the following file:
src/server/game/Grids/GridReference.h