Azerotcore-wotlk: DispelInfo Class Reference
DispelInfo Class Reference
#include <Unit.h>
Public Member Functions
DispelInfo (Unit *dispeller, uint32 dispellerSpellId, uint8 chargesRemoved)
Unit * GetDispeller () const
uint32 GetDispellerSpellId () const
uint8 GetRemovedCharges () const
void SetRemovedCharges (uint8 amount)
Private Attributes
Unit * _dispellerUnit
uint32 _dispellerSpell
uint8 _chargesRemoved
Detailed Description
Definition at line 868 of file Unit.h.
Constructor & Destructor Documentation
DispelInfo()
DispelInfo::DispelInfo (Unit * dispeller, uint32 dispellerSpellId, uint8 chargesRemoved) inline explicit
Definition at line 871 of file Unit.h.
                                                                                         :
         _dispellerUnit(dispeller), _dispellerSpell(dispellerSpellId), _chargesRemoved(chargesRemoved) {}
Member Function Documentation
GetDispeller()
Unit* DispelInfo::GetDispeller () const inline
Definition at line 874 of file Unit.h.
 { return _dispellerUnit; }
References _dispellerUnit.
Referenced by spell_hexlord_unstable_affliction::spell_hexlord_unstable_affliction_AuraScript::HandleDispel(), spell_faction_champion_warl_unstable_affliction::spell_faction_champion_warl_unstable_affliction_AuraScript::HandleDispel(), and spell_warl_unstable_affliction::HandleDispel().
GetDispellerSpellId()
uint32 DispelInfo::GetDispellerSpellId () const inline
Definition at line 875 of file Unit.h.
 { return _dispellerSpell; }
References _dispellerSpell.
GetRemovedCharges()
uint8 DispelInfo::GetRemovedCharges () const inline
Definition at line 876 of file Unit.h.
 { return _chargesRemoved; }
References _chargesRemoved.
Referenced by spell_dru_lifebloom::HandleDispel(), and Unit::RemoveAurasDueToSpellByDispel().
SetRemovedCharges()
void DispelInfo::SetRemovedCharges (uint8 amount) inline
Definition at line 877 of file Unit.h.
     {
         _chargesRemoved = amount;
     }
References _chargesRemoved.
Referenced by spell_halion_marks::spell_halion_marks_AuraScript::BeforeDispel().
Member Data Documentation
_chargesRemoved
uint8 DispelInfo::_chargesRemoved private
Definition at line 884 of file Unit.h.
Referenced by GetRemovedCharges(), and SetRemovedCharges().
_dispellerSpell
uint32 DispelInfo::_dispellerSpell private
Definition at line 883 of file Unit.h.
Referenced by GetDispellerSpellId().
_dispellerUnit
Unit* DispelInfo::_dispellerUnit private
Definition at line 882 of file Unit.h.
Referenced by GetDispeller().
The documentation for this class was generated from the following file:
src/server/game/Entities/Unit/Unit.h