Azerotcore-wotlk: _malloc_zone_t Struct Reference
_malloc_zone_t Struct Reference
Public Attributes
void * reserved1
void * reserved2
size_t(* size)(struct _malloc_zone_t *, const void *)
void *(* malloc)(struct _malloc_zone_t *, size_t)
void *(* calloc)(struct _malloc_zone_t *, size_t, size_t)
void *(* valloc)(struct _malloc_zone_t *, size_t)
void(* free)(struct _malloc_zone_t *, void *)
void *(* realloc)(struct _malloc_zone_t *, void *, size_t)
void(* destroy)(struct _malloc_zone_t *)
const char * zone_name
unsigned(* batch_malloc)(struct _malloc_zone_t *, size_t, void **, unsigned)
void(* batch_free)(struct _malloc_zone_t *, void **, unsigned)
struct malloc_introspection_t * introspect
unsigned version
void *(* memalign)(struct _malloc_zone_t *, size_t, size_t)
void(* free_definite_size)(struct _malloc_zone_t *, void *, size_t)
size_t(* pressure_relief)(struct _malloc_zone_t *, size_t)
Detailed Description
Definition at line 14 of file zone.c.
Member Data Documentation
batch_free
void(* _malloc_zone_t::batch_free) (struct _malloc_zone_t *, void **, unsigned)
Definition at line 26 of file zone.c.
Referenced by zone_init().
batch_malloc
unsigned(* _malloc_zone_t::batch_malloc) (struct _malloc_zone_t *, size_t, void **, unsigned)
Definition at line 25 of file zone.c.
Referenced by zone_init().
calloc
void*(* _malloc_zone_t::calloc) (struct _malloc_zone_t *, size_t, size_t)
Definition at line 19 of file zone.c.
Referenced by zone_init().
destroy
void(* _malloc_zone_t::destroy) (struct _malloc_zone_t *)
Definition at line 23 of file zone.c.
Referenced by zone_init().
free
void(* _malloc_zone_t::free) (struct _malloc_zone_t *, void *)
Definition at line 21 of file zone.c.
Referenced by zone_init().
free_definite_size
void(* _malloc_zone_t::free_definite_size) (struct _malloc_zone_t *, void *, size_t)
Definition at line 30 of file zone.c.
Referenced by zone_init().
introspect
struct malloc_introspection_t* _malloc_zone_t::introspect
Definition at line 27 of file zone.c.
Referenced by zone_init().
malloc
void*(* _malloc_zone_t::malloc) (struct _malloc_zone_t *, size_t)
Definition at line 18 of file zone.c.
Referenced by zone_init().
memalign
void*(* _malloc_zone_t::memalign) (struct _malloc_zone_t *, size_t, size_t)
Definition at line 29 of file zone.c.
Referenced by zone_init().
pressure_relief
size_t(* _malloc_zone_t::pressure_relief) (struct _malloc_zone_t *, size_t)
Definition at line 31 of file zone.c.
Referenced by zone_init().
realloc
void*(* _malloc_zone_t::realloc) (struct _malloc_zone_t *, void *, size_t)
Definition at line 22 of file zone.c.
Referenced by zone_init().
reserved1
void* _malloc_zone_t::reserved1
Definition at line 15 of file zone.c.
reserved2
void* _malloc_zone_t::reserved2
Definition at line 16 of file zone.c.
size
size_t(* _malloc_zone_t::size) (struct _malloc_zone_t *, const void *)
Definition at line 17 of file zone.c.
Referenced by zone_init().
valloc
void*(* _malloc_zone_t::valloc) (struct _malloc_zone_t *, size_t)
Definition at line 20 of file zone.c.
Referenced by zone_init().
version
unsigned _malloc_zone_t::version
Definition at line 28 of file zone.c.
Referenced by zone_init().
zone_name
const char* _malloc_zone_t::zone_name
Definition at line 24 of file zone.c.
Referenced by zone_init(), and zone_register().
The documentation for this struct was generated from the following file:
deps/jemalloc/src/zone.c