Azerotcore-wotlk: Acore::ChatCommands::PlayerIdentifier Struct Reference
Acore::ChatCommands::PlayerIdentifier Struct Reference
#include <ChatCommandTags.h>
Public Types
using value_type = Player *
Public Types inherited from Acore::Impl::ChatCommands::ContainerTag
using ChatCommandResult = Acore::Impl::ChatCommands::ChatCommandResult
Public Member Functions
PlayerIdentifier ()
PlayerIdentifier (Player &player)
operator ObjectGuid () const
operator std::string const & () const
operator std::string_view () const
std::string const & GetName () const
ObjectGuid GetGUID () const
bool IsConnected () const
Player * GetConnectedPlayer () const
ChatCommandResult TryConsume (ChatHandler const *handler, std::string_view args)
Static Public Member Functions
static Optional< PlayerIdentifier > FromTarget (ChatHandler *handler)
static Optional< PlayerIdentifier > FromSelf (ChatHandler *handler)
static Optional< PlayerIdentifier > FromTargetOrSelf (ChatHandler *handler)
Private Attributes
std::string _name
ObjectGuid _guid
Player * _player
Detailed Description
Definition at line 169 of file ChatCommandTags.h.
Member Typedef Documentation
value_type
using Acore::ChatCommands::PlayerIdentifier::value_type = Player*
Definition at line 171 of file ChatCommandTags.h.
Constructor & Destructor Documentation
PlayerIdentifier() [1/2]
Acore::ChatCommands::PlayerIdentifier::PlayerIdentifier () inline
Definition at line 173 of file ChatCommandTags.h.
 : _name(), _guid(), _player(nullptr) {}
PlayerIdentifier() [2/2]
Acore::ChatCommands::PlayerIdentifier::PlayerIdentifier (Player & player)
Definition at line 127 of file ChatCommandTags.cpp.
     : _name(player.GetName()), _guid(player.GetGUID()), _player(&player) {}
Member Function Documentation
FromSelf()
Optional< Acore::ChatCommands::PlayerIdentifier > Acore::ChatCommands::PlayerIdentifier::FromSelf (ChatHandler * handler) static
Definition at line 139 of file ChatCommandTags.cpp.
 {
     if (Player* player = handler->GetPlayer())
         return { *player };
     return std::nullopt;
 }
References ChatHandler::GetPlayer().
Referenced by instance_commandscript::HandleInstanceGetBossStateCommand(), and instance_commandscript::HandleInstanceSetBossStateCommand().
FromTarget()
Optional< Acore::ChatCommands::PlayerIdentifier > Acore::ChatCommands::PlayerIdentifier::FromTarget (ChatHandler * handler) static
Definition at line 130 of file ChatCommandTags.cpp.
 {
     if (Player* player = handler->GetPlayer())
         if (Player* target = player->GetSelectedPlayer())
             return { *target };
     return std::nullopt;
 }
References ChatHandler::GetPlayer(), and Player::GetSelectedPlayer().
Referenced by character_commandscript::HandleCharacterChangeFactionCommand(), character_commandscript::HandleCharacterChangeRaceCommand(), character_commandscript::HandleCharacterCustomizeCommand(), character_commandscript::HandleCharacterRenameCommand(), and misc_commandscript::HandleMuteCommand().
FromTargetOrSelf()
static Optional<PlayerIdentifier> Acore::ChatCommands::PlayerIdentifier::FromTargetOrSelf (ChatHandler * handler) inline static
Definition at line 189 of file ChatCommandTags.h.
         {
             if (Optional<PlayerIdentifier> fromTarget = FromTarget(handler))
                 return fromTarget;
             else
                 return FromSelf(handler);
         }
Referenced by arena_commandscript::HandleArenaCaptainCommand(), arena_commandscript::HandleArenaCreateCommand(), character_commandscript::HandleCharacterLevelCommand(), character_commandscript::HandleCharacterReputationCommand(), character_commandscript::HandleCharacterTitlesCommand(), guild_commandscript::HandleGuildRankCommand(), misc_commandscript::HandleInventoryCountCommand(), learn_commandscript::HandleLearnAllDefaultCommand(), character_commandscript::HandleLevelUpCommand(), lfg_commandscript::HandleLfgGroupInfoCommand(), lfg_commandscript::HandleLfgPlayerInfoCommand(), player_commandscript::HandlePlayerLearnCommand(), player_commandscript::HandlePlayerUnLearnCommand(), and tele_commandscript::HandleTeleNameCommand().
GetConnectedPlayer()
Player* Acore::ChatCommands::PlayerIdentifier::GetConnectedPlayer () const inline
Definition at line 183 of file ChatCommandTags.h.
 { return _player; }
Referenced by tele_commandscript::DoNameTeleport(), and character_commandscript::HandleCharacterEraseCommand().
GetGUID()
ObjectGuid Acore::ChatCommands::PlayerIdentifier::GetGUID () const inline
Definition at line 181 of file ChatCommandTags.h.
 { return _guid; }
Referenced by tele_commandscript::DoNameTeleport(), character_commandscript::HandleCharacterEraseCommand(), and character_commandscript::HandlePDumpWriteCommand().
GetName()
std::string const& Acore::ChatCommands::PlayerIdentifier::GetName () const inline
Definition at line 180 of file ChatCommandTags.h.
 { return _name; }
Referenced by tele_commandscript::DoNameTeleport(), and character_commandscript::HandleCharacterEraseCommand().
IsConnected()
bool Acore::ChatCommands::PlayerIdentifier::IsConnected () const inline
Definition at line 182 of file ChatCommandTags.h.
 { return (_player != nullptr); }
operator ObjectGuid()
Acore::ChatCommands::PlayerIdentifier::operator ObjectGuid () const inline
Definition at line 176 of file ChatCommandTags.h.
 { return _guid; }
operator std::string const &()
Acore::ChatCommands::PlayerIdentifier::operator std::string const & () const inline
Definition at line 177 of file ChatCommandTags.h.
 { return _name; }
operator std::string_view()
Acore::ChatCommands::PlayerIdentifier::operator std::string_view () const inline
Definition at line 178 of file ChatCommandTags.h.
 { return _name; }
TryConsume()
ChatCommandResult Acore::ChatCommands::PlayerIdentifier::TryConsume (ChatHandler const * handler, std::string_view args)
Definition at line 90 of file ChatCommandTags.cpp.
 {
     Variant<Hyperlink<player>, ObjectGuid::LowType, std::string_view> val;
     ChatCommandResult next = ArgInfo<decltype(val)>::TryConsume(val, handler, args);
     if (!next)
         return next;
     if (val.holds_alternative<ObjectGuid::LowType>())
     {
         _guid = ObjectGuid::Create<HighGuid::Player>(val.get<ObjectGuid::LowType>());
         if ((_player = ObjectAccessor::FindPlayerByLowGUID(_guid.GetCounter())))
             _name = _player->GetName();
         else if (!sObjectMgr->GetPlayerNameByGUID(_guid.GetCounter(), _name))
             return FormatAcoreString(handler, LANG_CMDPARSER_CHAR_GUID_NO_EXIST, _guid.ToString().c_str());
         return next;
     }
     else
     {
         if (val.holds_alternative<Hyperlink<player>>())
             _name.assign(static_cast<std::string_view>(val.get<Hyperlink<player>>()));
         else
             _name.assign(val.get<std::string_view>());
         if (!normalizePlayerName(_name))
             return FormatAcoreString(handler, LANG_CMDPARSER_CHAR_NAME_INVALID, STRING_VIEW_FMT_ARG(_name));
         if ((_player = ObjectAccessor::FindPlayerByName(_name)))
             _guid = _player->GetGUID();
         else if (!(_guid = sObjectMgr->GetPlayerGUIDByName(_name)))
             return FormatAcoreString(handler, LANG_CMDPARSER_CHAR_NAME_NO_EXIST, STRING_VIEW_FMT_ARG(_name));
         return next;
     }
 }
References ObjectAccessor::FindPlayerByLowGUID(), ObjectAccessor::FindPlayerByName(), Acore::Impl::ChatCommands::FormatAcoreString(), Acore::ChatCommands::Variant< T1, Ts >::get(), Acore::ChatCommands::Variant< T1, Ts >::holds_alternative(), LANG_CMDPARSER_CHAR_GUID_NO_EXIST, LANG_CMDPARSER_CHAR_NAME_INVALID, LANG_CMDPARSER_CHAR_NAME_NO_EXIST, next(), normalizePlayerName(), sObjectMgr, and STRING_VIEW_FMT_ARG.
Member Data Documentation
_guid
ObjectGuid Acore::ChatCommands::PlayerIdentifier::_guid private
Definition at line 199 of file ChatCommandTags.h.
_name
std::string Acore::ChatCommands::PlayerIdentifier::_name private
Definition at line 198 of file ChatCommandTags.h.
_player
Player* Acore::ChatCommands::PlayerIdentifier::_player private
Definition at line 200 of file ChatCommandTags.h.
The documentation for this struct was generated from the following files:
src/server/game/Chat/ChatCommands/ChatCommandTags.h
src/server/game/Chat/ChatCommands/ChatCommandTags.cpp