Azerotcore-wotlk: G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator Class Reference
G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator Class Reference
#include <PointHashGrid.h>
Public Member Functions
bool operator!= (const SphereIterator &other) const
bool operator== (const SphereIterator &other) const
SphereIterator & operator++ ()
SphereIterator operator++ (int)
const Value & operator* () const
const Value * operator-> () const
operator Value * () const
bool G3D_DEPRECATED hasMore () const
bool isValid () const
Private Member Functions
SphereIterator ()
void advance ()
SphereIterator (const ThisType *grid, const Sphere &sphere)
const Value & value () const
SphereIterator & operator= (const SphereIterator &)
Static Private Member Functions
static AABox getBoundingBox (const Sphere &s)
Private Attributes
bool m_isEnd
Sphere m_sphere
BoxIterator m_boxIterator
Friends
class ThisType
Detailed Description
template<class Value, class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>>
class G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator
Definition at line 716 of file PointHashGrid.h.
Constructor & Destructor Documentation
SphereIterator() [1/2]
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::SphereIterator () inline private
Definition at line 725 of file PointHashGrid.h.
 : m_isEnd(true) {}
SphereIterator() [2/2]
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::SphereIterator (const ThisType * grid, const Sphere & sphere) inline private
Definition at line 749 of file PointHashGrid.h.
                                                                    :
             m_isEnd(false),
             m_sphere(sphere),
             m_boxIterator(grid, false, getBoundingBox(sphere)) {
             // Find the first element that is actually in the sphere,
             // not just the box.
             advance();
         }
References G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::advance().
Member Function Documentation
advance()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> void G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::advance () inline private
Definition at line 727 of file PointHashGrid.h.
{
             if (! m_boxIterator.isValid()) {
                 m_isEnd = true;
                 return;
             }
             while (! m_sphere.contains(m_boxIterator.position())) {
                 ++m_boxIterator;
                 if (! m_boxIterator.isValid()) {
                     m_isEnd = true;
                     return;
                 }
             }
         }
References G3D::Sphere::contains(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::isValid(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::m_boxIterator, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::m_isEnd, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::m_sphere, and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::BoxIterator::position().
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::operator++(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::SphereIterator().
getBoundingBox()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> static AABox G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::getBoundingBox (const Sphere & s) inline static private
Definition at line 743 of file PointHashGrid.h.
{
             AABox box;
             s.getBounds(box);
             return box;
         }
References G3D::Sphere::getBounds().
hasMore()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> bool G3D_DEPRECATED G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::hasMore () const inline
Deprecated:
use isValid
Definition at line 809 of file PointHashGrid.h.
{
             return ! m_isEnd;
         }
References G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::m_isEnd.
isValid()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> bool G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::isValid () const inline
Definition at line 813 of file PointHashGrid.h.
{
             return ! m_isEnd;
         }
References G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::m_isEnd.
Referenced by G3D::_internal::WeldHelper::getIndex(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::getIntersectingMembers(), and G3D::_internal::WeldHelper::smoothNormals().
operator Value *()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::operator Value * () const inline
Definition at line 806 of file PointHashGrid.h.
 { return &value(); }
operator!=()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> bool G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::operator!= (const SphereIterator & other) const inline
Definition at line 772 of file PointHashGrid.h.
{
             if (other.m_isEnd && m_isEnd) {
                 return false;
             } else {
                 return
                     (m_isEnd         != other.m_isEnd) ||
                     (m_sphere        != other.m_sphere) ||
                     (m_boxIterator   != other.m_boxIterator);
             }
         }
References G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::m_boxIterator, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::m_isEnd, and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::m_sphere.
operator*()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> const Value& G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::operator* () const inline
Definition at line 804 of file PointHashGrid.h.
 { return  value(); }
References G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::value().
operator++() [1/2]
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> SphereIterator& G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::operator++ () inline
Preincrement
Definition at line 788 of file PointHashGrid.h.
{
             debugAssert(! m_isEnd);
             ++m_boxIterator;
             advance();
             return *this;
         }
References G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::advance(), debugAssert, G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::m_boxIterator, and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::m_isEnd.
operator++() [2/2]
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> SphereIterator G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::operator++ (int) inline
Post increment (slower)
Definition at line 798 of file PointHashGrid.h.
{
             Iterator old = *this;
             ++(*this);
             return old;
         }
operator->()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> const Value* G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::operator-> () const inline
Definition at line 805 of file PointHashGrid.h.
 { return &value(); }
References G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::value().
operator=()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> SphereIterator& G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::operator= (const SphereIterator &) private
operator==()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> bool G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::operator== (const SphereIterator & other) const inline
Definition at line 783 of file PointHashGrid.h.
{
             return !(*this != other);
         }
value()
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> const Value& G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::value () const inline private
Definition at line 759 of file PointHashGrid.h.
{
             return *m_boxIterator;
         }
References G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::m_boxIterator.
Referenced by G3D::PointHashGrid< G3D::_internal::VNTi >::SphereIterator::operator G3D::_internal::VNTi *(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::operator*(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::operator->().
Friends And Related Function Documentation
ThisType
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> friend class ThisType friend
Definition at line 719 of file PointHashGrid.h.
Member Data Documentation
m_boxIterator
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> BoxIterator G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::m_boxIterator private
Definition at line 723 of file PointHashGrid.h.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::advance(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::operator!=(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::operator++(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::value().
m_isEnd
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> bool G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::m_isEnd private
Definition at line 721 of file PointHashGrid.h.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::advance(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::hasMore(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::isValid(), G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::operator!=(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::operator++().
m_sphere
template<class Value , class PosFunc = PositionTrait<Value>, class EqualsFunc = EqualsTrait<Value>> Sphere G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::m_sphere private
Definition at line 722 of file PointHashGrid.h.
Referenced by G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::advance(), and G3D::PointHashGrid< Value, PosFunc, EqualsFunc >::SphereIterator::operator!=().
The documentation for this class was generated from the following file:
deps/g3dlite/include/G3D/PointHashGrid.h