Azerotcore-wotlk: Acore::WorldObjectSearcher< Check > Struct Template Reference
Acore::WorldObjectSearcher< Check > Struct Template Reference
#include <GridNotifiers.h>
Public Member Functions
WorldObjectSearcher (WorldObject const *searcher, WorldObject *&result, Check &check, uint32 mapTypeMask=GRID_MAP_TYPE_MASK_ALL)
void Visit (GameObjectMapType &m)
void Visit (PlayerMapType &m)
void Visit (CreatureMapType &m)
void Visit (CorpseMapType &m)
void Visit (DynamicObjectMapType &m)
template<class NOT_INTERESTED >
void Visit (GridRefMgr< NOT_INTERESTED > &)
Public Attributes
uint32 i_mapTypeMask
uint32 i_phaseMask
WorldObject *& i_object
Check & i_check
Detailed Description
template<class Check>
struct Acore::WorldObjectSearcher< Check >
Definition at line 169 of file GridNotifiers.h.
Constructor & Destructor Documentation
WorldObjectSearcher()
template<class Check > Acore::WorldObjectSearcher< Check >::WorldObjectSearcher (WorldObject const * searcher, WorldObject *& result, Check & check, uint32 mapTypeMask = GRID_MAP_TYPE_MASK_ALL) inline
Definition at line 176 of file GridNotifiers.h.
             : i_mapTypeMask(mapTypeMask), i_phaseMask(searcher->GetPhaseMask()), i_object(result), i_check(check) {}
Member Function Documentation
Visit() [1/6]
template<class Check > void Acore::WorldObjectSearcher< Check >::Visit (CorpseMapType & m)
Definition at line 121 of file GridNotifiersImpl.h.
 {
     if (!(i_mapTypeMask & GRID_MAP_TYPE_MASK_CORPSE))
         return;
     // already found
     if (i_object)
         return;
     for (CorpseMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
     {
         if (!itr->GetSource()->InSamePhase(i_phaseMask))
             continue;
         if (i_check(itr->GetSource()))
         {
             i_object = itr->GetSource();
             return;
         }
     }
 }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), and GRID_MAP_TYPE_MASK_CORPSE.
Visit() [2/6]
template<class Check > void Acore::WorldObjectSearcher< Check >::Visit (CreatureMapType & m)
Definition at line 98 of file GridNotifiersImpl.h.
 {
     if (!(i_mapTypeMask & GRID_MAP_TYPE_MASK_CREATURE))
         return;
     // already found
     if (i_object)
         return;
     for (CreatureMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
     {
         if (!itr->GetSource()->InSamePhase(i_phaseMask))
             continue;
         if (i_check(itr->GetSource()))
         {
             i_object = itr->GetSource();
             return;
         }
     }
 }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), and GRID_MAP_TYPE_MASK_CREATURE.
Visit() [3/6]
template<class Check > void Acore::WorldObjectSearcher< Check >::Visit (DynamicObjectMapType & m)
Definition at line 144 of file GridNotifiersImpl.h.
 {
     if (!(i_mapTypeMask & GRID_MAP_TYPE_MASK_DYNAMICOBJECT))
         return;
     // already found
     if (i_object)
         return;
     for (DynamicObjectMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
     {
         if (!itr->GetSource()->InSamePhase(i_phaseMask))
             continue;
         if (i_check(itr->GetSource()))
         {
             i_object = itr->GetSource();
             return;
         }
     }
 }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), and GRID_MAP_TYPE_MASK_DYNAMICOBJECT.
Visit() [4/6]
template<class Check > void Acore::WorldObjectSearcher< Check >::Visit (GameObjectMapType & m)
Definition at line 52 of file GridNotifiersImpl.h.
 {
     if (!(i_mapTypeMask & GRID_MAP_TYPE_MASK_GAMEOBJECT))
         return;
     // already found
     if (i_object)
         return;
     for (GameObjectMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
     {
         if (!itr->GetSource()->InSamePhase(i_phaseMask))
             continue;
         if (i_check(itr->GetSource()))
         {
             i_object = itr->GetSource();
             return;
         }
     }
 }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), and GRID_MAP_TYPE_MASK_GAMEOBJECT.
Visit() [5/6]
template<class Check > template<class NOT_INTERESTED > void Acore::WorldObjectSearcher< Check >::Visit (GridRefMgr< NOT_INTERESTED > &) inline
Definition at line 185 of file GridNotifiers.h.
 {}
Visit() [6/6]
template<class Check > void Acore::WorldObjectSearcher< Check >::Visit (PlayerMapType & m)
Definition at line 75 of file GridNotifiersImpl.h.
 {
     if (!(i_mapTypeMask & GRID_MAP_TYPE_MASK_PLAYER))
         return;
     // already found
     if (i_object)
         return;
     for (PlayerMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
     {
         if (!itr->GetSource()->InSamePhase(i_phaseMask))
             continue;
         if (i_check(itr->GetSource()))
         {
             i_object = itr->GetSource();
             return;
         }
     }
 }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), and GRID_MAP_TYPE_MASK_PLAYER.
Member Data Documentation
i_check
template<class Check > Check& Acore::WorldObjectSearcher< Check >::i_check
Definition at line 174 of file GridNotifiers.h.
i_mapTypeMask
template<class Check > uint32 Acore::WorldObjectSearcher< Check >::i_mapTypeMask
Definition at line 171 of file GridNotifiers.h.
i_object
template<class Check > WorldObject*& Acore::WorldObjectSearcher< Check >::i_object
Definition at line 173 of file GridNotifiers.h.
i_phaseMask
template<class Check > uint32 Acore::WorldObjectSearcher< Check >::i_phaseMask
Definition at line 172 of file GridNotifiers.h.
The documentation for this struct was generated from the following files:
src/server/game/Grids/Notifiers/GridNotifiers.h
src/server/game/Grids/Notifiers/GridNotifiersImpl.h