Azerotcore-wotlk: spell_gen_defend Class Reference
spell_gen_defend Class Reference
Private Member Functions
PrepareAuraScript (spell_gen_defend)
bool Validate (SpellInfo const *) override
void RefreshVisualShields (AuraEffect const *aurEff, AuraEffectHandleModes)
void RemoveVisualShields (AuraEffect const *, AuraEffectHandleModes)
void RemoveDummyFromDriver (AuraEffect const *, AuraEffectHandleModes)
void Register () override
Additional Inherited Members
Public Member Functions inherited from AuraScript
AuraScript ()
bool _Validate (SpellInfo const *entry) override
bool _Load (Aura *aura)
void _PrepareScriptCall (AuraScriptHookType hookType, AuraApplication const *aurApp=nullptr)
void _FinishScriptCall ()
bool _IsDefaultActionPrevented ()
void PreventDefaultAction ()
SpellInfo const * GetSpellInfo () const
uint32 GetId () const
ObjectGuid GetCasterGUID () const
Unit * GetCaster () const
WorldObject * GetOwner () const
Unit * GetUnitOwner () const
DynamicObject * GetDynobjOwner () const
void Remove (uint32 removeMode=0)
Aura * GetAura () const
AuraObjectType GetType () const
int32 GetDuration () const
void SetDuration (int32 duration, bool withMods=false)
void RefreshDuration ()
time_t GetApplyTime () const
int32 GetMaxDuration () const
void SetMaxDuration (int32 duration)
int32 CalcMaxDuration () const
bool IsExpired () const
bool IsPermanent () const
uint8 GetCharges () const
void SetCharges (uint8 charges)
uint8 CalcMaxCharges () const
bool ModCharges (int8 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool DropCharge (AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
uint8 GetStackAmount () const
void SetStackAmount (uint8 num)
bool ModStackAmount (int32 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool IsPassive () const
bool IsDeathPersistent () const
bool HasEffect (uint8 effIndex) const
AuraEffect * GetEffect (uint8 effIndex) const
bool HasEffectType (AuraType type) const
Unit * GetTarget () const
AuraApplication const * GetTargetApplication () const
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from AuraScript
HookList< CheckAreaTargetHandler > DoCheckAreaTarget
HookList< AuraDispelHandler > OnDispel
HookList< AuraDispelHandler > AfterDispel
HookList< EffectApplyHandler > OnEffectApply
HookList< EffectApplyHandler > AfterEffectApply
HookList< EffectApplyHandler > OnEffectRemove
HookList< EffectApplyHandler > AfterEffectRemove
HookList< EffectPeriodicHandler > OnEffectPeriodic
HookList< EffectUpdatePeriodicHandler > OnEffectUpdatePeriodic
HookList< EffectCalcAmountHandler > DoEffectCalcAmount
HookList< EffectCalcPeriodicHandler > DoEffectCalcPeriodic
HookList< EffectCalcSpellModHandler > DoEffectCalcSpellMod
HookList< EffectAbsorbHandler > OnEffectAbsorb
HookList< EffectAbsorbHandler > AfterEffectAbsorb
HookList< EffectManaShieldHandler > OnEffectManaShield
HookList< EffectManaShieldHandler > AfterEffectManaShield
HookList< EffectSplitHandler > OnEffectSplit
HookList< CheckProcHandler > DoCheckProc
HookList< AuraProcHandler > DoPrepareProc
HookList< AuraProcHandler > OnProc
HookList< AuraProcHandler > AfterProc
HookList< EffectProcHandler > OnEffectProc
HookList< EffectProcHandler > AfterEffectProc
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Definition at line 2949 of file spell_generic.cpp.
Member Function Documentation
PrepareAuraScript()
spell_gen_defend::PrepareAuraScript (spell_gen_defend) private
RefreshVisualShields()
void spell_gen_defend::RefreshVisualShields (AuraEffect const * aurEff, AuraEffectHandleModes) inline private
Definition at line 2963 of file spell_generic.cpp.
     {
         if (GetCaster())
         {
             Unit* target = GetTarget();
             for (uint8 i = 0; i < GetSpellInfo()->StackAmount; ++i)
                 target->RemoveAurasDueToSpell(SPELL_VISUAL_SHIELD_1 + i);
             target->CastSpell(target, SPELL_VISUAL_SHIELD_1 + GetAura()->GetStackAmount() - 1, true, nullptr, aurEff);
         }
         else
             GetTarget()->RemoveAurasDueToSpell(GetId());
     }
References Unit::CastSpell(), AuraScript::GetAura(), AuraScript::GetCaster(), AuraScript::GetId(), AuraScript::GetSpellInfo(), Aura::GetStackAmount(), AuraScript::GetTarget(), Unit::RemoveAurasDueToSpell(), SPELL_VISUAL_SHIELD_1, and SpellInfo::StackAmount.
Referenced by Register().
Register()
void spell_gen_defend::Register () inline override private virtual
Implements _SpellScript.
Definition at line 2992 of file spell_generic.cpp.
     {
         SpellInfo const* spell = sSpellMgr->AssertSpellInfo(m_scriptSpellId);
         // Defend spells cast by NPCs (add visuals)
         if (spell->Effects[EFFECT_0].ApplyAuraName == SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN)
         {
             AfterEffectApply += AuraEffectApplyFn(spell_gen_defend::RefreshVisualShields, EFFECT_0, SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN, AURA_EFFECT_HANDLE_REAL_OR_REAPPLY_MASK);
             OnEffectRemove += AuraEffectRemoveFn(spell_gen_defend::RemoveVisualShields, EFFECT_0, SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN, AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK);
         }
         // Remove Defend spell from player when he dismounts
         if (spell->Effects[EFFECT_2].ApplyAuraName == SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN)
             OnEffectRemove += AuraEffectRemoveFn(spell_gen_defend::RemoveDummyFromDriver, EFFECT_2, SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN, AURA_EFFECT_HANDLE_REAL);
         // Defend spells cast by players (add/remove visuals)
         if (spell->Effects[EFFECT_1].ApplyAuraName == SPELL_AURA_DUMMY)
         {
             AfterEffectApply += AuraEffectApplyFn(spell_gen_defend::RefreshVisualShields, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL_OR_REAPPLY_MASK);
             OnEffectRemove += AuraEffectRemoveFn(spell_gen_defend::RemoveVisualShields, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK);
         }
     }
References AuraScript::AfterEffectApply, AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_REAL, AURA_EFFECT_HANDLE_REAL_OR_REAPPLY_MASK, AuraEffectApplyFn, AuraEffectRemoveFn, EFFECT_0, EFFECT_1, EFFECT_2, SpellInfo::Effects, _SpellScript::m_scriptSpellId, AuraScript::OnEffectRemove, RefreshVisualShields(), RemoveDummyFromDriver(), RemoveVisualShields(), SPELL_AURA_DUMMY, SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN, and sSpellMgr.
RemoveDummyFromDriver()
void spell_gen_defend::RemoveDummyFromDriver (AuraEffect const * , AuraEffectHandleModes) inline private
Definition at line 2984 of file spell_generic.cpp.
     {
         if (Unit* caster = GetCaster())
             if (TempSummon* vehicle = caster->ToTempSummon())
                 if (Unit* rider = vehicle->GetSummonerUnit())
                     rider->RemoveAurasDueToSpell(GetId());
     }
References AuraScript::GetCaster(), AuraScript::GetId(), and Unit::ToTempSummon().
Referenced by Register().
RemoveVisualShields()
void spell_gen_defend::RemoveVisualShields (AuraEffect const * , AuraEffectHandleModes) inline private
Definition at line 2978 of file spell_generic.cpp.
     {
         for (uint8 i = 0; i < GetSpellInfo()->StackAmount; ++i)
             GetTarget()->RemoveAurasDueToSpell(SPELL_VISUAL_SHIELD_1 + i);
     }
References AuraScript::GetSpellInfo(), AuraScript::GetTarget(), Unit::RemoveAurasDueToSpell(), SPELL_VISUAL_SHIELD_1, and SpellInfo::StackAmount.
Referenced by Register().
Validate()
bool spell_gen_defend::Validate (SpellInfo const *) inline override private virtual
Reimplemented from _SpellScript.
Definition at line 2953 of file spell_generic.cpp.
     {
         return ValidateSpellInfo(
             {
                 SPELL_VISUAL_SHIELD_1,
                 SPELL_VISUAL_SHIELD_2,
                 SPELL_VISUAL_SHIELD_3
             });
     }
References SPELL_VISUAL_SHIELD_1, SPELL_VISUAL_SHIELD_2, SPELL_VISUAL_SHIELD_3, and _SpellScript::ValidateSpellInfo().
The documentation for this class was generated from the following file:
src/server/scripts/Spells/spell_generic.cpp