Azerotcore-wotlk: AchievementGlobalMgr Class Reference
AchievementGlobalMgr Class Reference
#include <AchievementMgr.h>
Public Member Functions
bool IsStatisticCriteria (AchievementCriteriaEntry const *achievementCriteria) const
bool isStatisticAchievement (AchievementEntry const *achievement) const
AchievementCriteriaEntryList const * GetAchievementCriteriaByType (AchievementCriteriaTypes type) const
AchievementCriteriaEntryList const * GetSpecialAchievementCriteriaByType (AchievementCriteriaTypes type, uint32 val)
AchievementCriteriaEntryList const * GetAchievementCriteriaByCondition (AchievementCriteriaCondition condition, uint32 val)
AchievementCriteriaEntryList const & GetTimedAchievementCriteriaByType (AchievementCriteriaTimedTypes type) const
AchievementCriteriaEntryList const * GetAchievementCriteriaByAchievement (uint32 id) const
AchievementEntryList const * GetAchievementByReferencedId (uint32 id) const
AchievementReward const * GetAchievementReward (AchievementEntry const *achievement) const
AchievementRewardLocale const * GetAchievementRewardLocale (AchievementEntry const *achievement) const
AchievementCriteriaDataSet const * GetCriteriaDataSet (AchievementCriteriaEntry const *achievementCriteria) const
bool IsRealmCompleted (AchievementEntry const *achievement) const
void SetRealmCompleted (AchievementEntry const *achievement)
void LoadAchievementCriteriaList ()
void LoadAchievementCriteriaData ()
void LoadAchievementReferenceList ()
void LoadCompletedAchievements ()
void LoadRewards ()
void LoadRewardLocales ()
AchievementEntry const * GetAchievement (uint32 achievementId) const
Static Public Member Functions
static AchievementGlobalMgr * instance ()
Private Types
typedef std::unordered_map< uint32, std::chrono::system_clock::time_point > AllCompletedAchievements
Private Member Functions
AchievementGlobalMgr ()=default
~AchievementGlobalMgr ()=default
Private Attributes
AchievementCriteriaDataMap m_criteriaDataMap
AchievementCriteriaEntryList m_AchievementCriteriasByType [ACHIEVEMENT_CRITERIA_TYPE_TOTAL]
AchievementCriteriaEntryList m_AchievementCriteriasByTimedType [ACHIEVEMENT_TIMED_TYPE_MAX]
AchievementCriteriaListByAchievement m_AchievementCriteriaListByAchievement
AchievementListByReferencedId m_AchievementListByReferencedId
AllCompletedAchievements m_allCompletedAchievements
AchievementRewards m_achievementRewards
AchievementRewardLocales m_achievementRewardLocales
std::map< uint32, AchievementCriteriaEntryList > m_SpecialList [ACHIEVEMENT_CRITERIA_TYPE_TOTAL]
std::map< uint32, AchievementCriteriaEntryList > m_AchievementCriteriasByCondition [ACHIEVEMENT_CRITERIA_CONDITION_TOTAL]
Detailed Description
Definition at line 316 of file AchievementMgr.h.
Member Typedef Documentation
AllCompletedAchievements
typedef std::unordered_map<uint32 , std::chrono::system_clock::time_point > AchievementGlobalMgr::AllCompletedAchievements private
Definition at line 404 of file AchievementMgr.h.
Constructor & Destructor Documentation
AchievementGlobalMgr()
AchievementGlobalMgr::AchievementGlobalMgr () private default
~AchievementGlobalMgr()
AchievementGlobalMgr::~AchievementGlobalMgr () private default
Member Function Documentation
GetAchievement()
AchievementEntry const * AchievementGlobalMgr::GetAchievement (uint32 achievementId) const
Definition at line 2972 of file AchievementMgr.cpp.
 {
     return sAchievementStore.LookupEntry(achievementId);
 }
References sAchievementStore.
GetAchievementByReferencedId()
AchievementEntryList const* AchievementGlobalMgr::GetAchievementByReferencedId (uint32 id) const inline
Definition at line 357 of file AchievementMgr.h.
     {
         AchievementListByReferencedId::const_iterator itr = m_AchievementListByReferencedId.find(id);
         return itr != m_AchievementListByReferencedId.end() ? &itr->second : nullptr;
     }
References m_AchievementListByReferencedId.
GetAchievementCriteriaByAchievement()
AchievementCriteriaEntryList const* AchievementGlobalMgr::GetAchievementCriteriaByAchievement (uint32 id) const inline
Definition at line 351 of file AchievementMgr.h.
     {
         AchievementCriteriaListByAchievement::const_iterator itr = m_AchievementCriteriaListByAchievement.find(id);
         return itr != m_AchievementCriteriaListByAchievement.end() ? &itr->second : nullptr;
     }
References m_AchievementCriteriaListByAchievement.
GetAchievementCriteriaByCondition()
AchievementCriteriaEntryList const* AchievementGlobalMgr::GetAchievementCriteriaByCondition (AchievementCriteriaCondition condition, uint32 val) inline
Definition at line 339 of file AchievementMgr.h.
     {
         if (m_AchievementCriteriasByCondition[condition].find(val) != m_AchievementCriteriasByCondition[condition].end())
             return &m_AchievementCriteriasByCondition[condition][val];
         return nullptr;
     }
References find(), and m_AchievementCriteriasByCondition.
GetAchievementCriteriaByType()
AchievementCriteriaEntryList const* AchievementGlobalMgr::GetAchievementCriteriaByType (AchievementCriteriaTypes type) const inline
Definition at line 327 of file AchievementMgr.h.
     {
         return &m_AchievementCriteriasByType[type];
     }
References m_AchievementCriteriasByType.
GetAchievementReward()
AchievementReward const* AchievementGlobalMgr::GetAchievementReward (AchievementEntry const * achievement) const inline
Definition at line 363 of file AchievementMgr.h.
     {
         AchievementRewards::const_iterator iter = m_achievementRewards.find(achievement->ID);
         return iter != m_achievementRewards.end() ? &iter->second : nullptr;
     }
References AchievementEntry::ID, and m_achievementRewards.
GetAchievementRewardLocale()
AchievementRewardLocale const* AchievementGlobalMgr::GetAchievementRewardLocale (AchievementEntry const * achievement) const inline
Definition at line 369 of file AchievementMgr.h.
     {
         AchievementRewardLocales::const_iterator iter = m_achievementRewardLocales.find(achievement->ID);
         return iter != m_achievementRewardLocales.end() ? &iter->second : nullptr;
     }
References AchievementEntry::ID, and m_achievementRewardLocales.
GetCriteriaDataSet()
AchievementCriteriaDataSet const* AchievementGlobalMgr::GetCriteriaDataSet (AchievementCriteriaEntry const * achievementCriteria) const inline
Definition at line 375 of file AchievementMgr.h.
     {
         AchievementCriteriaDataMap::const_iterator iter = m_criteriaDataMap.find(achievementCriteria->ID);
         return iter != m_criteriaDataMap.end() ? &iter->second : nullptr;
     }
References AchievementCriteriaEntry::ID, and m_criteriaDataMap.
Referenced by LoadAchievementCriteriaData().
GetSpecialAchievementCriteriaByType()
AchievementCriteriaEntryList const* AchievementGlobalMgr::GetSpecialAchievementCriteriaByType (AchievementCriteriaTypes type, uint32 val) inline
Definition at line 332 of file AchievementMgr.h.
     {
         if (m_SpecialList[type].find(val) != m_SpecialList[type].end())
             return &m_SpecialList[type][val];
         return nullptr;
     }
References find(), and m_SpecialList.
GetTimedAchievementCriteriaByType()
AchievementCriteriaEntryList const& AchievementGlobalMgr::GetTimedAchievementCriteriaByType (AchievementCriteriaTimedTypes type) const inline
Definition at line 346 of file AchievementMgr.h.
     {
         return m_AchievementCriteriasByTimedType[type];
     }
References m_AchievementCriteriasByTimedType.
instance()
AchievementGlobalMgr * AchievementGlobalMgr::instance () static
Definition at line 2384 of file AchievementMgr.cpp.
 {
     static AchievementGlobalMgr instance;
     return &instance;
 }
IsRealmCompleted()
bool AchievementGlobalMgr::IsRealmCompleted (AchievementEntry const * achievement) const
Definition at line 2418 of file AchievementMgr.cpp.
 {
     auto itr = m_allCompletedAchievements.find(achievement->ID);
     if (itr == m_allCompletedAchievements.end())
         return false;
     if (itr->second == std::chrono::system_clock::time_point::min())
         return false;
     if (!sScriptMgr->IsRealmCompleted(this, achievement, itr->second))
         return false;
     if (itr->second == std::chrono::system_clock::time_point::max())
         return true;
     // Allow completing the realm first kill for entire minute after first person did it
     // it may allow more than one group to achieve it (highly unlikely)
     // but apparently this is how blizz handles it as well
     if (achievement->flags & ACHIEVEMENT_FLAG_REALM_FIRST_KILL)
         return (std::chrono::system_clock::now() - itr->second) > std::chrono::minutes(1);
     sScriptMgr->SetRealmCompleted(achievement);
     return true;
 }
References ACHIEVEMENT_FLAG_REALM_FIRST_KILL, AchievementEntry::flags, AchievementEntry::ID, m_allCompletedAchievements, max, min, G3D::units::minutes(), and sScriptMgr.
Referenced by SetRealmCompleted().
isStatisticAchievement()
bool AchievementGlobalMgr::isStatisticAchievement (AchievementEntry const * achievement) const
Definition at line 2395 of file AchievementMgr.cpp.
 {
     if (!achievement)
         return false;
     AchievementCategoryEntry const* cat = sAchievementCategoryStore.LookupEntry(achievement->categoryId);
     do
     {
         switch(cat->ID)
         {
             case ACHIEVEMENT_CATEGORY_STATISTICS:
                 return true;
             case ACHIEVEMENT_CATEOGRY_GENERAL:
                 return false;
             default:
                 cat = sAchievementCategoryStore.LookupEntry(cat->parentCategory);
                 break;
         }
     } while (cat);
     return false;
 }
References ACHIEVEMENT_CATEGORY_STATISTICS, ACHIEVEMENT_CATEOGRY_GENERAL, AchievementEntry::categoryId, AchievementCategoryEntry::ID, AchievementCategoryEntry::parentCategory, and sAchievementCategoryStore.
Referenced by IsStatisticCriteria().
IsStatisticCriteria()
bool AchievementGlobalMgr::IsStatisticCriteria (AchievementCriteriaEntry const * achievementCriteria) const
Definition at line 2390 of file AchievementMgr.cpp.
 {
     return isStatisticAchievement(sAchievementStore.LookupEntry(achievementCriteria->referredAchievement));
 }
References isStatisticAchievement(), AchievementCriteriaEntry::referredAchievement, and sAchievementStore.
LoadAchievementCriteriaData()
void AchievementGlobalMgr::LoadAchievementCriteriaData ()
Definition at line 2629 of file AchievementMgr.cpp.
 {
     uint32 oldMSTime = getMSTime();
     m_criteriaDataMap.clear();                              // need for reload case
     QueryResult result = WorldDatabase.Query("SELECT criteria_id, type, value1, value2, ScriptName FROM achievement_criteria_data");
     if (!result)
     {
         LOG_INFO("server.loading", ">> Loaded 0 additional achievement criteria data. DB table `achievement_criteria_data` is empty.");
         LOG_INFO("server.loading", " ");
         return;
     }
     uint32 count = 0;
     do
     {
         Field* fields = result->Fetch();
         uint32 criteria_id = fields[0].GetUInt32();
         AchievementCriteriaEntry const* criteria = sAchievementCriteriaStore.LookupEntry(criteria_id);
         if (!criteria)
         {
             LOG_ERROR("sql.sql", "Table `achievement_criteria_data` has data for non-existing criteria (Entry: %u), ignore.", criteria_id);
             continue;
         }
         uint32 dataType = fields[1].GetUInt8();
         std::string scriptName = fields[4].GetString();
         uint32 scriptId = 0;
         if (scriptName.length()) // not empty
         {
             if (dataType != ACHIEVEMENT_CRITERIA_DATA_TYPE_SCRIPT)
                 LOG_ERROR("sql.sql", "Table `achievement_criteria_data` has ScriptName set for non-scripted data type (Entry: %u, type %u), useless data.", criteria_id, dataType);
             else
                 scriptId = sObjectMgr->GetScriptId(scriptName.c_str());
         }
         AchievementCriteriaData data(dataType, fields[2].GetUInt32(), fields[3].GetUInt32(), scriptId);
         if (!data.IsValid(criteria))
             continue;
         // this will allocate empty data set storage
         AchievementCriteriaDataSet& dataSet = m_criteriaDataMap[criteria_id];
         dataSet.SetCriteriaId(criteria_id);
         // add real data only for not NONE data types
         if (data.dataType != ACHIEVEMENT_CRITERIA_DATA_TYPE_NONE)
             dataSet.Add(data);
         // counting data by and data types
         ++count;
     } while (result->NextRow());
     // post loading checks
     for (uint32 entryId = 0; entryId < sAchievementCriteriaStore.GetNumRows(); ++entryId)
     {
         AchievementCriteriaEntry const* criteria = sAchievementCriteriaStore.LookupEntry(entryId);
         if (!criteria)
             continue;
         switch (criteria->requiredType)
         {
             case ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE:
             case ACHIEVEMENT_CRITERIA_TYPE_WIN_BG:
             case ACHIEVEMENT_CRITERIA_TYPE_FALL_WITHOUT_DYING:
             case ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET:
             case ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL:
             case ACHIEVEMENT_CRITERIA_TYPE_BG_OBJECTIVE_CAPTURE:
             case ACHIEVEMENT_CRITERIA_TYPE_HONORABLE_KILL:
             case ACHIEVEMENT_CRITERIA_TYPE_EQUIP_EPIC_ITEM:
             case ACHIEVEMENT_CRITERIA_TYPE_ROLL_NEED_ON_LOOT:
             case ACHIEVEMENT_CRITERIA_TYPE_ROLL_GREED_ON_LOOT:
             case ACHIEVEMENT_CRITERIA_TYPE_GET_KILLING_BLOWS:
             case ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET2:
             case ACHIEVEMENT_CRITERIA_TYPE_SPECIAL_PVP_KILL:
             case ACHIEVEMENT_CRITERIA_TYPE_ON_LOGIN:
             case ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE_TYPE:
             case ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL2:
                 // achievement requires db data
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUEST:
                 {
                     AchievementEntry const* achievement = sAchievementStore.LookupEntry(criteria->referredAchievement);
                     if (!achievement)
                         continue;
                     // exist many achievements with this criteria, use at this moment hardcoded check to skil simple case
                     if (achievement->ID == 1282)
                         break;
                     continue;
                 }
             case ACHIEVEMENT_CRITERIA_TYPE_WIN_RATED_ARENA: // need skip generic cases
                 if (criteria->additionalRequirements[0].additionalRequirement_type != ACHIEVEMENT_CRITERIA_CONDITION_NO_LOSE)
                     continue;
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_DO_EMOTE:        // need skip generic cases
                 if (criteria->do_emote.count == 0)
                     continue;
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_WIN_DUEL:        // skip statistics
                 if (criteria->win_duel.duelCount == 0)
                     continue;
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_LOOT_TYPE:       // need skip generic cases
                 if (criteria->loot_type.lootTypeCount != 1)
                     continue;
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_DAILY_QUEST:
             case ACHIEVEMENT_CRITERIA_TYPE_USE_ITEM:        // only Children's Week achievements
                 {
                     AchievementEntry const* achievement = sAchievementStore.LookupEntry(criteria->referredAchievement);
                     if (!achievement)
                         continue;
                     if (achievement->categoryId != CATEGORY_CHILDRENS_WEEK)
                         continue;
                     break;
                 }
             default:                                        // type not use DB data, ignore
                 continue;
         }
         if (!GetCriteriaDataSet(criteria) && !DisableMgr::IsDisabledFor(DISABLE_TYPE_ACHIEVEMENT_CRITERIA, entryId, nullptr))
             LOG_ERROR("sql.sql", "Table `achievement_criteria_data` does not have expected data for criteria (Entry: %u Type: %u) for achievement %u.", criteria->ID, criteria->requiredType, criteria->referredAchievement);
     }
     LOG_INFO("server.loading", ">> Loaded %u additional achievement criteria data in %u ms", count, GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
 }
References ACHIEVEMENT_CRITERIA_CONDITION_NO_LOSE, ACHIEVEMENT_CRITERIA_DATA_TYPE_NONE, ACHIEVEMENT_CRITERIA_DATA_TYPE_SCRIPT, ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET2, ACHIEVEMENT_CRITERIA_TYPE_BG_OBJECTIVE_CAPTURE, ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL, ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL2, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_DAILY_QUEST, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUEST, ACHIEVEMENT_CRITERIA_TYPE_DO_EMOTE, ACHIEVEMENT_CRITERIA_TYPE_EQUIP_EPIC_ITEM, ACHIEVEMENT_CRITERIA_TYPE_FALL_WITHOUT_DYING, ACHIEVEMENT_CRITERIA_TYPE_GET_KILLING_BLOWS, ACHIEVEMENT_CRITERIA_TYPE_HONORABLE_KILL, ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE_TYPE, ACHIEVEMENT_CRITERIA_TYPE_LOOT_TYPE, ACHIEVEMENT_CRITERIA_TYPE_ON_LOGIN, ACHIEVEMENT_CRITERIA_TYPE_ROLL_GREED_ON_LOOT, ACHIEVEMENT_CRITERIA_TYPE_ROLL_NEED_ON_LOOT, ACHIEVEMENT_CRITERIA_TYPE_SPECIAL_PVP_KILL, ACHIEVEMENT_CRITERIA_TYPE_USE_ITEM, ACHIEVEMENT_CRITERIA_TYPE_WIN_BG, ACHIEVEMENT_CRITERIA_TYPE_WIN_DUEL, ACHIEVEMENT_CRITERIA_TYPE_WIN_RATED_ARENA, AchievementCriteriaDataSet::Add(), AchievementCriteriaEntry::additionalRequirement_type, AchievementCriteriaEntry::additionalRequirements, CATEGORY_CHILDRENS_WEEK, AchievementEntry::categoryId, count(), DISABLE_TYPE_ACHIEVEMENT_CRITERIA, AchievementCriteriaEntry::do_emote, GetCriteriaDataSet(), getMSTime(), GetMSTimeDiffToNow(), Field::GetString(), Field::GetUInt32(), Field::GetUInt8(), AchievementEntry::ID, AchievementCriteriaEntry::ID, DisableMgr::IsDisabledFor(), LOG_ERROR, LOG_INFO, AchievementCriteriaEntry::loot_type, m_criteriaDataMap, AchievementCriteriaEntry::referredAchievement, AchievementCriteriaEntry::requiredType, sAchievementCriteriaStore, sAchievementStore, AchievementCriteriaDataSet::SetCriteriaId(), sObjectMgr, AchievementCriteriaEntry::win_duel, and WorldDatabase.
LoadAchievementCriteriaList()
void AchievementGlobalMgr::LoadAchievementCriteriaList ()
Definition at line 2453 of file AchievementMgr.cpp.
 {
     uint32 oldMSTime = getMSTime();
     if (sAchievementCriteriaStore.GetNumRows() == 0)
     {
         LOG_INFO("server.loading", ">> Loaded 0 achievement criteria.");
         LOG_INFO("server.loading", " ");
         return;
     }
     uint32 loaded = 0;
     for (uint32 entryId = 0; entryId < sAchievementCriteriaStore.GetNumRows(); ++entryId)
     {
         AchievementCriteriaEntry const* criteria = sAchievementCriteriaStore.LookupEntry(entryId);
         if (!criteria)
             continue;
         m_AchievementCriteriasByType[criteria->requiredType].push_back(criteria);
         m_AchievementCriteriaListByAchievement[criteria->referredAchievement].push_back(criteria);
         if (criteria->additionalRequirements[0].additionalRequirement_type != ACHIEVEMENT_CRITERIA_CONDITION_NONE)
             m_AchievementCriteriasByCondition[criteria->additionalRequirements[0].additionalRequirement_type][criteria->additionalRequirements[0].additionalRequirement_value].push_back(criteria);
         if (criteria->additionalRequirements[1].additionalRequirement_type != ACHIEVEMENT_CRITERIA_CONDITION_NONE &&
                 criteria->additionalRequirements[1].additionalRequirement_type != criteria->additionalRequirements[0].additionalRequirement_type)
             m_AchievementCriteriasByCondition[criteria->additionalRequirements[1].additionalRequirement_type][criteria->additionalRequirements[1].additionalRequirement_value].push_back(criteria);
         switch (criteria->requiredType)
         {
             case ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE:
                 m_SpecialList[criteria->requiredType][criteria->kill_creature.creatureID].push_back(criteria);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_WIN_BG:
                 m_SpecialList[criteria->requiredType][criteria->win_bg.bgMapID].push_back(criteria);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_REACH_SKILL_LEVEL:
                 m_SpecialList[criteria->requiredType][criteria->reach_skill_level.skillID].push_back(criteria);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_ACHIEVEMENT:
                 m_SpecialList[criteria->requiredType][criteria->complete_achievement.linkedAchievement].push_back(criteria);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUESTS_IN_ZONE:
                 m_SpecialList[criteria->requiredType][criteria->complete_quests_in_zone.zoneID].push_back(criteria);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_BATTLEGROUND:
                 m_SpecialList[criteria->requiredType][criteria->complete_battleground.mapID].push_back(criteria);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_KILLED_BY_CREATURE:
                 m_SpecialList[criteria->requiredType][criteria->killed_by_creature.creatureEntry].push_back(criteria);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUEST:
                 m_SpecialList[criteria->requiredType][criteria->complete_quest.questID].push_back(criteria);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET:
                 m_SpecialList[criteria->requiredType][criteria->be_spell_target.spellID].push_back(criteria);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL:
                 m_SpecialList[criteria->requiredType][criteria->cast_spell.spellID].push_back(criteria);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_BG_OBJECTIVE_CAPTURE:
                 m_SpecialList[criteria->requiredType][criteria->bg_objective.objectiveId].push_back(criteria);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_HONORABLE_KILL_AT_AREA:
                 m_SpecialList[criteria->requiredType][criteria->honorable_kill_at_area.areaID].push_back(criteria);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_LEARN_SPELL:
                 m_SpecialList[criteria->requiredType][criteria->learn_spell.spellID].push_back(criteria);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_OWN_ITEM:
                 m_SpecialList[criteria->requiredType][criteria->own_item.itemID].push_back(criteria);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILL_LEVEL:
                 m_SpecialList[criteria->requiredType][criteria->learn_skill_level.skillID].push_back(criteria);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_USE_ITEM:
                 m_SpecialList[criteria->requiredType][criteria->use_item.itemID].push_back(criteria);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_LOOT_ITEM:
                 m_SpecialList[criteria->requiredType][criteria->own_item.itemID].push_back(criteria);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_EXPLORE_AREA:
                 {
                     WorldMapOverlayEntry const* worldOverlayEntry = sWorldMapOverlayStore.LookupEntry(criteria->explore_area.areaReference);
                     if (!worldOverlayEntry)
                         break;
                     for (uint8 j = 0; j < MAX_WORLD_MAP_OVERLAY_AREA_IDX; ++j)
                         if (worldOverlayEntry->areatableID[j])
{
                             bool valid = true;
                             for (uint8 i = 0; i < j; ++i)
                                 if (worldOverlayEntry->areatableID[j] == worldOverlayEntry->areatableID[i])
                                     valid = false;
                             if (valid)
                                 m_SpecialList[criteria->requiredType][worldOverlayEntry->areatableID[j]].push_back(criteria);
                         }
                 }
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_GAIN_REPUTATION:
                 m_SpecialList[criteria->requiredType][criteria->gain_reputation.factionID].push_back(criteria);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_EQUIP_EPIC_ITEM:
                 m_SpecialList[criteria->requiredType][criteria->equip_epic_item.itemSlot].push_back(criteria);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_HK_CLASS:
                 m_SpecialList[criteria->requiredType][criteria->hk_class.classID].push_back(criteria);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_HK_RACE:
                 m_SpecialList[criteria->requiredType][criteria->hk_race.raceID].push_back(criteria);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_DO_EMOTE:
                 m_SpecialList[criteria->requiredType][criteria->do_emote.emoteID].push_back(criteria);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_EQUIP_ITEM:
                 m_SpecialList[criteria->requiredType][criteria->equip_item.itemID].push_back(criteria);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_USE_GAMEOBJECT:
                 m_SpecialList[criteria->requiredType][criteria->use_gameobject.goEntry].push_back(criteria);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET2:
                 m_SpecialList[criteria->requiredType][criteria->be_spell_target.spellID].push_back(criteria);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_FISH_IN_GAMEOBJECT:
                 m_SpecialList[criteria->requiredType][criteria->fish_in_gameobject.goEntry].push_back(criteria);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILLLINE_SPELLS:
                 m_SpecialList[criteria->requiredType][criteria->learn_skillline_spell.skillLine].push_back(criteria);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_LOOT_TYPE:
                 m_SpecialList[criteria->requiredType][criteria->loot_type.lootType].push_back(criteria);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL2:
                 m_SpecialList[criteria->requiredType][criteria->cast_spell.spellID].push_back(criteria);
                 break;
             case ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILL_LINE:
                 m_SpecialList[criteria->requiredType][criteria->learn_skill_line.skillLine].push_back(criteria);
                 break;
         }
         if (criteria->timeLimit)
             m_AchievementCriteriasByTimedType[criteria->timedType].push_back(criteria);
         ++loaded;
     }
     LOG_INFO("server.loading", ">> Loaded %u achievement criteria in %u ms", loaded, GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
 }
References ACHIEVEMENT_CRITERIA_CONDITION_NONE, ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET2, ACHIEVEMENT_CRITERIA_TYPE_BG_OBJECTIVE_CAPTURE, ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL, ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL2, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_ACHIEVEMENT, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_BATTLEGROUND, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUEST, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUESTS_IN_ZONE, ACHIEVEMENT_CRITERIA_TYPE_DO_EMOTE, ACHIEVEMENT_CRITERIA_TYPE_EQUIP_EPIC_ITEM, ACHIEVEMENT_CRITERIA_TYPE_EQUIP_ITEM, ACHIEVEMENT_CRITERIA_TYPE_EXPLORE_AREA, ACHIEVEMENT_CRITERIA_TYPE_FISH_IN_GAMEOBJECT, ACHIEVEMENT_CRITERIA_TYPE_GAIN_REPUTATION, ACHIEVEMENT_CRITERIA_TYPE_HK_CLASS, ACHIEVEMENT_CRITERIA_TYPE_HK_RACE, ACHIEVEMENT_CRITERIA_TYPE_HONORABLE_KILL_AT_AREA, ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, ACHIEVEMENT_CRITERIA_TYPE_KILLED_BY_CREATURE, ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILL_LEVEL, ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILL_LINE, ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILLLINE_SPELLS, ACHIEVEMENT_CRITERIA_TYPE_LEARN_SPELL, ACHIEVEMENT_CRITERIA_TYPE_LOOT_ITEM, ACHIEVEMENT_CRITERIA_TYPE_LOOT_TYPE, ACHIEVEMENT_CRITERIA_TYPE_OWN_ITEM, ACHIEVEMENT_CRITERIA_TYPE_REACH_SKILL_LEVEL, ACHIEVEMENT_CRITERIA_TYPE_USE_GAMEOBJECT, ACHIEVEMENT_CRITERIA_TYPE_USE_ITEM, ACHIEVEMENT_CRITERIA_TYPE_WIN_BG, AchievementCriteriaEntry::additionalRequirement_type, AchievementCriteriaEntry::additionalRequirement_value, AchievementCriteriaEntry::additionalRequirements, WorldMapOverlayEntry::areatableID, AchievementCriteriaEntry::be_spell_target, AchievementCriteriaEntry::bg_objective, AchievementCriteriaEntry::cast_spell, AchievementCriteriaEntry::complete_achievement, AchievementCriteriaEntry::complete_battleground, AchievementCriteriaEntry::complete_quest, AchievementCriteriaEntry::complete_quests_in_zone, AchievementCriteriaEntry::do_emote, AchievementCriteriaEntry::equip_epic_item, AchievementCriteriaEntry::equip_item, AchievementCriteriaEntry::explore_area, AchievementCriteriaEntry::fish_in_gameobject, AchievementCriteriaEntry::gain_reputation, getMSTime(), GetMSTimeDiffToNow(), AchievementCriteriaEntry::hk_class, AchievementCriteriaEntry::hk_race, AchievementCriteriaEntry::honorable_kill_at_area, AchievementCriteriaEntry::kill_creature, AchievementCriteriaEntry::killed_by_creature, AchievementCriteriaEntry::learn_skill_level, AchievementCriteriaEntry::learn_skill_line, AchievementCriteriaEntry::learn_skillline_spell, AchievementCriteriaEntry::learn_spell, LOG_INFO, AchievementCriteriaEntry::loot_type, m_AchievementCriteriaListByAchievement, m_AchievementCriteriasByCondition, m_AchievementCriteriasByTimedType, m_AchievementCriteriasByType, m_SpecialList, MAX_WORLD_MAP_OVERLAY_AREA_IDX, AchievementCriteriaEntry::own_item, AchievementCriteriaEntry::reach_skill_level, AchievementCriteriaEntry::referredAchievement, AchievementCriteriaEntry::requiredType, sAchievementCriteriaStore, sWorldMapOverlayStore, AchievementCriteriaEntry::timedType, AchievementCriteriaEntry::timeLimit, AchievementCriteriaEntry::use_gameobject, AchievementCriteriaEntry::use_item, and AchievementCriteriaEntry::win_bg.
LoadAchievementReferenceList()
void AchievementGlobalMgr::LoadAchievementReferenceList ()
Definition at line 2602 of file AchievementMgr.cpp.
 {
     uint32 oldMSTime = getMSTime();
     if (sAchievementStore.GetNumRows() == 0)
     {
         LOG_INFO("server.loading", ">> Loaded 0 achievement references.");
         LOG_INFO("server.loading", " ");
         return;
     }
     uint32 count = 0;
     for (uint32 entryId = 0; entryId < sAchievementStore.GetNumRows(); ++entryId)
     {
         AchievementEntry const* achievement = sAchievementStore.LookupEntry(entryId);
         if (!achievement || !achievement->refAchievement)
             continue;
         m_AchievementListByReferencedId[achievement->refAchievement].push_back(achievement);
         ++count;
     }
     LOG_INFO("server.loading", ">> Loaded %u achievement references in %u ms", count, GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
 }
References count(), getMSTime(), GetMSTimeDiffToNow(), LOG_INFO, m_AchievementListByReferencedId, AchievementEntry::refAchievement, and sAchievementStore.
LoadCompletedAchievements()
void AchievementGlobalMgr::LoadCompletedAchievements ()
Definition at line 2764 of file AchievementMgr.cpp.
 {
     uint32 oldMSTime = getMSTime();
     QueryResult result = CharacterDatabase.Query("SELECT achievement FROM character_achievement GROUP BY achievement");
     // Populate _allCompletedAchievements with all realm first achievement ids to make multithreaded access safer
     // while it will not prevent races, it will prevent crashes that happen because std::unordered_map key was added
     // instead the only potential race will happen on value associated with the key
     for (uint32 i = 0; i < sAchievementStore.GetNumRows(); ++i)
         if (AchievementEntry const* achievement = sAchievementStore.LookupEntry(i))
             if (achievement->flags & (ACHIEVEMENT_FLAG_REALM_FIRST_REACH | ACHIEVEMENT_FLAG_REALM_FIRST_KILL))
                 m_allCompletedAchievements[achievement->ID] = std::chrono::system_clock::time_point::min();
     if (!result)
     {
         LOG_INFO("server.loading", ">> Loaded 0 completed achievements. DB table `character_achievement` is empty.");
         LOG_INFO("server.loading", " ");
         return;
     }
     do
     {
         Field* fields = result->Fetch();
         uint16 achievementId = fields[0].GetUInt16();
         const AchievementEntry* achievement = sAchievementStore.LookupEntry(achievementId);
         if (!achievement)
         {
             // Remove non existent achievements from all characters
             LOG_ERROR("achievement", "Non-existing achievement %u data removed from table `character_achievement`.", achievementId);
             CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_INVALID_ACHIEVMENT);
             stmt->setUInt16(0, uint16(achievementId));
             CharacterDatabase.Execute(stmt);
             continue;
         }
         else if (achievement->flags & (ACHIEVEMENT_FLAG_REALM_FIRST_REACH | ACHIEVEMENT_FLAG_REALM_FIRST_KILL))
             m_allCompletedAchievements[achievementId] =  std::chrono::system_clock::time_point::max();
     } while (result->NextRow());
     LOG_INFO("server.loading", ">> Loaded %lu completed achievements in %u ms", (unsigned long)m_allCompletedAchievements.size(), GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
 }
References ACHIEVEMENT_FLAG_REALM_FIRST_KILL, ACHIEVEMENT_FLAG_REALM_FIRST_REACH, CHAR_DEL_INVALID_ACHIEVMENT, CharacterDatabase, AchievementEntry::flags, getMSTime(), GetMSTimeDiffToNow(), Field::GetUInt16(), LOG_ERROR, LOG_INFO, m_allCompletedAchievements, max, min, sAchievementStore, and PreparedStatementBase::setUInt16().
LoadRewardLocales()
void AchievementGlobalMgr::LoadRewardLocales ()
Definition at line 2932 of file AchievementMgr.cpp.
 {
     uint32 oldMSTime = getMSTime();
     m_achievementRewardLocales.clear();                       // need for reload case
     //                                               0   1       2        3
     QueryResult result = WorldDatabase.Query("SELECT ID, Locale, Subject, Text FROM achievement_reward_locale");
     if (!result)
     {
         LOG_INFO("server.loading", ">> Loaded 0 achievement reward locale strings.  DB table `achievement_reward_locale` is empty");
         LOG_INFO("server.loading", " ");
         return;
     }
     do
     {
         Field* fields = result->Fetch();
         uint32 ID = fields[0].GetUInt32();
         if (m_achievementRewards.find(ID) == m_achievementRewards.end())
         {
             LOG_ERROR("sql.sql", "Table `achievement_reward_locale` (Entry: %u) has locale strings for non-existing achievement reward.", ID);
             continue;
         }
         LocaleConstant locale = GetLocaleByName(fields[1].GetString());
         if (locale == LOCALE_enUS)
             continue;
         AchievementRewardLocale& data = m_achievementRewardLocales[ID];
         ObjectMgr::AddLocaleString(fields[2].GetString(), locale, data.Subject);
         ObjectMgr::AddLocaleString(fields[3].GetString(), locale, data.Text);
     } while (result->NextRow());
     LOG_INFO("server.loading", ">> Loaded %lu Achievement Reward Locale strings in %u ms", (unsigned long)m_achievementRewardLocales.size(), GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
 }
References ObjectMgr::AddLocaleString(), GetLocaleByName(), getMSTime(), GetMSTimeDiffToNow(), Field::GetUInt32(), LOCALE_enUS, LOG_ERROR, LOG_INFO, m_achievementRewardLocales, m_achievementRewards, and WorldDatabase.
LoadRewards()
void AchievementGlobalMgr::LoadRewards ()
Definition at line 2811 of file AchievementMgr.cpp.
 {
     uint32 oldMSTime = getMSTime();
     m_achievementRewards.clear();                           // need for reload case
     //                                               0      1        2        3     4       5        6     7
     QueryResult result = WorldDatabase.Query("SELECT ID, TitleA, TitleH, ItemID, Sender, Subject, Body, MailTemplateID FROM achievement_reward");
     if (!result)
     {
         LOG_INFO("server.loading", ">> Loaded 0 achievement rewards. DB table `achievement_reward` is empty.");
         LOG_INFO("server.loading", " ");
         return;
     }
     uint32 count = 0;
     do
     {
         Field* fields = result->Fetch();
         uint32 entry = fields[0].GetUInt32();
         AchievementEntry const* achievement = sAchievementStore.LookupEntry(entry);
         if (!achievement)
         {
             LOG_ERROR("sql.sql", "Table `achievement_reward` has wrong achievement (Entry: %u). Ignoring.", entry);
             continue;
         }
         AchievementReward reward;
         reward.titleId[0]   = fields[1].GetUInt32(); // Alliance title
         reward.titleId[1]   = fields[2].GetUInt32(); // Horde title
         reward.itemId       = fields[3].GetUInt32();
         reward.sender       = fields[4].GetUInt32(); // The sender of the mail (a creature from creature_template)
         reward.subject      = fields[5].GetString();
         reward.text         = fields[6].GetString(); // Body in DB
         reward.mailTemplate = fields[7].GetUInt32();
         // Must reward a title or send a mail else, skip it.
         if (!reward.titleId[0] && !reward.titleId[1] && !reward.sender)
         {
             LOG_ERROR("sql.sql", "Table `achievement_reward` (Entry: %u) does not have any title or item reward data. Ignoring.", entry);
             continue;
         }
         if (achievement->requiredFaction == ACHIEVEMENT_FACTION_ANY && (!reward.titleId[0] ^ !reward.titleId[1]))
             LOG_DEBUG("achievement", "Table `achievement_reward` (Entry: %u) has title (A: %u H: %u) set for only one team.", entry, reward.titleId[0], reward.titleId[1]);
         if (reward.titleId[0])
         {
             CharTitlesEntry const* titleEntry = sCharTitlesStore.LookupEntry(reward.titleId[0]);
             if (!titleEntry)
             {
                 LOG_ERROR("sql.sql", "Table `achievement_reward` (Entry: %u) has invalid title id (%u) in `title_A`. Setting it to 0.", entry, reward.titleId[0]);
                 reward.titleId[0] = 0;
             }
         }
         if (reward.titleId[1])
         {
             CharTitlesEntry const* titleEntry = sCharTitlesStore.LookupEntry(reward.titleId[1]);
             if (!titleEntry)
             {
                 LOG_ERROR("sql.sql", "Table `achievement_reward` (Entry: %u) has invalid title id (%u) in `title_H`. Setting it to 0.", entry, reward.titleId[1]);
                 reward.titleId[1] = 0;
             }
         }
         // Check mail data before item for report including wrong item case
         if (reward.sender)
         {
             if (!sObjectMgr->GetCreatureTemplate(reward.sender))
             {
                 LOG_ERROR("sql.sql", "Table `achievement_reward` (Entry: %u) has invalid creature_template entry %u as Sender. Will not send the mail reward.", entry, reward.sender);
                 reward.sender = 0;
             }
         }
         else
         {
             if (reward.itemId)
                 LOG_ERROR("sql.sql", "Table `achievement_reward` (Entry: %u) has itemId reward set but does not have Sender data set. Item will not be sent.", entry);
             if (!reward.subject.empty())
                 LOG_ERROR("sql.sql", "Table `achievement_reward` (Entry: %u) has mail Subject but does not have Sender data set.", entry); // Maybe add "Mail will not be sent." ?
             if (!reward.text.empty())
                 LOG_ERROR("sql.sql", "Table `achievement_reward` (Entry: %u) has mail text (Body) set but does not have Sender data set.", entry); // Maybe add "Mail will not be sent." ?
             if (reward.mailTemplate)
                 LOG_ERROR("sql.sql", "Table `achievement_reward` (Entry: %u) has mailTemplate set does not have Sender data set.", entry); // Maybe add "Mail will not be sent." ?
         }
         if (reward.mailTemplate)
         {
             if (!sMailTemplateStore.LookupEntry(reward.mailTemplate))
             {
                 LOG_ERROR("sql.sql", "Table `achievement_reward` (Entry: %u) has invalid mailTemplate (%u) (check the DBC).", entry, reward.mailTemplate);
                 reward.mailTemplate = 0;
             }
             else if (!reward.subject.empty() || !reward.text.empty())
                 LOG_ERROR("sql.sql", "Table `achievement_reward` (Entry: %u) has mailTemplate (%u) and mail Subject/Body. To use the column mailTemplate, Subject and Body must be empty.", entry, reward.mailTemplate);
         }
         if (reward.itemId)
         {
             if (!sObjectMgr->GetItemTemplate(reward.itemId))
             {
                 // Not sure it's an error, it's probably an outDebug instead, because we can simply send a mail with no reward, right?
                 LOG_ERROR("sql.sql", "Table `achievement_reward` (Entry: %u) has invalid item_template id %u. Reward mail will not contain any item.", entry, reward.itemId);
                 reward.itemId = 0;
             }
         }
         m_achievementRewards[entry] = reward;
         ++count;
     } while (result->NextRow());
     LOG_INFO("server.loading", ">> Loaded %u achievement rewards in %u ms", count, GetMSTimeDiffToNow(oldMSTime));
     LOG_INFO("server.loading", " ");
 }
References ACHIEVEMENT_FACTION_ANY, count(), getMSTime(), GetMSTimeDiffToNow(), Field::GetString(), Field::GetUInt32(), AchievementReward::itemId, LOG_DEBUG, LOG_ERROR, LOG_INFO, m_achievementRewards, AchievementReward::mailTemplate, AchievementEntry::requiredFaction, sAchievementStore, sCharTitlesStore, AchievementReward::sender, sMailTemplateStore, sObjectMgr, AchievementReward::subject, AchievementReward::text, AchievementReward::titleId, and WorldDatabase.
SetRealmCompleted()
void AchievementGlobalMgr::SetRealmCompleted (AchievementEntry const * achievement)
Definition at line 2444 of file AchievementMgr.cpp.
 {
     if (IsRealmCompleted(achievement))
         return;
     m_allCompletedAchievements[achievement->ID] = std::chrono::system_clock::now();
 }
References AchievementEntry::ID, IsRealmCompleted(), and m_allCompletedAchievements.
Member Data Documentation
m_AchievementCriteriaListByAchievement
AchievementCriteriaListByAchievement AchievementGlobalMgr::m_AchievementCriteriaListByAchievement private
Definition at line 400 of file AchievementMgr.h.
Referenced by GetAchievementCriteriaByAchievement(), and LoadAchievementCriteriaList().
m_AchievementCriteriasByCondition
std::map<uint32, AchievementCriteriaEntryList> AchievementGlobalMgr::m_AchievementCriteriasByCondition[ACHIEVEMENT_CRITERIA_CONDITION_TOTAL] private
Definition at line 412 of file AchievementMgr.h.
Referenced by GetAchievementCriteriaByCondition(), and LoadAchievementCriteriaList().
m_AchievementCriteriasByTimedType
AchievementCriteriaEntryList AchievementGlobalMgr::m_AchievementCriteriasByTimedType[ACHIEVEMENT_TIMED_TYPE_MAX] private
Definition at line 398 of file AchievementMgr.h.
Referenced by GetTimedAchievementCriteriaByType(), and LoadAchievementCriteriaList().
m_AchievementCriteriasByType
AchievementCriteriaEntryList AchievementGlobalMgr::m_AchievementCriteriasByType[ACHIEVEMENT_CRITERIA_TYPE_TOTAL] private
Definition at line 397 of file AchievementMgr.h.
Referenced by GetAchievementCriteriaByType(), and LoadAchievementCriteriaList().
m_AchievementListByReferencedId
AchievementListByReferencedId AchievementGlobalMgr::m_AchievementListByReferencedId private
Definition at line 402 of file AchievementMgr.h.
Referenced by GetAchievementByReferencedId(), and LoadAchievementReferenceList().
m_achievementRewardLocales
AchievementRewardLocales AchievementGlobalMgr::m_achievementRewardLocales private
Definition at line 408 of file AchievementMgr.h.
Referenced by GetAchievementRewardLocale(), and LoadRewardLocales().
m_achievementRewards
AchievementRewards AchievementGlobalMgr::m_achievementRewards private
Definition at line 407 of file AchievementMgr.h.
Referenced by GetAchievementReward(), LoadRewardLocales(), and LoadRewards().
m_allCompletedAchievements
AllCompletedAchievements AchievementGlobalMgr::m_allCompletedAchievements private
Definition at line 405 of file AchievementMgr.h.
Referenced by IsRealmCompleted(), LoadCompletedAchievements(), and SetRealmCompleted().
m_criteriaDataMap
AchievementCriteriaDataMap AchievementGlobalMgr::m_criteriaDataMap private
Definition at line 394 of file AchievementMgr.h.
Referenced by GetCriteriaDataSet(), and LoadAchievementCriteriaData().
m_SpecialList
std::map<uint32, AchievementCriteriaEntryList> AchievementGlobalMgr::m_SpecialList[ACHIEVEMENT_CRITERIA_TYPE_TOTAL] private
Definition at line 411 of file AchievementMgr.h.
Referenced by GetSpecialAchievementCriteriaByType(), and LoadAchievementCriteriaList().
The documentation for this class was generated from the following files:
src/server/game/Achievements/AchievementMgr.h
src/server/game/Achievements/AchievementMgr.cpp