Azerotcore-wotlk: boss_faction_championsAI Struct Reference
boss_faction_championsAI Struct Reference
Public Member Functions
boss_faction_championsAI (Creature *pCreature, uint32 aitype)
void EnterCombat (Unit *) override
void AttackStart (Unit *who) override
float GetThreatMod (float dist, float, uint32 health, uint32, Unit *target)
void RecalculateThreat ()
void EventMapGCD (EventMap &e, uint32 delay, uint32 gcd=0)
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void EnterEvadeMode () override
bool IsCCed ()
Creature * SelectTarget_MostHPLostFriendlyMissingBuff (uint32 spell, float range)
uint32 EnemiesInRange (float distance)
Unit * SelectEnemyCaster (bool casting, float range)
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
uint32 mAIType
uint32 threatTimer
uint32 powerTimer
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 38 of file boss_faction_champions.cpp.
Constructor & Destructor Documentation
boss_faction_championsAI()
boss_faction_championsAI::boss_faction_championsAI (Creature * pCreature, uint32 aitype) inline
Definition at line 40 of file boss_faction_champions.cpp.
                                                                  : ScriptedAI(pCreature)
     {
         pInstance = pCreature->GetInstanceScript();
         me->SetReactState(REACT_PASSIVE);
         mAIType = aitype;
         threatTimer = 2000;
         powerTimer = 1000;
     }
References WorldObject::GetInstanceScript(), mAIType, ScriptedAI::me, pInstance, powerTimer, REACT_PASSIVE, Creature::SetReactState(), and threatTimer.
Member Function Documentation
AttackStart()
void boss_faction_championsAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 62 of file boss_faction_champions.cpp.
     {
         if( !who )
             return;
         if( mAIType == AI_MELEE || mAIType == AI_PET )
             UnitAI::AttackStart(who);
         else
             UnitAI::AttackStartCaster(who, 18.5f);
     }
References AI_MELEE, AI_PET, UnitAI::AttackStart(), UnitAI::AttackStartCaster(), and mAIType.
EnemiesInRange()
uint32 boss_faction_championsAI::EnemiesInRange (float distance) inline
Definition at line 178 of file boss_faction_champions.cpp.
     {
         ThreatContainer::StorageType const& tList = me->getThreatMgr().getThreatList();
         uint32 count = 0;
         Unit* target;
         for( ThreatContainer::StorageType::const_iterator iter = tList.begin(); iter != tList.end(); ++iter )
         {
             target = ObjectAccessor::GetUnit((*me), (*iter)->getUnitGuid());
             if( target && me->GetDistance2d(target) < distance )
                 ++count;
         }
         return count;
     }
References count(), G3D::distance(), WorldObject::GetDistance2d(), ThreatMgr::getThreatList(), Unit::getThreatMgr(), ObjectAccessor::GetUnit(), and ScriptedAI::me.
Referenced by npc_toc_priest::npc_toc_priestAI::UpdateAI(), npc_toc_shadow_priest::npc_toc_shadow_priestAI::UpdateAI(), npc_toc_warlock::npc_toc_warlockAI::UpdateAI(), npc_toc_mage::npc_toc_mageAI::UpdateAI(), npc_toc_hunter::npc_toc_hunterAI::UpdateAI(), npc_toc_warrior::npc_toc_warriorAI::UpdateAI(), npc_toc_rogue::npc_toc_rogueAI::UpdateAI(), and npc_toc_retro_paladin::npc_toc_retro_paladinAI::UpdateAI().
EnterCombat()
void boss_faction_championsAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 54 of file boss_faction_champions.cpp.
     {
         me->SetInCombatWithZone();
         RecalculateThreat();
         if( pInstance )
             pInstance->SetData(TYPE_FACTION_CHAMPIONS_START, 0);
     }
References ScriptedAI::me, pInstance, RecalculateThreat(), ZoneScript::SetData(), Creature::SetInCombatWithZone(), and TYPE_FACTION_CHAMPIONS_START.
EnterEvadeMode()
void boss_faction_championsAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Reimplemented in npc_toc_pet_hunter::npc_toc_pet_hunterAI, and npc_toc_pet_warlock::npc_toc_pet_warlockAI.
Definition at line 137 of file boss_faction_champions.cpp.
     {
         if( pInstance )
             pInstance->SetData(TYPE_FAILED, 0);
     }
References pInstance, ZoneScript::SetData(), and TYPE_FAILED.
EventMapGCD()
void boss_faction_championsAI::EventMapGCD (EventMap & e, uint32 delay, uint32 gcd = 0) inline
Definition at line 120 of file boss_faction_champions.cpp.
     {
         e.DelayEventsToMax(delay, gcd);
     }
References EventMap::DelayEventsToMax().
Referenced by npc_toc_druid::npc_toc_druidAI::UpdateAI(), npc_toc_shaman::npc_toc_shamanAI::UpdateAI(), npc_toc_paladin::npc_toc_paladinAI::UpdateAI(), npc_toc_priest::npc_toc_priestAI::UpdateAI(), npc_toc_shadow_priest::npc_toc_shadow_priestAI::UpdateAI(), npc_toc_warlock::npc_toc_warlockAI::UpdateAI(), npc_toc_mage::npc_toc_mageAI::UpdateAI(), npc_toc_hunter::npc_toc_hunterAI::UpdateAI(), npc_toc_boomkin::npc_toc_boomkinAI::UpdateAI(), npc_toc_warrior::npc_toc_warriorAI::UpdateAI(), npc_toc_dk::npc_toc_dkAI::UpdateAI(), npc_toc_rogue::npc_toc_rogueAI::UpdateAI(), npc_toc_enh_shaman::npc_toc_enh_shamanAI::UpdateAI(), npc_toc_retro_paladin::npc_toc_retro_paladinAI::UpdateAI(), and npc_toc_pet_warlock::npc_toc_pet_warlockAI::UpdateAI().
GetThreatMod()
float boss_faction_championsAI::GetThreatMod (float dist, float , uint32 health, uint32 , Unit * target) inline
Definition at line 73 of file boss_faction_champions.cpp.
     {
         /*float mod_health = ((float)health)/maxhealth;
         if (mod_health < 0.4f) mod_health = 0.4f;
         float unimportant_dist = (mAIType == AI_MELEE || mAIType == AI_PET ? 5.0f : 20.0f);
         if (dist > unimportant_dist)
             dist -= unimportant_dist; // compensate melee range
         else
             dist = 0.0f;
         float mod_dist = 25.0f/(25.0f + dist);
         float mod_armor = (mAIType == AI_MELEE || mAIType == AI_PET) ? armor / 16635.0f : 0.0f;
         return mod_dist / ((0.15f+mod_armor)*mod_health);*/
         // TC:
         /*float dist_mod = (mAIType == AI_MELEE || mAIType == AI_PET) ? 15.0f / (15.0f + dist) : 1.0f;
         float armor_mod = (mAIType == AI_MELEE || mAIType == AI_PET) ? armor / 16635.0f : 0.0f;
         float eh = (health + 1) * (1.0f + armor_mod);
         return dist_mod * 30000.0f / eh;*/
         // third try:
         float unimportant_dist = (mAIType == AI_MELEE || mAIType == AI_PET ? 5.0f : 35.0f);
         if (dist > unimportant_dist) dist -= unimportant_dist;
         else dist = 0.0f;
         const float dist_factor = (mAIType == AI_MELEE || mAIType == AI_PET ? 15.0f : 25.0f);
         float mod_dist = dist_factor / (dist_factor + dist); // 0.2 .. 1.0
         float mod_health = health > 40000 ? 2.0f : (60000 - health) / 10000.0f; // 2.0 .. 6.0
         float mod_armor = (mAIType == AI_MELEE || mAIType == AI_PET) ? Unit::CalcArmorReducedDamage(me, target, 10000, nullptr) / 10000.0f : 1.0f;
         return mod_dist * mod_health * mod_armor;
     }
References AI_MELEE, AI_PET, Unit::CalcArmorReducedDamage(), mAIType, and ScriptedAI::me.
Referenced by RecalculateThreat().
IsCCed()
bool boss_faction_championsAI::IsCCed () inline
Definition at line 143 of file boss_faction_champions.cpp.
     {
         // check for stun, fear, etc.
         // for casting, silence, disarm check individually in the ai
         if( me->isFeared() || me->isFrozen() || me->HasUnitState(UNIT_STATE_STUNNED) || me->HasUnitState(UNIT_STATE_CONFUSED) )
         {
             if( !IsHeroic() )
                 return true;
             if( me->HasSpellCooldown(SPELL_PVP_TRINKET) )
                 return true;
             else
             {
                 me->CastSpell(me, SPELL_PVP_TRINKET, false);
                 me->AddSpellCooldown(SPELL_PVP_TRINKET, 0, 0);
             }
         }
         return false;
     }
References Creature::AddSpellCooldown(), Unit::CastSpell(), Creature::HasSpellCooldown(), Unit::HasUnitState(), Unit::isFeared(), Unit::isFrozen(), ScriptedAI::IsHeroic(), ScriptedAI::me, SPELL_PVP_TRINKET, UNIT_STATE_CONFUSED, and UNIT_STATE_STUNNED.
Referenced by npc_toc_druid::npc_toc_druidAI::myCanCast(), npc_toc_shaman::npc_toc_shamanAI::myCanCast(), npc_toc_paladin::npc_toc_paladinAI::myCanCast(), npc_toc_priest::npc_toc_priestAI::myCanCast(), npc_toc_shadow_priest::npc_toc_shadow_priestAI::myCanCast(), npc_toc_warlock::npc_toc_warlockAI::myCanCast(), npc_toc_mage::npc_toc_mageAI::myCanCast(), npc_toc_hunter::npc_toc_hunterAI::myCanCast(), npc_toc_boomkin::npc_toc_boomkinAI::myCanCast(), npc_toc_warrior::npc_toc_warriorAI::myCanCast(), npc_toc_dk::npc_toc_dkAI::myCanCast(), npc_toc_rogue::npc_toc_rogueAI::myCanCast(), npc_toc_enh_shaman::npc_toc_enh_shamanAI::myCanCast(), npc_toc_retro_paladin::npc_toc_retro_paladinAI::myCanCast(), npc_toc_pet_warlock::npc_toc_pet_warlockAI::myCanCast(), and npc_toc_pet_hunter::npc_toc_pet_hunterAI::myCanCast().
JustDied()
void boss_faction_championsAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 125 of file boss_faction_champions.cpp.
     {
         if( pInstance && mAIType != AI_PET )
             pInstance->SetData(TYPE_FACTION_CHAMPIONS, DONE);
     }
References AI_PET, DONE, mAIType, pInstance, ZoneScript::SetData(), and TYPE_FACTION_CHAMPIONS.
KilledUnit()
void boss_faction_championsAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 131 of file boss_faction_champions.cpp.
     {
         if( pInstance )
             pInstance->SetData(TYPE_FACTION_CHAMPIONS_PLAYER_DIED, 1);
     }
References pInstance, ZoneScript::SetData(), and TYPE_FACTION_CHAMPIONS_PLAYER_DIED.
RecalculateThreat()
void boss_faction_championsAI::RecalculateThreat () inline
Definition at line 103 of file boss_faction_champions.cpp.
     {
         ThreatContainer::StorageType const& tList = me->getThreatMgr().getThreatList();
         for( ThreatContainer::StorageType::const_iterator itr = tList.begin(); itr != tList.end(); ++itr )
         {
             Unit* pUnit = ObjectAccessor::GetUnit(*me, (*itr)->getUnitGuid());
             if( pUnit && pUnit->GetTypeId() == TYPEID_PLAYER && me->getThreatMgr().getThreat(pUnit) )
             {
                 float threatMod = GetThreatMod(me->GetDistance2d(pUnit), (float)pUnit->GetArmor(), pUnit->GetHealth(), pUnit->GetMaxHealth(), pUnit);
                 me->getThreatMgr().modifyThreatPercent(pUnit, -100);
                 //me->getThreatMgr().doAddThreat(pUnit, 10000000.0f * threatMod);
                 if (HostileReference* ref = me->getThreatMgr().getOnlineContainer().getReferenceByTarget(pUnit))
                     ref->addThreat(10000000.0f * threatMod);
             }
         }
     }
References Unit::GetArmor(), WorldObject::GetDistance2d(), Unit::GetHealth(), Unit::GetMaxHealth(), ThreatMgr::getOnlineContainer(), ThreatContainer::getReferenceByTarget(), ThreatMgr::getThreat(), ThreatMgr::getThreatList(), Unit::getThreatMgr(), GetThreatMod(), Object::GetTypeId(), ObjectAccessor::GetUnit(), ScriptedAI::me, ThreatMgr::modifyThreatPercent(), and TYPEID_PLAYER.
Referenced by EnterCombat(), and UpdateAI().
SelectEnemyCaster()
Unit* boss_faction_championsAI::SelectEnemyCaster (bool casting, float range) inline
Definition at line 192 of file boss_faction_champions.cpp.
     {
         ThreatContainer::StorageType const& tList = me->getThreatMgr().getThreatList();
         Unit* target;
         for( ThreatContainer::StorageType::const_iterator iter = tList.begin(); iter != tList.end(); ++iter )
         {
             target = ObjectAccessor::GetUnit((*me), (*iter)->getUnitGuid());
             if( target && target->getPowerType() == POWER_MANA && (!casting || target->HasUnitState(UNIT_STATE_CASTING)) && me->GetExactDist(target) <= range )
                 return target;
         }
         return nullptr;
     }
References Position::GetExactDist(), Unit::getPowerType(), ThreatMgr::getThreatList(), Unit::getThreatMgr(), ObjectAccessor::GetUnit(), Unit::HasUnitState(), ScriptedAI::me, POWER_MANA, and UNIT_STATE_CASTING.
Referenced by npc_toc_priest::npc_toc_priestAI::UpdateAI(), npc_toc_shadow_priest::npc_toc_shadow_priestAI::UpdateAI(), npc_toc_mage::npc_toc_mageAI::UpdateAI(), and npc_toc_dk::npc_toc_dkAI::UpdateAI().
SelectTarget_MostHPLostFriendlyMissingBuff()
Creature* boss_faction_championsAI::SelectTarget_MostHPLostFriendlyMissingBuff (uint32 spell, float range) inline
Definition at line 162 of file boss_faction_champions.cpp.
     {
         std::list<Creature*> lst = DoFindFriendlyMissingBuff(range, spell);
         if( lst.empty() )
             return nullptr;
         std::list<Creature*>::const_iterator iter = lst.begin();
         uint32 lowestHP = (*iter)->GetMaxHealth() - (*iter)->GetHealth();
         for( std::list<Creature*>::const_iterator itr = lst.begin(); itr != lst.end(); ++itr )
             if( ((*itr)->GetMaxHealth() - (*itr)->GetHealth()) > lowestHP )
             {
                 iter = itr;
                 lowestHP = (*itr)->GetMaxHealth() - (*itr)->GetHealth();
             }
         return (*iter);
     }
References ScriptedAI::DoFindFriendlyMissingBuff().
Referenced by npc_toc_druid::npc_toc_druidAI::UpdateAI(), npc_toc_shaman::npc_toc_shamanAI::UpdateAI(), npc_toc_paladin::npc_toc_paladinAI::UpdateAI(), npc_toc_priest::npc_toc_priestAI::UpdateAI(), npc_toc_shadow_priest::npc_toc_shadow_priestAI::UpdateAI(), and npc_toc_retro_paladin::npc_toc_retro_paladinAI::UpdateAI().
UpdateAI()
void boss_faction_championsAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Reimplemented in npc_toc_pet_hunter::npc_toc_pet_hunterAI, npc_toc_pet_warlock::npc_toc_pet_warlockAI, npc_toc_retro_paladin::npc_toc_retro_paladinAI, npc_toc_enh_shaman::npc_toc_enh_shamanAI, npc_toc_rogue::npc_toc_rogueAI, npc_toc_dk::npc_toc_dkAI, npc_toc_warrior::npc_toc_warriorAI, npc_toc_boomkin::npc_toc_boomkinAI, npc_toc_hunter::npc_toc_hunterAI, npc_toc_mage::npc_toc_mageAI, npc_toc_warlock::npc_toc_warlockAI, npc_toc_shadow_priest::npc_toc_shadow_priestAI, npc_toc_priest::npc_toc_priestAI, npc_toc_paladin::npc_toc_paladinAI, npc_toc_shaman::npc_toc_shamanAI, and npc_toc_druid::npc_toc_druidAI.
Definition at line 205 of file boss_faction_champions.cpp.
     {
         if (!me->IsInCombat())
             return;
         if( threatTimer <= diff )
         {
             RecalculateThreat();
             threatTimer = urand(8750, 9250);
         }
         else
             threatTimer -= diff;
         if( me->getPowerType() == POWER_MANA )
         {
             if( powerTimer <= diff )
             {
                 me->ModifyPower(POWER_MANA, me->GetMaxPower(POWER_MANA) / 3);
                 powerTimer = 4000;
             }
             else
                 powerTimer -= diff;
         }
         else if( me->getPowerType() == POWER_ENERGY )
         {
             if( powerTimer <= diff )
             {
                 me->ModifyPower(POWER_ENERGY, me->GetMaxPower(POWER_ENERGY) / 3);
                 powerTimer = 1000;
             }
             else
                 powerTimer -= diff;
         }
     }
References diff(), Unit::GetMaxPower(), Unit::getPowerType(), Unit::IsInCombat(), ScriptedAI::me, Unit::ModifyPower(), POWER_ENERGY, POWER_MANA, powerTimer, RecalculateThreat(), threatTimer, and urand().
Referenced by npc_toc_druid::npc_toc_druidAI::UpdateAI(), npc_toc_shaman::npc_toc_shamanAI::UpdateAI(), npc_toc_paladin::npc_toc_paladinAI::UpdateAI(), npc_toc_priest::npc_toc_priestAI::UpdateAI(), npc_toc_shadow_priest::npc_toc_shadow_priestAI::UpdateAI(), npc_toc_warlock::npc_toc_warlockAI::UpdateAI(), npc_toc_mage::npc_toc_mageAI::UpdateAI(), npc_toc_hunter::npc_toc_hunterAI::UpdateAI(), npc_toc_boomkin::npc_toc_boomkinAI::UpdateAI(), npc_toc_warrior::npc_toc_warriorAI::UpdateAI(), npc_toc_dk::npc_toc_dkAI::UpdateAI(), npc_toc_rogue::npc_toc_rogueAI::UpdateAI(), npc_toc_enh_shaman::npc_toc_enh_shamanAI::UpdateAI(), npc_toc_retro_paladin::npc_toc_retro_paladinAI::UpdateAI(), npc_toc_pet_warlock::npc_toc_pet_warlockAI::UpdateAI(), and npc_toc_pet_hunter::npc_toc_pet_hunterAI::UpdateAI().
Member Data Documentation
mAIType
uint32 boss_faction_championsAI::mAIType
Definition at line 50 of file boss_faction_champions.cpp.
Referenced by AttackStart(), boss_faction_championsAI(), GetThreatMod(), and JustDied().
pInstance
InstanceScript* boss_faction_championsAI::pInstance
Definition at line 49 of file boss_faction_champions.cpp.
Referenced by boss_faction_championsAI(), EnterCombat(), EnterEvadeMode(), JustDied(), and KilledUnit().
powerTimer
uint32 boss_faction_championsAI::powerTimer
Definition at line 52 of file boss_faction_champions.cpp.
Referenced by boss_faction_championsAI(), and UpdateAI().
threatTimer
uint32 boss_faction_championsAI::threatTimer
Definition at line 51 of file boss_faction_champions.cpp.
Referenced by boss_faction_championsAI(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_faction_champions.cpp