Azerotcore-wotlk: deps/g3dlite/Readme.txt File Reference
deps/g3dlite/Readme.txt File Reference
Functions
Due to issues with G3D normally requiring X11 and the ZIP the library version in this sourcetree contains a modified version The applied patches are added as diff files to the repository for future reference (knowing what was changed is quite handy). G3D-v8.0_hotfix1.diff - 2010-08-27 - remove dependency on zip/z11 libraries
Variables
Due to issues with G3D normally requiring X11 and the ZIP library
Function Documentation
reference()
Due to issues with G3D normally requiring X11 and the ZIP the library version in this sourcetree contains a modified version The applied patches are added as diff files to the repository for future reference (knowing what was changed is quite handy)
Referenced by Group::CanJoinBattlegroundQueue(), LootStore::LoadLootTable(), and boss_taldaram::boss_taldaramAI::UpdateAI().
Variable Documentation
library
Due to issues with G3D normally requiring X11 and the ZIP library
Definition at line 1 of file Readme.txt.