Azerotcore-wotlk: deps/fmt/include/fmt/format.h File Reference
format.h File Reference
#include <cmath>
#include <cstdint>
#include <limits>
#include <memory>
#include <stdexcept>
#include <system_error>
#include <utility>
#include "core.h"
Classes
struct detail::fallback_uintptr
struct detail::is_locale< T, Enable >
struct detail::is_locale< T, void_t< decltype(T::classic())> >
class basic_memory_buffer< T, SIZE, Allocator >
struct is_contiguous< basic_memory_buffer< T, SIZE, Allocator > >
class format_error
struct is_integral< T >
struct is_integral< int128_t >
struct is_integral< uint128_t >
struct basic_data< T >
struct data
struct thousands_sep_result< Char >
struct format_decimal_result< Iterator >
class utf8_to_utf16
struct dragonbox::float_info< float >
struct dragonbox::float_info< double >
struct dragonbox::decimal_fp< T >
struct write_int_data< Char >
struct write_int_arg< UInt >
struct big_decimal_fp
struct default_arg_formatter< Char >
struct arg_formatter< Char >
struct custom_formatter< Char >
class width_checker< ErrorHandler >
class precision_checker< ErrorHandler >
class specs_handler< Char >
class format_int
struct formatter< void *, Char >
struct formatter< Char[N], Char >
class dynamic_formatter< Char >
struct dynamic_formatter< Char >::null_handler
class bytes
struct formatter< bytes >
struct join_view< It, Sentinel, Char >
struct formatter< join_view< It, Sentinel, Char >, Char >
Namespaces
detail
detail_exported
dragonbox
Macros
#define FMT_ICC_VERSION 0
#define FMT_CUDA_VERSION 0
#define FMT_HAS_BUILTIN(x) 0
#define FMT_NOINLINE
#define FMT_MSC_DEFAULT
#define FMT_THROW(x) throw x
#define FMT_TRY try
#define FMT_CATCH(x) catch (x)
#define FMT_DEPRECATED /* deprecated */
#define FMT_DEPRECATED_ALIAS FMT_DEPRECATED
#define FMT_USE_USER_DEFINED_LITERALS 0
#define FMT_REDUCE_INT_INSTANTIATIONS 0
#define FMT_CONSTEXPR20
#define FMT_USE_FULL_CACHE_DRAGONBOX 0
#define FMT_POWERS_OF_10(factor)
#define FMT_INC(T) (((sizeof(#T) - 1ull) << 32) - T)
#define FMT_STRING_IMPL(s, base, explicit)
#define FMT_STRING(s) FMT_STRING_IMPL(s, fmt::compile_string,)
#define FMT_FORMAT_AS(Type, Base)
#define FMT_FUNC
Typedefs
using detail::uintptr_t = fallback_uintptr
template<typename T >
using detail::iterator_t = decltype(std::begin(std::declval< T & >()))
template<typename T >
using detail::sentinel_t = decltype(std::end(std::declval< T & >()))
template<typename T >
using detail::checked_ptr = T *
template<typename OutputIt >
using detail::reserve_iterator = remove_reference_t< decltype(reserve(std::declval< OutputIt & >(), 0))>
template<typename T >
using detail::is_fast_float = bool_constant< std::numeric_limits< T >::is_iec559 &&sizeof(T)<=sizeof(double)>
using memory_buffer = basic_memory_buffer< char >
template<typename T >
using is_signed = std::integral_constant< bool, std::numeric_limits< T >::is_signed||std::is_same< T, int128_t >::value >
template<typename T >
using uint32_or_64_or_128_t = conditional_t< num_bits< T >()<=32 &&!FMT_REDUCE_INT_INSTANTIATIONS, uint32_t, conditional_t< num_bits< T >()<=64, uint64_t, uint128_t > >
template<typename T >
using uint64_or_128_t = conditional_t< num_bits< T >()<=64, uint64_t, uint128_t >
template<typename T >
using is_integer = bool_constant< is_integral< T >::value &&!std::is_same< T, bool >::value &&!std::is_same< T, char >::value &&!std::is_same< T, wchar_t >::value >
using format_func = void(*)(detail::buffer< char > &, int, const char *)
using FMT_DEPRECATED_ALIAS = join_view< It, Sentinel, Char >
Enumerations
enum detail::char8_type : unsigned char
enum { inline_buffer_size = 500 }
Functions
template<typename Dest , typename Source >
auto detail::bit_cast (const Source &source) -> Dest
auto detail::is_big_endian () -> bool
auto detail::to_uintptr (const void *p) -> fallback_uintptr
template<typename T >
constexpr auto detail::max_value () -> T
template<typename T >
constexpr auto detail::num_bits () -> int
template<>
constexpr auto detail::num_bits< int128_t > () -> int
template<>
constexpr auto detail::num_bits< uint128_t > () -> int
template<>
constexpr auto detail::num_bits< fallback_uintptr > () -> int
FMT_INLINE void detail::assume (bool condition)
template<typename Char >
auto detail::get_data (std::basic_string< Char > &s) -> Char *
template<typename Container >
auto detail::get_data (Container &c) -> typename Container::value_type *
template<typename T >
auto detail::make_checked (T *p, size_t) -> T *
template<typename Container , FMT_ENABLE_IF(is_contiguous< Container >::value) >
auto detail::reserve (std::back_insert_iterator< Container > it, size_t n) -> checked_ptr< typename Container::value_type >
template<typename T >
auto detail::reserve (buffer_appender< T > it, size_t n) -> buffer_appender< T >
template<typename Iterator >
constexpr auto detail::reserve (Iterator &it, size_t) -> Iterator &
template<typename T , typename OutputIt >
constexpr auto detail::to_pointer (OutputIt, size_t) -> T *
template<typename T >
auto detail::to_pointer (buffer_appender< T > it, size_t n) -> T *
template<typename Container , FMT_ENABLE_IF(is_contiguous< Container >::value) >
auto detail::base_iterator (std::back_insert_iterator< Container > &it, checked_ptr< typename Container::value_type >) -> std::back_insert_iterator< Container >
template<typename Iterator >
constexpr auto detail::base_iterator (Iterator, Iterator it) -> Iterator
template<typename OutputIt , typename Size , typename T >
FMT_CONSTEXPR auto detail::fill_n (OutputIt out, Size count, const T &value) -> OutputIt
template<typename T , typename Size >
FMT_CONSTEXPR20 auto detail::fill_n (T *out, Size count, char value) -> T *
template<typename OutChar , typename InputIt , typename OutputIt >
FMT_CONSTEXPR FMT_NOINLINE auto detail::copy_str_noinline (InputIt begin, InputIt end, OutputIt out) -> OutputIt
FMT_CONSTEXPR auto detail::utf8_decode (const char *s, uint32_t *c, int *e) -> const char *
template<typename F >
FMT_CONSTEXPR void detail::for_each_codepoint (string_view s, F f)
template<typename Char >
auto detail::compute_width (basic_string_view< Char > s) -> size_t
auto detail::compute_width (basic_string_view< char8_type > s) -> size_t
template<typename Char >
auto detail::code_point_index (basic_string_view< Char > s, size_t n) -> size_t
auto detail::code_point_index (basic_string_view< char8_type > s, size_t n) -> size_t
FMT_FUNC void detail::print (std::FILE *f, string_view text)
template<typename... Args, typename S , typename Char = char_t<S>>
FMT_INLINE auto make_args_checked (const S &fmt, const remove_reference_t< Args > &... args) -> format_arg_store< buffer_context< Char >, remove_reference_t< Args >... >
template<typename Char , size_t N>
constexpr auto detail_exported::compile_string_to_view (const Char(&s)[N]) -> basic_string_view< Char >
template<typename Char >
constexpr auto detail_exported::compile_string_to_view (detail::std_string_view< Char > s) -> basic_string_view< Char >
FMT_BEGIN_DETAIL_NAMESPACE void throw_format_error (const char *message)
template<typename T , FMT_ENABLE_IF(is_signed< T >::value) >
FMT_CONSTEXPR auto is_negative (T value) -> bool
template<typename T , FMT_ENABLE_IF(std::is_floating_point< T >::value) >
FMT_CONSTEXPR auto is_supported_floating_point (T) -> uint16_t
template<typename T >
FMT_CONSTEXPR auto count_digits_fallback (T n) -> int
FMT_CONSTEXPR20 auto count_digits (uint64_t n) -> int
template<int BITS, typename UInt >
FMT_CONSTEXPR auto count_digits (UInt n) -> int
template<>
auto count_digits< 4 > (detail::fallback_uintptr n) -> int
FMT_INLINE uint64_t count_digits_inc (int n)
FMT_CONSTEXPR20 auto count_digits (uint32_t n) -> int
template<typename Int >
constexpr auto digits10 () FMT_NOEXCEPT -> int
template<>
constexpr auto digits10< int128_t > () FMT_NOEXCEPT -> int
template<>
constexpr auto digits10< uint128_t > () FMT_NOEXCEPT -> int
template<typename Char >
FMT_API auto thousands_sep_impl (locale_ref loc) -> thousands_sep_result< Char >
template<typename Char >
auto thousands_sep (locale_ref loc) -> thousands_sep_result< Char >
template<>
auto thousands_sep (locale_ref loc) -> thousands_sep_result< wchar_t >
template<typename Char >
FMT_API auto decimal_point_impl (locale_ref loc) -> Char
template<typename Char >
auto decimal_point (locale_ref loc) -> Char
template<>
auto decimal_point (locale_ref loc) -> wchar_t
template<typename Char >
auto equal2 (const Char *lhs, const char *rhs) -> bool
template<typename Char >
void copy2 (Char *dst, const char *src)
template<typename Char , typename UInt >
FMT_CONSTEXPR20 auto format_decimal (Char *out, UInt value, int size) -> format_decimal_result< Char * >
template<typename Char , typename UInt , typename Iterator , FMT_ENABLE_IF(!std::is_pointer< remove_cvref_t< Iterator >>::value) >
auto format_decimal (Iterator out, UInt value, int size) -> format_decimal_result< Iterator >
template<unsigned BASE_BITS, typename Char , typename UInt >
FMT_CONSTEXPR auto format_uint (Char *buffer, UInt value, int num_digits, bool upper=false) -> Char *
template<unsigned BASE_BITS, typename Char >
auto format_uint (Char *buffer, detail::fallback_uintptr n, int num_digits, bool=false) -> Char *
template<unsigned BASE_BITS, typename Char , typename It , typename UInt >
auto format_uint (It out, UInt value, int num_digits, bool upper=false) -> It
template<typename T >
FMT_API auto dragonbox::to_decimal (T x) FMT_NOEXCEPT -> decimal_fp< T >
template<typename T >
constexpr auto exponent_mask () -> typename dragonbox::float_info< T >::carrier_uint
template<typename Char , typename It >
auto write_exponent (int exp, It it) -> It
template<typename T >
auto format_float (T value, int precision, float_specs specs, buffer< char > &buf) -> int
template<typename T >
auto snprintf_float (T value, int precision, float_specs specs, buffer< char > &buf) -> int
template<typename T >
auto promote_float (T value) -> T
auto promote_float (float value) -> double
template<typename OutputIt , typename Char >
FMT_NOINLINE FMT_CONSTEXPR auto fill (OutputIt it, size_t n, const fill_t< Char > &fill) -> OutputIt
template<align::type align = align::left, typename OutputIt , typename Char , typename F >
FMT_CONSTEXPR auto write_padded (OutputIt out, const basic_format_specs< Char > &specs, size_t size, size_t width, F &&f) -> OutputIt
template<align::type align = align::left, typename OutputIt , typename Char , typename F >
constexpr auto write_padded (OutputIt out, const basic_format_specs< Char > &specs, size_t size, F &&f) -> OutputIt
template<align::type align = align::left, typename Char , typename OutputIt >
FMT_CONSTEXPR auto write_bytes (OutputIt out, string_view bytes, const basic_format_specs< Char > &specs) -> OutputIt
template<typename Char , typename OutputIt , typename UIntPtr >
auto write_ptr (OutputIt out, UIntPtr value, const basic_format_specs< Char > *specs) -> OutputIt
template<typename Char , typename OutputIt >
FMT_CONSTEXPR auto write_char (OutputIt out, Char value, const basic_format_specs< Char > &specs) -> OutputIt
template<typename Char , typename OutputIt >
FMT_CONSTEXPR auto write (OutputIt out, Char value, const basic_format_specs< Char > &specs, locale_ref loc={}) -> OutputIt
template<typename OutputIt , typename Char , typename W >
FMT_CONSTEXPR FMT_INLINE auto write_int (OutputIt out, int num_digits, unsigned prefix, const basic_format_specs< Char > &specs, W write_digits) -> OutputIt
template<typename OutputIt , typename UInt , typename Char >
auto write_int_localized (OutputIt &out, UInt value, unsigned prefix, const basic_format_specs< Char > &specs, locale_ref loc) -> bool
FMT_CONSTEXPR void prefix_append (unsigned &prefix, unsigned value)
template<typename T >
FMT_CONSTEXPR auto make_write_int_arg (T value, sign_t sign) -> write_int_arg< uint32_or_64_or_128_t< T >>
template<typename Char , typename OutputIt , typename T >
FMT_CONSTEXPR FMT_INLINE auto write_int (OutputIt out, write_int_arg< T > arg, const basic_format_specs< Char > &specs, locale_ref loc) -> OutputIt
template<typename Char , typename OutputIt , typename T , FMT_ENABLE_IF(is_integral< T >::value && !std::is_same< T, bool >::value && std::is_same< OutputIt, buffer_appender< Char >>::value) >
FMT_CONSTEXPR auto write (OutputIt out, T value, const basic_format_specs< Char > &specs, locale_ref loc) -> OutputIt
template<typename Char , typename OutputIt , typename T , FMT_ENABLE_IF(is_integral< T >::value && !std::is_same< T, bool >::value && !std::is_same< OutputIt, buffer_appender< Char >>::value) >
FMT_CONSTEXPR FMT_INLINE auto write (OutputIt out, T value, const basic_format_specs< Char > &specs, locale_ref loc) -> OutputIt
template<typename Char , typename OutputIt >
FMT_CONSTEXPR auto write (OutputIt out, basic_string_view< Char > s, const basic_format_specs< Char > &specs) -> OutputIt
template<typename Char , typename OutputIt >
FMT_CONSTEXPR auto write (OutputIt out, basic_string_view< type_identity_t< Char >> s, const basic_format_specs< Char > &specs, locale_ref) -> OutputIt
template<typename Char , typename OutputIt >
FMT_CONSTEXPR auto write (OutputIt out, const Char *s, const basic_format_specs< Char > &specs, locale_ref) -> OutputIt
template<typename Char , typename OutputIt >
auto write_nonfinite (OutputIt out, bool isinf, basic_format_specs< Char > specs, const float_specs &fspecs) -> OutputIt
auto get_significand_size (const big_decimal_fp &fp) -> int
template<typename T >
auto get_significand_size (const dragonbox::decimal_fp< T > &fp) -> int
template<typename Char , typename OutputIt >
auto write_significand (OutputIt out, const char *significand, int &significand_size) -> OutputIt
template<typename Char , typename OutputIt , typename UInt >
auto write_significand (OutputIt out, UInt significand, int significand_size) -> OutputIt
template<typename Char , typename UInt , FMT_ENABLE_IF(std::is_integral< UInt >::value) >
auto write_significand (Char *out, UInt significand, int significand_size, int integral_size, Char decimal_point) -> Char *
template<typename OutputIt , typename UInt , typename Char , FMT_ENABLE_IF(!std::is_pointer< remove_cvref_t< OutputIt >>::value) >
auto write_significand (OutputIt out, UInt significand, int significand_size, int integral_size, Char decimal_point) -> OutputIt
template<typename OutputIt , typename Char >
auto write_significand (OutputIt out, const char *significand, int significand_size, int integral_size, Char decimal_point) -> OutputIt
template<typename OutputIt , typename DecimalFP , typename Char >
auto write_float (OutputIt out, const DecimalFP &fp, const basic_format_specs< Char > &specs, float_specs fspecs, Char decimal_point) -> OutputIt
template<typename Char , typename OutputIt , typename T , FMT_ENABLE_IF(std::is_floating_point< T >::value) >
auto write (OutputIt out, T value, basic_format_specs< Char > specs, locale_ref loc={}) -> OutputIt
template<typename Char , typename OutputIt , typename T , FMT_ENABLE_IF(is_fast_float< T >::value) >
auto write (OutputIt out, T value) -> OutputIt
template<typename Char , typename OutputIt >
auto write (OutputIt out, monostate, basic_format_specs< Char >={}, locale_ref={}) -> OutputIt
template<typename Char , typename OutputIt >
FMT_CONSTEXPR auto write (OutputIt out, basic_string_view< Char > value) -> OutputIt
template<typename Char , typename OutputIt , typename T , FMT_ENABLE_IF(is_string< T >::value) >
constexpr auto write (OutputIt out, const T &value) -> OutputIt
template<typename Char , typename OutputIt , typename T , FMT_ENABLE_IF(is_integral< T >::value && !std::is_same< T, bool >::value && !std::is_same< T, Char >::value) >
FMT_CONSTEXPR auto write (OutputIt out, T value) -> OutputIt
template<typename Char , typename OutputIt , typename T , bool check = std::is_enum<T>::value && !std::is_same<T, Char>::value && mapped_type_constant<T, basic_format_context<OutputIt, Char>>::value != type::custom_type, FMT_ENABLE_IF(check) >
FMT_CONSTEXPR auto write (OutputIt out, T value) -> OutputIt
template<typename Char , typename OutputIt >
FMT_CONSTEXPR auto write (OutputIt out, Char value) -> OutputIt
template<typename Char , typename OutputIt >
FMT_CONSTEXPR_CHAR_TRAITS auto write (OutputIt out, const Char *value) -> OutputIt
template<typename Char , typename OutputIt , typename T , FMT_ENABLE_IF(std::is_same< T, void >::value) >
auto write (OutputIt out, const T *value, const basic_format_specs< Char > &specs={}, locale_ref={}) -> OutputIt
template<typename Char , typename OutputIt , typename T >
FMT_CONSTEXPR auto write (OutputIt out, const T &value) -> typename std::enable_if< mapped_type_constant< T, basic_format_context< OutputIt, Char >>::value==type::custom_type, OutputIt >::type
template<template< typename > class Handler, typename FormatArg , typename ErrorHandler >
FMT_CONSTEXPR auto get_dynamic_spec (FormatArg arg, ErrorHandler eh) -> int
template<typename Context , typename ID >
FMT_CONSTEXPR auto get_arg (Context &ctx, ID id) -> typename Context::format_arg
template<template< typename > class Handler, typename Context >
FMT_CONSTEXPR void handle_dynamic_spec (int &value, arg_ref< typename Context::char_type > ref, Context &ctx)
template<typename Locale , typename Char >
auto vformat (const Locale &loc, basic_string_view< Char > format_str, basic_format_args< buffer_context< type_identity_t< Char >>> args) -> std::basic_string< Char >
FMT_API void format_error_code (buffer< char > &out, int error_code, string_view message) FMT_NOEXCEPT
FMT_API void report_error (format_func func, int error_code, const char *message) FMT_NOEXCEPT
FMT_END_DETAIL_NAMESPACE FMT_API auto vsystem_error (int error_code, string_view format_str, format_args args) -> std::system_error
template<typename... T>
auto system_error (int error_code, format_string< T... > fmt, T &&... args) -> std::system_error
FMT_API void format_system_error (detail::buffer< char > &out, int error_code, const char *message) FMT_NOEXCEPT
FMT_API void report_system_error (int error_code, const char *message) FMT_NOEXCEPT
FMT_FORMAT_AS (signed char, int)
FMT_FORMAT_AS (unsigned char, unsigned)
FMT_FORMAT_AS (short, int)
FMT_FORMAT_AS (unsigned short, unsigned)
FMT_FORMAT_AS (long, long long)
FMT_FORMAT_AS (unsigned long, unsigned long long)
FMT_FORMAT_AS (Char *, const Char *)
FMT_FORMAT_AS (std::basic_string< Char >, basic_string_view< Char >)
FMT_FORMAT_AS (std::nullptr_t, const void *)
FMT_FORMAT_AS (detail::std_string_view< Char >, basic_string_view< Char >)
template<typename T >
auto ptr (T p) -> const void *
template<typename T >
auto ptr (const std::unique_ptr< T > &p) -> const void *
template<typename T >
auto ptr (const std::shared_ptr< T > &p) -> const void *
template<typename It , typename Sentinel >
auto join (It begin, Sentinel end, string_view sep) -> join_view< It, Sentinel >
template<typename Range >
auto join (Range &&range, string_view sep) -> join_view< detail::iterator_t< Range >, detail::sentinel_t< Range >>
template<typename T , FMT_ENABLE_IF(!std::is_integral< T >::value) >
auto to_string (const T &value) -> std::string
template<typename T , FMT_ENABLE_IF(std::is_integral< T >::value) >
auto to_string (T value) -> std::string
template<typename Char , size_t SIZE>
auto to_string (const basic_memory_buffer< Char, SIZE > &buf) -> std::basic_string< Char >
template<typename Char >
FMT_BEGIN_DETAIL_NAMESPACE void vformat_to (buffer< Char > &buf, basic_string_view< Char > fmt, basic_format_args< FMT_BUFFER_CONTEXT(type_identity_t< Char >)> args, locale_ref loc)
template FMT_API auto thousands_sep_impl< char > (locale_ref) -> thousands_sep_result< char >
template FMT_API auto thousands_sep_impl< wchar_t > (locale_ref) -> thousands_sep_result< wchar_t >
template auto format_float< double > (double value, int precision, float_specs specs, buffer< char > &buf) -> int
template auto format_float< long double > (long double value, int precision, float_specs specs, buffer< char > &buf) -> int
void snprintf_float (float, int, float_specs, buffer< char > &)=delete
template auto snprintf_float< double > (double value, int precision, float_specs specs, buffer< char > &buf) -> int
template auto snprintf_float< long double > (long double value, int precision, float_specs specs, buffer< char > &buf) -> int
template<typename Locale , FMT_ENABLE_IF(detail::is_locale< Locale >::value) >
FMT_END_DETAIL_NAMESPACE auto vformat (const Locale &loc, string_view fmt, format_args args) -> std::string
template<typename Locale , typename... T, FMT_ENABLE_IF(detail::is_locale< Locale >::value) >
auto format (const Locale &loc, format_string< T... > fmt, T &&... args) -> std::string
template<typename... T, size_t SIZE, typename Allocator >
FMT_DEPRECATED auto format_to (basic_memory_buffer< char, SIZE, Allocator > &buf, format_string< T... > fmt, T &&... args) -> appender
template<typename OutputIt , typename Locale , FMT_ENABLE_IF(detail::is_output_iterator< OutputIt, char >::value && detail::is_locale< Locale >::value) >
auto vformat_to (OutputIt out, const Locale &loc, string_view fmt, format_args args) -> OutputIt
template<typename OutputIt , typename Locale , typename... T, FMT_ENABLE_IF(detail::is_output_iterator< OutputIt, char >::value && detail::is_locale< Locale >::value) >
FMT_INLINE auto format_to (OutputIt out, const Locale &loc, format_string< T... > fmt, T &&... args) -> OutputIt
Macro Definition Documentation
FMT_CATCH
#define FMT_CATCH (x) catch (x)
Definition at line 105 of file format.h.
FMT_CONSTEXPR20
#define FMT_CONSTEXPR20
Definition at line 254 of file format.h.
FMT_CUDA_VERSION
#define FMT_CUDA_VERSION 0
Definition at line 57 of file format.h.
FMT_DEPRECATED
#define FMT_DEPRECATED /* deprecated */
Definition at line 120 of file format.h.
FMT_DEPRECATED_ALIAS
#define FMT_DEPRECATED_ALIAS FMT_DEPRECATED
Definition at line 129 of file format.h.
FMT_FORMAT_AS
#define FMT_FORMAT_AS (Type, Base)
Value:
  template <typename Char>                                               \
  struct formatter<Type, Char> : formatter<Base, Char> {                 \
    template <typename FormatContext>                                    \
    auto format(Type const& val, FormatContext& ctx) const               \
        -> decltype(ctx.out()) {                                         \
      return formatter<Base, Char>::format(static_cast<Base>(val), ctx); \
    }                                                                    \
  }
Definition at line 2352 of file format.h.
FMT_FUNC
#define FMT_FUNC
Definition at line 2827 of file format.h.
FMT_HAS_BUILTIN
#define FMT_HAS_BUILTIN (x) 0
Definition at line 63 of file format.h.
FMT_ICC_VERSION
#define FMT_ICC_VERSION 0
Definition at line 51 of file format.h.
FMT_INC
#define FMT_INC (T) (((sizeof(#T) - 1ull) << 32) - T)
FMT_MSC_DEFAULT
#define FMT_MSC_DEFAULT
Definition at line 75 of file format.h.
FMT_NOINLINE
#define FMT_NOINLINE
Definition at line 69 of file format.h.
FMT_POWERS_OF_10
#define FMT_POWERS_OF_10 (factor)
Value:
  factor * 10, (factor)*100, (factor)*1000, (factor)*10000, (factor)*100000, \
      (factor)*1000000, (factor)*10000000, (factor)*100000000,               \
      (factor)*1000000000
Definition at line 851 of file format.h.
FMT_REDUCE_INT_INSTANTIATIONS
#define FMT_REDUCE_INT_INSTANTIATIONS 0
Definition at line 148 of file format.h.
FMT_STRING
#define FMT_STRING (s) FMT_STRING_IMPL(s, fmt::compile_string,)
\rst Constructs a compile-time format string from a string literal s.
Example**::
A compile-time error because 'd' is an invalid specifier for strings. std::string s = fmt::format(FMT_STRING("{:d}"), "foo"); \endrst
Definition at line 2155 of file format.h.
FMT_STRING_IMPL
#define FMT_STRING_IMPL (s, base, explicit)
Value:
  [] {                                                                     \
    /* Use the hidden visibility as a workaround for a GCC bug (#1973). */ \
    /* Use a macro-like name to avoid shadowing warnings. */               \
    struct FMT_GCC_VISIBILITY_HIDDEN FMT_COMPILE_STRING : base {           \
      using char_type = fmt::remove_cvref_t<decltype(s[0])>;               \
      FMT_MAYBE_UNUSED FMT_CONSTEXPR explicit                              \
      operator fmt::basic_string_view<char_type>() const {                 \
        return fmt::detail_exported::compile_string_to_view<char_type>(s); \
      }                                                                    \
    };                                                                     \
    return FMT_COMPILE_STRING();                                           \
  }()
Definition at line 2131 of file format.h.
FMT_THROW
#define FMT_THROW (x) throw x
Definition at line 93 of file format.h.
FMT_TRY
#define FMT_TRY try
Definition at line 104 of file format.h.
FMT_USE_FULL_CACHE_DRAGONBOX
#define FMT_USE_FULL_CACHE_DRAGONBOX 0
Definition at line 572 of file format.h.
FMT_USE_USER_DEFINED_LITERALS
#define FMT_USE_USER_DEFINED_LITERALS 0
Definition at line 139 of file format.h.
Typedef Documentation
FMT_DEPRECATED_ALIAS
using FMT_DEPRECATED_ALIAS = join_view<It, Sentinel, Char>
Definition at line 2507 of file format.h.
format_func
using format_func = void (*)(detail::buffer<char>&, int, const char*)
Definition at line 2213 of file format.h.
is_integer
template<typename T > using is_integer = bool_constant<is_integral<T>::value && !std::is_same<T, bool>::value && !std::is_same<T, char>::value && !std::is_same<T, wchar_t>::value>
Definition at line 2010 of file format.h.
is_signed
template<typename T > using is_signed = std::integral_constant<bool, std::numeric_limits<T>::is_signed || std::is_same<T, int128_t>::value>
Definition at line 819 of file format.h.
memory_buffer
using memory_buffer = basic_memory_buffer<char>
Definition at line 736 of file format.h.
uint32_or_64_or_128_t
template<typename T > using uint32_or_64_or_128_t = conditional_t<num_bits<T>() <= 32 && !FMT_REDUCE_INT_INSTANTIATIONS, uint32_t, conditional_t<num_bits<T>() <= 64, uint64_t, uint128_t> >
Definition at line 844 of file format.h.
uint64_or_128_t
template<typename T > using uint64_or_128_t = conditional_t<num_bits<T>() <= 64, uint64_t, uint128_t>
Definition at line 849 of file format.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
inline_buffer_size
Definition at line 599 of file format.h.
 { inline_buffer_size = 500 };
Function Documentation
copy2()
template<typename Char > FMT_INLINE void copy2 (Char * dst, const char * src)
Definition at line 1035 of file format.h.
{
   *dst++ = static_cast<Char>(*src++);
   *dst = static_cast<Char>(*src);
 }
Referenced by format_decimal().
count_digits() [1/3]
template<int BITS, typename UInt > FMT_CONSTEXPR auto count_digits (UInt n) -> int
Definition at line 943 of file format.h.
{
 #ifdef FMT_BUILTIN_CLZ
   if (num_bits<UInt>() == 32)
     return (FMT_BUILTIN_CLZ(static_cast<uint32_t>(n) | 1) ^ 31) / BITS + 1;
 #endif
   int num_digits = 0;
   do {
     ++num_digits;
   } while ((n >>= BITS) != 0);
   return num_digits;
 }
References BITS.
count_digits() [2/3]
FMT_CONSTEXPR20 auto count_digits (uint32_t n) -> int inline
Definition at line 980 of file format.h.
{
 #ifdef FMT_BUILTIN_CLZ
   if (!is_constant_evaluated()) {
     auto inc = count_digits_inc(FMT_BUILTIN_CLZ(n | 1) ^ 31);
     return static_cast<int>((n + inc) >> 32);
   }
 #endif
   return count_digits_fallback(n);
 }
References count_digits_fallback(), count_digits_inc(), and is_constant_evaluated().
count_digits() [3/3]
FMT_CONSTEXPR20 auto count_digits (uint64_t n) -> int inline
Definition at line 921 of file format.h.
{
 #ifdef FMT_BUILTIN_CLZLL
   if (!is_constant_evaluated()) {
     // https://github.com/fmtlib/format-benchmark/blob/master/digits10
     // Maps bsr(n) to ceil(log10(pow(2, bsr(n) + 1) - 1)).
     constexpr uint16_t bsr2log10[] = {
         1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4,  4,  5,  5,  5,
         6,  6,  6,  7,  7,  7,  7,  8,  8,  8,  9,  9,  9,  10, 10, 10,
         10, 11, 11, 11, 12, 12, 12, 13, 13, 13, 13, 14, 14, 14, 15, 15,
         15, 16, 16, 16, 16, 17, 17, 17, 18, 18, 18, 19, 19, 19, 19, 20};
     auto t = bsr2log10[FMT_BUILTIN_CLZLL(n | 1) ^ 63];
     constexpr const uint64_t zero_or_powers_of_10[] = {
         0, 0, FMT_POWERS_OF_10(1U), FMT_POWERS_OF_10(1000000000ULL),
         10000000000000000000ULL};
     return t - (n < zero_or_powers_of_10[t]);
   }
 #endif
   return count_digits_fallback(n);
 }
References count_digits_fallback(), FMT_POWERS_OF_10, and is_constant_evaluated().
Referenced by format_decimal(), detail::format_error_code(), get_significand_size(), detail::grisu_gen_digits(), write(), chrono_formatter< FormatContext, OutputIt, Rep, Period >::write(), write_int(), and write_int_localized().
count_digits< 4 >()
template<> auto count_digits< 4 > (detail::fallback_uintptr n) -> int
Referenced by write_int(), and write_ptr().
count_digits_fallback()
template<typename T > FMT_CONSTEXPR auto count_digits_fallback (T n) -> int
Definition at line 899 of file format.h.
{
   int count = 1;
   for (;;) {
     // Integer division is slow so do it for a group of four digits instead
     // of for every digit. The idea comes from the talk by Alexandrescu
     // "Three Optimization Tips for C++". See speed-test for a comparison.
     if (n < 10) return count;
     if (n < 100) return count + 1;
     if (n < 1000) return count + 2;
     if (n < 10000) return count + 3;
     n /= 10000u;
     count += 4;
   }
 }
References count().
Referenced by count_digits().
count_digits_inc()
FMT_INLINE uint64_t count_digits_inc (int n)
Definition at line 959 of file format.h.
{
   // An optimization by Kendall Willets from https://bit.ly/3uOIQrB.
   // This increments the upper 32 bits (log10(T) - 1) when >= T is added.
 #define FMT_INC(T) (((sizeof(#T) - 1ull) << 32) - T)
   static constexpr uint64_t table[] = {
       FMT_INC(0),          FMT_INC(0),          FMT_INC(0),           // 8
       FMT_INC(10),         FMT_INC(10),         FMT_INC(10),          // 64
       FMT_INC(100),        FMT_INC(100),        FMT_INC(100),         // 512
       FMT_INC(1000),       FMT_INC(1000),       FMT_INC(1000),        // 4096
       FMT_INC(10000),      FMT_INC(10000),      FMT_INC(10000),       // 32k
       FMT_INC(100000),     FMT_INC(100000),     FMT_INC(100000),      // 256k
       FMT_INC(1000000),    FMT_INC(1000000),    FMT_INC(1000000),     // 2048k
       FMT_INC(10000000),   FMT_INC(10000000),   FMT_INC(10000000),    // 16M
       FMT_INC(100000000),  FMT_INC(100000000),  FMT_INC(100000000),   // 128M
       FMT_INC(1000000000), FMT_INC(1000000000), FMT_INC(1000000000),  // 1024M
       FMT_INC(1000000000), FMT_INC(1000000000)                        // 4B
   };
   return table[n];
 }
References FMT_INC.
Referenced by count_digits().
decimal_point() [1/2]
template<typename Char > auto decimal_point (locale_ref loc) -> Char inline
Definition at line 1019 of file format.h.
{
   return Char(decimal_point_impl<char>(loc));
 }
Referenced by write_float(), and write_significand().
decimal_point() [2/2]
template<> auto decimal_point (locale_ref loc) -> wchar_t inline
Definition at line 1022 of file format.h.
{
   return decimal_point_impl<wchar_t>(loc);
 }
decimal_point_impl()
template<typename Char > template FMT_API auto decimal_point_impl (locale_ref loc) -> Char
digits10()
template<typename Int > constexpr auto digits10 () -> int constexpr
Definition at line 990 of file format.h.
{
   return std::numeric_limits<Int>::digits10;
 }
Referenced by parse_nonnegative_int().
digits10< int128_t >()
template<> constexpr auto digits10< int128_t > () -> int constexpr
Definition at line 993 of file format.h.
{
   return 38;
 }
digits10< uint128_t >()
template<> constexpr auto digits10< uint128_t > () -> int constexpr
Definition at line 996 of file format.h.
{
   return 38;
 }
equal2()
template<typename Char > auto equal2 (const Char * lhs, const char * rhs) -> bool inline
Definition at line 1027 of file format.h.
{
   return lhs[0] == Char(rhs[0]) && lhs[1] == Char(rhs[1]);
 }
Referenced by vformat_to().
exponent_mask()
template<typename T > constexpr auto exponent_mask () -> typename dragonbox::float_info<T>::carrier_uint constexpr
Definition at line 1220 of file format.h.
{
   using uint = typename dragonbox::float_info<T>::carrier_uint;
   return ((uint(1) << dragonbox::float_info<T>::exponent_bits) - 1)
          << dragonbox::float_info<T>::significand_bits;
 }
Referenced by detail::fp::assign().
fill()
template<typename OutputIt , typename Char > FMT_NOINLINE FMT_CONSTEXPR auto fill (OutputIt it, size_t n, const fill_t< Char > & fill) -> OutputIt
Definition at line 1264 of file format.h.
{
   auto fill_size = fill.size();
   if (fill_size == 1) return detail::fill_n(it, n, fill[0]);
   auto data = fill.data();
   for (size_t i = 0; i < n; ++i)
     it = copy_str<Char>(data, data + fill_size, it);
   return it;
 }
References detail::fill_n().
Referenced by bitmap_init(), blake2b_update(), decimal2string(), inflate_table(), RealmList::LoadBuildInfo(), my_fill_8bit(), formatter< std::chrono::duration< Rep, Period >, Char >::spec_handler::on_fill(), specs_setter< Char >::on_fill(), stats_general_print(), strappend(), strfill(), and write_padded().
FMT_FORMAT_AS() [1/10]
FMT_FORMAT_AS (Char * , const Char *)
FMT_FORMAT_AS() [2/10]
FMT_FORMAT_AS (detail::std_string_view< Char > , basic_string_view< Char >)
FMT_FORMAT_AS() [3/10]
FMT_FORMAT_AS (long , long long)
FMT_FORMAT_AS() [4/10]
FMT_FORMAT_AS (short , int)
FMT_FORMAT_AS() [5/10]
FMT_FORMAT_AS (signed char , int)
FMT_FORMAT_AS() [6/10]
FMT_FORMAT_AS (std::basic_string< Char > , basic_string_view< Char >)
FMT_FORMAT_AS() [7/10]
FMT_FORMAT_AS (std::nullptr_t , const void *)
FMT_FORMAT_AS() [8/10]
FMT_FORMAT_AS (unsigned char , unsigned)
FMT_FORMAT_AS() [9/10]
FMT_FORMAT_AS (unsigned long , unsigned long long)
FMT_FORMAT_AS() [10/10]
FMT_FORMAT_AS (unsigned short , unsigned)
format()
template<typename Locale , typename... T, FMT_ENABLE_IF(detail::is_locale< Locale >::value) > auto format (const Locale & loc, format_string< T... > fmt, T &&... args) -> std::string inline
Definition at line 2784 of file format.h.
                  {
   return vformat(loc, string_view(fmt), fmt::make_format_args(args...));
 }
References fmt, make_format_args(), and vformat().
Referenced by formatter< Char[N], Char >::format(), and formatter< void *, Char >::format().
format_decimal() [1/2]
template<typename Char , typename UInt > FMT_CONSTEXPR20 auto format_decimal (Char * out, UInt value, int size) -> format_decimal_result<Char*>
Definition at line 1050 of file format.h.
{
   FMT_ASSERT(size >= count_digits(value), "invalid digit count");
   out += size;
   Char* end = out;
   if (is_constant_evaluated()) {
     while (value >= 10) {
       *--out = static_cast<Char>('0' + value % 10);
       value /= 10;
     }
     *--out = static_cast<Char>('0' + value);
     return {out, end};
   }
   while (value >= 100) {
     // Integer division is slow so do it for a group of two digits instead
     // of for every digit. The idea comes from the talk by Alexandrescu
     // "Three Optimization Tips for C++". See speed-test for a comparison.
     out -= 2;
     copy2(out, data::digits[value % 100]);
     value /= 100;
   }
   if (value < 10) {
     *--out = static_cast<Char>('0' + value);
     return {out, end};
   }
   out -= 2;
   copy2(out, data::digits[value]);
   return {out, end};
 }
References copy2(), count_digits(), basic_data< T >::digits, FMT_ASSERT, and is_constant_evaluated().
Referenced by format_decimal(), format_int::format_unsigned(), write_int_localized(), and write_significand().
format_decimal() [2/2]
template<typename Char , typename UInt , typename Iterator , FMT_ENABLE_IF(!std::is_pointer< remove_cvref_t< Iterator >>::value) > auto format_decimal (Iterator out, UInt value, int size) -> format_decimal_result<Iterator> inline
Definition at line 1082 of file format.h.
{
   // Buffer is large enough to hold all digits (digits10 + 1).
   Char buffer[digits10<UInt>() + 1];
   auto end = format_decimal(buffer, value, size).end;
   return {out, detail::copy_str_noinline<Char>(buffer, end, out)};
 }
References format_decimal().
format_error_code()
FMT_API void format_error_code (buffer< char > & out, int error_code, string_view message)
Referenced by format_system_error().
format_float()
template<typename T > auto format_float (T value, int precision, float_specs specs, buffer< char > & buf) -> int
format_float< double >()
template auto format_float< double > (double value, int precision, float_specs specs, buffer< char > & buf) -> int
format_float< long double >()
template auto format_float< long double > (long double value, int precision, float_specs specs, buffer< char > & buf) -> int
format_system_error()
FMT_API void format_system_error (detail::buffer< char > & out, int error_code, const char * message)
\rst Formats an error message for an error returned by an operating system or a language runtime, for example a file opening error, and writes it to out. The format is the same as the one used by std::system_error(ec, message) where ec is std::error_code(error_code, std::generic_category()}). It is implementation-defined but normally looks like:
.. parsed-literal:: <message>*: *<system-message>*
where *<message>* is the passed message and *<system-message>* is the system message corresponding to the error code. error_code* is a system error code as given by errno. \endrst
Definition at line 2541 of file format-inl.h.
{
   FMT_TRY {
     auto ec = std::error_code(error_code, std::generic_category());
     write(std::back_inserter(out), std::system_error(ec, message).what());
     return;
   }
   FMT_CATCH(...) {}
   format_error_code(out, error_code, message);
 }
References FMT_CATCH, FMT_TRY, format_error_code(), message(), system_error(), and write.
Referenced by report_system_error().
format_to() [1/2]
template<typename... T, size_t SIZE, typename Allocator > FMT_DEPRECATED auto format_to (basic_memory_buffer< char, SIZE, Allocator > & buf, format_string< T... > fmt, T &&... args) -> appender
Definition at line 2790 of file format.h.
                 {
   detail::vformat_to(buf, string_view(fmt), fmt::make_format_args(args...));
   return appender(buf);
 }
References fmt, make_format_args(), and vformat_to().
format_to() [2/2]
template<typename OutputIt , typename Locale , typename... T, FMT_ENABLE_IF(detail::is_output_iterator< OutputIt, char >::value && detail::is_locale< Locale >::value) > FMT_INLINE auto format_to (OutputIt out, const Locale & loc, format_string< T... > fmt, T &&... args) -> OutputIt
Definition at line 2811 of file format.h.
{
   return vformat_to(out, loc, fmt, fmt::make_format_args(args...));
 }
References fmt, make_format_args(), and vformat_to().
format_uint() [1/3]
template<unsigned BASE_BITS, typename Char > auto format_uint (Char * buffer, detail::fallback_uintptr n, int num_digits, bool = false) -> Char*
Definition at line 1105 of file format.h.
{
   auto char_digits = std::numeric_limits<unsigned char>::digits / 4;
   int start = (num_digits + char_digits - 1) / char_digits - 1;
   if (int start_digits = num_digits % char_digits) {
     unsigned value = n.value[start--];
     buffer = format_uint<BASE_BITS>(buffer, value, start_digits);
   }
   for (; start >= 0; --start) {
     unsigned value = n.value[start];
     buffer += char_digits;
     auto p = buffer;
     for (int i = 0; i < char_digits; ++i) {
       unsigned digit = (value & ((1 << BASE_BITS) - 1));
       *--p = static_cast<Char>(data::hex_digits[digit]);
       value >>= BASE_BITS;
     }
   }
   return buffer;
 }
References buffer, basic_data< T >::hex_digits, and value< Context >::value().
format_uint() [2/3]
template<unsigned BASE_BITS, typename Char , typename UInt > FMT_CONSTEXPR auto format_uint (Char * buffer, UInt value, int num_digits, bool upper = false) -> Char*
Definition at line 1091 of file format.h.
{
   buffer += num_digits;
   Char* end = buffer;
   do {
     const char* digits = upper ? "0123456789ABCDEF" : data::hex_digits;
     unsigned digit = (value & ((1 << BASE_BITS) - 1));
     *--buffer = static_cast<Char>(BASE_BITS < 4 ? static_cast<char>('0' + digit)
                                                 : digits[digit]);
   } while ((value >>= BASE_BITS) != 0);
   return end;
 }
References buffer, and basic_data< T >::hex_digits.
format_uint() [3/3]
template<unsigned BASE_BITS, typename Char , typename It , typename UInt > auto format_uint (It out, UInt value, int num_digits, bool upper = false) -> It inline
Definition at line 1127 of file format.h.
           {
   if (auto ptr = to_pointer<Char>(out, to_unsigned(num_digits))) {
     format_uint<BASE_BITS>(ptr, value, num_digits, upper);
     return out;
   }
   // Buffer should be large enough to hold all digits (digits / BASE_BITS + 1).
   char buffer[num_bits<UInt>() / BASE_BITS + 1];
   format_uint<BASE_BITS>(buffer, value, num_digits, upper);
   return detail::copy_str_noinline<Char>(buffer, buffer + num_digits, out);
 }
References ptr(), and to_unsigned().
get_arg()
template<typename Context , typename ID > FMT_CONSTEXPR auto get_arg (Context & ctx, ID id) -> typename Context::format_arg
Definition at line 2064 of file format.h.
{
   auto arg = ctx.arg(id);
   if (!arg) ctx.on_error("argument not found");
   return arg;
 }
References arg().
Referenced by specs_handler< Char >::get_arg(), specs_handler< Char >::on_dynamic_precision(), specs_handler< Char >::on_dynamic_width(), parse_header(), vformat_to(), and vprintf().
get_dynamic_spec()
template<template< typename > class Handler, typename FormatArg , typename ErrorHandler > FMT_CONSTEXPR auto get_dynamic_spec (FormatArg arg, ErrorHandler eh) -> int
Definition at line 2057 of file format.h.
{
   unsigned long long value = visit_format_arg(Handler<ErrorHandler>(eh), arg);
   if (value > to_unsigned(max_value<int>())) eh.on_error("number is too big");
   return static_cast<int>(value);
 }
References arg(), to_unsigned(), and visit_format_arg().
get_significand_size() [1/2]
auto get_significand_size (const big_decimal_fp & fp) -> int inline
Definition at line 1609 of file format.h.
{
   return fp.significand_size;
 }
Referenced by write_float().
get_significand_size() [2/2]
template<typename T > auto get_significand_size (const dragonbox::decimal_fp< T > & fp) -> int inline
Definition at line 1613 of file format.h.
{
   return count_digits(fp.significand);
 }
References count_digits().
handle_dynamic_spec()
template<template< typename > class Handler, typename Context > FMT_CONSTEXPR void handle_dynamic_spec (int & value, arg_ref< typename Context::char_type > ref, Context & ctx)
Definition at line 2114 of file format.h.
{
   switch (ref.kind) {
   case arg_id_kind::none:
     break;
   case arg_id_kind::index:
     value = detail::get_dynamic_spec<Handler>(ctx.arg(ref.val.index),
                                               ctx.error_handler());
     break;
   case arg_id_kind::name:
     value = detail::get_dynamic_spec<Handler>(ctx.arg(ref.val.name),
                                               ctx.error_handler());
     break;
   }
 }
References index, arg_ref< Char >::value::index, arg_ref< Char >::kind, name, arg_ref< Char >::value::name, none, and arg_ref< Char >::val.
is_negative()
template<typename T , FMT_ENABLE_IF(is_signed< T >::value) > FMT_CONSTEXPR auto is_negative (T value) -> bool
Definition at line 826 of file format.h.
{
   return value < 0;
 }
Referenced by detail::format_error_code(), make_write_int_arg(), printf_width_handler< Char >::operator()(), width_checker< ErrorHandler >::operator()(), precision_checker< ErrorHandler >::operator()(), and write().
is_supported_floating_point()
template<typename T , FMT_ENABLE_IF(std::is_floating_point< T >::value) > FMT_CONSTEXPR auto is_supported_floating_point (T) -> uint16_t
Definition at line 835 of file format.h.
{
   return (std::is_same<T, float>::value && FMT_USE_FLOAT) ||
          (std::is_same<T, double>::value && FMT_USE_DOUBLE) ||
          (std::is_same<T, long double>::value && FMT_USE_LONG_DOUBLE);
 }
References FMT_USE_DOUBLE, FMT_USE_FLOAT, and FMT_USE_LONG_DOUBLE.
Referenced by write().
join() [1/2]
template<typename It , typename Sentinel > auto join (It begin, Sentinel end, string_view sep) -> join_view<It, Sentinel>
Returns an object that formats the iterator range [begin, end) with elements separated by sep.
Definition at line 2562 of file format.h.
{
   return {begin, end, sep};
 }
Referenced by Acore::CreateChildProcess(), join(), mpq.Reader::read(), mpq.Reader::readline(), and WorldSession::SendLfgUpdateParty().
join() [2/2]
template<typename Range > auto join (Range && range, string_view sep) -> join_view<detail::iterator_t<Range>, detail::sentinel_t<Range>>
\rst Returns an object that formats range with elements separated by sep.
Example**::
std::vector<int> v = {1, 2, 3}; fmt::print("{}", fmt::join(v, ", ")); Output: "1, 2, 3"
fmt::join applies passed format specifiers to the range elements::
fmt::print("{:02}", fmt::join(v, ", ")); Output: "01, 02, 03" \endrst
Definition at line 2583 of file format.h.
{
   return join(std::begin(range), std::end(range), sep);
 }
References join().
make_args_checked()
template<typename... Args, typename S , typename Char = char_t<S>> FMT_INLINE auto make_args_checked (const S & fmt, const remove_reference_t< Args > &... args) -> format_arg_store<buffer_context<Char>, remove_reference_t<Args>...>
\rst Constructs a ~fmtformat_arg_store object that contains references to arguments and can be implicitly converted to ~fmtformat_args. If fmt is a compile-time string then make_args_checked checks its validity at compile time. \endrst
Definition at line 769 of file format.h.
{
   static_assert(
       detail::count<(
               std::is_base_of<detail::view, remove_reference_t<Args>>::value &&
               std::is_reference<Args>::value)...>() == 0,
       "passing views as lvalues is disallowed");
   detail::check_format_string<Args...>(fmt);
   return {args...};
 }
References check_format_string(), count(), and fmt.
Referenced by format(), format_to(), format_to_n(), and formatted_size().
make_write_int_arg()
template<typename T > FMT_CONSTEXPR auto make_write_int_arg (T value, sign_t sign) -> write_int_arg<uint32_or_64_or_128_t<T>>
Definition at line 1460 of file format.h.
{
   auto prefix = 0u;
   auto abs_value = static_cast<uint32_or_64_or_128_t<T>>(value);
   if (is_negative(value)) {
     prefix = 0x01000000 | '-';
     abs_value = 0 - abs_value;
   } else {
     prefix = data::prefixes[sign];
   }
   return {abs_value, prefix};
 }
References is_negative(), basic_data< T >::prefixes, and G3D::sign().
Referenced by write().
prefix_append()
FMT_CONSTEXPR void prefix_append (unsigned & prefix, unsigned value) inline
Definition at line 1449 of file format.h.
{
   prefix |= prefix != 0 ? value << 8 : value;
   prefix += (1u + (value > 0xff ? 1 : 0)) << 24;
 }
Referenced by write_int().
promote_float() [1/2]
auto promote_float (float value) -> double inline
Definition at line 1259 of file format.h.
{
   return static_cast<double>(value);
 }
promote_float() [2/2]
template<typename T > auto promote_float (T value) -> T
Definition at line 1258 of file format.h.
 { return value; }
ptr() [1/3]
template<typename T > auto ptr (const std::shared_ptr< T > & p) -> const void*
Definition at line 2458 of file format.h.
{
   return p.get();
 }
ptr() [2/3]
template<typename T > auto ptr (const std::unique_ptr< T > & p) -> const void*
Definition at line 2455 of file format.h.
{
   return p.get();
 }
ptr() [3/3]
template<typename T > auto ptr (T p) -> const void*
\rst Converts p to const void* for pointer formatting.
Example**::
auto s = fmt::format("{}", fmt::ptr(p)); \endrst
Definition at line 2451 of file format.h.
{
   static_assert(std::is_pointer<T>::value, "");
   return detail::bit_cast<const void*>(p);
 }
Referenced by _lf_dynarray_lvalue(), _lf_dynarray_value(), a0dalloc(), a0idalloc(), Acore::AddressOrSelf(), alloc_free(), arena_aalloc(), arena_alloc_junk_small(), arena_dalloc(), arena_dalloc_bin(), arena_dalloc_bin_junked_locked(), arena_dalloc_bin_locked_impl(), arena_dalloc_junk_small_impl(), arena_dalloc_large(), arena_dalloc_large_no_tcache(), arena_dalloc_no_tcache(), arena_dalloc_promoted(), arena_dalloc_small(), arena_prof_alloc_time_get(), arena_prof_alloc_time_set(), arena_prof_demote(), arena_prof_promote(), arena_prof_tctx_get(), arena_prof_tctx_reset(), arena_prof_tctx_set(), arena_ralloc(), arena_ralloc_no_move(), arena_reset(), arena_salloc(), arena_sdalloc(), arena_sdalloc_no_tcache(), arena_slab_reg_dalloc(), arena_slab_regind(), arena_tcache_fill_small(), arena_vsalloc(), arenas_lookup_ctl(), DBCFileLoader::AutoProduceData(), bootstrap_free(), BZ2_blockSort(), cache_bin_dalloc_easy(), check_struct_option(), CLI_MYSQL_REAL_CONNECT(), G3D::Image1uint8::copyArray(), G3D::Image3uint8::copyArray(), G3D::Image4uint8::copyArray(), create_last_word_mask(), Acore::CreateChildProcess(), G3D::GImage::decodeJPEG(), default_local_infile_end(), default_local_infile_error(), default_local_infile_init(), default_local_infile_read(), delete_dynamic_element(), dtCustomFree(), dtFree(), dtFreeDefault(), experimental_utilization_query_ctl(), extent_grow_retained(), extent_util_stats_get(), extent_util_stats_verbose_get(), find_type_or_exit(), G3D::BufferPool::flushPool(), format_uint(), G3D::BufferPool::free(), G3D::MemoryManager::free(), G3D::AlignedMemoryManager::free(), G3D::CRTMemoryManager::free(), free_default(), free_defaults(), free_fastpath(), freeSpan(), G3D::Image1uint8::fromArray(), G3D::Image3uint8::fromArray(), G3D::Image4uint8::fromArray(), G3D::Image1::fromArray(), G3D::Image3::fromArray(), G3D::Image4::fromArray(), detail::fwrite_fully(), generateMTFValues(), get_argument(), get_scode(), handleOOM(), huge_dalloc(), huge_dalloc_junk(), huge_prof_ctx_get(), huge_prof_ctx_set(), huge_ralloc(), huge_salloc(), iaalloc(), idalloc(), idalloct(), idalloctm(), iealloc(), ifree(), G3D::BufferPool::inTinyHeap(), iqalloc(), iqalloct(), iralloc(), iralloct(), iralloct_realign(), isalloc(), isdalloct(), isfree(), G3D::isNull(), ivsalloc(), ixalloc(), ixallocx_helper(), ixallocx_prof(), ixallocx_prof_sample(), je_dallocx(), je_free(), je_malloc_usable_size(), je_rallocx(), je_realloc(), je_sallocx(), je_sdallocx(), je_sdallocx_noflags(), je_xallocx(), large_dalloc_junk_impl(), large_dalloc_maybe_junk_impl(), large_ralloc(), mainQSort3(), mainSimpleSort(), mainSort(), G3D::BufferPool::malloc(), multi_alloc_root(), my_aes_create_key(), my_free(), my_get_ptr(), my_lengthsp_8bit(), my_like_range_simple(), my_load_defaults(), my_memdup(), my_multi_malloc(), my_qsort(), my_realpath(), my_search_option_files(), my_str_free_default(), my_strdup(), my_string_ptr_sort(), my_strndup(), mysql_close_free_options(), newImpl(), G3D::notNull(), WMORoot::open(), operator delete(), SFMTRand::operator delete(), operator delete[](), SFMTRand::operator delete[](), p2rz(), pages_set_thp_state(), parse_chrono_format(), prof_alloc_time_get(), prof_alloc_time_set(), prof_free(), prof_free_sampled_object(), prof_malloc(), prof_malloc_sample_object(), prof_realloc(), prof_tctx_get(), prof_tctx_reset(), prof_tctx_set(), prof_try_log(), quarantine(), radixsort_for_str_ptr(), anonymous_namespace{Recast.cpp}::rcDelete(), rcFree(), rcFreeDefault(), anonymous_namespace{Recast.cpp}::rcNew(), G3D::Array< T, MIN_ELEMENTS >::realloc(), G3D::BufferPool::realloc(), recursive_iterate(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::remove(), remove_end_comment(), safety_check_set_redzone(), safety_check_verify_redzone(), sdallocx_default(), search_default_file_with_ext(), set_prealloc_root(), sigwait(), skip_trailing_space(), soap_alloc_multipart(), soap_attachment_forward(), soap_delelement(), soap_dupelement(), soap_markelement(), soap_putelement(), soap_set_dime_attachment(), soap_set_mime_attachment(), soap_xop_forward(), tcache_bin_flush_large(), tcache_bin_flush_small(), tcache_dalloc_large(), tcache_dalloc_small(), tcache_salloc(), G3D::BufferPool::tinyFree(), G3D::BufferPool::tinyMalloc(), write(), zcfree(), zone_free(), zone_free_definite_size(), and zone_realloc().
report_error()
FMT_API void report_error (format_func func, int error_code, const char * message)
Referenced by report_system_error().
report_system_error()
FMT_API void report_system_error (int error_code, const char * message)
Definition at line 2556 of file format-inl.h.
{
   report_error(format_system_error, error_code, message);
 }
References format_system_error(), message(), and report_error().
Referenced by buffered_file::~buffered_file().
snprintf_float() [1/2]
void snprintf_float (float , int , float_specs , buffer< char > &) delete
snprintf_float() [2/2]
template<typename T > auto snprintf_float (T value, int precision, float_specs specs, buffer< char > & buf) -> int
snprintf_float< double >()
template auto snprintf_float< double > (double value, int precision, float_specs specs, buffer< char > & buf) -> int
snprintf_float< long double >()
template auto snprintf_float< long double > (long double value, int precision, float_specs specs, buffer< char > & buf) -> int
system_error()
template<typename... T> auto system_error (int error_code, format_string< T... > fmt, T &&... args) -> std::system_error
\rst Constructs :class:std::system_error with a message formatted with fmt::format(fmt, args...). error_code* is a system error code as given by errno.
Example**::
This throws std::system_error with the description cannot open file 'madeup': No such file or directory or similar (system message may vary). const char* filename = "madeup"; std::FILE* file = std::fopen(filename, "r"); if (!file) throw fmt::system_error(errno, "cannot open file '{}'", filename); \endrst
Definition at line 2243 of file format.h.
{
   return vsystem_error(error_code, fmt, fmt::make_format_args(args...));
 }
References fmt, make_format_args(), and vsystem_error().
Referenced by AsyncAcceptor::AsyncAccept(), AsyncAcceptor::AsyncAcceptWithCallback(), buffered_file::buffered_file(), buffered_file::close(), buffered_file::fileno(), format_system_error(), detail::fwrite_fully(), SocketMgr< SocketType >::OnSocketOpen(), SocketMgr< SocketType >::StartNetwork(), vprint(), vsystem_error(), and Acore::Thread::wait().
thousands_sep() [1/2]
template<typename Char > auto thousands_sep (locale_ref loc) -> thousands_sep_result<Char> inline
Definition at line 1008 of file format.h.
{
   auto result = thousands_sep_impl<char>(loc);
   return {result.grouping, Char(result.thousands_sep)};
 }
References thousands_sep_impl< char >().
Referenced by detail::thousands_sep_impl().
thousands_sep() [2/2]
template<> auto thousands_sep (locale_ref loc) -> thousands_sep_result<wchar_t> inline
Definition at line 1013 of file format.h.
{
   return thousands_sep_impl<wchar_t>(loc);
 }
References thousands_sep_impl< wchar_t >().
thousands_sep_impl()
template<typename Char > FMT_API auto thousands_sep_impl (locale_ref loc) -> thousands_sep_result< Char >
thousands_sep_impl< char >()
template FMT_API auto thousands_sep_impl< char > (locale_ref) -> thousands_sep_result< char >
Referenced by thousands_sep().
thousands_sep_impl< wchar_t >()
template FMT_API auto thousands_sep_impl< wchar_t > (locale_ref) -> thousands_sep_result< wchar_t >
Referenced by thousands_sep().
throw_format_error()
FMT_BEGIN_DETAIL_NAMESPACE void throw_format_error (const char * message) inline
Definition at line 810 of file format.h.
{
   FMT_THROW(format_error(message));
 }
References FMT_THROW, and message().
Referenced by fill_t< Char >::operator=().
to_string() [1/3]
template<typename Char , size_t SIZE> auto to_string (const basic_memory_buffer< Char, SIZE > & buf) -> std::basic_string<Char>
Definition at line 2617 of file format.h.
{
   auto size = buf.size();
   detail::assume(size < std::basic_string<Char>().max_size());
   return std::basic_string<Char>(buf.data(), size);
 }
References detail::assume().
to_string() [2/3]
template<typename T , FMT_ENABLE_IF(!std::is_integral< T >::value) > auto to_string (const T & value) -> std::string inline
\rst Converts value to std::string using the default format for type T.
Example**::
include <fmt/format.h>
std::string answer = fmt::to_string(42); \endrst
Definition at line 2600 of file format.h.
{
   auto result = std::string();
   detail::write<char>(std::back_inserter(result), value);
   return result;
 }
Referenced by Warden::ApplyPenalty(), MapUpdateRequest::call(), AuthSession::CheckIpCallback(), WorldSocket::CheckIpCallback(), Socket< T >::CloseSocket(), WheatyExceptionReport::DumpTypeIndex(), WorldSession::DosProtection::EvaluateOpcode(), Metric::FormatInfluxDBValue(), Guild::HandleAddNewRank(), WorldSocket::HandleAuthSessionCallback(), AuthSession::HandleLogonChallenge(), AuthSession::HandleLogonProof(), WorldSocket::HandlePing(), AuthSession::HandleReconnectChallenge(), AuthSession::HandleReconnectProof(), Guild::HandleSetBankTabInfo(), Guild::HandleSetRankInfo(), VMAP::StaticMapTree::LoadMapTile(), WorldSocket::LogOpcodeText(), Log::outCommand(), WorldSocket::ReadDataHandler(), WorldSocket::ReadHeaderHandler(), Metric::SendBatch(), WorldSocket::SendPacketAndLogOpcode(), World::SetInitialWorldSettings(), Socket< T >::SetNoDelay(), Acore::Impl::StringConvertImpl::For< T, std::enable_if_t< std::is_floating_point_v< T > > >::ToString(), VMAP::StaticMapTree::UnloadMapTile(), Map::Update(), UpdateFetcher::UpdateEntry(), World::UpdateSessions(), vformat(), and vsprintf().
to_string() [3/3]
template<typename T , FMT_ENABLE_IF(std::is_integral< T >::value) > auto to_string (T value) -> std::string inline
Definition at line 2607 of file format.h.
{
   // The buffer should be large enough to store the number including the sign
   // or "false" for bool.
   constexpr int max_size = detail::digits10<T>() + 2;
   char buffer[max_size > 5 ? static_cast<unsigned>(max_size) : 5];
   char* begin = buffer;
   return std::string(begin, detail::write<char>(begin, value));
 }
References buffer.
vformat() [1/2]
template<typename Locale , typename Char > auto vformat (const Locale & loc, basic_string_view< Char > format_str, basic_format_args< buffer_context< type_identity_t< Char >>> args) -> std::basic_string<Char>
Definition at line 2205 of file format.h.
{
   basic_memory_buffer<Char> buffer;
   detail::vformat_to(buffer, format_str, args, detail::locale_ref(loc));
   return {buffer.data(), buffer.size()};
 }
References buffer, buffer< T >::data(), buffer< T >::size(), and vformat_to().
Referenced by format(), and vformat().
vformat() [2/2]
template<typename Locale , FMT_ENABLE_IF(detail::is_locale< Locale >::value) > FMT_END_DETAIL_NAMESPACE auto vformat (const Locale & loc, string_view fmt, format_args args) -> std::string inline
Definition at line 2777 of file format.h.
                  {
   return detail::vformat(loc, fmt, args);
 }
References fmt, and vformat().
vformat_to() [1/2]
template<typename Char > FMT_BEGIN_DETAIL_NAMESPACE void vformat_to (buffer< Char > & buf, basic_string_view< Char > fmt, basic_format_args< FMT_BUFFER_CONTEXT(type_identity_t< Char >)> args, locale_ref loc)
Definition at line 2627 of file format.h.
                     {
   // workaround for msvc bug regarding name-lookup in module
   // link names into function scope
   using detail::arg_formatter;
   using detail::buffer_appender;
   using detail::custom_formatter;
   using detail::default_arg_formatter;
   using detail::get_arg;
   using detail::locale_ref;
   using detail::parse_format_specs;
   using detail::specs_checker;
   using detail::specs_handler;
   using detail::to_unsigned;
   using detail::type;
   using detail::write;
   auto out = buffer_appender<Char>(buf);
   if (fmt.size() == 2 && equal2(fmt.data(), "{}")) {
     auto arg = args.get(0);
     if (!arg) error_handler().on_error("argument not found");
     visit_format_arg(default_arg_formatter<Char>{out, args, loc}, arg);
     return;
   }
   struct format_handler : error_handler {
     basic_format_parse_context<Char> parse_context;
     buffer_context<Char> context;
     format_handler(buffer_appender<Char> out, basic_string_view<Char> str,
                    basic_format_args<buffer_context<Char>> args, locale_ref loc)
         : parse_context(str), context(out, args, loc) {}
     void on_text(const Char* begin, const Char* end) {
       auto text = basic_string_view<Char>(begin, to_unsigned(end - begin));
       context.advance_to(write<Char>(context.out(), text));
     }
     FMT_CONSTEXPR auto on_arg_id() -> int {
       return parse_context.next_arg_id();
     }
     FMT_CONSTEXPR auto on_arg_id(int id) -> int {
       return parse_context.check_arg_id(id), id;
     }
     FMT_CONSTEXPR auto on_arg_id(basic_string_view<Char> id) -> int {
       int arg_id = context.arg_id(id);
       if (arg_id < 0) on_error("argument not found");
       return arg_id;
     }
     FMT_INLINE void on_replacement_field(int id, const Char*) {
       auto arg = get_arg(context, id);
       context.advance_to(visit_format_arg(
           default_arg_formatter<Char>{context.out(), context.args(),
                                       context.locale()},
           arg));
     }
     auto on_format_specs(int id, const Char* begin, const Char* end)
         -> const Char* {
       auto arg = get_arg(context, id);
       if (arg.type() == type::custom_type) {
         parse_context.advance_to(parse_context.begin() +
                                  (begin - &*parse_context.begin()));
         visit_format_arg(custom_formatter<Char>{parse_context, context}, arg);
         return parse_context.begin();
       }
       auto specs = basic_format_specs<Char>();
       specs_checker<specs_handler<Char>> handler(
           specs_handler<Char>(specs, parse_context, context), arg.type());
       begin = parse_format_specs(begin, end, handler);
       if (begin == end || *begin != '}')
         on_error("missing '}' in format string");
       auto f = arg_formatter<Char>{context.out(), specs, context.locale()};
       context.advance_to(visit_format_arg(f, arg));
       return begin;
     }
   };
   detail::parse_format_string<false>(fmt, format_handler(out, fmt, args, loc));
 }
References basic_format_parse_context< Char, ErrorHandler >::advance_to(), basic_format_context< OutputIt, Char >::advance_to(), arg(), basic_format_context< OutputIt, Char >::arg_id(), basic_format_context< OutputIt, Char >::args(), basic_format_parse_context< Char, ErrorHandler >::begin(), basic_format_parse_context< Char, ErrorHandler >::check_arg_id(), custom_type, equal2(), f(), fmt, FMT_CONSTEXPR, FMT_INLINE, get_arg(), basic_format_context< OutputIt, Char >::locale(), basic_format_parse_context< Char, ErrorHandler >::next_arg_id(), error_handler::on_error(), basic_format_context< OutputIt, Char >::out(), parse_format_specs(), to_unsigned(), visit_format_arg(), and detail::write().
Referenced by format_to(), formatted_size(), vformat(), vformat_to(), and vformat_to_n().
vformat_to() [2/2]
template<typename OutputIt , typename Locale , FMT_ENABLE_IF(detail::is_output_iterator< OutputIt, char >::value && detail::is_locale< Locale >::value) > auto vformat_to (OutputIt out, const Locale & loc, string_view fmt, format_args args) -> OutputIt
Definition at line 2800 of file format.h.
{
   using detail::get_buffer;
   auto&& buf = get_buffer<char>(out);
   detail::vformat_to(buf, fmt, args, detail::locale_ref(loc));
   return detail::get_iterator(buf);
 }
References fmt, get_buffer(), get_iterator(), and vformat_to().
vsystem_error()
FMT_END_DETAIL_NAMESPACE FMT_API auto vsystem_error (int error_code, string_view format_str, format_args args) -> std::system_error
Definition at line 132 of file format-inl.h.
{
   auto ec = std::error_code(error_code, std::generic_category());
   return std::system_error(ec, vformat(format_str, args));
 }
References system_error(), and vformat().
Referenced by system_error().
write() [1/17]
template<typename Char , typename OutputIt > FMT_CONSTEXPR auto write (OutputIt out, basic_string_view< Char > s, const basic_format_specs< Char > & specs) -> OutputIt
Definition at line 1554 of file format.h.
{
   auto data = s.data();
   auto size = s.size();
   if (specs.precision >= 0 && to_unsigned(specs.precision) < size)
     size = code_point_index(s, to_unsigned(specs.precision));
   auto width =
       specs.width != 0 ? compute_width(basic_string_view<Char>(data, size)) : 0;
   return write_padded(out, specs, size, width,
                       [=](reserve_iterator<OutputIt> it) {
                         return copy_str<Char>(data, data + size, it);
                       });
 }
References detail::code_point_index(), detail::compute_width(), basic_string_view< Char >::data(), basic_format_specs< Char >::precision, basic_string_view< Char >::size(), to_unsigned(), basic_format_specs< Char >::width, width, and write_padded().
write() [2/17]
template<typename Char , typename OutputIt > FMT_CONSTEXPR auto write (OutputIt out, basic_string_view< Char > value) -> OutputIt
Definition at line 1857 of file format.h.
                 {
   auto it = reserve(out, value.size());
   it = copy_str_noinline<Char>(value.begin(), value.end(), it);
   return base_iterator(out, it);
 }
References detail::base_iterator(), and detail::reserve().
write() [3/17]
template<typename Char , typename OutputIt > FMT_CONSTEXPR auto write (OutputIt out, basic_string_view< type_identity_t< Char >> s, const basic_format_specs< Char > & specs, locale_ref) -> OutputIt
Definition at line 1568 of file format.h.
                 {
   check_string_type_spec(specs.type);
   return write(out, s, specs);
 }
References check_string_type_spec(), basic_format_specs< Char >::type, and write().
write() [4/17]
template<typename Char , typename OutputIt > FMT_CONSTEXPR auto write (OutputIt out, Char value) -> OutputIt
Definition at line 1916 of file format.h.
{
   auto it = reserve(out, 1);
   *it++ = value;
   return base_iterator(out, it);
 }
References detail::base_iterator(), and detail::reserve().
write() [5/17]
template<typename Char , typename OutputIt > FMT_CONSTEXPR auto write (OutputIt out, Char value, const basic_format_specs< Char > & specs, locale_ref loc = {}) -> OutputIt
Definition at line 1338 of file format.h.
                                           {}) -> OutputIt {
   return check_char_specs(specs)
              ? write_char(out, value, specs)
              : write(out, static_cast<int>(value), specs, loc);
 }
Referenced by write(), write_float(), and write_ptr().
write() [6/17]
template<typename Char , typename OutputIt > FMT_CONSTEXPR auto write (OutputIt out, const Char * s, const basic_format_specs< Char > & specs, locale_ref) -> OutputIt
Definition at line 1576 of file format.h.
                 {
   return check_cstring_type_spec(specs.type)
              ? write(out, basic_string_view<Char>(s), specs, {})
              : write_ptr<Char>(out, to_uintptr(s), &specs);
 }
References check_cstring_type_spec(), detail::to_uintptr(), basic_format_specs< Char >::type, and write().
write() [7/17]
template<typename Char , typename OutputIt > FMT_CONSTEXPR_CHAR_TRAITS auto write (OutputIt out, const Char * value) -> OutputIt
Definition at line 1923 of file format.h.
                 {
   if (!value) {
     FMT_THROW(format_error("string pointer is null"));
   } else {
     auto length = std::char_traits<Char>::length(value);
     out = write(out, basic_string_view<Char>(value, length));
   }
   return out;
 }
References FMT_THROW, G3D::length(), and write().
write() [8/17]
template<typename Char , typename OutputIt , typename T , FMT_ENABLE_IF(is_string< T >::value) > constexpr auto write (OutputIt out, const T & value) -> OutputIt constexpr
Definition at line 1866 of file format.h.
{
   return write<Char>(out, to_string_view(value));
 }
References to_string_view().
write() [9/17]
template<typename Char , typename OutputIt , typename T > FMT_CONSTEXPR auto write (OutputIt out, const T & value) -> typename std::enable_if< mapped_type_constant<T, basic_format_context<OutputIt, Char>>::value == type::custom_type, OutputIt>::type
Definition at line 1944 of file format.h.
                       {
   using context_type = basic_format_context<OutputIt, Char>;
   using formatter_type =
       conditional_t<has_formatter<T, context_type>::value,
                     typename context_type::template formatter_type<T>,
                     fallback_formatter<T, Char>>;
   context_type ctx(out, {}, {});
   return formatter_type().format(value, ctx);
 }
write() [10/17]
template<typename Char , typename OutputIt , typename T , FMT_ENABLE_IF(std::is_same< T, void >::value) > auto write (OutputIt out, const T * value, const basic_format_specs< Char > & specs = {}, locale_ref = {}) -> OutputIt
Definition at line 1936 of file format.h.
                                                    {}, locale_ref = {})
     -> OutputIt {
   check_pointer_type_spec(specs.type, error_handler());
   return write_ptr<Char>(out, to_uintptr(value), &specs);
 }
write() [11/17]
template<typename Char , typename OutputIt > auto write (OutputIt out, monostate , basic_format_specs< Char > = {}, locale_ref = {}) -> OutputIt
Definition at line 1850 of file format.h.
                                                                {},
            locale_ref = {}) -> OutputIt {
   FMT_ASSERT(false, "");
   return out;
 }
write() [12/17]
template<typename Char , typename OutputIt , typename T , FMT_ENABLE_IF(is_fast_float< T >::value) > auto write (OutputIt out, T value) -> OutputIt inline
Definition at line 1819 of file format.h.
{
   if (const_check(!is_supported_floating_point(value))) return out;
   using floaty = conditional_t<std::is_same<T, long double>::value, double, T>;
   using uint = typename dragonbox::float_info<floaty>::carrier_uint;
   auto bits = bit_cast<uint>(value);
   auto fspecs = float_specs();
   auto sign_bit = bits & (uint(1) << (num_bits<uint>() - 1));
   if (sign_bit != 0) {
     fspecs.sign = sign::minus;
     value = -value;
   }
   static const auto specs = basic_format_specs<Char>();
   uint mask = exponent_mask<floaty>();
   if ((bits & mask) == mask)
     return write_nonfinite(out, std::isinf(value), specs, fspecs);
   auto dec = dragonbox::to_decimal(static_cast<floaty>(value));
   return write_float(out, dec, specs, fspecs, static_cast<Char>('.'));
 }
References G3D::bits(), const_check(), is_supported_floating_point(), sign::minus, float_specs::sign, dragonbox::to_decimal(), write_float(), and write_nonfinite().
write() [13/17]
template<typename Char , typename OutputIt , typename T , FMT_ENABLE_IF(is_integral< T >::value && !std::is_same< T, bool >::value && !std::is_same< T, Char >::value) > FMT_CONSTEXPR auto write (OutputIt out, T value) -> OutputIt
Definition at line 1874 of file format.h.
{
   auto abs_value = static_cast<uint32_or_64_or_128_t<T>>(value);
   bool negative = is_negative(value);
   // Don't do -abs_value since it trips unsigned-integer-overflow sanitizer.
   if (negative) abs_value = ~abs_value + 1;
   int num_digits = count_digits(abs_value);
   auto size = (negative ? 1 : 0) + static_cast<size_t>(num_digits);
   auto it = reserve(out, size);
   if (auto ptr = to_pointer<Char>(it, size)) {
     if (negative) *ptr++ = static_cast<Char>('-');
     format_decimal<Char>(ptr, abs_value, num_digits);
     return out;
   }
   if (negative) *it++ = static_cast<Char>('-');
   it = format_decimal<Char>(it, abs_value, num_digits).end;
   return base_iterator(out, it);
 }
References detail::base_iterator(), count_digits(), is_negative(), ptr(), and detail::reserve().
write() [14/17]
template<typename Char , typename OutputIt , typename T , bool check = std::is_enum<T>::value && !std::is_same<T, Char>::value && mapped_type_constant<T, basic_format_context<OutputIt, Char>>::value != type::custom_type, FMT_ENABLE_IF(check) > FMT_CONSTEXPR auto write (OutputIt out, T value) -> OutputIt
Definition at line 1900 of file format.h.
{
   return write<Char>(
       out, static_cast<typename std::underlying_type<T>::type>(value));
 }
write() [15/17]
template<typename Char , typename OutputIt , typename T , FMT_ENABLE_IF(std::is_floating_point< T >::value) > auto write (OutputIt out, T value, basic_format_specs< Char > specs, locale_ref loc = {}) -> OutputIt
Definition at line 1770 of file format.h.
                             {}) -> OutputIt {
   if (const_check(!is_supported_floating_point(value))) return out;
   float_specs fspecs = parse_float_type_spec(specs);
   fspecs.sign = specs.sign;
   if (std::signbit(value)) {  // value < 0 is false for NaN so use signbit.
     fspecs.sign = sign::minus;
     value = -value;
   } else if (fspecs.sign == sign::minus) {
     fspecs.sign = sign::none;
   }
   if (!std::isfinite(value))
     return write_nonfinite(out, std::isinf(value), specs, fspecs);
   if (specs.align == align::numeric && fspecs.sign) {
     auto it = reserve(out, 1);
     *it++ = static_cast<Char>(data::signs[fspecs.sign]);
     out = base_iterator(out, it);
     fspecs.sign = sign::none;
     if (specs.width != 0) --specs.width;
   }
   memory_buffer buffer;
   if (fspecs.format == float_format::hex) {
     if (fspecs.sign) buffer.push_back(data::signs[fspecs.sign]);
     snprintf_float(promote_float(value), specs.precision, fspecs, buffer);
     return write_bytes<align::right>(out, {buffer.data(), buffer.size()},
                                      specs);
   }
   int precision = specs.precision >= 0 || !specs.type ? specs.precision : 6;
   if (fspecs.format == float_format::exp) {
     if (precision == max_value<int>())
       FMT_THROW(format_error("number is too big"));
     else
       ++precision;
   }
   if (const_check(std::is_same<T, float>())) fspecs.binary32 = true;
   fspecs.use_grisu = is_fast_float<T>();
   int exp = format_float(promote_float(value), precision, fspecs, buffer);
   fspecs.precision = precision;
   Char point =
       fspecs.locale ? decimal_point<Char>(loc) : static_cast<Char>('.');
   auto fp = big_decimal_fp{buffer.data(), static_cast<int>(buffer.size()), exp};
   return write_float(out, fp, specs, fspecs, point);
 }
write() [16/17]
template<typename Char , typename OutputIt , typename T , FMT_ENABLE_IF(is_integral< T >::value && !std::is_same< T, bool >::value && std::is_same< OutputIt, buffer_appender< Char >>::value) > FMT_CONSTEXPR auto write (OutputIt out, T value, const basic_format_specs< Char > & specs = {}, locale_ref loc = {}) -> OutputIt
Definition at line 1537 of file format.h.
                 {
   return write_int(out, make_write_int_arg(value, specs.sign), specs, loc);
 }
References make_write_int_arg(), basic_format_specs< Char >::sign, and write_int().
write() [17/17]
template<typename Char , typename OutputIt , typename T , FMT_ENABLE_IF(is_integral< T >::value && !std::is_same< T, bool >::value && !std::is_same< OutputIt, buffer_appender< Char >>::value) > FMT_CONSTEXPR FMT_INLINE auto write (OutputIt out, T value, const basic_format_specs< Char > & specs, locale_ref loc) -> OutputIt
Definition at line 1547 of file format.h.
{
   return write_int(out, make_write_int_arg(value, specs.sign), specs, loc);
 }
References make_write_int_arg(), basic_format_specs< Char >::sign, and write_int().
write_bytes()
template<align::type align = align::left, typename Char , typename OutputIt > FMT_CONSTEXPR auto write_bytes (OutputIt out, string_view bytes, const basic_format_specs< Char > & specs) -> OutputIt
Definition at line 1304 of file format.h.
                 {
   return write_padded<align>(
       out, specs, bytes.size(), [bytes](reserve_iterator<OutputIt> it) {
         const char* data = bytes.data();
         return copy_str<Char>(data, data + bytes.size(), it);
       });
 }
Referenced by formatter< bytes >::format(), formatter< std::error_code, Char >::format(), and printf_arg_formatter< OutputIt, Char >::write_null_pointer().
write_char()
template<typename Char , typename OutputIt > FMT_CONSTEXPR auto write_char (OutputIt out, Char value, const basic_format_specs< Char > & specs) -> OutputIt
Definition at line 1329 of file format.h.
                 {
   return write_padded(out, specs, 1, [=](reserve_iterator<OutputIt> it) {
     *it++ = value;
     return it;
   });
 }
References write_padded().
Referenced by write_int().
write_exponent()
template<typename Char , typename It > auto write_exponent (int exp, It it) -> It
Definition at line 1229 of file format.h.
{
   FMT_ASSERT(-10000 < exp && exp < 10000, "exponent out of range");
   if (exp < 0) {
     *it++ = static_cast<Char>('-');
     exp = -exp;
   } else {
     *it++ = static_cast<Char>('+');
   }
   if (exp >= 100) {
     const char* top = data::digits[exp / 100];
     if (exp >= 1000) *it++ = static_cast<Char>(top[0]);
     *it++ = static_cast<Char>(top[1]);
     exp %= 100;
   }
   const char* d = data::digits[exp];
   *it++ = static_cast<Char>(d[0]);
   *it++ = static_cast<Char>(d[1]);
   return it;
 }
References mpq::d, basic_data< T >::digits, exp, and FMT_ASSERT.
write_float()
template<typename OutputIt , typename DecimalFP , typename Char > auto write_float (OutputIt out, const DecimalFP & fp, const basic_format_specs< Char > & specs, float_specs fspecs, Char decimal_point) -> OutputIt
Definition at line 1670 of file format.h.
{
   auto significand = fp.significand;
   int significand_size = get_significand_size(fp);
   static const Char zero = static_cast<Char>('0');
   auto sign = fspecs.sign;
   size_t size = to_unsigned(significand_size) + (sign ? 1 : 0);
   using iterator = reserve_iterator<OutputIt>;
   int output_exp = fp.exponent + significand_size - 1;
   auto use_exp_format = [=]() {
     if (fspecs.format == float_format::exp) return true;
     if (fspecs.format != float_format::general) return false;
     // Use the fixed notation if the exponent is in [exp_lower, exp_upper),
     // e.g. 0.0001 instead of 1e-04. Otherwise use the exponent notation.
     const int exp_lower = -4, exp_upper = 16;
     return output_exp < exp_lower ||
            output_exp >= (fspecs.precision > 0 ? fspecs.precision : exp_upper);
   };
   if (use_exp_format()) {
     int num_zeros = 0;
     if (fspecs.showpoint) {
       num_zeros = fspecs.precision - significand_size;
       if (num_zeros < 0) num_zeros = 0;
       size += to_unsigned(num_zeros);
     } else if (significand_size == 1) {
       decimal_point = Char();
     }
     auto abs_output_exp = output_exp >= 0 ? output_exp : -output_exp;
     int exp_digits = 2;
     if (abs_output_exp >= 100) exp_digits = abs_output_exp >= 1000 ? 4 : 3;
     size += to_unsigned((decimal_point ? 1 : 0) + 2 + exp_digits);
     char exp_char = fspecs.upper ? 'E' : 'e';
     auto write = [=](iterator it) {
       if (sign) *it++ = static_cast<Char>(data::signs[sign]);
       // Insert a decimal point after the first digit and add an exponent.
       it = write_significand(it, significand, significand_size, 1,
                              decimal_point);
       if (num_zeros > 0) it = detail::fill_n(it, num_zeros, zero);
       *it++ = static_cast<Char>(exp_char);
       return write_exponent<Char>(output_exp, it);
     };
     return specs.width > 0 ? write_padded<align::right>(out, specs, size, write)
                            : base_iterator(out, write(reserve(out, size)));
   }
   int exp = fp.exponent + significand_size;
   if (fp.exponent >= 0) {
     // 1234e5 -> 123400000[.0+]
     size += to_unsigned(fp.exponent);
     int num_zeros = fspecs.precision - exp;
 #ifdef FMT_FUZZ
     if (num_zeros > 5000)
       throw std::runtime_error("fuzz mode - avoiding excessive cpu use");
 #endif
     if (fspecs.showpoint) {
       if (num_zeros <= 0 && fspecs.format != float_format::fixed) num_zeros = 1;
       if (num_zeros > 0) size += to_unsigned(num_zeros) + 1;
     }
     return write_padded<align::right>(out, specs, size, [&](iterator it) {
       if (sign) *it++ = static_cast<Char>(data::signs[sign]);
       it = write_significand<Char>(it, significand, significand_size);
       it = detail::fill_n(it, fp.exponent, zero);
       if (!fspecs.showpoint) return it;
       *it++ = decimal_point;
       return num_zeros > 0 ? detail::fill_n(it, num_zeros, zero) : it;
     });
   } else if (exp > 0) {
     // 1234e-2 -> 12.34[0+]
     int num_zeros = fspecs.showpoint ? fspecs.precision - significand_size : 0;
     size += 1 + to_unsigned(num_zeros > 0 ? num_zeros : 0);
     return write_padded<align::right>(out, specs, size, [&](iterator it) {
       if (sign) *it++ = static_cast<Char>(data::signs[sign]);
       it = write_significand(it, significand, significand_size, exp,
                              decimal_point);
       return num_zeros > 0 ? detail::fill_n(it, num_zeros, zero) : it;
     });
   }
   // 1234e-6 -> 0.001234
   int num_zeros = -exp;
   if (significand_size == 0 && fspecs.precision >= 0 &&
       fspecs.precision < num_zeros) {
     num_zeros = fspecs.precision;
   }
   bool pointy = num_zeros != 0 || significand_size != 0 || fspecs.showpoint;
   size += 1 + (pointy ? 1 : 0) + to_unsigned(num_zeros);
   return write_padded<align::right>(out, specs, size, [&](iterator it) {
     if (sign) *it++ = static_cast<Char>(data::signs[sign]);
     *it++ = zero;
     if (!pointy) return it;
     *it++ = decimal_point;
     it = detail::fill_n(it, num_zeros, zero);
     return write_significand<Char>(it, significand, significand_size);
   });
 }
References detail::base_iterator(), decimal_point(), exp, detail::fill_n(), fixed, general, get_significand_size(), detail::reserve(), G3D::sign(), basic_data< T >::signs, to_unsigned(), basic_format_specs< Char >::width, write(), write_significand(), and G3D::zero().
Referenced by write().
write_int() [1/2]
template<typename OutputIt , typename Char , typename W > FMT_CONSTEXPR FMT_INLINE auto write_int (OutputIt out, int num_digits, unsigned prefix, const basic_format_specs< Char > & specs, W write_digits) -> OutputIt
Definition at line 1373 of file format.h.
{
   // Slightly faster check for specs.width == 0 && specs.precision == -1.
   if ((specs.width | (specs.precision + 1)) == 0) {
     auto it = reserve(out, to_unsigned(num_digits) + (prefix >> 24));
     if (prefix != 0) {
       for (unsigned p = prefix & 0xffffff; p != 0; p >>= 8)
         *it++ = static_cast<Char>(p & 0xff);
     }
     return base_iterator(out, write_digits(it));
   }
   auto data = write_int_data<Char>(num_digits, prefix, specs);
   return write_padded<align::right>(
       out, specs, data.size, [=](reserve_iterator<OutputIt> it) {
         for (unsigned p = prefix & 0xffffff; p != 0; p >>= 8)
           *it++ = static_cast<Char>(p & 0xff);
         it = detail::fill_n(it, data.padding, static_cast<Char>('0'));
         return write_digits(it);
       });
 }
References detail::base_iterator(), basic_format_specs< Char >::precision, detail::reserve(), to_unsigned(), and basic_format_specs< Char >::width.
Referenced by write(), and write_int().
write_int() [2/2]
template<typename Char , typename OutputIt , typename T > FMT_CONSTEXPR FMT_INLINE auto write_int (OutputIt out, write_int_arg< T > arg, const basic_format_specs< Char > & specs, locale_ref loc) -> OutputIt
Definition at line 1474 of file format.h.
{
   static_assert(std::is_same<T, uint32_or_64_or_128_t<T>>::value, "");
   auto abs_value = arg.abs_value;
   auto prefix = arg.prefix;
   auto utype = static_cast<unsigned>(specs.type);
   switch (specs.type) {
   case 0:
   case 'd': {
     if (specs.localized &&
         write_int_localized(out, static_cast<uint64_or_128_t<T>>(abs_value),
                             prefix, specs, loc)) {
       return out;
     }
     auto num_digits = count_digits(abs_value);
     return write_int(
         out, num_digits, prefix, specs, [=](reserve_iterator<OutputIt> it) {
           return format_decimal<Char>(it, abs_value, num_digits).end;
         });
   }
   case 'x':
   case 'X': {
     if (specs.alt) prefix_append(prefix, (utype << 8) | '0');
     bool upper = specs.type != 'x';
     int num_digits = count_digits<4>(abs_value);
     return write_int(
         out, num_digits, prefix, specs, [=](reserve_iterator<OutputIt> it) {
           return format_uint<4, Char>(it, abs_value, num_digits, upper);
         });
   }
   case 'b':
   case 'B': {
     if (specs.alt) prefix_append(prefix, (utype << 8) | '0');
     int num_digits = count_digits<1>(abs_value);
     return write_int(out, num_digits, prefix, specs,
                      [=](reserve_iterator<OutputIt> it) {
                        return format_uint<1, Char>(it, abs_value, num_digits);
                      });
   }
   case 'o': {
     int num_digits = count_digits<3>(abs_value);
     if (specs.alt && specs.precision <= num_digits && abs_value != 0) {
       // Octal prefix '0' is counted as a digit, so only add it if precision
       // is not greater than the number of digits.
       prefix_append(prefix, '0');
     }
     return write_int(out, num_digits, prefix, specs,
                      [=](reserve_iterator<OutputIt> it) {
                        return format_uint<3, Char>(it, abs_value, num_digits);
                      });
   }
   case 'c':
     return write_char(out, static_cast<Char>(abs_value), specs);
   default:
     FMT_THROW(format_error("invalid type specifier"));
   }
   return out;
 }
References basic_format_specs< Char >::alt, arg(), count_digits(), count_digits< 4 >(), FMT_THROW, basic_format_specs< Char >::localized, basic_format_specs< Char >::precision, prefix_append(), basic_format_specs< Char >::type, write_char(), write_int(), and write_int_localized().
write_int_localized()
template<typename OutputIt , typename UInt , typename Char > auto write_int_localized (OutputIt & out, UInt value, unsigned prefix, const basic_format_specs< Char > & specs, locale_ref loc) -> bool
Definition at line 1397 of file format.h.
             {
   static_assert(std::is_same<uint64_or_128_t<UInt>, UInt>::value, "");
   const auto sep_size = 1;
   auto ts = thousands_sep<Char>(loc);
   if (!ts.thousands_sep) return false;
   int num_digits = count_digits(value);
   int size = num_digits, n = num_digits;
   const std::string& groups = ts.grouping;
   std::string::const_iterator group = groups.cbegin();
   while (group != groups.cend() && n > *group && *group > 0 &&
          *group != max_value<char>()) {
     size += sep_size;
     n -= *group;
     ++group;
   }
   if (group == groups.cend()) size += sep_size * ((n - 1) / groups.back());
   char digits[40];
   format_decimal(digits, value, num_digits);
   basic_memory_buffer<Char> buffer;
   if (prefix != 0) ++size;
   const auto usize = to_unsigned(size);
   buffer.resize(usize);
   basic_string_view<Char> s(&ts.thousands_sep, sep_size);
   // Index of a decimal digit with the least significant digit having index 0.
   int digit_index = 0;
   group = groups.cbegin();
   auto p = buffer.data() + size - 1;
   for (int i = num_digits - 1; i > 0; --i) {
     *p-- = static_cast<Char>(digits[i]);
     if (*group <= 0 || ++digit_index % *group != 0 ||
         *group == max_value<char>())
       continue;
     if (group + 1 != groups.cend()) {
       digit_index = 0;
       ++group;
     }
     std::uninitialized_copy(s.data(), s.data() + s.size(),
                             make_checked(p, s.size()));
     p -= s.size();
   }
   *p-- = static_cast<Char>(*digits);
   if (prefix != 0) *p = static_cast<Char>(prefix);
   auto data = buffer.data();
   out = write_padded<align::right>(
       out, specs, usize, usize, [=](reserve_iterator<OutputIt> it) {
         return copy_str<Char>(data, data + size, it);
       });
   return true;
 }
References buffer, count_digits(), basic_string_view< Char >::data(), buffer< T >::data(), format_decimal(), detail::make_checked(), basic_string_view< Char >::size(), and to_unsigned().
Referenced by write_int().
write_nonfinite()
template<typename Char , typename OutputIt > auto write_nonfinite (OutputIt out, bool isinf, basic_format_specs< Char > specs, const float_specs & fspecs) -> OutputIt
Definition at line 1585 of file format.h.
{
   auto str =
       isinf ? (fspecs.upper ? "INF" : "inf") : (fspecs.upper ? "NAN" : "nan");
   constexpr size_t str_size = 3;
   auto sign = fspecs.sign;
   auto size = str_size + (sign ? 1 : 0);
   // Replace '0'-padding with space for non-finite values.
   const bool is_zero_fill =
       specs.fill.size() == 1 && *specs.fill.data() == static_cast<Char>('0');
   if (is_zero_fill) specs.fill[0] = static_cast<Char>(' ');
   return write_padded(out, specs, size, [=](reserve_iterator<OutputIt> it) {
     if (sign) *it++ = static_cast<Char>(data::signs[sign]);
     return copy_str<Char>(str, str + str_size, it);
   });
 }
References basic_format_specs< Char >::fill, basic_data< T >::signs, and write_padded().
Referenced by write().
write_padded() [1/2]
template<align::type align = align::left, typename OutputIt , typename Char , typename F > constexpr auto write_padded (OutputIt out, const basic_format_specs< Char > & specs, size_t size, F && f) -> OutputIt constexpr
Definition at line 1298 of file format.h.
{
   return write_padded<align>(out, specs, size, size, f);
 }
References f().
write_padded() [2/2]
template<align::type align = align::left, typename OutputIt , typename Char , typename F > FMT_CONSTEXPR auto write_padded (OutputIt out, const basic_format_specs< Char > & specs, size_t size, size_t width, F && f) -> OutputIt
Definition at line 1279 of file format.h.
{
   static_assert(align == align::left || align == align::right, "");
   unsigned spec_width = to_unsigned(specs.width);
   size_t padding = spec_width > width ? spec_width - width : 0;
   auto* shifts = align == align::left ? data::left_padding_shifts
                                       : data::right_padding_shifts;
   size_t left_padding = padding >> shifts[specs.align];
   size_t right_padding = padding - left_padding;
   auto it = reserve(out, size + padding * specs.fill.size());
   if (left_padding != 0) it = fill(it, left_padding, specs.fill);
   it = f(it);
   if (right_padding != 0) it = fill(it, right_padding, specs.fill);
   return base_iterator(out, it);
 }
References detail::base_iterator(), f(), fill(), align::left, basic_data< T >::left_padding_shifts, detail::reserve(), align::right, basic_data< T >::right_padding_shifts, to_unsigned(), and width.
Referenced by write(), write_char(), and write_nonfinite().
write_ptr()
template<typename Char , typename OutputIt , typename UIntPtr > auto write_ptr (OutputIt out, UIntPtr value, const basic_format_specs< Char > * specs) -> OutputIt
Definition at line 1315 of file format.h.
{
   int num_digits = count_digits<4>(value);
   auto size = to_unsigned(num_digits) + size_t(2);
   auto write = [=](reserve_iterator<OutputIt> it) {
     *it++ = static_cast<Char>('0');
     *it++ = static_cast<Char>('x');
     return format_uint<4, Char>(it, value, num_digits);
   };
   return specs ? write_padded<align::right>(out, *specs, size, write)
                : base_iterator(out, write(reserve(out, size)));
 }
References detail::base_iterator(), count_digits< 4 >(), detail::reserve(), to_unsigned(), and write().
write_significand() [1/5]
template<typename Char , typename UInt , FMT_ENABLE_IF(std::is_integral< UInt >::value) > auto write_significand (Char * out, UInt significand, int significand_size, int integral_size, Char decimal_point) -> Char* inline
Definition at line 1630 of file format.h.
{
   if (!decimal_point)
     return format_decimal(out, significand, significand_size).end;
   auto end = format_decimal(out + 1, significand, significand_size).end;
   if (integral_size == 1) {
     out[0] = out[1];
   } else {
     std::uninitialized_copy_n(out + 1, integral_size,
                               make_checked(out, to_unsigned(integral_size)));
   }
   out[integral_size] = decimal_point;
   return end;
 }
References decimal_point(), format_decimal(), detail::make_checked(), and to_unsigned().
write_significand() [2/5]
template<typename Char , typename OutputIt > auto write_significand (OutputIt out, const char * significand, int & significand_size) -> OutputIt inline
Definition at line 1618 of file format.h.
{
   return copy_str<Char>(significand, significand + significand_size, out);
 }
Referenced by write_float(), and write_significand().
write_significand() [3/5]
template<typename OutputIt , typename Char > auto write_significand (OutputIt out, const char * significand, int significand_size, int integral_size, Char decimal_point) -> OutputIt inline
Definition at line 1658 of file format.h.
{
   out = detail::copy_str_noinline<Char>(significand,
                                         significand + integral_size, out);
   if (!decimal_point) return out;
   *out++ = decimal_point;
   return detail::copy_str_noinline<Char>(significand + integral_size,
                                          significand + significand_size, out);
 }
References decimal_point().
write_significand() [4/5]
template<typename Char , typename OutputIt , typename UInt > auto write_significand (OutputIt out, UInt significand, int significand_size) -> OutputIt inline
Definition at line 1623 of file format.h.
{
   return format_decimal<Char>(out, significand, significand_size).end;
 }
write_significand() [5/5]
template<typename OutputIt , typename UInt , typename Char , FMT_ENABLE_IF(!std::is_pointer< remove_cvref_t< OutputIt >>::value) > auto write_significand (OutputIt out, UInt significand, int significand_size, int integral_size, Char decimal_point) -> OutputIt inline
Definition at line 1647 of file format.h.
{
   // Buffer is large enough to hold digits (digits10 + 1) and a decimal point.
   Char buffer[digits10<UInt>() + 2];
   auto end = write_significand(buffer, significand, significand_size,
                                integral_size, decimal_point);
   return detail::copy_str_noinline<Char>(buffer, end, out);
 }
References decimal_point(), and write_significand().