Azerotcore-wotlk: spell_the_lich_king_necrotic_plague_jump::spell_the_lich_king_necrotic_plague_AuraScript Class Reference
spell_the_lich_king_necrotic_plague_jump::spell_the_lich_king_necrotic_plague_AuraScript Class Reference
Private Member Functions
PrepareAuraScript (spell_the_lich_king_necrotic_plague_AuraScript)
bool Load () override
void OnApply (AuraEffect const *, AuraEffectHandleModes)
void OnRemove (AuraEffect const *aurEff, AuraEffectHandleModes)
void OnDispel (AuraEffect const *aurEff, AuraEffectHandleModes)
void AfterDispel (AuraEffect const *aurEff, AuraEffectHandleModes)
void Register () override
Private Attributes
int32 _lastAmount
Additional Inherited Members
Public Member Functions inherited from AuraScript
AuraScript ()
bool _Validate (SpellInfo const *entry) override
bool _Load (Aura *aura)
void _PrepareScriptCall (AuraScriptHookType hookType, AuraApplication const *aurApp=nullptr)
void _FinishScriptCall ()
bool _IsDefaultActionPrevented ()
void PreventDefaultAction ()
SpellInfo const * GetSpellInfo () const
uint32 GetId () const
ObjectGuid GetCasterGUID () const
Unit * GetCaster () const
WorldObject * GetOwner () const
Unit * GetUnitOwner () const
DynamicObject * GetDynobjOwner () const
void Remove (uint32 removeMode=0)
Aura * GetAura () const
AuraObjectType GetType () const
int32 GetDuration () const
void SetDuration (int32 duration, bool withMods=false)
void RefreshDuration ()
time_t GetApplyTime () const
int32 GetMaxDuration () const
void SetMaxDuration (int32 duration)
int32 CalcMaxDuration () const
bool IsExpired () const
bool IsPermanent () const
uint8 GetCharges () const
void SetCharges (uint8 charges)
uint8 CalcMaxCharges () const
bool ModCharges (int8 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool DropCharge (AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
uint8 GetStackAmount () const
void SetStackAmount (uint8 num)
bool ModStackAmount (int32 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool IsPassive () const
bool IsDeathPersistent () const
bool HasEffect (uint8 effIndex) const
AuraEffect * GetEffect (uint8 effIndex) const
bool HasEffectType (AuraType type) const
Unit * GetTarget () const
AuraApplication const * GetTargetApplication () const
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual bool Validate (SpellInfo const *)
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from AuraScript
HookList< CheckAreaTargetHandler > DoCheckAreaTarget
HookList< AuraDispelHandler > OnDispel
HookList< AuraDispelHandler > AfterDispel
HookList< EffectApplyHandler > OnEffectApply
HookList< EffectApplyHandler > AfterEffectApply
HookList< EffectApplyHandler > OnEffectRemove
HookList< EffectApplyHandler > AfterEffectRemove
HookList< EffectPeriodicHandler > OnEffectPeriodic
HookList< EffectUpdatePeriodicHandler > OnEffectUpdatePeriodic
HookList< EffectCalcAmountHandler > DoEffectCalcAmount
HookList< EffectCalcPeriodicHandler > DoEffectCalcPeriodic
HookList< EffectCalcSpellModHandler > DoEffectCalcSpellMod
HookList< EffectAbsorbHandler > OnEffectAbsorb
HookList< EffectAbsorbHandler > AfterEffectAbsorb
HookList< EffectManaShieldHandler > OnEffectManaShield
HookList< EffectManaShieldHandler > AfterEffectManaShield
HookList< EffectSplitHandler > OnEffectSplit
HookList< CheckProcHandler > DoCheckProc
HookList< AuraProcHandler > DoPrepareProc
HookList< AuraProcHandler > OnProc
HookList< AuraProcHandler > AfterProc
HookList< EffectProcHandler > OnEffectProc
HookList< EffectProcHandler > AfterEffectProc
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Definition at line 2027 of file boss_the_lich_king.cpp.
Member Function Documentation
AfterDispel()
void spell_the_lich_king_necrotic_plague_jump::spell_the_lich_king_necrotic_plague_AuraScript::AfterDispel (AuraEffect const * aurEff, AuraEffectHandleModes) inline private
Definition at line 2068 of file boss_the_lich_king.cpp.
         {
             // this means the stack increased so don't process as if dispelled
             if (aurEff->GetAmount() > _lastAmount)
                 return;
             CustomSpellValues values;
             values.AddSpellMod(SPELLVALUE_AURA_STACK, GetStackAmount());
             values.AddSpellMod(SPELLVALUE_BASE_POINT1, AURA_REMOVE_BY_ENEMY_SPELL); // add as marker (spell has no effect 1)
             GetTarget()->CastCustomSpell(SPELL_NECROTIC_PLAGUE_JUMP, values, nullptr, TRIGGERED_FULL_MASK, nullptr, nullptr, GetCasterGUID());
             if (Unit* caster = GetCaster())
                 caster->CastSpell(caster, SPELL_PLAGUE_SIPHON, true);
             Remove(AURA_REMOVE_BY_ENEMY_SPELL);
         }
References _lastAmount, CustomSpellValues::AddSpellMod(), AURA_REMOVE_BY_ENEMY_SPELL, Unit::CastCustomSpell(), AuraEffect::GetAmount(), AuraScript::GetCaster(), AuraScript::GetCasterGUID(), AuraScript::GetStackAmount(), AuraScript::GetTarget(), AuraScript::Remove(), SPELL_NECROTIC_PLAGUE_JUMP, SPELL_PLAGUE_SIPHON, SPELLVALUE_AURA_STACK, SPELLVALUE_BASE_POINT1, and TRIGGERED_FULL_MASK.
Load()
bool spell_the_lich_king_necrotic_plague_jump::spell_the_lich_king_necrotic_plague_AuraScript::Load () inline override private virtual
Reimplemented from _SpellScript.
Definition at line 2031 of file boss_the_lich_king.cpp.
         {
             _lastAmount = 0;
             return true;
         }
References _lastAmount.
OnApply()
void spell_the_lich_king_necrotic_plague_jump::spell_the_lich_king_necrotic_plague_AuraScript::OnApply (AuraEffect const * , AuraEffectHandleModes) inline private
Definition at line 2037 of file boss_the_lich_king.cpp.
         {
             if (Unit* caster = GetCaster())
                 if (caster->GetAI())
                     caster->GetAI()->SetData(DATA_PLAGUE_STACK, GetStackAmount());
         }
References DATA_PLAGUE_STACK, AuraScript::GetCaster(), and AuraScript::GetStackAmount().
Referenced by Register().
OnDispel()
void spell_the_lich_king_necrotic_plague_jump::spell_the_lich_king_necrotic_plague_AuraScript::OnDispel (AuraEffect const * aurEff, AuraEffectHandleModes) inline private
Definition at line 2063 of file boss_the_lich_king.cpp.
         {
             _lastAmount = aurEff->GetAmount();
         }
References _lastAmount, and AuraEffect::GetAmount().
OnRemove()
void spell_the_lich_king_necrotic_plague_jump::spell_the_lich_king_necrotic_plague_AuraScript::OnRemove (AuraEffect const * aurEff, AuraEffectHandleModes) inline private
Definition at line 2044 of file boss_the_lich_king.cpp.
         {
             _lastAmount = aurEff->GetAmount();
             switch (GetTargetApplication()->GetRemoveMode())
             {
                 case AURA_REMOVE_BY_EXPIRE:
                 case AURA_REMOVE_BY_DEATH:
                     break;
                 default:
                     return;
             }
             CustomSpellValues values;
             values.AddSpellMod(SPELLVALUE_AURA_STACK, GetStackAmount());
             GetTarget()->CastCustomSpell(SPELL_NECROTIC_PLAGUE_JUMP, values, nullptr, TRIGGERED_FULL_MASK, nullptr, nullptr, GetCasterGUID());
             if (Unit* caster = GetCaster())
                 caster->CastSpell(caster, SPELL_PLAGUE_SIPHON, true);
         }
References _lastAmount, CustomSpellValues::AddSpellMod(), AURA_REMOVE_BY_DEATH, AURA_REMOVE_BY_EXPIRE, Unit::CastCustomSpell(), AuraEffect::GetAmount(), AuraScript::GetCaster(), AuraScript::GetCasterGUID(), AuraScript::GetStackAmount(), AuraScript::GetTarget(), AuraScript::GetTargetApplication(), SPELL_NECROTIC_PLAGUE_JUMP, SPELL_PLAGUE_SIPHON, SPELLVALUE_AURA_STACK, and TRIGGERED_FULL_MASK.
Referenced by Register().
PrepareAuraScript()
spell_the_lich_king_necrotic_plague_jump::spell_the_lich_king_necrotic_plague_AuraScript::PrepareAuraScript (spell_the_lich_king_necrotic_plague_AuraScript) private
Register()
void spell_the_lich_king_necrotic_plague_jump::spell_the_lich_king_necrotic_plague_AuraScript::Register () inline override private virtual
Implements _SpellScript.
Definition at line 2084 of file boss_the_lich_king.cpp.
         {
             OnEffectApply += AuraEffectApplyFn(spell_the_lich_king_necrotic_plague_AuraScript::OnApply, EFFECT_0, SPELL_AURA_PERIODIC_DAMAGE, AURA_EFFECT_HANDLE_REAL_OR_REAPPLY_MASK);
             AfterEffectRemove += AuraEffectRemoveFn(spell_the_lich_king_necrotic_plague_AuraScript::OnRemove, EFFECT_0, SPELL_AURA_PERIODIC_DAMAGE, AURA_EFFECT_HANDLE_REAL);
             AfterEffectRemove += AuraEffectRemoveFn(spell_the_lich_king_necrotic_plague_AuraScript::OnDispel, EFFECT_0, SPELL_AURA_PERIODIC_DAMAGE, AURA_EFFECT_HANDLE_REAPPLY);
             AfterEffectApply += AuraEffectApplyFn(spell_the_lich_king_necrotic_plague_AuraScript::AfterDispel, EFFECT_0, SPELL_AURA_PERIODIC_DAMAGE, AURA_EFFECT_HANDLE_REAPPLY);
         }
References AuraScript::AfterDispel, AuraScript::AfterEffectApply, AuraScript::AfterEffectRemove, AURA_EFFECT_HANDLE_REAL, AURA_EFFECT_HANDLE_REAL_OR_REAPPLY_MASK, AURA_EFFECT_HANDLE_REAPPLY, AuraEffectApplyFn, AuraEffectRemoveFn, EFFECT_0, OnApply(), AuraScript::OnDispel, AuraScript::OnEffectApply, OnRemove(), and SPELL_AURA_PERIODIC_DAMAGE.
Member Data Documentation
_lastAmount
int32 spell_the_lich_king_necrotic_plague_jump::spell_the_lich_king_necrotic_plague_AuraScript::_lastAmount private
Definition at line 2092 of file boss_the_lich_king.cpp.
Referenced by AfterDispel(), Load(), OnDispel(), and OnRemove().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp