Azerotcore-wotlk: spell_hun_lock_and_load Class Reference
spell_hun_lock_and_load Class Reference
Private Member Functions
PrepareAuraScript (spell_hun_lock_and_load)
bool Validate (SpellInfo const *) override
bool CheckTrapProc (ProcEventInfo &eventInfo)
bool IsTargetValid (SpellInfo const *spellInfo, Unit *target)
template<uint32 mask>
void HandleProcs (AuraEffect const *aurEff, ProcEventInfo &eventInfo)
void ApplyMarker (ProcEventInfo &eventInfo)
void Register () override
Additional Inherited Members
Public Member Functions inherited from AuraScript
AuraScript ()
bool _Validate (SpellInfo const *entry) override
bool _Load (Aura *aura)
void _PrepareScriptCall (AuraScriptHookType hookType, AuraApplication const *aurApp=nullptr)
void _FinishScriptCall ()
bool _IsDefaultActionPrevented ()
void PreventDefaultAction ()
SpellInfo const * GetSpellInfo () const
uint32 GetId () const
ObjectGuid GetCasterGUID () const
Unit * GetCaster () const
WorldObject * GetOwner () const
Unit * GetUnitOwner () const
DynamicObject * GetDynobjOwner () const
void Remove (uint32 removeMode=0)
Aura * GetAura () const
AuraObjectType GetType () const
int32 GetDuration () const
void SetDuration (int32 duration, bool withMods=false)
void RefreshDuration ()
time_t GetApplyTime () const
int32 GetMaxDuration () const
void SetMaxDuration (int32 duration)
int32 CalcMaxDuration () const
bool IsExpired () const
bool IsPermanent () const
uint8 GetCharges () const
void SetCharges (uint8 charges)
uint8 CalcMaxCharges () const
bool ModCharges (int8 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool DropCharge (AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
uint8 GetStackAmount () const
void SetStackAmount (uint8 num)
bool ModStackAmount (int32 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool IsPassive () const
bool IsDeathPersistent () const
bool HasEffect (uint8 effIndex) const
AuraEffect * GetEffect (uint8 effIndex) const
bool HasEffectType (AuraType type) const
Unit * GetTarget () const
AuraApplication const * GetTargetApplication () const
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from AuraScript
HookList< CheckAreaTargetHandler > DoCheckAreaTarget
HookList< AuraDispelHandler > OnDispel
HookList< AuraDispelHandler > AfterDispel
HookList< EffectApplyHandler > OnEffectApply
HookList< EffectApplyHandler > AfterEffectApply
HookList< EffectApplyHandler > OnEffectRemove
HookList< EffectApplyHandler > AfterEffectRemove
HookList< EffectPeriodicHandler > OnEffectPeriodic
HookList< EffectUpdatePeriodicHandler > OnEffectUpdatePeriodic
HookList< EffectCalcAmountHandler > DoEffectCalcAmount
HookList< EffectCalcPeriodicHandler > DoEffectCalcPeriodic
HookList< EffectCalcSpellModHandler > DoEffectCalcSpellMod
HookList< EffectAbsorbHandler > OnEffectAbsorb
HookList< EffectAbsorbHandler > AfterEffectAbsorb
HookList< EffectManaShieldHandler > OnEffectManaShield
HookList< EffectManaShieldHandler > AfterEffectManaShield
HookList< EffectSplitHandler > OnEffectSplit
HookList< CheckProcHandler > DoCheckProc
HookList< AuraProcHandler > DoPrepareProc
HookList< AuraProcHandler > OnProc
HookList< AuraProcHandler > AfterProc
HookList< EffectProcHandler > OnEffectProc
HookList< EffectProcHandler > AfterEffectProc
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Definition at line 1110 of file spell_hunter.cpp.
Member Function Documentation
ApplyMarker()
void spell_hun_lock_and_load::ApplyMarker (ProcEventInfo & eventInfo) inline private
Definition at line 1196 of file spell_hunter.cpp.
     {
         if (IsTargetValid(eventInfo.GetSpellInfo(), eventInfo.GetProcTarget()))
         {
             Unit* caster = eventInfo.GetActor();
             caster->CastSpell(caster, SPELL_LOCK_AND_LOAD_MARKER, true);
         }
     }
References Unit::CastSpell(), ProcEventInfo::GetActor(), ProcEventInfo::GetProcTarget(), ProcEventInfo::GetSpellInfo(), IsTargetValid(), and SPELL_LOCK_AND_LOAD_MARKER.
Referenced by Register().
CheckTrapProc()
bool spell_hun_lock_and_load::CheckTrapProc (ProcEventInfo & eventInfo) inline private
Definition at line 1119 of file spell_hunter.cpp.
     {
         SpellInfo const* spellInfo = eventInfo.GetSpellInfo();
         if (!spellInfo)
         {
             return false;
         }
         // Black Arrow and Fire traps may trigger on periodic tick only.
         if (((spellInfo->GetSchoolMask() & SPELL_SCHOOL_MASK_FIRE) || (spellInfo->GetSchoolMask() & SPELL_SCHOOL_MASK_SHADOW))
             && (spellInfo->Effects[0].ApplyAuraName == SPELL_AURA_PERIODIC_DAMAGE || spellInfo->Effects[1].ApplyAuraName == SPELL_AURA_PERIODIC_DAMAGE))
         {
             return true;
         }
         return IsTargetValid(spellInfo, eventInfo.GetProcTarget()) && !eventInfo.GetActor()->HasAura(SPELL_LOCK_AND_LOAD_MARKER);
     }
References SpellInfo::Effects, ProcEventInfo::GetActor(), ProcEventInfo::GetProcTarget(), SpellInfo::GetSchoolMask(), ProcEventInfo::GetSpellInfo(), Unit::HasAura(), IsTargetValid(), SPELL_AURA_PERIODIC_DAMAGE, SPELL_LOCK_AND_LOAD_MARKER, SPELL_SCHOOL_MASK_FIRE, and SPELL_SCHOOL_MASK_SHADOW.
Referenced by Register().
HandleProcs()
template<uint32 mask> void spell_hun_lock_and_load::HandleProcs (AuraEffect const * aurEff, ProcEventInfo & eventInfo) inline private
Definition at line 1167 of file spell_hunter.cpp.
     {
         PreventDefaultAction();
         SpellInfo const* spellInfo = eventInfo.GetSpellInfo();
         if (!(eventInfo.GetTypeMask() & mask) || !spellInfo)
         {
             return;
         }
         // Also check if the proc from the fire traps and black arrow actually comes from the periodic ticks here.
         // Normally this wouldn't be required, but we are circumventing the current proc system limitations.
         if (((spellInfo->GetSchoolMask() & SPELL_SCHOOL_MASK_FIRE) || (spellInfo->GetSchoolMask() & SPELL_SCHOOL_MASK_SHADOW))
             && (spellInfo->Effects[0].ApplyAuraName == SPELL_AURA_PERIODIC_DAMAGE || spellInfo->Effects[1].ApplyAuraName == SPELL_AURA_PERIODIC_DAMAGE)
             && !(mask & PROC_FLAG_DONE_PERIODIC))
         {
             return;
         }
         if (!roll_chance_i(aurEff->GetAmount()))
         {
             return;
         }
         Unit* caster = eventInfo.GetActor();
         caster->CastSpell(caster, SPELL_LOCK_AND_LOAD_TRIGGER, true);
     }
References Unit::CastSpell(), SpellInfo::Effects, ProcEventInfo::GetActor(), AuraEffect::GetAmount(), SpellInfo::GetSchoolMask(), ProcEventInfo::GetSpellInfo(), ProcEventInfo::GetTypeMask(), AuraScript::PreventDefaultAction(), PROC_FLAG_DONE_PERIODIC, roll_chance_i(), SPELL_AURA_PERIODIC_DAMAGE, SPELL_LOCK_AND_LOAD_TRIGGER, SPELL_SCHOOL_MASK_FIRE, and SPELL_SCHOOL_MASK_SHADOW.
IsTargetValid()
bool spell_hun_lock_and_load::IsTargetValid (SpellInfo const * spellInfo, Unit * target) inline private
Definition at line 1137 of file spell_hunter.cpp.
     {
         if (!spellInfo || !target)
         {
             return false;
         }
         // Don't check it for fire traps and black arrow, they proc on periodic only and not spell hit.
         // So it's wrong to check for immunity, it was already checked when the spell was applied.
         if ((spellInfo->GetSchoolMask() & SPELL_SCHOOL_MASK_FIRE) || (spellInfo->GetSchoolMask() & SPELL_SCHOOL_MASK_SHADOW))
         {
             return false;
         }
         // HitMask for Frost Trap can't be checked correctly as it is.
         // That's because the talent is triggered by the spell that fires the trap (63487)...
         // ...and not the actual spell that applies the slow effect (67035).
         // So the IMMUNE result is never sent by the spell that triggers this.
         if (spellInfo->GetSchoolMask() & SPELL_SCHOOL_MASK_NATURE)
         {
             if (SpellInfo const* triggerSpell = sSpellMgr->GetSpellInfo(SPELL_FROST_TRAP_SLOW))
             {
                 return !target->IsImmunedToSpell(triggerSpell);
             }
         }
         return true;
     }
References SpellInfo::GetSchoolMask(), Unit::IsImmunedToSpell(), SPELL_FROST_TRAP_SLOW, SPELL_SCHOOL_MASK_FIRE, SPELL_SCHOOL_MASK_NATURE, SPELL_SCHOOL_MASK_SHADOW, and sSpellMgr.
Referenced by ApplyMarker(), and CheckTrapProc().
PrepareAuraScript()
spell_hun_lock_and_load::PrepareAuraScript (spell_hun_lock_and_load) private
Register()
void spell_hun_lock_and_load::Register () inline override private virtual
Implements _SpellScript.
Definition at line 1205 of file spell_hunter.cpp.
     {
         DoCheckProc += AuraCheckProcFn(spell_hun_lock_and_load::CheckTrapProc);
         OnEffectProc += AuraEffectProcFn(spell_hun_lock_and_load::HandleProcs<PROC_FLAG_DONE_TRAP_ACTIVATION>, EFFECT_0, SPELL_AURA_PROC_TRIGGER_SPELL);
         OnEffectProc += AuraEffectProcFn(spell_hun_lock_and_load::HandleProcs<PROC_FLAG_DONE_PERIODIC>, EFFECT_1, SPELL_AURA_DUMMY);
         AfterProc += AuraProcFn(spell_hun_lock_and_load::ApplyMarker);
     }
References AuraScript::AfterProc, ApplyMarker(), AuraCheckProcFn, AuraEffectProcFn, AuraProcFn, CheckTrapProc(), AuraScript::DoCheckProc, EFFECT_0, EFFECT_1, AuraScript::OnEffectProc, SPELL_AURA_DUMMY, and SPELL_AURA_PROC_TRIGGER_SPELL.
Validate()
bool spell_hun_lock_and_load::Validate (SpellInfo const *) inline override private virtual
Reimplemented from _SpellScript.
Definition at line 1114 of file spell_hunter.cpp.
     {
         return ValidateSpellInfo({ SPELL_LOCK_AND_LOAD_TRIGGER, SPELL_LOCK_AND_LOAD_MARKER, SPELL_FROST_TRAP_SLOW });
     }
References SPELL_FROST_TRAP_SLOW, SPELL_LOCK_AND_LOAD_MARKER, SPELL_LOCK_AND_LOAD_TRIGGER, and _SpellScript::ValidateSpellInfo().
The documentation for this class was generated from the following file:
src/server/scripts/Spells/spell_hunter.cpp