Azerotcore-wotlk: deps/mysqllite/strings/ctype-simple.c File Reference
ctype-simple.c File Reference
#include <my_global.h>
#include "m_string.h"
#include "m_ctype.h"
#include "my_sys.h"
#include <errno.h>
#include "stdarg.h"
Classes
struct uni_idx
Macros
#define likeconv(s, A) (uchar) (s)->sort_order[(uchar) (A)]
#define INC_PTR(cs, A, B) (A)++
#define PLANE_SIZE 0x100
#define PLANE_NUM 0x100
#define PLANE_NUMBER(x) (((x)>>8) % PLANE_NUM)
#define CUTOFF (ULONGLONG_MAX / 10)
#define CUTLIM (ULONGLONG_MAX % 10)
#define DIGITS_IN_ULONGLONG 20
Functions
size_t my_strnxfrmlen_simple (CHARSET_INFO *cs, size_t len)
size_t my_strnxfrm_simple (CHARSET_INFO *cs, uchar *dest, size_t len, const uchar *src, size_t srclen)
int my_strnncoll_simple (CHARSET_INFO *cs, const uchar *s, size_t slen, const uchar *t, size_t tlen, my_bool t_is_prefix)
int my_strnncollsp_simple (CHARSET_INFO *cs, const uchar *a, size_t a_length, const uchar *b, size_t b_length, my_bool diff_if_only_endspace_difference)
size_t my_caseup_str_8bit (CHARSET_INFO *cs, char *str)
size_t my_casedn_str_8bit (CHARSET_INFO *cs, char *str)
size_t my_caseup_8bit (CHARSET_INFO *cs, char *src, size_t srclen, char *dst __attribute__((unused)), size_t dstlen __attribute__((unused)))
size_t my_casedn_8bit (CHARSET_INFO *cs, char *src, size_t srclen, char *dst __attribute__((unused)), size_t dstlen __attribute__((unused)))
int my_strcasecmp_8bit (CHARSET_INFO *cs, const char *s, const char *t)
int my_mb_wc_8bit (CHARSET_INFO *cs, my_wc_t *wc, const uchar *str, const uchar *end __attribute__((unused)))
int my_wc_mb_8bit (CHARSET_INFO *cs, my_wc_t wc, uchar *str, uchar *end)
size_t my_snprintf_8bit (CHARSET_INFO *cs __attribute__((unused)), char *to, size_t n __attribute__((unused)), const char *fmt,...)
void my_hash_sort_simple (CHARSET_INFO *cs, const uchar *key, size_t len, ulong *nr1, ulong *nr2)
long my_strntol_8bit (CHARSET_INFO *cs, const char *nptr, size_t l, int base, char **endptr, int *err)
ulong my_strntoul_8bit (CHARSET_INFO *cs, const char *nptr, size_t l, int base, char **endptr, int *err)
longlong my_strntoll_8bit (CHARSET_INFO *cs __attribute__((unused)), const char *nptr, size_t l, int base, char **endptr, int *err)
ulonglong my_strntoull_8bit (CHARSET_INFO *cs, const char *nptr, size_t l, int base, char **endptr, int *err)
double my_strntod_8bit (CHARSET_INFO *cs __attribute__((unused)), char *str, size_t length, char **end, int *err)
size_t my_long10_to_str_8bit (CHARSET_INFO *cs __attribute__((unused)), char *dst, size_t len, int radix, long int val)
size_t my_longlong10_to_str_8bit (CHARSET_INFO *cs __attribute__((unused)), char *dst, size_t len, int radix, longlong val)
int my_wildcmp_8bit (CHARSET_INFO *cs, const char *str, const char *str_end, const char *wildstr, const char *wildend, int escape, int w_one, int w_many)
my_bool my_like_range_simple (CHARSET_INFO *cs, const char *ptr, size_t ptr_length, pbool escape, pbool w_one, pbool w_many, size_t res_length, char *min_str, char *max_str, size_t *min_length, size_t *max_length)
size_t my_scan_8bit (CHARSET_INFO *cs, const char *str, const char *end, int sq)
void my_fill_8bit (CHARSET_INFO *cs __attribute__((unused)), char *s, size_t l, int fill)
size_t my_numchars_8bit (CHARSET_INFO *cs __attribute__((unused)), const char *b, const char *e)
size_t my_numcells_8bit (CHARSET_INFO *cs __attribute__((unused)), const char *b, const char *e)
size_t my_charpos_8bit (CHARSET_INFO *cs __attribute__((unused)), const char *b __attribute__((unused)), const char *e __attribute__((unused)), size_t pos)
size_t my_well_formed_len_8bit (CHARSET_INFO *cs __attribute__((unused)), const char *start, const char *end, size_t nchars, int *error)
size_t my_lengthsp_8bit (CHARSET_INFO *cs __attribute__((unused)), const char *ptr, size_t length)
uint my_instr_simple (CHARSET_INFO *cs, const char *b, size_t b_length, const char *s, size_t s_length, my_match_t *match, uint nmatch)
static int pcmp (const void *f, const void *s)
static my_bool create_fromuni (CHARSET_INFO *cs, void *(*alloc)(size_t))
static my_bool my_cset_init_8bit (CHARSET_INFO *cs, void *(*alloc)(size_t))
static void set_max_sort_char (CHARSET_INFO *cs)
static my_bool my_coll_init_simple (CHARSET_INFO *cs, void *(*alloc)(size_t) __attribute__((unused)))
longlong my_strtoll10_8bit (CHARSET_INFO *cs __attribute__((unused)), const char *nptr, char **endptr, int *error)
int my_mb_ctype_8bit (CHARSET_INFO *cs, int *ctype, const uchar *s, const uchar *e)
ulonglong my_strntoull10rnd_8bit (CHARSET_INFO *cs __attribute__((unused)), const char *str, size_t length, int unsigned_flag, char **endptr, int *error)
my_bool my_propagate_simple (CHARSET_INFO *cs __attribute__((unused)), const uchar *str __attribute__((unused)), size_t length __attribute__((unused)))
my_bool my_propagate_complex (CHARSET_INFO *cs __attribute__((unused)), const uchar *str __attribute__((unused)), size_t length __attribute__((unused)))
Variables
static ulonglong d10 [DIGITS_IN_ULONGLONG]
MY_CHARSET_HANDLER my_charset_8bit_handler
MY_COLLATION_HANDLER my_collation_8bit_simple_ci_handler
Macro Definition Documentation
CUTLIM
#define CUTLIM (ULONGLONG_MAX % 10)
Definition at line 1281 of file ctype-simple.c.
CUTOFF
#define CUTOFF (ULONGLONG_MAX / 10)
Definition at line 1280 of file ctype-simple.c.
DIGITS_IN_ULONGLONG
#define DIGITS_IN_ULONGLONG 20
Definition at line 1282 of file ctype-simple.c.
INC_PTR
#define INC_PTR (cs, A, B) (A)++
Definition at line 841 of file ctype-simple.c.
likeconv
#define likeconv (s, A) (uchar) (s)->sort_order[(uchar) (A)]
Definition at line 838 of file ctype-simple.c.
PLANE_NUM
#define PLANE_NUM 0x100
Definition at line 1132 of file ctype-simple.c.
PLANE_NUMBER
#define PLANE_NUMBER (x) (((x)>>8) % PLANE_NUM)
Definition at line 1133 of file ctype-simple.c.
PLANE_SIZE
#define PLANE_SIZE 0x100
Definition at line 1131 of file ctype-simple.c.
Function Documentation
create_fromuni()
static my_bool create_fromuni (CHARSET_INFO * cs, void *(*)(size_t) alloc) static
Definition at line 1146 of file ctype-simple.c.
 {
   uni_idx   idx[PLANE_NUM];
   int       i,n;
   /*
     Check that Unicode map is loaded.
     It can be not loaded when the collation is
     listed in Index.xml but not specified
     in the character set specific XML file.
   */
   if (!cs->tab_to_uni)
     return TRUE;
   /* Clear plane statistics */
   bzero(idx,sizeof(idx));
   /* Count number of characters in each plane */
   for (i=0; i< 0x100; i++)
   {
     uint16 wc=cs->tab_to_uni[i];
     int pl= PLANE_NUMBER(wc);
     if (wc || !i)
     {
       if (!idx[pl].nchars)
       {
         idx[pl].uidx.from=wc;
         idx[pl].uidx.to=wc;
       }else
       {
         idx[pl].uidx.from=wc<idx[pl].uidx.from?wc:idx[pl].uidx.from;
         idx[pl].uidx.to=wc>idx[pl].uidx.to?wc:idx[pl].uidx.to;
       }
       idx[pl].nchars++;
     }
   }
   /* Sort planes in descending order */
   qsort(&idx,PLANE_NUM,sizeof(uni_idx),&pcmp);
   for (i=0; i < PLANE_NUM; i++)
   {
     int ch,numchars;
     /* Skip empty plane */
     if (!idx[i].nchars)
       break;
     numchars=idx[i].uidx.to-idx[i].uidx.from+1;
     if (!(idx[i].uidx.tab=(uchar*) alloc(numchars * sizeof(*idx[i].uidx.tab))))
       return TRUE;
     bzero(idx[i].uidx.tab,numchars*sizeof(*idx[i].uidx.tab));
     for (ch=1; ch < PLANE_SIZE; ch++)
     {
       uint16 wc=cs->tab_to_uni[ch];
       if (wc >= idx[i].uidx.from && wc <= idx[i].uidx.to && wc)
       {
         int ofs= wc - idx[i].uidx.from;
         idx[i].uidx.tab[ofs]= ch;
       }
     }
   }
   /* Allocate and fill reverse table for each plane */
   n=i;
   if (!(cs->tab_from_uni= (MY_UNI_IDX*) alloc(sizeof(MY_UNI_IDX)*(n+1))))
     return TRUE;
   for (i=0; i< n; i++)
     cs->tab_from_uni[i]= idx[i].uidx;
   /* Set end-of-list marker */
   bzero(&cs->tab_from_uni[i],sizeof(MY_UNI_IDX));
   return FALSE;
 }
References bzero, FALSE, idx, pcmp(), PLANE_NUM, PLANE_NUMBER, PLANE_SIZE, charset_info_st::tab_from_uni, charset_info_st::tab_to_uni, and TRUE.
Referenced by my_cset_init_8bit().
my_casedn_8bit()
size_t my_casedn_8bit (CHARSET_INFO * cs, char * src, size_t srclen, char *dst __attribute__(unused), size_t dstlen __attribute__(unused))
Definition at line 229 of file ctype-simple.c.
 {
   char *end= src + srclen;
   register uchar *map=cs->to_lower;
   DBUG_ASSERT(src == dst && srclen == dstlen);
   for ( ; src != end ; src++)
     *src= (char) map[(uchar) *src];
   return srclen;
 }
References DBUG_ASSERT, and charset_info_st::to_lower.
my_casedn_str_8bit()
size_t my_casedn_str_8bit (CHARSET_INFO * cs, char * str)
Definition at line 206 of file ctype-simple.c.
 {
   register uchar *map= cs->to_lower;
   char *str_orig= str;
   while ((*str= (char) map[(uchar) *str]) != 0)
     str++;
   return (size_t) (str - str_orig);
 }
References charset_info_st::to_lower.
my_caseup_8bit()
size_t my_caseup_8bit (CHARSET_INFO * cs, char * src, size_t srclen, char *dst __attribute__(unused), size_t dstlen __attribute__(unused))
Definition at line 216 of file ctype-simple.c.
 {
   char *end= src + srclen;
   register uchar *map= cs->to_upper;
   DBUG_ASSERT(src == dst && srclen == dstlen);
   for ( ; src != end ; src++)
     *src= (char) map[(uchar) *src];
   return srclen;
 }
References DBUG_ASSERT, and charset_info_st::to_upper.
my_caseup_str_8bit()
size_t my_caseup_str_8bit (CHARSET_INFO * cs, char * str)
Definition at line 196 of file ctype-simple.c.
 {
   register uchar *map= cs->to_upper;
   char *str_orig= str;
   while ((*str= (char) map[(uchar) *str]) != 0)
     str++;
   return (size_t) (str - str_orig);
 }
References charset_info_st::to_upper.
my_charpos_8bit()
size_t my_charpos_8bit (CHARSET_INFO *cs __attribute__(unused), const char *b __attribute__(unused), const char *e __attribute__(unused), size_t pos)
Definition at line 1037 of file ctype-simple.c.
 {
   return pos;
 }
References pos().
my_coll_init_simple()
static my_bool my_coll_init_simple (CHARSET_INFO * cs, void * *)(size_t) __attribute__ alloc((unused)) static
Definition at line 1252 of file ctype-simple.c.
 {
   set_max_sort_char(cs);
   return FALSE;
 }
References FALSE, and set_max_sort_char().
my_cset_init_8bit()
static my_bool my_cset_init_8bit (CHARSET_INFO * cs, void *(*)(size_t) alloc) static
Definition at line 1225 of file ctype-simple.c.
 {
   cs->caseup_multiply= 1;
   cs->casedn_multiply= 1;
   cs->pad_char= ' ';
   return create_fromuni(cs, alloc);
 }
References charset_info_st::casedn_multiply, charset_info_st::caseup_multiply, create_fromuni(), and charset_info_st::pad_char.
my_fill_8bit()
void my_fill_8bit (CHARSET_INFO *cs __attribute__(unused), char * s, size_t l, int fill)
Definition at line 1016 of file ctype-simple.c.
 {
   bfill((uchar*) s,l,fill);
 }
References bfill, fill(), and mpq::l.
my_hash_sort_simple()
void my_hash_sort_simple (CHARSET_INFO * cs, const uchar * key, size_t len, ulong * nr1, ulong * nr2)
Definition at line 302 of file ctype-simple.c.
 {
   register uchar *sort_order=cs->sort_order;
   const uchar *end;
   /*
     Remove end space. We have to do this to be able to compare
     'A ' and 'A' as identical
   */
   end= skip_trailing_space(key, len);
   for (; key < (uchar*) end ; key++)
   {
     nr1[0]^=(ulong) ((((uint) nr1[0] & 63)+nr2[0]) *
          ((uint) sort_order[(uint) *key])) + (nr1[0] << 8);
     nr2[0]+=3;
   }
 }
References skip_trailing_space(), and charset_info_st::sort_order.
my_instr_simple()
uint my_instr_simple (CHARSET_INFO * cs, const char * b, size_t b_length, const char * s, size_t s_length, my_match_t * match, uint nmatch)
Definition at line 1065 of file ctype-simple.c.
 {
   register const uchar *str, *search, *end, *search_end;
   if (s_length <= b_length)
   {
     if (!s_length)
     {
       if (nmatch)
       {
         match->beg= 0;
         match->end= 0;
         match->mb_len= 0;
       }
       return 1;     /* Empty string is always found */
     }
     str= (const uchar*) b;
     search= (const uchar*) s;
     end= (const uchar*) b+b_length-s_length+1;
     search_end= (const uchar*) s + s_length;
 skip:
     while (str != end)
     {
       if (cs->sort_order[*str++] == cs->sort_order[*search])
       {
     register const uchar *i,*j;
     i= str;
     j= search+1;
     while (j != search_end)
       if (cs->sort_order[*i++] != cs->sort_order[*j++])
             goto skip;
     if (nmatch > 0)
     {
       match[0].beg= 0;
       match[0].end= (size_t) (str- (const uchar*)b-1);
       match[0].mb_len= match[0].end;
       if (nmatch > 1)
       {
         match[1].beg= match[0].end;
         match[1].end= match[0].end+s_length;
         match[1].mb_len= match[1].end-match[1].beg;
       }
     }
     return 2;
       }
     }
   }
   return 0;
 }
References b, my_match_t::beg, my_match_t::end, my_match_t::mb_len, and charset_info_st::sort_order.
my_lengthsp_8bit()
size_t my_lengthsp_8bit (CHARSET_INFO *cs __attribute__(unused), const char * ptr, size_t length)
Definition at line 1056 of file ctype-simple.c.
 {
   const char *end;
   end= (const char *) skip_trailing_space((const uchar *)ptr, length);
   return (size_t) (end-ptr);
 }
References G3D::length(), ptr(), and skip_trailing_space().
my_like_range_simple()
my_bool my_like_range_simple (CHARSET_INFO * cs, const char * ptr, size_t ptr_length, pbool escape, pbool w_one, pbool w_many, size_t res_length, char * min_str, char * max_str, size_t * min_length, size_t * max_length)
Definition at line 940 of file ctype-simple.c.
 {
   const char *end= ptr + ptr_length;
   char *min_org=min_str;
   char *min_end=min_str+res_length;
   size_t charlen= res_length / cs->mbmaxlen;
   for (; ptr != end && min_str != min_end && charlen > 0 ; ptr++, charlen--)
   {
     if (*ptr == escape && ptr+1 != end)
     {
       ptr++;                    /* Skip escape */
       *min_str++= *max_str++ = *ptr;
       continue;
     }
     if (*ptr == w_one)              /* '_' in SQL */
     {
       *min_str++='\0';              /* This should be min char */
       *max_str++= (char) cs->max_sort_char;
       continue;
     }
     if (*ptr == w_many)             /* '%' in SQL */
     {
       /* Calculate length of keys */
       *min_length= ((cs->state & MY_CS_BINSORT) ?
                     (size_t) (min_str - min_org) :
                     res_length);
       *max_length= res_length;
       do
       {
     *min_str++= 0;
     *max_str++= (char) cs->max_sort_char;
       } while (min_str != min_end);
       return 0;
     }
     *min_str++= *max_str++ = *ptr;
   }
  *min_length= *max_length = (size_t) (min_str - min_org);
   while (min_str != min_end)
     *min_str++= *max_str++ = ' ';      /* Because if key compression */
   return 0;
 }
References G3D::escape(), charset_info_st::max_sort_char, charset_info_st::mbmaxlen, MY_CS_BINSORT, ptr(), and charset_info_st::state.
my_long10_to_str_8bit()
size_t my_long10_to_str_8bit (CHARSET_INFO *cs __attribute__(unused), char * dst, size_t len, int radix, long int val)
Definition at line 732 of file ctype-simple.c.
 {
   char buffer[66];
   register char *p, *e;
   long int new_val;
   uint sign=0;
   unsigned long int uval = (unsigned long int) val;
   e = p = &buffer[sizeof(buffer)-1];
   *p= 0;
   if (radix < 0)
   {
     if (val < 0)
     {
       /* Avoid integer overflow in (-val) for LONGLONG_MIN (BUG#31799). */
       uval= (unsigned long int)0 - uval;
       *dst++= '-';
       len--;
       sign= 1;
     }
   }
   new_val = (long) (uval / 10);
   *--p    = '0'+ (char) (uval - (unsigned long) new_val * 10);
   val     = new_val;
   while (val != 0)
   {
     new_val=val/10;
     *--p = '0' + (char) (val-new_val*10);
     val= new_val;
   }
   len= min(len, (size_t) (e-p));
   memcpy(dst, p, len);
   return len+sign;
 }
References buffer, memcpy, min, and G3D::sign().
my_longlong10_to_str_8bit()
size_t my_longlong10_to_str_8bit (CHARSET_INFO *cs __attribute__(unused), char * dst, size_t len, int radix, longlong val)
Definition at line 773 of file ctype-simple.c.
 {
   char buffer[65];
   register char *p, *e;
   long long_val;
   uint sign= 0;
   ulonglong uval = (ulonglong)val;
   if (radix < 0)
   {
     if (val < 0)
     {
       /* Avoid integer overflow in (-val) for LONGLONG_MIN (BUG#31799). */
       uval = (ulonglong)0 - uval;
       *dst++= '-';
       len--;
       sign= 1;
     }
   }
   e = p = &buffer[sizeof(buffer)-1];
   *p= 0;
   if (uval == 0)
   {
     *--p= '0';
     len= 1;
     goto cnv;
   }
   while (uval > (ulonglong) LONG_MAX)
   {
     ulonglong quo= uval/(uint) 10;
     uint rem= (uint) (uval- quo* (uint) 10);
     *--p = '0' + rem;
     uval= quo;
   }
   long_val= (long) uval;
   while (long_val != 0)
   {
     long quo= long_val/10;
     *--p = (char) ('0' + (long_val - quo*10));
     long_val= quo;
   }
   len= min(len, (size_t) (e-p));
 cnv:
   memcpy(dst, p, len);
   return len+sign;
 }
References buffer, memcpy, min, and G3D::sign().
my_mb_ctype_8bit()
int my_mb_ctype_8bit (CHARSET_INFO * cs, int * ctype, const uchar * s, const uchar * e)
Definition at line 1267 of file ctype-simple.c.
 {
   if (s >= e)
   {
     *ctype= 0;
     return MY_CS_TOOSMALL;
   }
   *ctype= cs->ctype[*s + 1];
   return 1;
 }
References charset_info_st::ctype, and MY_CS_TOOSMALL.
my_mb_wc_8bit()
int my_mb_wc_8bit (CHARSET_INFO * cs, my_wc_t * wc, const uchar * str, const uchar *end __attribute__(unused))
Definition at line 250 of file ctype-simple.c.
 {
   if (str >= end)
     return MY_CS_TOOSMALL;
   *wc=cs->tab_to_uni[*str];
   return (!wc[0] && str[0]) ? -1 : 1;
 }
References MY_CS_TOOSMALL, and charset_info_st::tab_to_uni.
my_numcells_8bit()
size_t my_numcells_8bit (CHARSET_INFO *cs __attribute__(unused), const char * b, const char * e)
Definition at line 1030 of file ctype-simple.c.
 {
   return (size_t) (e - b);
 }
References b.
my_numchars_8bit()
size_t my_numchars_8bit (CHARSET_INFO *cs __attribute__(unused), const char * b, const char * e)
Definition at line 1023 of file ctype-simple.c.
 {
   return (size_t) (e - b);
 }
References b.
my_propagate_complex()
my_bool my_propagate_complex (CHARSET_INFO *cs __attribute__(unused), const uchar *str __attribute__(unused), size_t length __attribute__(unused))
Definition at line 1652 of file ctype-simple.c.
 {
   return 0;
 }
my_propagate_simple()
my_bool my_propagate_simple (CHARSET_INFO *cs __attribute__(unused), const uchar *str __attribute__(unused), size_t length __attribute__(unused))
Definition at line 1644 of file ctype-simple.c.
 {
   return 1;
 }
my_scan_8bit()
size_t my_scan_8bit (CHARSET_INFO * cs, const char * str, const char * end, int sq)
Definition at line 990 of file ctype-simple.c.
 {
   const char *str0= str;
   switch (sq)
   {
   case MY_SEQ_INTTAIL:
     if (*str == '.')
     {
       for(str++ ; str != end && *str == '0' ; str++);
       return (size_t) (str - str0);
     }
     return 0;
   case MY_SEQ_SPACES:
     for ( ; str < end ; str++)
     {
       if (!my_isspace(cs,*str))
         break;
     }
     return (size_t) (str - str0);
   default:
     return 0;
   }
 }
References my_isspace, MY_SEQ_INTTAIL, and MY_SEQ_SPACES.
my_snprintf_8bit()
size_t my_snprintf_8bit (CHARSET_INFO *cs __attribute__(unused), char * to, size_t n __attribute__(unused), const char * fmt, ...)
Definition at line 289 of file ctype-simple.c.
 {
   va_list args;
   int result;
   va_start(args,fmt);
   result= my_vsnprintf(to, n, fmt, args);
   va_end(args);
   return result;
 }
References fmt, and my_vsnprintf().
my_strcasecmp_8bit()
int my_strcasecmp_8bit (CHARSET_INFO * cs, const char * s, const char * t)
Definition at line 241 of file ctype-simple.c.
 {
   register uchar *map=cs->to_upper;
   while (map[(uchar) *s] == map[(uchar) *t++])
     if (!*s++) return 0;
   return ((int) map[(uchar) s[0]] - (int) map[(uchar) t[-1]]);
 }
References charset_info_st::to_upper.
my_strnncoll_simple()
int my_strnncoll_simple (CHARSET_INFO * cs, const uchar * s, size_t slen, const uchar * t, size_t tlen, my_bool t_is_prefix)
Definition at line 99 of file ctype-simple.c.
 {
   size_t len = ( slen > tlen ) ? tlen : slen;
   uchar *map= cs->sort_order;
   if (t_is_prefix && slen > tlen)
     slen=tlen;
   while (len--)
   {
     if (map[*s++] != map[*t++])
       return ((int) map[s[-1]] - (int) map[t[-1]]);
   }
   /*
     We can't use (slen - tlen) here as the result may be outside of the
     precision of a signed int
   */
   return slen > tlen ? 1 : slen < tlen ? -1 : 0 ;
 }
References charset_info_st::sort_order.
my_strnncollsp_simple()
int my_strnncollsp_simple (CHARSET_INFO * cs, const uchar * a, size_t a_length, const uchar * b, size_t b_length, my_bool diff_if_only_endspace_difference)
Definition at line 150 of file ctype-simple.c.
 {
   const uchar *map= cs->sort_order, *end;
   size_t length;
   int res;
 #ifndef VARCHAR_WITH_DIFF_ENDSPACE_ARE_DIFFERENT_FOR_UNIQUE
   diff_if_only_endspace_difference= 0;
 #endif
   end= a + (length= min(a_length, b_length));
   while (a < end)
   {
     if (map[*a++] != map[*b++])
       return ((int) map[a[-1]] - (int) map[b[-1]]);
   }
   res= 0;
   if (a_length != b_length)
   {
     int swap= 1;
     if (diff_if_only_endspace_difference)
       res= 1;                                   /* Assume 'a' is bigger */
     /*
       Check the next not space character of the longer key. If it's < ' ',
       then it's smaller than the other key.
     */
     if (a_length < b_length)
     {
       /* put shorter key in s */
       a_length= b_length;
       a= b;
       swap= -1;                                 /* swap sign of result */
       res= -res;
     }
     for (end= a + a_length-length; a < end ; a++)
     {
       if (map[*a] != map[' '])
     return (map[*a] < map[' ']) ? -swap : swap;
     }
   }
   return res;
 }
References mpq::a, b, G3D::length(), min, charset_info_st::sort_order, and swap().
my_strntod_8bit()
double my_strntod_8bit (CHARSET_INFO *cs __attribute__(unused), char * str, size_t length, char ** end, int * err)
Definition at line 715 of file ctype-simple.c.
 {
   if (length == INT_MAX32)
     length= 65535;                          /* Should be big enough */
   *end= str + length;
   return my_strtod(str, end, err);
 }
References INT_MAX32, G3D::length(), and my_strtod().
my_strntol_8bit()
long my_strntol_8bit (CHARSET_INFO * cs, const char * nptr, size_t l, int base, char ** endptr, int * err)
Definition at line 324 of file ctype-simple.c.
 {
   int negative;
   register uint32 cutoff;
   register uint cutlim;
   register uint32 i;
   register const char *s;
   register uchar c;
   const char *save, *e;
   int overflow;
   *err= 0;              /* Initialize error indicator */
   s = nptr;
   e = nptr+l;
   for ( ; s<e && my_isspace(cs, *s) ; s++);
   if (s == e)
   {
     goto noconv;
   }
   /* Check for a sign.  */
   if (*s == '-')
   {
     negative = 1;
     ++s;
   }
   else if (*s == '+')
   {
     negative = 0;
     ++s;
   }
   else
     negative = 0;
   save = s;
   cutoff = ((uint32)~0L) / (uint32) base;
   cutlim = (uint) (((uint32)~0L) % (uint32) base);
   overflow = 0;
   i = 0;
   for (c = *s; s != e; c = *++s)
   {
     if (c>='0' && c<='9')
       c -= '0';
     else if (c>='A' && c<='Z')
       c = c - 'A' + 10;
     else if (c>='a' && c<='z')
       c = c - 'a' + 10;
     else
       break;
     if (c >= base)
       break;
     if (i > cutoff || (i == cutoff && c > cutlim))
       overflow = 1;
     else
     {
       i *= (uint32) base;
       i += c;
     }
   }
   if (s == save)
     goto noconv;
   if (endptr != NULL)
     *endptr = (char *) s;
   if (negative)
   {
     if (i  > (uint32) INT_MIN32)
       overflow = 1;
   }
   else if (i > INT_MAX32)
     overflow = 1;
   if (overflow)
   {
     err[0]= ERANGE;
     return negative ? INT_MIN32 : INT_MAX32;
   }
   return (negative ? -((long) i) : (long) i);
 noconv:
   err[0]= EDOM;
   if (endptr != NULL)
     *endptr = (char *) nptr;
   return 0L;
 }
References mpq::c, INT_MAX32, INT_MIN32, mpq::l, my_isspace, and NULL.
my_strntoll_8bit()
longlong my_strntoll_8bit (CHARSET_INFO *cs __attribute__(unused), const char * nptr, size_t l, int base, char ** endptr, int * err)
Definition at line 507 of file ctype-simple.c.
 {
   int negative;
   register ulonglong cutoff;
   register uint cutlim;
   register ulonglong i;
   register const char *s, *e;
   const char *save;
   int overflow;
   *err= 0;              /* Initialize error indicator */
   s = nptr;
   e = nptr+l;
   for(; s<e && my_isspace(cs,*s); s++);
   if (s == e)
   {
     goto noconv;
   }
   if (*s == '-')
   {
     negative = 1;
     ++s;
   }
   else if (*s == '+')
   {
     negative = 0;
     ++s;
   }
   else
     negative = 0;
   save = s;
   cutoff = (~(ulonglong) 0) / (unsigned long int) base;
   cutlim = (uint) ((~(ulonglong) 0) % (unsigned long int) base);
   overflow = 0;
   i = 0;
   for ( ; s != e; s++)
   {
     register uchar c= *s;
     if (c>='0' && c<='9')
       c -= '0';
     else if (c>='A' && c<='Z')
       c = c - 'A' + 10;
     else if (c>='a' && c<='z')
       c = c - 'a' + 10;
     else
       break;
     if (c >= base)
       break;
     if (i > cutoff || (i == cutoff && c > cutlim))
       overflow = 1;
     else
     {
       i *= (ulonglong) base;
       i += c;
     }
   }
   if (s == save)
     goto noconv;
   if (endptr != NULL)
     *endptr = (char *) s;
   if (negative)
   {
     if (i  > (ulonglong) LONGLONG_MIN)
       overflow = 1;
   }
   else if (i > (ulonglong) LONGLONG_MAX)
     overflow = 1;
   if (overflow)
   {
     err[0]= ERANGE;
     return negative ? LONGLONG_MIN : LONGLONG_MAX;
   }
   return (negative ? -((longlong) i) : (longlong) i);
 noconv:
   err[0]= EDOM;
   if (endptr != NULL)
     *endptr = (char *) nptr;
   return 0L;
 }
References mpq::c, mpq::l, my_isspace, and NULL.
my_strntoul_8bit()
ulong my_strntoul_8bit (CHARSET_INFO * cs, const char * nptr, size_t l, int base, char ** endptr, int * err)
Definition at line 420 of file ctype-simple.c.
 {
   int negative;
   register uint32 cutoff;
   register uint cutlim;
   register uint32 i;
   register const char *s;
   register uchar c;
   const char *save, *e;
   int overflow;
   *err= 0;              /* Initialize error indicator */
   s = nptr;
   e = nptr+l;
   for( ; s<e && my_isspace(cs, *s); s++);
   if (s==e)
   {
     goto noconv;
   }
   if (*s == '-')
   {
     negative = 1;
     ++s;
   }
   else if (*s == '+')
   {
     negative = 0;
     ++s;
   }
   else
     negative = 0;
   save = s;
   cutoff = ((uint32)~0L) / (uint32) base;
   cutlim = (uint) (((uint32)~0L) % (uint32) base);
   overflow = 0;
   i = 0;
   for (c = *s; s != e; c = *++s)
   {
     if (c>='0' && c<='9')
       c -= '0';
     else if (c>='A' && c<='Z')
       c = c - 'A' + 10;
     else if (c>='a' && c<='z')
       c = c - 'a' + 10;
     else
       break;
     if (c >= base)
       break;
     if (i > cutoff || (i == cutoff && c > cutlim))
       overflow = 1;
     else
     {
       i *= (uint32) base;
       i += c;
     }
   }
   if (s == save)
     goto noconv;
   if (endptr != NULL)
     *endptr = (char *) s;
   if (overflow)
   {
     err[0]= ERANGE;
     return (~(uint32) 0);
   }
   return (negative ? -((long) i) : (long) i);
 noconv:
   err[0]= EDOM;
   if (endptr != NULL)
     *endptr = (char *) nptr;
   return 0L;
 }
References mpq::c, mpq::l, my_isspace, and NULL.
my_strntoull10rnd_8bit()
ulonglong my_strntoull10rnd_8bit (CHARSET_INFO *cs __attribute__(unused), const char * str, size_t length, int unsigned_flag, char ** endptr, int * error)
Definition at line 1366 of file ctype-simple.c.
 {
   const char *dot, *end9, *beg, *end= str + length;
   ulonglong ull;
   ulong ul;
   uchar ch;
   int shift= 0, digits= 0, negative, addon;
   /* Skip leading spaces and tabs */
   for ( ; str < end && (*str == ' ' || *str == '\t') ; str++);
   if (str >= end)
     goto ret_edom;
   if ((negative= (*str == '-')) || *str=='+') /* optional sign */
   {
     if (++str == end)
       goto ret_edom;
   }
   beg= str;
   end9= (str + 9) > end ? end : (str + 9);
   /* Accumulate small number into ulong, for performance purposes */
   for (ul= 0 ; str < end9 && (ch= (uchar) (*str - '0')) < 10; str++)
   {
     ul= ul * 10 + ch;
   }
   if (str >= end) /* Small number without dots and expanents */
   {
     *endptr= (char*) str;
     if (negative)
     {
       if (unsigned_flag)
       {
         *error= ul ? MY_ERRNO_ERANGE : 0;
         return 0;
       }
       else
       {
         *error= 0;
         return (ulonglong) (longlong) -(long) ul;
       }
     }
     else
     {
       *error=0;
       return (ulonglong) ul;
     }
   }
   digits= str - beg;
   /* Continue to accumulate into ulonglong */
   for (dot= NULL, ull= ul; str < end; str++)
   {
     if ((ch= (uchar) (*str - '0')) < 10)
     {
       if (ull < CUTOFF || (ull == CUTOFF && ch <= CUTLIM))
       {
         ull= ull * 10 + ch;
         digits++;
         continue;
       }
       /*
         Adding the next digit would overflow.
         Remember the next digit in "addon", for rounding.
         Scan all digits with an optional single dot.
       */
       if (ull == CUTOFF)
       {
         ull= ULONGLONG_MAX;
         addon= 1;
         str++;
       }
       else
         addon= (*str >= '5');
       if (!dot)
       {
         for ( ; str < end && (ch= (uchar) (*str - '0')) < 10; shift++, str++);
         if (str < end && *str == '.')
         {
           str++;
           for ( ; str < end && (ch= (uchar) (*str - '0')) < 10; str++);
         }
       }
       else
       {
         shift= dot - str;
         for ( ; str < end && (ch= (uchar) (*str - '0')) < 10; str++);
       }
       goto exp;
     }
     if (*str == '.')
     {
       if (dot)
       {
         /* The second dot character */
         addon= 0;
         goto exp;
       }
       else
       {
         dot= str + 1;
       }
       continue;
     }
     /* Unknown character, exit the loop */
     break;
   }
   shift= dot ? dot - str : 0; /* Right shift */
   addon= 0;
 exp:    /* [ E [ <sign> ] <unsigned integer> ] */
   if (!digits)
   {
     str= beg;
     goto ret_edom;
   }
   if (str < end && (*str == 'e' || *str == 'E'))
   {
     str++;
     if (str < end)
     {
       int negative_exp, exponent;
       if ((negative_exp= (*str == '-')) || *str=='+')
       {
         if (++str == end)
           goto ret_sign;
       }
       for (exponent= 0 ;
            str < end && (ch= (uchar) (*str - '0')) < 10;
            str++)
       {
         exponent= exponent * 10 + ch;
       }
       shift+= negative_exp ? -exponent : exponent;
     }
   }
   if (shift == 0) /* No shift, check addon digit */
   {
     if (addon)
     {
       if (ull == ULONGLONG_MAX)
         goto ret_too_big;
       ull++;
     }
     goto ret_sign;
   }
   if (shift < 0) /* Right shift */
   {
     ulonglong d, r;
     if (-shift >= DIGITS_IN_ULONGLONG)
       goto ret_zero; /* Exponent is a big negative number, return 0 */
     d= d10[-shift];
     r= (ull % d) * 2;
     ull /= d;
     if (r >= d)
       ull++;
     goto ret_sign;
   }
   if (shift > DIGITS_IN_ULONGLONG) /* Huge left shift */
   {
     if (!ull)
       goto ret_sign;
     goto ret_too_big;
   }
   for ( ; shift > 0; shift--, ull*= 10) /* Left shift */
   {
     if (ull > CUTOFF)
       goto ret_too_big; /* Overflow, number too big */
   }
 ret_sign:
   *endptr= (char*) str;
   if (!unsigned_flag)
   {
     if (negative)
     {
       if (ull > (ulonglong) LONGLONG_MIN)
       {
         *error= MY_ERRNO_ERANGE;
         return (ulonglong) LONGLONG_MIN;
       }
       *error= 0;
       return (ulonglong) -(longlong) ull;
     }
     else
     {
       if (ull > (ulonglong) LONGLONG_MAX)
       {
         *error= MY_ERRNO_ERANGE;
         return (ulonglong) LONGLONG_MAX;
       }
       *error= 0;
       return ull;
     }
   }
   /* Unsigned number */
   if (negative && ull)
   {
     *error= MY_ERRNO_ERANGE;
     return 0;
   }
   *error= 0;
   return ull;
 ret_zero:
   *endptr= (char*) str;
   *error= 0;
   return 0;
 ret_edom:
   *endptr= (char*) str;
   *error= MY_ERRNO_EDOM;
   return 0;
 ret_too_big:
   *endptr= (char*) str;
   *error= MY_ERRNO_ERANGE;
   return unsigned_flag ?
          ULONGLONG_MAX :
          negative ? (ulonglong) LONGLONG_MIN : (ulonglong) LONGLONG_MAX;
 }
References CUTLIM, CUTOFF, mpq::d, d10, DIGITS_IN_ULONGLONG, G3D::dot(), error(), G3D::length(), MY_ERRNO_EDOM, MY_ERRNO_ERANGE, NULL, and ULONGLONG_MAX.
my_strntoull_8bit()
ulonglong my_strntoull_8bit (CHARSET_INFO * cs, const char * nptr, size_t l, int base, char ** endptr, int * err)
Definition at line 603 of file ctype-simple.c.
 {
   int negative;
   register ulonglong cutoff;
   register uint cutlim;
   register ulonglong i;
   register const char *s, *e;
   const char *save;
   int overflow;
   *err= 0;              /* Initialize error indicator */
   s = nptr;
   e = nptr+l;
   for(; s<e && my_isspace(cs,*s); s++);
   if (s == e)
   {
     goto noconv;
   }
   if (*s == '-')
   {
     negative = 1;
     ++s;
   }
   else if (*s == '+')
   {
     negative = 0;
     ++s;
   }
   else
     negative = 0;
   save = s;
   cutoff = (~(ulonglong) 0) / (unsigned long int) base;
   cutlim = (uint) ((~(ulonglong) 0) % (unsigned long int) base);
   overflow = 0;
   i = 0;
   for ( ; s != e; s++)
   {
     register uchar c= *s;
     if (c>='0' && c<='9')
       c -= '0';
     else if (c>='A' && c<='Z')
       c = c - 'A' + 10;
     else if (c>='a' && c<='z')
       c = c - 'a' + 10;
     else
       break;
     if (c >= base)
       break;
     if (i > cutoff || (i == cutoff && c > cutlim))
       overflow = 1;
     else
     {
       i *= (ulonglong) base;
       i += c;
     }
   }
   if (s == save)
     goto noconv;
   if (endptr != NULL)
     *endptr = (char *) s;
   if (overflow)
   {
     err[0]= ERANGE;
     return (~(ulonglong) 0);
   }
   return (negative ? -((longlong) i) : (longlong) i);
 noconv:
   err[0]= EDOM;
   if (endptr != NULL)
     *endptr = (char *) nptr;
   return 0L;
 }
References mpq::c, mpq::l, my_isspace, and NULL.
my_strnxfrm_simple()
size_t my_strnxfrm_simple (CHARSET_INFO * cs, uchar * dest, size_t len, const uchar * src, size_t srclen)
Definition at line 74 of file ctype-simple.c.
 {
   uchar *map= cs->sort_order;
   size_t dstlen= len;
   set_if_smaller(len, srclen);
   if (dest != src)
   {
     const uchar *end;
     for ( end=src+len; src < end ;  )
       *dest++= map[*src++];
   }
   else
   {
     const uchar *end;
     for ( end=dest+len; dest < end ; dest++)
       *dest= (char) map[(uchar) *dest];
   }
   if (dstlen > len)
     bfill(dest, dstlen - len, ' ');
   return dstlen;
 }
References bfill, set_if_smaller, and charset_info_st::sort_order.
my_strnxfrmlen_simple()
size_t my_strnxfrmlen_simple (CHARSET_INFO * cs, size_t len)
Definition at line 28 of file ctype-simple.c.
 {
   return len * (cs->strxfrm_multiply ? cs->strxfrm_multiply : 1);
 }
References charset_info_st::strxfrm_multiply.
my_strtoll10_8bit()
longlong my_strtoll10_8bit (CHARSET_INFO *cs __attribute__(unused), const char * nptr, char ** endptr, int * error)
Definition at line 1260 of file ctype-simple.c.
 {
   return my_strtoll10(nptr, endptr, error);
 }
References error(), and my_strtoll10().
my_wc_mb_8bit()
int my_wc_mb_8bit (CHARSET_INFO * cs, my_wc_t wc, uchar * str, uchar * end)
Definition at line 261 of file ctype-simple.c.
 {
   MY_UNI_IDX *idx;
   if (str >= end)
     return MY_CS_TOOSMALL;
   for (idx=cs->tab_from_uni; idx->tab ; idx++)
   {
     if (idx->from <= wc && idx->to >= wc)
     {
       str[0]= idx->tab[wc - idx->from];
       return (!str[0] && wc) ? MY_CS_ILUNI : 1;
     }
   }
   return MY_CS_ILUNI;
 }
References idx, MY_CS_ILUNI, MY_CS_TOOSMALL, and charset_info_st::tab_from_uni.
my_well_formed_len_8bit()
size_t my_well_formed_len_8bit (CHARSET_INFO *cs __attribute__(unused), const char * start, const char * end, size_t nchars, int * error)
Definition at line 1046 of file ctype-simple.c.
 {
   size_t nbytes= (size_t) (end-start);
   *error= 0;
   return min(nbytes, nchars);
 }
References error(), and min.
my_wildcmp_8bit()
int my_wildcmp_8bit (CHARSET_INFO * cs, const char * str, const char * str_end, const char * wildstr, const char * wildend, int escape, int w_one, int w_many)
Definition at line 844 of file ctype-simple.c.
 {
   int result= -1;           /* Not found, using wildcards */
   while (wildstr != wildend)
   {
     while (*wildstr != w_many && *wildstr != w_one)
     {
       if (*wildstr == escape && wildstr+1 != wildend)
     wildstr++;
       if (str == str_end || likeconv(cs,*wildstr++) != likeconv(cs,*str++))
     return(1);              /* No match */
       if (wildstr == wildend)
     return(str != str_end);     /* Match if both are at end */
       result=1;                 /* Found an anchor char     */
     }
     if (*wildstr == w_one)
     {
       do
       {
     if (str == str_end)         /* Skip one char if possible */
       return(result);
     INC_PTR(cs,str,str_end);
       } while (++wildstr < wildend && *wildstr == w_one);
       if (wildstr == wildend)
     break;
     }
     if (*wildstr == w_many)
     {                       /* Found w_many */
       uchar cmp;
       wildstr++;
       /* Remove any '%' and '_' from the wild search string */
       for (; wildstr != wildend ; wildstr++)
       {
     if (*wildstr == w_many)
       continue;
     if (*wildstr == w_one)
     {
       if (str == str_end)
         return(-1);
       INC_PTR(cs,str,str_end);
       continue;
     }
     break;                  /* Not a wild character */
       }
       if (wildstr == wildend)
     return(0);              /* Ok if w_many is last */
       if (str == str_end)
     return(-1);
       if ((cmp= *wildstr) == escape && wildstr+1 != wildend)
     cmp= *++wildstr;
       INC_PTR(cs,wildstr,wildend);  /* This is compared trough cmp */
       cmp=likeconv(cs,cmp);
       do
       {
     while (str != str_end && (uchar) likeconv(cs,*str) != cmp)
       str++;
     if (str++ == str_end) return(-1);
     {
       int tmp=my_wildcmp_8bit(cs,str,str_end,wildstr,wildend,escape,w_one,
                   w_many);
       if (tmp <= 0)
         return(tmp);
     }
       } while (str != str_end && wildstr[0] != w_many);
       return(-1);
     }
   }
   return(str != str_end ? 1 : 0);
 }
References cmp, G3D::escape(), INC_PTR, likeconv, and my_wildcmp_8bit().
Referenced by my_wildcmp_8bit().
pcmp()
static int pcmp (const void * f, const void * s) static
Definition at line 1135 of file ctype-simple.c.
 {
   const uni_idx *F= (const uni_idx*) f;
   const uni_idx *S= (const uni_idx*) s;
   int res;
   if (!(res=((S->nchars)-(F->nchars))))
     res=((F->uidx.from)-(S->uidx.to));
   return res;
 }
References f(), F, uni_idx::nchars, my_uni_idx_st::to, and uni_idx::uidx.
Referenced by create_fromuni().
set_max_sort_char()
static void set_max_sort_char (CHARSET_INFO * cs) static
Definition at line 1233 of file ctype-simple.c.
 {
   uchar max_char;
   uint  i;
   if (!cs->sort_order)
     return;
   max_char=cs->sort_order[(uchar) cs->max_sort_char];
   for (i= 0; i < 256; i++)
   {
     if ((uchar) cs->sort_order[i] > max_char)
     {
       max_char=(uchar) cs->sort_order[i];
       cs->max_sort_char= i;
     }
   }
 }
References charset_info_st::max_sort_char, and charset_info_st::sort_order.
Referenced by my_coll_init_simple().
Variable Documentation
d10
ulonglong d10[DIGITS_IN_ULONGLONG] static
Initial value:
=
{
  1,
  10,
  100,
  1000,
  10000,
  100000,
  1000000,
  10000000,
  100000000,
  1000000000,
  10000000000ULL,
  100000000000ULL,
  1000000000000ULL,
  10000000000000ULL,
  100000000000000ULL,
  1000000000000000ULL,
  10000000000000000ULL,
  100000000000000000ULL,
  1000000000000000000ULL,
  10000000000000000000ULL
}
Definition at line 1284 of file ctype-simple.c.
Referenced by my_strntoull10rnd_8bit().
my_charset_8bit_handler
MY_CHARSET_HANDLER my_charset_8bit_handler
Initial value:
=
{
    my_cset_init_8bit,
    NULL,
    my_mbcharlen_8bit,
    my_numchars_8bit,
    my_charpos_8bit,
    my_well_formed_len_8bit,
    my_lengthsp_8bit,
    my_numcells_8bit,
    my_mb_wc_8bit,
    my_wc_mb_8bit,
    my_mb_ctype_8bit,
    my_caseup_str_8bit,
    my_casedn_str_8bit,
    my_caseup_8bit,
    my_casedn_8bit,
    my_snprintf_8bit,
    my_long10_to_str_8bit,
    my_longlong10_to_str_8bit,
    my_fill_8bit,
    my_strntol_8bit,
    my_strntoul_8bit,
    my_strntoll_8bit,
    my_strntoull_8bit,
    my_strntod_8bit,
    my_strtoll10_8bit,
    my_strntoull10rnd_8bit,
    my_scan_8bit
}
Definition at line 1660 of file ctype-simple.c.
Referenced by simple_cs_init_functions().
my_collation_8bit_simple_ci_handler
MY_COLLATION_HANDLER my_collation_8bit_simple_ci_handler
Initial value:
=
{
    my_coll_init_simple,
    my_strnncoll_simple,
    my_strnncollsp_simple,
    my_strnxfrm_simple,
    my_strnxfrmlen_simple,
    my_like_range_simple,
    my_wildcmp_8bit,
    my_strcasecmp_8bit,
    my_instr_simple,
    my_hash_sort_simple,
    my_propagate_simple
}
Definition at line 1691 of file ctype-simple.c.
Referenced by simple_cs_init_functions().