Azerotcore-wotlk: OPvPCapturePointTF Class Reference
OPvPCapturePointTF Class Reference
#include <OutdoorPvPTF.h>
Public Member Functions
OPvPCapturePointTF (OutdoorPvP *pvp, OutdoorPvPTF_TowerType type)
bool Update (uint32 diff) override
void ChangeState () override
void SendChangePhase () override
void FillInitialWorldStates (WorldPacket &data) override
bool HandlePlayerEnter (Player *player) override
void HandlePlayerLeave (Player *player) override
void UpdateTowerState ()
Public Member Functions inherited from OPvPCapturePoint
OPvPCapturePoint (OutdoorPvP *pvp)
virtual ~OPvPCapturePoint ()
void SendUpdateWorldState (uint32 field, uint32 value)
void SendObjectiveComplete (uint32 id, ObjectGuid guid=ObjectGuid::Empty)
bool IsInsideObjective (Player *player) const
virtual bool HandleCustomSpell (Player *player, uint32 spellId, GameObject *go)
virtual int32 HandleOpenGo (Player *player, GameObject *go)
virtual void ChangeTeam (TeamId)
virtual bool HandleGossipOption (Player *player, Creature *creature, uint32 gossipid)
virtual bool CanTalkTo (Player *player, Creature *c, GossipMenuItems const &gso)
virtual bool HandleDropFlag (Player *player, uint32 spellId)
virtual void DeleteSpawns ()
void AddGO (uint32 type, ObjectGuid::LowType guid, uint32 entry=0)
void AddCre (uint32 type, ObjectGuid::LowType guid, uint32 entry=0)
bool SetCapturePointData (uint32 entry, uint32 map, float x, float y, float z, float o=0, float rotation0=0, float rotation1=0, float rotation2=0, float rotation3=0)
Protected Attributes
OutdoorPvPTF_TowerType m_TowerType
uint32 m_TowerState
Protected Attributes inherited from OPvPCapturePoint
PlayerSet m_activePlayers [2]
float m_maxValue
float m_minValue
float m_maxSpeed
float m_value
TeamId m_team
ObjectiveStates m_OldState
ObjectiveStates m_State
uint32 m_neutralValuePct
OutdoorPvP * m_PvP
std::map< uint32, ObjectGuid::LowType > m_Objects
std::map< uint32, ObjectGuid::LowType > m_Creatures
std::map< ObjectGuid::LowType, uint32 > m_ObjectTypes
std::map< ObjectGuid::LowType, uint32 > m_CreatureTypes
Additional Inherited Members
Public Attributes inherited from OPvPCapturePoint
ObjectGuid::LowType m_capturePointSpawnId
GameObject * m_capturePoint
Protected Member Functions inherited from OPvPCapturePoint
bool AddObject (uint32 type, uint32 entry, uint32 map, float x, float y, float z, float o, float rotation0, float rotation1, float rotation2, float rotation3)
bool AddCreature (uint32 type, uint32 entry, uint32 map, float x, float y, float z, float o, uint32 spawntimedelay=0)
bool DelCreature (uint32 type)
bool DelObject (uint32 type)
bool DelCapturePoint ()
Detailed Description
Definition at line 124 of file OutdoorPvPTF.h.
Constructor & Destructor Documentation
OPvPCapturePointTF()
OPvPCapturePointTF::OPvPCapturePointTF (OutdoorPvP * pvp, OutdoorPvPTF_TowerType type)
Definition at line 45 of file OutdoorPvPTF.cpp.
     : OPvPCapturePoint(pvp), m_TowerType(type), m_TowerState(TF_TOWERSTATE_N)
 {
     SetCapturePointData(TFCapturePoints[type].entry, TFCapturePoints[type].map, TFCapturePoints[type].x, TFCapturePoints[type].y, TFCapturePoints[type].z, TFCapturePoints[type].o, TFCapturePoints[type].rot0, TFCapturePoints[type].rot1, TFCapturePoints[type].rot2, TFCapturePoints[type].rot3);
 }
References OPvPCapturePoint::SetCapturePointData(), TFCapturePoints, G3D::x, G3D::y, and G3D::z.
Member Function Documentation
ChangeState()
void OPvPCapturePointTF::ChangeState () override virtual
Implements OPvPCapturePoint.
Definition at line 286 of file OutdoorPvPTF.cpp.
 {
     // if changing from controlling alliance to horde
     if (m_OldState == OBJECTIVESTATE_ALLIANCE)
     {
         if (uint32 alliance_towers = ((OutdoorPvPTF*)m_PvP)->GetAllianceTowersControlled())
             ((OutdoorPvPTF*)m_PvP)->SetAllianceTowersControlled(--alliance_towers);
         sWorld->SendZoneText(OutdoorPvPTFBuffZones[0], sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_TF_LOSE_A));
     }
     // if changing from controlling horde to alliance
     else if (m_OldState == OBJECTIVESTATE_HORDE)
     {
         if (uint32 horde_towers = ((OutdoorPvPTF*)m_PvP)->GetHordeTowersControlled())
             ((OutdoorPvPTF*)m_PvP)->SetHordeTowersControlled(--horde_towers);
         sWorld->SendZoneText(OutdoorPvPTFBuffZones[0], sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_TF_LOSE_H));
     }
     uint32 artkit = 21;
     switch (m_State)
     {
         case OBJECTIVESTATE_ALLIANCE:
             {
                 m_TowerState = TF_TOWERSTATE_A;
                 artkit = 2;
                 uint32 alliance_towers = ((OutdoorPvPTF*)m_PvP)->GetAllianceTowersControlled();
                 if (alliance_towers < TF_TOWER_NUM)
                     ((OutdoorPvPTF*)m_PvP)->SetAllianceTowersControlled(++alliance_towers);
                 sWorld->SendZoneText(OutdoorPvPTFBuffZones[0], sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_TF_CAPTURE_A));
                 for (PlayerSet::iterator itr = m_activePlayers[0].begin(); itr != m_activePlayers[0].end(); ++itr)
                     if (Player* player = ObjectAccessor::FindPlayer(*itr))
                         player->AreaExploredOrEventHappens(TF_ALLY_QUEST);
                 break;
             }
         case OBJECTIVESTATE_HORDE:
             {
                 m_TowerState = TF_TOWERSTATE_H;
                 artkit = 1;
                 uint32 horde_towers = ((OutdoorPvPTF*)m_PvP)->GetHordeTowersControlled();
                 if (horde_towers < TF_TOWER_NUM)
                     ((OutdoorPvPTF*)m_PvP)->SetHordeTowersControlled(++horde_towers);
                 sWorld->SendZoneText(OutdoorPvPTFBuffZones[0], sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_TF_CAPTURE_H));
                 for (PlayerSet::iterator itr = m_activePlayers[1].begin(); itr != m_activePlayers[1].end(); ++itr)
                     if (Player* player = ObjectAccessor::FindPlayer(*itr))
                         player->AreaExploredOrEventHappens(TF_HORDE_QUEST);
                 break;
             }
         case OBJECTIVESTATE_NEUTRAL:
         case OBJECTIVESTATE_NEUTRAL_ALLIANCE_CHALLENGE:
         case OBJECTIVESTATE_NEUTRAL_HORDE_CHALLENGE:
         case OBJECTIVESTATE_ALLIANCE_HORDE_CHALLENGE:
         case OBJECTIVESTATE_HORDE_ALLIANCE_CHALLENGE:
             m_TowerState = TF_TOWERSTATE_N;
             break;
     }
     auto bounds = sMapMgr->FindMap(530, 0)->GetGameObjectBySpawnIdStore().equal_range(m_capturePointSpawnId);
     for (auto itr = bounds.first; itr != bounds.second; ++itr)
         itr->second->SetGoArtKit(artkit);
     UpdateTowerState();
 }
References ObjectAccessor::FindPlayer(), LANG_OPVP_TF_CAPTURE_A, LANG_OPVP_TF_CAPTURE_H, LANG_OPVP_TF_LOSE_A, LANG_OPVP_TF_LOSE_H, OPvPCapturePoint::m_activePlayers, OPvPCapturePoint::m_capturePointSpawnId, OPvPCapturePoint::m_OldState, OPvPCapturePoint::m_PvP, OPvPCapturePoint::m_State, m_TowerState, OBJECTIVESTATE_ALLIANCE, OBJECTIVESTATE_ALLIANCE_HORDE_CHALLENGE, OBJECTIVESTATE_HORDE, OBJECTIVESTATE_HORDE_ALLIANCE_CHALLENGE, OBJECTIVESTATE_NEUTRAL, OBJECTIVESTATE_NEUTRAL_ALLIANCE_CHALLENGE, OBJECTIVESTATE_NEUTRAL_HORDE_CHALLENGE, OutdoorPvPTFBuffZones, sMapMgr, sObjectMgr, sWorld, TF_ALLY_QUEST, TF_HORDE_QUEST, TF_TOWER_NUM, TF_TOWERSTATE_A, TF_TOWERSTATE_H, TF_TOWERSTATE_N, and UpdateTowerState().
FillInitialWorldStates()
void OPvPCapturePointTF::FillInitialWorldStates (WorldPacket & data) override virtual
Reimplemented from OPvPCapturePoint.
Definition at line 51 of file OutdoorPvPTF.cpp.
 {
     data << uint32(TFTowerWorldStates[m_TowerType].n) << uint32(bool(m_TowerState & TF_TOWERSTATE_N));
     data << uint32(TFTowerWorldStates[m_TowerType].h) << uint32(bool(m_TowerState & TF_TOWERSTATE_H));
     data << uint32(TFTowerWorldStates[m_TowerType].a) << uint32(bool(m_TowerState & TF_TOWERSTATE_A));
 }
References mpq::a, m_TowerState, m_TowerType, TF_TOWERSTATE_A, TF_TOWERSTATE_H, TF_TOWERSTATE_N, and TFTowerWorldStates.
HandlePlayerEnter()
bool OPvPCapturePointTF::HandlePlayerEnter (Player * player) override virtual
Reimplemented from OPvPCapturePoint.
Definition at line 115 of file OutdoorPvPTF.cpp.
 {
     if (OPvPCapturePoint::HandlePlayerEnter(player))
     {
         player->SendUpdateWorldState(TF_UI_TOWER_SLIDER_DISPLAY, 1);
         uint32 phase = (uint32)ceil((m_value + m_maxValue) / (2 * m_maxValue) * 100.0f);
         player->SendUpdateWorldState(TF_UI_TOWER_SLIDER_POS, phase);
         player->SendUpdateWorldState(TF_UI_TOWER_SLIDER_N, m_neutralValuePct);
         return true;
     }
     return false;
 }
References G3D::ceil(), OPvPCapturePoint::HandlePlayerEnter(), OPvPCapturePoint::m_maxValue, OPvPCapturePoint::m_neutralValuePct, OPvPCapturePoint::m_value, Player::SendUpdateWorldState(), TF_UI_TOWER_SLIDER_DISPLAY, TF_UI_TOWER_SLIDER_N, and TF_UI_TOWER_SLIDER_POS.
HandlePlayerLeave()
void OPvPCapturePointTF::HandlePlayerLeave (Player * player) override virtual
Reimplemented from OPvPCapturePoint.
Definition at line 128 of file OutdoorPvPTF.cpp.
 {
     player->SendUpdateWorldState(TF_UI_TOWER_SLIDER_DISPLAY, 0);
     OPvPCapturePoint::HandlePlayerLeave(player);
 }
References OPvPCapturePoint::HandlePlayerLeave(), Player::SendUpdateWorldState(), and TF_UI_TOWER_SLIDER_DISPLAY.
SendChangePhase()
void OPvPCapturePointTF::SendChangePhase () override virtual
Reimplemented from OPvPCapturePoint.
Definition at line 353 of file OutdoorPvPTF.cpp.
 {
     // send this too, sometimes the slider disappears, dunno why :(
     SendUpdateWorldState(TF_UI_TOWER_SLIDER_DISPLAY, 1);
     // send these updates to only the ones in this objective
     uint32 phase = (uint32)ceil((m_value + m_maxValue) / (2 * m_maxValue) * 100.0f);
     SendUpdateWorldState(TF_UI_TOWER_SLIDER_POS, phase);
     // send this too, sometimes it resets :S
     SendUpdateWorldState(TF_UI_TOWER_SLIDER_N, m_neutralValuePct);
 }
References G3D::ceil(), OPvPCapturePoint::m_maxValue, OPvPCapturePoint::m_neutralValuePct, OPvPCapturePoint::m_value, OPvPCapturePoint::SendUpdateWorldState(), TF_UI_TOWER_SLIDER_DISPLAY, TF_UI_TOWER_SLIDER_N, and TF_UI_TOWER_SLIDER_POS.
Update()
bool OPvPCapturePointTF::Update (uint32 diff) override virtual
Reimplemented from OPvPCapturePoint.
Definition at line 276 of file OutdoorPvPTF.cpp.
 {
     // can update even in locked state if gathers the controlling faction
     bool canupdate = ((((OutdoorPvPTF*)m_PvP)->GetAllianceTowersControlled() > 0) && m_activePlayers[0].size() > m_activePlayers[1].size()) ||
                      ((((OutdoorPvPTF*)m_PvP)->GetHordeTowersControlled() > 0) && m_activePlayers[0].size() < m_activePlayers[1].size());
     // if gathers the other faction, then only update if the pvp is unlocked
     canupdate = canupdate || !((OutdoorPvPTF*)m_PvP)->IsLocked();
     return canupdate && OPvPCapturePoint::Update(diff);
 }
References diff(), OPvPCapturePoint::m_activePlayers, OPvPCapturePoint::m_PvP, and OPvPCapturePoint::Update().
UpdateTowerState()
void OPvPCapturePointTF::UpdateTowerState ()
Definition at line 108 of file OutdoorPvPTF.cpp.
 {
     m_PvP->SendUpdateWorldState(uint32(TFTowerWorldStates[m_TowerType].n), uint32(bool(m_TowerState & TF_TOWERSTATE_N)));
     m_PvP->SendUpdateWorldState(uint32(TFTowerWorldStates[m_TowerType].h), uint32(bool(m_TowerState & TF_TOWERSTATE_H)));
     m_PvP->SendUpdateWorldState(uint32(TFTowerWorldStates[m_TowerType].a), uint32(bool(m_TowerState & TF_TOWERSTATE_A)));
 }
References mpq::a, OPvPCapturePoint::m_PvP, m_TowerState, m_TowerType, OutdoorPvP::SendUpdateWorldState(), TF_TOWERSTATE_A, TF_TOWERSTATE_H, TF_TOWERSTATE_N, and TFTowerWorldStates.
Referenced by ChangeState().
Member Data Documentation
m_TowerState
uint32 OPvPCapturePointTF::m_TowerState protected
Definition at line 146 of file OutdoorPvPTF.h.
Referenced by ChangeState(), FillInitialWorldStates(), and UpdateTowerState().
m_TowerType
OutdoorPvPTF_TowerType OPvPCapturePointTF::m_TowerType protected
Definition at line 144 of file OutdoorPvPTF.h.
Referenced by FillInitialWorldStates(), and UpdateTowerState().
The documentation for this class was generated from the following files:
src/server/scripts/OutdoorPvP/OutdoorPvPTF.h
src/server/scripts/OutdoorPvP/OutdoorPvPTF.cpp