Azerotcore-wotlk: deps/jemalloc/src/quarantine.c File Reference
quarantine.c File Reference
#include "jemalloc/internal/jemalloc_internal.h"
Macros
#define JEMALLOC_QUARANTINE_C_
#define QUARANTINE_STATE_REINCARNATED ((quarantine_t *)(uintptr_t)1)
#define QUARANTINE_STATE_PURGATORY ((quarantine_t *)(uintptr_t)2)
#define QUARANTINE_STATE_MAX QUARANTINE_STATE_PURGATORY
Functions
malloc_tsd_data (static void quarantine_drain(quarantine_t *quarantine, quarantine_t *, NULL)
static quarantine_t * quarantine_grow (quarantine_t *quarantine)
static void quarantine_drain_one (quarantine_t *quarantine)
static void quarantine_drain (quarantine_t *quarantine, size_t upper_bound)
void quarantine (void *ptr)
void quarantine_cleanup (void *arg)
bool quarantine_boot (void)
Macro Definition Documentation
JEMALLOC_QUARANTINE_C_
#define JEMALLOC_QUARANTINE_C_
Definition at line 1 of file quarantine.c.
QUARANTINE_STATE_MAX
#define QUARANTINE_STATE_MAX QUARANTINE_STATE_PURGATORY
Definition at line 10 of file quarantine.c.
QUARANTINE_STATE_PURGATORY
#define QUARANTINE_STATE_PURGATORY ((quarantine_t *)(uintptr_t)2)
Definition at line 9 of file quarantine.c.
QUARANTINE_STATE_REINCARNATED
#define QUARANTINE_STATE_REINCARNATED ((quarantine_t *)(uintptr_t)1)
Definition at line 8 of file quarantine.c.
Function Documentation
malloc_tsd_data()
malloc_tsd_data (static void quarantine_drain(quarantine_t * quarantine, quarantine_t * , NULL)
Definition at line 15 of file quarantine.c.
 {
     quarantine_t *quarantine;
     quarantine = (quarantine_t *)imalloc(offsetof(quarantine_t, objs) +
         ((ZU(1) << lg_maxobjs) * sizeof(quarantine_obj_t)));
     if (quarantine == NULL)
         return (NULL);
     quarantine->curbytes = 0;
     quarantine->curobjs = 0;
     quarantine->first = 0;
     quarantine->lg_maxobjs = lg_maxobjs;
     quarantine_tsd_set(&quarantine);
     return (quarantine);
 }
quarantine()
void quarantine (void * ptr)
Definition at line 100 of file quarantine.c.
 {
     quarantine_t *quarantine;
     size_t usize = isalloc(ptr, config_prof);
     cassert(config_fill);
     assert(opt_quarantine);
     quarantine = *quarantine_tsd_get();
     if ((uintptr_t)quarantine <= (uintptr_t)QUARANTINE_STATE_MAX) {
         if (quarantine == QUARANTINE_STATE_PURGATORY) {
             /*
              * Make a note that quarantine() was called after
              * quarantine_cleanup() was called.
              */
             quarantine = QUARANTINE_STATE_REINCARNATED;
             quarantine_tsd_set(&quarantine);
         }
         idalloc(ptr);
         return;
     }
     /*
      * Drain one or more objects if the quarantine size limit would be
      * exceeded by appending ptr.
      */
     if (quarantine->curbytes + usize > opt_quarantine) {
         size_t upper_bound = (opt_quarantine >= usize) ? opt_quarantine
             - usize : 0;
         quarantine_drain(quarantine, upper_bound);
     }
     /* Grow the quarantine ring buffer if it's full. */
     if (quarantine->curobjs == (ZU(1) << quarantine->lg_maxobjs))
         quarantine = quarantine_grow(quarantine);
     /* quarantine_grow() must free a slot if it fails to grow. */
     assert(quarantine->curobjs < (ZU(1) << quarantine->lg_maxobjs));
     /* Append ptr if its size doesn't exceed the quarantine size. */
     if (quarantine->curbytes + usize <= opt_quarantine) {
         size_t offset = (quarantine->first + quarantine->curobjs) &
             ((ZU(1) << quarantine->lg_maxobjs) - 1);
         quarantine_obj_t *obj = &quarantine->objs[offset];
         obj->ptr = ptr;
         obj->usize = usize;
         quarantine->curbytes += usize;
         quarantine->curobjs++;
         if (config_fill && opt_junk) {
             /*
              * Only do redzone validation if Valgrind isn't in
              * operation.
              */
             if ((config_valgrind == false || opt_valgrind == false)
                 && usize <= SMALL_MAXCLASS)
                 arena_quarantine_junk_small(ptr, usize);
             else
                 memset(ptr, 0x5a, usize);
         }
     } else {
         assert(quarantine->curbytes == 0);
         idalloc(ptr);
     }
 }
References assert(), cassert(), config_fill, config_prof, config_valgrind, idalloc(), isalloc(), memset, opt_junk, opt_quarantine, opt_valgrind, ptr(), quarantine_drain(), quarantine_grow(), QUARANTINE_STATE_MAX, QUARANTINE_STATE_PURGATORY, QUARANTINE_STATE_REINCARNATED, and ZU.
Referenced by iqalloct(), quarantine_cleanup(), quarantine_drain(), quarantine_drain_one(), and quarantine_grow().
quarantine_boot()
bool quarantine_boot (void)
Definition at line 190 of file quarantine.c.
 {
     cassert(config_fill);
     if (quarantine_tsd_boot())
         return (true);
     return (false);
 }
References cassert(), and config_fill.
quarantine_cleanup()
void quarantine_cleanup (void * arg)
Definition at line 162 of file quarantine.c.
 {
     quarantine_t *quarantine = *(quarantine_t **)arg;
     if (quarantine == QUARANTINE_STATE_REINCARNATED) {
         /*
          * Another destructor deallocated memory after this destructor
          * was called.  Reset quarantine to QUARANTINE_STATE_PURGATORY
          * in order to receive another callback.
          */
         quarantine = QUARANTINE_STATE_PURGATORY;
         quarantine_tsd_set(&quarantine);
     } else if (quarantine == QUARANTINE_STATE_PURGATORY) {
         /*
          * The previous time this destructor was called, we set the key
          * to QUARANTINE_STATE_PURGATORY so that other destructors
          * wouldn't cause re-creation of the quarantine.  This time, do
          * nothing, so that the destructor will not be called again.
          */
     } else if (quarantine != NULL) {
         quarantine_drain(quarantine, 0);
         idalloc(quarantine);
         quarantine = QUARANTINE_STATE_PURGATORY;
         quarantine_tsd_set(&quarantine);
     }
 }
References arg(), idalloc(), NULL, quarantine(), quarantine_drain(), QUARANTINE_STATE_PURGATORY, and QUARANTINE_STATE_REINCARNATED.
quarantine_drain()
static void quarantine_drain (quarantine_t * quarantine, size_t upper_bound) static
Definition at line 92 of file quarantine.c.
 {
     while (quarantine->curbytes > upper_bound && quarantine->curobjs > 0)
         quarantine_drain_one(quarantine);
 }
References quarantine(), and quarantine_drain_one().
Referenced by quarantine(), and quarantine_cleanup().
quarantine_drain_one()
static void quarantine_drain_one (quarantine_t * quarantine) static
Definition at line 80 of file quarantine.c.
 {
     quarantine_obj_t *obj = &quarantine->objs[quarantine->first];
     assert(obj->usize == isalloc(obj->ptr, config_prof));
     idalloc(obj->ptr);
     quarantine->curbytes -= obj->usize;
     quarantine->curobjs--;
     quarantine->first = (quarantine->first + 1) & ((ZU(1) <<
         quarantine->lg_maxobjs) - 1);
 }
References assert(), config_prof, idalloc(), isalloc(), quarantine(), and ZU.
Referenced by quarantine_drain(), and quarantine_grow().
quarantine_grow()
static quarantine_t* quarantine_grow (quarantine_t * quarantine) static
Definition at line 46 of file quarantine.c.
 {
     quarantine_t *ret;
     ret = quarantine_init(quarantine->lg_maxobjs + 1);
     if (ret == NULL) {
         quarantine_drain_one(quarantine);
         return (quarantine);
     }
     ret->curbytes = quarantine->curbytes;
     ret->curobjs = quarantine->curobjs;
     if (quarantine->first + quarantine->curobjs <= (ZU(1) <<
         quarantine->lg_maxobjs)) {
         /* objs ring buffer data are contiguous. */
         memcpy(ret->objs, &quarantine->objs[quarantine->first],
             quarantine->curobjs * sizeof(quarantine_obj_t));
     } else {
         /* objs ring buffer data wrap around. */
         size_t ncopy_a = (ZU(1) << quarantine->lg_maxobjs) -
             quarantine->first;
         size_t ncopy_b = quarantine->curobjs - ncopy_a;
         memcpy(ret->objs, &quarantine->objs[quarantine->first], ncopy_a
             * sizeof(quarantine_obj_t));
         memcpy(&ret->objs[ncopy_a], quarantine->objs, ncopy_b *
             sizeof(quarantine_obj_t));
     }
     idalloc(quarantine);
     return (ret);
 }
References idalloc(), memcpy, NULL, quarantine(), quarantine_drain_one(), ret, and ZU.
Referenced by quarantine().