Azerotcore-wotlk: deps/recastnavigation/Recast/Include/RecastAlloc.h File Reference
RecastAlloc.h File Reference
#include <stddef.h>
#include <stdint.h>
#include <RecastAssert.h>
Classes
struct rcNewTag
class rcVectorBase< T, H >
class rcTempVector< T >
class rcPermVector< T >
class rcIntArray
Legacy class. Prefer rcVector<int>.
class rcScopedDelete< T >
Macros
#define RC_SIZE_MAX INTPTR_MAX
#define rcLikely(x) (x)
#define rcUnlikely(x) (x)
Typedefs
typedef void *() rcAllocFunc(size_t size, rcAllocHint hint)
A memory allocation function.
typedef void() rcFreeFunc(void *ptr)
typedef intptr_t rcSizeType
Enumerations
enum rcAllocHint { RC_ALLOC_PERM , RC_ALLOC_TEMP }
Functions
void rcAllocSetCustom (rcAllocFunc *allocFunc, rcFreeFunc *freeFunc)
void * rcAlloc (size_t size, rcAllocHint hint)
void rcFree (void *ptr)
void * operator new (size_t, const rcNewTag &, void *p)
void operator delete (void *, const rcNewTag &, void *)
Macro Definition Documentation
RC_SIZE_MAX
#define RC_SIZE_MAX INTPTR_MAX
Definition at line 74 of file RecastAlloc.h.
rcLikely
#define rcLikely (x) (x)
Macros to hint to the compiler about the likeliest branch. Please add a benchmark that demonstrates a performance improvement before introducing use cases.
Definition at line 82 of file RecastAlloc.h.
rcUnlikely
#define rcUnlikely (x) (x)
Definition at line 83 of file RecastAlloc.h.
Typedef Documentation
rcAllocFunc
typedef void*() rcAllocFunc(size_t size, rcAllocHint hint)
A memory allocation function.
See also
rcAllocSetCustom
Definition at line 40 of file RecastAlloc.h.
rcFreeFunc
typedef void() rcFreeFunc(void *ptr)
A memory deallocation function.
Parameters
[in] ptr A pointer to a memory block previously allocated using rcAllocFunc.
See also
rcAllocSetCustom
Definition at line 45 of file RecastAlloc.h.
rcSizeType
typedef intptr_t rcSizeType
Signed to avoid warnnings when comparing to int loop indexes, and common error with comparing to zero. MSVC2010 has a bug where ssize_t is unsigned (!!!).
Definition at line 73 of file RecastAlloc.h.
Enumeration Type Documentation
rcAllocHint
enum rcAllocHint
Provides hint values to the memory allocator on how long the memory is expected to be used.
Enumerator
RC_ALLOC_PERM
Memory will persist after a function call.
RC_ALLOC_TEMP
Memory used temporarily within a function.
Definition at line 29 of file RecastAlloc.h.
 {
     RC_ALLOC_PERM,
     RC_ALLOC_TEMP
 };
Function Documentation
operator delete()
void operator delete (void * , const rcNewTag & , void *) inline
Definition at line 69 of file RecastAlloc.h.
 {}
operator new()
void* operator new (size_t , const rcNewTag & , void * p) inline
Definition at line 68 of file RecastAlloc.h.
 { return p; }
rcAlloc()
void* rcAlloc (size_t size, rcAllocHint hint)
Allocates a memory block.
Parameters
[in] size The size, in bytes of memory, to allocate.
[in] hint A hint to the allocator on how long the memory is expected to be in use.
Returns
A pointer to the beginning of the allocated memory block, or null if the allocation failed.
See also
rcFree
rcAllocSetCustom
Definition at line 45 of file RecastAlloc.cpp.
 {
     return sRecastAllocFunc(size, hint);
 }
References sRecastAllocFunc.
Referenced by rcVectorBase< T, H >::allocate_and_copy(), allocSpan(), buildMeshAdjacency(), canRemoveVertex(), mergeContours(), mergeRegionHoles(), rcAllocPolyMeshDetail(), rcBuildCompactHeightfield(), rcBuildContours(), rcBuildDistanceField(), rcBuildHeightfieldLayers(), rcBuildLayerRegions(), rcBuildPolyMesh(), rcBuildPolyMeshDetail(), rcBuildRegions(), rcBuildRegionsMonotone(), rcCopyPolyMesh(), rcCreateHeightfield(), rcErodeWalkableArea(), rcMedianFilterWalkableArea(), rcMergePolyMeshDetails(), rcMergePolyMeshes(), anonymous_namespace{Recast.cpp}::rcNew(), and removeVertex().
rcAllocSetCustom()
void rcAllocSetCustom (rcAllocFunc * allocFunc, rcFreeFunc * freeFunc)
Sets the base custom allocation functions to be used by Recast.
Parameters
[in] allocFunc The memory allocation function to be used by rcAlloc
[in] freeFunc The memory de-allocation function to be used by rcFree
See also
rcAlloc, rcFree
Definition at line 38 of file RecastAlloc.cpp.
 {
     sRecastAllocFunc = allocFunc ? allocFunc : rcAllocDefault;
     sRecastFreeFunc = freeFunc ? freeFunc : rcFreeDefault;
 }
References rcAllocDefault(), rcFreeDefault(), sRecastAllocFunc, and sRecastFreeFunc.
rcFree()
void rcFree (void * ptr)
Deallocates a memory block.
Parameters
[in] ptr A pointer to a memory block previously allocated using rcAlloc.
See also
rcAlloc
Warning
This function leaves the value of ptr unchanged. So it still points to the same (now invalid) location, and not to null.
See also
rcAllocSetCustom
Definition at line 56 of file RecastAlloc.cpp.
 {
     if (ptr)
         sRecastFreeFunc(ptr);
 }
References ptr(), and sRecastFreeFunc.
Referenced by buildMeshAdjacency(), mergeContours(), rcVectorBase< T, H >::push_back(), rcBuildContours(), rcBuildDistanceField(), rcBuildPolyMeshDetail(), anonymous_namespace{Recast.cpp}::rcDelete(), rcErodeWalkableArea(), rcFreePolyMeshDetail(), rcMedianFilterWalkableArea(), rcVectorBase< T, H >::reserve(), rcVectorBase< T, H >::resize_impl(), rcCompactHeightfield::~rcCompactHeightfield(), rcContourSet::~rcContourSet(), rcHeightfield::~rcHeightfield(), rcHeightfieldLayerSet::~rcHeightfieldLayerSet(), rcHeightPatch::~rcHeightPatch(), rcPolyMesh::~rcPolyMesh(), rcScopedDelete< T >::~rcScopedDelete(), and rcVectorBase< T, H >::~rcVectorBase().