Azerotcore-wotlk: UnitAI Class Reference
UnitAI Class Reference abstract
#include <UnitAI.h>
Public Member Functions
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void UpdateAI (uint32)=0
virtual void InitializeAI ()
virtual void Reset ()
virtual void OnCharmed (bool apply)=0
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Static Public Member Functions
static void FillAISpellInfo ()
Static Public Attributes
static AISpellInfoType * AISpellInfo
Protected Attributes
Unit *const me
Detailed Description
Definition at line 176 of file UnitAI.h.
Constructor & Destructor Documentation
UnitAI()
UnitAI::UnitAI (Unit * unit) inline explicit
Definition at line 181 of file UnitAI.h.
 : me(unit) {}
~UnitAI()
virtual UnitAI::~UnitAI () inline virtual
Definition at line 182 of file UnitAI.h.
 {}
Member Function Documentation
AttackStart()
void UnitAI::AttackStart (Unit * victim) virtual
Reimplemented in npc_pet_gen_gnomish_flame_turret, npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI, exarch_orelis::exarch_orelisAI, boss_kaelthas::boss_kaelthasAI, boss_high_astromancer_solarian::boss_high_astromancer_solarianAI, npc_millhouse_manastorm::npc_millhouse_manastormAI, boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI, boss_nazan::boss_nazanAI, boss_krosh_firehand::boss_krosh_firehandAI, boss_olm_the_summoner::boss_olm_the_summonerAI, boss_the_lurker_below::boss_the_lurker_belowAI, boss_leotheras_the_blind::boss_leotheras_the_blindAI, boss_lady_malande::boss_lady_malandeAI, boss_high_nethermancer_zerevor::boss_high_nethermancer_zerevorAI, boss_ambassador_hellmaw::boss_ambassador_hellmawAI, npc_ravenous_worg::npc_ravenous_worgAI, npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI, violet_hold_trashAI, boss_toravon::boss_toravonAI, boss_koralon::boss_koralonAI, boss_emalon::boss_emalonAI, boss_archavon::boss_archavonAI, boss_keleseth::boss_kelesethAI, npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI, boss_razorscale::boss_razorscaleAI, npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI, boss_mimiron::boss_mimironAI, boss_kologarn::boss_kologarnAI, npc_ulduar_hodir_mage::npc_ulduar_hodir_mageAI, npc_ulduar_hodir_shaman::npc_ulduar_hodir_shamanAI, npc_ulduar_hodir_druid::npc_ulduar_hodir_druidAI, npc_ulduar_hodir_priest::npc_ulduar_hodir_priestAI, boss_flame_leviathan::boss_flame_leviathanAI, boss_algalon_the_observer::boss_algalon_the_observerAI, npc_hol_monument::npc_hol_monumentAI, boss_urom::boss_uromAI, boss_magus_telestra::boss_magus_telestraAI, boss_kelthuzad_minion::boss_kelthuzad_minionAI, boss_four_horsemen::boss_four_horsemenAI, npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI, npc_icc_skybreaker_luminary::npc_icc_skybreaker_luminaryAI, npc_icc_skybreaker_vicar::npc_icc_skybreaker_vicarAI, npc_icc_skybreaker_marksman::npc_icc_skybreaker_marksmanAI, npc_icc_skybreaker_hierophant::npc_icc_skybreaker_hierophantAI, npc_suppresser::npc_suppresserAI, npc_raging_spirit::npc_raging_spiritAI, boss_professor_putricide::boss_professor_putricideAI, npc_vengeful_shade::npc_vengeful_shadeAI, npc_ball_of_flame::npc_ball_of_flameAI, npc_dark_nucleus::npc_dark_nucleusAI, boss_prince_keleseth_icc::boss_prince_kelesethAI, npc_living_mojo::npc_living_mojoAI, npc_tortured_rifleman::npc_tortured_riflemanAI, npc_spectral_footman::npc_spectral_footmanAI, npc_shadowy_mercenary::npc_shadowy_mercenaryAI, npc_phantom_mage::npc_phantom_mageAI, npc_ghostly_priest::npc_ghostly_priestAI, boss_icehowl::boss_icehowlAI, boss_jormungarAI, npc_snobold_vassal::npc_snobold_vassalAI, boss_faction_championsAI, boss_halion::boss_halionAI, npc_twilight_volunteer::npc_twilight_volunteerAI, npc_zelfrax::npc_zelfraxAI, npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI, boss_veklor::boss_veklorAI, boss_zuljin::boss_zuljinAI, boss_nalorakk::boss_nalorakkAI, boss_slither::boss_slitherAI, boss_gazakrothAI, boss_alyson_antille::boss_alyson_antilleAI, npc_halazzi_lynx::npc_halazzi_lynxAI, boss_halazzi::boss_halazziAI, npc_daphne_stilwell::npc_daphne_stilwellAI, boss_kiljaeden::boss_kiljaedenAI, boss_brutallus::boss_brutallusAI, npc_koltira_deathweaver::npc_koltira_deathweaverAI, boss_julianne::boss_julianneAI, boss_roar::boss_roarAI, boss_tinhead::boss_tinheadAI, boss_strawman::boss_strawmanAI, boss_dorothee::boss_dorotheeAI, boss_nightbane::boss_nightbaneAI, SmartAI, npc_escortAI, TurretAI, ArcherAI, boss_illidan_stormrage::boss_illidan_stormrageAI, npc_nexus_lord::npc_nexus_lordAI, boss_malygos::boss_malygosAI, npc_frostwing_vrykul::npc_frostwing_vrykulAI, boss_sister_svalna::boss_sister_svalnaAI, boss_lady_deathwhisper::boss_lady_deathwhisperAI, npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI, npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, npc_shadowpriest_sezziz::npc_shadowpriest_sezzizAI, npc_weegli_blastfuse::npc_weegli_blastfuseAI, npc_hive_zara_larva::npc_hive_zara_larvaAI, boss_priestess_lackey_commonAI, TotemAI, CasterAI, npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI, npc_gunship_gunner::npc_gunship_gunnerAI, npc_gunship_mage::npc_gunship_mageAI, boss_ragnaros::boss_ragnarosAI, PetAI, PossessedAI, npc_ritual_channeler::npc_ritual_channelerAI, npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI, npc_warden_mellichar::npc_warden_mellicharAI, boss_vazruden_the_herald::boss_vazruden_the_heraldAI, boss_illidari_council::boss_illidari_councilAI, boss_reliquary_of_souls::boss_reliquary_of_soulsAI, npc_icefang::npc_icefangAI, npc_wild_wyrm::npc_wild_wyrmAI, npc_frosthound::npc_frosthoundAI, npc_mageguard_dalaran::npc_mageguard_dalaranAI, npc_warmage_coldarra::npc_warmage_coldarraAI, npc_ichor_globule::npc_ichor_globuleAI, boss_yoggsaron::boss_yoggsaronAI, boss_yoggsaron_cloud::boss_yoggsaron_cloudAI, boss_yoggsaron_sara::boss_yoggsaron_saraAI, npc_xt002_heart::npc_xt002_heartAI, boss_thorim_sif_blizzard::boss_thorim_sif_blizzardAI, boss_thorim_lightning_orb::boss_thorim_lightning_orbAI, boss_thorim_sif::boss_thorim_sifAI, npc_ulduar_emergency_fire_bot::npc_ulduar_emergency_fire_botAI, npc_ulduar_proximity_mine::npc_ulduar_proximity_mineAI, npc_ulduar_vx001::npc_ulduar_vx001AI, boss_kologarn_arms::boss_kologarn_armsAI, npc_mimirons_inferno::npc_mimirons_infernoAI, boss_flame_leviathan_seat::boss_flame_leviathan_seatAI, npc_assembly_lightning::npc_assembly_lightningAI, npc_spark_of_ionar::npc_spark_of_ionarAI, npc_oculus_unstable_sphere::npc_oculus_unstable_sphereAI, npc_alexstrasza::npc_alexstraszaAI, npc_hover_disk::npc_hover_diskAI, npc_scion_of_eternity::npc_scion_of_eternityAI, npc_vortex_ride::npc_vortex_rideAI, npc_valithria_cloud::npc_valithria_cloudAI, npc_the_lich_king_controller::npc_the_lich_king_controllerAI, boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI, npc_pos_leader::npc_pos_leaderAI, npc_toc5_player_vehicle::npc_toc5_player_vehicleAI, npc_amanitar_mushrooms::npc_amanitar_mushroomsAI, npc_depth_charge::npc_depth_chargeAI, npc_medivh_bm::npc_medivh_bmAI, npc_taretha::npc_tarethaAI, npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI, boss_headless_horseman_pumpkin::boss_headless_horseman_pumpkinAI, npc_brewfest_super_brew_trigger::npc_brewfest_super_brew_triggerAI, npc_dark_iron_guzzler::npc_dark_iron_guzzlerAI, npc_dark_iron_attack_mole_machine::npc_dark_iron_attack_mole_machineAI, npc_janalai_hatcher::npc_janalai_hatcherAI, npc_janalai_firebomb::npc_janalai_firebombAI, npc_demon_chain::npc_demon_chainAI, FollowerAI, ScriptedAI, NullCreatureAI, PassiveAI, VehicleAI, and NPCStaveQuestAI.
Definition at line 28 of file UnitAI.cpp.
 {
     if (victim && me->Attack(victim, true))
         me->GetMotionMaster()->MoveChase(victim);
 }
References Unit::Attack(), Unit::GetMotionMaster(), me, and MotionMaster::MoveChase().
Referenced by ScriptedAI::AttackStart(), boss_faction_championsAI::AttackStart(), npc_ravenous_worg::npc_ravenous_worgAI::AttackStart(), npc_anubisath_sentinel::aqsentinelAI::CallBuddiesToAttack(), boss_veknilash::boss_veknilashAI::CastSpellOnBug(), Unit::CombatStart(), npc_boss_gothik_minion::npc_boss_gothik_minionAI::DamageTaken(), Spell::DoAllEffectOnTarget(), instance_stratholme::instance_stratholme_InstanceMapScript::DoSpawnPlaguedCritters(), instance_mechanar::instance_mechanar_InstanceMapScript::DoSummonAction(), Spell::EffectTaunt(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::EnterCombat(), npc_beryl_sorcerer::npc_beryl_sorcererAI::EnterCombat(), boss_zuljin::boss_zuljinAI::EnterPhase(), AssistDelayEvent::Execute(), StartMovementEvent::Execute(), WorldSession::HandlePetActionHelper(), spell_the_lich_king_vile_spirit_move_target_search::spell_the_lich_king_vile_spirit_move_target_search_SpellScript::HandleScript(), spell_pursue::spell_pursue_SpellScript::HandleScript(), npc_toc_warlock::npc_toc_warlockAI::JustSummoned(), npc_toc_hunter::npc_toc_hunterAI::JustSummoned(), npc_toc_boomkin::npc_toc_boomkinAI::JustSummoned(), boss_maexxna::boss_maexxnaAI::JustSummoned(), npc_frosthound::npc_frosthoundAI::JustSummoned(), npc_eye_of_acherus::npc_eye_of_acherusAI::JustSummoned(), npc_daphne_stilwell::npc_daphne_stilwellAI::JustSummoned(), boss_skeram::boss_skeramAI::JustSummoned(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::JustSummoned(), boss_urom::boss_uromAI::JustSummoned(), boss_onyxia::boss_onyxiaAI::JustSummoned(), npc_hor_lich_king::npc_hor_lich_kingAI::JustSummoned(), WorldBossAI::JustSummoned(), npc_grimstone::npc_grimstoneAI::JustSummoned(), boss_gyth::boss_gythAI::JustSummoned(), boss_curator::boss_curatorAI::JustSummoned(), boss_sacrolash::boss_sacrolashAI::JustSummoned(), npc_demonic_vapor_trail::npc_demonic_vapor_trailAI::JustSummoned(), boss_halazzi::boss_halazziAI::JustSummoned(), boss_black_knight::boss_black_knightAI::JustSummoned(), boss_devourer_of_souls::boss_devourer_of_soulsAI::JustSummoned(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustSummoned(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustSummoned(), npc_precious_icc::npc_precious_iccAI::JustSummoned(), npc_the_lich_king_controller::npc_the_lich_king_controllerAI::JustSummoned(), npc_gluttonous_abomination::npc_gluttonous_abominationAI::JustSummoned(), boss_gluth::boss_gluthAI::JustSummoned(), boss_volkhan::boss_volkhanAI::JustSummoned(), boss_nexusprince_shaffar::boss_nexusprince_shaffarAI::JustSummoned(), boss_anzu::boss_anzuAI::JustSummoned(), npc_akama_illidan::npc_akama_illidanAI::JustSummoned(), npc_creature_generator_akama::npc_creature_generator_akamaAI::JustSummoned(), boss_the_black_stalker::boss_the_black_stalkerAI::JustSummoned(), boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI::JustSummoned(), boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI::JustSummoned(), npc_nelson::npc_nelsonAI::JustSummoned(), boss_balinda::boss_balindaAI::JustSummoned(), boss_nightbane::boss_nightbaneAI::JustSummoned(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::JustSummoned(), npc_professor_phizzlethorpe::npc_professor_phizzlethorpeAI::JustSummoned(), npc_thrall_bfu::npc_thrall_bfuAI::JustSummoned(), npc_tapoke_slim_jahn::npc_tapoke_slim_jahnAI::JustSummoned(), boss_archimonde::boss_archimondeAI::JustSummoned(), npc_muglash::npc_muglashAI::JustSummoned(), npc_kaya_flathoof::npc_kaya_flathoofAI::JustSummoned(), npc_wizzlecrank_shredder::npc_wizzlecrank_shredderAI::JustSummoned(), npc_ame::npc_ameAI::JustSummoned(), npc_emily::npc_emilyAI::JustSummoned(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::JustSummoned(), npc_wounded_blood_elf::npc_wounded_blood_elfAI::JustSummoned(), npc_maghar_captive::npc_maghar_captiveAI::JustSummoned(), npc_kurenai_captive::npc_kurenai_captiveAI::JustSummoned(), npc_bessy::npc_bessyAI::JustSummoned(), npc_earthmender_wilda::npc_earthmender_wildaAI::JustSummoned(), boss_ayamiss::boss_ayamissAI::JustSummoned(), npc_buru_egg::npc_buru_eggAI::JustSummoned(), CreatureGroup::MemberAttackStart(), CreatureAI::MoveInLineOfSight(), npc_air_force_bots::npc_air_force_botsAI::MoveInLineOfSight(), npc_pet_mage_mirror_image::MySelectNextTarget(), npc_salsalabim::OnGossipHello(), npc_raliq_the_drunk::OnGossipSelect(), npc_floon::OnGossipSelect(), npc_cooshcoosh::OnGossipSelect(), npc_ulduar_expedition_commander::OnGossipSelect(), npc_natrualist_bite::OnGossipSelect(), npc_bartleby::OnQuestAccept(), Acore::CallOfHelpCreatureInRangeDo::operator()(), Unit::PetSpellFail(), SmartScript::ProcessAction(), npc_heated_battle::npc_heated_battleAI::Reset(), Resurrect(), instance_naxxramas::instance_naxxramas_InstanceMapScript::SetBossState(), CreatureAI::SetGazeOn(), boss_cthun::cthunAI::SpawnEyeTentacle(), spell_putricide_ooze_channel::spell_putricide_ooze_channel_SpellScript::StartAttack(), brann_bronzebeard::brann_bronzebeardAI::SummonCreatures(), npc_artruis_the_hearthless::npc_artruis_the_hearthlessAI::SummonsAction(), boss_fankriss::boss_fankrissAI::SummonSpawn(), Unit::TauntApply(), Unit::TauntFadeOut(), Pet::Update(), SimpleCharmedAI::UpdateAI(), npc_rookery_hatcher::npc_rookery_hatcherAI::UpdateAI(), npc_death_knight_initiate::npc_death_knight_initiateAI::UpdateAI(), boss_akilzon::boss_akilzonAI::UpdateAI(), boss_hazzarah::boss_hazzarahAI::UpdateAI(), boss_jindo::boss_jindoAI::UpdateAI(), boss_marli::boss_marliAI::UpdateAI(), boss_eye_of_cthun::eye_of_cthunAI::UpdateAI(), boss_fankriss::boss_fankrissAI::UpdateAI(), npc_twiggy_flathead::npc_twiggy_flatheadAI::UpdateAI(), npc_freya_ward::npc_freya_wardAI::UpdateAI(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::UpdateAI(), npc_llod_generic::npc_llod_genericAI::UpdateAI(), socrethar::socretharAI::UpdateAI(), CreatureAI::UpdateVictim(), CreatureAI::UpdateVictimWithGaze(), and npc_cork_gizelton::npc_cork_gizeltonAI::WaypointReached().
AttackStartCaster()
void UnitAI::AttackStartCaster (Unit * victim, float dist)
Definition at line 34 of file UnitAI.cpp.
 {
     if (victim && me->Attack(victim, false))
         me->GetMotionMaster()->MoveChase(victim, dist);
 }
References Unit::Attack(), Unit::GetMotionMaster(), me, and MotionMaster::MoveChase().
Referenced by CasterAI::AttackStart(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::AttackStart(), npc_shadowpriest_sezziz::npc_shadowpriest_sezzizAI::AttackStart(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::AttackStart(), boss_faction_championsAI::AttackStart(), boss_prince_keleseth_icc::boss_prince_kelesethAI::AttackStart(), npc_icc_skybreaker_hierophant::npc_icc_skybreaker_hierophantAI::AttackStart(), npc_icc_skybreaker_marksman::npc_icc_skybreaker_marksmanAI::AttackStart(), npc_icc_skybreaker_vicar::npc_icc_skybreaker_vicarAI::AttackStart(), npc_icc_skybreaker_luminary::npc_icc_skybreaker_luminaryAI::AttackStart(), npc_ulduar_hodir_priest::npc_ulduar_hodir_priestAI::AttackStart(), npc_ulduar_hodir_druid::npc_ulduar_hodir_druidAI::AttackStart(), npc_ulduar_hodir_shaman::npc_ulduar_hodir_shamanAI::AttackStart(), npc_ulduar_hodir_mage::npc_ulduar_hodir_mageAI::AttackStart(), and boss_keleseth::boss_kelesethAI::AttackStart().
CanAIAttack()
virtual bool UnitAI::CanAIAttack (Unit const *) const inline virtual
Reimplemented in boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI, npc_lady_sylvanas_windrunner_bfu::npc_lady_sylvanas_windrunner_bfuAI, npc_thrall_bfu::npc_thrall_bfuAI, npc_icc_spire_frostwyrm::npc_icc_spire_frostwyrmAI, npc_icc_severed_essence::npc_icc_severed_essenceAI, npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI, npc_frostwing_vrykul::npc_frostwing_vrykulAI, npc_argent_captainAI, npc_crok_scourgebane::npc_crok_scourgebaneAI, npc_risen_archmage::npc_risen_archmageAI, npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI, npc_lk_wicked_spirit::npc_lk_wicked_spiritAI, npc_icc_lk_checktarget::npc_icc_lk_checktargetAI, npc_terenas_menethil::npc_terenas_menethilAI, npc_raging_spirit::npc_raging_spiritAI, npc_shambling_horror_icc::npc_shambling_horror_iccAI, npc_tirion_fordring_tft::npc_tirion_fordringAI, boss_the_lich_king::boss_the_lich_kingAI, boss_lord_marrowgar, boss_sathrovarr::boss_sathrovarrAI, boss_kalecgos::boss_kalecgosAI, boss_majordomo::boss_majordomoAI, npc_inner_demon::npc_inner_demonAI, npc_mindless_ghoul::npc_mindless_ghoulAI, npc_pos_freed_slave::npc_pos_freed_slaveAI, boss_tyrannus::boss_tyrannusAI, boss_halion::boss_halionAI, boss_selin_fireheart::boss_selin_fireheartAI, SmartAI, TurretAI, boss_illidan_stormrage::boss_illidan_stormrageAI, npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI, boss_thorim_arena_npcs::boss_thorim_arena_npcsAI, npc_ulduar_dark_rune_sentinel::npc_ulduar_dark_rune_sentinelAI, npc_ulduar_dark_rune_watcher::npc_ulduar_dark_rune_watcherAI, npc_ulduar_dark_rune_guardian::npc_ulduar_dark_rune_guardianAI, boss_sindragosa::boss_sindragosaAI, boss_professor_putricide::boss_professor_putricideAI, npc_gunship_gunner::npc_gunship_gunnerAI, npc_gunship_boarding_addAI, npc_igb_ship_crew::npc_igb_ship_crewAI, npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI, npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI, boss_devourer_of_souls::boss_devourer_of_soulsAI, npc_nerubian_burrower::npc_nerubian_burrowerAI, npc_swarm_scarab::npc_swarm_scarabAI, boss_anubarak_trial::boss_anubarak_trialAI, npc_ulduar_hodir_mage::npc_ulduar_hodir_mageAI, npc_ulduar_hodir_shaman::npc_ulduar_hodir_shamanAI, npc_ulduar_hodir_druid::npc_ulduar_hodir_druidAI, npc_ulduar_hodir_priest::npc_ulduar_hodir_priestAI, boss_hodir::boss_hodirAI, npc_ulduar_proximity_mine::npc_ulduar_proximity_mineAI, npc_gunship_rocketeer::npc_gunship_rocketeerAI, npc_gunship_mage::npc_gunship_mageAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI, boss_ick::boss_ickAI, and boss_victor_nefarius::boss_victor_nefariusAI.
Definition at line 184 of file UnitAI.h.
 { return true; }
Referenced by npc_escortAI::AssistPlayerInCombat().
DamageDealt()
virtual void UnitAI::DamageDealt (Unit * , uint32 & , DamageEffectType) inline virtual
Reimplemented in npc_ball_of_flame::npc_ball_of_flameAI, boss_prince_valanar_icc::boss_prince_valanarAI, boss_prince_taldaram_icc::boss_prince_taldaramAI, boss_prince_keleseth_icc::boss_prince_kelesethAI, boss_janalai::boss_janalaiAI, SmartAI, and boss_kologarn_eyebeam::boss_kologarn_eyebeamAI.
Definition at line 281 of file UnitAI.h.
 { }
Referenced by Unit::DealDamage().
DamageTaken()
virtual void UnitAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline virtual
Reimplemented in npc_inner_demon::npc_inner_demonAI, npc_wild_wyrm::npc_wild_wyrmAI, boss_yoggsaron_brain::boss_yoggsaron_brainAI, boss_yoggsaron_sara::boss_yoggsaron_saraAI, boss_thorim::boss_thorimAI, boss_kologarn_arms::boss_kologarn_armsAI, boss_kologarn::boss_kologarnAI, boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI, boss_razuvious::boss_razuviousAI, boss_mal_ganis::boss_mal_ganisAI, boss_sathrovarr::boss_sathrovarrAI, boss_kalec::boss_kalecAI, boss_brutallus::boss_brutallusAI, npc_infra_green_bomber_generic::npc_infra_green_bomber_genericAI, npc_heated_battle::npc_heated_battleAI, boss_thorim_start_npcs::boss_thorim_start_npcsAI, boss_yoggsaron_crusher_tentacle::boss_yoggsaron_crusher_tentacleAI, npc_calvin_montague::npc_calvin_montagueAI, npc_bartleby::npc_bartlebyAI, npc_ulduar_flash_freeze::npc_ulduar_flash_freezeAI, npc_rotting_forest_rager::npc_rotting_forest_ragerAI, npc_infested_root_walker::npc_infested_root_walkerAI, npc_unkor_the_ruthless::npc_unkor_the_ruthlessAI, npc_salsalabim::npc_salsalabimAI, hyjal_trashAI, netherspite_infernal::netherspite_infernalAI, SmartAI, npc_warden_mellichar::npc_warden_mellicharAI, npc_ulduar_iron_construct::npc_ulduar_iron_constructAI, npc_boss_gothik_minion::npc_boss_gothik_minionAI, boss_the_lich_king::boss_the_lich_kingAI, boss_prince_valanar_icc::boss_prince_valanarAI, boss_prince_taldaram_icc::boss_prince_taldaramAI, boss_prince_keleseth_icc::boss_prince_kelesethAI, boss_twilight_halion::boss_twilight_halionAI, boss_halion::boss_halionAI, npc_tiger_matriarch::npc_tiger_matriarchAI, boss_kalecgos::boss_kalecgosAI, npc_death_knight_initiate::npc_death_knight_initiateAI, npc_garr_firesworn::npc_garr_fireswornAI, npc_centrifuge_construct::npc_centrifuge_constructAI, boss_viscidus::boss_viscidusAI, npc_dark_nucleus::npc_dark_nucleusAI, npc_molten_golem::npc_molten_golemAI, npc_tapoke_slim_jahn::npc_tapoke_slim_jahnAI, npc_blistering_zombie::npc_blistering_zombieAI, npc_ice_tomb::npc_ice_tombAI, npc_hor_leader_second::npc_hor_leader_secondAI, npc_training_dummy::npc_training_dummyAI, boss_alar::boss_alarAI, boss_essence_of_desire::boss_essence_of_desireAI, boss_essence_of_suffering::boss_essence_of_sufferingAI, npc_akama_illidan::npc_akama_illidanAI, boss_illidan_stormrage::boss_illidan_stormrageAI, npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI, npc_still_at_it_trigger::npc_still_at_it_triggerAI, npc_tournament_training_dummy::npc_tournament_training_dummyAI, npc_vrykul_skeleton::npc_vrykul_skeletonAI, boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI, npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI, boss_yoggsaron_immortal_guardian::boss_yoggsaron_immortal_guardianAI, npc_xt002_boombot::npc_xt002_boombotAI, npc_xt002_heart::npc_xt002_heartAI, boss_razorscale::boss_razorscaleAI, npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI, npc_ulduar_vx001::npc_ulduar_vx001AI, npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI, boss_hodir::boss_hodirAI, boss_freya::boss_freyaAI, npc_pool_of_tar::npc_pool_of_tarAI, npc_collapsing_star::npc_collapsing_starAI, boss_algalon_the_observer::boss_algalon_the_observerAI, brann_bronzebeard::brann_bronzebeardAI, npc_spark_of_ionar::npc_spark_of_ionarAI, npc_crystalline_frayer::npc_crystalline_frayerAI, npc_power_spark::npc_power_sparkAI, npc_vortex_ride::npc_vortex_rideAI, boss_malygos::boss_malygosAI, npc_tesla::npc_teslaAI, boss_gothik::boss_gothikAI, npc_crok_scourgebane::npc_crok_scourgebaneAI, boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI, npc_terenas_menethil::npc_terenas_menethilAI, npc_valkyr_shadowguard::npc_valkyr_shadowguardAI, npc_shambling_horror_icc::npc_shambling_horror_iccAI, boss_sindragosa::boss_sindragosaAI, boss_lady_deathwhisper::boss_lady_deathwhisperAI, npc_gunship_boarding_addAI, npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI, npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI, npc_gunship::npc_gunshipAI, boss_drakkari_colossus::boss_drakkari_colossusAI, npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI, boss_ick::boss_ickAI, boss_bronjahm::boss_bronjahmAI, npc_anubarak_spike::npc_anubarak_spikeAI, npc_frost_sphere::npc_frost_sphereAI, npc_announcer_toc5::npc_announcer_toc5AI, boss_grand_champion::boss_grand_championAI, boss_black_knight::boss_black_knightAI, npc_argent_soldier::npc_argent_soldierAI, boss_paletress::boss_paletressAI, boss_eadric::boss_eadricAI, boss_sartharion::boss_sartharionAI, boss_taldaram::boss_taldaramAI, boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI, boss_volazj::boss_volazjAI, boss_elder_nadox::boss_elder_nadoxAI, npc_amanitar_mushrooms::npc_amanitar_mushroomsAI, boss_twinemperorsAI, boss_cthun::cthunAI, boss_eye_of_cthun::eye_of_cthunAI, npc_doomfire_targetting::npc_doomfire_targettingAI, npc_doomfire::npc_doomfireAI, npc_ancient_wisp::npc_ancient_wispAI, npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI, boss_headless_horseman_head::boss_headless_horseman_headAI, boss_headless_horseman::boss_headless_horsemanAI, npc_coren_direbrew::npc_coren_direbrewAI, npc_dark_iron_guzzler::npc_dark_iron_guzzlerAI, npc_halazzi_lynx::npc_halazzi_lynxAI, boss_halazzi::boss_halazziAI, npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI, boss_muru::boss_muruAI, boss_kiljaeden::boss_kiljaedenAI, boss_high_inquisitor_whitemane::boss_high_inquisitor_whitemaneAI, npc_mograine::npc_mograineAI, boss_felblood_kaelthas::boss_felblood_kaelthasAI, boss_romulo::boss_romuloAI, boss_julianne::boss_julianneAI, boss_shade_of_aran::boss_aranAI, npc_mc_core_hound::npc_mc_core_houndAI, boss_majordomo::boss_majordomoAI, npc_core_rager::npc_core_ragerAI, boss_golemagg::boss_golemaggAI, boss_baron_geddon::boss_baron_geddonAI, boss_razorgore::boss_razorgoreAI, boss_warmaster_voone::boss_warmastervooneAI, boss_quartermaster_zigris, npc_blackhand_incarcerator::npc_blackhand_incarceratorAI, boss_gyth::boss_gythAI, boss_freya_elder_stonebark::boss_freya_elder_stonebarkAI, boss_taerar::boss_taerarAI, boss_emeriss::boss_emerissAI, boss_lethon::boss_lethonAI, boss_ysondre::boss_ysondreAI, socrethar::socretharAI, boss_yoggsaron_influence_tentacle::boss_yoggsaron_influence_tentacleAI, boss_eregos::boss_eregosAI, boss_professor_putricide::boss_professor_putricideAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_garfrost::boss_garfrostAI, boss_moam::boss_moamAI, boss_kurinnaxx::boss_kurinnaxxAI, boss_onyxia::boss_onyxiaAI, boss_venoxis::boss_venoxisAI, boss_jeklik::boss_jeklikAI, ScriptedAI, and CritterAI.
Definition at line 286 of file UnitAI.h.
 {}
Referenced by Unit::DealDamage().
DoAction()
virtual void UnitAI::DoAction (int32) inline virtual
Reimplemented in npc_spring_rabbit::npc_spring_rabbitAI, boss_pathaleon_the_calculator::boss_pathaleon_the_calculatorAI, npc_rocket_propelled_warhead::npc_rocket_propelled_warheadAI, npc_sergeant_bly::npc_sergeant_blyAI, npc_taretha::npc_tarethaAI, npc_brew_bubble::npc_brew_bubbleAI, npc_scarlet_miner_cart::npc_scarlet_miner_cartAI, npc_stolen_soul::npc_stolen_soulAI, SmartAI, npc_riggle_bassbait::npc_riggle_bassbaitAI, npc_elder_clearwater::npc_elder_clearwaterAI, npc_pet_gen_argent_pony_bridle, socrethar::socretharAI, exarch_orelis::exarch_orelisAI, anchorite_karja::anchorite_karjaAI, adyen_the_lightbringer::adyen_the_lightbringerAI, boss_nazan::boss_nazanAI, boss_kelidan_the_breaker::boss_kelidan_the_breakerAI, npc_naga_distiller::npc_naga_distillerAI, boss_the_lurker_below::boss_the_lurker_belowAI, boss_illidari_council_memberAI, boss_illidari_council::boss_illidari_councilAI, npc_creature_generator_akama::npc_creature_generator_akamaAI, npc_akama_shade::npc_akamaAI, boss_shade_of_akama::boss_shade_of_akamaAI, boss_essence_of_anger::boss_essence_of_angerAI, boss_essence_of_desire::boss_essence_of_desireAI, boss_essence_of_suffering::boss_essence_of_sufferingAI, boss_reliquary_of_souls::boss_reliquary_of_soulsAI, npc_akama_illidan::npc_akama_illidanAI, boss_illidan_stormrage::boss_illidan_stormrageAI, boss_ambassador_hellmaw::boss_ambassador_hellmawAI, npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI, boss_ichoron::boss_ichoronAI, boss_skadi_grauf::boss_skadi_graufAI, boss_skadi::boss_skadiAI, npc_frenzied_worgen::npc_frenzied_worgenAI, npc_ravenous_furbolg::npc_ravenous_furbolgAI, npc_ferocious_rhino::npc_ferocious_rhinoAI, npc_massive_jormungar::npc_massive_jormungarAI, boss_palehoof::boss_palehoofAI, boss_dalronn_the_controller::boss_dalronn_the_controllerAI, boss_skarvald_the_constructor::boss_skarvald_the_constructorAI, boss_yoggsaron_keeper::boss_yoggsaron_keeperAI, boss_yoggsaron_constrictor_tentacle::boss_yoggsaron_constrictor_tentacleAI, boss_yoggsaron_corruptor_tentacle::boss_yoggsaron_corruptor_tentacleAI, boss_yoggsaron_crusher_tentacle::boss_yoggsaron_crusher_tentacleAI, boss_yoggsaron_brain::boss_yoggsaron_brainAI, boss_yoggsaron::boss_yoggsaronAI, boss_yoggsaron_cloud::boss_yoggsaron_cloudAI, boss_yoggsaron_sara::boss_yoggsaron_saraAI, npc_xt002_heart::npc_xt002_heartAI, boss_xt002::boss_xt002AI, boss_thorim_ancient_rune_giant::boss_thorim_ancient_rune_giantAI, boss_thorim_sif::boss_thorim_sifAI, boss_thorim::boss_thorimAI, npc_ulduar_bot_summon_trigger::npc_ulduar_bot_summon_triggerAI, npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI, boss_kologarn::boss_kologarnAI, boss_vezax::boss_vezaxAI, boss_freya_summons::boss_freya_summonsAI, boss_freya::boss_freyaAI, npc_mimirons_inferno::npc_mimirons_infernoAI, npc_freya_ward::npc_freya_wardAI, npc_auriaya_feral_defender::npc_auriaya_feral_defenderAI, boss_auriaya::boss_auriayaAI, boss_steelbreaker::boss_steelbreakerAI, boss_sjonnir::boss_sjonnirAI, npc_molten_golem::npc_molten_golemAI, boss_volkhan::boss_volkhanAI, npc_spark_of_ionar::npc_spark_of_ionarAI, npc_hover_disk::npc_hover_diskAI, npc_power_spark::npc_power_sparkAI, boss_thaddius_summon::boss_thaddius_summonAI, boss_thaddius::boss_thaddiusAI, boss_sapphiron::boss_sapphironAI, boss_kelthuzad_minion::boss_kelthuzad_minionAI, npc_icc_putricades_trap::npc_icc_putricades_trapAI, npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI, npc_icc_blood_beast::npc_icc_blood_beastAI, npc_living_mojo::npc_living_mojoAI, boss_drakkari_elemental::boss_drakkari_elementalAI, boss_drakkari_colossus::boss_drakkari_colossusAI, boss_tyrannus::boss_tyrannusAI, boss_tharon_ja::boss_tharon_jaAI, npc_concentrated_ball::npc_concentrated_ballAI, boss_jormungarAI, boss_gormok::boss_gormokAI, npc_snobold_vassal::npc_snobold_vassalAI, npc_anubarak_spike::npc_anubarak_spikeAI, npc_swarm_scarab::npc_swarm_scarabAI, boss_anubarak_trial::boss_anubarak_trialAI, boss_grand_champion::boss_grand_championAI, npc_black_knight_skeletal_gryphon::npc_black_knight_skeletal_gryphonAI, boss_black_knight::boss_black_knightAI, boss_paletress::boss_paletressAI, npc_twilight_summon::npc_twilight_summonAI, boss_sartharion::boss_sartharionAI, npc_anub_ar_crusher::npc_anub_ar_crusherAI, boss_hadronox::boss_hadronoxAI, boss_cthun::cthunAI, boss_onyxia::boss_onyxiaAI, npc_medivh_bm::npc_medivh_bmAI, npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI, npc_cos_stratholme_citizien::npc_cos_stratholme_citizienAI, npc_arthas::npc_arthasAI, boss_infinite_corruptor::boss_infinite_corruptorAI, npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI, npc_love_in_air_hummel_helper::npc_love_in_air_hummel_helperAI, npc_love_in_air_hummel::npc_love_in_air_hummelAI, boss_headless_horseman::boss_headless_horsemanAI, npc_hallows_end_soh::npc_hallows_end_sohAI, npc_costumed_orphan_matron::npc_costumed_orphan_matronAI, npc_kalecgos_kj::npc_kalecgos_kjAI, boss_kiljaeden::boss_kiljaedenAI, boss_sathrovarr::boss_sathrovarrAI, boss_kalecgos::boss_kalecgosAI, boss_felmyst::boss_felmystAI, boss_alythess::boss_alythessAI, boss_sacrolash::boss_sacrolashAI, npc_madrigosa::npc_madrigosaAI, npc_highlord_darion_mograine::npc_highlord_darion_mograineAI, boss_ambassador_flamelash::boss_ambassador_flamelashAI, TotemAI, boss_sartharion_dragonAI, npc_pos_leader_second::npc_pos_leader_secondAI, npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI, boss_high_king_maulgar::boss_high_king_maulgarAI, npc_hor_leader_second::npc_hor_leader_secondAI, npc_hor_leader::npc_hor_leaderAI, npc_nelson::npc_nelsonAI, npc_artorius::npc_artoriusAI, npc_simon_bunny::npc_simon_bunnyAI, boss_broggok::boss_broggokAI, npc_ulduar_flames_initial::npc_ulduar_flames_initialAI, npc_ulduar_vx001::npc_ulduar_vx001AI, boss_flame_leviathan::boss_flame_leviathanAI, npc_living_constellation::npc_living_constellationAI, npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI, boss_algalon_the_observer::boss_algalon_the_observerAI, brann_bronzebeard::brann_bronzebeardAI, npc_ioc_gunship_captain::npc_ioc_gunship_captainAI, npc_argent_captainAI, boss_sister_svalna::boss_sister_svalnaAI, npc_crok_scourgebane::npc_crok_scourgebaneAI, npc_frost_freeze_trap::npc_frost_freeze_trapAI, npc_risen_archmage::npc_risen_archmageAI, npc_the_lich_king_controller::npc_the_lich_king_controllerAI, npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI, boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI, npc_terenas_menethil::npc_terenas_menethilAI, npc_strangulate_vehicle::npc_strangulate_vehicleAI, npc_tirion_fordring_tft::npc_tirion_fordringAI, boss_the_lich_king::boss_the_lich_kingAI, npc_rimefang::npc_rimefangAI, npc_spinestalker::npc_spinestalkerAI, boss_sindragosa::boss_sindragosaAI, npc_big_ooze::npc_big_oozeAI, boss_professor_putricide::boss_professor_putricideAI, npc_bone_spike::npc_bone_spikeAI, boss_lady_deathwhisper::boss_lady_deathwhisperAI, npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI, npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI, npc_saurfang_event::npc_saurfang_eventAI, npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI, npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI, npc_kinetic_bomb::npc_kinetic_bombAI, npc_ball_of_flame::npc_ball_of_flameAI, boss_prince_valanar_icc::boss_prince_valanarAI, boss_prince_taldaram_icc::boss_prince_taldaramAI, boss_prince_keleseth_icc::boss_prince_kelesethAI, npc_orb_carrier::npc_orb_carrierAI, npc_halion_controller::npc_halion_controllerAI, npc_xerestrasza::npc_xerestraszaAI, boss_baltharus_the_warborn::boss_baltharus_the_warbornAI, boss_taldaram::boss_taldaramAI, npc_taldaram_flamesphere::npc_taldaram_flamesphereAI, npc_twilight_volunteer::npc_twilight_volunteerAI, boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI, boss_ossirian::boss_ossirianAI, boss_moam::boss_moamAI, boss_buru::boss_buruAI, npc_direbrew_antagonist::npc_direbrew_antagonistAI, npc_coren_direbrew::npc_coren_direbrewAI, npc_eris_hevenfire::npc_eris_hevenfireAI, npc_dkc1_gothik::npc_dkc1_gothikAI, boss_ragnaros::boss_ragnarosAI, boss_majordomo::boss_majordomoAI, boss_razorgore::boss_razorgoreAI, npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI, npc_vh_void_sentry::npc_vh_void_sentryAI, npc_ulduar_toasty_fire::npc_ulduar_toasty_fireAI, npc_icc_spire_frostwyrm::npc_icc_spire_frostwyrmAI, npc_icc_severed_essence::npc_icc_severed_essenceAI, npc_icc_ice_sphere::npc_icc_ice_sphereAI, npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI, boss_krick::boss_krickAI, npc_hor_lich_king::npc_hor_lich_kingAI, npc_tortured_rifleman::npc_tortured_riflemanAI, npc_spectral_footman::npc_spectral_footmanAI, npc_shadowy_mercenary::npc_shadowy_mercenaryAI, npc_phantom_mage::npc_phantom_mageAI, npc_ghostly_priest::npc_ghostly_priestAI, boss_marwyn::boss_marwynAI, boss_falric::boss_falricAI, npc_fos_leader::npc_fos_leaderAI, boss_twin_valkyrAI, and npc_grand_magister_rommath::npc_grand_magister_rommathAI.
Definition at line 196 of file UnitAI.h.
 {}
Referenced by boss_algalon_the_observer::boss_algalon_the_observerAI::CallConstellations(), spell_the_lich_king_ice_burst_target_search::spell_the_lich_king_ice_burst_target_search_SpellScript::CheckTargetCount(), spell_algalon_big_bang::spell_algalon_big_bang_SpellScript::CheckTargets(), SummonList::DoAction(), boss_illidari_council::boss_illidari_councilAI::DoAction(), BattlegroundIC::HandleCapturedNodes(), spell_halion_twilight_division::spell_halion_twilight_division_SpellScript::HandleDummy(), spell_algalon_trigger_3_adds::spell_algalon_trigger_3_adds_SpellScript::HandleDummyEffect(), spell_egg_event::spell_egg_eventSpellScript::HandleOnHit(), spell_jedoga_sacrafice_beam::spell_jedoga_sacrafice_beam_AuraScript::HandleRemoval(), spell_kiljaeden_darkness::spell_kiljaeden_darkness_AuraScript::HandleRemove(), spell_taldaram_summon_flame_ball::spell_taldaram_summon_flame_ball_SpellScript::HandleScript(), spell_xt002_gravity_bomb_damage::spell_xt002_gravity_bomb_damage_SpellScript::HandleScript(), spell_the_lich_king_quake::spell_the_lich_king_quake_SpellScript::HandleSendEvent(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::InformCloud(), socrethar::socretharAI::JustDied(), boss_drakkari_colossus::boss_drakkari_colossusAI::JustSummoned(), npc_brew_bubble::npc_brew_bubbleAI::MoveInLineOfSight(), spell_pilgrims_bounty_serve_generic::spell_pilgrims_bounty_serve_generic_AuraScript::OnAuraRemove(), go_palehoof_sphere::OnGossipHello(), go_ossirian_crystal::OnGossipHello(), npc_pet_gen_argent_pony_bridle::OnGossipSelect(), boss_majordomo::OnGossipSelect(), npc_highlord_darion_mograine::OnGossipSelect(), npc_arthas::OnGossipSelect(), npc_high_overlord_saurfang_icc::OnGossipSelect(), npc_muradin_bronzebeard_icc::OnGossipSelect(), brann_bronzebeard::OnGossipSelect(), adyen_the_lightbringer::OnGossipSelect(), npc_fos_leader::OnGossipSelect(), npc_hor_leader::OnGossipSelect(), npc_thrall_old_hillsbrad::OnGossipSelect(), npc_hor_leader_second::OnGossipSelect(), npc_tirions_gambit_tirion::OnGossipSelect(), npc_artorius::OnGossipSelect(), npc_nelson::OnGossipSelect(), spell_xt002_gravity_bomb_aura::spell_xt002_gravity_bomb_aura_AuraScript::OnPeriodic(), instance_ulduar::instance_ulduar_InstanceMapScript::OnPlayerEnter(), npc_costumed_orphan_matron::OnQuestAccept(), npc_love_in_air_hummel::OnQuestReward(), npc_elder_clearwater::OnQuestReward(), npc_riggle_bassbait::OnQuestReward(), FrostwingGauntletRespawner::operator()(), kaylaan_the_lost::kaylaan_the_lostAI::ResetDeathblowEvent(), instance_ahnkahet::instance_ahnkahet_InstanceScript::SetData(), boss_yoggsaron_immortal_guardian::boss_yoggsaron_immortal_guardianAI::SpellHit(), npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::SpellHitTarget(), boss_zuramat::boss_zuramatAI::SummonedCreatureDespawn(), and boss_prince_valanar_icc::boss_prince_valanarAI::UpdateAI().
DoAddAuraToAllHostilePlayers()
void UnitAI::DoAddAuraToAllHostilePlayers (uint32 spellid)
Definition at line 109 of file UnitAI.cpp.
 {
     if (me->IsInCombat())
     {
         ThreatContainer::StorageType threatlist = me->getThreatMgr().getThreatList();
         for (ThreatContainer::StorageType::const_iterator itr = threatlist.begin(); itr != threatlist.end(); ++itr)
         {
             if (Unit* unit = ObjectAccessor::GetUnit(*me, (*itr)->getUnitGuid()))
                 if (unit->GetTypeId() == TYPEID_PLAYER)
                     me->AddAura(spellid, unit);
         }
     }
 }
References Unit::AddAura(), ThreatMgr::getThreatList(), Unit::getThreatMgr(), ObjectAccessor::GetUnit(), Unit::IsInCombat(), me, and TYPEID_PLAYER.
DoCast() [1/2]
void UnitAI::DoCast (uint32 spellId)
Definition at line 137 of file UnitAI.cpp.
 {
     Unit* target = nullptr;
     switch (AISpellInfo[spellId].target)
     {
         default:
         case AITARGET_SELF:
             target = me;
             break;
         case AITARGET_VICTIM:
             target = me->GetVictim();
             break;
         case AITARGET_ENEMY:
             {
                 const SpellInfo* spellInfo = sSpellMgr->GetSpellInfo(spellId);
                 bool playerOnly = spellInfo->HasAttribute(SPELL_ATTR3_ONLY_ON_PLAYER);
                 //float range = GetSpellMaxRange(spellInfo, false);
                 target = SelectTarget(SELECT_TARGET_RANDOM, 0, spellInfo->GetMaxRange(false), playerOnly);
                 break;
             }
         case AITARGET_ALLY:
             target = me;
             break;
         case AITARGET_BUFF:
             target = me;
             break;
         case AITARGET_DEBUFF:
             {
                 const SpellInfo* spellInfo = sSpellMgr->GetSpellInfo(spellId);
                 bool playerOnly = spellInfo->HasAttribute(SPELL_ATTR3_ONLY_ON_PLAYER);
                 float range = spellInfo->GetMaxRange(false);
                 DefaultTargetSelector targetSelector(me, range, playerOnly, -(int32)spellId);
                 if (!(spellInfo->AuraInterruptFlags & AURA_INTERRUPT_FLAG_NOT_VICTIM)
                         && targetSelector(me->GetVictim()))
                     target = me->GetVictim();
                 else
                     target = SelectTarget(SELECT_TARGET_RANDOM, 0, targetSelector);
                 break;
             }
     }
     if (target)
         me->CastSpell(target, spellId, false);
 }
References AISpellInfo, AITARGET_ALLY, AITARGET_BUFF, AITARGET_DEBUFF, AITARGET_ENEMY, AITARGET_SELF, AITARGET_VICTIM, AURA_INTERRUPT_FLAG_NOT_VICTIM, SpellInfo::AuraInterruptFlags, Unit::CastSpell(), SpellInfo::GetMaxRange(), Unit::GetVictim(), SpellInfo::HasAttribute(), me, SELECT_TARGET_RANDOM, SelectTarget(), SPELL_ATTR3_ONLY_ON_PLAYER, and sSpellMgr.
Referenced by npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI::AttackStart(), boss_victor_nefarius::boss_victor_nefariusAI::BeginEvent(), boss_professor_putricide::boss_professor_putricideAI::ChangePhase(), boss_twinemperorsAI::CheckEnrage(), boss_kurinnaxx::boss_kurinnaxxAI::DamageTaken(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::DamageTaken(), boss_ysondre::boss_ysondreAI::DamageTaken(), boss_lethon::boss_lethonAI::DamageTaken(), boss_emeriss::boss_emerissAI::DamageTaken(), boss_taerar::boss_taerarAI::DamageTaken(), boss_gyth::boss_gythAI::DamageTaken(), boss_viscidus::boss_viscidusAI::DamageTaken(), npc_infested_root_walker::npc_infested_root_walkerAI::DamageTaken(), npc_rotting_forest_rager::npc_rotting_forest_ragerAI::DamageTaken(), boss_moam::boss_moamAI::DoAction(), boss_professor_putricide::boss_professor_putricideAI::DoAction(), npc_ioc_gunship_captain::npc_ioc_gunship_captainAI::DoAction(), npc_simon_bunny::npc_simon_bunnyAI::DoAction(), DoCastSelf(), npc_ranshalla::npc_ranshallaAI::DoChannelTorchSpell(), hyjalAI::DoOverrun(), CasterAI::EnterCombat(), boss_jeklik::boss_jeklikAI::EnterCombat(), npc_coren_direbrew_sisters::npc_coren_direbrew_sistersAI::EnterCombat(), boss_ossirian::boss_ossirianAI::EnterCombat(), npc_centrifuge_construct::npc_centrifuge_constructAI::EnterCombat(), npc_maghar_captive::npc_maghar_captiveAI::EnterCombat(), npc_kurenai_captive::npc_kurenai_captiveAI::EnterCombat(), boss_vaelastrasz::boss_vaelAI::EnterCombat(), npc_high_inquisitor_valroth::npc_high_inquisitor_valrothAI::EnterCombat(), boss_buru::boss_buruAI::EnterCombat(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::EnterCombat(), boss_erekem::boss_erekemAI::EnterCombat(), boss_halazzi::boss_halazziAI::EnterPhase(), boss_zuljin::boss_zuljinAI::EnterPhase(), boss_baron_geddon::boss_baron_geddonAI::ExecuteEvent(), boss_gehennas::boss_gehennasAI::ExecuteEvent(), boss_magmadar::boss_magmadarAI::ExecuteEvent(), boss_shazzrah::boss_shazzrahAI::ExecuteEvent(), boss_sulfuron::boss_sulfuronAI::ExecuteEvent(), boss_amanitar::boss_amanitarAI::ExecuteEvent(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), emerald_dragonAI::ExecuteEvent(), boss_taerar::boss_taerarAI::ExecuteEvent(), npc_rocket_propelled_warhead::npc_rocket_propelled_warheadAI::FinishQuest(), boss_shade_of_aran::boss_aranAI::FlameWreathEffect(), npc_simon_bunny::npc_simon_bunnyAI::GivePunishment(), npc_simon_bunny::npc_simon_bunnyAI::GiveRewardForLevel(), npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::HandleAnimation(), boss_janalai::boss_janalaiAI::HandleBombSequence(), boss_viscidus::boss_viscidusAI::InitSpells(), npc_tiger_matriarch::npc_tiger_matriarchAI::IsSummonedBy(), npc_kilrek::npc_kilrekAI::JustDied(), npc_buru_egg::npc_buru_eggAI::JustDied(), boss_viscidus::boss_viscidusAI::JustDied(), npc_omen::npc_omenAI::JustDied(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustDied(), socrethar::socretharAI::JustDied(), boss_skeram::boss_skeramAI::JustSummoned(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustSummoned(), boss_twilight_corrupter::boss_twilight_corrupterAI::KilledUnit(), boss_mandokir::boss_mandokirAI::KilledUnit(), boss_doomlord_kazzak::boss_doomlordkazzakAI::KilledUnit(), boss_emeriss::boss_emerissAI::KilledUnit(), npc_drakuru_shackles::npc_drakuru_shacklesAI::LockRageclaw(), npc_depth_charge::npc_depth_chargeAI::MoveInLineOfSight(), npc_aged_dying_ancient_kodo::npc_aged_dying_ancient_kodoAI::MoveInLineOfSight(), npc_mageguard_dalaran::npc_mageguard_dalaranAI::MoveInLineOfSight(), npc_daranelle::npc_daranelleAI::MoveInLineOfSight(), npc_hive_zara_larva::npc_hive_zara_larvaAI::MovementInform(), npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::MovementInform(), npc_fel_guard_hound::npc_fel_guard_houndAI::MovementInform(), npc_vics_flying_machine::npc_vics_flying_machineAI::MovementInform(), npc_glob_of_viscidus::npc_glob_of_viscidusAI::MovementInform(), npc_akilzon_eagle::npc_akilzon_eagleAI::MovementInform(), npc_rocket_propelled_warhead::npc_rocket_propelled_warheadAI::PassengerBoarded(), boss_malchezaar::boss_malchezaarAI::Phase2(), npc_simon_bunny::npc_simon_bunnyAI::PlayColor(), npc_lake_frog::npc_lake_frogAI::ReceiveEmote(), npc_pet_gen_mojo::ReceiveEmote(), npc_dancing_flames::npc_dancing_flamesAI::ReceiveEmote(), npc_plucky::npc_pluckyAI::ReceiveEmote(), boss_terestian_illhoof::boss_terestianAI::Reset(), boss_halazzi::boss_halazziAI::Reset(), npc_zulian_prowler::npc_zulian_prowlerAI::Reset(), npc_shade_of_jindo::npc_shade_of_jindoAI::Reset(), npc_towering_infernal::npc_towering_infernalAI::Reset(), npc_lesser_doomguard::npc_lesser_doomguardAI::Reset(), hyjalAI::Reset(), npc_belnistrasz::npc_belnistraszAI::Reset(), npc_draenei_survivor::npc_draenei_survivorAI::Reset(), npc_troll_volunteer::npc_troll_volunteerAI::Reset(), npc_plucky::npc_pluckyAI::Reset(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::Reset(), npc_hidden_cultist::npc_hidden_cultistAI::Reset(), npc_tournament_training_dummy::npc_tournament_training_dummyAI::Reset(), npc_blessed_banner::npc_blessed_bannerAI::Reset(), npc_captured_rageclaw::npc_captured_rageclawAI::Reset(), emerald_dragonAI::Reset(), npc_dancing_flames::npc_dancing_flamesAI::Reset(), boss_baroness_anastari::boss_baroness_anastariAI::SchedulePossession(), boss_twinemperorsAI::SetAfterTeleport(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::SetGUID(), npc_kerlonian::npc_kerlonianAI::SetSleeping(), npc_lake_frog::npc_lake_frogAI::sGossipSelect(), npc_janalai_firebomb::npc_janalai_firebombAI::SpellHit(), npc_janalai_egg::npc_janalai_eggAI::SpellHit(), npc_captured_rageclaw::npc_captured_rageclawAI::SpellHit(), boss_viscidus::boss_viscidusAI::SpellHit(), npc_argent_captainAI::SpellHit(), npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::SpellHit(), npc_zuljin_vortex::npc_zuljin_vortexAI::SpellHit(), npc_draenei_survivor::npc_draenei_survivorAI::SpellHit(), npc_outhouse_bunny::npc_outhouse_bunnyAI::SpellHit(), npc_wounded_skirmisher::npc_wounded_skirmisherAI::SpellHit(), npc_forest_frog::npc_forest_frogAI::SpellHit(), npc_aged_dying_ancient_kodo::npc_aged_dying_ancient_kodoAI::SpellHit(), npc_troll_volunteer::npc_troll_volunteerAI::SpellHit(), npc_tournament_training_dummy::npc_tournament_training_dummyAI::SpellHit(), npc_greengill_slave::npc_greengill_slaveAI::SpellHit(), npc_spitelashes::npc_spitelashesAI::SpellHit(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::SpellHitTarget(), boss_netherspite::boss_netherspiteAI::SwitchToBanishPhase(), boss_twinemperorsAI::TryActivateAfterTTelep(), boss_twinemperorsAI::TryHealBrother(), npc_drakuru_shackles::npc_drakuru_shacklesAI::UnlockRageclaw(), CombatAI::UpdateAI(), CasterAI::UpdateAI(), npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI::UpdateAI(), boss_anubshiah::boss_anubshiahAI::UpdateAI(), boss_emperor_dagran_thaurissan::boss_draganthaurissanAI::UpdateAI(), boss_gorosh_the_dervish::boss_gorosh_the_dervishAI::UpdateAI(), boss_grizzle::boss_grizzleAI::UpdateAI(), boss_high_interrogator_gerstahn::boss_high_interrogator_gerstahnAI::UpdateAI(), boss_doomrel::boss_doomrelAI::UpdateAI(), boss_gyth::boss_gythAI::UpdateAI(), boss_halycon::boss_halyconAI::UpdateAI(), boss_lord_valthalak::boss_lord_valthalakAI::UpdateAI(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::UpdateAI(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::UpdateAI(), boss_rend_blackhand::boss_rend_blackhandAI::UpdateAI(), npc_rookery_hatcher::npc_rookery_hatcherAI::UpdateAI(), boss_the_beast::boss_thebeastAI::UpdateAI(), boss_chromaggus::boss_chromaggusAI::UpdateAI(), boss_flamegor::boss_flamegorAI::UpdateAI(), boss_victor_nefarius::boss_victor_nefariusAI::UpdateAI(), boss_nefarian::boss_nefarianAI::UpdateAI(), boss_golemagg::boss_golemaggAI::UpdateAI(), boss_majordomo::boss_majordomoAI::UpdateAI(), boss_ragnaros::boss_ragnarosAI::UpdateAI(), npc_flamewaker_priest::npc_flamewaker_priestAI::UpdateAI(), boss_netherspite::boss_netherspiteAI::UpdateAI(), boss_nightbane::boss_nightbaneAI::UpdateAI(), netherspite_infernal::netherspite_infernalAI::UpdateAI(), boss_malchezaar::boss_malchezaarAI::UpdateAI(), boss_shade_of_aran::boss_aranAI::UpdateAI(), boss_terestian_illhoof::boss_terestianAI::UpdateAI(), boss_dorothee::boss_dorotheeAI::UpdateAI(), npc_scarlet_miner::npc_scarlet_minerAI::UpdateAI(), npc_high_inquisitor_valroth::npc_high_inquisitor_valrothAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::UpdateAI(), boss_high_inquisitor_whitemane::boss_high_inquisitor_whitemaneAI::UpdateAI(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::UpdateAI(), boss_felmyst::boss_felmystAI::UpdateAI(), boss_twilight_corrupter::boss_twilight_corrupterAI::UpdateAI(), npc_calvin_montague::npc_calvin_montagueAI::UpdateAI(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::UpdateAI(), npc_highborne_lamenter::npc_highborne_lamenterAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_jaina_proudmoore_bfu::npc_jaina_proudmoore_bfuAI::UpdateAI(), boss_blight_worm::boss_blight_wormAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), npc_lady_sylvanas_windrunner_bfu::npc_lady_sylvanas_windrunner_bfuAI::UpdateAI(), boss_akilzon::boss_akilzonAI::UpdateAI(), boss_halazzi::boss_halazziAI::UpdateAI(), npc_halazzi_lynx::npc_halazzi_lynxAI::UpdateAI(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::UpdateAI(), boss_thurg::boss_thurgAI::UpdateAI(), boss_alyson_antille::boss_alyson_antilleAI::UpdateAI(), boss_slither::boss_slitherAI::UpdateAI(), boss_koragg::boss_koraggAI::UpdateAI(), boss_janalai::boss_janalaiAI::UpdateAI(), boss_nalorakk::boss_nalorakkAI::UpdateAI(), boss_zuljin::boss_zuljinAI::UpdateAI(), npc_forest_frog::npc_forest_frogAI::UpdateAI(), npc_harrison_jones::npc_harrison_jonesAI::UpdateAI(), boss_arlokk::boss_arlokkAI::UpdateAI(), boss_grilek::boss_grilekAI::UpdateAI(), boss_hakkar::boss_hakkarAI::UpdateAI(), boss_jeklik::boss_jeklikAI::UpdateAI(), boss_jindo::boss_jindoAI::UpdateAI(), npc_healing_ward::npc_healing_wardAI::UpdateAI(), boss_mandokir::boss_mandokirAI::UpdateAI(), npc_vilebranch_speaker::npc_vilebranch_speakerAI::UpdateAI(), boss_marli::boss_marliAI::UpdateAI(), npc_spawn_of_marli::npc_spawn_of_marliAI::UpdateAI(), boss_renataki::boss_renatakiAI::UpdateAI(), boss_thekal::boss_thekalAI::UpdateAI(), npc_zealot_lorkhan::npc_zealot_lorkhanAI::UpdateAI(), boss_venoxis::boss_venoxisAI::UpdateAI(), boss_wushoolay::boss_wushoolayAI::UpdateAI(), npc_snowfall_glade_playmate::npc_snowfall_glade_playmateAI::UpdateAI(), boss_azuregos::boss_azuregosAI::UpdateAI(), boss_anetheron::boss_anetheronAI::UpdateAI(), npc_towering_infernal::npc_towering_infernalAI::UpdateAI(), npc_ancient_wisp::npc_ancient_wispAI::UpdateAI(), boss_archimonde::boss_archimondeAI::UpdateAI(), boss_azgalor::boss_azgalorAI::UpdateAI(), npc_lesser_doomguard::npc_lesser_doomguardAI::UpdateAI(), boss_kazrogal::boss_kazrogalAI::UpdateAI(), boss_rage_winterchill::boss_rage_winterchillAI::UpdateAI(), npc_giant_infernal::npc_giant_infernalAI::UpdateAI(), npc_abomination::npc_abominationAI::UpdateAI(), npc_ghoul::npc_ghoulAI::UpdateAI(), npc_banshee::npc_bansheeAI::UpdateAI(), hyjalAI::UpdateAI(), npc_belnistrasz::npc_belnistraszAI::UpdateAI(), boss_ayamiss::boss_ayamissAI::UpdateAI(), boss_buru::boss_buruAI::UpdateAI(), boss_kurinnaxx::boss_kurinnaxxAI::UpdateAI(), boss_moam::boss_moamAI::UpdateAI(), boss_ossirian::boss_ossirianAI::UpdateAI(), boss_rajaxx::boss_rajaxxAI::UpdateAI(), boss_kri::boss_kriAI::UpdateAI(), boss_vem::boss_vemAI::UpdateAI(), boss_yauj::boss_yaujAI::UpdateAI(), boss_eye_of_cthun::eye_of_cthunAI::UpdateAI(), boss_cthun::cthunAI::UpdateAI(), npc_eye_tentacle::eye_tentacleAI::UpdateAI(), npc_giant_eye_tentacle::giant_eye_tentacleAI::UpdateAI(), boss_fankriss::boss_fankrissAI::UpdateAI(), boss_huhuran::boss_huhuranAI::UpdateAI(), boss_ouro::boss_ouroAI::UpdateAI(), boss_sartura::boss_sarturaAI::UpdateAI(), npc_sartura_royal_guard::npc_sartura_royal_guardAI::UpdateAI(), boss_skeram::boss_skeramAI::UpdateAI(), boss_veknilash::boss_veknilashAI::UpdateAI(), boss_veklor::boss_veklorAI::UpdateAI(), boss_viscidus::boss_viscidusAI::UpdateAI(), npc_spitelashes::npc_spitelashesAI::UpdateAI(), npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI::UpdateAI(), npc_omen::npc_omenAI::UpdateAI(), npc_qiraj_war_spawn::npc_qiraj_war_spawnAI::UpdateAI(), npc_aquementas::npc_aquementasAI::UpdateAI(), npc_cairne_bloodhoof::npc_cairne_bloodhoofAI::UpdateAI(), npc_shadowpriest_sezziz::npc_shadowpriest_sezzizAI::UpdateAI(), boss_elder_nadox::boss_elder_nadoxAI::UpdateAI(), boss_volazj::boss_volazjAI::UpdateAI(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::UpdateAI(), boss_taldaram::boss_taldaramAI::UpdateAI(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), npc_rotting_frost_giant::npc_rotting_frost_giantAI::UpdateAI(), npc_frost_freeze_trap::npc_frost_freeze_trapAI::UpdateAI(), boss_sister_svalna::boss_sister_svalnaAI::UpdateAI(), npc_captain_arnath::npc_captain_arnathAI::UpdateAI(), npc_captain_brandon::npc_captain_brandonAI::UpdateAI(), npc_captain_grondel::npc_captain_grondelAI::UpdateAI(), npc_captain_rupert::npc_captain_rupertAI::UpdateAI(), npc_ioc_gunship_captain::npc_ioc_gunship_captainAI::UpdateAI(), boss_urom::boss_uromAI::UpdateAI(), npc_vrykul_skeleton::npc_vrykul_skeletonAI::UpdateAI(), npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI::UpdateAI(), boss_archavon::boss_archavonAI::UpdateAI(), npc_azure_invader::npc_azure_invaderAI::UpdateAI(), npc_azure_binder::npc_azure_binderAI::UpdateAI(), npc_azure_mage_slayer::npc_azure_mage_slayerAI::UpdateAI(), npc_azure_raider::npc_azure_raiderAI::UpdateAI(), npc_azure_stalker::npc_azure_stalkerAI::UpdateAI(), npc_azure_spellbreaker::npc_azure_spellbreakerAI::UpdateAI(), npc_azure_captain::npc_azure_captainAI::UpdateAI(), npc_azure_sorceror::npc_azure_sorcerorAI::UpdateAI(), npc_sinkhole_kill_credit::npc_sinkhole_kill_creditAI::UpdateAI(), npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI::UpdateAI(), npc_minigob_manabonk::npc_minigob_manabonkAI::UpdateAI(), npc_dalaran_mage::npc_dalaran_mageAI::UpdateAI(), npc_dalaran_warrior::npc_dalaran_warriorAI::UpdateAI(), npc_venture_co_straggler::npc_venture_co_stragglerAI::UpdateAI(), npc_lake_frog::npc_lake_frogAI::UpdateAI(), npc_tournament_training_dummy::npc_tournament_training_dummyAI::UpdateAI(), npc_blessed_banner::npc_blessed_bannerAI::UpdateAI(), boss_pandemonius::boss_pandemoniusAI::UpdateAI(), boss_talon_king_ikiss::boss_talon_king_ikissAI::UpdateAI(), boss_doomlord_kazzak::boss_doomlordkazzakAI::UpdateAI(), boss_doomwalker::boss_doomwalkerAI::UpdateAI(), boss_hydromancer_thespia::boss_thespiaAI::UpdateAI(), boss_gruul::boss_gruulAI::UpdateAI(), npc_nether_drake::npc_nether_drakeAI::UpdateAI(), npc_simon_bunny::npc_simon_bunnyAI::UpdateAI(), npc_oscillating_frequency_scanner_master_bunny::npc_oscillating_frequency_scanner_master_bunnyAI::UpdateAI(), npc_maghar_captive::npc_maghar_captiveAI::UpdateAI(), npc_phase_hunter::npc_phase_hunterAI::UpdateAI(), npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::UpdateAI(), npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI::UpdateAI(), npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::UpdateAI(), npc_illidari_spawn::npc_illidari_spawnAI::UpdateAI(), npc_unkor_the_ruthless::npc_unkor_the_ruthlessAI::UpdateAI(), npc_floon::npc_floonAI::UpdateAI(), emerald_dragonAI::UpdateAI(), guard_shattrath_scryer::guard_shattrath_scryerAI::UpdateAI(), guard_shattrath_aldor::guard_shattrath_aldorAI::UpdateAI(), npc_warmage_coldarra::npc_warmage_coldarraAI::UpdateAI(), npc_earthmender_wilda::npc_earthmender_wildaAI::UpdateAI(), npc_zulaman_hostage::npc_zulaman_hostageAI::UpdateAI(), npc_warmage_violetstand::npc_warmage_violetstandAI::UpdateAI(), npc_wg_spirit_guide::npc_wg_spirit_guideAI::UpdateAI(), npc_apothecary_hanes::npc_Apothecary_HanesAI::UpdateEscortAI(), npc_kurenai_captive::npc_kurenai_captiveAI::UpdateEscortAI(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::UseAbility(), npc_barnes::npc_barnesAI::WaypointReached(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::WaypointReached(), npc_frost_wyrm::npc_frost_wyrmAI::WaypointReached(), npc_gargoyle::npc_gargoyleAI::WaypointReached(), hyjalAI::WaypointReached(), npc_custodian_of_time::npc_custodian_of_timeAI::WaypointReached(), and npc_isla_starmane::npc_isla_starmaneAI::WaypointReached().
DoCast() [2/2]
void UnitAI::DoCast (Unit * victim, uint32 spellId, bool triggered = false)
Definition at line 184 of file UnitAI.cpp.
 {
     if (!victim || (me->HasUnitState(UNIT_STATE_CASTING) && !triggered))
         return;
     me->CastSpell(victim, spellId, triggered);
 }
References Unit::CastSpell(), Unit::HasUnitState(), me, and UNIT_STATE_CASTING.
DoCastAOE()
void UnitAI::DoCastAOE (uint32 spellId, bool triggered = false)
Definition at line 200 of file UnitAI.cpp.
 {
     if (!triggered && me->HasUnitState(UNIT_STATE_CASTING))
         return;
     me->CastSpell((Unit*)nullptr, spellId, triggered);
 }
References Unit::CastSpell(), Unit::HasUnitState(), me, and UNIT_STATE_CASTING.
Referenced by boss_golemagg::boss_golemaggAI::DamageTaken(), npc_garr_firesworn::npc_garr_fireswornAI::DamageTaken(), boss_icehowl::boss_icehowlAI::DoTrampleIfValid(), boss_majordomo::boss_majordomoAI::EnterCombat(), boss_baron_geddon::boss_baron_geddonAI::ExecuteEvent(), boss_shazzrah::boss_shazzrahAI::ExecuteEvent(), boss_amanitar::boss_amanitarAI::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), npc_buru_egg::npc_buru_eggAI::JustDied(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::JustDied(), boss_professor_putricide::boss_professor_putricideAI::JustDied(), boss_sindragosa::boss_sindragosaAI::JustDied(), boss_majordomo::boss_majordomoAI::MovementInform(), boss_urom::boss_uromAI::SpellHit(), npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::SpellHit(), npc_crusade_persuaded::npc_crusade_persuadedAI::SpellHit(), boss_majordomo::boss_majordomoAI::SummonedCreatureDies(), boss_drakkisath::boss_drakkisathAI::UpdateAI(), boss_garr::boss_garrAI::UpdateAI(), boss_golemagg::boss_golemaggAI::UpdateAI(), boss_majordomo::boss_majordomoAI::UpdateAI(), npc_crusade_persuaded::npc_crusade_persuadedAI::UpdateAI(), boss_kazrogal::boss_kazrogalAI::UpdateAI(), boss_moam::boss_moamAI::UpdateAI(), boss_skeram::boss_skeramAI::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), npc_arthas_teleport_visual::npc_arthas_teleport_visualAI::UpdateAI(), npc_azure_captain::npc_azure_captainAI::UpdateAI(), npc_azure_sorceror::npc_azure_sorcerorAI::UpdateAI(), and npc_onyx_flamecaller::npc_onyx_flamecallerAI::UpdateEscortAI().
DoCastRandomTarget()
void UnitAI::DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition = 0, float dist = 0.0f, bool playerOnly = true, bool triggered = false)
Definition at line 208 of file UnitAI.cpp.
 {
     if (!triggered && me->HasUnitState(UNIT_STATE_CASTING))
     {
         return;
     }
     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, threatTablePosition, dist, playerOnly))
     {
         me->CastSpell(target, spellId, triggered);
     }
 }
References Unit::CastSpell(), Unit::HasUnitState(), me, SELECT_TARGET_RANDOM, SelectTarget(), and UNIT_STATE_CASTING.
Referenced by boss_warmaster_voone::boss_warmastervooneAI::ExecuteEvent(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::UpdateAI(), and boss_the_beast::boss_thebeastAI::UpdateAI().
DoCastSelf()
void UnitAI::DoCastSelf (uint32 spellId, bool triggered = false) inline
Definition at line 299 of file UnitAI.h.
 { DoCast(me, spellId, triggered); }
References DoCast(), and me.
Referenced by boss_quartermaster_zigris::DamageTaken(), boss_golemagg::boss_golemaggAI::DamageTaken(), npc_core_rager::npc_core_ragerAI::DamageTaken(), npc_mc_core_hound::npc_mc_core_houndAI::DamageTaken(), npc_amanitar_mushrooms::npc_amanitar_mushroomsAI::DamageTaken(), boss_volazj::boss_volazjAI::DamageTaken(), boss_sartharion::boss_sartharionAI::DamageTaken(), npc_garr_firesworn::npc_garr_fireswornAI::DamageTaken(), npc_twilight_volunteer::npc_twilight_volunteerAI::DoAction(), boss_taldaram::boss_taldaramAI::DoAction(), boss_sartharion::boss_sartharionAI::DoAction(), boss_garr::boss_garrAI::EnterCombat(), boss_majordomo::boss_majordomoAI::EnterCombat(), npc_coren_direbrew_sisters::npc_coren_direbrew_sistersAI::EnterCombat(), boss_volazj::boss_volazjAI::EnterCombat(), boss_sartharion::boss_sartharionAI::EnterCombat(), boss_warmaster_voone::boss_warmastervooneAI::ExecuteEvent(), boss_magmadar::boss_magmadarAI::ExecuteEvent(), boss_shazzrah::boss_shazzrahAI::ExecuteEvent(), boss_sulfuron::boss_sulfuronAI::ExecuteEvent(), boss_amanitar::boss_amanitarAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), boss_taldaram::boss_taldaramAI::InitializeAI(), npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::IsSummonedBy(), boss_volazj::boss_volazjAI::JustDied(), npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::JustDied(), boss_volazj::boss_volazjAI::KilledUnit(), npc_twilight_volunteer::npc_twilight_volunteerAI::MovementInform(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::MovementInform(), npc_core_rager::npc_core_ragerAI::Reset(), boss_ragnaros::boss_ragnarosAI::Reset(), npc_amanitar_mushrooms::npc_amanitar_mushroomsAI::Reset(), npc_ahnkahar_nerubian::npc_ahnkahar_nerubianAI::Reset(), boss_baroness_anastari::boss_baroness_anastariAI::SchedulePossession(), npc_thassarian2::npc_thassarian2AI::sGossipHello(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::SummonedCreatureDies(), boss_drakkisath::boss_drakkisathAI::UpdateAI(), boss_garr::boss_garrAI::UpdateAI(), boss_majordomo::boss_majordomoAI::UpdateAI(), boss_ragnaros::boss_ragnarosAI::UpdateAI(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::UpdateAI(), npc_coren_direbrew::npc_coren_direbrewAI::UpdateAI(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::UpdateAI(), npc_amanitar_mushrooms::npc_amanitar_mushroomsAI::UpdateAI(), boss_elder_nadox::boss_elder_nadoxAI::UpdateAI(), npc_ahnkahar_nerubian::npc_ahnkahar_nerubianAI::UpdateAI(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::UpdateAI(), npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::UpdateAI(), boss_taldaram::boss_taldaramAI::UpdateAI(), boss_sartharion::boss_sartharionAI::UpdateAI(), boss_noth::boss_nothAI::UpdateAI(), and npc_counselor_talbot::npc_counselor_talbotAI::UpdateAI().
DoCastToAllHostilePlayers()
void UnitAI::DoCastToAllHostilePlayers (uint32 spellid, bool triggered = false)
Definition at line 123 of file UnitAI.cpp.
 {
     if (me->IsInCombat())
     {
         ThreatContainer::StorageType threatlist = me->getThreatMgr().getThreatList();
         for (ThreatContainer::StorageType::const_iterator itr = threatlist.begin(); itr != threatlist.end(); ++itr)
         {
             if (Unit* unit = ObjectAccessor::GetUnit(*me, (*itr)->getUnitGuid()))
                 if (unit->GetTypeId() == TYPEID_PLAYER)
                     me->CastSpell(unit, spellid, triggered);
         }
     }
 }
References Unit::CastSpell(), ThreatMgr::getThreatList(), Unit::getThreatMgr(), ObjectAccessor::GetUnit(), Unit::IsInCombat(), me, and TYPEID_PLAYER.
DoCastVictim()
void UnitAI::DoCastVictim (uint32 spellId, bool triggered = false)
Definition at line 192 of file UnitAI.cpp.
 {
     if (!me->GetVictim() || (me->HasUnitState(UNIT_STATE_CASTING) && !triggered))
         return;
     me->CastSpell(me->GetVictim(), spellId, triggered);
 }
References Unit::CastSpell(), Unit::GetVictim(), Unit::HasUnitState(), me, and UNIT_STATE_CASTING.
Referenced by boss_taerar::boss_taerarAI::DamageTaken(), boss_zuljin::boss_zuljinAI::DoMeleeAttackIfReady(), boss_baroness_anastari::boss_baroness_anastariAI::EnterCombat(), npc_hallows_end_soh::npc_hallows_end_sohAI::EnterCombat(), boss_ouro::boss_ouroAI::EnterCombat(), boss_solakar_flamewreath::boss_solakar_flamewreathAI::ExecuteEvent(), boss_warmaster_voone::boss_warmastervooneAI::ExecuteEvent(), boss_gehennas::boss_gehennasAI::ExecuteEvent(), boss_lucifron::boss_lucifronAI::ExecuteEvent(), boss_magmadar::boss_magmadarAI::ExecuteEvent(), boss_shazzrah::boss_shazzrahAI::ExecuteEvent(), boss_sulfuron::boss_sulfuronAI::ExecuteEvent(), boss_amanitar::boss_amanitarAI::ExecuteEvent(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), boss_ysondre::boss_ysondreAI::ExecuteEvent(), boss_emeriss::boss_emerissAI::ExecuteEvent(), boss_archimonde::boss_archimondeAI::UnleashSoulCharge(), npc_daphne_stilwell::npc_daphne_stilwellAI::Update(), npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI::UpdateAI(), npc_water_elemental::npc_water_elementalAI::UpdateAI(), boss_balinda::boss_balindaAI::UpdateAI(), boss_drekthar::boss_drektharAI::UpdateAI(), boss_galvangar::boss_galvangarAI::UpdateAI(), boss_vanndar::boss_vanndarAI::UpdateAI(), npc_phalanx::npc_phalanxAI::UpdateAI(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::UpdateAI(), boss_anubshiah::boss_anubshiahAI::UpdateAI(), boss_emperor_dagran_thaurissan::boss_draganthaurissanAI::UpdateAI(), boss_general_angerforge::boss_general_angerforgeAI::UpdateAI(), boss_gorosh_the_dervish::boss_gorosh_the_dervishAI::UpdateAI(), boss_grizzle::boss_grizzleAI::UpdateAI(), boss_high_interrogator_gerstahn::boss_high_interrogator_gerstahnAI::UpdateAI(), boss_magmus::boss_magmusAI::UpdateAI(), boss_moira_bronzebeard::boss_moira_bronzebeardAI::UpdateAI(), boss_doomrel::boss_doomrelAI::UpdateAI(), boss_drakkisath::boss_drakkisathAI::UpdateAI(), chromatic_elite_guard::chromatic_elite_guardAI::UpdateAI(), boss_gyth::boss_gythAI::UpdateAI(), boss_halycon::boss_halyconAI::UpdateAI(), boss_highlord_omokk::boss_highlordomokkAI::UpdateAI(), boss_lord_valthalak::boss_lord_valthalakAI::UpdateAI(), boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI::UpdateAI(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::UpdateAI(), boss_quartermaster_zigris::UpdateAI(), boss_rend_blackhand::boss_rend_blackhandAI::UpdateAI(), boss_the_beast::boss_thebeastAI::UpdateAI(), boss_urok_doomhowl::boss_urok_doomhowlAI::UpdateAI(), boss_broodlord::boss_broodlordAI::UpdateAI(), boss_chromaggus::boss_chromaggusAI::UpdateAI(), boss_ebonroc::boss_ebonrocAI::UpdateAI(), boss_firemaw::boss_firemawAI::UpdateAI(), boss_flamegor::boss_flamegorAI::UpdateAI(), boss_victor_nefarius::boss_victor_nefariusAI::UpdateAI(), boss_nefarian::boss_nefarianAI::UpdateAI(), boss_razorgore::boss_razorgoreAI::UpdateAI(), boss_vaelastrasz::boss_vaelAI::UpdateAI(), npc_core_rager::npc_core_ragerAI::UpdateAI(), boss_majordomo::boss_majordomoAI::UpdateAI(), boss_ragnaros::boss_ragnarosAI::UpdateAI(), npc_mc_core_hound::npc_mc_core_houndAI::UpdateAI(), boss_nightbane::boss_nightbaneAI::UpdateAI(), npc_aran_elemental::water_elementalAI::UpdateAI(), npc_kilrek::npc_kilrekAI::UpdateAI(), npc_fiendish_imp::npc_fiendish_impAI::UpdateAI(), boss_terestian_illhoof::boss_terestianAI::UpdateAI(), boss_dorothee::boss_dorotheeAI::UpdateAI(), npc_tito::npc_titoAI::UpdateAI(), npc_unworthy_initiate::npc_unworthy_initiateAI::UpdateAI(), npc_high_inquisitor_valroth::npc_high_inquisitor_valrothAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::UpdateAI(), boss_twilight_corrupter::boss_twilight_corrupterAI::UpdateAI(), npc_corporal_keeshan::npc_corporal_keeshanAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), npc_lady_sylvanas_windrunner_bfu::npc_lady_sylvanas_windrunner_bfuAI::UpdateAI(), boss_akilzon::boss_akilzonAI::UpdateAI(), boss_halazzi::boss_halazziAI::UpdateAI(), npc_halazzi_lynx::npc_halazzi_lynxAI::UpdateAI(), boss_thurg::boss_thurgAI::UpdateAI(), boss_gazakrothAI::UpdateAI(), boss_lord_raadan::boss_lord_raadanAI::UpdateAI(), boss_darkheart::boss_darkheartAI::UpdateAI(), boss_koragg::boss_koraggAI::UpdateAI(), npc_janalai_hatchling::npc_janalai_hatchlingAI::UpdateAI(), boss_nalorakk::boss_nalorakkAI::UpdateAI(), boss_arlokk::boss_arlokkAI::UpdateAI(), boss_gahzranka::boss_gahzrankaAI::UpdateAI(), boss_grilek::boss_grilekAI::UpdateAI(), boss_hakkar::boss_hakkarAI::UpdateAI(), boss_hazzarah::boss_hazzarahAI::UpdateAI(), boss_jeklik::boss_jeklikAI::UpdateAI(), npc_shade_of_jindo::npc_shade_of_jindoAI::UpdateAI(), boss_mandokir::boss_mandokirAI::UpdateAI(), npc_ohgan::npc_ohganAI::UpdateAI(), npc_vilebranch_speaker::npc_vilebranch_speakerAI::UpdateAI(), boss_marli::boss_marliAI::UpdateAI(), boss_renataki::boss_renatakiAI::UpdateAI(), boss_thekal::boss_thekalAI::UpdateAI(), npc_zealot_lorkhan::npc_zealot_lorkhanAI::UpdateAI(), npc_zealot_zath::npc_zealot_zathAI::UpdateAI(), boss_venoxis::boss_venoxisAI::UpdateAI(), boss_wushoolay::boss_wushoolayAI::UpdateAI(), boss_azuregos::boss_azuregosAI::UpdateAI(), boss_archimonde::boss_archimondeAI::UpdateAI(), boss_azgalor::boss_azgalorAI::UpdateAI(), boss_rage_winterchill::boss_rage_winterchillAI::UpdateAI(), npc_giant_infernal::npc_giant_infernalAI::UpdateAI(), npc_abomination::npc_abominationAI::UpdateAI(), npc_necromancer::npc_necromancerAI::UpdateAI(), npc_banshee::npc_bansheeAI::UpdateAI(), npc_crypt_fiend::npc_crypt_fiendAI::UpdateAI(), npc_fel_stalker::npc_fel_stalkerAI::UpdateAI(), npc_frost_wyrm::npc_frost_wyrmAI::UpdateAI(), npc_gargoyle::npc_gargoyleAI::UpdateAI(), npc_belnistrasz::npc_belnistraszAI::UpdateAI(), boss_ayamiss::boss_ayamissAI::UpdateAI(), boss_buru::boss_buruAI::UpdateAI(), boss_kurinnaxx::boss_kurinnaxxAI::UpdateAI(), boss_ossirian::boss_ossirianAI::UpdateAI(), boss_rajaxx::boss_rajaxxAI::UpdateAI(), boss_kri::boss_kriAI::UpdateAI(), boss_vem::boss_vemAI::UpdateAI(), boss_yauj::boss_yaujAI::UpdateAI(), npc_claw_tentacle::claw_tentacleAI::UpdateAI(), npc_giant_claw_tentacle::giant_claw_tentacleAI::UpdateAI(), boss_fankriss::boss_fankrissAI::UpdateAI(), boss_huhuran::boss_huhuranAI::UpdateAI(), boss_ouro::boss_ouroAI::UpdateAI(), boss_skeram::boss_skeramAI::UpdateAI(), boss_veknilash::boss_veknilashAI::UpdateAI(), boss_veklor::boss_veklorAI::UpdateAI(), npc_death_ravager::npc_death_ravagerAI::UpdateAI(), npc_tiger_matriarch::npc_tiger_matriarchAI::UpdateAI(), npc_omen::npc_omenAI::UpdateAI(), npc_thrall_warchief::npc_thrall_warchiefAI::UpdateAI(), npc_aquementas::npc_aquementasAI::UpdateAI(), npc_cairne_bloodhoof::npc_cairne_bloodhoofAI::UpdateAI(), npc_ame::npc_ameAI::UpdateAI(), npc_sergeant_bly::npc_sergeant_blyAI::UpdateAI(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::UpdateAI(), npc_shadowpriest_sezziz::npc_shadowpriest_sezzizAI::UpdateAI(), boss_elder_nadox::boss_elder_nadoxAI::UpdateAI(), boss_volazj::boss_volazjAI::UpdateAI(), boss_sartharion::boss_sartharionAI::UpdateAI(), npc_twilight_summon::npc_twilight_summonAI::UpdateAI(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::UpdateAI(), boss_lord_marrowgar::UpdateAI(), npc_rotting_frost_giant::npc_rotting_frost_giantAI::UpdateAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI(), npc_captain_arnath::npc_captain_arnathAI::UpdateAI(), npc_captain_brandon::npc_captain_brandonAI::UpdateAI(), npc_captain_grondel::npc_captain_grondelAI::UpdateAI(), boss_archavon::boss_archavonAI::UpdateAI(), npc_beryl_sorcerer::npc_beryl_sorcererAI::UpdateAI(), npc_counselor_talbot::npc_counselor_talbotAI::UpdateAI(), npc_torturer_lecraft::npc_torturer_lecraftAI::UpdateAI(), npc_venture_co_straggler::npc_venture_co_stragglerAI::UpdateAI(), npc_yor::npc_yorAI::UpdateAI(), boss_doomlord_kazzak::boss_doomlordkazzakAI::UpdateAI(), boss_doomwalker::boss_doomwalkerAI::UpdateAI(), npc_nether_drake::npc_nether_drakeAI::UpdateAI(), npc_aeranas::npc_aeranasAI::UpdateAI(), npc_maghar_captive::npc_maghar_captiveAI::UpdateAI(), socrethar::socretharAI::UpdateAI(), npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::UpdateAI(), npc_dragonmaw_peon::npc_dragonmaw_peonAI::UpdateAI(), npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::UpdateAI(), npc_illidari_spawn::npc_illidari_spawnAI::UpdateAI(), npc_raliq_the_drunk::npc_raliq_the_drunkAI::UpdateAI(), npc_salsalabim::npc_salsalabimAI::UpdateAI(), npc_floon::npc_floonAI::UpdateAI(), npc_cooshcoosh::npc_cooshcooshAI::UpdateAI(), npc_pet_hunter_snake_trap::UpdateAI(), npc_pet_shaman_earth_elemental::UpdateAI(), npc_onyx_flamecaller::npc_onyx_flamecallerAI::UpdateEscortAI(), and npc_kurenai_captive::npc_kurenai_captiveAI::UpdateEscortAI().
DoGetSpellMaxRange()
float UnitAI::DoGetSpellMaxRange (uint32 spellId, bool positive = false)
Definition at line 103 of file UnitAI.cpp.
 {
     SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(spellId);
     return spellInfo ? spellInfo->GetMaxRange(positive) : 0;
 }
References SpellInfo::GetMaxRange(), and sSpellMgr.
DoMeleeAttackIfReady()
void UnitAI::DoMeleeAttackIfReady ()
Definition at line 40 of file UnitAI.cpp.
 {
     if (me->HasUnitState(UNIT_STATE_CASTING))
         return;
     Unit* victim = me->GetVictim();
     if (!victim || !victim->IsInWorld())
         return;
     if (!me->IsWithinMeleeRange(victim))
         return;
     //Make sure our attack is ready and we aren't currently casting before checking distance
     if (me->isAttackReady())
     {
         // xinef: prevent base and off attack in same time, delay attack at 0.2 sec
         if (me->haveOffhandWeapon())
             if (me->getAttackTimer(OFF_ATTACK) < ATTACK_DISPLAY_DELAY)
                 me->setAttackTimer(OFF_ATTACK, ATTACK_DISPLAY_DELAY);
         me->AttackerStateUpdate(victim);
         me->resetAttackTimer();
     }
     if (me->haveOffhandWeapon() && me->isAttackReady(OFF_ATTACK))
     {
         // xinef: delay main hand attack if both will hit at the same time (players code)
         if (me->getAttackTimer(BASE_ATTACK) < ATTACK_DISPLAY_DELAY)
             me->setAttackTimer(BASE_ATTACK, ATTACK_DISPLAY_DELAY);
         me->AttackerStateUpdate(victim, OFF_ATTACK);
         me->resetAttackTimer(OFF_ATTACK);
     }
 }
References ATTACK_DISPLAY_DELAY, Unit::AttackerStateUpdate(), BASE_ATTACK, Unit::getAttackTimer(), Unit::GetVictim(), Unit::HasUnitState(), Unit::haveOffhandWeapon(), Unit::isAttackReady(), Object::IsInWorld(), Unit::IsWithinMeleeRange(), me, OFF_ATTACK, Unit::resetAttackTimer(), Unit::setAttackTimer(), and UNIT_STATE_CASTING.
Referenced by PetAI::_doMeleeAttack(), boss_twin_valkyrAI::myDoMeleeAttackIfReady(), npc_razzashi_cobra_venoxis::npc_razzashi_cobra_venoxis_AI::UpdateAI(), boss_sartharion_dragonAI::UpdateAI(), CombatAI::UpdateAI(), ArcherAI::UpdateAI(), ReactorAI::UpdateAI(), ScriptedAI::UpdateAI(), BossAI::UpdateAI(), WorldBossAI::UpdateAI(), SmartAI::UpdateAI(), npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI::UpdateAI(), npc_water_elemental::npc_water_elementalAI::UpdateAI(), boss_balinda::boss_balindaAI::UpdateAI(), boss_drekthar::boss_drektharAI::UpdateAI(), boss_galvangar::boss_galvangarAI::UpdateAI(), boss_vanndar::boss_vanndarAI::UpdateAI(), npc_phalanx::npc_phalanxAI::UpdateAI(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::UpdateAI(), boss_anubshiah::boss_anubshiahAI::UpdateAI(), boss_emperor_dagran_thaurissan::boss_draganthaurissanAI::UpdateAI(), boss_general_angerforge::boss_general_angerforgeAI::UpdateAI(), boss_gorosh_the_dervish::boss_gorosh_the_dervishAI::UpdateAI(), boss_grizzle::boss_grizzleAI::UpdateAI(), boss_high_interrogator_gerstahn::boss_high_interrogator_gerstahnAI::UpdateAI(), boss_magmus::boss_magmusAI::UpdateAI(), boss_doomrel::boss_doomrelAI::UpdateAI(), boss_drakkisath::boss_drakkisathAI::UpdateAI(), chromatic_elite_guard::chromatic_elite_guardAI::UpdateAI(), boss_gyth::boss_gythAI::UpdateAI(), boss_halycon::boss_halyconAI::UpdateAI(), boss_highlord_omokk::boss_highlordomokkAI::UpdateAI(), boss_lord_valthalak::boss_lord_valthalakAI::UpdateAI(), boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI::UpdateAI(), boss_pyroguard_emberseer::boss_pyroguard_emberseerAI::UpdateAI(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::UpdateAI(), boss_quartermaster_zigris::UpdateAI(), boss_rend_blackhand::boss_rend_blackhandAI::UpdateAI(), npc_rookery_hatcher::npc_rookery_hatcherAI::UpdateAI(), boss_solakar_flamewreath::boss_solakar_flamewreathAI::UpdateAI(), boss_the_beast::boss_thebeastAI::UpdateAI(), boss_urok_doomhowl::boss_urok_doomhowlAI::UpdateAI(), boss_broodlord::boss_broodlordAI::UpdateAI(), boss_chromaggus::boss_chromaggusAI::UpdateAI(), boss_ebonroc::boss_ebonrocAI::UpdateAI(), boss_firemaw::boss_firemawAI::UpdateAI(), boss_flamegor::boss_flamegorAI::UpdateAI(), boss_nefarian::boss_nefarianAI::UpdateAI(), boss_razorgore::boss_razorgoreAI::UpdateAI(), boss_vaelastrasz::boss_vaelAI::UpdateAI(), boss_garr::boss_garrAI::UpdateAI(), boss_golemagg::boss_golemaggAI::UpdateAI(), npc_core_rager::npc_core_ragerAI::UpdateAI(), boss_majordomo::boss_majordomoAI::UpdateAI(), boss_ragnaros::boss_ragnarosAI::UpdateAI(), npc_flamewaker_priest::npc_flamewaker_priestAI::UpdateAI(), npc_mc_core_hound::npc_mc_core_houndAI::UpdateAI(), boss_mr_smite::boss_mr_smiteAI::UpdateAI(), boss_curator::boss_curatorAI::UpdateAI(), boss_maiden_of_virtue::boss_maiden_of_virtueAI::UpdateAI(), boss_midnight::boss_midnightAI::UpdateAI(), boss_attumen::boss_attumenAI::UpdateAI(), boss_attumen_midnight::boss_attumen_midnightAI::UpdateAI(), boss_moroes::boss_moroesAI::UpdateAI(), boss_netherspite::boss_netherspiteAI::UpdateAI(), boss_nightbane::boss_nightbaneAI::UpdateAI(), boss_malchezaar::boss_malchezaarAI::UpdateAI(), prince_axes::prince_axesAI::UpdateAI(), boss_servant_quarters::boss_servant_quartersAI::UpdateAI(), boss_shade_of_aran::boss_aranAI::UpdateAI(), npc_kilrek::npc_kilrekAI::UpdateAI(), npc_fiendish_imp::npc_fiendish_impAI::UpdateAI(), boss_terestian_illhoof::boss_terestianAI::UpdateAI(), boss_dorothee::boss_dorotheeAI::UpdateAI(), npc_tito::npc_titoAI::UpdateAI(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::UpdateAI(), boss_priestess_delrissa::boss_priestess_delrissaAI::UpdateAI(), boss_kagani_nightstrike::boss_kagani_nightstrikeAI::UpdateAI(), boss_ellris_duskhallow::boss_ellris_duskhallowAI::UpdateAI(), boss_eramas_brightblaze::boss_eramas_brightblazeAI::UpdateAI(), boss_yazzai::boss_yazzaiAI::UpdateAI(), boss_warlord_salaris::boss_warlord_salarisAI::UpdateAI(), boss_garaxxas::boss_garaxxasAI::UpdateAI(), boss_apoko::boss_apokoAI::UpdateAI(), boss_zelfan::boss_zelfanAI::UpdateAI(), boss_selin_fireheart::boss_selin_fireheartAI::UpdateAI(), boss_vexallus::boss_vexallusAI::UpdateAI(), npc_scarlet_ghoul::npc_scarlet_ghoulAI::UpdateAI(), npc_unworthy_initiate::npc_unworthy_initiateAI::UpdateAI(), npc_scarlet_courier::npc_scarlet_courierAI::UpdateAI(), npc_high_inquisitor_valroth::npc_high_inquisitor_valrothAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_mograine::npc_mograineAI::UpdateAI(), boss_high_inquisitor_whitemane::boss_high_inquisitor_whitemaneAI::UpdateAI(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::UpdateAI(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::UpdateAI(), npc_scholomance_occultist::npc_scholomance_occultistAI::UpdateAI(), boss_baroness_anastari::boss_baroness_anastariAI::UpdateAI(), boss_brutallus::boss_brutallusAI::UpdateAI(), boss_sacrolash::boss_sacrolashAI::UpdateAI(), boss_alythess::boss_alythessAI::UpdateAI(), boss_felmyst::boss_felmystAI::UpdateAI(), boss_kalecgos::boss_kalecgosAI::UpdateAI(), boss_kalec::boss_kalecAI::UpdateAI(), boss_sathrovarr::boss_sathrovarrAI::UpdateAI(), boss_kiljaeden::boss_kiljaedenAI::UpdateAI(), boss_entropius::boss_entropiusAI::UpdateAI(), boss_twilight_corrupter::boss_twilight_corrupterAI::UpdateAI(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), npc_corporal_keeshan::npc_corporal_keeshanAI::UpdateAI(), pyrewood_ambush::pyrewood_ambushAI::UpdateAI(), npc_yenniku::npc_yennikuAI::UpdateAI(), npc_calvin_montague::npc_calvin_montagueAI::UpdateAI(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_jaina_proudmoore_bfu::npc_jaina_proudmoore_bfuAI::UpdateAI(), boss_blight_worm::boss_blight_wormAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), npc_lady_sylvanas_windrunner_bfu::npc_lady_sylvanas_windrunner_bfuAI::UpdateAI(), boss_akilzon::boss_akilzonAI::UpdateAI(), boss_halazzi::boss_halazziAI::UpdateAI(), npc_halazzi_lynx::npc_halazzi_lynxAI::UpdateAI(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::UpdateAI(), boss_janalai::boss_janalaiAI::UpdateAI(), npc_janalai_hatchling::npc_janalai_hatchlingAI::UpdateAI(), boss_nalorakk::boss_nalorakkAI::UpdateAI(), boss_arlokk::boss_arlokkAI::UpdateAI(), npc_zulian_prowler::npc_zulian_prowlerAI::UpdateAI(), boss_gahzranka::boss_gahzrankaAI::UpdateAI(), boss_grilek::boss_grilekAI::UpdateAI(), boss_hakkar::boss_hakkarAI::UpdateAI(), boss_hazzarah::boss_hazzarahAI::UpdateAI(), boss_jeklik::boss_jeklikAI::UpdateAI(), boss_jindo::boss_jindoAI::UpdateAI(), npc_healing_ward::npc_healing_wardAI::UpdateAI(), npc_shade_of_jindo::npc_shade_of_jindoAI::UpdateAI(), boss_mandokir::boss_mandokirAI::UpdateAI(), npc_ohgan::npc_ohganAI::UpdateAI(), npc_vilebranch_speaker::npc_vilebranch_speakerAI::UpdateAI(), boss_marli::boss_marliAI::UpdateAI(), npc_spawn_of_marli::npc_spawn_of_marliAI::UpdateAI(), boss_renataki::boss_renatakiAI::UpdateAI(), boss_thekal::boss_thekalAI::UpdateAI(), npc_zealot_lorkhan::npc_zealot_lorkhanAI::UpdateAI(), npc_zealot_zath::npc_zealot_zathAI::UpdateAI(), boss_venoxis::boss_venoxisAI::UpdateAI(), boss_wushoolay::boss_wushoolayAI::UpdateAI(), npc_coren_direbrew::npc_coren_direbrewAI::UpdateAI(), npc_coren_direbrew_sisters::npc_coren_direbrew_sistersAI::UpdateAI(), npc_hallows_end_soh::npc_hallows_end_sohAI::UpdateAI(), boss_headless_horseman::boss_headless_horsemanAI::UpdateAI(), npc_love_in_air_hummel::npc_love_in_air_hummelAI::UpdateAI(), npc_love_in_air_hummel_helper::npc_love_in_air_hummel_helperAI::UpdateAI(), boss_azuregos::boss_azuregosAI::UpdateAI(), boss_anetheron::boss_anetheronAI::UpdateAI(), npc_towering_infernal::npc_towering_infernalAI::UpdateAI(), boss_archimonde::boss_archimondeAI::UpdateAI(), boss_azgalor::boss_azgalorAI::UpdateAI(), npc_lesser_doomguard::npc_lesser_doomguardAI::UpdateAI(), boss_kazrogal::boss_kazrogalAI::UpdateAI(), boss_rage_winterchill::boss_rage_winterchillAI::UpdateAI(), npc_giant_infernal::npc_giant_infernalAI::UpdateAI(), npc_abomination::npc_abominationAI::UpdateAI(), npc_ghoul::npc_ghoulAI::UpdateAI(), npc_necromancer::npc_necromancerAI::UpdateAI(), npc_banshee::npc_bansheeAI::UpdateAI(), npc_crypt_fiend::npc_crypt_fiendAI::UpdateAI(), npc_fel_stalker::npc_fel_stalkerAI::UpdateAI(), alliance_rifleman::alliance_riflemanAI::UpdateAI(), hyjalAI::UpdateAI(), boss_epoch::boss_epochAI::UpdateAI(), boss_infinite_corruptor::boss_infinite_corruptorAI::UpdateAI(), boss_mal_ganis::boss_mal_ganisAI::UpdateAI(), boss_meathook::boss_meathookAI::UpdateAI(), boss_salramm::boss_salrammAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), boss_captain_skarloc::boss_captain_skarlocAI::UpdateAI(), boss_epoch_hunter::boss_epoch_hunterAI::UpdateAI(), boss_lieutenant_drake::boss_lieutenant_drakeAI::UpdateAI(), boss_aeonus::boss_aeonusAI::UpdateAI(), boss_chrono_lord_deja::boss_chrono_lord_dejaAI::UpdateAI(), boss_temporus::boss_temporusAI::UpdateAI(), boss_onyxia::boss_onyxiaAI::UpdateAI(), npc_onyxian_lair_guard::npc_onyxian_lair_guardAI::UpdateAI(), npc_belnistrasz::npc_belnistraszAI::UpdateAI(), boss_ayamiss::boss_ayamissAI::UpdateAI(), boss_buru::boss_buruAI::UpdateAI(), boss_kurinnaxx::boss_kurinnaxxAI::UpdateAI(), boss_moam::boss_moamAI::UpdateAI(), boss_ossirian::boss_ossirianAI::UpdateAI(), boss_rajaxx::boss_rajaxxAI::UpdateAI(), boss_kri::boss_kriAI::UpdateAI(), boss_vem::boss_vemAI::UpdateAI(), boss_yauj::boss_yaujAI::UpdateAI(), npc_claw_tentacle::claw_tentacleAI::UpdateAI(), npc_giant_claw_tentacle::giant_claw_tentacleAI::UpdateAI(), boss_fankriss::boss_fankrissAI::UpdateAI(), boss_huhuran::boss_huhuranAI::UpdateAI(), boss_ouro::boss_ouroAI::UpdateAI(), boss_sartura::boss_sarturaAI::UpdateAI(), npc_sartura_royal_guard::npc_sartura_royal_guardAI::UpdateAI(), boss_skeram::boss_skeramAI::UpdateAI(), boss_veknilash::boss_veknilashAI::UpdateAI(), boss_viscidus::boss_viscidusAI::UpdateAI(), npc_muglash::npc_muglashAI::UpdateAI(), npc_spitelashes::npc_spitelashesAI::UpdateAI(), npc_death_ravager::npc_death_ravagerAI::UpdateAI(), npc_murkdeep::npc_murkdeepAI::UpdateAI(), npc_tiger_matriarch::npc_tiger_matriarchAI::UpdateAI(), npc_shay_leafrunner::npc_shay_leafrunnerAI::UpdateAI(), npc_omen::npc_omenAI::UpdateAI(), npc_shenthul::npc_shenthulAI::UpdateAI(), npc_thrall_warchief::npc_thrall_warchiefAI::UpdateAI(), npc_qiraj_war_spawn::npc_qiraj_war_spawnAI::UpdateAI(), npc_aquementas::npc_aquementasAI::UpdateAI(), npc_taskmaster_fizzule::npc_taskmaster_fizzuleAI::UpdateAI(), npc_plucky::npc_pluckyAI::UpdateAI(), npc_cairne_bloodhoof::npc_cairne_bloodhoofAI::UpdateAI(), npc_sergeant_bly::npc_sergeant_blyAI::UpdateAI(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::UpdateAI(), boss_elder_nadox::boss_elder_nadoxAI::UpdateAI(), npc_ahnkahar_nerubian::npc_ahnkahar_nerubianAI::UpdateAI(), boss_volazj::boss_volazjAI::UpdateAI(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::UpdateAI(), npc_twilight_volunteer::npc_twilight_volunteerAI::UpdateAI(), boss_taldaram::boss_taldaramAI::UpdateAI(), boss_anub_arak::boss_anub_arakAI::UpdateAI(), boss_hadronox::boss_hadronoxAI::UpdateAI(), npc_anub_ar_crusher::npc_anub_ar_crusherAI::UpdateAI(), boss_krik_thir::boss_krik_thirAI::UpdateAI(), boss_sartharion::boss_sartharionAI::UpdateAI(), npc_twilight_summon::npc_twilight_summonAI::UpdateAI(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::UpdateAI(), npc_baltharus_the_warborn_clone::npc_baltharus_the_warborn_cloneAI::UpdateAI(), boss_general_zarithrian::boss_general_zarithrianAI::UpdateAI(), boss_halion::boss_halionAI::UpdateAI(), boss_twilight_halion::boss_twilight_halionAI::UpdateAI(), boss_saviana_ragefire::boss_saviana_ragefireAI::UpdateAI(), boss_eadric::boss_eadricAI::UpdateAI(), boss_paletress::boss_paletressAI::UpdateAI(), npc_memory::npc_memoryAI::UpdateAI(), npc_argent_soldier::npc_argent_soldierAI::UpdateAI(), boss_black_knight::boss_black_knightAI::UpdateAI(), npc_black_knight_ghoul::npc_black_knight_ghoulAI::UpdateAI(), boss_grand_champion::boss_grand_championAI::UpdateAI(), boss_anubarak_trial::boss_anubarak_trialAI::UpdateAI(), npc_swarm_scarab::npc_swarm_scarabAI::UpdateAI(), npc_nerubian_burrower::npc_nerubian_burrowerAI::UpdateAI(), npc_toc_druid::npc_toc_druidAI::UpdateAI(), npc_toc_shaman::npc_toc_shamanAI::UpdateAI(), npc_toc_paladin::npc_toc_paladinAI::UpdateAI(), npc_toc_priest::npc_toc_priestAI::UpdateAI(), npc_toc_shadow_priest::npc_toc_shadow_priestAI::UpdateAI(), npc_toc_warlock::npc_toc_warlockAI::UpdateAI(), npc_toc_mage::npc_toc_mageAI::UpdateAI(), npc_toc_boomkin::npc_toc_boomkinAI::UpdateAI(), npc_toc_warrior::npc_toc_warriorAI::UpdateAI(), npc_toc_dk::npc_toc_dkAI::UpdateAI(), npc_toc_rogue::npc_toc_rogueAI::UpdateAI(), npc_toc_enh_shaman::npc_toc_enh_shamanAI::UpdateAI(), npc_toc_retro_paladin::npc_toc_retro_paladinAI::UpdateAI(), npc_toc_pet_warlock::npc_toc_pet_warlockAI::UpdateAI(), npc_toc_pet_hunter::npc_toc_pet_hunterAI::UpdateAI(), boss_jaraxxus::boss_jaraxxusAI::UpdateAI(), npc_fel_infernal::npc_fel_infernalAI::UpdateAI(), npc_mistress_of_pain::npc_mistress_of_painAI::UpdateAI(), npc_snobold_vassal::npc_snobold_vassalAI::UpdateAI(), boss_gormok::boss_gormokAI::UpdateAI(), boss_jormungarAI::UpdateAI(), boss_icehowl::boss_icehowlAI::UpdateAI(), boss_dred::boss_dredAI::UpdateAI(), boss_tharon_ja::boss_tharon_jaAI::UpdateAI(), boss_trollgore::boss_trollgoreAI::UpdateAI(), boss_bronjahm::boss_bronjahmAI::UpdateAI(), boss_devourer_of_souls::boss_devourer_of_soulsAI::UpdateAI(), npc_fos_leader::npc_fos_leaderAI::UpdateAI(), boss_falric::boss_falricAI::UpdateAI(), boss_marwyn::boss_marwynAI::UpdateAI(), npc_ghostly_priest::npc_ghostly_priestAI::UpdateAI(), npc_phantom_mage::npc_phantom_mageAI::UpdateAI(), npc_shadowy_mercenary::npc_shadowy_mercenaryAI::UpdateAI(), npc_spectral_footman::npc_spectral_footmanAI::UpdateAI(), boss_frostsworn_general::boss_frostsworn_generalAI::UpdateAI(), npc_hor_spiritual_reflection::npc_hor_spiritual_reflectionAI::UpdateAI(), npc_hor_risen_witch_doctor::npc_hor_risen_witch_doctorAI::UpdateAI(), npc_hor_lumbering_abomination::npc_hor_lumbering_abominationAI::UpdateAI(), boss_garfrost::boss_garfrostAI::UpdateAI(), boss_ick::boss_ickAI::UpdateAI(), boss_tyrannus::boss_tyrannusAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI::UpdateAI(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::UpdateAI(), boss_drakkari_colossus::boss_drakkari_colossusAI::UpdateAI(), boss_drakkari_elemental::boss_drakkari_elementalAI::UpdateAI(), npc_living_mojo::npc_living_mojoAI::UpdateAI(), boss_eck::boss_eckAI::UpdateAI(), boss_gal_darah::boss_gal_darahAI::UpdateAI(), boss_moorabi::boss_moorabiAI::UpdateAI(), boss_slad_ran::boss_slad_ranAI::UpdateAI(), boss_prince_taldaram_icc::boss_prince_taldaramAI::UpdateAI(), boss_prince_valanar_icc::boss_prince_valanarAI::UpdateAI(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::UpdateAI(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::UpdateAI(), boss_festergut::boss_festergutAI::UpdateAI(), npc_stinky_icc::npc_stinky_iccAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), npc_gunship_boarding_leader::npc_gunship_boarding_leaderAI::UpdateAI(), npc_gunship_boarding_add::npc_gunship_boarding_add_realAI::UpdateAI(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::UpdateAI(), npc_cult_fanatic::npc_cult_fanaticAI::UpdateAI(), npc_cult_adherent::npc_cult_adherentAI::UpdateAI(), npc_vengeful_shade::npc_vengeful_shadeAI::UpdateAI(), npc_darnavan::npc_darnavanAI::UpdateAI(), boss_lord_marrowgar::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), npc_putricide_oozeAI::UpdateAI(), boss_rotface::boss_rotfaceAI::UpdateAI(), npc_little_ooze::npc_little_oozeAI::UpdateAI(), npc_big_ooze::npc_big_oozeAI::UpdateAI(), npc_precious_icc::npc_precious_iccAI::UpdateAI(), boss_sindragosa::boss_sindragosaAI::UpdateAI(), npc_spinestalker::npc_spinestalkerAI::UpdateAI(), npc_rimefang::npc_rimefangAI::UpdateAI(), npc_sindragosa_trash::npc_sindragosa_trashAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI(), npc_shambling_horror_icc::npc_shambling_horror_iccAI::UpdateAI(), npc_raging_spirit::npc_raging_spiritAI::UpdateAI(), npc_terenas_menethil::npc_terenas_menethilAI::UpdateAI(), npc_spirit_warden::npc_spirit_wardenAI::UpdateAI(), npc_risen_archmage::npc_risen_archmageAI::UpdateAI(), npc_blazing_skeleton::npc_blazing_skeletonAI::UpdateAI(), npc_blistering_zombie::npc_blistering_zombieAI::UpdateAI(), npc_gluttonous_abomination::npc_gluttonous_abominationAI::UpdateAI(), npc_rotting_frost_giant::npc_rotting_frost_giantAI::UpdateAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI(), boss_sister_svalna::boss_sister_svalnaAI::UpdateAI(), npc_captain_arnath::npc_captain_arnathAI::UpdateAI(), npc_captain_brandon::npc_captain_brandonAI::UpdateAI(), npc_captain_grondel::npc_captain_grondelAI::UpdateAI(), npc_captain_rupert::npc_captain_rupertAI::UpdateAI(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::UpdateAI(), npc_icc_skybreaker_hierophant::npc_icc_skybreaker_hierophantAI::UpdateAI(), npc_icc_skybreaker_vicar::npc_icc_skybreaker_vicarAI::UpdateAI(), npc_icc_skybreaker_luminary::npc_icc_skybreaker_luminaryAI::UpdateAI(), npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::UpdateAI(), npc_icc_severed_essence::npc_icc_severed_essenceAI::UpdateAI(), npc_icc_spire_frostwyrm::npc_icc_spire_frostwyrmAI::UpdateAI(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::UpdateAI(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::UpdateAI(), boss_isle_of_conquest::boss_isle_of_conquestAI::UpdateAI(), boss_anubrekhan::boss_anubrekhanAI::UpdateAI(), boss_faerlina::boss_faerlinaAI::UpdateAI(), boss_four_horsemen::boss_four_horsemenAI::UpdateAI(), boss_gluth::boss_gluthAI::UpdateAI(), boss_gothik::boss_gothikAI::UpdateAI(), npc_boss_gothik_minion::npc_boss_gothik_minionAI::UpdateAI(), boss_grobbulus::boss_grobbulusAI::UpdateAI(), boss_heigan::boss_heiganAI::UpdateAI(), boss_kelthuzad::boss_kelthuzadAI::UpdateAI(), boss_kelthuzad_minion::boss_kelthuzad_minionAI::UpdateAI(), boss_loatheb::boss_loathebAI::UpdateAI(), boss_maexxna::boss_maexxnaAI::UpdateAI(), boss_noth::boss_nothAI::UpdateAI(), boss_patchwerk::boss_patchwerkAI::UpdateAI(), boss_razuvious::boss_razuviousAI::UpdateAI(), boss_razuvious_minion::boss_razuvious_minionAI::UpdateAI(), boss_sapphiron::boss_sapphironAI::UpdateAI(), boss_thaddius::boss_thaddiusAI::UpdateAI(), boss_thaddius_summon::boss_thaddius_summonAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_nexus_lord::npc_nexus_lordAI::UpdateAI(), boss_anomalus::boss_anomalusAI::UpdateAI(), boss_commander_stoutbeard::boss_commander_stoutbeardAI::UpdateAI(), boss_keristrasza::boss_keristraszaAI::UpdateAI(), boss_magus_telestra::boss_magus_telestraAI::UpdateAI(), boss_ormorok::boss_ormorokAI::UpdateAI(), boss_drakos::boss_drakosAI::UpdateAI(), boss_eregos::boss_eregosAI::UpdateAI(), boss_urom::boss_uromAI::UpdateAI(), boss_varos::boss_varosAI::UpdateAI(), npc_stormforged_lieutenant::npc_stormforged_lieutenantAI::UpdateAI(), boss_ionar::boss_ionarAI::UpdateAI(), boss_loken::boss_lokenAI::UpdateAI(), boss_volkhan::boss_volkhanAI::UpdateAI(), npc_molten_golem::npc_molten_golemAI::UpdateAI(), npc_hol_monument::npc_hol_monumentAI::UpdateAI(), boss_krystallus::boss_krystallusAI::UpdateAI(), boss_maiden_of_grief::boss_maiden_of_griefAI::UpdateAI(), boss_sjonnir::boss_sjonnirAI::UpdateAI(), boss_sjonnir_iron_sludge::boss_sjonnir_iron_sludgeAI::UpdateAI(), boss_algalon_the_observer::boss_algalon_the_observerAI::UpdateAI(), boss_steelbreaker::boss_steelbreakerAI::UpdateAI(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::UpdateAI(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI(), boss_auriaya::boss_auriayaAI::UpdateAI(), npc_auriaya_sanctum_sentry::npc_auriaya_sanctum_sentryAI::UpdateAI(), npc_auriaya_feral_defender::npc_auriaya_feral_defenderAI::UpdateAI(), boss_freya::boss_freyaAI::UpdateAI(), boss_freya_elder_stonebark::boss_freya_elder_stonebarkAI::UpdateAI(), boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI::UpdateAI(), boss_freya_elder_ironbranch::boss_freya_elder_ironbranchAI::UpdateAI(), boss_freya_summons::boss_freya_summonsAI::UpdateAI(), boss_vezax::boss_vezaxAI::UpdateAI(), npc_ulduar_saronite_animus::npc_ulduar_saronite_animusAI::UpdateAI(), boss_hodir::boss_hodirAI::UpdateAI(), npc_ulduar_iron_construct::npc_ulduar_iron_constructAI::UpdateAI(), boss_ignis::boss_ignisAI::UpdateAI(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::UpdateAI(), boss_razorscale::boss_razorscaleAI::UpdateAI(), npc_ulduar_dark_rune_guardian::npc_ulduar_dark_rune_guardianAI::UpdateAI(), npc_ulduar_dark_rune_watcher::npc_ulduar_dark_rune_watcherAI::UpdateAI(), npc_ulduar_dark_rune_sentinel::npc_ulduar_dark_rune_sentinelAI::UpdateAI(), boss_thorim::boss_thorimAI::UpdateAI(), boss_thorim_start_npcs::boss_thorim_start_npcsAI::UpdateAI(), boss_thorim_gauntlet_npcs::boss_thorim_gauntlet_npcsAI::UpdateAI(), boss_thorim_runic_colossus::boss_thorim_runic_colossusAI::UpdateAI(), boss_thorim_ancient_rune_giant::boss_thorim_ancient_rune_giantAI::UpdateAI(), boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::UpdateAI(), boss_xt002::boss_xt002AI::UpdateAI(), npc_xt002_pummeller::npc_xt002_pummellerAI::UpdateAI(), boss_yoggsaron_guardian_of_ys::boss_yoggsaron_guardian_of_ysAI::UpdateAI(), boss_yoggsaron_immortal_guardian::boss_yoggsaron_immortal_guardianAI::UpdateAI(), npc_ulduar_storm_tempered_keeper::npc_ulduar_storm_tempered_keeperAI::UpdateAI(), npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI::UpdateAI(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::UpdateAI(), boss_keleseth::boss_kelesethAI::UpdateAI(), npc_vrykul_skeleton::npc_vrykul_skeletonAI::UpdateAI(), boss_skarvald_the_constructor::boss_skarvald_the_constructorAI::UpdateAI(), boss_dalronn_the_controller::boss_dalronn_the_controllerAI::UpdateAI(), npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI::UpdateAI(), boss_palehoof::boss_palehoofAI::UpdateAI(), npc_massive_jormungar::npc_massive_jormungarAI::UpdateAI(), npc_ferocious_rhino::npc_ferocious_rhinoAI::UpdateAI(), npc_ravenous_furbolg::npc_ravenous_furbolgAI::UpdateAI(), npc_frenzied_worgen::npc_frenzied_worgenAI::UpdateAI(), boss_skadi::boss_skadiAI::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), boss_ymiron::boss_ymironAI::UpdateAI(), boss_archavon::boss_archavonAI::UpdateAI(), boss_emalon::boss_emalonAI::UpdateAI(), boss_koralon::boss_koralonAI::UpdateAI(), boss_toravon::boss_toravonAI::UpdateAI(), boss_cyanigosa::boss_cyanigosaAI::UpdateAI(), boss_erekem::boss_erekemAI::UpdateAI(), npc_erekem_guard::npc_erekem_guardAI::UpdateAI(), boss_lavanthor::boss_lavanthorAI::UpdateAI(), boss_moragg::boss_moraggAI::UpdateAI(), boss_xevozz::boss_xevozzAI::UpdateAI(), boss_zuramat::boss_zuramatAI::UpdateAI(), npc_azure_invader::npc_azure_invaderAI::UpdateAI(), npc_azure_binder::npc_azure_binderAI::UpdateAI(), npc_azure_mage_slayer::npc_azure_mage_slayerAI::UpdateAI(), npc_azure_raider::npc_azure_raiderAI::UpdateAI(), npc_azure_stalker::npc_azure_stalkerAI::UpdateAI(), npc_azure_spellbreaker::npc_azure_spellbreakerAI::UpdateAI(), npc_azure_captain::npc_azure_captainAI::UpdateAI(), npc_azure_sorceror::npc_azure_sorcerorAI::UpdateAI(), npc_beryl_sorcerer::npc_beryl_sorcererAI::UpdateAI(), npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI::UpdateAI(), npc_hidden_cultist::npc_hidden_cultistAI::UpdateAI(), npc_bloodmage_laurith::npc_bloodmage_laurithAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_counselor_talbot::npc_counselor_talbotAI::UpdateAI(), npc_dalaran_mage::npc_dalaran_mageAI::UpdateAI(), npc_dalaran_warrior::npc_dalaran_warriorAI::UpdateAI(), npc_q24545_vegard::npc_q24545_vegardAI::UpdateAI(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::UpdateAI(), npc_torturer_lecraft::npc_torturer_lecraftAI::UpdateAI(), npc_venture_co_straggler::npc_venture_co_stragglerAI::UpdateAI(), npc_your_inner_turmoil::npc_your_inner_turmoilAI::UpdateAI(), npc_iron_watcher::npc_iron_watcherAI::UpdateAI(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::UpdateAI(), boss_exarch_maladaar::boss_exarch_maladaarAI::UpdateAI(), npc_stolen_soul::npc_stolen_soulAI::UpdateAI(), boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI::UpdateAI(), boss_nexusprince_shaffar::boss_nexusprince_shaffarAI::UpdateAI(), npc_yor::npc_yorAI::UpdateAI(), boss_pandemonius::boss_pandemoniusAI::UpdateAI(), boss_talon_king_ikiss::boss_talon_king_ikissAI::UpdateAI(), boss_anzu::boss_anzuAI::UpdateAI(), boss_ambassador_hellmaw::boss_ambassador_hellmawAI::UpdateAI(), boss_blackheart_the_inciter::boss_blackheart_the_inciterAI::UpdateAI(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::UpdateAI(), boss_murmur::boss_murmurAI::UpdateAI(), boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI::UpdateAI(), boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI(), boss_mother_shahraz::boss_shahrazAI::UpdateAI(), boss_essence_of_suffering::boss_essence_of_sufferingAI::UpdateAI(), boss_essence_of_desire::boss_essence_of_desireAI::UpdateAI(), boss_essence_of_anger::boss_essence_of_angerAI::UpdateAI(), boss_shade_of_akama::boss_shade_of_akamaAI::UpdateAI(), npc_akama_shade::npc_akamaAI::UpdateAI(), boss_supremus::boss_supremusAI::UpdateAI(), boss_teron_gorefiend::boss_teron_gorefiendAI::UpdateAI(), boss_najentus::boss_najentusAI::UpdateAI(), boss_gathios_the_shatterer::boss_gathios_the_shattererAI::UpdateAI(), boss_high_nethermancer_zerevor::boss_high_nethermancer_zerevorAI::UpdateAI(), boss_veras_darkshadow::boss_veras_darkshadowAI::UpdateAI(), boss_doomlord_kazzak::boss_doomlordkazzakAI::UpdateAI(), boss_doomwalker::boss_doomwalkerAI::UpdateAI(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::UpdateAI(), boss_hydross_the_unstable::boss_hydross_the_unstableAI::UpdateAI(), boss_lady_vashj::boss_lady_vashjAI::UpdateAI(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::UpdateAI(), npc_inner_demon::npc_inner_demonAI::UpdateAI(), boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI::UpdateAI(), boss_ahune::boss_ahuneAI::UpdateAI(), boss_hydromancer_thespia::boss_thespiaAI::UpdateAI(), boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI::UpdateAI(), npc_steamrigger_mechanic::npc_steamrigger_mechanicAI::UpdateAI(), boss_warlord_kalithresh::boss_warlord_kalithreshAI::UpdateAI(), boss_the_black_stalker::boss_the_black_stalkerAI::UpdateAI(), boss_gruul::boss_gruulAI::UpdateAI(), boss_high_king_maulgar::boss_high_king_maulgarAI::UpdateAI(), boss_olm_the_summoner::boss_olm_the_summonerAI::UpdateAI(), boss_kiggler_the_crazed::boss_kiggler_the_crazedAI::UpdateAI(), boss_blindeye_the_seer::boss_blindeye_the_seerAI::UpdateAI(), boss_krosh_firehand::boss_krosh_firehandAI::UpdateAI(), boss_broggok::boss_broggokAI::UpdateAI(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::UpdateAI(), npc_shadowmoon_channeler::npc_shadowmoon_channelerAI::UpdateAI(), boss_the_maker::boss_the_makerAI::UpdateAI(), boss_omor_the_unscarred::boss_omor_the_unscarredAI::UpdateAI(), boss_nazan::boss_nazanAI::UpdateAI(), boss_vazruden::boss_vazrudenAI::UpdateAI(), boss_watchkeeper_gargolmar::boss_watchkeeper_gargolmarAI::UpdateAI(), boss_magtheridon::boss_magtheridonAI::UpdateAI(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::UpdateAI(), boss_warbringer_omrogg::boss_warbringer_omroggAI::UpdateAI(), boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI::UpdateAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::UpdateAI(), boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI::UpdateAI(), boss_harbinger_skyriss::boss_harbinger_skyrissAI::UpdateAI(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::UpdateAI(), boss_zereketh_the_unbound::boss_zereketh_the_unboundAI::UpdateAI(), boss_commander_sarannis::boss_commander_sarannisAI::UpdateAI(), boss_high_botanist_freywinn::boss_high_botanist_freywinnAI::UpdateAI(), boss_laj::boss_lajAI::UpdateAI(), boss_thorngrin_the_tender::boss_thorngrin_the_tenderAI::UpdateAI(), boss_warp_splinter::boss_warp_splinterAI::UpdateAI(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::UpdateAI(), boss_kaelthas::boss_kaelthasAI::UpdateAI(), boss_void_reaver::boss_void_reaverAI::UpdateAI(), boss_gatewatcher_gyrokill::boss_gatewatcher_gyrokillAI::UpdateAI(), boss_gatewatcher_iron_hand::boss_gatewatcher_iron_handAI::UpdateAI(), boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI::UpdateAI(), boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI::UpdateAI(), npc_ragin_flames::npc_ragin_flamesAI::UpdateAI(), boss_pathaleon_the_calculator::boss_pathaleon_the_calculatorAI::UpdateAI(), npc_nether_drake::npc_nether_drakeAI::UpdateAI(), npc_aeranas::npc_aeranasAI::UpdateAI(), npc_fel_guard_hound::npc_fel_guard_houndAI::UpdateAI(), npc_maghar_captive::npc_maghar_captiveAI::UpdateAI(), adyen_the_lightbringer::adyen_the_lightbringerAI::UpdateAI(), anchorite_karja::anchorite_karjaAI::UpdateAI(), exarch_orelis::exarch_orelisAI::UpdateAI(), socrethar::socretharAI::UpdateAI(), kaylaan_the_lost::kaylaan_the_lostAI::UpdateAI(), npc_captain_saeed::npc_captain_saeedAI::UpdateAI(), npc_phase_hunter::npc_phase_hunterAI::UpdateAI(), npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::UpdateAI(), npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI::UpdateAI(), npc_dragonmaw_peon::npc_dragonmaw_peonAI::UpdateAI(), npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::UpdateAI(), npc_illidari_spawn::npc_illidari_spawnAI::UpdateAI(), npc_raliq_the_drunk::npc_raliq_the_drunkAI::UpdateAI(), npc_salsalabim::npc_salsalabimAI::UpdateAI(), npc_ishanah::ishanahAI::UpdateAI(), npc_unkor_the_ruthless::npc_unkor_the_ruthlessAI::UpdateAI(), npc_floon::npc_floonAI::UpdateAI(), npc_cooshcoosh::npc_cooshcooshAI::UpdateAI(), npc_pet_hunter_snake_trap::UpdateAI(), npc_pet_shaman_earth_elemental::UpdateAI(), npc_pet_shaman_fire_elemental::UpdateAI(), emerald_dragonAI::UpdateAI(), guard_shattrath_scryer::guard_shattrath_scryerAI::UpdateAI(), guard_shattrath_aldor::guard_shattrath_aldorAI::UpdateAI(), npc_artorius::npc_artoriusAI::UpdateAI(), npc_simone::npc_simoneAI::UpdateAI(), npc_nelson::npc_nelsonAI::UpdateAI(), npc_franklin::npc_franklinAI::UpdateAI(), npc_chicken_cluck::npc_chicken_cluckAI::UpdateAI(), npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI::UpdateAI(), npc_tyrion_spybot::npc_tyrion_spybotAI::UpdateAI(), boss_ichoron::boss_ichoronAI::UpdateAI(), npc_maxx_a_million_escort::npc_maxx_a_million_escortAI::UpdateAI(), AggressorAI::UpdateAI(), PossessedAI::UpdateAI(), npc_greengill_slave::npc_greengill_slaveAI::UpdateAI(), npc_marzon_silent_blade::npc_marzon_silent_bladeAI::UpdateAI(), boss_hexlord_addAI::UpdateAI(), npc_zelfrax::npc_zelfraxAI::UpdateAI(), npc_enraged_panther::npc_enraged_pantherAI::UpdateAI(), npc_hor_raging_ghoul::npc_hor_raging_ghoulAI::UpdateAI(), npc_centrifuge_construct::npc_centrifuge_constructAI::UpdateAI(), npc_xt002_life_spark::npc_xt002_life_sparkAI::UpdateAI(), boss_yoggsaron_crusher_tentacle::boss_yoggsaron_crusher_tentacleAI::UpdateAI(), npc_future_you::npc_future_youAI::UpdateAI(), npc_tallhorn_stag::npc_tallhorn_stagAI::UpdateAI(), npc_wounded_skirmisher::npc_wounded_skirmisherAI::UpdateAI(), npc_bushwhacker::npc_bushwhackerAI::UpdateAI(), npc_infernal_attacker::npc_infernal_attackerAI::UpdateAI(), npc_precious::npc_preciousAI::UpdateAI(), npc_escortAI::UpdateEscortAI(), npc_rinji::npc_rinjiAI::UpdateEscortAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateEscortAI(), npc_cork_gizelton::npc_cork_gizeltonAI::UpdateEscortAI(), npc_wizzlecrank_shredder::npc_wizzlecrank_shredderAI::UpdateEscortAI(), npc_onyx_flamecaller::npc_onyx_flamecallerAI::UpdateEscortAI(), boss_bjarngrim::boss_bjarngrimAI::UpdateEscortAI(), npc_apothecary_hanes::npc_Apothecary_HanesAI::UpdateEscortAI(), npc_time_lost_proto_drake::npc_time_lost_proto_drakeAI::UpdateEscortAI(), npc_akama_illidan::npc_akama_illidanAI::UpdateEscortAI(), npc_kurenai_captive::npc_kurenai_captiveAI::UpdateEscortAI(), npc_isla_starmane::npc_isla_starmaneAI::UpdateEscortAI(), npc_bonker_togglevolt::npc_bonker_togglevoltAI::UpdateEscortAI(), npc_kerlonian::npc_kerlonianAI::UpdateFollowerAI(), npc_tooga::npc_toogaAI::UpdateFollowerAI(), npc_ringo::npc_ringoAI::UpdateFollowerAI(), and FollowerAI::UpdateFollowerAI().
DoSpellAttackIfReady()
bool UnitAI::DoSpellAttackIfReady (uint32 spell)
Definition at line 75 of file UnitAI.cpp.
 {
     if (me->HasUnitState(UNIT_STATE_CASTING) || !me->isAttackReady())
         return true;
     if (SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(spell))
     {
         if (me->IsWithinCombatRange(me->GetVictim(), spellInfo->GetMaxRange(false)))
         {
             me->CastSpell(me->GetVictim(), spell, false);
             me->resetAttackTimer();
             return true;
         }
     }
     return false;
 }
References Unit::CastSpell(), Unit::GetVictim(), Unit::HasUnitState(), Unit::isAttackReady(), Unit::IsWithinCombatRange(), me, Unit::resetAttackTimer(), sSpellMgr, and UNIT_STATE_CASTING.
Referenced by ArcherAI::UpdateAI(), TurretAI::UpdateAI(), boss_jormungarAI::UpdateAI(), npc_tortured_rifleman::npc_tortured_riflemanAI::UpdateAI(), boss_prince_keleseth_icc::boss_prince_kelesethAI::UpdateAI(), npc_gunship_gunner::npc_gunship_gunnerAI::UpdateAI(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::UpdateAI(), npc_icc_skybreaker_marksman::npc_icc_skybreaker_marksmanAI::UpdateAI(), npc_pet_gen_valkyr_guardian::UpdateAI(), boss_sjonnir_dwarf::boss_sjonnir_dwarfAI::UpdateAI(), and npc_pet_gen_gnomish_flame_turret::UpdateAI().
FillAISpellInfo()
void UnitAI::FillAISpellInfo () static
Definition at line 223 of file UnitAI.cpp.
 {
     AISpellInfo = new AISpellInfoType[sSpellMgr->GetSpellInfoStoreSize()];
     AISpellInfoType* AIInfo = AISpellInfo;
     const SpellInfo* spellInfo;
     for (uint32 i = 0; i < sSpellMgr->GetSpellInfoStoreSize(); ++i, ++AIInfo)
     {
         spellInfo = sSpellMgr->GetSpellInfo(i);
         if (!spellInfo)
             continue;
         if (spellInfo->HasAttribute(SPELL_ATTR0_ALLOW_CAST_WHILE_DEAD))
             AIInfo->condition = AICOND_DIE;
         else if (spellInfo->IsPassive() || spellInfo->GetDuration() == -1)
             AIInfo->condition = AICOND_AGGRO;
         else
             AIInfo->condition = AICOND_COMBAT;
         if (AIInfo->cooldown < spellInfo->RecoveryTime)
             AIInfo->cooldown = spellInfo->RecoveryTime;
         if (!spellInfo->GetMaxRange(false))
             UPDATE_TARGET(AITARGET_SELF)
             else
             {
                 for (uint32 j = 0; j < MAX_SPELL_EFFECTS; ++j)
                 {
                     uint32 targetType = spellInfo->Effects[j].TargetA.GetTarget();
                     if (targetType == TARGET_UNIT_TARGET_ENEMY
                             || targetType == TARGET_DEST_TARGET_ENEMY)
                         UPDATE_TARGET(AITARGET_VICTIM)
                         else if (targetType == TARGET_UNIT_DEST_AREA_ENEMY)
                             UPDATE_TARGET(AITARGET_ENEMY)
                             if (spellInfo->Effects[j].Effect == SPELL_EFFECT_APPLY_AURA)
{
                                 if (targetType == TARGET_UNIT_TARGET_ENEMY)
                                     UPDATE_TARGET(AITARGET_DEBUFF)
                                     else if (spellInfo->IsPositive())
                                         UPDATE_TARGET(AITARGET_BUFF)
                                     }
                 }
             }
         AIInfo->realCooldown = spellInfo->RecoveryTime + spellInfo->StartRecoveryTime;
         AIInfo->maxRange = spellInfo->GetMaxRange(false) * 3 / 4;
     }
 }
References AICOND_AGGRO, AICOND_COMBAT, AICOND_DIE, AISpellInfo, AITARGET_BUFF, AITARGET_DEBUFF, AITARGET_ENEMY, AITARGET_SELF, AITARGET_VICTIM, AISpellInfoType::condition, AISpellInfoType::cooldown, SpellInfo::Effects, SpellInfo::GetDuration(), SpellInfo::GetMaxRange(), SpellInfo::HasAttribute(), SpellInfo::IsPassive(), SpellInfo::IsPositive(), MAX_SPELL_EFFECTS, AISpellInfoType::maxRange, AISpellInfoType::realCooldown, SpellInfo::RecoveryTime, SPELL_ATTR0_ALLOW_CAST_WHILE_DEAD, SPELL_EFFECT_APPLY_AURA, sSpellMgr, SpellInfo::StartRecoveryTime, TARGET_DEST_TARGET_ENEMY, TARGET_UNIT_DEST_AREA_ENEMY, TARGET_UNIT_TARGET_ENEMY, and UPDATE_TARGET.
Referenced by ScriptMgr::FillSpellSummary().
GetData()
virtual uint32 UnitAI::GetData (uint32) const inline virtual
Reimplemented in npc_natrualist_bite::npc_natrualist_biteAI, npc_ulduar_vx001::npc_ulduar_vx001AI, npc_living_constellation::npc_living_constellationAI, boss_gal_darah::boss_gal_darahAI, npc_hallows_end_soh::npc_hallows_end_sohAI, npc_wormhole::npc_wormholeAI, npc_riggle_bassbait::npc_riggle_bassbaitAI, npc_elder_clearwater::npc_elder_clearwaterAI, npc_valithria_portal::npc_valithria_portalAI, boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI, boss_the_lich_king::boss_the_lich_kingAI, npc_sindragosa_trash::npc_sindragosa_trashAI, boss_sindragosa::boss_sindragosaAI, boss_professor_putricide::boss_professor_putricideAI, boss_festergut::boss_festergutAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI, boss_elder_nadox::boss_elder_nadoxAI, boss_entropius::boss_entropiusAI, boss_darkmaster_gandling::boss_darkmaster_gandlingAI, npc_highlord_darion_mograine::npc_highlord_darion_mograineAI, npc_pet_gen_argent_pony_bridle, boss_yoggsaron_brain::boss_yoggsaron_brainAI, boss_yoggsaron::boss_yoggsaronAI, boss_yoggsaron_sara::boss_yoggsaron_saraAI, boss_xt002::boss_xt002AI, boss_thorim::boss_thorimAI, boss_kologarn::boss_kologarnAI, boss_freya::boss_freyaAI, boss_flame_leviathan::boss_flame_leviathanAI, boss_auriaya::boss_auriayaAI, boss_stormcaller_brundir::boss_stormcaller_brundirAI, boss_algalon_the_observer::boss_algalon_the_observerAI, npc_costumed_orphan_matron::npc_costumed_orphan_matronAI, SmartAI, npc_ulduar_harpoonfirestate::npc_ulduar_harpoonfirestateAI, boss_razorscale::boss_razorscaleAI, boss_mimiron::boss_mimironAI, boss_ignis::boss_ignisAI, boss_hodir::boss_hodirAI, boss_vezax::boss_vezaxAI, npc_gunship::npc_gunshipAI, boss_devourer_of_souls::boss_devourer_of_soulsAI, boss_keristrasza::boss_keristraszaAI, boss_sartharion::boss_sartharionAI, npc_captain_saeed::npc_captain_saeedAI, boss_magus_telestra::boss_magus_telestraAI, boss_anomalus::boss_anomalusAI, boss_slad_ran::boss_slad_ranAI, boss_novos::boss_novosAI, boss_dred::boss_dredAI, boss_krik_thir::boss_krik_thirAI, boss_hadronox::boss_hadronoxAI, and npc_death_knight_initiate::npc_death_knight_initiateAI.
Definition at line 197 of file UnitAI.h.
 { return 0; }
Referenced by boss_algalon_the_observer::boss_algalon_the_observerAI::CallConstellations(), instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::CheckAchievementCriteriaMeet(), spell_putricide_mutation_init::spell_putricide_mutation_init_SpellScript::CheckRequirementInternal(), spell_putricide_unstable_experiment::spell_putricide_unstable_experiment_SpellScript::HandleScript(), spell_putricide_mutated_transformation::spell_putricide_mutated_transformation_SpellScript::HandleSummon(), npc_risen_guardian::npc_risen_guardianAI::IsSummonedBy(), achievement_respect_your_elders::OnCheck(), achievement_hadronox_denied::OnCheck(), achievement_watch_him_die::OnCheck(), achievement_better_off_dred::OnCheck(), achievement_oh_novos::OnCheck(), achievement_share_the_love::OnCheck(), achievement_snakes_whyd_it_have_to_be_snakes::OnCheck(), achievement_flu_shot_shortage::OnCheck(), achievement_im_on_a_boat::OnCheck(), achievement_all_you_can_eat::OnCheck(), achievement_been_waiting_long_time::OnCheck(), achievement_neck_deep_in_vile::OnCheck(), achievement_portal_jockey::OnCheck(), achievement_chaos_theory::OnCheck(), achievement_split_personality::OnCheck(), achievement_algalon_he_feeds_on_your_tears::OnCheck(), achievement_algalon_herald_of_the_titans::OnCheck(), achievement_flame_leviathan_towers::OnCheck(), achievement_flame_leviathan_shutout::OnCheck(), achievement_freya_getting_back_to_nature::OnCheck(), achievement_freya_knock_on_wood::OnCheck(), achievement_smell_saronite::OnCheck(), achievement_shadowdodger::OnCheck(), achievement_cheese_the_freeze::OnCheck(), achievement_getting_cold_in_here::OnCheck(), achievement_i_could_say_that_this_cache_was_rare::OnCheck(), achievement_i_have_the_coolest_friends::OnCheck(), achievement_ignis_shattered::OnCheck(), achievement_mimiron_firefighter::OnCheck(), achievement_mimiron_set_up_us_the_bomb_11::OnCheck(), achievement_mimiron_set_up_us_the_bomb_12::OnCheck(), achievement_mimiron_set_up_us_the_bomb_13::OnCheck(), achievement_quick_shave::OnCheck(), achievement_yogg_saron_drive_me_crazy::OnCheck(), achievement_yogg_saron_kiss_and_make_up::OnCheck(), achievement_intense_cold::OnCheck(), npc_pet_gen_argent_pony_bridle::OnGossipHello(), npc_highlord_darion_mograine::OnGossipHello(), npc_costumed_orphan_matron::OnGossipHello(), npc_captain_saeed::OnGossipHello(), npc_natrualist_bite::OnGossipHello(), npc_elder_clearwater::OnGossipHello(), npc_riggle_bassbait::OnGossipHello(), npc_wormhole::OnGossipHello(), npc_death_knight_initiate::OnGossipSelect(), npc_natrualist_bite::OnGossipSelect(), npc_costumed_orphan_matron::OnQuestAccept(), npc_elder_clearwater::OnQuestReward(), npc_riggle_bassbait::OnQuestReward(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath(), OrderWhelpTargetSelector::operator()(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::SummonedCreatureDespawn(), and npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::UpdateAI().
GetGUID()
virtual ObjectGuid UnitAI::GetGUID (int32 = 0) const inline virtual
Reimplemented in npc_unworthy_initiate_anchor::npc_unworthy_initiate_anchorAI, SmartAI, boss_lord_marrowgar, and npc_coren_direbrew_sisters::npc_coren_direbrew_sistersAI.
Definition at line 200 of file UnitAI.h.
 { return ObjectGuid::Empty; }
References ObjectGuid::Empty.
Referenced by spell_send_mug_target_picker::spell_send_mug_target_picker_SpellScript::FilterTargets(), spell_marrowgar_bone_spike_graveyard::spell_marrowgar_bone_spike_graveyard_SpellScript::HandleSpikes(), npc_death_knight_initiate::OnGossipHello(), and boss_darkmaster_gandling::boss_darkmaster_gandlingAI::SummonedCreatureDespawn().
HealDone()
virtual void UnitAI::HealDone (Unit * , uint32 &) inline virtual
Definition at line 292 of file UnitAI.h.
 {}
Referenced by Unit::DealHeal().
HealReceived()
virtual void UnitAI::HealReceived (Unit * , uint32 &) inline virtual
Reimplemented in boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI, and SmartAI.
Definition at line 289 of file UnitAI.h.
 {}
Referenced by Unit::DealHeal().
InitializeAI()
virtual void UnitAI::InitializeAI () inline virtual
Reimplemented in npc_wormhole::npc_wormholeAI, npc_precious::npc_preciousAI, npc_pet_shaman_fire_elemental, npc_pet_shaman_earth_elemental, npc_pet_pri_lightwell, npc_pet_mage_mirror_image, npc_pet_gen_imp_in_a_bottle, npc_pet_gen_valkyr_guardian, npc_pet_dk_dancing_rune_weapon::npc_pet_dk_dancing_rune_weaponAI, npc_pet_dk_army_of_the_dead::npc_pet_dk_army_of_the_deadAI, npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI, boss_pathaleon_the_calculator::boss_pathaleon_the_calculatorAI, boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI, boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI, npc_millhouse_manastorm::npc_millhouse_manastormAI, boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI, boss_leotheras_the_blind::boss_leotheras_the_blindAI, npc_bushwhacker::npc_bushwhackerAI, npc_lord_arete::npc_lord_areteAI, npc_hourglass_of_eternity::npc_hourglass_of_eternityAI, npc_preparations_for_war_vehicle::npc_preparations_for_war_vehicleAI, boss_razorscale::boss_razorscaleAI, npc_ulduar_mimiron_rocket::npc_ulduar_mimiron_rocketAI, boss_flame_leviathan::boss_flame_leviathanAI, boss_malygos::boss_malygosAI, boss_sapphiron::boss_sapphironAI, npc_sindragosa_trash::npc_sindragosa_trashAI, npc_rimefang::npc_rimefangAI, npc_spinestalker::npc_spinestalkerAI, boss_prince_valanar_icc::boss_prince_valanarAI, boss_prince_taldaram_icc::boss_prince_taldaramAI, boss_prince_keleseth_icc::boss_prince_kelesethAI, boss_gal_darah::boss_gal_darahAI, boss_eck::boss_eckAI, boss_drakkari_colossus::boss_drakkari_colossusAI, npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI, boss_baltharus_the_warborn::boss_baltharus_the_warbornAI, boss_taldaram::boss_taldaramAI, boss_volazj::boss_volazjAI, npc_weegli_blastfuse::npc_weegli_blastfuseAI, npc_sergeant_bly::npc_sergeant_blyAI, npc_shay_leafrunner::npc_shay_leafrunnerAI, npc_troll_volunteer::npc_troll_volunteerAI, npc_cork_gizelton::npc_cork_gizeltonAI, boss_temporus::boss_temporusAI, boss_chrono_lord_deja::boss_chrono_lord_dejaAI, boss_aeonus::boss_aeonusAI, boss_lieutenant_drake::boss_lieutenant_drakeAI, boss_captain_skarloc::boss_captain_skarlocAI, npc_lady_sylvanas_windrunner_bfu::npc_lady_sylvanas_windrunner_bfuAI, boss_twilight_corrupter::boss_twilight_corrupterAI, boss_kiljaeden::boss_kiljaedenAI, npc_scarlet_ghoul::npc_scarlet_ghoulAI, npc_eye_of_acherus::npc_eye_of_acherusAI, boss_priestess_delrissa::boss_priestess_delrissaAI, boss_felblood_kaelthas::boss_felblood_kaelthasAI, boss_moroes::boss_moroesAI, boss_majordomo::boss_majordomoAI, boss_urok_doomhowl::boss_urok_doomhowlAI, boss_solakar_flamewreath::boss_solakar_flamewreathAI, npc_rookery_hatcher::npc_rookery_hatcherAI, SmartAI, CasterAI, and CombatAI.
Definition at line 188 of file UnitAI.h.
 { if (!me->isDead()) Reset(); }
References Unit::isDead(), me, and Reset().
Referenced by Creature::AIM_Initialize(), CombatAI::InitializeAI(), npc_rookery_hatcher::npc_rookery_hatcherAI::InitializeAI(), boss_solakar_flamewreath::boss_solakar_flamewreathAI::InitializeAI(), boss_urok_doomhowl::boss_urok_doomhowlAI::InitializeAI(), boss_majordomo::boss_majordomoAI::InitializeAI(), boss_moroes::boss_moroesAI::InitializeAI(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::InitializeAI(), boss_priestess_delrissa::boss_priestess_delrissaAI::InitializeAI(), npc_scarlet_ghoul::npc_scarlet_ghoulAI::InitializeAI(), boss_kiljaeden::boss_kiljaedenAI::InitializeAI(), boss_twilight_corrupter::boss_twilight_corrupterAI::InitializeAI(), boss_captain_skarloc::boss_captain_skarlocAI::InitializeAI(), boss_lieutenant_drake::boss_lieutenant_drakeAI::InitializeAI(), boss_aeonus::boss_aeonusAI::InitializeAI(), boss_chrono_lord_deja::boss_chrono_lord_dejaAI::InitializeAI(), boss_temporus::boss_temporusAI::InitializeAI(), npc_cork_gizelton::npc_cork_gizeltonAI::InitializeAI(), boss_volazj::boss_volazjAI::InitializeAI(), boss_taldaram::boss_taldaramAI::InitializeAI(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::InitializeAI(), boss_drakkari_colossus::boss_drakkari_colossusAI::InitializeAI(), boss_eck::boss_eckAI::InitializeAI(), boss_gal_darah::boss_gal_darahAI::InitializeAI(), boss_prince_keleseth_icc::boss_prince_kelesethAI::InitializeAI(), boss_prince_taldaram_icc::boss_prince_taldaramAI::InitializeAI(), boss_prince_valanar_icc::boss_prince_valanarAI::InitializeAI(), boss_sapphiron::boss_sapphironAI::InitializeAI(), boss_flame_leviathan::boss_flame_leviathanAI::InitializeAI(), npc_preparations_for_war_vehicle::npc_preparations_for_war_vehicleAI::InitializeAI(), boss_leotheras_the_blind::boss_leotheras_the_blindAI::InitializeAI(), boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI::InitializeAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::InitializeAI(), boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI::InitializeAI(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::InitializeAI(), boss_pathaleon_the_calculator::boss_pathaleon_the_calculatorAI::InitializeAI(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::InitializeAI(), npc_pet_dk_dancing_rune_weapon::npc_pet_dk_dancing_rune_weaponAI::InitializeAI(), npc_pet_gen_imp_in_a_bottle::InitializeAI(), and npc_pet_pri_lightwell::InitializeAI().
OnCharmed()
virtual void UnitAI::OnCharmed (bool apply) pure virtual
Implemented in npc_icefang::npc_icefangAI, npc_frosthound::npc_frosthoundAI, npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI, npc_assembly_lightning::npc_assembly_lightningAI, npc_strangulate_vehicle::npc_strangulate_vehicleAI, npc_valkyr_shadowguard::npc_valkyr_shadowguardAI, NullCreatureAI, npc_wild_wyrm::npc_wild_wyrmAI, npc_toc5_player_vehicle::npc_toc5_player_vehicleAI, SmartAI, CreatureAI, PlayerAI, and VehicleAI.
Reset()
virtual void UnitAI::Reset () inline virtual
Reimplemented in boss_twinemperorsAI, npc_spring_rabbit::npc_spring_rabbitAI, npc_firework::npc_fireworkAI, npc_steam_tonk::npc_steam_tonkAI, npc_guardian::npc_guardianAI, npc_garments_of_quests::npc_garments_of_questsAI, npc_injured_patient::npc_injured_patientAI, npc_doctor::npc_doctorAI, npc_dancing_flames::npc_dancing_flamesAI, npc_chicken_cluck::npc_chicken_cluckAI, npc_air_force_bots::npc_air_force_botsAI, npc_target_dummy::npc_target_dummyAI, npc_training_dummy::npc_training_dummyAI, npc_franklin::npc_franklinAI, npc_nelson::npc_nelsonAI, npc_simone::npc_simoneAI, npc_precious::npc_preciousAI, npc_artorius::npc_artoriusAI, generic_creature::generic_creatureAI, guard_shattrath_aldor::guard_shattrath_aldorAI, guard_shattrath_scryer::guard_shattrath_scryerAI, boss_taerar::boss_taerarAI, boss_emeriss::boss_emerissAI, boss_lethon::boss_lethonAI, boss_ysondre::boss_ysondreAI, npc_dream_fog::npc_dream_fogAI, emerald_dragonAI, npc_pet_pri_shadowfiend, npc_pet_mage_mirror_image, npc_pet_hunter_snake_trap, npc_pet_gen_toxic_wasteling, npc_pet_gen_gnomish_flame_turret, npc_pet_gen_argent_pony_bridle, npc_pet_gen_mojo, npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI, npc_kayra_longmane::npc_kayra_longmaneAI, npc_cooshcoosh::npc_cooshcooshAI, npc_isla_starmane::npc_isla_starmaneAI, npc_floon::npc_floonAI, npc_rotting_forest_rager::npc_rotting_forest_ragerAI, npc_infested_root_walker::npc_infested_root_walkerAI, npc_unkor_the_ruthless::npc_unkor_the_ruthlessAI, npc_kservant::npc_kservantAI, npc_salsalabim::npc_salsalabimAI, npc_raliq_the_drunk::npc_raliq_the_drunkAI, npc_shadowmoon_tuber_node::npc_shadowmoon_tuber_nodeAI, npc_enraged_spirit::npc_enraged_spiritAI, npc_illidari_spawn::npc_illidari_spawnAI, npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI, npc_torloth_the_magnificent::npc_torloth_the_magnificentAI, npc_earthmender_wilda::npc_earthmender_wildaAI, npc_dragonmaw_peon::npc_dragonmaw_peonAI, npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI, npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI, npc_infernal_attacker::npc_infernal_attackerAI, npc_invis_infernal_caster::npc_invis_infernal_casterAI, npc_maxx_a_million_escort::npc_maxx_a_million_escortAI, npc_bessy::npc_bessyAI, npc_phase_hunter::npc_phase_hunterAI, npc_commander_dawnforge::npc_commander_dawnforgeAI, npc_captain_saeed::npc_captain_saeedAI, socrethar::socretharAI, npc_kurenai_captive::npc_kurenai_captiveAI, npc_corki::npc_corkiAI, npc_creditmarker_visit_with_ancestors::npc_creditmarker_visit_with_ancestorsAI, npc_maghar_captive::npc_maghar_captiveAI, npc_fel_guard_hound::npc_fel_guard_houndAI, npc_wounded_blood_elf::npc_wounded_blood_elfAI, npc_ancestral_wolf::npc_ancestral_wolfAI, npc_aeranas::npc_aeranasAI, npc_oscillating_frequency_scanner_master_bunny::npc_oscillating_frequency_scanner_master_bunnyAI, npc_daranelle::npc_daranelleAI, npc_nether_drake::npc_nether_drakeAI, npc_deaths_fel_cannon::npc_deaths_fel_cannonAI, npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI, npc_ragin_flames::npc_ragin_flamesAI, boss_void_reaver::boss_void_reaverAI, boss_kaelthas::boss_kaelthasAI, boss_high_astromancer_solarian::boss_high_astromancer_solarianAI, boss_alar::boss_alarAI, boss_warp_splinter::boss_warp_splinterAI, boss_thorngrin_the_tender::boss_thorngrin_the_tenderAI, boss_laj::boss_lajAI, boss_high_botanist_freywinn::boss_high_botanist_freywinnAI, boss_commander_sarannis::boss_commander_sarannisAI, boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI, boss_harbinger_skyriss::boss_harbinger_skyrissAI, boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI, npc_warden_mellichar::npc_warden_mellicharAI, npc_millhouse_manastorm::npc_millhouse_manastormAI, boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI, boss_magtheridon::boss_magtheridonAI, boss_watchkeeper_gargolmar::boss_watchkeeper_gargolmarAI, boss_vazruden::boss_vazrudenAI, boss_nazan::boss_nazanAI, boss_vazruden_the_herald::boss_vazruden_the_heraldAI, boss_omor_the_unscarred::boss_omor_the_unscarredAI, boss_the_maker::boss_the_makerAI, npc_shadowmoon_channeler::npc_shadowmoon_channelerAI, boss_kelidan_the_breaker::boss_kelidan_the_breakerAI, boss_broggok::boss_broggokAI, boss_krosh_firehand::boss_krosh_firehandAI, boss_blindeye_the_seer::boss_blindeye_the_seerAI, boss_kiggler_the_crazed::boss_kiggler_the_crazedAI, boss_olm_the_summoner::boss_olm_the_summonerAI, boss_high_king_maulgar::boss_high_king_maulgarAI, boss_gruul::boss_gruulAI, boss_the_black_stalker::boss_the_black_stalkerAI, npc_naga_distiller::npc_naga_distillerAI, boss_warlord_kalithresh::boss_warlord_kalithreshAI, npc_steamrigger_mechanic::npc_steamrigger_mechanicAI, boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI, boss_hydromancer_thespia::boss_thespiaAI, boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI, boss_the_lurker_below::boss_the_lurker_belowAI, boss_leotheras_the_blind::boss_leotheras_the_blindAI, boss_lady_vashj::boss_lady_vashjAI, boss_hydross_the_unstable::boss_hydross_the_unstableAI, boss_fathomlord_karathress::boss_fathomlord_karathressAI, boss_doomwalker::boss_doomwalkerAI, boss_doomlord_kazzak::boss_doomlordkazzakAI, boss_illidari_council_memberAI, boss_illidari_council::boss_illidari_councilAI, boss_najentus::boss_najentusAI, boss_teron_gorefiend::boss_teron_gorefiendAI, boss_supremus::boss_supremusAI, npc_creature_generator_akama::npc_creature_generator_akamaAI, npc_akama_shade::npc_akamaAI, boss_shade_of_akama::boss_shade_of_akamaAI, boss_essence_of_anger::boss_essence_of_angerAI, boss_essence_of_desire::boss_essence_of_desireAI, boss_essence_of_suffering::boss_essence_of_sufferingAI, boss_reliquary_of_souls::boss_reliquary_of_soulsAI, boss_mother_shahraz::boss_shahrazAI, npc_akama_illidan::npc_akama_illidanAI, boss_illidan_stormrage::boss_illidan_stormrageAI, boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI, boss_murmur::boss_murmurAI, boss_grandmaster_vorpil::boss_grandmaster_vorpilAI, boss_blackheart_the_inciter::boss_blackheart_the_inciterAI, boss_ambassador_hellmaw::boss_ambassador_hellmawAI, boss_anzu::boss_anzuAI, boss_talon_king_ikiss::boss_talon_king_ikissAI, boss_pandemonius::boss_pandemoniusAI, npc_yor::npc_yorAI, boss_nexusprince_shaffar::boss_nexusprince_shaffarAI, boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI, npc_stolen_soul::npc_stolen_soulAI, boss_exarch_maladaar::boss_exarch_maladaarAI, npc_storm_cloud::npc_storm_cloudAI, npc_crusade_recruit::npc_crusade_recruitAI, npc_released_offspring_harkoa::npc_released_offspring_harkoaAI, npc_captured_rageclaw::npc_captured_rageclawAI, npc_drakuru_shackles::npc_drakuru_shacklesAI, npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI, npc_freed_protodrake::npc_freed_protodrakeAI, npc_brunnhildar_prisoner::npc_brunnhildar_prisonerAI, npc_wild_wyrm::npc_wild_wyrmAI, npc_time_lost_proto_drake::npc_time_lost_proto_drakeAI, npc_iron_watcher::npc_iron_watcherAI, npc_jungle_punch_target::npc_jungle_punch_targetAI, npc_engineer_helice::npc_engineer_heliceAI, npc_still_at_it_trigger::npc_still_at_it_triggerAI, npc_artruis_the_hearthless::npc_artruis_the_hearthlessAI, npc_blessed_banner::npc_blessed_bannerAI, npc_tournament_training_dummy::npc_tournament_training_dummyAI, npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI, npc_llod_generic::npc_llod_genericAI, npc_battle_at_valhalas::npc_battle_at_valhalasAI, npc_plaguehound_tracker::npc_plaguehound_trackerAI, npc_apothecary_hanes::npc_Apothecary_HanesAI, npc_your_inner_turmoil::npc_your_inner_turmoilAI, npc_lake_frog::npc_lake_frogAI, npc_venture_co_straggler::npc_venture_co_stragglerAI, npc_wounded_skirmisher::npc_wounded_skirmisherAI, npc_amberpine_woodsman::npc_amberpine_woodsmanAI, npc_tallhorn_stag::npc_tallhorn_stagAI, npc_outhouse_bunny::npc_outhouse_bunnyAI, npc_mrfloppy::npc_mrfloppyAI, npc_emily::npc_emilyAI, npc_torturer_lecraft::npc_torturer_lecraftAI, npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI, npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI, npc_q24545_lich_king::npc_q24545_lich_kingAI, npc_heated_battle::npc_heated_battleAI, npc_injured_7th_legion_soldier::npc_injured_7th_legion_soldierAI, npc_future_you::npc_future_youAI, npc_conversing_with_the_depths_trigger::npc_conversing_with_the_depths_triggerAI, npc_dalaran_warrior::npc_dalaran_warriorAI, npc_dalaran_mage::npc_dalaran_mageAI, npc_minigob_manabonk::npc_minigob_manabonkAI, npc_mageguard_dalaran::npc_mageguard_dalaranAI, npc_shandy_dalaran::npc_shandy_dalaranAI, npc_warmage_violetstand::npc_warmage_violetstandAI, npc_counselor_talbot::npc_counselor_talbotAI, npc_thassarian2::npc_thassarian2AI, npc_thassarian::npc_thassarianAI, npc_bloodmage_laurith::npc_bloodmage_laurithAI, npc_hidden_cultist::npc_hidden_cultistAI, npc_warmage_coldarra::npc_warmage_coldarraAI, npc_valiance_keep_cannoneer::npc_valiance_keep_cannoneerAI, npc_bonker_togglevolt::npc_bonker_togglevoltAI, npc_mootoo_the_younger::npc_mootoo_the_youngerAI, npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI, npc_captured_beryl_sorcerer::npc_captured_beryl_sorcererAI, npc_beryl_sorcerer::npc_beryl_sorcererAI, npc_lurgglbr::npc_lurgglbrAI, npc_sinkhole_kill_credit::npc_sinkhole_kill_creditAI, npc_azure_sorceror::npc_azure_sorcerorAI, npc_azure_captain::npc_azure_captainAI, npc_azure_spellbreaker::npc_azure_spellbreakerAI, npc_azure_stalker::npc_azure_stalkerAI, npc_azure_raider::npc_azure_raiderAI, npc_azure_mage_slayer::npc_azure_mage_slayerAI, npc_azure_binder::npc_azure_binderAI, npc_azure_invader::npc_azure_invaderAI, boss_zuramat::boss_zuramatAI, boss_xevozz::boss_xevozzAI, boss_moragg::boss_moraggAI, boss_lavanthor::boss_lavanthorAI, boss_ichoron::boss_ichoronAI, npc_erekem_guard::npc_erekem_guardAI, boss_erekem::boss_erekemAI, boss_cyanigosa::boss_cyanigosaAI, npc_frozen_orb_stalker::npc_frozen_orb_stalkerAI, npc_frozen_orb::npc_frozen_orbAI, boss_toravon::boss_toravonAI, boss_koralon::boss_koralonAI, boss_emalon::boss_emalonAI, boss_archavon::boss_archavonAI, boss_ymiron::boss_ymironAI, boss_svala::boss_svalaAI, boss_skadi_grauf::boss_skadi_graufAI, boss_skadi::boss_skadiAI, npc_frenzied_worgen::npc_frenzied_worgenAI, npc_ravenous_furbolg::npc_ravenous_furbolgAI, npc_ferocious_rhino::npc_ferocious_rhinoAI, npc_massive_jormungar::npc_massive_jormungarAI, boss_palehoof::boss_palehoofAI, npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI, npc_dragonflayer_forge_master::npc_dragonflayer_forge_masterAI, boss_dalronn_the_controller::boss_dalronn_the_controllerAI, boss_skarvald_the_constructor::boss_skarvald_the_constructorAI, npc_vrykul_skeleton::npc_vrykul_skeletonAI, boss_keleseth::boss_kelesethAI, boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI, npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI, npc_ulduar_storm_tempered_keeper::npc_ulduar_storm_tempered_keeperAI, boss_yoggsaron_voice::boss_yoggsaron_voiceAI, boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI, boss_yoggsaron_llane::boss_yoggsaron_llaneAI, boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI, boss_yoggsaron_immortal_guardian::boss_yoggsaron_immortal_guardianAI, boss_yoggsaron_crusher_tentacle::boss_yoggsaron_crusher_tentacleAI, boss_yoggsaron_brain::boss_yoggsaron_brainAI, boss_yoggsaron_guardian_of_ys::boss_yoggsaron_guardian_of_ysAI, boss_yoggsaron_cloud::boss_yoggsaron_cloudAI, boss_yoggsaron_sara::boss_yoggsaron_saraAI, npc_xt002_life_spark::npc_xt002_life_sparkAI, npc_xt002_boombot::npc_xt002_boombotAI, npc_xt002_pummeller::npc_xt002_pummellerAI, npc_xt002_scrapbot::npc_xt002_scrapbotAI, boss_xt002::boss_xt002AI, boss_thorim_arena_npcs::boss_thorim_arena_npcsAI, boss_thorim_ancient_rune_giant::boss_thorim_ancient_rune_giantAI, boss_thorim_runic_colossus::boss_thorim_runic_colossusAI, boss_thorim_gauntlet_npcs::boss_thorim_gauntlet_npcsAI, boss_thorim_start_npcs::boss_thorim_start_npcsAI, boss_thorim_pillar::boss_thorim_pillarAI, boss_thorim_sif_blizzard::boss_thorim_sif_blizzardAI, boss_thorim_trap::boss_thorim_trapAI, boss_thorim_lightning_orb::boss_thorim_lightning_orbAI, boss_thorim_sif::boss_thorim_sifAI, boss_thorim::boss_thorimAI, npc_ulduar_dark_rune_sentinel::npc_ulduar_dark_rune_sentinelAI, npc_ulduar_dark_rune_watcher::npc_ulduar_dark_rune_watcherAI, npc_ulduar_dark_rune_guardian::npc_ulduar_dark_rune_guardianAI, npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI, npc_ulduar_harpoonfirestate::npc_ulduar_harpoonfirestateAI, boss_razorscale::boss_razorscaleAI, npc_ulduar_bot_summon_trigger::npc_ulduar_bot_summon_triggerAI, npc_ulduar_mimiron_rocket::npc_ulduar_mimiron_rocketAI, npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI, npc_ulduar_vx001::npc_ulduar_vx001AI, npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI, boss_mimiron::boss_mimironAI, boss_kologarn_arms::boss_kologarn_armsAI, boss_kologarn::boss_kologarnAI, boss_ignis::boss_ignisAI, npc_ulduar_iron_construct::npc_ulduar_iron_constructAI, boss_hodir::boss_hodirAI, boss_vezax::boss_vezaxAI, boss_freya_nature_bomb::boss_freya_nature_bombAI, boss_freya_summons::boss_freya_summonsAI, boss_freya_healthy_spore::boss_freya_healthy_sporeAI, boss_freya_lifebinder::boss_freya_lifebinderAI, boss_freya_elder_ironbranch::boss_freya_elder_ironbranchAI, boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI, boss_freya_elder_stonebark::boss_freya_elder_stonebarkAI, boss_freya::boss_freyaAI, npc_mechanolift::npc_mechanoliftAI, npc_brann_radio::npc_brann_radioAI, npc_thorims_hammer::npc_thorims_hammerAI, npc_mimirons_inferno::npc_mimirons_infernoAI, npc_hodirs_fury::npc_hodirs_furyAI, npc_freya_ward::npc_freya_wardAI, boss_flame_leviathan_seat::boss_flame_leviathan_seatAI, boss_flame_leviathan::boss_flame_leviathanAI, npc_auriaya_feral_defender::npc_auriaya_feral_defenderAI, npc_auriaya_sanctum_sentry::npc_auriaya_sanctum_sentryAI, boss_auriaya::boss_auriayaAI, boss_stormcaller_brundir::boss_stormcaller_brundirAI, npc_assembly_lightning::npc_assembly_lightningAI, boss_runemaster_molgeim::boss_runemaster_molgeimAI, boss_steelbreaker::boss_steelbreakerAI, npc_algalon_worm_hole::npc_algalon_worm_holeAI, npc_living_constellation::npc_living_constellationAI, boss_algalon_the_observer::boss_algalon_the_observerAI, iron_golem_custodian::iron_golem_custodianAI, dark_rune_stormcaller::dark_rune_stormcallerAI, dark_rune_protectors::dark_rune_protectorsAI, brann_bronzebeard::brann_bronzebeardAI, boss_sjonnir_iron_sludge::boss_sjonnir_iron_sludgeAI, boss_sjonnir::boss_sjonnirAI, boss_maiden_of_grief::boss_maiden_of_griefAI, boss_krystallus::boss_krystallusAI, npc_hol_monument::npc_hol_monumentAI, npc_molten_golem::npc_molten_golemAI, boss_volkhan::boss_volkhanAI, boss_loken::boss_lokenAI, npc_spark_of_ionar::npc_spark_of_ionarAI, boss_ionar::boss_ionarAI, npc_stormforged_lieutenant::npc_stormforged_lieutenantAI, boss_bjarngrim::boss_bjarngrimAI, npc_centrifuge_construct::npc_centrifuge_constructAI, boss_varos::boss_varosAI, boss_urom::boss_uromAI, boss_eregos::boss_eregosAI, npc_oculus_unstable_sphere::npc_oculus_unstable_sphereAI, boss_drakos::boss_drakosAI, npc_crystalline_frayer::npc_crystalline_frayerAI, npc_crystal_spike::npc_crystal_spikeAI, boss_ormorok::boss_ormorokAI, boss_magus_telestra::boss_magus_telestraAI, boss_keristrasza::boss_keristraszaAI, boss_commander_stoutbeard::boss_commander_stoutbeardAI, boss_anomalus::boss_anomalusAI, boss_malygos::boss_malygosAI, boss_thaddius_summon::boss_thaddius_summonAI, boss_thaddius::boss_thaddiusAI, boss_sapphiron::boss_sapphironAI, boss_razuvious_minion::boss_razuvious_minionAI, boss_razuvious::boss_razuviousAI, boss_patchwerk::boss_patchwerkAI, boss_noth::boss_nothAI, boss_maexxna::boss_maexxnaAI, boss_loatheb::boss_loathebAI, boss_kelthuzad_minion::boss_kelthuzad_minionAI, boss_kelthuzad::boss_kelthuzadAI, boss_heigan::boss_heiganAI, boss_grobbulus_poison_cloud::boss_grobbulus_poison_cloudAI, boss_grobbulus::boss_grobbulusAI, npc_boss_gothik_minion::npc_boss_gothik_minionAI, boss_gothik::boss_gothikAI, boss_gluth::boss_gluthAI, boss_four_horsemen::boss_four_horsemenAI, boss_faerlina::boss_faerlinaAI, boss_anubrekhan::boss_anubrekhanAI, boss_isle_of_conquest::boss_isle_of_conquestAI, npc_icc_putricades_trap::npc_icc_putricades_trapAI, npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI, npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI, npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI, npc_icc_spire_frostwyrm::npc_icc_spire_frostwyrmAI, npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI, npc_icc_skybreaker_luminary::npc_icc_skybreaker_luminaryAI, npc_icc_skybreaker_vicar::npc_icc_skybreaker_vicarAI, npc_icc_skybreaker_marksman::npc_icc_skybreaker_marksmanAI, npc_icc_skybreaker_hierophant::npc_icc_skybreaker_hierophantAI, npc_arthas_teleport_visual::npc_arthas_teleport_visualAI, npc_impaling_spear::npc_impaling_spearAI, npc_frostwing_vrykul::npc_frostwing_vrykulAI, npc_captain_rupert::npc_captain_rupertAI, npc_captain_grondel::npc_captain_grondelAI, npc_captain_brandon::npc_captain_brandonAI, npc_captain_arnath::npc_captain_arnathAI, npc_argent_captainAI, boss_sister_svalna::boss_sister_svalnaAI, npc_crok_scourgebane::npc_crok_scourgebaneAI, npc_rotting_frost_giant::npc_rotting_frost_giantAI, npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI, npc_gluttonous_abomination::npc_gluttonous_abominationAI, npc_blazing_skeleton::npc_blazing_skeletonAI, npc_valithria_cloud::npc_valithria_cloudAI, npc_risen_archmage::npc_risen_archmageAI, npc_the_lich_king_controller::npc_the_lich_king_controllerAI, npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI, boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI, npc_lk_wicked_spirit::npc_lk_wicked_spiritAI, npc_spirit_warden::npc_spirit_wardenAI, npc_raging_spirit::npc_raging_spiritAI, npc_shambling_horror_icc::npc_shambling_horror_iccAI, npc_tirion_fordring_tft::npc_tirion_fordringAI, boss_the_lich_king::boss_the_lich_kingAI, npc_sindragosa_trash::npc_sindragosa_trashAI, npc_rimefang::npc_rimefangAI, npc_spinestalker::npc_spinestalkerAI, boss_sindragosa::boss_sindragosaAI, npc_precious_icc::npc_precious_iccAI, boss_rotface::boss_rotfaceAI, boss_professor_putricide::boss_professor_putricideAI, boss_lord_marrowgar, npc_darnavan::npc_darnavanAI, npc_vengeful_shade::npc_vengeful_shadeAI, npc_cult_adherent::npc_cult_adherentAI, npc_cult_fanatic::npc_cult_fanaticAI, boss_lady_deathwhisper::boss_lady_deathwhisperAI, npc_stinky_icc::npc_stinky_iccAI, boss_festergut::boss_festergutAI, npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI, npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI, npc_kinetic_bomb::npc_kinetic_bombAI, npc_dark_nucleus::npc_dark_nucleusAI, npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI, boss_prince_valanar_icc::boss_prince_valanarAI, boss_prince_taldaram_icc::boss_prince_taldaramAI, boss_prince_keleseth_icc::boss_prince_kelesethAI, boss_slad_ran::boss_slad_ranAI, boss_moorabi::boss_moorabiAI, boss_gal_darah::boss_gal_darahAI, boss_eck::boss_eckAI, npc_living_mojo::npc_living_mojoAI, boss_drakkari_elemental::boss_drakkari_elementalAI, boss_drakkari_colossus::boss_drakkari_colossusAI, npc_pos_after_first_boss::npc_pos_after_first_bossAI, npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI, npc_pos_leader::npc_pos_leaderAI, boss_tyrannus::boss_tyrannusAI, boss_ick::boss_ickAI, boss_garfrost::boss_garfrostAI, npc_hor_lumbering_abomination::npc_hor_lumbering_abominationAI, npc_hor_risen_witch_doctor::npc_hor_risen_witch_doctorAI, npc_hor_raging_ghoul::npc_hor_raging_ghoulAI, npc_hor_leader_second::npc_hor_leader_secondAI, npc_hor_lich_king::npc_hor_lich_kingAI, npc_hor_spiritual_reflection::npc_hor_spiritual_reflectionAI, boss_frostsworn_general::boss_frostsworn_generalAI, npc_tortured_rifleman::npc_tortured_riflemanAI, npc_spectral_footman::npc_spectral_footmanAI, npc_shadowy_mercenary::npc_shadowy_mercenaryAI, npc_phantom_mage::npc_phantom_mageAI, npc_ghostly_priest::npc_ghostly_priestAI, npc_hor_leader::npc_hor_leaderAI, boss_marwyn::boss_marwynAI, boss_falric::boss_falricAI, npc_fos_leader::npc_fos_leaderAI, boss_devourer_of_souls::boss_devourer_of_soulsAI, npc_fos_corrupted_soul_fragment::npc_fos_corrupted_soul_fragmentAI, boss_bronjahm::boss_bronjahmAI, boss_trollgore::boss_trollgoreAI, boss_tharon_ja::boss_tharon_jaAI, boss_novos::boss_novosAI, boss_dred::boss_dredAI, boss_gormok::boss_gormokAI, npc_snobold_vassal::npc_snobold_vassalAI, npc_mistress_of_pain::npc_mistress_of_painAI, npc_fel_infernal::npc_fel_infernalAI, boss_jaraxxus::boss_jaraxxusAI, npc_anubarak_spike::npc_anubarak_spikeAI, npc_nerubian_burrower::npc_nerubian_burrowerAI, npc_swarm_scarab::npc_swarm_scarabAI, boss_anubarak_trial::boss_anubarak_trialAI, npc_announcer_toc5::npc_announcer_toc5AI, boss_grand_champion::boss_grand_championAI, npc_toc5_grand_champion_minion::npc_toc5_grand_champion_minionAI, npc_toc5_player_vehicle::npc_toc5_player_vehicleAI, npc_black_knight_ghoul::npc_black_knight_ghoulAI, npc_black_knight_skeletal_gryphon::npc_black_knight_skeletal_gryphonAI, boss_black_knight::boss_black_knightAI, npc_argent_soldier::npc_argent_soldierAI, npc_memory::npc_memoryAI, boss_paletress::boss_paletressAI, boss_eadric::boss_eadricAI, boss_saviana_ragefire::boss_saviana_ragefireAI, npc_halion_controller::npc_halion_controllerAI, boss_twilight_halion::boss_twilight_halionAI, boss_halion::boss_halionAI, npc_onyx_flamecaller::npc_onyx_flamecallerAI, boss_general_zarithrian::boss_general_zarithrianAI, npc_xerestrasza::npc_xerestraszaAI, boss_baltharus_the_warborn::boss_baltharus_the_warbornAI, npc_twilight_summon::npc_twilight_summonAI, boss_sartharion_vesperon::boss_sartharion_vesperonAI, boss_sartharion_shadron::boss_sartharion_shadronAI, boss_sartharion_tenebron::boss_sartharion_tenebronAI, boss_sartharion_dragonAI, boss_sartharion::boss_sartharionAI, boss_krik_thir::boss_krik_thirAI, npc_anub_ar_crusher::npc_anub_ar_crusherAI, boss_hadronox::boss_hadronoxAI, boss_anub_arak::boss_anub_arakAI, boss_taldaram::boss_taldaramAI, boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI, boss_volazj::boss_volazjAI, npc_ahnkahar_nerubian::npc_ahnkahar_nerubianAI, boss_elder_nadox::boss_elder_nadoxAI, npc_amanitar_mushrooms::npc_amanitar_mushroomsAI, boss_amanitar::boss_amanitarAI, npc_shadowpriest_sezziz::npc_shadowpriest_sezzizAI, npc_weegli_blastfuse::npc_weegli_blastfuseAI, npc_sergeant_bly::npc_sergeant_blyAI, npc_ranshalla::npc_ranshallaAI, npc_ringo::npc_ringoAI, npc_ame::npc_ameAI, npc_cairne_bloodhoof::npc_cairne_bloodhoofAI, npc_enraged_panther::npc_enraged_pantherAI, npc_plucky::npc_pluckyAI, npc_paoka_swiftmountain::npc_paoka_swiftmountainAI, npc_lakota_windsong::npc_lakota_windsongAI, npc_wizzlecrank_shredder::npc_wizzlecrank_shredderAI, npc_twiggy_flathead::npc_twiggy_flatheadAI, npc_taskmaster_fizzule::npc_taskmaster_fizzuleAI, npc_gilthares::npc_giltharesAI, npc_tooga::npc_toogaAI, npc_custodian_of_time::npc_custodian_of_timeAI, npc_aquementas::npc_aquementasAI, npc_kaya_flathoof::npc_kaya_flathoofAI, npc_anachronos_quest_trigger::npc_anachronos_quest_triggerAI, npc_qiraj_war_spawn::npc_qiraj_war_spawnAI, npc_anachronos_the_ancient::npc_anachronos_the_ancientAI, npc_thrall_warchief::npc_thrall_warchiefAI, npc_shenthul::npc_shenthulAI, npc_giant_spotlight::npc_giant_spotlightAI, npc_clintar_spirit::npc_clintar_spiritAI, npc_troll_volunteer::npc_troll_volunteerAI, npc_prospector_remtravel::npc_prospector_remtravelAI, npc_kerlonian::npc_kerlonianAI, npc_murkdeep::npc_murkdeepAI, npc_webbed_creature::npc_webbed_creatureAI, npc_stillpine_capitive::npc_stillpine_capitiveAI, npc_death_ravager::npc_death_ravagerAI, npc_magwin::npc_magwinAI, npc_injured_draenei::npc_injured_draeneiAI, npc_draenei_survivor::npc_draenei_survivorAI, npc_depth_charge::npc_depth_chargeAI, npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI, npc_spitelashes::npc_spitelashesAI, npc_muglash::npc_muglashAI, npc_anubisath_sentinel::aqsentinelAI, boss_viscidus::boss_viscidusAI, boss_veklor::boss_veklorAI, boss_veknilash::boss_veknilashAI, boss_skeram::boss_skeramAI, npc_sartura_royal_guard::npc_sartura_royal_guardAI, boss_sartura::boss_sarturaAI, boss_ouro::boss_ouroAI, boss_huhuran::boss_huhuranAI, boss_fankriss::boss_fankrissAI, npc_giant_eye_tentacle::giant_eye_tentacleAI, npc_giant_claw_tentacle::giant_claw_tentacleAI, npc_claw_tentacle::claw_tentacleAI, npc_eye_tentacle::eye_tentacleAI, boss_cthun::cthunAI, boss_eye_of_cthun::eye_of_cthunAI, boss_yauj::boss_yaujAI, boss_vem::boss_vemAI, boss_kri::boss_kriAI, boss_rajaxx::boss_rajaxxAI, boss_ossirian::boss_ossirianAI, boss_moam::boss_moamAI, boss_kurinnaxx::boss_kurinnaxxAI, boss_ayamiss::boss_ayamissAI, npc_belnistrasz::npc_belnistraszAI, boss_onyxia::boss_onyxiaAI, npc_time_rift::npc_time_riftAI, npc_medivh_bm::npc_medivh_bmAI, boss_temporus::boss_temporusAI, boss_chrono_lord_deja::boss_chrono_lord_dejaAI, boss_aeonus::boss_aeonusAI, npc_taretha::npc_tarethaAI, npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI, boss_lieutenant_drake::boss_lieutenant_drakeAI, boss_epoch_hunter::boss_epoch_hunterAI, boss_captain_skarloc::boss_captain_skarlocAI, npc_cos_stratholme_citizien::npc_cos_stratholme_citizienAI, npc_arthas::npc_arthasAI, boss_salramm::boss_salrammAI, boss_meathook::boss_meathookAI, boss_mal_ganis::boss_mal_ganisAI, boss_infinite_corruptor::boss_infinite_corruptorAI, boss_epoch::boss_epochAI, hyjalAI, alliance_rifleman::alliance_riflemanAI, npc_gargoyle::npc_gargoyleAI, npc_frost_wyrm::npc_frost_wyrmAI, npc_fel_stalker::npc_fel_stalkerAI, npc_crypt_fiend::npc_crypt_fiendAI, npc_banshee::npc_bansheeAI, npc_necromancer::npc_necromancerAI, npc_ghoul::npc_ghoulAI, npc_abomination::npc_abominationAI, npc_giant_infernal::npc_giant_infernalAI, boss_rage_winterchill::boss_rage_winterchillAI, boss_kazrogal::boss_kazrogalAI, npc_lesser_doomguard::npc_lesser_doomguardAI, boss_azgalor::boss_azgalorAI, boss_archimonde::boss_archimondeAI, npc_doomfire_targetting::npc_doomfire_targettingAI, npc_doomfire::npc_doomfireAI, npc_ancient_wisp::npc_ancient_wispAI, npc_towering_infernal::npc_towering_infernalAI, boss_anetheron::boss_anetheronAI, boss_azuregos::boss_azuregosAI, npc_love_in_air_hummel_helper::npc_love_in_air_hummel_helperAI, npc_love_in_air_hummel::npc_love_in_air_hummelAI, npc_love_in_air_snivel::npc_love_in_air_snivelAI, boss_headless_horseman_pumpkin::boss_headless_horseman_pumpkinAI, boss_headless_horseman_head::boss_headless_horseman_headAI, boss_headless_horseman::boss_headless_horsemanAI, npc_hallows_end_train_fire::npc_hallows_end_train_fireAI, npc_hallows_end_soh::npc_hallows_end_sohAI, npc_soh_fire_trigger::npc_soh_fire_triggerAI, npc_costumed_orphan_matron::npc_costumed_orphan_matronAI, npc_alexstraza_the_lifebinder::npc_alexstraza_the_lifebinderAI, npc_the_etymidian::npc_the_etymidianAI, npc_elder_kekek::npc_elder_kekekAI, npc_high_oracle_soo_roo::npc_high_oracle_soo_rooAI, npc_the_biggest_tree::npc_the_biggest_treeAI, npc_snowfall_glade_playmate::npc_snowfall_glade_playmateAI, npc_winterfin_playmate::npc_winterfin_playmateAI, npc_direbrew_minion::npc_direbrew_minionAI, npc_coren_direbrew::npc_coren_direbrewAI, npc_brew_bubble::npc_brew_bubbleAI, npc_brewfest_super_brew_trigger::npc_brewfest_super_brew_triggerAI, npc_dark_iron_guzzler::npc_dark_iron_guzzlerAI, npc_dark_iron_attack_mole_machine::npc_dark_iron_attack_mole_machineAI, npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI, boss_wushoolay::boss_wushoolayAI, boss_venoxis::boss_venoxisAI, npc_zealot_zath::npc_zealot_zathAI, npc_zealot_lorkhan::npc_zealot_lorkhanAI, boss_thekal::boss_thekalAI, boss_renataki::boss_renatakiAI, npc_spawn_of_marli::npc_spawn_of_marliAI, boss_marli::boss_marliAI, npc_vilebranch_speaker::npc_vilebranch_speakerAI, npc_ohgan::npc_ohganAI, boss_mandokir::boss_mandokirAI, npc_shade_of_jindo::npc_shade_of_jindoAI, npc_healing_ward::npc_healing_wardAI, boss_jindo::boss_jindoAI, npc_batrider::npc_batriderAI, boss_jeklik::boss_jeklikAI, boss_hazzarah::boss_hazzarahAI, boss_hakkar::boss_hakkarAI, boss_grilek::boss_grilekAI, boss_gahzranka::boss_gahzrankaAI, npc_zulian_prowler::npc_zulian_prowlerAI, boss_arlokk::boss_arlokkAI, npc_harrison_jones::npc_harrison_jonesAI, npc_zulaman_hostage::npc_zulaman_hostageAI, npc_forest_frog::npc_forest_frogAI, npc_zuljin_vortex::npc_zuljin_vortexAI, boss_zuljin::boss_zuljinAI, boss_nalorakk::boss_nalorakkAI, npc_janalai_egg::npc_janalai_eggAI, npc_janalai_hatchling::npc_janalai_hatchlingAI, npc_janalai_hatcher::npc_janalai_hatcherAI, npc_janalai_firebomb::npc_janalai_firebombAI, boss_janalai::boss_janalaiAI, boss_koragg::boss_koraggAI, boss_fenstalker::boss_fenstalkerAI, boss_slither::boss_slitherAI, boss_darkheart::boss_darkheartAI, boss_lord_raadan::boss_lord_raadanAI, boss_gazakrothAI, boss_alyson_antille::boss_alyson_antilleAI, boss_thurg::boss_thurgAI, boss_hexlord_malacrass::boss_hex_lord_malacrassAI, boss_hexlord_addAI, npc_halazzi_lynx::npc_halazzi_lynxAI, boss_halazzi::boss_halazziAI, npc_akilzon_eagle::npc_akilzon_eagleAI, boss_akilzon::boss_akilzonAI, npc_tapoke_slim_jahn::npc_tapoke_slim_jahnAI, npc_daphne_stilwell::npc_daphne_stilwellAI, npc_the_scourge_cauldron::npc_the_scourge_cauldronAI, npc_lady_sylvanas_windrunner_bfu::npc_lady_sylvanas_windrunner_bfuAI, npc_thrall_bfu::npc_thrall_bfuAI, boss_blight_worm::boss_blight_wormAI, npc_jaina_proudmoore_bfu::npc_jaina_proudmoore_bfuAI, npc_varian_wrynn::npc_varian_wrynnAI, npc_highborne_lamenter::npc_highborne_lamenterAI, npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI, npc_calvin_montague::npc_calvin_montagueAI, npc_yenniku::npc_yennikuAI, npc_tyrion_spybot::npc_tyrion_spybotAI, npc_marzon_silent_blade::npc_marzon_silent_bladeAI, npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI, npc_bartleby::npc_bartlebyAI, pyrewood_ambush::pyrewood_ambushAI, npc_deathstalker_erland::npc_deathstalker_erlandAI, npc_corporal_keeshan::npc_corporal_keeshanAI, npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI, npc_rinji::npc_rinjiAI, npc_ranger_lilatha::npc_ranger_lilathaAI, npc_eris_hevenfire::npc_eris_hevenfireAI, boss_twilight_corrupter::boss_twilight_corrupterAI, npc_singularity::npc_singularityAI, boss_entropius::boss_entropiusAI, boss_muru::boss_muruAI, npc_kalecgos_kj::npc_kalecgos_kjAI, boss_kiljaeden::boss_kiljaedenAI, npc_kiljaeden_controller::npc_kiljaeden_controllerAI, boss_sathrovarr::boss_sathrovarrAI, boss_kalec::boss_kalecAI, boss_kalecgos::boss_kalecgosAI, npc_demonic_vapor_trail::npc_demonic_vapor_trailAI, npc_demonic_vapor::npc_demonic_vaporAI, boss_felmyst::boss_felmystAI, boss_alythess::boss_alythessAI, boss_sacrolash::boss_sacrolashAI, boss_brutallus::boss_brutallusAI, boss_baroness_anastari::boss_baroness_anastariAI, boss_darkmaster_gandling::boss_darkmaster_gandlingAI, npc_fairbanks::npc_fairbanksAI, boss_high_inquisitor_whitemane::boss_high_inquisitor_whitemaneAI, npc_mograine::npc_mograineAI, npc_scarlet_guard::npc_scarlet_guardAI, npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI, npc_highlord_darion_mograine::npc_highlord_darion_mograineAI, npc_a_special_surprise::npc_a_special_surpriseAI, npc_high_inquisitor_valroth::npc_high_inquisitor_valrothAI, npc_scarlet_courier::npc_scarlet_courierAI, npc_koltira_deathweaver::npc_koltira_deathweaverAI, npc_crusade_persuaded::npc_crusade_persuadedAI, npc_scarlet_miner::npc_scarlet_minerAI, npc_unworthy_initiate::npc_unworthy_initiateAI, npc_death_knight_initiate::npc_death_knight_initiateAI, boss_vexallus::boss_vexallusAI, boss_selin_fireheart::boss_selin_fireheartAI, boss_garaxxas::boss_garaxxasAI, boss_priestess_lackey_commonAI, boss_priestess_delrissa::boss_priestess_delrissaAI, boss_felblood_kaelthas::boss_felblood_kaelthasAI, npc_image_of_medivh::npc_image_of_medivhAI, npc_barnes::npc_barnesAI, boss_romulo::boss_romuloAI, boss_julianne::boss_julianneAI, boss_bigbadwolf::boss_bigbadwolfAI, npc_cyclone::npc_cycloneAI, boss_crone::boss_croneAI, boss_roar::boss_roarAI, boss_tinhead::boss_tinheadAI, boss_strawman::boss_strawmanAI, npc_tito::npc_titoAI, boss_dorothee::boss_dorotheeAI, boss_terestian_illhoof::boss_terestianAI, npc_fiendish_imp::npc_fiendish_impAI, npc_fiendish_portal::npc_fiendish_portalAI, npc_demon_chain::npc_demon_chainAI, npc_kilrek::npc_kilrekAI, npc_aran_elemental::water_elementalAI, boss_shade_of_aran::boss_aranAI, boss_servant_quarters::boss_servant_quartersAI, prince_axes::prince_axesAI, boss_malchezaar::boss_malchezaarAI, netherspite_infernal::netherspite_infernalAI, boss_nightbane::boss_nightbaneAI, boss_netherspite::boss_netherspiteAI, boss_moroes::boss_moroesAI, boss_attumen_midnight::boss_attumen_midnightAI, boss_attumen::boss_attumenAI, boss_midnight::boss_midnightAI, boss_maiden_of_virtue::boss_maiden_of_virtueAI, boss_curator::boss_curatorAI, boss_mr_smite::boss_mr_smiteAI, npc_mc_core_hound::npc_mc_core_houndAI, npc_flamewaker_priest::npc_flamewaker_priestAI, boss_ragnaros::boss_ragnarosAI, boss_majordomo::boss_majordomoAI, npc_core_rager::npc_core_ragerAI, boss_golemagg::boss_golemaggAI, boss_garr::boss_garrAI, boss_baron_geddon::boss_baron_geddonAI, boss_vaelastrasz::boss_vaelAI, boss_razorgore::boss_razorgoreAI, boss_nefarian::boss_nefarianAI, boss_victor_nefarius::boss_victor_nefariusAI, boss_chromaggus::boss_chromaggusAI, boss_the_beast::boss_thebeastAI, boss_solakar_flamewreath::boss_solakar_flamewreathAI, boss_rend_blackhand::boss_rend_blackhandAI, boss_quartermaster_zigris, npc_blackhand_incarcerator::npc_blackhand_incarceratorAI, boss_pyroguard_emberseer::boss_pyroguard_emberseerAI, boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI, boss_lord_valthalak::boss_lord_valthalakAI, boss_highlord_omokk::boss_highlordomokkAI, boss_halycon::boss_halyconAI, boss_gyth::boss_gythAI, boss_drakkisath::boss_drakkisathAI, boss_doomrel::boss_doomrelAI, boss_moira_bronzebeard::boss_moira_bronzebeardAI, boss_magmus::boss_magmusAI, boss_high_interrogator_gerstahn::boss_high_interrogator_gerstahnAI, boss_grizzle::boss_grizzleAI, boss_gorosh_the_dervish::boss_gorosh_the_dervishAI, boss_general_angerforge::boss_general_angerforgeAI, boss_emperor_dagran_thaurissan::boss_draganthaurissanAI, boss_anubshiah::boss_anubshiahAI, boss_ambassador_flamelash::boss_ambassador_flamelashAI, npc_rocknot::npc_rocknotAI, npc_phalanx::npc_phalanxAI, npc_grimstone::npc_grimstoneAI, boss_vanndar::boss_vanndarAI, boss_galvangar::boss_galvangarAI, boss_drekthar::boss_drektharAI, boss_balinda::boss_balindaAI, npc_water_elemental::npc_water_elementalAI, npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI, WorldBossAI, BossAI, ScriptedAI, GuardAI, CombatAI, and npc_razzashi_cobra_venoxis::npc_razzashi_cobra_venoxis_AI.
Definition at line 190 of file UnitAI.h.
 {};
Referenced by CreatureAI::EnterEvadeMode(), ValithriaDespawner::Execute(), InitializeAI(), CreatureAI::JustRespawned(), npc_infra_green_bomber_generic::npc_infra_green_bomber_genericAI::npc_infra_green_bomber_genericAI(), FrostwingGauntletRespawner::operator()(), ValithriaDespawner::operator()(), npc_pet_pri_shadowfiend::Reset(), Creature::Respawn(), and Creature::RespawnOnEvade().
SelectTarget() [1/2]
template<class PREDICATE > Unit* UnitAI::SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const & predicate) inline
Definition at line 205 of file UnitAI.h.
     {
         ThreatContainer::StorageType const& threatlist = me->getThreatMgr().getThreatList();
         if (position >= threatlist.size())
             return nullptr;
         std::list<Unit*> targetList;
         for (ThreatContainer::StorageType::const_iterator itr = threatlist.begin(); itr != threatlist.end(); ++itr)
             if (predicate((*itr)->getTarget()))
                 targetList.push_back((*itr)->getTarget());
         if (position >= targetList.size())
             return nullptr;
         if (targetType == SELECT_TARGET_NEAREST || targetType == SELECT_TARGET_FARTHEST)
             targetList.sort(Acore::ObjectDistanceOrderPred(me));
         switch (targetType)
         {
             case SELECT_TARGET_NEAREST:
             case SELECT_TARGET_TOPAGGRO:
                 {
                     std::list<Unit*>::iterator itr = targetList.begin();
                     std::advance(itr, position);
                     return *itr;
                 }
             case SELECT_TARGET_FARTHEST:
             case SELECT_TARGET_BOTTOMAGGRO:
                 {
                     std::list<Unit*>::reverse_iterator ritr = targetList.rbegin();
                     std::advance(ritr, position);
                     return *ritr;
                 }
             case SELECT_TARGET_RANDOM:
                 {
                     std::list<Unit*>::iterator itr = targetList.begin();
                     std::advance(itr, urand(position, targetList.size() - 1));
                     return *itr;
                 }
             default:
                 break;
         }
         return nullptr;
     }
References ThreatMgr::getThreatList(), Unit::getThreatMgr(), me, SELECT_TARGET_BOTTOMAGGRO, SELECT_TARGET_FARTHEST, SELECT_TARGET_NEAREST, SELECT_TARGET_RANDOM, SELECT_TARGET_TOPAGGRO, and urand().
SelectTarget() [2/2]
Unit * UnitAI::SelectTarget (SelectAggroTarget targetType, uint32 position = 0, float dist = 0.0f, bool playerOnly = false, int32 aura = 0)
Definition at line 93 of file UnitAI.cpp.
 {
     return SelectTarget(targetType, position, DefaultTargetSelector(me, dist, playerOnly, aura));
 }
References me.
Referenced by WorldBossAI::_EnterCombat(), prince_axes::prince_axesAI::changetarget(), boss_buru::boss_buruAI::ChaseNewVictim(), npc_ghostly_priest::npc_ghostly_priestAI::DoAction(), npc_phantom_mage::npc_phantom_mageAI::DoAction(), npc_shadowy_mercenary::npc_shadowy_mercenaryAI::DoAction(), npc_spectral_footman::npc_spectral_footmanAI::DoAction(), npc_tortured_rifleman::npc_tortured_riflemanAI::DoAction(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::DoAction(), DoCast(), boss_archimonde::boss_archimondeAI::DoCastDoomfire(), DoCastRandomTarget(), boss_sartharion_dragonAI::EnterCombat(), npc_coren_direbrew_sisters::npc_coren_direbrew_sistersAI::EnterCombat(), npc_hallows_end_soh::npc_hallows_end_sohAI::EnterCombat(), boss_zuljin::boss_zuljinAI::EnterPhase(), StartMovementEvent::Execute(), boss_baron_geddon::boss_baron_geddonAI::ExecuteEvent(), boss_gehennas::boss_gehennasAI::ExecuteEvent(), boss_magmadar::boss_magmadarAI::ExecuteEvent(), boss_shazzrah::boss_shazzrahAI::ExecuteEvent(), boss_sulfuron::boss_sulfuronAI::ExecuteEvent(), boss_amanitar::boss_amanitarAI::ExecuteEvent(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), SmartScript::GetTargets(), boss_yauj::boss_yaujAI::JustDied(), boss_maexxna::boss_maexxnaAI::JustSummoned(), boss_skeram::boss_skeramAI::JustSummoned(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::JustSummoned(), WorldBossAI::JustSummoned(), boss_vexallus::boss_vexallusAI::JustSummoned(), boss_sacrolash::boss_sacrolashAI::JustSummoned(), npc_demonic_vapor_trail::npc_demonic_vapor_trailAI::JustSummoned(), npc_necromancer::npc_necromancerAI::JustSummoned(), boss_gal_darah::boss_gal_darahAI::JustSummoned(), boss_prince_taldaram_icc::boss_prince_taldaramAI::JustSummoned(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::JustSummoned(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustSummoned(), npc_precious_icc::npc_precious_iccAI::JustSummoned(), boss_volkhan::boss_volkhanAI::JustSummoned(), boss_algalon_the_observer::boss_algalon_the_observerAI::JustSummoned(), boss_supremus::boss_supremusAI::JustSummoned(), boss_the_black_stalker::boss_the_black_stalkerAI::JustSummoned(), boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI::JustSummoned(), boss_balinda::boss_balindaAI::JustSummoned(), boss_ayamiss::boss_ayamissAI::JustSummoned(), npc_swarm_scarab::npc_swarm_scarabAI::Reset(), boss_baroness_anastari::boss_baroness_anastariAI::SchedulePossession(), npc_anubarak_spike::npc_anubarak_spikeAI::SelectNewTarget(), spell_marrowgar_coldflame::spell_marrowgar_coldflame_SpellScript::SelectTarget(), boss_eye_of_cthun::eye_of_cthunAI::SpawnEyeTentacle(), npc_black_knight_ghoul::npc_black_knight_ghoulAI::SpellHitTarget(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::SpellHitTarget(), boss_ragnaros::boss_ragnarosAI::SummonMinions(), boss_anubshiah::boss_anubshiahAI::UpdateAI(), boss_emperor_dagran_thaurissan::boss_draganthaurissanAI::UpdateAI(), boss_high_interrogator_gerstahn::boss_high_interrogator_gerstahnAI::UpdateAI(), boss_doomrel::boss_doomrelAI::UpdateAI(), boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI::UpdateAI(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::UpdateAI(), boss_the_beast::boss_thebeastAI::UpdateAI(), boss_victor_nefarius::boss_victor_nefariusAI::UpdateAI(), boss_nefarian::boss_nefarianAI::UpdateAI(), boss_razorgore::boss_razorgoreAI::UpdateAI(), boss_vaelastrasz::boss_vaelAI::UpdateAI(), boss_golemagg::boss_golemaggAI::UpdateAI(), boss_majordomo::boss_majordomoAI::UpdateAI(), boss_ragnaros::boss_ragnarosAI::UpdateAI(), npc_flamewaker_priest::npc_flamewaker_priestAI::UpdateAI(), boss_curator::boss_curatorAI::UpdateAI(), boss_maiden_of_virtue::boss_maiden_of_virtueAI::UpdateAI(), boss_attumen_midnight::boss_attumen_midnightAI::UpdateAI(), boss_moroes::boss_moroesAI::UpdateAI(), boss_netherspite::boss_netherspiteAI::UpdateAI(), boss_nightbane::boss_nightbaneAI::UpdateAI(), boss_malchezaar::boss_malchezaarAI::UpdateAI(), boss_servant_quarters::boss_servant_quartersAI::UpdateAI(), boss_shade_of_aran::boss_aranAI::UpdateAI(), boss_terestian_illhoof::boss_terestianAI::UpdateAI(), boss_dorothee::boss_dorotheeAI::UpdateAI(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::UpdateAI(), boss_priestess_delrissa::boss_priestess_delrissaAI::UpdateAI(), boss_kagani_nightstrike::boss_kagani_nightstrikeAI::UpdateAI(), boss_ellris_duskhallow::boss_ellris_duskhallowAI::UpdateAI(), boss_yazzai::boss_yazzaiAI::UpdateAI(), boss_apoko::boss_apokoAI::UpdateAI(), boss_zelfan::boss_zelfanAI::UpdateAI(), boss_selin_fireheart::boss_selin_fireheartAI::UpdateAI(), boss_vexallus::boss_vexallusAI::UpdateAI(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::UpdateAI(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::UpdateAI(), npc_scholomance_occultist::npc_scholomance_occultistAI::UpdateAI(), boss_brutallus::boss_brutallusAI::UpdateAI(), boss_sacrolash::boss_sacrolashAI::UpdateAI(), boss_alythess::boss_alythessAI::UpdateAI(), boss_felmyst::boss_felmystAI::UpdateAI(), boss_kiljaeden::boss_kiljaedenAI::UpdateAI(), boss_entropius::boss_entropiusAI::UpdateAI(), boss_twilight_corrupter::boss_twilight_corrupterAI::UpdateAI(), npc_jaina_proudmoore_bfu::npc_jaina_proudmoore_bfuAI::UpdateAI(), boss_blight_worm::boss_blight_wormAI::UpdateAI(), boss_akilzon::boss_akilzonAI::UpdateAI(), npc_akilzon_eagle::npc_akilzon_eagleAI::UpdateAI(), boss_halazzi::boss_halazziAI::UpdateAI(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::UpdateAI(), boss_alyson_antille::boss_alyson_antilleAI::UpdateAI(), boss_slither::boss_slitherAI::UpdateAI(), boss_koragg::boss_koraggAI::UpdateAI(), boss_janalai::boss_janalaiAI::UpdateAI(), boss_nalorakk::boss_nalorakkAI::UpdateAI(), boss_zuljin::boss_zuljinAI::UpdateAI(), boss_arlokk::boss_arlokkAI::UpdateAI(), npc_zulian_prowler::npc_zulian_prowlerAI::UpdateAI(), boss_grilek::boss_grilekAI::UpdateAI(), boss_hakkar::boss_hakkarAI::UpdateAI(), boss_hazzarah::boss_hazzarahAI::UpdateAI(), boss_jeklik::boss_jeklikAI::UpdateAI(), boss_jindo::boss_jindoAI::UpdateAI(), boss_mandokir::boss_mandokirAI::UpdateAI(), boss_marli::boss_marliAI::UpdateAI(), boss_renataki::boss_renatakiAI::UpdateAI(), boss_thekal::boss_thekalAI::UpdateAI(), boss_venoxis::boss_venoxisAI::UpdateAI(), boss_wushoolay::boss_wushoolayAI::UpdateAI(), boss_headless_horseman::boss_headless_horsemanAI::UpdateAI(), npc_love_in_air_hummel_helper::npc_love_in_air_hummel_helperAI::UpdateAI(), boss_azuregos::boss_azuregosAI::UpdateAI(), boss_anetheron::boss_anetheronAI::UpdateAI(), boss_archimonde::boss_archimondeAI::UpdateAI(), boss_azgalor::boss_azgalorAI::UpdateAI(), npc_lesser_doomguard::npc_lesser_doomguardAI::UpdateAI(), boss_rage_winterchill::boss_rage_winterchillAI::UpdateAI(), npc_gargoyle::npc_gargoyleAI::UpdateAI(), hyjalAI::UpdateAI(), boss_epoch::boss_epochAI::UpdateAI(), boss_infinite_corruptor::boss_infinite_corruptorAI::UpdateAI(), boss_mal_ganis::boss_mal_ganisAI::UpdateAI(), boss_meathook::boss_meathookAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), boss_lieutenant_drake::boss_lieutenant_drakeAI::UpdateAI(), boss_onyxia::boss_onyxiaAI::UpdateAI(), boss_ayamiss::boss_ayamissAI::UpdateAI(), boss_kurinnaxx::boss_kurinnaxxAI::UpdateAI(), boss_vem::boss_vemAI::UpdateAI(), boss_eye_of_cthun::eye_of_cthunAI::UpdateAI(), npc_eye_tentacle::eye_tentacleAI::UpdateAI(), npc_claw_tentacle::claw_tentacleAI::UpdateAI(), npc_giant_claw_tentacle::giant_claw_tentacleAI::UpdateAI(), npc_giant_eye_tentacle::giant_eye_tentacleAI::UpdateAI(), boss_fankriss::boss_fankrissAI::UpdateAI(), boss_huhuran::boss_huhuranAI::UpdateAI(), boss_ouro::boss_ouroAI::UpdateAI(), boss_sartura::boss_sarturaAI::UpdateAI(), npc_sartura_royal_guard::npc_sartura_royal_guardAI::UpdateAI(), boss_skeram::boss_skeramAI::UpdateAI(), boss_veknilash::boss_veknilashAI::UpdateAI(), boss_veklor::boss_veklorAI::UpdateAI(), npc_omen::npc_omenAI::UpdateAI(), npc_cairne_bloodhoof::npc_cairne_bloodhoofAI::UpdateAI(), boss_volazj::boss_volazjAI::UpdateAI(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::UpdateAI(), boss_taldaram::boss_taldaramAI::UpdateAI(), boss_anub_arak::boss_anub_arakAI::UpdateAI(), boss_hadronox::boss_hadronoxAI::UpdateAI(), boss_krik_thir::boss_krik_thirAI::UpdateAI(), boss_baltharus_the_warborn::boss_baltharus_the_warbornAI::UpdateAI(), npc_baltharus_the_warborn_clone::npc_baltharus_the_warborn_cloneAI::UpdateAI(), boss_halion::boss_halionAI::UpdateAI(), boss_twilight_halion::boss_twilight_halionAI::UpdateAI(), boss_eadric::boss_eadricAI::UpdateAI(), boss_paletress::boss_paletressAI::UpdateAI(), npc_memory::npc_memoryAI::UpdateAI(), npc_argent_soldier::npc_argent_soldierAI::UpdateAI(), boss_black_knight::boss_black_knightAI::UpdateAI(), boss_grand_champion::boss_grand_championAI::UpdateAI(), npc_nerubian_burrower::npc_nerubian_burrowerAI::UpdateAI(), npc_toc_shaman::npc_toc_shamanAI::UpdateAI(), npc_toc_paladin::npc_toc_paladinAI::UpdateAI(), npc_toc_priest::npc_toc_priestAI::UpdateAI(), npc_toc_shadow_priest::npc_toc_shadow_priestAI::UpdateAI(), npc_toc_warlock::npc_toc_warlockAI::UpdateAI(), npc_toc_mage::npc_toc_mageAI::UpdateAI(), npc_toc_hunter::npc_toc_hunterAI::UpdateAI(), npc_toc_boomkin::npc_toc_boomkinAI::UpdateAI(), npc_toc_rogue::npc_toc_rogueAI::UpdateAI(), npc_toc_enh_shaman::npc_toc_enh_shamanAI::UpdateAI(), npc_toc_retro_paladin::npc_toc_retro_paladinAI::UpdateAI(), boss_jaraxxus::boss_jaraxxusAI::UpdateAI(), npc_fel_infernal::npc_fel_infernalAI::UpdateAI(), npc_mistress_of_pain::npc_mistress_of_painAI::UpdateAI(), boss_jormungarAI::UpdateAI(), boss_icehowl::boss_icehowlAI::UpdateAI(), boss_novos::boss_novosAI::UpdateAI(), boss_tharon_ja::boss_tharon_jaAI::UpdateAI(), boss_bronjahm::boss_bronjahmAI::UpdateAI(), boss_devourer_of_souls::boss_devourer_of_soulsAI::UpdateAI(), boss_garfrost::boss_garfrostAI::UpdateAI(), boss_ick::boss_ickAI::UpdateAI(), boss_tyrannus::boss_tyrannusAI::UpdateAI(), npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI::UpdateAI(), boss_eck::boss_eckAI::UpdateAI(), boss_gal_darah::boss_gal_darahAI::UpdateAI(), boss_prince_valanar_icc::boss_prince_valanarAI::UpdateAI(), boss_festergut::boss_festergutAI::UpdateAI(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::UpdateAI(), npc_cult_adherent::npc_cult_adherentAI::UpdateAI(), boss_lord_marrowgar::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), boss_rotface::boss_rotfaceAI::UpdateAI(), boss_sindragosa::boss_sindragosaAI::UpdateAI(), npc_rimefang::npc_rimefangAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), npc_risen_archmage::npc_risen_archmageAI::UpdateAI(), npc_rotting_frost_giant::npc_rotting_frost_giantAI::UpdateAI(), boss_sister_svalna::boss_sister_svalnaAI::UpdateAI(), npc_captain_arnath::npc_captain_arnathAI::UpdateAI(), npc_captain_brandon::npc_captain_brandonAI::UpdateAI(), npc_captain_grondel::npc_captain_grondelAI::UpdateAI(), npc_captain_rupert::npc_captain_rupertAI::UpdateAI(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::UpdateAI(), npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::UpdateAI(), npc_icc_spire_frostwyrm::npc_icc_spire_frostwyrmAI::UpdateAI(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::UpdateAI(), boss_isle_of_conquest::boss_isle_of_conquestAI::UpdateAI(), boss_anubrekhan::boss_anubrekhanAI::UpdateAI(), boss_faerlina::boss_faerlinaAI::UpdateAI(), boss_four_horsemen::boss_four_horsemenAI::UpdateAI(), boss_gothik::boss_gothikAI::UpdateAI(), boss_grobbulus::boss_grobbulusAI::UpdateAI(), boss_kelthuzad::boss_kelthuzadAI::UpdateAI(), boss_maexxna::boss_maexxnaAI::UpdateAI(), boss_razuvious::boss_razuviousAI::UpdateAI(), boss_sapphiron::boss_sapphironAI::UpdateAI(), boss_thaddius::boss_thaddiusAI::UpdateAI(), boss_thaddius_summon::boss_thaddius_summonAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), boss_anomalus::boss_anomalusAI::UpdateAI(), boss_commander_stoutbeard::boss_commander_stoutbeardAI::UpdateAI(), boss_keristrasza::boss_keristraszaAI::UpdateAI(), boss_magus_telestra::boss_magus_telestraAI::UpdateAI(), boss_ormorok::boss_ormorokAI::UpdateAI(), boss_eregos::boss_eregosAI::UpdateAI(), boss_urom::boss_uromAI::UpdateAI(), boss_varos::boss_varosAI::UpdateAI(), boss_ionar::boss_ionarAI::UpdateAI(), npc_hol_monument::npc_hol_monumentAI::UpdateAI(), boss_krystallus::boss_krystallusAI::UpdateAI(), boss_maiden_of_grief::boss_maiden_of_griefAI::UpdateAI(), boss_sjonnir::boss_sjonnirAI::UpdateAI(), boss_steelbreaker::boss_steelbreakerAI::UpdateAI(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::UpdateAI(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI(), boss_freya::boss_freyaAI::UpdateAI(), boss_freya_elder_ironbranch::boss_freya_elder_ironbranchAI::UpdateAI(), boss_freya_summons::boss_freya_summonsAI::UpdateAI(), boss_hodir::boss_hodirAI::UpdateAI(), boss_kologarn::boss_kologarnAI::UpdateAI(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), boss_razorscale::boss_razorscaleAI::UpdateAI(), boss_thorim::boss_thorimAI::UpdateAI(), boss_thorim_start_npcs::boss_thorim_start_npcsAI::UpdateAI(), boss_thorim_gauntlet_npcs::boss_thorim_gauntlet_npcsAI::UpdateAI(), boss_thorim_runic_colossus::boss_thorim_runic_colossusAI::UpdateAI(), boss_thorim_ancient_rune_giant::boss_thorim_ancient_rune_giantAI::UpdateAI(), boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::UpdateAI(), boss_keleseth::boss_kelesethAI::UpdateAI(), boss_skarvald_the_constructor::boss_skarvald_the_constructorAI::UpdateAI(), boss_dalronn_the_controller::boss_dalronn_the_controllerAI::UpdateAI(), boss_palehoof::boss_palehoofAI::UpdateAI(), npc_massive_jormungar::npc_massive_jormungarAI::UpdateAI(), npc_ferocious_rhino::npc_ferocious_rhinoAI::UpdateAI(), boss_skadi::boss_skadiAI::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), boss_archavon::boss_archavonAI::UpdateAI(), boss_emalon::boss_emalonAI::UpdateAI(), boss_toravon::boss_toravonAI::UpdateAI(), boss_cyanigosa::boss_cyanigosaAI::UpdateAI(), boss_erekem::boss_erekemAI::UpdateAI(), boss_moragg::boss_moraggAI::UpdateAI(), boss_zuramat::boss_zuramatAI::UpdateAI(), npc_azure_invader::npc_azure_invaderAI::UpdateAI(), npc_azure_binder::npc_azure_binderAI::UpdateAI(), npc_azure_mage_slayer::npc_azure_mage_slayerAI::UpdateAI(), npc_azure_stalker::npc_azure_stalkerAI::UpdateAI(), npc_azure_spellbreaker::npc_azure_spellbreakerAI::UpdateAI(), npc_azure_sorceror::npc_azure_sorcerorAI::UpdateAI(), boss_exarch_maladaar::boss_exarch_maladaarAI::UpdateAI(), boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI::UpdateAI(), boss_pandemonius::boss_pandemoniusAI::UpdateAI(), boss_talon_king_ikiss::boss_talon_king_ikissAI::UpdateAI(), boss_anzu::boss_anzuAI::UpdateAI(), boss_blackheart_the_inciter::boss_blackheart_the_inciterAI::UpdateAI(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::UpdateAI(), boss_murmur::boss_murmurAI::UpdateAI(), boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI::UpdateAI(), boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI(), boss_supremus::boss_supremusAI::UpdateAI(), boss_teron_gorefiend::boss_teron_gorefiendAI::UpdateAI(), boss_najentus::boss_najentusAI::UpdateAI(), boss_gathios_the_shatterer::boss_gathios_the_shattererAI::UpdateAI(), boss_high_nethermancer_zerevor::boss_high_nethermancer_zerevorAI::UpdateAI(), boss_lady_malande::boss_lady_malandeAI::UpdateAI(), boss_doomlord_kazzak::boss_doomlordkazzakAI::UpdateAI(), boss_doomwalker::boss_doomwalkerAI::UpdateAI(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::UpdateAI(), boss_hydross_the_unstable::boss_hydross_the_unstableAI::UpdateAI(), boss_lady_vashj::boss_lady_vashjAI::UpdateAI(), boss_the_lurker_below::boss_the_lurker_belowAI::UpdateAI(), boss_ahune::boss_ahuneAI::UpdateAI(), boss_hydromancer_thespia::boss_thespiaAI::UpdateAI(), boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI::UpdateAI(), boss_warlord_kalithresh::boss_warlord_kalithreshAI::UpdateAI(), boss_the_black_stalker::boss_the_black_stalkerAI::UpdateAI(), boss_gruul::boss_gruulAI::UpdateAI(), boss_high_king_maulgar::boss_high_king_maulgarAI::UpdateAI(), boss_olm_the_summoner::boss_olm_the_summonerAI::UpdateAI(), boss_kiggler_the_crazed::boss_kiggler_the_crazedAI::UpdateAI(), boss_broggok::boss_broggokAI::UpdateAI(), npc_shadowmoon_channeler::npc_shadowmoon_channelerAI::UpdateAI(), boss_the_maker::boss_the_makerAI::UpdateAI(), boss_omor_the_unscarred::boss_omor_the_unscarredAI::UpdateAI(), boss_nazan::boss_nazanAI::UpdateAI(), boss_watchkeeper_gargolmar::boss_watchkeeper_gargolmarAI::UpdateAI(), boss_magtheridon::boss_magtheridonAI::UpdateAI(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::UpdateAI(), boss_warbringer_omrogg::boss_warbringer_omroggAI::UpdateAI(), boss_harbinger_skyriss::boss_harbinger_skyrissAI::UpdateAI(), boss_zereketh_the_unbound::boss_zereketh_the_unboundAI::UpdateAI(), boss_thorngrin_the_tender::boss_thorngrin_the_tenderAI::UpdateAI(), boss_alar::boss_alarAI::UpdateAI(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::UpdateAI(), boss_kaelthas::boss_kaelthasAI::UpdateAI(), boss_void_reaver::boss_void_reaverAI::UpdateAI(), boss_gatewatcher_gyrokill::boss_gatewatcher_gyrokillAI::UpdateAI(), boss_pathaleon_the_calculator::boss_pathaleon_the_calculatorAI::UpdateAI(), npc_illidari_spawn::npc_illidari_spawnAI::UpdateAI(), emerald_dragonAI::UpdateAI(), npc_dream_fog::npc_dream_fogAI::UpdateAI(), npc_zuljin_vortex::npc_zuljin_vortexAI::UpdateAI(), boss_bjarngrim::boss_bjarngrimAI::UpdateEscortAI(), and boss_hexlord_malacrass::boss_hex_lord_malacrassAI::UseAbility().
SelectTargetList() [1/2]
template<class PREDICATE > void UnitAI::SelectTargetList (std::list< Unit * > & targetList, PREDICATE const & predicate, uint32 maxTargets, SelectAggroTarget targetType) inline
Definition at line 255 of file UnitAI.h.
     {
         ThreatContainer::StorageType const& threatlist = me->getThreatMgr().getThreatList();
         if (threatlist.empty())
             return;
         for (ThreatContainer::StorageType::const_iterator itr = threatlist.begin(); itr != threatlist.end(); ++itr)
             if (predicate((*itr)->getTarget()))
                 targetList.push_back((*itr)->getTarget());
         if (targetList.size() < maxTargets)
             return;
         if (targetType == SELECT_TARGET_NEAREST || targetType == SELECT_TARGET_FARTHEST)
             targetList.sort(Acore::ObjectDistanceOrderPred(me));
         if (targetType == SELECT_TARGET_FARTHEST || targetType == SELECT_TARGET_BOTTOMAGGRO)
             targetList.reverse();
         if (targetType == SELECT_TARGET_RANDOM)
             Acore::Containers::RandomResize(targetList, maxTargets);
         else
             targetList.resize(maxTargets);
     }
References ThreatMgr::getThreatList(), Unit::getThreatMgr(), me, Acore::Containers::RandomResize(), SELECT_TARGET_BOTTOMAGGRO, SELECT_TARGET_FARTHEST, SELECT_TARGET_NEAREST, and SELECT_TARGET_RANDOM.
SelectTargetList() [2/2]
void UnitAI::SelectTargetList (std::list< Unit * > & targetList, uint32 num, SelectAggroTarget targetType, float dist = 0.0f, bool playerOnly = false, int32 aura = 0)
Definition at line 98 of file UnitAI.cpp.
 {
     SelectTargetList(targetList, DefaultTargetSelector(me, dist, playerOnly, aura), num, targetType);
 }
References me.
Referenced by boss_magmadar::boss_magmadarAI::ExecuteEvent(), npc_batrider::npc_batriderAI::UpdateAI(), boss_festergut::boss_festergutAI::UpdateAI(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), and boss_rotface::boss_rotfaceAI::UpdateAI().
SetData()
virtual void UnitAI::SetData (uint32 , uint32) inline virtual
Reimplemented in npc_ulduar_magnetic_core::npc_ulduar_magnetic_coreAI, npc_ulduar_mimiron_rocket::npc_ulduar_mimiron_rocketAI, boss_mimiron::boss_mimironAI, boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI, boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI, npc_thassarian2::npc_thassarian2AI, npc_idol_room_spawner::npc_idol_room_spawnerAI, boss_pyroguard_emberseer::boss_pyroguard_emberseerAI, npc_argent_soldier::npc_argent_soldierAI, boss_grand_champion::boss_grand_championAI, npc_simon_bunny::npc_simon_bunnyAI, npc_shandy_dalaran::npc_shandy_dalaranAI, boss_keristrasza::boss_keristraszaAI, boss_anomalus::boss_anomalusAI, npc_pos_leader::npc_pos_leaderAI, boss_novos::boss_novosAI, boss_dred::boss_dredAI, boss_midnight::boss_midnightAI, boss_the_beast::boss_thebeastAI, boss_the_lich_king::boss_the_lich_kingAI, boss_volazj::boss_volazjAI, boss_teron_gorefiend::boss_teron_gorefiendAI, npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI, npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI, boss_kaelthas::boss_kaelthasAI, npc_warden_mellichar::npc_warden_mellicharAI, npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI, npc_outhouse_bunny::npc_outhouse_bunnyAI, npc_q24545_lich_king::npc_q24545_lich_kingAI, npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI, npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI, npc_sindragosa_trash::npc_sindragosa_trashAI, npc_gunship_boarding_addAI, gunship_npc_AI, npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI, npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI, boss_festergut::boss_festergutAI, npc_saurfang_event::npc_saurfang_eventAI, boss_sartharion::boss_sartharionAI, npc_alexstraza_the_lifebinder::npc_alexstraza_the_lifebinderAI, boss_entropius::boss_entropiusAI, boss_darkmaster_gandling::boss_darkmaster_gandlingAI, boss_victor_nefarius::boss_victor_nefariusAI, boss_rend_blackhand::boss_rend_blackhandAI, npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI, boss_ignis::boss_ignisAI, boss_garfrost::boss_garfrostAI, boss_arlokk::boss_arlokkAI, npc_ulduar_harpoonfirestate::npc_ulduar_harpoonfirestateAI, npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI, npc_ulduar_vx001::npc_ulduar_vx001AI, npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI, boss_hodir::boss_hodirAI, npc_halion_controller::npc_halion_controllerAI, SmartAI, npc_shadowmoon_tuber_node::npc_shadowmoon_tuber_nodeAI, npc_invis_infernal_caster::npc_invis_infernal_casterAI, boss_professor_putricide::boss_professor_putricideAI, npc_cork_gizelton::npc_cork_gizeltonAI, npc_eris_hevenfire::npc_eris_hevenfireAI, boss_slad_ran::boss_slad_ranAI, npc_omrogg_heads::npc_omrogg_headsAI, boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI, npc_blackhand_incarcerator::npc_blackhand_incarceratorAI, and boss_svala::boss_svalaAI.
Definition at line 198 of file UnitAI.h.
 {}
Referenced by RestoreAttack::Execute(), spell_kiljaeden_sinister_reflection_clone::spell_kiljaeden_sinister_reflection_clone_SpellScript::FilterTargets(), spell_herald_volzaj_insanity::spell_herald_volzaj_insanity_SpellScript::HandleAfterCast(), spell_kaelthas_resurrection::spell_kaelthas_resurrection_SpellScript::HandleBeforeCast(), npc_commandscript::HandleNpcSetDataCommand(), spell_putricide_unstable_experiment::spell_putricide_unstable_experiment_SpellScript::HandleScript(), spell_frostwarden_handler_focus_fire::spell_frostwarden_handler_focus_fire_SpellScript::HandleScript(), boss_warbringer_omrogg::boss_warbringer_omroggAI::JustDied(), boss_muru::boss_muruAI::JustSummoned(), npc_risen_guardian::npc_risen_guardianAI::KilledUnit(), npc_shandy_dalaran::OnGossipSelect(), go_amberpine_outhouse::OnGossipSelect(), npc_eris_hevenfire::OnQuestAccept(), at_blackrock_stadium::OnTrigger(), spell_hodir_flash_freeze::spell_hodir_flash_freeze_AuraScript::PrepareAuraScript(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), and boss_razorscale::boss_razorscaleAI::UpdateAI().
SetGUID()
virtual void UnitAI::SetGUID (ObjectGuid , int32 = 0) inline virtual
Reimplemented in npc_captain_saeed::npc_captain_saeedAI, npc_cork_gizelton::npc_cork_gizeltonAI, npc_kurenai_captive::npc_kurenai_captiveAI, npc_voidtraveler::npc_voidtravelerAI, npc_q24545_lich_king::npc_q24545_lich_kingAI, npc_bloodmage_laurith::npc_bloodmage_laurithAI, boss_maexxna_webwrap::boss_maexxna_webwrapAI, npc_valkyr_shadowguard::npc_valkyr_shadowguardAI, npc_ball_of_flame::npc_ball_of_flameAI, npc_time_rift::npc_time_riftAI, npc_eris_hevenfire::npc_eris_hevenfireAI, npc_scarlet_miner_cart::npc_scarlet_miner_cartAI, npc_unworthy_initiate_anchor::npc_unworthy_initiate_anchorAI, npc_scarlet_ghoul::npc_scarlet_ghoulAI, npc_kernobee::npc_kernobeeAI, boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI, npc_crok_scourgebane::npc_crok_scourgebaneAI, npc_ice_tomb::npc_ice_tombAI, npc_putricide_oozeAI, npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI, SmartAI, npc_simon_bunny::npc_simon_bunnyAI, npc_gunship::npc_gunshipAI, and npc_coren_direbrew_sisters::npc_coren_direbrew_sistersAI.
Definition at line 199 of file UnitAI.h.
 {}
Referenced by spell_blood_queen_bloodbolt::spell_blood_queen_bloodbolt_SpellScript::FilterTargets(), spell_send_mug_target_picker::spell_send_mug_target_picker_SpellScript::HandleDummy(), boss_prince_taldaram_icc::boss_prince_taldaramAI::JustSummoned(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::JustSummoned(), npc_dkc1_gothik::npc_dkc1_gothikAI::MoveInLineOfSight(), npc_captain_saeed::OnGossipSelect(), npc_kernobee::OnQuestAccept(), npc_kurenai_captive::OnQuestAccept(), npc_eris_hevenfire::OnQuestAccept(), npc_cork_gizelton::OnQuestAccept(), npc_lady_sylvanas_windrunner::OnQuestReward(), spell_the_lich_king_valkyr_target_search::spell_the_lich_king_valkyr_target_search_SpellScript::SelectTarget(), and instance_the_black_morass::instance_the_black_morass_InstanceMapScript::SummonPortalKeeper().
sGossipHello()
virtual void UnitAI::sGossipHello (Player *) inline virtual
Reimplemented in npc_weegli_blastfuse::npc_weegli_blastfuseAI, npc_sergeant_bly::npc_sergeant_blyAI, npc_maredis_firestar::npc_maredis_firestarAI, SmartAI, and npc_thassarian2::npc_thassarian2AI.
Definition at line 313 of file UnitAI.h.
 {}
Referenced by WorldSession::HandleGossipHelloOpcode(), and WorldSession::HandleQuestgiverHelloOpcode().
sGossipSelect()
virtual void UnitAI::sGossipSelect (Player * , uint32 , uint32) inline virtual
Reimplemented in npc_akama_illidan::npc_akama_illidanAI, npc_crusade_recruit::npc_crusade_recruitAI, npc_lake_frog::npc_lake_frogAI, npc_zafod_boombox::npc_zafod_boomboxAI, npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI, npc_maredis_firestar::npc_maredis_firestarAI, npc_hidden_cultist::npc_hidden_cultistAI, npc_weegli_blastfuse::npc_weegli_blastfuseAI, npc_sergeant_bly::npc_sergeant_blyAI, npc_akama_shade::npc_akamaAI, npc_thassarian2::npc_thassarian2AI, npc_cairne_bloodhoof::npc_cairne_bloodhoofAI, npc_harrison_jones::npc_harrison_jonesAI, boss_vaelastrasz::boss_vaelAI, boss_victor_nefarius::boss_victor_nefariusAI, SmartAI, npc_stable_master::npc_stable_masterAI, npc_pet_trainer::npc_pet_trainerAI, npc_coren_direbrew::npc_coren_direbrewAI, npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI, npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI, and npc_tirion_fordring_tft::npc_tirion_fordringAI.
Definition at line 314 of file UnitAI.h.
 {}
Referenced by WorldSession::HandleGossipSelectOptionOpcode().
sGossipSelectCode()
virtual void UnitAI::sGossipSelectCode (Player * , uint32 , uint32 , char const *) inline virtual
Reimplemented in SmartAI.
Definition at line 315 of file UnitAI.h.
 {}
Referenced by WorldSession::HandleGossipSelectOptionOpcode().
sOnGameEvent()
virtual void UnitAI::sOnGameEvent (bool , uint16) inline virtual
Reimplemented in SmartAI.
Definition at line 320 of file UnitAI.h.
 {}
sQuestAccept()
virtual void UnitAI::sQuestAccept (Player * , Quest const *) inline virtual
Reimplemented in npc_wounded_blood_elf::npc_wounded_blood_elfAI, npc_shay_leafrunner::npc_shay_leafrunnerAI, npc_magwin::npc_magwinAI, npc_muglash::npc_muglashAI, npc_corporal_keeshan::npc_corporal_keeshanAI, npc_rinji::npc_rinjiAI, npc_professor_phizzlethorpe::npc_professor_phizzlethorpeAI, SmartAI, and npc_belnistrasz::npc_belnistraszAI.
Definition at line 316 of file UnitAI.h.
 {}
Referenced by Player::AddQuestAndCheckCompletion().
sQuestComplete()
virtual void UnitAI::sQuestComplete (Player * , Quest const *) inline virtual
Definition at line 318 of file UnitAI.h.
 {}
sQuestReward()
virtual void UnitAI::sQuestReward (Player * , Quest const * , uint32) inline virtual
Reimplemented in SmartAI.
Definition at line 319 of file UnitAI.h.
 {}
Referenced by WorldSession::HandleQuestgiverChooseRewardOpcode().
sQuestSelect()
virtual void UnitAI::sQuestSelect (Player * , Quest const *) inline virtual
Definition at line 317 of file UnitAI.h.
 {}
UpdateAI()
virtual void UnitAI::UpdateAI (uint32) pure virtual
Implemented in npc_guardian::npc_guardianAI, npc_injured_patient::npc_injured_patientAI, npc_precious::npc_preciousAI, npc_pet_gen_gnomish_flame_turret, npc_pet_gen_mojo, npc_infernal_attacker::npc_infernal_attackerAI, npc_deaths_fel_cannon::npc_deaths_fel_cannonAI, boss_vazruden_the_herald::boss_vazruden_the_heraldAI, boss_illidari_council::boss_illidari_councilAI, npc_wg_spirit_guide::npc_wg_spirit_guideAI, npc_brunnhildar_prisoner::npc_brunnhildar_prisonerAI, npc_bushwhacker::npc_bushwhackerAI, npc_wounded_skirmisher::npc_wounded_skirmisherAI, npc_tallhorn_stag::npc_tallhorn_stagAI, npc_mrfloppy::npc_mrfloppyAI, npc_q24545_vegard_dummy::npc_q24545_vegard_dummyAI, npc_future_you::npc_future_youAI, npc_mageguard_dalaran::npc_mageguard_dalaranAI, npc_warmage_violetstand::npc_warmage_violetstandAI, npc_frost_tomb::npc_frost_tombAI, npc_ulduar_snow_mound::npc_ulduar_snow_moundAI, boss_yoggsaron_corruptor_tentacle::boss_yoggsaron_corruptor_tentacleAI, boss_yoggsaron_crusher_tentacle::boss_yoggsaron_crusher_tentacleAI, npc_xt002_life_spark::npc_xt002_life_sparkAI, npc_xt002_boombot::npc_xt002_boombotAI, npc_xt002_scrapbot::npc_xt002_scrapbotAI, npc_ulduar_mimiron_rocket::npc_ulduar_mimiron_rocketAI, boss_kologarn_arms::boss_kologarn_armsAI, npc_assembly_lightning::npc_assembly_lightningAI, boss_sjonnir_dwarf::boss_sjonnir_dwarfAI, npc_spark_of_ionar::npc_spark_of_ionarAI, npc_centrifuge_construct::npc_centrifuge_constructAI, npc_tesla::npc_teslaAI, npc_suppresser::npc_suppresserAI, npc_gunship_rocketeer::npc_gunship_rocketeerAI, npc_hor_raging_ghoul::npc_hor_raging_ghoulAI, npc_concentrated_ball::npc_concentrated_ballAI, npc_announcer_toc5::npc_announcer_toc5AI, npc_orb_carrier::npc_orb_carrierAI, npc_enraged_panther::npc_enraged_pantherAI, npc_zelfrax::npc_zelfraxAI, npc_injured_draenei::npc_injured_draeneiAI, npc_onyxia_trigger::npc_onyxia_triggerAI, npc_zulaman_hostage::npc_zulaman_hostageAI, npc_zuljin_vortex::npc_zuljin_vortexAI, npc_janalai_egg::npc_janalai_eggAI, npc_janalai_firebomb::npc_janalai_firebombAI, boss_hexlord_addAI, npc_marzon_silent_blade::npc_marzon_silent_bladeAI, npc_greengill_slave::npc_greengill_slaveAI, npc_demonic_vapor::npc_demonic_vaporAI, FollowerAI, PetAI, CritterAI, NullCreatureAI, PossessedAI, PassiveAI, AggressorAI, npc_earthmender_wilda::npc_earthmender_wildaAI, npc_maxx_a_million_escort::npc_maxx_a_million_escortAI, npc_engineer_helice::npc_engineer_heliceAI, npc_warmage_coldarra::npc_warmage_coldarraAI, npc_ichor_globule::npc_ichor_globuleAI, boss_ichoron::boss_ichoronAI, npc_black_knight_skeletal_gryphon::npc_black_knight_skeletal_gryphonAI, npc_tyrion_spybot::npc_tyrion_spybotAI, npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI, npc_koltira_deathweaver::npc_koltira_deathweaverAI, npc_spring_rabbit::npc_spring_rabbitAI, npc_garments_of_quests::npc_garments_of_questsAI, npc_doctor::npc_doctorAI, npc_dancing_flames::npc_dancing_flamesAI, npc_chicken_cluck::npc_chicken_cluckAI, npc_target_dummy::npc_target_dummyAI, npc_training_dummy::npc_training_dummyAI, npc_riggle_bassbait::npc_riggle_bassbaitAI, npc_elder_clearwater::npc_elder_clearwaterAI, npc_franklin::npc_franklinAI, npc_nelson::npc_nelsonAI, npc_simone::npc_simoneAI, npc_artorius::npc_artoriusAI, trigger_periodic::trigger_periodicAI, generic_creature::generic_creatureAI, guard_shattrath_aldor::guard_shattrath_aldorAI, guard_shattrath_scryer::guard_shattrath_scryerAI, boss_taerar::boss_taerarAI, npc_dream_fog::npc_dream_fogAI, emerald_dragonAI, npc_pet_shaman_fire_elemental, npc_pet_shaman_earth_elemental, npc_pet_mage_mirror_image, npc_pet_hunter_snake_trap, npc_pet_gen_fetch_ball, npc_pet_gen_toxic_wasteling, npc_pet_gen_plump_turkey, npc_pet_gen_wind_rider_cub, npc_pet_gen_imp_in_a_bottle, npc_pet_gen_valkyr_guardian, npc_pet_gen_target_following_bomb, npc_pet_gen_argent_pony_bridle, npc_pet_gen_soul_trader_beacon, npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI, npc_cooshcoosh::npc_cooshcooshAI, npc_floon::npc_floonAI, npc_unkor_the_ruthless::npc_unkor_the_ruthlessAI, npc_ishanah::ishanahAI, npc_salsalabim::npc_salsalabimAI, npc_raliq_the_drunk::npc_raliq_the_drunkAI, npc_shadowmoon_tuber_node::npc_shadowmoon_tuber_nodeAI, npc_illidari_spawn::npc_illidari_spawnAI, npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI, npc_torloth_the_magnificent::npc_torloth_the_magnificentAI, npc_dragonmaw_peon::npc_dragonmaw_peonAI, npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI, npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI, npc_invis_infernal_caster::npc_invis_infernal_casterAI, npc_phase_hunter::npc_phase_hunterAI, npc_commander_dawnforge::npc_commander_dawnforgeAI, npc_captain_saeed::npc_captain_saeedAI, kaylaan_the_lost::kaylaan_the_lostAI, socrethar::socretharAI, exarch_orelis::exarch_orelisAI, anchorite_karja::anchorite_karjaAI, adyen_the_lightbringer::adyen_the_lightbringerAI, npc_corki::npc_corkiAI, npc_maghar_captive::npc_maghar_captiveAI, npc_fel_guard_hound::npc_fel_guard_houndAI, npc_aeranas::npc_aeranasAI, npc_oscillating_frequency_scanner_master_bunny::npc_oscillating_frequency_scanner_master_bunnyAI, npc_simon_bunny::npc_simon_bunnyAI, npc_nether_drake::npc_nether_drakeAI, npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI, boss_pathaleon_the_calculator::boss_pathaleon_the_calculatorAI, npc_ragin_flames::npc_ragin_flamesAI, boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI, boss_mechano_lord_capacitus::boss_mechano_lord_capacitusAI, boss_gatewatcher_iron_hand::boss_gatewatcher_iron_handAI, boss_gatewatcher_gyrokill::boss_gatewatcher_gyrokillAI, boss_void_reaver::boss_void_reaverAI, boss_kaelthas::boss_kaelthasAI, boss_high_astromancer_solarian::boss_high_astromancer_solarianAI, boss_alar::boss_alarAI, boss_warp_splinter::boss_warp_splinterAI, boss_thorngrin_the_tender::boss_thorngrin_the_tenderAI, boss_laj::boss_lajAI, boss_high_botanist_freywinn::boss_high_botanist_freywinnAI, boss_commander_sarannis::boss_commander_sarannisAI, boss_zereketh_the_unbound::boss_zereketh_the_unboundAI, boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI, boss_harbinger_skyriss::boss_harbinger_skyrissAI, boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI, npc_warden_mellichar::npc_warden_mellicharAI, npc_millhouse_manastorm::npc_millhouse_manastormAI, boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI, npc_omrogg_heads::npc_omrogg_headsAI, boss_warbringer_omrogg::boss_warbringer_omroggAI, boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI, boss_magtheridon::boss_magtheridonAI, boss_watchkeeper_gargolmar::boss_watchkeeper_gargolmarAI, boss_vazruden::boss_vazrudenAI, boss_nazan::boss_nazanAI, boss_omor_the_unscarred::boss_omor_the_unscarredAI, boss_the_maker::boss_the_makerAI, npc_shadowmoon_channeler::npc_shadowmoon_channelerAI, boss_kelidan_the_breaker::boss_kelidan_the_breakerAI, boss_broggok::boss_broggokAI, boss_krosh_firehand::boss_krosh_firehandAI, boss_blindeye_the_seer::boss_blindeye_the_seerAI, boss_kiggler_the_crazed::boss_kiggler_the_crazedAI, boss_olm_the_summoner::boss_olm_the_summonerAI, boss_high_king_maulgar::boss_high_king_maulgarAI, boss_gruul::boss_gruulAI, boss_the_black_stalker::boss_the_black_stalkerAI, npc_naga_distiller::npc_naga_distillerAI, boss_warlord_kalithresh::boss_warlord_kalithreshAI, npc_steamrigger_mechanic::npc_steamrigger_mechanicAI, boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI, boss_hydromancer_thespia::boss_thespiaAI, boss_ahune::boss_ahuneAI, boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI, boss_the_lurker_below::boss_the_lurker_belowAI, npc_inner_demon::npc_inner_demonAI, boss_leotheras_the_blind::boss_leotheras_the_blindAI, boss_lady_vashj::boss_lady_vashjAI, boss_hydross_the_unstable::boss_hydross_the_unstableAI, boss_fathomlord_karathress::boss_fathomlord_karathressAI, boss_doomwalker::boss_doomwalkerAI, boss_doomlord_kazzak::boss_doomlordkazzakAI, boss_veras_darkshadow::boss_veras_darkshadowAI, boss_lady_malande::boss_lady_malandeAI, boss_high_nethermancer_zerevor::boss_high_nethermancer_zerevorAI, boss_gathios_the_shatterer::boss_gathios_the_shattererAI, boss_najentus::boss_najentusAI, boss_teron_gorefiend::boss_teron_gorefiendAI, boss_supremus::boss_supremusAI, npc_creature_generator_akama::npc_creature_generator_akamaAI, npc_akama_shade::npc_akamaAI, boss_shade_of_akama::boss_shade_of_akamaAI, boss_essence_of_anger::boss_essence_of_angerAI, boss_essence_of_desire::boss_essence_of_desireAI, boss_essence_of_suffering::boss_essence_of_sufferingAI, boss_reliquary_of_souls::boss_reliquary_of_soulsAI, boss_mother_shahraz::boss_shahrazAI, boss_illidan_stormrage::boss_illidan_stormrageAI, boss_gurtogg_bloodboil::boss_gurtogg_bloodboilAI, boss_murmur::boss_murmurAI, npc_voidtraveler::npc_voidtravelerAI, boss_grandmaster_vorpil::boss_grandmaster_vorpilAI, boss_blackheart_the_inciter::boss_blackheart_the_inciterAI, boss_ambassador_hellmaw::boss_ambassador_hellmawAI, boss_anzu::boss_anzuAI, boss_talon_king_ikiss::boss_talon_king_ikissAI, boss_pandemonius::boss_pandemoniusAI, npc_yor::npc_yorAI, boss_nexusprince_shaffar::boss_nexusprince_shaffarAI, boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI, npc_stolen_soul::npc_stolen_soulAI, boss_exarch_maladaar::boss_exarch_maladaarAI, npc_crusade_recruit::npc_crusade_recruitAI, npc_drakuru_shackles::npc_drakuru_shacklesAI, npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI, npc_feedin_da_goolz::npc_feedin_da_goolzAI, npc_wg_siege_machine::npc_wg_siege_machineAI, npc_wg_queue::npc_wg_queueAI, npc_hyldsmeet_protodrake::npc_hyldsmeet_protodrakeAI, npc_icefang::npc_icefangAI, npc_freed_protodrake::npc_freed_protodrakeAI, npc_wild_wyrm::npc_wild_wyrmAI, npc_iron_watcher::npc_iron_watcherAI, npc_frosthound::npc_frosthoundAI, npc_jungle_punch_target::npc_jungle_punch_targetAI, npc_still_at_it_trigger::npc_still_at_it_triggerAI, npc_artruis_the_hearthless::npc_artruis_the_hearthlessAI, npc_frostbrood_skytalon::npc_frostbrood_skytalonAI, npc_blessed_banner::npc_blessed_bannerAI, npc_tournament_training_dummy::npc_tournament_training_dummyAI, npc_infra_green_bomber_generic::npc_infra_green_bomber_genericAI, npc_boneguard_footman::npc_boneguard_footmanAI, npc_lord_arete::npc_lord_areteAI, npc_llod_generic::npc_llod_genericAI, npc_battle_at_valhalas::npc_battle_at_valhalasAI, npc_your_inner_turmoil::npc_your_inner_turmoilAI, npc_lake_frog::npc_lake_frogAI, npc_venture_co_straggler::npc_venture_co_stragglerAI, npc_amberpine_woodsman::npc_amberpine_woodsmanAI, npc_ravenous_worg::npc_ravenous_worgAI, npc_torturer_lecraft::npc_torturer_lecraftAI, npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI, npc_q24545_vegard::npc_q24545_vegardAI, npc_q24545_lich_king::npc_q24545_lich_kingAI, npc_hourglass_of_eternity::npc_hourglass_of_eternityAI, npc_conversing_with_the_depths_trigger::npc_conversing_with_the_depths_triggerAI, npc_dalaran_warrior::npc_dalaran_warriorAI, npc_dalaran_mage::npc_dalaran_mageAI, npc_minigob_manabonk::npc_minigob_manabonkAI, npc_archmage_landalock::npc_archmage_landalockAI, npc_shandy_dalaran::npc_shandy_dalaranAI, npc_preparations_for_war_vehicle::npc_preparations_for_war_vehicleAI, npc_counselor_talbot::npc_counselor_talbotAI, npc_thassarian2::npc_thassarian2AI, npc_thassarian::npc_thassarianAI, npc_bloodmage_laurith::npc_bloodmage_laurithAI, npc_hidden_cultist::npc_hidden_cultistAI, npc_valiance_keep_cannoneer::npc_valiance_keep_cannoneerAI, npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI, npc_captured_beryl_sorcerer::npc_captured_beryl_sorcererAI, npc_beryl_sorcerer::npc_beryl_sorcererAI, npc_lurgglbr::npc_lurgglbrAI, npc_sinkhole_kill_credit::npc_sinkhole_kill_creditAI, npc_azure_saboteur::npc_azure_saboteurAI, npc_azure_sorceror::npc_azure_sorcerorAI, npc_azure_captain::npc_azure_captainAI, npc_azure_spellbreaker::npc_azure_spellbreakerAI, npc_azure_stalker::npc_azure_stalkerAI, npc_azure_raider::npc_azure_raiderAI, npc_azure_mage_slayer::npc_azure_mage_slayerAI, npc_azure_binder::npc_azure_binderAI, npc_azure_invader::npc_azure_invaderAI, violet_hold_trashAI, npc_vh_teleportation_portal::npc_vh_teleportation_portalAI, npc_vh_void_sentry::npc_vh_void_sentryAI, boss_zuramat::boss_zuramatAI, boss_xevozz::boss_xevozzAI, boss_moragg::boss_moraggAI, boss_lavanthor::boss_lavanthorAI, npc_erekem_guard::npc_erekem_guardAI, boss_erekem::boss_erekemAI, boss_cyanigosa::boss_cyanigosaAI, npc_frozen_orb::npc_frozen_orbAI, boss_toravon::boss_toravonAI, boss_koralon::boss_koralonAI, boss_emalon::boss_emalonAI, boss_archavon::boss_archavonAI, boss_ymiron::boss_ymironAI, boss_svala::boss_svalaAI, boss_skadi_grauf::boss_skadi_graufAI, boss_skadi::boss_skadiAI, npc_frenzied_worgen::npc_frenzied_worgenAI, npc_ravenous_furbolg::npc_ravenous_furbolgAI, npc_ferocious_rhino::npc_ferocious_rhinoAI, npc_massive_jormungar::npc_massive_jormungarAI, boss_palehoof::boss_palehoofAI, npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI, boss_dalronn_the_controller::boss_dalronn_the_controllerAI, boss_skarvald_the_constructor::boss_skarvald_the_constructorAI, npc_vrykul_skeleton::npc_vrykul_skeletonAI, boss_keleseth::boss_kelesethAI, boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI, npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI, npc_ulduar_storm_tempered_keeper::npc_ulduar_storm_tempered_keeperAI, boss_yoggsaron_voice::boss_yoggsaron_voiceAI, boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI, boss_yoggsaron_llane::boss_yoggsaron_llaneAI, boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI, boss_yoggsaron_immortal_guardian::boss_yoggsaron_immortal_guardianAI, boss_yoggsaron_keeper::boss_yoggsaron_keeperAI, boss_yoggsaron_constrictor_tentacle::boss_yoggsaron_constrictor_tentacleAI, boss_yoggsaron_death_orb::boss_yoggsaron_death_orbAI, boss_yoggsaron_brain::boss_yoggsaron_brainAI, boss_yoggsaron::boss_yoggsaronAI, boss_yoggsaron_guardian_of_ys::boss_yoggsaron_guardian_of_ysAI, boss_yoggsaron_sara::boss_yoggsaron_saraAI, npc_xt002_pummeller::npc_xt002_pummellerAI, npc_xt002_heart::npc_xt002_heartAI, boss_xt002::boss_xt002AI, boss_thorim_arena_npcs::boss_thorim_arena_npcsAI, boss_thorim_ancient_rune_giant::boss_thorim_ancient_rune_giantAI, boss_thorim_runic_colossus::boss_thorim_runic_colossusAI, boss_thorim_gauntlet_npcs::boss_thorim_gauntlet_npcsAI, boss_thorim_start_npcs::boss_thorim_start_npcsAI, boss_thorim_pillar::boss_thorim_pillarAI, boss_thorim_trap::boss_thorim_trapAI, boss_thorim_sif::boss_thorim_sifAI, boss_thorim::boss_thorimAI, npc_ulduar_dark_rune_sentinel::npc_ulduar_dark_rune_sentinelAI, npc_ulduar_dark_rune_watcher::npc_ulduar_dark_rune_watcherAI, npc_ulduar_dark_rune_guardian::npc_ulduar_dark_rune_guardianAI, npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI, boss_razorscale::boss_razorscaleAI, npc_ulduar_emergency_fire_bot::npc_ulduar_emergency_fire_botAI, npc_ulduar_flames_initial::npc_ulduar_flames_initialAI, npc_ulduar_bot_summon_trigger::npc_ulduar_bot_summon_triggerAI, npc_ulduar_magnetic_core::npc_ulduar_magnetic_coreAI, npc_ulduar_proximity_mine::npc_ulduar_proximity_mineAI, npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI, npc_ulduar_vx001::npc_ulduar_vx001AI, npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI, boss_mimiron::boss_mimironAI, boss_kologarn_eyebeam::boss_kologarn_eyebeamAI, boss_kologarn::boss_kologarnAI, boss_ignis::boss_ignisAI, npc_ulduar_iron_construct::npc_ulduar_iron_constructAI, npc_ulduar_hodir_mage::npc_ulduar_hodir_mageAI, npc_ulduar_hodir_shaman::npc_ulduar_hodir_shamanAI, npc_ulduar_hodir_druid::npc_ulduar_hodir_druidAI, npc_ulduar_hodir_priest::npc_ulduar_hodir_priestAI, npc_ulduar_flash_freeze::npc_ulduar_flash_freezeAI, npc_ulduar_icicle::npc_ulduar_icicleAI, boss_hodir::boss_hodirAI, npc_ulduar_saronite_animus::npc_ulduar_saronite_animusAI, boss_vezax::boss_vezaxAI, boss_freya_nature_bomb::boss_freya_nature_bombAI, boss_freya_summons::boss_freya_summonsAI, boss_freya_healthy_spore::boss_freya_healthy_sporeAI, boss_freya_lifebinder::boss_freya_lifebinderAI, boss_freya_elder_ironbranch::boss_freya_elder_ironbranchAI, boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI, boss_freya_elder_stonebark::boss_freya_elder_stonebarkAI, boss_freya::boss_freyaAI, npc_mechanolift::npc_mechanoliftAI, boss_flame_leviathan_safety_container::boss_flame_leviathan_safety_containerAI, npc_storm_beacon_spawn::npc_storm_beacon_spawnAI, npc_thorims_hammer::npc_thorims_hammerAI, npc_mimirons_inferno::npc_mimirons_infernoAI, npc_hodirs_fury::npc_hodirs_furyAI, npc_freya_ward::npc_freya_wardAI, boss_flame_leviathan_defense_turret::boss_flame_leviathan_defense_turretAI, boss_flame_leviathan_seat::boss_flame_leviathan_seatAI, boss_flame_leviathan::boss_flame_leviathanAI, npc_auriaya_feral_defender::npc_auriaya_feral_defenderAI, npc_auriaya_sanctum_sentry::npc_auriaya_sanctum_sentryAI, boss_auriaya::boss_auriayaAI, boss_stormcaller_brundir::boss_stormcaller_brundirAI, boss_runemaster_molgeim::boss_runemaster_molgeimAI, boss_steelbreaker::boss_steelbreakerAI, npc_algalon_worm_hole::npc_algalon_worm_holeAI, npc_living_constellation::npc_living_constellationAI, npc_brann_bronzebeard_algalon::npc_brann_bronzebeard_algalonAI, boss_algalon_the_observer::boss_algalon_the_observerAI, iron_golem_custodian::iron_golem_custodianAI, dark_rune_stormcaller::dark_rune_stormcallerAI, dark_rune_protectors::dark_rune_protectorsAI, boss_sjonnir_malformed_ooze::boss_sjonnir_malformed_oozeAI, boss_sjonnir_iron_sludge::boss_sjonnir_iron_sludgeAI, boss_sjonnir::boss_sjonnirAI, boss_maiden_of_grief::boss_maiden_of_griefAI, boss_krystallus::boss_krystallusAI, npc_hol_monument::npc_hol_monumentAI, npc_molten_golem::npc_molten_golemAI, boss_volkhan::boss_volkhanAI, boss_loken::boss_lokenAI, boss_ionar::boss_ionarAI, npc_stormforged_lieutenant::npc_stormforged_lieutenantAI, npc_oculus_drake::npc_oculus_drakeAI, npc_oculus_drakegiver::npc_oculus_drakegiverAI, boss_varos::boss_varosAI, boss_urom::boss_uromAI, boss_eregos::boss_eregosAI, npc_oculus_unstable_sphere::npc_oculus_unstable_sphereAI, boss_drakos::boss_drakosAI, npc_crystalline_frayer::npc_crystalline_frayerAI, npc_crystal_spike::npc_crystal_spikeAI, boss_ormorok::boss_ormorokAI, boss_magus_telestra::boss_magus_telestraAI, boss_keristrasza::boss_keristraszaAI, boss_commander_stoutbeard::boss_commander_stoutbeardAI, boss_anomalus::boss_anomalusAI, npc_alexstrasza::npc_alexstraszaAI, npc_hover_disk::npc_hover_diskAI, npc_scion_of_eternity::npc_scion_of_eternityAI, npc_nexus_lord::npc_nexus_lordAI, npc_power_spark::npc_power_sparkAI, npc_vortex_ride::npc_vortex_rideAI, boss_malygos::boss_malygosAI, boss_naxxramas_misc::boss_naxxramas_miscAI, boss_thaddius_summon::boss_thaddius_summonAI, boss_thaddius::boss_thaddiusAI, boss_sapphiron::boss_sapphironAI, boss_razuvious_minion::boss_razuvious_minionAI, boss_razuvious::boss_razuviousAI, boss_patchwerk::boss_patchwerkAI, boss_noth::boss_nothAI, boss_maexxna::boss_maexxnaAI, boss_loatheb::boss_loathebAI, boss_kelthuzad_minion::boss_kelthuzad_minionAI, boss_kelthuzad::boss_kelthuzadAI, boss_heigan::boss_heiganAI, boss_grobbulus_poison_cloud::boss_grobbulus_poison_cloudAI, boss_grobbulus::boss_grobbulusAI, npc_boss_gothik_minion::npc_boss_gothik_minionAI, boss_gothik::boss_gothikAI, boss_gluth::boss_gluthAI, boss_four_horsemen::boss_four_horsemenAI, boss_faerlina::boss_faerlinaAI, boss_anubrekhan::boss_anubrekhanAI, boss_isle_of_conquest::boss_isle_of_conquestAI, npc_ioc_gunship_captain::npc_ioc_gunship_captainAI, npc_isle_of_conquest_turret::npc_isle_of_conquest_turretAI, npc_icc_putricades_trap::npc_icc_putricades_trapAI, npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI, npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI, npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI, npc_icc_spire_frostwyrm::npc_icc_spire_frostwyrmAI, npc_icc_severed_essence::npc_icc_severed_essenceAI, npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI, npc_icc_skybreaker_luminary::npc_icc_skybreaker_luminaryAI, npc_icc_skybreaker_vicar::npc_icc_skybreaker_vicarAI, npc_icc_skybreaker_marksman::npc_icc_skybreaker_marksmanAI, npc_icc_skybreaker_hierophant::npc_icc_skybreaker_hierophantAI, npc_arthas_teleport_visual::npc_arthas_teleport_visualAI, npc_impaling_spear::npc_impaling_spearAI, npc_frostwing_vrykul::npc_frostwing_vrykulAI, npc_captain_rupert::npc_captain_rupertAI, npc_captain_grondel::npc_captain_grondelAI, npc_captain_brandon::npc_captain_brandonAI, npc_captain_arnath::npc_captain_arnathAI, boss_sister_svalna::boss_sister_svalnaAI, npc_crok_scourgebane::npc_crok_scourgebaneAI, npc_frost_freeze_trap::npc_frost_freeze_trapAI, npc_rotting_frost_giant::npc_rotting_frost_giantAI, npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI, npc_gluttonous_abomination::npc_gluttonous_abominationAI, npc_blistering_zombie::npc_blistering_zombieAI, npc_blazing_skeleton::npc_blazing_skeletonAI, npc_valithria_cloud::npc_valithria_cloudAI, npc_risen_archmage::npc_risen_archmageAI, npc_the_lich_king_controller::npc_the_lich_king_controllerAI, npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI, boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI, npc_lk_spirit_bomb::npc_lk_spirit_bombAI, npc_spirit_warden::npc_spirit_wardenAI, npc_terenas_menethil::npc_terenas_menethilAI, npc_strangulate_vehicle::npc_strangulate_vehicleAI, npc_valkyr_shadowguard::npc_valkyr_shadowguardAI, npc_raging_spirit::npc_raging_spiritAI, npc_icc_ice_sphere::npc_icc_ice_sphereAI, npc_shambling_horror_icc::npc_shambling_horror_iccAI, npc_tirion_fordring_tft::npc_tirion_fordringAI, boss_the_lich_king::boss_the_lich_kingAI, npc_sindragosa_trash::npc_sindragosa_trashAI, npc_rimefang::npc_rimefangAI, npc_spinestalker::npc_spinestalkerAI, npc_ice_tomb::npc_ice_tombAI, boss_sindragosa::boss_sindragosaAI, npc_precious_icc::npc_precious_iccAI, npc_big_ooze::npc_big_oozeAI, npc_little_ooze::npc_little_oozeAI, boss_rotface::boss_rotfaceAI, npc_putricide_oozeAI, boss_professor_putricide::boss_professor_putricideAI, npc_bone_spike::npc_bone_spikeAI, npc_coldflame::npc_coldflameAI, boss_lord_marrowgar, npc_darnavan::npc_darnavanAI, npc_vengeful_shade::npc_vengeful_shadeAI, npc_cult_adherent::npc_cult_adherentAI, npc_cult_fanatic::npc_cult_fanaticAI, boss_lady_deathwhisper::boss_lady_deathwhisperAI, npc_gunship_gunner::npc_gunship_gunnerAI, npc_gunship_mage::npc_gunship_mageAI, npc_gunship_boarding_add::npc_gunship_boarding_add_realAI, npc_gunship_boarding_leader::npc_gunship_boarding_leaderAI, npc_gunship_boarding_addAI, npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI, npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI, npc_stinky_icc::npc_stinky_iccAI, boss_festergut::boss_festergutAI, npc_icc_blood_beast::npc_icc_blood_beastAI, npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI, npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI, boss_deathbringer_saurfang::boss_deathbringer_saurfangAI, boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI, npc_kinetic_bomb::npc_kinetic_bombAI, npc_dark_nucleus::npc_dark_nucleusAI, npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI, boss_prince_valanar_icc::boss_prince_valanarAI, boss_prince_taldaram_icc::boss_prince_taldaramAI, boss_prince_keleseth_icc::boss_prince_kelesethAI, boss_slad_ran::boss_slad_ranAI, boss_moorabi::boss_moorabiAI, boss_gal_darah::boss_gal_darahAI, boss_eck::boss_eckAI, npc_living_mojo::npc_living_mojoAI, boss_drakkari_elemental::boss_drakkari_elementalAI, boss_drakkari_colossus::boss_drakkari_colossusAI, npc_frostbite_invisible_stalker::npc_frostbite_invisible_stalkerAI, npc_pos_leader_second::npc_pos_leader_secondAI, npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI, npc_pos_collapsing_icicle::npc_pos_collapsing_icicleAI, npc_pos_icicle_trigger::npc_pos_icicle_triggerAI, npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI, npc_pos_after_first_boss::npc_pos_after_first_bossAI, npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI, npc_pos_leader::npc_pos_leaderAI, boss_tyrannus::boss_tyrannusAI, boss_krick::boss_krickAI, boss_ick::boss_ickAI, boss_garfrost::boss_garfrostAI, npc_hor_lumbering_abomination::npc_hor_lumbering_abominationAI, npc_hor_risen_witch_doctor::npc_hor_risen_witch_doctorAI, npc_hor_leader_second::npc_hor_leader_secondAI, npc_hor_lich_king::npc_hor_lich_kingAI, npc_hor_spiritual_reflection::npc_hor_spiritual_reflectionAI, boss_frostsworn_general::boss_frostsworn_generalAI, npc_tortured_rifleman::npc_tortured_riflemanAI, npc_spectral_footman::npc_spectral_footmanAI, npc_shadowy_mercenary::npc_shadowy_mercenaryAI, npc_phantom_hallucination::npc_phantom_hallucinationAI, npc_phantom_mage::npc_phantom_mageAI, npc_ghostly_priest::npc_ghostly_priestAI, npc_hor_leader::npc_hor_leaderAI, boss_marwyn::boss_marwynAI, boss_falric::boss_falricAI, npc_fos_leader::npc_fos_leaderAI, boss_devourer_of_souls::boss_devourer_of_soulsAI, npc_fos_corrupted_soul_fragment::npc_fos_corrupted_soul_fragmentAI, boss_bronjahm::boss_bronjahmAI, boss_trollgore::boss_trollgoreAI, boss_tharon_ja::boss_tharon_jaAI, boss_novos::boss_novosAI, boss_dred::boss_dredAI, boss_twin_valkyrAI, boss_icehowl::boss_icehowlAI, boss_jormungarAI, boss_gormok::boss_gormokAI, npc_snobold_vassal::npc_snobold_vassalAI, npc_mistress_of_pain::npc_mistress_of_painAI, npc_fel_infernal::npc_fel_infernalAI, boss_jaraxxus::boss_jaraxxusAI, npc_toc_pet_hunter::npc_toc_pet_hunterAI, npc_toc_pet_warlock::npc_toc_pet_warlockAI, npc_toc_retro_paladin::npc_toc_retro_paladinAI, npc_toc_enh_shaman::npc_toc_enh_shamanAI, npc_toc_rogue::npc_toc_rogueAI, npc_toc_dk::npc_toc_dkAI, npc_toc_warrior::npc_toc_warriorAI, npc_toc_boomkin::npc_toc_boomkinAI, npc_toc_hunter::npc_toc_hunterAI, npc_toc_mage::npc_toc_mageAI, npc_toc_warlock::npc_toc_warlockAI, npc_toc_shadow_priest::npc_toc_shadow_priestAI, npc_toc_priest::npc_toc_priestAI, npc_toc_paladin::npc_toc_paladinAI, npc_toc_shaman::npc_toc_shamanAI, npc_toc_druid::npc_toc_druidAI, boss_faction_championsAI, npc_anubarak_spike::npc_anubarak_spikeAI, npc_nerubian_burrower::npc_nerubian_burrowerAI, npc_frost_sphere::npc_frost_sphereAI, npc_swarm_scarab::npc_swarm_scarabAI, boss_anubarak_trial::boss_anubarak_trialAI, boss_grand_champion::boss_grand_championAI, npc_toc5_grand_champion_minion::npc_toc5_grand_champion_minionAI, npc_toc5_player_vehicle::npc_toc5_player_vehicleAI, npc_black_knight_ghoul::npc_black_knight_ghoulAI, boss_black_knight::boss_black_knightAI, npc_argent_soldier::npc_argent_soldierAI, npc_memory::npc_memoryAI, boss_paletress::boss_paletressAI, boss_eadric::boss_eadricAI, boss_saviana_ragefire::boss_saviana_ragefireAI, npc_halion_controller::npc_halion_controllerAI, boss_twilight_halion::boss_twilight_halionAI, boss_halion::boss_halionAI, boss_general_zarithrian::boss_general_zarithrianAI, npc_xerestrasza::npc_xerestraszaAI, npc_baltharus_the_warborn_clone::npc_baltharus_the_warborn_cloneAI, boss_baltharus_the_warborn::boss_baltharus_the_warbornAI, npc_twilight_summon::npc_twilight_summonAI, boss_sartharion::boss_sartharionAI, boss_krik_thir::boss_krik_thirAI, npc_anub_ar_crusher::npc_anub_ar_crusherAI, boss_hadronox::boss_hadronoxAI, boss_anub_arak::boss_anub_arakAI, boss_taldaram::boss_taldaramAI, npc_taldaram_flamesphere::npc_taldaram_flamesphereAI, npc_twilight_volunteer::npc_twilight_volunteerAI, boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI, boss_volazj::boss_volazjAI, npc_ahnkahar_nerubian::npc_ahnkahar_nerubianAI, boss_elder_nadox::boss_elder_nadoxAI, npc_amanitar_mushrooms::npc_amanitar_mushroomsAI, npc_shadowpriest_sezziz::npc_shadowpriest_sezzizAI, npc_weegli_blastfuse::npc_weegli_blastfuseAI, npc_sergeant_bly::npc_sergeant_blyAI, npc_ame::npc_ameAI, npc_cairne_bloodhoof::npc_cairne_bloodhoofAI, npc_plucky::npc_pluckyAI, npc_twiggy_flathead::npc_twiggy_flatheadAI, npc_taskmaster_fizzule::npc_taskmaster_fizzuleAI, npc_custodian_of_time::npc_custodian_of_timeAI, npc_aquementas::npc_aquementasAI, npc_anachronos_quest_trigger::npc_anachronos_quest_triggerAI, npc_qiraj_war_spawn::npc_qiraj_war_spawnAI, npc_anachronos_the_ancient::npc_anachronos_the_ancientAI, npc_thrall_warchief::npc_thrall_warchiefAI, npc_shenthul::npc_shenthulAI, npc_giant_spotlight::npc_giant_spotlightAI, npc_omen::npc_omenAI, npc_clintar_spirit::npc_clintar_spiritAI, npc_shay_leafrunner::npc_shay_leafrunnerAI, npc_tiger_matriarch::npc_tiger_matriarchAI, npc_tiger_matriarch_credit::npc_tiger_matriarch_creditAI, npc_murkdeep::npc_murkdeepAI, npc_stillpine_capitive::npc_stillpine_capitiveAI, npc_death_ravager::npc_death_ravagerAI, npc_draenei_survivor::npc_draenei_survivorAI, npc_depth_charge::npc_depth_chargeAI, npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI, npc_spitelashes::npc_spitelashesAI, npc_muglash::npc_muglashAI, boss_viscidus::boss_viscidusAI, boss_veklor::boss_veklorAI, boss_veknilash::boss_veknilashAI, boss_skeram::boss_skeramAI, npc_sartura_royal_guard::npc_sartura_royal_guardAI, boss_sartura::boss_sarturaAI, boss_ouro::boss_ouroAI, boss_huhuran::boss_huhuranAI, boss_fankriss::boss_fankrissAI, npc_giant_eye_tentacle::giant_eye_tentacleAI, npc_giant_claw_tentacle::giant_claw_tentacleAI, npc_claw_tentacle::claw_tentacleAI, npc_eye_tentacle::eye_tentacleAI, boss_cthun::cthunAI, boss_eye_of_cthun::eye_of_cthunAI, boss_yauj::boss_yaujAI, boss_vem::boss_vemAI, boss_kri::boss_kriAI, boss_rajaxx::boss_rajaxxAI, boss_ossirian::boss_ossirianAI, boss_moam::boss_moamAI, boss_kurinnaxx::boss_kurinnaxxAI, boss_buru::boss_buruAI, npc_hive_zara_larva::npc_hive_zara_larvaAI, boss_ayamiss::boss_ayamissAI, npc_belnistrasz::npc_belnistraszAI, npc_onyxian_lair_guard::npc_onyxian_lair_guardAI, boss_onyxia::boss_onyxiaAI, npc_time_rift::npc_time_riftAI, npc_medivh_bm::npc_medivh_bmAI, boss_temporus::boss_temporusAI, boss_chrono_lord_deja::boss_chrono_lord_dejaAI, boss_aeonus::boss_aeonusAI, npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI, boss_lieutenant_drake::boss_lieutenant_drakeAI, boss_epoch_hunter::boss_epoch_hunterAI, boss_captain_skarloc::boss_captain_skarlocAI, npc_cos_stratholme_citizien::npc_cos_stratholme_citizienAI, npc_arthas::npc_arthasAI, boss_salramm::boss_salrammAI, boss_meathook::boss_meathookAI, boss_mal_ganis::boss_mal_ganisAI, boss_infinite_corruptor::boss_infinite_corruptorAI, boss_epoch::boss_epochAI, hyjalAI, hyjal_trashAI, alliance_rifleman::alliance_riflemanAI, npc_gargoyle::npc_gargoyleAI, npc_frost_wyrm::npc_frost_wyrmAI, npc_fel_stalker::npc_fel_stalkerAI, npc_crypt_fiend::npc_crypt_fiendAI, npc_banshee::npc_bansheeAI, npc_necromancer::npc_necromancerAI, npc_ghoul::npc_ghoulAI, npc_abomination::npc_abominationAI, npc_giant_infernal::npc_giant_infernalAI, boss_rage_winterchill::boss_rage_winterchillAI, boss_kazrogal::boss_kazrogalAI, npc_lesser_doomguard::npc_lesser_doomguardAI, boss_azgalor::boss_azgalorAI, boss_archimonde::boss_archimondeAI, npc_doomfire_targetting::npc_doomfire_targettingAI, npc_ancient_wisp::npc_ancient_wispAI, npc_towering_infernal::npc_towering_infernalAI, boss_anetheron::boss_anetheronAI, boss_azuregos::boss_azuregosAI, npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI, npc_midsummer_torch_target::npc_midsummer_torch_targetAI, npc_love_in_air_hummel_helper::npc_love_in_air_hummel_helperAI, npc_love_in_air_hummel::npc_love_in_air_hummelAI, npc_love_in_air_snivel_real::npc_love_in_air_snivel_realAI, npc_love_in_air_snivel::npc_love_in_air_snivelAI, npc_love_in_air_supply_sentry::npc_love_in_air_supply_sentryAI, boss_headless_horseman_pumpkin::boss_headless_horseman_pumpkinAI, boss_headless_horseman_head::boss_headless_horseman_headAI, boss_headless_horseman::boss_headless_horsemanAI, npc_hallows_end_train_fire::npc_hallows_end_train_fireAI, npc_hallows_end_soh::npc_hallows_end_sohAI, npc_costumed_orphan_matron::npc_costumed_orphan_matronAI, npc_alexstraza_the_lifebinder::npc_alexstraza_the_lifebinderAI, npc_the_etymidian::npc_the_etymidianAI, npc_elder_kekek::npc_elder_kekekAI, npc_high_oracle_soo_roo::npc_high_oracle_soo_rooAI, npc_the_biggest_tree::npc_the_biggest_treeAI, npc_snowfall_glade_playmate::npc_snowfall_glade_playmateAI, npc_winterfin_playmate::npc_winterfin_playmateAI, npc_coren_direbrew_sisters::npc_coren_direbrew_sistersAI, npc_coren_direbrew::npc_coren_direbrewAI, npc_brew_bubble::npc_brew_bubbleAI, npc_brewfest_super_brew_trigger::npc_brewfest_super_brew_triggerAI, npc_dark_iron_guzzler::npc_dark_iron_guzzlerAI, npc_dark_iron_attack_mole_machine::npc_dark_iron_attack_mole_machineAI, npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI, boss_wushoolay::boss_wushoolayAI, boss_venoxis::boss_venoxisAI, npc_zealot_zath::npc_zealot_zathAI, npc_zealot_lorkhan::npc_zealot_lorkhanAI, boss_thekal::boss_thekalAI, boss_renataki::boss_renatakiAI, npc_spawn_of_marli::npc_spawn_of_marliAI, boss_marli::boss_marliAI, npc_vilebranch_speaker::npc_vilebranch_speakerAI, npc_ohgan::npc_ohganAI, boss_mandokir::boss_mandokirAI, npc_shade_of_jindo::npc_shade_of_jindoAI, npc_healing_ward::npc_healing_wardAI, boss_jindo::boss_jindoAI, npc_batrider::npc_batriderAI, boss_jeklik::boss_jeklikAI, boss_hazzarah::boss_hazzarahAI, boss_hakkar::boss_hakkarAI, boss_grilek::boss_grilekAI, boss_gahzranka::boss_gahzrankaAI, npc_zulian_prowler::npc_zulian_prowlerAI, boss_arlokk::boss_arlokkAI, npc_harrison_jones::npc_harrison_jonesAI, npc_forest_frog::npc_forest_frogAI, boss_zuljin::boss_zuljinAI, boss_nalorakk::boss_nalorakkAI, npc_janalai_hatchling::npc_janalai_hatchlingAI, npc_janalai_hatcher::npc_janalai_hatcherAI, boss_janalai::boss_janalaiAI, boss_koragg::boss_koraggAI, boss_fenstalker::boss_fenstalkerAI, boss_slither::boss_slitherAI, boss_darkheart::boss_darkheartAI, boss_lord_raadan::boss_lord_raadanAI, boss_gazakrothAI, boss_alyson_antille::boss_alyson_antilleAI, boss_thurg::boss_thurgAI, boss_hexlord_malacrass::boss_hex_lord_malacrassAI, npc_halazzi_lynx::npc_halazzi_lynxAI, boss_halazzi::boss_halazziAI, npc_akilzon_eagle::npc_akilzon_eagleAI, boss_akilzon::boss_akilzonAI, npc_lady_sylvanas_windrunner_bfu::npc_lady_sylvanas_windrunner_bfuAI, npc_thrall_bfu::npc_thrall_bfuAI, boss_blight_worm::boss_blight_wormAI, npc_jaina_proudmoore_bfu::npc_jaina_proudmoore_bfuAI, npc_varian_wrynn::npc_varian_wrynnAI, npc_highborne_lamenter::npc_highborne_lamenterAI, npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI, npc_calvin_montague::npc_calvin_montagueAI, npc_yenniku::npc_yennikuAI, pyrewood_ambush::pyrewood_ambushAI, npc_corporal_keeshan::npc_corporal_keeshanAI, npc_grand_magister_rommath::npc_grand_magister_rommathAI, npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI, npc_balance_of_light_and_shadow::npc_balance_of_light_and_shadowAI, npc_eris_hevenfire::npc_eris_hevenfireAI, boss_twilight_corrupter::boss_twilight_corrupterAI, npc_professor_phizzlethorpe::npc_professor_phizzlethorpeAI, npc_singularity::npc_singularityAI, boss_entropius::boss_entropiusAI, boss_muru::boss_muruAI, npc_kalecgos_kj::npc_kalecgos_kjAI, boss_kiljaeden::boss_kiljaedenAI, npc_kiljaeden_controller::npc_kiljaeden_controllerAI, boss_sathrovarr::boss_sathrovarrAI, boss_kalec::boss_kalecAI, boss_kalecgos::boss_kalecgosAI, npc_demonic_vapor_trail::npc_demonic_vapor_trailAI, boss_felmyst::boss_felmystAI, boss_alythess::boss_alythessAI, boss_sacrolash::boss_sacrolashAI, npc_madrigosa::npc_madrigosaAI, boss_brutallus::boss_brutallusAI, boss_baroness_anastari::boss_baroness_anastariAI, npc_scholomance_occultist::npc_scholomance_occultistAI, boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI, boss_darkmaster_gandling::boss_darkmaster_gandlingAI, boss_high_inquisitor_whitemane::boss_high_inquisitor_whitemaneAI, npc_mograine::npc_mograineAI, npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI, npc_highlord_darion_mograine::npc_highlord_darion_mograineAI, npc_a_special_surprise::npc_a_special_surpriseAI, npc_high_inquisitor_valroth::npc_high_inquisitor_valrothAI, npc_scarlet_courier::npc_scarlet_courierAI, npc_crusade_persuaded::npc_crusade_persuadedAI, npc_scarlet_miner::npc_scarlet_minerAI, npc_unworthy_initiate::npc_unworthy_initiateAI, npc_scarlet_cannon::npc_scarlet_cannonAI, npc_dkc1_gothik::npc_dkc1_gothikAI, npc_scarlet_ghoul::npc_scarlet_ghoulAI, npc_death_knight_initiate::npc_death_knight_initiateAI, npc_eye_of_acherus::npc_eye_of_acherusAI, boss_vexallus::boss_vexallusAI, boss_selin_fireheart::boss_selin_fireheartAI, boss_zelfan::boss_zelfanAI, boss_apoko::boss_apokoAI, boss_garaxxas::boss_garaxxasAI, boss_warlord_salaris::boss_warlord_salarisAI, boss_yazzai::boss_yazzaiAI, boss_eramas_brightblaze::boss_eramas_brightblazeAI, boss_ellris_duskhallow::boss_ellris_duskhallowAI, boss_kagani_nightstrike::boss_kagani_nightstrikeAI, boss_priestess_lackey_commonAI, boss_priestess_delrissa::boss_priestess_delrissaAI, boss_felblood_kaelthas::boss_felblood_kaelthasAI, npc_image_of_medivh::npc_image_of_medivhAI, npc_barnes::npc_barnesAI, boss_romulo::boss_romuloAI, boss_julianne::boss_julianneAI, boss_bigbadwolf::boss_bigbadwolfAI, npc_cyclone::npc_cycloneAI, boss_crone::boss_croneAI, boss_roar::boss_roarAI, boss_tinhead::boss_tinheadAI, boss_strawman::boss_strawmanAI, npc_tito::npc_titoAI, boss_dorothee::boss_dorotheeAI, boss_terestian_illhoof::boss_terestianAI, npc_fiendish_imp::npc_fiendish_impAI, npc_kilrek::npc_kilrekAI, npc_aran_elemental::water_elementalAI, boss_shade_of_aran::boss_aranAI, boss_servant_quarters::boss_servant_quartersAI, prince_axes::prince_axesAI, boss_malchezaar::boss_malchezaarAI, netherspite_infernal::netherspite_infernalAI, boss_nightbane::boss_nightbaneAI, boss_netherspite::boss_netherspiteAI, boss_moroes::boss_moroesAI, boss_attumen_midnight::boss_attumen_midnightAI, boss_attumen::boss_attumenAI, boss_midnight::boss_midnightAI, boss_maiden_of_virtue::boss_maiden_of_virtueAI, boss_curator::boss_curatorAI, npc_kernobee::npc_kernobeeAI, boss_mr_smite::boss_mr_smiteAI, npc_mc_core_hound::npc_mc_core_houndAI, npc_flamewaker_priest::npc_flamewaker_priestAI, boss_ragnaros::boss_ragnarosAI, boss_majordomo::boss_majordomoAI, npc_core_rager::npc_core_ragerAI, boss_golemagg::boss_golemaggAI, boss_garr::boss_garrAI, boss_vaelastrasz::boss_vaelAI, boss_razorgore::boss_razorgoreAI, boss_nefarian::boss_nefarianAI, boss_victor_nefarius::boss_victor_nefariusAI, boss_flamegor::boss_flamegorAI, boss_firemaw::boss_firemawAI, boss_ebonroc::boss_ebonrocAI, boss_chromaggus::boss_chromaggusAI, boss_broodlord::boss_broodlordAI, boss_urok_doomhowl::boss_urok_doomhowlAI, boss_the_beast::boss_thebeastAI, boss_solakar_flamewreath::boss_solakar_flamewreathAI, npc_rookery_hatcher::npc_rookery_hatcherAI, boss_rend_blackhand::boss_rend_blackhandAI, boss_quartermaster_zigris, npc_blackhand_incarcerator::npc_blackhand_incarceratorAI, boss_pyroguard_emberseer::boss_pyroguard_emberseerAI, boss_overlord_wyrmthalak::boss_overlordwyrmthalakAI, boss_lord_valthalak::boss_lord_valthalakAI, boss_highlord_omokk::boss_highlordomokkAI, boss_halycon::boss_halyconAI, boss_gyth::boss_gythAI, chromatic_elite_guard::chromatic_elite_guardAI, boss_drakkisath::boss_drakkisathAI, boss_doomrel::boss_doomrelAI, boss_moira_bronzebeard::boss_moira_bronzebeardAI, boss_magmus::boss_magmusAI, boss_high_interrogator_gerstahn::boss_high_interrogator_gerstahnAI, boss_grizzle::boss_grizzleAI, boss_gorosh_the_dervish::boss_gorosh_the_dervishAI, boss_general_angerforge::boss_general_angerforgeAI, boss_emperor_dagran_thaurissan::boss_draganthaurissanAI, boss_anubshiah::boss_anubshiahAI, boss_ambassador_flamelash::boss_ambassador_flamelashAI, npc_rocknot::npc_rocknotAI, npc_phalanx::npc_phalanxAI, boss_vanndar::boss_vanndarAI, boss_galvangar::boss_galvangarAI, boss_drekthar::boss_drektharAI, boss_balinda::boss_balindaAI, npc_water_elemental::npc_water_elementalAI, npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI, SmartAI, npc_escortAI, WorldBossAI, BossAI, ScriptedAI, SimpleCharmedAI, TotemAI, ReactorAI, VehicleAI, TurretAI, ArcherAI, CasterAI, CombatAI, boss_sartharion_dragonAI, and npc_razzashi_cobra_venoxis::npc_razzashi_cobra_venoxis_AI.
Referenced by Creature::Update().
Member Data Documentation
AISpellInfo
AISpellInfoType * UnitAI::AISpellInfo static
Definition at line 310 of file UnitAI.h.
Referenced by DoCast(), CasterAI::EnterCombat(), CombatAI::EnterCombat(), FillAISpellInfo(), GetAISpellInfo(), CasterAI::InitializeAI(), CombatAI::JustDied(), and CombatAI::UpdateAI().
me
Unit* const UnitAI::me protected
Definition at line 179 of file UnitAI.h.
Referenced by AttackStart(), AttackStartCaster(), DoAddAuraToAllHostilePlayers(), DoCast(), DoCastAOE(), DoCastRandomTarget(), DoCastSelf(), DoCastToAllHostilePlayers(), DoCastVictim(), DoMeleeAttackIfReady(), DoSpellAttackIfReady(), InitializeAI(), SelectTarget(), and SelectTargetList().
The documentation for this class was generated from the following files:
src/server/game/AI/CoreAI/UnitAI.h
src/server/game/AI/CoreAI/UnitAI.cpp
src/server/game/AI/CreatureAI.cpp