Azerotcore-wotlk: npc_engineering_tele_trinket Class Reference
npc_engineering_tele_trinket Class Reference
Public Member Functions
npc_engineering_tele_trinket ()
bool CanLearn (Player *player, uint32 textId, uint32 altTextId, uint32 skillValue, uint32 reqSpellId, uint32 spellId, uint32 &npcTextId)
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *creature, uint32 sender, uint32 action) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 850 of file npc_professions.cpp.
Constructor & Destructor Documentation
npc_engineering_tele_trinket()
npc_engineering_tele_trinket::npc_engineering_tele_trinket () inline
Definition at line 853 of file npc_professions.cpp.
 : CreatureScript("npc_engineering_tele_trinket") { }
Member Function Documentation
CanLearn()
bool npc_engineering_tele_trinket::CanLearn (Player * player, uint32 textId, uint32 altTextId, uint32 skillValue, uint32 reqSpellId, uint32 spellId, uint32 & npcTextId) inline
Definition at line 855 of file npc_professions.cpp.
     {
         bool res = false;
         npcTextId = textId;
         if (player->GetBaseSkillValue(SKILL_ENGINEERING) >= skillValue && player->HasSpell(reqSpellId))
         {
             if (!player->HasSpell(spellId))
                 res = true;
             else
                 npcTextId = altTextId;
         }
         return res;
     }
References Player::GetBaseSkillValue(), Player::HasSpell(), and SKILL_ENGINEERING.
Referenced by OnGossipHello().
OnGossipHello()
bool npc_engineering_tele_trinket::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 869 of file npc_professions.cpp.
     {
         uint32 npcTextId = 0;
         std::string gossipItem;
         bool canLearn = false;
         if (player->HasSkill(SKILL_ENGINEERING))
         {
             switch (creature->GetEntry())
             {
                 case NPC_ZAP:
                     canLearn = CanLearn(player, 6092, 0, 260, S_GOBLIN, SPELL_TO_EVERLOOK, npcTextId);
                     if (canLearn)
                         gossipItem = GOSSIP_ITEM_ZAP;
                     break;
                 case NPC_JHORDY:
                     canLearn = CanLearn(player, 7251, 7252, 260, S_GNOMISH, SPELL_TO_GADGET, npcTextId);
                     if (canLearn)
                         gossipItem = GOSSIP_ITEM_JHORDY;
                     break;
                 case NPC_KABLAM:
                     canLearn = CanLearn(player, 10365, 0, 350, S_GOBLIN, SPELL_TO_AREA52, npcTextId);
                     if (canLearn)
                         gossipItem = GOSSIP_ITEM_KABLAM;
                     break;
                 case NPC_SMILES:
                     canLearn = CanLearn(player, 10363, 0, 350, S_GNOMISH, SPELL_TO_TOSHLEY, npcTextId);
                     if (canLearn)
                         gossipItem = GOSSIP_ITEM_KABLAM;
                     break;
             }
         }
         if (canLearn)
             AddGossipItemFor(player, GOSSIP_ICON_CHAT, gossipItem, creature->GetEntry(), GOSSIP_ACTION_INFO_DEF + 1);
         SendGossipMenuFor(player, npcTextId ? npcTextId : player->GetGossipTextId(creature), creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), CanLearn(), Object::GetEntry(), Player::GetGossipTextId(), Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_JHORDY, GOSSIP_ITEM_KABLAM, GOSSIP_ITEM_ZAP, Player::HasSkill(), NPC_JHORDY, NPC_KABLAM, NPC_SMILES, NPC_ZAP, S_GNOMISH, S_GOBLIN, SendGossipMenuFor(), SKILL_ENGINEERING, SPELL_TO_AREA52, SPELL_TO_EVERLOOK, SPELL_TO_GADGET, and SPELL_TO_TOSHLEY.
OnGossipSelect()
bool npc_engineering_tele_trinket::OnGossipSelect (Player * player, Creature * creature, uint32 sender, uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 909 of file npc_professions.cpp.
     {
         ClearGossipMenuFor(player);
         if (action == GOSSIP_ACTION_INFO_DEF + 1)
             CloseGossipMenuFor(player);
         if (sender != creature->GetEntry())
             return true;
         switch (sender)
         {
             case NPC_ZAP:
                 player->CastSpell(player, SPELL_LEARN_TO_EVERLOOK, false);
                 break;
             case NPC_JHORDY:
                 player->CastSpell(player, SPELL_LEARN_TO_GADGET, false);
                 break;
             case NPC_KABLAM:
                 player->CastSpell(player, SPELL_LEARN_TO_AREA52, false);
                 break;
             case NPC_SMILES:
                 player->CastSpell(player, SPELL_LEARN_TO_TOSHLEY, false);
                 break;
         }
         return true;
     }
References Unit::CastSpell(), ClearGossipMenuFor(), CloseGossipMenuFor(), Object::GetEntry(), GOSSIP_ACTION_INFO_DEF, NPC_JHORDY, NPC_KABLAM, NPC_SMILES, NPC_ZAP, SPELL_LEARN_TO_AREA52, SPELL_LEARN_TO_EVERLOOK, SPELL_LEARN_TO_GADGET, and SPELL_LEARN_TO_TOSHLEY.
The documentation for this class was generated from the following file:
src/server/scripts/World/npc_professions.cpp