Azerotcore-wotlk: G3D::AlignedMemoryManager Class Reference
G3D::AlignedMemoryManager Class Reference
#include <MemoryManager.h>
Public Types
typedef shared_ptr< class AlignedMemoryManager > Ref
Public Types inherited from G3D::MemoryManager
typedef shared_ptr< class MemoryManager > Ref
Public Member Functions
virtual void * alloc (size_t s)
virtual void free (void *ptr)
virtual bool isThreadsafe () const
Public Member Functions inherited from G3D::ReferenceCountedObject
virtual ~ReferenceCountedObject ()
Static Public Member Functions
static AlignedMemoryManager::Ref create ()
Static Public Member Functions inherited from G3D::MemoryManager
static MemoryManager::Ref create ()
Protected Member Functions
AlignedMemoryManager ()
Protected Member Functions inherited from G3D::MemoryManager
MemoryManager ()
Detailed Description
Allocates memory on 16-byte boundaries.
See also
MemoryManager, CRTMemoryManager, AreaMemoryManager
Definition at line 55 of file MemoryManager.h.
Member Typedef Documentation
Ref
typedef shared_ptr<class AlignedMemoryManager> G3D::AlignedMemoryManager::Ref
Definition at line 62 of file MemoryManager.h.
Constructor & Destructor Documentation
AlignedMemoryManager()
G3D::AlignedMemoryManager::AlignedMemoryManager () protected
Definition at line 43 of file MemoryManager.cpp.
 {}
Referenced by create().
Member Function Documentation
alloc()
void * G3D::AlignedMemoryManager::alloc (size_t s) virtual
Return a pointer to s bytes of memory that are unused by the rest of the program. The contents of the memory are undefined
Reimplemented from G3D::MemoryManager.
Definition at line 46 of file MemoryManager.cpp.
{
     return System::alignedMalloc(s, 16);
 }
References G3D::System::alignedMalloc().
create()
AlignedMemoryManager::Ref G3D::AlignedMemoryManager::create () static
Definition at line 61 of file MemoryManager.cpp.
{
     static AlignedMemoryManager::Ref m(new AlignedMemoryManager());
     return m;
 }
References AlignedMemoryManager().
free()
void G3D::AlignedMemoryManager::free (void * ptr) virtual
Invoke to declare that this memory will no longer be used by the program. The memory manager is not required to actually reuse or release this memory.
Reimplemented from G3D::MemoryManager.
Definition at line 51 of file MemoryManager.cpp.
{
     System::alignedFree(ptr);
 }
References G3D::System::alignedFree(), and ptr().
isThreadsafe()
bool G3D::AlignedMemoryManager::isThreadsafe () const virtual
Returns true if this memory manager is threadsafe (i.e., alloc and free can be called asychronously)
Reimplemented from G3D::MemoryManager.
Definition at line 56 of file MemoryManager.cpp.
{
     return true;
 }
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/MemoryManager.h
deps/g3dlite/source/MemoryManager.cpp