Azerotcore-wotlk: npc_love_in_air_snivel::npc_love_in_air_snivelAI Struct Reference
npc_love_in_air_snivel::npc_love_in_air_snivelAI Struct Reference
Public Member Functions
npc_love_in_air_snivelAI (Creature *creature)
void Reset () override
bool AllowAction (Player *player)
void MoveInLineOfSight (Unit *who) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
int32 delay
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 128 of file love_in_air.cpp.
Constructor & Destructor Documentation
npc_love_in_air_snivelAI()
npc_love_in_air_snivel::npc_love_in_air_snivelAI::npc_love_in_air_snivelAI (Creature * creature) inline
Definition at line 130 of file love_in_air.cpp.
                                                      : NullCreatureAI(creature)
         {
         }
Member Function Documentation
AllowAction()
bool npc_love_in_air_snivel::npc_love_in_air_snivelAI::AllowAction (Player * player) inline
Definition at line 142 of file love_in_air.cpp.
         {
             uint16 slot = player->FindQuestSlot(player->GetTeamId() == TEAM_ALLIANCE ? QUEST_HOT_ON_TRAIL_ALLY : QUEST_HOT_ON_TRAIL_HORDE);
             if (slot >= MAX_QUEST_LOG_SIZE)
                 return false;
             QuestStatusData& qData = player->getQuestStatusMap()[(player->GetTeamId() == TEAM_ALLIANCE ? QUEST_HOT_ON_TRAIL_ALLY : QUEST_HOT_ON_TRAIL_HORDE)];
             if (qData.CreatureOrGOCount[me->GetEntry() - NPC_SNIVEL_COUNTER] == 0)
                 return true;
             return false;
         }
References QuestStatusData::CreatureOrGOCount, Player::FindQuestSlot(), Object::GetEntry(), Player::getQuestStatusMap(), Player::GetTeamId(), MAX_QUEST_LOG_SIZE, CreatureAI::me, NPC_SNIVEL_COUNTER, QUEST_HOT_ON_TRAIL_ALLY, QUEST_HOT_ON_TRAIL_HORDE, and TEAM_ALLIANCE.
Referenced by MoveInLineOfSight().
MoveInLineOfSight()
void npc_love_in_air_snivel::npc_love_in_air_snivelAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 155 of file love_in_air.cpp.
         {
             if (delay == 0 && me->GetDistance(who) < 7.0f && who->GetTypeId() == TYPEID_PLAYER)
             {
                 Player* plr = who->ToPlayer();
                 if (AllowAction(plr))
                 {
                     delay = 25000;
                     uint8 index = plr->GetTeamId() * 3 + (me->GetEntry() - NPC_SNIVEL_COUNTER);
                     plr->CastSpell(plr, spellTable[index], true);
                 }
             }
         }
References AllowAction(), Unit::CastSpell(), delay, WorldObject::GetDistance(), Object::GetEntry(), Player::GetTeamId(), Object::GetTypeId(), CreatureAI::me, NPC_SNIVEL_COUNTER, spellTable, Object::ToPlayer(), and TYPEID_PLAYER.
Reset()
void npc_love_in_air_snivel::npc_love_in_air_snivelAI::Reset () inline override virtual
Reimplemented from UnitAI.
Definition at line 136 of file love_in_air.cpp.
         {
             delay = 0;
             me->SetReactState(REACT_AGGRESSIVE);
         }
References delay, CreatureAI::me, REACT_AGGRESSIVE, and Creature::SetReactState().
UpdateAI()
void npc_love_in_air_snivel::npc_love_in_air_snivelAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 169 of file love_in_air.cpp.
         {
             if (delay > 0)
                 delay -= std::min<int32>(delay, diff);
         }
References delay.
Member Data Documentation
delay
int32 npc_love_in_air_snivel::npc_love_in_air_snivelAI::delay
Definition at line 134 of file love_in_air.cpp.
Referenced by MoveInLineOfSight(), Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Events/love_in_air.cpp