Azerotcore-wotlk: Acore::ChatCommands::AccountIdentifier Struct Reference
Acore::ChatCommands::AccountIdentifier Struct Reference
#include <ChatCommandTags.h>
Public Types
using value_type = uint32
Public Types inherited from Acore::Impl::ChatCommands::ContainerTag
using ChatCommandResult = Acore::Impl::ChatCommands::ChatCommandResult
Public Member Functions
operator uint32 () const
operator std::string const & () const
operator std::string_view () const
uint32 GetID () const
std::string const & GetName () const
ChatCommandResult TryConsume (ChatHandler const *handler, std::string_view args)
Private Attributes
uint32 _id
std::string _name
Detailed Description
Definition at line 151 of file ChatCommandTags.h.
Member Typedef Documentation
value_type
using Acore::ChatCommands::AccountIdentifier::value_type = uint32
Definition at line 153 of file ChatCommandTags.h.
Member Function Documentation
GetID()
uint32 Acore::ChatCommands::AccountIdentifier::GetID () const inline
Definition at line 159 of file ChatCommandTags.h.
 { return _id; }
Referenced by character_commandscript::HandlePDumpLoadCommand().
GetName()
std::string const& Acore::ChatCommands::AccountIdentifier::GetName () const inline
Definition at line 160 of file ChatCommandTags.h.
 { return _name; }
Referenced by character_commandscript::HandlePDumpLoadCommand().
operator std::string const &()
Acore::ChatCommands::AccountIdentifier::operator std::string const & () const inline
Definition at line 156 of file ChatCommandTags.h.
 { return _name; }
operator std::string_view()
Acore::ChatCommands::AccountIdentifier::operator std::string_view () const inline
Definition at line 157 of file ChatCommandTags.h.
 { return { _name }; }
operator uint32()
Acore::ChatCommands::AccountIdentifier::operator uint32 () const inline
Definition at line 155 of file ChatCommandTags.h.
 { return _id; }
TryConsume()
ChatCommandResult Acore::ChatCommands::AccountIdentifier::TryConsume (ChatHandler const * handler, std::string_view args)
Definition at line 61 of file ChatCommandTags.cpp.
 {
     std::string_view text;
     ChatCommandResult next = ArgInfo<std::string_view>::TryConsume(text, handler, args);
     if (!next)
         return next;
     // first try parsing as account name
     _name.assign(text);
     if (!Utf8ToUpperOnlyLatin(_name))
         return GetAcoreString(handler, LANG_CMDPARSER_INVALID_UTF8);
     _id = AccountMgr::GetId(_name);
     if (_id) // account with name exists, we are done
         return next;
     // try parsing as account id instead
     Optional<uint32> id = Acore::StringTo<uint32>(text, 10);
     if (!id)
         return FormatAcoreString(handler, LANG_CMDPARSER_ACCOUNT_NAME_NO_EXIST, STRING_VIEW_FMT_ARG(_name));
     _id = *id;
     if (AccountMgr::GetName(_id, _name))
         return next;
     else
         return FormatAcoreString(handler, LANG_CMDPARSER_ACCOUNT_ID_NO_EXIST, _id);
 }
References Acore::Impl::ChatCommands::FormatAcoreString(), Acore::Impl::ChatCommands::GetAcoreString(), AccountMgr::GetId(), AccountMgr::GetName(), LANG_CMDPARSER_ACCOUNT_ID_NO_EXIST, LANG_CMDPARSER_ACCOUNT_NAME_NO_EXIST, LANG_CMDPARSER_INVALID_UTF8, STRING_VIEW_FMT_ARG, and Utf8ToUpperOnlyLatin().
Member Data Documentation
_id
uint32 Acore::ChatCommands::AccountIdentifier::_id private
Definition at line 165 of file ChatCommandTags.h.
_name
std::string Acore::ChatCommands::AccountIdentifier::_name private
Definition at line 166 of file ChatCommandTags.h.
The documentation for this struct was generated from the following files:
src/server/game/Chat/ChatCommands/ChatCommandTags.h
src/server/game/Chat/ChatCommands/ChatCommandTags.cpp