Azerotcore-wotlk: VMAP::WorldModel_Raw Struct Reference
VMAP::WorldModel_Raw Struct Reference
#include <TileAssembler.h>
Public Member Functions
bool Read (const char *path)
Public Attributes
uint32 RootWMOID
std::vector< GroupModel_Raw > groupsArray
Detailed Description
Definition at line 84 of file TileAssembler.h.
Member Function Documentation
Read()
bool VMAP::WorldModel_Raw::Read (const char * path)
rf will be freed inside Read if the function had any errors.
Definition at line 557 of file TileAssembler.cpp.
     {
         FILE* rf = fopen(path, "rb");
         if (!rf)
         {
             printf("ERROR: Can't open raw model file: %s\n", path);
             return false;
         }
         char ident[9];
         ident[8] = '\0';
         int readOperation = 0;
         READ_OR_RETURN(&ident, 8);
         CMP_OR_RETURN(ident, RAW_VMAP_MAGIC);
         // we have to read one int. This is needed during the export and we have to skip it here
         uint32 tempNVectors;
         READ_OR_RETURN(&tempNVectors, sizeof(tempNVectors));
         uint32 groups;
         READ_OR_RETURN(&groups, sizeof(uint32));
         READ_OR_RETURN(&RootWMOID, sizeof(uint32));
         groupsArray.resize(groups);
         bool succeed = true;
         for (uint32 g = 0; g < groups && succeed; ++g)
         {
             succeed = groupsArray[g].Read(rf);
         }
         if (succeed)
         {
             fclose(rf);
         }
         return succeed;
     }
References CMP_OR_RETURN, groupsArray, printf(), VMAP::RAW_VMAP_MAGIC, READ_OR_RETURN, and RootWMOID.
Referenced by VMAP::TileAssembler::calculateTransformedBound(), VMAP::TileAssembler::convertRawFile(), and VMAP::TileAssembler::exportGameobjectModels().
Member Data Documentation
groupsArray
std::vector<GroupModel_Raw> VMAP::WorldModel_Raw::groupsArray
Definition at line 87 of file TileAssembler.h.
Referenced by VMAP::TileAssembler::calculateTransformedBound(), VMAP::TileAssembler::convertRawFile(), VMAP::TileAssembler::exportGameobjectModels(), and Read().
RootWMOID
uint32 VMAP::WorldModel_Raw::RootWMOID
Definition at line 86 of file TileAssembler.h.
Referenced by VMAP::TileAssembler::convertRawFile(), and Read().
The documentation for this struct was generated from the following files:
src/common/Collision/Maps/TileAssembler.h
src/common/Collision/Maps/TileAssembler.cpp