Azerotcore-wotlk: Acore::Impl::ChatCommands::ArgInfo< Acore::ChatCommands::Variant< Ts... > > Struct Template Reference
Acore::Impl::ChatCommands::ArgInfo< Acore::ChatCommands::Variant< Ts... > > Struct Template Reference
#include <ChatCommandArgs.h>
Public Types
using V = std::variant< Ts... >
Static Public Member Functions
template<size_t I>
static ChatCommandResult TryAtIndex ([[maybe_unused]] Acore::ChatCommands::Variant< Ts... > &val, [[maybe_unused]] ChatHandler const *handler, [[maybe_unused]] std::string_view args)
static ChatCommandResult TryConsume (Acore::ChatCommands::Variant< Ts... > &val, ChatHandler const *handler, std::string_view args)
Static Public Attributes
static constexpr size_t N = std::variant_size_v<V>
Detailed Description
template<typename... Ts>
struct Acore::Impl::ChatCommands::ArgInfo< Acore::ChatCommands::Variant< Ts... > >
Definition at line 255 of file ChatCommandArgs.h.
Member Typedef Documentation
V
template<typename... Ts> using Acore::Impl::ChatCommands::ArgInfo< Acore::ChatCommands::Variant< Ts... > >::V = std::variant<Ts...>
Definition at line 257 of file ChatCommandArgs.h.
Member Function Documentation
TryAtIndex()
template<typename... Ts> template<size_t I> static ChatCommandResult Acore::Impl::ChatCommands::ArgInfo< Acore::ChatCommands::Variant< Ts... > >::TryAtIndex ([[maybe_unused] ] Acore::ChatCommands::Variant< Ts... > & val, [[maybe_unused] ] ChatHandler const * handler, [[maybe_unused] ] std::string_view args) inline static
Definition at line 261 of file ChatCommandArgs.h.
         {
             if constexpr (I < N)
             {
                 ChatCommandResult thisResult = ArgInfo<std::variant_alternative_t<I, V>>::TryConsume(val.template emplace<I>(), handler, args);
                 if (thisResult)
                     return thisResult;
                 else
                 {
                     ChatCommandResult nestedResult = TryAtIndex<I + 1>(val, handler, args);
                     if (nestedResult || !thisResult.HasErrorMessage())
                         return nestedResult;
                     if (!nestedResult.HasErrorMessage())
                         return thisResult;
                     if (StringStartsWith(nestedResult.GetErrorMessage(), "\""))
                         return Acore::StringFormat("\"%s\"\n%s %s", thisResult.GetErrorMessage().c_str(), GetAcoreString(handler, LANG_CMDPARSER_OR), nestedResult.GetErrorMessage().c_str());
                     else
                         return Acore::StringFormat("\"%s\"\n%s \"%s\"", thisResult.GetErrorMessage().c_str(), GetAcoreString(handler, LANG_CMDPARSER_OR), nestedResult.GetErrorMessage().c_str());
                 }
             }
             else
                 return std::nullopt;
         }
References Acore::Impl::ChatCommands::GetAcoreString(), Acore::Impl::ChatCommands::ChatCommandResult::GetErrorMessage(), Acore::Impl::ChatCommands::ChatCommandResult::HasErrorMessage(), I, LANG_CMDPARSER_OR, Acore::StringFormat(), and StringStartsWith().
TryConsume()
template<typename... Ts> static ChatCommandResult Acore::Impl::ChatCommands::ArgInfo< Acore::ChatCommands::Variant< Ts... > >::TryConsume (Acore::ChatCommands::Variant< Ts... > & val, ChatHandler const * handler, std::string_view args) inline static
Definition at line 285 of file ChatCommandArgs.h.
         {
             ChatCommandResult result = TryAtIndex<0>(val, handler, args);
             if (result.HasErrorMessage() && (result.GetErrorMessage().find('\n') != std::string::npos))
                 return Acore::StringFormat("%s %s", GetAcoreString(handler, LANG_CMDPARSER_EITHER), result.GetErrorMessage().c_str());
             return result;
         }
References Acore::Impl::ChatCommands::GetAcoreString(), LANG_CMDPARSER_EITHER, and Acore::StringFormat().
Member Data Documentation
N
template<typename... Ts> constexpr size_t Acore::Impl::ChatCommands::ArgInfo< Acore::ChatCommands::Variant< Ts... > >::N = std::variant_size_v<V> static constexpr
Definition at line 258 of file ChatCommandArgs.h.
The documentation for this struct was generated from the following file:
src/server/game/Chat/ChatCommands/ChatCommandArgs.h