Azerotcore-wotlk: go_direbrew_mole_machine::go_direbrew_mole_machineAI Struct Reference
go_direbrew_mole_machine::go_direbrew_mole_machineAI Struct Reference
Public Member Functions
go_direbrew_mole_machineAI (GameObject *go)
void Reset () override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32)
virtual ObjectGuid GetGUID (int32) const
virtual bool GossipHello (Player *, bool)
virtual bool GossipSelect (Player *, uint32, uint32)
virtual bool GossipSelectCode (Player *, uint32, uint32, char const *)
virtual bool QuestAccept (Player *, Quest const *)
virtual bool QuestReward (Player *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *)
virtual void Destroyed (Player *, uint32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void OnGameEvent (bool, uint16)
virtual void OnStateChanged (uint32, Unit *)
virtual void EventInform (uint32)
virtual void SpellHit (Unit *, const SpellInfo *)
virtual bool CanBeSeen (Player const *)
Private Attributes
TaskScheduler _scheduler
Additional Inherited Members
Static Public Member Functions inherited from GameObjectAI
static int Permissible (GameObject const *go)
Protected Attributes inherited from GameObjectAI
GameObject *const me
Detailed Description
Definition at line 2102 of file brewfest.cpp.
Constructor & Destructor Documentation
go_direbrew_mole_machineAI()
go_direbrew_mole_machine::go_direbrew_mole_machineAI::go_direbrew_mole_machineAI (GameObject * go) inline
Definition at line 2104 of file brewfest.cpp.
 : GameObjectAI(go) { }
Member Function Documentation
Reset()
void go_direbrew_mole_machine::go_direbrew_mole_machineAI::Reset () inline override virtual
Reimplemented from GameObjectAI.
Definition at line 2106 of file brewfest.cpp.
         {
             me->SetLootState(GO_READY);
             _scheduler.Schedule(Seconds(1), [this](TaskContext /*context*/)
             {
                 me->UseDoorOrButton();
                 me->CastSpell(nullptr, SPELL_MOLE_MACHINE_EMERGE);
             })
             .Schedule(Seconds(4), [this](TaskContext /*context*/)
             {
             if (GameObject* trap = me->GetLinkedTrap())
                 {
                     trap->UseDoorOrButton();
                     trap->SetLootState(GO_READY);
                 }
             });
         }
References _scheduler, GameObject::CastSpell(), GameObject::GetLinkedTrap(), GO_READY, GameObjectAI::me, TaskScheduler::Schedule(), GameObject::SetLootState(), SPELL_MOLE_MACHINE_EMERGE, and GameObject::UseDoorOrButton().
UpdateAI()
void go_direbrew_mole_machine::go_direbrew_mole_machineAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from GameObjectAI.
Definition at line 2125 of file brewfest.cpp.
         {
             _scheduler.Update(diff);
         }
References _scheduler, and TaskScheduler::Update().
Member Data Documentation
_scheduler
TaskScheduler go_direbrew_mole_machine::go_direbrew_mole_machineAI::_scheduler private
Definition at line 2131 of file brewfest.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Events/brewfest.cpp