Azerotcore-wotlk: go_harpoon_canon Class Reference
go_harpoon_canon Class Reference
Public Member Functions
go_harpoon_canon ()
bool OnGossipHello (Player *pPlayer, GameObject *go) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Definition at line 497 of file boss_skadi.cpp.
Constructor & Destructor Documentation
go_harpoon_canon()
go_harpoon_canon::go_harpoon_canon () inline
Definition at line 500 of file boss_skadi.cpp.
 : GameObjectScript("go_harpoon_canon") { }
Member Function Documentation
OnGossipHello()
bool go_harpoon_canon::OnGossipHello (Player * pPlayer, GameObject * go) inline override virtual
Reimplemented from GameObjectScript.
Definition at line 502 of file boss_skadi.cpp.
     {
         InstanceScript* m_pInstance = go->GetInstanceScript();
         if (m_pInstance && m_pInstance->GetData(DATA_SKADI_THE_RUTHLESS) == IN_PROGRESS)
             if (m_pInstance->GetData(SKADI_IN_RANGE) == 1)
             {
                 uint8 count = m_pInstance->GetData(SKADI_HITS) + 1;
                 m_pInstance->SetData(SKADI_HITS, count);
                 if (Creature* grauf = ObjectAccessor::GetCreature(*pPlayer, m_pInstance->GetGuidData(DATA_GRAUF)))
                 {
                     if (count >= 3)
                     {
                         m_pInstance->SetData(SKADI_IN_RANGE, 0);
                         grauf->AI()->DoAction(ACTION_REMOVE_SKADI);
                     }
                     grauf->AI()->DoAction(ACTION_MYGIRL_ACHIEVEMENT);
                 }
                 go->CastSpell((Unit*)nullptr, SPELL_LAUNCH_HARPOON);
             }
         return true;
     }
References ACTION_MYGIRL_ACHIEVEMENT, ACTION_REMOVE_SKADI, GameObject::CastSpell(), DATA_GRAUF, DATA_SKADI_THE_RUTHLESS, ObjectAccessor::GetCreature(), ZoneScript::GetData(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), IN_PROGRESS, ZoneScript::SetData(), SKADI_HITS, SKADI_IN_RANGE, and SPELL_LAUNCH_HARPOON.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_skadi.cpp