Azerotcore-wotlk: OutdoorPvP Class Reference
OutdoorPvP Class Reference
#include <OutdoorPvP.h>
Public Types
typedef std::map< ObjectGuid::LowType, OPvPCapturePoint * > OPvPCapturePointMap
typedef std::pair< ObjectGuid::LowType, GameObject * > GoScriptPair
typedef std::pair< ObjectGuid::LowType, Creature * > CreatureScriptPair
Public Member Functions
OutdoorPvP ()
~OutdoorPvP () override
void DeleteSpawns ()
virtual void FillInitialWorldStates (WorldPacket &)
virtual bool HandleAreaTrigger (Player *player, uint32 trigger)
virtual bool HandleCustomSpell (Player *player, uint32 spellId, GameObject *go)
virtual bool HandleOpenGo (Player *player, GameObject *go)
virtual bool SetupOutdoorPvP ()
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
void OnCreatureCreate (Creature *creature) override
void OnCreatureRemove (Creature *creature) override
void SendUpdateWorldState (uint32 field, uint32 value)
virtual bool Update (uint32 diff)
virtual void HandleKill (Player *killer, Unit *killed)
virtual void HandleKillImpl (Player *, Unit *)
bool IsInsideObjective (Player *player) const
virtual void AwardKillBonus (Player *)
uint32 GetTypeId ()
virtual bool HandleDropFlag (Player *player, uint32 spellId)
virtual bool HandleGossipOption (Player *player, Creature *creature, uint32 gossipid)
virtual bool CanTalkTo (Player *player, Creature *c, GossipMenuItems const &gso)
void TeamApplyBuff (TeamId teamId, uint32 spellId, uint32 spellId2=0, Player *sameMapPlr=nullptr)
Map * GetMap () const
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Protected Member Functions
virtual void SendRemoveWorldStates (Player *)
void BroadcastPacket (WorldPacket &data) const
virtual void HandlePlayerEnterZone (Player *player, uint32 zone)
virtual void HandlePlayerLeaveZone (Player *player, uint32 zone)
virtual void HandlePlayerResurrects (Player *player, uint32 zone)
void AddCapturePoint (OPvPCapturePoint *cp)
OPvPCapturePoint * GetCapturePoint (ObjectGuid::LowType spawnId) const
void RegisterZone (uint32 zoneid)
bool HasPlayer (Player const *player) const
void TeamCastSpell (TeamId team, int32 spellId, Player *sameMapPlr=nullptr)
void SetMapFromZone (uint32 zone)
Protected Attributes
OPvPCapturePointMap m_capturePoints
PlayerSet m_players [2]
uint32 m_TypeId
bool m_sendUpdate
std::map< ObjectGuid::LowType, GameObject * > m_GoScriptStore
std::map< ObjectGuid::LowType, Creature * > m_CreatureScriptStore
Map * m_map
Friends
class OutdoorPvPMgr
Detailed Description
Definition at line 186 of file OutdoorPvP.h.
Member Typedef Documentation
CreatureScriptPair
typedef std::pair<ObjectGuid::LowType, Creature*> OutdoorPvP::CreatureScriptPair
Definition at line 202 of file OutdoorPvP.h.
GoScriptPair
typedef std::pair<ObjectGuid::LowType, GameObject*> OutdoorPvP::GoScriptPair
Definition at line 201 of file OutdoorPvP.h.
OPvPCapturePointMap
typedef std::map<ObjectGuid::LowType, OPvPCapturePoint*> OutdoorPvP::OPvPCapturePointMap
Definition at line 200 of file OutdoorPvP.h.
Constructor & Destructor Documentation
OutdoorPvP()
OutdoorPvP::OutdoorPvP ()
Definition at line 248 of file OutdoorPvP.cpp.
 : m_TypeId(0), m_sendUpdate(true), m_map(nullptr) { }
~OutdoorPvP()
OutdoorPvP::~OutdoorPvP () override
Definition at line 250 of file OutdoorPvP.cpp.
 {
     DeleteSpawns();
 }
References DeleteSpawns().
Member Function Documentation
AddCapturePoint()
void OutdoorPvP::AddCapturePoint (OPvPCapturePoint * cp) inline protected
Definition at line 271 of file OutdoorPvP.h.
     {
         m_capturePoints[cp->m_capturePointSpawnId] = cp;
     }
References m_capturePoints, and OPvPCapturePoint::m_capturePointSpawnId.
Referenced by OutdoorPvPEP::SetupOutdoorPvP(), OutdoorPvPGH::SetupOutdoorPvP(), OutdoorPvPHP::SetupOutdoorPvP(), OutdoorPvPNA::SetupOutdoorPvP(), OutdoorPvPTF::SetupOutdoorPvP(), and OutdoorPvPZM::SetupOutdoorPvP().
AwardKillBonus()
virtual void OutdoorPvP::AwardKillBonus (Player *) inline virtual
Definition at line 237 of file OutdoorPvP.h.
 {}
BroadcastPacket()
void OutdoorPvP::BroadcastPacket (WorldPacket & data) const protected
Definition at line 582 of file OutdoorPvP.cpp.
 {
     // This is faster than sWorld->SendZoneMessage
     for (uint32 team = 0; team < 2; ++team)
         for (PlayerSet::const_iterator itr = m_players[team].begin(); itr != m_players[team].end(); ++itr)
             if (Player* const player = ObjectAccessor::FindPlayer(*itr))
                 player->GetSession()->SendPacket(&data);
 }
References ObjectAccessor::FindPlayer(), and m_players.
CanTalkTo()
bool OutdoorPvP::CanTalkTo (Player * player, Creature * c, GossipMenuItems const & gso) virtual
Definition at line 534 of file OutdoorPvP.cpp.
 {
     for (OPvPCapturePointMap::iterator itr = m_capturePoints.begin(); itr != m_capturePoints.end(); ++itr)
         if (itr->second->CanTalkTo(player, c, gso))
             return true;
     return false;
 }
References mpq::c, and m_capturePoints.
DeleteSpawns()
void OutdoorPvP::DeleteSpawns ()
Definition at line 223 of file OutdoorPvP.cpp.
 {
     // Remove script from any registered gameobjects/creatures
     for (auto itr = m_GoScriptStore.begin(); itr != m_GoScriptStore.end(); ++itr)
     {
         if (GameObject* go = itr->second)
             go->ClearZoneScript();
     }
     m_GoScriptStore.clear();
     for (auto itr = m_CreatureScriptStore.begin(); itr != m_CreatureScriptStore.end(); ++itr)
     {
         if (Creature* creature = itr->second)
             creature->ClearZoneScript();
     }
     m_CreatureScriptStore.clear();
     for (OPvPCapturePointMap::iterator itr = m_capturePoints.begin(); itr != m_capturePoints.end(); ++itr)
     {
         itr->second->DeleteSpawns();
         delete itr->second;
     }
     m_capturePoints.clear();
 }
References m_capturePoints, m_CreatureScriptStore, and m_GoScriptStore.
Referenced by ~OutdoorPvP().
FillInitialWorldStates()
virtual void OutdoorPvP::FillInitialWorldStates (WorldPacket &) inline virtual
Reimplemented in OutdoorPvPZM, OutdoorPvPTF, OutdoorPvPSI, OutdoorPvPNA, OutdoorPvPHP, and OutdoorPvPEP.
Definition at line 204 of file OutdoorPvP.h.
 {}
Referenced by Player::SendInitWorldStates().
GetCapturePoint()
OPvPCapturePoint* OutdoorPvP::GetCapturePoint (ObjectGuid::LowType spawnId) const inline protected
Definition at line 276 of file OutdoorPvP.h.
     {
         OutdoorPvP::OPvPCapturePointMap::const_iterator itr = m_capturePoints.find(spawnId);
         if (itr != m_capturePoints.end())
             return itr->second;
         return nullptr;
     }
References m_capturePoints.
Referenced by OnGameObjectCreate(), and OnGameObjectRemove().
GetMap()
Map* OutdoorPvP::GetMap () const inline
Definition at line 249 of file OutdoorPvP.h.
 { return m_map; }
References m_map.
Referenced by OPvPCapturePoint::DelCreature(), OPvPCapturePoint::DelObject(), and OPvPCapturePointNA::GetAliveGuardsCount().
GetTypeId()
uint32 OutdoorPvP::GetTypeId () inline
Definition at line 239 of file OutdoorPvP.h.
 {return m_TypeId;}
References m_TypeId.
Referenced by Player::SendInitWorldStates().
HandleAreaTrigger()
bool OutdoorPvP::HandleAreaTrigger (Player * player, uint32 trigger) virtual
Reimplemented in OutdoorPvPSI.
Definition at line 577 of file OutdoorPvP.cpp.
 {
     return false;
 }
HandleCustomSpell()
bool OutdoorPvP::HandleCustomSpell (Player * player, uint32 spellId, GameObject * go) virtual
Reimplemented in OutdoorPvPSI.
Definition at line 500 of file OutdoorPvP.cpp.
 {
     for (OPvPCapturePointMap::iterator itr = m_capturePoints.begin(); itr != m_capturePoints.end(); ++itr)
         if (itr->second->HandleCustomSpell(player, spellId, go))
             return true;
     return false;
 }
References m_capturePoints.
HandleDropFlag()
bool OutdoorPvP::HandleDropFlag (Player * player, uint32 spellId) virtual
Reimplemented in OutdoorPvPSI.
Definition at line 543 of file OutdoorPvP.cpp.
 {
     for (OPvPCapturePointMap::iterator itr = m_capturePoints.begin(); itr != m_capturePoints.end(); ++itr)
         if (itr->second->HandleDropFlag(player, id))
             return true;
     return false;
 }
References m_capturePoints.
HandleGossipOption()
bool OutdoorPvP::HandleGossipOption (Player * player, Creature * creature, uint32 gossipid) virtual
Definition at line 525 of file OutdoorPvP.cpp.
 {
     for (OPvPCapturePointMap::iterator itr = m_capturePoints.begin(); itr != m_capturePoints.end(); ++itr)
         if (itr->second->HandleGossipOption(player, creature, id))
             return true;
     return false;
 }
References m_capturePoints.
HandleKill()
void OutdoorPvP::HandleKill (Player * killer, Unit * killed) virtual
Definition at line 452 of file OutdoorPvP.cpp.
 {
     if (Group* group = killer->GetGroup())
     {
         for (GroupReference* itr = group->GetFirstMember(); itr != nullptr; itr = itr->next())
         {
             Player* groupGuy = itr->GetSource();
             if (!groupGuy)
                 continue;
             // skip if too far away
             if (!groupGuy->IsAtGroupRewardDistance(killed) && killer != groupGuy)
                 continue;
             // creature kills must be notified, even if not inside objective / not outdoor pvp active
             // player kills only count if active and inside objective
             if ((groupGuy->IsOutdoorPvPActive() && IsInsideObjective(groupGuy)) || killed->GetTypeId() == TYPEID_UNIT)
             {
                 HandleKillImpl(groupGuy, killed);
             }
         }
     }
     else
     {
         // creature kills must be notified, even if not inside objective / not outdoor pvp active
         if (killer && ((killer->IsOutdoorPvPActive() && IsInsideObjective(killer)) || killed->GetTypeId() == TYPEID_UNIT))
         {
             HandleKillImpl(killer, killed);
         }
     }
 }
References Player::GetGroup(), Object::GetTypeId(), HandleKillImpl(), Player::IsAtGroupRewardDistance(), IsInsideObjective(), Player::IsOutdoorPvPActive(), GroupReference::next(), and TYPEID_UNIT.
HandleKillImpl()
virtual void OutdoorPvP::HandleKillImpl (Player * , Unit *) inline virtual
Reimplemented in OutdoorPvPZM, OutdoorPvPNA, and OutdoorPvPHP.
Definition at line 231 of file OutdoorPvP.h.
 {}
Referenced by HandleKill().
HandleOpenGo()
bool OutdoorPvP::HandleOpenGo (Player * player, GameObject * go) virtual
Definition at line 516 of file OutdoorPvP.cpp.
 {
     for (OPvPCapturePointMap::iterator itr = m_capturePoints.begin(); itr != m_capturePoints.end(); ++itr)
         if (itr->second->HandleOpenGo(player, go) >= 0)
             return true;
     return false;
 }
References m_capturePoints.
HandlePlayerEnterZone()
void OutdoorPvP::HandlePlayerEnterZone (Player * player, uint32 zone) protected virtual
Reimplemented in OutdoorPvPZM, OutdoorPvPTF, OutdoorPvPSI, OutdoorPvPNA, OutdoorPvPHP, and OutdoorPvPEP.
Definition at line 255 of file OutdoorPvP.cpp.
 {
     m_players[player->GetTeamId()].insert(player->GetGUID());
 }
References Object::GetGUID(), Player::GetTeamId(), and m_players.
Referenced by OutdoorPvPEP::HandlePlayerEnterZone(), OutdoorPvPHP::HandlePlayerEnterZone(), OutdoorPvPNA::HandlePlayerEnterZone(), OutdoorPvPSI::HandlePlayerEnterZone(), OutdoorPvPTF::HandlePlayerEnterZone(), and OutdoorPvPZM::HandlePlayerEnterZone().
HandlePlayerLeaveZone()
void OutdoorPvP::HandlePlayerLeaveZone (Player * player, uint32 zone) protected virtual
Reimplemented in OutdoorPvPZM, OutdoorPvPTF, OutdoorPvPSI, OutdoorPvPNA, OutdoorPvPHP, and OutdoorPvPEP.
Definition at line 260 of file OutdoorPvP.cpp.
 {
     // inform the objectives of the leaving
     for (OPvPCapturePointMap::iterator itr = m_capturePoints.begin(); itr != m_capturePoints.end(); ++itr)
         itr->second->HandlePlayerLeave(player);
     // remove the world state information from the player (we can't keep everyone up to date, so leave out those who are not in the concerning zones)
     if (!player->GetSession()->PlayerLogout())
         SendRemoveWorldStates(player);
     m_players[player->GetTeamId()].erase(player->GetGUID());
     LOG_DEBUG("outdoorpvp", "Player %s left an outdoorpvp zone", player->GetName().c_str());
 }
References Object::GetGUID(), WorldObject::GetName(), Player::GetSession(), Player::GetTeamId(), LOG_DEBUG, m_capturePoints, m_players, WorldSession::PlayerLogout(), and SendRemoveWorldStates().
Referenced by OutdoorPvPEP::HandlePlayerLeaveZone(), OutdoorPvPHP::HandlePlayerLeaveZone(), OutdoorPvPNA::HandlePlayerLeaveZone(), OutdoorPvPSI::HandlePlayerLeaveZone(), OutdoorPvPTF::HandlePlayerLeaveZone(), and OutdoorPvPZM::HandlePlayerLeaveZone().
HandlePlayerResurrects()
void OutdoorPvP::HandlePlayerResurrects (Player * player, uint32 zone) protected virtual
Definition at line 272 of file OutdoorPvP.cpp.
 {
 }
HasPlayer()
bool OutdoorPvP::HasPlayer (Player const * player) const protected
Definition at line 596 of file OutdoorPvP.cpp.
 {
     PlayerSet const& plSet = m_players[player->GetTeamId()];
     return plSet.find(player->GetGUID()) != plSet.end();
 }
References Object::GetGUID(), Player::GetTeamId(), and m_players.
IsInsideObjective()
bool OutdoorPvP::IsInsideObjective (Player * player) const
Definition at line 485 of file OutdoorPvP.cpp.
 {
     for (OPvPCapturePointMap::const_iterator itr = m_capturePoints.begin(); itr != m_capturePoints.end(); ++itr)
         if (itr->second->IsInsideObjective(player))
             return true;
     return false;
 }
References m_capturePoints.
Referenced by HandleKill().
OnCreatureCreate()
void OutdoorPvP::OnCreatureCreate (Creature * creature) override virtual
Reimplemented from ZoneScript.
Definition at line 649 of file OutdoorPvP.cpp.
 {
     CreatureScriptPair sp(creature->GetGUID().GetCounter(), creature);
     m_CreatureScriptStore.insert(sp);
 }
References ObjectGuid::GetCounter(), Object::GetGUID(), and m_CreatureScriptStore.
OnCreatureRemove()
void OutdoorPvP::OnCreatureRemove (Creature * creature) override virtual
Reimplemented from ZoneScript.
Definition at line 655 of file OutdoorPvP.cpp.
 {
     m_CreatureScriptStore.erase(creature->GetGUID().GetCounter());
 }
References ObjectGuid::GetCounter(), Object::GetGUID(), and m_CreatureScriptStore.
OnGameObjectCreate()
void OutdoorPvP::OnGameObjectCreate (GameObject * go) override virtual
Reimplemented from ZoneScript.
Definition at line 626 of file OutdoorPvP.cpp.
 {
     GoScriptPair sp(go->GetGUID().GetCounter(), go);
     m_GoScriptStore.insert(sp);
     if (go->GetGoType() != GAMEOBJECT_TYPE_CAPTURE_POINT)
         return;
     if (OPvPCapturePoint* cp = GetCapturePoint(go->GetSpawnId()))
         cp->m_capturePoint = go;
 }
References GAMEOBJECT_TYPE_CAPTURE_POINT, GetCapturePoint(), ObjectGuid::GetCounter(), GameObject::GetGoType(), Object::GetGUID(), GameObject::GetSpawnId(), and m_GoScriptStore.
OnGameObjectRemove()
void OutdoorPvP::OnGameObjectRemove (GameObject * go) override virtual
Reimplemented from ZoneScript.
Definition at line 638 of file OutdoorPvP.cpp.
 {
     m_GoScriptStore.erase(go->GetGUID().GetCounter());
     if (go->GetGoType() != GAMEOBJECT_TYPE_CAPTURE_POINT)
         return;
     if (OPvPCapturePoint* cp = GetCapturePoint(go->GetSpawnId()))
         cp->m_capturePoint = nullptr;
 }
References GAMEOBJECT_TYPE_CAPTURE_POINT, GetCapturePoint(), ObjectGuid::GetCounter(), GameObject::GetGoType(), Object::GetGUID(), GameObject::GetSpawnId(), and m_GoScriptStore.
RegisterZone()
void OutdoorPvP::RegisterZone (uint32 zoneid) protected
Definition at line 591 of file OutdoorPvP.cpp.
 {
     sOutdoorPvPMgr->AddZone(zoneId, this);
 }
References sOutdoorPvPMgr.
Referenced by OutdoorPvPEP::SetupOutdoorPvP(), OutdoorPvPGH::SetupOutdoorPvP(), OutdoorPvPHP::SetupOutdoorPvP(), OutdoorPvPNA::SetupOutdoorPvP(), OutdoorPvPSI::SetupOutdoorPvP(), OutdoorPvPTF::SetupOutdoorPvP(), and OutdoorPvPZM::SetupOutdoorPvP().
SendRemoveWorldStates()
virtual void OutdoorPvP::SendRemoveWorldStates (Player *) inline protected virtual
Reimplemented in OutdoorPvPZM, OutdoorPvPTF, OutdoorPvPSI, OutdoorPvPNA, OutdoorPvPHP, OutdoorPvPGH, and OutdoorPvPEP.
Definition at line 262 of file OutdoorPvP.h.
 {}
Referenced by HandlePlayerLeaveZone().
SendUpdateWorldState()
void OutdoorPvP::SendUpdateWorldState (uint32 field, uint32 value)
Definition at line 411 of file OutdoorPvP.cpp.
 {
     if (m_sendUpdate)
         for (int i = 0; i < 2; ++i)
             for (PlayerSet::iterator itr = m_players[i].begin(); itr != m_players[i].end(); ++itr)
                 if (Player* const player = ObjectAccessor::FindPlayer(*itr))
                     player->SendUpdateWorldState(field, value);
 }
References ObjectAccessor::FindPlayer(), m_players, and m_sendUpdate.
Referenced by OPvPCapturePointHP::ChangeState(), OPvPCapturePointNA::FactionTakeOver(), OutdoorPvPEP::Update(), OutdoorPvPHP::Update(), OPvPCapturePointNA::Update(), OutdoorPvPTF::Update(), OPvPCapturePointNA::UpdateHalaaWorldState(), OPvPCapturePointEP_EWT::UpdateTowerState(), OPvPCapturePointEP_NPT::UpdateTowerState(), OPvPCapturePointEP_CGT::UpdateTowerState(), OPvPCapturePointEP_PWT::UpdateTowerState(), OPvPCapturePointTF::UpdateTowerState(), OPvPCapturePointZM_Beacon::UpdateTowerState(), OPvPCapturePointZM_GraveYard::UpdateTowerState(), OutdoorPvPSI::UpdateWorldState(), and OPvPCapturePointNA::UpdateWyvernRoostWorldState().
SetMapFromZone()
void OutdoorPvP::SetMapFromZone (uint32 zone) protected
Definition at line 660 of file OutdoorPvP.cpp.
 {
     AreaTableEntry const* areaTable = sAreaTableStore.LookupEntry(zone);
     ASSERT(areaTable);
     Map* map = sMapMgr->CreateBaseMap(areaTable->mapid);
     ASSERT(!map->Instanceable());
     m_map = map;
 }
References ASSERT, Map::Instanceable(), m_map, AreaTableEntry::mapid, sAreaTableStore, and sMapMgr.
Referenced by OutdoorPvPEP::SetupOutdoorPvP(), OutdoorPvPGH::SetupOutdoorPvP(), OutdoorPvPHP::SetupOutdoorPvP(), OutdoorPvPNA::SetupOutdoorPvP(), OutdoorPvPSI::SetupOutdoorPvP(), OutdoorPvPTF::SetupOutdoorPvP(), and OutdoorPvPZM::SetupOutdoorPvP().
SetupOutdoorPvP()
virtual bool OutdoorPvP::SetupOutdoorPvP () inline virtual
Reimplemented in OutdoorPvPZM, OutdoorPvPTF, OutdoorPvPSI, OutdoorPvPNA, OutdoorPvPHP, OutdoorPvPGH, and OutdoorPvPEP.
Definition at line 216 of file OutdoorPvP.h.
 {return true;}
Referenced by OutdoorPvPMgr::InitOutdoorPvP().
TeamApplyBuff()
void OutdoorPvP::TeamApplyBuff (TeamId teamId, uint32 spellId, uint32 spellId2 = 0, Player * sameMapPlr = nullptr)
Definition at line 620 of file OutdoorPvP.cpp.
 {
     TeamCastSpell(teamId, spellId, sameMapPlr);
     TeamCastSpell(teamId == TEAM_ALLIANCE ? TEAM_HORDE : TEAM_ALLIANCE, spellId2 ? -(int32)spellId2 : -(int32)spellId, sameMapPlr);
 }
References TEAM_ALLIANCE, TEAM_HORDE, and TeamCastSpell().
Referenced by OPvPCapturePointNA::FactionTakeOver(), OutdoorPvPSI::HandleAreaTrigger(), OPvPCapturePointZM_GraveYard::HandleOpenGo(), OutdoorPvPHP::Update(), and OutdoorPvPTF::Update().
TeamCastSpell()
void OutdoorPvP::TeamCastSpell (TeamId team, int32 spellId, Player * sameMapPlr = nullptr) protected
Definition at line 602 of file OutdoorPvP.cpp.
 {
     if (spellId > 0)
     {
         for (PlayerSet::iterator itr = m_players[team].begin(); itr != m_players[team].end(); ++itr)
             if (Player* const player = ObjectAccessor::FindPlayer(*itr))
                 if (!sameMapPlr || sameMapPlr->FindMap() == player->FindMap())
                     player->CastSpell(player, (uint32)spellId, true);
     }
     else
     {
         for (PlayerSet::iterator itr = m_players[team].begin(); itr != m_players[team].end(); ++itr)
             if (Player* const player = ObjectAccessor::FindPlayer(*itr))
                 if (!sameMapPlr || sameMapPlr->FindMap() == player->FindMap())
                     player->RemoveAura((uint32) - spellId); // by stack?
     }
 }
References WorldObject::FindMap(), ObjectAccessor::FindPlayer(), and m_players.
Referenced by TeamApplyBuff(), OutdoorPvPHP::Update(), and OutdoorPvPTF::Update().
Update()
bool OutdoorPvP::Update (uint32 diff) virtual
Reimplemented in OutdoorPvPZM, OutdoorPvPTF, OutdoorPvPSI, OutdoorPvPNA, OutdoorPvPHP, and OutdoorPvPEP.
Definition at line 276 of file OutdoorPvP.cpp.
 {
     bool objective_changed = false;
     for (OPvPCapturePointMap::iterator itr = m_capturePoints.begin(); itr != m_capturePoints.end(); ++itr)
     {
         if (itr->second->Update(diff))
             objective_changed = true;
     }
     return objective_changed;
 }
References diff(), and m_capturePoints.
Referenced by OutdoorPvPEP::Update(), OutdoorPvPHP::Update(), OutdoorPvPTF::Update(), and OutdoorPvPZM::Update().
Friends And Related Function Documentation
OutdoorPvPMgr
friend class OutdoorPvPMgr friend
Definition at line 188 of file OutdoorPvP.h.
Member Data Documentation
m_capturePoints
OPvPCapturePointMap OutdoorPvP::m_capturePoints protected
Definition at line 253 of file OutdoorPvP.h.
Referenced by AddCapturePoint(), CanTalkTo(), DeleteSpawns(), OutdoorPvPEP::FillInitialWorldStates(), OutdoorPvPHP::FillInitialWorldStates(), OutdoorPvPTF::FillInitialWorldStates(), OutdoorPvPZM::FillInitialWorldStates(), GetCapturePoint(), HandleCustomSpell(), HandleDropFlag(), HandleGossipOption(), HandleOpenGo(), HandlePlayerLeaveZone(), IsInsideObjective(), and Update().
m_CreatureScriptStore
std::map<ObjectGuid::LowType, Creature*> OutdoorPvP::m_CreatureScriptStore protected
Definition at line 293 of file OutdoorPvP.h.
Referenced by DeleteSpawns(), OnCreatureCreate(), and OnCreatureRemove().
m_GoScriptStore
std::map<ObjectGuid::LowType, GameObject*> OutdoorPvP::m_GoScriptStore protected
Definition at line 292 of file OutdoorPvP.h.
Referenced by DeleteSpawns(), OnGameObjectCreate(), and OnGameObjectRemove().
m_map
Map* OutdoorPvP::m_map protected
Definition at line 295 of file OutdoorPvP.h.
Referenced by GetMap(), and SetMapFromZone().
m_players
PlayerSet OutdoorPvP::m_players[2] protected
Definition at line 255 of file OutdoorPvP.h.
Referenced by BroadcastPacket(), OutdoorPvPEP::BuffTeams(), HandlePlayerEnterZone(), HandlePlayerLeaveZone(), HasPlayer(), SendUpdateWorldState(), and TeamCastSpell().
m_sendUpdate
bool OutdoorPvP::m_sendUpdate protected
Definition at line 259 of file OutdoorPvP.h.
Referenced by SendUpdateWorldState().
m_TypeId
uint32 OutdoorPvP::m_TypeId protected
Definition at line 257 of file OutdoorPvP.h.
Referenced by GetTypeId(), OutdoorPvPEP::OutdoorPvPEP(), OutdoorPvPGH::OutdoorPvPGH(), OutdoorPvPHP::OutdoorPvPHP(), OutdoorPvPNA::OutdoorPvPNA(), OutdoorPvPSI::OutdoorPvPSI(), OutdoorPvPTF::OutdoorPvPTF(), and OutdoorPvPZM::OutdoorPvPZM().
The documentation for this class was generated from the following files:
src/server/game/OutdoorPvP/OutdoorPvP.h
src/server/game/OutdoorPvP/OutdoorPvP.cpp