Azerotcore-wotlk: achievement_not_even_a_scratch Class Reference
achievement_not_even_a_scratch Class Reference
Public Member Functions
achievement_not_even_a_scratch ()
bool OnCheck (Player *source, Unit *, uint32) override
Public Member Functions inherited from AchievementCriteriaScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AchievementCriteriaScript
AchievementCriteriaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 228 of file achievement_scripts.cpp.
Constructor & Destructor Documentation
achievement_not_even_a_scratch()
achievement_not_even_a_scratch::achievement_not_even_a_scratch () inline
Definition at line 231 of file achievement_scripts.cpp.
 : AchievementCriteriaScript("achievement_not_even_a_scratch") { }
Member Function Documentation
OnCheck()
bool achievement_not_even_a_scratch::OnCheck (Player * source, Unit * , uint32) inline override virtual
Reimplemented from AchievementCriteriaScript.
Definition at line 233 of file achievement_scripts.cpp.
     {
         if (!source)
             return false;
         Battleground* battleground = source->GetBattleground();
         return battleground && battleground->GetBgTypeID(true) == BATTLEGROUND_SA && battleground->ToBattlegroundSA()->notEvenAScratch(source->GetTeamId());
     }
References BATTLEGROUND_SA, Player::GetBattleground(), Battleground::GetBgTypeID(), Player::GetTeamId(), BattlegroundSA::notEvenAScratch(), and Battleground::ToBattlegroundSA().
The documentation for this class was generated from the following file:
src/server/scripts/World/achievement_scripts.cpp