Azerotcore-wotlk: npc_toc_hunter::npc_toc_hunterAI Struct Reference
npc_toc_hunter::npc_toc_hunterAI Struct Reference
Public Member Functions
npc_toc_hunterAI (Creature *pCreature)
bool myCanCast ()
void JustSummoned (Creature *c) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from boss_faction_championsAI
boss_faction_championsAI (Creature *pCreature, uint32 aitype)
void EnterCombat (Unit *) override
void AttackStart (Unit *who) override
float GetThreatMod (float dist, float, uint32 health, uint32, Unit *target)
void RecalculateThreat ()
void EventMapGCD (EventMap &e, uint32 delay, uint32 gcd=0)
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void EnterEvadeMode () override
bool IsCCed ()
Creature * SelectTarget_MostHPLostFriendlyMissingBuff (uint32 spell, float range)
uint32 EnemiesInRange (float distance)
Unit * SelectEnemyCaster (bool casting, float range)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
Public Attributes inherited from boss_faction_championsAI
InstanceScript * pInstance
uint32 mAIType
uint32 threatTimer
uint32 powerTimer
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1227 of file boss_faction_champions.cpp.
Constructor & Destructor Documentation
npc_toc_hunterAI()
npc_toc_hunter::npc_toc_hunterAI::npc_toc_hunterAI (Creature * pCreature) inline
Definition at line 1229 of file boss_faction_champions.cpp.
                                               : boss_faction_championsAI(pCreature, AI_RANGED)
         {
             SetEquipmentSlots(false, 47156, EQUIP_NO_CHANGE, 48711);
             events.Reset();
             events.RescheduleEvent(EVENT_SPELL_AIMED_SHOT, urand(3000, 10000));
             events.RescheduleEvent(EVENT_SPELL_DETERRENCE, 10000);
             //events.RescheduleEvent(EVENT_SPELL_DISENGAGE, 10000);
             events.RescheduleEvent(EVENT_SPELL_EXPLOSIVE_SHOT, urand(3000, 10000));
             events.RescheduleEvent(EVENT_SPELL_FROST_TRAP, urand(15000, 20000));
             events.RescheduleEvent(EVENT_SPELL_STEADY_SHOT, urand(3000, 10000));
             events.RescheduleEvent(EVENT_SPELL_WING_CLIP, 10000);
             events.RescheduleEvent(EVENT_SPELL_WYVERN_STING, urand(5000, 15000));
             events.RescheduleEvent(EVENT_SPELL_CALL_PET, 0);
         }
References EQUIP_NO_CHANGE, EVENT_SPELL_AIMED_SHOT, EVENT_SPELL_CALL_PET, EVENT_SPELL_DETERRENCE, EVENT_SPELL_EXPLOSIVE_SHOT, EVENT_SPELL_FROST_TRAP, EVENT_SPELL_STEADY_SHOT, EVENT_SPELL_WING_CLIP, EVENT_SPELL_WYVERN_STING, ScriptedAI::SetEquipmentSlots(), and urand().
Member Function Documentation
JustSummoned()
void npc_toc_hunter::npc_toc_hunterAI::JustSummoned (Creature * c) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1251 of file boss_faction_champions.cpp.
         {
             if( Unit* target = c->SelectNearestTarget(200.0f) )
                 c->AI()->AttackStart(target);
         }
References mpq::c.
myCanCast()
bool npc_toc_hunter::npc_toc_hunterAI::myCanCast () inline
Definition at line 1246 of file boss_faction_champions.cpp.
         {
             return !(me->HasUnitState(UNIT_STATE_CASTING) || me->HasFlag(UNIT_FIELD_FLAGS_2, UNIT_FLAG2_DISARM_RANGED) || IsCCed());
         }
References Object::HasFlag(), Unit::HasUnitState(), boss_faction_championsAI::IsCCed(), ScriptedAI::me, UNIT_FIELD_FLAGS_2, UNIT_FLAG2_DISARM_RANGED, and UNIT_STATE_CASTING.
Referenced by UpdateAI().
UpdateAI()
void npc_toc_hunter::npc_toc_hunterAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from boss_faction_championsAI.
Definition at line 1257 of file boss_faction_champions.cpp.
         {
             boss_faction_championsAI::UpdateAI(diff);
             if( !UpdateVictim() )
                 return;
             events.Update(diff);
             if( !myCanCast() )
                 return;
             switch( events.ExecuteEvent() )
             {
                 case 0:
                     break;
                 case EVENT_SPELL_CALL_PET:
                     DoSummon(35610, *me);
                     break;
                 case EVENT_SPELL_AIMED_SHOT:
                     if( me->GetVictim() )
                         me->CastSpell(me->GetVictim(), SPELL_AIMED_SHOT, false);
                     events.RepeatEvent(urand(5000, 15000));
                     EventMapGCD(events, 1500);
                     break;
                 case EVENT_SPELL_DETERRENCE:
                     if( HealthBelowPct(25) )
                     {
                         me->CastSpell(me, SPELL_DETERRENCE, false);
                         events.RepeatEvent(90000);
                         EventMapGCD(events, 1500);
                     }
                     else
                         events.RepeatEvent(6000);
                     break;
                 case EVENT_SPELL_DISENGAGE:
                     if( EnemiesInRange(10.0f) >= 3 )
                     {
                         me->CastSpell(me, SPELL_DISENGAGE, false);
                         events.RepeatEvent(20000);
                         EventMapGCD(events, 1500);
                     }
                     else
                         events.RepeatEvent(6000);
                     break;
                 case EVENT_SPELL_EXPLOSIVE_SHOT:
                     if( me->GetVictim() )
                         me->CastSpell(me->GetVictim(), SPELL_EXPLOSIVE_SHOT, false);
                     events.RepeatEvent(urand(5000, 15000));
                     EventMapGCD(events, 1500);
                     break;
                 case EVENT_SPELL_FROST_TRAP:
                     me->CastSpell(me, SPELL_FROST_TRAP, false);
                     events.RepeatEvent(30000);
                     EventMapGCD(events, 1500);
                     break;
                 case EVENT_SPELL_STEADY_SHOT:
                     if( me->GetVictim() )
                         me->CastSpell(me->GetVictim(), SPELL_STEADY_SHOT, false);
                     events.RepeatEvent(urand(5000, 15000));
                     EventMapGCD(events, 1500);
                     break;
                 case EVENT_SPELL_WING_CLIP:
                     if( me->GetVictim() && me->GetDistance2d(me->GetVictim()) <= 5.0f )
                         me->CastSpell(me->GetVictim(), SPELL_WING_CLIP, false);
                     events.RepeatEvent(8000);
                     EventMapGCD(events, 1500);
                     break;
                 case EVENT_SPELL_WYVERN_STING:
                     if( Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 35.0f, true) )
                     {
                         me->CastSpell(target, SPELL_WYVERN_STING, false);
                         events.RepeatEvent(60000);
                         EventMapGCD(events, 1500);
                         break;
                     }
                     events.RepeatEvent(10000);
                     break;
             }
             if( me->isAttackReady() && !me->HasUnitState(UNIT_STATE_CASTING) )
             {
                 me->CastSpell(me->GetVictim(), SPELL_SHOOT, true);
                 me->resetAttackTimer();
             }
         }
References Unit::CastSpell(), diff(), CreatureAI::DoSummon(), boss_faction_championsAI::EnemiesInRange(), EVENT_SPELL_AIMED_SHOT, EVENT_SPELL_CALL_PET, EVENT_SPELL_DETERRENCE, EVENT_SPELL_DISENGAGE, EVENT_SPELL_EXPLOSIVE_SHOT, EVENT_SPELL_FROST_TRAP, EVENT_SPELL_STEADY_SHOT, EVENT_SPELL_WING_CLIP, EVENT_SPELL_WYVERN_STING, boss_faction_championsAI::EventMapGCD(), WorldObject::GetDistance2d(), Unit::GetVictim(), Unit::HasUnitState(), ScriptedAI::HealthBelowPct(), Unit::isAttackReady(), ScriptedAI::me, myCanCast(), Unit::resetAttackTimer(), SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), SPELL_AIMED_SHOT, SPELL_DETERRENCE, SPELL_DISENGAGE, SPELL_EXPLOSIVE_SHOT, SPELL_FROST_TRAP, SPELL_SHOOT, SPELL_STEADY_SHOT, SPELL_WING_CLIP, SPELL_WYVERN_STING, UNIT_STATE_CASTING, boss_faction_championsAI::UpdateAI(), CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
events
EventMap npc_toc_hunter::npc_toc_hunterAI::events
Definition at line 1244 of file boss_faction_champions.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_faction_champions.cpp