Azerotcore-wotlk: boss_gothik::boss_gothikAI Struct Reference
boss_gothik::boss_gothikAI Struct Reference
Public Member Functions
boss_gothikAI (Creature *c)
bool IsInRoom ()
void Reset () override
void EnterCombat (Unit *who) override
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *cr) override
void KilledUnit (Unit *who) override
void JustDied (Unit *killer) override
void SummonHelpers (uint32 entry)
bool CheckGroupSplitted ()
void SpellHit (Unit *, const SpellInfo *spellInfo) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
SummonList summons
InstanceScript * pInstance
bool secondPhase {}
bool gateOpened {}
uint8 waveCount {}
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 197 of file boss_gothik.cpp.
Constructor & Destructor Documentation
boss_gothikAI()
boss_gothik::boss_gothikAI::boss_gothikAI (Creature * c) inline explicit
Definition at line 199 of file boss_gothik.cpp.
                                             : BossAI(c, BOSS_GOTHIK), summons(me)
         {
             pInstance = me->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), ScriptedAI::me, and pInstance.
Member Function Documentation
CheckGroupSplitted()
bool boss_gothik::boss_gothikAI::CheckGroupSplitted () inline
Definition at line 350 of file boss_gothik.cpp.
         {
             Map::PlayerList const& PlayerList = me->GetMap()->GetPlayers();
             if (!PlayerList.isEmpty())
             {
                 bool checklife = false;
                 bool checkdead = false;
                 for (const auto& i : PlayerList)
                 {
                     Player* player = i.GetSource();
                     if (player->IsAlive() &&
                         player->GetPositionX() <= POS_X_NORTH &&
                         player->GetPositionX() >= POS_X_SOUTH &&
                         player->GetPositionY() <= POS_Y_GATE &&
                         player->GetPositionY() >= POS_Y_EAST)
{
                             checklife = true;
                         }
                     else if (player->IsAlive() &&
                              player->GetPositionX() <= POS_X_NORTH &&
                              player->GetPositionX() >= POS_X_SOUTH &&
                              player->GetPositionY() >= POS_Y_GATE &&
                              player->GetPositionY() <= POS_Y_WEST)
{
                                  checkdead = true;
                              }
                     if (checklife && checkdead)
                         return true;
                 }
             }
             return false;
         }
References WorldObject::GetMap(), Map::GetPlayers(), Position::GetPositionX(), Position::GetPositionY(), Unit::IsAlive(), LinkedListHead::isEmpty(), ScriptedAI::me, POS_X_NORTH, POS_X_SOUTH, POS_Y_EAST, POS_Y_GATE, and POS_Y_WEST.
Referenced by UpdateAI().
DamageTaken()
void boss_gothik::boss_gothikAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 403 of file boss_gothik.cpp.
         {
             if (!secondPhase)
             {
                 damage = 0;
             }
         }
References secondPhase.
EnterCombat()
void boss_gothik::boss_gothikAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from BossAI.
Definition at line 248 of file boss_gothik.cpp.
         {
             BossAI::EnterCombat(who);
             me->SetInCombatWithZone();
             Talk(SAY_INTRO_1);
             events.ScheduleEvent(EVENT_INTRO_2, 4000);
             events.ScheduleEvent(EVENT_INTRO_3, 9000);
             events.ScheduleEvent(EVENT_INTRO_4, 14000);
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE);
             events.ScheduleEvent(EVENT_SUMMON_ADDS, 30000);
             events.ScheduleEvent(EVENT_CHECK_PLAYERS, 120000);
             if (pInstance)
             {
                 if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_GOTHIK_ENTER_GATE)))
                 {
                     go->SetGoState(GO_STATE_READY);
                 }
                 if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_GOTHIK_INNER_GATE)))
                 {
                     go->SetGoState(GO_STATE_READY);
                 }
             }
         }
References DATA_GOTHIK_ENTER_GATE, DATA_GOTHIK_INNER_GATE, BossAI::EnterCombat(), EVENT_CHECK_PLAYERS, EVENT_INTRO_2, EVENT_INTRO_3, EVENT_INTRO_4, EVENT_SUMMON_ADDS, Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), GO_STATE_READY, ScriptedAI::me, pInstance, SAY_INTRO_1, Object::SetFlag(), Creature::SetInCombatWithZone(), CreatureAI::Talk(), UNIT_FIELD_FLAGS, and UNIT_FLAG_DISABLE_MOVE.
IsInRoom()
bool boss_gothik::boss_gothikAI::IsInRoom () inline
Definition at line 210 of file boss_gothik.cpp.
         {
             if (me->GetPositionX() > 2767 || me->GetPositionX() < 2618 || me->GetPositionY() > -3285 || me->GetPositionY() < -3435)
             {
                 EnterEvadeMode();
                 return false;
             }
             return true;
         }
References CreatureAI::EnterEvadeMode(), Position::GetPositionX(), Position::GetPositionY(), and ScriptedAI::me.
Referenced by UpdateAI().
JustDied()
void boss_gothik::boss_gothikAI::JustDied (Unit * killer) inline override virtual
Reimplemented from BossAI.
Definition at line 303 of file boss_gothik.cpp.
         {
             BossAI::JustDied(killer);
             Talk(SAY_DEATH);
             summons.DespawnAll();
             if (pInstance)
             {
                 if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_GOTHIK_ENTER_GATE)))
                 {
                     go->SetGoState(GO_STATE_ACTIVE);
                 }
                 if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_GOTHIK_INNER_GATE)))
                 {
                     go->SetGoState(GO_STATE_ACTIVE);
                 }
                 if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_GOTHIK_EXIT_GATE)))
                 {
                     go->SetGoState(GO_STATE_ACTIVE);
                 }
             }
         }
References DATA_GOTHIK_ENTER_GATE, DATA_GOTHIK_EXIT_GATE, DATA_GOTHIK_INNER_GATE, SummonList::DespawnAll(), Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), GO_STATE_ACTIVE, BossAI::JustDied(), ScriptedAI::me, pInstance, SAY_DEATH, summons, and CreatureAI::Talk().
JustSummoned()
void boss_gothik::boss_gothikAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
Definition at line 272 of file boss_gothik.cpp.
         {
             summons.Summon(summon);
             if (gateOpened)
             {
                 summons.DoZoneInCombat();
             }
             else if (Unit* target = me->SelectNearestTarget(50.0f))
             {
                 AttackStart(target);
                 DoZoneInCombat();
             }
         }
References ScriptedAI::AttackStart(), CreatureAI::DoZoneInCombat(), SummonList::DoZoneInCombat(), gateOpened, ScriptedAI::me, Creature::SelectNearestTarget(), SummonList::Summon(), and summons.
KilledUnit()
void boss_gothik::boss_gothikAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 291 of file boss_gothik.cpp.
         {
             if (who->GetTypeId() != TYPEID_PLAYER)
                 return;
             Talk(SAY_KILL);
             if (pInstance)
             {
                 pInstance->SetData(DATA_IMMORTAL_FAIL, 0);
             }
         }
References DATA_IMMORTAL_FAIL, Object::GetTypeId(), pInstance, SAY_KILL, ZoneScript::SetData(), CreatureAI::Talk(), and TYPEID_PLAYER.
Reset()
void boss_gothik::boss_gothikAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 220 of file boss_gothik.cpp.
         {
             BossAI::Reset();
             events.Reset();
             summons.DespawnAll();
             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_DISABLE_MOVE);
             me->SetReactState(REACT_PASSIVE);
             secondPhase = false;
             gateOpened = false;
             waveCount = 0;
             me->NearTeleportTo(2642.139f, -3386.959f, 285.492f, 6.265f);
             if (pInstance)
             {
                 if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_GOTHIK_ENTER_GATE)))
                 {
                     go->SetGoState(GO_STATE_ACTIVE);
                 }
                 if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_GOTHIK_INNER_GATE)))
                 {
                     go->SetGoState(GO_STATE_ACTIVE);
                 }
                 if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_GOTHIK_EXIT_GATE)))
                 {
                     go->SetGoState(GO_STATE_READY);
                 }
             }
         }
References DATA_GOTHIK_ENTER_GATE, DATA_GOTHIK_EXIT_GATE, DATA_GOTHIK_INNER_GATE, SummonList::DespawnAll(), gateOpened, Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), GO_STATE_ACTIVE, GO_STATE_READY, ScriptedAI::me, Unit::NearTeleportTo(), pInstance, REACT_PASSIVE, Object::RemoveFlag(), BossAI::Reset(), secondPhase, Creature::SetReactState(), summons, UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE, UNIT_FLAG_IMMUNE_TO_PC, and waveCount.
SpellHit()
void boss_gothik::boss_gothikAI::SpellHit (Unit * , const SpellInfo * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 384 of file boss_gothik.cpp.
         {
             uint8 pos = urand(0, 4);
             switch (spellInfo->Id)
             {
                 case SPELL_INFORM_LIVING_TRAINEE:
                     me->SummonCreature(NPC_DEAD_TRAINEE, PosSummonDead[pos].GetPositionX(), PosSummonDead[pos].GetPositionY(), PosSummonDead[pos].GetPositionZ(), PosSummonDead[pos].GetOrientation());
                     break;
                 case SPELL_INFORM_LIVING_KNIGHT:
                     me->SummonCreature(NPC_DEAD_KNIGHT, PosSummonDead[pos].GetPositionX(), PosSummonDead[pos].GetPositionY(), PosSummonDead[pos].GetPositionZ(), PosSummonDead[pos].GetOrientation());
                     break;
                 case SPELL_INFORM_LIVING_RIDER:
                     me->SummonCreature(NPC_DEAD_RIDER, PosSummonDead[pos].GetPositionX(), PosSummonDead[pos].GetPositionY(), PosSummonDead[pos].GetPositionZ(), PosSummonDead[pos].GetOrientation());
                     me->SummonCreature(NPC_DEAD_HORSE, PosSummonDead[pos].GetPositionX(), PosSummonDead[pos].GetPositionY(), PosSummonDead[pos].GetPositionZ(), PosSummonDead[pos].GetOrientation());
                     break;
             }
             me->HandleEmoteCommand(EMOTE_ONESHOT_SPELL_CAST);
         }
References EMOTE_ONESHOT_SPELL_CAST, Unit::HandleEmoteCommand(), SpellInfo::Id, ScriptedAI::me, NPC_DEAD_HORSE, NPC_DEAD_KNIGHT, NPC_DEAD_RIDER, NPC_DEAD_TRAINEE, PosSummonDead, SPELL_INFORM_LIVING_KNIGHT, SPELL_INFORM_LIVING_RIDER, SPELL_INFORM_LIVING_TRAINEE, WorldObject::SummonCreature(), and urand().
SummonedCreatureDespawn()
void boss_gothik::boss_gothikAI::SummonedCreatureDespawn (Creature * cr) inline override virtual
Reimplemented from BossAI.
Definition at line 286 of file boss_gothik.cpp.
         {
             summons.Despawn(cr);
         }
References SummonList::Despawn(), and summons.
SummonHelpers()
void boss_gothik::boss_gothikAI::SummonHelpers (uint32 entry) inline
Definition at line 325 of file boss_gothik.cpp.
         {
             switch(entry)
             {
                 case NPC_LIVING_TRAINEE:
                     me->SummonCreature(NPC_LIVING_TRAINEE, PosSummonLiving[0].GetPositionX(), PosSummonLiving[0].GetPositionY(), PosSummonLiving[0].GetPositionZ(), PosSummonLiving[0].GetOrientation());
                     me->SummonCreature(NPC_LIVING_TRAINEE, PosSummonLiving[1].GetPositionX(), PosSummonLiving[1].GetPositionY(), PosSummonLiving[1].GetPositionZ(), PosSummonLiving[1].GetOrientation());
                     if (Is25ManRaid())
                     {
                         me->SummonCreature(NPC_LIVING_TRAINEE, PosSummonLiving[2].GetPositionX(), PosSummonLiving[2].GetPositionY(), PosSummonLiving[2].GetPositionZ(), PosSummonLiving[2].GetOrientation());
                     }
                     break;
                 case NPC_LIVING_KNIGHT:
                     me->SummonCreature(NPC_LIVING_KNIGHT, PosSummonLiving[3].GetPositionX(), PosSummonLiving[3].GetPositionY(), PosSummonLiving[3].GetPositionZ(), PosSummonLiving[3].GetOrientation());
                     if (Is25ManRaid())
                     {
                         me->SummonCreature(NPC_LIVING_KNIGHT, PosSummonLiving[5].GetPositionX(), PosSummonLiving[5].GetPositionY(), PosSummonLiving[5].GetPositionZ(), PosSummonLiving[5].GetOrientation());
                     }
                     break;
                 case NPC_LIVING_RIDER:
                     me->SummonCreature(NPC_LIVING_RIDER, PosSummonLiving[4].GetPositionX(), PosSummonLiving[4].GetPositionY(), PosSummonLiving[4].GetPositionZ(), PosSummonLiving[4].GetOrientation());
                     break;
             }
         }
References ScriptedAI::Is25ManRaid(), ScriptedAI::me, NPC_LIVING_KNIGHT, NPC_LIVING_RIDER, NPC_LIVING_TRAINEE, PosSummonLiving, and WorldObject::SummonCreature().
Referenced by UpdateAI().
UpdateAI()
void boss_gothik::boss_gothikAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 411 of file boss_gothik.cpp.
         {
             if (!IsInRoom())
                 return;
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_INTRO_2:
                     Talk(SAY_INTRO_2);
                     break;
                 case EVENT_INTRO_3:
                     Talk(SAY_INTRO_3);
                     break;
                 case EVENT_INTRO_4:
                     Talk(SAY_INTRO_4);
                     break;
                 case EVENT_SHADOW_BOLT:
                     me->CastSpell(me->GetVictim(), RAID_MODE(SPELL_SHADOW_BOLT_10, SPELL_SHADOW_BOLT_25), false);
                     events.RepeatEvent(1010);
                     break;
                 case EVENT_HARVEST_SOUL:
                     me->CastSpell(me, SPELL_HARVEST_SOUL, false);
                     events.RepeatEvent(15000);
                     break;
                 case EVENT_TELEPORT:
                     me->AttackStop();
                     if (IN_LIVE_SIDE(me))
                     {
                         me->CastSpell(me, SPELL_TELEPORT_DEAD, false);
                     }
                     else
                     {
                         me->CastSpell(me, SPELL_TELEPORT_LIVE, false);
                     }
                     me->getThreatMgr().resetAggro(NotOnSameSide(me));
                     if (Unit* pTarget = SelectTarget(SELECT_TARGET_NEAREST, 0))
                     {
                         me->getThreatMgr().addThreat(pTarget, 100.0f);
                         AttackStart(pTarget);
                     }
                     events.RepeatEvent(20000);
                     break;
                 case EVENT_CHECK_HEALTH:
                     if (me->HealthBelowPct(30) && pInstance)
                     {
                         if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_GOTHIK_INNER_GATE)))
{
                             go->SetGoState(GO_STATE_ACTIVE);
                         }
                         events.CancelEvent(EVENT_TELEPORT);
                         break;
                     }
                     events.RepeatEvent(1000);
                     break;
                 case EVENT_SUMMON_ADDS:
                     if (gothikWaves[waveCount][0])
                     {
                         SummonHelpers(gothikWaves[waveCount][0]);
                         events.RepeatEvent(gothikWaves[waveCount][1]);
                     }
                     else
                     {
                         secondPhase = true;
                         Talk(SAY_PHASE_TWO);
                         Talk(EMOTE_PHASE_TWO);
                         me->CastSpell(me, SPELL_TELEPORT_LIVE, false);
                         me->SetReactState(REACT_AGGRESSIVE);
                         me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC | UNIT_FLAG_DISABLE_MOVE);
                         me->RemoveAllAuras();
                         summons.DoZoneInCombat();
                         events.ScheduleEvent(EVENT_SHADOW_BOLT, 1000);
                         events.ScheduleEvent(EVENT_HARVEST_SOUL, urand(5000, 15000));
                         events.ScheduleEvent(EVENT_TELEPORT, 20000);
                         events.ScheduleEvent(EVENT_CHECK_HEALTH, 1000);
                     }
                     waveCount++;
                     break;
                 case EVENT_CHECK_PLAYERS:
                     if (!CheckGroupSplitted())
                     {
                         if (GameObject* go = me->GetMap()->GetGameObject(pInstance->GetGuidData(DATA_GOTHIK_INNER_GATE)))
{
                             go->SetGoState(GO_STATE_ACTIVE);
                         }
                         summons.DoZoneInCombat();
                         gateOpened = true;
                         Talk(EMOTE_GATE_OPENED);
                     }
                     break;
             }
             DoMeleeAttackIfReady();
         }
References ThreatMgr::addThreat(), ScriptedAI::AttackStart(), Unit::AttackStop(), Unit::CastSpell(), CheckGroupSplitted(), DATA_GOTHIK_INNER_GATE, UnitAI::DoMeleeAttackIfReady(), SummonList::DoZoneInCombat(), EMOTE_GATE_OPENED, EMOTE_PHASE_TWO, EVENT_CHECK_HEALTH, EVENT_CHECK_PLAYERS, EVENT_HARVEST_SOUL, EVENT_INTRO_2, EVENT_INTRO_3, EVENT_INTRO_4, EVENT_SHADOW_BOLT, EVENT_SUMMON_ADDS, EVENT_TELEPORT, gateOpened, Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), Unit::getThreatMgr(), Unit::GetVictim(), GO_STATE_ACTIVE, gothikWaves, Unit::HasUnitState(), Unit::HealthBelowPct(), IN_LIVE_SIDE, IsInRoom(), ScriptedAI::me, pInstance, ScriptedAI::RAID_MODE(), REACT_AGGRESSIVE, Unit::RemoveAllAuras(), Object::RemoveFlag(), ThreatMgr::resetAggro(), SAY_INTRO_2, SAY_INTRO_3, SAY_INTRO_4, SAY_PHASE_TWO, secondPhase, SELECT_TARGET_NEAREST, UnitAI::SelectTarget(), Creature::SetReactState(), SPELL_HARVEST_SOUL, SPELL_SHADOW_BOLT_10, SPELL_SHADOW_BOLT_25, SPELL_TELEPORT_DEAD, SPELL_TELEPORT_LIVE, SummonHelpers(), summons, CreatureAI::Talk(), UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE, UNIT_FLAG_IMMUNE_TO_PC, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), urand(), and waveCount.
Member Data Documentation
events
EventMap boss_gothik::boss_gothikAI::events
Definition at line 203 of file boss_gothik.cpp.
gateOpened
bool boss_gothik::boss_gothikAI::gateOpened {}
Definition at line 207 of file boss_gothik.cpp.
Referenced by JustSummoned(), Reset(), and UpdateAI().
pInstance
InstanceScript* boss_gothik::boss_gothikAI::pInstance
Definition at line 205 of file boss_gothik.cpp.
Referenced by boss_gothikAI(), EnterCombat(), JustDied(), KilledUnit(), Reset(), and UpdateAI().
secondPhase
bool boss_gothik::boss_gothikAI::secondPhase {}
Definition at line 206 of file boss_gothik.cpp.
Referenced by DamageTaken(), Reset(), and UpdateAI().
summons
SummonList boss_gothik::boss_gothikAI::summons
Definition at line 204 of file boss_gothik.cpp.
Referenced by JustDied(), JustSummoned(), Reset(), SummonedCreatureDespawn(), and UpdateAI().
waveCount
uint8 boss_gothik::boss_gothikAI::waveCount {}
Definition at line 208 of file boss_gothik.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Naxxramas/boss_gothik.cpp