Azerotcore-wotlk: G3D::Ray Class Reference
G3D::Ray Class Reference
#include <Ray.h>
Public Member Functions
void set (const Point3 &origin, const Vector3 &direction)
const Point3 & origin () const
const Vector3 & direction () const
const Vector3 & invDirection () const
Ray ()
Ray (const Point3 &origin, const Vector3 &direction)
Ray (class BinaryInput &b)
void serialize (class BinaryOutput &b) const
void deserialize (class BinaryInput &b)
Ray bumpedRay (float distance) const
Ray bumpedRay (float distance, const Vector3 &bumpDirection) const
Point3 closestPoint (const Point3 &point) const
Returns the closest point on the Ray to point.
float distance (const Point3 &point) const
Point3 intersection (const class Plane &plane) const
float intersectionTime (const class Sphere &sphere, bool solid=false) const
float intersectionTime (const class Plane &plane) const
float intersectionTime (const class Box &box) const
float intersectionTime (const class AABox &box) const
float intersectionTime (const Vector3 &v0, const Vector3 &v1, const Vector3 &v2, const Vector3 &edge01, const Vector3 &edge02, float &w0, float &w1, float &w2) const
float intersectionTime (const Point3 &vert0, const Point3 &vert1, const Point3 &vert2, const Vector3 &edge01, const Vector3 &edge02) const
float intersectionTime (const Point3 &vert0, const Point3 &vert1, const Point3 &vert2) const
float intersectionTime (const Point3 &vert0, const Point3 &vert1, const Point3 &vert2, float &w0, float &w1, float &w2) const
float intersectionTime (const Triangle &triangle) const
float intersectionTime (const Triangle &triangle, float &w0, float &w1, float &w2) const
Ray refract (const Vector3 &newOrigin, const Vector3 &normal, float iInside, float iOutside) const
Ray reflect (const Vector3 &newOrigin, const Vector3 &normal) const
Static Public Member Functions
static Ray fromOriginAndDirection (const Point3 &point, const Vector3 &direction)
Private Types
enum Classification {
MMM , MMP , MPM , MPP ,
PMM , PMP , PPM , PPP ,
POO , MOO , OPO , OMO ,
OOP , OOM , OMM , OMP ,
OPM , OPP , MOM , MOP ,
POM , POP , MMO , MPO ,
PMO , PPO
}
Private Attributes
Point3 m_origin
Vector3 m_direction
Vector3 m_invDirection
Classification classification
float ibyj
float jbyi
float kbyj
float jbyk
float ibyk
float kbyi
float c_xy
float c_xz
float c_yx
float c_yz
float c_zx
float c_zy
Friends
class Intersect
Detailed Description
A 3D Ray.
Definition at line 24 of file Ray.h.
Member Enumeration Documentation
Classification
enum G3D::Ray::Classification private
The following are for the "ray slope" optimization from "Fast Ray / Axis-Aligned Bounding Box Overlap Tests using Ray Slopes" by Martin Eisemann, Thorsten Grosch, Stefan Müller and Marcus Magnor Computer Graphics Lab, TU Braunschweig, Germany and University of Koblenz-Landau, Germany
Enumerator
MMM
MMP
MPM
MPP
PMM
PMP
PPM
PPP
POO
MOO
OPO
OMO
OOP
OOM
OMM
OMP
OPM
OPP
MOM
MOP
POM
POP
MMO
MPO
PMO
PPO
Definition at line 42 of file Ray.h.
 {MMM, MMP, MPM, MPP, PMM, PMP, PPM, PPP, POO, MOO, OPO, OMO, OOP, OOM, OMM, OMP, OPM, OPP, MOM, MOP, POM, POP, MMO, MPO, PMO, PPO};
Constructor & Destructor Documentation
Ray() [1/3]
G3D::Ray::Ray () inline
Definition at line 70 of file Ray.h.
           {
         set(Point3::zero(), Vector3::unitX());
     }
References set(), G3D::Vector3::unitX(), and G3D::Vector3::zero().
Referenced by bumpedRay(), fromOriginAndDirection(), reflect(), and refract().
Ray() [2/3]
G3D::Ray::Ray (const Point3 & origin, const Vector3 & direction) inline
Parameters
direction Assumed to have unit length
Definition at line 75 of file Ray.h.
{
         set(origin, direction);
     }
References direction(), origin(), and set().
Ray() [3/3]
G3D::Ray::Ray (class BinaryInput & b)
Definition at line 126 of file Ray.cpp.
{
     deserialize(b);
 }
References b, and deserialize().
Member Function Documentation
bumpedRay() [1/2]
Ray G3D::Ray::bumpedRay (float distance) const inline
Returns a new ray which has the same direction but an origin advanced along direction by distance
Definition at line 93 of file Ray.h.
{
         return Ray(m_origin + m_direction * distance, m_direction);
     }
References distance(), m_direction, m_origin, and Ray().
bumpedRay() [2/2]
Ray G3D::Ray::bumpedRay (float distance, const Vector3 & bumpDirection) const inline
Returns a new ray which has the same direction but an origin advanced by distance * bumpDirection
Definition at line 99 of file Ray.h.
{
         return Ray(m_origin + bumpDirection * distance, m_direction);
     }
References distance(), m_direction, m_origin, and Ray().
closestPoint()
Point3 G3D::Ray::closestPoint (const Point3 & point) const inline
Returns the closest point on the Ray to point.
Definition at line 106 of file Ray.h.
{
         float t = m_direction.dot(point - m_origin);
         if (t < 0) {
             return m_origin;
         } else {
             return m_origin + m_direction * t;
         }
     }
References G3D::Vector3::dot(), m_direction, and m_origin.
Referenced by distance().
deserialize()
void G3D::Ray::deserialize (class BinaryInput & b)
Definition at line 137 of file Ray.cpp.
{
     m_origin.deserialize(b);
     m_direction.deserialize(b);
     set(m_origin, m_direction);
 }
References b, G3D::Vector3::deserialize(), m_direction, m_origin, and set().
Referenced by Ray().
direction()
const Vector3& G3D::Ray::direction () const inline
Unit direction vector.
Definition at line 61 of file Ray.h.
{
         return m_direction;
     }
References m_direction.
Referenced by G3D::findRayCapsuleIntersection(), fromOriginAndDirection(), G3D::Triangle::intersect(), VMAP::ModelInstance::intersectRay(), BIH::intersectRay(), GameObjectModel::intersectRay(), RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::intersectRay(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Node::intersectRay(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Node::intersects(), VMAP::IntersectTriangle(), Ray(), G3D::CollisionDetection::rayAABox(), set(), G3D::CoordinateFrame::toObjectSpace(), G3D::CoordinateFrame::toWorldSpace(), and G3D::GCamera::unproject().
distance()
float G3D::Ray::distance (const Point3 & point) const inline
Returns the closest distance between point and the Ray
Definition at line 118 of file Ray.h.
{
         return (closestPoint(point) - point).magnitude();
     }
References closestPoint().
Referenced by bumpedRay().
fromOriginAndDirection()
static Ray G3D::Ray::fromOriginAndDirection (const Point3 & point, const Vector3 & direction) inline static
Creates a Ray from a origin and a (nonzero) unit direction.
Definition at line 87 of file Ray.h.
{
         return Ray(point, direction);
     }
References direction(), and Ray().
Referenced by G3D::CollisionDetection::collisionTimeForMovingPointFixedCapsule(), G3D::CollisionDetection::collisionTimeForMovingPointFixedTriangle(), VMAP::StaticMapTree::isInLineOfSight(), G3D::CoordinateFrame::lookRay(), G3D::CoordinateFrame::toObjectSpace(), G3D::CoordinateFrame::toWorldSpace(), and G3D::GCamera::worldRay().
intersection()
Vector3 G3D::Ray::intersection (const class Plane & plane) const
Returns the point where the Ray and plane intersect. If there is no intersection, returns a point at infinity.
Planes are considered one-sided, so the ray will not intersect a plane where the normal faces in the traveling direction.
Definition at line 164 of file Ray.cpp.
{
     float d;
     Vector3 normal = plane.normal();
     plane.getEquation(normal, d);
     float rate = m_direction.dot(normal);
     if (rate >= 0.0f) {
         return Vector3::inf();
     } else {
         float t = -(d + m_origin.dot(normal)) / rate;
         return m_origin + m_direction * t;
     }
 }
References mpq::d, G3D::Vector3::dot(), G3D::Plane::getEquation(), G3D::Vector3::inf(), m_direction, m_origin, and G3D::Plane::normal().
intersectionTime() [1/10]
float G3D::Ray::intersectionTime (const class AABox & box) const
Definition at line 206 of file Ray.cpp.
{
     Vector3 dummy;
     bool inside;
     float time = CollisionDetection::collisionTimeForMovingPointFixedAABox(
             m_origin, m_direction, box, dummy, inside);
     if ((time == finf()) && inside) {
         return 0.0f;
     } else {
         return time;
     }
 }
References G3D::CollisionDetection::collisionTimeForMovingPointFixedAABox(), G3D::finf(), m_direction, and m_origin.
intersectionTime() [2/10]
float G3D::Ray::intersectionTime (const class Box & box) const
Definition at line 193 of file Ray.cpp.
{
     Vector3 dummy;
     float time = CollisionDetection::collisionTimeForMovingPointFixedBox(
             m_origin, m_direction, box, dummy);
     if ((time == finf()) && (box.contains(m_origin))) {
         return 0.0f;
     } else {
         return time;
     }
 }
References G3D::CollisionDetection::collisionTimeForMovingPointFixedBox(), G3D::Box::contains(), G3D::finf(), m_direction, and m_origin.
intersectionTime() [3/10]
float G3D::Ray::intersectionTime (const class Plane & plane) const
Definition at line 186 of file Ray.cpp.
{
     Vector3 dummy;
     return CollisionDetection::collisionTimeForMovingPointFixedPlane(
             m_origin, m_direction, plane, dummy);
 }
References G3D::CollisionDetection::collisionTimeForMovingPointFixedPlane(), m_direction, and m_origin.
intersectionTime() [4/10]
float G3D::Ray::intersectionTime (const class Sphere & sphere, bool solid = false) const
Returns the distance until intersection with the sphere or the (solid) ball bounded by the sphere. Will be 0 if inside the sphere, inf if there is no intersection.
The ray direction is not normalized. If the ray direction has unit length, the distance from the origin to intersection is equal to the time. If the direction does not have unit length, the distance = time * direction.length().
See also the G3D::CollisionDetection "movingPoint" methods, which give more information about the intersection.
Parameters
solid If true, rays inside the sphere immediately intersect (good for collision detection). If false, they hit the opposite side of the sphere (good for ray tracing).
Definition at line 179 of file Ray.cpp.
{
     Vector3 dummy;
     return CollisionDetection::collisionTimeForMovingPointFixedSphere(
             m_origin, m_direction, sphere, dummy, dummy, solid);
 }
References G3D::CollisionDetection::collisionTimeForMovingPointFixedSphere(), m_direction, and m_origin.
Referenced by G3D::CollisionDetection::collisionTimeForMovingPointFixedTriangle(), intersectionTime(), VMAP::ModelInstance::intersectRay(), and GameObjectModel::intersectRay().
intersectionTime() [5/10]
float G3D::Ray::intersectionTime (const Point3 & vert0, const Point3 & vert1, const Point3 & vert2) const inline
Definition at line 176 of file Ray.h.
{
         return intersectionTime(vert0, vert1, vert2, vert1 - vert0, vert2 - vert0);
     }
References intersectionTime().
intersectionTime() [6/10]
float G3D::Ray::intersectionTime (const Point3 & vert0, const Point3 & vert1, const Point3 & vert2, const Vector3 & edge01, const Vector3 & edge02) const inline
Ray-triangle intersection for a 1-sided triangle. Fastest version. [http://www.acm.org/jgt/papers/MollerTrumbore97/] http://www.graphics.cornell.edu/pubs/1997/MT97.html
Definition at line 247 of file Ray.h.
{
     (void)vert1;
     (void)vert2;
     // Barycenteric coords
     float u, v;
     float tvec[3], pvec[3], qvec[3];
     // begin calculating determinant - also used to calculate U parameter
     CROSS(pvec, m_direction, edge2);
     // if determinant is near zero, ray lies in plane of triangle
     const float det = DOT(edge1, pvec);
     if (det < EPSILON) {
         return finf();
     }
     // calculate distance from vert0 to ray origin
     SUB(tvec, m_origin, vert0);
     // calculate U parameter and test bounds
     u = DOT(tvec, pvec);
     if ((u < 0.0f) || (u > det)) {
         // Hit the plane outside the triangle
         return finf();
     }
     // prepare to test V parameter
     CROSS(qvec, tvec, edge1);
     // calculate V parameter and test bounds
     v = DOT(m_direction, qvec);
     if ((v < 0.0f) || (u + v > det)) {
         // Hit the plane outside the triangle
         return finf();
     }
     // Case where we don't need correct (u, v):
     const float t = DOT(edge2, qvec);
     if (t >= 0.0f) {
         // Note that det must be positive
         return t / det;
     } else {
         // We had to travel backwards in time to intersect
         return finf();
     }
 }
References CROSS, DOT, EPSILON, G3D::finf(), m_direction, m_origin, and SUB.
intersectionTime() [7/10]
float G3D::Ray::intersectionTime (const Point3 & vert0, const Point3 & vert1, const Point3 & vert2, float & w0, float & w1, float & w2) const inline
Definition at line 185 of file Ray.h.
{
         return intersectionTime(vert0, vert1, vert2, vert1 - vert0, vert2 - vert0, w0, w1, w2);
     }
References intersectionTime().
intersectionTime() [8/10]
float G3D::Ray::intersectionTime (const Triangle & triangle) const inline
Definition at line 199 of file Ray.h.
{
         return intersectionTime(
             triangle.vertex(0), triangle.vertex(1), triangle.vertex(2),
             triangle.edge01(), triangle.edge02());
     }
References intersectionTime().
intersectionTime() [9/10]
float G3D::Ray::intersectionTime (const Triangle & triangle, float & w0, float & w1, float & w2) const inline
Definition at line 206 of file Ray.h.
{
         return intersectionTime(triangle.vertex(0), triangle.vertex(1), triangle.vertex(2),
             triangle.edge01(), triangle.edge02(), w0, w1, w2);
     }
References intersectionTime().
intersectionTime() [10/10]
float G3D::Ray::intersectionTime (const Vector3 & v0, const Vector3 & v1, const Vector3 & v2, const Vector3 & edge01, const Vector3 & edge02, float & w0, float & w1, float & w2) const inline
The three extra arguments are the weights of vertices 0, 1, and 2 at the intersection point; they are useful for texture mapping and interpolated normals.
Definition at line 306 of file Ray.h.
{
     (void)vert1;
     (void)vert2;
     // Barycenteric coords
     float u, v;
     float tvec[3], pvec[3], qvec[3];
     // begin calculating determinant - also used to calculate U parameter
     CROSS(pvec, m_direction, edge2);
     // if determinant is near zero, ray lies in plane of triangle
     const float det = DOT(edge1, pvec);
     if (det < EPSILON) {
         return finf();
     }
     // calculate distance from vert0 to ray origin
     SUB(tvec, m_origin, vert0);
     // calculate U parameter and test bounds
     u = DOT(tvec, pvec);
     if ((u < 0.0f) || (u > det)) {
         // Hit the plane outside the triangle
         return finf();
     }
     // prepare to test V parameter
     CROSS(qvec, tvec, edge1);
     // calculate V parameter and test bounds
     v = DOT(m_direction, qvec);
     if ((v < 0.0f) || (u + v > det)) {
         // Hit the plane outside the triangle
         return finf();
     }
     float t = DOT(edge2, qvec);
     if (t >= 0) {
         const float inv_det = 1.0f / det;
         t *= inv_det;
         u *= inv_det;
         v *= inv_det;
         w0 = (1.0f - u - v);
         w1 = u;
         w2 = v;
         return t;
     } else {
         // We had to travel backwards in time to intersect
         return finf();
     }
 }
References CROSS, DOT, EPSILON, G3D::finf(), m_direction, m_origin, and SUB.
invDirection()
const Vector3& G3D::Ray::invDirection () const inline
Component-wise inverse of direction vector. May have inf() components
Definition at line 66 of file Ray.h.
{
         return m_invDirection;
     }
References m_invDirection.
Referenced by RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::intersectRay().
origin()
const Point3& G3D::Ray::origin () const inline
Definition at line 56 of file Ray.h.
{
         return m_origin;
     }
References m_origin.
Referenced by G3D::findRayCapsuleIntersection(), G3D::Triangle::intersect(), VMAP::ModelInstance::intersectRay(), BIH::intersectRay(), GameObjectModel::intersectRay(), RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::intersectRay(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Node::intersectRay(), G3D::KDTree< T, BoundsFunc, HashFunc, EqualsFunc >::Node::intersects(), VMAP::IntersectTriangle(), RegularGrid2D< T, Node, NodeCreatorFunc, PositionFunc >::intersectZAllignedRay(), Ray(), G3D::CollisionDetection::rayAABox(), set(), G3D::CoordinateFrame::toObjectSpace(), G3D::CoordinateFrame::toWorldSpace(), and G3D::GCamera::unproject().
reflect()
Ray G3D::Ray::reflect (const Vector3 & newOrigin, const Vector3 & normal) const
Reflects about the normal using G3D::Vector3::reflectionDirection and bumps the ray slightly from the newOrigin.
Definition at line 155 of file Ray.cpp.
{
     Vector3 D = m_direction.reflectionDirection(normal);
     return Ray(newOrigin + (D + normal) * 0.001f, D);
 }
References m_direction, Ray(), and G3D::Vector3::reflectionDirection().
refract()
Ray G3D::Ray::refract (const Vector3 & newOrigin, const Vector3 & normal, float iInside, float iOutside) const
Refracts about the normal using G3D::Vector3::refractionDirection and bumps the ray slightly from the newOrigin.
Definition at line 144 of file Ray.cpp.
{
     Vector3 D = m_direction.refractionDirection(normal, iInside, iOutside);
     return Ray(newOrigin + (m_direction + normal * (float)sign(m_direction.dot(normal))) * 0.001f, D);
 }
References G3D::Vector3::dot(), m_direction, Ray(), G3D::Vector3::refractionDirection(), and G3D::sign().
serialize()
void G3D::Ray::serialize (class BinaryOutput & b) const
Definition at line 131 of file Ray.cpp.
{
     m_origin.serialize(b);
     m_direction.serialize(b);
 }
References b, m_direction, m_origin, and G3D::Vector3::serialize().
set()
void G3D::Ray::set (const Point3 & origin, const Vector3 & direction)
Parameters
direction Assumed to have unit length
Definition at line 18 of file Ray.cpp.
{
     m_origin = origin;
     m_direction = direction;
     debugAssert(direction.isUnit());
     m_invDirection = Vector3::one() / direction;
     // ray slope
     ibyj = m_direction.x * m_invDirection.y;
     jbyi = m_direction.y * m_invDirection.x;
     jbyk = m_direction.y * m_invDirection.z;
     kbyj = m_direction.z * m_invDirection.y;
     ibyk = m_direction.x * m_invDirection.z;
     kbyi = m_direction.z * m_invDirection.x;
     // precomputed terms
     c_xy = m_origin.y - jbyi * m_origin.x;
     c_xz = m_origin.z - kbyi * m_origin.x;
     c_yx = m_origin.x - ibyj * m_origin.y;
     c_yz = m_origin.z - kbyj * m_origin.y;
     c_zx = m_origin.x - ibyk * m_origin.z;
     c_zy = m_origin.y - jbyk * m_origin.z;
     //ray slope classification
     if (m_direction.x < 0) {
         if (m_direction.y < 0) {
             if (m_direction.z < 0) {
                 classification = MMM;
             } else if (m_direction.z > 0) {
                 classification = MMP;
             } else { //(m_direction.z >= 0)
                 classification = MMO;
             }
         } else { //(m_direction.y >= 0)
             if (m_direction.z < 0) {
                 if (m_direction.y == 0) {
                     classification = MOM;
                 } else {
                     classification = MPM;
                 }
             } else { //(m_direction.z >= 0)
                 if ((m_direction.y == 0) && (m_direction.z == 0)) {
                     classification = MOO;
                 } else if (m_direction.z == 0) {
                     classification = MPO;
                 } else if (m_direction.y == 0) {
                     classification = MOP;
                 } else {
                     classification = MPP;
                 }
             }
         }
     } else { //(m_direction.x >= 0)
         if (m_direction.y < 0) {
             if (m_direction.z < 0) {
                 if (m_direction.x == 0) {
                     classification = OMM;
                 } else {
                     classification = PMM;
                 }
             } else { //(m_direction.z >= 0)
                 if ((m_direction.x == 0) && (m_direction.z == 0)) {
                     classification = OMO;
                 } else if (m_direction.z == 0) {
                     classification = PMO;
                 } else if (m_direction.x == 0) {
                     classification = OMP;
                 } else {
                     classification = PMP;
                 }
             }
         } else { //(m_direction.y >= 0)
             if (m_direction.z < 0) {
                 if ((m_direction.x == 0) && (m_direction.y == 0)) {
                     classification = OOM;
                 } else if (m_direction.x == 0) {
                     classification = OPM;
                 } else if (m_direction.y == 0) {
                     classification = POM;
                 } else {
                     classification = PPM;
                 }
             } else { //(m_direction.z > 0)
                 if (m_direction.x == 0) {
                     if (m_direction.y == 0) {
                         classification = OOP;
                     } else if (m_direction.z == 0) {
                         classification = OPO;
                     } else {
                         classification = OPP;
                     }
                 } else {
                     if ((m_direction.y == 0) && (m_direction.z == 0)) {
                         classification = POO;
                     } else if (m_direction.y == 0) {
                         classification = POP;
                     } else if (m_direction.z == 0) {
                         classification = PPO;
                     } else {
                         classification = PPP;
                     }
                 }
             }
         }
     }
 }
References c_xy, c_xz, c_yx, c_yz, c_zx, c_zy, classification, debugAssert, direction(), ibyj, ibyk, G3D::Vector3::isUnit(), jbyi, jbyk, kbyi, kbyj, m_direction, m_invDirection, m_origin, MMM, MMO, MMP, MOM, MOO, MOP, MPM, MPO, MPP, OMM, OMO, OMP, G3D::Vector3::one(), OOM, OOP, OPM, OPO, OPP, origin(), PMM, PMO, PMP, POM, POO, POP, PPM, PPO, PPP, G3D::Vector3::x, G3D::Vector3::y, and G3D::Vector3::z.
Referenced by deserialize(), and Ray().
Friends And Related Function Documentation
Intersect
friend class Intersect friend
Definition at line 26 of file Ray.h.
Member Data Documentation
c_xy
float G3D::Ray::c_xy private
Precomputed components
Definition at line 50 of file Ray.h.
Referenced by G3D::Intersect::rayAABox(), and set().
c_xz
float G3D::Ray::c_xz private
Definition at line 50 of file Ray.h.
Referenced by G3D::Intersect::rayAABox(), and set().
c_yx
float G3D::Ray::c_yx private
Definition at line 50 of file Ray.h.
Referenced by G3D::Intersect::rayAABox(), and set().
c_yz
float G3D::Ray::c_yz private
Definition at line 50 of file Ray.h.
Referenced by G3D::Intersect::rayAABox(), and set().
c_zx
float G3D::Ray::c_zx private
Definition at line 50 of file Ray.h.
Referenced by G3D::Intersect::rayAABox(), and set().
c_zy
float G3D::Ray::c_zy private
Definition at line 50 of file Ray.h.
Referenced by G3D::Intersect::rayAABox(), and set().
classification
Classification G3D::Ray::classification private
Definition at line 44 of file Ray.h.
Referenced by G3D::Intersect::rayAABox(), and set().
ibyj
float G3D::Ray::ibyj private
ray slope
Definition at line 47 of file Ray.h.
Referenced by G3D::Intersect::rayAABox(), and set().
ibyk
float G3D::Ray::ibyk private
Definition at line 47 of file Ray.h.
Referenced by G3D::Intersect::rayAABox(), and set().
jbyi
float G3D::Ray::jbyi private
Definition at line 47 of file Ray.h.
Referenced by G3D::Intersect::rayAABox(), and set().
jbyk
float G3D::Ray::jbyk private
Definition at line 47 of file Ray.h.
Referenced by G3D::Intersect::rayAABox(), and set().
kbyi
float G3D::Ray::kbyi private
Definition at line 47 of file Ray.h.
Referenced by G3D::Intersect::rayAABox(), and set().
kbyj
float G3D::Ray::kbyj private
Definition at line 47 of file Ray.h.
Referenced by G3D::Intersect::rayAABox(), and set().
m_direction
Vector3 G3D::Ray::m_direction private
Unit length
Definition at line 31 of file Ray.h.
Referenced by bumpedRay(), closestPoint(), deserialize(), direction(), intersection(), intersectionTime(), reflect(), refract(), serialize(), and set().
m_invDirection
Vector3 G3D::Ray::m_invDirection private
1.0 / direction
Definition at line 34 of file Ray.h.
Referenced by invDirection(), G3D::Intersect::rayAABox(), and set().
m_origin
Point3 G3D::Ray::m_origin private
Definition at line 28 of file Ray.h.
Referenced by bumpedRay(), closestPoint(), deserialize(), intersection(), intersectionTime(), origin(), G3D::Intersect::rayAABox(), serialize(), and set().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/Ray.h
deps/g3dlite/source/Ray.cpp