Azerotcore-wotlk: npc_riggle_bassbait Class Reference
npc_riggle_bassbait Class Reference
Classes
struct npc_riggle_bassbaitAI
Public Member Functions
npc_riggle_bassbait ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnQuestReward (Player *player, Creature *creature, Quest const *quest, uint32) override
CreatureAI * GetAI (Creature *pCreature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 221 of file npcs_special.cpp.
Constructor & Destructor Documentation
npc_riggle_bassbait()
npc_riggle_bassbait::npc_riggle_bassbait () inline
Definition at line 224 of file npcs_special.cpp.
 : CreatureScript("npc_riggle_bassbait") { }
Member Function Documentation
GetAI()
CreatureAI* npc_riggle_bassbait::GetAI (Creature * pCreature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 309 of file npcs_special.cpp.
     {
         return new npc_riggle_bassbaitAI (pCreature);
     }
OnGossipHello()
bool npc_riggle_bassbait::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 290 of file npcs_special.cpp.
     {
         if (!creature->AI()->GetData(DATA_ANGLER_FINISHED))
             player->PrepareQuestMenu(creature->GetGUID());
         SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
         return true;
     }
References Creature::AI(), DATA_ANGLER_FINISHED, UnitAI::GetData(), Player::GetGossipTextId(), Object::GetGUID(), Player::PrepareQuestMenu(), and SendGossipMenuFor().
OnQuestReward()
bool npc_riggle_bassbait::OnQuestReward (Player * player, Creature * creature, Quest const * quest, uint32) inline override virtual
Reimplemented from CreatureScript.
Definition at line 299 of file npcs_special.cpp.
     {
         if (!creature->AI()->GetData(DATA_ANGLER_FINISHED) && quest->GetQuestId() == QUEST_MASTER_ANGLER)
         {
             creature->AI()->DoAction(DATA_ANGLER_FINISHED);
             sCreatureTextMgr->SendChat(creature, RIGGLE_SAY_WINNER, player, CHAT_MSG_MONSTER_YELL, LANG_UNIVERSAL, TEXT_RANGE_ZONE);
         }
         return true;
     }
References Creature::AI(), CHAT_MSG_MONSTER_YELL, DATA_ANGLER_FINISHED, UnitAI::DoAction(), UnitAI::GetData(), Quest::GetQuestId(), LANG_UNIVERSAL, QUEST_MASTER_ANGLER, RIGGLE_SAY_WINNER, sCreatureTextMgr, and TEXT_RANGE_ZONE.
The documentation for this class was generated from the following file:
src/server/scripts/World/npcs_special.cpp