Azerotcore-wotlk: G3D::Plane Class Reference
G3D::Plane Class Reference
#include <Plane.h>
Public Member Functions
Plane ()
Plane (const class Any &a)
Any toAny () const
Plane (const Point3 &point0, const Point3 &point1, const Point3 &point2)
Plane (Vector4 point0, Vector4 point1, Vector4 point2)
Plane (const Vector3 &normal, const Point3 &point)
Plane (class BinaryInput &b)
void serialize (class BinaryOutput &b) const
void deserialize (class BinaryInput &b)
virtual ~Plane ()
bool halfSpaceContains (Point3 point) const
bool halfSpaceContains (const Vector4 &point) const
bool halfSpaceContainsFinite (const Point3 &point) const
bool fuzzyContains (const Point3 &point) const
const Vector3 & normal () const
float distance (const Vector3 &x) const
Point3 closestPoint (const Point3 &x) const
Vector3 center () const
void flip ()
void getEquation (Vector3 &normal, double &d) const
void getEquation (Vector3 &normal, float &d) const
void getEquation (double &a, double &b, double &c, double &d) const
void getEquation (float &a, float &b, float &c, float &d) const
std::string toString () const
Static Public Member Functions
static Plane fromEquation (float a, float b, float c, float d)
Private Member Functions
Plane (const Vector3 &n, float d)
Private Attributes
Vector3 _normal
float _distance
Detailed Description
An infinite 2D plane in 3D space.
Definition at line 25 of file Plane.h.
Constructor & Destructor Documentation
Plane() [1/7]
G3D::Plane::Plane (const Vector3 & n, float d) inline private
Assumes the normal has unit length.
Definition at line 35 of file Plane.h.
                                      : _normal(n), _distance(d) {
     }
Plane() [2/7]
G3D::Plane::Plane () inline
Definition at line 40 of file Plane.h.
             : _normal(Vector3::unitY()), _distance(0) {
     }
Referenced by fromEquation().
Plane() [3/7]
G3D::Plane::Plane (const class Any & a) explicit
Format is:
Plane(normal, point)
Plane() [4/7]
G3D::Plane::Plane (const Point3 & point0, const Point3 & point1, const Point3 & point2)
Constructs a plane from three points.
Definition at line 98 of file Plane.cpp.
{
     _normal   = (point1 - point0).cross(point2 - point0).direction();
     _distance = _normal.dot(point0);
 }
References _distance, _normal, G3D::cross(), G3D::Vector3::direction(), and G3D::Vector3::dot().
Plane() [5/7]
G3D::Plane::Plane (Vector4 point0, Vector4 point1, Vector4 point2)
Constructs a plane from three points, where at most two are at infinity (w = 0, not xyz = inf).
Definition at line 51 of file Plane.cpp.
                       {
     debugAssertM(
         point0.w != 0 ||
         point1.w != 0 ||
         point2.w != 0,
         "At least one point must be finite.");
     // Rotate the points around so that the finite points come first.
     while ((point0.w == 0) &&
            ((point1.w == 0) || (point2.w != 0))) {
         Vector4 temp = point0;
         point0 = point1;
         point1 = point2;
         point2 = temp;
     }
     Vector3 dir1;
     Vector3 dir2;
     if (point1.w == 0) {
         // 1 finite, 2 infinite points; the plane must contain
         // the direction of the two direcitons
         dir1 = point1.xyz();
         dir2 = point2.xyz();
     } else if (point2.w != 0) {
         // 3 finite points, the plane must contain the directions
         // betwseen the points.
         dir1 = point1.xyz() - point0.xyz();
         dir2 = point2.xyz() - point0.xyz();
     } else {
         // 2 finite, 1 infinite point; the plane must contain
         // the direction between the first two points and the
         // direction of the third point.
         dir1 = point1.xyz() - point0.xyz();
         dir2 = point2.xyz();
     }
     _normal   = dir1.cross(dir2).direction();
     _distance = _normal.dot(point0.xyz());
 }
References _distance, _normal, G3D::Vector3::cross(), debugAssertM, G3D::Vector3::direction(), G3D::Vector3::dot(), G3D::Vector4::w, and G3D::Vector4::xyz().
Plane() [6/7]
G3D::Plane::Plane (const Vector3 & normal, const Point3 & point)
The normal will be unitized.
Definition at line 108 of file Plane.cpp.
{
     _normal    = __normal.direction();
     _distance  = _normal.dot(point);
 }
References _distance, _normal, G3D::Vector3::direction(), and G3D::Vector3::dot().
Plane() [7/7]
G3D::Plane::Plane (class BinaryInput & b)
Definition at line 34 of file Plane.cpp.
{
     deserialize(b);
 }
References b, and deserialize().
~Plane()
virtual G3D::Plane::~Plane () inline virtual
Definition at line 81 of file Plane.h.
 {}
Member Function Documentation
center()
Vector3 G3D::Plane::center () const inline
Returns normal * distance from origin
Definition at line 140 of file Plane.h.
{
         return _normal * _distance;
     }
References _distance, and _normal.
closestPoint()
Point3 G3D::Plane::closestPoint (const Point3 & x) const inline
Definition at line 135 of file Plane.h.
{
         return x + (_normal * (-distance(x)));
     }
References _normal, distance(), and G3D::x.
Referenced by G3D::CollisionDetection::fixedSolidSphereIntersectsFixedTriangle().
deserialize()
void G3D::Plane::deserialize (class BinaryInput & b)
Definition at line 45 of file Plane.cpp.
{
     _normal.deserialize(b);
     _distance = (float)b.readFloat64();
 }
References _distance, _normal, b, and G3D::Vector3::deserialize().
Referenced by Plane().
distance()
float G3D::Plane::distance (const Vector3 & x) const inline
Returns distance from point to plane. Distance is negative if point is behind (not in plane in direction opposite normal) the plane.
Definition at line 131 of file Plane.h.
{
         return (_normal.dot(x) - _distance);
     }
References _distance, _normal, G3D::Vector3::dot(), and G3D::x.
Referenced by closestPoint(), and GridMap::getMinHeight().
flip()
void G3D::Plane::flip ()
Inverts the facing direction of the plane so the new normal is the inverse of the old normal.
Definition at line 126 of file Plane.cpp.
                  {
     _normal   = -_normal;
     _distance  = -_distance;
 }
References _distance, and _normal.
fromEquation()
Plane G3D::Plane::fromEquation (float a, float b, float c, float d) static
Definition at line 117 of file Plane.cpp.
{
     Vector3 n(a, b, c);
     float magnitude = n.magnitude();
     d /= magnitude;
     n /= magnitude;
     return Plane(n, -d);
 }
References mpq::a, b, mpq::c, mpq::d, G3D::Vector3::magnitude(), and Plane().
Referenced by G3D::GCamera::frustum().
fuzzyContains()
bool G3D::Plane::fuzzyContains (const Point3 & point) const inline
Returns true if the point is nearly in the plane.
Definition at line 120 of file Plane.h.
{
         return fuzzyEq(point.dot(_normal), _distance);
     }
References _distance, _normal, G3D::Vector3::dot(), and G3D::fuzzyEq().
Referenced by G3D::ConvexPolyhedron::cut().
getEquation() [1/4]
void G3D::Plane::getEquation (double & a, double & b, double & c, double & d) const
ax + by + cz + d = 0
Definition at line 153 of file Plane.cpp.
{
     a = _normal.x;
     b = _normal.y;
     c = _normal.z;
     d = -_distance;
 }
References _distance, _normal, mpq::a, b, mpq::c, mpq::d, G3D::Vector3::x, G3D::Vector3::y, and G3D::Vector3::z.
getEquation() [2/4]
void G3D::Plane::getEquation (float & a, float & b, float & c, float & d) const
Definition at line 144 of file Plane.cpp.
{
     double _a, _b, _c, _d;
     getEquation(_a, _b, _c, _d);
     a = (float)_a;
     b = (float)_b;
     c = (float)_c;
     d = (float)_d;
 }
References mpq::a, b, mpq::c, mpq::d, and getEquation().
getEquation() [3/4]
void G3D::Plane::getEquation (Vector3 & normal, double & d) const
Returns the equation in the form:
normal.Dot(Vector3(x, y, z)) + d = 0
Definition at line 138 of file Plane.cpp.
{
     n = _normal;
     d = -_distance;
 }
References _distance, _normal, and mpq::d.
Referenced by G3D::CollisionDetection::closestPointToRectangle(), G3D::CollisionDetection::collisionTimeForMovingPointFixedPlane(), G3D::CollisionDetection::collisionTimeForMovingSphereFixedPlane(), G3D::ConvexPolygon::cut(), G3D::ConvexPolyhedron::cut(), getEquation(), G3D::Ray::intersection(), G3D::Line::intersection(), G3D::CollisionDetection::penetrationDepthForFixedBoxFixedPlane(), G3D::CollisionDetection::penetrationDepthForFixedSphereFixedPlane(), and G3D::CoordinateFrame::toObjectSpace().
getEquation() [4/4]
void G3D::Plane::getEquation (Vector3 & normal, float & d) const
Definition at line 132 of file Plane.cpp.
{
     double _d;
     getEquation(n, _d);
     d = (float)_d;
 }
References mpq::d, and getEquation().
halfSpaceContains() [1/2]
bool G3D::Plane::halfSpaceContains (const Vector4 & point) const inline
Returns true if point is on the side the normal points to or is in the plane.
Definition at line 100 of file Plane.h.
{
         if (point.w == 0) {
             return _normal.dot(point.xyz()) > 0;
         } else {
             return halfSpaceContains(point.xyz() / point.w);
         }
     }
References _normal, G3D::Vector3::dot(), halfSpaceContains(), G3D::Vector4::w, and G3D::Vector4::xyz().
halfSpaceContains() [2/2]
bool G3D::Plane::halfSpaceContains (Point3 point) const inline
Returns true if point is on the side the normal points to or is in the plane.
Definition at line 87 of file Plane.h.
{
         // Clamp to a finite range for testing
         point = point.clamp(Vector3::minFinite(), Vector3::maxFinite());
         // We can get away with putting values *at* the limits of the float32 range into
         // a dot product, since the dot product is carried out on float64.
         return _normal.dot(point) >= _distance;
     }
References _distance, _normal, G3D::Vector3::clamp(), G3D::Vector3::dot(), G3D::Vector3::maxFinite(), and G3D::Vector3::minFinite().
Referenced by G3D::ConvexPolygon::cut(), G3D::PointKDTree< T, PositionFunc, HashFunc, EqualsFunc >::getIntersectingMembers(), and halfSpaceContains().
halfSpaceContainsFinite()
bool G3D::Plane::halfSpaceContainsFinite (const Point3 & point) const inline
Returns true if point is on the side the normal points to or is in the plane. Only call on finite points. Faster than halfSpaceContains.
Definition at line 112 of file Plane.h.
{
         debugAssert(point.isFinite());
         return _normal.dot(point) >= _distance;
     }
References _distance, _normal, debugAssert, G3D::Vector3::dot(), and G3D::Vector3::isFinite().
normal()
const Vector3& G3D::Plane::normal () const inline
Definition at line 124 of file Plane.h.
{
         return _normal;
     }
References _normal.
Referenced by G3D::CollisionDetection::closestPointToRectangle(), G3D::CollisionDetection::collisionTimeForMovingPointFixedRectangle(), G3D::CollisionDetection::collisionTimeForMovingSphereFixedRectangle(), G3D::ConvexPolygon::cut(), G3D::Triangle::init(), G3D::Ray::intersection(), G3D::Line::intersection(), G3D::Triangle::normal(), and toAny().
serialize()
void G3D::Plane::serialize (class BinaryOutput & b) const
Definition at line 39 of file Plane.cpp.
{
     _normal.serialize(b);
     b.writeFloat64(_distance);
 }
References _distance, _normal, b, and G3D::Vector3::serialize().
toAny()
Any G3D::Plane::toAny () const
Definition at line 27 of file Plane.cpp.
{
     Any a(Any::ARRAY, "Plane");
     a.append(normal(), normal() * _distance);
     return a;
 }
References _distance, mpq::a, G3D::Any::ARRAY, and normal().
toString()
std::string G3D::Plane::toString () const
Definition at line 161 of file Plane.cpp.
{
     return format("Plane(%g, %g, %g, %g)", _normal.x, _normal.y, _normal.z, _distance);
 }
References _distance, _normal, G3D::format(), G3D::Vector3::x, G3D::Vector3::y, and G3D::Vector3::z.
Member Data Documentation
_distance
float G3D::Plane::_distance private
Definition at line 30 of file Plane.h.
Referenced by center(), deserialize(), distance(), flip(), fuzzyContains(), getEquation(), halfSpaceContains(), halfSpaceContainsFinite(), Plane(), serialize(), toAny(), and toString().
_normal
Vector3 G3D::Plane::_normal private
normal.Dot(x,y,z) = distance
Definition at line 29 of file Plane.h.
Referenced by center(), closestPoint(), deserialize(), distance(), flip(), fuzzyContains(), getEquation(), halfSpaceContains(), halfSpaceContainsFinite(), normal(), Plane(), serialize(), and toString().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/Plane.h
deps/g3dlite/source/Plane.cpp