Azerotcore-wotlk: Acore::Crypto::TOTP Struct Reference
Acore::Crypto::TOTP Struct Reference
#include <TOTP.h>
Public Types
using Secret = std::vector< uint8 >
Static Public Member Functions
static uint32 GenerateToken (Secret const &key, time_t timestamp)
static bool ValidateToken (Secret const &key, uint32 token)
Static Public Attributes
static constexpr size_t RECOMMENDED_SECRET_LENGTH = 20
Detailed Description
Definition at line 15 of file TOTP.h.
Member Typedef Documentation
Secret
using Acore::Crypto::TOTP::Secret = std::vector<uint8>
Definition at line 18 of file TOTP.h.
Member Function Documentation
GenerateToken()
uint32 Acore::Crypto::TOTP::GenerateToken (Secret const & key, time_t timestamp) static
Definition at line 14 of file TOTP.cpp.
 {
     timestamp /= TOTP_INTERVAL;
     unsigned char challenge[8];
     for (int i = 8; i--; timestamp >>= 8)
     {
         challenge[i] = timestamp;
     }
     unsigned char digest[HMAC_RESULT_SIZE];
     uint32 digestSize = HMAC_RESULT_SIZE;
     HMAC(EVP_sha1(), secret.data(), secret.size(), challenge, 8, digest, &digestSize);
     uint32 offset = digest[19] & 0xF;
     uint32 truncated = (digest[offset] << 24) | (digest[offset + 1] << 16) | (digest[offset + 2] << 8) | (digest[offset + 3]);
     truncated &= 0x7FFFFFFF;
     return (truncated % 1000000);
 }
References HMAC_RESULT_SIZE, and TOTP_INTERVAL.
ValidateToken()
bool Acore::Crypto::TOTP::ValidateToken (Secret const & key, uint32 token) static
Definition at line 35 of file TOTP.cpp.
 {
     time_t now = time(nullptr);
     return (
         (token == GenerateToken(secret, now - TOTP_INTERVAL)) ||
         (token == GenerateToken(secret, now)) ||
         (token == GenerateToken(secret, now + TOTP_INTERVAL))
     );
 }
References TOTP_INTERVAL.
Referenced by account_commandscript::HandleAccount2FARemoveCommand(), account_commandscript::HandleAccount2FASetupCommand(), and AuthSession::HandleLogonProof().
Member Data Documentation
RECOMMENDED_SECRET_LENGTH
constexpr std::size_t Acore::Crypto::TOTP::RECOMMENDED_SECRET_LENGTH = 20 static constexpr
Definition at line 17 of file TOTP.h.
Referenced by account_commandscript::HandleAccount2FASetupCommand().
The documentation for this struct was generated from the following files:
src/common/Cryptography/TOTP.h
src/common/Cryptography/TOTP.cpp