Azerotcore-wotlk: lfg::LFGPlayerScript Class Reference
lfg::LFGPlayerScript Class Reference
#include <LFGScripts.h>
Public Member Functions
LFGPlayerScript ()
void OnLevelChanged (Player *player, uint8 oldLevel) override
void OnLogout (Player *player) override
void OnLogin (Player *player) override
void OnBindToInstance (Player *player, Difficulty difficulty, uint32 mapId, bool permanent) override
void OnMapChanged (Player *player) override
Public Member Functions inherited from PlayerScript
virtual void OnPlayerReleasedGhost (Player *)
virtual void OnSendInitialPacketsBeforeAddToMap (Player *, WorldPacket &)
virtual void OnBattlegroundDesertion (Player *, BattlegroundDesertionType const)
virtual void OnPlayerCompleteQuest (Player *, Quest const *)
virtual void OnPVPKill (Player *, Player *)
virtual void OnPlayerPVPFlagChange (Player *, bool)
virtual void OnCreatureKill (Player *, Creature *)
virtual void OnCreatureKilledByPet (Player *, Creature *)
virtual void OnPlayerKilledByCreature (Creature *, Player *)
virtual void OnFreeTalentPointsChanged (Player *, uint32)
virtual void OnTalentsReset (Player *, bool)
virtual void OnBeforeUpdate (Player *, uint32)
virtual void OnUpdate (Player *, uint32)
virtual void OnMoneyChanged (Player *, int32 &)
virtual void OnGiveXP (Player *, uint32 &, Unit *)
virtual void OnReputationChange (Player *, uint32, int32 &, bool)
virtual void OnReputationRankChange (Player *, uint32, ReputationRank, ReputationRank, bool)
virtual void OnLearnSpell (Player *, uint32)
virtual void OnForgotSpell (Player *, uint32)
virtual void OnDuelRequest (Player *, Player *)
virtual void OnDuelStart (Player *, Player *)
virtual void OnDuelEnd (Player *, Player *, DuelCompleteType)
virtual void OnChat (Player *, uint32, uint32, std::string &)
virtual void OnBeforeSendChatMessage (Player *, uint32 &, uint32 &, std::string &)
virtual void OnChat (Player *, uint32, uint32, std::string &, Player *)
virtual void OnChat (Player *, uint32, uint32, std::string &, Group *)
virtual void OnChat (Player *, uint32, uint32, std::string &, Guild *)
virtual void OnChat (Player *, uint32, uint32, std::string &, Channel *)
virtual void OnEmote (Player *, uint32)
virtual void OnTextEmote (Player *, uint32, uint32, ObjectGuid)
virtual void OnSpellCast (Player *, Spell *, bool)
virtual void OnLoadFromDB (Player *)
virtual void OnCreate (Player *)
virtual void OnDelete (ObjectGuid, uint32)
virtual void OnFailedDelete (ObjectGuid, uint32)
virtual void OnSave (Player *)
virtual void OnUpdateZone (Player *, uint32, uint32)
virtual void OnUpdateArea (Player *, uint32, uint32)
virtual bool OnBeforeTeleport (Player *, uint32, float, float, float, float, uint32, Unit *)
virtual void OnUpdateFaction (Player *)
virtual void OnAddToBattleground (Player *, Battleground *)
virtual void OnQueueRandomDungeon (Player *, uint32 &)
virtual void OnRemoveFromBattleground (Player *, Battleground *)
virtual void OnAchiComplete (Player *, AchievementEntry const *)
virtual bool OnBeforeAchiComplete (Player *, AchievementEntry const *)
virtual void OnCriteriaProgress (Player *, AchievementCriteriaEntry const *)
virtual bool OnBeforeCriteriaProgress (Player *, AchievementCriteriaEntry const *)
virtual void OnAchiSave (CharacterDatabaseTransaction, Player *, uint16, CompletedAchievementData)
virtual void OnCriteriaSave (CharacterDatabaseTransaction, Player *, uint16, CriteriaProgress)
virtual void OnGossipSelect (Player *, uint32, uint32, uint32)
virtual void OnGossipSelectCode (Player *, uint32, uint32, uint32, const char *)
virtual void OnBeingCharmed (Player *, Unit *, uint32, uint32)
virtual void OnAfterSetVisibleItemSlot (Player *, uint8, Item *)
virtual void OnAfterMoveItemFromInventory (Player *, Item *, uint8, uint8, bool)
virtual void OnEquip (Player *, Item *, uint8, uint8, bool)
virtual void OnPlayerJoinBG (Player *)
virtual void OnPlayerJoinArena (Player *)
virtual void GetCustomGetArenaTeamId (const Player *, uint8, uint32 &) const
virtual void GetCustomArenaPersonalRating (const Player *, uint8, uint32 &) const
virtual void OnGetMaxPersonalArenaRatingRequirement (const Player *, uint32, uint32 &) const
virtual void OnLootItem (Player *, Item *, uint32, ObjectGuid)
virtual void OnCreateItem (Player *, Item *, uint32)
virtual void OnQuestRewardItem (Player *, Item *, uint32)
virtual bool OnBeforeQuestComplete (Player *, uint32)
virtual void OnBeforeDurabilityRepair (Player *, ObjectGuid, ObjectGuid, float &, uint8)
virtual void OnBeforeBuyItemFromVendor (Player *, ObjectGuid, uint32, uint32 &, uint8, uint8, uint8)
virtual void OnBeforeStoreOrEquipNewItem (Player *, uint32, uint32 &, uint8, uint8, uint8, ItemTemplate const *, Creature *, VendorItem const *, bool)
virtual void OnAfterStoreOrEquipNewItem (Player *, uint32, Item *, uint8, uint8, uint8, ItemTemplate const *, Creature *, VendorItem const *, bool)
virtual void OnAfterUpdateMaxPower (Player *, Powers &, float &)
virtual void OnAfterUpdateMaxHealth (Player *, float &)
virtual void OnBeforeUpdateAttackPowerAndDamage (Player *, float &, float &, bool)
virtual void OnAfterUpdateAttackPowerAndDamage (Player *, float &, float &, float &, float &, bool)
virtual void OnBeforeInitTalentForLevel (Player *, uint8 &, uint32 &)
virtual void OnFirstLogin (Player *)
virtual bool CanJoinInBattlegroundQueue (Player *, ObjectGuid, BattlegroundTypeId, uint8, GroupJoinBattlegroundResult &)
virtual bool ShouldBeRewardedWithMoneyInsteadOfExp (Player *)
virtual void OnBeforeTempSummonInitStats (Player *, TempSummon *, uint32 &)
virtual void OnBeforeGuardianInitStatsForLevel (Player *, Guardian *, CreatureTemplate const *, PetType &)
virtual void OnAfterGuardianInitStatsForLevel (Player *, Guardian *)
virtual void OnBeforeLoadPetFromDB (Player *, uint32 &, uint32 &, bool &, bool &)
virtual bool CanJoinInArenaQueue (Player *, ObjectGuid, uint8, BattlegroundTypeId, uint8, uint8, GroupJoinBattlegroundResult &)
virtual bool CanBattleFieldPort (Player *, uint8, BattlegroundTypeId, uint8)
virtual bool CanGroupInvite (Player *, std::string &)
virtual bool CanGroupAccept (Player *, Group *)
virtual bool CanSellItem (Player *, Item *, Creature *)
virtual bool CanSendMail (Player *, ObjectGuid, ObjectGuid, std::string &, std::string &, uint32, uint32, Item *)
virtual void PetitionBuy (Player *, Creature *, uint32 &, uint32 &, uint32 &)
virtual void PetitionShowList (Player *, Creature *, uint32 &, uint32 &, uint32 &)
virtual void OnRewardKillRewarder (Player *, bool, float &)
virtual bool CanGiveMailRewardAtGiveLevel (Player *, uint8)
virtual void OnDeleteFromDB (CharacterDatabaseTransaction, uint32)
virtual bool CanRepopAtGraveyard (Player *)
virtual void OnGetMaxSkillValue (Player *, uint32, int32 &, bool)
virtual bool CanAreaExploreAndOutdoor (Player *)
virtual void OnVictimRewardBefore (Player *, Player *, uint32 &, uint32 &)
virtual void OnVictimRewardAfter (Player *, Player *, uint32 &, uint32 &, float &)
virtual void OnCustomScalingStatValueBefore (Player *, ItemTemplate const *, uint8, bool, uint32 &)
virtual void OnCustomScalingStatValue (Player *, ItemTemplate const *, uint32 &, int32 &, uint8, uint32, ScalingStatValuesEntry const *)
virtual bool CanArmorDamageModifier (Player *)
virtual void OnGetFeralApBonus (Player *, int32 &, int32, ItemTemplate const *, ScalingStatValuesEntry const *)
virtual bool CanApplyWeaponDependentAuraDamageMod (Player *, Item *, WeaponAttackType, AuraEffect const *, bool)
virtual bool CanApplyEquipSpell (Player *, SpellInfo const *, Item *, bool, bool)
virtual bool CanApplyEquipSpellsItemSet (Player *, ItemSetEffect *)
virtual bool CanCastItemCombatSpell (Player *, Unit *, WeaponAttackType, uint32, uint32, Item *, ItemTemplate const *)
virtual bool CanCastItemUseSpell (Player *, Item *, SpellCastTargets const &, uint8, uint32)
virtual void OnApplyAmmoBonuses (Player *, ItemTemplate const *, float &)
virtual bool CanEquipItem (Player *, uint8, uint16 &, Item *, bool, bool)
virtual bool CanUnequipItem (Player *, uint16, bool)
virtual bool CanUseItem (Player *, ItemTemplate const *, InventoryResult &)
virtual bool CanSaveEquipNewItem (Player *, Item *, uint16, bool)
virtual bool CanApplyEnchantment (Player *, Item *, EnchantmentSlot, bool, bool, bool)
virtual void OnGetQuestRate (Player *, float &)
virtual bool PassedQuestKilledMonsterCredit (Player *, Quest const *, uint32, uint32, ObjectGuid)
virtual bool CheckItemInSlotAtLoadInventory (Player *, Item *, uint8, uint8 &, uint16 &)
virtual bool NotAvoidSatisfy (Player *, DungeonProgressionRequirements const *, uint32, bool)
virtual bool NotVisibleGloballyFor (Player *, Player const *)
virtual void OnGetArenaPersonalRating (Player *, uint8, uint32 &)
virtual void OnGetArenaTeamId (Player *, uint8, uint32 &)
virtual void OnIsFFAPvP (Player *, bool &)
virtual void OnIsPvP (Player *, bool &)
virtual void OnGetMaxSkillValueForLevel (Player *, uint16 &)
virtual bool NotSetArenaTeamInfoField (Player *, uint8, ArenaTeamInfoType, uint32)
virtual bool CanJoinLfg (Player *, uint8, lfg::LfgDungeonSet &, const std::string &)
virtual bool CanEnterMap (Player *, MapEntry const *, InstanceTemplate const *, MapDifficulty const *, bool)
virtual bool CanInitTrade (Player *, Player *)
virtual void OnSetServerSideVisibility (Player *, ServerSideVisibilityType &, AccountTypes &)
virtual void OnSetServerSideVisibilityDetect (Player *, ServerSideVisibilityType &, AccountTypes &)
virtual void AnticheatSetSkipOnePacketForASH (Player *, bool)
virtual void AnticheatSetCanFlybyServer (Player *, bool)
virtual void AnticheatSetUnderACKmount (Player *)
virtual void AnticheatSetRootACKUpd (Player *)
virtual void AnticheatSetJumpingbyOpcode (Player *, bool)
virtual void AnticheatUpdateMovementInfo (Player *, MovementInfo const &)
virtual bool AnticheatHandleDoubleJump (Player *, Unit *)
virtual bool AnticheatCheckMovementInfo (Player *, MovementInfo const &, Unit *, bool)
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from PlayerScript
PlayerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 32 of file LFGScripts.h.
Constructor & Destructor Documentation
LFGPlayerScript()
lfg::LFGPlayerScript::LFGPlayerScript ()
Definition at line 33 of file LFGScripts.cpp.
                                      : PlayerScript("LFGPlayerScript")
     {
     }
Member Function Documentation
OnBindToInstance()
void lfg::LFGPlayerScript::OnBindToInstance (Player * player, Difficulty difficulty, uint32 mapId, bool permanent) override virtual
Reimplemented from PlayerScript.
Definition at line 88 of file LFGScripts.cpp.
     {
         MapEntry const* mapEntry = sMapStore.LookupEntry(mapId);
         if (mapEntry->IsDungeon() && difficulty > DUNGEON_DIFFICULTY_NORMAL)
             sLFGMgr->InitializeLockedDungeons(player);
     }
References DUNGEON_DIFFICULTY_NORMAL, MapEntry::IsDungeon(), sLFGMgr, and sMapStore.
OnLevelChanged()
void lfg::LFGPlayerScript::OnLevelChanged (Player * player, uint8 oldLevel) override virtual
Reimplemented from PlayerScript.
Definition at line 37 of file LFGScripts.cpp.
     {
         if (!sLFGMgr->isOptionEnabled(LFG_OPTION_ENABLE_DUNGEON_FINDER | LFG_OPTION_ENABLE_RAID_BROWSER | LFG_OPTION_ENABLE_SEASONAL_BOSSES))
             return;
         sLFGMgr->InitializeLockedDungeons(player);
     }
References lfg::LFG_OPTION_ENABLE_DUNGEON_FINDER, lfg::LFG_OPTION_ENABLE_RAID_BROWSER, lfg::LFG_OPTION_ENABLE_SEASONAL_BOSSES, and sLFGMgr.
OnLogin()
void lfg::LFGPlayerScript::OnLogin (Player * player) override virtual
Reimplemented from PlayerScript.
Definition at line 65 of file LFGScripts.cpp.
     {
         if (!sLFGMgr->isOptionEnabled(LFG_OPTION_ENABLE_DUNGEON_FINDER | LFG_OPTION_ENABLE_RAID_BROWSER | LFG_OPTION_ENABLE_SEASONAL_BOSSES))
             return;
         // Temporal: Trying to determine when group data and LFG data gets desynched
         ObjectGuid guid = player->GetGUID();
         ObjectGuid gguid = sLFGMgr->GetGroup(guid);
         if (Group const* group = player->GetGroup())
         {
             ObjectGuid gguid2 = group->GetGUID();
             if (gguid != gguid2)
             {
                 sLFGMgr->SetupGroupMember(guid, group->GetGUID());
             }
         }
         sLFGMgr->InitializeLockedDungeons(player);
         sLFGMgr->SetTeam(player->GetGUID(), player->GetTeamId());
         // TODO - Restore LfgPlayerData and send proper status to player if it was in a group
     }
References Player::GetGroup(), Object::GetGUID(), Player::GetTeamId(), lfg::LFG_OPTION_ENABLE_DUNGEON_FINDER, lfg::LFG_OPTION_ENABLE_RAID_BROWSER, lfg::LFG_OPTION_ENABLE_SEASONAL_BOSSES, and sLFGMgr.
OnLogout()
void lfg::LFGPlayerScript::OnLogout (Player * player) override virtual
Reimplemented from PlayerScript.
Definition at line 45 of file LFGScripts.cpp.
     {
         if (!sLFGMgr->isOptionEnabled(LFG_OPTION_ENABLE_DUNGEON_FINDER | LFG_OPTION_ENABLE_RAID_BROWSER | LFG_OPTION_ENABLE_SEASONAL_BOSSES))
             return;
         if (!player->GetGroup() || !player->GetGroup()->isLFGGroup())
         {
             player->GetSession()->SendLfgLfrList(false);
             sLFGMgr->LeaveLfg(player->GetGUID());
             sLFGMgr->LeaveAllLfgQueues(player->GetGUID(), true, player->GetGroup() ? player->GetGroup()->GetGUID() : ObjectGuid::Empty);
             // pussywizard: after all necessary actions handle raid browser
             // pussywizard: already done above
             //if (sLFGMgr->GetState(player->GetGUID()) == LFG_STATE_RAIDBROWSER)
             //  sLFGMgr->LeaveLfg(player->GetGUID());
         }
         sLFGMgr->LfrSearchRemove(player);
     }
References ObjectGuid::Empty, Player::GetGroup(), Group::GetGUID(), Object::GetGUID(), Player::GetSession(), Group::isLFGGroup(), lfg::LFG_OPTION_ENABLE_DUNGEON_FINDER, lfg::LFG_OPTION_ENABLE_RAID_BROWSER, lfg::LFG_OPTION_ENABLE_SEASONAL_BOSSES, WorldSession::SendLfgLfrList(), and sLFGMgr.
OnMapChanged()
void lfg::LFGPlayerScript::OnMapChanged (Player * player) override virtual
Reimplemented from PlayerScript.
Definition at line 95 of file LFGScripts.cpp.
     {
         Map const* map = player->GetMap();
         if (sLFGMgr->inLfgDungeonMap(player->GetGUID(), map->GetId(), map->GetDifficulty()))
         {
             Group* group = player->GetGroup();
             // This function is also called when players log in
             // if for some reason the LFG system recognises the player as being in a LFG dungeon,
             // but the player was loaded without a valid group, we'll teleport to homebind to prevent
             // crashes or other undefined behaviour
             if (!group)
             {
                 sLFGMgr->LeaveLfg(player->GetGUID());
                 sLFGMgr->LeaveAllLfgQueues(player->GetGUID(), true);
                 player->RemoveAurasDueToSpell(LFG_SPELL_LUCK_OF_THE_DRAW);
                 player->TeleportTo(player->m_homebindMapId, player->m_homebindX, player->m_homebindY, player->m_homebindZ, 0.0f);
                 LOG_DEBUG("lfg", "LFGPlayerScript::OnMapChanged, Player %s (%s) is in LFG dungeon map but does not have a valid group! Teleporting to homebind.",
                     player->GetName().c_str(), player->GetGUID().ToString().c_str());
                 return;
             }
             for (GroupReference* itr = group->GetFirstMember(); itr != nullptr; itr = itr->next())
                 if (Player* member = itr->GetSource())
                     player->GetSession()->SendNameQueryOpcode(member->GetGUID());
             if (group->IsLfgWithBuff())
                 player->CastSpell(player, LFG_SPELL_LUCK_OF_THE_DRAW, true);
         }
         else
         {
             player->RemoveAurasDueToSpell(LFG_SPELL_LUCK_OF_THE_DRAW);
             // Xinef: Destroy group if only one player is left
             if (Group* group = player->GetGroup())
                 if (group->GetMembersCount() <= 1u)
                     group->Disband();
         }
     }
References Unit::CastSpell(), Map::GetDifficulty(), Group::GetFirstMember(), Player::GetGroup(), Object::GetGUID(), Map::GetId(), WorldObject::GetMap(), WorldObject::GetName(), Player::GetSession(), Group::IsLfgWithBuff(), lfg::LFG_SPELL_LUCK_OF_THE_DRAW, LOG_DEBUG, Player::m_homebindMapId, Player::m_homebindX, Player::m_homebindY, Player::m_homebindZ, GroupReference::next(), Unit::RemoveAurasDueToSpell(), WorldSession::SendNameQueryOpcode(), sLFGMgr, Player::TeleportTo(), and ObjectGuid::ToString().
The documentation for this class was generated from the following files:
src/server/game/DungeonFinding/LFGScripts.h
src/server/game/DungeonFinding/LFGScripts.cpp