Azerotcore-wotlk: npc_akama_shade::npc_akamaAI Struct Reference
npc_akama_shade::npc_akamaAI Struct Reference
Public Member Functions
npc_akamaAI (Creature *creature)
void Reset () override
void MovementInform (uint32 type, uint32 point) override
void DoAction (int32 param) override
void JustDied (Unit *) override
void EnterCombat (Unit *) override
void JustSummoned (Creature *summon) override
void UpdateAI (uint32 diff) override
void sGossipSelect (Player *player, uint32, uint32 action) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * instance
EventMap events
EventMap events2
SummonList summons
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 281 of file boss_shade_of_akama.cpp.
Constructor & Destructor Documentation
npc_akamaAI()
npc_akama_shade::npc_akamaAI::npc_akamaAI (Creature * creature) inline
Definition at line 283 of file boss_shade_of_akama.cpp.
                                         : ScriptedAI(creature), summons(me)
         {
             instance = creature->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), and instance.
Member Function Documentation
DoAction()
void npc_akama_shade::npc_akamaAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 322 of file boss_shade_of_akama.cpp.
         {
             if (param == ACTION_SHADE_DIED)
                 events2.ScheduleEvent(EVENT_AKAMA_SCENE0, 1000);
         }
References ACTION_SHADE_DIED, EVENT_AKAMA_SCENE0, events2, and EventMap::ScheduleEvent().
EnterCombat()
void npc_akama_shade::npc_akamaAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 334 of file boss_shade_of_akama.cpp.
         {
             events.ScheduleEvent(EVENT_SPELL_CHAIN_LIGHTNING, 2000);
             events.ScheduleEvent(EVENT_SPELL_DESTRUCTIVE_POISON, 5000);
         }
References EVENT_SPELL_CHAIN_LIGHTNING, and EVENT_SPELL_DESTRUCTIVE_POISON.
JustDied()
void npc_akama_shade::npc_akamaAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 328 of file boss_shade_of_akama.cpp.
         {
             if (Creature* shade = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_SHADE_OF_AKAMA)))
                 shade->AI()->DoAction(ACTION_AKAMA_DIED);
         }
References ACTION_AKAMA_DIED, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), instance, ScriptedAI::me, and NPC_SHADE_OF_AKAMA.
JustSummoned()
void npc_akama_shade::npc_akamaAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 340 of file boss_shade_of_akama.cpp.
         {
             float dist = frand(30.0f, 32.0f);
             summon->SetWalk(true);
             summon->GetMotionMaster()->MovePoint(POINT_START, summon->GetPositionX() + dist * cos(summon->GetOrientation()), summon->GetPositionY() + dist * sin(summon->GetOrientation()), summon->GetPositionZ(), false);
             summons.Summon(summon);
         }
References frand(), Unit::GetMotionMaster(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), MotionMaster::MovePoint(), POINT_START, Creature::SetWalk(), SummonList::Summon(), and summons.
MovementInform()
void npc_akama_shade::npc_akamaAI::MovementInform (uint32 type, uint32 point) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 307 of file boss_shade_of_akama.cpp.
         {
             if (type != POINT_MOTION_TYPE || point != POINT_CHANNEL_SOUL)
                 return;
             me->SetFacingTo(0.0f);
             events2.ScheduleEvent(EVENT_AKAMA_SCENE1, 1000);
             events2.ScheduleEvent(EVENT_AKAMA_SCENE2, 16500);
             events2.ScheduleEvent(EVENT_AKAMA_SCENE3, 17500);
             events2.ScheduleEvent(EVENT_AKAMA_SCENE4, 27000);
             events2.ScheduleEvent(EVENT_AKAMA_SCENE5, 37000);
             events2.ScheduleEvent(EVENT_AKAMA_SCENE6, 51000);
             events2.ScheduleEvent(EVENT_AKAMA_SCENE7, 56000);
         }
References EVENT_AKAMA_SCENE1, EVENT_AKAMA_SCENE2, EVENT_AKAMA_SCENE3, EVENT_AKAMA_SCENE4, EVENT_AKAMA_SCENE5, EVENT_AKAMA_SCENE6, EVENT_AKAMA_SCENE7, events2, ScriptedAI::me, POINT_CHANNEL_SOUL, POINT_MOTION_TYPE, EventMap::ScheduleEvent(), and Unit::SetFacingTo().
Reset()
void npc_akama_shade::npc_akamaAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 293 of file boss_shade_of_akama.cpp.
         {
             if (instance->GetBossState(DATA_SHADE_OF_AKAMA) == DONE)
             {
                 me->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
                 return;
             }
             me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
             me->CastSpell(me, SPELL_STEALTH, true);
             events.Reset();
             events2.Reset();
         }
References Unit::CastSpell(), DATA_SHADE_OF_AKAMA, DONE, events2, InstanceScript::GetBossState(), instance, ScriptedAI::me, Object::RemoveFlag(), EventMap::Reset(), Object::SetFlag(), SPELL_STEALTH, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
sGossipSelect()
void npc_akama_shade::npc_akamaAI::sGossipSelect (Player * player, uint32 , uint32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 423 of file boss_shade_of_akama.cpp.
         {
             if (action == 0)
             {
                 CloseGossipMenuFor(player);
                 me->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
                 events2.ScheduleEvent(EVENT_AKAMA_START_ENCOUNTER, 0);
             }
         }
References CloseGossipMenuFor(), EVENT_AKAMA_START_ENCOUNTER, events2, ScriptedAI::me, Object::RemoveFlag(), EventMap::ScheduleEvent(), UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
UpdateAI()
void npc_akama_shade::npc_akamaAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 348 of file boss_shade_of_akama.cpp.
         {
             events2.Update(diff);
             switch (events2.ExecuteEvent())
             {
                 case EVENT_AKAMA_START_ENCOUNTER:
                     me->RemoveAura(SPELL_STEALTH);
                     me->SetWalk(true);
                     me->GetMotionMaster()->MovePoint(POINT_START, 517.4877f, 400.7993f, 112.7837f, false);
                     events2.ScheduleEvent(EVENT_AKAMA_START_CHANNEL, 11000);
                     break;
                 case EVENT_AKAMA_START_CHANNEL:
                     me->CastSpell(me, SPELL_AKAMA_SOUL_CHANNEL, false);
                     if (Creature* shade = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_SHADE_OF_AKAMA)))
                     {
                         shade->AI()->AttackStart(me);
                         shade->GetMotionMaster()->Clear();
                         shade->AI()->DoAction(ACTION_START_ENCOUNTER);
                     }
                     break;
                 case EVENT_AKAMA_SCENE0:
                     me->SetWalk(true);
                     me->GetMotionMaster()->MovePoint(POINT_CHANNEL_SOUL, 467.0f, 400.7993f, 118.537f);
                     break;
                 case EVENT_AKAMA_SCENE1:
                     me->CastSpell(me, SPELL_AKAMA_SOUL_RETRIEVE, true);
                     break;
                 case EVENT_AKAMA_SCENE2:
                     Talk(SAY_BROKEN_FREE_0);
                     break;
                 case EVENT_AKAMA_SCENE3:
                     me->SummonCreatureGroup(SUMMON_GROUP_BROKENS);
                     break;
                 case EVENT_AKAMA_SCENE4:
                     Talk(SAY_BROKEN_FREE_1);
                     break;
                 case EVENT_AKAMA_SCENE5:
                     for (SummonList::const_iterator itr = summons.begin(); itr != summons.end(); ++itr)
                         if (Creature* broken = ObjectAccessor::GetCreature(*me, *itr))
                             broken->SetStandState(UNIT_STAND_STATE_KNEEL);
                     Talk(SAY_BROKEN_FREE_2);
                     break;
                 case EVENT_AKAMA_SCENE6:
                     if (Creature* broken = summons.GetCreatureWithEntry(NPC_ASHTONGUE_BROKEN))
                         broken->AI()->Talk(SAY_BROKEN_S1);
                     break;
                 case EVENT_AKAMA_SCENE7:
                     for (SummonList::const_iterator itr = summons.begin(); itr != summons.end(); ++itr)
                         if (Creature* broken = ObjectAccessor::GetCreature(*me, *itr))
                             broken->AI()->Talk(SAY_BROKEN_S2);
                     break;
             }
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_SPELL_CHAIN_LIGHTNING:
                     me->CastSpell(me->GetVictim(), SPELL_CHAIN_LIGHTNING, false);
                     events.ScheduleEvent(EVENT_SPELL_CHAIN_LIGHTNING, urand(10000, 15000));
                     break;
                 case EVENT_SPELL_DESTRUCTIVE_POISON:
                     me->CastSpell(me, SPELL_DESTRUCTIVE_POISON, false);
                     events.ScheduleEvent(EVENT_SPELL_DESTRUCTIVE_POISON, urand(4000, 5000));
                     break;
             }
             DoMeleeAttackIfReady();
         }
References ACTION_START_ENCOUNTER, SummonList::begin(), Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), SummonList::end(), EVENT_AKAMA_SCENE0, EVENT_AKAMA_SCENE1, EVENT_AKAMA_SCENE2, EVENT_AKAMA_SCENE3, EVENT_AKAMA_SCENE4, EVENT_AKAMA_SCENE5, EVENT_AKAMA_SCENE6, EVENT_AKAMA_SCENE7, EVENT_AKAMA_START_CHANNEL, EVENT_AKAMA_START_ENCOUNTER, EVENT_SPELL_CHAIN_LIGHTNING, EVENT_SPELL_DESTRUCTIVE_POISON, events2, EventMap::ExecuteEvent(), ObjectAccessor::GetCreature(), SummonList::GetCreatureWithEntry(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), Unit::GetVictim(), Unit::HasUnitState(), instance, ScriptedAI::me, MotionMaster::MovePoint(), NPC_ASHTONGUE_BROKEN, NPC_SHADE_OF_AKAMA, POINT_CHANNEL_SOUL, POINT_START, Unit::RemoveAura(), SAY_BROKEN_FREE_0, SAY_BROKEN_FREE_1, SAY_BROKEN_FREE_2, SAY_BROKEN_S1, SAY_BROKEN_S2, EventMap::ScheduleEvent(), Creature::SetWalk(), SPELL_AKAMA_SOUL_CHANNEL, SPELL_AKAMA_SOUL_RETRIEVE, SPELL_CHAIN_LIGHTNING, SPELL_DESTRUCTIVE_POISON, SPELL_STEALTH, SUMMON_GROUP_BROKENS, WorldObject::SummonCreatureGroup(), summons, CreatureAI::Talk(), UNIT_STAND_STATE_KNEEL, UNIT_STATE_CASTING, EventMap::Update(), CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
events
EventMap npc_akama_shade::npc_akamaAI::events
Definition at line 289 of file boss_shade_of_akama.cpp.
events2
EventMap npc_akama_shade::npc_akamaAI::events2
Definition at line 290 of file boss_shade_of_akama.cpp.
Referenced by DoAction(), MovementInform(), Reset(), sGossipSelect(), and UpdateAI().
instance
InstanceScript* npc_akama_shade::npc_akamaAI::instance
Definition at line 288 of file boss_shade_of_akama.cpp.
Referenced by JustDied(), npc_akamaAI(), Reset(), and UpdateAI().
summons
SummonList npc_akama_shade::npc_akamaAI::summons
Definition at line 291 of file boss_shade_of_akama.cpp.
Referenced by JustSummoned(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/BlackTemple/boss_shade_of_akama.cpp