Azerotcore-wotlk: deps/recastnavigation/Detour/Include/DetourNode.h File Reference
DetourNode.h File Reference
#include "DetourNavMesh.h"
Classes
struct dtNode
class dtNodePool
class dtNodeQueue
Typedefs
typedef unsigned short dtNodeIndex
Enumerations
enum dtNodeFlags { DT_NODE_OPEN = 0x01 , DT_NODE_CLOSED = 0x02 , DT_NODE_PARENT_DETACHED = 0x04 }
Variables
static const dtNodeIndex DT_NULL_IDX = (dtNodeIndex)~0
static const int DT_NODE_PARENT_BITS = 24
static const int DT_NODE_STATE_BITS = 2
static const int DT_MAX_STATES_PER_NODE = 1 << DT_NODE_STATE_BITS
Typedef Documentation
dtNodeIndex
typedef unsigned short dtNodeIndex
Definition at line 31 of file DetourNode.h.
Enumeration Type Documentation
dtNodeFlags
enum dtNodeFlags
Enumerator
DT_NODE_OPEN
DT_NODE_CLOSED
DT_NODE_PARENT_DETACHED
Definition at line 24 of file DetourNode.h.
 {
     DT_NODE_OPEN = 0x01,
     DT_NODE_CLOSED = 0x02,
     DT_NODE_PARENT_DETACHED = 0x04, // parent of the node is not adjacent. Found using raycast.
 };
Variable Documentation
DT_MAX_STATES_PER_NODE
const int DT_MAX_STATES_PER_NODE = 1 << DT_NODE_STATE_BITS static
Definition at line 47 of file DetourNode.h.
Referenced by dtNavMeshQuery::isInClosedList().
DT_NODE_PARENT_BITS
const int DT_NODE_PARENT_BITS = 24 static
Definition at line 34 of file DetourNode.h.
Referenced by dtNodePool::dtNodePool(), and dtNavMeshQuery::init().
DT_NODE_STATE_BITS
const int DT_NODE_STATE_BITS = 2 static
Definition at line 35 of file DetourNode.h.
DT_NULL_IDX
const dtNodeIndex DT_NULL_IDX = (dtNodeIndex)~0 static
Definition at line 32 of file DetourNode.h.
Referenced by dtNodePool::dtNodePool(), dtNodePool::findNode(), dtNodePool::findNodes(), dtNodePool::getNode(), and dtNavMeshQuery::init().