Azerotcore-wotlk: ResetEncounterEvent Class Reference
ResetEncounterEvent Class Reference
Public Member Functions
ResetEncounterEvent (Unit *caster, uint32 spellId, ObjectGuid otherTransport)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()
virtual ~BasicEvent ()
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Unit * _caster
uint32 _spellId
ObjectGuid _otherTransport
Detailed Description
Definition at line 507 of file boss_icecrown_gunship_battle.cpp.
Constructor & Destructor Documentation
ResetEncounterEvent()
ResetEncounterEvent::ResetEncounterEvent (Unit * caster, uint32 spellId, ObjectGuid otherTransport) inline
Definition at line 510 of file boss_icecrown_gunship_battle.cpp.
 : _caster(caster), _spellId(spellId), _otherTransport(otherTransport) { }
Member Function Documentation
Execute()
bool ResetEncounterEvent::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
Definition at line 512 of file boss_icecrown_gunship_battle.cpp.
     {
         _caster->CastSpell(_caster, _spellId, true);
         _caster->GetTransport()->ToMotionTransport()->UnloadNonStaticPassengers();
         _caster->GetTransport()->AddObjectToRemoveList();
         if (Transport* transport = ObjectAccessor::GetTransport(*_caster, _otherTransport))
         {
             transport->ToMotionTransport()->UnloadNonStaticPassengers();
             transport->AddObjectToRemoveList();
         }
         return true;
     }
References _caster, _otherTransport, _spellId, WorldObject::AddObjectToRemoveList(), Unit::CastSpell(), WorldObject::GetTransport(), ObjectAccessor::GetTransport(), GameObject::ToMotionTransport(), and MotionTransport::UnloadNonStaticPassengers().
Member Data Documentation
_caster
Unit* ResetEncounterEvent::_caster private
Definition at line 528 of file boss_icecrown_gunship_battle.cpp.
Referenced by Execute().
_otherTransport
ObjectGuid ResetEncounterEvent::_otherTransport private
Definition at line 530 of file boss_icecrown_gunship_battle.cpp.
Referenced by Execute().
_spellId
uint32 ResetEncounterEvent::_spellId private
Definition at line 529 of file boss_icecrown_gunship_battle.cpp.
Referenced by Execute().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_icecrown_gunship_battle.cpp