Azerotcore-wotlk: boss_razorscale::boss_razorscaleAI Struct Reference
boss_razorscale::boss_razorscaleAI Struct Reference
Public Member Functions
boss_razorscaleAI (Creature *pCreature)
void InitializeAI () override
void Reset () override
void AttackStart (Unit *who) override
void EnterCombat (Unit *) override
void JustDied (Unit *) override
void SpellHit (Unit *caster, const SpellInfo *spell) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void MovementInform (uint32 type, uint32 id) override
void UpdateAI (uint32 diff) override
void MoveInLineOfSight (Unit *) override
void JustReachedHome () override
void JustSummoned (Creature *s) override
uint32 GetData (uint32 id) const override
void KilledUnit (Unit *victim) override
void EnterEvadeMode () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void DoAction (int32)
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
EventMap events
SummonList summons
ObjectGuid ExpeditionEngineerGUIDs [3]
ObjectGuid CommanderGUID
float cords [4][2]
bool bGroundPhase
bool startPath
uint8 flyTimes
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 131 of file boss_razorscale.cpp.
Constructor & Destructor Documentation
boss_razorscaleAI()
boss_razorscale::boss_razorscaleAI::boss_razorscaleAI (Creature * pCreature) inline
Definition at line 133 of file boss_razorscale.cpp.
                                                : ScriptedAI(pCreature), summons(me)
         {
             pInstance = me->GetInstanceScript();
             startPath = true;
         }
References WorldObject::GetInstanceScript(), ScriptedAI::me, pInstance, and startPath.
Member Function Documentation
AttackStart()
void boss_razorscale::boss_razorscaleAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 172 of file boss_razorscale.cpp.
         {
             if (who && me->Attack(who, true) && bGroundPhase)
                 me->GetMotionMaster()->MoveChase(who);
         }
References Unit::Attack(), bGroundPhase, Unit::GetMotionMaster(), ScriptedAI::me, and MotionMaster::MoveChase().
Referenced by UpdateAI().
DamageTaken()
void boss_razorscale::boss_razorscaleAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 278 of file boss_razorscale.cpp.
         {
             if (me->GetPositionZ() > 440.0f) // protection, razorscale is attackable (so harpoons can hit him, etc.), but should not receive dmg while in air
                 damage = 0;
             else if (!bGroundPhase && ((me->GetHealth() * 100) / me->GetMaxHealth() < 50) && me->HasAura(62794)) // already below 50%, but still in chains and stunned
                 events.RescheduleEvent(EVENT_WARN_DEEP_BREATH, 0);
         }
References bGroundPhase, EVENT_WARN_DEEP_BREATH, Unit::GetHealth(), Unit::GetMaxHealth(), Position::GetPositionZ(), Unit::HasAura(), and ScriptedAI::me.
EnterCombat()
void boss_razorscale::boss_razorscaleAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 178 of file boss_razorscale.cpp.
         {
             me->SetInCombatWithZone();
             events.Reset();
             events.ScheduleEvent(EVENT_COMMANDER_SAY_AGGRO, 5000);
             events.ScheduleEvent(EVENT_EE_SAY_MOVE_OUT, 10000);
             events.ScheduleEvent(EVENT_ENRAGE, 600000);
             events.ScheduleEvent(EVENT_SPELL_FIREBALL, 6000);
             events.ScheduleEvent(EVENT_SPELL_DEVOURING_FLAME, 13000);
             events.ScheduleEvent(EVENT_SUMMON_MOLE_MACHINES, 11000);
             std::list<Creature*> eeList;
             me->GetCreaturesWithEntryInRange(eeList, 300.0f, NPC_EXPEDITION_ENGINEER);
             uint8 i = 0;
             for( std::list<Creature*>::iterator itr = eeList.begin(); itr != eeList.end(); ++itr )
             {
                 if( i > 2 )
                     break;
                 ExpeditionEngineerGUIDs[i] = (*itr)->GetGUID();
                 if (!i)
                     (*itr)->Yell(TEXT_EE_AGGRO, LANG_UNIVERSAL);
                 ++i;
             }
             if (Creature* c = me->FindNearestCreature(NPC_EXPEDITION_COMMANDER, 300.0f, true))
                 CommanderGUID = c->GetGUID();
             if( pInstance )
                 pInstance->SetData(TYPE_RAZORSCALE, IN_PROGRESS);
         }
References mpq::c, CommanderGUID, EVENT_COMMANDER_SAY_AGGRO, EVENT_EE_SAY_MOVE_OUT, EVENT_ENRAGE, EVENT_SPELL_DEVOURING_FLAME, EVENT_SPELL_FIREBALL, EVENT_SUMMON_MOLE_MACHINES, ExpeditionEngineerGUIDs, WorldObject::FindNearestCreature(), WorldObject::GetCreaturesWithEntryInRange(), IN_PROGRESS, LANG_UNIVERSAL, ScriptedAI::me, NPC_EXPEDITION_COMMANDER, NPC_EXPEDITION_ENGINEER, pInstance, ZoneScript::SetData(), Creature::SetInCombatWithZone(), TEXT_EE_AGGRO, and TYPE_RAZORSCALE.
EnterEvadeMode()
void boss_razorscale::boss_razorscaleAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 591 of file boss_razorscale.cpp.
         {
             me->SetDisableGravity(true);
             me->SetControlled(false, UNIT_STATE_ROOT);
             me->DisableRotate(false);
             ScriptedAI::EnterEvadeMode();
         }
References Unit::DisableRotate(), CreatureAI::EnterEvadeMode(), ScriptedAI::me, Unit::SetControlled(), Creature::SetDisableGravity(), and UNIT_STATE_ROOT.
GetData()
uint32 boss_razorscale::boss_razorscaleAI::GetData (uint32 id) const inline override virtual
Reimplemented from UnitAI.
Definition at line 577 of file boss_razorscale.cpp.
         {
             if (id == 1)
                 return (flyTimes <= 1 ? 1 : 0);
             return 0;
         }
References flyTimes.
InitializeAI()
void boss_razorscale::boss_razorscaleAI::InitializeAI () inline override virtual
Reimplemented from UnitAI.
Definition at line 149 of file boss_razorscale.cpp.
         {
             me->SetDisableGravity(true);
             me->setActive(true);
             Reset();
         }
References ScriptedAI::me, Reset(), WorldObject::setActive(), and Creature::SetDisableGravity().
JustDied()
void boss_razorscale::boss_razorscaleAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 208 of file boss_razorscale.cpp.
         {
             summons.DespawnAll();
             if( pInstance )
                 pInstance->SetData(TYPE_RAZORSCALE, DONE);
         }
References SummonList::DespawnAll(), DONE, pInstance, ZoneScript::SetData(), summons, and TYPE_RAZORSCALE.
JustReachedHome()
void boss_razorscale::boss_razorscaleAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 567 of file boss_razorscale.cpp.
         {
             startPath = true;
         }
References startPath.
JustSummoned()
void boss_razorscale::boss_razorscaleAI::JustSummoned (Creature * s) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 572 of file boss_razorscale.cpp.
         {
             summons.Summon(s);
         }
References SummonList::Summon(), and summons.
KilledUnit()
void boss_razorscale::boss_razorscaleAI::KilledUnit (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 584 of file boss_razorscale.cpp.
         {
             if (victim && victim->GetEntry() == NPC_DARK_RUNE_GUARDIAN)
                 if (pInstance)
                     pInstance->DoUpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, NPC_DARK_RUNE_GUARDIAN, 1, me);
         }
References ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, InstanceScript::DoUpdateAchievementCriteria(), Object::GetEntry(), ScriptedAI::me, NPC_DARK_RUNE_GUARDIAN, and pInstance.
MoveInLineOfSight()
void boss_razorscale::boss_razorscaleAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 565 of file boss_razorscale.cpp.
 {}
MovementInform()
void boss_razorscale::boss_razorscaleAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 286 of file boss_razorscale.cpp.
         {
             if (type == POINT_MOTION_TYPE && id == POINT_RAZORSCALE_INIT)
             {
                 me->SetFacingTo(1.6f);
                 return;
             }
             else if (type == ESCORT_MOTION_TYPE && me->movespline->Finalized() && !me->IsInCombat())
             {
                 startPath = true;
                 return;
             }
             if (type != EFFECT_MOTION_TYPE)
                 return;
             if (id == 0) // landed
             {
                 me->SetControlled(true, UNIT_STATE_ROOT);
                 me->DisableRotate(true);
                 me->SetOrientation((float)(M_PI + 0.01) / 2);
                 me->SetFacingTo(M_PI / 2);
                 me->SetDisableGravity(false);
                 me->CastSpell(me, 62794, true);
                 events.ScheduleEvent(EVENT_WARN_DEEP_BREATH, 30000);
             }
             else if (id == 1) // flied up
             {
                 events.ScheduleEvent(EVENT_SPELL_FIREBALL, 2000);
                 events.ScheduleEvent(EVENT_SPELL_DEVOURING_FLAME, 4000);
                 events.ScheduleEvent(EVENT_SUMMON_MOLE_MACHINES, 5000);
             }
         }
References Unit::CastSpell(), Unit::DisableRotate(), EFFECT_MOTION_TYPE, ESCORT_MOTION_TYPE, EVENT_SPELL_DEVOURING_FLAME, EVENT_SPELL_FIREBALL, EVENT_SUMMON_MOLE_MACHINES, EVENT_WARN_DEEP_BREATH, Movement::MoveSpline::Finalized(), Unit::IsInCombat(), M_PI, ScriptedAI::me, Unit::movespline, POINT_MOTION_TYPE, POINT_RAZORSCALE_INIT, Unit::SetControlled(), Creature::SetDisableGravity(), Unit::SetFacingTo(), Position::SetOrientation(), startPath, and UNIT_STATE_ROOT.
Reset()
void boss_razorscale::boss_razorscaleAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 156 of file boss_razorscale.cpp.
         {
             events.Reset();
             summons.DespawnAll();
             for (uint8 i = 0; i < 3; ++i)
                 ExpeditionEngineerGUIDs[i].Clear();
             CommanderGUID.Clear();
             bGroundPhase = false;
             flyTimes = 0;
             if( pInstance )
                 pInstance->SetData(TYPE_RAZORSCALE, NOT_STARTED);
         }
References bGroundPhase, ObjectGuid::Clear(), CommanderGUID, SummonList::DespawnAll(), ExpeditionEngineerGUIDs, flyTimes, NOT_STARTED, pInstance, ZoneScript::SetData(), summons, and TYPE_RAZORSCALE.
Referenced by InitializeAI().
SpellHit()
void boss_razorscale::boss_razorscaleAI::SpellHit (Unit * caster, const SpellInfo * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 216 of file boss_razorscale.cpp.
         {
             if (!caster || !pInstance)
                 return;
             switch (spell->Id)
             {
                 case SPELL_LAUNCH_CHAIN:
                     {
                         uint32 spellId = SPELL_CHAIN_4;
                         if (caster->GetGUID() == pInstance->GetGuidData(DATA_HARPOON_FIRE_STATE_1))
{
                             spellId = SPELL_CHAIN_1;
                         }
                         else if (caster->GetGUID() == pInstance->GetGuidData(DATA_HARPOON_FIRE_STATE_2))
{
                             spellId = SPELL_CHAIN_2;
                         }
                         else if (caster->GetGUID() == pInstance->GetGuidData(DATA_HARPOON_FIRE_STATE_3))
{
                             spellId = SPELL_CHAIN_3;
                         }
                         caster->CastSpell(me, spellId, true);
                     }
                     break;
                 case SPELL_CHAIN_1:
                 case SPELL_CHAIN_2:
                 case SPELL_CHAIN_3:
                 case SPELL_CHAIN_4:
                     {
                         uint8 count = 0;
                         if( me->HasAura(SPELL_CHAIN_1) )
                             count++;
                         if( me->HasAura(SPELL_CHAIN_3) )
                             count++;
                         if (RAID_MODE(0, 1))
{
                             if( me->HasAura(SPELL_CHAIN_2) )
                                 count++;
                             if( me->HasAura(SPELL_CHAIN_4) )
                                 count++;
                         }
                         if( count >= REQ_CHAIN_COUNT )
{
                             if (Creature* commander = ObjectAccessor::GetCreature(*me, CommanderGUID))
                                 commander->AI()->Talk(SAY_COMMANDER_GROUND);
                             me->InterruptNonMeleeSpells(true);
                             events.CancelEvent(EVENT_SPELL_FIREBALL);
                             events.CancelEvent(EVENT_SPELL_DEVOURING_FLAME);
                             events.CancelEvent(EVENT_SUMMON_MOLE_MACHINES);
                             me->SetTarget();
                             me->SendMeleeAttackStop(me->GetVictim());
                             me->GetMotionMaster()->MoveLand(0, CORDS_GROUND, 25.0f);
                         }
                     }
                     break;
             }
         }
References Unit::CastSpell(), CommanderGUID, CORDS_GROUND, count(), DATA_HARPOON_FIRE_STATE_1, DATA_HARPOON_FIRE_STATE_2, DATA_HARPOON_FIRE_STATE_3, EVENT_SPELL_DEVOURING_FLAME, EVENT_SPELL_FIREBALL, EVENT_SUMMON_MOLE_MACHINES, ObjectAccessor::GetCreature(), Object::GetGUID(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), Unit::GetVictim(), Unit::HasAura(), SpellInfo::Id, Unit::InterruptNonMeleeSpells(), ScriptedAI::me, MotionMaster::MoveLand(), pInstance, ScriptedAI::RAID_MODE(), REQ_CHAIN_COUNT, SAY_COMMANDER_GROUND, Unit::SendMeleeAttackStop(), Creature::SetTarget(), SPELL_CHAIN_1, SPELL_CHAIN_2, SPELL_CHAIN_3, SPELL_CHAIN_4, and SPELL_LAUNCH_CHAIN.
UpdateAI()
void boss_razorscale::boss_razorscaleAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 319 of file boss_razorscale.cpp.
         {
             if (startPath)
             {
                 me->StopMoving();
                 startPath = false;
                 if (WaypointPath const* i_path = sWaypointMgr->GetPath(me->GetWaypointPath()))
                 {
                     Movement::PointsArray pathPoints;
                     pathPoints.push_back(G3D::Vector3(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()));
                     for (uint8 i = 0; i < i_path->size(); ++i)
                     {
                         WaypointData const* node = i_path->at(i);
                         pathPoints.push_back(G3D::Vector3(node->x, node->y, node->z));
                     }
                     me->GetMotionMaster()->MoveSplinePath(&pathPoints);
                 }
             }
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case 0:
                     break;
                 case EVENT_ENRAGE:
                     me->CastSpell(me, SPELL_BERSERK, true);
                     events.RepeatEvent(600000);
                     break;
                 case EVENT_COMMANDER_SAY_AGGRO:
                     if (Creature* commander = ObjectAccessor::GetCreature(*me, CommanderGUID))
                         commander->AI()->Talk(SAY_COMMANDER_AGGRO);
                     break;
                 case EVENT_EE_SAY_MOVE_OUT:
                     for (uint8 i = 0; i < 3; ++i)
                         if (Creature* c = ObjectAccessor::GetCreature(*me, ExpeditionEngineerGUIDs[i]))
{
                             if (!i)
                                 c->Yell(TEXT_EE_MOVE_OUT, LANG_UNIVERSAL);
                             c->AI()->SetData(1, 0); // start repairing
                         }
                     break;
                 case EVENT_SPELL_FIREBALL:
                     if( Unit* pTarget = SelectTarget(SELECT_TARGET_RANDOM, 0, 200.0f, true) )
                         me->CastSpell(pTarget, SPELL_FIREBALL, false);
                     events.RepeatEvent(4000);
                     break;
                 case EVENT_SPELL_DEVOURING_FLAME:
                     if( Unit* pTarget = SelectTarget(SELECT_TARGET_RANDOM, 0, 200.0f, true) )
                         me->CastSpell(pTarget, SPELL_DEVOURINGFLAME, false);
                     events.RepeatEvent(13000);
                     break;
                 case EVENT_SUMMON_MOLE_MACHINES:
                     {
                         memset(cords, '\0', sizeof(cords));
                         uint8 num = RAID_MODE( urand(2, 3), urand(2, 4) );
                         for( int i = 0; i < num; ++i )
{
                             // X: (550, 625) Y: (-185, -230)
                             cords[i][0] = urand(550, 625);
                             cords[i][1] = -230 + rand() % 45;
                             if( GameObject* drill = me->SummonGameObject(GO_DRILL, cords[i][0], cords[i][1], 391.1f, M_PI / 4, 0.0f, 0.0f, 0.0f, 0.0f, 8) )
{
                                 //drill->SetGoAnimProgress(0);
                                 //drill->SetLootState(GO_READY);
                                 //drill->UseDoorOrButton(8);
                                 //drill->SetGoState(GO_STATE_READY);
                                 drill->SetGoState(GO_STATE_ACTIVE);
                                 drill->SetGoAnimProgress(0);
                             }
                         }
                         events.RepeatEvent(45000);
                         events.RescheduleEvent(EVENT_SUMMON_ADDS, 4000);
                     }
                     break;
                 case EVENT_SUMMON_ADDS:
                     for( int i = 0; i < 4; ++i )
                     {
                         if( !cords[i][0] )
                             break;
                         uint8 opt;
                         uint8 r = urand(1, 100);
                         if( r <= 30 ) opt = 1;
                         else if( r <= 65 ) opt = 2;
                         else opt = 3;
                         for( int j = 0; j < 4; ++j )
{
                             float x = cords[i][0] + 4.0f * cos(j * M_PI / 2);
                             float y = cords[i][1] + 4.0f * sin(j * M_PI / 2);
                             uint32 npc_entry = 0;
                             switch( opt )
{
                                 case 1:
                                     if( j == 1 ) npc_entry = NPC_DARK_RUNE_SENTINEL;
                                     break;
                                 case 2:
                                     switch( j )
{
                                         case 1:
                                             npc_entry = NPC_DARK_RUNE_WATCHER;
                                             break;
                                         case 2:
                                             npc_entry = NPC_DARK_RUNE_GUARDIAN;
                                             break;
                                     }
                                     break;
                                 default: // case 3:
                                     switch( j )
{
                                         case 1:
                                             npc_entry = NPC_DARK_RUNE_WATCHER;
                                             break;
                                         case 2:
                                             npc_entry = NPC_DARK_RUNE_GUARDIAN;
                                             break;
                                         case 3:
                                             npc_entry = NPC_DARK_RUNE_GUARDIAN;
                                             break;
                                     }
                                     break;
                             }
                             if( npc_entry )
                                 if (Creature* c = me->SummonCreature(npc_entry, x, y, 391.1f, j * M_PI / 2, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 5000))
                                     DoZoneInCombat(c);
                         }
                     }
                     break;
                 case EVENT_WARN_DEEP_BREATH:
                     me->TextEmote(TEXT_DEEP_BREATH, nullptr, true);
                     me->RemoveAura(62794);
                     events.ScheduleEvent(EVENT_PHASE2_FLAME_BREATH, 2500);
                     break;
                 case EVENT_PHASE2_FLAME_BREATH:
                     me->CastSpell(me, S_FLAMEBREATH, true);
                     events.ScheduleEvent(EVENT_FLY_UP, 2000);
                     break;
                 case EVENT_FLY_UP:
                     me->SetInCombatWithZone(); // just in case
                     if (pInstance)
                         for( int i = 0; i < 4; ++i )
                             if( ObjectGuid guid = pInstance->GetGuidData(DATA_HARPOON_FIRE_STATE_1 + i) )
                                 if( Creature* hfs = ObjectAccessor::GetCreature(*me, guid) )
{
                                     me->SummonCreature(34188, hfs->GetPositionX(), hfs->GetPositionY(), hfs->GetPositionZ(), 0, TEMPSUMMON_TIMED_DESPAWN, 22000);
                                     hfs->AI()->SetData(1, 0);
                                 }
                     me->RemoveAura(SPELL_LAUNCH_CHAIN);
                     me->RemoveAura(SPELL_CHAIN_1);
                     me->RemoveAura(SPELL_CHAIN_3);
                     if (RAID_MODE(0, 1))
                     {
                         me->RemoveAura(SPELL_CHAIN_2);
                         me->RemoveAura(SPELL_CHAIN_4);
                     }
                     me->CastSpell(me, SPELL_WINGBUFFET, true);
                     if( (me->GetHealth() * 100) / me->GetMaxHealth() < 50 ) // start phase 3
                     {
                         me->SetControlled(false, UNIT_STATE_ROOT);
                         me->DisableRotate(false);
                         DoResetThreat();
                         Unit* target = SelectTarget(SELECT_TARGET_NEAREST, 0, 0.0, true);
                         if (!target)
                             target = me->SelectNearestPlayer(200.0f);
                         if (target)
{
                             AttackStart(target);
                             me->GetMotionMaster()->MoveChase(target);
                         }
                         bGroundPhase = true;
                         events.CancelEvent(EVENT_SPELL_FIREBALL);
                         events.CancelEvent(EVENT_SPELL_DEVOURING_FLAME);
                         events.CancelEvent(EVENT_SUMMON_MOLE_MACHINES);
                         events.ScheduleEvent(EVENT_SPELL_FLAME_BREATH, 20000);
                         events.ScheduleEvent(EVENT_SPELL_DEVOURING_FLAME_GROUND, 5000);
                         events.ScheduleEvent(EVENT_SPELL_FUSE_ARMOR, 10000);
                         events.ScheduleEvent(EVENT_SPELL_FLAME_BUFFET, 3000);
                         break;
                     }
                     else
                     {
                         ++flyTimes;
                         me->SetControlled(false, UNIT_STATE_ROOT);
                         me->DisableRotate(false);
                         me->SendMeleeAttackStop(me->GetVictim());
                         me->GetMotionMaster()->MoveIdle();
                         me->StopMoving();
                         me->SetDisableGravity(true);
                         me->GetMotionMaster()->MoveTakeoff(1, CORDS_AIR, 25.0f);
                         events.ScheduleEvent(EVENT_RESUME_FIXING, 22000);
                     }
                     break;
                 case EVENT_RESUME_FIXING:
                     for (uint8 i = 0; i < 3; ++i)
                         if (Creature* c = ObjectAccessor::GetCreature(*me, ExpeditionEngineerGUIDs[i]))
{
                             if (!i)
                                 c->Yell(TEXT_EE_FIRES_OUT, LANG_UNIVERSAL);
                             c->AI()->SetData(1, 0); // start repairing
                         }
                     break;
                 case EVENT_SPELL_FLAME_BREATH:
                     me->CastSpell(me->GetVictim(), S_FLAMEBREATH, false);
                     events.RepeatEvent(20000);
                     break;
                 case EVENT_SPELL_DEVOURING_FLAME_GROUND:
                     me->CastSpell(me->GetVictim(), SPELL_DEVOURINGFLAME, false);
                     events.RepeatEvent(13000);
                     break;
                 case EVENT_SPELL_FUSE_ARMOR:
                     if (Unit* victim = me->GetVictim())
                         if (me->IsWithinMeleeRange(victim))
{
                             me->CastSpell(victim, SPELL_FUSEARMOR, false);
                             if (Aura* aur = victim->GetAura(SPELL_FUSEARMOR))
                                 if (aur->GetStackAmount() == 5)
                                     victim->CastSpell(victim, 64774, true);
                             events.RepeatEvent(10000);
                             break;
                         }
                     events.RepeatEvent(2000);
                     break;
                 case EVENT_SPELL_FLAME_BUFFET:
                     me->CastSpell(me->GetVictim(), S_FLAMEBUFFET, false);
                     events.RepeatEvent(7000);
                     break;
             }
             if (bGroundPhase)
                 DoMeleeAttackIfReady();
         }
References Creature::AI(), AttackStart(), bGroundPhase, mpq::c, Unit::CastSpell(), CommanderGUID, cords, CORDS_AIR, DATA_HARPOON_FIRE_STATE_1, diff(), Unit::DisableRotate(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DoResetThreat(), CreatureAI::DoZoneInCombat(), EVENT_COMMANDER_SAY_AGGRO, EVENT_EE_SAY_MOVE_OUT, EVENT_ENRAGE, EVENT_FLY_UP, EVENT_PHASE2_FLAME_BREATH, EVENT_RESUME_FIXING, EVENT_SPELL_DEVOURING_FLAME, EVENT_SPELL_DEVOURING_FLAME_GROUND, EVENT_SPELL_FIREBALL, EVENT_SPELL_FLAME_BREATH, EVENT_SPELL_FLAME_BUFFET, EVENT_SPELL_FUSE_ARMOR, EVENT_SUMMON_ADDS, EVENT_SUMMON_MOLE_MACHINES, EVENT_WARN_DEEP_BREATH, ExpeditionEngineerGUIDs, flyTimes, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Unit::GetHealth(), Unit::GetMaxHealth(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetVictim(), Creature::GetWaypointPath(), GO_DRILL, GO_STATE_ACTIVE, Unit::HasUnitState(), Unit::IsWithinMeleeRange(), LANG_UNIVERSAL, M_PI, ScriptedAI::me, memset, MotionMaster::MoveChase(), MotionMaster::MoveIdle(), MotionMaster::MoveSplinePath(), MotionMaster::MoveTakeoff(), NPC_DARK_RUNE_GUARDIAN, NPC_DARK_RUNE_SENTINEL, NPC_DARK_RUNE_WATCHER, pInstance, ScriptedAI::RAID_MODE(), Unit::RemoveAura(), S_FLAMEBREATH, S_FLAMEBUFFET, SAY_COMMANDER_AGGRO, SELECT_TARGET_NEAREST, SELECT_TARGET_RANDOM, WorldObject::SelectNearestPlayer(), UnitAI::SelectTarget(), Unit::SendMeleeAttackStop(), Unit::SetControlled(), UnitAI::SetData(), Creature::SetDisableGravity(), Creature::SetInCombatWithZone(), SPELL_BERSERK, SPELL_CHAIN_1, SPELL_CHAIN_2, SPELL_CHAIN_3, SPELL_CHAIN_4, SPELL_DEVOURINGFLAME, SPELL_FIREBALL, SPELL_FUSEARMOR, SPELL_LAUNCH_CHAIN, SPELL_WINGBUFFET, startPath, Unit::StopMoving(), WorldObject::SummonCreature(), WorldObject::SummonGameObject(), sWaypointMgr, TEMPSUMMON_CORPSE_TIMED_DESPAWN, TEMPSUMMON_TIMED_DESPAWN, TEXT_DEEP_BREATH, TEXT_EE_FIRES_OUT, TEXT_EE_MOVE_OUT, Unit::TextEmote(), UNIT_STATE_CASTING, UNIT_STATE_ROOT, CreatureAI::UpdateVictim(), urand(), G3D::x, WaypointData::x, G3D::y, WaypointData::y, and WaypointData::z.
Member Data Documentation
bGroundPhase
bool boss_razorscale::boss_razorscaleAI::bGroundPhase
Definition at line 145 of file boss_razorscale.cpp.
Referenced by AttackStart(), DamageTaken(), Reset(), and UpdateAI().
CommanderGUID
ObjectGuid boss_razorscale::boss_razorscaleAI::CommanderGUID
Definition at line 143 of file boss_razorscale.cpp.
Referenced by EnterCombat(), Reset(), SpellHit(), and UpdateAI().
cords
float boss_razorscale::boss_razorscaleAI::cords[4][2]
Definition at line 144 of file boss_razorscale.cpp.
Referenced by UpdateAI().
events
EventMap boss_razorscale::boss_razorscaleAI::events
Definition at line 140 of file boss_razorscale.cpp.
ExpeditionEngineerGUIDs
ObjectGuid boss_razorscale::boss_razorscaleAI::ExpeditionEngineerGUIDs[3]
Definition at line 142 of file boss_razorscale.cpp.
Referenced by EnterCombat(), Reset(), and UpdateAI().
flyTimes
uint8 boss_razorscale::boss_razorscaleAI::flyTimes
Definition at line 147 of file boss_razorscale.cpp.
Referenced by GetData(), Reset(), and UpdateAI().
pInstance
InstanceScript* boss_razorscale::boss_razorscaleAI::pInstance
Definition at line 139 of file boss_razorscale.cpp.
Referenced by boss_razorscaleAI(), EnterCombat(), JustDied(), KilledUnit(), Reset(), SpellHit(), and UpdateAI().
startPath
bool boss_razorscale::boss_razorscaleAI::startPath
Definition at line 146 of file boss_razorscale.cpp.
Referenced by boss_razorscaleAI(), JustReachedHome(), MovementInform(), and UpdateAI().
summons
SummonList boss_razorscale::boss_razorscaleAI::summons
Definition at line 141 of file boss_razorscale.cpp.
Referenced by JustDied(), JustSummoned(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_razorscale.cpp