Azerotcore-wotlk: Acore::GameObjectFocusCheck Class Reference
Acore::GameObjectFocusCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
GameObjectFocusCheck (Unit const *unit, uint32 focusId)
bool operator() (GameObject *go) const
Private Attributes
Unit const * i_unit
uint32 i_focusId
Detailed Description
Definition at line 622 of file GridNotifiers.h.
Constructor & Destructor Documentation
GameObjectFocusCheck()
Acore::GameObjectFocusCheck::GameObjectFocusCheck (Unit const * unit, uint32 focusId) inline
Definition at line 625 of file GridNotifiers.h.
 : i_unit(unit), i_focusId(focusId) {}
Member Function Documentation
operator()()
bool Acore::GameObjectFocusCheck::operator() (GameObject * go) const inline
Definition at line 626 of file GridNotifiers.h.
         {
             if (go->GetGOInfo()->type != GAMEOBJECT_TYPE_SPELL_FOCUS)
                 return false;
             if (!go->isSpawned()) // xinef: dont allow to count deactivated objects
                 return false;
             if (go->GetGOInfo()->spellFocus.focusId != i_focusId)
                 return false;
             float dist = (float)((go->GetGOInfo()->spellFocus.dist) / 2);
             return go->IsWithinDistInMap(i_unit, dist);
         }
References GAMEOBJECT_TYPE_SPELL_FOCUS, GameObject::GetGOInfo(), i_focusId, i_unit, GameObject::isSpawned(), GameObject::IsWithinDistInMap(), GameObjectTemplate::spellFocus, and GameObjectTemplate::type.
Member Data Documentation
i_focusId
uint32 Acore::GameObjectFocusCheck::i_focusId private
Definition at line 643 of file GridNotifiers.h.
Referenced by operator()().
i_unit
Unit const* Acore::GameObjectFocusCheck::i_unit private
Definition at line 642 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/game/Grids/Notifiers/GridNotifiers.h