Azerotcore-wotlk: Acore::Impl::CryptoGenericsImpl Struct Reference
Acore::Impl::CryptoGenericsImpl Struct Reference
#include <CryptoGenerics.h>
Static Public Member Functions
template<typename Cipher >
static Cipher::IV GenerateRandomIV ()
template<typename Container >
static void AppendToBack (std::vector< uint8 > &data, Container const &tail)
template<typename Container >
static void SplitFromBack (std::vector< uint8 > &data, Container &tail)
Detailed Description
Definition at line 30 of file CryptoGenerics.h.
Member Function Documentation
AppendToBack()
template<typename Container > static void Acore::Impl::CryptoGenericsImpl::AppendToBack (std::vector< uint8 > & data, Container const & tail) inline static
Definition at line 41 of file CryptoGenerics.h.
         {
             data.insert(data.end(), std::begin(tail), std::end(tail));
         }
Referenced by Acore::Crypto::AEEncryptWithRandomIV().
GenerateRandomIV()
template<typename Cipher > static Cipher::IV Acore::Impl::CryptoGenericsImpl::GenerateRandomIV () inline static
Definition at line 33 of file CryptoGenerics.h.
         {
             typename Cipher::IV iv;
             Acore::Crypto::GetRandomBytes(iv);
             return iv;
         }
References Acore::Crypto::GetRandomBytes().
SplitFromBack()
template<typename Container > static void Acore::Impl::CryptoGenericsImpl::SplitFromBack (std::vector< uint8 > & data, Container & tail) inline static
Definition at line 47 of file CryptoGenerics.h.
         {
             ASSERT(data.size() >= std::size(tail));
             for (size_t i = 1, N = std::size(tail); i <= N; ++i)
             {
                 tail[N - i] = data.back();
                 data.pop_back();
             }
         }
References ASSERT.
Referenced by Acore::Crypto::AEDecrypt().
The documentation for this struct was generated from the following file:
src/common/Cryptography/CryptoGenerics.h