Azerotcore-wotlk: deps/mysqllite/mysys/my_copy.c File Reference
my_copy.c File Reference
#include "mysys_priv.h"
#include <my_dir.h>
#include <m_string.h>
#include "mysys_err.h"
#include <time.h>
Classes
struct utimbuf
Functions
int my_copy (const char *from, const char *to, myf MyFlags)
Function Documentation
my_copy()
int my_copy (const char * from, const char * to, myf MyFlags)
Definition at line 52 of file my_copy.c.
 {
   size_t Count;
   my_bool new_file_stat= 0; /* 1 if we could stat "to" */
   int create_flag;
   File from_file,to_file;
   uchar buff[IO_SIZE];
   MY_STAT stat_buff,new_stat_buff;
   DBUG_ENTER("my_copy");
   DBUG_PRINT("my",("from %s to %s MyFlags %d", from, to, MyFlags));
   from_file=to_file= -1;
   DBUG_ASSERT(!(MyFlags & (MY_FNABP | MY_NABP))); /* for my_read/my_write */
   if (MyFlags & MY_HOLD_ORIGINAL_MODES)     /* Copy stat if possible */
     new_file_stat= test(my_stat((char*) to, &new_stat_buff, MYF(0)));
   if ((from_file=my_open(from,O_RDONLY | O_SHARE,MyFlags)) >= 0)
   {
     if (!my_stat(from, &stat_buff, MyFlags))
     {
       my_errno=errno;
       goto err;
     }
     if (MyFlags & MY_HOLD_ORIGINAL_MODES && new_file_stat)
       stat_buff=new_stat_buff;
     create_flag= (MyFlags & MY_DONT_OVERWRITE_FILE) ? O_EXCL : O_TRUNC;
     if ((to_file=  my_create(to,(int) stat_buff.st_mode,
                  O_WRONLY | create_flag | O_BINARY | O_SHARE,
                  MyFlags)) < 0)
       goto err;
     while ((Count=my_read(from_file, buff, sizeof(buff), MyFlags)) != 0)
     {
     if (Count == (uint) -1 ||
         my_write(to_file,buff,Count,MYF(MyFlags | MY_NABP)))
     goto err;
     }
     /* sync the destination file */
     if (MyFlags & MY_SYNC)
     {
       if (my_sync(to_file, MyFlags))
         goto err;
     }
     if (my_close(from_file,MyFlags) | my_close(to_file,MyFlags))
       DBUG_RETURN(-1);              /* Error on close */
     /* Copy modes if possible */
     if (MyFlags & MY_HOLD_ORIGINAL_MODES && !new_file_stat)
     DBUG_RETURN(0);         /* File copyed but not stat */
     /* Copy modes */
     if (chmod(to, stat_buff.st_mode & 07777))
     {
       my_errno= errno;
       if (MyFlags & (MY_FAE+MY_WME))
         my_error(EE_CHANGE_PERMISSIONS, MYF(ME_BELL+ME_WAITTANG), from, errno);
       goto err;
     }
 #if !defined(__WIN__)
     /* Copy ownership */
     if (chown(to, stat_buff.st_uid, stat_buff.st_gid))
     {
       my_errno= errno;
       if (MyFlags & (MY_FAE+MY_WME))
         my_error(EE_CHANGE_OWNERSHIP, MYF(ME_BELL+ME_WAITTANG), from, errno);
       goto err;
     }
 #endif
     if (MyFlags & MY_COPYTIME)
     {
       struct utimbuf timep;
       timep.actime  = stat_buff.st_atime;
       timep.modtime = stat_buff.st_mtime;
       (void) utime((char*) to, &timep); /* last accessed and modified times */
     }
     DBUG_RETURN(0);
   }
 err:
   if (from_file >= 0) (void) my_close(from_file,MyFlags);
   if (to_file >= 0)
   {
     (void) my_close(to_file, MyFlags);
     /* attempt to delete the to-file we've partially written */
     (void) my_delete(to, MyFlags);
   }
   DBUG_RETURN(-1);
 } /* my_copy */
References utimbuf::actime, Acore::Count(), DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_CHANGE_OWNERSHIP, EE_CHANGE_PERMISSIONS, errno, IO_SIZE, ME_BELL, ME_WAITTANG, utimbuf::modtime, my_close(), MY_COPYTIME, my_create(), my_delete(), MY_DONT_OVERWRITE_FILE, my_errno, my_error(), MY_FAE, MY_FNABP, MY_HOLD_ORIGINAL_MODES, MY_NABP, my_open(), my_read, MY_STAT, my_stat(), MY_SYNC, my_sync(), MY_WME, my_write, MYF, O_BINARY, O_SHARE, and test.