Azerotcore-wotlk: Acore::PlayerRelocationNotifier Struct Reference
Acore::PlayerRelocationNotifier Struct Reference
#include <GridNotifiers.h>
Public Member Functions
PlayerRelocationNotifier (Player &player, bool largeOnly)
template<class T >
void Visit (GridRefMgr< T > &m)
void Visit (PlayerMapType &)
Public Member Functions inherited from Acore::VisibleNotifier
VisibleNotifier (Player &player, bool gobjOnly, bool largeOnly)
void Visit (GameObjectMapType &)
template<class T >
void Visit (GridRefMgr< T > &m)
void SendToSelf (void)
Additional Inherited Members
Public Attributes inherited from Acore::VisibleNotifier
Player & i_player
GuidUnorderedSet vis_guids
std::vector< Unit * > & i_visibleNow
bool i_gobjOnly
bool i_largeOnly
UpdateData i_data
Detailed Description
Definition at line 72 of file GridNotifiers.h.
Constructor & Destructor Documentation
PlayerRelocationNotifier()
Acore::PlayerRelocationNotifier::PlayerRelocationNotifier (Player & player, bool largeOnly) inline
Definition at line 74 of file GridNotifiers.h.
 : VisibleNotifier(player, false, largeOnly) { }
Member Function Documentation
Visit() [1/2]
template<class T > void Acore::PlayerRelocationNotifier::Visit (GridRefMgr< T > & m) inline
Definition at line 76 of file GridNotifiers.h.
 { VisibleNotifier::Visit(m); }
References Acore::VisibleNotifier::Visit().
Visit() [2/2]
void PlayerRelocationNotifier::Visit (PlayerMapType & m)
Definition at line 170 of file GridNotifiers.cpp.
 {
     for (PlayerMapType::iterator iter = m.begin(); iter != m.end(); ++iter)
     {
         Player* player = iter->GetSource();
         vis_guids.erase(player->GetGUID());
         i_player.UpdateVisibilityOf(player, i_data, i_visibleNow);
         player->UpdateVisibilityOf(&i_player); // this notifier with different Visit(PlayerMapType&) than VisibleNotifier is needed to update visibility of self for other players when we move (eg. stealth detection changes)
     }
 }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), Object::GetGUID(), Acore::VisibleNotifier::i_data, Acore::VisibleNotifier::i_player, Acore::VisibleNotifier::i_visibleNow, Player::UpdateVisibilityOf(), and Acore::VisibleNotifier::vis_guids.
The documentation for this struct was generated from the following files:
src/server/game/Grids/Notifiers/GridNotifiers.h
src/server/game/Grids/Notifiers/GridNotifiers.cpp