Azerotcore-wotlk: npc_lk_spirit_bomb::npc_lk_spirit_bombAI Struct Reference
npc_lk_spirit_bomb::npc_lk_spirit_bombAI Struct Reference
Public Member Functions
npc_lk_spirit_bombAI (Creature *creature)
void IsSummonedBy (Unit *) override
void MovementInform (uint32 type, uint32 point) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
uint16 timer
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 3645 of file boss_the_lich_king.cpp.
Constructor & Destructor Documentation
npc_lk_spirit_bombAI()
npc_lk_spirit_bomb::npc_lk_spirit_bombAI::npc_lk_spirit_bombAI (Creature * creature) inline
Definition at line 3647 of file boss_the_lich_king.cpp.
                                                  : NullCreatureAI(creature)
         {
             me->SetReactState(REACT_PASSIVE);
             me->DespawnOrUnsummon(45000); // for safety
             timer = 0;
         }
References Creature::DespawnOrUnsummon(), CreatureAI::me, REACT_PASSIVE, Creature::SetReactState(), and timer.
Member Function Documentation
IsSummonedBy()
void npc_lk_spirit_bomb::npc_lk_spirit_bombAI::IsSummonedBy (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 3656 of file boss_the_lich_king.cpp.
         {
             float destX, destY, destZ;
             me->GetPosition(destX, destY);
             destZ = 1055.0f;    // approximation, gets more precise later
             me->UpdateGroundPositionZ(destX, destY, destZ);
             me->SetWalk(false);
             me->GetMotionMaster()->MovePoint(POINT_GROUND, destX, destY, destZ);
         }
References Unit::GetMotionMaster(), Position::GetPosition(), CreatureAI::me, MotionMaster::MovePoint(), POINT_GROUND, Creature::SetWalk(), and WorldObject::UpdateGroundPositionZ().
MovementInform()
void npc_lk_spirit_bomb::npc_lk_spirit_bombAI::MovementInform (uint32 type, uint32 point) inline override virtual
Reimplemented from CreatureAI.
Definition at line 3666 of file boss_the_lich_king.cpp.
         {
             if (type != POINT_MOTION_TYPE || point != POINT_GROUND)
                 return;
             timer = 1000;
         }
References POINT_GROUND, POINT_MOTION_TYPE, and timer.
UpdateAI()
void npc_lk_spirit_bomb::npc_lk_spirit_bombAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 3674 of file boss_the_lich_king.cpp.
         {
             if (timer)
             {
                 if (timer <= diff)
                 {
                     timer = 0;
                     me->RemoveAllAuras();
                     me->CastSpell((Unit*)nullptr, SPELL_EXPLOSION, false);
                     me->DespawnOrUnsummon(1000);
                 }
                 else
                     timer -= diff;
             }
         }
References Unit::CastSpell(), Creature::DespawnOrUnsummon(), diff(), CreatureAI::me, Unit::RemoveAllAuras(), SPELL_EXPLOSION, and timer.
Member Data Documentation
timer
uint16 npc_lk_spirit_bomb::npc_lk_spirit_bombAI::timer
Definition at line 3654 of file boss_the_lich_king.cpp.
Referenced by MovementInform(), npc_lk_spirit_bombAI(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp