Azerotcore-wotlk: formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > > Struct Template Reference
formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > > Struct Template Reference
#include <core.h>
Public Member Functions
template<typename ParseContext >
FMT_CONSTEXPR auto parse (ParseContext &ctx) -> decltype(ctx.begin())
template<typename FormatContext >
FMT_CONSTEXPR auto format (const T &val, FormatContext &ctx) const -> decltype(ctx.out())
template<typename FormatContext >
FMT_CONSTEXPR FMT_INLINE auto format (const T &val, FormatContext &ctx) const -> decltype(ctx.out())
Private Attributes
detail::dynamic_format_specs< Char > specs_
Detailed Description
template<typename T, typename Char>
struct formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > >
Definition at line 2748 of file core.h.
Member Function Documentation
format() [1/2]
template<typename T , typename Char > template<typename FormatContext > FMT_CONSTEXPR auto formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > >::format (const T & val, FormatContext & ctx) const -> decltype(ctx.out())
format() [2/2]
template<typename T , typename Char > template<typename FormatContext > FMT_CONSTEXPR FMT_INLINE auto formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > >::format (const T & val, FormatContext & ctx) const -> decltype(ctx.out())
Definition at line 2337 of file format.h.
{
   if (specs_.width_ref.kind != detail::arg_id_kind::none ||
       specs_.precision_ref.kind != detail::arg_id_kind::none) {
     auto specs = specs_;
     detail::handle_dynamic_spec<detail::width_checker>(specs.width,
                                                        specs.width_ref, ctx);
     detail::handle_dynamic_spec<detail::precision_checker>(
         specs.precision, specs.precision_ref, ctx);
     return detail::write<Char>(ctx.out(), val, specs, ctx.locale());
   }
   return detail::write<Char>(ctx.out(), val, specs_, ctx.locale());
 }
References basic_format_specs< Char >::precision, and basic_format_specs< Char >::width.
parse()
template<typename T , typename Char > template<typename ParseContext > FMT_CONSTEXPR auto formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > >::parse (ParseContext & ctx) -> decltype(ctx.begin()) inline
Definition at line 2758 of file core.h.
{
     auto begin = ctx.begin(), end = ctx.end();
     if (begin == end) return begin;
     using handler_type = detail::dynamic_specs_handler<ParseContext>;
     auto type = detail::type_constant<T, Char>::value;
     auto checker =
         detail::specs_checker<handler_type>(handler_type(specs_, ctx), type);
     auto it = detail::parse_format_specs(begin, end, checker);
     auto eh = ctx.error_handler();
     switch (type) {
     case detail::type::none_type:
       FMT_ASSERT(false, "invalid argument type");
       break;
     case detail::type::bool_type:
       if (!specs_.type || specs_.type == 's') break;
       FMT_FALLTHROUGH;
     case detail::type::int_type:
     case detail::type::uint_type:
     case detail::type::long_long_type:
     case detail::type::ulong_long_type:
     case detail::type::int128_type:
     case detail::type::uint128_type:
       detail::check_int_type_spec(specs_.type, eh);
       break;
     case detail::type::char_type:
       detail::check_char_specs(specs_, eh);
       break;
     case detail::type::float_type:
       if (detail::const_check(FMT_USE_FLOAT))
         detail::parse_float_type_spec(specs_, eh);
       else
         FMT_ASSERT(false, "float support disabled");
       break;
     case detail::type::double_type:
       if (detail::const_check(FMT_USE_DOUBLE))
         detail::parse_float_type_spec(specs_, eh);
       else
         FMT_ASSERT(false, "double support disabled");
       break;
     case detail::type::long_double_type:
       if (detail::const_check(FMT_USE_LONG_DOUBLE))
         detail::parse_float_type_spec(specs_, eh);
       else
         FMT_ASSERT(false, "long double support disabled");
       break;
     case detail::type::cstring_type:
       detail::check_cstring_type_spec(specs_.type, eh);
       break;
     case detail::type::string_type:
       detail::check_string_type_spec(specs_.type, eh);
       break;
     case detail::type::pointer_type:
       detail::check_pointer_type_spec(specs_.type, eh);
       break;
     case detail::type::custom_type:
       // Custom format specifiers are checked in parse functions of
       // formatter specializations.
       break;
     }
     return it;
   }
References check_char_specs(), check_cstring_type_spec(), check_int_type_spec(), check_pointer_type_spec(), check_string_type_spec(), const_check(), FMT_ASSERT, FMT_FALLTHROUGH, FMT_USE_DOUBLE, FMT_USE_FLOAT, FMT_USE_LONG_DOUBLE, parse_float_type_spec(), and parse_format_specs().
Member Data Documentation
specs_
template<typename T , typename Char > detail::dynamic_format_specs<Char> formatter< T, Char, enable_if_t< detail::type_constant< T, Char >::value !=detail::type::custom_type > >::specs_ private
Definition at line 2752 of file core.h.
The documentation for this struct was generated from the following files:
deps/fmt/include/fmt/core.h
deps/fmt/include/fmt/format.h