Azerotcore-wotlk: Acore::Crypto Namespace Reference
Acore::Crypto Namespace Reference
Classes
class AES
class ARC4
struct Argon2
class SRP6
struct Constants
struct TOTP
Typedefs
using SHA1 = Acore::Impl::GenericHash< EVP_sha1, Constants::SHA1_DIGEST_LENGTH_BYTES >
using SHA256 = Acore::Impl::GenericHash< EVP_sha256, Constants::SHA256_DIGEST_LENGTH_BYTES >
using HMAC_SHA1 = Acore::Impl::GenericHMAC< EVP_sha1, Constants::SHA1_DIGEST_LENGTH_BYTES >
using HMAC_SHA256 = Acore::Impl::GenericHMAC< EVP_sha256, Constants::SHA256_DIGEST_LENGTH_BYTES >
Functions
template<typename Cipher >
void AEEncryptWithRandomIV (std::vector< uint8 > &data, typename Cipher::Key const &key)
template<typename Cipher >
void AEEncryptWithRandomIV (std::vector< uint8 > &data, BigNumber const &key)
template<typename Cipher >
bool AEDecrypt (std::vector< uint8 > &data, typename Cipher::Key const &key)
template<typename Cipher >
bool AEDecrypt (std::vector< uint8 > &data, BigNumber const &key)
void GetRandomBytes (uint8 *buf, size_t len)
template<typename Container >
void GetRandomBytes (Container &c)
template<size_t S>
std::array< uint8, S > GetRandomBytes ()
Typedef Documentation
HMAC_SHA1
using Acore::Crypto::HMAC_SHA1 = typedef Acore::Impl::GenericHMAC<EVP_sha1, Constants::SHA1_DIGEST_LENGTH_BYTES>
Definition at line 128 of file HMAC.h.
HMAC_SHA256
using Acore::Crypto::HMAC_SHA256 = typedef Acore::Impl::GenericHMAC<EVP_sha256, Constants::SHA256_DIGEST_LENGTH_BYTES>
Definition at line 129 of file HMAC.h.
SHA1
using Acore::Crypto::SHA1 = typedef Acore::Impl::GenericHash<EVP_sha1, Constants::SHA1_DIGEST_LENGTH_BYTES>
Definition at line 117 of file CryptoHash.h.
SHA256
using Acore::Crypto::SHA256 = typedef Acore::Impl::GenericHash<EVP_sha256, Constants::SHA256_DIGEST_LENGTH_BYTES>
Definition at line 118 of file CryptoHash.h.
Function Documentation
AEDecrypt() [1/2]
template<typename Cipher > bool Acore::Crypto::AEDecrypt (std::vector< uint8 > & data, BigNumber const & key)
Definition at line 105 of file CryptoGenerics.h.
     {
         return AEDecrypt<Cipher>(data, key.ToByteArray<Cipher::KEY_SIZE_BYTES>());
     }
References BigNumber::ToByteArray().
AEDecrypt() [2/2]
template<typename Cipher > bool Acore::Crypto::AEDecrypt (std::vector< uint8 > & data, typename Cipher::Key const & key)
Definition at line 88 of file CryptoGenerics.h.
     {
         using IV = typename Cipher::IV;
         using Tag = typename Cipher::Tag;
         // extract trailing IV and tag
         IV iv;
         Tag tag;
         Acore::Impl::CryptoGenericsImpl::SplitFromBack(data, tag);
         Acore::Impl::CryptoGenericsImpl::SplitFromBack(data, iv);
         // decrypt data
         Cipher cipher(false);
         cipher.Init(key);
         return cipher.Process(iv, data.data(), data.size(), tag);
     }
References Acore::Impl::CryptoGenericsImpl::SplitFromBack().
AEEncryptWithRandomIV() [1/2]
template<typename Cipher > void Acore::Crypto::AEEncryptWithRandomIV (std::vector< uint8 > & data, BigNumber const & key)
Definition at line 82 of file CryptoGenerics.h.
     {
         AEEncryptWithRandomIV<Cipher>(data, key.ToByteArray<Cipher::KEY_SIZE_BYTES>());
     }
References BigNumber::ToByteArray().
AEEncryptWithRandomIV() [2/2]
template<typename Cipher > void Acore::Crypto::AEEncryptWithRandomIV (std::vector< uint8 > & data, typename Cipher::Key const & key)
Definition at line 62 of file CryptoGenerics.h.
     {
         using IV = typename Cipher::IV;
         using Tag = typename Cipher::Tag;
         // select random IV
         IV iv = Acore::Impl::CryptoGenericsImpl::GenerateRandomIV<Cipher>();
         Tag tag;
         // encrypt data
         Cipher cipher(true);
         cipher.Init(key);
         bool success = cipher.Process(iv, data.data(), data.size(), tag);
         ASSERT(success);
         // append trailing IV and tag
         Acore::Impl::CryptoGenericsImpl::AppendToBack(data, iv);
         Acore::Impl::CryptoGenericsImpl::AppendToBack(data, tag);
     }
References Acore::Impl::CryptoGenericsImpl::AppendToBack(), and ASSERT.
GetRandomBytes() [1/3]
template<size_t S> std::array<uint8, S> Acore::Crypto::GetRandomBytes ()
Definition at line 35 of file CryptoRandom.h.
     {
         std::array<uint8, S> arr;
         GetRandomBytes(arr);
         return arr;
     }
References GetRandomBytes().
GetRandomBytes() [2/3]
template<typename Container > void Acore::Crypto::GetRandomBytes (Container & c)
Definition at line 29 of file CryptoRandom.h.
     {
         GetRandomBytes(std::data(c), std::size(c));
     }
References mpq::c, and GetRandomBytes().
GetRandomBytes() [3/3]
void Acore::Crypto::GetRandomBytes (uint8 * buf, size_t len)
Definition at line 22 of file CryptoRandom.cpp.
 {
     int result = RAND_bytes(buf, len);
     ASSERT(result == 1);
 }
References ASSERT.
Referenced by Acore::Impl::CryptoGenericsImpl::GenerateRandomIV(), GetRandomBytes(), account_commandscript::HandleAccount2FASetupCommand(), Acore::Crypto::SRP6::MakeRegistrationData(), AuthSession::ReconnectChallengeCallback(), and WorldSocket::WorldSocket().