Azerotcore-wotlk: npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI Struct Reference
npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI Struct Reference
Public Member Functions
npc_imprisoned_beryl_sorcererAI (Creature *creature)
void Reset () override
void UpdateAI (uint32 diff) override
void EnterCombat (Unit *) override
void SpellHit (Unit *unit, const SpellInfo *spell) override
void GotStinged (ObjectGuid casterGUID)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
uint32 rebuff
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 738 of file zone_borean_tundra.cpp.
Constructor & Destructor Documentation
npc_imprisoned_beryl_sorcererAI()
npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI::npc_imprisoned_beryl_sorcererAI (Creature * creature) inline
Definition at line 740 of file zone_borean_tundra.cpp.
 : ScriptedAI(creature) { }
Member Function Documentation
EnterCombat()
void npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 774 of file zone_borean_tundra.cpp.
         {
         }
GotStinged()
void npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI::GotStinged (ObjectGuid casterGUID) inline
Definition at line 789 of file zone_borean_tundra.cpp.
         {
             if (Player* caster = ObjectAccessor::GetPlayer(*me, casterGUID))
             {
                 uint32 step = caster->GetAuraCount(SPELL_NEURAL_NEEDLE) + 1;
                 switch (step)
                 {
                     case 1:
                         Talk(SAY_IMPRISIONED_BERYL_1);
                         break;
                     case 2:
                         Talk(SAY_IMPRISIONED_BERYL_2, caster);
                         break;
                     case 3:
                         Talk(SAY_IMPRISIONED_BERYL_3);
                         break;
                     case 4:
                         Talk(SAY_IMPRISIONED_BERYL_4);
                         break;
                     case 5:
                         Talk(SAY_IMPRISIONED_BERYL_5);
                         break;
                     case 6:
                         Talk(SAY_IMPRISIONED_BERYL_6, caster);
                         break;
                     case 7:
                         Talk(SAY_IMPRISIONED_BERYL_7);
                         caster->KilledMonsterCredit(NPC_IMPRISONED_BERYL_SORCERER);
                         break;
                 }
             }
         }
References ObjectAccessor::GetPlayer(), ScriptedAI::me, NPC_IMPRISONED_BERYL_SORCERER, SAY_IMPRISIONED_BERYL_1, SAY_IMPRISIONED_BERYL_2, SAY_IMPRISIONED_BERYL_3, SAY_IMPRISIONED_BERYL_4, SAY_IMPRISIONED_BERYL_5, SAY_IMPRISIONED_BERYL_6, SAY_IMPRISIONED_BERYL_7, SPELL_NEURAL_NEEDLE, and CreatureAI::Talk().
Referenced by SpellHit().
Reset()
void npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 744 of file zone_borean_tundra.cpp.
         {
             if (me->GetReactState() != REACT_PASSIVE)
                 me->SetReactState(REACT_PASSIVE);
             rebuff = 0;
             // xinef: correct visuals
             me->UpdatePosition(me->GetPositionX(), me->GetPositionY(), 150.517f, me->GetOrientation(), true);
             me->SetStandState(UNIT_STAND_STATE_SIT_MEDIUM_CHAIR);
         }
References Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Creature::GetReactState(), ScriptedAI::me, REACT_PASSIVE, rebuff, Creature::SetReactState(), Unit::SetStandState(), UNIT_STAND_STATE_SIT_MEDIUM_CHAIR, and Unit::UpdatePosition().
SpellHit()
void npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI::SpellHit (Unit * unit, const SpellInfo * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 778 of file zone_borean_tundra.cpp.
         {
             if (spell->Id == SPELL_NEURAL_NEEDLE && unit->GetTypeId() == TYPEID_PLAYER)
             {
                 if (Player* player = unit->ToPlayer())
                 {
                     GotStinged(player->GetGUID());
                 }
             }
         }
References Object::GetTypeId(), GotStinged(), SpellInfo::Id, SPELL_NEURAL_NEEDLE, Object::ToPlayer(), and TYPEID_PLAYER.
UpdateAI()
void npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 756 of file zone_borean_tundra.cpp.
         {
             UpdateVictim();
             if (rebuff <= diff)
             {
                 if (!me->HasAura(SPELL_COSMETIC_ENSLAVE_CHAINS_SELF))
                 {
                     DoCast(me, SPELL_COSMETIC_ENSLAVE_CHAINS_SELF);
                 }
                 rebuff = 180000;
             }
             else
                 rebuff -= diff;
             DoMeleeAttackIfReady();
         }
References UnitAI::DoCast(), UnitAI::DoMeleeAttackIfReady(), Unit::HasAura(), ScriptedAI::me, rebuff, SPELL_COSMETIC_ENSLAVE_CHAINS_SELF, and CreatureAI::UpdateVictim().
Member Data Documentation
rebuff
uint32 npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI::rebuff
Definition at line 742 of file zone_borean_tundra.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/zone_borean_tundra.cpp