Azerotcore-wotlk: npc_hover_disk::npc_hover_diskAI Struct Reference
npc_hover_disk::npc_hover_diskAI Struct Reference
Public Member Functions
npc_hover_diskAI (Creature *pCreature)
void PassengerBoarded (Unit *who, int8, bool apply) override
== Fields =======================================
void MovementInform (uint32 type, uint32 id) override
void DoAction (int32 param) override
void UpdateAI (uint32 diff) override
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
Public Member Functions inherited from VehicleAI
VehicleAI (Creature *creature)
void OnCharmed (bool apply) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void Reset ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
EventMap events
Additional Inherited Members
Static Public Member Functions inherited from VehicleAI
static int Permissible (Creature const *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1241 of file boss_malygos.cpp.
Constructor & Destructor Documentation
npc_hover_diskAI()
npc_hover_disk::npc_hover_diskAI::npc_hover_diskAI (Creature * pCreature) inline
Definition at line 1243 of file boss_malygos.cpp.
                                               : VehicleAI(pCreature)
         {
             pInstance = me->GetInstanceScript();
             events.Reset();
         }
References WorldObject::GetInstanceScript(), CreatureAI::me, and pInstance.
Member Function Documentation
AttackStart()
void npc_hover_disk::npc_hover_diskAI::AttackStart (Unit *) inline override virtual
Reimplemented from VehicleAI.
Definition at line 1369 of file boss_malygos.cpp.
 {}
DoAction()
void npc_hover_disk::npc_hover_diskAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 1320 of file boss_malygos.cpp.
         {
             switch(param)
             {
                 case 1: // move to next point
                     if (Vehicle* v = me->GetVehicleKit())
                         if (Unit* pass = v->GetPassenger(0))
                             switch(pass->GetEntry())
{
                                 case NPC_NEXUS_LORD:
{
                                         float angle = CenterPos.GetAngle(me);
                                         float newangle = angle - 0.5f;
                                         if (newangle < 0.0f) newangle += 2 * M_PI;
                                         float newz = me->GetPositionZ() - 4.0f;
                                         if (newz < CenterPos.GetPositionZ()) newz = CenterPos.GetPositionZ();
                                         me->GetMotionMaster()->MovePoint(MI_POINT_NEXUS_LORD, CenterPos.GetPositionX() + cos(newangle) * 22.0f, CenterPos.GetPositionY() + sin(newangle) * 22.0f, newz);
                                     }
                                     break;
                                 case NPC_SCION_OF_ETERNITY:
{
                                         float angle = CenterPos.GetAngle(me);
                                         float newangle = angle - 0.3f;
                                         if (newangle < 0.0f) newangle += 2 * M_PI;
                                         float newz = me->GetPositionZ() - 2.0f;
                                         if (newz < CenterPos.GetPositionZ() + 20.0f) newz = CenterPos.GetPositionZ() + 20.0f;
                                         me->GetMotionMaster()->MovePoint(MI_POINT_SCION, CenterPos.GetPositionX() + cos(newangle) * 30.0f, CenterPos.GetPositionY() + sin(newangle) * 30.0f, newz);
                                     }
                                     break;
                             }
                     break;
             }
         }
References CenterPos, Position::GetAngle(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetVehicleKit(), M_PI, CreatureAI::me, MI_POINT_NEXUS_LORD, MI_POINT_SCION, MotionMaster::MovePoint(), NPC_NEXUS_LORD, and NPC_SCION_OF_ETERNITY.
Referenced by UpdateAI().
MoveInLineOfSight()
void npc_hover_disk::npc_hover_diskAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from VehicleAI.
Definition at line 1368 of file boss_malygos.cpp.
 {}
MovementInform()
void npc_hover_disk::npc_hover_diskAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from CreatureAI.
Definition at line 1295 of file boss_malygos.cpp.
         {
             if (type != POINT_MOTION_TYPE)
                 return;
             switch (id)
             {
                 case MI_POINT_SCION:
                     events.RescheduleEvent(EVENT_DISK_MOVE_NEXT_POINT, 0);
                     break;
                 case MI_POINT_NEXUS_LORD:
                     if (me->GetPositionZ() > CenterPos.GetPositionZ() + 2.0f)
                         events.RescheduleEvent(EVENT_DISK_MOVE_NEXT_POINT, 0);
                     else if (Vehicle* v = me->GetVehicleKit())
                         if (Unit* pass = v->GetPassenger(0))
                             if (Creature* c = pass->ToCreature())
{
                                 c->SetReactState(REACT_AGGRESSIVE);
                                 if (Player* plr = c->SelectNearestPlayer(100.0f))
                                     c->AI()->AttackStart(plr);
                             }
                     break;
             }
         }
References mpq::c, CenterPos, EVENT_DISK_MOVE_NEXT_POINT, Position::GetPositionZ(), Unit::GetVehicleKit(), CreatureAI::me, MI_POINT_NEXUS_LORD, MI_POINT_SCION, POINT_MOTION_TYPE, and REACT_AGGRESSIVE.
PassengerBoarded()
void npc_hover_disk::npc_hover_diskAI::PassengerBoarded (Unit * , int8 , bool) inline override virtual
== Fields =======================================
Reimplemented from CreatureAI.
Definition at line 1252 of file boss_malygos.cpp.
         {
             events.Reset();
             if (!who)
                 return;
             if (apply)
             {
                 if (who->GetTypeId() == TYPEID_PLAYER)
                 {
                     who->ApplySpellImmune(0, IMMUNITY_ID, SPELL_ARCANE_OVERLOAD_DMG, true);
                     who->ApplySpellImmune(0, IMMUNITY_ID, SPELL_SURGE_OF_POWER_DMG, true);
                     me->SetSpeed(MOVE_RUN, 1.5f);
                     me->SetSpeed(MOVE_FLIGHT, 1.5f);
                 }
                 else if (who->GetEntry() == NPC_NEXUS_LORD)
                 {
                     me->SetSpeed(MOVE_RUN, 1.5f);
                     me->SetSpeed(MOVE_FLIGHT, 1.5f);
                 }
                 else
                 {
                     me->SetSpeed(MOVE_RUN, 0.6f);
                     me->SetSpeed(MOVE_FLIGHT, 0.6f);
                 }
                 who->SetFacingTo(me->GetOrientation());
                 me->SetCanFly(true);
             }
             else
             {
                 me->GetMotionMaster()->MoveIdle();
                 me->DisableSpline();
                 me->SetCanFly(false);
                 me->GetMotionMaster()->MoveLand(0, me->GetPositionX(), me->GetPositionY(), 267.24f, 10.0f);
                 if (who->GetTypeId() == TYPEID_PLAYER)
                 {
                     who->ApplySpellImmune(0, IMMUNITY_ID, SPELL_ARCANE_OVERLOAD_DMG, false);
                     who->ApplySpellImmune(0, IMMUNITY_ID, SPELL_SURGE_OF_POWER_DMG, false);
                 }
             }
         }
References ByteConverter::apply(), Unit::ApplySpellImmune(), Unit::DisableSpline(), Object::GetEntry(), Unit::GetMotionMaster(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Object::GetTypeId(), IMMUNITY_ID, CreatureAI::me, MOVE_FLIGHT, MOVE_RUN, MotionMaster::MoveIdle(), MotionMaster::MoveLand(), NPC_NEXUS_LORD, Creature::SetCanFly(), Unit::SetFacingTo(), Unit::SetSpeed(), SPELL_ARCANE_OVERLOAD_DMG, SPELL_SURGE_OF_POWER_DMG, and TYPEID_PLAYER.
UpdateAI()
void npc_hover_disk::npc_hover_diskAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from VehicleAI.
Definition at line 1354 of file boss_malygos.cpp.
         {
             events.Update(diff);
             switch(events.ExecuteEvent())
             {
                 case 0:
                     break;
                 case EVENT_DISK_MOVE_NEXT_POINT:
                     DoAction(1);
                     break;
             }
         }
References diff(), DoAction(), and EVENT_DISK_MOVE_NEXT_POINT.
Member Data Documentation
events
EventMap npc_hover_disk::npc_hover_diskAI::events
Definition at line 1250 of file boss_malygos.cpp.
pInstance
InstanceScript* npc_hover_disk::npc_hover_diskAI::pInstance
Definition at line 1249 of file boss_malygos.cpp.
Referenced by npc_hover_diskAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Nexus/EyeOfEternity/boss_malygos.cpp