Azerotcore-wotlk: StoneGripTargetSelector Class Reference
StoneGripTargetSelector Class Reference
Public Member Functions
StoneGripTargetSelector (Creature *me, Unit const *victim)
bool operator() (WorldObject *target) const
Public Attributes
Creature * _me
Unit const * _victim
Additional Inherited Members
Public Types inherited from Acore::unary_function< Unit *, bool >
typedef Unit * argument_type
typedef bool result_type
Detailed Description
Definition at line 651 of file boss_kologarn.cpp.
Constructor & Destructor Documentation
StoneGripTargetSelector()
StoneGripTargetSelector::StoneGripTargetSelector (Creature * me, Unit const * victim) inline
Definition at line 654 of file boss_kologarn.cpp.
 : _me(me), _victim(victim) {}
Member Function Documentation
operator()()
bool StoneGripTargetSelector::operator() (WorldObject * target) const inline
Definition at line 656 of file boss_kologarn.cpp.
     {
         if (target == _victim && _me->getThreatMgr().getThreatList().size() > 1)
             return true;
         if (target->GetTypeId() != TYPEID_PLAYER)
             return true;
         return false;
     }
References _me, _victim, ThreatMgr::getThreatList(), Unit::getThreatMgr(), Object::GetTypeId(), and TYPEID_PLAYER.
Member Data Documentation
_me
Creature* StoneGripTargetSelector::_me
Definition at line 667 of file boss_kologarn.cpp.
Referenced by operator()().
_victim
Unit const* StoneGripTargetSelector::_victim
Definition at line 668 of file boss_kologarn.cpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_kologarn.cpp