Azerotcore-wotlk: AreaTrigger_at_stormwright_shelf Class Reference
AreaTrigger_at_stormwright_shelf Class Reference
Public Member Functions
AreaTrigger_at_stormwright_shelf ()
bool OnTrigger (Player *player, AreaTrigger const *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 146 of file areatrigger_scripts.cpp.
Constructor & Destructor Documentation
AreaTrigger_at_stormwright_shelf()
AreaTrigger_at_stormwright_shelf::AreaTrigger_at_stormwright_shelf () inline
Definition at line 149 of file areatrigger_scripts.cpp.
         : AreaTriggerScript("at_stormwright_shelf")
     {
     }
Member Function Documentation
OnTrigger()
bool AreaTrigger_at_stormwright_shelf::OnTrigger (Player * player, AreaTrigger const *) inline override virtual
Reimplemented from AreaTriggerScript.
Definition at line 154 of file areatrigger_scripts.cpp.
     {
         if (!player->isDead() && player->GetQuestStatus(QUEST_STRENGTH_OF_THE_TEMPEST) == QUEST_STATUS_INCOMPLETE)
             player->CastSpell(player, SPELL_CREATE_TRUE_POWER_OF_THE_TEMPEST, false);
         return true;
     }
References Unit::CastSpell(), Player::GetQuestStatus(), Unit::isDead(), QUEST_STATUS_INCOMPLETE, QUEST_STRENGTH_OF_THE_TEMPEST, and SPELL_CREATE_TRUE_POWER_OF_THE_TEMPEST.
The documentation for this class was generated from the following file:
src/server/scripts/World/areatrigger_scripts.cpp