Azerotcore-wotlk: G3D::Vector4 Class Reference
G3D::Vector4 Class Reference
#include <Vector4.h>
Public Member Functions
Vector4 (const Any &any)
Vector4 & operator= (const Any &a)
Any toAny () const
Vector4 ()
Vector4 (float fX, float fY, float fZ, float fW)
Vector4 (float afCoordinate[4])
Vector4 (const Vector4 &rkVector)
Vector4 (const class Color4 &c)
Vector4 (const Vector3 &rkVector, float fW)
Vector4 (const Vector2 &v1, const Vector2 &v2)
Vector4 (const Vector2 &v1, float fz, float fw)
Vector4 (const Vector4int8 &)
Vector4 (class BinaryInput &b)
void serialize (class BinaryOutput &b) const
void deserialize (class BinaryInput &b)
float & operator[] (int i)
const float & operator[] (int i) const
Vector4 & operator= (const Vector4 &rkVector)
bool operator== (const Vector4 &rkVector) const
bool operator!= (const Vector4 &rkVector) const
void set (float _x, float _y, float _z, float _w)
void set (const Vector3 &v, float _w)
void set (const Vector2 &v, float _z, float _w)
size_t hashCode () const
bool fuzzyEq (const Vector4 &other) const
bool fuzzyNe (const Vector4 &other) const
float length () const
float squaredLength () const
float sum () const
bool isFinite () const
bool isZero () const
bool isUnit () const
Vector4 operator+ (const Vector4 &rkVector) const
Vector4 operator- (const Vector4 &rkVector) const
Vector4 operator* (const Vector4 &rkVector) const
Vector4 operator/ (const Vector4 &rkVector) const
Vector4 operator* (const class Matrix4 &M) const
Vector4 operator* (float fScalar) const
Vector4 operator/ (float fScalar) const
Vector4 operator- () const
Vector4 & operator+= (const Vector4 &rkVector)
Vector4 & operator-= (const Vector4 &rkVector)
Vector4 & operator*= (float fScalar)
Vector4 & operator/= (float fScalar)
Vector4 clamp (const Vector4 &low, const Vector4 &high) const
Vector4 clamp (float low, float high) const
float dot (const Vector4 &rkVector) const
Vector4 min (const Vector4 &v) const
Vector4 max (const Vector4 &v) const
std::string toString () const
Vector4 lerp (const Vector4 &v, float alpha) const
Vector2 xx () const
Vector2 yx () const
Vector2 zx () const
Vector2 wx () const
Vector2 xy () const
Vector2 yy () const
Vector2 zy () const
Vector2 wy () const
Vector2 xz () const
Vector2 yz () const
Vector2 zz () const
Vector2 wz () const
Vector2 xw () const
Vector2 yw () const
Vector2 zw () const
Vector2 ww () const
Vector3 xxx () const
Vector3 yxx () const
Vector3 zxx () const
Vector3 wxx () const
Vector3 xyx () const
Vector3 yyx () const
Vector3 zyx () const
Vector3 wyx () const
Vector3 xzx () const
Vector3 yzx () const
Vector3 zzx () const
Vector3 wzx () const
Vector3 xwx () const
Vector3 ywx () const
Vector3 zwx () const
Vector3 wwx () const
Vector3 xxy () const
Vector3 yxy () const
Vector3 zxy () const
Vector3 wxy () const
Vector3 xyy () const
Vector3 yyy () const
Vector3 zyy () const
Vector3 wyy () const
Vector3 xzy () const
Vector3 yzy () const
Vector3 zzy () const
Vector3 wzy () const
Vector3 xwy () const
Vector3 ywy () const
Vector3 zwy () const
Vector3 wwy () const
Vector3 xxz () const
Vector3 yxz () const
Vector3 zxz () const
Vector3 wxz () const
Vector3 xyz () const
Vector3 yyz () const
Vector3 zyz () const
Vector3 wyz () const
Vector3 xzz () const
Vector3 yzz () const
Vector3 zzz () const
Vector3 wzz () const
Vector3 xwz () const
Vector3 ywz () const
Vector3 zwz () const
Vector3 wwz () const
Vector3 xxw () const
Vector3 yxw () const
Vector3 zxw () const
Vector3 wxw () const
Vector3 xyw () const
Vector3 yyw () const
Vector3 zyw () const
Vector3 wyw () const
Vector3 xzw () const
Vector3 yzw () const
Vector3 zzw () const
Vector3 wzw () const
Vector3 xww () const
Vector3 yww () const
Vector3 zww () const
Vector3 www () const
Vector4 xxxx () const
Vector4 yxxx () const
Vector4 zxxx () const
Vector4 wxxx () const
Vector4 xyxx () const
Vector4 yyxx () const
Vector4 zyxx () const
Vector4 wyxx () const
Vector4 xzxx () const
Vector4 yzxx () const
Vector4 zzxx () const
Vector4 wzxx () const
Vector4 xwxx () const
Vector4 ywxx () const
Vector4 zwxx () const
Vector4 wwxx () const
Vector4 xxyx () const
Vector4 yxyx () const
Vector4 zxyx () const
Vector4 wxyx () const
Vector4 xyyx () const
Vector4 yyyx () const
Vector4 zyyx () const
Vector4 wyyx () const
Vector4 xzyx () const
Vector4 yzyx () const
Vector4 zzyx () const
Vector4 wzyx () const
Vector4 xwyx () const
Vector4 ywyx () const
Vector4 zwyx () const
Vector4 wwyx () const
Vector4 xxzx () const
Vector4 yxzx () const
Vector4 zxzx () const
Vector4 wxzx () const
Vector4 xyzx () const
Vector4 yyzx () const
Vector4 zyzx () const
Vector4 wyzx () const
Vector4 xzzx () const
Vector4 yzzx () const
Vector4 zzzx () const
Vector4 wzzx () const
Vector4 xwzx () const
Vector4 ywzx () const
Vector4 zwzx () const
Vector4 wwzx () const
Vector4 xxwx () const
Vector4 yxwx () const
Vector4 zxwx () const
Vector4 wxwx () const
Vector4 xywx () const
Vector4 yywx () const
Vector4 zywx () const
Vector4 wywx () const
Vector4 xzwx () const
Vector4 yzwx () const
Vector4 zzwx () const
Vector4 wzwx () const
Vector4 xwwx () const
Vector4 ywwx () const
Vector4 zwwx () const
Vector4 wwwx () const
Vector4 xxxy () const
Vector4 yxxy () const
Vector4 zxxy () const
Vector4 wxxy () const
Vector4 xyxy () const
Vector4 yyxy () const
Vector4 zyxy () const
Vector4 wyxy () const
Vector4 xzxy () const
Vector4 yzxy () const
Vector4 zzxy () const
Vector4 wzxy () const
Vector4 xwxy () const
Vector4 ywxy () const
Vector4 zwxy () const
Vector4 wwxy () const
Vector4 xxyy () const
Vector4 yxyy () const
Vector4 zxyy () const
Vector4 wxyy () const
Vector4 xyyy () const
Vector4 yyyy () const
Vector4 zyyy () const
Vector4 wyyy () const
Vector4 xzyy () const
Vector4 yzyy () const
Vector4 zzyy () const
Vector4 wzyy () const
Vector4 xwyy () const
Vector4 ywyy () const
Vector4 zwyy () const
Vector4 wwyy () const
Vector4 xxzy () const
Vector4 yxzy () const
Vector4 zxzy () const
Vector4 wxzy () const
Vector4 xyzy () const
Vector4 yyzy () const
Vector4 zyzy () const
Vector4 wyzy () const
Vector4 xzzy () const
Vector4 yzzy () const
Vector4 zzzy () const
Vector4 wzzy () const
Vector4 xwzy () const
Vector4 ywzy () const
Vector4 zwzy () const
Vector4 wwzy () const
Vector4 xxwy () const
Vector4 yxwy () const
Vector4 zxwy () const
Vector4 wxwy () const
Vector4 xywy () const
Vector4 yywy () const
Vector4 zywy () const
Vector4 wywy () const
Vector4 xzwy () const
Vector4 yzwy () const
Vector4 zzwy () const
Vector4 wzwy () const
Vector4 xwwy () const
Vector4 ywwy () const
Vector4 zwwy () const
Vector4 wwwy () const
Vector4 xxxz () const
Vector4 yxxz () const
Vector4 zxxz () const
Vector4 wxxz () const
Vector4 xyxz () const
Vector4 yyxz () const
Vector4 zyxz () const
Vector4 wyxz () const
Vector4 xzxz () const
Vector4 yzxz () const
Vector4 zzxz () const
Vector4 wzxz () const
Vector4 xwxz () const
Vector4 ywxz () const
Vector4 zwxz () const
Vector4 wwxz () const
Vector4 xxyz () const
Vector4 yxyz () const
Vector4 zxyz () const
Vector4 wxyz () const
Vector4 xyyz () const
Vector4 yyyz () const
Vector4 zyyz () const
Vector4 wyyz () const
Vector4 xzyz () const
Vector4 yzyz () const
Vector4 zzyz () const
Vector4 wzyz () const
Vector4 xwyz () const
Vector4 ywyz () const
Vector4 zwyz () const
Vector4 wwyz () const
Vector4 xxzz () const
Vector4 yxzz () const
Vector4 zxzz () const
Vector4 wxzz () const
Vector4 xyzz () const
Vector4 yyzz () const
Vector4 zyzz () const
Vector4 wyzz () const
Vector4 xzzz () const
Vector4 yzzz () const
Vector4 zzzz () const
Vector4 wzzz () const
Vector4 xwzz () const
Vector4 ywzz () const
Vector4 zwzz () const
Vector4 wwzz () const
Vector4 xxwz () const
Vector4 yxwz () const
Vector4 zxwz () const
Vector4 wxwz () const
Vector4 xywz () const
Vector4 yywz () const
Vector4 zywz () const
Vector4 wywz () const
Vector4 xzwz () const
Vector4 yzwz () const
Vector4 zzwz () const
Vector4 wzwz () const
Vector4 xwwz () const
Vector4 ywwz () const
Vector4 zwwz () const
Vector4 wwwz () const
Vector4 xxxw () const
Vector4 yxxw () const
Vector4 zxxw () const
Vector4 wxxw () const
Vector4 xyxw () const
Vector4 yyxw () const
Vector4 zyxw () const
Vector4 wyxw () const
Vector4 xzxw () const
Vector4 yzxw () const
Vector4 zzxw () const
Vector4 wzxw () const
Vector4 xwxw () const
Vector4 ywxw () const
Vector4 zwxw () const
Vector4 wwxw () const
Vector4 xxyw () const
Vector4 yxyw () const
Vector4 zxyw () const
Vector4 wxyw () const
Vector4 xyyw () const
Vector4 yyyw () const
Vector4 zyyw () const
Vector4 wyyw () const
Vector4 xzyw () const
Vector4 yzyw () const
Vector4 zzyw () const
Vector4 wzyw () const
Vector4 xwyw () const
Vector4 ywyw () const
Vector4 zwyw () const
Vector4 wwyw () const
Vector4 xxzw () const
Vector4 yxzw () const
Vector4 zxzw () const
Vector4 wxzw () const
Vector4 xyzw () const
Vector4 yyzw () const
Vector4 zyzw () const
Vector4 wyzw () const
Vector4 xzzw () const
Vector4 yzzw () const
Vector4 zzzw () const
Vector4 wzzw () const
Vector4 xwzw () const
Vector4 ywzw () const
Vector4 zwzw () const
Vector4 wwzw () const
Vector4 xxww () const
Vector4 yxww () const
Vector4 zxww () const
Vector4 wxww () const
Vector4 xyww () const
Vector4 yyww () const
Vector4 zyww () const
Vector4 wyww () const
Vector4 xzww () const
Vector4 yzww () const
Vector4 zzww () const
Vector4 wzww () const
Vector4 xwww () const
Vector4 ywww () const
Vector4 zwww () const
Vector4 wwww () const
Static Public Member Functions
static const Vector4 & zero ()
static const Vector4 & inf ()
static const Vector4 & nan ()
Public Attributes
float x
float y
float z
float w
Private Member Functions
bool operator< (const Vector4 &) const
bool operator> (const Vector4 &) const
bool operator<= (const Vector4 &) const
bool operator>= (const Vector4 &) const
Friends
Vector4 operator* (float, const Vector4 &rkVector)
Detailed Description
Do not subclass– this implementation makes assumptions about the memory layout.
Definition at line 39 of file Vector4.h.
Constructor & Destructor Documentation
Vector4() [1/11]
G3D::Vector4::Vector4 (const Any & any) explicit
Parameters
any Must either Vector4(#, #, #, #) or Vector3 {x = #, y = #, z = #, w =#}
Definition at line 30 of file Vector4.cpp.
{
     any.verifyName("Vector4");
     any.verifyType(Any::TABLE, Any::ARRAY);
     any.verifySize(4);
     if (any.type() == Any::ARRAY) {
         x = any[0];
         y = any[1];
         z = any[2];
         w = any[3];
     } else {
         // Table
         x = any["x"];
         y = any["y"];
         z = any["z"];
         w = any["w"];
     }
 }
References G3D::any(), G3D::Any::ARRAY, G3D::Any::TABLE, w, x, y, and z.
Vector4() [2/11]
G3D::Vector4::Vector4 () inline
Definition at line 538 of file Vector4.h.
{
     x = y = z = w = 0;
 }
References w, x, y, and z.
Referenced by clamp(), max(), min(), operator*(), operator+(), operator-(), operator/(), operator=(), wwww(), wwwx(), wwwy(), wwwz(), wwxw(), wwxx(), wwxy(), wwxz(), wwyw(), wwyx(), wwyy(), wwyz(), wwzw(), wwzx(), wwzy(), wwzz(), wxww(), wxwx(), wxwy(), wxwz(), wxxw(), wxxx(), wxxy(), wxxz(), wxyw(), wxyx(), wxyy(), wxyz(), wxzw(), wxzx(), wxzy(), wxzz(), wyww(), wywx(), wywy(), wywz(), wyxw(), wyxx(), wyxy(), wyxz(), wyyw(), wyyx(), wyyy(), wyyz(), wyzw(), wyzx(), wyzy(), wyzz(), wzww(), wzwx(), wzwy(), wzwz(), wzxw(), wzxx(), wzxy(), wzxz(), wzyw(), wzyx(), wzyy(), wzyz(), wzzw(), wzzx(), wzzy(), wzzz(), xwww(), xwwx(), xwwy(), xwwz(), xwxw(), xwxx(), xwxy(), xwxz(), xwyw(), xwyx(), xwyy(), xwyz(), xwzw(), xwzx(), xwzy(), xwzz(), xxww(), xxwx(), xxwy(), xxwz(), xxxw(), xxxx(), xxxy(), xxxz(), xxyw(), xxyx(), xxyy(), xxyz(), xxzw(), xxzx(), xxzy(), xxzz(), xyww(), xywx(), xywy(), xywz(), xyxw(), xyxx(), xyxy(), xyxz(), xyyw(), xyyx(), xyyy(), xyyz(), xyzw(), xyzx(), xyzy(), xyzz(), xzww(), xzwx(), xzwy(), xzwz(), xzxw(), xzxx(), xzxy(), xzxz(), xzyw(), xzyx(), xzyy(), xzyz(), xzzw(), xzzx(), xzzy(), xzzz(), ywww(), ywwx(), ywwy(), ywwz(), ywxw(), ywxx(), ywxy(), ywxz(), ywyw(), ywyx(), ywyy(), ywyz(), ywzw(), ywzx(), ywzy(), ywzz(), yxww(), yxwx(), yxwy(), yxwz(), yxxw(), yxxx(), yxxy(), yxxz(), yxyw(), yxyx(), yxyy(), yxyz(), yxzw(), yxzx(), yxzy(), yxzz(), yyww(), yywx(), yywy(), yywz(), yyxw(), yyxx(), yyxy(), yyxz(), yyyw(), yyyx(), yyyy(), yyyz(), yyzw(), yyzx(), yyzy(), yyzz(), yzww(), yzwx(), yzwy(), yzwz(), yzxw(), yzxx(), yzxy(), yzxz(), yzyw(), yzyx(), yzyy(), yzyz(), yzzw(), yzzx(), yzzy(), yzzz(), zwww(), zwwx(), zwwy(), zwwz(), zwxw(), zwxx(), zwxy(), zwxz(), zwyw(), zwyx(), zwyy(), zwyz(), zwzw(), zwzx(), zwzy(), zwzz(), zxww(), zxwx(), zxwy(), zxwz(), zxxw(), zxxx(), zxxy(), zxxz(), zxyw(), zxyx(), zxyy(), zxyz(), zxzw(), zxzx(), zxzy(), zxzz(), zyww(), zywx(), zywy(), zywz(), zyxw(), zyxx(), zyxy(), zyxz(), zyyw(), zyyx(), zyyy(), zyyz(), zyzw(), zyzx(), zyzy(), zyzz(), zzww(), zzwx(), zzwy(), zzwz(), zzxw(), zzxx(), zzxy(), zzxz(), zzyw(), zzyx(), zzyy(), zzyz(), zzzw(), zzzx(), zzzy(), and zzzz().
Vector4() [3/11]
G3D::Vector4::Vector4 (float fX, float fY, float fZ, float fW) inline
Definition at line 544 of file Vector4.h.
{
     x = fX;
     y = fY;
     z = fZ;
     w = fW;
 }
References w, x, y, and z.
Vector4() [4/11]
G3D::Vector4::Vector4 (float afCoordinate[4]) inline
Definition at line 552 of file Vector4.h.
{
     x = afCoordinate[0];
     y = afCoordinate[1];
     z = afCoordinate[2];
     w = afCoordinate[3];
 }
References w, x, y, and z.
Vector4() [5/11]
G3D::Vector4::Vector4 (const Vector4 & rkVector) inline
Definition at line 560 of file Vector4.h.
{
     x = rkVector.x;
     y = rkVector.y;
     z = rkVector.z;
     w = rkVector.w;
 }
References w, x, y, and z.
Vector4() [6/11]
G3D::Vector4::Vector4 (const class Color4 & c)
Definition at line 83 of file Vector4.cpp.
{
     x = c.r;
     y = c.g;
     z = c.b;
     w = c.a;
 }
References mpq::c, w, x, y, and z.
Vector4() [7/11]
G3D::Vector4::Vector4 (const Vector3 & rkVector, float fW) inline
Definition at line 567 of file Vector4.h.
{
     x = rkVector.x;
     y = rkVector.y;
     z = rkVector.z;
     w = fW;
 }
References w, G3D::Vector3::x, x, G3D::Vector3::y, y, G3D::Vector3::z, and z.
Vector4() [8/11]
G3D::Vector4::Vector4 (const Vector2 & v1, const Vector2 & v2)
Definition at line 91 of file Vector4.cpp.
{
     x = v1.x;
     y = v1.y;
     z = v2.x;
     w = v2.y;
 }
References w, G3D::Vector2::x, x, G3D::Vector2::y, y, and z.
Vector4() [9/11]
G3D::Vector4::Vector4 (const Vector2 & v1, float fz, float fw)
Definition at line 99 of file Vector4.cpp.
{
     x = v1.x;
     y = v1.y;
     z = fz;
     w = fw;
 }
References w, G3D::Vector2::x, x, G3D::Vector2::y, y, and z.
Vector4() [10/11]
G3D::Vector4::Vector4 (const Vector4int8 & v)
Divides by 127 when converting
Definition at line 57 of file Vector4.cpp.
                                      : x(v.x / 127.0f), y(v.y / 127.0f), z(v.z / 127.0f), w(v.w / 127.0f) {
 }
Vector4() [11/11]
G3D::Vector4::Vector4 (class BinaryInput & b)
Definition at line 106 of file Vector4.cpp.
{
     deserialize(b);
 }
References b, and deserialize().
Member Function Documentation
clamp() [1/2]
Vector4 G3D::Vector4::clamp (const Vector4 & low, const Vector4 & high) const inline
Definition at line 161 of file Vector4.h.
{
         return Vector4(
             G3D::clamp(x, low.x, high.x),
             G3D::clamp(y, low.y, high.y),
             G3D::clamp(z, low.z, high.z),
             G3D::clamp(w, low.w, high.w));
     }
References G3D::clamp(), Vector4(), w, x, y, and z.
Referenced by G3D::clamp().
clamp() [2/2]
Vector4 G3D::Vector4::clamp (float low, float high) const inline
Definition at line 169 of file Vector4.h.
{
         return Vector4(
             G3D::clamp(x, low, high),
             G3D::clamp(y, low, high),
             G3D::clamp(z, low, high),
             G3D::clamp(w, low, high));
     }
References G3D::clamp(), Vector4(), w, x, y, and z.
deserialize()
void G3D::Vector4::deserialize (class BinaryInput & b)
Definition at line 111 of file Vector4.cpp.
{
     x = b.readFloat32();
     y = b.readFloat32();
     z = b.readFloat32();
     w = b.readFloat32();
 }
References b, w, x, y, and z.
Referenced by G3D::deserialize(), and Vector4().
dot()
float G3D::Vector4::dot (const Vector4 & rkVector) const inline
Definition at line 659 of file Vector4.h.
{
     return x*rkVector.x + y*rkVector.y + z*rkVector.z + w*rkVector.w;
 }
References w, x, y, and z.
Referenced by G3D::Matrix4::determinant(), and G3D::Matrix4::inverse().
fuzzyEq()
bool G3D::Vector4::fuzzyEq (const Vector4 & other) const
fuzzyNe()
bool G3D::Vector4::fuzzyNe (const Vector4 & other) const
hashCode()
size_t G3D::Vector4::hashCode () const
Definition at line 78 of file Vector4.cpp.
{
     return HashTrait<uint128>::hashCode(*((uint128*)this));
 }
References G3D::hashCode().
Referenced by HashTrait< G3D::Vector4 >::hashCode().
inf()
const Vector4 & G3D::Vector4::inf () static
Definition at line 61 of file Vector4.cpp.
{
     static const Vector4 v((float)G3D::finf(), (float)G3D::finf(), (float)G3D::finf(), (float)G3D::finf());
     return v;
 }
References G3D::finf().
Referenced by operator/(), and operator/=().
isFinite()
bool G3D::Vector4::isFinite () const inline
Returns true if this vector has finite length
Definition at line 680 of file Vector4.h.
{
     return G3D::isFinite(x) && G3D::isFinite(y) && G3D::isFinite(z) && G3D::isFinite(w);
 }
References G3D::isFinite(), w, x, y, and z.
isUnit()
bool G3D::Vector4::isUnit () const inline
Returns true if this vector has length == 1
Definition at line 686 of file Vector4.h.
{
     return squaredLength() == 1.0;
 }
References squaredLength().
isZero()
bool G3D::Vector4::isZero () const inline
Returns true if this vector has length == 0
Definition at line 674 of file Vector4.h.
{
     return (x == 0.0f) && (y == 0.0f) && (z == 0.0f) && (w == 0.0f);
 }
References w, x, y, and z.
length()
float G3D::Vector4::length () const inline
sqrt(this->dot(*this))
Definition at line 692 of file Vector4.h.
{
     return sqrtf(squaredLength());
 }
References squaredLength().
Referenced by G3D::length(), and G3D::normalize().
lerp()
Vector4 G3D::Vector4::lerp (const Vector4 & v, float alpha) const inline
Linear interpolation
Definition at line 643 of file Vector4.h.
{
     return (*this) + (v - *this) * alpha;
 }
Referenced by G3D::lerp().
max()
Vector4 G3D::Vector4::max (const Vector4 & v) const inline
Definition at line 669 of file Vector4.h.
{
     return Vector4(G3D::max(v.x, x), G3D::max(v.y, y), G3D::max(v.z, z), G3D::max(v.w, w));
 }
References G3D::max(), Vector4(), w, x, y, and z.
Referenced by G3D::max().
min()
Vector4 G3D::Vector4::min (const Vector4 & v) const inline
Definition at line 664 of file Vector4.h.
{
     return Vector4(G3D::min(v.x, x), G3D::min(v.y, y), G3D::min(v.z, z), G3D::min(v.w, w));
 }
References G3D::min(), Vector4(), w, x, y, and z.
Referenced by G3D::min().
nan()
const Vector4 & G3D::Vector4::nan () static
Definition at line 72 of file Vector4.cpp.
{
     static Vector4 v((float)G3D::fnan(), (float)G3D::fnan(), (float)G3D::fnan(), (float)G3D::fnan());
     return v;
 }
References G3D::fnan().
operator!=()
bool G3D::Vector4::operator!= (const Vector4 & rkVector) const inline
Definition at line 599 of file Vector4.h.
{
     return ( x != rkVector.x || y != rkVector.y || z != rkVector.z || w != rkVector.w);
 }
References w, x, y, and z.
operator*() [1/3]
Vector4 G3D::Vector4::operator* (const class Matrix4 & M) const
operator*() [2/3]
Vector4 G3D::Vector4::operator* (const Vector4 & rkVector) const inline
Definition at line 140 of file Vector4.h.
{
         return Vector4(x * rkVector.x, y * rkVector.y, z * rkVector.z, w * rkVector.w);
     }
References Vector4(), w, x, y, and z.
operator*() [3/3]
Vector4 G3D::Vector4::operator* (float fScalar) const inline
Definition at line 614 of file Vector4.h.
{
     return Vector4(fScalar*x, fScalar*y, fScalar*z, fScalar*w);
 }
References Vector4(), w, x, y, and z.
operator*=()
Vector4 & G3D::Vector4::operator*= (float fScalar) inline
Definition at line 649 of file Vector4.h.
{
     x *= fScalar;
     y *= fScalar;
     z *= fScalar;
     w *= fScalar;
     return *this;
 }
References w, x, y, and z.
operator+()
Vector4 G3D::Vector4::operator+ (const Vector4 & rkVector) const inline
Definition at line 604 of file Vector4.h.
{
     return Vector4(x + rkVector.x, y + rkVector.y, z + rkVector.z, w + rkVector.w);
 }
References Vector4(), w, x, y, and z.
operator+=()
Vector4 & G3D::Vector4::operator+= (const Vector4 & rkVector) inline
Definition at line 624 of file Vector4.h.
{
     x += rkVector.x;
     y += rkVector.y;
     z += rkVector.z;
     w += rkVector.w;
     return *this;
 }
References w, x, y, and z.
operator-() [1/2]
Vector4 G3D::Vector4::operator- () const inline
Definition at line 619 of file Vector4.h.
{
     return Vector4( -x, -y, -z, -w);
 }
References Vector4(), w, x, y, and z.
operator-() [2/2]
Vector4 G3D::Vector4::operator- (const Vector4 & rkVector) const inline
Definition at line 609 of file Vector4.h.
{
     return Vector4(x - rkVector.x, y - rkVector.y, z - rkVector.z, w - rkVector.w);
 }
References Vector4(), w, x, y, and z.
operator-=()
Vector4 & G3D::Vector4::operator-= (const Vector4 & rkVector) inline
Definition at line 633 of file Vector4.h.
{
     x -= rkVector.x;
     y -= rkVector.y;
     z -= rkVector.z;
     w -= rkVector.w;
     return *this;
 }
References w, x, y, and z.
operator/() [1/2]
Vector4 G3D::Vector4::operator/ (const Vector4 & rkVector) const inline
Definition at line 144 of file Vector4.h.
{
         return Vector4(x / rkVector.x, y / rkVector.y, z / rkVector.z, w / rkVector.w);
     }
References Vector4(), w, x, y, and z.
operator/() [2/2]
Vector4 G3D::Vector4::operator/ (float fScalar) const
Definition at line 140 of file Vector4.cpp.
{
     Vector4 kQuot;
     if ( fScalar != 0.0 ) {
         float fInvScalar = 1.0f / fScalar;
         kQuot.x = fInvScalar * x;
         kQuot.y = fInvScalar * y;
         kQuot.z = fInvScalar * z;
         kQuot.w = fInvScalar * w;
         return kQuot;
     } else {
         return Vector4::inf();
     }
 }
References inf(), w, x, y, and z.
operator/=()
Vector4 & G3D::Vector4::operator/= (float fScalar)
Definition at line 156 of file Vector4.cpp.
{
     if (fScalar != 0.0f) {
         float fInvScalar = 1.0f / fScalar;
         x *= fInvScalar;
         y *= fInvScalar;
         z *= fInvScalar;
         w *= fInvScalar;
     } else {
         *this = Vector4::inf();
     }
     return *this;
 }
References inf(), w, x, y, and z.
operator<()
bool G3D::Vector4::operator< (const Vector4 &) const private
operator<=()
bool G3D::Vector4::operator<= (const Vector4 &) const private
operator=() [1/2]
Vector4 & G3D::Vector4::operator= (const Any & a)
Definition at line 24 of file Vector4.cpp.
{
     *this = Vector4(a);
     return *this;
 }
References mpq::a, and Vector4().
operator=() [2/2]
Vector4 & G3D::Vector4::operator= (const Vector4 & rkVector) inline
Definition at line 585 of file Vector4.h.
{
     x = rkVector.x;
     y = rkVector.y;
     z = rkVector.z;
     w = rkVector.w;
     return *this;
 }
References w, x, y, and z.
operator==()
bool G3D::Vector4::operator== (const Vector4 & rkVector) const inline
Definition at line 594 of file Vector4.h.
{
     return ( (x == rkVector.x) && (y == rkVector.y) && (z == rkVector.z) && (w == rkVector.w));
 }
References w, x, y, and z.
operator>()
bool G3D::Vector4::operator> (const Vector4 &) const private
operator>=()
bool G3D::Vector4::operator>= (const Vector4 &) const private
operator[]() [1/2]
float & G3D::Vector4::operator[] (int i) inline
Definition at line 575 of file Vector4.h.
{
     return ((float*)this)[i];
 }
operator[]() [2/2]
const float & G3D::Vector4::operator[] (int i) const inline
Definition at line 580 of file Vector4.h.
{
     return ((float*)this)[i];
 }
serialize()
void G3D::Vector4::serialize (class BinaryOutput & b) const
Definition at line 119 of file Vector4.cpp.
{
     b.writeFloat32(x);
     b.writeFloat32(y);
     b.writeFloat32(z);
     b.writeFloat32(w);
 }
References b, w, x, y, and z.
Referenced by G3D::serialize().
set() [1/3]
void G3D::Vector4::set (const Vector2 & v, float _z, float _w) inline
Definition at line 105 of file Vector4.h.
{
         x = v.x;
         y = v.y;
         z = _z;
         w = _w;
     }
References w, G3D::Vector2::x, x, G3D::Vector2::y, y, and z.
set() [2/3]
void G3D::Vector4::set (const Vector3 & v, float _w) inline
Definition at line 98 of file Vector4.h.
{
         x = v.x;
         y = v.y;
         z = v.z;
         w = _w;
     }
References w, G3D::Vector3::x, x, G3D::Vector3::y, y, G3D::Vector3::z, and z.
set() [3/3]
void G3D::Vector4::set (float _x, float _y, float _z, float _w) inline
Definition at line 91 of file Vector4.h.
{
         x = _x;
         y = _y;
         z = _z;
         w = _w;
     }
References w, x, y, and z.
squaredLength()
float G3D::Vector4::squaredLength () const inline
Definition at line 698 of file Vector4.h.
{
     return x * x + y * y + z * z + w * w;
 }
References w, x, y, and z.
Referenced by isUnit(), and length().
sum()
float G3D::Vector4::sum () const inline
Definition at line 123 of file Vector4.h.
{
         return x + y + z + w;
     }
References w, x, y, and z.
toAny()
Any G3D::Vector4::toAny () const
Converts the Vector4 to an Any.
Definition at line 50 of file Vector4.cpp.
{
     Any any(Any::ARRAY, "Vector4");
     any.append(x, y, z, w);
     return any;
 }
References G3D::any(), G3D::Any::ARRAY, w, x, y, and z.
toString()
std::string G3D::Vector4::toString () const
Definition at line 173 of file Vector4.cpp.
{
     return G3D::format("(%g, %g, %g, %g)", x, y, z, w);
 }
References G3D::format(), w, x, y, and z.
ww()
Vector2 G3D::Vector4::ww () const
Definition at line 193 of file Vector4.cpp.
 { return Vector2       (w, w); }
References w.
www()
Vector3 G3D::Vector4::www () const
Definition at line 260 of file Vector4.cpp.
 { return Vector3       (w, w, w); }
References w.
wwww()
Vector4 G3D::Vector4::wwww () const
Definition at line 519 of file Vector4.cpp.
 { return Vector4       (w, w, w, w); }
References Vector4(), and w.
wwwx()
Vector4 G3D::Vector4::wwwx () const
Definition at line 327 of file Vector4.cpp.
 { return Vector4       (w, w, w, x); }
References Vector4(), w, and x.
wwwy()
Vector4 G3D::Vector4::wwwy () const
Definition at line 391 of file Vector4.cpp.
 { return Vector4       (w, w, w, y); }
References Vector4(), w, and y.
wwwz()
Vector4 G3D::Vector4::wwwz () const
Definition at line 455 of file Vector4.cpp.
 { return Vector4       (w, w, w, z); }
References Vector4(), w, and z.
wwx()
Vector3 G3D::Vector4::wwx () const
Definition at line 212 of file Vector4.cpp.
 { return Vector3       (w, w, x); }
References w, and x.
wwxw()
Vector4 G3D::Vector4::wwxw () const
Definition at line 471 of file Vector4.cpp.
 { return Vector4       (w, w, x, w); }
References Vector4(), w, and x.
wwxx()
Vector4 G3D::Vector4::wwxx () const
Definition at line 279 of file Vector4.cpp.
 { return Vector4       (w, w, x, x); }
References Vector4(), w, and x.
wwxy()
Vector4 G3D::Vector4::wwxy () const
Definition at line 343 of file Vector4.cpp.
 { return Vector4       (w, w, x, y); }
References Vector4(), w, x, and y.
wwxz()
Vector4 G3D::Vector4::wwxz () const
Definition at line 407 of file Vector4.cpp.
 { return Vector4       (w, w, x, z); }
References Vector4(), w, x, and z.
wwy()
Vector3 G3D::Vector4::wwy () const
Definition at line 228 of file Vector4.cpp.
 { return Vector3       (w, w, y); }
References w, and y.
wwyw()
Vector4 G3D::Vector4::wwyw () const
Definition at line 487 of file Vector4.cpp.
 { return Vector4       (w, w, y, w); }
References Vector4(), w, and y.
wwyx()
Vector4 G3D::Vector4::wwyx () const
Definition at line 295 of file Vector4.cpp.
 { return Vector4       (w, w, y, x); }
References Vector4(), w, x, and y.
wwyy()
Vector4 G3D::Vector4::wwyy () const
Definition at line 359 of file Vector4.cpp.
 { return Vector4       (w, w, y, y); }
References Vector4(), w, and y.
wwyz()
Vector4 G3D::Vector4::wwyz () const
Definition at line 423 of file Vector4.cpp.
 { return Vector4       (w, w, y, z); }
References Vector4(), w, y, and z.
wwz()
Vector3 G3D::Vector4::wwz () const
Definition at line 244 of file Vector4.cpp.
 { return Vector3       (w, w, z); }
References w, and z.
wwzw()
Vector4 G3D::Vector4::wwzw () const
Definition at line 503 of file Vector4.cpp.
 { return Vector4       (w, w, z, w); }
References Vector4(), w, and z.
wwzx()
Vector4 G3D::Vector4::wwzx () const
Definition at line 311 of file Vector4.cpp.
 { return Vector4       (w, w, z, x); }
References Vector4(), w, x, and z.
wwzy()
Vector4 G3D::Vector4::wwzy () const
Definition at line 375 of file Vector4.cpp.
 { return Vector4       (w, w, z, y); }
References Vector4(), w, y, and z.
wwzz()
Vector4 G3D::Vector4::wwzz () const
Definition at line 439 of file Vector4.cpp.
 { return Vector4       (w, w, z, z); }
References Vector4(), w, and z.
wx()
Vector2 G3D::Vector4::wx () const
Definition at line 181 of file Vector4.cpp.
 { return Vector2       (w, x); }
References w, and x.
wxw()
Vector3 G3D::Vector4::wxw () const
Definition at line 248 of file Vector4.cpp.
 { return Vector3       (w, x, w); }
References w, and x.
wxww()
Vector4 G3D::Vector4::wxww () const
Definition at line 507 of file Vector4.cpp.
 { return Vector4       (w, x, w, w); }
References Vector4(), w, and x.
wxwx()
Vector4 G3D::Vector4::wxwx () const
Definition at line 315 of file Vector4.cpp.
 { return Vector4       (w, x, w, x); }
References Vector4(), w, and x.
wxwy()
Vector4 G3D::Vector4::wxwy () const
Definition at line 379 of file Vector4.cpp.
 { return Vector4       (w, x, w, y); }
References Vector4(), w, x, and y.
wxwz()
Vector4 G3D::Vector4::wxwz () const
Definition at line 443 of file Vector4.cpp.
 { return Vector4       (w, x, w, z); }
References Vector4(), w, x, and z.
wxx()
Vector3 G3D::Vector4::wxx () const
Definition at line 200 of file Vector4.cpp.
 { return Vector3       (w, x, x); }
References w, and x.
wxxw()
Vector4 G3D::Vector4::wxxw () const
Definition at line 459 of file Vector4.cpp.
 { return Vector4       (w, x, x, w); }
References Vector4(), w, and x.
wxxx()
Vector4 G3D::Vector4::wxxx () const
Definition at line 267 of file Vector4.cpp.
 { return Vector4       (w, x, x, x); }
References Vector4(), w, and x.
wxxy()
Vector4 G3D::Vector4::wxxy () const
Definition at line 331 of file Vector4.cpp.
 { return Vector4       (w, x, x, y); }
References Vector4(), w, x, and y.
wxxz()
Vector4 G3D::Vector4::wxxz () const
Definition at line 395 of file Vector4.cpp.
 { return Vector4       (w, x, x, z); }
References Vector4(), w, x, and z.
wxy()
Vector3 G3D::Vector4::wxy () const
Definition at line 216 of file Vector4.cpp.
 { return Vector3       (w, x, y); }
References w, x, and y.
wxyw()
Vector4 G3D::Vector4::wxyw () const
Definition at line 475 of file Vector4.cpp.
 { return Vector4       (w, x, y, w); }
References Vector4(), w, x, and y.
wxyx()
Vector4 G3D::Vector4::wxyx () const
Definition at line 283 of file Vector4.cpp.
 { return Vector4       (w, x, y, x); }
References Vector4(), w, x, and y.
wxyy()
Vector4 G3D::Vector4::wxyy () const
Definition at line 347 of file Vector4.cpp.
 { return Vector4       (w, x, y, y); }
References Vector4(), w, x, and y.
wxyz()
Vector4 G3D::Vector4::wxyz () const
Definition at line 411 of file Vector4.cpp.
 { return Vector4       (w, x, y, z); }
References Vector4(), w, x, y, and z.
wxz()
Vector3 G3D::Vector4::wxz () const
Definition at line 232 of file Vector4.cpp.
 { return Vector3       (w, x, z); }
References w, x, and z.
wxzw()
Vector4 G3D::Vector4::wxzw () const
Definition at line 491 of file Vector4.cpp.
 { return Vector4       (w, x, z, w); }
References Vector4(), w, x, and z.
wxzx()
Vector4 G3D::Vector4::wxzx () const
Definition at line 299 of file Vector4.cpp.
 { return Vector4       (w, x, z, x); }
References Vector4(), w, x, and z.
wxzy()
Vector4 G3D::Vector4::wxzy () const
Definition at line 363 of file Vector4.cpp.
 { return Vector4       (w, x, z, y); }
References Vector4(), w, x, y, and z.
wxzz()
Vector4 G3D::Vector4::wxzz () const
Definition at line 427 of file Vector4.cpp.
 { return Vector4       (w, x, z, z); }
References Vector4(), w, x, and z.
wy()
Vector2 G3D::Vector4::wy () const
Definition at line 185 of file Vector4.cpp.
 { return Vector2       (w, y); }
References w, and y.
wyw()
Vector3 G3D::Vector4::wyw () const
Definition at line 252 of file Vector4.cpp.
 { return Vector3       (w, y, w); }
References w, and y.
wyww()
Vector4 G3D::Vector4::wyww () const
Definition at line 511 of file Vector4.cpp.
 { return Vector4       (w, y, w, w); }
References Vector4(), w, and y.
wywx()
Vector4 G3D::Vector4::wywx () const
Definition at line 319 of file Vector4.cpp.
 { return Vector4       (w, y, w, x); }
References Vector4(), w, x, and y.
wywy()
Vector4 G3D::Vector4::wywy () const
Definition at line 383 of file Vector4.cpp.
 { return Vector4       (w, y, w, y); }
References Vector4(), w, and y.
wywz()
Vector4 G3D::Vector4::wywz () const
Definition at line 447 of file Vector4.cpp.
 { return Vector4       (w, y, w, z); }
References Vector4(), w, y, and z.
wyx()
Vector3 G3D::Vector4::wyx () const
Definition at line 204 of file Vector4.cpp.
 { return Vector3       (w, y, x); }
References w, x, and y.
wyxw()
Vector4 G3D::Vector4::wyxw () const
Definition at line 463 of file Vector4.cpp.
 { return Vector4       (w, y, x, w); }
References Vector4(), w, x, and y.
wyxx()
Vector4 G3D::Vector4::wyxx () const
Definition at line 271 of file Vector4.cpp.
 { return Vector4       (w, y, x, x); }
References Vector4(), w, x, and y.
wyxy()
Vector4 G3D::Vector4::wyxy () const
Definition at line 335 of file Vector4.cpp.
 { return Vector4       (w, y, x, y); }
References Vector4(), w, x, and y.
wyxz()
Vector4 G3D::Vector4::wyxz () const
Definition at line 399 of file Vector4.cpp.
 { return Vector4       (w, y, x, z); }
References Vector4(), w, x, y, and z.
wyy()
Vector3 G3D::Vector4::wyy () const
Definition at line 220 of file Vector4.cpp.
 { return Vector3       (w, y, y); }
References w, and y.
wyyw()
Vector4 G3D::Vector4::wyyw () const
Definition at line 479 of file Vector4.cpp.
 { return Vector4       (w, y, y, w); }
References Vector4(), w, and y.
wyyx()
Vector4 G3D::Vector4::wyyx () const
Definition at line 287 of file Vector4.cpp.
 { return Vector4       (w, y, y, x); }
References Vector4(), w, x, and y.
wyyy()
Vector4 G3D::Vector4::wyyy () const
Definition at line 351 of file Vector4.cpp.
 { return Vector4       (w, y, y, y); }
References Vector4(), w, and y.
wyyz()
Vector4 G3D::Vector4::wyyz () const
Definition at line 415 of file Vector4.cpp.
 { return Vector4       (w, y, y, z); }
References Vector4(), w, y, and z.
wyz()
Vector3 G3D::Vector4::wyz () const
Definition at line 236 of file Vector4.cpp.
 { return Vector3       (w, y, z); }
References w, y, and z.
wyzw()
Vector4 G3D::Vector4::wyzw () const
Definition at line 495 of file Vector4.cpp.
 { return Vector4       (w, y, z, w); }
References Vector4(), w, y, and z.
wyzx()
Vector4 G3D::Vector4::wyzx () const
Definition at line 303 of file Vector4.cpp.
 { return Vector4       (w, y, z, x); }
References Vector4(), w, x, y, and z.
wyzy()
Vector4 G3D::Vector4::wyzy () const
Definition at line 367 of file Vector4.cpp.
 { return Vector4       (w, y, z, y); }
References Vector4(), w, y, and z.
wyzz()
Vector4 G3D::Vector4::wyzz () const
Definition at line 431 of file Vector4.cpp.
 { return Vector4       (w, y, z, z); }
References Vector4(), w, y, and z.
wz()
Vector2 G3D::Vector4::wz () const
Definition at line 189 of file Vector4.cpp.
 { return Vector2       (w, z); }
References w, and z.
wzw()
Vector3 G3D::Vector4::wzw () const
Definition at line 256 of file Vector4.cpp.
 { return Vector3       (w, z, w); }
References w, and z.
wzww()
Vector4 G3D::Vector4::wzww () const
Definition at line 515 of file Vector4.cpp.
 { return Vector4       (w, z, w, w); }
References Vector4(), w, and z.
wzwx()
Vector4 G3D::Vector4::wzwx () const
Definition at line 323 of file Vector4.cpp.
 { return Vector4       (w, z, w, x); }
References Vector4(), w, x, and z.
wzwy()
Vector4 G3D::Vector4::wzwy () const
Definition at line 387 of file Vector4.cpp.
 { return Vector4       (w, z, w, y); }
References Vector4(), w, y, and z.
wzwz()
Vector4 G3D::Vector4::wzwz () const
Definition at line 451 of file Vector4.cpp.
 { return Vector4       (w, z, w, z); }
References Vector4(), w, and z.
wzx()
Vector3 G3D::Vector4::wzx () const
Definition at line 208 of file Vector4.cpp.
 { return Vector3       (w, z, x); }
References w, x, and z.
wzxw()
Vector4 G3D::Vector4::wzxw () const
Definition at line 467 of file Vector4.cpp.
 { return Vector4       (w, z, x, w); }
References Vector4(), w, x, and z.
wzxx()
Vector4 G3D::Vector4::wzxx () const
Definition at line 275 of file Vector4.cpp.
 { return Vector4       (w, z, x, x); }
References Vector4(), w, x, and z.
wzxy()
Vector4 G3D::Vector4::wzxy () const
Definition at line 339 of file Vector4.cpp.
 { return Vector4       (w, z, x, y); }
References Vector4(), w, x, y, and z.
wzxz()
Vector4 G3D::Vector4::wzxz () const
Definition at line 403 of file Vector4.cpp.
 { return Vector4       (w, z, x, z); }
References Vector4(), w, x, and z.
wzy()
Vector3 G3D::Vector4::wzy () const
Definition at line 224 of file Vector4.cpp.
 { return Vector3       (w, z, y); }
References w, y, and z.
wzyw()
Vector4 G3D::Vector4::wzyw () const
Definition at line 483 of file Vector4.cpp.
 { return Vector4       (w, z, y, w); }
References Vector4(), w, y, and z.
wzyx()
Vector4 G3D::Vector4::wzyx () const
Definition at line 291 of file Vector4.cpp.
 { return Vector4       (w, z, y, x); }
References Vector4(), w, x, y, and z.
wzyy()
Vector4 G3D::Vector4::wzyy () const
Definition at line 355 of file Vector4.cpp.
 { return Vector4       (w, z, y, y); }
References Vector4(), w, y, and z.
wzyz()
Vector4 G3D::Vector4::wzyz () const
Definition at line 419 of file Vector4.cpp.
 { return Vector4       (w, z, y, z); }
References Vector4(), w, y, and z.
wzz()
Vector3 G3D::Vector4::wzz () const
Definition at line 240 of file Vector4.cpp.
 { return Vector3       (w, z, z); }
References w, and z.
wzzw()
Vector4 G3D::Vector4::wzzw () const
Definition at line 499 of file Vector4.cpp.
 { return Vector4       (w, z, z, w); }
References Vector4(), w, and z.
wzzx()
Vector4 G3D::Vector4::wzzx () const
Definition at line 307 of file Vector4.cpp.
 { return Vector4       (w, z, z, x); }
References Vector4(), w, x, and z.
wzzy()
Vector4 G3D::Vector4::wzzy () const
Definition at line 371 of file Vector4.cpp.
 { return Vector4       (w, z, z, y); }
References Vector4(), w, y, and z.
wzzz()
Vector4 G3D::Vector4::wzzz () const
Definition at line 435 of file Vector4.cpp.
 { return Vector4       (w, z, z, z); }
References Vector4(), w, and z.
xw()
Vector2 G3D::Vector4::xw () const
Definition at line 190 of file Vector4.cpp.
 { return Vector2       (x, w); }
References w, and x.
xww()
Vector3 G3D::Vector4::xww () const
Definition at line 257 of file Vector4.cpp.
 { return Vector3       (x, w, w); }
References w, and x.
xwww()
Vector4 G3D::Vector4::xwww () const
Definition at line 516 of file Vector4.cpp.
 { return Vector4       (x, w, w, w); }
References Vector4(), w, and x.
xwwx()
Vector4 G3D::Vector4::xwwx () const
Definition at line 324 of file Vector4.cpp.
 { return Vector4       (x, w, w, x); }
References Vector4(), w, and x.
xwwy()
Vector4 G3D::Vector4::xwwy () const
Definition at line 388 of file Vector4.cpp.
 { return Vector4       (x, w, w, y); }
References Vector4(), w, x, and y.
xwwz()
Vector4 G3D::Vector4::xwwz () const
Definition at line 452 of file Vector4.cpp.
 { return Vector4       (x, w, w, z); }
References Vector4(), w, x, and z.
xwx()
Vector3 G3D::Vector4::xwx () const
Definition at line 209 of file Vector4.cpp.
 { return Vector3       (x, w, x); }
References w, and x.
xwxw()
Vector4 G3D::Vector4::xwxw () const
Definition at line 468 of file Vector4.cpp.
 { return Vector4       (x, w, x, w); }
References Vector4(), w, and x.
xwxx()
Vector4 G3D::Vector4::xwxx () const
Definition at line 276 of file Vector4.cpp.
 { return Vector4       (x, w, x, x); }
References Vector4(), w, and x.
xwxy()
Vector4 G3D::Vector4::xwxy () const
Definition at line 340 of file Vector4.cpp.
 { return Vector4       (x, w, x, y); }
References Vector4(), w, x, and y.
xwxz()
Vector4 G3D::Vector4::xwxz () const
Definition at line 404 of file Vector4.cpp.
 { return Vector4       (x, w, x, z); }
References Vector4(), w, x, and z.
xwy()
Vector3 G3D::Vector4::xwy () const
Definition at line 225 of file Vector4.cpp.
 { return Vector3       (x, w, y); }
References w, x, and y.
xwyw()
Vector4 G3D::Vector4::xwyw () const
Definition at line 484 of file Vector4.cpp.
 { return Vector4       (x, w, y, w); }
References Vector4(), w, x, and y.
xwyx()
Vector4 G3D::Vector4::xwyx () const
Definition at line 292 of file Vector4.cpp.
 { return Vector4       (x, w, y, x); }
References Vector4(), w, x, and y.
xwyy()
Vector4 G3D::Vector4::xwyy () const
Definition at line 356 of file Vector4.cpp.
 { return Vector4       (x, w, y, y); }
References Vector4(), w, x, and y.
xwyz()
Vector4 G3D::Vector4::xwyz () const
Definition at line 420 of file Vector4.cpp.
 { return Vector4       (x, w, y, z); }
References Vector4(), w, x, y, and z.
xwz()
Vector3 G3D::Vector4::xwz () const
Definition at line 241 of file Vector4.cpp.
 { return Vector3       (x, w, z); }
References w, x, and z.
xwzw()
Vector4 G3D::Vector4::xwzw () const
Definition at line 500 of file Vector4.cpp.
 { return Vector4       (x, w, z, w); }
References Vector4(), w, x, and z.
xwzx()
Vector4 G3D::Vector4::xwzx () const
Definition at line 308 of file Vector4.cpp.
 { return Vector4       (x, w, z, x); }
References Vector4(), w, x, and z.
xwzy()
Vector4 G3D::Vector4::xwzy () const
Definition at line 372 of file Vector4.cpp.
 { return Vector4       (x, w, z, y); }
References Vector4(), w, x, y, and z.
xwzz()
Vector4 G3D::Vector4::xwzz () const
Definition at line 436 of file Vector4.cpp.
 { return Vector4       (x, w, z, z); }
References Vector4(), w, x, and z.
xx()
Vector2 G3D::Vector4::xx () const
Definition at line 178 of file Vector4.cpp.
 { return Vector2       (x, x); }
References x.
xxw()
Vector3 G3D::Vector4::xxw () const
Definition at line 245 of file Vector4.cpp.
 { return Vector3       (x, x, w); }
References w, and x.
xxww()
Vector4 G3D::Vector4::xxww () const
Definition at line 504 of file Vector4.cpp.
 { return Vector4       (x, x, w, w); }
References Vector4(), w, and x.
xxwx()
Vector4 G3D::Vector4::xxwx () const
Definition at line 312 of file Vector4.cpp.
 { return Vector4       (x, x, w, x); }
References Vector4(), w, and x.
xxwy()
Vector4 G3D::Vector4::xxwy () const
Definition at line 376 of file Vector4.cpp.
 { return Vector4       (x, x, w, y); }
References Vector4(), w, x, and y.
xxwz()
Vector4 G3D::Vector4::xxwz () const
Definition at line 440 of file Vector4.cpp.
 { return Vector4       (x, x, w, z); }
References Vector4(), w, x, and z.
xxx()
Vector3 G3D::Vector4::xxx () const
Definition at line 197 of file Vector4.cpp.
 { return Vector3       (x, x, x); }
References x.
xxxw()
Vector4 G3D::Vector4::xxxw () const
Definition at line 456 of file Vector4.cpp.
 { return Vector4       (x, x, x, w); }
References Vector4(), w, and x.
xxxx()
Vector4 G3D::Vector4::xxxx () const
Definition at line 264 of file Vector4.cpp.
 { return Vector4       (x, x, x, x); }
References Vector4(), and x.
xxxy()
Vector4 G3D::Vector4::xxxy () const
Definition at line 328 of file Vector4.cpp.
 { return Vector4       (x, x, x, y); }
References Vector4(), x, and y.
xxxz()
Vector4 G3D::Vector4::xxxz () const
Definition at line 392 of file Vector4.cpp.
 { return Vector4       (x, x, x, z); }
References Vector4(), x, and z.
xxy()
Vector3 G3D::Vector4::xxy () const
Definition at line 213 of file Vector4.cpp.
 { return Vector3       (x, x, y); }
References x, and y.
xxyw()
Vector4 G3D::Vector4::xxyw () const
Definition at line 472 of file Vector4.cpp.
 { return Vector4       (x, x, y, w); }
References Vector4(), w, x, and y.
xxyx()
Vector4 G3D::Vector4::xxyx () const
Definition at line 280 of file Vector4.cpp.
 { return Vector4       (x, x, y, x); }
References Vector4(), x, and y.
xxyy()
Vector4 G3D::Vector4::xxyy () const
Definition at line 344 of file Vector4.cpp.
 { return Vector4       (x, x, y, y); }
References Vector4(), x, and y.
xxyz()
Vector4 G3D::Vector4::xxyz () const
Definition at line 408 of file Vector4.cpp.
 { return Vector4       (x, x, y, z); }
References Vector4(), x, y, and z.
xxz()
Vector3 G3D::Vector4::xxz () const
Definition at line 229 of file Vector4.cpp.
 { return Vector3       (x, x, z); }
References x, and z.
xxzw()
Vector4 G3D::Vector4::xxzw () const
Definition at line 488 of file Vector4.cpp.
 { return Vector4       (x, x, z, w); }
References Vector4(), w, x, and z.
xxzx()
Vector4 G3D::Vector4::xxzx () const
Definition at line 296 of file Vector4.cpp.
 { return Vector4       (x, x, z, x); }
References Vector4(), x, and z.
xxzy()
Vector4 G3D::Vector4::xxzy () const
Definition at line 360 of file Vector4.cpp.
 { return Vector4       (x, x, z, y); }
References Vector4(), x, y, and z.
xxzz()
Vector4 G3D::Vector4::xxzz () const
Definition at line 424 of file Vector4.cpp.
 { return Vector4       (x, x, z, z); }
References Vector4(), x, and z.
xy()
Vector2 G3D::Vector4::xy () const
Definition at line 182 of file Vector4.cpp.
 { return Vector2       (x, y); }
References x, and y.
xyw()
Vector3 G3D::Vector4::xyw () const
Definition at line 249 of file Vector4.cpp.
 { return Vector3       (x, y, w); }
References w, x, and y.
xyww()
Vector4 G3D::Vector4::xyww () const
Definition at line 508 of file Vector4.cpp.
 { return Vector4       (x, y, w, w); }
References Vector4(), w, x, and y.
xywx()
Vector4 G3D::Vector4::xywx () const
Definition at line 316 of file Vector4.cpp.
 { return Vector4       (x, y, w, x); }
References Vector4(), w, x, and y.
xywy()
Vector4 G3D::Vector4::xywy () const
Definition at line 380 of file Vector4.cpp.
 { return Vector4       (x, y, w, y); }
References Vector4(), w, x, and y.
xywz()
Vector4 G3D::Vector4::xywz () const
Definition at line 444 of file Vector4.cpp.
 { return Vector4       (x, y, w, z); }
References Vector4(), w, x, y, and z.
xyx()
Vector3 G3D::Vector4::xyx () const
Definition at line 201 of file Vector4.cpp.
 { return Vector3       (x, y, x); }
References x, and y.
xyxw()
Vector4 G3D::Vector4::xyxw () const
Definition at line 460 of file Vector4.cpp.
 { return Vector4       (x, y, x, w); }
References Vector4(), w, x, and y.
xyxx()
Vector4 G3D::Vector4::xyxx () const
Definition at line 268 of file Vector4.cpp.
 { return Vector4       (x, y, x, x); }
References Vector4(), x, and y.
xyxy()
Vector4 G3D::Vector4::xyxy () const
Definition at line 332 of file Vector4.cpp.
 { return Vector4       (x, y, x, y); }
References Vector4(), x, and y.
xyxz()
Vector4 G3D::Vector4::xyxz () const
Definition at line 396 of file Vector4.cpp.
 { return Vector4       (x, y, x, z); }
References Vector4(), x, y, and z.
xyy()
Vector3 G3D::Vector4::xyy () const
Definition at line 217 of file Vector4.cpp.
 { return Vector3       (x, y, y); }
References x, and y.
xyyw()
Vector4 G3D::Vector4::xyyw () const
Definition at line 476 of file Vector4.cpp.
 { return Vector4       (x, y, y, w); }
References Vector4(), w, x, and y.
xyyx()
Vector4 G3D::Vector4::xyyx () const
Definition at line 284 of file Vector4.cpp.
 { return Vector4       (x, y, y, x); }
References Vector4(), x, and y.
xyyy()
Vector4 G3D::Vector4::xyyy () const
Definition at line 348 of file Vector4.cpp.
 { return Vector4       (x, y, y, y); }
References Vector4(), x, and y.
xyyz()
Vector4 G3D::Vector4::xyyz () const
Definition at line 412 of file Vector4.cpp.
 { return Vector4       (x, y, y, z); }
References Vector4(), x, y, and z.
xyz()
Vector3 G3D::Vector4::xyz () const
Definition at line 233 of file Vector4.cpp.
 { return Vector3       (x, y, z); }
References x, y, and z.
Referenced by G3D::GLight::effectSphere(), G3D::GLight::frame(), BoundsTrait< class G3D::Vector4 >::getBounds(), BoundsTrait< class G3D::Vector4 * >::getBounds(), PositionTrait< class G3D::Vector4 >::getPosition(), G3D::GLight::GLight(), G3D::Plane::halfSpaceContains(), G3D::Matrix4::homoMul(), G3D::MeshAlg::identifyBackfaces(), G3D::Plane::Plane(), and G3D::GCamera::projectUnit().
xyzw()
Vector4 G3D::Vector4::xyzw () const
Definition at line 492 of file Vector4.cpp.
 { return Vector4       (x, y, z, w); }
References Vector4(), w, x, y, and z.
xyzx()
Vector4 G3D::Vector4::xyzx () const
Definition at line 300 of file Vector4.cpp.
 { return Vector4       (x, y, z, x); }
References Vector4(), x, y, and z.
xyzy()
Vector4 G3D::Vector4::xyzy () const
Definition at line 364 of file Vector4.cpp.
 { return Vector4       (x, y, z, y); }
References Vector4(), x, y, and z.
xyzz()
Vector4 G3D::Vector4::xyzz () const
Definition at line 428 of file Vector4.cpp.
 { return Vector4       (x, y, z, z); }
References Vector4(), x, y, and z.
xz()
Vector2 G3D::Vector4::xz () const
Definition at line 186 of file Vector4.cpp.
 { return Vector2       (x, z); }
References x, and z.
xzw()
Vector3 G3D::Vector4::xzw () const
Definition at line 253 of file Vector4.cpp.
 { return Vector3       (x, z, w); }
References w, x, and z.
xzww()
Vector4 G3D::Vector4::xzww () const
Definition at line 512 of file Vector4.cpp.
 { return Vector4       (x, z, w, w); }
References Vector4(), w, x, and z.
xzwx()
Vector4 G3D::Vector4::xzwx () const
Definition at line 320 of file Vector4.cpp.
 { return Vector4       (x, z, w, x); }
References Vector4(), w, x, and z.
xzwy()
Vector4 G3D::Vector4::xzwy () const
Definition at line 384 of file Vector4.cpp.
 { return Vector4       (x, z, w, y); }
References Vector4(), w, x, y, and z.
xzwz()
Vector4 G3D::Vector4::xzwz () const
Definition at line 448 of file Vector4.cpp.
 { return Vector4       (x, z, w, z); }
References Vector4(), w, x, and z.
xzx()
Vector3 G3D::Vector4::xzx () const
Definition at line 205 of file Vector4.cpp.
 { return Vector3       (x, z, x); }
References x, and z.
xzxw()
Vector4 G3D::Vector4::xzxw () const
Definition at line 464 of file Vector4.cpp.
 { return Vector4       (x, z, x, w); }
References Vector4(), w, x, and z.
xzxx()
Vector4 G3D::Vector4::xzxx () const
Definition at line 272 of file Vector4.cpp.
 { return Vector4       (x, z, x, x); }
References Vector4(), x, and z.
xzxy()
Vector4 G3D::Vector4::xzxy () const
Definition at line 336 of file Vector4.cpp.
 { return Vector4       (x, z, x, y); }
References Vector4(), x, y, and z.
xzxz()
Vector4 G3D::Vector4::xzxz () const
Definition at line 400 of file Vector4.cpp.
 { return Vector4       (x, z, x, z); }
References Vector4(), x, and z.
xzy()
Vector3 G3D::Vector4::xzy () const
Definition at line 221 of file Vector4.cpp.
 { return Vector3       (x, z, y); }
References x, y, and z.
xzyw()
Vector4 G3D::Vector4::xzyw () const
Definition at line 480 of file Vector4.cpp.
 { return Vector4       (x, z, y, w); }
References Vector4(), w, x, y, and z.
xzyx()
Vector4 G3D::Vector4::xzyx () const
Definition at line 288 of file Vector4.cpp.
 { return Vector4       (x, z, y, x); }
References Vector4(), x, y, and z.
xzyy()
Vector4 G3D::Vector4::xzyy () const
Definition at line 352 of file Vector4.cpp.
 { return Vector4       (x, z, y, y); }
References Vector4(), x, y, and z.
xzyz()
Vector4 G3D::Vector4::xzyz () const
Definition at line 416 of file Vector4.cpp.
 { return Vector4       (x, z, y, z); }
References Vector4(), x, y, and z.
xzz()
Vector3 G3D::Vector4::xzz () const
Definition at line 237 of file Vector4.cpp.
 { return Vector3       (x, z, z); }
References x, and z.
xzzw()
Vector4 G3D::Vector4::xzzw () const
Definition at line 496 of file Vector4.cpp.
 { return Vector4       (x, z, z, w); }
References Vector4(), w, x, and z.
xzzx()
Vector4 G3D::Vector4::xzzx () const
Definition at line 304 of file Vector4.cpp.
 { return Vector4       (x, z, z, x); }
References Vector4(), x, and z.
xzzy()
Vector4 G3D::Vector4::xzzy () const
Definition at line 368 of file Vector4.cpp.
 { return Vector4       (x, z, z, y); }
References Vector4(), x, y, and z.
xzzz()
Vector4 G3D::Vector4::xzzz () const
Definition at line 432 of file Vector4.cpp.
 { return Vector4       (x, z, z, z); }
References Vector4(), x, and z.
yw()
Vector2 G3D::Vector4::yw () const
Definition at line 191 of file Vector4.cpp.
 { return Vector2       (y, w); }
References w, and y.
yww()
Vector3 G3D::Vector4::yww () const
Definition at line 258 of file Vector4.cpp.
 { return Vector3       (y, w, w); }
References w, and y.
ywww()
Vector4 G3D::Vector4::ywww () const
Definition at line 517 of file Vector4.cpp.
 { return Vector4       (y, w, w, w); }
References Vector4(), w, and y.
ywwx()
Vector4 G3D::Vector4::ywwx () const
Definition at line 325 of file Vector4.cpp.
 { return Vector4       (y, w, w, x); }
References Vector4(), w, x, and y.
ywwy()
Vector4 G3D::Vector4::ywwy () const
Definition at line 389 of file Vector4.cpp.
 { return Vector4       (y, w, w, y); }
References Vector4(), w, and y.
ywwz()
Vector4 G3D::Vector4::ywwz () const
Definition at line 453 of file Vector4.cpp.
 { return Vector4       (y, w, w, z); }
References Vector4(), w, y, and z.
ywx()
Vector3 G3D::Vector4::ywx () const
Definition at line 210 of file Vector4.cpp.
 { return Vector3       (y, w, x); }
References w, x, and y.
ywxw()
Vector4 G3D::Vector4::ywxw () const
Definition at line 469 of file Vector4.cpp.
 { return Vector4       (y, w, x, w); }
References Vector4(), w, x, and y.
ywxx()
Vector4 G3D::Vector4::ywxx () const
Definition at line 277 of file Vector4.cpp.
 { return Vector4       (y, w, x, x); }
References Vector4(), w, x, and y.
ywxy()
Vector4 G3D::Vector4::ywxy () const
Definition at line 341 of file Vector4.cpp.
 { return Vector4       (y, w, x, y); }
References Vector4(), w, x, and y.
ywxz()
Vector4 G3D::Vector4::ywxz () const
Definition at line 405 of file Vector4.cpp.
 { return Vector4       (y, w, x, z); }
References Vector4(), w, x, y, and z.
ywy()
Vector3 G3D::Vector4::ywy () const
Definition at line 226 of file Vector4.cpp.
 { return Vector3       (y, w, y); }
References w, and y.
ywyw()
Vector4 G3D::Vector4::ywyw () const
Definition at line 485 of file Vector4.cpp.
 { return Vector4       (y, w, y, w); }
References Vector4(), w, and y.
ywyx()
Vector4 G3D::Vector4::ywyx () const
Definition at line 293 of file Vector4.cpp.
 { return Vector4       (y, w, y, x); }
References Vector4(), w, x, and y.
ywyy()
Vector4 G3D::Vector4::ywyy () const
Definition at line 357 of file Vector4.cpp.
 { return Vector4       (y, w, y, y); }
References Vector4(), w, and y.
ywyz()
Vector4 G3D::Vector4::ywyz () const
Definition at line 421 of file Vector4.cpp.
 { return Vector4       (y, w, y, z); }
References Vector4(), w, y, and z.
ywz()
Vector3 G3D::Vector4::ywz () const
Definition at line 242 of file Vector4.cpp.
 { return Vector3       (y, w, z); }
References w, y, and z.
ywzw()
Vector4 G3D::Vector4::ywzw () const
Definition at line 501 of file Vector4.cpp.
 { return Vector4       (y, w, z, w); }
References Vector4(), w, y, and z.
ywzx()
Vector4 G3D::Vector4::ywzx () const
Definition at line 309 of file Vector4.cpp.
 { return Vector4       (y, w, z, x); }
References Vector4(), w, x, y, and z.
ywzy()
Vector4 G3D::Vector4::ywzy () const
Definition at line 373 of file Vector4.cpp.
 { return Vector4       (y, w, z, y); }
References Vector4(), w, y, and z.
ywzz()
Vector4 G3D::Vector4::ywzz () const
Definition at line 437 of file Vector4.cpp.
 { return Vector4       (y, w, z, z); }
References Vector4(), w, y, and z.
yx()
Vector2 G3D::Vector4::yx () const
Definition at line 179 of file Vector4.cpp.
 { return Vector2       (y, x); }
References x, and y.
yxw()
Vector3 G3D::Vector4::yxw () const
Definition at line 246 of file Vector4.cpp.
 { return Vector3       (y, x, w); }
References w, x, and y.
yxww()
Vector4 G3D::Vector4::yxww () const
Definition at line 505 of file Vector4.cpp.
 { return Vector4       (y, x, w, w); }
References Vector4(), w, x, and y.
yxwx()
Vector4 G3D::Vector4::yxwx () const
Definition at line 313 of file Vector4.cpp.
 { return Vector4       (y, x, w, x); }
References Vector4(), w, x, and y.
yxwy()
Vector4 G3D::Vector4::yxwy () const
Definition at line 377 of file Vector4.cpp.
 { return Vector4       (y, x, w, y); }
References Vector4(), w, x, and y.
yxwz()
Vector4 G3D::Vector4::yxwz () const
Definition at line 441 of file Vector4.cpp.
 { return Vector4       (y, x, w, z); }
References Vector4(), w, x, y, and z.
yxx()
Vector3 G3D::Vector4::yxx () const
Definition at line 198 of file Vector4.cpp.
 { return Vector3       (y, x, x); }
References x, and y.
yxxw()
Vector4 G3D::Vector4::yxxw () const
Definition at line 457 of file Vector4.cpp.
 { return Vector4       (y, x, x, w); }
References Vector4(), w, x, and y.
yxxx()
Vector4 G3D::Vector4::yxxx () const
Definition at line 265 of file Vector4.cpp.
 { return Vector4       (y, x, x, x); }
References Vector4(), x, and y.
yxxy()
Vector4 G3D::Vector4::yxxy () const
Definition at line 329 of file Vector4.cpp.
 { return Vector4       (y, x, x, y); }
References Vector4(), x, and y.
yxxz()
Vector4 G3D::Vector4::yxxz () const
Definition at line 393 of file Vector4.cpp.
 { return Vector4       (y, x, x, z); }
References Vector4(), x, y, and z.
yxy()
Vector3 G3D::Vector4::yxy () const
Definition at line 214 of file Vector4.cpp.
 { return Vector3       (y, x, y); }
References x, and y.
yxyw()
Vector4 G3D::Vector4::yxyw () const
Definition at line 473 of file Vector4.cpp.
 { return Vector4       (y, x, y, w); }
References Vector4(), w, x, and y.
yxyx()
Vector4 G3D::Vector4::yxyx () const
Definition at line 281 of file Vector4.cpp.
 { return Vector4       (y, x, y, x); }
References Vector4(), x, and y.
yxyy()
Vector4 G3D::Vector4::yxyy () const
Definition at line 345 of file Vector4.cpp.
 { return Vector4       (y, x, y, y); }
References Vector4(), x, and y.
yxyz()
Vector4 G3D::Vector4::yxyz () const
Definition at line 409 of file Vector4.cpp.
 { return Vector4       (y, x, y, z); }
References Vector4(), x, y, and z.
yxz()
Vector3 G3D::Vector4::yxz () const
Definition at line 230 of file Vector4.cpp.
 { return Vector3       (y, x, z); }
References x, y, and z.
yxzw()
Vector4 G3D::Vector4::yxzw () const
Definition at line 489 of file Vector4.cpp.
 { return Vector4       (y, x, z, w); }
References Vector4(), w, x, y, and z.
yxzx()
Vector4 G3D::Vector4::yxzx () const
Definition at line 297 of file Vector4.cpp.
 { return Vector4       (y, x, z, x); }
References Vector4(), x, y, and z.
yxzy()
Vector4 G3D::Vector4::yxzy () const
Definition at line 361 of file Vector4.cpp.
 { return Vector4       (y, x, z, y); }
References Vector4(), x, y, and z.
yxzz()
Vector4 G3D::Vector4::yxzz () const
Definition at line 425 of file Vector4.cpp.
 { return Vector4       (y, x, z, z); }
References Vector4(), x, y, and z.
yy()
Vector2 G3D::Vector4::yy () const
Definition at line 183 of file Vector4.cpp.
 { return Vector2       (y, y); }
References y.
yyw()
Vector3 G3D::Vector4::yyw () const
Definition at line 250 of file Vector4.cpp.
 { return Vector3       (y, y, w); }
References w, and y.
yyww()
Vector4 G3D::Vector4::yyww () const
Definition at line 509 of file Vector4.cpp.
 { return Vector4       (y, y, w, w); }
References Vector4(), w, and y.
yywx()
Vector4 G3D::Vector4::yywx () const
Definition at line 317 of file Vector4.cpp.
 { return Vector4       (y, y, w, x); }
References Vector4(), w, x, and y.
yywy()
Vector4 G3D::Vector4::yywy () const
Definition at line 381 of file Vector4.cpp.
 { return Vector4       (y, y, w, y); }
References Vector4(), w, and y.
yywz()
Vector4 G3D::Vector4::yywz () const
Definition at line 445 of file Vector4.cpp.
 { return Vector4       (y, y, w, z); }
References Vector4(), w, y, and z.
yyx()
Vector3 G3D::Vector4::yyx () const
Definition at line 202 of file Vector4.cpp.
 { return Vector3       (y, y, x); }
References x, and y.
yyxw()
Vector4 G3D::Vector4::yyxw () const
Definition at line 461 of file Vector4.cpp.
 { return Vector4       (y, y, x, w); }
References Vector4(), w, x, and y.
yyxx()
Vector4 G3D::Vector4::yyxx () const
Definition at line 269 of file Vector4.cpp.
 { return Vector4       (y, y, x, x); }
References Vector4(), x, and y.
yyxy()
Vector4 G3D::Vector4::yyxy () const
Definition at line 333 of file Vector4.cpp.
 { return Vector4       (y, y, x, y); }
References Vector4(), x, and y.
yyxz()
Vector4 G3D::Vector4::yyxz () const
Definition at line 397 of file Vector4.cpp.
 { return Vector4       (y, y, x, z); }
References Vector4(), x, y, and z.
yyy()
Vector3 G3D::Vector4::yyy () const
Definition at line 218 of file Vector4.cpp.
 { return Vector3       (y, y, y); }
References y.
yyyw()
Vector4 G3D::Vector4::yyyw () const
Definition at line 477 of file Vector4.cpp.
 { return Vector4       (y, y, y, w); }
References Vector4(), w, and y.
yyyx()
Vector4 G3D::Vector4::yyyx () const
Definition at line 285 of file Vector4.cpp.
 { return Vector4       (y, y, y, x); }
References Vector4(), x, and y.
yyyy()
Vector4 G3D::Vector4::yyyy () const
Definition at line 349 of file Vector4.cpp.
 { return Vector4       (y, y, y, y); }
References Vector4(), and y.
yyyz()
Vector4 G3D::Vector4::yyyz () const
Definition at line 413 of file Vector4.cpp.
 { return Vector4       (y, y, y, z); }
References Vector4(), y, and z.
yyz()
Vector3 G3D::Vector4::yyz () const
Definition at line 234 of file Vector4.cpp.
 { return Vector3       (y, y, z); }
References y, and z.
yyzw()
Vector4 G3D::Vector4::yyzw () const
Definition at line 493 of file Vector4.cpp.
 { return Vector4       (y, y, z, w); }
References Vector4(), w, y, and z.
yyzx()
Vector4 G3D::Vector4::yyzx () const
Definition at line 301 of file Vector4.cpp.
 { return Vector4       (y, y, z, x); }
References Vector4(), x, y, and z.
yyzy()
Vector4 G3D::Vector4::yyzy () const
Definition at line 365 of file Vector4.cpp.
 { return Vector4       (y, y, z, y); }
References Vector4(), y, and z.
yyzz()
Vector4 G3D::Vector4::yyzz () const
Definition at line 429 of file Vector4.cpp.
 { return Vector4       (y, y, z, z); }
References Vector4(), y, and z.
yz()
Vector2 G3D::Vector4::yz () const
Definition at line 187 of file Vector4.cpp.
 { return Vector2       (y, z); }
References y, and z.
yzw()
Vector3 G3D::Vector4::yzw () const
Definition at line 254 of file Vector4.cpp.
 { return Vector3       (y, z, w); }
References w, y, and z.
yzww()
Vector4 G3D::Vector4::yzww () const
Definition at line 513 of file Vector4.cpp.
 { return Vector4       (y, z, w, w); }
References Vector4(), w, y, and z.
yzwx()
Vector4 G3D::Vector4::yzwx () const
Definition at line 321 of file Vector4.cpp.
 { return Vector4       (y, z, w, x); }
References Vector4(), w, x, y, and z.
yzwy()
Vector4 G3D::Vector4::yzwy () const
Definition at line 385 of file Vector4.cpp.
 { return Vector4       (y, z, w, y); }
References Vector4(), w, y, and z.
yzwz()
Vector4 G3D::Vector4::yzwz () const
Definition at line 449 of file Vector4.cpp.
 { return Vector4       (y, z, w, z); }
References Vector4(), w, y, and z.
yzx()
Vector3 G3D::Vector4::yzx () const
Definition at line 206 of file Vector4.cpp.
 { return Vector3       (y, z, x); }
References x, y, and z.
yzxw()
Vector4 G3D::Vector4::yzxw () const
Definition at line 465 of file Vector4.cpp.
 { return Vector4       (y, z, x, w); }
References Vector4(), w, x, y, and z.
yzxx()
Vector4 G3D::Vector4::yzxx () const
Definition at line 273 of file Vector4.cpp.
 { return Vector4       (y, z, x, x); }
References Vector4(), x, y, and z.
yzxy()
Vector4 G3D::Vector4::yzxy () const
Definition at line 337 of file Vector4.cpp.
 { return Vector4       (y, z, x, y); }
References Vector4(), x, y, and z.
yzxz()
Vector4 G3D::Vector4::yzxz () const
Definition at line 401 of file Vector4.cpp.
 { return Vector4       (y, z, x, z); }
References Vector4(), x, y, and z.
yzy()
Vector3 G3D::Vector4::yzy () const
Definition at line 222 of file Vector4.cpp.
 { return Vector3       (y, z, y); }
References y, and z.
yzyw()
Vector4 G3D::Vector4::yzyw () const
Definition at line 481 of file Vector4.cpp.
 { return Vector4       (y, z, y, w); }
References Vector4(), w, y, and z.
yzyx()
Vector4 G3D::Vector4::yzyx () const
Definition at line 289 of file Vector4.cpp.
 { return Vector4       (y, z, y, x); }
References Vector4(), x, y, and z.
yzyy()
Vector4 G3D::Vector4::yzyy () const
Definition at line 353 of file Vector4.cpp.
 { return Vector4       (y, z, y, y); }
References Vector4(), y, and z.
yzyz()
Vector4 G3D::Vector4::yzyz () const
Definition at line 417 of file Vector4.cpp.
 { return Vector4       (y, z, y, z); }
References Vector4(), y, and z.
yzz()
Vector3 G3D::Vector4::yzz () const
Definition at line 238 of file Vector4.cpp.
 { return Vector3       (y, z, z); }
References y, and z.
yzzw()
Vector4 G3D::Vector4::yzzw () const
Definition at line 497 of file Vector4.cpp.
 { return Vector4       (y, z, z, w); }
References Vector4(), w, y, and z.
yzzx()
Vector4 G3D::Vector4::yzzx () const
Definition at line 305 of file Vector4.cpp.
 { return Vector4       (y, z, z, x); }
References Vector4(), x, y, and z.
yzzy()
Vector4 G3D::Vector4::yzzy () const
Definition at line 369 of file Vector4.cpp.
 { return Vector4       (y, z, z, y); }
References Vector4(), y, and z.
yzzz()
Vector4 G3D::Vector4::yzzz () const
Definition at line 433 of file Vector4.cpp.
 { return Vector4       (y, z, z, z); }
References Vector4(), y, and z.
zero()
const Vector4 & G3D::Vector4::zero () static
Definition at line 67 of file Vector4.cpp.
{
     static const Vector4 v(0,0,0,0);
     return v;
 }
zw()
Vector2 G3D::Vector4::zw () const
Definition at line 192 of file Vector4.cpp.
 { return Vector2       (z, w); }
References w, and z.
zww()
Vector3 G3D::Vector4::zww () const
Definition at line 259 of file Vector4.cpp.
 { return Vector3       (z, w, w); }
References w, and z.
zwww()
Vector4 G3D::Vector4::zwww () const
Definition at line 518 of file Vector4.cpp.
 { return Vector4       (z, w, w, w); }
References Vector4(), w, and z.
zwwx()
Vector4 G3D::Vector4::zwwx () const
Definition at line 326 of file Vector4.cpp.
 { return Vector4       (z, w, w, x); }
References Vector4(), w, x, and z.
zwwy()
Vector4 G3D::Vector4::zwwy () const
Definition at line 390 of file Vector4.cpp.
 { return Vector4       (z, w, w, y); }
References Vector4(), w, y, and z.
zwwz()
Vector4 G3D::Vector4::zwwz () const
Definition at line 454 of file Vector4.cpp.
 { return Vector4       (z, w, w, z); }
References Vector4(), w, and z.
zwx()
Vector3 G3D::Vector4::zwx () const
Definition at line 211 of file Vector4.cpp.
 { return Vector3       (z, w, x); }
References w, x, and z.
zwxw()
Vector4 G3D::Vector4::zwxw () const
Definition at line 470 of file Vector4.cpp.
 { return Vector4       (z, w, x, w); }
References Vector4(), w, x, and z.
zwxx()
Vector4 G3D::Vector4::zwxx () const
Definition at line 278 of file Vector4.cpp.
 { return Vector4       (z, w, x, x); }
References Vector4(), w, x, and z.
zwxy()
Vector4 G3D::Vector4::zwxy () const
Definition at line 342 of file Vector4.cpp.
 { return Vector4       (z, w, x, y); }
References Vector4(), w, x, y, and z.
zwxz()
Vector4 G3D::Vector4::zwxz () const
Definition at line 406 of file Vector4.cpp.
 { return Vector4       (z, w, x, z); }
References Vector4(), w, x, and z.
zwy()
Vector3 G3D::Vector4::zwy () const
Definition at line 227 of file Vector4.cpp.
 { return Vector3       (z, w, y); }
References w, y, and z.
zwyw()
Vector4 G3D::Vector4::zwyw () const
Definition at line 486 of file Vector4.cpp.
 { return Vector4       (z, w, y, w); }
References Vector4(), w, y, and z.
zwyx()
Vector4 G3D::Vector4::zwyx () const
Definition at line 294 of file Vector4.cpp.
 { return Vector4       (z, w, y, x); }
References Vector4(), w, x, y, and z.
zwyy()
Vector4 G3D::Vector4::zwyy () const
Definition at line 358 of file Vector4.cpp.
 { return Vector4       (z, w, y, y); }
References Vector4(), w, y, and z.
zwyz()
Vector4 G3D::Vector4::zwyz () const
Definition at line 422 of file Vector4.cpp.
 { return Vector4       (z, w, y, z); }
References Vector4(), w, y, and z.
zwz()
Vector3 G3D::Vector4::zwz () const
Definition at line 243 of file Vector4.cpp.
 { return Vector3       (z, w, z); }
References w, and z.
zwzw()
Vector4 G3D::Vector4::zwzw () const
Definition at line 502 of file Vector4.cpp.
 { return Vector4       (z, w, z, w); }
References Vector4(), w, and z.
zwzx()
Vector4 G3D::Vector4::zwzx () const
Definition at line 310 of file Vector4.cpp.
 { return Vector4       (z, w, z, x); }
References Vector4(), w, x, and z.
zwzy()
Vector4 G3D::Vector4::zwzy () const
Definition at line 374 of file Vector4.cpp.
 { return Vector4       (z, w, z, y); }
References Vector4(), w, y, and z.
zwzz()
Vector4 G3D::Vector4::zwzz () const
Definition at line 438 of file Vector4.cpp.
 { return Vector4       (z, w, z, z); }
References Vector4(), w, and z.
zx()
Vector2 G3D::Vector4::zx () const
Definition at line 180 of file Vector4.cpp.
 { return Vector2       (z, x); }
References x, and z.
zxw()
Vector3 G3D::Vector4::zxw () const
Definition at line 247 of file Vector4.cpp.
 { return Vector3       (z, x, w); }
References w, x, and z.
zxww()
Vector4 G3D::Vector4::zxww () const
Definition at line 506 of file Vector4.cpp.
 { return Vector4       (z, x, w, w); }
References Vector4(), w, x, and z.
zxwx()
Vector4 G3D::Vector4::zxwx () const
Definition at line 314 of file Vector4.cpp.
 { return Vector4       (z, x, w, x); }
References Vector4(), w, x, and z.
zxwy()
Vector4 G3D::Vector4::zxwy () const
Definition at line 378 of file Vector4.cpp.
 { return Vector4       (z, x, w, y); }
References Vector4(), w, x, y, and z.
zxwz()
Vector4 G3D::Vector4::zxwz () const
Definition at line 442 of file Vector4.cpp.
 { return Vector4       (z, x, w, z); }
References Vector4(), w, x, and z.
zxx()
Vector3 G3D::Vector4::zxx () const
Definition at line 199 of file Vector4.cpp.
 { return Vector3       (z, x, x); }
References x, and z.
zxxw()
Vector4 G3D::Vector4::zxxw () const
Definition at line 458 of file Vector4.cpp.
 { return Vector4       (z, x, x, w); }
References Vector4(), w, x, and z.
zxxx()
Vector4 G3D::Vector4::zxxx () const
Definition at line 266 of file Vector4.cpp.
 { return Vector4       (z, x, x, x); }
References Vector4(), x, and z.
zxxy()
Vector4 G3D::Vector4::zxxy () const
Definition at line 330 of file Vector4.cpp.
 { return Vector4       (z, x, x, y); }
References Vector4(), x, y, and z.
zxxz()
Vector4 G3D::Vector4::zxxz () const
Definition at line 394 of file Vector4.cpp.
 { return Vector4       (z, x, x, z); }
References Vector4(), x, and z.
zxy()
Vector3 G3D::Vector4::zxy () const
Definition at line 215 of file Vector4.cpp.
 { return Vector3       (z, x, y); }
References x, y, and z.
zxyw()
Vector4 G3D::Vector4::zxyw () const
Definition at line 474 of file Vector4.cpp.
 { return Vector4       (z, x, y, w); }
References Vector4(), w, x, y, and z.
zxyx()
Vector4 G3D::Vector4::zxyx () const
Definition at line 282 of file Vector4.cpp.
 { return Vector4       (z, x, y, x); }
References Vector4(), x, y, and z.
zxyy()
Vector4 G3D::Vector4::zxyy () const
Definition at line 346 of file Vector4.cpp.
 { return Vector4       (z, x, y, y); }
References Vector4(), x, y, and z.
zxyz()
Vector4 G3D::Vector4::zxyz () const
Definition at line 410 of file Vector4.cpp.
 { return Vector4       (z, x, y, z); }
References Vector4(), x, y, and z.
zxz()
Vector3 G3D::Vector4::zxz () const
Definition at line 231 of file Vector4.cpp.
 { return Vector3       (z, x, z); }
References x, and z.
zxzw()
Vector4 G3D::Vector4::zxzw () const
Definition at line 490 of file Vector4.cpp.
 { return Vector4       (z, x, z, w); }
References Vector4(), w, x, and z.
zxzx()
Vector4 G3D::Vector4::zxzx () const
Definition at line 298 of file Vector4.cpp.
 { return Vector4       (z, x, z, x); }
References Vector4(), x, and z.
zxzy()
Vector4 G3D::Vector4::zxzy () const
Definition at line 362 of file Vector4.cpp.
 { return Vector4       (z, x, z, y); }
References Vector4(), x, y, and z.
zxzz()
Vector4 G3D::Vector4::zxzz () const
Definition at line 426 of file Vector4.cpp.
 { return Vector4       (z, x, z, z); }
References Vector4(), x, and z.
zy()
Vector2 G3D::Vector4::zy () const
Definition at line 184 of file Vector4.cpp.
 { return Vector2       (z, y); }
References y, and z.
zyw()
Vector3 G3D::Vector4::zyw () const
Definition at line 251 of file Vector4.cpp.
 { return Vector3       (z, y, w); }
References w, y, and z.
zyww()
Vector4 G3D::Vector4::zyww () const
Definition at line 510 of file Vector4.cpp.
 { return Vector4       (z, y, w, w); }
References Vector4(), w, y, and z.
zywx()
Vector4 G3D::Vector4::zywx () const
Definition at line 318 of file Vector4.cpp.
 { return Vector4       (z, y, w, x); }
References Vector4(), w, x, y, and z.
zywy()
Vector4 G3D::Vector4::zywy () const
Definition at line 382 of file Vector4.cpp.
 { return Vector4       (z, y, w, y); }
References Vector4(), w, y, and z.
zywz()
Vector4 G3D::Vector4::zywz () const
Definition at line 446 of file Vector4.cpp.
 { return Vector4       (z, y, w, z); }
References Vector4(), w, y, and z.
zyx()
Vector3 G3D::Vector4::zyx () const
Definition at line 203 of file Vector4.cpp.
 { return Vector3       (z, y, x); }
References x, y, and z.
zyxw()
Vector4 G3D::Vector4::zyxw () const
Definition at line 462 of file Vector4.cpp.
 { return Vector4       (z, y, x, w); }
References Vector4(), w, x, y, and z.
zyxx()
Vector4 G3D::Vector4::zyxx () const
Definition at line 270 of file Vector4.cpp.
 { return Vector4       (z, y, x, x); }
References Vector4(), x, y, and z.
zyxy()
Vector4 G3D::Vector4::zyxy () const
Definition at line 334 of file Vector4.cpp.
 { return Vector4       (z, y, x, y); }
References Vector4(), x, y, and z.
zyxz()
Vector4 G3D::Vector4::zyxz () const
Definition at line 398 of file Vector4.cpp.
 { return Vector4       (z, y, x, z); }
References Vector4(), x, y, and z.
zyy()
Vector3 G3D::Vector4::zyy () const
Definition at line 219 of file Vector4.cpp.
 { return Vector3       (z, y, y); }
References y, and z.
zyyw()
Vector4 G3D::Vector4::zyyw () const
Definition at line 478 of file Vector4.cpp.
 { return Vector4       (z, y, y, w); }
References Vector4(), w, y, and z.
zyyx()
Vector4 G3D::Vector4::zyyx () const
Definition at line 286 of file Vector4.cpp.
 { return Vector4       (z, y, y, x); }
References Vector4(), x, y, and z.
zyyy()
Vector4 G3D::Vector4::zyyy () const
Definition at line 350 of file Vector4.cpp.
 { return Vector4       (z, y, y, y); }
References Vector4(), y, and z.
zyyz()
Vector4 G3D::Vector4::zyyz () const
Definition at line 414 of file Vector4.cpp.
 { return Vector4       (z, y, y, z); }
References Vector4(), y, and z.
zyz()
Vector3 G3D::Vector4::zyz () const
Definition at line 235 of file Vector4.cpp.
 { return Vector3       (z, y, z); }
References y, and z.
zyzw()
Vector4 G3D::Vector4::zyzw () const
Definition at line 494 of file Vector4.cpp.
 { return Vector4       (z, y, z, w); }
References Vector4(), w, y, and z.
zyzx()
Vector4 G3D::Vector4::zyzx () const
Definition at line 302 of file Vector4.cpp.
 { return Vector4       (z, y, z, x); }
References Vector4(), x, y, and z.
zyzy()
Vector4 G3D::Vector4::zyzy () const
Definition at line 366 of file Vector4.cpp.
 { return Vector4       (z, y, z, y); }
References Vector4(), y, and z.
zyzz()
Vector4 G3D::Vector4::zyzz () const
Definition at line 430 of file Vector4.cpp.
 { return Vector4       (z, y, z, z); }
References Vector4(), y, and z.
zz()
Vector2 G3D::Vector4::zz () const
Definition at line 188 of file Vector4.cpp.
 { return Vector2       (z, z); }
References z.
zzw()
Vector3 G3D::Vector4::zzw () const
Definition at line 255 of file Vector4.cpp.
 { return Vector3       (z, z, w); }
References w, and z.
zzww()
Vector4 G3D::Vector4::zzww () const
Definition at line 514 of file Vector4.cpp.
 { return Vector4       (z, z, w, w); }
References Vector4(), w, and z.
zzwx()
Vector4 G3D::Vector4::zzwx () const
Definition at line 322 of file Vector4.cpp.
 { return Vector4       (z, z, w, x); }
References Vector4(), w, x, and z.
zzwy()
Vector4 G3D::Vector4::zzwy () const
Definition at line 386 of file Vector4.cpp.
 { return Vector4       (z, z, w, y); }
References Vector4(), w, y, and z.
zzwz()
Vector4 G3D::Vector4::zzwz () const
Definition at line 450 of file Vector4.cpp.
 { return Vector4       (z, z, w, z); }
References Vector4(), w, and z.
zzx()
Vector3 G3D::Vector4::zzx () const
Definition at line 207 of file Vector4.cpp.
 { return Vector3       (z, z, x); }
References x, and z.
zzxw()
Vector4 G3D::Vector4::zzxw () const
Definition at line 466 of file Vector4.cpp.
 { return Vector4       (z, z, x, w); }
References Vector4(), w, x, and z.
zzxx()
Vector4 G3D::Vector4::zzxx () const
Definition at line 274 of file Vector4.cpp.
 { return Vector4       (z, z, x, x); }
References Vector4(), x, and z.
zzxy()
Vector4 G3D::Vector4::zzxy () const
Definition at line 338 of file Vector4.cpp.
 { return Vector4       (z, z, x, y); }
References Vector4(), x, y, and z.
zzxz()
Vector4 G3D::Vector4::zzxz () const
Definition at line 402 of file Vector4.cpp.
 { return Vector4       (z, z, x, z); }
References Vector4(), x, and z.
zzy()
Vector3 G3D::Vector4::zzy () const
Definition at line 223 of file Vector4.cpp.
 { return Vector3       (z, z, y); }
References y, and z.
zzyw()
Vector4 G3D::Vector4::zzyw () const
Definition at line 482 of file Vector4.cpp.
 { return Vector4       (z, z, y, w); }
References Vector4(), w, y, and z.
zzyx()
Vector4 G3D::Vector4::zzyx () const
Definition at line 290 of file Vector4.cpp.
 { return Vector4       (z, z, y, x); }
References Vector4(), x, y, and z.
zzyy()
Vector4 G3D::Vector4::zzyy () const
Definition at line 354 of file Vector4.cpp.
 { return Vector4       (z, z, y, y); }
References Vector4(), y, and z.
zzyz()
Vector4 G3D::Vector4::zzyz () const
Definition at line 418 of file Vector4.cpp.
 { return Vector4       (z, z, y, z); }
References Vector4(), y, and z.
zzz()
Vector3 G3D::Vector4::zzz () const
Definition at line 239 of file Vector4.cpp.
 { return Vector3       (z, z, z); }
References z.
zzzw()
Vector4 G3D::Vector4::zzzw () const
Definition at line 498 of file Vector4.cpp.
 { return Vector4       (z, z, z, w); }
References Vector4(), w, and z.
zzzx()
Vector4 G3D::Vector4::zzzx () const
Definition at line 306 of file Vector4.cpp.
 { return Vector4       (z, z, z, x); }
References Vector4(), x, and z.
zzzy()
Vector4 G3D::Vector4::zzzy () const
Definition at line 370 of file Vector4.cpp.
 { return Vector4       (z, z, z, y); }
References Vector4(), y, and z.
zzzz()
Vector4 G3D::Vector4::zzzz () const
Definition at line 434 of file Vector4.cpp.
 { return Vector4       (z, z, z, z); }
References Vector4(), and z.
Friends And Related Function Documentation
operator*
Vector4 operator* (float s, const Vector4 & rkVector) friend
Definition at line 717 of file Vector4.h.
{
     return v * s;
 }
Member Data Documentation
w
float G3D::Vector4::w
Definition at line 74 of file Vector4.h.
Referenced by G3D::abs(), G3D::all(), G3D::any(), clamp(), deserialize(), G3D::AnyVal::deserialize(), dot(), G3D::GLight::effectSphere(), G3D::GLight::frame(), G3D::Plane::halfSpaceContains(), debug_commandscript::HandleDebugPlayCinematicCommand(), G3D::Matrix4::homoMul(), G3D::MeshAlg::identifyBackfaces(), isFinite(), isZero(), max(), min(), operator!=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator=(), operator==(), G3D::Plane::Plane(), G3D::GCamera::projectUnit(), readCamera(), serialize(), set(), G3D::sign(), squaredLength(), sum(), toAny(), toString(), G3D::CoordinateFrame::toWorldSpace(), TranslateLocation(), Vector4(), G3D::Vector4int8::Vector4int8(), G3D::BinaryOutput::writeVector4(), ww(), www(), wwww(), wwwx(), wwwy(), wwwz(), wwx(), wwxw(), wwxx(), wwxy(), wwxz(), wwy(), wwyw(), wwyx(), wwyy(), wwyz(), wwz(), wwzw(), wwzx(), wwzy(), wwzz(), wx(), wxw(), wxww(), wxwx(), wxwy(), wxwz(), wxx(), wxxw(), wxxx(), wxxy(), wxxz(), wxy(), wxyw(), wxyx(), wxyy(), wxyz(), wxz(), wxzw(), wxzx(), wxzy(), wxzz(), wy(), wyw(), wyww(), wywx(), wywy(), wywz(), wyx(), wyxw(), wyxx(), wyxy(), wyxz(), wyy(), wyyw(), wyyx(), wyyy(), wyyz(), wyz(), wyzw(), wyzx(), wyzy(), wyzz(), wz(), wzw(), wzww(), wzwx(), wzwy(), wzwz(), wzx(), wzxw(), wzxx(), wzxy(), wzxz(), wzy(), wzyw(), wzyx(), wzyy(), wzyz(), wzz(), wzzw(), wzzx(), wzzy(), wzzz(), xw(), xww(), xwww(), xwwx(), xwwy(), xwwz(), xwx(), xwxw(), xwxx(), xwxy(), xwxz(), xwy(), xwyw(), xwyx(), xwyy(), xwyz(), xwz(), xwzw(), xwzx(), xwzy(), xwzz(), xxw(), xxww(), xxwx(), xxwy(), xxwz(), xxxw(), xxyw(), xxzw(), xyw(), xyww(), xywx(), xywy(), xywz(), xyxw(), xyyw(), xyzw(), xzw(), xzww(), xzwx(), xzwy(), xzwz(), xzxw(), xzyw(), xzzw(), yw(), yww(), ywww(), ywwx(), ywwy(), ywwz(), ywx(), ywxw(), ywxx(), ywxy(), ywxz(), ywy(), ywyw(), ywyx(), ywyy(), ywyz(), ywz(), ywzw(), ywzx(), ywzy(), ywzz(), yxw(), yxww(), yxwx(), yxwy(), yxwz(), yxxw(), yxyw(), yxzw(), yyw(), yyww(), yywx(), yywy(), yywz(), yyxw(), yyyw(), yyzw(), yzw(), yzww(), yzwx(), yzwy(), yzwz(), yzxw(), yzyw(), yzzw(), zw(), zww(), zwww(), zwwx(), zwwy(), zwwz(), zwx(), zwxw(), zwxx(), zwxy(), zwxz(), zwy(), zwyw(), zwyx(), zwyy(), zwyz(), zwz(), zwzw(), zwzx(), zwzy(), zwzz(), zxw(), zxww(), zxwx(), zxwy(), zxwz(), zxxw(), zxyw(), zxzw(), zyw(), zyww(), zywx(), zywy(), zywz(), zyxw(), zyyw(), zyzw(), zzw(), zzww(), zzwx(), zzwy(), zzwz(), zzxw(), zzyw(), and zzzw().
x
float G3D::Vector4::x
Definition at line 74 of file Vector4.h.
Referenced by G3D::abs(), G3D::all(), G3D::any(), clamp(), deserialize(), G3D::AnyVal::deserialize(), dot(), debug_commandscript::HandleDebugPlayCinematicCommand(), isFinite(), isZero(), max(), min(), operator!=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator=(), operator==(), readCamera(), serialize(), set(), G3D::sign(), squaredLength(), sum(), toAny(), toString(), G3D::CoordinateFrame::toWorldSpace(), TranslateLocation(), Vector4(), G3D::Vector4int8::Vector4int8(), G3D::BinaryOutput::writeVector4(), wwwx(), wwx(), wwxw(), wwxx(), wwxy(), wwxz(), wwyx(), wwzx(), wx(), wxw(), wxww(), wxwx(), wxwy(), wxwz(), wxx(), wxxw(), wxxx(), wxxy(), wxxz(), wxy(), wxyw(), wxyx(), wxyy(), wxyz(), wxz(), wxzw(), wxzx(), wxzy(), wxzz(), wywx(), wyx(), wyxw(), wyxx(), wyxy(), wyxz(), wyyx(), wyzx(), wzwx(), wzx(), wzxw(), wzxx(), wzxy(), wzxz(), wzyx(), wzzx(), xw(), xww(), xwww(), xwwx(), xwwy(), xwwz(), xwx(), xwxw(), xwxx(), xwxy(), xwxz(), xwy(), xwyw(), xwyx(), xwyy(), xwyz(), xwz(), xwzw(), xwzx(), xwzy(), xwzz(), xx(), xxw(), xxww(), xxwx(), xxwy(), xxwz(), xxx(), xxxw(), xxxx(), xxxy(), xxxz(), xxy(), xxyw(), xxyx(), xxyy(), xxyz(), xxz(), xxzw(), xxzx(), xxzy(), xxzz(), xy(), xyw(), xyww(), xywx(), xywy(), xywz(), xyx(), xyxw(), xyxx(), xyxy(), xyxz(), xyy(), xyyw(), xyyx(), xyyy(), xyyz(), xyz(), xyzw(), xyzx(), xyzy(), xyzz(), xz(), xzw(), xzww(), xzwx(), xzwy(), xzwz(), xzx(), xzxw(), xzxx(), xzxy(), xzxz(), xzy(), xzyw(), xzyx(), xzyy(), xzyz(), xzz(), xzzw(), xzzx(), xzzy(), xzzz(), ywwx(), ywx(), ywxw(), ywxx(), ywxy(), ywxz(), ywyx(), ywzx(), yx(), yxw(), yxww(), yxwx(), yxwy(), yxwz(), yxx(), yxxw(), yxxx(), yxxy(), yxxz(), yxy(), yxyw(), yxyx(), yxyy(), yxyz(), yxz(), yxzw(), yxzx(), yxzy(), yxzz(), yywx(), yyx(), yyxw(), yyxx(), yyxy(), yyxz(), yyyx(), yyzx(), yzwx(), yzx(), yzxw(), yzxx(), yzxy(), yzxz(), yzyx(), yzzx(), zwwx(), zwx(), zwxw(), zwxx(), zwxy(), zwxz(), zwyx(), zwzx(), zx(), zxw(), zxww(), zxwx(), zxwy(), zxwz(), zxx(), zxxw(), zxxx(), zxxy(), zxxz(), zxy(), zxyw(), zxyx(), zxyy(), zxyz(), zxz(), zxzw(), zxzx(), zxzy(), zxzz(), zywx(), zyx(), zyxw(), zyxx(), zyxy(), zyxz(), zyyx(), zyzx(), zzwx(), zzx(), zzxw(), zzxx(), zzxy(), zzxz(), zzyx(), and zzzx().
y
float G3D::Vector4::y
Definition at line 74 of file Vector4.h.
Referenced by G3D::abs(), G3D::all(), G3D::any(), clamp(), deserialize(), G3D::AnyVal::deserialize(), dot(), debug_commandscript::HandleDebugPlayCinematicCommand(), isFinite(), isZero(), max(), min(), operator!=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator=(), operator==(), readCamera(), serialize(), set(), G3D::sign(), squaredLength(), sum(), toAny(), toString(), G3D::CoordinateFrame::toWorldSpace(), TranslateLocation(), Vector4(), G3D::Vector4int8::Vector4int8(), G3D::BinaryOutput::writeVector4(), wwwy(), wwxy(), wwy(), wwyw(), wwyx(), wwyy(), wwyz(), wwzy(), wxwy(), wxxy(), wxy(), wxyw(), wxyx(), wxyy(), wxyz(), wxzy(), wy(), wyw(), wyww(), wywx(), wywy(), wywz(), wyx(), wyxw(), wyxx(), wyxy(), wyxz(), wyy(), wyyw(), wyyx(), wyyy(), wyyz(), wyz(), wyzw(), wyzx(), wyzy(), wyzz(), wzwy(), wzxy(), wzy(), wzyw(), wzyx(), wzyy(), wzyz(), wzzy(), xwwy(), xwxy(), xwy(), xwyw(), xwyx(), xwyy(), xwyz(), xwzy(), xxwy(), xxxy(), xxy(), xxyw(), xxyx(), xxyy(), xxyz(), xxzy(), xy(), xyw(), xyww(), xywx(), xywy(), xywz(), xyx(), xyxw(), xyxx(), xyxy(), xyxz(), xyy(), xyyw(), xyyx(), xyyy(), xyyz(), xyz(), xyzw(), xyzx(), xyzy(), xyzz(), xzwy(), xzxy(), xzy(), xzyw(), xzyx(), xzyy(), xzyz(), xzzy(), yw(), yww(), ywww(), ywwx(), ywwy(), ywwz(), ywx(), ywxw(), ywxx(), ywxy(), ywxz(), ywy(), ywyw(), ywyx(), ywyy(), ywyz(), ywz(), ywzw(), ywzx(), ywzy(), ywzz(), yx(), yxw(), yxww(), yxwx(), yxwy(), yxwz(), yxx(), yxxw(), yxxx(), yxxy(), yxxz(), yxy(), yxyw(), yxyx(), yxyy(), yxyz(), yxz(), yxzw(), yxzx(), yxzy(), yxzz(), yy(), yyw(), yyww(), yywx(), yywy(), yywz(), yyx(), yyxw(), yyxx(), yyxy(), yyxz(), yyy(), yyyw(), yyyx(), yyyy(), yyyz(), yyz(), yyzw(), yyzx(), yyzy(), yyzz(), yz(), yzw(), yzww(), yzwx(), yzwy(), yzwz(), yzx(), yzxw(), yzxx(), yzxy(), yzxz(), yzy(), yzyw(), yzyx(), yzyy(), yzyz(), yzz(), yzzw(), yzzx(), yzzy(), yzzz(), zwwy(), zwxy(), zwy(), zwyw(), zwyx(), zwyy(), zwyz(), zwzy(), zxwy(), zxxy(), zxy(), zxyw(), zxyx(), zxyy(), zxyz(), zxzy(), zy(), zyw(), zyww(), zywx(), zywy(), zywz(), zyx(), zyxw(), zyxx(), zyxy(), zyxz(), zyy(), zyyw(), zyyx(), zyyy(), zyyz(), zyz(), zyzw(), zyzx(), zyzy(), zyzz(), zzwy(), zzxy(), zzy(), zzyw(), zzyx(), zzyy(), zzyz(), and zzzy().
z
float G3D::Vector4::z
Definition at line 74 of file Vector4.h.
Referenced by G3D::abs(), G3D::all(), G3D::any(), clamp(), deserialize(), G3D::AnyVal::deserialize(), dot(), debug_commandscript::HandleDebugPlayCinematicCommand(), isFinite(), isZero(), max(), min(), operator!=(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator=(), operator==(), readCamera(), serialize(), set(), G3D::sign(), squaredLength(), sum(), toAny(), toString(), G3D::CoordinateFrame::toWorldSpace(), TranslateLocation(), Vector4(), G3D::Vector4int8::Vector4int8(), G3D::BinaryOutput::writeVector4(), wwwz(), wwxz(), wwyz(), wwz(), wwzw(), wwzx(), wwzy(), wwzz(), wxwz(), wxxz(), wxyz(), wxz(), wxzw(), wxzx(), wxzy(), wxzz(), wywz(), wyxz(), wyyz(), wyz(), wyzw(), wyzx(), wyzy(), wyzz(), wz(), wzw(), wzww(), wzwx(), wzwy(), wzwz(), wzx(), wzxw(), wzxx(), wzxy(), wzxz(), wzy(), wzyw(), wzyx(), wzyy(), wzyz(), wzz(), wzzw(), wzzx(), wzzy(), wzzz(), xwwz(), xwxz(), xwyz(), xwz(), xwzw(), xwzx(), xwzy(), xwzz(), xxwz(), xxxz(), xxyz(), xxz(), xxzw(), xxzx(), xxzy(), xxzz(), xywz(), xyxz(), xyyz(), xyz(), xyzw(), xyzx(), xyzy(), xyzz(), xz(), xzw(), xzww(), xzwx(), xzwy(), xzwz(), xzx(), xzxw(), xzxx(), xzxy(), xzxz(), xzy(), xzyw(), xzyx(), xzyy(), xzyz(), xzz(), xzzw(), xzzx(), xzzy(), xzzz(), ywwz(), ywxz(), ywyz(), ywz(), ywzw(), ywzx(), ywzy(), ywzz(), yxwz(), yxxz(), yxyz(), yxz(), yxzw(), yxzx(), yxzy(), yxzz(), yywz(), yyxz(), yyyz(), yyz(), yyzw(), yyzx(), yyzy(), yyzz(), yz(), yzw(), yzww(), yzwx(), yzwy(), yzwz(), yzx(), yzxw(), yzxx(), yzxy(), yzxz(), yzy(), yzyw(), yzyx(), yzyy(), yzyz(), yzz(), yzzw(), yzzx(), yzzy(), yzzz(), zw(), zww(), zwww(), zwwx(), zwwy(), zwwz(), zwx(), zwxw(), zwxx(), zwxy(), zwxz(), zwy(), zwyw(), zwyx(), zwyy(), zwyz(), zwz(), zwzw(), zwzx(), zwzy(), zwzz(), zx(), zxw(), zxww(), zxwx(), zxwy(), zxwz(), zxx(), zxxw(), zxxx(), zxxy(), zxxz(), zxy(), zxyw(), zxyx(), zxyy(), zxyz(), zxz(), zxzw(), zxzx(), zxzy(), zxzz(), zy(), zyw(), zyww(), zywx(), zywy(), zywz(), zyx(), zyxw(), zyxx(), zyxy(), zyxz(), zyy(), zyyw(), zyyx(), zyyy(), zyyz(), zyz(), zyzw(), zyzx(), zyzy(), zyzz(), zz(), zzw(), zzww(), zzwx(), zzwy(), zzwz(), zzx(), zzxw(), zzxx(), zzxy(), zzxz(), zzy(), zzyw(), zzyx(), zzyy(), zzyz(), zzz(), zzzw(), zzzx(), zzzy(), and zzzz().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/Vector4.h
deps/g3dlite/source/Vector4.cpp