Azerotcore-wotlk: deps/SFMT/SFMT-alti.h File Reference
SFMT-alti.h File Reference
SIMD oriented Fast Mersenne Twister(SFMT) pseudorandom number generator.
Macros
#define SFMT_ALTI_H
#define SFMT_ALTI_SWAP {4, 5, 6, 7, 0, 1, 2, 3, 12, 13, 14, 15, 8, 9, 10, 11}
Functions
static vector unsigned int vec_recursion (vector unsigned int a, vector unsigned int b, vector unsigned int c, vector unsigned int d)
void sfmt_gen_rand_all (sfmt_t *sfmt)
static void gen_rand_array (sfmt_t *sfmt, w128_t *array, int size)
static void swap (w128_t *array, int size)
Detailed Description
SIMD oriented Fast Mersenne Twister(SFMT) pseudorandom number generator.
Author
Mutsuo Saito (Hiroshima University)
Makoto Matsumoto (Hiroshima University)
Copyright (C) 2007 Mutsuo Saito, Makoto Matsumoto and Hiroshima University. All rights reserved.
The new BSD License is applied to this software. see LICENSE.txt
Definition in file SFMT-alti.h.
Macro Definition Documentation
SFMT_ALTI_H
#define SFMT_ALTI_H
Definition at line 19 of file SFMT-alti.h.
SFMT_ALTI_SWAP
#define SFMT_ALTI_SWAP {4, 5, 6, 7, 0, 1, 2, 3, 12, 13, 14, 15, 8, 9, 10, 11}
Definition at line 137 of file SFMT-alti.h.
Function Documentation
gen_rand_array()
static void gen_rand_array (sfmt_t * sfmt, w128_t * array, int size) inline static
This function fills the user-specified array with pseudorandom integers.
Parameters
array an 128-bit array to be filled by pseudorandom numbers.
size number of 128-bit pesudorandom numbers to be generated.
Definition at line 95 of file SFMT-alti.h.
{
     int i, j;
     vector unsigned int r, r1, r2;
     r1 = sfmt->state[N - 2].s;
     r2 = sfmt->state[N - 1].s;
     for (i = 0; i < N - POS1; i++) {
     r = vec_recursion(sfmt->state[i].s, sfmt->state[i + POS1].s, r1, r2);
     array[i].s = r;
     r1 = r2;
     r2 = r;
     }
     for (; i < N; i++) {
     r = vec_recursion(sfmt->state[i].s, array[i + POS1 - N].s, r1, r2);
     array[i].s = r;
     r1 = r2;
     r2 = r;
     }
     /* main loop */
     for (; i < size - N; i++) {
     r = vec_recursion(array[i - N].s, array[i + POS1 - N].s, r1, r2);
     array[i].s = r;
     r1 = r2;
     r2 = r;
     }
     for (j = 0; j < 2 * N - size; j++) {
     sfmt->state[j].s = array[j + size - N].s;
     }
     for (; i < size; i++) {
     r = vec_recursion(array[i - N].s, array[i + POS1 - N].s, r1, r2);
     array[i].s = r;
     sfmt->state[j++].s = r;
     r1 = r2;
     r2 = r;
     }
 }
References array, SFMT_T::state, and vec_recursion().
sfmt_gen_rand_all()
void sfmt_gen_rand_all (sfmt_t * sfmt)
This function fills the internal state array with pseudorandom integers.
Definition at line 68 of file SFMT-alti.h.
{
     int i;
     vector unsigned int r, r1, r2;
     r1 = sfmt->state[N - 2].s;
     r2 = sfmt->state[N - 1].s;
     for (i = 0; i < N - POS1; i++) {
     r = vec_recursion(sfmt->state[i].s, sfmt->state[i + POS1].s, r1, r2);
     sfmt->state[i].s = r;
     r1 = r2;
     r2 = r;
     }
     for (; i < N; i++) {
     r = vec_recursion(sfmt->state[i].s, sfmt->state[i + POS1 - N].s, r1, r2);
     sfmt->state[i].s = r;
     r1 = r2;
     r2 = r;
     }
 }
References SFMT_T::state, and vec_recursion().
swap()
static void swap (w128_t * array, int size) inline static
This function swaps high and low 32-bit of 64-bit integers in user specified array.
Parameters
array an 128-bit array to be swaped.
size size of 128-bit array.
Definition at line 146 of file SFMT-alti.h.
{
     int i;
     const vector unsigned char perm = SFMT_ALTI_SWAP;
     for (i = 0; i < size; i++) {
     array[i].s = vec_perm(array[i].s, (vector unsigned int)perm, perm);
     }
 }
References array, and SFMT_ALTI_SWAP.
Referenced by Guild::_DoItemsMove(), Player::CanBankItem(), ScriptMgr::CanEquipItem(), Player::CanEquipItem(), Player::CanEquipNewItem(), Guild::PlayerMoveItemData::CanStore(), Guild::BankMoveItemData::CanStore(), Guild::MoveItemData::CanStore(), Player::CanStoreItem(), Player::CanStoreItem_InSpecificSlot(), ScriptMgr::CanUnequipItem(), Player::CanUnequipItem(), compare_bin(), ByteConverter::convert(), Acore::Containers::EraseIf(), ExtractSingleWmo(), detail::fallback_uintptr::fallback_uintptr(), Player::FindEquipSlot(), BIH::intersectRay(), Map2ZoneCoordinates(), my_strnncollsp_8bit_bin(), my_strnncollsp_latin1_de(), my_strnncollsp_simple(), my_strnncollsp_utf8(), Player::RemoveItem(), sfmt_fill_array64(), G3D::Array< T, MIN_ELEMENTS >::swap(), BattlegroundMgr::Update(), and Zone2MapCoordinates().
vec_recursion()
static vector unsigned int vec_recursion (vector unsigned int a, vector unsigned int b, vector unsigned int c, vector unsigned int d) inline static
This function represents the recursion formula in AltiVec and BIG ENDIAN.
Parameters
a a 128-bit part of the interal state array
b a 128-bit part of the interal state array
c a 128-bit part of the interal state array
d a 128-bit part of the interal state array
Returns
output
Definition at line 34 of file SFMT-alti.h.
{
     const vector unsigned int sl1 = SFMT_ALTI_SL1;
     const vector unsigned int sr1 = SFMT_ALTI_SR1;
 #ifdef ONLY64
     const vector unsigned int mask = SFMT_ALTI_MSK64;
     const vector unsigned char perm_sl = SFMT_ALTI_SL2_PERM64;
     const vector unsigned char perm_sr = SFMT_ALTI_SR2_PERM64;
 #else
     const vector unsigned int mask = SFMT_ALTI_MSK;
     const vector unsigned char perm_sl = SFMT_ALTI_SL2_PERM;
     const vector unsigned char perm_sr = SFMT_ALTI_SR2_PERM;
 #endif
     vector unsigned int v, w, x, y, z;
     x = vec_perm(a, (vector unsigned int)perm_sl, perm_sl);
     v = a;
     y = vec_sr(b, sr1);
     z = vec_perm(c, (vector unsigned int)perm_sr, perm_sr);
     w = vec_sl(d, sl1);
     z = vec_xor(z, w);
     y = vec_and(y, mask);
     v = vec_xor(v, x);
     z = vec_xor(z, y);
     z = vec_xor(z, v);
     return z;
 }
References mpq::a, b, mpq::c, mpq::d, SFMT_ALTI_MSK, SFMT_ALTI_MSK64, SFMT_ALTI_SL1, SFMT_ALTI_SL2_PERM, SFMT_ALTI_SL2_PERM64, SFMT_ALTI_SR1, SFMT_ALTI_SR2_PERM, SFMT_ALTI_SR2_PERM64, G3D::x, G3D::y, and G3D::z.
Referenced by gen_rand_array(), and sfmt_gen_rand_all().