Azerotcore-wotlk: npc_tooga::npc_toogaAI Struct Reference
npc_tooga::npc_toogaAI Struct Reference
Public Member Functions
npc_toogaAI (Creature *creature)
void Reset () override
void MoveInLineOfSight (Unit *who) override
void MovementInform (uint32 MotionType, uint32 PointId) override
void UpdateFollowerAI (uint32 Diff) override
Public Member Functions inherited from FollowerAI
FollowerAI (Creature *creature)
~FollowerAI () override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void JustDied (Unit *) override
void JustRespawned () override
void UpdateAI (uint32) override
void StartFollow (Player *player, uint32 factionForFollower=0, const Quest *quest=nullptr)
void SetFollowPaused (bool bPaused)
void SetFollowComplete (bool bWithEndEvent=false)
bool HasFollowState (uint32 uiFollowState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
uint32 CheckSpeechTimer
uint32 PostEventTimer
uint32 PhasePostEvent
ObjectGuid TortaGUID
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from FollowerAI
Player * GetLeaderForFollower ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 435 of file zone_tanaris.cpp.
Constructor & Destructor Documentation
npc_toogaAI()
npc_tooga::npc_toogaAI::npc_toogaAI (Creature * creature) inline
Definition at line 437 of file zone_tanaris.cpp.
 : FollowerAI(creature) { }
Member Function Documentation
MoveInLineOfSight()
void npc_tooga::npc_toogaAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from FollowerAI.
Definition at line 454 of file zone_tanaris.cpp.
         {
             FollowerAI::MoveInLineOfSight(who);
             if (!me->GetVictim() && !HasFollowState(STATE_FOLLOW_COMPLETE | STATE_FOLLOW_POSTEVENT) && who->GetEntry() == NPC_TORTA)
             {
                 if (me->IsWithinDistInMap(who, INTERACTION_DISTANCE))
                 {
                     Player* player = GetLeaderForFollower();
                     if (player && player->GetQuestStatus(QUEST_TOOGA) == QUEST_STATUS_INCOMPLETE)
                         player->GroupEventHappens(QUEST_TOOGA, me);
                     TortaGUID = who->GetGUID();
                     SetFollowComplete(true);
                 }
             }
         }
References Object::GetEntry(), Object::GetGUID(), FollowerAI::GetLeaderForFollower(), Player::GetQuestStatus(), Unit::GetVictim(), Player::GroupEventHappens(), FollowerAI::HasFollowState(), INTERACTION_DISTANCE, WorldObject::IsWithinDistInMap(), ScriptedAI::me, FollowerAI::MoveInLineOfSight(), NPC_TORTA, QUEST_STATUS_INCOMPLETE, QUEST_TOOGA, FollowerAI::SetFollowComplete(), STATE_FOLLOW_COMPLETE, STATE_FOLLOW_POSTEVENT, and TortaGUID.
MovementInform()
void npc_tooga::npc_toogaAI::MovementInform (uint32 MotionType, uint32 PointId) inline override virtual
Reimplemented from FollowerAI.
Definition at line 473 of file zone_tanaris.cpp.
         {
             FollowerAI::MovementInform(MotionType, PointId);
             if (MotionType != POINT_MOTION_TYPE)
                 return;
             if (PointId == POINT_ID_TO_WATER)
                 SetFollowComplete();
         }
References FollowerAI::MovementInform(), POINT_ID_TO_WATER, POINT_MOTION_TYPE, and FollowerAI::SetFollowComplete().
Reset()
void npc_tooga::npc_toogaAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 445 of file zone_tanaris.cpp.
         {
             CheckSpeechTimer = 2500;
             PostEventTimer = 1000;
             PhasePostEvent = 0;
             TortaGUID.Clear();
         }
References CheckSpeechTimer, ObjectGuid::Clear(), PhasePostEvent, PostEventTimer, and TortaGUID.
UpdateFollowerAI()
void npc_tooga::npc_toogaAI::UpdateFollowerAI (uint32 Diff) inline override virtual
Reimplemented from FollowerAI.
Definition at line 484 of file zone_tanaris.cpp.
         {
             if (!UpdateVictim())
             {
                 //we are doing the post-event, or...
                 if (HasFollowState(STATE_FOLLOW_POSTEVENT))
                 {
                     if (PostEventTimer <= Diff)
                     {
                         PostEventTimer = 5000;
                         Creature* torta = ObjectAccessor::GetCreature(*me, TortaGUID);
                         if (!torta || !torta->IsAlive())
{
                             //something happened, so just complete
                             SetFollowComplete();
                             return;
                         }
                         switch (PhasePostEvent)
{
                             case 1:
                                 Talk(SAY_TOOG_POST_1);
                                 break;
                             case 2:
                                 torta->AI()->Talk(SAY_TORT_POST_2);
                                 break;
                             case 3:
                                 Talk(SAY_TOOG_POST_3);
                                 break;
                             case 4:
                                 torta->AI()->Talk(SAY_TORT_POST_4);
                                 break;
                             case 5:
                                 Talk(SAY_TOOG_POST_5);
                                 break;
                             case 6:
                                 torta->AI()->Talk(SAY_TORT_POST_6);
                                 me->GetMotionMaster()->MovePoint(POINT_ID_TO_WATER, ToWaterLoc);
                                 break;
                         }
                         ++PhasePostEvent;
                     }
                     else
                         PostEventTimer -= Diff;
                 }
                 //...we are doing regular speech check
                 else if (HasFollowState(STATE_FOLLOW_INPROGRESS))
                 {
                     if (CheckSpeechTimer <= Diff)
                     {
                         CheckSpeechTimer = 5000;
                         if (urand(0, 9) > 8)
                             Talk(SAY_TOOG_WORRIED);
                     }
                     else
                         CheckSpeechTimer -= Diff;
                 }
                 return;
             }
             DoMeleeAttackIfReady();
         }
References Creature::AI(), CheckSpeechTimer, UnitAI::DoMeleeAttackIfReady(), ObjectAccessor::GetCreature(), Unit::GetMotionMaster(), FollowerAI::HasFollowState(), Unit::IsAlive(), ScriptedAI::me, MotionMaster::MovePoint(), PhasePostEvent, POINT_ID_TO_WATER, PostEventTimer, SAY_TOOG_POST_1, SAY_TOOG_POST_3, SAY_TOOG_POST_5, SAY_TOOG_WORRIED, SAY_TORT_POST_2, SAY_TORT_POST_4, SAY_TORT_POST_6, FollowerAI::SetFollowComplete(), STATE_FOLLOW_INPROGRESS, STATE_FOLLOW_POSTEVENT, CreatureAI::Talk(), TortaGUID, ToWaterLoc, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
CheckSpeechTimer
uint32 npc_tooga::npc_toogaAI::CheckSpeechTimer
Definition at line 439 of file zone_tanaris.cpp.
Referenced by Reset(), and UpdateFollowerAI().
PhasePostEvent
uint32 npc_tooga::npc_toogaAI::PhasePostEvent
Definition at line 441 of file zone_tanaris.cpp.
Referenced by Reset(), and UpdateFollowerAI().
PostEventTimer
uint32 npc_tooga::npc_toogaAI::PostEventTimer
Definition at line 440 of file zone_tanaris.cpp.
Referenced by Reset(), and UpdateFollowerAI().
TortaGUID
ObjectGuid npc_tooga::npc_toogaAI::TortaGUID
Definition at line 443 of file zone_tanaris.cpp.
Referenced by MoveInLineOfSight(), Reset(), and UpdateFollowerAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/zone_tanaris.cpp