Azerotcore-wotlk: npc_tirion_fordring_tft::npc_tirion_fordringAI Struct Reference
npc_tirion_fordring_tft::npc_tirion_fordringAI Struct Reference
Public Member Functions
npc_tirion_fordringAI (Creature *creature)
void Reset () override
void MovementInform (uint32 type, uint32 id) override
void DoAction (int32 action) override
void SpellHit (Unit *, SpellInfo const *spell) override
void JustReachedHome () override
void sGossipSelect (Player *, uint32 sender, uint32 action) override
void UpdateAI (uint32 diff) override
void EnterEvadeMode () override
bool CanAIAttack (Unit const *target) const override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
EventMap _events
InstanceScript * _instance
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1281 of file boss_the_lich_king.cpp.
Constructor & Destructor Documentation
npc_tirion_fordringAI()
npc_tirion_fordring_tft::npc_tirion_fordringAI::npc_tirion_fordringAI (Creature * creature) inline
Definition at line 1283 of file boss_the_lich_king.cpp.
 : ScriptedAI(creature), _instance(creature->GetInstanceScript()) {}
Member Function Documentation
CanAIAttack()
bool npc_tirion_fordring_tft::npc_tirion_fordringAI::CanAIAttack (Unit const * target) const inline override virtual
Reimplemented from UnitAI.
Definition at line 1655 of file boss_the_lich_king.cpp.
         {
             return target->GetEntry() == NPC_THE_LICH_KING;
         }
References Object::GetEntry(), and NPC_THE_LICH_KING.
DoAction()
void npc_tirion_fordring_tft::npc_tirion_fordringAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 1320 of file boss_the_lich_king.cpp.
         {
             switch (action)
             {
                 case ACTION_OUTRO:
                     _events.ScheduleEvent(EVENT_OUTRO_LK_TALK_1, 2600);
                     _events.ScheduleEvent(EVENT_OUTRO_LK_EMOTE_TALK, 6600);
                     _events.ScheduleEvent(EVENT_OUTRO_LK_EMOTE_TALK, 17600);
                     _events.ScheduleEvent(EVENT_OUTRO_LK_TALK_2, 30000);
                     _events.ScheduleEvent(EVENT_OUTRO_LK_TALK_3, 39000);
                     _events.ScheduleEvent(EVENT_OUTRO_LK_EMOTE_CAST_SHOUT, 50000);
                     _events.ScheduleEvent(EVENT_OUTRO_LK_EMOTE_TALK, 54000);
                     _events.ScheduleEvent(EVENT_OUTRO_LK_MOVE_CENTER, 65000);
                     break;
                 case ACTION_BREAK_FROSTMOURNE:
                     _events.ScheduleEvent(EVENT_OUTRO_LK_TALK_6, 2500);
                     _events.ScheduleEvent(EVENT_OUTRO_SOUL_BARRAGE, 6500);
                     break;
             }
         }
References _events, ACTION_BREAK_FROSTMOURNE, ACTION_OUTRO, EVENT_OUTRO_LK_EMOTE_CAST_SHOUT, EVENT_OUTRO_LK_EMOTE_TALK, EVENT_OUTRO_LK_MOVE_CENTER, EVENT_OUTRO_LK_TALK_1, EVENT_OUTRO_LK_TALK_2, EVENT_OUTRO_LK_TALK_3, EVENT_OUTRO_LK_TALK_6, EVENT_OUTRO_SOUL_BARRAGE, and EventMap::ScheduleEvent().
EnterEvadeMode()
void npc_tirion_fordring_tft::npc_tirion_fordringAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 1639 of file boss_the_lich_king.cpp.
         {
             if (!me->IsAlive())
                 return;
             if (Creature* theLichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_THE_LICH_KING)))
                 if (theLichKing->IsInEvadeMode())
                 {
                     ScriptedAI::EnterEvadeMode();
                     return;
                 }
             me->DeleteThreatList();
             me->CombatStop(false);
         }
References _instance, Unit::CombatStop(), DATA_THE_LICH_KING, Unit::DeleteThreatList(), CreatureAI::EnterEvadeMode(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Unit::IsAlive(), and ScriptedAI::me.
JustReachedHome()
void npc_tirion_fordring_tft::npc_tirion_fordringAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 1357 of file boss_the_lich_king.cpp.
         {
             ScriptedAI::JustReachedHome();
             if (!(_instance->GetBossState(DATA_THE_LICH_KING) == DONE || (me->GetMap()->IsHeroic() && !_instance->GetData(DATA_LK_HC_AVAILABLE))))
                 me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
             me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
         }
References _instance, DATA_LK_HC_AVAILABLE, DATA_THE_LICH_KING, DONE, EMOTE_ONESHOT_NONE, InstanceScript::GetBossState(), ZoneScript::GetData(), WorldObject::GetMap(), Map::IsHeroic(), CreatureAI::JustReachedHome(), ScriptedAI::me, Object::SetFlag(), Object::SetUInt32Value(), UNIT_NPC_EMOTESTATE, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
MovementInform()
void npc_tirion_fordring_tft::npc_tirion_fordringAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1293 of file boss_the_lich_king.cpp.
         {
             if (type != POINT_MOTION_TYPE)
                 return;
             switch (id)
             {
                 case POINT_TIRION_INTRO:
                     if (Creature* theLichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_THE_LICH_KING)))
                     {
                         if (!theLichKing->IsAlive() || !theLichKing->IsVisible())
                             break;
                         me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_READY2H);
                         theLichKing->SetStandState(UNIT_STAND_STATE_STAND);
                         theLichKing->SetSheath(SHEATH_STATE_MELEE);
                         theLichKing->RemoveAurasDueToSpell(SPELL_EMOTE_SIT_NO_SHEATH);
                         theLichKing->AI()->Talk(SAY_LK_INTRO_1);
                         me->GetMap()->SetZoneMusic(AREA_THE_FROZEN_THRONE, MUSIC_FROZEN_THRONE);
                         _events.ScheduleEvent(EVENT_INTRO_LK_MOVE, 3000);
                     }
                     break;
                 case POINT_TIRION_OUTRO:
                     _events.ScheduleEvent(EVENT_OUTRO_FORDRING_JUMP, 1);
                     break;
             }
         }
References _events, _instance, AREA_THE_FROZEN_THRONE, DATA_THE_LICH_KING, EMOTE_STATE_READY2H, EVENT_INTRO_LK_MOVE, EVENT_OUTRO_FORDRING_JUMP, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), WorldObject::GetMap(), ScriptedAI::me, MUSIC_FROZEN_THRONE, POINT_MOTION_TYPE, POINT_TIRION_INTRO, POINT_TIRION_OUTRO, SAY_LK_INTRO_1, EventMap::ScheduleEvent(), Object::SetUInt32Value(), Map::SetZoneMusic(), SHEATH_STATE_MELEE, SPELL_EMOTE_SIT_NO_SHEATH, UNIT_NPC_EMOTESTATE, and UNIT_STAND_STATE_STAND.
Reset()
void npc_tirion_fordring_tft::npc_tirion_fordringAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1285 of file boss_the_lich_king.cpp.
         {
             _events.Reset();
             if (_instance->GetBossState(DATA_THE_LICH_KING) == DONE || (me->GetMap()->IsHeroic() && !_instance->GetData(DATA_LK_HC_AVAILABLE)))
                 me->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
             me->SetReactState(REACT_PASSIVE);
         }
References _events, _instance, DATA_LK_HC_AVAILABLE, DATA_THE_LICH_KING, DONE, InstanceScript::GetBossState(), ZoneScript::GetData(), WorldObject::GetMap(), Map::IsHeroic(), ScriptedAI::me, REACT_PASSIVE, Object::RemoveFlag(), EventMap::Reset(), Creature::SetReactState(), UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
sGossipSelect()
void npc_tirion_fordring_tft::npc_tirion_fordringAI::sGossipSelect (Player * , uint32 sender, uint32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 1365 of file boss_the_lich_king.cpp.
         {
             Creature* theLichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_THE_LICH_KING));
             if (me->GetCreatureTemplate()->GossipMenuId == sender && !action && me->HasFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP) && theLichKing && !theLichKing->IsInEvadeMode())
             {
                 if (me->GetMap()->IsHeroic() && !_instance->GetData(DATA_LK_HC_AVAILABLE))
                     return;
                 me->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
                 me->SetWalk(true);
                 me->GetMotionMaster()->MovePoint(POINT_TIRION_INTRO, TirionIntro);
             }
         }
References _instance, DATA_LK_HC_AVAILABLE, DATA_THE_LICH_KING, ObjectAccessor::GetCreature(), Creature::GetCreatureTemplate(), ZoneScript::GetData(), InstanceScript::GetGuidData(), WorldObject::GetMap(), Unit::GetMotionMaster(), CreatureTemplate::GossipMenuId, Object::HasFlag(), Map::IsHeroic(), Creature::IsInEvadeMode(), ScriptedAI::me, MotionMaster::MovePoint(), POINT_TIRION_INTRO, Object::RemoveFlag(), Creature::SetWalk(), TirionIntro, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
SpellHit()
void npc_tirion_fordring_tft::npc_tirion_fordringAI::SpellHit (Unit * , SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1341 of file boss_the_lich_king.cpp.
         {
             if (spell->Id == SPELL_ICE_LOCK)
             {
                 me->StopMoving();
                 me->GetMotionMaster()->Clear(true);
                 me->SetFacingTo(3.085098f);
             }
             else if (spell->Id == SPELL_BROKEN_FROSTMOURNE_KNOCK)
             {
                 // remove glow on ashbringer and tirion
                 me->RemoveAllAuras();
                 SetEquipmentSlots(true);
             }
         }
References MotionMaster::Clear(), Unit::GetMotionMaster(), SpellInfo::Id, ScriptedAI::me, Unit::RemoveAllAuras(), ScriptedAI::SetEquipmentSlots(), Unit::SetFacingTo(), SPELL_BROKEN_FROSTMOURNE_KNOCK, SPELL_ICE_LOCK, and Unit::StopMoving().
UpdateAI()
void npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1383 of file boss_the_lich_king.cpp.
         {
             UpdateVictim();
             _events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (_events.ExecuteEvent())
             {
                 case EVENT_INTRO_LK_MOVE:
                     if (Creature* theLichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_THE_LICH_KING)))
                     {
                         Movement::PointsArray path;
                         path.push_back(G3D::Vector3(theLichKing->GetPositionX(), theLichKing->GetPositionY(), theLichKing->GetPositionZ()));
                         for (uint8 i = 0; i < 3; ++i)
                             path.push_back(G3D::Vector3(LichKingIntro[i].GetPositionX(), LichKingIntro[i].GetPositionY(), LichKingIntro[i].GetPositionZ()));
                         theLichKing->SetWalk(true);
                         theLichKing->GetMotionMaster()->MoveSplinePath(&path);
                         _events.ScheduleEvent(EVENT_INTRO_FORDRING_TALK_1, 11000);
                     }
                     break;
                 case EVENT_INTRO_LK_TALK_1:
                     if (Creature* theLichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_THE_LICH_KING)))
                     {
                         theLichKing->AI()->Talk(SAY_LK_INTRO_2);
                         theLichKing->HandleEmoteCommand(EMOTE_ONESHOT_TALK_NO_SHEATHE);
                         _events.ScheduleEvent(EVENT_INTRO_LK_EMOTE_CAST_SHOUT, 7000);
                         _events.ScheduleEvent(EVENT_INTRO_LK_EMOTE_1, 13000);
                         _events.ScheduleEvent(EVENT_INTRO_LK_EMOTE_CAST_SHOUT, 18000);
                         _events.ScheduleEvent(EVENT_INTRO_LK_CAST_FREEZE, 31000);
                     }
                     break;
                 case EVENT_INTRO_LK_EMOTE_CAST_SHOUT:
                     if (Creature* theLichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_THE_LICH_KING)))
                         theLichKing->CastSpell(theLichKing, SPELL_EMOTE_SHOUT_NO_SHEATH, false);
                     break;
                 case EVENT_INTRO_LK_EMOTE_1:
                     if (Creature* theLichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_THE_LICH_KING)))
                         theLichKing->HandleEmoteCommand(EMOTE_ONESHOT_POINT_NO_SHEATHE);
                     break;
                 case EVENT_INTRO_LK_CAST_FREEZE:
                     if (Creature* theLichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_THE_LICH_KING)))
                     {
                         theLichKing->AI()->Talk(SAY_LK_INTRO_3);
                         theLichKing->CastSpell((Unit*)nullptr, SPELL_ICE_LOCK, false);
                         _events.ScheduleEvent(EVENT_INTRO_FINISH, 1000);
                     }
                     break;
                 case EVENT_INTRO_FORDRING_TALK_1:
                     {
                         Talk(SAY_TIRION_INTRO_1);
                         _events.ScheduleEvent(EVENT_INTRO_LK_TALK_1, 9000);
                         _events.ScheduleEvent(EVENT_INTRO_FORDRING_TALK_2, 34000);
                     }
                     break;
                 case EVENT_INTRO_FORDRING_TALK_2:
                     {
                         Talk(SAY_TIRION_INTRO_2);
                         _events.ScheduleEvent(EVENT_INTRO_FORDRING_EMOTE_1, 2000);
                         _events.ScheduleEvent(EVENT_INTRO_FORDRING_CHARGE, 5000);
                     }
                     break;
                 case EVENT_INTRO_FORDRING_EMOTE_1:
                     me->HandleEmoteCommand(EMOTE_ONESHOT_POINT_NO_SHEATHE);
                     break;
                 case EVENT_INTRO_FORDRING_CHARGE:
                     me->SetWalk(false);
                     me->GetMotionMaster()->MovePoint(0, TirionCharge);
                     break;
                 case EVENT_INTRO_FINISH:
                     if (Creature* theLichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_THE_LICH_KING)))
                     {
                         theLichKing->SetWalk(false);
                         theLichKing->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                         theLichKing->SetReactState(REACT_AGGRESSIVE);
                         theLichKing->SetInCombatWithZone();
                         if (!theLichKing->IsInCombat())
                             theLichKing->AI()->EnterEvadeMode();
                     }
                     break;
                 case EVENT_OUTRO_LK_TALK_1:
                     if (Creature* theLichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_THE_LICH_KING)))
                     {
                         theLichKing->AI()->Talk(SAY_LK_OUTRO_1);
                         theLichKing->CastSpell((Unit*)nullptr, SPELL_FURY_OF_FROSTMOURNE_NO_REZ, true);
                         Map::PlayerList const& pl = me->GetMap()->GetPlayers();
                         for (Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr)
                             if (Player* p = itr->GetSource())
                                 if (p->IsAlive())
                                     Unit::Kill(me, p);
                     }
                     break;
                 case EVENT_OUTRO_LK_TALK_2:
                     if (Creature* theLichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_THE_LICH_KING)))
                     {
                         theLichKing->AI()->Talk(SAY_LK_OUTRO_2);
                         theLichKing->CastSpell((Unit*)nullptr, SPELL_EMOTE_QUESTION_NO_SHEATH, false);
                     }
                     break;
                 case EVENT_OUTRO_LK_EMOTE_TALK:
                     if (Creature* theLichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_THE_LICH_KING)))
                         theLichKing->HandleEmoteCommand(EMOTE_ONESHOT_TALK_NO_SHEATHE);
                     break;
                 case EVENT_OUTRO_LK_TALK_3:
                     if (Creature* theLichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_THE_LICH_KING)))
                     {
                         theLichKing->SetFacingToObject(me);
                         theLichKing->AI()->Talk(SAY_LK_OUTRO_3);
                     }
                     break;
                 case EVENT_OUTRO_LK_MOVE_CENTER:
                     if (Creature* theLichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_THE_LICH_KING)))
                     {
                         theLichKing->GetMotionMaster()->MovePoint(0, CenterPosition);
                         uint32 travelTime = 1000 * theLichKing->GetExactDist(&CenterPosition) / theLichKing->GetSpeed(MOVE_WALK) + 1000;
                         _events.ScheduleEvent(EVENT_OUTRO_LK_TALK_4, 1 + travelTime);
                         _events.ScheduleEvent(EVENT_OUTRO_LK_RAISE_DEAD, 1000 + travelTime);
                         _events.ScheduleEvent(EVENT_OUTRO_LK_TALK_5, 29000 + travelTime);
                     }
                     break;
                 case EVENT_OUTRO_LK_TALK_4:
                     if (Creature* theLichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_THE_LICH_KING)))
                     {
                         theLichKing->SetFacingTo(0.01745329f);
                         theLichKing->AI()->Talk(SAY_LK_OUTRO_4);
                     }
                     break;
                 case EVENT_OUTRO_LK_RAISE_DEAD:
                     if (Creature* theLichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_THE_LICH_KING)))
                     {
                         theLichKing->CastSpell((Unit*)nullptr, SPELL_RAISE_DEAD, false);
                         theLichKing->ClearUnitState(UNIT_STATE_CASTING);
                         me->GetMap()->SetZoneMusic(AREA_THE_FROZEN_THRONE, MUSIC_FINAL);
                     }
                     break;
                 case EVENT_OUTRO_LK_TALK_5:
                     if (Creature* theLichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_THE_LICH_KING)))
                     {
                         theLichKing->AI()->Talk(SAY_LK_OUTRO_5);
                         _events.ScheduleEvent(EVENT_OUTRO_FORDRING_TALK_1, 7000);
                         _events.ScheduleEvent(EVENT_OUTRO_FORDRING_BLESS, 18000);
                         _events.ScheduleEvent(EVENT_OUTRO_FORDRING_REMOVE_ICE, 23000);
                         _events.ScheduleEvent(EVENT_OUTRO_FORDRING_MOVE_1, 25000);
                     }
                     break;
                 case EVENT_OUTRO_LK_TALK_6:
                     if (Creature* theLichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_THE_LICH_KING)))
                     {
                         theLichKing->AI()->Talk(SAY_LK_OUTRO_6);
                         me->SetFacingToObject(theLichKing);
                         theLichKing->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID, EQUIP_UNEQUIP);
                         theLichKing->CastSpell((Unit*)nullptr, SPELL_SUMMON_BROKEN_FROSTMOURNE_3, true);
                         me->GetMap()->SetZoneOverrideLight(AREA_THE_FROZEN_THRONE, LIGHT_SOULSTORM, 10s);
                         me->GetMap()->SetZoneWeather(AREA_THE_FROZEN_THRONE, WEATHER_STATE_BLACKSNOW, 0.5f);
                         _events.ScheduleEvent(EVENT_OUTRO_AFTER_SUMMON_BROKEN_FROSTMOURNE, 1000);
                         _events.ScheduleEvent(EVENT_OUTRO_KNOCK_BACK, 3000);
                         break;
                     }
                     break;
                 case EVENT_OUTRO_AFTER_SUMMON_BROKEN_FROSTMOURNE:
                     if (Creature* frostmourne = me->FindNearestCreature(NPC_FROSTMOURNE_TRIGGER, 50.0f))
                         frostmourne->CastSpell((Unit*)nullptr, SPELL_BROKEN_FROSTMOURNE, true);
                     break;
                 case EVENT_OUTRO_KNOCK_BACK:
                     if (Creature* frostmourne = me->FindNearestCreature(NPC_FROSTMOURNE_TRIGGER, 50.0f))
                         frostmourne->CastSpell((Unit*)nullptr, SPELL_BROKEN_FROSTMOURNE_KNOCK, false);
                     break;
                 case EVENT_OUTRO_SOUL_BARRAGE:
                     if (Creature* theLichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_THE_LICH_KING)))
                     {
                         theLichKing->CastSpell((Unit*)nullptr, SPELL_SOUL_BARRAGE, TRIGGERED_IGNORE_CAST_IN_PROGRESS);
                         sCreatureTextMgr->SendSound(theLichKing, SOUND_PAIN, CHAT_MSG_MONSTER_YELL, 0, TEXT_RANGE_NORMAL, TEAM_NEUTRAL, false);
                         theLichKing->SetDisableGravity(true);
                         theLichKing->GetMotionMaster()->MovePoint(0, OutroFlying);
                         _events.ScheduleEvent(EVENT_OUTRO_AFTER_SOUL_BARRAGE, 3000);
                     }
                     break;
                 case EVENT_OUTRO_AFTER_SOUL_BARRAGE:
                     Talk(SAY_TIRION_OUTRO_2);
                     _events.ScheduleEvent(EVENT_OUTRO_SUMMON_TERENAS, 6000);
                     break;
                 case EVENT_OUTRO_SUMMON_TERENAS:
                     if (Creature* frostmourne = me->FindNearestCreature(NPC_FROSTMOURNE_TRIGGER, 50.0f))
                     {
                         frostmourne->CastSpell((Unit*)nullptr, SPELL_SUMMON_TERENAS, false);
                         if (Creature* terenas = me->FindNearestCreature(NPC_TERENAS_MENETHIL_OUTRO, 50.0f))
                             terenas->SetFacingToObject(frostmourne);
                     }
                     _events.ScheduleEvent(EVENT_OUTRO_TERENAS_TALK_1, 2000);
                     _events.ScheduleEvent(EVENT_OUTRO_TERENAS_TALK_2, 14000);
                     break;
                 case EVENT_OUTRO_TERENAS_TALK_1:
                     if (Creature* terenas = me->FindNearestCreature(NPC_TERENAS_MENETHIL_OUTRO, 50.0f))
                         terenas->AI()->Talk(SAY_TERENAS_OUTRO_1);
                     break;
                 case EVENT_OUTRO_TERENAS_TALK_2:
                     if (Creature* terenas = me->FindNearestCreature(NPC_TERENAS_MENETHIL_OUTRO, 50.0f))
                     {
                         terenas->AI()->Talk(SAY_TERENAS_OUTRO_2);
                         terenas->CastSpell((Unit*)nullptr, SPELL_MASS_RESURRECTION, false);
                         if (Creature* lichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_THE_LICH_KING)))
{
                             lichKing->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
                             me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                             me->RemoveAllAuras();
                             SetEquipmentSlots(true);
                             me->Attack(lichKing, true);
                             me->GetMotionMaster()->MovePoint(0, 512.16f, -2120.25f, 840.86f);
                         }
                         _events.ScheduleEvent(EVENT_OUTRO_LK_TALK_7, 7000);
                         _events.ScheduleEvent(EVENT_OUTRO_LK_TALK_8, 17000);
                     }
                     break;
                 case EVENT_OUTRO_LK_TALK_7:
                     if (Creature* theLichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_THE_LICH_KING)))
                         theLichKing->AI()->Talk(SAY_LK_OUTRO_7);
                     break;
                 case EVENT_OUTRO_LK_TALK_8:
                     if (Creature* theLichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_THE_LICH_KING)))
                         theLichKing->AI()->Talk(SAY_LK_OUTRO_8);
                     break;
                 case EVENT_OUTRO_FORDRING_TALK_1:
                     Talk(SAY_TIRION_OUTRO_1);
                     break;
                 case EVENT_OUTRO_FORDRING_BLESS:
                     me->CastSpell(me, SPELL_LIGHTS_BLESSING, false);
                     break;
                 case EVENT_OUTRO_FORDRING_REMOVE_ICE:
                     me->RemoveAurasDueToSpell(SPELL_ICE_LOCK);
                     SetEquipmentSlots(false, EQUIP_ASHBRINGER_GLOWING);
                     if (Creature* lichKing = ObjectAccessor::GetCreature(*me, _instance->GetGuidData(DATA_THE_LICH_KING)))
                     {
                         me->SetFacingToObject(lichKing);
                         me->GetMap()->SetZoneMusic(AREA_THE_FROZEN_THRONE, MUSIC_FINAL);
                     }
                     break;
                 case EVENT_OUTRO_FORDRING_MOVE_1:
                     me->GetMotionMaster()->MovePoint(POINT_TIRION_OUTRO, OutroPosition1);
                     break;
                 case EVENT_OUTRO_FORDRING_JUMP:
                     me->CastSpell((Unit*)nullptr, SPELL_JUMP, false);
                     break;
                 default:
                     break;
             }
             DoMeleeAttackIfReady();
         }
References _events, _instance, AREA_THE_FROZEN_THRONE, Unit::Attack(), MapRefMgr::begin(), Unit::CastSpell(), CenterPosition, CHAT_MSG_MONSTER_YELL, DATA_THE_LICH_KING, diff(), UnitAI::DoMeleeAttackIfReady(), EMOTE_ONESHOT_NONE, EMOTE_ONESHOT_POINT_NO_SHEATHE, EMOTE_ONESHOT_TALK_NO_SHEATHE, MapRefMgr::end(), EQUIP_ASHBRINGER_GLOWING, EQUIP_UNEQUIP, EVENT_INTRO_FINISH, EVENT_INTRO_FORDRING_CHARGE, EVENT_INTRO_FORDRING_EMOTE_1, EVENT_INTRO_FORDRING_TALK_1, EVENT_INTRO_FORDRING_TALK_2, EVENT_INTRO_LK_CAST_FREEZE, EVENT_INTRO_LK_EMOTE_1, EVENT_INTRO_LK_EMOTE_CAST_SHOUT, EVENT_INTRO_LK_MOVE, EVENT_INTRO_LK_TALK_1, EVENT_OUTRO_AFTER_SOUL_BARRAGE, EVENT_OUTRO_AFTER_SUMMON_BROKEN_FROSTMOURNE, EVENT_OUTRO_FORDRING_BLESS, EVENT_OUTRO_FORDRING_JUMP, EVENT_OUTRO_FORDRING_MOVE_1, EVENT_OUTRO_FORDRING_REMOVE_ICE, EVENT_OUTRO_FORDRING_TALK_1, EVENT_OUTRO_KNOCK_BACK, EVENT_OUTRO_LK_EMOTE_TALK, EVENT_OUTRO_LK_MOVE_CENTER, EVENT_OUTRO_LK_RAISE_DEAD, EVENT_OUTRO_LK_TALK_1, EVENT_OUTRO_LK_TALK_2, EVENT_OUTRO_LK_TALK_3, EVENT_OUTRO_LK_TALK_4, EVENT_OUTRO_LK_TALK_5, EVENT_OUTRO_LK_TALK_6, EVENT_OUTRO_LK_TALK_7, EVENT_OUTRO_LK_TALK_8, EVENT_OUTRO_SOUL_BARRAGE, EVENT_OUTRO_SUMMON_TERENAS, EVENT_OUTRO_TERENAS_TALK_1, EVENT_OUTRO_TERENAS_TALK_2, EventMap::ExecuteEvent(), WorldObject::FindNearestCreature(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), WorldObject::GetMap(), Unit::GetMotionMaster(), Map::GetPlayers(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::HandleEmoteCommand(), Unit::HasUnitState(), Unit::Kill(), LichKingIntro, LIGHT_SOULSTORM, ScriptedAI::me, MOVE_WALK, MotionMaster::MovePoint(), MUSIC_FINAL, NPC_FROSTMOURNE_TRIGGER, NPC_TERENAS_MENETHIL_OUTRO, OutroFlying, OutroPosition1, POINT_TIRION_OUTRO, REACT_AGGRESSIVE, Unit::RemoveAllAuras(), Unit::RemoveAurasDueToSpell(), SAY_LK_INTRO_2, SAY_LK_INTRO_3, SAY_LK_OUTRO_1, SAY_LK_OUTRO_2, SAY_LK_OUTRO_3, SAY_LK_OUTRO_4, SAY_LK_OUTRO_5, SAY_LK_OUTRO_6, SAY_LK_OUTRO_7, SAY_LK_OUTRO_8, SAY_TERENAS_OUTRO_1, SAY_TERENAS_OUTRO_2, SAY_TIRION_INTRO_1, SAY_TIRION_INTRO_2, SAY_TIRION_OUTRO_1, SAY_TIRION_OUTRO_2, EventMap::ScheduleEvent(), sCreatureTextMgr, ScriptedAI::SetEquipmentSlots(), Unit::SetFacingToObject(), Object::SetUInt32Value(), Creature::SetWalk(), Map::SetZoneMusic(), Map::SetZoneOverrideLight(), Map::SetZoneWeather(), SOUND_PAIN, SPELL_BROKEN_FROSTMOURNE, SPELL_BROKEN_FROSTMOURNE_KNOCK, SPELL_EMOTE_QUESTION_NO_SHEATH, SPELL_EMOTE_SHOUT_NO_SHEATH, SPELL_FURY_OF_FROSTMOURNE_NO_REZ, SPELL_ICE_LOCK, SPELL_JUMP, SPELL_LIGHTS_BLESSING, SPELL_MASS_RESURRECTION, SPELL_RAISE_DEAD, SPELL_SOUL_BARRAGE, SPELL_SUMMON_BROKEN_FROSTMOURNE_3, SPELL_SUMMON_TERENAS, CreatureAI::Talk(), TEAM_NEUTRAL, TEXT_RANGE_NORMAL, TirionCharge, TRIGGERED_IGNORE_CAST_IN_PROGRESS, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PC, UNIT_NPC_EMOTESTATE, UNIT_STATE_CASTING, UNIT_VIRTUAL_ITEM_SLOT_ID, EventMap::Update(), CreatureAI::UpdateVictim(), and WEATHER_STATE_BLACKSNOW.
Member Data Documentation
_events
EventMap npc_tirion_fordring_tft::npc_tirion_fordringAI::_events private
Definition at line 1661 of file boss_the_lich_king.cpp.
Referenced by DoAction(), MovementInform(), Reset(), and UpdateAI().
_instance
InstanceScript* npc_tirion_fordring_tft::npc_tirion_fordringAI::_instance private
Definition at line 1662 of file boss_the_lich_king.cpp.
Referenced by EnterEvadeMode(), JustReachedHome(), MovementInform(), Reset(), sGossipSelect(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp