Azerotcore-wotlk: at_q24545_frostmourne_cavern Class Reference
at_q24545_frostmourne_cavern Class Reference
Public Member Functions
at_q24545_frostmourne_cavern ()
bool OnTrigger (Player *player, AreaTrigger const *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 1053 of file zone_dragonblight.cpp.
Constructor & Destructor Documentation
at_q24545_frostmourne_cavern()
at_q24545_frostmourne_cavern::at_q24545_frostmourne_cavern () inline
Definition at line 1056 of file zone_dragonblight.cpp.
 : AreaTriggerScript("at_q24545_frostmourne_cavern") { }
Member Function Documentation
OnTrigger()
bool at_q24545_frostmourne_cavern::OnTrigger (Player * player, AreaTrigger const *) inline override virtual
Reimplemented from AreaTriggerScript.
Definition at line 1058 of file zone_dragonblight.cpp.
     {
         if (player->GetPhaseMask() & 2)
             if (Creature* c = player->FindNearestCreature(NPC_SAC_LICH_KING, 60.0f, true))
                 c->AI()->SetGUID(player->GetGUID());
         return true;
     }
References mpq::c, WorldObject::FindNearestCreature(), Object::GetGUID(), WorldObject::GetPhaseMask(), and NPC_SAC_LICH_KING.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/zone_dragonblight.cpp