Azerotcore-wotlk: G3D::Image1 Class Reference
G3D::Image1 Class Reference
#include <Image1.h>
Public Types
typedef Image1 Type
typedef shared_ptr< class Image1 > Ref
typedef Color1 Storage
typedef Color1 Compute
Public Types inherited from G3D::Map2D< Color1, Color1 >
typedef Color1 StorageType
typedef Color1 ComputeType
typedef Map2D< Color1, Color1 > Type
typedef shared_ptr< Map2D > Ref
Public Member Functions
const class ImageFormat * format () const
void load (const std::string &filename)
void save (const std::string &filename)
Public Member Functions inherited from G3D::Map2D< Color1, Color1 >
const Color1 & fastGet (int x, int y) const
void fastSet (int x, int y, const Color1 &v)
Color1 bicubic (float x, float y, WrapMode wrap) const
Color1 bicubic (float x, float y) const
Color1 bicubic (const Vector2 &p, WrapMode wrap) const
Color1 bicubic (const Vector2 &p) const
void resize (uint32 newW, uint32 newH)
bool changed ()
void setChanged (bool c)
Color1 * getCArray ()
const Color1 * getCArray () const
Array< Color1 > & getArray ()
const Array< Color1 > & getArray () const
bool inBounds (int x, int y) const
bool inBounds (const Vector2int16 &v) const
const Color1 & get (int x, int y, WrapMode wrap) const
const Color1 & get (int x, int y) const
const Color1 & get (const Vector2int16 &p) const
const Color1 & get (const Vector2int16 &p, WrapMode wrap) const
Color1 & get (int x, int y, WrapMode wrap)
Color1 & get (int x, int y)
Color1 & get (const Vector2int16 &p)
void set (const Vector2int16 &p, const Color1 &v)
void set (int x, int y, const Color1 &v, WrapMode wrap)
void set (int x, int y, const Color1 &v)
void set (const shared_ptr< Map2D< Color1, T > > &src)
void setAll (const Color1 &v)
void maybeFlipVertical (bool flip)
virtual void flipVertical ()
virtual void flipHorizontal ()
virtual void crop (int newX, int newY, int newW, int newH)
virtual void crop (const Rect2D &rect)
Color1 nearest (float x, float y, WrapMode wrap) const
Color1 nearest (float x, float y) const
Color1 nearest (const Vector2 &p) const
Color1 average () const
Color1 bilinear (float x, float y, WrapMode wrap) const
Color1 bilinear (float x, float y) const
Color1 bilinear (const Vector2 &p) const
Color1 bilinear (const Vector2 &p, WrapMode wrap) const
int32 width () const
int32 height () const
Vector2int16 size () const
Rect2D rect2DBounds () const
size_t sizeInMemory () const
WrapMode wrapMode () const
void setWrapMode (WrapMode m)
Public Member Functions inherited from G3D::ReferenceCountedObject
virtual ~ReferenceCountedObject ()
Static Public Member Functions
static Ref createEmpty (int width, int height, WrapMode wrap=WrapMode::ERROR)
static Ref createEmpty (WrapMode wrap=WrapMode::ERROR)
static Ref fromFile (const std::string &filename, WrapMode wrap=WrapMode::ERROR)
static Ref fromArray (const class Color1unorm8 *ptr, int width, int height, WrapMode wrap=WrapMode::ERROR)
static Ref fromArray (const class Color3unorm8 *ptr, int width, int height, WrapMode wrap=WrapMode::ERROR)
static Ref fromArray (const class Color4unorm8 *ptr, int width, int height, WrapMode wrap=WrapMode::ERROR)
static Ref fromArray (const class Color1 *ptr, int width, int height, WrapMode wrap=WrapMode::ERROR)
static Ref fromArray (const class Color3 *ptr, int width, int height, WrapMode wrap=WrapMode::ERROR)
static Ref fromArray (const class Color4 *ptr, int width, int height, WrapMode wrap=WrapMode::ERROR)
static Ref fromImage1unorm8 (const shared_ptr< class Image1unorm8 > &im)
Static Public Member Functions inherited from G3D::Map2D< Color1, Color1 >
static Ref create (int w=0, int h=0, WrapMode wrap=WrapMode::ERROR)
Protected Member Functions
Image1 (int w, int h, WrapMode wrap)
void copyGImage (const class GImage &im)
void copyArray (const Color1 *src, int w, int h)
void copyArray (const Color3 *src, int w, int h)
void copyArray (const Color4 *src, int w, int h)
void copyArray (const Color1unorm8 *src, int w, int h)
void copyArray (const Color3unorm8 *src, int w, int h)
void copyArray (const Color4unorm8 *src, int w, int h)
Protected Member Functions inherited from G3D::Map2D< Color1, Color1 >
const Color1 & slowGet (int x, int y, WrapMode wrap)
Color1 bicubic (const Color1 *ctrl, double s) const
Map2D (int w, int h, WrapMode wrap)
Additional Inherited Members
Public Attributes inherited from G3D::Map2D< Color1, Color1 >
GMutex mutex
Protected Attributes inherited from G3D::Map2D< Color1, Color1 >
Color1 ZERO
uint32 w
uint32 h
WrapMode _wrapMode
AtomicInt32 m_changed
Array< Color1 > data
Detailed Description
Luminance image with 32-bit floating point storage.
See also G3D::Image1unorm8, G3D::GImage.
Definition at line 27 of file Image1.h.
Member Typedef Documentation
Compute
typedef Color1 G3D::Image1::Compute
Definition at line 33 of file Image1.h.
Ref
typedef shared_ptr<class Image1> G3D::Image1::Ref
Definition at line 31 of file Image1.h.
Storage
typedef Color1 G3D::Image1::Storage
Definition at line 32 of file Image1.h.
Type
typedef Image1 G3D::Image1::Type
Definition at line 30 of file Image1.h.
Constructor & Destructor Documentation
Image1()
G3D::Image1::Image1 (int w, int h, WrapMode wrap) protected
Definition at line 24 of file Image1.cpp.
                                           : Map2D<Color1, Color1>(w, h, wrap) {
     setAll(Color1(0.0f));
 }
References G3D::Map2D< Color1, Color1 >::setAll().
Member Function Documentation
copyArray() [1/6]
void G3D::Image1::copyArray (const Color1 * src, int w, int h) protected
Definition at line 161 of file Image1.cpp.
{
     resize(w, h);
     System::memcpy(getCArray(), src, w * h * sizeof(Color1));
 }
References G3D::Map2D< Color1, Color1 >::getCArray(), G3D::Map2D< Color1, Color1 >::h, G3D::System::memcpy(), G3D::Map2D< Color1, Color1 >::resize(), and G3D::Map2D< Color1, Color1 >::w.
Referenced by load().
copyArray() [2/6]
void G3D::Image1::copyArray (const Color1unorm8 * src, int w, int h) protected
Definition at line 180 of file Image1.cpp.
{
     resize(w, h);
     int N = w * h;
     Color1* dst = getCArray();
     for (int i = 0; i < N; ++i) {
         dst[i]= Color1(src[i]);
     }
 }
References G3D::Map2D< Color1, Color1 >::getCArray(), G3D::Map2D< Color1, Color1 >::h, G3D::Map2D< Color1, Color1 >::resize(), and G3D::Map2D< Color1, Color1 >::w.
copyArray() [3/6]
void G3D::Image1::copyArray (const Color3 * src, int w, int h) protected
Definition at line 191 of file Image1.cpp.
{
     resize(w, h);
     int N = w * h;
     Color1* dst = getCArray();
     for (int i = 0; i < N; ++i) {
         dst[i] = Color1(src[i].average());
     }
 }
References G3D::Map2D< Color1, Color1 >::average(), G3D::Map2D< Color1, Color1 >::getCArray(), G3D::Map2D< Color1, Color1 >::h, G3D::Map2D< Color1, Color1 >::resize(), and G3D::Map2D< Color1, Color1 >::w.
copyArray() [4/6]
void G3D::Image1::copyArray (const Color3unorm8 * src, int w, int h) protected
Definition at line 136 of file Image1.cpp.
{
     resize(w, h);
     int N = w * h;
     Color1* dst = data.getCArray();
     // Convert int8 -> float
     for (int i = 0; i < N; ++i) {
         dst[i] = Color1(Color3(src[i]).average());
     }
 }
References G3D::Map2D< Color1, Color1 >::average(), G3D::Map2D< Color1, Color1 >::h, G3D::Map2D< Color1, Color1 >::resize(), and G3D::Map2D< Color1, Color1 >::w.
copyArray() [5/6]
void G3D::Image1::copyArray (const Color4 * src, int w, int h) protected
Definition at line 167 of file Image1.cpp.
{
     resize(w, h);
     int N = w * h;
     Color1* dst = data.getCArray();
     // Strip alpha
     for (int i = 0; i < N; ++i) {
         dst[i] = Color1(src[i].rgb().average());
     }
 }
References G3D::Map2D< Color1, Color1 >::average(), G3D::Map2D< Color1, Color1 >::h, G3D::Map2D< Color1, Color1 >::resize(), and G3D::Map2D< Color1, Color1 >::w.
copyArray() [6/6]
void G3D::Image1::copyArray (const Color4unorm8 * src, int w, int h) protected
Definition at line 148 of file Image1.cpp.
{
     resize(w, h);
     int N = w * h;
     Color1* dst = data.getCArray();
     // Strip alpha and convert
     for (int i = 0; i < N; ++i) {
         dst[i] = Color1(Color3(src[i].rgb()).average());
     }
 }
References G3D::Map2D< Color1, Color1 >::average(), G3D::Map2D< Color1, Color1 >::h, G3D::Map2D< Color1, Color1 >::resize(), and G3D::Map2D< Color1, Color1 >::w.
copyGImage()
void G3D::Image1::copyGImage (const class GImage & im) protected
createEmpty() [1/2]
Image1::Ref G3D::Image1::createEmpty (int width, int height, WrapMode wrap = WrapMode::ERROR) static
Creates an all-zero width x height image.
Definition at line 43 of file Image1.cpp.
{
     return Image1::Ref(new Type(width, height, wrap));
 }
References G3D::Map2D< Color1, Color1 >::height(), G3D::Map2D< Color1, Color1 >::width(), and G3D::wrap().
Referenced by createEmpty(), fromArray(), fromFile(), and fromImage1unorm8().
createEmpty() [2/2]
Image1::Ref G3D::Image1::createEmpty (WrapMode wrap = WrapMode::ERROR) static
Creates a 0 x 0 image.
Definition at line 48 of file Image1.cpp.
{
     return createEmpty(0, 0, wrap);
 }
References createEmpty(), and G3D::wrap().
format()
const ImageFormat * G3D::Image1::format () const
Definition at line 209 of file Image1.cpp.
{
     return ImageFormat::L32F();
 }
References G3D::ImageFormat::L32F().
fromArray() [1/6]
Image1::Ref G3D::Image1::fromArray (const class Color1 * ptr, int width, int height, WrapMode wrap = WrapMode::ERROR) static
Definition at line 102 of file Image1.cpp.
{
     Ref out = createEmpty(wrap);
     out->copyArray(ptr, w, h);
     return out;
 }
References createEmpty(), G3D::Map2D< Color1, Color1 >::h, ptr(), G3D::Map2D< Color1, Color1 >::w, and G3D::wrap().
fromArray() [2/6]
Image1::Ref G3D::Image1::fromArray (const class Color1unorm8 * ptr, int width, int height, WrapMode wrap = WrapMode::ERROR) static
Definition at line 109 of file Image1.cpp.
{
     Ref out = createEmpty(wrap);
     out->copyArray(ptr, w, h);
     return out;
 }
References createEmpty(), G3D::Map2D< Color1, Color1 >::h, ptr(), G3D::Map2D< Color1, Color1 >::w, and G3D::wrap().
fromArray() [3/6]
Image1::Ref G3D::Image1::fromArray (const class Color3 * ptr, int width, int height, WrapMode wrap = WrapMode::ERROR) static
Definition at line 116 of file Image1.cpp.
{
     Ref out = createEmpty(wrap);
     out->copyArray(ptr, w, h);
     return out;
 }
References createEmpty(), G3D::Map2D< Color1, Color1 >::h, ptr(), G3D::Map2D< Color1, Color1 >::w, and G3D::wrap().
fromArray() [4/6]
Image1::Ref G3D::Image1::fromArray (const class Color3unorm8 * ptr, int width, int height, WrapMode wrap = WrapMode::ERROR) static
Definition at line 95 of file Image1.cpp.
{
     Ref out = createEmpty(wrap);
     out->copyArray(ptr, w, h);
     return out;
 }
References createEmpty(), G3D::Map2D< Color1, Color1 >::h, ptr(), G3D::Map2D< Color1, Color1 >::w, and G3D::wrap().
fromArray() [5/6]
Image1::Ref G3D::Image1::fromArray (const class Color4 * ptr, int width, int height, WrapMode wrap = WrapMode::ERROR) static
Definition at line 130 of file Image1.cpp.
{
     Ref out = createEmpty(wrap);
     out->copyArray(ptr, w, h);
     return out;
 }
References createEmpty(), G3D::Map2D< Color1, Color1 >::h, ptr(), G3D::Map2D< Color1, Color1 >::w, and G3D::wrap().
fromArray() [6/6]
Image1::Ref G3D::Image1::fromArray (const class Color4unorm8 * ptr, int width, int height, WrapMode wrap = WrapMode::ERROR) static
Definition at line 123 of file Image1.cpp.
{
     Ref out = createEmpty(wrap);
     out->copyArray(ptr, w, h);
     return out;
 }
References createEmpty(), G3D::Map2D< Color1, Color1 >::h, ptr(), G3D::Map2D< Color1, Color1 >::w, and G3D::wrap().
fromFile()
Image1::Ref G3D::Image1::fromFile (const std::string & filename, WrapMode wrap = WrapMode::ERROR) static
Definition at line 53 of file Image1.cpp.
{
     Ref out = createEmpty(wrap);
     out->load(filename);
     return out;
 }
References createEmpty(), and G3D::wrap().
fromImage1unorm8()
Image1::Ref G3D::Image1::fromImage1unorm8 (const shared_ptr< class Image1unorm8 > & im) static
Definition at line 29 of file Image1.cpp.
{
     Ref out = createEmpty(static_cast<WrapMode>(im->wrapMode()));
     out->resize(im->width(), im->height());
     int N = im->width() * im->height();
     const Color1unorm8* src = reinterpret_cast<Color1unorm8*>(im->getCArray());
     for (int i = 0; i < N; ++i) {
         out->data[i] = Color1(src[i]);
     }
     return out;
 }
References createEmpty().
load()
void G3D::Image1::load (const std::string & filename)
Loads from any of the file formats supported by G3D::Image.
If there is an alpha channel on the input, it is stripped. Values are automatically scaled to the range [0, 1].
Definition at line 60 of file Image1.cpp.
{
     shared_ptr<Image> image = Image::fromFile(filename);
     if (image->format() != ImageFormat::L32F()) {
         image->convertToL8();
     }
     switch (image->format()->code)
     {
         case ImageFormat::CODE_L8:
             copyArray(static_cast<const Color1unorm8*>(image->toPixelTransferBuffer()->buffer()), image->width(), image->height());
             break;
         case ImageFormat::CODE_L32F:
             copyArray(static_cast<const Color1*>(image->toPixelTransferBuffer()->buffer()), image->width(), image->height());
             break;
         case ImageFormat::CODE_RGB8:
             copyArray(static_cast<const Color3unorm8*>(image->toPixelTransferBuffer()->buffer()), image->width(), image->height());
             break;
         case ImageFormat::CODE_RGB32F:
             copyArray(static_cast<const Color3*>(image->toPixelTransferBuffer()->buffer()), image->width(), image->height());
             break;
         case ImageFormat::CODE_RGBA8:
             copyArray(static_cast<const Color4unorm8*>(image->toPixelTransferBuffer()->buffer()), image->width(), image->height());
             break;
         case ImageFormat::CODE_RGBA32F:
             copyArray(static_cast<const Color4*>(image->toPixelTransferBuffer()->buffer()), image->width(), image->height());
             break;
         default:
             debugAssertM(false, "Trying to load unsupported image format");
             break;
     }
     setChanged(true);
 }
References G3D::ImageFormat::CODE_L32F, G3D::ImageFormat::CODE_L8, G3D::ImageFormat::CODE_RGB32F, G3D::ImageFormat::CODE_RGB8, G3D::ImageFormat::CODE_RGBA32F, G3D::ImageFormat::CODE_RGBA8, copyArray(), debugAssertM, G3D::ImageFormat::L32F(), and G3D::Map2D< Color1, Color1 >::setChanged().
save()
void G3D::Image1::save (const std::string & filename)
Saves in any of the formats supported by G3D::Image.
The data values are assumed to be on the range [0, 1] and will be scaled appropriately for the save format.
Definition at line 202 of file Image1.cpp.
{
     // To avoid saving as floating point image.  FreeImage cannot convert floating point to L8.
     Image1unorm8::Ref unorm8 = Image1unorm8::fromImage1(dynamic_pointer_cast<Image1>(shared_from_this()));
     unorm8->save(filename);
 }
References G3D::unorm8.
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/Image1.h
deps/g3dlite/source/Image1.cpp