Azerotcore-wotlk: at_sindragosa_lair Class Reference
at_sindragosa_lair Class Reference
Public Member Functions
at_sindragosa_lair ()
bool OnTrigger (Player *player, AreaTrigger const *) override
Public Member Functions inherited from AreaTriggerScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AreaTriggerScript
AreaTriggerScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 1717 of file boss_sindragosa.cpp.
Constructor & Destructor Documentation
at_sindragosa_lair()
at_sindragosa_lair::at_sindragosa_lair () inline
Definition at line 1720 of file boss_sindragosa.cpp.
 : AreaTriggerScript("at_sindragosa_lair") { }
Member Function Documentation
OnTrigger()
bool at_sindragosa_lair::OnTrigger (Player * player, AreaTrigger const *) inline override virtual
Reimplemented from AreaTriggerScript.
Definition at line 1722 of file boss_sindragosa.cpp.
     {
         if (InstanceScript* instance = player->GetInstanceScript())
         {
             if (!instance->GetData(DATA_SPINESTALKER))
                 if (Creature* spinestalker = ObjectAccessor::GetCreature(*player, instance->GetGuidData(DATA_SPINESTALKER)))
                     spinestalker->AI()->DoAction(ACTION_START_FROSTWYRM);
             if (!instance->GetData(DATA_RIMEFANG))
                 if (Creature* rimefang = ObjectAccessor::GetCreature(*player, instance->GetGuidData(DATA_RIMEFANG)))
                     rimefang->AI()->DoAction(ACTION_START_FROSTWYRM);
             if (!instance->GetData(DATA_SINDRAGOSA_FROSTWYRMS) && !instance->GetGuidData(DATA_SINDRAGOSA) && instance->GetBossState(DATA_SINDRAGOSA) != DONE)
             {
                 if (instance->GetData(DATA_HAS_LIMITED_ATTEMPTS) && !instance->GetData(DATA_HEROIC_ATTEMPTS))
                     return true;
                 player->GetMap()->LoadGrid(SindragosaSpawnPos.GetPositionX(), SindragosaSpawnPos.GetPositionY());
                 if (Creature* sindragosa = player->GetMap()->SummonCreature(NPC_SINDRAGOSA, SindragosaSpawnPos))
                     sindragosa->AI()->DoAction(ACTION_START_FROSTWYRM);
             }
         }
         return true;
     }
References ACTION_START_FROSTWYRM, DATA_HAS_LIMITED_ATTEMPTS, DATA_HEROIC_ATTEMPTS, DATA_RIMEFANG, DATA_SINDRAGOSA, DATA_SINDRAGOSA_FROSTWYRMS, DATA_SPINESTALKER, DONE, ObjectAccessor::GetCreature(), WorldObject::GetInstanceScript(), WorldObject::GetMap(), Position::GetPositionX(), Position::GetPositionY(), Map::LoadGrid(), NPC_SINDRAGOSA, SindragosaSpawnPos, and Map::SummonCreature().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_sindragosa.cpp