Azerotcore-wotlk: Acore::AnyFriendlyNotSelfUnitInObjectRangeCheck Class Reference
Acore::AnyFriendlyNotSelfUnitInObjectRangeCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
AnyFriendlyNotSelfUnitInObjectRangeCheck (WorldObject const *obj, Unit const *funit, float range, bool playerOnly=false)
bool operator() (Unit *u)
Private Attributes
WorldObject const * i_obj
Unit const * i_funit
float i_range
bool i_playerOnly
Detailed Description
Definition at line 885 of file GridNotifiers.h.
Constructor & Destructor Documentation
AnyFriendlyNotSelfUnitInObjectRangeCheck()
Acore::AnyFriendlyNotSelfUnitInObjectRangeCheck::AnyFriendlyNotSelfUnitInObjectRangeCheck (WorldObject const * obj, Unit const * funit, float range, bool playerOnly = false) inline
Definition at line 888 of file GridNotifiers.h.
 : i_obj(obj), i_funit(funit), i_range(range), i_playerOnly(playerOnly) {}
Member Function Documentation
operator()()
bool Acore::AnyFriendlyNotSelfUnitInObjectRangeCheck::operator() (Unit * u) inline
Definition at line 889 of file GridNotifiers.h.
         {
             if (u != i_obj && u->IsAlive() && i_obj->IsWithinDistInMap(u, i_range) && i_funit->IsFriendlyTo(u) && (!i_playerOnly || u->GetTypeId() == TYPEID_PLAYER))
                 return true;
             else
                 return false;
         }
References Object::GetTypeId(), i_funit, i_obj, i_playerOnly, i_range, Unit::IsAlive(), Unit::IsFriendlyTo(), WorldObject::IsWithinDistInMap(), and TYPEID_PLAYER.
Member Data Documentation
i_funit
Unit const* Acore::AnyFriendlyNotSelfUnitInObjectRangeCheck::i_funit private
Definition at line 898 of file GridNotifiers.h.
Referenced by operator()().
i_obj
WorldObject const* Acore::AnyFriendlyNotSelfUnitInObjectRangeCheck::i_obj private
Definition at line 897 of file GridNotifiers.h.
Referenced by operator()().
i_playerOnly
bool Acore::AnyFriendlyNotSelfUnitInObjectRangeCheck::i_playerOnly private
Definition at line 900 of file GridNotifiers.h.
Referenced by operator()().
i_range
float Acore::AnyFriendlyNotSelfUnitInObjectRangeCheck::i_range private
Definition at line 899 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/game/Grids/Notifiers/GridNotifiers.h