Azerotcore-wotlk: npc_zulaman_hostage Class Reference
npc_zulaman_hostage Class Reference
Classes
struct npc_zulaman_hostageAI
Public Member Functions
npc_zulaman_hostage ()
CreatureAI * GetAI (Creature *creature) const override
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 455 of file zulaman.cpp.
Constructor & Destructor Documentation
npc_zulaman_hostage()
npc_zulaman_hostage::npc_zulaman_hostage () inline
Definition at line 458 of file zulaman.cpp.
 : CreatureScript("npc_zulaman_hostage") { }
Member Function Documentation
GetAI()
CreatureAI* npc_zulaman_hostage::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 487 of file zulaman.cpp.
     {
         return GetZulAmanAI<npc_zulaman_hostageAI>(creature);
     }
OnGossipHello()
bool npc_zulaman_hostage::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 492 of file zulaman.cpp.
     {
         AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_HOSTAGE1, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
         SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), Player::GetGossipTextId(), Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, GOSSIP_HOSTAGE1, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, and SendGossipMenuFor().
OnGossipSelect()
bool npc_zulaman_hostage::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 499 of file zulaman.cpp.
     {
         ClearGossipMenuFor(player);
         if (action == GOSSIP_ACTION_INFO_DEF + 1)
             CloseGossipMenuFor(player);
         if (!creature->HasFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP))
             return true;
         creature->RemoveFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP);
         InstanceScript* instance = creature->GetInstanceScript();
         if (instance)
         {
             //uint8 progress = instance->GetData(DATA_CHESTLOOTED);
             instance->SetData(DATA_CHESTLOOTED, 0);
             float x, y, z;
             creature->GetPosition(x, y, z);
             uint32 entry = creature->GetEntry();
             for (uint8 i = 0; i < 4; ++i)
             {
                 if (HostageEntry[i] == entry)
                 {
                     creature->SummonGameObject(ChestEntry[i], x - 2, y, z, 0, 0, 0, 0, 0, 0);
                     break;
                 }
             }
         }
         return true;
     }
References ChestEntry, ClearGossipMenuFor(), CloseGossipMenuFor(), DATA_CHESTLOOTED, Object::GetEntry(), WorldObject::GetInstanceScript(), Position::GetPosition(), GOSSIP_ACTION_INFO_DEF, Object::HasFlag(), HostageEntry, Object::RemoveFlag(), ZoneScript::SetData(), WorldObject::SummonGameObject(), UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
The documentation for this class was generated from the following file:
src/server/scripts/EasternKingdoms/ZulAman/zulaman.cpp