Azerotcore-wotlk: RisenArchmageCheck Class Reference
RisenArchmageCheck Class Reference
Public Member Functions
bool operator() (Creature *creature)
Detailed Description
Definition at line 149 of file boss_valithria_dreamwalker.cpp.
Member Function Documentation
operator()()
bool RisenArchmageCheck::operator() (Creature * creature) inline
Definition at line 153 of file boss_valithria_dreamwalker.cpp.
     {
         return creature->IsAlive() && creature->GetEntry() == NPC_RISEN_ARCHMAGE &&
                creature->GetSpawnId() && !creature->IsInCombat();
     }
References Object::GetEntry(), Creature::GetSpawnId(), Unit::IsAlive(), Unit::IsInCombat(), and NPC_RISEN_ARCHMAGE.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_valithria_dreamwalker.cpp