Azerotcore-wotlk: deps/mysqllite/mysys/my_read.c File Reference
my_read.c File Reference
#include "mysys_priv.h"
#include "mysys_err.h"
#include <my_base.h>
#include <errno.h>
Functions
size_t my_read (File Filedes, uchar *Buffer, size_t Count, myf MyFlags)
Function Documentation
my_read()
size_t my_read (File Filedes, uchar * Buffer, size_t Count, myf MyFlags)
Definition at line 36 of file my_read.c.
 {
   size_t readbytes, save_count;
   DBUG_ENTER("my_read");
   DBUG_PRINT("my",("fd: %d  Buffer: %p  Count: %lu  MyFlags: %d",
                    Filedes, Buffer, (ulong) Count, MyFlags));
   save_count= Count;
   for (;;)
   {
     errno= 0;                   /* Linux, Windows don't reset this on EOF/success */
 #ifdef _WIN32
     readbytes= my_win_read(Filedes, Buffer, Count);
 #else
     readbytes= read(Filedes, Buffer, Count);
 #endif
     if (readbytes != Count)
     {
       my_errno= errno;
       if (errno == 0 || (readbytes != (size_t) -1 &&
                          (MyFlags & (MY_NABP | MY_FNABP))))
         my_errno= HA_ERR_FILE_TOO_SHORT;
       DBUG_PRINT("warning",("Read only %d bytes off %lu from %d, errno: %d",
                             (int) readbytes, (ulong) Count, Filedes,
                             my_errno));
       if ((readbytes == 0 || (int) readbytes == -1) && errno == EINTR)
       {
         DBUG_PRINT("debug", ("my_read() was interrupted and returned %ld",
                              (long) readbytes));
         continue;                              /* Interrupted */
       }
       if (MyFlags & (MY_WME | MY_FAE | MY_FNABP))
       {
         if (readbytes == (size_t) -1)
           my_error(EE_READ, MYF(ME_BELL+ME_WAITTANG),
                    my_filename(Filedes),my_errno);
         else if (MyFlags & (MY_NABP | MY_FNABP))
           my_error(EE_EOFERR, MYF(ME_BELL+ME_WAITTANG),
                    my_filename(Filedes),my_errno);
       }
       if (readbytes == (size_t) -1 ||
           ((MyFlags & (MY_FNABP | MY_NABP)) && !(MyFlags & MY_FULL_IO)))
         DBUG_RETURN(MY_FILE_ERROR); /* Return with error */
       if (readbytes != (size_t) -1 && (MyFlags & MY_FULL_IO))
       {
         Buffer+= readbytes;
         Count-= readbytes;
         continue;
       }
     }
     if (MyFlags & (MY_NABP | MY_FNABP))
       readbytes= 0;         /* Ok on read */
     else if (MyFlags & MY_FULL_IO)
       readbytes= save_count;
     break;
   }
   DBUG_RETURN(readbytes);
 } /* my_read */
References Acore::Count(), DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_EOFERR, EE_READ, errno, HA_ERR_FILE_TOO_SHORT, ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_FAE, MY_FILE_ERROR, my_filename(), MY_FNABP, MY_FULL_IO, MY_NABP, MY_WME, MYF, and read.