Azerotcore-wotlk: boss_kelthuzad_minion::boss_kelthuzad_minionAI Struct Reference
boss_kelthuzad_minion::boss_kelthuzad_minionAI Struct Reference
Public Member Functions
boss_kelthuzad_minionAI (Creature *c)
void Reset () override
void DoAction (int32 param) override
void MoveInLineOfSight (Unit *who) override
void JustDied (Unit *) override
void AttackStart (Unit *who) override
void EnterCombat (Unit *) override
void KilledUnit (Unit *who) override
void JustReachedHome () override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
bool callHelp {}
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 524 of file boss_kelthuzad.cpp.
Constructor & Destructor Documentation
boss_kelthuzad_minionAI()
boss_kelthuzad_minion::boss_kelthuzad_minionAI::boss_kelthuzad_minionAI (Creature * c) inline explicit
Definition at line 526 of file boss_kelthuzad.cpp.
 : ScriptedAI(c) { }
Member Function Documentation
AttackStart()
void boss_kelthuzad_minion::boss_kelthuzad_minionAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 581 of file boss_kelthuzad.cpp.
         {
             ScriptedAI::AttackStart(who);
             if (callHelp)
             {
                 std::list<Creature*> targets;
                 me->GetCreaturesWithEntryInRange(targets, 15.0f, me->GetEntry());
                 for (std::list<Creature*>::const_iterator itr = targets.begin(); itr != targets.end(); ++itr)
                 {
                     if ((*itr)->GetGUID() != me->GetGUID())
                     {
                         (*itr)->ToCreature()->AI()->DoAction(ACTION_CALL_HELP_OFF);
                         (*itr)->ToCreature()->AI()->AttackStart(who);
                     }
                 }
             }
             if (me->GetEntry() != NPC_UNSTOPPABLE_ABOMINATION && me->GetEntry() != NPC_GUARDIAN_OF_ICECROWN)
             {
                 me->AddThreat(who, 1000000.0f);
             }
         }
References ACTION_CALL_HELP_OFF, Unit::AddThreat(), ScriptedAI::AttackStart(), callHelp, WorldObject::GetCreaturesWithEntryInRange(), Object::GetEntry(), Object::GetGUID(), ScriptedAI::me, NPC_GUARDIAN_OF_ICECROWN, and NPC_UNSTOPPABLE_ABOMINATION.
DoAction()
void boss_kelthuzad_minion::boss_kelthuzad_minionAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 538 of file boss_kelthuzad.cpp.
         {
             if (param == ACTION_CALL_HELP_ON)
             {
                 callHelp = true;
             }
             else if (param == ACTION_CALL_HELP_OFF)
             {
                 callHelp = false;
             }
             else if (param == ACTION_SECOND_PHASE)
             {
                 if (!me->IsInCombat())
                 {
                     me->DespawnOrUnsummon(500);
                 }
             }
             if (param == ACTION_GUARDIANS_OFF)
             {
                 me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                 me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                 me->RemoveAllAuras();
                 EnterEvadeMode();
                 me->SetPosition(me->GetHomePosition());
             }
         }
References ACTION_CALL_HELP_OFF, ACTION_CALL_HELP_ON, ACTION_GUARDIANS_OFF, ACTION_SECOND_PHASE, callHelp, Creature::DespawnOrUnsummon(), CreatureAI::EnterEvadeMode(), Creature::GetHomePosition(), Unit::IsInCombat(), ScriptedAI::me, Unit::RemoveAllAuras(), Object::SetFlag(), Creature::SetPosition(), UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
EnterCombat()
void boss_kelthuzad_minion::boss_kelthuzad_minionAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 604 of file boss_kelthuzad.cpp.
         {
             me->SetInCombatWithZone();
             if (me->GetEntry() == NPC_UNSTOPPABLE_ABOMINATION)
             {
                 events.ScheduleEvent(EVENT_MINION_FRENZY, 1000);
                 events.ScheduleEvent(EVENT_MINION_MORTAL_WOUND, 5000);
             }
             else if (me->GetEntry() == NPC_GUARDIAN_OF_ICECROWN)
             {
                 events.ScheduleEvent(EVENT_MINION_BLOOD_TAP, 15000);
             }
         }
References EVENT_MINION_BLOOD_TAP, EVENT_MINION_FRENZY, EVENT_MINION_MORTAL_WOUND, Object::GetEntry(), ScriptedAI::me, NPC_GUARDIAN_OF_ICECROWN, NPC_UNSTOPPABLE_ABOMINATION, and Creature::SetInCombatWithZone().
JustDied()
void boss_kelthuzad_minion::boss_kelthuzad_minionAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 573 of file boss_kelthuzad.cpp.
         {
             if (me->GetEntry() == NPC_UNSTOPPABLE_ABOMINATION && me->GetInstanceScript())
             {
                 me->GetInstanceScript()->SetData(DATA_ABOMINATION_KILLED, 0);
             }
         }
References DATA_ABOMINATION_KILLED, Object::GetEntry(), WorldObject::GetInstanceScript(), ScriptedAI::me, NPC_UNSTOPPABLE_ABOMINATION, and ZoneScript::SetData().
JustReachedHome()
void boss_kelthuzad_minion::boss_kelthuzad_minionAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 626 of file boss_kelthuzad.cpp.
         {
             if (me->GetEntry() == NPC_GUARDIAN_OF_ICECROWN)
             {
                 me->DespawnOrUnsummon();
             }
         }
References Creature::DespawnOrUnsummon(), Object::GetEntry(), ScriptedAI::me, and NPC_GUARDIAN_OF_ICECROWN.
KilledUnit()
void boss_kelthuzad_minion::boss_kelthuzad_minionAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 618 of file boss_kelthuzad.cpp.
         {
             if (who->GetTypeId() == TYPEID_PLAYER && me->GetInstanceScript())
             {
                 me->GetInstanceScript()->SetData(DATA_IMMORTAL_FAIL, 0);
             }
         }
References DATA_IMMORTAL_FAIL, WorldObject::GetInstanceScript(), Object::GetTypeId(), ScriptedAI::me, ZoneScript::SetData(), and TYPEID_PLAYER.
MoveInLineOfSight()
void boss_kelthuzad_minion::boss_kelthuzad_minionAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
Definition at line 565 of file boss_kelthuzad.cpp.
         {
             if (who->GetTypeId() != TYPEID_PLAYER && !who->IsPet())
                 return;
             ScriptedAI::MoveInLineOfSight(who);
         }
References Object::GetTypeId(), Unit::IsPet(), CreatureAI::MoveInLineOfSight(), and TYPEID_PLAYER.
Reset()
void boss_kelthuzad_minion::boss_kelthuzad_minionAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 531 of file boss_kelthuzad.cpp.
         {
             me->SetNoCallAssistance(true);
             callHelp = true;
             events.Reset();
         }
References callHelp, ScriptedAI::me, and Creature::SetNoCallAssistance().
UpdateAI()
void boss_kelthuzad_minion::boss_kelthuzad_minionAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 634 of file boss_kelthuzad.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_MINION_MORTAL_WOUND:
                     me->CastSpell(me->GetVictim(), SPELL_MORTAL_WOUND, false);
                     events.RepeatEvent(15000);
                     break;
                 case EVENT_MINION_FRENZY:
                     if (me->HealthBelowPct(35))
                     {
                         me->CastSpell(me, SPELL_FRENZY, true);
                         break;
                     }
                     events.RepeatEvent(1000);
                     break;
                 case EVENT_MINION_BLOOD_TAP:
                     me->CastSpell(me->GetVictim(), SPELL_BLOOD_TAP, false);
                     events.RepeatEvent(15000);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), EVENT_MINION_BLOOD_TAP, EVENT_MINION_FRENZY, EVENT_MINION_MORTAL_WOUND, Unit::GetVictim(), Unit::HasUnitState(), Unit::HealthBelowPct(), ScriptedAI::me, SPELL_BLOOD_TAP, SPELL_FRENZY, SPELL_MORTAL_WOUND, UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
callHelp
bool boss_kelthuzad_minion::boss_kelthuzad_minionAI::callHelp {}
Definition at line 529 of file boss_kelthuzad.cpp.
Referenced by AttackStart(), DoAction(), and Reset().
events
EventMap boss_kelthuzad_minion::boss_kelthuzad_minionAI::events
Definition at line 528 of file boss_kelthuzad.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Naxxramas/boss_kelthuzad.cpp