Azerotcore-wotlk: instance_steam_vault::instance_steam_vault_InstanceMapScript Struct Reference
instance_steam_vault::instance_steam_vault_InstanceMapScript Struct Reference
Public Member Functions
instance_steam_vault_InstanceMapScript (Map *map)
void Initialize () override
bool IsEncounterInProgress () const override
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 type) const override
ObjectGuid GetGuidData (uint32 data) const override
std::string GetSaveData () override
void Load (const char *strIn) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void CreatureLooted (Creature *, LootType)
void SaveToDB ()
virtual void Update (uint32)
void OnCreatureRemove (Creature *creature) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual void ProcessEvent (WorldObject *, uint32)
Public Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
ObjectGuid MekgineerGUID
ObjectGuid MainChambersDoor
ObjectGuid AccessPanelHydro
ObjectGuid AccessPanelMek
Public Attributes inherited from InstanceScript
Map * instance
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Definition at line 61 of file instance_steam_vault.cpp.
Constructor & Destructor Documentation
instance_steam_vault_InstanceMapScript()
instance_steam_vault::instance_steam_vault_InstanceMapScript::instance_steam_vault_InstanceMapScript (Map * map) inline
Definition at line 63 of file instance_steam_vault.cpp.
 : InstanceScript(map) {}
Member Function Documentation
GetData()
uint32 instance_steam_vault::instance_steam_vault_InstanceMapScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
Definition at line 163 of file instance_steam_vault.cpp.
         {
             switch (type)
             {
                 case TYPE_HYDROMANCER_THESPIA:
                 case TYPE_MEKGINEER_STEAMRIGGER:
                 case TYPE_WARLORD_KALITHRESH:
                     return m_auiEncounter[type];
             }
             return 0;
         }
References m_auiEncounter, TYPE_HYDROMANCER_THESPIA, TYPE_MEKGINEER_STEAMRIGGER, and TYPE_WARLORD_KALITHRESH.
Referenced by OnGameObjectCreate(), and SetData().
GetGuidData()
ObjectGuid instance_steam_vault::instance_steam_vault_InstanceMapScript::GetGuidData (uint32 data) const inline override virtual
Reimplemented from InstanceScript.
Definition at line 175 of file instance_steam_vault.cpp.
         {
             if (data == TYPE_MEKGINEER_STEAMRIGGER)
                 return MekgineerGUID;
             return ObjectGuid::Empty;
         }
References ObjectGuid::Empty, MekgineerGUID, and TYPE_MEKGINEER_STEAMRIGGER.
GetSaveData()
std::string instance_steam_vault::instance_steam_vault_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
Definition at line 183 of file instance_steam_vault.cpp.
         {
             OUT_SAVE_INST_DATA;
             std::ostringstream stream;
             stream << "S V " << m_auiEncounter[0] << ' ' << m_auiEncounter[1] << ' ' << m_auiEncounter[2];
             OUT_SAVE_INST_DATA_COMPLETE;
             return stream.str();
         }
References m_auiEncounter, OUT_SAVE_INST_DATA, and OUT_SAVE_INST_DATA_COMPLETE.
Initialize()
void instance_steam_vault::instance_steam_vault_InstanceMapScript::Initialize (void) inline override virtual
Reimplemented from InstanceScript.
Definition at line 72 of file instance_steam_vault.cpp.
         {
             memset(&m_auiEncounter, 0, sizeof(m_auiEncounter));
         }
References m_auiEncounter, and memset.
IsEncounterInProgress()
bool instance_steam_vault::instance_steam_vault_InstanceMapScript::IsEncounterInProgress () const inline override virtual
Reimplemented from InstanceScript.
Definition at line 77 of file instance_steam_vault.cpp.
         {
             for (uint8 i = 0; i < MAX_ENCOUNTER; ++i)
                 if (m_auiEncounter[i] == IN_PROGRESS)
                     return true;
             return false;
         }
References IN_PROGRESS, m_auiEncounter, and MAX_ENCOUNTER.
Load()
void instance_steam_vault::instance_steam_vault_InstanceMapScript::Load (const char * strIn) inline override virtual
Reimplemented from InstanceScript.
Definition at line 194 of file instance_steam_vault.cpp.
         {
             if (!strIn)
             {
                 OUT_LOAD_INST_DATA_FAIL;
                 return;
             }
             char dataHead1, dataHead2;
             std::istringstream loadStream(strIn);
             loadStream >> dataHead1 >> dataHead2;
             if (dataHead1 == 'S' && dataHead2 == 'V')
                 for (uint8 i = 0; i < MAX_ENCOUNTER; ++i)
                 {
                     loadStream >> m_auiEncounter[i];
                     if (m_auiEncounter[i] == IN_PROGRESS)
                         m_auiEncounter[i] = NOT_STARTED;
                 }
             OUT_LOAD_INST_DATA_COMPLETE;
         }
References IN_PROGRESS, m_auiEncounter, MAX_ENCOUNTER, NOT_STARTED, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_steam_vault::instance_steam_vault_InstanceMapScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 86 of file instance_steam_vault.cpp.
         {
             switch (creature->GetEntry())
             {
                 case NPC_MEKGINEER_STEAMRIGGER:
                     MekgineerGUID = creature->GetGUID();
                     break;
             }
         }
References Object::GetEntry(), Object::GetGUID(), MekgineerGUID, and NPC_MEKGINEER_STEAMRIGGER.
OnGameObjectCreate()
void instance_steam_vault::instance_steam_vault_InstanceMapScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
Definition at line 96 of file instance_steam_vault.cpp.
         {
             switch (go->GetEntry())
             {
                 case GO_MAIN_CHAMBERS_DOOR:
                     MainChambersDoor = go->GetGUID();
                     if (GetData(TYPE_HYDROMANCER_THESPIA) == SPECIAL && GetData(TYPE_MEKGINEER_STEAMRIGGER) == SPECIAL)
                         HandleGameObject(ObjectGuid::Empty, true, go);
                     break;
                 case GO_ACCESS_PANEL_HYDRO:
                     AccessPanelHydro = go->GetGUID();
                     if (GetData(TYPE_HYDROMANCER_THESPIA) == DONE)
                         go->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                     else if (GetData(TYPE_HYDROMANCER_THESPIA) == SPECIAL)
                         HandleGameObject(ObjectGuid::Empty, true, go);
                     break;
                 case GO_ACCESS_PANEL_MEK:
                     AccessPanelMek = go->GetGUID();
                     if (GetData(TYPE_MEKGINEER_STEAMRIGGER) == DONE)
                         go->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                     else if (GetData(TYPE_MEKGINEER_STEAMRIGGER) == SPECIAL)
                         HandleGameObject(ObjectGuid::Empty, true, go);
                     break;
             }
         }
References AccessPanelHydro, AccessPanelMek, DONE, ObjectGuid::Empty, GAMEOBJECT_FLAGS, GetData(), Object::GetEntry(), Object::GetGUID(), GO_ACCESS_PANEL_HYDRO, GO_ACCESS_PANEL_MEK, GO_FLAG_NOT_SELECTABLE, GO_MAIN_CHAMBERS_DOOR, InstanceScript::HandleGameObject(), MainChambersDoor, Object::RemoveFlag(), SPECIAL, TYPE_HYDROMANCER_THESPIA, and TYPE_MEKGINEER_STEAMRIGGER.
SetData()
void instance_steam_vault::instance_steam_vault_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
Definition at line 122 of file instance_steam_vault.cpp.
         {
             switch (type)
             {
                 case TYPE_HYDROMANCER_THESPIA:
                     if (data == SPECIAL)
                     {
                         if (GetData(TYPE_MEKGINEER_STEAMRIGGER) == SPECIAL)
                             HandleGameObject(MainChambersDoor, true);
                     }
                     else if (data == DONE)
                     {
                         if (GameObject* panel = instance->GetGameObject(AccessPanelHydro))
                             panel->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                     }
                     m_auiEncounter[type] = data;
                     break;
                 case TYPE_MEKGINEER_STEAMRIGGER:
                     if (data == SPECIAL)
                     {
                         if (GetData(TYPE_HYDROMANCER_THESPIA) == SPECIAL)
                             HandleGameObject(MainChambersDoor, true);
                     }
                     else if (data == DONE)
                     {
                         if (GameObject* panel = instance->GetGameObject(AccessPanelMek))
                             panel->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
                     }
                     m_auiEncounter[type] = data;
                     break;
                 case TYPE_WARLORD_KALITHRESH:
                     m_auiEncounter[type] = data;
                     break;
             }
             if (data == DONE || data == SPECIAL)
                 SaveToDB();
         }
References AccessPanelHydro, AccessPanelMek, DONE, GAMEOBJECT_FLAGS, GetData(), Map::GetGameObject(), GO_FLAG_NOT_SELECTABLE, InstanceScript::HandleGameObject(), InstanceScript::instance, m_auiEncounter, MainChambersDoor, InstanceScript::SaveToDB(), SPECIAL, TYPE_HYDROMANCER_THESPIA, TYPE_MEKGINEER_STEAMRIGGER, and TYPE_WARLORD_KALITHRESH.
Member Data Documentation
AccessPanelHydro
ObjectGuid instance_steam_vault::instance_steam_vault_InstanceMapScript::AccessPanelHydro
Definition at line 69 of file instance_steam_vault.cpp.
Referenced by OnGameObjectCreate(), and SetData().
AccessPanelMek
ObjectGuid instance_steam_vault::instance_steam_vault_InstanceMapScript::AccessPanelMek
Definition at line 70 of file instance_steam_vault.cpp.
Referenced by OnGameObjectCreate(), and SetData().
m_auiEncounter
uint32 instance_steam_vault::instance_steam_vault_InstanceMapScript::m_auiEncounter[MAX_ENCOUNTER]
Definition at line 65 of file instance_steam_vault.cpp.
Referenced by GetData(), GetSaveData(), Initialize(), IsEncounterInProgress(), Load(), and SetData().
MainChambersDoor
ObjectGuid instance_steam_vault::instance_steam_vault_InstanceMapScript::MainChambersDoor
Definition at line 68 of file instance_steam_vault.cpp.
Referenced by OnGameObjectCreate(), and SetData().
MekgineerGUID
ObjectGuid instance_steam_vault::instance_steam_vault_InstanceMapScript::MekgineerGUID
Definition at line 67 of file instance_steam_vault.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/CoilfangReservoir/SteamVault/instance_steam_vault.cpp