Azerotcore-wotlk: boss_onyxia::boss_onyxiaAI Struct Reference
boss_onyxia::boss_onyxiaAI Struct Reference
Public Member Functions
boss_onyxiaAI (Creature *pCreature)
void SetPhase (uint8 ph)
void Reset () override
void MoveInLineOfSight (Unit *who) override
void DoAction (int32 param) override
void BindPlayers ()
void EnterCombat (Unit *) override
void JustDied (Unit *) override
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustSummoned (Creature *pSummoned) override
void MovementInform (uint32 type, uint32 id) override
void HandleWhelpSpam (const uint32 diff)
void UpdateAI (uint32 diff) override
void SpellHitTarget (Unit *target, const SpellInfo *spell) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void KilledUnit (Unit *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
InstanceScript * m_pInstance
uint8 Phase
int8 CurrentWP
bool whelpSpam
uint8 whelpCount
int32 whelpSpamTimer
bool bManyWhelpsAvailable
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 121 of file boss_onyxia.cpp.
Constructor & Destructor Documentation
boss_onyxiaAI()
boss_onyxia::boss_onyxiaAI::boss_onyxiaAI (Creature * pCreature) inline
Definition at line 123 of file boss_onyxia.cpp.
                                            : ScriptedAI(pCreature)
         {
             m_pInstance = me->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), m_pInstance, and ScriptedAI::me.
Member Function Documentation
BindPlayers()
void boss_onyxia::boss_onyxiaAI::BindPlayers () inline
Definition at line 203 of file boss_onyxia.cpp.
         {
             me->GetMap()->ToInstanceMap()->PermBindAllPlayers();
         }
References WorldObject::GetMap(), ScriptedAI::me, InstanceMap::PermBindAllPlayers(), and Map::ToInstanceMap().
Referenced by EnterCombat().
DamageTaken()
void boss_onyxia::boss_onyxiaAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 229 of file boss_onyxia.cpp.
         {
             switch( Phase )
             {
                 case 1:
                     if( me->GetHealth() * 100 / me->GetMaxHealth() <= 65 )
                         SetPhase(2);
                     break;
                 case 2:
                     if( me->GetHealth() * 100 / me->GetMaxHealth() <= 40 )
                     {
                         me->InterruptNonMeleeSpells(false);
                         SetPhase(3);
                     }
                     break;
             }
         }
References Unit::GetHealth(), Unit::GetMaxHealth(), Unit::InterruptNonMeleeSpells(), ScriptedAI::me, and SetPhase().
DoAction()
void boss_onyxia::boss_onyxiaAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 192 of file boss_onyxia.cpp.
         {
             switch( param )
             {
                 case -1:
                     if( bManyWhelpsAvailable && m_pInstance )
                         m_pInstance->SetData(DATA_WHELP_SUMMONED, 1);
                     break;
             }
         }
References bManyWhelpsAvailable, DATA_WHELP_SUMMONED, m_pInstance, and ZoneScript::SetData().
EnterCombat()
void boss_onyxia::boss_onyxiaAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 208 of file boss_onyxia.cpp.
         {
             Talk(SAY_AGGRO);
             DoZoneInCombat();
             SetPhase(1);
             if( m_pInstance )
             {
                 m_pInstance->SetData(DATA_ONYXIA, IN_PROGRESS);
                 m_pInstance->DoStopTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, ACHIEV_TIMED_START_EVENT); // just in case at reset some players already left the instance
                 m_pInstance->DoStartTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, ACHIEV_TIMED_START_EVENT);
             }
             BindPlayers();
         }
References ACHIEV_TIMED_START_EVENT, ACHIEVEMENT_TIMED_TYPE_EVENT, BindPlayers(), DATA_ONYXIA, InstanceScript::DoStartTimedAchievement(), InstanceScript::DoStopTimedAchievement(), CreatureAI::DoZoneInCombat(), IN_PROGRESS, m_pInstance, SAY_AGGRO, ZoneScript::SetData(), SetPhase(), and CreatureAI::Talk().
HandleWhelpSpam()
void boss_onyxia::boss_onyxiaAI::HandleWhelpSpam (const uint32 diff) inline
Definition at line 298 of file boss_onyxia.cpp.
         {
             if( whelpSpam )
             {
                 if( whelpCount < 40 )
                 {
                     whelpSpamTimer -= diff;
                     if( whelpSpamTimer <= 0 )
                     {
                         float angle = rand_norm() * 2 * M_PI;
                         float dist = rand_norm() * 4.0f;
                         me->CastSpell(-33.18f + cos(angle)*dist, -258.80f + sin(angle)*dist, -89.0f, 17646, true);
                         me->CastSpell(-32.535f + cos(angle)*dist, -170.190f + sin(angle)*dist, -89.0f, 17646, true);
                         whelpCount += 2;
                         whelpSpamTimer += 600;
                     }
                 }
                 else
                 {
                     whelpSpam = false;
                     whelpCount = 0;
                     whelpSpamTimer = 0;
                 }
             }
         }
References Unit::CastSpell(), ScriptedAI::me, rand_norm(), whelpCount, whelpSpam, and whelpSpamTimer.
Referenced by UpdateAI().
JustDied()
void boss_onyxia::boss_onyxiaAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 223 of file boss_onyxia.cpp.
         {
             if( m_pInstance )
                 m_pInstance->SetData(DATA_ONYXIA, DONE);
         }
References DATA_ONYXIA, DONE, m_pInstance, and ZoneScript::SetData().
JustSummoned()
void boss_onyxia::boss_onyxiaAI::JustSummoned (Creature * pSummoned) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 247 of file boss_onyxia.cpp.
         {
             if( !pSummoned )
                 return;
             if( pSummoned->GetEntry() != NPC_ONYXIAN_WHELP && pSummoned->GetEntry() != NPC_ONYXIAN_LAIR_GUARD )
                 return;
             if( Unit* target = pSummoned->SelectNearestTarget(300.0f) )
             {
                 pSummoned->AI()->AttackStart(target);
                 DoZoneInCombat(pSummoned);
             }
         }
References Creature::AI(), UnitAI::AttackStart(), CreatureAI::DoZoneInCombat(), Object::GetEntry(), NPC_ONYXIAN_LAIR_GUARD, NPC_ONYXIAN_WHELP, and Creature::SelectNearestTarget().
MoveInLineOfSight()
void boss_onyxia::boss_onyxiaAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
Definition at line 183 of file boss_onyxia.cpp.
         {
             if( me->GetVictim() || me->GetDistance(who) > 30.0f )
                 return;
             if( who->GetTypeId() == TYPEID_PLAYER )
                 AttackStart(who);
         }
References ScriptedAI::AttackStart(), WorldObject::GetDistance(), Object::GetTypeId(), Unit::GetVictim(), ScriptedAI::me, and TYPEID_PLAYER.
MovementInform()
void boss_onyxia::boss_onyxiaAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 260 of file boss_onyxia.cpp.
         {
             if( type != POINT_MOTION_TYPE && type != EFFECT_MOTION_TYPE )
                 return;
             if( id < 9 )
             {
                 if( id > 0 && Phase == 2 )
                 {
                     me->SetFacingTo(OnyxiaMoveData[id].o);
                     me->SetSpeed(MOVE_RUN, 1.6f, false);
                     CurrentWP = id;
                     events.ScheduleEvent(EVENT_SPELL_FIREBALL_FIRST, 1000);
                 }
             }
             else switch( id )
                 {
                     case 10:
                         me->SetFacingTo(OnyxiaMoveData[0].o);
                         events.ScheduleEvent(EVENT_LIFTOFF, 0);
                         break;
                     case 11:
                         me->SetFacingTo(OnyxiaMoveData[1].o);
                         events.ScheduleEvent(EVENT_FLY_S_TO_N, 0);
                         break;
                     case 12:
                         me->SetFacingTo(OnyxiaMoveData[1].o);
                         events.ScheduleEvent(EVENT_LAND, 0);
                         break;
                     case 13:
                         me->SetCanFly(false);
                         me->SetDisableGravity(false);
                         me->SetSpeed(MOVE_RUN, me->GetCreatureTemplate()->speed_run, false);
                         events.ScheduleEvent(EVENT_PHASE_3_ATTACK, 0);
                         break;
                 }
         }
References CurrentWP, EFFECT_MOTION_TYPE, EVENT_FLY_S_TO_N, EVENT_LAND, EVENT_LIFTOFF, EVENT_PHASE_3_ATTACK, EVENT_SPELL_FIREBALL_FIRST, Creature::GetCreatureTemplate(), ScriptedAI::me, MOVE_RUN, OnyxiaMoveData, POINT_MOTION_TYPE, Creature::SetCanFly(), Creature::SetDisableGravity(), Unit::SetFacingTo(), Unit::SetSpeed(), and CreatureTemplate::speed_run.
Reset()
void boss_onyxia::boss_onyxiaAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 162 of file boss_onyxia.cpp.
         {
             CurrentWP = 0;
             SetPhase(0);
             me->SetReactState(REACT_AGGRESSIVE);
             me->SetCanFly(false);
             me->SetDisableGravity(false);
             me->SetSpeed(MOVE_RUN, me->GetCreatureTemplate()->speed_run, false);
             whelpSpam = false;
             whelpCount = 0;
             whelpSpamTimer = 0;
             bManyWhelpsAvailable = false;
             if( m_pInstance )
             {
                 m_pInstance->SetData(DATA_ONYXIA, NOT_STARTED);
                 m_pInstance->DoStopTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, ACHIEV_TIMED_START_EVENT);
             }
         }
References ACHIEV_TIMED_START_EVENT, ACHIEVEMENT_TIMED_TYPE_EVENT, bManyWhelpsAvailable, CurrentWP, DATA_ONYXIA, InstanceScript::DoStopTimedAchievement(), Creature::GetCreatureTemplate(), m_pInstance, ScriptedAI::me, MOVE_RUN, NOT_STARTED, REACT_AGGRESSIVE, Creature::SetCanFly(), ZoneScript::SetData(), Creature::SetDisableGravity(), SetPhase(), Creature::SetReactState(), Unit::SetSpeed(), CreatureTemplate::speed_run, whelpCount, whelpSpam, and whelpSpamTimer.
SetPhase()
void boss_onyxia::boss_onyxiaAI::SetPhase (uint8 ph) inline
Definition at line 139 of file boss_onyxia.cpp.
         {
             events.Reset();
             Phase = ph;
             switch( ph )
             {
                 case 0:
                     break;
                 case 1:
                     events.ScheduleEvent(EVENT_SPELL_WINGBUFFET, urand(10000, 20000));
                     events.ScheduleEvent(EVENT_SPELL_FLAMEBREATH, urand(10000, 20000));
                     events.ScheduleEvent(EVENT_SPELL_TAILSWEEP, urand(15000, 20000));
                     events.ScheduleEvent(EVENT_SPELL_CLEAVE, urand(2000, 5000));
                     break;
                 case 2:
                     events.ScheduleEvent(EVENT_START_PHASE_2, 0);
                     break;
                 case 3:
                     events.ScheduleEvent(EVENT_START_PHASE_3, 5000);
                     break;
             }
         }
References EVENT_SPELL_CLEAVE, EVENT_SPELL_FLAMEBREATH, EVENT_SPELL_TAILSWEEP, EVENT_SPELL_WINGBUFFET, EVENT_START_PHASE_2, EVENT_START_PHASE_3, and urand().
Referenced by DamageTaken(), EnterCombat(), and Reset().
SpellHitTarget()
void boss_onyxia::boss_onyxiaAI::SpellHitTarget (Unit * target, const SpellInfo * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 529 of file boss_onyxia.cpp.
         {
             if (target->GetTypeId() == TYPEID_PLAYER && spell->DurationEntry && spell->DurationEntry->ID == 328 && spell->Effects[EFFECT_1].TargetA.GetTarget() == 1 && (spell->Effects[EFFECT_1].Amplitude == 50 || spell->Effects[EFFECT_1].Amplitude == 215)) // Deep Breath
                 if (m_pInstance)
                     m_pInstance->SetData(DATA_DEEP_BREATH_FAILED, 1);
         }
References DATA_DEEP_BREATH_FAILED, SpellInfo::DurationEntry, EFFECT_1, SpellInfo::Effects, Object::GetTypeId(), SpellDurationEntry::ID, m_pInstance, ZoneScript::SetData(), and TYPEID_PLAYER.
UpdateAI()
void boss_onyxia::boss_onyxiaAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 324 of file boss_onyxia.cpp.
         {
             if( !UpdateVictim() )
                 return;
             events.Update(diff);
             HandleWhelpSpam(diff);
             if( me->HasUnitState(UNIT_STATE_CASTING) )
                 return;
             DoMeleeAttackIfReady();
             switch( events.ExecuteEvent() )
             {
                 case 0:
                     break;
                 case EVENT_SPELL_WINGBUFFET:
                     {
                         me->CastSpell(me, SPELL_WINGBUFFET, false);
                         events.RepeatEvent(urand(15000, 30000));
                     }
                     break;
                 case EVENT_SPELL_FLAMEBREATH:
                     {
                         me->CastSpell(me, SPELL_FLAMEBREATH, false);
                         events.RepeatEvent(urand(10000, 20000));
                     }
                     break;
                 case EVENT_SPELL_TAILSWEEP:
                     {
                         me->CastSpell(me, SPELL_TAILSWEEP, false);
                         events.RepeatEvent(urand(15000, 20000));
                     }
                     break;
                 case EVENT_SPELL_CLEAVE:
                     {
                         me->CastSpell(me->GetVictim(), SPELL_CLEAVE, false);
                         events.RepeatEvent(urand(2000, 5000));
                     }
                     break;
                 case EVENT_START_PHASE_2:
                     {
                         me->AttackStop();
                         me->SetReactState(REACT_PASSIVE);
                         me->StopMoving();
                         DoResetThreat();
                         me->GetMotionMaster()->MovePoint(10, OnyxiaMoveData[0].x, OnyxiaMoveData[0].y, OnyxiaMoveData[0].z);
                     }
                     break;
                 case EVENT_LIFTOFF:
                     {
                         Talk(SAY_PHASE_2_TRANS);
                         me->SendMeleeAttackStop(me->GetVictim());
                         me->GetMotionMaster()->MoveIdle();
                         me->DisableSpline();
                         me->SetCanFly(true);
                         me->SetDisableGravity(true);
                         me->SetOrientation(OnyxiaMoveData[0].o);
                         me->SendMovementFlagUpdate();
                         me->GetMotionMaster()->MoveTakeoff(11, OnyxiaMoveData[1].x + 1.0f, OnyxiaMoveData[1].y, OnyxiaMoveData[1].z, 12.0f);
                         bManyWhelpsAvailable = true;
                         events.RescheduleEvent(EVENT_END_MANY_WHELPS_TIME, 10000);
                     }
                     break;
                 case EVENT_END_MANY_WHELPS_TIME:
                     bManyWhelpsAvailable = false;
                     break;
                 case EVENT_FLY_S_TO_N:
                     {
                         me->SetSpeed(MOVE_RUN, 2.95f, false);
                         me->GetMotionMaster()->MovePoint(5, OnyxiaMoveData[5].x, OnyxiaMoveData[5].y, OnyxiaMoveData[5].z);
                         whelpSpam = true;
                         events.ScheduleEvent(EVENT_WHELP_SPAM, 90000);
                         events.ScheduleEvent(EVENT_SUMMON_LAIR_GUARD, 30000);
                     }
                     break;
                 case EVENT_SUMMON_LAIR_GUARD:
                     {
                         me->CastSpell(-101.654f, -214.491f, -80.70f, SPELL_SUMMON_LAIR_GUARD, true);
                         events.RepeatEvent(30000);
                     }
                     break;
                 case EVENT_WHELP_SPAM:
                     {
                         whelpSpam = true;
                         events.RepeatEvent(90000);
                     }
                     break;
                 case EVENT_LAND:
                     {
                         Talk(SAY_PHASE_3_TRANS);
                         me->SendMeleeAttackStop(me->GetVictim());
                         me->GetMotionMaster()->MoveLand(13, OnyxiaMoveData[0].x + 1.0f, OnyxiaMoveData[0].y, OnyxiaMoveData[0].z, 12.0f);
                         DoResetThreat();
                     }
                     break;
                 case EVENT_SPELL_FIREBALL_FIRST:
                     {
                         if( Unit* v = SelectTarget(SELECT_TARGET_RANDOM, 0, 200.0f, true) )
{
                             me->SetFacingToObject(v);
                             me->CastSpell(v, SPELL_FIREBALL, false);
                         }
                         events.ScheduleEvent(EVENT_SPELL_FIREBALL_SECOND, 4000);
                     }
                     break;
                 case EVENT_SPELL_FIREBALL_SECOND:
                     {
                         if( Unit* v = SelectTarget(SELECT_TARGET_RANDOM, 0, 200.0f, true) )
{
                             me->SetFacingToObject(v);
                             me->CastSpell(v, SPELL_FIREBALL, false);
                         }
                         uint8 rand = urand(0, 99);
                         if( rand < 33 )
                             events.ScheduleEvent(EVENT_PHASE_2_STEP_CW, 4000);
                         else if( rand < 66 )
                             events.ScheduleEvent(EVENT_PHASE_2_STEP_ACW, 4000);
                         else
                             events.ScheduleEvent(EVENT_PHASE_2_STEP_ACROSS, 4000);
                     }
                     break;
                 case EVENT_PHASE_2_STEP_CW:
                     {
                         uint8 newWP = CurrentWP + 1;
                         if( newWP > 8 )
                             newWP = 1;
                         me->GetMotionMaster()->MovePoint(newWP, OnyxiaMoveData[newWP].x, OnyxiaMoveData[newWP].y, OnyxiaMoveData[newWP].z);
                     }
                     break;
                 case EVENT_PHASE_2_STEP_ACW:
                     {
                         uint8 newWP = CurrentWP - 1;
                         if( newWP < 1 )
                             newWP = 8;
                         me->GetMotionMaster()->MovePoint(newWP, OnyxiaMoveData[newWP].x, OnyxiaMoveData[newWP].y, OnyxiaMoveData[newWP].z);
                     }
                     break;
                 case EVENT_PHASE_2_STEP_ACROSS:
                     {
                         me->SetFacingTo(OnyxiaMoveData[CurrentWP].o);
                         me->TextEmote("Onyxia takes in a deep breath...", nullptr, true);
                         me->CastSpell(me, OnyxiaMoveData[CurrentWP].spellId, false);
                         events.ScheduleEvent(EVENT_SPELL_BREATH, 8250);
                     }
                     break;
                 case EVENT_SPELL_BREATH:
                     {
                         uint8 newWP = OnyxiaMoveData[CurrentWP].DestId;
                         me->SetSpeed(MOVE_RUN, 2.95f, false);
                         me->GetMotionMaster()->MovePoint(newWP, OnyxiaMoveData[newWP].x, OnyxiaMoveData[newWP].y, OnyxiaMoveData[newWP].z);
                     }
                     break;
                 case EVENT_START_PHASE_3:
                     {
                         me->SetSpeed(MOVE_RUN, 2.95f, false);
                         me->GetMotionMaster()->MovePoint(12, OnyxiaMoveData[1].x, OnyxiaMoveData[1].y, OnyxiaMoveData[1].z);
                     }
                     break;
                 case EVENT_PHASE_3_ATTACK:
                     {
                         me->SetReactState(REACT_AGGRESSIVE);
                         AttackStart(SelectTarget(SELECT_TARGET_TOPAGGRO, 0, 0, false));
                         me->CastSpell(me, SPELL_BELLOWINGROAR, false);
                         events.ScheduleEvent(EVENT_ERUPTION, 0);
                         events.ScheduleEvent(EVENT_SPELL_WINGBUFFET, urand(10000, 20000));
                         events.ScheduleEvent(EVENT_SPELL_FLAMEBREATH, urand(10000, 20000));
                         events.ScheduleEvent(EVENT_SPELL_TAILSWEEP, urand(15000, 20000));
                         events.ScheduleEvent(EVENT_SPELL_CLEAVE, urand(2000, 5000));
                         events.ScheduleEvent(EVENT_SPELL_BELLOWINGROAR, 15000);
                         events.ScheduleEvent(EVENT_SUMMON_WHELP, 10000);
                     }
                     break;
                 case EVENT_SPELL_BELLOWINGROAR:
                     {
                         me->CastSpell(me, SPELL_BELLOWINGROAR, false);
                         events.RepeatEvent(22000);
                         events.ScheduleEvent(EVENT_ERUPTION, 0);
                     }
                     break;
                 case EVENT_ERUPTION:
                     {
                         if( Creature* trigger = me->SummonCreature(12758, *me, TEMPSUMMON_TIMED_DESPAWN, 1000) )
                             trigger->CastSpell(trigger, 17731, false);
                     }
                     break;
                 case EVENT_SUMMON_WHELP:
                     {
                         float angle = rand_norm() * 2 * M_PI;
                         float dist = rand_norm() * 4.0f;
                         me->CastSpell(-33.18f + cos(angle)*dist, -258.80f + sin(angle)*dist, -89.0f, 17646, true);
                         me->CastSpell(-32.535f + cos(angle)*dist, -170.190f + sin(angle)*dist, -89.0f, 17646, true);
                         events.RepeatEvent(30000);
                     }
                     break;
             }
         }
References ScriptedAI::AttackStart(), Unit::AttackStop(), bManyWhelpsAvailable, Unit::CastSpell(), CurrentWP, sOnyxMove::DestId, Unit::DisableSpline(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DoResetThreat(), EVENT_END_MANY_WHELPS_TIME, EVENT_ERUPTION, EVENT_FLY_S_TO_N, EVENT_LAND, EVENT_LIFTOFF, EVENT_PHASE_2_STEP_ACROSS, EVENT_PHASE_2_STEP_ACW, EVENT_PHASE_2_STEP_CW, EVENT_PHASE_3_ATTACK, EVENT_SPELL_BELLOWINGROAR, EVENT_SPELL_BREATH, EVENT_SPELL_CLEAVE, EVENT_SPELL_FIREBALL_FIRST, EVENT_SPELL_FIREBALL_SECOND, EVENT_SPELL_FLAMEBREATH, EVENT_SPELL_TAILSWEEP, EVENT_SPELL_WINGBUFFET, EVENT_START_PHASE_2, EVENT_START_PHASE_3, EVENT_SUMMON_LAIR_GUARD, EVENT_SUMMON_WHELP, EVENT_WHELP_SPAM, Unit::GetMotionMaster(), Unit::GetVictim(), HandleWhelpSpam(), Unit::HasUnitState(), ScriptedAI::me, MOVE_RUN, MotionMaster::MoveIdle(), MotionMaster::MoveLand(), MotionMaster::MovePoint(), MotionMaster::MoveTakeoff(), OnyxiaMoveData, rand_norm(), REACT_AGGRESSIVE, REACT_PASSIVE, SAY_PHASE_2_TRANS, SAY_PHASE_3_TRANS, SELECT_TARGET_RANDOM, SELECT_TARGET_TOPAGGRO, UnitAI::SelectTarget(), Unit::SendMeleeAttackStop(), Unit::SendMovementFlagUpdate(), Creature::SetCanFly(), Creature::SetDisableGravity(), Unit::SetFacingTo(), Unit::SetFacingToObject(), Position::SetOrientation(), Creature::SetReactState(), Unit::SetSpeed(), SPELL_BELLOWINGROAR, SPELL_CLEAVE, SPELL_FIREBALL, SPELL_FLAMEBREATH, SPELL_SUMMON_LAIR_GUARD, SPELL_TAILSWEEP, SPELL_WINGBUFFET, Unit::StopMoving(), WorldObject::SummonCreature(), CreatureAI::Talk(), TEMPSUMMON_TIMED_DESPAWN, Unit::TextEmote(), UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), urand(), and whelpSpam.
Member Data Documentation
bManyWhelpsAvailable
bool boss_onyxia::boss_onyxiaAI::bManyWhelpsAvailable
Definition at line 137 of file boss_onyxia.cpp.
Referenced by DoAction(), Reset(), and UpdateAI().
CurrentWP
int8 boss_onyxia::boss_onyxiaAI::CurrentWP
Definition at line 132 of file boss_onyxia.cpp.
Referenced by MovementInform(), Reset(), and UpdateAI().
events
EventMap boss_onyxia::boss_onyxiaAI::events
Definition at line 128 of file boss_onyxia.cpp.
m_pInstance
InstanceScript* boss_onyxia::boss_onyxiaAI::m_pInstance
Definition at line 130 of file boss_onyxia.cpp.
Referenced by boss_onyxiaAI(), DoAction(), EnterCombat(), JustDied(), Reset(), and SpellHitTarget().
Phase
uint8 boss_onyxia::boss_onyxiaAI::Phase
Definition at line 131 of file boss_onyxia.cpp.
whelpCount
uint8 boss_onyxia::boss_onyxiaAI::whelpCount
Definition at line 135 of file boss_onyxia.cpp.
Referenced by HandleWhelpSpam(), and Reset().
whelpSpam
bool boss_onyxia::boss_onyxiaAI::whelpSpam
Definition at line 134 of file boss_onyxia.cpp.
Referenced by HandleWhelpSpam(), Reset(), and UpdateAI().
whelpSpamTimer
int32 boss_onyxia::boss_onyxiaAI::whelpSpamTimer
Definition at line 136 of file boss_onyxia.cpp.
Referenced by HandleWhelpSpam(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/OnyxiasLair/boss_onyxia.cpp