Azerotcore-wotlk: LinkedListHead Class Reference
LinkedListHead Class Reference
#include <LinkedList.h>
Classes
class Iterator
Public Types
typedef Iterator< LinkedListElement > iterator
Public Member Functions
LinkedListHead ()
bool isEmpty () const
LinkedListElement * getFirst ()
LinkedListElement const * getFirst () const
LinkedListElement * getLast ()
LinkedListElement const * getLast () const
void insertFirst (LinkedListElement *pElem)
void insertLast (LinkedListElement *pElem)
uint32 getSize () const
void incSize ()
void decSize ()
Private Attributes
LinkedListElement iFirst
LinkedListElement iLast
uint32 iSize {0}
Detailed Description
Definition at line 82 of file LinkedList.h.
Member Typedef Documentation
iterator
typedef Iterator<LinkedListElement> LinkedListHead::iterator
Definition at line 260 of file LinkedList.h.
Constructor & Destructor Documentation
LinkedListHead()
LinkedListHead::LinkedListHead () inline
Definition at line 89 of file LinkedList.h.
     {
         // create empty list
         iFirst.iNext = &iLast;
         iLast.iPrev = &iFirst;
     }
References iFirst, iLast, LinkedListElement::iNext, and LinkedListElement::iPrev.
Member Function Documentation
decSize()
void LinkedListHead::decSize () inline
Definition at line 135 of file LinkedList.h.
 { --iSize; }
References iSize.
Referenced by MapReference::sourceObjectDestroyLink(), and MapReference::targetObjectDestroyLink().
getFirst() [1/2]
LinkedListElement* LinkedListHead::getFirst () inline
Definition at line 99 of file LinkedList.h.
 { return (isEmpty() ? nullptr : iFirst.iNext); }
References iFirst, LinkedListElement::iNext, and isEmpty().
Referenced by RefMgr< TO, FROM >::getFirst(), and getSize().
getFirst() [2/2]
LinkedListElement const* LinkedListHead::getFirst () const inline
Definition at line 100 of file LinkedList.h.
 { return (isEmpty() ? nullptr : iFirst.iNext); }
References iFirst, LinkedListElement::iNext, and isEmpty().
getLast() [1/2]
LinkedListElement* LinkedListHead::getLast () inline
Definition at line 102 of file LinkedList.h.
 { return (isEmpty() ? nullptr : iLast.iPrev); }
References iLast, LinkedListElement::iPrev, and isEmpty().
Referenced by RefMgr< TO, FROM >::getLast().
getLast() [2/2]
LinkedListElement const* LinkedListHead::getLast () const inline
Definition at line 103 of file LinkedList.h.
 { return (isEmpty() ? nullptr : iLast.iPrev); }
References iLast, LinkedListElement::iPrev, and isEmpty().
getSize()
uint32 LinkedListHead::getSize () const inline
Definition at line 115 of file LinkedList.h.
     {
         if (!iSize)
         {
             uint32 result = 0;
             LinkedListElement const* e = getFirst();
             while (e)
             {
                 ++result;
                 e = e->next();
             }
             return result;
         }
         else
         {
             return iSize;
         }
     }
References getFirst(), iSize, and LinkedListElement::next().
Referenced by spell_yogg_saron_brain_link::spell_yogg_saron_brain_link_AuraScript::HandleOnEffectApply(), Group::RemoveMember(), boss_yoggsaron_constrictor_tentacle::boss_yoggsaron_constrictor_tentacleAI::SelectConstrictTarget(), boss_yoggsaron_corruptor_tentacle::boss_yoggsaron_corruptor_tentacleAI::SelectCorruptionTarget(), boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::SelectT(), HostileRefMgr::threatAssist(), and boss_twin_valkyrAI::UpdateAI().
incSize()
void LinkedListHead::incSize () inline
Definition at line 134 of file LinkedList.h.
 { ++iSize; }
References iSize.
Referenced by MapReference::targetObjectBuildLink().
insertFirst()
void LinkedListHead::insertFirst (LinkedListElement * pElem) inline
Definition at line 105 of file LinkedList.h.
     {
         iFirst.insertAfter(pElem);
     }
References iFirst, and LinkedListElement::insertAfter().
Referenced by Unit::addFollower(), Unit::addHatedBy(), Loot::addLootValidatorRef(), Group::LinkMember(), and MapReference::targetObjectBuildLink().
insertLast()
void LinkedListHead::insertLast (LinkedListElement * pElem) inline
Definition at line 110 of file LinkedList.h.
     {
         iLast.insertBefore(pElem);
     }
References iLast, and LinkedListElement::insertBefore().
isEmpty()
bool LinkedListHead::isEmpty () const inline
Definition at line 97 of file LinkedList.h.
 { return (!iFirst.iNext->isInList()); }
References iFirst, LinkedListElement::iNext, and LinkedListElement::isInList().
Referenced by Map::AddToMap(), MotionTransport::BuildUpdate(), StaticTransport::BuildUpdate(), InstanceMap::CannotEnter(), boss_gothik::boss_gothikAI::CheckGroupSplitted(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::ChromieWhisper(), brann_bronzebeard::brann_bronzebeardAI::DoAction(), npc_arthas::npc_arthasAI::DoAction(), InstanceScript::DoCastSpellOnPlayers(), ScriptedAI::DoPlayMusic(), InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), InstanceScript::DoSendNotifyToInstance(), InstanceScript::DoStartTimedAchievement(), InstanceScript::DoStopTimedAchievement(), InstanceScript::DoUpdateAchievementCriteria(), InstanceScript::DoUpdateWorldState(), CreatureAI::DoZoneInCombat(), boss_sapphiron::boss_sapphironAI::EnterCombatSelfFunction(), instance_pit_of_saron::instance_pit_of_saron_InstanceScript::GetCreatureEntry(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::GetCreatureEntry(), getFirst(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::GetGameObjectEntry(), getLast(), instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::GetPlayerInMap(), WorldSession::HandleMoveWorldportAck(), Map::HavePlayers(), boss_ichoron::boss_ichoronAI::IchoronDoCastToAllHostilePlayers(), npc_coren_direbrew::npc_coren_direbrewAI::JustDied(), boss_headless_horseman::boss_headless_horsemanAI::JustDied(), npc_love_in_air_hummel::npc_love_in_air_hummelAI::JustDied(), boss_ahune::boss_ahuneAI::JustDied(), boss_four_horsemen::boss_four_horsemenAI::JustDied(), WorldSession::LogoutPlayer(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::OnCreatureCreate(), instance_forge_of_souls::instance_forge_of_souls_InstanceScript::OnCreatureCreate(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::OnCreatureCreate(), instance_pit_of_saron::instance_pit_of_saron_InstanceScript::OnCreatureCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), instance_nexus::instance_nexus_InstanceMapScript::OnCreatureCreate(), instance_shattered_halls::instance_shattered_halls_InstanceMapScript::OnCreatureCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectCreate(), Map::PlayDirectSoundToMap(), SmartScript::ProcessAction(), Map::RemoveFromMap(), InstanceMap::Reset(), SendPacketToPlayers(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::SendUpdateWorldState(), instance_hyjal::instance_mount_hyjal_InstanceMapScript::SetData(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::SetData(), instance_the_black_morass::instance_the_black_morass_InstanceMapScript::SetData(), Map::SetZoneMusic(), Map::SetZoneOverrideLight(), Map::SetZoneWeather(), instance_zulaman::instance_zulaman_InstanceMapScript::SummonHostage(), npc_arthas::npc_arthasAI::SummonNextWave(), instance_stratholme::instance_stratholme_InstanceMapScript::Update(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::Update(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::Update(), instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::Update(), Unit::Update(), npc_barnes::npc_barnesAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), boss_cthun::cthunAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_scion_of_eternity::npc_scion_of_eternityAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateWorldState(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateWorldState(), and ObjectGridUnloader::Visit().
Member Data Documentation
iFirst
LinkedListElement LinkedListHead::iFirst private
Definition at line 85 of file LinkedList.h.
Referenced by getFirst(), insertFirst(), isEmpty(), and LinkedListHead().
iLast
LinkedListElement LinkedListHead::iLast private
Definition at line 86 of file LinkedList.h.
Referenced by getLast(), insertLast(), and LinkedListHead().
iSize
uint32 LinkedListHead::iSize {0} private
Definition at line 87 of file LinkedList.h.
Referenced by decSize(), getSize(), and incSize().
The documentation for this class was generated from the following file:
src/common/Dynamic/LinkedList.h