Azerotcore-wotlk: SplineHandler Class Reference
SplineHandler Class Reference
Public Member Functions
SplineHandler (Unit *unit)
bool operator() (Movement::MoveSpline::UpdateResult result)
Private Attributes
Unit * _unit
Detailed Description
Definition at line 531 of file Unit.cpp.
Constructor & Destructor Documentation
SplineHandler()
SplineHandler::SplineHandler (Unit * unit) inline
Definition at line 534 of file Unit.cpp.
 : _unit(unit) { }
Member Function Documentation
operator()()
bool SplineHandler::operator() (Movement::MoveSpline::UpdateResult result) inline
Definition at line 536 of file Unit.cpp.
     {
         if ((result & (Movement::MoveSpline::Result_NextSegment | Movement::MoveSpline::Result_JustArrived)) &&
                 _unit->GetTypeId() == TYPEID_UNIT && _unit->GetMotionMaster()->GetCurrentMovementGeneratorType() == ESCORT_MOTION_TYPE &&
                 _unit->movespline->GetId() == _unit->GetMotionMaster()->GetCurrentSplineId())
         {
             _unit->ToCreature()->AI()->MovementInform(ESCORT_MOTION_TYPE, _unit->movespline->currentPathIdx() - 1);
         }
         return true;
     }
References _unit, Creature::AI(), Movement::MoveSpline::currentPathIdx(), ESCORT_MOTION_TYPE, MotionMaster::GetCurrentMovementGeneratorType(), MotionMaster::GetCurrentSplineId(), Movement::MoveSpline::GetId(), Unit::GetMotionMaster(), Object::GetTypeId(), CreatureAI::MovementInform(), Unit::movespline, Movement::MoveSpline::Result_JustArrived, Movement::MoveSpline::Result_NextSegment, Object::ToCreature(), and TYPEID_UNIT.
Member Data Documentation
_unit
Unit* SplineHandler::_unit private
Definition at line 549 of file Unit.cpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/game/Entities/Unit/Unit.cpp