Azerotcore-wotlk: icecrown_citadel_teleport Class Reference
icecrown_citadel_teleport Class Reference
Public Member Functions
icecrown_citadel_teleport ()
bool OnGossipHello (Player *player, GameObject *go) override
bool OnGossipSelect (Player *player, GameObject *, uint32 sender, uint32 action) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Definition at line 37 of file icecrown_citadel_teleport.cpp.
Constructor & Destructor Documentation
icecrown_citadel_teleport()
icecrown_citadel_teleport::icecrown_citadel_teleport () inline
Definition at line 40 of file icecrown_citadel_teleport.cpp.
 : GameObjectScript("icecrown_citadel_teleport") { }
Member Function Documentation
OnGossipHello()
bool icecrown_citadel_teleport::OnGossipHello (Player * player, GameObject * go) inline override virtual
Reimplemented from GameObjectScript.
Definition at line 42 of file icecrown_citadel_teleport.cpp.
     {
         uint32 gossipMenuId = go->GetGOInfo()->GetGossipMenuId();
         if (go->GetEntry() != GO_SCOURGE_TRANSPORTER_FIRST)
             AddGossipItemFor(
                 player, gossipMenuId, ICC_TELEPORT_GOSSIP_OPT_LIGHTS_HAMMER,
                 GOSSIP_SENDER_ICC_PORT, LIGHT_S_HAMMER_TELEPORT
             ); // M_PI + M_PI/6
         if (InstanceScript* instance = go->GetInstanceScript())
         {
             if (instance->GetBossState(DATA_LORD_MARROWGAR) == DONE && go->GetEntry() != 202245)
                 AddGossipItemFor(
                     player, gossipMenuId, ICC_TELEPORT_GOSSIP_OPT_ORATORY_OF_THE_DAMNED,
                     GOSSIP_SENDER_ICC_PORT, ORATORY_OF_THE_DAMNED_TELEPORT
                 ); // M_PI + M_PI/6
             if (instance->GetBossState(DATA_LADY_DEATHWHISPER) == DONE && go->GetEntry() != 202243)
                 AddGossipItemFor(
                     player, gossipMenuId, ICC_TELEPORT_GOSSIP_OPT_RAMPART_OF_SKULLS,
                     GOSSIP_SENDER_ICC_PORT, RAMPART_OF_SKULLS_TELEPORT
                 ); // M_PI/6
             if (instance->GetBossState(DATA_ICECROWN_GUNSHIP_BATTLE) == DONE && go->GetEntry() != 202244)
                 AddGossipItemFor(
                     player, gossipMenuId, ICC_TELEPORT_GOSSIP_OPT_DEATHBRINGERS_RISE,
                     GOSSIP_SENDER_ICC_PORT, DEATHBRINGER_S_RISE_TELEPORT
                 ); // M_PI/6
             if (instance->GetData(DATA_COLDFLAME_JETS) == DONE && go->GetEntry() != 202235)
                 AddGossipItemFor(
                     player, gossipMenuId, ICC_TELEPORT_GOSSIP_OPT_UPPER_SPIRE,
                     GOSSIP_SENDER_ICC_PORT, UPPER_SPIRE_TELEPORT
                 ); // M_PI/6
             if (instance->GetBossState(DATA_VALITHRIA_DREAMWALKER) == DONE && instance->GetBossState(DATA_SINDRAGOSA_GAUNTLET) == DONE && go->GetEntry() != 202246)
                 AddGossipItemFor(
                     player, gossipMenuId, ICC_TELEPORT_GOSSIP_OPT_SINDRAGOSAS_LAIR,
                     GOSSIP_SENDER_ICC_PORT, SINDRAGOSA_S_LAIR_TELEPORT
                 ); // M_PI*3/2 + M_PI/6
         }
         SendGossipMenuFor(player, player->GetGossipTextId(go), go->GetGUID());
         return true;
     }
References AddGossipItemFor(), DATA_COLDFLAME_JETS, DATA_ICECROWN_GUNSHIP_BATTLE, DATA_LADY_DEATHWHISPER, DATA_LORD_MARROWGAR, DATA_SINDRAGOSA_GAUNTLET, DATA_VALITHRIA_DREAMWALKER, DEATHBRINGER_S_RISE_TELEPORT, DONE, Object::GetEntry(), GameObject::GetGOInfo(), GameObjectTemplate::GetGossipMenuId(), Player::GetGossipTextId(), Object::GetGUID(), WorldObject::GetInstanceScript(), GO_SCOURGE_TRANSPORTER_FIRST, GOSSIP_SENDER_ICC_PORT, ICC_TELEPORT_GOSSIP_OPT_DEATHBRINGERS_RISE, ICC_TELEPORT_GOSSIP_OPT_LIGHTS_HAMMER, ICC_TELEPORT_GOSSIP_OPT_ORATORY_OF_THE_DAMNED, ICC_TELEPORT_GOSSIP_OPT_RAMPART_OF_SKULLS, ICC_TELEPORT_GOSSIP_OPT_SINDRAGOSAS_LAIR, ICC_TELEPORT_GOSSIP_OPT_UPPER_SPIRE, LIGHT_S_HAMMER_TELEPORT, ORATORY_OF_THE_DAMNED_TELEPORT, RAMPART_OF_SKULLS_TELEPORT, SendGossipMenuFor(), SINDRAGOSA_S_LAIR_TELEPORT, and UPPER_SPIRE_TELEPORT.
OnGossipSelect()
bool icecrown_citadel_teleport::OnGossipSelect (Player * player, GameObject * , uint32 sender, uint32 action) inline override virtual
Reimplemented from GameObjectScript.
Definition at line 85 of file icecrown_citadel_teleport.cpp.
     {
         ClearGossipMenuFor(player);
         CloseGossipMenuFor(player);
         SpellInfo const* spell = sSpellMgr->GetSpellInfo(action);
         if (!spell)
             return false;
         if (player->IsInCombat())
         {
             Spell::SendCastResult(player, spell, 0, SPELL_FAILED_AFFECTING_COMBAT);
             return true;
         }
         if (sender == GOSSIP_SENDER_ICC_PORT)
             player->CastSpell(player, spell, false);
         return true;
     }
References Unit::CastSpell(), ClearGossipMenuFor(), CloseGossipMenuFor(), GOSSIP_SENDER_ICC_PORT, Unit::IsInCombat(), Spell::SendCastResult(), SPELL_FAILED_AFFECTING_COMBAT, and sSpellMgr.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel_teleport.cpp