Azerotcore-wotlk: BattlefieldWG Class Reference
BattlefieldWG Class Reference
#include <BattlefieldWG.h>
Public Member Functions
~BattlefieldWG () override
void OnBattleStart () override
Called when the battle start.
void OnBattleEnd (bool endByTimer) override
Called when battle end.
void OnStartGrouping () override
Called when grouping starts (15 minutes before battlestart)
void OnPlayerJoinWar (Player *player) override
Called when player accept invite to join battle.
void OnPlayerLeaveWar (Player *player) override
Called when player left the battle.
void OnPlayerLeaveZone (Player *player) override
Called when player left the WG zone.
void OnPlayerEnterZone (Player *player) override
Called when player enters in WG zone.
bool Update (uint32 diff) override
Called for update battlefield data.
void OnCreatureCreate (Creature *creature) override
Called when a creature is created.
void OnCreatureRemove (Creature *creature) override
Called when a creature is removed.
void OnGameObjectCreate (GameObject *go) override
Called when a gameobject is created.
void BrokenWallOrTower (TeamId team)
Called when a wall/tower is broken.
void UpdateDamagedTowerCount (TeamId team)
Called when a tower is damaged.
void UpdatedDestroyedTowerCount (TeamId team, GameObject *go)
Called when tower is broken.
void RemoveAurasFromPlayer (Player *player)
bool SetupBattlefield () override
Called when battlefield is setup, at server start.
GameObject * GetRelic ()
Return pointer to relic object.
bool CanInteractWithRelic ()
Define relic object.
void SetRelicInteractible (bool allow)
Define if player can interact with the relic.
void UpdateCounterVehicle (bool init)
Vehicle world states update.
void UpdateVehicleCountWG ()
void CapturePointTaken (uint32 areaId)
void SendInitWorldStatesTo (Player *player)
void SendInitWorldStatesToAll () override
Send all worldstate data to all player in zone.
void FillInitialWorldStates (WorldPacket &data) override
void HandleKill (Player *killer, Unit *victim) override
Called when a Unit is kill in battlefield zone.
void OnUnitDeath (Unit *unit) override
void PromotePlayer (Player *killer)
uint32 GetHonorBuff (int32 stack) const
void UpdateTenacity ()
void AddUpdateTenacity (Player *player)
void RemoveUpdateTenacity (Player *player)
void ProcessEvent (WorldObject *obj, uint32 eventId) override
bool FindAndRemoveVehicleFromList (Unit *vehicle)
uint8 GetSpiritGraveyardId (uint32 areaId) const
uint32 GetAreaByGraveyardId (uint8 gId) const
uint32 GetData (uint32 data) const override
bool IsKeepNpc (uint32 entry)
Public Member Functions inherited from Battlefield
Battlefield ()
Constructor.
~Battlefield () override
Destructor.
void SendUpdateWorldState (uint32 field, uint32 value)
Update data of a worldstate to all players present in zone.
void InvitePlayersInZoneToQueue ()
Invite all players in zone to join the queue, called x minutes before battle start in Update()
void InvitePlayersInQueueToWar ()
Invite all players in queue to join battle on battle start.
void InvitePlayersInZoneToWar ()
Invite all players in zone to join battle on battle start.
uint32 GetTypeId ()
uint32 GetZoneId ()
void TeamApplyBuff (TeamId team, uint32 spellId, uint32 spellId2=0)
bool IsWarTime ()
Return true if battle is start, false if battle is not started.
void ToggleBattlefield (bool enable)
Enable or Disable battlefield.
bool IsEnabled ()
Return if battlefield is enable.
void KickPlayerFromBattlefield (ObjectGuid guid)
Kick player from battlefield and teleport him to kick-point location.
void HandlePlayerEnterZone (Player *player, uint32 zone)
Called when player (player) enter in zone.
void HandlePlayerLeaveZone (Player *player, uint32 zone)
Called when player (player) leave the zone.
uint64 GetData64 (uint32 dataId) const override
void SetData64 (uint32 dataId, uint64 value) override
void SetData (uint32 dataId, uint32 value) override
virtual void UpdateData (uint32 index, int32 pad)
TeamId GetDefenderTeam ()
TeamId GetAttackerTeam ()
TeamId GetOtherTeam (TeamId team)
void SetDefenderTeam (TeamId team)
Group * GetFreeBfRaid (TeamId TeamId)
Find a not full battlefield group, if there is no, create one.
Group * GetGroupPlayer (ObjectGuid guid, TeamId TeamId)
Return battlefield group where player is.
bool AddOrSetPlayerToCorrectBfGroup (Player *player)
Force player to join a battlefield group.
GraveyardStruct const * GetClosestGraveyard (Player *player)
virtual void AddPlayerToResurrectQueue (ObjectGuid npc_guid, ObjectGuid player_guid)
void RemovePlayerFromResurrectQueue (ObjectGuid player_guid)
void SetGraveyardNumber (uint32 number)
BfGraveyard * GetGraveyardById (uint32 id) const
Creature * SpawnCreature (uint32 entry, float x, float y, float z, float o, TeamId teamId)
Creature * SpawnCreature (uint32 entry, Position pos, TeamId teamId)
GameObject * SpawnGameObject (uint32 entry, float x, float y, float z, float o)
Creature * GetCreature (ObjectGuid const guid)
GameObject * GetGameObject (ObjectGuid const guid)
void SendWarningToAllInZone (uint32 entry)
void SendWarningToPlayer (Player *player, uint32 entry)
void PlayerAcceptInviteToQueue (Player *player)
void PlayerAcceptInviteToWar (Player *player)
uint32 GetBattleId ()
void AskToLeaveQueue (Player *player)
void PlayerAskToLeave (Player *player)
bool CanFlyIn ()
Return if we can use mount in battlefield.
void SendAreaSpiritHealerQueryOpcode (Player *player, const ObjectGuid &guid)
void StartBattle ()
void EndBattle (bool endByTimer)
void HideNpc (Creature *creature)
void ShowNpc (Creature *creature, bool aggressive)
GraveyardVect GetGraveyardVector ()
uint32 GetTimer ()
void SetTimer (uint32 timer)
void DoPlaySoundToAll (uint32 SoundID)
void InvitePlayerToQueue (Player *player)
void InvitePlayerToWar (Player *player)
void InitStalker (uint32 entry, float x, float y, float z, float o)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnGameObjectRemove (GameObject *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
Protected Attributes
bool m_isRelicInteractible
Workshop WorkshopsList
GameObjectSet DefenderPortalList
GameObjectSet m_KeepGameObject [2]
GameObjectBuilding BuildingsInZone
GuidUnorderedSet m_vehicles [2]
GuidUnorderedSet CanonList
GuidUnorderedSet KeepCreature [2]
GuidUnorderedSet OutsideCreature [2]
GuidUnorderedSet m_updateTenacityList
int32 m_tenacityStack
uint32 m_tenacityUpdateTimer
uint32 m_saveTimer
ObjectGuid m_titansRelic
Protected Attributes inherited from Battlefield
ObjectGuid StalkerGuid
uint32 m_Timer
bool m_IsEnabled
bool m_isActive
TeamId m_DefenderTeam
BfCapturePointVector m_capturePoints
GuidUnorderedSet m_players [BG_TEAMS_COUNT]
GuidUnorderedSet m_PlayersInQueue [BG_TEAMS_COUNT]
GuidUnorderedSet m_PlayersInWar [BG_TEAMS_COUNT]
PlayerTimerMap m_InvitedPlayers [BG_TEAMS_COUNT]
PlayerTimerMap m_PlayersWillBeKick [BG_TEAMS_COUNT]
uint32 m_TypeId
uint32 m_BattleId
uint32 m_ZoneId
uint32 m_MapId
Map * m_Map
uint32 m_MaxPlayer
uint32 m_MinPlayer
uint32 m_MinLevel
uint32 m_BattleTime
uint32 m_NoWarBattleTime
uint32 m_RestartAfterCrash
uint32 m_TimeForAcceptInvite
uint32 m_uiKickDontAcceptTimer
WorldLocation KickPosition
uint32 m_uiKickAfkPlayersTimer
GraveyardVect m_GraveyardList
uint32 m_LastResurectTimer
uint32 m_StartGroupingTimer
bool m_StartGrouping
GuidUnorderedSet m_Groups [BG_TEAMS_COUNT]
std::vector< uint64 > m_Data64
std::vector< uint32 > m_Data32
Additional Inherited Members
Public Types inherited from Battlefield
typedef std::vector< BfCapturePoint * > BfCapturePointVector
typedef of map witch store capturepoint and the associate gameobject entry
Protected Member Functions inherited from Battlefield
void KickAfkPlayers ()
virtual void SendRemoveWorldStates (Player *)
void BroadcastPacketToZone (WorldPacket &data) const
void BroadcastPacketToQueue (WorldPacket &data) const
void BroadcastPacketToWar (WorldPacket &data) const
void AddCapturePoint (BfCapturePoint *cp)
void RegisterZone (uint32 zoneid)
bool HasPlayer (Player *player) const
void TeamCastSpell (TeamId team, int32 spellId)
Detailed Description
Definition at line 274 of file BattlefieldWG.h.
Constructor & Destructor Documentation
~BattlefieldWG()
BattlefieldWG::~BattlefieldWG () override
Definition at line 31 of file BattlefieldWG.cpp.
 {
     for (Workshop::const_iterator itr = WorkshopsList.begin(); itr != WorkshopsList.end(); ++itr)
         delete *itr;
     for (GameObjectBuilding::const_iterator itr = BuildingsInZone.begin(); itr != BuildingsInZone.end(); ++itr)
         delete *itr;
 }
References BuildingsInZone, and WorkshopsList.
Member Function Documentation
AddUpdateTenacity()
void BattlefieldWG::AddUpdateTenacity (Player * player)
Definition at line 1055 of file BattlefieldWG.cpp.
 {
     m_updateTenacityList.insert(player->GetGUID());
 }
References Object::GetGUID(), and m_updateTenacityList.
Referenced by OnPlayerJoinWar().
BrokenWallOrTower()
void BattlefieldWG::BrokenWallOrTower (TeamId team)
Called when a wall/tower is broken.
Update quest
Definition at line 929 of file BattlefieldWG.cpp.
 {
     // might be some use for this in the future. old code commented out below. KL
     /*    if (team == GetDefenderTeam())
         {
             for (GuidUnorderedSet::const_iterator itr = m_PlayersInWar[GetAttackerTeam()].begin(); itr != m_PlayersInWar[GetAttackerTeam()].end(); ++itr)
             {
                 if (Player* player = ObjectAccessor::FindPlayer(*itr))
                     IncrementQuest(player, WGQuest[player->GetTeamId()][2], true);
             }
         }*/
 }
Referenced by BfWGGameObjectBuilding::Destroyed().
CanInteractWithRelic()
bool BattlefieldWG::CanInteractWithRelic () inline
Define relic object.
Check if players can interact with the relic (Only if the last door has been broken)
Definition at line 394 of file BattlefieldWG.h.
 { return m_isRelicInteractible; }
References m_isRelicInteractible.
Referenced by ProcessEvent().
CapturePointTaken()
void BattlefieldWG::CapturePointTaken (uint32 areaId)
Definition at line 327 of file BattlefieldWG.cpp.
 {
     for (uint8 i = 0; i < BG_TEAMS_COUNT; ++i)
         for (GuidUnorderedSet::iterator itr = m_players[i].begin(); itr != m_players[i].end(); ++itr)
             if (Player* player = ObjectAccessor::FindPlayer(*itr))
                 if (player->GetAreaId() == areaId)
                     player->UpdateAreaDependentAuras(areaId);
 }
References BG_TEAMS_COUNT, ObjectAccessor::FindPlayer(), and Battlefield::m_players.
Referenced by WGWorkshop::GiveControlTo().
FillInitialWorldStates()
void BattlefieldWG::FillInitialWorldStates (WorldPacket & data) override virtual
Implements Battlefield.
Definition at line 884 of file BattlefieldWG.cpp.
 {
     data << uint32(BATTLEFIELD_WG_WORLD_STATE_ATTACKER) << uint32(GetAttackerTeam());
     data << uint32(BATTLEFIELD_WG_WORLD_STATE_DEFENDER) << uint32(GetDefenderTeam());
     data << uint32(BATTLEFIELD_WG_WORLD_STATE_ACTIVE) << uint32(IsWarTime() ? 0 : 1); // Note: cleanup these two, their names look awkward
     data << uint32(BATTLEFIELD_WG_WORLD_STATE_SHOW_WORLDSTATE) << uint32(IsWarTime() ? 1 : 0);
     for (uint32 i = 0; i < 2; ++i)
         data << ClockWorldState[i] << uint32(time(nullptr) + (m_Timer / 1000));
     data << uint32(BATTLEFIELD_WG_WORLD_STATE_VEHICLE_H) << uint32(GetData(BATTLEFIELD_WG_DATA_VEHICLE_H));
     data << uint32(BATTLEFIELD_WG_WORLD_STATE_MAX_VEHICLE_H) << GetData(BATTLEFIELD_WG_DATA_MAX_VEHICLE_H);
     data << uint32(BATTLEFIELD_WG_WORLD_STATE_VEHICLE_A) << uint32(GetData(BATTLEFIELD_WG_DATA_VEHICLE_A));
     data << uint32(BATTLEFIELD_WG_WORLD_STATE_MAX_VEHICLE_A) << GetData(BATTLEFIELD_WG_DATA_MAX_VEHICLE_A);
     for (GameObjectBuilding::const_iterator itr = BuildingsInZone.begin(); itr != BuildingsInZone.end(); ++itr)
         data << (*itr)->m_WorldState << (*itr)->m_State;
     for (Workshop::const_iterator itr = WorkshopsList.begin(); itr != WorkshopsList.end(); ++itr)
         if (*itr)
             data << WorkshopsData[(*itr)->workshopId].worldstate << (*itr)->state;
 }
References BATTLEFIELD_WG_DATA_MAX_VEHICLE_A, BATTLEFIELD_WG_DATA_MAX_VEHICLE_H, BATTLEFIELD_WG_DATA_VEHICLE_A, BATTLEFIELD_WG_DATA_VEHICLE_H, BATTLEFIELD_WG_WORLD_STATE_ACTIVE, BATTLEFIELD_WG_WORLD_STATE_ATTACKER, BATTLEFIELD_WG_WORLD_STATE_DEFENDER, BATTLEFIELD_WG_WORLD_STATE_MAX_VEHICLE_A, BATTLEFIELD_WG_WORLD_STATE_MAX_VEHICLE_H, BATTLEFIELD_WG_WORLD_STATE_SHOW_WORLDSTATE, BATTLEFIELD_WG_WORLD_STATE_VEHICLE_A, BATTLEFIELD_WG_WORLD_STATE_VEHICLE_H, BuildingsInZone, ClockWorldState, Battlefield::GetAttackerTeam(), GetData(), Battlefield::GetDefenderTeam(), Battlefield::IsWarTime(), Battlefield::m_Timer, WorkshopsData, WorkshopsList, and WGWorkshopData::worldstate.
Referenced by SendInitWorldStatesTo().
FindAndRemoveVehicleFromList()
bool BattlefieldWG::FindAndRemoveVehicleFromList (Unit * vehicle)
Definition at line 721 of file BattlefieldWG.cpp.
 {
     for (uint32 itr = 0; itr < 2; ++itr)
     {
         if (m_vehicles[itr].find(vehicle->GetGUID()) != m_vehicles[itr].end())
         {
             //m_vehicles[itr].erase(vehicle->GetGUID());
             if (itr == TEAM_HORDE)
                 UpdateData(BATTLEFIELD_WG_DATA_VEHICLE_H, -1);
             else
                 UpdateData(BATTLEFIELD_WG_DATA_VEHICLE_A, -1);
             return true;
         }
     }
     return false;
 }
References BATTLEFIELD_WG_DATA_VEHICLE_A, BATTLEFIELD_WG_DATA_VEHICLE_H, find(), Object::GetGUID(), m_vehicles, TEAM_HORDE, and Battlefield::UpdateData().
Referenced by OnUnitDeath().
GetAreaByGraveyardId()
uint32 BattlefieldWG::GetAreaByGraveyardId (uint8 gId) const
Definition at line 518 of file BattlefieldWG.cpp.
 {
     switch (gId)
     {
         case BATTLEFIELD_WG_GY_WORKSHOP_NE:
             return AREA_THE_SUNKEN_RING;
         case BATTLEFIELD_WG_GY_WORKSHOP_NW:
             return AREA_THE_BROKEN_TEMPLE;
         case BATTLEFIELD_WG_GY_WORKSHOP_SW:
             return AREA_WESTPARK_WORKSHOP;
         case BATTLEFIELD_WG_GY_WORKSHOP_SE:
             return AREA_EASTPARK_WORKSHOP;
     }
     return 0;
 }
References AREA_EASTPARK_WORKSHOP, AREA_THE_BROKEN_TEMPLE, AREA_THE_SUNKEN_RING, AREA_WESTPARK_WORKSHOP, BATTLEFIELD_WG_GY_WORKSHOP_NE, BATTLEFIELD_WG_GY_WORKSHOP_NW, BATTLEFIELD_WG_GY_WORKSHOP_SE, and BATTLEFIELD_WG_GY_WORKSHOP_SW.
Referenced by WGWorkshop::GiveControlTo().
GetData()
uint32 BattlefieldWG::GetData (uint32 data) const override virtual
Reimplemented from Battlefield.
Definition at line 861 of file BattlefieldWG.cpp.
 {
     // xinef: little hack, same area for default horde graveyard
     // this graveyard is the one of broken temple!
     if (data == AREA_THE_CHILLED_QUAGMIRE)
         data = AREA_THE_BROKEN_TEMPLE;
     switch (data)
     {
         // Used to determine when the phasing spells must be casted
         // See: SpellArea::IsFitToRequirements
         case AREA_THE_SUNKEN_RING:
         case AREA_THE_BROKEN_TEMPLE:
         case AREA_WESTPARK_WORKSHOP:
         case AREA_EASTPARK_WORKSHOP:
             // Graveyards and Workshops are controlled by the same team.
             if (BfGraveyard const* graveyard = GetGraveyardById(GetSpiritGraveyardId(data)))
                 return graveyard->GetControlTeamId();
     }
     return Battlefield::GetData(data);
 }
References AREA_EASTPARK_WORKSHOP, AREA_THE_BROKEN_TEMPLE, AREA_THE_CHILLED_QUAGMIRE, AREA_THE_SUNKEN_RING, AREA_WESTPARK_WORKSHOP, Battlefield::GetData(), Battlefield::GetGraveyardById(), and GetSpiritGraveyardId().
Referenced by FillInitialWorldStates(), OnBattleEnd(), OnCreatureCreate(), OnPlayerJoinWar(), UpdatedDestroyedTowerCount(), and UpdateVehicleCountWG().
GetHonorBuff()
uint32 BattlefieldWG::GetHonorBuff (int32 stack) const
Definition at line 1044 of file BattlefieldWG.cpp.
 {
     if (stack < 5)
         return 0;
     if (stack < 10)
         return SPELL_GREAT_HONOR;
     if (stack < 15)
         return SPELL_GREATER_HONOR;
     return SPELL_GREATEST_HONOR;
 }
References SPELL_GREAT_HONOR, SPELL_GREATER_HONOR, and SPELL_GREATEST_HONOR.
Referenced by UpdateTenacity().
GetRelic()
GameObject* BattlefieldWG::GetRelic () inline
Return pointer to relic object.
Definition at line 388 of file BattlefieldWG.h.
 { return GetGameObject(m_titansRelic); }
References Battlefield::GetGameObject(), and m_titansRelic.
Referenced by BfWGGameObjectBuilding::Destroyed(), OnBattleEnd(), and ProcessEvent().
GetSpiritGraveyardId()
uint8 BattlefieldWG::GetSpiritGraveyardId (uint32 areaId) const
Definition at line 492 of file BattlefieldWG.cpp.
 {
     switch (areaId)
     {
         case AREA_WINTERGRASP_FORTRESS:
             return BATTLEFIELD_WG_GY_KEEP;
         case AREA_THE_SUNKEN_RING:
             return BATTLEFIELD_WG_GY_WORKSHOP_NE;
         case AREA_THE_BROKEN_TEMPLE:
             return BATTLEFIELD_WG_GY_WORKSHOP_NW;
         case AREA_WESTPARK_WORKSHOP:
             return BATTLEFIELD_WG_GY_WORKSHOP_SW;
         case AREA_EASTPARK_WORKSHOP:
             return BATTLEFIELD_WG_GY_WORKSHOP_SE;
         case AREA_WINTERGRASP:
             return BATTLEFIELD_WG_GY_ALLIANCE;
         case AREA_THE_CHILLED_QUAGMIRE:
             return BATTLEFIELD_WG_GY_HORDE;
         default:
             LOG_ERROR("bg.battlefield", "BattlefieldWG::GetSpiritGraveyardId: Unexpected Area Id %u", areaId);
             break;
     }
     return 0;
 }
References AREA_EASTPARK_WORKSHOP, AREA_THE_BROKEN_TEMPLE, AREA_THE_CHILLED_QUAGMIRE, AREA_THE_SUNKEN_RING, AREA_WESTPARK_WORKSHOP, AREA_WINTERGRASP, AREA_WINTERGRASP_FORTRESS, BATTLEFIELD_WG_GY_ALLIANCE, BATTLEFIELD_WG_GY_HORDE, BATTLEFIELD_WG_GY_KEEP, BATTLEFIELD_WG_GY_WORKSHOP_NE, BATTLEFIELD_WG_GY_WORKSHOP_NW, BATTLEFIELD_WG_GY_WORKSHOP_SE, BATTLEFIELD_WG_GY_WORKSHOP_SW, and LOG_ERROR.
Referenced by GetData(), and OnCreatureCreate().
HandleKill()
void BattlefieldWG::HandleKill (Player * , Unit *) override virtual
Called when a Unit is kill in battlefield zone.
Reimplemented from Battlefield.
Definition at line 692 of file BattlefieldWG.cpp.
 {
     if (killer == victim)
         return;
     TeamId killerTeam = killer->GetTeamId();
     // xinef: tower cannons also grant rank
     if (victim->GetTypeId() == TYPEID_PLAYER || IsKeepNpc(victim->GetEntry()) || victim->GetEntry() == NPC_WINTERGRASP_TOWER_CANNON)
     {
         for (GuidUnorderedSet::const_iterator itr = m_PlayersInWar[killerTeam].begin(); itr != m_PlayersInWar[killerTeam].end(); ++itr)
             if (Player* player = ObjectAccessor::FindPlayer(*itr))
                 if (player->GetDistance2d(killer) < 40)
                     PromotePlayer(player);
         // Xinef: Allow to Skin non-released corpse
         if (victim->GetTypeId() == TYPEID_PLAYER)
             victim->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_SKINNABLE);
     }
     else if (victim->IsVehicle() && !killer->IsFriendlyTo(victim))
     {
         // Quest - Wintergrasp - PvP Kill - Vehicle
         for (GuidUnorderedSet::const_iterator itr = m_PlayersInWar[killerTeam].begin(); itr != m_PlayersInWar[killerTeam].end(); ++itr)
             if (Player* player = ObjectAccessor::FindPlayer(*itr))
                 if (player->GetDistance2d(killer) < 40)
                     player->KilledMonsterCredit(NPC_QUEST_PVP_KILL_VEHICLE);
     }
 }
References ObjectAccessor::FindPlayer(), Object::GetEntry(), Player::GetTeamId(), Object::GetTypeId(), Unit::IsFriendlyTo(), IsKeepNpc(), Unit::IsVehicle(), Battlefield::m_PlayersInWar, NPC_QUEST_PVP_KILL_VEHICLE, NPC_WINTERGRASP_TOWER_CANNON, PromotePlayer(), Object::SetFlag(), TYPEID_PLAYER, UNIT_FIELD_FLAGS, and UNIT_FLAG_SKINNABLE.
IsKeepNpc()
bool BattlefieldWG::IsKeepNpc (uint32 entry) inline
Definition at line 426 of file BattlefieldWG.h.
     {
         switch (entry)
         {
             case BATTLEFIELD_WG_NPC_GUARD_H:
             case BATTLEFIELD_WG_NPC_GUARD_A:
             case BATTLEFIELD_WG_NPC_VIERON_BLAZEFEATHER:
             case BATTLEFIELD_WG_NPC_BOWYER_RANDOLPH:
             case BATTLEFIELD_WG_NPC_STONE_GUARD_MUKAR:
             case BATTLEFIELD_WG_NPC_KNIGHT_DAMERON:
             case BATTLEFIELD_WG_NPC_HOODOO_MASTER_FU_JIN:
             case BATTLEFIELD_WG_NPC_SORCERESS_KAYLANA:
             case BATTLEFIELD_WG_NPC_CHAMPION_ROS_SLAI:
             case BATTLEFIELD_WG_NPC_MARSHAL_MAGRUDER:
             case BATTLEFIELD_WG_NPC_COMMANDER_DARDOSH:
             case BATTLEFIELD_WG_NPC_COMMANDER_ZANNETH:
             case BATTLEFIELD_WG_NPC_TACTICAL_OFFICER_KILRATH:
             case BATTLEFIELD_WG_NPC_TACTICAL_OFFICER_AHBRAMIS:
             case BATTLEFIELD_WG_NPC_HORDE_WARBRINGER:
             case BATTLEFIELD_WG_NPC_BRIGADIER_GENERAL:
             case BATTLEFIELD_WG_NPC_SIEGESMITH_STRONGHOOF:
             case BATTLEFIELD_WG_NPC_SIEGE_MASTER_STOUTHANDLE:
             case BATTLEFIELD_WG_NPC_PRIMALIST_MULFORT:
             case BATTLEFIELD_WG_NPC_ANCHORITE_TESSA:
             case BATTLEFIELD_WG_NPC_LIEUTENANT_MURP:
             case BATTLEFIELD_WG_NPC_SENIOR_DEMOLITIONIST_LEGOSO:
                 return true;
         }
         return false;
     }
References BATTLEFIELD_WG_NPC_ANCHORITE_TESSA, BATTLEFIELD_WG_NPC_BOWYER_RANDOLPH, BATTLEFIELD_WG_NPC_BRIGADIER_GENERAL, BATTLEFIELD_WG_NPC_CHAMPION_ROS_SLAI, BATTLEFIELD_WG_NPC_COMMANDER_DARDOSH, BATTLEFIELD_WG_NPC_COMMANDER_ZANNETH, BATTLEFIELD_WG_NPC_GUARD_A, BATTLEFIELD_WG_NPC_GUARD_H, BATTLEFIELD_WG_NPC_HOODOO_MASTER_FU_JIN, BATTLEFIELD_WG_NPC_HORDE_WARBRINGER, BATTLEFIELD_WG_NPC_KNIGHT_DAMERON, BATTLEFIELD_WG_NPC_LIEUTENANT_MURP, BATTLEFIELD_WG_NPC_MARSHAL_MAGRUDER, BATTLEFIELD_WG_NPC_PRIMALIST_MULFORT, BATTLEFIELD_WG_NPC_SENIOR_DEMOLITIONIST_LEGOSO, BATTLEFIELD_WG_NPC_SIEGE_MASTER_STOUTHANDLE, BATTLEFIELD_WG_NPC_SIEGESMITH_STRONGHOOF, BATTLEFIELD_WG_NPC_SORCERESS_KAYLANA, BATTLEFIELD_WG_NPC_STONE_GUARD_MUKAR, BATTLEFIELD_WG_NPC_TACTICAL_OFFICER_AHBRAMIS, BATTLEFIELD_WG_NPC_TACTICAL_OFFICER_KILRATH, and BATTLEFIELD_WG_NPC_VIERON_BLAZEFEATHER.
Referenced by HandleKill().
OnBattleEnd()
void BattlefieldWG::OnBattleEnd (bool endByTimer) override virtual
Called when battle end.
Remove relic and turret
Change banner/npc in keep if it needed
Saving battlestate
Reward honor/mark to player
Remove vehicle
Parameters
endByTimer : true if battle ended when timer is at 00:00, false if battle ended by clicking on relic
Reimplemented from Battlefield.
Definition at line 336 of file BattlefieldWG.cpp.
 {
     // Remove relic
     if (GameObject* go = GetRelic())
         go->RemoveFromWorld();
     m_titansRelic.Clear();
     // Remove turret
     for (GuidUnorderedSet::const_iterator itr = CanonList.begin(); itr != CanonList.end(); ++itr)
     {
         if (Creature* creature = GetCreature(*itr))
         {
             if (!endByTimer)
                 creature->SetFaction(WintergraspFaction[GetDefenderTeam()]);
             HideNpc(creature);
         }
     }
     // Change all npc in keep
     for (GuidUnorderedSet::const_iterator itr = KeepCreature[GetAttackerTeam()].begin(); itr != KeepCreature[GetAttackerTeam()].end(); ++itr)
         if (Creature* creature = GetCreature(*itr))
             HideNpc(creature);
     for (GuidUnorderedSet::const_iterator itr = KeepCreature[GetDefenderTeam()].begin(); itr != KeepCreature[GetDefenderTeam()].end(); ++itr)
         if (Creature* creature = GetCreature(*itr))
             ShowNpc(creature, true);
     // Change all npc out of keep
     for (GuidUnorderedSet::const_iterator itr = OutsideCreature[GetDefenderTeam()].begin(); itr != OutsideCreature[GetDefenderTeam()].end(); ++itr)
         if (Creature* creature = GetCreature(*itr))
             HideNpc(creature);
     for (GuidUnorderedSet::const_iterator itr = OutsideCreature[GetAttackerTeam()].begin(); itr != OutsideCreature[GetAttackerTeam()].end(); ++itr)
         if (Creature* creature = GetCreature(*itr))
             ShowNpc(creature, true);
     // Update all graveyard, control is to defender when no wartime
     for (uint8 i = 0; i < BATTLEFIELD_WG_GY_HORDE; i++)
         if (BfGraveyard* graveyard = GetGraveyardById(i))
             graveyard->GiveControlTo(GetDefenderTeam());
     for (GameObjectSet::const_iterator itr = m_KeepGameObject[GetDefenderTeam()].begin(); itr != m_KeepGameObject[GetDefenderTeam()].end(); ++itr)
         (*itr)->SetRespawnTime(RESPAWN_IMMEDIATELY);
     for (GameObjectSet::const_iterator itr = m_KeepGameObject[GetAttackerTeam()].begin(); itr != m_KeepGameObject[GetAttackerTeam()].end(); ++itr)
         (*itr)->SetRespawnTime(RESPAWN_ONE_DAY);
     // Update portal defender faction
     for (GameObjectSet::const_iterator itr = DefenderPortalList.begin(); itr != DefenderPortalList.end(); ++itr)
         (*itr)->SetUInt32Value(GAMEOBJECT_FACTION, WintergraspFaction[GetDefenderTeam()]);
     // Saving data
     for (GameObjectBuilding::const_iterator itr = BuildingsInZone.begin(); itr != BuildingsInZone.end(); ++itr)
     {
         (*itr)->Rebuild();
         (*itr)->Save();
         (*itr)->UpdateTurretAttack(true);
     }
     for (Workshop::const_iterator itr = WorkshopsList.begin(); itr != WorkshopsList.end(); ++itr)
         (*itr)->Save();
     for (uint8 team = 0; team < 2; ++team)
     {
         for (GuidUnorderedSet::const_iterator itr = m_vehicles[team].begin(); itr != m_vehicles[team].end(); ++itr)
             if (Creature* creature = GetCreature(*itr))
                 creature->DespawnOrUnsummon(1);
         m_vehicles[team].clear();
     }
     uint8 damagedTowersDef = GetData(BATTLEFIELD_WG_DATA_DAMAGED_TOWER_ATT);
     uint8 brokenTowersDef = GetData(BATTLEFIELD_WG_DATA_BROKEN_TOWER_ATT);
     uint8 damagedTowersAtt = GetData(BATTLEFIELD_WG_DATA_DAMAGED_TOWER_ATT);
     uint8 brokenTowersAtt = GetData(BATTLEFIELD_WG_DATA_INTACT_TOWER_ATT);
     uint32 spellDamagedDef = SPELL_DAMAGED_TOWER;
     uint32 spellFullDef = SPELL_DESTROYED_TOWER;
     uint32 spellDamagedAtt = SPELL_DAMAGED_BUILDING;
     uint32 spellFullAtt = SPELL_INTACT_BUILDING;
     if (!endByTimer)
     {
         brokenTowersDef = GetData(BATTLEFIELD_WG_DATA_INTACT_TOWER_ATT);
         brokenTowersAtt = GetData(BATTLEFIELD_WG_DATA_BROKEN_TOWER_ATT);
         spellDamagedDef = SPELL_DAMAGED_BUILDING;
         spellFullDef = SPELL_INTACT_BUILDING;
         spellDamagedAtt = SPELL_DAMAGED_TOWER;
         spellFullAtt = SPELL_DESTROYED_TOWER;
     }
     for (GuidUnorderedSet::const_iterator itr = m_PlayersInWar[GetDefenderTeam()].begin(); itr != m_PlayersInWar[GetDefenderTeam()].end(); ++itr)
     {
         if (Player* player = ObjectAccessor::FindPlayer(*itr))
         {
             // Victory in Wintergrasp
             player->AreaExploredOrEventHappens(GetDefenderTeam() ? 13183 : 13181); // HORDE / ALLY win wg quest id
             player->CastSpell(player, SPELL_ESSENCE_OF_WINTERGRASP, true);
             player->CastSpell(player, SPELL_VICTORY_REWARD, true);
             RemoveAurasFromPlayer(player);
             for (uint8 i = 0; i < damagedTowersDef; ++i)
                 player->CastSpell(player, spellDamagedDef, true);
             for (uint8 i = 0; i < brokenTowersDef; ++i)
                 player->CastSpell(player, spellFullDef, true);
         }
     }
     for (GuidUnorderedSet::const_iterator itr = m_PlayersInWar[GetAttackerTeam()].begin(); itr != m_PlayersInWar[GetAttackerTeam()].end(); ++itr)
         if (Player* player = ObjectAccessor::FindPlayer(*itr))
         {
             player->CastSpell(player, SPELL_DEFEAT_REWARD, true);
             RemoveAurasFromPlayer(player);
             for (uint8 i = 0; i < damagedTowersAtt; ++i)
                 player->CastSpell(player, spellDamagedAtt, true);
             for (uint8 i = 0; i < brokenTowersAtt; ++i)
                 player->CastSpell(player, spellFullAtt, true);
         }
     if (!endByTimer)
     {
         for (uint8 team = 0; team < 2; ++team)
         {
             for (GuidUnorderedSet::const_iterator itr = m_players[team].begin(); itr != m_players[team].end(); ++itr)
             {
                 if (Player* player = ObjectAccessor::FindPlayer(*itr))
                 {
                     player->RemoveAurasDueToSpell(m_DefenderTeam == TEAM_ALLIANCE ? SPELL_HORDE_CONTROL_PHASE_SHIFT : SPELL_ALLIANCE_CONTROL_PHASE_SHIFT, player->GetGUID());
                     player->AddAura(m_DefenderTeam == TEAM_HORDE ? SPELL_HORDE_CONTROL_PHASE_SHIFT : SPELL_ALLIANCE_CONTROL_PHASE_SHIFT, player);
                 }
             }
         }
     }
     // Clear players in war list at the end.
     m_PlayersInWar[TEAM_ALLIANCE].clear();
     m_PlayersInWar[TEAM_HORDE].clear();
     if (!endByTimer) // win alli/horde
         SendWarningToAllInZone((GetDefenderTeam() == TEAM_ALLIANCE) ? BATTLEFIELD_WG_TEXT_WIN_KEEP : (BATTLEFIELD_WG_TEXT_WIN_KEEP + 2));
     else // defend alli/horde
         SendWarningToAllInZone((GetDefenderTeam() == TEAM_ALLIANCE) ? BATTLEFIELD_WG_TEXT_DEFEND_KEEP : (BATTLEFIELD_WG_TEXT_DEFEND_KEEP + 2));
 }
References BATTLEFIELD_WG_DATA_BROKEN_TOWER_ATT, BATTLEFIELD_WG_DATA_DAMAGED_TOWER_ATT, BATTLEFIELD_WG_DATA_INTACT_TOWER_ATT, BATTLEFIELD_WG_GY_HORDE, BATTLEFIELD_WG_TEXT_DEFEND_KEEP, BATTLEFIELD_WG_TEXT_WIN_KEEP, BuildingsInZone, CanonList, ObjectGuid::Clear(), DefenderPortalList, ObjectAccessor::FindPlayer(), GAMEOBJECT_FACTION, Battlefield::GetAttackerTeam(), Battlefield::GetCreature(), GetData(), Battlefield::GetDefenderTeam(), Battlefield::GetGraveyardById(), GetRelic(), Battlefield::HideNpc(), KeepCreature, Battlefield::m_DefenderTeam, m_KeepGameObject, Battlefield::m_players, Battlefield::m_PlayersInWar, m_titansRelic, m_vehicles, OutsideCreature, RemoveAurasFromPlayer(), RESPAWN_IMMEDIATELY, RESPAWN_ONE_DAY, Battlefield::SendWarningToAllInZone(), Battlefield::ShowNpc(), SPELL_ALLIANCE_CONTROL_PHASE_SHIFT, SPELL_DAMAGED_BUILDING, SPELL_DAMAGED_TOWER, SPELL_DEFEAT_REWARD, SPELL_DESTROYED_TOWER, SPELL_ESSENCE_OF_WINTERGRASP, SPELL_HORDE_CONTROL_PHASE_SHIFT, SPELL_INTACT_BUILDING, SPELL_VICTORY_REWARD, TEAM_ALLIANCE, TEAM_HORDE, WintergraspFaction, and WorkshopsList.
OnBattleStart()
void BattlefieldWG::OnBattleStart () override virtual
Called when the battle start.
Spawn relic and turret
Rebuild tower and wall
Invite player to war
Reimplemented from Battlefield.
Definition at line 217 of file BattlefieldWG.cpp.
 {
     // Spawn titan relic
     GameObject* go = SpawnGameObject(GO_WINTERGRASP_TITAN_S_RELIC, 5440.0f, 2840.8f, 430.43f, 0);
     if (go)
     {
         // Update faction of relic, only attacker can click on
         go->SetUInt32Value(GAMEOBJECT_FACTION, WintergraspFaction[GetAttackerTeam()]);
         // Set in use (not allow to click on before last door is broken)
         go->SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
         // save guid
         m_titansRelic = go->GetGUID();
     }
     else
         LOG_ERROR("bg.battlefield", "WG: Failed to spawn titan relic.");
     // Update tower visibility and update faction
     for (GuidUnorderedSet::const_iterator itr = CanonList.begin(); itr != CanonList.end(); ++itr)
     {
         if (Creature* creature = GetCreature(*itr))
         {
             ShowNpc(creature, true);
             creature->SetFaction(WintergraspFaction[GetDefenderTeam()]);
         }
     }
     // Rebuild all wall
     for (GameObjectBuilding::const_iterator itr = BuildingsInZone.begin(); itr != BuildingsInZone.end(); ++itr)
     {
         if (*itr)
         {
             (*itr)->Rebuild();
             (*itr)->UpdateTurretAttack(false);
         }
     }
     SetData(BATTLEFIELD_WG_DATA_INTACT_TOWER_ATT, WG_MAX_ATTACKTOWERS);
     SetData(BATTLEFIELD_WG_DATA_BROKEN_TOWER_ATT, 0);
     SetData(BATTLEFIELD_WG_DATA_DAMAGED_TOWER_ATT, 0);
     // Update graveyard (in no war time all graveyard is to deffender, in war time, depend of base)
     for (Workshop::const_iterator itr = WorkshopsList.begin(); itr != WorkshopsList.end(); ++itr)
         if (*itr)
             (*itr)->UpdateGraveyardAndWorkshop();
     for (uint8 team = 0; team < 2; ++team)
         for (GuidUnorderedSet::const_iterator itr = m_players[team].begin(); itr != m_players[team].end(); ++itr)
         {
             // Kick player in orb room, TODO: offline player ?
             if (Player* player = ObjectAccessor::FindPlayer(*itr))
             {
                 float x, y, z;
                 player->GetPosition(x, y, z);
                 if (5500 > x && x > 5392 && y < 2880 && y > 2800 && z < 480)
                     player->TeleportTo(571, 5349.8686f, 2838.481f, 409.240f, 0.046328f);
                 SendInitWorldStatesTo(player);
             }
         }
     // Initialize vehicle counter
     UpdateCounterVehicle(true);
     // Send start warning to all players
     SendWarningToAllInZone(BATTLEFIELD_WG_TEXT_START);
     // Xinef: reset tenacity counter
     m_tenacityStack = 0;
     m_tenacityUpdateTimer = 20000;
     if (sWorld->getBoolConfig(CONFIG_BATTLEGROUND_QUEUE_ANNOUNCER_ENABLE))
         sWorld->SendWorldText(BATTLEFIELD_WG_WORLD_START_MESSAGE);
 }
References BATTLEFIELD_WG_DATA_BROKEN_TOWER_ATT, BATTLEFIELD_WG_DATA_DAMAGED_TOWER_ATT, BATTLEFIELD_WG_DATA_INTACT_TOWER_ATT, BATTLEFIELD_WG_TEXT_START, BATTLEFIELD_WG_WORLD_START_MESSAGE, BuildingsInZone, CanonList, CONFIG_BATTLEGROUND_QUEUE_ANNOUNCER_ENABLE, ObjectAccessor::FindPlayer(), GAMEOBJECT_FACTION, GAMEOBJECT_FLAGS, Battlefield::GetAttackerTeam(), Battlefield::GetCreature(), Battlefield::GetDefenderTeam(), Object::GetGUID(), GO_FLAG_NOT_SELECTABLE, GO_WINTERGRASP_TITAN_S_RELIC, LOG_ERROR, Battlefield::m_players, m_tenacityStack, m_tenacityUpdateTimer, m_titansRelic, SendInitWorldStatesTo(), Battlefield::SendWarningToAllInZone(), Battlefield::SetData(), Object::SetFlag(), Object::SetUInt32Value(), Battlefield::ShowNpc(), Battlefield::SpawnGameObject(), sWorld, UpdateCounterVehicle(), WG_MAX_ATTACKTOWERS, WintergraspFaction, WorkshopsList, G3D::x, G3D::y, and G3D::z.
OnCreatureCreate()
void BattlefieldWG::OnCreatureCreate (Creature * creature) override virtual
Called when a creature is created.
Update vehicle count
Reimplemented from ZoneScript.
Definition at line 535 of file BattlefieldWG.cpp.
 {
     // Accessing to db spawned creatures
     switch (creature->GetEntry())
     {
         case NPC_DWARVEN_SPIRIT_GUIDE:
         case NPC_TAUNKA_SPIRIT_GUIDE:
             {
                 TeamId teamId = (creature->GetEntry() == NPC_DWARVEN_SPIRIT_GUIDE ? TEAM_ALLIANCE : TEAM_HORDE);
                 uint8 graveyardId = GetSpiritGraveyardId(creature->GetAreaId());
                 // xinef: little workaround, there are 2 spirit guides in same area
                 if (creature->IsWithinDist2d(5103.0f, 3461.5f, 5.0f))
                     graveyardId = BATTLEFIELD_WG_GY_WORKSHOP_NW;
                 if (m_GraveyardList[graveyardId])
                     m_GraveyardList[graveyardId]->SetSpirit(creature, teamId);
                 break;
             }
     }
     // untested code - not sure if it is valid.
     if (IsWarTime())
     {
         switch (creature->GetEntry())
         {
             case NPC_WINTERGRASP_SIEGE_ENGINE_ALLIANCE:
             case NPC_WINTERGRASP_SIEGE_ENGINE_HORDE:
             case NPC_WINTERGRASP_CATAPULT:
             case NPC_WINTERGRASP_DEMOLISHER:
                 {
                     if (!creature->IsSummon() || !creature->ToTempSummon()->GetSummonerGUID())
                         return;
                     Player* creator = ObjectAccessor::FindPlayer(creature->ToTempSummon()->GetSummonerGUID());
                     if (!creator)
                         return;
                     TeamId team = creator->GetTeamId();
                     if (team == TEAM_HORDE)
                     {
                         if (GetData(BATTLEFIELD_WG_DATA_VEHICLE_H) < GetData(BATTLEFIELD_WG_DATA_MAX_VEHICLE_H))
{
                             UpdateData(BATTLEFIELD_WG_DATA_VEHICLE_H, 1);
                             creature->CastSpell(creature, SPELL_HORDE_FLAG, true);
                             m_vehicles[team].insert(creature->GetGUID());
                             UpdateVehicleCountWG();
                         }
                         else
{
                             creature->DespawnOrUnsummon();
                             return;
                         }
                     }
                     else
                     {
                         if (GetData(BATTLEFIELD_WG_DATA_VEHICLE_A) < GetData(BATTLEFIELD_WG_DATA_MAX_VEHICLE_A))
{
                             UpdateData(BATTLEFIELD_WG_DATA_VEHICLE_A, 1);
                             creature->CastSpell(creature, SPELL_ALLIANCE_FLAG, true);
                             m_vehicles[team].insert(creature->GetGUID());
                             UpdateVehicleCountWG();
                         }
                         else
{
                             creature->DespawnOrUnsummon();
                             return;
                         }
                     }
                     break;
                 }
             case NPC_WINTERGRASP_SIEGE_ENGINE_TURRET_HORDE:
             case NPC_WINTERGRASP_SIEGE_ENGINE_TURRET_ALLIANCE:
                 {
                     if (!creature->IsSummon() || !creature->ToTempSummon()->GetSummonerGUID())
                         return;
                     if (Unit* owner = creature->ToTempSummon()->GetSummonerUnit())
                         creature->SetFaction(owner->GetFaction());
                     break;
                 }
         }
     }
 }
References BATTLEFIELD_WG_DATA_MAX_VEHICLE_A, BATTLEFIELD_WG_DATA_MAX_VEHICLE_H, BATTLEFIELD_WG_DATA_VEHICLE_A, BATTLEFIELD_WG_DATA_VEHICLE_H, BATTLEFIELD_WG_GY_WORKSHOP_NW, Unit::CastSpell(), Creature::DespawnOrUnsummon(), ObjectAccessor::FindPlayer(), WorldObject::GetAreaId(), GetData(), Object::GetEntry(), Object::GetGUID(), GetSpiritGraveyardId(), TempSummon::GetSummonerGUID(), TempSummon::GetSummonerUnit(), Player::GetTeamId(), Unit::IsSummon(), Battlefield::IsWarTime(), WorldObject::IsWithinDist2d(), Battlefield::m_GraveyardList, m_vehicles, NPC_DWARVEN_SPIRIT_GUIDE, NPC_TAUNKA_SPIRIT_GUIDE, NPC_WINTERGRASP_CATAPULT, NPC_WINTERGRASP_DEMOLISHER, NPC_WINTERGRASP_SIEGE_ENGINE_ALLIANCE, NPC_WINTERGRASP_SIEGE_ENGINE_HORDE, NPC_WINTERGRASP_SIEGE_ENGINE_TURRET_ALLIANCE, NPC_WINTERGRASP_SIEGE_ENGINE_TURRET_HORDE, Unit::SetFaction(), SPELL_ALLIANCE_FLAG, SPELL_HORDE_FLAG, TEAM_ALLIANCE, TEAM_HORDE, Unit::ToTempSummon(), Battlefield::UpdateData(), and UpdateVehicleCountWG().
OnCreatureRemove()
void BattlefieldWG::OnCreatureRemove (Creature * creature) override virtual
Called when a creature is removed.
Update vehicle count
Reimplemented from ZoneScript.
Definition at line 619 of file BattlefieldWG.cpp.
 {
     /* possibly can be used later
         if (IsWarTime())
         {
             switch (creature->GetEntry())
             {
                 case NPC_WINTERGRASP_SIEGE_ENGINE_ALLIANCE:
                 case NPC_WINTERGRASP_SIEGE_ENGINE_HORDE:
                 case NPC_WINTERGRASP_CATAPULT:
                 case NPC_WINTERGRASP_DEMOLISHER:
                 {
                     uint8 team;
                     if (creature->GetFaction() == WintergraspFaction[TEAM_ALLIANCE])
                         team = TEAM_ALLIANCE;
                     else if (creature->GetFaction() == WintergraspFaction[TEAM_HORDE])
                         team = TEAM_HORDE;
                     else
                         return;
                     m_vehicles[team].erase(creature->GetGUID());
                     if (team == TEAM_HORDE)
                         UpdateData(BATTLEFIELD_WG_DATA_VEHICLE_H, -1);
                     else
                         UpdateData(BATTLEFIELD_WG_DATA_VEHICLE_A, -1);
                     UpdateVehicleCountWG();
                     break;
                 }
             }
         }*/
 }
OnGameObjectCreate()
void BattlefieldWG::OnGameObjectCreate (GameObject * go) override virtual
Called when a gameobject is created.
Reimplemented from ZoneScript.
Definition at line 652 of file BattlefieldWG.cpp.
 {
     uint8 workshopId = 0;
     switch (go->GetEntry())
     {
         case GO_WINTERGRASP_FACTORY_BANNER_NE:
             workshopId = BATTLEFIELD_WG_WORKSHOP_NE;
             break;
         case GO_WINTERGRASP_FACTORY_BANNER_NW:
             workshopId = BATTLEFIELD_WG_WORKSHOP_NW;
             break;
         case GO_WINTERGRASP_FACTORY_BANNER_SE:
             workshopId = BATTLEFIELD_WG_WORKSHOP_SE;
             break;
         case GO_WINTERGRASP_FACTORY_BANNER_SW:
             workshopId = BATTLEFIELD_WG_WORKSHOP_SW;
             break;
         default:
             return;
     }
     for (Workshop::const_iterator itr = WorkshopsList.begin(); itr != WorkshopsList.end(); ++itr)
     {
         if (WGWorkshop* workshop = (*itr))
         {
             if (workshop->workshopId == workshopId)
             {
                 WintergraspCapturePoint* capturePoint = new WintergraspCapturePoint(this, GetAttackerTeam());
                 capturePoint->SetCapturePointData(go);
                 capturePoint->LinkToWorkshop(workshop);
                 AddCapturePoint(capturePoint);
                 break;
             }
         }
     }
 }
References Battlefield::AddCapturePoint(), BATTLEFIELD_WG_WORKSHOP_NE, BATTLEFIELD_WG_WORKSHOP_NW, BATTLEFIELD_WG_WORKSHOP_SE, BATTLEFIELD_WG_WORKSHOP_SW, Battlefield::GetAttackerTeam(), Object::GetEntry(), GO_WINTERGRASP_FACTORY_BANNER_NE, GO_WINTERGRASP_FACTORY_BANNER_NW, GO_WINTERGRASP_FACTORY_BANNER_SE, GO_WINTERGRASP_FACTORY_BANNER_SW, WintergraspCapturePoint::LinkToWorkshop(), BfCapturePoint::SetCapturePointData(), and WorkshopsList.
OnPlayerEnterZone()
void BattlefieldWG::OnPlayerEnterZone (Player * player) override virtual
Called when player enters in WG zone.
Update aura
Update worldstate
Parameters
player : Player who enters the zone
Reimplemented from Battlefield.
Definition at line 846 of file BattlefieldWG.cpp.
 {
     if (!m_isActive)
         RemoveAurasFromPlayer(player);
     player->AddAura(m_DefenderTeam == TEAM_HORDE ? SPELL_HORDE_CONTROL_PHASE_SHIFT : SPELL_ALLIANCE_CONTROL_PHASE_SHIFT, player);
     // Send worldstate to player
     SendInitWorldStatesTo(player);
     // xinef: Attacker, if hidden in relic room kick him out
     if (player->GetTeamId() == GetAttackerTeam())
         if (player->GetPositionX() > 5400.0f && player->GetPositionX() < 5490.0f && player->GetPositionY() > 2803.0f && player->GetPositionY() < 2878.0f)
             KickPlayerFromBattlefield(player->GetGUID());
 }
References Unit::AddAura(), Battlefield::GetAttackerTeam(), Object::GetGUID(), Position::GetPositionX(), Position::GetPositionY(), Player::GetTeamId(), Battlefield::KickPlayerFromBattlefield(), Battlefield::m_DefenderTeam, Battlefield::m_isActive, RemoveAurasFromPlayer(), SendInitWorldStatesTo(), SPELL_ALLIANCE_CONTROL_PHASE_SHIFT, SPELL_HORDE_CONTROL_PHASE_SHIFT, and TEAM_HORDE.
OnPlayerJoinWar()
void BattlefieldWG::OnPlayerJoinWar (Player * player) override virtual
Called when player accept invite to join battle.
Update aura
Teleport if it needed
Update worldstate
Update tenacity
Parameters
player Player who accepted invite
Reimplemented from Battlefield.
Definition at line 792 of file BattlefieldWG.cpp.
 {
     RemoveAurasFromPlayer(player);
     player->CastSpell(player, SPELL_RECRUIT, true);
     AddUpdateTenacity(player);
     if (player->GetTeamId() == GetDefenderTeam())
         player->TeleportTo(571, 5345, 2842, 410, 3.14f);
     else
     {
         if (player->GetTeamId() == TEAM_HORDE)
             player->TeleportTo(571, 5025.857422f, 3674.628906f, 362.737122f, 4.135169f);
         else
             player->TeleportTo(571, 5101.284f, 2186.564f, 373.549f, 3.812f);
     }
     if (player->GetTeamId() == GetAttackerTeam())
     {
         if (GetData(BATTLEFIELD_WG_DATA_BROKEN_TOWER_ATT) < 3)
             player->SetAuraStack(SPELL_TOWER_CONTROL, player, 3 - GetData(BATTLEFIELD_WG_DATA_BROKEN_TOWER_ATT));
     }
     else
     {
         if (GetData(BATTLEFIELD_WG_DATA_BROKEN_TOWER_ATT) > 0)
             player->SetAuraStack(SPELL_TOWER_CONTROL, player, GetData(BATTLEFIELD_WG_DATA_BROKEN_TOWER_ATT));
     }
     SendInitWorldStatesTo(player);
 }
References AddUpdateTenacity(), BATTLEFIELD_WG_DATA_BROKEN_TOWER_ATT, Unit::CastSpell(), Battlefield::GetAttackerTeam(), GetData(), Battlefield::GetDefenderTeam(), Player::GetTeamId(), RemoveAurasFromPlayer(), SendInitWorldStatesTo(), Unit::SetAuraStack(), SPELL_RECRUIT, SPELL_TOWER_CONTROL, TEAM_HORDE, and Player::TeleportTo().
OnPlayerLeaveWar()
void BattlefieldWG::OnPlayerLeaveWar (Player * player) override virtual
Called when player left the battle.
Update player aura
Parameters
player : Player who left the battle
Reimplemented from Battlefield.
Definition at line 822 of file BattlefieldWG.cpp.
 {
     // Remove all aura from WG // TODO: false we can go out of this zone on retail and keep Rank buff, remove on end of WG
     if (!player->GetSession()->PlayerLogout())
     {
         if (player->GetVehicle())                              // Remove vehicle of player if he go out.
             player->GetVehicle()->Dismiss();
         RemoveAurasFromPlayer(player);
     }
     RemoveUpdateTenacity(player);
 }
References Vehicle::Dismiss(), Player::GetSession(), Unit::GetVehicle(), WorldSession::PlayerLogout(), RemoveAurasFromPlayer(), and RemoveUpdateTenacity().
OnPlayerLeaveZone()
void BattlefieldWG::OnPlayerLeaveZone (Player * player) override virtual
Called when player left the WG zone.
Parameters
player : Player who left the zone
Reimplemented from Battlefield.
Definition at line 835 of file BattlefieldWG.cpp.
 {
     if (!m_isActive)
         RemoveAurasFromPlayer(player);
     player->RemoveAurasDueToSpell(SPELL_HORDE_CONTROLS_FACTORY_PHASE_SHIFT);
     player->RemoveAurasDueToSpell(SPELL_ALLIANCE_CONTROLS_FACTORY_PHASE_SHIFT);
     player->RemoveAurasDueToSpell(SPELL_HORDE_CONTROL_PHASE_SHIFT);
     player->RemoveAurasDueToSpell(SPELL_ALLIANCE_CONTROL_PHASE_SHIFT);
 }
References Battlefield::m_isActive, Unit::RemoveAurasDueToSpell(), RemoveAurasFromPlayer(), SPELL_ALLIANCE_CONTROL_PHASE_SHIFT, SPELL_ALLIANCE_CONTROLS_FACTORY_PHASE_SHIFT, SPELL_HORDE_CONTROL_PHASE_SHIFT, and SPELL_HORDE_CONTROLS_FACTORY_PHASE_SHIFT.
OnStartGrouping()
void BattlefieldWG::OnStartGrouping () override virtual
Called when grouping starts (15 minutes before battlestart)
Invite all player in zone to join queue
Reimplemented from Battlefield.
Definition at line 486 of file BattlefieldWG.cpp.
 {
     if (!IsWarTime())
         SendWarningToAllInZone(BATTLEFIELD_WG_TEXT_WILL_START);
 }
References BATTLEFIELD_WG_TEXT_WILL_START, Battlefield::IsWarTime(), and Battlefield::SendWarningToAllInZone().
OnUnitDeath()
void BattlefieldWG::OnUnitDeath (Unit * unit) override virtual
Reimplemented from ZoneScript.
Definition at line 738 of file BattlefieldWG.cpp.
 {
     if (IsWarTime())
         if (unit->IsVehicle())
             if (FindAndRemoveVehicleFromList(unit))
                 UpdateVehicleCountWG();
 }
References FindAndRemoveVehicleFromList(), Unit::IsVehicle(), Battlefield::IsWarTime(), and UpdateVehicleCountWG().
ProcessEvent()
void BattlefieldWG::ProcessEvent (WorldObject * obj, uint32 eventId) override virtual
Reimplemented from ZoneScript.
Definition at line 992 of file BattlefieldWG.cpp.
 {
     if (!obj || !IsWarTime())
         return;
     // We handle only gameobjects here
     GameObject* go = obj->ToGameObject();
     if (!go)
         return;
     // On click on titan relic
     if (go->GetEntry() == GO_WINTERGRASP_TITAN_S_RELIC)
     {
         if (CanInteractWithRelic())
         {
             EndBattle(false);
         }
         else if (GameObject* relic = GetRelic())
         {
             relic->SetRespawnTime(RESPAWN_IMMEDIATELY);
         }
     }
     // if destroy or damage event, search the wall/tower and update worldstate/send warning message
     for (GameObjectBuilding::const_iterator itr = BuildingsInZone.begin(); itr != BuildingsInZone.end(); ++itr)
     {
         if (GameObject* build = ObjectAccessor::GetGameObject(*obj, (*itr)->m_Build))
         {
             if (go->GetEntry() == build->GetEntry())
             {
                 if (build->GetGOInfo()->building.damagedEvent == eventId)
                     (*itr)->Damaged();
                 if (build->GetGOInfo()->building.destroyedEvent == eventId)
                     (*itr)->Destroyed();
                 break;
             }
         }
     }
 }
References BuildingsInZone, CanInteractWithRelic(), Battlefield::EndBattle(), Object::GetEntry(), ObjectAccessor::GetGameObject(), GetRelic(), GO_WINTERGRASP_TITAN_S_RELIC, Battlefield::IsWarTime(), RESPAWN_IMMEDIATELY, and Object::ToGameObject().
PromotePlayer()
void BattlefieldWG::PromotePlayer (Player * killer)
Definition at line 747 of file BattlefieldWG.cpp.
 {
     if (!m_isActive)
         return;
     // Updating rank of player
     if (Aura* recruitAura = killer->GetAura(SPELL_RECRUIT))
     {
         if (recruitAura->GetStackAmount() >= 5)
         {
             killer->RemoveAura(SPELL_RECRUIT);
             killer->CastSpell(killer, SPELL_CORPORAL, true);
             SendWarningToPlayer(killer, BATTLEFIELD_WG_TEXT_FIRSTRANK);
         }
         else
         {
             killer->CastSpell(killer, SPELL_RECRUIT, true);
         }
     }
     else if (Aura* corporalAura = killer->GetAura(SPELL_CORPORAL))
     {
         if (corporalAura->GetStackAmount() >= 5)
         {
             killer->RemoveAura(SPELL_CORPORAL);
             killer->CastSpell(killer, SPELL_LIEUTENANT, true);
             SendWarningToPlayer(killer, BATTLEFIELD_WG_TEXT_SECONDRANK);
         }
         else
         {
             killer->CastSpell(killer, SPELL_CORPORAL, true);
         }
     }
 }
References BATTLEFIELD_WG_TEXT_FIRSTRANK, BATTLEFIELD_WG_TEXT_SECONDRANK, Unit::CastSpell(), Unit::GetAura(), Battlefield::m_isActive, Unit::RemoveAura(), Battlefield::SendWarningToPlayer(), SPELL_CORPORAL, SPELL_LIEUTENANT, and SPELL_RECRUIT.
Referenced by HandleKill().
RemoveAurasFromPlayer()
void BattlefieldWG::RemoveAurasFromPlayer (Player * player)
Definition at line 780 of file BattlefieldWG.cpp.
 {
     player->RemoveAurasDueToSpell(SPELL_RECRUIT);
     player->RemoveAurasDueToSpell(SPELL_CORPORAL);
     player->RemoveAurasDueToSpell(SPELL_LIEUTENANT);
     player->RemoveAurasDueToSpell(SPELL_TOWER_CONTROL);
     player->RemoveAurasDueToSpell(SPELL_SPIRITUAL_IMMUNITY);
     player->RemoveAurasDueToSpell(SPELL_TENACITY);
     player->RemoveAurasDueToSpell(SPELL_ESSENCE_OF_WINTERGRASP);
     player->RemoveAurasDueToSpell(SPELL_WINTERGRASP_RESTRICTED_FLIGHT_AREA);
 }
References Unit::RemoveAurasDueToSpell(), SPELL_CORPORAL, SPELL_ESSENCE_OF_WINTERGRASP, SPELL_LIEUTENANT, SPELL_RECRUIT, SPELL_SPIRITUAL_IMMUNITY, SPELL_TENACITY, SPELL_TOWER_CONTROL, and SPELL_WINTERGRASP_RESTRICTED_FLIGHT_AREA.
Referenced by OnBattleEnd(), OnPlayerEnterZone(), OnPlayerJoinWar(), OnPlayerLeaveWar(), and OnPlayerLeaveZone().
RemoveUpdateTenacity()
void BattlefieldWG::RemoveUpdateTenacity (Player * player)
Definition at line 1060 of file BattlefieldWG.cpp.
 {
     m_updateTenacityList.erase(player->GetGUID());
     m_updateTenacityList.insert(ObjectGuid::Empty);
 }
References ObjectGuid::Empty, Object::GetGUID(), and m_updateTenacityList.
Referenced by OnPlayerLeaveWar().
SendInitWorldStatesTo()
void BattlefieldWG::SendInitWorldStatesTo (Player * player)
Definition at line 907 of file BattlefieldWG.cpp.
 {
     WorldPacket data(SMSG_INIT_WORLD_STATES, (4 + 4 + 4 + 2 + (BuildingsInZone.size() * 8) + (WorkshopsList.size() * 8)));
     data << uint32(m_MapId);
     data << uint32(m_ZoneId);
     data << uint32(0);
     data << uint16(10 + BuildingsInZone.size() + WorkshopsList.size()); // Number of fields
     FillInitialWorldStates(data);
     player->GetSession()->SendPacket(&data);
 }
References BuildingsInZone, FillInitialWorldStates(), Player::GetSession(), Battlefield::m_MapId, Battlefield::m_ZoneId, WorldSession::SendPacket(), SMSG_INIT_WORLD_STATES, and WorkshopsList.
Referenced by OnBattleStart(), OnPlayerEnterZone(), OnPlayerJoinWar(), and SendInitWorldStatesToAll().
SendInitWorldStatesToAll()
void BattlefieldWG::SendInitWorldStatesToAll () override virtual
Send all worldstate data to all player in zone.
Implements Battlefield.
Definition at line 921 of file BattlefieldWG.cpp.
 {
     for (uint8 team = 0; team < 2; team++)
         for (GuidUnorderedSet::iterator itr = m_players[team].begin(); itr != m_players[team].end(); ++itr)
             if (Player* player = ObjectAccessor::FindPlayer(*itr))
                 SendInitWorldStatesTo(player);
 }
References ObjectAccessor::FindPlayer(), Battlefield::m_players, and SendInitWorldStatesTo().
Referenced by UpdatedDestroyedTowerCount().
SetRelicInteractible()
void BattlefieldWG::SetRelicInteractible (bool allow) inline
Define if player can interact with the relic.
Definition at line 397 of file BattlefieldWG.h.
 { m_isRelicInteractible = allow; }
References m_isRelicInteractible.
Referenced by BfWGGameObjectBuilding::Destroyed().
SetupBattlefield()
bool BattlefieldWG::SetupBattlefield () override virtual
Called when battlefield is setup, at server start.
Reimplemented from Battlefield.
Definition at line 40 of file BattlefieldWG.cpp.
 {
     m_TypeId = BATTLEFIELD_WG;                              // See enum BattlefieldTypes
     m_BattleId = BATTLEFIELD_BATTLEID_WG;
     m_ZoneId = BATTLEFIELD_WG_ZONEID;
     m_MapId = BATTLEFIELD_WG_MAPID;
     m_Map = sMapMgr->FindMap(m_MapId, 0);
     // init stalker AFTER setting map id... we spawn it at map=random memory value?...
     InitStalker(BATTLEFIELD_WG_NPC_STALKER, WintergraspStalkerPos[0], WintergraspStalkerPos[1], WintergraspStalkerPos[2], WintergraspStalkerPos[3]);
     m_MaxPlayer = sWorld->getIntConfig(CONFIG_WINTERGRASP_PLR_MAX);
     m_IsEnabled = sWorld->getBoolConfig(CONFIG_WINTERGRASP_ENABLE);
     m_MinPlayer = sWorld->getIntConfig(CONFIG_WINTERGRASP_PLR_MIN);
     m_MinLevel = sWorld->getIntConfig(CONFIG_WINTERGRASP_PLR_MIN_LVL);
     m_BattleTime = sWorld->getIntConfig(CONFIG_WINTERGRASP_BATTLETIME) * MINUTE * IN_MILLISECONDS;
     m_NoWarBattleTime = sWorld->getIntConfig(CONFIG_WINTERGRASP_NOBATTLETIME) * MINUTE * IN_MILLISECONDS;
     m_RestartAfterCrash = sWorld->getIntConfig(CONFIG_WINTERGRASP_RESTART_AFTER_CRASH) * MINUTE * IN_MILLISECONDS;
     m_TimeForAcceptInvite = 20;
     m_StartGroupingTimer = 15 * MINUTE * IN_MILLISECONDS;
     m_StartGrouping = false;
     m_tenacityStack = 0;
     m_titansRelic.Clear();
     KickPosition.Relocate(5728.117f, 2714.346f, 697.733f, 0);
     KickPosition.m_mapId = m_MapId;
     RegisterZone(m_ZoneId);
     m_Data32.resize(BATTLEFIELD_WG_DATA_MAX);
     m_saveTimer = 60000;
     // Init GraveYards
     SetGraveyardNumber(BATTLEFIELD_WG_GRAVEYARD_MAX);
     // Load from db
     if ((sWorld->getWorldState(BATTLEFIELD_WG_WORLD_STATE_ACTIVE) == 0) && (sWorld->getWorldState(BATTLEFIELD_WG_WORLD_STATE_DEFENDER) == 0)
             && (sWorld->getWorldState(ClockWorldState[0]) == 0))
     {
         sWorld->setWorldState(BATTLEFIELD_WG_WORLD_STATE_ACTIVE, uint64(false));
         sWorld->setWorldState(BATTLEFIELD_WG_WORLD_STATE_DEFENDER, uint64(urand(0, 1)));
         sWorld->setWorldState(ClockWorldState[0], uint64(m_NoWarBattleTime));
     }
     m_isActive = bool(sWorld->getWorldState(BATTLEFIELD_WG_WORLD_STATE_ACTIVE));
     m_DefenderTeam = TeamId(sWorld->getWorldState(BATTLEFIELD_WG_WORLD_STATE_DEFENDER));
     m_Timer = sWorld->getWorldState(ClockWorldState[0]);
     if (m_isActive)
     {
         m_isActive = false;
         m_Timer = m_RestartAfterCrash;
     }
     for (uint8 i = 0; i < BATTLEFIELD_WG_GRAVEYARD_MAX; i++)
     {
         BfGraveyardWG* graveyard = new BfGraveyardWG(this);
         // When between games, the graveyard is controlled by the defending team
         if (WGGraveYard[i].startcontrol == TEAM_NEUTRAL)
             graveyard->Initialize(m_DefenderTeam, WGGraveYard[i].gyid);
         else
             graveyard->Initialize(WGGraveYard[i].startcontrol, WGGraveYard[i].gyid);
         graveyard->SetTextId(WGGraveYard[i].textid);
         m_GraveyardList[i] = graveyard;
     }
     // Spawn workshop creatures and gameobjects
     for (uint8 i = 0; i < WG_MAX_WORKSHOP; i++)
     {
         WGWorkshop* workshop = new WGWorkshop(this, i);
         if (i < BATTLEFIELD_WG_WORKSHOP_KEEP_WEST)
             workshop->GiveControlTo(GetAttackerTeam(), true);
         else
             workshop->GiveControlTo(GetDefenderTeam(), true);
         // Note: Capture point is added once the gameobject is created.
         WorkshopsList.insert(workshop);
     }
     // Spawn NPCs in the defender's keep, both Horde and Alliance
     for (uint8 i = 0; i < WG_MAX_KEEP_NPC; i++)
     {
         // Horde npc
         if (Creature* creature = SpawnCreature(WGKeepNPC[i].entryHorde, WGKeepNPC[i].x, WGKeepNPC[i].y, WGKeepNPC[i].z, WGKeepNPC[i].o, TEAM_HORDE))
             KeepCreature[TEAM_HORDE].insert(creature->GetGUID());
         // Alliance npc
         if (Creature* creature = SpawnCreature(WGKeepNPC[i].entryAlliance, WGKeepNPC[i].x, WGKeepNPC[i].y, WGKeepNPC[i].z, WGKeepNPC[i].o, TEAM_ALLIANCE))
             KeepCreature[TEAM_ALLIANCE].insert(creature->GetGUID());
     }
     // Hide NPCs from the Attacker's team in the keep
     for (GuidUnorderedSet::const_iterator itr = KeepCreature[GetAttackerTeam()].begin(); itr != KeepCreature[GetAttackerTeam()].end(); ++itr)
         if (Creature* creature = GetCreature(*itr))
             HideNpc(creature);
     // Spawn Horde NPCs outside the keep
     for (uint8 i = 0; i < WG_OUTSIDE_ALLIANCE_NPC; i++)
         if (Creature* creature = SpawnCreature(WGOutsideNPC[i].entryHorde, WGOutsideNPC[i].x, WGOutsideNPC[i].y, WGOutsideNPC[i].z, WGOutsideNPC[i].o, TEAM_HORDE))
             OutsideCreature[TEAM_HORDE].insert(creature->GetGUID());
     // Spawn Alliance NPCs outside the keep
     for (uint8 i = WG_OUTSIDE_ALLIANCE_NPC; i < WG_MAX_OUTSIDE_NPC; i++)
         if (Creature* creature = SpawnCreature(WGOutsideNPC[i].entryAlliance, WGOutsideNPC[i].x, WGOutsideNPC[i].y, WGOutsideNPC[i].z, WGOutsideNPC[i].o, TEAM_ALLIANCE))
             OutsideCreature[TEAM_ALLIANCE].insert(creature->GetGUID());
     // Hide units outside the keep that are defenders
     for (GuidUnorderedSet::const_iterator itr = OutsideCreature[GetDefenderTeam()].begin(); itr != OutsideCreature[GetDefenderTeam()].end(); ++itr)
         if (Creature* creature = GetCreature(*itr))
             HideNpc(creature);
     // Spawn turrets and hide them per default
     for (uint8 i = 0; i < WG_MAX_TURRET; i++)
     {
         Position towerCannonPos = WGTurret[i].GetPosition();
         if (Creature* creature = SpawnCreature(NPC_WINTERGRASP_TOWER_CANNON, towerCannonPos, TEAM_ALLIANCE))
         {
             CanonList.insert(creature->GetGUID());
             HideNpc(creature);
         }
     }
     // Spawn all gameobjects
     for (uint8 i = 0; i < WG_MAX_OBJ; i++)
     {
         GameObject* go = SpawnGameObject(WGGameObjectBuilding[i].entry, WGGameObjectBuilding[i].x, WGGameObjectBuilding[i].y, WGGameObjectBuilding[i].z, WGGameObjectBuilding[i].o);
         BfWGGameObjectBuilding* b = new BfWGGameObjectBuilding(this);
         b->Init(go, WGGameObjectBuilding[i].type, WGGameObjectBuilding[i].WorldState, WGGameObjectBuilding[i].damageText, WGGameObjectBuilding[i].destroyText);
         BuildingsInZone.insert(b);
     }
     // Spawning portal defender
     for (uint8 i = 0; i < WG_MAX_TELEPORTER; i++)
     {
         GameObject* go = SpawnGameObject(WGPortalDefenderData[i].entry, WGPortalDefenderData[i].x, WGPortalDefenderData[i].y, WGPortalDefenderData[i].z, WGPortalDefenderData[i].o);
         DefenderPortalList.insert(go);
         go->SetUInt32Value(GAMEOBJECT_FACTION, WintergraspFaction[GetDefenderTeam()]);
     }
     UpdateCounterVehicle(true);
     return true;
 }
References b, BATTLEFIELD_BATTLEID_WG, BATTLEFIELD_WG, BATTLEFIELD_WG_DATA_MAX, BATTLEFIELD_WG_GRAVEYARD_MAX, BATTLEFIELD_WG_MAPID, BATTLEFIELD_WG_NPC_STALKER, BATTLEFIELD_WG_WORKSHOP_KEEP_WEST, BATTLEFIELD_WG_WORLD_STATE_ACTIVE, BATTLEFIELD_WG_WORLD_STATE_DEFENDER, BATTLEFIELD_WG_ZONEID, bool, BuildingsInZone, CanonList, ObjectGuid::Clear(), ClockWorldState, CONFIG_WINTERGRASP_BATTLETIME, CONFIG_WINTERGRASP_ENABLE, CONFIG_WINTERGRASP_NOBATTLETIME, CONFIG_WINTERGRASP_PLR_MAX, CONFIG_WINTERGRASP_PLR_MIN, CONFIG_WINTERGRASP_PLR_MIN_LVL, CONFIG_WINTERGRASP_RESTART_AFTER_CRASH, DefenderPortalList, GAMEOBJECT_FACTION, Battlefield::GetAttackerTeam(), Battlefield::GetCreature(), Battlefield::GetDefenderTeam(), Position::GetPosition(), WGWorkshop::GiveControlTo(), Battlefield::HideNpc(), IN_MILLISECONDS, BfGraveyard::Initialize(), Battlefield::InitStalker(), KeepCreature, Battlefield::KickPosition, Battlefield::m_BattleId, Battlefield::m_BattleTime, Battlefield::m_Data32, Battlefield::m_DefenderTeam, Battlefield::m_GraveyardList, Battlefield::m_isActive, Battlefield::m_IsEnabled, Battlefield::m_Map, Battlefield::m_MapId, WorldLocation::m_mapId, Battlefield::m_MaxPlayer, Battlefield::m_MinLevel, Battlefield::m_MinPlayer, Battlefield::m_NoWarBattleTime, Battlefield::m_RestartAfterCrash, m_saveTimer, Battlefield::m_StartGrouping, Battlefield::m_StartGroupingTimer, m_tenacityStack, Battlefield::m_TimeForAcceptInvite, Battlefield::m_Timer, m_titansRelic, Battlefield::m_TypeId, Battlefield::m_ZoneId, MINUTE, NPC_WINTERGRASP_TOWER_CANNON, OutsideCreature, Battlefield::RegisterZone(), Position::Relocate(), Battlefield::SetGraveyardNumber(), BfGraveyardWG::SetTextId(), Object::SetUInt32Value(), sMapMgr, Battlefield::SpawnCreature(), Battlefield::SpawnGameObject(), sWorld, TEAM_ALLIANCE, TEAM_HORDE, TEAM_NEUTRAL, UpdateCounterVehicle(), urand(), WG_MAX_KEEP_NPC, WG_MAX_OBJ, WG_MAX_OUTSIDE_NPC, WG_MAX_TELEPORTER, WG_MAX_TURRET, WG_MAX_WORKSHOP, WG_OUTSIDE_ALLIANCE_NPC, WGGameObjectBuilding, WGGraveYard, WGKeepNPC, WGOutsideNPC, WGPortalDefenderData, WGTurret, WintergraspFaction, WintergraspStalkerPos, WorkshopsList, G3D::x, G3D::y, and G3D::z.
Update()
bool BattlefieldWG::Update (uint32 diff) override virtual
Called for update battlefield data.
Save battle timer in database every minutes
Update imunity aura from graveyard
Parameters
diff : time elapsed since the last call (in ms)
Reimplemented from Battlefield.
Definition at line 187 of file BattlefieldWG.cpp.
 {
     bool m_return = Battlefield::Update(diff);
     if (m_saveTimer <= diff)
     {
         sWorld->setWorldState(BATTLEFIELD_WG_WORLD_STATE_ACTIVE, m_isActive);
         sWorld->setWorldState(BATTLEFIELD_WG_WORLD_STATE_DEFENDER, m_DefenderTeam);
         sWorld->setWorldState(ClockWorldState[0], m_Timer);
         m_saveTimer = 60 * IN_MILLISECONDS;
     }
     else
         m_saveTimer -= diff;
     // Update Tenacity
     if (IsWarTime())
     {
         if (m_tenacityUpdateTimer <= diff)
         {
             m_tenacityUpdateTimer = 10000;
             if (!m_updateTenacityList.empty())
                 UpdateTenacity();
             m_updateTenacityList.clear();
         }
         else
             m_tenacityUpdateTimer -= diff;
     }
     return m_return;
 }
References BATTLEFIELD_WG_WORLD_STATE_ACTIVE, BATTLEFIELD_WG_WORLD_STATE_DEFENDER, ClockWorldState, diff(), IN_MILLISECONDS, Battlefield::IsWarTime(), Battlefield::m_DefenderTeam, Battlefield::m_isActive, m_saveTimer, m_tenacityUpdateTimer, Battlefield::m_Timer, m_updateTenacityList, sWorld, Battlefield::Update(), and UpdateTenacity().
UpdateCounterVehicle()
void BattlefieldWG::UpdateCounterVehicle (bool init)
Vehicle world states update.
Definition at line 289 of file BattlefieldWG.cpp.
 {
     if (init)
     {
         SetData(BATTLEFIELD_WG_DATA_VEHICLE_H, 0);
         SetData(BATTLEFIELD_WG_DATA_VEHICLE_A, 0);
     }
     SetData(BATTLEFIELD_WG_DATA_MAX_VEHICLE_H, 0);
     SetData(BATTLEFIELD_WG_DATA_MAX_VEHICLE_A, 0);
     for (Workshop::const_iterator itr = WorkshopsList.begin(); itr != WorkshopsList.end(); ++itr)
     {
         if (WGWorkshop* workshop = (*itr))
         {
             if (workshop->teamControl == TEAM_ALLIANCE)
                 UpdateData(BATTLEFIELD_WG_DATA_MAX_VEHICLE_A, 4);
             else if (workshop->teamControl == TEAM_HORDE)
                 UpdateData(BATTLEFIELD_WG_DATA_MAX_VEHICLE_H, 4);
         }
     }
     UpdateVehicleCountWG();
 }
References BATTLEFIELD_WG_DATA_MAX_VEHICLE_A, BATTLEFIELD_WG_DATA_MAX_VEHICLE_H, BATTLEFIELD_WG_DATA_VEHICLE_A, BATTLEFIELD_WG_DATA_VEHICLE_H, Battlefield::SetData(), TEAM_ALLIANCE, TEAM_HORDE, Battlefield::UpdateData(), UpdateVehicleCountWG(), and WorkshopsList.
Referenced by WGWorkshop::GiveControlTo(), OnBattleStart(), and SetupBattlefield().
UpdateDamagedTowerCount()
void BattlefieldWG::UpdateDamagedTowerCount (TeamId team)
Called when a tower is damaged.
Update tower count (for reward calcul)
Definition at line 1035 of file BattlefieldWG.cpp.
 {
     if (team == GetAttackerTeam())
     {
         UpdateData(BATTLEFIELD_WG_DATA_DAMAGED_TOWER_ATT, 1);
         UpdateData(BATTLEFIELD_WG_DATA_INTACT_TOWER_ATT, -1);
     }
 }
References BATTLEFIELD_WG_DATA_DAMAGED_TOWER_ATT, BATTLEFIELD_WG_DATA_INTACT_TOWER_ATT, Battlefield::GetAttackerTeam(), and Battlefield::UpdateData().
Referenced by BfWGGameObjectBuilding::Damaged().
UpdatedDestroyedTowerCount()
void BattlefieldWG::UpdatedDestroyedTowerCount (TeamId team, GameObject * go)
Called when tower is broken.
Update tower buff
check if three south tower is down for remove 10 minutes to wg
Definition at line 943 of file BattlefieldWG.cpp.
 {
     // Destroy an attack tower
     if (team == GetAttackerTeam())
     {
         // Update counter
         UpdateData(BATTLEFIELD_WG_DATA_DAMAGED_TOWER_ATT, -1);
         UpdateData(BATTLEFIELD_WG_DATA_BROKEN_TOWER_ATT, 1);
         // Remove buff stack on attackers
         for (GuidUnorderedSet::const_iterator itr = m_PlayersInWar[GetAttackerTeam()].begin(); itr != m_PlayersInWar[GetAttackerTeam()].end(); ++itr)
             if (Player* player = ObjectAccessor::FindPlayer(*itr))
                 player->RemoveAuraFromStack(SPELL_TOWER_CONTROL);
         // Add buff stack to defenders
         for (GuidUnorderedSet::const_iterator itr = m_PlayersInWar[GetDefenderTeam()].begin(); itr != m_PlayersInWar[GetDefenderTeam()].end(); ++itr)
             if (Player* player = ObjectAccessor::FindPlayer(*itr))
             {
                 // Quest - Wintergrasp - Southern Tower Kill
                 if (go && player->GetDistance2d(go) < 200.0f)
                     player->KilledMonsterCredit(NPC_QUEST_SOUTHERN_TOWER_KILL);
                 player->CastSpell(player, SPELL_TOWER_CONTROL, true);
                 player->UpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, SPELL_LEANING_TOWER_ACHIEVEMENT, 0, 0);
             }
         // If all three south towers are destroyed (ie. all attack towers), remove ten minutes from battle time
         if (GetData(BATTLEFIELD_WG_DATA_BROKEN_TOWER_ATT) == 3)
         {
             if (int32(m_Timer - 600000) < 0)
                 m_Timer = 0;
             else
                 m_Timer -= 600000;
             SendInitWorldStatesToAll();
         }
     }
     else
     {
         // Xinef: rest of structures, quest credit
         for (GuidUnorderedSet::const_iterator itr = m_PlayersInWar[GetAttackerTeam()].begin(); itr != m_PlayersInWar[GetAttackerTeam()].end(); ++itr)
             if (Player* player = ObjectAccessor::FindPlayer(*itr))
             {
                 // Quest - Wintergrasp - Vehicle Protected
                 if (go && player->GetDistance2d(go) < 100.0f)
                     player->KilledMonsterCredit(NPC_QUEST_VEHICLE_PROTECTED);
             }
     }
 }
References ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, BATTLEFIELD_WG_DATA_BROKEN_TOWER_ATT, BATTLEFIELD_WG_DATA_DAMAGED_TOWER_ATT, ObjectAccessor::FindPlayer(), Battlefield::GetAttackerTeam(), GetData(), Battlefield::GetDefenderTeam(), WorldObject::GetDistance2d(), Battlefield::m_PlayersInWar, Battlefield::m_Timer, NPC_QUEST_SOUTHERN_TOWER_KILL, NPC_QUEST_VEHICLE_PROTECTED, SendInitWorldStatesToAll(), SPELL_LEANING_TOWER_ACHIEVEMENT, SPELL_TOWER_CONTROL, and Battlefield::UpdateData().
Referenced by BfWGGameObjectBuilding::Destroyed().
UpdateTenacity()
void BattlefieldWG::UpdateTenacity ()
Definition at line 1066 of file BattlefieldWG.cpp.
 {
     TeamId team = TEAM_NEUTRAL;
     uint32 alliancePlayers = m_PlayersInWar[TEAM_ALLIANCE].size();
     uint32 hordePlayers = m_PlayersInWar[TEAM_HORDE].size();
     int32 newStack = 0;
     if (alliancePlayers && hordePlayers)
     {
         if (alliancePlayers < hordePlayers)
             newStack = int32((((float)hordePlayers / alliancePlayers) - 1.0f) * 4.0f);  // positive, should cast on alliance
         else if (alliancePlayers > hordePlayers)
             newStack = int32((1.0f - ((float)alliancePlayers / hordePlayers)) * 4.0f);  // negative, should cast on horde
     }
     // Return if no change in stack and apply tenacity to new player
     if (newStack == m_tenacityStack)
     {
         for (GuidUnorderedSet::const_iterator itr = m_updateTenacityList.begin(); itr != m_updateTenacityList.end(); ++itr)
             if (Player* newPlayer = ObjectAccessor::FindPlayer(*itr))
                 if ((newPlayer->GetTeamId() == TEAM_ALLIANCE && m_tenacityStack > 0) || (newPlayer->GetTeamId() == TEAM_HORDE && m_tenacityStack < 0))
                 {
                     newStack = std::min(abs(newStack), 20);
                     uint32 buff_honor = GetHonorBuff(newStack);
                     newPlayer->SetAuraStack(SPELL_TENACITY, newPlayer, newStack);
                     if (buff_honor)
                         newPlayer->CastSpell(newPlayer, buff_honor, true);
                 }
         return;
     }
     if (m_tenacityStack != 0)
     {
         if (m_tenacityStack > 0 && newStack <= 0)               // old buff was on alliance
             team = TEAM_ALLIANCE;
         else if (m_tenacityStack < 0 && newStack >= 0)          // old buff was on horde
             team = TEAM_HORDE;
     }
     m_tenacityStack = newStack;
     // Remove old buff
     if (team != TEAM_NEUTRAL)
     {
         for (GuidUnorderedSet::const_iterator itr = m_PlayersInWar[team].begin(); itr != m_PlayersInWar[team].end(); ++itr)
             if (Player* player = ObjectAccessor::FindPlayer(*itr))
                 player->RemoveAurasDueToSpell(SPELL_TENACITY);
         for (GuidUnorderedSet::const_iterator itr = m_vehicles[team].begin(); itr != m_vehicles[team].end(); ++itr)
             if (Creature* creature = GetCreature(*itr))
                 creature->RemoveAurasDueToSpell(SPELL_TENACITY_VEHICLE);
     }
     // Apply new buff
     if (newStack)
     {
         team = newStack > 0 ? TEAM_ALLIANCE : TEAM_HORDE;
         newStack = std::min(abs(newStack), 20);
         uint32 buff_honor = GetHonorBuff(newStack);
         for (GuidUnorderedSet::const_iterator itr = m_PlayersInWar[team].begin(); itr != m_PlayersInWar[team].end(); ++itr)
             if (Player* player = ObjectAccessor::FindPlayer(*itr))
             {
                 player->SetAuraStack(SPELL_TENACITY, player, newStack);
                 if (buff_honor)
                     player->CastSpell(player, buff_honor, true);
             }
         for (GuidUnorderedSet::const_iterator itr = m_vehicles[team].begin(); itr != m_vehicles[team].end(); ++itr)
             if (Creature* creature = GetCreature(*itr))
             {
                 creature->SetAuraStack(SPELL_TENACITY_VEHICLE, creature, newStack);
                 if (buff_honor)
                     creature->CastSpell(creature, buff_honor, true);
             }
     }
 }
References abs(), ObjectAccessor::FindPlayer(), Battlefield::GetCreature(), GetHonorBuff(), Battlefield::m_PlayersInWar, m_tenacityStack, m_updateTenacityList, m_vehicles, min, SPELL_TENACITY, SPELL_TENACITY_VEHICLE, TEAM_ALLIANCE, TEAM_HORDE, and TEAM_NEUTRAL.
Referenced by Update().
UpdateVehicleCountWG()
void BattlefieldWG::UpdateVehicleCountWG ()
Definition at line 314 of file BattlefieldWG.cpp.
 {
     for (uint8 i = 0; i < BG_TEAMS_COUNT; ++i)
         for (GuidUnorderedSet::iterator itr = m_players[i].begin(); itr != m_players[i].end(); ++itr)
             if (Player* player = ObjectAccessor::FindPlayer(*itr))
             {
                 player->SendUpdateWorldState(BATTLEFIELD_WG_WORLD_STATE_VEHICLE_H,     GetData(BATTLEFIELD_WG_DATA_VEHICLE_H));
                 player->SendUpdateWorldState(BATTLEFIELD_WG_WORLD_STATE_MAX_VEHICLE_H, GetData(BATTLEFIELD_WG_DATA_MAX_VEHICLE_H));
                 player->SendUpdateWorldState(BATTLEFIELD_WG_WORLD_STATE_VEHICLE_A,     GetData(BATTLEFIELD_WG_DATA_VEHICLE_A));
                 player->SendUpdateWorldState(BATTLEFIELD_WG_WORLD_STATE_MAX_VEHICLE_A, GetData(BATTLEFIELD_WG_DATA_MAX_VEHICLE_A));
             }
 }
References BATTLEFIELD_WG_DATA_MAX_VEHICLE_A, BATTLEFIELD_WG_DATA_MAX_VEHICLE_H, BATTLEFIELD_WG_DATA_VEHICLE_A, BATTLEFIELD_WG_DATA_VEHICLE_H, BATTLEFIELD_WG_WORLD_STATE_MAX_VEHICLE_A, BATTLEFIELD_WG_WORLD_STATE_MAX_VEHICLE_H, BATTLEFIELD_WG_WORLD_STATE_VEHICLE_A, BATTLEFIELD_WG_WORLD_STATE_VEHICLE_H, BG_TEAMS_COUNT, ObjectAccessor::FindPlayer(), GetData(), and Battlefield::m_players.
Referenced by OnCreatureCreate(), OnUnitDeath(), and UpdateCounterVehicle().
Member Data Documentation
BuildingsInZone
GameObjectBuilding BattlefieldWG::BuildingsInZone protected
Definition at line 463 of file BattlefieldWG.h.
Referenced by FillInitialWorldStates(), OnBattleEnd(), OnBattleStart(), ProcessEvent(), SendInitWorldStatesTo(), SetupBattlefield(), and ~BattlefieldWG().
CanonList
GuidUnorderedSet BattlefieldWG::CanonList protected
Definition at line 466 of file BattlefieldWG.h.
Referenced by OnBattleEnd(), OnBattleStart(), and SetupBattlefield().
DefenderPortalList
GameObjectSet BattlefieldWG::DefenderPortalList protected
Definition at line 461 of file BattlefieldWG.h.
Referenced by OnBattleEnd(), and SetupBattlefield().
KeepCreature
GuidUnorderedSet BattlefieldWG::KeepCreature[2] protected
Definition at line 467 of file BattlefieldWG.h.
Referenced by OnBattleEnd(), and SetupBattlefield().
m_isRelicInteractible
bool BattlefieldWG::m_isRelicInteractible protected
Definition at line 457 of file BattlefieldWG.h.
Referenced by CanInteractWithRelic(), and SetRelicInteractible().
m_KeepGameObject
GameObjectSet BattlefieldWG::m_KeepGameObject[2] protected
Definition at line 462 of file BattlefieldWG.h.
Referenced by OnBattleEnd().
m_saveTimer
uint32 BattlefieldWG::m_saveTimer protected
Definition at line 473 of file BattlefieldWG.h.
Referenced by SetupBattlefield(), and Update().
m_tenacityStack
int32 BattlefieldWG::m_tenacityStack protected
Definition at line 471 of file BattlefieldWG.h.
Referenced by OnBattleStart(), SetupBattlefield(), and UpdateTenacity().
m_tenacityUpdateTimer
uint32 BattlefieldWG::m_tenacityUpdateTimer protected
Definition at line 472 of file BattlefieldWG.h.
Referenced by OnBattleStart(), and Update().
m_titansRelic
ObjectGuid BattlefieldWG::m_titansRelic protected
Definition at line 475 of file BattlefieldWG.h.
Referenced by GetRelic(), OnBattleEnd(), OnBattleStart(), and SetupBattlefield().
m_updateTenacityList
GuidUnorderedSet BattlefieldWG::m_updateTenacityList protected
Definition at line 469 of file BattlefieldWG.h.
Referenced by AddUpdateTenacity(), RemoveUpdateTenacity(), Update(), and UpdateTenacity().
m_vehicles
GuidUnorderedSet BattlefieldWG::m_vehicles[2] protected
Definition at line 465 of file BattlefieldWG.h.
Referenced by FindAndRemoveVehicleFromList(), OnBattleEnd(), OnCreatureCreate(), and UpdateTenacity().
OutsideCreature
GuidUnorderedSet BattlefieldWG::OutsideCreature[2] protected
Definition at line 468 of file BattlefieldWG.h.
Referenced by OnBattleEnd(), and SetupBattlefield().
WorkshopsList
Workshop BattlefieldWG::WorkshopsList protected
Definition at line 459 of file BattlefieldWG.h.
Referenced by FillInitialWorldStates(), OnBattleEnd(), OnBattleStart(), OnGameObjectCreate(), SendInitWorldStatesTo(), SetupBattlefield(), UpdateCounterVehicle(), and ~BattlefieldWG().
The documentation for this class was generated from the following files:
src/server/game/Battlefield/Zones/BattlefieldWG.h
src/server/game/Battlefield/Zones/BattlefieldWG.cpp