Azerotcore-wotlk: Acore::CallOfHelpCreatureInRangeDo Class Reference
Acore::CallOfHelpCreatureInRangeDo Class Reference
#include <GridNotifiers.h>
Public Member Functions
CallOfHelpCreatureInRangeDo (Unit *funit, Unit *enemy, float range)
void operator() (Creature *u)
Private Attributes
Unit *const i_funit
Unit *const i_enemy
float i_range
Detailed Description
Definition at line 1026 of file GridNotifiers.h.
Constructor & Destructor Documentation
CallOfHelpCreatureInRangeDo()
Acore::CallOfHelpCreatureInRangeDo::CallOfHelpCreatureInRangeDo (Unit * funit, Unit * enemy, float range) inline
Definition at line 1029 of file GridNotifiers.h.
             : i_funit(funit), i_enemy(enemy), i_range(range)
         {}
Member Function Documentation
operator()()
void Acore::CallOfHelpCreatureInRangeDo::operator() (Creature * u) inline
Definition at line 1032 of file GridNotifiers.h.
         {
             if (u == i_funit)
                 return;
             if (!u->CanAssistTo(i_funit, i_enemy, false))
                 return;
             // too far
             if (!u->IsWithinDistInMap(i_funit, i_range))
                 return;
             // only if see assisted creature's enemy
             if (!u->IsWithinLOSInMap(i_enemy))
                 return;
             if (u->AI())
                 u->AI()->AttackStart(i_enemy);
         }
References Creature::AI(), UnitAI::AttackStart(), Creature::CanAssistTo(), i_enemy, i_funit, i_range, WorldObject::IsWithinDistInMap(), and WorldObject::IsWithinLOSInMap().
Member Data Documentation
i_enemy
Unit* const Acore::CallOfHelpCreatureInRangeDo::i_enemy private
Definition at line 1053 of file GridNotifiers.h.
Referenced by operator()().
i_funit
Unit* const Acore::CallOfHelpCreatureInRangeDo::i_funit private
Definition at line 1052 of file GridNotifiers.h.
Referenced by operator()().
i_range
float Acore::CallOfHelpCreatureInRangeDo::i_range private
Definition at line 1054 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/game/Grids/Notifiers/GridNotifiers.h