Azerotcore-wotlk: npc_icc_putricades_trap::npc_icc_putricades_trapAI Struct Reference
npc_icc_putricades_trap::npc_icc_putricades_trapAI Struct Reference
Public Member Functions
npc_icc_putricades_trapAI (Creature *creature)
void DoAction (int32 param) override
void Reset () override
void JustReachedHome () override
void JustSummoned (Creature *summon) override
void SummonedCreatureDies (Creature *summon, Unit *) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
SummonList summons
InstanceScript * instance
EventMap events
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 3620 of file icecrown_citadel.cpp.
Constructor & Destructor Documentation
npc_icc_putricades_trapAI()
npc_icc_putricades_trap::npc_icc_putricades_trapAI::npc_icc_putricades_trapAI (Creature * creature) inline
Definition at line 3622 of file icecrown_citadel.cpp.
                                                       : NullCreatureAI(creature), summons(me)
         {
             instance = creature->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), and instance.
Member Function Documentation
DoAction()
void npc_icc_putricades_trap::npc_icc_putricades_trapAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 3631 of file icecrown_citadel.cpp.
         {
             if (param == ACTION_START_GAUNTLET)
             {
                 me->setActive(true);
                 events.Reset();
                 events.ScheduleEvent(EVENT_CHECK_FIGHT, 1000);
                 instance->SetData(DATA_PUTRICIDE_TRAP_STATE, IN_PROGRESS);
                 me->CastSpell(me, SPELL_GIANT_INSECT_SWARM, true);
                 for (uint8 i = 0; i < 60; ++i)
                     events.ScheduleEvent(EVENT_GAUNTLET_PHASE1, i * 1000);
                 events.ScheduleEvent(EVENT_GAUNTLET_PHASE2, 60000);
             }
         }
References ACTION_START_GAUNTLET, Unit::CastSpell(), DATA_PUTRICIDE_TRAP_STATE, EVENT_CHECK_FIGHT, EVENT_GAUNTLET_PHASE1, EVENT_GAUNTLET_PHASE2, IN_PROGRESS, instance, CreatureAI::me, WorldObject::setActive(), ZoneScript::SetData(), and SPELL_GIANT_INSECT_SWARM.
JustReachedHome()
void npc_icc_putricades_trap::npc_icc_putricades_trapAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 3655 of file icecrown_citadel.cpp.
         {
             me->setActive(false);
         }
References CreatureAI::me, and WorldObject::setActive().
JustSummoned()
void npc_icc_putricades_trap::npc_icc_putricades_trapAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from CreatureAI.
Definition at line 3660 of file icecrown_citadel.cpp.
         {
             summons.Summon(summon);
             summon->CastSpell(summon, SPELL_LEAP_TO_A_RANDOM_LOCATION, true);
         }
References Unit::CastSpell(), SPELL_LEAP_TO_A_RANDOM_LOCATION, SummonList::Summon(), and summons.
Reset()
void npc_icc_putricades_trap::npc_icc_putricades_trapAI::Reset () inline override virtual
Reimplemented from UnitAI.
Definition at line 3647 of file icecrown_citadel.cpp.
         {
             events.Reset();
             summons.DespawnAll();
             if (instance->GetData(DATA_PUTRICIDE_TRAP_STATE) != DONE)
                 instance->SetData(DATA_PUTRICIDE_TRAP_STATE, NOT_STARTED);
         }
References DATA_PUTRICIDE_TRAP_STATE, SummonList::DespawnAll(), DONE, ZoneScript::GetData(), instance, NOT_STARTED, ZoneScript::SetData(), and summons.
SummonedCreatureDies()
void npc_icc_putricades_trap::npc_icc_putricades_trapAI::SummonedCreatureDies (Creature * summon, Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 3666 of file icecrown_citadel.cpp.
         {
             summons.Despawn(summon);
         }
References SummonList::Despawn(), and summons.
UpdateAI()
void npc_icc_putricades_trap::npc_icc_putricades_trapAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 3671 of file icecrown_citadel.cpp.
         {
             events.Update(diff);
             switch (events.ExecuteEvent())
             {
                 case EVENT_CHECK_FIGHT:
                     {
                         Map::PlayerList const& pList = me->GetMap()->GetPlayers();
                         for (Map::PlayerList::const_iterator itr = pList.begin(); itr != pList.end(); ++itr)
{
                             if (me->GetDistance(itr->GetSource()) > 100.0f || !itr->GetSource()->IsAlive() || itr->GetSource()->IsGameMaster())
                                 continue;
                             events.ScheduleEvent(EVENT_CHECK_FIGHT, 1000);
                             return;
                         }
                         CreatureAI::EnterEvadeMode();
                         return;
                     }
                 case EVENT_GAUNTLET_PHASE1:
                     {
                         std::list<Creature*> clist;
                         me->GetCreaturesWithEntryInRange(clist, 80.0f, NPC_INVISIBLE_STALKER);
                         // xinef: spell: 70484, some hack would be required, skip
                         for (std::list<Creature*>::const_iterator itr = clist.begin(); itr != clist.end(); ++itr)
                             me->SummonCreature(NPC_FLASH_EATING_INSECT, **itr, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 15000);
                         break;
                     }
                 case EVENT_GAUNTLET_PHASE2:
                     instance->SetData(DATA_PUTRICIDE_TRAP_STATE, DONE);
                     me->RemoveAllAuras();
                     me->RemoveAllDynObjects();
                     break;
             }
         }
References MapRefMgr::begin(), DATA_PUTRICIDE_TRAP_STATE, DONE, MapRefMgr::end(), CreatureAI::EnterEvadeMode(), EVENT_CHECK_FIGHT, EVENT_GAUNTLET_PHASE1, EVENT_GAUNTLET_PHASE2, WorldObject::GetCreaturesWithEntryInRange(), WorldObject::GetDistance(), WorldObject::GetMap(), Map::GetPlayers(), instance, CreatureAI::me, NPC_FLASH_EATING_INSECT, NPC_INVISIBLE_STALKER, Unit::RemoveAllAuras(), Unit::RemoveAllDynObjects(), ZoneScript::SetData(), WorldObject::SummonCreature(), and TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT.
Member Data Documentation
events
EventMap npc_icc_putricades_trap::npc_icc_putricades_trapAI::events
Definition at line 3629 of file icecrown_citadel.cpp.
instance
InstanceScript* npc_icc_putricades_trap::npc_icc_putricades_trapAI::instance
Definition at line 3628 of file icecrown_citadel.cpp.
Referenced by DoAction(), npc_icc_putricades_trapAI(), Reset(), and UpdateAI().
summons
SummonList npc_icc_putricades_trap::npc_icc_putricades_trapAI::summons
Definition at line 3627 of file icecrown_citadel.cpp.
Referenced by JustSummoned(), Reset(), and SummonedCreatureDies().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp