Azerotcore-wotlk: src/server/game/Warden/WardenWin.cpp File Reference
WardenWin.cpp File Reference
#include "ByteBuffer.h"
#include "Common.h"
#include "CryptoRandom.h"
#include "HMAC.h"
#include "Opcodes.h"
#include "Player.h"
#include "SessionKeyGenerator.h"
#include "Util.h"
#include "WardenCheckMgr.h"
#include "WardenModuleWin.h"
#include "WardenWin.h"
#include "World.h"
#include "WorldPacket.h"
#include "WorldSession.h"
#include <openssl/md5.h>
Functions
static constexpr uint8 GetCheckPacketBaseSize (uint8 type)
static uint16 GetCheckPacketSize (WardenCheck const *check)
static WorldIntConfigs GetMaxWardenChecksForType (uint8 type)
Variables
static constexpr char _luaEvalPrefix [] = "local S,T,R=SendAddonMessage,function()"
static constexpr char _luaEvalMidfix [] = " end R=S and T()if R then S('_TW',"
static constexpr char _luaEvalPostfix [] = ",'GUILD')end"
Function Documentation
GetCheckPacketBaseSize()
static constexpr uint8 GetCheckPacketBaseSize (uint8 type) static constexpr
Definition at line 41 of file WardenWin.cpp.
 {
     switch (type)
     {
     case DRIVER_CHECK:
     case MPQ_CHECK: return 1;
     case LUA_EVAL_CHECK: return 1 + sizeof(_luaEvalPrefix) - 1 + sizeof(_luaEvalMidfix) - 1 + 4 + sizeof(_luaEvalPostfix) - 1;
     case PAGE_CHECK_A: return (4 + 1);
     case PAGE_CHECK_B: return (4 + 1);
     case MODULE_CHECK: return (4 + Acore::Crypto::Constants::SHA1_DIGEST_LENGTH_BYTES);
     case MEM_CHECK: return (1 + 4 + 1);
     default: return 0;
     }
 }
References _luaEvalMidfix, _luaEvalPostfix, _luaEvalPrefix, DRIVER_CHECK, LUA_EVAL_CHECK, MEM_CHECK, MODULE_CHECK, MPQ_CHECK, PAGE_CHECK_A, PAGE_CHECK_B, and Acore::Crypto::Constants::SHA1_DIGEST_LENGTH_BYTES.
Referenced by GetCheckPacketSize().
GetCheckPacketSize()
static uint16 GetCheckPacketSize (WardenCheck const * check) static
Definition at line 56 of file WardenWin.cpp.
 {
     if (!check)
     {
         return 0;
     }
     uint16 size = 1 + GetCheckPacketBaseSize(check->Type); // 1 byte check type
     if (!check->Str.empty())
     {
         size += (static_cast<uint16>(check->Str.length()) + 1); // 1 byte string length
     }
     BigNumber tempNumber = check->Data;
     if (!tempNumber.GetNumBytes())
     {
         size += tempNumber.GetNumBytes();
     }
     return size;
 }
References WardenCheck::Data, GetCheckPacketBaseSize(), BigNumber::GetNumBytes(), WardenCheck::Str, and WardenCheck::Type.
Referenced by WardenWin::RequestChecks().
GetMaxWardenChecksForType()
static WorldIntConfigs GetMaxWardenChecksForType (uint8 type) static
Definition at line 78 of file WardenWin.cpp.
 {
     // Should never be higher type than defined
     ASSERT(type < MAX_WARDEN_CHECK_TYPES);
     switch (type)
     {
     case WARDEN_CHECK_MEM_TYPE:
         return CONFIG_WARDEN_NUM_MEM_CHECKS;
     case WARDEN_CHECK_LUA_TYPE:
         return CONFIG_WARDEN_NUM_LUA_CHECKS;
     default:
         break;
     }
     return CONFIG_WARDEN_NUM_OTHER_CHECKS;
 }
References ASSERT, CONFIG_WARDEN_NUM_LUA_CHECKS, CONFIG_WARDEN_NUM_MEM_CHECKS, CONFIG_WARDEN_NUM_OTHER_CHECKS, MAX_WARDEN_CHECK_TYPES, WARDEN_CHECK_LUA_TYPE, and WARDEN_CHECK_MEM_TYPE.
Referenced by WardenWin::RequestChecks().
Variable Documentation
_luaEvalMidfix
constexpr char _luaEvalMidfix[] = " end R=S and T()if R then S('_TW'," static constexpr
Definition at line 36 of file WardenWin.cpp.
Referenced by GetCheckPacketBaseSize(), and WardenWin::RequestChecks().
_luaEvalPostfix
constexpr char _luaEvalPostfix[] = ",'GUILD')end" static constexpr
Definition at line 37 of file WardenWin.cpp.
Referenced by GetCheckPacketBaseSize(), and WardenWin::RequestChecks().
_luaEvalPrefix
constexpr char _luaEvalPrefix[] = "local S,T,R=SendAddonMessage,function()" static constexpr
Definition at line 35 of file WardenWin.cpp.
Referenced by GetCheckPacketBaseSize(), and WardenWin::RequestChecks().