Azerotcore-wotlk: src/server/game/AI/ScriptedAI/ScriptedGossip.h File Reference
ScriptedGossip.h File Reference
#include "GossipDef.h"
#include "QuestDef.h"
Macros
#define GOSSIP_TEXT_BROWSE_GOODS "I'd like to browse your goods."
#define GOSSIP_TEXT_TRAIN "Train me!"
Enumerations
enum eTradeskill {
TRADESKILL_ALCHEMY = 1 , TRADESKILL_BLACKSMITHING = 2 , TRADESKILL_COOKING = 3 , TRADESKILL_ENCHANTING = 4 ,
TRADESKILL_ENGINEERING = 5 , TRADESKILL_FIRSTAID = 6 , TRADESKILL_HERBALISM = 7 , TRADESKILL_LEATHERWORKING = 8 ,
TRADESKILL_POISONS = 9 , TRADESKILL_TAILORING = 10 , TRADESKILL_MINING = 11 , TRADESKILL_FISHING = 12 ,
TRADESKILL_SKINNING = 13 , TRADESKILL_JEWLCRAFTING = 14 , TRADESKILL_INSCRIPTION = 15 , TRADESKILL_LEVEL_NONE = 0 ,
TRADESKILL_LEVEL_APPRENTICE = 1 , TRADESKILL_LEVEL_JOURNEYMAN = 2 , TRADESKILL_LEVEL_EXPERT = 3 , TRADESKILL_LEVEL_ARTISAN = 4 ,
TRADESKILL_LEVEL_MASTER = 5 , TRADESKILL_LEVEL_GRAND_MASTER = 6 , GOSSIP_ACTION_TRADE = 1 , GOSSIP_ACTION_TRAIN = 2 ,
GOSSIP_ACTION_TAXI = 3 , GOSSIP_ACTION_GUILD = 4 , GOSSIP_ACTION_BATTLE = 5 , GOSSIP_ACTION_BANK = 6 ,
GOSSIP_ACTION_INN = 7 , GOSSIP_ACTION_HEAL = 8 , GOSSIP_ACTION_TABARD = 9 , GOSSIP_ACTION_AUCTION = 10 ,
GOSSIP_ACTION_INN_INFO = 11 , GOSSIP_ACTION_UNLEARN = 12 , GOSSIP_ACTION_INFO_DEF = 1000 , GOSSIP_SENDER_MAIN = 1 ,
GOSSIP_SENDER_INN_INFO = 2 , GOSSIP_SENDER_INFO = 3 , GOSSIP_SENDER_SEC_PROFTRAIN = 4 , GOSSIP_SENDER_SEC_CLASSTRAIN = 5 ,
GOSSIP_SENDER_SEC_BATTLEINFO = 6 , GOSSIP_SENDER_SEC_BANK = 7 , GOSSIP_SENDER_SEC_INN = 8 , GOSSIP_SENDER_SEC_MAILBOX = 9 ,
GOSSIP_SENDER_SEC_STABLEMASTER = 10
}
Functions
void ClearGossipMenuFor (Player *player)
void AddGossipItemFor (Player *player, uint32 icon, std::string const &text, uint32 sender, uint32 action)
void AddGossipItemFor (Player *player, uint32 icon, std::string const &text, uint32 sender, uint32 action, std::string const &popupText, uint32 popupMoney, bool coded)
void AddGossipItemFor (Player *player, uint32 gossipMenuID, uint32 gossipMenuItemID, uint32 sender, uint32 action)
void SendGossipMenuFor (Player *player, uint32 npcTextID, ObjectGuid const guid)
void SendGossipMenuFor (Player *player, uint32 npcTextID, Creature const *creature)
void CloseGossipMenuFor (Player *player)
Macro Definition Documentation
GOSSIP_TEXT_BROWSE_GOODS
#define GOSSIP_TEXT_BROWSE_GOODS "I'd like to browse your goods."
Definition at line 25 of file ScriptedGossip.h.
GOSSIP_TEXT_TRAIN
#define GOSSIP_TEXT_TRAIN "Train me!"
Definition at line 26 of file ScriptedGossip.h.
Enumeration Type Documentation
eTradeskill
enum eTradeskill
Enumerator
TRADESKILL_ALCHEMY
TRADESKILL_BLACKSMITHING
TRADESKILL_COOKING
TRADESKILL_ENCHANTING
TRADESKILL_ENGINEERING
TRADESKILL_FIRSTAID
TRADESKILL_HERBALISM
TRADESKILL_LEATHERWORKING
TRADESKILL_POISONS
TRADESKILL_TAILORING
TRADESKILL_MINING
TRADESKILL_FISHING
TRADESKILL_SKINNING
TRADESKILL_JEWLCRAFTING
TRADESKILL_INSCRIPTION
TRADESKILL_LEVEL_NONE
TRADESKILL_LEVEL_APPRENTICE
TRADESKILL_LEVEL_JOURNEYMAN
TRADESKILL_LEVEL_EXPERT
TRADESKILL_LEVEL_ARTISAN
TRADESKILL_LEVEL_MASTER
TRADESKILL_LEVEL_GRAND_MASTER
GOSSIP_ACTION_TRADE
GOSSIP_ACTION_TRAIN
GOSSIP_ACTION_TAXI
GOSSIP_ACTION_GUILD
GOSSIP_ACTION_BATTLE
GOSSIP_ACTION_BANK
GOSSIP_ACTION_INN
GOSSIP_ACTION_HEAL
GOSSIP_ACTION_TABARD
GOSSIP_ACTION_AUCTION
GOSSIP_ACTION_INN_INFO
GOSSIP_ACTION_UNLEARN
GOSSIP_ACTION_INFO_DEF
GOSSIP_SENDER_MAIN
GOSSIP_SENDER_INN_INFO
GOSSIP_SENDER_INFO
GOSSIP_SENDER_SEC_PROFTRAIN
GOSSIP_SENDER_SEC_CLASSTRAIN
GOSSIP_SENDER_SEC_BATTLEINFO
GOSSIP_SENDER_SEC_BANK
GOSSIP_SENDER_SEC_INN
GOSSIP_SENDER_SEC_MAILBOX
GOSSIP_SENDER_SEC_STABLEMASTER
Definition at line 28 of file ScriptedGossip.h.
 {
     // Skill defines
     TRADESKILL_ALCHEMY                  = 1,
     TRADESKILL_BLACKSMITHING            = 2,
     TRADESKILL_COOKING                  = 3,
     TRADESKILL_ENCHANTING               = 4,
     TRADESKILL_ENGINEERING              = 5,
     TRADESKILL_FIRSTAID                 = 6,
     TRADESKILL_HERBALISM                = 7,
     TRADESKILL_LEATHERWORKING           = 8,
     TRADESKILL_POISONS                  = 9,
     TRADESKILL_TAILORING                = 10,
     TRADESKILL_MINING                   = 11,
     TRADESKILL_FISHING                  = 12,
     TRADESKILL_SKINNING                 = 13,
     TRADESKILL_JEWLCRAFTING             = 14,
     TRADESKILL_INSCRIPTION              = 15,
     TRADESKILL_LEVEL_NONE               = 0,
     TRADESKILL_LEVEL_APPRENTICE         = 1,
     TRADESKILL_LEVEL_JOURNEYMAN         = 2,
     TRADESKILL_LEVEL_EXPERT             = 3,
     TRADESKILL_LEVEL_ARTISAN            = 4,
     TRADESKILL_LEVEL_MASTER             = 5,
     TRADESKILL_LEVEL_GRAND_MASTER       = 6,
     // Gossip defines
     GOSSIP_ACTION_TRADE                 = 1,
     GOSSIP_ACTION_TRAIN                 = 2,
     GOSSIP_ACTION_TAXI                  = 3,
     GOSSIP_ACTION_GUILD                 = 4,
     GOSSIP_ACTION_BATTLE                = 5,
     GOSSIP_ACTION_BANK                  = 6,
     GOSSIP_ACTION_INN                   = 7,
     GOSSIP_ACTION_HEAL                  = 8,
     GOSSIP_ACTION_TABARD                = 9,
     GOSSIP_ACTION_AUCTION               = 10,
     GOSSIP_ACTION_INN_INFO              = 11,
     GOSSIP_ACTION_UNLEARN               = 12,
     GOSSIP_ACTION_INFO_DEF              = 1000,
     GOSSIP_SENDER_MAIN                  = 1,
     GOSSIP_SENDER_INN_INFO              = 2,
     GOSSIP_SENDER_INFO                  = 3,
     GOSSIP_SENDER_SEC_PROFTRAIN         = 4,
     GOSSIP_SENDER_SEC_CLASSTRAIN        = 5,
     GOSSIP_SENDER_SEC_BATTLEINFO        = 6,
     GOSSIP_SENDER_SEC_BANK              = 7,
     GOSSIP_SENDER_SEC_INN               = 8,
     GOSSIP_SENDER_SEC_MAILBOX           = 9,
     GOSSIP_SENDER_SEC_STABLEMASTER      = 10
 };
Function Documentation
AddGossipItemFor() [1/3]
void AddGossipItemFor (Player * player, uint32 gossipMenuID, uint32 gossipMenuItemID, uint32 sender, uint32 action)
Definition at line 40 of file ScriptedGossip.cpp.
 {
     player->PlayerTalkClass->GetGossipMenu().AddMenuItem(gossipMenuID, gossipMenuItemID, sender, action);
 }
References GossipMenu::AddMenuItem(), PlayerMenu::GetGossipMenu(), and Player::PlayerTalkClass.
AddGossipItemFor() [2/3]
void AddGossipItemFor (Player * player, uint32 icon, std::string const & text, uint32 sender, uint32 action)
Definition at line 28 of file ScriptedGossip.cpp.
 {
     player->PlayerTalkClass->GetGossipMenu().AddMenuItem(-1, icon, text, sender, action, "", 0);
 }
References GossipMenu::AddMenuItem(), PlayerMenu::GetGossipMenu(), and Player::PlayerTalkClass.
Referenced by npc_pet_gen_argent_pony_bridle::OnGossipHello(), npc_lokhtos_darkbargainer::OnGossipHello(), boss_gloomrel::OnGossipHello(), boss_doomrel::OnGossipHello(), boss_majordomo::OnGossipHello(), npc_grandmother::OnGossipHello(), npc_barnes::OnGossipHello(), npc_death_knight_initiate::OnGossipHello(), npc_highlord_darion_mograine::OnGossipHello(), npc_fairbanks::OnGossipHello(), npc_augustus_the_touched::OnGossipHello(), npc_parqual_fintallas::OnGossipHello(), npc_varian_wrynn::OnGossipHello(), npc_thrall_bfu::OnGossipHello(), npc_zulaman_hostage::OnGossipHello(), npc_brewfest_keg_reciver::OnGossipHello(), npc_jaina_proudmoore::OnGossipHello(), npc_thrall::OnGossipHello(), npc_tyrande_whisperwind::OnGossipHello(), npc_arthas::OnGossipHello(), npc_rizzle_sprysprocket::OnGossipHello(), npc_lady_jaina_proudmoore::OnGossipHello(), npc_nat_pagle::OnGossipHello(), npcs_riverbreeze_and_silversky::OnGossipHello(), npc_bunthen_plainswind::OnGossipHello(), npc_great_bear_spirit::OnGossipHello(), npc_silva_filnaveth::OnGossipHello(), npc_thrall_warchief::OnGossipHello(), npc_braug_dimspirit::OnGossipHello(), npc_steward_of_time::OnGossipHello(), npc_stone_watcher_of_norgannon::OnGossipHello(), npc_beaten_corpse::OnGossipHello(), npc_plucky::OnGossipHello(), npc_rivern_frostwind::OnGossipHello(), npc_announcer_toc5::OnGossipHello(), npc_announcer_toc10::OnGossipHello(), npc_fos_leader::OnGossipHello(), npc_hor_leader::OnGossipHello(), npc_high_overlord_saurfang_icc::OnGossipHello(), npc_muradin_bronzebeard_icc::OnGossipHello(), npc_oculus_drakegiver::OnGossipHello(), brann_bronzebeard::OnGossipHello(), npc_ulduar_expedition_commander::OnGossipHello(), npc_ulduar_keeper::OnGossipHello(), npc_vh_sinclari::OnGossipHello(), npc_iruk::OnGossipHello(), npc_shandy_dalaran::OnGossipHello(), npc_razael_and_lyana::OnGossipHello(), npc_mcmanus::OnGossipHello(), npc_vekjik::OnGossipHello(), npc_avatar_of_freya::OnGossipHello(), npc_adventurous_dwarf::OnGossipHello(), npc_roxi_ramrocket::OnGossipHello(), npc_wg_demolisher_engineer::OnGossipHello(), npc_wg_spirit_guide::OnGossipHello(), npc_wg_queue::OnGossipHello(), npc_finklestein::OnGossipHello(), adyen_the_lightbringer::OnGossipHello(), npc_captain_saeed::OnGossipHello(), npc_professor_dabiri::OnGossipHello(), npc_drake_dealer_hurlunk::OnGossipHello(), npcs_flanis_swiftwing_and_kagrosh::OnGossipHello(), npc_raliq_the_drunk::OnGossipHello(), npc_shattrathflaskvendors::OnGossipHello(), npc_zephyr::OnGossipHello(), npc_ishanah::OnGossipHello(), npc_floon::OnGossipHello(), npc_slim::OnGossipHello(), npcs_ashyen_and_keleth::OnGossipHello(), npc_cooshcoosh::OnGossipHello(), npc_elder_kuruti::OnGossipHello(), npc_mortog_steamhead::OnGossipHello(), npc_timothy_daniels::OnGossipHello(), npc_innkeeper::OnGossipHello(), npc_prof_alchemy::OnGossipHello(), npc_prof_blacksmith::OnGossipHello(), npc_engineering_tele_trinket::OnGossipHello(), npc_prof_leather::OnGossipHello(), npc_prof_tailor::OnGossipHello(), npc_artorius::OnGossipHello(), npc_simone::OnGossipHello(), npc_nelson::OnGossipHello(), npc_franklin::OnGossipHello(), npc_taxi::OnGossipHello(), npc_sayge::OnGossipHello(), npc_wormhole::OnGossipHello(), npc_locksmith::OnGossipHello(), npc_experience::OnGossipHello(), go_evil_book_for_dummies::OnGossipHello(), icecrown_citadel_teleport::OnGossipHello(), go_ahune_ice_stone::OnGossipHello(), go_skull_pile::OnGossipHello(), go_fel_crystalforge::OnGossipHello(), go_bashir_crystalforge::OnGossipHello(), go_amberpine_outhouse::OnGossipHello(), boss_gloomrel::OnGossipSelect(), boss_doomrel::OnGossipSelect(), boss_majordomo::OnGossipSelect(), npc_barnes::OnGossipSelect(), npc_arthas::OnGossipSelect(), npc_great_bear_spirit::OnGossipSelect(), npc_thrall_warchief::OnGossipSelect(), npc_stone_watcher_of_norgannon::OnGossipSelect(), npc_vekjik::OnGossipSelect(), npc_avatar_of_freya::OnGossipSelect(), npc_floon::OnGossipSelect(), npc_elder_kuruti::OnGossipSelect(), npc_fairbanks::OnGossipSelect(), npc_oculus_drakegiver::OnGossipSelect(), go_fel_crystalforge::OnGossipSelect(), go_bashir_crystalforge::OnGossipSelect(), npc_sayge::SendAction(), npc_prof_alchemy::SendConfirmLearn(), npc_prof_blacksmith::SendConfirmLearn(), npc_prof_tailor::SendConfirmLearn(), go_evil_book_for_dummies::SendConfirmLearn(), npc_prof_alchemy::SendConfirmUnlearn(), npc_prof_blacksmith::SendConfirmUnlearn(), npc_prof_tailor::SendConfirmUnlearn(), go_evil_book_for_dummies::SendConfirmUnlearn(), npc_sergeant_bly::npc_sergeant_blyAI::sGossipHello(), and npc_weegli_blastfuse::npc_weegli_blastfuseAI::sGossipHello().
AddGossipItemFor() [3/3]
void AddGossipItemFor (Player * player, uint32 icon, std::string const & text, uint32 sender, uint32 action, std::string const & popupText, uint32 popupMoney, bool coded)
Definition at line 34 of file ScriptedGossip.cpp.
 {
     player->PlayerTalkClass->GetGossipMenu().AddMenuItem(-1, icon, text, sender, action, popupText, popupMoney, coded);
 }
References GossipMenu::AddMenuItem(), PlayerMenu::GetGossipMenu(), and Player::PlayerTalkClass.
ClearGossipMenuFor()
void ClearGossipMenuFor (Player * player)
Definition at line 22 of file ScriptedGossip.cpp.
 {
     player->PlayerTalkClass->ClearMenus();
 }
References PlayerMenu::ClearMenus(), and Player::PlayerTalkClass.
Referenced by ScriptMgr::GetDialogStatus(), Creature::isCanInteractWithBattleMaster(), ScriptMgr::OnGossipHello(), npc_steward_of_time::OnGossipSelect(), npc_plucky::OnGossipSelect(), npc_iruk::OnGossipSelect(), npcs_flanis_swiftwing_and_kagrosh::OnGossipSelect(), npc_zephyr::OnGossipSelect(), npc_taxi::OnGossipSelect(), npc_locksmith::OnGossipSelect(), npc_experience::OnGossipSelect(), npc_prof_alchemy::OnGossipSelect(), npc_prof_blacksmith::OnGossipSelect(), npc_engineering_tele_trinket::OnGossipSelect(), npc_prof_leather::OnGossipSelect(), npc_prof_tailor::OnGossipSelect(), npc_sayge::OnGossipSelect(), npc_lokhtos_darkbargainer::OnGossipSelect(), boss_gloomrel::OnGossipSelect(), boss_doomrel::OnGossipSelect(), boss_majordomo::OnGossipSelect(), npc_grandmother::OnGossipSelect(), npc_barnes::OnGossipSelect(), npc_death_knight_initiate::OnGossipSelect(), npc_highlord_darion_mograine::OnGossipSelect(), npc_augustus_the_touched::OnGossipSelect(), npc_parqual_fintallas::OnGossipSelect(), npc_varian_wrynn::OnGossipSelect(), npc_thrall_bfu::OnGossipSelect(), npc_zulaman_hostage::OnGossipSelect(), npc_jaina_proudmoore::OnGossipSelect(), npc_thrall::OnGossipSelect(), npc_tyrande_whisperwind::OnGossipSelect(), npc_arthas::OnGossipSelect(), npc_lady_jaina_proudmoore::OnGossipSelect(), npc_nat_pagle::OnGossipSelect(), npcs_riverbreeze_and_silversky::OnGossipSelect(), npc_bunthen_plainswind::OnGossipSelect(), npc_great_bear_spirit::OnGossipSelect(), npc_silva_filnaveth::OnGossipSelect(), npc_thrall_warchief::OnGossipSelect(), npc_braug_dimspirit::OnGossipSelect(), npc_stone_watcher_of_norgannon::OnGossipSelect(), npc_beaten_corpse::OnGossipSelect(), npc_rivern_frostwind::OnGossipSelect(), npc_high_overlord_saurfang_icc::OnGossipSelect(), npc_muradin_bronzebeard_icc::OnGossipSelect(), npc_razael_and_lyana::OnGossipSelect(), npc_vekjik::OnGossipSelect(), npc_avatar_of_freya::OnGossipSelect(), npc_adventurous_dwarf::OnGossipSelect(), npc_roxi_ramrocket::OnGossipSelect(), adyen_the_lightbringer::OnGossipSelect(), npc_professor_dabiri::OnGossipSelect(), npc_drake_dealer_hurlunk::OnGossipSelect(), npc_raliq_the_drunk::OnGossipSelect(), npc_shattrathflaskvendors::OnGossipSelect(), npc_ishanah::OnGossipSelect(), npc_floon::OnGossipSelect(), npc_slim::OnGossipSelect(), npcs_ashyen_and_keleth::OnGossipSelect(), npc_cooshcoosh::OnGossipSelect(), npc_elder_kuruti::OnGossipSelect(), npc_mortog_steamhead::OnGossipSelect(), npc_timothy_daniels::OnGossipSelect(), npc_innkeeper::OnGossipSelect(), npc_wormhole::OnGossipSelect(), npc_fairbanks::OnGossipSelect(), npc_fos_leader::OnGossipSelect(), npc_hor_leader::OnGossipSelect(), npc_oculus_drakegiver::OnGossipSelect(), npc_vh_sinclari::OnGossipSelect(), npc_captain_saeed::OnGossipSelect(), npc_thrall_old_hillsbrad::OnGossipSelect(), npc_hor_leader_second::OnGossipSelect(), npc_natrualist_bite::OnGossipSelect(), icecrown_citadel_teleport::OnGossipSelect(), go_evil_book_for_dummies::OnGossipSelect(), go_skull_pile::OnGossipSelect(), go_fel_crystalforge::OnGossipSelect(), go_bashir_crystalforge::OnGossipSelect(), go_amberpine_outhouse::OnGossipSelect(), ScriptMgr::OnQuestAccept(), ScriptMgr::OnQuestComplete(), ScriptMgr::OnQuestReward(), ScriptMgr::OnQuestSelect(), npc_sergeant_bly::npc_sergeant_blyAI::sGossipSelect(), and npc_weegli_blastfuse::npc_weegli_blastfuseAI::sGossipSelect().
CloseGossipMenuFor()
void CloseGossipMenuFor (Player * player)
Definition at line 56 of file ScriptedGossip.cpp.
 {
     player->PlayerTalkClass->SendCloseGossip();
 }
References Player::PlayerTalkClass, and PlayerMenu::SendCloseGossip().
Referenced by npc_essence_of_twin::OnGossipHello(), npc_plucky::OnGossipSelect(), npc_iruk::OnGossipSelect(), npc_wg_spirit_guide::OnGossipSelect(), npc_taxi::OnGossipSelect(), npc_locksmith::OnGossipSelect(), npc_brewfest_keg_reciver::OnGossipSelect(), npc_wg_queue::OnGossipSelect(), npc_engineering_tele_trinket::OnGossipSelect(), npc_pet_gen_argent_pony_bridle::OnGossipSelect(), npc_lokhtos_darkbargainer::OnGossipSelect(), boss_gloomrel::OnGossipSelect(), boss_doomrel::OnGossipSelect(), boss_majordomo::OnGossipSelect(), npc_barnes::OnGossipSelect(), npc_death_knight_initiate::OnGossipSelect(), npc_highlord_darion_mograine::OnGossipSelect(), npc_parqual_fintallas::OnGossipSelect(), npc_varian_wrynn::OnGossipSelect(), npc_thrall_bfu::OnGossipSelect(), npc_zulaman_hostage::OnGossipSelect(), npc_arthas::OnGossipSelect(), npcs_riverbreeze_and_silversky::OnGossipSelect(), npc_bunthen_plainswind::OnGossipSelect(), npc_silva_filnaveth::OnGossipSelect(), npc_thrall_warchief::OnGossipSelect(), npc_braug_dimspirit::OnGossipSelect(), npc_stone_watcher_of_norgannon::OnGossipSelect(), npc_high_overlord_saurfang_icc::OnGossipSelect(), npc_muradin_bronzebeard_icc::OnGossipSelect(), brann_bronzebeard::OnGossipSelect(), npc_shandy_dalaran::OnGossipSelect(), npc_vekjik::OnGossipSelect(), npc_avatar_of_freya::OnGossipSelect(), npc_wg_demolisher_engineer::OnGossipSelect(), adyen_the_lightbringer::OnGossipSelect(), npc_professor_dabiri::OnGossipSelect(), npc_raliq_the_drunk::OnGossipSelect(), npc_floon::OnGossipSelect(), npcs_ashyen_and_keleth::OnGossipSelect(), npc_cooshcoosh::OnGossipSelect(), npc_innkeeper::OnGossipSelect(), npc_wormhole::OnGossipSelect(), npc_announcer_toc5::OnGossipSelect(), npc_announcer_toc10::OnGossipSelect(), npc_fos_leader::OnGossipSelect(), npc_hor_leader::OnGossipSelect(), npc_oculus_drakegiver::OnGossipSelect(), npc_vh_sinclari::OnGossipSelect(), npc_mcmanus::OnGossipSelect(), npc_finklestein::OnGossipSelect(), npc_captain_saeed::OnGossipSelect(), npc_thrall_old_hillsbrad::OnGossipSelect(), npc_icc_buff_switcher::OnGossipSelect(), npc_tirions_gambit_tirion::OnGossipSelect(), npc_natrualist_bite::OnGossipSelect(), npc_artorius::OnGossipSelect(), npc_simone::OnGossipSelect(), npc_nelson::OnGossipSelect(), npc_franklin::OnGossipSelect(), icecrown_citadel_teleport::OnGossipSelect(), go_midsummer_bonfire::OnGossipSelect(), go_ahune_ice_stone::OnGossipSelect(), go_amberpine_outhouse::OnGossipSelect(), go_apexis_relic::OnGossipSelect(), ProcessCastaction(), ProcessUnlearnAction(), npc_coren_direbrew::npc_coren_direbrewAI::sGossipSelect(), boss_victor_nefarius::boss_victor_nefariusAI::sGossipSelect(), boss_vaelastrasz::boss_vaelAI::sGossipSelect(), npc_harrison_jones::npc_harrison_jonesAI::sGossipSelect(), npc_thassarian2::npc_thassarian2AI::sGossipSelect(), npc_akama_shade::npc_akamaAI::sGossipSelect(), npc_sergeant_bly::npc_sergeant_blyAI::sGossipSelect(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::sGossipSelect(), npc_hidden_cultist::npc_hidden_cultistAI::sGossipSelect(), npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI::sGossipSelect(), npc_crusade_recruit::npc_crusade_recruitAI::sGossipSelect(), and npc_akama_illidan::npc_akama_illidanAI::sGossipSelect().
SendGossipMenuFor() [1/2]
void SendGossipMenuFor (Player * player, uint32 npcTextID, Creature const * creature)
Definition at line 50 of file ScriptedGossip.cpp.
 {
     if (creature)
         SendGossipMenuFor(player, npcTextID, creature->GetGUID());
 }
References Object::GetGUID(), and SendGossipMenuFor().
SendGossipMenuFor() [2/2]
void SendGossipMenuFor (Player * player, uint32 npcTextID, ObjectGuid const guid)
Definition at line 45 of file ScriptedGossip.cpp.
 {
     player->PlayerTalkClass->SendGossipMenu(npcTextID, guid);
 }
References Player::PlayerTalkClass, and PlayerMenu::SendGossipMenu().
Referenced by Creature::isCanInteractWithBattleMaster(), npc_pet_gen_argent_pony_bridle::OnGossipHello(), npc_lokhtos_darkbargainer::OnGossipHello(), boss_gloomrel::OnGossipHello(), boss_doomrel::OnGossipHello(), boss_majordomo::OnGossipHello(), npc_grandmother::OnGossipHello(), npc_barnes::OnGossipHello(), npc_death_knight_initiate::OnGossipHello(), npc_highlord_darion_mograine::OnGossipHello(), npc_fairbanks::OnGossipHello(), npc_augustus_the_touched::OnGossipHello(), npc_parqual_fintallas::OnGossipHello(), npc_varian_wrynn::OnGossipHello(), npc_thrall_bfu::OnGossipHello(), npc_zulaman_hostage::OnGossipHello(), npc_brewfest_keg_reciver::OnGossipHello(), npc_jaina_proudmoore::OnGossipHello(), npc_thrall::OnGossipHello(), npc_tyrande_whisperwind::OnGossipHello(), npc_arthas::OnGossipHello(), npc_rizzle_sprysprocket::OnGossipHello(), npc_aged_dying_ancient_kodo::OnGossipHello(), npc_lady_jaina_proudmoore::OnGossipHello(), npc_nat_pagle::OnGossipHello(), npcs_riverbreeze_and_silversky::OnGossipHello(), npc_bunthen_plainswind::OnGossipHello(), npc_great_bear_spirit::OnGossipHello(), npc_silva_filnaveth::OnGossipHello(), npc_thrall_warchief::OnGossipHello(), npc_braug_dimspirit::OnGossipHello(), npc_steward_of_time::OnGossipHello(), npc_stone_watcher_of_norgannon::OnGossipHello(), npc_beaten_corpse::OnGossipHello(), npc_plucky::OnGossipHello(), npc_rivern_frostwind::OnGossipHello(), npc_announcer_toc5::OnGossipHello(), npc_announcer_toc10::OnGossipHello(), npc_fos_leader::OnGossipHello(), npc_hor_leader::OnGossipHello(), npc_high_overlord_saurfang_icc::OnGossipHello(), npc_muradin_bronzebeard_icc::OnGossipHello(), npc_oculus_drakegiver::OnGossipHello(), brann_bronzebeard::OnGossipHello(), npc_ulduar_expedition_commander::OnGossipHello(), npc_ulduar_keeper::OnGossipHello(), npc_vh_sinclari::OnGossipHello(), npc_iruk::OnGossipHello(), npc_shandy_dalaran::OnGossipHello(), npc_razael_and_lyana::OnGossipHello(), npc_mcmanus::OnGossipHello(), npc_vekjik::OnGossipHello(), npc_avatar_of_freya::OnGossipHello(), npc_adventurous_dwarf::OnGossipHello(), npc_roxi_ramrocket::OnGossipHello(), npc_wg_demolisher_engineer::OnGossipHello(), npc_wg_spirit_guide::OnGossipHello(), npc_wg_queue::OnGossipHello(), npc_wg_quest_giver::OnGossipHello(), npc_finklestein::OnGossipHello(), adyen_the_lightbringer::OnGossipHello(), npc_captain_saeed::OnGossipHello(), npc_professor_dabiri::OnGossipHello(), npc_drake_dealer_hurlunk::OnGossipHello(), npcs_flanis_swiftwing_and_kagrosh::OnGossipHello(), npc_raliq_the_drunk::OnGossipHello(), npc_salsalabim::OnGossipHello(), npc_shattrathflaskvendors::OnGossipHello(), npc_zephyr::OnGossipHello(), npc_ishanah::OnGossipHello(), npc_floon::OnGossipHello(), npc_slim::OnGossipHello(), npcs_ashyen_and_keleth::OnGossipHello(), npc_cooshcoosh::OnGossipHello(), npc_elder_kuruti::OnGossipHello(), npc_mortog_steamhead::OnGossipHello(), npc_timothy_daniels::OnGossipHello(), npc_innkeeper::OnGossipHello(), npc_prof_alchemy::OnGossipHello(), npc_prof_blacksmith::OnGossipHello(), npc_engineering_tele_trinket::OnGossipHello(), npc_prof_leather::OnGossipHello(), npc_prof_tailor::OnGossipHello(), npc_artorius::OnGossipHello(), npc_simone::OnGossipHello(), npc_nelson::OnGossipHello(), npc_franklin::OnGossipHello(), npc_taxi::OnGossipHello(), npc_riggle_bassbait::OnGossipHello(), npc_sayge::OnGossipHello(), npc_wormhole::OnGossipHello(), npc_locksmith::OnGossipHello(), npc_experience::OnGossipHello(), go_evil_book_for_dummies::OnGossipHello(), icecrown_citadel_teleport::OnGossipHello(), go_ahune_ice_stone::OnGossipHello(), go_skull_pile::OnGossipHello(), go_fel_crystalforge::OnGossipHello(), go_bashir_crystalforge::OnGossipHello(), go_table_theka::OnGossipHello(), go_amberpine_outhouse::OnGossipHello(), boss_gloomrel::OnGossipSelect(), boss_doomrel::OnGossipSelect(), boss_majordomo::OnGossipSelect(), npc_barnes::OnGossipSelect(), npc_tyrande_whisperwind::OnGossipSelect(), npc_arthas::OnGossipSelect(), npc_lady_jaina_proudmoore::OnGossipSelect(), npc_bunthen_plainswind::OnGossipSelect(), npc_great_bear_spirit::OnGossipSelect(), npc_silva_filnaveth::OnGossipSelect(), npc_thrall_warchief::OnGossipSelect(), npc_stone_watcher_of_norgannon::OnGossipSelect(), npc_beaten_corpse::OnGossipSelect(), npc_razael_and_lyana::OnGossipSelect(), npc_vekjik::OnGossipSelect(), npc_avatar_of_freya::OnGossipSelect(), npc_ishanah::OnGossipSelect(), npc_floon::OnGossipSelect(), npc_elder_kuruti::OnGossipSelect(), npc_timothy_daniels::OnGossipSelect(), npc_fairbanks::OnGossipSelect(), npc_oculus_drakegiver::OnGossipSelect(), npc_vh_sinclari::OnGossipSelect(), go_fel_crystalforge::OnGossipSelect(), go_bashir_crystalforge::OnGossipSelect(), npc_sayge::SendAction(), npc_prof_blacksmith::SendActionMenu(), npc_prof_alchemy::SendConfirmLearn(), npc_prof_blacksmith::SendConfirmLearn(), npc_prof_tailor::SendConfirmLearn(), go_evil_book_for_dummies::SendConfirmLearn(), npc_prof_alchemy::SendConfirmUnlearn(), npc_prof_blacksmith::SendConfirmUnlearn(), npc_prof_tailor::SendConfirmUnlearn(), go_evil_book_for_dummies::SendConfirmUnlearn(), SendGossipMenuFor(), npc_sergeant_bly::npc_sergeant_blyAI::sGossipHello(), and npc_weegli_blastfuse::npc_weegli_blastfuseAI::sGossipHello().