Azerotcore-wotlk: QuestMenu Class Reference
QuestMenu Class Reference
#include <GossipDef.h>
Public Member Functions
uint8 GetMenuItemCount () const
bool Empty () const
QuestMenuItem const & GetItem (uint16 index) const
AddMenuItem
Adds a localized gossip menu item from db by menu id and menu item id.
Parameters
menuId Gossip menu id.
menuItemId Gossip menu item id.
sender Identifier of the current menu.
action Custom action given to OnGossipHello.
QuestMenu ()
~QuestMenu ()
void AddMenuItem (uint32 QuestId, uint8 Icon)
void ClearMenu ()
bool HasItem (uint32 questId) const
Private Attributes
QuestMenuItemList _questMenuItems
Detailed Description
Definition at line 222 of file GossipDef.h.
Constructor & Destructor Documentation
QuestMenu()
QuestMenu::QuestMenu ()
Definition at line 270 of file GossipDef.cpp.
 {
     _questMenuItems.reserve(16);                                   // can be set for max from most often sizes to speedup push_back and less memory use
 }
References _questMenuItems.
~QuestMenu()
QuestMenu::~QuestMenu ()
Definition at line 275 of file GossipDef.cpp.
 {
     ClearMenu();
 }
References ClearMenu().
Member Function Documentation
AddMenuItem()
void QuestMenu::AddMenuItem (uint32 QuestId, uint8 Icon)
Definition at line 280 of file GossipDef.cpp.
 {
     if (!sObjectMgr->GetQuestTemplate(QuestId))
         return;
     ASSERT(_questMenuItems.size() <= GOSSIP_MAX_MENU_ITEMS);
     QuestMenuItem questMenuItem;
     questMenuItem.QuestId        = QuestId;
     questMenuItem.QuestIcon      = Icon;
     _questMenuItems.push_back(questMenuItem);
 }
References _questMenuItems, ASSERT, GOSSIP_MAX_MENU_ITEMS, QuestMenuItem::QuestIcon, QuestMenuItem::QuestId, and sObjectMgr.
Referenced by npc_costumed_orphan_matron::OnGossipHello(), npc_wg_quest_giver::OnGossipHello(), and Player::PrepareQuestMenu().
ClearMenu()
void QuestMenu::ClearMenu ()
Definition at line 304 of file GossipDef.cpp.
 {
     _questMenuItems.clear();
 }
References _questMenuItems.
Referenced by PlayerMenu::ClearMenus(), npc_costumed_orphan_matron::OnGossipHello(), npc_wg_quest_giver::OnGossipHello(), npc_elder_clearwater::OnGossipHello(), Player::PrepareQuestMenu(), and ~QuestMenu().
Empty()
bool QuestMenu::Empty () const inline
Definition at line 236 of file GossipDef.h.
     {
         return _questMenuItems.empty();
     }
References _questMenuItems.
Referenced by PlayerMenu::Empty(), Player::SendPreparedGossip(), and Player::SendPreparedQuest().
GetItem()
QuestMenuItem const& QuestMenu::GetItem (uint16 index) const inline
Definition at line 243 of file GossipDef.h.
     {
         return _questMenuItems[index];
     }
References _questMenuItems, and index.
Referenced by PlayerMenu::SendGossipMenu(), Player::SendPreparedQuest(), and PlayerMenu::SendQuestGiverQuestList().
GetMenuItemCount()
uint8 QuestMenu::GetMenuItemCount () const inline
Definition at line 231 of file GossipDef.h.
     {
         return _questMenuItems.size();
     }
References _questMenuItems.
Referenced by PlayerMenu::SendGossipMenu(), Player::SendPreparedQuest(), and PlayerMenu::SendQuestGiverQuestList().
HasItem()
bool QuestMenu::HasItem (uint32 questId) const
Definition at line 295 of file GossipDef.cpp.
 {
     for (QuestMenuItemList::const_iterator i = _questMenuItems.begin(); i != _questMenuItems.end(); ++i)
         if (i->QuestId == questId)
             return true;
     return false;
 }
References _questMenuItems.
Member Data Documentation
_questMenuItems
QuestMenuItemList QuestMenu::_questMenuItems private
Definition at line 249 of file GossipDef.h.
Referenced by AddMenuItem(), ClearMenu(), Empty(), GetItem(), GetMenuItemCount(), HasItem(), and QuestMenu().
The documentation for this class was generated from the following files:
src/server/game/Entities/Creature/GossipDef.h
src/server/game/Entities/Creature/GossipDef.cpp