Azerotcore-wotlk: npc_wormhole Class Reference
npc_wormhole Class Reference
Classes
struct npc_wormholeAI
Public Member Functions
npc_wormhole ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 1692 of file npcs_special.cpp.
Constructor & Destructor Documentation
npc_wormhole()
npc_wormhole::npc_wormhole () inline
Definition at line 1695 of file npcs_special.cpp.
 : CreatureScript("npc_wormhole") { }
Member Function Documentation
GetAI()
CreatureAI* npc_wormhole::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 1772 of file npcs_special.cpp.
     {
         return new npc_wormholeAI(creature);
     }
OnGossipHello()
bool npc_wormhole::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 1715 of file npcs_special.cpp.
     {
         if (creature->IsSummon())
         {
             if (player == creature->ToTempSummon()->GetSummonerUnit())
             {
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ENGINEERING1, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ENGINEERING2, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ENGINEERING3, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 3);
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ENGINEERING4, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 4);
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ENGINEERING5, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 5);
                 if (creature->AI()->GetData(DATA_SHOW_UNDERGROUND))
                     AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ENGINEERING6, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 6);
                 SendGossipMenuFor(player, TEXT_WORMHOLE, creature);
             }
         }
         return true;
     }
References AddGossipItemFor(), Creature::AI(), DATA_SHOW_UNDERGROUND, UnitAI::GetData(), TempSummon::GetSummonerUnit(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ENGINEERING1, GOSSIP_ENGINEERING2, GOSSIP_ENGINEERING3, GOSSIP_ENGINEERING4, GOSSIP_ENGINEERING5, GOSSIP_ENGINEERING6, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, Unit::IsSummon(), SendGossipMenuFor(), TEXT_WORMHOLE, and Unit::ToTempSummon().
OnGossipSelect()
bool npc_wormhole::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 1737 of file npcs_special.cpp.
     {
         ClearGossipMenuFor(player);
         switch (action)
         {
             case GOSSIP_ACTION_INFO_DEF + 1: // Borean Tundra
                 CloseGossipMenuFor(player);
                 creature->CastSpell(player, SPELL_BOREAN_TUNDRA, false);
                 break;
             case GOSSIP_ACTION_INFO_DEF + 2: // Howling Fjord
                 CloseGossipMenuFor(player);
                 creature->CastSpell(player, SPELL_HOWLING_FJORD, false);
                 break;
             case GOSSIP_ACTION_INFO_DEF + 3: // Sholazar Basin
                 CloseGossipMenuFor(player);
                 creature->CastSpell(player, SPELL_SHOLAZAR_BASIN, false);
                 break;
             case GOSSIP_ACTION_INFO_DEF + 4: // Icecrown
                 CloseGossipMenuFor(player);
                 creature->CastSpell(player, SPELL_ICECROWN, false);
                 break;
             case GOSSIP_ACTION_INFO_DEF + 5: // Storm peaks
                 CloseGossipMenuFor(player);
                 creature->CastSpell(player, SPELL_STORM_PEAKS, false);
                 break;
             case GOSSIP_ACTION_INFO_DEF + 6: // Underground
                 CloseGossipMenuFor(player);
                 creature->CastSpell(player, SPELL_UNDERGROUND, false);
                 break;
         }
         return true;
     }
References Unit::CastSpell(), ClearGossipMenuFor(), CloseGossipMenuFor(), GOSSIP_ACTION_INFO_DEF, SPELL_BOREAN_TUNDRA, SPELL_HOWLING_FJORD, SPELL_ICECROWN, SPELL_SHOLAZAR_BASIN, SPELL_STORM_PEAKS, and SPELL_UNDERGROUND.
The documentation for this class was generated from the following file:
src/server/scripts/World/npcs_special.cpp