Azerotcore-wotlk: G3D::Stopwatch Class Reference
G3D::Stopwatch Class Reference
Accurately measure durations and framerates.
#include <Stopwatch.h>
Public Member Functions
Stopwatch (const std::string &name="Stopwatch")
void setEnabled (bool e)
bool enabled () const
double FPS () const
RealTime elapsedTime () const
RealTime smoothElapsedTime () const
double smoothFPS () const
uint64 elapsedCycles () const
void tick ()
void tock ()
void reset ()
void after (const std::string &s="")
Private Member Functions
void computeOverhead ()
Private Attributes
std::string myName
bool m_enabled
double startTime
std::string prevMark
double prevTime
bool inBetween
uint64 cycleStart
RealTime timeStart
RealTime lastTockTime
RealTime lastDuration
int64 lastCycleCount
double m_fps
double emwaFPS
double m_smoothFPS
RealTime emwaDuration
int64 cycleOverhead
Detailed Description
Accurately measure durations and framerates.
Example 1: For profiling code in the context of a rendering loop:
    sw.tick();
    ...timed code...
    sw.tock();
    screenPrintf("%f\n", sw.smoothFPS());
Example 2: For profiling pieces of a sequence:
  Stopwatch sw;
  slowOperation();
  sw.after("slowOperation");
  kdTree.balance();
  sw.after("Balance tree");
Definition at line 45 of file Stopwatch.h.
Constructor & Destructor Documentation
Stopwatch()
G3D::Stopwatch::Stopwatch (const std::string & name = "Stopwatch")
Definition at line 18 of file Stopwatch.cpp.
                                             :
     myName(myName),
     inBetween(false), lastTockTime(-1),
     lastDuration(0), lastCycleCount(0), m_fps(0), emwaFPS(0),
     m_smoothFPS(0), emwaDuration(0) {
     computeOverhead();
     reset();
 }
References computeOverhead(), and reset().
Member Function Documentation
after()
void G3D::Stopwatch::after (const std::string & s = "")
Call after an operation has completed, with the name of the operation, to print a debug message listing the time since the previous after() call.
Does nothing if the stopwatch is disabled.
Definition at line 106 of file Stopwatch.cpp.
{
     RealTime now = System::time();
     if (m_enabled) {
         debugPrintf("%s: %10s - %8fs since %s (%fs since start)\n",
                myName.c_str(),
                s.c_str(),
                now - prevTime,
                prevMark.c_str(),
                now - startTime);
     }
     prevTime = now;
     prevMark = s;
 }
References G3D::debugPrintf(), m_enabled, myName, prevMark, prevTime, startTime, and G3D::System::time().
computeOverhead()
void G3D::Stopwatch::computeOverhead () private
Called from the constructor.
Definition at line 28 of file Stopwatch.cpp.
{
     cycleOverhead = 0;
     tick();
     tock();
     cycleOverhead = elapsedCycles();
 }
References cycleOverhead, elapsedCycles(), tick(), and tock().
Referenced by Stopwatch().
elapsedCycles()
uint64 G3D::Stopwatch::elapsedCycles () const inline
The elapsed cycle time between tick and tock. An attempt is made to factor out all tick/tock overhead, so that back-to-back calls should return zero.
Unreliable on non-x86 platforms.
Definition at line 130 of file Stopwatch.h.
{
         return lastCycleCount;
     }
References lastCycleCount.
Referenced by computeOverhead().
elapsedTime()
RealTime G3D::Stopwatch::elapsedTime () const inline
Amount of time between the most recent tick and tock calls. 0 if tick has never been called.
Definition at line 108 of file Stopwatch.h.
{
         return lastDuration;
     }
References lastDuration.
enabled()
bool G3D::Stopwatch::enabled () const inline
A stopwatch only prints output when enabled
Definition at line 96 of file Stopwatch.h.
{
         return m_enabled;
     }
References m_enabled.
FPS()
double G3D::Stopwatch::FPS () const inline
Returns the number of times that tick was called per wall-clock second; e.g. frames-per-second.
Definition at line 102 of file Stopwatch.h.
{
         return m_fps;
     }
References m_fps.
reset()
void G3D::Stopwatch::reset ()
Reset the start time used by after() and the emwa value.
Definition at line 100 of file Stopwatch.cpp.
                       {
     prevTime = startTime = System::time();
     prevMark = "start";
 }
References prevMark, prevTime, startTime, and G3D::System::time().
Referenced by Stopwatch().
setEnabled()
void G3D::Stopwatch::setEnabled (bool e) inline
Definition at line 91 of file Stopwatch.h.
{
         m_enabled = e;
     }
References m_enabled.
smoothElapsedTime()
RealTime G3D::Stopwatch::smoothElapsedTime () const inline
Time-smoothed value that is stable to the nearest 1%. This is useful if you are displaying elapsed time in real-time and want a stable number.
Definition at line 115 of file Stopwatch.h.
{
         return emwaDuration;
     }
References emwaDuration.
smoothFPS()
double G3D::Stopwatch::smoothFPS () const inline
Time-smoothed value of fps that is stable to the nearest integer for fps > 10 and to the first decimal place for fps <= 10. This is useful if you are displaying the frame rate in real-time and want a stable (readable) number.
Definition at line 123 of file Stopwatch.h.
{
         return m_smoothFPS;
     }
References m_smoothFPS.
tick()
void G3D::Stopwatch::tick ()
Call at the beginning of the period that you want timed.
Definition at line 36 of file Stopwatch.cpp.
                      {
     // This is 'alwaysAssert' instead of 'debugAssert'
     // since people rarely profile in debug mode.
     alwaysAssertM(! inBetween, "Stopwatch::tick() called twice in a row.");
     inBetween = true;
     // We read RDTSC twice here, but it is more abstract to implement this
     // way and at least we're reading the cycle count last.
     timeStart = System::time();
     System::beginCycleCount(cycleStart);
 }
References alwaysAssertM, G3D::System::beginCycleCount(), cycleStart, inBetween, G3D::System::time(), and timeStart.
Referenced by computeOverhead().
tock()
void G3D::Stopwatch::tock ()
Call at the end of the period that you want timed.
Definition at line 49 of file Stopwatch.cpp.
                      {
     System::endCycleCount(cycleStart);
     RealTime now = System::time();
     lastDuration = now - timeStart;
     if (abs(emwaDuration - lastDuration) > max(emwaDuration, lastDuration) * 0.50) {
         // Off by more than 50%
         emwaDuration = lastDuration;
     } else {
         emwaDuration = lastDuration * 0.05 + emwaDuration * 0.95;
     }
     lastCycleCount = cycleStart - cycleOverhead;
     if (lastCycleCount < 0) {
         lastCycleCount = 0;
     }
     if (lastTockTime != -1.0) {
         m_fps = 1.0 / (now - lastTockTime);
         const double blend = 0.01;
         emwaFPS = m_fps * blend + emwaFPS * (1.0 - blend);
         double maxDiscrepancyPercentage = 0.25;
         if (abs(emwaFPS - m_fps) > max(emwaFPS, m_fps) * maxDiscrepancyPercentage) {
             // The difference between emwa and m_fps is way off, so
             // update emwa directly.
             emwaFPS = m_fps * 0.20 + emwaFPS * 0.80;
         }
         // Update m_smoothFPS only when the value varies significantly.
         // We round so as to not mislead the user as to the accuracy of
         // the number.
         if (m_smoothFPS == 0) {
             m_smoothFPS = m_fps;
         } else if (emwaFPS <= 20) {
             if (::fabs(m_smoothFPS - emwaFPS) > 0.75) {
                 // Small number and display is off by more than 0.75; round to the nearest 0.1
                 m_smoothFPS = floor(emwaFPS * 10.0 + 0.5) / 10.0;
             }
         } else if (::fabs(m_smoothFPS - emwaFPS) > 1.25) {
             // Large number and display is off by more than 1.25; round to the nearest 1.0
             m_smoothFPS = floor(emwaFPS + 0.5);
         }
     }
     lastTockTime = now;
     alwaysAssertM(inBetween, "Stopwatch::tock() called without matching tick.");
     inBetween = false;
 }
References G3D::abs(), alwaysAssertM, cycleOverhead, cycleStart, emwaDuration, emwaFPS, G3D::System::endCycleCount(), G3D::floor(), inBetween, lastCycleCount, lastDuration, lastTockTime, m_fps, m_smoothFPS, G3D::max(), G3D::System::time(), and timeStart.
Referenced by computeOverhead().
Member Data Documentation
cycleOverhead
int64 G3D::Stopwatch::cycleOverhead private
The overhead for calling into the class.
Definition at line 82 of file Stopwatch.h.
Referenced by computeOverhead(), and tock().
cycleStart
uint64 G3D::Stopwatch::cycleStart private
The initial cycle count.
Definition at line 60 of file Stopwatch.h.
Referenced by tick(), and tock().
emwaDuration
RealTime G3D::Stopwatch::emwaDuration private
Weighted duration
Definition at line 79 of file Stopwatch.h.
Referenced by smoothElapsedTime(), and tock().
emwaFPS
double G3D::Stopwatch::emwaFPS private
Weighted fps
Definition at line 75 of file Stopwatch.h.
Referenced by tock().
inBetween
bool G3D::Stopwatch::inBetween private
True between tick and tock
Definition at line 57 of file Stopwatch.h.
Referenced by tick(), and tock().
lastCycleCount
int64 G3D::Stopwatch::lastCycleCount private
Definition at line 69 of file Stopwatch.h.
Referenced by elapsedCycles(), and tock().
lastDuration
RealTime G3D::Stopwatch::lastDuration private
Definition at line 68 of file Stopwatch.h.
Referenced by elapsedTime(), and tock().
lastTockTime
RealTime G3D::Stopwatch::lastTockTime private
The time at which the previous tock was called, -1 if never.
Definition at line 66 of file Stopwatch.h.
Referenced by tock().
m_enabled
bool G3D::Stopwatch::m_enabled private
Definition at line 50 of file Stopwatch.h.
Referenced by after(), enabled(), and setEnabled().
m_fps
double G3D::Stopwatch::m_fps private
Frames per second.
Definition at line 72 of file Stopwatch.h.
Referenced by FPS(), and tock().
m_smoothFPS
double G3D::Stopwatch::m_smoothFPS private
Definition at line 76 of file Stopwatch.h.
Referenced by smoothFPS(), and tock().
myName
std::string G3D::Stopwatch::myName private
Definition at line 48 of file Stopwatch.h.
Referenced by after().
prevMark
std::string G3D::Stopwatch::prevMark private
Definition at line 53 of file Stopwatch.h.
Referenced by after(), and reset().
prevTime
double G3D::Stopwatch::prevTime private
Definition at line 54 of file Stopwatch.h.
Referenced by after(), and reset().
startTime
double G3D::Stopwatch::startTime private
Definition at line 52 of file Stopwatch.h.
Referenced by after(), and reset().
timeStart
RealTime G3D::Stopwatch::timeStart private
The time at which tick was called.
Definition at line 63 of file Stopwatch.h.
Referenced by tick(), and tock().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/Stopwatch.h
deps/g3dlite/source/Stopwatch.cpp