Azerotcore-wotlk: ZoneScript Class Reference
ZoneScript Class Reference
#include <ZoneScript.h>
Public Member Functions
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRemove (Creature *)
virtual void OnGameObjectCreate (GameObject *)
virtual void OnGameObjectRemove (GameObject *)
virtual void OnUnitDeath (Unit *)
virtual ObjectGuid GetGuidData (uint32) const
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Detailed Description
Definition at line 26 of file ZoneScript.h.
Constructor & Destructor Documentation
ZoneScript()
ZoneScript::ZoneScript () inline
Definition at line 29 of file ZoneScript.h.
 {}
~ZoneScript()
virtual ZoneScript::~ZoneScript () inline virtual
Definition at line 30 of file ZoneScript.h.
 {}
Member Function Documentation
GetCreatureEntry()
virtual uint32 ZoneScript::GetCreatureEntry (ObjectGuid::LowType , CreatureData const * data) inline virtual
Reimplemented in instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript, and instance_pit_of_saron::instance_pit_of_saron_InstanceScript.
Definition at line 32 of file ZoneScript.h.
 { return data->id; }
References CreatureData::id.
Referenced by Creature::CreateFromProto().
GetData()
virtual uint32 ZoneScript::GetData (uint32) const inline virtual
Reimplemented in instance_arcatraz::instance_arcatraz_InstanceMapScript, instance_halls_of_lightning::instance_halls_of_lightning_InstanceMapScript, instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript, instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript, instance_blood_furnace::instance_blood_furnace_InstanceMapScript, instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript, instance_steam_vault::instance_steam_vault_InstanceMapScript, instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript, instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript, instance_violet_hold::instance_violet_hold_InstanceMapScript, instance_utgarde_pinnacle::instance_utgarde_pinnacle_InstanceMapScript, instance_ulduar::instance_ulduar_InstanceMapScript, instance_oculus::instance_oculus_InstanceMapScript, instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript, instance_pit_of_saron::instance_pit_of_saron_InstanceScript, instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript, instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript, instance_ahnkahet::instance_ahnkahet_InstanceScript, instance_zulfarrak::instance_zulfarrak_InstanceMapScript, instance_wailing_caverns::instance_wailing_caverns_InstanceMapScript, instance_temple_of_ahnqiraj::instance_temple_of_ahnqiraj_InstanceMapScript, instance_razorfen_downs::instance_razorfen_downs_InstanceMapScript, instance_dire_maul::instance_dire_maul_InstanceMapScript, instance_the_black_morass::instance_the_black_morass_InstanceMapScript, instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript, instance_hyjal::instance_mount_hyjal_InstanceMapScript, instance_zulaman::instance_zulaman_InstanceMapScript, instance_sunken_temple::instance_sunken_temple_InstanceMapScript, instance_stratholme::instance_stratholme_InstanceMapScript, instance_scholomance::instance_scholomance_InstanceMapScript, instance_scarlet_monastery::instance_scarlet_monastery_InstanceMapScript, instance_karazhan::instance_karazhan_InstanceMapScript, instance_blackrock_spire::instance_blackrock_spireMapScript, instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript, instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript, instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript, instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript, instance_halls_of_stone::instance_halls_of_stone_InstanceMapScript, instance_naxxramas::instance_naxxramas_InstanceMapScript, Battlefield, instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript, instance_uldaman::instance_uldaman_InstanceMapScript, and BattlefieldWG.
Definition at line 51 of file ZoneScript.h.
 { return 0; }
Referenced by boss_loken::boss_lokenAI::boss_lokenAI(), boss_yoggsaron::boss_yoggsaronAI::boss_yoggsaronAI(), boss_ick::boss_ickAI::CanAIAttack(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::CanAIAttack(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::CanAIAttack(), boss_eye_of_cthun::eye_of_cthunAI::DamageTaken(), boss_cthun::cthunAI::DamageTaken(), boss_grand_champion::boss_grand_championAI::DamageTaken(), boss_sindragosa::boss_sindragosaAI::DamageTaken(), npc_ulduar_flash_freeze::npc_ulduar_flash_freezeAI::DamageTaken(), boss_black_knight::boss_black_knightAI::DoAction(), npc_forest_frog::npc_forest_frogAI::DoSpawnRandom(), boss_grand_champion::boss_grand_championAI::EnterCombat(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::EnterCombat(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::EnterCombat(), boss_sjonnir::boss_sjonnirAI::EnterCombat(), boss_freya::boss_freyaAI::EnterCombat(), boss_hodir::boss_hodirAI::EnterCombat(), boss_mimiron::boss_mimironAI::EnterCombat(), npc_dragonflayer_forge_master::npc_dragonflayer_forge_masterAI::EnterCombat(), boss_ymiron::boss_ymironAI::EnterCombat(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::EnterCombat(), npc_ghostly_priest::npc_ghostly_priestAI::EnterEvadeMode(), npc_phantom_mage::npc_phantom_mageAI::EnterEvadeMode(), npc_shadowy_mercenary::npc_shadowy_mercenaryAI::EnterEvadeMode(), npc_spectral_footman::npc_spectral_footmanAI::EnterEvadeMode(), npc_tortured_rifleman::npc_tortured_riflemanAI::EnterEvadeMode(), instance_blackrock_spire::instance_blackrock_spireMapScript::GetData(), hyjalAI::GetInstanceData(), spell_serpentshrine_cavern_coilfang_water::spell_serpentshrine_cavern_coilfang_water_AuraScript::HandlePeriodic(), spell_temple_of_atal_hakkar_awaken_the_soulflayer::spell_temple_of_atal_hakkar_awaken_the_soulflayer_SpellScript::HandleSendEvent(), spell_uldaman_boss_agro_archaedas::spell_uldaman_boss_agro_archaedas_SpellScript::HandleSendEvent(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::InitFight(), boss_taldaram::boss_taldaramAI::InitializeAI(), npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI::InitializeAI(), boss_flame_leviathan::boss_flame_leviathanAI::InitializeAI(), hyjal_trashAI::JustDied(), hyjalAI::JustDied(), boss_kri::boss_kriAI::JustDied(), boss_vem::boss_vemAI::JustDied(), boss_yauj::boss_yaujAI::JustDied(), gunship_npc_AI::JustDied(), brann_bronzebeard::brann_bronzebeardAI::JustDied(), boss_high_king_maulgar::boss_high_king_maulgarAI::JustDied(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::JustDied(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::JustReachedHome(), npc_tirion_fordring_tft::npc_tirion_fordringAI::JustReachedHome(), npc_medivh_bm::npc_medivh_bmAI::MoveInLineOfSight(), npc_gunship_boarding_addAI::MovementInform(), npc_sergeant_bly::npc_sergeant_blyAI::MovementInform(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::MovementInform(), npc_announcer_toc5::npc_announcer_toc5AI::MovementInform(), npc_azure_saboteur::npc_azure_saboteurAI::npc_azure_saboteurAI(), npc_hor_leader::npc_hor_leaderAI::npc_hor_leaderAI(), npc_oculus_drakegiver::npc_oculus_drakegiverAI::npc_oculus_drakegiverAI(), npc_ulduar_expedition_commander::npc_ulduar_expedition_commanderAI::npc_ulduar_expedition_commanderAI(), npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::npc_vh_teleportation_portalAI(), achievement_flame_leviathan_unbroken::OnCheck(), go_main_chambers_access_panel::OnGossipHello(), npc_arthas::OnGossipHello(), npc_cos_chromie_middle::OnGossipHello(), npc_thrall_old_hillsbrad::OnGossipHello(), npc_announcer_toc5::OnGossipHello(), npc_announcer_toc10::OnGossipHello(), npc_oculus_drakegiver::OnGossipHello(), brann_bronzebeard::OnGossipHello(), npc_ulduar_expedition_commander::OnGossipHello(), go_prince_taldaram_sphere::OnGossipHello(), go_harpoon_canon::OnGossipHello(), npc_hor_leader::OnGossipSelect(), npc_ulduar_expedition_commander::OnGossipSelect(), npc_cos_chromie_middle::OnGossipSelect(), npc_thrall_old_hillsbrad::OnGossipSelect(), npc_rocknot::OnQuestReward(), at_icc_saurfang_portal::OnTrigger(), at_thaddius_entrance::OnTrigger(), at_hor_shadow_throne::OnTrigger(), at_tyrannus_event_starter::OnTrigger(), spell_igb_gunship_fall_teleport::spell_igb_gunship_fall_teleport_SpellScript::RelocateDest(), boss_doomrel::boss_doomrelAI::Reset(), boss_nightbane::boss_nightbaneAI::Reset(), boss_servant_quarters::boss_servant_quartersAI::Reset(), npc_barnes::npc_barnesAI::Reset(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::Reset(), hyjalAI::Reset(), npc_arthas::npc_arthasAI::Reset(), npc_cos_stratholme_citizien::npc_cos_stratholme_citizienAI::Reset(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::Reset(), npc_medivh_bm::npc_medivh_bmAI::Reset(), npc_time_rift::npc_time_riftAI::Reset(), boss_grand_champion::boss_grand_championAI::Reset(), npc_announcer_toc5::npc_announcer_toc5AI::Reset(), npc_pos_leader::npc_pos_leaderAI::Reset(), npc_tirion_fordring_tft::npc_tirion_fordringAI::Reset(), npc_icc_putricades_trap::npc_icc_putricades_trapAI::Reset(), boss_eregos::boss_eregosAI::Reset(), boss_urom::boss_uromAI::Reset(), boss_varos::boss_varosAI::Reset(), boss_sjonnir::boss_sjonnirAI::Reset(), brann_bronzebeard::brann_bronzebeardAI::Reset(), boss_flame_leviathan::boss_flame_leviathanAI::Reset(), boss_freya::boss_freyaAI::Reset(), boss_hodir::boss_hodirAI::Reset(), boss_mimiron::boss_mimironAI::Reset(), boss_ymiron::boss_ymironAI::Reset(), boss_archavon::boss_archavonAI::Reset(), boss_emalon::boss_emalonAI::Reset(), boss_koralon::boss_koralonAI::Reset(), boss_toravon::boss_toravonAI::Reset(), boss_ambassador_hellmaw::boss_ambassador_hellmawAI::Reset(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::SaveKeepers(), boss_svala::boss_svalaAI::SetData(), npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::SetData(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::SetData(), npc_pos_leader::npc_pos_leaderAI::SetData(), gunship_npc_AI::SetSlotInfo(), npc_gunship_boarding_addAI::SetSlotInfo(), npc_sergeant_bly::npc_sergeant_blyAI::sGossipHello(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::sGossipHello(), npc_tirion_fordring_tft::npc_tirion_fordringAI::sGossipSelect(), hyjalAI::SummonCreature(), SummonCroneIfReady(), npc_arthas::npc_arthasAI::SummonedCreatureDies(), hyjalAI::SummonNextWave(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::SummonWaveP1(), TriggerBurningPitch(), npc_mograine::npc_mograineAI::UpdateAI(), npc_janalai_hatcher::npc_janalai_hatcherAI::UpdateAI(), npc_janalai_hatchling::npc_janalai_hatchlingAI::UpdateAI(), npc_harrison_jones::npc_harrison_jonesAI::UpdateAI(), boss_archimonde::boss_archimondeAI::UpdateAI(), npc_giant_infernal::npc_giant_infernalAI::UpdateAI(), npc_abomination::npc_abominationAI::UpdateAI(), npc_ghoul::npc_ghoulAI::UpdateAI(), npc_necromancer::npc_necromancerAI::UpdateAI(), npc_banshee::npc_bansheeAI::UpdateAI(), npc_crypt_fiend::npc_crypt_fiendAI::UpdateAI(), npc_fel_stalker::npc_fel_stalkerAI::UpdateAI(), hyjalAI::UpdateAI(), npc_cos_stratholme_citizien::npc_cos_stratholme_citizienAI::UpdateAI(), npc_medivh_bm::npc_medivh_bmAI::UpdateAI(), boss_kri::boss_kriAI::UpdateAI(), boss_yauj::boss_yaujAI::UpdateAI(), boss_eye_of_cthun::eye_of_cthunAI::UpdateAI(), boss_cthun::cthunAI::UpdateAI(), boss_grand_champion::boss_grand_championAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), npc_pos_icicle_trigger::npc_pos_icicle_triggerAI::UpdateAI(), npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::UpdateAI(), npc_oculus_drakegiver::npc_oculus_drakegiverAI::UpdateAI(), npc_oculus_drake::npc_oculus_drakeAI::UpdateAI(), boss_hodir::boss_hodirAI::UpdateAI(), boss_yoggsaron_keeper::boss_yoggsaron_keeperAI::UpdateAI(), npc_vrykul_skeleton::npc_vrykul_skeletonAI::UpdateAI(), boss_hexlord_addAI::UpdateAI(), violet_hold_trashAI::violet_hold_trashAI(), npc_giant_infernal::npc_giant_infernalAI::WaypointReached(), npc_abomination::npc_abominationAI::WaypointReached(), npc_ghoul::npc_ghoulAI::WaypointReached(), npc_necromancer::npc_necromancerAI::WaypointReached(), npc_banshee::npc_bansheeAI::WaypointReached(), npc_crypt_fiend::npc_crypt_fiendAI::WaypointReached(), and npc_fel_stalker::npc_fel_stalkerAI::WaypointReached().
GetData64()
virtual uint64 ZoneScript::GetData64 (uint32) const inline virtual
Reimplemented in Battlefield.
Definition at line 47 of file ZoneScript.h.
 { return 0; }
GetGameObjectEntry()
virtual uint32 ZoneScript::GetGameObjectEntry (ObjectGuid::LowType , uint32 entry) inline virtual
Reimplemented in instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript.
Definition at line 33 of file ZoneScript.h.
 { return entry; }
Referenced by GameObject::Create(), and StaticTransport::Create().
GetGuidData()
virtual ObjectGuid ZoneScript::GetGuidData (uint32) const inline virtual
Reimplemented in instance_halls_of_lightning::instance_halls_of_lightning_InstanceMapScript, instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript, instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript, instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript, instance_zulgurub::instance_zulgurub_InstanceMapScript, instance_the_slave_pens::instance_the_slave_pens_InstanceMapScript, instance_black_temple::instance_black_temple_InstanceMapScript, instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript, instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript, instance_pit_of_saron::instance_pit_of_saron_InstanceScript, instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript, instance_forge_of_souls::instance_forge_of_souls_InstanceScript, instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript, instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript, instance_ahnkahet::instance_ahnkahet_InstanceScript, instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript, instance_zulaman::instance_zulaman_InstanceMapScript, instance_scholomance::instance_scholomance_InstanceMapScript, instance_scarlet_monastery::instance_scarlet_monastery_InstanceMapScript, instance_molten_core::instance_molten_core_InstanceMapScript, instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript, instance_blackrock_spire::instance_blackrock_spireMapScript, InstanceScript, instance_the_eye::instance_the_eye_InstanceMapScript, instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript, instance_violet_hold::instance_violet_hold_InstanceMapScript, instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript, instance_utgarde_pinnacle::instance_utgarde_pinnacle_InstanceMapScript, instance_oculus::instance_oculus_InstanceMapScript, instance_temple_of_ahnqiraj::instance_temple_of_ahnqiraj_InstanceMapScript, instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript, instance_hyjal::instance_mount_hyjal_InstanceMapScript, instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript, instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript, instance_halls_of_stone::instance_halls_of_stone_InstanceMapScript, instance_naxxramas::instance_naxxramas_InstanceMapScript, instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript, instance_arcatraz::instance_arcatraz_InstanceMapScript, instance_shattered_halls::instance_shattered_halls_InstanceMapScript, instance_blood_furnace::instance_blood_furnace_InstanceMapScript, instance_steam_vault::instance_steam_vault_InstanceMapScript, instance_ulduar::instance_ulduar_InstanceMapScript, instance_zulfarrak::instance_zulfarrak_InstanceMapScript, instance_the_black_morass::instance_the_black_morass_InstanceMapScript, instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript, instance_karazhan::instance_karazhan_InstanceMapScript, and instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript.
Definition at line 44 of file ZoneScript.h.
 { return ObjectGuid::Empty; }
References ObjectGuid::Empty.
OnCreatureCreate()
virtual void ZoneScript::OnCreatureCreate (Creature *) inline virtual
Reimplemented in instance_utgarde_pinnacle::instance_utgarde_pinnacle_InstanceMapScript, instance_halls_of_lightning::instance_halls_of_lightning_InstanceMapScript, instance_oculus::instance_oculus_InstanceMapScript, instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript, instance_ahnkahet::instance_ahnkahet_InstanceScript, instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript, instance_mechanar::instance_mechanar_InstanceMapScript, instance_the_eye::instance_the_eye_InstanceMapScript, instance_arcatraz::instance_arcatraz_InstanceMapScript, instance_shattered_halls::instance_shattered_halls_InstanceMapScript, instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript, instance_blood_furnace::instance_blood_furnace_InstanceMapScript, instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript, instance_steam_vault::instance_steam_vault_InstanceMapScript, instance_the_slave_pens::instance_the_slave_pens_InstanceMapScript, instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript, instance_black_temple::instance_black_temple_InstanceMapScript, instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript, instance_sethekk_halls::instance_sethekk_halls_InstanceMapScript, instance_violet_hold::instance_violet_hold_InstanceMapScript, instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript, instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript, instance_ulduar::instance_ulduar_InstanceMapScript, instance_halls_of_stone::instance_halls_of_stone_InstanceMapScript, instance_nexus::instance_nexus_InstanceMapScript, instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript, instance_naxxramas::instance_naxxramas_InstanceMapScript, instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript, instance_pit_of_saron::instance_pit_of_saron_InstanceScript, instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript, instance_forge_of_souls::instance_forge_of_souls_InstanceScript, instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript, instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript, instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript, instance_azjol_nerub::instance_azjol_nerub_InstanceScript, instance_zulfarrak::instance_zulfarrak_InstanceMapScript, instance_wailing_caverns::instance_wailing_caverns_InstanceMapScript, instance_temple_of_ahnqiraj::instance_temple_of_ahnqiraj_InstanceMapScript, instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript, instance_dire_maul::instance_dire_maul_InstanceMapScript, instance_the_black_morass::instance_the_black_morass_InstanceMapScript, instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript, instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript, instance_hyjal::instance_mount_hyjal_InstanceMapScript, instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript, instance_zulgurub::instance_zulgurub_InstanceMapScript, instance_zulaman::instance_zulaman_InstanceMapScript, instance_uldaman::instance_uldaman_InstanceMapScript, instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript, instance_sunken_temple::instance_sunken_temple_InstanceMapScript, instance_stratholme::instance_stratholme_InstanceMapScript, instance_scarlet_monastery::instance_scarlet_monastery_InstanceMapScript, instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript, instance_karazhan::instance_karazhan_InstanceMapScript, instance_molten_core::instance_molten_core_InstanceMapScript, instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript, instance_blackrock_spire::instance_blackrock_spireMapScript, instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript, OutdoorPvP, InstanceScript, BattlefieldWG, and instance_scholomance::instance_scholomance_InstanceMapScript.
Definition at line 35 of file ZoneScript.h.
 { }
Referenced by Creature::AddToWorld().
OnCreatureRemove()
virtual void ZoneScript::OnCreatureRemove (Creature *) inline virtual
Reimplemented in instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript, instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript, instance_ulduar::instance_ulduar_InstanceMapScript, instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript, instance_the_black_morass::instance_the_black_morass_InstanceMapScript, instance_molten_core::instance_molten_core_InstanceMapScript, OutdoorPvP, InstanceScript, and BattlefieldWG.
Definition at line 36 of file ZoneScript.h.
 { }
Referenced by Creature::RemoveFromWorld().
OnGameObjectCreate()
virtual void ZoneScript::OnGameObjectCreate (GameObject *) inline virtual
Reimplemented in instance_utgarde_pinnacle::instance_utgarde_pinnacle_InstanceMapScript, instance_halls_of_lightning::instance_halls_of_lightning_InstanceMapScript, instance_oculus::instance_oculus_InstanceMapScript, instance_naxxramas::instance_naxxramas_InstanceMapScript, instance_ahnkahet::instance_ahnkahet_InstanceScript, instance_the_eye::instance_the_eye_InstanceMapScript, instance_arcatraz::instance_arcatraz_InstanceMapScript, instance_shattered_halls::instance_shattered_halls_InstanceMapScript, instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript, instance_hellfire_ramparts::instance_hellfire_ramparts_InstanceMapScript, instance_blood_furnace::instance_blood_furnace_InstanceMapScript, instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript, instance_steam_vault::instance_steam_vault_InstanceMapScript, instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript, instance_black_temple::instance_black_temple_InstanceMapScript, instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript, instance_sethekk_halls::instance_sethekk_halls_InstanceMapScript, instance_violet_hold::instance_violet_hold_InstanceMapScript, instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript, instance_halls_of_stone::instance_halls_of_stone_InstanceMapScript, instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript, instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript, instance_pit_of_saron::instance_pit_of_saron_InstanceScript, instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript, instance_drak_tharon_keep::instance_drak_tharon_keep_InstanceScript, instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript, instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript, instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript, instance_azjol_nerub::instance_azjol_nerub_InstanceScript, instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript, instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript, instance_hyjal::instance_mount_hyjal_InstanceMapScript, instance_zulgurub::instance_zulgurub_InstanceMapScript, instance_zulaman::instance_zulaman_InstanceMapScript, instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript, instance_stratholme::instance_stratholme_InstanceMapScript, instance_scholomance::instance_scholomance_InstanceMapScript, instance_scarlet_monastery::instance_scarlet_monastery_InstanceMapScript, instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript, instance_karazhan::instance_karazhan_InstanceMapScript, instance_molten_core::instance_molten_core_InstanceMapScript, instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript, instance_blackrock_spire::instance_blackrock_spireMapScript, instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript, OutdoorPvP, InstanceScript, BattlefieldWG, instance_mechanar::instance_mechanar_InstanceMapScript, instance_ulduar::instance_ulduar_InstanceMapScript, instance_nexus::instance_nexus_InstanceMapScript, instance_gundrak::instance_gundrak_InstanceMapScript, instance_zulfarrak::instance_zulfarrak_InstanceMapScript, instance_razorfen_downs::instance_razorfen_downs_InstanceMapScript, instance_maraudon::instance_maraudon_InstanceMapScript, instance_dire_maul::instance_dire_maul_InstanceMapScript, instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript, instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript, instance_uldaman::instance_uldaman_InstanceMapScript, instance_sunken_temple::instance_sunken_temple_InstanceMapScript, instance_shadowfang_keep::instance_shadowfang_keep_InstanceMapScript, and instance_deadmines::instance_deadmines_InstanceMapScript.
Definition at line 38 of file ZoneScript.h.
 { }
Referenced by GameObject::AddToWorld().
OnGameObjectRemove()
virtual void ZoneScript::OnGameObjectRemove (GameObject *) inline virtual
Reimplemented in instance_naxxramas::instance_naxxramas_InstanceMapScript, instance_arcatraz::instance_arcatraz_InstanceMapScript, instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript, instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript, instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript, instance_black_temple::instance_black_temple_InstanceMapScript, instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript, instance_drak_tharon_keep::instance_drak_tharon_keep_InstanceScript, instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript, instance_azjol_nerub::instance_azjol_nerub_InstanceScript, instance_zulgurub::instance_zulgurub_InstanceMapScript, instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript, instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript, OutdoorPvP, InstanceScript, instance_mechanar::instance_mechanar_InstanceMapScript, instance_nexus::instance_nexus_InstanceMapScript, and instance_gundrak::instance_gundrak_InstanceMapScript.
Definition at line 39 of file ZoneScript.h.
 { }
Referenced by GameObject::RemoveFromWorld().
OnUnitDeath()
virtual void ZoneScript::OnUnitDeath (Unit *) inline virtual
Reimplemented in instance_mechanar::instance_mechanar_InstanceMapScript, instance_blood_furnace::instance_blood_furnace_InstanceMapScript, instance_ulduar::instance_ulduar_InstanceMapScript, instance_oculus::instance_oculus_InstanceMapScript, instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript, instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript, instance_zulfarrak::instance_zulfarrak_InstanceMapScript, instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript, instance_sunken_temple::instance_sunken_temple_InstanceMapScript, instance_stratholme::instance_stratholme_InstanceMapScript, instance_karazhan::instance_karazhan_InstanceMapScript, instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript, instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript, BattlefieldWG, and instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript.
Definition at line 41 of file ZoneScript.h.
 { }
ProcessEvent()
virtual void ZoneScript::ProcessEvent (WorldObject * , uint32) inline virtual
Reimplemented in instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript, BattlefieldWG, instance_ulduar::instance_ulduar_InstanceMapScript, instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript, and instance_blackrock_spire::instance_blackrock_spireMapScript.
Definition at line 54 of file ZoneScript.h.
 {}
Referenced by GameObject::EventInform().
SetData()
virtual void ZoneScript::SetData (uint32 , uint32) inline virtual
Reimplemented in instance_halls_of_lightning::instance_halls_of_lightning_InstanceMapScript, instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript, instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript, instance_gruuls_lair::instance_gruuls_lair_InstanceMapScript, instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript, instance_nexus::instance_nexus_InstanceMapScript, instance_gundrak::instance_gundrak_InstanceMapScript, instance_the_black_morass::instance_the_black_morass_InstanceMapScript, instance_shadow_labyrinth::instance_shadow_labyrinth_InstanceMapScript, instance_arcatraz::instance_arcatraz_InstanceMapScript, instance_shattered_halls::instance_shattered_halls_InstanceMapScript, instance_magtheridons_lair::instance_magtheridons_lair_InstanceMapScript, instance_blood_furnace::instance_blood_furnace_InstanceMapScript, instance_steam_vault::instance_steam_vault_InstanceMapScript, instance_sethekk_halls::instance_sethekk_halls_InstanceMapScript, instance_violet_hold::instance_violet_hold_InstanceMapScript, instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript, instance_utgarde_pinnacle::instance_utgarde_pinnacle_InstanceMapScript, instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript, instance_ulduar::instance_ulduar_InstanceMapScript, instance_halls_of_stone::instance_halls_of_stone_InstanceMapScript, instance_oculus::instance_oculus_InstanceMapScript, instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript, instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript, instance_pit_of_saron::instance_pit_of_saron_InstanceScript, instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript, instance_forge_of_souls::instance_forge_of_souls_InstanceScript, instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript, instance_ahnkahet::instance_ahnkahet_InstanceScript, instance_zulfarrak::instance_zulfarrak_InstanceMapScript, instance_wailing_caverns::instance_wailing_caverns_InstanceMapScript, instance_temple_of_ahnqiraj::instance_temple_of_ahnqiraj_InstanceMapScript, instance_razorfen_downs::instance_razorfen_downs_InstanceMapScript, instance_maraudon::instance_maraudon_InstanceMapScript, instance_dire_maul::instance_dire_maul_InstanceMapScript, instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript, instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript, instance_hyjal::instance_mount_hyjal_InstanceMapScript, instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript, instance_zulaman::instance_zulaman_InstanceMapScript, instance_uldaman::instance_uldaman_InstanceMapScript, instance_sunken_temple::instance_sunken_temple_InstanceMapScript, instance_stratholme::instance_stratholme_InstanceMapScript, instance_shadowfang_keep::instance_shadowfang_keep_InstanceMapScript, instance_scholomance::instance_scholomance_InstanceMapScript, instance_scarlet_monastery::instance_scarlet_monastery_InstanceMapScript, instance_karazhan::instance_karazhan_InstanceMapScript, instance_deadmines::instance_deadmines_InstanceMapScript, instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript, instance_blackrock_spire::instance_blackrock_spireMapScript, instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript, instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript, instance_naxxramas::instance_naxxramas_InstanceMapScript, and Battlefield.
Definition at line 52 of file ZoneScript.h.
 {}
Referenced by boss_freya::boss_freyaAI::boss_freyaAI(), boss_hodir::boss_hodirAI::boss_hodirAI(), boss_mimiron::boss_mimironAI::boss_mimironAI(), boss_thorim::boss_thorimAI::boss_thorimAI(), boss_prince_keleseth_icc::boss_prince_kelesethAI::DamageDealt(), boss_prince_taldaram_icc::boss_prince_taldaramAI::DamageDealt(), boss_prince_valanar_icc::boss_prince_valanarAI::DamageDealt(), npc_ball_of_flame::npc_ball_of_flameAI::DamageDealt(), npc_mograine::npc_mograineAI::DamageTaken(), boss_eye_of_cthun::eye_of_cthunAI::DamageTaken(), boss_eadric::boss_eadricAI::DamageTaken(), boss_paletress::boss_paletressAI::DamageTaken(), boss_grand_champion::boss_grand_championAI::DamageTaken(), brann_bronzebeard::brann_bronzebeardAI::DamageTaken(), boss_freya::boss_freyaAI::DamageTaken(), boss_hodir::boss_hodirAI::DamageTaken(), hyjal_trashAI::DamageTaken(), boss_thorim::boss_thorimAI::DamageTaken(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::DestroyDoor(), npc_hor_lich_king::npc_hor_lich_kingAI::DoAction(), boss_algalon_the_observer::boss_algalon_the_observerAI::DoAction(), boss_onyxia::boss_onyxiaAI::DoAction(), boss_black_knight::boss_black_knightAI::DoAction(), npc_icc_putricades_trap::npc_icc_putricades_trapAI::DoAction(), boss_volkhan::boss_volkhanAI::DoAction(), boss_sjonnir::boss_sjonnirAI::DoAction(), boss_skadi_grauf::boss_skadi_graufAI::DoAction(), boss_ichoron::boss_ichoronAI::DoAction(), npc_forest_frog::npc_forest_frogAI::DoSpawnRandom(), boss_nightbane::boss_nightbaneAI::EnterCombat(), boss_shade_of_aran::boss_aranAI::EnterCombat(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::EnterCombat(), boss_priestess_delrissa::boss_priestess_delrissaAI::EnterCombat(), boss_selin_fireheart::boss_selin_fireheartAI::EnterCombat(), boss_vexallus::boss_vexallusAI::EnterCombat(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::EnterCombat(), boss_akilzon::boss_akilzonAI::EnterCombat(), boss_halazzi::boss_halazziAI::EnterCombat(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::EnterCombat(), boss_janalai::boss_janalaiAI::EnterCombat(), boss_nalorakk::boss_nalorakkAI::EnterCombat(), boss_zuljin::boss_zuljinAI::EnterCombat(), boss_anetheron::boss_anetheronAI::EnterCombat(), boss_archimonde::boss_archimondeAI::EnterCombat(), boss_azgalor::boss_azgalorAI::EnterCombat(), boss_kazrogal::boss_kazrogalAI::EnterCombat(), boss_rage_winterchill::boss_rage_winterchillAI::EnterCombat(), boss_onyxia::boss_onyxiaAI::EnterCombat(), boss_eye_of_cthun::eye_of_cthunAI::EnterCombat(), boss_eadric::boss_eadricAI::EnterCombat(), boss_paletress::boss_paletressAI::EnterCombat(), boss_anubarak_trial::boss_anubarak_trialAI::EnterCombat(), boss_faction_championsAI::EnterCombat(), boss_jaraxxus::boss_jaraxxusAI::EnterCombat(), boss_bronjahm::boss_bronjahmAI::EnterCombat(), boss_devourer_of_souls::boss_devourer_of_soulsAI::EnterCombat(), boss_frostsworn_general::boss_frostsworn_generalAI::EnterCombat(), boss_garfrost::boss_garfrostAI::EnterCombat(), boss_ick::boss_ickAI::EnterCombat(), boss_malygos::boss_malygosAI::EnterCombat(), boss_drakos::boss_drakosAI::EnterCombat(), boss_eregos::boss_eregosAI::EnterCombat(), boss_urom::boss_uromAI::EnterCombat(), boss_varos::boss_varosAI::EnterCombat(), boss_bjarngrim::boss_bjarngrimAI::EnterCombat(), boss_ionar::boss_ionarAI::EnterCombat(), boss_loken::boss_lokenAI::EnterCombat(), boss_volkhan::boss_volkhanAI::EnterCombat(), boss_krystallus::boss_krystallusAI::EnterCombat(), boss_maiden_of_grief::boss_maiden_of_griefAI::EnterCombat(), boss_sjonnir::boss_sjonnirAI::EnterCombat(), boss_algalon_the_observer::boss_algalon_the_observerAI::EnterCombat(), boss_auriaya::boss_auriayaAI::EnterCombat(), boss_flame_leviathan::boss_flame_leviathanAI::EnterCombat(), boss_freya::boss_freyaAI::EnterCombat(), boss_vezax::boss_vezaxAI::EnterCombat(), boss_hodir::boss_hodirAI::EnterCombat(), boss_kologarn::boss_kologarnAI::EnterCombat(), boss_mimiron::boss_mimironAI::EnterCombat(), boss_razorscale::boss_razorscaleAI::EnterCombat(), boss_thorim::boss_thorimAI::EnterCombat(), boss_xt002::boss_xt002AI::EnterCombat(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::EnterCombat(), boss_keleseth::boss_kelesethAI::EnterCombat(), npc_dragonflayer_forge_master::npc_dragonflayer_forge_masterAI::EnterCombat(), boss_palehoof::boss_palehoofAI::EnterCombat(), boss_skadi::boss_skadiAI::EnterCombat(), boss_svala::boss_svalaAI::EnterCombat(), boss_ymiron::boss_ymironAI::EnterCombat(), boss_archavon::boss_archavonAI::EnterCombat(), boss_emalon::boss_emalonAI::EnterCombat(), boss_koralon::boss_koralonAI::EnterCombat(), boss_toravon::boss_toravonAI::EnterCombat(), boss_ichoron::boss_ichoronAI::EnterCombat(), boss_zuramat::boss_zuramatAI::EnterCombat(), boss_ambassador_hellmaw::boss_ambassador_hellmawAI::EnterCombat(), boss_blackheart_the_inciter::boss_blackheart_the_inciterAI::EnterCombat(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::EnterCombat(), boss_murmur::boss_murmurAI::EnterCombat(), boss_hydromancer_thespia::boss_thespiaAI::EnterCombat(), boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI::EnterCombat(), boss_warlord_kalithresh::boss_warlord_kalithreshAI::EnterCombat(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::EnterCombat(), boss_the_maker::boss_the_makerAI::EnterCombat(), boss_prince_valanar_icc::boss_prince_valanarAI::EnterCombat(), boss_professor_putricide::boss_professor_putricideAI::EnterCombat(), boss_rotface::boss_rotfaceAI::EnterCombat(), boss_loatheb::boss_loathebAI::EnterCombat(), boss_steelbreaker::boss_steelbreakerAI::EnterCombat(), boss_skarvald_the_constructor::boss_skarvald_the_constructorAI::EnterCombat(), boss_dalronn_the_controller::boss_dalronn_the_controllerAI::EnterCombat(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::EnterEvadeMode(), boss_anubarak_trial::boss_anubarak_trialAI::EnterEvadeMode(), boss_faction_championsAI::EnterEvadeMode(), boss_jaraxxus::boss_jaraxxusAI::EnterEvadeMode(), boss_gormok::boss_gormokAI::EnterEvadeMode(), boss_jormungarAI::EnterEvadeMode(), boss_icehowl::boss_icehowlAI::EnterEvadeMode(), boss_twin_valkyrAI::EnterEvadeMode(), boss_frostsworn_general::boss_frostsworn_generalAI::EnterEvadeMode(), boss_cyanigosa::boss_cyanigosaAI::EnterEvadeMode(), boss_erekem::boss_erekemAI::EnterEvadeMode(), boss_ichoron::boss_ichoronAI::EnterEvadeMode(), boss_lavanthor::boss_lavanthorAI::EnterEvadeMode(), boss_moragg::boss_moraggAI::EnterEvadeMode(), boss_xevozz::boss_xevozzAI::EnterEvadeMode(), boss_zuramat::boss_zuramatAI::EnterEvadeMode(), go_troll_cage::go_troll_cageAI::GossipHello(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::GoToMinchar(), spell_thaddius_pos_neg_charge::spell_thaddius_pos_neg_charge_SpellScript::HandleDamage(), spell_temple_of_atal_hakkar_awaken_the_soulflayer::spell_temple_of_atal_hakkar_awaken_the_soulflayer_SpellScript::HandleSendEvent(), spell_uldaman_boss_agro_archaedas::spell_uldaman_boss_agro_archaedas_SpellScript::HandleSendEvent(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::InitFight(), npc_spinestalker::npc_spinestalkerAI::InitializeAI(), npc_rimefang::npc_rimefangAI::InitializeAI(), npc_sindragosa_trash::npc_sindragosa_trashAI::InitializeAI(), boss_lord_valthalak::boss_lord_valthalakAI::JustDied(), boss_solakar_flamewreath::boss_solakar_flamewreathAI::JustDied(), boss_razorgore::boss_razorgoreAI::JustDied(), boss_nightbane::boss_nightbaneAI::JustDied(), boss_shade_of_aran::boss_aranAI::JustDied(), boss_terestian_illhoof::boss_terestianAI::JustDied(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::JustDied(), boss_priestess_delrissa::boss_priestess_delrissaAI::JustDied(), boss_selin_fireheart::boss_selin_fireheartAI::JustDied(), boss_vexallus::boss_vexallusAI::JustDied(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::JustDied(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::JustDied(), boss_baroness_anastari::boss_baroness_anastariAI::JustDied(), boss_akilzon::boss_akilzonAI::JustDied(), boss_halazzi::boss_halazziAI::JustDied(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::JustDied(), boss_janalai::boss_janalaiAI::JustDied(), boss_nalorakk::boss_nalorakkAI::JustDied(), boss_zuljin::boss_zuljinAI::JustDied(), boss_archimonde::boss_archimondeAI::JustDied(), npc_frost_wyrm::npc_frost_wyrmAI::JustDied(), hyjal_trashAI::JustDied(), hyjalAI::JustDied(), npc_arthas::npc_arthasAI::JustDied(), boss_captain_skarloc::boss_captain_skarlocAI::JustDied(), boss_aeonus::boss_aeonusAI::JustDied(), boss_onyxia::boss_onyxiaAI::JustDied(), boss_kri::boss_kriAI::JustDied(), boss_vem::boss_vemAI::JustDied(), boss_yauj::boss_yaujAI::JustDied(), boss_cthun::cthunAI::JustDied(), npc_argent_soldier::npc_argent_soldierAI::JustDied(), boss_black_knight::boss_black_knightAI::JustDied(), npc_toc5_grand_champion_minion::npc_toc5_grand_champion_minionAI::JustDied(), boss_anubarak_trial::boss_anubarak_trialAI::JustDied(), boss_faction_championsAI::JustDied(), boss_jaraxxus::boss_jaraxxusAI::JustDied(), boss_gormok::boss_gormokAI::JustDied(), boss_jormungarAI::JustDied(), boss_icehowl::boss_icehowlAI::JustDied(), boss_twin_valkyrAI::JustDied(), boss_bronjahm::boss_bronjahmAI::JustDied(), boss_devourer_of_souls::boss_devourer_of_soulsAI::JustDied(), boss_falric::boss_falricAI::JustDied(), boss_marwyn::boss_marwynAI::JustDied(), boss_frostsworn_general::boss_frostsworn_generalAI::JustDied(), boss_garfrost::boss_garfrostAI::JustDied(), boss_ick::boss_ickAI::JustDied(), boss_tyrannus::boss_tyrannusAI::JustDied(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::JustDied(), boss_kelthuzad_minion::boss_kelthuzad_minionAI::JustDied(), boss_malygos::boss_malygosAI::JustDied(), boss_drakos::boss_drakosAI::JustDied(), boss_eregos::boss_eregosAI::JustDied(), boss_urom::boss_uromAI::JustDied(), boss_varos::boss_varosAI::JustDied(), boss_bjarngrim::boss_bjarngrimAI::JustDied(), boss_ionar::boss_ionarAI::JustDied(), boss_loken::boss_lokenAI::JustDied(), boss_volkhan::boss_volkhanAI::JustDied(), boss_krystallus::boss_krystallusAI::JustDied(), boss_maiden_of_grief::boss_maiden_of_griefAI::JustDied(), boss_sjonnir::boss_sjonnirAI::JustDied(), brann_bronzebeard::brann_bronzebeardAI::JustDied(), boss_steelbreaker::boss_steelbreakerAI::JustDied(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::JustDied(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::JustDied(), boss_auriaya::boss_auriayaAI::JustDied(), boss_vezax::boss_vezaxAI::JustDied(), boss_ignis::boss_ignisAI::JustDied(), boss_kologarn::boss_kologarnAI::JustDied(), boss_razorscale::boss_razorscaleAI::JustDied(), boss_xt002::boss_xt002AI::JustDied(), boss_yoggsaron::boss_yoggsaronAI::JustDied(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::JustDied(), boss_keleseth::boss_kelesethAI::JustDied(), boss_skarvald_the_constructor::boss_skarvald_the_constructorAI::JustDied(), boss_dalronn_the_controller::boss_dalronn_the_controllerAI::JustDied(), npc_dragonflayer_forge_master::npc_dragonflayer_forge_masterAI::JustDied(), boss_palehoof::boss_palehoofAI::JustDied(), boss_skadi::boss_skadiAI::JustDied(), boss_svala::boss_svalaAI::JustDied(), boss_ymiron::boss_ymironAI::JustDied(), boss_archavon::boss_archavonAI::JustDied(), boss_emalon::boss_emalonAI::JustDied(), boss_koralon::boss_koralonAI::JustDied(), boss_toravon::boss_toravonAI::JustDied(), boss_cyanigosa::boss_cyanigosaAI::JustDied(), boss_erekem::boss_erekemAI::JustDied(), boss_ichoron::boss_ichoronAI::JustDied(), boss_lavanthor::boss_lavanthorAI::JustDied(), boss_moragg::boss_moraggAI::JustDied(), boss_xevozz::boss_xevozzAI::JustDied(), boss_zuramat::boss_zuramatAI::JustDied(), npc_vh_void_sentry::npc_vh_void_sentryAI::JustDied(), npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::JustDied(), boss_ambassador_hellmaw::boss_ambassador_hellmawAI::JustDied(), boss_blackheart_the_inciter::boss_blackheart_the_inciterAI::JustDied(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::JustDied(), boss_murmur::boss_murmurAI::JustDied(), boss_hydromancer_thespia::boss_thespiaAI::JustDied(), boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI::JustDied(), boss_warlord_kalithresh::boss_warlord_kalithreshAI::JustDied(), boss_olm_the_summoner::boss_olm_the_summonerAI::JustDied(), boss_kiggler_the_crazed::boss_kiggler_the_crazedAI::JustDied(), boss_blindeye_the_seer::boss_blindeye_the_seerAI::JustDied(), boss_krosh_firehand::boss_krosh_firehandAI::JustDied(), boss_broggok::boss_broggokAI::JustDied(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::JustDied(), boss_the_maker::boss_the_makerAI::JustDied(), boss_anetheron::boss_anetheronAI::JustDied(), boss_azgalor::boss_azgalorAI::JustDied(), boss_kazrogal::boss_kazrogalAI::JustDied(), boss_rage_winterchill::boss_rage_winterchillAI::JustDied(), boss_epoch_hunter::boss_epoch_hunterAI::JustDied(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::JustDied(), boss_loatheb::boss_loathebAI::JustDied(), boss_high_inquisitor_whitemane::boss_high_inquisitor_whitemaneAI::JustReachedHome(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::JustReachedHome(), boss_flame_leviathan::boss_flame_leviathanAI::JustReachedHome(), npc_spinestalker::npc_spinestalkerAI::JustRespawned(), npc_rimefang::npc_rimefangAI::JustRespawned(), npc_sindragosa_trash::npc_sindragosa_trashAI::JustRespawned(), boss_paletress::boss_paletressAI::JustSummoned(), boss_faction_championsAI::KilledUnit(), boss_anubrekhan::boss_anubrekhanAI::KilledUnit(), boss_svala::boss_svalaAI::KilledUnit(), boss_faerlina::boss_faerlinaAI::KilledUnit(), boss_four_horsemen::boss_four_horsemenAI::KilledUnit(), boss_gluth::boss_gluthAI::KilledUnit(), boss_gothik::boss_gothikAI::KilledUnit(), npc_boss_gothik_minion::npc_boss_gothik_minionAI::KilledUnit(), boss_grobbulus::boss_grobbulusAI::KilledUnit(), boss_grobbulus_poison_cloud::boss_grobbulus_poison_cloudAI::KilledUnit(), boss_heigan::boss_heiganAI::KilledUnit(), boss_kelthuzad::boss_kelthuzadAI::KilledUnit(), boss_kelthuzad_minion::boss_kelthuzad_minionAI::KilledUnit(), boss_loatheb::boss_loathebAI::KilledUnit(), boss_maexxna::boss_maexxnaAI::KilledUnit(), boss_noth::boss_nothAI::KilledUnit(), boss_patchwerk::boss_patchwerkAI::KilledUnit(), boss_razuvious::boss_razuviousAI::KilledUnit(), boss_razuvious_minion::boss_razuvious_minionAI::KilledUnit(), boss_sapphiron::boss_sapphironAI::KilledUnit(), boss_thaddius::boss_thaddiusAI::KilledUnit(), boss_thaddius_summon::boss_thaddius_summonAI::KilledUnit(), npc_medivh_bm::npc_medivh_bmAI::MoveInLineOfSight(), boss_grand_champion::boss_grand_championAI::MovementInform(), boss_lady_vashj::boss_lady_vashjAI::MovementInform(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::MovementInform(), npc_hor_lich_king::npc_hor_lich_kingAI::MovementInform(), boss_skadi_grauf::boss_skadi_graufAI::MovementInform(), go_call_tram::OnGossipHello(), go_main_chambers_access_panel::OnGossipHello(), go_prince_taldaram_sphere::OnGossipHello(), go_harpoon_canon::OnGossipHello(), npc_ulduar_keeper::OnGossipSelect(), boss_doomrel::OnGossipSelect(), npc_zulaman_hostage::OnGossipSelect(), npc_announcer_toc5::OnGossipSelect(), npc_announcer_toc10::OnGossipSelect(), npc_hor_leader::OnGossipSelect(), npc_cos_chromie_middle::OnGossipSelect(), npc_rocknot::OnQuestReward(), at_icc_saurfang_portal::OnTrigger(), at_thaddius_entrance::OnTrigger(), at_hor_shadow_throne::OnTrigger(), at_tyrannus_event_starter::OnTrigger(), SmartScript::ProcessAction(), boss_razorgore::boss_razorgoreAI::Reset(), boss_nightbane::boss_nightbaneAI::Reset(), boss_shade_of_aran::boss_aranAI::Reset(), boss_terestian_illhoof::boss_terestianAI::Reset(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::Reset(), boss_priestess_delrissa::boss_priestess_delrissaAI::Reset(), boss_selin_fireheart::boss_selin_fireheartAI::Reset(), boss_vexallus::boss_vexallusAI::Reset(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::Reset(), boss_akilzon::boss_akilzonAI::Reset(), boss_halazzi::boss_halazziAI::Reset(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::Reset(), boss_janalai::boss_janalaiAI::Reset(), boss_nalorakk::boss_nalorakkAI::Reset(), boss_zuljin::boss_zuljinAI::Reset(), boss_anetheron::boss_anetheronAI::Reset(), boss_archimonde::boss_archimondeAI::Reset(), boss_azgalor::boss_azgalorAI::Reset(), boss_kazrogal::boss_kazrogalAI::Reset(), boss_rage_winterchill::boss_rage_winterchillAI::Reset(), hyjalAI::Reset(), npc_arthas::npc_arthasAI::Reset(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::Reset(), boss_onyxia::boss_onyxiaAI::Reset(), boss_eye_of_cthun::eye_of_cthunAI::Reset(), boss_cthun::cthunAI::Reset(), boss_eadric::boss_eadricAI::Reset(), boss_paletress::boss_paletressAI::Reset(), boss_black_knight::boss_black_knightAI::Reset(), boss_jaraxxus::boss_jaraxxusAI::Reset(), boss_bronjahm::boss_bronjahmAI::Reset(), boss_devourer_of_souls::boss_devourer_of_soulsAI::Reset(), boss_falric::boss_falricAI::Reset(), boss_marwyn::boss_marwynAI::Reset(), boss_garfrost::boss_garfrostAI::Reset(), boss_ick::boss_ickAI::Reset(), boss_lord_marrowgar::Reset(), npc_icc_putricades_trap::npc_icc_putricades_trapAI::Reset(), boss_loatheb::boss_loathebAI::Reset(), boss_malygos::boss_malygosAI::Reset(), boss_drakos::boss_drakosAI::Reset(), boss_eregos::boss_eregosAI::Reset(), boss_urom::boss_uromAI::Reset(), boss_varos::boss_varosAI::Reset(), boss_bjarngrim::boss_bjarngrimAI::Reset(), boss_ionar::boss_ionarAI::Reset(), boss_loken::boss_lokenAI::Reset(), boss_volkhan::boss_volkhanAI::Reset(), boss_krystallus::boss_krystallusAI::Reset(), boss_maiden_of_grief::boss_maiden_of_griefAI::Reset(), boss_sjonnir::boss_sjonnirAI::Reset(), brann_bronzebeard::brann_bronzebeardAI::Reset(), boss_algalon_the_observer::boss_algalon_the_observerAI::Reset(), boss_steelbreaker::boss_steelbreakerAI::Reset(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::Reset(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::Reset(), boss_auriaya::boss_auriayaAI::Reset(), boss_flame_leviathan::boss_flame_leviathanAI::Reset(), boss_freya::boss_freyaAI::Reset(), boss_vezax::boss_vezaxAI::Reset(), boss_hodir::boss_hodirAI::Reset(), boss_kologarn::boss_kologarnAI::Reset(), boss_mimiron::boss_mimironAI::Reset(), boss_razorscale::boss_razorscaleAI::Reset(), boss_thorim::boss_thorimAI::Reset(), boss_xt002::boss_xt002AI::Reset(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::Reset(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::Reset(), boss_keleseth::boss_kelesethAI::Reset(), boss_skarvald_the_constructor::boss_skarvald_the_constructorAI::Reset(), boss_dalronn_the_controller::boss_dalronn_the_controllerAI::Reset(), npc_dragonflayer_forge_master::npc_dragonflayer_forge_masterAI::Reset(), boss_palehoof::boss_palehoofAI::Reset(), boss_skadi::boss_skadiAI::Reset(), boss_svala::boss_svalaAI::Reset(), boss_ymiron::boss_ymironAI::Reset(), boss_archavon::boss_archavonAI::Reset(), boss_emalon::boss_emalonAI::Reset(), boss_koralon::boss_koralonAI::Reset(), boss_toravon::boss_toravonAI::Reset(), boss_ambassador_hellmaw::boss_ambassador_hellmawAI::Reset(), boss_blackheart_the_inciter::boss_blackheart_the_inciterAI::Reset(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::Reset(), boss_murmur::boss_murmurAI::Reset(), boss_hydromancer_thespia::boss_thespiaAI::Reset(), boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI::Reset(), boss_warlord_kalithresh::boss_warlord_kalithreshAI::Reset(), boss_broggok::boss_broggokAI::Reset(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::Reset(), boss_the_maker::boss_the_makerAI::Reset(), hyjalAI::Retreat(), boss_svala::boss_svalaAI::SetData(), boss_garfrost::boss_garfrostAI::SetData(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::SetData(), npc_mograine::npc_mograineAI::SpellHit(), npc_harrison_jones::npc_harrison_jonesAI::SpellHit(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::SpellHit(), boss_faerlina::boss_faerlinaAI::SpellHit(), boss_ymiron::boss_ymironAI::SpellHitTarget(), boss_onyxia::boss_onyxiaAI::SpellHitTarget(), npc_black_knight_ghoul::npc_black_knight_ghoulAI::SpellHitTarget(), npc_pos_collapsing_icicle::npc_pos_collapsing_icicleAI::SpellHitTarget(), npc_barnes::npc_barnesAI::StartEvent(), SummonCroneIfReady(), boss_priestess_delrissa::boss_priestess_delrissaAI::SummonedCreatureDies(), boss_loatheb::boss_loathebAI::SummonedCreatureDies(), hyjalAI::SummonNextWave(), npc_rocknot::npc_rocknotAI::UpdateAI(), boss_solakar_flamewreath::boss_solakar_flamewreathAI::UpdateAI(), npc_harrison_jones::npc_harrison_jonesAI::UpdateAI(), boss_thekal::boss_thekalAI::UpdateAI(), npc_arthas::npc_arthasAI::UpdateAI(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::UpdateAI(), npc_time_rift::npc_time_riftAI::UpdateAI(), npc_belnistrasz::npc_belnistraszAI::UpdateAI(), boss_eye_of_cthun::eye_of_cthunAI::UpdateAI(), boss_cthun::cthunAI::UpdateAI(), npc_weegli_blastfuse::npc_weegli_blastfuseAI::UpdateAI(), npc_hor_leader::npc_hor_leaderAI::UpdateAI(), boss_frostsworn_general::boss_frostsworn_generalAI::UpdateAI(), npc_hor_lich_king::npc_hor_lich_kingAI::UpdateAI(), npc_hor_leader_second::npc_hor_leader_secondAI::UpdateAI(), boss_krick::boss_krickAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), npc_icc_putricades_trap::npc_icc_putricades_trapAI::UpdateAI(), boss_heigan::boss_heiganAI::UpdateAI(), boss_sapphiron::boss_sapphironAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), boss_loken::boss_lokenAI::UpdateAI(), boss_algalon_the_observer::boss_algalon_the_observerAI::UpdateAI(), boss_hodir::boss_hodirAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), boss_thorim::boss_thorimAI::UpdateAI(), boss_skadi_grauf::boss_skadi_graufAI::UpdateAI(), npc_azure_saboteur::npc_azure_saboteurAI::UpdateAI(), boss_magtheridon::boss_magtheridonAI::UpdateAI(), npc_warden_mellichar::npc_warden_mellicharAI::UpdateAI(), brann_bronzebeard::brann_bronzebeardAI::UpdateEscortAI(), boss_grand_champion::boss_grand_championAI::WaypointReached(), npc_arthas::npc_arthasAI::WaypointReached(), npc_grimstone::npc_grimstoneAI::WaypointReached(), and npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::WaypointReached().
SetData64()
virtual void ZoneScript::SetData64 (uint32 , uint64) inline virtual
Reimplemented in Battlefield.
Definition at line 48 of file ZoneScript.h.
 {}
SetGuidData()
virtual void ZoneScript::SetGuidData (uint32 , ObjectGuid) inline virtual
Reimplemented in instance_violet_hold::instance_violet_hold_InstanceMapScript, instance_pit_of_saron::instance_pit_of_saron_InstanceScript, instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript, instance_the_black_morass::instance_the_black_morass_InstanceMapScript, instance_karazhan::instance_karazhan_InstanceMapScript, and instance_the_slave_pens::instance_the_slave_pens_InstanceMapScript.
Definition at line 45 of file ZoneScript.h.
 {}
Referenced by npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI::InitializeAI(), boss_ichoron::boss_ichoronAI::JustSummoned(), boss_xevozz::boss_xevozzAI::JustSummoned(), boss_zuramat::boss_zuramatAI::JustSummoned(), npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::JustSummoned(), npc_medivh_bm::npc_medivh_bmAI::JustSummoned(), npc_vh_void_sentry::npc_vh_void_sentryAI::npc_vh_void_sentryAI(), SmartScript::ProcessAction(), npc_image_of_medivh::npc_image_of_medivhAI::Reset(), boss_tyrannus::boss_tyrannusAI::Reset(), boss_ichoron::boss_ichoronAI::SummonedCreatureDespawn(), boss_xevozz::boss_xevozzAI::SummonedCreatureDespawn(), boss_zuramat::boss_zuramatAI::SummonedCreatureDespawn(), npc_vh_void_sentry::npc_vh_void_sentryAI::SummonedCreatureDespawn(), npc_medivh_bm::npc_medivh_bmAI::SummonedCreatureDespawn(), npc_vh_teleportation_portal::npc_vh_teleportation_portalAI::SummonedMobDied(), and boss_ayamiss::boss_ayamissAI::UpdateAI().
The documentation for this class was generated from the following file:
src/server/game/Maps/ZoneScript.h