Azerotcore-wotlk: OrcMoveEvent Class Reference
OrcMoveEvent Class Reference
Public Member Functions
OrcMoveEvent (Creature *me)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()
virtual ~BasicEvent ()
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Creature * _me
Detailed Description
Definition at line 57 of file boss_the_beast.cpp.
Constructor & Destructor Documentation
OrcMoveEvent()
OrcMoveEvent::OrcMoveEvent (Creature * me) inline
Definition at line 60 of file boss_the_beast.cpp.
 : _me(me) {}
Member Function Documentation
Execute()
bool OrcMoveEvent::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
Definition at line 62 of file boss_the_beast.cpp.
     {
         _me->SetReactState(REACT_PASSIVE);
         Position movePos = _me->GetRandomPoint(OrcsRunawayPosition, 10.0f);
         _me->GetMotionMaster()->MovePoint(1, movePos);
         return true;
     }
References _me, Unit::GetMotionMaster(), WorldObject::GetRandomPoint(), MotionMaster::MovePoint(), OrcsRunawayPosition, REACT_PASSIVE, and Creature::SetReactState().
Member Data Documentation
_me
Creature* OrcMoveEvent::_me private
Definition at line 71 of file boss_the_beast.cpp.
Referenced by Execute().
The documentation for this class was generated from the following file:
src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/boss_the_beast.cpp