Azerotcore-wotlk: Acore::MessageDistDelivererToHostile Struct Reference
Acore::MessageDistDelivererToHostile Struct Reference
#include <GridNotifiers.h>
Public Member Functions
MessageDistDelivererToHostile (Unit *src, WorldPacket *msg, float dist)
void Visit (PlayerMapType &m)
void Visit (CreatureMapType &m)
void Visit (DynamicObjectMapType &m)
template<class SKIP >
void Visit (GridRefMgr< SKIP > &)
void SendPacket (Player *player)
Public Attributes
Unit * i_source
WorldPacket * i_message
uint32 i_phaseMask
float i_distSq
Detailed Description
Definition at line 129 of file GridNotifiers.h.
Constructor & Destructor Documentation
MessageDistDelivererToHostile()
Acore::MessageDistDelivererToHostile::MessageDistDelivererToHostile (Unit * src, WorldPacket * msg, float dist) inline
Definition at line 135 of file GridNotifiers.h.
             : i_source(src), i_message(msg), i_phaseMask(src->GetPhaseMask()), i_distSq(dist * dist)
         {
         }
Member Function Documentation
SendPacket()
void Acore::MessageDistDelivererToHostile::SendPacket (Player * player) inline
Definition at line 144 of file GridNotifiers.h.
         {
             // never send packet to self
             if (player == i_source || !player->HaveAtClient(i_source) || player->IsFriendlyTo(i_source))
                 return;
             player->GetSession()->SendPacket(i_message);
         }
References Player::GetSession(), Player::HaveAtClient(), i_message, i_source, Unit::IsFriendlyTo(), and WorldSession::SendPacket().
Referenced by Visit().
Visit() [1/4]
void MessageDistDelivererToHostile::Visit (CreatureMapType & m)
Definition at line 304 of file GridNotifiers.cpp.
 {
     for (CreatureMapType::iterator iter = m.begin(); iter != m.end(); ++iter)
     {
         Creature* target = iter->GetSource();
         if (!target->HasSharedVision() || !target->InSamePhase(i_phaseMask))
             continue;
         if (target->GetExactDist2dSq(i_source) > i_distSq)
             continue;
         // Send packet to all who are sharing the creature's vision
         SharedVisionList::const_iterator i = target->GetSharedVisionList().begin();
         for (; i != target->GetSharedVisionList().end(); ++i)
             if ((*i)->m_seer == target)
                 SendPacket(*i);
     }
 }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), Position::GetExactDist2dSq(), Unit::GetSharedVisionList(), Unit::HasSharedVision(), i_distSq, i_phaseMask, i_source, WorldObject::InSamePhase(), and SendPacket().
Visit() [2/4]
void MessageDistDelivererToHostile::Visit (DynamicObjectMapType & m)
Definition at line 323 of file GridNotifiers.cpp.
 {
     for (DynamicObjectMapType::iterator iter = m.begin(); iter != m.end(); ++iter)
     {
         DynamicObject* target = iter->GetSource();
         if (!target->GetCasterGUID().IsPlayer() || !target->InSamePhase(i_phaseMask))
             continue;
         if (target->GetExactDist2dSq(i_source) > i_distSq)
             continue;
         // Send packet back to the caster if the caster has vision of dynamic object
         Player* caster = (Player*)target->GetCaster();
         if (caster && caster->m_seer == target)
             SendPacket(caster);
     }
 }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), DynamicObject::GetCaster(), DynamicObject::GetCasterGUID(), Position::GetExactDist2dSq(), i_distSq, i_phaseMask, i_source, WorldObject::InSamePhase(), ObjectGuid::IsPlayer(), Player::m_seer, and SendPacket().
Visit() [3/4]
template<class SKIP > void Acore::MessageDistDelivererToHostile::Visit (GridRefMgr< SKIP > &) inline
Definition at line 142 of file GridNotifiers.h.
 {}
Visit() [4/4]
void MessageDistDelivererToHostile::Visit (PlayerMapType & m)
Definition at line 279 of file GridNotifiers.cpp.
 {
     for (PlayerMapType::iterator iter = m.begin(); iter != m.end(); ++iter)
     {
         Player* target = iter->GetSource();
         if (!target->InSamePhase(i_phaseMask))
             continue;
         if (target->GetExactDist2dSq(i_source) > i_distSq)
             continue;
         // Send packet to all who are sharing the player's vision
         if (target->HasSharedVision())
         {
             SharedVisionList::const_iterator i = target->GetSharedVisionList().begin();
             for (; i != target->GetSharedVisionList().end(); ++i)
                 if ((*i)->m_seer == target)
                     SendPacket(*i);
         }
         if (target->m_seer == target || target->GetVehicle())
             SendPacket(target);
     }
 }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), Position::GetExactDist2dSq(), Unit::GetSharedVisionList(), Unit::GetVehicle(), Unit::HasSharedVision(), i_distSq, i_phaseMask, i_source, WorldObject::InSamePhase(), Player::m_seer, and SendPacket().
Member Data Documentation
i_distSq
float Acore::MessageDistDelivererToHostile::i_distSq
Definition at line 134 of file GridNotifiers.h.
Referenced by Visit().
i_message
WorldPacket* Acore::MessageDistDelivererToHostile::i_message
Definition at line 132 of file GridNotifiers.h.
Referenced by SendPacket().
i_phaseMask
uint32 Acore::MessageDistDelivererToHostile::i_phaseMask
Definition at line 133 of file GridNotifiers.h.
Referenced by Visit().
i_source
Unit* Acore::MessageDistDelivererToHostile::i_source
Definition at line 131 of file GridNotifiers.h.
Referenced by SendPacket(), and Visit().
The documentation for this struct was generated from the following files:
src/server/game/Grids/Notifiers/GridNotifiers.h
src/server/game/Grids/Notifiers/GridNotifiers.cpp