Azerotcore-wotlk: boss_gal_darah::boss_gal_darahAI Struct Reference
boss_gal_darah::boss_gal_darahAI Struct Reference
Public Member Functions
boss_gal_darahAI (Creature *creature)
void Reset () override
void InitializeAI () override
void JustReachedHome () override
void ScheduleEvents (bool troll)
void EnterCombat (Unit *who) override
void JustSummoned (Creature *summon) override
uint32 GetData (uint32) const override
void JustDied (Unit *killer) override
void KilledUnit (Unit *) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void DoAction (int32)
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
uint8 phaseCounter
GuidSet impaledList
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 69 of file boss_gal_darah.cpp.
Constructor & Destructor Documentation
boss_gal_darahAI()
boss_gal_darah::boss_gal_darahAI::boss_gal_darahAI (Creature * creature) inline
Definition at line 71 of file boss_gal_darah.cpp.
                                              : BossAI(creature, DATA_GAL_DARAH)
         {
         }
Member Function Documentation
EnterCombat()
void boss_gal_darah::boss_gal_darahAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from BossAI.
Definition at line 114 of file boss_gal_darah.cpp.
         {
             Talk(SAY_AGGRO);
             BossAI::EnterCombat(who);
             ScheduleEvents(true);
             me->RemoveAurasDueToSpell(SPELL_START_VISUAL);
             me->InterruptNonMeleeSpells(true);
         }
References BossAI::EnterCombat(), Unit::InterruptNonMeleeSpells(), ScriptedAI::me, Unit::RemoveAurasDueToSpell(), SAY_AGGRO, ScheduleEvents(), SPELL_START_VISUAL, and CreatureAI::Talk().
GetData()
uint32 boss_gal_darah::boss_gal_darahAI::GetData (uint32) const inline override virtual
Reimplemented from UnitAI.
Definition at line 136 of file boss_gal_darah.cpp.
         {
             return impaledList.size();
         }
References impaledList.
InitializeAI()
void boss_gal_darah::boss_gal_darahAI::InitializeAI () inline override virtual
Reimplemented from UnitAI.
Definition at line 85 of file boss_gal_darah.cpp.
         {
             BossAI::InitializeAI();
             me->CastSpell(me, SPELL_START_VISUAL, false);
         }
References Unit::CastSpell(), UnitAI::InitializeAI(), ScriptedAI::me, and SPELL_START_VISUAL.
JustDied()
void boss_gal_darah::boss_gal_darahAI::JustDied (Unit * killer) inline override virtual
Reimplemented from BossAI.
Definition at line 141 of file boss_gal_darah.cpp.
         {
             Talk(SAY_DEATH);
             BossAI::JustDied(killer);
         }
References BossAI::JustDied(), SAY_DEATH, and CreatureAI::Talk().
JustReachedHome()
void boss_gal_darah::boss_gal_darahAI::JustReachedHome () inline override virtual
Reimplemented from BossAI.
Definition at line 91 of file boss_gal_darah.cpp.
         {
             BossAI::JustReachedHome();
             me->CastSpell(me, SPELL_START_VISUAL, false);
         }
References Unit::CastSpell(), BossAI::JustReachedHome(), ScriptedAI::me, and SPELL_START_VISUAL.
JustSummoned()
void boss_gal_darah::boss_gal_darahAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
Definition at line 124 of file boss_gal_darah.cpp.
         {
             uint32 despawnTime = 0;
             if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 60.0f, true))
             {
                 summon->CastSpell(target, SPELL_STAMPEDE_DMG, true);
                 despawnTime = (summon->GetDistance(target) / 40.0f * 1000) + 500;
             }
             summon->DespawnOrUnsummon(despawnTime);
         }
References Unit::CastSpell(), Creature::DespawnOrUnsummon(), WorldObject::GetDistance(), SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), and SPELL_STAMPEDE_DMG.
KilledUnit()
void boss_gal_darah::boss_gal_darahAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 147 of file boss_gal_darah.cpp.
         {
             if (events.GetNextEventTime(EVENT_KILL_TALK) == 0)
             {
                 Talk(SAY_SLAY);
                 events.ScheduleEvent(EVENT_KILL_TALK, 6000);
             }
         }
References EVENT_KILL_TALK, SAY_SLAY, and CreatureAI::Talk().
Reset()
void boss_gal_darah::boss_gal_darahAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 78 of file boss_gal_darah.cpp.
         {
             BossAI::Reset();
             impaledList.clear();
             phaseCounter = 0;
         }
References impaledList, phaseCounter, and BossAI::Reset().
ScheduleEvents()
void boss_gal_darah::boss_gal_darahAI::ScheduleEvents (bool troll) inline
Definition at line 97 of file boss_gal_darah.cpp.
         {
             events.Reset();
             if (troll)
             {
                 events.RescheduleEvent(EVENT_STAMPEDE, 10000);
                 events.RescheduleEvent(EVENT_WHIRLING_SLASH, 21000);
             }
             else
             {
                 events.RescheduleEvent(EVENT_PUNCTURE, 10000);
                 events.RescheduleEvent(EVENT_ENRAGE, 15000);
                 events.RescheduleEvent(EVENT_IMPALING_CHARGE, 21000);
                 events.RescheduleEvent(EVENT_STOMP, 5000);
             }
         }
References EVENT_ENRAGE, EVENT_IMPALING_CHARGE, EVENT_PUNCTURE, EVENT_STAMPEDE, EVENT_STOMP, and EVENT_WHIRLING_SLASH.
Referenced by EnterCombat(), and UpdateAI().
UpdateAI()
void boss_gal_darah::boss_gal_darahAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 156 of file boss_gal_darah.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING | UNIT_STATE_CHARGING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_STAMPEDE:
                     Talk(SAY_SUMMON_RHINO);
                     me->CastSpell(me->GetVictim(), SPELL_STAMPEDE, false);
                     events.ScheduleEvent(EVENT_STAMPEDE, 15000);
                     break;
                 case EVENT_WHIRLING_SLASH:
                     if (++phaseCounter >= 3)
                     {
                         ScheduleEvents(false);
                         me->CastSpell(me, SPELL_TRANSFORM_TO_RHINO, false);
                         Talk(SAY_TRANSFORM_1);
                         phaseCounter = 0;
                         return;
                     }
                     events.ScheduleEvent(EVENT_WHIRLING_SLASH, 21000);
                     me->CastSpell(me, SPELL_WHIRLING_SLASH, false);
                     break;
                 case EVENT_PUNCTURE:
                     me->CastSpell(me->GetVictim(), SPELL_PUNCTURE, false);
                     events.ScheduleEvent(EVENT_PUNCTURE, 8000);
                     break;
                 case EVENT_ENRAGE:
                     me->CastSpell(me, SPELL_ENRAGE, false);
                     events.ScheduleEvent(EVENT_ENRAGE, 20000);
                     break;
                 case EVENT_STOMP:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 30.0f, true))
                         me->CastSpell(target, SPELL_STOMP, false);
                     events.ScheduleEvent(EVENT_STOMP, 20000);
                     break;
                 case EVENT_IMPALING_CHARGE:
                     if (++phaseCounter >= 3)
                     {
                         ScheduleEvents(true);
                         me->CastSpell(me, SPELL_TRANSFORM_TO_TROLL, false);
                         Talk(SAY_TRANSFORM_2);
                         phaseCounter = 0;
                         return;
                     }
                     events.ScheduleEvent(EVENT_IMPALING_CHARGE, 21000);
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 1, 100.0f, true))
                     {
                         me->CastSpell(target, SPELL_IMPALING_CHARGE, false);
                         impaledList.insert(target->GetGUID());
                     }
                     break;
             }
             DoMeleeAttackIfReady();
         }
References Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), EVENT_ENRAGE, EVENT_IMPALING_CHARGE, EVENT_PUNCTURE, EVENT_STAMPEDE, EVENT_STOMP, EVENT_WHIRLING_SLASH, Unit::GetVictim(), Unit::HasUnitState(), impaledList, ScriptedAI::me, phaseCounter, SAY_SUMMON_RHINO, SAY_TRANSFORM_1, SAY_TRANSFORM_2, ScheduleEvents(), SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), SPELL_ENRAGE, SPELL_IMPALING_CHARGE, SPELL_PUNCTURE, SPELL_STAMPEDE, SPELL_STOMP, SPELL_TRANSFORM_TO_RHINO, SPELL_TRANSFORM_TO_TROLL, SPELL_WHIRLING_SLASH, CreatureAI::Talk(), UNIT_STATE_CASTING, UNIT_STATE_CHARGING, and CreatureAI::UpdateVictim().
Member Data Documentation
impaledList
GuidSet boss_gal_darah::boss_gal_darahAI::impaledList
Definition at line 76 of file boss_gal_darah.cpp.
Referenced by GetData(), Reset(), and UpdateAI().
phaseCounter
uint8 boss_gal_darah::boss_gal_darahAI::phaseCounter
Definition at line 75 of file boss_gal_darah.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Gundrak/boss_gal_darah.cpp