Azerotcore-wotlk: Acore::MostHPMissingGroupInRange Class Reference
Acore::MostHPMissingGroupInRange Class Reference
#include <GridNotifiers.h>
Public Member Functions
MostHPMissingGroupInRange (Unit const *obj, float range, uint32 hp)
bool operator() (Unit *u)
Private Attributes
Unit const * i_obj
float i_range
uint32 i_hp
Detailed Description
Definition at line 1358 of file GridNotifiers.h.
Constructor & Destructor Documentation
MostHPMissingGroupInRange()
Acore::MostHPMissingGroupInRange::MostHPMissingGroupInRange (Unit const * obj, float range, uint32 hp) inline
Definition at line 1361 of file GridNotifiers.h.
 : i_obj(obj), i_range(range), i_hp(hp) {}
Member Function Documentation
operator()()
bool Acore::MostHPMissingGroupInRange::operator() (Unit * u) inline
Definition at line 1363 of file GridNotifiers.h.
         {
             if (i_obj == u)
             {
                 return false;
             }
             Player* player = nullptr;
             if (u->GetTypeId() == TYPEID_PLAYER)
             {
                 player = u->ToPlayer();
             }
             else if (u->IsPet() && u->GetOwner())
             {
                 player = u->GetOwner()->ToPlayer();
             }
             if (!player)
             {
                 return false;
             }
             Group* group = player->GetGroup();
             if (!group || !group->IsMember(i_obj->IsPet() ? i_obj->GetOwnerGUID() : i_obj->GetGUID()))
             {
                 return false;
             }
             if (u->IsAlive() && !i_obj->IsHostileTo(u) && i_obj->IsWithinDistInMap(u, i_range) && u->GetMaxHealth() - u->GetHealth() > i_hp)
             {
                 i_hp = u->GetMaxHealth() - u->GetHealth();
                 return true;
             }
             return false;
         }
References Player::GetGroup(), Object::GetGUID(), Unit::GetHealth(), Unit::GetMaxHealth(), Unit::GetOwner(), Unit::GetOwnerGUID(), Object::GetTypeId(), i_hp, i_obj, i_range, Unit::IsAlive(), Unit::IsHostileTo(), Group::IsMember(), Unit::IsPet(), WorldObject::IsWithinDistInMap(), Object::ToPlayer(), and TYPEID_PLAYER.
Member Data Documentation
i_hp
uint32 Acore::MostHPMissingGroupInRange::i_hp private
Definition at line 1404 of file GridNotifiers.h.
Referenced by operator()().
i_obj
Unit const* Acore::MostHPMissingGroupInRange::i_obj private
Definition at line 1402 of file GridNotifiers.h.
Referenced by operator()().
i_range
float Acore::MostHPMissingGroupInRange::i_range private
Definition at line 1403 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/game/Grids/Notifiers/GridNotifiers.h