Azerotcore-wotlk: G3D::PhysicsFrame Class Reference
G3D::PhysicsFrame Class Reference
#include <PhysicsFrame.h>
Public Member Functions
PhysicsFrame ()
PhysicsFrame (const Vector3 &translation)
PhysicsFrame (const Quat &rot, const Vector3 &translation)
PhysicsFrame (const Matrix3 &rot, const Vector3 &translation)
PhysicsFrame (const Matrix3 &rot)
PhysicsFrame (const CoordinateFrame &coordinateFrame)
PhysicsFrame & operator= (const PhysicsFrame &p)
PhysicsFrame (const class Any &any)
Any toAny () const
PhysicsFrame operator* (const PhysicsFrame &other) const
virtual ~PhysicsFrame ()
PhysicsFrame lerp (const PhysicsFrame &other, float alpha) const
void deserialize (class BinaryInput &b)
void serialize (class BinaryOutput &b) const
operator CFrame () const
PhysicsFrame & operator*= (float f)
PhysicsFrame operator* (float f) const
PhysicsFrame operator+ (const PhysicsFrame &f) const
PhysicsFrame & operator+= (const PhysicsFrame &f)
bool operator== (const PhysicsFrame &other) const
bool operator!= (const PhysicsFrame &other) const
Public Attributes
Quat rotation
Point3 translation
Detailed Description
An RT transformation using a quaternion; suitable for physics integration.
This interface is in "Beta" and will change in the next release.
Definition at line 30 of file PhysicsFrame.h.
Constructor & Destructor Documentation
PhysicsFrame() [1/7]
G3D::PhysicsFrame::PhysicsFrame ()
Initializes to the identity frame.
Definition at line 20 of file PhysicsFrame.cpp.
{
     translation = Vector3::zero();
     rotation    = Quat();
 }
References rotation, translation, and G3D::Vector3::zero().
Referenced by operator*(), and operator+().
PhysicsFrame() [2/7]
G3D::PhysicsFrame::PhysicsFrame (const Vector3 & translation) inline
Purely translational.
Definition at line 48 of file PhysicsFrame.h.
 : translation(translation) {}
PhysicsFrame() [3/7]
G3D::PhysicsFrame::PhysicsFrame (const Quat & rot, const Vector3 & translation) inline
Definition at line 49 of file PhysicsFrame.h.
 : rotation(rot), translation(translation) {}
PhysicsFrame() [4/7]
G3D::PhysicsFrame::PhysicsFrame (const Matrix3 & rot, const Vector3 & translation) inline
Definition at line 50 of file PhysicsFrame.h.
 : rotation(rot), translation(translation) {}
PhysicsFrame() [5/7]
G3D::PhysicsFrame::PhysicsFrame (const Matrix3 & rot) inline
Definition at line 51 of file PhysicsFrame.h.
 : rotation(rot), translation(Vector3::zero()) {}
PhysicsFrame() [6/7]
G3D::PhysicsFrame::PhysicsFrame (const CoordinateFrame & coordinateFrame)
Definition at line 26 of file PhysicsFrame.cpp.
{
     translation = coordinateFrame.translation;
     rotation    = Quat(coordinateFrame.rotation);
 }
References G3D::CoordinateFrame::rotation, rotation, G3D::CoordinateFrame::translation, and translation.
PhysicsFrame() [7/7]
G3D::PhysicsFrame::PhysicsFrame (const class Any & any)
PhysicsFrame([quat], [vec3])
Vector3(...)
CFrame(...)
CFrame::from...(...)
~PhysicsFrame()
virtual G3D::PhysicsFrame::~PhysicsFrame () inline virtual
Definition at line 74 of file PhysicsFrame.h.
 {}
Member Function Documentation
deserialize()
void G3D::PhysicsFrame::deserialize (class BinaryInput & b)
Definition at line 113 of file PhysicsFrame.cpp.
{
     translation.deserialize(b);
     rotation.deserialize(b);
 }
References b, G3D::Quat::deserialize(), G3D::Vector3::deserialize(), rotation, and translation.
lerp()
PhysicsFrame G3D::PhysicsFrame::lerp (const PhysicsFrame & other, float alpha) const
Linear interpolation (spherical linear for the rotations).
Definition at line 100 of file PhysicsFrame.cpp.
{
     PhysicsFrame result;
     result.translation = translation.lerp(other.translation, alpha);
     result.rotation    = rotation.slerp(other.rotation, alpha);
     return result;
 }
References G3D::Vector3::lerp(), rotation, G3D::Quat::slerp(), and translation.
operator CFrame()
G3D::PhysicsFrame::operator CFrame () const
operator!=()
bool G3D::PhysicsFrame::operator!= (const PhysicsFrame & other) const inline
Definition at line 118 of file PhysicsFrame.h.
{
         return ! ((*this) == other);
     }
operator*() [1/2]
PhysicsFrame G3D::PhysicsFrame::operator* (const PhysicsFrame & other) const
Compose: create the transformation that is other followed by this.
Definition at line 80 of file PhysicsFrame.cpp.
{
     PhysicsFrame result;
     result.rotation = rotation * other.rotation;
     result.translation = translation + rotation.toRotationMatrix() * other.translation;
     return result;
 }
References rotation, G3D::Quat::toRotationMatrix(), and translation.
operator*() [2/2]
PhysicsFrame G3D::PhysicsFrame::operator* (float f) const inline
Multiplies both pieces by f; note that this will result in a non-unit quaternion that needs to be normalized
Definition at line 99 of file PhysicsFrame.h.
{
         return PhysicsFrame(rotation * f, translation * f);
     }
References f(), PhysicsFrame(), rotation, and translation.
operator*=()
PhysicsFrame& G3D::PhysicsFrame::operator*= (float f) inline
Multiplies both pieces by f; note that this will result in a non-unit quaternion that needs to be normalized
Definition at line 91 of file PhysicsFrame.h.
{
         rotation *= f;
         translation *= f;
         return *this;
     }
References f(), rotation, and translation.
operator+()
PhysicsFrame G3D::PhysicsFrame::operator+ (const PhysicsFrame & f) const inline
Definition at line 103 of file PhysicsFrame.h.
{
         return PhysicsFrame(rotation + f.rotation, translation + f.translation);
     }
References f(), PhysicsFrame(), rotation, and translation.
operator+=()
PhysicsFrame& G3D::PhysicsFrame::operator+= (const PhysicsFrame & f) inline
Definition at line 107 of file PhysicsFrame.h.
{
         rotation += f.rotation;
         translation += f.translation;
         return *this;
     }
References f(), rotation, and translation.
operator=()
PhysicsFrame& G3D::PhysicsFrame::operator= (const PhysicsFrame & p) inline
Definition at line 54 of file PhysicsFrame.h.
{
         rotation = p.rotation;
         translation = p.translation;
         return *this;
     }
References rotation, and translation.
operator==()
bool G3D::PhysicsFrame::operator== (const PhysicsFrame & other) const inline
Definition at line 113 of file PhysicsFrame.h.
{
         return (translation == other.translation) &&
             ((rotation == other.rotation) || (rotation == -other.rotation));
     }
References rotation, and translation.
serialize()
void G3D::PhysicsFrame::serialize (class BinaryOutput & b) const
Definition at line 119 of file PhysicsFrame.cpp.
{
     translation.serialize(b);
     rotation.serialize(b);
 }
References b, rotation, G3D::Quat::serialize(), G3D::Vector3::serialize(), and translation.
toAny()
Any G3D::PhysicsFrame::toAny () const
Definition at line 33 of file PhysicsFrame.cpp.
{
     // Prefer to serialize as a CFrame, which is easier to read
     if (false) {
         Any a(Any::ARRAY, "PFrame");
         a.append(rotation, translation.toAny("Point3"));
         return a;
     } else {
         return CFrame(*this).toAny();
     }
 }
References mpq::a, G3D::Any::ARRAY, rotation, G3D::CoordinateFrame::toAny(), G3D::Vector3::toAny(), and translation.
Member Data Documentation
rotation
Quat G3D::PhysicsFrame::rotation
Definition at line 33 of file PhysicsFrame.h.
Referenced by G3D::PhysicsFrameSpline::correct(), deserialize(), G3D::PhysicsFrameSpline::ensureShortestPath(), lerp(), operator*(), operator*=(), operator+(), operator+=(), operator=(), operator==(), PhysicsFrame(), serialize(), and toAny().
translation
Point3 G3D::PhysicsFrame::translation
Origin of this reference frame in its parent's frame.
Definition at line 38 of file PhysicsFrame.h.
Referenced by deserialize(), lerp(), operator*(), operator*=(), operator+(), operator+=(), operator=(), operator==(), PhysicsFrame(), serialize(), and toAny().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/PhysicsFrame.h
deps/g3dlite/source/PhysicsFrame.cpp