Azerotcore-wotlk: npc_troll_volunteer::npc_troll_volunteerAI Struct Reference
npc_troll_volunteer::npc_troll_volunteerAI Struct Reference
Public Member Functions
npc_troll_volunteerAI (Creature *creature)
void InitializeAI () override
void Reset () override
uint32 GetMountId ()
void MovementInform (uint32 type, uint32 id) override
void SpellHit (Unit *caster, SpellInfo const *spell) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
uint32 _mountModel
bool _complete
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 276 of file zone_durotar.cpp.
Constructor & Destructor Documentation
npc_troll_volunteerAI()
npc_troll_volunteer::npc_troll_volunteerAI::npc_troll_volunteerAI (Creature * creature) inline
Definition at line 278 of file zone_durotar.cpp.
                                                   : ScriptedAI(creature)
         {
         }
Member Function Documentation
GetMountId()
uint32 npc_troll_volunteer::npc_troll_volunteerAI::GetMountId () inline
Definition at line 320 of file zone_durotar.cpp.
         {
             return _mountModel;
         }
References _mountModel.
InitializeAI()
void npc_troll_volunteer::npc_troll_volunteerAI::InitializeAI () inline override virtual
Reimplemented from UnitAI.
Definition at line 282 of file zone_durotar.cpp.
         {
             if (me->isDead() || !me->GetOwner())
                 return;
             Reset();
             switch (urand(0, 3))
             {
                 case 0:
                     _mountModel = 6471;
                     break;
                 case 1:
                     _mountModel = 6473;
                     break;
                 case 2:
                     _mountModel = 6469;
                     break;
                 default:
                     _mountModel = 6472;
                     break;
             }
             me->SetDisplayId(trollmodel[urand(0, 39)]);
             if (Player* player = me->GetOwner()->ToPlayer())
                 me->GetMotionMaster()->MoveFollow(player, 5.0f, float(rand_norm() + 1.0f) * M_PI / 3.0f * 4.0f);
         }
References _mountModel, Unit::GetMotionMaster(), Unit::GetOwner(), Unit::isDead(), ScriptedAI::me, MotionMaster::MoveFollow(), rand_norm(), Reset(), Creature::SetDisplayId(), Object::ToPlayer(), trollmodel, and urand().
MovementInform()
void npc_troll_volunteer::npc_troll_volunteerAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 325 of file zone_durotar.cpp.
         {
             if (type != POINT_MOTION_TYPE)
                 return;
             if (id == POINT_URUZIN)
                 me->DespawnOrUnsummon();
         }
References Creature::DespawnOrUnsummon(), ScriptedAI::me, POINT_MOTION_TYPE, and POINT_URUZIN.
Reset()
void npc_troll_volunteer::npc_troll_volunteerAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 309 of file zone_durotar.cpp.
         {
             _complete = false;
             me->AddAura(SPELL_VOLUNTEER_AURA, me);
             me->AddAura(SPELL_MOUNTING_CHECK, me);
             DoCast(me, SPELL_PETACT_AURA);
             me->SetReactState(REACT_PASSIVE);
             Talk(SAY_VOLUNTEER_START);
         }
References _complete, Unit::AddAura(), UnitAI::DoCast(), ScriptedAI::me, REACT_PASSIVE, SAY_VOLUNTEER_START, Creature::SetReactState(), SPELL_MOUNTING_CHECK, SPELL_PETACT_AURA, SPELL_VOLUNTEER_AURA, and CreatureAI::Talk().
Referenced by InitializeAI().
SpellHit()
void npc_troll_volunteer::npc_troll_volunteerAI::SpellHit (Unit * caster, SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 333 of file zone_durotar.cpp.
         {
             if (spell->Id == SPELL_AOE_TURNIN && caster->GetEntry() == NPC_URUZIN && !_complete)
             {
                 _complete = true;    // Preventing from giving credit twice
                 DoCast(me, SPELL_TURNIN);
                 DoCast(me, SPELL_QUEST_CREDIT);
                 me->RemoveAurasDueToSpell(SPELL_MOUNTING_CHECK);
                 me->Dismount();
                 Talk(SAY_VOLUNTEER_END);
                 me->GetMotionMaster()->MovePoint(POINT_URUZIN, caster->GetPositionX(), caster->GetPositionY(), caster->GetPositionZ());
             }
         }
References _complete, Unit::Dismount(), UnitAI::DoCast(), Object::GetEntry(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), SpellInfo::Id, ScriptedAI::me, MotionMaster::MovePoint(), NPC_URUZIN, POINT_URUZIN, Unit::RemoveAurasDueToSpell(), SAY_VOLUNTEER_END, SPELL_AOE_TURNIN, SPELL_MOUNTING_CHECK, SPELL_QUEST_CREDIT, SPELL_TURNIN, and CreatureAI::Talk().
Member Data Documentation
_complete
bool npc_troll_volunteer::npc_troll_volunteerAI::_complete private
Definition at line 349 of file zone_durotar.cpp.
Referenced by Reset(), and SpellHit().
_mountModel
uint32 npc_troll_volunteer::npc_troll_volunteerAI::_mountModel private
Definition at line 348 of file zone_durotar.cpp.
Referenced by GetMountId(), and InitializeAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/zone_durotar.cpp