Azerotcore-wotlk: Acore::NearestGameObjectEntryInObjectRangeCheck Class Reference
Acore::NearestGameObjectEntryInObjectRangeCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
NearestGameObjectEntryInObjectRangeCheck (WorldObject const &obj, uint32 entry, float range, bool onlySpawned=false)
bool operator() (GameObject *go)
Private Member Functions
NearestGameObjectEntryInObjectRangeCheck (NearestGameObjectEntryInObjectRangeCheck const &)
Private Attributes
WorldObject const & i_obj
uint32 i_entry
float i_range
bool i_onlySpawned
Detailed Description
Definition at line 690 of file GridNotifiers.h.
Constructor & Destructor Documentation
NearestGameObjectEntryInObjectRangeCheck() [1/2]
Acore::NearestGameObjectEntryInObjectRangeCheck::NearestGameObjectEntryInObjectRangeCheck (WorldObject const & obj, uint32 entry, float range, bool onlySpawned = false) inline
Definition at line 693 of file GridNotifiers.h.
                                                                                                                               :
             i_obj(obj), i_entry(entry), i_range(range), i_onlySpawned(onlySpawned) { }
NearestGameObjectEntryInObjectRangeCheck() [2/2]
Acore::NearestGameObjectEntryInObjectRangeCheck::NearestGameObjectEntryInObjectRangeCheck (NearestGameObjectEntryInObjectRangeCheck const &) private
Member Function Documentation
operator()()
bool Acore::NearestGameObjectEntryInObjectRangeCheck::operator() (GameObject * go) inline
Definition at line 696 of file GridNotifiers.h.
         {
             if (go->GetEntry() == i_entry && i_obj.IsWithinDistInMap(go, i_range) && (!i_onlySpawned || go->isSpawned()))
             {
                 i_range = i_obj.GetDistance(go);        // use found GO range as new range limit for next check
                 return true;
             }
             return false;
         }
References WorldObject::GetDistance(), Object::GetEntry(), i_entry, i_obj, i_onlySpawned, i_range, GameObject::isSpawned(), and WorldObject::IsWithinDistInMap().
Member Data Documentation
i_entry
uint32 Acore::NearestGameObjectEntryInObjectRangeCheck::i_entry private
Definition at line 707 of file GridNotifiers.h.
Referenced by operator()().
i_obj
WorldObject const& Acore::NearestGameObjectEntryInObjectRangeCheck::i_obj private
Definition at line 706 of file GridNotifiers.h.
Referenced by operator()().
i_onlySpawned
bool Acore::NearestGameObjectEntryInObjectRangeCheck::i_onlySpawned private
Definition at line 709 of file GridNotifiers.h.
Referenced by operator()().
i_range
float Acore::NearestGameObjectEntryInObjectRangeCheck::i_range private
Definition at line 708 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/game/Grids/Notifiers/GridNotifiers.h