Azerotcore-wotlk: spell_pet_hit_expertise_scalling Class Reference
spell_pet_hit_expertise_scalling Class Reference
Private Member Functions
PrepareAuraScript (spell_pet_hit_expertise_scalling) int32 CalculatePercent(float hitChance
void CalculateHitAmount (AuraEffect const *, int32 &amount, bool &)
void CalculateSpellHitAmount (AuraEffect const *, int32 &amount, bool &)
void CalculateExpertiseAmount (AuraEffect const *, int32 &amount, bool &)
void HandleEffectApply (AuraEffect const *aurEff, AuraEffectHandleModes)
void CalcPeriodic (AuraEffect const *, bool &isPeriodic, int32 &amplitude)
void HandlePeriodic (AuraEffect const *aurEff)
void Register () override
Private Attributes
float cap
float float maxChance
Additional Inherited Members
Public Member Functions inherited from AuraScript
AuraScript ()
bool _Validate (SpellInfo const *entry) override
bool _Load (Aura *aura)
void _PrepareScriptCall (AuraScriptHookType hookType, AuraApplication const *aurApp=nullptr)
void _FinishScriptCall ()
bool _IsDefaultActionPrevented ()
void PreventDefaultAction ()
SpellInfo const * GetSpellInfo () const
uint32 GetId () const
ObjectGuid GetCasterGUID () const
Unit * GetCaster () const
WorldObject * GetOwner () const
Unit * GetUnitOwner () const
DynamicObject * GetDynobjOwner () const
void Remove (uint32 removeMode=0)
Aura * GetAura () const
AuraObjectType GetType () const
int32 GetDuration () const
void SetDuration (int32 duration, bool withMods=false)
void RefreshDuration ()
time_t GetApplyTime () const
int32 GetMaxDuration () const
void SetMaxDuration (int32 duration)
int32 CalcMaxDuration () const
bool IsExpired () const
bool IsPermanent () const
uint8 GetCharges () const
void SetCharges (uint8 charges)
uint8 CalcMaxCharges () const
bool ModCharges (int8 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool DropCharge (AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
uint8 GetStackAmount () const
void SetStackAmount (uint8 num)
bool ModStackAmount (int32 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool IsPassive () const
bool IsDeathPersistent () const
bool HasEffect (uint8 effIndex) const
AuraEffect * GetEffect (uint8 effIndex) const
bool HasEffectType (AuraType type) const
Unit * GetTarget () const
AuraApplication const * GetTargetApplication () const
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from AuraScript
HookList< CheckAreaTargetHandler > DoCheckAreaTarget
HookList< AuraDispelHandler > OnDispel
HookList< AuraDispelHandler > AfterDispel
HookList< EffectApplyHandler > OnEffectApply
HookList< EffectApplyHandler > AfterEffectApply
HookList< EffectApplyHandler > OnEffectRemove
HookList< EffectApplyHandler > AfterEffectRemove
HookList< EffectPeriodicHandler > OnEffectPeriodic
HookList< EffectUpdatePeriodicHandler > OnEffectUpdatePeriodic
HookList< EffectCalcAmountHandler > DoEffectCalcAmount
HookList< EffectCalcPeriodicHandler > DoEffectCalcPeriodic
HookList< EffectCalcSpellModHandler > DoEffectCalcSpellMod
HookList< EffectAbsorbHandler > OnEffectAbsorb
HookList< EffectAbsorbHandler > AfterEffectAbsorb
HookList< EffectManaShieldHandler > OnEffectManaShield
HookList< EffectManaShieldHandler > AfterEffectManaShield
HookList< EffectSplitHandler > OnEffectSplit
HookList< CheckProcHandler > DoCheckProc
HookList< AuraProcHandler > DoPrepareProc
HookList< AuraProcHandler > OnProc
HookList< AuraProcHandler > AfterProc
HookList< EffectProcHandler > OnEffectProc
HookList< EffectProcHandler > AfterEffectProc
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Definition at line 423 of file spell_generic.cpp.
Member Function Documentation
CalcPeriodic()
void spell_pet_hit_expertise_scalling::CalcPeriodic (AuraEffect const * , bool & isPeriodic, int32 & amplitude) inline private
Definition at line 476 of file spell_generic.cpp.
     {
         if (!GetUnitOwner()->IsPet())
             return;
         isPeriodic = true;
         amplitude = 3 * IN_MILLISECONDS;
     }
References AuraScript::GetUnitOwner(), and IN_MILLISECONDS.
Referenced by Register().
CalculateExpertiseAmount()
void spell_pet_hit_expertise_scalling::CalculateExpertiseAmount (AuraEffect const * , int32 & amount, bool &) inline private
Definition at line 458 of file spell_generic.cpp.
     {
         if (Player* modOwner = GetUnitOwner()->GetSpellModOwner())
         {
             if (modOwner->getClass() == CLASS_HUNTER)
                 amount = CalculatePercent(modOwner->m_modRangedHitChance, 8.0f, 26.0f);
             else if (modOwner->getPowerType() == POWER_MANA)
                 amount = CalculatePercent(modOwner->m_modSpellHitChance, 17.0f, 26.0f);
             else
                 amount = CalculatePercent(modOwner->m_modMeleeHitChance, 8.0f, 26.0f);
         }
     }
References CLASS_HUNTER, AuraScript::GetUnitOwner(), and POWER_MANA.
Referenced by Register().
CalculateHitAmount()
void spell_pet_hit_expertise_scalling::CalculateHitAmount (AuraEffect const * , int32 & amount, bool &) inline private
Definition at line 432 of file spell_generic.cpp.
     {
         if (Player* modOwner = GetUnitOwner()->GetSpellModOwner())
         {
             if (modOwner->getClass() == CLASS_HUNTER)
                 amount = CalculatePercent(modOwner->m_modRangedHitChance, 8.0f, 8.0f);
             else if (modOwner->getPowerType() == POWER_MANA)
                 amount = CalculatePercent(modOwner->m_modSpellHitChance, 17.0f, 8.0f);
             else
                 amount = CalculatePercent(modOwner->m_modMeleeHitChance, 8.0f, 8.0f);
         }
     }
References CLASS_HUNTER, AuraScript::GetUnitOwner(), and POWER_MANA.
Referenced by Register().
CalculateSpellHitAmount()
void spell_pet_hit_expertise_scalling::CalculateSpellHitAmount (AuraEffect const * , int32 & amount, bool &) inline private
Definition at line 445 of file spell_generic.cpp.
     {
         if (Player* modOwner = GetUnitOwner()->GetSpellModOwner())
         {
             if (modOwner->getClass() == CLASS_HUNTER)
                 amount = CalculatePercent(modOwner->m_modRangedHitChance, 8.0f, 17.0f);
             else if (modOwner->getPowerType() == POWER_MANA)
                 amount = CalculatePercent(modOwner->m_modSpellHitChance, 17.0f, 17.0f);
             else
                 amount = CalculatePercent(modOwner->m_modMeleeHitChance, 8.0f, 17.0f);
         }
     }
References CLASS_HUNTER, AuraScript::GetUnitOwner(), and POWER_MANA.
Referenced by Register().
HandleEffectApply()
void spell_pet_hit_expertise_scalling::HandleEffectApply (AuraEffect const * aurEff, AuraEffectHandleModes) inline private
Definition at line 471 of file spell_generic.cpp.
     {
         GetUnitOwner()->ApplySpellImmune(GetId(), IMMUNITY_STATE, aurEff->GetAuraType(), true, SPELL_BLOCK_TYPE_POSITIVE);
     }
References Unit::ApplySpellImmune(), AuraEffect::GetAuraType(), AuraScript::GetId(), AuraScript::GetUnitOwner(), IMMUNITY_STATE, and SPELL_BLOCK_TYPE_POSITIVE.
Referenced by Register().
HandlePeriodic()
void spell_pet_hit_expertise_scalling::HandlePeriodic (AuraEffect const * aurEff) inline private
Definition at line 485 of file spell_generic.cpp.
     {
         PreventDefaultAction();
         GetEffect(aurEff->GetEffIndex())->RecalculateAmount();
     }
References AuraScript::GetEffect(), AuraEffect::GetEffIndex(), AuraScript::PreventDefaultAction(), and AuraEffect::RecalculateAmount().
Referenced by Register().
PrepareAuraScript()
spell_pet_hit_expertise_scalling::PrepareAuraScript (spell_pet_hit_expertise_scalling) private
Register()
void spell_pet_hit_expertise_scalling::Register () inline override private virtual
Implements _SpellScript.
Definition at line 491 of file spell_generic.cpp.
     {
         DoEffectCalcAmount += AuraEffectCalcAmountFn(spell_pet_hit_expertise_scalling::CalculateHitAmount, EFFECT_0, SPELL_AURA_MOD_HIT_CHANCE);
         DoEffectCalcAmount += AuraEffectCalcAmountFn(spell_pet_hit_expertise_scalling::CalculateSpellHitAmount, EFFECT_1, SPELL_AURA_MOD_SPELL_HIT_CHANCE);
         DoEffectCalcAmount += AuraEffectCalcAmountFn(spell_pet_hit_expertise_scalling::CalculateExpertiseAmount, EFFECT_2, SPELL_AURA_MOD_EXPERTISE);
         OnEffectApply += AuraEffectApplyFn(spell_pet_hit_expertise_scalling::HandleEffectApply, EFFECT_ALL, SPELL_AURA_ANY, AURA_EFFECT_HANDLE_REAL);
         DoEffectCalcPeriodic += AuraEffectCalcPeriodicFn(spell_pet_hit_expertise_scalling::CalcPeriodic, EFFECT_ALL, SPELL_AURA_ANY);
         OnEffectPeriodic += AuraEffectPeriodicFn(spell_pet_hit_expertise_scalling::HandlePeriodic, EFFECT_ALL, SPELL_AURA_ANY);
     }
References AURA_EFFECT_HANDLE_REAL, AuraEffectApplyFn, AuraEffectCalcAmountFn, AuraEffectCalcPeriodicFn, AuraEffectPeriodicFn, CalcPeriodic(), CalculateExpertiseAmount(), CalculateHitAmount(), CalculateSpellHitAmount(), AuraScript::DoEffectCalcAmount, AuraScript::DoEffectCalcPeriodic, EFFECT_0, EFFECT_1, EFFECT_2, EFFECT_ALL, HandleEffectApply(), HandlePeriodic(), AuraScript::OnEffectApply, AuraScript::OnEffectPeriodic, SPELL_AURA_ANY, SPELL_AURA_MOD_EXPERTISE, SPELL_AURA_MOD_HIT_CHANCE, and SPELL_AURA_MOD_SPELL_HIT_CHANCE.
Member Data Documentation
cap
float spell_pet_hit_expertise_scalling::cap private
Definition at line 427 of file spell_generic.cpp.
maxChance
float float spell_pet_hit_expertise_scalling::maxChance private
Initial value:
{
        return (hitChance / cap) * maxChance
Definition at line 427 of file spell_generic.cpp.
The documentation for this class was generated from the following file:
src/server/scripts/Spells/spell_generic.cpp