Azerotcore-wotlk: EntryPointData Struct Reference
EntryPointData Struct Reference
#include <Player.h>
Public Member Functions
EntryPointData ()
void ClearTaxiPath ()
bool HasTaxiPath () const
Public Attributes
uint32 mountSpell {0}
std::vector< uint32 > taxiPath
WorldLocation joinPos
Detailed Description
Definition at line 1008 of file Player.h.
Constructor & Destructor Documentation
EntryPointData()
EntryPointData::EntryPointData () inline
Definition at line 1010 of file Player.h.
     {
         ClearTaxiPath();
     }
References ClearTaxiPath().
Member Function Documentation
ClearTaxiPath()
void EntryPointData::ClearTaxiPath () inline
Definition at line 1019 of file Player.h.
 { taxiPath.clear(); }
References taxiPath.
Referenced by Player::_LoadEntryPointData(), EntryPointData(), Player::LoadFromDB(), Player::ProcessDelayedOperations(), and Player::SetEntryPoint().
HasTaxiPath()
bool EntryPointData::HasTaxiPath () const inline
Definition at line 1020 of file Player.h.
 { return !taxiPath.empty(); }
References taxiPath.
Referenced by Player::_SaveEntryPoint(), Player::LoadFromDB(), and Player::ProcessDelayedOperations().
Member Data Documentation
joinPos
WorldLocation EntryPointData::joinPos
Definition at line 1017 of file Player.h.
Referenced by Player::_LoadEntryPointData(), Player::_SaveEntryPoint(), Player::GetEntryPoint(), Player::SetEntryPoint(), and Player::TeleportToEntryPoint().
mountSpell
uint32 EntryPointData::mountSpell {0}
Definition at line 1015 of file Player.h.
Referenced by Player::_LoadEntryPointData(), Player::_SaveEntryPoint(), Player::ProcessDelayedOperations(), and Player::SetEntryPoint().
taxiPath
std::vector<uint32> EntryPointData::taxiPath
Definition at line 1016 of file Player.h.
Referenced by Player::_LoadEntryPointData(), Player::_SaveEntryPoint(), ClearTaxiPath(), HasTaxiPath(), Player::LoadFromDB(), Player::ProcessDelayedOperations(), and Player::SetEntryPoint().
The documentation for this struct was generated from the following file:
src/server/game/Entities/Player/Player.h