Azerotcore-wotlk: Acore::UnitSearcher< Check > Struct Template Reference
Acore::UnitSearcher< Check > Struct Template Reference
#include <GridNotifiers.h>
Public Member Functions
UnitSearcher (WorldObject const *searcher, Unit *&result, Check &check)
void Visit (CreatureMapType &m)
void Visit (PlayerMapType &m)
template<class NOT_INTERESTED >
void Visit (GridRefMgr< NOT_INTERESTED > &)
Public Attributes
uint32 i_phaseMask
Unit *& i_object
Check & i_check
Detailed Description
template<class Check>
struct Acore::UnitSearcher< Check >
Definition at line 357 of file GridNotifiers.h.
Constructor & Destructor Documentation
UnitSearcher()
template<class Check > Acore::UnitSearcher< Check >::UnitSearcher (WorldObject const * searcher, Unit *& result, Check & check) inline
Definition at line 363 of file GridNotifiers.h.
             : i_phaseMask(searcher->GetPhaseMask()), i_object(result), i_check(check) {}
Member Function Documentation
Visit() [1/3]
template<class Check > void Acore::UnitSearcher< Check >::Visit (CreatureMapType & m)
Definition at line 348 of file GridNotifiersImpl.h.
 {
     // already found
     if (i_object)
         return;
     for (CreatureMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
     {
         if (!itr->GetSource()->InSamePhase(i_phaseMask))
             continue;
         if (i_check(itr->GetSource()))
         {
             i_object = itr->GetSource();
             return;
         }
     }
 }
References GridRefMgr< OBJECT >::begin(), and GridRefMgr< OBJECT >::end().
Visit() [2/3]
template<class Check > template<class NOT_INTERESTED > void Acore::UnitSearcher< Check >::Visit (GridRefMgr< NOT_INTERESTED > &) inline
Definition at line 369 of file GridNotifiers.h.
 {}
Visit() [3/3]
template<class Check > void Acore::UnitSearcher< Check >::Visit (PlayerMapType & m)
Definition at line 368 of file GridNotifiersImpl.h.
 {
     // already found
     if (i_object)
         return;
     for (PlayerMapType::iterator itr = m.begin(); itr != m.end(); ++itr)
     {
         if (!itr->GetSource()->InSamePhase(i_phaseMask))
             continue;
         if (i_check(itr->GetSource()))
         {
             i_object = itr->GetSource();
             return;
         }
     }
 }
References GridRefMgr< OBJECT >::begin(), and GridRefMgr< OBJECT >::end().
Member Data Documentation
i_check
template<class Check > Check& Acore::UnitSearcher< Check >::i_check
Definition at line 361 of file GridNotifiers.h.
i_object
template<class Check > Unit*& Acore::UnitSearcher< Check >::i_object
Definition at line 360 of file GridNotifiers.h.
i_phaseMask
template<class Check > uint32 Acore::UnitSearcher< Check >::i_phaseMask
Definition at line 359 of file GridNotifiers.h.
The documentation for this struct was generated from the following files:
src/server/game/Grids/Notifiers/GridNotifiers.h
src/server/game/Grids/Notifiers/GridNotifiersImpl.h