Azerotcore-wotlk: SpellRuneCostEntry Struct Reference
SpellRuneCostEntry Struct Reference
#include <DBCStructure.h>
Public Member Functions
bool NoRuneCost () const
bool NoRunicPowerGain () const
Public Attributes
uint32 ID
uint32 RuneCost [3]
uint32 runePowerGain
Detailed Description
Definition at line 1730 of file DBCStructure.h.
Member Function Documentation
NoRuneCost()
bool SpellRuneCostEntry::NoRuneCost () const inline
Definition at line 1736 of file DBCStructure.h.
 { return RuneCost[0] == 0 && RuneCost[1] == 0 && RuneCost[2] == 0; }
References RuneCost.
Referenced by Spell::CheckRuneCost(), and Spell::TakeRunePower().
NoRunicPowerGain()
bool SpellRuneCostEntry::NoRunicPowerGain () const inline
Definition at line 1737 of file DBCStructure.h.
 { return runePowerGain == 0; }
References runePowerGain.
Referenced by Spell::TakeRunePower().
Member Data Documentation
ID
uint32 SpellRuneCostEntry::ID
Definition at line 1732 of file DBCStructure.h.
RuneCost
uint32 SpellRuneCostEntry::RuneCost[3]
Definition at line 1733 of file DBCStructure.h.
Referenced by Spell::CheckRuneCost(), NoRuneCost(), and Spell::TakeRunePower().
runePowerGain
uint32 SpellRuneCostEntry::runePowerGain
Definition at line 1734 of file DBCStructure.h.
Referenced by NoRunicPowerGain(), and Spell::TakeRunePower().
The documentation for this struct was generated from the following file:
src/server/shared/DataStores/DBCStructure.h