Azerotcore-wotlk: npc_magwin::npc_magwinAI Struct Reference
npc_magwin::npc_magwinAI Struct Reference
Public Member Functions
npc_magwinAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *who) override
void sQuestAccept (Player *player, Quest const *quest) override
void WaypointReached (uint32 waypointId) override
void UpdateEscortAI (uint32 diff) override
Public Member Functions inherited from npc_escortAI
npc_escortAI (Creature *creature)
~npc_escortAI () override
void AttackStart (Unit *who) override
void MoveInLineOfSight (Unit *who) override
void JustDied (Unit *) override
void JustRespawned () override
void ReturnToLastPoint ()
void EnterEvadeMode () override
void UpdateAI (uint32 diff) override
void MovementInform (uint32, uint32) override
void AddWaypoint (uint32 id, float x, float y, float z, uint32 waitTime=0)
bool SetNextWaypoint (uint32 pointId, float x, float y, float z, float orientation)
bool SetNextWaypoint (uint32 pointId, bool setPosition=true)
bool GetWaypointPosition (uint32 pointId, float &x, float &y, float &z)
void GenerateWaypointArray (Movement::PointsArray *points)
virtual void WaypointStart (uint32)
void Start (bool isActiveAttacker=true, bool run=false, ObjectGuid playerGUID=ObjectGuid::Empty, Quest const *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, bool resetWaypoints=true)
void SetRun (bool on=true)
void SetEscortPaused (bool on)
bool HasEscortState (uint32 escortState)
bool IsEscorted () override
void SetMaxPlayerDistance (float newMax)
float GetMaxPlayerDistance ()
void SetDespawnAtEnd (bool despawn)
void SetDespawnAtFar (bool despawn)
bool GetAttack ()
void SetCanAttack (bool attack)
ObjectGuid GetEventStarterGUID ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
EventMap _events
ObjectGuid _player
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from npc_escortAI
Player * GetPlayerForEscort ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 239 of file zone_azuremyst_isle.cpp.
Constructor & Destructor Documentation
npc_magwinAI()
npc_magwin::npc_magwinAI::npc_magwinAI (Creature * creature) inline
Definition at line 241 of file zone_azuremyst_isle.cpp.
 : npc_escortAI(creature) { }
Member Function Documentation
EnterCombat()
void npc_magwin::npc_magwinAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 248 of file zone_azuremyst_isle.cpp.
         {
             Talk(SAY_AGGRO, who);
         }
References SAY_AGGRO, and CreatureAI::Talk().
Reset()
void npc_magwin::npc_magwinAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 243 of file zone_azuremyst_isle.cpp.
         {
             _events.Reset();
         }
References _events, and EventMap::Reset().
sQuestAccept()
void npc_magwin::npc_magwinAI::sQuestAccept (Player * player, Quest const * quest) inline override virtual
Reimplemented from UnitAI.
Definition at line 253 of file zone_azuremyst_isle.cpp.
         {
             if (quest->GetQuestId() == QUEST_A_CRY_FOR_HELP)
             {
                 _player = player->GetGUID();
                 _events.ScheduleEvent(EVENT_ACCEPT_QUEST, 2000);
             }
         }
References _events, _player, EVENT_ACCEPT_QUEST, Object::GetGUID(), Quest::GetQuestId(), QUEST_A_CRY_FOR_HELP, and EventMap::ScheduleEvent().
UpdateEscortAI()
void npc_magwin::npc_magwinAI::UpdateEscortAI (uint32 diff) inline override virtual
Reimplemented from npc_escortAI.
Definition at line 287 of file zone_azuremyst_isle.cpp.
         {
             _events.Update(diff);
             if (uint32 eventId = _events.ExecuteEvent())
             {
                 switch (eventId)
                 {
                     case EVENT_ACCEPT_QUEST:
                         if (Player* player = ObjectAccessor::GetPlayer(*me, _player))
{
                             Talk(SAY_START, player);
                         }
                         me->SetFaction(FACTION_ESCORTEE_N_NEUTRAL_PASSIVE);
                         _events.ScheduleEvent(EVENT_START_ESCORT, 1000);
                         break;
                     case EVENT_START_ESCORT:
                         if (Player* player = ObjectAccessor::GetPlayer(*me, _player))
{
                             npc_escortAI::Start(true, false, player->GetGUID());
                         }
                         _events.ScheduleEvent(EVENT_STAND, 2000);
                         break;
                     case EVENT_STAND: // Remove kneel standstate. Using a separate delayed event because it causes unwanted delay before starting waypoint movement.
                         me->SetByteValue(UNIT_FIELD_BYTES_1, UNIT_BYTES_1_OFFSET_STAND_STATE, UNIT_STAND_STATE_STAND);
                         break;
                     case EVENT_TALK_END:
                         if (Player* player = ObjectAccessor::GetPlayer(*me, _player))
{
                             Talk(SAY_END1, player);
                         }
                         _events.ScheduleEvent(EVENT_COWLEN_TALK, 2000);
                         break;
                     case EVENT_COWLEN_TALK:
                         if (Creature* cowlen = me->FindNearestCreature(NPC_COWLEN, 50.0f, true))
{
                             cowlen->AI()->Talk(SAY_COWLEN);
                         }
                         break;
                 }
             }
             npc_escortAI::UpdateEscortAI(diff);
         }
References _events, _player, EVENT_ACCEPT_QUEST, EVENT_COWLEN_TALK, EVENT_STAND, EVENT_START_ESCORT, EVENT_TALK_END, EventMap::ExecuteEvent(), FACTION_ESCORTEE_N_NEUTRAL_PASSIVE, WorldObject::FindNearestCreature(), ObjectAccessor::GetPlayer(), ScriptedAI::me, NPC_COWLEN, SAY_COWLEN, SAY_END1, SAY_START, EventMap::ScheduleEvent(), Object::SetByteValue(), Unit::SetFaction(), npc_escortAI::Start(), CreatureAI::Talk(), UNIT_BYTES_1_OFFSET_STAND_STATE, UNIT_FIELD_BYTES_1, UNIT_STAND_STATE_STAND, EventMap::Update(), and npc_escortAI::UpdateEscortAI().
WaypointReached()
void npc_magwin::npc_magwinAI::WaypointReached (uint32 waypointId) inline override virtual
Implements npc_escortAI.
Definition at line 262 of file zone_azuremyst_isle.cpp.
         {
             if (Player* player = GetPlayerForEscort())
             {
                 switch (waypointId)
                 {
                     case 17:
                         Talk(SAY_PROGRESS, player);
                         break;
                     case 28:
                         player->GroupEventHappens(QUEST_A_CRY_FOR_HELP, me);
                         _events.ScheduleEvent(EVENT_TALK_END, 2000);
                         SetRun(true);
                         break;
                     case 29:
                         if (Creature* cowlen = me->FindNearestCreature(NPC_COWLEN, 50.0f, true))
{
                             Talk(EMOTE_HUG, cowlen);
                             Talk(SAY_END2, player);
                             break;
                         }
                 }
             }
         }
References _events, EMOTE_HUG, EVENT_TALK_END, WorldObject::FindNearestCreature(), npc_escortAI::GetPlayerForEscort(), ScriptedAI::me, NPC_COWLEN, QUEST_A_CRY_FOR_HELP, SAY_END2, SAY_PROGRESS, EventMap::ScheduleEvent(), npc_escortAI::SetRun(), and CreatureAI::Talk().
Member Data Documentation
_events
EventMap npc_magwin::npc_magwinAI::_events private
Definition at line 330 of file zone_azuremyst_isle.cpp.
Referenced by Reset(), sQuestAccept(), UpdateEscortAI(), and WaypointReached().
_player
ObjectGuid npc_magwin::npc_magwinAI::_player private
Definition at line 331 of file zone_azuremyst_isle.cpp.
Referenced by sQuestAccept(), and UpdateEscortAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/zone_azuremyst_isle.cpp