Azerotcore-wotlk: MotionTransport Class Reference
MotionTransport Class Reference
#include <Transport.h>
Public Member Functions
~MotionTransport () override
bool CreateMoTrans (ObjectGuid::LowType guidlow, uint32 entry, uint32 mapid, float x, float y, float z, float ang, uint32 animprogress)
void CleanupsBeforeDelete (bool finalCleanup=true) override
void BuildUpdate (UpdateDataMapType &data_map, UpdatePlayerSet &) override
void Update (uint32 diff) override
void DelayedUpdate (uint32 diff)
void UpdatePosition (float x, float y, float z, float o)
void AddPassenger (WorldObject *passenger, bool withAll=false) override
void RemovePassenger (WorldObject *passenger, bool withAll=false) override
Creature * CreateNPCPassenger (ObjectGuid::LowType guid, CreatureData const *data)
GameObject * CreateGOPassenger (ObjectGuid::LowType guid, GameObjectData const *data)
void LoadStaticPassengers ()
PassengerSet const & GetStaticPassengers () const
void UnloadStaticPassengers ()
void UnloadNonStaticPassengers ()
void SetPassengersLoaded (bool loaded)
bool PassengersLoaded () const
KeyFrameVec const & GetKeyFrames () const
void EnableMovement (bool enabled)
TransportTemplate const * GetTransportTemplate () const
uint32 GetPeriod () const
void SetPeriod (uint32 period)
Public Member Functions inherited from Transport
Transport ()
void CalculatePassengerPosition (float &x, float &y, float &z, float *o=nullptr) const override
This method transforms supplied transport offsets into global coordinates.
void CalculatePassengerOffset (float &x, float &y, float &z, float *o=nullptr) const override
This method transforms supplied global coordinates into local offsets.
PassengerSet const & GetPassengers () const
uint32 GetPathProgress () const
void SetPathProgress (uint32 val)
Public Member Functions inherited from GameObject
GameObject ()
~GameObject () override
void BuildValuesUpdate (uint8 updatetype, ByteBuffer *data, Player *target) const override
void AddToWorld () override
void RemoveFromWorld () override
virtual bool Create (ObjectGuid::LowType guidlow, uint32 name_id, Map *map, uint32 phaseMask, float x, float y, float z, float ang, G3D::Quat const &rotation, uint32 animprogress, GOState go_state, uint32 artKit=0)
GameObjectTemplate const * GetGOInfo () const
GameObjectTemplateAddon const * GetTemplateAddon () const
GameObjectData const * GetGOData () const
GameObjectValue const * GetGOValue () const
bool IsTransport () const
bool IsDestructibleBuilding () const
ObjectGuid::LowType GetSpawnId () const
void SetLocalRotationAngles (float z_rot, float y_rot, float x_rot)
void SetLocalRotation (G3D::Quat const &rot)
void SetTransportPathRotation (float qx, float qy, float qz, float qw)
G3D::Quat const & GetLocalRotation () const
int64 GetPackedLocalRotation () const
G3D::Quat GetWorldRotation () const
std::string const & GetNameForLocaleIdx (LocaleConstant locale_idx) const override
void SaveToDB (bool saveAddon=false)
void SaveToDB (uint32 mapid, uint8 spawnMask, uint32 phaseMask, bool saveAddon=false)
bool LoadFromDB (ObjectGuid::LowType guid, Map *map)
bool LoadGameObjectFromDB (ObjectGuid::LowType guid, Map *map, bool addToMap=true)
void DeleteFromDB ()
void SetOwnerGUID (ObjectGuid owner)
ObjectGuid GetOwnerGUID () const
Unit * GetOwner () const
void SetSpellId (uint32 id)
uint32 GetSpellId () const
time_t GetRespawnTime () const
time_t GetRespawnTimeEx () const
void SetRespawnTime (int32 respawn)
void SetRespawnDelay (int32 respawn)
void Respawn ()
bool isSpawned () const
bool isSpawnedByDefault () const
void SetSpawnedByDefault (bool b)
uint32 GetRespawnDelay () const
void Refresh ()
void DespawnOrUnsummon (Milliseconds delay=0ms, Seconds forcedRespawnTime=0s)
void Delete ()
void GetFishLoot (Loot *loot, Player *loot_owner)
void GetFishLootJunk (Loot *loot, Player *loot_owner)
GameobjectTypes GetGoType () const
void SetGoType (GameobjectTypes type)
GOState GetGoState () const
void SetGoState (GOState state)
uint8 GetGoArtKit () const
void SetGoArtKit (uint8 artkit)
uint8 GetGoAnimProgress () const
void SetGoAnimProgress (uint8 animprogress)
void SetPhaseMask (uint32 newPhaseMask, bool update) override
void EnableCollision (bool enable)
void Use (Unit *user)
LootState getLootState () const
void SetLootState (LootState s, Unit *unit=nullptr)
uint16 GetLootMode () const
bool HasLootMode (uint16 lootMode) const
void SetLootMode (uint16 lootMode)
void AddLootMode (uint16 lootMode)
void RemoveLootMode (uint16 lootMode)
void ResetLootMode ()
void AddToSkillupList (ObjectGuid playerGuid)
bool IsInSkillupList (ObjectGuid playerGuid) const
void ClearSkillupList ()
void AddUniqueUse (Player *player)
void AddUse ()
uint32 GetUseCount () const
uint32 GetUniqueUseCount () const
void SaveRespawnTime () override
void SaveRespawnTime (uint32 forceDelay)
Player * GetLootRecipient () const
Group * GetLootRecipientGroup () const
void SetLootRecipient (Creature *creature)
void SetLootRecipient (Map *map)
bool IsLootAllowedFor (Player const *player) const
bool HasLootRecipient () const
void SetLootGenerationTime ()
uint32 GetLootGenerationTime () const
GameObject * GetLinkedTrap ()
void SetLinkedTrap (GameObject *linkedTrap)
bool hasQuest (uint32 quest_id) const override
bool hasInvolvedQuest (uint32 quest_id) const override
bool ActivateToQuest (Player *target) const
void UseDoorOrButton (uint32 time_to_restore=0, bool alternative=false, Unit *user=nullptr)
void ResetDoorOrButton ()
void TriggeringLinkedGameObject (uint32 trapEntry, Unit *target)
bool IsNeverVisible () const override
bool IsAlwaysVisibleFor (WorldObject const *seer) const override
bool IsInvisibleDueToDespawn () const override
uint8 getLevelForTarget (WorldObject const *target) const override
GameObject * LookupFishingHoleAround (float range)
void CastSpell (Unit *target, uint32 spell)
void SendCustomAnim (uint32 anim)
bool IsInRange (float x, float y, float z, float radius) const
void SendMessageToSetInRange (WorldPacket *data, float dist, bool, bool includeMargin=false, Player const *skipped_rcvr=nullptr) override
void ModifyHealth (int32 change, Unit *attackerOrHealer=nullptr, uint32 spellId=0)
void SetDestructibleBuildingModifyState (bool allow)
void SetDestructibleState (GameObjectDestructibleState state, Player *eventInvoker=nullptr, bool setHealth=false)
GameObjectDestructibleState GetDestructibleState () const
void EventInform (uint32 eventId)
virtual uint32 GetScriptId () const
GameObjectAI * AI () const
std::string GetAIName () const
void SetDisplayId (uint32 displayid)
uint32 GetDisplayId () const
void GetRespawnPosition (float &x, float &y, float &z, float *ori=nullptr) const
void SetPosition (float x, float y, float z, float o)
void SetPosition (const Position &pos)
bool IsStaticTransport () const
bool IsMotionTransport () const
Transport * ToTransport ()
Transport const * ToTransport () const
StaticTransport * ToStaticTransport ()
StaticTransport const * ToStaticTransport () const
MotionTransport * ToMotionTransport ()
MotionTransport const * ToMotionTransport () const
float GetStationaryX () const override
float GetStationaryY () const override
float GetStationaryZ () const override
float GetStationaryO () const override
float GetInteractionDistance () const
void UpdateModelPosition ()
bool IsAtInteractDistance (Position const &pos, float radius) const
bool IsAtInteractDistance (Player const *player, SpellInfo const *spell=nullptr) const
bool IsWithinDistInMap (Player const *player) const
SpellInfo const * GetSpellForLock (Player const *player) const
bool IsWithinDistInMap (WorldObject const *obj, float dist2compare, bool is3D=true, bool useBoundingRadius=true) const
Public Member Functions inherited from WorldObject
~WorldObject () override
void _Create (ObjectGuid::LowType guidlow, HighGuid guidhigh, uint32 phaseMask)
void AddToWorld () override
void RemoveFromWorld () override
void GetNearPoint2D (WorldObject const *searcher, float &x, float &y, float distance, float absAngle, Position const *startPos=nullptr) const
void GetNearPoint2D (float &x, float &y, float distance, float absAngle, Position const *startPos=nullptr) const
void GetNearPoint (WorldObject const *searcher, float &x, float &y, float &z, float searcher_size, float distance2d, float absAngle, float controlZ=0, Position const *startPos=nullptr) const
void GetVoidClosePoint (float &x, float &y, float &z, float size, float distance2d=0, float relAngle=0, float controlZ=0) const
bool GetClosePoint (float &x, float &y, float &z, float size, float distance2d=0, float angle=0, const WorldObject *forWho=nullptr, bool force=false) const
void MovePosition (Position &pos, float dist, float angle)
Position GetNearPosition (float dist, float angle)
void MovePositionToFirstCollision (Position &pos, float dist, float angle)
Position GetFirstCollisionPosition (float startX, float startY, float startZ, float destX, float destY)
Position GetFirstCollisionPosition (float destX, float destY, float destZ)
Position GetFirstCollisionPosition (float dist, float angle)
Position GetRandomNearPosition (float radius)
void GetContactPoint (const WorldObject *obj, float &x, float &y, float &z, float distance2d=CONTACT_DISTANCE) const
void GetChargeContactPoint (const WorldObject *obj, float &x, float &y, float &z, float distance2d=CONTACT_DISTANCE) const
float GetObjectSize () const
virtual float GetCombatReach () const
void UpdateGroundPositionZ (float x, float y, float &z) const
void UpdateAllowedPositionZ (float x, float y, float &z, float *groundZ=nullptr) const
void GetRandomPoint (const Position &srcPos, float distance, float &rand_x, float &rand_y, float &rand_z) const
Position GetRandomPoint (const Position &srcPos, float distance) const
uint32 GetInstanceId () const
uint32 GetPhaseMask () const
bool InSamePhase (WorldObject const *obj) const
bool InSamePhase (uint32 phasemask) const
uint32 GetZoneId () const
uint32 GetAreaId () const
void GetZoneAndAreaId (uint32 &zoneid, uint32 &areaid) const
bool IsOutdoors () const
LiquidData const & GetLiquidData () const
InstanceScript * GetInstanceScript () const
std::string const & GetName () const
void SetName (std::string const &newname)
float GetDistance (const WorldObject *obj) const
float GetDistance (const Position &pos) const
float GetDistance (float x, float y, float z) const
float GetDistance2d (const WorldObject *obj) const
float GetDistance2d (float x, float y) const
float GetDistanceZ (const WorldObject *obj) const
bool IsSelfOrInSameMap (const WorldObject *obj) const
bool IsInMap (const WorldObject *obj) const
bool IsWithinDist3d (float x, float y, float z, float dist) const
bool IsWithinDist3d (const Position *pos, float dist) const
bool IsWithinDist2d (float x, float y, float dist) const
bool IsWithinDist2d (const Position *pos, float dist) const
bool IsWithinDist (WorldObject const *obj, float dist2compare, bool is3D=true, bool useBoundingRadius=true) const
bool IsWithinDistInMap (WorldObject const *obj, float dist2compare, bool is3D=true, bool useBoundingRadius=true) const
bool IsWithinLOS (float x, float y, float z, LineOfSightChecks checks=LINEOFSIGHT_ALL_CHECKS) const
bool IsWithinLOSInMap (WorldObject const *obj, LineOfSightChecks checks=LINEOFSIGHT_ALL_CHECKS) const
Position GetHitSpherePointFor (Position const &dest) const
void GetHitSpherePointFor (Position const &dest, float &x, float &y, float &z) const
bool GetDistanceOrder (WorldObject const *obj1, WorldObject const *obj2, bool is3D=true) const
bool IsInRange (WorldObject const *obj, float minRange, float maxRange, bool is3D=true) const
bool IsInRange2d (float x, float y, float minRange, float maxRange) const
bool IsInRange3d (float x, float y, float z, float minRange, float maxRange) const
bool isInFront (WorldObject const *target, float arc=M_PI) const
bool isInBack (WorldObject const *target, float arc=M_PI) const
bool IsInBetween (const WorldObject *obj1, const WorldObject *obj2, float size=0) const
virtual void SendMessageToSet (WorldPacket *data, bool self)
virtual void SendMessageToSet (WorldPacket *data, Player const *skipped_rcvr)
void PlayDistanceSound (uint32 sound_id, Player *target=nullptr)
void PlayDirectSound (uint32 sound_id, Player *target=nullptr)
void PlayDirectMusic (uint32 music_id, Player *target=nullptr)
void SendObjectDeSpawnAnim (ObjectGuid guid)
void AddObjectToRemoveList ()
float GetGridActivationRange () const
float GetVisibilityRange () const
virtual float GetSightRange (const WorldObject *target=nullptr) const
bool CanSeeOrDetect (WorldObject const *obj, bool ignoreStealth=false, bool distanceCheck=false, bool checkAlert=false) const
void SendPlayMusic (uint32 Music, bool OnlySelf)
virtual void SetMap (Map *map)
virtual void ResetMap ()
Map * GetMap () const
Map * FindMap () const
void SetZoneScript ()
void ClearZoneScript ()
ZoneScript * GetZoneScript () const
TempSummon * SummonCreature (uint32 id, const Position &pos, TempSummonType spwtype=TEMPSUMMON_MANUAL_DESPAWN, uint32 despwtime=0, uint32 vehId=0, SummonPropertiesEntry const *properties=nullptr) const
TempSummon * SummonCreature (uint32 id, float x, float y, float z, float ang=0, TempSummonType spwtype=TEMPSUMMON_MANUAL_DESPAWN, uint32 despwtime=0, SummonPropertiesEntry const *properties=nullptr)
GameObject * SummonGameObject (uint32 entry, float x, float y, float z, float ang, float rotation0, float rotation1, float rotation2, float rotation3, uint32 respawnTime, bool checkTransport=true)
Creature * SummonTrigger (float x, float y, float z, float ang, uint32 dur, bool setLevel=false, CreatureAI *(*GetAI)(Creature *)=nullptr)
void SummonCreatureGroup (uint8 group, std::list< TempSummon * > *list=nullptr)
Creature * FindNearestCreature (uint32 entry, float range, bool alive=true) const
GameObject * FindNearestGameObject (uint32 entry, float range, bool onlySpawned=false) const
GameObject * FindNearestGameObjectOfType (GameobjectTypes type, float range) const
Player * SelectNearestPlayer (float distance=0) const
void GetGameObjectListWithEntryInGrid (std::list< GameObject * > &lList, uint32 uiEntry, float fMaxSearchRange) const
void GetCreatureListWithEntryInGrid (std::list< Creature * > &lList, uint32 uiEntry, float fMaxSearchRange) const
void GetDeadCreatureListInGrid (std::list< Creature * > &lList, float maxSearchRange, bool alive=false) const
void DestroyForNearbyPlayers ()
virtual void UpdateObjectVisibility (bool forced=true, bool fromUpdate=false)
void GetCreaturesWithEntryInRange (std::list< Creature * > &creatureList, float radius, uint32 entry)
void SetPositionDataUpdate ()
void UpdatePositionData ()
void AddToObjectUpdate () override
void RemoveFromObjectUpdate () override
void AddToNotify (uint16 f)
void RemoveFromNotify (uint16 f)
bool isNeedNotify (uint16 f) const
uint16 GetNotifyFlags () const
bool NotifyExecuted (uint16 f) const
void SetNotified (uint16 f)
void ResetAllNotifies ()
bool isActiveObject () const
void setActive (bool isActiveObject)
bool IsVisibilityOverridden () const
void SetVisibilityDistanceOverride (bool isVisibilityDistanceOverride)
void SetWorldObject (bool apply)
bool IsPermanentWorldObject () const
bool IsWorldObject () const
bool IsInWintergrasp () const
Transport * GetTransport () const
float GetTransOffsetX () const
float GetTransOffsetY () const
float GetTransOffsetZ () const
float GetTransOffsetO () const
uint32 GetTransTime () const
int8 GetTransSeat () const
virtual ObjectGuid GetTransGUID () const
void SetTransport (Transport *t)
float GetMapWaterOrGroundLevel (float x, float y, float z, float *ground=nullptr) const
float GetMapHeight (float x, float y, float z, bool vmap=true, float distanceToSearch=50.0f) const
float GetFloorZ () const
float GetMinHeightInWater () const
Get the minimum height of a object that should be in water to start floating/swim.
virtual float GetCollisionHeight () const
virtual float GetCollisionWidth () const
virtual float GetCollisionRadius () const
void AddAllowedLooter (ObjectGuid guid)
void ResetAllowedLooters ()
void SetAllowedLooters (GuidUnorderedSet const looters)
bool HasAllowedLooter (ObjectGuid guid) const
GuidUnorderedSet const & GetAllowedLooters () const
Public Member Functions inherited from Object
virtual ~Object ()
bool IsInWorld () const
ObjectGuid GetGUID () const
PackedGuid const & GetPackGUID () const
uint32 GetEntry () const
void SetEntry (uint32 entry)
float GetObjectScale () const
virtual void SetObjectScale (float scale)
TypeID GetTypeId () const
bool isType (uint16 mask) const
virtual void BuildCreateUpdateBlockForPlayer (UpdateData *data, Player *target) const
void SendUpdateToPlayer (Player *player)
void BuildValuesUpdateBlockForPlayer (UpdateData *data, Player *target) const
void BuildOutOfRangeUpdateBlock (UpdateData *data) const
void BuildMovementUpdateBlock (UpdateData *data, uint32 flags=0) const
virtual void DestroyForPlayer (Player *target, bool onDeath=false) const
int32 GetInt32Value (uint16 index) const
uint32 GetUInt32Value (uint16 index) const
uint64 GetUInt64Value (uint16 index) const
float GetFloatValue (uint16 index) const
uint8 GetByteValue (uint16 index, uint8 offset) const
uint16 GetUInt16Value (uint16 index, uint8 offset) const
ObjectGuid GetGuidValue (uint16 index) const
void SetInt32Value (uint16 index, int32 value)
void SetUInt32Value (uint16 index, uint32 value)
void UpdateUInt32Value (uint16 index, uint32 value)
void SetUInt64Value (uint16 index, uint64 value)
void SetFloatValue (uint16 index, float value)
void SetByteValue (uint16 index, uint8 offset, uint8 value)
void SetUInt16Value (uint16 index, uint8 offset, uint16 value)
void SetInt16Value (uint16 index, uint8 offset, int16 value)
void SetGuidValue (uint16 index, ObjectGuid value)
void SetStatFloatValue (uint16 index, float value)
void SetStatInt32Value (uint16 index, int32 value)
bool AddGuidValue (uint16 index, ObjectGuid value)
bool RemoveGuidValue (uint16 index, ObjectGuid value)
void ApplyModUInt32Value (uint16 index, int32 val, bool apply)
void ApplyModInt32Value (uint16 index, int32 val, bool apply)
void ApplyModUInt64Value (uint16 index, int32 val, bool apply)
void ApplyModPositiveFloatValue (uint16 index, float val, bool apply)
void ApplyModSignedFloatValue (uint16 index, float val, bool apply)
void ApplyPercentModFloatValue (uint16 index, float val, bool apply)
void SetFlag (uint16 index, uint32 newFlag)
void RemoveFlag (uint16 index, uint32 oldFlag)
void ToggleFlag (uint16 index, uint32 flag)
bool HasFlag (uint16 index, uint32 flag) const
void ApplyModFlag (uint16 index, uint32 flag, bool apply)
void SetByteFlag (uint16 index, uint8 offset, uint8 newFlag)
void RemoveByteFlag (uint16 index, uint8 offset, uint8 newFlag)
bool HasByteFlag (uint16 index, uint8 offset, uint8 flag) const
void SetFlag64 (uint16 index, uint64 newFlag)
void RemoveFlag64 (uint16 index, uint64 oldFlag)
void ToggleFlag64 (uint16 index, uint64 flag)
bool HasFlag64 (uint16 index, uint64 flag) const
void ApplyModFlag64 (uint16 index, uint64 flag, bool apply)
void ClearUpdateMask (bool remove)
uint16 GetValuesCount () const
void BuildFieldsUpdate (Player *, UpdateDataMapType &) const
void SetFieldNotifyFlag (uint16 flag)
void RemoveFieldNotifyFlag (uint16 flag)
void ForceValuesUpdateAtIndex (uint32)
bool IsPlayer () const
Player * ToPlayer ()
Player const * ToPlayer () const
Creature * ToCreature ()
Creature const * ToCreature () const
Unit * ToUnit ()
Unit const * ToUnit () const
GameObject * ToGameObject ()
GameObject const * ToGameObject () const
Corpse * ToCorpse ()
Corpse const * ToCorpse () const
DynamicObject * ToDynObject ()
DynamicObject const * ToDynObject () const
Public Member Functions inherited from WorldLocation
WorldLocation (uint32 _mapId=MAPID_INVALID, float x=0.f, float y=0.f, float z=0.f, float o=0.f)
WorldLocation (uint32 mapId, Position const &position)
void WorldRelocate (const WorldLocation &loc)
void WorldRelocate (uint32 mapId=MAPID_INVALID, float x=0.f, float y=0.f, float z=0.f, float o=0.f)
void SetMapId (uint32 mapId)
uint32 GetMapId () const
void GetWorldLocation (uint32 &mapId, float &x, float &y) const
void GetWorldLocation (uint32 &mapId, float &x, float &y, float &z) const
void GetWorldLocation (uint32 &mapId, float &x, float &y, float &z, float &o) const
void GetWorldLocation (WorldLocation *location) const
WorldLocation GetWorldLocation () const
Public Member Functions inherited from Position
Position (float x=0, float y=0, float z=0, float o=0)
Position (Position const &loc)
bool operator== (Position const &a) const
bool operator!= (Position const &a)
operator G3D::Vector3 () const
void Relocate (float x, float y)
void Relocate (float x, float y, float z)
void Relocate (float x, float y, float z, float orientation)
void Relocate (const Position &pos)
void Relocate (const Position *pos)
void RelocatePolarOffset (float angle, float dist, float z=0.0f)
void RelocateOffset (const Position &offset)
void SetOrientation (float orientation)
float GetPositionX () const
float GetPositionY () const
float GetPositionZ () const
float GetOrientation () const
void GetPosition (float &x, float &y) const
void GetPosition (float &x, float &y, float &z) const
void GetPosition (float &x, float &y, float &z, float &o) const
Position GetPosition () const
Position::PositionXYZStreamer PositionXYZStream ()
Position::PositionXYZOStreamer PositionXYZOStream ()
bool IsPositionValid () const
float GetExactDist2dSq (const float x, const float y) const
float GetExactDist2dSq (Position const &pos) const
float GetExactDist2dSq (Position const *pos) const
float GetExactDist2d (const float x, const float y) const
float GetExactDist2d (Position const &pos) const
float GetExactDist2d (Position const *pos) const
float GetExactDistSq (float x, float y, float z) const
float GetExactDistSq (Position const &pos) const
float GetExactDistSq (Position const *pos) const
float GetExactDist (float x, float y, float z) const
float GetExactDist (Position const &pos) const
float GetExactDist (Position const *pos) const
void GetPositionOffsetTo (const Position &endPos, Position &retOffset) const
Position GetPositionWithOffset (Position const &offset) const
float GetAngle (const Position *pos) const
float GetAngle (float x, float y) const
float GetAbsoluteAngle (float x, float y) const
float GetAbsoluteAngle (Position const &pos) const
float GetAbsoluteAngle (Position const *pos) const
float GetRelativeAngle (const Position *pos) const
float GetRelativeAngle (float x, float y) const
float ToAbsoluteAngle (float relAngle) const
void GetSinCos (float x, float y, float &vsin, float &vcos) const
bool IsInDist2d (float x, float y, float dist) const
bool IsInDist2d (const Position *pos, float dist) const
bool IsInDist (float x, float y, float z, float dist) const
bool IsInDist (const Position *pos, float dist) const
bool IsWithinBox (const Position &center, float xradius, float yradius, float zradius) const
bool HasInArc (float arcangle, const Position *pos, float targetRadius=0.0f) const
bool HasInLine (WorldObject const *target, float width) const
std::string ToString () const
Public Member Functions inherited from GridObject< GameObject >
bool IsInGrid () const
void AddToGrid (GridRefMgr< GameObject > &m)
void RemoveFromGrid ()
Private Member Functions
MotionTransport ()
void MoveToNextWaypoint ()
float CalculateSegmentPos (float perc)
bool TeleportTransport (uint32 newMapid, float x, float y, float z, float o)
void DelayedTeleportTransport ()
void UpdatePassengerPositions (PassengerSet &passengers)
void DoEventIfAny (KeyFrame const &node, bool departure)
bool IsMoving () const
Helpers to know if stop frame was reached.
void SetMoving (bool val)
Private Attributes
TransportTemplate const * _transportInfo
KeyFrameVec::const_iterator _currentFrame
KeyFrameVec::const_iterator _nextFrame
TimeTrackerSmall _positionChangeTimer
bool _isMoving
bool _pendingStop
bool _triggeredArrivalEvent
These are needed to properly control events triggering only once for each frame.
bool _triggeredDepartureEvent
PassengerSet _staticPassengers
std::mutex Lock
bool _passengersLoaded
bool _delayedTeleport
Friends
MotionTransport * TransportMgr::CreateTransport (uint32, ObjectGuid::LowType, Map *)
Additional Inherited Members
Public Types inherited from Transport
typedef std::set< WorldObject * > PassengerSet
Static Public Member Functions inherited from GameObject
static void SetGoArtKit (uint8 artkit, GameObject *go, ObjectGuid::LowType lowguid=0)
Static Public Member Functions inherited from Object
static ObjectGuid GetGUID (Object const *o)
Static Public Member Functions inherited from Position
static float NormalizeOrientation (float o)
Public Attributes inherited from GameObject
Loot loot
uint32 m_groupLootTimer
uint32 lootingGroupLowGUID
GameObjectModel * m_model
Public Attributes inherited from WorldObject
FlaggedValuesArray32< int32, uint32, StealthType, TOTAL_STEALTH_TYPES > m_stealth
FlaggedValuesArray32< int32, uint32, StealthType, TOTAL_STEALTH_TYPES > m_stealthDetect
FlaggedValuesArray32< int32, uint32, InvisibilityType, TOTAL_INVISIBILITY_TYPES > m_invisibility
FlaggedValuesArray32< int32, uint32, InvisibilityType, TOTAL_INVISIBILITY_TYPES > m_invisibilityDetect
FlaggedValuesArray32< int32, uint32, ServerSideVisibilityType, TOTAL_SERVERSIDE_VISIBILITY_TYPES > m_serverSideVisibility
FlaggedValuesArray32< int32, uint32, ServerSideVisibilityType, TOTAL_SERVERSIDE_VISIBILITY_TYPES > m_serverSideVisibilityDetect
uint32 LastUsedScriptID
MovementInfo m_movementInfo
Public Attributes inherited from Object
DataMap CustomData
Public Attributes inherited from WorldLocation
uint32 m_mapId
Public Attributes inherited from Position
float m_positionX = 0
float m_positionY = 0
float m_positionZ = 0
float m_orientation = 0
Static Public Attributes inherited from GameObject
static std::unordered_map< int, goEventFlag > gameObjectToEventFlag = { }
Protected Types inherited from GameObject
typedef std::map< uint32, ObjectGuid > ChairSlotAndUser
Protected Member Functions inherited from GameObject
bool AIM_Initialize ()
GameObjectModel * CreateModel ()
void UpdateModel ()
Protected Member Functions inherited from WorldObject
WorldObject (bool isWorldObject)
virtual void ProcessPositionDataChanged (PositionFullTerrainStatus const &data)
void SetLocationMapId (uint32 _mapId)
void SetLocationInstanceId (uint32 _instanceId)
virtual bool IsAlwaysDetectableFor (WorldObject const *) const
Protected Member Functions inherited from Object
Object ()
void _InitValues ()
void _Create (ObjectGuid::LowType guidlow, uint32 entry, HighGuid guidhigh)
std::string _ConcatFields (uint16 startIndex, uint16 size) const
void _LoadIntoDataField (std::string const &data, uint32 startOffset, uint32 count)
uint32 GetUpdateFieldData (Player const *target, uint32 *&flags) const
void BuildMovementUpdate (ByteBuffer *data, uint16 flags) const
void AddToObjectUpdateIfNeeded ()
Protected Member Functions inherited from MovableMapObject
MovableMapObject ()
Protected Member Functions inherited from TransportBase
TransportBase ()=default
virtual ~TransportBase ()=default
Static Protected Member Functions inherited from TransportBase
static void CalculatePassengerPosition (float &x, float &y, float &z, float *o, float transX, float transY, float transZ, float transO)
static void CalculatePassengerOffset (float &x, float &y, float &z, float *o, float transX, float transY, float transZ, float transO)
Protected Attributes inherited from Transport
PassengerSet _passengers
Protected Attributes inherited from GameObject
uint32 m_spellId
time_t m_respawnTime
uint32 m_respawnDelayTime
uint32 m_despawnDelay
Seconds m_despawnRespawnTime
LootState m_lootState
bool m_spawnedByDefault
uint32 m_cooldownTime
GuidList m_SkillupList
ObjectGuid m_ritualOwnerGUID
GuidSet m_unique_users
uint32 m_usetimes
ChairSlotAndUser ChairListSlots
ObjectGuid::LowType m_spawnId
For new or temporary gameobjects is 0 for saved it is lowguid.
GameObjectTemplate const * m_goInfo
GameObjectData const * m_goData
GameObjectValue m_goValue
bool m_allowModifyDestructibleBuilding
int64 m_packedRotation
G3D::Quat m_localRotation
Position m_stationaryPosition
ObjectGuid m_lootRecipient
ObjectGuid::LowType m_lootRecipientGroup
uint16 m_LootMode
uint32 m_lootGenerationTime
ObjectGuid m_linkedTrap
Protected Attributes inherited from WorldObject
std::string m_name
bool m_isActive
bool m_isVisibilityDistanceOverride
const bool m_isWorldObject
ZoneScript * m_zoneScript
uint32 _zoneId
uint32 _areaId
float _floorZ
bool _outdoors
LiquidData _liquidData
bool _updatePositionData
Transport * m_transport
Protected Attributes inherited from Object
uint16 m_objectType
TypeID m_objectTypeId
uint16 m_updateFlag
union {
int32 * m_int32Values
uint32 * m_uint32Values
float * m_floatValues
};
UpdateMask _changesMask
uint16 m_valuesCount
uint16 _fieldNotifyFlags
bool m_objectUpdated
Detailed Description
Definition at line 47 of file Transport.h.
Constructor & Destructor Documentation
MotionTransport()
MotionTransport::MotionTransport () private
Definition at line 34 of file Transport.cpp.
                                  : Transport(), _transportInfo(nullptr), _isMoving(true), _pendingStop(false), _triggeredArrivalEvent(false), _triggeredDepartureEvent(false), _passengersLoaded(false), _delayedTeleport(false)
 {
     m_updateFlag = UPDATEFLAG_TRANSPORT | UPDATEFLAG_LOWGUID | UPDATEFLAG_STATIONARY_POSITION | UPDATEFLAG_ROTATION;
 }
References Object::m_updateFlag, UPDATEFLAG_LOWGUID, UPDATEFLAG_ROTATION, UPDATEFLAG_STATIONARY_POSITION, and UPDATEFLAG_TRANSPORT.
~MotionTransport()
MotionTransport::~MotionTransport () override
Definition at line 39 of file Transport.cpp.
 {
     ASSERT(_passengers.empty());
     UnloadStaticPassengers();
 }
References Transport::_passengers, ASSERT, and UnloadStaticPassengers().
Member Function Documentation
AddPassenger()
void MotionTransport::AddPassenger (WorldObject * passenger, bool withAll = false) override virtual
Implements Transport.
Definition at line 262 of file Transport.cpp.
 {
     std::lock_guard<std::mutex> guard(Lock);
     if (_passengers.insert(passenger).second)
     {
         if (Player* plr = passenger->ToPlayer())
             sScriptMgr->OnAddPassenger(ToTransport(), plr);
         if (withAll)
         {
             if (Transport* t = passenger->GetTransport()) // SHOULD NEVER HAPPEN
                 t->RemovePassenger(passenger, false);
             float x, y, z, o;
             passenger->GetPosition(x, y, z, o);
             CalculatePassengerOffset(x, y, z, &o);
             passenger->SetTransport(this);
             passenger->m_movementInfo.flags |= MOVEMENTFLAG_ONTRANSPORT;
             passenger->m_movementInfo.transport.guid = GetGUID();
             passenger->m_movementInfo.transport.pos.Relocate(x, y, z, o);
             if (passenger->ToUnit())
             {
                 passenger->ToUnit()->AddUnitState(UNIT_STATE_IGNORE_PATHFINDING);
             }
         }
     }
 }
References Transport::_passengers, Unit::AddUnitState(), Transport::CalculatePassengerOffset(), MovementInfo::flags, Object::GetGUID(), Position::GetPosition(), WorldObject::GetTransport(), MovementInfo::TransportInfo::guid, Lock, WorldObject::m_movementInfo, MOVEMENTFLAG_ONTRANSPORT, MovementInfo::TransportInfo::pos, Position::Relocate(), WorldObject::SetTransport(), sScriptMgr, Object::ToPlayer(), GameObject::ToTransport(), Object::ToUnit(), MovementInfo::transport, and UNIT_STATE_IGNORE_PATHFINDING.
Referenced by Battleground::AddCreature(), and PassengerController::SummonCreatures().
BuildUpdate()
void MotionTransport::BuildUpdate (UpdateDataMapType & data_map, UpdatePlayerSet &) override virtual
Reimplemented from WorldObject.
Definition at line 124 of file Transport.cpp.
 {
     Map::PlayerList const& players = GetMap()->GetPlayers();
     if (players.isEmpty())
         return;
     for (Map::PlayerList::const_iterator itr = players.begin(); itr != players.end(); ++itr)
         BuildFieldsUpdate(itr->GetSource(), data_map);
     ClearUpdateMask(true);
 }
References MapRefMgr::begin(), Object::BuildFieldsUpdate(), Object::ClearUpdateMask(), MapRefMgr::end(), WorldObject::GetMap(), Map::GetPlayers(), and LinkedListHead::isEmpty().
CalculateSegmentPos()
float MotionTransport::CalculateSegmentPos (float perc) private
Definition at line 473 of file Transport.cpp.
 {
     KeyFrame const& frame = *_currentFrame;
     const float speed = float(m_goInfo->moTransport.moveSpeed);
     const float accel = float(m_goInfo->moTransport.accelRate);
     float timeSinceStop = frame.TimeFrom + (now - (1.0f / IN_MILLISECONDS) * frame.DepartureTime);
     float timeUntilStop = frame.TimeTo - (now - (1.0f / IN_MILLISECONDS) * frame.DepartureTime);
     float segmentPos, dist;
     float accelTime = _transportInfo->accelTime;
     float accelDist = _transportInfo->accelDist;
     // calculate from nearest stop, less confusing calculation...
     if (timeSinceStop < timeUntilStop)
     {
         if (timeSinceStop < accelTime)
             dist = 0.5f * accel * timeSinceStop * timeSinceStop;
         else
             dist = accelDist + (timeSinceStop - accelTime) * speed;
         segmentPos = dist - frame.DistSinceStop;
     }
     else
     {
         if (timeUntilStop < _transportInfo->accelTime)
             dist = 0.5f * accel * timeUntilStop * timeUntilStop;
         else
             dist = accelDist + (timeUntilStop - accelTime) * speed;
         segmentPos = frame.DistUntilStop - dist;
     }
     return segmentPos / frame.NextDistFromPrev;
 }
References _currentFrame, _transportInfo, TransportTemplate::accelDist, TransportTemplate::accelTime, KeyFrame::DepartureTime, KeyFrame::DistSinceStop, KeyFrame::DistUntilStop, IN_MILLISECONDS, GameObject::m_goInfo, GameObjectTemplate::moTransport, KeyFrame::NextDistFromPrev, KeyFrame::TimeFrom, and KeyFrame::TimeTo.
Referenced by Update().
CleanupsBeforeDelete()
void MotionTransport::CleanupsBeforeDelete (bool finalCleanup = true) override virtual
Reimplemented from GameObject.
Definition at line 109 of file Transport.cpp.
 {
     UnloadStaticPassengers();
     while (!_passengers.empty())
     {
         WorldObject* obj = *_passengers.begin();
         RemovePassenger(obj);
         obj->SetTransport(nullptr);
         obj->m_movementInfo.transport.Reset();
         obj->m_movementInfo.RemoveMovementFlag(MOVEMENTFLAG_ONTRANSPORT);
     }
     GameObject::CleanupsBeforeDelete(finalCleanup);
 }
References Transport::_passengers, GameObject::CleanupsBeforeDelete(), WorldObject::m_movementInfo, MOVEMENTFLAG_ONTRANSPORT, MovementInfo::RemoveMovementFlag(), RemovePassenger(), MovementInfo::TransportInfo::Reset(), WorldObject::SetTransport(), MovementInfo::transport, and UnloadStaticPassengers().
CreateGOPassenger()
GameObject * MotionTransport::CreateGOPassenger (ObjectGuid::LowType guid, GameObjectData const * data)
Definition at line 364 of file Transport.cpp.
 {
     Map* map = GetMap();
     GameObject* go = new GameObject();
     ASSERT(!sObjectMgr->IsGameObjectStaticTransport(data->id));
     if (!go->LoadGameObjectFromDB(guid, map, false))
     {
         delete go;
         return nullptr;
     }
     float x = data->posX;
     float y = data->posY;
     float z = data->posZ;
     float o = data->orientation;
     go->SetTransport(this);
     go->m_movementInfo.transport.guid = GetGUID();
     go->m_movementInfo.transport.pos.Relocate(x, y, z, o);
     CalculatePassengerPosition(x, y, z, &o);
     go->Relocate(x, y, z, o);
     if (!go->IsPositionValid())
     {
         LOG_ERROR("entities.transport", "GameObject (%s) not created. Suggested coordinates aren't valid (X: %f Y: %f)",
             go->GetGUID().ToString().c_str(), go->GetPositionX(), go->GetPositionY());
         delete go;
         return nullptr;
     }
     if (!map->AddToMap(go))
     {
         delete go;
         return nullptr;
     }
     _staticPassengers.insert(go);
     return go;
 }
References _staticPassengers, Map::AddToMap(), ASSERT, Transport::CalculatePassengerPosition(), GameObject::GameObject(), Object::GetGUID(), WorldObject::GetMap(), Position::GetPositionX(), Position::GetPositionY(), MovementInfo::TransportInfo::guid, GameObjectData::id, Position::IsPositionValid(), GameObject::LoadGameObjectFromDB(), LOG_ERROR, WorldObject::m_movementInfo, GameObjectData::orientation, MovementInfo::TransportInfo::pos, GameObjectData::posX, GameObjectData::posY, GameObjectData::posZ, Position::Relocate(), WorldObject::SetTransport(), sObjectMgr, ObjectGuid::ToString(), and MovementInfo::transport.
Referenced by LoadStaticPassengers().
CreateMoTrans()
bool MotionTransport::CreateMoTrans (ObjectGuid::LowType guidlow, uint32 entry, uint32 mapid, float x, float y, float z, float ang, uint32 animprogress)
Definition at line 45 of file Transport.cpp.
 {
     Relocate(x, y, z, ang);
     if (!IsPositionValid())
     {
         LOG_ERROR("entities.transport", "Transport (GUID: %u) not created. Suggested coordinates isn't valid (X: %f Y: %f)",
                        guidlow, x, y);
         return false;
     }
     Object::_Create(guidlow, 0, HighGuid::Mo_Transport);
     GameObjectTemplate const* goinfo = sObjectMgr->GetGameObjectTemplate(entry);
     if (!goinfo)
     {
         LOG_ERROR("entities.transport", "Transport not created: entry in `gameobject_template` not found, guidlow: %u map: %u  (X: %f Y: %f Z: %f) ang: %f", guidlow, mapid, x, y, z, ang);
         return false;
     }
     m_goInfo = goinfo;
     TransportTemplate const* tInfo = sTransportMgr->GetTransportTemplate(entry);
     if (!tInfo)
     {
         LOG_ERROR("entities.transport", "Transport %u (name: %s) will not be created, missing `transport_template` entry.", entry, goinfo->name.c_str());
         return false;
     }
     _transportInfo = tInfo;
     // initialize waypoints
     _nextFrame = tInfo->keyFrames.begin();
     _currentFrame = _nextFrame++;
     _triggeredArrivalEvent = false;
     _triggeredDepartureEvent = false;
     if (GameObjectTemplateAddon const* addon = GetTemplateAddon())
     {
         SetUInt32Value(GAMEOBJECT_FACTION, addon->faction);
         SetUInt32Value(GAMEOBJECT_FLAGS, addon->flags);
     }
     SetObjectScale(goinfo->size);
     SetPathProgress(0);
     SetPeriod(tInfo->pathTime);
     SetEntry(goinfo->entry);
     SetDisplayId(goinfo->displayId);
     SetGoState(!goinfo->moTransport.canBeStopped ? GO_STATE_READY : GO_STATE_ACTIVE);
     SetGoType(GAMEOBJECT_TYPE_MO_TRANSPORT);
     SetGoAnimProgress(animprogress);
     SetName(goinfo->name);
     // pussywizard: no WorldRotation for MotionTransports
     SetLocalRotation(G3D::Quat());
     // pussywizard: no PathRotation for MotionTransports
     SetTransportPathRotation(0.0f, 0.0f, 0.0f, 1.0f);
     m_model = CreateModel();
     return true;
 }
References Object::_Create(), _currentFrame, _nextFrame, _transportInfo, _triggeredArrivalEvent, _triggeredDepartureEvent, GameObject::CreateModel(), GameObjectTemplate::displayId, GameObjectTemplate::entry, GAMEOBJECT_FACTION, GAMEOBJECT_FLAGS, GAMEOBJECT_TYPE_MO_TRANSPORT, GameObject::GetTemplateAddon(), GO_STATE_ACTIVE, GO_STATE_READY, Position::IsPositionValid(), TransportTemplate::keyFrames, LOG_ERROR, GameObject::m_goInfo, GameObject::m_model, Mo_Transport, GameObjectTemplate::moTransport, GameObjectTemplate::name, TransportTemplate::pathTime, Position::Relocate(), GameObject::SetDisplayId(), Object::SetEntry(), GameObject::SetGoAnimProgress(), GameObject::SetGoState(), GameObject::SetGoType(), GameObject::SetLocalRotation(), WorldObject::SetName(), Object::SetObjectScale(), Transport::SetPathProgress(), SetPeriod(), GameObject::SetTransportPathRotation(), Object::SetUInt32Value(), GameObjectTemplate::size, sObjectMgr, and sTransportMgr.
Referenced by TransportMgr::CreateTransport().
CreateNPCPassenger()
Creature * MotionTransport::CreateNPCPassenger (ObjectGuid::LowType guid, CreatureData const * data)
@HACK - transport models are not added to map's dynamic LoS calculations because the current GameObjectModel cannot be moved without recreating
Definition at line 316 of file Transport.cpp.
 {
     Map* map = GetMap();
     Creature* creature = new Creature();
     if (!creature->LoadCreatureFromDB(guid, map, false))
     {
         delete creature;
         return nullptr;
     }
     float x = data->posX;
     float y = data->posY;
     float z = data->posZ;
     float o = data->orientation;
     creature->SetTransport(this);
     creature->AddUnitMovementFlag(MOVEMENTFLAG_ONTRANSPORT);
     creature->m_movementInfo.transport.guid = GetGUID();
     creature->m_movementInfo.transport.pos.Relocate(x, y, z, o);
     CalculatePassengerPosition(x, y, z, &o);
     creature->Relocate(x, y, z, o);
     creature->SetHomePosition(creature->GetPositionX(), creature->GetPositionY(), creature->GetPositionZ(), creature->GetOrientation());
     creature->SetTransportHomePosition(creature->m_movementInfo.transport.pos);
     creature->AddUnitState(UNIT_STATE_IGNORE_PATHFINDING);
     if (!creature->IsPositionValid())
     {
         LOG_ERROR("entities.transport", "Creature (%s) not created. Suggested coordinates aren't valid (X: %f Y: %f)",
             creature->GetGUID().ToString().c_str(), creature->GetPositionX(), creature->GetPositionY());
         delete creature;
         return nullptr;
     }
     if (!map->AddToMap(creature))
     {
         delete creature;
         return nullptr;
     }
     _staticPassengers.insert(creature);
     sScriptMgr->OnAddCreaturePassenger(this, creature);
     return creature;
 }
References _staticPassengers, Map::AddToMap(), Unit::AddUnitMovementFlag(), Unit::AddUnitState(), Transport::CalculatePassengerPosition(), Object::GetGUID(), WorldObject::GetMap(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), MovementInfo::TransportInfo::guid, Position::IsPositionValid(), Creature::LoadCreatureFromDB(), LOG_ERROR, WorldObject::m_movementInfo, MOVEMENTFLAG_ONTRANSPORT, CreatureData::orientation, MovementInfo::TransportInfo::pos, CreatureData::posX, CreatureData::posY, CreatureData::posZ, Position::Relocate(), Creature::SetHomePosition(), WorldObject::SetTransport(), Creature::SetTransportHomePosition(), sScriptMgr, ObjectGuid::ToString(), MovementInfo::transport, and UNIT_STATE_IGNORE_PATHFINDING.
Referenced by LoadStaticPassengers().
DelayedTeleportTransport()
void MotionTransport::DelayedTeleportTransport () private
Definition at line 534 of file Transport.cpp.
 {
     if (!_delayedTeleport)
         return;
     _delayedTeleport = false;
     uint32 newMapId = _nextFrame->Node->mapid;
     float x = _nextFrame->Node->x,
           y = _nextFrame->Node->y,
           z = _nextFrame->Node->z,
           o = _nextFrame->InitialOrientation;
     PassengerSet _passengersCopy = _passengers;
     for (PassengerSet::iterator itr = _passengersCopy.begin(); itr != _passengersCopy.end(); )
     {
         WorldObject* obj = (*itr++);
         if (_passengers.find(obj) == _passengers.end())
             continue;
         switch (obj->GetTypeId())
         {
             case TYPEID_UNIT:
                 _passengers.erase(obj);
                 if (!obj->ToCreature()->IsPet())
                     obj->ToCreature()->DespawnOrUnsummon();
                 break;
             case TYPEID_GAMEOBJECT:
                 _passengers.erase(obj);
                 obj->ToGameObject()->Delete();
                 break;
             case TYPEID_DYNAMICOBJECT:
                 _passengers.erase(obj);
                 if (Unit* caster = obj->ToDynObject()->GetCaster())
                     if (Spell* s = caster->GetCurrentSpell(CURRENT_CHANNELED_SPELL))
                         if (obj->ToDynObject()->GetSpellId() == s->GetSpellInfo()->Id)
{
                             s->SendChannelUpdate(0);
                             s->SendInterrupted(0);
                             caster->RemoveOwnedAura(s->GetSpellInfo()->Id, caster->GetGUID());
                         }
                 obj->AddObjectToRemoveList();
                 break;
             case TYPEID_PLAYER:
                 {
                     float destX, destY, destZ, destO;
                     obj->m_movementInfo.transport.pos.GetPosition(destX, destY, destZ, destO);
                     TransportBase::CalculatePassengerPosition(destX, destY, destZ, &destO, x, y, z, o);
                     if (!obj->ToPlayer()->TeleportTo(newMapId, destX, destY, destZ, destO, TELE_TO_NOT_LEAVE_TRANSPORT))
                         _passengers.erase(obj);
                 }
                 break;
             default:
                 break;
         }
     }
     Map* newMap = sMapMgr->CreateBaseMap(newMapId);
     GetMap()->RemoveFromMap<MotionTransport>(this, false);
     newMap->LoadGrid(x, y); // xinef: load before adding passengers to new map
     SetMap(newMap);
     Relocate(x, y, z, o);
     GetMap()->AddToMap<MotionTransport>(this);
     LoadStaticPassengers();
 }
References _delayedTeleport, _nextFrame, Transport::_passengers, WorldObject::AddObjectToRemoveList(), Map::AddToMap(), TransportBase::CalculatePassengerPosition(), CURRENT_CHANNELED_SPELL, GameObject::Delete(), Creature::DespawnOrUnsummon(), DynamicObject::GetCaster(), WorldObject::GetMap(), Position::GetPosition(), DynamicObject::GetSpellId(), Object::GetTypeId(), Unit::IsPet(), Map::LoadGrid(), LoadStaticPassengers(), WorldObject::m_movementInfo, MovementInfo::TransportInfo::pos, Position::Relocate(), Map::RemoveFromMap(), WorldObject::SetMap(), sMapMgr, TELE_TO_NOT_LEAVE_TRANSPORT, Player::TeleportTo(), Object::ToCreature(), Object::ToDynObject(), Object::ToGameObject(), Object::ToPlayer(), MovementInfo::transport, TYPEID_DYNAMICOBJECT, TYPEID_GAMEOBJECT, TYPEID_PLAYER, and TYPEID_UNIT.
Referenced by DelayedUpdate().
DelayedUpdate()
void MotionTransport::DelayedUpdate (uint32 diff)
Definition at line 238 of file Transport.cpp.
 {
     if (GetKeyFrames().size() <= 1)
         return;
     DelayedTeleportTransport();
 }
References DelayedTeleportTransport(), and GetKeyFrames().
Referenced by Map::DelayedUpdate().
DoEventIfAny()
void MotionTransport::DoEventIfAny (KeyFrame const & node, bool departure) private
Definition at line 654 of file Transport.cpp.
 {
     if (uint32 eventid = departure ? node.Node->departureEventID : node.Node->arrivalEventID)
     {
         //TC_LOG_DEBUG("maps.script", "Taxi %s event %u of node %u of %s path", departure ? "departure" : "arrival", eventid, node.Node->index, GetName().c_str());
         GetMap()->ScriptsStart(sEventScripts, eventid, this, this);
         EventInform(eventid);
     }
 }
References TaxiPathNodeEntry::arrivalEventID, TaxiPathNodeEntry::departureEventID, GameObject::EventInform(), WorldObject::GetMap(), KeyFrame::Node, Map::ScriptsStart(), and sEventScripts.
Referenced by Update().
EnableMovement()
void MotionTransport::EnableMovement (bool enabled)
Definition at line 453 of file Transport.cpp.
 {
     if (!GetGOInfo()->moTransport.canBeStopped)
         return;
     _pendingStop = !enabled;
 }
References _pendingStop, GameObjectTemplate::canBeStopped, and GameObject::GetGOInfo().
Referenced by npc_gunship::npc_gunshipAI::JustDied(), BattlegroundIC::SetupBattleground(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::sGossipSelect(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::sGossipSelect(), and instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::Update().
GetKeyFrames()
KeyFrameVec const& MotionTransport::GetKeyFrames () const inline
Definition at line 74 of file Transport.h.
 { return _transportInfo->keyFrames; }
References _transportInfo, and TransportTemplate::keyFrames.
Referenced by DelayedUpdate(), MoveToNextWaypoint(), and Update().
GetPeriod()
uint32 MotionTransport::GetPeriod () const inline
Definition at line 78 of file Transport.h.
 { return GetUInt32Value(GAMEOBJECT_LEVEL); }
References GAMEOBJECT_LEVEL, and Object::GetUInt32Value().
Referenced by Update().
GetStaticPassengers()
PassengerSet const& MotionTransport::GetStaticPassengers () const inline
Definition at line 68 of file Transport.h.
 { return _staticPassengers; }
References _staticPassengers.
GetTransportTemplate()
TransportTemplate const* MotionTransport::GetTransportTemplate () const inline
Definition at line 76 of file Transport.h.
 { return _transportInfo; }
References _transportInfo.
IsMoving()
bool MotionTransport::IsMoving () const inline private
Helpers to know if stop frame was reached.
Definition at line 90 of file Transport.h.
 { return _isMoving; }
References _isMoving.
Referenced by Update().
LoadStaticPassengers()
void MotionTransport::LoadStaticPassengers ()
Definition at line 405 of file Transport.cpp.
 {
     if (PassengersLoaded())
         return;
     SetPassengersLoaded(true);
     if (uint32 mapId = GetGOInfo()->moTransport.mapID)
     {
         CellObjectGuidsMap const& cells = sObjectMgr->GetMapObjectGuids(mapId, GetMap()->GetSpawnMode());
         CellGuidSet::const_iterator guidEnd;
         for (CellObjectGuidsMap::const_iterator cellItr = cells.begin(); cellItr != cells.end(); ++cellItr)
         {
             // Creatures on transport
             guidEnd = cellItr->second.creatures.end();
             for (CellGuidSet::const_iterator guidItr = cellItr->second.creatures.begin(); guidItr != guidEnd; ++guidItr)
                 CreateNPCPassenger(*guidItr, sObjectMgr->GetCreatureData(*guidItr));
             // GameObjects on transport
             guidEnd = cellItr->second.gameobjects.end();
             for (CellGuidSet::const_iterator guidItr = cellItr->second.gameobjects.begin(); guidItr != guidEnd; ++guidItr)
                 CreateGOPassenger(*guidItr, sObjectMgr->GetGOData(*guidItr));
         }
     }
 }
References CreateGOPassenger(), CreateNPCPassenger(), GameObject::GetGOInfo(), WorldObject::GetMap(), GameObjectTemplate::mapID, PassengersLoaded(), SetPassengersLoaded(), and sObjectMgr.
Referenced by DelayedTeleportTransport(), Update(), and UpdatePosition().
MoveToNextWaypoint()
void MotionTransport::MoveToNextWaypoint () private
Definition at line 461 of file Transport.cpp.
 {
     // Clear events flagging
     _triggeredArrivalEvent = false;
     _triggeredDepartureEvent = false;
     // Set frames
     _currentFrame = _nextFrame++;
     if (_nextFrame == GetKeyFrames().end())
         _nextFrame = GetKeyFrames().begin();
 }
References _currentFrame, _nextFrame, _triggeredArrivalEvent, _triggeredDepartureEvent, and GetKeyFrames().
Referenced by Update().
PassengersLoaded()
bool MotionTransport::PassengersLoaded () const inline
Definition at line 72 of file Transport.h.
 { return _passengersLoaded; }
References _passengersLoaded.
Referenced by LoadStaticPassengers().
RemovePassenger()
void MotionTransport::RemovePassenger (WorldObject * passenger, bool withAll = false) override virtual
Implements Transport.
Definition at line 291 of file Transport.cpp.
 {
     std::lock_guard<std::mutex> guard(Lock);
     if (_passengers.erase(passenger) || _staticPassengers.erase(passenger))
     {
         if (Player* plr = passenger->ToPlayer())
         {
             sScriptMgr->OnRemovePassenger(ToTransport(), plr);
             plr->SetFallInformation(time(nullptr), plr->GetPositionZ());
         }
         if (withAll)
         {
             passenger->SetTransport(nullptr);
             passenger->m_movementInfo.flags &= ~MOVEMENTFLAG_ONTRANSPORT;
             passenger->m_movementInfo.transport.guid.Clear();
             passenger->m_movementInfo.transport.pos.Relocate(0.0f, 0.0f, 0.0f, 0.0f);
             if (passenger->ToUnit())
             {
                 passenger->ToUnit()->ClearUnitState(UNIT_STATE_IGNORE_PATHFINDING);
             }
         }
     }
 }
References Transport::_passengers, _staticPassengers, ObjectGuid::Clear(), Unit::ClearUnitState(), MovementInfo::flags, MovementInfo::TransportInfo::guid, Lock, WorldObject::m_movementInfo, MOVEMENTFLAG_ONTRANSPORT, MovementInfo::TransportInfo::pos, Position::Relocate(), WorldObject::SetTransport(), sScriptMgr, Object::ToPlayer(), GameObject::ToTransport(), Object::ToUnit(), MovementInfo::transport, and UNIT_STATE_IGNORE_PATHFINDING.
Referenced by CleanupsBeforeDelete().
SetMoving()
void MotionTransport::SetMoving (bool val) inline private
Definition at line 91 of file Transport.h.
 { _isMoving = val; }
References _isMoving.
Referenced by Update().
SetPassengersLoaded()
void MotionTransport::SetPassengersLoaded (bool loaded) inline
Definition at line 71 of file Transport.h.
 { _passengersLoaded = loaded; }
References _passengersLoaded.
Referenced by LoadStaticPassengers(), and UnloadStaticPassengers().
SetPeriod()
void MotionTransport::SetPeriod (uint32 period) inline
Definition at line 79 of file Transport.h.
 { SetUInt32Value(GAMEOBJECT_LEVEL, period); }
References GAMEOBJECT_LEVEL, and Object::SetUInt32Value().
Referenced by CreateMoTrans().
TeleportTransport()
bool MotionTransport::TeleportTransport (uint32 newMapid, float x, float y, float z, float o) private
Definition at line 504 of file Transport.cpp.
 {
     Map const* oldMap = GetMap();
     if (oldMap->GetId() != newMapid)
     {
         _delayedTeleport = true;
         UnloadStaticPassengers();
         return true;
     }
     else
     {
         // Teleport players, they need to know it
         for (PassengerSet::iterator itr = _passengers.begin(); itr != _passengers.end(); ++itr)
         {
             if ((*itr)->GetTypeId() == TYPEID_PLAYER)
             {
                 float destX, destY, destZ, destO;
                 (*itr)->m_movementInfo.transport.pos.GetPosition(destX, destY, destZ, destO);
                 TransportBase::CalculatePassengerPosition(destX, destY, destZ, &destO, x, y, z, o);
                 (*itr)->ToUnit()->NearTeleportTo(destX, destY, destZ, destO);
             }
         }
         UpdatePosition(x, y, z, o);
         return false;
     }
 }
References _delayedTeleport, Transport::_passengers, TransportBase::CalculatePassengerPosition(), Map::GetId(), WorldObject::GetMap(), TYPEID_PLAYER, UnloadStaticPassengers(), and UpdatePosition().
Referenced by Update().
UnloadNonStaticPassengers()
void MotionTransport::UnloadNonStaticPassengers ()
Definition at line 439 of file Transport.cpp.
 {
     for (PassengerSet::iterator itr = _passengers.begin(); itr != _passengers.end(); )
     {
         if ((*itr)->GetTypeId() == TYPEID_PLAYER)
         {
             ++itr;
             continue;
         }
         PassengerSet::iterator itr2 = itr++;
         (*itr2)->AddObjectToRemoveList();
     }
 }
References Transport::_passengers, and TYPEID_PLAYER.
Referenced by ResetEncounterEvent::Execute().
UnloadStaticPassengers()
void MotionTransport::UnloadStaticPassengers ()
Definition at line 429 of file Transport.cpp.
 {
     SetPassengersLoaded(false);
     while (!_staticPassengers.empty())
     {
         WorldObject* obj = *_staticPassengers.begin();
         obj->AddObjectToRemoveList();   // also removes from _staticPassengers
     }
 }
References _staticPassengers, WorldObject::AddObjectToRemoveList(), and SetPassengersLoaded().
Referenced by CleanupsBeforeDelete(), TeleportTransport(), and ~MotionTransport().
Update()
void MotionTransport::Update (uint32 diff) override virtual
Reimplemented from GameObject.
Definition at line 136 of file Transport.cpp.
 {
     uint32 const positionUpdateDelay = 1;
     if (AI())
         AI()->UpdateAI(diff);
     else if (!AIM_Initialize())
         LOG_ERROR("entities.transport", "Could not initialize GameObjectAI for Transport");
     if (GetKeyFrames().size() <= 1)
         return;
     if (IsMoving() || !_pendingStop)
         SetPathProgress(GetPathProgress() + diff);
     uint32 timer = GetPathProgress() % GetPeriod();
     // Set current waypoint
     // Desired outcome: _currentFrame->DepartureTime < timer < _nextFrame->ArriveTime
     // ... arrive | ... delay ... | departure
     //      event /         event /
     for (;;)
     {
         if (timer >= _currentFrame->ArriveTime)
         {
             if (!_triggeredArrivalEvent)
             {
                 DoEventIfAny(*_currentFrame, false);
                 _triggeredArrivalEvent = true;
             }
             if (timer < _currentFrame->DepartureTime)
             {
                 SetMoving(false);
                 if (_pendingStop && GetGoState() != GO_STATE_READY)
                 {
                     SetGoState(GO_STATE_READY);
                     SetPathProgress(GetPathProgress() / GetPeriod());
                     SetPathProgress(GetPathProgress() * GetPeriod());
                     SetPathProgress(GetPathProgress() + _currentFrame->ArriveTime);
                 }
                 break;  // its a stop frame and we are waiting
             }
         }
         if (timer >= _currentFrame->DepartureTime && !_triggeredDepartureEvent)
         {
             DoEventIfAny(*_currentFrame, true); // departure event
             _triggeredDepartureEvent = true;
         }
         // not waiting anymore
         SetMoving(true);
         // Enable movement
         if (GetGOInfo()->moTransport.canBeStopped)
             SetGoState(GO_STATE_ACTIVE);
         if (timer >= _currentFrame->DepartureTime && timer < _currentFrame->NextArriveTime)
             break;  // found current waypoint
         MoveToNextWaypoint();
         sScriptMgr->OnRelocate(this, _currentFrame->Node->index, _currentFrame->Node->mapid, _currentFrame->Node->x, _currentFrame->Node->y, _currentFrame->Node->z);
         //TC_LOG_DEBUG("entities.transport", "Transport %u (%s) moved to node %u %u %f %f %f", GetEntry(), GetName().c_str(), _currentFrame->Node->index, _currentFrame->Node->mapid, _currentFrame->Node->x, _currentFrame->Node->y, _currentFrame->Node->z);
         // Departure event
         if (_currentFrame->IsTeleportFrame())
             if (TeleportTransport(_nextFrame->Node->mapid, _nextFrame->Node->x, _nextFrame->Node->y, _nextFrame->Node->z, _nextFrame->InitialOrientation))
                 return; // Update more in new map thread
     }
     // Set position
     _positionChangeTimer.Update(diff);
     if (_positionChangeTimer.Passed())
     {
         _positionChangeTimer.Reset(positionUpdateDelay);
         if (IsMoving())
         {
             float t = CalculateSegmentPos(float(timer) * 0.001f);
             G3D::Vector3 pos, dir;
             _currentFrame->Spline->evaluate_percent(_currentFrame->Index, t, pos);
             _currentFrame->Spline->evaluate_derivative(_currentFrame->Index, t, dir);
             UpdatePosition(pos.x, pos.y, pos.z, NormalizeOrientation(atan2(dir.y, dir.x) + M_PI));
         }
         else
         {
             /* There are four possible scenarios that trigger loading/unloading passengers:
               1. transport moves from inactive to active grid
               2. the grid that transport is currently in becomes active
               3. transport moves from active to inactive grid
               4. the grid that transport is currently in unloads
             */
             if (_staticPassengers.empty() && GetMap()->IsGridLoaded(GetPositionX(), GetPositionY())) // 2.
                 LoadStaticPassengers();
         }
     }
     sScriptMgr->OnTransportUpdate(this, diff);
 }
References _currentFrame, _nextFrame, _pendingStop, _positionChangeTimer, _staticPassengers, _triggeredArrivalEvent, _triggeredDepartureEvent, GameObject::AI(), GameObject::AIM_Initialize(), CalculateSegmentPos(), GameObjectTemplate::canBeStopped, DoEventIfAny(), GameObject::GetGOInfo(), GameObject::GetGoState(), GetKeyFrames(), WorldObject::GetMap(), Transport::GetPathProgress(), GetPeriod(), Position::GetPositionX(), Position::GetPositionY(), GO_STATE_ACTIVE, GO_STATE_READY, IsMoving(), LoadStaticPassengers(), LOG_ERROR, MoveToNextWaypoint(), Position::NormalizeOrientation(), TimeTrackerSmall::Passed(), TimeTrackerSmall::Reset(), GameObject::SetGoState(), SetMoving(), Transport::SetPathProgress(), sScriptMgr, TeleportTransport(), TimeTrackerSmall::Update(), GameObjectAI::UpdateAI(), and UpdatePosition().
Referenced by Map::Update().
UpdatePassengerPositions()
void MotionTransport::UpdatePassengerPositions (PassengerSet & passengers) private
Definition at line 603 of file Transport.cpp.
 {
     for (PassengerSet::iterator itr = passengers.begin(); itr != passengers.end(); ++itr)
     {
         WorldObject* passenger = *itr;
         // transport teleported but passenger not yet (can happen for players)
         if (passenger->GetMap() != GetMap())
             continue;
         // if passenger is on vehicle we have to assume the vehicle is also on transport and its the vehicle that will be updating its passengers
         if (Unit* unit = passenger->ToUnit())
             if (unit->GetVehicle())
                 continue;
         // Do not use Unit::UpdatePosition here, we don't want to remove auras as if regular movement occurred
         float x, y, z, o;
         passenger->m_movementInfo.transport.pos.GetPosition(x, y, z, o);
         CalculatePassengerPosition(x, y, z, &o);
         // check if position is valid
         if (!Acore::IsValidMapCoord(x, y, z))
             continue;
         switch (passenger->GetTypeId())
         {
             case TYPEID_UNIT:
                 {
                     Creature* creature = passenger->ToCreature();
                     GetMap()->CreatureRelocation(creature, x, y, z, o);
                     creature->GetTransportHomePosition(x, y, z, o);
                     CalculatePassengerPosition(x, y, z, &o);
                     creature->SetHomePosition(x, y, z, o);
                 }
                 break;
             case TYPEID_PLAYER:
                 if (passenger->IsInWorld())
                     GetMap()->PlayerRelocation(passenger->ToPlayer(), x, y, z, o);
                 break;
             case TYPEID_GAMEOBJECT:
                 GetMap()->GameObjectRelocation(passenger->ToGameObject(), x, y, z, o);
                 break;
             case TYPEID_DYNAMICOBJECT:
                 GetMap()->DynamicObjectRelocation(passenger->ToDynObject(), x, y, z, o);
                 break;
             default:
                 break;
         }
     }
 }
References Transport::CalculatePassengerPosition(), Map::CreatureRelocation(), Map::DynamicObjectRelocation(), Map::GameObjectRelocation(), WorldObject::GetMap(), Position::GetPosition(), Creature::GetTransportHomePosition(), Object::GetTypeId(), Object::IsInWorld(), Acore::IsValidMapCoord(), WorldObject::m_movementInfo, Map::PlayerRelocation(), MovementInfo::TransportInfo::pos, Creature::SetHomePosition(), Object::ToCreature(), Object::ToDynObject(), Object::ToGameObject(), Object::ToPlayer(), Object::ToUnit(), MovementInfo::transport, TYPEID_DYNAMICOBJECT, TYPEID_GAMEOBJECT, TYPEID_PLAYER, and TYPEID_UNIT.
Referenced by UpdatePosition().
UpdatePosition()
void MotionTransport::UpdatePosition (float x, float y, float z, float o)
Definition at line 246 of file Transport.cpp.
 {
     if (!GetMap()->IsGridLoaded(x, y)) // pussywizard: should not happen, but just in case
         GetMap()->LoadGrid(x, y);
     Relocate(x, y, z, o);
     UpdateModelPosition();
     UpdatePassengerPositions(_passengers);
     if (_staticPassengers.empty())
         LoadStaticPassengers();
     else
         UpdatePassengerPositions(_staticPassengers);
 }
References Transport::_passengers, _staticPassengers, WorldObject::GetMap(), Map::LoadGrid(), LoadStaticPassengers(), Position::Relocate(), GameObject::UpdateModelPosition(), and UpdatePassengerPositions().
Referenced by TeleportTransport(), and Update().
Friends And Related Function Documentation
TransportMgr::CreateTransport
MotionTransport* TransportMgr::CreateTransport (uint32 , ObjectGuid::LowType , Map *) friend
Member Data Documentation
_currentFrame
KeyFrameVec::const_iterator MotionTransport::_currentFrame private
Definition at line 94 of file Transport.h.
Referenced by CalculateSegmentPos(), CreateMoTrans(), MoveToNextWaypoint(), and Update().
_delayedTeleport
bool MotionTransport::_delayedTeleport private
Definition at line 107 of file Transport.h.
Referenced by DelayedTeleportTransport(), and TeleportTransport().
_isMoving
bool MotionTransport::_isMoving private
Definition at line 97 of file Transport.h.
Referenced by IsMoving(), and SetMoving().
_nextFrame
KeyFrameVec::const_iterator MotionTransport::_nextFrame private
Definition at line 95 of file Transport.h.
Referenced by CreateMoTrans(), DelayedTeleportTransport(), MoveToNextWaypoint(), and Update().
_passengersLoaded
bool MotionTransport::_passengersLoaded private
Definition at line 106 of file Transport.h.
Referenced by PassengersLoaded(), and SetPassengersLoaded().
_pendingStop
bool MotionTransport::_pendingStop private
Definition at line 98 of file Transport.h.
Referenced by EnableMovement(), and Update().
_positionChangeTimer
TimeTrackerSmall MotionTransport::_positionChangeTimer private
Definition at line 96 of file Transport.h.
Referenced by Update().
_staticPassengers
PassengerSet MotionTransport::_staticPassengers private
Definition at line 104 of file Transport.h.
Referenced by CreateGOPassenger(), CreateNPCPassenger(), GetStaticPassengers(), RemovePassenger(), UnloadStaticPassengers(), Update(), and UpdatePosition().
_transportInfo
TransportTemplate const* MotionTransport::_transportInfo private
Definition at line 93 of file Transport.h.
Referenced by CalculateSegmentPos(), CreateMoTrans(), GetKeyFrames(), and GetTransportTemplate().
_triggeredArrivalEvent
bool MotionTransport::_triggeredArrivalEvent private
These are needed to properly control events triggering only once for each frame.
Definition at line 101 of file Transport.h.
Referenced by CreateMoTrans(), MoveToNextWaypoint(), and Update().
_triggeredDepartureEvent
bool MotionTransport::_triggeredDepartureEvent private
Definition at line 102 of file Transport.h.
Referenced by CreateMoTrans(), MoveToNextWaypoint(), and Update().
Lock
std::mutex MotionTransport::Lock mutable private
Definition at line 105 of file Transport.h.
Referenced by AddPassenger(), and RemovePassenger().
The documentation for this class was generated from the following files:
src/server/game/Entities/Transport/Transport.h
src/server/game/Entities/Transport/Transport.cpp