Azerotcore-wotlk: OPvPCapturePointNA Class Reference
OPvPCapturePointNA Class Reference
#include <OutdoorPvPNA.h>
Public Member Functions
OPvPCapturePointNA (OutdoorPvP *pvp)
bool Update (uint32 diff) override
void ChangeState () override
void SendChangePhase () override
void FillInitialWorldStates (WorldPacket &data) override
bool HandlePlayerEnter (Player *player) override
void HandlePlayerLeave (Player *player) override
bool HandleCustomSpell (Player *player, uint32 spellId, GameObject *go) override
int32 HandleOpenGo (Player *player, GameObject *go) override
uint32 GetAliveGuardsCount ()
TeamId GetControllingFaction () const
Public Member Functions inherited from OPvPCapturePoint
OPvPCapturePoint (OutdoorPvP *pvp)
virtual ~OPvPCapturePoint ()
void SendUpdateWorldState (uint32 field, uint32 value)
void SendObjectiveComplete (uint32 id, ObjectGuid guid=ObjectGuid::Empty)
bool IsInsideObjective (Player *player) const
virtual void ChangeTeam (TeamId)
virtual bool HandleGossipOption (Player *player, Creature *creature, uint32 gossipid)
virtual bool CanTalkTo (Player *player, Creature *c, GossipMenuItems const &gso)
virtual bool HandleDropFlag (Player *player, uint32 spellId)
virtual void DeleteSpawns ()
void AddGO (uint32 type, ObjectGuid::LowType guid, uint32 entry=0)
void AddCre (uint32 type, ObjectGuid::LowType guid, uint32 entry=0)
bool SetCapturePointData (uint32 entry, uint32 map, float x, float y, float z, float o=0, float rotation0=0, float rotation1=0, float rotation2=0, float rotation3=0)
Protected Member Functions
void FactionTakeOver (TeamId teamId)
void DeSpawnNPCs ()
void DeSpawnGOs ()
void SpawnNPCsForTeam (TeamId teamId)
void SpawnGOsForTeam (TeamId teamId)
void UpdateWyvernRoostWorldState (uint32 roost)
void UpdateHalaaWorldState ()
Protected Member Functions inherited from OPvPCapturePoint
bool AddObject (uint32 type, uint32 entry, uint32 map, float x, float y, float z, float o, float rotation0, float rotation1, float rotation2, float rotation3)
bool AddCreature (uint32 type, uint32 entry, uint32 map, float x, float y, float z, float o, uint32 spawntimedelay=0)
bool DelCreature (uint32 type)
bool DelObject (uint32 type)
bool DelCapturePoint ()
Private Attributes
bool m_capturable
uint32 m_GuardsAlive
TeamId m_ControllingFaction
uint32 m_WyvernStateNorth
uint32 m_WyvernStateSouth
uint32 m_WyvernStateEast
uint32 m_WyvernStateWest
uint32 m_HalaaState
uint32 m_RespawnTimer
uint32 m_GuardCheckTimer
Additional Inherited Members
Public Attributes inherited from OPvPCapturePoint
ObjectGuid::LowType m_capturePointSpawnId
GameObject * m_capturePoint
Protected Attributes inherited from OPvPCapturePoint
PlayerSet m_activePlayers [2]
float m_maxValue
float m_minValue
float m_maxSpeed
float m_value
TeamId m_team
ObjectiveStates m_OldState
ObjectiveStates m_State
uint32 m_neutralValuePct
OutdoorPvP * m_PvP
std::map< uint32, ObjectGuid::LowType > m_Objects
std::map< uint32, ObjectGuid::LowType > m_Creatures
std::map< ObjectGuid::LowType, uint32 > m_ObjectTypes
std::map< ObjectGuid::LowType, uint32 > m_CreatureTypes
Detailed Description
Definition at line 253 of file OutdoorPvPNA.h.
Constructor & Destructor Documentation
OPvPCapturePointNA()
OPvPCapturePointNA::OPvPCapturePointNA (OutdoorPvP * pvp)
Definition at line 204 of file OutdoorPvPNA.cpp.
                                                       :
     OPvPCapturePoint(pvp), m_capturable(true), m_GuardsAlive(0), m_ControllingFaction(TEAM_NEUTRAL),
     m_WyvernStateNorth(0), m_WyvernStateSouth(0), m_WyvernStateEast(0), m_WyvernStateWest(0),
     m_HalaaState(HALAA_N), m_RespawnTimer(NA_RESPAWN_TIME), m_GuardCheckTimer(NA_GUARD_CHECK_TIME)
 {
     SetCapturePointData(182210, 530, -1572.57f, 7945.3f, -22.475f, 2.05949f, 0.0f, 0.0f, 0.857167f, 0.515038f);
 }
References OPvPCapturePoint::SetCapturePointData().
Member Function Documentation
ChangeState()
void OPvPCapturePointNA::ChangeState () override virtual
Implements OPvPCapturePoint.
Definition at line 573 of file OutdoorPvPNA.cpp.
 {
     uint32 artkit = 21;
     switch (m_State)
     {
         case OBJECTIVESTATE_NEUTRAL:
             m_HalaaState = HALAA_N;
             break;
         case OBJECTIVESTATE_ALLIANCE:
             m_HalaaState = HALAA_A;
             FactionTakeOver(TEAM_ALLIANCE);
             artkit = 2;
             break;
         case OBJECTIVESTATE_HORDE:
             m_HalaaState = HALAA_H;
             FactionTakeOver(TEAM_HORDE);
             artkit = 1;
             break;
         case OBJECTIVESTATE_NEUTRAL_ALLIANCE_CHALLENGE:
             m_HalaaState = HALAA_N_A;
             break;
         case OBJECTIVESTATE_NEUTRAL_HORDE_CHALLENGE:
             m_HalaaState = HALAA_N_H;
             break;
         case OBJECTIVESTATE_ALLIANCE_HORDE_CHALLENGE:
             m_HalaaState = HALAA_N_A;
             artkit = 2;
             break;
         case OBJECTIVESTATE_HORDE_ALLIANCE_CHALLENGE:
             m_HalaaState = HALAA_N_H;
             artkit = 1;
             break;
     }
     auto bounds = sMapMgr->FindMap(530, 0)->GetGameObjectBySpawnIdStore().equal_range(m_capturePointSpawnId);
     for (auto itr = bounds.first; itr != bounds.second; ++itr)
         itr->second->SetGoArtKit(artkit);
     UpdateHalaaWorldState();
 }
References FactionTakeOver(), HALAA_A, HALAA_H, HALAA_N, HALAA_N_A, HALAA_N_H, OPvPCapturePoint::m_capturePointSpawnId, m_HalaaState, OPvPCapturePoint::m_State, OBJECTIVESTATE_ALLIANCE, OBJECTIVESTATE_ALLIANCE_HORDE_CHALLENGE, OBJECTIVESTATE_HORDE, OBJECTIVESTATE_HORDE_ALLIANCE_CHALLENGE, OBJECTIVESTATE_NEUTRAL, OBJECTIVESTATE_NEUTRAL_ALLIANCE_CHALLENGE, OBJECTIVESTATE_NEUTRAL_HORDE_CHALLENGE, sMapMgr, TEAM_ALLIANCE, TEAM_HORDE, and UpdateHalaaWorldState().
DeSpawnGOs()
void OPvPCapturePointNA::DeSpawnGOs () protected
Definition at line 128 of file OutdoorPvPNA.cpp.
 {
     for (int i = 0; i < NA_CONTROL_GO_NUM; ++i)
     {
         DelObject(i);
     }
 }
References OPvPCapturePoint::DelObject(), and NA_CONTROL_GO_NUM.
Referenced by FactionTakeOver().
DeSpawnNPCs()
void OPvPCapturePointNA::DeSpawnNPCs () protected
Definition at line 98 of file OutdoorPvPNA.cpp.
 {
     for (int i = 0; i < NA_CONTROL_NPC_NUM; ++i)
         DelCreature(i);
 }
References OPvPCapturePoint::DelCreature(), and NA_CONTROL_NPC_NUM.
Referenced by FactionTakeOver().
FactionTakeOver()
void OPvPCapturePointNA::FactionTakeOver (TeamId teamId) protected
Definition at line 136 of file OutdoorPvPNA.cpp.
 {
     if (m_ControllingFaction != TEAM_NEUTRAL)
         sGraveyard->RemoveGraveyardLink(NA_HALAA_GRAVEYARD, NA_HALAA_GRAVEYARD_ZONE, m_ControllingFaction, false);
     if (m_ControllingFaction == TEAM_ALLIANCE)
         sWorld->SendZoneText(NA_HALAA_GRAVEYARD_ZONE, sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_NA_LOSE_A));
     else if (m_ControllingFaction == TEAM_HORDE)
         sWorld->SendZoneText(NA_HALAA_GRAVEYARD_ZONE, sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_NA_LOSE_H));
     m_ControllingFaction = teamId;
     if (m_ControllingFaction != TEAM_NEUTRAL)
         sGraveyard->AddGraveyardLink(NA_HALAA_GRAVEYARD, NA_HALAA_GRAVEYARD_ZONE, m_ControllingFaction, false);
     DeSpawnGOs();
     DeSpawnNPCs();
     SpawnGOsForTeam(teamId);
     SpawnNPCsForTeam(teamId);
     m_GuardsAlive = NA_GUARDS_MAX;
     m_capturable = false;
     this->UpdateHalaaWorldState();
     if (teamId == TEAM_ALLIANCE)
     {
         m_WyvernStateSouth = WYVERN_NEU_HORDE;
         m_WyvernStateNorth = WYVERN_NEU_HORDE;
         m_WyvernStateEast = WYVERN_NEU_HORDE;
         m_WyvernStateWest = WYVERN_NEU_HORDE;
         m_PvP->TeamApplyBuff(TEAM_ALLIANCE, NA_CAPTURE_BUFF);
         m_PvP->SendUpdateWorldState(NA_UI_HORDE_GUARDS_SHOW, 0);
         m_PvP->SendUpdateWorldState(NA_UI_ALLIANCE_GUARDS_SHOW, 1);
         m_PvP->SendUpdateWorldState(NA_UI_GUARDS_LEFT, m_GuardsAlive);
         sWorld->SendZoneText(NA_HALAA_GRAVEYARD_ZONE, sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_NA_CAPTURE_A));
     }
     else
     {
         m_WyvernStateSouth = WYVERN_NEU_ALLIANCE;
         m_WyvernStateNorth = WYVERN_NEU_ALLIANCE;
         m_WyvernStateEast = WYVERN_NEU_ALLIANCE;
         m_WyvernStateWest = WYVERN_NEU_ALLIANCE;
         m_PvP->TeamApplyBuff(TEAM_HORDE, NA_CAPTURE_BUFF);
         m_PvP->SendUpdateWorldState(NA_UI_HORDE_GUARDS_SHOW, 1);
         m_PvP->SendUpdateWorldState(NA_UI_ALLIANCE_GUARDS_SHOW, 0);
         m_PvP->SendUpdateWorldState(NA_UI_GUARDS_LEFT, m_GuardsAlive);
         sWorld->SendZoneText(NA_HALAA_GRAVEYARD_ZONE, sObjectMgr->GetAcoreStringForDBCLocale(LANG_OPVP_NA_CAPTURE_H));
     }
     UpdateWyvernRoostWorldState(NA_ROOST_S);
     UpdateWyvernRoostWorldState(NA_ROOST_N);
     UpdateWyvernRoostWorldState(NA_ROOST_W);
     UpdateWyvernRoostWorldState(NA_ROOST_E);
 }
References DeSpawnGOs(), DeSpawnNPCs(), LANG_OPVP_NA_CAPTURE_A, LANG_OPVP_NA_CAPTURE_H, LANG_OPVP_NA_LOSE_A, LANG_OPVP_NA_LOSE_H, m_capturable, m_ControllingFaction, m_GuardsAlive, OPvPCapturePoint::m_PvP, m_WyvernStateEast, m_WyvernStateNorth, m_WyvernStateSouth, m_WyvernStateWest, NA_CAPTURE_BUFF, NA_GUARDS_MAX, NA_HALAA_GRAVEYARD, NA_HALAA_GRAVEYARD_ZONE, NA_ROOST_E, NA_ROOST_N, NA_ROOST_S, NA_ROOST_W, NA_UI_ALLIANCE_GUARDS_SHOW, NA_UI_GUARDS_LEFT, NA_UI_HORDE_GUARDS_SHOW, OutdoorPvP::SendUpdateWorldState(), sGraveyard, sObjectMgr, SpawnGOsForTeam(), SpawnNPCsForTeam(), sWorld, TEAM_ALLIANCE, TEAM_HORDE, TEAM_NEUTRAL, OutdoorPvP::TeamApplyBuff(), UpdateHalaaWorldState(), UpdateWyvernRoostWorldState(), WYVERN_NEU_ALLIANCE, and WYVERN_NEU_HORDE.
Referenced by ChangeState(), and Update().
FillInitialWorldStates()
void OPvPCapturePointNA::FillInitialWorldStates (WorldPacket & data) override virtual
Reimplemented from OPvPCapturePoint.
Definition at line 248 of file OutdoorPvPNA.cpp.
 {
     if (m_ControllingFaction == TEAM_ALLIANCE)
     {
         data << NA_UI_HORDE_GUARDS_SHOW << uint32(0);
         data << NA_UI_ALLIANCE_GUARDS_SHOW << uint32(1);
     }
     else if (m_ControllingFaction == TEAM_HORDE)
     {
         data << NA_UI_HORDE_GUARDS_SHOW << uint32(1);
         data << NA_UI_ALLIANCE_GUARDS_SHOW << uint32(0);
     }
     else
     {
         data << NA_UI_HORDE_GUARDS_SHOW << uint32(0);
         data << NA_UI_ALLIANCE_GUARDS_SHOW << uint32(0);
     }
     data << NA_UI_GUARDS_MAX << NA_GUARDS_MAX;
     data << NA_UI_GUARDS_LEFT << uint32(m_GuardsAlive);
     data << NA_UI_TOWER_SLIDER_DISPLAY << uint32(0);
     data << NA_UI_TOWER_SLIDER_POS << uint32(50);
     data << NA_UI_TOWER_SLIDER_N << uint32(100);
     data << NA_MAP_WYVERN_NORTH_NEU_H << uint32(bool(m_WyvernStateNorth & WYVERN_NEU_HORDE));
     data << NA_MAP_WYVERN_NORTH_NEU_A << uint32(bool(m_WyvernStateNorth & WYVERN_NEU_ALLIANCE));
     data << NA_MAP_WYVERN_NORTH_H << uint32(bool(m_WyvernStateNorth & WYVERN_HORDE));
     data << NA_MAP_WYVERN_NORTH_A << uint32(bool(m_WyvernStateNorth & WYVERN_ALLIANCE));
     data << NA_MAP_WYVERN_SOUTH_NEU_H << uint32(bool(m_WyvernStateSouth & WYVERN_NEU_HORDE));
     data << NA_MAP_WYVERN_SOUTH_NEU_A << uint32(bool(m_WyvernStateSouth & WYVERN_NEU_ALLIANCE));
     data << NA_MAP_WYVERN_SOUTH_H << uint32(bool(m_WyvernStateSouth & WYVERN_HORDE));
     data << NA_MAP_WYVERN_SOUTH_A << uint32(bool(m_WyvernStateSouth & WYVERN_ALLIANCE));
     data << NA_MAP_WYVERN_WEST_NEU_H << uint32(bool(m_WyvernStateWest & WYVERN_NEU_HORDE));
     data << NA_MAP_WYVERN_WEST_NEU_A << uint32(bool(m_WyvernStateWest & WYVERN_NEU_ALLIANCE));
     data << NA_MAP_WYVERN_WEST_H << uint32(bool(m_WyvernStateWest & WYVERN_HORDE));
     data << NA_MAP_WYVERN_WEST_A << uint32(bool(m_WyvernStateWest & WYVERN_ALLIANCE));
     data << NA_MAP_WYVERN_EAST_NEU_H << uint32(bool(m_WyvernStateEast & WYVERN_NEU_HORDE));
     data << NA_MAP_WYVERN_EAST_NEU_A << uint32(bool(m_WyvernStateEast & WYVERN_NEU_ALLIANCE));
     data << NA_MAP_WYVERN_EAST_H << uint32(bool(m_WyvernStateEast & WYVERN_HORDE));
     data << NA_MAP_WYVERN_EAST_A << uint32(bool(m_WyvernStateEast & WYVERN_ALLIANCE));
     data << NA_MAP_HALAA_NEUTRAL << uint32(bool(m_HalaaState & HALAA_N));
     data << NA_MAP_HALAA_NEU_A << uint32(bool(m_HalaaState & HALAA_N_A));
     data << NA_MAP_HALAA_NEU_H << uint32(bool(m_HalaaState & HALAA_N_H));
     data << NA_MAP_HALAA_HORDE << uint32(bool(m_HalaaState & HALAA_H));
     data << NA_MAP_HALAA_ALLIANCE << uint32(bool(m_HalaaState & HALAA_A));
 }
References HALAA_A, HALAA_H, HALAA_N, HALAA_N_A, HALAA_N_H, m_ControllingFaction, m_GuardsAlive, m_HalaaState, m_WyvernStateEast, m_WyvernStateNorth, m_WyvernStateSouth, m_WyvernStateWest, NA_GUARDS_MAX, NA_MAP_HALAA_ALLIANCE, NA_MAP_HALAA_HORDE, NA_MAP_HALAA_NEU_A, NA_MAP_HALAA_NEU_H, NA_MAP_HALAA_NEUTRAL, NA_MAP_WYVERN_EAST_A, NA_MAP_WYVERN_EAST_H, NA_MAP_WYVERN_EAST_NEU_A, NA_MAP_WYVERN_EAST_NEU_H, NA_MAP_WYVERN_NORTH_A, NA_MAP_WYVERN_NORTH_H, NA_MAP_WYVERN_NORTH_NEU_A, NA_MAP_WYVERN_NORTH_NEU_H, NA_MAP_WYVERN_SOUTH_A, NA_MAP_WYVERN_SOUTH_H, NA_MAP_WYVERN_SOUTH_NEU_A, NA_MAP_WYVERN_SOUTH_NEU_H, NA_MAP_WYVERN_WEST_A, NA_MAP_WYVERN_WEST_H, NA_MAP_WYVERN_WEST_NEU_A, NA_MAP_WYVERN_WEST_NEU_H, NA_UI_ALLIANCE_GUARDS_SHOW, NA_UI_GUARDS_LEFT, NA_UI_GUARDS_MAX, NA_UI_HORDE_GUARDS_SHOW, NA_UI_TOWER_SLIDER_DISPLAY, NA_UI_TOWER_SLIDER_N, NA_UI_TOWER_SLIDER_POS, TEAM_ALLIANCE, TEAM_HORDE, WYVERN_ALLIANCE, WYVERN_HORDE, WYVERN_NEU_ALLIANCE, and WYVERN_NEU_HORDE.
Referenced by OutdoorPvPNA::FillInitialWorldStates().
GetAliveGuardsCount()
uint32 OPvPCapturePointNA::GetAliveGuardsCount ()
Definition at line 44 of file OutdoorPvPNA.cpp.
 {
     uint32 cnt = 0;
     for (std::map<uint32, ObjectGuid::LowType>::iterator itr = m_Creatures.begin(); itr != m_Creatures.end(); ++itr)
     {
         switch (itr->first)
         {
             case NA_NPC_GUARD_01:
             case NA_NPC_GUARD_02:
             case NA_NPC_GUARD_03:
             case NA_NPC_GUARD_04:
             case NA_NPC_GUARD_05:
             case NA_NPC_GUARD_06:
             case NA_NPC_GUARD_07:
             case NA_NPC_GUARD_08:
             case NA_NPC_GUARD_09:
             case NA_NPC_GUARD_10:
             case NA_NPC_GUARD_11:
             case NA_NPC_GUARD_12:
             case NA_NPC_GUARD_13:
             case NA_NPC_GUARD_14:
             case NA_NPC_GUARD_15:
             {
                 auto bounds = m_PvP->GetMap()->GetCreatureBySpawnIdStore().equal_range(itr->second);
                 for (auto itr2 = bounds.first; itr2 != bounds.second; ++itr2)
                     if (itr2->second->IsAlive())
                         ++cnt;
                 break;
             }
             default:
                 break;
         }
     }
     return cnt;
 }
References Map::GetCreatureBySpawnIdStore(), OutdoorPvP::GetMap(), OPvPCapturePoint::m_Creatures, OPvPCapturePoint::m_PvP, NA_NPC_GUARD_01, NA_NPC_GUARD_02, NA_NPC_GUARD_03, NA_NPC_GUARD_04, NA_NPC_GUARD_05, NA_NPC_GUARD_06, NA_NPC_GUARD_07, NA_NPC_GUARD_08, NA_NPC_GUARD_09, NA_NPC_GUARD_10, NA_NPC_GUARD_11, NA_NPC_GUARD_12, NA_NPC_GUARD_13, NA_NPC_GUARD_14, and NA_NPC_GUARD_15.
Referenced by Update().
GetControllingFaction()
TeamId OPvPCapturePointNA::GetControllingFaction () const
Definition at line 80 of file OutdoorPvPNA.cpp.
 {
     return m_ControllingFaction;
 }
References m_ControllingFaction.
Referenced by OutdoorPvPNA::HandlePlayerEnterZone().
HandleCustomSpell()
bool OPvPCapturePointNA::HandleCustomSpell (Player * player, uint32 spellId, GameObject * go) override virtual
Reimplemented from OPvPCapturePoint.
Definition at line 337 of file OutdoorPvPNA.cpp.
 {
     std::vector<uint32> nodes;
     nodes.resize(2);
     bool retval = false;
     switch (spellId)
     {
         case NA_SPELL_FLY_NORTH:
             nodes[0] = FlightPathStartNodes[NA_ROOST_N];
             nodes[1] = FlightPathEndNodes[NA_ROOST_N];
             player->ActivateTaxiPathTo(nodes);
             player->SetFlag(PLAYER_FLAGS, PLAYER_FLAGS_IN_PVP);
             player->UpdatePvP(true, true);
             retval = true;
             break;
         case NA_SPELL_FLY_SOUTH:
             nodes[0] = FlightPathStartNodes[NA_ROOST_S];
             nodes[1] = FlightPathEndNodes[NA_ROOST_S];
             player->ActivateTaxiPathTo(nodes);
             player->SetFlag(PLAYER_FLAGS, PLAYER_FLAGS_IN_PVP);
             player->UpdatePvP(true, true);
             retval = true;
             break;
         case NA_SPELL_FLY_WEST:
             nodes[0] = FlightPathStartNodes[NA_ROOST_W];
             nodes[1] = FlightPathEndNodes[NA_ROOST_W];
             player->ActivateTaxiPathTo(nodes);
             player->SetFlag(PLAYER_FLAGS, PLAYER_FLAGS_IN_PVP);
             player->UpdatePvP(true, true);
             retval = true;
             break;
         case NA_SPELL_FLY_EAST:
             nodes[0] = FlightPathStartNodes[NA_ROOST_E];
             nodes[1] = FlightPathEndNodes[NA_ROOST_E];
             player->ActivateTaxiPathTo(nodes);
             player->SetFlag(PLAYER_FLAGS, PLAYER_FLAGS_IN_PVP);
             player->UpdatePvP(true, true);
             retval = true;
             break;
         default:
             break;
     }
     if (retval)
     {
         //Adding items
         uint32 noSpaceForCount = 0;
         // check space and find places
         ItemPosCountVec dest;
         int32 count = 10;
         uint32 itemid = 24538;
         // bomb id count
         InventoryResult msg = player->CanStoreNewItem(NULL_BAG, NULL_SLOT, dest, itemid, count, &noSpaceForCount);
         if (msg != EQUIP_ERR_OK)                               // convert to possible store amount
             count -= noSpaceForCount;
         if (count == 0 || dest.empty())                         // can't add any
         {
             return true;
         }
         Item* item = player->StoreNewItem(dest, itemid, true);
         if (count > 0 && item)
         {
             player->SendNewItem(item, count, true, false);
         }
         return true;
     }
     return false;
 }
References Player::ActivateTaxiPathTo(), Player::CanStoreNewItem(), EQUIP_ERR_OK, FlightPathEndNodes, FlightPathStartNodes, NA_ROOST_E, NA_ROOST_N, NA_ROOST_S, NA_ROOST_W, NA_SPELL_FLY_EAST, NA_SPELL_FLY_NORTH, NA_SPELL_FLY_SOUTH, NA_SPELL_FLY_WEST, NULL_BAG, NULL_SLOT, PLAYER_FLAGS, PLAYER_FLAGS_IN_PVP, Player::SendNewItem(), Object::SetFlag(), Player::StoreNewItem(), and Player::UpdatePvP().
HandleOpenGo()
int32 OPvPCapturePointNA::HandleOpenGo (Player * player, GameObject * go) override virtual
Reimplemented from OPvPCapturePoint.
Definition at line 412 of file OutdoorPvPNA.cpp.
 {
     int32 retval = OPvPCapturePoint::HandleOpenGo(player, go);
     if (retval >= 0)
     {
         const go_type* gos = nullptr;
         if (m_ControllingFaction == TEAM_ALLIANCE)
             gos = AllianceControlGOs;
         else if (m_ControllingFaction == TEAM_HORDE)
             gos = HordeControlGOs;
         else
             return -1;
         int32 del = -1;
         int32 del2 = -1;
         int32 add = -1;
         int32 add2 = -1;
         switch (retval)
         {
             case NA_DESTROYED_ROOST_S:
                 del = NA_DESTROYED_ROOST_S;
                 add = NA_ROOST_S;
                 add2 = NA_BOMB_WAGON_S;
                 if (m_ControllingFaction == TEAM_HORDE)
                     m_WyvernStateSouth = WYVERN_ALLIANCE;
                 else
                     m_WyvernStateSouth = WYVERN_HORDE;
                 UpdateWyvernRoostWorldState(NA_ROOST_S);
                 break;
             case NA_DESTROYED_ROOST_N:
                 del = NA_DESTROYED_ROOST_N;
                 add = NA_ROOST_N;
                 add2 = NA_BOMB_WAGON_N;
                 if (m_ControllingFaction == TEAM_HORDE)
                     m_WyvernStateNorth = WYVERN_ALLIANCE;
                 else
                     m_WyvernStateNorth = WYVERN_HORDE;
                 UpdateWyvernRoostWorldState(NA_ROOST_N);
                 break;
             case NA_DESTROYED_ROOST_W:
                 del = NA_DESTROYED_ROOST_W;
                 add = NA_ROOST_W;
                 add2 = NA_BOMB_WAGON_W;
                 if (m_ControllingFaction == TEAM_HORDE)
                     m_WyvernStateWest = WYVERN_ALLIANCE;
                 else
                     m_WyvernStateWest = WYVERN_HORDE;
                 UpdateWyvernRoostWorldState(NA_ROOST_W);
                 break;
             case NA_DESTROYED_ROOST_E:
                 del = NA_DESTROYED_ROOST_E;
                 add = NA_ROOST_E;
                 add2 = NA_BOMB_WAGON_E;
                 if (m_ControllingFaction == TEAM_HORDE)
                     m_WyvernStateEast = WYVERN_ALLIANCE;
                 else
                     m_WyvernStateEast = WYVERN_HORDE;
                 UpdateWyvernRoostWorldState(NA_ROOST_E);
                 break;
             case NA_BOMB_WAGON_S:
                 del = NA_BOMB_WAGON_S;
                 del2 = NA_ROOST_S;
                 add = NA_DESTROYED_ROOST_S;
                 if (m_ControllingFaction == TEAM_HORDE)
                     m_WyvernStateSouth = WYVERN_NEU_ALLIANCE;
                 else
                     m_WyvernStateSouth = WYVERN_NEU_HORDE;
                 UpdateWyvernRoostWorldState(NA_ROOST_S);
                 break;
             case NA_BOMB_WAGON_N:
                 del = NA_BOMB_WAGON_N;
                 del2 = NA_ROOST_N;
                 add = NA_DESTROYED_ROOST_N;
                 if (m_ControllingFaction == TEAM_HORDE)
                     m_WyvernStateNorth = WYVERN_NEU_ALLIANCE;
                 else
                     m_WyvernStateNorth = WYVERN_NEU_HORDE;
                 UpdateWyvernRoostWorldState(NA_ROOST_N);
                 break;
             case NA_BOMB_WAGON_W:
                 del = NA_BOMB_WAGON_W;
                 del2 = NA_ROOST_W;
                 add = NA_DESTROYED_ROOST_W;
                 if (m_ControllingFaction == TEAM_HORDE)
                     m_WyvernStateWest = WYVERN_NEU_ALLIANCE;
                 else
                     m_WyvernStateWest = WYVERN_NEU_HORDE;
                 UpdateWyvernRoostWorldState(NA_ROOST_W);
                 break;
             case NA_BOMB_WAGON_E:
                 del = NA_BOMB_WAGON_E;
                 del2 = NA_ROOST_E;
                 add = NA_DESTROYED_ROOST_E;
                 if (m_ControllingFaction == TEAM_HORDE)
                     m_WyvernStateEast = WYVERN_NEU_ALLIANCE;
                 else
                     m_WyvernStateEast = WYVERN_NEU_HORDE;
                 UpdateWyvernRoostWorldState(NA_ROOST_E);
                 break;
             default:
                 return -1;
                 break;
         }
         if (del > -1)
             DelObject(del);
         if (del2 > -1)
             DelObject(del2);
         if (add > -1)
             AddObject(add, gos[add].entry, gos[add].map, gos[add].x, gos[add].y, gos[add].z, gos[add].o, gos[add].rot0, gos[add].rot1, gos[add].rot2, gos[add].rot3);
         if (add2 > -1)
             AddObject(add2, gos[add2].entry, gos[add2].map, gos[add2].x, gos[add2].y, gos[add2].z, gos[add2].o, gos[add2].rot0, gos[add2].rot1, gos[add2].rot2, gos[add2].rot3);
         return retval;
     }
     return -1;
 }
References OPvPCapturePoint::AddObject(), AllianceControlGOs, OPvPCapturePoint::DelObject(), OPvPCapturePoint::HandleOpenGo(), HordeControlGOs, m_ControllingFaction, m_WyvernStateEast, m_WyvernStateNorth, m_WyvernStateSouth, m_WyvernStateWest, NA_BOMB_WAGON_E, NA_BOMB_WAGON_N, NA_BOMB_WAGON_S, NA_BOMB_WAGON_W, NA_DESTROYED_ROOST_E, NA_DESTROYED_ROOST_N, NA_DESTROYED_ROOST_S, NA_DESTROYED_ROOST_W, NA_ROOST_E, NA_ROOST_N, NA_ROOST_S, NA_ROOST_W, TEAM_ALLIANCE, TEAM_HORDE, UpdateWyvernRoostWorldState(), WYVERN_ALLIANCE, WYVERN_HORDE, WYVERN_NEU_ALLIANCE, and WYVERN_NEU_HORDE.
HandlePlayerEnter()
bool OPvPCapturePointNA::HandlePlayerEnter (Player * player) override virtual
Reimplemented from OPvPCapturePoint.
Definition at line 185 of file OutdoorPvPNA.cpp.
 {
     if (OPvPCapturePoint::HandlePlayerEnter(player))
     {
         player->SendUpdateWorldState(NA_UI_TOWER_SLIDER_DISPLAY, 1);
         uint32 phase = (uint32)ceil((m_value + m_maxValue) / (2 * m_maxValue) * 100.0f);
         player->SendUpdateWorldState(NA_UI_TOWER_SLIDER_POS, phase);
         player->SendUpdateWorldState(NA_UI_TOWER_SLIDER_N, m_neutralValuePct);
         return true;
     }
     return false;
 }
References OPvPCapturePoint::HandlePlayerEnter(), OPvPCapturePoint::m_maxValue, OPvPCapturePoint::m_neutralValuePct, OPvPCapturePoint::m_value, NA_UI_TOWER_SLIDER_DISPLAY, NA_UI_TOWER_SLIDER_N, NA_UI_TOWER_SLIDER_POS, and Player::SendUpdateWorldState().
HandlePlayerLeave()
void OPvPCapturePointNA::HandlePlayerLeave (Player * player) override virtual
Reimplemented from OPvPCapturePoint.
Definition at line 198 of file OutdoorPvPNA.cpp.
 {
     player->SendUpdateWorldState(NA_UI_TOWER_SLIDER_DISPLAY, 0);
     OPvPCapturePoint::HandlePlayerLeave(player);
 }
References OPvPCapturePoint::HandlePlayerLeave(), NA_UI_TOWER_SLIDER_DISPLAY, and Player::SendUpdateWorldState().
SendChangePhase()
void OPvPCapturePointNA::SendChangePhase () override virtual
Reimplemented from OPvPCapturePoint.
Definition at line 614 of file OutdoorPvPNA.cpp.
 {
     // send this too, sometimes the slider disappears, dunno why :(
     SendUpdateWorldState(NA_UI_TOWER_SLIDER_DISPLAY, 1);
     // send these updates to only the ones in this objective
     uint32 phase = (uint32)ceil((m_value + m_maxValue) / (2 * m_maxValue) * 100.0f);
     SendUpdateWorldState(NA_UI_TOWER_SLIDER_POS, phase);
     SendUpdateWorldState(NA_UI_TOWER_SLIDER_N, m_neutralValuePct);
 }
References OPvPCapturePoint::m_maxValue, OPvPCapturePoint::m_neutralValuePct, OPvPCapturePoint::m_value, NA_UI_TOWER_SLIDER_DISPLAY, NA_UI_TOWER_SLIDER_N, NA_UI_TOWER_SLIDER_POS, and OPvPCapturePoint::SendUpdateWorldState().
SpawnGOsForTeam()
void OPvPCapturePointNA::SpawnGOsForTeam (TeamId teamId) protected
Definition at line 104 of file OutdoorPvPNA.cpp.
 {
     const go_type* gos = nullptr;
     if (teamId == TEAM_ALLIANCE)
         gos = AllianceControlGOs;
     else if (teamId == TEAM_HORDE)
         gos = HordeControlGOs;
     else
         return;
     for (int i = 0; i < NA_CONTROL_GO_NUM; ++i)
     {
         if (i == NA_ROOST_S ||
                 i == NA_ROOST_W ||
                 i == NA_ROOST_N ||
                 i == NA_ROOST_E ||
                 i == NA_BOMB_WAGON_S ||
                 i == NA_BOMB_WAGON_W ||
                 i == NA_BOMB_WAGON_N ||
                 i == NA_BOMB_WAGON_E)
             continue;   // roosts and bomb wagons are spawned when someone uses the matching destroyed roost
         AddObject(i, gos[i].entry, gos[i].map, gos[i].x, gos[i].y, gos[i].z, gos[i].o, gos[i].rot0, gos[i].rot1, gos[i].rot2, gos[i].rot3);
     }
 }
References OPvPCapturePoint::AddObject(), AllianceControlGOs, HordeControlGOs, NA_BOMB_WAGON_E, NA_BOMB_WAGON_N, NA_BOMB_WAGON_S, NA_BOMB_WAGON_W, NA_CONTROL_GO_NUM, NA_ROOST_E, NA_ROOST_N, NA_ROOST_S, NA_ROOST_W, TEAM_ALLIANCE, and TEAM_HORDE.
Referenced by FactionTakeOver().
SpawnNPCsForTeam()
void OPvPCapturePointNA::SpawnNPCsForTeam (TeamId teamId) protected
Definition at line 85 of file OutdoorPvPNA.cpp.
 {
     const creature_type* creatures = nullptr;
     if (teamId == TEAM_ALLIANCE)
         creatures = AllianceControlNPCs;
     else if (teamId == TEAM_HORDE)
         creatures = HordeControlNPCs;
     else
         return;
     for (int i = 0; i < NA_CONTROL_NPC_NUM; ++i)
         AddCreature(i, creatures[i].entry, creatures[i].map, creatures[i].x, creatures[i].y, creatures[i].z, creatures[i].o, 1000000);
 }
References OPvPCapturePoint::AddCreature(), AllianceControlNPCs, HordeControlNPCs, NA_CONTROL_NPC_NUM, TEAM_ALLIANCE, and TEAM_HORDE.
Referenced by FactionTakeOver().
Update()
bool OPvPCapturePointNA::Update (uint32 diff) override virtual
Reimplemented from OPvPCapturePoint.
Definition at line 534 of file OutdoorPvPNA.cpp.
 {
     // let the controlling faction advance in phase
     bool capturable = false;
     if (m_ControllingFaction == TEAM_ALLIANCE && m_activePlayers[0].size() > m_activePlayers[1].size())
         capturable = true;
     else if (m_ControllingFaction == TEAM_HORDE && m_activePlayers[0].size() < m_activePlayers[1].size())
         capturable = true;
     if (m_GuardCheckTimer < diff)
     {
         m_GuardCheckTimer = NA_GUARD_CHECK_TIME;
         uint32 cnt = GetAliveGuardsCount();
         if (cnt != m_GuardsAlive)
         {
             m_GuardsAlive = cnt;
             if (m_GuardsAlive == 0)
                 m_capturable = true;
             // update the guard count for the players in zone
             m_PvP->SendUpdateWorldState(NA_UI_GUARDS_LEFT, m_GuardsAlive);
         }
     }
     else m_GuardCheckTimer -= diff;
     if (m_capturable || capturable)
     {
         if (m_RespawnTimer < diff)
         {
             // if the guards have been killed, then the challenger has one hour to take over halaa.
             // in case they fail to do it, the guards are respawned, and they have to start again.
             if (m_ControllingFaction)
                 FactionTakeOver(m_ControllingFaction);
             m_RespawnTimer = NA_RESPAWN_TIME;
         }
         else m_RespawnTimer -= diff;
     }
     return OPvPCapturePoint::Update(diff);
 }
References FactionTakeOver(), GetAliveGuardsCount(), OPvPCapturePoint::m_activePlayers, m_capturable, m_ControllingFaction, m_GuardCheckTimer, m_GuardsAlive, OPvPCapturePoint::m_PvP, m_RespawnTimer, NA_GUARD_CHECK_TIME, NA_RESPAWN_TIME, NA_UI_GUARDS_LEFT, OutdoorPvP::SendUpdateWorldState(), TEAM_ALLIANCE, TEAM_HORDE, and OPvPCapturePoint::Update().
Referenced by OutdoorPvPNA::Update().
UpdateHalaaWorldState()
void OPvPCapturePointNA::UpdateHalaaWorldState () protected
Definition at line 624 of file OutdoorPvPNA.cpp.
 {
     m_PvP->SendUpdateWorldState(NA_MAP_HALAA_NEUTRAL, uint32(bool(m_HalaaState & HALAA_N)));
     m_PvP->SendUpdateWorldState(NA_MAP_HALAA_NEU_A, uint32(bool(m_HalaaState & HALAA_N_A)));
     m_PvP->SendUpdateWorldState(NA_MAP_HALAA_NEU_H, uint32(bool(m_HalaaState & HALAA_N_H)));
     m_PvP->SendUpdateWorldState(NA_MAP_HALAA_HORDE, uint32(bool(m_HalaaState & HALAA_H)));
     m_PvP->SendUpdateWorldState(NA_MAP_HALAA_ALLIANCE, uint32(bool(m_HalaaState & HALAA_A)));
 }
References HALAA_A, HALAA_H, HALAA_N, HALAA_N_A, HALAA_N_H, m_HalaaState, OPvPCapturePoint::m_PvP, NA_MAP_HALAA_ALLIANCE, NA_MAP_HALAA_HORDE, NA_MAP_HALAA_NEU_A, NA_MAP_HALAA_NEU_H, NA_MAP_HALAA_NEUTRAL, and OutdoorPvP::SendUpdateWorldState().
Referenced by ChangeState(), and FactionTakeOver().
UpdateWyvernRoostWorldState()
void OPvPCapturePointNA::UpdateWyvernRoostWorldState (uint32 roost) protected
Definition at line 633 of file OutdoorPvPNA.cpp.
 {
     switch (roost)
     {
         case NA_ROOST_S:
             m_PvP->SendUpdateWorldState(NA_MAP_WYVERN_SOUTH_NEU_H, uint32(bool(m_WyvernStateSouth & WYVERN_NEU_HORDE)));
             m_PvP->SendUpdateWorldState(NA_MAP_WYVERN_SOUTH_NEU_A, uint32(bool(m_WyvernStateSouth & WYVERN_NEU_ALLIANCE)));
             m_PvP->SendUpdateWorldState(NA_MAP_WYVERN_SOUTH_H, uint32(bool(m_WyvernStateSouth & WYVERN_HORDE)));
             m_PvP->SendUpdateWorldState(NA_MAP_WYVERN_SOUTH_A, uint32(bool(m_WyvernStateSouth & WYVERN_ALLIANCE)));
             break;
         case NA_ROOST_N:
             m_PvP->SendUpdateWorldState(NA_MAP_WYVERN_NORTH_NEU_H, uint32(bool(m_WyvernStateNorth & WYVERN_NEU_HORDE)));
             m_PvP->SendUpdateWorldState(NA_MAP_WYVERN_NORTH_NEU_A, uint32(bool(m_WyvernStateNorth & WYVERN_NEU_ALLIANCE)));
             m_PvP->SendUpdateWorldState(NA_MAP_WYVERN_NORTH_H, uint32(bool(m_WyvernStateNorth & WYVERN_HORDE)));
             m_PvP->SendUpdateWorldState(NA_MAP_WYVERN_NORTH_A, uint32(bool(m_WyvernStateNorth & WYVERN_ALLIANCE)));
             break;
         case NA_ROOST_W:
             m_PvP->SendUpdateWorldState(NA_MAP_WYVERN_WEST_NEU_H, uint32(bool(m_WyvernStateWest & WYVERN_NEU_HORDE)));
             m_PvP->SendUpdateWorldState(NA_MAP_WYVERN_WEST_NEU_A, uint32(bool(m_WyvernStateWest & WYVERN_NEU_ALLIANCE)));
             m_PvP->SendUpdateWorldState(NA_MAP_WYVERN_WEST_H, uint32(bool(m_WyvernStateWest & WYVERN_HORDE)));
             m_PvP->SendUpdateWorldState(NA_MAP_WYVERN_WEST_A, uint32(bool(m_WyvernStateWest & WYVERN_ALLIANCE)));
             break;
         case NA_ROOST_E:
             m_PvP->SendUpdateWorldState(NA_MAP_WYVERN_EAST_NEU_H, uint32(bool(m_WyvernStateEast & WYVERN_NEU_HORDE)));
             m_PvP->SendUpdateWorldState(NA_MAP_WYVERN_EAST_NEU_A, uint32(bool(m_WyvernStateEast & WYVERN_NEU_ALLIANCE)));
             m_PvP->SendUpdateWorldState(NA_MAP_WYVERN_EAST_H, uint32(bool(m_WyvernStateEast & WYVERN_HORDE)));
             m_PvP->SendUpdateWorldState(NA_MAP_WYVERN_EAST_A, uint32(bool(m_WyvernStateEast & WYVERN_ALLIANCE)));
             break;
     }
 }
References OPvPCapturePoint::m_PvP, m_WyvernStateEast, m_WyvernStateNorth, m_WyvernStateSouth, m_WyvernStateWest, NA_MAP_WYVERN_EAST_A, NA_MAP_WYVERN_EAST_H, NA_MAP_WYVERN_EAST_NEU_A, NA_MAP_WYVERN_EAST_NEU_H, NA_MAP_WYVERN_NORTH_A, NA_MAP_WYVERN_NORTH_H, NA_MAP_WYVERN_NORTH_NEU_A, NA_MAP_WYVERN_NORTH_NEU_H, NA_MAP_WYVERN_SOUTH_A, NA_MAP_WYVERN_SOUTH_H, NA_MAP_WYVERN_SOUTH_NEU_A, NA_MAP_WYVERN_SOUTH_NEU_H, NA_MAP_WYVERN_WEST_A, NA_MAP_WYVERN_WEST_H, NA_MAP_WYVERN_WEST_NEU_A, NA_MAP_WYVERN_WEST_NEU_H, NA_ROOST_E, NA_ROOST_N, NA_ROOST_S, NA_ROOST_W, OutdoorPvP::SendUpdateWorldState(), WYVERN_ALLIANCE, WYVERN_HORDE, WYVERN_NEU_ALLIANCE, and WYVERN_NEU_HORDE.
Referenced by FactionTakeOver(), and HandleOpenGo().
Member Data Documentation
m_capturable
bool OPvPCapturePointNA::m_capturable private
Definition at line 291 of file OutdoorPvPNA.h.
Referenced by FactionTakeOver(), and Update().
m_ControllingFaction
TeamId OPvPCapturePointNA::m_ControllingFaction private
Definition at line 295 of file OutdoorPvPNA.h.
Referenced by FactionTakeOver(), FillInitialWorldStates(), GetControllingFaction(), HandleOpenGo(), and Update().
m_GuardCheckTimer
uint32 OPvPCapturePointNA::m_GuardCheckTimer private
Definition at line 306 of file OutdoorPvPNA.h.
Referenced by Update().
m_GuardsAlive
uint32 OPvPCapturePointNA::m_GuardsAlive private
Definition at line 293 of file OutdoorPvPNA.h.
Referenced by FactionTakeOver(), FillInitialWorldStates(), and Update().
m_HalaaState
uint32 OPvPCapturePointNA::m_HalaaState private
Definition at line 302 of file OutdoorPvPNA.h.
Referenced by ChangeState(), FillInitialWorldStates(), and UpdateHalaaWorldState().
m_RespawnTimer
uint32 OPvPCapturePointNA::m_RespawnTimer private
Definition at line 304 of file OutdoorPvPNA.h.
Referenced by Update().
m_WyvernStateEast
uint32 OPvPCapturePointNA::m_WyvernStateEast private
Definition at line 299 of file OutdoorPvPNA.h.
Referenced by FactionTakeOver(), FillInitialWorldStates(), HandleOpenGo(), and UpdateWyvernRoostWorldState().
m_WyvernStateNorth
uint32 OPvPCapturePointNA::m_WyvernStateNorth private
Definition at line 297 of file OutdoorPvPNA.h.
Referenced by FactionTakeOver(), FillInitialWorldStates(), HandleOpenGo(), and UpdateWyvernRoostWorldState().
m_WyvernStateSouth
uint32 OPvPCapturePointNA::m_WyvernStateSouth private
Definition at line 298 of file OutdoorPvPNA.h.
Referenced by FactionTakeOver(), FillInitialWorldStates(), HandleOpenGo(), and UpdateWyvernRoostWorldState().
m_WyvernStateWest
uint32 OPvPCapturePointNA::m_WyvernStateWest private
Definition at line 300 of file OutdoorPvPNA.h.
Referenced by FactionTakeOver(), FillInitialWorldStates(), HandleOpenGo(), and UpdateWyvernRoostWorldState().
The documentation for this class was generated from the following files:
src/server/scripts/OutdoorPvP/OutdoorPvPNA.h
src/server/scripts/OutdoorPvP/OutdoorPvPNA.cpp