Azerotcore-wotlk: deps/mysqllite/include/internal/my_tree.h File Reference
my_tree.h File Reference
#include "my_base.h"
#include "my_alloc.h"
Classes
struct st_tree_element
struct st_tree
Macros
#define MAX_TREE_HEIGHT 64
#define ELEMENT_KEY(tree, element)
#define tree_set_pointer(element, ptr) *((uchar **) (element+1))=((uchar*) (ptr))
#define TREE_NO_DUPS 1
#define ELEMENT_CHILD(element, offs) (*(TREE_ELEMENT**)((char*)element + offs))
#define is_tree_inited(tree) ((tree)->root != 0)
#define TREE_ELEMENT_EXTRA_SIZE (sizeof(TREE_ELEMENT) + sizeof(void*))
Typedefs
typedef uint32 element_count
typedef int(* tree_walk_action) (void *, element_count, void *)
typedef void(* tree_element_free) (void *, TREE_FREE, void *)
typedef struct st_tree_element TREE_ELEMENT
typedef struct st_tree TREE
Enumerations
enum TREE_WALK { left_root_right , right_root_left }
enum TREE_FREE { free_init , free_free , free_end }
Functions
void init_tree (TREE *tree, ulong default_alloc_size, ulong memory_limit, int size, qsort_cmp2 compare, my_bool with_delete, tree_element_free free_element, void *custom_arg)
void delete_tree (TREE *)
void reset_tree (TREE *)
TREE_ELEMENT * tree_insert (TREE *tree, void *key, uint key_size, void *custom_arg)
void * tree_search (TREE *tree, void *key, void *custom_arg)
int tree_walk (TREE *tree, tree_walk_action action, void *argument, TREE_WALK visit)
int tree_delete (TREE *tree, void *key, uint key_size, void *custom_arg)
void * tree_search_key (TREE *tree, const void *key, TREE_ELEMENT **parents, TREE_ELEMENT ***last_pos, enum ha_rkey_function flag, void *custom_arg)
void * tree_search_edge (TREE *tree, TREE_ELEMENT **parents, TREE_ELEMENT ***last_pos, int child_offs)
void * tree_search_next (TREE *tree, TREE_ELEMENT ***last_pos, int l_offs, int r_offs)
ha_rows tree_record_pos (TREE *tree, const void *key, enum ha_rkey_function search_flag, void *custom_arg)
Macro Definition Documentation
ELEMENT_CHILD
#define ELEMENT_CHILD (element, offs) (*(TREE_ELEMENT**)((char*)element + offs))
Definition at line 49 of file my_tree.h.
ELEMENT_KEY
#define ELEMENT_KEY (tree, element)
Value:
(tree->offset_to_key ? (void*)((uchar*) element+tree->offset_to_key) :\
            *((void**) (element+1)))
Definition at line 28 of file my_tree.h.
is_tree_inited
#define is_tree_inited (tree) ((tree)->root != 0)
Definition at line 72 of file my_tree.h.
MAX_TREE_HEIGHT
#define MAX_TREE_HEIGHT 64
Definition at line 26 of file my_tree.h.
TREE_ELEMENT_EXTRA_SIZE
#define TREE_ELEMENT_EXTRA_SIZE (sizeof(TREE_ELEMENT) + sizeof(void*))
Definition at line 91 of file my_tree.h.
TREE_NO_DUPS
#define TREE_NO_DUPS 1
Definition at line 34 of file my_tree.h.
tree_set_pointer
#define tree_set_pointer (element, ptr) *((uchar **) (element+1))=((uchar*) (ptr))
Definition at line 32 of file my_tree.h.
Typedef Documentation
element_count
typedef uint32 element_count
Definition at line 37 of file my_tree.h.
TREE
typedef struct st_tree TREE
TREE_ELEMENT
typedef struct st_tree_element TREE_ELEMENT
tree_element_free
typedef void(* tree_element_free) (void *, TREE_FREE, void *)
Definition at line 41 of file my_tree.h.
tree_walk_action
typedef int(* tree_walk_action) (void *, element_count, void *)
Definition at line 38 of file my_tree.h.
Enumeration Type Documentation
TREE_FREE
enum TREE_FREE
Enumerator
free_init
free_free
free_end
Definition at line 40 of file my_tree.h.
 { free_init, free_free, free_end } TREE_FREE;
TREE_WALK
enum TREE_WALK
Enumerator
left_root_right
right_root_left
Definition at line 36 of file my_tree.h.
 { left_root_right, right_root_left } TREE_WALK;
Function Documentation
delete_tree()
void delete_tree (TREE * tree)
Definition at line 165 of file tree.c.
 {
   free_tree(tree, MYF(0)); /* my_free() mem_root if applicable */
 }
References free_tree(), and MYF.
init_tree()
void init_tree (TREE * tree, ulong default_alloc_size, ulong memory_limit, int size, qsort_cmp2 compare, my_bool with_delete, tree_element_free free_element, void * custom_arg)
Definition at line 86 of file tree.c.
 {
   DBUG_ENTER("init_tree");
   DBUG_PRINT("enter",("tree: 0x%lx  size: %d", (long) tree, size));
   if (default_alloc_size < DEFAULT_ALLOC_SIZE)
     default_alloc_size= DEFAULT_ALLOC_SIZE;
   default_alloc_size= MY_ALIGN(default_alloc_size, DEFAULT_ALIGN_SIZE);
   bzero((uchar*) &tree->null_element,sizeof(tree->null_element));
   tree->root= &tree->null_element;
   tree->compare=compare;
   tree->size_of_element=size > 0 ? (uint) size : 0;
   tree->memory_limit=memory_limit;
   tree->free=free_element;
   tree->allocated=0;
   tree->elements_in_tree=0;
   tree->custom_arg = custom_arg;
   tree->null_element.colour=BLACK;
   tree->null_element.left=tree->null_element.right=0;
   tree->flag= 0;
   if (!free_element && size >= 0 &&
       ((uint) size <= sizeof(void*) || ((uint) size & (sizeof(void*)-1))))
   {
     /*
       We know that the data doesn't have to be aligned (like if the key
       contains a double), so we can store the data combined with the
       TREE_ELEMENT.
     */
     tree->offset_to_key=sizeof(TREE_ELEMENT); /* Put key after element */
     /* Fix allocation size so that we don't lose any memory */
     default_alloc_size/=(sizeof(TREE_ELEMENT)+size);
     if (!default_alloc_size)
       default_alloc_size=1;
     default_alloc_size*=(sizeof(TREE_ELEMENT)+size);
   }
   else
   {
     tree->offset_to_key=0;      /* use key through pointer */
     tree->size_of_element+=sizeof(void*);
   }
   if (!(tree->with_delete=with_delete))
   {
     init_alloc_root(&tree->mem_root, (uint) default_alloc_size, 0);
     tree->mem_root.min_malloc=(sizeof(TREE_ELEMENT)+tree->size_of_element);
   }
   DBUG_VOID_RETURN;
 }
References st_tree::allocated, BLACK, bzero, st_tree_element::colour, st_tree::compare, st_tree::custom_arg, DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, DEFAULT_ALIGN_SIZE, DEFAULT_ALLOC_SIZE, st_tree::elements_in_tree, st_tree::flag, st_tree::free, init_alloc_root(), st_tree_element::left, st_tree::mem_root, st_tree::memory_limit, st_mem_root::min_malloc, MY_ALIGN, st_tree::null_element, st_tree::offset_to_key, st_tree_element::right, st_tree::root, st_tree::size_of_element, and st_tree::with_delete.
reset_tree()
void reset_tree (TREE * tree)
Definition at line 170 of file tree.c.
 {
   /* do not free mem_root, just mark blocks as free */
   free_tree(tree, MYF(MY_MARK_BLOCKS_FREE));
 }
References free_tree(), MY_MARK_BLOCKS_FREE, and MYF.
Referenced by tree_insert().
tree_delete()
int tree_delete (TREE * tree, void * key, uint key_size, void * custom_arg)
Definition at line 273 of file tree.c.
 {
   int cmp,remove_colour;
   TREE_ELEMENT *element,***parent, ***org_parent, *nod;
   if (!tree->with_delete)
     return 1;                   /* not allowed */
   parent= tree->parents;
   *parent= &tree->root; element= tree->root;
   for (;;)
   {
     if (element == &tree->null_element)
       return 1;             /* Was not in tree */
     if ((cmp = (*tree->compare)(custom_arg, ELEMENT_KEY(tree,element),
                                 key)) == 0)
       break;
     if (cmp < 0)
     {
       *++parent= &element->right; element= element->right;
     }
     else
     {
       *++parent = &element->left; element= element->left;
     }
   }
   if (element->left == &tree->null_element)
   {
     (**parent)=element->right;
     remove_colour= element->colour;
   }
   else if (element->right == &tree->null_element)
   {
     (**parent)=element->left;
     remove_colour= element->colour;
   }
   else
   {
     org_parent= parent;
     *++parent= &element->right; nod= element->right;
     while (nod->left != &tree->null_element)
     {
       *++parent= &nod->left; nod= nod->left;
     }
     (**parent)=nod->right;      /* unlink nod from tree */
     remove_colour= nod->colour;
     org_parent[0][0]=nod;       /* put y in place of element */
     org_parent[1]= &nod->right;
     nod->left=element->left;
     nod->right=element->right;
     nod->colour=element->colour;
   }
   if (remove_colour == BLACK)
     rb_delete_fixup(tree,parent);
   if (tree->free)
     (*tree->free)(ELEMENT_KEY(tree,element), free_free, tree->custom_arg);
   tree->allocated-= sizeof(TREE_ELEMENT) + tree->size_of_element + key_size;
   my_free(element);
   tree->elements_in_tree--;
   return 0;
 }
References st_tree::allocated, BLACK, cmp, st_tree_element::colour, st_tree::compare, st_tree::custom_arg, ELEMENT_KEY, st_tree::elements_in_tree, st_tree::free, free_free, st_tree_element::left, my_free(), st_tree::null_element, st_tree::parents, rb_delete_fixup(), st_tree_element::right, st_tree::root, st_tree::size_of_element, and st_tree::with_delete.
tree_insert()
TREE_ELEMENT* tree_insert (TREE * tree, void * key, uint key_size, void * custom_arg)
Definition at line 199 of file tree.c.
 {
   int cmp;
   TREE_ELEMENT *element,***parent;
   parent= tree->parents;
   *parent = &tree->root; element= tree->root;
   for (;;)
   {
     if (element == &tree->null_element ||
     (cmp = (*tree->compare)(custom_arg, ELEMENT_KEY(tree,element),
                                 key)) == 0)
       break;
     if (cmp < 0)
     {
       *++parent= &element->right; element= element->right;
     }
     else
     {
       *++parent = &element->left; element= element->left;
     }
   }
   if (element == &tree->null_element)
   {
     uint alloc_size=sizeof(TREE_ELEMENT)+key_size+tree->size_of_element;
     tree->allocated+=alloc_size;
     if (tree->memory_limit && tree->elements_in_tree
                            && tree->allocated > tree->memory_limit)
     {
       reset_tree(tree);
       return tree_insert(tree, key, key_size, custom_arg);
     }
     key_size+=tree->size_of_element;
     if (tree->with_delete)
       element=(TREE_ELEMENT *) my_malloc(alloc_size, MYF(MY_WME));
     else
       element=(TREE_ELEMENT *) alloc_root(&tree->mem_root,alloc_size);
     if (!element)
       return(NULL);
     **parent=element;
     element->left=element->right= &tree->null_element;
     if (!tree->offset_to_key)
     {
       if (key_size == sizeof(void*))         /* no length, save pointer */
     *((void**) (element+1))=key;
       else
       {
     *((void**) (element+1))= (void*) ((void **) (element+1)+1);
     memcpy((uchar*) *((void **) (element+1)),key,
            (size_t) (key_size-sizeof(void*)));
       }
     }
     else
       memcpy((uchar*) element+tree->offset_to_key,key,(size_t) key_size);
     element->count=1;           /* May give warning in purify */
     tree->elements_in_tree++;
     rb_insert(tree,parent,element); /* rebalance tree */
   }
   else
   {
     if (tree->flag & TREE_NO_DUPS)
       return(NULL);
     element->count++;
     /* Avoid a wrap over of the count. */
     if (! element->count)
       element->count--;
   }
   DBUG_EXECUTE("check_tree", test_rb_tree(tree->root););
   return element;
 }
References alloc_root(), st_tree::allocated, cmp, st_tree::compare, st_tree_element::count, DBUG_EXECUTE, ELEMENT_KEY, st_tree::elements_in_tree, st_tree::flag, if(), st_tree_element::left, st_tree::mem_root, memcpy, st_tree::memory_limit, my_malloc(), MY_WME, MYF, NULL, st_tree::null_element, st_tree::offset_to_key, st_tree::parents, rb_insert(), reset_tree(), st_tree_element::right, st_tree::root, st_tree::size_of_element, test_rb_tree(), tree_insert(), TREE_NO_DUPS, and st_tree::with_delete.
Referenced by tree_insert().
tree_record_pos()
ha_rows tree_record_pos (TREE * tree, const void * key, enum ha_rkey_function search_flag, void * custom_arg)
Definition at line 478 of file tree.c.
 {
   int cmp;
   TREE_ELEMENT *element= tree->root;
   double left= 1;
   double right= tree->elements_in_tree;
   while (element != &tree->null_element)
   {
     if ((cmp= (*tree->compare)(custom_arg, ELEMENT_KEY(tree, element),
                    key)) == 0)
     {
       switch (flag) {
       case HA_READ_KEY_EXACT:
       case HA_READ_BEFORE_KEY:
         cmp= 1;
         break;
       case HA_READ_AFTER_KEY:
         cmp= -1;
         break;
       default:
         return HA_POS_ERROR;
       }
     }
     if (cmp < 0) /* element < key */
     {
       element= element->right;
       left= (left + right) / 2;
     }
     else
     {
       element= element->left;
       right= (left + right) / 2;
     }
   }
   switch (flag) {
   case HA_READ_KEY_EXACT:
   case HA_READ_BEFORE_KEY:
     return (ha_rows) right;
   case HA_READ_AFTER_KEY:
     return (ha_rows) left;
   default:
     return HA_POS_ERROR;
   }
 }
References cmp, st_tree::compare, ELEMENT_KEY, st_tree::elements_in_tree, HA_POS_ERROR, HA_READ_AFTER_KEY, HA_READ_BEFORE_KEY, HA_READ_KEY_EXACT, align::left, st_tree_element::left, st_tree::null_element, align::right, st_tree_element::right, and st_tree::root.
tree_search()
void* tree_search (TREE * tree, void * key, void * custom_arg)
Definition at line 335 of file tree.c.
 {
   int cmp;
   TREE_ELEMENT *element=tree->root;
   for (;;)
   {
     if (element == &tree->null_element)
       return (void*) 0;
     if ((cmp = (*tree->compare)(custom_arg, ELEMENT_KEY(tree,element),
                                 key)) == 0)
       return ELEMENT_KEY(tree,element);
     if (cmp < 0)
       element=element->right;
     else
       element=element->left;
   }
 }
References cmp, st_tree::compare, ELEMENT_KEY, st_tree_element::left, st_tree::null_element, st_tree_element::right, and st_tree::root.
tree_search_edge()
void* tree_search_edge (TREE * tree, TREE_ELEMENT ** parents, TREE_ELEMENT *** last_pos, int child_offs)
Definition at line 430 of file tree.c.
 {
   TREE_ELEMENT *element= tree->root;
   *parents= &tree->null_element;
   while (element != &tree->null_element)
   {
     *++parents= element;
     element= ELEMENT_CHILD(element, child_offs);
   }
   *last_pos= parents;
   return **last_pos != &tree->null_element ?
     ELEMENT_KEY(tree, **last_pos) : NULL;
 }
References ELEMENT_CHILD, ELEMENT_KEY, NULL, st_tree::null_element, and st_tree::root.
tree_search_key()
void* tree_search_key (TREE * tree, const void * key, TREE_ELEMENT ** parents, TREE_ELEMENT *** last_pos, enum ha_rkey_function flag, void * custom_arg)
Definition at line 354 of file tree.c.
 {
   int cmp;
   TREE_ELEMENT *element= tree->root;
   TREE_ELEMENT **last_left_step_parent= NULL, **last_right_step_parent= NULL;
   TREE_ELEMENT **last_equal_element= NULL;
 /*
   TODO: support for HA_READ_KEY_OR_PREV, HA_READ_PREFIX flags if needed.
 */
   *parents = &tree->null_element;
   while (element != &tree->null_element)
   {
     *++parents= element;
     if ((cmp= (*tree->compare)(custom_arg, ELEMENT_KEY(tree, element),
                    key)) == 0)
     {
       switch (flag) {
       case HA_READ_KEY_EXACT:
       case HA_READ_KEY_OR_NEXT:
       case HA_READ_BEFORE_KEY:
     last_equal_element= parents;
     cmp= 1;
     break;
       case HA_READ_AFTER_KEY:
     cmp= -1;
     break;
       case HA_READ_PREFIX_LAST:
       case HA_READ_PREFIX_LAST_OR_PREV:
     last_equal_element= parents;
     cmp= -1;
     break;
       default:
     return NULL;
       }
     }
     if (cmp < 0) /* element < key */
     {
       last_right_step_parent= parents;
       element= element->right;
     }
     else
     {
       last_left_step_parent= parents;
       element= element->left;
     }
   }
   switch (flag) {
   case HA_READ_KEY_EXACT:
   case HA_READ_PREFIX_LAST:
     *last_pos= last_equal_element;
     break;
   case HA_READ_KEY_OR_NEXT:
     *last_pos= last_equal_element ? last_equal_element : last_left_step_parent;
     break;
   case HA_READ_AFTER_KEY:
     *last_pos= last_left_step_parent;
     break;
   case HA_READ_PREFIX_LAST_OR_PREV:
     *last_pos= last_equal_element ? last_equal_element : last_right_step_parent;
     break;
   case HA_READ_BEFORE_KEY:
     *last_pos= last_right_step_parent;
     break;
   default:
     return NULL;
   }
   return *last_pos ? ELEMENT_KEY(tree, **last_pos) : NULL;
 }
References cmp, st_tree::compare, ELEMENT_KEY, HA_READ_AFTER_KEY, HA_READ_BEFORE_KEY, HA_READ_KEY_EXACT, HA_READ_KEY_OR_NEXT, HA_READ_PREFIX_LAST, HA_READ_PREFIX_LAST_OR_PREV, st_tree_element::left, NULL, st_tree::null_element, st_tree_element::right, and st_tree::root.
tree_search_next()
void* tree_search_next (TREE * tree, TREE_ELEMENT *** last_pos, int l_offs, int r_offs)
Definition at line 446 of file tree.c.
 {
   TREE_ELEMENT *x= **last_pos;
   if (ELEMENT_CHILD(x, r_offs) != &tree->null_element)
   {
     x= ELEMENT_CHILD(x, r_offs);
     *++*last_pos= x;
     while (ELEMENT_CHILD(x, l_offs) != &tree->null_element)
     {
       x= ELEMENT_CHILD(x, l_offs);
       *++*last_pos= x;
     }
     return ELEMENT_KEY(tree, x);
   }
   else
   {
     TREE_ELEMENT *y= *--*last_pos;
     while (y != &tree->null_element && x == ELEMENT_CHILD(y, r_offs))
     {
       x= y;
       y= *--*last_pos;
     }
     return y == &tree->null_element ? NULL : ELEMENT_KEY(tree, y);
   }
 }
References ELEMENT_CHILD, ELEMENT_KEY, NULL, st_tree::null_element, G3D::x, and G3D::y.
tree_walk()
int tree_walk (TREE * tree, tree_walk_action action, void * argument, TREE_WALK visit)
Definition at line 525 of file tree.c.
 {
   switch (visit) {
   case left_root_right:
     return tree_walk_left_root_right(tree,tree->root,action,argument);
   case right_root_left:
     return tree_walk_right_root_left(tree,tree->root,action,argument);
   }
   return 0;         /* Keep gcc happy */
 }
References left_root_right, right_root_left, st_tree::root, tree_walk_left_root_right(), and tree_walk_right_root_left().