Azerotcore-wotlk: spell_midsummer_ribbon_pole::spell_midsummer_ribbon_pole_AuraScript Class Reference
spell_midsummer_ribbon_pole::spell_midsummer_ribbon_pole_AuraScript Class Reference
Private Member Functions
PrepareAuraScript (spell_midsummer_ribbon_pole_AuraScript) void HandleEffectPeriodic(AuraEffect const *)
void HandleEffectApply (AuraEffect const *, AuraEffectHandleModes)
void Register () override
Additional Inherited Members
Public Member Functions inherited from AuraScript
AuraScript ()
bool _Validate (SpellInfo const *entry) override
bool _Load (Aura *aura)
void _PrepareScriptCall (AuraScriptHookType hookType, AuraApplication const *aurApp=nullptr)
void _FinishScriptCall ()
bool _IsDefaultActionPrevented ()
void PreventDefaultAction ()
SpellInfo const * GetSpellInfo () const
uint32 GetId () const
ObjectGuid GetCasterGUID () const
Unit * GetCaster () const
WorldObject * GetOwner () const
Unit * GetUnitOwner () const
DynamicObject * GetDynobjOwner () const
void Remove (uint32 removeMode=0)
Aura * GetAura () const
AuraObjectType GetType () const
int32 GetDuration () const
void SetDuration (int32 duration, bool withMods=false)
void RefreshDuration ()
time_t GetApplyTime () const
int32 GetMaxDuration () const
void SetMaxDuration (int32 duration)
int32 CalcMaxDuration () const
bool IsExpired () const
bool IsPermanent () const
uint8 GetCharges () const
void SetCharges (uint8 charges)
uint8 CalcMaxCharges () const
bool ModCharges (int8 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool DropCharge (AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
uint8 GetStackAmount () const
void SetStackAmount (uint8 num)
bool ModStackAmount (int32 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool IsPassive () const
bool IsDeathPersistent () const
bool HasEffect (uint8 effIndex) const
AuraEffect * GetEffect (uint8 effIndex) const
bool HasEffectType (AuraType type) const
Unit * GetTarget () const
AuraApplication const * GetTargetApplication () const
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual bool Validate (SpellInfo const *)
virtual bool Load ()
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from AuraScript
HookList< CheckAreaTargetHandler > DoCheckAreaTarget
HookList< AuraDispelHandler > OnDispel
HookList< AuraDispelHandler > AfterDispel
HookList< EffectApplyHandler > OnEffectApply
HookList< EffectApplyHandler > AfterEffectApply
HookList< EffectApplyHandler > OnEffectRemove
HookList< EffectApplyHandler > AfterEffectRemove
HookList< EffectPeriodicHandler > OnEffectPeriodic
HookList< EffectUpdatePeriodicHandler > OnEffectUpdatePeriodic
HookList< EffectCalcAmountHandler > DoEffectCalcAmount
HookList< EffectCalcPeriodicHandler > DoEffectCalcPeriodic
HookList< EffectCalcSpellModHandler > DoEffectCalcSpellMod
HookList< EffectAbsorbHandler > OnEffectAbsorb
HookList< EffectAbsorbHandler > AfterEffectAbsorb
HookList< EffectManaShieldHandler > OnEffectManaShield
HookList< EffectManaShieldHandler > AfterEffectManaShield
HookList< EffectSplitHandler > OnEffectSplit
HookList< CheckProcHandler > DoCheckProc
HookList< AuraProcHandler > DoPrepareProc
HookList< AuraProcHandler > OnProc
HookList< AuraProcHandler > AfterProc
HookList< EffectProcHandler > OnEffectProc
HookList< EffectProcHandler > AfterEffectProc
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Definition at line 283 of file midsummer.cpp.
Member Function Documentation
HandleEffectApply()
void spell_midsummer_ribbon_pole::spell_midsummer_ribbon_pole_AuraScript::HandleEffectApply (AuraEffect const * , AuraEffectHandleModes) inline private
Definition at line 318 of file midsummer.cpp.
         {
             Unit* ar = GetTarget();
             ar->CastSpell(ar, SPELL_RIBBON_POLE_CHANNEL_VISUAL, true);
         }
References Unit::CastSpell(), AuraScript::GetTarget(), and SPELL_RIBBON_POLE_CHANNEL_VISUAL.
Referenced by Register().
PrepareAuraScript()
spell_midsummer_ribbon_pole::spell_midsummer_ribbon_pole_AuraScript::PrepareAuraScript (spell_midsummer_ribbon_pole_AuraScript) const inline private
Definition at line 285 of file midsummer.cpp.
         {
             PreventDefaultAction();
             if (Unit* target = GetTarget())
             {
                 Creature* cr = target->FindNearestCreature(NPC_RIBBON_POLE_DEBUG_TARGET, 10.0f);
                 if (!cr)
                 {
                     target->RemoveAura(SPELL_RIBBON_POLE_CHANNEL_VISUAL);
                     SetDuration(1);
                     return;
                 }
                 if (Aura* aur = target->GetAura(SPELL_RIBBON_POLE_XP))
                     aur->SetDuration(std::min(aur->GetDuration() + 3 * MINUTE * IN_MILLISECONDS, 60 * MINUTE * IN_MILLISECONDS));
                 else
                     target->CastSpell(target, SPELL_RIBBON_POLE_XP, true);
                 if (roll_chance_i(5))
                 {
                     cr->Relocate(cr->GetPositionX(), cr->GetPositionY(), cr->GetPositionZ() - 6.5f);
                     cr->CastSpell(cr, SPELL_RIBBON_POLE_FIREWORKS, true);
                     cr->Relocate(cr->GetPositionX(), cr->GetPositionY(), cr->GetPositionZ() + 6.5f);
                 }
                 // Achievement
                 if ((time(nullptr) - GetApplyTime()) > 60 && target->GetTypeId() == TYPEID_PLAYER)
                     target->ToPlayer()->UpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, 58934, 0, target);
             }
         }
References ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, Unit::CastSpell(), WorldObject::FindNearestCreature(), AuraScript::GetApplyTime(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), AuraScript::GetTarget(), IN_MILLISECONDS, MINUTE, NPC_RIBBON_POLE_DEBUG_TARGET, AuraScript::PreventDefaultAction(), Position::Relocate(), Unit::RemoveAura(), roll_chance_i(), AuraScript::SetDuration(), SPELL_RIBBON_POLE_CHANNEL_VISUAL, SPELL_RIBBON_POLE_FIREWORKS, SPELL_RIBBON_POLE_XP, and TYPEID_PLAYER.
Register()
void spell_midsummer_ribbon_pole::spell_midsummer_ribbon_pole_AuraScript::Register () inline override private virtual
Implements _SpellScript.
Definition at line 324 of file midsummer.cpp.
         {
             OnEffectApply += AuraEffectApplyFn(spell_midsummer_ribbon_pole_AuraScript::HandleEffectApply, EFFECT_0, SPELL_AURA_PERIODIC_DUMMY, AURA_EFFECT_HANDLE_REAL);
             OnEffectPeriodic += AuraEffectPeriodicFn(spell_midsummer_ribbon_pole_AuraScript::HandleEffectPeriodic, EFFECT_0, SPELL_AURA_PERIODIC_DUMMY);
         }
References AURA_EFFECT_HANDLE_REAL, AuraEffectApplyFn, AuraEffectPeriodicFn, EFFECT_0, HandleEffectApply(), AuraScript::OnEffectApply, AuraScript::OnEffectPeriodic, and SPELL_AURA_PERIODIC_DUMMY.
The documentation for this class was generated from the following file:
src/server/scripts/Events/midsummer.cpp