Azerotcore-wotlk: npc_maghar_captive Class Reference
npc_maghar_captive Class Reference
Classes
struct npc_maghar_captiveAI
Public Member Functions
npc_maghar_captive ()
bool OnQuestAccept (Player *player, Creature *creature, const Quest *quest) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, Creature *)
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 67 of file zone_nagrand.cpp.
Constructor & Destructor Documentation
npc_maghar_captive()
npc_maghar_captive::npc_maghar_captive () inline
Definition at line 70 of file zone_nagrand.cpp.
 : CreatureScript("npc_maghar_captive") { }
Member Function Documentation
GetAI()
CreatureAI* npc_maghar_captive::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 91 of file zone_nagrand.cpp.
     {
         return new npc_maghar_captiveAI(creature);
     }
OnQuestAccept()
bool npc_maghar_captive::OnQuestAccept (Player * player, Creature * creature, const Quest * quest) inline override virtual
Reimplemented from CreatureScript.
Definition at line 72 of file zone_nagrand.cpp.
     {
         if (quest->GetQuestId() == QUEST_TOTEM_KARDASH_H)
         {
             if (npc_maghar_captiveAI* EscortAI = dynamic_cast<npc_maghar_captiveAI*>(creature->AI()))
             {
                 creature->SetStandState(UNIT_STAND_STATE_STAND);
                 creature->SetFaction(FACTION_ESCORTEE_H_NEUTRAL_ACTIVE);
                 EscortAI->Start(true, false, player->GetGUID(), quest);
                 creature->AI()->Talk(SAY_MAG_START);
                 creature->SummonCreature(NPC_MURK_RAIDER, m_afAmbushA[0] + 2.5f, m_afAmbushA[1] - 2.5f, m_afAmbushA[2], 0.0f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 25000);
                 creature->SummonCreature(NPC_MURK_PUTRIFIER, m_afAmbushA[0] - 2.5f, m_afAmbushA[1] + 2.5f, m_afAmbushA[2], 0.0f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 25000);
                 creature->SummonCreature(NPC_MURK_BRUTE, m_afAmbushA[0], m_afAmbushA[1], m_afAmbushA[2], 0.0f, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 25000);
             }
         }
         return true;
     }
References Creature::AI(), FACTION_ESCORTEE_H_NEUTRAL_ACTIVE, Object::GetGUID(), Quest::GetQuestId(), m_afAmbushA, NPC_MURK_BRUTE, NPC_MURK_PUTRIFIER, NPC_MURK_RAIDER, QUEST_TOTEM_KARDASH_H, SAY_MAG_START, Unit::SetFaction(), Unit::SetStandState(), WorldObject::SummonCreature(), CreatureAI::Talk(), TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, and UNIT_STAND_STATE_STAND.
The documentation for this class was generated from the following file:
src/server/scripts/Outland/zone_nagrand.cpp