Azerotcore-wotlk: npc_hor_leader::npc_hor_leaderAI Struct Reference
npc_hor_leader::npc_hor_leaderAI Struct Reference
Public Member Functions
npc_hor_leaderAI (Creature *creature)
void Reset () override
void DoAction (int32 actionId) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
EventMap events
bool first
bool shortver
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 175 of file halls_of_reflection.cpp.
Constructor & Destructor Documentation
npc_hor_leaderAI()
npc_hor_leader::npc_hor_leaderAI::npc_hor_leaderAI (Creature * creature) inline
Definition at line 177 of file halls_of_reflection.cpp.
                                              : NullCreatureAI(creature)
         {
             pInstance = me->GetInstanceScript();
             if (!pInstance)
                 me->IsAIEnabled = false;
             first = (pInstance && !pInstance->GetData(DATA_INTRO));
         }
References DATA_INTRO, first, ZoneScript::GetData(), WorldObject::GetInstanceScript(), Unit::IsAIEnabled, CreatureAI::me, and pInstance.
Member Function Documentation
DoAction()
void npc_hor_leader::npc_hor_leaderAI::DoAction (int32 actionId) inline override virtual
Reimplemented from UnitAI.
Definition at line 204 of file halls_of_reflection.cpp.
         {
             switch(actionId)
             {
                 case ACTION_START_INTRO:
                     events.ScheduleEvent(EVENT_START_INTRO, 0);
                     break;
                 case ACTION_SKIP_INTRO:
                     events.ScheduleEvent(EVENT_SKIP_INTRO, 0);
                     break;
             }
         }
References ACTION_SKIP_INTRO, ACTION_START_INTRO, EVENT_SKIP_INTRO, and EVENT_START_INTRO.
Reset()
void npc_hor_leader::npc_hor_leaderAI::Reset () inline override virtual
Reimplemented from UnitAI.
Definition at line 190 of file halls_of_reflection.cpp.
         {
             shortver = false;
             events.Reset();
             me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
             if (first)
             {
                 first = false;
                 events.ScheduleEvent(EVENT_PRE_INTRO_1, 10000);
                 events.ScheduleEvent(EVENT_PRE_INTRO_2, 11000);
                 events.ScheduleEvent(EVENT_PRE_INTRO_3, 17000);
             }
         }
References EMOTE_ONESHOT_NONE, EVENT_PRE_INTRO_1, EVENT_PRE_INTRO_2, EVENT_PRE_INTRO_3, first, CreatureAI::me, Object::SetUInt32Value(), shortver, and UNIT_NPC_EMOTESTATE.
UpdateAI()
void npc_hor_leader::npc_hor_leaderAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 217 of file halls_of_reflection.cpp.
         {
             events.Update(diff);
             switch(events.ExecuteEvent())
             {
                 case EVENT_PRE_INTRO_1:
                     if (pInstance)
                     {
                         me->SetVisible(true);
                         if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(NPC_DARK_RANGER_LORALEN)))
                             c->SetVisible(true);
                     }
                     break;
                 case EVENT_PRE_INTRO_2:
                     if (me->GetEntry() == NPC_JAINA_PART1)
                         Talk(SAY_JAINA_INTRO_1);
                     me->GetMotionMaster()->MovePoint(0, SpawnPos);
                     break;
                 case EVENT_PRE_INTRO_3:
                     me->SetFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_GOSSIP | UNIT_NPC_FLAG_QUESTGIVER);
                     Talk(me->GetEntry() == NPC_JAINA_PART1 ? SAY_JAINA_INTRO_2 : SAY_SYLVANAS_INTRO_1);
                     me->SetFacingTo(0.89f);
                     break;
                 case EVENT_START_INTRO:
                     shortver = false;
                     me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                     me->GetMotionMaster()->MovePoint(0, MoveThronePos);
                     if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(NPC_DARK_RANGER_LORALEN)))
                         c->GetMotionMaster()->MovePoint(0, LoralenFollowPos);
                     // Begining of intro is differents between factions as the speech sequence and timers are differents.
                     if (me->GetEntry() == NPC_JAINA_PART1)
                         events.ScheduleEvent(EVENT_INTRO_A2_1, 10000);
                     else
                         events.ScheduleEvent(EVENT_INTRO_H2_2, 10000);
                     break;
                 case EVENT_SKIP_INTRO:
                     shortver = true;
                     me->SetUInt32Value(UNIT_NPC_EMOTESTATE, (me->GetEntry() == NPC_JAINA_PART1 ? EMOTE_STATE_READY2H : EMOTE_STATE_READY1H));
                     me->GetMotionMaster()->MovePoint(0, MoveThronePos);
                     if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(NPC_DARK_RANGER_LORALEN)))
                         c->GetMotionMaster()->MovePoint(0, LoralenFollowPos);
                     events.ScheduleEvent(EVENT_INTRO_LK_1, 0);
                     break;
                 // A2 Intro Events
                 case EVENT_INTRO_A2_1:
                     Talk(SAY_JAINA_INTRO_3);
                     events.ScheduleEvent(EVENT_INTRO_A2_2, 5000);
                     break;
                 case EVENT_INTRO_A2_2:
                     Talk(SAY_JAINA_INTRO_4);
                     events.ScheduleEvent(EVENT_INTRO_A2_3, 10000);
                     break;
                 case EVENT_INTRO_A2_3:
                     pInstance->HandleGameObject(pInstance->GetGuidData(GO_FROSTMOURNE), true);
                     me->CastSpell(me, SPELL_FROSTMOURNE_SPAWN_SOUND, true);
                     me->CastSpell(me, SPELL_ARCANE_CAST_VISUAL, false);
                     events.ScheduleEvent(EVENT_INTRO_A2_4, 10000);
                     break;
                 case EVENT_INTRO_A2_4:
                     if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                     {
                         pUther->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                         pUther->SetVisible(true);
                         if (Aura* a = pUther->AddAura(SPELL_SHADOWMOURNE_VISUAL, pUther))
                             a->SetDuration(8000);
                     }
                     events.ScheduleEvent(EVENT_INTRO_A2_5, 2000);
                     break;
                 case EVENT_INTRO_A2_5:
                     if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                         pUther->AI()->Talk(SAY_UTHER_INTRO_A2_1);
                     events.ScheduleEvent(EVENT_INTRO_A2_6, 3000);
                     break;
                 case EVENT_INTRO_A2_6:
                     Talk(SAY_JAINA_INTRO_5);
                     events.ScheduleEvent(EVENT_INTRO_A2_7, 6000);
                     break;
                 case EVENT_INTRO_A2_7:
                     if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                         pUther->AI()->Talk(SAY_UTHER_INTRO_A2_2);
                     events.ScheduleEvent(EVENT_INTRO_A2_8, 6500);
                     break;
                 case EVENT_INTRO_A2_8:
                     Talk(SAY_JAINA_INTRO_6);
                     events.ScheduleEvent(EVENT_INTRO_A2_9, 2000);
                     break;
                 case EVENT_INTRO_A2_9:
                     if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                         pUther->AI()->Talk(SAY_UTHER_INTRO_A2_3);
                     events.ScheduleEvent(EVENT_INTRO_A2_10, 9000);
                     break;
                 case EVENT_INTRO_A2_10:
                     Talk(SAY_JAINA_INTRO_7);
                     events.ScheduleEvent(EVENT_INTRO_A2_11, 5000);
                     break;
                 case EVENT_INTRO_A2_11:
                     if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                         pUther->AI()->Talk(SAY_UTHER_INTRO_A2_4);
                     events.ScheduleEvent(EVENT_INTRO_A2_12, 11000);
                     break;
                 case EVENT_INTRO_A2_12:
                     Talk(SAY_JAINA_INTRO_8);
                     events.ScheduleEvent(EVENT_INTRO_A2_13, 4000);
                     break;
                 case EVENT_INTRO_A2_13:
                     if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                         pUther->AI()->Talk(SAY_UTHER_INTRO_A2_5);
                     events.ScheduleEvent(EVENT_INTRO_A2_14, 12500);
                     break;
                 case EVENT_INTRO_A2_14:
                     Talk(SAY_JAINA_INTRO_9);
                     events.ScheduleEvent(EVENT_INTRO_A2_15, 10000);
                     break;
                 case EVENT_INTRO_A2_15:
                     if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                         pUther->AI()->Talk(SAY_UTHER_INTRO_A2_6);
                     events.ScheduleEvent(EVENT_INTRO_A2_16, 24000);
                     break;
                 case EVENT_INTRO_A2_16:
                     if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                         pUther->AI()->Talk(SAY_UTHER_INTRO_A2_7);
                     events.ScheduleEvent(EVENT_INTRO_A2_17, 4000);
                     break;
                 case EVENT_INTRO_A2_17:
                     Talk(SAY_JAINA_INTRO_10);
                     events.ScheduleEvent(EVENT_INTRO_A2_18, 2000);
                     break;
                 case EVENT_INTRO_A2_18:
                     if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                     {
                         pUther->HandleEmoteCommand(EMOTE_ONESHOT_NO);
                         pUther->AI()->Talk(SAY_UTHER_INTRO_A2_8);
                     }
                     events.ScheduleEvent(EVENT_INTRO_A2_19, 11000);
                     break;
                 case EVENT_INTRO_A2_19:
                     Talk(SAY_JAINA_INTRO_11);
                     events.ScheduleEvent(EVENT_INTRO_LK_1, 2000);
                     break;
                 // H2 Intro Events
                 case EVENT_INTRO_H2_2:
                     Talk(SAY_SYLVANAS_INTRO_2);
                     events.ScheduleEvent(EVENT_INTRO_H2_3, 6000);
                     break;
                 case EVENT_INTRO_H2_3:
                     Talk(SAY_SYLVANAS_INTRO_3);
                     pInstance->HandleGameObject(pInstance->GetGuidData(GO_FROSTMOURNE), true);
                     me->CastSpell(me, SPELL_FROSTMOURNE_SPAWN_SOUND, true);
                     me->CastSpell(me, SPELL_ARCANE_CAST_VISUAL, false);
                     events.ScheduleEvent(EVENT_INTRO_H2_4, 6000);
                     break;
                 case EVENT_INTRO_H2_4:
                     if (Creature* pUther = pInstance->instance->GetCreature(pInstance->GetGuidData(NPC_UTHER)))
                     {
                         pUther->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_NONE);
                         pUther->SetVisible(true);
                         if (Aura* a = pUther->AddAura(SPELL_SHADOWMOURNE_VISUAL, pUther))
                             a->SetDuration(8000);
                     }
                     events.ScheduleEvent(EVENT_INTRO_H2_5, 2000);
                     break;
                 case EVENT_INTRO_H2_5:
                     if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                         pUther->AI()->Talk(SAY_UTHER_INTRO_H2_1);
                     events.ScheduleEvent(EVENT_INTRO_H2_6, 11000);
                     break;
                 case EVENT_INTRO_H2_6:
                     Talk(SAY_SYLVANAS_INTRO_4);
                     events.ScheduleEvent(EVENT_INTRO_H2_7, 3000);
                     break;
                 case EVENT_INTRO_H2_7:
                     if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                         pUther->AI()->Talk(SAY_UTHER_INTRO_H2_2);
                     events.ScheduleEvent(EVENT_INTRO_H2_8, 6000);
                     break;
                 case EVENT_INTRO_H2_8:
                     Talk(SAY_SYLVANAS_INTRO_5);
                     events.ScheduleEvent(EVENT_INTRO_H2_9, 5000);
                     break;
                 case EVENT_INTRO_H2_9:
                     if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                         pUther->AI()->Talk(SAY_UTHER_INTRO_H2_3);
                     events.ScheduleEvent(EVENT_INTRO_H2_10, 19000);
                     break;
                 case EVENT_INTRO_H2_10:
                     Talk(SAY_SYLVANAS_INTRO_6);
                     events.ScheduleEvent(EVENT_INTRO_H2_11, 1500);
                     break;
                 case EVENT_INTRO_H2_11:
                     if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                         pUther->AI()->Talk(SAY_UTHER_INTRO_H2_4);
                     events.ScheduleEvent(EVENT_INTRO_H2_12, 19500);
                     break;
                 case EVENT_INTRO_H2_12:
                     Talk(SAY_SYLVANAS_INTRO_7);
                     events.ScheduleEvent(EVENT_INTRO_H2_13, 2000);
                     break;
                 case EVENT_INTRO_H2_13:
                     if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                     {
                         pUther->HandleEmoteCommand(EMOTE_ONESHOT_NO);
                         pUther->AI()->Talk(SAY_UTHER_INTRO_H2_5);
                     }
                     events.ScheduleEvent(EVENT_INTRO_H2_14, 12000);
                     break;
                 case EVENT_INTRO_H2_14:
                     if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                         pUther->AI()->Talk(SAY_UTHER_INTRO_H2_6);
                     events.ScheduleEvent(EVENT_INTRO_H2_15, 8000);
                     break;
                 case EVENT_INTRO_H2_15:
                     Talk(SAY_SYLVANAS_INTRO_8);
                     events.ScheduleEvent(EVENT_INTRO_LK_1, 2000);
                     break;
                 // Remaining Intro Events common for both faction
                 case EVENT_INTRO_LK_1:
                     if (Creature* pLichKing = pInstance->instance->GetCreature(pInstance->GetGuidData(NPC_LICH_KING_EVENT)))
                     {
                         pInstance->HandleGameObject(pInstance->GetGuidData(GO_ARTHAS_DOOR), true);
                         pLichKing->SetVisible(true);
                         pLichKing->GetMotionMaster()->MovePoint(0, LichKingMoveThronePos, false);
                     }
                     if (!shortver)
                         if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
{
                             if (me->GetEntry() == NPC_JAINA_PART1)
                                 pUther->AI()->Talk(SAY_UTHER_INTRO_A2_9);
                             else
                                 pUther->AI()->Talk(SAY_UTHER_INTRO_H2_7);
                         }
                     events.ScheduleEvent(EVENT_INTRO_LK_1_2, 2000);
                     events.ScheduleEvent(EVENT_INTRO_LK_1_3, 4000);
                     events.ScheduleEvent(EVENT_INTRO_LK_2, 11000);
                     break;
                 case EVENT_INTRO_LK_1_2:
                     if (!shortver)
                         if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                             pUther->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_COWER);
                     break;
                 case EVENT_INTRO_LK_1_3:
                     pInstance->HandleGameObject(pInstance->GetGuidData(GO_ARTHAS_DOOR), false);
                     break;
                 case EVENT_INTRO_LK_2:
                     if (!shortver)
                         if (Creature* pLichKing = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_LICH_KING_EVENT)))
                             pLichKing->AI()->Talk(SAY_LK_INTRO_1);
                     events.ScheduleEvent(EVENT_INTRO_LK_3, 2000);
                     break;
                 case EVENT_INTRO_LK_3:
                     if (!shortver)
                         if (Creature* pUther = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_UTHER)))
                             pUther->SetVisible(false);
                     events.ScheduleEvent(EVENT_INTRO_LK_4, 4000);
                     break;
                 case EVENT_INTRO_LK_4:
                     if (Creature* pLichKing = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_LICH_KING_EVENT)))
                         pLichKing->AI()->Talk(SAY_LK_INTRO_2);
                     events.ScheduleEvent(EVENT_INTRO_LK_4_2, 10000);
                     break;
                 case EVENT_INTRO_LK_4_2:
                     if (Creature* pLichKing = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_LICH_KING_EVENT)))
                     {
                         pLichKing->LoadEquipment(1, true);
                         pLichKing->SendMovementFlagUpdate();
                         pLichKing->CastSpell(pLichKing, SPELL_FROSTMOURNE_EQUIP, false);
                         pInstance->HandleGameObject(pInstance->GetGuidData(GO_FROSTMOURNE), false);
                         events.ScheduleEvent(EVENT_INTRO_LK_4_3, 1750);
                     }
                     events.ScheduleEvent(EVENT_INTRO_LK_5, 6000);
                     break;
                 case EVENT_INTRO_LK_4_3:
                     if (GameObject* go = pInstance->instance->GetGameObject(pInstance->GetGuidData(GO_FROSTMOURNE)))
                         go->SetPhaseMask(2, true);
                     break;
                 case EVENT_INTRO_LK_5:
                     if (Creature* pFalric = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(DATA_FALRIC)))
                     {
                         pFalric->UpdatePosition(5274.9f, 2039.2f, 709.319f, 5.4619f, true);
                         pFalric->StopMovingOnCurrentPos();
                         pFalric->SetVisible(true);
                         if (pFalric->IsAlive())
{
                             pFalric->GetMotionMaster()->MovePoint(0, FalricMovePos);
                             if (Aura* a = pFalric->AddAura(SPELL_SHADOWMOURNE_VISUAL, pFalric))
                                 a->SetDuration(8000);
                         }
                     }
                     if (Creature* pMarwyn = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(DATA_MARWYN)))
                     {
                         pMarwyn->UpdatePosition(5343.77f, 1973.86f, 709.319f, 2.35173f, true);
                         pMarwyn->StopMovingOnCurrentPos();
                         pMarwyn->SetVisible(true);
                         if (pMarwyn->IsAlive())
{
                             pMarwyn->GetMotionMaster()->MovePoint(0, MarwynMovePos);
                             if (Aura* a = pMarwyn->AddAura(SPELL_SHADOWMOURNE_VISUAL, pMarwyn))
                                 a->SetDuration(8000);
                         }
                     }
                     if (Creature* pLichKing = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_LICH_KING_EVENT)))
                         pLichKing->AI()->Talk(SAY_LK_INTRO_3);
                     events.ScheduleEvent(EVENT_INTRO_LK_5_2, 5000);
                     events.ScheduleEvent(EVENT_INTRO_LK_6, 8000);
                     break;
                 case EVENT_INTRO_LK_5_2:
                     if (Creature* pLichKing = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_LICH_KING_EVENT)))
                         pLichKing->GetMotionMaster()->MovePoint(0, LichKingMoveAwayPos, false);
                     break;
                 case EVENT_INTRO_LK_6:
                     if (Creature* pFalric = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(DATA_FALRIC)))
                         pFalric->AI()->Talk(SAY_FALRIC_INTRO_1);
                     events.ScheduleEvent(EVENT_INTRO_LK_7, 2000);
                     break;
                 case EVENT_INTRO_LK_7:
                     if (Creature* pMarwyn = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(DATA_MARWYN)))
                         pMarwyn->AI()->Talk(SAY_MARWYN_INTRO_1);
                     events.ScheduleEvent(EVENT_INTRO_LK_8, 2000);
                     break;
                 case EVENT_INTRO_LK_8:
                     if (Creature* pFalric = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(DATA_FALRIC)))
                         pFalric->AI()->Talk(SAY_FALRIC_INTRO_2);
                     pInstance->SetData(ACTION_SHOW_TRASH, 1);
                     pInstance->HandleGameObject(pInstance->GetGuidData(GO_ARTHAS_DOOR), true);
                     events.ScheduleEvent(EVENT_INTRO_LK_9, 5000);
                     break;
                 case EVENT_INTRO_LK_9:
                     if (me->GetEntry() == NPC_JAINA_PART1)
                         Talk(SAY_JAINA_INTRO_END);
                     else
                         Talk(SAY_SYLVANAS_INTRO_END);
                     me->GetMotionMaster()->MovePoint(0, LichKingMoveAwayPos, false);
                     if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(NPC_DARK_RANGER_LORALEN)))
                         c->GetMotionMaster()->MovePoint(0, LichKingMoveAwayPos, false);
                     events.ScheduleEvent(EVENT_INTRO_END, 14000);
                     break;
                 case EVENT_INTRO_END:
                     pInstance->HandleGameObject(pInstance->GetGuidData(GO_ARTHAS_DOOR), false);
                     pInstance->HandleGameObject(pInstance->GetGuidData(GO_FRONT_DOOR), false);
                     events.ScheduleEvent(EVENT_INTRO_END_SET, 10000);
                     break;
                 case EVENT_INTRO_END_SET:
                     if (Creature* pLichKing = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_LICH_KING_EVENT)))
                         pLichKing->SetVisible(false);
                     if (Creature* c = pInstance->instance->GetCreature(pInstance->GetGuidData(NPC_DARK_RANGER_LORALEN)))
                         c->SetVisible(false);
                     me->SetVisible(false);
                     pInstance->SetData(DATA_INTRO, DONE);
                     break;
             }
         }
References mpq::a, ACTION_SHOW_TRASH, mpq::c, Unit::CastSpell(), DATA_FALRIC, DATA_INTRO, DATA_MARWYN, diff(), DONE, EMOTE_ONESHOT_NO, EMOTE_ONESHOT_NONE, EMOTE_STATE_COWER, EMOTE_STATE_READY1H, EMOTE_STATE_READY2H, EVENT_INTRO_A2_1, EVENT_INTRO_A2_10, EVENT_INTRO_A2_11, EVENT_INTRO_A2_12, EVENT_INTRO_A2_13, EVENT_INTRO_A2_14, EVENT_INTRO_A2_15, EVENT_INTRO_A2_16, EVENT_INTRO_A2_17, EVENT_INTRO_A2_18, EVENT_INTRO_A2_19, EVENT_INTRO_A2_2, EVENT_INTRO_A2_3, EVENT_INTRO_A2_4, EVENT_INTRO_A2_5, EVENT_INTRO_A2_6, EVENT_INTRO_A2_7, EVENT_INTRO_A2_8, EVENT_INTRO_A2_9, EVENT_INTRO_END, EVENT_INTRO_END_SET, EVENT_INTRO_H2_10, EVENT_INTRO_H2_11, EVENT_INTRO_H2_12, EVENT_INTRO_H2_13, EVENT_INTRO_H2_14, EVENT_INTRO_H2_15, EVENT_INTRO_H2_2, EVENT_INTRO_H2_3, EVENT_INTRO_H2_4, EVENT_INTRO_H2_5, EVENT_INTRO_H2_6, EVENT_INTRO_H2_7, EVENT_INTRO_H2_8, EVENT_INTRO_H2_9, EVENT_INTRO_LK_1, EVENT_INTRO_LK_1_2, EVENT_INTRO_LK_1_3, EVENT_INTRO_LK_2, EVENT_INTRO_LK_3, EVENT_INTRO_LK_4, EVENT_INTRO_LK_4_2, EVENT_INTRO_LK_4_3, EVENT_INTRO_LK_5, EVENT_INTRO_LK_5_2, EVENT_INTRO_LK_6, EVENT_INTRO_LK_7, EVENT_INTRO_LK_8, EVENT_INTRO_LK_9, EVENT_PRE_INTRO_1, EVENT_PRE_INTRO_2, EVENT_PRE_INTRO_3, EVENT_SKIP_INTRO, EVENT_START_INTRO, FalricMovePos, Map::GetCreature(), ObjectAccessor::GetCreature(), Object::GetEntry(), Map::GetGameObject(), InstanceScript::GetGuidData(), Unit::GetMotionMaster(), GO_ARTHAS_DOOR, GO_FRONT_DOOR, GO_FROSTMOURNE, InstanceScript::HandleGameObject(), InstanceScript::instance, LichKingMoveAwayPos, LichKingMoveThronePos, LoralenFollowPos, MarwynMovePos, CreatureAI::me, MotionMaster::MovePoint(), MoveThronePos, NPC_DARK_RANGER_LORALEN, NPC_JAINA_PART1, NPC_LICH_KING_EVENT, NPC_UTHER, pInstance, SAY_FALRIC_INTRO_1, SAY_FALRIC_INTRO_2, SAY_JAINA_INTRO_1, SAY_JAINA_INTRO_10, SAY_JAINA_INTRO_11, SAY_JAINA_INTRO_2, SAY_JAINA_INTRO_3, SAY_JAINA_INTRO_4, SAY_JAINA_INTRO_5, SAY_JAINA_INTRO_6, SAY_JAINA_INTRO_7, SAY_JAINA_INTRO_8, SAY_JAINA_INTRO_9, SAY_JAINA_INTRO_END, SAY_LK_INTRO_1, SAY_LK_INTRO_2, SAY_LK_INTRO_3, SAY_MARWYN_INTRO_1, SAY_SYLVANAS_INTRO_1, SAY_SYLVANAS_INTRO_2, SAY_SYLVANAS_INTRO_3, SAY_SYLVANAS_INTRO_4, SAY_SYLVANAS_INTRO_5, SAY_SYLVANAS_INTRO_6, SAY_SYLVANAS_INTRO_7, SAY_SYLVANAS_INTRO_8, SAY_SYLVANAS_INTRO_END, SAY_UTHER_INTRO_A2_1, SAY_UTHER_INTRO_A2_2, SAY_UTHER_INTRO_A2_3, SAY_UTHER_INTRO_A2_4, SAY_UTHER_INTRO_A2_5, SAY_UTHER_INTRO_A2_6, SAY_UTHER_INTRO_A2_7, SAY_UTHER_INTRO_A2_8, SAY_UTHER_INTRO_A2_9, SAY_UTHER_INTRO_H2_1, SAY_UTHER_INTRO_H2_2, SAY_UTHER_INTRO_H2_3, SAY_UTHER_INTRO_H2_4, SAY_UTHER_INTRO_H2_5, SAY_UTHER_INTRO_H2_6, SAY_UTHER_INTRO_H2_7, ZoneScript::SetData(), Unit::SetFacingTo(), Object::SetFlag(), Object::SetUInt32Value(), Unit::SetVisible(), shortver, SpawnPos, SPELL_ARCANE_CAST_VISUAL, SPELL_FROSTMOURNE_EQUIP, SPELL_FROSTMOURNE_SPAWN_SOUND, SPELL_SHADOWMOURNE_VISUAL, CreatureAI::Talk(), UNIT_NPC_EMOTESTATE, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAG_QUESTGIVER, and UNIT_NPC_FLAGS.
Member Data Documentation
events
EventMap npc_hor_leader::npc_hor_leaderAI::events
Definition at line 186 of file halls_of_reflection.cpp.
first
bool npc_hor_leader::npc_hor_leaderAI::first
Definition at line 187 of file halls_of_reflection.cpp.
Referenced by npc_hor_leaderAI(), and Reset().
pInstance
InstanceScript* npc_hor_leader::npc_hor_leaderAI::pInstance
Definition at line 185 of file halls_of_reflection.cpp.
Referenced by npc_hor_leaderAI(), and UpdateAI().
shortver
bool npc_hor_leader::npc_hor_leaderAI::shortver
Definition at line 188 of file halls_of_reflection.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/FrozenHalls/HallsOfReflection/halls_of_reflection.cpp