Azerotcore-wotlk: npc_torloth_the_magnificent::npc_torloth_the_magnificentAI Struct Reference
npc_torloth_the_magnificent::npc_torloth_the_magnificentAI Struct Reference
Public Member Functions
npc_torloth_the_magnificentAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *) override
void HandleAnimation ()
void UpdateAI (uint32 diff) override
void JustDied (Unit *killer) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
uint32 AnimationTimer
uint32 SpellTimer1
uint32 SpellTimer2
uint32 SpellTimer3
uint8 AnimationCount
ObjectGuid LordIllidanGUID
ObjectGuid AggroTargetGUID
bool Timers
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1090 of file zone_shadowmoon_valley.cpp.
Constructor & Destructor Documentation
npc_torloth_the_magnificentAI()
npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::npc_torloth_the_magnificentAI (Creature * creature) inline
Definition at line 1092 of file zone_shadowmoon_valley.cpp.
 : ScriptedAI(creature) { }
Member Function Documentation
EnterCombat()
void npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1116 of file zone_shadowmoon_valley.cpp.
 { }
HandleAnimation()
void npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::HandleAnimation () inline
Definition at line 1118 of file zone_shadowmoon_valley.cpp.
         {
             Creature* creature = me;
             if (TorlothAnim[AnimationCount].creature == 1)
             {
                 creature = (ObjectAccessor::GetCreature(*me, LordIllidanGUID));
                 if (!creature)
                     return;
             }
             AnimationTimer = TorlothAnim[AnimationCount].Timer;
             switch (AnimationCount)
             {
                 case 0:
                     me->SetUInt32Value(UNIT_FIELD_BYTES_1, 8);
                     break;
                 case 3:
                     me->RemoveFlag(UNIT_FIELD_BYTES_1, 8);
                     break;
                 case 5:
                     if (Player* AggroTarget = ObjectAccessor::GetPlayer(*me, AggroTargetGUID))
                     {
                         me->SetTarget(AggroTarget->GetGUID());
                         me->AddThreat(AggroTarget, 1);
                         me->HandleEmoteCommand(EMOTE_ONESHOT_POINT);
                     }
                     break;
                 case 6:
                     if (Player* AggroTarget = ObjectAccessor::GetPlayer(*me, AggroTargetGUID))
                     {
                         me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                         me->ClearUnitState(UNIT_STATE_ROOT);
                         float x, y, z;
                         AggroTarget->GetPosition(x, y, z);
                         me->GetMotionMaster()->MovePoint(0, x, y, z);
                     }
                     break;
             }
             ++AnimationCount;
         }
References Unit::AddThreat(), AggroTargetGUID, AnimationCount, AnimationTimer, Unit::ClearUnitState(), EMOTE_ONESHOT_POINT, ObjectAccessor::GetCreature(), Unit::GetMotionMaster(), ObjectAccessor::GetPlayer(), Unit::HandleEmoteCommand(), LordIllidanGUID, ScriptedAI::me, MotionMaster::MovePoint(), Object::RemoveFlag(), Creature::SetTarget(), Object::SetUInt32Value(), TorlothCinematic::Timer, TorlothAnim, UNIT_FIELD_BYTES_1, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and UNIT_STATE_ROOT.
Referenced by UpdateAI().
JustDied()
void npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::JustDied (Unit * killer) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1213 of file zone_shadowmoon_valley.cpp.
         {
             switch (killer->GetTypeId())
             {
                 case TYPEID_UNIT:
                     if (Unit* owner = killer->GetOwner())
                         if (Player* player = owner->ToPlayer())
                             player->GroupEventHappens(QUEST_BATTLE_OF_THE_CRIMSON_WATCH, me);
                     break;
                 case TYPEID_PLAYER:
                     if (Player* player = killer->ToPlayer())
                         player->GroupEventHappens(QUEST_BATTLE_OF_THE_CRIMSON_WATCH, me);
                     break;
                 default:
                     break;
             }
             if (Creature* LordIllidan = (ObjectAccessor::GetCreature(*me, LordIllidanGUID)))
                 LordIllidan->AI()->EnterEvadeMode();
         }
References ObjectAccessor::GetCreature(), Unit::GetOwner(), Object::GetTypeId(), LordIllidanGUID, ScriptedAI::me, QUEST_BATTLE_OF_THE_CRIMSON_WATCH, Object::ToPlayer(), TYPEID_PLAYER, and TYPEID_UNIT.
Reset()
void npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1103 of file zone_shadowmoon_valley.cpp.
         {
             AnimationTimer = 4000;
             AnimationCount = 0;
             LordIllidanGUID.Clear();
             AggroTargetGUID.Clear();
             Timers = false;
             me->AddUnitState(UNIT_STATE_ROOT);
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
             me->SetTarget();
         }
References Unit::AddUnitState(), AggroTargetGUID, AnimationCount, AnimationTimer, ObjectGuid::Clear(), LordIllidanGUID, ScriptedAI::me, Object::SetFlag(), Creature::SetTarget(), UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and UNIT_STATE_ROOT.
UpdateAI()
void npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1163 of file zone_shadowmoon_valley.cpp.
         {
             if (AnimationTimer)
             {
                 if (AnimationTimer <= diff)
                 {
                     HandleAnimation();
                 }
                 else AnimationTimer -= diff;
             }
             if (AnimationCount < 6)
             {
                 me->CombatStop();
             }
             else if (!Timers)
             {
                 SpellTimer1 = SpawnCast[6].Timer1;
                 SpellTimer2 = SpawnCast[7].Timer1;
                 SpellTimer3 = SpawnCast[8].Timer1;
                 Timers = true;
             }
             if (Timers)
             {
                 if (SpellTimer1 <= diff)
                 {
                     DoCastVictim(SpawnCast[6].SpellId);//Cleave
                     SpellTimer1 = SpawnCast[6].Timer2 + (rand() % 10 * 1000);
                 }
                 else SpellTimer1 -= diff;
                 if (SpellTimer2 <= diff)
                 {
                     DoCastVictim(SpawnCast[7].SpellId);//Shadowfury
                     SpellTimer2 = SpawnCast[7].Timer2 + (rand() % 5 * 1000);
                 }
                 else SpellTimer2 -= diff;
                 if (SpellTimer3 <= diff)
                 {
                     DoCast(me, SpawnCast[8].SpellId);
                     SpellTimer3 = SpawnCast[8].Timer2 + (rand() % 7 * 1000); //Spell Reflection
                 }
                 else SpellTimer3 -= diff;
             }
             DoMeleeAttackIfReady();
         }
References AnimationCount, AnimationTimer, Unit::CombatStop(), UnitAI::DoCast(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), HandleAnimation(), ScriptedAI::me, SpawnCast, SpellTimer1, SpellTimer2, SpellTimer3, SpawnSpells::Timer1, and SpawnSpells::Timer2.
Member Data Documentation
AggroTargetGUID
ObjectGuid npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::AggroTargetGUID
Definition at line 1099 of file zone_shadowmoon_valley.cpp.
Referenced by HandleAnimation(), and Reset().
AnimationCount
uint8 npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::AnimationCount
Definition at line 1096 of file zone_shadowmoon_valley.cpp.
Referenced by HandleAnimation(), Reset(), and UpdateAI().
AnimationTimer
uint32 npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::AnimationTimer
Definition at line 1094 of file zone_shadowmoon_valley.cpp.
Referenced by HandleAnimation(), Reset(), and UpdateAI().
LordIllidanGUID
ObjectGuid npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::LordIllidanGUID
Definition at line 1098 of file zone_shadowmoon_valley.cpp.
Referenced by HandleAnimation(), JustDied(), and Reset().
SpellTimer1
uint32 npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::SpellTimer1
Definition at line 1094 of file zone_shadowmoon_valley.cpp.
Referenced by UpdateAI().
SpellTimer2
uint32 npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::SpellTimer2
Definition at line 1094 of file zone_shadowmoon_valley.cpp.
Referenced by UpdateAI().
SpellTimer3
uint32 npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::SpellTimer3
Definition at line 1094 of file zone_shadowmoon_valley.cpp.
Referenced by UpdateAI().
Timers
bool npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::Timers
Definition at line 1101 of file zone_shadowmoon_valley.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/zone_shadowmoon_valley.cpp