Azerotcore-wotlk: boss_garfrost::boss_garfrostAI Struct Reference
boss_garfrost::boss_garfrostAI Struct Reference
Public Member Functions
boss_garfrostAI (Creature *creature)
void Reset () override
void SetData (uint32 id, uint32) override
void EnterCombat (Unit *) override
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void MovementInform (uint32 type, uint32 id) override
void SpellHitTarget (Unit *, const SpellInfo *spell) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *who) override
void EnterEvadeMode () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
EventMap events
uint8 phase
bool bCanSayBoulderHit
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 79 of file boss_forgemaster_garfrost.cpp.
Constructor & Destructor Documentation
boss_garfrostAI()
boss_garfrost::boss_garfrostAI::boss_garfrostAI (Creature * creature) inline
Definition at line 81 of file boss_forgemaster_garfrost.cpp.
                                             : ScriptedAI(creature)
         {
             pInstance = creature->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), and pInstance.
Member Function Documentation
DamageTaken()
void boss_garfrost::boss_garfrostAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 124 of file boss_forgemaster_garfrost.cpp.
         {
             if (phase == 0 && !HealthAbovePct(66) && !me->HasUnitState(UNIT_STATE_ROOT))
             {
                 phase = 1;
                 me->SetReactState(REACT_PASSIVE);
                 me->SetTarget();
                 me->SendMeleeAttackStop(me->GetVictim());
                 events.DelayEvents(8000);
                 me->CastSpell(me, SPELL_THUNDERING_STOMP, false);
                 events.RescheduleEvent(EVENT_JUMP, 1250);
                 return;
             }
             if (phase == 1 && !HealthAbovePct(33) && !me->HasUnitState(UNIT_STATE_ROOT))
             {
                 events.CancelEvent(EVENT_SPELL_CHILLING_WAVE);
                 phase = 2;
                 me->SetReactState(REACT_PASSIVE);
                 me->SetTarget();
                 me->SendMeleeAttackStop(me->GetVictim());
                 events.DelayEvents(8000);
                 me->CastSpell(me, SPELL_THUNDERING_STOMP, false);
                 events.RescheduleEvent(EVENT_JUMP, 1250);
                 return;
             }
         }
References Unit::CastSpell(), EVENT_JUMP, EVENT_SPELL_CHILLING_WAVE, Unit::GetVictim(), Unit::HasUnitState(), ScriptedAI::HealthAbovePct(), ScriptedAI::me, REACT_PASSIVE, Unit::SendMeleeAttackStop(), Creature::SetReactState(), Creature::SetTarget(), SPELL_THUNDERING_STOMP, and UNIT_STATE_ROOT.
EnterCombat()
void boss_garfrost::boss_garfrostAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 112 of file boss_forgemaster_garfrost.cpp.
         {
             me->CastSpell(me, SPELL_PERMAFROST, true);
             Talk(SAY_AGGRO);
             DoZoneInCombat();
             events.RescheduleEvent(EVENT_SPELL_THROW_SARONITE, urand(5000, 7500));
             if (pInstance)
                 pInstance->SetData(DATA_GARFROST, IN_PROGRESS);
         }
References Unit::CastSpell(), DATA_GARFROST, CreatureAI::DoZoneInCombat(), EVENT_SPELL_THROW_SARONITE, IN_PROGRESS, ScriptedAI::me, pInstance, SAY_AGGRO, ZoneScript::SetData(), SPELL_PERMAFROST, CreatureAI::Talk(), and urand().
EnterEvadeMode()
void boss_garfrost::boss_garfrostAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 292 of file boss_forgemaster_garfrost.cpp.
         {
             me->SetControlled(false, UNIT_STATE_ROOT);
             me->DisableRotate(false);
             ScriptedAI::EnterEvadeMode();
         }
References Unit::DisableRotate(), CreatureAI::EnterEvadeMode(), ScriptedAI::me, Unit::SetControlled(), and UNIT_STATE_ROOT.
Referenced by UpdateAI().
JustDied()
void boss_garfrost::boss_garfrostAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 279 of file boss_forgemaster_garfrost.cpp.
         {
             Talk(SAY_DEATH);
             if (pInstance)
                 pInstance->SetData(DATA_GARFROST, DONE);
         }
References DATA_GARFROST, DONE, pInstance, SAY_DEATH, ZoneScript::SetData(), and CreatureAI::Talk().
KilledUnit()
void boss_garfrost::boss_garfrostAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 286 of file boss_forgemaster_garfrost.cpp.
         {
             if (who->GetTypeId() == TYPEID_PLAYER)
                 Talk(SAY_SLAY_1);
         }
References Object::GetTypeId(), SAY_SLAY_1, CreatureAI::Talk(), and TYPEID_PLAYER.
MovementInform()
void boss_garfrost::boss_garfrostAI::MovementInform (uint32 type, uint32 id) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 152 of file boss_forgemaster_garfrost.cpp.
         {
             if (type != EFFECT_MOTION_TYPE || id != 0)
                 return;
             if (phase == 1)
             {
                 me->SetControlled(true, UNIT_STATE_ROOT);
                 me->CastSpell(me, SPELL_FORGE_BLADE, false);
                 Talk(SAY_FORGE_1);
             }
             else if (phase == 2)
             {
                 me->SetControlled(true, UNIT_STATE_ROOT);
                 me->RemoveAurasDueToSpell(SPELL_FORGE_BLADE);
                 me->CastSpell(me, SPELL_FORGE_MACE, false);
                 Talk(SAY_FORGE_2);
             }
         }
References Unit::CastSpell(), EFFECT_MOTION_TYPE, ScriptedAI::me, Unit::RemoveAurasDueToSpell(), SAY_FORGE_1, SAY_FORGE_2, Unit::SetControlled(), SPELL_FORGE_BLADE, SPELL_FORGE_MACE, CreatureAI::Talk(), and UNIT_STATE_ROOT.
Reset()
void boss_garfrost::boss_garfrostAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 91 of file boss_forgemaster_garfrost.cpp.
         {
             me->RemoveAura(SPELL_PERMAFROST);
             SetEquipmentSlots(true);
             me->SetReactState(REACT_AGGRESSIVE);
             me->SetControlled(false, UNIT_STATE_ROOT);
             me->DisableRotate(false);
             phase = 0;
             bCanSayBoulderHit = true;
             events.Reset();
             if (pInstance)
                 pInstance->SetData(DATA_GARFROST, NOT_STARTED);
         }
References bCanSayBoulderHit, DATA_GARFROST, Unit::DisableRotate(), ScriptedAI::me, NOT_STARTED, pInstance, REACT_AGGRESSIVE, Unit::RemoveAura(), Unit::SetControlled(), ZoneScript::SetData(), ScriptedAI::SetEquipmentSlots(), Creature::SetReactState(), SPELL_PERMAFROST, and UNIT_STATE_ROOT.
SetData()
void boss_garfrost::boss_garfrostAI::SetData (uint32 id, uint32) inline override virtual
Reimplemented from UnitAI.
Definition at line 106 of file boss_forgemaster_garfrost.cpp.
         {
             if (id == 1 && pInstance)
                 pInstance->SetData(DATA_ACHIEV_ELEVEN, 0);
         }
References DATA_ACHIEV_ELEVEN, pInstance, and ZoneScript::SetData().
SpellHitTarget()
void boss_garfrost::boss_garfrostAI::SpellHitTarget (Unit * , const SpellInfo * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 172 of file boss_forgemaster_garfrost.cpp.
         {
             if (spell->Id == uint32(SPELL_SARONITE_TRIGGERED))
             {
                 if (bCanSayBoulderHit)
                 {
                     bCanSayBoulderHit = false;
                     Talk(SAY_BOULDER_HIT);
                 }
             }
             if (spell->Id == uint32(SPELL_FORGE_BLADE))
             {
                 events.RescheduleEvent(EVENT_SPELL_CHILLING_WAVE, 10000);
                 SetEquipmentSlots(false, EQUIP_ID_SWORD);
                 me->SetReactState(REACT_AGGRESSIVE);
                 me->SetControlled(false, UNIT_STATE_ROOT);
                 me->DisableRotate(false);
                 if (me->GetVictim())
                 {
                     AttackStart(me->GetVictim());
                     me->SetTarget(me->GetVictim()->GetGUID());
                 }
             }
             else if (spell->Id == uint32(SPELL_FORGE_MACE))
             {
                 events.RescheduleEvent(EVENT_SPELL_DEEP_FREEZE, 10000);
                 SetEquipmentSlots(false, EQUIP_ID_MACE);
                 me->SetReactState(REACT_AGGRESSIVE);
                 me->SetControlled(false, UNIT_STATE_ROOT);
                 me->DisableRotate(false);
                 if (me->GetVictim())
                 {
                     AttackStart(me->GetVictim());
                     me->SetTarget(me->GetVictim()->GetGUID());
                 }
             }
         }
References ScriptedAI::AttackStart(), bCanSayBoulderHit, Unit::DisableRotate(), EQUIP_ID_MACE, EQUIP_ID_SWORD, EVENT_SPELL_CHILLING_WAVE, EVENT_SPELL_DEEP_FREEZE, Object::GetGUID(), Unit::GetVictim(), SpellInfo::Id, ScriptedAI::me, REACT_AGGRESSIVE, SAY_BOULDER_HIT, Unit::SetControlled(), ScriptedAI::SetEquipmentSlots(), Creature::SetReactState(), Creature::SetTarget(), SPELL_FORGE_BLADE, SPELL_FORGE_MACE, SPELL_SARONITE_TRIGGERED, CreatureAI::Talk(), and UNIT_STATE_ROOT.
UpdateAI()
void boss_garfrost::boss_garfrostAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 210 of file boss_forgemaster_garfrost.cpp.
         {
             if (!UpdateVictim())
                 return;
             if (me->GetVictim())
             {
                 float x, y, z;
                 me->GetVictim()->GetPosition(x, y, z);
                 if (x < 600.0f || x > 770.0f || y < -270.0f || y > -137.0f || z < 514.0f || z > 550.0f)
                 {
                     me->SetHealth(me->GetMaxHealth());
                     EnterEvadeMode();
                     if (CreatureGroup* f = me->GetFormation())
                     {
                         const CreatureGroup::CreatureGroupMemberType& m = f->GetMembers();
                         for (CreatureGroup::CreatureGroupMemberType::const_iterator itr = m.begin(); itr != m.end(); ++itr)
                             if (itr->first->IsAlive() && itr->first->IsInCombat() && !itr->first->IsInEvadeMode() && itr->first->IsAIEnabled)
                                 itr->first->AI()->EnterEvadeMode();
                     }
                     return;
                 }
             }
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch(events.ExecuteEvent())
             {
                 case 0:
                     break;
                 case EVENT_SPELL_THROW_SARONITE:
                     bCanSayBoulderHit = true;
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 140.0f, true))
                     {
                         WorldPacket data;
                         ChatHandler::BuildChatPacket(data, CHAT_MSG_RAID_BOSS_EMOTE, LANG_UNIVERSAL, me, nullptr, EMOTE_THROW_SARONITE);
                         target->ToPlayer()->GetSession()->SendPacket(&data);
                         me->CastSpell(target, SPELL_THROW_SARONITE, false);
                     }
                     events.RepeatEvent(urand(12500, 20000));
                     break;
                 case EVENT_JUMP:
                     me->DisableRotate(true);
                     if (phase == 1)
                         me->GetMotionMaster()->MoveJump(northForgePos.GetPositionX(), northForgePos.GetPositionY(), northForgePos.GetPositionZ(), 25.0f, 15.0f, 0);
                     else if (phase == 2)
                         me->GetMotionMaster()->MoveJump(southForgePos.GetPositionX(), southForgePos.GetPositionY(), southForgePos.GetPositionZ(), 25.0f, 15.0f, 0);
                     break;
                 case EVENT_SPELL_CHILLING_WAVE:
                     me->CastSpell(me->GetVictim(), SPELL_CHILLING_WAVE, false);
                     events.RepeatEvent(35000);
                     break;
                 case EVENT_SPELL_DEEP_FREEZE:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 0.0f, true))
                     {
                         Talk(EMOTE_DEEP_FREEZE, target);
                         me->CastSpell(target, SPELL_DEEP_FREEZE, false);
                     }
                     events.RepeatEvent(35000);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References bCanSayBoulderHit, ChatHandler::BuildChatPacket(), Unit::CastSpell(), CHAT_MSG_RAID_BOSS_EMOTE, Unit::DisableRotate(), UnitAI::DoMeleeAttackIfReady(), EMOTE_DEEP_FREEZE, EMOTE_THROW_SARONITE, EnterEvadeMode(), EVENT_JUMP, EVENT_SPELL_CHILLING_WAVE, EVENT_SPELL_DEEP_FREEZE, EVENT_SPELL_THROW_SARONITE, Creature::GetFormation(), Unit::GetMaxHealth(), Unit::GetMotionMaster(), Position::GetPosition(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetVictim(), Unit::HasUnitState(), LANG_UNIVERSAL, ScriptedAI::me, MotionMaster::MoveJump(), northForgePos, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Unit::SetHealth(), southForgePos, SPELL_CHILLING_WAVE, SPELL_DEEP_FREEZE, SPELL_THROW_SARONITE, CreatureAI::Talk(), UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
bCanSayBoulderHit
bool boss_garfrost::boss_garfrostAI::bCanSayBoulderHit
Definition at line 89 of file boss_forgemaster_garfrost.cpp.
Referenced by Reset(), SpellHitTarget(), and UpdateAI().
events
EventMap boss_garfrost::boss_garfrostAI::events
Definition at line 87 of file boss_forgemaster_garfrost.cpp.
phase
uint8 boss_garfrost::boss_garfrostAI::phase
Definition at line 88 of file boss_forgemaster_garfrost.cpp.
pInstance
InstanceScript* boss_garfrost::boss_garfrostAI::pInstance
Definition at line 86 of file boss_forgemaster_garfrost.cpp.
Referenced by boss_garfrostAI(), EnterCombat(), JustDied(), Reset(), and SetData().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/FrozenHalls/PitOfSaron/boss_forgemaster_garfrost.cpp