Azerotcore-wotlk: deps/fmt/include/fmt/chrono.h File Reference
chrono.h File Reference
#include <algorithm>
#include <chrono>
#include <ctime>
#include <locale>
#include <sstream>
#include "format.h"
Classes
struct detail::null< T >
struct formatter< std::chrono::time_point< std::chrono::system_clock, Duration >, Char >
struct formatter< std::tm, Char >
struct null_chrono_spec_handler< Derived >
struct chrono_format_checker
struct make_unsigned_or_unchanged< T, INTEGRAL >
struct make_unsigned_or_unchanged< T, true >
struct chrono_formatter< FormatContext, OutputIt, Rep, Period >
class weekday
struct formatter< weekday >
struct formatter< std::chrono::duration< Rep, Period >, Char >
struct formatter< std::chrono::duration< Rep, Period >, Char >::spec_handler
struct formatter< std::chrono::duration< Rep, Period >, Char >::parse_range
Namespaces
safe_duration_cast
detail
Macros
#define FMT_SAFE_DURATION_CAST 1
#define FMT_NOMACRO
Enumerations
enum class numeric_system { standard , alternative }
Functions
template<typename To , typename From , FMT_ENABLE_IF(!std::is_same< From, To >::value && std::numeric_limits< From >::is_signed== std::numeric_limits< To >::is_signed) >
FMT_CONSTEXPR To safe_duration_cast::lossless_integral_conversion (const From from, int &ec)
template<typename To , typename From , FMT_ENABLE_IF(!std::is_same< From, To >::value) >
FMT_CONSTEXPR To safe_duration_cast::safe_float_conversion (const From from, int &ec)
template<typename To , typename FromRep , typename FromPeriod , FMT_ENABLE_IF(std::is_integral< FromRep >::value) , FMT_ENABLE_IF(std::is_integral< typename To::rep >::value) >
To safe_duration_cast::safe_duration_cast (std::chrono::duration< FromRep, FromPeriod > from, int &ec)
null localtime_r detail::FMT_NOMACRO (...)
null detail::localtime_s (...)
null detail::gmtime_r (...)
null detail::gmtime_s (...)
auto detail::do_write (const std::tm &time, const std::locale &loc, char format, char modifier) -> std::string
template<typename OutputIt >
auto detail::write (OutputIt out, const std::tm &time, const std::locale &loc, char format, char modifier=0) -> OutputIt
FMT_MODULE_EXPORT_BEGIN std::tm localtime (std::time_t time)
std::tm localtime (std::chrono::time_point< std::chrono::system_clock > time_point)
std::tm gmtime (std::time_t time)
std::tm gmtime (std::chrono::time_point< std::chrono::system_clock > time_point)
FMT_BEGIN_DETAIL_NAMESPACE size_t strftime (char *str, size_t count, const char *format, const std::tm *time)
size_t strftime (wchar_t *str, size_t count, const wchar_t *format, const std::tm *time)
template<typename Period >
FMT_BEGIN_DETAIL_NAMESPACE FMT_CONSTEXPR const char * get_units ()
template<typename Char , typename Handler >
FMT_CONSTEXPR const Char * parse_chrono_format (const Char *begin, const Char *end, Handler &&handler)
template<typename T , FMT_ENABLE_IF(std::is_integral< T >::value) >
bool isnan (T)
template<typename T , FMT_ENABLE_IF(std::is_integral< T >::value) >
bool isfinite (T)
template<typename T , FMT_ENABLE_IF(std::is_integral< T >::value) >
int to_nonnegative_int (T value, int upper)
template<typename T , FMT_ENABLE_IF(std::is_integral< T >::value) >
T mod (T x, int y)
template<typename To , typename FromRep , typename FromPeriod >
To fmt_safe_duration_cast (std::chrono::duration< FromRep, FromPeriod > from)
template<typename Rep , typename Period , FMT_ENABLE_IF(std::is_integral< Rep >::value) >
std::chrono::duration< Rep, std::milli > get_milliseconds (std::chrono::duration< Rep, Period > d)
template<typename Char , typename Rep , typename OutputIt , FMT_ENABLE_IF(std::is_integral< Rep >::value) >
OutputIt format_duration_value (OutputIt out, Rep val, int)
template<typename Char , typename OutputIt >
OutputIt copy_unit (string_view unit, OutputIt out, Char)
template<typename OutputIt >
OutputIt copy_unit (string_view unit, OutputIt out, wchar_t)
template<typename Char , typename Period , typename OutputIt >
OutputIt format_duration_unit (OutputIt out)
Macro Definition Documentation
FMT_NOMACRO
#define FMT_NOMACRO
Definition at line 282 of file chrono.h.
FMT_SAFE_DURATION_CAST
#define FMT_SAFE_DURATION_CAST 1
Definition at line 23 of file chrono.h.
Enumeration Type Documentation
numeric_system
enum numeric_system strong
Enumerator
standard
alternative
Definition at line 576 of file chrono.h.
{
   standard,
   // Alternative numeric system, e.g. 十二 instead of 12 in ja_JP locale.
   alternative
 };
Function Documentation
copy_unit() [1/2]
template<typename Char , typename OutputIt > OutputIt copy_unit (string_view unit, OutputIt out, Char)
Definition at line 902 of file chrono.h.
{
   return std::copy(unit.begin(), unit.end(), out);
 }
References basic_string_view< Char >::begin(), detail::copy(), and basic_string_view< Char >::end().
Referenced by format_duration_unit().
copy_unit() [2/2]
template<typename OutputIt > OutputIt copy_unit (string_view unit, OutputIt out, wchar_t)
Definition at line 907 of file chrono.h.
{
   // This works when wchar_t is UTF-32 because units only contain characters
   // that have the same representation in UTF-16 and UTF-32.
   utf8_to_utf16 u(unit);
   return std::copy(u.c_str(), u.c_str() + u.size(), out);
 }
References utf8_to_utf16::c_str(), detail::copy(), and utf8_to_utf16::size().
fmt_safe_duration_cast()
template<typename To , typename FromRep , typename FromPeriod > To fmt_safe_duration_cast (std::chrono::duration< FromRep, FromPeriod > from)
Definition at line 844 of file chrono.h.
{
   int ec;
   To to = safe_duration_cast::safe_duration_cast<To>(from, ec);
   if (ec) FMT_THROW(format_error("cannot format duration"));
   return to;
 }
References FMT_THROW.
format_duration_unit()
template<typename Char , typename Period , typename OutputIt > OutputIt format_duration_unit (OutputIt out)
Definition at line 915 of file chrono.h.
{
   if (const char* unit = get_units<Period>())
     return copy_unit(string_view(unit), out, Char());
   *out++ = '[';
   out = write<Char>(out, Period::num);
   if (const_check(Period::den != 1)) {
     *out++ = '/';
     out = write<Char>(out, Period::den);
   }
   *out++ = ']';
   *out++ = 's';
   return out;
 }
References const_check(), and copy_unit().
format_duration_value()
template<typename Char , typename Rep , typename OutputIt , FMT_ENABLE_IF(std::is_integral< Rep >::value) > OutputIt format_duration_value (OutputIt out, Rep val, int precision)
Definition at line 888 of file chrono.h.
{
   return write<Char>(out, val);
 }
get_milliseconds()
template<typename Rep , typename Period , FMT_ENABLE_IF(std::is_integral< Rep >::value) > std::chrono::duration< Rep, std::milli > get_milliseconds (std::chrono::duration< Rep, Period > d) inline
Definition at line 854 of file chrono.h.
{
   // this may overflow and/or the result may not fit in the
   // target type.
 #if FMT_SAFE_DURATION_CAST
   using CommonSecondsType =
       typename std::common_type<decltype(d), std::chrono::seconds>::type;
   const auto d_as_common = fmt_safe_duration_cast<CommonSecondsType>(d);
   const auto d_as_whole_seconds =
       fmt_safe_duration_cast<std::chrono::seconds>(d_as_common);
   // this conversion should be nonproblematic
   const auto diff = d_as_common - d_as_whole_seconds;
   const auto ms =
       fmt_safe_duration_cast<std::chrono::duration<Rep, std::milli>>(diff);
   return ms;
 #else
   auto s = std::chrono::duration_cast<std::chrono::seconds>(d);
   return std::chrono::duration_cast<std::chrono::milliseconds>(d - s);
 #endif
 }
References mpq::d, diff(), and G3D::units::seconds().
Referenced by chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_second().
get_units()
template<typename Period > FMT_BEGIN_DETAIL_NAMESPACE FMT_CONSTEXPR const char* get_units () inline
Definition at line 553 of file chrono.h.
{
   if (std::is_same<Period, std::atto>::value) return "as";
   if (std::is_same<Period, std::femto>::value) return "fs";
   if (std::is_same<Period, std::pico>::value) return "ps";
   if (std::is_same<Period, std::nano>::value) return "ns";
   if (std::is_same<Period, std::micro>::value) return "µs";
   if (std::is_same<Period, std::milli>::value) return "ms";
   if (std::is_same<Period, std::centi>::value) return "cs";
   if (std::is_same<Period, std::deci>::value) return "ds";
   if (std::is_same<Period, std::ratio<1>>::value) return "s";
   if (std::is_same<Period, std::deca>::value) return "das";
   if (std::is_same<Period, std::hecto>::value) return "hs";
   if (std::is_same<Period, std::kilo>::value) return "ks";
   if (std::is_same<Period, std::mega>::value) return "Ms";
   if (std::is_same<Period, std::giga>::value) return "Gs";
   if (std::is_same<Period, std::tera>::value) return "Ts";
   if (std::is_same<Period, std::peta>::value) return "Ps";
   if (std::is_same<Period, std::exa>::value) return "Es";
   if (std::is_same<Period, std::ratio<60>>::value) return "m";
   if (std::is_same<Period, std::ratio<3600>>::value) return "h";
   return nullptr;
 }
gmtime() [1/2]
std::tm gmtime (std::chrono::time_point< std::chrono::system_clock > time_point) inline
Definition at line 449 of file chrono.h.
{
   return gmtime(std::chrono::system_clock::to_time_t(time_point));
 }
References gmtime().
gmtime() [2/2]
std::tm gmtime (std::time_t time) inline
Converts given time since epoch as std::time_t value into calendar time, expressed in Coordinated Universal Time (UTC). Unlike std::gmtime, this function is thread-safe on most platforms.
Definition at line 414 of file chrono.h.
{
   struct dispatcher {
     std::time_t time_;
     std::tm tm_;
     dispatcher(std::time_t t) : time_(t) {}
     bool run() {
       using namespace fmt::detail;
       return handle(gmtime_r(&time_, &tm_));
     }
     bool handle(std::tm* tm) { return tm != nullptr; }
     bool handle(detail::null<>) {
       using namespace fmt::detail;
       return fallback(gmtime_s(&tm_, &time_));
     }
     bool fallback(int res) { return res == 0; }
 #if !FMT_MSC_VER
     bool fallback(detail::null<>) {
       std::tm* tm = std::gmtime(&time_);
       if (tm) tm_ = *tm;
       return tm != nullptr;
     }
 #endif
   };
   dispatcher gt(time);
   // Too big time values may be unsupported.
   if (!gt.run()) FMT_THROW(format_error("time_t value out of range"));
   return gt.tm_;
 }
References FMT_THROW, detail::gmtime_r(), and detail::gmtime_s().
Referenced by get_date(), gmtime(), gmtime_r(), soap_dateTime2s(), and soap_timegm().
isfinite()
template<typename T , FMT_ENABLE_IF(std::is_integral< T >::value) > bool isfinite (T value) inline
Definition at line 796 of file chrono.h.
{
   return true;
 }
Referenced by Player::_SaveCharacter(), dtMathIsfinite(), chrono_formatter< FormatContext, OutputIt, Rep, Period >::handle_nan_inf(), VMAP::StaticMapTree::isInLineOfSight(), Acore::IsValidMapCoord(), ByteBuffer::operator>>(), safe_duration_cast::safe_float_conversion(), and Acore::Impl::ChatCommands::ArgInfo< T, std::enable_if_t< std::is_integral_v< T >||std::is_floating_point_v< T > > >::TryConsume().
isnan()
template<typename T , FMT_ENABLE_IF(std::is_integral< T >::value) > bool isnan (T value) inline
Definition at line 787 of file chrono.h.
                      {
   return false;
 }
Referenced by chrono_formatter< FormatContext, OutputIt, Rep, Period >::format_localized(), chrono_formatter< FormatContext, OutputIt, Rep, Period >::handle_nan_inf(), and chrono_formatter< FormatContext, OutputIt, Rep, Period >::write().
localtime() [1/2]
std::tm localtime (std::chrono::time_point< std::chrono::system_clock > time_point) inline
Definition at line 404 of file chrono.h.
{
   return localtime(std::chrono::system_clock::to_time_t(time_point));
 }
References localtime().
localtime() [2/2]
FMT_MODULE_EXPORT_BEGIN std::tm localtime (std::time_t time) inline
Converts given time since epoch as std::time_t value into calendar time, expressed in local time. Unlike std::localtime, this function is thread-safe on most platforms.
Definition at line 368 of file chrono.h.
{
   struct dispatcher {
     std::time_t time_;
     std::tm tm_;
     dispatcher(std::time_t t) : time_(t) {}
     bool run() {
       using namespace fmt::detail;
       return handle(localtime_r(&time_, &tm_));
     }
     bool handle(std::tm* tm) { return tm != nullptr; }
     bool handle(detail::null<>) {
       using namespace fmt::detail;
       return fallback(localtime_s(&tm_, &time_));
     }
     bool fallback(int res) { return res == 0; }
 #if !FMT_MSC_VER
     bool fallback(detail::null<>) {
       using namespace fmt::detail;
       std::tm* tm = std::localtime(&time_);
       if (tm) tm_ = *tm;
       return tm != nullptr;
     }
 #endif
   };
   dispatcher lt(time);
   // Too big time values may be unsupported.
   if (!lt.run()) FMT_THROW(format_error("time_t value out of range"));
   return lt.tm_;
 }
References FMT_THROW, localtime_r(), and detail::localtime_s().
Referenced by G3D::System::currentDateString(), G3D::System::currentTimeString(), DoPrefix(), formatter< std::chrono::time_point< std::chrono::system_clock, Duration >, Char >::format(), get_date(), G3D::System::initTime(), localtime(), localtime_r(), and soap_dateTime2s().
mod()
template<typename T , FMT_ENABLE_IF(std::is_integral< T >::value) > T mod (T x, int y) inline
Definition at line 822 of file chrono.h.
{
   return x % static_cast<T>(y);
 }
References G3D::x, and G3D::y.
Referenced by Player::_ApplyWeaponDependentAuraCritMod(), _lf_dynarray_lvalue(), Player::AddSpellMod(), CustomSpellValues::AddSpellMod(), Unit::ApplyDiminishingToDuration(), Player::ApplySpellMod(), spell_dru_bear_form_passive::CalculateAmount(), Unit::CalculateMeleeDamage(), Unit::CastCustomSpell(), do_div_mod(), Player::DropModCharge(), ArenaTeam::FinishGame(), ArenaTeam::GetMatchmakerRatingMod(), WardenMac::GetModuleForClient(), WardenWin::GetModuleForClient(), ArenaTeam::GetRatingMod(), Unit::HandleAuraProc(), spell_dk_raise_ally::HandleDummy(), AuraEffect::HandlePeriodicDummyAuraTick(), Player::HasSpellMod(), chrono_formatter< FormatContext, OutputIt, Rep, Period >::hour(), chrono_formatter< FormatContext, OutputIt, Rep, Period >::hour12(), Player::IsAffectedBySpellmod(), SpellInfo::IsAffectedBySpellMod(), ArenaTeam::LostAgainst(), ArenaTeam::MemberLost(), ArenaTeam::MemberWon(), chrono_formatter< FormatContext, OutputIt, Rep, Period >::minute(), ArenaTeamMember::ModifyMatchmakerRating(), ArenaTeamMember::ModifyPersonalRating(), Aura::ModStackAmount(), Position::NormalizeOrientation(), MapMgr::NormalizeOrientation(), ScriptMgr::OnBeforeUpdatingPersonalRating(), spell_broggok_poison_cloud::spell_broggok_poison_cloud_AuraScript::PeriodicTick(), Unit::processDummyAuras(), Player::RemoveSpellMods(), Player::RestoreSpellMods(), chrono_formatter< FormatContext, OutputIt, Rep, Period >::second(), Channel::SetMode(), Spell::SetSpellValue(), sz_index2size_compute(), sz_pind2sz_compute(), sz_psz2ind(), sz_size2index_compute(), and ArenaTeam::WonAgainst().
parse_chrono_format()
template<typename Char , typename Handler > FMT_CONSTEXPR const Char* parse_chrono_format (const Char * begin, const Char * end, Handler && handler)
Definition at line 584 of file chrono.h.
{
   auto ptr = begin;
   while (ptr != end) {
     auto c = *ptr;
     if (c == '}') break;
     if (c != '%') {
       ++ptr;
       continue;
     }
     if (begin != ptr) handler.on_text(begin, ptr);
     ++ptr;  // consume '%'
     if (ptr == end) FMT_THROW(format_error("invalid format"));
     c = *ptr++;
     switch (c) {
     case '%':
       handler.on_text(ptr - 1, ptr);
       break;
     case 'n': {
       const Char newline[] = {'\n'};
       handler.on_text(newline, newline + 1);
       break;
     }
     case 't': {
       const Char tab[] = {'\t'};
       handler.on_text(tab, tab + 1);
       break;
     }
     // Day of the week:
     case 'a':
       handler.on_abbr_weekday();
       break;
     case 'A':
       handler.on_full_weekday();
       break;
     case 'w':
       handler.on_dec0_weekday(numeric_system::standard);
       break;
     case 'u':
       handler.on_dec1_weekday(numeric_system::standard);
       break;
     // Month:
     case 'b':
       handler.on_abbr_month();
       break;
     case 'B':
       handler.on_full_month();
       break;
     // Hour, minute, second:
     case 'H':
       handler.on_24_hour(numeric_system::standard);
       break;
     case 'I':
       handler.on_12_hour(numeric_system::standard);
       break;
     case 'M':
       handler.on_minute(numeric_system::standard);
       break;
     case 'S':
       handler.on_second(numeric_system::standard);
       break;
     // Other:
     case 'c':
       handler.on_datetime(numeric_system::standard);
       break;
     case 'x':
       handler.on_loc_date(numeric_system::standard);
       break;
     case 'X':
       handler.on_loc_time(numeric_system::standard);
       break;
     case 'D':
       handler.on_us_date();
       break;
     case 'F':
       handler.on_iso_date();
       break;
     case 'r':
       handler.on_12_hour_time();
       break;
     case 'R':
       handler.on_24_hour_time();
       break;
     case 'T':
       handler.on_iso_time();
       break;
     case 'p':
       handler.on_am_pm();
       break;
     case 'Q':
       handler.on_duration_value();
       break;
     case 'q':
       handler.on_duration_unit();
       break;
     case 'z':
       handler.on_utc_offset();
       break;
     case 'Z':
       handler.on_tz_name();
       break;
     // Alternative representation:
     case 'E': {
       if (ptr == end) FMT_THROW(format_error("invalid format"));
       c = *ptr++;
       switch (c) {
       case 'c':
         handler.on_datetime(numeric_system::alternative);
         break;
       case 'x':
         handler.on_loc_date(numeric_system::alternative);
         break;
       case 'X':
         handler.on_loc_time(numeric_system::alternative);
         break;
       default:
         FMT_THROW(format_error("invalid format"));
       }
       break;
     }
     case 'O':
       if (ptr == end) FMT_THROW(format_error("invalid format"));
       c = *ptr++;
       switch (c) {
       case 'w':
         handler.on_dec0_weekday(numeric_system::alternative);
         break;
       case 'u':
         handler.on_dec1_weekday(numeric_system::alternative);
         break;
       case 'H':
         handler.on_24_hour(numeric_system::alternative);
         break;
       case 'I':
         handler.on_12_hour(numeric_system::alternative);
         break;
       case 'M':
         handler.on_minute(numeric_system::alternative);
         break;
       case 'S':
         handler.on_second(numeric_system::alternative);
         break;
       default:
         FMT_THROW(format_error("invalid format"));
       }
       break;
     default:
       FMT_THROW(format_error("invalid format"));
     }
     begin = ptr;
   }
   if (begin != ptr) handler.on_text(begin, ptr);
   return ptr;
 }
References alternative, mpq::c, FMT_THROW, ptr(), and standard.
Referenced by formatter< std::chrono::duration< Rep, Period >, Char >::do_parse(), and formatter< std::chrono::duration< Rep, Period >, Char >::format().
strftime() [1/2]
FMT_BEGIN_DETAIL_NAMESPACE size_t strftime (char * str, size_t count, const char * format, const std::tm * time) inline
Definition at line 456 of file chrono.h.
{
   // Assign to a pointer to suppress GCCs -Wformat-nonliteral
   // First assign the nullptr to suppress -Wsuggest-attribute=format
   std::size_t (*strftime)(char*, std::size_t, const char*, const std::tm*) =
       nullptr;
   strftime = std::strftime;
   return strftime(str, count, format, time);
 }
References count(), and format().
Referenced by formatter< std::tm, Char >::format(), guild_commandscript::HandleGuildInfoCommand(), misc_commandscript::HandleMuteInfoHelper(), soap_dateTime2s(), and TimeToHumanReadable().
strftime() [2/2]
size_t strftime (wchar_t * str, size_t count, const wchar_t * format, const std::tm * time) inline
Definition at line 466 of file chrono.h.
{
   // See above
   std::size_t (*wcsftime)(wchar_t*, std::size_t, const wchar_t*,
                           const std::tm*) = nullptr;
   wcsftime = std::wcsftime;
   return wcsftime(str, count, format, time);
 }
References count(), and format().
to_nonnegative_int()
template<typename T , FMT_ENABLE_IF(std::is_integral< T >::value) > int to_nonnegative_int (T value, int upper) inline
Definition at line 806 of file chrono.h.
{
   FMT_ASSERT(value >= 0 && to_unsigned(value) <= to_unsigned(upper),
              "invalid value");
   (void)upper;
   return static_cast<int>(value);
 }
References FMT_ASSERT, and to_unsigned().
Referenced by chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_12_hour(), chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_24_hour(), chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_minute(), chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_second(), chrono_formatter< FormatContext, OutputIt, Rep, Period >::time(), and chrono_formatter< FormatContext, OutputIt, Rep, Period >::write().