Azerotcore-wotlk: dtNodeQueue Class Reference
dtNodeQueue Class Reference
#include <DetourNode.h>
Public Member Functions
dtNodeQueue (int n)
~dtNodeQueue ()
void clear ()
dtNode * top ()
dtNode * pop ()
void push (dtNode *node)
void modify (dtNode *node)
bool empty () const
int getMemUsed () const
int getCapacity () const
Private Member Functions
dtNodeQueue (const dtNodeQueue &)
dtNodeQueue & operator= (const dtNodeQueue &)
void bubbleUp (int i, dtNode *node)
void trickleDown (int i, dtNode *node)
Private Attributes
dtNode ** m_heap
const int m_capacity
int m_size
Detailed Description
Definition at line 108 of file DetourNode.h.
Constructor & Destructor Documentation
dtNodeQueue() [1/2]
dtNodeQueue::dtNodeQueue (int n)
Definition at line 156 of file DetourNode.cpp.
                               :
     m_heap(0),
     m_capacity(n),
     m_size(0)
 {
     dtAssert(m_capacity > 0);
     m_heap = (dtNode**)dtAlloc(sizeof(dtNode*)*(m_capacity+1), DT_ALLOC_PERM);
     dtAssert(m_heap);
 }
References DT_ALLOC_PERM, dtAlloc(), dtAssert, m_capacity, and m_heap.
~dtNodeQueue()
dtNodeQueue::~dtNodeQueue ()
Definition at line 167 of file DetourNode.cpp.
 {
     dtFree(m_heap);
 }
References dtFree(), and m_heap.
Referenced by dtNavMeshQuery::init(), and dtNavMeshQuery::~dtNavMeshQuery().
dtNodeQueue() [2/2]
dtNodeQueue::dtNodeQueue (const dtNodeQueue &) private
Member Function Documentation
bubbleUp()
void dtNodeQueue::bubbleUp (int i, dtNode * node) private
Definition at line 172 of file DetourNode.cpp.
 {
     int parent = (i-1)/2;
     // note: (index > 0) means there is a parent
     while ((i > 0) && (m_heap[parent]->total > node->total))
     {
         m_heap[i] = m_heap[parent];
         i = parent;
         parent = (i-1)/2;
     }
     m_heap[i] = node;
 }
References m_heap, and dtNode::total.
Referenced by modify(), push(), and trickleDown().
clear()
void dtNodeQueue::clear () inline
Definition at line 114 of file DetourNode.h.
 { m_size = 0; }
References m_size.
Referenced by dtNavMeshQuery::findDistanceToWall(), dtNavMeshQuery::findPath(), dtNavMeshQuery::findPolysAroundCircle(), dtNavMeshQuery::findPolysAroundShape(), dtNavMeshQuery::findRandomPointAroundCircle(), dtNavMeshQuery::init(), and dtNavMeshQuery::initSlicedFindPath().
empty()
bool dtNodeQueue::empty () const inline
Definition at line 144 of file DetourNode.h.
 { return m_size == 0; }
References m_size.
Referenced by dtNavMeshQuery::findDistanceToWall(), dtNavMeshQuery::findPath(), dtNavMeshQuery::findPolysAroundCircle(), dtNavMeshQuery::findPolysAroundShape(), dtNavMeshQuery::findRandomPointAroundCircle(), and dtNavMeshQuery::updateSlicedFindPath().
getCapacity()
int dtNodeQueue::getCapacity () const inline
Definition at line 152 of file DetourNode.h.
 { return m_capacity; }
References m_capacity.
Referenced by dtNavMeshQuery::init().
getMemUsed()
int dtNodeQueue::getMemUsed () const inline
Definition at line 146 of file DetourNode.h.
     {
         return sizeof(*this) +
         sizeof(dtNode*) * (m_capacity + 1);
     }
References m_capacity.
modify()
void dtNodeQueue::modify (dtNode * node) inline
Definition at line 132 of file DetourNode.h.
     {
         for (int i = 0; i < m_size; ++i)
         {
             if (m_heap[i] == node)
             {
                 bubbleUp(i, node);
                 return;
             }
         }
     }
References bubbleUp(), m_heap, and m_size.
Referenced by dtNavMeshQuery::findDistanceToWall(), dtNavMeshQuery::findPath(), dtNavMeshQuery::findPolysAroundCircle(), dtNavMeshQuery::findPolysAroundShape(), dtNavMeshQuery::findRandomPointAroundCircle(), and dtNavMeshQuery::updateSlicedFindPath().
operator=()
dtNodeQueue& dtNodeQueue::operator= (const dtNodeQueue &) private
pop()
dtNode* dtNodeQueue::pop () inline
Definition at line 118 of file DetourNode.h.
     {
         dtNode* result = m_heap[0];
         m_size--;
         trickleDown(0, m_heap[m_size]);
         return result;
     }
References m_heap, m_size, and trickleDown().
Referenced by dtNavMeshQuery::findDistanceToWall(), dtNavMeshQuery::findPath(), dtNavMeshQuery::findPolysAroundCircle(), dtNavMeshQuery::findPolysAroundShape(), dtNavMeshQuery::findRandomPointAroundCircle(), and dtNavMeshQuery::updateSlicedFindPath().
push()
void dtNodeQueue::push (dtNode * node) inline
Definition at line 126 of file DetourNode.h.
     {
         m_size++;
         bubbleUp(m_size-1, node);
     }
References bubbleUp(), and m_size.
Referenced by dtNavMeshQuery::findDistanceToWall(), dtNavMeshQuery::findPath(), dtNavMeshQuery::findPolysAroundCircle(), dtNavMeshQuery::findPolysAroundShape(), dtNavMeshQuery::findRandomPointAroundCircle(), dtNavMeshQuery::initSlicedFindPath(), and dtNavMeshQuery::updateSlicedFindPath().
top()
dtNode* dtNodeQueue::top () inline
Definition at line 116 of file DetourNode.h.
 { return m_heap[0]; }
References m_heap.
trickleDown()
void dtNodeQueue::trickleDown (int i, dtNode * node) private
Definition at line 185 of file DetourNode.cpp.
 {
     int child = (i*2)+1;
     while (child < m_size)
     {
         if (((child+1) < m_size) &&
             (m_heap[child]->total > m_heap[child+1]->total))
         {
             child++;
         }
         m_heap[i] = m_heap[child];
         i = child;
         child = (i*2)+1;
     }
     bubbleUp(i, node);
 }
References bubbleUp(), m_heap, m_size, and dtNode::total.
Referenced by pop().
Member Data Documentation
m_capacity
const int dtNodeQueue::m_capacity private
Definition at line 163 of file DetourNode.h.
Referenced by dtNodeQueue(), getCapacity(), and getMemUsed().
m_heap
dtNode** dtNodeQueue::m_heap private
Definition at line 162 of file DetourNode.h.
Referenced by bubbleUp(), dtNodeQueue(), modify(), pop(), top(), trickleDown(), and ~dtNodeQueue().
m_size
int dtNodeQueue::m_size private
Definition at line 164 of file DetourNode.h.
Referenced by clear(), empty(), modify(), pop(), push(), and trickleDown().
The documentation for this class was generated from the following files:
deps/recastnavigation/Detour/Include/DetourNode.h
deps/recastnavigation/Detour/Source/DetourNode.cpp