Azerotcore-wotlk: npc_ravenous_furbolg::npc_ravenous_furbolgAI Struct Reference
npc_ravenous_furbolg::npc_ravenous_furbolgAI Struct Reference
Public Member Functions
npc_ravenous_furbolgAI (Creature *pCreature)
void Reset () override
void EnterCombat (Unit *) override
void DoAction (int32 param) override
void MoveInLineOfSight (Unit *who) override
void JustReachedHome () override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * m_pInstance
EventMap events
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 590 of file boss_palehoof.cpp.
Constructor & Destructor Documentation
npc_ravenous_furbolgAI()
npc_ravenous_furbolg::npc_ravenous_furbolgAI::npc_ravenous_furbolgAI (Creature * pCreature) inline
Definition at line 592 of file boss_palehoof.cpp.
                                                     : ScriptedAI(pCreature)
         {
             m_pInstance = pCreature->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), and m_pInstance.
Member Function Documentation
DoAction()
void npc_ravenous_furbolg::npc_ravenous_furbolgAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 608 of file boss_palehoof.cpp.
         {
             if (param == ACTION_UNFREEZE)
             {
                 me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
             }
             else if (param == ACTION_UNFREEZE2)
             {
                 me->RemoveAurasDueToSpell(SPELL_FREEZE);
                 me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                 me->SetInCombatWithZone();
                 events.ScheduleEvent(EVENT_FURBOLG_CHAIN, 3000);
                 events.ScheduleEvent(EVENT_FURBOLG_CRAZED, 12000);
                 events.ScheduleEvent(EVENT_FURBOLG_ROAR, 10000);
             }
         }
References ACTION_UNFREEZE, ACTION_UNFREEZE2, EVENT_FURBOLG_CHAIN, EVENT_FURBOLG_CRAZED, EVENT_FURBOLG_ROAR, ScriptedAI::me, Unit::RemoveAurasDueToSpell(), Object::RemoveFlag(), Creature::SetInCombatWithZone(), SPELL_FREEZE, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
EnterCombat()
void npc_ravenous_furbolg::npc_ravenous_furbolgAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 606 of file boss_palehoof.cpp.
 {}
JustDied()
void npc_ravenous_furbolg::npc_ravenous_furbolgAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 673 of file boss_palehoof.cpp.
         {
             if (m_pInstance)
             {
                 if (Creature* palehoof = ObjectAccessor::GetCreature(*me, m_pInstance->GetGuidData(DATA_GORTOK_PALEHOOF)))
                     palehoof->AI()->DoAction(ACTION_MINIBOSS_DIED);
             }
         }
References ACTION_MINIBOSS_DIED, DATA_GORTOK_PALEHOOF, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), m_pInstance, and ScriptedAI::me.
JustReachedHome()
void npc_ravenous_furbolg::npc_ravenous_furbolgAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 634 of file boss_palehoof.cpp.
         {
             me->SetStandState(UNIT_STAND_STATE_STAND);
         }
References ScriptedAI::me, Unit::SetStandState(), and UNIT_STAND_STATE_STAND.
MoveInLineOfSight()
void npc_ravenous_furbolg::npc_ravenous_furbolgAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
Definition at line 626 of file boss_palehoof.cpp.
         {
             if (me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE))
                 return;
             ScriptedAI::MoveInLineOfSight(who);
         }
References Object::HasFlag(), ScriptedAI::me, CreatureAI::MoveInLineOfSight(), UNIT_FIELD_FLAGS, and UNIT_FLAG_NOT_SELECTABLE.
Reset()
void npc_ravenous_furbolg::npc_ravenous_furbolgAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 600 of file boss_palehoof.cpp.
         {
             events.Reset();
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE);
         }
References ScriptedAI::me, Object::SetFlag(), UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
UpdateAI()
void npc_ravenous_furbolg::npc_ravenous_furbolgAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 639 of file boss_palehoof.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_FURBOLG_CHAIN:
                     {
                         me->CastSpell(me->GetVictim(), IsHeroic() ? SPELL_CHAIN_LIGHTING_H : SPELL_CHAIN_LIGHTING_N, false);
                         events.RepeatEvent(4000 + rand() % 3000);
                         break;
                     }
                 case EVENT_FURBOLG_CRAZED:
                     {
                         me->CastSpell(me, SPELL_CRAZED, false);
                         events.RepeatEvent(8000 + rand() % 4000);
                         break;
                     }
                 case EVENT_FURBOLG_ROAR:
                     {
                         me->CastSpell(me, SPELL_TERRIFYING_ROAR, false);
                         events.RepeatEvent(10000 + rand() % 5000);
                         break;
                     }
             }
             DoMeleeAttackIfReady();
         }
References Unit::CastSpell(), diff(), UnitAI::DoMeleeAttackIfReady(), EVENT_FURBOLG_CHAIN, EVENT_FURBOLG_CRAZED, EVENT_FURBOLG_ROAR, Unit::GetVictim(), Unit::HasUnitState(), ScriptedAI::IsHeroic(), ScriptedAI::me, SPELL_CHAIN_LIGHTING_H, SPELL_CHAIN_LIGHTING_N, SPELL_CRAZED, SPELL_TERRIFYING_ROAR, UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
events
EventMap npc_ravenous_furbolg::npc_ravenous_furbolgAI::events
Definition at line 598 of file boss_palehoof.cpp.
m_pInstance
InstanceScript* npc_ravenous_furbolg::npc_ravenous_furbolgAI::m_pInstance
Definition at line 597 of file boss_palehoof.cpp.
Referenced by JustDied(), and npc_ravenous_furbolgAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_palehoof.cpp