Azerotcore-wotlk: chrono_formatter< FormatContext, OutputIt, Rep, Period > Struct Template Reference
chrono_formatter< FormatContext, OutputIt, Rep, Period > Struct Template Reference
#include <chrono.h>
Public Types
using rep = conditional_t< std::is_integral< Rep >::value &&sizeof(Rep)< sizeof(int), unsigned, typename make_unsigned_or_unchanged< Rep >::type >
using seconds = std::chrono::duration< rep >
using milliseconds = std::chrono::duration< rep, std::milli >
using char_type = typename FormatContext::char_type
Public Member Functions
chrono_formatter (FormatContext &ctx, OutputIt o, std::chrono::duration< Rep, Period > d)
bool handle_nan_inf ()
Rep hour () const
Rep hour12 () const
Rep minute () const
Rep second () const
std::tm time () const
void write_sign ()
void write (Rep value, int width)
void write_nan ()
void write_pinf ()
void write_ninf ()
void format_localized (const tm &time, char format, char modifier=0)
void on_text (const char_type *begin, const char_type *end)
void on_abbr_weekday ()
void on_full_weekday ()
void on_dec0_weekday (numeric_system)
void on_dec1_weekday (numeric_system)
void on_abbr_month ()
void on_full_month ()
void on_datetime (numeric_system)
void on_loc_date (numeric_system)
void on_loc_time (numeric_system)
void on_us_date ()
void on_iso_date ()
void on_utc_offset ()
void on_tz_name ()
void on_24_hour (numeric_system ns)
void on_12_hour (numeric_system ns)
void on_minute (numeric_system ns)
void on_second (numeric_system ns)
void on_12_hour_time ()
void on_24_hour_time ()
void on_iso_time ()
void on_am_pm ()
void on_duration_value ()
void on_duration_unit ()
Public Attributes
FormatContext & context
OutputIt out
int precision
bool localized = false
rep val
seconds s
bool negative
Detailed Description
template<typename FormatContext, typename OutputIt, typename Rep, typename Period>
struct chrono_formatter< FormatContext, OutputIt, Rep, Period >
Definition at line 931 of file chrono.h.
Member Typedef Documentation
char_type
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > using chrono_formatter< FormatContext, OutputIt, Rep, Period >::char_type = typename FormatContext::char_type
Definition at line 946 of file chrono.h.
milliseconds
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > using chrono_formatter< FormatContext, OutputIt, Rep, Period >::milliseconds = std::chrono::duration<rep, std::milli>
Definition at line 943 of file chrono.h.
rep
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > using chrono_formatter< FormatContext, OutputIt, Rep, Period >::rep = conditional_t<std::is_integral<Rep>::value && sizeof(Rep) < sizeof(int), unsigned, typename make_unsigned_or_unchanged<Rep>::type>
Definition at line 937 of file chrono.h.
seconds
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > using chrono_formatter< FormatContext, OutputIt, Rep, Period >::seconds = std::chrono::duration<rep>
Definition at line 941 of file chrono.h.
Constructor & Destructor Documentation
chrono_formatter()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > chrono_formatter< FormatContext, OutputIt, Rep, Period >::chrono_formatter (FormatContext & ctx, OutputIt o, std::chrono::duration< Rep, Period > d) inline explicit
Definition at line 948 of file chrono.h.
       : context(ctx),
         out(o),
         val(static_cast<rep>(d.count())),
         negative(false) {
     if (d.count() < 0) {
       val = 0 - val;
       negative = true;
     }
     // this may overflow and/or the result may not fit in the
     // target type.
 #if FMT_SAFE_DURATION_CAST
     // might need checked conversion (rep!=Rep)
     auto tmpval = std::chrono::duration<rep, Period>(val);
     s = fmt_safe_duration_cast<seconds>(tmpval);
 #else
     s = std::chrono::duration_cast<seconds>(
         std::chrono::duration<rep, Period>(val));
 #endif
   }
References mpq::d.
Member Function Documentation
format_localized()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::format_localized (const tm & time, char format, char modifier = 0) inline
Definition at line 1028 of file chrono.h.
{
     if (isnan(val)) return write_nan();
     const auto& loc = localized ? context.locale().template get<std::locale>()
                                 : std::locale::classic();
     out = detail::write(out, time, loc, format, modifier);
   }
References format(), isnan(), and detail::write().
handle_nan_inf()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > bool chrono_formatter< FormatContext, OutputIt, Rep, Period >::handle_nan_inf () inline
Definition at line 972 of file chrono.h.
{
     if (isfinite(val)) {
       return false;
     }
     if (isnan(val)) {
       write_nan();
       return true;
     }
     // must be +-inf
     if (val > 0) {
       write_pinf();
     } else {
       write_ninf();
     }
     return true;
   }
References isfinite(), and isnan().
hour()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > Rep chrono_formatter< FormatContext, OutputIt, Rep, Period >::hour () const inline
Definition at line 989 of file chrono.h.
 { return static_cast<Rep>(mod((s.count() / 3600), 24)); }
References mod().
hour12()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > Rep chrono_formatter< FormatContext, OutputIt, Rep, Period >::hour12 () const inline
Definition at line 991 of file chrono.h.
                      {
     Rep hour = static_cast<Rep>(mod((s.count() / 3600), 12));
     return hour <= 0 ? 12 : hour;
   }
References mod().
minute()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > Rep chrono_formatter< FormatContext, OutputIt, Rep, Period >::minute () const inline
Definition at line 996 of file chrono.h.
 { return static_cast<Rep>(mod((s.count() / 60), 60)); }
References mod().
on_12_hour()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_12_hour (numeric_system ns) inline
Definition at line 1063 of file chrono.h.
{
     if (handle_nan_inf()) return;
     if (ns == numeric_system::standard) return write(hour12(), 2);
     auto time = tm();
     time.tm_hour = to_nonnegative_int(hour12(), 12);
     format_localized(time, 'I', 'O');
   }
References standard, to_nonnegative_int(), and detail::write().
on_12_hour_time()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_12_hour_time () inline
Definition at line 1106 of file chrono.h.
{
     if (handle_nan_inf()) return;
     format_localized(time(), 'r');
   }
on_24_hour()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_24_hour (numeric_system ns) inline
Definition at line 1054 of file chrono.h.
{
     if (handle_nan_inf()) return;
     if (ns == numeric_system::standard) return write(hour(), 2);
     auto time = tm();
     time.tm_hour = to_nonnegative_int(hour(), 24);
     format_localized(time, 'H', 'O');
   }
References standard, to_nonnegative_int(), and detail::write().
on_24_hour_time()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_24_hour_time () inline
Definition at line 1111 of file chrono.h.
{
     if (handle_nan_inf()) {
       *out++ = ':';
       handle_nan_inf();
       return;
     }
     write(hour(), 2);
     *out++ = ':';
     write(minute(), 2);
   }
References detail::write().
on_abbr_month()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_abbr_month () inline
Definition at line 1044 of file chrono.h.
 {}
on_abbr_weekday()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_abbr_weekday () inline
Definition at line 1040 of file chrono.h.
 {}
on_am_pm()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_am_pm () inline
Definition at line 1130 of file chrono.h.
                   {
     if (handle_nan_inf()) return;
     format_localized(time(), 'p');
   }
on_datetime()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_datetime (numeric_system) inline
Definition at line 1046 of file chrono.h.
 {}
on_dec0_weekday()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_dec0_weekday (numeric_system) inline
Definition at line 1042 of file chrono.h.
 {}
on_dec1_weekday()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_dec1_weekday (numeric_system) inline
Definition at line 1043 of file chrono.h.
 {}
on_duration_unit()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_duration_unit () inline
Definition at line 1141 of file chrono.h.
{
     out = format_duration_unit<char_type, Period>(out);
   }
on_duration_value()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_duration_value () inline
Definition at line 1135 of file chrono.h.
{
     if (handle_nan_inf()) return;
     write_sign();
     out = format_duration_value<char_type>(out, val, precision);
   }
on_full_month()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_full_month () inline
Definition at line 1045 of file chrono.h.
 {}
on_full_weekday()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_full_weekday () inline
Definition at line 1041 of file chrono.h.
 {}
on_iso_date()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_iso_date () inline
Definition at line 1050 of file chrono.h.
 {}
on_iso_time()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_iso_time () inline
Definition at line 1123 of file chrono.h.
                      {
     on_24_hour_time();
     *out++ = ':';
     if (handle_nan_inf()) return;
     write(second(), 2);
   }
References detail::write().
on_loc_date()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_loc_date (numeric_system) inline
Definition at line 1047 of file chrono.h.
 {}
on_loc_time()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_loc_time (numeric_system) inline
Definition at line 1048 of file chrono.h.
 {}
on_minute()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_minute (numeric_system ns) inline
Definition at line 1072 of file chrono.h.
{
     if (handle_nan_inf()) return;
     if (ns == numeric_system::standard) return write(minute(), 2);
     auto time = tm();
     time.tm_min = to_nonnegative_int(minute(), 60);
     format_localized(time, 'M', 'O');
   }
References standard, to_nonnegative_int(), and detail::write().
on_second()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_second (numeric_system ns) inline
Definition at line 1081 of file chrono.h.
{
     if (handle_nan_inf()) return;
     if (ns == numeric_system::standard) {
       write(second(), 2);
 #if FMT_SAFE_DURATION_CAST
       // convert rep->Rep
       using duration_rep = std::chrono::duration<rep, Period>;
       using duration_Rep = std::chrono::duration<Rep, Period>;
       auto tmpval = fmt_safe_duration_cast<duration_Rep>(duration_rep{val});
 #else
       auto tmpval = std::chrono::duration<Rep, Period>(val);
 #endif
       auto ms = get_milliseconds(tmpval);
       if (ms != std::chrono::milliseconds(0)) {
         *out++ = '.';
         write(ms.count(), 3);
       }
       return;
     }
     auto time = tm();
     time.tm_sec = to_nonnegative_int(second(), 60);
     format_localized(time, 'S', 'O');
   }
References get_milliseconds(), G3D::units::milliseconds(), standard, to_nonnegative_int(), and detail::write().
on_text()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_text (const char_type * begin, const char_type * end) inline
Definition at line 1035 of file chrono.h.
{
     std::copy(begin, end, out);
   }
References detail::copy().
on_tz_name()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_tz_name () inline
Definition at line 1052 of file chrono.h.
 {}
on_us_date()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_us_date () inline
Definition at line 1049 of file chrono.h.
 {}
on_utc_offset()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::on_utc_offset () inline
Definition at line 1051 of file chrono.h.
 {}
second()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > Rep chrono_formatter< FormatContext, OutputIt, Rep, Period >::second () const inline
Definition at line 997 of file chrono.h.
 { return static_cast<Rep>(mod(s.count(), 60)); }
References mod().
time()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > std::tm chrono_formatter< FormatContext, OutputIt, Rep, Period >::time () const inline
Definition at line 999 of file chrono.h.
                      {
     auto time = std::tm();
     time.tm_hour = to_nonnegative_int(hour(), 24);
     time.tm_min = to_nonnegative_int(minute(), 60);
     time.tm_sec = to_nonnegative_int(second(), 60);
     return time;
   }
References to_nonnegative_int().
write()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::write (Rep value, int width) inline
Definition at line 1014 of file chrono.h.
{
     write_sign();
     if (isnan(value)) return write_nan();
     uint32_or_64_or_128_t<int> n =
         to_unsigned(to_nonnegative_int(value, max_value<int>()));
     int num_digits = detail::count_digits(n);
     if (width > num_digits) out = std::fill_n(out, width - num_digits, '0');
     out = format_decimal<char_type>(out, n, num_digits).end;
   }
References count_digits(), detail::fill_n(), isnan(), to_nonnegative_int(), to_unsigned(), and width.
write_nan()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::write_nan () inline
Definition at line 1024 of file chrono.h.
 { std::copy_n("nan", 3, out); }
write_ninf()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::write_ninf () inline
Definition at line 1026 of file chrono.h.
 { std::copy_n("-inf", 4, out); }
write_pinf()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::write_pinf () inline
Definition at line 1025 of file chrono.h.
 { std::copy_n("inf", 3, out); }
write_sign()
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > void chrono_formatter< FormatContext, OutputIt, Rep, Period >::write_sign () inline
Definition at line 1007 of file chrono.h.
                     {
     if (negative) {
       *out++ = '-';
       negative = false;
     }
   }
Member Data Documentation
context
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > FormatContext& chrono_formatter< FormatContext, OutputIt, Rep, Period >::context
Definition at line 932 of file chrono.h.
localized
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > bool chrono_formatter< FormatContext, OutputIt, Rep, Period >::localized = false
Definition at line 935 of file chrono.h.
negative
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > bool chrono_formatter< FormatContext, OutputIt, Rep, Period >::negative
Definition at line 944 of file chrono.h.
out
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > OutputIt chrono_formatter< FormatContext, OutputIt, Rep, Period >::out
Definition at line 933 of file chrono.h.
precision
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > int chrono_formatter< FormatContext, OutputIt, Rep, Period >::precision
Definition at line 934 of file chrono.h.
s
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > seconds chrono_formatter< FormatContext, OutputIt, Rep, Period >::s
Definition at line 942 of file chrono.h.
val
template<typename FormatContext , typename OutputIt , typename Rep , typename Period > rep chrono_formatter< FormatContext, OutputIt, Rep, Period >::val
Definition at line 940 of file chrono.h.
The documentation for this struct was generated from the following file:
deps/fmt/include/fmt/chrono.h