Azerotcore-wotlk: lapseTeleport Class Reference
lapseTeleport Class Reference
Public Member Functions
lapseTeleport (Player *owner)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()
virtual ~BasicEvent ()
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Player * _owner
Detailed Description
Definition at line 923 of file boss_kaelthas.cpp.
Constructor & Destructor Documentation
lapseTeleport()
lapseTeleport::lapseTeleport (Player * owner) inline
Definition at line 926 of file boss_kaelthas.cpp.
                                  : _owner(owner)
     {
     }
Referenced by Execute().
Member Function Documentation
Execute()
bool lapseTeleport::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
Definition at line 930 of file boss_kaelthas.cpp.
     {
         if (_owner->IsBeingTeleportedNear())
             _owner->m_Events.AddEvent(new lapseTeleport(_owner), _owner->m_Events.CalculateTime(1));
         else if (!_owner->IsBeingTeleported())
         {
             _owner->CastSpell(_owner, SPELL_GRAVITY_LAPSE_KNOCKBACK, true);
             _owner->CastSpell(_owner, SPELL_GRAVITY_LAPSE_AURA, true);
         }
         return true;
     }
References _owner, EventProcessor::AddEvent(), EventProcessor::CalculateTime(), Unit::CastSpell(), Player::IsBeingTeleported(), Player::IsBeingTeleportedNear(), lapseTeleport(), Unit::m_Events, SPELL_GRAVITY_LAPSE_AURA, and SPELL_GRAVITY_LAPSE_KNOCKBACK.
Member Data Documentation
_owner
Player* lapseTeleport::_owner private
Definition at line 943 of file boss_kaelthas.cpp.
Referenced by Execute().
The documentation for this class was generated from the following file:
src/server/scripts/Outland/TempestKeep/Eye/boss_kaelthas.cpp