Azerotcore-wotlk: npc_medivh_bm::npc_medivh_bmAI Struct Reference
npc_medivh_bm::npc_medivh_bmAI Struct Reference
Public Member Functions
npc_medivh_bmAI (Creature *creature)
void Reset () override
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void MoveInLineOfSight (Unit *who) override
void AttackStart (Unit *) override
void DoAction (int32 param) override
void JustDied (Unit *) override
void UpdateAI (uint32 diff) override
void SummonOrcs (float x, float y, uint32 duration, uint32 homeTime, bool first)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * instance
EventMap events
Movement::PointsArray groundArray
Movement::PointsArray airArray
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 99 of file the_black_morass.cpp.
Constructor & Destructor Documentation
npc_medivh_bmAI()
npc_medivh_bm::npc_medivh_bmAI::npc_medivh_bmAI (Creature * creature) inline
Definition at line 101 of file the_black_morass.cpp.
                                             : ScriptedAI(creature)
         {
             instance = creature->GetInstanceScript();
             groundArray.clear();
             airArray.clear();
             groundArray.push_back(G3D::Vector3(creature->GetPositionX() + 8.0f, creature->GetPositionY(), creature->GetPositionZ()));
             airArray.push_back(G3D::Vector3(creature->GetPositionX(), creature->GetPositionY(), creature->GetPositionZ()));
             for (uint8 i = 0; i < 10; ++i)
                 groundArray.push_back(G3D::Vector3(creature->GetPositionX() + 8.0f * cos(2.0f * M_PI * i / 10.0f), creature->GetPositionY() + 8.0f * sin(2.0f * M_PI * i / 10.0f), creature->GetPositionZ()));
             for (uint8 i = 0; i < 40; ++i)
                 airArray.push_back(G3D::Vector3(creature->GetPositionX() + i * 0.25f * cos(2.0f * M_PI * i / 10.0f), creature->GetPositionY() + i * 0.25f * sin(2.0f * M_PI * i / 10.0f), creature->GetPositionZ() + i / 4.0f));
             for (uint8 i = 40; i < 80; ++i)
                 airArray.push_back(G3D::Vector3(creature->GetPositionX() + 10.0f * cos(2.0f * M_PI * i / 10.0f), creature->GetPositionY() + 10.0f * sin(2.0f * M_PI * i / 10.0f), creature->GetPositionZ() + i / 4.0f));
         }
References airArray, WorldObject::GetInstanceScript(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), groundArray, and instance.
Member Function Documentation
AttackStart()
void npc_medivh_bm::npc_medivh_bmAI::AttackStart (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 183 of file the_black_morass.cpp.
 { }
DoAction()
void npc_medivh_bm::npc_medivh_bmAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 185 of file the_black_morass.cpp.
         {
             if (param == ACTION_OUTRO)
             {
                 events.Reset();
                 events.ScheduleEvent(EVENT_OUTRO_1, 4000);
                 me->InterruptNonMeleeSpells(true);
                 me->SummonGameObject(GO_DARK_PORTAL, -2086.0f, 7125.6215f, 30.5f, 6.148f, 0.0f, 0.0f, 0.0f, 0.0f, 0);
             }
         }
References ACTION_OUTRO, EVENT_OUTRO_1, GO_DARK_PORTAL, Unit::InterruptNonMeleeSpells(), ScriptedAI::me, and WorldObject::SummonGameObject().
JustDied()
void npc_medivh_bm::npc_medivh_bmAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 197 of file the_black_morass.cpp.
         {
             me->SetRespawnTime(DAY);
             events.Reset();
             Talk(SAY_DEATH);
         }
References DAY, ScriptedAI::me, SAY_DEATH, Creature::SetRespawnTime(), and CreatureAI::Talk().
JustSummoned()
void npc_medivh_bm::npc_medivh_bmAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 133 of file the_black_morass.cpp.
         {
             if (instance)
                 instance->SetGuidData(DATA_SUMMONED_NPC, summon->GetGUID());
             if (summon->GetEntry() == NPC_DP_CRYSTAL_STALKER)
             {
                 summon->DespawnOrUnsummon(25000);
                 summon->CastSpell(summon, RAND(SPELL_BANISH_PURPLE, SPELL_BANISH_GREEN), true);
                 summon->GetMotionMaster()->MoveSplinePath(&airArray);
             }
             else if (summon->GetEntry() == NPC_DP_EMITTER_STALKER)
             {
                 summon->CastSpell(summon, SPELL_BLACK_CRYSTAL, true);
                 Movement::MoveSplineInit init(summon);
                 init.MovebyPath(groundArray);
                 init.SetCyclic();
                 init.Launch();
             }
         }
References airArray, Unit::CastSpell(), DATA_SUMMONED_NPC, Creature::DespawnOrUnsummon(), Object::GetEntry(), Object::GetGUID(), Unit::GetMotionMaster(), groundArray, instance, Movement::MoveSplineInit::Launch(), Movement::MoveSplineInit::MovebyPath(), MotionMaster::MoveSplinePath(), NPC_DP_CRYSTAL_STALKER, NPC_DP_EMITTER_STALKER, RAND(), Movement::MoveSplineInit::SetCyclic(), ZoneScript::SetGuidData(), SPELL_BANISH_GREEN, SPELL_BANISH_PURPLE, and SPELL_BLACK_CRYSTAL.
MoveInLineOfSight()
void npc_medivh_bm::npc_medivh_bmAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
Definition at line 160 of file the_black_morass.cpp.
         {
             if (!events.Empty() || (instance && instance->GetData(TYPE_AEONUS) == DONE))
                 return;
             if (who->GetTypeId() == TYPEID_PLAYER && me->IsWithinDistInMap(who, 20.0f))
             {
                 Talk(SAY_ENTER);
                 if (instance)
                     instance->SetData(DATA_MEDIVH, 1);
                 me->CastSpell(me, SPELL_MEDIVH_CHANNEL, false);
                 events.ScheduleEvent(EVENT_CHECK_HEALTH_75, 500);
                 events.ScheduleEvent(EVENT_CHECK_HEALTH_50, 500);
                 events.ScheduleEvent(EVENT_CHECK_HEALTH_25, 500);
                 events.ScheduleEvent(EVENT_SUMMON_CRYSTAL, 2000);
                 events.ScheduleEvent(EVENT_SUMMON_CRYSTAL, 4000);
                 events.ScheduleEvent(EVENT_SUMMON_CRYSTAL, 6000);
                 events.ScheduleEvent(EVENT_SUMMON_FLYING_CRYSTAL, 8000);
             }
         }
References Unit::CastSpell(), DATA_MEDIVH, DONE, EVENT_CHECK_HEALTH_25, EVENT_CHECK_HEALTH_50, EVENT_CHECK_HEALTH_75, EVENT_SUMMON_CRYSTAL, EVENT_SUMMON_FLYING_CRYSTAL, ZoneScript::GetData(), Object::GetTypeId(), instance, WorldObject::IsWithinDistInMap(), ScriptedAI::me, SAY_ENTER, ZoneScript::SetData(), SPELL_MEDIVH_CHANNEL, CreatureAI::Talk(), TYPE_AEONUS, and TYPEID_PLAYER.
Reset()
void npc_medivh_bm::npc_medivh_bmAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 124 of file the_black_morass.cpp.
         {
             events.Reset();
             me->CastSpell(me, SPELL_MANA_SHIELD, true);
             if (instance && instance->GetData(TYPE_AEONUS) != DONE)
                 me->CastSpell(me, SPELL_MEDIVH_CHANNEL, false);
         }
References Unit::CastSpell(), DONE, ZoneScript::GetData(), instance, ScriptedAI::me, SPELL_MANA_SHIELD, SPELL_MEDIVH_CHANNEL, and TYPE_AEONUS.
SummonedCreatureDespawn()
void npc_medivh_bm::npc_medivh_bmAI::SummonedCreatureDespawn (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 154 of file the_black_morass.cpp.
         {
             if (instance)
                 instance->SetGuidData(DATA_DELETED_NPC, summon->GetGUID());
         }
References DATA_DELETED_NPC, Object::GetGUID(), instance, and ZoneScript::SetGuidData().
SummonOrcs()
void npc_medivh_bm::npc_medivh_bmAI::SummonOrcs (float x, float y, uint32 duration, uint32 homeTime, bool first) inline
Definition at line 265 of file the_black_morass.cpp.
         {
             for (uint8 i = 0; i < 6; ++i)
             {
                 if (Creature* cr = me->SummonCreature(NPC_SHADOW_COUNCIL_ENFORCER, -2091.731f, 7133.083f - 3.0f * i, 34.589f, 0.0f))
                 {
                     cr->GetMotionMaster()->MovePoint(0, (first && i == 3) ? x + 2.0f : x, cr->GetPositionY() + y, cr->GetMapHeight(x, cr->GetPositionY() + y, cr->GetPositionZ(), true));
                     cr->m_Events.AddEvent(new NpcRunToHome(*cr), cr->m_Events.CalculateTime(homeTime + urand(0, 2000)));
                     cr->DespawnOrUnsummon(duration + urand(0, 2000));
                 }
             }
         }
References ScriptedAI::me, NPC_SHADOW_COUNCIL_ENFORCER, WorldObject::SummonCreature(), and urand().
Referenced by UpdateAI().
UpdateAI()
void npc_medivh_bm::npc_medivh_bmAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 204 of file the_black_morass.cpp.
         {
             events.Update(diff);
             switch (uint32 eventId = events.ExecuteEvent())
             {
                 case EVENT_CHECK_HEALTH_25:
                 case EVENT_CHECK_HEALTH_50:
                 case EVENT_CHECK_HEALTH_75:
                     if (instance && instance->GetData(DATA_SHIELD_PERCENT) <= eventId * 25)
                     {
                         Talk(eventId - 1);
                         break;
                     }
                     events.ScheduleEvent(eventId, 500);
                     break;
                 case EVENT_SUMMON_CRYSTAL:
                     me->SummonCreature(NPC_DP_EMITTER_STALKER, me->GetPositionX() + 8.0f, me->GetPositionY(), me->GetPositionZ());
                     break;
                 case EVENT_SUMMON_FLYING_CRYSTAL:
                     me->CastSpell(me, SPELL_PORTAL_CRYSTALS, true);
                     events.ScheduleEvent(EVENT_SUMMON_FLYING_CRYSTAL, 1000);
                     break;
                 case EVENT_OUTRO_1:
                     me->SetFacingTo(6.21f);
                     Talk(SAY_WIN);
                     events.ScheduleEvent(EVENT_OUTRO_2, 17000);
                     break;
                 case EVENT_OUTRO_2:
                     me->SetFacingTo(3.07f);
                     events.ScheduleEvent(EVENT_OUTRO_3, 2000);
                     break;
                 case EVENT_OUTRO_3:
                     SummonOrcs(-2046.158f, -3.0f, 37000, 30000, true);
                     events.ScheduleEvent(EVENT_OUTRO_4, 2000);
                     break;
                 case EVENT_OUTRO_4:
                     SummonOrcs(-2055.97f, -2.0f, 33000, 28000, false);
                     events.ScheduleEvent(EVENT_OUTRO_5, 2000);
                     break;
                 case EVENT_OUTRO_5:
                     SummonOrcs(-2064.0f, -1.5f, 29000, 26000, false);
                     events.ScheduleEvent(EVENT_OUTRO_6, 2000);
                     break;
                 case EVENT_OUTRO_6:
                     SummonOrcs(-2074.35f, -0.1f, 26000, 24000, false);
                     events.ScheduleEvent(EVENT_OUTRO_7, 7000);
                     break;
                 case EVENT_OUTRO_7:
                     Talk(SAY_ORCS_ENTER);
                     events.ScheduleEvent(EVENT_OUTRO_8, 7000);
                     break;
                 case EVENT_OUTRO_8:
                     if (Creature* cr = me->FindNearestCreature(NPC_SHADOW_COUNCIL_ENFORCER, 20.0f))
                     {
                         cr->SetFacingTo(3.07f);
                         cr->AI()->Talk(SAY_ORCS_ANSWER);
                     }
                     break;
             }
         }
References Unit::CastSpell(), DATA_SHIELD_PERCENT, EVENT_CHECK_HEALTH_25, EVENT_CHECK_HEALTH_50, EVENT_CHECK_HEALTH_75, EVENT_OUTRO_1, EVENT_OUTRO_2, EVENT_OUTRO_3, EVENT_OUTRO_4, EVENT_OUTRO_5, EVENT_OUTRO_6, EVENT_OUTRO_7, EVENT_OUTRO_8, EVENT_SUMMON_CRYSTAL, EVENT_SUMMON_FLYING_CRYSTAL, WorldObject::FindNearestCreature(), ZoneScript::GetData(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), instance, ScriptedAI::me, NPC_DP_EMITTER_STALKER, NPC_SHADOW_COUNCIL_ENFORCER, SAY_ORCS_ANSWER, SAY_ORCS_ENTER, SAY_WIN, Unit::SetFacingTo(), SPELL_PORTAL_CRYSTALS, WorldObject::SummonCreature(), SummonOrcs(), and CreatureAI::Talk().
Member Data Documentation
airArray
Movement::PointsArray npc_medivh_bm::npc_medivh_bmAI::airArray
Definition at line 122 of file the_black_morass.cpp.
Referenced by JustSummoned(), and npc_medivh_bmAI().
events
EventMap npc_medivh_bm::npc_medivh_bmAI::events
Definition at line 120 of file the_black_morass.cpp.
groundArray
Movement::PointsArray npc_medivh_bm::npc_medivh_bmAI::groundArray
Definition at line 121 of file the_black_morass.cpp.
Referenced by JustSummoned(), and npc_medivh_bmAI().
instance
InstanceScript* npc_medivh_bm::npc_medivh_bmAI::instance
Definition at line 119 of file the_black_morass.cpp.
Referenced by JustSummoned(), MoveInLineOfSight(), npc_medivh_bmAI(), Reset(), SummonedCreatureDespawn(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/CavernsOfTime/TheBlackMorass/the_black_morass.cpp