Azerotcore-wotlk: src/common/Utilities/ByteConverter.h File Reference
ByteConverter.h File Reference
#include "Define.h"
#include <algorithm>
Namespaces
ByteConverter
Functions
template<size_t T>
void ByteConverter::convert (char *val)
template<>
void ByteConverter::convert< 0 > (char *)
template<>
void ByteConverter::convert< 1 > (char *)
template<typename T >
void ByteConverter::apply (T *val)
template<typename T >
void EndianConvert (T &val)
template<typename T >
void EndianConvertReverse (T &)
template<typename T >
void EndianConvertPtr (void *val)
template<typename T >
void EndianConvertPtrReverse (void *)
template<typename T >
void EndianConvert (T *)
template<typename T >
void EndianConvertReverse (T *)
void EndianConvert (uint8 &)
void EndianConvert (int8 &)
void EndianConvertReverse (uint8 &)
void EndianConvertReverse (int8 &)
Function Documentation
EndianConvert() [1/4]
void EndianConvert (int8 &) inline
Definition at line 62 of file ByteConverter.h.
 { }
EndianConvert() [2/4]
template<typename T > void EndianConvert (T & val) inline
Definition at line 47 of file ByteConverter.h.
 { ByteConverter::apply<T>(&val); }
Referenced by ByteBuffer::append(), DBCFileLoader::Record::getFloat(), DBCFileLoader::Record::getUInt(), WardenWin::InitializeModule(), DBCFileLoader::Load(), ByteBuffer::put(), ByteBuffer::read(), WorldSocket::ReadHeaderHandler(), and Warden::RequestModule().
EndianConvert() [3/4]
template<typename T > void EndianConvert (T *)
EndianConvert() [4/4]
void EndianConvert (uint8 &) inline
Definition at line 61 of file ByteConverter.h.
 { }
EndianConvertPtr()
template<typename T > void EndianConvertPtr (void * val) inline
Definition at line 49 of file ByteConverter.h.
 { ByteConverter::apply<T>(val); }
EndianConvertPtrReverse()
template<typename T > void EndianConvertPtrReverse (void *) inline
Definition at line 50 of file ByteConverter.h.
 { }
EndianConvertReverse() [1/4]
void EndianConvertReverse (int8 &) inline
Definition at line 64 of file ByteConverter.h.
 { }
EndianConvertReverse() [2/4]
template<typename T > void EndianConvertReverse (T &) inline
Definition at line 48 of file ByteConverter.h.
 { }
Referenced by WorldSocket::ReadHeaderHandler().
EndianConvertReverse() [3/4]
template<typename T > void EndianConvertReverse (T *)
EndianConvertReverse() [4/4]
void EndianConvertReverse (uint8 &) inline
Definition at line 63 of file ByteConverter.h.
 { }