Azerotcore-wotlk: deps/jemalloc/src/rtree.c File Reference
rtree.c File Reference
#include "jemalloc/internal/jemalloc_preamble.h"
#include "jemalloc/internal/jemalloc_internal_includes.h"
#include "jemalloc/internal/assert.h"
#include "jemalloc/internal/mutex.h"
Macros
#define JEMALLOC_RTREE_C_
#define RTREE_GET_CHILD(level)
#define RTREE_GET_LEAF(level)
Functions
bool rtree_new (rtree_t *rtree, bool zeroed)
static rtree_node_elm_t * rtree_node_alloc_impl (tsdn_t *tsdn, rtree_t *rtree, size_t nelms)
static void rtree_node_dalloc_impl (tsdn_t *tsdn, rtree_t *rtree, rtree_node_elm_t *node)
static rtree_leaf_elm_t * rtree_leaf_alloc_impl (tsdn_t *tsdn, rtree_t *rtree, size_t nelms)
static void rtree_leaf_dalloc_impl (tsdn_t *tsdn, rtree_t *rtree, rtree_leaf_elm_t *leaf)
static rtree_node_elm_t * rtree_node_init (tsdn_t *tsdn, rtree_t *rtree, unsigned level, atomic_p_t *elmp)
static rtree_leaf_elm_t * rtree_leaf_init (tsdn_t *tsdn, rtree_t *rtree, atomic_p_t *elmp)
static bool rtree_node_valid (rtree_node_elm_t *node)
static bool rtree_leaf_valid (rtree_leaf_elm_t *leaf)
static rtree_node_elm_t * rtree_child_node_tryread (rtree_node_elm_t *elm, bool dependent)
static rtree_node_elm_t * rtree_child_node_read (tsdn_t *tsdn, rtree_t *rtree, rtree_node_elm_t *elm, unsigned level, bool dependent)
static rtree_leaf_elm_t * rtree_child_leaf_tryread (rtree_node_elm_t *elm, bool dependent)
static rtree_leaf_elm_t * rtree_child_leaf_read (tsdn_t *tsdn, rtree_t *rtree, rtree_node_elm_t *elm, unsigned level, bool dependent)
rtree_leaf_elm_t * rtree_leaf_elm_lookup_hard (tsdn_t *tsdn, rtree_t *rtree, rtree_ctx_t *rtree_ctx, uintptr_t key, bool dependent, bool init_missing)
void rtree_ctx_data_init (rtree_ctx_t *ctx)
Variables
rtree_node_alloc_t *JET_MUTABLE rtree_node_alloc = rtree_node_alloc_impl
rtree_node_dalloc_t *JET_MUTABLE rtree_node_dalloc
rtree_leaf_alloc_t *JET_MUTABLE rtree_leaf_alloc = rtree_leaf_alloc_impl
rtree_leaf_dalloc_t *JET_MUTABLE rtree_leaf_dalloc
Macro Definition Documentation
JEMALLOC_RTREE_C_
#define JEMALLOC_RTREE_C_
Definition at line 1 of file rtree.c.
RTREE_GET_CHILD
#define RTREE_GET_CHILD (level)
Value:
        {                   \
        assert(level < RTREE_HEIGHT-1);             \
        if (level != 0 && !dependent &&             \
            unlikely(!rtree_node_valid(node))) {        \
            return NULL;                    \
        }                           \
        uintptr_t subkey = rtree_subkey(key, level);        \
        if (level + 2 < RTREE_HEIGHT) {             \
            node = init_missing ?               \
                rtree_child_node_read(tsdn, rtree,      \
                &node[subkey], level, dependent) :      \
                rtree_child_node_tryread(&node[subkey], \
                dependent);                 \
        } else {                        \
            leaf = init_missing ?               \
                rtree_child_leaf_read(tsdn, rtree,      \
                &node[subkey], level, dependent) :      \
                rtree_child_leaf_tryread(&node[subkey], \
                dependent);                 \
        }                           \
    }
RTREE_GET_LEAF
#define RTREE_GET_LEAF (level)
Value:
        {                       \
        assert(level == RTREE_HEIGHT-1);            \
        if (!dependent && unlikely(!rtree_leaf_valid(leaf))) {  \
            return NULL;                    \
        }                           \
        if (RTREE_CTX_NCACHE_L2 > 1) {              \
            memmove(&rtree_ctx->l2_cache[1],        \
                &rtree_ctx->l2_cache[0],            \
                sizeof(rtree_ctx_cache_elm_t) *     \
                (RTREE_CTX_NCACHE_L2 - 1));         \
        }                           \
        size_t slot = rtree_cache_direct_map(key);      \
        rtree_ctx->l2_cache[0].leafkey =            \
            rtree_ctx->cache[slot].leafkey;         \
        rtree_ctx->l2_cache[0].leaf =               \
            rtree_ctx->cache[slot].leaf;            \
        uintptr_t leafkey = rtree_leafkey(key);         \
        rtree_ctx->cache[slot].leafkey = leafkey;       \
        rtree_ctx->cache[slot].leaf = leaf;         \
        uintptr_t subkey = rtree_subkey(key, level);        \
        return &leaf[subkey];                   \
    }
Function Documentation
rtree_child_leaf_read()
static rtree_leaf_elm_t* rtree_child_leaf_read (tsdn_t * tsdn, rtree_t * rtree, rtree_node_elm_t * elm, unsigned level, bool dependent) static
Definition at line 210 of file rtree.c.
{
     rtree_leaf_elm_t *leaf;
     leaf = rtree_child_leaf_tryread(elm, dependent);
     if (!dependent && unlikely(!rtree_leaf_valid(leaf))) {
         leaf = rtree_leaf_init(tsdn, rtree, &elm->child);
     }
     assert(!dependent || leaf != NULL);
     return leaf;
 }
References assert(), rtree_node_elm_s::child, NULL, rtree_child_leaf_tryread(), rtree_leaf_init(), rtree_leaf_valid(), and unlikely.
rtree_child_leaf_tryread()
static rtree_leaf_elm_t* rtree_child_leaf_tryread (rtree_node_elm_t * elm, bool dependent) static
Definition at line 194 of file rtree.c.
{
     rtree_leaf_elm_t *leaf;
     if (dependent) {
         leaf = (rtree_leaf_elm_t *)atomic_load_p(&elm->child,
             ATOMIC_RELAXED);
     } else {
         leaf = (rtree_leaf_elm_t *)atomic_load_p(&elm->child,
             ATOMIC_ACQUIRE);
     }
     assert(!dependent || leaf != NULL);
     return leaf;
 }
References assert(), ATOMIC_ACQUIRE, ATOMIC_RELAXED, rtree_node_elm_s::child, and NULL.
Referenced by rtree_child_leaf_read().
rtree_child_node_read()
static rtree_node_elm_t* rtree_child_node_read (tsdn_t * tsdn, rtree_t * rtree, rtree_node_elm_t * elm, unsigned level, bool dependent) static
Definition at line 181 of file rtree.c.
{
     rtree_node_elm_t *node;
     node = rtree_child_node_tryread(elm, dependent);
     if (!dependent && unlikely(!rtree_node_valid(node))) {
         node = rtree_node_init(tsdn, rtree, level + 1, &elm->child);
     }
     assert(!dependent || node != NULL);
     return node;
 }
References assert(), rtree_node_elm_s::child, NULL, rtree_child_node_tryread(), rtree_node_init(), rtree_node_valid(), and unlikely.
rtree_child_node_tryread()
static rtree_node_elm_t* rtree_child_node_tryread (rtree_node_elm_t * elm, bool dependent) static
Definition at line 165 of file rtree.c.
{
     rtree_node_elm_t *node;
     if (dependent) {
         node = (rtree_node_elm_t *)atomic_load_p(&elm->child,
             ATOMIC_RELAXED);
     } else {
         node = (rtree_node_elm_t *)atomic_load_p(&elm->child,
             ATOMIC_ACQUIRE);
     }
     assert(!dependent || node != NULL);
     return node;
 }
References assert(), ATOMIC_ACQUIRE, ATOMIC_RELAXED, rtree_node_elm_s::child, and NULL.
Referenced by rtree_child_node_read().
rtree_ctx_data_init()
void rtree_ctx_data_init (rtree_ctx_t * ctx)
Definition at line 309 of file rtree.c.
{
     for (unsigned i = 0; i < RTREE_CTX_NCACHE; i++) {
         rtree_ctx_cache_elm_t *cache = &ctx->cache[i];
         cache->leafkey = RTREE_LEAFKEY_INVALID;
         cache->leaf = NULL;
     }
     for (unsigned i = 0; i < RTREE_CTX_NCACHE_L2; i++) {
         rtree_ctx_cache_elm_t *cache = &ctx->l2_cache[i];
         cache->leafkey = RTREE_LEAFKEY_INVALID;
         cache->leaf = NULL;
     }
 }
References rtree_ctx_s::cache, rtree_ctx_s::l2_cache, rtree_ctx_cache_elm_s::leaf, rtree_ctx_cache_elm_s::leafkey, NULL, RTREE_CTX_NCACHE, RTREE_CTX_NCACHE_L2, and RTREE_LEAFKEY_INVALID.
rtree_leaf_alloc_impl()
static rtree_leaf_elm_t* rtree_leaf_alloc_impl (tsdn_t * tsdn, rtree_t * rtree, size_t nelms) static
Definition at line 46 of file rtree.c.
{
     return (rtree_leaf_elm_t *)base_alloc(tsdn, b0get(), nelms *
         sizeof(rtree_leaf_elm_t), CACHELINE);
 }
References b0get, base_alloc, and CACHELINE.
rtree_leaf_dalloc_impl()
static void rtree_leaf_dalloc_impl (tsdn_t * tsdn, rtree_t * rtree, rtree_leaf_elm_t * leaf) static
Definition at line 53 of file rtree.c.
{
     /* Leaves are never deleted during normal operation. */
     not_reached();
 }
References not_reached.
rtree_leaf_elm_lookup_hard()
rtree_leaf_elm_t* rtree_leaf_elm_lookup_hard (tsdn_t * tsdn, rtree_t * rtree, rtree_ctx_t * rtree_ctx, uintptr_t key, bool dependent, bool init_missing)
Definition at line 223 of file rtree.c.
{
     rtree_node_elm_t *node;
     rtree_leaf_elm_t *leaf;
 #if RTREE_HEIGHT > 1
     node = rtree->root;
 #else
     leaf = rtree->root;
 #endif
     if (config_debug) {
         uintptr_t leafkey = rtree_leafkey(key);
         for (unsigned i = 0; i < RTREE_CTX_NCACHE; i++) {
             assert(rtree_ctx->cache[i].leafkey != leafkey);
         }
         for (unsigned i = 0; i < RTREE_CTX_NCACHE_L2; i++) {
             assert(rtree_ctx->l2_cache[i].leafkey != leafkey);
         }
     }
 #define RTREE_GET_CHILD(level) {                    \
         assert(level < RTREE_HEIGHT-1);             \
         if (level != 0 && !dependent &&             \
             unlikely(!rtree_node_valid(node))) {        \
             return NULL;                    \
         }                           \
         uintptr_t subkey = rtree_subkey(key, level);        \
         if (level + 2 < RTREE_HEIGHT) {             \
             node = init_missing ?               \
                 rtree_child_node_read(tsdn, rtree,      \
                 &node[subkey], level, dependent) :      \
                 rtree_child_node_tryread(&node[subkey], \
                 dependent);                 \
         } else {                        \
             leaf = init_missing ?               \
                 rtree_child_leaf_read(tsdn, rtree,      \
                 &node[subkey], level, dependent) :      \
                 rtree_child_leaf_tryread(&node[subkey], \
                 dependent);                 \
         }                           \
     }
     /*
      * Cache replacement upon hard lookup (i.e. L1 & L2 rtree cache miss):
      * (1) evict last entry in L2 cache; (2) move the collision slot from L1
      * cache down to L2; and 3) fill L1.
      */
 #define RTREE_GET_LEAF(level) {                     \
         assert(level == RTREE_HEIGHT-1);            \
         if (!dependent && unlikely(!rtree_leaf_valid(leaf))) {  \
             return NULL;                    \
         }                           \
         if (RTREE_CTX_NCACHE_L2 > 1) {              \
             memmove(&rtree_ctx->l2_cache[1],        \
                 &rtree_ctx->l2_cache[0],            \
                 sizeof(rtree_ctx_cache_elm_t) *     \
                 (RTREE_CTX_NCACHE_L2 - 1));         \
         }                           \
         size_t slot = rtree_cache_direct_map(key);      \
         rtree_ctx->l2_cache[0].leafkey =            \
             rtree_ctx->cache[slot].leafkey;         \
         rtree_ctx->l2_cache[0].leaf =               \
             rtree_ctx->cache[slot].leaf;            \
         uintptr_t leafkey = rtree_leafkey(key);         \
         rtree_ctx->cache[slot].leafkey = leafkey;       \
         rtree_ctx->cache[slot].leaf = leaf;         \
         uintptr_t subkey = rtree_subkey(key, level);        \
         return &leaf[subkey];                   \
     }
     if (RTREE_HEIGHT > 1) {
         RTREE_GET_CHILD(0)
     }
     if (RTREE_HEIGHT > 2) {
         RTREE_GET_CHILD(1)
     }
     if (RTREE_HEIGHT > 3) {
         for (unsigned i = 2; i < RTREE_HEIGHT-1; i++) {
             RTREE_GET_CHILD(i)
         }
     }
     RTREE_GET_LEAF(RTREE_HEIGHT-1)
 #undef RTREE_GET_CHILD
 #undef RTREE_GET_LEAF
     not_reached();
 }
References assert(), rtree_ctx_s::cache, config_debug, rtree_ctx_s::l2_cache, rtree_ctx_cache_elm_s::leafkey, not_reached, rtree_s::root, RTREE_CTX_NCACHE, RTREE_CTX_NCACHE_L2, RTREE_GET_CHILD, RTREE_GET_LEAF, RTREE_HEIGHT, and rtree_leafkey().
Referenced by rtree_leaf_elm_lookup().
rtree_leaf_init()
static rtree_leaf_elm_t* rtree_leaf_init (tsdn_t * tsdn, rtree_t * rtree, atomic_p_t * elmp) static
Definition at line 129 of file rtree.c.
{
     malloc_mutex_lock(tsdn, &rtree->init_lock);
     /*
      * If *elmp is non-null, then it was initialized with the init lock
      * held, so we can get by with 'relaxed' here.
      */
     rtree_leaf_elm_t *leaf = atomic_load_p(elmp, ATOMIC_RELAXED);
     if (leaf == NULL) {
         leaf = rtree_leaf_alloc(tsdn, rtree, ZU(1) <<
             rtree_levels[RTREE_HEIGHT-1].bits);
         if (leaf == NULL) {
             malloc_mutex_unlock(tsdn, &rtree->init_lock);
             return NULL;
         }
         /*
          * Even though we hold the lock, a later reader might not; we
          * need release semantics.
          */
         atomic_store_p(elmp, leaf, ATOMIC_RELEASE);
     }
     malloc_mutex_unlock(tsdn, &rtree->init_lock);
     return leaf;
 }
References ATOMIC_RELAXED, ATOMIC_RELEASE, G3D::bits(), rtree_s::init_lock, malloc_mutex_lock(), malloc_mutex_unlock(), NULL, RTREE_HEIGHT, rtree_leaf_alloc, rtree_levels, and ZU.
Referenced by rtree_child_leaf_read().
rtree_leaf_valid()
static bool rtree_leaf_valid (rtree_leaf_elm_t * leaf) static
Definition at line 160 of file rtree.c.
{
     return ((uintptr_t)leaf != (uintptr_t)0);
 }
Referenced by rtree_child_leaf_read().
rtree_new()
bool rtree_new (rtree_t * rtree, bool zeroed)
Definition at line 13 of file rtree.c.
{
 #ifdef JEMALLOC_JET
     if (!zeroed) {
         memset(rtree, 0, sizeof(rtree_t)); /* Clear root. */
     }
 #else
     assert(zeroed);
 #endif
     if (malloc_mutex_init(&rtree->init_lock, "rtree", WITNESS_RANK_RTREE,
         malloc_mutex_rank_exclusive)) {
         return true;
     }
     return false;
 }
References assert(), rtree_s::init_lock, malloc_mutex_init, malloc_mutex_rank_exclusive, memset, and WITNESS_RANK_RTREE.
rtree_node_alloc_impl()
static rtree_node_elm_t* rtree_node_alloc_impl (tsdn_t * tsdn, rtree_t * rtree, size_t nelms) static
Definition at line 31 of file rtree.c.
{
     return (rtree_node_elm_t *)base_alloc(tsdn, b0get(), nelms *
         sizeof(rtree_node_elm_t), CACHELINE);
 }
References b0get, base_alloc, and CACHELINE.
rtree_node_dalloc_impl()
static void rtree_node_dalloc_impl (tsdn_t * tsdn, rtree_t * rtree, rtree_node_elm_t * node) static
Definition at line 38 of file rtree.c.
{
     /* Nodes are never deleted during normal operation. */
     not_reached();
 }
References not_reached.
rtree_node_init()
static rtree_node_elm_t* rtree_node_init (tsdn_t * tsdn, rtree_t * rtree, unsigned level, atomic_p_t * elmp) static
Definition at line 102 of file rtree.c.
                       {
     malloc_mutex_lock(tsdn, &rtree->init_lock);
     /*
      * If *elmp is non-null, then it was initialized with the init lock
      * held, so we can get by with 'relaxed' here.
      */
     rtree_node_elm_t *node = atomic_load_p(elmp, ATOMIC_RELAXED);
     if (node == NULL) {
         node = rtree_node_alloc(tsdn, rtree, ZU(1) <<
             rtree_levels[level].bits);
         if (node == NULL) {
             malloc_mutex_unlock(tsdn, &rtree->init_lock);
             return NULL;
         }
         /*
          * Even though we hold the lock, a later reader might not; we
          * need release semantics.
          */
         atomic_store_p(elmp, node, ATOMIC_RELEASE);
     }
     malloc_mutex_unlock(tsdn, &rtree->init_lock);
     return node;
 }
References ATOMIC_RELAXED, ATOMIC_RELEASE, G3D::bits(), rtree_s::init_lock, malloc_mutex_lock(), malloc_mutex_unlock(), NULL, rtree_levels, rtree_node_alloc, and ZU.
Referenced by rtree_child_node_read().
rtree_node_valid()
static bool rtree_node_valid (rtree_node_elm_t * node) static
Definition at line 155 of file rtree.c.
{
     return ((uintptr_t)node != (uintptr_t)0);
 }
Referenced by rtree_child_node_read().
Variable Documentation
rtree_leaf_alloc
rtree_leaf_alloc_t* JET_MUTABLE rtree_leaf_alloc = rtree_leaf_alloc_impl
Definition at line 50 of file rtree.c.
Referenced by rtree_leaf_init().
rtree_leaf_dalloc
rtree_leaf_dalloc_t* JET_MUTABLE rtree_leaf_dalloc
Initial value:
=
    rtree_leaf_dalloc_impl
Definition at line 57 of file rtree.c.
rtree_node_alloc
rtree_node_alloc_t* JET_MUTABLE rtree_node_alloc = rtree_node_alloc_impl
Definition at line 35 of file rtree.c.
Referenced by rtree_node_init().
rtree_node_dalloc
rtree_node_dalloc_t* JET_MUTABLE rtree_node_dalloc
Initial value:
=
    rtree_node_dalloc_impl
Definition at line 42 of file rtree.c.