Azerotcore-wotlk: FactorySelector Namespace Reference
FactorySelector Namespace Reference
Functions
CreatureAI * selectAI (Creature *creature)
MovementGenerator * selectMovementGenerator (Creature *creature)
GameObjectAI * SelectGameObjectAI (GameObject *go)
Function Documentation
selectAI()
CreatureAI * FactorySelector::selectAI (Creature * creature)
Definition at line 29 of file CreatureAISelector.cpp.
     {
         const CreatureAICreator* ai_factory = nullptr;
         CreatureAIRegistry& ai_registry(*CreatureAIRegistry::instance());
         // xinef: if we have controlable guardian, define petai for players as they can steer him, otherwise db / normal ai
         // xinef: dont remember why i changed this qq commented out as may break some quests
         if (creature->IsPet()/* || (creature->HasUnitTypeMask(UNIT_MASK_CONTROLABLE_GUARDIAN) && ((Guardian*)creature)->GetOwner()->GetTypeId() == TYPEID_PLAYER)*/)
             ai_factory = ai_registry.GetRegistryItem("PetAI");
         //scriptname in db
         if (!ai_factory)
             if (CreatureAI* scriptedAI = sScriptMgr->GetCreatureAI(creature))
                 return scriptedAI;
         // AIname in db
         std::string ainame = creature->GetAIName();
         if (!ai_factory && !ainame.empty())
             ai_factory = ai_registry.GetRegistryItem(ainame);
         // select by NPC flags
         if (!ai_factory)
         {
             if (creature->IsVehicle())
                 ai_factory = ai_registry.GetRegistryItem("VehicleAI");
             else if (creature->HasUnitTypeMask(UNIT_MASK_CONTROLABLE_GUARDIAN) && ((Guardian*)creature)->GetOwner()->GetTypeId() == TYPEID_PLAYER)
                 ai_factory = ai_registry.GetRegistryItem("PetAI");
             else if (creature->HasFlag(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_SPELLCLICK))
                 ai_factory = ai_registry.GetRegistryItem("NullCreatureAI");
             else if (creature->IsGuard())
                 ai_factory = ai_registry.GetRegistryItem("GuardAI");
             else if (creature->HasUnitTypeMask(UNIT_MASK_CONTROLABLE_GUARDIAN))
                 ai_factory = ai_registry.GetRegistryItem("PetAI");
             else if (creature->IsTotem())
                 ai_factory = ai_registry.GetRegistryItem("TotemAI");
             else if (creature->IsTrigger())
             {
                 if (creature->m_spells[0])
                     ai_factory = ai_registry.GetRegistryItem("TriggerAI");
                 else
                     ai_factory = ai_registry.GetRegistryItem("NullCreatureAI");
             }
             else if (creature->IsCritter() && !creature->HasUnitTypeMask(UNIT_MASK_GUARDIAN))
                 ai_factory = ai_registry.GetRegistryItem("CritterAI");
         }
         // select by permit check
         if (!ai_factory)
         {
             int best_val = -1;
             typedef CreatureAIRegistry::RegistryMapType RMT;
             RMT const& l = ai_registry.GetRegisteredItems();
             for (RMT::const_iterator iter = l.begin(); iter != l.end(); ++iter)
             {
                 const CreatureAICreator* factory = iter->second;
                 const SelectableAI* p = dynamic_cast<const SelectableAI*>(factory);
                 ASSERT(p);
                 int val = p->Permit(creature);
                 if (val > best_val)
                 {
                     best_val = val;
                     ai_factory = p;
                 }
             }
         }
         // select NullCreatureAI if not another cases
         ainame = (ai_factory == nullptr) ? "NullCreatureAI" : ai_factory->key();
         LOG_DEBUG("scripts.ai", "Creature %s used AI is %s.", creature->GetGUID().ToString().c_str(), ainame.c_str());
         return (ai_factory == nullptr ? new NullCreatureAI(creature) : ai_factory->Create(creature));
     }
References ASSERT, FactoryHolder< T, Key >::Create(), Creature::GetAIName(), Object::GetGUID(), Object::HasFlag(), Unit::HasUnitTypeMask(), Unit::IsCritter(), Creature::IsGuard(), Unit::IsPet(), Unit::IsTotem(), Creature::IsTrigger(), Unit::IsVehicle(), FactoryHolder< T, Key >::key(), LOG_DEBUG, Creature::m_spells, Permissible< T >::Permit(), sScriptMgr, ObjectGuid::ToString(), TYPEID_PLAYER, UNIT_MASK_CONTROLABLE_GUARDIAN, UNIT_MASK_GUARDIAN, UNIT_NPC_FLAG_SPELLCLICK, and UNIT_NPC_FLAGS.
Referenced by Creature::AIM_Initialize().
SelectGameObjectAI()
GameObjectAI * FactorySelector::SelectGameObjectAI (GameObject * go)
Definition at line 129 of file CreatureAISelector.cpp.
     {
         const GameObjectAICreator* ai_factory = nullptr;
         GameObjectAIRegistry& ai_registry(*GameObjectAIRegistry::instance());
         if (GameObjectAI* scriptedAI = sScriptMgr->GetGameObjectAI(go))
             return scriptedAI;
         ai_factory = ai_registry.GetRegistryItem(go->GetAIName());
         //future goAI types go here
         std::string ainame = (ai_factory == nullptr || go->GetScriptId()) ? "NullGameObjectAI" : ai_factory->key();
         LOG_DEBUG("scripts.ai", "GameObject %s used AI is %s.", go->GetGUID().ToString().c_str(), ainame.c_str());
         return (ai_factory == nullptr ? new NullGameObjectAI(go) : ai_factory->Create(go));
     }
References FactoryHolder< T, Key >::Create(), GameObject::GetAIName(), Object::GetGUID(), GameObject::GetScriptId(), FactoryHolder< T, Key >::key(), LOG_DEBUG, sScriptMgr, and ObjectGuid::ToString().
Referenced by GameObject::AIM_Initialize().
selectMovementGenerator()
MovementGenerator * FactorySelector::selectMovementGenerator (Creature * creature)
Definition at line 101 of file CreatureAISelector.cpp.
     {
         MovementGeneratorRegistry& mv_registry(*MovementGeneratorRegistry::instance());
         ASSERT(creature->GetCreatureTemplate());
         const MovementGeneratorCreator* mv_factory = mv_registry.GetRegistryItem(creature->GetDefaultMovementType());
         /* if (mv_factory == nullptr)
         {
             int best_val = -1;
             std::vector<std::string> l;
             mv_registry.GetRegisteredItems(l);
             for (std::vector<std::string>::iterator iter = l.begin(); iter != l.end(); ++iter)
             {
             const MovementGeneratorCreator *factory = mv_registry.GetRegistryItem((*iter).c_str());
             const SelectableMovement *p = dynamic_cast<const SelectableMovement *>(factory);
             ASSERT(p != nullptr);
             int val = p->Permit(creature);
             if (val > best_val)
             {
                 best_val = val;
                 mv_factory = p;
             }
             }
         }*/
         return (mv_factory == nullptr ? nullptr : mv_factory->Create(creature));
     }
References ASSERT, FactoryHolder< T, Key >::Create(), Creature::GetCreatureTemplate(), and Creature::GetDefaultMovementType().
Referenced by MotionMaster::InitDefault().