Azerotcore-wotlk: boss_marli::boss_marliAI Struct Reference
boss_marli::boss_marliAI Struct Reference
Public Member Functions
boss_marliAI (Creature *creature)
void Reset () override
void JustDied (Unit *) override
void EnterCombat (Unit *) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 71 of file boss_marli.cpp.
Constructor & Destructor Documentation
boss_marliAI()
boss_marli::boss_marliAI::boss_marliAI (Creature * creature) inline
Definition at line 73 of file boss_marli.cpp.
 : BossAI(creature, DATA_MARLI) { }
Member Function Documentation
EnterCombat()
void boss_marli::boss_marliAI::EnterCombat (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 88 of file boss_marli.cpp.
         {
             _EnterCombat();
             events.ScheduleEvent(EVENT_SPAWN_START_SPIDERS, 1000, 0, PHASE_ONE);
             Talk(SAY_AGGRO);
         }
References BossAI::_EnterCombat(), EVENT_SPAWN_START_SPIDERS, PHASE_ONE, SAY_AGGRO, and CreatureAI::Talk().
JustDied()
void boss_marli::boss_marliAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 82 of file boss_marli.cpp.
         {
             _JustDied();
             Talk(SAY_DEATH);
         }
References BossAI::_JustDied(), SAY_DEATH, and CreatureAI::Talk().
Reset()
void boss_marli::boss_marliAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 75 of file boss_marli.cpp.
         {
             if (events.IsInPhase(PHASE_THREE))
                 me->HandleStatModifier(UNIT_MOD_DAMAGE_MAINHAND, TOTAL_PCT, 35.0f, false); // hack
             _Reset();
         }
References BossAI::_Reset(), Unit::HandleStatModifier(), ScriptedAI::me, PHASE_THREE, TOTAL_PCT, and UNIT_MOD_DAMAGE_MAINHAND.
UpdateAI()
void boss_marli::boss_marliAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 95 of file boss_marli.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             while (uint32 eventId = events.ExecuteEvent())
             {
                 switch (eventId)
                 {
                     case EVENT_SPAWN_START_SPIDERS:
                         if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
{
                             Talk(SAY_SPIDER_SPAWN);
                             Creature* Spider = me->SummonCreature(15041, target->GetPositionX(), target->GetPositionY(), target->GetPositionZ(), 0, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 15000);
                             if (Spider)
                                 Spider->AI()->AttackStart(target);
                             Spider = me->SummonCreature(15041, target->GetPositionX(), target->GetPositionY(), target->GetPositionZ(), 0, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 15000);
                             if (Spider)
                                 Spider->AI()->AttackStart(target);
                             Spider = me->SummonCreature(15041, target->GetPositionX(), target->GetPositionY(), target->GetPositionZ(), 0, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 15000);
                             if (Spider)
                                 Spider->AI()->AttackStart(target);
                             Spider = me->SummonCreature(15041, target->GetPositionX(), target->GetPositionY(), target->GetPositionZ(), 0, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 15000);
                             if (Spider)
                                 Spider->AI()->AttackStart(target);
                         }
                         events.ScheduleEvent(EVENT_ASPECT_OF_MARLI, 12000, 0, PHASE_TWO);
                         events.ScheduleEvent(EVENT_TRANSFORM, 45000, 0, PHASE_TWO);
                         events.ScheduleEvent(EVENT_POISON_VOLLEY, 15000);
                         events.ScheduleEvent(EVENT_SPAWN_SPIDER, 30000);
                         events.ScheduleEvent(EVENT_TRANSFORM, 45000, 0, PHASE_TWO);
                         events.SetPhase(PHASE_TWO);
                         break;
                     case EVENT_POISON_VOLLEY:
                         DoCastVictim(SPELL_POISON_VOLLEY, true);
                         events.ScheduleEvent(EVENT_POISON_VOLLEY, urand(10000, 20000));
                         break;
                     case EVENT_ASPECT_OF_MARLI:
                         DoCastVictim(SPELL_ASPECT_OF_MARLI, true);
                         events.ScheduleEvent(EVENT_ASPECT_OF_MARLI, urand(13000, 18000), 0, PHASE_TWO);
                         break;
                     case EVENT_SPAWN_SPIDER:
                         if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
{
                             Creature* Spider = me->SummonCreature(15041, target->GetPositionX(), target->GetPositionY(), target->GetPositionZ(), 0, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 15000);
                             if (Spider)
                                 Spider->AI()->AttackStart(target);
                         }
                         events.ScheduleEvent(EVENT_SPAWN_SPIDER, urand(12000, 17000));
                         break;
                     case EVENT_TRANSFORM:
{
                             Talk(SAY_TRANSFORM);
                             DoCast(me, SPELL_SPIDER_FORM); // SPELL_AURA_TRANSFORM
                             /*
                             CreatureTemplate const* cinfo = me->GetCreatureTemplate();
                             me->SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, (cinfo->mindmg +((cinfo->mindmg/100) * 35)));
                             me->SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, (cinfo->maxdmg +((cinfo->maxdmg/100) * 35)));
                             me->UpdateDamagePhysical(BASE_ATTACK);
                             */
                             me->HandleStatModifier(UNIT_MOD_DAMAGE_MAINHAND, TOTAL_PCT, 35.0f, true); // hack
                             DoCastVictim(SPELL_ENVOLWINGWEB);
                             if (DoGetThreat(me->GetVictim()))
                                 DoModifyThreatPercent(me->GetVictim(), -100);
                             events.ScheduleEvent(EVENT_CHARGE_PLAYER, 1500, 0, PHASE_THREE);
                             events.ScheduleEvent(EVENT_TRANSFORM_BACK, 25000, 0, PHASE_THREE);
                             events.SetPhase(PHASE_THREE);
                             break;
                         }
                     case EVENT_CHARGE_PLAYER:
{
                             Unit* target = nullptr;
                             int i = 0;
                             while (i++ < 3) // max 3 tries to get a random target with power_mana
{
                                 target = SelectTarget(SELECT_TARGET_RANDOM, 1, 100, true);  // not aggro leader
                                 if (target && target->getPowerType() == POWER_MANA)
                                     break;
                             }
                             if (target)
{
                                 DoCast(target, SPELL_CHARGE);
                                 AttackStart(target);
                             }
                             events.ScheduleEvent(EVENT_CHARGE_PLAYER, 8000, 0, PHASE_THREE);
                             break;
                         }
                     case EVENT_TRANSFORM_BACK:
{
                             me->RemoveAura(SPELL_SPIDER_FORM);
                             /*
                             CreatureTemplate const* cinfo = me->GetCreatureTemplate();
                             me->SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, (cinfo->mindmg +((cinfo->mindmg/100) * 1)));
                             me->SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, (cinfo->maxdmg +((cinfo->maxdmg/100) * 1)));
                             me->UpdateDamagePhysical(BASE_ATTACK);
                             */
                             me->HandleStatModifier(UNIT_MOD_DAMAGE_MAINHAND, TOTAL_PCT, 35.0f, false); // hack
                             events.ScheduleEvent(EVENT_ASPECT_OF_MARLI, 12000, 0, PHASE_TWO);
                             events.ScheduleEvent(EVENT_TRANSFORM, 45000, 0, PHASE_TWO);
                             events.ScheduleEvent(EVENT_POISON_VOLLEY, 15000);
                             events.ScheduleEvent(EVENT_SPAWN_SPIDER, 30000);
                             events.ScheduleEvent(EVENT_TRANSFORM, urand(35000, 60000), 0, PHASE_TWO);
                             events.SetPhase(PHASE_TWO);
                             break;
                         }
                     default:
                         break;
                 }
             }
             DoMeleeAttackIfReady();
         }
References Creature::AI(), UnitAI::AttackStart(), ScriptedAI::AttackStart(), UnitAI::DoCast(), UnitAI::DoCastVictim(), ScriptedAI::DoGetThreat(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DoModifyThreatPercent(), EVENT_ASPECT_OF_MARLI, EVENT_CHARGE_PLAYER, EVENT_POISON_VOLLEY, EVENT_SPAWN_SPIDER, EVENT_SPAWN_START_SPIDERS, EVENT_TRANSFORM, EVENT_TRANSFORM_BACK, Unit::getPowerType(), Unit::GetVictim(), Unit::HandleStatModifier(), Unit::HasUnitState(), ScriptedAI::me, PHASE_THREE, PHASE_TWO, POWER_MANA, Unit::RemoveAura(), SAY_SPIDER_SPAWN, SAY_TRANSFORM, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), SPELL_ASPECT_OF_MARLI, SPELL_CHARGE, SPELL_ENVOLWINGWEB, SPELL_POISON_VOLLEY, SPELL_SPIDER_FORM, WorldObject::SummonCreature(), CreatureAI::Talk(), TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, TOTAL_PCT, UNIT_MOD_DAMAGE_MAINHAND, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/ZulGurub/boss_marli.cpp