Azerotcore-wotlk: SOAPCommand Class Reference
SOAPCommand Class Reference
#include <ACSoap.h>
Public Member Functions
SOAPCommand ()
~SOAPCommand ()
void appendToPrintBuffer (std::string_view msg)
void setCommandSuccess (bool val)
bool hasCommandSucceeded () const
Static Public Member Functions
static void print (void *callbackArg, std::string_view msg)
static void commandFinished (void *callbackArg, bool success)
Public Attributes
bool m_success
std::string m_printBuffer
std::promise< void > finishedPromise
Detailed Description
Definition at line 28 of file ACSoap.h.
Constructor & Destructor Documentation
SOAPCommand()
SOAPCommand::SOAPCommand () inline
Definition at line 31 of file ACSoap.h.
                   :
         m_success(false) { }
~SOAPCommand()
SOAPCommand::~SOAPCommand () inline
Definition at line 34 of file ACSoap.h.
 { }
Member Function Documentation
appendToPrintBuffer()
void SOAPCommand::appendToPrintBuffer (std::string_view msg) inline
Definition at line 36 of file ACSoap.h.
     {
         m_printBuffer += msg;
     }
References m_printBuffer.
commandFinished()
void SOAPCommand::commandFinished (void * callbackArg, bool success) static
Definition at line 130 of file ACSoap.cpp.
 {
     SOAPCommand* con = (SOAPCommand*)soapconnection;
     con->setCommandSuccess(success);
 }
References setCommandSuccess().
Referenced by ns1__executeCommand().
hasCommandSucceeded()
bool SOAPCommand::hasCommandSucceeded () const inline
Definition at line 47 of file ACSoap.h.
     {
         return m_success;
     }
References m_success.
Referenced by ns1__executeCommand().
print()
static void SOAPCommand::print (void * callbackArg, std::string_view msg) inline static
Definition at line 52 of file ACSoap.h.
     {
         ((SOAPCommand*)callbackArg)->appendToPrintBuffer(msg);
     }
Referenced by ns1__executeCommand().
setCommandSuccess()
void SOAPCommand::setCommandSuccess (bool val) inline
Definition at line 41 of file ACSoap.h.
     {
         m_success = val;
         finishedPromise.set_value();
     }
References finishedPromise, and m_success.
Referenced by commandFinished().
Member Data Documentation
finishedPromise
std::promise<void> SOAPCommand::finishedPromise
Definition at line 61 of file ACSoap.h.
Referenced by ns1__executeCommand(), and setCommandSuccess().
m_printBuffer
std::string SOAPCommand::m_printBuffer
Definition at line 60 of file ACSoap.h.
Referenced by appendToPrintBuffer(), and ns1__executeCommand().
m_success
bool SOAPCommand::m_success
Definition at line 59 of file ACSoap.h.
Referenced by hasCommandSucceeded(), and setCommandSuccess().
The documentation for this class was generated from the following files:
src/server/worldserver/ACSoap/ACSoap.h
src/server/worldserver/ACSoap/ACSoap.cpp