Azerotcore-wotlk: go_prince_taldaram_sphere Class Reference
go_prince_taldaram_sphere Class Reference
Public Member Functions
go_prince_taldaram_sphere ()
bool OnGossipHello (Player *pPlayer, GameObject *go) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Definition at line 515 of file boss_prince_taldaram.cpp.
Constructor & Destructor Documentation
go_prince_taldaram_sphere()
go_prince_taldaram_sphere::go_prince_taldaram_sphere () inline
Definition at line 518 of file boss_prince_taldaram.cpp.
 : GameObjectScript("go_prince_taldaram_sphere") { }
Member Function Documentation
OnGossipHello()
bool go_prince_taldaram_sphere::OnGossipHello (Player * pPlayer, GameObject * go) inline override virtual
Reimplemented from GameObjectScript.
Definition at line 520 of file boss_prince_taldaram.cpp.
     {
         if (pPlayer && pPlayer->IsInCombat())
         {
             return true;
         }
         InstanceScript *pInstance = go->GetInstanceScript();
         if (!pInstance)
         {
             return true;
         }
         go->SetFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
         go->SetGoState(GO_STATE_ACTIVE);
         uint32 const objectIndex = go->GetEntry() == GO_TELDARAM_SPHERE1 ? DATA_TELDRAM_SPHERE1 : DATA_TELDRAM_SPHERE2;
         if (pInstance->GetData(objectIndex) == NOT_STARTED)
         {
             Creature* taldaram = ObjectAccessor::GetCreature(*go, pInstance->GetGuidData(DATA_PRINCE_TALDARAM));
             if (taldaram && taldaram->IsAlive())
             {
                 taldaram->AI()->Talk(SAY_SPHERE_ACTIVATED);
             }
             pInstance->SetData(objectIndex, DONE);
         }
         return true;
     }
References Creature::AI(), DATA_PRINCE_TALDARAM, DATA_TELDRAM_SPHERE1, DATA_TELDRAM_SPHERE2, DONE, GAMEOBJECT_FLAGS, ObjectAccessor::GetCreature(), ZoneScript::GetData(), Object::GetEntry(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), GO_FLAG_NOT_SELECTABLE, GO_STATE_ACTIVE, GO_TELDARAM_SPHERE1, Unit::IsAlive(), Unit::IsInCombat(), NOT_STARTED, SAY_SPHERE_ACTIVATED, ZoneScript::SetData(), Object::SetFlag(), GameObject::SetGoState(), and CreatureAI::Talk().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/AzjolNerub/ahnkahet/boss_prince_taldaram.cpp