Azerotcore-wotlk: GridRefMgr< OBJECT > Class Template Reference
GridRefMgr< OBJECT > Class Template Reference
#include <GridRefMgr.h>
Public Types
typedef LinkedListHead::Iterator< GridReference< OBJECT > > iterator
Public Types inherited from RefMgr< GridRefMgr< OBJECT >, OBJECT >
typedef LinkedListHead::Iterator< Reference< GridRefMgr< OBJECT >, OBJECT > > iterator
Public Types inherited from LinkedListHead
typedef Iterator< LinkedListElement > iterator
Public Member Functions
GridReference< OBJECT > * getFirst ()
GridReference< OBJECT > * getLast ()
iterator begin ()
iterator end ()
iterator rbegin ()
iterator rend ()
Public Member Functions inherited from RefMgr< GridRefMgr< OBJECT >, OBJECT >
RefMgr ()=default
virtual ~RefMgr ()
Reference< GridRefMgr< OBJECT >, OBJECT > * getFirst ()
Reference< GridRefMgr< OBJECT >, OBJECT > const * getFirst () const
Reference< GridRefMgr< OBJECT >, OBJECT > * getLast ()
Reference< GridRefMgr< OBJECT >, OBJECT > const * getLast () const
iterator begin ()
iterator end ()
iterator rbegin ()
iterator rend ()
void clearReferences ()
Public Member Functions inherited from LinkedListHead
LinkedListHead ()
bool isEmpty () const
LinkedListElement * getFirst ()
LinkedListElement const * getFirst () const
LinkedListElement * getLast ()
LinkedListElement const * getLast () const
void insertFirst (LinkedListElement *pElem)
void insertLast (LinkedListElement *pElem)
uint32 getSize () const
void incSize ()
void decSize ()
Detailed Description
template<class OBJECT>
class GridRefMgr< OBJECT >
Definition at line 27 of file GridRefMgr.h.
Member Typedef Documentation
iterator
template<class OBJECT > typedef LinkedListHead::Iterator< GridReference<OBJECT> > GridRefMgr< OBJECT >::iterator
Definition at line 30 of file GridRefMgr.h.
Member Function Documentation
begin()
template<class OBJECT > iterator GridRefMgr< OBJECT >::begin () inline
Definition at line 35 of file GridRefMgr.h.
 { return iterator(getFirst()); }
References GridRefMgr< OBJECT >::getFirst().
Referenced by ResetNotifier::resetNotify(), Acore::AIRelocationNotifier::Visit(), Acore::UnitSearcher< Check >::Visit(), Acore::UnitLastSearcher< Check >::Visit(), Acore::CreatureSearcher< Check >::Visit(), Acore::CreatureLastSearcher< Check >::Visit(), Acore::CreatureListSearcher< Check >::Visit(), Acore::CreatureWorker< Do >::Visit(), Acore::VisibleNotifier::Visit(), Acore::WorldObjectSearcher< Check >::Visit(), Acore::WorldObjectLastSearcher< Check >::Visit(), Acore::WorldObjectWorker< Do >::Visit(), Acore::GameObjectSearcher< Check >::Visit(), Acore::GameObjectLastSearcher< Check >::Visit(), Acore::GameObjectListSearcher< Check >::Visit(), Acore::GameObjectWorker< Functor >::Visit(), ObjectGridCleaner::Visit(), Acore::ObjectUpdater::Visit(), Acore::VisibleChangesNotifier::Visit(), Acore::PlayerRelocationNotifier::Visit(), Acore::CreatureRelocationNotifier::Visit(), WorldObjectChangeAccumulator::Visit(), Acore::MessageDistDeliverer::Visit(), Acore::MessageDistDelivererToHostile::Visit(), Acore::WorldObjectListSearcher< Check >::Visit(), Acore::UnitListSearcher< Check >::Visit(), Acore::PlayerSearcher< Check >::Visit(), Acore::PlayerListSearcher< Check >::Visit(), Acore::PlayerListSearcherWithSharedVision< Check >::Visit(), Acore::PlayerLastSearcher< Check >::Visit(), Acore::PlayerWorker< Do >::Visit(), and Acore::PlayerDistWorker< Do >::Visit().
end()
template<class OBJECT > iterator GridRefMgr< OBJECT >::end () inline
Definition at line 36 of file GridRefMgr.h.
 { return iterator(nullptr); }
Referenced by ResetNotifier::resetNotify(), Map::UnloadAll(), Acore::AIRelocationNotifier::Visit(), Acore::UnitSearcher< Check >::Visit(), Acore::UnitLastSearcher< Check >::Visit(), Acore::CreatureSearcher< Check >::Visit(), Acore::CreatureLastSearcher< Check >::Visit(), Acore::CreatureListSearcher< Check >::Visit(), Acore::CreatureWorker< Do >::Visit(), Acore::VisibleNotifier::Visit(), Acore::WorldObjectSearcher< Check >::Visit(), Acore::WorldObjectLastSearcher< Check >::Visit(), Acore::WorldObjectWorker< Do >::Visit(), Acore::GameObjectSearcher< Check >::Visit(), Acore::GameObjectLastSearcher< Check >::Visit(), Acore::GameObjectListSearcher< Check >::Visit(), Acore::GameObjectWorker< Functor >::Visit(), ObjectGridCleaner::Visit(), Acore::ObjectUpdater::Visit(), Acore::VisibleChangesNotifier::Visit(), Acore::PlayerRelocationNotifier::Visit(), Acore::CreatureRelocationNotifier::Visit(), WorldObjectChangeAccumulator::Visit(), Acore::MessageDistDeliverer::Visit(), Acore::MessageDistDelivererToHostile::Visit(), Acore::WorldObjectListSearcher< Check >::Visit(), Acore::UnitListSearcher< Check >::Visit(), Acore::PlayerSearcher< Check >::Visit(), Acore::PlayerListSearcher< Check >::Visit(), Acore::PlayerListSearcherWithSharedVision< Check >::Visit(), Acore::PlayerLastSearcher< Check >::Visit(), Acore::PlayerWorker< Do >::Visit(), and Acore::PlayerDistWorker< Do >::Visit().
getFirst()
template<class OBJECT > GridReference<OBJECT>* GridRefMgr< OBJECT >::getFirst () inline
Definition at line 32 of file GridRefMgr.h.
 { return (GridReference<OBJECT>*)RefMgr<GridRefMgr<OBJECT>, OBJECT>::getFirst(); }
Referenced by GridRefMgr< OBJECT >::begin(), and ObjectGridUnloader::Visit().
getLast()
template<class OBJECT > GridReference<OBJECT>* GridRefMgr< OBJECT >::getLast () inline
Definition at line 33 of file GridRefMgr.h.
 { return (GridReference<OBJECT>*)RefMgr<GridRefMgr<OBJECT>, OBJECT>::getLast(); }
Referenced by GridRefMgr< OBJECT >::rbegin().
rbegin()
template<class OBJECT > iterator GridRefMgr< OBJECT >::rbegin () inline
Definition at line 37 of file GridRefMgr.h.
 { return iterator(getLast()); }
References GridRefMgr< OBJECT >::getLast().
rend()
template<class OBJECT > iterator GridRefMgr< OBJECT >::rend () inline
Definition at line 38 of file GridRefMgr.h.
 { return iterator(nullptr); }
The documentation for this class was generated from the following files:
src/server/game/Grids/GridReference.h
src/server/game/Grids/GridRefMgr.h