Azerotcore-wotlk: instance_forge_of_souls::instance_forge_of_souls_InstanceScript Struct Reference
instance_forge_of_souls::instance_forge_of_souls_InstanceScript Struct Reference
Public Member Functions
instance_forge_of_souls_InstanceScript (Map *map)
void Initialize () override
bool IsEncounterInProgress () const override
void OnPlayerEnter (Player *) override
void OnCreatureCreate (Creature *creature) override
void HandleOutro ()
void SetData (uint32 type, uint32 data) override
ObjectGuid GetGuidData (uint32 type) const override
bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *, Unit const *, uint32) override
std::string GetSaveData () override
void Load (const char *in) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void CreatureLooted (Creature *, LootType)
void SaveToDB ()
virtual void Update (uint32)
void OnCreatureRemove (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void ProcessEvent (WorldObject *, uint32)
Public Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
TeamId teamIdInInstance
std::string str_data
ObjectGuid NPC_BronjahmGUID
ObjectGuid NPC_DevourerGUID
ObjectGuid NPC_LeaderFirstGUID
ObjectGuid NPC_LeaderSecondGUID
ObjectGuid NPC_GuardFirstGUID
ObjectGuid NPC_GuardSecondGUID
Public Attributes inherited from InstanceScript
Map * instance
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Definition at line 33 of file instance_forge_of_souls.cpp.
Constructor & Destructor Documentation
instance_forge_of_souls_InstanceScript()
instance_forge_of_souls::instance_forge_of_souls_InstanceScript::instance_forge_of_souls_InstanceScript (Map * map) inline
Definition at line 35 of file instance_forge_of_souls.cpp.
 : InstanceScript(map) {}
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_forge_of_souls::instance_forge_of_souls_InstanceScript::CheckAchievementCriteriaMeet (uint32 criteria_id, Player const * , Unit const * , uint32) inline override virtual
Reimplemented from InstanceScript.
Definition at line 170 of file instance_forge_of_souls.cpp.
         {
             switch(criteria_id)
             {
                 case 12752: // Soul Power
                     if( Creature* c = instance->GetCreature(NPC_BronjahmGUID) )
                     {
                         std::list<Creature*> L;
                         uint8 count = 0;
                         c->GetCreaturesWithEntryInRange(L, 200.0f, 36535); // find all Corrupted Soul Fragment (36535)
                         for( std::list<Creature*>::const_iterator itr = L.begin(); itr != L.end(); ++itr )
                             if( (*itr)->IsAlive() )
                                 ++count;
                         return (count >= 4);
                     }
                     break;
                 case 12976:
                     if( Creature* c = instance->GetCreature(NPC_DevourerGUID) )
                         return (bool)c->AI()->GetData(1);
                     break;
             }
             return false;
         }
References mpq::c, count(), Map::GetCreature(), InstanceScript::instance, NPC_BronjahmGUID, and NPC_DevourerGUID.
GetGuidData()
ObjectGuid instance_forge_of_souls::instance_forge_of_souls_InstanceScript::GetGuidData (uint32 type) const inline override virtual
Reimplemented from InstanceScript.
Definition at line 159 of file instance_forge_of_souls.cpp.
         {
             switch (type)
             {
                 case DATA_BRONJAHM:
                     return NPC_BronjahmGUID;
             }
             return ObjectGuid::Empty;
         }
References DATA_BRONJAHM, ObjectGuid::Empty, and NPC_BronjahmGUID.
GetSaveData()
std::string instance_forge_of_souls::instance_forge_of_souls_InstanceScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
Definition at line 194 of file instance_forge_of_souls.cpp.
         {
             OUT_SAVE_INST_DATA;
             std::ostringstream saveStream;
             saveStream << "F S " << m_auiEncounter[0] << ' ' << m_auiEncounter[1];
             str_data = saveStream.str();
             OUT_SAVE_INST_DATA_COMPLETE;
             return str_data;
         }
References m_auiEncounter, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, and str_data.
HandleOutro()
void instance_forge_of_souls::instance_forge_of_souls_InstanceScript::HandleOutro () inline
Definition at line 126 of file instance_forge_of_souls.cpp.
         {
             if (!NPC_LeaderSecondGUID || !instance->GetCreature(NPC_LeaderSecondGUID))
                 if (Creature* leader = instance->SummonCreature(NPC_SYLVANAS_PART2, outroSpawnPoint))
                     if (Creature* boss = instance->GetCreature(NPC_DevourerGUID))
                     {
                         float angle = boss->GetAngle(leader);
                         leader->GetMotionMaster()->MovePoint(1, boss->GetPositionX() + 10.0f * cos(angle), boss->GetPositionY() + 10.0f * sin(angle), boss->GetPositionZ());
                     }
             for (int8 i = 0; outroPositions[i].entry[teamIdInInstance] != 0; ++i)
                 if (Creature* summon = instance->SummonCreature(outroPositions[i].entry[teamIdInInstance], outroPositions[i].startPosition))
                     summon->GetMotionMaster()->MovePath(outroPositions[i].pathId, false);
         }
References outroPosition::entry, Map::GetCreature(), InstanceScript::instance, NPC_DevourerGUID, NPC_LeaderSecondGUID, NPC_SYLVANAS_PART2, outroPositions, outroSpawnPoint, outroPosition::startPosition, Map::SummonCreature(), and teamIdInInstance.
Referenced by SetData().
Initialize()
void instance_forge_of_souls::instance_forge_of_souls_InstanceScript::Initialize (void) inline override virtual
Reimplemented from InstanceScript.
Definition at line 48 of file instance_forge_of_souls.cpp.
         {
             memset(&m_auiEncounter, 0, sizeof(m_auiEncounter));
             teamIdInInstance = TEAM_NEUTRAL;
         }
References m_auiEncounter, memset, TEAM_NEUTRAL, and teamIdInInstance.
IsEncounterInProgress()
bool instance_forge_of_souls::instance_forge_of_souls_InstanceScript::IsEncounterInProgress () const inline override virtual
Reimplemented from InstanceScript.
Definition at line 54 of file instance_forge_of_souls.cpp.
         {
             for (uint8 i = 0; i < MAX_ENCOUNTER; ++i)
                 if (m_auiEncounter[i] == IN_PROGRESS) return true;
             return false;
         }
References IN_PROGRESS, m_auiEncounter, and MAX_ENCOUNTER.
Load()
void instance_forge_of_souls::instance_forge_of_souls_InstanceScript::Load (const char * in) inline override virtual
Reimplemented from InstanceScript.
Definition at line 206 of file instance_forge_of_souls.cpp.
         {
             if (!in)
             {
                 OUT_LOAD_INST_DATA_FAIL;
                 return;
             }
             OUT_LOAD_INST_DATA(in);
             char dataHead1, dataHead2;
             uint32 data0, data1;
             std::istringstream loadStream(in);
             loadStream >> dataHead1 >> dataHead2 >> data0 >> data1;
             if (dataHead1 == 'F' && dataHead2 == 'S')
             {
                 m_auiEncounter[0] = data0;
                 m_auiEncounter[1] = data1;
                 for (uint8 i = 0; i < MAX_ENCOUNTER; ++i)
                     if (m_auiEncounter[i] == IN_PROGRESS)
                         m_auiEncounter[i] = NOT_STARTED;
             }
             else OUT_LOAD_INST_DATA_FAIL;
             OUT_LOAD_INST_DATA_COMPLETE;
         }
References IN_PROGRESS, m_auiEncounter, MAX_ENCOUNTER, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_forge_of_souls::instance_forge_of_souls_InstanceScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 72 of file instance_forge_of_souls.cpp.
         {
             if (teamIdInInstance == TEAM_NEUTRAL)
             {
                 Map::PlayerList const& players = instance->GetPlayers();
                 if (!players.isEmpty())
                     if (Player* player = players.begin()->GetSource())
                         teamIdInInstance = player->GetTeamId();
             }
             switch (creature->GetEntry())
             {
                 case NPC_BRONJAHM:
                     NPC_BronjahmGUID = creature->GetGUID();
                     break;
                 case NPC_DEVOURER:
                     NPC_DevourerGUID = creature->GetGUID();
                     break;
                 case NPC_SYLVANAS_PART1:
                     if (teamIdInInstance == TEAM_ALLIANCE)
                         creature->UpdateEntry(NPC_JAINA_PART1);
                     NPC_LeaderFirstGUID = creature->GetGUID();
                     if (m_auiEncounter[0] == DONE && m_auiEncounter[1] == DONE)
                         creature->SetVisible(false);
                     break;
                 case NPC_SYLVANAS_PART2:
                     if (teamIdInInstance == TEAM_ALLIANCE)
                         creature->UpdateEntry(NPC_JAINA_PART2);
                     NPC_LeaderSecondGUID = creature->GetGUID();
                     break;
                 case NPC_LORALEN:
                     if (teamIdInInstance == TEAM_ALLIANCE)
                         creature->UpdateEntry(NPC_ELANDRA);
                     if (!NPC_GuardFirstGUID)
                     {
                         NPC_GuardFirstGUID = creature->GetGUID();
                         if (m_auiEncounter[0] == DONE && m_auiEncounter[1] == DONE)
                             creature->SetVisible(false);
                     }
                     break;
                 case NPC_KALIRA:
                     if (teamIdInInstance == TEAM_ALLIANCE)
                         creature->UpdateEntry(NPC_KORELN);
                     if (!NPC_GuardSecondGUID)
                     {
                         NPC_GuardSecondGUID = creature->GetGUID();
                         if (m_auiEncounter[0] == DONE && m_auiEncounter[1] == DONE)
                             creature->SetVisible(false);
                     }
                     break;
             }
         }
References MapRefMgr::begin(), DONE, Object::GetEntry(), Object::GetGUID(), Map::GetPlayers(), InstanceScript::instance, LinkedListHead::isEmpty(), m_auiEncounter, NPC_BRONJAHM, NPC_BronjahmGUID, NPC_DEVOURER, NPC_DevourerGUID, NPC_ELANDRA, NPC_GuardFirstGUID, NPC_GuardSecondGUID, NPC_JAINA_PART1, NPC_JAINA_PART2, NPC_KALIRA, NPC_KORELN, NPC_LeaderFirstGUID, NPC_LeaderSecondGUID, NPC_LORALEN, NPC_SYLVANAS_PART1, NPC_SYLVANAS_PART2, Unit::SetVisible(), TEAM_ALLIANCE, TEAM_NEUTRAL, teamIdInInstance, and Creature::UpdateEntry().
OnPlayerEnter()
void instance_forge_of_souls::instance_forge_of_souls_InstanceScript::OnPlayerEnter (Player *) inline override virtual
Reimplemented from InstanceScript.
Definition at line 62 of file instance_forge_of_souls.cpp.
         {
             // this will happen only after crash and loading the instance from db
             if (m_auiEncounter[0] == DONE && m_auiEncounter[1] == DONE && (!NPC_LeaderSecondGUID || !instance->GetCreature(NPC_LeaderSecondGUID)))
             {
                 Position pos = {5658.15f, 2502.564f, 708.83f, 0.885207f};
                 instance->SummonCreature(NPC_SYLVANAS_PART2, pos);
             }
         }
References DONE, Map::GetCreature(), InstanceScript::instance, m_auiEncounter, NPC_LeaderSecondGUID, NPC_SYLVANAS_PART2, pos(), and Map::SummonCreature().
SetData()
void instance_forge_of_souls::instance_forge_of_souls_InstanceScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
Definition at line 141 of file instance_forge_of_souls.cpp.
         {
             switch(type)
             {
                 case DATA_BRONJAHM:
                     m_auiEncounter[type] = data;
                     break;
                 case DATA_DEVOURER:
                     m_auiEncounter[type] = data;
                     if (m_auiEncounter[0] == DONE && m_auiEncounter[1] == DONE)
                         HandleOutro();
                     break;
             }
             if (data == DONE)
                 SaveToDB();
         }
References DATA_BRONJAHM, DATA_DEVOURER, DONE, HandleOutro(), m_auiEncounter, and InstanceScript::SaveToDB().
Member Data Documentation
m_auiEncounter
uint32 instance_forge_of_souls::instance_forge_of_souls_InstanceScript::m_auiEncounter[MAX_ENCOUNTER]
Definition at line 37 of file instance_forge_of_souls.cpp.
Referenced by GetSaveData(), Initialize(), IsEncounterInProgress(), Load(), OnCreatureCreate(), OnPlayerEnter(), and SetData().
NPC_BronjahmGUID
ObjectGuid instance_forge_of_souls::instance_forge_of_souls_InstanceScript::NPC_BronjahmGUID
Definition at line 40 of file instance_forge_of_souls.cpp.
Referenced by CheckAchievementCriteriaMeet(), GetGuidData(), and OnCreatureCreate().
NPC_DevourerGUID
ObjectGuid instance_forge_of_souls::instance_forge_of_souls_InstanceScript::NPC_DevourerGUID
Definition at line 41 of file instance_forge_of_souls.cpp.
Referenced by CheckAchievementCriteriaMeet(), HandleOutro(), and OnCreatureCreate().
NPC_GuardFirstGUID
ObjectGuid instance_forge_of_souls::instance_forge_of_souls_InstanceScript::NPC_GuardFirstGUID
Definition at line 45 of file instance_forge_of_souls.cpp.
Referenced by OnCreatureCreate().
NPC_GuardSecondGUID
ObjectGuid instance_forge_of_souls::instance_forge_of_souls_InstanceScript::NPC_GuardSecondGUID
Definition at line 46 of file instance_forge_of_souls.cpp.
Referenced by OnCreatureCreate().
NPC_LeaderFirstGUID
ObjectGuid instance_forge_of_souls::instance_forge_of_souls_InstanceScript::NPC_LeaderFirstGUID
Definition at line 43 of file instance_forge_of_souls.cpp.
Referenced by OnCreatureCreate().
NPC_LeaderSecondGUID
ObjectGuid instance_forge_of_souls::instance_forge_of_souls_InstanceScript::NPC_LeaderSecondGUID
Definition at line 44 of file instance_forge_of_souls.cpp.
Referenced by HandleOutro(), OnCreatureCreate(), and OnPlayerEnter().
str_data
std::string instance_forge_of_souls::instance_forge_of_souls_InstanceScript::str_data
Definition at line 39 of file instance_forge_of_souls.cpp.
Referenced by GetSaveData().
teamIdInInstance
TeamId instance_forge_of_souls::instance_forge_of_souls_InstanceScript::teamIdInInstance
Definition at line 38 of file instance_forge_of_souls.cpp.
Referenced by HandleOutro(), Initialize(), and OnCreatureCreate().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/FrozenHalls/ForgeOfSouls/instance_forge_of_souls.cpp