Azerotcore-wotlk: AuraApplication Class Reference
AuraApplication Class Reference
#include <SpellAuras.h>
Public Member Functions
Unit * GetTarget () const
Aura * GetBase () const
uint8 GetSlot () const
uint8 GetFlags () const
uint8 GetEffectMask () const
bool HasEffect (uint8 effect) const
bool IsPositive () const
bool IsSelfcasted () const
uint8 GetEffectsToApply () const
void SetRemoveMode (AuraRemoveMode mode)
AuraRemoveMode GetRemoveMode () const
void SetNeedClientUpdate ()
bool IsNeedClientUpdate () const
void BuildUpdatePacket (ByteBuffer &data, bool remove) const
void ClientUpdate (bool remove=false)
bool IsActive (uint8 effIdx)
void SetDisableMask (uint8 effIdx)
void RemoveDisableMask (uint8 effIdx)
Private Member Functions
AuraApplication (Unit *target, Unit *caster, Aura *base, uint8 effMask)
void _Remove ()
void _InitFlags (Unit *caster, uint8 effMask)
void _HandleEffect (uint8 effIndex, bool apply)
Private Attributes
Unit *const _target
Aura *const _base
AuraRemoveMode _removeMode: 8
uint8 _slot
uint8 _flags
uint8 _effectsToApply
bool _needClientUpdate: 1
uint8 _disableMask
Friends
void Unit::_ApplyAura (AuraApplication *aurApp, uint8 effMask)
void Unit::_UnapplyAura (AuraApplicationMap::iterator &i, AuraRemoveMode removeMode)
void Unit::_ApplyAuraEffect (Aura *aura, uint8 effIndex)
void Unit::RemoveAura (AuraApplication *aurApp, AuraRemoveMode mode)
AuraApplication * Unit::_CreateAuraApplication (Aura *aura, uint8 effMask)
Detailed Description
Definition at line 36 of file SpellAuras.h.
Constructor & Destructor Documentation
AuraApplication()
AuraApplication::AuraApplication (Unit * target, Unit * caster, Aura * base, uint8 effMask) explicit private
Definition at line 42 of file SpellAuras.cpp.
                                                                                      :
     _target(target), _base(aura), _removeMode(AURA_REMOVE_NONE), _slot(MAX_AURAS),
     _flags(AFLAG_NONE), _effectsToApply(effMask), _needClientUpdate(false), _disableMask(0)
 {
     ASSERT(GetTarget() && GetBase());
     if (GetBase()->CanBeSentToClient())
     {
         // Try find slot for aura
         uint8 slot = MAX_AURAS;
         // Lookup for auras already applied from spell
         if (AuraApplication* foundAura = GetTarget()->GetAuraApplication(GetBase()->GetId(), GetBase()->GetCasterGUID(), GetBase()->GetCastItemGUID()))
         {
             // allow use single slot only by auras from same caster
             slot = foundAura->GetSlot();
         }
         else
         {
             Unit::VisibleAuraMap const* visibleAuras = GetTarget()->GetVisibleAuras();
             // lookup for free slots in units visibleAuras
             Unit::VisibleAuraMap::const_iterator itr = visibleAuras->find(0);
             for (uint32 freeSlot = 0; freeSlot < MAX_AURAS; ++itr, ++freeSlot)
             {
                 if (itr == visibleAuras->end() || itr->first != freeSlot)
                 {
                     slot = freeSlot;
                     break;
                 }
             }
         }
         // Register Visible Aura
         if (slot < MAX_AURAS)
         {
             _slot = slot;
             GetTarget()->SetVisibleAura(slot, this);
             SetNeedClientUpdate();
             LOG_DEBUG("spells.aura", "Aura: %u Effect: %d put to unit visible auras slot: %u", GetBase()->GetId(), GetEffectMask(), slot);
         }
         else
         {
             LOG_ERROR("spells.aura", "Aura: %u Effect: %d could not find empty unit visible slot", GetBase()->GetId(), GetEffectMask());
         }
     }
     _InitFlags(caster, effMask);
 }
References _InitFlags(), _slot, ASSERT, GetBase(), GetEffectMask(), AccountMgr::GetId(), GetTarget(), Unit::GetVisibleAuras(), LOG_DEBUG, LOG_ERROR, MAX_AURAS, SetNeedClientUpdate(), and Unit::SetVisibleAura().
Member Function Documentation
_HandleEffect()
void AuraApplication::_HandleEffect (uint8 effIndex, bool apply) private
Definition at line 156 of file SpellAuras.cpp.
 {
     AuraEffect* aurEff = GetBase()->GetEffect(effIndex);
     ASSERT(aurEff);
     ASSERT(HasEffect(effIndex) == (!apply));
     ASSERT((1 << effIndex) & _effectsToApply);
     LOG_DEBUG("spells.aura", "AuraApplication::_HandleEffect: %u, apply: %u: amount: %u", aurEff->GetAuraType(), apply, aurEff->GetAmount());
     if (apply)
     {
         ASSERT(!(_flags & (1 << effIndex)));
         _flags |= 1 << effIndex;
         aurEff->HandleEffect(this, AURA_EFFECT_HANDLE_REAL, true);
     }
     else
     {
         ASSERT(_flags & (1 << effIndex));
         _flags &= ~(1 << effIndex);
         aurEff->HandleEffect(this, AURA_EFFECT_HANDLE_REAL, false);
         // Remove all triggered by aura spells vs unlimited duration
         aurEff->CleanupTriggeredSpells(GetTarget());
     }
     // Stacking!
     if (uint32 groupId = aurEff->GetAuraGroup())
     {
         SpellGroupStackFlags sFlag = sSpellMgr->GetGroupStackFlags(groupId);
         if (!aurEff->IsPeriodic() && (sFlag & SPELL_GROUP_STACK_FLAG_EFFECT_EXCLUSIVE))
         {
             AuraApplication* strongestApp = apply ? this : nullptr;
             AuraEffect* strongestEff = apply ? aurEff : nullptr;
             int32 amount = apply ? abs(aurEff->GetAmount()) : 0;
             Unit* target = GetTarget();
             Unit::AuraEffectList const& auraList = target->GetAuraEffectsByType(aurEff->GetAuraType());
             for (Unit::AuraEffectList::const_iterator iter = auraList.begin(); iter != auraList.end(); ++iter)
             {
                 if ((*iter)->GetAuraGroup() != groupId || (*iter) == strongestEff || (*iter)->GetBase()->IsRemoved())
                     continue;
                 // xinef: skip different misc values
                 if (aurEff->GetAuraType() != SPELL_AURA_230 /*SPELL_AURA_MOD_INCREASE_HEALTH_2*/ && aurEff->GetAuraType() != SPELL_AURA_MOD_CASTING_SPEED_NOT_STACK &&
                         aurEff->GetMiscValue() != (*iter)->GetMiscValue())
                     continue;
                 // xinef: should not happen
                 AuraApplication* aurApp = (*iter)->GetBase()->GetApplicationOfTarget(target->GetGUID());
                 if (!aurApp)
                     continue;
                 if (amount < abs((*iter)->GetForcedAmount()))
                 {
                     // xinef: if we have strongest aura and it is active, turn it off
                     // xinef: otherwise just save new aura;
                     if (strongestApp && strongestEff && strongestApp->IsActive(strongestEff->GetEffIndex()))
                     {
                         strongestEff->HandleEffect(strongestApp, AURA_EFFECT_HANDLE_CHANGE_AMOUNT, false);
                         if (!strongestEff->GetSpellInfo()->HasAreaAuraEffect())
                             strongestEff->SetEnabled(false);
                         strongestApp->SetDisableMask(strongestEff->GetEffIndex());
                     }
                     strongestApp = aurApp;
                     strongestEff = (*iter);
                     amount = abs((*iter)->GetAmount());
                 }
                 // xinef: itered aura is weaker, deactivate if active
                 else if (aurApp->IsActive((*iter)->GetEffIndex()))
                 {
                     (*iter)->HandleEffect(aurApp, AURA_EFFECT_HANDLE_CHANGE_AMOUNT, false);
                     if (!(*iter)->GetSpellInfo()->HasAreaAuraEffect())
                         (*iter)->SetEnabled(false);
                     aurApp->SetDisableMask((*iter)->GetEffIndex());
                 }
             }
             // xinef: if we have new strongest aura, and it is not active
             if (strongestApp && strongestEff && !strongestApp->IsActive(strongestEff->GetEffIndex()))
             {
                 strongestApp->RemoveDisableMask(strongestEff->GetEffIndex());
                 strongestEff->SetEnabled(true);
                 strongestEff->HandleEffect(strongestApp, AURA_EFFECT_HANDLE_CHANGE_AMOUNT, true);
             }
         }
     }
     SetNeedClientUpdate();
 }
References _effectsToApply, _flags, ByteConverter::apply(), ASSERT, AURA_EFFECT_HANDLE_CHANGE_AMOUNT, AURA_EFFECT_HANDLE_REAL, AuraEffect::CleanupTriggeredSpells(), AuraEffect::GetAmount(), Aura::GetApplicationOfTarget(), Unit::GetAuraEffectsByType(), AuraEffect::GetAuraGroup(), AuraEffect::GetAuraType(), AuraEffect::GetBase(), GetBase(), Aura::GetEffect(), AuraEffect::GetEffIndex(), Object::GetGUID(), AuraEffect::GetMiscValue(), AuraEffect::GetSpellInfo(), GetTarget(), AuraEffect::HandleEffect(), SpellInfo::HasAreaAuraEffect(), HasEffect(), IsActive(), AuraEffect::IsPeriodic(), Aura::IsRemoved(), LOG_DEBUG, RemoveDisableMask(), SetDisableMask(), AuraEffect::SetEnabled(), SetNeedClientUpdate(), SPELL_AURA_230, SPELL_AURA_MOD_CASTING_SPEED_NOT_STACK, SPELL_GROUP_STACK_FLAG_EFFECT_EXCLUSIVE, and sSpellMgr.
Referenced by Unit::_ApplyAura(), Unit::_ApplyAuraEffect(), Unit::_UnapplyAura(), and Unit::RemoveAura().
_InitFlags()
void AuraApplication::_InitFlags (Unit * caster, uint8 effMask) private
Definition at line 119 of file SpellAuras.cpp.
 {
     // mark as selfcasted if needed
     _flags |= (GetBase()->GetCasterGUID() == GetTarget()->GetGUID()) ? AFLAG_CASTER : AFLAG_NONE;
     // aura is casted by self or an enemy
     // one negative effect and we know aura is negative
     if (IsSelfcasted() || !caster || !caster->IsFriendlyTo(GetTarget()))
     {
         bool negativeFound = false;
         for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
         {
             if (((1 << i) & effMask) && !GetBase()->GetSpellInfo()->IsPositiveEffect(i))
             {
                 negativeFound = true;
                 break;
             }
         }
         _flags |= negativeFound ? AFLAG_NEGATIVE : AFLAG_POSITIVE;
     }
     // aura is casted by friend
     // one positive effect and we know aura is positive
     else
     {
         bool positiveFound = false;
         for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
         {
             if (((1 << i) & effMask) && GetBase()->GetSpellInfo()->IsPositiveEffect(i))
             {
                 positiveFound = true;
                 break;
             }
         }
         _flags |= positiveFound ? AFLAG_POSITIVE : AFLAG_NEGATIVE;
     }
 }
References _flags, AFLAG_CASTER, AFLAG_NEGATIVE, AFLAG_NONE, AFLAG_POSITIVE, GetBase(), Aura::GetCasterGUID(), Object::GetGUID(), Aura::GetSpellInfo(), GetTarget(), Unit::IsFriendlyTo(), SpellInfo::IsPositiveEffect(), IsSelfcasted(), and MAX_SPELL_EFFECTS.
Referenced by AuraApplication().
_Remove()
void AuraApplication::_Remove () private
Definition at line 89 of file SpellAuras.cpp.
 {
     uint8 slot = GetSlot();
     if (slot >= MAX_AURAS)
         return;
     if (AuraApplication* foundAura = _target->GetAuraApplication(GetBase()->GetId(), GetBase()->GetCasterGUID(), GetBase()->GetCastItemGUID()))
     {
         // Reuse visible aura slot by aura which is still applied - prevent storing dead pointers
         if (slot == foundAura->GetSlot())
         {
             if (GetTarget()->GetVisibleAura(slot) == this)
             {
                 GetTarget()->SetVisibleAura(slot, foundAura);
                 foundAura->SetNeedClientUpdate();
             }
             // set not valid slot for aura - prevent removing other visible aura
             slot = MAX_AURAS;
         }
     }
     // update for out of range group members
     if (slot < MAX_AURAS)
     {
         GetTarget()->RemoveVisibleAura(slot);
         ClientUpdate(true);
     }
 }
References _target, ClientUpdate(), Unit::GetAuraApplication(), GetBase(), AccountMgr::GetId(), GetSlot(), GetTarget(), MAX_AURAS, Unit::RemoveVisibleAura(), and Unit::SetVisibleAura().
Referenced by Unit::_UnapplyAura().
BuildUpdatePacket()
void AuraApplication::BuildUpdatePacket (ByteBuffer & data, bool remove) const
Definition at line 243 of file SpellAuras.cpp.
 {
     data << uint8(_slot);
     if (remove)
     {
         ASSERT(!_target->GetVisibleAura(_slot));
         data << uint32(0);
         return;
     }
     ASSERT(_target->GetVisibleAura(_slot));
     Aura const* aura = GetBase();
     data << uint32(aura->GetId());
     uint32 flags = _flags;
     if (aura->GetMaxDuration() > 0 && !aura->GetSpellInfo()->HasAttribute(SPELL_ATTR5_DO_NOT_DISPLAY_DURATION))
         flags |= AFLAG_DURATION;
     data << uint8(flags);
     data << uint8(aura->GetCasterLevel());
     // send stack amount for aura which could be stacked (never 0 - causes incorrect display) or charges
     // stack amount has priority over charges (checked on retail with spell 50262)
     data << uint8(aura->GetSpellInfo()->StackAmount ? aura->GetStackAmount() : aura->GetCharges());
     if (!(flags & AFLAG_CASTER))
         data << aura->GetCasterGUID().WriteAsPacked();
     if (flags & AFLAG_DURATION)
     {
         data << uint32(aura->GetMaxDuration());
         data << uint32(aura->GetDuration());
     }
 }
References _flags, _slot, _target, AFLAG_CASTER, AFLAG_DURATION, ASSERT, GetBase(), Aura::GetCasterGUID(), Aura::GetCasterLevel(), Aura::GetCharges(), Aura::GetDuration(), Aura::GetId(), Aura::GetMaxDuration(), Aura::GetSpellInfo(), Aura::GetStackAmount(), Unit::GetVisibleAura(), SpellInfo::HasAttribute(), SPELL_ATTR5_DO_NOT_DISPLAY_DURATION, SpellInfo::StackAmount, and ObjectGuid::WriteAsPacked().
Referenced by ClientUpdate(), and Player::GetAurasForTarget().
ClientUpdate()
void AuraApplication::ClientUpdate (bool remove = false)
Definition at line 276 of file SpellAuras.cpp.
 {
     _needClientUpdate = false;
     WorldPacket data(SMSG_AURA_UPDATE);
     data << GetTarget()->GetPackGUID();
     BuildUpdatePacket(data, remove);
     if (GetSlot() < MAX_AURAS)
         if (const Player* plr = GetTarget()->ToPlayer())
             if (Aura* aura = GetBase())
                 if (plr->NeedSendSpectatorData() && ArenaSpectator::ShouldSendAura(aura, GetEffectMask(), GetTarget()->GetGUID(), remove))
                     ArenaSpectator::SendCommand_Aura(plr->FindMap(), plr->GetGUID(), "AUR", aura->GetCasterGUID(), aura->GetSpellInfo()->Id, aura->GetSpellInfo()->IsPositive(), aura->GetSpellInfo()->Dispel, aura->GetDuration(), aura->GetMaxDuration(), (aura->GetCharges() > 1 ? aura->GetCharges() : aura->GetStackAmount()), remove);
     _target->SendMessageToSet(&data, true);
 }
References _needClientUpdate, _target, BuildUpdatePacket(), GetBase(), GetEffectMask(), Object::GetPackGUID(), GetSlot(), GetTarget(), MAX_AURAS, ArenaSpectator::SendCommand_Aura(), WorldObject::SendMessageToSet(), ArenaSpectator::ShouldSendAura(), and SMSG_AURA_UPDATE.
Referenced by _Remove().
GetBase()
Aura* AuraApplication::GetBase () const inline
Definition at line 62 of file SpellAuras.h.
 { return _base; }
References _base.
Referenced by Unit::_ApplyAura(), _HandleEffect(), _InitFlags(), Battleground::_ProcessJoin(), _Remove(), Unit::_UnapplyAura(), Aura::_UnapplyForTarget(), AuraApplication(), WorldSession::BuildPartyMemberStatsChangedPacket(), BuildUpdatePacket(), Unit::CalcAbsorbResist(), ClientUpdate(), Unit::GetAura(), Unit::GetAuraApplication(), Unit::GetAuraOfRankedSpell(), Aura::HandleAuraSpecificMods(), SpellInfo::IsStrongerAuraActive(), Unit::RemoveArenaAuras(), Unit::RemoveAura(), and Unit::RestoreDisplayId().
GetEffectMask()
uint8 AuraApplication::GetEffectMask () const inline
Definition at line 66 of file SpellAuras.h.
 { return _flags & (AFLAG_EFF_INDEX_0 | AFLAG_EFF_INDEX_1 | AFLAG_EFF_INDEX_2); }
References _flags, AFLAG_EFF_INDEX_0, AFLAG_EFF_INDEX_1, and AFLAG_EFF_INDEX_2.
Referenced by Unit::_ApplyAuraEffect(), Unit::_UnapplyAura(), AuraApplication(), and ClientUpdate().
GetEffectsToApply()
uint8 AuraApplication::GetEffectsToApply () const inline
Definition at line 70 of file SpellAuras.h.
 { return _effectsToApply; }
References _effectsToApply.
GetFlags()
uint8 AuraApplication::GetFlags () const inline
Definition at line 65 of file SpellAuras.h.
 { return _flags; }
References _flags.
Referenced by WorldSession::BuildPartyMemberStatsChangedPacket().
GetRemoveMode()
AuraRemoveMode AuraApplication::GetRemoveMode () const inline
Definition at line 73 of file SpellAuras.h.
 {return _removeMode;}
References _removeMode.
Referenced by Unit::_ApplyAura(), Unit::_EnterVehicle(), Unit::_UnapplyAura(), Aura::_UnapplyForTarget(), spell_mage_living_bomb::AfterRemove(), AuraEffect::HandleAuraDummy(), AuraEffect::HandleAuraLinked(), AuraEffect::HandleAuraModShapeshift(), Aura::HandleAuraSpecificMods(), AuraEffect::HandleChannelDeathItem(), AuraEffect::HandleEffect(), AuraEffect::HandleFeignDeath(), spell_jedoga_sacrafice_beam::spell_jedoga_sacrafice_beam_AuraScript::HandleRemoval(), spell_warl_curse_of_doom::OnRemove(), Unit::RemoveAura(), and Unit::SetCharmedBy().
GetSlot()
uint8 AuraApplication::GetSlot () const inline
Definition at line 64 of file SpellAuras.h.
 { return _slot; }
References _slot.
Referenced by _Remove(), and ClientUpdate().
GetTarget()
Unit* AuraApplication::GetTarget () const inline
Definition at line 61 of file SpellAuras.h.
 { return _target; }
References _target.
Referenced by Unit::_ApplyAura(), _HandleEffect(), _InitFlags(), _Remove(), Aura::_Remove(), Unit::_UnapplyAura(), AuraApplication(), ClientUpdate(), AuraScript::GetTarget(), AuraEffect::HandleArenaPreparation(), AuraEffect::HandleAuraAllowFlight(), AuraEffect::HandleAuraAllowOnlyAbility(), AuraEffect::HandleAuraCloneCaster(), AuraEffect::HandleAuraControlVehicle(), AuraEffect::HandleAuraConvertRune(), AuraEffect::HandleAuraDummy(), AuraEffect::HandleAuraEmpathy(), AuraEffect::HandleAuraFeatherFall(), AuraEffect::HandleAuraGhost(), AuraEffect::HandleAuraHover(), AuraEffect::HandleAuraIncreaseBaseHealthPercent(), AuraEffect::HandleAuraLinked(), AuraEffect::HandleAuraModAttackPower(), AuraEffect::HandleAuraModAttackPowerOfArmor(), AuraEffect::HandleAuraModAttackPowerPercent(), AuraEffect::HandleAuraModBaseResistancePCT(), AuraEffect::HandleAuraModBlockPercent(), AuraEffect::HandleAuraModCritPct(), AuraEffect::HandleAuraModDecreaseSpeed(), AuraEffect::HandleAuraModDisarm(), AuraEffect::HandleAuraModDispelImmunity(), AuraEffect::HandleAuraModDmgImmunity(), AuraEffect::HandleAuraModDodgePercent(), AuraEffect::HandleAuraModEffectImmunity(), AuraEffect::HandleAuraModExpertise(), AuraEffect::HandleAuraModFaction(), AuraEffect::HandleAuraModFakeInebriation(), AuraEffect::HandleAuraModIncreaseEnergy(), AuraEffect::HandleAuraModIncreaseEnergyPercent(), AuraEffect::HandleAuraModIncreaseFlightSpeed(), AuraEffect::HandleAuraModIncreaseHealth(), AuraEffect::HandleAuraModIncreaseHealthPercent(), AuraEffect::HandleAuraModIncreaseMaxHealth(), AuraEffect::HandleAuraModIncreaseSpeed(), AuraEffect::HandleAuraModIncreaseSwimSpeed(), AuraEffect::HandleAuraModPacify(), AuraEffect::HandleAuraModPacifyAndSilence(), AuraEffect::HandleAuraModParryPercent(), AuraEffect::HandleAuraModPetTalentsPoints(), AuraEffect::HandleAuraModRangedAttackPower(), AuraEffect::HandleAuraModRangedAttackPowerOfStatPercent(), AuraEffect::HandleAuraModRangedAttackPowerPercent(), AuraEffect::HandleAuraModRangedHaste(), AuraEffect::HandleAuraModResistance(), AuraEffect::HandleAuraModResistanceExclusive(), AuraEffect::HandleAuraModResistenceOfStatPercent(), AuraEffect::HandleAuraModRoot(), AuraEffect::HandleAuraModScale(), AuraEffect::HandleAuraModSchoolImmunity(), AuraEffect::HandleAuraModShapeshift(), AuraEffect::HandleAuraModSilence(), AuraEffect::HandleAuraModSkill(), AuraEffect::HandleAuraModStalked(), AuraEffect::HandleAuraModStat(), AuraEffect::HandleAuraModStateImmunity(), AuraEffect::HandleAuraModStun(), AuraEffect::HandleAuraModTotalThreat(), AuraEffect::HandleAuraModUseNormalSpeed(), AuraEffect::HandleAuraModWeaponCritPercent(), AuraEffect::HandleAuraMounted(), AuraEffect::HandleAuraOpenStable(), AuraEffect::HandleAuraOverrideSpells(), AuraEffect::HandleAuraRetainComboPoints(), AuraEffect::HandleAuraSetVehicle(), Aura::HandleAuraSpecificMods(), AuraEffect::HandleAuraTrackCreatures(), AuraEffect::HandleAuraTrackResources(), AuraEffect::HandleAuraTrackStealthed(), AuraEffect::HandleAuraTransform(), AuraEffect::HandleAuraUntrackable(), AuraEffect::HandleAuraWaterWalk(), AuraEffect::HandleBindSight(), AuraEffect::HandleCharmConvert(), AuraEffect::HandleComprehendLanguage(), AuraEffect::HandleDetectAmore(), AuraEffect::HandleEffect(), AuraEffect::HandleFeignDeath(), AuraEffect::HandleForceMoveForward(), AuraEffect::HandleForceReaction(), AuraEffect::HandleModAttackSpeed(), AuraEffect::HandleModBaseResistance(), AuraEffect::HandleModCastingSpeed(), AuraEffect::HandleModCharm(), AuraEffect::HandleModCombatSpeedPct(), AuraEffect::HandleModConfuse(), AuraEffect::HandleModDamageDone(), AuraEffect::HandleModDamagePercentDone(), AuraEffect::HandleModFear(), AuraEffect::HandleModHealingDone(), AuraEffect::HandleModHitChance(), AuraEffect::HandleModInvisibility(), AuraEffect::HandleModInvisibilityDetect(), AuraEffect::HandleModManaRegen(), AuraEffect::HandleModMechanicImmunity(), AuraEffect::HandleModMeleeRangedSpeedPct(), AuraEffect::HandleModMeleeSpeedPct(), AuraEffect::HandleModOffhandDamagePercent(), AuraEffect::HandleModPercentStat(), AuraEffect::HandleModPossess(), AuraEffect::HandleModPossessPet(), AuraEffect::HandleModPowerCost(), AuraEffect::HandleModPowerCostPCT(), AuraEffect::HandleModPowerRegen(), AuraEffect::HandleModRating(), AuraEffect::HandleModRatingFromStat(), AuraEffect::HandleModResistancePercent(), AuraEffect::HandleModSpellCritChance(), AuraEffect::HandleModSpellCritChanceShool(), AuraEffect::HandleModSpellDamagePercentFromAttackPower(), AuraEffect::HandleModSpellDamagePercentFromStat(), AuraEffect::HandleModSpellHealingPercentFromAttackPower(), AuraEffect::HandleModSpellHealingPercentFromStat(), AuraEffect::HandleModSpellHitChance(), AuraEffect::HandleModStateImmunityMask(), AuraEffect::HandleModStealth(), AuraEffect::HandleModStealthDetect(), AuraEffect::HandleModStealthLevel(), AuraEffect::HandleModTargetResistance(), AuraEffect::HandleModTaunt(), AuraEffect::HandleModThreat(), AuraEffect::HandleModTotalPercentStat(), AuraEffect::HandleModUnattackable(), AuraEffect::HandleNoReagentUseAura(), AuraEffect::HandlePhase(), AuraEffect::HandlePreventFleeing(), AuraEffect::HandlePreventResurrection(), AuraEffect::HandleProcTriggerDamageAuraProc(), AuraEffect::HandleProcTriggerSpellAuraProc(), AuraEffect::HandleProcTriggerSpellWithValueAuraProc(), AuraEffect::HandleRaidProcFromChargeAuraProc(), AuraEffect::HandleRaidProcFromChargeWithValueAuraProc(), AuraEffect::HandleRangedAmmoHaste(), AuraEffect::HandleShieldBlockValue(), AuraEffect::HandleSpiritOfRedemption(), AuraEffect::HandleWaterBreathing(), Aura::IsProcTriggeredOnEvent(), AuraEffect::PeriodicTick(), and Unit::RemoveAreaAurasDueToLeaveWorld().
HasEffect()
bool AuraApplication::HasEffect (uint8 effect) const inline
Definition at line 67 of file SpellAuras.h.
 { ASSERT(effect < MAX_SPELL_EFFECTS);  return _flags & (1 << effect); }
References _flags, ASSERT, and MAX_SPELL_EFFECTS.
Referenced by _HandleEffect(), Unit::_UnapplyAura(), Unit::RemoveAura(), and Aura::TriggerProcOnEvent().
IsActive()
bool AuraApplication::IsActive (uint8 effIdx) inline
Definition at line 81 of file SpellAuras.h.
 { return ((1 << effIdx) & _disableMask) == 0; }
References _disableMask.
Referenced by _HandleEffect(), AuraEffect::HandleEffect(), and SpellInfo::IsStrongerAuraActive().
IsNeedClientUpdate()
bool AuraApplication::IsNeedClientUpdate () const inline
Definition at line 76 of file SpellAuras.h.
 { return _needClientUpdate;}
References _needClientUpdate.
IsPositive()
bool AuraApplication::IsPositive () const inline
Definition at line 68 of file SpellAuras.h.
 { return _flags & AFLAG_POSITIVE; }
References _flags, and AFLAG_POSITIVE.
Referenced by Battleground::_ProcessJoin(), Spell::EffectStealBeneficialBuff(), AuraEffect::HandleAuraModResistanceExclusive(), Unit::RemoveArenaAuras(), and Unit::RemoveAurasByType().
IsSelfcasted()
bool AuraApplication::IsSelfcasted () const inline
Definition at line 69 of file SpellAuras.h.
 { return _flags & AFLAG_CASTER; }
References _flags, and AFLAG_CASTER.
Referenced by _InitFlags().
RemoveDisableMask()
void AuraApplication::RemoveDisableMask (uint8 effIdx) inline
Definition at line 83 of file SpellAuras.h.
 { _disableMask &= ~(1 << effIdx); }
References _disableMask.
Referenced by _HandleEffect().
SetDisableMask()
void AuraApplication::SetDisableMask (uint8 effIdx) inline
Definition at line 82 of file SpellAuras.h.
 { _disableMask |= 1 << effIdx; }
References _disableMask.
Referenced by _HandleEffect().
SetNeedClientUpdate()
void AuraApplication::SetNeedClientUpdate () inline
Definition at line 75 of file SpellAuras.h.
 { _needClientUpdate = true;}
References _needClientUpdate.
Referenced by _HandleEffect(), and AuraApplication().
SetRemoveMode()
void AuraApplication::SetRemoveMode (AuraRemoveMode mode) inline
Definition at line 72 of file SpellAuras.h.
 { _removeMode = mode; }
References _removeMode.
Referenced by Unit::_UnapplyAura().
Friends And Related Function Documentation
Unit::_ApplyAura
void Unit::_ApplyAura (AuraApplication * aurApp, uint8 effMask) friend
Unit::_ApplyAuraEffect
void Unit::_ApplyAuraEffect (Aura * aura, uint8 effIndex) friend
Unit::_CreateAuraApplication
AuraApplication* Unit::_CreateAuraApplication (Aura * aura, uint8 effMask) friend
Unit::_UnapplyAura
void Unit::_UnapplyAura (AuraApplicationMap::iterator & i, AuraRemoveMode removeMode) friend
Unit::RemoveAura
void Unit::RemoveAura (AuraApplication * aurApp, AuraRemoveMode mode) friend
Member Data Documentation
_base
Aura* const AuraApplication::_base private
Definition at line 45 of file SpellAuras.h.
Referenced by GetBase().
_disableMask
uint8 AuraApplication::_disableMask private
Definition at line 53 of file SpellAuras.h.
Referenced by IsActive(), RemoveDisableMask(), and SetDisableMask().
_effectsToApply
uint8 AuraApplication::_effectsToApply private
Definition at line 49 of file SpellAuras.h.
Referenced by _HandleEffect(), and GetEffectsToApply().
_flags
uint8 AuraApplication::_flags private
Definition at line 48 of file SpellAuras.h.
Referenced by _HandleEffect(), _InitFlags(), BuildUpdatePacket(), GetEffectMask(), GetFlags(), HasEffect(), IsPositive(), and IsSelfcasted().
_needClientUpdate
bool AuraApplication::_needClientUpdate private
Definition at line 50 of file SpellAuras.h.
Referenced by ClientUpdate(), IsNeedClientUpdate(), and SetNeedClientUpdate().
_removeMode
AuraRemoveMode AuraApplication::_removeMode private
Definition at line 46 of file SpellAuras.h.
Referenced by GetRemoveMode(), and SetRemoveMode().
_slot
uint8 AuraApplication::_slot private
Definition at line 47 of file SpellAuras.h.
Referenced by AuraApplication(), BuildUpdatePacket(), and GetSlot().
_target
Unit* const AuraApplication::_target private
Definition at line 44 of file SpellAuras.h.
Referenced by _Remove(), BuildUpdatePacket(), ClientUpdate(), and GetTarget().
The documentation for this class was generated from the following files:
src/server/game/Spells/Auras/SpellAuras.h
src/server/game/Spells/Auras/SpellAuras.cpp