Azerotcore-wotlk: go_crystal_prison Class Reference
go_crystal_prison Class Reference
Public Member Functions
go_crystal_prison ()
bool OnQuestAccept (Player *player, GameObject *, Quest const *quest) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipHello (Player *, GameObject *)
virtual bool OnGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Definition at line 1576 of file zone_shadowmoon_valley.cpp.
Constructor & Destructor Documentation
go_crystal_prison()
go_crystal_prison::go_crystal_prison () inline
Definition at line 1579 of file zone_shadowmoon_valley.cpp.
 : GameObjectScript("go_crystal_prison") { }
Member Function Documentation
OnQuestAccept()
bool go_crystal_prison::OnQuestAccept (Player * player, GameObject * , Quest const * quest) inline override virtual
Reimplemented from GameObjectScript.
Definition at line 1581 of file zone_shadowmoon_valley.cpp.
     {
         if (quest->GetQuestId() == QUEST_BATTLE_OF_THE_CRIMSON_WATCH)
         {
             Creature* Illidan = player->FindNearestCreature(22083, 50);
             if (Illidan && !CAST_AI(npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI, Illidan->AI())->EventStarted)
             {
                 CAST_AI(npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI, Illidan->AI())->PlayerGUID = player->GetGUID();
                 CAST_AI(npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI, Illidan->AI())->LiveCount = 0;
                 CAST_AI(npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI, Illidan->AI())->EventStarted = true;
             }
         }
         return true;
     }
References Creature::AI(), CAST_AI, WorldObject::FindNearestCreature(), Object::GetGUID(), Quest::GetQuestId(), and QUEST_BATTLE_OF_THE_CRIMSON_WATCH.
The documentation for this class was generated from the following file:
src/server/scripts/Outland/zone_shadowmoon_valley.cpp