Azerotcore-wotlk: deps/jemalloc/src/extent.c File Reference
extent.c File Reference
#include "jemalloc/internal/jemalloc_preamble.h"
#include "jemalloc/internal/jemalloc_internal_includes.h"
#include "jemalloc/internal/assert.h"
#include "jemalloc/internal/extent_dss.h"
#include "jemalloc/internal/extent_mmap.h"
#include "jemalloc/internal/ph.h"
#include "jemalloc/internal/rtree.h"
#include "jemalloc/internal/mutex.h"
#include "jemalloc/internal/mutex_pool.h"
Macros
#define JEMALLOC_EXTENT_C_
#define ATTR_NONE /* does nothing */
Enumerations
enum extent_split_interior_result_t { extent_split_interior_ok , extent_split_interior_cant_alloc , extent_split_interior_error }
Functions
static void * extent_alloc_default (extent_hooks_t *extent_hooks, void *new_addr, size_t size, size_t alignment, bool *zero, bool *commit, unsigned arena_ind)
static bool extent_dalloc_default (extent_hooks_t *extent_hooks, void *addr, size_t size, bool committed, unsigned arena_ind)
static void extent_destroy_default (extent_hooks_t *extent_hooks, void *addr, size_t size, bool committed, unsigned arena_ind)
static bool extent_commit_default (extent_hooks_t *extent_hooks, void *addr, size_t size, size_t offset, size_t length, unsigned arena_ind)
static bool extent_commit_impl (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extent_t *extent, size_t offset, size_t length, bool growing_retained)
static bool extent_decommit_default (extent_hooks_t *extent_hooks, void *addr, size_t size, size_t offset, size_t length, unsigned arena_ind)
static bool extent_purge_lazy_impl (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extent_t *extent, size_t offset, size_t length, bool growing_retained)
static bool extent_purge_forced_impl (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extent_t *extent, size_t offset, size_t length, bool growing_retained)
static bool extent_split_default (extent_hooks_t *extent_hooks, void *addr, size_t size, size_t size_a, size_t size_b, bool committed, unsigned arena_ind)
static extent_t * extent_split_impl (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extent_t *extent, size_t size_a, szind_t szind_a, bool slab_a, size_t size_b, szind_t szind_b, bool slab_b, bool growing_retained)
static bool extent_merge_default (extent_hooks_t *extent_hooks, void *addr_a, size_t size_a, void *addr_b, size_t size_b, bool committed, unsigned arena_ind)
static bool extent_merge_impl (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extent_t *a, extent_t *b, bool growing_retained)
static void extent_deregister (tsdn_t *tsdn, extent_t *extent)
static extent_t * extent_recycle (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extents_t *extents, void *new_addr, size_t usize, size_t pad, size_t alignment, bool slab, szind_t szind, bool *zero, bool *commit, bool growing_retained)
static extent_t * extent_try_coalesce (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, rtree_ctx_t *rtree_ctx, extents_t *extents, extent_t *extent, bool *coalesced, bool growing_retained)
static void extent_record (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extents_t *extents, extent_t *extent, bool growing_retained)
ph_gen (ATTR_NONE, extent_avail_, extent_tree_t, extent_t, ph_link, extent_esnead_comp)
static lock_result_t extent_rtree_leaf_elm_try_lock (tsdn_t *tsdn, rtree_leaf_elm_t *elm, extent_t **result, bool inactive_only)
static extent_t * extent_lock_from_addr (tsdn_t *tsdn, rtree_ctx_t *rtree_ctx, void *addr, bool inactive_only)
extent_t * extent_alloc (tsdn_t *tsdn, arena_t *arena)
void extent_dalloc (tsdn_t *tsdn, arena_t *arena, extent_t *extent)
extent_hooks_t * extent_hooks_get (arena_t *arena)
extent_hooks_t * extent_hooks_set (tsd_t *tsd, arena_t *arena, extent_hooks_t *extent_hooks)
static void extent_hooks_assure_initialized (arena_t *arena, extent_hooks_t **r_extent_hooks)
static size_t extent_size_quantize_floor (size_t size)
static size_t extent_size_quantize_ceil (size_t size)
ph_gen (extent_heap_, extent_heap_t, extent_t, ph_link, extent_snad_comp)
extent_state_t extents_state_get (const extents_t *extents)
size_t extents_npages_get (extents_t *extents)
size_t extents_nextents_get (extents_t *extents, pszind_t pind)
size_t extents_nbytes_get (extents_t *extents, pszind_t pind)
static void extents_stats_add (extents_t *extent, pszind_t pind, size_t sz)
static void extents_stats_sub (extents_t *extent, pszind_t pind, size_t sz)
static void extents_insert_locked (tsdn_t *tsdn, extents_t *extents, extent_t *extent)
static void extents_remove_locked (tsdn_t *tsdn, extents_t *extents, extent_t *extent)
static extent_t * extents_fit_alignment (extents_t *extents, size_t min_size, size_t max_size, size_t alignment)
static extent_t * extents_first_fit_locked (tsdn_t *tsdn, arena_t *arena, extents_t *extents, size_t size)
static extent_t * extents_fit_locked (tsdn_t *tsdn, arena_t *arena, extents_t *extents, size_t esize, size_t alignment)
static bool extent_try_delayed_coalesce (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, rtree_ctx_t *rtree_ctx, extents_t *extents, extent_t *extent)
extent_t * extents_alloc (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extents_t *extents, void *new_addr, size_t size, size_t pad, size_t alignment, bool slab, szind_t szind, bool *zero, bool *commit)
void extents_dalloc (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extents_t *extents, extent_t *extent)
extent_t * extents_evict (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extents_t *extents, size_t npages_min)
static void extents_abandon_vm (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extents_t *extents, extent_t *extent, bool growing_retained)
void extents_prefork (tsdn_t *tsdn, extents_t *extents)
void extents_postfork_parent (tsdn_t *tsdn, extents_t *extents)
void extents_postfork_child (tsdn_t *tsdn, extents_t *extents)
static void extent_deactivate_locked (tsdn_t *tsdn, arena_t *arena, extents_t *extents, extent_t *extent)
static void extent_deactivate (tsdn_t *tsdn, arena_t *arena, extents_t *extents, extent_t *extent)
static void extent_activate_locked (tsdn_t *tsdn, arena_t *arena, extents_t *extents, extent_t *extent)
static bool extent_rtree_leaf_elms_lookup (tsdn_t *tsdn, rtree_ctx_t *rtree_ctx, const extent_t *extent, bool dependent, bool init_missing, rtree_leaf_elm_t **r_elm_a, rtree_leaf_elm_t **r_elm_b)
static void extent_rtree_write_acquired (tsdn_t *tsdn, rtree_leaf_elm_t *elm_a, rtree_leaf_elm_t *elm_b, extent_t *extent, szind_t szind, bool slab)
static void extent_interior_register (tsdn_t *tsdn, rtree_ctx_t *rtree_ctx, extent_t *extent, szind_t szind)
static void extent_gdump_add (tsdn_t *tsdn, const extent_t *extent)
static void extent_gdump_sub (tsdn_t *tsdn, const extent_t *extent)
static bool extent_register_impl (tsdn_t *tsdn, extent_t *extent, bool gdump_add)
static bool extent_register (tsdn_t *tsdn, extent_t *extent)
static bool extent_register_no_gdump_add (tsdn_t *tsdn, extent_t *extent)
static void extent_reregister (tsdn_t *tsdn, extent_t *extent)
static void extent_interior_deregister (tsdn_t *tsdn, rtree_ctx_t *rtree_ctx, extent_t *extent)
static void extent_deregister_impl (tsdn_t *tsdn, extent_t *extent, bool gdump)
static void extent_deregister_no_gdump_sub (tsdn_t *tsdn, extent_t *extent)
static extent_t * extent_recycle_extract (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, rtree_ctx_t *rtree_ctx, extents_t *extents, void *new_addr, size_t size, size_t pad, size_t alignment, bool slab, bool growing_retained)
static extent_split_interior_result_t extent_split_interior (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, rtree_ctx_t *rtree_ctx, extent_t **extent, extent_t **lead, extent_t **trail, extent_t **to_leak, extent_t **to_salvage, void *new_addr, size_t size, size_t pad, size_t alignment, bool slab, szind_t szind, bool growing_retained)
static extent_t * extent_recycle_split (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, rtree_ctx_t *rtree_ctx, extents_t *extents, void *new_addr, size_t size, size_t pad, size_t alignment, bool slab, szind_t szind, extent_t *extent, bool growing_retained)
static bool extent_need_manual_zero (arena_t *arena)
static void * extent_alloc_core (tsdn_t *tsdn, arena_t *arena, void *new_addr, size_t size, size_t alignment, bool *zero, bool *commit, dss_prec_t dss_prec)
static void * extent_alloc_default_impl (tsdn_t *tsdn, arena_t *arena, void *new_addr, size_t size, size_t alignment, bool *zero, bool *commit)
static void extent_hook_pre_reentrancy (tsdn_t *tsdn, arena_t *arena)
static void extent_hook_post_reentrancy (tsdn_t *tsdn)
static extent_t * extent_grow_retained (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, size_t size, size_t pad, size_t alignment, bool slab, szind_t szind, bool *zero, bool *commit)
static extent_t * extent_alloc_retained (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, void *new_addr, size_t size, size_t pad, size_t alignment, bool slab, szind_t szind, bool *zero, bool *commit)
static extent_t * extent_alloc_wrapper_hard (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, void *new_addr, size_t size, size_t pad, size_t alignment, bool slab, szind_t szind, bool *zero, bool *commit)
extent_t * extent_alloc_wrapper (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, void *new_addr, size_t size, size_t pad, size_t alignment, bool slab, szind_t szind, bool *zero, bool *commit)
static bool extent_can_coalesce (arena_t *arena, extents_t *extents, const extent_t *inner, const extent_t *outer)
static bool extent_coalesce (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extents_t *extents, extent_t *inner, extent_t *outer, bool forward, bool growing_retained)
static extent_t * extent_try_coalesce_impl (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, rtree_ctx_t *rtree_ctx, extents_t *extents, extent_t *extent, bool *coalesced, bool growing_retained, bool inactive_only)
static extent_t * extent_try_coalesce_large (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, rtree_ctx_t *rtree_ctx, extents_t *extents, extent_t *extent, bool *coalesced, bool growing_retained)
void extent_dalloc_gap (tsdn_t *tsdn, arena_t *arena, extent_t *extent)
static bool extent_may_dalloc (void)
static bool extent_dalloc_default_impl (void *addr, size_t size)
static bool extent_dalloc_wrapper_try (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extent_t *extent)
void extent_dalloc_wrapper (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extent_t *extent)
static void extent_destroy_default_impl (void *addr, size_t size)
void extent_destroy_wrapper (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extent_t *extent)
bool extent_commit_wrapper (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extent_t *extent, size_t offset, size_t length)
bool extent_decommit_wrapper (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extent_t *extent, size_t offset, size_t length)
bool extent_purge_lazy_wrapper (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extent_t *extent, size_t offset, size_t length)
bool extent_purge_forced_wrapper (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extent_t *extent, size_t offset, size_t length)
extent_t * extent_split_wrapper (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extent_t *extent, size_t size_a, szind_t szind_a, bool slab_a, size_t size_b, szind_t szind_b, bool slab_b)
static bool extent_merge_default_impl (void *addr_a, void *addr_b)
static bool extent_head_no_merge (extent_t *a, extent_t *b)
bool extent_merge_wrapper (tsdn_t *tsdn, arena_t *arena, extent_hooks_t **r_extent_hooks, extent_t *a, extent_t *b)
bool extent_boot (void)
void extent_util_stats_get (tsdn_t *tsdn, const void *ptr, size_t *nfree, size_t *nregs, size_t *size)
void extent_util_stats_verbose_get (tsdn_t *tsdn, const void *ptr, size_t *nfree, size_t *nregs, size_t *size, size_t *bin_nfree, size_t *bin_nregs, void **slabcur_addr)
Variables
rtree_t extents_rtree
mutex_pool_t extent_mutex_pool
size_t opt_lg_extent_max_active_fit = LG_EXTENT_MAX_ACTIVE_FIT_DEFAULT
static const bitmap_info_t extents_bitmap_info
const extent_hooks_t extent_hooks_default
static atomic_zu_t curpages
static atomic_zu_t highpages
lock_result_t
Macro Definition Documentation
ATTR_NONE
#define ATTR_NONE /* does nothing */
Definition at line 116 of file extent.c.
JEMALLOC_EXTENT_C_
#define JEMALLOC_EXTENT_C_
Definition at line 1 of file extent.c.
Enumeration Type Documentation
extent_split_interior_result_t
enum extent_split_interior_result_t
Enumerator
extent_split_interior_ok
extent_split_interior_cant_alloc
extent_split_interior_error
Definition at line 960 of file extent.c.
              {
     /*
      * Split successfully.  lead, extent, and trail, are modified to extents
      * describing the ranges before, in, and after the given allocation.
      */
     extent_split_interior_ok,
     /*
      * The extent can't satisfy the given allocation request.  None of the
      * input extent_t *s are touched.
      */
     extent_split_interior_cant_alloc,
     /*
      * In a potentially invalid state.  Must leak (if *to_leak is non-NULL),
      * and salvage what's still salvageable (if *to_salvage is non-NULL).
      * None of lead, extent, or trail are valid.
      */
     extent_split_interior_error
 } extent_split_interior_result_t;
Function Documentation
extent_activate_locked()
static void extent_activate_locked (tsdn_t * tsdn, arena_t * arena, extents_t * extents, extent_t * extent) static
Definition at line 690 of file extent.c.
                       {
     assert(extent_arena_get(extent) == arena);
     assert(extent_state_get(extent) == extents_state_get(extents));
     extents_remove_locked(tsdn, extents, extent);
     extent_state_set(extent, extent_state_active);
 }
References arena, assert(), extent_arena_get(), extent_state_active, extent_state_get(), extent_state_set(), extents_remove_locked(), and extents_state_get().
Referenced by extent_coalesce(), and extent_recycle_extract().
extent_alloc()
extent_t* extent_alloc (tsdn_t * tsdn, arena_t * arena)
Definition at line 180 of file extent.c.
{
     malloc_mutex_lock(tsdn, &arena->extent_avail_mtx);
     extent_t *extent = extent_avail_first(&arena->extent_avail);
     if (extent == NULL) {
         malloc_mutex_unlock(tsdn, &arena->extent_avail_mtx);
         return base_alloc_extent(tsdn, arena->base);
     }
     extent_avail_remove(&arena->extent_avail, extent);
     atomic_fetch_sub_zu(&arena->extent_avail_cnt, 1, ATOMIC_RELAXED);
     malloc_mutex_unlock(tsdn, &arena->extent_avail_mtx);
     return extent;
 }
References arena, ATOMIC_RELAXED, arena_s::base, base_alloc_extent, arena_s::extent_avail, arena_s::extent_avail_cnt, extent_avail_first, arena_s::extent_avail_mtx, extent_avail_remove, malloc_mutex_lock(), malloc_mutex_unlock(), and NULL.
Referenced by extent_alloc_wrapper_hard(), extent_grow_retained(), and extent_split_impl().
extent_alloc_core()
static void* extent_alloc_core (tsdn_t * tsdn, arena_t * arena, void * new_addr, size_t size, size_t alignment, bool * zero, bool * commit, dss_prec_t dss_prec) static
Definition at line 1209 of file extent.c.
{
     void *ret;
     assert(size != 0);
     assert(alignment != 0);
     /* "primary" dss. */
     if (have_dss && dss_prec == dss_prec_primary && (ret =
         extent_alloc_dss(tsdn, arena, new_addr, size, alignment, zero,
         commit)) != NULL) {
         return ret;
     }
     /* mmap. */
     if ((ret = extent_alloc_mmap(new_addr, size, alignment, zero, commit))
         != NULL) {
         return ret;
     }
     /* "secondary" dss. */
     if (have_dss && dss_prec == dss_prec_secondary && (ret =
         extent_alloc_dss(tsdn, arena, new_addr, size, alignment, zero,
         commit)) != NULL) {
         return ret;
     }
     /* All strategies for allocation failed. */
     return NULL;
 }
References arena, assert(), dss_prec_primary, dss_prec_secondary, extent_alloc_dss, extent_alloc_mmap, have_dss, NULL, ret, and G3D::zero().
Referenced by extent_alloc_default_impl().
extent_alloc_default()
static void * extent_alloc_default (extent_hooks_t * extent_hooks, void * new_addr, size_t size, size_t alignment, bool * zero, bool * commit, unsigned arena_ind) static
Definition at line 1251 of file extent.c.
{
     tsdn_t *tsdn;
     arena_t *arena;
     tsdn = tsdn_fetch();
     arena = arena_get(tsdn, arena_ind, false);
     /*
      * The arena we're allocating on behalf of must have been initialized
      * already.
      */
     assert(arena != NULL);
     return extent_alloc_default_impl(tsdn, arena, new_addr, size,
         ALIGNMENT_CEILING(alignment, PAGE), zero, commit);
 }
References ALIGNMENT_CEILING, arena, arena_get(), assert(), extent_alloc_default_impl(), NULL, PAGE, tsdn_fetch(), and G3D::zero().
extent_alloc_default_impl()
static void* extent_alloc_default_impl (tsdn_t * tsdn, arena_t * arena, void * new_addr, size_t size, size_t alignment, bool * zero, bool * commit) static
Definition at line 1239 of file extent.c.
{
     void *ret = extent_alloc_core(tsdn, arena, new_addr, size, alignment, zero,
         commit, (dss_prec_t)atomic_load_u(&arena->dss_prec,
         ATOMIC_RELAXED));
     if (have_madvise_huge && ret) {
         pages_set_thp_state(ret, size);
     }
     return ret;
 }
References arena, ATOMIC_RELAXED, arena_s::dss_prec, extent_alloc_core(), have_madvise_huge, pages_set_thp_state, ret, and G3D::zero().
Referenced by extent_alloc_default(), extent_alloc_wrapper_hard(), and extent_grow_retained().
extent_alloc_retained()
static extent_t* extent_alloc_retained (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, void * new_addr, size_t size, size_t pad, size_t alignment, bool slab, szind_t szind, bool * zero, bool * commit) static
Definition at line 1463 of file extent.c.
{
     assert(size != 0);
     assert(alignment != 0);
     malloc_mutex_lock(tsdn, &arena->extent_grow_mtx);
     extent_t *extent = extent_recycle(tsdn, arena, r_extent_hooks,
         &arena->extents_retained, new_addr, size, pad, alignment, slab,
         szind, zero, commit, true);
     if (extent != NULL) {
         malloc_mutex_unlock(tsdn, &arena->extent_grow_mtx);
         if (config_prof) {
             extent_gdump_add(tsdn, extent);
         }
     } else if (opt_retain && new_addr == NULL) {
         extent = extent_grow_retained(tsdn, arena, r_extent_hooks, size,
             pad, alignment, slab, szind, zero, commit);
         /* extent_grow_retained() always releases extent_grow_mtx. */
     } else {
         malloc_mutex_unlock(tsdn, &arena->extent_grow_mtx);
     }
     malloc_mutex_assert_not_owner(tsdn, &arena->extent_grow_mtx);
     return extent;
 }
References arena, assert(), config_prof, extent_gdump_add(), arena_s::extent_grow_mtx, extent_grow_retained(), extent_recycle(), arena_s::extents_retained, malloc_mutex_assert_not_owner(), malloc_mutex_lock(), malloc_mutex_unlock(), NULL, opt_retain, and G3D::zero().
Referenced by extent_alloc_wrapper().
extent_alloc_wrapper()
extent_t* extent_alloc_wrapper (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, void * new_addr, size_t size, size_t pad, size_t alignment, bool slab, szind_t szind, bool * zero, bool * commit)
Definition at line 1531 of file extent.c.
{
     witness_assert_depth_to_rank(tsdn_witness_tsdp_get(tsdn),
         WITNESS_RANK_CORE, 0);
     extent_hooks_assure_initialized(arena, r_extent_hooks);
     extent_t *extent = extent_alloc_retained(tsdn, arena, r_extent_hooks,
         new_addr, size, pad, alignment, slab, szind, zero, commit);
     if (extent == NULL) {
         if (opt_retain && new_addr != NULL) {
             /*
              * When retain is enabled and new_addr is set, we do not
              * attempt extent_alloc_wrapper_hard which does mmap
              * that is very unlikely to succeed (unless it happens
              * to be at the end).
              */
             return NULL;
         }
         extent = extent_alloc_wrapper_hard(tsdn, arena, r_extent_hooks,
             new_addr, size, pad, alignment, slab, szind, zero, commit);
     }
     assert(extent == NULL || extent_dumpable_get(extent));
     return extent;
 }
References arena, assert(), extent_alloc_retained(), extent_alloc_wrapper_hard(), extent_dumpable_get(), extent_hooks_assure_initialized(), NULL, opt_retain, witness_assert_depth_to_rank(), WITNESS_RANK_CORE, and G3D::zero().
extent_alloc_wrapper_hard()
static extent_t* extent_alloc_wrapper_hard (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, void * new_addr, size_t size, size_t pad, size_t alignment, bool slab, szind_t szind, bool * zero, bool * commit) static
Definition at line 1492 of file extent.c.
{
     size_t esize = size + pad;
     extent_t *extent = extent_alloc(tsdn, arena);
     if (extent == NULL) {
         return NULL;
     }
     void *addr;
     size_t palignment = ALIGNMENT_CEILING(alignment, PAGE);
     if (*r_extent_hooks == &extent_hooks_default) {
         /* Call directly to propagate tsdn. */
         addr = extent_alloc_default_impl(tsdn, arena, new_addr, esize,
             palignment, zero, commit);
     } else {
         extent_hook_pre_reentrancy(tsdn, arena);
         addr = (*r_extent_hooks)->alloc(*r_extent_hooks, new_addr,
             esize, palignment, zero, commit, arena_ind_get(arena));
         extent_hook_post_reentrancy(tsdn);
     }
     if (addr == NULL) {
         extent_dalloc(tsdn, arena, extent);
         return NULL;
     }
     extent_init(extent, arena, addr, esize, slab, szind,
         arena_extent_sn_next(arena), extent_state_active, *zero, *commit,
         true, EXTENT_NOT_HEAD);
     if (pad != 0) {
         extent_addr_randomize(tsdn, extent, alignment);
     }
     if (extent_register(tsdn, extent)) {
         extent_dalloc(tsdn, arena, extent);
         return NULL;
     }
     return extent;
 }
References ALIGNMENT_CEILING, arena, arena_extent_sn_next, arena_ind_get(), extent_addr_randomize(), extent_alloc(), extent_alloc_default_impl(), extent_dalloc(), extent_hook_post_reentrancy(), extent_hook_pre_reentrancy(), extent_hooks_default, extent_init(), EXTENT_NOT_HEAD, extent_register(), extent_state_active, NULL, PAGE, and G3D::zero().
Referenced by extent_alloc_wrapper().
extent_boot()
bool extent_boot (void)
Definition at line 2319 of file extent.c.
                   {
     if (rtree_new(&extents_rtree, true)) {
         return true;
     }
     if (mutex_pool_init(&extent_mutex_pool, "extent_mutex_pool",
         WITNESS_RANK_EXTENT_POOL)) {
         return true;
     }
     if (have_dss) {
         extent_dss_boot();
     }
     return false;
 }
References extent_dss_boot, extent_mutex_pool, extents_rtree, have_dss, mutex_pool_init, rtree_new, and WITNESS_RANK_EXTENT_POOL.
extent_can_coalesce()
static bool extent_can_coalesce (arena_t * arena, extents_t * extents, const extent_t * inner, const extent_t * outer) static
Definition at line 1560 of file extent.c.
{
     assert(extent_arena_get(inner) == arena);
     if (extent_arena_get(outer) != arena) {
         return false;
     }
     assert(extent_state_get(inner) == extent_state_active);
     if (extent_state_get(outer) != extents->state) {
         return false;
     }
     if (extent_committed_get(inner) != extent_committed_get(outer)) {
         return false;
     }
     return true;
 }
References arena, assert(), extent_arena_get(), extent_committed_get(), extent_state_active, extent_state_get(), and extents_s::state.
Referenced by extent_coalesce(), and extent_try_coalesce_impl().
extent_coalesce()
static bool extent_coalesce (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extents_t * extents, extent_t * inner, extent_t * outer, bool forward, bool growing_retained) static
Definition at line 1580 of file extent.c.
{
     assert(extent_can_coalesce(arena, extents, inner, outer));
     extent_activate_locked(tsdn, arena, extents, outer);
     malloc_mutex_unlock(tsdn, &extents->mtx);
     bool err = extent_merge_impl(tsdn, arena, r_extent_hooks,
         forward ? inner : outer, forward ? outer : inner, growing_retained);
     malloc_mutex_lock(tsdn, &extents->mtx);
     if (err) {
         extent_deactivate_locked(tsdn, arena, extents, outer);
     }
     return err;
 }
References arena, assert(), extent_activate_locked(), extent_can_coalesce(), extent_deactivate_locked(), extent_merge_impl(), malloc_mutex_lock(), malloc_mutex_unlock(), and extents_s::mtx.
Referenced by extent_try_coalesce_impl().
extent_commit_default()
static bool extent_commit_default (extent_hooks_t * extent_hooks, void * addr, size_t size, size_t offset, size_t length, unsigned arena_ind) static
Definition at line 1908 of file extent.c.
{
     return pages_commit((void *)((uintptr_t)addr + (uintptr_t)offset),
         length);
 }
References G3D::length(), and pages_commit.
extent_commit_impl()
static bool extent_commit_impl (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extent_t * extent, size_t offset, size_t length, bool growing_retained) static
Definition at line 1915 of file extent.c.
{
     witness_assert_depth_to_rank(tsdn_witness_tsdp_get(tsdn),
         WITNESS_RANK_CORE, growing_retained ? 1 : 0);
     extent_hooks_assure_initialized(arena, r_extent_hooks);
     if (*r_extent_hooks != &extent_hooks_default) {
         extent_hook_pre_reentrancy(tsdn, arena);
     }
     bool err = ((*r_extent_hooks)->commit == NULL ||
         (*r_extent_hooks)->commit(*r_extent_hooks, extent_base_get(extent),
         extent_size_get(extent), offset, length, arena_ind_get(arena)));
     if (*r_extent_hooks != &extent_hooks_default) {
         extent_hook_post_reentrancy(tsdn);
     }
     extent_committed_set(extent, extent_committed_get(extent) || !err);
     return err;
 }
References arena, arena_ind_get(), extent_base_get(), extent_committed_get(), extent_committed_set(), extent_hook_post_reentrancy(), extent_hook_pre_reentrancy(), extent_hooks_assure_initialized(), extent_hooks_default, extent_size_get(), G3D::length(), NULL, witness_assert_depth_to_rank(), and WITNESS_RANK_CORE.
Referenced by extent_commit_wrapper(), extent_grow_retained(), and extent_recycle().
extent_commit_wrapper()
bool extent_commit_wrapper (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extent_t * extent, size_t offset, size_t length)
Definition at line 1936 of file extent.c.
                    {
     return extent_commit_impl(tsdn, arena, r_extent_hooks, extent, offset,
         length, false);
 }
References arena, extent_commit_impl(), and G3D::length().
extent_dalloc()
void extent_dalloc (tsdn_t * tsdn, arena_t * arena, extent_t * extent)
Definition at line 194 of file extent.c.
{
     malloc_mutex_lock(tsdn, &arena->extent_avail_mtx);
     extent_avail_insert(&arena->extent_avail, extent);
     atomic_fetch_add_zu(&arena->extent_avail_cnt, 1, ATOMIC_RELAXED);
     malloc_mutex_unlock(tsdn, &arena->extent_avail_mtx);
 }
References arena, ATOMIC_RELAXED, arena_s::extent_avail, arena_s::extent_avail_cnt, extent_avail_insert, arena_s::extent_avail_mtx, malloc_mutex_lock(), and malloc_mutex_unlock().
Referenced by extent_alloc_wrapper_hard(), extent_dalloc_gap(), extent_dalloc_wrapper_try(), extent_destroy_wrapper(), extent_grow_retained(), extent_merge_impl(), extent_split_impl(), and extents_abandon_vm().
extent_dalloc_default()
static bool extent_dalloc_default (extent_hooks_t * extent_hooks, void * addr, size_t size, bool committed, unsigned arena_ind) static
Definition at line 1767 of file extent.c.
{
     return extent_dalloc_default_impl(addr, size);
 }
References extent_dalloc_default_impl().
extent_dalloc_default_impl()
static bool extent_dalloc_default_impl (void * addr, size_t size) static
Definition at line 1759 of file extent.c.
{
     if (!have_dss || !extent_in_dss(addr)) {
         return extent_dalloc_mmap(addr, size);
     }
     return true;
 }
References extent_dalloc_mmap, extent_in_dss, and have_dss.
Referenced by extent_dalloc_default(), and extent_dalloc_wrapper_try().
extent_dalloc_gap()
void extent_dalloc_gap (tsdn_t * tsdn, arena_t * arena, extent_t * extent)
Definition at line 1739 of file extent.c.
{
     extent_hooks_t *extent_hooks = EXTENT_HOOKS_INITIALIZER;
     witness_assert_depth_to_rank(tsdn_witness_tsdp_get(tsdn),
         WITNESS_RANK_CORE, 0);
     if (extent_register(tsdn, extent)) {
         extent_dalloc(tsdn, arena, extent);
         return;
     }
     extent_dalloc_wrapper(tsdn, arena, &extent_hooks, extent);
 }
References arena, extent_dalloc(), extent_dalloc_wrapper(), EXTENT_HOOKS_INITIALIZER, extent_register(), witness_assert_depth_to_rank(), and WITNESS_RANK_CORE.
extent_dalloc_wrapper()
void extent_dalloc_wrapper (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extent_t * extent)
Definition at line 1807 of file extent.c.
{
     assert(extent_dumpable_get(extent));
     witness_assert_depth_to_rank(tsdn_witness_tsdp_get(tsdn),
         WITNESS_RANK_CORE, 0);
     /* Avoid calling the default extent_dalloc unless have to. */
     if (*r_extent_hooks != &extent_hooks_default || extent_may_dalloc()) {
         /*
          * Deregister first to avoid a race with other allocating
          * threads, and reregister if deallocation fails.
          */
         extent_deregister(tsdn, extent);
         if (!extent_dalloc_wrapper_try(tsdn, arena, r_extent_hooks,
             extent)) {
             return;
         }
         extent_reregister(tsdn, extent);
     }
     if (*r_extent_hooks != &extent_hooks_default) {
         extent_hook_pre_reentrancy(tsdn, arena);
     }
     /* Try to decommit; purge if that fails. */
     bool zeroed;
     if (!extent_committed_get(extent)) {
         zeroed = true;
     } else if (!extent_decommit_wrapper(tsdn, arena, r_extent_hooks, extent,
         0, extent_size_get(extent))) {
         zeroed = true;
     } else if ((*r_extent_hooks)->purge_forced != NULL &&
         !(*r_extent_hooks)->purge_forced(*r_extent_hooks,
         extent_base_get(extent), extent_size_get(extent), 0,
         extent_size_get(extent), arena_ind_get(arena))) {
         zeroed = true;
     } else if (extent_state_get(extent) == extent_state_muzzy ||
         ((*r_extent_hooks)->purge_lazy != NULL &&
         !(*r_extent_hooks)->purge_lazy(*r_extent_hooks,
         extent_base_get(extent), extent_size_get(extent), 0,
         extent_size_get(extent), arena_ind_get(arena)))) {
         zeroed = false;
     } else {
         zeroed = false;
     }
     if (*r_extent_hooks != &extent_hooks_default) {
         extent_hook_post_reentrancy(tsdn);
     }
     extent_zeroed_set(extent, zeroed);
     if (config_prof) {
         extent_gdump_sub(tsdn, extent);
     }
     extent_record(tsdn, arena, r_extent_hooks, &arena->extents_retained,
         extent, false);
 }
References arena, arena_ind_get(), assert(), config_prof, extent_base_get(), extent_committed_get(), extent_dalloc_wrapper_try(), extent_decommit_wrapper(), extent_deregister(), extent_dumpable_get(), extent_gdump_sub(), extent_hook_post_reentrancy(), extent_hook_pre_reentrancy(), extent_hooks_default, extent_may_dalloc(), extent_record(), extent_reregister(), extent_size_get(), extent_state_get(), extent_state_muzzy, extent_zeroed_set(), arena_s::extents_retained, NULL, witness_assert_depth_to_rank(), and WITNESS_RANK_CORE.
Referenced by extent_dalloc_gap().
extent_dalloc_wrapper_try()
static bool extent_dalloc_wrapper_try (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extent_t * extent) static
Definition at line 1773 of file extent.c.
{
     bool err;
     assert(extent_base_get(extent) != NULL);
     assert(extent_size_get(extent) != 0);
     witness_assert_depth_to_rank(tsdn_witness_tsdp_get(tsdn),
         WITNESS_RANK_CORE, 0);
     extent_addr_set(extent, extent_base_get(extent));
     extent_hooks_assure_initialized(arena, r_extent_hooks);
     /* Try to deallocate. */
     if (*r_extent_hooks == &extent_hooks_default) {
         /* Call directly to propagate tsdn. */
         err = extent_dalloc_default_impl(extent_base_get(extent),
             extent_size_get(extent));
     } else {
         extent_hook_pre_reentrancy(tsdn, arena);
         err = ((*r_extent_hooks)->dalloc == NULL ||
             (*r_extent_hooks)->dalloc(*r_extent_hooks,
             extent_base_get(extent), extent_size_get(extent),
             extent_committed_get(extent), arena_ind_get(arena)));
         extent_hook_post_reentrancy(tsdn);
     }
     if (!err) {
         extent_dalloc(tsdn, arena, extent);
     }
     return err;
 }
References arena, arena_ind_get(), assert(), extent_addr_set(), extent_base_get(), extent_committed_get(), extent_dalloc(), extent_dalloc_default_impl(), extent_hook_post_reentrancy(), extent_hook_pre_reentrancy(), extent_hooks_assure_initialized(), extent_hooks_default, extent_size_get(), NULL, witness_assert_depth_to_rank(), and WITNESS_RANK_CORE.
Referenced by extent_dalloc_wrapper().
extent_deactivate()
static void extent_deactivate (tsdn_t * tsdn, arena_t * arena, extents_t * extents, extent_t * extent) static
Definition at line 682 of file extent.c.
                       {
     malloc_mutex_lock(tsdn, &extents->mtx);
     extent_deactivate_locked(tsdn, arena, extents, extent);
     malloc_mutex_unlock(tsdn, &extents->mtx);
 }
References arena, extent_deactivate_locked(), malloc_mutex_lock(), malloc_mutex_unlock(), and extents_s::mtx.
Referenced by extent_recycle_split().
extent_deactivate_locked()
static void extent_deactivate_locked (tsdn_t * tsdn, arena_t * arena, extents_t * extents, extent_t * extent) static
Definition at line 672 of file extent.c.
                       {
     assert(extent_arena_get(extent) == arena);
     assert(extent_state_get(extent) == extent_state_active);
     extent_state_set(extent, extents_state_get(extents));
     extents_insert_locked(tsdn, extents, extent);
 }
References arena, assert(), extent_arena_get(), extent_state_active, extent_state_get(), extent_state_set(), extents_insert_locked(), and extents_state_get().
Referenced by extent_coalesce(), extent_deactivate(), and extent_record().
extent_decommit_default()
static bool extent_decommit_default (extent_hooks_t * extent_hooks, void * addr, size_t size, size_t offset, size_t length, unsigned arena_ind) static
Definition at line 1944 of file extent.c.
{
     return pages_decommit((void *)((uintptr_t)addr + (uintptr_t)offset),
         length);
 }
References G3D::length(), and pages_decommit.
extent_decommit_wrapper()
bool extent_decommit_wrapper (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extent_t * extent, size_t offset, size_t length)
Definition at line 1951 of file extent.c.
                    {
     witness_assert_depth_to_rank(tsdn_witness_tsdp_get(tsdn),
         WITNESS_RANK_CORE, 0);
     extent_hooks_assure_initialized(arena, r_extent_hooks);
     if (*r_extent_hooks != &extent_hooks_default) {
         extent_hook_pre_reentrancy(tsdn, arena);
     }
     bool err = ((*r_extent_hooks)->decommit == NULL ||
         (*r_extent_hooks)->decommit(*r_extent_hooks,
         extent_base_get(extent), extent_size_get(extent), offset, length,
         arena_ind_get(arena)));
     if (*r_extent_hooks != &extent_hooks_default) {
         extent_hook_post_reentrancy(tsdn);
     }
     extent_committed_set(extent, extent_committed_get(extent) && err);
     return err;
 }
References arena, arena_ind_get(), extent_base_get(), extent_committed_get(), extent_committed_set(), extent_hook_post_reentrancy(), extent_hook_pre_reentrancy(), extent_hooks_assure_initialized(), extent_hooks_default, extent_size_get(), G3D::length(), NULL, witness_assert_depth_to_rank(), and WITNESS_RANK_CORE.
Referenced by extent_dalloc_wrapper().
extent_deregister()
static void extent_deregister (tsdn_t * tsdn, extent_t * extent) static
Definition at line 878 of file extent.c.
{
     extent_deregister_impl(tsdn, extent, true);
 }
References extent_deregister_impl().
Referenced by extent_dalloc_wrapper(), extent_destroy_wrapper(), extent_recycle_split(), and extents_evict().
extent_deregister_impl()
static void extent_deregister_impl (tsdn_t * tsdn, extent_t * extent, bool gdump) static
Definition at line 855 of file extent.c.
{
     rtree_ctx_t rtree_ctx_fallback;
     rtree_ctx_t *rtree_ctx = tsdn_rtree_ctx(tsdn, &rtree_ctx_fallback);
     rtree_leaf_elm_t *elm_a, *elm_b;
     extent_rtree_leaf_elms_lookup(tsdn, rtree_ctx, extent, true, false,
         &elm_a, &elm_b);
     extent_lock(tsdn, extent);
     extent_rtree_write_acquired(tsdn, elm_a, elm_b, NULL, SC_NSIZES, false);
     if (extent_slab_get(extent)) {
         extent_interior_deregister(tsdn, rtree_ctx, extent);
         extent_slab_set(extent, false);
     }
     extent_unlock(tsdn, extent);
     if (config_prof && gdump) {
         extent_gdump_sub(tsdn, extent);
     }
 }
References config_prof, extent_gdump_sub(), extent_interior_deregister(), extent_lock(), extent_rtree_leaf_elms_lookup(), extent_rtree_write_acquired(), extent_slab_get(), extent_slab_set(), extent_unlock(), NULL, SC_NSIZES, and tsdn_rtree_ctx().
Referenced by extent_deregister(), and extent_deregister_no_gdump_sub().
extent_deregister_no_gdump_sub()
static void extent_deregister_no_gdump_sub (tsdn_t * tsdn, extent_t * extent) static
Definition at line 883 of file extent.c.
{
     extent_deregister_impl(tsdn, extent, false);
 }
References extent_deregister_impl().
Referenced by extent_grow_retained(), and extent_recycle_split().
extent_destroy_default()
static void extent_destroy_default (extent_hooks_t * extent_hooks, void * addr, size_t size, bool committed, unsigned arena_ind) static
Definition at line 1872 of file extent.c.
{
     extent_destroy_default_impl(addr, size);
 }
References extent_destroy_default_impl().
extent_destroy_default_impl()
static void extent_destroy_default_impl (void * addr, size_t size) static
Definition at line 1865 of file extent.c.
{
     if (!have_dss || !extent_in_dss(addr)) {
         pages_unmap(addr, size);
     }
 }
References extent_in_dss, have_dss, and pages_unmap.
Referenced by extent_destroy_default(), and extent_destroy_wrapper().
extent_destroy_wrapper()
void extent_destroy_wrapper (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extent_t * extent)
Definition at line 1878 of file extent.c.
{
     assert(extent_base_get(extent) != NULL);
     assert(extent_size_get(extent) != 0);
     witness_assert_depth_to_rank(tsdn_witness_tsdp_get(tsdn),
         WITNESS_RANK_CORE, 0);
     /* Deregister first to avoid a race with other allocating threads. */
     extent_deregister(tsdn, extent);
     extent_addr_set(extent, extent_base_get(extent));
     extent_hooks_assure_initialized(arena, r_extent_hooks);
     /* Try to destroy; silently fail otherwise. */
     if (*r_extent_hooks == &extent_hooks_default) {
         /* Call directly to propagate tsdn. */
         extent_destroy_default_impl(extent_base_get(extent),
             extent_size_get(extent));
     } else if ((*r_extent_hooks)->destroy != NULL) {
         extent_hook_pre_reentrancy(tsdn, arena);
         (*r_extent_hooks)->destroy(*r_extent_hooks,
             extent_base_get(extent), extent_size_get(extent),
             extent_committed_get(extent), arena_ind_get(arena));
         extent_hook_post_reentrancy(tsdn);
     }
     extent_dalloc(tsdn, arena, extent);
 }
References arena, arena_ind_get(), assert(), extent_addr_set(), extent_base_get(), extent_committed_get(), extent_dalloc(), extent_deregister(), extent_destroy_default_impl(), extent_hook_post_reentrancy(), extent_hook_pre_reentrancy(), extent_hooks_assure_initialized(), extent_hooks_default, extent_size_get(), NULL, witness_assert_depth_to_rank(), and WITNESS_RANK_CORE.
extent_gdump_add()
static void extent_gdump_add (tsdn_t * tsdn, const extent_t * extent) static
Definition at line 744 of file extent.c.
{
     cassert(config_prof);
     /* prof_gdump() requirement. */
     witness_assert_depth_to_rank(tsdn_witness_tsdp_get(tsdn),
         WITNESS_RANK_CORE, 0);
     if (opt_prof && extent_state_get(extent) == extent_state_active) {
         size_t nadd = extent_size_get(extent) >> LG_PAGE;
         size_t cur = atomic_fetch_add_zu(&curpages, nadd,
             ATOMIC_RELAXED) + nadd;
         size_t high = atomic_load_zu(&highpages, ATOMIC_RELAXED);
         while (cur > high && !atomic_compare_exchange_weak_zu(
             &highpages, &high, cur, ATOMIC_RELAXED, ATOMIC_RELAXED)) {
             /*
              * Don't refresh cur, because it may have decreased
              * since this thread lost the highpages update race.
              * Note that high is updated in case of CAS failure.
              */
         }
         if (cur > high && prof_gdump_get_unlocked()) {
             prof_gdump(tsdn);
         }
     }
 }
References ATOMIC_RELAXED, cassert(), config_prof, curpages, extent_size_get(), extent_state_active, extent_state_get(), highpages, LG_PAGE, opt_prof, prof_gdump, prof_gdump_get_unlocked(), witness_assert_depth_to_rank(), and WITNESS_RANK_CORE.
Referenced by extent_alloc_retained(), extent_grow_retained(), and extent_register_impl().
extent_gdump_sub()
static void extent_gdump_sub (tsdn_t * tsdn, const extent_t * extent) static
Definition at line 770 of file extent.c.
{
     cassert(config_prof);
     if (opt_prof && extent_state_get(extent) == extent_state_active) {
         size_t nsub = extent_size_get(extent) >> LG_PAGE;
         assert(atomic_load_zu(&curpages, ATOMIC_RELAXED) >= nsub);
         atomic_fetch_sub_zu(&curpages, nsub, ATOMIC_RELAXED);
     }
 }
References assert(), ATOMIC_RELAXED, cassert(), config_prof, curpages, extent_size_get(), extent_state_active, extent_state_get(), LG_PAGE, and opt_prof.
Referenced by extent_dalloc_wrapper(), and extent_deregister_impl().
extent_grow_retained()
static extent_t* extent_grow_retained (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, size_t size, size_t pad, size_t alignment, bool slab, szind_t szind, bool * zero, bool * commit) static
Definition at line 1297 of file extent.c.
{
     malloc_mutex_assert_owner(tsdn, &arena->extent_grow_mtx);
     assert(pad == 0 || !slab);
     assert(!*zero || !slab);
     size_t esize = size + pad;
     size_t alloc_size_min = esize + PAGE_CEILING(alignment) - PAGE;
     /* Beware size_t wrap-around. */
     if (alloc_size_min < esize) {
         goto label_err;
     }
     /*
      * Find the next extent size in the series that would be large enough to
      * satisfy this request.
      */
     pszind_t egn_skip = 0;
     size_t alloc_size = sz_pind2sz(arena->extent_grow_next + egn_skip);
     while (alloc_size < alloc_size_min) {
         egn_skip++;
         if (arena->extent_grow_next + egn_skip >=
             sz_psz2ind(SC_LARGE_MAXCLASS)) {
             /* Outside legal range. */
             goto label_err;
         }
         alloc_size = sz_pind2sz(arena->extent_grow_next + egn_skip);
     }
     extent_t *extent = extent_alloc(tsdn, arena);
     if (extent == NULL) {
         goto label_err;
     }
     bool zeroed = false;
     bool committed = false;
     void *ptr;
     if (*r_extent_hooks == &extent_hooks_default) {
         ptr = extent_alloc_default_impl(tsdn, arena, NULL,
             alloc_size, PAGE, &zeroed, &committed);
     } else {
         extent_hook_pre_reentrancy(tsdn, arena);
         ptr = (*r_extent_hooks)->alloc(*r_extent_hooks, NULL,
             alloc_size, PAGE, &zeroed, &committed,
             arena_ind_get(arena));
         extent_hook_post_reentrancy(tsdn);
     }
     extent_init(extent, arena, ptr, alloc_size, false, SC_NSIZES,
         arena_extent_sn_next(arena), extent_state_active, zeroed,
         committed, true, EXTENT_IS_HEAD);
     if (ptr == NULL) {
         extent_dalloc(tsdn, arena, extent);
         goto label_err;
     }
     if (extent_register_no_gdump_add(tsdn, extent)) {
         extent_dalloc(tsdn, arena, extent);
         goto label_err;
     }
     if (extent_zeroed_get(extent) && extent_committed_get(extent)) {
         *zero = true;
     }
     if (extent_committed_get(extent)) {
         *commit = true;
     }
     rtree_ctx_t rtree_ctx_fallback;
     rtree_ctx_t *rtree_ctx = tsdn_rtree_ctx(tsdn, &rtree_ctx_fallback);
     extent_t *lead;
     extent_t *trail;
     extent_t *to_leak;
     extent_t *to_salvage;
     extent_split_interior_result_t result = extent_split_interior(
         tsdn, arena, r_extent_hooks, rtree_ctx, &extent, &lead, &trail,
         &to_leak, &to_salvage, NULL, size, pad, alignment, slab, szind,
         true);
     if (result == extent_split_interior_ok) {
         if (lead != NULL) {
             extent_record(tsdn, arena, r_extent_hooks,
                 &arena->extents_retained, lead, true);
         }
         if (trail != NULL) {
             extent_record(tsdn, arena, r_extent_hooks,
                 &arena->extents_retained, trail, true);
         }
     } else {
         /*
          * We should have allocated a sufficiently large extent; the
          * cant_alloc case should not occur.
          */
         assert(result == extent_split_interior_error);
         if (to_salvage != NULL) {
             if (config_prof) {
                 extent_gdump_add(tsdn, to_salvage);
             }
             extent_record(tsdn, arena, r_extent_hooks,
                 &arena->extents_retained, to_salvage, true);
         }
         if (to_leak != NULL) {
             extent_deregister_no_gdump_sub(tsdn, to_leak);
             extents_abandon_vm(tsdn, arena, r_extent_hooks,
                 &arena->extents_retained, to_leak, true);
         }
         goto label_err;
     }
     if (*commit && !extent_committed_get(extent)) {
         if (extent_commit_impl(tsdn, arena, r_extent_hooks, extent, 0,
             extent_size_get(extent), true)) {
             extent_record(tsdn, arena, r_extent_hooks,
                 &arena->extents_retained, extent, true);
             goto label_err;
         }
         if (!extent_need_manual_zero(arena)) {
             extent_zeroed_set(extent, true);
         }
     }
     /*
      * Increment extent_grow_next if doing so wouldn't exceed the allowed
      * range.
      */
     if (arena->extent_grow_next + egn_skip + 1 <=
         arena->retain_grow_limit) {
         arena->extent_grow_next += egn_skip + 1;
     } else {
         arena->extent_grow_next = arena->retain_grow_limit;
     }
     /* All opportunities for failure are past. */
     malloc_mutex_unlock(tsdn, &arena->extent_grow_mtx);
     if (config_prof) {
         /* Adjust gdump stats now that extent is final size. */
         extent_gdump_add(tsdn, extent);
     }
     if (pad != 0) {
         extent_addr_randomize(tsdn, extent, alignment);
     }
     if (slab) {
         rtree_ctx_t rtree_ctx_fallback;
         rtree_ctx_t *rtree_ctx = tsdn_rtree_ctx(tsdn,
             &rtree_ctx_fallback);
         extent_slab_set(extent, true);
         extent_interior_register(tsdn, rtree_ctx, extent, szind);
     }
     if (*zero && !extent_zeroed_get(extent)) {
         void *addr = extent_base_get(extent);
         size_t size = extent_size_get(extent);
         if (extent_need_manual_zero(arena) ||
             pages_purge_forced(addr, size)) {
             memset(addr, 0, size);
         }
     }
     return extent;
 label_err:
     malloc_mutex_unlock(tsdn, &arena->extent_grow_mtx);
     return NULL;
 }
References arena, arena_extent_sn_next, arena_ind_get(), assert(), config_prof, extent_addr_randomize(), extent_alloc(), extent_alloc_default_impl(), extent_base_get(), extent_commit_impl(), extent_committed_get(), extent_dalloc(), extent_deregister_no_gdump_sub(), extent_gdump_add(), arena_s::extent_grow_mtx, arena_s::extent_grow_next, extent_hook_post_reentrancy(), extent_hook_pre_reentrancy(), extent_hooks_default, extent_init(), extent_interior_register(), EXTENT_IS_HEAD, extent_need_manual_zero(), extent_record(), extent_register_no_gdump_add(), extent_size_get(), extent_slab_set(), extent_split_interior(), extent_split_interior_error, extent_split_interior_ok, extent_state_active, extent_zeroed_get(), extent_zeroed_set(), extents_abandon_vm(), arena_s::extents_retained, malloc_mutex_assert_owner(), malloc_mutex_unlock(), memset, NULL, PAGE, PAGE_CEILING, pages_purge_forced, ptr(), arena_s::retain_grow_limit, SC_LARGE_MAXCLASS, SC_NSIZES, sz_pind2sz(), sz_psz2ind(), tsdn_rtree_ctx(), and G3D::zero().
Referenced by extent_alloc_retained().
extent_head_no_merge()
static bool extent_head_no_merge (extent_t * a, extent_t * b) static
Definition at line 2197 of file extent.c.
{
     assert(extent_base_get(a) < extent_base_get(b));
     /*
      * When coalesce is not always allowed (Windows), only merge extents
      * from the same VirtualAlloc region under opt.retain (in which case
      * MEM_DECOMMIT is utilized for purging).
      */
     if (maps_coalesce) {
         return false;
     }
     if (!opt_retain) {
         return true;
     }
     /* If b is a head extent, disallow the cross-region merge. */
     if (extent_is_head_get(b)) {
         /*
          * Additionally, sn should not overflow with retain; sanity
          * check that different regions have unique sn.
          */
         assert(extent_sn_comp(a, b) != 0);
         return true;
     }
     assert(extent_sn_comp(a, b) == 0);
     return false;
 }
References mpq::a, assert(), b, extent_base_get(), extent_is_head_get(), extent_sn_comp(), maps_coalesce, and opt_retain.
Referenced by extent_merge_default(), and extent_merge_impl().
extent_hook_post_reentrancy()
static void extent_hook_post_reentrancy (tsdn_t * tsdn) static
Definition at line 1286 of file extent.c.
{
     tsd_t *tsd = tsdn_null(tsdn) ? tsd_fetch() : tsdn_tsd(tsdn);
     post_reentrancy(tsd);
 }
References post_reentrancy(), tsd_fetch(), tsdn_null(), and tsdn_tsd().
Referenced by extent_alloc_wrapper_hard(), extent_commit_impl(), extent_dalloc_wrapper(), extent_dalloc_wrapper_try(), extent_decommit_wrapper(), extent_destroy_wrapper(), extent_grow_retained(), extent_merge_impl(), extent_purge_forced_impl(), extent_purge_lazy_impl(), and extent_split_impl().
extent_hook_pre_reentrancy()
static void extent_hook_pre_reentrancy (tsdn_t * tsdn, arena_t * arena) static
Definition at line 1269 of file extent.c.
{
     tsd_t *tsd = tsdn_null(tsdn) ? tsd_fetch() : tsdn_tsd(tsdn);
     if (arena == arena_get(tsd_tsdn(tsd), 0, false)) {
         /*
          * The only legitimate case of customized extent hooks for a0 is
          * hooks with no allocation activities.  One such example is to
          * place metadata on pre-allocated resources such as huge pages.
          * In that case, rely on reentrancy_level checks to catch
          * infinite recursions.
          */
         pre_reentrancy(tsd, NULL);
     } else {
         pre_reentrancy(tsd, arena);
     }
 }
References arena, arena_get(), NULL, pre_reentrancy(), tsd_fetch(), tsd_tsdn(), tsdn_null(), and tsdn_tsd().
Referenced by extent_alloc_wrapper_hard(), extent_commit_impl(), extent_dalloc_wrapper(), extent_dalloc_wrapper_try(), extent_decommit_wrapper(), extent_destroy_wrapper(), extent_grow_retained(), extent_merge_impl(), extent_purge_forced_impl(), extent_purge_lazy_impl(), and extent_split_impl().
extent_hooks_assure_initialized()
static void extent_hooks_assure_initialized (arena_t * arena, extent_hooks_t ** r_extent_hooks) static
Definition at line 222 of file extent.c.
{
     if (*r_extent_hooks == EXTENT_HOOKS_INITIALIZER) {
         *r_extent_hooks = extent_hooks_get(arena);
     }
 }
References arena, extent_hooks_get(), and EXTENT_HOOKS_INITIALIZER.
Referenced by extent_alloc_wrapper(), extent_commit_impl(), extent_dalloc_wrapper_try(), extent_decommit_wrapper(), extent_destroy_wrapper(), extent_merge_impl(), extent_purge_forced_impl(), extent_purge_lazy_impl(), extent_record(), extent_recycle_extract(), and extent_split_impl().
extent_hooks_get()
extent_hooks_t* extent_hooks_get (arena_t * arena)
Definition at line 202 of file extent.c.
{
     return base_extent_hooks_get(arena->base);
 }
References arena, arena_s::base, and base_extent_hooks_get.
Referenced by extent_hooks_assure_initialized().
extent_hooks_set()
extent_hooks_t* extent_hooks_set (tsd_t * tsd, arena_t * arena, extent_hooks_t * extent_hooks)
Definition at line 207 of file extent.c.
{
     background_thread_info_t *info;
     if (have_background_thread) {
         info = arena_background_thread_info_get(arena);
         malloc_mutex_lock(tsd_tsdn(tsd), &info->mtx);
     }
     extent_hooks_t *ret = base_extent_hooks_set(arena->base, extent_hooks);
     if (have_background_thread) {
         malloc_mutex_unlock(tsd_tsdn(tsd), &info->mtx);
     }
     return ret;
 }
References arena, arena_background_thread_info_get(), arena_s::base, base_extent_hooks_set, have_background_thread, malloc_mutex_lock(), malloc_mutex_unlock(), background_thread_info_s::mtx, ret, and tsd_tsdn().
extent_interior_deregister()
static void extent_interior_deregister (tsdn_t * tsdn, rtree_ctx_t * rtree_ctx, extent_t * extent) static
Definition at line 838 of file extent.c.
                       {
     size_t i;
     assert(extent_slab_get(extent));
     for (i = 1; i < (extent_size_get(extent) >> LG_PAGE) - 1; i++) {
         rtree_clear(tsdn, &extents_rtree, rtree_ctx,
             (uintptr_t)extent_base_get(extent) + (uintptr_t)(i <<
             LG_PAGE));
     }
 }
References assert(), extent_base_get(), extent_size_get(), extent_slab_get(), extents_rtree, LG_PAGE, and rtree_clear().
Referenced by extent_deregister_impl(), and extent_record().
extent_interior_register()
static void extent_interior_register (tsdn_t * tsdn, rtree_ctx_t * rtree_ctx, extent_t * extent, szind_t szind) static
Definition at line 731 of file extent.c.
                    {
     assert(extent_slab_get(extent));
     /* Register interior. */
     for (size_t i = 1; i < (extent_size_get(extent) >> LG_PAGE) - 1; i++) {
         rtree_write(tsdn, &extents_rtree, rtree_ctx,
             (uintptr_t)extent_base_get(extent) + (uintptr_t)(i <<
             LG_PAGE), extent, szind, true);
     }
 }
References assert(), extent_base_get(), extent_size_get(), extent_slab_get(), extents_rtree, LG_PAGE, and rtree_write().
Referenced by extent_grow_retained(), extent_recycle(), and extent_register_impl().
extent_lock_from_addr()
static extent_t* extent_lock_from_addr (tsdn_t * tsdn, rtree_ctx_t * rtree_ctx, void * addr, bool inactive_only) static
Definition at line 163 of file extent.c.
{
     extent_t *ret = NULL;
     rtree_leaf_elm_t *elm = rtree_leaf_elm_lookup(tsdn, &extents_rtree,
         rtree_ctx, (uintptr_t)addr, false, false);
     if (elm == NULL) {
         return NULL;
     }
     lock_result_t lock_result;
     do {
         lock_result = extent_rtree_leaf_elm_try_lock(tsdn, elm, &ret,
             inactive_only);
     } while (lock_result == lock_result_failure);
     return ret;
 }
References extent_rtree_leaf_elm_try_lock(), extents_rtree, lock_result_t, NULL, ret, and rtree_leaf_elm_lookup().
Referenced by extent_recycle_extract(), extent_recycle_split(), and extent_try_coalesce_impl().
extent_may_dalloc()
static bool extent_may_dalloc (void) static
Definition at line 1753 of file extent.c.
{
     /* With retain enabled, the default dalloc always fails. */
     return !opt_retain;
 }
References opt_retain.
Referenced by extent_dalloc_wrapper().
extent_merge_default()
static bool extent_merge_default (extent_hooks_t * extent_hooks, void * addr_a, size_t size_a, void * addr_b, size_t size_b, bool committed, unsigned arena_ind) static
Definition at line 2225 of file extent.c.
{
     if (!maps_coalesce) {
         tsdn_t *tsdn = tsdn_fetch();
         extent_t *a = iealloc(tsdn, addr_a);
         extent_t *b = iealloc(tsdn, addr_b);
         if (extent_head_no_merge(a, b)) {
             return true;
         }
     }
     return extent_merge_default_impl(addr_a, addr_b);
 }
References mpq::a, b, extent_head_no_merge(), extent_merge_default_impl(), iealloc(), maps_coalesce, and tsdn_fetch().
extent_merge_default_impl()
static bool extent_merge_default_impl (void * addr_a, void * addr_b) static
Definition at line 2181 of file extent.c.
{
     if (!maps_coalesce && !opt_retain) {
         return true;
     }
     if (have_dss && !extent_dss_mergeable(addr_a, addr_b)) {
         return true;
     }
     return false;
 }
References extent_dss_mergeable, have_dss, maps_coalesce, and opt_retain.
Referenced by extent_merge_default(), and extent_merge_impl().
extent_merge_impl()
static bool extent_merge_impl (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extent_t * a, extent_t * b, bool growing_retained) static
Definition at line 2239 of file extent.c.
{
     witness_assert_depth_to_rank(tsdn_witness_tsdp_get(tsdn),
         WITNESS_RANK_CORE, growing_retained ? 1 : 0);
     assert(extent_base_get(a) < extent_base_get(b));
     extent_hooks_assure_initialized(arena, r_extent_hooks);
     if ((*r_extent_hooks)->merge == NULL || extent_head_no_merge(a, b)) {
         return true;
     }
     bool err;
     if (*r_extent_hooks == &extent_hooks_default) {
         /* Call directly to propagate tsdn. */
         err = extent_merge_default_impl(extent_base_get(a),
             extent_base_get(b));
     } else {
         extent_hook_pre_reentrancy(tsdn, arena);
         err = (*r_extent_hooks)->merge(*r_extent_hooks,
             extent_base_get(a), extent_size_get(a), extent_base_get(b),
             extent_size_get(b), extent_committed_get(a),
             arena_ind_get(arena));
         extent_hook_post_reentrancy(tsdn);
     }
     if (err) {
         return true;
     }
     /*
      * The rtree writes must happen while all the relevant elements are
      * owned, so the following code uses decomposed helper functions rather
      * than extent_{,de}register() to do things in the right order.
      */
     rtree_ctx_t rtree_ctx_fallback;
     rtree_ctx_t *rtree_ctx = tsdn_rtree_ctx(tsdn, &rtree_ctx_fallback);
     rtree_leaf_elm_t *a_elm_a, *a_elm_b, *b_elm_a, *b_elm_b;
     extent_rtree_leaf_elms_lookup(tsdn, rtree_ctx, a, true, false, &a_elm_a,
         &a_elm_b);
     extent_rtree_leaf_elms_lookup(tsdn, rtree_ctx, b, true, false, &b_elm_a,
         &b_elm_b);
     extent_lock2(tsdn, a, b);
     if (a_elm_b != NULL) {
         rtree_leaf_elm_write(tsdn, &extents_rtree, a_elm_b, NULL,
             SC_NSIZES, false);
     }
     if (b_elm_b != NULL) {
         rtree_leaf_elm_write(tsdn, &extents_rtree, b_elm_a, NULL,
             SC_NSIZES, false);
     } else {
         b_elm_b = b_elm_a;
     }
     extent_size_set(a, extent_size_get(a) + extent_size_get(b));
     extent_szind_set(a, SC_NSIZES);
     extent_sn_set(a, (extent_sn_get(a) < extent_sn_get(b)) ?
         extent_sn_get(a) : extent_sn_get(b));
     extent_zeroed_set(a, extent_zeroed_get(a) && extent_zeroed_get(b));
     extent_rtree_write_acquired(tsdn, a_elm_a, b_elm_b, a, SC_NSIZES,
         false);
     extent_unlock2(tsdn, a, b);
     extent_dalloc(tsdn, extent_arena_get(b), b);
     return false;
 }
References mpq::a, arena, arena_ind_get(), assert(), b, extent_arena_get(), extent_base_get(), extent_committed_get(), extent_dalloc(), extent_head_no_merge(), extent_hook_post_reentrancy(), extent_hook_pre_reentrancy(), extent_hooks_assure_initialized(), extent_hooks_default, extent_lock2(), extent_merge_default_impl(), extent_rtree_leaf_elms_lookup(), extent_rtree_write_acquired(), extent_size_get(), extent_size_set(), extent_sn_get(), extent_sn_set(), extent_szind_set(), extent_unlock2(), extent_zeroed_get(), extent_zeroed_set(), extents_rtree, NULL, rtree_leaf_elm_write(), SC_NSIZES, tsdn_rtree_ctx(), witness_assert_depth_to_rank(), and WITNESS_RANK_CORE.
Referenced by extent_coalesce(), and extent_merge_wrapper().
extent_merge_wrapper()
bool extent_merge_wrapper (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extent_t * a, extent_t * b)
Definition at line 2313 of file extent.c.
{
     return extent_merge_impl(tsdn, arena, r_extent_hooks, a, b, false);
 }
References mpq::a, arena, b, and extent_merge_impl().
extent_need_manual_zero()
static bool extent_need_manual_zero (arena_t * arena) static
Definition at line 1113 of file extent.c.
{
     /*
      * Need to manually zero the extent on repopulating if either; 1) non
      * default extent hooks installed (in which case the purge semantics may
      * change); or 2) transparent huge pages enabled.
      */
     return (!arena_has_default_hooks(arena) ||
         (opt_thp == thp_mode_always));
 }
References arena, arena_has_default_hooks(), opt_thp, and thp_mode_always.
Referenced by extent_grow_retained(), and extent_recycle().
extent_purge_forced_impl()
static bool extent_purge_forced_impl (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extent_t * extent, size_t offset, size_t length, bool growing_retained) static
Definition at line 2035 of file extent.c.
{
     witness_assert_depth_to_rank(tsdn_witness_tsdp_get(tsdn),
         WITNESS_RANK_CORE, growing_retained ? 1 : 0);
     extent_hooks_assure_initialized(arena, r_extent_hooks);
     if ((*r_extent_hooks)->purge_forced == NULL) {
         return true;
     }
     if (*r_extent_hooks != &extent_hooks_default) {
         extent_hook_pre_reentrancy(tsdn, arena);
     }
     bool err = (*r_extent_hooks)->purge_forced(*r_extent_hooks,
         extent_base_get(extent), extent_size_get(extent), offset, length,
         arena_ind_get(arena));
     if (*r_extent_hooks != &extent_hooks_default) {
         extent_hook_post_reentrancy(tsdn);
     }
     return err;
 }
References arena, arena_ind_get(), extent_base_get(), extent_hook_post_reentrancy(), extent_hook_pre_reentrancy(), extent_hooks_assure_initialized(), extent_hooks_default, extent_size_get(), G3D::length(), NULL, witness_assert_depth_to_rank(), and WITNESS_RANK_CORE.
Referenced by extent_purge_forced_wrapper(), and extents_abandon_vm().
extent_purge_forced_wrapper()
bool extent_purge_forced_wrapper (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extent_t * extent, size_t offset, size_t length)
Definition at line 2059 of file extent.c.
                    {
     return extent_purge_forced_impl(tsdn, arena, r_extent_hooks, extent,
         offset, length, false);
 }
References arena, extent_purge_forced_impl(), and G3D::length().
extent_purge_lazy_impl()
static bool extent_purge_lazy_impl (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extent_t * extent, size_t offset, size_t length, bool growing_retained) static
Definition at line 1988 of file extent.c.
{
     witness_assert_depth_to_rank(tsdn_witness_tsdp_get(tsdn),
         WITNESS_RANK_CORE, growing_retained ? 1 : 0);
     extent_hooks_assure_initialized(arena, r_extent_hooks);
     if ((*r_extent_hooks)->purge_lazy == NULL) {
         return true;
     }
     if (*r_extent_hooks != &extent_hooks_default) {
         extent_hook_pre_reentrancy(tsdn, arena);
     }
     bool err = (*r_extent_hooks)->purge_lazy(*r_extent_hooks,
         extent_base_get(extent), extent_size_get(extent), offset, length,
         arena_ind_get(arena));
     if (*r_extent_hooks != &extent_hooks_default) {
         extent_hook_post_reentrancy(tsdn);
     }
     return err;
 }
References arena, arena_ind_get(), extent_base_get(), extent_hook_post_reentrancy(), extent_hook_pre_reentrancy(), extent_hooks_assure_initialized(), extent_hooks_default, extent_size_get(), G3D::length(), NULL, witness_assert_depth_to_rank(), and WITNESS_RANK_CORE.
Referenced by extent_purge_lazy_wrapper(), and extents_abandon_vm().
extent_purge_lazy_wrapper()
bool extent_purge_lazy_wrapper (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extent_t * extent, size_t offset, size_t length)
Definition at line 2013 of file extent.c.
                    {
     return extent_purge_lazy_impl(tsdn, arena, r_extent_hooks, extent,
         offset, length, false);
 }
References arena, extent_purge_lazy_impl(), and G3D::length().
extent_record()
static void extent_record (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extents_t * extents, extent_t * extent, bool growing_retained) static
Definition at line 1692 of file extent.c.
{
     rtree_ctx_t rtree_ctx_fallback;
     rtree_ctx_t *rtree_ctx = tsdn_rtree_ctx(tsdn, &rtree_ctx_fallback);
     assert((extents_state_get(extents) != extent_state_dirty &&
         extents_state_get(extents) != extent_state_muzzy) ||
         !extent_zeroed_get(extent));
     malloc_mutex_lock(tsdn, &extents->mtx);
     extent_hooks_assure_initialized(arena, r_extent_hooks);
     extent_szind_set(extent, SC_NSIZES);
     if (extent_slab_get(extent)) {
         extent_interior_deregister(tsdn, rtree_ctx, extent);
         extent_slab_set(extent, false);
     }
     assert(rtree_extent_read(tsdn, &extents_rtree, rtree_ctx,
         (uintptr_t)extent_base_get(extent), true) == extent);
     if (!extents->delay_coalesce) {
         extent = extent_try_coalesce(tsdn, arena, r_extent_hooks,
             rtree_ctx, extents, extent, NULL, growing_retained);
     } else if (extent_size_get(extent) >= SC_LARGE_MINCLASS) {
         assert(extents == &arena->extents_dirty);
         /* Always coalesce large extents eagerly. */
         bool coalesced;
         do {
             assert(extent_state_get(extent) == extent_state_active);
             extent = extent_try_coalesce_large(tsdn, arena,
                 r_extent_hooks, rtree_ctx, extents, extent,
                 &coalesced, growing_retained);
         } while (coalesced);
         if (extent_size_get(extent) >= oversize_threshold) {
             /* Shortcut to purge the oversize extent eagerly. */
             malloc_mutex_unlock(tsdn, &extents->mtx);
             arena_decay_extent(tsdn, arena, r_extent_hooks, extent);
             return;
         }
     }
     extent_deactivate_locked(tsdn, arena, extents, extent);
     malloc_mutex_unlock(tsdn, &extents->mtx);
 }
References arena, arena_decay_extent(), assert(), extents_s::delay_coalesce, extent_base_get(), extent_deactivate_locked(), extent_hooks_assure_initialized(), extent_interior_deregister(), extent_size_get(), extent_slab_get(), extent_slab_set(), extent_state_active, extent_state_dirty, extent_state_get(), extent_state_muzzy, extent_szind_set(), extent_try_coalesce(), extent_try_coalesce_large(), extent_zeroed_get(), arena_s::extents_dirty, extents_rtree, extents_state_get(), malloc_mutex_lock(), malloc_mutex_unlock(), extents_s::mtx, NULL, oversize_threshold, rtree_extent_read(), SC_LARGE_MINCLASS, SC_NSIZES, and tsdn_rtree_ctx().
Referenced by extent_dalloc_wrapper(), extent_grow_retained(), extent_recycle(), and extents_dalloc().
extent_recycle()
static extent_t * extent_recycle (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extents_t * extents, void * new_addr, size_t usize, size_t pad, size_t alignment, bool slab, szind_t szind, bool * zero, bool * commit, bool growing_retained) static
Definition at line 1128 of file extent.c.
{
     witness_assert_depth_to_rank(tsdn_witness_tsdp_get(tsdn),
         WITNESS_RANK_CORE, growing_retained ? 1 : 0);
     assert(new_addr == NULL || !slab);
     assert(pad == 0 || !slab);
     assert(!*zero || !slab);
     rtree_ctx_t rtree_ctx_fallback;
     rtree_ctx_t *rtree_ctx = tsdn_rtree_ctx(tsdn, &rtree_ctx_fallback);
     extent_t *extent = extent_recycle_extract(tsdn, arena, r_extent_hooks,
         rtree_ctx, extents, new_addr, size, pad, alignment, slab,
         growing_retained);
     if (extent == NULL) {
         return NULL;
     }
     extent = extent_recycle_split(tsdn, arena, r_extent_hooks, rtree_ctx,
         extents, new_addr, size, pad, alignment, slab, szind, extent,
         growing_retained);
     if (extent == NULL) {
         return NULL;
     }
     if (*commit && !extent_committed_get(extent)) {
         if (extent_commit_impl(tsdn, arena, r_extent_hooks, extent,
             0, extent_size_get(extent), growing_retained)) {
             extent_record(tsdn, arena, r_extent_hooks, extents,
                 extent, growing_retained);
             return NULL;
         }
         if (!extent_need_manual_zero(arena)) {
             extent_zeroed_set(extent, true);
         }
     }
     if (extent_committed_get(extent)) {
         *commit = true;
     }
     if (extent_zeroed_get(extent)) {
         *zero = true;
     }
     if (pad != 0) {
         extent_addr_randomize(tsdn, extent, alignment);
     }
     assert(extent_state_get(extent) == extent_state_active);
     if (slab) {
         extent_slab_set(extent, slab);
         extent_interior_register(tsdn, rtree_ctx, extent, szind);
     }
     if (*zero) {
         void *addr = extent_base_get(extent);
         if (!extent_zeroed_get(extent)) {
             size_t size = extent_size_get(extent);
             if (extent_need_manual_zero(arena) ||
                 pages_purge_forced(addr, size)) {
                 memset(addr, 0, size);
             }
         } else if (config_debug) {
             size_t *p = (size_t *)(uintptr_t)addr;
             /* Check the first page only. */
             for (size_t i = 0; i < PAGE / sizeof(size_t); i++) {
                 assert(p[i] == 0);
             }
         }
     }
     return extent;
 }
References arena, assert(), config_debug, extent_addr_randomize(), extent_base_get(), extent_commit_impl(), extent_committed_get(), extent_interior_register(), extent_need_manual_zero(), extent_record(), extent_recycle_extract(), extent_recycle_split(), extent_size_get(), extent_slab_set(), extent_state_active, extent_state_get(), extent_zeroed_get(), extent_zeroed_set(), memset, NULL, PAGE, pages_purge_forced, tsdn_rtree_ctx(), witness_assert_depth_to_rank(), WITNESS_RANK_CORE, and G3D::zero().
Referenced by extent_alloc_retained(), and extents_alloc().
extent_recycle_extract()
static extent_t* extent_recycle_extract (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, rtree_ctx_t * rtree_ctx, extents_t * extents, void * new_addr, size_t size, size_t pad, size_t alignment, bool slab, bool growing_retained) static
Definition at line 892 of file extent.c.
{
     witness_assert_depth_to_rank(tsdn_witness_tsdp_get(tsdn),
         WITNESS_RANK_CORE, growing_retained ? 1 : 0);
     assert(alignment > 0);
     if (config_debug && new_addr != NULL) {
         /*
          * Non-NULL new_addr has two use cases:
          *
          *   1) Recycle a known-extant extent, e.g. during purging.
          *   2) Perform in-place expanding reallocation.
          *
          * Regardless of use case, new_addr must either refer to a
          * non-existing extent, or to the base of an extant extent,
          * since only active slabs support interior lookups (which of
          * course cannot be recycled).
          */
         assert(PAGE_ADDR2BASE(new_addr) == new_addr);
         assert(pad == 0);
         assert(alignment <= PAGE);
     }
     size_t esize = size + pad;
     malloc_mutex_lock(tsdn, &extents->mtx);
     extent_hooks_assure_initialized(arena, r_extent_hooks);
     extent_t *extent;
     if (new_addr != NULL) {
         extent = extent_lock_from_addr(tsdn, rtree_ctx, new_addr,
             false);
         if (extent != NULL) {
             /*
              * We might null-out extent to report an error, but we
              * still need to unlock the associated mutex after.
              */
             extent_t *unlock_extent = extent;
             assert(extent_base_get(extent) == new_addr);
             if (extent_arena_get(extent) != arena ||
                 extent_size_get(extent) < esize ||
                 extent_state_get(extent) !=
                 extents_state_get(extents)) {
                 extent = NULL;
             }
             extent_unlock(tsdn, unlock_extent);
         }
     } else {
         extent = extents_fit_locked(tsdn, arena, extents, esize,
             alignment);
     }
     if (extent == NULL) {
         malloc_mutex_unlock(tsdn, &extents->mtx);
         return NULL;
     }
     extent_activate_locked(tsdn, arena, extents, extent);
     malloc_mutex_unlock(tsdn, &extents->mtx);
     return extent;
 }
References arena, assert(), config_debug, extent_activate_locked(), extent_arena_get(), extent_base_get(), extent_hooks_assure_initialized(), extent_lock_from_addr(), extent_size_get(), extent_state_get(), extent_unlock(), extents_fit_locked(), extents_state_get(), malloc_mutex_lock(), malloc_mutex_unlock(), extents_s::mtx, NULL, PAGE, PAGE_ADDR2BASE, witness_assert_depth_to_rank(), and WITNESS_RANK_CORE.
Referenced by extent_recycle().
extent_recycle_split()
static extent_t* extent_recycle_split (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, rtree_ctx_t * rtree_ctx, extents_t * extents, void * new_addr, size_t size, size_t pad, size_t alignment, bool slab, szind_t szind, extent_t * extent, bool growing_retained) static
Definition at line 1057 of file extent.c.
{
     extent_t *lead;
     extent_t *trail;
     extent_t *to_leak;
     extent_t *to_salvage;
     extent_split_interior_result_t result = extent_split_interior(
         tsdn, arena, r_extent_hooks, rtree_ctx, &extent, &lead, &trail,
         &to_leak, &to_salvage, new_addr, size, pad, alignment, slab, szind,
         growing_retained);
     if (!maps_coalesce && result != extent_split_interior_ok
         && !opt_retain) {
         /*
          * Split isn't supported (implies Windows w/o retain).  Avoid
          * leaking the extents.
          */
         assert(to_leak != NULL && lead == NULL && trail == NULL);
         extent_deactivate(tsdn, arena, extents, to_leak);
         return NULL;
     }
     if (result == extent_split_interior_ok) {
         if (lead != NULL) {
             extent_deactivate(tsdn, arena, extents, lead);
         }
         if (trail != NULL) {
             extent_deactivate(tsdn, arena, extents, trail);
         }
         return extent;
     } else {
         /*
          * We should have picked an extent that was large enough to
          * fulfill our allocation request.
          */
         assert(result == extent_split_interior_error);
         if (to_salvage != NULL) {
             extent_deregister(tsdn, to_salvage);
         }
         if (to_leak != NULL) {
             void *leak = extent_base_get(to_leak);
             extent_deregister_no_gdump_sub(tsdn, to_leak);
             extents_abandon_vm(tsdn, arena, r_extent_hooks, extents,
                 to_leak, growing_retained);
             assert(extent_lock_from_addr(tsdn, rtree_ctx, leak,
                 false) == NULL);
         }
         return NULL;
     }
     unreachable();
 }
References arena, assert(), extent_base_get(), extent_deactivate(), extent_deregister(), extent_deregister_no_gdump_sub(), extent_lock_from_addr(), extent_split_interior(), extent_split_interior_error, extent_split_interior_ok, extents_abandon_vm(), maps_coalesce, NULL, opt_retain, and unreachable.
Referenced by extent_recycle().
extent_register()
static bool extent_register (tsdn_t * tsdn, extent_t * extent) static
Definition at line 815 of file extent.c.
{
     return extent_register_impl(tsdn, extent, true);
 }
References extent_register_impl().
Referenced by extent_alloc_wrapper_hard(), extent_dalloc_gap(), and extent_reregister().
extent_register_impl()
static bool extent_register_impl (tsdn_t * tsdn, extent_t * extent, bool gdump_add) static
Definition at line 781 of file extent.c.
{
     rtree_ctx_t rtree_ctx_fallback;
     rtree_ctx_t *rtree_ctx = tsdn_rtree_ctx(tsdn, &rtree_ctx_fallback);
     rtree_leaf_elm_t *elm_a, *elm_b;
     /*
      * We need to hold the lock to protect against a concurrent coalesce
      * operation that sees us in a partial state.
      */
     extent_lock(tsdn, extent);
     if (extent_rtree_leaf_elms_lookup(tsdn, rtree_ctx, extent, false, true,
         &elm_a, &elm_b)) {
         extent_unlock(tsdn, extent);
         return true;
     }
     szind_t szind = extent_szind_get_maybe_invalid(extent);
     bool slab = extent_slab_get(extent);
     extent_rtree_write_acquired(tsdn, elm_a, elm_b, extent, szind, slab);
     if (slab) {
         extent_interior_register(tsdn, rtree_ctx, extent, szind);
     }
     extent_unlock(tsdn, extent);
     if (config_prof && gdump_add) {
         extent_gdump_add(tsdn, extent);
     }
     return false;
 }
References config_prof, extent_gdump_add(), extent_interior_register(), extent_lock(), extent_rtree_leaf_elms_lookup(), extent_rtree_write_acquired(), extent_slab_get(), extent_szind_get_maybe_invalid(), extent_unlock(), and tsdn_rtree_ctx().
Referenced by extent_register(), and extent_register_no_gdump_add().
extent_register_no_gdump_add()
static bool extent_register_no_gdump_add (tsdn_t * tsdn, extent_t * extent) static
Definition at line 820 of file extent.c.
{
     return extent_register_impl(tsdn, extent, false);
 }
References extent_register_impl().
Referenced by extent_grow_retained().
extent_reregister()
static void extent_reregister (tsdn_t * tsdn, extent_t * extent) static
Definition at line 825 of file extent.c.
{
     bool err = extent_register(tsdn, extent);
     assert(!err);
 }
References assert(), and extent_register().
Referenced by extent_dalloc_wrapper().
extent_rtree_leaf_elm_try_lock()
static lock_result_t extent_rtree_leaf_elm_try_lock (tsdn_t * tsdn, rtree_leaf_elm_t * elm, extent_t ** result, bool inactive_only) static
Definition at line 130 of file extent.c.
{
     extent_t *extent1 = rtree_leaf_elm_extent_read(tsdn, &extents_rtree,
         elm, true);
     /* Slab implies active extents and should be skipped. */
     if (extent1 == NULL || (inactive_only && rtree_leaf_elm_slab_read(tsdn,
         &extents_rtree, elm, true))) {
         return lock_result_no_extent;
     }
     /*
      * It's possible that the extent changed out from under us, and with it
      * the leaf->extent mapping.  We have to recheck while holding the lock.
      */
     extent_lock(tsdn, extent1);
     extent_t *extent2 = rtree_leaf_elm_extent_read(tsdn,
         &extents_rtree, elm, true);
     if (extent1 == extent2) {
         *result = extent1;
         return lock_result_success;
     } else {
         extent_unlock(tsdn, extent1);
         return lock_result_failure;
     }
 }
References extent_lock(), extent_unlock(), extents_rtree, NULL, rtree_leaf_elm_extent_read(), and rtree_leaf_elm_slab_read().
Referenced by extent_lock_from_addr().
extent_rtree_leaf_elms_lookup()
static bool extent_rtree_leaf_elms_lookup (tsdn_t * tsdn, rtree_ctx_t * rtree_ctx, const extent_t * extent, bool dependent, bool init_missing, rtree_leaf_elm_t ** r_elm_a, rtree_leaf_elm_t ** r_elm_b) static
Definition at line 700 of file extent.c.
{
     *r_elm_a = rtree_leaf_elm_lookup(tsdn, &extents_rtree, rtree_ctx,
         (uintptr_t)extent_base_get(extent), dependent, init_missing);
     if (!dependent && *r_elm_a == NULL) {
         return true;
     }
     assert(*r_elm_a != NULL);
     *r_elm_b = rtree_leaf_elm_lookup(tsdn, &extents_rtree, rtree_ctx,
         (uintptr_t)extent_last_get(extent), dependent, init_missing);
     if (!dependent && *r_elm_b == NULL) {
         return true;
     }
     assert(*r_elm_b != NULL);
     return false;
 }
References assert(), extent_base_get(), extent_last_get(), extents_rtree, NULL, and rtree_leaf_elm_lookup().
Referenced by extent_deregister_impl(), extent_merge_impl(), extent_register_impl(), and extent_split_impl().
extent_rtree_write_acquired()
static void extent_rtree_write_acquired (tsdn_t * tsdn, rtree_leaf_elm_t * elm_a, rtree_leaf_elm_t * elm_b, extent_t * extent, szind_t szind, bool slab) static
Definition at line 721 of file extent.c.
{
     rtree_leaf_elm_write(tsdn, &extents_rtree, elm_a, extent, szind, slab);
     if (elm_b != NULL) {
         rtree_leaf_elm_write(tsdn, &extents_rtree, elm_b, extent, szind,
             slab);
     }
 }
References extents_rtree, NULL, and rtree_leaf_elm_write().
Referenced by extent_deregister_impl(), extent_merge_impl(), extent_register_impl(), and extent_split_impl().
extent_size_quantize_ceil()
static size_t extent_size_quantize_ceil (size_t size) static
Definition at line 259 of file extent.c.
{
     size_t ret;
     assert(size > 0);
     assert(size - sz_large_pad <= SC_LARGE_MAXCLASS);
     assert((size & PAGE_MASK) == 0);
     ret = extent_size_quantize_floor(size);
     if (ret < size) {
         /*
          * Skip a quantization that may have an adequately large extent,
          * because under-sized extents may be mixed in.  This only
          * happens when an unusual size is requested, i.e. for aligned
          * allocation, and is just one of several places where linear
          * search would potentially find sufficiently aligned available
          * memory somewhere lower.
          */
         ret = sz_pind2sz(sz_psz2ind(ret - sz_large_pad + 1)) +
             sz_large_pad;
     }
     return ret;
 }
References assert(), extent_size_quantize_floor(), PAGE_MASK, ret, SC_LARGE_MAXCLASS, sz_large_pad, sz_pind2sz(), and sz_psz2ind().
Referenced by extents_first_fit_locked(), and extents_fit_alignment().
extent_size_quantize_floor()
static size_t extent_size_quantize_floor (size_t size) static
Definition at line 233 of file extent.c.
{
     size_t ret;
     pszind_t pind;
     assert(size > 0);
     assert((size & PAGE_MASK) == 0);
     pind = sz_psz2ind(size - sz_large_pad + 1);
     if (pind == 0) {
         /*
          * Avoid underflow.  This short-circuit would also do the right
          * thing for all sizes in the range for which there are
          * PAGE-spaced size classes, but it's simplest to just handle
          * the one case that would cause erroneous results.
          */
         return size;
     }
     ret = sz_pind2sz(pind - 1) + sz_large_pad;
     assert(ret <= size);
     return ret;
 }
References assert(), PAGE_MASK, ret, sz_large_pad, sz_pind2sz(), and sz_psz2ind().
Referenced by extent_size_quantize_ceil(), extents_insert_locked(), and extents_remove_locked().
extent_split_default()
static bool extent_split_default (extent_hooks_t * extent_hooks, void * addr, size_t size, size_t size_a, size_t size_b, bool committed, unsigned arena_ind) static
Definition at line 2067 of file extent.c.
{
     if (!maps_coalesce) {
         /*
          * Without retain, only whole regions can be purged (required by
          * MEM_RELEASE on Windows) -- therefore disallow splitting.  See
          * comments in extent_head_no_merge().
          */
         return !opt_retain;
     }
     return false;
 }
References maps_coalesce, and opt_retain.
extent_split_impl()
static extent_t * extent_split_impl (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extent_t * extent, size_t size_a, szind_t szind_a, bool slab_a, size_t size_b, szind_t szind_b, bool slab_b, bool growing_retained) static
Definition at line 2089 of file extent.c.
{
     assert(extent_size_get(extent) == size_a + size_b);
     witness_assert_depth_to_rank(tsdn_witness_tsdp_get(tsdn),
         WITNESS_RANK_CORE, growing_retained ? 1 : 0);
     extent_hooks_assure_initialized(arena, r_extent_hooks);
     if ((*r_extent_hooks)->split == NULL) {
         return NULL;
     }
     extent_t *trail = extent_alloc(tsdn, arena);
     if (trail == NULL) {
         goto label_error_a;
     }
     extent_init(trail, arena, (void *)((uintptr_t)extent_base_get(extent) +
         size_a), size_b, slab_b, szind_b, extent_sn_get(extent),
         extent_state_get(extent), extent_zeroed_get(extent),
         extent_committed_get(extent), extent_dumpable_get(extent),
         EXTENT_NOT_HEAD);
     rtree_ctx_t rtree_ctx_fallback;
     rtree_ctx_t *rtree_ctx = tsdn_rtree_ctx(tsdn, &rtree_ctx_fallback);
     rtree_leaf_elm_t *lead_elm_a, *lead_elm_b;
     {
         extent_t lead;
         extent_init(&lead, arena, extent_addr_get(extent), size_a,
             slab_a, szind_a, extent_sn_get(extent),
             extent_state_get(extent), extent_zeroed_get(extent),
             extent_committed_get(extent), extent_dumpable_get(extent),
             EXTENT_NOT_HEAD);
         extent_rtree_leaf_elms_lookup(tsdn, rtree_ctx, &lead, false,
             true, &lead_elm_a, &lead_elm_b);
     }
     rtree_leaf_elm_t *trail_elm_a, *trail_elm_b;
     extent_rtree_leaf_elms_lookup(tsdn, rtree_ctx, trail, false, true,
         &trail_elm_a, &trail_elm_b);
     if (lead_elm_a == NULL || lead_elm_b == NULL || trail_elm_a == NULL
         || trail_elm_b == NULL) {
         goto label_error_b;
     }
     extent_lock2(tsdn, extent, trail);
     if (*r_extent_hooks != &extent_hooks_default) {
         extent_hook_pre_reentrancy(tsdn, arena);
     }
     bool err = (*r_extent_hooks)->split(*r_extent_hooks, extent_base_get(extent),
         size_a + size_b, size_a, size_b, extent_committed_get(extent),
         arena_ind_get(arena));
     if (*r_extent_hooks != &extent_hooks_default) {
         extent_hook_post_reentrancy(tsdn);
     }
     if (err) {
         goto label_error_c;
     }
     extent_size_set(extent, size_a);
     extent_szind_set(extent, szind_a);
     extent_rtree_write_acquired(tsdn, lead_elm_a, lead_elm_b, extent,
         szind_a, slab_a);
     extent_rtree_write_acquired(tsdn, trail_elm_a, trail_elm_b, trail,
         szind_b, slab_b);
     extent_unlock2(tsdn, extent, trail);
     return trail;
 label_error_c:
     extent_unlock2(tsdn, extent, trail);
 label_error_b:
     extent_dalloc(tsdn, arena, trail);
 label_error_a:
     return NULL;
 }
References arena, arena_ind_get(), assert(), extent_addr_get(), extent_alloc(), extent_base_get(), extent_committed_get(), extent_dalloc(), extent_dumpable_get(), extent_hook_post_reentrancy(), extent_hook_pre_reentrancy(), extent_hooks_assure_initialized(), extent_hooks_default, extent_init(), extent_lock2(), EXTENT_NOT_HEAD, extent_rtree_leaf_elms_lookup(), extent_rtree_write_acquired(), extent_size_get(), extent_size_set(), extent_sn_get(), extent_state_get(), extent_szind_set(), extent_unlock2(), extent_zeroed_get(), NULL, tsdn_rtree_ctx(), witness_assert_depth_to_rank(), and WITNESS_RANK_CORE.
Referenced by extent_split_interior(), and extent_split_wrapper().
extent_split_interior()
static extent_split_interior_result_t extent_split_interior (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, rtree_ctx_t * rtree_ctx, extent_t ** extent, extent_t ** lead, extent_t ** trail, extent_t ** to_leak, extent_t ** to_salvage, void * new_addr, size_t size, size_t pad, size_t alignment, bool slab, szind_t szind, bool growing_retained) static
Definition at line 980 of file extent.c.
{
     size_t esize = size + pad;
     size_t leadsize = ALIGNMENT_CEILING((uintptr_t)extent_base_get(*extent),
         PAGE_CEILING(alignment)) - (uintptr_t)extent_base_get(*extent);
     assert(new_addr == NULL || leadsize == 0);
     if (extent_size_get(*extent) < leadsize + esize) {
         return extent_split_interior_cant_alloc;
     }
     size_t trailsize = extent_size_get(*extent) - leadsize - esize;
     *lead = NULL;
     *trail = NULL;
     *to_leak = NULL;
     *to_salvage = NULL;
     /* Split the lead. */
     if (leadsize != 0) {
         *lead = *extent;
         *extent = extent_split_impl(tsdn, arena, r_extent_hooks,
             *lead, leadsize, SC_NSIZES, false, esize + trailsize, szind,
             slab, growing_retained);
         if (*extent == NULL) {
             *to_leak = *lead;
             *lead = NULL;
             return extent_split_interior_error;
         }
     }
     /* Split the trail. */
     if (trailsize != 0) {
         *trail = extent_split_impl(tsdn, arena, r_extent_hooks, *extent,
             esize, szind, slab, trailsize, SC_NSIZES, false,
             growing_retained);
         if (*trail == NULL) {
             *to_leak = *extent;
             *to_salvage = *lead;
             *lead = NULL;
             *extent = NULL;
             return extent_split_interior_error;
         }
     }
     if (leadsize == 0 && trailsize == 0) {
         /*
          * Splitting causes szind to be set as a side effect, but no
          * splitting occurred.
          */
         extent_szind_set(*extent, szind);
         if (szind != SC_NSIZES) {
             rtree_szind_slab_update(tsdn, &extents_rtree, rtree_ctx,
                 (uintptr_t)extent_addr_get(*extent), szind, slab);
             if (slab && extent_size_get(*extent) > PAGE) {
                 rtree_szind_slab_update(tsdn, &extents_rtree,
                     rtree_ctx,
                     (uintptr_t)extent_past_get(*extent) -
                     (uintptr_t)PAGE, szind, slab);
             }
         }
     }
     return extent_split_interior_ok;
 }
References ALIGNMENT_CEILING, arena, assert(), extent_addr_get(), extent_base_get(), extent_past_get(), extent_size_get(), extent_split_impl(), extent_split_interior_cant_alloc, extent_split_interior_error, extent_split_interior_ok, extent_szind_set(), extents_rtree, NULL, PAGE, PAGE_CEILING, rtree_szind_slab_update(), SC_NSIZES, and uintptr_t.
Referenced by extent_grow_retained(), and extent_recycle_split().
extent_split_wrapper()
extent_t* extent_split_wrapper (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extent_t * extent, size_t size_a, szind_t szind_a, bool slab_a, size_t size_b, szind_t szind_b, bool slab_b)
Definition at line 2173 of file extent.c.
{
     return extent_split_impl(tsdn, arena, r_extent_hooks, extent, size_a,
         szind_a, slab_a, size_b, szind_b, slab_b, false);
 }
References arena, and extent_split_impl().
extent_try_coalesce()
static extent_t * extent_try_coalesce (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, rtree_ctx_t * rtree_ctx, extents_t * extents, extent_t * extent, bool * coalesced, bool growing_retained) static
Definition at line 1672 of file extent.c.
{
     return extent_try_coalesce_impl(tsdn, arena, r_extent_hooks, rtree_ctx,
         extents, extent, coalesced, growing_retained, false);
 }
References arena, and extent_try_coalesce_impl().
Referenced by extent_record(), and extent_try_delayed_coalesce().
extent_try_coalesce_impl()
static extent_t* extent_try_coalesce_impl (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, rtree_ctx_t * rtree_ctx, extents_t * extents, extent_t * extent, bool * coalesced, bool growing_retained, bool inactive_only) static
Definition at line 1600 of file extent.c.
{
     /*
      * We avoid checking / locking inactive neighbors for large size
      * classes, since they are eagerly coalesced on deallocation which can
      * cause lock contention.
      */
     /*
      * Continue attempting to coalesce until failure, to protect against
      * races with other threads that are thwarted by this one.
      */
     bool again;
     do {
         again = false;
         /* Try to coalesce forward. */
         extent_t *next = extent_lock_from_addr(tsdn, rtree_ctx,
             extent_past_get(extent), inactive_only);
         if (next != NULL) {
             /*
              * extents->mtx only protects against races for
              * like-state extents, so call extent_can_coalesce()
              * before releasing next's pool lock.
              */
             bool can_coalesce = extent_can_coalesce(arena, extents,
                 extent, next);
             extent_unlock(tsdn, next);
             if (can_coalesce && !extent_coalesce(tsdn, arena,
                 r_extent_hooks, extents, extent, next, true,
                 growing_retained)) {
                 if (extents->delay_coalesce) {
                     /* Do minimal coalescing. */
                     *coalesced = true;
                     return extent;
                 }
                 again = true;
             }
         }
         /* Try to coalesce backward. */
         extent_t *prev = extent_lock_from_addr(tsdn, rtree_ctx,
             extent_before_get(extent), inactive_only);
         if (prev != NULL) {
             bool can_coalesce = extent_can_coalesce(arena, extents,
                 extent, prev);
             extent_unlock(tsdn, prev);
             if (can_coalesce && !extent_coalesce(tsdn, arena,
                 r_extent_hooks, extents, extent, prev, false,
                 growing_retained)) {
                 extent = prev;
                 if (extents->delay_coalesce) {
                     /* Do minimal coalescing. */
                     *coalesced = true;
                     return extent;
                 }
                 again = true;
             }
         }
     } while (again);
     if (extents->delay_coalesce) {
         *coalesced = false;
     }
     return extent;
 }
References arena, extents_s::delay_coalesce, extent_before_get(), extent_can_coalesce(), extent_coalesce(), extent_lock_from_addr(), extent_past_get(), extent_unlock(), next(), NULL, and prev().
Referenced by extent_try_coalesce(), and extent_try_coalesce_large().
extent_try_coalesce_large()
static extent_t* extent_try_coalesce_large (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, rtree_ctx_t * rtree_ctx, extents_t * extents, extent_t * extent, bool * coalesced, bool growing_retained) static
Definition at line 1680 of file extent.c.
{
     return extent_try_coalesce_impl(tsdn, arena, r_extent_hooks, rtree_ctx,
         extents, extent, coalesced, growing_retained, true);
 }
References arena, and extent_try_coalesce_impl().
Referenced by extent_record().
extent_try_delayed_coalesce()
static bool extent_try_delayed_coalesce (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, rtree_ctx_t * rtree_ctx, extents_t * extents, extent_t * extent) static
Definition at line 520 of file extent.c.
                       {
     extent_state_set(extent, extent_state_active);
     bool coalesced;
     extent = extent_try_coalesce(tsdn, arena, r_extent_hooks, rtree_ctx,
         extents, extent, &coalesced, false);
     extent_state_set(extent, extents_state_get(extents));
     if (!coalesced) {
         return true;
     }
     extents_insert_locked(tsdn, extents, extent);
     return false;
 }
References arena, extent_state_active, extent_state_set(), extent_try_coalesce(), extents_insert_locked(), and extents_state_get().
Referenced by extents_evict().
extent_util_stats_get()
void extent_util_stats_get (tsdn_t * tsdn, const void * ptr, size_t * nfree, size_t * nregs, size_t * size)
Definition at line 2337 of file extent.c.
{
     assert(ptr != NULL && nfree != NULL && nregs != NULL && size != NULL);
     const extent_t *extent = iealloc(tsdn, ptr);
     if (unlikely(extent == NULL)) {
         *nfree = *nregs = *size = 0;
         return;
     }
     *size = extent_size_get(extent);
     if (!extent_slab_get(extent)) {
         *nfree = 0;
         *nregs = 1;
     } else {
         *nfree = extent_nfree_get(extent);
         *nregs = bin_infos[extent_szind_get(extent)].nregs;
         assert(*nfree <= *nregs);
         assert(*nfree * extent_usize_get(extent) <= *size);
     }
 }
References assert(), bin_infos, extent_nfree_get(), extent_size_get(), extent_slab_get(), extent_szind_get(), extent_usize_get(), iealloc(), NULL, ptr(), and unlikely.
extent_util_stats_verbose_get()
void extent_util_stats_verbose_get (tsdn_t * tsdn, const void * ptr, size_t * nfree, size_t * nregs, size_t * size, size_t * bin_nfree, size_t * bin_nregs, void ** slabcur_addr)
Definition at line 2360 of file extent.c.
{
     assert(ptr != NULL && nfree != NULL && nregs != NULL && size != NULL
         && bin_nfree != NULL && bin_nregs != NULL && slabcur_addr != NULL);
     const extent_t *extent = iealloc(tsdn, ptr);
     if (unlikely(extent == NULL)) {
         *nfree = *nregs = *size = *bin_nfree = *bin_nregs = 0;
         *slabcur_addr = NULL;
         return;
     }
     *size = extent_size_get(extent);
     if (!extent_slab_get(extent)) {
         *nfree = *bin_nfree = *bin_nregs = 0;
         *nregs = 1;
         *slabcur_addr = NULL;
         return;
     }
     *nfree = extent_nfree_get(extent);
     const szind_t szind = extent_szind_get(extent);
     *nregs = bin_infos[szind].nregs;
     assert(*nfree <= *nregs);
     assert(*nfree * extent_usize_get(extent) <= *size);
     const arena_t *arena = extent_arena_get(extent);
     assert(arena != NULL);
     const unsigned binshard = extent_binshard_get(extent);
     bin_t *bin = &arena->bins[szind].bin_shards[binshard];
     malloc_mutex_lock(tsdn, &bin->lock);
     if (config_stats) {
         *bin_nregs = *nregs * bin->stats.curslabs;
         assert(*bin_nregs >= bin->stats.curregs);
         *bin_nfree = *bin_nregs - bin->stats.curregs;
     } else {
         *bin_nfree = *bin_nregs = 0;
     }
     *slabcur_addr = extent_addr_get(bin->slabcur);
     assert(*slabcur_addr != NULL);
     malloc_mutex_unlock(tsdn, &bin->lock);
 }
References arena, assert(), bin_infos, bins_s::bin_shards, arena_s::bins, config_stats, bin_stats_s::curregs, bin_stats_s::curslabs, extent_addr_get(), extent_arena_get(), extent_binshard_get(), extent_nfree_get(), extent_size_get(), extent_slab_get(), extent_szind_get(), extent_usize_get(), iealloc(), bin_s::lock, malloc_mutex_lock(), malloc_mutex_unlock(), NULL, ptr(), bin_s::slabcur, bin_s::stats, and unlikely.
extents_abandon_vm()
static void extents_abandon_vm (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extents_t * extents, extent_t * extent, bool growing_retained) static
Definition at line 635 of file extent.c.
{
     size_t sz = extent_size_get(extent);
     if (config_stats) {
         arena_stats_accum_zu(&arena->stats.abandoned_vm, sz);
     }
     /*
      * Leak extent after making sure its pages have already been purged, so
      * that this is only a virtual memory leak.
      */
     if (extents_state_get(extents) == extent_state_dirty) {
         if (extent_purge_lazy_impl(tsdn, arena, r_extent_hooks,
             extent, 0, sz, growing_retained)) {
             extent_purge_forced_impl(tsdn, arena, r_extent_hooks,
                 extent, 0, extent_size_get(extent),
                 growing_retained);
         }
     }
     extent_dalloc(tsdn, arena, extent);
 }
References arena_stats_s::abandoned_vm, arena, arena_stats_accum_zu(), config_stats, extent_dalloc(), extent_purge_forced_impl(), extent_purge_lazy_impl(), extent_size_get(), extent_state_dirty, extents_state_get(), and arena_s::stats.
Referenced by extent_grow_retained(), and extent_recycle_split().
extents_alloc()
extent_t* extents_alloc (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extents_t * extents, void * new_addr, size_t size, size_t pad, size_t alignment, bool slab, szind_t szind, bool * zero, bool * commit)
Definition at line 537 of file extent.c.
{
     assert(size + pad != 0);
     assert(alignment != 0);
     witness_assert_depth_to_rank(tsdn_witness_tsdp_get(tsdn),
         WITNESS_RANK_CORE, 0);
     extent_t *extent = extent_recycle(tsdn, arena, r_extent_hooks, extents,
         new_addr, size, pad, alignment, slab, szind, zero, commit, false);
     assert(extent == NULL || extent_dumpable_get(extent));
     return extent;
 }
References arena, assert(), extent_dumpable_get(), extent_recycle(), NULL, witness_assert_depth_to_rank(), WITNESS_RANK_CORE, and G3D::zero().
extents_dalloc()
void extents_dalloc (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extents_t * extents, extent_t * extent)
Definition at line 552 of file extent.c.
{
     assert(extent_base_get(extent) != NULL);
     assert(extent_size_get(extent) != 0);
     assert(extent_dumpable_get(extent));
     witness_assert_depth_to_rank(tsdn_witness_tsdp_get(tsdn),
         WITNESS_RANK_CORE, 0);
     extent_addr_set(extent, extent_base_get(extent));
     extent_zeroed_set(extent, false);
     extent_record(tsdn, arena, r_extent_hooks, extents, extent, false);
 }
References arena, assert(), extent_addr_set(), extent_base_get(), extent_dumpable_get(), extent_record(), extent_size_get(), extent_zeroed_set(), NULL, witness_assert_depth_to_rank(), and WITNESS_RANK_CORE.
extents_evict()
extent_t* extents_evict (tsdn_t * tsdn, arena_t * arena, extent_hooks_t ** r_extent_hooks, extents_t * extents, size_t npages_min)
Definition at line 567 of file extent.c.
{
     rtree_ctx_t rtree_ctx_fallback;
     rtree_ctx_t *rtree_ctx = tsdn_rtree_ctx(tsdn, &rtree_ctx_fallback);
     malloc_mutex_lock(tsdn, &extents->mtx);
     /*
      * Get the LRU coalesced extent, if any.  If coalescing was delayed,
      * the loop will iterate until the LRU extent is fully coalesced.
      */
     extent_t *extent;
     while (true) {
         /* Get the LRU extent, if any. */
         extent = extent_list_first(&extents->lru);
         if (extent == NULL) {
             goto label_return;
         }
         /* Check the eviction limit. */
         size_t extents_npages = atomic_load_zu(&extents->npages,
             ATOMIC_RELAXED);
         if (extents_npages <= npages_min) {
             extent = NULL;
             goto label_return;
         }
         extents_remove_locked(tsdn, extents, extent);
         if (!extents->delay_coalesce) {
             break;
         }
         /* Try to coalesce. */
         if (extent_try_delayed_coalesce(tsdn, arena, r_extent_hooks,
             rtree_ctx, extents, extent)) {
             break;
         }
         /*
          * The LRU extent was just coalesced and the result placed in
          * the LRU at its neighbor's position.  Start over.
          */
     }
     /*
      * Either mark the extent active or deregister it to protect against
      * concurrent operations.
      */
     switch (extents_state_get(extents)) {
     case extent_state_active:
         not_reached();
     case extent_state_dirty:
     case extent_state_muzzy:
         extent_state_set(extent, extent_state_active);
         break;
     case extent_state_retained:
         extent_deregister(tsdn, extent);
         break;
     default:
         not_reached();
     }
 label_return:
     malloc_mutex_unlock(tsdn, &extents->mtx);
     return extent;
 }
References arena, ATOMIC_RELAXED, extents_s::delay_coalesce, extent_deregister(), extent_list_first(), extent_state_active, extent_state_dirty, extent_state_muzzy, extent_state_retained, extent_state_set(), extent_try_delayed_coalesce(), extents_remove_locked(), extents_state_get(), extents_s::lru, malloc_mutex_lock(), malloc_mutex_unlock(), extents_s::mtx, not_reached, extents_s::npages, NULL, and tsdn_rtree_ctx().
extents_first_fit_locked()
static extent_t* extents_first_fit_locked (tsdn_t * tsdn, arena_t * arena, extents_t * extents, size_t size) static
Definition at line 443 of file extent.c.
                  {
     extent_t *ret = NULL;
     pszind_t pind = sz_psz2ind(extent_size_quantize_ceil(size));
     if (!maps_coalesce && !opt_retain) {
         /*
          * No split / merge allowed (Windows w/o retain). Try exact fit
          * only.
          */
         return extent_heap_empty(&extents->heaps[pind]) ? NULL :
             extent_heap_first(&extents->heaps[pind]);
     }
     for (pszind_t i = (pszind_t)bitmap_ffu(extents->bitmap,
         &extents_bitmap_info, (size_t)pind);
         i < SC_NPSIZES + 1;
         i = (pszind_t)bitmap_ffu(extents->bitmap, &extents_bitmap_info,
         (size_t)i+1)) {
         assert(!extent_heap_empty(&extents->heaps[i]));
         extent_t *extent = extent_heap_first(&extents->heaps[i]);
         assert(extent_size_get(extent) >= size);
         /*
          * In order to reduce fragmentation, avoid reusing and splitting
          * large extents for much smaller sizes.
          *
          * Only do check for dirty extents (delay_coalesce).
          */
         if (extents->delay_coalesce &&
             (sz_pind2sz(i) >> opt_lg_extent_max_active_fit) > size) {
             break;
         }
         if (ret == NULL || extent_snad_comp(extent, ret) < 0) {
             ret = extent;
         }
         if (i == SC_NPSIZES) {
             break;
         }
         assert(i < SC_NPSIZES);
     }
     return ret;
 }
References assert(), extents_s::bitmap, bitmap_ffu(), extents_s::delay_coalesce, extent_heap_empty, extent_heap_first, extent_size_get(), extent_size_quantize_ceil(), extent_snad_comp(), extents_bitmap_info, extents_s::heaps, maps_coalesce, NULL, opt_lg_extent_max_active_fit, opt_retain, ret, SC_NPSIZES, sz_pind2sz(), and sz_psz2ind().
Referenced by extents_fit_locked().
extents_fit_alignment()
static extent_t* extents_fit_alignment (extents_t * extents, size_t min_size, size_t max_size, size_t alignment) static
Definition at line 406 of file extent.c.
                       {
         pszind_t pind = sz_psz2ind(extent_size_quantize_ceil(min_size));
         pszind_t pind_max = sz_psz2ind(extent_size_quantize_ceil(max_size));
     for (pszind_t i = (pszind_t)bitmap_ffu(extents->bitmap,
         &extents_bitmap_info, (size_t)pind); i < pind_max; i =
         (pszind_t)bitmap_ffu(extents->bitmap, &extents_bitmap_info,
         (size_t)i+1)) {
         assert(i < SC_NPSIZES);
         assert(!extent_heap_empty(&extents->heaps[i]));
         extent_t *extent = extent_heap_first(&extents->heaps[i]);
         uintptr_t base = (uintptr_t)extent_base_get(extent);
         size_t candidate_size = extent_size_get(extent);
         assert(candidate_size >= min_size);
         uintptr_t next_align = ALIGNMENT_CEILING((uintptr_t)base,
             PAGE_CEILING(alignment));
         if (base > next_align || base + candidate_size <= next_align) {
             /* Overflow or not crossing the next alignment. */
             continue;
         }
         size_t leadsize = next_align - base;
         if (candidate_size - leadsize >= min_size) {
             return extent;
         }
     }
     return NULL;
 }
References ALIGNMENT_CEILING, assert(), extents_s::bitmap, bitmap_ffu(), extent_base_get(), extent_heap_empty, extent_heap_first, extent_size_get(), extent_size_quantize_ceil(), extents_bitmap_info, extents_s::heaps, NULL, PAGE_CEILING, SC_NPSIZES, sz_psz2ind(), and uintptr_t.
Referenced by extents_fit_locked().
extents_fit_locked()
static extent_t* extents_fit_locked (tsdn_t * tsdn, arena_t * arena, extents_t * extents, size_t esize, size_t alignment) static
Definition at line 493 of file extent.c.
{
     malloc_mutex_assert_owner(tsdn, &extents->mtx);
     size_t max_size = esize + PAGE_CEILING(alignment) - PAGE;
     /* Beware size_t wrap-around. */
     if (max_size < esize) {
         return NULL;
     }
     extent_t *extent =
         extents_first_fit_locked(tsdn, arena, extents, max_size);
     if (alignment > PAGE && extent == NULL) {
         /*
          * max_size guarantees the alignment requirement but is rather
          * pessimistic.  Next we try to satisfy the aligned allocation
          * with sizes in [esize, max_size).
          */
         extent = extents_fit_alignment(extents, esize, max_size,
             alignment);
     }
     return extent;
 }
References arena, extents_first_fit_locked(), extents_fit_alignment(), malloc_mutex_assert_owner(), extents_s::mtx, NULL, PAGE, and PAGE_CEILING.
Referenced by extent_recycle_extract().
extents_insert_locked()
static void extents_insert_locked (tsdn_t * tsdn, extents_t * extents, extent_t * extent) static
Definition at line 340 of file extent.c.
{
     malloc_mutex_assert_owner(tsdn, &extents->mtx);
     assert(extent_state_get(extent) == extents->state);
     size_t size = extent_size_get(extent);
     size_t psz = extent_size_quantize_floor(size);
     pszind_t pind = sz_psz2ind(psz);
     if (extent_heap_empty(&extents->heaps[pind])) {
         bitmap_unset(extents->bitmap, &extents_bitmap_info,
             (size_t)pind);
     }
     extent_heap_insert(&extents->heaps[pind], extent);
     if (config_stats) {
         extents_stats_add(extents, pind, size);
     }
     extent_list_append(&extents->lru, extent);
     size_t npages = size >> LG_PAGE;
     /*
      * All modifications to npages hold the mutex (as asserted above), so we
      * don't need an atomic fetch-add; we can get by with a load followed by
      * a store.
      */
     size_t cur_extents_npages =
         atomic_load_zu(&extents->npages, ATOMIC_RELAXED);
     atomic_store_zu(&extents->npages, cur_extents_npages + npages,
         ATOMIC_RELAXED);
 }
References assert(), ATOMIC_RELAXED, extents_s::bitmap, bitmap_unset(), config_stats, extent_heap_empty, extent_heap_insert, extent_list_append(), extent_size_get(), extent_size_quantize_floor(), extent_state_get(), extents_bitmap_info, extents_stats_add(), extents_s::heaps, LG_PAGE, extents_s::lru, malloc_mutex_assert_owner(), extents_s::mtx, extents_s::npages, extents_s::state, and sz_psz2ind().
Referenced by extent_deactivate_locked(), and extent_try_delayed_coalesce().
extents_nbytes_get()
size_t extents_nbytes_get (extents_t * extents, pszind_t pind)
Definition at line 319 of file extent.c.
{
     return atomic_load_zu(&extents->nbytes[pind], ATOMIC_RELAXED);
 }
References ATOMIC_RELAXED, and extents_s::nbytes.
extents_nextents_get()
size_t extents_nextents_get (extents_t * extents, pszind_t pind)
Definition at line 314 of file extent.c.
{
     return atomic_load_zu(&extents->nextents[pind], ATOMIC_RELAXED);
 }
References ATOMIC_RELAXED, and extents_s::nextents.
extents_npages_get()
size_t extents_npages_get (extents_t * extents)
Definition at line 309 of file extent.c.
{
     return atomic_load_zu(&extents->npages, ATOMIC_RELAXED);
 }
References ATOMIC_RELAXED, and extents_s::npages.
extents_postfork_child()
void extents_postfork_child (tsdn_t * tsdn, extents_t * extents)
Definition at line 667 of file extent.c.
{
     malloc_mutex_postfork_child(tsdn, &extents->mtx);
 }
References malloc_mutex_postfork_child, and extents_s::mtx.
extents_postfork_parent()
void extents_postfork_parent (tsdn_t * tsdn, extents_t * extents)
Definition at line 662 of file extent.c.
{
     malloc_mutex_postfork_parent(tsdn, &extents->mtx);
 }
References malloc_mutex_postfork_parent, and extents_s::mtx.
extents_prefork()
void extents_prefork (tsdn_t * tsdn, extents_t * extents)
Definition at line 657 of file extent.c.
{
     malloc_mutex_prefork(tsdn, &extents->mtx);
 }
References malloc_mutex_prefork, and extents_s::mtx.
extents_remove_locked()
static void extents_remove_locked (tsdn_t * tsdn, extents_t * extents, extent_t * extent) static
Definition at line 371 of file extent.c.
{
     malloc_mutex_assert_owner(tsdn, &extents->mtx);
     assert(extent_state_get(extent) == extents->state);
     size_t size = extent_size_get(extent);
     size_t psz = extent_size_quantize_floor(size);
     pszind_t pind = sz_psz2ind(psz);
     extent_heap_remove(&extents->heaps[pind], extent);
     if (config_stats) {
         extents_stats_sub(extents, pind, size);
     }
     if (extent_heap_empty(&extents->heaps[pind])) {
         bitmap_set(extents->bitmap, &extents_bitmap_info,
             (size_t)pind);
     }
     extent_list_remove(&extents->lru, extent);
     size_t npages = size >> LG_PAGE;
     /*
      * As in extents_insert_locked, we hold extents->mtx and so don't need
      * atomic operations for updating extents->npages.
      */
     size_t cur_extents_npages =
         atomic_load_zu(&extents->npages, ATOMIC_RELAXED);
     assert(cur_extents_npages >= npages);
     atomic_store_zu(&extents->npages,
         cur_extents_npages - (size >> LG_PAGE), ATOMIC_RELAXED);
 }
References assert(), ATOMIC_RELAXED, extents_s::bitmap, bitmap_set(), config_stats, extent_heap_empty, extent_heap_remove, extent_list_remove(), extent_size_get(), extent_size_quantize_floor(), extent_state_get(), extents_bitmap_info, extents_stats_sub(), extents_s::heaps, LG_PAGE, extents_s::lru, malloc_mutex_assert_owner(), extents_s::mtx, extents_s::npages, extents_s::state, and sz_psz2ind().
Referenced by extent_activate_locked(), and extents_evict().
extents_state_get()
extent_state_t extents_state_get (const extents_t * extents)
Definition at line 304 of file extent.c.
{
     return extents->state;
 }
References extents_s::state.
Referenced by extent_activate_locked(), extent_deactivate_locked(), extent_record(), extent_recycle_extract(), extent_try_delayed_coalesce(), extents_abandon_vm(), and extents_evict().
extents_stats_add()
static void extents_stats_add (extents_t * extent, pszind_t pind, size_t sz) static
Definition at line 324 of file extent.c.
{
     size_t cur = atomic_load_zu(&extent->nextents[pind], ATOMIC_RELAXED);
     atomic_store_zu(&extent->nextents[pind], cur + 1, ATOMIC_RELAXED);
     cur = atomic_load_zu(&extent->nbytes[pind], ATOMIC_RELAXED);
     atomic_store_zu(&extent->nbytes[pind], cur + sz, ATOMIC_RELAXED);
 }
References ATOMIC_RELAXED, extents_s::nbytes, and extents_s::nextents.
Referenced by extents_insert_locked().
extents_stats_sub()
static void extents_stats_sub (extents_t * extent, pszind_t pind, size_t sz) static
Definition at line 332 of file extent.c.
{
     size_t cur = atomic_load_zu(&extent->nextents[pind], ATOMIC_RELAXED);
     atomic_store_zu(&extent->nextents[pind], cur - 1, ATOMIC_RELAXED);
     cur = atomic_load_zu(&extent->nbytes[pind], ATOMIC_RELAXED);
     atomic_store_zu(&extent->nbytes[pind], cur - sz, ATOMIC_RELAXED);
 }
References ATOMIC_RELAXED, extents_s::nbytes, and extents_s::nextents.
Referenced by extents_remove_locked().
ph_gen() [1/2]
ph_gen (ATTR_NONE , extent_avail_ , extent_tree_t , extent_t , ph_link , extent_esnead_comp)
Definition at line 118 of file extent.c.
              {
     lock_result_success,
     lock_result_failure,
     lock_result_no_extent
 } lock_result_t;
ph_gen() [2/2]
ph_gen (extent_heap_ , extent_heap_t , extent_t , ph_link , extent_snad_comp)
Definition at line 283 of file extent.c.
{
     if (malloc_mutex_init(&extents->mtx, "extents", WITNESS_RANK_EXTENTS,
         malloc_mutex_rank_exclusive)) {
         return true;
     }
     for (unsigned i = 0; i < SC_NPSIZES + 1; i++) {
         extent_heap_new(&extents->heaps[i]);
     }
     bitmap_init(extents->bitmap, &extents_bitmap_info, true);
     extent_list_init(&extents->lru);
     atomic_store_zu(&extents->npages, 0, ATOMIC_RELAXED);
     extents->state = state;
     extents->delay_coalesce = delay_coalesce;
     return false;
 }
References ATOMIC_RELAXED, extents_s::bitmap, bitmap_init, extents_s::delay_coalesce, extent_heap_new, extent_list_init(), extents_bitmap_info, extents_s::heaps, extents_s::lru, malloc_mutex_init, malloc_mutex_rank_exclusive, extents_s::mtx, extents_s::npages, SC_NPSIZES, extents_s::state, and WITNESS_RANK_EXTENTS.
Variable Documentation
curpages
atomic_zu_t curpages static
Definition at line 93 of file extent.c.
Referenced by extent_gdump_add(), and extent_gdump_sub().
extent_hooks_default
const extent_hooks_t extent_hooks_default
Initial value:
= {
    extent_alloc_default,
    extent_dalloc_default,
    extent_destroy_default,
    extent_commit_default,
    extent_decommit_default
    ,
    NULL
    ,
    NULL
    ,
    extent_split_default,
    extent_merge_default
}
Definition at line 67 of file extent.c.
Referenced by extent_alloc_wrapper_hard(), extent_commit_impl(), extent_dalloc_wrapper(), extent_dalloc_wrapper_try(), extent_decommit_wrapper(), extent_destroy_wrapper(), extent_grow_retained(), extent_merge_impl(), extent_purge_forced_impl(), extent_purge_lazy_impl(), and extent_split_impl().
extent_mutex_pool
mutex_pool_t extent_mutex_pool
Definition at line 18 of file extent.c.
Referenced by extent_boot().
extents_bitmap_info
const bitmap_info_t extents_bitmap_info static
Initial value:
=
    BITMAP_INFO_INITIALIZER(SC_NPSIZES+1)
Definition at line 22 of file extent.c.
Referenced by extents_first_fit_locked(), extents_fit_alignment(), extents_insert_locked(), extents_remove_locked(), and ph_gen().
extents_rtree
rtree_t extents_rtree
Definition at line 16 of file extent.c.
Referenced by extent_boot(), extent_interior_deregister(), extent_interior_register(), extent_lock_from_addr(), extent_merge_impl(), extent_record(), extent_rtree_leaf_elm_try_lock(), extent_rtree_leaf_elms_lookup(), extent_rtree_write_acquired(), and extent_split_interior().
highpages
atomic_zu_t highpages static
Definition at line 94 of file extent.c.
Referenced by extent_gdump_add().
lock_result_t
lock_result_t
Definition at line 127 of file extent.c.
Referenced by extent_lock_from_addr().
opt_lg_extent_max_active_fit
size_t opt_lg_extent_max_active_fit = LG_EXTENT_MAX_ACTIVE_FIT_DEFAULT
Definition at line 20 of file extent.c.
Referenced by extents_first_fit_locked().