Azerotcore-wotlk: AuraEffect Class Reference
AuraEffect Class Reference
#include <SpellAuraEffects.h>
Public Member Functions
Unit * GetCaster () const
ObjectGuid GetCasterGUID () const
Aura * GetBase () const
void GetTargetList (std::list< Unit * > &targetList) const
void GetApplicationList (std::list< AuraApplication * > &applicationList) const
SpellModifier * GetSpellModifier () const
SpellInfo const * GetSpellInfo () const
uint32 GetId () const
uint32 GetEffIndex () const
int32 GetBaseAmount () const
int32 GetAmplitude () const
int32 GetMiscValueB () const
int32 GetMiscValue () const
AuraType GetAuraType () const
int32 GetAmount () const
int32 GetForcedAmount () const
void SetAmount (int32 amount)
int32 GetPeriodicTimer () const
void SetPeriodicTimer (int32 periodicTimer)
int32 CalculateAmount (Unit *caster)
void CalculatePeriodic (Unit *caster, bool create=false, bool load=false)
void CalculatePeriodicData ()
void CalculateSpellMod ()
void ChangeAmount (int32 newAmount, bool mark=true, bool onStackOrReapply=false)
void RecalculateAmount ()
void RecalculateAmount (Unit *caster)
bool CanBeRecalculated () const
void SetCanBeRecalculated (bool val)
void HandleEffect (AuraApplication *aurApp, uint8 mode, bool apply)
void HandleEffect (Unit *target, uint8 mode, bool apply)
void ApplySpellMod (Unit *target, bool apply)
void Update (uint32 diff, Unit *caster)
void UpdatePeriodic (Unit *caster)
uint32 GetTickNumber () const
int32 GetTotalTicks () const
void ResetPeriodic (bool resetPeriodicTimer=false)
void ResetTicks ()
bool IsPeriodic () const
void SetPeriodic (bool isPeriodic)
bool IsAffectedOnSpell (SpellInfo const *spell) const
bool HasSpellClassMask () const
void SendTickImmune (Unit *target, Unit *caster) const
void PeriodicTick (AuraApplication *aurApp, Unit *caster) const
void HandleProc (AuraApplication *aurApp, ProcEventInfo &eventInfo)
void CleanupTriggeredSpells (Unit *target)
void HandleShapeshiftBoosts (Unit *target, bool apply) const
float GetCritChance () const
void SetCritChance (float crit)
uint8 GetCasterLevel () const
bool CanApplyResilience () const
float GetPctMods () const
uint32 GetAuraGroup () const
int32 GetOldAmount () const
void SetOldAmount (int32 amount)
void SetEnabled (bool enabled)
void HandleNULL (AuraApplication const *, uint8, bool) const
void HandleUnused (AuraApplication const *, uint8, bool) const
void HandleNoImmediateEffect (AuraApplication const *, uint8, bool) const
void HandleModInvisibilityDetect (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModInvisibility (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModStealth (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModStealthLevel (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModStealthDetect (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleDetectAmore (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleSpiritOfRedemption (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraGhost (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandlePhase (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModShapeshift (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraTransform (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModScale (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraCloneCaster (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleFeignDeath (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModUnattackable (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModDisarm (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModSilence (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModPacify (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModPacifyAndSilence (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraAllowOnlyAbility (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraTrackResources (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraTrackCreatures (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraTrackStealthed (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModStalked (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraUntrackable (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModPetTalentsPoints (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModSkill (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraMounted (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraAllowFlight (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraWaterWalk (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraFeatherFall (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraHover (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleWaterBreathing (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleForceMoveForward (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModThreat (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModTotalThreat (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModTaunt (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModConfuse (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModFear (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModStun (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModRoot (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandlePreventFleeing (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModPossess (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModPossessPet (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModCharm (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleCharmConvert (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraControlVehicle (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModIncreaseSpeed (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModIncreaseMountedSpeed (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModIncreaseFlightSpeed (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModIncreaseSwimSpeed (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModDecreaseSpeed (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModUseNormalSpeed (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModStateImmunityMask (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModMechanicImmunity (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModEffectImmunity (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModStateImmunity (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModSchoolImmunity (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModDmgImmunity (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModDispelImmunity (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModResistanceExclusive (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModResistance (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModBaseResistancePCT (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModResistancePercent (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModBaseResistance (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModTargetResistance (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModStat (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModPercentStat (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModSpellDamagePercentFromStat (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModSpellHealingPercentFromStat (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModSpellDamagePercentFromAttackPower (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModSpellHealingPercentFromAttackPower (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModHealingDone (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModTotalPercentStat (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModResistenceOfStatPercent (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModExpertise (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModPowerRegen (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModPowerRegenPCT (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModManaRegen (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModIncreaseHealth (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModIncreaseMaxHealth (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModIncreaseEnergy (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModIncreaseEnergyPercent (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModIncreaseHealthPercent (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraIncreaseBaseHealthPercent (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModParryPercent (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModDodgePercent (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModBlockPercent (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModRegenInterrupt (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModWeaponCritPercent (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModHitChance (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModSpellHitChance (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModSpellCritChance (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModSpellCritChanceShool (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModCritPct (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModCastingSpeed (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModMeleeRangedSpeedPct (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModCombatSpeedPct (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModAttackSpeed (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModMeleeSpeedPct (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModRangedHaste (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleRangedAmmoHaste (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModRating (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModRatingFromStat (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModAttackPower (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModRangedAttackPower (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModAttackPowerPercent (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModRangedAttackPowerPercent (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModRangedAttackPowerOfStatPercent (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModAttackPowerOfStatPercent (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModAttackPowerOfArmor (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModDamageDone (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModDamagePercentDone (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModOffhandDamagePercent (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleShieldBlockValue (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModPowerCostPCT (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleModPowerCost (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleArenaPreparation (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleNoReagentUseAura (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraRetainComboPoints (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraDummy (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleChannelDeathItem (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleBindSight (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleFarSight (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleForceReaction (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraEmpathy (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModFaction (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleComprehendLanguage (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraConvertRune (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraLinked (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraOpenStable (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraModFakeInebriation (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraOverrideSpells (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandleAuraSetVehicle (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandlePreventResurrection (AuraApplication const *aurApp, uint8 mode, bool apply) const
void HandlePeriodicDummyAuraTick (Unit *target, Unit *caster) const
void HandlePeriodicTriggerSpellAuraTick (Unit *target, Unit *caster) const
void HandlePeriodicTriggerSpellWithValueAuraTick (Unit *target, Unit *caster) const
void HandlePeriodicDamageAurasTick (Unit *target, Unit *caster) const
void HandlePeriodicHealthLeechAuraTick (Unit *target, Unit *caster) const
void HandlePeriodicHealthFunnelAuraTick (Unit *target, Unit *caster) const
void HandlePeriodicHealAurasTick (Unit *target, Unit *caster) const
void HandlePeriodicManaLeechAuraTick (Unit *target, Unit *caster) const
void HandleObsModPowerAuraTick (Unit *target, Unit *caster) const
void HandlePeriodicEnergizeAuraTick (Unit *target, Unit *caster) const
void HandlePeriodicPowerBurnAuraTick (Unit *target, Unit *caster) const
void HandleProcTriggerSpellAuraProc (AuraApplication *aurApp, ProcEventInfo &eventInfo)
void HandleProcTriggerSpellWithValueAuraProc (AuraApplication *aurApp, ProcEventInfo &eventInfo)
void HandleProcTriggerDamageAuraProc (AuraApplication *aurApp, ProcEventInfo &eventInfo)
void HandleRaidProcFromChargeAuraProc (AuraApplication *aurApp, ProcEventInfo &eventInfo)
void HandleRaidProcFromChargeWithValueAuraProc (AuraApplication *aurApp, ProcEventInfo &eventInfo)
Private Member Functions
friend Aura::~Aura ()
~AuraEffect ()
AuraEffect (Aura *base, uint8 effIndex, int32 *baseAmount, Unit *caster)
float CalcPeriodicCritChance (Unit const *caster, Unit const *target) const
Private Attributes
Aura *const m_base
SpellInfo const *const m_spellInfo
int32 const m_baseAmount
bool m_applyResilience
uint8 m_casterLevel
int32 m_amount
float m_critChance
float m_pctMods
uint32 m_auraGroup
int32 m_oldAmount
bool m_isAuraEnabled
ChannelTargetData * m_channelData
SpellModifier * m_spellmod
int32 m_periodicTimer
int32 m_amplitude
uint32 m_tickNumber
uint8 const m_effIndex
bool m_canBeRecalculated
bool m_isPeriodic
Friends
void Aura::_InitEffects (uint8 effMask, Unit *caster, int32 *baseAmount)
Aura * Unit::_TryStackingOrRefreshingExistingAura (SpellInfo const *newAura, uint8 effMask, Unit *caster, int32 *baseAmount, Item *castItem, ObjectGuid casterGUID, bool noPeriodicReset)
Detailed Description
Definition at line 31 of file SpellAuraEffects.h.
Constructor & Destructor Documentation
Aura::~Aura()
AuraEffect::Aura::~Aura () private
~AuraEffect()
AuraEffect::~AuraEffect () private
Definition at line 404 of file SpellAuraEffects.cpp.
 {
     delete m_spellmod;
     delete m_channelData;
 }
References m_channelData, and m_spellmod.
AuraEffect()
AuraEffect::AuraEffect (Aura * base, uint8 effIndex, int32 * baseAmount, Unit * caster) explicit private
Definition at line 382 of file SpellAuraEffects.cpp.
                                                                                  :
     m_base(base), m_spellInfo(base->GetSpellInfo()),
     m_baseAmount(baseAmount ? * baseAmount : m_spellInfo->Effects[effIndex].BasePoints), m_critChance(0),
     m_oldAmount(0), m_isAuraEnabled(true), m_channelData(nullptr), m_spellmod(nullptr), m_periodicTimer(0), m_tickNumber(0), m_effIndex(effIndex),
     m_canBeRecalculated(true), m_isPeriodic(false)
 {
     CalculatePeriodic(caster, true, false);
     CalculatePeriodicData();
     m_amount = CalculateAmount(caster);
     m_casterLevel = caster ? caster->getLevel() : 0;
     m_applyResilience = caster && caster->CanApplyResilience();
     m_auraGroup = sSpellMgr->GetSpellGroup(GetId());
     CalculateSpellMod();
     // Xinef: channel data structure
     if (caster)
         if (Spell* spell = caster->GetCurrentSpell(CURRENT_CHANNELED_SPELL))
             m_channelData = new ChannelTargetData(caster->GetGuidValue(UNIT_FIELD_CHANNEL_OBJECT), spell->m_targets.HasDst() ? spell->m_targets.GetDst() : nullptr);
 }
References CalculateAmount(), CalculatePeriodic(), CalculatePeriodicData(), CalculateSpellMod(), Unit::CanApplyResilience(), CURRENT_CHANNELED_SPELL, Unit::GetCurrentSpell(), Object::GetGuidValue(), GetId(), Unit::getLevel(), m_amount, m_applyResilience, m_auraGroup, m_casterLevel, m_channelData, sSpellMgr, and UNIT_FIELD_CHANNEL_OBJECT.
Member Function Documentation
ApplySpellMod()
void AuraEffect::ApplySpellMod (Unit * target, bool apply)
Definition at line 791 of file SpellAuraEffects.cpp.
 {
     if (!m_spellmod || target->GetTypeId() != TYPEID_PLAYER)
         return;
     target->ToPlayer()->AddSpellMod(m_spellmod, apply);
     // Auras with charges do not mod amount of passive auras
     if (GetBase()->IsUsingCharges())
         return;
     // reapply some passive spells after add/remove related spellmods
     // Warning: it is a dead loop if 2 auras each other amount-shouldn't happen
     switch (GetMiscValue())
     {
         case SPELLMOD_ALL_EFFECTS:
         case SPELLMOD_EFFECT1:
         case SPELLMOD_EFFECT2:
         case SPELLMOD_EFFECT3:
             {
                 ObjectGuid guid = target->GetGUID();
                 Unit::AuraApplicationMap& auras = target->GetAppliedAuras();
                 for (Unit::AuraApplicationMap::iterator iter = auras.begin(); iter != auras.end(); ++iter)
                 {
                     Aura* aura = iter->second->GetBase();
                     // only passive and permament auras-active auras should have amount set on spellcast and not be affected
                     // if aura is casted by others, it will not be affected
                     if ((aura->IsPassive() || aura->IsPermanent()) && aura->GetCasterGUID() == guid && aura->GetSpellInfo()->IsAffectedBySpellMod(m_spellmod))
                     {
                         if (GetMiscValue() == SPELLMOD_ALL_EFFECTS)
{
                             for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
{
                                 if (AuraEffect* aurEff = aura->GetEffect(i))
                                     aurEff->RecalculateAmount();
                             }
                         }
                         else if (GetMiscValue() == SPELLMOD_EFFECT1)
{
                             if (AuraEffect* aurEff = aura->GetEffect(0))
                                 aurEff->RecalculateAmount();
                         }
                         else if (GetMiscValue() == SPELLMOD_EFFECT2)
{
                             if (AuraEffect* aurEff = aura->GetEffect(1))
                                 aurEff->RecalculateAmount();
                         }
                         else //if (modOp == SPELLMOD_EFFECT3)
{
                             if (AuraEffect* aurEff = aura->GetEffect(2))
                                 aurEff->RecalculateAmount();
                         }
                     }
                 }
                 Pet* pet = target->ToPlayer()->GetPet();
                 if (!pet)
                     break;
                 ObjectGuid petguid = pet->GetGUID();
                 Unit::AuraApplicationMap& petauras = pet->GetAppliedAuras();
                 for (Unit::AuraApplicationMap::iterator iter = petauras.begin(); iter != petauras.end(); ++iter)
                 {
                     Aura* aura = iter->second->GetBase();
                     // only passive auras-active auras should have amount set on spellcast and not be affected
                     // if aura is casted by others, it will not be affected
                     if ((aura->IsPassive() || aura->IsPermanent()) && aura->GetCasterGUID() == petguid && aura->GetSpellInfo()->IsAffectedBySpellMod(m_spellmod))
                     {
                         if (GetMiscValue() == SPELLMOD_ALL_EFFECTS)
{
                             for (uint8 i = 0; i < MAX_SPELL_EFFECTS; ++i)
{
                                 if (AuraEffect* aurEff = aura->GetEffect(i))
                                     aurEff->RecalculateAmount();
                             }
                         }
                         else if (GetMiscValue() == SPELLMOD_EFFECT1)
{
                             if (AuraEffect* aurEff = aura->GetEffect(0))
                                 aurEff->RecalculateAmount();
                         }
                         else if (GetMiscValue() == SPELLMOD_EFFECT2)
{
                             if (AuraEffect* aurEff = aura->GetEffect(1))
                                 aurEff->RecalculateAmount();
                         }
                         else //if (modOp == SPELLMOD_EFFECT3)
{
                             if (AuraEffect* aurEff = aura->GetEffect(2))
                                 aurEff->RecalculateAmount();
                         }
                     }
                 }
             }
         default:
             break;
     }
 }
References Player::AddSpellMod(), ByteConverter::apply(), Unit::GetAppliedAuras(), GetBase(), Aura::GetCasterGUID(), Aura::GetEffect(), Object::GetGUID(), GetMiscValue(), Player::GetPet(), Aura::GetSpellInfo(), Object::GetTypeId(), SpellInfo::IsAffectedBySpellMod(), Aura::IsPassive(), Aura::IsPermanent(), Aura::IsUsingCharges(), m_spellmod, MAX_SPELL_EFFECTS, SPELLMOD_ALL_EFFECTS, SPELLMOD_EFFECT1, SPELLMOD_EFFECT2, SPELLMOD_EFFECT3, Object::ToPlayer(), and TYPEID_PLAYER.
Referenced by HandleEffect().
CalcPeriodicCritChance()
float AuraEffect::CalcPeriodicCritChance (Unit const * caster, Unit const * target) const private
Definition at line 1029 of file SpellAuraEffects.cpp.
 {
     float critChance = 0.0f;
     if (caster)
     {
         if (Player* modOwner = caster->GetSpellModOwner())
         {
             Unit::AuraEffectList const& mPeriodicCritAuras = modOwner->GetAuraEffectsByType(SPELL_AURA_ABILITY_PERIODIC_CRIT);
             for (Unit::AuraEffectList::const_iterator itr = mPeriodicCritAuras.begin(); itr != mPeriodicCritAuras.end(); ++itr)
             {
                 if ((*itr)->IsAffectedOnSpell(GetSpellInfo()))
                 {
                     critChance = modOwner->SpellDoneCritChance(nullptr, GetSpellInfo(), GetSpellInfo()->GetSchoolMask(), (GetSpellInfo()->DmgClass == SPELL_DAMAGE_CLASS_RANGED ? RANGED_ATTACK : BASE_ATTACK), true);
                     break;
                 }
             }
             switch(GetSpellInfo()->SpellFamilyName)
             {
                 // Rupture - since 3.3.3 can crit
                 case SPELLFAMILY_ROGUE:
                     if (GetSpellInfo()->SpellFamilyFlags[0] & 0x100000)
                         critChance = modOwner->SpellDoneCritChance(nullptr, GetSpellInfo(), GetSpellInfo()->GetSchoolMask(), BASE_ATTACK, true);
                     break;
             }
         }
     }
     if (target && critChance > 0.0f)
         critChance = target->SpellTakenCritChance(caster, GetSpellInfo(), GetSpellInfo()->GetSchoolMask(), critChance, BASE_ATTACK, true);
     return std::max(0.0f, critChance);
 }
References BASE_ATTACK, GetSpellInfo(), Unit::GetSpellModOwner(), max, RANGED_ATTACK, SPELL_AURA_ABILITY_PERIODIC_CRIT, SPELL_DAMAGE_CLASS_RANGED, SPELLFAMILY_ROGUE, and Unit::SpellTakenCritChance().
Referenced by CalculatePeriodicData().
CalculateAmount()
int32 AuraEffect::CalculateAmount (Unit * caster)
Definition at line 451 of file SpellAuraEffects.cpp.
 {
     int32 amount;
     // default amount calculation
     amount = m_spellInfo->Effects[m_effIndex].CalcValue(caster, &m_baseAmount, nullptr);
     // check item enchant aura cast
     if (!amount && caster)
         if (ObjectGuid itemGUID = GetBase()->GetCastItemGUID())
             if (Player* playerCaster = caster->ToPlayer())
                 if (Item* castItem = playerCaster->GetItemByGuid(itemGUID))
                     if (castItem->GetItemSuffixFactor())
                     {
                         ItemRandomSuffixEntry const* item_rand_suffix = sItemRandomSuffixStore.LookupEntry(abs(castItem->GetItemRandomPropertyId()));
                         if (item_rand_suffix)
{
                             for (uint8 k = 0; k < MAX_ITEM_ENCHANTMENT_EFFECTS; k++)
{
                                 SpellItemEnchantmentEntry const* pEnchant = sSpellItemEnchantmentStore.LookupEntry(item_rand_suffix->Enchantment[k]);
                                 if (pEnchant)
{
                                     for (uint8 t = 0; t < MAX_SPELL_ITEM_ENCHANTMENT_EFFECTS; t++)
                                         if (pEnchant->spellid[t] == m_spellInfo->Id)
{
                                             amount = uint32((item_rand_suffix->AllocationPct[k] * castItem->GetItemSuffixFactor()) / 10000);
                                             break;
                                         }
                                 }
                                 if (amount)
                                     break;
                             }
                         }
                     }
     // custom amount calculations go here
     // xinef: normal auras
     switch (GetAuraType())
     {
         // crowd control auras
         case SPELL_AURA_MOD_CONFUSE:
         case SPELL_AURA_MOD_FEAR:
         case SPELL_AURA_MOD_STUN:
         case SPELL_AURA_MOD_ROOT:
         case SPELL_AURA_TRANSFORM:
             m_canBeRecalculated = false;
             if (!m_spellInfo->ProcFlags || m_spellInfo->HasAura(SPELL_AURA_PROC_TRIGGER_SPELL)) // xinef: skip auras with proctriggerspell, they must have procflags...
                 break;
             amount = int32(GetBase()->GetUnitOwner()->CountPctFromMaxHealth(10));
             if (caster)
             {
                 // Glyphs increasing damage cap
                 Unit::AuraEffectList const& overrideClassScripts = caster->GetAuraEffectsByType(SPELL_AURA_OVERRIDE_CLASS_SCRIPTS);
                 for (Unit::AuraEffectList::const_iterator itr = overrideClassScripts.begin(); itr != overrideClassScripts.end(); ++itr)
                 {
                     if ((*itr)->IsAffectedOnSpell(m_spellInfo))
                     {
                         // Glyph of Fear, Glyph of Frost nova and similar auras
                         if ((*itr)->GetMiscValue() == 7801)
{
                             AddPct(amount, (*itr)->GetAmount());
                             break;
                         }
                     }
                 }
             }
             break;
         case SPELL_AURA_SCHOOL_ABSORB:
         case SPELL_AURA_MANA_SHIELD:
             m_canBeRecalculated = false;
             break;
         case SPELL_AURA_MOD_DAMAGE_PERCENT_DONE:
             // Titan's Grip
             if (!caster)
                 break;
             if (GetId() == 49152 && caster->ToPlayer())
             {
                 Item* item1 = caster->ToPlayer()->GetWeaponForAttack(BASE_ATTACK);
                 Item* item2 = caster->ToPlayer()->GetWeaponForAttack(OFF_ATTACK);
                 if (item1 && item2 && (item1->GetTemplate()->InventoryType == INVTYPE_2HWEAPON || item2->GetTemplate()->InventoryType == INVTYPE_2HWEAPON))
                     amount = -10;
                 else
                     amount = 0;
             }
             break;
         default:
             break;
     }
     // xinef: save base amount, before calculating sp etc. Used for Unit::CastDelayedSpellWithPeriodicAmount
     SetOldAmount(amount * GetBase()->GetStackAmount());
     GetBase()->CallScriptEffectCalcAmountHandlers(this, amount, m_canBeRecalculated);
     // Xinef: Periodic auras
     if (caster)
         switch (GetAuraType())
         {
             case SPELL_AURA_PERIODIC_DAMAGE:
             case SPELL_AURA_PERIODIC_LEECH:
                 // xinef: save caster depending auras, always pass 1 as stack amount, effect will be multiplicated at the end of the function by correct value!
                 if (GetBase()->GetType() == UNIT_AURA_TYPE)
                     amount = caster->SpellDamageBonusDone(GetBase()->GetUnitOwner(), GetSpellInfo(), amount, DOT, GetPctMods(), 1);
                 break;
             case SPELL_AURA_PERIODIC_HEAL:
                 if (GetBase()->GetType() == UNIT_AURA_TYPE)
                     amount = caster->SpellHealingBonusDone(GetBase()->GetUnitOwner(), GetSpellInfo(), amount, DOT, GetPctMods(), 1);
                 break;
             case SPELL_AURA_DAMAGE_SHIELD:
                 if (GetBase()->GetType() == UNIT_AURA_TYPE)
                     amount = caster->SpellDamageBonusDone(GetBase()->GetUnitOwner(), GetSpellInfo(), amount, SPELL_DIRECT_DAMAGE, 0.0f, 1);
                 break;
             default:
                 break;
         }
     amount *= GetBase()->GetStackAmount();
     return amount;
 }
References abs(), AddPct(), ItemRandomSuffixEntry::AllocationPct, BASE_ATTACK, Aura::CallScriptEffectCalcAmountHandlers(), DOT, SpellInfo::Effects, ItemRandomSuffixEntry::Enchantment, Unit::GetAuraEffectsByType(), GetAuraType(), GetBase(), Aura::GetCastItemGUID(), GetId(), GetPctMods(), GetSpellInfo(), Aura::GetStackAmount(), Item::GetTemplate(), Aura::GetType(), Aura::GetUnitOwner(), Player::GetWeaponForAttack(), SpellInfo::HasAura(), SpellInfo::Id, ItemTemplate::InventoryType, INVTYPE_2HWEAPON, m_baseAmount, m_canBeRecalculated, m_effIndex, m_spellInfo, MAX_ITEM_ENCHANTMENT_EFFECTS, MAX_SPELL_ITEM_ENCHANTMENT_EFFECTS, OFF_ATTACK, SpellInfo::ProcFlags, SetOldAmount(), sItemRandomSuffixStore, SPELL_AURA_DAMAGE_SHIELD, SPELL_AURA_MANA_SHIELD, SPELL_AURA_MOD_CONFUSE, SPELL_AURA_MOD_DAMAGE_PERCENT_DONE, SPELL_AURA_MOD_FEAR, SPELL_AURA_MOD_ROOT, SPELL_AURA_MOD_STUN, SPELL_AURA_OVERRIDE_CLASS_SCRIPTS, SPELL_AURA_PERIODIC_DAMAGE, SPELL_AURA_PERIODIC_HEAL, SPELL_AURA_PERIODIC_LEECH, SPELL_AURA_PROC_TRIGGER_SPELL, SPELL_AURA_SCHOOL_ABSORB, SPELL_AURA_TRANSFORM, SPELL_DIRECT_DAMAGE, Unit::SpellDamageBonusDone(), Unit::SpellHealingBonusDone(), SpellItemEnchantmentEntry::spellid, sSpellItemEnchantmentStore, Object::ToPlayer(), and UNIT_AURA_TYPE.
Referenced by AuraEffect(), spell_dk_pet_scaling::HandlePeriodic(), spell_hun_generic_scaling::HandlePeriodic(), spell_mage_pet_scaling::HandlePeriodic(), spell_sha_feral_spirit_scaling::HandlePeriodic(), spell_warl_generic_scaling::HandlePeriodic(), and RecalculateAmount().
CalculatePeriodic()
void AuraEffect::CalculatePeriodic (Unit * caster, bool create = false, bool load = false)
Definition at line 586 of file SpellAuraEffects.cpp.
 {
     m_amplitude = m_spellInfo->Effects[m_effIndex].Amplitude;
     // prepare periodics
     switch (GetAuraType())
     {
         case SPELL_AURA_OBS_MOD_POWER:
             // 3 spells have no amplitude set
             if (!m_amplitude)
                 m_amplitude = 1 * IN_MILLISECONDS;
             [[fallthrough]]; // TODO: Not sure whether the fallthrough was a mistake (forgetting a break) or intended. This should be double-checked.
         case SPELL_AURA_PERIODIC_DAMAGE:
         case SPELL_AURA_PERIODIC_HEAL:
         case SPELL_AURA_OBS_MOD_HEALTH:
         case SPELL_AURA_PERIODIC_TRIGGER_SPELL:
         case SPELL_AURA_PERIODIC_ENERGIZE:
         case SPELL_AURA_PERIODIC_LEECH:
         case SPELL_AURA_PERIODIC_HEALTH_FUNNEL:
         case SPELL_AURA_PERIODIC_MANA_LEECH:
         case SPELL_AURA_PERIODIC_DAMAGE_PERCENT:
         case SPELL_AURA_POWER_BURN:
         case SPELL_AURA_PERIODIC_DUMMY:
         case SPELL_AURA_PERIODIC_TRIGGER_SPELL_WITH_VALUE:
             m_isPeriodic = true;
             break;
         default:
             break;
     }
     GetBase()->CallScriptEffectCalcPeriodicHandlers(this, m_isPeriodic, m_amplitude);
     if (!m_isPeriodic)
         return;
     // Xinef: fix broken data in dbc
     if (m_amplitude <= 0)
         m_amplitude = 1000;
     Player* modOwner = caster ? caster->GetSpellModOwner() : nullptr;
     // Apply casting time mods
     if (m_amplitude)
     {
         // Apply periodic time mod
         if (modOwner)
             modOwner->ApplySpellMod(GetId(), SPELLMOD_ACTIVATION_TIME, m_amplitude);
         if (caster)
         {
             if (caster->HasAuraTypeWithAffectMask(SPELL_AURA_PERIODIC_HASTE, m_spellInfo) || m_spellInfo->HasAttribute(SPELL_ATTR5_SPELL_HASTE_AFFECTS_PERIODIC))
                 m_amplitude = int32(m_amplitude * caster->GetFloatValue(UNIT_MOD_CAST_SPEED));
         }
     }
     if (load) // aura loaded from db
     {
         m_tickNumber = m_amplitude ? GetBase()->GetDuration() / m_amplitude : 0;
         m_periodicTimer = m_amplitude ? GetBase()->GetDuration() % m_amplitude : 0;
         if (m_spellInfo->HasAttribute(SPELL_ATTR5_EXTRA_INITIAL_PERIOD))
             ++m_tickNumber;
     }
     else // aura just created or reapplied
     {
         m_tickNumber = 0;
         // reset periodic timer on aura create or on reapply when aura isn't dot
         // possibly we should not reset periodic timers only when aura is triggered by proc
         // or maybe there's a spell attribute somewhere
         bool resetPeriodicTimer = create
                                   || ((GetAuraType() != SPELL_AURA_PERIODIC_DAMAGE) && (GetAuraType() != SPELL_AURA_PERIODIC_DAMAGE_PERCENT));
         if (resetPeriodicTimer)
         {
             m_periodicTimer = 0;
             // Start periodic on next tick or at aura apply
             if (m_amplitude)
             {
                 if (!GetSpellInfo()->HasAttribute(SPELL_ATTR5_EXTRA_INITIAL_PERIOD))
                     m_periodicTimer += m_amplitude;
                 else if (caster && caster->IsTotem()) // for totems only ;d
                 {
                     m_periodicTimer = 100; // make it ALMOST instant
                     if (!GetBase()->IsPassive())
                         GetBase()->SetDuration(GetBase()->GetDuration() + 100);
                 }
             }
         }
     }
 }
References Player::ApplySpellMod(), Aura::CallScriptEffectCalcPeriodicHandlers(), SpellInfo::Effects, GetAuraType(), GetBase(), Aura::GetDuration(), Object::GetFloatValue(), GetId(), GetSpellInfo(), Unit::GetSpellModOwner(), SpellInfo::HasAttribute(), Unit::HasAuraTypeWithAffectMask(), IN_MILLISECONDS, Aura::IsPassive(), Unit::IsTotem(), m_amplitude, m_effIndex, m_isPeriodic, m_periodicTimer, m_spellInfo, m_tickNumber, Aura::SetDuration(), SPELL_ATTR5_EXTRA_INITIAL_PERIOD, SPELL_ATTR5_SPELL_HASTE_AFFECTS_PERIODIC, SPELL_AURA_OBS_MOD_HEALTH, SPELL_AURA_OBS_MOD_POWER, SPELL_AURA_PERIODIC_DAMAGE, SPELL_AURA_PERIODIC_DAMAGE_PERCENT, SPELL_AURA_PERIODIC_DUMMY, SPELL_AURA_PERIODIC_ENERGIZE, SPELL_AURA_PERIODIC_HASTE, SPELL_AURA_PERIODIC_HEAL, SPELL_AURA_PERIODIC_HEALTH_FUNNEL, SPELL_AURA_PERIODIC_LEECH, SPELL_AURA_PERIODIC_MANA_LEECH, SPELL_AURA_PERIODIC_TRIGGER_SPELL, SPELL_AURA_PERIODIC_TRIGGER_SPELL_WITH_VALUE, SPELL_AURA_POWER_BURN, SPELLMOD_ACTIVATION_TIME, and UNIT_MOD_CAST_SPEED.
Referenced by AuraEffect(), spell_shadowfang_keep_haunting_spirits::spell_shadowfang_keep_haunting_spirits_AuraScript::HandleUpdatePeriodic(), and Aura::SetLoadedState().
CalculatePeriodicData()
void AuraEffect::CalculatePeriodicData ()
Definition at line 571 of file SpellAuraEffects.cpp.
 {
     // xinef: save caster depending auras with pct mods
     if (GetBase()->GetType() == UNIT_AURA_TYPE && GetCaster())
     {
         if (m_spellInfo->HasAura(SPELL_AURA_PERIODIC_HEAL))
             m_pctMods = GetCaster()->SpellPctHealingModsDone(GetBase()->GetUnitOwner(), GetSpellInfo(), DOT);
         else if (m_spellInfo->HasAura(SPELL_AURA_PERIODIC_DAMAGE) || m_spellInfo->HasAura(SPELL_AURA_PERIODIC_LEECH))
             m_pctMods = GetCaster()->SpellPctDamageModsDone(GetBase()->GetUnitOwner(), GetSpellInfo(), DOT);
     }
     if (GetCaster())
         SetCritChance(CalcPeriodicCritChance(GetCaster(), (GetBase()->GetType() == UNIT_AURA_TYPE ? GetBase()->GetUnitOwner() : nullptr)));
 }
References CalcPeriodicCritChance(), DOT, GetBase(), GetCaster(), GetSpellInfo(), Aura::GetType(), Aura::GetUnitOwner(), SpellInfo::HasAura(), m_pctMods, m_spellInfo, SetCritChance(), SPELL_AURA_PERIODIC_DAMAGE, SPELL_AURA_PERIODIC_HEAL, SPELL_AURA_PERIODIC_LEECH, Unit::SpellPctDamageModsDone(), Unit::SpellPctHealingModsDone(), and UNIT_AURA_TYPE.
Referenced by AuraEffect().
CalculateSpellMod()
void AuraEffect::CalculateSpellMod ()
Definition at line 676 of file SpellAuraEffects.cpp.
 {
     switch (GetAuraType())
     {
         case SPELL_AURA_ADD_FLAT_MODIFIER:
         case SPELL_AURA_ADD_PCT_MODIFIER:
             if (!m_spellmod)
             {
                 m_spellmod = new SpellModifier(GetBase());
                 m_spellmod->op = SpellModOp(GetMiscValue());
                 m_spellmod->type = SpellModType(GetAuraType()); // SpellModType value == spell aura types
                 m_spellmod->spellId = GetId();
                 m_spellmod->mask = GetSpellInfo()->Effects[GetEffIndex()].SpellClassMask;
                 m_spellmod->charges = GetBase()->GetCharges();
             }
             m_spellmod->value = GetAmount();
             break;
         default:
             break;
     }
     GetBase()->CallScriptEffectCalcSpellModHandlers(this, m_spellmod);
 }
References Aura::CallScriptEffectCalcSpellModHandlers(), SpellModifier::charges, SpellInfo::Effects, GetAmount(), GetAuraType(), GetBase(), Aura::GetCharges(), GetEffIndex(), GetId(), GetMiscValue(), GetSpellInfo(), m_spellmod, SpellModifier::mask, SpellModifier::op, SPELL_AURA_ADD_FLAT_MODIFIER, SPELL_AURA_ADD_PCT_MODIFIER, SpellModifier::spellId, SpellModifier::type, and SpellModifier::value.
Referenced by AuraEffect(), ChangeAmount(), and Aura::SetLoadedState().
CanApplyResilience()
bool AuraEffect::CanApplyResilience () const inline
Definition at line 103 of file SpellAuraEffects.h.
 { return m_applyResilience; }
References m_applyResilience.
Referenced by HandlePeriodicDamageAurasTick(), and HandlePeriodicHealthLeechAuraTick().
CanBeRecalculated()
bool AuraEffect::CanBeRecalculated () const inline
Definition at line 70 of file SpellAuraEffects.h.
 { return m_canBeRecalculated; }
References m_canBeRecalculated.
Referenced by Pet::_SaveAuras(), RecalculateAmount(), and Unit::RemoveAurasDueToSpellBySteal().
ChangeAmount()
void AuraEffect::ChangeAmount (int32 newAmount, bool mark = true, bool onStackOrReapply = false)
Definition at line 700 of file SpellAuraEffects.cpp.
 {
     // Reapply if amount change
     uint8 handleMask = 0;
     if (newAmount != GetAmount())
         handleMask |= AURA_EFFECT_HANDLE_CHANGE_AMOUNT;
     if (onStackOrReapply)
         handleMask |= AURA_EFFECT_HANDLE_REAPPLY;
     if (!handleMask)
         return;
     std::list<AuraApplication*> effectApplications;
     GetApplicationList(effectApplications);
     for (std::list<AuraApplication*>::const_iterator apptItr = effectApplications.begin(); apptItr != effectApplications.end(); ++apptItr)
         if ((*apptItr)->HasEffect(GetEffIndex()))
             HandleEffect(*apptItr, handleMask, false);
     if (handleMask & AURA_EFFECT_HANDLE_CHANGE_AMOUNT)
     {
         if (!mark)
             m_amount = newAmount;
         else
             SetAmount(newAmount);
         CalculateSpellMod();
     }
     for (std::list<AuraApplication*>::const_iterator apptItr = effectApplications.begin(); apptItr != effectApplications.end(); ++apptItr)
         if ((*apptItr)->HasEffect(GetEffIndex()))
             HandleEffect(*apptItr, handleMask, true);
 }
References AURA_EFFECT_HANDLE_CHANGE_AMOUNT, AURA_EFFECT_HANDLE_REAPPLY, CalculateSpellMod(), GetAmount(), GetApplicationList(), GetEffIndex(), HandleEffect(), m_amount, and SetAmount().
Referenced by spell_dk_pet_scaling::HandlePeriodic(), spell_hun_generic_scaling::HandlePeriodic(), spell_mage_pet_scaling::HandlePeriodic(), spell_sha_feral_spirit_scaling::HandlePeriodic(), spell_warl_generic_scaling::HandlePeriodic(), RecalculateAmount(), Unit::RemoveMovementImpairingAuras(), and Aura::SetStackAmount().
CleanupTriggeredSpells()
void AuraEffect::CleanupTriggeredSpells (Unit * target)
Definition at line 1167 of file SpellAuraEffects.cpp.
 {
     uint32 tSpellId = m_spellInfo->Effects[GetEffIndex()].TriggerSpell;
     if (!tSpellId)
         return;
     SpellInfo const* tProto = sSpellMgr->GetSpellInfo(tSpellId);
     if (!tProto)
         return;
     if (tProto->GetDuration() != -1)
         return;
     // needed for spell 43680, maybe others
     // TODO: is there a spell flag, which can solve this in a more sophisticated way?
     if (m_spellInfo->Effects[GetEffIndex()].ApplyAuraName == SPELL_AURA_PERIODIC_TRIGGER_SPELL &&
             uint32(m_spellInfo->GetDuration()) == m_spellInfo->Effects[GetEffIndex()].Amplitude)
         return;
     target->RemoveAurasDueToSpell(tSpellId, GetCasterGUID());
 }
References SpellInfo::Effects, GetCasterGUID(), SpellInfo::GetDuration(), GetEffIndex(), m_spellInfo, Unit::RemoveAurasDueToSpell(), SPELL_AURA_PERIODIC_TRIGGER_SPELL, and sSpellMgr.
Referenced by AuraApplication::_HandleEffect().
GetAmount()
int32 AuraEffect::GetAmount () const inline
Definition at line 56 of file SpellAuraEffects.h.
 { return m_isAuraEnabled ? m_amount : 0; }
References m_amount, and m_isAuraEnabled.
Referenced by Player::_ApplyWeaponDependentAuraCritMod(), Player::_ApplyWeaponDependentAuraDamageMod(), AuraApplication::_HandleEffect(), Pet::_SaveAuras(), spell_dru_survival_instincts_aura::AfterApply(), spell_the_lich_king_necrotic_plague_jump::spell_the_lich_king_necrotic_plague_AuraScript::AfterDispel(), spell_dru_lifebloom::AfterRemove(), spell_mage_living_bomb::AfterRemove(), Unit::CalcAbsorbResist(), Unit::CalcHealAbsorb(), CalculateSpellMod(), ChangeAmount(), Spell::EffectHeal(), Spell::EffectSchoolDMG(), spell_pri_renew::HandleApplyEffect(), HandleAuraDummy(), HandleAuraIncreaseBaseHealthPercent(), HandleAuraLinked(), HandleAuraModAttackPower(), HandleAuraModAttackPowerPercent(), HandleAuraModBaseResistancePCT(), HandleAuraModCritPct(), HandleAuraModFakeInebriation(), HandleAuraModIncreaseEnergy(), HandleAuraModIncreaseEnergyPercent(), HandleAuraModIncreaseHealth(), HandleAuraModIncreaseHealthPercent(), HandleAuraModIncreaseMaxHealth(), HandleAuraModRangedAttackPower(), HandleAuraModRangedAttackPowerPercent(), HandleAuraModRangedHaste(), HandleAuraModResistance(), HandleAuraModResistanceExclusive(), HandleAuraModScale(), HandleAuraModSkill(), HandleAuraModStat(), HandleAuraModTotalThreat(), HandleAuraModWeaponCritPercent(), Unit::HandleAuraRaidProcFromChargeWithValue(), HandleAuraRetainComboPoints(), Aura::HandleAuraSpecificMods(), HandleChannelDeathItem(), spell_dk_raise_ally::HandleDummy(), Unit::HandleDummyAuraProc(), spell_shadowfang_keep_haunting_spirits::spell_shadowfang_keep_haunting_spirits_AuraScript::HandleDummyTick(), spell_dk_improved_blood_presence::HandleEffectApply(), spell_dk_improved_frost_presence::HandleEffectApply(), spell_dk_improved_unholy_presence::HandleEffectApply(), spell_dru_idol_lifebloom::HandleEffectCalcSpellMod(), spell_pal_exorcism_and_holy_wrath_damage::HandleEffectCalcSpellMod(), spell_warl_improved_demonic_tactics::HandleEffectCalcSpellMod(), spell_warr_glyph_of_sunder_armor::HandleEffectCalcSpellMod(), spell_gen_leeching_swarm::spell_gen_leeching_swarm_AuraScript::HandleEffectPeriodic(), spell_hallows_end_base_fire::spell_hallows_end_base_fire_AuraScript::HandleEffectPeriodicUpdate(), spell_gen_burn_brutallus::HandleEffectPeriodicUpdate(), spell_sha_item_t10_elemental_2p_bonus::HandleEffectProc(), HandleModAttackSpeed(), HandleModBaseResistance(), HandleModCastingSpeed(), HandleModCombatSpeedPct(), HandleModDamageDone(), HandleModDamagePercentDone(), HandleModHitChance(), HandleModInvisibility(), HandleModInvisibilityDetect(), HandleModMeleeRangedSpeedPct(), HandleModMeleeSpeedPct(), HandleModOffhandDamagePercent(), HandleModPowerCost(), HandleModPowerCostPCT(), HandleModRating(), HandleModResistancePercent(), HandleModSpellCritChance(), HandleModSpellHitChance(), HandleModStateImmunityMask(), HandleModStealth(), HandleModStealthDetect(), HandleModStealthLevel(), HandleModTargetResistance(), HandleModThreat(), HandleModTotalPercentStat(), Unit::HandleOverrideClassScriptAuraProc(), spell_dk_chains_of_ice_aura::HandlePeriodic(), spell_ragin_flames_inferno::spell_ragin_flames_inferno_AuraScript::HandlePeriodic(), spell_dk_death_and_decay_aura::HandlePeriodic(), spell_dk_pet_scaling::HandlePeriodic(), spell_hun_generic_scaling::HandlePeriodic(), spell_hun_sniper_training::HandlePeriodic(), spell_mage_pet_scaling::HandlePeriodic(), spell_sha_feral_spirit_scaling::HandlePeriodic(), spell_warl_generic_scaling::HandlePeriodic(), HandlePeriodicDamageAurasTick(), HandlePeriodicHealthFunnelAuraTick(), HandlePeriodicHealthLeechAuraTick(), HandlePeriodicTriggerSpellAuraTick(), HandlePeriodicTriggerSpellWithValueAuraTick(), spell_dru_living_seed_proc::HandleProc(), spell_sha_earth_shield::HandleProc(), spell_oculus_temporal_rift::spell_oculus_temporal_rift_AuraScript::HandleProc(), spell_dk_wandering_plague_aura::HandleProc(), spell_dru_t10_balance_4p_bonus::HandleProc(), spell_dru_living_seed::HandleProc(), spell_hun_glyph_of_arcane_shot::HandleProc(), spell_item_necrotic_touch::HandleProc(), spell_mage_burnout::HandleProc(), spell_mage_master_of_elements::HandleProc(), spell_pal_sacred_shield_base::HandleProc(), spell_pri_divine_aegis::HandleProc(), spell_pri_glyph_of_prayer_of_healing::HandleProc(), spell_sha_t10_restoration_4p_bonus::HandleProc(), spell_hun_lock_and_load::HandleProcs(), HandleProcTriggerDamageAuraProc(), Unit::HandleProcTriggerSpell(), HandleProcTriggerSpellWithValueAuraProc(), HandleRaidProcFromChargeWithValueAuraProc(), HandleRangedAmmoHaste(), spell_warl_haunt_aura::HandleRemove(), HandleShieldBlockValue(), spell_hun_sniper_training::HandleUpdatePeriodic(), Aura::IsAuraStronger(), spell_valanar_kinetic_bomb_absorb::spell_valanar_kinetic_bomb_absorb_AuraScript::OnAbsorb(), spell_alar_ember_blast_death::spell_alar_ember_blast_death_AuraScript::OnApply(), spell_the_lich_king_necrotic_plague_jump::spell_the_lich_king_necrotic_plague_AuraScript::OnDispel(), spell_kalecgos_curse_of_boundless_agony::spell_kalecgos_curse_of_boundless_agony_AuraScript::OnPeriodic(), spell_xt002_gravity_bomb_aura::spell_xt002_gravity_bomb_aura_AuraScript::OnPeriodic(), spell_lurker_below_spout::spell_lurker_below_spout_AuraScript::OnPeriodic(), spell_blood_queen_essence_of_the_blood_queen::spell_blood_queen_essence_of_the_blood_queen_AuraScript::OnProc(), spell_pal_eye_for_an_eye::OnProc(), spell_warl_siphon_life::OnProc(), spell_warl_fel_synergy::OnProc(), spell_warr_improved_spell_reflection::OnProc(), spell_warr_damage_shield::OnProc(), spell_sindragosa_instability::spell_sindragosa_instability_AuraScript::OnRemove(), spell_the_lich_king_necrotic_plague_jump::spell_the_lich_king_necrotic_plague_AuraScript::OnRemove(), spell_shield_of_runes::spell_shield_of_runes_AuraScript::OnRemove(), spell_xt002_gravity_bomb_aura::spell_xt002_gravity_bomb_aura_AuraScript::OnRemove(), spell_xt002_searing_light_spawn_life_spark::spell_xt002_searing_light_spawn_life_spark_AuraScript::OnRemove(), spell_ulduar_stone_grip::spell_ulduar_stone_grip_AuraScript::OnRemoveStun(), spell_the_lich_king_infest::spell_the_lich_king_infest_AuraScript::OnUpdate(), spell_karazhan_overload::spell_karazhan_overload_AuraScript::PeriodicTick(), spell_icc_yh_volley::spell_icc_yh_volley_AuraScript::PrepareAuraScript(), spell_serpentshrine_cavern_infection::spell_serpentshrine_cavern_infection_AuraScript::PrepareAuraScript(), Unit::ProcDamageAndSpellFor(), Unit::RemoveAurasDueToSpellBySteal(), ArenaSpectator::ShouldSendAura(), spell_mother_shahraz_fatal_attraction_aura::spell_mother_shahraz_fatal_attraction_aura_AuraScript::Update(), spell_black_temple_shadow_inferno::spell_black_temple_shadow_inferno_AuraScript::Update(), spell_black_temple_spell_absorption::spell_black_temple_spell_absorption_AuraScript::Update(), Player::UpdateAttackPowerAndDamage(), UpdatePeriodic(), and SpellInfo::ValidateAttribute6SpellDamageMods().
GetAmplitude()
int32 AuraEffect::GetAmplitude () const inline
Definition at line 51 of file SpellAuraEffects.h.
 { return m_amplitude; }
References m_amplitude.
Referenced by spell_igb_rocket_pack::spell_igb_rocket_pack_AuraScript::HandleRemove().
GetApplicationList()
void AuraEffect::GetApplicationList (std::list< AuraApplication * > & applicationList) const
Definition at line 421 of file SpellAuraEffects.cpp.
 {
     Aura::ApplicationMap const& targetMap = GetBase()->GetApplicationMap();
     for (Aura::ApplicationMap::const_iterator appIter = targetMap.begin(); appIter != targetMap.end(); ++appIter)
     {
         if (appIter->second->HasEffect(GetEffIndex()))
             applicationList.push_back(appIter->second);
     }
 }
References Aura::GetApplicationMap(), GetBase(), and GetEffIndex().
Referenced by ChangeAmount(), and Update().
GetAuraGroup()
uint32 AuraEffect::GetAuraGroup () const inline
Definition at line 107 of file SpellAuraEffects.h.
 { return m_auraGroup; }
References m_auraGroup.
Referenced by AuraApplication::_HandleEffect().
GetAuraType()
AuraType AuraEffect::GetAuraType () const
Definition at line 446 of file SpellAuraEffects.cpp.
 {
     return (AuraType)m_spellInfo->Effects[m_effIndex].ApplyAuraName;
 }
References SpellInfo::Effects, m_effIndex, and m_spellInfo.
Referenced by Player::_ApplyWeaponDependentAuraDamageMod(), AuraApplication::_HandleEffect(), Unit::_RegisterAuraEffect(), CalculateAmount(), CalculatePeriodic(), CalculateSpellMod(), HandleArenaPreparation(), HandleAuraAllowFlight(), HandleAuraEmpathy(), HandleAuraFeatherFall(), HandleAuraHover(), HandleAuraModDisarm(), HandleAuraModIncreaseFlightSpeed(), HandleAuraModSchoolImmunity(), HandleAuraModSkill(), HandleAuraModStalked(), HandleAuraTrackStealthed(), HandleAuraUntrackable(), HandleAuraWaterWalk(), HandleComprehendLanguage(), HandleEffect(), spell_dk_pet_scaling::HandleEffectApply(), spell_dru_treant_scaling::HandleEffectApply(), spell_pet_hit_expertise_scalling::HandleEffectApply(), spell_mage_pet_scaling::HandleEffectApply(), spell_pri_shadowfiend_scaling::HandleEffectApply(), spell_sha_feral_spirit_scaling::HandleEffectApply(), spell_sha_fire_elemental_scaling::HandleEffectApply(), spell_warl_infernal_scaling::HandleEffectApply(), HandleForceMoveForward(), spell_dk_pet_scaling::HandlePeriodic(), spell_hun_generic_scaling::HandlePeriodic(), spell_mage_pet_scaling::HandlePeriodic(), spell_sha_feral_spirit_scaling::HandlePeriodic(), spell_warl_generic_scaling::HandlePeriodic(), HandlePeriodicDamageAurasTick(), HandlePeriodicHealAurasTick(), HandleProc(), Unit::HandleProcTriggerSpell(), HandleShieldBlockValue(), Aura::IsAuraStronger(), PeriodicTick(), Unit::ProcDamageAndSpellFor(), Player::RestoreBaseRune(), Unit::SendPeriodicAuraLog(), ArenaSpectator::ShouldSendAura(), and UpdatePeriodic().
GetBase()
Aura* AuraEffect::GetBase () const inline
Definition at line 42 of file SpellAuraEffects.h.
 { return m_base; }
References m_base.
Referenced by AuraApplication::_HandleEffect(), ApplySpellMod(), Unit::CalcAbsorbResist(), Unit::CalcHealAbsorb(), CalculateAmount(), CalculatePeriodic(), CalculatePeriodicData(), CalculateSpellMod(), Spell::EffectHeal(), Spell::EffectSchoolDMG(), spell_festergut_blighted_spores::spell_festergut_blighted_spores_AuraScript::ExtraEffect(), GetApplicationList(), GetCaster(), GetCasterGUID(), GetTargetList(), GetTotalTicks(), HandleAuraDummy(), HandleAuraLinked(), HandleAuraModShapeshift(), HandleAuraModStateImmunity(), HandleAuraMounted(), Unit::HandleAuraRaidProcFromCharge(), Unit::HandleAuraRaidProcFromChargeWithValue(), HandleAuraRetainComboPoints(), Unit::HandleDummyAuraProc(), HandleEffect(), spell_pal_exorcism_and_holy_wrath_damage::HandleEffectCalcSpellMod(), spell_warl_improved_demonic_tactics::HandleEffectCalcSpellMod(), spell_warr_glyph_of_sunder_armor::HandleEffectCalcSpellMod(), spell_brewfest_main_ram_buff::spell_brewfest_main_ram_buff_AuraScript::HandleEffectPeriodic(), HandleObsModPowerAuraTick(), Unit::HandleOverrideClassScriptAuraProc(), HandlePeriodicDamageAurasTick(), HandlePeriodicEnergizeAuraTick(), HandlePeriodicHealAurasTick(), HandlePeriodicHealthLeechAuraTick(), HandlePeriodicManaLeechAuraTick(), HandlePeriodicTriggerSpellAuraTick(), HandleProc(), Unit::HandleProcTriggerSpell(), HandleRaidProcFromChargeAuraProc(), HandleRaidProcFromChargeWithValueAuraProc(), spell_hor_shared_suffering::spell_hor_shared_sufferingAuraScript::OnRemove(), PeriodicTick(), Spell::prepare(), spell_pos_glacial_strike::spell_pos_glacial_strikeAuraScript::PrepareAuraScript(), Unit::ProcDamageAndSpellFor(), Player::RestoreBaseRune(), Update(), UpdatePeriodic(), and SpellInfo::ValidateAttribute6SpellDamageMods().
GetBaseAmount()
int32 AuraEffect::GetBaseAmount () const inline
Definition at line 50 of file SpellAuraEffects.h.
 { return m_baseAmount; }
References m_baseAmount.
Referenced by Pet::_SaveAuras(), spell_warl_demonic_knowledge::CalculateAmount(), spell_hun_sniper_training::HandleUpdatePeriodic(), and Unit::RemoveAurasDueToSpellBySteal().
GetCaster()
Unit* AuraEffect::GetCaster () const inline
Definition at line 40 of file SpellAuraEffects.h.
 { return GetBase()->GetCaster(); }
References GetBase(), and Aura::GetCaster().
Referenced by Unit::CalcAbsorbResist(), CalculatePeriodicData(), Spell::EffectHeal(), HandleAuraCloneCaster(), HandleAuraControlVehicle(), HandleAuraDummy(), HandleAuraLinked(), HandleAuraModTotalThreat(), Unit::HandleAuraRaidProcFromCharge(), Unit::HandleAuraRaidProcFromChargeWithValue(), HandleAuraTransform(), HandleBindSight(), HandleChannelDeathItem(), HandleCharmConvert(), Unit::HandleDummyAuraProc(), HandleFarSight(), HandleModCharm(), HandleModPossess(), HandleModPossessPet(), HandleModTaunt(), spell_pal_sacred_shield_base::HandleProc(), HandleRaidProcFromChargeAuraProc(), HandleRaidProcFromChargeWithValueAuraProc(), and RecalculateAmount().
GetCasterGUID()
ObjectGuid AuraEffect::GetCasterGUID () const inline
Definition at line 41 of file SpellAuraEffects.h.
 { return GetBase()->GetCasterGUID(); }
References GetBase(), and Aura::GetCasterGUID().
Referenced by Unit::CastDelayedSpellWithPeriodicAmount(), Unit::CastSpell(), CleanupTriggeredSpells(), Spell::EffectHeal(), HandleAuraDummy(), HandleAuraLinked(), Unit::HandleAuraRaidProcFromCharge(), Unit::HandleAuraRaidProcFromChargeWithValue(), HandleAuraTransform(), Unit::HandleDummyAuraProc(), HandleFeignDeath(), HandleObsModPowerAuraTick(), HandlePeriodicDamageAurasTick(), HandlePeriodicEnergizeAuraTick(), HandlePeriodicHealAurasTick(), HandlePeriodicHealthLeechAuraTick(), HandlePeriodicManaLeechAuraTick(), HandleRaidProcFromChargeAuraProc(), HandleRaidProcFromChargeWithValueAuraProc(), Unit::ProcDamageAndSpellFor(), Unit::SendPeriodicAuraLog(), and SpellInfo::ValidateAttribute6SpellDamageMods().
GetCasterLevel()
uint8 AuraEffect::GetCasterLevel () const inline
Definition at line 102 of file SpellAuraEffects.h.
 { return m_casterLevel; }
References m_casterLevel.
Referenced by HandlePeriodicDamageAurasTick(), and HandlePeriodicHealthLeechAuraTick().
GetCritChance()
float AuraEffect::GetCritChance () const inline
Definition at line 100 of file SpellAuraEffects.h.
 { return m_critChance; }
References m_critChance.
Referenced by HandlePeriodicDamageAurasTick(), HandlePeriodicHealAurasTick(), and HandlePeriodicHealthLeechAuraTick().
GetEffIndex()
uint32 AuraEffect::GetEffIndex () const inline
Definition at line 49 of file SpellAuraEffects.h.
 { return m_effIndex; }
References m_effIndex.
Referenced by AuraApplication::_HandleEffect(), Unit::CalcAbsorbResist(), spell_pal_sacred_shield_base::CalculateAmount(), spell_warl_improved_demonic_tactics::CalculateAmount(), spell_warr_rend::CalculateAmount(), spell_dru_treant_scaling::CalculateResistanceAmount(), spell_hun_generic_scaling::CalculateResistanceAmount(), spell_mage_pet_scaling::CalculateResistanceAmount(), spell_pri_shadowfiend_scaling::CalculateResistanceAmount(), spell_sha_feral_spirit_scaling::CalculateResistanceAmount(), spell_sha_fire_elemental_scaling::CalculateResistanceAmount(), spell_warl_generic_scaling::CalculateResistanceAmount(), spell_warl_infernal_scaling::CalculateResistanceAmount(), spell_mage_ice_barrier_aura::CalculateSpellAmount(), spell_mage_ice_barrier::CalculateSpellAmount(), CalculateSpellAmount(), CalculateSpellMod(), spell_dk_pet_scaling::CalculateStatAmount(), spell_dru_treant_scaling::CalculateStatAmount(), spell_hun_generic_scaling::CalculateStatAmount(), spell_mage_pet_scaling::CalculateStatAmount(), spell_pri_shadowfiend_scaling::CalculateStatAmount(), spell_sha_feral_spirit_scaling::CalculateStatAmount(), spell_sha_fire_elemental_scaling::CalculateStatAmount(), spell_warl_generic_scaling::CalculateStatAmount(), spell_warl_infernal_scaling::CalculateStatAmount(), Aura::CallScriptAfterEffectApplyHandlers(), Aura::CallScriptAfterEffectProcHandlers(), Aura::CallScriptAfterEffectRemoveHandlers(), Aura::CallScriptEffectAbsorbHandlers(), Aura::CallScriptEffectAfterAbsorbHandlers(), Aura::CallScriptEffectAfterManaShieldHandlers(), Aura::CallScriptEffectApplyHandlers(), Aura::CallScriptEffectCalcAmountHandlers(), Aura::CallScriptEffectCalcPeriodicHandlers(), Aura::CallScriptEffectCalcSpellModHandlers(), Aura::CallScriptEffectManaShieldHandlers(), Aura::CallScriptEffectPeriodicHandlers(), Aura::CallScriptEffectProcHandlers(), Aura::CallScriptEffectRemoveHandlers(), Aura::CallScriptEffectSplitHandlers(), Aura::CallScriptEffectUpdatePeriodicHandlers(), Unit::CastDelayedSpellWithPeriodicAmount(), ChangeAmount(), CleanupTriggeredSpells(), GetApplicationList(), GetTargetList(), spell_muru_summon_blood_elves_periodic::spell_muru_summon_blood_elves_periodic_AuraScript::HandleApply(), spell_gen_baby_murloc_passive::HandleApply(), HandleAuraLinked(), HandleAuraModStat(), Unit::HandleAuraRaidProcFromCharge(), Unit::HandleAuraRaidProcFromChargeWithValue(), Unit::HandleDummyAuraProc(), HandleEffect(), spell_dru_idol_lifebloom::HandleEffectCalcSpellMod(), spell_warr_glyph_of_sunder_armor::HandleEffectCalcSpellMod(), spell_q12619_emblazon_runeblade::HandleEffectPeriodic(), spell_oculus_rider_aura::spell_oculus_rider_auraAuraScript::HandleOnEffectApply(), spell_transitus_shield_beam::spell_transitus_shield_beam_AuraScript::HandleOnEffectApply(), spell_kiljaeden_shadow_spike::spell_kiljaeden_shadow_spike_AuraScript::HandlePeriodic(), spell_kiljaeden_armageddon_periodic::spell_kiljaeden_armageddon_periodic_AuraScript::HandlePeriodic(), spell_halion_twilight_cutter_periodic::spell_halion_twilight_cutter_periodic_AuraScript::HandlePeriodic(), spell_oculus_ride_ruby_emerald_amber_drake_que::spell_oculus_ride_ruby_emerald_amber_drake_que_AuraScript::HandlePeriodic(), spell_dk_pet_scaling::HandlePeriodic(), spell_pet_hit_expertise_scalling::HandlePeriodic(), spell_hun_generic_scaling::HandlePeriodic(), spell_mage_pet_scaling::HandlePeriodic(), spell_sha_feral_spirit_scaling::HandlePeriodic(), spell_warl_improved_demonic_tactics::HandlePeriodic(), spell_warl_demonic_knowledge::HandlePeriodic(), spell_warl_generic_scaling::HandlePeriodic(), HandlePeriodicDamageAurasTick(), HandlePeriodicHealAurasTick(), HandlePeriodicHealthFunnelAuraTick(), HandlePeriodicHealthLeechAuraTick(), HandlePeriodicManaLeechAuraTick(), HandlePeriodicPowerBurnAuraTick(), HandlePeriodicTriggerSpellAuraTick(), HandlePeriodicTriggerSpellWithValueAuraTick(), spell_item_unsated_craving::HandleProc(), spell_pal_sacred_shield_base::HandleProc(), Unit::HandleProcTriggerSpell(), HandleProcTriggerSpellAuraProc(), HandleRaidProcFromChargeAuraProc(), HandleRaidProcFromChargeWithValueAuraProc(), spell_putricide_mutated_plague::spell_putricide_mutated_plague_AuraScript::HandleTriggerSpell(), spell_hun_sniper_training::HandleUpdatePeriodic(), TriggeredByAuraSpellData::Init(), spell_hadronox_summon_periodic::spell_hadronox_summon_periodic_AuraScript::OnApply(), spell_gruul_ground_slam_trigger::spell_gruul_ground_slam_trigger_AuraScript::OnApply(), spell_kalecgos_curse_of_boundless_agony::spell_kalecgos_curse_of_boundless_agony_AuraScript::OnPeriodic(), spell_the_lich_king_vile_spirits::spell_the_lich_king_vile_spirits_AuraScript::OnPeriodic(), spell_tar_blaze::spell_tar_blaze_AuraScript::OnPeriodic(), spell_thorim_lightning_pillar_P2::spell_thorim_lightning_pillar_P2_AuraScript::OnPeriodic(), spell_karathress_power_of_caribdis::spell_karathress_power_of_caribdis_AuraScript::OnPeriodic(), spell_leotheras_demon_link::spell_leotheras_demon_link_AuraScript::OnPeriodic(), spell_gen_periodic_knock_away::OnPeriodic(), spell_broggok_poison_cloud::spell_broggok_poison_cloud_AuraScript::PeriodicTick(), spell_mother_shahraz_beam_periodic::spell_mother_shahraz_beam_periodic_AuraScript::Update(), spell_mother_shahraz_saber_lash::spell_mother_shahraz_saber_lash_AuraScript::Update(), spell_illidari_council_deadly_strike::spell_illidari_council_deadly_strike_AuraScript::Update(), spell_black_temple_charge_rage::spell_black_temple_charge_rage_AuraScript::Update(), spell_black_temple_shadow_inferno::spell_black_temple_shadow_inferno_AuraScript::Update(), spell_black_temple_spell_absorption::spell_black_temple_spell_absorption_AuraScript::Update(), Update(), and Player::UpdateAttackPowerAndDamage().
GetForcedAmount()
int32 AuraEffect::GetForcedAmount () const inline
Definition at line 57 of file SpellAuraEffects.h.
 { return m_amount; }
References m_amount.
GetId()
uint32 AuraEffect::GetId () const
Definition at line 431 of file SpellAuraEffects.cpp.
 {
     return m_spellInfo->Id;
 }
References SpellInfo::Id, and m_spellInfo.
Referenced by AuraEffect(), CalculateAmount(), CalculatePeriodic(), CalculateSpellMod(), Unit::CastDelayedSpellWithPeriodicAmount(), Spell::EffectHeal(), Spell::EffectSchoolDMG(), HandleAuraControlVehicle(), HandleAuraDummy(), HandleAuraModDmgImmunity(), HandleAuraModEffectImmunity(), HandleAuraModIncreaseFlightSpeed(), HandleAuraModSchoolImmunity(), HandleAuraModStat(), HandleAuraModStateImmunity(), Aura::HandleAuraSpecificMods(), HandleAuraTransform(), Unit::HandleDummyAuraProc(), HandleModMechanicImmunity(), HandleModStateImmunityMask(), HandleModTotalPercentStat(), HandleObsModPowerAuraTick(), HandlePeriodicDamageAurasTick(), HandlePeriodicDummyAuraTick(), HandlePeriodicEnergizeAuraTick(), HandlePeriodicHealAurasTick(), HandlePeriodicHealthLeechAuraTick(), HandlePeriodicManaLeechAuraTick(), HandlePeriodicTriggerSpellAuraTick(), HandlePeriodicTriggerSpellWithValueAuraTick(), HandleProcTriggerDamageAuraProc(), Unit::HandleProcTriggerSpell(), HandleProcTriggerSpellAuraProc(), HandleProcTriggerSpellWithValueAuraProc(), HandleRaidProcFromChargeAuraProc(), HandleRaidProcFromChargeWithValueAuraProc(), spell_brewfest_ram_fatigue::spell_brewfest_ram_fatigue_AuraScript::PrepareAuraScript(), spell_ignis_scorch::spell_ignis_scorch_AuraScript::PrepareAuraScript(), spell_ulduar_energy_sap::spell_ulduar_energy_sap_AuraScript::PrepareAuraScript(), Unit::ProcDamageAndSpellFor(), Unit::SendPeriodicAuraLog(), and UpdatePeriodic().
GetMiscValue()
int32 AuraEffect::GetMiscValue () const
Definition at line 441 of file SpellAuraEffects.cpp.
 {
     return m_spellInfo->Effects[m_effIndex].MiscValue;
 }
References SpellInfo::Effects, m_effIndex, and m_spellInfo.
Referenced by Player::_ApplyWeaponDependentAuraDamageMod(), AuraApplication::_HandleEffect(), ApplySpellMod(), Unit::CalcAbsorbResist(), CalculateSpellMod(), Unit::GetMaxPositiveAuraModifierByMiscMask(), HandleAuraConvertRune(), HandleAuraDummy(), HandleAuraModBaseResistancePCT(), HandleAuraModDispelImmunity(), HandleAuraModDmgImmunity(), HandleAuraModEffectImmunity(), HandleAuraModFaction(), HandleAuraModIncreaseEnergy(), HandleAuraModIncreaseEnergyPercent(), HandleAuraModResistance(), HandleAuraModResistanceExclusive(), HandleAuraModResistenceOfStatPercent(), HandleAuraModSchoolImmunity(), HandleAuraModShapeshift(), HandleAuraModSkill(), HandleAuraModStat(), HandleAuraModStateImmunity(), HandleAuraMounted(), HandleAuraOverrideSpells(), HandleAuraSetVehicle(), HandleAuraTrackCreatures(), HandleAuraTrackResources(), HandleAuraTransform(), HandleDetectAmore(), spell_warl_improved_demonic_tactics::HandleEffectCalcSpellMod(), spell_warr_glyph_of_sunder_armor::HandleEffectCalcSpellMod(), HandleForceReaction(), HandleModBaseResistance(), HandleModDamageDone(), HandleModDamagePercentDone(), HandleModInvisibility(), HandleModInvisibilityDetect(), HandleModMechanicImmunity(), HandleModPercentStat(), HandleModPowerCost(), HandleModPowerCostPCT(), HandleModPowerRegen(), HandleModRating(), HandleModRatingFromStat(), HandleModResistancePercent(), HandleModSpellCritChanceShool(), HandleModStateImmunityMask(), HandleModStealth(), HandleModStealthDetect(), HandleModStealthLevel(), HandleModTargetResistance(), HandleModThreat(), HandleModTotalPercentStat(), HandleObsModPowerAuraTick(), Unit::HandleOverrideClassScriptAuraProc(), spell_dk_pet_scaling::HandlePeriodic(), spell_hun_generic_scaling::HandlePeriodic(), spell_mage_pet_scaling::HandlePeriodic(), spell_sha_feral_spirit_scaling::HandlePeriodic(), spell_warl_generic_scaling::HandlePeriodic(), HandlePeriodicEnergizeAuraTick(), HandlePeriodicManaLeechAuraTick(), HandlePeriodicPowerBurnAuraTick(), HandleShapeshiftBoosts(), Aura::IsAuraStronger(), spell_alar_ember_blast_death::spell_alar_ember_blast_death_AuraScript::OnApply(), Unit::ProcDamageAndSpellFor(), and Unit::SendPeriodicAuraLog().
GetMiscValueB()
int32 AuraEffect::GetMiscValueB () const
Definition at line 436 of file SpellAuraEffects.cpp.
 {
     return m_spellInfo->Effects[m_effIndex].MiscValueB;
 }
References SpellInfo::Effects, m_effIndex, and m_spellInfo.
Referenced by HandleAuraConvertRune(), and HandleModPowerRegen().
GetOldAmount()
int32 AuraEffect::GetOldAmount () const inline
Definition at line 108 of file SpellAuraEffects.h.
 { return m_oldAmount; }
References m_oldAmount.
Referenced by Unit::CastDelayedSpellWithPeriodicAmount().
GetPctMods()
float AuraEffect::GetPctMods () const inline
Definition at line 104 of file SpellAuraEffects.h.
 { return m_pctMods; }
References m_pctMods.
Referenced by CalculateAmount().
GetPeriodicTimer()
int32 AuraEffect::GetPeriodicTimer () const inline
Definition at line 60 of file SpellAuraEffects.h.
 { return m_periodicTimer; }
References m_periodicTimer.
Referenced by spell_dreamwalker_decay_periodic_timer::spell_dreamwalker_decay_periodic_timer_AuraScript::DecayPeriodicTimer().
GetSpellInfo()
SpellInfo const* AuraEffect::GetSpellInfo () const inline
Definition at line 47 of file SpellAuraEffects.h.
 { return m_spellInfo; }
References m_spellInfo.
Referenced by Player::_ApplyWeaponDependentAuraCritMod(), Player::_ApplyWeaponDependentAuraDamageMod(), AuraApplication::_HandleEffect(), Unit::CalcAbsorbResist(), CalcPeriodicCritChance(), CalculateAmount(), CalculatePeriodic(), CalculatePeriodicData(), spell_dru_treant_scaling::CalculateResistanceAmount(), spell_hun_generic_scaling::CalculateResistanceAmount(), spell_mage_pet_scaling::CalculateResistanceAmount(), spell_pri_shadowfiend_scaling::CalculateResistanceAmount(), spell_sha_feral_spirit_scaling::CalculateResistanceAmount(), spell_sha_fire_elemental_scaling::CalculateResistanceAmount(), spell_warl_generic_scaling::CalculateResistanceAmount(), spell_warl_infernal_scaling::CalculateResistanceAmount(), CalculateSpellMod(), spell_dk_pet_scaling::CalculateStatAmount(), spell_dru_treant_scaling::CalculateStatAmount(), spell_hun_generic_scaling::CalculateStatAmount(), spell_mage_pet_scaling::CalculateStatAmount(), spell_pri_shadowfiend_scaling::CalculateStatAmount(), spell_sha_feral_spirit_scaling::CalculateStatAmount(), spell_sha_fire_elemental_scaling::CalculateStatAmount(), spell_warl_generic_scaling::CalculateStatAmount(), spell_warl_infernal_scaling::CalculateStatAmount(), Spell::EffectHeal(), Spell::EffectSchoolDMG(), HandleAuraDummy(), HandleAuraModEffectImmunity(), HandleAuraModSchoolImmunity(), HandleAuraModShapeshift(), HandleAuraModStateImmunity(), HandleAuraModWeaponCritPercent(), HandleAuraMounted(), Unit::HandleAuraRaidProcFromCharge(), Unit::HandleAuraRaidProcFromChargeWithValue(), HandleAuraTransform(), HandleChannelDeathItem(), spell_dk_raise_ally::HandleDummy(), Unit::HandleDummyAuraProc(), HandleModDamageDone(), HandleModDamagePercentDone(), HandleModMechanicImmunity(), HandleModStateImmunityMask(), HandleObsModPowerAuraTick(), spell_putricide_unbound_plague_dmg::spell_putricide_unbound_plague_dmg_AuraScript::HandlePeriodic(), HandlePeriodicDamageAurasTick(), HandlePeriodicDummyAuraTick(), HandlePeriodicEnergizeAuraTick(), HandlePeriodicHealAurasTick(), HandlePeriodicHealthFunnelAuraTick(), HandlePeriodicHealthLeechAuraTick(), HandlePeriodicManaLeechAuraTick(), HandlePeriodicPowerBurnAuraTick(), HandlePeriodicTriggerSpellAuraTick(), HandlePeriodicTriggerSpellWithValueAuraTick(), spell_dk_blood_caked_blade::HandleProc(), spell_pal_seal_of_command_aura::HandleProc(), HandleProcTriggerDamageAuraProc(), Unit::HandleProcTriggerSpell(), HandleProcTriggerSpellAuraProc(), HandleProcTriggerSpellWithValueAuraProc(), HandleRaidProcFromChargeAuraProc(), HandleRaidProcFromChargeWithValueAuraProc(), TriggeredByAuraSpellData::Init(), Acore::AbsorbAuraOrderPred::operator()(), spell_optic_link::spell_optic_linkAuraScript::PrepareAuraScript(), Unit::ProcDamageAndSpellFor(), Player::RestoreBaseRune(), Unit::SendPeriodicAuraLog(), Player::UpdateAttackPowerAndDamage(), UpdatePeriodic(), and SpellInfo::ValidateAttribute6SpellDamageMods().
GetSpellModifier()
SpellModifier* AuraEffect::GetSpellModifier () const inline
Definition at line 45 of file SpellAuraEffects.h.
 { return m_spellmod; }
References m_spellmod.
GetTargetList()
void AuraEffect::GetTargetList (std::list< Unit * > & targetList) const
Definition at line 410 of file SpellAuraEffects.cpp.
 {
     Aura::ApplicationMap const& targetMap = GetBase()->GetApplicationMap();
     // remove all targets which were not added to new list - they no longer deserve area aura
     for (Aura::ApplicationMap::const_iterator appIter = targetMap.begin(); appIter != targetMap.end(); ++appIter)
     {
         if (appIter->second->HasEffect(GetEffIndex()))
             targetList.push_back(appIter->second->GetTarget());
     }
 }
References Aura::GetApplicationMap(), GetBase(), and GetEffIndex().
GetTickNumber()
uint32 AuraEffect::GetTickNumber () const inline
Definition at line 79 of file SpellAuraEffects.h.
 { return m_tickNumber; }
References m_tickNumber.
Referenced by Unit::CastDelayedSpellWithPeriodicAmount(), spell_frost_tomb::spell_frost_tombAuraScript::HandleEffectPeriodic(), spell_quest_test_flight_charging::HandleEffectPeriodicPlatform(), spell_quest_test_flight_charging::HandleEffectPeriodicSelf(), spell_hallows_end_base_fire::spell_hallows_end_base_fire_AuraScript::HandleEffectPeriodicUpdate(), spell_gen_burn_brutallus::HandleEffectPeriodicUpdate(), spell_putricide_unbound_plague_dmg::spell_putricide_unbound_plague_dmg_AuraScript::HandlePeriodic(), HandlePeriodicHealAurasTick(), spell_bronjahm_soulstorm_channel_ooc::spell_bronjahm_soulstorm_channel_ooc_AuraScript::HandlePeriodicTick(), spell_bronjahm_soulstorm_visual::spell_bronjahm_soulstorm_visual_AuraScript::HandlePeriodicTick(), spell_wailing_souls_periodic::spell_wailing_souls_periodic_AuraScript::HandlePeriodicTick(), spell_exploding_orb_auto_grow::spell_exploding_orb_auto_grow_AuraScript::HandlePeriodicTick(), spell_item_direbrew_remote_aura::HandlePeriodicTick(), HandlePeriodicTriggerSpellAuraTick(), spell_igb_rocket_pack::spell_igb_rocket_pack_AuraScript::HandleRemove(), TriggeredByAuraSpellData::Init(), spell_kalecgos_curse_of_boundless_agony::spell_kalecgos_curse_of_boundless_agony_AuraScript::OnPeriodic(), spell_muru_darkness::spell_muru_darkness_AuraScript::OnPeriodic(), spell_the_lich_king_vile_spirits::spell_the_lich_king_vile_spirits_AuraScript::OnPeriodic(), spell_the_lich_king_soul_rip::spell_the_lich_king_soul_rip_AuraScript::OnPeriodic(), spell_assembly_rune_of_summoning::spell_assembly_rune_of_summoning_AuraScript::OnPeriodic(), spell_illidan_demon_transform2::spell_illidan_demon_transform2_AuraScript::OnPeriodic(), spell_the_lich_king_infest::spell_the_lich_king_infest_AuraScript::OnUpdate(), spell_karazhan_overload::spell_karazhan_overload_AuraScript::PeriodicTick(), spell_geddon_inferno::spell_geddon_inferno_AuraScript::PeriodicTick(), spell_trollgore_corpse_explode::spell_trollgore_corpse_explode_AuraScript::PeriodicTick(), spell_blood_queen_pact_of_the_darkfallen_dmg::spell_blood_queen_pact_of_the_darkfallen_dmg_AuraScript::PeriodicTick(), spell_igb_explosion_main::spell_igb_explosion_main_AuraScript::PeriodicTick(), spell_dreamwalker_mana_void::spell_dreamwalker_mana_void_AuraScript::PeriodicTick(), spell_broggok_poison_cloud::spell_broggok_poison_cloud_AuraScript::PeriodicTick(), spell_hodir_biting_cold_main_aura::spell_hodir_biting_cold_main_aura_AuraScript::PrepareAuraScript(), spell_hodir_flash_freeze::spell_hodir_flash_freeze_AuraScript::PrepareAuraScript(), spell_icc_yh_volley::spell_icc_yh_volley_AuraScript::PrepareAuraScript(), spell_ignis_scorch::spell_ignis_scorch_AuraScript::PrepareAuraScript(), spell_mimiron_rapid_burst::spell_mimiron_rapid_burst_AuraScript::PrepareAuraScript(), spell_optic_link::spell_optic_linkAuraScript::PrepareAuraScript(), spell_pos_blight::spell_pos_blightAuraScript::PrepareAuraScript(), spell_gen_holiday_buff_food::TriggerFoodBuff(), spell_mother_shahraz_random_periodic::spell_mother_shahraz_random_periodic_AuraScript::Update(), and spell_mother_shahraz_fatal_attraction_aura::spell_mother_shahraz_fatal_attraction_aura_AuraScript::Update().
GetTotalTicks()
int32 AuraEffect::GetTotalTicks () const inline
Definition at line 80 of file SpellAuraEffects.h.
 { return m_amplitude ? (GetBase()->GetMaxDuration() / m_amplitude) : 1;}
References GetBase(), Aura::GetMaxDuration(), and m_amplitude.
Referenced by spell_dru_innervate::CalculateAmount(), spell_dru_insect_swarm::CalculateAmount(), spell_gen_lifeblood::CalculateAmount(), spell_gen_gift_of_naaru::CalculateAmount(), Unit::CastDelayedSpellWithPeriodicAmount(), spell_pri_renew::HandleApplyEffect(), Aura::HandleAuraSpecificMods(), HandlePeriodicDamageAurasTick(), HandlePeriodicHealAurasTick(), spell_hun_chimera_shot::HandleScriptEffect(), spell_broggok_poison_cloud::spell_broggok_poison_cloud_AuraScript::PeriodicTick(), spell_hodir_flash_freeze::spell_hodir_flash_freeze_AuraScript::PrepareAuraScript(), spell_ignis_scorch::spell_ignis_scorch_AuraScript::PrepareAuraScript(), and spell_pos_blight::spell_pos_blightAuraScript::PrepareAuraScript().
HandleArenaPreparation()
void AuraEffect::HandleArenaPreparation (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4921 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     if (apply)
         target->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PREPARATION);
     else
     {
         // do not remove unit flag if there are more than this auraEffect of that kind on unit on unit
         if (target->HasAuraType(GetAuraType()))
             return;
         target->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PREPARATION);
     }
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_REAL, GetAuraType(), AuraApplication::GetTarget(), Unit::HasAuraType(), Object::RemoveFlag(), Object::SetFlag(), UNIT_FIELD_FLAGS, and UNIT_FLAG_PREPARATION.
HandleAuraAllowFlight()
void AuraEffect::HandleAuraAllowFlight (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 2854 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     if (!apply)
     {
         // do not remove unit flag if there are more than this auraEffect of that kind on unit on unit
         if (target->HasAuraType(GetAuraType()) || target->HasAuraType(SPELL_AURA_MOD_INCREASE_MOUNTED_FLIGHT_SPEED))
             return;
     }
     target->SetCanFly(apply);
     if (!apply && target->GetTypeId() == TYPEID_UNIT && !target->IsLevitating())
         target->GetMotionMaster()->MoveFall();
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK, GetAuraType(), Unit::GetMotionMaster(), AuraApplication::GetTarget(), Object::GetTypeId(), Unit::HasAuraType(), Unit::IsLevitating(), MotionMaster::MoveFall(), Unit::SetCanFly(), SPELL_AURA_MOD_INCREASE_MOUNTED_FLIGHT_SPEED, and TYPEID_UNIT.
HandleAuraAllowOnlyAbility()
void AuraEffect::HandleAuraAllowOnlyAbility (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 2650 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() == TYPEID_PLAYER)
     {
         if (apply)
             target->SetFlag(PLAYER_FLAGS, PLAYER_ALLOW_ONLY_ABILITY);
         else
         {
             // do not remove unit flag if there are more than this auraEffect of that kind on unit on unit
             if (target->HasAuraType(SPELL_AURA_ALLOW_ONLY_ABILITY))
                 return;
             target->RemoveFlag(PLAYER_FLAGS, PLAYER_ALLOW_ONLY_ABILITY);
         }
     }
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK, AuraApplication::GetTarget(), Object::GetTypeId(), Unit::HasAuraType(), PLAYER_ALLOW_ONLY_ABILITY, PLAYER_FLAGS, Object::RemoveFlag(), Object::SetFlag(), SPELL_AURA_ALLOW_ONLY_ABILITY, and TYPEID_PLAYER.
HandleAuraCloneCaster()
void AuraEffect::HandleAuraCloneCaster (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 2346 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     if (apply)
     {
         Unit* caster = GetCaster();
         if (!caster || caster == target)
             return;
         // What must be cloned? at least display and scale
         target->SetDisplayId(caster->GetDisplayId());
         target->SetFlag(UNIT_FIELD_FLAGS_2, UNIT_FLAG2_MIRROR_IMAGE);
     }
     else
     {
         target->SetDisplayId(target->GetNativeDisplayId());
         target->RemoveFlag(UNIT_FIELD_FLAGS_2, UNIT_FLAG2_MIRROR_IMAGE);
     }
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK, GetCaster(), Unit::GetDisplayId(), Unit::GetNativeDisplayId(), AuraApplication::GetTarget(), Object::RemoveFlag(), Unit::SetDisplayId(), Object::SetFlag(), UNIT_FIELD_FLAGS_2, and UNIT_FLAG2_MIRROR_IMAGE.
HandleAuraControlVehicle()
void AuraEffect::HandleAuraControlVehicle (AuraApplication const * aurApp, uint8 mode, bool apply) const
Such auras are applied from a caster(=player) to a vehicle. This has been verified using spell #49256
Definition at line 3198 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     if (!target->IsVehicle())
         return;
     Unit* caster = GetCaster();
     if (!caster || caster == target)
         return;
     if (apply)
     {
         // Currently spells that have base points  0 and DieSides 0 = "0/0" exception are pushed to -1,
         // however the idea of 0/0 is to ingore flag VEHICLE_SEAT_FLAG_CAN_ENTER_OR_EXIT and -1 checks for it,
         // so this break such spells or most of them.
         // Current formula about m_amount: effect base points + dieside - 1
         // TO DO: Reasearch more about 0/0 and fix it.
         caster->_EnterVehicle(target->GetVehicleKit(), m_amount - 1, aurApp);
     }
     else
     {
         if (GetId() == 53111) // Devour Humanoid
         {
             Unit::Kill(target, caster);
             if (caster->GetTypeId() == TYPEID_UNIT)
                 caster->ToCreature()->RemoveCorpse();
         }
         caster->_ExitVehicle();
         // some SPELL_AURA_CONTROL_VEHICLE auras have a dummy effect on the player - remove them
         caster->RemoveAurasDueToSpell(GetId());
     }
 }
References Unit::_EnterVehicle(), Unit::_ExitVehicle(), ByteConverter::apply(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, GetCaster(), GetId(), AuraApplication::GetTarget(), Object::GetTypeId(), Unit::GetVehicleKit(), Unit::IsVehicle(), Unit::Kill(), m_amount, Unit::RemoveAurasDueToSpell(), Creature::RemoveCorpse(), Object::ToCreature(), and TYPEID_UNIT.
HandleAuraConvertRune()
void AuraEffect::HandleAuraConvertRune (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 5565 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     Player* player = target->ToPlayer();
     if (player->getClass() != CLASS_DEATH_KNIGHT)
         return;
     uint32 runes = m_amount;
     // convert number of runes specified in aura amount of rune type in miscvalue to runetype in miscvalueb
     if (apply)
     {
         for (uint32 i = 0; i < MAX_RUNES && runes; ++i)
         {
             if (GetMiscValue() != player->GetCurrentRune(i))
                 continue;
             if (!player->GetRuneCooldown(i))
             {
                 player->AddRuneByAuraEffect(i, RuneType(GetMiscValueB()), this);
                 --runes;
             }
         }
     }
     else
         player->RemoveRunesByAuraEffect(this);
 }
References Player::AddRuneByAuraEffect(), ByteConverter::apply(), AURA_EFFECT_HANDLE_REAL, CLASS_DEATH_KNIGHT, Unit::getClass(), Player::GetCurrentRune(), GetMiscValue(), GetMiscValueB(), Player::GetRuneCooldown(), AuraApplication::GetTarget(), Object::GetTypeId(), m_amount, MAX_RUNES, Player::RemoveRunesByAuraEffect(), Object::ToPlayer(), and TYPEID_PLAYER.
HandleAuraDummy()
void AuraEffect::HandleAuraDummy (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4980 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_REAPPLY)))
         return;
     Unit* target = aurApp->GetTarget();
     Unit* caster = GetCaster();
     if (mode & AURA_EFFECT_HANDLE_REAL)
     {
         // pet auras
         if (PetAura const* petSpell = sSpellMgr->GetPetAura(GetId(), m_effIndex))
         {
             if (apply)
                 target->AddPetAura(petSpell);
             else
                 target->RemovePetAura(petSpell);
         }
     }
     if (mode & (AURA_EFFECT_HANDLE_REAL | AURA_EFFECT_HANDLE_REAPPLY))
     {
         // AT APPLY
         if (apply)
         {
             switch (GetId())
             {
                 case 1515:                                      // Tame beast
                     // FIX_ME: this is 2.0.12 threat effect replaced in 2.1.x by dummy aura, must be checked for correctness
                     if (caster && target->CanHaveThreatList())
                         target->AddThreat(caster, 10.0f);
                     break;
                 case 13139:                                     // net-o-matic
                     // root to self part of (root_target->charge->root_self sequence
                     if (caster)
                         caster->CastSpell(caster, 13138, true, nullptr, this);
                     break;
                 case 34026:   // kill command
                     {
                         Unit* pet = target->GetGuardianPet();
                         if (!pet)
                             break;
                         target->CastSpell(target, 34027, true, nullptr, this);
                         // set 3 stacks and 3 charges (to make all auras not disappear at once)
                         Aura* owner_aura = target->GetAura(34027, GetCasterGUID());
                         Aura* pet_aura  = pet->GetAura(58914, GetCasterGUID());
                         if (owner_aura)
{
                             owner_aura->SetCharges(0);
                             owner_aura->SetStackAmount(owner_aura->GetSpellInfo()->StackAmount);
                             if (pet_aura)
{
                                 pet_aura->SetCharges(0);
                                 pet_aura->SetStackAmount(owner_aura->GetSpellInfo()->StackAmount);
                             }
                         }
                         break;
                     }
                 case 37096:                                     // Blood Elf Illusion
                     {
                         if (caster)
{
                             switch (caster->getGender())
{
                                 case GENDER_FEMALE:
                                     caster->CastSpell(target, 37095, true, nullptr, this); // Blood Elf Disguise
                                     break;
                                 case GENDER_MALE:
                                     caster->CastSpell(target, 37093, true, nullptr, this);
                                     break;
                                 default:
                                     break;
                             }
                         }
                         break;
                     }
                 case 55198:   // Tidal Force
                     {
                         target->CastSpell(target, 55166, true);
                         if (Aura* owner_aura = target->GetAura(55166))
                             owner_aura->SetStackAmount(owner_aura->GetSpellInfo()->StackAmount);
                         return;
                     }
                 case 39850:                                     // Rocket Blast
                     if (roll_chance_i(20))                       // backfire stun
                         target->CastSpell(target, 51581, true, nullptr, this);
                     break;
                 case 43873:                                     // Headless Horseman Laugh
                     target->PlayDistanceSound(11965);
                     break;
                 case 46354:                                     // Blood Elf Illusion
                     if (caster)
                     {
                         switch (caster->getGender())
{
                             case GENDER_FEMALE:
                                 caster->CastSpell(target, 46356, true, nullptr, this);
                                 break;
                             case GENDER_MALE:
                                 caster->CastSpell(target, 46355, true, nullptr, this);
                                 break;
                         }
                     }
                     break;
                 case 46361:                                     // Reinforced Net
                     if (caster)
                         target->GetMotionMaster()->MoveFall();
                     break;
                 case 46699:                                     // Requires No Ammo
                     if (target->GetTypeId() == TYPEID_PLAYER)
                         target->ToPlayer()->RemoveAmmo();      // not use ammo and not allow use
                     break;
                 case 71563:
                     {
                         if (Aura* newAura = target->AddAura(71564, target))
                             newAura->SetStackAmount(newAura->GetSpellInfo()->StackAmount);
                         return;
                     }
             }
         }
         // AT REMOVE
         else
         {
             if ((GetSpellInfo()->IsQuestTame()) && caster && caster->IsAlive() && target->IsAlive() && aurApp->GetRemoveMode() != AURA_REMOVE_BY_CANCEL)
             {
                 uint32 finalSpelId = 0;
                 switch (GetId())
                 {
                     case 19548:
                         finalSpelId = 19597;
                         break;
                     case 19674:
                         finalSpelId = 19677;
                         break;
                     case 19687:
                         finalSpelId = 19676;
                         break;
                     case 19688:
                         finalSpelId = 19678;
                         break;
                     case 19689:
                         finalSpelId = 19679;
                         break;
                     case 19692:
                         finalSpelId = 19680;
                         break;
                     case 19693:
                         finalSpelId = 19684;
                         break;
                     case 19694:
                         finalSpelId = 19681;
                         break;
                     case 19696:
                         finalSpelId = 19682;
                         break;
                     case 19697:
                         finalSpelId = 19683;
                         break;
                     case 19699:
                         finalSpelId = 19685;
                         break;
                     case 19700:
                         finalSpelId = 19686;
                         break;
                     case 30646:
                         finalSpelId = 30647;
                         break;
                     case 30653:
                         finalSpelId = 30648;
                         break;
                     case 30654:
                         finalSpelId = 30652;
                         break;
                     case 30099:
                         finalSpelId = 30100;
                         break;
                     case 30102:
                         finalSpelId = 30103;
                         break;
                     case 30105:
                         finalSpelId = 30104;
                         break;
                 }
                 if (finalSpelId)
                     caster->CastSpell(target, finalSpelId, true, nullptr, this);
             }
             switch (m_spellInfo->SpellFamilyName)
             {
                 case SPELLFAMILY_GENERIC:
                     switch (GetId())
                     {
                         case 2584: // Waiting to Resurrect
                             // Waiting to resurrect spell cancel, we must remove player from resurrect queue
                             if (target->GetTypeId() == TYPEID_PLAYER)
{
                                 if (Battleground* bg = target->ToPlayer()->GetBattleground())
                                     bg->RemovePlayerFromResurrectQueue(target->ToPlayer());
                                 if(Battlefield* bf = sBattlefieldMgr->GetBattlefieldToZoneId(target->GetZoneId()))
                                     bf->RemovePlayerFromResurrectQueue(target->GetGUID());
                             }
                             break;
                         case 43681: // Inactive
{
                                 if (target->GetTypeId() != TYPEID_PLAYER || aurApp->GetRemoveMode() != AURA_REMOVE_BY_EXPIRE)
                                     return;
                                 if (target->GetMap()->IsBattleground())
                                     target->ToPlayer()->LeaveBattleground();
                                 break;
                             }
                         case 52172:  // Coyote Spirit Despawn Aura
                         case 60244:  // Blood Parrot Despawn Aura
                             target->CastSpell((Unit*)nullptr, GetAmount(), true, nullptr, this);
                             break;
                         // Halls of Lightning, Arc Lightning
                         case 52921:
{
                                 if( aurApp->GetRemoveMode() != AURA_REMOVE_BY_EXPIRE )
                                     return;
                                 Player* player = nullptr;
                                 Acore::AnyPlayerInObjectRangeCheck checker(target, 10.0f);
                                 Acore::PlayerSearcher<Acore::AnyPlayerInObjectRangeCheck> searcher(target, player, checker);
                                 Cell::VisitWorldObjects(target, searcher, 10.0f);
                                 if( player && player->GetGUID() != target->GetGUID() )
                                     target->CastSpell(player, 52921, true);
                                 return;
                             }
                         case 58600: // Restricted Flight Area
                         case 58730: // Restricted Flight Area
                             if (aurApp->GetRemoveMode() == AURA_REMOVE_BY_EXPIRE)
                                 target->CastSpell(target, 58601, true);
                             break;
                         case 46374: // quest The Power of the Elements (11893)
{
                                 if (target->isDead() && GetBase() && target->GetTypeId() == TYPEID_UNIT && target->GetEntry() == 24601)
{
                                     auto caster2 = GetBase()->GetCaster();
                                     if (caster2 && caster2->GetTypeId() == TYPEID_PLAYER)
{
                                         caster2->ToPlayer()->KilledMonsterCredit(25987);
                                     }
                                 }
                                 return;
                             }
                     }
                     break;
                 default:
                     break;
             }
         }
     }
     // AT APPLY & REMOVE
     switch (m_spellInfo->SpellFamilyName)
     {
         case SPELLFAMILY_GENERIC:
             {
                 if (!(mode & AURA_EFFECT_HANDLE_REAL))
                     break;
                 switch (GetId())
                 {
                     // Recently Bandaged
                     case 11196:
                         target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, GetMiscValue(), apply);
                         break;
                     // Unstable Power
                     case 24658:
{
                             uint32 spellId = 24659;
                             if (apply && caster)
{
                                 SpellInfo const* spell = sSpellMgr->AssertSpellInfo(spellId);
                                 for (uint32 i = 0; i < spell->StackAmount; ++i)
                                     caster->CastSpell(target, spell->Id, true, nullptr, nullptr, GetCasterGUID());
                                 break;
                             }
                             target->RemoveAurasDueToSpell(spellId);
                             break;
                         }
                     // Restless Strength
                     case 24661:
{
                             uint32 spellId = 24662;
                             if (apply && caster)
{
                                 SpellInfo const* spell = sSpellMgr->AssertSpellInfo(spellId);
                                 for (uint32 i = 0; i < spell->StackAmount; ++i)
                                     caster->CastSpell(target, spell->Id, true, nullptr, nullptr, GetCasterGUID());
                                 break;
                             }
                             target->RemoveAurasDueToSpell(spellId);
                             break;
                         }
                     // Tag Murloc
                     case 30877:
{
                             // Tag/untag Blacksilt Scout
                             target->SetEntry(apply ? 17654 : 17326);
                             break;
                         }
                     case 57819: // Argent Champion
                     case 57820: // Ebon Champion
                     case 57821: // Champion of the Kirin Tor
                     case 57822: // Wyrmrest Champion
{
                             if (!caster || caster->GetTypeId() != TYPEID_PLAYER)
                                 break;
                             uint32 FactionID = 0;
                             if (apply)
{
                                 switch (m_spellInfo->Id)
{
                                     case 57819:
                                         FactionID = 1106;
                                         break; // Argent Crusade
                                     case 57820:
                                         FactionID = 1098;
                                         break; // Knights of the Ebon Blade
                                     case 57821:
                                         FactionID = 1090;
                                         break; // Kirin Tor
                                     case 57822:
                                         FactionID = 1091;
                                         break; // The Wyrmrest Accord
                                 }
                             }
                             caster->ToPlayer()->SetChampioningFaction(FactionID);
                             break;
                         }
                     // LK Intro VO (1)
                     case 58204:
                         if (target->GetTypeId() == TYPEID_PLAYER)
{
                             // Play part 1
                             if (apply)
                                 target->PlayDirectSound(14970, target->ToPlayer());
                             // continue in 58205
                             else
                                 target->CastSpell(target, 58205, true);
                         }
                         break;
                     // LK Intro VO (2)
                     case 58205:
                         if (target->GetTypeId() == TYPEID_PLAYER)
{
                             // Play part 2
                             if (apply)
                                 target->PlayDirectSound(14971, target->ToPlayer());
                             // Play part 3
                             else
                                 target->PlayDirectSound(14972, target->ToPlayer());
                         }
                         break;
                     case 62061: // Festive Holiday Mount
                         if (target->HasAuraType(SPELL_AURA_MOUNTED))
{
                             uint32 creatureEntry = 0;
                             if (apply)
{
                                 if (target->HasAuraType(SPELL_AURA_MOD_INCREASE_MOUNTED_FLIGHT_SPEED))
                                     creatureEntry = 24906;
                                 else
                                     creatureEntry = 15665;
                             }
                             else
                                 creatureEntry = target->GetAuraEffectsByType(SPELL_AURA_MOUNTED).front()->GetMiscValue();
                             if (CreatureTemplate const* creatureInfo = sObjectMgr->GetCreatureTemplate(creatureEntry))
{
                                 uint32 displayID = ObjectMgr::ChooseDisplayId(creatureInfo);
                                 sObjectMgr->GetCreatureModelRandomGender(&displayID);
                                 target->SetUInt32Value(UNIT_FIELD_MOUNTDISPLAYID, displayID);
                             }
                         }
                         break;
                 }
                 break;
             }
         case SPELLFAMILY_MAGE:
             {
                 //if (!(mode & AURA_EFFECT_HANDLE_REAL))
                 //break;
                 break;
             }
         case SPELLFAMILY_PRIEST:
             {
                 //if (!(mode & AURA_EFFECT_HANDLE_REAL))
                 //break;
                 break;
             }
         case SPELLFAMILY_DRUID:
             {
                 //if (!(mode & AURA_EFFECT_HANDLE_REAL))
                 //    break;
                 break;
             }
         case SPELLFAMILY_SHAMAN:
             {
                 //if (!(mode & AURA_EFFECT_HANDLE_REAL))
                 //    break;
                 break;
             }
     }
 }
References Unit::AddAura(), Unit::AddPetAura(), Unit::AddThreat(), ByteConverter::apply(), Unit::ApplySpellImmune(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_REAL, AURA_EFFECT_HANDLE_REAPPLY, AURA_REMOVE_BY_CANCEL, AURA_REMOVE_BY_EXPIRE, bg(), Unit::CanHaveThreatList(), Unit::CastSpell(), ObjectMgr::ChooseDisplayId(), GENDER_FEMALE, GENDER_MALE, GetAmount(), Unit::GetAura(), Unit::GetAuraEffectsByType(), GetBase(), Player::GetBattleground(), GetCaster(), Aura::GetCaster(), GetCasterGUID(), Object::GetEntry(), Unit::getGender(), Unit::GetGuardianPet(), Object::GetGUID(), GetId(), WorldObject::GetMap(), GetMiscValue(), Unit::GetMotionMaster(), AuraApplication::GetRemoveMode(), GetSpellInfo(), Aura::GetSpellInfo(), AuraApplication::GetTarget(), Object::GetTypeId(), WorldObject::GetZoneId(), Unit::HasAuraType(), SpellInfo::Id, IMMUNITY_MECHANIC, Unit::IsAlive(), Map::IsBattleground(), Unit::isDead(), Player::KilledMonsterCredit(), Player::LeaveBattleground(), m_effIndex, m_spellInfo, MotionMaster::MoveFall(), WorldObject::PlayDirectSound(), WorldObject::PlayDistanceSound(), Player::RemoveAmmo(), Unit::RemoveAurasDueToSpell(), Unit::RemovePetAura(), roll_chance_i(), sBattlefieldMgr, Player::SetChampioningFaction(), Aura::SetCharges(), Object::SetEntry(), Aura::SetStackAmount(), Object::SetUInt32Value(), sObjectMgr, SPELL_AURA_MOD_INCREASE_MOUNTED_FLIGHT_SPEED, SPELL_AURA_MOUNTED, SPELLFAMILY_DRUID, SPELLFAMILY_GENERIC, SPELLFAMILY_MAGE, SPELLFAMILY_PRIEST, SPELLFAMILY_SHAMAN, SpellInfo::SpellFamilyName, sSpellMgr, SpellInfo::StackAmount, Object::ToPlayer(), TYPEID_PLAYER, TYPEID_UNIT, UNIT_FIELD_MOUNTDISPLAYID, and Cell::VisitWorldObjects().
HandleAuraEmpathy()
void AuraEffect::HandleAuraEmpathy (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 5508 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     if (!apply)
     {
         // do not remove unit flag if there are more than this auraEffect of that kind on unit on unit
         if (target->HasAuraType(GetAuraType()))
             return;
     }
     if (target->GetCreatureType() == CREATURE_TYPE_BEAST)
         target->ApplyModUInt32Value(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_SPECIALINFO, apply);
 }
References ByteConverter::apply(), Object::ApplyModUInt32Value(), AURA_EFFECT_HANDLE_REAL, CREATURE_TYPE_BEAST, GetAuraType(), Unit::GetCreatureType(), AuraApplication::GetTarget(), Unit::HasAuraType(), UNIT_DYNAMIC_FLAGS, and UNIT_DYNFLAG_SPECIALINFO.
HandleAuraFeatherFall()
void AuraEffect::HandleAuraFeatherFall (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 2896 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     if (Player* targetPlayer = target->ToPlayer())
     {
         sScriptMgr->AnticheatSetUnderACKmount(targetPlayer);
     }
     if (!apply)
     {
         // do not remove unit flag if there are more than this auraEffect of that kind on unit on unit
         if (target->HasAuraType(GetAuraType()))
             return;
     }
     target->SetFeatherFall(apply);
     // start fall from current height
     if (!apply && target->GetTypeId() == TYPEID_PLAYER)
         target->ToPlayer()->SetFallInformation(time(nullptr), target->GetPositionZ());
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK, GetAuraType(), Position::GetPositionZ(), AuraApplication::GetTarget(), Object::GetTypeId(), Unit::HasAuraType(), Player::SetFallInformation(), Unit::SetFeatherFall(), sScriptMgr, Object::ToPlayer(), and TYPEID_PLAYER.
HandleAuraGhost()
void AuraEffect::HandleAuraGhost (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 1741 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     if (apply)
     {
         target->SetFlag(PLAYER_FLAGS, PLAYER_FLAGS_GHOST);
         target->m_serverSideVisibility.SetValue(SERVERSIDE_VISIBILITY_GHOST, GHOST_VISIBILITY_GHOST);
         target->m_serverSideVisibilityDetect.SetValue(SERVERSIDE_VISIBILITY_GHOST, GHOST_VISIBILITY_GHOST);
     }
     else
     {
         if (target->HasAuraType(SPELL_AURA_GHOST))
             return;
         target->RemoveFlag(PLAYER_FLAGS, PLAYER_FLAGS_GHOST);
         target->m_serverSideVisibility.SetValue(SERVERSIDE_VISIBILITY_GHOST, GHOST_VISIBILITY_ALIVE);
         target->m_serverSideVisibilityDetect.SetValue(SERVERSIDE_VISIBILITY_GHOST, GHOST_VISIBILITY_ALIVE);
     }
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK, AuraApplication::GetTarget(), Object::GetTypeId(), GHOST_VISIBILITY_ALIVE, GHOST_VISIBILITY_GHOST, Unit::HasAuraType(), WorldObject::m_serverSideVisibility, WorldObject::m_serverSideVisibilityDetect, PLAYER_FLAGS, PLAYER_FLAGS_GHOST, Object::RemoveFlag(), SERVERSIDE_VISIBILITY_GHOST, Object::SetFlag(), FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::SetValue(), SPELL_AURA_GHOST, and TYPEID_PLAYER.
HandleAuraHover()
void AuraEffect::HandleAuraHover (AuraApplication const * aurApp, uint8 mode, bool apply) const
Sets movementflags
Definition at line 2922 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     if (Player* targetPlayer = target->ToPlayer())
     {
         sScriptMgr->AnticheatSetUnderACKmount(targetPlayer);
     }
     if (!apply)
     {
         // do not remove unit flag if there are more than this auraEffect of that kind on unit on unit
         if (target->HasAuraType(GetAuraType()))
             return;
     }
     target->SetHover(apply);
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK, GetAuraType(), AuraApplication::GetTarget(), Unit::HasAuraType(), Unit::SetHover(), sScriptMgr, and Object::ToPlayer().
HandleAuraIncreaseBaseHealthPercent()
void AuraEffect::HandleAuraIncreaseBaseHealthPercent (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4367 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     target->HandleStatModifier(UNIT_MOD_HEALTH, BASE_PCT, float(GetAmount()), apply);
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, BASE_PCT, GetAmount(), AuraApplication::GetTarget(), Unit::HandleStatModifier(), and UNIT_MOD_HEALTH.
HandleAuraLinked()
void AuraEffect::HandleAuraLinked (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 5599 of file SpellAuraEffects.cpp.
 {
     Unit* target = aurApp->GetTarget();
     uint32 triggeredSpellId = sSpellMgr->GetSpellIdForDifficulty(m_spellInfo->Effects[m_effIndex].TriggerSpell, target);
     SpellInfo const* triggeredSpellInfo = sSpellMgr->GetSpellInfo(triggeredSpellId);
     if (!triggeredSpellInfo)
         return;
     if (mode & AURA_EFFECT_HANDLE_REAL)
     {
         if (apply)
         {
             Unit* caster = triggeredSpellInfo->NeedsToBeTriggeredByCaster(m_spellInfo, GetEffIndex()) ? GetCaster() : target;
             if (!caster)
                 return;
             // If amount avalible cast with basepoints (Crypt Fever for example)
             if (GetAmount())
                 caster->CastCustomSpell(target, triggeredSpellId, &m_amount, nullptr, nullptr, true, nullptr, this);
             else
                 caster->CastSpell(target, triggeredSpellId, true, nullptr, this);
         }
         else
         {
             ObjectGuid casterGUID = triggeredSpellInfo->NeedsToBeTriggeredByCaster(m_spellInfo, GetEffIndex()) ? GetCasterGUID() : target->GetGUID();
             target->RemoveAura(triggeredSpellId, casterGUID, 0, aurApp->GetRemoveMode());
         }
     }
     else if (mode & AURA_EFFECT_HANDLE_REAPPLY && apply)
     {
         ObjectGuid casterGUID = triggeredSpellInfo->NeedsToBeTriggeredByCaster(m_spellInfo, GetEffIndex()) ? GetCasterGUID() : target->GetGUID();
         // change the stack amount to be equal to stack amount of our aura
         if (Aura* triggeredAura = target->GetAura(triggeredSpellId, casterGUID))
             triggeredAura->ModStackAmount(GetBase()->GetStackAmount() - triggeredAura->GetStackAmount());
     }
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_REAL, AURA_EFFECT_HANDLE_REAPPLY, Unit::CastCustomSpell(), Unit::CastSpell(), SpellInfo::Effects, GetAmount(), Unit::GetAura(), GetBase(), GetCaster(), GetCasterGUID(), GetEffIndex(), Object::GetGUID(), AuraApplication::GetRemoveMode(), Aura::GetStackAmount(), AuraApplication::GetTarget(), m_amount, m_effIndex, m_spellInfo, SpellInfo::NeedsToBeTriggeredByCaster(), Unit::RemoveAura(), and sSpellMgr.
HandleAuraModAttackPower()
void AuraEffect::HandleAuraModAttackPower (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4669 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     target->HandleStatModifier(UNIT_MOD_ATTACK_POWER, TOTAL_VALUE, float(GetAmount()), apply);
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, GetAmount(), AuraApplication::GetTarget(), Unit::HandleStatModifier(), TOTAL_VALUE, and UNIT_MOD_ATTACK_POWER.
HandleAuraModAttackPowerOfArmor()
void AuraEffect::HandleAuraModAttackPowerOfArmor (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4734 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     // Recalculate bonus
     if (target->GetTypeId() == TYPEID_PLAYER)
         target->ToPlayer()->UpdateAttackPowerAndDamage(false);
 }
References AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, AuraApplication::GetTarget(), Object::GetTypeId(), Object::ToPlayer(), TYPEID_PLAYER, and Player::UpdateAttackPowerAndDamage().
Referenced by HandleAuraModAttackPowerOfStatPercent().
HandleAuraModAttackPowerOfStatPercent()
void AuraEffect::HandleAuraModAttackPowerOfStatPercent (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4729 of file SpellAuraEffects.cpp.
 {
     HandleAuraModAttackPowerOfArmor(aurApp, mode, apply);
 }
References ByteConverter::apply(), and HandleAuraModAttackPowerOfArmor().
HandleAuraModAttackPowerPercent()
void AuraEffect::HandleAuraModAttackPowerPercent (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4692 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     //UNIT_FIELD_ATTACK_POWER_MULTIPLIER = multiplier - 1
     target->HandleStatModifier(UNIT_MOD_ATTACK_POWER, TOTAL_PCT, float(GetAmount()), apply);
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, GetAmount(), AuraApplication::GetTarget(), Unit::HandleStatModifier(), TOTAL_PCT, and UNIT_MOD_ATTACK_POWER.
HandleAuraModBaseResistancePCT()
void AuraEffect::HandleAuraModBaseResistancePCT (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 3908 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     // only players have base stats
     if (target->GetTypeId() != TYPEID_PLAYER)
     {
         //pets only have base armor
         if (target->IsPet() && (GetMiscValue() & SPELL_SCHOOL_MASK_NORMAL))
             target->HandleStatModifier(UNIT_MOD_ARMOR, BASE_PCT, float(GetAmount()), apply);
     }
     else
     {
         for (int8 x = SPELL_SCHOOL_NORMAL; x < MAX_SPELL_SCHOOL; x++)
         {
             if (GetMiscValue() & int32(1 << x))
                 target->HandleStatModifier(UnitMods(UNIT_MOD_RESISTANCE_START + x), BASE_PCT, float(GetAmount()), apply);
         }
     }
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, BASE_PCT, GetAmount(), GetMiscValue(), AuraApplication::GetTarget(), Object::GetTypeId(), Unit::HandleStatModifier(), Unit::IsPet(), MAX_SPELL_SCHOOL, SPELL_SCHOOL_MASK_NORMAL, SPELL_SCHOOL_NORMAL, TYPEID_PLAYER, UNIT_MOD_ARMOR, UNIT_MOD_RESISTANCE_START, and G3D::x.
HandleAuraModBlockPercent()
void AuraEffect::HandleAuraModBlockPercent (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4410 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     target->ToPlayer()->UpdateBlockPercentage();
 }
References AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, AuraApplication::GetTarget(), Object::GetTypeId(), Object::ToPlayer(), TYPEID_PLAYER, and Player::UpdateBlockPercentage().
HandleAuraModCritPct()
void AuraEffect::HandleAuraModCritPct (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4518 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
     {
         target->m_baseSpellCritChance += (apply) ? GetAmount() : -GetAmount();
         return;
     }
     target->ToPlayer()->HandleBaseModValue(CRIT_PERCENTAGE,         FLAT_MOD, float (GetAmount()), apply);
     target->ToPlayer()->HandleBaseModValue(OFFHAND_CRIT_PERCENTAGE, FLAT_MOD, float (GetAmount()), apply);
     target->ToPlayer()->HandleBaseModValue(RANGED_CRIT_PERCENTAGE,  FLAT_MOD, float (GetAmount()), apply);
     // included in Player::UpdateSpellCritChance calculation
     target->ToPlayer()->UpdateAllSpellCritChances();
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, CRIT_PERCENTAGE, FLAT_MOD, GetAmount(), AuraApplication::GetTarget(), Object::GetTypeId(), Player::HandleBaseModValue(), Unit::m_baseSpellCritChance, OFFHAND_CRIT_PERCENTAGE, RANGED_CRIT_PERCENTAGE, Object::ToPlayer(), TYPEID_PLAYER, and Player::UpdateAllSpellCritChances().
HandleAuraModDecreaseSpeed()
void AuraEffect::HandleAuraModDecreaseSpeed (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 3315 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     target->UpdateSpeed(MOVE_WALK, true);
     target->UpdateSpeed(MOVE_RUN, true);
     target->UpdateSpeed(MOVE_SWIM, true);
     target->UpdateSpeed(MOVE_FLIGHT, true);
     target->UpdateSpeed(MOVE_RUN_BACK, true);
     target->UpdateSpeed(MOVE_SWIM_BACK, true);
     target->UpdateSpeed(MOVE_FLIGHT_BACK, true);
     if (Player* targetPlayer = target->ToPlayer())
     {
         sScriptMgr->AnticheatSetUnderACKmount(targetPlayer);
     }
 }
References AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AuraApplication::GetTarget(), MOVE_FLIGHT, MOVE_FLIGHT_BACK, MOVE_RUN, MOVE_RUN_BACK, MOVE_SWIM, MOVE_SWIM_BACK, MOVE_WALK, sScriptMgr, Object::ToPlayer(), and Unit::UpdateSpeed().
HandleAuraModDisarm()
void AuraEffect::HandleAuraModDisarm (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 2517 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     AuraType type = GetAuraType();
     //Prevent handling aura twice
     if ((apply) ? target->GetAuraEffectsByType(type).size() > 1 : target->HasAuraType(type))
         return;
     uint32 field, flag, slot;
     WeaponAttackType attType;
     switch (type)
     {
         case SPELL_AURA_MOD_DISARM:
             field = UNIT_FIELD_FLAGS;
             flag = UNIT_FLAG_DISARMED;
             slot = EQUIPMENT_SLOT_MAINHAND;
             attType = BASE_ATTACK;
             break;
         case SPELL_AURA_MOD_DISARM_OFFHAND:
             field = UNIT_FIELD_FLAGS_2;
             flag = UNIT_FLAG2_DISARM_OFFHAND;
             slot = EQUIPMENT_SLOT_OFFHAND;
             attType = OFF_ATTACK;
             break;
         case SPELL_AURA_MOD_DISARM_RANGED:
             field = UNIT_FIELD_FLAGS_2;
             flag = UNIT_FLAG2_DISARM_RANGED;
             slot = EQUIPMENT_SLOT_RANGED;
             attType = RANGED_ATTACK;
             break;
         default:
             return;
     }
     // if disarm aura is to be removed, remove the flag first to reapply damage/aura mods
     if (!apply)
         target->RemoveFlag(field, flag);
     // Handle damage modification, shapeshifted druids are not affected
     if (target->GetTypeId() == TYPEID_PLAYER && (!target->IsInFeralForm() || target->GetShapeshiftForm() == FORM_GHOSTWOLF))
     {
         if (Item* pItem = target->ToPlayer()->GetItemByPos(INVENTORY_SLOT_BAG_0, slot))
         {
             uint8 attacktype = Player::GetAttackBySlot(slot);
             if (attacktype < MAX_ATTACK)
             {
                 target->ToPlayer()->_ApplyWeaponDamage(slot, pItem->GetTemplate(), nullptr, !apply);
                 target->ToPlayer()->_ApplyWeaponDependentAuraMods(pItem, WeaponAttackType(attacktype), !apply);
             }
         }
     }
     // if disarm effects should be applied, wait to set flag until damage mods are unapplied
     if (apply)
         target->SetFlag(field, flag);
     if (target->GetTypeId() == TYPEID_UNIT && target->ToCreature()->GetCurrentEquipmentId())
         target->UpdateDamagePhysical(attType);
 }
References Player::_ApplyWeaponDamage(), Player::_ApplyWeaponDependentAuraMods(), ByteConverter::apply(), AURA_EFFECT_HANDLE_REAL, BASE_ATTACK, EQUIPMENT_SLOT_MAINHAND, EQUIPMENT_SLOT_OFFHAND, EQUIPMENT_SLOT_RANGED, FORM_GHOSTWOLF, Player::GetAttackBySlot(), Unit::GetAuraEffectsByType(), GetAuraType(), Creature::GetCurrentEquipmentId(), Player::GetItemByPos(), Unit::GetShapeshiftForm(), AuraApplication::GetTarget(), Object::GetTypeId(), Unit::HasAuraType(), INVENTORY_SLOT_BAG_0, Unit::IsInFeralForm(), MAX_ATTACK, OFF_ATTACK, RANGED_ATTACK, Object::RemoveFlag(), Object::SetFlag(), SPELL_AURA_MOD_DISARM, SPELL_AURA_MOD_DISARM_OFFHAND, SPELL_AURA_MOD_DISARM_RANGED, Object::ToCreature(), Object::ToPlayer(), TYPEID_PLAYER, TYPEID_UNIT, UNIT_FIELD_FLAGS, UNIT_FIELD_FLAGS_2, UNIT_FLAG2_DISARM_OFFHAND, UNIT_FLAG2_DISARM_RANGED, UNIT_FLAG_DISARMED, and Unit::UpdateDamagePhysical().
HandleAuraModDispelImmunity()
void AuraEffect::HandleAuraModDispelImmunity (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 3849 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     target->ApplySpellDispelImmunity(m_spellInfo, DispelType(GetMiscValue()), (apply));
 }
References ByteConverter::apply(), Unit::ApplySpellDispelImmunity(), AURA_EFFECT_HANDLE_REAL, GetMiscValue(), AuraApplication::GetTarget(), and m_spellInfo.
HandleAuraModDmgImmunity()
void AuraEffect::HandleAuraModDmgImmunity (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 3839 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     target->ApplySpellImmune(GetId(), IMMUNITY_DAMAGE, GetMiscValue(), apply);
 }
References ByteConverter::apply(), Unit::ApplySpellImmune(), AURA_EFFECT_HANDLE_REAL, GetId(), GetMiscValue(), AuraApplication::GetTarget(), and IMMUNITY_DAMAGE.
HandleAuraModDodgePercent()
void AuraEffect::HandleAuraModDodgePercent (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4397 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     target->ToPlayer()->UpdateDodgePercentage();
 }
References AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, AuraApplication::GetTarget(), Object::GetTypeId(), Object::ToPlayer(), TYPEID_PLAYER, and Player::UpdateDodgePercentage().
HandleAuraModEffectImmunity()
void AuraEffect::HandleAuraModEffectImmunity (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 3744 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     target->ApplySpellImmune(GetId(), IMMUNITY_EFFECT, GetMiscValue(), apply);
     // when removing flag aura, handle flag drop
     Player* player = target->ToPlayer();
     if (!apply && player && (GetSpellInfo()->AuraInterruptFlags & AURA_INTERRUPT_FLAG_IMMUNE_OR_LOST_SELECTION))
     {
         if (player->InBattleground())
         {
             if (Battleground* bg = player->GetBattleground())
                 bg->EventPlayerDroppedFlag(player);
         }
         else
             sOutdoorPvPMgr->HandleDropFlag(player, GetSpellInfo()->Id);
     }
 }
References ByteConverter::apply(), Unit::ApplySpellImmune(), AURA_EFFECT_HANDLE_REAL, AURA_INTERRUPT_FLAG_IMMUNE_OR_LOST_SELECTION, bg(), Player::GetBattleground(), GetId(), GetMiscValue(), GetSpellInfo(), AuraApplication::GetTarget(), IMMUNITY_EFFECT, Player::InBattleground(), sOutdoorPvPMgr, and Object::ToPlayer().
HandleAuraModExpertise()
void AuraEffect::HandleAuraModExpertise (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4201 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     target->ToPlayer()->UpdateExpertise(BASE_ATTACK);
     target->ToPlayer()->UpdateExpertise(OFF_ATTACK);
 }
References AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, BASE_ATTACK, AuraApplication::GetTarget(), Object::GetTypeId(), OFF_ATTACK, Object::ToPlayer(), TYPEID_PLAYER, and Player::UpdateExpertise().
HandleAuraModFaction()
void AuraEffect::HandleAuraModFaction (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 5526 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     if (apply)
     {
         target->SetFaction(GetMiscValue());
         if (target->GetTypeId() == TYPEID_PLAYER)
             target->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PLAYER_CONTROLLED);
     }
     else
     {
         target->RestoreFaction();
         if (target->GetTypeId() == TYPEID_PLAYER)
             target->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PLAYER_CONTROLLED);
     }
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_REAL, GetMiscValue(), AuraApplication::GetTarget(), Object::GetTypeId(), Object::RemoveFlag(), Unit::RestoreFaction(), Unit::SetFaction(), Object::SetFlag(), TYPEID_PLAYER, UNIT_FIELD_FLAGS, and UNIT_FLAG_PLAYER_CONTROLLED.
HandleAuraModFakeInebriation()
void AuraEffect::HandleAuraModFakeInebriation (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 5653 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     if (apply)
     {
         target->m_invisibilityDetect.AddFlag(INVISIBILITY_DRUNK);
         target->m_invisibilityDetect.AddValue(INVISIBILITY_DRUNK, GetAmount());
         if (target->GetTypeId() == TYPEID_PLAYER)
         {
             int32 oldval = target->ToPlayer()->GetInt32Value(PLAYER_FAKE_INEBRIATION);
             target->ToPlayer()->SetInt32Value(PLAYER_FAKE_INEBRIATION, oldval + GetAmount());
         }
     }
     else
     {
         bool removeDetect = !target->HasAuraType(SPELL_AURA_MOD_FAKE_INEBRIATE);
         target->m_invisibilityDetect.AddValue(INVISIBILITY_DRUNK, -GetAmount());
         if (target->GetTypeId() == TYPEID_PLAYER)
         {
             int32 oldval = target->ToPlayer()->GetInt32Value(PLAYER_FAKE_INEBRIATION);
             target->ToPlayer()->SetInt32Value(PLAYER_FAKE_INEBRIATION, oldval - GetAmount());
             if (removeDetect)
                 removeDetect = !target->ToPlayer()->GetDrunkValue();
         }
         if (removeDetect)
             target->m_invisibilityDetect.DelFlag(INVISIBILITY_DRUNK);
     }
     // call functions which may have additional effects after chainging state of unit
     target->UpdateObjectVisibility(false);
 }
References FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::AddFlag(), FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::AddValue(), ByteConverter::apply(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::DelFlag(), GetAmount(), Player::GetDrunkValue(), Object::GetInt32Value(), AuraApplication::GetTarget(), Object::GetTypeId(), Unit::HasAuraType(), INVISIBILITY_DRUNK, WorldObject::m_invisibilityDetect, PLAYER_FAKE_INEBRIATION, Object::SetInt32Value(), SPELL_AURA_MOD_FAKE_INEBRIATE, Object::ToPlayer(), TYPEID_PLAYER, and Unit::UpdateObjectVisibility().
HandleAuraModIncreaseEnergy()
void AuraEffect::HandleAuraModIncreaseEnergy (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4300 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     Powers PowerType = Powers(GetMiscValue());
     // do not check power type, we can always modify the maximum
     // as the client will not see any difference
     // also, placing conditions that may change during the aura duration
     // inside effect handlers is not a good idea
     //if (int32(PowerType) != GetMiscValue())
     //    return;
     UnitMods unitMod = UnitMods(static_cast<uint16>(UNIT_MOD_POWER_START) + PowerType);
     target->HandleStatModifier(unitMod, TOTAL_VALUE, float(GetAmount()), apply);
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, GetAmount(), GetMiscValue(), AuraApplication::GetTarget(), Unit::HandleStatModifier(), TOTAL_VALUE, and UNIT_MOD_POWER_START.
HandleAuraModIncreaseEnergyPercent()
void AuraEffect::HandleAuraModIncreaseEnergyPercent (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4320 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     Powers PowerType = Powers(GetMiscValue());
     // do not check power type, we can always modify the maximum
     // as the client will not see any difference
     // also, placing conditions that may change during the aura duration
     // inside effect handlers is not a good idea
     //if (int32(PowerType) != GetMiscValue())
     //    return;
     UnitMods unitMod = UnitMods(static_cast<uint16>(UNIT_MOD_POWER_START) + PowerType);
     float amount = float(GetAmount());
     if (apply)
     {
         target->HandleStatModifier(unitMod, TOTAL_PCT, amount, apply);
         target->ModifyPowerPct(PowerType, amount, apply);
     }
     else
     {
         target->ModifyPowerPct(PowerType, amount, apply);
         target->HandleStatModifier(unitMod, TOTAL_PCT, amount, apply);
     }
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, GetAmount(), GetMiscValue(), AuraApplication::GetTarget(), Unit::HandleStatModifier(), Unit::ModifyPowerPct(), TOTAL_PCT, and UNIT_MOD_POWER_START.
HandleAuraModIncreaseFlightSpeed()
void AuraEffect::HandleAuraModIncreaseFlightSpeed (AuraApplication const * aurApp, uint8 mode, bool apply) const
Update ability to fly
Someone should clean up these hacks and remove it from this function. It doesn't even belong here.
Definition at line 3260 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_CHANGE_AMOUNT_SEND_FOR_CLIENT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     if (mode & AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK)
         target->UpdateSpeed(MOVE_FLIGHT, true);
     if (GetAuraType() == SPELL_AURA_MOD_INCREASE_MOUNTED_FLIGHT_SPEED)
     {
         // do not remove unit flag if there are more than this auraEffect of that kind on unit on unit
         if (mode & AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK && (apply || (!target->HasAuraType(SPELL_AURA_MOD_INCREASE_MOUNTED_FLIGHT_SPEED) && !target->HasAuraType(SPELL_AURA_FLY))))
         {
             target->SetCanFly(apply);
             if (!apply && target->GetTypeId() == TYPEID_UNIT && !target->IsLevitating())
                 target->GetMotionMaster()->MoveFall();
         }
         if (mode & AURA_EFFECT_HANDLE_REAL)
         {
             //Players on flying mounts must be immune to polymorph
             if (target->GetTypeId() == TYPEID_PLAYER)
                 target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_POLYMORPH, apply);
             // Dragonmaw Illusion (overwrite mount model, mounted aura already applied)
             if (apply && target->HasAuraEffect(42016, 0) && target->GetMountID())
                 target->SetUInt32Value(UNIT_FIELD_MOUNTDISPLAYID, 16314);
         }
     }
     if (Player* targetPlayer = target->ToPlayer())
     {
         sScriptMgr->AnticheatSetUnderACKmount(targetPlayer);
     }
 }
References ByteConverter::apply(), Unit::ApplySpellImmune(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_CHANGE_AMOUNT_SEND_FOR_CLIENT_MASK, AURA_EFFECT_HANDLE_REAL, AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK, GetAuraType(), GetId(), Unit::GetMotionMaster(), Unit::GetMountID(), AuraApplication::GetTarget(), Object::GetTypeId(), Unit::HasAuraEffect(), Unit::HasAuraType(), IMMUNITY_MECHANIC, Unit::IsLevitating(), MECHANIC_POLYMORPH, MOVE_FLIGHT, MotionMaster::MoveFall(), Unit::SetCanFly(), Object::SetUInt32Value(), SPELL_AURA_FLY, SPELL_AURA_MOD_INCREASE_MOUNTED_FLIGHT_SPEED, sScriptMgr, Object::ToPlayer(), TYPEID_PLAYER, TYPEID_UNIT, UNIT_FIELD_MOUNTDISPLAYID, and Unit::UpdateSpeed().
HandleAuraModIncreaseHealth()
void AuraEffect::HandleAuraModIncreaseHealth (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4255 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     if (apply)
     {
         target->HandleStatModifier(UNIT_MOD_HEALTH, TOTAL_VALUE, float(GetAmount()), apply);
         target->ModifyHealth(GetAmount());
     }
     else
     {
         if (int32(target->GetHealth()) > GetAmount())
             target->ModifyHealth(-GetAmount());
         else
             target->SetHealth(1);
         target->HandleStatModifier(UNIT_MOD_HEALTH, TOTAL_VALUE, float(GetAmount()), apply);
     }
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, GetAmount(), Unit::GetHealth(), AuraApplication::GetTarget(), Unit::HandleStatModifier(), Unit::ModifyHealth(), Unit::SetHealth(), TOTAL_VALUE, and UNIT_MOD_HEALTH.
HandleAuraModIncreaseHealthPercent()
void AuraEffect::HandleAuraModIncreaseHealthPercent (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4350 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     // Unit will keep hp% after MaxHealth being modified if unit is alive.
     float percent = target->GetHealthPct();
     target->HandleStatModifier(UNIT_MOD_HEALTH, TOTAL_PCT, float(GetAmount()), apply);
     // Xinef: pct was rounded down and could "kill" creature by setting its health to 0 making npc zombie
     if (target->IsAlive())
         if (uint32 healthAmount = CalculatePct(target->GetMaxHealth(), percent))
             target->SetHealth(healthAmount);
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, CalculatePct(), GetAmount(), Unit::GetHealthPct(), Unit::GetMaxHealth(), AuraApplication::GetTarget(), Unit::HandleStatModifier(), Unit::IsAlive(), Unit::SetHealth(), TOTAL_PCT, and UNIT_MOD_HEALTH.
HandleAuraModIncreaseMaxHealth()
void AuraEffect::HandleAuraModIncreaseMaxHealth (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4277 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     uint32 oldhealth = target->GetHealth();
     double healthPercentage = (double)oldhealth / (double)target->GetMaxHealth();
     target->HandleStatModifier(UNIT_MOD_HEALTH, TOTAL_VALUE, float(GetAmount()), apply);
     // refresh percentage
     if (oldhealth > 0)
     {
         uint32 newhealth = uint32(ceil((double)target->GetMaxHealth() * healthPercentage));
         if (newhealth == 0)
             newhealth = 1;
         target->SetHealth(newhealth);
     }
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, G3D::ceil(), GetAmount(), Unit::GetHealth(), Unit::GetMaxHealth(), AuraApplication::GetTarget(), Unit::HandleStatModifier(), Unit::SetHealth(), TOTAL_VALUE, and UNIT_MOD_HEALTH.
HandleAuraModIncreaseMountedSpeed()
void AuraEffect::HandleAuraModIncreaseMountedSpeed (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 3255 of file SpellAuraEffects.cpp.
 {
     HandleAuraModIncreaseSpeed(aurApp, mode, apply);
 }
References ByteConverter::apply(), and HandleAuraModIncreaseSpeed().
HandleAuraModIncreaseSpeed()
void AuraEffect::HandleAuraModIncreaseSpeed (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 3240 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     target->UpdateSpeed(MOVE_RUN, true);
     if (Player* targetPlayer = target->ToPlayer())
     {
         sScriptMgr->AnticheatSetUnderACKmount(targetPlayer);
     }
 }
References AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AuraApplication::GetTarget(), MOVE_RUN, sScriptMgr, Object::ToPlayer(), and Unit::UpdateSpeed().
Referenced by HandleAuraModIncreaseMountedSpeed().
HandleAuraModIncreaseSwimSpeed()
void AuraEffect::HandleAuraModIncreaseSwimSpeed (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 3300 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     target->UpdateSpeed(MOVE_SWIM, true);
     if (Player* targetPlayer = target->ToPlayer())
     {
         sScriptMgr->AnticheatSetUnderACKmount(targetPlayer);
     }
 }
References AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AuraApplication::GetTarget(), MOVE_SWIM, sScriptMgr, Object::ToPlayer(), and Unit::UpdateSpeed().
HandleAuraModPacify()
void AuraEffect::HandleAuraModPacify (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 2612 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     if (apply)
     {
         target->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PACIFIED);
         //target->AttackStop(); // pussywizard: wtf? why having this flag prevents from being in combat? it should just prevent melee attack
     }
     else
     {
         // do not remove unit flag if there are more than this auraEffect of that kind on unit on unit
         if (target->HasAuraType(SPELL_AURA_MOD_PACIFY) || target->HasAuraType(SPELL_AURA_MOD_PACIFY_SILENCE))
             return;
         target->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PACIFIED);
     }
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK, AuraApplication::GetTarget(), Unit::HasAuraType(), Object::RemoveFlag(), Object::SetFlag(), SPELL_AURA_MOD_PACIFY, SPELL_AURA_MOD_PACIFY_SILENCE, UNIT_FIELD_FLAGS, and UNIT_FLAG_PACIFIED.
Referenced by HandleAuraModPacifyAndSilence().
HandleAuraModPacifyAndSilence()
void AuraEffect::HandleAuraModPacifyAndSilence (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 2633 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     if (!(apply))
     {
         // do not remove unit flag if there are more than this auraEffect of that kind on unit on unit
         if (target->HasAuraType(SPELL_AURA_MOD_PACIFY_SILENCE))
             return;
     }
     HandleAuraModPacify(aurApp, mode, apply);
     HandleAuraModSilence(aurApp, mode, apply);
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK, AuraApplication::GetTarget(), HandleAuraModPacify(), HandleAuraModSilence(), Unit::HasAuraType(), and SPELL_AURA_MOD_PACIFY_SILENCE.
HandleAuraModParryPercent()
void AuraEffect::HandleAuraModParryPercent (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4381 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     if (!target->ToPlayer()->CanParry())
         target->ToPlayer()->SetCanParry(true);
     else
         target->ToPlayer()->UpdateParryPercentage();
 }
References AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, Player::CanParry(), AuraApplication::GetTarget(), Object::GetTypeId(), Player::SetCanParry(), Object::ToPlayer(), TYPEID_PLAYER, and Player::UpdateParryPercentage().
HandleAuraModPetTalentsPoints()
void AuraEffect::HandleAuraModPetTalentsPoints (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 2769 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     // Recalculate pet talent points
     if (Pet* pet = target->ToPlayer()->GetPet())
         pet->InitTalentForLevel();
 }
References AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, Player::GetPet(), AuraApplication::GetTarget(), Object::GetTypeId(), Object::ToPlayer(), and TYPEID_PLAYER.
HandleAuraModRangedAttackPower()
void AuraEffect::HandleAuraModRangedAttackPower (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4679 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     if ((target->getClassMask() & CLASSMASK_WAND_USERS) != 0)
         return;
     target->HandleStatModifier(UNIT_MOD_ATTACK_POWER_RANGED, TOTAL_VALUE, float(GetAmount()), apply);
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, CLASSMASK_WAND_USERS, GetAmount(), Unit::getClassMask(), AuraApplication::GetTarget(), Unit::HandleStatModifier(), TOTAL_VALUE, and UNIT_MOD_ATTACK_POWER_RANGED.
HandleAuraModRangedAttackPowerOfStatPercent()
void AuraEffect::HandleAuraModRangedAttackPowerOfStatPercent (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4717 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     // Recalculate bonus
     if (target->GetTypeId() == TYPEID_PLAYER && !(target->getClassMask() & CLASSMASK_WAND_USERS))
         target->ToPlayer()->UpdateAttackPowerAndDamage(true);
 }
References AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, CLASSMASK_WAND_USERS, Unit::getClassMask(), AuraApplication::GetTarget(), Object::GetTypeId(), Object::ToPlayer(), TYPEID_PLAYER, and Player::UpdateAttackPowerAndDamage().
HandleAuraModRangedAttackPowerPercent()
void AuraEffect::HandleAuraModRangedAttackPowerPercent (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4703 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     if ((target->getClassMask() & CLASSMASK_WAND_USERS) != 0)
         return;
     //UNIT_FIELD_RANGED_ATTACK_POWER_MULTIPLIER = multiplier - 1
     target->HandleStatModifier(UNIT_MOD_ATTACK_POWER_RANGED, TOTAL_PCT, float(GetAmount()), apply);
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, CLASSMASK_WAND_USERS, GetAmount(), Unit::getClassMask(), AuraApplication::GetTarget(), Unit::HandleStatModifier(), TOTAL_PCT, and UNIT_MOD_ATTACK_POWER_RANGED.
HandleAuraModRangedHaste()
void AuraEffect::HandleAuraModRangedHaste (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4607 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     target->ApplyAttackTimePercentMod(RANGED_ATTACK, (float)GetAmount(), apply);
 }
References ByteConverter::apply(), Unit::ApplyAttackTimePercentMod(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, GetAmount(), AuraApplication::GetTarget(), and RANGED_ATTACK.
HandleAuraModRegenInterrupt()
void AuraEffect::HandleAuraModRegenInterrupt (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4423 of file SpellAuraEffects.cpp.
 {
     HandleModManaRegen(aurApp, mode, apply);
 }
References ByteConverter::apply(), and HandleModManaRegen().
HandleAuraModResistance()
void AuraEffect::HandleAuraModResistance (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 3890 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     for (int8 x = SPELL_SCHOOL_NORMAL; x < MAX_SPELL_SCHOOL; x++)
     {
         if (GetMiscValue() & int32(1 << x))
         {
             target->HandleStatModifier(UnitMods(UNIT_MOD_RESISTANCE_START + x), TOTAL_VALUE, float(GetAmount()), apply);
             if (target->GetTypeId() == TYPEID_PLAYER || target->IsPet())
                 target->ApplyResistanceBuffModsMod(SpellSchools(x), GetAmount() > 0, (float)GetAmount(), apply);
         }
     }
 }
References ByteConverter::apply(), Unit::ApplyResistanceBuffModsMod(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, GetAmount(), GetMiscValue(), AuraApplication::GetTarget(), Object::GetTypeId(), Unit::HandleStatModifier(), Unit::IsPet(), MAX_SPELL_SCHOOL, SPELL_SCHOOL_NORMAL, TOTAL_VALUE, TYPEID_PLAYER, UNIT_MOD_RESISTANCE_START, and G3D::x.
HandleAuraModResistanceExclusive()
void AuraEffect::HandleAuraModResistanceExclusive (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 3867 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     for (int8 x = SPELL_SCHOOL_NORMAL; x < MAX_SPELL_SCHOOL; x++)
     {
         if (GetMiscValue() & int32(1 << x))
         {
             int32 amount = target->GetMaxPositiveAuraModifierByMiscMask(SPELL_AURA_MOD_RESISTANCE_EXCLUSIVE, 1 << x, this);
             if (amount < GetAmount())
             {
                 float value = float(GetAmount() - amount);
                 target->HandleStatModifier(UnitMods(UNIT_MOD_RESISTANCE_START + x), BASE_VALUE, value, apply);
                 if (target->GetTypeId() == TYPEID_PLAYER)
                     target->ApplyResistanceBuffModsMod(SpellSchools(x), aurApp->IsPositive(), value, apply);
             }
         }
     }
 }
References ByteConverter::apply(), Unit::ApplyResistanceBuffModsMod(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, BASE_VALUE, GetAmount(), Unit::GetMaxPositiveAuraModifierByMiscMask(), GetMiscValue(), AuraApplication::GetTarget(), Object::GetTypeId(), Unit::HandleStatModifier(), AuraApplication::IsPositive(), MAX_SPELL_SCHOOL, SPELL_AURA_MOD_RESISTANCE_EXCLUSIVE, SPELL_SCHOOL_NORMAL, TYPEID_PLAYER, UNIT_MOD_RESISTANCE_START, and G3D::x.
HandleAuraModResistenceOfStatPercent()
void AuraEffect::HandleAuraModResistenceOfStatPercent (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4179 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     if (GetMiscValue() != SPELL_SCHOOL_MASK_NORMAL)
     {
         // support required adding replace UpdateArmor by loop by UpdateResistence at intellect update
         // and include in UpdateResistence same code as in UpdateArmor for aura mod apply.
         LOG_ERROR("spells.aura.effect", "Aura SPELL_AURA_MOD_RESISTANCE_OF_STAT_PERCENT(182) does not work for non-armor type resistances!");
         return;
     }
     // Recalculate Armor
     target->UpdateArmor();
 }
References AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, GetMiscValue(), AuraApplication::GetTarget(), Object::GetTypeId(), LOG_ERROR, SPELL_SCHOOL_MASK_NORMAL, TYPEID_PLAYER, and Unit::UpdateArmor().
HandleAuraModRoot()
void AuraEffect::HandleAuraModRoot (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 3061 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     target->SetControlled(apply, UNIT_STATE_ROOT);
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_REAL, AuraApplication::GetTarget(), Unit::SetControlled(), and UNIT_STATE_ROOT.
HandleAuraModScale()
void AuraEffect::HandleAuraModScale (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 2334 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_CHANGE_AMOUNT_SEND_FOR_CLIENT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     float scale = target->GetObjectScale();
     ApplyPercentModFloatVar(scale, float(GetAmount()), apply);
     target->SetObjectScale(scale);
 }
References ByteConverter::apply(), ApplyPercentModFloatVar(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_SEND_FOR_CLIENT_MASK, GetAmount(), Object::GetObjectScale(), AuraApplication::GetTarget(), and Object::SetObjectScale().
HandleAuraModSchoolImmunity()
void AuraEffect::HandleAuraModSchoolImmunity (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 3780 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     target->ApplySpellImmune(GetId(), IMMUNITY_SCHOOL, GetMiscValue(), (apply));
     if (GetSpellInfo()->Mechanic == MECHANIC_BANISH)
     {
         if (apply)
             target->AddUnitState(UNIT_STATE_ISOLATED);
         else
         {
             bool banishFound = false;
             Unit::AuraEffectList const& banishAuras = target->GetAuraEffectsByType(GetAuraType());
             for (Unit::AuraEffectList::const_iterator i = banishAuras.begin(); i != banishAuras.end(); ++i)
                 if ((*i)->GetSpellInfo()->Mechanic == MECHANIC_BANISH)
                 {
                     banishFound = true;
                     break;
                 }
             if (!banishFound)
                 target->ClearUnitState(UNIT_STATE_ISOLATED);
         }
     }
     if (apply && GetMiscValue() == SPELL_SCHOOL_MASK_NORMAL)
         target->RemoveAurasWithInterruptFlags(AURA_INTERRUPT_FLAG_IMMUNE_OR_LOST_SELECTION);
     // remove all flag auras (they are positive, but they must be removed when you are immune)
     if (GetSpellInfo()->HasAttribute(SPELL_ATTR1_IMMUNITY_PURGES_EFFECT)
             && GetSpellInfo()->HasAttribute(SPELL_ATTR2_FAIL_ON_ALL_TARGETS_IMMUNE))
         target->RemoveAurasWithInterruptFlags(AURA_INTERRUPT_FLAG_IMMUNE_OR_LOST_SELECTION);
     // TODO: optimalize this cycle - use RemoveAurasWithInterruptFlags call or something else
     if ((apply)
             && GetSpellInfo()->HasAttribute(SPELL_ATTR1_IMMUNITY_PURGES_EFFECT)
             && GetSpellInfo()->IsPositive())                       //Only positive immunity removes auras
     {
         uint32 school_mask = GetMiscValue();
         Unit::AuraApplicationMap& Auras = target->GetAppliedAuras();
         for (Unit::AuraApplicationMap::iterator iter = Auras.begin(); iter != Auras.end();)
         {
             SpellInfo const* spell = iter->second->GetBase()->GetSpellInfo();
             if ((spell->GetSchoolMask() & school_mask)//Check for school mask
                     && GetSpellInfo()->CanDispelAura(spell)
                     && !iter->second->IsPositive()          //Don't remove positive spells
                     && spell->Id != GetId())               //Don't remove self
             {
                 target->RemoveAura(iter);
             }
             else
                 ++iter;
         }
     }
 }
References Unit::AddUnitState(), ByteConverter::apply(), Unit::ApplySpellImmune(), AURA_EFFECT_HANDLE_REAL, AURA_INTERRUPT_FLAG_IMMUNE_OR_LOST_SELECTION, Unit::ClearUnitState(), Unit::GetAppliedAuras(), Unit::GetAuraEffectsByType(), GetAuraType(), GetId(), GetMiscValue(), SpellInfo::GetSchoolMask(), GetSpellInfo(), AuraApplication::GetTarget(), SpellInfo::Id, IMMUNITY_SCHOOL, SpellInfo::IsPositive(), MECHANIC_BANISH, Unit::RemoveAura(), Unit::RemoveAurasWithInterruptFlags(), SPELL_ATTR1_IMMUNITY_PURGES_EFFECT, SPELL_ATTR2_FAIL_ON_ALL_TARGETS_IMMUNE, SPELL_SCHOOL_MASK_NORMAL, and UNIT_STATE_ISOLATED.
HandleAuraModShapeshift()
void AuraEffect::HandleAuraModShapeshift (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 1828 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL_OR_REAPPLY_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     uint32 modelid = 0;
     Powers PowerType = POWER_MANA;
     ShapeshiftForm form = ShapeshiftForm(GetMiscValue());
     switch (form)
     {
         case FORM_CAT:                                      // 0x01
         case FORM_GHOUL:                                    // 0x07
             PowerType = POWER_ENERGY;
             break;
         case FORM_BEAR:                                     // 0x05
         case FORM_DIREBEAR:                                 // 0x08
         case FORM_BATTLESTANCE:                             // 0x11
         case FORM_DEFENSIVESTANCE:                          // 0x12
         case FORM_BERSERKERSTANCE:                          // 0x13
             PowerType = POWER_RAGE;
             break;
         case FORM_TREE:                                     // 0x02
         case FORM_TRAVEL:                                   // 0x03
         case FORM_AQUA:                                     // 0x04
         case FORM_AMBIENT:                                  // 0x06
         case FORM_STEVES_GHOUL:                             // 0x09
         case FORM_THARONJA_SKELETON:                        // 0x0A
         case FORM_TEST_OF_STRENGTH:                         // 0x0B
         case FORM_BLB_PLAYER:                               // 0x0C
         case FORM_SHADOW_DANCE:                             // 0x0D
         case FORM_CREATUREBEAR:                             // 0x0E
         case FORM_CREATURECAT:                              // 0x0F
         case FORM_GHOSTWOLF:                                // 0x10
         case FORM_TEST:                                     // 0x14
         case FORM_ZOMBIE:                                   // 0x15
         case FORM_METAMORPHOSIS:                            // 0x16
         case FORM_UNDEAD:                                   // 0x19
         case FORM_MASTER_ANGLER:                            // 0x1A
         case FORM_FLIGHT_EPIC:                              // 0x1B
         case FORM_SHADOW:                                   // 0x1C
         case FORM_FLIGHT:                                   // 0x1D
         case FORM_STEALTH:                                  // 0x1E
         case FORM_MOONKIN:                                  // 0x1F
         case FORM_SPIRITOFREDEMPTION:                       // 0x20
             break;
         default:
             LOG_ERROR("spells.aura.effect", "Auras: Unknown Shapeshift Type: %u", GetMiscValue());
     }
     modelid = target->GetModelForForm(form);
     if (apply)
     {
         // remove polymorph before changing display id to keep new display id
         switch (form)
         {
             case FORM_CAT:
             case FORM_TREE:
             case FORM_TRAVEL:
             case FORM_AQUA:
             case FORM_BEAR:
             case FORM_DIREBEAR:
             case FORM_FLIGHT_EPIC:
             case FORM_FLIGHT:
             case FORM_MOONKIN:
                 {
                     // remove movement affects
                     target->RemoveAurasByShapeShift();
                     // and polymorphic affects
                     if (target->IsPolymorphed())
                         target->RemoveAurasDueToSpell(target->getTransForm());
                     break;
                 }
             default:
                 break;
         }
         // remove other shapeshift before applying a new one
         // xinef: rogue shouldnt be wrapped by this check (shadow dance vs stealth)
         if (GetSpellInfo()->SpellFamilyName != SPELLFAMILY_ROGUE)
             target->RemoveAurasByType(SPELL_AURA_MOD_SHAPESHIFT, ObjectGuid::Empty, GetBase());
         // stop handling the effect if it was removed by linked event
         if (aurApp->GetRemoveMode())
             return;
         if (PowerType != POWER_MANA)
         {
             uint32 oldPower = target->GetPower(PowerType);
             // reset power to default values only at power change
             if (target->getPowerType() != PowerType)
                 target->setPowerType(PowerType);
             switch (form)
             {
                 case FORM_CAT:
                 case FORM_BEAR:
                 case FORM_DIREBEAR:
                     {
                         // get furor proc chance
                         uint32 FurorChance = 0;
                         if (AuraEffect const* dummy = target->GetDummyAuraEffect(SPELLFAMILY_DRUID, 238, 0))
                             FurorChance = std::max(dummy->GetAmount(), 0);
                         switch (GetMiscValue())
{
                             case FORM_CAT:
{
                                     int32 basePoints = int32(std::min(oldPower, FurorChance));
                                     target->SetPower(POWER_ENERGY, 0);
                                     target->CastCustomSpell(target, 17099, &basePoints, nullptr, nullptr, true, nullptr, this);
                                     break;
                                 }
                             case FORM_BEAR:
                             case FORM_DIREBEAR:
                                 if (urand(0, 99) < FurorChance)
                                     target->CastSpell(target, 17057, true);
                                 break;
                             default:
{
                                     uint32 newEnergy = std::min(target->GetPower(POWER_ENERGY), FurorChance);
                                     target->SetPower(POWER_ENERGY, newEnergy);
                                     break;
                                 }
                         }
                         break;
                     }
                 default:
                     break;
             }
         }
         // stop handling the effect if it was removed by linked event
         if (aurApp->GetRemoveMode())
             return;
         target->SetShapeshiftForm(form);
         // xinef: allow shapeshift to override model id if forced transform aura is not present!
         if (modelid > 0)
         {
             bool allow = true;
             if (target->getTransForm())
                 if (SpellInfo const* transformSpellInfo = sSpellMgr->GetSpellInfo(target->getTransForm()))
                     if (transformSpellInfo->HasAttribute(SPELL_ATTR0_NO_IMMUNITIES) || !transformSpellInfo->IsPositive())
                         allow = false;
             if (allow)
                 target->SetDisplayId(modelid);
         }
     }
     else
     {
         // reset model id if no other auras present
         // may happen when aura is applied on linked event on aura removal
         if (!target->HasAuraType(SPELL_AURA_MOD_SHAPESHIFT))
         {
             target->SetShapeshiftForm(FORM_NONE);
             if (target->getClass() == CLASS_DRUID)
             {
                 target->setPowerType(POWER_MANA);
                 // Remove movement impairing effects also when shifting out
                 target->RemoveAurasByShapeShift();
             }
         }
         if (modelid > 0)
             target->RestoreDisplayId();
         switch (form)
         {
             // Nordrassil Harness - bonus
             case FORM_BEAR:
             case FORM_DIREBEAR:
             case FORM_CAT:
                 if (AuraEffect* dummy = target->GetAuraEffect(37315, 0))
                     target->CastSpell(target, 37316, true, nullptr, dummy);
                 break;
             // Nordrassil Regalia - bonus
             case FORM_MOONKIN:
                 if (AuraEffect* dummy = target->GetAuraEffect(37324, 0))
                     target->CastSpell(target, 37325, true, nullptr, dummy);
                 break;
             case FORM_BATTLESTANCE:
             case FORM_DEFENSIVESTANCE:
             case FORM_BERSERKERSTANCE:
                 {
                     uint32 Rage_val = 0;
                     // Defensive Tactics
                     if (form == FORM_DEFENSIVESTANCE)
                     {
                         if (AuraEffect const* aurEff = target->IsScriptOverriden(m_spellInfo, 831))
                             Rage_val += aurEff->GetAmount() * 10;
                     }
                     // Stance mastery + Tactical mastery (both passive, and last have aura only in defense stance, but need apply at any stance switch)
                     if (target->GetTypeId() == TYPEID_PLAYER)
                     {
                         // Stance mastery - trainer spell
                         PlayerSpellMap const& sp_list = target->ToPlayer()->GetSpellMap();
                         for (PlayerSpellMap::const_iterator itr = sp_list.begin(); itr != sp_list.end(); ++itr)
{
                             if (itr->second->State == PLAYERSPELL_REMOVED || !itr->second->IsInSpec(target->ToPlayer()->GetActiveSpec()))
                                 continue;
                             SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(itr->first);
                             if (spellInfo && spellInfo->SpellFamilyName == SPELLFAMILY_WARRIOR && spellInfo->SpellIconID == 139)
                                 Rage_val += target->CalculateSpellDamage(target, spellInfo, 0) * 10;
                         }
                         // Tactical Mastery - talent
                         PlayerTalentMap const& tp_list = target->ToPlayer()->GetTalentMap();
                         for (PlayerTalentMap::const_iterator itr = tp_list.begin(); itr != tp_list.end(); ++itr)
{
                             if (itr->second->State == PLAYERSPELL_REMOVED || !itr->second->IsInSpec(target->ToPlayer()->GetActiveSpec()))
                                 continue;
                             SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(itr->first);
                             if (spellInfo && spellInfo->SpellFamilyName == SPELLFAMILY_WARRIOR && spellInfo->SpellIconID == 139)
                                 Rage_val += target->CalculateSpellDamage(target, spellInfo, 0) * 10;
                         }
                     }
                     if (target->GetPower(POWER_RAGE) > Rage_val)
                         target->SetPower(POWER_RAGE, Rage_val);
                     break;
                 }
             default:
                 break;
         }
     }
     // adding/removing linked auras
     // add/remove the shapeshift aura's boosts
     HandleShapeshiftBoosts(target, apply);
     if (target->GetTypeId() == TYPEID_PLAYER)
         target->ToPlayer()->InitDataForForm();
     if (target->getClass() == CLASS_DRUID)
     {
         // Dash
         if (AuraEffect* aurEff = target->GetAuraEffect(SPELL_AURA_MOD_INCREASE_SPEED, SPELLFAMILY_DRUID, 0, 0, 0x8))
             aurEff->RecalculateAmount();
         // Disarm handling
         // If druid shifts while being disarmed we need to deal with that since forms aren't affected by disarm
         // and also HandleAuraModDisarm is not triggered
         if (!target->CanUseAttackType(BASE_ATTACK))
         {
             if (Item* pItem = target->ToPlayer()->GetItemByPos(INVENTORY_SLOT_BAG_0, EQUIPMENT_SLOT_MAINHAND))
             {
                 target->ToPlayer()->_ApplyWeaponDamage(EQUIPMENT_SLOT_MAINHAND, pItem->GetTemplate(), nullptr, apply);
             }
         }
     }
     // stop handling the effect if it was removed by linked event
     if (apply && aurApp->GetRemoveMode())
         return;
     if (target->GetTypeId() == TYPEID_PLAYER)
     {
         SpellShapeshiftEntry const* shapeInfo = sSpellShapeshiftStore.LookupEntry(form);
         // Learn spells for shapeshift form - no need to send action bars or add spells to spellbook
         for (uint8 i = 0; i < MAX_SHAPESHIFT_SPELLS; ++i)
         {
             if (!shapeInfo->stanceSpell[i])
                 continue;
             if (apply)
                 target->ToPlayer()->_addSpell(shapeInfo->stanceSpell[i], SPEC_MASK_ALL, true);
             else
                 target->ToPlayer()->removeSpell(shapeInfo->stanceSpell[i], SPEC_MASK_ALL, true);
         }
     }
 }
References Player::_addSpell(), Player::_ApplyWeaponDamage(), ByteConverter::apply(), AURA_EFFECT_HANDLE_REAL_OR_REAPPLY_MASK, BASE_ATTACK, Unit::CalculateSpellDamage(), Unit::CanUseAttackType(), Unit::CastCustomSpell(), Unit::CastSpell(), CLASS_DRUID, ObjectGuid::Empty, EQUIPMENT_SLOT_MAINHAND, FORM_AMBIENT, FORM_AQUA, FORM_BATTLESTANCE, FORM_BEAR, FORM_BERSERKERSTANCE, FORM_BLB_PLAYER, FORM_CAT, FORM_CREATUREBEAR, FORM_CREATURECAT, FORM_DEFENSIVESTANCE, FORM_DIREBEAR, FORM_FLIGHT, FORM_FLIGHT_EPIC, FORM_GHOSTWOLF, FORM_GHOUL, FORM_MASTER_ANGLER, FORM_METAMORPHOSIS, FORM_MOONKIN, FORM_NONE, FORM_SHADOW, FORM_SHADOW_DANCE, FORM_SPIRITOFREDEMPTION, FORM_STEALTH, FORM_STEVES_GHOUL, FORM_TEST, FORM_TEST_OF_STRENGTH, FORM_THARONJA_SKELETON, FORM_TRAVEL, FORM_TREE, FORM_UNDEAD, FORM_ZOMBIE, Player::GetActiveSpec(), Unit::GetAuraEffect(), GetBase(), Unit::getClass(), Unit::GetDummyAuraEffect(), Player::GetItemByPos(), GetMiscValue(), Unit::GetModelForForm(), Unit::GetPower(), Unit::getPowerType(), AuraApplication::GetRemoveMode(), GetSpellInfo(), Player::GetSpellMap(), Player::GetTalentMap(), AuraApplication::GetTarget(), Unit::getTransForm(), Object::GetTypeId(), HandleShapeshiftBoosts(), Unit::HasAuraType(), Player::InitDataForForm(), INVENTORY_SLOT_BAG_0, Unit::IsPolymorphed(), Unit::IsScriptOverriden(), LOG_ERROR, m_spellInfo, max, MAX_SHAPESHIFT_SPELLS, min, PLAYERSPELL_REMOVED, POWER_ENERGY, POWER_MANA, POWER_RAGE, Unit::RemoveAurasByShapeShift(), Unit::RemoveAurasByType(), Unit::RemoveAurasDueToSpell(), Player::removeSpell(), Unit::RestoreDisplayId(), Unit::SetDisplayId(), Unit::SetPower(), Unit::setPowerType(), Unit::SetShapeshiftForm(), SPEC_MASK_ALL, SPELL_ATTR0_NO_IMMUNITIES, SPELL_AURA_MOD_INCREASE_SPEED, SPELL_AURA_MOD_SHAPESHIFT, SPELLFAMILY_DRUID, SPELLFAMILY_ROGUE, SPELLFAMILY_WARRIOR, SpellInfo::SpellFamilyName, SpellInfo::SpellIconID, sSpellMgr, sSpellShapeshiftStore, SpellShapeshiftEntry::stanceSpell, Object::ToPlayer(), TYPEID_PLAYER, and urand().
HandleAuraModSilence()
void AuraEffect::HandleAuraModSilence (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 2583 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     if (apply)
     {
         target->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_SILENCED);
         // call functions which may have additional effects after chainging state of unit
         // Stop cast only spells vs PreventionType == SPELL_PREVENTION_TYPE_SILENCE
         for (uint32 i = CURRENT_MELEE_SPELL; i < CURRENT_MAX_SPELL; ++i)
             if (Spell* spell = target->GetCurrentSpell(CurrentSpellTypes(i)))
                 if (spell->m_spellInfo->PreventionType == SPELL_PREVENTION_TYPE_SILENCE)
                     // Stop spells on prepare or casting state
                     target->InterruptSpell(CurrentSpellTypes(i), false);
     }
     else
     {
         // do not remove unit flag if there are more than this auraEffect of that kind on unit on unit
         if (target->HasAuraType(SPELL_AURA_MOD_SILENCE) || target->HasAuraType(SPELL_AURA_MOD_PACIFY_SILENCE))
             return;
         target->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_SILENCED);
     }
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_REAL, CURRENT_MAX_SPELL, CURRENT_MELEE_SPELL, Unit::GetCurrentSpell(), AuraApplication::GetTarget(), Unit::HasAuraType(), Unit::InterruptSpell(), Object::RemoveFlag(), Object::SetFlag(), SPELL_AURA_MOD_PACIFY_SILENCE, SPELL_AURA_MOD_SILENCE, SPELL_PREVENTION_TYPE_SILENCE, UNIT_FIELD_FLAGS, and UNIT_FLAG_SILENCED.
Referenced by HandleAuraModPacifyAndSilence().
HandleAuraModSkill()
void AuraEffect::HandleAuraModSkill (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 2784 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_SKILL)))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     uint32 prot = GetMiscValue();
     int32 points = GetAmount();
     target->ToPlayer()->ModifySkillBonus(prot, ((apply) ? points : -points), GetAuraType() == SPELL_AURA_MOD_SKILL_TALENT);
     if (prot == SKILL_DEFENSE)
         target->ToPlayer()->UpdateDefenseBonusesMod();
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_SKILL, GetAmount(), GetAuraType(), GetMiscValue(), AuraApplication::GetTarget(), Object::GetTypeId(), Player::ModifySkillBonus(), SKILL_DEFENSE, SPELL_AURA_MOD_SKILL_TALENT, Object::ToPlayer(), TYPEID_PLAYER, and Player::UpdateDefenseBonusesMod().
HandleAuraModStalked()
void AuraEffect::HandleAuraModStalked (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 2726 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     // used by spells: Hunter's Mark, Mind Vision, Syndicate Tracker (MURP) DND
     if (apply)
         target->SetFlag(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_TRACK_UNIT);
     else
     {
         // do not remove unit flag if there are more than this auraEffect of that kind on unit on unit
         if (!target->HasAuraType(GetAuraType()))
             target->RemoveFlag(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_TRACK_UNIT);
     }
     // call functions which may have additional effects after chainging state of unit
     target->UpdateObjectVisibility(target->GetTypeId() == TYPEID_PLAYER);
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK, GetAuraType(), AuraApplication::GetTarget(), Object::GetTypeId(), Unit::HasAuraType(), Object::RemoveFlag(), Object::SetFlag(), TYPEID_PLAYER, UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_TRACK_UNIT, and Unit::UpdateObjectVisibility().
HandleAuraModStat()
void AuraEffect::HandleAuraModStat (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 3997 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     if (GetMiscValue() < -2 || GetMiscValue() > 4)
     {
         LOG_ERROR("spells.aura.effect", "WARNING: Spell %u effect %u has an unsupported misc value (%i) for SPELL_AURA_MOD_STAT ", GetId(), GetEffIndex(), GetMiscValue());
         return;
     }
     for (int32 i = STAT_STRENGTH; i < MAX_STATS; i++)
     {
         // -1 or -2 is all stats (misc < -2 checked in function beginning)
         if (GetMiscValue() < 0 || GetMiscValue() == i)
         {
             //target->ApplyStatMod(Stats(i), m_amount, apply);
             target->HandleStatModifier(UnitMods(UNIT_MOD_STAT_START + i), TOTAL_VALUE, float(GetAmount()), apply);
             if (target->GetTypeId() == TYPEID_PLAYER || target->IsPet())
                 target->ApplyStatBuffMod(Stats(i), (float)GetAmount(), apply);
         }
     }
 }
References ByteConverter::apply(), Unit::ApplyStatBuffMod(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, GetAmount(), GetEffIndex(), GetId(), GetMiscValue(), AuraApplication::GetTarget(), Object::GetTypeId(), Unit::HandleStatModifier(), Unit::IsPet(), LOG_ERROR, MAX_STATS, STAT_STRENGTH, TOTAL_VALUE, TYPEID_PLAYER, and UNIT_MOD_STAT_START.
HandleAuraModStateImmunity()
void AuraEffect::HandleAuraModStateImmunity (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 3767 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     target->ApplySpellImmune(GetId(), IMMUNITY_STATE, GetMiscValue(), apply);
     if (apply && GetSpellInfo()->HasAttribute(SPELL_ATTR1_IMMUNITY_PURGES_EFFECT))
         target->RemoveAurasByType(AuraType(GetMiscValue()), ObjectGuid::Empty, GetBase());
 }
References ByteConverter::apply(), Unit::ApplySpellImmune(), AURA_EFFECT_HANDLE_REAL, ObjectGuid::Empty, GetBase(), GetId(), GetMiscValue(), GetSpellInfo(), AuraApplication::GetTarget(), IMMUNITY_STATE, Unit::RemoveAurasByType(), and SPELL_ATTR1_IMMUNITY_PURGES_EFFECT.
HandleAuraModStun()
void AuraEffect::HandleAuraModStun (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 3051 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     target->SetControlled(apply, UNIT_STATE_STUNNED);
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_REAL, AuraApplication::GetTarget(), Unit::SetControlled(), and UNIT_STATE_STUNNED.
HandleAuraModTotalThreat()
void AuraEffect::HandleAuraModTotalThreat (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 2989 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     if (!target->IsAlive() || target->GetTypeId() != TYPEID_PLAYER)
         return;
     Unit* caster = GetCaster();
     if (caster && caster->IsAlive())
         target->getHostileRefMgr().addTempThreat((float)GetAmount(), apply);
 }
References HostileRefMgr::addTempThreat(), ByteConverter::apply(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, GetAmount(), GetCaster(), Unit::getHostileRefMgr(), AuraApplication::GetTarget(), Object::GetTypeId(), Unit::IsAlive(), and TYPEID_PLAYER.
HandleAuraModUseNormalSpeed()
void AuraEffect::HandleAuraModUseNormalSpeed (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 3336 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     target->UpdateSpeed(MOVE_RUN,  true);
     target->UpdateSpeed(MOVE_SWIM, true);
     target->UpdateSpeed(MOVE_FLIGHT,  true);
     if (Player* targetPlayer = target->ToPlayer())
     {
         sScriptMgr->AnticheatSetUnderACKmount(targetPlayer);
     }
 }
References AURA_EFFECT_HANDLE_REAL, AuraApplication::GetTarget(), MOVE_FLIGHT, MOVE_RUN, MOVE_SWIM, sScriptMgr, Object::ToPlayer(), and Unit::UpdateSpeed().
HandleAuraModWeaponCritPercent()
void AuraEffect::HandleAuraModWeaponCritPercent (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4428 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     for (int i = 0; i < MAX_ATTACK; ++i)
         if (Item* pItem = target->ToPlayer()->GetWeaponForAttack(WeaponAttackType(i), true))
             target->ToPlayer()->_ApplyWeaponDependentAuraCritMod(pItem, WeaponAttackType(i), this, apply);
     // mods must be applied base at equipped weapon class and subclass comparison
     // with spell->EquippedItemClass and  EquippedItemSubClassMask and EquippedItemInventoryTypeMask
     // GetMiscValue() comparison with item generated damage types
     if (GetSpellInfo()->EquippedItemClass == -1)
     {
         target->ToPlayer()->HandleBaseModValue(CRIT_PERCENTAGE,         FLAT_MOD, float (GetAmount()), apply);
         target->ToPlayer()->HandleBaseModValue(OFFHAND_CRIT_PERCENTAGE, FLAT_MOD, float (GetAmount()), apply);
         target->ToPlayer()->HandleBaseModValue(RANGED_CRIT_PERCENTAGE,  FLAT_MOD, float (GetAmount()), apply);
     }
     else
     {
         // done in Player::_ApplyWeaponDependentAuraMods
     }
 }
References Player::_ApplyWeaponDependentAuraCritMod(), ByteConverter::apply(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, CRIT_PERCENTAGE, FLAT_MOD, GetAmount(), GetSpellInfo(), AuraApplication::GetTarget(), Object::GetTypeId(), Player::GetWeaponForAttack(), Player::HandleBaseModValue(), MAX_ATTACK, OFFHAND_CRIT_PERCENTAGE, RANGED_CRIT_PERCENTAGE, Object::ToPlayer(), and TYPEID_PLAYER.
HandleAuraMounted()
void AuraEffect::HandleAuraMounted (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 2805 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     if (apply)
     {
         uint32 creatureEntry = GetMiscValue();
         // Festive Holiday Mount
         if (target->HasAura(62061))
         {
             if (GetBase()->HasEffectType(SPELL_AURA_MOD_INCREASE_MOUNTED_FLIGHT_SPEED))
                 creatureEntry = 24906;
             else
                 creatureEntry = 15665;
         }
         CreatureTemplate const* ci = sObjectMgr->GetCreatureTemplate(creatureEntry);
         if (!ci)
         {
             LOG_ERROR("sql.sql", "AuraMounted: `creature_template`='%u' not found in database (only need its modelid)", GetMiscValue());
             return;
         }
         uint32 displayID = ObjectMgr::ChooseDisplayId(ci);
         sObjectMgr->GetCreatureModelRandomGender(&displayID);
         //some spell has one aura of mount and one of vehicle
         for (uint32 i = 0; i < MAX_SPELL_EFFECTS; ++i)
             if (GetSpellInfo()->Effects[i].Effect == SPELL_EFFECT_SUMMON
                     && GetSpellInfo()->Effects[i].MiscValue == GetMiscValue())
                 displayID = 0;
         target->Mount(displayID, ci->VehicleId, GetMiscValue());
     }
     else
     {
         target->Dismount();
         //some mounts like Headless Horseman's Mount or broom stick are skill based spell
         // need to remove ALL arura related to mounts, this will stop client crash with broom stick
         // and never endless flying after using Headless Horseman's Mount
         if (mode & AURA_EFFECT_HANDLE_REAL)
             target->RemoveAurasByType(SPELL_AURA_MOUNTED);
     }
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_REAL, AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK, ObjectMgr::ChooseDisplayId(), Unit::Dismount(), GetBase(), GetMiscValue(), GetSpellInfo(), AuraApplication::GetTarget(), Unit::HasAura(), Aura::HasEffectType(), LOG_ERROR, MAX_SPELL_EFFECTS, Unit::Mount(), Unit::RemoveAurasByType(), sObjectMgr, SPELL_AURA_MOD_INCREASE_MOUNTED_FLIGHT_SPEED, SPELL_AURA_MOUNTED, SPELL_EFFECT_SUMMON, and CreatureTemplate::VehicleId.
HandleAuraOpenStable()
void AuraEffect::HandleAuraOpenStable (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 5637 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER || !target->IsInWorld())
         return;
     if (apply)
         target->ToPlayer()->GetSession()->SendStablePet(target->GetGUID());
     // client auto close stable dialog at !apply aura
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_REAL, Object::GetGUID(), Player::GetSession(), AuraApplication::GetTarget(), Object::GetTypeId(), Object::IsInWorld(), WorldSession::SendStablePet(), Object::ToPlayer(), and TYPEID_PLAYER.
HandleAuraOverrideSpells()
void AuraEffect::HandleAuraOverrideSpells (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 5694 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Player* target = aurApp->GetTarget()->ToPlayer();
     if (!target || !target->IsInWorld())
         return;
     uint32 overrideId = uint32(GetMiscValue());
     if (apply)
     {
         target->SetUInt16Value(PLAYER_FIELD_BYTES2, PLAYER_BYTES_2_OVERRIDE_SPELLS_UINT16_OFFSET, overrideId);
         if (OverrideSpellDataEntry const* overrideSpells = sOverrideSpellDataStore.LookupEntry(overrideId))
             for (uint8 i = 0; i < MAX_OVERRIDE_SPELL; ++i)
                 if (uint32 spellId = overrideSpells->spellId[i])
                     target->_addSpell(spellId, SPEC_MASK_ALL, true);
     }
     else
     {
         target->SetUInt16Value(PLAYER_FIELD_BYTES2, PLAYER_BYTES_2_OVERRIDE_SPELLS_UINT16_OFFSET, 0);
         if (OverrideSpellDataEntry const* overrideSpells = sOverrideSpellDataStore.LookupEntry(overrideId))
             for (uint8 i = 0; i < MAX_OVERRIDE_SPELL; ++i)
                 if (uint32 spellId = overrideSpells->spellId[i])
                     target->removeSpell(spellId, SPEC_MASK_ALL, true);
     }
 }
References Player::_addSpell(), ByteConverter::apply(), AURA_EFFECT_HANDLE_REAL, GetMiscValue(), AuraApplication::GetTarget(), Object::IsInWorld(), MAX_OVERRIDE_SPELL, PLAYER_BYTES_2_OVERRIDE_SPELLS_UINT16_OFFSET, PLAYER_FIELD_BYTES2, Player::removeSpell(), Object::SetUInt16Value(), sOverrideSpellDataStore, SPEC_MASK_ALL, and Object::ToPlayer().
HandleAuraRetainComboPoints()
void AuraEffect::HandleAuraRetainComboPoints (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4959 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     // combo points was added in SPELL_EFFECT_ADD_COMBO_POINTS handler
     // remove only if aura expire by time (in case combo points amount change aura removed without combo points lost)
     if (!(apply) && GetBase()->GetDuration() == 0 && target->ToPlayer()->GetComboTarget())
         if (Unit* unit = ObjectAccessor::GetUnit(*target, target->ToPlayer()->GetComboTarget()))
             target->ToPlayer()->AddComboPoints(unit, -GetAmount());
 }
References Player::AddComboPoints(), ByteConverter::apply(), AURA_EFFECT_HANDLE_REAL, GetAmount(), GetBase(), Player::GetComboTarget(), Aura::GetDuration(), AuraApplication::GetTarget(), Object::GetTypeId(), ObjectAccessor::GetUnit(), Object::ToPlayer(), and TYPEID_PLAYER.
HandleAuraSetVehicle()
void AuraEffect::HandleAuraSetVehicle (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 5724 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER || !target->IsInWorld())
         return;
     uint32 vehicleId = GetMiscValue();
     if (apply)
     {
         if (!target->CreateVehicleKit(vehicleId, 0))
             return;
     }
     else if (target->GetVehicleKit())
         target->RemoveVehicleKit();
     WorldPacket data(SMSG_PLAYER_VEHICLE_DATA, target->GetPackGUID().size() + 4);
     data << target->GetPackGUID();
     data << uint32(apply ? vehicleId : 0);
     target->SendMessageToSet(&data, true);
     if (apply)
     {
         data.Initialize(SMSG_ON_CANCEL_EXPECTED_RIDE_VEHICLE_AURA, 0);
         target->ToPlayer()->GetSession()->SendPacket(&data);
     }
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_REAL, Unit::CreateVehicleKit(), GetMiscValue(), Object::GetPackGUID(), Player::GetSession(), AuraApplication::GetTarget(), Object::GetTypeId(), Unit::GetVehicleKit(), Object::IsInWorld(), Unit::RemoveVehicleKit(), WorldObject::SendMessageToSet(), WorldSession::SendPacket(), PackedGuid::size(), SMSG_ON_CANCEL_EXPECTED_RIDE_VEHICLE_AURA, SMSG_PLAYER_VEHICLE_DATA, Object::ToPlayer(), and TYPEID_PLAYER.
HandleAuraTrackCreatures()
void AuraEffect::HandleAuraTrackCreatures (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 2675 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     if (apply)
         target->SetFlag(PLAYER_TRACK_CREATURES, uint32(1) << (GetMiscValue() - 1));
     else
         target->RemoveFlag(PLAYER_TRACK_CREATURES, uint32(1) << (GetMiscValue() - 1));
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK, GetMiscValue(), AuraApplication::GetTarget(), Object::GetTypeId(), PLAYER_TRACK_CREATURES, Object::RemoveFlag(), Object::SetFlag(), and TYPEID_PLAYER.
HandleAuraTrackResources()
void AuraEffect::HandleAuraTrackResources (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 2691 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     if (apply)
         target->SetFlag(PLAYER_TRACK_RESOURCES, uint32(1) << (GetMiscValue() - 1));
     else
         target->RemoveFlag(PLAYER_TRACK_RESOURCES, uint32(1) << (GetMiscValue() - 1));
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK, GetMiscValue(), AuraApplication::GetTarget(), Object::GetTypeId(), PLAYER_TRACK_RESOURCES, Object::RemoveFlag(), Object::SetFlag(), and TYPEID_PLAYER.
HandleAuraTrackStealthed()
void AuraEffect::HandleAuraTrackStealthed (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 2707 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     if (!(apply))
     {
         // do not remove unit flag if there are more than this auraEffect of that kind on unit on unit
         if (target->HasAuraType(GetAuraType()))
             return;
     }
     target->ApplyModFlag(PLAYER_FIELD_BYTES, PLAYER_FIELD_BYTE_TRACK_STEALTHED, apply);
 }
References ByteConverter::apply(), Object::ApplyModFlag(), AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK, GetAuraType(), AuraApplication::GetTarget(), Object::GetTypeId(), Unit::HasAuraType(), PLAYER_FIELD_BYTE_TRACK_STEALTHED, PLAYER_FIELD_BYTES, and TYPEID_PLAYER.
HandleAuraTransform()
void AuraEffect::HandleAuraTransform (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 2110 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     if (apply)
     {
         // update active transform spell only when transform or shapeshift not set or not overwriting negative by positive case
         if (GetSpellInfo()->HasAttribute(SPELL_ATTR0_NO_IMMUNITIES) || !target->GetModelForForm(target->GetShapeshiftForm()) || !GetSpellInfo()->IsPositive())
         {
             // special case (spell specific functionality)
             if (GetMiscValue() == 0)
             {
                 switch (GetId())
                 {
                     // Orb of Deception
                     case 16739:
{
                             if (target->GetTypeId() != TYPEID_PLAYER)
                                 return;
                             switch (target->getRace())
{
                                 // Blood Elf
                                 case RACE_BLOODELF:
                                     target->SetDisplayId(target->getGender() == GENDER_MALE ? 17829 : 17830);
                                     break;
                                 // Orc
                                 case RACE_ORC:
                                     target->SetDisplayId(target->getGender() == GENDER_MALE ? 10139 : 10140);
                                     break;
                                 // Troll
                                 case RACE_TROLL:
                                     target->SetDisplayId(target->getGender() == GENDER_MALE ? 10135 : 10134);
                                     break;
                                 // Tauren
                                 case RACE_TAUREN:
                                     target->SetDisplayId(target->getGender() == GENDER_MALE ? 10136 : 10147);
                                     break;
                                 // Undead
                                 case RACE_UNDEAD_PLAYER:
                                     target->SetDisplayId(target->getGender() == GENDER_MALE ? 10146 : 10145);
                                     break;
                                 // Draenei
                                 case RACE_DRAENEI:
                                     target->SetDisplayId(target->getGender() == GENDER_MALE ? 17827 : 17828);
                                     break;
                                 // Dwarf
                                 case RACE_DWARF:
                                     target->SetDisplayId(target->getGender() == GENDER_MALE ? 10141 : 10142);
                                     break;
                                 // Gnome
                                 case RACE_GNOME:
                                     target->SetDisplayId(target->getGender() == GENDER_MALE ? 10148 : 10149);
                                     break;
                                 // Human
                                 case RACE_HUMAN:
                                     target->SetDisplayId(target->getGender() == GENDER_MALE ? 10137 : 10138);
                                     break;
                                 // Night Elf
                                 case RACE_NIGHTELF:
                                     target->SetDisplayId(target->getGender() == GENDER_MALE ? 10143 : 10144);
                                     break;
                                 default:
                                     break;
                             }
                             break;
                         }
                     // Murloc costume
                     case 42365:
                         target->SetDisplayId(21723);
                         break;
                     // Dread Corsair
                     case 50517:
                     // Corsair Costume
                     case 51926:
{
                             if (target->GetTypeId() != TYPEID_PLAYER)
                                 return;
                             switch (target->getRace())
{
                                 // Blood Elf
                                 case RACE_BLOODELF:
                                     target->SetDisplayId(target->getGender() == GENDER_MALE ? 25032 : 25043);
                                     break;
                                 // Orc
                                 case RACE_ORC:
                                     target->SetDisplayId(target->getGender() == GENDER_MALE ? 25039 : 25050);
                                     break;
                                 // Troll
                                 case RACE_TROLL:
                                     target->SetDisplayId(target->getGender() == GENDER_MALE ? 25041 : 25052);
                                     break;
                                 // Tauren
                                 case RACE_TAUREN:
                                     target->SetDisplayId(target->getGender() == GENDER_MALE ? 25040 : 25051);
                                     break;
                                 // Undead
                                 case RACE_UNDEAD_PLAYER:
                                     target->SetDisplayId(target->getGender() == GENDER_MALE ? 25042 : 25053);
                                     break;
                                 // Draenei
                                 case RACE_DRAENEI:
                                     target->SetDisplayId(target->getGender() == GENDER_MALE ? 25033 : 25044);
                                     break;
                                 // Dwarf
                                 case RACE_DWARF:
                                     target->SetDisplayId(target->getGender() == GENDER_MALE ? 25034 : 25045);
                                     break;
                                 // Gnome
                                 case RACE_GNOME:
                                     target->SetDisplayId(target->getGender() == GENDER_MALE ? 25035 : 25046);
                                     break;
                                 // Human
                                 case RACE_HUMAN:
                                     target->SetDisplayId(target->getGender() == GENDER_MALE ? 25037 : 25048);
                                     break;
                                 // Night Elf
                                 case RACE_NIGHTELF:
                                     target->SetDisplayId(target->getGender() == GENDER_MALE ? 25038 : 25049);
                                     break;
                                 default:
                                     break;
                             }
                             break;
                         }
                     // Pygmy Oil
                     case 53806:
                         target->SetDisplayId(22512);
                         break;
                     // Honor the Dead
                     case 65386:
                     case 65495:
                         target->SetDisplayId(target->getGender() == GENDER_MALE ? 29203 : 29204);
                         break;
                     // Darkspear Pride
                     case 75532:
                         target->SetDisplayId(target->getGender() == GENDER_MALE ? 31737 : 31738);
                         break;
                     // Gnomeregan Pride
                     case 75531:
                         target->SetDisplayId(target->getGender() == GENDER_MALE ? 31654 : 31655);
                         break;
                     default:
                         break;
                 }
             }
             else
             {
                 CreatureTemplate const* ci = sObjectMgr->GetCreatureTemplate(GetMiscValue());
                 if (!ci)
                 {
                     target->SetDisplayId(16358);              // pig pink ^_^
                     LOG_ERROR("spells.aura.effect", "Auras: unknown creature id = %d (only need its modelid) From Spell Aura Transform in Spell ID = %d", GetMiscValue(), GetId());
                 }
                 else
                 {
                     uint32 model_id = 0;
                     if (uint32 modelid = ci->GetRandomValidModelId())
                         model_id = modelid;                     // Will use the default model here
                     // Polymorph (sheep)
                     if (GetSpellInfo()->SpellFamilyName == SPELLFAMILY_MAGE && GetSpellInfo()->SpellIconID == 82 && GetSpellInfo()->SpellVisual[0] == 12978)
                         if (Unit* caster = GetCaster())
                             if (caster->HasAura(52648))         // Glyph of the Penguin
                                 model_id = 26452;
                     target->SetDisplayId(model_id);
                     // Dragonmaw Illusion (set mount model also)
                     if (GetId() == 42016 && target->GetMountID() && !target->GetAuraEffectsByType(SPELL_AURA_MOD_INCREASE_MOUNTED_FLIGHT_SPEED).empty())
                         target->SetUInt32Value(UNIT_FIELD_MOUNTDISPLAYID, 16314);
                 }
             }
         }
         // update active transform spell only when transform or shapeshift not set or not overwriting negative by positive case
         SpellInfo const* transformSpellInfo = sSpellMgr->GetSpellInfo(target->getTransForm());
         if (!transformSpellInfo || GetSpellInfo()->HasAttribute(SPELL_ATTR0_NO_IMMUNITIES) || !GetSpellInfo()->IsPositive() || transformSpellInfo->IsPositive())
             target->setTransForm(GetId());
         // polymorph case
         if ((mode & AURA_EFFECT_HANDLE_REAL) && target->GetTypeId() == TYPEID_PLAYER && target->IsPolymorphed())
         {
             // for players, start regeneration after 1s (in polymorph fast regeneration case)
             // only if caster is Player (after patch 2.4.2)
             if (GetCasterGUID().IsPlayer())
                 target->ToPlayer()->setRegenTimerCount(1 * IN_MILLISECONDS);
             //dismount polymorphed target (after patch 2.4.2)
             if (target->IsMounted())
                 target->RemoveAurasByType(SPELL_AURA_MOUNTED);
         }
     }
     else
     {
         // HandleEffect(this, AURA_EFFECT_HANDLE_SEND_FOR_CLIENT, true) will reapply it if need
         if (target->getTransForm() == GetId())
             target->setTransForm(0);
         target->RestoreDisplayId();
         // Dragonmaw Illusion (restore mount model)
         if (GetId() == 42016 && target->GetMountID() == 16314)
         {
             if (!target->GetAuraEffectsByType(SPELL_AURA_MOUNTED).empty())
             {
                 uint32 cr_id = target->GetAuraEffectsByType(SPELL_AURA_MOUNTED).front()->GetMiscValue();
                 if (CreatureTemplate const* ci = sObjectMgr->GetCreatureTemplate(cr_id))
                 {
                     uint32 displayID = ObjectMgr::ChooseDisplayId(ci);
                     sObjectMgr->GetCreatureModelRandomGender(&displayID);
                     target->SetUInt32Value(UNIT_FIELD_MOUNTDISPLAYID, displayID);
                 }
             }
         }
     }
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_REAL, AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK, ObjectMgr::ChooseDisplayId(), GENDER_MALE, Unit::GetAuraEffectsByType(), GetCaster(), GetCasterGUID(), Unit::getGender(), GetId(), GetMiscValue(), Unit::GetModelForForm(), Unit::GetMountID(), Unit::getRace(), CreatureTemplate::GetRandomValidModelId(), Unit::GetShapeshiftForm(), GetSpellInfo(), AuraApplication::GetTarget(), Unit::getTransForm(), Object::GetTypeId(), IN_MILLISECONDS, Unit::IsMounted(), Unit::IsPolymorphed(), SpellInfo::IsPositive(), LOG_ERROR, RACE_BLOODELF, RACE_DRAENEI, RACE_DWARF, RACE_GNOME, RACE_HUMAN, RACE_NIGHTELF, RACE_ORC, RACE_TAUREN, RACE_TROLL, RACE_UNDEAD_PLAYER, Unit::RemoveAurasByType(), Unit::RestoreDisplayId(), Unit::SetDisplayId(), Player::setRegenTimerCount(), Unit::setTransForm(), Object::SetUInt32Value(), sObjectMgr, SPELL_ATTR0_NO_IMMUNITIES, SPELL_AURA_MOD_INCREASE_MOUNTED_FLIGHT_SPEED, SPELL_AURA_MOUNTED, SPELLFAMILY_MAGE, sSpellMgr, Object::ToPlayer(), TYPEID_PLAYER, and UNIT_FIELD_MOUNTDISPLAYID.
HandleAuraUntrackable()
void AuraEffect::HandleAuraUntrackable (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 2747 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     if (apply)
         target->SetByteFlag(UNIT_FIELD_BYTES_1, UNIT_BYTES_1_OFFSET_VIS_FLAG, UNIT_STAND_FLAGS_UNTRACKABLE);
     else
     {
         // do not remove unit flag if there are more than this auraEffect of that kind on unit on unit
         if (target->HasAuraType(GetAuraType()))
             return;
         target->RemoveByteFlag(UNIT_FIELD_BYTES_1, UNIT_BYTES_1_OFFSET_VIS_FLAG, UNIT_STAND_FLAGS_UNTRACKABLE);
     }
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK, GetAuraType(), AuraApplication::GetTarget(), Unit::HasAuraType(), Object::RemoveByteFlag(), Object::SetByteFlag(), UNIT_BYTES_1_OFFSET_VIS_FLAG, UNIT_FIELD_BYTES_1, and UNIT_STAND_FLAGS_UNTRACKABLE.
HandleAuraWaterWalk()
void AuraEffect::HandleAuraWaterWalk (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 2874 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     if (Player* targetPlayer = target->ToPlayer())
     {
         sScriptMgr->AnticheatSetUnderACKmount(targetPlayer);
     }
     if (!apply)
     {
         // do not remove unit flag if there are more than this auraEffect of that kind on unit on unit
         if (target->HasAuraType(GetAuraType()))
             return;
     }
     target->SetWaterWalking(apply);
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK, GetAuraType(), AuraApplication::GetTarget(), Unit::HasAuraType(), Unit::SetWaterWalking(), sScriptMgr, and Object::ToPlayer().
HandleBindSight()
void AuraEffect::HandleBindSight (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 5444 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     Unit* caster = GetCaster();
     if (!caster || caster->GetTypeId() != TYPEID_PLAYER)
         return;
     caster->ToPlayer()->SetViewpoint(target, apply);
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_REAL, GetCaster(), AuraApplication::GetTarget(), Object::GetTypeId(), Player::SetViewpoint(), Object::ToPlayer(), and TYPEID_PLAYER.
HandleChannelDeathItem()
void AuraEffect::HandleChannelDeathItem (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 5399 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     if (apply || aurApp->GetRemoveMode() != AURA_REMOVE_BY_DEATH)
         return;
     Unit* caster = GetCaster();
     if (!caster || caster->GetTypeId() != TYPEID_PLAYER)
         return;
     Player* plCaster = caster->ToPlayer();
     // Item amount
     if (GetAmount() <= 0)
         return;
     if (GetSpellInfo()->Effects[m_effIndex].ItemType == 0)
         return;
     //Adding items
     uint32 noSpaceForCount = 0;
     uint32 count = m_amount;
     ItemPosCountVec dest;
     InventoryResult msg = plCaster->CanStoreNewItem(NULL_BAG, NULL_SLOT, dest, GetSpellInfo()->Effects[m_effIndex].ItemType, count, &noSpaceForCount);
     if (msg != EQUIP_ERR_OK)
     {
         count -= noSpaceForCount;
         plCaster->SendEquipError(msg, nullptr, nullptr, GetSpellInfo()->Effects[m_effIndex].ItemType);
         if (count == 0)
             return;
     }
     Item* newitem = plCaster->StoreNewItem(dest, GetSpellInfo()->Effects[m_effIndex].ItemType, true);
     if (!newitem)
     {
         plCaster->SendEquipError(EQUIP_ERR_ITEM_NOT_FOUND, nullptr, nullptr);
         return;
     }
     plCaster->SendNewItem(newitem, count, true, true);
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_REAL, AURA_REMOVE_BY_DEATH, Player::CanStoreNewItem(), count(), EQUIP_ERR_ITEM_NOT_FOUND, EQUIP_ERR_OK, GetAmount(), GetCaster(), AuraApplication::GetRemoveMode(), GetSpellInfo(), Object::GetTypeId(), m_amount, m_effIndex, NULL_BAG, NULL_SLOT, Player::SendEquipError(), Player::SendNewItem(), Player::StoreNewItem(), Object::ToPlayer(), and TYPEID_PLAYER.
HandleCharmConvert()
void AuraEffect::HandleCharmConvert (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 3179 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     Unit* caster = GetCaster();
     if (apply)
         target->SetCharmedBy(caster, CHARM_TYPE_CONVERT, aurApp);
     else
         target->RemoveCharmedBy(caster);
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_REAL, CHARM_TYPE_CONVERT, GetCaster(), AuraApplication::GetTarget(), Unit::RemoveCharmedBy(), and Unit::SetCharmedBy().
HandleComprehendLanguage()
void AuraEffect::HandleComprehendLanguage (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 5547 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     if (apply)
         target->SetFlag(UNIT_FIELD_FLAGS_2, UNIT_FLAG2_COMPREHEND_LANG);
     else
     {
         if (target->HasAuraType(GetAuraType()))
             return;
         target->RemoveFlag(UNIT_FIELD_FLAGS_2, UNIT_FLAG2_COMPREHEND_LANG);
     }
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK, GetAuraType(), AuraApplication::GetTarget(), Unit::HasAuraType(), Object::RemoveFlag(), Object::SetFlag(), UNIT_FIELD_FLAGS_2, and UNIT_FLAG2_COMPREHEND_LANG.
HandleDetectAmore()
void AuraEffect::HandleDetectAmore (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 1673 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK))
     {
         return;
     }
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
     {
         return;
     }
     if (apply)
     {
         target->SetByteFlag(PLAYER_FIELD_BYTES2, 3, 1 << (GetMiscValue() - 1));
     }
     else
     {
         if (target->HasAuraType(SPELL_AURA_DETECT_AMORE))
         {
             Unit::AuraEffectList const& amoreAuras = target->GetAuraEffectsByType(SPELL_AURA_DETECT_AMORE);
             for (AuraEffect const* aurEff : amoreAuras)
                 if (GetMiscValue() == aurEff->GetMiscValue())
                 {
                     return;
                 }
         }
         target->RemoveByteFlag(PLAYER_FIELD_BYTES2, 3, 1 << (GetMiscValue() - 1));
     }
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK, Unit::GetAuraEffectsByType(), GetMiscValue(), AuraApplication::GetTarget(), Object::GetTypeId(), Unit::HasAuraType(), PLAYER_FIELD_BYTES2, Object::RemoveByteFlag(), Object::SetByteFlag(), SPELL_AURA_DETECT_AMORE, and TYPEID_PLAYER.
HandleEffect() [1/2]
void AuraEffect::HandleEffect (AuraApplication * aurApp, uint8 mode, bool apply)
Definition at line 733 of file SpellAuraEffects.cpp.
 {
     // check if call is correct, we really don't want using bitmasks here (with 1 exception)
     ASSERT(mode == AURA_EFFECT_HANDLE_REAL
            || mode == AURA_EFFECT_HANDLE_SEND_FOR_CLIENT
            || mode == AURA_EFFECT_HANDLE_CHANGE_AMOUNT
            || mode == AURA_EFFECT_HANDLE_STAT
            || mode == AURA_EFFECT_HANDLE_SKILL
            || mode == AURA_EFFECT_HANDLE_REAPPLY
            || mode == (AURA_EFFECT_HANDLE_CHANGE_AMOUNT | AURA_EFFECT_HANDLE_REAPPLY));
     // register/unregister effect in lists in case of real AuraEffect apply/remove
     // registration/unregistration is done always before real effect handling (some effect handlers code is depending on this)
     if (mode & AURA_EFFECT_HANDLE_REAL)
         aurApp->GetTarget()->_RegisterAuraEffect(this, apply);
     // xinef: stacking system, force return if effect is disabled, prevents double apply / unapply
     // xinef: placed here so above line can unregister effect from the list
     // xinef: this condition works under assumption that effect handlers performs ALL necessery action with CHANGE_AMOUNT mode
     // xinef: as far as i've checked, all grouped spells meet this condition
     if (!aurApp->IsActive(GetEffIndex()))
         return;
     // real aura apply/remove, handle modifier
     if (mode & AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK)
         ApplySpellMod(aurApp->GetTarget(), apply);
     // call scripts helping/replacing effect handlers
     bool prevented = false;
     if (apply)
         prevented = GetBase()->CallScriptEffectApplyHandlers(this, const_cast<AuraApplication const*>(aurApp), (AuraEffectHandleModes)mode);
     else
         prevented = GetBase()->CallScriptEffectRemoveHandlers(this, const_cast<AuraApplication const*>(aurApp), (AuraEffectHandleModes)mode);
     // check if script events have removed the aura or if default effect prevention was requested
     if ((apply && aurApp->GetRemoveMode()) || prevented)
         return;
     (*this.*AuraEffectHandler [GetAuraType()])(aurApp, mode, apply);
     // check if script events have removed the aura or if default effect prevention was requested
     if (apply && aurApp->GetRemoveMode())
         return;
     // call scripts triggering additional events after apply/remove
     if (apply)
         GetBase()->CallScriptAfterEffectApplyHandlers(this, aurApp, (AuraEffectHandleModes)mode);
     else
         GetBase()->CallScriptAfterEffectRemoveHandlers(this, aurApp, (AuraEffectHandleModes)mode);
 }
References Unit::_RegisterAuraEffect(), ByteConverter::apply(), ApplySpellMod(), ASSERT, AURA_EFFECT_HANDLE_CHANGE_AMOUNT, AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_REAL, AURA_EFFECT_HANDLE_REAPPLY, AURA_EFFECT_HANDLE_SEND_FOR_CLIENT, AURA_EFFECT_HANDLE_SKILL, AURA_EFFECT_HANDLE_STAT, AuraEffectHandler, Aura::CallScriptAfterEffectApplyHandlers(), Aura::CallScriptAfterEffectRemoveHandlers(), Aura::CallScriptEffectApplyHandlers(), Aura::CallScriptEffectRemoveHandlers(), const, GetAuraType(), GetBase(), GetEffIndex(), AuraApplication::GetRemoveMode(), AuraApplication::GetTarget(), and AuraApplication::IsActive().
Referenced by AuraApplication::_HandleEffect(), ChangeAmount(), Aura::HandleAllEffects(), HandleEffect(), and Unit::RestoreDisplayId().
HandleEffect() [2/2]
void AuraEffect::HandleEffect (Unit * target, uint8 mode, bool apply)
Definition at line 784 of file SpellAuraEffects.cpp.
 {
     AuraApplication* aurApp = GetBase()->GetApplicationOfTarget(target->GetGUID());
     ASSERT(aurApp);
     HandleEffect(aurApp, mode, apply);
 }
References ByteConverter::apply(), ASSERT, Aura::GetApplicationOfTarget(), GetBase(), Object::GetGUID(), and HandleEffect().
HandleFarSight()
void AuraEffect::HandleFarSight (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 5459 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
     {
         return;
     }
     Unit* caster = GetCaster();
     if (!caster || caster->GetTypeId() != TYPEID_PLAYER)
     {
         return;
     }
     Player* player = caster->ToPlayer();
     if (apply)
     {
         player->SetFarSightDistance(m_spellInfo->GetMaxRange());
     }
     else
     {
         player->ResetFarSightDistance();
     }
     caster->UpdateObjectVisibility(!apply);
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_REAL, GetCaster(), SpellInfo::GetMaxRange(), Object::GetTypeId(), m_spellInfo, Player::ResetFarSightDistance(), Player::SetFarSightDistance(), Object::ToPlayer(), TYPEID_PLAYER, and Unit::UpdateObjectVisibility().
HandleFeignDeath()
void AuraEffect::HandleFeignDeath (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 2374 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     if (Player* targetPlayer = target->ToPlayer())
     {
         sScriptMgr->AnticheatSetUnderACKmount(targetPlayer);
     }
     if (apply)
     {
         /*
         WorldPacket data(SMSG_FEIGN_DEATH_RESISTED, 9);
         data<<target->GetGUID();
         data<<uint8(0);
         target->SendMessageToSet(&data, true);
         */
         UnitList targets;
         Acore::AnyUnfriendlyUnitInObjectRangeCheck u_check(target, target, target->GetVisibilityRange()); // no VISIBILITY_COMPENSATION, distance is enough
         Acore::UnitListSearcher<Acore::AnyUnfriendlyUnitInObjectRangeCheck> searcher(target, targets, u_check);
         Cell::VisitAllObjects(target, searcher, target->GetMap()->GetVisibilityRange());
         for (UnitList::iterator iter = targets.begin(); iter != targets.end(); ++iter)
         {
             if (!(*iter)->HasUnitState(UNIT_STATE_CASTING))
                 continue;
             for (uint32 i = CURRENT_FIRST_NON_MELEE_SPELL; i < CURRENT_MAX_SPELL; i++)
             {
                 if ((*iter)->GetCurrentSpell(i) && (*iter)->GetCurrentSpell(i)->m_targets.GetUnitTargetGUID() == target->GetGUID())
                 {
                     const SpellInfo* si = (*iter)->GetCurrentSpell(i)->GetSpellInfo();
                     if (si->HasAttribute(SPELL_ATTR6_IGNORE_PHASE_SHIFT) && (*iter)->GetTypeId() == TYPEID_UNIT)
                     {
                         Creature* c = (*iter)->ToCreature();
                         if ((!c->IsPet() && c->GetCreatureTemplate()->rank == CREATURE_ELITE_WORLDBOSS) || c->isWorldBoss() || c->IsDungeonBoss())
                             continue;
                     }
                     bool interrupt = false; // pussywizard: skip spells that don't target units, but casted on unit (eg. TARGET_DEST_TARGET_ENEMY)
                     for (uint8 j = 0; j < MAX_SPELL_EFFECTS; ++j)
                         if (si->Effects[j].Effect && (si->Effects[j].GetUsedTargetObjectType() == TARGET_OBJECT_TYPE_UNIT || si->Effects[j].GetUsedTargetObjectType() == TARGET_OBJECT_TYPE_UNIT_AND_DEST))
{
                             // at least one effect truly targets an unit, interrupt the spell
                             interrupt = true;
                             break;
                         }
                     if (interrupt)
                         (*iter)->InterruptSpell(CurrentSpellTypes(i), false);
                 }
             }
         }
         if (target->GetInstanceScript() && target->GetInstanceScript()->IsEncounterInProgress())
         {
             // Xinef: replaced with CombatStop(false)
             target->AttackStop();
             target->RemoveAllAttackers();
             target->getHostileRefMgr().addThreatPercent(-100);
             target->ToPlayer()->SendAttackSwingCancelAttack();     // melee and ranged forced attack cancel
         }
         else
         {
             target->CombatStop();
             target->getHostileRefMgr().deleteReferences();
         }
         target->RemoveAurasWithInterruptFlags(AURA_INTERRUPT_FLAG_IMMUNE_OR_LOST_SELECTION);
         // prevent interrupt message
         if (GetCasterGUID() == target->GetGUID())
         {
             if (target->GetCurrentSpell(CURRENT_GENERIC_SPELL))
                 target->FinishSpell(CURRENT_GENERIC_SPELL, true);
             // interrupt autoshot
             if (target->GetCurrentSpell(CURRENT_AUTOREPEAT_SPELL))
             {
                 target->FinishSpell(CURRENT_AUTOREPEAT_SPELL);
                 target->ToPlayer()->SendAutoRepeatCancel(target);
             }
         }
         target->InterruptNonMeleeSpells(true);
         // stop handling the effect if it was removed by linked event
         if (aurApp->GetRemoveMode())
             return;
         // blizz like 2.0.x
         target->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PREVENT_EMOTES_FROM_CHAT_TEXT);
         // blizz like 2.0.x
         target->SetFlag(UNIT_FIELD_FLAGS_2, UNIT_FLAG2_FEIGN_DEATH);
         // blizz like 2.0.x
         target->SetFlag(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_DEAD);
         target->AddUnitState(UNIT_STATE_DIED);
     }
     else
     {
         /*
         WorldPacket data(SMSG_FEIGN_DEATH_RESISTED, 9);
         data<<target->GetGUID();
         data<<uint8(1);
         target->SendMessageToSet(&data, true);
         */
         // blizz like 2.0.x
         target->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PREVENT_EMOTES_FROM_CHAT_TEXT);
         // blizz like 2.0.x
         target->RemoveFlag(UNIT_FIELD_FLAGS_2, UNIT_FLAG2_FEIGN_DEATH);
         // blizz like 2.0.x
         target->RemoveFlag(UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_DEAD);
         target->ClearUnitState(UNIT_STATE_DIED);
     }
 }
References HostileRefMgr::addThreatPercent(), Unit::AddUnitState(), ByteConverter::apply(), Unit::AttackStop(), AURA_EFFECT_HANDLE_REAL, AURA_INTERRUPT_FLAG_IMMUNE_OR_LOST_SELECTION, mpq::c, Unit::ClearUnitState(), Unit::CombatStop(), CREATURE_ELITE_WORLDBOSS, CURRENT_AUTOREPEAT_SPELL, CURRENT_FIRST_NON_MELEE_SPELL, CURRENT_GENERIC_SPELL, CURRENT_MAX_SPELL, HostileRefMgr::deleteReferences(), SpellInfo::Effects, Unit::FinishSpell(), GetCasterGUID(), Unit::GetCurrentSpell(), Object::GetGUID(), Unit::getHostileRefMgr(), WorldObject::GetInstanceScript(), WorldObject::GetMap(), AuraApplication::GetRemoveMode(), AuraApplication::GetTarget(), Object::GetTypeId(), WorldObject::GetVisibilityRange(), Map::GetVisibilityRange(), SpellInfo::HasAttribute(), Unit::InterruptNonMeleeSpells(), InstanceScript::IsEncounterInProgress(), MAX_SPELL_EFFECTS, Unit::RemoveAllAttackers(), Unit::RemoveAurasWithInterruptFlags(), Object::RemoveFlag(), Player::SendAttackSwingCancelAttack(), Player::SendAutoRepeatCancel(), Object::SetFlag(), SPELL_ATTR6_IGNORE_PHASE_SHIFT, sScriptMgr, TARGET_OBJECT_TYPE_UNIT, TARGET_OBJECT_TYPE_UNIT_AND_DEST, Object::ToPlayer(), TYPEID_PLAYER, TYPEID_UNIT, UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_DEAD, UNIT_FIELD_FLAGS, UNIT_FIELD_FLAGS_2, UNIT_FLAG2_FEIGN_DEATH, UNIT_FLAG_PREVENT_EMOTES_FROM_CHAT_TEXT, UNIT_STATE_CASTING, UNIT_STATE_DIED, and Cell::VisitAllObjects().
HandleForceMoveForward()
void AuraEffect::HandleForceMoveForward (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 2956 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     if (apply)
         target->SetFlag(UNIT_FIELD_FLAGS_2, UNIT_FLAG2_FORCE_MOVEMENT);
     else
     {
         // do not remove unit flag if there are more than this auraEffect of that kind on unit on unit
         if (target->HasAuraType(GetAuraType()))
             return;
         target->RemoveFlag(UNIT_FIELD_FLAGS_2, UNIT_FLAG2_FORCE_MOVEMENT);
     }
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK, GetAuraType(), AuraApplication::GetTarget(), Unit::HasAuraType(), Object::RemoveFlag(), Object::SetFlag(), UNIT_FIELD_FLAGS_2, and UNIT_FLAG2_FORCE_MOVEMENT.
HandleForceReaction()
void AuraEffect::HandleForceReaction (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 5485 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     Player* player = target->ToPlayer();
     uint32 faction_id = GetMiscValue();
     ReputationRank faction_rank = ReputationRank(m_amount);
     player->GetReputationMgr().ApplyForceReaction(faction_id, faction_rank, apply);
     player->GetReputationMgr().SendForceReactions();
     // stop fighting if at apply forced rank friendly or at remove real rank friendly
     if ((apply && faction_rank >= REP_FRIENDLY) || (!apply && player->GetReputationRank(faction_id) >= REP_FRIENDLY))
         player->StopAttackFaction(faction_id);
 }
References ByteConverter::apply(), ReputationMgr::ApplyForceReaction(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, GetMiscValue(), Player::GetReputationMgr(), Player::GetReputationRank(), AuraApplication::GetTarget(), Object::GetTypeId(), m_amount, REP_FRIENDLY, ReputationMgr::SendForceReactions(), Unit::StopAttackFaction(), Object::ToPlayer(), and TYPEID_PLAYER.
HandleModAttackSpeed()
void AuraEffect::HandleModAttackSpeed (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4585 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     target->ApplyAttackTimePercentMod(BASE_ATTACK, float(GetAmount()), apply);
     target->UpdateDamagePhysical(BASE_ATTACK);
 }
References ByteConverter::apply(), Unit::ApplyAttackTimePercentMod(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, BASE_ATTACK, GetAmount(), AuraApplication::GetTarget(), and Unit::UpdateDamagePhysical().
HandleModBaseResistance()
void AuraEffect::HandleModBaseResistance (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 3953 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     // only players have base stats
     if (target->GetTypeId() != TYPEID_PLAYER)
     {
         //only pets have base stats
         if (target->IsPet() && (GetMiscValue() & SPELL_SCHOOL_MASK_NORMAL))
             target->HandleStatModifier(UNIT_MOD_ARMOR, TOTAL_VALUE, float(GetAmount()), apply);
     }
     else
     {
         for (int i = SPELL_SCHOOL_NORMAL; i < MAX_SPELL_SCHOOL; i++)
             if (GetMiscValue() & (1 << i))
                 target->HandleStatModifier(UnitMods(UNIT_MOD_RESISTANCE_START + i), TOTAL_VALUE, float(GetAmount()), apply);
     }
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, GetAmount(), GetMiscValue(), AuraApplication::GetTarget(), Object::GetTypeId(), Unit::HandleStatModifier(), Unit::IsPet(), MAX_SPELL_SCHOOL, SPELL_SCHOOL_MASK_NORMAL, SPELL_SCHOOL_NORMAL, TOTAL_VALUE, TYPEID_PLAYER, UNIT_MOD_ARMOR, and UNIT_MOD_RESISTANCE_START.
HandleModCastingSpeed()
void AuraEffect::HandleModCastingSpeed (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4543 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     // Xinef: Do not apply such auras in normal way
     if (GetAmount() >= 1000)
     {
         target->SetInstantCast(apply);
         return;
     }
     target->ApplyCastTimePercentMod((float)GetAmount(), apply);
 }
References ByteConverter::apply(), Unit::ApplyCastTimePercentMod(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, GetAmount(), AuraApplication::GetTarget(), and Unit::SetInstantCast().
HandleModCharm()
void AuraEffect::HandleModCharm (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 3164 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     Unit* caster = GetCaster();
     if (apply)
         target->SetCharmedBy(caster, CHARM_TYPE_CHARM, aurApp);
     else
         target->RemoveCharmedBy(caster);
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_REAL, CHARM_TYPE_CHARM, GetCaster(), AuraApplication::GetTarget(), Unit::RemoveCharmedBy(), and Unit::SetCharmedBy().
Referenced by HandleModPossess().
HandleModCombatSpeedPct()
void AuraEffect::HandleModCombatSpeedPct (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4572 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     target->ApplyCastTimePercentMod(float(GetAmount()), apply);
     target->ApplyAttackTimePercentMod(BASE_ATTACK, float(GetAmount()), apply);
     target->ApplyAttackTimePercentMod(OFF_ATTACK, float(GetAmount()), apply);
     target->ApplyAttackTimePercentMod(RANGED_ATTACK, float(GetAmount()), apply);
 }
References ByteConverter::apply(), Unit::ApplyAttackTimePercentMod(), Unit::ApplyCastTimePercentMod(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, BASE_ATTACK, GetAmount(), AuraApplication::GetTarget(), OFF_ATTACK, and RANGED_ATTACK.
HandleModConfuse()
void AuraEffect::HandleModConfuse (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 3031 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     target->SetControlled(apply, UNIT_STATE_CONFUSED);
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_REAL, AuraApplication::GetTarget(), Unit::SetControlled(), and UNIT_STATE_CONFUSED.
HandleModDamageDone()
void AuraEffect::HandleModDamageDone (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4748 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     // apply item specific bonuses for already equipped weapon
     if (target->GetTypeId() == TYPEID_PLAYER)
     {
         for (int i = 0; i < MAX_ATTACK; ++i)
             if (Item* pItem = target->ToPlayer()->GetWeaponForAttack(WeaponAttackType(i), true))
                 target->ToPlayer()->_ApplyWeaponDependentAuraDamageMod(pItem, WeaponAttackType(i), this, apply);
     }
     // GetMiscValue() is bitmask of spell schools
     // 1 (0-bit) - normal school damage (SPELL_SCHOOL_MASK_NORMAL)
     // 126 - full bitmask all magic damages (SPELL_SCHOOL_MASK_MAGIC) including wands
     // 127 - full bitmask any damages
     //
     // mods must be applied base at equipped weapon class and subclass comparison
     // with spell->EquippedItemClass and  EquippedItemSubClassMask and EquippedItemInventoryTypeMask
     // GetMiscValue() comparison with item generated damage types
     if ((GetMiscValue() & SPELL_SCHOOL_MASK_NORMAL) != 0 && sScriptMgr->CanModAuraEffectDamageDone(this, target, aurApp, mode, apply))
     {
         // apply generic physical damage bonuses including wand case
         if (GetSpellInfo()->EquippedItemClass == -1 || target->GetTypeId() != TYPEID_PLAYER)
         {
             target->HandleStatModifier(UNIT_MOD_DAMAGE_MAINHAND, TOTAL_VALUE, float(GetAmount()), apply);
             target->HandleStatModifier(UNIT_MOD_DAMAGE_OFFHAND, TOTAL_VALUE, float(GetAmount()), apply);
             target->HandleStatModifier(UNIT_MOD_DAMAGE_RANGED, TOTAL_VALUE, float(GetAmount()), apply);
             if (target->GetTypeId() == TYPEID_PLAYER)
             {
                 if (GetAmount() > 0)
                     target->ApplyModInt32Value(PLAYER_FIELD_MOD_DAMAGE_DONE_POS, GetAmount(), apply);
                 else
                     target->ApplyModInt32Value(PLAYER_FIELD_MOD_DAMAGE_DONE_NEG, GetAmount(), apply);
             }
         }
         else
         {
             // done in Player::_ApplyWeaponDependentAuraMods
         }
     }
     // Skip non magic case for Speedup
     if ((GetMiscValue() & SPELL_SCHOOL_MASK_MAGIC) == 0)
         return;
     if (GetSpellInfo()->EquippedItemClass != -1 || GetSpellInfo()->EquippedItemInventoryTypeMask != 0)
     {
         // wand magic case (skip generic to all item spell bonuses)
         // done in Player::_ApplyWeaponDependentAuraMods
         // Skip item specific requirements for not wand magic damage
         return;
     }
     // Magic damage modifiers implemented in Unit::SpellDamageBonus
     // This information for client side use only
     if (target->GetTypeId() == TYPEID_PLAYER)
     {
         if (GetAmount() > 0)
         {
             for (uint32 i = SPELL_SCHOOL_HOLY; i < MAX_SPELL_SCHOOL; i++)
             {
                 if ((GetMiscValue() & (1 << i)) != 0)
                     target->ApplyModInt32Value(PLAYER_FIELD_MOD_DAMAGE_DONE_POS + i, GetAmount(), apply);
             }
         }
         else
         {
             for (uint32 i = SPELL_SCHOOL_HOLY; i < MAX_SPELL_SCHOOL; i++)
             {
                 if ((GetMiscValue() & (1 << i)) != 0)
                     target->ApplyModInt32Value(PLAYER_FIELD_MOD_DAMAGE_DONE_NEG + i, GetAmount(), apply);
             }
         }
         if (Guardian* pet = target->ToPlayer()->GetGuardianPet())
             pet->UpdateAttackPowerAndDamage();
     }
 }
References Player::_ApplyWeaponDependentAuraDamageMod(), ByteConverter::apply(), Object::ApplyModInt32Value(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, GetAmount(), Unit::GetGuardianPet(), GetMiscValue(), GetSpellInfo(), AuraApplication::GetTarget(), Object::GetTypeId(), Player::GetWeaponForAttack(), Unit::HandleStatModifier(), MAX_ATTACK, MAX_SPELL_SCHOOL, PLAYER_FIELD_MOD_DAMAGE_DONE_NEG, PLAYER_FIELD_MOD_DAMAGE_DONE_POS, SPELL_SCHOOL_HOLY, SPELL_SCHOOL_MASK_MAGIC, SPELL_SCHOOL_MASK_NORMAL, sScriptMgr, Object::ToPlayer(), TOTAL_VALUE, TYPEID_PLAYER, UNIT_MOD_DAMAGE_MAINHAND, UNIT_MOD_DAMAGE_OFFHAND, and UNIT_MOD_DAMAGE_RANGED.
HandleModDamagePercentDone()
void AuraEffect::HandleModDamagePercentDone (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4833 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     if (!target)
         return;
     if (!sScriptMgr->CanModAuraEffectModDamagePercentDone(this, target, aurApp, mode, apply))
         return;
     if (target->GetTypeId() == TYPEID_PLAYER)
     {
         for (int i = 0; i < MAX_ATTACK; ++i)
             if (Item* item = target->ToPlayer()->GetWeaponForAttack(WeaponAttackType(i), false))
                 target->ToPlayer()->_ApplyWeaponDependentAuraDamageMod(item, WeaponAttackType(i), this, apply);
     }
     if ((GetMiscValue() & SPELL_SCHOOL_MASK_NORMAL) && (GetSpellInfo()->EquippedItemClass == -1 || target->GetTypeId() != TYPEID_PLAYER))
     {
         target->HandleStatModifier(UNIT_MOD_DAMAGE_MAINHAND, TOTAL_PCT, float(GetAmount()), apply);
         target->HandleStatModifier(UNIT_MOD_DAMAGE_OFFHAND,  TOTAL_PCT, float(GetAmount()), apply);
         target->HandleStatModifier(UNIT_MOD_DAMAGE_RANGED,   TOTAL_PCT, float(GetAmount()), apply);
         if (target->GetTypeId() == TYPEID_PLAYER)
             target->ToPlayer()->ApplyPercentModFloatValue(PLAYER_FIELD_MOD_DAMAGE_DONE_PCT, float (GetAmount()), apply);
     }
     else
     {
         // done in Player::_ApplyWeaponDependentAuraMods for SPELL_SCHOOL_MASK_NORMAL && EquippedItemClass != -1 and also for wand case
     }
 }
References Player::_ApplyWeaponDependentAuraDamageMod(), ByteConverter::apply(), Object::ApplyPercentModFloatValue(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, GetAmount(), GetMiscValue(), GetSpellInfo(), AuraApplication::GetTarget(), Object::GetTypeId(), Player::GetWeaponForAttack(), Unit::HandleStatModifier(), MAX_ATTACK, PLAYER_FIELD_MOD_DAMAGE_DONE_PCT, SPELL_SCHOOL_MASK_NORMAL, sScriptMgr, Object::ToPlayer(), TOTAL_PCT, TYPEID_PLAYER, UNIT_MOD_DAMAGE_MAINHAND, UNIT_MOD_DAMAGE_OFFHAND, and UNIT_MOD_DAMAGE_RANGED.
HandleModFear()
void AuraEffect::HandleModFear (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 3041 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     target->SetControlled(apply, UNIT_STATE_FLEEING);
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_REAL, AuraApplication::GetTarget(), Unit::SetControlled(), and UNIT_STATE_FLEEING.
HandleModHealingDone()
void AuraEffect::HandleModHealingDone (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4107 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     // implemented in Unit::SpellHealingBonus
     // this information is for client side only
     target->ToPlayer()->UpdateSpellDamageAndHealingBonus();
 }
References AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, AuraApplication::GetTarget(), Object::GetTypeId(), Object::ToPlayer(), TYPEID_PLAYER, and Player::UpdateSpellDamageAndHealingBonus().
HandleModHitChance()
void AuraEffect::HandleModHitChance (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4458 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() == TYPEID_PLAYER)
     {
         target->ToPlayer()->UpdateMeleeHitChances();
         target->ToPlayer()->UpdateRangedHitChances();
     }
     else
     {
         target->m_modMeleeHitChance += (apply) ? GetAmount() : (-GetAmount());
         target->m_modRangedHitChance += (apply) ? GetAmount() : (-GetAmount());
     }
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, GetAmount(), AuraApplication::GetTarget(), Object::GetTypeId(), Unit::m_modMeleeHitChance, Unit::m_modRangedHitChance, Object::ToPlayer(), TYPEID_PLAYER, Player::UpdateMeleeHitChances(), and Player::UpdateRangedHitChances().
HandleModInvisibility()
void AuraEffect::HandleModInvisibility (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 1515 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_CHANGE_AMOUNT_SEND_FOR_CLIENT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     InvisibilityType type = InvisibilityType(GetMiscValue());
     if (apply)
     {
         // apply glow vision
         if (target->GetTypeId() == TYPEID_PLAYER && type == INVISIBILITY_GENERAL)
             target->SetByteFlag(PLAYER_FIELD_BYTES2, PLAYER_FIELD_BYTES_2_OFFSET_AURA_VISION, PLAYER_FIELD_BYTE2_INVISIBILITY_GLOW);
         target->m_invisibility.AddFlag(type);
         target->m_invisibility.AddValue(type, GetAmount());
     }
     else
     {
         if (!target->HasAuraType(SPELL_AURA_MOD_INVISIBILITY))
         {
             // if not have different invisibility auras.
             // always remove glow vision
             if (target->GetTypeId() == TYPEID_PLAYER)
                 target->RemoveByteFlag(PLAYER_FIELD_BYTES2, 3, PLAYER_FIELD_BYTE2_INVISIBILITY_GLOW);
             target->m_invisibility.DelFlag(type);
         }
         else
         {
             bool found = false;
             Unit::AuraEffectList const& invisAuras = target->GetAuraEffectsByType(SPELL_AURA_MOD_INVISIBILITY);
             for (Unit::AuraEffectList::const_iterator i = invisAuras.begin(); i != invisAuras.end(); ++i)
             {
                 if (GetMiscValue() == (*i)->GetMiscValue())
                 {
                     found = true;
                     break;
                 }
             }
             if (!found)
             {
                 // if not have invisibility auras of type INVISIBILITY_GENERAL
                 // remove glow vision
                 if (target->GetTypeId() == TYPEID_PLAYER && type == INVISIBILITY_GENERAL)
                 {
                     target->RemoveByteFlag(PLAYER_FIELD_BYTES2, PLAYER_FIELD_BYTES_2_OFFSET_AURA_VISION, PLAYER_FIELD_BYTE2_INVISIBILITY_GLOW);
                 }
                 target->m_invisibility.DelFlag(type);
             }
         }
         target->m_invisibility.AddValue(type, -GetAmount());
     }
     // call functions which may have additional effects after chainging state of unit
     if (apply && (mode & AURA_EFFECT_HANDLE_REAL))
     {
         // drop flag at invisibiliy in bg
         target->RemoveAurasWithInterruptFlags(AURA_INTERRUPT_FLAG_IMMUNE_OR_LOST_SELECTION);
     }
     target->UpdateObjectVisibility(target->GetTypeId() == TYPEID_PLAYER || target->GetOwnerGUID().IsPlayer() || target->GetMap()->Instanceable(), true);
     target->bRequestForcedVisibilityUpdate = false;
 }
References FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::AddFlag(), FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::AddValue(), ByteConverter::apply(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_SEND_FOR_CLIENT_MASK, AURA_EFFECT_HANDLE_REAL, AURA_INTERRUPT_FLAG_IMMUNE_OR_LOST_SELECTION, Unit::bRequestForcedVisibilityUpdate, FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::DelFlag(), GetAmount(), Unit::GetAuraEffectsByType(), WorldObject::GetMap(), GetMiscValue(), Unit::GetOwnerGUID(), AuraApplication::GetTarget(), Object::GetTypeId(), Unit::HasAuraType(), Map::Instanceable(), INVISIBILITY_GENERAL, ObjectGuid::IsPlayer(), WorldObject::m_invisibility, PLAYER_FIELD_BYTE2_INVISIBILITY_GLOW, PLAYER_FIELD_BYTES2, PLAYER_FIELD_BYTES_2_OFFSET_AURA_VISION, Unit::RemoveAurasWithInterruptFlags(), Object::RemoveByteFlag(), Object::SetByteFlag(), SPELL_AURA_MOD_INVISIBILITY, TYPEID_PLAYER, and Unit::UpdateObjectVisibility().
HandleModInvisibilityDetect()
void AuraEffect::HandleModInvisibilityDetect (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 1490 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     InvisibilityType type = InvisibilityType(GetMiscValue());
     if (apply)
     {
         target->m_invisibilityDetect.AddFlag(type);
         target->m_invisibilityDetect.AddValue(type, GetAmount());
     }
     else
     {
         if (!target->HasAuraType(SPELL_AURA_MOD_INVISIBILITY_DETECT))
             target->m_invisibilityDetect.DelFlag(type);
         target->m_invisibilityDetect.AddValue(type, -GetAmount());
     }
     // call functions which may have additional effects after chainging state of unit
     target->UpdateObjectVisibility(target->GetTypeId() == TYPEID_PLAYER || target->GetOwnerGUID().IsPlayer());
 }
References FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::AddFlag(), FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::AddValue(), ByteConverter::apply(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::DelFlag(), GetAmount(), GetMiscValue(), Unit::GetOwnerGUID(), AuraApplication::GetTarget(), Object::GetTypeId(), Unit::HasAuraType(), ObjectGuid::IsPlayer(), WorldObject::m_invisibilityDetect, SPELL_AURA_MOD_INVISIBILITY_DETECT, TYPEID_PLAYER, and Unit::UpdateObjectVisibility().
HandleModManaRegen()
void AuraEffect::HandleModManaRegen (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4241 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     //Note: an increase in regen does NOT cause threat.
     target->ToPlayer()->UpdateManaRegen();
 }
References AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, AuraApplication::GetTarget(), Object::GetTypeId(), Object::ToPlayer(), TYPEID_PLAYER, and Player::UpdateManaRegen().
Referenced by HandleAuraModRegenInterrupt().
HandleModMechanicImmunity()
void AuraEffect::HandleModMechanicImmunity (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 3677 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     uint32 mechanic = 0;
     switch (GetId())
     {
         case 46924: // BladeStorm
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_STUN, apply);
             break;
         case 34471: // The Beast Within
         case 19574: // Bestial Wrath
             mechanic = IMMUNE_TO_MOVEMENT_IMPAIRMENT_AND_LOSS_CONTROL_MASK;
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_CHARM, apply);
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_DISORIENTED, apply);
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_FEAR, apply);
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_ROOT, apply);
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_SLEEP, apply);
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_SNARE, apply);
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_STUN, apply);
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_FREEZE, apply);
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_KNOCKOUT, apply);
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_POLYMORPH, apply);
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_BANISH, apply);
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_SHACKLE, apply);
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_TURN, apply);
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_HORROR, apply);
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_DAZE, apply);
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_SAPPED, apply);
             break;
         case 42292: // PvP trinket
         case 59752: // Every Man for Himself
         case 65547: // PvP trinket for Faction Champions (ToC 25)
         case 53490: // Bullheaded
         case 46227: // Medalion of Immunity
             mechanic = IMMUNE_TO_MOVEMENT_IMPAIRMENT_AND_LOSS_CONTROL_MASK;
             target->RemoveAurasByType(SPELL_AURA_PREVENTS_FLEEING); // xinef: Patch 2.3.0 PvP Trinkets: Insignia of the Alliance, Insignia of the Horde, Medallion of the Alliance, and Medallion of the Horde now clear the debuff from Judgement of Justice.
             // Actually we should apply immunities here, too, but the aura has only 100 ms duration, so there is practically no point
             break;
         case 54508: // Demonic Empowerment
             mechanic = (1 << MECHANIC_SNARE) | (1 << MECHANIC_ROOT);
             target->RemoveAurasByType(SPELL_AURA_MOD_STUN);
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_SNARE, apply);
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_ROOT, apply);
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_STUN, apply);
             break;
         default:
             if (GetMiscValue() < 1)
                 return;
             mechanic = 1 << GetMiscValue();
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, GetMiscValue(), apply);
             break;
     }
     if (apply && GetSpellInfo()->HasAttribute(SPELL_ATTR1_IMMUNITY_PURGES_EFFECT))
     {
         // Xinef: exception for purely snare mechanic (eg. hands of freedom)!
         if (mechanic == (1 << MECHANIC_SNARE))
             target->RemoveMovementImpairingAuras(false);
         else
             target->RemoveAurasWithMechanic(mechanic, AURA_REMOVE_BY_DEFAULT, GetId());
     }
 }
References ByteConverter::apply(), Unit::ApplySpellImmune(), AURA_EFFECT_HANDLE_REAL, AURA_REMOVE_BY_DEFAULT, GetId(), GetMiscValue(), GetSpellInfo(), AuraApplication::GetTarget(), IMMUNE_TO_MOVEMENT_IMPAIRMENT_AND_LOSS_CONTROL_MASK, IMMUNITY_MECHANIC, MECHANIC_BANISH, MECHANIC_CHARM, MECHANIC_DAZE, MECHANIC_DISORIENTED, MECHANIC_FEAR, MECHANIC_FREEZE, MECHANIC_HORROR, MECHANIC_KNOCKOUT, MECHANIC_POLYMORPH, MECHANIC_ROOT, MECHANIC_SAPPED, MECHANIC_SHACKLE, MECHANIC_SLEEP, MECHANIC_SNARE, MECHANIC_STUN, MECHANIC_TURN, Unit::RemoveAurasByType(), Unit::RemoveAurasWithMechanic(), Unit::RemoveMovementImpairingAuras(), SPELL_ATTR1_IMMUNITY_PURGES_EFFECT, SPELL_AURA_MOD_STUN, and SPELL_AURA_PREVENTS_FLEEING.
HandleModMeleeRangedSpeedPct()
void AuraEffect::HandleModMeleeRangedSpeedPct (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4560 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     target->ApplyAttackTimePercentMod(BASE_ATTACK, (float)GetAmount(), apply);
     target->ApplyAttackTimePercentMod(OFF_ATTACK, (float)GetAmount(), apply);
     target->ApplyAttackTimePercentMod(RANGED_ATTACK, (float)GetAmount(), apply);
 }
References ByteConverter::apply(), Unit::ApplyAttackTimePercentMod(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, BASE_ATTACK, GetAmount(), AuraApplication::GetTarget(), OFF_ATTACK, and RANGED_ATTACK.
HandleModMeleeSpeedPct()
void AuraEffect::HandleModMeleeSpeedPct (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4596 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     target->ApplyAttackTimePercentMod(BASE_ATTACK, float(GetAmount()), apply);
     target->ApplyAttackTimePercentMod(OFF_ATTACK,  float(GetAmount()), apply);
 }
References ByteConverter::apply(), Unit::ApplyAttackTimePercentMod(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, BASE_ATTACK, GetAmount(), AuraApplication::GetTarget(), and OFF_ATTACK.
HandleModOffhandDamagePercent()
void AuraEffect::HandleModOffhandDamagePercent (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4867 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     target->HandleStatModifier(UNIT_MOD_DAMAGE_OFFHAND, TOTAL_PCT, float(GetAmount()), apply);
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, GetAmount(), AuraApplication::GetTarget(), Unit::HandleStatModifier(), TOTAL_PCT, and UNIT_MOD_DAMAGE_OFFHAND.
HandleModPercentStat()
void AuraEffect::HandleModPercentStat (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4023 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     if (GetMiscValue() < -1 || GetMiscValue() > 4)
     {
         LOG_ERROR("spells.aura.effect", "WARNING: Misc Value for SPELL_AURA_MOD_PERCENT_STAT not valid");
         return;
     }
     // only players have base stats
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     for (int32 i = STAT_STRENGTH; i < MAX_STATS; ++i)
     {
         if (GetMiscValue() == i || GetMiscValue() == -1)
             target->HandleStatModifier(UnitMods(UNIT_MOD_STAT_START + i), BASE_PCT, float(m_amount), apply);
     }
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, BASE_PCT, GetMiscValue(), AuraApplication::GetTarget(), Object::GetTypeId(), Unit::HandleStatModifier(), LOG_ERROR, m_amount, MAX_STATS, STAT_STRENGTH, TYPEID_PLAYER, and UNIT_MOD_STAT_START.
HandleModPossess()
void AuraEffect::HandleModPossess (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 3089 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     Unit* caster = GetCaster();
     // no support for posession AI yet
     if (caster && caster->GetTypeId() == TYPEID_UNIT)
     {
         HandleModCharm(aurApp, mode, apply);
         return;
     }
     if (apply)
         target->SetCharmedBy(caster, CHARM_TYPE_POSSESS, aurApp);
     else
         target->RemoveCharmedBy(caster);
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_REAL, CHARM_TYPE_POSSESS, GetCaster(), AuraApplication::GetTarget(), Object::GetTypeId(), HandleModCharm(), Unit::RemoveCharmedBy(), Unit::SetCharmedBy(), and TYPEID_UNIT.
HandleModPossessPet()
void AuraEffect::HandleModPossessPet (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 3111 of file SpellAuraEffects.cpp.
 {
     // Used by spell "Eyes of the Beast"
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* caster = GetCaster();
     if (!caster || caster->GetTypeId() != TYPEID_PLAYER)
         return;
     //seems it may happen that when removing it is no longer owner's pet
     //if (caster->ToPlayer()->GetPet() != target)
     //    return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_UNIT || !target->IsPet())
         return;
     Pet* pet = target->ToPet();
     if (apply)
     {
         if (caster->ToPlayer()->GetPet() != pet)
             return;
         // Must clear current motion or pet leashes back to owner after a few yards
         //  when under spell 'Eyes of the Beast'
         pet->GetMotionMaster()->Clear();
         pet->SetCharmedBy(caster, CHARM_TYPE_POSSESS, aurApp);
     }
     else
     {
         pet->RemoveCharmedBy(caster);
         if (!pet->IsWithinDistInMap(caster, pet->GetMap()->GetVisibilityRange()))
             pet->Remove(PET_SAVE_NOT_IN_SLOT, true);
         else
         {
             // Reinitialize the pet bar or it will appear greyed out
             caster->ToPlayer()->PetSpellInitialize();
             // Follow owner only if not fighting or owner didn't click "stay" at new location
             // This may be confusing because pet bar shows "stay" when under the spell but it retains
             //  the "follow" flag. Player MUST click "stay" while under the spell.
             if (!pet->GetVictim() && !pet->GetCharmInfo()->HasCommandState(COMMAND_STAY))
             {
                 pet->GetMotionMaster()->MoveFollow(caster, PET_FOLLOW_DIST, pet->GetFollowAngle());
             }
         }
     }
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_REAL, CHARM_TYPE_POSSESS, MotionMaster::Clear(), COMMAND_STAY, GetCaster(), Unit::GetCharmInfo(), Minion::GetFollowAngle(), WorldObject::GetMap(), Unit::GetMotionMaster(), Player::GetPet(), AuraApplication::GetTarget(), Object::GetTypeId(), Unit::GetVictim(), Map::GetVisibilityRange(), CharmInfo::HasCommandState(), Unit::IsPet(), WorldObject::IsWithinDistInMap(), MotionMaster::MoveFollow(), PET_FOLLOW_DIST, PET_SAVE_NOT_IN_SLOT, Player::PetSpellInitialize(), Pet::Remove(), Unit::RemoveCharmedBy(), Unit::SetCharmedBy(), Unit::ToPet(), Object::ToPlayer(), TYPEID_PLAYER, and TYPEID_UNIT.
HandleModPowerCost()
void AuraEffect::HandleModPowerCost (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4909 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     for (int i = 0; i < MAX_SPELL_SCHOOL; ++i)
         if (GetMiscValue() & (1 << i))
             target->ApplyModInt32Value(UNIT_FIELD_POWER_COST_MODIFIER + i, GetAmount(), apply);
 }
References ByteConverter::apply(), Object::ApplyModInt32Value(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, GetAmount(), GetMiscValue(), AuraApplication::GetTarget(), MAX_SPELL_SCHOOL, and UNIT_FIELD_POWER_COST_MODIFIER.
HandleModPowerCostPCT()
void AuraEffect::HandleModPowerCostPCT (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4896 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     float amount = CalculatePct(1.0f, GetAmount());
     for (int i = 0; i < MAX_SPELL_SCHOOL; ++i)
         if (GetMiscValue() & (1 << i))
             target->ApplyModSignedFloatValue(UNIT_FIELD_POWER_COST_MULTIPLIER + i, amount, apply);
 }
References ByteConverter::apply(), Object::ApplyModSignedFloatValue(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, CalculatePct(), GetAmount(), GetMiscValue(), AuraApplication::GetTarget(), MAX_SPELL_SCHOOL, and UNIT_FIELD_POWER_COST_MULTIPLIER.
HandleModPowerRegen()
void AuraEffect::HandleModPowerRegen (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4218 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     // Update manaregen value
     if (GetMiscValue() == POWER_MANA)
         target->ToPlayer()->UpdateManaRegen();
     else if (GetMiscValue() == POWER_RUNE)
         target->ToPlayer()->UpdateRuneRegen(RuneType(GetMiscValueB()));
     // other powers are not immediate effects - implemented in Player::Regenerate, Creature::Regenerate
 }
References AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, GetMiscValue(), GetMiscValueB(), AuraApplication::GetTarget(), Object::GetTypeId(), POWER_MANA, POWER_RUNE, Object::ToPlayer(), TYPEID_PLAYER, Player::UpdateManaRegen(), and Player::UpdateRuneRegen().
Referenced by HandleModPowerRegenPCT().
HandleModPowerRegenPCT()
void AuraEffect::HandleModPowerRegenPCT (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4236 of file SpellAuraEffects.cpp.
 {
     HandleModPowerRegen(aurApp, mode, apply);
 }
References ByteConverter::apply(), and HandleModPowerRegen().
HandleModRating()
void AuraEffect::HandleModRating (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4634 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     for (uint32 rating = 0; rating < MAX_COMBAT_RATING; ++rating)
         if (GetMiscValue() & (1 << rating))
             target->ToPlayer()->ApplyRatingMod(CombatRating(rating), GetAmount(), apply);
 }
References ByteConverter::apply(), Player::ApplyRatingMod(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, GetAmount(), GetMiscValue(), AuraApplication::GetTarget(), Object::GetTypeId(), MAX_COMBAT_RATING, Object::ToPlayer(), and TYPEID_PLAYER.
HandleModRatingFromStat()
void AuraEffect::HandleModRatingFromStat (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4649 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     // Just recalculate ratings
     for (uint32 rating = 0; rating < MAX_COMBAT_RATING; ++rating)
         if (GetMiscValue() & (1 << rating))
             target->ToPlayer()->ApplyRatingMod(CombatRating(rating), 0, apply);
 }
References ByteConverter::apply(), Player::ApplyRatingMod(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, GetMiscValue(), AuraApplication::GetTarget(), Object::GetTypeId(), MAX_COMBAT_RATING, Object::ToPlayer(), and TYPEID_PLAYER.
HandleModResistancePercent()
void AuraEffect::HandleModResistancePercent (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 3932 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     for (int8 i = SPELL_SCHOOL_NORMAL; i < MAX_SPELL_SCHOOL; i++)
     {
         if (GetMiscValue() & int32(1 << i))
         {
             target->HandleStatModifier(UnitMods(UNIT_MOD_RESISTANCE_START + i), TOTAL_PCT, float(GetAmount()), apply);
             if (target->GetTypeId() == TYPEID_PLAYER || target->IsPet())
             {
                 target->ApplyResistanceBuffModsPercentMod(SpellSchools(i), true, (float)GetAmount(), apply);
                 target->ApplyResistanceBuffModsPercentMod(SpellSchools(i), false, (float)GetAmount(), apply);
             }
         }
     }
 }
References ByteConverter::apply(), Unit::ApplyResistanceBuffModsPercentMod(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, GetAmount(), GetMiscValue(), AuraApplication::GetTarget(), Object::GetTypeId(), Unit::HandleStatModifier(), Unit::IsPet(), MAX_SPELL_SCHOOL, SPELL_SCHOOL_NORMAL, TOTAL_PCT, TYPEID_PLAYER, and UNIT_MOD_RESISTANCE_START.
HandleModSpellCritChance()
void AuraEffect::HandleModSpellCritChance (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4490 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() == TYPEID_PLAYER)
         target->ToPlayer()->UpdateAllSpellCritChances();
     else
         target->m_baseSpellCritChance += (apply) ? GetAmount() : -GetAmount();
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, GetAmount(), AuraApplication::GetTarget(), Object::GetTypeId(), Unit::m_baseSpellCritChance, Object::ToPlayer(), TYPEID_PLAYER, and Player::UpdateAllSpellCritChances().
HandleModSpellCritChanceShool()
void AuraEffect::HandleModSpellCritChanceShool (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4503 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     for (int school = SPELL_SCHOOL_NORMAL; school < MAX_SPELL_SCHOOL; ++school)
         if (GetMiscValue() & (1 << school))
             target->ToPlayer()->UpdateSpellCritChance(school);
 }
References AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, GetMiscValue(), AuraApplication::GetTarget(), Object::GetTypeId(), MAX_SPELL_SCHOOL, SPELL_SCHOOL_NORMAL, Object::ToPlayer(), TYPEID_PLAYER, and Player::UpdateSpellCritChance().
HandleModSpellDamagePercentFromAttackPower()
void AuraEffect::HandleModSpellDamagePercentFromAttackPower (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4077 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     // Magic damage modifiers implemented in Unit::SpellDamageBonus
     // This information for client side use only
     // Recalculate bonus
     target->ToPlayer()->UpdateSpellDamageAndHealingBonus();
 }
References AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, AuraApplication::GetTarget(), Object::GetTypeId(), Object::ToPlayer(), TYPEID_PLAYER, and Player::UpdateSpellDamageAndHealingBonus().
HandleModSpellDamagePercentFromStat()
void AuraEffect::HandleModSpellDamagePercentFromStat (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4047 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     // Magic damage modifiers implemented in Unit::SpellDamageBonus
     // This information for client side use only
     // Recalculate bonus
     target->ToPlayer()->UpdateSpellDamageAndHealingBonus();
 }
References AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, AuraApplication::GetTarget(), Object::GetTypeId(), Object::ToPlayer(), TYPEID_PLAYER, and Player::UpdateSpellDamageAndHealingBonus().
HandleModSpellHealingPercentFromAttackPower()
void AuraEffect::HandleModSpellHealingPercentFromAttackPower (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4093 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     // Recalculate bonus
     target->ToPlayer()->UpdateSpellDamageAndHealingBonus();
 }
References AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, AuraApplication::GetTarget(), Object::GetTypeId(), Object::ToPlayer(), TYPEID_PLAYER, and Player::UpdateSpellDamageAndHealingBonus().
HandleModSpellHealingPercentFromStat()
void AuraEffect::HandleModSpellHealingPercentFromStat (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4063 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     // Recalculate bonus
     target->ToPlayer()->UpdateSpellDamageAndHealingBonus();
 }
References AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, AuraApplication::GetTarget(), Object::GetTypeId(), Object::ToPlayer(), TYPEID_PLAYER, and Player::UpdateSpellDamageAndHealingBonus().
HandleModSpellHitChance()
void AuraEffect::HandleModSpellHitChance (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4477 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() == TYPEID_PLAYER)
         target->ToPlayer()->UpdateSpellHitChances();
     else
         target->m_modSpellHitChance += (apply) ? GetAmount() : (-GetAmount());
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, GetAmount(), AuraApplication::GetTarget(), Object::GetTypeId(), Unit::m_modSpellHitChance, Object::ToPlayer(), TYPEID_PLAYER, and Player::UpdateSpellHitChances().
HandleModStateImmunityMask()
void AuraEffect::HandleModStateImmunityMask (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 3357 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     std::list <AuraType> aura_immunity_list;
     uint32 mechanic_immunity_list = 0;
     int32 miscVal = GetMiscValue();
     switch (miscVal)
     {
         case 96:
         case 1615:
             {
                 if (!GetAmount())
                 {
                     mechanic_immunity_list = (1 << MECHANIC_SNARE) | (1 << MECHANIC_ROOT)
                                              | (1 << MECHANIC_FEAR) | (1 << MECHANIC_STUN)
                                              | (1 << MECHANIC_SLEEP) | (1 << MECHANIC_CHARM)
                                              | (1 << MECHANIC_SAPPED) | (1 << MECHANIC_HORROR)
                                              | (1 << MECHANIC_POLYMORPH) | (1 << MECHANIC_DISORIENTED)
                                              | (1 << MECHANIC_FREEZE) | (1 << MECHANIC_TURN);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_CHARM, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_SNARE, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_ROOT, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_FEAR, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_STUN, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_SLEEP, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_SAPPED, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_HORROR, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_POLYMORPH, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_DISORIENTED, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_FREEZE, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_TURN, apply);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_CHARM);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_STUN);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_DECREASE_SPEED);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_ROOT);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_CONFUSE);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_FEAR);
                 }
                 break;
             }
         case 679:
             {
                 if (GetId() == 57742)
                 {
                     mechanic_immunity_list = (1 << MECHANIC_SNARE) | (1 << MECHANIC_ROOT)
                                              | (1 << MECHANIC_FEAR) | (1 << MECHANIC_STUN)
                                              | (1 << MECHANIC_SLEEP) | (1 << MECHANIC_CHARM)
                                              | (1 << MECHANIC_SAPPED) | (1 << MECHANIC_HORROR)
                                              | (1 << MECHANIC_POLYMORPH) | (1 << MECHANIC_DISORIENTED)
                                              | (1 << MECHANIC_FREEZE) | (1 << MECHANIC_TURN);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_SNARE, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_ROOT, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_FEAR, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_STUN, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_SLEEP, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_CHARM, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_SAPPED, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_HORROR, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_POLYMORPH, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_DISORIENTED, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_FREEZE, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_TURN, apply);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_STUN);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_DECREASE_SPEED);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_ROOT);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_CONFUSE);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_FEAR);
                 }
                 break;
             }
         case 1557:
             {
                 if (GetId() == 64187)
                 {
                     mechanic_immunity_list = (1 << MECHANIC_STUN);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_STUN, apply);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_STUN);
                 }
                 else
                 {
                     mechanic_immunity_list = (1 << MECHANIC_SNARE) | (1 << MECHANIC_ROOT)
                                              | (1 << MECHANIC_FEAR) | (1 << MECHANIC_STUN)
                                              | (1 << MECHANIC_SLEEP) | (1 << MECHANIC_CHARM)
                                              | (1 << MECHANIC_SAPPED) | (1 << MECHANIC_HORROR)
                                              | (1 << MECHANIC_POLYMORPH) | (1 << MECHANIC_DISORIENTED)
                                              | (1 << MECHANIC_FREEZE) | (1 << MECHANIC_TURN);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_SNARE, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_ROOT, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_FEAR, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_STUN, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_SLEEP, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_CHARM, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_SAPPED, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_HORROR, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_POLYMORPH, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_DISORIENTED, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_FREEZE, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_TURN, apply);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_STUN);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_DECREASE_SPEED);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_ROOT);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_CONFUSE);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_FEAR);
                 }
                 break;
             }
         case 1614:
         case 1694:
             {
                 target->ApplySpellImmune(GetId(), IMMUNITY_EFFECT, SPELL_EFFECT_ATTACK_ME, apply);
                 aura_immunity_list.push_back(SPELL_AURA_MOD_TAUNT);
                 break;
             }
         case 1630:
             {
                 if (!GetAmount())
                 {
                     target->ApplySpellImmune(GetId(), IMMUNITY_EFFECT, SPELL_EFFECT_ATTACK_ME, apply);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_TAUNT);
                 }
                 else
                 {
                     mechanic_immunity_list = (1 << MECHANIC_SNARE) | (1 << MECHANIC_ROOT)
                                              | (1 << MECHANIC_FEAR) | (1 << MECHANIC_STUN)
                                              | (1 << MECHANIC_SLEEP) | (1 << MECHANIC_CHARM)
                                              | (1 << MECHANIC_SAPPED) | (1 << MECHANIC_HORROR)
                                              | (1 << MECHANIC_POLYMORPH) | (1 << MECHANIC_DISORIENTED)
                                              | (1 << MECHANIC_FREEZE) | (1 << MECHANIC_TURN);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_SNARE, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_ROOT, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_FEAR, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_STUN, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_SLEEP, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_CHARM, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_SAPPED, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_HORROR, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_POLYMORPH, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_DISORIENTED, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_FREEZE, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_TURN, apply);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_STUN);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_DECREASE_SPEED);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_ROOT);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_CONFUSE);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_FEAR);
                 }
                 break;
             }
         case 477:
         case 1733:
         case 1632:
             {
                 if (!GetAmount())
                 {
                     mechanic_immunity_list = (1 << MECHANIC_SNARE) | (1 << MECHANIC_ROOT)
                                              | (1 << MECHANIC_FEAR) | (1 << MECHANIC_STUN)
                                              | (1 << MECHANIC_SLEEP) | (1 << MECHANIC_CHARM)
                                              | (1 << MECHANIC_SAPPED) | (1 << MECHANIC_HORROR)
                                              | (1 << MECHANIC_POLYMORPH) | (1 << MECHANIC_DISORIENTED)
                                              | (1 << MECHANIC_FREEZE) | (1 << MECHANIC_TURN) | (1 << MECHANIC_BANISH);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_SNARE, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_ROOT, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_FEAR, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_STUN, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_SLEEP, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_CHARM, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_SAPPED, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_HORROR, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_POLYMORPH, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_DISORIENTED, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_FREEZE, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_TURN, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_BANISH, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_EFFECT, SPELL_EFFECT_KNOCK_BACK, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_EFFECT, SPELL_EFFECT_KNOCK_BACK_DEST, apply);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_STUN);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_DECREASE_SPEED);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_ROOT);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_CONFUSE);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_FEAR);
                 }
                 break;
             }
         case 878:
             {
                 if (GetAmount() == 1)
                 {
                     mechanic_immunity_list = (1 << MECHANIC_SNARE) | (1 << MECHANIC_STUN)
                                              | (1 << MECHANIC_DISORIENTED) | (1 << MECHANIC_FREEZE);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_SNARE, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_STUN, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_DISORIENTED, apply);
                     target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_FREEZE, apply);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_STUN);
                     aura_immunity_list.push_back(SPELL_AURA_MOD_DECREASE_SPEED);
                 }
                 break;
             }
         default:
             break;
     }
     if (aura_immunity_list.empty())
     {
         // Roots, OK
         if (GetMiscValue() & (1 << 0))
         {
             mechanic_immunity_list = (1 << MECHANIC_SNARE);
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_SNARE, apply);
             aura_immunity_list.push_back(SPELL_AURA_MOD_ROOT);
         }
         // Taunt, OK
         if (GetMiscValue() & (1 << 1))
         {
             aura_immunity_list.push_back(SPELL_AURA_MOD_TAUNT);
         }
         // Crowd-Control auras?
         if (GetMiscValue() & (1 << 2))
         {
             mechanic_immunity_list = (1 << MECHANIC_POLYMORPH) | (1 << MECHANIC_DISORIENTED);
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_POLYMORPH, apply);
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_DISORIENTED, apply);
             aura_immunity_list.push_back(SPELL_AURA_MOD_CONFUSE);
         }
         // Interrupt, OK
         if (GetMiscValue() & (1 << 3))
         {
             mechanic_immunity_list = (1 << MECHANIC_INTERRUPT);
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_INTERRUPT, apply);
         }
         // Transform?
         if (GetMiscValue() & (1 << 4))
         {
             aura_immunity_list.push_back(SPELL_AURA_TRANSFORM);
         }
         // Stun auras breakable by damage (Incapacitate effects), OK
         if (GetMiscValue() & (1 << 5))
         {
             mechanic_immunity_list = (1 << MECHANIC_KNOCKOUT);
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_KNOCKOUT, apply);
         }
         // // Slowing effects
         if (GetMiscValue() & (1 << 6))
         {
             mechanic_immunity_list = (1 << MECHANIC_SNARE);
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_SNARE, apply);
             aura_immunity_list.push_back(SPELL_AURA_MOD_DECREASE_SPEED);
         }
         // Charm auras?, 90%
         if ((GetMiscValue() & (1 << 7)))
         {
             mechanic_immunity_list = (1 << MECHANIC_CHARM);
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_CHARM, apply);
             aura_immunity_list.push_back(SPELL_AURA_MOD_CHARM);
             aura_immunity_list.push_back(SPELL_AURA_MOD_POSSESS);
         }
         // UNK
         // if ((GetMiscValue() & (1 << 8)))
         // {
         // }
         // Fear, OK
         if (GetMiscValue() & (1 << 9))
         {
             mechanic_immunity_list = (1 << MECHANIC_FEAR);
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_FEAR, apply);
             aura_immunity_list.push_back(SPELL_AURA_MOD_FEAR);
         }
         // Stuns, OK
         if (GetMiscValue() & (1 << 10))
         {
             mechanic_immunity_list = (1 << MECHANIC_STUN);
             target->ApplySpellImmune(GetId(), IMMUNITY_MECHANIC, MECHANIC_STUN, apply);
             aura_immunity_list.push_back(SPELL_AURA_MOD_STUN);
         }
     }
     // apply immunities
     for (std::list <AuraType>::iterator iter = aura_immunity_list.begin(); iter != aura_immunity_list.end(); ++iter)
         target->ApplySpellImmune(GetId(), IMMUNITY_STATE, *iter, apply);
     // Patch 3.0.3 Bladestorm now breaks all snares and roots on the warrior when activated.
     if (GetId() == 46924)
     {
         if (apply)
         {
             target->resetAttackTimer();
             target->resetAttackTimer(OFF_ATTACK);
         }
         // Knockback and hex
         target->ApplySpellImmune(GetId(), IMMUNITY_EFFECT, SPELL_EFFECT_KNOCK_BACK, apply);
     }
     if (apply && GetSpellInfo()->HasAttribute(SPELL_ATTR1_IMMUNITY_PURGES_EFFECT))
     {
         target->RemoveAurasWithMechanic(mechanic_immunity_list, AURA_REMOVE_BY_DEFAULT, GetId());
         for (std::list <AuraType>::iterator iter = aura_immunity_list.begin(); iter != aura_immunity_list.end(); ++iter)
             target->RemoveAurasByType(*iter);
     }
 }
References ByteConverter::apply(), Unit::ApplySpellImmune(), AURA_EFFECT_HANDLE_REAL, AURA_REMOVE_BY_DEFAULT, GetAmount(), GetId(), GetMiscValue(), GetSpellInfo(), AuraApplication::GetTarget(), SpellInfo::HasAttribute(), IMMUNITY_EFFECT, IMMUNITY_MECHANIC, IMMUNITY_STATE, MECHANIC_BANISH, MECHANIC_CHARM, MECHANIC_DISORIENTED, MECHANIC_FEAR, MECHANIC_FREEZE, MECHANIC_HORROR, MECHANIC_INTERRUPT, MECHANIC_KNOCKOUT, MECHANIC_POLYMORPH, MECHANIC_ROOT, MECHANIC_SAPPED, MECHANIC_SLEEP, MECHANIC_SNARE, MECHANIC_STUN, MECHANIC_TURN, OFF_ATTACK, Unit::RemoveAurasByType(), Unit::RemoveAurasWithMechanic(), Unit::resetAttackTimer(), SPELL_ATTR1_IMMUNITY_PURGES_EFFECT, SPELL_AURA_MOD_CHARM, SPELL_AURA_MOD_CONFUSE, SPELL_AURA_MOD_DECREASE_SPEED, SPELL_AURA_MOD_FEAR, SPELL_AURA_MOD_POSSESS, SPELL_AURA_MOD_ROOT, SPELL_AURA_MOD_STUN, SPELL_AURA_MOD_TAUNT, SPELL_AURA_TRANSFORM, SPELL_EFFECT_ATTACK_ME, SPELL_EFFECT_KNOCK_BACK, and SPELL_EFFECT_KNOCK_BACK_DEST.
HandleModStealth()
void AuraEffect::HandleModStealth (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 1607 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_CHANGE_AMOUNT_SEND_FOR_CLIENT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     StealthType type = StealthType(GetMiscValue());
     if (apply)
     {
         target->m_stealth.AddFlag(type);
         target->m_stealth.AddValue(type, GetAmount());
         target->SetStandFlags(UNIT_STAND_FLAGS_CREEP);
         if (target->GetTypeId() == TYPEID_PLAYER)
             target->SetByteFlag(PLAYER_FIELD_BYTES2, 3, PLAYER_FIELD_BYTE2_STEALTH);
         // interrupt autoshot
         if (target->GetCurrentSpell(CURRENT_AUTOREPEAT_SPELL))
         {
             target->FinishSpell(CURRENT_AUTOREPEAT_SPELL);
             target->ToPlayer()->SendAutoRepeatCancel(target);
         }
     }
     else
     {
         target->m_stealth.AddValue(type, -GetAmount());
         if (!target->HasAuraType(SPELL_AURA_MOD_STEALTH)) // if last SPELL_AURA_MOD_STEALTH
         {
             target->m_stealth.DelFlag(type);
             target->RemoveStandFlags(UNIT_STAND_FLAGS_CREEP);
             if (target->GetTypeId() == TYPEID_PLAYER)
                 target->RemoveByteFlag(PLAYER_FIELD_BYTES2, 3, PLAYER_FIELD_BYTE2_STEALTH);
         }
     }
     // call functions which may have additional effects after chainging state of unit
     if (apply && (mode & AURA_EFFECT_HANDLE_REAL))
     {
         // drop flag at stealth in bg
         target->RemoveAurasWithInterruptFlags(AURA_INTERRUPT_FLAG_IMMUNE_OR_LOST_SELECTION);
     }
     target->UpdateObjectVisibility(target->GetTypeId() == TYPEID_PLAYER || target->GetOwnerGUID().IsPlayer() || target->GetMap()->Instanceable(), true);
     target->bRequestForcedVisibilityUpdate = false;
 }
References FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::AddFlag(), FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::AddValue(), ByteConverter::apply(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_SEND_FOR_CLIENT_MASK, AURA_EFFECT_HANDLE_REAL, AURA_INTERRUPT_FLAG_IMMUNE_OR_LOST_SELECTION, Unit::bRequestForcedVisibilityUpdate, CURRENT_AUTOREPEAT_SPELL, FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::DelFlag(), Unit::FinishSpell(), GetAmount(), Unit::GetCurrentSpell(), WorldObject::GetMap(), GetMiscValue(), Unit::GetOwnerGUID(), AuraApplication::GetTarget(), Object::GetTypeId(), Unit::HasAuraType(), Map::Instanceable(), ObjectGuid::IsPlayer(), WorldObject::m_stealth, PLAYER_FIELD_BYTE2_STEALTH, PLAYER_FIELD_BYTES2, Unit::RemoveAurasWithInterruptFlags(), Object::RemoveByteFlag(), Unit::RemoveStandFlags(), Player::SendAutoRepeatCancel(), Object::SetByteFlag(), Unit::SetStandFlags(), SPELL_AURA_MOD_STEALTH, Object::ToPlayer(), TYPEID_PLAYER, UNIT_STAND_FLAGS_CREEP, and Unit::UpdateObjectVisibility().
HandleModStealthDetect()
void AuraEffect::HandleModStealthDetect (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 1582 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     StealthType type = StealthType(GetMiscValue());
     if (apply)
     {
         target->m_stealthDetect.AddFlag(type);
         target->m_stealthDetect.AddValue(type, GetAmount());
     }
     else
     {
         if (!target->HasAuraType(SPELL_AURA_MOD_STEALTH_DETECT))
             target->m_stealthDetect.DelFlag(type);
         target->m_stealthDetect.AddValue(type, -GetAmount());
     }
     // call functions which may have additional effects after chainging state of unit
     target->UpdateObjectVisibility(target->GetTypeId() == TYPEID_PLAYER || target->GetOwnerGUID().IsPlayer());
 }
References FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::AddFlag(), FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::AddValue(), ByteConverter::apply(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::DelFlag(), GetAmount(), GetMiscValue(), Unit::GetOwnerGUID(), AuraApplication::GetTarget(), Object::GetTypeId(), Unit::HasAuraType(), ObjectGuid::IsPlayer(), WorldObject::m_stealthDetect, SPELL_AURA_MOD_STEALTH_DETECT, TYPEID_PLAYER, and Unit::UpdateObjectVisibility().
HandleModStealthLevel()
void AuraEffect::HandleModStealthLevel (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 1656 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     StealthType type = StealthType(GetMiscValue());
     if (apply)
         target->m_stealth.AddValue(type, GetAmount());
     else
         target->m_stealth.AddValue(type, -GetAmount());
     // call functions which may have additional effects after chainging state of unit
     target->UpdateObjectVisibility(target->GetTypeId() == TYPEID_PLAYER || target->GetOwnerGUID().IsPlayer());
 }
References FlaggedValuesArray32< T_VALUES, T_FLAGS, FLAG_TYPE, ARRAY_SIZE >::AddValue(), ByteConverter::apply(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, GetAmount(), GetMiscValue(), Unit::GetOwnerGUID(), AuraApplication::GetTarget(), Object::GetTypeId(), ObjectGuid::IsPlayer(), WorldObject::m_stealth, TYPEID_PLAYER, and Unit::UpdateObjectVisibility().
HandleModTargetResistance()
void AuraEffect::HandleModTargetResistance (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 3975 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     // applied to damage as HandleNoImmediateEffect in Unit::CalcAbsorbResist and Unit::CalcArmorReducedDamage
     // show armor penetration
     if (target->GetTypeId() == TYPEID_PLAYER && (GetMiscValue() & SPELL_SCHOOL_MASK_NORMAL))
         target->ApplyModInt32Value(PLAYER_FIELD_MOD_TARGET_PHYSICAL_RESISTANCE, GetAmount(), apply);
     // show as spell penetration only full spell penetration bonuses (all resistances except armor and holy
     if (target->GetTypeId() == TYPEID_PLAYER && (GetMiscValue() & SPELL_SCHOOL_MASK_SPELL) == SPELL_SCHOOL_MASK_SPELL)
         target->ApplyModInt32Value(PLAYER_FIELD_MOD_TARGET_RESISTANCE, GetAmount(), apply);
 }
References ByteConverter::apply(), Object::ApplyModInt32Value(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, GetAmount(), GetMiscValue(), AuraApplication::GetTarget(), Object::GetTypeId(), PLAYER_FIELD_MOD_TARGET_PHYSICAL_RESISTANCE, PLAYER_FIELD_MOD_TARGET_RESISTANCE, SPELL_SCHOOL_MASK_NORMAL, SPELL_SCHOOL_MASK_SPELL, and TYPEID_PLAYER.
HandleModTaunt()
void AuraEffect::HandleModTaunt (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 3004 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     if (!target->IsAlive() || !target->CanHaveThreatList())
         return;
     Unit* caster = GetCaster();
     if (!caster || !caster->IsAlive())
         return;
     if (apply)
         target->TauntApply(caster);
     else
     {
         // When taunt aura fades out, mob will switch to previous target if current has less than 1.1 * secondthreat
         target->TauntFadeOut(caster);
     }
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_REAL, Unit::CanHaveThreatList(), GetCaster(), AuraApplication::GetTarget(), Unit::IsAlive(), Unit::TauntApply(), and Unit::TauntFadeOut().
HandleModThreat()
void AuraEffect::HandleModThreat (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 2978 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     for (int8 i = 0; i < MAX_SPELL_SCHOOL; ++i)
         if (GetMiscValue() & (1 << i))
             ApplyPercentModFloatVar(target->m_threatModifier[i], float(GetAmount()), apply);
 }
References ByteConverter::apply(), ApplyPercentModFloatVar(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, GetAmount(), GetMiscValue(), AuraApplication::GetTarget(), Unit::m_threatModifier, and MAX_SPELL_SCHOOL.
HandleModTotalPercentStat()
void AuraEffect::HandleModTotalPercentStat (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4121 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     if (GetMiscValue() < -1 || GetMiscValue() > 4)
     {
         LOG_ERROR("spells.aura.effect", "WARNING: Misc Value for SPELL_AURA_MOD_PERCENT_STAT not valid");
         return;
     }
     // save current health state
     float healthPct = target->GetHealthPct();
     bool alive = target->IsAlive();
     float value = GetAmount();
     if (GetId() == 67480) // xinef: hack fix for blessing of sanctuary stats stack with blessing of kings...
     {
         if (value) // not turned off
             value = 10.0f;
         for (int32 i = STAT_STRENGTH; i < MAX_STATS; i++)
         {
             if (i == STAT_STRENGTH || i == STAT_STAMINA)
             {
                 if (apply && (target->GetTypeId() == TYPEID_PLAYER || target->IsPet()))
                     target->ApplyStatPercentBuffMod(Stats(i), value, apply);
                 target->HandleStatModifier(UnitMods(UNIT_MOD_STAT_START + i), TOTAL_PCT, value, apply);
                 if (!apply && (target->GetTypeId() == TYPEID_PLAYER || target->IsPet()))
                     target->ApplyStatPercentBuffMod(Stats(i), value, apply);
             }
         }
         return;
     }
     for (int32 i = STAT_STRENGTH; i < MAX_STATS; i++)
     {
         if (GetMiscValue() == i || GetMiscValue() == -1)
         {
             if (apply && (target->GetTypeId() == TYPEID_PLAYER || target->IsPet()))
                 target->ApplyStatPercentBuffMod(Stats(i), value, apply);
             target->HandleStatModifier(UnitMods(UNIT_MOD_STAT_START + i), TOTAL_PCT, value, apply);
             if (!apply && (target->GetTypeId() == TYPEID_PLAYER || target->IsPet()))
                 target->ApplyStatPercentBuffMod(Stats(i), value, apply);
         }
     }
     // recalculate current HP/MP after applying aura modifications (only for spells with SPELL_ATTR0_UNK4 0x00000010 flag)
     // this check is total bullshit i think
     if (GetMiscValue() == STAT_STAMINA && m_spellInfo->HasAttribute(SPELL_ATTR0_IS_ABILITY))
         target->SetHealth(std::max<uint32>(uint32(healthPct * target->GetMaxHealth() * 0.01f), (alive ? 1 : 0)));
 }
References ByteConverter::apply(), Unit::ApplyStatPercentBuffMod(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, GetAmount(), Unit::GetHealthPct(), GetId(), Unit::GetMaxHealth(), GetMiscValue(), AuraApplication::GetTarget(), Object::GetTypeId(), Unit::HandleStatModifier(), SpellInfo::HasAttribute(), Unit::IsAlive(), Unit::IsPet(), LOG_ERROR, m_spellInfo, MAX_STATS, Unit::SetHealth(), SPELL_ATTR0_IS_ABILITY, STAT_STAMINA, STAT_STRENGTH, TOTAL_PCT, TYPEID_PLAYER, and UNIT_MOD_STAT_START.
HandleModUnattackable()
void AuraEffect::HandleModUnattackable (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 2495 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     // do not remove unit flag if there are more than this auraEffect of that kind on unit on unit
     if (!apply && target->HasAuraType(SPELL_AURA_MOD_UNATTACKABLE))
         return;
     target->ApplyModFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, apply);
     // call functions which may have additional effects after chainging state of unit
     if (apply && (mode & AURA_EFFECT_HANDLE_REAL))
     {
         // xinef: this aura should not stop combat (movie with sindragosa proves that)
         //target->CombatStop();
         target->RemoveAurasWithInterruptFlags(AURA_INTERRUPT_FLAG_IMMUNE_OR_LOST_SELECTION);
     }
 }
References ByteConverter::apply(), Object::ApplyModFlag(), AURA_EFFECT_HANDLE_REAL, AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK, AURA_INTERRUPT_FLAG_IMMUNE_OR_LOST_SELECTION, AuraApplication::GetTarget(), Unit::HasAuraType(), Unit::RemoveAurasWithInterruptFlags(), SPELL_AURA_MOD_UNATTACKABLE, UNIT_FIELD_FLAGS, and UNIT_FLAG_NON_ATTACKABLE.
HandleNoImmediateEffect()
void AuraEffect::HandleNoImmediateEffect (AuraApplication const * , uint8 , bool) const inline
Definition at line 153 of file SpellAuraEffects.h.
     {
         // aura type not have immediate effect at add/remove and handled by ID in other code place
     }
HandleNoReagentUseAura()
void AuraEffect::HandleNoReagentUseAura (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4939 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     flag96 mask;
     Unit::AuraEffectList const& noReagent = target->GetAuraEffectsByType(SPELL_AURA_NO_REAGENT_USE);
     for (Unit::AuraEffectList::const_iterator i = noReagent.begin(); i != noReagent.end(); ++i)
         mask |= (*i)->m_spellInfo->Effects[(*i)->m_effIndex].SpellClassMask;
     target->SetUInt32Value(PLAYER_NO_REAGENT_COST_1, mask[0]);
     target->SetUInt32Value(PLAYER_NO_REAGENT_COST_1 + 1, mask[1]);
     target->SetUInt32Value(PLAYER_NO_REAGENT_COST_1 + 2, mask[2]);
 }
References AURA_EFFECT_HANDLE_REAL, Unit::GetAuraEffectsByType(), AuraApplication::GetTarget(), Object::GetTypeId(), PLAYER_NO_REAGENT_COST_1, Object::SetUInt32Value(), SPELL_AURA_NO_REAGENT_USE, and TYPEID_PLAYER.
HandleNULL()
void AuraEffect::HandleNULL (AuraApplication const * , uint8 , bool) const inline
Definition at line 145 of file SpellAuraEffects.h.
     {
         // not implemented
     }
HandleObsModPowerAuraTick()
void AuraEffect::HandleObsModPowerAuraTick (Unit * target, Unit * caster) const
Definition at line 6669 of file SpellAuraEffects.cpp.
 {
     Powers PowerType;
     if (GetMiscValue() == POWER_ALL)
         PowerType = target->getPowerType();
     else
         PowerType = Powers(GetMiscValue());
     if (!target->IsAlive() || !target->GetMaxPower(PowerType))
         return;
     if (target->HasUnitState(UNIT_STATE_ISOLATED))
     {
         SendTickImmune(target, caster);
         return;
     }
     // don't regen when permanent aura target has full power
     if (GetBase()->IsPermanent() && target->GetPower(PowerType) == target->GetMaxPower(PowerType))
         return;
     // ignore negative values (can be result apply spellmods to aura damage
     uint32 amount = std::max(m_amount, 0) * target->GetMaxPower(PowerType) / 100;
     LOG_DEBUG("spells.aura.effect", "PeriodicTick: %s energize %s for %u dmg inflicted by %u",
                     GetCasterGUID().ToString().c_str(), target->GetGUID().ToString().c_str(), amount, GetId());
     SpellPeriodicAuraLogInfo pInfo(this, amount, 0, 0, 0, 0.0f, false);
     target->SendPeriodicAuraLog(&pInfo);
     int32 gain = target->ModifyPower(PowerType, amount);
     if (caster)
         target->getHostileRefMgr().threatAssist(caster, float(gain) * 0.5f, GetSpellInfo());
 }
References GetBase(), GetCasterGUID(), Object::GetGUID(), Unit::getHostileRefMgr(), GetId(), Unit::GetMaxPower(), GetMiscValue(), Unit::GetPower(), Unit::getPowerType(), GetSpellInfo(), Unit::HasUnitState(), Unit::IsAlive(), Aura::IsPermanent(), LOG_DEBUG, m_amount, max, Unit::ModifyPower(), POWER_ALL, Unit::SendPeriodicAuraLog(), SendTickImmune(), HostileRefMgr::threatAssist(), ObjectGuid::ToString(), Acore::ToString(), and UNIT_STATE_ISOLATED.
Referenced by PeriodicTick().
HandlePeriodicDamageAurasTick()
void AuraEffect::HandlePeriodicDamageAurasTick (Unit * target, Unit * caster) const
Definition at line 6190 of file SpellAuraEffects.cpp.
 {
     if (!target->IsAlive())
         return;
     if (target->HasUnitState(UNIT_STATE_ISOLATED) || target->IsImmunedToDamageOrSchool(GetSpellInfo()) || target->IsTotem())
     {
         SendTickImmune(target, caster);
         return;
     }
     // Consecrate ticks can miss and will not show up in the combat log
     if (caster && GetSpellInfo()->Effects[GetEffIndex()].Effect == SPELL_EFFECT_PERSISTENT_AREA_AURA &&
             caster->SpellHitResult(target, GetSpellInfo(), false) != SPELL_MISS_NONE)
         return;
     // some auras remove at specific health level or more
     if (GetAuraType() == SPELL_AURA_PERIODIC_DAMAGE)
     {
         switch (GetSpellInfo()->Id)
         {
             case 43093:
             case 31956:
             case 38801:  // Grievous Wound
             case 35321:
             case 38363:
             case 39215:  // Gushing Wound
                 if (target->IsFullHealth())
                 {
                     target->RemoveAurasDueToSpell(GetSpellInfo()->Id);
                     return;
                 }
                 break;
             case 38772: // Grievous Wound
                 {
                     uint32 percent = GetSpellInfo()->Effects[EFFECT_1].CalcValue(caster);
                     if (!target->HealthBelowPct(percent))
                     {
                         target->RemoveAurasDueToSpell(GetSpellInfo()->Id);
                         return;
                     }
                     break;
                 }
         }
     }
     CleanDamage cleanDamage = CleanDamage(0, 0, BASE_ATTACK, MELEE_HIT_NORMAL);
     // ignore non positive values (can be result apply spellmods to aura damage
     uint32 damage = std::max(GetAmount(), 0);
     // Script Hook For HandlePeriodicDamageAurasTick -- Allow scripts to change the Damage pre class mitigation calculations
     sScriptMgr->ModifyPeriodicDamageAurasTick(target, caster, damage);
     if (GetAuraType() == SPELL_AURA_PERIODIC_DAMAGE)
     {
         // xinef: leave only target depending bonuses, rest is handled in calculate amount
         if (GetBase()->GetType() == DYNOBJ_AURA_TYPE && caster)
             damage = caster->SpellDamageBonusDone(target, GetSpellInfo(), damage, DOT, 0.0f, GetBase()->GetStackAmount());
         damage = target->SpellDamageBonusTaken(caster, GetSpellInfo(), damage, DOT, GetBase()->GetStackAmount());
         // Calculate armor mitigation
         if (Unit::IsDamageReducedByArmor(GetSpellInfo()->GetSchoolMask(), GetSpellInfo(), GetEffIndex()))
         {
             uint32 damageReductedArmor = Unit::CalcArmorReducedDamage(caster, target, damage, GetSpellInfo(), GetCasterLevel());
             cleanDamage.mitigated_damage += damage - damageReductedArmor;
             damage = damageReductedArmor;
         }
         // Curse of Agony damage-per-tick calculation
         if (GetSpellInfo()->SpellFamilyName == SPELLFAMILY_WARLOCK && (GetSpellInfo()->SpellFamilyFlags[0] & 0x400) && GetSpellInfo()->SpellIconID == 544)
         {
             uint32 totalTick = GetTotalTicks();
             // 1..4 ticks, 1/2 from normal tick damage
             if (m_tickNumber <= totalTick / 3)
                 damage = damage / 2;
             // 9..12 ticks, 3/2 from normal tick damage
             else if (m_tickNumber > totalTick * 2 / 3)
                 damage += (damage + 1) / 2;       // +1 prevent 0.5 damage possible lost at 1..4 ticks
             // 5..8 ticks have normal tick damage
         }
     }
     else // xinef: ceil obtained value, it may happen that 10 ticks for 10% damage may not kill owner
         damage = uint32(ceil(CalculatePct<float, float>(target->GetMaxHealth(), damage)));
     // calculate crit chance
     bool crit = false;
     if ((crit = roll_chance_f(GetCritChance())))
         damage = Unit::SpellCriticalDamageBonus(caster, m_spellInfo, damage, target);
     // Auras reducing damage from AOE spells
     if (GetSpellInfo()->Effects[GetEffIndex()].IsAreaAuraEffect() || GetSpellInfo()->Effects[GetEffIndex()].IsTargetingArea() || GetSpellInfo()->Effects[GetEffIndex()].Effect == SPELL_EFFECT_PERSISTENT_AREA_AURA) // some persistent area auras have targets like A=53 B=28
     {
         damage = target->CalculateAOEDamageReduction(damage, GetSpellInfo()->SchoolMask, caster);
     }
     if (CanApplyResilience())
     {
         int32 resilienceReduction = damage;
         Unit::ApplyResilience(target, nullptr, &resilienceReduction, crit, CR_CRIT_TAKEN_SPELL);
         resilienceReduction = damage - resilienceReduction;
         damage -= resilienceReduction;
         cleanDamage.mitigated_damage += resilienceReduction;
     }
     DamageInfo dmgInfo(caster, target, damage, GetSpellInfo(), GetSpellInfo()->GetSchoolMask(), DOT, cleanDamage.mitigated_damage);
     Unit::CalcAbsorbResist(dmgInfo);
     uint32 absorb = dmgInfo.GetAbsorb();
     uint32 resist = dmgInfo.GetResist();
     damage = dmgInfo.GetDamage();
     LOG_DEBUG("spells.aura.effect", "PeriodicTick: %s attacked %s for %u dmg inflicted by %u abs is %u",
                     GetCasterGUID().ToString().c_str(), target->GetGUID().ToString().c_str(), damage, GetId(), absorb);
     Unit::DealDamageMods(target, damage, &absorb);
     // Set trigger flag
     uint32 procAttacker = PROC_FLAG_DONE_PERIODIC;
     uint32 procVictim   = PROC_FLAG_TAKEN_PERIODIC;
     uint32 procEx = (crit ? PROC_EX_CRITICAL_HIT : PROC_EX_NORMAL_HIT) | PROC_EX_INTERNAL_DOT;
     if (absorb > 0)
         procEx |= PROC_EX_ABSORB;
     if (damage)
         procVictim |= PROC_FLAG_TAKEN_DAMAGE;
     int32 overkill = damage - target->GetHealth();
     if (overkill < 0)
         overkill = 0;
     SpellPeriodicAuraLogInfo pInfo(this, damage, overkill, absorb, resist, 0.0f, crit);
     target->SendPeriodicAuraLog(&pInfo);
     Unit::DealDamage(caster, target, damage, &cleanDamage, DOT, GetSpellInfo()->GetSchoolMask(), GetSpellInfo(), true);
     // allow null caster to call this function
     caster->ProcDamageAndSpell(target, caster ? procAttacker : 0, procVictim, procEx, damage, BASE_ATTACK, GetSpellInfo(), nullptr, GetEffIndex(), nullptr, &dmgInfo);
 }
References Unit::ApplyResilience(), BASE_ATTACK, Unit::CalcAbsorbResist(), Unit::CalcArmorReducedDamage(), Unit::CalculateAOEDamageReduction(), CanApplyResilience(), G3D::ceil(), CR_CRIT_TAKEN_SPELL, Unit::DealDamage(), Unit::DealDamageMods(), DOT, DYNOBJ_AURA_TYPE, EFFECT_1, SpellInfo::Effects, DamageInfo::GetAbsorb(), GetAmount(), GetAuraType(), GetBase(), GetCasterGUID(), GetCasterLevel(), GetCritChance(), DamageInfo::GetDamage(), GetEffIndex(), Object::GetGUID(), Unit::GetHealth(), GetId(), Unit::GetMaxHealth(), DamageInfo::GetResist(), GetSpellInfo(), Aura::GetStackAmount(), GetTotalTicks(), Aura::GetType(), Unit::HasUnitState(), Unit::HealthBelowPct(), Unit::IsAlive(), Unit::IsDamageReducedByArmor(), Unit::IsFullHealth(), Unit::IsImmunedToDamageOrSchool(), Unit::IsTotem(), LOG_DEBUG, m_spellInfo, m_tickNumber, max, MELEE_HIT_NORMAL, CleanDamage::mitigated_damage, PROC_EX_ABSORB, PROC_EX_CRITICAL_HIT, PROC_EX_INTERNAL_DOT, PROC_EX_NORMAL_HIT, PROC_FLAG_DONE_PERIODIC, PROC_FLAG_TAKEN_DAMAGE, PROC_FLAG_TAKEN_PERIODIC, Unit::ProcDamageAndSpell(), Unit::RemoveAurasDueToSpell(), roll_chance_f(), Unit::SendPeriodicAuraLog(), SendTickImmune(), SPELL_AURA_PERIODIC_DAMAGE, SPELL_EFFECT_PERSISTENT_AREA_AURA, SPELL_MISS_NONE, Unit::SpellCriticalDamageBonus(), Unit::SpellDamageBonusDone(), Unit::SpellDamageBonusTaken(), SPELLFAMILY_WARLOCK, Unit::SpellHitResult(), sScriptMgr, ObjectGuid::ToString(), Acore::ToString(), and UNIT_STATE_ISOLATED.
Referenced by PeriodicTick().
HandlePeriodicDummyAuraTick()
void AuraEffect::HandlePeriodicDummyAuraTick (Unit * target, Unit * caster) const
Definition at line 5770 of file SpellAuraEffects.cpp.
 {
     switch (GetSpellInfo()->SpellFamilyName)
     {
         case SPELLFAMILY_DRUID:
             {
                 switch (GetSpellInfo()->Id)
                 {
                     // Frenzied Regeneration
                     case 22842:
{
                             // Converts up to 10 rage per second into health for $d.  Each point of rage is converted into ${$m2/10}.1% of max health.
                             // Should be manauser
                             if (target->getPowerType() != POWER_RAGE)
                                 break;
                             uint32 rage = target->GetPower(POWER_RAGE);
                             // Nothing todo
                             if (rage == 0)
                                 break;
                             int32 mod = (rage < 100) ? rage : 100;
                             int32 points = target->CalculateSpellDamage(target, GetSpellInfo(), 1);
                             int32 regen = target->GetMaxHealth() * (mod * points / 10) / 1000;
                             target->CastCustomSpell(target, 22845, &regen, 0, 0, true, 0, this);
                             target->SetPower(POWER_RAGE, rage - mod);
                             break;
                         }
                 }
                 break;
             }
         case SPELLFAMILY_HUNTER:
             {
                 // Explosive Shot
                 if (GetSpellInfo()->SpellFamilyFlags[1] & 0x80000000)
                 {
                     if (caster)
                         caster->CastCustomSpell(53352, SPELLVALUE_BASE_POINT0, m_amount, target, true, nullptr, this);
                     break;
                 }
                 switch (GetSpellInfo()->Id)
                 {
                     // Feeding Frenzy Rank 1
                     case 53511:
                         if (target->GetVictim() && target->GetVictim()->HealthBelowPct(35))
                             target->CastSpell(target, 60096, true, 0, this);
                         return;
                     // Feeding Frenzy Rank 2
                     case 53512:
                         if (target->GetVictim() && target->GetVictim()->HealthBelowPct(35))
                             target->CastSpell(target, 60097, true, 0, this);
                         return;
                     default:
                         break;
                 }
                 break;
             }
         case SPELLFAMILY_SHAMAN:
             if (GetId() == 52179) // Astral Shift
             {
                 // Periodic need for remove visual on stun/fear/silence lost
                 if (!(target->GetUInt32Value(UNIT_FIELD_FLAGS) & (UNIT_FLAG_STUNNED | UNIT_FLAG_FLEEING | UNIT_FLAG_SILENCED)))
                     target->RemoveAurasDueToSpell(52179);
                 break;
             }
             break;
         case SPELLFAMILY_DEATHKNIGHT:
             switch (GetId())
             {
                 case 49016: // Hysteria
                     uint32 damage = uint32(target->CountPctFromMaxHealth(1));
                     Unit::DealDamage(target, target, damage, nullptr, NODAMAGE, SPELL_SCHOOL_MASK_NORMAL, nullptr, false);
                     break;
             }
             // Blood of the North
             // Reaping
             // Death Rune Mastery
             if (GetSpellInfo()->SpellIconID == 3041 || GetSpellInfo()->SpellIconID == 22 || GetSpellInfo()->SpellIconID == 2622)
             {
                 if (target->GetTypeId() != TYPEID_PLAYER)
                     return;
                 if (target->ToPlayer()->getClass() != CLASS_DEATH_KNIGHT)
                     return;
                 // timer expired - remove death runes
                 target->ToPlayer()->RemoveRunesByAuraEffect(this);
             }
             break;
         default:
             break;
     }
 }
References Unit::CalculateSpellDamage(), Unit::CastCustomSpell(), Unit::CastSpell(), CLASS_DEATH_KNIGHT, Unit::CountPctFromMaxHealth(), Unit::DealDamage(), Unit::getClass(), GetId(), Unit::GetMaxHealth(), Unit::GetPower(), Unit::getPowerType(), GetSpellInfo(), Object::GetTypeId(), Object::GetUInt32Value(), Unit::GetVictim(), Unit::HealthBelowPct(), SpellInfo::Id, m_amount, mod(), NODAMAGE, POWER_RAGE, Unit::RemoveAurasDueToSpell(), Player::RemoveRunesByAuraEffect(), Unit::SetPower(), SPELL_SCHOOL_MASK_NORMAL, SPELLFAMILY_DEATHKNIGHT, SPELLFAMILY_DRUID, SPELLFAMILY_HUNTER, SPELLFAMILY_SHAMAN, SpellInfo::SpellFamilyFlags, SPELLVALUE_BASE_POINT0, Object::ToPlayer(), TYPEID_PLAYER, UNIT_FIELD_FLAGS, UNIT_FLAG_FLEEING, UNIT_FLAG_SILENCED, and UNIT_FLAG_STUNNED.
Referenced by PeriodicTick().
HandlePeriodicEnergizeAuraTick()
void AuraEffect::HandlePeriodicEnergizeAuraTick (Unit * target, Unit * caster) const
Definition at line 6703 of file SpellAuraEffects.cpp.
 {
     Powers PowerType = Powers(GetMiscValue());
     if (target->GetTypeId() == TYPEID_PLAYER && target->getPowerType() != PowerType && !m_spellInfo->HasAttribute(SPELL_ATTR7_ONLY_IN_SPELLBOOK_UNTIL_LEARNED))
         return;
     if (!target->IsAlive() || !target->GetMaxPower(PowerType))
         return;
     if (target->HasUnitState(UNIT_STATE_ISOLATED))
     {
         SendTickImmune(target, caster);
         return;
     }
     // don't regen when permanent aura target has full power
     if (GetBase()->IsPermanent() && target->GetPower(PowerType) == target->GetMaxPower(PowerType))
         return;
     // ignore negative values (can be result apply spellmods to aura damage
     int32 amount = std::max(m_amount, 0);
     SpellPeriodicAuraLogInfo pInfo(this, amount, 0, 0, 0, 0.0f, false);
     target->SendPeriodicAuraLog(&pInfo);
     LOG_DEBUG("spells.aura.effect", "PeriodicTick: %s energize %s for %u dmg inflicted by %u",
                     GetCasterGUID().ToString().c_str(), target->GetGUID().ToString().c_str(), amount, GetId());
     int32 gain = target->ModifyPower(PowerType, amount);
     if (caster)
         target->getHostileRefMgr().threatAssist(caster, float(gain) * 0.5f, GetSpellInfo());
 }
References GetBase(), GetCasterGUID(), Object::GetGUID(), Unit::getHostileRefMgr(), GetId(), Unit::GetMaxPower(), GetMiscValue(), Unit::GetPower(), Unit::getPowerType(), GetSpellInfo(), Object::GetTypeId(), SpellInfo::HasAttribute(), Unit::HasUnitState(), Unit::IsAlive(), Aura::IsPermanent(), LOG_DEBUG, m_amount, m_spellInfo, max, Unit::ModifyPower(), Unit::SendPeriodicAuraLog(), SendTickImmune(), SPELL_ATTR7_ONLY_IN_SPELLBOOK_UNTIL_LEARNED, HostileRefMgr::threatAssist(), ObjectGuid::ToString(), Acore::ToString(), TYPEID_PLAYER, and UNIT_STATE_ISOLATED.
Referenced by PeriodicTick().
HandlePeriodicHealAurasTick()
void AuraEffect::HandlePeriodicHealAurasTick (Unit * target, Unit * caster) const
Definition at line 6454 of file SpellAuraEffects.cpp.
 {
     if (!target->IsAlive())
         return;
     if (target->HasUnitState(UNIT_STATE_ISOLATED))
     {
         SendTickImmune(target, caster);
         return;
     }
     // heal for caster damage (must be alive)
     if (target != caster && GetSpellInfo()->HasAttribute(SPELL_ATTR2_NO_TARGET_PER_SECOND_COST) && (!caster || !caster->IsAlive()))
         return;
     // don't regen when permanent aura target has full power
     if (GetBase()->IsPermanent() && target->IsFullHealth())
         return;
     // ignore negative values (can be result apply spellmods to aura damage
     int32 damage = std::max(m_amount, 0);
     if (GetAuraType() == SPELL_AURA_OBS_MOD_HEALTH)
     {
         // Taken mods
         float TakenTotalMod = 1.0f;
         // Tenacity increase healing % taken
         if (AuraEffect const* Tenacity = target->GetAuraEffect(58549, 0))
             AddPct(TakenTotalMod, Tenacity->GetAmount());
         // Healing taken percent
         float minval = (float)target->GetMaxNegativeAuraModifier(SPELL_AURA_MOD_HEALING_PCT);
         if (minval)
             AddPct(TakenTotalMod, minval);
         float maxval = (float)target->GetMaxPositiveAuraModifier(SPELL_AURA_MOD_HEALING_PCT);
         if (maxval)
             AddPct(TakenTotalMod, maxval);
         // Healing over time taken percent
         float minval_hot = (float)target->GetMaxNegativeAuraModifier(SPELL_AURA_MOD_HOT_PCT);
         if (minval_hot)
             AddPct(TakenTotalMod, minval_hot);
         float maxval_hot = (float)target->GetMaxPositiveAuraModifier(SPELL_AURA_MOD_HOT_PCT);
         if (maxval_hot)
             AddPct(TakenTotalMod, maxval_hot);
         // Arena / BG Dampening
         float minval_pct = (float)target->GetMaxNegativeAuraModifier(SPELL_AURA_MOD_HEALING_DONE_PERCENT);
         if (minval_pct)
             AddPct(TakenTotalMod, minval_pct);
         TakenTotalMod = std::max(TakenTotalMod, 0.0f);
         // the most ugly hack i made :P the other option is to change all spellvalues to float...
         // demonic aegis
         if (caster && GetSpellInfo()->SpellFamilyName == SPELLFAMILY_WARLOCK && (GetSpellInfo()->SpellFamilyFlags[1] & 0x20000000))
             if (AuraEffect* aurEff = caster->GetAuraEffect(SPELL_AURA_ADD_PCT_MODIFIER, SPELLFAMILY_WARLOCK, 89, 0))
                 AddPct(TakenTotalMod, aurEff->GetAmount());
         damage = uint32(target->CountPctFromMaxHealth(damage));
         damage = uint32(damage * TakenTotalMod);
     }
     else
     {
         // Wild Growth = amount + (6 - 2*doneTicks) * ticks* amount / 100
         if (GetSpellInfo()->SpellFamilyName == SPELLFAMILY_DRUID && GetSpellInfo()->SpellIconID == 2864)
         {
             uint32 tickNumber = GetTickNumber() - 1;
             int32 tempAmount = m_spellInfo->Effects[m_effIndex].CalcValue(caster, &m_baseAmount, nullptr);
             float drop = 2.0f;
             // Item - Druid T10 Restoration 2P Bonus
             if (caster)
                 if (AuraEffect* aurEff = caster->GetAuraEffect(70658, 0))
                     AddPct(drop, -aurEff->GetAmount());
             damage += GetTotalTicks() * tempAmount * (6 - (drop * tickNumber)) * 0.01f;
         }
         if (GetBase()->GetType() == DYNOBJ_AURA_TYPE)
             damage = caster->SpellHealingBonusDone(target, GetSpellInfo(), damage, DOT, 0.0f, GetBase()->GetStackAmount());
         damage = target->SpellHealingBonusTaken(caster, GetSpellInfo(), damage, DOT, GetBase()->GetStackAmount());
     }
     bool crit = false;
     if ((crit = roll_chance_f(GetCritChance())))
         damage = Unit::SpellCriticalHealingBonus(caster, GetSpellInfo(), damage, target);
     LOG_DEBUG("spells.aura.effect", "PeriodicTick: %s heal of %s for %u health inflicted by %u",
                     GetCasterGUID().ToString().c_str(), target->GetGUID().ToString().c_str(), damage, GetId());
     uint32 heal = uint32(damage);
     // Script Hook For HandlePeriodicDamageAurasTick -- Allow scripts to change the Damage pre class mitigation calculations
     sScriptMgr->ModifyPeriodicDamageAurasTick(target, caster, heal);
     HealInfo healInfo(caster, target, heal, GetSpellInfo(), GetSpellInfo()->GetSchoolMask());
     Unit::CalcHealAbsorb(healInfo);
     int32 gain = Unit::DealHeal(caster, target, healInfo.GetHeal());
     SpellPeriodicAuraLogInfo pInfo(this, healInfo.GetHeal(), healInfo.GetHeal() - gain, healInfo.GetAbsorb(), 0, 0.0f, crit);
     target->SendPeriodicAuraLog(&pInfo);
     if (caster)
         target->getHostileRefMgr().threatAssist(caster, float(gain) * 0.5f, GetSpellInfo());
     bool haveCastItem = GetBase()->GetCastItemGUID();
     // Health Funnel
     // damage caster for heal amount
     // xinef: caster is available, checked earlier
     if (target != caster && GetSpellInfo()->HasAttribute(SPELL_ATTR2_NO_TARGET_PER_SECOND_COST))
     {
         uint32 manaPerSecond = GetSpellInfo()->ManaPerSecond;
         if ((int32)manaPerSecond > gain && gain > 0)
         {
             manaPerSecond = gain;
         }
         uint32 absorb2 = 0;
         Unit::DealDamageMods(caster, manaPerSecond, &absorb2);
         CleanDamage cleanDamage = CleanDamage(0, 0, BASE_ATTACK, MELEE_HIT_NORMAL);
         Unit::DealDamage(caster, caster, manaPerSecond, &cleanDamage, SELF_DAMAGE, GetSpellInfo()->GetSchoolMask(), GetSpellInfo(), true);
     }
     uint32 procAttacker = PROC_FLAG_DONE_PERIODIC;
     uint32 procVictim   = PROC_FLAG_TAKEN_PERIODIC;
     uint32 procEx = (crit ? PROC_EX_CRITICAL_HIT : PROC_EX_NORMAL_HIT) | PROC_EX_INTERNAL_HOT;
     if (healInfo.GetAbsorb() > 0)
         procEx |= PROC_EX_ABSORB;
     // ignore item heals
     if (!haveCastItem && GetAuraType() != SPELL_AURA_OBS_MOD_HEALTH) // xinef: dont allow obs_mod_health to proc spells, this is passive regeneration and not hot
         // xinef: allow null caster to proc
         caster->ProcDamageAndSpell(target, caster ? procAttacker : 0, procVictim, procEx, heal, BASE_ATTACK, GetSpellInfo(), nullptr, GetEffIndex(), nullptr, nullptr, &healInfo);
 }
References AddPct(), BASE_ATTACK, Unit::CalcHealAbsorb(), Unit::CountPctFromMaxHealth(), Unit::DealDamage(), Unit::DealDamageMods(), Unit::DealHeal(), DOT, DYNOBJ_AURA_TYPE, SpellInfo::Effects, HealInfo::GetAbsorb(), Unit::GetAuraEffect(), GetAuraType(), GetBase(), GetCasterGUID(), Aura::GetCastItemGUID(), GetCritChance(), GetEffIndex(), Object::GetGUID(), HealInfo::GetHeal(), Unit::getHostileRefMgr(), GetId(), Unit::GetMaxNegativeAuraModifier(), Unit::GetMaxPositiveAuraModifier(), GetSpellInfo(), Aura::GetStackAmount(), GetTickNumber(), GetTotalTicks(), Aura::GetType(), Unit::HasUnitState(), Unit::IsAlive(), Unit::IsFullHealth(), Aura::IsPermanent(), LOG_DEBUG, m_amount, m_baseAmount, m_effIndex, m_spellInfo, SpellInfo::ManaPerSecond, max, MELEE_HIT_NORMAL, PROC_EX_ABSORB, PROC_EX_CRITICAL_HIT, PROC_EX_INTERNAL_HOT, PROC_EX_NORMAL_HIT, PROC_FLAG_DONE_PERIODIC, PROC_FLAG_TAKEN_PERIODIC, Unit::ProcDamageAndSpell(), roll_chance_f(), SELF_DAMAGE, Unit::SendPeriodicAuraLog(), SendTickImmune(), SPELL_ATTR2_NO_TARGET_PER_SECOND_COST, SPELL_AURA_ADD_PCT_MODIFIER, SPELL_AURA_MOD_HEALING_DONE_PERCENT, SPELL_AURA_MOD_HEALING_PCT, SPELL_AURA_MOD_HOT_PCT, SPELL_AURA_OBS_MOD_HEALTH, Unit::SpellCriticalHealingBonus(), SPELLFAMILY_DRUID, SPELLFAMILY_WARLOCK, Unit::SpellHealingBonusDone(), Unit::SpellHealingBonusTaken(), sScriptMgr, HostileRefMgr::threatAssist(), ObjectGuid::ToString(), Acore::ToString(), and UNIT_STATE_ISOLATED.
Referenced by PeriodicTick().
HandlePeriodicHealthFunnelAuraTick()
void AuraEffect::HandlePeriodicHealthFunnelAuraTick (Unit * target, Unit * caster) const
Definition at line 6425 of file SpellAuraEffects.cpp.
 {
     if (!caster || !caster->IsAlive() || !target->IsAlive())
         return;
     if (target->HasUnitState(UNIT_STATE_ISOLATED))
     {
         SendTickImmune(target, caster);
         return;
     }
     uint32 damage = std::max(GetAmount(), 0);
     // do not kill health donator
     if (caster->GetHealth() < damage)
         damage = caster->GetHealth() - 1;
     if (!damage)
         return;
     caster->ModifyHealth(-(int32)damage);
     LOG_DEBUG("spells.aura", "PeriodicTick: donator %u target %u damage %u.", caster->GetEntry(), target->GetEntry(), damage);
     float gainMultiplier = GetSpellInfo()->Effects[GetEffIndex()].CalcValueMultiplier(caster);
     damage = int32(damage * gainMultiplier);
     HealInfo healInfo(caster, target, damage, GetSpellInfo(), GetSpellInfo()->GetSchoolMask());
     caster->HealBySpell(healInfo);
 }
References SpellInfo::Effects, GetAmount(), GetEffIndex(), Object::GetEntry(), Unit::GetHealth(), GetSpellInfo(), Unit::HasUnitState(), Unit::HealBySpell(), Unit::IsAlive(), LOG_DEBUG, max, Unit::ModifyHealth(), SendTickImmune(), and UNIT_STATE_ISOLATED.
Referenced by PeriodicTick().
HandlePeriodicHealthLeechAuraTick()
void AuraEffect::HandlePeriodicHealthLeechAuraTick (Unit * target, Unit * caster) const
Definition at line 6329 of file SpellAuraEffects.cpp.
 {
     if (!target->IsAlive())
         return;
     if (target->HasUnitState(UNIT_STATE_ISOLATED) || target->IsImmunedToDamageOrSchool(GetSpellInfo()))
     {
         SendTickImmune(target, caster);
         return;
     }
     if (caster && GetSpellInfo()->Effects[GetEffIndex()].Effect == SPELL_EFFECT_PERSISTENT_AREA_AURA &&
             caster->SpellHitResult(target, GetSpellInfo(), false) != SPELL_MISS_NONE)
         return;
     CleanDamage cleanDamage = CleanDamage(0, 0, BASE_ATTACK, MELEE_HIT_NORMAL);
     uint32 damage = std::max(GetAmount(), 0);
     // Script Hook For HandlePeriodicHealthLeechAurasTick -- Allow scripts to change the Damage pre class mitigation calculations
     sScriptMgr->ModifyPeriodicDamageAurasTick(target, caster, damage);
     if (GetBase()->GetType() == DYNOBJ_AURA_TYPE)
         damage = caster->SpellDamageBonusDone(target, GetSpellInfo(), damage, DOT, 0.0f, GetBase()->GetStackAmount());
     damage = target->SpellDamageBonusTaken(caster, GetSpellInfo(), damage, DOT, GetBase()->GetStackAmount());
     bool crit = false;
     if ((crit = roll_chance_f(GetCritChance())))
         damage = Unit::SpellCriticalDamageBonus(caster, m_spellInfo, damage, target);
     // Calculate armor mitigation
     if (Unit::IsDamageReducedByArmor(GetSpellInfo()->GetSchoolMask(), GetSpellInfo(), m_effIndex))
     {
         uint32 damageReductedArmor = Unit::CalcArmorReducedDamage(caster, target, damage, GetSpellInfo(), GetCasterLevel());
         cleanDamage.mitigated_damage += damage - damageReductedArmor;
         damage = damageReductedArmor;
     }
     if (CanApplyResilience())
     {
         int32 resilienceReduction = damage;
         Unit::ApplyResilience(target, nullptr, &resilienceReduction, crit, CR_CRIT_TAKEN_SPELL);
         resilienceReduction = damage - resilienceReduction;
         damage -= resilienceReduction;
         cleanDamage.mitigated_damage += resilienceReduction;
     }
     DamageInfo dmgInfo(caster, target, damage, GetSpellInfo(), GetSpellInfo()->GetSchoolMask(), DOT, cleanDamage.mitigated_damage);
     Unit::CalcAbsorbResist(dmgInfo);
     uint32 absorb = dmgInfo.GetAbsorb();
     uint32 resist = dmgInfo.GetResist();
     damage = dmgInfo.GetDamage();
     // Set trigger flag
     uint32 procAttacker = PROC_FLAG_DONE_PERIODIC;
     uint32 procVictim   = PROC_FLAG_TAKEN_PERIODIC;
     uint32 procEx = (crit ? PROC_EX_CRITICAL_HIT : PROC_EX_NORMAL_HIT) | PROC_EX_INTERNAL_DOT;
     if (absorb > 0)
         procEx |= PROC_EX_ABSORB;
     if (dmgInfo.GetDamage())
         procVictim |= PROC_FLAG_TAKEN_DAMAGE;
     if (target->GetHealth() < dmgInfo.GetDamage())
     {
         dmgInfo.ModifyDamage(dmgInfo.GetDamage() - target->GetHealth());
     }
     damage = dmgInfo.GetDamage();
     LOG_DEBUG("spells.aura.effect", "PeriodicTick: %s health leech of %s for %u dmg inflicted by %u abs is %u",
                     GetCasterGUID().ToString().c_str(), target->GetGUID().ToString().c_str(), damage, GetId(), absorb);
     if (caster)
         caster->SendSpellNonMeleeDamageLog(target, GetSpellInfo(), damage, GetSpellInfo()->GetSchoolMask(), absorb, resist, false, 0, crit);
     int32 new_damage;
     new_damage = Unit::DealDamage(caster, target, damage, &cleanDamage, DOT, GetSpellInfo()->GetSchoolMask(), GetSpellInfo(), false);
     // allow null caster to call this function
     caster->ProcDamageAndSpell(target, caster ? procAttacker : 0, procVictim, procEx, damage, BASE_ATTACK, GetSpellInfo(), nullptr, GetEffIndex(), nullptr, &dmgInfo);
     if (!caster || !caster->IsAlive())
         return;
     float gainMultiplier = GetSpellInfo()->Effects[GetEffIndex()].CalcValueMultiplier(caster);
     uint32 heal = uint32(caster->SpellHealingBonusDone(caster, GetSpellInfo(), uint32(new_damage * gainMultiplier), DOT, 0.0f, GetBase()->GetStackAmount()));
     heal = uint32(caster->SpellHealingBonusTaken(caster, GetSpellInfo(), heal, DOT, GetBase()->GetStackAmount()));
     HealInfo healInfo(caster, caster, heal, GetSpellInfo(), GetSpellInfo()->GetSchoolMask());
     int32 gain = caster->HealBySpell(healInfo);
     caster->getHostileRefMgr().threatAssist(caster, gain * 0.5f, GetSpellInfo());
 }
References Unit::ApplyResilience(), BASE_ATTACK, Unit::CalcAbsorbResist(), Unit::CalcArmorReducedDamage(), CanApplyResilience(), CR_CRIT_TAKEN_SPELL, Unit::DealDamage(), DOT, DYNOBJ_AURA_TYPE, SpellInfo::Effects, DamageInfo::GetAbsorb(), GetAmount(), GetBase(), GetCasterGUID(), GetCasterLevel(), GetCritChance(), DamageInfo::GetDamage(), GetEffIndex(), Object::GetGUID(), Unit::GetHealth(), Unit::getHostileRefMgr(), GetId(), DamageInfo::GetResist(), GetSpellInfo(), Aura::GetStackAmount(), Aura::GetType(), Unit::HasUnitState(), Unit::HealBySpell(), Unit::IsAlive(), Unit::IsDamageReducedByArmor(), Unit::IsImmunedToDamageOrSchool(), LOG_DEBUG, m_effIndex, m_spellInfo, max, MELEE_HIT_NORMAL, CleanDamage::mitigated_damage, DamageInfo::ModifyDamage(), PROC_EX_ABSORB, PROC_EX_CRITICAL_HIT, PROC_EX_INTERNAL_DOT, PROC_EX_NORMAL_HIT, PROC_FLAG_DONE_PERIODIC, PROC_FLAG_TAKEN_DAMAGE, PROC_FLAG_TAKEN_PERIODIC, Unit::ProcDamageAndSpell(), roll_chance_f(), Unit::SendSpellNonMeleeDamageLog(), SendTickImmune(), SPELL_EFFECT_PERSISTENT_AREA_AURA, SPELL_MISS_NONE, Unit::SpellCriticalDamageBonus(), Unit::SpellDamageBonusDone(), Unit::SpellDamageBonusTaken(), Unit::SpellHealingBonusDone(), Unit::SpellHealingBonusTaken(), Unit::SpellHitResult(), sScriptMgr, HostileRefMgr::threatAssist(), ObjectGuid::ToString(), Acore::ToString(), and UNIT_STATE_ISOLATED.
Referenced by PeriodicTick().
HandlePeriodicManaLeechAuraTick()
void AuraEffect::HandlePeriodicManaLeechAuraTick (Unit * target, Unit * caster) const
Definition at line 6596 of file SpellAuraEffects.cpp.
 {
     Powers PowerType = Powers(GetMiscValue());
     if (!caster || !caster->IsAlive() || !target->IsAlive() || target->getPowerType() != PowerType)
         return;
     if (target->HasUnitState(UNIT_STATE_ISOLATED) || target->IsImmunedToDamageOrSchool(GetSpellInfo()))
     {
         SendTickImmune(target, caster);
         return;
     }
     if (GetSpellInfo()->Effects[GetEffIndex()].Effect == SPELL_EFFECT_PERSISTENT_AREA_AURA &&
             caster->SpellHitResult(target, GetSpellInfo(), false) != SPELL_MISS_NONE)
         return;
     // ignore negative values (can be result apply spellmods to aura damage
     int32 drainAmount = std::max(m_amount, 0);
     // Special case: draining x% of mana (up to a maximum of 2*x% of the caster's maximum mana)
     // It's mana percent cost spells, m_amount is percent drain from target
     if (m_spellInfo->ManaCostPercentage)
     {
         // max value
         int32 maxmana = CalculatePct(caster->GetMaxPower(PowerType), drainAmount * 2.0f);
         ApplyPct(drainAmount, target->GetMaxPower(PowerType));
         if (drainAmount > maxmana)
             drainAmount = maxmana;
     }
     LOG_DEBUG("spells.aura.effect", "PeriodicTick: %s power leech of %s for %u dmg inflicted by %u",
                     GetCasterGUID().ToString().c_str(), target->GetGUID().ToString().c_str(), drainAmount, GetId());
     // resilience reduce mana draining effect at spell crit damage reduction (added in 2.4)
     if (PowerType == POWER_MANA)
         drainAmount -= target->GetSpellCritDamageReduction(drainAmount);
     int32 drainedAmount = -target->ModifyPower(PowerType, -drainAmount);
     float gainMultiplier = GetSpellInfo()->Effects[GetEffIndex()].CalcValueMultiplier(caster);
     SpellPeriodicAuraLogInfo pInfo(this, drainedAmount, 0, 0, 0, gainMultiplier, false);
     target->SendPeriodicAuraLog(&pInfo);
     int32 gainAmount = int32(drainedAmount * gainMultiplier);
     int32 gainedAmount = 0;
     if (gainAmount)
     {
         gainedAmount = caster->ModifyPower(PowerType, gainAmount);
         target->AddThreat(caster, float(gainedAmount) * 0.5f, GetSpellInfo()->GetSchoolMask(), GetSpellInfo());
     }
     target->AddThreat(caster, float(gainedAmount) * 0.5f, GetSpellInfo()->GetSchoolMask(), GetSpellInfo());
     // remove CC auras
     target->RemoveAurasWithInterruptFlags(AURA_INTERRUPT_FLAG_TAKE_DAMAGE);
     // Drain Mana
     if (m_spellInfo->SpellFamilyName == SPELLFAMILY_WARLOCK
             && m_spellInfo->SpellFamilyFlags[0] & 0x00000010)
     {
         int32 manaFeedVal = 0;
         if (AuraEffect const* aurEff = GetBase()->GetEffect(1))
             manaFeedVal = aurEff->GetAmount();
         // Mana Feed - Drain Mana
         if (manaFeedVal > 0)
         {
             int32 feedAmount = CalculatePct(gainedAmount, manaFeedVal);
             caster->CastCustomSpell(caster, 32554, &feedAmount, nullptr, nullptr, true, nullptr, this);
         }
     }
 }
References Unit::AddThreat(), ApplyPct(), AURA_INTERRUPT_FLAG_TAKE_DAMAGE, CalculatePct(), Unit::CastCustomSpell(), SpellInfo::Effects, GetBase(), GetCasterGUID(), Aura::GetEffect(), GetEffIndex(), Object::GetGUID(), GetId(), Unit::GetMaxPower(), GetMiscValue(), Unit::getPowerType(), Unit::GetSpellCritDamageReduction(), GetSpellInfo(), Unit::HasUnitState(), Unit::IsAlive(), Unit::IsImmunedToDamageOrSchool(), LOG_DEBUG, m_amount, m_spellInfo, SpellInfo::ManaCostPercentage, max, Unit::ModifyPower(), POWER_MANA, Unit::RemoveAurasWithInterruptFlags(), Unit::SendPeriodicAuraLog(), SendTickImmune(), SPELL_EFFECT_PERSISTENT_AREA_AURA, SPELL_MISS_NONE, SPELLFAMILY_WARLOCK, SpellInfo::SpellFamilyFlags, SpellInfo::SpellFamilyName, Unit::SpellHitResult(), ObjectGuid::ToString(), Acore::ToString(), and UNIT_STATE_ISOLATED.
Referenced by PeriodicTick().
HandlePeriodicPowerBurnAuraTick()
void AuraEffect::HandlePeriodicPowerBurnAuraTick (Unit * target, Unit * caster) const
Definition at line 6737 of file SpellAuraEffects.cpp.
 {
     Powers PowerType = Powers(GetMiscValue());
     if (!caster || !target->IsAlive() || target->getPowerType() != PowerType)
         return;
     if (target->HasUnitState(UNIT_STATE_ISOLATED) || target->IsImmunedToDamageOrSchool(GetSpellInfo()))
     {
         SendTickImmune(target, caster);
         return;
     }
     // ignore negative values (can be result apply spellmods to aura damage
     int32 damage = std::max(m_amount, 0);
     // resilience reduce mana draining effect at spell crit damage reduction (added in 2.4)
     if (PowerType == POWER_MANA)
         damage -= target->GetSpellCritDamageReduction(damage);
     uint32 gain = uint32(-target->ModifyPower(PowerType, -damage));
     float dmgMultiplier = GetSpellInfo()->Effects[GetEffIndex()].CalcValueMultiplier(caster);
     SpellInfo const* spellProto = GetSpellInfo();
     // maybe has to be sent different to client, but not by SMSG_PERIODICAURALOG
     SpellNonMeleeDamage damageInfo(caster, target, spellProto, spellProto->SchoolMask);
     // no SpellDamageBonus for burn mana
     caster->CalculateSpellDamageTaken(&damageInfo, int32(gain * dmgMultiplier), spellProto);
     Unit::DealDamageMods(damageInfo.target, damageInfo.damage, &damageInfo.absorb);
     caster->SendSpellNonMeleeDamageLog(&damageInfo);
     // Set trigger flag
     uint32 procAttacker = PROC_FLAG_DONE_PERIODIC;
     uint32 procVictim   = PROC_FLAG_TAKEN_PERIODIC;
     uint32 procEx       = createProcExtendMask(&damageInfo, SPELL_MISS_NONE) | PROC_EX_INTERNAL_DOT;
     if (damageInfo.damage)
         procVictim |= PROC_FLAG_TAKEN_DAMAGE;
     caster->DealSpellDamage(&damageInfo, true);
     DamageInfo dmgInfo(damageInfo, DOT);
     caster->ProcDamageAndSpell(damageInfo.target, procAttacker, procVictim, procEx, damageInfo.damage, BASE_ATTACK, spellProto, nullptr, GetEffIndex(), nullptr, &dmgInfo);
 }
References SpellNonMeleeDamage::absorb, BASE_ATTACK, Unit::CalculateSpellDamageTaken(), createProcExtendMask(), SpellNonMeleeDamage::damage, Unit::DealDamageMods(), Unit::DealSpellDamage(), DOT, SpellInfo::Effects, GetEffIndex(), GetMiscValue(), Unit::getPowerType(), Unit::GetSpellCritDamageReduction(), GetSpellInfo(), Unit::HasUnitState(), Unit::IsAlive(), Unit::IsImmunedToDamageOrSchool(), m_amount, max, Unit::ModifyPower(), POWER_MANA, PROC_EX_INTERNAL_DOT, PROC_FLAG_DONE_PERIODIC, PROC_FLAG_TAKEN_DAMAGE, PROC_FLAG_TAKEN_PERIODIC, Unit::ProcDamageAndSpell(), SpellInfo::SchoolMask, Unit::SendSpellNonMeleeDamageLog(), SendTickImmune(), SPELL_MISS_NONE, SpellNonMeleeDamage::target, and UNIT_STATE_ISOLATED.
Referenced by PeriodicTick().
HandlePeriodicTriggerSpellAuraTick()
void AuraEffect::HandlePeriodicTriggerSpellAuraTick (Unit * target, Unit * caster) const
Definition at line 5861 of file SpellAuraEffects.cpp.
 {
     // generic casting code with custom spells and target/caster customs
     uint32 triggerSpellId = GetSpellInfo()->Effects[GetEffIndex()].TriggerSpell;
     SpellInfo const* triggeredSpellInfo = sSpellMgr->GetSpellInfo(triggerSpellId);
     SpellInfo const* auraSpellInfo = GetSpellInfo();
     uint32 auraId = auraSpellInfo->Id;
     // specific code for cases with no trigger spell provided in field
     if (triggeredSpellInfo == nullptr)
     {
         switch (auraSpellInfo->SpellFamilyName)
         {
             case SPELLFAMILY_GENERIC:
                 {
                     switch (auraId)
                     {
                         // Thaumaturgy Channel
                         case 9712:
                             triggerSpellId = 21029;
                             if (caster)
                                 caster->CastSpell(caster, triggerSpellId, true);
                             return;
                         // Brood Affliction: Bronze
                         case 23170:
                             triggerSpellId = 23171;
                             break;
                         // Restoration
                         case 24379:
                         case 23493:
{
                                 if (caster)
{
                                     int32 heal = caster->CountPctFromMaxHealth(10);
                                     HealInfo healInfo(caster, target, heal, auraSpellInfo, auraSpellInfo->GetSchoolMask());
                                     caster->HealBySpell(healInfo);
                                     if (int32 mana = caster->GetMaxPower(POWER_MANA))
{
                                         mana /= 10;
                                         caster->EnergizeBySpell(caster, 23493, mana, POWER_MANA);
                                     }
                                 }
                                 return;
                             }
                         // Nitrous Boost
                         case 27746:
                             if (caster && target->GetPower(POWER_MANA) >= 10)
{
                                 target->ModifyPower(POWER_MANA, -10);
                                 target->SendEnergizeSpellLog(caster, 27746, 10, POWER_MANA);
                             }
                             else
                                 target->RemoveAurasDueToSpell(27746);
                             return;
                         // Frost Blast
                         case 27808:
                             if (caster)
{
                                 caster->CastCustomSpell(29879, SPELLVALUE_BASE_POINT0, int32(target->CountPctFromMaxHealth(21)), target, true, nullptr, this);
                                 if (GetTickNumber() == 1)
                                     caster->CastSpell(target, 27808, true);
                             }
                             return;
                         // Inoculate Nestlewood Owlkin
                         case 29528:
                             if (target->GetTypeId() != TYPEID_UNIT) // prevent error reports in case ignored player target
                                 return;
                             break;
                         // Feed Captured Animal
                         case 29917:
                             triggerSpellId = 29916;
                             break;
                         // Extract Gas
                         case 30427:
{
                                 // move loot to player inventory and despawn target
                                 if (caster && caster->GetTypeId() == TYPEID_PLAYER &&
                                         target->GetTypeId() == TYPEID_UNIT &&
                                         target->ToCreature()->GetCreatureTemplate()->type == CREATURE_TYPE_GAS_CLOUD)
{
                                     Player* player = caster->ToPlayer();
                                     Creature* creature = target->ToCreature();
                                     // missing lootid has been reported on startup - just return
                                     if (!creature->GetCreatureTemplate()->SkinLootId)
                                         return;
                                     player->AutoStoreLoot(creature->GetCreatureTemplate()->SkinLootId, LootTemplates_Skinning, true);
                                     creature->DespawnOrUnsummon();
                                 }
                                 return;
                             }
                         // Quake
                         case 30576:
                             triggerSpellId = 30571;
                             break;
                         // Doom
                         // TODO: effect trigger spell may be independant on spell targets, and executed in spell finish phase
                         // so instakill will be naturally done before trigger spell
                         case 31347:
{
                                 target->CastSpell(target, 31350, true, nullptr, this);
                                 Unit::Kill(target, target);
                                 return;
                             }
                         // Spellcloth
                         case 31373:
{
                                 // Summon Elemental after create item
                                 target->SummonCreature(17870, 0, 0, 0, target->GetOrientation(), TEMPSUMMON_DEAD_DESPAWN, 0);
                                 return;
                             }
                         // Eye of Grillok
                         case 38495:
                             triggerSpellId = 38530;
                             break;
                         // Absorb Eye of Grillok (Zezzak's Shard)
                         case 38554:
{
                                 if (!caster || target->GetTypeId() != TYPEID_UNIT)
                                     return;
                                 caster->CastSpell(caster, 38495, true, nullptr, this);
                                 Creature* creatureTarget = target->ToCreature();
                                 creatureTarget->DespawnOrUnsummon();
                                 return;
                             }
                         // Tear of Azzinoth Summon Channel - it's not really supposed to do anything, and this only prevents the console spam
                         case 39857:
                             triggerSpellId = 39856;
                             break;
                         // Personalized Weather
                         case 46736:
                             triggerSpellId = 46737;
                             break;
                         // Shield Level 1
                         case 63130:
                         // Shield Level 2
                         case 63131:
                         // Shield Level 3
                         case 63132:
                         // Ball of Flames Visual
                         case 71706:
                             return;
                         // Oculus, Mage-Lord Urom, Time Bomb
                         case 51121:
                         case 59376:
{
                                 const int32 dmg = target->GetMaxHealth() - target->GetHealth();
                                 target->CastCustomSpell(target, 51132, &dmg, 0, 0, true);
                                 return;
                             }
                     }
                     break;
                 }
             case SPELLFAMILY_SHAMAN:
                 {
                     switch (auraId)
                     {
                         // Lightning Shield (The Earthshatterer set trigger after cast Lighting Shield)
                         case 28820:
{
                                 // Need remove self if Lightning Shield not active
                                 if (!target->GetAuraEffect(SPELL_AURA_PROC_TRIGGER_SPELL, SPELLFAMILY_SHAMAN, 0x400, 0, 0))
                                     target->RemoveAurasDueToSpell(28820);
                                 return;
                             }
                     }
                     break;
                 }
             default:
                 break;
         }
     }
     else
     {
         // Spell exist but require custom code
         switch (auraId)
         {
             // Mana Tide
             case 16191:
                 target->CastCustomSpell(target, triggerSpellId, &m_amount, nullptr, nullptr, true, nullptr, this);
                 return;
             // Poison (Grobbulus)
             case 28158:
             case 54362:
             // Slime Pool (Dreadscale & Acidmaw)
             case 66882:
                 target->CastCustomSpell(triggerSpellId, SPELLVALUE_RADIUS_MOD, (int32)((((float)m_tickNumber / 60) * 0.9f + 0.1f) * 10000 * 2 / 3), nullptr, true, nullptr, this);
                 return;
             // Eye of Eternity, Malygos, Arcane Overload
             case 56432:
                 if (triggerSpellId == 56438)
                 {
                     target->CastCustomSpell(triggerSpellId, SPELLVALUE_RADIUS_MOD, (int32)(10000 * (1.0f - 0.02f * (m_tickNumber + 1))), nullptr, true, nullptr, this);
                     return;
                 }
                 break;
             // Beacon of Light
             case 53563:
                 {
                     // area aura owner casts the spell
                     GetBase()->GetUnitOwner()->CastSpell(target, triggeredSpellInfo, true, 0, this, GetBase()->GetUnitOwner()->GetGUID());
                     return;
                 }
             // Slime Spray - temporary here until preventing default effect works again
             // added on 9.10.2010
             case 69508:
                 {
                     if (caster)
                         caster->CastSpell(target, triggerSpellId, true, nullptr, nullptr, caster->GetGUID());
                     return;
                 }
             // Trial of the Crusader, Jaraxxus, Spinning Pain Spike
             case 66283:
                 {
                     const int32 dmg = target->GetMaxHealth() / 2;
                     target->CastCustomSpell(target, 66316, &dmg, nullptr, nullptr, true);
                     return;
                 }
             // Violet Hold, Moragg, Ray of Suffering, Ray of Pain
             case 54442:
             case 59524:
             case 54438:
             case 59523:
                 {
                     if (caster)
                         if (Unit* victim = caster->GetVictim())
                             if(victim->GetDistance(caster) < 45.0f)
{
                                 target = victim;
                                 break;
                             }
                     return;
                 }
             case 24745: // Summon Templar, Trigger
             case 24747: // Summon Templar Fire, Trigger
             case 24757: // Summon Templar Air, Trigger
             case 24759: // Summon Templar Earth, Trigger
             case 24761: // Summon Templar Water, Trigger
             case 24762: // Summon Duke, Trigger
             case 24766: // Summon Duke Fire, Trigger
             case 24769: // Summon Duke Air, Trigger
             case 24771: // Summon Duke Earth, Trigger
             case 24773: // Summon Duke Water, Trigger
             case 24785: // Summon Royal, Trigger
             case 24787: // Summon Royal Fire, Trigger
             case 24791: // Summon Royal Air, Trigger
             case 24792: // Summon Royal Earth, Trigger
             case 24793: // Summon Royal Water, Trigger
                 {
                     // All this spells trigger a spell that requires reagents; if the
                     // triggered spell is cast as "triggered", reagents are not consumed
                     if (caster)
                         caster->CastSpell(target, triggerSpellId, false);
                     return;
                 }
             // Hunter - Rapid Recuperation
             case 56654:
             case 58882:
                 int32 amount = int32(target->GetMaxPower(POWER_MANA) * GetAmount() / 100.0f);
                 target->CastCustomSpell(target, triggerSpellId, &amount, nullptr, nullptr, true);
                 return;
         }
     }
     // Reget trigger spell proto
     triggeredSpellInfo = sSpellMgr->GetSpellInfo(triggerSpellId);
     if (triggeredSpellInfo)
     {
         if (Unit* triggerCaster = triggeredSpellInfo->NeedsToBeTriggeredByCaster(m_spellInfo, GetEffIndex()) ? caster : target)
         {
             SpellCastTargets targets;
             targets.SetUnitTarget(target);
             if (triggeredSpellInfo->IsChannelCategorySpell() && m_channelData)
             {
                 targets.SetDstChannel(m_channelData->spellDst);
                 targets.SetObjectTargetChannel(m_channelData->channelGUID);
             }
             // Xinef: do not skip reagent cost for entry casts
             TriggerCastFlags triggerFlags = TRIGGERED_FULL_MASK;
             if (GetSpellInfo()->Effects[GetEffIndex()].TargetA.GetCheckType() == TARGET_CHECK_ENTRY || GetSpellInfo()->Effects[GetEffIndex()].TargetB.GetCheckType() == TARGET_CHECK_ENTRY)
                 triggerFlags = TriggerCastFlags(TRIGGERED_FULL_MASK & ~TRIGGERED_IGNORE_POWER_AND_REAGENT_COST);
             triggerCaster->CastSpell(targets, triggeredSpellInfo, nullptr, triggerFlags, nullptr, this);
             LOG_DEBUG("spells.aura", "AuraEffect::HandlePeriodicTriggerSpellAuraTick: Spell %u Trigger %u", GetId(), triggeredSpellInfo->Id);
         }
     }
 }
References Player::AutoStoreLoot(), Unit::CastCustomSpell(), Unit::CastSpell(), ChannelTargetData::channelGUID, Unit::CountPctFromMaxHealth(), CREATURE_TYPE_GAS_CLOUD, Creature::DespawnOrUnsummon(), SpellInfo::Effects, Unit::EnergizeBySpell(), GetAmount(), Unit::GetAuraEffect(), GetBase(), Creature::GetCreatureTemplate(), GetEffIndex(), Object::GetGUID(), Unit::GetHealth(), GetId(), Unit::GetMaxHealth(), Unit::GetMaxPower(), Position::GetOrientation(), Unit::GetPower(), SpellInfo::GetSchoolMask(), GetSpellInfo(), GetTickNumber(), Object::GetTypeId(), Aura::GetUnitOwner(), Unit::GetVictim(), Unit::HealBySpell(), SpellInfo::Id, SpellInfo::IsChannelCategorySpell(), Unit::Kill(), LOG_DEBUG, LootTemplates_Skinning, m_amount, m_channelData, m_spellInfo, m_tickNumber, Unit::ModifyPower(), SpellInfo::NeedsToBeTriggeredByCaster(), POWER_MANA, Unit::RemoveAurasDueToSpell(), Unit::SendEnergizeSpellLog(), SpellCastTargets::SetDstChannel(), SpellCastTargets::SetObjectTargetChannel(), SpellCastTargets::SetUnitTarget(), CreatureTemplate::SkinLootId, SPELL_AURA_PROC_TRIGGER_SPELL, ChannelTargetData::spellDst, SPELLFAMILY_GENERIC, SPELLFAMILY_SHAMAN, SpellInfo::SpellFamilyName, SPELLVALUE_BASE_POINT0, SPELLVALUE_RADIUS_MOD, sSpellMgr, WorldObject::SummonCreature(), TARGET_CHECK_ENTRY, TEMPSUMMON_DEAD_DESPAWN, Object::ToCreature(), Object::ToPlayer(), TRIGGERED_FULL_MASK, TRIGGERED_IGNORE_POWER_AND_REAGENT_COST, CreatureTemplate::type, TYPEID_PLAYER, and TYPEID_UNIT.
Referenced by PeriodicTick().
HandlePeriodicTriggerSpellWithValueAuraTick()
void AuraEffect::HandlePeriodicTriggerSpellWithValueAuraTick (Unit * target, Unit * caster) const
Definition at line 6157 of file SpellAuraEffects.cpp.
 {
     uint32 triggerSpellId = GetSpellInfo()->Effects[m_effIndex].TriggerSpell;
     if (SpellInfo const* triggeredSpellInfo = sSpellMgr->GetSpellInfo(triggerSpellId))
     {
         if (Unit* triggerCaster = triggeredSpellInfo->NeedsToBeTriggeredByCaster(m_spellInfo, GetEffIndex()) ? caster : target)
         {
             SpellCastTargets targets;
             targets.SetUnitTarget(target);
             if (triggeredSpellInfo->IsChannelCategorySpell() && m_channelData)
             {
                 targets.SetDstChannel(m_channelData->spellDst);
                 targets.SetObjectTargetChannel(m_channelData->channelGUID);
             }
             CustomSpellValues values;
             values.AddSpellMod(SPELLVALUE_BASE_POINT0, GetAmount());
             triggerCaster->CastSpell(targets, triggeredSpellInfo, &values, TRIGGERED_FULL_MASK, nullptr, this);
             LOG_DEBUG("spells.aura", "AuraEffect::HandlePeriodicTriggerSpellWithValueAuraTick: Spell %u Trigger %u", GetId(), triggeredSpellInfo->Id);
         }
     }
     else
     {
 #ifdef ELUNA
         Creature* c = target->ToCreature();
         if (c && caster)
             sEluna->OnDummyEffect(caster, GetId(), SpellEffIndex(GetEffIndex()), target->ToCreature());
 #endif
         LOG_DEBUG("spells.aura", "AuraEffect::HandlePeriodicTriggerSpellWithValueAuraTick: Spell %u has non-existent spell %u in EffectTriggered[%d] and is therefor not triggered.", GetId(), triggerSpellId, GetEffIndex());
     }
 }
References CustomSpellValues::AddSpellMod(), mpq::c, ChannelTargetData::channelGUID, SpellInfo::Effects, GetAmount(), GetEffIndex(), GetId(), GetSpellInfo(), LOG_DEBUG, m_channelData, m_effIndex, m_spellInfo, SpellCastTargets::SetDstChannel(), SpellCastTargets::SetObjectTargetChannel(), SpellCastTargets::SetUnitTarget(), ChannelTargetData::spellDst, SPELLVALUE_BASE_POINT0, sSpellMgr, Object::ToCreature(), and TRIGGERED_FULL_MASK.
Referenced by PeriodicTick().
HandlePhase()
void AuraEffect::HandlePhase (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 1768 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     // no-phase is also phase state so same code for apply and remove
     uint32 newPhase = target->GetPhaseByAuras();
     if (Player* player = target->ToPlayer())
     {
         if (!newPhase)
             newPhase = PHASEMASK_NORMAL;
         // do not change phase to GM with all phases enabled
         if (player->IsGameMaster())
             newPhase = PHASEMASK_ANYWHERE;
         player->SetPhaseMask(newPhase, false);
         player->GetSession()->SendSetPhaseShift(newPhase);
     }
     else
     {
         if (!newPhase)
         {
             newPhase = PHASEMASK_NORMAL;
             if (Creature* creature = target->ToCreature())
                 if (CreatureData const* data = sObjectMgr->GetCreatureData(creature->GetSpawnId()))
                     newPhase = data->phaseMask;
         }
         target->SetPhaseMask(newPhase, false);
     }
     // call functions which may have additional effects after chainging state of unit
     // phase auras normally not expected at BG but anyway better check
     if (apply)
     {
         // drop flag at invisibiliy in bg
         target->RemoveAurasWithInterruptFlags(AURA_INTERRUPT_FLAG_IMMUNE_OR_LOST_SELECTION);
     }
     // need triggering visibility update base at phase update of not GM invisible (other GMs anyway see in any phases)
     if (target->IsVisible())
     {
         if (!target->GetMap()->Instanceable())
         {
             target->UpdateObjectVisibility(false);
             target->m_last_notify_position.Relocate(-5000.0f, -5000.0f, -5000.0f);
         }
         else
             target->UpdateObjectVisibility();
     }
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_REAL, AURA_INTERRUPT_FLAG_IMMUNE_OR_LOST_SELECTION, WorldObject::GetMap(), Unit::GetPhaseByAuras(), AuraApplication::GetTarget(), Map::Instanceable(), Unit::IsVisible(), Unit::m_last_notify_position, PHASEMASK_ANYWHERE, PHASEMASK_NORMAL, Position::Relocate(), Unit::RemoveAurasWithInterruptFlags(), Unit::SetPhaseMask(), sObjectMgr, Object::ToCreature(), Object::ToPlayer(), and Unit::UpdateObjectVisibility().
HandlePreventFleeing()
void AuraEffect::HandlePreventFleeing (AuraApplication const * aurApp, uint8 mode, bool apply) const
TODO: find a way to cancel fleeing for assistance. Currently this will only stop creatures fleeing due to low health that could not find nearby allies to flee towards.
Definition at line 3071 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     // Since patch 3.0.2 this mechanic no longer affects fear effects. It will ONLY prevent humanoids from fleeing due to low health.
     if (target->GetTypeId() == TYPEID_PLAYER || !apply || target->HasAuraType(SPELL_AURA_MOD_FEAR))
         return;
     target->SetControlled(false, UNIT_STATE_FLEEING);
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_REAL, AuraApplication::GetTarget(), Object::GetTypeId(), Unit::HasAuraType(), Unit::SetControlled(), SPELL_AURA_MOD_FEAR, TYPEID_PLAYER, and UNIT_STATE_FLEEING.
HandlePreventResurrection()
void AuraEffect::HandlePreventResurrection (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 5756 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     if (aurApp->GetTarget()->GetTypeId() != TYPEID_PLAYER)
         return;
     if (apply)
         aurApp->GetTarget()->RemoveByteFlag(PLAYER_FIELD_BYTES, 0, PLAYER_FIELD_BYTE_RELEASE_TIMER);
     else if (!aurApp->GetTarget()->GetMap()->Instanceable())
         aurApp->GetTarget()->SetByteFlag(PLAYER_FIELD_BYTES, 0, PLAYER_FIELD_BYTE_RELEASE_TIMER);
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_REAL, WorldObject::GetMap(), AuraApplication::GetTarget(), Object::GetTypeId(), Map::Instanceable(), PLAYER_FIELD_BYTE_RELEASE_TIMER, PLAYER_FIELD_BYTES, Object::RemoveByteFlag(), Object::SetByteFlag(), and TYPEID_PLAYER.
HandleProc()
void AuraEffect::HandleProc (AuraApplication * aurApp, ProcEventInfo & eventInfo)
Definition at line 1137 of file SpellAuraEffects.cpp.
 {
     bool prevented = GetBase()->CallScriptEffectProcHandlers(this, aurApp, eventInfo);
     if (prevented)
         return;
     switch (GetAuraType())
     {
         case SPELL_AURA_PROC_TRIGGER_SPELL:
             HandleProcTriggerSpellAuraProc(aurApp, eventInfo);
             break;
         case SPELL_AURA_PROC_TRIGGER_SPELL_WITH_VALUE:
             HandleProcTriggerSpellWithValueAuraProc(aurApp, eventInfo);
             break;
         case SPELL_AURA_PROC_TRIGGER_DAMAGE:
             HandleProcTriggerDamageAuraProc(aurApp, eventInfo);
             break;
         case SPELL_AURA_RAID_PROC_FROM_CHARGE:
             HandleRaidProcFromChargeAuraProc(aurApp, eventInfo);
             break;
         case SPELL_AURA_RAID_PROC_FROM_CHARGE_WITH_VALUE:
             HandleRaidProcFromChargeWithValueAuraProc(aurApp, eventInfo);
             break;
         default:
             break;
     }
     GetBase()->CallScriptAfterEffectProcHandlers(this, aurApp, eventInfo);
 }
References Aura::CallScriptAfterEffectProcHandlers(), Aura::CallScriptEffectProcHandlers(), GetAuraType(), GetBase(), HandleProcTriggerDamageAuraProc(), HandleProcTriggerSpellAuraProc(), HandleProcTriggerSpellWithValueAuraProc(), HandleRaidProcFromChargeAuraProc(), HandleRaidProcFromChargeWithValueAuraProc(), SPELL_AURA_PROC_TRIGGER_DAMAGE, SPELL_AURA_PROC_TRIGGER_SPELL, SPELL_AURA_PROC_TRIGGER_SPELL_WITH_VALUE, SPELL_AURA_RAID_PROC_FROM_CHARGE, and SPELL_AURA_RAID_PROC_FROM_CHARGE_WITH_VALUE.
Referenced by Aura::TriggerProcOnEvent().
HandleProcTriggerDamageAuraProc()
void AuraEffect::HandleProcTriggerDamageAuraProc (AuraApplication * aurApp, ProcEventInfo & eventInfo)
Definition at line 6822 of file SpellAuraEffects.cpp.
 {
     Unit* target = aurApp->GetTarget();
     Unit* triggerTarget = eventInfo.GetProcTarget();
     if (triggerTarget->HasUnitState(UNIT_STATE_ISOLATED) || triggerTarget->IsImmunedToDamageOrSchool(GetSpellInfo()))
     {
         SendTickImmune(triggerTarget, target);
         return;
     }
     SpellNonMeleeDamage damageInfo(target, triggerTarget, GetSpellInfo(), GetSpellInfo()->SchoolMask);
     uint32 damage = target->SpellDamageBonusDone(triggerTarget, GetSpellInfo(), GetAmount(), SPELL_DIRECT_DAMAGE);
     damage = triggerTarget->SpellDamageBonusTaken(target, GetSpellInfo(), damage, SPELL_DIRECT_DAMAGE);
     target->CalculateSpellDamageTaken(&damageInfo, damage, GetSpellInfo());
     Unit::DealDamageMods(damageInfo.target, damageInfo.damage, &damageInfo.absorb);
     target->SendSpellNonMeleeDamageLog(&damageInfo);
     LOG_DEBUG("spells.aura", "AuraEffect::HandleProcTriggerDamageAuraProc: Triggering %u spell damage from aura %u proc", damage, GetId());
     target->DealSpellDamage(&damageInfo, true);
 }
References SpellNonMeleeDamage::absorb, Unit::CalculateSpellDamageTaken(), SpellNonMeleeDamage::damage, Unit::DealDamageMods(), Unit::DealSpellDamage(), GetAmount(), GetId(), ProcEventInfo::GetProcTarget(), GetSpellInfo(), AuraApplication::GetTarget(), Unit::HasUnitState(), Unit::IsImmunedToDamageOrSchool(), LOG_DEBUG, Unit::SendSpellNonMeleeDamageLog(), SendTickImmune(), SPELL_DIRECT_DAMAGE, Unit::SpellDamageBonusDone(), Unit::SpellDamageBonusTaken(), SpellNonMeleeDamage::target, and UNIT_STATE_ISOLATED.
Referenced by HandleProc(), and Unit::ProcDamageAndSpellFor().
HandleProcTriggerSpellAuraProc()
void AuraEffect::HandleProcTriggerSpellAuraProc (AuraApplication * aurApp, ProcEventInfo & eventInfo)
Definition at line 6784 of file SpellAuraEffects.cpp.
 {
     Unit* triggerCaster = aurApp->GetTarget();
     Unit* triggerTarget = eventInfo.GetProcTarget();
     uint32 triggerSpellId = GetSpellInfo()->Effects[GetEffIndex()].TriggerSpell;
     if (SpellInfo const* triggeredSpellInfo = sSpellMgr->GetSpellInfo(triggerSpellId))
     {
         LOG_DEBUG("spells.aura", "AuraEffect::HandleProcTriggerSpellAuraProc: Triggering spell %u from aura %u proc", triggeredSpellInfo->Id, GetId());
         triggerCaster->CastSpell(triggerTarget, triggeredSpellInfo, true, nullptr, this);
     }
     else
     {
         LOG_DEBUG("spells.aura", "AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell %u from aura %u proc, because the spell does not have an entry in Spell.dbc.", triggerSpellId, GetId());
     }
 }
References Unit::CastSpell(), SpellInfo::Effects, GetEffIndex(), GetId(), ProcEventInfo::GetProcTarget(), GetSpellInfo(), AuraApplication::GetTarget(), LOG_DEBUG, and sSpellMgr.
Referenced by HandleProc().
HandleProcTriggerSpellWithValueAuraProc()
void AuraEffect::HandleProcTriggerSpellWithValueAuraProc (AuraApplication * aurApp, ProcEventInfo & eventInfo)
Definition at line 6801 of file SpellAuraEffects.cpp.
 {
     Unit* triggerCaster = aurApp->GetTarget();
     Unit* triggerTarget = eventInfo.GetProcTarget();
     uint32 triggerSpellId = GetSpellInfo()->Effects[m_effIndex].TriggerSpell;
     if (SpellInfo const* triggeredSpellInfo = sSpellMgr->GetSpellInfo(triggerSpellId))
     {
         // used only with EXTRA_LOGS
         (void)triggeredSpellInfo;
         int32 basepoints0 = GetAmount();
         LOG_DEBUG("spells.aura", "AuraEffect::HandleProcTriggerSpellWithValueAuraProc: Triggering spell %u with value %d from aura %u proc", triggeredSpellInfo->Id, basepoints0, GetId());
         triggerCaster->CastCustomSpell(triggerTarget, triggerSpellId, &basepoints0, nullptr, nullptr, true, nullptr, this);
     }
     else
     {
         LOG_DEBUG("spells.aura", "AuraEffect::HandleProcTriggerSpellWithValueAuraProc: Could not trigger spell %u from aura %u proc, because the spell does not have an entry in Spell.dbc.", triggerSpellId, GetId());
     }
 }
References Unit::CastCustomSpell(), SpellInfo::Effects, GetAmount(), GetId(), ProcEventInfo::GetProcTarget(), GetSpellInfo(), AuraApplication::GetTarget(), LOG_DEBUG, m_effIndex, and sSpellMgr.
Referenced by HandleProc().
HandleRaidProcFromChargeAuraProc()
void AuraEffect::HandleRaidProcFromChargeAuraProc (AuraApplication * aurApp, ProcEventInfo & eventInfo)
Definition at line 6842 of file SpellAuraEffects.cpp.
 {
     Unit* target = aurApp->GetTarget();
     uint32 triggerSpellId;
     switch (GetId())
     {
         case 57949:            // Shiver
             triggerSpellId = 57952;
             //animationSpellId = 57951; dummy effects for jump spell have unknown use (see also 41637)
             break;
         case 59978:            // Shiver
             triggerSpellId = 59979;
             break;
         case 43593:            // Cold Stare
             triggerSpellId = 43594;
             break;
         default:
             LOG_DEBUG("spells.aura", "AuraEffect::HandleRaidProcFromChargeAuraProc: received not handled spell: %u", GetId());
             return;
     }
     int32 jumps = GetBase()->GetCharges();
     // current aura expire on proc finish
     GetBase()->SetCharges(0);
     GetBase()->SetUsingCharges(true);
     // next target selection
     if (jumps > 0)
     {
         if (Unit* caster = GetCaster())
         {
             float radius = GetSpellInfo()->Effects[GetEffIndex()].CalcRadius(caster);
             if (Unit* triggerTarget = target->GetNextRandomRaidMemberOrPet(radius))
             {
                 target->CastSpell(triggerTarget, GetSpellInfo(), true, nullptr, this, GetCasterGUID());
                 if (Aura* aura = triggerTarget->GetAura(GetId(), GetCasterGUID()))
                     aura->SetCharges(jumps);
             }
         }
     }
     LOG_DEBUG("spells.aura", "AuraEffect::HandleRaidProcFromChargeAuraProc: Triggering spell %u from aura %u proc", triggerSpellId, GetId());
     target->CastSpell(target, triggerSpellId, true, nullptr, this, GetCasterGUID());
 }
References Unit::CastSpell(), SpellInfo::Effects, GetBase(), GetCaster(), GetCasterGUID(), Aura::GetCharges(), GetEffIndex(), GetId(), Unit::GetNextRandomRaidMemberOrPet(), GetSpellInfo(), AuraApplication::GetTarget(), LOG_DEBUG, Aura::SetCharges(), and Aura::SetUsingCharges().
Referenced by HandleProc().
HandleRaidProcFromChargeWithValueAuraProc()
void AuraEffect::HandleRaidProcFromChargeWithValueAuraProc (AuraApplication * aurApp, ProcEventInfo & eventInfo)
Definition at line 6890 of file SpellAuraEffects.cpp.
 {
     Unit* target = aurApp->GetTarget();
     // Currently only Prayer of Mending
     if (!(GetSpellInfo()->SpellFamilyName == SPELLFAMILY_PRIEST && GetSpellInfo()->SpellFamilyFlags[1] & 0x20))
     {
         LOG_DEBUG("spells.aura", "AuraEffect::HandleRaidProcFromChargeWithValueAuraProc: received not handled spell: %u", GetId());
         return;
     }
     uint32 triggerSpellId = 33110;
     int32 value = GetAmount();
     int32 jumps = GetBase()->GetCharges();
     // current aura expire on proc finish
     GetBase()->SetCharges(0);
     GetBase()->SetUsingCharges(true);
     // next target selection
     if (jumps > 0)
     {
         if (Unit* caster = GetCaster())
         {
             float radius = GetSpellInfo()->Effects[GetEffIndex()].CalcRadius(caster);
             Unit*                                                         triggerTarget = nullptr;
             Acore::MostHPMissingGroupInRange                              u_check(target, radius, 0);
             Acore::UnitLastSearcher<Acore::MostHPMissingGroupInRange>     searcher(target, triggerTarget, u_check);
             Cell::VisitAllObjects(target, searcher, radius);
             if (triggerTarget)
             {
                 target->CastCustomSpell(triggerTarget, GetId(), &value, nullptr, nullptr, true, nullptr, this, GetCasterGUID());
                 if (Aura* aura = triggerTarget->GetAura(GetId(), GetCasterGUID()))
                     aura->SetCharges(jumps);
             }
         }
     }
     LOG_DEBUG("spells.aura", "AuraEffect::HandleRaidProcFromChargeWithValueAuraProc: Triggering spell %u from aura %u proc", triggerSpellId, GetId());
     target->CastCustomSpell(target, triggerSpellId, &value, nullptr, nullptr, true, nullptr, this, GetCasterGUID());
 }
References Unit::CastCustomSpell(), SpellInfo::Effects, GetAmount(), Unit::GetAura(), GetBase(), GetCaster(), GetCasterGUID(), Aura::GetCharges(), GetEffIndex(), GetId(), GetSpellInfo(), AuraApplication::GetTarget(), LOG_DEBUG, Aura::SetCharges(), Aura::SetUsingCharges(), SPELLFAMILY_PRIEST, and Cell::VisitAllObjects().
Referenced by HandleProc().
HandleRangedAmmoHaste()
void AuraEffect::HandleRangedAmmoHaste (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4617 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     target->ApplyAttackTimePercentMod(RANGED_ATTACK, (float)GetAmount(), apply);
 }
References ByteConverter::apply(), Unit::ApplyAttackTimePercentMod(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, GetAmount(), AuraApplication::GetTarget(), Object::GetTypeId(), RANGED_ATTACK, and TYPEID_PLAYER.
HandleShapeshiftBoosts()
void AuraEffect::HandleShapeshiftBoosts (Unit * target, bool apply) const
Definition at line 1189 of file SpellAuraEffects.cpp.
 {
     uint32 spellId = 0;
     uint32 spellId2 = 0;
     //uint32 spellId3 = 0;
     uint32 HotWSpellId = 0;
     switch (GetMiscValue())
     {
         case FORM_CAT:
             spellId = 3025;
             HotWSpellId = 24900;
             break;
         case FORM_TREE:
             spellId = 34123;
             break;
         case FORM_TRAVEL:
             spellId = 5419;
             break;
         case FORM_AQUA:
             spellId = 5421;
             break;
         case FORM_BEAR:
             spellId = 1178;
             spellId2 = 21178;
             HotWSpellId = 24899;
             break;
         case FORM_DIREBEAR:
             spellId = 9635;
             spellId2 = 21178;
             HotWSpellId = 24899;
             break;
         case FORM_BATTLESTANCE:
             spellId = 21156;
             break;
         case FORM_DEFENSIVESTANCE:
             spellId = 7376;
             break;
         case FORM_BERSERKERSTANCE:
             spellId = 7381;
             break;
         case FORM_MOONKIN:
             spellId = 24905;
             spellId2 = 69366;
             break;
         case FORM_FLIGHT:
             spellId = 33948;
             spellId2 = 34764;
             break;
         case FORM_FLIGHT_EPIC:
             spellId  = 40122;
             spellId2 = 40121;
             break;
         case FORM_METAMORPHOSIS:
             spellId  = 54817;
             spellId2 = 54879;
             break;
         case FORM_SPIRITOFREDEMPTION:
             spellId  = 27792;
             spellId2 = 27795;                               // must be second, this important at aura remove to prevent to early iterator invalidation.
             break;
         case FORM_SHADOW:
             spellId = 49868;
             spellId2 = 71167;
             break;
         case FORM_GHOSTWOLF:
             spellId = 67116;
             break;
         case FORM_GHOUL:
         case FORM_AMBIENT:
         case FORM_STEALTH:
         case FORM_CREATURECAT:
         case FORM_CREATUREBEAR:
             break;
         default:
             break;
     }
     Player* player = target->ToPlayer();
     if (apply)
     {
         // Remove cooldown of spells triggered on stance change - they may share cooldown with stance spell
         if (spellId)
         {
             if (player)
                 player->RemoveSpellCooldown(spellId);
             target->CastSpell(target, spellId, true, nullptr, this, target->GetGUID());
         }
         if (spellId2)
         {
             if (player)
                 player->RemoveSpellCooldown(spellId2);
             target->CastSpell(target, spellId2, true, nullptr, this, target->GetGUID());
         }
         if (player)
         {
             const PlayerSpellMap& sp_list = player->GetSpellMap();
             for (PlayerSpellMap::const_iterator itr = sp_list.begin(); itr != sp_list.end(); ++itr)
             {
                 if (itr->second->State == PLAYERSPELL_REMOVED || !itr->second->IsInSpec(player->GetActiveSpec()))
                     continue;
                 if (itr->first == spellId || itr->first == spellId2)
                     continue;
                 SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(itr->first);
                 if (!spellInfo || !spellInfo->HasAttribute(SpellAttr0(SPELL_ATTR0_PASSIVE | SPELL_ATTR0_DO_NOT_DISPLAY)))
                     continue;
                 if (spellInfo->Stances & (1 << (GetMiscValue() - 1)))
                     target->CastSpell(target, itr->first, true, nullptr, this, target->GetGUID());
             }
             // xinef: talent stance auras are not on m_spells map, so iterate talents
             const PlayerTalentMap& tl_list = player->GetTalentMap();
             for (PlayerTalentMap::const_iterator itr = tl_list.begin(); itr != tl_list.end(); ++itr)
             {
                 if (itr->second->State == PLAYERSPELL_REMOVED || !itr->second->IsInSpec(player->GetActiveSpec()))
                     continue;
                 if (itr->first == spellId || itr->first == spellId2)
                     continue;
                 // Xinef: skip talents with effect learn spell
                 SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(itr->first);
                 if (!spellInfo || !spellInfo->HasAttribute(SpellAttr0(SPELL_ATTR0_PASSIVE | SPELL_ATTR0_DO_NOT_DISPLAY)) || spellInfo->HasEffect(SPELL_EFFECT_LEARN_SPELL))
                     continue;
                 if (spellInfo->Stances & (1 << (GetMiscValue() - 1)))
                     target->CastSpell(target, itr->first, true, nullptr, this, target->GetGUID());
             }
             // Also do it for Glyphs
             for (uint32 i = 0; i < MAX_GLYPH_SLOT_INDEX; ++i)
             {
                 if (uint32 glyphId = player->GetGlyph(i))
                 {
                     if (GlyphPropertiesEntry const* glyph = sGlyphPropertiesStore.LookupEntry(glyphId))
                     {
                         SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(glyph->SpellId);
                         if (!spellInfo || !spellInfo->HasAttribute(SpellAttr0(SPELL_ATTR0_PASSIVE | SPELL_ATTR0_DO_NOT_DISPLAY)))
                             continue;
                         if (spellInfo->Stances & (1 << (GetMiscValue() - 1)))
                             target->CastSpell(target, glyph->SpellId, TriggerCastFlags(TRIGGERED_FULL_MASK & ~(TRIGGERED_IGNORE_SHAPESHIFT | TRIGGERED_IGNORE_CASTER_AURASTATE)), nullptr, this, target->GetGUID());
                     }
                 }
             }
             // Leader of the Pack
             if (player->HasTalent(17007, player->GetActiveSpec()))
             {
                 SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(24932);
                 if (spellInfo && spellInfo->Stances & (1 << (GetMiscValue() - 1)))
                     target->CastSpell(target, 24932, true, nullptr, this, target->GetGUID());
             }
             // Improved Barkskin - apply/remove armor bonus due to shapeshift
             if (player->HasTalent(63410, player->GetActiveSpec()) || player->HasTalent(63411, player->GetActiveSpec()))
             {
                 target->RemoveAurasDueToSpell(66530);
                 if (GetMiscValue() == FORM_TRAVEL || GetMiscValue() == FORM_NONE) // "while in Travel Form or while not shapeshifted"
                     target->CastSpell(target, 66530, true);
             }
             // Heart of the Wild
             if (HotWSpellId)
             {
                 // hacky, but the only way as spell family is not SPELLFAMILY_DRUID
                 Unit::AuraEffectList const& mModTotalStatPct = target->GetAuraEffectsByType(SPELL_AURA_MOD_TOTAL_STAT_PERCENTAGE);
                 for (Unit::AuraEffectList::const_iterator i = mModTotalStatPct.begin(); i != mModTotalStatPct.end(); ++i)
                 {
                     // Heart of the Wild
                     if ((*i)->GetSpellInfo()->SpellIconID == 240 && (*i)->GetMiscValue() == STAT_INTELLECT)
                     {
                         int32 HotWMod = (*i)->GetAmount() / 2; // For each 2% Intelligence, you get 1% stamina and 1% attack power.
                         target->CastCustomSpell(target, HotWSpellId, &HotWMod, nullptr, nullptr, true, nullptr, this, target->GetGUID());
                         break;
                     }
                 }
             }
             switch (GetMiscValue())
             {
                 case FORM_CAT:
                     // Savage Roar
                     if (target->GetAuraEffect(SPELL_AURA_DUMMY, SPELLFAMILY_DRUID, 0, 0x10000000, 0))
                         target->CastSpell(target, 62071, true);
                     // Nurturing Instinct
                     if (AuraEffect const* aurEff = target->GetAuraEffect(SPELL_AURA_MOD_SPELL_HEALING_OF_STAT_PERCENT, SPELLFAMILY_DRUID, 2254, 0))
                     {
                         uint32 spellId3 = 0;
                         switch (aurEff->GetId())
{
                             case 33872:
                                 spellId3 = 47179;
                                 break;
                             case 33873:
                                 spellId3 = 47180;
                                 break;
                         }
                         target->CastSpell(target, spellId3, true, nullptr, this, target->GetGUID());
                     }
                     // Master Shapeshifter - Cat
                     if (AuraEffect const* aurEff = target->GetDummyAuraEffect(SPELLFAMILY_GENERIC, 2851, 0))
                     {
                         int32 bp = aurEff->GetAmount();
                         target->CastCustomSpell(target, 48420, &bp, nullptr, nullptr, true);
                     }
                     break;
                 case FORM_DIREBEAR:
                 case FORM_BEAR:
                     // Master Shapeshifter - Bear
                     if (AuraEffect const* aurEff = target->GetDummyAuraEffect(SPELLFAMILY_GENERIC, 2851, 0))
                     {
                         int32 bp = aurEff->GetAmount();
                         target->CastCustomSpell(target, 48418, &bp, nullptr, nullptr, true);
                     }
                     // Survival of the Fittest
                     if (AuraEffect const* aurEff = target->GetAuraEffect(SPELL_AURA_MOD_TOTAL_STAT_PERCENTAGE, SPELLFAMILY_DRUID, 961, 0))
                     {
                         int32 bp = aurEff->GetSpellInfo()->Effects[EFFECT_2].CalcValue();
                         target->CastCustomSpell(target, 62069, &bp, nullptr, nullptr, true, 0, this, target->GetGUID());
                     }
                     break;
                 case FORM_MOONKIN:
                     // Master Shapeshifter - Moonkin
                     if (AuraEffect const* aurEff = target->GetDummyAuraEffect(SPELLFAMILY_GENERIC, 2851, 0))
                     {
                         int32 bp = aurEff->GetAmount();
                         target->CastCustomSpell(target, 48421, &bp, nullptr, nullptr, true);
                     }
                     break;
                 // Master Shapeshifter - Tree of Life
                 case FORM_TREE:
                     if (AuraEffect const* aurEff = target->GetDummyAuraEffect(SPELLFAMILY_GENERIC, 2851, 0))
                     {
                         int32 bp = aurEff->GetAmount();
                         target->CastCustomSpell(target, 48422, &bp, nullptr, nullptr, true);
                     }
                     break;
             }
         }
     }
     else
     {
         if (spellId)
             target->RemoveOwnedAura(spellId);
         if (spellId2)
             target->RemoveOwnedAura(spellId2);
         // Improved Barkskin - apply/remove armor bonus due to shapeshift
         if (player)
         {
             if (player->HasTalent(63410, player->GetActiveSpec()) || player->HasTalent(63411, player->GetActiveSpec()))
             {
                 target->RemoveAurasDueToSpell(66530);
                 target->CastSpell(target, 66530, true);
             }
         }
         const Unit::AuraEffectList& shapeshifts = target->GetAuraEffectsByType(SPELL_AURA_MOD_SHAPESHIFT);
         AuraEffect* newAura = nullptr;
         // Iterate through all the shapeshift auras that the target has, if there is another aura with SPELL_AURA_MOD_SHAPESHIFT, then this aura is being removed due to that one being applied
         for (Unit::AuraEffectList::const_iterator itr = shapeshifts.begin(); itr != shapeshifts.end(); ++itr)
         {
             if ((*itr) != this)
             {
                 newAura = *itr;
                 break;
             }
         }
         // Use the new aura to see on what stance the target will be
         uint32 newStance = (1 << ((newAura ? newAura->GetMiscValue() : 0) - 1));
         Unit::AuraApplicationMap& tAuras = target->GetAppliedAuras();
         for (Unit::AuraApplicationMap::iterator itr = tAuras.begin(); itr != tAuras.end();)
         {
             // If the stances are not compatible with the spell, remove it
             // Xinef: Remove all passive auras, they will be added if needed
             if (itr->second->GetBase()->IsRemovedOnShapeLost(target) && (!(itr->second->GetBase()->GetSpellInfo()->Stances & newStance) || itr->second->GetBase()->IsPassive()))
                 target->RemoveAura(itr);
             else
                 ++itr;
         }
         // Xinef: Remove autoattack spells
         if (Spell* spell = target->GetCurrentSpell(CURRENT_MELEE_SPELL))
             if (spell->GetSpellInfo()->CheckShapeshift(newAura ? newAura->GetMiscValue() : 0) != SPELL_CAST_OK)
                 spell->cancel(true);
     }
 }
References ByteConverter::apply(), Unit::CastCustomSpell(), Unit::CastSpell(), CURRENT_MELEE_SPELL, EFFECT_2, FORM_AMBIENT, FORM_AQUA, FORM_BATTLESTANCE, FORM_BEAR, FORM_BERSERKERSTANCE, FORM_CAT, FORM_CREATUREBEAR, FORM_CREATURECAT, FORM_DEFENSIVESTANCE, FORM_DIREBEAR, FORM_FLIGHT, FORM_FLIGHT_EPIC, FORM_GHOSTWOLF, FORM_GHOUL, FORM_METAMORPHOSIS, FORM_MOONKIN, FORM_NONE, FORM_SHADOW, FORM_SPIRITOFREDEMPTION, FORM_STEALTH, FORM_TRAVEL, FORM_TREE, Player::GetActiveSpec(), Unit::GetAppliedAuras(), Unit::GetAuraEffect(), Unit::GetAuraEffectsByType(), Unit::GetCurrentSpell(), Unit::GetDummyAuraEffect(), Player::GetGlyph(), Object::GetGUID(), GetMiscValue(), Player::GetSpellMap(), Player::GetTalentMap(), SpellInfo::HasAttribute(), SpellInfo::HasEffect(), Player::HasTalent(), MAX_GLYPH_SLOT_INDEX, PLAYERSPELL_REMOVED, Unit::RemoveAura(), Unit::RemoveAurasDueToSpell(), Unit::RemoveOwnedAura(), Player::RemoveSpellCooldown(), sGlyphPropertiesStore, SPELL_ATTR0_DO_NOT_DISPLAY, SPELL_ATTR0_PASSIVE, SPELL_AURA_DUMMY, SPELL_AURA_MOD_SHAPESHIFT, SPELL_AURA_MOD_SPELL_HEALING_OF_STAT_PERCENT, SPELL_AURA_MOD_TOTAL_STAT_PERCENTAGE, SPELL_CAST_OK, SPELL_EFFECT_LEARN_SPELL, SPELLFAMILY_DRUID, SPELLFAMILY_GENERIC, sSpellMgr, SpellInfo::Stances, STAT_INTELLECT, Object::ToPlayer(), TRIGGERED_FULL_MASK, TRIGGERED_IGNORE_CASTER_AURASTATE, and TRIGGERED_IGNORE_SHAPESHIFT.
Referenced by HandleAuraModShapeshift().
HandleShieldBlockValue()
void AuraEffect::HandleShieldBlockValue (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 4877 of file SpellAuraEffects.cpp.
 {
     if (!(mode & (AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK | AURA_EFFECT_HANDLE_STAT)))
         return;
     Unit* target = aurApp->GetTarget();
     BaseModType modType = FLAT_MOD;
     if (GetAuraType() == SPELL_AURA_MOD_SHIELD_BLOCKVALUE_PCT)
         modType = PCT_MOD;
     if (target->GetTypeId() == TYPEID_PLAYER)
         target->ToPlayer()->HandleBaseModValue(SHIELD_BLOCK_VALUE, modType, float(GetAmount()), apply);
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_CHANGE_AMOUNT_MASK, AURA_EFFECT_HANDLE_STAT, FLAT_MOD, GetAmount(), GetAuraType(), AuraApplication::GetTarget(), Object::GetTypeId(), Player::HandleBaseModValue(), PCT_MOD, SHIELD_BLOCK_VALUE, SPELL_AURA_MOD_SHIELD_BLOCKVALUE_PCT, Object::ToPlayer(), and TYPEID_PLAYER.
HandleSpiritOfRedemption()
void AuraEffect::HandleSpiritOfRedemption (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 1706 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_REAL))
         return;
     Unit* target = aurApp->GetTarget();
     if (target->GetTypeId() != TYPEID_PLAYER)
         return;
     // prepare spirit state
     if (apply)
     {
         // disable breath/etc timers
         target->ToPlayer()->StopMirrorTimers();
         // set stand state (expected in this form)
         if (!target->IsStandState())
             target->SetStandState(UNIT_STAND_STATE_STAND);
         target->SetHealth(1);
     }
     // die at aura end
     else if (target->IsAlive())
         // call functions which may have additional effects after chainging state of unit
         target->setDeathState(JUST_DIED);
     // xinef: damage immunity spell, not needed because of 93 aura (adds non_attackable state)
     // xinef: probably blizzard added it just in case in wotlk (id > 46000)
     if (apply)
         target->CastSpell(target, 62371, true);
     else
         target->RemoveAurasDueToSpell(62371);
 }
References ByteConverter::apply(), AURA_EFFECT_HANDLE_REAL, Unit::CastSpell(), AuraApplication::GetTarget(), Object::GetTypeId(), Unit::IsAlive(), Unit::IsStandState(), JUST_DIED, Unit::RemoveAurasDueToSpell(), Unit::setDeathState(), Unit::SetHealth(), Unit::SetStandState(), Player::StopMirrorTimers(), Object::ToPlayer(), TYPEID_PLAYER, and UNIT_STAND_STATE_STAND.
HandleUnused()
void AuraEffect::HandleUnused (AuraApplication const * , uint8 , bool) const inline
Definition at line 149 of file SpellAuraEffects.h.
     {
         // useless
     }
HandleWaterBreathing()
void AuraEffect::HandleWaterBreathing (AuraApplication const * aurApp, uint8 mode, bool apply) const
Definition at line 2944 of file SpellAuraEffects.cpp.
 {
     if (!(mode & AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK))
         return;
     Unit* target = aurApp->GetTarget();
     // update timers in client
     if (target->GetTypeId() == TYPEID_PLAYER)
         target->ToPlayer()->UpdateMirrorTimers();
 }
References AURA_EFFECT_HANDLE_SEND_FOR_CLIENT_MASK, AuraApplication::GetTarget(), Object::GetTypeId(), Object::ToPlayer(), TYPEID_PLAYER, and Player::UpdateMirrorTimers().
HasSpellClassMask()
bool AuraEffect::HasSpellClassMask () const
Definition at line 1076 of file SpellAuraEffects.cpp.
 {
     return m_spellInfo->Effects[m_effIndex].SpellClassMask;
 }
References SpellInfo::Effects, m_effIndex, and m_spellInfo.
IsAffectedOnSpell()
bool AuraEffect::IsAffectedOnSpell (SpellInfo const * spell) const
Definition at line 1062 of file SpellAuraEffects.cpp.
 {
     if (!spell)
         return false;
     // Check family name
     if (spell->SpellFamilyName != m_spellInfo->SpellFamilyName)
         return false;
     // Check EffectClassMask
     if (m_spellInfo->Effects[m_effIndex].SpellClassMask & spell->SpellFamilyFlags)
         return true;
     return false;
 }
References SpellInfo::Effects, m_effIndex, m_spellInfo, SpellInfo::SpellFamilyFlags, and SpellInfo::SpellFamilyName.
IsPeriodic()
bool AuraEffect::IsPeriodic () const inline
Definition at line 84 of file SpellAuraEffects.h.
 { return m_isPeriodic; }
References m_isPeriodic.
Referenced by AuraApplication::_HandleEffect(), and Spell::prepare().
PeriodicTick()
void AuraEffect::PeriodicTick (AuraApplication * aurApp, Unit * caster) const
Definition at line 1087 of file SpellAuraEffects.cpp.
 {
     bool prevented = GetBase()->CallScriptEffectPeriodicHandlers(this, aurApp);
     if (prevented)
         return;
     Unit* target = aurApp->GetTarget();
     switch (GetAuraType())
     {
         case SPELL_AURA_PERIODIC_DUMMY:
             HandlePeriodicDummyAuraTick(target, caster);
             break;
         case SPELL_AURA_PERIODIC_TRIGGER_SPELL:
             HandlePeriodicTriggerSpellAuraTick(target, caster);
             break;
         case SPELL_AURA_PERIODIC_TRIGGER_SPELL_WITH_VALUE:
             HandlePeriodicTriggerSpellWithValueAuraTick(target, caster);
             break;
         case SPELL_AURA_PERIODIC_DAMAGE:
         case SPELL_AURA_PERIODIC_DAMAGE_PERCENT:
             HandlePeriodicDamageAurasTick(target, caster);
             break;
         case SPELL_AURA_PERIODIC_LEECH:
             HandlePeriodicHealthLeechAuraTick(target, caster);
             break;
         case SPELL_AURA_PERIODIC_HEALTH_FUNNEL:
             HandlePeriodicHealthFunnelAuraTick(target, caster);
             break;
         case SPELL_AURA_PERIODIC_HEAL:
         case SPELL_AURA_OBS_MOD_HEALTH:
             HandlePeriodicHealAurasTick(target, caster);
             break;
         case SPELL_AURA_PERIODIC_MANA_LEECH:
             HandlePeriodicManaLeechAuraTick(target, caster);
             break;
         case SPELL_AURA_OBS_MOD_POWER:
             HandleObsModPowerAuraTick(target, caster);
             break;
         case SPELL_AURA_PERIODIC_ENERGIZE:
             HandlePeriodicEnergizeAuraTick(target, caster);
             break;
         case SPELL_AURA_POWER_BURN:
             HandlePeriodicPowerBurnAuraTick(target, caster);
             break;
         default:
             break;
     }
 }
References Aura::CallScriptEffectPeriodicHandlers(), GetAuraType(), GetBase(), AuraApplication::GetTarget(), HandleObsModPowerAuraTick(), HandlePeriodicDamageAurasTick(), HandlePeriodicDummyAuraTick(), HandlePeriodicEnergizeAuraTick(), HandlePeriodicHealAurasTick(), HandlePeriodicHealthFunnelAuraTick(), HandlePeriodicHealthLeechAuraTick(), HandlePeriodicManaLeechAuraTick(), HandlePeriodicPowerBurnAuraTick(), HandlePeriodicTriggerSpellAuraTick(), HandlePeriodicTriggerSpellWithValueAuraTick(), SPELL_AURA_OBS_MOD_HEALTH, SPELL_AURA_OBS_MOD_POWER, SPELL_AURA_PERIODIC_DAMAGE, SPELL_AURA_PERIODIC_DAMAGE_PERCENT, SPELL_AURA_PERIODIC_DUMMY, SPELL_AURA_PERIODIC_ENERGIZE, SPELL_AURA_PERIODIC_HEAL, SPELL_AURA_PERIODIC_HEALTH_FUNNEL, SPELL_AURA_PERIODIC_LEECH, SPELL_AURA_PERIODIC_MANA_LEECH, SPELL_AURA_PERIODIC_TRIGGER_SPELL, SPELL_AURA_PERIODIC_TRIGGER_SPELL_WITH_VALUE, and SPELL_AURA_POWER_BURN.
Referenced by Update().
RecalculateAmount() [1/2]
void AuraEffect::RecalculateAmount () inline
Definition at line 68 of file SpellAuraEffects.h.
 { if (!CanBeRecalculated()) return; ChangeAmount(CalculateAmount(GetCaster()), false); }
References CalculateAmount(), CanBeRecalculated(), ChangeAmount(), and GetCaster().
Referenced by spell_dk_pet_scaling::HandlePeriodic(), spell_pet_hit_expertise_scalling::HandlePeriodic(), spell_hun_generic_scaling::HandlePeriodic(), spell_mage_pet_scaling::HandlePeriodic(), spell_sha_feral_spirit_scaling::HandlePeriodic(), spell_warl_improved_demonic_tactics::HandlePeriodic(), spell_warl_demonic_knowledge::HandlePeriodic(), spell_warl_generic_scaling::HandlePeriodic(), Aura::RecalculateAmountOfEffects(), and Aura::SetLoadedState().
RecalculateAmount() [2/2]
void AuraEffect::RecalculateAmount (Unit * caster) inline
Definition at line 69 of file SpellAuraEffects.h.
 { if (!CanBeRecalculated()) return; ChangeAmount(CalculateAmount(caster), false); }
References CalculateAmount(), CanBeRecalculated(), and ChangeAmount().
ResetPeriodic()
void AuraEffect::ResetPeriodic (bool resetPeriodicTimer = false) inline
Definition at line 81 of file SpellAuraEffects.h.
 { if (resetPeriodicTimer) m_periodicTimer = m_amplitude; m_tickNumber = 0;}
References m_amplitude, m_periodicTimer, and m_tickNumber.
Referenced by Unit::HandleAuraProc().
ResetTicks()
void AuraEffect::ResetTicks () inline
Definition at line 82 of file SpellAuraEffects.h.
 { m_tickNumber = 0; }
References m_tickNumber.
SendTickImmune()
void AuraEffect::SendTickImmune (Unit * target, Unit * caster) const
Definition at line 1081 of file SpellAuraEffects.cpp.
 {
     if (caster)
         caster->SendSpellDamageImmune(target, m_spellInfo->Id);
 }
References SpellInfo::Id, m_spellInfo, and Unit::SendSpellDamageImmune().
Referenced by HandleObsModPowerAuraTick(), HandlePeriodicDamageAurasTick(), HandlePeriodicEnergizeAuraTick(), HandlePeriodicHealAurasTick(), HandlePeriodicHealthFunnelAuraTick(), HandlePeriodicHealthLeechAuraTick(), HandlePeriodicManaLeechAuraTick(), HandlePeriodicPowerBurnAuraTick(), and HandleProcTriggerDamageAuraProc().
SetAmount()
void AuraEffect::SetAmount (int32 amount) inline
Definition at line 58 of file SpellAuraEffects.h.
 { m_amount = amount; m_canBeRecalculated = false;}
References m_amount, and m_canBeRecalculated.
Referenced by spell_dru_savage_defense::Absorb(), Unit::CalcAbsorbResist(), ChangeAmount(), Aura::HandleAuraSpecificMods(), Unit::HandleDummyAuraProc(), spell_hallows_end_base_fire::spell_hallows_end_base_fire_AuraScript::HandleEffectPeriodicUpdate(), spell_gen_burn_brutallus::HandleEffectPeriodicUpdate(), spell_putricide_unbound_plague_dmg::spell_putricide_unbound_plague_dmg_AuraScript::HandlePeriodic(), spell_hun_sniper_training::HandleUpdatePeriodic(), spell_kalecgos_curse_of_boundless_agony::spell_kalecgos_curse_of_boundless_agony_AuraScript::OnPeriodic(), spell_the_lich_king_infest::spell_the_lich_king_infest_AuraScript::OnUpdate(), spell_optic_link::spell_optic_linkAuraScript::PrepareAuraScript(), Unit::ProcDamageAndSpellFor(), Aura::SetLoadedState(), and spell_black_temple_shadow_inferno::spell_black_temple_shadow_inferno_AuraScript::Update().
SetCanBeRecalculated()
void AuraEffect::SetCanBeRecalculated (bool val) inline
Definition at line 71 of file SpellAuraEffects.h.
 { m_canBeRecalculated = val; }
References m_canBeRecalculated.
Referenced by Aura::SetLoadedState().
SetCritChance()
void AuraEffect::SetCritChance (float crit) inline
Definition at line 101 of file SpellAuraEffects.h.
 { m_critChance = crit; }
References m_critChance.
Referenced by CalculatePeriodicData().
SetEnabled()
void AuraEffect::SetEnabled (bool enabled) inline
Definition at line 110 of file SpellAuraEffects.h.
 { m_isAuraEnabled = enabled; }
References m_isAuraEnabled.
Referenced by AuraApplication::_HandleEffect().
SetOldAmount()
void AuraEffect::SetOldAmount (int32 amount) inline
Definition at line 109 of file SpellAuraEffects.h.
 { m_oldAmount = amount; }
References m_oldAmount.
Referenced by CalculateAmount().
SetPeriodic()
void AuraEffect::SetPeriodic (bool isPeriodic) inline
Definition at line 85 of file SpellAuraEffects.h.
 { m_isPeriodic = isPeriodic; }
References m_isPeriodic.
SetPeriodicTimer()
void AuraEffect::SetPeriodicTimer (int32 periodicTimer) inline
Definition at line 61 of file SpellAuraEffects.h.
 { m_periodicTimer = periodicTimer; }
References m_periodicTimer.
Referenced by spell_dreamwalker_decay_periodic_timer::spell_dreamwalker_decay_periodic_timer_AuraScript::DecayPeriodicTimer(), spell_muru_summon_blood_elves_periodic::spell_muru_summon_blood_elves_periodic_AuraScript::HandleApply(), spell_gen_baby_murloc_passive::HandleApply(), spell_gen_baby_murloc_passive::HandlePeriodicTimer(), spell_hadronox_summon_periodic::spell_hadronox_summon_periodic_AuraScript::OnApply(), and spell_item_goblin_gumbo_kettle::Update().
Update()
void AuraEffect::Update (uint32 diff, Unit * caster)
Definition at line 889 of file SpellAuraEffects.cpp.
 {
     if (m_isPeriodic && (GetBase()->GetDuration() >= 0 || GetBase()->IsPassive() || GetBase()->IsPermanent()))
     {
         m_periodicTimer -= int32(diff);
         while (m_periodicTimer <= 0)
         {
             ++m_tickNumber;
             // update before tick (aura can be removed in TriggerSpell or PeriodicTick calls)
             m_periodicTimer += m_amplitude;
             UpdatePeriodic(caster);
             std::list<AuraApplication*> effectApplications;
             GetApplicationList(effectApplications);
             // tick on targets of effects
             for (std::list<AuraApplication*>::const_iterator apptItr = effectApplications.begin(); apptItr != effectApplications.end(); ++apptItr)
                 if ((*apptItr)->HasEffect(GetEffIndex()))
                     PeriodicTick(*apptItr, caster);
         }
     }
 }
References diff(), GetApplicationList(), GetBase(), Aura::GetDuration(), GetEffIndex(), Aura::IsPassive(), Aura::IsPermanent(), m_amplitude, m_isPeriodic, m_periodicTimer, m_tickNumber, PeriodicTick(), and UpdatePeriodic().
Referenced by Aura::UpdateOwner().
UpdatePeriodic()
void AuraEffect::UpdatePeriodic (Unit * caster)
Definition at line 912 of file SpellAuraEffects.cpp.
 {
     switch (GetAuraType())
     {
         case SPELL_AURA_PERIODIC_DUMMY:
             switch (GetSpellInfo()->SpellFamilyName)
             {
                 case SPELLFAMILY_GENERIC:
                     switch (GetId())
                     {
                         // Drink
                         case 430:
                         case 431:
                         case 432:
                         case 1133:
                         case 1135:
                         case 1137:
                         case 10250:
                         case 22734:
                         case 27089:
                         case 34291:
                         case 43182:
                         case 43183:
                         case 46755:
                         case 49472: // Drink Coffee
                         case 57073:
                         case 61830:
                             if (!caster || caster->GetTypeId() != TYPEID_PLAYER)
                                 return;
                             // Get SPELL_AURA_MOD_POWER_REGEN aura from spell
                             if (AuraEffect* aurEff = GetBase()->GetEffect(0))
{
                                 if (aurEff->GetAuraType() != SPELL_AURA_MOD_POWER_REGEN)
{
                                     m_isPeriodic = false;
                                     LOG_ERROR("spells.aura.effect", "Aura %d structure has been changed - first aura is no longer SPELL_AURA_MOD_POWER_REGEN", GetId());
                                 }
                                 else
{
                                     // default case - not in arena
                                     if (!caster->ToPlayer()->InArena())
{
                                         aurEff->ChangeAmount(GetAmount());
                                         m_isPeriodic = false;
                                     }
                                     else
{
                                         // **********************************************
                                         // This feature uses only in arenas
                                         // **********************************************
                                         // Here need increase mana regen per tick (6 second rule)
                                         // on 0 tick -   0  (handled in 2 second)
                                         // on 1 tick - 166% (handled in 4 second)
                                         // on 2 tick - 133% (handled in 6 second)
                                         // Apply bonus for 1 - 4 tick
                                         switch (m_tickNumber)
{
                                             case 1:   // 0%
                                                 aurEff->ChangeAmount(0);
                                                 break;
                                             case 2:   // 166%
                                                 aurEff->ChangeAmount(GetAmount() * 5 / 3);
                                                 break;
                                             case 3:   // 133%
                                                 aurEff->ChangeAmount(GetAmount() * 4 / 3);
                                                 break;
                                             default:  // 100% - normal regen
                                                 aurEff->ChangeAmount(GetAmount());
                                                 // No need to update after 4th tick
                                                 m_isPeriodic = false;
                                                 break;
                                         }
                                     }
                                 }
                             }
                             break;
                         case 58549: // Tenacity
                         case 59911: // Tenacity (vehicle)
                             GetBase()->RefreshDuration();
                             break;
                         case 66823:
                         case 67618:
                         case 67619:
                         case 67620: // Paralytic Toxin
                             // Get 0 effect aura
                             if (AuraEffect* slow = GetBase()->GetEffect(0))
{
                                 int32 newAmount = slow->GetAmount() - 10;
                                 if (newAmount < -100)
                                     newAmount = -100;
                                 slow->ChangeAmount(newAmount);
                             }
                             break;
                         case 66020:
                             // Get 0 effect aura
                             if (AuraEffect* slow = GetBase()->GetEffect(0))
{
                                 int32 newAmount = slow->GetAmount() + GetAmount();
                                 if (newAmount > 0)
                                     newAmount = 0;
                                 slow->ChangeAmount(newAmount);
                             }
                             break;
                         default:
                             break;
                     }
                     break;
                 default:
                     break;
             }
         default:
             break;
     }
     GetBase()->CallScriptEffectUpdatePeriodicHandlers(this);
 }
References Aura::CallScriptEffectUpdatePeriodicHandlers(), GetAmount(), GetAuraType(), GetBase(), Aura::GetEffect(), GetId(), GetSpellInfo(), Object::GetTypeId(), Player::InArena(), LOG_ERROR, m_isPeriodic, m_tickNumber, Aura::RefreshDuration(), SPELL_AURA_MOD_POWER_REGEN, SPELL_AURA_PERIODIC_DUMMY, SPELLFAMILY_GENERIC, Object::ToPlayer(), and TYPEID_PLAYER.
Referenced by Update().
Friends And Related Function Documentation
Aura::_InitEffects
void Aura::_InitEffects (uint8 effMask, Unit * caster, int32 * baseAmount) friend
Unit::_TryStackingOrRefreshingExistingAura
Aura* Unit::_TryStackingOrRefreshingExistingAura (SpellInfo const * newAura, uint8 effMask, Unit * caster, int32 * baseAmount, Item * castItem, ObjectGuid casterGUID, bool noPeriodicReset) friend
Member Data Documentation
m_amount
int32 AuraEffect::m_amount private
Definition at line 120 of file SpellAuraEffects.h.
Referenced by AuraEffect(), ChangeAmount(), GetAmount(), GetForcedAmount(), HandleAuraControlVehicle(), HandleAuraConvertRune(), HandleAuraLinked(), HandleChannelDeathItem(), HandleForceReaction(), HandleModPercentStat(), HandleObsModPowerAuraTick(), HandlePeriodicDummyAuraTick(), HandlePeriodicEnergizeAuraTick(), HandlePeriodicHealAurasTick(), HandlePeriodicManaLeechAuraTick(), HandlePeriodicPowerBurnAuraTick(), HandlePeriodicTriggerSpellAuraTick(), and SetAmount().
m_amplitude
int32 AuraEffect::m_amplitude private
Definition at line 134 of file SpellAuraEffects.h.
Referenced by CalculatePeriodic(), GetAmplitude(), GetTotalTicks(), ResetPeriodic(), and Update().
m_applyResilience
bool AuraEffect::m_applyResilience private
Definition at line 118 of file SpellAuraEffects.h.
Referenced by AuraEffect(), and CanApplyResilience().
m_auraGroup
uint32 AuraEffect::m_auraGroup private
Definition at line 125 of file SpellAuraEffects.h.
Referenced by AuraEffect(), and GetAuraGroup().
m_base
Aura* const AuraEffect::m_base private
Definition at line 113 of file SpellAuraEffects.h.
Referenced by GetBase().
m_baseAmount
int32 const AuraEffect::m_baseAmount private
Definition at line 116 of file SpellAuraEffects.h.
Referenced by CalculateAmount(), GetBaseAmount(), and HandlePeriodicHealAurasTick().
m_canBeRecalculated
bool AuraEffect::m_canBeRecalculated private
Definition at line 138 of file SpellAuraEffects.h.
Referenced by CalculateAmount(), CanBeRecalculated(), SetAmount(), and SetCanBeRecalculated().
m_casterLevel
uint8 AuraEffect::m_casterLevel private
Definition at line 119 of file SpellAuraEffects.h.
Referenced by AuraEffect(), and GetCasterLevel().
m_channelData
ChannelTargetData* AuraEffect::m_channelData private
Definition at line 129 of file SpellAuraEffects.h.
Referenced by AuraEffect(), HandlePeriodicTriggerSpellAuraTick(), HandlePeriodicTriggerSpellWithValueAuraTick(), and ~AuraEffect().
m_critChance
float AuraEffect::m_critChance private
Definition at line 121 of file SpellAuraEffects.h.
Referenced by GetCritChance(), and SetCritChance().
m_effIndex
uint8 const AuraEffect::m_effIndex private
Definition at line 137 of file SpellAuraEffects.h.
Referenced by CalculateAmount(), CalculatePeriodic(), GetAuraType(), GetEffIndex(), GetMiscValue(), GetMiscValueB(), HandleAuraDummy(), HandleAuraLinked(), HandleChannelDeathItem(), HandlePeriodicHealAurasTick(), HandlePeriodicHealthLeechAuraTick(), HandlePeriodicTriggerSpellWithValueAuraTick(), HandleProcTriggerSpellWithValueAuraProc(), HasSpellClassMask(), and IsAffectedOnSpell().
m_isAuraEnabled
bool AuraEffect::m_isAuraEnabled private
Definition at line 127 of file SpellAuraEffects.h.
Referenced by GetAmount(), and SetEnabled().
m_isPeriodic
bool AuraEffect::m_isPeriodic private
Definition at line 139 of file SpellAuraEffects.h.
Referenced by CalculatePeriodic(), IsPeriodic(), SetPeriodic(), Update(), and UpdatePeriodic().
m_oldAmount
int32 AuraEffect::m_oldAmount private
Definition at line 126 of file SpellAuraEffects.h.
Referenced by GetOldAmount(), and SetOldAmount().
m_pctMods
float AuraEffect::m_pctMods private
Definition at line 122 of file SpellAuraEffects.h.
Referenced by CalculatePeriodicData(), and GetPctMods().
m_periodicTimer
int32 AuraEffect::m_periodicTimer private
Definition at line 133 of file SpellAuraEffects.h.
Referenced by CalculatePeriodic(), GetPeriodicTimer(), ResetPeriodic(), SetPeriodicTimer(), and Update().
m_spellInfo
SpellInfo const* const AuraEffect::m_spellInfo private
Definition at line 115 of file SpellAuraEffects.h.
Referenced by CalculateAmount(), CalculatePeriodic(), CalculatePeriodicData(), CleanupTriggeredSpells(), GetAuraType(), GetId(), GetMiscValue(), GetMiscValueB(), GetSpellInfo(), HandleAuraDummy(), HandleAuraLinked(), HandleAuraModDispelImmunity(), HandleAuraModShapeshift(), HandleFarSight(), HandleModTotalPercentStat(), HandlePeriodicDamageAurasTick(), HandlePeriodicEnergizeAuraTick(), HandlePeriodicHealAurasTick(), HandlePeriodicHealthLeechAuraTick(), HandlePeriodicManaLeechAuraTick(), HandlePeriodicTriggerSpellAuraTick(), HandlePeriodicTriggerSpellWithValueAuraTick(), HasSpellClassMask(), IsAffectedOnSpell(), and SendTickImmune().
m_spellmod
SpellModifier* AuraEffect::m_spellmod private
Definition at line 131 of file SpellAuraEffects.h.
Referenced by ApplySpellMod(), CalculateSpellMod(), GetSpellModifier(), and ~AuraEffect().
m_tickNumber
uint32 AuraEffect::m_tickNumber private
Definition at line 135 of file SpellAuraEffects.h.
Referenced by CalculatePeriodic(), GetTickNumber(), HandlePeriodicDamageAurasTick(), HandlePeriodicTriggerSpellAuraTick(), ResetPeriodic(), ResetTicks(), Update(), and UpdatePeriodic().
The documentation for this class was generated from the following files:
src/server/game/Spells/Auras/SpellAuraEffects.h
src/server/game/Spells/Auras/SpellAuraEffects.cpp