Azerotcore-wotlk: Guild Class Reference
Guild Class Reference
#include <Guild.h>
Classes
class BankEventLogEntry
class BankMoveItemData
class BankTab
class EventLogEntry
class LogEntry
class LogHolder
class Member
class MoveItemData
class PlayerMoveItemData
class RankInfo
Public Member Functions
const Member * GetMember (ObjectGuid guid) const
Member * GetMember (ObjectGuid guid)
Member * GetMember (std::string const &name)
Guild ()
~Guild ()
bool Create (Player *pLeader, std::string const &name)
void Disband ()
uint32 GetId () const
ObjectGuid GetLeaderGUID () const
std::string const & GetName () const
std::string const & GetMOTD () const
std::string const & GetInfo () const
void HandleRoster (WorldSession *session)
void HandleQuery (WorldSession *session)
void HandleSetMOTD (WorldSession *session, std::string const &motd)
void HandleSetInfo (WorldSession *session, std::string const &info)
void HandleSetEmblem (WorldSession *session, const EmblemInfo &emblemInfo)
void HandleSetLeader (WorldSession *session, std::string const &name)
void HandleSetBankTabInfo (WorldSession *session, uint8 tabId, std::string const &name, std::string const &icon)
void HandleSetMemberNote (WorldSession *session, std::string const &name, std::string const &note, bool officer)
void HandleSetRankInfo (WorldSession *session, uint8 rankId, std::string const &name, uint32 rights, uint32 moneyPerDay, GuildBankRightsAndSlotsVec rightsAndSlots)
void HandleBuyBankTab (WorldSession *session, uint8 tabId)
void HandleInviteMember (WorldSession *session, std::string const &name)
void HandleAcceptMember (WorldSession *session)
void HandleLeaveMember (WorldSession *session)
void HandleRemoveMember (WorldSession *session, std::string const &name)
void HandleUpdateMemberRank (WorldSession *session, std::string const &name, bool demote)
void HandleAddNewRank (WorldSession *session, std::string const &name)
void HandleRemoveRank (WorldSession *session, uint8 rankId)
void HandleRemoveLowestRank (WorldSession *session)
void HandleMemberDepositMoney (WorldSession *session, uint32 amount)
bool HandleMemberWithdrawMoney (WorldSession *session, uint32 amount, bool repair=false)
void HandleMemberLogout (WorldSession *session)
void HandleDisband (WorldSession *session)
void UpdateMemberData (Player *player, uint8 dataid, uint32 value)
void OnPlayerStatusChange (Player *player, uint32 flag, bool state)
void SendInfo (WorldSession *session) const
void SendEventLog (WorldSession *session) const
void SendBankLog (WorldSession *session, uint8 tabId) const
void SendBankTabsInfo (WorldSession *session, bool showTabs=false) const
void SendBankTabData (WorldSession *session, uint8 tabId) const
void SendBankTabText (WorldSession *session, uint8 tabId) const
void SendPermissions (WorldSession *session) const
void SendMoneyInfo (WorldSession *session) const
void SendLoginInfo (WorldSession *session)
bool LoadFromDB (Field *fields)
void LoadRankFromDB (Field *fields)
bool LoadMemberFromDB (Field *fields)
bool LoadEventLogFromDB (Field *fields)
void LoadBankRightFromDB (Field *fields)
void LoadBankTabFromDB (Field *fields)
bool LoadBankEventLogFromDB (Field *fields)
bool LoadBankItemFromDB (Field *fields)
bool Validate ()
void BroadcastToGuild (WorldSession *session, bool officerOnly, std::string const &msg, uint32 language=LANG_UNIVERSAL) const
void BroadcastPacketToRank (WorldPacket *packet, uint8 rankId) const
void BroadcastPacket (WorldPacket *packet) const
void MassInviteToEvent (WorldSession *session, uint32 minLevel, uint32 maxLevel, uint32 minRank)
template<class Do >
void BroadcastWorker (Do &_do, Player *except=nullptr)
bool AddMember (ObjectGuid guid, uint8 rankId=GUILD_RANK_NONE)
void DeleteMember (ObjectGuid guid, bool isDisbanding=false, bool isKicked=false, bool canDeleteGuild=false)
bool ChangeMemberRank (ObjectGuid guid, uint8 newRank)
void SwapItems (Player *player, uint8 tabId, uint8 slotId, uint8 destTabId, uint8 destSlotId, uint32 splitedAmount)
void SwapItemsWithInventory (Player *player, bool toChar, uint8 tabId, uint8 slotId, uint8 playerBag, uint8 playerSlotId, uint32 splitedAmount)
uint64 GetTotalBankMoney () const
uint32 GetMemberCount () const
time_t GetCreatedDate () const
void SetBankTabText (uint8 tabId, std::string const &text)
void ResetTimes ()
bool ModifyBankMoney (CharacterDatabaseTransaction trans, const uint64 &amount, bool add)
uint32 GetMemberSize () const
Static Public Member Functions
static void SendCommandResult (WorldSession *session, GuildCommandType type, GuildCommandError errCode, std::string const &param="")
static void SendSaveEmblemResult (WorldSession *session, GuildEmblemError errCode)
Protected Attributes
uint32 m_id
std::string m_name
ObjectGuid m_leaderGuid
std::string m_motd
std::string m_info
time_t m_createdDate
EmblemInfo m_emblemInfo
uint32 m_accountsNumber
uint64 m_bankMoney
Ranks m_ranks
Members m_members
BankTabs m_bankTabs
LogHolder * m_eventLog
LogHolder * m_bankEventLog [GUILD_BANK_MAX_TABS+1]
Private Types
typedef std::list< LogEntry * > GuildLog
typedef std::unordered_map< ObjectGuid, Member * > Members
typedef std::vector< RankInfo > Ranks
typedef std::vector< BankTab * > BankTabs
Private Member Functions
uint8 _GetRanksSize () const
const RankInfo * GetRankInfo (uint8 rankId) const
RankInfo * GetRankInfo (uint8 rankId)
bool _HasRankRight (Player *player, uint32 right) const
uint8 _GetLowestRankId () const
uint8 _GetPurchasedTabsSize () const
BankTab * GetBankTab (uint8 tabId)
const BankTab * GetBankTab (uint8 tabId) const
void _DeleteMemberFromDB (ObjectGuid::LowType lowguid) const
void _CreateLogHolders ()
void _CreateNewBankTab ()
void _CreateDefaultGuildRanks (LocaleConstant loc)
bool _CreateRank (std::string const &name, uint32 rights)
void _UpdateAccountsNumber ()
bool _IsLeader (Player *player) const
void _DeleteBankItems (CharacterDatabaseTransaction trans, bool removeItemsFromDB=false)
bool _ModifyBankMoney (CharacterDatabaseTransaction trans, uint64 amount, bool add)
void _SetLeaderGUID (Member *pLeader)
void _SetRankBankMoneyPerDay (uint8 rankId, uint32 moneyPerDay)
void _SetRankBankTabRightsAndSlots (uint8 rankId, GuildBankRightsAndSlots rightsAndSlots, bool saveToDB=true)
int8 _GetRankBankTabRights (uint8 rankId, uint8 tabId) const
uint32 _GetRankRights (uint8 rankId) const
int32 _GetRankBankMoneyPerDay (uint8 rankId) const
int32 _GetRankBankTabSlotsPerDay (uint8 rankId, uint8 tabId) const
std::string _GetRankName (uint8 rankId) const
int32 _GetMemberRemainingSlots (Member const *member, uint8 tabId) const
int32 _GetMemberRemainingMoney (Member const *member) const
void _UpdateMemberWithdrawSlots (CharacterDatabaseTransaction trans, ObjectGuid guid, uint8 tabId)
bool _MemberHasTabRights (ObjectGuid guid, uint8 tabId, uint32 rights) const
void _LogEvent (GuildEventLogTypes eventType, ObjectGuid playerGuid1, ObjectGuid playerGuid2=ObjectGuid::Empty, uint8 newRank=0)
void _LogBankEvent (CharacterDatabaseTransaction trans, GuildBankEventLogTypes eventType, uint8 tabId, ObjectGuid playerGuid, uint32 itemOrMoney, uint16 itemStackCount=0, uint8 destTabId=0)
Item * _GetItem (uint8 tabId, uint8 slotId) const
void _RemoveItem (CharacterDatabaseTransaction trans, uint8 tabId, uint8 slotId)
void _MoveItems (MoveItemData *pSrc, MoveItemData *pDest, uint32 splitedAmount)
bool _DoItemsMove (MoveItemData *pSrc, MoveItemData *pDest, bool sendError, uint32 splitedAmount=0)
void _SendBankContent (WorldSession *session, uint8 tabId) const
void _SendBankMoneyUpdate (WorldSession *session) const
void _SendBankContentUpdate (MoveItemData *pSrc, MoveItemData *pDest) const
void _SendBankContentUpdate (uint8 tabId, SlotIds slots) const
void _SendBankList (WorldSession *session=nullptr, uint8 tabId=0, bool sendFullSlots=false, SlotIds *slots=nullptr) const
void _BroadcastEvent (GuildEvents guildEvent, ObjectGuid guid=ObjectGuid::Empty, const char *param1=nullptr, const char *param2=nullptr, const char *param3=nullptr) const
Detailed Description
Definition at line 281 of file Guild.h.
Member Typedef Documentation
BankTabs
typedef std::vector<BankTab*> Guild::BankTabs private
Definition at line 666 of file Guild.h.
GuildLog
typedef std::list<LogEntry*> Guild::GuildLog private
Definition at line 464 of file Guild.h.
Members
typedef std::unordered_map<ObjectGuid, Member*> Guild::Members private
Definition at line 664 of file Guild.h.
Ranks
typedef std::vector<RankInfo> Guild::Ranks private
Definition at line 665 of file Guild.h.
Constructor & Destructor Documentation
Guild()
Guild::Guild ()
Definition at line 1122 of file Guild.cpp.
             :
     m_id(0),
     m_createdDate(0),
     m_accountsNumber(0),
     m_bankMoney(0),
     m_eventLog(nullptr)
 {
     memset(&m_bankEventLog, 0, (GUILD_BANK_MAX_TABS + 1) * sizeof(LogHolder*));
 }
References GUILD_BANK_MAX_TABS, m_bankEventLog, and memset.
~Guild()
Guild::~Guild ()
Definition at line 1132 of file Guild.cpp.
 {
     CharacterDatabaseTransaction temp(nullptr);
     _DeleteBankItems(temp);
     // Cleanup
     delete m_eventLog;
     m_eventLog = nullptr;
     for (uint8 tabId = 0; tabId <= GUILD_BANK_MAX_TABS; ++tabId)
     {
         delete m_bankEventLog[tabId];
         m_bankEventLog[tabId] = nullptr;
     }
     for (Members::iterator itr = m_members.begin(); itr != m_members.end(); ++itr)
     {
         delete itr->second;
         itr->second = nullptr;
     }
 }
References _DeleteBankItems(), GUILD_BANK_MAX_TABS, m_bankEventLog, m_eventLog, and m_members.
Member Function Documentation
_BroadcastEvent()
void Guild::_BroadcastEvent (GuildEvents guildEvent, ObjectGuid guid = ObjectGuid::Empty, const char * param1 = nullptr, const char * param2 = nullptr, const char * param3 = nullptr) const private
Definition at line 2817 of file Guild.cpp.
 {
     uint8 count = !param3 ? (!param2 ? (!param1 ? 0 : 1) : 2) : 3;
     WorldPacket data(SMSG_GUILD_EVENT, 1 + 1 + count + (guid ? 8 : 0));
     data << uint8(guildEvent);
     data << uint8(count);
     if (param3)
         data << param1 << param2 << param3;
     else if (param2)
         data << param1 << param2;
     else if (param1)
         data << param1;
     if (guid)
         data << guid;
     BroadcastPacket(&data);
     LOG_DEBUG("guild", "SMSG_GUILD_EVENT [Broadcast] Event: %u", guildEvent);
 }
References BroadcastPacket(), count(), LOG_DEBUG, and SMSG_GUILD_EVENT.
Referenced by AddMember(), DeleteMember(), Disband(), HandleAddNewRank(), HandleBuyBankTab(), HandleLeaveMember(), HandleMemberDepositMoney(), HandleMemberLogout(), HandleMemberWithdrawMoney(), HandleRemoveMember(), HandleRemoveRank(), HandleSetBankTabInfo(), HandleSetLeader(), HandleSetMOTD(), HandleSetRankInfo(), HandleUpdateMemberRank(), ResetTimes(), and SendLoginInfo().
_CreateDefaultGuildRanks()
void Guild::_CreateDefaultGuildRanks (LocaleConstant loc) private
Definition at line 2412 of file Guild.cpp.
 {
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_GUILD_RANKS);
     stmt->setUInt32(0, m_id);
     CharacterDatabase.Execute(stmt);
     stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_GUILD_BANK_RIGHTS);
     stmt->setUInt32(0, m_id);
     CharacterDatabase.Execute(stmt);
     _CreateRank(sObjectMgr->GetAcoreString(LANG_GUILD_MASTER,   loc), GR_RIGHT_ALL);
     _CreateRank(sObjectMgr->GetAcoreString(LANG_GUILD_OFFICER,  loc), GR_RIGHT_ALL);
     _CreateRank(sObjectMgr->GetAcoreString(LANG_GUILD_VETERAN,  loc), GR_RIGHT_GCHATLISTEN | GR_RIGHT_GCHATSPEAK);
     _CreateRank(sObjectMgr->GetAcoreString(LANG_GUILD_MEMBER,   loc), GR_RIGHT_GCHATLISTEN | GR_RIGHT_GCHATSPEAK);
     _CreateRank(sObjectMgr->GetAcoreString(LANG_GUILD_INITIATE, loc), GR_RIGHT_GCHATLISTEN | GR_RIGHT_GCHATSPEAK);
 }
References _CreateRank(), CHAR_DEL_GUILD_BANK_RIGHTS, CHAR_DEL_GUILD_RANKS, CharacterDatabase, GR_RIGHT_ALL, GR_RIGHT_GCHATLISTEN, GR_RIGHT_GCHATSPEAK, LANG_GUILD_INITIATE, LANG_GUILD_MASTER, LANG_GUILD_MEMBER, LANG_GUILD_OFFICER, LANG_GUILD_VETERAN, m_id, PreparedStatementBase::setUInt32(), and sObjectMgr.
Referenced by Create(), and Validate().
_CreateLogHolders()
void Guild::_CreateLogHolders () private
Definition at line 2381 of file Guild.cpp.
 {
     m_eventLog = new LogHolder(m_id, sWorld->getIntConfig(CONFIG_GUILD_EVENT_LOG_COUNT));
     for (uint8 tabId = 0; tabId <= GUILD_BANK_MAX_TABS; ++tabId)
         m_bankEventLog[tabId] = new LogHolder(m_id, sWorld->getIntConfig(CONFIG_GUILD_BANK_EVENT_LOG_COUNT));
 }
References CONFIG_GUILD_BANK_EVENT_LOG_COUNT, CONFIG_GUILD_EVENT_LOG_COUNT, GUILD_BANK_MAX_TABS, m_bankEventLog, m_eventLog, m_id, and sWorld.
Referenced by Create(), and LoadFromDB().
_CreateNewBankTab()
void Guild::_CreateNewBankTab () private
Definition at line 2388 of file Guild.cpp.
 {
     uint8 tabId = _GetPurchasedTabsSize();                      // Next free id
     m_bankTabs.push_back(new BankTab(m_id, tabId));
     CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_GUILD_BANK_TAB);
     stmt->setUInt32(0, m_id);
     stmt->setUInt8 (1, tabId);
     trans->Append(stmt);
     stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_GUILD_BANK_TAB);
     stmt->setUInt32(0, m_id);
     stmt->setUInt8 (1, tabId);
     trans->Append(stmt);
     ++tabId;
     for (Ranks::iterator itr = m_ranks.begin(); itr != m_ranks.end(); ++itr)
         (*itr).CreateMissingTabsIfNeeded(tabId, trans, false);
     CharacterDatabase.CommitTransaction(trans);
 }
References _GetPurchasedTabsSize(), CHAR_DEL_GUILD_BANK_TAB, CHAR_INS_GUILD_BANK_TAB, CharacterDatabase, m_bankTabs, m_id, m_ranks, PreparedStatementBase::setUInt32(), and PreparedStatementBase::setUInt8().
Referenced by Create(), and HandleBuyBankTab().
_CreateRank()
bool Guild::_CreateRank (std::string const & name, uint32 rights) private
Definition at line 2429 of file Guild.cpp.
 {
     uint8 newRankId = _GetRanksSize();
     if (newRankId >= GUILD_RANKS_MAX_COUNT)
         return false;
     // Ranks represent sequence 0, 1, 2, ... where 0 means guildmaster
     RankInfo info(m_id, newRankId, name, rights, 0);
     m_ranks.push_back(info);
     CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
     info.CreateMissingTabsIfNeeded(_GetPurchasedTabsSize(), trans);
     info.SaveToDB(trans);
     CharacterDatabase.CommitTransaction(trans);
     return true;
 }
References _GetPurchasedTabsSize(), _GetRanksSize(), CharacterDatabase, Guild::RankInfo::CreateMissingTabsIfNeeded(), GUILD_RANKS_MAX_COUNT, m_id, m_ranks, name, and Guild::RankInfo::SaveToDB().
Referenced by _CreateDefaultGuildRanks(), and HandleAddNewRank().
_DeleteBankItems()
void Guild::_DeleteBankItems (CharacterDatabaseTransaction trans, bool removeItemsFromDB = false) private
Definition at line 2471 of file Guild.cpp.
 {
     for (uint8 tabId = 0; tabId < _GetPurchasedTabsSize(); ++tabId)
     {
         m_bankTabs[tabId]->Delete(trans, removeItemsFromDB);
         delete m_bankTabs[tabId];
         m_bankTabs[tabId] = nullptr;
     }
     m_bankTabs.clear();
 }
References _GetPurchasedTabsSize(), and m_bankTabs.
Referenced by Disband(), and ~Guild().
_DeleteMemberFromDB()
void Guild::_DeleteMemberFromDB (ObjectGuid::LowType lowguid) const inline private
Definition at line 811 of file Guild.h.
     {
         CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_GUILD_MEMBER);
         stmt->setUInt32(0, lowguid);
         CharacterDatabase.Execute(stmt);
     }
References CHAR_DEL_GUILD_MEMBER, CharacterDatabase, and PreparedStatementBase::setUInt32().
Referenced by DeleteMember(), and LoadMemberFromDB().
_DoItemsMove()
bool Guild::_DoItemsMove (MoveItemData * pSrc, MoveItemData * pDest, bool sendError, uint32 splitedAmount = 0) private
Definition at line 2722 of file Guild.cpp.
 {
     Item* pDestItem = pDest->GetItem();
     bool swap = (pDestItem != nullptr);
     Item* pSrcItem = pSrc->GetItem(splitedAmount);
     // 1. Can store source item in destination
     if (!pDest->CanStore(pSrcItem, swap, sendError))
         return false;
     // 2. Can store destination item in source
     if (swap)
         if (!pSrc->CanStore(pDestItem, true, true))
             return false;
     // GM LOG (TODO: move to scripts)
     pDest->LogAction(pSrc);
     if (swap)
         pSrc->LogAction(pDest);
     CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
     // 3. Log bank events
     pDest->LogBankEvent(trans, pSrc, pSrcItem->GetCount());
     if (swap)
         pSrc->LogBankEvent(trans, pDest, pDestItem->GetCount());
     // 4. Remove item from source
     pSrc->RemoveItem(trans, pDest, splitedAmount);
     // 5. Remove item from destination
     if (swap)
         pDest->RemoveItem(trans, pSrc);
     // 6. Store item in destination
     pDest->StoreItem(trans, pSrcItem);
     // 7. Store item in source
     if (swap)
         pSrc->StoreItem(trans, pDestItem);
     CharacterDatabase.CommitTransaction(trans);
     return true;
 }
References Guild::MoveItemData::CanStore(), CharacterDatabase, Item::GetCount(), Guild::MoveItemData::GetItem(), Guild::MoveItemData::LogAction(), Guild::MoveItemData::LogBankEvent(), Guild::MoveItemData::RemoveItem(), Guild::MoveItemData::StoreItem(), and swap().
Referenced by _MoveItems().
_GetItem()
Item * Guild::_GetItem (uint8 tabId, uint8 slotId) const inline private
Definition at line 2656 of file Guild.cpp.
 {
     if (const BankTab* tab = GetBankTab(tabId))
         return tab->GetItem(slotId);
     return nullptr;
 }
References GetBankTab().
_GetLowestRankId()
uint8 Guild::_GetLowestRankId () const inline private
Definition at line 805 of file Guild.h.
 { return uint8(m_ranks.size() - 1); }
References m_ranks.
Referenced by AddMember(), ChangeMemberRank(), HandleRemoveLowestRank(), HandleUpdateMemberRank(), and Validate().
_GetMemberRemainingMoney()
int32 Guild::_GetMemberRemainingMoney (Member const * member) const inline private
Definition at line 2583 of file Guild.cpp.
 {
     if (member)
     {
         uint8 rankId = member->GetRankId();
         if (rankId == GR_GUILDMASTER)
             return GUILD_WITHDRAW_MONEY_UNLIMITED;
         if ((_GetRankRights(rankId) & (GR_RIGHT_WITHDRAW_REPAIR | GR_RIGHT_WITHDRAW_GOLD)) != 0)
         {
             int32 remaining = _GetRankBankMoneyPerDay(rankId) - member->GetBankWithdrawValue(GUILD_BANK_MAX_TABS);
             if (remaining > 0)
                 return remaining;
         }
     }
     return 0;
 }
References _GetRankBankMoneyPerDay(), _GetRankRights(), Guild::Member::GetBankWithdrawValue(), Guild::Member::GetRankId(), GR_GUILDMASTER, GR_RIGHT_WITHDRAW_GOLD, GR_RIGHT_WITHDRAW_REPAIR, GUILD_BANK_MAX_TABS, and GUILD_WITHDRAW_MONEY_UNLIMITED.
Referenced by HandleMemberWithdrawMoney(), SendMoneyInfo(), and SendPermissions().
_GetMemberRemainingSlots()
int32 Guild::_GetMemberRemainingSlots (Member const * member, uint8 tabId) const inline private
Definition at line 2566 of file Guild.cpp.
 {
     if (member)
     {
         uint8 rankId = member->GetRankId();
         if (rankId == GR_GUILDMASTER)
             return GUILD_WITHDRAW_SLOT_UNLIMITED;
         if ((_GetRankBankTabRights(rankId, tabId) & GUILD_BANK_RIGHT_VIEW_TAB) != 0)
         {
             int32 remaining = _GetRankBankTabSlotsPerDay(rankId, tabId) - member->GetBankWithdrawValue(tabId);
             if (remaining > 0)
                 return remaining;
         }
     }
     return 0;
 }
References _GetRankBankTabRights(), _GetRankBankTabSlotsPerDay(), Guild::Member::GetBankWithdrawValue(), Guild::Member::GetRankId(), GR_GUILDMASTER, GUILD_BANK_RIGHT_VIEW_TAB, and GUILD_WITHDRAW_SLOT_UNLIMITED.
Referenced by _SendBankList(), and SendPermissions().
_GetPurchasedTabsSize()
uint8 Guild::_GetPurchasedTabsSize () const inline private
Definition at line 807 of file Guild.h.
 { return uint8(m_bankTabs.size()); }
References m_bankTabs.
Referenced by _CreateNewBankTab(), _CreateRank(), _DeleteBankItems(), _GetRankBankTabSlotsPerDay(), _SendBankList(), _SetRankBankTabRightsAndSlots(), HandleBuyBankTab(), LoadBankEventLogFromDB(), LoadBankItemFromDB(), LoadBankTabFromDB(), SendBankLog(), SendBankTabData(), SendPermissions(), SwapItems(), SwapItemsWithInventory(), and Validate().
_GetRankBankMoneyPerDay()
int32 Guild::_GetRankBankMoneyPerDay (uint8 rankId) const inline private
Definition at line 2544 of file Guild.cpp.
 {
     if (const RankInfo* rankInfo = GetRankInfo(rankId))
         return rankInfo->GetBankMoneyPerDay();
     return 0;
 }
References GetRankInfo().
Referenced by _GetMemberRemainingMoney().
_GetRankBankTabRights()
int8 Guild::_GetRankBankTabRights (uint8 rankId, uint8 tabId) const inline private
Definition at line 2559 of file Guild.cpp.
 {
     if (const RankInfo* rankInfo = GetRankInfo(rankId))
         return rankInfo->GetBankTabRights(tabId);
     return 0;
 }
References GetRankInfo().
Referenced by _GetMemberRemainingSlots(), _MemberHasTabRights(), and SendPermissions().
_GetRankBankTabSlotsPerDay()
int32 Guild::_GetRankBankTabSlotsPerDay (uint8 rankId, uint8 tabId) const inline private
Definition at line 2551 of file Guild.cpp.
 {
     if (tabId < _GetPurchasedTabsSize())
         if (const RankInfo* rankInfo = GetRankInfo(rankId))
             return rankInfo->GetBankTabSlotsPerDay(tabId);
     return 0;
 }
References _GetPurchasedTabsSize(), and GetRankInfo().
Referenced by _GetMemberRemainingSlots(), and _UpdateMemberWithdrawSlots().
_GetRankName()
std::string Guild::_GetRankName (uint8 rankId) const inline private
Definition at line 2530 of file Guild.cpp.
 {
     if (const RankInfo* rankInfo = GetRankInfo(rankId))
         return rankInfo->GetName();
     return "<unknown>";
 }
References GetRankInfo().
Referenced by HandleUpdateMemberRank().
_GetRankRights()
uint32 Guild::_GetRankRights (uint8 rankId) const inline private
Definition at line 2537 of file Guild.cpp.
 {
     if (const RankInfo* rankInfo = GetRankInfo(rankId))
         return rankInfo->GetRights();
     return 0;
 }
References GetRankInfo().
Referenced by _GetMemberRemainingMoney(), _HasRankRight(), and SendPermissions().
_GetRanksSize()
uint8 Guild::_GetRanksSize () const inline private
Definition at line 794 of file Guild.h.
 { return uint8(m_ranks.size()); }
References m_ranks.
Referenced by _CreateRank(), GetRankInfo(), HandleAddNewRank(), HandleQuery(), HandleRemoveRank(), HandleRoster(), and Validate().
_HasRankRight()
bool Guild::_HasRankRight (Player * player, uint32 right) const inline private
Definition at line 797 of file Guild.h.
     {
         if (player)
             if (Member const* member = GetMember(player->GetGUID()))
                 return (_GetRankRights(member->GetRankId()) & right) != GR_RIGHT_EMPTY;
         return false;
     }
References _GetRankRights(), Object::GetGUID(), GetMember(), GR_RIGHT_EMPTY, and align::right.
Referenced by BroadcastToGuild(), HandleInviteMember(), HandleRemoveMember(), HandleRoster(), HandleSetInfo(), HandleSetMemberNote(), HandleSetMOTD(), and HandleUpdateMemberRank().
_IsLeader()
bool Guild::_IsLeader (Player * player) const private
Definition at line 2462 of file Guild.cpp.
 {
     if (player->GetGUID() == m_leaderGuid)
         return true;
     if (const Member* member = GetMember(player->GetGUID()))
         return member->IsRank(GR_GUILDMASTER);
     return false;
 }
References Object::GetGUID(), GetMember(), GR_GUILDMASTER, and m_leaderGuid.
Referenced by HandleAddNewRank(), HandleDisband(), HandleLeaveMember(), HandleRemoveRank(), HandleSetEmblem(), HandleSetLeader(), and HandleSetRankInfo().
_LogBankEvent()
void Guild::_LogBankEvent (CharacterDatabaseTransaction trans, GuildBankEventLogTypes eventType, uint8 tabId, ObjectGuid playerGuid, uint32 itemOrMoney, uint16 itemStackCount = 0, uint8 destTabId = 0) private
Definition at line 2635 of file Guild.cpp.
 {
     if (tabId > GUILD_BANK_MAX_TABS)
         return;
     // not logging moves within the same tab
     if (eventType == GUILD_BANK_LOG_MOVE_ITEM && tabId == destTabId)
         return;
     uint8 dbTabId = tabId;
     if (BankEventLogEntry::IsMoneyEvent(eventType))
     {
         tabId = GUILD_BANK_MAX_TABS;
         dbTabId = GUILD_BANK_MONEY_LOGS_TAB;
     }
     LogHolder* pLog = m_bankEventLog[tabId];
     pLog->AddEvent(trans, new BankEventLogEntry(m_id, pLog->GetNextGUID(), eventType, dbTabId, guid, itemOrMoney, itemStackCount, destTabId));
     sScriptMgr->OnGuildBankEvent(this, uint8(eventType), tabId, guid.GetCounter(), itemOrMoney, itemStackCount, destTabId);
 }
References Guild::LogHolder::AddEvent(), ObjectGuid::GetCounter(), Guild::LogHolder::GetNextGUID(), GUILD_BANK_LOG_MOVE_ITEM, GUILD_BANK_MAX_TABS, GUILD_BANK_MONEY_LOGS_TAB, Guild::BankEventLogEntry::IsMoneyEvent(), m_bankEventLog, m_id, and sScriptMgr.
Referenced by HandleMemberDepositMoney(), and HandleMemberWithdrawMoney().
_LogEvent()
void Guild::_LogEvent (GuildEventLogTypes eventType, ObjectGuid playerGuid1, ObjectGuid playerGuid2 = ObjectGuid::Empty, uint8 newRank = 0) inline private
Definition at line 2625 of file Guild.cpp.
 {
     CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
     m_eventLog->AddEvent(trans, new EventLogEntry(m_id, m_eventLog->GetNextGUID(), eventType, playerGuid1, playerGuid2, newRank));
     CharacterDatabase.CommitTransaction(trans);
     sScriptMgr->OnGuildEvent(this, uint8(eventType), playerGuid1.GetCounter(), playerGuid2.GetCounter(), newRank);
 }
References Guild::LogHolder::AddEvent(), CharacterDatabase, ObjectGuid::GetCounter(), Guild::LogHolder::GetNextGUID(), m_eventLog, m_id, and sScriptMgr.
Referenced by AddMember(), HandleInviteMember(), HandleLeaveMember(), HandleRemoveMember(), and HandleUpdateMemberRank().
_MemberHasTabRights()
bool Guild::_MemberHasTabRights (ObjectGuid guid, uint8 tabId, uint32 rights) const inline private
Definition at line 2612 of file Guild.cpp.
 {
     if (const Member* member = GetMember(guid))
     {
         // Leader always has full rights
         if (member->IsRank(GR_GUILDMASTER) || m_leaderGuid == guid)
             return true;
         return (_GetRankBankTabRights(member->GetRankId(), tabId) & rights) == rights;
     }
     return false;
 }
References _GetRankBankTabRights(), GetMember(), GR_GUILDMASTER, and m_leaderGuid.
Referenced by _SendBankContent(), and _SendBankList().
_ModifyBankMoney()
bool Guild::_ModifyBankMoney (CharacterDatabaseTransaction trans, uint64 amount, bool add) private
Definition at line 2482 of file Guild.cpp.
 {
     if (add)
         m_bankMoney += amount;
     else
     {
         // Check if there is enough money in bank.
         if (m_bankMoney < amount)
             return false;
         m_bankMoney -= amount;
     }
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_GUILD_BANK_MONEY);
     stmt->setUInt64(0, m_bankMoney);
     stmt->setUInt32(1, m_id);
     trans->Append(stmt);
     return true;
 }
References CHAR_UPD_GUILD_BANK_MONEY, CharacterDatabase, m_bankMoney, m_id, PreparedStatementBase::setUInt32(), and PreparedStatementBase::setUInt64().
Referenced by HandleMemberDepositMoney(), HandleMemberWithdrawMoney(), and ModifyBankMoney().
_MoveItems()
void Guild::_MoveItems (MoveItemData * pSrc, MoveItemData * pDest, uint32 splitedAmount) private
Definition at line 2669 of file Guild.cpp.
 {
     // 1. Initialize source item
     if (!pSrc->InitItem())
         return; // No source item
     // 2. Check source item
     if (!pSrc->CheckItem(splitedAmount))
         return; // Source item or splited amount is invalid
     // 3. Check destination rights
     if (!pDest->HasStoreRights(pSrc))
         return; // Player has no rights to store item in destination
     // 4. Check source withdraw rights
     if (!pSrc->HasWithdrawRights(pDest))
         return; // Player has no rights to withdraw items from source
     // 5. Check split
     if (splitedAmount)
     {
         // 5.1. Clone source item
         if (!pSrc->CloneItem(splitedAmount))
             return; // Item could not be cloned
         // 5.2. Move splited item to destination
         _DoItemsMove(pSrc, pDest, true, splitedAmount);
     }
     else // 6. No split
     {
         // 6.1. Try to merge items in destination (pDest->GetItem() == nullptr)
         if (!_DoItemsMove(pSrc, pDest, false)) // Item could not be merged
         {
             // 6.2. Try to swap items
             // 6.2.1. Initialize destination item
             if (!pDest->InitItem())
                 return;
             // 6.2.2. Check rights to store item in source (opposite direction)
             if (!pSrc->HasStoreRights(pDest))
                 return; // Player has no rights to store item in source (opposite direction)
             if (!pDest->HasWithdrawRights(pSrc))
                 return; // Player has no rights to withdraw item from destination (opposite direction)
             // 6.2.3. Swap items (pDest->GetItem() != nullptr)
             _DoItemsMove(pSrc, pDest, true);
         }
     }
     // 7. Send changes
     _SendBankContentUpdate(pSrc, pDest);
 }
References _DoItemsMove(), _SendBankContentUpdate(), Guild::MoveItemData::CheckItem(), Guild::MoveItemData::CloneItem(), Guild::MoveItemData::HasStoreRights(), Guild::MoveItemData::HasWithdrawRights(), and Guild::MoveItemData::InitItem().
Referenced by SwapItems(), and SwapItemsWithInventory().
_RemoveItem()
void Guild::_RemoveItem (CharacterDatabaseTransaction trans, uint8 tabId, uint8 slotId) inline private
Definition at line 2663 of file Guild.cpp.
 {
     if (BankTab* pTab = GetBankTab(tabId))
         pTab->SetItem(trans, slotId, nullptr);
 }
References GetBankTab().
_SendBankContent()
void Guild::_SendBankContent (WorldSession * session, uint8 tabId) const private
Definition at line 2766 of file Guild.cpp.
 {
     ObjectGuid guid = session->GetPlayer()->GetGUID();
     if (!_MemberHasTabRights(guid, tabId, GUILD_BANK_RIGHT_VIEW_TAB))
         return;
     _SendBankList(session, tabId, true);
 }
References _MemberHasTabRights(), _SendBankList(), Object::GetGUID(), WorldSession::GetPlayer(), and GUILD_BANK_RIGHT_VIEW_TAB.
Referenced by SendBankTabData().
_SendBankContentUpdate() [1/2]
void Guild::_SendBankContentUpdate (MoveItemData * pSrc, MoveItemData * pDest) const private
Definition at line 2780 of file Guild.cpp.
 {
     ASSERT(pSrc->IsBank() || pDest->IsBank());
     uint8 tabId = 0;
     SlotIds slots;
     if (pSrc->IsBank()) // B ->
     {
         tabId = pSrc->GetContainer();
         slots.insert(pSrc->GetSlotId());
         if (pDest->IsBank()) // B -> B
         {
             // Same tab - add destination slots to collection
             if (pDest->GetContainer() == pSrc->GetContainer())
                 pDest->CopySlots(slots);
             else // Different tabs - send second message
             {
                 SlotIds destSlots;
                 pDest->CopySlots(destSlots);
                 _SendBankContentUpdate(pDest->GetContainer(), destSlots);
             }
         }
     }
     else if (pDest->IsBank()) // C -> B
     {
         tabId = pDest->GetContainer();
         pDest->CopySlots(slots);
     }
     _SendBankContentUpdate(tabId, slots);
 }
References ASSERT, Guild::MoveItemData::CopySlots(), Guild::MoveItemData::GetContainer(), Guild::MoveItemData::GetSlotId(), and Guild::MoveItemData::IsBank().
Referenced by _MoveItems().
_SendBankContentUpdate() [2/2]
void Guild::_SendBankContentUpdate (uint8 tabId, SlotIds slots) const private
Definition at line 2812 of file Guild.cpp.
 {
     _SendBankList(nullptr, tabId, false, &slots);
 }
References _SendBankList().
_SendBankList()
void Guild::_SendBankList (WorldSession * session = nullptr, uint8 tabId = 0, bool sendFullSlots = false, SlotIds * slots = nullptr) const private
Definition at line 2839 of file Guild.cpp.
 {
     if (!sScriptMgr->CanGuildSendBankList(this, session, tabId, sendAllSlots))
         return;
     WorldPacket data(SMSG_GUILD_BANK_LIST, 500);
     data << uint64(m_bankMoney);
     data << uint8(tabId);
     size_t rempos = data.wpos();
     data << uint32(0);
     data << uint8(sendAllSlots);
     if (sendAllSlots && !tabId)
     {
         data << uint8(_GetPurchasedTabsSize());                  // Number of tabs
         for (uint8 i = 0; i < _GetPurchasedTabsSize(); ++i)
             m_bankTabs[i]->WriteInfoPacket(data);
     }
     BankTab const* tab = GetBankTab(tabId);
     if (!tab)
         data << uint8(0);
     else if (sendAllSlots)
         tab->WritePacket(data);
     else if (slots && !slots->empty())
     {
         data << uint8(slots->size());
         for (SlotIds::const_iterator itr = slots->begin(); itr != slots->end(); ++itr)
             tab->WriteSlotPacket(data, *itr, false);
     }
     else
         data << uint8(0);
     if (session)
     {
         int32 numSlots = 0;
         if (Member const* member = GetMember(session->GetPlayer()->GetGUID()))
             numSlots = _GetMemberRemainingSlots(member, tabId);
         data.put<uint32>(rempos, numSlots);
         session->SendPacket(&data);
         LOG_DEBUG("guild", "SMSG_GUILD_BANK_LIST [%s]: TabId: %u, FullSlots: %u, slots: %d",
                        session->GetPlayerInfo().c_str(), tabId, sendAllSlots, numSlots);
     }
     else // TODO - Probably this is just sent to session + those that have sent CMSG_GUILD_BANKER_ACTIVATE
     {
         for (Members::const_iterator itr = m_members.begin(); itr != m_members.end(); ++itr)
         {
             if (!_MemberHasTabRights(itr->second->GetGUID(), tabId, GUILD_BANK_RIGHT_VIEW_TAB))
                 continue;
             Player* player = itr->second->FindPlayer();
             if (!player)
                 continue;
             uint32 numSlots = _GetMemberRemainingSlots(itr->second, tabId);
             data.put<uint32>(rempos, numSlots);
             player->GetSession()->SendPacket(&data);
             LOG_DEBUG("guild", "SMSG_GUILD_BANK_LIST [%s]: TabId: %u, FullSlots: %u, slots: %u"
                            , player->GetName().c_str(), tabId, sendAllSlots, numSlots);
         }
     }
 }
References _GetMemberRemainingSlots(), _GetPurchasedTabsSize(), _MemberHasTabRights(), GetBankTab(), Object::GetGUID(), GetMember(), WorldObject::GetName(), WorldSession::GetPlayer(), WorldSession::GetPlayerInfo(), Player::GetSession(), GUILD_BANK_RIGHT_VIEW_TAB, LOG_DEBUG, m_bankMoney, m_bankTabs, m_members, WorldSession::SendPacket(), SMSG_GUILD_BANK_LIST, sScriptMgr, Guild::BankTab::WritePacket(), and Guild::BankTab::WriteSlotPacket().
Referenced by _SendBankContent(), _SendBankContentUpdate(), _SendBankMoneyUpdate(), and SendBankTabsInfo().
_SendBankMoneyUpdate()
void Guild::_SendBankMoneyUpdate (WorldSession * session) const private
Definition at line 2775 of file Guild.cpp.
 {
     _SendBankList(session);
 }
References _SendBankList().
_SetLeaderGUID()
void Guild::_SetLeaderGUID (Member * pLeader) private
Definition at line 2501 of file Guild.cpp.
 {
     if (!pLeader)
         return;
     m_leaderGuid = pLeader->GetGUID();
     pLeader->ChangeRank(GR_GUILDMASTER);
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_GUILD_LEADER);
     stmt->setUInt32(0, m_leaderGuid.GetCounter());
     stmt->setUInt32(1, m_id);
     CharacterDatabase.Execute(stmt);
 }
References Guild::Member::ChangeRank(), CHAR_UPD_GUILD_LEADER, CharacterDatabase, ObjectGuid::GetCounter(), Guild::Member::GetGUID(), GR_GUILDMASTER, m_id, m_leaderGuid, and PreparedStatementBase::setUInt32().
Referenced by DeleteMember(), HandleSetLeader(), and Validate().
_SetRankBankMoneyPerDay()
void Guild::_SetRankBankMoneyPerDay (uint8 rankId, uint32 moneyPerDay) private
Definition at line 2515 of file Guild.cpp.
 {
     if (RankInfo* rankInfo = GetRankInfo(rankId))
         rankInfo->SetBankMoneyPerDay(moneyPerDay);
 }
References GetRankInfo().
Referenced by HandleSetRankInfo().
_SetRankBankTabRightsAndSlots()
void Guild::_SetRankBankTabRightsAndSlots (uint8 rankId, GuildBankRightsAndSlots rightsAndSlots, bool saveToDB = true) private
Definition at line 2521 of file Guild.cpp.
 {
     if (rightsAndSlots.GetTabId() >= _GetPurchasedTabsSize())
         return;
     if (RankInfo* rankInfo = GetRankInfo(rankId))
         rankInfo->SetBankTabSlotsAndRights(rightsAndSlots, saveToDB);
 }
References _GetPurchasedTabsSize(), GetRankInfo(), and GuildBankRightsAndSlots::GetTabId().
Referenced by HandleSetRankInfo(), and LoadBankRightFromDB().
_UpdateAccountsNumber()
void Guild::_UpdateAccountsNumber () private
Definition at line 2449 of file Guild.cpp.
 {
     // We use a set to be sure each element will be unique
     std::set<uint32> accountsIdSet;
     for (Members::const_iterator itr = m_members.begin(); itr != m_members.end(); ++itr)
         accountsIdSet.insert(itr->second->GetAccountId());
     m_accountsNumber = accountsIdSet.size();
 }
References m_accountsNumber, and m_members.
Referenced by AddMember(), DeleteMember(), and Validate().
_UpdateMemberWithdrawSlots()
void Guild::_UpdateMemberWithdrawSlots (CharacterDatabaseTransaction trans, ObjectGuid guid, uint8 tabId) inline private
Definition at line 2601 of file Guild.cpp.
 {
     if (Member* member = GetMember(guid))
     {
         uint8 rankId = member->GetRankId();
         if (rankId != GR_GUILDMASTER
                 && member->GetBankWithdrawValue(tabId) < _GetRankBankTabSlotsPerDay(rankId, tabId))
             member->UpdateBankWithdrawValue(trans, tabId, 1);
     }
 }
References _GetRankBankTabSlotsPerDay(), GetMember(), and GR_GUILDMASTER.
AddMember()
bool Guild::AddMember (ObjectGuid guid, uint8 rankId = GUILD_RANK_NONE)
Definition at line 2191 of file Guild.cpp.
 {
     Player* player = ObjectAccessor::FindConnectedPlayer(guid);
     // Player cannot be in guild
     if (player)
     {
         if (player->GetGuildId() != 0)
             return false;
     }
     else if (Player::GetGuildIdFromStorage(guid.GetCounter()) != 0)
         return false;
     // Remove all player signs from another petitions
     // This will be prevent attempt to join many guilds and corrupt guild data integrity
     Player::RemovePetitionsAndSigns(guid, GUILD_CHARTER_TYPE);
     // If rank was not passed, assign lowest possible rank
     if (rankId == GUILD_RANK_NONE)
         rankId = _GetLowestRankId();
     Member* member = new Member(m_id, guid, rankId);
     std::string name;
     if (player)
     {
         m_members[guid] = member;
         player->SetInGuild(m_id);
         player->SetGuildIdInvited(0);
         player->SetRank(rankId);
         member->SetStats(player);
         SendLoginInfo(player->GetSession());
         name = player->GetName();
     }
     else
     {
         member->ResetFlags();
         bool ok = false;
         // xinef: zomg! sync query
         // Player must exist
         CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_SEL_CHAR_DATA_FOR_GUILD);
         stmt->setUInt32(0, guid.GetCounter());
         if (PreparedQueryResult result = CharacterDatabase.Query(stmt))
         {
             Field* fields = result->Fetch();
             name = fields[0].GetString();
             member->SetStats(
                 name,
                 fields[1].GetUInt8(),
                 fields[2].GetUInt8(),
                 fields[3].GetUInt8(),
                 fields[4].GetUInt16(),
                 fields[5].GetUInt32());
             ok = member->CheckStats();
         }
         if (!ok)
         {
             delete member;
             return false;
         }
         m_members[guid] = member;
         sWorld->UpdateGlobalPlayerGuild(guid.GetCounter(), m_id);
     }
     CharacterDatabaseTransaction trans(nullptr);
     member->SaveToDB(trans);
     _UpdateAccountsNumber();
     _LogEvent(GUILD_EVENT_LOG_JOIN_GUILD, guid);
     _BroadcastEvent(GE_JOINED, guid, name.c_str());
     // Call scripts if member was succesfully added (and stored to database)
     sScriptMgr->OnGuildAddMember(this, player, rankId);
     return true;
 }
References _BroadcastEvent(), _GetLowestRankId(), _LogEvent(), _UpdateAccountsNumber(), CHAR_SEL_CHAR_DATA_FOR_GUILD, CharacterDatabase, Guild::Member::CheckStats(), ObjectAccessor::FindConnectedPlayer(), GE_JOINED, ObjectGuid::GetCounter(), Player::GetGuildId(), Player::GetGuildIdFromStorage(), WorldObject::GetName(), Player::GetSession(), Field::GetString(), GUILD_CHARTER_TYPE, GUILD_EVENT_LOG_JOIN_GUILD, GUILD_RANK_NONE, m_id, m_members, name, Player::RemovePetitionsAndSigns(), Guild::Member::ResetFlags(), Guild::Member::SaveToDB(), SendLoginInfo(), Player::SetGuildIdInvited(), Player::SetInGuild(), Player::SetRank(), Guild::Member::SetStats(), PreparedStatementBase::setUInt32(), sScriptMgr, and sWorld.
Referenced by Create(), HandleAcceptMember(), guild_commandscript::HandleGuildInviteCommand(), and WorldSession::HandleTurnInPetitionOpcode().
BroadcastPacket()
void Guild::BroadcastPacket (WorldPacket * packet) const
Definition at line 2150 of file Guild.cpp.
 {
     for (Members::const_iterator itr = m_members.begin(); itr != m_members.end(); ++itr)
         if (Player* player = itr->second->FindPlayer())
             player->GetSession()->SendPacket(packet);
 }
References m_members.
Referenced by _BroadcastEvent(), and Guild::BankTab::SendText().
BroadcastPacketToRank()
void Guild::BroadcastPacketToRank (WorldPacket * packet, uint8 rankId) const
Definition at line 2142 of file Guild.cpp.
 {
     for (Members::const_iterator itr = m_members.begin(); itr != m_members.end(); ++itr)
         if (itr->second->IsRank(rankId))
             if (Player* player = itr->second->FindPlayer())
                 player->GetSession()->SendPacket(packet);
 }
References m_members.
BroadcastToGuild()
void Guild::BroadcastToGuild (WorldSession * session, bool officerOnly, std::string const & msg, uint32 language = LANG_UNIVERSAL) const
Definition at line 2129 of file Guild.cpp.
 {
     if (session && session->GetPlayer() && _HasRankRight(session->GetPlayer(), officerOnly ? GR_RIGHT_OFFCHATSPEAK : GR_RIGHT_GCHATSPEAK))
     {
         WorldPacket data;
         ChatHandler::BuildChatPacket(data, officerOnly ? CHAT_MSG_OFFICER : CHAT_MSG_GUILD, Language(language), session->GetPlayer(), nullptr, msg);
         for (Members::const_iterator itr = m_members.begin(); itr != m_members.end(); ++itr)
             if (Player* player = itr->second->FindPlayer())
                 if (_HasRankRight(player, officerOnly ? GR_RIGHT_OFFCHATLISTEN : GR_RIGHT_GCHATLISTEN) && !player->GetSocial()->HasIgnore(session->GetPlayer()->GetGUID()))
                     player->GetSession()->SendPacket(&data);
     }
 }
References _HasRankRight(), ChatHandler::BuildChatPacket(), CHAT_MSG_GUILD, CHAT_MSG_OFFICER, Object::GetGUID(), WorldSession::GetPlayer(), GR_RIGHT_GCHATLISTEN, GR_RIGHT_GCHATSPEAK, GR_RIGHT_OFFCHATLISTEN, GR_RIGHT_OFFCHATSPEAK, and m_members.
BroadcastWorker()
template<class Do > void Guild::BroadcastWorker (Do & _do, Player * except = nullptr) inline
Definition at line 742 of file Guild.h.
     {
         for (Members::iterator itr = m_members.begin(); itr != m_members.end(); ++itr)
             if (Player* player = itr->second->FindPlayer())
                 if (player != except)
                     _do(player);
     }
References m_members.
Referenced by AchievementMgr::SendAchievementEarned().
ChangeMemberRank()
bool Guild::ChangeMemberRank (ObjectGuid guid, uint8 newRank)
Definition at line 2331 of file Guild.cpp.
 {
     if (newRank <= _GetLowestRankId())                    // Validate rank (allow only existing ranks)
         if (Member* member = GetMember(guid))
         {
             member->ChangeRank(newRank);
             return true;
         }
     return false;
 }
References _GetLowestRankId(), and GetMember().
Referenced by guild_commandscript::HandleGuildRankCommand().
Create()
bool Guild::Create (Player * pLeader, std::string const & name)
Definition at line 1155 of file Guild.cpp.
 {
     // Check if guild with such name already exists
     if (sGuildMgr->GetGuildByName(name))
         return false;
     WorldSession* pLeaderSession = pLeader->GetSession();
     if (!pLeaderSession)
         return false;
     m_id = sGuildMgr->GenerateGuildId();
     m_leaderGuid = pLeader->GetGUID();
     m_name = name;
     m_info = "";
     m_motd = "No message set.";
     m_bankMoney = 0;
     m_createdDate = sWorld->GetGameTime();
     _CreateLogHolders();
     LOG_DEBUG("guild", "GUILD: creating guild [%s] for leader %s (%s)",
         name.c_str(), pLeader->GetName().c_str(), m_leaderGuid.ToString().c_str());
     CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_GUILD_MEMBERS);
     stmt->setUInt32(0, m_id);
     trans->Append(stmt);
     uint8 index = 0;
     stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_GUILD);
     stmt->setUInt32(  index, m_id);
     stmt->setString(++index, name);
     stmt->setUInt32(++index, m_leaderGuid.GetCounter());
     stmt->setString(++index, m_info);
     stmt->setString(++index, m_motd);
     stmt->setUInt64(++index, uint32(m_createdDate));
     stmt->setUInt32(++index, m_emblemInfo.GetStyle());
     stmt->setUInt32(++index, m_emblemInfo.GetColor());
     stmt->setUInt32(++index, m_emblemInfo.GetBorderStyle());
     stmt->setUInt32(++index, m_emblemInfo.GetBorderColor());
     stmt->setUInt32(++index, m_emblemInfo.GetBackgroundColor());
     stmt->setUInt64(++index, m_bankMoney);
     trans->Append(stmt);
     CharacterDatabase.CommitTransaction(trans);
     _CreateDefaultGuildRanks(pLeaderSession->GetSessionDbLocaleIndex()); // Create default ranks
     bool ret = AddMember(m_leaderGuid, GR_GUILDMASTER);                  // Add guildmaster
     for (short i = 0; i < static_cast<short>(sWorld->getIntConfig(CONFIG_GUILD_BANK_INITIAL_TABS)); i++)
     {
         _CreateNewBankTab();
     }
     if (ret)
         sScriptMgr->OnGuildCreate(this, pLeader, name);
     return ret;
 }
References _CreateDefaultGuildRanks(), _CreateLogHolders(), _CreateNewBankTab(), AddMember(), CHAR_DEL_GUILD_MEMBERS, CHAR_INS_GUILD, CharacterDatabase, CONFIG_GUILD_BANK_INITIAL_TABS, EmblemInfo::GetBackgroundColor(), EmblemInfo::GetBorderColor(), EmblemInfo::GetBorderStyle(), EmblemInfo::GetColor(), ObjectGuid::GetCounter(), Object::GetGUID(), WorldObject::GetName(), Player::GetSession(), WorldSession::GetSessionDbLocaleIndex(), EmblemInfo::GetStyle(), GR_GUILDMASTER, index, LOG_DEBUG, m_bankMoney, m_createdDate, m_emblemInfo, m_id, m_info, m_leaderGuid, m_motd, m_name, name, ret, PreparedStatementBase::setString(), PreparedStatementBase::setUInt32(), PreparedStatementBase::setUInt64(), sGuildMgr, sScriptMgr, sWorld, and ObjectGuid::ToString().
Referenced by guild_commandscript::HandleGuildCreateCommand(), and WorldSession::HandleTurnInPetitionOpcode().
DeleteMember()
void Guild::DeleteMember (ObjectGuid guid, bool isDisbanding = false, bool isKicked = false, bool canDeleteGuild = false)
Definition at line 2268 of file Guild.cpp.
 {
     Player* player = ObjectAccessor::FindConnectedPlayer(guid);
     // Guild master can be deleted when loading guild and guid doesn't exist in characters table
     // or when he is removed from guild by gm command
     if (m_leaderGuid == guid && !isDisbanding)
     {
         Member* oldLeader = nullptr;
         Member* newLeader = nullptr;
         for (Guild::Members::iterator i = m_members.begin(); i != m_members.end(); ++i)
         {
             if (i->first == guid)
                 oldLeader = i->second;
             else if (!newLeader || newLeader->GetRankId() > i->second->GetRankId())
                 newLeader = i->second;
         }
         if (!newLeader)
         {
             Disband();
             if (canDeleteGuild)
                 delete this;
             return;
         }
         _SetLeaderGUID(newLeader);
         // If player not online data in data field will be loaded from guild tabs no need to update it !!
         if (Player* newLeaderPlayer = newLeader->FindPlayer())
             newLeaderPlayer->SetRank(GR_GUILDMASTER);
         // If leader does not exist (at guild loading with deleted leader) do not send broadcasts
         if (oldLeader)
         {
             _BroadcastEvent(GE_LEADER_CHANGED, ObjectGuid::Empty, oldLeader->GetName().c_str(), newLeader->GetName().c_str());
             _BroadcastEvent(GE_LEFT, guid, oldLeader->GetName().c_str());
         }
     }
     // Call script on remove before member is actually removed from guild (and database)
     sScriptMgr->OnGuildRemoveMember(this, player, isDisbanding, isKicked);
     auto memberItr = m_members.find(guid);
     if (memberItr != m_members.end())
     {
         delete memberItr->second;
         m_members.erase(memberItr);
     }
     // If player not online data in data field will be loaded from guild tabs no need to update it !!
     if (player)
     {
         player->SetInGuild(0);
         player->SetRank(0);
     }
     else
         sWorld->UpdateGlobalPlayerGuild(guid.GetCounter(), 0);
     _DeleteMemberFromDB(guid.GetCounter());
     if (!isDisbanding)
         _UpdateAccountsNumber();
 }
References _BroadcastEvent(), _DeleteMemberFromDB(), _SetLeaderGUID(), _UpdateAccountsNumber(), Disband(), ObjectGuid::Empty, ObjectAccessor::FindConnectedPlayer(), Guild::Member::FindPlayer(), GE_LEADER_CHANGED, GE_LEFT, ObjectGuid::GetCounter(), Guild::Member::GetName(), Guild::Member::GetRankId(), GR_GUILDMASTER, m_leaderGuid, m_members, Player::SetInGuild(), Player::SetRank(), sScriptMgr, and sWorld.
Referenced by Disband(), guild_commandscript::HandleGuildUninviteCommand(), HandleLeaveMember(), HandleRemoveMember(), and Validate().
Disband()
void Guild::Disband ()
Definition at line 1215 of file Guild.cpp.
 {
     // Call scripts before guild data removed from database
     sScriptMgr->OnGuildDisband(this);
     _BroadcastEvent(GE_DISBANDED);
     // Remove all members
     while (!m_members.empty())
     {
         Members::const_iterator itr = m_members.begin();
         DeleteMember(itr->second->GetGUID(), true);
     }
     CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_GUILD);
     stmt->setUInt32(0, m_id);
     trans->Append(stmt);
     stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_GUILD_RANKS);
     stmt->setUInt32(0, m_id);
     trans->Append(stmt);
     stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_GUILD_BANK_TABS);
     stmt->setUInt32(0, m_id);
     trans->Append(stmt);
     // Free bank tab used memory and delete items stored in them
     _DeleteBankItems(trans, true);
     stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_GUILD_BANK_ITEMS);
     stmt->setUInt32(0, m_id);
     trans->Append(stmt);
     stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_GUILD_BANK_RIGHTS);
     stmt->setUInt32(0, m_id);
     trans->Append(stmt);
     stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_GUILD_BANK_EVENTLOGS);
     stmt->setUInt32(0, m_id);
     trans->Append(stmt);
     stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_GUILD_EVENTLOGS);
     stmt->setUInt32(0, m_id);
     trans->Append(stmt);
     CharacterDatabase.CommitTransaction(trans);
     sGuildMgr->RemoveGuild(m_id);
 }
References _BroadcastEvent(), _DeleteBankItems(), CHAR_DEL_GUILD, CHAR_DEL_GUILD_BANK_EVENTLOGS, CHAR_DEL_GUILD_BANK_ITEMS, CHAR_DEL_GUILD_BANK_RIGHTS, CHAR_DEL_GUILD_BANK_TABS, CHAR_DEL_GUILD_EVENTLOGS, CHAR_DEL_GUILD_RANKS, CharacterDatabase, DeleteMember(), GE_DISBANDED, m_id, m_members, PreparedStatementBase::setUInt32(), sGuildMgr, and sScriptMgr.
Referenced by DeleteMember(), HandleDisband(), guild_commandscript::HandleGuildDeleteCommand(), HandleLeaveMember(), and Validate().
GetBankTab() [1/2]
BankTab* Guild::GetBankTab (uint8 tabId) inline private
Definition at line 808 of file Guild.h.
 { return tabId < m_bankTabs.size() ? m_bankTabs[tabId] : nullptr; }
References m_bankTabs.
Referenced by _GetItem(), _RemoveItem(), _SendBankList(), HandleSetBankTabInfo(), SendBankTabText(), and SetBankTabText().
GetBankTab() [2/2]
const BankTab* Guild::GetBankTab (uint8 tabId) const inline private
Definition at line 809 of file Guild.h.
 { return tabId < m_bankTabs.size() ? m_bankTabs[tabId] : nullptr; }
References m_bankTabs.
GetCreatedDate()
time_t Guild::GetCreatedDate () const inline
Definition at line 763 of file Guild.h.
 { return m_createdDate; }
References m_createdDate.
Referenced by guild_commandscript::HandleGuildInfoCommand().
GetId()
uint32 Guild::GetId () const inline
Definition at line 679 of file Guild.h.
 { return m_id; }
References m_id.
Referenced by GuildMgr::AddGuild(), guild_commandscript::HandleGuildInfoCommand(), HandleLeaveMember(), HandleMemberDepositMoney(), HandleMemberWithdrawMoney(), and LoadMemberFromDB().
GetInfo()
std::string const& Guild::GetInfo () const inline
Definition at line 683 of file Guild.h.
 { return m_info; }
References m_info.
Referenced by guild_commandscript::HandleGuildInfoCommand().
GetLeaderGUID()
ObjectGuid Guild::GetLeaderGUID () const inline
Definition at line 680 of file Guild.h.
 { return m_leaderGuid; }
References m_leaderGuid.
Referenced by HandleAcceptMember(), guild_commandscript::HandleGuildInfoCommand(), HandleMemberDepositMoney(), and HandleMemberWithdrawMoney().
GetMember() [1/3]
Member* Guild::GetMember (ObjectGuid guid) inline
Definition at line 372 of file Guild.h.
     {
         Members::iterator itr = m_members.find(guid);
         return itr != m_members.end() ? itr->second : nullptr;
     }
References m_members.
GetMember() [2/3]
const Member* Guild::GetMember (ObjectGuid guid) const inline
Definition at line 367 of file Guild.h.
     {
         Members::const_iterator itr = m_members.find(guid);
         return itr != m_members.end() ? itr->second : nullptr;
     }
References m_members.
Referenced by _HasRankRight(), _IsLeader(), _MemberHasTabRights(), _SendBankList(), _UpdateMemberWithdrawSlots(), ChangeMemberRank(), HandleBuyBankTab(), HandleMemberLogout(), HandleMemberWithdrawMoney(), WorldSession::HandlePlayerLoginFromDB(), HandleRemoveMember(), HandleSetLeader(), HandleSetMemberNote(), HandleUpdateMemberRank(), OnPlayerStatusChange(), SendLoginInfo(), SendMoneyInfo(), SendPermissions(), UpdateMemberData(), and Validate().
GetMember() [3/3]
Member* Guild::GetMember (std::string const & name) inline
Definition at line 377 of file Guild.h.
     {
         for (Members::iterator itr = m_members.begin(); itr != m_members.end(); ++itr)
             if (itr->second->GetName() == name)
                 return itr->second;
         return nullptr;
     }
References m_members, and name.
GetMemberCount()
uint32 Guild::GetMemberCount () const inline
Definition at line 762 of file Guild.h.
 { return m_members.size(); }
References m_members.
Referenced by guild_commandscript::HandleGuildInfoCommand(), HandleMemberDepositMoney(), and HandleMemberWithdrawMoney().
GetMemberSize()
uint32 Guild::GetMemberSize () const inline
Definition at line 771 of file Guild.h.
 { return m_members.size(); }
References m_members.
GetMOTD()
std::string const& Guild::GetMOTD () const inline
Definition at line 682 of file Guild.h.
 { return m_motd; }
References m_motd.
Referenced by guild_commandscript::HandleGuildInfoCommand().
GetName()
std::string const& Guild::GetName () const inline
Definition at line 681 of file Guild.h.
 { return m_name; }
References m_name.
Referenced by guild_commandscript::HandleGuildInfoCommand(), HandleMemberDepositMoney(), HandleMemberWithdrawMoney(), ChatLogScript::OnChat(), and AchievementMgr::SendAchievementEarned().
GetRankInfo() [1/2]
RankInfo* Guild::GetRankInfo (uint8 rankId) inline private
Definition at line 796 of file Guild.h.
 { return rankId < _GetRanksSize() ? &m_ranks[rankId] : nullptr; }
References _GetRanksSize(), and m_ranks.
GetRankInfo() [2/2]
const RankInfo* Guild::GetRankInfo (uint8 rankId) const inline private
Definition at line 795 of file Guild.h.
 { return rankId < _GetRanksSize() ? &m_ranks[rankId] : nullptr; }
References _GetRanksSize(), and m_ranks.
Referenced by _GetRankBankMoneyPerDay(), _GetRankBankTabRights(), _GetRankBankTabSlotsPerDay(), _GetRankName(), _GetRankRights(), _SetRankBankMoneyPerDay(), _SetRankBankTabRightsAndSlots(), HandleSetRankInfo(), and Validate().
GetTotalBankMoney()
uint64 Guild::GetTotalBankMoney () const inline
Definition at line 761 of file Guild.h.
 { return m_bankMoney; }
References m_bankMoney.
Referenced by guild_commandscript::HandleGuildInfoCommand(), HandleMemberDepositMoney(), and HandleMemberWithdrawMoney().
HandleAcceptMember()
void Guild::HandleAcceptMember (WorldSession * session)
Definition at line 1550 of file Guild.cpp.
 {
     Player* player = session->GetPlayer();
     if (!sWorld->getBoolConfig(CONFIG_ALLOW_TWO_SIDE_INTERACTION_GUILD) &&
             player->GetTeamId() != sObjectMgr->GetPlayerTeamIdByGUID(GetLeaderGUID().GetCounter()))
         return;
     AddMember(player->GetGUID());
 }
References AddMember(), CONFIG_ALLOW_TWO_SIDE_INTERACTION_GUILD, Object::GetGUID(), GetLeaderGUID(), WorldSession::GetPlayer(), Player::GetTeamId(), sObjectMgr, and sWorld.
HandleAddNewRank()
void Guild::HandleAddNewRank (WorldSession * session, std::string const & name)
Definition at line 1675 of file Guild.cpp.
 {
     uint8 size = _GetRanksSize();
     if (size >= GUILD_RANKS_MAX_COUNT)
         return;
     // Only leader can add new rank
     if (_IsLeader(session->GetPlayer()))
         if (_CreateRank(name, GR_RIGHT_GCHATLISTEN | GR_RIGHT_GCHATSPEAK))
             _BroadcastEvent(GE_RANK_UPDATED, ObjectGuid::Empty, std::to_string(size).c_str(), name.c_str());
 }
References _BroadcastEvent(), _CreateRank(), _GetRanksSize(), _IsLeader(), ObjectGuid::Empty, GE_RANK_UPDATED, WorldSession::GetPlayer(), GR_RIGHT_GCHATLISTEN, GR_RIGHT_GCHATSPEAK, GUILD_RANKS_MAX_COUNT, name, and to_string().
HandleBuyBankTab()
void Guild::HandleBuyBankTab (WorldSession * session, uint8 tabId)
Hack to force client to update permissions
Definition at line 1467 of file Guild.cpp.
 {
     Player* player = session->GetPlayer();
     if (!player)
         return;
     Member const* member = GetMember(player->GetGUID());
     if (!member)
         return;
     if (_GetPurchasedTabsSize() >= GUILD_BANK_MAX_TABS)
         return;
     if (tabId != _GetPurchasedTabsSize())
         return;
     uint32 tabCost = _GetGuildBankTabPrice(tabId);
     if (!tabCost)
         return;
     if (!player->HasEnoughMoney(tabCost))                   // Should not happen, this is checked by client
         return;
     player->ModifyMoney(-int32(tabCost));
     _CreateNewBankTab();
     _BroadcastEvent(GE_BANK_TAB_PURCHASED);
     SendPermissions(session);
 }
References _BroadcastEvent(), _CreateNewBankTab(), _GetGuildBankTabPrice(), _GetPurchasedTabsSize(), GE_BANK_TAB_PURCHASED, Object::GetGUID(), GetMember(), WorldSession::GetPlayer(), GUILD_BANK_MAX_TABS, Player::HasEnoughMoney(), Player::ModifyMoney(), and SendPermissions().
HandleDisband()
void Guild::HandleDisband (WorldSession * session)
Definition at line 1798 of file Guild.cpp.
 {
     // Only leader can disband guild
     if (_IsLeader(session->GetPlayer()))
     {
         Disband();
         LOG_DEBUG("guild", "Guild Successfully Disbanded");
         delete this;
     }
 }
References _IsLeader(), Disband(), WorldSession::GetPlayer(), and LOG_DEBUG.
HandleInviteMember()
void Guild::HandleInviteMember (WorldSession * session, std::string const & name)
Definition at line 1497 of file Guild.cpp.
 {
     Player* pInvitee = ObjectAccessor::FindPlayerByName(name, false);
     if (!pInvitee)
     {
         SendCommandResult(session, GUILD_COMMAND_INVITE, ERR_GUILD_PLAYER_NOT_FOUND_S, name);
         return;
     }
     Player* player = session->GetPlayer();
     // Do not show invitations from ignored players
     if (pInvitee->GetSocial()->HasIgnore(player->GetGUID()))
         return;
     if (!sWorld->getBoolConfig(CONFIG_ALLOW_TWO_SIDE_INTERACTION_GUILD) && pInvitee->GetTeamId(true) != player->GetTeamId(true))
     {
         SendCommandResult(session, GUILD_COMMAND_INVITE, ERR_GUILD_NOT_ALLIED, name);
         return;
     }
     // Invited player cannot be in another guild
     if (pInvitee->GetGuildId())
     {
         SendCommandResult(session, GUILD_COMMAND_INVITE, ERR_ALREADY_IN_GUILD_S, name);
         return;
     }
     // Invited player cannot be invited
     if (pInvitee->GetGuildIdInvited())
     {
         SendCommandResult(session, GUILD_COMMAND_INVITE, ERR_ALREADY_INVITED_TO_GUILD_S, name);
         return;
     }
     // Inviting player must have rights to invite
     if (!_HasRankRight(player, GR_RIGHT_INVITE))
     {
         SendCommandResult(session, GUILD_COMMAND_INVITE, ERR_GUILD_PERMISSIONS);
         return;
     }
     SendCommandResult(session, GUILD_COMMAND_INVITE, ERR_GUILD_COMMAND_SUCCESS, name);
     LOG_DEBUG("guild", "Player %s invited %s to join his Guild", player->GetName().c_str(), name.c_str());
     pInvitee->SetGuildIdInvited(m_id);
     _LogEvent(GUILD_EVENT_LOG_INVITE_PLAYER, player->GetGUID(), pInvitee->GetGUID());
     WorldPacket data(SMSG_GUILD_INVITE, 8 + 10);              // Guess size
     data << player->GetName();
     data << m_name;
     pInvitee->GetSession()->SendPacket(&data);
     LOG_DEBUG("guild", "SMSG_GUILD_INVITE [%s]", pInvitee->GetName().c_str());
 }
References _HasRankRight(), _LogEvent(), CONFIG_ALLOW_TWO_SIDE_INTERACTION_GUILD, ERR_ALREADY_IN_GUILD_S, ERR_ALREADY_INVITED_TO_GUILD_S, ERR_GUILD_COMMAND_SUCCESS, ERR_GUILD_NOT_ALLIED, ERR_GUILD_PERMISSIONS, ERR_GUILD_PLAYER_NOT_FOUND_S, ObjectAccessor::FindPlayerByName(), Object::GetGUID(), Player::GetGuildId(), Player::GetGuildIdInvited(), WorldObject::GetName(), WorldSession::GetPlayer(), Player::GetSession(), Player::GetSocial(), Player::GetTeamId(), GR_RIGHT_INVITE, GUILD_COMMAND_INVITE, GUILD_EVENT_LOG_INVITE_PLAYER, PlayerSocial::HasIgnore(), LOG_DEBUG, m_id, m_name, name, SendCommandResult(), WorldSession::SendPacket(), Player::SetGuildIdInvited(), SMSG_GUILD_INVITE, and sWorld.
HandleLeaveMember()
void Guild::HandleLeaveMember (WorldSession * session)
Definition at line 1560 of file Guild.cpp.
 {
     Player* player = session->GetPlayer();
     bool disband = false;
     // If leader is leaving
     if (_IsLeader(player))
     {
         if (m_members.size() > 1)
             // Leader cannot leave if he is not the last member
             SendCommandResult(session, GUILD_COMMAND_QUIT, ERR_GUILD_LEADER_LEAVE);
         else
         {
             // Guild is disbanded if leader leaves.
             Disband();
             disband = true;
         }
     }
     else
     {
         DeleteMember(player->GetGUID(), false, false);
         _LogEvent(GUILD_EVENT_LOG_LEAVE_GUILD, player->GetGUID());
         _BroadcastEvent(GE_LEFT, player->GetGUID(), player->GetName().c_str());
         SendCommandResult(session, GUILD_COMMAND_QUIT, ERR_GUILD_COMMAND_SUCCESS, m_name);
     }
     sCalendarMgr->RemovePlayerGuildEventsAndSignups(player->GetGUID(), GetId());
     if (disband)
         delete this;
 }
References _BroadcastEvent(), _IsLeader(), _LogEvent(), DeleteMember(), Disband(), ERR_GUILD_COMMAND_SUCCESS, ERR_GUILD_LEADER_LEAVE, GE_LEFT, Object::GetGUID(), GetId(), WorldObject::GetName(), WorldSession::GetPlayer(), GUILD_COMMAND_QUIT, GUILD_EVENT_LOG_LEAVE_GUILD, m_members, m_name, sCalendarMgr, and SendCommandResult().
HandleMemberDepositMoney()
void Guild::HandleMemberDepositMoney (WorldSession * session, uint32 amount)
Definition at line 1714 of file Guild.cpp.
 {
     Player* player = session->GetPlayer();
     // Call script after validation and before money transfer.
     sScriptMgr->OnGuildMemberDepositMoney(this, player, amount);
     CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
     _ModifyBankMoney(trans, amount, true);
     player->ModifyMoney(-int32(amount));
     player->SaveGoldToDB(trans);
     _LogBankEvent(trans, GUILD_BANK_LOG_DEPOSIT_MONEY, uint8(0), player->GetGUID(), amount);
     CharacterDatabase.CommitTransaction(trans);
     std::string aux = Acore::Impl::ByteArrayToHexStr(reinterpret_cast<uint8*>(&m_bankMoney), 8, true);
     _BroadcastEvent(GE_BANK_MONEY_SET, ObjectGuid::Empty, aux.c_str());
     if (amount > 10 * GOLD)
         CharacterDatabase.PExecute("INSERT INTO log_money VALUES(%u, %u, \"%s\", \"%s\", %u, \"%s\", %u, \"<GB DEPOSIT> %s (guild id: %u, members: %u, new amount: %u, leader guid low: %u, char level: %u)\", NOW())",
             session->GetAccountId(), player->GetGUID().GetCounter(), player->GetName().c_str(), session->GetRemoteAddress().c_str(), 0, "", amount, GetName().c_str(), GetId(), GetMemberCount(), GetTotalBankMoney(), GetLeaderGUID().GetCounter(), player->getLevel());
 }
References _BroadcastEvent(), _LogBankEvent(), _ModifyBankMoney(), Acore::Impl::ByteArrayToHexStr(), CharacterDatabase, ObjectGuid::Empty, GE_BANK_MONEY_SET, WorldSession::GetAccountId(), ObjectGuid::GetCounter(), Object::GetGUID(), GetId(), GetLeaderGUID(), Unit::getLevel(), GetMemberCount(), WorldObject::GetName(), GetName(), WorldSession::GetPlayer(), WorldSession::GetRemoteAddress(), GetTotalBankMoney(), GOLD, GUILD_BANK_LOG_DEPOSIT_MONEY, m_bankMoney, Player::ModifyMoney(), Player::SaveGoldToDB(), and sScriptMgr.
HandleMemberLogout()
void Guild::HandleMemberLogout (WorldSession * session)
Definition at line 1786 of file Guild.cpp.
 {
     Player* player = session->GetPlayer();
     if (Member* member = GetMember(player->GetGUID()))
     {
         member->SetStats(player);
         member->UpdateLogoutTime();
         member->ResetFlags();
     }
     _BroadcastEvent(GE_SIGNED_OFF, player->GetGUID(), player->GetName().c_str());
 }
References _BroadcastEvent(), GE_SIGNED_OFF, Object::GetGUID(), GetMember(), WorldObject::GetName(), and WorldSession::GetPlayer().
HandleMemberWithdrawMoney()
bool Guild::HandleMemberWithdrawMoney (WorldSession * session, uint32 amount, bool repair = false)
Definition at line 1738 of file Guild.cpp.
 {
     //clamp amount to MAX_MONEY_AMOUNT, Players can't hold more than that anyway
     amount = std::min(amount, uint32(MAX_MONEY_AMOUNT));
     if (m_bankMoney < amount)                               // Not enough money in bank
         return false;
     Player* player = session->GetPlayer();
     Member* member = GetMember(player->GetGUID());
     if (!member)
         return false;
     if (uint32(_GetMemberRemainingMoney(member)) < amount)   // Check if we have enough slot/money today
         return false;
     // Call script after validation and before money transfer.
     sScriptMgr->OnGuildMemberWitdrawMoney(this, player, amount, repair);
     CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
     // Add money to player (if required)
     if (!repair)
     {
         if (!player->ModifyMoney(amount))
             return false;
         player->SaveGoldToDB(trans);
     }
     // Update remaining money amount
     member->UpdateBankWithdrawValue(trans, GUILD_BANK_MAX_TABS, amount);
     // Remove money from bank
     _ModifyBankMoney(trans, amount, false);
     // Log guild bank event
     _LogBankEvent(trans, repair ? GUILD_BANK_LOG_REPAIR_MONEY : GUILD_BANK_LOG_WITHDRAW_MONEY, uint8(0), player->GetGUID(), amount);
     CharacterDatabase.CommitTransaction(trans);
     if (amount > 10 * GOLD)
         CharacterDatabase.PExecute("INSERT INTO log_money VALUES(%u, %u, \"%s\", \"%s\", %u, \"%s\", %u, \"<GB WITHDRAW> %s (guild id: %u, members: %u, new amount: %u, leader guid low: %u, char level: %u)\", NOW())",
             session->GetAccountId(), player->GetGUID().GetCounter(), player->GetName().c_str(), session->GetRemoteAddress().c_str(), 0, "", amount, GetName().c_str(), GetId(), GetMemberCount(), GetTotalBankMoney(), GetLeaderGUID().GetCounter(), player->getLevel());
     std::string aux = Acore::Impl::ByteArrayToHexStr(reinterpret_cast<uint8*>(&m_bankMoney), 8, true);
     _BroadcastEvent(GE_BANK_MONEY_SET, ObjectGuid::Empty, aux.c_str());
     return true;
 }
References _BroadcastEvent(), _GetMemberRemainingMoney(), _LogBankEvent(), _ModifyBankMoney(), Acore::Impl::ByteArrayToHexStr(), CharacterDatabase, ObjectGuid::Empty, GE_BANK_MONEY_SET, WorldSession::GetAccountId(), ObjectGuid::GetCounter(), Object::GetGUID(), GetId(), GetLeaderGUID(), Unit::getLevel(), GetMember(), GetMemberCount(), WorldObject::GetName(), GetName(), WorldSession::GetPlayer(), WorldSession::GetRemoteAddress(), GetTotalBankMoney(), GOLD, GUILD_BANK_LOG_REPAIR_MONEY, GUILD_BANK_LOG_WITHDRAW_MONEY, GUILD_BANK_MAX_TABS, m_bankMoney, MAX_MONEY_AMOUNT, min, Player::ModifyMoney(), Player::SaveGoldToDB(), sScriptMgr, and Guild::Member::UpdateBankWithdrawValue().
Referenced by Player::DurabilityRepair().
HandleQuery()
void Guild::HandleQuery (WorldSession * session)
Definition at line 1314 of file Guild.cpp.
 {
     WorldPacket data(SMSG_GUILD_QUERY_RESPONSE, 8 * 32 + 200);      // Guess size
     data << uint32(m_id);
     data << m_name;
     // Rank name
     for (uint8 i = 0; i < GUILD_RANKS_MAX_COUNT; ++i)               // Always show 10 ranks
     {
         if (i < _GetRanksSize())
             data << m_ranks[i].GetName();
         else
             data << uint8(0);                                       // Empty string
     }
     m_emblemInfo.WritePacket(data);
     data << uint32(_GetRanksSize());                                // Number of ranks used
     session->SendPacket(&data);
     LOG_DEBUG("guild", "SMSG_GUILD_QUERY_RESPONSE [%s]", session->GetPlayerInfo().c_str());
 }
References _GetRanksSize(), WorldSession::GetPlayerInfo(), GUILD_RANKS_MAX_COUNT, LOG_DEBUG, m_emblemInfo, m_id, m_name, m_ranks, WorldSession::SendPacket(), SMSG_GUILD_QUERY_RESPONSE, and EmblemInfo::WritePacket().
Referenced by HandleSetEmblem().
HandleRemoveLowestRank()
void Guild::HandleRemoveLowestRank (WorldSession * session)
Definition at line 1687 of file Guild.cpp.
 {
     HandleRemoveRank(session, _GetLowestRankId());
 }
References _GetLowestRankId(), and HandleRemoveRank().
HandleRemoveMember()
void Guild::HandleRemoveMember (WorldSession * session, std::string const & name)
Definition at line 1594 of file Guild.cpp.
 {
     Player* player = session->GetPlayer();
     // Player must have rights to remove members
     if (!_HasRankRight(player, GR_RIGHT_REMOVE))
         SendCommandResult(session, GUILD_COMMAND_REMOVE, ERR_GUILD_PERMISSIONS);
     else if (Member* member = GetMember(name))
     {
         // Guild masters cannot be removed
         if (member->IsRank(GR_GUILDMASTER))
             SendCommandResult(session, GUILD_COMMAND_REMOVE, ERR_GUILD_LEADER_LEAVE);
         // Do not allow to remove player with the same rank or higher
         else
         {
             Member const* memberMe = GetMember(player->GetGUID());
             if (!memberMe || member->IsRankNotLower(memberMe->GetRankId()))
                 SendCommandResult(session, GUILD_COMMAND_REMOVE, ERR_GUILD_RANK_TOO_HIGH_S, name);
             else
             {
                 ObjectGuid guid = member->GetGUID();
                 // After call to DeleteMember pointer to member becomes invalid
                 DeleteMember(guid, false, true);
                 _LogEvent(GUILD_EVENT_LOG_UNINVITE_PLAYER, player->GetGUID(), guid);
                 _BroadcastEvent(GE_REMOVED, ObjectGuid::Empty, name.c_str(), player->GetName().c_str());
             }
         }
     }
 }
References _BroadcastEvent(), _HasRankRight(), _LogEvent(), DeleteMember(), ObjectGuid::Empty, ERR_GUILD_LEADER_LEAVE, ERR_GUILD_PERMISSIONS, ERR_GUILD_RANK_TOO_HIGH_S, GE_REMOVED, Object::GetGUID(), GetMember(), WorldObject::GetName(), WorldSession::GetPlayer(), Guild::Member::GetRankId(), GR_GUILDMASTER, GR_RIGHT_REMOVE, GUILD_COMMAND_REMOVE, GUILD_EVENT_LOG_UNINVITE_PLAYER, Guild::Member::IsRankNotLower(), name, and SendCommandResult().
HandleRemoveRank()
void Guild::HandleRemoveRank (WorldSession * session, uint8 rankId)
Definition at line 1692 of file Guild.cpp.
 {
     // Cannot remove rank if total count is minimum allowed by the client or is not leader
     if (_GetRanksSize() <= GUILD_RANKS_MIN_COUNT || rankId >= _GetRanksSize() || !_IsLeader(session->GetPlayer()))
         return;
     // Delete bank rights for rank
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_GUILD_BANK_RIGHTS_FOR_RANK);
     stmt->setUInt32(0, m_id);
     stmt->setUInt8(1, rankId);
     CharacterDatabase.Execute(stmt);
     // Delete rank
     stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_GUILD_LOWEST_RANK);
     stmt->setUInt32(0, m_id);
     stmt->setUInt8(1, rankId);
     CharacterDatabase.Execute(stmt);
     m_ranks.pop_back();
     _BroadcastEvent(GE_RANK_DELETED);
 }
References _BroadcastEvent(), _GetRanksSize(), _IsLeader(), CHAR_DEL_GUILD_BANK_RIGHTS_FOR_RANK, CHAR_DEL_GUILD_LOWEST_RANK, CharacterDatabase, GE_RANK_DELETED, WorldSession::GetPlayer(), GUILD_RANKS_MIN_COUNT, m_id, m_ranks, PreparedStatementBase::setUInt32(), and PreparedStatementBase::setUInt8().
Referenced by HandleRemoveLowestRank().
HandleRoster()
void Guild::HandleRoster (WorldSession * session)
Definition at line 1295 of file Guild.cpp.
 {
     // Guess size
     WorldPacket data(SMSG_GUILD_ROSTER, (4 + m_motd.length() + 1 + m_info.length() + 1 + 4 + _GetRanksSize() * (4 + 4 + GUILD_BANK_MAX_TABS * (4 + 4)) + m_members.size() * 50));
     data << uint32(m_members.size());
     data << m_motd;
     data << m_info;
     data << uint32(_GetRanksSize());
     for (Ranks::const_iterator ritr = m_ranks.begin(); ritr != m_ranks.end(); ++ritr)
         ritr->WritePacket(data);
     for (Members::const_iterator itr = m_members.begin(); itr != m_members.end(); ++itr)
         itr->second->WritePacket(data, _HasRankRight(session->GetPlayer(), GR_RIGHT_VIEWOFFNOTE));
     LOG_DEBUG("guild", "SMSG_GUILD_ROSTER [%s]", session->GetPlayerInfo().c_str());
     session->SendPacket(&data);
 }
References _GetRanksSize(), _HasRankRight(), WorldSession::GetPlayer(), WorldSession::GetPlayerInfo(), GR_RIGHT_VIEWOFFNOTE, GUILD_BANK_MAX_TABS, LOG_DEBUG, m_info, m_members, m_motd, m_ranks, WorldSession::SendPacket(), and SMSG_GUILD_ROSTER.
Referenced by HandleSetMemberNote(), and SendLoginInfo().
HandleSetBankTabInfo()
void Guild::HandleSetBankTabInfo (WorldSession * session, uint8 tabId, std::string const & name, std::string const & icon)
Definition at line 1417 of file Guild.cpp.
 {
     BankTab* tab = GetBankTab(tabId);
     if (!tab)
     {
         LOG_ERROR("guild", "Guild::HandleSetBankTabInfo: Player %s trying to change bank tab info from unexisting tab %d.",
                        session->GetPlayerInfo().c_str(), tabId);
         return;
     }
     tab->SetInfo(name, icon);
     _BroadcastEvent(GE_BANK_TAB_UPDATED, ObjectGuid::Empty, std::to_string(tabId).c_str(), name.c_str(), icon.c_str());
 }
References _BroadcastEvent(), ObjectGuid::Empty, GE_BANK_TAB_UPDATED, GetBankTab(), WorldSession::GetPlayerInfo(), LOG_ERROR, name, Guild::BankTab::SetInfo(), and to_string().
HandleSetEmblem()
void Guild::HandleSetEmblem (WorldSession * session, const EmblemInfo & emblemInfo)
Definition at line 1378 of file Guild.cpp.
 {
     Player* player = session->GetPlayer();
     if (!_IsLeader(player))
         SendSaveEmblemResult(session, ERR_GUILDEMBLEM_NOTGUILDMASTER); // "Only guild leaders can create emblems."
     else if (!player->HasEnoughMoney(EMBLEM_PRICE))
         SendSaveEmblemResult(session, ERR_GUILDEMBLEM_NOTENOUGHMONEY); // "You can't afford to do that."
     else
     {
         player->ModifyMoney(-int32(EMBLEM_PRICE));
         m_emblemInfo = emblemInfo;
         m_emblemInfo.SaveToDB(m_id);
         SendSaveEmblemResult(session, ERR_GUILDEMBLEM_SUCCESS); // "Guild Emblem saved."
         HandleQuery(session);
     }
 }
References _IsLeader(), EMBLEM_PRICE, ERR_GUILDEMBLEM_NOTENOUGHMONEY, ERR_GUILDEMBLEM_NOTGUILDMASTER, ERR_GUILDEMBLEM_SUCCESS, WorldSession::GetPlayer(), HandleQuery(), Player::HasEnoughMoney(), m_emblemInfo, m_id, Player::ModifyMoney(), EmblemInfo::SaveToDB(), and SendSaveEmblemResult().
HandleSetInfo()
void Guild::HandleSetInfo (WorldSession * session, std::string const & info)
Definition at line 1359 of file Guild.cpp.
 {
     if (m_info == info)
         return;
     // Player must have rights to set guild's info
     if (_HasRankRight(session->GetPlayer(), GR_RIGHT_MODIFY_GUILD_INFO))
     {
         m_info = info;
         sScriptMgr->OnGuildInfoChanged(this, info);
         CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_GUILD_INFO);
         stmt->setString(0, info);
         stmt->setUInt32(1, m_id);
         CharacterDatabase.Execute(stmt);
     }
 }
References _HasRankRight(), CHAR_UPD_GUILD_INFO, CharacterDatabase, WorldSession::GetPlayer(), GR_RIGHT_MODIFY_GUILD_INFO, m_id, m_info, PreparedStatementBase::setString(), PreparedStatementBase::setUInt32(), and sScriptMgr.
HandleSetLeader()
void Guild::HandleSetLeader (WorldSession * session, std::string const & name)
Definition at line 1398 of file Guild.cpp.
 {
     Player* player = session->GetPlayer();
     // Only leader can assign new leader
     if (!_IsLeader(player))
         SendCommandResult(session, GUILD_COMMAND_CHANGE_LEADER, ERR_GUILD_PERMISSIONS);
     // Old leader must be a member of guild
     else if (Member* pOldLeader = GetMember(player->GetGUID()))
     {
         // New leader must be a member of guild
         if (Member* pNewLeader = GetMember(name))
         {
             _SetLeaderGUID(pNewLeader);
             pOldLeader->ChangeRank(GR_OFFICER);
             _BroadcastEvent(GE_LEADER_CHANGED, ObjectGuid::Empty, player->GetName().c_str(), name.c_str());
         }
     }
 }
References _BroadcastEvent(), _IsLeader(), _SetLeaderGUID(), ObjectGuid::Empty, ERR_GUILD_PERMISSIONS, GE_LEADER_CHANGED, Object::GetGUID(), GetMember(), WorldObject::GetName(), WorldSession::GetPlayer(), GR_OFFICER, GUILD_COMMAND_CHANGE_LEADER, name, and SendCommandResult().
HandleSetMemberNote()
void Guild::HandleSetMemberNote (WorldSession * session, std::string const & name, std::string const & note, bool officer)
Definition at line 1431 of file Guild.cpp.
 {
     // Player must have rights to set public/officer note
     if (!_HasRankRight(session->GetPlayer(), isPublic ? GR_RIGHT_EPNOTE : GR_RIGHT_EOFFNOTE))
         SendCommandResult(session, GUILD_COMMAND_PUBLIC_NOTE, ERR_GUILD_PERMISSIONS);
     else if (Member* member = GetMember(name))
     {
         if (isPublic)
             member->SetPublicNote(note);
         else
             member->SetOfficerNote(note);
         HandleRoster(session);
     }
 }
References _HasRankRight(), ERR_GUILD_PERMISSIONS, GetMember(), WorldSession::GetPlayer(), GR_RIGHT_EOFFNOTE, GR_RIGHT_EPNOTE, GUILD_COMMAND_PUBLIC_NOTE, HandleRoster(), name, and SendCommandResult().
HandleSetMOTD()
void Guild::HandleSetMOTD (WorldSession * session, std::string const & motd)
Definition at line 1336 of file Guild.cpp.
 {
     if (m_motd == motd)
         return;
     // Player must have rights to set MOTD
     if (!_HasRankRight(session->GetPlayer(), GR_RIGHT_SETMOTD))
         SendCommandResult(session, GUILD_COMMAND_EDIT_MOTD, ERR_GUILD_PERMISSIONS);
     else
     {
         m_motd = motd;
         sScriptMgr->OnGuildMOTDChanged(this, motd);
         CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_UPD_GUILD_MOTD);
         stmt->setString(0, motd);
         stmt->setUInt32(1, m_id);
         CharacterDatabase.Execute(stmt);
         _BroadcastEvent(GE_MOTD, ObjectGuid::Empty, motd.c_str());
     }
 }
References _BroadcastEvent(), _HasRankRight(), CHAR_UPD_GUILD_MOTD, CharacterDatabase, ObjectGuid::Empty, ERR_GUILD_PERMISSIONS, GE_MOTD, WorldSession::GetPlayer(), GR_RIGHT_SETMOTD, GUILD_COMMAND_EDIT_MOTD, m_id, m_motd, SendCommandResult(), PreparedStatementBase::setString(), PreparedStatementBase::setUInt32(), and sScriptMgr.
HandleSetRankInfo()
void Guild::HandleSetRankInfo (WorldSession * session, uint8 rankId, std::string const & name, uint32 rights, uint32 moneyPerDay, GuildBankRightsAndSlotsVec rightsAndSlots)
Definition at line 1447 of file Guild.cpp.
 {
     // Only leader can modify ranks
     if (!_IsLeader(session->GetPlayer()))
         SendCommandResult(session, GUILD_COMMAND_CHANGE_RANK, ERR_GUILD_PERMISSIONS);
     else if (RankInfo* rankInfo = GetRankInfo(rankId))
     {
         LOG_DEBUG("guild", "Changed RankName to '%s', rights to 0x%08X", name.c_str(), rights);
         rankInfo->SetName(name);
         rankInfo->SetRights(rights);
         _SetRankBankMoneyPerDay(rankId, moneyPerDay);
         for (GuildBankRightsAndSlotsVec::const_iterator itr = rightsAndSlots.begin(); itr != rightsAndSlots.end(); ++itr)
             _SetRankBankTabRightsAndSlots(rankId, *itr);
         _BroadcastEvent(GE_RANK_UPDATED, ObjectGuid::Empty, std::to_string(rankId).c_str(), name.c_str());
     }
 }
References _BroadcastEvent(), _IsLeader(), _SetRankBankMoneyPerDay(), _SetRankBankTabRightsAndSlots(), ObjectGuid::Empty, ERR_GUILD_PERMISSIONS, GE_RANK_UPDATED, WorldSession::GetPlayer(), GetRankInfo(), GUILD_COMMAND_CHANGE_RANK, LOG_DEBUG, name, SendCommandResult(), and to_string().
Referenced by WorldSession::HandleGuildRankOpcode().
HandleUpdateMemberRank()
void Guild::HandleUpdateMemberRank (WorldSession * session, std::string const & name, bool demote)
Definition at line 1623 of file Guild.cpp.
 {
     Player* player = session->GetPlayer();
     GuildCommandType type = demote ? GUILD_COMMAND_DEMOTE : GUILD_COMMAND_PROMOTE;
     // Player must have rights to promote
     if (!_HasRankRight(player, demote ? GR_RIGHT_DEMOTE : GR_RIGHT_PROMOTE))
         SendCommandResult(session, type, ERR_GUILD_PERMISSIONS);
     // Promoted player must be a member of guild
     else if (Member* member = GetMember(name))
     {
         // Player cannot promote himself
         if (member->IsSamePlayer(player->GetGUID()))
         {
             SendCommandResult(session, type, ERR_GUILD_NAME_INVALID);
             return;
         }
         Member const* memberMe = GetMember(player->GetGUID());
         uint8 rankId = memberMe->GetRankId();
         if (demote)
         {
             // Player can demote only lower rank members
             if (member->IsRankNotLower(rankId))
             {
                 SendCommandResult(session, type, ERR_GUILD_RANK_TOO_HIGH_S, name);
                 return;
             }
             // Lowest rank cannot be demoted
             if (member->GetRankId() >= _GetLowestRankId())
             {
                 SendCommandResult(session, type, ERR_GUILD_RANK_TOO_LOW_S, name);
                 return;
             }
         }
         else
         {
             // Allow to promote only to lower rank than member's rank
             // member->GetRankId() + 1 is the highest rank that current player can promote to
             if (member->IsRankNotLower(rankId + 1))
             {
                 SendCommandResult(session, type, ERR_GUILD_RANK_TOO_HIGH_S, name);
                 return;
             }
         }
         uint32 newRankId = member->GetRankId() + (demote ? 1 : -1);
         member->ChangeRank(newRankId);
         _LogEvent(demote ? GUILD_EVENT_LOG_DEMOTE_PLAYER : GUILD_EVENT_LOG_PROMOTE_PLAYER, player->GetGUID(), member->GetGUID(), newRankId);
         _BroadcastEvent(demote ? GE_DEMOTION : GE_PROMOTION, ObjectGuid::Empty, player->GetName().c_str(), name.c_str(), _GetRankName(newRankId).c_str());
     }
 }
References _BroadcastEvent(), _GetLowestRankId(), _GetRankName(), _HasRankRight(), _LogEvent(), ObjectGuid::Empty, ERR_GUILD_NAME_INVALID, ERR_GUILD_PERMISSIONS, ERR_GUILD_RANK_TOO_HIGH_S, ERR_GUILD_RANK_TOO_LOW_S, GE_DEMOTION, GE_PROMOTION, Object::GetGUID(), GetMember(), WorldObject::GetName(), WorldSession::GetPlayer(), Guild::Member::GetRankId(), GR_RIGHT_DEMOTE, GR_RIGHT_PROMOTE, GUILD_COMMAND_DEMOTE, GUILD_COMMAND_PROMOTE, GUILD_EVENT_LOG_DEMOTE_PLAYER, GUILD_EVENT_LOG_PROMOTE_PLAYER, name, and SendCommandResult().
LoadBankEventLogFromDB()
bool Guild::LoadBankEventLogFromDB (Field * fields)
Definition at line 1995 of file Guild.cpp.
 {
     uint8 dbTabId = fields[1].GetUInt8();
     bool isMoneyTab = (dbTabId == GUILD_BANK_MONEY_LOGS_TAB);
     if (dbTabId < _GetPurchasedTabsSize() || isMoneyTab)
     {
         uint8 tabId = isMoneyTab ? uint8(GUILD_BANK_MAX_TABS) : dbTabId;
         LogHolder* pLog = m_bankEventLog[tabId];
         if (pLog->CanInsert())
         {
             ObjectGuid::LowType guid = fields[2].GetUInt32();
             GuildBankEventLogTypes eventType = GuildBankEventLogTypes(fields[3].GetUInt8());
             if (BankEventLogEntry::IsMoneyEvent(eventType))
             {
                 if (!isMoneyTab)
                 {
                     LOG_ERROR("guild", "GuildBankEventLog ERROR: MoneyEvent(LogGuid: %u, Guild: %u) does not belong to money tab (%u), ignoring...", guid, m_id, dbTabId);
                     return false;
                 }
             }
             else if (isMoneyTab)
             {
                 LOG_ERROR("guild", "GuildBankEventLog ERROR: non-money event (LogGuid: %u, Guild: %u) belongs to money tab, ignoring...", guid, m_id);
                 return false;
             }
             pLog->LoadEvent(new BankEventLogEntry(
                                 m_id,                                                       // guild id
                                 guid,                                                       // guid
                                 time_t(fields[8].GetUInt32()),                              // timestamp
                                 dbTabId,                                                    // tab id
                                 eventType,                                                  // event type
                                 ObjectGuid::Create<HighGuid::Player>(fields[4].GetUInt32()), // player guid
                                 fields[5].GetUInt32(),                                      // item or money
                                 fields[6].GetUInt16(),                                      // itam stack count
                                 fields[7].GetUInt8()));                                     // dest tab id
         }
     }
     return true;
 }
References _GetPurchasedTabsSize(), Guild::LogHolder::CanInsert(), Field::GetUInt32(), Field::GetUInt8(), GUILD_BANK_MAX_TABS, GUILD_BANK_MONEY_LOGS_TAB, Guild::BankEventLogEntry::IsMoneyEvent(), Guild::LogHolder::LoadEvent(), LOG_ERROR, m_bankEventLog, and m_id.
LoadBankItemFromDB()
bool Guild::LoadBankItemFromDB (Field * fields)
Definition at line 2044 of file Guild.cpp.
 {
     uint8 tabId = fields[12].GetUInt8();
     if (tabId >= _GetPurchasedTabsSize())
     {
         LOG_ERROR("guild", "Invalid tab for item (GUID: %u, id: #%u) in guild bank, skipped.",
                        fields[14].GetUInt32(), fields[15].GetUInt32());
         return false;
     }
     return m_bankTabs[tabId]->LoadItemFromDB(fields);
 }
References _GetPurchasedTabsSize(), Field::GetUInt8(), LOG_ERROR, and m_bankTabs.
LoadBankRightFromDB()
void Guild::LoadBankRightFromDB (Field * fields)
Definition at line 1970 of file Guild.cpp.
 {
     // tabId              rights                slots
     GuildBankRightsAndSlots rightsAndSlots(fields[1].GetUInt8(), fields[3].GetUInt8(), fields[4].GetUInt32());
     // rankId
     _SetRankBankTabRightsAndSlots(fields[2].GetUInt8(), rightsAndSlots, false);
 }
References _SetRankBankTabRightsAndSlots().
LoadBankTabFromDB()
void Guild::LoadBankTabFromDB (Field * fields)
Definition at line 2035 of file Guild.cpp.
 {
     uint8 tabId = fields[1].GetUInt8();
     if (tabId >= _GetPurchasedTabsSize())
         LOG_ERROR("guild", "Invalid tab (tabId: %u) in guild bank, skipped.", tabId);
     else
         m_bankTabs[tabId]->LoadFromDB(fields);
 }
References _GetPurchasedTabsSize(), Field::GetUInt8(), LOG_ERROR, and m_bankTabs.
LoadEventLogFromDB()
bool Guild::LoadEventLogFromDB (Field * fields)
Definition at line 1978 of file Guild.cpp.
 {
     if (m_eventLog->CanInsert())
     {
         m_eventLog->LoadEvent(new EventLogEntry(
                                   m_id,                                                         // guild id
                                   fields[1].GetUInt32(),                                        // guid
                                   time_t(fields[6].GetUInt32()),                                // timestamp
                                   GuildEventLogTypes(fields[2].GetUInt8()),                     // event type
                                   ObjectGuid::Create<HighGuid::Player>(fields[3].GetUInt32()),  // player guid 1
                                   ObjectGuid::Create<HighGuid::Player>(fields[4].GetUInt32()),  // player guid 2
                                   fields[5].GetUInt8()));                                       // rank
         return true;
     }
     return false;
 }
References Guild::LogHolder::CanInsert(), Guild::LogHolder::LoadEvent(), m_eventLog, and m_id.
LoadFromDB()
bool Guild::LoadFromDB (Field * fields)
Definition at line 1922 of file Guild.cpp.
 {
     m_id            = fields[0].GetUInt32();
     m_name          = fields[1].GetString();
     m_leaderGuid    = ObjectGuid::Create<HighGuid::Player>(fields[2].GetUInt32());
     m_emblemInfo.LoadFromDB(fields);
     m_info          = fields[8].GetString();
     m_motd          = fields[9].GetString();
     m_createdDate   = time_t(fields[10].GetUInt32());
     m_bankMoney     = fields[11].GetUInt64();
     uint8 purchasedTabs = uint8(fields[12].GetUInt64());
     if (purchasedTabs > GUILD_BANK_MAX_TABS)
         purchasedTabs = GUILD_BANK_MAX_TABS;
     m_bankTabs.resize(purchasedTabs);
     for (uint8 i = 0; i < purchasedTabs; ++i)
         m_bankTabs[i] = new BankTab(m_id, i);
     _CreateLogHolders();
     return true;
 }
References _CreateLogHolders(), Field::GetString(), Field::GetUInt32(), Field::GetUInt64(), GUILD_BANK_MAX_TABS, EmblemInfo::LoadFromDB(), m_bankMoney, m_bankTabs, m_createdDate, m_emblemInfo, m_id, m_info, m_leaderGuid, m_motd, and m_name.
Referenced by GuildMgr::LoadGuilds().
LoadMemberFromDB()
bool Guild::LoadMemberFromDB (Field * fields)
Definition at line 1954 of file Guild.cpp.
 {
     ObjectGuid memberGUID = ObjectGuid::Create<HighGuid::Player>(fields[1].GetUInt32());
     Member* member = new Member(m_id, memberGUID, fields[2].GetUInt8());
     if (!member->LoadFromDB(fields))
     {
         _DeleteMemberFromDB(memberGUID.GetCounter());
         delete member;
         return false;
     }
     m_members[memberGUID] = member;
     sWorld->UpdateGlobalPlayerGuild(memberGUID.GetCounter(), GetId());
     return true;
 }
References _DeleteMemberFromDB(), ObjectGuid::GetCounter(), GetId(), Guild::Member::LoadFromDB(), m_id, m_members, and sWorld.
LoadRankFromDB()
void Guild::LoadRankFromDB (Field * fields)
Definition at line 1945 of file Guild.cpp.
 {
     RankInfo rankInfo(m_id);
     rankInfo.LoadFromDB(fields);
     m_ranks.push_back(rankInfo);
 }
References Guild::RankInfo::LoadFromDB(), m_id, and m_ranks.
MassInviteToEvent()
void Guild::MassInviteToEvent (WorldSession * session, uint32 minLevel, uint32 maxLevel, uint32 minRank)
Definition at line 2157 of file Guild.cpp.
 {
     uint32 count = 0;
     WorldPacket data(SMSG_CALENDAR_FILTER_GUILD);
     data << uint32(count); // count placeholder
     for (Members::const_iterator itr = m_members.begin(); itr != m_members.end(); ++itr)
     {
         // not sure if needed, maybe client checks it as well
         if (count >= CALENDAR_MAX_INVITES)
         {
             if (Player* player = session->GetPlayer())
                 sCalendarMgr->SendCalendarCommandResult(player->GetGUID(), CALENDAR_ERROR_INVITES_EXCEEDED);
             return;
         }
         Member* member = itr->second;
         uint32 level = Player::GetLevelFromStorage(member->GetGUID().GetCounter());
         if (member->GetGUID() != session->GetPlayer()->GetGUID() && level >= minLevel && level <= maxLevel && member->IsRankNotLower(minRank))
         {
             data.appendPackGUID(member->GetGUID().GetRawValue());
             data << uint8(0); // unk
             ++count;
         }
     }
     data.put<uint32>(0, count);
     session->SendPacket(&data);
 }
References CALENDAR_ERROR_INVITES_EXCEEDED, CALENDAR_MAX_INVITES, count(), ObjectGuid::GetCounter(), Guild::Member::GetGUID(), Object::GetGUID(), Player::GetLevelFromStorage(), WorldSession::GetPlayer(), ObjectGuid::GetRawValue(), m_members, sCalendarMgr, WorldSession::SendPacket(), and SMSG_CALENDAR_FILTER_GUILD.
ModifyBankMoney()
bool Guild::ModifyBankMoney (CharacterDatabaseTransaction trans, const uint64 & amount, bool add) inline
Definition at line 770 of file Guild.h.
 { return _ModifyBankMoney(trans, amount, add); }
References _ModifyBankMoney().
OnPlayerStatusChange()
void Guild::OnPlayerStatusChange (Player * player, uint32 flag, bool state)
Definition at line 1285 of file Guild.cpp.
 {
     if (Member* member = GetMember(player->GetGUID()))
     {
         if (state)
             member->AddFlag(flag);
         else member->RemFlag(flag);
     }
 }
References Object::GetGUID(), and GetMember().
ResetTimes()
void Guild::ResetTimes ()
Definition at line 2901 of file Guild.cpp.
 {
     for (Members::const_iterator itr = m_members.begin(); itr != m_members.end(); ++itr)
         itr->second->ResetValues();
     _BroadcastEvent(GE_BANK_TAB_AND_MONEY_UPDATED);
 }
References _BroadcastEvent(), GE_BANK_TAB_AND_MONEY_UPDATED, and m_members.
SendBankLog()
void Guild::SendBankLog (WorldSession * session, uint8 tabId) const
Definition at line 1830 of file Guild.cpp.
 {
     // GUILD_BANK_MAX_TABS send by client for money log
     if (tabId < _GetPurchasedTabsSize() || tabId == GUILD_BANK_MAX_TABS)
     {
         const LogHolder* pLog = m_bankEventLog[tabId];
         WorldPacket data(MSG_GUILD_BANK_LOG_QUERY, pLog->GetSize() * (4 * 4 + 1) + 1 + 1);
         data << uint8(tabId);
         pLog->WritePacket(data);
         session->SendPacket(&data);
         LOG_DEBUG("guild", "MSG_GUILD_BANK_LOG_QUERY [%s]", session->GetPlayerInfo().c_str());
     }
 }
References _GetPurchasedTabsSize(), WorldSession::GetPlayerInfo(), Guild::LogHolder::GetSize(), GUILD_BANK_MAX_TABS, LOG_DEBUG, m_bankEventLog, MSG_GUILD_BANK_LOG_QUERY, WorldSession::SendPacket(), and Guild::LogHolder::WritePacket().
SendBankTabData()
void Guild::SendBankTabData (WorldSession * session, uint8 tabId) const
Definition at line 1844 of file Guild.cpp.
 {
     if (tabId < _GetPurchasedTabsSize())
         _SendBankContent(session, tabId);
 }
References _GetPurchasedTabsSize(), and _SendBankContent().
SendBankTabsInfo()
void Guild::SendBankTabsInfo (WorldSession * session, bool showTabs = false) const
Definition at line 1850 of file Guild.cpp.
 {
     _SendBankList(session, 0, sendAllSlots);
 }
References _SendBankList().
Referenced by WorldSession::HandleGuildBankerActivate(), and SendLoginInfo().
SendBankTabText()
void Guild::SendBankTabText (WorldSession * session, uint8 tabId) const
Definition at line 1855 of file Guild.cpp.
 {
     if (BankTab const* tab = GetBankTab(tabId))
         tab->SendText(this, session);
 }
References GetBankTab().
SendCommandResult()
void Guild::SendCommandResult (WorldSession * session, GuildCommandType type, GuildCommandError errCode, std::string const & param = "") static
Definition at line 104 of file Guild.cpp.
 {
     WorldPacket data(SMSG_GUILD_COMMAND_RESULT, 8 + param.size() + 1);
     data << uint32(type);
     data << param;
     data << uint32(errCode);
     session->SendPacket(&data);
     LOG_DEBUG("guild", "SMSG_GUILD_COMMAND_RESULT [%s]: Type: %u, code: %u, param: %s", session->GetPlayerInfo().c_str(), type, errCode, param.c_str());
 }
References WorldSession::GetPlayerInfo(), LOG_DEBUG, WorldSession::SendPacket(), and SMSG_GUILD_COMMAND_RESULT.
Referenced by WorldSession::HandleGuildBankerActivate(), WorldSession::HandleGuildRosterOpcode(), HandleInviteMember(), HandleLeaveMember(), WorldSession::HandleOfferPetitionOpcode(), WorldSession::HandlePetitionBuyOpcode(), WorldSession::HandlePetitionRenameOpcode(), WorldSession::HandlePetitionSignOpcode(), HandleRemoveMember(), HandleSetLeader(), HandleSetMemberNote(), HandleSetMOTD(), HandleSetRankInfo(), WorldSession::HandleTurnInPetitionOpcode(), and HandleUpdateMemberRank().
SendEventLog()
void Guild::SendEventLog (WorldSession * session) const
Definition at line 1822 of file Guild.cpp.
 {
     WorldPacket data(MSG_GUILD_EVENT_LOG_QUERY, 1 + m_eventLog->GetSize() * (1 + 8 + 4));
     m_eventLog->WritePacket(data);
     session->SendPacket(&data);
     LOG_DEBUG("guild", "MSG_GUILD_EVENT_LOG_QUERY [%s]", session->GetPlayerInfo().c_str());
 }
References WorldSession::GetPlayerInfo(), Guild::LogHolder::GetSize(), LOG_DEBUG, m_eventLog, MSG_GUILD_EVENT_LOG_QUERY, WorldSession::SendPacket(), and Guild::LogHolder::WritePacket().
SendInfo()
void Guild::SendInfo (WorldSession * session) const
Definition at line 1810 of file Guild.cpp.
 {
     WorldPacket data(SMSG_GUILD_INFO, m_name.size() + 4 + 4 + 4);
     data << m_name;
     data.AppendPackedTime(m_createdDate);           // 3.x (prev. year + month + day)
     data << uint32(m_members.size());               // Number of members
     data << m_accountsNumber;                       // Number of accounts
     session->SendPacket(&data);
     LOG_DEBUG("guild", "SMSG_GUILD_INFO [%s]", session->GetPlayerInfo().c_str());
 }
References WorldSession::GetPlayerInfo(), LOG_DEBUG, m_accountsNumber, m_createdDate, m_members, m_name, WorldSession::SendPacket(), and SMSG_GUILD_INFO.
SendLoginInfo()
void Guild::SendLoginInfo (WorldSession * session)
Definition at line 1897 of file Guild.cpp.
 {
     WorldPacket data(SMSG_GUILD_EVENT, 1 + 1 + m_motd.size() + 1);
     data << uint8(GE_MOTD);
     data << uint8(1);
     data << m_motd;
     session->SendPacket(&data);
     LOG_DEBUG("guild", "SMSG_GUILD_EVENT [%s] MOTD", session->GetPlayerInfo().c_str());
     SendBankTabsInfo(session);
     Player* player = session->GetPlayer();
     HandleRoster(session);
     _BroadcastEvent(GE_SIGNED_ON, player->GetGUID(), player->GetName().c_str());
     if (Member* member = GetMember(player->GetGUID()))
     {
         member->SetStats(player);
         member->AddFlag(GUILDMEMBER_STATUS_ONLINE);
     }
 }
References _BroadcastEvent(), GE_MOTD, GE_SIGNED_ON, Object::GetGUID(), GetMember(), WorldObject::GetName(), WorldSession::GetPlayer(), WorldSession::GetPlayerInfo(), GUILDMEMBER_STATUS_ONLINE, HandleRoster(), LOG_DEBUG, m_motd, SendBankTabsInfo(), WorldSession::SendPacket(), and SMSG_GUILD_EVENT.
Referenced by AddMember(), and WorldSession::HandlePlayerLoginFromDB().
SendMoneyInfo()
void Guild::SendMoneyInfo (WorldSession * session) const
Definition at line 1884 of file Guild.cpp.
 {
     Member const* member = GetMember(session->GetPlayer()->GetGUID());
     if (!member)
         return;
     int32 amount = _GetMemberRemainingMoney(member);
     WorldPacket data(MSG_GUILD_BANK_MONEY_WITHDRAWN, 4);
     data << int32(amount);
     session->SendPacket(&data);
     LOG_DEBUG("guild", "MSG_GUILD_BANK_MONEY_WITHDRAWN [%s] Money: %u", session->GetPlayerInfo().c_str(), amount);
 }
References _GetMemberRemainingMoney(), Object::GetGUID(), GetMember(), WorldSession::GetPlayer(), WorldSession::GetPlayerInfo(), LOG_DEBUG, MSG_GUILD_BANK_MONEY_WITHDRAWN, and WorldSession::SendPacket().
SendPermissions()
void Guild::SendPermissions (WorldSession * session) const
Definition at line 1861 of file Guild.cpp.
 {
     Member const* member = GetMember(session->GetPlayer()->GetGUID());
     if (!member)
         return;
     uint8 rankId = member->GetRankId();
     WorldPacket data(MSG_GUILD_PERMISSIONS, 4 * 15 + 1);
     data << uint32(rankId);
     data << uint32(_GetRankRights(rankId));
     data << uint32(_GetMemberRemainingMoney(member));
     data << uint8(_GetPurchasedTabsSize());
     for (uint8 tabId = 0; tabId < GUILD_BANK_MAX_TABS; ++tabId)
     {
         data << uint32(_GetRankBankTabRights(rankId, tabId));
         data << uint32(_GetMemberRemainingSlots(member, tabId));
     }
     session->SendPacket(&data);
     LOG_DEBUG("guild", "MSG_GUILD_PERMISSIONS [%s] Rank: %u", session->GetPlayerInfo().c_str(), rankId);
 }
References _GetMemberRemainingMoney(), _GetMemberRemainingSlots(), _GetPurchasedTabsSize(), _GetRankBankTabRights(), _GetRankRights(), Object::GetGUID(), GetMember(), WorldSession::GetPlayer(), WorldSession::GetPlayerInfo(), Guild::Member::GetRankId(), GUILD_BANK_MAX_TABS, LOG_DEBUG, MSG_GUILD_PERMISSIONS, and WorldSession::SendPacket().
Referenced by HandleBuyBankTab().
SendSaveEmblemResult()
void Guild::SendSaveEmblemResult (WorldSession * session, GuildEmblemError errCode) static
Definition at line 115 of file Guild.cpp.
 {
     WorldPacket data(MSG_SAVE_GUILD_EMBLEM, 4);
     data << uint32(errCode);
     session->SendPacket(&data);
     LOG_DEBUG("guild", "MSG_SAVE_GUILD_EMBLEM [%s] Code: %u", session->GetPlayerInfo().c_str(), errCode);
 }
References WorldSession::GetPlayerInfo(), LOG_DEBUG, MSG_SAVE_GUILD_EMBLEM, and WorldSession::SendPacket().
Referenced by WorldSession::HandleSaveGuildEmblemOpcode(), and HandleSetEmblem().
SetBankTabText()
void Guild::SetBankTabText (uint8 tabId, std::string const & text)
Definition at line 2371 of file Guild.cpp.
 {
     if (BankTab* pTab = GetBankTab(tabId))
     {
         pTab->SetText(text);
         pTab->SendText(this, nullptr);
     }
 }
References GetBankTab().
SwapItems()
void Guild::SwapItems (Player * player, uint8 tabId, uint8 slotId, uint8 destTabId, uint8 destSlotId, uint32 splitedAmount)
Definition at line 2343 of file Guild.cpp.
 {
     if (tabId >= _GetPurchasedTabsSize() || slotId >= GUILD_BANK_MAX_SLOTS ||
             destTabId >= _GetPurchasedTabsSize() || destSlotId >= GUILD_BANK_MAX_SLOTS)
         return;
     if (tabId == destTabId && slotId == destSlotId)
         return;
     BankMoveItemData from(this, player, tabId, slotId);
     BankMoveItemData to(this, player, destTabId, destSlotId);
     _MoveItems(&from, &to, splitedAmount);
 }
References _GetPurchasedTabsSize(), _MoveItems(), and GUILD_BANK_MAX_SLOTS.
Referenced by WorldSession::HandleGuildBankSwapItems().
SwapItemsWithInventory()
void Guild::SwapItemsWithInventory (Player * player, bool toChar, uint8 tabId, uint8 slotId, uint8 playerBag, uint8 playerSlotId, uint32 splitedAmount)
Definition at line 2357 of file Guild.cpp.
 {
     if ((slotId >= GUILD_BANK_MAX_SLOTS && slotId != NULL_SLOT) || tabId >= _GetPurchasedTabsSize())
         return;
     BankMoveItemData bankData(this, player, tabId, slotId);
     PlayerMoveItemData charData(this, player, playerBag, playerSlotId);
     if (toChar)
         _MoveItems(&bankData, &charData, splitedAmount);
     else
         _MoveItems(&charData, &bankData, splitedAmount);
 }
References _GetPurchasedTabsSize(), _MoveItems(), GUILD_BANK_MAX_SLOTS, and NULL_SLOT.
Referenced by WorldSession::HandleGuildBankSwapItems().
UpdateMemberData()
void Guild::UpdateMemberData (Player * player, uint8 dataid, uint32 value)
Definition at line 1265 of file Guild.cpp.
 {
     if (Member* member = GetMember(player->GetGUID()))
     {
         switch (dataid)
         {
             case GUILD_MEMBER_DATA_ZONEID:
                 member->SetZoneID(value);
                 break;
             case GUILD_MEMBER_DATA_LEVEL:
                 member->SetLevel(value);
                 break;
             default:
                 LOG_ERROR("guild", "Guild::UpdateMemberData: Called with incorrect DATAID %u (value %u)", dataid, value);
                 return;
         }
         //HandleRoster();
     }
 }
References Object::GetGUID(), GetMember(), GUILD_MEMBER_DATA_LEVEL, GUILD_MEMBER_DATA_ZONEID, and LOG_ERROR.
Validate()
bool Guild::Validate ()
Definition at line 2057 of file Guild.cpp.
 {
     // Validate ranks data
     // GUILD RANKS represent a sequence starting from 0 = GUILD_MASTER (ALL PRIVILEGES) to max 9 (lowest privileges).
     // The lower rank id is considered higher rank - so promotion does rank-- and demotion does rank++
     // Between ranks in sequence cannot be gaps - so 0, 1, 2, 4 is impossible
     // Min ranks count is 5 and max is 10.
     bool broken_ranks = false;
     uint8 ranks = _GetRanksSize();
     if (ranks < GUILD_RANKS_MIN_COUNT || ranks > GUILD_RANKS_MAX_COUNT)
     {
         LOG_ERROR("guild", "Guild %u has invalid number of ranks, creating new...", m_id);
         broken_ranks = true;
     }
     else
     {
         for (uint8 rankId = 0; rankId < ranks; ++rankId)
         {
             RankInfo* rankInfo = GetRankInfo(rankId);
             if (rankInfo->GetId() != rankId)
             {
                 LOG_ERROR("guild", "Guild %u has broken rank id %u, creating default set of ranks...", m_id, rankId);
                 broken_ranks = true;
             }
             else
             {
                 CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
                 rankInfo->CreateMissingTabsIfNeeded(_GetPurchasedTabsSize(), trans, true);
                 CharacterDatabase.CommitTransaction(trans);
             }
         }
     }
     if (broken_ranks)
     {
         m_ranks.clear();
         _CreateDefaultGuildRanks(DEFAULT_LOCALE);
     }
     // Validate members' data
     for (Members::iterator itr = m_members.begin(); itr != m_members.end(); ++itr)
         if (itr->second->GetRankId() > _GetRanksSize())
             itr->second->ChangeRank(_GetLowestRankId());
     // Repair the structure of the guild.
     // If the guildmaster doesn't exist or isn't member of the guild
     // attempt to promote another member.
     Member* pLeader = GetMember(m_leaderGuid);
     if (!pLeader)
     {
         DeleteMember(m_leaderGuid);
         // If no more members left, disband guild
         if (m_members.empty())
         {
             Disband();
             return false;
         }
     }
     else if (!pLeader->IsRank(GR_GUILDMASTER))
         _SetLeaderGUID(pLeader);
     // Check config if multiple guildmasters are allowed
     if (!sConfigMgr->GetOption<bool>("Guild.AllowMultipleGuildMaster", 0))
         for (Members::iterator itr = m_members.begin(); itr != m_members.end(); ++itr)
             if (itr->second->GetRankId() == GR_GUILDMASTER && !itr->second->IsSamePlayer(m_leaderGuid))
                 itr->second->ChangeRank(GR_OFFICER);
     _UpdateAccountsNumber();
     return true;
 }
References _CreateDefaultGuildRanks(), _GetLowestRankId(), _GetPurchasedTabsSize(), _GetRanksSize(), _SetLeaderGUID(), _UpdateAccountsNumber(), CharacterDatabase, Guild::RankInfo::CreateMissingTabsIfNeeded(), DEFAULT_LOCALE, DeleteMember(), Disband(), Guild::RankInfo::GetId(), GetMember(), GetRankInfo(), GR_GUILDMASTER, GR_OFFICER, GUILD_RANKS_MAX_COUNT, Guild::Member::IsRank(), LOG_ERROR, m_id, m_leaderGuid, m_members, m_ranks, and sConfigMgr.
Referenced by GuildMgr::LoadGuilds().
Member Data Documentation
m_accountsNumber
uint32 Guild::m_accountsNumber protected
Definition at line 782 of file Guild.h.
Referenced by _UpdateAccountsNumber(), and SendInfo().
m_bankEventLog
LogHolder* Guild::m_bankEventLog[GUILD_BANK_MAX_TABS+1] protected
Definition at line 791 of file Guild.h.
Referenced by _CreateLogHolders(), _LogBankEvent(), Guild(), LoadBankEventLogFromDB(), SendBankLog(), and ~Guild().
m_bankMoney
uint64 Guild::m_bankMoney protected
Definition at line 783 of file Guild.h.
Referenced by _ModifyBankMoney(), _SendBankList(), Create(), GetTotalBankMoney(), HandleMemberDepositMoney(), HandleMemberWithdrawMoney(), and LoadFromDB().
m_bankTabs
BankTabs Guild::m_bankTabs protected
Definition at line 787 of file Guild.h.
Referenced by _CreateNewBankTab(), _DeleteBankItems(), _GetPurchasedTabsSize(), _SendBankList(), GetBankTab(), LoadBankItemFromDB(), LoadBankTabFromDB(), and LoadFromDB().
m_createdDate
time_t Guild::m_createdDate protected
Definition at line 779 of file Guild.h.
Referenced by Create(), GetCreatedDate(), LoadFromDB(), and SendInfo().
m_emblemInfo
EmblemInfo Guild::m_emblemInfo protected
Definition at line 781 of file Guild.h.
Referenced by Create(), HandleQuery(), HandleSetEmblem(), and LoadFromDB().
m_eventLog
LogHolder* Guild::m_eventLog protected
Definition at line 790 of file Guild.h.
Referenced by _CreateLogHolders(), _LogEvent(), LoadEventLogFromDB(), SendEventLog(), and ~Guild().
m_id
uint32 Guild::m_id protected
Definition at line 774 of file Guild.h.
Referenced by _CreateDefaultGuildRanks(), _CreateLogHolders(), _CreateNewBankTab(), _CreateRank(), _LogBankEvent(), _LogEvent(), _ModifyBankMoney(), _SetLeaderGUID(), AddMember(), Create(), Disband(), GetId(), HandleInviteMember(), HandleQuery(), HandleRemoveRank(), HandleSetEmblem(), HandleSetInfo(), HandleSetMOTD(), LoadBankEventLogFromDB(), LoadEventLogFromDB(), LoadFromDB(), LoadMemberFromDB(), LoadRankFromDB(), and Validate().
m_info
std::string Guild::m_info protected
Definition at line 778 of file Guild.h.
Referenced by Create(), GetInfo(), HandleRoster(), HandleSetInfo(), and LoadFromDB().
m_leaderGuid
ObjectGuid Guild::m_leaderGuid protected
Definition at line 776 of file Guild.h.
Referenced by _IsLeader(), _MemberHasTabRights(), _SetLeaderGUID(), Create(), DeleteMember(), GetLeaderGUID(), LoadFromDB(), and Validate().
m_members
Members Guild::m_members protected
Definition at line 786 of file Guild.h.
Referenced by _SendBankList(), _UpdateAccountsNumber(), AddMember(), BroadcastPacket(), BroadcastPacketToRank(), BroadcastToGuild(), BroadcastWorker(), DeleteMember(), Disband(), GetMember(), GetMemberCount(), GetMemberSize(), HandleLeaveMember(), HandleRoster(), LoadMemberFromDB(), MassInviteToEvent(), ResetTimes(), SendInfo(), Validate(), and ~Guild().
m_motd
std::string Guild::m_motd protected
Definition at line 777 of file Guild.h.
Referenced by Create(), GetMOTD(), HandleRoster(), HandleSetMOTD(), LoadFromDB(), and SendLoginInfo().
m_name
std::string Guild::m_name protected
Definition at line 775 of file Guild.h.
Referenced by Create(), GetName(), HandleInviteMember(), HandleLeaveMember(), HandleQuery(), Guild::RankInfo::LoadFromDB(), Guild::BankTab::LoadFromDB(), LoadFromDB(), Guild::RankInfo::SaveToDB(), SendInfo(), Guild::BankTab::SetInfo(), Guild::RankInfo::SetName(), Guild::Member::SetStats(), and Guild::Member::WritePacket().
m_ranks
Ranks Guild::m_ranks protected
Definition at line 785 of file Guild.h.
Referenced by _CreateNewBankTab(), _CreateRank(), _GetLowestRankId(), _GetRanksSize(), GetRankInfo(), HandleQuery(), HandleRemoveRank(), HandleRoster(), LoadRankFromDB(), and Validate().
The documentation for this class was generated from the following files:
src/server/game/Guilds/Guild.h
src/server/game/Guilds/Guild.cpp