Azerotcore-wotlk: npc_spinestalker::npc_spinestalkerAI Struct Reference
npc_spinestalker::npc_spinestalkerAI Struct Reference
Public Member Functions
npc_spinestalkerAI (Creature *creature)
void InitializeAI () override
void Reset () override
void JustReachedHome () override
void JustRespawned () override
void JustDied (Unit *) override
void DoAction (int32 action) override
void MovementInform (uint32 type, uint32 point) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void EnterCombat (Unit *) override
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
EventMap _events
InstanceScript * _instance
bool _summoned
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1372 of file boss_sindragosa.cpp.
Constructor & Destructor Documentation
npc_spinestalkerAI()
npc_spinestalker::npc_spinestalkerAI::npc_spinestalkerAI (Creature * creature) inline
Definition at line 1374 of file boss_sindragosa.cpp.
                                                : ScriptedAI(creature), _instance(creature->GetInstanceScript()), _summoned(false)
         {
         }
Member Function Documentation
DoAction()
void npc_spinestalker::npc_spinestalkerAI::DoAction (int32 action) inline override virtual
Reimplemented from UnitAI.
Definition at line 1421 of file boss_sindragosa.cpp.
         {
             if (action == ACTION_START_FROSTWYRM)
             {
                 if (_summoned)
                     return;
                 _summoned = true;
                 if (me->isDead())
                     return;
                 me->setActive(true);
                 me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
                 float moveTime = me->GetExactDist(&SpinestalkerFlyPos) / (me->GetSpeed(MOVE_RUN) * 0.001f);
                 me->m_Events.AddEvent(new FrostwyrmLandEvent(*me, SpinestalkerLandPos), me->m_Events.CalculateTime(uint64(moveTime) + 250));
                 me->SetDefaultMovementType(IDLE_MOTION_TYPE);
                 me->GetMotionMaster()->MoveIdle();
                 me->StopMoving();
                 me->GetMotionMaster()->MovePoint(POINT_FROSTWYRM_FLY_IN, SpinestalkerFlyPos);
             }
         }
References _summoned, ACTION_START_FROSTWYRM, EventProcessor::AddEvent(), EventProcessor::CalculateTime(), Position::GetExactDist(), Unit::GetMotionMaster(), Unit::GetSpeed(), IDLE_MOTION_TYPE, Unit::isDead(), Unit::m_Events, ScriptedAI::me, MOVE_RUN, MotionMaster::MoveIdle(), MotionMaster::MovePoint(), POINT_FROSTWYRM_FLY_IN, WorldObject::setActive(), Creature::SetDefaultMovementType(), Object::SetFlag(), SpinestalkerFlyPos, SpinestalkerLandPos, Unit::StopMoving(), UNIT_FIELD_FLAGS, and UNIT_FLAG_IMMUNE_TO_PC.
InitializeAI()
void npc_spinestalker::npc_spinestalkerAI::InitializeAI () inline override virtual
Reimplemented from UnitAI.
Definition at line 1378 of file boss_sindragosa.cpp.
         {
             if (!me->isDead())
             {
                 _instance->SetData(DATA_SINDRAGOSA_FROSTWYRMS, me->GetSpawnId());  // this cannot be in Reset because reset also happens on evade
                 Reset();
             }
         }
References _instance, DATA_SINDRAGOSA_FROSTWYRMS, Creature::GetSpawnId(), Unit::isDead(), ScriptedAI::me, Reset(), and ZoneScript::SetData().
JustDied()
void npc_spinestalker::npc_spinestalkerAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1416 of file boss_sindragosa.cpp.
         {
             _events.Reset();
         }
References _events, and EventMap::Reset().
JustReachedHome()
void npc_spinestalker::npc_spinestalkerAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 1401 of file boss_sindragosa.cpp.
         {
             ScriptedAI::JustReachedHome();
             if (_summoned)
             {
                 me->SetDisableGravity(false);
             }
         }
References _summoned, CreatureAI::JustReachedHome(), ScriptedAI::me, and Creature::SetDisableGravity().
JustRespawned()
void npc_spinestalker::npc_spinestalkerAI::JustRespawned () inline override virtual
Reimplemented from CreatureAI.
Definition at line 1410 of file boss_sindragosa.cpp.
         {
             ScriptedAI::JustRespawned();
             _instance->SetData(DATA_SINDRAGOSA_FROSTWYRMS, me->GetSpawnId());  // this cannot be in Reset because reset also happens on evade
         }
References _instance, DATA_SINDRAGOSA_FROSTWYRMS, Creature::GetSpawnId(), CreatureAI::JustRespawned(), ScriptedAI::me, and ZoneScript::SetData().
MovementInform()
void npc_spinestalker::npc_spinestalkerAI::MovementInform (uint32 type, uint32 point) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1443 of file boss_sindragosa.cpp.
         {
             if (type != EFFECT_MOTION_TYPE || point != POINT_FROSTWYRM_LAND)
                 return;
             me->setActive(false);
             me->SetDisableGravity(false);
             me->SetHomePosition(SpinestalkerLandPos);
             me->SetFacingTo(SpinestalkerLandPos.GetOrientation());
             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC);
         }
References EFFECT_MOTION_TYPE, Position::GetOrientation(), ScriptedAI::me, POINT_FROSTWYRM_LAND, Object::RemoveFlag(), WorldObject::setActive(), Creature::SetDisableGravity(), Unit::SetFacingTo(), Creature::SetHomePosition(), SpinestalkerLandPos, UNIT_FIELD_FLAGS, and UNIT_FLAG_IMMUNE_TO_PC.
Reset()
void npc_spinestalker::npc_spinestalkerAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1387 of file boss_sindragosa.cpp.
         {
             _events.Reset();
             _events.ScheduleEvent(EVENT_BELLOWING_ROAR, urand(20000, 25000));
             _events.ScheduleEvent(EVENT_CLEAVE_SPINESTALKER, urand(10000, 15000));
             _events.ScheduleEvent(EVENT_TAIL_SWEEP, urand(8000, 12000));
             me->SetReactState(REACT_DEFENSIVE);
             if (!_summoned)
             {
                 me->SetDisableGravity(true);
             }
         }
References _events, _summoned, EVENT_BELLOWING_ROAR, EVENT_CLEAVE_SPINESTALKER, EVENT_TAIL_SWEEP, ScriptedAI::me, REACT_DEFENSIVE, EventMap::Reset(), EventMap::ScheduleEvent(), Creature::SetDisableGravity(), Creature::SetReactState(), and urand().
Referenced by InitializeAI().
UpdateAI()
void npc_spinestalker::npc_spinestalkerAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1455 of file boss_sindragosa.cpp.
         {
             if (!UpdateVictim())
                 return;
             _events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (_events.ExecuteEvent())
             {
                 case EVENT_BELLOWING_ROAR:
                     me->CastSpell(me, SPELL_BELLOWING_ROAR, false);
                     _events.ScheduleEvent(EVENT_BELLOWING_ROAR, urand(25000, 30000));
                     break;
                 case EVENT_CLEAVE_SPINESTALKER:
                     me->CastSpell(me->GetVictim(), SPELL_CLEAVE_SPINESTALKER, false);
                     _events.ScheduleEvent(EVENT_CLEAVE_SPINESTALKER, urand(10000, 15000));
                     break;
                 case EVENT_TAIL_SWEEP:
                     me->CastSpell(me->GetVictim(), SPELL_TAIL_SWEEP, false);
                     _events.ScheduleEvent(EVENT_TAIL_SWEEP, urand(22000, 25000));
                     break;
                 default:
                     break;
             }
             DoMeleeAttackIfReady();
         }
References _events, Unit::CastSpell(), diff(), UnitAI::DoMeleeAttackIfReady(), EVENT_BELLOWING_ROAR, EVENT_CLEAVE_SPINESTALKER, EVENT_TAIL_SWEEP, EventMap::ExecuteEvent(), Unit::GetVictim(), Unit::HasUnitState(), ScriptedAI::me, EventMap::ScheduleEvent(), SPELL_BELLOWING_ROAR, SPELL_CLEAVE_SPINESTALKER, SPELL_TAIL_SWEEP, UNIT_STATE_CASTING, EventMap::Update(), CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
_events
EventMap npc_spinestalker::npc_spinestalkerAI::_events private
Definition at line 1487 of file boss_sindragosa.cpp.
Referenced by JustDied(), Reset(), and UpdateAI().
_instance
InstanceScript* npc_spinestalker::npc_spinestalkerAI::_instance private
Definition at line 1488 of file boss_sindragosa.cpp.
Referenced by InitializeAI(), and JustRespawned().
_summoned
bool npc_spinestalker::npc_spinestalkerAI::_summoned private
Definition at line 1489 of file boss_sindragosa.cpp.
Referenced by DoAction(), JustReachedHome(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_sindragosa.cpp