Azerotcore-wotlk: SACActivateEvent Class Reference
SACActivateEvent Class Reference
Public Member Functions
SACActivateEvent (Creature *owner)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()
virtual ~BasicEvent ()
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Creature * _owner
Detailed Description
Definition at line 1068 of file zone_dragonblight.cpp.
Constructor & Destructor Documentation
SACActivateEvent()
SACActivateEvent::SACActivateEvent (Creature * owner) inline
Definition at line 1071 of file zone_dragonblight.cpp.
 : _owner(owner) {}
Member Function Documentation
Execute()
bool SACActivateEvent::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
Definition at line 1073 of file zone_dragonblight.cpp.
     {
         if (!_owner->IsAlive())
             return true;
         _owner->GetMotionMaster()->MoveRandom(5.0f);
         _owner->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
         _owner->SetReactState(REACT_AGGRESSIVE);
         _owner->CastSpell(_owner, SPELL_SAC_GHOUL_AREA_AURA, true);
         return true;
     }
References _owner, Unit::CastSpell(), Unit::GetMotionMaster(), Unit::IsAlive(), MotionMaster::MoveRandom(), REACT_AGGRESSIVE, Object::RemoveFlag(), Creature::SetReactState(), SPELL_SAC_GHOUL_AREA_AURA, UNIT_FIELD_FLAGS, and UNIT_FLAG_NOT_SELECTABLE.
Member Data Documentation
_owner
Creature* SACActivateEvent::_owner private
Definition at line 1085 of file zone_dragonblight.cpp.
Referenced by Execute().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/zone_dragonblight.cpp