Azerotcore-wotlk: go_corkis_prison Class Reference
go_corkis_prison Class Reference
Public Member Functions
go_corkis_prison ()
bool OnGossipHello (Player *player, GameObject *go) override
Public Member Functions inherited from GameObjectScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelect (Player *, GameObject *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, GameObject *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, GameObject *, Quest const *)
virtual bool OnQuestReward (Player *, GameObject *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, GameObject *)
virtual void OnDestroyed (GameObject *, Player *)
virtual void OnDamaged (GameObject *, Player *)
virtual void OnLootStateChanged (GameObject *, uint32, Unit *)
virtual void OnGameObjectStateChanged (GameObject *, uint32)
virtual GameObjectAI * GetAI (GameObject *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< GameObject >
virtual void OnUpdate (GameObject *, uint32)
Additional Inherited Members
Protected Member Functions inherited from GameObjectScript
GameObjectScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< GameObject >
UpdatableScript ()=default
Detailed Description
Definition at line 287 of file zone_nagrand.cpp.
Constructor & Destructor Documentation
go_corkis_prison()
go_corkis_prison::go_corkis_prison () inline
Definition at line 290 of file zone_nagrand.cpp.
 : GameObjectScript("go_corkis_prison") { }
Member Function Documentation
OnGossipHello()
bool go_corkis_prison::OnGossipHello (Player * player, GameObject * go) inline override virtual
Reimplemented from GameObjectScript.
Definition at line 292 of file zone_nagrand.cpp.
     {
         go->SetGoState(GO_STATE_READY);
         if (go->GetEntry() == GO_CORKIS_PRISON)
         {
             if (Creature* corki = go->FindNearestCreature(NPC_CORKI, 25, true))
             {
                 corki->GetMotionMaster()->MovePoint(1, go->GetPositionX() + 5, go->GetPositionY(), go->GetPositionZ());
                 if (player)
                     player->KilledMonsterCredit(NPC_CORKI_CREDIT_1);
             }
         }
         if (go->GetEntry() == GO_CORKIS_PRISON_2)
         {
             if (Creature* corki = go->FindNearestCreature(NPC_CORKI_2, 25, true))
             {
                 corki->GetMotionMaster()->MovePoint(1, go->GetPositionX() - 5, go->GetPositionY(), go->GetPositionZ());
                 if (player)
                     player->KilledMonsterCredit(NPC_CORKI_2);
             }
         }
         if (go->GetEntry() == GO_CORKIS_PRISON_3)
         {
             if (Creature* corki = go->FindNearestCreature(NPC_CORKI_3, 25, true))
             {
                 corki->GetMotionMaster()->MovePoint(1, go->GetPositionX() + 4, go->GetPositionY(), go->GetPositionZ());
                 if (player)
                     player->KilledMonsterCredit(NPC_CORKI_CREDIT_3);
             }
         }
         return true;
     }
References WorldObject::FindNearestCreature(), Object::GetEntry(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), GO_CORKIS_PRISON, GO_CORKIS_PRISON_2, GO_CORKIS_PRISON_3, GO_STATE_READY, Player::KilledMonsterCredit(), NPC_CORKI, NPC_CORKI_2, NPC_CORKI_3, NPC_CORKI_CREDIT_1, NPC_CORKI_CREDIT_3, and GameObject::SetGoState().
The documentation for this class was generated from the following file:
src/server/scripts/Outland/zone_nagrand.cpp