Azerotcore-wotlk: detail::fp Class Reference
detail::fp Class Reference
#include <format-inl.h>
Public Member Functions
fp ()
fp (uint64_t f_val, int e_val)
template<typename Double >
fp (Double d)
template<typename Float , FMT_ENABLE_IF(is_supported_float< Float >::value) >
bool assign (Float d)
template<typename Float , FMT_ENABLE_IF(!is_supported_float< Float >::value) >
bool assign (Float)
Public Attributes
significand_type f
int e
Static Public Attributes
static FMT_CONSTEXPR_DECL const int double_significand_size
static FMT_CONSTEXPR_DECL const uint64_t implicit_bit
static FMT_CONSTEXPR_DECL const int significand_size
Private Types
using significand_type = uint64_t
template<typename Float >
using is_supported_float = bool_constant< sizeof(Float)==sizeof(uint64_t)||sizeof(Float)==sizeof(uint32_t)>
Detailed Description
Definition at line 175 of file format-inl.h.
Member Typedef Documentation
is_supported_float
template<typename Float > using detail::fp::is_supported_float = bool_constant<sizeof(Float) == sizeof(uint64_t) || sizeof(Float) == sizeof(uint32_t)> private
Definition at line 180 of file format-inl.h.
significand_type
using detail::fp::significand_type = uint64_t private
Definition at line 177 of file format-inl.h.
Constructor & Destructor Documentation
fp() [1/3]
detail::fp::fp () inline
Definition at line 197 of file format-inl.h.
 : f(0), e(0) {}
Referenced by assign().
fp() [2/3]
detail::fp::fp (uint64_t f_val, int e_val) inline
Definition at line 198 of file format-inl.h.
 : f(f_val), e(e_val) {}
fp() [3/3]
template<typename Double > detail::fp::fp (Double d) inline explicit
Definition at line 202 of file format-inl.h.
 { assign(d); }
References assign(), and mpq::d.
Member Function Documentation
assign() [1/2]
template<typename Float , FMT_ENABLE_IF(is_supported_float< Float >::value) > bool detail::fp::assign (Float d) inline
Definition at line 206 of file format-inl.h.
{
     // Assume float is in the format [sign][exponent][significand].
     using limits = std::numeric_limits<Float>;
     const int float_significand_size = limits::digits - 1;
     const int exponent_size =
         bits<Float>::value - float_significand_size - 1;  // -1 for sign
     const uint64_t float_implicit_bit = 1ULL << float_significand_size;
     const uint64_t significand_mask = float_implicit_bit - 1;
     const uint64_t exponent_mask = (~0ULL >> 1) & ~significand_mask;
     const int exponent_bias = (1 << exponent_size) - limits::max_exponent - 1;
     constexpr bool is_double = sizeof(Float) == sizeof(uint64_t);
     auto u = bit_cast<conditional_t<is_double, uint64_t, uint32_t>>(d);
     f = u & significand_mask;
     int biased_e =
         static_cast<int>((u & exponent_mask) >> float_significand_size);
     // Predecessor is closer if d is a normalized power of 2 (f == 0) other than
     // the smallest normalized number (biased_e > 1).
     bool is_predecessor_closer = f == 0 && biased_e > 1;
     if (biased_e != 0)
       f += float_implicit_bit;
     else
       biased_e = 1;  // Subnormals use biased exponent 1 (min exponent).
     e = biased_e - exponent_bias - float_significand_size;
     return is_predecessor_closer;
   }
References mpq::d, e, exponent_mask(), f, Float, and ULL.
Referenced by fp().
assign() [2/2]
template<typename Float , FMT_ENABLE_IF(!is_supported_float< Float >::value) > bool detail::fp::assign (Float) inline
Definition at line 233 of file format-inl.h.
                      {
     *this = fp();
     return false;
   }
References fp().
Member Data Documentation
double_significand_size
FMT_CONSTEXPR_DECL const int detail::fp::double_significand_size static
Initial value:
=
      std::numeric_limits<double>::digits - 1
Definition at line 190 of file format-inl.h.
Referenced by detail::normalize().
e
int detail::fp::e
Definition at line 185 of file format-inl.h.
Referenced by assign(), and detail::format_float().
f
significand_type detail::fp::f
Definition at line 184 of file format-inl.h.
Referenced by assign().
implicit_bit
FMT_CONSTEXPR_DECL const uint64_t detail::fp::implicit_bit static
Initial value:
=
      1ULL << double_significand_size
Definition at line 192 of file format-inl.h.
Referenced by detail::normalize().
significand_size
FMT_CONSTEXPR_DECL const int detail::fp::significand_size static
Initial value:
=
      bits<significand_type>::value
Definition at line 194 of file format-inl.h.
Referenced by detail::format_float(), detail::get_cached_power(), and detail::normalize().
The documentation for this class was generated from the following file:
deps/fmt/include/fmt/format-inl.h