Azerotcore-wotlk: deps/mysqllite/mysys/my_fopen.c File Reference
my_fopen.c File Reference
#include "mysys_priv.h"
#include "my_static.h"
#include <errno.h>
#include "mysys_err.h"
Functions
static void make_ftype (char *to, int flag)
FILE * my_fopen (const char *filename, int flags, myf MyFlags)
FILE * my_freopen (const char *path, const char *mode, FILE *stream)
int my_fclose (FILE *fd, myf MyFlags)
FILE * my_fdopen (File Filedes, const char *name, int Flags, myf MyFlags)
static void make_ftype (register char *to, register int flag)
Function Documentation
make_ftype() [1/2]
static void make_ftype (char * to, int flag) static
Referenced by my_fdopen(), and my_fopen().
make_ftype() [2/2]
static void make_ftype (register char * to, register int flag) static
Definition at line 331 of file my_fopen.c.
 {
   /* check some possible invalid combinations */
   DBUG_ASSERT((flag & (O_TRUNC | O_APPEND)) != (O_TRUNC | O_APPEND));
   DBUG_ASSERT((flag & (O_WRONLY | O_RDWR)) != (O_WRONLY | O_RDWR));
   if ((flag & (O_RDONLY|O_WRONLY)) == O_WRONLY)
     *to++= (flag & O_APPEND) ? 'a' : 'w';
   else if (flag & O_RDWR)
   {
     /* Add '+' after theese */
     if (flag & (O_TRUNC | O_CREAT))
       *to++= 'w';
     else if (flag & O_APPEND)
       *to++= 'a';
     else
       *to++= 'r';
     *to++= '+';
   }
   else
     *to++= 'r';
 #if FILE_BINARY            /* If we have binary-files */
   if (flag & FILE_BINARY)
     *to++='b';
 #endif
   *to='\0';
 } /* make_ftype */
References DBUG_ASSERT, and FILE_BINARY.
my_fclose()
int my_fclose (FILE * fd, myf MyFlags)
Definition at line 227 of file my_fopen.c.
 {
   int err,file;
   DBUG_ENTER("my_fclose");
   DBUG_PRINT("my",("stream: 0x%lx  MyFlags: %d", (long) fd, MyFlags));
   mysql_mutex_lock(&THR_LOCK_open);
   file= my_fileno(fd);
 #ifndef _WIN32
   err= fclose(fd);
 #else
   err= my_win_fclose(fd);
 #endif
   if(err < 0)
   {
     my_errno=errno;
     if (MyFlags & (MY_FAE | MY_WME))
       my_error(EE_BADCLOSE, MYF(ME_BELL+ME_WAITTANG),
            my_filename(file),errno);
   }
   else
     my_stream_opened--;
   if ((uint) file < my_file_limit && my_file_info[file].type != UNOPEN)
   {
     my_file_info[file].type = UNOPEN;
     my_free(my_file_info[file].name);
   }
   mysql_mutex_unlock(&THR_LOCK_open);
   DBUG_RETURN(err);
 } /* my_fclose */
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_BADCLOSE, errno, mpq::file, ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_FAE, my_file_info, my_file_limit, my_filename(), my_fileno(), my_free(), my_stream_opened, MY_WME, MYF, mysql_mutex_lock, mysql_mutex_unlock, THR_LOCK_open, st_my_file_info::type, and UNOPEN.
Referenced by inline_mysql_file_fclose(), and my_fopen().
my_fdopen()
FILE* my_fdopen (File Filedes, const char * name, int Flags, myf MyFlags)
Definition at line 262 of file my_fopen.c.
 {
   FILE *fd;
   char type[5];
   DBUG_ENTER("my_fdopen");
   DBUG_PRINT("my",("Fd: %d  Flags: %d  MyFlags: %d",
            Filedes, Flags, MyFlags));
   make_ftype(type,Flags);
 #ifdef _WIN32
   fd= my_win_fdopen(Filedes, type);
 #else
   fd= fdopen(Filedes, type);
 #endif
   if (!fd)
   {
     my_errno=errno;
     if (MyFlags & (MY_FAE | MY_WME))
       my_error(EE_CANT_OPEN_STREAM, MYF(ME_BELL+ME_WAITTANG),errno);
   }
   else
   {
     mysql_mutex_lock(&THR_LOCK_open);
     my_stream_opened++;
     if ((uint) Filedes < (uint) my_file_limit)
     {
       if (my_file_info[Filedes].type != UNOPEN)
       {
         my_file_opened--;       /* File is opened with my_open ! */
       }
       else
       {
         my_file_info[Filedes].name=  my_strdup(name,MyFlags);
       }
       my_file_info[Filedes].type = STREAM_BY_FDOPEN;
     }
     mysql_mutex_unlock(&THR_LOCK_open);
   }
   DBUG_PRINT("exit",("stream: 0x%lx", (long) fd));
   DBUG_RETURN(fd);
 } /* my_fdopen */
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_CANT_OPEN_STREAM, errno, make_ftype(), ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_FAE, my_file_info, my_file_limit, my_file_opened, my_strdup(), my_stream_opened, MY_WME, MYF, mysql_mutex_lock, mysql_mutex_unlock, st_my_file_info::name, STREAM_BY_FDOPEN, THR_LOCK_open, st_my_file_info::type, and UNOPEN.
my_fopen()
FILE* my_fopen (const char * filename, int flags, myf MyFlags)
Definition at line 41 of file my_fopen.c.
 {
   FILE *fd;
   char type[5];
   DBUG_ENTER("my_fopen");
   DBUG_PRINT("my",("Name: '%s'  flags: %d  MyFlags: %d",
            filename, flags, MyFlags));
   make_ftype(type,flags);
 #ifdef _WIN32
   fd= my_win_fopen(filename, type);
 #else
   fd= fopen(filename, type);
 #endif
   if (fd != 0)
   {
     /*
       The test works if MY_NFILE < 128. The problem is that fileno() is char
       on some OS (SUNOS). Actually the filename save isn't that important
       so we can ignore if this doesn't work.
     */
     int filedesc= my_fileno(fd);
     if ((uint)filedesc >= my_file_limit)
     {
       thread_safe_increment(my_stream_opened,&THR_LOCK_open);
       DBUG_RETURN(fd);              /* safeguard */
     }
     mysql_mutex_lock(&THR_LOCK_open);
     if ((my_file_info[filedesc].name= (char*)
      my_strdup(filename,MyFlags)))
     {
       my_stream_opened++;
       my_file_total_opened++;
       my_file_info[filedesc].type= STREAM_BY_FOPEN;
       mysql_mutex_unlock(&THR_LOCK_open);
       DBUG_PRINT("exit",("stream: 0x%lx", (long) fd));
       DBUG_RETURN(fd);
     }
     mysql_mutex_unlock(&THR_LOCK_open);
     (void) my_fclose(fd,MyFlags);
     my_errno=ENOMEM;
   }
   else
     my_errno=errno;
   DBUG_PRINT("error",("Got error %d on open",my_errno));
   if (MyFlags & (MY_FFNF | MY_FAE | MY_WME))
     my_error((flags & O_RDONLY) || (flags == O_RDONLY ) ? EE_FILENOTFOUND :
          EE_CANTCREATEFILE,
          MYF(ME_BELL+ME_WAITTANG), filename, my_errno);
   DBUG_RETURN((FILE*) 0);
 } /* my_fopen */
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_CANTCREATEFILE, EE_FILENOTFOUND, errno, make_ftype(), ME_BELL, ME_WAITTANG, my_errno, my_error(), MY_FAE, my_fclose(), MY_FFNF, my_file_info, my_file_limit, my_file_total_opened, my_fileno(), my_strdup(), my_stream_opened, MY_WME, MYF, mysql_mutex_lock, mysql_mutex_unlock, STREAM_BY_FOPEN, THR_LOCK_open, thread_safe_increment, and st_my_file_info::type.
Referenced by inline_mysql_file_fopen().
my_freopen()
FILE* my_freopen (const char * path, const char * mode, FILE * stream)
Change the file associated with a file stream.
Parameters
path Path to file.
mode Mode of the stream.
stream File stream.
Note
This function is used to redirect stdout and stderr to a file and subsequently to close and reopen that file for log rotation.
Return values
A FILE pointer on success. Otherwise, NULL.
Definition at line 202 of file my_fopen.c.
 {
   FILE *result;
 #if defined(_WIN32)
   result= my_win_freopen(path, mode, stream);
 #elif defined(__FreeBSD__)
   /*
     XXX: Once the fix is ported to the stable releases, this should
          be dependent upon the specific FreeBSD versions. Check at:
          http://www.freebsd.org/cgi/query-pr.cgi?pr=79887
   */
   if (getosreldate() > 900027)
     result= freopen(path, mode, stream);
   else
     result= my_freebsd_freopen(path, mode, stream);
 #else
   result= freopen(path, mode, stream);
 #endif
   return result;
 }