Azerotcore-wotlk: boss_ymiron::boss_ymironAI Struct Reference
boss_ymiron::boss_ymironAI Struct Reference
Public Member Functions
boss_ymironAI (Creature *pCreature)
void Reset () override
void EnterEvadeMode () override
void EnterCombat (Unit *) override
void MovementInform (uint32 uiType, uint32 point) override
void SpellHitTarget (Unit *, const SpellInfo *spellInfo) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
EventMap events
SummonList summons
SummonList summons2
uint8 BoatNum
uint8 BoatOrder [4]
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 111 of file boss_ymiron.cpp.
Constructor & Destructor Documentation
boss_ymironAI()
boss_ymiron::boss_ymironAI::boss_ymironAI (Creature * pCreature) inline
Definition at line 113 of file boss_ymiron.cpp.
                                            : ScriptedAI(pCreature), summons(me), summons2(me)
         {
             pInstance = pCreature->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), and pInstance.
Member Function Documentation
EnterCombat()
void boss_ymiron::boss_ymironAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 168 of file boss_ymiron.cpp.
         {
             Talk(SAY_AGGRO);
             if(pInstance)
             {
                 pInstance->SetData(DATA_KING_YMIRON, IN_PROGRESS);
                 if (pInstance->GetData(DATA_SKADI_THE_RUTHLESS) == DONE)
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
             }
             events.RescheduleEvent(EVENT_YMIRON_BANE, 18000);
             events.RescheduleEvent(EVENT_YMIRON_FETID_ROT, 8000);
             events.RescheduleEvent(EVENT_YMIRON_DARK_SLASH, 28000);
             events.RescheduleEvent(EVENT_YMIRON_HEALTH_CHECK, 1000);
         }
References DATA_KING_YMIRON, DATA_SKADI_THE_RUTHLESS, DONE, EVENT_YMIRON_BANE, EVENT_YMIRON_DARK_SLASH, EVENT_YMIRON_FETID_ROT, EVENT_YMIRON_HEALTH_CHECK, ZoneScript::GetData(), IN_PROGRESS, ScriptedAI::me, pInstance, Object::RemoveFlag(), SAY_AGGRO, ZoneScript::SetData(), CreatureAI::Talk(), UNIT_FIELD_FLAGS, and UNIT_FLAG_NOT_SELECTABLE.
EnterEvadeMode()
void boss_ymiron::boss_ymironAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 162 of file boss_ymiron.cpp.
         {
             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE);
             ScriptedAI::EnterEvadeMode();
         }
References CreatureAI::EnterEvadeMode(), ScriptedAI::me, Object::RemoveFlag(), UNIT_FIELD_FLAGS, and UNIT_FLAG_DISABLE_MOVE.
JustDied()
void boss_ymiron::boss_ymironAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 335 of file boss_ymiron.cpp.
         {
             Talk(SAY_DEATH);
             summons.DespawnAll();
             summons2.DespawnAll();
             if(pInstance)
                 pInstance->SetData(DATA_KING_YMIRON, DONE);
         }
References DATA_KING_YMIRON, SummonList::DespawnAll(), DONE, pInstance, SAY_DEATH, ZoneScript::SetData(), summons, summons2, and CreatureAI::Talk().
KilledUnit()
void boss_ymiron::boss_ymironAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 345 of file boss_ymiron.cpp.
         {
             if (urand(0, 1))
                 return;
             Talk(SAY_SLAY);
         }
References SAY_SLAY, CreatureAI::Talk(), and urand().
MovementInform()
void boss_ymiron::boss_ymironAI::MovementInform (uint32 uiType, uint32 point) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 184 of file boss_ymiron.cpp.
         {
             if(uiType != POINT_MOTION_TYPE)
                 return;
             if (point == 0)
             {
                 Talk(BoatStructure[BoatOrder[BoatNum - 1]].say);
                 if (Creature* cr = me->FindNearestCreature(BoatStructure[BoatOrder[BoatNum - 1]].trigger, 50.0f))
                     me->CastSpell(cr, SPELL_CHANNEL_YMIRON_TO_SPIRIT, true);
                 events.ScheduleEvent(EVENT_YMIRON_ACTIVATE_BOAT, 6000);
             }
         }
References BoatNum, BoatOrder, BoatStructure, Unit::CastSpell(), EVENT_YMIRON_ACTIVATE_BOAT, WorldObject::FindNearestCreature(), ScriptedAI::me, POINT_MOTION_TYPE, SPELL_CHANNEL_YMIRON_TO_SPIRIT, CreatureAI::Talk(), and ActiveBoatStruct::trigger.
Reset()
void boss_ymiron::boss_ymironAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 125 of file boss_ymiron.cpp.
         {
             for (uint8 i = 0; i < 4; ++i)
             {
                 bool good;
                 do
                 {
                     good = true;
                     BoatOrder[i] = urand(0, 3);
                     for (uint8 j = 0; j < i; ++j)
                         if (BoatOrder[i] == BoatOrder[j])
{
                             good = false;
                             break;
                         }
                 } while (!good);
             }
             events.Reset();
             summons.DespawnAll();
             summons2.DespawnAll();
             BoatNum = 0;
             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_DISABLE_MOVE);
             if(pInstance)
             {
                 pInstance->SetData(DATA_KING_YMIRON, NOT_STARTED);
                 pInstance->SetData(DATA_YMIRON_ACHIEVEMENT, true);
                 me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                 if (pInstance->GetData(DATA_SKADI_THE_RUTHLESS) == DONE)
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
             }
         }
References BoatNum, BoatOrder, DATA_KING_YMIRON, DATA_SKADI_THE_RUTHLESS, DATA_YMIRON_ACHIEVEMENT, SummonList::DespawnAll(), DONE, ZoneScript::GetData(), ScriptedAI::me, NOT_STARTED, pInstance, Object::RemoveFlag(), ZoneScript::SetData(), Object::SetFlag(), summons, summons2, UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, and urand().
SpellHitTarget()
void boss_ymiron::boss_ymironAI::SpellHitTarget (Unit * , const SpellInfo * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 199 of file boss_ymiron.cpp.
         {
             if (spellInfo->Id == 59302 && pInstance) // Bane trigger
                 pInstance->SetData(DATA_YMIRON_ACHIEVEMENT, false);
         }
References DATA_YMIRON_ACHIEVEMENT, SpellInfo::Id, pInstance, and ZoneScript::SetData().
UpdateAI()
void boss_ymiron::boss_ymironAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 205 of file boss_ymiron.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_YMIRON_HEALTH_CHECK:
                     {
                         if (me->GetHealth() < std::max(0.0f, float(me->GetMaxHealth() * (1.0f - (IsHeroic() ? 0.2f : 0.334f)*float(BoatNum + 1)))))
{
                             events.DelayEvents(12000);
                             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                             me->InterruptNonMeleeSpells(true);
                             me->CastSpell(me, SPELL_SCREAMS_OF_THE_DEAD, true);
                             me->GetMotionMaster()->Clear();
                             me->GetMotionMaster()->MovePoint(0, BoatStructure[BoatOrder[BoatNum]].MoveX, BoatStructure[BoatOrder[BoatNum]].MoveY, BoatStructure[BoatOrder[BoatNum]].MoveZ);
                             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE);
                             summons.DespawnAll();
                             // Spawn flames in previous boat if any
                             if (BoatNum) // different than 0
                                 if (Creature* cr = me->SummonTrigger(BoatStructure[BoatOrder[BoatNum - 1]].SpawnX, BoatStructure[BoatOrder[BoatNum - 1]].SpawnY, BoatStructure[BoatOrder[BoatNum - 1]].SpawnZ, 0, 1800000))
{
                                     cr->AddAura(SPELL_FLAMES, cr);
                                     summons2.Summon(cr);
                                 }
                             BoatNum++;
                         }
                         events.RepeatEvent(1000);
                         break;
                     }
                 case EVENT_YMIRON_BANE:
                     {
                         me->CastSpell(me, IsHeroic() ? SPELL_BANE_H : SPELL_BANE_N, false);
                         events.RepeatEvent(20000 + rand() % 5000);
                         break;
                     }
                 case EVENT_YMIRON_FETID_ROT:
                     {
                         me->CastSpell(me->GetVictim(), IsHeroic() ? SPELL_FETID_ROT_H : SPELL_FETID_ROT_N, false);
                         events.RepeatEvent(10000 + rand() % 3000);
                         break;
                     }
                 case EVENT_YMIRON_DARK_SLASH:
                     {
                         int32 dmg = me->GetVictim()->GetHealth() / 2;
                         me->CastCustomSpell(me->GetVictim(), SPELL_DARK_SLASH, &dmg, 0, 0, false);
                         events.RepeatEvent(30000 + rand() % 5000);
                         break;
                     }
                 case EVENT_YMIRON_ACTIVATE_BOAT:
                     {
                         // Spawn it!
                         if (Creature* king = me->SummonCreature(BoatStructure[BoatOrder[BoatNum - 1]].npc, BoatStructure[BoatOrder[BoatNum - 1]].SpawnX, BoatStructure[BoatOrder[BoatNum - 1]].SpawnY, BoatStructure[BoatOrder[BoatNum - 1]].SpawnZ, BoatStructure[BoatOrder[BoatNum - 1]].SpawnO, TEMPSUMMON_CORPSE_DESPAWN, 0))
{
                             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                             king->CastSpell(me, SPELL_CHANNEL_SPIRIT_TO_YMIRON, true);
                             summons.Summon(king);
                             king->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE);
                             king->SetDisableGravity(true);
                             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE);
                             me->GetMotionMaster()->MoveChase(me->GetVictim());
                             switch(BoatOrder[BoatNum - 1])
{
                                 case 0:
                                     events.ScheduleEvent(EVENT_YMIRON_RANULF_ABILITY, 3000, 1);
                                     break;
                                 case 1:
                                     events.ScheduleEvent(EVENT_YMIRON_TORGYN_ABILITY, 3000, 1);
                                     break;
                                 case 2:
                                     events.ScheduleEvent(EVENT_YMIRON_BJORN_ABILITY, 3000, 1);
                                     break;
                                 case 3:
                                     events.ScheduleEvent(EVENT_YMIRON_HALDOR_ABILITY, 3000, 1);
                                     break;
                             }
                         }
                         break;
                     }
                 case EVENT_YMIRON_BJORN_ABILITY:
                     {
                         if (Creature* sf = me->SummonCreature(NPC_SPIRIT_FOUNT, 385 + rand() % 10, -330 + rand() % 10, 104.756f, 0, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 180000))
{
                             summons.Summon(sf);
                             sf->SetSpeed(MOVE_RUN, 0.4f);
                             sf->AddAura(IsHeroic() ? SPELL_SPIRIT_FOUNT_H : SPELL_SPIRIT_FOUNT_N, sf);
                             sf->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                             sf->GetMotionMaster()->MoveFollow(me->GetVictim(), 0, rand_norm()*M_PI * 2);
                         }
                         break;
                     }
                 case EVENT_YMIRON_HALDOR_ABILITY:
                     {
                         me->CastSpell(me->GetVictim(), IsHeroic() ? SPELL_SPIRIT_STRIKE_H : SPELL_SPIRIT_STRIKE_N, false);
                         events.RepeatEvent(5000);
                         break;
                     }
                 case EVENT_YMIRON_RANULF_ABILITY:
                     {
                         me->CastSpell(me, IsHeroic() ? SPELL_SPIRIT_BURST_H : SPELL_SPIRIT_BURST_N, false);
                         events.RepeatEvent(10000);
                         break;
                     }
                 case EVENT_YMIRON_TORGYN_ABILITY:
                     {
                         for(uint8 i = 0; i < 4; ++i)
{
                             if (Creature* as = me->SummonCreature(NPC_AVENGING_SPIRIT, me->GetPositionX() + rand() % 10, me->GetPositionY() + rand() % 10, me->GetPositionZ(), 0, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 30000))
{
                                 summons.Summon(as);
                                 as->SetInCombatWithZone();
                             }
                         }
                         events.RepeatEvent(15000);
                         break;
                     }
             }
             DoMeleeAttackIfReady();
         }
References BoatNum, BoatOrder, BoatStructure, Unit::CastCustomSpell(), Unit::CastSpell(), MotionMaster::Clear(), SummonList::DespawnAll(), UnitAI::DoMeleeAttackIfReady(), EVENT_YMIRON_ACTIVATE_BOAT, EVENT_YMIRON_BANE, EVENT_YMIRON_BJORN_ABILITY, EVENT_YMIRON_DARK_SLASH, EVENT_YMIRON_FETID_ROT, EVENT_YMIRON_HALDOR_ABILITY, EVENT_YMIRON_HEALTH_CHECK, EVENT_YMIRON_RANULF_ABILITY, EVENT_YMIRON_TORGYN_ABILITY, Unit::GetHealth(), Unit::GetMaxHealth(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::GetVictim(), Unit::HasUnitState(), Unit::InterruptNonMeleeSpells(), ScriptedAI::IsHeroic(), ScriptedAI::me, MOVE_RUN, MotionMaster::MoveChase(), MotionMaster::MovePoint(), ActiveBoatStruct::npc, NPC_AVENGING_SPIRIT, NPC_SPIRIT_FOUNT, rand_norm(), Object::RemoveFlag(), Object::SetFlag(), ActiveBoatStruct::SpawnO, ActiveBoatStruct::SpawnX, ActiveBoatStruct::SpawnY, ActiveBoatStruct::SpawnZ, SPELL_BANE_H, SPELL_BANE_N, SPELL_CHANNEL_SPIRIT_TO_YMIRON, SPELL_DARK_SLASH, SPELL_FETID_ROT_H, SPELL_FETID_ROT_N, SPELL_FLAMES, SPELL_SCREAMS_OF_THE_DEAD, SPELL_SPIRIT_BURST_H, SPELL_SPIRIT_BURST_N, SPELL_SPIRIT_FOUNT_H, SPELL_SPIRIT_FOUNT_N, SPELL_SPIRIT_STRIKE_H, SPELL_SPIRIT_STRIKE_N, SummonList::Summon(), WorldObject::SummonCreature(), summons, summons2, WorldObject::SummonTrigger(), TEMPSUMMON_CORPSE_DESPAWN, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, UNIT_FIELD_FLAGS, UNIT_FLAG_DISABLE_MOVE, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
BoatNum
uint8 boss_ymiron::boss_ymironAI::BoatNum
Definition at line 122 of file boss_ymiron.cpp.
Referenced by MovementInform(), Reset(), and UpdateAI().
BoatOrder
uint8 boss_ymiron::boss_ymironAI::BoatOrder[4]
Definition at line 123 of file boss_ymiron.cpp.
Referenced by MovementInform(), Reset(), and UpdateAI().
events
EventMap boss_ymiron::boss_ymironAI::events
Definition at line 119 of file boss_ymiron.cpp.
pInstance
InstanceScript* boss_ymiron::boss_ymironAI::pInstance
Definition at line 118 of file boss_ymiron.cpp.
Referenced by boss_ymironAI(), EnterCombat(), JustDied(), Reset(), and SpellHitTarget().
summons
SummonList boss_ymiron::boss_ymironAI::summons
Definition at line 120 of file boss_ymiron.cpp.
Referenced by JustDied(), Reset(), and UpdateAI().
summons2
SummonList boss_ymiron::boss_ymironAI::summons2
Definition at line 121 of file boss_ymiron.cpp.
Referenced by JustDied(), Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/UtgardeKeep/UtgardePinnacle/boss_ymiron.cpp