Azerotcore-wotlk: deps/mysqllite/include/my_pthread.h File Reference
my_pthread.h File Reference
#include "my_global.h"
#include <pthread.h>
#include <mysql/psi/mysql_thread.h>
Classes
struct st_safe_mutex_t
struct st_rw_pr_lock_t
struct st_my_rw_lock_t
struct st_my_thread_var
Macros
#define ETIME ETIMEDOUT /* For FreeBSD */
#define EXTERNC
#define pthread_key(T, V) pthread_key_t V
#define my_pthread_getspecific_ptr(T, V) my_pthread_getspecific(T,(V))
#define my_pthread_setspecific_ptr(T, V) pthread_setspecific(T,(void*) (V))
#define pthread_detach_this_thread()
#define pthread_handler_t EXTERNC void *
#define my_pthread_once_t pthread_once_t
#define MY_PTHREAD_ONCE_INIT PTHREAD_ONCE_INIT
#define my_pthread_once(C, F) pthread_once(C,F)
#define my_sigwait(A, B) sigwait((A),(B))
#define my_sigset(A, B) signal((A),(B))
#define pthread_attr_setscope(A, B)
#define my_pthread_getspecific(A, B) ((A) pthread_getspecific(B))
#define pthread_key_delete(A) pthread_dummy(0)
#define HAVE_PTHREAD_KILL
#define set_timespec(ABSTIME, SEC)
#define set_timespec_nsec(ABSTIME, NSEC)
#define cmp_timespec(TS1, TS2)
#define safe_mutex_assert_owner(mp)
#define safe_mutex_assert_not_owner(mp)
#define NEED_MY_RW_LOCK 1
#define rw_lock_t my_rw_lock_t
#define my_rwlock_init(A, B) my_rw_init((A))
#define rw_rdlock(A) my_rw_rdlock((A))
#define rw_wrlock(A) my_rw_wrlock((A))
#define rw_tryrdlock(A) my_rw_tryrdlock((A))
#define rw_trywrlock(A) my_rw_trywrlock((A))
#define rw_unlock(A) my_rw_unlock((A))
#define rwlock_destroy(A) my_rw_destroy((A))
#define rw_lock_assert_write_owner(A) my_rw_lock_assert_write_owner((A))
#define rw_lock_assert_not_write_owner(A) my_rw_lock_assert_not_write_owner((A))
#define rw_pr_lock_assert_write_owner(A)
#define rw_pr_lock_assert_not_write_owner(A)
#define my_rw_lock_assert_write_owner(A)
#define my_rw_lock_assert_not_write_owner(A)
#define GETHOSTBYADDR_BUFF_SIZE 2048
#define thr_setconcurrency(A) pthread_dummy(0)
#define pthread_attr_setstacksize(A, B) pthread_dummy(0)
#define MY_MUTEX_INIT_SLOW NULL
#define MY_MUTEX_INIT_FAST NULL
#define MY_MUTEX_INIT_ERRCHK NULL
#define ESRCH 1
#define THREAD_NAME_SIZE 10
#define DEFAULT_THREAD_STACK (192*1024)
#define INSTRUMENT_ME 0
#define my_thread_var (_my_thread_var())
#define my_errno my_thread_var->thr_errno
#define THD_LIB_OTHER 1
#define THD_LIB_NPTL 2
#define THD_LIB_LT 4
#define thread_safe_increment(V, L) (mysql_mutex_lock((L)), (V)++, mysql_mutex_unlock((L)))
#define thread_safe_decrement(V, L) (mysql_mutex_lock((L)), (V)--, mysql_mutex_unlock((L)))
#define thread_safe_add(V, C, L) (mysql_mutex_lock((L)), (V)+=(C), mysql_mutex_unlock((L)))
#define thread_safe_sub(V, C, L) (mysql_mutex_lock((L)), (V)-=(C), mysql_mutex_unlock((L)))
#define statistic_decrement(V, L) (V)--
#define statistic_increment(V, L) (V)++
#define statistic_add(V, C, L) (V)+=(C)
#define statistic_sub(V, C, L) (V)-=(C)
#define status_var_increment(V) (V)++
#define status_var_decrement(V) (V)--
#define status_var_add(V, C) (V)+=(C)
#define status_var_sub(V, C) (V)-=(C)
Typedefs
typedef void *(* pthread_handler) (void *)
typedef struct st_safe_mutex_t safe_mutex_t
typedef struct st_rw_pr_lock_t rw_pr_lock_t
typedef struct st_my_rw_lock_t my_rw_lock_t
typedef ulong my_thread_id
Functions
int sigwait (sigset_t *setp, int *sigp)
struct tm * localtime_r (const time_t *clock, struct tm *res)
struct tm * gmtime_r (const time_t *clock, struct tm *res)
int safe_mutex_init (safe_mutex_t *mp, const pthread_mutexattr_t *attr, const char *file, uint line)
int safe_mutex_lock (safe_mutex_t *mp, my_bool try_lock, const char *file, uint line)
int safe_mutex_unlock (safe_mutex_t *mp, const char *file, uint line)
int safe_mutex_destroy (safe_mutex_t *mp, const char *file, uint line)
int safe_cond_wait (pthread_cond_t *cond, safe_mutex_t *mp, const char *file, uint line)
int safe_cond_timedwait (pthread_cond_t *cond, safe_mutex_t *mp, const struct timespec *abstime, const char *file, uint line)
void safe_mutex_global_init (void)
void safe_mutex_end (FILE *file)
int rw_pr_init (rw_pr_lock_t *)
int rw_pr_rdlock (rw_pr_lock_t *)
int rw_pr_wrlock (rw_pr_lock_t *)
int rw_pr_unlock (rw_pr_lock_t *)
int rw_pr_destroy (rw_pr_lock_t *)
int my_rw_init (my_rw_lock_t *)
int my_rw_destroy (my_rw_lock_t *)
int my_rw_rdlock (my_rw_lock_t *)
int my_rw_wrlock (my_rw_lock_t *)
int my_rw_unlock (my_rw_lock_t *)
int my_rw_tryrdlock (my_rw_lock_t *)
int my_rw_trywrlock (my_rw_lock_t *)
my_bool my_thread_global_init (void)
my_bool my_thread_basic_global_init (void)
void my_thread_basic_global_reinit (void)
void my_thread_global_end (void)
my_bool my_thread_init (void)
void my_thread_end (void)
const char * my_thread_name (void)
my_thread_id my_thread_dbug_id (void)
int pthread_dummy (int)
struct st_my_thread_var * _my_thread_var (void) __attribute__((const))
void ** my_thread_var_dbug ()
Variables
uint my_thread_end_wait_time
uint thd_lib_detected
Macro Definition Documentation
cmp_timespec
#define cmp_timespec (TS1, TS2)
Value:
  ((TS1.tv_sec > TS2.tv_sec || \
    (TS1.tv_sec == TS2.tv_sec && TS1.tv_nsec > TS2.tv_nsec)) ? 1 : \
   ((TS1.tv_sec < TS2.tv_sec || \
     (TS1.tv_sec == TS2.tv_sec && TS1.tv_nsec < TS2.tv_nsec)) ? -1 : 0))
Compare two timespec structs.
Return values
1 If TS1 ends after TS2.
0 If TS1 is equal to TS2.
-1 If TS1 ends before TS2.
Definition at line 463 of file my_pthread.h.
DEFAULT_THREAD_STACK
#define DEFAULT_THREAD_STACK (192*1024)
Definition at line 829 of file my_pthread.h.
ESRCH
#define ESRCH 1
Definition at line 803 of file my_pthread.h.
ETIME
#define ETIME ETIMEDOUT /* For FreeBSD */
Definition at line 24 of file my_pthread.h.
EXTERNC
#define EXTERNC
Definition at line 31 of file my_pthread.h.
GETHOSTBYADDR_BUFF_SIZE
#define GETHOSTBYADDR_BUFF_SIZE 2048
Definition at line 777 of file my_pthread.h.
HAVE_PTHREAD_KILL
#define HAVE_PTHREAD_KILL
Definition at line 369 of file my_pthread.h.
INSTRUMENT_ME
#define INSTRUMENT_ME 0
Definition at line 835 of file my_pthread.h.
my_errno
#define my_errno my_thread_var->thr_errno
Definition at line 862 of file my_pthread.h.
MY_MUTEX_INIT_ERRCHK
#define MY_MUTEX_INIT_ERRCHK NULL
Definition at line 798 of file my_pthread.h.
MY_MUTEX_INIT_FAST
#define MY_MUTEX_INIT_FAST NULL
Definition at line 792 of file my_pthread.h.
MY_MUTEX_INIT_SLOW
#define MY_MUTEX_INIT_SLOW NULL
Definition at line 787 of file my_pthread.h.
my_pthread_getspecific
#define my_pthread_getspecific (A, B) ((A) pthread_getspecific(B))
Definition at line 300 of file my_pthread.h.
my_pthread_getspecific_ptr
#define my_pthread_getspecific_ptr (T, V) my_pthread_getspecific(T,(V))
Definition at line 210 of file my_pthread.h.
my_pthread_once
#define my_pthread_once (C, F) pthread_once(C,F)
Definition at line 222 of file my_pthread.h.
MY_PTHREAD_ONCE_INIT
#define MY_PTHREAD_ONCE_INIT PTHREAD_ONCE_INIT
Definition at line 220 of file my_pthread.h.
my_pthread_once_t
#define my_pthread_once_t pthread_once_t
Definition at line 216 of file my_pthread.h.
my_pthread_setspecific_ptr
#define my_pthread_setspecific_ptr (T, V) pthread_setspecific(T,(void*) (V))
Definition at line 211 of file my_pthread.h.
my_rw_lock_assert_not_write_owner
#define my_rw_lock_assert_not_write_owner (A)
Definition at line 772 of file my_pthread.h.
my_rw_lock_assert_write_owner
#define my_rw_lock_assert_write_owner (A)
Definition at line 771 of file my_pthread.h.
my_rwlock_init
#define my_rwlock_init (A, B) my_rw_init((A))
Definition at line 613 of file my_pthread.h.
my_sigset
#define my_sigset (A, B) signal((A),(B))
Definition at line 284 of file my_pthread.h.
my_sigwait
#define my_sigwait (A, B) sigwait((A),(B))
Definition at line 241 of file my_pthread.h.
my_thread_var
#define my_thread_var (_my_thread_var())
Definition at line 861 of file my_pthread.h.
NEED_MY_RW_LOCK
#define NEED_MY_RW_LOCK 1
Definition at line 611 of file my_pthread.h.
pthread_attr_setscope
#define pthread_attr_setscope (A, B)
Definition at line 288 of file my_pthread.h.
pthread_attr_setstacksize
#define pthread_attr_setstacksize (A, B) pthread_dummy(0)
Definition at line 783 of file my_pthread.h.
pthread_detach_this_thread
#define pthread_detach_this_thread ()
Definition at line 212 of file my_pthread.h.
pthread_handler_t
#define pthread_handler_t EXTERNC void *
Definition at line 213 of file my_pthread.h.
pthread_key
#define pthread_key (T, V) pthread_key_t V
Definition at line 209 of file my_pthread.h.
pthread_key_delete
#define pthread_key_delete (A) pthread_dummy(0)
Definition at line 322 of file my_pthread.h.
rw_lock_assert_not_write_owner
#define rw_lock_assert_not_write_owner (A) my_rw_lock_assert_not_write_owner((A))
Definition at line 621 of file my_pthread.h.
rw_lock_assert_write_owner
#define rw_lock_assert_write_owner (A) my_rw_lock_assert_write_owner((A))
Definition at line 620 of file my_pthread.h.
rw_lock_t
#define rw_lock_t my_rw_lock_t
Definition at line 612 of file my_pthread.h.
rw_pr_lock_assert_not_write_owner
#define rw_pr_lock_assert_not_write_owner (A)
Definition at line 693 of file my_pthread.h.
rw_pr_lock_assert_write_owner
#define rw_pr_lock_assert_write_owner (A)
Definition at line 692 of file my_pthread.h.
rw_rdlock
#define rw_rdlock (A) my_rw_rdlock((A))
Definition at line 614 of file my_pthread.h.
rw_tryrdlock
#define rw_tryrdlock (A) my_rw_tryrdlock((A))
Definition at line 616 of file my_pthread.h.
rw_trywrlock
#define rw_trywrlock (A) my_rw_trywrlock((A))
Definition at line 617 of file my_pthread.h.
rw_unlock
#define rw_unlock (A) my_rw_unlock((A))
Definition at line 618 of file my_pthread.h.
rw_wrlock
#define rw_wrlock (A) my_rw_wrlock((A))
Definition at line 615 of file my_pthread.h.
rwlock_destroy
#define rwlock_destroy (A) my_rw_destroy((A))
Definition at line 619 of file my_pthread.h.
safe_mutex_assert_not_owner
#define safe_mutex_assert_not_owner (mp)
Definition at line 541 of file my_pthread.h.
safe_mutex_assert_owner
#define safe_mutex_assert_owner (mp)
Definition at line 540 of file my_pthread.h.
set_timespec
#define set_timespec (ABSTIME, SEC)
Value:
{\
  struct timeval tv;\
  gettimeofday(&tv,0);\
  (ABSTIME).tv_sec=tv.tv_sec+(time_t) (SEC);\
  (ABSTIME).tv_nsec=tv.tv_usec*1000;\
}
Definition at line 426 of file my_pthread.h.
set_timespec_nsec
#define set_timespec_nsec (ABSTIME, NSEC)
Value:
{\
  ulonglong now= my_getsystime() + (NSEC/100); \
  (ABSTIME).tv_sec=  (time_t) (now / ULL(10000000));                  \
  (ABSTIME).tv_nsec= (long) (now % ULL(10000000) * 100 + ((NSEC) % 100)); \
}
Definition at line 435 of file my_pthread.h.
statistic_add
#define statistic_add (V, C, L) (V)+=(C)
Definition at line 928 of file my_pthread.h.
statistic_decrement
#define statistic_decrement (V, L) (V)--
Definition at line 926 of file my_pthread.h.
statistic_increment
#define statistic_increment (V, L) (V)++
Definition at line 927 of file my_pthread.h.
statistic_sub
#define statistic_sub (V, C, L) (V)-=(C)
Definition at line 929 of file my_pthread.h.
status_var_add
#define status_var_add (V, C) (V)+=(C)
Definition at line 937 of file my_pthread.h.
status_var_decrement
#define status_var_decrement (V) (V)--
Definition at line 936 of file my_pthread.h.
status_var_increment
#define status_var_increment (V) (V)++
Definition at line 935 of file my_pthread.h.
status_var_sub
#define status_var_sub (V, C) (V)-=(C)
Definition at line 938 of file my_pthread.h.
THD_LIB_LT
#define THD_LIB_LT 4
Definition at line 872 of file my_pthread.h.
THD_LIB_NPTL
#define THD_LIB_NPTL 2
Definition at line 871 of file my_pthread.h.
THD_LIB_OTHER
#define THD_LIB_OTHER 1
Definition at line 870 of file my_pthread.h.
thr_setconcurrency
#define thr_setconcurrency (A) pthread_dummy(0)
Definition at line 780 of file my_pthread.h.
THREAD_NAME_SIZE
#define THREAD_NAME_SIZE 10
Definition at line 820 of file my_pthread.h.
thread_safe_add
#define thread_safe_add (V, C, L) (mysql_mutex_lock((L)), (V)+=(C), mysql_mutex_unlock((L)))
Definition at line 901 of file my_pthread.h.
thread_safe_decrement
#define thread_safe_decrement (V, L) (mysql_mutex_lock((L)), (V)--, mysql_mutex_unlock((L)))
Definition at line 891 of file my_pthread.h.
thread_safe_increment
#define thread_safe_increment (V, L) (mysql_mutex_lock((L)), (V)++, mysql_mutex_unlock((L)))
Definition at line 889 of file my_pthread.h.
thread_safe_sub
#define thread_safe_sub (V, C, L) (mysql_mutex_lock((L)), (V)-=(C), mysql_mutex_unlock((L)))
Definition at line 903 of file my_pthread.h.
Typedef Documentation
my_rw_lock_t
typedef struct st_my_rw_lock_t my_rw_lock_t
my_thread_id
typedef ulong my_thread_id
Definition at line 806 of file my_pthread.h.
pthread_handler
typedef void*(* pthread_handler) (void *)
Definition at line 214 of file my_pthread.h.
rw_pr_lock_t
typedef struct st_rw_pr_lock_t rw_pr_lock_t
Portable implementation of special type of read-write locks.
These locks have two properties which are unusual for rwlocks: 1) They "prefer readers" in the sense that they do not allow situations in which rwlock is rd-locked and there is a pending rd-lock which is blocked (e.g. due to pending request for wr-lock). This is a stronger guarantee than one which is provided for PTHREAD_RWLOCK_PREFER_READER_NP rwlocks in Linux. MDL subsystem deadlock detector relies on this property for its correctness. 2) They are optimized for uncontended wr-lock/unlock case. This is scenario in which they are most oftenly used within MDL subsystem. Optimizing for it gives significant performance improvements in some of tests involving many connections.
Another important requirement imposed on this type of rwlock by the MDL subsystem is that it should be OK to destroy rwlock object which is in unlocked state even though some threads might have not yet fully left unlock operation for it (of course there is an external guarantee that no thread will try to lock rwlock which is destroyed). Putting it another way the unlock operation should not access rwlock data after changing its state to unlocked.
TODO/FIXME: We should consider alleviating this requirement as it blocks us from doing certain performance optimizations.
safe_mutex_t
typedef struct st_safe_mutex_t safe_mutex_t
Function Documentation
_my_thread_var()
struct st_my_thread_var* _my_thread_var (void) const
gmtime_r()
struct tm* gmtime_r (const time_t * clock, struct tm * res)
Definition at line 92 of file my_pthread.c.
 {
   struct tm *tmp;
   mysql_mutex_lock(&LOCK_localtime_r);
   tmp= gmtime(clock);
   *res= *tmp;
   mysql_mutex_unlock(&LOCK_localtime_r);
   return res;
 }
References gmtime(), LOCK_localtime_r, mysql_mutex_lock, and mysql_mutex_unlock.
localtime_r()
struct tm* localtime_r (const time_t * clock, struct tm * res)
Definition at line 75 of file my_pthread.c.
 {
   struct tm *tmp;
   mysql_mutex_lock(&LOCK_localtime_r);
   tmp=localtime(clock);
   *res= *tmp;
   mysql_mutex_unlock(&LOCK_localtime_r);
   return res;
 }
References localtime(), LOCK_localtime_r, mysql_mutex_lock, and mysql_mutex_unlock.
Referenced by Player::_LoadBrewOfTheMonth(), npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::AllowStart(), ByteBuffer::AppendPackedTime(), get_date(), World::GetNextTimeWithDayAndHour(), World::GetNextTimeWithMonthAndHour(), Log::GetTimestampStr(), LogMessage::getTimeStr(), ban_commandscript::HandleBanListCharacterCommand(), ban_commandscript::HandleBanListHelper(), ban_commandscript::HandleBanListIPCommand(), guild_commandscript::HandleGuildInfoCommand(), misc_commandscript::HandleMuteInfoHelper(), localtime(), AchievementCriteriaData::Meets(), my_init_time(), my_system_gmt_sec(), Weather::ReGenerate(), GameEventMgr::SetHolidayEventTime(), soap_dateTime2s(), TimeBreakdown(), TimeToHumanReadable(), TimeToTimestampStr(), go_bells::go_bellsAI::UpdateAI(), npc_elder_clearwater::npc_elder_clearwaterAI::UpdateAI(), and npc_riggle_bassbait::npc_riggle_bassbaitAI::UpdateAI().
my_rw_destroy()
int my_rw_destroy (my_rw_lock_t *)
my_rw_init()
int my_rw_init (my_rw_lock_t *)
_WIN32
my_rw_rdlock()
int my_rw_rdlock (my_rw_lock_t *)
my_rw_tryrdlock()
int my_rw_tryrdlock (my_rw_lock_t *)
my_rw_trywrlock()
int my_rw_trywrlock (my_rw_lock_t *)
my_rw_unlock()
int my_rw_unlock (my_rw_lock_t *)
my_rw_wrlock()
int my_rw_wrlock (my_rw_lock_t *)
my_thread_basic_global_init()
my_bool my_thread_basic_global_init (void)
Perform a minimal initialisation of mysys, when compiled with threads. The initialisation performed is sufficient to:
allocate memory
perform file operations
use charsets
use my_errno
See also
my_basic_init
my_thread_basic_global_reinit
Definition at line 82 of file my_thr_init.c.
 {
   int pth_ret;
   if (my_thread_basic_global_init_done)
     return 0;
   my_thread_basic_global_init_done= 1;
 #ifdef PTHREAD_ADAPTIVE_MUTEX_INITIALIZER_NP
   /*
     Set mutex type to "fast" a.k.a "adaptive"
     In this case the thread may steal the mutex from some other thread
     that is waiting for the same mutex.  This will save us some
     context switches but may cause a thread to 'starve forever' while
     waiting for the mutex (not likely if the code within the mutex is
     short).
   */
   pthread_mutexattr_init(&my_fast_mutexattr);
   pthread_mutexattr_settype(&my_fast_mutexattr,
                             PTHREAD_MUTEX_ADAPTIVE_NP);
 #endif
 #ifdef PTHREAD_ERRORCHECK_MUTEX_INITIALIZER_NP
   /*
     Set mutex type to "errorcheck"
   */
   pthread_mutexattr_init(&my_errorcheck_mutexattr);
   pthread_mutexattr_settype(&my_errorcheck_mutexattr,
                             PTHREAD_MUTEX_ERRORCHECK);
 #endif
   mysql_mutex_init(key_THR_LOCK_malloc, &THR_LOCK_malloc, MY_MUTEX_INIT_FAST);
   mysql_mutex_init(key_THR_LOCK_open, &THR_LOCK_open, MY_MUTEX_INIT_FAST);
   mysql_mutex_init(key_THR_LOCK_charset, &THR_LOCK_charset, MY_MUTEX_INIT_FAST);
   mysql_mutex_init(key_THR_LOCK_threads, &THR_LOCK_threads, MY_MUTEX_INIT_FAST);
   if ((pth_ret= pthread_key_create(&THR_KEY_mysys, NULL)) != 0)
   {
     fprintf(stderr, "Can't initialize threads: error %d\n", pth_ret);
     return 1;
   }
   if (my_thread_init())
     return 1;
   return 0;
 }
References fprintf(), MY_MUTEX_INIT_FAST, my_thread_basic_global_init_done, my_thread_init(), mysql_mutex_init, NULL, THR_LOCK_charset, THR_LOCK_malloc, THR_LOCK_open, and THR_LOCK_threads.
Referenced by my_basic_init(), and my_thread_global_init().
my_thread_basic_global_reinit()
void my_thread_basic_global_reinit (void)
Re-initialize components initialized early with my_thread_basic_global_init. Some mutexes were initialized before the instrumentation. Destroy + create them again, now that the instrumentation is in place. This is safe, since this function() is called before creating new threads, so the mutexes are not in use.
Definition at line 139 of file my_thr_init.c.
 {
   struct st_my_thread_var *tmp;
   DBUG_ASSERT(my_thread_basic_global_init_done);
 #ifdef HAVE_PSI_INTERFACE
   my_init_mysys_psi_keys();
 #endif
   mysql_mutex_destroy(&THR_LOCK_malloc);
   mysql_mutex_init(key_THR_LOCK_malloc, &THR_LOCK_malloc, MY_MUTEX_INIT_FAST);
   mysql_mutex_destroy(&THR_LOCK_open);
   mysql_mutex_init(key_THR_LOCK_open, &THR_LOCK_open, MY_MUTEX_INIT_FAST);
   mysql_mutex_destroy(&THR_LOCK_charset);
   mysql_mutex_init(key_THR_LOCK_charset, &THR_LOCK_charset, MY_MUTEX_INIT_FAST);
   mysql_mutex_destroy(&THR_LOCK_threads);
   mysql_mutex_init(key_THR_LOCK_threads, &THR_LOCK_threads, MY_MUTEX_INIT_FAST);
   tmp= my_pthread_getspecific(struct st_my_thread_var*, THR_KEY_mysys);
   DBUG_ASSERT(tmp);
   mysql_mutex_destroy(&tmp->mutex);
   mysql_mutex_init(key_my_thread_var_mutex, &tmp->mutex, MY_MUTEX_INIT_FAST);
   mysql_cond_destroy(&tmp->suspend);
   mysql_cond_init(key_my_thread_var_suspend, &tmp->suspend, NULL);
 }
References DBUG_ASSERT, st_my_thread_var::mutex, MY_MUTEX_INIT_FAST, my_pthread_getspecific, my_thread_basic_global_init_done, mysql_cond_destroy, mysql_cond_init, mysql_mutex_destroy, mysql_mutex_init, NULL, st_my_thread_var::suspend, THR_LOCK_charset, THR_LOCK_malloc, THR_LOCK_open, and THR_LOCK_threads.
my_thread_dbug_id()
my_thread_id my_thread_dbug_id (void)
Definition at line 456 of file my_thr_init.c.
 {
   return my_thread_var->id;
 }
References my_thread_var.
Referenced by my_thread_name().
my_thread_end()
void my_thread_end (void)
Definition at line 393 of file my_thr_init.c.
 {
   struct st_my_thread_var *tmp;
   tmp= my_pthread_getspecific(struct st_my_thread_var*,THR_KEY_mysys);
 #ifdef EXTRA_DEBUG_THREADS
   fprintf(stderr,"my_thread_end(): tmp: 0x%lx  pthread_self: 0x%lx  thread_id: %ld\n",
       (long) tmp, (long) pthread_self(), tmp ? (long) tmp->id : 0L);
 #endif
 #ifdef HAVE_PSI_INTERFACE
   /*
     Remove the instrumentation for this thread.
     This must be done before trashing st_my_thread_var,
     because the LF_HASH depends on it.
   */
   if (PSI_server)
     PSI_server->delete_current_thread();
 #endif
   if (tmp && tmp->init)
   {
 #if !defined(DBUG_OFF)
     /* tmp->dbug is allocated inside DBUG library */
     if (tmp->dbug)
     {
       DBUG_POP();
       free(tmp->dbug);
       tmp->dbug=0;
     }
 #endif
 #if !defined(__bsdi__) && !defined(__OpenBSD__)
  /* bsdi and openbsd 3.5 dumps core here */
     mysql_cond_destroy(&tmp->suspend);
 #endif
     mysql_mutex_destroy(&tmp->mutex);
     free(tmp);
     /*
       Decrement counter for number of running threads. We are using this
       in my_thread_global_end() to wait until all threads have called
       my_thread_end and thus freed all memory they have allocated in
       my_thread_init() and DBUG_xxxx
     */
     mysql_mutex_lock(&THR_LOCK_threads);
     DBUG_ASSERT(THR_thread_count != 0);
     if (--THR_thread_count == 0)
       mysql_cond_signal(&THR_COND_threads);
     mysql_mutex_unlock(&THR_LOCK_threads);
   }
   pthread_setspecific(THR_KEY_mysys,0);
 }
References st_my_thread_var::dbug, DBUG_ASSERT, DBUG_POP, fprintf(), st_my_thread_var::id, st_my_thread_var::init, st_my_thread_var::mutex, my_pthread_getspecific, mysql_cond_destroy, mysql_cond_signal, mysql_mutex_destroy, mysql_mutex_lock, mysql_mutex_unlock, PSI_server, st_my_thread_var::pthread_self, st_my_thread_var::suspend, THR_COND_threads, THR_LOCK_threads, and THR_thread_count.
Referenced by my_end(), and mysql_thread_end().
my_thread_global_end()
void my_thread_global_end (void)
Definition at line 246 of file my_thr_init.c.
 {
   struct timespec abstime;
   my_bool all_threads_killed= 1;
   set_timespec(abstime, my_thread_end_wait_time);
   mysql_mutex_lock(&THR_LOCK_threads);
   while (THR_thread_count > 0)
   {
     int error= mysql_cond_timedwait(&THR_COND_threads, &THR_LOCK_threads,
                                     &abstime);
     if (error == ETIMEDOUT || error == ETIME)
     {
 #ifdef HAVE_PTHREAD_KILL
       /*
         We shouldn't give an error here, because if we don't have
         pthread_kill(), programs like mysqld can't ensure that all threads
         are killed when we enter here.
       */
       if (THR_thread_count)
         fprintf(stderr,
                 "Error in my_thread_global_end(): %d threads didn't exit\n",
                 THR_thread_count);
 #endif
       all_threads_killed= 0;
       break;
     }
   }
   mysql_mutex_unlock(&THR_LOCK_threads);
   pthread_key_delete(THR_KEY_mysys);
 #ifdef PTHREAD_ADAPTIVE_MUTEX_INITIALIZER_NP
   pthread_mutexattr_destroy(&my_fast_mutexattr);
 #endif
 #ifdef PTHREAD_ERRORCHECK_MUTEX_INITIALIZER_NP
   pthread_mutexattr_destroy(&my_errorcheck_mutexattr);
 #endif
   mysql_mutex_destroy(&THR_LOCK_malloc);
   mysql_mutex_destroy(&THR_LOCK_open);
   mysql_mutex_destroy(&THR_LOCK_lock);
   mysql_mutex_destroy(&THR_LOCK_isam);
   mysql_mutex_destroy(&THR_LOCK_myisam);
   mysql_mutex_destroy(&THR_LOCK_myisam_mmap);
   mysql_mutex_destroy(&THR_LOCK_heap);
   mysql_mutex_destroy(&THR_LOCK_net);
   mysql_mutex_destroy(&THR_LOCK_time);
   mysql_mutex_destroy(&THR_LOCK_charset);
   if (all_threads_killed)
   {
     mysql_mutex_destroy(&THR_LOCK_threads);
     mysql_cond_destroy(&THR_COND_threads);
   }
 #if !defined(HAVE_LOCALTIME_R) || !defined(HAVE_GMTIME_R)
   mysql_mutex_destroy(&LOCK_localtime_r);
 #endif
 #ifndef HAVE_GETHOSTBYNAME_R
   mysql_mutex_destroy(&LOCK_gethostbyname_r);
 #endif
   my_thread_basic_global_init_done= 0;
 }
References error(), ETIME, fprintf(), LOCK_gethostbyname_r, LOCK_localtime_r, my_thread_basic_global_init_done, my_thread_end_wait_time, mysql_cond_destroy, mysql_cond_timedwait, mysql_mutex_destroy, mysql_mutex_lock, mysql_mutex_unlock, pthread_key_delete, set_timespec, THR_COND_threads, THR_LOCK_charset, THR_LOCK_heap, THR_LOCK_isam, THR_LOCK_lock, THR_LOCK_malloc, THR_LOCK_myisam, THR_LOCK_myisam_mmap, THR_LOCK_net, THR_LOCK_open, THR_LOCK_threads, THR_LOCK_time, and THR_thread_count.
Referenced by my_end(), and my_thread_global_init().
my_thread_global_init()
my_bool my_thread_global_init (void)
Definition at line 182 of file my_thr_init.c.
 {
   if (my_thread_basic_global_init())
     return 1;
   thd_lib_detected= get_thread_lib();
 #ifdef TARGET_OS_LINUX
   /*
     BUG#24507: Race conditions inside current NPTL pthread_exit()
     implementation.
     To avoid a possible segmentation fault during concurrent
     executions of pthread_exit(), a dummy thread is spawned which
     initializes internal variables of pthread lib. See bug description
     for a full explanation.
     TODO: Remove this code when fixed versions of glibc6 are in common
     use.
   */
   if (thd_lib_detected == THD_LIB_NPTL)
   {
     pthread_t       dummy_thread;
     pthread_attr_t  dummy_thread_attr;
     pthread_attr_init(&dummy_thread_attr);
     pthread_attr_setdetachstate(&dummy_thread_attr, PTHREAD_CREATE_JOINABLE);
     if (pthread_create(&dummy_thread,&dummy_thread_attr,
                        nptl_pthread_exit_hack_handler, NULL) == 0)
       (void)pthread_join(dummy_thread, NULL);
   }
 #endif /* TARGET_OS_LINUX */
   mysql_mutex_init(key_THR_LOCK_lock, &THR_LOCK_lock, MY_MUTEX_INIT_FAST);
   mysql_mutex_init(key_THR_LOCK_isam, &THR_LOCK_isam, MY_MUTEX_INIT_SLOW);
   mysql_mutex_init(key_THR_LOCK_myisam, &THR_LOCK_myisam, MY_MUTEX_INIT_SLOW);
   mysql_mutex_init(key_THR_LOCK_myisam_mmap, &THR_LOCK_myisam_mmap, MY_MUTEX_INIT_FAST);
   mysql_mutex_init(key_THR_LOCK_heap, &THR_LOCK_heap, MY_MUTEX_INIT_FAST);
   mysql_mutex_init(key_THR_LOCK_net, &THR_LOCK_net, MY_MUTEX_INIT_FAST);
   mysql_mutex_init(key_THR_LOCK_time, &THR_LOCK_time, MY_MUTEX_INIT_FAST);
   mysql_cond_init(key_THR_COND_threads, &THR_COND_threads, NULL);
 #if !defined(HAVE_LOCALTIME_R) || !defined(HAVE_GMTIME_R)
   mysql_mutex_init(key_LOCK_localtime_r, &LOCK_localtime_r, MY_MUTEX_INIT_SLOW);
 #endif
 #ifndef HAVE_GETHOSTBYNAME_R
   mysql_mutex_init(key_LOCK_gethostbyname_r,
                    &LOCK_gethostbyname_r, MY_MUTEX_INIT_SLOW);
 #endif
 #ifdef _MSC_VER
   install_sigabrt_handler();
 #endif
   if (my_thread_init())
   {
     my_thread_global_end();         /* Clean up */
     return 1;
   }
   return 0;
 }
References get_thread_lib(), LOCK_gethostbyname_r, LOCK_localtime_r, MY_MUTEX_INIT_FAST, MY_MUTEX_INIT_SLOW, my_thread_basic_global_init(), my_thread_global_end(), my_thread_init(), mysql_cond_init, mysql_mutex_init, NULL, thd_lib_detected, THD_LIB_NPTL, THR_COND_threads, THR_LOCK_heap, THR_LOCK_isam, THR_LOCK_lock, THR_LOCK_myisam, THR_LOCK_myisam_mmap, THR_LOCK_net, and THR_LOCK_time.
Referenced by my_basic_init(), and my_init().
my_thread_init()
my_bool my_thread_init (void)
Definition at line 330 of file my_thr_init.c.
 {
   struct st_my_thread_var *tmp;
   my_bool error=0;
 #ifdef EXTRA_DEBUG_THREADS
   fprintf(stderr,"my_thread_init(): thread_id: 0x%lx\n",
           (ulong) pthread_self());
 #endif
   if (my_pthread_getspecific(struct st_my_thread_var *,THR_KEY_mysys))
   {
 #ifdef EXTRA_DEBUG_THREADS
     fprintf(stderr,"my_thread_init() called more than once in thread 0x%lx\n",
             (long) pthread_self());
 #endif
     goto end;
   }
 #ifdef _MSC_VER
   install_sigabrt_handler();
 #endif
   if (!(tmp= (struct st_my_thread_var *) calloc(1, sizeof(*tmp))))
   {
     error= 1;
     goto end;
   }
   pthread_setspecific(THR_KEY_mysys,tmp);
   tmp->pthread_self= pthread_self();
   mysql_mutex_init(key_my_thread_var_mutex, &tmp->mutex, MY_MUTEX_INIT_FAST);
   mysql_cond_init(key_my_thread_var_suspend, &tmp->suspend, NULL);
   tmp->stack_ends_here= (char*)&tmp +
                          STACK_DIRECTION * (long)my_thread_stack_size;
   mysql_mutex_lock(&THR_LOCK_threads);
   tmp->id= ++thread_id;
   ++THR_thread_count;
   mysql_mutex_unlock(&THR_LOCK_threads);
   tmp->init= 1;
 #ifndef DBUG_OFF
   /* Generate unique name for thread */
   (void) my_thread_name();
 #endif
 end:
   return error;
 }
References error(), fprintf(), st_my_thread_var::id, st_my_thread_var::init, st_my_thread_var::mutex, MY_MUTEX_INIT_FAST, my_pthread_getspecific, my_thread_name(), my_thread_stack_size, mysql_cond_init, mysql_mutex_init, mysql_mutex_lock, mysql_mutex_unlock, NULL, st_my_thread_var::pthread_self, st_my_thread_var::stack_ends_here, st_my_thread_var::suspend, THR_LOCK_threads, THR_thread_count, and thread_id.
Referenced by mysql_server_init(), and mysql_thread_init().
my_thread_name()
const char* my_thread_name (void)
Definition at line 469 of file my_thr_init.c.
 {
   char name_buff[100];
   struct st_my_thread_var *tmp=my_thread_var;
   if (!tmp->name[0])
   {
     my_thread_id id= my_thread_dbug_id();
     sprintf(name_buff,"T@%lu", (ulong) id);
     strmake(tmp->name,name_buff,THREAD_NAME_SIZE);
   }
   return tmp->name;
 }
References my_thread_dbug_id(), my_thread_var, st_my_thread_var::name, sprintf(), strmake(), and THREAD_NAME_SIZE.
Referenced by DoPrefix(), my_thread_init(), thr_alarm(), and thr_multi_unlock().
my_thread_var_dbug()
void** my_thread_var_dbug ()
Definition at line 484 of file my_thr_init.c.
 {
   struct st_my_thread_var *tmp=
     my_pthread_getspecific(struct st_my_thread_var*,THR_KEY_mysys);
   return tmp && tmp->init ? &tmp->dbug : 0;
 }
References st_my_thread_var::dbug, st_my_thread_var::init, and my_pthread_getspecific.
Referenced by code_state().
pthread_dummy()
int pthread_dummy (int ret)
Definition at line 466 of file my_pthread.c.
 {
   return ret;
 }
References ret.
rw_pr_destroy()
int rw_pr_destroy (rw_pr_lock_t * rwlock)
Definition at line 367 of file thr_rwlock.c.
 {
   pthread_cond_destroy(&rwlock->no_active_readers);
   pthread_mutex_destroy(&rwlock->lock);
   return 0;
 }
References st_rw_pr_lock_t::lock, and st_rw_pr_lock_t::no_active_readers.
Referenced by inline_mysql_prlock_destroy().
rw_pr_init()
int rw_pr_init (rw_pr_lock_t * rwlock)
Definition at line 353 of file thr_rwlock.c.
 {
   pthread_mutex_init(&rwlock->lock, NULL);
   pthread_cond_init(&rwlock->no_active_readers, NULL);
   rwlock->active_readers= 0;
   rwlock->writers_waiting_readers= 0;
   rwlock->active_writer= FALSE;
 #ifdef SAFE_MUTEX
   rwlock->writer_thread= 0;
 #endif
   return 0;
 }
References st_rw_pr_lock_t::active_readers, st_rw_pr_lock_t::active_writer, FALSE, st_rw_pr_lock_t::lock, st_rw_pr_lock_t::no_active_readers, NULL, and st_rw_pr_lock_t::writers_waiting_readers.
Referenced by inline_mysql_prlock_init().
rw_pr_rdlock()
int rw_pr_rdlock (rw_pr_lock_t * rwlock)
Definition at line 375 of file thr_rwlock.c.
 {
   pthread_mutex_lock(&rwlock->lock);
   /*
     The fact that we were able to acquire 'lock' mutex means
     that there are no active writers and we can acquire rd-lock.
     Increment active readers counter to prevent requests for
     wr-lock from succeeding and unlock mutex.
   */
   rwlock->active_readers++;
   pthread_mutex_unlock(&rwlock->lock);
   return 0;
 }
References st_rw_pr_lock_t::active_readers, and st_rw_pr_lock_t::lock.
Referenced by inline_mysql_prlock_rdlock().
rw_pr_unlock()
int rw_pr_unlock (rw_pr_lock_t * rwlock)
Definition at line 426 of file thr_rwlock.c.
 {
   if (rwlock->active_writer)
   {
     /* We are unlocking wr-lock. */
 #ifdef SAFE_MUTEX
     rwlock->writer_thread= 0;
 #endif
     rwlock->active_writer= FALSE;
     if (rwlock->writers_waiting_readers)
     {
       /*
         Avoid expensive cond signal in case when there is no contention
         or it is wr-only.
         Note that from view point of performance it would be better to
         signal on the condition variable after unlocking mutex (as it
         reduces number of contex switches).
         Unfortunately this would mean that such rwlock can't be safely
         used by MDL subsystem, which relies on the fact that it is OK
         to destroy rwlock once it is in unlocked state.
       */
       pthread_cond_signal(&rwlock->no_active_readers);
     }
     pthread_mutex_unlock(&rwlock->lock);
   }
   else
   {
     /* We are unlocking rd-lock. */
     pthread_mutex_lock(&rwlock->lock);
     rwlock->active_readers--;
     if (rwlock->active_readers == 0 &&
         rwlock->writers_waiting_readers)
     {
       /*
         If we are last reader and there are waiting
         writers wake them up.
       */
       pthread_cond_signal(&rwlock->no_active_readers);
     }
     pthread_mutex_unlock(&rwlock->lock);
   }
   return 0;
 }
References st_rw_pr_lock_t::active_readers, st_rw_pr_lock_t::active_writer, FALSE, st_rw_pr_lock_t::lock, st_rw_pr_lock_t::no_active_readers, and st_rw_pr_lock_t::writers_waiting_readers.
Referenced by inline_mysql_prlock_unlock().
rw_pr_wrlock()
int rw_pr_wrlock (rw_pr_lock_t * rwlock)
Definition at line 390 of file thr_rwlock.c.
 {
   pthread_mutex_lock(&rwlock->lock);
   if (rwlock->active_readers != 0)
   {
     /* There are active readers. We have to wait until they are gone. */
     rwlock->writers_waiting_readers++;
     while (rwlock->active_readers != 0)
       pthread_cond_wait(&rwlock->no_active_readers, &rwlock->lock);
     rwlock->writers_waiting_readers--;
   }
   /*
     We own 'lock' mutex so there is no active writers.
     Also there are no active readers.
     This means that we can grant wr-lock.
     Not releasing 'lock' mutex until unlock will block
     both requests for rd and wr-locks.
     Set 'active_writer' flag to simplify unlock.
     Thanks to the fact wr-lock/unlock in the absence of
     contention from readers is essentially mutex lock/unlock
     with a few simple checks make this rwlock implementation
     wr-lock optimized.
   */
   rwlock->active_writer= TRUE;
 #ifdef SAFE_MUTEX
   rwlock->writer_thread= pthread_self();
 #endif
   return 0;
 }
References st_rw_pr_lock_t::active_readers, st_rw_pr_lock_t::active_writer, st_rw_pr_lock_t::lock, st_rw_pr_lock_t::no_active_readers, TRUE, and st_rw_pr_lock_t::writers_waiting_readers.
Referenced by inline_mysql_prlock_wrlock().
safe_cond_timedwait()
int safe_cond_timedwait (pthread_cond_t * cond, safe_mutex_t * mp, const struct timespec * abstime, const char * file, uint line)
safe_cond_wait()
int safe_cond_wait (pthread_cond_t * cond, safe_mutex_t * mp, const char * file, uint line)
safe_mutex_destroy()
int safe_mutex_destroy (safe_mutex_t * mp, const char * file, uint line)
Referenced by inline_mysql_mutex_destroy().
safe_mutex_end()
void safe_mutex_end (FILE * file)
Referenced by my_end().
safe_mutex_global_init()
void safe_mutex_global_init (void)
Referenced by my_basic_init().
safe_mutex_init()
int safe_mutex_init (safe_mutex_t * mp, const pthread_mutexattr_t * attr, const char * file, uint line)
Referenced by inline_mysql_mutex_init().
safe_mutex_lock()
int safe_mutex_lock (safe_mutex_t * mp, my_bool try_lock, const char * file, uint line)
Referenced by inline_mysql_mutex_lock(), and inline_mysql_mutex_trylock().
safe_mutex_unlock()
int safe_mutex_unlock (safe_mutex_t * mp, const char * file, uint line)
Referenced by inline_mysql_mutex_unlock().
sigwait()
int sigwait (sigset_t * setp, int * sigp)
Definition at line 172 of file my_pthread.c.
 {
   if (memcmp(setp,&sigwait_set,sizeof(sigwait_set)))
     sigwait_setup(setp);            /* Init or change of set */
   for (;;)
   {
     /*
       This is a fast, not 100% portable implementation to find the signal.
       Because the handler is blocked there should be at most 1 bit set, but
       the specification on this is somewhat shady so we use a set instead a
       single variable.
       */
     ulong *ptr= (ulong*) &px_recd;
     ulong *end=ptr+sizeof(px_recd)/sizeof(ulong);
     for ( ; ptr != end ; ptr++)
     {
       if (*ptr)
       {
     ulong set= *ptr;
     int found= (int) ((char*) ptr - (char*) &px_recd)*8+1;
     while (!(set & 1))
     {
       found++;
       set>>=1;
     }
     *sigp=found;
     sigdelset(&px_recd,found);
     return 0;
       }
     }
     sigsuspend(&rev_sigwait_set);
   }
   return 0;
 }
References ptr(), px_recd, rev_sigwait_set, set(), sigwait_set, and sigwait_setup().
Variable Documentation
my_thread_end_wait_time
uint my_thread_end_wait_time extern
Definition at line 33 of file my_thr_init.c.
Referenced by my_thread_global_end().
thd_lib_detected
uint thd_lib_detected extern
Definition at line 31 of file my_pthread.c.
Referenced by init_thr_alarm(), my_thread_global_init(), and process_alarm().