Azerotcore-wotlk: npc_vh_void_sentry::npc_vh_void_sentryAI Struct Reference
npc_vh_void_sentry::npc_vh_void_sentryAI Struct Reference
Public Member Functions
npc_vh_void_sentryAI (Creature *c)
void DoAction (int32 a) override
void JustDied (Unit *) override
void SummonedCreatureDespawn (Creature *pSummoned) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void Reset ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
ObjectGuid SummonedGUID
uint16 checkTimer
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 194 of file boss_zuramat.cpp.
Constructor & Destructor Documentation
npc_vh_void_sentryAI()
npc_vh_void_sentry::npc_vh_void_sentryAI::npc_vh_void_sentryAI (Creature * c) inline
Definition at line 196 of file boss_zuramat.cpp.
                                           : NullCreatureAI(c)
         {
             pInstance = c->GetInstanceScript();
             SummonedGUID.Clear();
             checkTimer = 5000;
             //me->CastSpell(me, SPELL_SUMMON_VOID_SENTRY_BALL, true);
             if (Creature* pSummoned = me->SummonCreature(NPC_VOID_SENTRY_BALL, *me, TEMPSUMMON_TIMED_DESPAWN, 300000))
             {
                 pSummoned->SetPhaseMask(1, true);
                 SummonedGUID = pSummoned->GetGUID();
                 pInstance->SetGuidData(DATA_ADD_TRASH_MOB, pSummoned->GetGUID());
             }
         }
References checkTimer, ObjectGuid::Clear(), DATA_ADD_TRASH_MOB, WorldObject::GetInstanceScript(), CreatureAI::me, NPC_VOID_SENTRY_BALL, pInstance, ZoneScript::SetGuidData(), WorldObject::SummonCreature(), SummonedGUID, and TEMPSUMMON_TIMED_DESPAWN.
Member Function Documentation
DoAction()
void npc_vh_void_sentry::npc_vh_void_sentryAI::DoAction (int32 a) inline override virtual
Reimplemented from UnitAI.
Definition at line 214 of file boss_zuramat.cpp.
         {
             if (a == -1337)
                 if (Creature* c = pInstance->instance->GetCreature(SummonedGUID))
                     c->DespawnOrUnsummon();
         }
References Map::GetCreature(), InstanceScript::instance, pInstance, and SummonedGUID.
JustDied()
void npc_vh_void_sentry::npc_vh_void_sentryAI::JustDied (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 221 of file boss_zuramat.cpp.
         {
             if (pInstance)
             {
                 pInstance->SetData(DATA_ACHIEV, 0);
                 if (Creature* c = pInstance->instance->GetCreature(SummonedGUID))
                     c->DespawnOrUnsummon();
             }
             me->DespawnOrUnsummon(5000);
         }
References DATA_ACHIEV, Creature::DespawnOrUnsummon(), Map::GetCreature(), InstanceScript::instance, CreatureAI::me, pInstance, ZoneScript::SetData(), and SummonedGUID.
SummonedCreatureDespawn()
void npc_vh_void_sentry::npc_vh_void_sentryAI::SummonedCreatureDespawn (Creature * pSummoned) inline override virtual
Reimplemented from CreatureAI.
Definition at line 232 of file boss_zuramat.cpp.
         {
             if (pSummoned)
                 pInstance->SetGuidData(DATA_DELETE_TRASH_MOB, pSummoned->GetGUID());
         }
References DATA_DELETE_TRASH_MOB, Object::GetGUID(), pInstance, and ZoneScript::SetGuidData().
UpdateAI()
void npc_vh_void_sentry::npc_vh_void_sentryAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 238 of file boss_zuramat.cpp.
         {
             if (checkTimer <= diff)
             {
                 checkTimer = 5000;
                 bool good = false;
                 if (me->IsSummon())
                     if (Unit* s = me->ToTempSummon()->GetSummonerUnit())
                         if (s->IsAlive())
                             good = true;
                 if (!good)
                     Unit::Kill(me, me);
             }
             else
                 checkTimer -= diff;
         }
References checkTimer, TempSummon::GetSummonerUnit(), Unit::IsSummon(), Unit::Kill(), CreatureAI::me, and Unit::ToTempSummon().
Member Data Documentation
checkTimer
uint16 npc_vh_void_sentry::npc_vh_void_sentryAI::checkTimer
Definition at line 212 of file boss_zuramat.cpp.
Referenced by npc_vh_void_sentryAI(), and UpdateAI().
pInstance
InstanceScript* npc_vh_void_sentry::npc_vh_void_sentryAI::pInstance
Definition at line 210 of file boss_zuramat.cpp.
Referenced by DoAction(), JustDied(), npc_vh_void_sentryAI(), and SummonedCreatureDespawn().
SummonedGUID
ObjectGuid npc_vh_void_sentry::npc_vh_void_sentryAI::SummonedGUID
Definition at line 211 of file boss_zuramat.cpp.
Referenced by DoAction(), JustDied(), and npc_vh_void_sentryAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/VioletHold/boss_zuramat.cpp