Azerotcore-wotlk: Guild::BankEventLogEntry Class Reference
Guild::BankEventLogEntry Class Reference
Public Member Functions
BankEventLogEntry (uint32 guildId, ObjectGuid::LowType guid, GuildBankEventLogTypes eventType, uint8 tabId, ObjectGuid playerGuid, uint32 itemOrMoney, uint16 itemStackCount, uint8 destTabId)
BankEventLogEntry (uint32 guildId, ObjectGuid::LowType guid, time_t timestamp, uint8 tabId, GuildBankEventLogTypes eventType, ObjectGuid playerGuid, uint32 itemOrMoney, uint16 itemStackCount, uint8 destTabId)
~BankEventLogEntry () override
void SaveToDB (CharacterDatabaseTransaction trans) const override
void WritePacket (WorldPacket &data) const override
Public Member Functions inherited from Guild::LogEntry
LogEntry (uint32 guildId, ObjectGuid::LowType guid)
LogEntry (uint32 guildId, ObjectGuid::LowType guid, time_t timestamp)
virtual ~LogEntry ()
ObjectGuid::LowType GetGUID () const
uint64 GetTimestamp () const
Static Public Member Functions
static bool IsMoneyEvent (GuildBankEventLogTypes eventType)
Private Attributes
GuildBankEventLogTypes m_eventType
uint8 m_bankTabId
ObjectGuid m_playerGuid
uint32 m_itemOrMoney
uint16 m_itemStackCount
uint8 m_destTabId
Additional Inherited Members
Protected Attributes inherited from Guild::LogEntry
uint32 m_guildId
ObjectGuid::LowType m_guid
uint64 m_timestamp
Detailed Description
Definition at line 430 of file Guild.h.
Constructor & Destructor Documentation
BankEventLogEntry() [1/2]
Guild::BankEventLogEntry::BankEventLogEntry (uint32 guildId, ObjectGuid::LowType guid, GuildBankEventLogTypes eventType, uint8 tabId, ObjectGuid playerGuid, uint32 itemOrMoney, uint16 itemStackCount, uint8 destTabId) inline
Definition at line 441 of file Guild.h.
                                                                                                                                                                                                     :
             LogEntry(guildId, guid), m_eventType(eventType), m_bankTabId(tabId), m_playerGuid(playerGuid),
             m_itemOrMoney(itemOrMoney), m_itemStackCount(itemStackCount), m_destTabId(destTabId) { }
BankEventLogEntry() [2/2]
Guild::BankEventLogEntry::BankEventLogEntry (uint32 guildId, ObjectGuid::LowType guid, time_t timestamp, uint8 tabId, GuildBankEventLogTypes eventType, ObjectGuid playerGuid, uint32 itemOrMoney, uint16 itemStackCount, uint8 destTabId) inline
Definition at line 445 of file Guild.h.
                                                                                                                                                                                                                       :
             LogEntry(guildId, guid, timestamp), m_eventType(eventType), m_bankTabId(tabId), m_playerGuid(playerGuid),
             m_itemOrMoney(itemOrMoney), m_itemStackCount(itemStackCount), m_destTabId(destTabId) { }
~BankEventLogEntry()
Guild::BankEventLogEntry::~BankEventLogEntry () inline override
Definition at line 449 of file Guild.h.
 { }
Member Function Documentation
IsMoneyEvent()
static bool Guild::BankEventLogEntry::IsMoneyEvent (GuildBankEventLogTypes eventType) inline static
Definition at line 433 of file Guild.h.
         {
             return
                 eventType == GUILD_BANK_LOG_DEPOSIT_MONEY ||
                 eventType == GUILD_BANK_LOG_WITHDRAW_MONEY ||
                 eventType == GUILD_BANK_LOG_REPAIR_MONEY;
         }
References GUILD_BANK_LOG_DEPOSIT_MONEY, GUILD_BANK_LOG_REPAIR_MONEY, and GUILD_BANK_LOG_WITHDRAW_MONEY.
Referenced by Guild::_LogBankEvent(), and Guild::LoadBankEventLogFromDB().
SaveToDB()
void Guild::BankEventLogEntry::SaveToDB (CharacterDatabaseTransaction trans) const override virtual
Implements Guild::LogEntry.
Definition at line 214 of file Guild.cpp.
 {
     uint8 index = 0;
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_DEL_GUILD_BANK_EVENTLOG);
     stmt->setUInt32(  index, m_guildId);
     stmt->setUInt32(++index, m_guid);
     stmt->setUInt8 (++index, m_bankTabId);
     CharacterDatabase.ExecuteOrAppend(trans, stmt);
     index = 0;
     stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_GUILD_BANK_EVENTLOG);
     stmt->setUInt32(  index, m_guildId);
     stmt->setUInt32(++index, m_guid);
     stmt->setUInt8 (++index, m_bankTabId);
     stmt->setUInt8 (++index, uint8(m_eventType));
     stmt->setUInt32(++index, m_playerGuid.GetCounter());
     stmt->setUInt32(++index, m_itemOrMoney);
     stmt->setUInt16(++index, m_itemStackCount);
     stmt->setUInt8 (++index, m_destTabId);
     stmt->setUInt64(++index, m_timestamp);
     CharacterDatabase.ExecuteOrAppend(trans, stmt);
 }
References CHAR_DEL_GUILD_BANK_EVENTLOG, CHAR_INS_GUILD_BANK_EVENTLOG, CharacterDatabase, PreparedStatementBase::setUInt16(), PreparedStatementBase::setUInt32(), PreparedStatementBase::setUInt64(), and PreparedStatementBase::setUInt8().
WritePacket()
void Guild::BankEventLogEntry::WritePacket (WorldPacket & data) const override virtual
Implements Guild::LogEntry.
Definition at line 238 of file Guild.cpp.
 {
     data << uint8(m_eventType);
     data << m_playerGuid;
     switch(m_eventType)
     {
         case GUILD_BANK_LOG_DEPOSIT_ITEM:
         case GUILD_BANK_LOG_WITHDRAW_ITEM:
             data << uint32(m_itemOrMoney);
             data << uint32(m_itemStackCount);
             break;
         case GUILD_BANK_LOG_MOVE_ITEM:
         case GUILD_BANK_LOG_MOVE_ITEM2:
             data << uint32(m_itemOrMoney);
             data << uint32(m_itemStackCount);
             data << uint8(m_destTabId);
             break;
         default:
             data << uint32(m_itemOrMoney);
     }
     data << uint32(time(nullptr) - m_timestamp);
 }
References GUILD_BANK_LOG_DEPOSIT_ITEM, GUILD_BANK_LOG_MOVE_ITEM, GUILD_BANK_LOG_MOVE_ITEM2, and GUILD_BANK_LOG_WITHDRAW_ITEM.
Member Data Documentation
m_bankTabId
uint8 Guild::BankEventLogEntry::m_bankTabId private
Definition at line 456 of file Guild.h.
m_destTabId
uint8 Guild::BankEventLogEntry::m_destTabId private
Definition at line 460 of file Guild.h.
m_eventType
GuildBankEventLogTypes Guild::BankEventLogEntry::m_eventType private
Definition at line 455 of file Guild.h.
m_itemOrMoney
uint32 Guild::BankEventLogEntry::m_itemOrMoney private
Definition at line 458 of file Guild.h.
m_itemStackCount
uint16 Guild::BankEventLogEntry::m_itemStackCount private
Definition at line 459 of file Guild.h.
m_playerGuid
ObjectGuid Guild::BankEventLogEntry::m_playerGuid private
Definition at line 457 of file Guild.h.
The documentation for this class was generated from the following files:
src/server/game/Guilds/Guild.h
src/server/game/Guilds/Guild.cpp