Azerotcore-wotlk: instance_oculus::instance_oculus_InstanceMapScript Struct Reference
instance_oculus::instance_oculus_InstanceMapScript Struct Reference
Public Member Functions
instance_oculus_InstanceMapScript (Map *pMap)
void Initialize () override
void OnCreatureCreate (Creature *pCreature) override
void OnGameObjectCreate (GameObject *pGo) override
void OnPlayerEnter (Player *player) override
void OnUnitDeath (Unit *unit) override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 type) const override
ObjectGuid GetGuidData (uint32 identifier) const override
std::string GetSaveData () override
void Load (const char *in) override
bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *, uint32) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void CreatureLooted (Creature *, LootType)
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureRemove (Creature *creature) override
void OnGameObjectRemove (GameObject *go) override
ObjectGuid GetObjectGuid (uint32 type) const
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
virtual bool SetBossState (uint32 id, EncounterState state)
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual void ProcessEvent (WorldObject *, uint32)
Public Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
ObjectGuid DragonCageDoorGUID [3]
ObjectGuid EregosCacheGUID
uint32 CentrifugeCount
ObjectGuid uiDrakosGUID
ObjectGuid uiVarosGUID
ObjectGuid uiUromGUID
ObjectGuid uiEregosGUID
bool bAmberVoid
bool bEmeraldVoid
bool bRubyVoid
Public Attributes inherited from InstanceScript
Map * instance
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Definition at line 35 of file instance_oculus.cpp.
Constructor & Destructor Documentation
instance_oculus_InstanceMapScript()
instance_oculus::instance_oculus_InstanceMapScript::instance_oculus_InstanceMapScript (Map * pMap) inline
Definition at line 37 of file instance_oculus.cpp.
 : InstanceScript(pMap) { Initialize(); }
References Initialize().
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_oculus::instance_oculus_InstanceMapScript::CheckAchievementCriteriaMeet (uint32 criteria_id, Player const * source, Unit const * , uint32) inline override virtual
Reimplemented from InstanceScript.
Definition at line 270 of file instance_oculus.cpp.
         {
             switch(criteria_id)
             {
                 case CRITERIA_EXPERIENCED_AMBER:
                     if( source )
                         if( Unit* drake = source->GetVehicleBase() )
                             if( drake->GetEntry() == NPC_AMBER_DRAKE )
                                 return true;
                     break;
                 case CRITERIA_EXPERIENCED_EMERALD:
                     if( source )
                         if( Unit* drake = source->GetVehicleBase() )
                             if( drake->GetEntry() == NPC_EMERALD_DRAKE )
                                 return true;
                     break;
                 case CRITERIA_EXPERIENCED_RUBY:
                     if( source )
                         if( Unit* drake = source->GetVehicleBase() )
                             if( drake->GetEntry() == NPC_RUBY_DRAKE )
                                 return true;
                     break;
                 case CRITERIA_AMBER_VOID:
                     return bAmberVoid;
                 case CRITERIA_EMERALD_VOID:
                     return bEmeraldVoid;
                 case CRITERIA_RUBY_VOID:
                     return bRubyVoid;
             }
             return false;
         }
References bAmberVoid, bEmeraldVoid, bRubyVoid, CRITERIA_AMBER_VOID, CRITERIA_EMERALD_VOID, CRITERIA_EXPERIENCED_AMBER, CRITERIA_EXPERIENCED_EMERALD, CRITERIA_EXPERIENCED_RUBY, CRITERIA_RUBY_VOID, Unit::GetVehicleBase(), NPC_AMBER_DRAKE, NPC_EMERALD_DRAKE, and NPC_RUBY_DRAKE.
GetData()
uint32 instance_oculus::instance_oculus_InstanceMapScript::GetData (uint32 type) const inline override virtual
Reimplemented from ZoneScript.
Definition at line 194 of file instance_oculus.cpp.
         {
             switch( type )
             {
                 case DATA_DRAKOS:
                 case DATA_VAROS:
                 case DATA_UROM:
                 case DATA_EREGOS:
                     return m_auiEncounter[type];
                 case DATA_CC_COUNT:
                     return CentrifugeCount;
             }
             return 0;
         }
References CentrifugeCount, DATA_CC_COUNT, DATA_DRAKOS, DATA_EREGOS, DATA_UROM, DATA_VAROS, and m_auiEncounter.
GetGuidData()
ObjectGuid instance_oculus::instance_oculus_InstanceMapScript::GetGuidData (uint32 identifier) const inline override virtual
Reimplemented from InstanceScript.
Definition at line 210 of file instance_oculus.cpp.
         {
             switch( identifier )
             {
                 case DATA_DRAKOS:
                     return uiDrakosGUID;
                 case DATA_VAROS:
                     return uiVarosGUID;
                 case DATA_UROM:
                     return uiUromGUID;
                 case DATA_EREGOS:
                     return uiEregosGUID;
                 case DATA_DCD_1:
                 case DATA_DCD_2:
                 case DATA_DCD_3:
                     return DragonCageDoorGUID[identifier - 100];
             }
             return ObjectGuid::Empty;
         }
References DATA_DCD_1, DATA_DCD_2, DATA_DCD_3, DATA_DRAKOS, DATA_EREGOS, DATA_UROM, DATA_VAROS, DragonCageDoorGUID, ObjectGuid::Empty, uiDrakosGUID, uiEregosGUID, uiUromGUID, and uiVarosGUID.
GetSaveData()
std::string instance_oculus::instance_oculus_InstanceMapScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
Definition at line 231 of file instance_oculus.cpp.
         {
             OUT_SAVE_INST_DATA;
             std::ostringstream saveStream;
             saveStream << "T O " << m_auiEncounter[0] << ' ' << m_auiEncounter[1] << ' ' << m_auiEncounter[2] << ' ' << m_auiEncounter[3] << ' ' << CentrifugeCount;
             OUT_SAVE_INST_DATA_COMPLETE;
             return saveStream.str();
         }
References CentrifugeCount, m_auiEncounter, OUT_SAVE_INST_DATA, and OUT_SAVE_INST_DATA_COMPLETE.
Initialize()
void instance_oculus::instance_oculus_InstanceMapScript::Initialize (void) inline override virtual
Reimplemented from InstanceScript.
Definition at line 53 of file instance_oculus.cpp.
         {
             CentrifugeCount = 0;
             bAmberVoid = false;
             bEmeraldVoid = false;
             bRubyVoid = false;
             memset(&m_auiEncounter, 0, sizeof(m_auiEncounter));
         }
References bAmberVoid, bEmeraldVoid, bRubyVoid, CentrifugeCount, and m_auiEncounter.
Referenced by instance_oculus_InstanceMapScript().
Load()
void instance_oculus::instance_oculus_InstanceMapScript::Load (const char * in) inline override virtual
Reimplemented from InstanceScript.
Definition at line 242 of file instance_oculus.cpp.
         {
             if( !in )
             {
                 OUT_LOAD_INST_DATA_FAIL;
                 return;
             }
             OUT_LOAD_INST_DATA(in);
             char dataHead1, dataHead2;
             std::istringstream loadStream(in);
             loadStream >> dataHead1 >> dataHead2;
             if( dataHead1 == 'T' && dataHead2 == 'O' )
             {
                 loadStream >> m_auiEncounter[0] >> m_auiEncounter[1] >> m_auiEncounter[2] >> m_auiEncounter[3] >> CentrifugeCount;
                 for( uint8 i = 0; i < MAX_ENCOUNTER; ++i )
                     if( m_auiEncounter[i] == IN_PROGRESS )
                         m_auiEncounter[i] = NOT_STARTED;
             }
             else
                 OUT_LOAD_INST_DATA_FAIL;
             OUT_LOAD_INST_DATA_COMPLETE;
         }
References CentrifugeCount, IN_PROGRESS, m_auiEncounter, MAX_ENCOUNTER, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_oculus::instance_oculus_InstanceMapScript::OnCreatureCreate (Creature * pCreature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 63 of file instance_oculus.cpp.
         {
             switch( pCreature->GetEntry() )
             {
                 case NPC_DRAKOS:
                     uiDrakosGUID = pCreature->GetGUID();
                     break;
                 case NPC_VAROS:
                     uiVarosGUID = pCreature->GetGUID();
                     break;
                 case NPC_UROM:
                     uiUromGUID = pCreature->GetGUID();
                     break;
                 case NPC_EREGOS:
                     uiEregosGUID = pCreature->GetGUID();
                     break;
             }
         }
References Object::GetEntry(), Object::GetGUID(), NPC_DRAKOS, NPC_EREGOS, NPC_UROM, NPC_VAROS, uiDrakosGUID, uiEregosGUID, uiUromGUID, and uiVarosGUID.
OnGameObjectCreate()
void instance_oculus::instance_oculus_InstanceMapScript::OnGameObjectCreate (GameObject * pGo) inline override virtual
Reimplemented from InstanceScript.
Definition at line 82 of file instance_oculus.cpp.
         {
             switch( pGo->GetEntry() )
             {
                 case GO_DRAGON_CAGE_DOOR:
                     for( uint8 i = 0; i < 3; ++i )
                     {
                         if( DragonCageDoorGUID[i] )
                             continue;
                         DragonCageDoorGUID[i] = pGo->GetGUID();
                         break;
                     }
                     if( m_auiEncounter[DATA_DRAKOS] == DONE )
                         if( pGo->GetGoState() != GO_STATE_ACTIVE )
{
                             pGo->SetLootState(GO_READY);
                             pGo->UseDoorOrButton(0, false);
                         }
                     break;
                 case GO_CACHE_OF_EREGOS:
                 case GO_CACHE_OF_EREGOS_HERO:
                     EregosCacheGUID = pGo->GetGUID();
                     break;
             }
         }
References DATA_DRAKOS, DONE, DragonCageDoorGUID, EregosCacheGUID, Object::GetEntry(), GameObject::GetGoState(), Object::GetGUID(), GO_CACHE_OF_EREGOS, GO_CACHE_OF_EREGOS_HERO, GO_DRAGON_CAGE_DOOR, GO_READY, GO_STATE_ACTIVE, m_auiEncounter, GameObject::SetLootState(), and GameObject::UseDoorOrButton().
OnPlayerEnter()
void instance_oculus::instance_oculus_InstanceMapScript::OnPlayerEnter (Player * player) inline override virtual
Reimplemented from InstanceScript.
Definition at line 109 of file instance_oculus.cpp.
         {
             if (m_auiEncounter[DATA_DRAKOS] == DONE && m_auiEncounter[DATA_VAROS] != DONE)
             {
                 player->SendUpdateWorldState(WORLD_STATE_CENTRIFUGE_CONSTRUCT_SHOW, 1);
                 player->SendUpdateWorldState(WORLD_STATE_CENTRIFUGE_CONSTRUCT_AMOUNT, 10 - CentrifugeCount);
             }
             else
             {
                 player->SendUpdateWorldState(WORLD_STATE_CENTRIFUGE_CONSTRUCT_SHOW, 0);
                 player->SendUpdateWorldState(WORLD_STATE_CENTRIFUGE_CONSTRUCT_AMOUNT, 0);
             }
         }
References CentrifugeCount, DATA_DRAKOS, DATA_VAROS, DONE, m_auiEncounter, Player::SendUpdateWorldState(), WORLD_STATE_CENTRIFUGE_CONSTRUCT_AMOUNT, and WORLD_STATE_CENTRIFUGE_CONSTRUCT_SHOW.
OnUnitDeath()
void instance_oculus::instance_oculus_InstanceMapScript::OnUnitDeath (Unit * unit) inline override virtual
Reimplemented from ZoneScript.
Definition at line 123 of file instance_oculus.cpp.
         {
             if (unit->GetEntry() == NPC_CENTRIFUGE_CONSTRUCT)
                 SetData(DATA_CC_COUNT, DONE);
         }
References DATA_CC_COUNT, DONE, Object::GetEntry(), NPC_CENTRIFUGE_CONSTRUCT, and SetData().
SetData()
void instance_oculus::instance_oculus_InstanceMapScript::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from ZoneScript.
Definition at line 129 of file instance_oculus.cpp.
         {
             switch( type )
             {
                 case DATA_DRAKOS:
                     m_auiEncounter[DATA_DRAKOS] = data;
                     if( data == DONE )
                     {
                         DoUpdateWorldState(WORLD_STATE_CENTRIFUGE_CONSTRUCT_SHOW, 1);
                         DoUpdateWorldState(WORLD_STATE_CENTRIFUGE_CONSTRUCT_AMOUNT, 10 - CentrifugeCount);
                         if (instance->IsHeroic())
                             DoStartTimedAchievement(ACHIEVEMENT_TIMED_TYPE_EVENT, ACHIEV_MAKE_IT_COUNT_TIMED_EVENT);
                     }
                     break;
                 case DATA_VAROS:
                     m_auiEncounter[DATA_VAROS] = data;
                     if( data == DONE )
                     {
                         DoUpdateWorldState(WORLD_STATE_CENTRIFUGE_CONSTRUCT_SHOW, 0);
                         if( Creature* urom = instance->GetCreature(uiUromGUID) )
                             urom->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                     }
                     break;
                 case DATA_UROM:
                     m_auiEncounter[DATA_UROM] = data;
                     if( data == DONE )
                         if( Creature* eregos = instance->GetCreature(uiEregosGUID) )
                             eregos->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                     break;
                 case DATA_EREGOS:
                     m_auiEncounter[DATA_EREGOS] = data;
                     if (data == DONE)
                         DoRespawnGameObject(EregosCacheGUID, 7 * DAY);
                     break;
                 case DATA_CC_COUNT:
                     if( CentrifugeCount < 10 )
                     {
                         ++CentrifugeCount;
                         DoUpdateWorldState(WORLD_STATE_CENTRIFUGE_CONSTRUCT_AMOUNT, 10 - CentrifugeCount);
                     }
                     if( CentrifugeCount >= 10 )
                         if( Creature* varos = instance->GetCreature(uiVarosGUID) )
{
                             varos->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                             varos->InterruptNonMeleeSpells(false);
                             varos->RemoveAura(50053);
                         }
                     break;
                 case DATA_AMBER_VOID:
                     bAmberVoid = !!data;
                     break;
                 case DATA_EMERALD_VOID:
                     bEmeraldVoid = !!data;
                     break;
                 case DATA_RUBY_VOID:
                     bRubyVoid = !!data;
                     break;
             }
             if( data == DONE )
                 SaveToDB();
         }
References ACHIEV_MAKE_IT_COUNT_TIMED_EVENT, ACHIEVEMENT_TIMED_TYPE_EVENT, bAmberVoid, bEmeraldVoid, bRubyVoid, CentrifugeCount, DATA_AMBER_VOID, DATA_CC_COUNT, DATA_DRAKOS, DATA_EMERALD_VOID, DATA_EREGOS, DATA_RUBY_VOID, DATA_UROM, DATA_VAROS, DAY, DONE, InstanceScript::DoRespawnGameObject(), InstanceScript::DoStartTimedAchievement(), InstanceScript::DoUpdateWorldState(), EregosCacheGUID, Map::GetCreature(), InstanceScript::instance, Map::IsHeroic(), m_auiEncounter, InstanceScript::SaveToDB(), uiEregosGUID, uiUromGUID, uiVarosGUID, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, WORLD_STATE_CENTRIFUGE_CONSTRUCT_AMOUNT, and WORLD_STATE_CENTRIFUGE_CONSTRUCT_SHOW.
Referenced by OnUnitDeath().
Member Data Documentation
bAmberVoid
bool instance_oculus::instance_oculus_InstanceMapScript::bAmberVoid
Definition at line 49 of file instance_oculus.cpp.
Referenced by CheckAchievementCriteriaMeet(), Initialize(), and SetData().
bEmeraldVoid
bool instance_oculus::instance_oculus_InstanceMapScript::bEmeraldVoid
Definition at line 50 of file instance_oculus.cpp.
Referenced by CheckAchievementCriteriaMeet(), Initialize(), and SetData().
bRubyVoid
bool instance_oculus::instance_oculus_InstanceMapScript::bRubyVoid
Definition at line 51 of file instance_oculus.cpp.
Referenced by CheckAchievementCriteriaMeet(), Initialize(), and SetData().
CentrifugeCount
uint32 instance_oculus::instance_oculus_InstanceMapScript::CentrifugeCount
Definition at line 42 of file instance_oculus.cpp.
Referenced by GetData(), GetSaveData(), Initialize(), Load(), OnPlayerEnter(), and SetData().
DragonCageDoorGUID
ObjectGuid instance_oculus::instance_oculus_InstanceMapScript::DragonCageDoorGUID[3]
Definition at line 40 of file instance_oculus.cpp.
Referenced by GetGuidData(), and OnGameObjectCreate().
EregosCacheGUID
ObjectGuid instance_oculus::instance_oculus_InstanceMapScript::EregosCacheGUID
Definition at line 41 of file instance_oculus.cpp.
Referenced by OnGameObjectCreate(), and SetData().
m_auiEncounter
uint32 instance_oculus::instance_oculus_InstanceMapScript::m_auiEncounter[MAX_ENCOUNTER]
Definition at line 39 of file instance_oculus.cpp.
Referenced by GetData(), GetSaveData(), Initialize(), Load(), OnGameObjectCreate(), OnPlayerEnter(), and SetData().
uiDrakosGUID
ObjectGuid instance_oculus::instance_oculus_InstanceMapScript::uiDrakosGUID
Definition at line 44 of file instance_oculus.cpp.
Referenced by GetGuidData(), and OnCreatureCreate().
uiEregosGUID
ObjectGuid instance_oculus::instance_oculus_InstanceMapScript::uiEregosGUID
Definition at line 47 of file instance_oculus.cpp.
Referenced by GetGuidData(), OnCreatureCreate(), and SetData().
uiUromGUID
ObjectGuid instance_oculus::instance_oculus_InstanceMapScript::uiUromGUID
Definition at line 46 of file instance_oculus.cpp.
Referenced by GetGuidData(), OnCreatureCreate(), and SetData().
uiVarosGUID
ObjectGuid instance_oculus::instance_oculus_InstanceMapScript::uiVarosGUID
Definition at line 45 of file instance_oculus.cpp.
Referenced by GetGuidData(), OnCreatureCreate(), and SetData().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Nexus/Oculus/instance_oculus.cpp