Azerotcore-wotlk: boss_yoggsaron_brain::boss_yoggsaron_brainAI Struct Reference
boss_yoggsaron_brain::boss_yoggsaron_brainAI Struct Reference
Public Member Functions
boss_yoggsaron_brainAI (Creature *pCreature)
void Reset () override
void JustSummoned (Creature *cr) override
void PrepareChamberIllusion ()
void PrepareIceCrownIllusion ()
void PrepareStormwindIllusion ()
void DoAction (int32 param) override
uint32 GetData (uint32 param) const override
void DamageTaken (Unit *who, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
bool _brainDamaged
uint8 _tentacleCount
uint8 _activeIllusion
uint32 _induceTimer
SummonList summons
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1219 of file boss_yoggsaron.cpp.
Constructor & Destructor Documentation
boss_yoggsaron_brainAI()
boss_yoggsaron_brain::boss_yoggsaron_brainAI::boss_yoggsaron_brainAI (Creature * pCreature) inline
Definition at line 1221 of file boss_yoggsaron.cpp.
                                                     : NullCreatureAI(pCreature), summons(pCreature)
         {
             me->SetDisableGravity(true);
             _tentacleCount = 0;
             _activeIllusion = 0;
             _induceTimer = 0;
             _brainDamaged = false;
             me->SetRegeneratingHealth(false);
         }
References _activeIllusion, _brainDamaged, _induceTimer, _tentacleCount, CreatureAI::me, Creature::SetDisableGravity(), and Creature::SetRegeneratingHealth().
Member Function Documentation
DamageTaken()
void boss_yoggsaron_brain::boss_yoggsaron_brainAI::DamageTaken (Unit * who, uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from UnitAI.
Definition at line 1410 of file boss_yoggsaron.cpp.
         {
             if (_tentacleCount < 7) // if all tentacles aren't killed
             {
                 damage = 0;
                 if (who)
                     Unit::Kill(who, who);
                 return;
             }
             if (!_brainDamaged)
             {
                 // START PHASE 3
                 if (me->HealthBelowPctDamaged(30, damage))
                 {
                     me->SetRegeneratingHealth(false);
                     _EnterEvadeMode();
                     _brainDamaged = true;
                     me->CastSpell(me, SPELL_BRAIN_HURT_VISUAL, true);
                     if (me->GetInstanceScript())
                         if(Creature* sara = ObjectAccessor::GetCreature(*me, me->GetInstanceScript()->GetGuidData(NPC_SARA)))
                             sara->AI()->DoAction(ACTION_BRAIN_DAMAGED);
                 }
             }
         }
References _brainDamaged, CreatureAI::_EnterEvadeMode(), _tentacleCount, ACTION_BRAIN_DAMAGED, Unit::CastSpell(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), Unit::HealthBelowPctDamaged(), Unit::Kill(), CreatureAI::me, NPC_SARA, Creature::SetRegeneratingHealth(), and SPELL_BRAIN_HURT_VISUAL.
DoAction()
void boss_yoggsaron_brain::boss_yoggsaron_brainAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 1350 of file boss_yoggsaron.cpp.
         {
             if (param == ACTION_DESPAWN_ADDS)
             {
                 summons.DespawnAll();
                 return;
             }
             else if (param == ACTION_INFLUENCE_TENTACLE_DIED)
             {
                 _tentacleCount++;
                 if (_tentacleCount >= 7 /*TENTACLES COUNT*/)
                 {
                     // Stun
                     if (me->GetInstanceScript())
                         if(Creature* sara = ObjectAccessor::GetCreature(*me, me->GetInstanceScript()->GetGuidData(NPC_SARA)))
                             sara->AI()->DoAction(MINUTE * IN_MILLISECONDS - std::min((uint32)MINUTE * IN_MILLISECONDS, _induceTimer));
                     _induceTimer = 0;
                     summons.DespawnEntry(NPC_LAUGHING_SKULL);
                     if (GameObject* go = me->FindNearestGameObject(GO_CHAMBER_ILLUSION_DOORS + _activeIllusion, 150.0f))
                         go->SetGoState(GO_STATE_ACTIVE);
                 }
                 return;
             }
             else if (param == ACTION_REMOVE_STUN)
                 return;
             summons.DespawnAll();
             switch(param)
             {
                 case ACTION_ILLUSION_STORMWIND:
                     PrepareStormwindIllusion();
                     break;
                 case ACTION_ILLUSION_DRAGONS:
                     PrepareChamberIllusion();
                     break;
                 case ACTION_ILLUSION_ICECROWN:
                     PrepareIceCrownIllusion();
                     break;
             }
             for (uint32 i = GO_CHAMBER_ILLUSION_DOORS; i <= GO_STORMWIND_ILLUSION_DOORS; ++i)
                 if (GameObject* go = me->FindNearestGameObject(i, 150.0f))
                     go->SetGoState(GO_STATE_READY);
             _activeIllusion = param - 1;
             _tentacleCount = 0;
             _induceTimer = 1;
             me->CastSpell(me, SPELL_INDUCE_MADNESS, false);
         }
References _activeIllusion, _induceTimer, _tentacleCount, ACTION_DESPAWN_ADDS, ACTION_ILLUSION_DRAGONS, ACTION_ILLUSION_ICECROWN, ACTION_ILLUSION_STORMWIND, ACTION_INFLUENCE_TENTACLE_DIED, ACTION_REMOVE_STUN, Unit::CastSpell(), SummonList::DespawnAll(), SummonList::DespawnEntry(), WorldObject::FindNearestGameObject(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), WorldObject::GetInstanceScript(), GO_CHAMBER_ILLUSION_DOORS, GO_STATE_ACTIVE, GO_STATE_READY, GO_STORMWIND_ILLUSION_DOORS, IN_MILLISECONDS, CreatureAI::me, MINUTE, NPC_LAUGHING_SKULL, NPC_SARA, PrepareChamberIllusion(), PrepareIceCrownIllusion(), PrepareStormwindIllusion(), SPELL_INDUCE_MADNESS, and summons.
GetData()
uint32 boss_yoggsaron_brain::boss_yoggsaron_brainAI::GetData (uint32 param) const inline override virtual
Reimplemented from UnitAI.
Definition at line 1402 of file boss_yoggsaron.cpp.
         {
             if (param == DATA_GET_CURRENT_ILLUSION)
                 return _activeIllusion + 1;
             return 0;
         }
References _activeIllusion, and DATA_GET_CURRENT_ILLUSION.
JustSummoned()
void boss_yoggsaron_brain::boss_yoggsaron_brainAI::JustSummoned (Creature * cr) inline override virtual
Reimplemented from CreatureAI.
Definition at line 1238 of file boss_yoggsaron.cpp.
         {
             if (cr->GetEntry() == NPC_INFLUENCE_TENTACLE)
             {
                 // Dragons Illusion
                 if (cr->GetPositionX() > 2000.0f && cr->GetPositionX() < 2150.0f)
                     cr->UpdateEntry(urand(NPC_CONSORT_FIRST, NPC_CONSORT_LAST));
                 // Icecrown Illusion
                 else if (cr->GetPositionY() > -150.0f && cr->GetPositionY() < -90.0f)
                 {
                     cr->SetStandState(UNIT_STAND_STATE_KNEEL);
                     cr->UpdateEntry(NPC_DEATHSWORN_ZEALOT);
                 }
                 // Stormwind Illusion
                 else
                     cr->UpdateEntry(NPC_SUIT_OF_ARMOR);
             }
             else if (cr->GetEntry() == NPC_LICH_KING)
                 cr->CastSpell(cr, SPELL_DEATHGRASP, false);
             summons.Summon(cr);
         }
References Unit::CastSpell(), Object::GetEntry(), Position::GetPositionX(), Position::GetPositionY(), NPC_CONSORT_FIRST, NPC_CONSORT_LAST, NPC_DEATHSWORN_ZEALOT, NPC_INFLUENCE_TENTACLE, NPC_LICH_KING, NPC_SUIT_OF_ARMOR, Unit::SetStandState(), SPELL_DEATHGRASP, SummonList::Summon(), summons, UNIT_STAND_STATE_KNEEL, Creature::UpdateEntry(), and urand().
PrepareChamberIllusion()
void boss_yoggsaron_brain::boss_yoggsaron_brainAI::PrepareChamberIllusion () inline
Definition at line 1261 of file boss_yoggsaron.cpp.
         {
             me->SummonCreature(NPC_INFLUENCE_TENTACLE, 2126.13f, -65.488f, 239.721f, 1.99171f);
             me->SummonCreature(NPC_INFLUENCE_TENTACLE, 2141.05f, -50.5146f, 239.751f, 2.72998f);
             me->SummonCreature(NPC_INFLUENCE_TENTACLE, 2148.83f, -23.9568f, 239.721f, 3.04807f);
             me->SummonCreature(NPC_INFLUENCE_TENTACLE, 2064.39f, -42.0691f, 239.719f, 0.0949586f);
             me->SummonCreature(NPC_INFLUENCE_TENTACLE, 2064.29f, -7.13128f, 239.756f, 5.96974f);
             me->SummonCreature(NPC_INFLUENCE_TENTACLE, 2117.31f, 14.897f, 239.731f, 4.32041f);
             me->SummonCreature(NPC_INFLUENCE_TENTACLE, 2136.7f, 2.43262f, 239.72f, 3.90023f);
             // Laughing Skulls
             if (urand(0, 1))
                 me->SummonCreature(NPC_LAUGHING_SKULL, 2139.13f, -59.0848f, 239.728f, 2.2974f);
             else
                 me->SummonCreature(NPC_LAUGHING_SKULL, 2083, -25.66f, 244, 0);
             if (urand(0, 1))
                 me->SummonCreature(NPC_LAUGHING_SKULL, 2066.67f, -59.8984f, 239.72f, 0.718747f);
             else
                 me->SummonCreature(NPC_LAUGHING_SKULL, 2126.22f, -25.86f, 244, 0);
             me->SummonCreature(NPC_LAUGHING_SKULL, 2133.09f, 15.341f, 239.72f, 4.0724f);
             me->SummonCreature(NPC_LAUGHING_SKULL, 2065.83f, 12.3772f, 239.792f, 5.49789f);
             // Aspects
             me->SummonCreature(NPC_ALEXTRASZA, 2091.92f, -25.8f, 242.647f, 0);
             me->SummonCreature(NPC_YSERA, 2116, -25.8f, 242.647f, 3.14f);
             me->SummonCreature(NPC_NELTHARION, 2103.6f, -35.8f, 242.64f, 1.5f);
             me->SummonCreature(NPC_MALYGOS, 2103.6f, -15.8f, 242.64f, 4.7f);
         }
References CreatureAI::me, NPC_ALEXTRASZA, NPC_INFLUENCE_TENTACLE, NPC_LAUGHING_SKULL, NPC_MALYGOS, NPC_NELTHARION, NPC_YSERA, WorldObject::SummonCreature(), and urand().
Referenced by DoAction().
PrepareIceCrownIllusion()
void boss_yoggsaron_brain::boss_yoggsaron_brainAI::PrepareIceCrownIllusion () inline
Definition at line 1291 of file boss_yoggsaron.cpp.
         {
             // Laughing Skulls
             me->SummonCreature(NPC_LAUGHING_SKULL, 1931.12f, -92.702f, 239.991f, 5.2819f);
             if (urand(0, 1))
                 me->SummonCreature(NPC_LAUGHING_SKULL, 1969.88f, -147.729f, 239.991f, 2.37593f);
             else
                 me->SummonCreature(NPC_LAUGHING_SKULL, 1878, -93.3f, 240, 0);
             if (urand(0, 1))
                 me->SummonCreature(NPC_LAUGHING_SKULL, 1950.78f, -167.902f, 239.991f, 2.34844f);
             else
                 me->SummonCreature(NPC_LAUGHING_SKULL, 1938.45f, -116.5f, 240, 0);
             if (urand(0, 1))
                 me->SummonCreature(NPC_LAUGHING_SKULL, 1896.45f, -141.469f, 239.991f, 6.12227f);
             else
                 me->SummonCreature(NPC_LAUGHING_SKULL, 1921, -158, 240, 0);
             // Influence
             me->SummonCreature(NPC_INFLUENCE_TENTACLE, 1958.29f, -128.65f, 239.99f, 3.61293f);
             me->SummonCreature(NPC_INFLUENCE_TENTACLE, 1957.78f, -134.368f, 239.99f, 3.35375f);
             me->SummonCreature(NPC_INFLUENCE_TENTACLE, 1953.04f, -137.843f, 239.99f, 3.55796f);
             me->SummonCreature(NPC_INFLUENCE_TENTACLE, 1900.31f, -93.5241f, 239.99f, 4.50043f);
             me->SummonCreature(NPC_INFLUENCE_TENTACLE, 1895.03f, -98.0773f, 239.99f, 4.88135f);
             me->SummonCreature(NPC_INFLUENCE_TENTACLE, 1895.19f, -104.587f, 239.99f, 5.02271f);
             me->SummonCreature(NPC_INFLUENCE_TENTACLE, 1923.31f, -125.98f, 240, 4.2f);
             // Others
             me->SummonCreature(NPC_LICH_KING, 1906.98f, -153, 240, 4.2f);
             me->SummonCreature(NPC_IMMOLATED_CHAMPION, 1902.03f, -161.7f, 240, 1.07f);
         }
References CreatureAI::me, NPC_IMMOLATED_CHAMPION, NPC_INFLUENCE_TENTACLE, NPC_LAUGHING_SKULL, NPC_LICH_KING, WorldObject::SummonCreature(), and urand().
Referenced by DoAction().
PrepareStormwindIllusion()
void boss_yoggsaron_brain::boss_yoggsaron_brainAI::PrepareStormwindIllusion () inline
Definition at line 1322 of file boss_yoggsaron.cpp.
         {
             // Laughing Skulls
             if (urand(0, 1))
                 me->SummonCreature(NPC_LAUGHING_SKULL, 1916.36f, 28.05f, 239.666f, 1.30238f);
             else
                 me->SummonCreature(NPC_LAUGHING_SKULL, 1966.7f, 57.8f, 239.66f, 0);
             if (urand(0, 1))
                 me->SummonCreature(NPC_LAUGHING_SKULL, 1902, 75.1362f, 239.666f, 6.06189f);
             else
                 me->SummonCreature(NPC_LAUGHING_SKULL, 1933, 91, 240, 0);
             me->SummonCreature(NPC_LAUGHING_SKULL, 1914.42f, 90.8465f, 239.666f, 5.25294f);
             me->SummonCreature(NPC_LAUGHING_SKULL, 1963.68f, 89.7549f, 239.667f, 3.70571f);
             // Influence
             me->SummonCreature(NPC_INFLUENCE_TENTACLE, 1931.41f, 39.0711f, 239.66f, 1.82467f);
             me->SummonCreature(NPC_INFLUENCE_TENTACLE, 1908.67f, 45.5867f, 239.666f, 0.72119f);
             me->SummonCreature(NPC_INFLUENCE_TENTACLE, 1897.68f, 66.1274f, 239.666f, 6.27395f);
             me->SummonCreature(NPC_INFLUENCE_TENTACLE, 1950.73f, 49.3446f, 239.666f, 2.63756f);
             me->SummonCreature(NPC_INFLUENCE_TENTACLE, 1923.16f, 97.5586f, 239.666f, 4.74635f);
             me->SummonCreature(NPC_INFLUENCE_TENTACLE, 1956.16f, 72.1403f, 239.666f, 3.19518f);
             me->SummonCreature(NPC_INFLUENCE_TENTACLE, 1944.81f, 92.3154f, 239.666f, 4.03556f);
             // Others
             me->SummonCreature(NPC_GARONA, 1928.58f, 65.64f, 242.37f, 2.1f);
             me->SummonCreature(NPC_KING_LLANE, 1925.14f, 71.74f, 242.37f, 5.17f);
         }
References CreatureAI::me, NPC_GARONA, NPC_INFLUENCE_TENTACLE, NPC_KING_LLANE, NPC_LAUGHING_SKULL, WorldObject::SummonCreature(), and urand().
Referenced by DoAction().
Reset()
void boss_yoggsaron_brain::boss_yoggsaron_brainAI::Reset () inline override virtual
Reimplemented from UnitAI.
Definition at line 1237 of file boss_yoggsaron.cpp.
 { }
UpdateAI()
void boss_yoggsaron_brain::boss_yoggsaron_brainAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 1437 of file boss_yoggsaron.cpp.
         {
             if (_induceTimer)
                 _induceTimer += diff;
         }
References _induceTimer.
Member Data Documentation
_activeIllusion
uint8 boss_yoggsaron_brain::boss_yoggsaron_brainAI::_activeIllusion
Definition at line 1233 of file boss_yoggsaron.cpp.
Referenced by boss_yoggsaron_brainAI(), DoAction(), and GetData().
_brainDamaged
bool boss_yoggsaron_brain::boss_yoggsaron_brainAI::_brainDamaged
Definition at line 1231 of file boss_yoggsaron.cpp.
Referenced by boss_yoggsaron_brainAI(), and DamageTaken().
_induceTimer
uint32 boss_yoggsaron_brain::boss_yoggsaron_brainAI::_induceTimer
Definition at line 1234 of file boss_yoggsaron.cpp.
Referenced by boss_yoggsaron_brainAI(), DoAction(), and UpdateAI().
_tentacleCount
uint8 boss_yoggsaron_brain::boss_yoggsaron_brainAI::_tentacleCount
Definition at line 1232 of file boss_yoggsaron.cpp.
Referenced by boss_yoggsaron_brainAI(), DamageTaken(), and DoAction().
summons
SummonList boss_yoggsaron_brain::boss_yoggsaron_brainAI::summons
Definition at line 1235 of file boss_yoggsaron.cpp.
Referenced by DoAction(), and JustSummoned().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_yoggsaron.cpp