Azerotcore-wotlk: deps/argon2/argon2/thread.h File Reference
thread.h File Reference
#include <pthread.h>
Typedefs
typedef void *(* argon2_thread_func_t) (void *)
typedef pthread_t argon2_thread_handle_t
Functions
int argon2_thread_create (argon2_thread_handle_t *handle, argon2_thread_func_t func, void *args)
int argon2_thread_join (argon2_thread_handle_t handle)
void argon2_thread_exit (void)
Typedef Documentation
argon2_thread_func_t
typedef void*(* argon2_thread_func_t) (void *)
Definition at line 39 of file thread.h.
argon2_thread_handle_t
typedef pthread_t argon2_thread_handle_t
Definition at line 40 of file thread.h.
Function Documentation
argon2_thread_create()
int argon2_thread_create (argon2_thread_handle_t * handle, argon2_thread_func_t func, void * args)
Definition at line 25 of file thread.c.
{
     if (NULL == handle || func == NULL) {
         return -1;
     }
 #if defined(_WIN32)
     *handle = _beginthreadex(NULL, 0, func, args, 0, NULL);
     return *handle != 0 ? 0 : -1;
 #else
     return pthread_create(handle, NULL, func, args);
 #endif
 }
References NULL.
Referenced by fill_memory_blocks_mt().
argon2_thread_exit()
void argon2_thread_exit (void)
Definition at line 49 of file thread.c.
{
 #if defined(_WIN32)
     _endthreadex(0);
 #else
     pthread_exit(NULL);
 #endif
 }
References NULL.
Referenced by fill_segment_thr().
argon2_thread_join()
int argon2_thread_join (argon2_thread_handle_t handle)
Definition at line 38 of file thread.c.
{
 #if defined(_WIN32)
     if (WaitForSingleObject((HANDLE)handle, INFINITE) == WAIT_OBJECT_0) {
         return CloseHandle((HANDLE)handle) != 0 ? 0 : -1;
     }
     return -1;
 #else
     return pthread_join(handle, NULL);
 #endif
 }
References HANDLE, and NULL.
Referenced by fill_memory_blocks_mt().