Azerotcore-wotlk: boss_servant_quarters::boss_servant_quartersAI Struct Reference
boss_servant_quarters::boss_servant_quartersAI Struct Reference
Public Member Functions
boss_servant_quartersAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *) override
void JustDied (Unit *) override
void MovementInform (uint32 type, uint32 point) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
EventMap _events2
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 56 of file boss_servant_quarters.cpp.
Constructor & Destructor Documentation
boss_servant_quartersAI()
boss_servant_quarters::boss_servant_quartersAI::boss_servant_quartersAI (Creature * creature) inline
Definition at line 58 of file boss_servant_quarters.cpp.
 : BossAI(creature, DATA_SERVANT_QUARTERS) { }
Member Function Documentation
EnterCombat()
void boss_servant_quarters::boss_servant_quartersAI::EnterCombat (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 75 of file boss_servant_quarters.cpp.
         {
             me->setActive(true);
             if (me->GetEntry() == NPC_HYAKISS_THE_LURKER)
             {
                 events.ScheduleEvent(EVENT_SPELL_ACIDIC_FANG, 5000);
                 events.ScheduleEvent(EVENT_SPELL_HYAKISS_WEB, 9000);
             }
             else if (me->GetEntry() == NPC_SHADIKITH_THE_GLIDER)
             {
                 events.ScheduleEvent(EVENT_SPELL_SONIC_BURST, 4000);
                 events.ScheduleEvent(EVENT_SPELL_WING_BUFFET, 7000);
                 events.ScheduleEvent(EVENT_SPELL_DIVE, 10000);
             }
             else // if (me->GetEntry() == NPC_ROKAD_THE_RAVAGER)
             {
                 events.ScheduleEvent(EVENT_SPELL_RAVAGE, 3000);
             }
         }
References EVENT_SPELL_ACIDIC_FANG, EVENT_SPELL_DIVE, EVENT_SPELL_HYAKISS_WEB, EVENT_SPELL_RAVAGE, EVENT_SPELL_SONIC_BURST, EVENT_SPELL_WING_BUFFET, Object::GetEntry(), ScriptedAI::me, NPC_HYAKISS_THE_LURKER, NPC_SHADIKITH_THE_GLIDER, and WorldObject::setActive().
JustDied()
void boss_servant_quarters::boss_servant_quartersAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 95 of file boss_servant_quarters.cpp.
         {
         }
MovementInform()
void boss_servant_quarters::boss_servant_quartersAI::MovementInform (uint32 type, uint32 point) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 99 of file boss_servant_quarters.cpp.
         {
             if (type == POINT_MOTION_TYPE && point == EVENT_CHARGE)
                 events.ScheduleEvent(EVENT_SPELL_FEAR, 0);
         }
References EVENT_CHARGE, EVENT_SPELL_FEAR, and POINT_MOTION_TYPE.
Reset()
void boss_servant_quarters::boss_servant_quartersAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 60 of file boss_servant_quarters.cpp.
         {
             events.Reset();
             me->SetVisible(false);
             me->SetReactState(REACT_PASSIVE);
             me->SetFaction(FACTION_FRIENDLY);
             _events2.Reset();
             _events2.ScheduleEvent(EVENT_CHECK_VISIBILITY, 5000);
             if (me->GetEntry() == NPC_HYAKISS_THE_LURKER)
                 me->CastSpell(me, SPELL_SNEAK, true);
             if (instance->GetData(DATA_SELECTED_RARE) != me->GetEntry())
                 me->DespawnOrUnsummon(1);
         }
References _events2, Unit::CastSpell(), DATA_SELECTED_RARE, Creature::DespawnOrUnsummon(), EVENT_CHECK_VISIBILITY, FACTION_FRIENDLY, ZoneScript::GetData(), Object::GetEntry(), BossAI::instance, ScriptedAI::me, NPC_HYAKISS_THE_LURKER, REACT_PASSIVE, EventMap::Reset(), EventMap::ScheduleEvent(), Unit::SetFaction(), Creature::SetReactState(), Unit::SetVisible(), and SPELL_SNEAK.
UpdateAI()
void boss_servant_quarters::boss_servant_quartersAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 105 of file boss_servant_quarters.cpp.
         {
             _events2.Update(diff);
             switch (_events2.ExecuteEvent())
             {
                 case EVENT_CHECK_VISIBILITY:
                     if (instance->GetBossState(DATA_SERVANT_QUARTERS) == DONE)
                     {
                         me->SetVisible(true);
                         me->SetReactState(REACT_AGGRESSIVE);
                         me->RestoreFaction();
                     }
                     else
                         _events2.ScheduleEvent(EVENT_CHECK_VISIBILITY, 5000);
                     break;
             }
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_SPELL_ACIDIC_FANG:
                     me->CastSpell(me->GetVictim(), SPELL_ACIDIC_FANG, false);
                     events.ScheduleEvent(EVENT_SPELL_ACIDIC_FANG, urand(12000, 18000));
                     break;
                 case EVENT_SPELL_HYAKISS_WEB:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 30.0f))
                         me->CastSpell(target, SPELL_HYAKISS_WEB, false);
                     events.ScheduleEvent(EVENT_SPELL_HYAKISS_WEB, 15000);
                     break;
                 case EVENT_SPELL_SONIC_BURST:
                     me->CastSpell(me, SPELL_SONIC_BURST, false);
                     events.ScheduleEvent(EVENT_SPELL_SONIC_BURST, urand(12000, 18000));
                     break;
                 case EVENT_SPELL_WING_BUFFET:
                     me->CastSpell(me, SPELL_WING_BUFFET, false);
                     events.ScheduleEvent(EVENT_SPELL_WING_BUFFET, urand(12000, 18000));
                     break;
                 case EVENT_SPELL_DIVE:
                     if (Unit* target = SelectTarget(SELECT_TARGET_FARTHEST, 0, FarthestTargetSelector(me, 40.0f, false, true)))
                         me->CastSpell(target, SPELL_DIVE, false);
                     events.ScheduleEvent(EVENT_SPELL_DIVE, 20000);
                     break;
                 case EVENT_SPELL_FEAR:
                     me->CastSpell(me->GetVictim(), SPELL_FEAR, false);
                     break;
                 case EVENT_SPELL_RAVAGE:
                     me->CastSpell(me->GetVictim(), SPELL_RAVAGE, false);
                     events.ScheduleEvent(EVENT_SPELL_RAVAGE, 10500);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References _events2, Unit::CastSpell(), DATA_SERVANT_QUARTERS, diff(), UnitAI::DoMeleeAttackIfReady(), DONE, EVENT_CHECK_VISIBILITY, EVENT_SPELL_ACIDIC_FANG, EVENT_SPELL_DIVE, EVENT_SPELL_FEAR, EVENT_SPELL_HYAKISS_WEB, EVENT_SPELL_RAVAGE, EVENT_SPELL_SONIC_BURST, EVENT_SPELL_WING_BUFFET, EventMap::ExecuteEvent(), InstanceScript::GetBossState(), Unit::GetVictim(), Unit::HasUnitState(), BossAI::instance, ScriptedAI::me, REACT_AGGRESSIVE, Unit::RestoreFaction(), EventMap::ScheduleEvent(), SELECT_TARGET_FARTHEST, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Creature::SetReactState(), Unit::SetVisible(), SPELL_ACIDIC_FANG, SPELL_DIVE, SPELL_FEAR, SPELL_HYAKISS_WEB, SPELL_RAVAGE, SPELL_SONIC_BURST, SPELL_WING_BUFFET, UNIT_STATE_CASTING, EventMap::Update(), CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
_events2
EventMap boss_servant_quarters::boss_servant_quartersAI::_events2 private
Definition at line 166 of file boss_servant_quarters.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/Karazhan/boss_servant_quarters.cpp