Azerotcore-wotlk: brann_bronzebeard Class Reference
brann_bronzebeard Class Reference
Classes
struct brann_bronzebeardAI
Public Member Functions
brann_bronzebeard ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
CreatureAI * GetAI (Creature *creature) const override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 160 of file brann_bronzebeard.cpp.
Constructor & Destructor Documentation
brann_bronzebeard()
brann_bronzebeard::brann_bronzebeard () inline
Definition at line 163 of file brann_bronzebeard.cpp.
 : CreatureScript("brann_bronzebeard") { }
Referenced by AddSC_brann_bronzebeard().
Member Function Documentation
GetAI()
CreatureAI* brann_bronzebeard::GetAI (Creature * creature) const inline override virtual
Reimplemented from CreatureScript.
Definition at line 230 of file brann_bronzebeard.cpp.
     {
         return new brann_bronzebeardAI (creature);
     }
OnGossipHello()
bool brann_bronzebeard::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 165 of file brann_bronzebeard.cpp.
     {
         InstanceScript* pInstance = (creature->GetInstanceScript());
         player->TalkedToCreature(creature->GetEntry(), creature->GetGUID());
         player->PrepareGossipMenu(creature, 0, true);
         if (pInstance)
         {
             uint32 brann = pInstance->GetData(BRANN_BRONZEBEARD);
             switch (brann)
             {
                 case 1:
                     AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ITEM_1, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
                     break;
                 case 2:
                     AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ITEM_2, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
                     break;
                 case 3:
                     AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ITEM_3, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 3);
                     break;
                 case 4:
                     AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ITEM_3, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 4);
                     break;
                 case 5:
                     AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ITEM_4, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 5);
                     break;
                 default:
                     break;
             }
         }
         SendGossipMenuFor(player, TEXT_ID_START, creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), BRANN_BRONZEBEARD, ZoneScript::GetData(), Object::GetEntry(), Object::GetGUID(), WorldObject::GetInstanceScript(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_1, GOSSIP_ITEM_2, GOSSIP_ITEM_3, GOSSIP_ITEM_4, GOSSIP_SENDER_MAIN, Player::PrepareGossipMenu(), SendGossipMenuFor(), Player::TalkedToCreature(), and TEXT_ID_START.
OnGossipSelect()
bool brann_bronzebeard::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 199 of file brann_bronzebeard.cpp.
     {
         if (action)
         {
             switch (action)
             {
                 case GOSSIP_ACTION_INFO_DEF+1:
                     creature->AI()->DoAction(ACTION_START_EVENT);
                     CloseGossipMenuFor(player);
                     break;
                 case GOSSIP_ACTION_INFO_DEF+2:
                     creature->AI()->DoAction(ACTION_START_TRIBUNAL);
                     CloseGossipMenuFor(player);
                     break;
                 case GOSSIP_ACTION_INFO_DEF+3:
                     creature->AI()->DoAction(ACTION_GO_TO_SJONNIR);
                     CloseGossipMenuFor(player);
                     break;
                 case GOSSIP_ACTION_INFO_DEF+4:
                     creature->AI()->DoAction(ACTION_WIPE_START);
                     CloseGossipMenuFor(player);
                     break;
                 case GOSSIP_ACTION_INFO_DEF+5:
                     creature->AI()->DoAction(ACTION_OPEN_DOOR);
                     CloseGossipMenuFor(player);
                     break;
             }
         }
         return true;
     }
References ACTION_GO_TO_SJONNIR, ACTION_OPEN_DOOR, ACTION_START_EVENT, ACTION_START_TRIBUNAL, ACTION_WIPE_START, Creature::AI(), CloseGossipMenuFor(), UnitAI::DoAction(), and GOSSIP_ACTION_INFO_DEF.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/Ulduar/HallsOfStone/brann_bronzebeard.cpp