Azerotcore-wotlk: instance_azjol_nerub::instance_azjol_nerub_InstanceScript Struct Reference
instance_azjol_nerub::instance_azjol_nerub_InstanceScript Struct Reference
Public Member Functions
instance_azjol_nerub_InstanceScript (Map *map)
void OnCreatureCreate (Creature *creature) override
void OnGameObjectCreate (GameObject *go) override
void OnGameObjectRemove (GameObject *go) override
bool SetBossState (uint32 id, EncounterState state) override
std::string GetSaveData () override
void Load (const char *in) override
Public Member Functions inherited from InstanceScript
InstanceScript (Map *map)
~InstanceScript () override
virtual void Initialize ()
virtual void CreatureLooted (Creature *, LootType)
void SaveToDB ()
virtual void Update (uint32)
virtual bool IsEncounterInProgress () const
void OnCreatureRemove (Creature *creature) override
ObjectGuid GetObjectGuid (uint32 type) const
ObjectGuid GetGuidData (uint32 type) const override
Creature * GetCreature (uint32 type)
GameObject * GetGameObject (uint32 type)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerAreaUpdate (Player *, uint32, uint32)
void HandleGameObject (ObjectGuid guid, bool open, GameObject *go=nullptr)
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
void DoUpdateWorldState (uint32 worldstateId, uint32 worldstateValue)
void DoSendNotifyToInstance (char const *format,...)
void DoUpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscValue1=0, uint32 miscValue2=0, Unit *unit=nullptr)
void DoStartTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoStopTimedAchievement (AchievementCriteriaTimedTypes type, uint32 entry)
void DoRemoveAurasDueToSpellOnPlayers (uint32 spell)
void DoCastSpellOnPlayers (uint32 spell)
bool ServerAllowsTwoSideGroups ()
EncounterState GetBossState (uint32 id) const
BossBoundaryMap const * GetBossBoundary (uint32 id) const
BossInfo const * GetBossInfo (uint32 id) const
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *=nullptr, uint32=0)
virtual bool CheckRequiredBosses (uint32, Player const *=nullptr) const
void SetCompletedEncountersMask (uint32 newMask, bool save)
uint32 GetCompletedEncounterMask () const
void SendEncounterUnit (uint32 type, Unit *unit=nullptr, uint8 param1=0, uint8 param2=0)
virtual void FillInitialWorldStates (WorldPacket &)
uint32 GetEncounterCount () const
void MarkAreaTriggerDone (uint32 id)
void ResetAreaTriggerDone (uint32 id)
bool IsAreaTriggerDone (uint32 id) const
virtual void DoAction (int32)
Public Member Functions inherited from ZoneScript
ZoneScript ()
virtual ~ZoneScript ()
virtual uint32 GetCreatureEntry (ObjectGuid::LowType, CreatureData const *data)
virtual uint32 GetGameObjectEntry (ObjectGuid::LowType, uint32 entry)
virtual void OnUnitDeath (Unit *)
virtual void SetGuidData (uint32, ObjectGuid)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void ProcessEvent (WorldObject *, uint32)
Additional Inherited Members
Static Public Member Functions inherited from InstanceScript
static std::string GetBossStateName (uint8 state)
Public Attributes inherited from InstanceScript
Map * instance
Protected Member Functions inherited from InstanceScript
void SetBossNumber (uint32 number)
void LoadDoorData (DoorData const *data)
void LoadMinionData (MinionData const *data)
void LoadObjectData (ObjectData const *creatureData, ObjectData const *gameObjectData)
void AddObject (Creature *obj, bool add)
void AddObject (GameObject *obj, bool add)
void AddObject (WorldObject *obj, uint32 type, bool add)
void AddDoor (GameObject *door, bool add)
void AddMinion (Creature *minion, bool add)
void UpdateDoorState (GameObject *door)
void UpdateMinionState (Creature *minion, EncounterState state)
std::string LoadBossState (char const *data)
std::string GetBossSaveData ()
Detailed Description
Definition at line 42 of file instance_azjol_nerub.cpp.
Constructor & Destructor Documentation
instance_azjol_nerub_InstanceScript()
instance_azjol_nerub::instance_azjol_nerub_InstanceScript::instance_azjol_nerub_InstanceScript (Map * map) inline
Definition at line 44 of file instance_azjol_nerub.cpp.
                                                       : InstanceScript(map)
         {
             SetBossNumber(MAX_ENCOUNTERS);
             LoadDoorData(doorData);
             LoadObjectData(creatureData, nullptr);
         };
References creatureData, doorData, InstanceScript::LoadDoorData(), InstanceScript::LoadObjectData(), MAX_ENCOUNTERS, and InstanceScript::SetBossNumber().
Member Function Documentation
GetSaveData()
std::string instance_azjol_nerub::instance_azjol_nerub_InstanceScript::GetSaveData () inline override virtual
Reimplemented from InstanceScript.
Definition at line 102 of file instance_azjol_nerub.cpp.
         {
             std::ostringstream saveStream;
             saveStream << "A N " << GetBossSaveData();
             return saveStream.str();
         }
References InstanceScript::GetBossSaveData().
Load()
void instance_azjol_nerub::instance_azjol_nerub_InstanceScript::Load (const char * in) inline override virtual
Reimplemented from InstanceScript.
Definition at line 109 of file instance_azjol_nerub.cpp.
         {
             if( !in )
                 return;
             char dataHead1, dataHead2;
             std::istringstream loadStream(in);
             loadStream >> dataHead1 >> dataHead2;
             if (dataHead1 == 'A' && dataHead2 == 'N')
             {
                 for (uint8 i = 0; i < MAX_ENCOUNTERS; ++i)
                 {
                     uint32 tmpState;
                     loadStream >> tmpState;
                     if (tmpState == IN_PROGRESS || tmpState > SPECIAL)
                         tmpState = NOT_STARTED;
                     SetBossState(i, EncounterState(tmpState));
                 }
             }
         }
References IN_PROGRESS, MAX_ENCOUNTERS, NOT_STARTED, SetBossState(), and SPECIAL.
OnCreatureCreate()
void instance_azjol_nerub::instance_azjol_nerub_InstanceScript::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceScript.
Definition at line 51 of file instance_azjol_nerub.cpp.
         {
             switch (creature->GetEntry())
             {
                 case NPC_SKITTERING_SWARMER:
                 case NPC_SKITTERING_INFECTIOR:
                     if (Creature* krikthir = GetCreature((DATA_KRIKTHIR_THE_GATEWATCHER_EVENT)))
                         krikthir->AI()->JustSummoned(creature);
                     break;
                 case NPC_ANUB_AR_CHAMPION:
                 case NPC_ANUB_AR_NECROMANCER:
                 case NPC_ANUB_AR_CRYPTFIEND:
                     if (Creature* hadronox = GetCreature(DATA_HADRONOX_EVENT))
                         hadronox->AI()->JustSummoned(creature);
                     break;
             }
             InstanceScript::OnCreatureCreate(creature);
         }
References DATA_HADRONOX_EVENT, DATA_KRIKTHIR_THE_GATEWATCHER_EVENT, InstanceScript::GetCreature(), Object::GetEntry(), NPC_ANUB_AR_CHAMPION, NPC_ANUB_AR_CRYPTFIEND, NPC_ANUB_AR_NECROMANCER, NPC_SKITTERING_INFECTIOR, NPC_SKITTERING_SWARMER, and InstanceScript::OnCreatureCreate().
OnGameObjectCreate()
void instance_azjol_nerub::instance_azjol_nerub_InstanceScript::OnGameObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
Definition at line 71 of file instance_azjol_nerub.cpp.
         {
             switch (go->GetEntry())
             {
                 case GO_KRIKTHIR_DOORS:
                 case GO_ANUBARAK_DOORS1:
                 case GO_ANUBARAK_DOORS2:
                 case GO_ANUBARAK_DOORS3:
                     AddDoor(go, true);
                     break;
             }
         }
References InstanceScript::AddDoor(), Object::GetEntry(), GO_ANUBARAK_DOORS1, GO_ANUBARAK_DOORS2, GO_ANUBARAK_DOORS3, and GO_KRIKTHIR_DOORS.
OnGameObjectRemove()
void instance_azjol_nerub::instance_azjol_nerub_InstanceScript::OnGameObjectRemove (GameObject * go) inline override virtual
Reimplemented from InstanceScript.
Definition at line 84 of file instance_azjol_nerub.cpp.
         {
             switch (go->GetEntry())
             {
                 case GO_KRIKTHIR_DOORS:
                 case GO_ANUBARAK_DOORS1:
                 case GO_ANUBARAK_DOORS2:
                 case GO_ANUBARAK_DOORS3:
                     AddDoor(go, false);
                     break;
             }
         }
References InstanceScript::AddDoor(), Object::GetEntry(), GO_ANUBARAK_DOORS1, GO_ANUBARAK_DOORS2, GO_ANUBARAK_DOORS3, and GO_KRIKTHIR_DOORS.
SetBossState()
bool instance_azjol_nerub::instance_azjol_nerub_InstanceScript::SetBossState (uint32 id, EncounterState state) inline override virtual
Reimplemented from InstanceScript.
Definition at line 97 of file instance_azjol_nerub.cpp.
         {
             return InstanceScript::SetBossState(id, state);
         }
References InstanceScript::SetBossState().
Referenced by Load().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/AzjolNerub/AzjolNerub/instance_azjol_nerub.cpp