Azerotcore-wotlk: TradeData Class Reference
TradeData Class Reference
#include <TradeData.h>
Public Member Functions
TradeData (Player *player, Player *trader)
Player * GetTrader () const
TradeData * GetTraderData () const
Item * GetItem (TradeSlots slot) const
bool HasItem (ObjectGuid itemGuid) const
TradeSlots GetTradeSlotForItem (ObjectGuid itemGuid) const
void SetItem (TradeSlots slot, Item *item)
uint32 GetSpell () const
void SetSpell (uint32 spell_id, Item *castItem=nullptr)
Item * GetSpellCastItem () const
bool HasSpellCastItem () const
uint32 GetMoney () const
void SetMoney (uint32 money)
bool IsAccepted () const
void SetAccepted (bool state, bool crosssend=false)
bool IsInAcceptProcess () const
void SetInAcceptProcess (bool state)
Private Member Functions
void Update (bool for_trader=true)
Private Attributes
Player * m_player
Player * m_trader
bool m_accepted
bool m_acceptProccess
uint32 m_money
uint32 m_spell
ObjectGuid m_spellCastItem
ObjectGuid m_items [TRADE_SLOT_COUNT]
Detailed Description
Definition at line 26 of file TradeData.h.
Constructor & Destructor Documentation
TradeData()
TradeData::TradeData (Player * player, Player * trader) inline
Definition at line 29 of file TradeData.h.
                                               : m_player(player),  m_trader(trader), m_accepted(false), m_acceptProccess(false), m_money(0), m_spell(0)
     {
     }
Member Function Documentation
GetItem()
Item * TradeData::GetItem (TradeSlots slot) const
Definition at line 25 of file TradeData.cpp.
 {
     return m_items[slot] ? m_player->GetItemByGuid(m_items[slot]) : nullptr;
 }
References Player::GetItemByGuid(), m_items, and m_player.
Referenced by WorldSession::HandleAcceptTradeOpcode(), WorldSession::SendUpdateTrade(), and setAcceptTradeMode().
GetMoney()
uint32 TradeData::GetMoney () const inline
Definition at line 47 of file TradeData.h.
 { return m_money; }
References m_money.
Referenced by WorldSession::HandleAcceptTradeOpcode(), and WorldSession::SendUpdateTrade().
GetSpell()
uint32 TradeData::GetSpell () const inline
Definition at line 41 of file TradeData.h.
 { return m_spell; }
References m_spell.
Referenced by Spell::CheckCast(), WorldSession::HandleAcceptTradeOpcode(), and WorldSession::SendUpdateTrade().
GetSpellCastItem()
Item * TradeData::GetSpellCastItem () const
Definition at line 48 of file TradeData.cpp.
 {
     return m_spellCastItem ? m_player->GetItemByGuid(m_spellCastItem) : nullptr;
 }
References Player::GetItemByGuid(), m_player, and m_spellCastItem.
Referenced by WorldSession::HandleAcceptTradeOpcode().
GetTrader()
Player* TradeData::GetTrader () const inline
Definition at line 33 of file TradeData.h.
 { return m_trader; }
References m_trader.
Referenced by Player::GetTrader(), WorldSession::HandleAcceptTradeOpcode(), WorldSession::HandleBeginTradeOpcode(), and Player::TradeCancel().
GetTraderData()
TradeData * TradeData::GetTraderData () const
Definition at line 20 of file TradeData.cpp.
 {
     return m_trader->GetTradeData();
 }
References Player::GetTradeData(), and m_trader.
Referenced by WorldSession::SendUpdateTrade(), SetItem(), SetMoney(), and SetSpell().
GetTradeSlotForItem()
TradeSlots TradeData::GetTradeSlotForItem (ObjectGuid itemGuid) const
Definition at line 39 of file TradeData.cpp.
 {
     for (uint8 i = 0; i < TRADE_SLOT_COUNT; ++i)
         if (m_items[i] == itemGuid)
             return TradeSlots(i);
     return TRADE_SLOT_INVALID;
 }
References m_items, TRADE_SLOT_COUNT, and TRADE_SLOT_INVALID.
HasItem()
bool TradeData::HasItem (ObjectGuid itemGuid) const
Definition at line 30 of file TradeData.cpp.
 {
     for (uint8 i = 0; i < TRADE_SLOT_COUNT; ++i)
         if (m_items[i] == itemGuid)
             return true;
     return false;
 }
References m_items, and TRADE_SLOT_COUNT.
Referenced by WorldSession::HandleSetTradeItemOpcode().
HasSpellCastItem()
bool TradeData::HasSpellCastItem () const inline
Definition at line 45 of file TradeData.h.
 { return m_spellCastItem; }
References m_spellCastItem.
Referenced by WorldSession::HandleAcceptTradeOpcode().
IsAccepted()
bool TradeData::IsAccepted () const inline
Definition at line 50 of file TradeData.h.
 { return m_accepted; }
References m_accepted.
Referenced by WorldSession::HandleAcceptTradeOpcode().
IsInAcceptProcess()
bool TradeData::IsInAcceptProcess () const inline
Definition at line 53 of file TradeData.h.
 { return m_acceptProccess; }
References m_acceptProccess.
SetAccepted()
void TradeData::SetAccepted (bool state, bool crosssend = false)
Definition at line 119 of file TradeData.cpp.
 {
     m_accepted = state;
     if (!state)
     {
         if (crosssend)
             m_trader->GetSession()->SendTradeStatus(TRADE_STATUS_BACK_TO_TRADE);
         else
             m_player->GetSession()->SendTradeStatus(TRADE_STATUS_BACK_TO_TRADE);
     }
 }
References Player::GetSession(), m_accepted, m_player, m_trader, WorldSession::SendTradeStatus(), and TRADE_STATUS_BACK_TO_TRADE.
Referenced by WorldSession::HandleAcceptTradeOpcode(), WorldSession::HandleUnacceptTradeOpcode(), SetItem(), SetMoney(), and SetSpell().
SetInAcceptProcess()
void TradeData::SetInAcceptProcess (bool state) inline
Definition at line 54 of file TradeData.h.
 { m_acceptProccess = state; }
References m_acceptProccess.
Referenced by clearAcceptTradeMode(), and setAcceptTradeMode().
SetItem()
void TradeData::SetItem (TradeSlots slot, Item * item)
Definition at line 53 of file TradeData.cpp.
 {
     ObjectGuid itemGuid = item ? item->GetGUID() : ObjectGuid::Empty;
     if (m_items[slot] == itemGuid)
         return;
     m_items[slot] = itemGuid;
     SetAccepted(false);
     GetTraderData()->SetAccepted(false);
     Update();
     // need remove possible trader spell applied to changed item
     if (slot == TRADE_SLOT_NONTRADED)
         GetTraderData()->SetSpell(0);
     // need remove possible player spell applied (possible move reagent)
     SetSpell(0);
 }
References ObjectGuid::Empty, Object::GetGUID(), GetTraderData(), m_items, SetAccepted(), SetSpell(), TRADE_SLOT_NONTRADED, and Update().
Referenced by WorldSession::HandleClearTradeItemOpcode(), and WorldSession::HandleSetTradeItemOpcode().
SetMoney()
void TradeData::SetMoney (uint32 money)
Definition at line 92 of file TradeData.cpp.
 {
     if (m_money == money)
         return;
     if (!m_player->HasEnoughMoney(money))
     {
         m_player->GetSession()->SendTradeStatus(TRADE_STATUS_BUSY);
         return;
     }
     m_money = money;
     SetAccepted(false);
     GetTraderData()->SetAccepted(false);
     Update(true);
 }
References Player::GetSession(), GetTraderData(), Player::HasEnoughMoney(), m_money, m_player, WorldSession::SendTradeStatus(), SetAccepted(), TRADE_STATUS_BUSY, and Update().
Referenced by WorldSession::HandleSetTradeGoldOpcode().
SetSpell()
void TradeData::SetSpell (uint32 spell_id, Item * castItem = nullptr)
Definition at line 75 of file TradeData.cpp.
 {
     ObjectGuid itemGuid = castItem ? castItem->GetGUID() : ObjectGuid::Empty;
     if (m_spell == spell_id && m_spellCastItem == itemGuid)
         return;
     m_spell = spell_id;
     m_spellCastItem = itemGuid;
     SetAccepted(false);
     GetTraderData()->SetAccepted(false);
     Update(true);                                           // send spell info to item owner
     Update(false);                                          // send spell info to caster self
 }
References ObjectGuid::Empty, Object::GetGUID(), GetTraderData(), m_spell, m_spellCastItem, SetAccepted(), and Update().
Referenced by WorldSession::HandleAcceptTradeOpcode(), and SetItem().
Update()
void TradeData::Update (bool for_trader = true) private
Definition at line 111 of file TradeData.cpp.
 {
     if (forTarget)
         m_trader->GetSession()->SendUpdateTrade(true);      // player state for trader
     else
         m_player->GetSession()->SendUpdateTrade(false);     // player state for player
 }
References Player::GetSession(), m_player, m_trader, and WorldSession::SendUpdateTrade().
Referenced by SetItem(), SetMoney(), and SetSpell().
Member Data Documentation
m_accepted
bool TradeData::m_accepted private
Definition at line 63 of file TradeData.h.
Referenced by IsAccepted(), and SetAccepted().
m_acceptProccess
bool TradeData::m_acceptProccess private
Definition at line 64 of file TradeData.h.
Referenced by IsInAcceptProcess(), and SetInAcceptProcess().
m_items
ObjectGuid TradeData::m_items[TRADE_SLOT_COUNT] private
Definition at line 71 of file TradeData.h.
Referenced by GetItem(), GetTradeSlotForItem(), HasItem(), and SetItem().
m_money
uint32 TradeData::m_money private
Definition at line 66 of file TradeData.h.
Referenced by GetMoney(), and SetMoney().
m_player
Player* TradeData::m_player private
Definition at line 60 of file TradeData.h.
Referenced by GetItem(), GetSpellCastItem(), SetAccepted(), SetMoney(), and Update().
m_spell
uint32 TradeData::m_spell private
Definition at line 68 of file TradeData.h.
Referenced by GetSpell(), and SetSpell().
m_spellCastItem
ObjectGuid TradeData::m_spellCastItem private
Definition at line 69 of file TradeData.h.
Referenced by GetSpellCastItem(), HasSpellCastItem(), and SetSpell().
m_trader
Player* TradeData::m_trader private
Definition at line 61 of file TradeData.h.
Referenced by GetTrader(), GetTraderData(), SetAccepted(), and Update().
The documentation for this class was generated from the following files:
src/server/game/Entities/Player/TradeData.h
src/server/game/Entities/Player/TradeData.cpp