Azerotcore-wotlk: npc_vics_flying_machine::npc_vics_flying_machineAI Struct Reference
npc_vics_flying_machine::npc_vics_flying_machineAI Struct Reference
Public Member Functions
npc_vics_flying_machineAI (Creature *creature)
void PassengerBoarded (Unit *passenger, int8, bool apply) override
== Fields =======================================
void MovementInform (uint32 type, uint32) override
void SpellHit (Unit *, SpellInfo const *spell) override
Public Member Functions inherited from VehicleAI
VehicleAI (Creature *creature)
void UpdateAI (uint32 diff) override
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void OnCharmed (bool apply) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
uint8 pointId
Additional Inherited Members
Static Public Member Functions inherited from VehicleAI
static int Permissible (Creature const *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1372 of file zone_sholazar_basin.cpp.
Constructor & Destructor Documentation
npc_vics_flying_machineAI()
npc_vics_flying_machine::npc_vics_flying_machineAI::npc_vics_flying_machineAI (Creature * creature) inline
Definition at line 1374 of file zone_sholazar_basin.cpp.
                                                       : VehicleAI(creature)
         {
             pointId = 0;
         }
References pointId.
Member Function Documentation
MovementInform()
void npc_vics_flying_machine::npc_vics_flying_machineAI::MovementInform (uint32 type, uint32) inline override virtual
Reimplemented from CreatureAI.
Definition at line 1399 of file zone_sholazar_basin.cpp.
         {
             if (type != ESCORT_MOTION_TYPE)
                 return;
             if (Vehicle* veh = me->GetVehicleKit())
                 if (Unit* pilot = veh->GetPassenger(0))
                     switch (pointId)
                     {
                         case 5:
                             pilot->ToCreature()->AI()->Talk(VIC_SAY_0);
                             break;
                         case 11:
                             pilot->ToCreature()->AI()->Talk(VIC_SAY_1);
                             break;
                         case 12:
                             pilot->ToCreature()->AI()->Talk(VIC_SAY_2);
                             break;
                         case 14:
                             pilot->ToCreature()->AI()->Talk(VIC_SAY_3);
                             break;
                         case 15:
                             pilot->ToCreature()->ToCreature()->AI()->Talk(VIC_SAY_4);
                             break;
                         case 17:
                             pilot->ToCreature()->AI()->Talk(VIC_SAY_5);
                             break;
                         case 21:
                             pilot->ToCreature()->AI()->Talk(VIC_SAY_6);
                             break;
                         case 25:
                             Talk(PLANE_EMOTE);
                             DoCast(AURA_ENGINE);
                             me->SetFlag(UNIT_FIELD_FLAGS_2, UNIT_FLAG2_FORCE_MOVEMENT);
                             break;
                     }
             pointId++;
         }
References AURA_ENGINE, UnitAI::DoCast(), ESCORT_MOTION_TYPE, Unit::GetVehicleKit(), CreatureAI::me, PLANE_EMOTE, pointId, Object::SetFlag(), CreatureAI::Talk(), UNIT_FIELD_FLAGS_2, UNIT_FLAG2_FORCE_MOVEMENT, VIC_SAY_0, VIC_SAY_1, VIC_SAY_2, VIC_SAY_3, VIC_SAY_4, VIC_SAY_5, and VIC_SAY_6.
PassengerBoarded()
void npc_vics_flying_machine::npc_vics_flying_machineAI::PassengerBoarded (Unit * , int8 , bool) inline override virtual
== Fields =======================================
Reimplemented from CreatureAI.
Definition at line 1381 of file zone_sholazar_basin.cpp.
         {
             if (apply && passenger->GetTypeId() == TYPEID_PLAYER)
             {
                 Movement::PointsArray pathPoints;
                 pathPoints.push_back(G3D::Vector3(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()));
                 WaypointPath const* i_path = sWaypointMgr->GetPath(NPC_PLANE);
                 for (uint8 i = 0; i < i_path->size(); ++i)
                 {
                     WaypointData const* node = i_path->at(i);
                     pathPoints.push_back(G3D::Vector3(node->x, node->y, node->z));
                 }
                 me->GetMotionMaster()->MoveSplinePath(&pathPoints);
             }
         }
References ByteConverter::apply(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Object::GetTypeId(), CreatureAI::me, MotionMaster::MoveSplinePath(), NPC_PLANE, sWaypointMgr, TYPEID_PLAYER, WaypointData::x, WaypointData::y, and WaypointData::z.
SpellHit()
void npc_vics_flying_machine::npc_vics_flying_machineAI::SpellHit (Unit * , SpellInfo const * spell) inline override virtual
Reimplemented from CreatureAI.
Definition at line 1438 of file zone_sholazar_basin.cpp.
         {
             if (spell->Id == SPELL_LAND)
             {
                 Unit* passenger = me->GetVehicleKit()->GetPassenger(1); // player should be on seat 1
                 if (passenger && passenger->GetTypeId() == TYPEID_PLAYER)
                     passenger->CastSpell(passenger, SPELL_CREDIT, true);
                 me->DespawnOrUnsummon();
             }
         }
References Unit::CastSpell(), Creature::DespawnOrUnsummon(), Vehicle::GetPassenger(), Object::GetTypeId(), Unit::GetVehicleKit(), SpellInfo::Id, CreatureAI::me, SPELL_CREDIT, SPELL_LAND, and TYPEID_PLAYER.
Member Data Documentation
pointId
uint8 npc_vics_flying_machine::npc_vics_flying_machineAI::pointId
Definition at line 1379 of file zone_sholazar_basin.cpp.
Referenced by MovementInform(), and npc_vics_flying_machineAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/zone_sholazar_basin.cpp