Azerotcore-wotlk: npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI Struct Reference
npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI Struct Reference
Public Member Functions
npc_lord_illidan_stormrageAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *) override
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void SummonNextWave ()
void CheckEventFail ()
void LiveCounter ()
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
ObjectGuid PlayerGUID
uint32 WaveTimer
uint32 AnnounceTimer
int8 LiveCount
uint8 WaveCount
bool EventStarted
bool Announced
bool Failed
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1250 of file zone_shadowmoon_valley.cpp.
Constructor & Destructor Documentation
npc_lord_illidan_stormrageAI()
npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::npc_lord_illidan_stormrageAI (Creature * creature) inline
Definition at line 1252 of file zone_shadowmoon_valley.cpp.
 : ScriptedAI(creature) { }
Member Function Documentation
AttackStart()
void npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::AttackStart (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1285 of file zone_shadowmoon_valley.cpp.
 { }
CheckEventFail()
void npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::CheckEventFail () inline
Definition at line 1289 of file zone_shadowmoon_valley.cpp.
         {
             Player* player = ObjectAccessor::GetPlayer(*me, PlayerGUID);
             if (!player)
             {
                 Failed = true;
                 return;
             }
             if (Group* EventGroup = player->GetGroup())
             {
                 uint8 GroupMemberCount = 0;
                 uint8 DeadMemberCount = 0;
                 uint8 FailedMemberCount = 0;
                 Group::MemberSlotList const& members = EventGroup->GetMemberSlots();
                 for (Group::member_citerator itr = members.begin(); itr != members.end(); ++itr)
                 {
                     Player* GroupMember = ObjectAccessor::GetPlayer(*me, itr->guid);
                     if (!GroupMember)
                         continue;
                     if (!GroupMember->IsWithinDistInMap(me, EVENT_AREA_RADIUS) && GroupMember->GetQuestStatus(QUEST_BATTLE_OF_THE_CRIMSON_WATCH) == QUEST_STATUS_INCOMPLETE)
                     {
                         GroupMember->FailQuest(QUEST_BATTLE_OF_THE_CRIMSON_WATCH);
                         ++FailedMemberCount;
                     }
                     ++GroupMemberCount;
                     if (GroupMember->isDead())
                         ++DeadMemberCount;
                 }
                 if (GroupMemberCount == FailedMemberCount)
                 {
                     Failed = true;
                 }
                 if (GroupMemberCount == DeadMemberCount)
                 {
                     for (Group::member_citerator itr = members.begin(); itr != members.end(); ++itr)
                     {
                         if (Player* groupMember = ObjectAccessor::GetPlayer(*me, itr->guid))
                             if (groupMember->GetQuestStatus(QUEST_BATTLE_OF_THE_CRIMSON_WATCH) == QUEST_STATUS_INCOMPLETE)
                                 groupMember->FailQuest(QUEST_BATTLE_OF_THE_CRIMSON_WATCH);
                     }
                     Failed = true;
                 }
             }
             else if (player->isDead() || !player->IsWithinDistInMap(me, EVENT_AREA_RADIUS))
             {
                 player->FailQuest(QUEST_BATTLE_OF_THE_CRIMSON_WATCH);
                 Failed = true;
             }
         }
References EVENT_AREA_RADIUS, Failed, Player::FailQuest(), Player::GetGroup(), ObjectAccessor::GetPlayer(), Player::GetQuestStatus(), Unit::isDead(), WorldObject::IsWithinDistInMap(), ScriptedAI::me, PlayerGUID, QUEST_BATTLE_OF_THE_CRIMSON_WATCH, and QUEST_STATUS_INCOMPLETE.
Referenced by UpdateAI().
EnterCombat()
void npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1282 of file zone_shadowmoon_valley.cpp.
 { }
LiveCounter()
void npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::LiveCounter () inline
Definition at line 1345 of file zone_shadowmoon_valley.cpp.
         {
             --LiveCount;
             if (!LiveCount)
                 Announced = false;
         }
References Announced, and LiveCount.
MoveInLineOfSight()
void npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 1283 of file zone_shadowmoon_valley.cpp.
 { }
Reset()
void npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1266 of file zone_shadowmoon_valley.cpp.
         {
             PlayerGUID.Clear();
             WaveTimer = 10000;
             AnnounceTimer = 7000;
             LiveCount = 0;
             WaveCount = 0;
             EventStarted = false;
             Announced = false;
             Failed = false;
             me->SetVisible(false);
         }
References Announced, AnnounceTimer, ObjectGuid::Clear(), EventStarted, Failed, LiveCount, ScriptedAI::me, PlayerGUID, Unit::SetVisible(), WaveCount, and WaveTimer.
SummonNextWave()
void npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::SummonNextWave ()
Definition at line 1507 of file zone_shadowmoon_valley.cpp.
 {
     uint8 count = WavesInfo[WaveCount].SpawnCount;
     uint8 locIndex = WavesInfo[WaveCount].UsedSpawnPoint;
     uint8 FelguardCount = 0;
     uint8 DreadlordCount = 0;
     for (uint8 i = 0; i < count; ++i)
     {
         Creature* Spawn = nullptr;
         float X = SpawnLocation[locIndex + i].x;
         float Y = SpawnLocation[locIndex + i].y;
         float Z = SpawnLocation[locIndex + i].z;
         float O = SpawnLocation[locIndex + i].o;
         Spawn = me->SummonCreature(WavesInfo[WaveCount].CreatureId, X, Y, Z, O, TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, 60000);
         ++LiveCount;
         if (Spawn)
         {
             if (WaveCount == 0)//1 Wave
             {
                 if (rand() % 3 == 1 && FelguardCount < 2)
                 {
                     Spawn->SetDisplayId(18654);
                     ++FelguardCount;
                 }
                 else if (DreadlordCount < 3)
                 {
                     Spawn->SetDisplayId(19991);
                     ++DreadlordCount;
                 }
                 else if (FelguardCount < 2)
                 {
                     Spawn->SetDisplayId(18654);
                     ++FelguardCount;
                 }
             }
             if (WaveCount < 3)//1-3 Wave
             {
                 if (PlayerGUID)
                 {
                     if (Player* target = ObjectAccessor::GetPlayer(*me, PlayerGUID))
                     {
                         float x, y, z;
                         target->GetPosition(x, y, z);
                         Spawn->GetMotionMaster()->MovePoint(0, x, y, z);
                     }
                 }
                 CAST_AI(npc_illidari_spawn::npc_illidari_spawnAI, Spawn->AI())->LordIllidanGUID = me->GetGUID();
             }
             if (WavesInfo[WaveCount].CreatureId == 22076) // Torloth
             {
                 CAST_AI(npc_torloth_the_magnificent::npc_torloth_the_magnificentAI, Spawn->AI())->LordIllidanGUID = me->GetGUID();
                 if (PlayerGUID)
                     CAST_AI(npc_torloth_the_magnificent::npc_torloth_the_magnificentAI, Spawn->AI())->AggroTargetGUID = PlayerGUID;
             }
         }
     }
     ++WaveCount;
     WaveTimer = WavesInfo[WaveCount].SpawnTimer;
     AnnounceTimer = WavesInfo[WaveCount].YellTimer;
 }
References Creature::AI(), AnnounceTimer, CAST_AI, count(), Object::GetGUID(), Unit::GetMotionMaster(), ObjectAccessor::GetPlayer(), LiveCount, ScriptedAI::me, MotionMaster::MovePoint(), O, Location::o, PlayerGUID, Creature::SetDisplayId(), WaveData::SpawnCount, SpawnLocation, WaveData::SpawnTimer, WorldObject::SummonCreature(), TEMPSUMMON_TIMED_OR_DEAD_DESPAWN, WaveData::UsedSpawnPoint, WaveCount, WavesInfo, WaveTimer, G3D::x, X, Location::x, G3D::y, Y, Location::y, WaveData::YellTimer, G3D::z, Z, and Location::z.
Referenced by UpdateAI().
UpdateAI()
void npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1352 of file zone_shadowmoon_valley.cpp.
         {
             if (!PlayerGUID || !EventStarted)
                 return;
             if (!LiveCount && WaveCount < 4)
             {
                 if (!Announced && AnnounceTimer <= diff)
                 {
                     Announced = true;
                 }
                 else
                     AnnounceTimer -= diff;
                 if (WaveTimer <= diff)
                 {
                     SummonNextWave();
                 }
                 else
                     WaveTimer -= diff;
             }
             CheckEventFail();
             if (Failed)
                 EnterEvadeMode();
         }
References Announced, AnnounceTimer, CheckEventFail(), diff(), CreatureAI::EnterEvadeMode(), EventStarted, Failed, LiveCount, PlayerGUID, SummonNextWave(), WaveCount, and WaveTimer.
Member Data Documentation
Announced
bool npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::Announced
Definition at line 1263 of file zone_shadowmoon_valley.cpp.
Referenced by LiveCounter(), Reset(), and UpdateAI().
AnnounceTimer
uint32 npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::AnnounceTimer
Definition at line 1257 of file zone_shadowmoon_valley.cpp.
Referenced by Reset(), SummonNextWave(), and UpdateAI().
EventStarted
bool npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::EventStarted
Definition at line 1262 of file zone_shadowmoon_valley.cpp.
Referenced by Reset(), and UpdateAI().
Failed
bool npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::Failed
Definition at line 1264 of file zone_shadowmoon_valley.cpp.
Referenced by CheckEventFail(), Reset(), and UpdateAI().
LiveCount
int8 npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::LiveCount
Definition at line 1259 of file zone_shadowmoon_valley.cpp.
Referenced by LiveCounter(), Reset(), SummonNextWave(), and UpdateAI().
PlayerGUID
ObjectGuid npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::PlayerGUID
Definition at line 1254 of file zone_shadowmoon_valley.cpp.
Referenced by CheckEventFail(), Reset(), SummonNextWave(), and UpdateAI().
WaveCount
uint8 npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::WaveCount
Definition at line 1260 of file zone_shadowmoon_valley.cpp.
Referenced by Reset(), SummonNextWave(), and UpdateAI().
WaveTimer
uint32 npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::WaveTimer
Definition at line 1256 of file zone_shadowmoon_valley.cpp.
Referenced by Reset(), SummonNextWave(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Outland/zone_shadowmoon_valley.cpp