Azerotcore-wotlk: FollowerAI Class Reference
FollowerAI Class Reference
#include <ScriptedFollowerAI.h>
Public Member Functions
FollowerAI (Creature *creature)
~FollowerAI () override
void MovementInform (uint32 motionType, uint32 pointId) override
void AttackStart (Unit *) override
void MoveInLineOfSight (Unit *) override
void EnterEvadeMode () override
void JustDied (Unit *) override
void JustRespawned () override
void UpdateAI (uint32) override
virtual void UpdateFollowerAI (uint32)
void StartFollow (Player *player, uint32 factionForFollower=0, const Quest *quest=nullptr)
void SetFollowPaused (bool bPaused)
void SetFollowComplete (bool bWithEndEvent=false)
bool HasFollowState (uint32 uiFollowState)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void Reset () override
void EnterCombat (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Protected Member Functions
Player * GetLeaderForFollower ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Private Member Functions
void AddFollowState (uint32 uiFollowState)
void RemoveFollowState (uint32 uiFollowState)
bool AssistPlayerInCombat (Unit *who)
Private Attributes
ObjectGuid m_uiLeaderGUID
uint32 m_uiUpdateFollowTimer
uint32 m_uiFollowState
const Quest * m_pQuestForFollow
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 34 of file ScriptedFollowerAI.h.
Constructor & Destructor Documentation
FollowerAI()
FollowerAI::FollowerAI (Creature * creature) explicit
Definition at line 37 of file ScriptedFollowerAI.cpp.
                                          : ScriptedAI(creature),
     m_uiUpdateFollowTimer(2500),
     m_uiFollowState(STATE_FOLLOW_NONE),
     m_pQuestForFollow(nullptr)
 {}
~FollowerAI()
FollowerAI::~FollowerAI () inline override
Definition at line 38 of file ScriptedFollowerAI.h.
 {}
Member Function Documentation
AddFollowState()
void FollowerAI::AddFollowState (uint32 uiFollowState) inline private
Definition at line 68 of file ScriptedFollowerAI.h.
 { m_uiFollowState |= uiFollowState; }
References m_uiFollowState.
Referenced by MovementInform(), SetFollowComplete(), SetFollowPaused(), and StartFollow().
AssistPlayerInCombat()
bool FollowerAI::AssistPlayerInCombat (Unit * who) private
Definition at line 66 of file ScriptedFollowerAI.cpp.
 {
     if (!who || !who->GetVictim())
         return false;
     //experimental (unknown) flag not present
     if (!(me->GetCreatureTemplate()->type_flags & CREATURE_TYPE_FLAG_CAN_ASSIST))
         return false;
     //not a player
     if (!who->GetVictim()->GetCharmerOrOwnerPlayerOrPlayerItself())
         return false;
     //never attack friendly
     if (me->IsFriendlyTo(who))
         return false;
     //too far away and no free sight?
     if (me->IsWithinDistInMap(who, MAX_PLAYER_DISTANCE) && me->IsWithinLOSInMap(who))
     {
         AttackStart(who);
         return true;
     }
     return false;
 }
References AttackStart(), CREATURE_TYPE_FLAG_CAN_ASSIST, Unit::GetCharmerOrOwnerPlayerOrPlayerItself(), Creature::GetCreatureTemplate(), Unit::GetVictim(), Unit::IsFriendlyTo(), WorldObject::IsWithinDistInMap(), WorldObject::IsWithinLOSInMap(), MAX_PLAYER_DISTANCE, ScriptedAI::me, and CreatureTemplate::type_flags.
Referenced by MoveInLineOfSight().
AttackStart()
void FollowerAI::AttackStart (Unit * who) override virtual
Reimplemented from ScriptedAI.
Definition at line 43 of file ScriptedFollowerAI.cpp.
 {
     if (!who)
         return;
     if (me->Attack(who, true))
     {
         // This is done in Unit::Attack function which wont bug npcs by not adding threat upon combat start...
         //me->AddThreat(who, 0.0f);
         //me->SetInCombatWith(who);
         //who->SetInCombatWith(me);
         if (me->HasUnitState(UNIT_STATE_FOLLOW))
             me->ClearUnitState(UNIT_STATE_FOLLOW);
         if (IsCombatMovementAllowed())
             me->GetMotionMaster()->MoveChase(who);
     }
 }
References Unit::Attack(), Unit::ClearUnitState(), Unit::GetMotionMaster(), Unit::HasUnitState(), ScriptedAI::IsCombatMovementAllowed(), ScriptedAI::me, MotionMaster::MoveChase(), and UNIT_STATE_FOLLOW.
Referenced by AssistPlayerInCombat(), and MoveInLineOfSight().
EnterEvadeMode()
void FollowerAI::EnterEvadeMode () override virtual
Reimplemented from CreatureAI.
Definition at line 153 of file ScriptedFollowerAI.cpp.
 {
     me->RemoveAllAuras();
     me->DeleteThreatList();
     me->CombatStop(true);
     me->SetLootRecipient(nullptr);
     if (HasFollowState(STATE_FOLLOW_INPROGRESS))
     {
         LOG_DEBUG("scripts.ai", "FollowerAI left combat, returning to CombatStartPosition.");
         if (me->GetMotionMaster()->GetCurrentMovementGeneratorType() == CHASE_MOTION_TYPE)
         {
             float fPosX, fPosY, fPosZ;
             me->GetPosition(fPosX, fPosY, fPosZ);
             me->GetMotionMaster()->MovePoint(POINT_COMBAT_START, fPosX, fPosY, fPosZ);
         }
     }
     else
     {
         if (me->GetMotionMaster()->GetCurrentMovementGeneratorType() == CHASE_MOTION_TYPE)
             me->GetMotionMaster()->MoveTargetedHome();
     }
     Reset();
 }
References CHASE_MOTION_TYPE, Unit::CombatStop(), Unit::DeleteThreatList(), MotionMaster::GetCurrentMovementGeneratorType(), Unit::GetMotionMaster(), Position::GetPosition(), HasFollowState(), LOG_DEBUG, ScriptedAI::me, MotionMaster::MovePoint(), MotionMaster::MoveTargetedHome(), POINT_COMBAT_START, Unit::RemoveAllAuras(), ScriptedAI::Reset(), Creature::SetLootRecipient(), and STATE_FOLLOW_INPROGRESS.
GetLeaderForFollower()
Player * FollowerAI::GetLeaderForFollower () protected
Definition at line 305 of file ScriptedFollowerAI.cpp.
 {
     if (Player* player = ObjectAccessor::GetPlayer(*me, m_uiLeaderGUID))
     {
         if (player->IsAlive())
             return player;
         else
         {
             if (Group* group = player->GetGroup())
             {
                 for (GroupReference* groupRef = group->GetFirstMember(); groupRef != nullptr; groupRef = groupRef->next())
                 {
                     Player* member = groupRef->GetSource();
                     if (member && me->IsWithinDistInMap(member, MAX_PLAYER_DISTANCE) && member->IsAlive())
                     {
                         LOG_DEBUG("scripts.ai", "FollowerAI GetLeader changed and returned new leader.");
                         m_uiLeaderGUID = member->GetGUID();
                         return member;
                     }
                 }
             }
         }
     }
     LOG_DEBUG("scripts.ai", "FollowerAI GetLeader can not find suitable leader.");
     return nullptr;
 }
References Object::GetGUID(), ObjectAccessor::GetPlayer(), Unit::IsAlive(), WorldObject::IsWithinDistInMap(), LOG_DEBUG, m_uiLeaderGUID, MAX_PLAYER_DISTANCE, ScriptedAI::me, and GroupReference::next().
Referenced by JustDied(), npc_kerlonian::npc_kerlonianAI::MoveInLineOfSight(), npc_tooga::npc_toogaAI::MoveInLineOfSight(), npc_ringo::npc_ringoAI::MoveInLineOfSight(), MovementInform(), SetFollowPaused(), and UpdateAI().
HasFollowState()
bool FollowerAI::HasFollowState (uint32 uiFollowState) inline
Definition at line 62 of file ScriptedFollowerAI.h.
 { return (m_uiFollowState & uiFollowState); }
References m_uiFollowState.
Referenced by npc_ringo::npc_ringoAI::ClearFaint(), EnterEvadeMode(), JustDied(), MoveInLineOfSight(), npc_kerlonian::npc_kerlonianAI::MoveInLineOfSight(), npc_tooga::npc_toogaAI::MoveInLineOfSight(), npc_ringo::npc_ringoAI::MoveInLineOfSight(), MovementInform(), npc_ringo::npc_ringoAI::SetFaint(), SetFollowComplete(), SetFollowPaused(), npc_kerlonian::npc_kerlonianAI::SpellHit(), npc_ringo::npc_ringoAI::SpellHit(), StartFollow(), UpdateAI(), npc_kerlonian::npc_kerlonianAI::UpdateFollowerAI(), npc_tooga::npc_toogaAI::UpdateFollowerAI(), and npc_ringo::npc_ringoAI::UpdateFollowerAI().
JustDied()
void FollowerAI::JustDied (Unit *) override virtual
Reimplemented from ScriptedAI.
Definition at line 113 of file ScriptedFollowerAI.cpp.
 {
     if (!HasFollowState(STATE_FOLLOW_INPROGRESS) || !m_uiLeaderGUID || !m_pQuestForFollow)
         return;
     //TODO: need a better check for quests with time limit.
     if (Player* player = GetLeaderForFollower())
     {
         if (Group* group = player->GetGroup())
         {
             for (GroupReference* groupRef = group->GetFirstMember(); groupRef != nullptr; groupRef = groupRef->next())
             {
                 if (Player* member = groupRef->GetSource())
                 {
                     if (member->IsInMap(player) && member->GetQuestStatus(m_pQuestForFollow->GetQuestId()) == QUEST_STATUS_INCOMPLETE)
                         member->FailQuest(m_pQuestForFollow->GetQuestId());
                 }
             }
         }
         else
         {
             if (player->GetQuestStatus(m_pQuestForFollow->GetQuestId()) == QUEST_STATUS_INCOMPLETE)
                 player->FailQuest(m_pQuestForFollow->GetQuestId());
         }
     }
 }
References GetLeaderForFollower(), Quest::GetQuestId(), HasFollowState(), m_pQuestForFollow, m_uiLeaderGUID, GroupReference::next(), QUEST_STATUS_INCOMPLETE, and STATE_FOLLOW_INPROGRESS.
JustRespawned()
void FollowerAI::JustRespawned () override virtual
Reimplemented from CreatureAI.
Definition at line 140 of file ScriptedFollowerAI.cpp.
 {
     m_uiFollowState = STATE_FOLLOW_NONE;
     if (!IsCombatMovementAllowed())
         SetCombatMovement(true);
     if (me->GetFaction() != me->GetCreatureTemplate()->faction)
         me->SetFaction(me->GetCreatureTemplate()->faction);
     Reset();
 }
References CreatureTemplate::faction, Creature::GetCreatureTemplate(), Unit::GetFaction(), ScriptedAI::IsCombatMovementAllowed(), m_uiFollowState, ScriptedAI::me, ScriptedAI::Reset(), ScriptedAI::SetCombatMovement(), Unit::SetFaction(), and STATE_FOLLOW_NONE.
MoveInLineOfSight()
void FollowerAI::MoveInLineOfSight (Unit * who) override virtual
Reimplemented from CreatureAI.
Reimplemented in npc_captured_beryl_sorcerer::npc_captured_beryl_sorcererAI, npc_ringo::npc_ringoAI, npc_tooga::npc_toogaAI, and npc_kerlonian::npc_kerlonianAI.
Definition at line 93 of file ScriptedFollowerAI.cpp.
 {
     if (me->GetVictim())
         return;
     if (!me->HasUnitState(UNIT_STATE_STUNNED) && who->isTargetableForAttack(true, me) && who->isInAccessiblePlaceFor(me))
         if (HasFollowState(STATE_FOLLOW_INPROGRESS) && AssistPlayerInCombat(who))
             return;
     if (me->CanStartAttack(who))
     {
         if (me->HasUnitState(UNIT_STATE_DISTRACTED))
         {
             me->ClearUnitState(UNIT_STATE_DISTRACTED);
             me->GetMotionMaster()->Clear();
         }
         AttackStart(who);
     }
 }
References AssistPlayerInCombat(), AttackStart(), Creature::CanStartAttack(), MotionMaster::Clear(), Unit::ClearUnitState(), Unit::GetMotionMaster(), Unit::GetVictim(), HasFollowState(), Unit::HasUnitState(), Unit::isInAccessiblePlaceFor(), Unit::isTargetableForAttack(), ScriptedAI::me, STATE_FOLLOW_INPROGRESS, UNIT_STATE_DISTRACTED, and UNIT_STATE_STUNNED.
Referenced by npc_kerlonian::npc_kerlonianAI::MoveInLineOfSight(), npc_tooga::npc_toogaAI::MoveInLineOfSight(), npc_ringo::npc_ringoAI::MoveInLineOfSight(), and npc_captured_beryl_sorcerer::npc_captured_beryl_sorcererAI::MoveInLineOfSight().
MovementInform()
void FollowerAI::MovementInform (uint32 motionType, uint32 pointId) override virtual
Reimplemented from ScriptedAI.
Reimplemented in npc_tooga::npc_toogaAI.
Definition at line 250 of file ScriptedFollowerAI.cpp.
 {
     if (motionType != POINT_MOTION_TYPE || !HasFollowState(STATE_FOLLOW_INPROGRESS))
         return;
     if (pointId == POINT_COMBAT_START)
     {
         if (GetLeaderForFollower())
         {
             if (!HasFollowState(STATE_FOLLOW_PAUSED))
                 AddFollowState(STATE_FOLLOW_RETURNING);
         }
         else
             me->DespawnOrUnsummon();
     }
 }
References AddFollowState(), Creature::DespawnOrUnsummon(), GetLeaderForFollower(), HasFollowState(), ScriptedAI::me, POINT_COMBAT_START, POINT_MOTION_TYPE, STATE_FOLLOW_INPROGRESS, STATE_FOLLOW_PAUSED, and STATE_FOLLOW_RETURNING.
Referenced by npc_tooga::npc_toogaAI::MovementInform().
RemoveFollowState()
void FollowerAI::RemoveFollowState (uint32 uiFollowState) inline private
Definition at line 69 of file ScriptedFollowerAI.h.
 { m_uiFollowState &= ~uiFollowState; }
References m_uiFollowState.
Referenced by SetFollowComplete(), SetFollowPaused(), and UpdateAI().
SetFollowComplete()
void FollowerAI::SetFollowComplete (bool bWithEndEvent = false)
Definition at line 334 of file ScriptedFollowerAI.cpp.
 {
     if (me->HasUnitState(UNIT_STATE_FOLLOW))
     {
         me->ClearUnitState(UNIT_STATE_FOLLOW);
         me->StopMoving();
         me->GetMotionMaster()->Clear();
         me->GetMotionMaster()->MoveIdle();
     }
     if (bWithEndEvent)
         AddFollowState(STATE_FOLLOW_POSTEVENT);
     else
     {
         if (HasFollowState(STATE_FOLLOW_POSTEVENT))
             RemoveFollowState(STATE_FOLLOW_POSTEVENT);
     }
     AddFollowState(STATE_FOLLOW_COMPLETE);
 }
References AddFollowState(), MotionMaster::Clear(), Unit::ClearUnitState(), Unit::GetMotionMaster(), HasFollowState(), Unit::HasUnitState(), ScriptedAI::me, MotionMaster::MoveIdle(), RemoveFollowState(), STATE_FOLLOW_COMPLETE, STATE_FOLLOW_POSTEVENT, Unit::StopMoving(), and UNIT_STATE_FOLLOW.
Referenced by npc_kerlonian::npc_kerlonianAI::MoveInLineOfSight(), npc_tooga::npc_toogaAI::MoveInLineOfSight(), npc_ringo::npc_ringoAI::MoveInLineOfSight(), npc_captured_beryl_sorcerer::npc_captured_beryl_sorcererAI::MoveInLineOfSight(), npc_tooga::npc_toogaAI::MovementInform(), npc_tooga::npc_toogaAI::UpdateFollowerAI(), and npc_ringo::npc_ringoAI::UpdateFollowerAI().
SetFollowPaused()
void FollowerAI::SetFollowPaused (bool bPaused)
Definition at line 356 of file ScriptedFollowerAI.cpp.
 {
     if (!HasFollowState(STATE_FOLLOW_INPROGRESS) || HasFollowState(STATE_FOLLOW_COMPLETE))
         return;
     if (paused)
     {
         AddFollowState(STATE_FOLLOW_PAUSED);
         if (me->HasUnitState(UNIT_STATE_FOLLOW))
         {
             me->ClearUnitState(UNIT_STATE_FOLLOW);
             me->StopMoving();
             me->GetMotionMaster()->Clear();
             me->GetMotionMaster()->MoveIdle();
         }
     }
     else
     {
         RemoveFollowState(STATE_FOLLOW_PAUSED);
         if (Player* leader = GetLeaderForFollower())
             me->GetMotionMaster()->MoveFollow(leader, PET_FOLLOW_DIST, PET_FOLLOW_ANGLE);
     }
 }
References AddFollowState(), MotionMaster::Clear(), Unit::ClearUnitState(), GetLeaderForFollower(), Unit::GetMotionMaster(), HasFollowState(), Unit::HasUnitState(), ScriptedAI::me, MotionMaster::MoveFollow(), MotionMaster::MoveIdle(), PET_FOLLOW_ANGLE, PET_FOLLOW_DIST, RemoveFollowState(), STATE_FOLLOW_COMPLETE, STATE_FOLLOW_INPROGRESS, STATE_FOLLOW_PAUSED, Unit::StopMoving(), and UNIT_STATE_FOLLOW.
Referenced by npc_ringo::npc_ringoAI::ClearFaint(), npc_kerlonian::npc_kerlonianAI::ClearSleeping(), npc_ringo::npc_ringoAI::SetFaint(), and npc_kerlonian::npc_kerlonianAI::SetSleeping().
StartFollow()
void FollowerAI::StartFollow (Player * player, uint32 factionForFollower = 0, const Quest * quest = nullptr)
Definition at line 267 of file ScriptedFollowerAI.cpp.
 {
     if (me->GetVictim())
     {
         LOG_DEBUG("scripts.ai", "FollowerAI attempt to StartFollow while in combat.");
         return;
     }
     if (HasFollowState(STATE_FOLLOW_INPROGRESS))
     {
         LOG_ERROR("entities.unit.ai", "FollowerAI attempt to StartFollow while already following.");
         return;
     }
     //set variables
     m_uiLeaderGUID = player->GetGUID();
     if (factionForFollower)
         me->SetFaction(factionForFollower);
     m_pQuestForFollow = quest;
     if (me->GetMotionMaster()->GetCurrentMovementGeneratorType() == WAYPOINT_MOTION_TYPE)
     {
         me->GetMotionMaster()->Clear();
         me->GetMotionMaster()->MoveIdle();
         LOG_DEBUG("scripts.ai", "FollowerAI start with WAYPOINT_MOTION_TYPE, set to MoveIdle.");
     }
     me->SetUInt32Value(UNIT_NPC_FLAGS, UNIT_NPC_FLAG_NONE);
     AddFollowState(STATE_FOLLOW_INPROGRESS);
     me->GetMotionMaster()->MoveFollow(player, PET_FOLLOW_DIST, PET_FOLLOW_ANGLE);
     LOG_DEBUG("scripts.ai", "FollowerAI start follow %s (%s)", player->GetName().c_str(), m_uiLeaderGUID.ToString().c_str());
 }
References AddFollowState(), MotionMaster::Clear(), MotionMaster::GetCurrentMovementGeneratorType(), Object::GetGUID(), Unit::GetMotionMaster(), WorldObject::GetName(), Unit::GetVictim(), HasFollowState(), LOG_DEBUG, LOG_ERROR, m_pQuestForFollow, m_uiLeaderGUID, ScriptedAI::me, MotionMaster::MoveFollow(), MotionMaster::MoveIdle(), PET_FOLLOW_ANGLE, PET_FOLLOW_DIST, Unit::SetFaction(), Object::SetUInt32Value(), STATE_FOLLOW_INPROGRESS, ObjectGuid::ToString(), UNIT_NPC_FLAG_NONE, UNIT_NPC_FLAGS, and WAYPOINT_MOTION_TYPE.
Referenced by npc_captured_beryl_sorcerer::npc_captured_beryl_sorcererAI::UpdateAI().
UpdateAI()
void FollowerAI::UpdateAI (uint32 uiDiff) override virtual
Reimplemented from ScriptedAI.
Reimplemented in npc_captured_beryl_sorcerer::npc_captured_beryl_sorcererAI.
Definition at line 180 of file ScriptedFollowerAI.cpp.
 {
     if (HasFollowState(STATE_FOLLOW_INPROGRESS) && !me->GetVictim())
     {
         if (m_uiUpdateFollowTimer <= uiDiff)
         {
             if (HasFollowState(STATE_FOLLOW_COMPLETE) && !HasFollowState(STATE_FOLLOW_POSTEVENT))
             {
                 LOG_DEBUG("scripts.ai", "FollowerAI is set completed, despawns.");
                 me->DespawnOrUnsummon();
                 return;
             }
             bool bIsMaxRangeExceeded = true;
             if (Player* player = GetLeaderForFollower())
             {
                 if (HasFollowState(STATE_FOLLOW_RETURNING))
                 {
                     LOG_DEBUG("scripts.ai", "FollowerAI is returning to leader.");
                     RemoveFollowState(STATE_FOLLOW_RETURNING);
                     me->GetMotionMaster()->MoveFollow(player, PET_FOLLOW_DIST, PET_FOLLOW_ANGLE);
                     return;
                 }
                 if (Group* group = player->GetGroup())
                 {
                     for (GroupReference* groupRef = group->GetFirstMember(); groupRef != nullptr; groupRef = groupRef->next())
                     {
                         Player* member = groupRef->GetSource();
                         if (member && me->IsWithinDistInMap(member, MAX_PLAYER_DISTANCE, true, false))
{
                             bIsMaxRangeExceeded = false;
                             break;
                         }
                     }
                 }
                 else
                 {
                     if (me->IsWithinDistInMap(player, MAX_PLAYER_DISTANCE, true, false))
                         bIsMaxRangeExceeded = false;
                 }
             }
             if (bIsMaxRangeExceeded)
             {
                 LOG_DEBUG("scripts.ai", "FollowerAI failed because player/group was to far away or not found");
                 me->DespawnOrUnsummon();
                 return;
             }
             m_uiUpdateFollowTimer = 1000;
         }
         else
             m_uiUpdateFollowTimer -= uiDiff;
     }
     UpdateFollowerAI(uiDiff);
 }
References Creature::DespawnOrUnsummon(), GetLeaderForFollower(), Unit::GetMotionMaster(), Unit::GetVictim(), HasFollowState(), WorldObject::IsWithinDistInMap(), LOG_DEBUG, m_uiUpdateFollowTimer, MAX_PLAYER_DISTANCE, ScriptedAI::me, MotionMaster::MoveFollow(), GroupReference::next(), PET_FOLLOW_ANGLE, PET_FOLLOW_DIST, RemoveFollowState(), STATE_FOLLOW_COMPLETE, STATE_FOLLOW_INPROGRESS, STATE_FOLLOW_POSTEVENT, STATE_FOLLOW_RETURNING, and UpdateFollowerAI().
UpdateFollowerAI()
void FollowerAI::UpdateFollowerAI (uint32) virtual
Reimplemented in npc_ringo::npc_ringoAI, npc_tooga::npc_toogaAI, and npc_kerlonian::npc_kerlonianAI.
Definition at line 242 of file ScriptedFollowerAI.cpp.
 {
     if (!UpdateVictim())
         return;
     DoMeleeAttackIfReady();
 }
References UnitAI::DoMeleeAttackIfReady(), and CreatureAI::UpdateVictim().
Referenced by UpdateAI().
Member Data Documentation
m_pQuestForFollow
const Quest* FollowerAI::m_pQuestForFollow private
Definition at line 77 of file ScriptedFollowerAI.h.
Referenced by JustDied(), and StartFollow().
m_uiFollowState
uint32 FollowerAI::m_uiFollowState private
Definition at line 75 of file ScriptedFollowerAI.h.
Referenced by AddFollowState(), HasFollowState(), JustRespawned(), and RemoveFollowState().
m_uiLeaderGUID
ObjectGuid FollowerAI::m_uiLeaderGUID private
Definition at line 73 of file ScriptedFollowerAI.h.
Referenced by GetLeaderForFollower(), JustDied(), and StartFollow().
m_uiUpdateFollowTimer
uint32 FollowerAI::m_uiUpdateFollowTimer private
Definition at line 74 of file ScriptedFollowerAI.h.
Referenced by UpdateAI().
The documentation for this class was generated from the following files:
src/server/game/AI/ScriptedAI/ScriptedFollowerAI.h
src/server/game/AI/ScriptedAI/ScriptedFollowerAI.cpp