Azerotcore-wotlk: deps/gsoap/soapServer.cpp File Reference
soapServer.cpp File Reference
#include "soapH.h"
Functions
SOAP_FMAC5 int SOAP_FMAC6 soap_serve (struct soap *soap)
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request (struct soap *soap)
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__executeCommand (struct soap *soap)
Function Documentation
soap_serve()
SOAP_FMAC5 int SOAP_FMAC6 soap_serve (struct soap * soap)
Definition at line 21 of file soapServer.cpp.
 {
 #ifndef WITH_FASTCGI
     soap->keep_alive = soap->max_keep_alive + 1;
 #endif
     do
     {
 #ifndef WITH_FASTCGI
         if (soap->keep_alive > 0 && soap->max_keep_alive > 0)
             soap->keep_alive--;
 #endif
         if (soap_begin_serve(soap))
         {   if (soap->error >= SOAP_STOP)
                 continue;
             return soap->error;
         }
         if ((soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap))) && soap->error && soap->error < SOAP_STOP)
         {
 #ifdef WITH_FASTCGI
             soap_send_fault(soap);
 #else
             return soap_send_fault(soap);
 #endif
         }
 #ifdef WITH_FASTCGI
         soap_destroy(soap);
         soap_end(soap);
     } while (1);
 #else
     } while (soap->keep_alive);
 #endif
     return SOAP_OK;
 }
References soap::error, soap::fserveloop, soap::keep_alive, soap::max_keep_alive, soap_begin_serve(), soap_destroy, soap_end(), soap_send_fault(), soap_serve_request(), and SOAP_STOP.
Referenced by process_message().
soap_serve_ns1__executeCommand()
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns1__executeCommand (struct soap * soap)
Definition at line 65 of file soapServer.cpp.
 {   struct ns1__executeCommand soap_tmp_ns1__executeCommand;
     struct ns1__executeCommandResponse soap_tmp_ns1__executeCommandResponse;
     char * soap_tmp_string;
     soap_default_ns1__executeCommandResponse(soap, &soap_tmp_ns1__executeCommandResponse);
     soap_tmp_string = NULL;
     soap_tmp_ns1__executeCommandResponse.result = &soap_tmp_string;
     soap_default_ns1__executeCommand(soap, &soap_tmp_ns1__executeCommand);
     if (!soap_get_ns1__executeCommand(soap, &soap_tmp_ns1__executeCommand, "ns1:executeCommand", NULL))
         return soap->error;
     if (soap_body_end_in(soap)
      || soap_envelope_end_in(soap)
      || soap_end_recv(soap))
         return soap->error;
     soap->error = ns1__executeCommand(soap, soap_tmp_ns1__executeCommand.command, soap_tmp_ns1__executeCommandResponse.result);
     if (soap->error)
         return soap->error;
     soap->encodingStyle = NULL; /* use SOAP literal style */
     soap_serializeheader(soap);
     soap_serialize_ns1__executeCommandResponse(soap, &soap_tmp_ns1__executeCommandResponse);
     if (soap_begin_count(soap))
         return soap->error;
     if ((soap->mode & SOAP_IO_LENGTH))
     {   if (soap_envelope_begin_out(soap)
          || soap_putheader(soap)
          || soap_body_begin_out(soap)
          || soap_put_ns1__executeCommandResponse(soap, &soap_tmp_ns1__executeCommandResponse, "ns1:executeCommandResponse", "")
          || soap_body_end_out(soap)
          || soap_envelope_end_out(soap))
              return soap->error;
     };
     if (soap_end_count(soap)
      || soap_response(soap, SOAP_OK)
      || soap_envelope_begin_out(soap)
      || soap_putheader(soap)
      || soap_body_begin_out(soap)
      || soap_put_ns1__executeCommandResponse(soap, &soap_tmp_ns1__executeCommandResponse, "ns1:executeCommandResponse", "")
      || soap_body_end_out(soap)
      || soap_envelope_end_out(soap)
      || soap_end_send(soap))
         return soap->error;
     return soap_closesock(soap);
 }
References ns1__executeCommand::command, soap::encodingStyle, soap::error, soap::mode, ns1__executeCommand(), NULL, ns1__executeCommandResponse::result, soap_begin_count(), soap_body_begin_out(), soap_body_end_in(), soap_body_end_out(), soap_closesock(), soap_default_ns1__executeCommand(), soap_default_ns1__executeCommandResponse(), soap_end_count(), soap_end_recv(), soap_end_send(), soap_envelope_begin_out(), soap_envelope_end_in(), soap_envelope_end_out(), soap_get_ns1__executeCommand(), SOAP_IO_LENGTH, SOAP_OK, soap_put_ns1__executeCommandResponse(), soap_putheader(), soap_response(), soap_serialize_ns1__executeCommandResponse(), and soap_serializeheader().
Referenced by soap_serve_request().
soap_serve_request()
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request (struct soap * soap)
Definition at line 56 of file soapServer.cpp.
 {
     (void)soap_peek_element(soap);
     if (!soap_match_tag(soap, soap->tag, "ns1:executeCommand"))
         return soap_serve_ns1__executeCommand(soap);
     return soap->error = SOAP_NO_METHOD;
 }
References soap::error, soap_match_tag(), SOAP_NO_METHOD, soap_peek_element(), soap_serve_ns1__executeCommand(), and soap::tag.
Referenced by soap_serve().