Azerotcore-wotlk: Acore::NearestHostileUnitCheck Class Reference
Acore::NearestHostileUnitCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
NearestHostileUnitCheck (Creature const *creature, float dist=0, bool playerOnly=false)
bool operator() (Unit *u)
Private Member Functions
NearestHostileUnitCheck (NearestHostileUnitCheck const &)
Private Attributes
Creature const * me
float m_range
bool i_playerOnly
Detailed Description
Definition at line 1071 of file GridNotifiers.h.
Constructor & Destructor Documentation
NearestHostileUnitCheck() [1/2]
Acore::NearestHostileUnitCheck::NearestHostileUnitCheck (Creature const * creature, float dist = 0, bool playerOnly = false) inline explicit
Definition at line 1074 of file GridNotifiers.h.
                                                                                                             : me(creature), i_playerOnly(playerOnly)
         {
             m_range = (dist == 0 ? 9999 : dist);
         }
References m_range.
NearestHostileUnitCheck() [2/2]
Acore::NearestHostileUnitCheck::NearestHostileUnitCheck (NearestHostileUnitCheck const &) private
Member Function Documentation
operator()()
bool Acore::NearestHostileUnitCheck::operator() (Unit * u) inline
Definition at line 1078 of file GridNotifiers.h.
         {
             if (!me->IsWithinDistInMap(u, m_range, true, false))
                 return false;
             if (!me->IsValidAttackTarget(u))
                 return false;
             if (i_playerOnly && u->GetTypeId() != TYPEID_PLAYER)
                 return false;
             m_range = me->GetDistance(u);   // use found unit range as new range limit for next check
             return true;
         }
References WorldObject::GetDistance(), Object::GetTypeId(), i_playerOnly, Unit::IsValidAttackTarget(), WorldObject::IsWithinDistInMap(), m_range, me, and TYPEID_PLAYER.
Member Data Documentation
i_playerOnly
bool Acore::NearestHostileUnitCheck::i_playerOnly private
Definition at line 1096 of file GridNotifiers.h.
Referenced by operator()().
m_range
float Acore::NearestHostileUnitCheck::m_range private
Definition at line 1095 of file GridNotifiers.h.
Referenced by NearestHostileUnitCheck(), and operator()().
me
Creature const* Acore::NearestHostileUnitCheck::me private
Definition at line 1094 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/game/Grids/Notifiers/GridNotifiers.h