Azerotcore-wotlk: src/server/game/Entities/Player/PlayerUpdates.cpp File Reference
PlayerUpdates.cpp File Reference
#include "BattlefieldMgr.h"
#include "CellImpl.h"
#include "Channel.h"
#include "ChannelMgr.h"
#include "Formulas.h"
#include "GridNotifiers.h"
#include "GridNotifiersImpl.h"
#include "Group.h"
#include "Guild.h"
#include "InstanceScript.h"
#include "Language.h"
#include "OutdoorPvPMgr.h"
#include "Pet.h"
#include "Player.h"
#include "SavingSystem.h"
#include "ScriptMgr.h"
#include "SkillDiscovery.h"
#include "SpellAuraEffects.h"
#include "UpdateFieldFlags.h"
#include "Vehicle.h"
#include "WeatherMgr.h"
Functions
int SkillGainChance (uint32 SkillValue, uint32 GrayLevel, uint32 GreenLevel, uint32 YellowLevel)
float getProbabilityOfLevelUp (uint32 SkillValue)
template<class T >
void UpdateVisibilityOf_helper (GuidUnorderedSet &s64, T *target, std::vector< Unit * > &)
template<>
void UpdateVisibilityOf_helper (GuidUnorderedSet &s64, GameObject *target, std::vector< Unit * > &)
template<>
void UpdateVisibilityOf_helper (GuidUnorderedSet &s64, Creature *target, std::vector< Unit * > &v)
template<>
void UpdateVisibilityOf_helper (GuidUnorderedSet &s64, Player *target, std::vector< Unit * > &v)
template<class T >
void BeforeVisibilityDestroy (T *, Player *)
template<>
void BeforeVisibilityDestroy< Creature > (Creature *t, Player *p)
Variables
constexpr auto ZONE_UPDATE_INTERVAL = 1000
constexpr auto CINEMATIC_UPDATEDIFF = 500
constexpr auto CINEMATIC_LOOKAHEAD = 2000
static uint32 bonusSkillLevels [] = {75, 150, 225, 300, 375, 450}
static const size_t bonusSkillLevelsSize
Function Documentation
BeforeVisibilityDestroy()
template<class T > void BeforeVisibilityDestroy (T * , Player *) inline
Definition at line 1701 of file PlayerUpdates.cpp.
 {
 }
BeforeVisibilityDestroy< Creature >()
template<> void BeforeVisibilityDestroy< Creature > (Creature * t, Player * p) inline
Definition at line 1706 of file PlayerUpdates.cpp.
 {
     if (p->GetPetGUID() == t->GetGUID() && t->IsPet())
         ((Pet*) t)->Remove(PET_SAVE_NOT_IN_SLOT, true);
 }
References Object::GetGUID(), Unit::GetPetGUID(), Unit::IsPet(), and PET_SAVE_NOT_IN_SLOT.
Referenced by Player::UpdateVisibilityOf().
getProbabilityOfLevelUp()
float getProbabilityOfLevelUp (uint32 SkillValue)
Definition at line 837 of file PlayerUpdates.cpp.
 {
     /* According to El's Extreme Angling page, from 1 to 115 the probability of
      * a skill level up is 100% since 100/1 = 100. From 115 - 135 should average
      * 2 catches per skill up so that means 100/2 = 50%. This returns the
      * probability depending on the player's SkillValue.
      */
     if (!SkillValue)
     {
         return 0.0f;
     }
     std::array<uint32, 10> bounds {115, 135, 160, 190, 215,
                                    295, 315, 355, 425, 450};
     std::array<float, 11>  dens {1.0f, 2.0f, 3.0f, 4.0f, 5.0f, 6.0f,
                                 9.0f, 10.0f, 11.0f, 12.0f, 1.0f};
     auto                   it =
         std::lower_bound(std::begin(bounds), std::end(bounds), SkillValue);
     return 100 / dens[std::distance(std::begin(bounds), it)];
 }
References G3D::distance().
Referenced by Player::UpdateFishingSkill().
SkillGainChance()
int SkillGainChance (uint32 SkillValue, uint32 GrayLevel, uint32 GreenLevel, uint32 YellowLevel) inline
Definition at line 723 of file PlayerUpdates.cpp.
 {
     if (SkillValue >= GrayLevel)
         return sWorld->getIntConfig(CONFIG_SKILL_CHANCE_GREY) * 10;
     if (SkillValue >= GreenLevel)
         return sWorld->getIntConfig(CONFIG_SKILL_CHANCE_GREEN) * 10;
     if (SkillValue >= YellowLevel)
         return sWorld->getIntConfig(CONFIG_SKILL_CHANCE_YELLOW) * 10;
     return sWorld->getIntConfig(CONFIG_SKILL_CHANCE_ORANGE) * 10;
 }
References CONFIG_SKILL_CHANCE_GREEN, CONFIG_SKILL_CHANCE_GREY, CONFIG_SKILL_CHANCE_ORANGE, CONFIG_SKILL_CHANCE_YELLOW, and sWorld.
Referenced by Player::UpdateCraftSkill(), and Player::UpdateGatherSkill().
UpdateVisibilityOf_helper() [1/4]
template<> void UpdateVisibilityOf_helper (GuidUnorderedSet & s64, Creature * target, std::vector< Unit * > & v) inline
Definition at line 1685 of file PlayerUpdates.cpp.
 {
     s64.insert(target->GetGUID());
     v.push_back(target);
 }
References Object::GetGUID().
UpdateVisibilityOf_helper() [2/4]
template<> void UpdateVisibilityOf_helper (GuidUnorderedSet & s64, GameObject * target, std::vector< Unit * > &) inline
Definition at line 1675 of file PlayerUpdates.cpp.
 {
     // @HACK: This is to prevent objects like deeprun tram from disappearing
     // when player moves far from its spawn point while riding it
     if ((target->GetGOInfo()->type != GAMEOBJECT_TYPE_TRANSPORT))
         s64.insert(target->GetGUID());
 }
References GAMEOBJECT_TYPE_TRANSPORT, GameObject::GetGOInfo(), Object::GetGUID(), and GameObjectTemplate::type.
UpdateVisibilityOf_helper() [3/4]
template<> void UpdateVisibilityOf_helper (GuidUnorderedSet & s64, Player * target, std::vector< Unit * > & v) inline
Definition at line 1693 of file PlayerUpdates.cpp.
 {
     s64.insert(target->GetGUID());
     v.push_back(target);
 }
References Object::GetGUID().
UpdateVisibilityOf_helper() [4/4]
template<class T > void UpdateVisibilityOf_helper (GuidUnorderedSet & s64, T * target, std::vector< Unit * > &) inline
Definition at line 1668 of file PlayerUpdates.cpp.
 {
     s64.insert(target->GetGUID());
 }
Referenced by Player::UpdateVisibilityOf().
Variable Documentation
bonusSkillLevels
uint32 bonusSkillLevels[] = {75, 150, 225, 300, 375, 450} static
Definition at line 881 of file PlayerUpdates.cpp.
Referenced by Player::UpdateSkillPro().
bonusSkillLevelsSize
const size_t bonusSkillLevelsSize static
Initial value:
=
    sizeof(bonusSkillLevels) / sizeof(uint32)
Definition at line 882 of file PlayerUpdates.cpp.
Referenced by Player::UpdateSkillPro().
CINEMATIC_LOOKAHEAD
constexpr auto CINEMATIC_LOOKAHEAD = 2000 constexpr
Definition at line 44 of file PlayerUpdates.cpp.
Referenced by Player::UpdateCinematicLocation().
CINEMATIC_UPDATEDIFF
constexpr auto CINEMATIC_UPDATEDIFF = 500 constexpr
Definition at line 43 of file PlayerUpdates.cpp.
Referenced by Player::Update().
ZONE_UPDATE_INTERVAL
constexpr auto ZONE_UPDATE_INTERVAL = 1000 constexpr
Definition at line 41 of file PlayerUpdates.cpp.
Referenced by Player::Update(), and Player::UpdateZone().