Azerotcore-wotlk: npc_ice_tomb::npc_ice_tombAI Struct Reference
npc_ice_tomb::npc_ice_tombAI Struct Reference
Public Member Functions
npc_ice_tombAI (Creature *creature)
void SetGUID (ObjectGuid guid, int32 type) override
void DamageTaken (Unit *, uint32 &dmg, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from NullCreatureAI
NullCreatureAI (Creature *c)
void MoveInLineOfSight (Unit *) override
void AttackStart (Unit *) override
void EnterEvadeMode () override
void OnCharmed (bool) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterCombat (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
virtual void MovementInform (uint32, uint32)
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void Reset ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
ObjectGuid _trappedPlayerGUID
uint32 _existenceCheckTimer
uint16 _asphyxiationTimer
Additional Inherited Members
Static Public Member Functions inherited from NullCreatureAI
static int Permissible (const Creature *)
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 715 of file boss_sindragosa.cpp.
Constructor & Destructor Documentation
npc_ice_tombAI()
npc_ice_tomb::npc_ice_tombAI::npc_ice_tombAI (Creature * creature) inline
Definition at line 717 of file boss_sindragosa.cpp.
                                            : NullCreatureAI(creature)
         {
             me->SetReactState(REACT_PASSIVE);
             _existenceCheckTimer = 1000;
             _asphyxiationTimer = 22500;
         }
References _asphyxiationTimer, _existenceCheckTimer, CreatureAI::me, REACT_PASSIVE, and Creature::SetReactState().
Member Function Documentation
DamageTaken()
void npc_ice_tomb::npc_ice_tombAI::DamageTaken (Unit * , uint32 & dmg, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from UnitAI.
Definition at line 734 of file boss_sindragosa.cpp.
         {
             if (dmg >= me->GetHealth())
                 me->m_positionZ = me->GetPositionZ() - 5.0f;
         }
References Unit::GetHealth(), Position::GetPositionZ(), Position::m_positionZ, and CreatureAI::me.
JustDied()
void npc_ice_tomb::npc_ice_tombAI::JustDied (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 740 of file boss_sindragosa.cpp.
         {
             me->RemoveAllGameObjects();
             if (Player* player = ObjectAccessor::GetPlayer(*me, _trappedPlayerGUID))
             {
                 _trappedPlayerGUID.Clear();
                 player->RemoveAurasDueToSpell(SPELL_ICE_TOMB_DAMAGE);
                 player->RemoveAurasDueToSpell(SPELL_ASPHYXIATION);
                 player->RemoveAurasDueToSpell(SPELL_ICE_TOMB_UNTARGETABLE);
                 me->DespawnOrUnsummon(5000);
             }
         }
References _trappedPlayerGUID, ObjectGuid::Clear(), Creature::DespawnOrUnsummon(), ObjectAccessor::GetPlayer(), CreatureAI::me, Unit::RemoveAllGameObjects(), SPELL_ASPHYXIATION, SPELL_ICE_TOMB_DAMAGE, and SPELL_ICE_TOMB_UNTARGETABLE.
Referenced by UpdateAI().
SetGUID()
void npc_ice_tomb::npc_ice_tombAI::SetGUID (ObjectGuid guid, int32 type) inline override virtual
Reimplemented from UnitAI.
Definition at line 728 of file boss_sindragosa.cpp.
         {
             if (type == DATA_TRAPPED_PLAYER)
                 _trappedPlayerGUID = guid;
         }
References _trappedPlayerGUID, and DATA_TRAPPED_PLAYER.
UpdateAI()
void npc_ice_tomb::npc_ice_tombAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from NullCreatureAI.
Definition at line 754 of file boss_sindragosa.cpp.
         {
             if (!_trappedPlayerGUID)
                 return;
             if (_existenceCheckTimer <= diff)
             {
                 Player* player = ObjectAccessor::GetPlayer(*me, _trappedPlayerGUID);
                 if (!player || !player->IsAlive() || !player->HasAura(SPELL_ICE_TOMB_DAMAGE))
                 {
                     // Remove object
                     JustDied(me);
                     me->DespawnOrUnsummon();
                     return;
                 }
                 _existenceCheckTimer = 1000;
             }
             else
                 _existenceCheckTimer -= diff;
             if (_asphyxiationTimer)
             {
                 if (_asphyxiationTimer <= diff)
                 {
                     _asphyxiationTimer = 0;
                     if (Player* player = ObjectAccessor::GetPlayer(*me, _trappedPlayerGUID))
                     {
                         player->RemoveAurasDueToSpell(SPELL_ICE_TOMB_UNTARGETABLE);
                         player->CastSpell(player, SPELL_ASPHYXIATION, true);
                     }
                 }
                 else
                     _asphyxiationTimer -= diff;
             }
         }
References _asphyxiationTimer, _existenceCheckTimer, _trappedPlayerGUID, Creature::DespawnOrUnsummon(), diff(), ObjectAccessor::GetPlayer(), Unit::HasAura(), Unit::IsAlive(), JustDied(), CreatureAI::me, SPELL_ASPHYXIATION, SPELL_ICE_TOMB_DAMAGE, and SPELL_ICE_TOMB_UNTARGETABLE.
Member Data Documentation
_asphyxiationTimer
uint16 npc_ice_tomb::npc_ice_tombAI::_asphyxiationTimer
Definition at line 726 of file boss_sindragosa.cpp.
Referenced by npc_ice_tombAI(), and UpdateAI().
_existenceCheckTimer
uint32 npc_ice_tomb::npc_ice_tombAI::_existenceCheckTimer
Definition at line 725 of file boss_sindragosa.cpp.
Referenced by npc_ice_tombAI(), and UpdateAI().
_trappedPlayerGUID
ObjectGuid npc_ice_tomb::npc_ice_tombAI::_trappedPlayerGUID
Definition at line 724 of file boss_sindragosa.cpp.
Referenced by JustDied(), SetGUID(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_sindragosa.cpp