Azerotcore-wotlk: deps/argon2/argon2/argon2.h File Reference
argon2.h File Reference
#include <stdint.h>
#include <stddef.h>
#include <limits.h>
Classes
struct Argon2_Context
Macros
#define ARGON2_PUBLIC
#define ARGON2_LOCAL
#define ARGON2_MIN_LANES UINT32_C(1)
#define ARGON2_MAX_LANES UINT32_C(0xFFFFFF)
#define ARGON2_MIN_THREADS UINT32_C(1)
#define ARGON2_MAX_THREADS UINT32_C(0xFFFFFF)
#define ARGON2_SYNC_POINTS UINT32_C(4)
#define ARGON2_MIN_OUTLEN UINT32_C(4)
#define ARGON2_MAX_OUTLEN UINT32_C(0xFFFFFFFF)
#define ARGON2_MIN_MEMORY (2 * ARGON2_SYNC_POINTS) /* 2 blocks per slice */
#define ARGON2_MIN(a, b) ((a) < (b) ? (a) : (b))
#define ARGON2_MAX_MEMORY_BITS ARGON2_MIN(UINT32_C(32), (sizeof(void *) * CHAR_BIT - 10 - 1))
#define ARGON2_MAX_MEMORY ARGON2_MIN(UINT32_C(0xFFFFFFFF), UINT64_C(1) << ARGON2_MAX_MEMORY_BITS)
#define ARGON2_MIN_TIME UINT32_C(1)
#define ARGON2_MAX_TIME UINT32_C(0xFFFFFFFF)
#define ARGON2_MIN_PWD_LENGTH UINT32_C(0)
#define ARGON2_MAX_PWD_LENGTH UINT32_C(0xFFFFFFFF)
#define ARGON2_MIN_AD_LENGTH UINT32_C(0)
#define ARGON2_MAX_AD_LENGTH UINT32_C(0xFFFFFFFF)
#define ARGON2_MIN_SALT_LENGTH UINT32_C(8)
#define ARGON2_MAX_SALT_LENGTH UINT32_C(0xFFFFFFFF)
#define ARGON2_MIN_SECRET UINT32_C(0)
#define ARGON2_MAX_SECRET UINT32_C(0xFFFFFFFF)
#define ARGON2_DEFAULT_FLAGS UINT32_C(0)
#define ARGON2_FLAG_CLEAR_PASSWORD (UINT32_C(1) << 0)
#define ARGON2_FLAG_CLEAR_SECRET (UINT32_C(1) << 1)
Typedefs
typedef enum Argon2_ErrorCodes argon2_error_codes
typedef int(* allocate_fptr) (uint8_t **memory, size_t bytes_to_allocate)
typedef void(* deallocate_fptr) (uint8_t *memory, size_t bytes_to_allocate)
typedef struct Argon2_Context argon2_context
typedef enum Argon2_type argon2_type
typedef enum Argon2_version argon2_version
Enumerations
enum Argon2_ErrorCodes {
ARGON2_OK = 0 , ARGON2_OUTPUT_PTR_NULL = -1 , ARGON2_OUTPUT_TOO_SHORT = -2 , ARGON2_OUTPUT_TOO_LONG = -3 ,
ARGON2_PWD_TOO_SHORT = -4 , ARGON2_PWD_TOO_LONG = -5 , ARGON2_SALT_TOO_SHORT = -6 , ARGON2_SALT_TOO_LONG = -7 ,
ARGON2_AD_TOO_SHORT = -8 , ARGON2_AD_TOO_LONG = -9 , ARGON2_SECRET_TOO_SHORT = -10 , ARGON2_SECRET_TOO_LONG = -11 ,
ARGON2_TIME_TOO_SMALL = -12 , ARGON2_TIME_TOO_LARGE = -13 , ARGON2_MEMORY_TOO_LITTLE = -14 , ARGON2_MEMORY_TOO_MUCH = -15 ,
ARGON2_LANES_TOO_FEW = -16 , ARGON2_LANES_TOO_MANY = -17 , ARGON2_PWD_PTR_MISMATCH = -18 , ARGON2_SALT_PTR_MISMATCH = -19 ,
ARGON2_SECRET_PTR_MISMATCH = -20 , ARGON2_AD_PTR_MISMATCH = -21 , ARGON2_MEMORY_ALLOCATION_ERROR = -22 , ARGON2_FREE_MEMORY_CBK_NULL = -23 ,
ARGON2_ALLOCATE_MEMORY_CBK_NULL = -24 , ARGON2_INCORRECT_PARAMETER = -25 , ARGON2_INCORRECT_TYPE = -26 , ARGON2_OUT_PTR_MISMATCH = -27 ,
ARGON2_THREADS_TOO_FEW = -28 , ARGON2_THREADS_TOO_MANY = -29 , ARGON2_MISSING_ARGS = -30 , ARGON2_ENCODING_FAIL = -31 ,
ARGON2_DECODING_FAIL = -32 , ARGON2_THREAD_FAIL = -33 , ARGON2_DECODING_LENGTH_FAIL = -34 , ARGON2_VERIFY_MISMATCH = -35
}
enum Argon2_type { Argon2_d = 0 , Argon2_i = 1 , Argon2_id = 2 }
enum Argon2_version { ARGON2_VERSION_10 = 0x10 , ARGON2_VERSION_13 = 0x13 , ARGON2_VERSION_NUMBER = ARGON2_VERSION_13 }
Functions
ARGON2_PUBLIC const char * argon2_type2string (argon2_type type, int uppercase)
ARGON2_PUBLIC int argon2_ctx (argon2_context *context, argon2_type type)
ARGON2_PUBLIC int argon2i_hash_encoded (const uint32_t t_cost, const uint32_t m_cost, const uint32_t parallelism, const void *pwd, const size_t pwdlen, const void *salt, const size_t saltlen, const size_t hashlen, char *encoded, const size_t encodedlen)
ARGON2_PUBLIC int argon2i_hash_raw (const uint32_t t_cost, const uint32_t m_cost, const uint32_t parallelism, const void *pwd, const size_t pwdlen, const void *salt, const size_t saltlen, void *hash, const size_t hashlen)
ARGON2_PUBLIC int argon2d_hash_encoded (const uint32_t t_cost, const uint32_t m_cost, const uint32_t parallelism, const void *pwd, const size_t pwdlen, const void *salt, const size_t saltlen, const size_t hashlen, char *encoded, const size_t encodedlen)
ARGON2_PUBLIC int argon2d_hash_raw (const uint32_t t_cost, const uint32_t m_cost, const uint32_t parallelism, const void *pwd, const size_t pwdlen, const void *salt, const size_t saltlen, void *hash, const size_t hashlen)
ARGON2_PUBLIC int argon2id_hash_encoded (const uint32_t t_cost, const uint32_t m_cost, const uint32_t parallelism, const void *pwd, const size_t pwdlen, const void *salt, const size_t saltlen, const size_t hashlen, char *encoded, const size_t encodedlen)
ARGON2_PUBLIC int argon2id_hash_raw (const uint32_t t_cost, const uint32_t m_cost, const uint32_t parallelism, const void *pwd, const size_t pwdlen, const void *salt, const size_t saltlen, void *hash, const size_t hashlen)
ARGON2_PUBLIC int argon2_hash (const uint32_t t_cost, const uint32_t m_cost, const uint32_t parallelism, const void *pwd, const size_t pwdlen, const void *salt, const size_t saltlen, void *hash, const size_t hashlen, char *encoded, const size_t encodedlen, argon2_type type, const uint32_t version)
ARGON2_PUBLIC int argon2i_verify (const char *encoded, const void *pwd, const size_t pwdlen)
ARGON2_PUBLIC int argon2d_verify (const char *encoded, const void *pwd, const size_t pwdlen)
ARGON2_PUBLIC int argon2id_verify (const char *encoded, const void *pwd, const size_t pwdlen)
ARGON2_PUBLIC int argon2_verify (const char *encoded, const void *pwd, const size_t pwdlen, argon2_type type)
ARGON2_PUBLIC int argon2d_ctx (argon2_context *context)
ARGON2_PUBLIC int argon2i_ctx (argon2_context *context)
ARGON2_PUBLIC int argon2id_ctx (argon2_context *context)
ARGON2_PUBLIC int argon2d_verify_ctx (argon2_context *context, const char *hash)
ARGON2_PUBLIC int argon2i_verify_ctx (argon2_context *context, const char *hash)
ARGON2_PUBLIC int argon2id_verify_ctx (argon2_context *context, const char *hash)
ARGON2_PUBLIC int argon2_verify_ctx (argon2_context *context, const char *hash, argon2_type type)
ARGON2_PUBLIC const char * argon2_error_message (int error_code)
ARGON2_PUBLIC size_t argon2_encodedlen (uint32_t t_cost, uint32_t m_cost, uint32_t parallelism, uint32_t saltlen, uint32_t hashlen, argon2_type type)
Variables
int FLAG_clear_internal_memory
Macro Definition Documentation
ARGON2_DEFAULT_FLAGS
#define ARGON2_DEFAULT_FLAGS UINT32_C(0)
Definition at line 91 of file argon2.h.
ARGON2_FLAG_CLEAR_PASSWORD
#define ARGON2_FLAG_CLEAR_PASSWORD (UINT32_C(1) << 0)
Definition at line 92 of file argon2.h.
ARGON2_FLAG_CLEAR_SECRET
#define ARGON2_FLAG_CLEAR_SECRET (UINT32_C(1) << 1)
Definition at line 93 of file argon2.h.
ARGON2_LOCAL
#define ARGON2_LOCAL
Definition at line 38 of file argon2.h.
ARGON2_MAX_AD_LENGTH
#define ARGON2_MAX_AD_LENGTH UINT32_C(0xFFFFFFFF)
Definition at line 80 of file argon2.h.
ARGON2_MAX_LANES
#define ARGON2_MAX_LANES UINT32_C(0xFFFFFF)
Definition at line 47 of file argon2.h.
ARGON2_MAX_MEMORY
#define ARGON2_MAX_MEMORY ARGON2_MIN(UINT32_C(0xFFFFFFFF), UINT64_C(1) << ARGON2_MAX_MEMORY_BITS)
Definition at line 67 of file argon2.h.
ARGON2_MAX_MEMORY_BITS
#define ARGON2_MAX_MEMORY_BITS ARGON2_MIN(UINT32_C(32), (sizeof(void *) * CHAR_BIT - 10 - 1))
Definition at line 65 of file argon2.h.
ARGON2_MAX_OUTLEN
#define ARGON2_MAX_OUTLEN UINT32_C(0xFFFFFFFF)
Definition at line 58 of file argon2.h.
ARGON2_MAX_PWD_LENGTH
#define ARGON2_MAX_PWD_LENGTH UINT32_C(0xFFFFFFFF)
Definition at line 76 of file argon2.h.
ARGON2_MAX_SALT_LENGTH
#define ARGON2_MAX_SALT_LENGTH UINT32_C(0xFFFFFFFF)
Definition at line 84 of file argon2.h.
ARGON2_MAX_SECRET
#define ARGON2_MAX_SECRET UINT32_C(0xFFFFFFFF)
Definition at line 88 of file argon2.h.
ARGON2_MAX_THREADS
#define ARGON2_MAX_THREADS UINT32_C(0xFFFFFF)
Definition at line 51 of file argon2.h.
ARGON2_MAX_TIME
#define ARGON2_MAX_TIME UINT32_C(0xFFFFFFFF)
Definition at line 72 of file argon2.h.
ARGON2_MIN
#define ARGON2_MIN (a, b) ((a) < (b) ? (a) : (b))
Definition at line 63 of file argon2.h.
ARGON2_MIN_AD_LENGTH
#define ARGON2_MIN_AD_LENGTH UINT32_C(0)
Definition at line 79 of file argon2.h.
ARGON2_MIN_LANES
#define ARGON2_MIN_LANES UINT32_C(1)
Definition at line 46 of file argon2.h.
ARGON2_MIN_MEMORY
#define ARGON2_MIN_MEMORY (2 * ARGON2_SYNC_POINTS) /* 2 blocks per slice */
Definition at line 61 of file argon2.h.
ARGON2_MIN_OUTLEN
#define ARGON2_MIN_OUTLEN UINT32_C(4)
Definition at line 57 of file argon2.h.
ARGON2_MIN_PWD_LENGTH
#define ARGON2_MIN_PWD_LENGTH UINT32_C(0)
Definition at line 75 of file argon2.h.
ARGON2_MIN_SALT_LENGTH
#define ARGON2_MIN_SALT_LENGTH UINT32_C(8)
Definition at line 83 of file argon2.h.
ARGON2_MIN_SECRET
#define ARGON2_MIN_SECRET UINT32_C(0)
Definition at line 87 of file argon2.h.
ARGON2_MIN_THREADS
#define ARGON2_MIN_THREADS UINT32_C(1)
Definition at line 50 of file argon2.h.
ARGON2_MIN_TIME
#define ARGON2_MIN_TIME UINT32_C(1)
Definition at line 71 of file argon2.h.
ARGON2_PUBLIC
#define ARGON2_PUBLIC
Definition at line 37 of file argon2.h.
ARGON2_SYNC_POINTS
#define ARGON2_SYNC_POINTS UINT32_C(4)
Definition at line 54 of file argon2.h.
Typedef Documentation
allocate_fptr
typedef int(* allocate_fptr) (uint8_t **memory, size_t bytes_to_allocate)
Definition at line 161 of file argon2.h.
argon2_context
typedef struct Argon2_Context argon2_context
argon2_error_codes
typedef enum Argon2_ErrorCodes argon2_error_codes
argon2_type
typedef enum Argon2_type argon2_type
argon2_version
typedef enum Argon2_version argon2_version
deallocate_fptr
typedef void(* deallocate_fptr) (uint8_t *memory, size_t bytes_to_allocate)
Definition at line 162 of file argon2.h.
Enumeration Type Documentation
Argon2_ErrorCodes
enum Argon2_ErrorCodes
Enumerator
ARGON2_OK
ARGON2_OUTPUT_PTR_NULL
ARGON2_OUTPUT_TOO_SHORT
ARGON2_OUTPUT_TOO_LONG
ARGON2_PWD_TOO_SHORT
ARGON2_PWD_TOO_LONG
ARGON2_SALT_TOO_SHORT
ARGON2_SALT_TOO_LONG
ARGON2_AD_TOO_SHORT
ARGON2_AD_TOO_LONG
ARGON2_SECRET_TOO_SHORT
ARGON2_SECRET_TOO_LONG
ARGON2_TIME_TOO_SMALL
ARGON2_TIME_TOO_LARGE
ARGON2_MEMORY_TOO_LITTLE
ARGON2_MEMORY_TOO_MUCH
ARGON2_LANES_TOO_FEW
ARGON2_LANES_TOO_MANY
ARGON2_PWD_PTR_MISMATCH
ARGON2_SALT_PTR_MISMATCH
ARGON2_SECRET_PTR_MISMATCH
ARGON2_AD_PTR_MISMATCH
ARGON2_MEMORY_ALLOCATION_ERROR
ARGON2_FREE_MEMORY_CBK_NULL
ARGON2_ALLOCATE_MEMORY_CBK_NULL
ARGON2_INCORRECT_PARAMETER
ARGON2_INCORRECT_TYPE
ARGON2_OUT_PTR_MISMATCH
ARGON2_THREADS_TOO_FEW
ARGON2_THREADS_TOO_MANY
ARGON2_MISSING_ARGS
ARGON2_ENCODING_FAIL
ARGON2_DECODING_FAIL
ARGON2_THREAD_FAIL
ARGON2_DECODING_LENGTH_FAIL
ARGON2_VERIFY_MISMATCH
Definition at line 100 of file argon2.h.
{
     ARGON2_OK = 0,
     ARGON2_OUTPUT_PTR_NULL = -1,
     ARGON2_OUTPUT_TOO_SHORT = -2,
     ARGON2_OUTPUT_TOO_LONG = -3,
     ARGON2_PWD_TOO_SHORT = -4,
     ARGON2_PWD_TOO_LONG = -5,
     ARGON2_SALT_TOO_SHORT = -6,
     ARGON2_SALT_TOO_LONG = -7,
     ARGON2_AD_TOO_SHORT = -8,
     ARGON2_AD_TOO_LONG = -9,
     ARGON2_SECRET_TOO_SHORT = -10,
     ARGON2_SECRET_TOO_LONG = -11,
     ARGON2_TIME_TOO_SMALL = -12,
     ARGON2_TIME_TOO_LARGE = -13,
     ARGON2_MEMORY_TOO_LITTLE = -14,
     ARGON2_MEMORY_TOO_MUCH = -15,
     ARGON2_LANES_TOO_FEW = -16,
     ARGON2_LANES_TOO_MANY = -17,
     ARGON2_PWD_PTR_MISMATCH = -18,    /* NULL ptr with non-zero length */
     ARGON2_SALT_PTR_MISMATCH = -19,   /* NULL ptr with non-zero length */
     ARGON2_SECRET_PTR_MISMATCH = -20, /* NULL ptr with non-zero length */
     ARGON2_AD_PTR_MISMATCH = -21,     /* NULL ptr with non-zero length */
     ARGON2_MEMORY_ALLOCATION_ERROR = -22,
     ARGON2_FREE_MEMORY_CBK_NULL = -23,
     ARGON2_ALLOCATE_MEMORY_CBK_NULL = -24,
     ARGON2_INCORRECT_PARAMETER = -25,
     ARGON2_INCORRECT_TYPE = -26,
     ARGON2_OUT_PTR_MISMATCH = -27,
     ARGON2_THREADS_TOO_FEW = -28,
     ARGON2_THREADS_TOO_MANY = -29,
     ARGON2_MISSING_ARGS = -30,
     ARGON2_ENCODING_FAIL = -31,
     ARGON2_DECODING_FAIL = -32,
     ARGON2_THREAD_FAIL = -33,
     ARGON2_DECODING_LENGTH_FAIL = -34,
     ARGON2_VERIFY_MISMATCH = -35
 } argon2_error_codes;
Argon2_type
enum Argon2_type
Enumerator
Argon2_d
Argon2_i
Argon2_id
Definition at line 221 of file argon2.h.
{
   Argon2_d = 0,
   Argon2_i = 1,
   Argon2_id = 2
 } argon2_type;
Argon2_version
enum Argon2_version
Enumerator
ARGON2_VERSION_10
ARGON2_VERSION_13
ARGON2_VERSION_NUMBER
Definition at line 228 of file argon2.h.
{
     ARGON2_VERSION_10 = 0x10,
     ARGON2_VERSION_13 = 0x13,
     ARGON2_VERSION_NUMBER = ARGON2_VERSION_13
 } argon2_version;
Function Documentation
argon2_ctx()
ARGON2_PUBLIC int argon2_ctx (argon2_context * context, argon2_type type)
Definition at line 39 of file argon2.c.
{
     /* 1. Validate all inputs */
     int result = validate_inputs(context);
     uint32_t memory_blocks, segment_length;
     argon2_instance_t instance;
     if (ARGON2_OK != result) {
         return result;
     }
     if (Argon2_d != type && Argon2_i != type && Argon2_id != type) {
         return ARGON2_INCORRECT_TYPE;
     }
     /* 2. Align memory size */
     /* Minimum memory_blocks = 8L blocks, where L is the number of lanes */
     memory_blocks = context->m_cost;
     if (memory_blocks < 2 * ARGON2_SYNC_POINTS * context->lanes) {
         memory_blocks = 2 * ARGON2_SYNC_POINTS * context->lanes;
     }
     segment_length = memory_blocks / (context->lanes * ARGON2_SYNC_POINTS);
     /* Ensure that all segments have equal length */
     memory_blocks = segment_length * (context->lanes * ARGON2_SYNC_POINTS);
     instance.version = context->version;
     instance.memory = NULL;
     instance.passes = context->t_cost;
     instance.memory_blocks = memory_blocks;
     instance.segment_length = segment_length;
     instance.lane_length = segment_length * ARGON2_SYNC_POINTS;
     instance.lanes = context->lanes;
     instance.threads = context->threads;
     instance.type = type;
     if (instance.threads > instance.lanes) {
         instance.threads = instance.lanes;
     }
     /* 3. Initialization: Hashing inputs, allocating memory, filling first
      * blocks
      */
     result = initialize(&instance, context);
     if (ARGON2_OK != result) {
         return result;
     }
     /* 4. Filling memory */
     result = fill_memory_blocks(&instance);
     if (ARGON2_OK != result) {
         return result;
     }
     /* 5. Finalization */
     finalize(context, &instance);
     return ARGON2_OK;
 }
References Argon2_d, Argon2_i, Argon2_id, ARGON2_INCORRECT_TYPE, ARGON2_OK, ARGON2_SYNC_POINTS, fill_memory_blocks(), finalize(), initialize(), Argon2_instance_t::lane_length, Argon2_Context::lanes, Argon2_instance_t::lanes, Argon2_Context::m_cost, Argon2_instance_t::memory, Argon2_instance_t::memory_blocks, NULL, Argon2_instance_t::passes, Argon2_instance_t::segment_length, Argon2_Context::t_cost, Argon2_Context::threads, Argon2_instance_t::threads, Argon2_instance_t::type, validate_inputs(), Argon2_Context::version, and Argon2_instance_t::version.
Referenced by argon2_hash(), argon2_verify_ctx(), argon2d_ctx(), argon2i_ctx(), and argon2id_ctx().
argon2_encodedlen()
ARGON2_PUBLIC size_t argon2_encodedlen (uint32_t t_cost, uint32_t m_cost, uint32_t parallelism, uint32_t saltlen, uint32_t hashlen, argon2_type type)
Returns the encoded hash length for the given input parameters
Parameters
t_cost Number of iterations
m_cost Memory usage in kibibytes
parallelism Number of threads; used to compute lanes
saltlen Salt size in bytes
hashlen Hash size in bytes
type The argon2_type that we want the encoded length for
Returns
The encoded hash length in bytes
Definition at line 447 of file argon2.c.
{
   return strlen("$$v=$m=,t=,p=$$") + strlen(argon2_type2string(type, 0)) +
          numlen(t_cost) + numlen(m_cost) + numlen(parallelism) +
          b64len(saltlen) + b64len(hashlen) + numlen(ARGON2_VERSION_NUMBER) + 1;
 }
References argon2_type2string(), ARGON2_VERSION_NUMBER, b64len(), and numlen().
argon2_error_message()
ARGON2_PUBLIC const char* argon2_error_message (int error_code)
Get the associated error message for given error code
Returns
The error message associated with the given error code
Definition at line 368 of file argon2.c.
{
     switch (error_code) {
     case ARGON2_OK:
         return "OK";
     case ARGON2_OUTPUT_PTR_NULL:
         return "Output pointer is NULL";
     case ARGON2_OUTPUT_TOO_SHORT:
         return "Output is too short";
     case ARGON2_OUTPUT_TOO_LONG:
         return "Output is too long";
     case ARGON2_PWD_TOO_SHORT:
         return "Password is too short";
     case ARGON2_PWD_TOO_LONG:
         return "Password is too long";
     case ARGON2_SALT_TOO_SHORT:
         return "Salt is too short";
     case ARGON2_SALT_TOO_LONG:
         return "Salt is too long";
     case ARGON2_AD_TOO_SHORT:
         return "Associated data is too short";
     case ARGON2_AD_TOO_LONG:
         return "Associated data is too long";
     case ARGON2_SECRET_TOO_SHORT:
         return "Secret is too short";
     case ARGON2_SECRET_TOO_LONG:
         return "Secret is too long";
     case ARGON2_TIME_TOO_SMALL:
         return "Time cost is too small";
     case ARGON2_TIME_TOO_LARGE:
         return "Time cost is too large";
     case ARGON2_MEMORY_TOO_LITTLE:
         return "Memory cost is too small";
     case ARGON2_MEMORY_TOO_MUCH:
         return "Memory cost is too large";
     case ARGON2_LANES_TOO_FEW:
         return "Too few lanes";
     case ARGON2_LANES_TOO_MANY:
         return "Too many lanes";
     case ARGON2_PWD_PTR_MISMATCH:
         return "Password pointer is NULL, but password length is not 0";
     case ARGON2_SALT_PTR_MISMATCH:
         return "Salt pointer is NULL, but salt length is not 0";
     case ARGON2_SECRET_PTR_MISMATCH:
         return "Secret pointer is NULL, but secret length is not 0";
     case ARGON2_AD_PTR_MISMATCH:
         return "Associated data pointer is NULL, but ad length is not 0";
     case ARGON2_MEMORY_ALLOCATION_ERROR:
         return "Memory allocation error";
     case ARGON2_FREE_MEMORY_CBK_NULL:
         return "The free memory callback is NULL";
     case ARGON2_ALLOCATE_MEMORY_CBK_NULL:
         return "The allocate memory callback is NULL";
     case ARGON2_INCORRECT_PARAMETER:
         return "Argon2_Context context is NULL";
     case ARGON2_INCORRECT_TYPE:
         return "There is no such version of Argon2";
     case ARGON2_OUT_PTR_MISMATCH:
         return "Output pointer mismatch";
     case ARGON2_THREADS_TOO_FEW:
         return "Not enough threads";
     case ARGON2_THREADS_TOO_MANY:
         return "Too many threads";
     case ARGON2_MISSING_ARGS:
         return "Missing arguments";
     case ARGON2_ENCODING_FAIL:
         return "Encoding failed";
     case ARGON2_DECODING_FAIL:
         return "Decoding failed";
     case ARGON2_THREAD_FAIL:
         return "Threading failure";
     case ARGON2_DECODING_LENGTH_FAIL:
         return "Some of encoded parameters are too long or too short";
     case ARGON2_VERIFY_MISMATCH:
         return "The password does not match the supplied hash";
     default:
         return "Unknown error code";
     }
 }
References ARGON2_AD_PTR_MISMATCH, ARGON2_AD_TOO_LONG, ARGON2_AD_TOO_SHORT, ARGON2_ALLOCATE_MEMORY_CBK_NULL, ARGON2_DECODING_FAIL, ARGON2_DECODING_LENGTH_FAIL, ARGON2_ENCODING_FAIL, ARGON2_FREE_MEMORY_CBK_NULL, ARGON2_INCORRECT_PARAMETER, ARGON2_INCORRECT_TYPE, ARGON2_LANES_TOO_FEW, ARGON2_LANES_TOO_MANY, ARGON2_MEMORY_ALLOCATION_ERROR, ARGON2_MEMORY_TOO_LITTLE, ARGON2_MEMORY_TOO_MUCH, ARGON2_MISSING_ARGS, ARGON2_OK, ARGON2_OUT_PTR_MISMATCH, ARGON2_OUTPUT_PTR_NULL, ARGON2_OUTPUT_TOO_LONG, ARGON2_OUTPUT_TOO_SHORT, ARGON2_PWD_PTR_MISMATCH, ARGON2_PWD_TOO_LONG, ARGON2_PWD_TOO_SHORT, ARGON2_SALT_PTR_MISMATCH, ARGON2_SALT_TOO_LONG, ARGON2_SALT_TOO_SHORT, ARGON2_SECRET_PTR_MISMATCH, ARGON2_SECRET_TOO_LONG, ARGON2_SECRET_TOO_SHORT, ARGON2_THREAD_FAIL, ARGON2_THREADS_TOO_FEW, ARGON2_THREADS_TOO_MANY, ARGON2_TIME_TOO_LARGE, ARGON2_TIME_TOO_SMALL, and ARGON2_VERIFY_MISMATCH.
argon2_hash()
ARGON2_PUBLIC int argon2_hash (const uint32_t t_cost, const uint32_t m_cost, const uint32_t parallelism, const void * pwd, const size_t pwdlen, const void * salt, const size_t saltlen, void * hash, const size_t hashlen, char * encoded, const size_t encodedlen, argon2_type type, const uint32_t version)
Definition at line 100 of file argon2.c.
{
     argon2_context context;
     int result;
     uint8_t *out;
     if (pwdlen > ARGON2_MAX_PWD_LENGTH) {
         return ARGON2_PWD_TOO_LONG;
     }
     if (saltlen > ARGON2_MAX_SALT_LENGTH) {
         return ARGON2_SALT_TOO_LONG;
     }
     if (hashlen > ARGON2_MAX_OUTLEN) {
         return ARGON2_OUTPUT_TOO_LONG;
     }
     if (hashlen < ARGON2_MIN_OUTLEN) {
         return ARGON2_OUTPUT_TOO_SHORT;
     }
     out = malloc(hashlen);
     if (!out) {
         return ARGON2_MEMORY_ALLOCATION_ERROR;
     }
     context.out = (uint8_t *)out;
     context.outlen = (uint32_t)hashlen;
     context.pwd = CONST_CAST(uint8_t *)pwd;
     context.pwdlen = (uint32_t)pwdlen;
     context.salt = CONST_CAST(uint8_t *)salt;
     context.saltlen = (uint32_t)saltlen;
     context.secret = NULL;
     context.secretlen = 0;
     context.ad = NULL;
     context.adlen = 0;
     context.t_cost = t_cost;
     context.m_cost = m_cost;
     context.lanes = parallelism;
     context.threads = parallelism;
     context.allocate_cbk = NULL;
     context.free_cbk = NULL;
     context.flags = ARGON2_DEFAULT_FLAGS;
     context.version = version;
     result = argon2_ctx(&context, type);
     if (result != ARGON2_OK) {
         clear_internal_memory(out, hashlen);
         free(out);
         return result;
     }
     /* if raw hash requested, write it */
     if (hash) {
         memcpy(hash, out, hashlen);
     }
     /* if encoding requested, write it */
     if (encoded && encodedlen) {
         if (encode_string(encoded, encodedlen, &context, type) != ARGON2_OK) {
             clear_internal_memory(out, hashlen); /* wipe buffers if error */
             clear_internal_memory(encoded, encodedlen);
             free(out);
             return ARGON2_ENCODING_FAIL;
         }
     }
     clear_internal_memory(out, hashlen);
     free(out);
     return ARGON2_OK;
 }
References Argon2_Context::ad, Argon2_Context::adlen, Argon2_Context::allocate_cbk, argon2_ctx(), ARGON2_DEFAULT_FLAGS, ARGON2_ENCODING_FAIL, ARGON2_MAX_OUTLEN, ARGON2_MAX_PWD_LENGTH, ARGON2_MAX_SALT_LENGTH, ARGON2_MEMORY_ALLOCATION_ERROR, ARGON2_MIN_OUTLEN, ARGON2_OK, ARGON2_OUTPUT_TOO_LONG, ARGON2_OUTPUT_TOO_SHORT, ARGON2_PWD_TOO_LONG, ARGON2_SALT_TOO_LONG, clear_internal_memory(), CONST_CAST, encode_string(), Argon2_Context::flags, Argon2_Context::free_cbk, hash(), Argon2_Context::lanes, Argon2_Context::m_cost, memcpy, NULL, Argon2_Context::out, Argon2_Context::outlen, Argon2_Context::pwd, Argon2_Context::pwdlen, Argon2_Context::salt, Argon2_Context::saltlen, Argon2_Context::secret, Argon2_Context::secretlen, Argon2_Context::t_cost, Argon2_Context::threads, Argon2_Context::version, and setup::version.
Referenced by argon2d_hash_encoded(), argon2d_hash_raw(), argon2i_hash_encoded(), argon2i_hash_raw(), argon2id_hash_encoded(), and argon2id_hash_raw().
argon2_type2string()
ARGON2_PUBLIC const char* argon2_type2string (argon2_type type, int uppercase)
Definition at line 26 of file argon2.c.
{
     switch (type) {
         case Argon2_d:
             return uppercase ? "Argon2d" : "argon2d";
         case Argon2_i:
             return uppercase ? "Argon2i" : "argon2i";
         case Argon2_id:
             return uppercase ? "Argon2id" : "argon2id";
     }
     return NULL;
 }
References Argon2_d, Argon2_i, Argon2_id, and NULL.
Referenced by argon2_encodedlen(), decode_string(), and encode_string().
argon2_verify()
ARGON2_PUBLIC int argon2_verify (const char * encoded, const void * pwd, const size_t pwdlen, argon2_type type)
Definition at line 249 of file argon2.c.
{
     argon2_context ctx;
     uint8_t *desired_result = NULL;
     int ret = ARGON2_OK;
     size_t encoded_len;
     uint32_t max_field_len;
     if (pwdlen > ARGON2_MAX_PWD_LENGTH) {
         return ARGON2_PWD_TOO_LONG;
     }
     if (encoded == NULL) {
         return ARGON2_DECODING_FAIL;
     }
     encoded_len = strlen(encoded);
     if (encoded_len > UINT32_MAX) {
         return ARGON2_DECODING_FAIL;
     }
     /* No field can be longer than the encoded length */
     max_field_len = (uint32_t)encoded_len;
     ctx.saltlen = max_field_len;
     ctx.outlen = max_field_len;
     ctx.salt = malloc(ctx.saltlen);
     ctx.out = malloc(ctx.outlen);
     if (!ctx.salt || !ctx.out) {
         ret = ARGON2_MEMORY_ALLOCATION_ERROR;
         goto fail;
     }
     ctx.pwd = (uint8_t *)pwd;
     ctx.pwdlen = (uint32_t)pwdlen;
     ret = decode_string(&ctx, encoded, type);
     if (ret != ARGON2_OK) {
         goto fail;
     }
     /* Set aside the desired result, and get a new buffer. */
     desired_result = ctx.out;
     ctx.out = malloc(ctx.outlen);
     if (!ctx.out) {
         ret = ARGON2_MEMORY_ALLOCATION_ERROR;
         goto fail;
     }
     ret = argon2_verify_ctx(&ctx, (char *)desired_result, type);
     if (ret != ARGON2_OK) {
         goto fail;
     }
 fail:
     free(ctx.salt);
     free(ctx.out);
     free(desired_result);
     return ret;
 }
References ARGON2_DECODING_FAIL, ARGON2_MAX_PWD_LENGTH, ARGON2_MEMORY_ALLOCATION_ERROR, ARGON2_OK, ARGON2_PWD_TOO_LONG, argon2_verify_ctx(), decode_string(), NULL, Argon2_Context::out, Argon2_Context::outlen, Argon2_Context::pwd, Argon2_Context::pwdlen, ret, Argon2_Context::salt, Argon2_Context::saltlen, and UINT32_MAX.
Referenced by argon2d_verify(), argon2i_verify(), and argon2id_verify().
argon2_verify_ctx()
ARGON2_PUBLIC int argon2_verify_ctx (argon2_context * context, const char * hash, argon2_type type)
Definition at line 342 of file argon2.c.
{
     int ret = argon2_ctx(context, type);
     if (ret != ARGON2_OK) {
         return ret;
     }
     if (argon2_compare((uint8_t *)hash, context->out, context->outlen)) {
         return ARGON2_VERIFY_MISMATCH;
     }
     return ARGON2_OK;
 }
References argon2_compare(), argon2_ctx(), ARGON2_OK, ARGON2_VERIFY_MISMATCH, hash(), Argon2_Context::out, Argon2_Context::outlen, and ret.
Referenced by argon2_verify(), argon2d_verify_ctx(), argon2i_verify_ctx(), and argon2id_verify_ctx().
argon2d_ctx()
ARGON2_PUBLIC int argon2d_ctx (argon2_context * context)
Argon2d: Version of Argon2 that picks memory blocks depending on the password and salt. Only for side-channel-free environment!!
Parameters
context Pointer to current Argon2 context
Returns
Zero if successful, a non zero error code otherwise
Definition at line 330 of file argon2.c.
{
     return argon2_ctx(context, Argon2_d);
 }
References argon2_ctx(), and Argon2_d.
argon2d_hash_encoded()
ARGON2_PUBLIC int argon2d_hash_encoded (const uint32_t t_cost, const uint32_t m_cost, const uint32_t parallelism, const void * pwd, const size_t pwdlen, const void * salt, const size_t saltlen, const size_t hashlen, char * encoded, const size_t encodedlen)
Definition at line 199 of file argon2.c.
{
     return argon2_hash(t_cost, m_cost, parallelism, pwd, pwdlen, salt, saltlen,
                        NULL, hashlen, encoded, encodedlen, Argon2_d,
                        ARGON2_VERSION_NUMBER);
 }
References Argon2_d, argon2_hash(), ARGON2_VERSION_NUMBER, and NULL.
argon2d_hash_raw()
ARGON2_PUBLIC int argon2d_hash_raw (const uint32_t t_cost, const uint32_t m_cost, const uint32_t parallelism, const void * pwd, const size_t pwdlen, const void * salt, const size_t saltlen, void * hash, const size_t hashlen)
Definition at line 210 of file argon2.c.
{
     return argon2_hash(t_cost, m_cost, parallelism, pwd, pwdlen, salt, saltlen,
                        hash, hashlen, NULL, 0, Argon2_d, ARGON2_VERSION_NUMBER);
 }
References Argon2_d, argon2_hash(), ARGON2_VERSION_NUMBER, hash(), and NULL.
argon2d_verify()
ARGON2_PUBLIC int argon2d_verify (const char * encoded, const void * pwd, const size_t pwdlen)
Definition at line 320 of file argon2.c.
{
     return argon2_verify(encoded, pwd, pwdlen, Argon2_d);
 }
References Argon2_d, and argon2_verify().
argon2d_verify_ctx()
ARGON2_PUBLIC int argon2d_verify_ctx (argon2_context * context, const char * hash)
Verify if a given password is correct for Argon2d hashing
Parameters
context Pointer to current Argon2 context
hash The password hash to verify. The length of the hash is specified by the context outlen member
Returns
Zero if successful, a non zero error code otherwise
Definition at line 356 of file argon2.c.
{
     return argon2_verify_ctx(context, hash, Argon2_d);
 }
References Argon2_d, argon2_verify_ctx(), and hash().
argon2i_ctx()
ARGON2_PUBLIC int argon2i_ctx (argon2_context * context)
Argon2i: Version of Argon2 that picks memory blocks independent on the password and salt. Good for side-channels, but worse w.r.t. tradeoff attacks if only one pass is used.
Parameters
context Pointer to current Argon2 context
Returns
Zero if successful, a non zero error code otherwise
Definition at line 334 of file argon2.c.
{
     return argon2_ctx(context, Argon2_i);
 }
References argon2_ctx(), and Argon2_i.
argon2i_hash_encoded()
ARGON2_PUBLIC int argon2i_hash_encoded (const uint32_t t_cost, const uint32_t m_cost, const uint32_t parallelism, const void * pwd, const size_t pwdlen, const void * salt, const size_t saltlen, const size_t hashlen, char * encoded, const size_t encodedlen)
Hashes a password with Argon2i, producing an encoded hash
Parameters
t_cost Number of iterations
m_cost Sets memory usage to m_cost kibibytes
parallelism Number of threads and compute lanes
pwd Pointer to password
pwdlen Password size in bytes
salt Pointer to salt
saltlen Salt size in bytes
hashlen Desired length of the hash in bytes
encoded Buffer where to write the encoded hash
encodedlen Size of the buffer (thus max size of the encoded hash)
Precondition
Different parallelism levels will give different results
Returns ARGON2_OK if successful
Definition at line 179 of file argon2.c.
{
     return argon2_hash(t_cost, m_cost, parallelism, pwd, pwdlen, salt, saltlen,
                        NULL, hashlen, encoded, encodedlen, Argon2_i,
                        ARGON2_VERSION_NUMBER);
 }
References argon2_hash(), Argon2_i, ARGON2_VERSION_NUMBER, and NULL.
argon2i_hash_raw()
ARGON2_PUBLIC int argon2i_hash_raw (const uint32_t t_cost, const uint32_t m_cost, const uint32_t parallelism, const void * pwd, const size_t pwdlen, const void * salt, const size_t saltlen, void * hash, const size_t hashlen)
Hashes a password with Argon2i, producing a raw hash at @hash
Parameters
t_cost Number of iterations
m_cost Sets memory usage to m_cost kibibytes
parallelism Number of threads and compute lanes
pwd Pointer to password
pwdlen Password size in bytes
salt Pointer to salt
saltlen Salt size in bytes
hash Buffer where to write the raw hash - updated by the function
hashlen Desired length of the hash in bytes
Precondition
Different parallelism levels will give different results
Returns ARGON2_OK if successful
Definition at line 190 of file argon2.c.
{
     return argon2_hash(t_cost, m_cost, parallelism, pwd, pwdlen, salt, saltlen,
                        hash, hashlen, NULL, 0, Argon2_i, ARGON2_VERSION_NUMBER);
 }
References argon2_hash(), Argon2_i, ARGON2_VERSION_NUMBER, hash(), and NULL.
argon2i_verify()
ARGON2_PUBLIC int argon2i_verify (const char * encoded, const void * pwd, const size_t pwdlen)
Verifies a password against an encoded string Encoded string is restricted as in validate_inputs()
Parameters
encoded String encoding parameters, salt, hash
pwd Pointer to password
Precondition
Returns ARGON2_OK if successful
Definition at line 315 of file argon2.c.
{
     return argon2_verify(encoded, pwd, pwdlen, Argon2_i);
 }
References Argon2_i, and argon2_verify().
argon2i_verify_ctx()
ARGON2_PUBLIC int argon2i_verify_ctx (argon2_context * context, const char * hash)
Verify if a given password is correct for Argon2i hashing
Parameters
context Pointer to current Argon2 context
hash The password hash to verify. The length of the hash is specified by the context outlen member
Returns
Zero if successful, a non zero error code otherwise
Definition at line 360 of file argon2.c.
{
     return argon2_verify_ctx(context, hash, Argon2_i);
 }
References Argon2_i, argon2_verify_ctx(), and hash().
argon2id_ctx()
ARGON2_PUBLIC int argon2id_ctx (argon2_context * context)
Argon2id: Version of Argon2 where the first half-pass over memory is password-independent, the rest are password-dependent (on the password and salt). OK against side channels (they reduce to 1/2-pass Argon2i), and better with w.r.t. tradeoff attacks (similar to Argon2d).
Parameters
context Pointer to current Argon2 context
Returns
Zero if successful, a non zero error code otherwise
Definition at line 338 of file argon2.c.
{
     return argon2_ctx(context, Argon2_id);
 }
References argon2_ctx(), and Argon2_id.
argon2id_hash_encoded()
ARGON2_PUBLIC int argon2id_hash_encoded (const uint32_t t_cost, const uint32_t m_cost, const uint32_t parallelism, const void * pwd, const size_t pwdlen, const void * salt, const size_t saltlen, const size_t hashlen, char * encoded, const size_t encodedlen)
Definition at line 219 of file argon2.c.
{
     return argon2_hash(t_cost, m_cost, parallelism, pwd, pwdlen, salt, saltlen,
                        NULL, hashlen, encoded, encodedlen, Argon2_id,
                        ARGON2_VERSION_NUMBER);
 }
References argon2_hash(), Argon2_id, ARGON2_VERSION_NUMBER, and NULL.
Referenced by Acore::Crypto::Argon2::Hash().
argon2id_hash_raw()
ARGON2_PUBLIC int argon2id_hash_raw (const uint32_t t_cost, const uint32_t m_cost, const uint32_t parallelism, const void * pwd, const size_t pwdlen, const void * salt, const size_t saltlen, void * hash, const size_t hashlen)
Definition at line 230 of file argon2.c.
{
     return argon2_hash(t_cost, m_cost, parallelism, pwd, pwdlen, salt, saltlen,
                        hash, hashlen, NULL, 0, Argon2_id,
                        ARGON2_VERSION_NUMBER);
 }
References argon2_hash(), Argon2_id, ARGON2_VERSION_NUMBER, hash(), and NULL.
argon2id_verify()
ARGON2_PUBLIC int argon2id_verify (const char * encoded, const void * pwd, const size_t pwdlen)
Definition at line 325 of file argon2.c.
{
     return argon2_verify(encoded, pwd, pwdlen, Argon2_id);
 }
References Argon2_id, and argon2_verify().
Referenced by Acore::Crypto::Argon2::Verify().
argon2id_verify_ctx()
ARGON2_PUBLIC int argon2id_verify_ctx (argon2_context * context, const char * hash)
Verify if a given password is correct for Argon2id hashing
Parameters
context Pointer to current Argon2 context
hash The password hash to verify. The length of the hash is specified by the context outlen member
Returns
Zero if successful, a non zero error code otherwise
Definition at line 364 of file argon2.c.
{
     return argon2_verify_ctx(context, hash, Argon2_id);
 }
References Argon2_id, argon2_verify_ctx(), and hash().
Variable Documentation
FLAG_clear_internal_memory
int FLAG_clear_internal_memory extern
Definition at line 148 of file core.c.
Referenced by clear_internal_memory().