Azerotcore-wotlk: instance_commandscript Class Reference
instance_commandscript Class Reference
Public Member Functions
instance_commandscript ()
ChatCommandTable GetCommands () const override
Public Member Functions inherited from ScriptObject
virtual bool IsDatabaseBound () const
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Static Public Member Functions
static bool HandleInstanceListBindsCommand (ChatHandler *handler)
static bool HandleInstanceUnbindCommand (ChatHandler *handler, Variant< uint16, EXACT_SEQUENCE("all")> mapArg, Optional< uint8 > difficultyArg)
static bool HandleInstanceStatsCommand (ChatHandler *handler)
static bool HandleInstanceSaveDataCommand (ChatHandler *handler)
static bool HandleInstanceSetBossStateCommand (ChatHandler *handler, uint32 encounterId, uint32 state, Optional< PlayerIdentifier > player)
static bool HandleInstanceGetBossStateCommand (ChatHandler *handler, uint32 encounterId, Optional< PlayerIdentifier > player)
Additional Inherited Members
Protected Member Functions inherited from CommandScript
CommandScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 37 of file cs_instance.cpp.
Constructor & Destructor Documentation
instance_commandscript()
instance_commandscript::instance_commandscript () inline
Definition at line 40 of file cs_instance.cpp.
 : CommandScript("instance_commandscript") { }
Member Function Documentation
GetCommands()
ChatCommandTable instance_commandscript::GetCommands () const inline override virtual
Implements CommandScript.
Definition at line 42 of file cs_instance.cpp.
     {
         static ChatCommandTable instanceCommandTable =
         {
             { "listbinds",    HandleInstanceListBindsCommand,    SEC_MODERATOR,     Console::No },
             { "unbind",       HandleInstanceUnbindCommand,       SEC_GAMEMASTER,    Console::No },
             { "stats",        HandleInstanceStatsCommand,        SEC_MODERATOR,     Console::Yes },
             { "savedata",     HandleInstanceSaveDataCommand,     SEC_ADMINISTRATOR, Console::No },
             { "setbossstate", HandleInstanceSetBossStateCommand, SEC_GAMEMASTER,    Console::Yes },
             { "getbossstate", HandleInstanceGetBossStateCommand, SEC_MODERATOR,     Console::Yes },
         };
         static ChatCommandTable commandTable =
         {
             { "instance", instanceCommandTable },
         };
         return commandTable;
     }
References Acore::ChatCommands::No, SEC_ADMINISTRATOR, SEC_GAMEMASTER, SEC_MODERATOR, and Acore::ChatCommands::Yes.
HandleInstanceGetBossStateCommand()
static bool instance_commandscript::HandleInstanceGetBossStateCommand (ChatHandler * handler, uint32 encounterId, Optional< PlayerIdentifier > player) inline static
Definition at line 219 of file cs_instance.cpp.
     {
         // Character name must be provided when using this from console.
         if (!player && !handler->GetSession())
         {
             handler->PSendSysMessage(LANG_CMD_SYNTAX);
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (!player)
             player = PlayerIdentifier::FromSelf(handler);
         if (!player->IsConnected())
         {
             handler->PSendSysMessage(LANG_PLAYER_NOT_FOUND);
             handler->SetSentErrorMessage(true);
             return false;
         }
         InstanceMap* map = player->GetConnectedPlayer()->GetMap()->ToInstanceMap();
         if (!map)
         {
             handler->PSendSysMessage(LANG_NOT_DUNGEON);
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (!map->GetInstanceScript())
         {
             handler->PSendSysMessage(LANG_NO_INSTANCE_DATA);
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (encounterId > map->GetInstanceScript()->GetEncounterCount())
         {
             handler->PSendSysMessage(LANG_BAD_VALUE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         uint32 state = map->GetInstanceScript()->GetBossState(encounterId);
         std::string stateName = InstanceScript::GetBossStateName(state);
         handler->PSendSysMessage(LANG_COMMAND_INST_GET_BOSS_STATE, encounterId, state, stateName.c_str());
         return true;
     }
References Acore::ChatCommands::PlayerIdentifier::FromSelf(), InstanceScript::GetBossState(), InstanceScript::GetBossStateName(), InstanceScript::GetEncounterCount(), InstanceMap::GetInstanceScript(), ChatHandler::GetSession(), LANG_BAD_VALUE, LANG_CMD_SYNTAX, LANG_COMMAND_INST_GET_BOSS_STATE, LANG_NO_INSTANCE_DATA, LANG_NOT_DUNGEON, LANG_PLAYER_NOT_FOUND, ChatHandler::PSendSysMessage(), ChatHandler::SetSentErrorMessage(), and Map::ToInstanceMap().
HandleInstanceListBindsCommand()
static bool instance_commandscript::HandleInstanceListBindsCommand (ChatHandler * handler) inline static
Definition at line 62 of file cs_instance.cpp.
     {
         Player* player = handler->getSelectedPlayer();
         if (!player)
             player = handler->GetSession()->GetPlayer();
         uint32 counter = 0;
         for (uint8 i = 0; i < MAX_DIFFICULTY; ++i)
         {
             for (auto const& [mapId, bind] : sInstanceSaveMgr->PlayerGetBoundInstances(player->GetGUID(), Difficulty(i)))
             {
                 InstanceSave const* save = bind.save;
                 uint32 resetTime = bind.extended ? save->GetExtendedResetTime() : save->GetResetTime();
                 uint32 ttr = (resetTime >= time(nullptr) ? resetTime - time(nullptr) : 0);
                 std::string timeleft = secsToTimeString(ttr);
                 handler->PSendSysMessage("map: %d, inst: %d, perm: %s, diff: %d, canReset: %s, TTR: %s%s",
                     mapId, save->GetInstanceId(), bind.perm ? "yes" : "no", save->GetDifficulty(), save->CanReset() ? "yes" : "no", timeleft.c_str(), (bind.extended ? " (extended)" : ""));
                 counter++;
             }
         }
         handler->PSendSysMessage("player binds: %d", counter);
         return true;
     }
References InstanceSave::CanReset(), InstanceSave::GetDifficulty(), InstanceSave::GetExtendedResetTime(), Object::GetGUID(), InstanceSave::GetInstanceId(), WorldSession::GetPlayer(), InstanceSave::GetResetTime(), ChatHandler::getSelectedPlayer(), ChatHandler::GetSession(), MAX_DIFFICULTY, ChatHandler::PSendSysMessage(), secsToTimeString(), and sInstanceSaveMgr.
HandleInstanceSaveDataCommand()
static bool instance_commandscript::HandleInstanceSaveDataCommand (ChatHandler * handler) inline static
Definition at line 147 of file cs_instance.cpp.
     {
         Player* player = handler->GetSession()->GetPlayer();
         Map* map = player->GetMap();
         if (!map->IsDungeon())
         {
             handler->PSendSysMessage("Map is not a dungeon.");
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (!map->ToInstanceMap()->GetInstanceScript())
         {
             handler->PSendSysMessage("Map has no instance data.");
             handler->SetSentErrorMessage(true);
             return false;
         }
         map->ToInstanceMap()->GetInstanceScript()->SaveToDB();
         return true;
     }
References InstanceMap::GetInstanceScript(), WorldObject::GetMap(), WorldSession::GetPlayer(), ChatHandler::GetSession(), Map::IsDungeon(), ChatHandler::PSendSysMessage(), InstanceScript::SaveToDB(), ChatHandler::SetSentErrorMessage(), and Map::ToInstanceMap().
HandleInstanceSetBossStateCommand()
static bool instance_commandscript::HandleInstanceSetBossStateCommand (ChatHandler * handler, uint32 encounterId, uint32 state, Optional< PlayerIdentifier > player) inline static
Definition at line 170 of file cs_instance.cpp.
     {
         // Character name must be provided when using this from console.
         if (!player && !handler->GetSession())
         {
             handler->PSendSysMessage(LANG_CMD_SYNTAX);
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (!player)
             player = PlayerIdentifier::FromSelf(handler);
         if (!player->IsConnected())
         {
             handler->PSendSysMessage(LANG_PLAYER_NOT_FOUND);
             handler->SetSentErrorMessage(true);
             return false;
         }
         InstanceMap* map = player->GetConnectedPlayer()->GetMap()->ToInstanceMap();
         if (!map)
         {
             handler->PSendSysMessage(LANG_NOT_DUNGEON);
             handler->SetSentErrorMessage(true);
             return false;
         }
         if (!map->GetInstanceScript())
         {
             handler->PSendSysMessage(LANG_NO_INSTANCE_DATA);
             handler->SetSentErrorMessage(true);
             return false;
         }
         // Reject improper values.
         if (encounterId > map->GetInstanceScript()->GetEncounterCount())
         {
             handler->PSendSysMessage(LANG_BAD_VALUE);
             handler->SetSentErrorMessage(true);
             return false;
         }
         map->GetInstanceScript()->SetBossState(encounterId, EncounterState(state));
         std::string stateName = InstanceScript::GetBossStateName(state);
         handler->PSendSysMessage(LANG_COMMAND_INST_SET_BOSS_STATE, encounterId, state, stateName.c_str());
         return true;
     }
References Acore::ChatCommands::PlayerIdentifier::FromSelf(), InstanceScript::GetBossStateName(), InstanceScript::GetEncounterCount(), InstanceMap::GetInstanceScript(), ChatHandler::GetSession(), LANG_BAD_VALUE, LANG_CMD_SYNTAX, LANG_COMMAND_INST_SET_BOSS_STATE, LANG_NO_INSTANCE_DATA, LANG_NOT_DUNGEON, LANG_PLAYER_NOT_FOUND, ChatHandler::PSendSysMessage(), InstanceScript::SetBossState(), ChatHandler::SetSentErrorMessage(), and Map::ToInstanceMap().
HandleInstanceStatsCommand()
static bool instance_commandscript::HandleInstanceStatsCommand (ChatHandler * handler) inline static
Definition at line 131 of file cs_instance.cpp.
     {
         uint32 dungeon = 0, battleground = 0, arena = 0, spectators = 0;
         sMapMgr->GetNumInstances(dungeon, battleground, arena);
         handler->PSendSysMessage("instances loaded: dungeons (%d), battlegrounds (%d), arenas (%d)", dungeon, battleground, arena);
         dungeon = 0;
         battleground = 0;
         arena = 0;
         spectators = 0;
         sMapMgr->GetNumPlayersInInstances(dungeon, battleground, arena, spectators);
         handler->PSendSysMessage("players in instances: dungeons (%d), battlegrounds (%d), arenas (%d + %d spect)", dungeon, battleground, arena, spectators);
         handler->SetSentErrorMessage(true);
         return false;
     }
References ChatHandler::PSendSysMessage(), ChatHandler::SetSentErrorMessage(), and sMapMgr.
HandleInstanceUnbindCommand()
static bool instance_commandscript::HandleInstanceUnbindCommand (ChatHandler * handler, Variant< uint16, EXACT_SEQUENCE("all")> mapArg, Optional< uint8 > difficultyArg) inline static
Definition at line 89 of file cs_instance.cpp.
     {
         Player* player = handler->getSelectedPlayer();
         if (!player)
             player = handler->GetSession()->GetPlayer();
         uint16 counter = 0;
         uint16 mapId = 0;
         if (mapArg.holds_alternative<uint16>())
         {
             mapId = mapArg.get<uint16>();
             if (!mapId)
                 return false;
         }
         for (uint8 i = 0; i < MAX_DIFFICULTY; ++i)
         {
             BoundInstancesMap const& m_boundInstances = sInstanceSaveMgr->PlayerGetBoundInstances(player->GetGUID(), Difficulty(i));
             for (BoundInstancesMap::const_iterator itr = m_boundInstances.begin(); itr != m_boundInstances.end();)
             {
                 InstanceSave const* save = itr->second.save;
                 if (itr->first != player->GetMapId() && (!mapId || mapId == itr->first) && (!difficultyArg || difficultyArg == save->GetDifficulty()))
                 {
                     uint32 resetTime = itr->second.extended ? save->GetExtendedResetTime() : save->GetResetTime();
                     uint32 ttr = (resetTime >= time(nullptr) ? resetTime - time(nullptr) : 0);
                     std::string timeleft = secsToTimeString(ttr);
                     handler->PSendSysMessage("unbinding map: %d, inst: %d, perm: %s, diff: %d, canReset: %s, TTR: %s%s", itr->first, save->GetInstanceId(), itr->second.perm ? "yes" : "no", save->GetDifficulty(), save->CanReset() ? "yes" : "no", timeleft.c_str(), (itr->second.extended ? " (extended)" : ""));
                     sInstanceSaveMgr->PlayerUnbindInstance(player->GetGUID(), itr->first, Difficulty(i), true, player);
                     itr = m_boundInstances.begin();
                     counter++;
                 }
                 else
                     ++itr;
             }
         }
         handler->PSendSysMessage("instances unbound: %d", counter);
         return true;
     }
References InstanceSave::CanReset(), InstanceSave::GetDifficulty(), InstanceSave::GetExtendedResetTime(), Object::GetGUID(), InstanceSave::GetInstanceId(), WorldLocation::GetMapId(), WorldSession::GetPlayer(), InstanceSave::GetResetTime(), ChatHandler::getSelectedPlayer(), ChatHandler::GetSession(), MAX_DIFFICULTY, ChatHandler::PSendSysMessage(), secsToTimeString(), and sInstanceSaveMgr.
The documentation for this class was generated from the following file:
src/server/scripts/Commands/cs_instance.cpp