Azerotcore-wotlk: boss_gormok::boss_gormokAI Struct Reference
boss_gormok::boss_gormokAI Struct Reference
Public Member Functions
boss_gormokAI (Creature *pCreature)
void Reset () override
void EnterCombat (Unit *) override
void JustReachedHome () override
void MoveInLineOfSight (Unit *) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void JustSummoned (Creature *summon) override
void DoAction (int32 param) override
void EnterEvadeMode () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
EventMap events
SummonList summons
ObjectGuid PlayerGUID
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 238 of file boss_northrend_beasts.cpp.
Constructor & Destructor Documentation
boss_gormokAI()
boss_gormok::boss_gormokAI::boss_gormokAI (Creature * pCreature) inline
Definition at line 240 of file boss_northrend_beasts.cpp.
                                            : ScriptedAI(pCreature), summons(pCreature)
         {
             pInstance = pCreature->GetInstanceScript();
             me->AddUnitMovementFlag(MOVEMENTFLAG_WALKING);
             me->SetReactState(REACT_PASSIVE);
         }
References Unit::AddUnitMovementFlag(), WorldObject::GetInstanceScript(), ScriptedAI::me, MOVEMENTFLAG_WALKING, pInstance, REACT_PASSIVE, and Creature::SetReactState().
Member Function Documentation
DoAction()
void boss_gormok::boss_gormokAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 395 of file boss_northrend_beasts.cpp.
         {
             switch( param )
             {
                 case -1:
                     summons.DespawnAll();
                     break;
             }
         }
References SummonList::DespawnAll(), and summons.
EnterCombat()
void boss_gormok::boss_gormokAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 259 of file boss_northrend_beasts.cpp.
         {
             me->setActive(true);
             events.Reset();
             events.RescheduleEvent(EVENT_SPELL_IMPALE, urand(9000, 10000));
             events.RescheduleEvent(EVENT_SPELL_STAGGERING_STOMP, 15000);
             events.RescheduleEvent(EVENT_PICK_SNOBOLD_TARGET, urand(16000, 24000));
             // refresh snobold position
             if( Vehicle* vk = me->GetVehicleKit() )
                 for( uint8 i = 0; i < 4; ++i )
                     if( Unit* snobold = vk->GetPassenger(i) )
                         snobold->SendMovementFlagUpdate();
         }
References EVENT_PICK_SNOBOLD_TARGET, EVENT_SPELL_IMPALE, EVENT_SPELL_STAGGERING_STOMP, Unit::GetVehicleKit(), ScriptedAI::me, WorldObject::setActive(), and urand().
EnterEvadeMode()
void boss_gormok::boss_gormokAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 405 of file boss_northrend_beasts.cpp.
         {
             events.Reset();
             summons.DespawnAll();
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
             if( pInstance )
                 pInstance->SetData(TYPE_FAILED, 1);
         }
References SummonList::DespawnAll(), ScriptedAI::me, pInstance, ZoneScript::SetData(), Object::SetFlag(), summons, TYPE_FAILED, UNIT_FIELD_FLAGS, and UNIT_FLAG_NON_ATTACKABLE.
JustDied()
void boss_gormok::boss_gormokAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 382 of file boss_northrend_beasts.cpp.
         {
             summons.DoAction(1);
             if( pInstance )
                 pInstance->SetData(TYPE_GORMOK, DONE);
         }
References SummonList::DoAction(), DONE, pInstance, ZoneScript::SetData(), summons, and TYPE_GORMOK.
JustReachedHome()
void boss_gormok::boss_gormokAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 274 of file boss_northrend_beasts.cpp.
         {
             me->setActive(false);
         }
References ScriptedAI::me, and WorldObject::setActive().
JustSummoned()
void boss_gormok::boss_gormokAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 390 of file boss_northrend_beasts.cpp.
         {
             summons.Summon(summon);
         }
References SummonList::Summon(), and summons.
MoveInLineOfSight()
void boss_gormok::boss_gormokAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 279 of file boss_northrend_beasts.cpp.
 {}
Reset()
void boss_gormok::boss_gormokAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 252 of file boss_northrend_beasts.cpp.
         {
             events.Reset();
             summons.DespawnAll();
             PlayerGUID.Clear();
         }
References ObjectGuid::Clear(), SummonList::DespawnAll(), PlayerGUID, and summons.
UpdateAI()
void boss_gormok::boss_gormokAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 281 of file boss_northrend_beasts.cpp.
         {
             if( !UpdateVictim() )
                 return;
             events.Update(diff);
             if( me->HasUnitState(UNIT_STATE_CASTING) )
                 return;
             switch( events.ExecuteEvent() )
             {
                 case 0:
                     break;
                 case EVENT_SPELL_IMPALE:
                     if( !me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_DISARMED) )
                     {
                         if( Unit* victim = me->GetVictim() )
                             me->CastSpell(victim, SPELL_IMPALE, false);
                         events.RepeatEvent(urand(9000, 10000));
                     }
                     else
                         events.RepeatEvent(2500);
                     break;
                 case EVENT_SPELL_STAGGERING_STOMP:
                     me->CastSpell((Unit*)nullptr, SPELL_STAGGERING_STOMP, false);
                     events.RepeatEvent(urand(20000, 25000));
                     break;
                 case EVENT_PICK_SNOBOLD_TARGET:
                     if( Vehicle* vk = me->GetVehicleKit() )
                         for( uint8 i = 0; i < 4; ++i )
                             if( Unit* snobold = vk->GetPassenger(i) )
{
                                 GuidVector validPlayers;
                                 Map::PlayerList const& pl = me->GetMap()->GetPlayers();
                                 for( Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr )
{
                                     if( Player* p = itr->GetSource() )
                                         if( p->IsAlive() && !p->GetVehicleKit() && !p->IsMounted() && !p->GetVehicle() && !p->IsGameMaster() )
                                             validPlayers.push_back(p->GetGUID());
                                 }
                                 if( !validPlayers.empty() )
                                     if( Player* p = ObjectAccessor::GetPlayer(*me, validPlayers.at(urand(0, validPlayers.size() - 1))) )
{
                                         snobold->ChangeSeat(4); // switch to hand
                                         me->setAttackTimer(BASE_ATTACK, 3000);
                                         PlayerGUID = p->GetGUID();
                                         events.RescheduleEvent(EVENT_RELEASE_SNOBOLD, 2500);
                                     }
                                 break;
                             }
                     events.RepeatEvent(urand(16000, 24000));
                     break;
                 case EVENT_RELEASE_SNOBOLD:
                     {
                         me->CastSpell(me, SPELL_RISING_ANGER, true);
                         Player* p = ObjectAccessor::GetPlayer(*me, PlayerGUID);
                         if( p && p->IsAlive() && !p->GetVehicleKit() && !p->IsMounted() && !p->GetVehicle() )
{
                             if( Vehicle* vk = me->GetVehicleKit() )
                                 if( Unit* snobold = vk->GetPassenger(4) )
{
                                     if( snobold->GetTypeId() == TYPEID_UNIT )
{
                                         CAST_AI(npc_snobold_vassal::npc_snobold_vassalAI, snobold->ToCreature()->AI())->TargetGUID = PlayerGUID;
                                         snobold->ToCreature()->AI()->AttackStart(p);
                                     }
                                     //Talk(EMOTE_SNOBOLLED);
                                     p->CastSpell(p, SPELL_CHANGE_VEHICLE, true);
                                     snobold->EnterVehicle(p, 0);
                                     //snobold->ClearUnitState(UNIT_STATE_ONVEHICLE);
                                 }
                         }
                         else if( Vehicle* vk = me->GetVehicleKit() )
{
                             events.RescheduleEvent(EVENT_PICK_SNOBOLD_TARGET, 5000); // player not found (died? left instance?), pick new one faster!
                             if( Unit* snobold = vk->GetPassenger(4) )
                                 if( snobold->GetTypeId() == TYPEID_UNIT )
{
                                     bool needDespawn = true;
                                     for( uint8 i = 0; i < 4; ++i )
                                         if( !vk->GetPassenger(i) )
{
                                             snobold->ChangeSeat(i);
                                             needDespawn = false;
                                             break;
                                         }
                                     if( needDespawn )
                                         snobold->ToCreature()->DespawnOrUnsummon();
                                 }
                         }
                         PlayerGUID.Clear();
                     }
                     break;
             }
             DoMeleeAttackIfReady();
         }
References BASE_ATTACK, MapRefMgr::begin(), CAST_AI, Unit::CastSpell(), ObjectGuid::Clear(), UnitAI::DoMeleeAttackIfReady(), MapRefMgr::end(), EVENT_PICK_SNOBOLD_TARGET, EVENT_RELEASE_SNOBOLD, EVENT_SPELL_IMPALE, EVENT_SPELL_STAGGERING_STOMP, WorldObject::GetMap(), ObjectAccessor::GetPlayer(), Map::GetPlayers(), Unit::GetVehicle(), Unit::GetVehicleKit(), Unit::GetVictim(), Object::HasFlag(), Unit::HasUnitState(), Unit::IsAlive(), Unit::IsMounted(), ScriptedAI::me, PlayerGUID, Unit::setAttackTimer(), SPELL_CHANGE_VEHICLE, SPELL_IMPALE, SPELL_RISING_ANGER, SPELL_STAGGERING_STOMP, TYPEID_UNIT, UNIT_FIELD_FLAGS, UNIT_FLAG_DISARMED, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
events
EventMap boss_gormok::boss_gormokAI::events
Definition at line 248 of file boss_northrend_beasts.cpp.
pInstance
InstanceScript* boss_gormok::boss_gormokAI::pInstance
Definition at line 247 of file boss_northrend_beasts.cpp.
Referenced by boss_gormokAI(), EnterEvadeMode(), and JustDied().
PlayerGUID
ObjectGuid boss_gormok::boss_gormokAI::PlayerGUID
Definition at line 250 of file boss_northrend_beasts.cpp.
Referenced by Reset(), and UpdateAI().
summons
SummonList boss_gormok::boss_gormokAI::summons
Definition at line 249 of file boss_northrend_beasts.cpp.
Referenced by DoAction(), EnterEvadeMode(), JustDied(), JustSummoned(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheCrusader/boss_northrend_beasts.cpp