Azerotcore-wotlk: RestoreAttack Class Reference
RestoreAttack Class Reference
Public Member Functions
RestoreAttack (Creature *boss)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()
virtual ~BasicEvent ()
virtual bool IsDeletable () const
virtual void Abort (uint64)
void ScheduleAbort ()
Private Attributes
Creature * _boss
Detailed Description
Definition at line 86 of file instance_blackrock_depths.cpp.
Constructor & Destructor Documentation
RestoreAttack()
RestoreAttack::RestoreAttack (Creature * boss) inline
Definition at line 89 of file instance_blackrock_depths.cpp.
 : _boss(boss) {}
Member Function Documentation
Execute()
bool RestoreAttack::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
Definition at line 91 of file instance_blackrock_depths.cpp.
     {
         _boss->SetReactState(REACT_AGGRESSIVE);
         _boss->AI()->SetData(DATA_GOLEM_LORD_ARGELMACH_INIT, DONE);
         if (Unit* victim = _boss->GetVictim())
         {
             _boss->SetTarget(victim->GetGUID());
             _boss->GetMotionMaster()->MoveChase(victim);
         }
         return true;
     }
References _boss, Creature::AI(), DATA_GOLEM_LORD_ARGELMACH_INIT, DONE, Unit::GetMotionMaster(), Unit::GetVictim(), MotionMaster::MoveChase(), REACT_AGGRESSIVE, UnitAI::SetData(), Creature::SetReactState(), and Creature::SetTarget().
Member Data Documentation
_boss
Creature* RestoreAttack::_boss private
Definition at line 106 of file instance_blackrock_depths.cpp.
Referenced by Execute().
The documentation for this class was generated from the following file:
src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/instance_blackrock_depths.cpp