Azerotcore-wotlk: ObjectGuidGeneratorBase Class Reference
ObjectGuidGeneratorBase Class Reference abstract
#include <ObjectGuid.h>
Public Member Functions
ObjectGuidGeneratorBase (ObjectGuid::LowType start=1)
virtual void Set (ObjectGuid::LowType val)
virtual ObjectGuid::LowType Generate ()=0
ObjectGuid::LowType GetNextAfterMaxUsed () const
virtual ~ObjectGuidGeneratorBase ()
Static Protected Member Functions
static void HandleCounterOverflow (HighGuid high)
Protected Attributes
ObjectGuid::LowType _nextGuid
Detailed Description
Definition at line 282 of file ObjectGuid.h.
Constructor & Destructor Documentation
ObjectGuidGeneratorBase()
ObjectGuidGeneratorBase::ObjectGuidGeneratorBase (ObjectGuid::LowType start = 1) inline
Definition at line 285 of file ObjectGuid.h.
 : _nextGuid(start) { }
~ObjectGuidGeneratorBase()
virtual ObjectGuidGeneratorBase::~ObjectGuidGeneratorBase () inline virtual
Definition at line 290 of file ObjectGuid.h.
 { }
Member Function Documentation
Generate()
virtual ObjectGuid::LowType ObjectGuidGeneratorBase::Generate () pure virtual
Implemented in ObjectGuidGenerator< high >.
GetNextAfterMaxUsed()
ObjectGuid::LowType ObjectGuidGeneratorBase::GetNextAfterMaxUsed () const inline
Definition at line 289 of file ObjectGuid.h.
 { return _nextGuid; }
References _nextGuid.
HandleCounterOverflow()
void ObjectGuidGeneratorBase::HandleCounterOverflow (HighGuid high) static protected
Definition at line 93 of file ObjectGuid.cpp.
 {
     LOG_ERROR("entities.object", "%s guid overflow!! Can't continue, shutting down server. ", ObjectGuid::GetTypeName(high));
     World::StopNow(ERROR_EXIT_CODE);
 }
References ERROR_EXIT_CODE, ObjectGuid::GetTypeName(), LOG_ERROR, and World::StopNow().
Referenced by ObjectGuidGenerator< high >::Generate().
Set()
virtual void ObjectGuidGeneratorBase::Set (ObjectGuid::LowType val) inline virtual
Definition at line 287 of file ObjectGuid.h.
 { _nextGuid = val; }
References _nextGuid.
Member Data Documentation
_nextGuid
ObjectGuid::LowType ObjectGuidGeneratorBase::_nextGuid protected
Definition at line 294 of file ObjectGuid.h.
Referenced by ObjectGuidGenerator< high >::Generate(), GetNextAfterMaxUsed(), and Set().
The documentation for this class was generated from the following files:
src/server/game/Entities/Object/ObjectGuid.h
src/server/game/Entities/Object/ObjectGuid.cpp