Azerotcore-wotlk: MMapTargetData Class Reference
MMapTargetData Class Reference
#include <Unit.h>
Public Member Functions
MMapTargetData ()=default
MMapTargetData (uint32 endTime, const Position *o, const Position *t)
MMapTargetData (const MMapTargetData &c)
bool PosChanged (const Position &o, const Position &t) const
Public Attributes
uint32 _endTime
Position _posOwner
Position _posTarget
Detailed Description
Definition at line 1370 of file Unit.h.
Constructor & Destructor Documentation
MMapTargetData() [1/3]
MMapTargetData::MMapTargetData () default
MMapTargetData() [2/3]
MMapTargetData::MMapTargetData (uint32 endTime, const Position * o, const Position * t) inline
Definition at line 1374 of file Unit.h.
     {
         _endTime = endTime;
         _posOwner.Relocate(o);
         _posTarget.Relocate(t);
     }
References _endTime, _posOwner, _posTarget, and Position::Relocate().
MMapTargetData() [3/3]
MMapTargetData::MMapTargetData (const MMapTargetData & c) inline
Definition at line 1380 of file Unit.h.
     {
         _endTime = c._endTime;
         _posOwner.Relocate(c._posOwner);
         _posTarget.Relocate(c._posTarget);
     }
References _endTime, _posOwner, _posTarget, and Position::Relocate().
Member Function Documentation
PosChanged()
bool MMapTargetData::PosChanged (const Position & o, const Position & t) const inline
Definition at line 1392 of file Unit.h.
     {
         return _posOwner.GetExactDistSq(&o) > 0.5f * 0.5f || _posTarget.GetExactDistSq(&t) > 0.5f * 0.5f;
     }
References _posOwner, _posTarget, and Position::GetExactDistSq().
Member Data Documentation
_endTime
uint32 MMapTargetData::_endTime
Definition at line 1396 of file Unit.h.
Referenced by MMapTargetData().
_posOwner
Position MMapTargetData::_posOwner
Definition at line 1397 of file Unit.h.
Referenced by MMapTargetData(), and PosChanged().
_posTarget
Position MMapTargetData::_posTarget
Definition at line 1398 of file Unit.h.
Referenced by MMapTargetData(), and PosChanged().
The documentation for this class was generated from the following file:
src/server/game/Entities/Unit/Unit.h