Azerotcore-wotlk: DialogueHelper Class Reference
DialogueHelper Class Reference
Public Member Functions
DialogueHelper (DialogueEntry const *dialogueArray)
void StartNextDialogueText (int32 textEntry)
void DialogueUpdate (uint32 diff)
Protected Member Functions
virtual void JustDidDialogueStep (int32)
Will be called when a dialogue step was done.
virtual Creature * GetSpeakerByEntry (int32)
Will be called to get a speaker, MUST be implemented if not used in instances.
Private Member Functions
void DoNextDialogueStep ()
Private Attributes
DialogueEntry const * _dialogueArray
DialogueEntry const * _currentEntry
uint32 _actionTimer
Detailed Description
Definition at line 154 of file zone_winterspring.cpp.
Constructor & Destructor Documentation
DialogueHelper()
DialogueHelper::DialogueHelper (DialogueEntry const * dialogueArray) inline
Definition at line 158 of file zone_winterspring.cpp.
                                                        :
         _dialogueArray(dialogueArray),
         _currentEntry(nullptr),
         _actionTimer(0)
     { }
Member Function Documentation
DialogueUpdate()
void DialogueHelper::DialogueUpdate (uint32 diff) inline
Definition at line 189 of file zone_winterspring.cpp.
     {
         if (_actionTimer)
         {
             if (_actionTimer <= diff)
                 DoNextDialogueStep();
             else
                 _actionTimer -= diff;
         }
     }
References _actionTimer, and DoNextDialogueStep().
Referenced by npc_ranshalla::npc_ranshallaAI::UpdateEscortAI().
DoNextDialogueStep()
void DialogueHelper::DoNextDialogueStep () inline private
Definition at line 207 of file zone_winterspring.cpp.
     {
         // Last Dialogue Entry done?
         if (!_currentEntry || !_currentEntry->TextEntry)
         {
             _actionTimer = 0;
             return;
         }
         // Get Text, SpeakerEntry and Timer
         int32 textEntry = _currentEntry->TextEntry;
         uint32 sayerEntry = _currentEntry->SayerEntry;
         _actionTimer = _currentEntry->SayTimer;
         // Simulate Case
         if (sayerEntry && textEntry >= 0)
         {
             // Use Speaker if directly provided
             if (Creature* speaker = GetSpeakerByEntry(sayerEntry))
                 speaker->AI()->Talk(textEntry);
         }
         JustDidDialogueStep(_currentEntry->TextEntry);
         // Increment position
         ++_currentEntry;
     }
References _actionTimer, _currentEntry, GetSpeakerByEntry(), JustDidDialogueStep(), DialogueEntry::SayerEntry, DialogueEntry::SayTimer, and DialogueEntry::TextEntry.
Referenced by DialogueUpdate(), and StartNextDialogueText().
GetSpeakerByEntry()
virtual Creature* DialogueHelper::GetSpeakerByEntry (int32) inline protected virtual
Will be called to get a speaker, MUST be implemented if not used in instances.
Reimplemented in npc_ranshalla::npc_ranshallaAI.
Definition at line 204 of file zone_winterspring.cpp.
 { return nullptr; }
Referenced by DoNextDialogueStep().
JustDidDialogueStep()
virtual void DialogueHelper::JustDidDialogueStep (int32) inline protected virtual
Will be called when a dialogue step was done.
Reimplemented in npc_ranshalla::npc_ranshallaAI.
Definition at line 202 of file zone_winterspring.cpp.
 { }
Referenced by DoNextDialogueStep().
StartNextDialogueText()
void DialogueHelper::StartNextDialogueText (int32 textEntry) inline
Function to initialize the dialogue helper for instances. If not used with instances, GetSpeakerByEntry MUST be overwritten to obtain the speakers Set if take first entries or second entries
Definition at line 168 of file zone_winterspring.cpp.
     {
         // Find textEntry
         bool found = false;
         for (DialogueEntry const* entry = _dialogueArray; entry->TextEntry; ++entry)
         {
             if (entry->TextEntry == textEntry)
             {
                 _currentEntry = entry;
                 found = true;
                 break;
             }
         }
         if (!found)
             return;
         DoNextDialogueStep();
     }
References _currentEntry, _dialogueArray, DoNextDialogueStep(), and DialogueEntry::TextEntry.
Referenced by npc_ranshalla::npc_ranshallaAI::SummonedMovementInform(), npc_ranshalla::npc_ranshallaAI::UpdateEscortAI(), and npc_ranshalla::npc_ranshallaAI::WaypointReached().
Member Data Documentation
_actionTimer
uint32 DialogueHelper::_actionTimer private
Definition at line 238 of file zone_winterspring.cpp.
Referenced by DialogueUpdate(), and DoNextDialogueStep().
_currentEntry
DialogueEntry const* DialogueHelper::_currentEntry private
Definition at line 236 of file zone_winterspring.cpp.
Referenced by DoNextDialogueStep(), and StartNextDialogueText().
_dialogueArray
DialogueEntry const* DialogueHelper::_dialogueArray private
Definition at line 235 of file zone_winterspring.cpp.
Referenced by StartNextDialogueText().
The documentation for this class was generated from the following file:
src/server/scripts/Kalimdor/zone_winterspring.cpp