Azerotcore-wotlk: deps/argon2/argon2/ref.c File Reference
ref.c File Reference
#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "argon2.h"
#include "core.h"
#include "blake2/blamka-round-ref.h"
#include "blake2/blake2-impl.h"
#include "blake2/blake2.h"
Functions
static void fill_block (const block *prev_block, const block *ref_block, block *next_block, int with_xor)
static void next_addresses (block *address_block, block *input_block, const block *zero_block)
void fill_segment (const argon2_instance_t *instance, argon2_position_t position)
Function Documentation
fill_block()
static void fill_block (const block * prev_block, const block * ref_block, block * next_block, int with_xor) static
Definition at line 39 of file ref.c.
{
     block blockR, block_tmp;
     unsigned i;
     copy_block(&blockR, ref_block);
     xor_block(&blockR, prev_block);
     copy_block(&block_tmp, &blockR);
     /* Now blockR = ref_block + prev_block and block_tmp = ref_block + prev_block */
     if (with_xor) {
         /* Saving the next block contents for XOR over: */
         xor_block(&block_tmp, next_block);
         /* Now blockR = ref_block + prev_block and
            block_tmp = ref_block + prev_block + next_block */
     }
     /* Apply Blake2 on columns of 64-bit words: (0,1,...,15) , then
        (16,17,..31)... finally (112,113,...127) */
     for (i = 0; i < 8; ++i) {
         BLAKE2_ROUND_NOMSG(
             blockR.v[16 * i], blockR.v[16 * i + 1], blockR.v[16 * i + 2],
             blockR.v[16 * i + 3], blockR.v[16 * i + 4], blockR.v[16 * i + 5],
             blockR.v[16 * i + 6], blockR.v[16 * i + 7], blockR.v[16 * i + 8],
             blockR.v[16 * i + 9], blockR.v[16 * i + 10], blockR.v[16 * i + 11],
             blockR.v[16 * i + 12], blockR.v[16 * i + 13], blockR.v[16 * i + 14],
             blockR.v[16 * i + 15]);
     }
     /* Apply Blake2 on rows of 64-bit words: (0,1,16,17,...112,113), then
        (2,3,18,19,...,114,115).. finally (14,15,30,31,...,126,127) */
     for (i = 0; i < 8; i++) {
         BLAKE2_ROUND_NOMSG(
             blockR.v[2 * i], blockR.v[2 * i + 1], blockR.v[2 * i + 16],
             blockR.v[2 * i + 17], blockR.v[2 * i + 32], blockR.v[2 * i + 33],
             blockR.v[2 * i + 48], blockR.v[2 * i + 49], blockR.v[2 * i + 64],
             blockR.v[2 * i + 65], blockR.v[2 * i + 80], blockR.v[2 * i + 81],
             blockR.v[2 * i + 96], blockR.v[2 * i + 97], blockR.v[2 * i + 112],
             blockR.v[2 * i + 113]);
     }
     copy_block(next_block, &block_tmp);
     xor_block(next_block, &blockR);
 }
References BLAKE2_ROUND_NOMSG, copy_block(), block_::v, and xor_block().
Referenced by fill_segment(), and next_addresses().
fill_segment()
void fill_segment (const argon2_instance_t * instance, argon2_position_t position)
Definition at line 90 of file ref.c.
{
     block *ref_block = NULL, *curr_block = NULL;
     block address_block, input_block, zero_block;
     uint64_t pseudo_rand, ref_index, ref_lane;
     uint32_t prev_offset, curr_offset;
     uint32_t starting_index;
     uint32_t i;
     int data_independent_addressing;
     if (instance == NULL) {
         return;
     }
     data_independent_addressing =
         (instance->type == Argon2_i) ||
         (instance->type == Argon2_id && (position.pass == 0) &&
          (position.slice < ARGON2_SYNC_POINTS / 2));
     if (data_independent_addressing) {
         init_block_value(&zero_block, 0);
         init_block_value(&input_block, 0);
         input_block.v[0] = position.pass;
         input_block.v[1] = position.lane;
         input_block.v[2] = position.slice;
         input_block.v[3] = instance->memory_blocks;
         input_block.v[4] = instance->passes;
         input_block.v[5] = instance->type;
     }
     starting_index = 0;
     if ((0 == position.pass) && (0 == position.slice)) {
         starting_index = 2; /* we have already generated the first two blocks */
         /* Don't forget to generate the first block of addresses: */
         if (data_independent_addressing) {
             next_addresses(&address_block, &input_block, &zero_block);
         }
     }
     /* Offset of the current block */
     curr_offset = position.lane * instance->lane_length +
                   position.slice * instance->segment_length + starting_index;
     if (0 == curr_offset % instance->lane_length) {
         /* Last block in this lane */
         prev_offset = curr_offset + instance->lane_length - 1;
     } else {
         /* Previous block */
         prev_offset = curr_offset - 1;
     }
     for (i = starting_index; i < instance->segment_length;
          ++i, ++curr_offset, ++prev_offset) {
         /*1.1 Rotating prev_offset if needed */
         if (curr_offset % instance->lane_length == 1) {
             prev_offset = curr_offset - 1;
         }
         /* 1.2 Computing the index of the reference block */
         /* 1.2.1 Taking pseudo-random value from the previous block */
         if (data_independent_addressing) {
             if (i % ARGON2_ADDRESSES_IN_BLOCK == 0) {
                 next_addresses(&address_block, &input_block, &zero_block);
             }
             pseudo_rand = address_block.v[i % ARGON2_ADDRESSES_IN_BLOCK];
         } else {
             pseudo_rand = instance->memory[prev_offset].v[0];
         }
         /* 1.2.2 Computing the lane of the reference block */
         ref_lane = ((pseudo_rand >> 32)) % instance->lanes;
         if ((position.pass == 0) && (position.slice == 0)) {
             /* Can not reference other lanes yet */
             ref_lane = position.lane;
         }
         /* 1.2.3 Computing the number of possible reference block within the
          * lane.
          */
         position.index = i;
         ref_index = index_alpha(instance, &position, pseudo_rand & 0xFFFFFFFF,
                                 ref_lane == position.lane);
         /* 2 Creating a new block */
         ref_block =
             instance->memory + instance->lane_length * ref_lane + ref_index;
         curr_block = instance->memory + curr_offset;
         if (ARGON2_VERSION_10 == instance->version) {
             /* version 1.2.1 and earlier: overwrite, not XOR */
             fill_block(instance->memory + prev_offset, ref_block, curr_block, 0);
         } else {
             if(0 == position.pass) {
                 fill_block(instance->memory + prev_offset, ref_block,
                            curr_block, 0);
             } else {
                 fill_block(instance->memory + prev_offset, ref_block,
                            curr_block, 1);
             }
         }
     }
 }
References ARGON2_512BIT_WORDS_IN_BLOCK, ARGON2_ADDRESSES_IN_BLOCK, ARGON2_BLOCK_SIZE, ARGON2_HWORDS_IN_BLOCK, Argon2_i, Argon2_id, ARGON2_OWORDS_IN_BLOCK, ARGON2_SYNC_POINTS, ARGON2_VERSION_10, fill_block(), Argon2_position_t::index, index_alpha(), init_block_value(), Argon2_position_t::lane, Argon2_instance_t::lane_length, Argon2_instance_t::lanes, memcpy, Argon2_instance_t::memory, Argon2_instance_t::memory_blocks, next_addresses(), NULL, Argon2_position_t::pass, Argon2_instance_t::passes, Argon2_instance_t::segment_length, Argon2_position_t::slice, Argon2_instance_t::type, block_::v, and Argon2_instance_t::version.
Referenced by fill_memory_blocks_st(), and fill_segment_thr().
next_addresses()
static void next_addresses (block * address_block, block * input_block, const block * zero_block) static
Definition at line 83 of file ref.c.
{
     input_block->v[6]++;
     fill_block(zero_block, input_block, address_block, 0);
     fill_block(zero_block, address_block, address_block, 0);
 }
References fill_block(), and block_::v.
Referenced by fill_segment().