Azerotcore-wotlk: boss_arlokk::boss_arlokkAI Struct Reference
boss_arlokk::boss_arlokkAI Struct Reference
Public Member Functions
boss_arlokkAI (Creature *creature)
void Reset () override
void JustDied (Unit *) override
void EnterCombat (Unit *) override
void EnterEvadeMode () override
void SetData (uint32 id, uint32) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void KilledUnit (Unit *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
uint8 _summonCountA
uint8 _summonCountB
ObjectGuid _triggersSideAGUID [5]
ObjectGuid _triggersSideBGUID [5]
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 94 of file boss_arlokk.cpp.
Constructor & Destructor Documentation
boss_arlokkAI()
boss_arlokk::boss_arlokkAI::boss_arlokkAI (Creature * creature) inline
Definition at line 96 of file boss_arlokk.cpp.
 : BossAI(creature, DATA_ARLOKK) { }
Member Function Documentation
EnterCombat()
void boss_arlokk::boss_arlokkAI::EnterCombat (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 117 of file boss_arlokk.cpp.
         {
             _EnterCombat();
             events.ScheduleEvent(EVENT_SHADOW_WORD_PAIN, urand(7000, 9000), 0, PHASE_ONE);
             events.ScheduleEvent(EVENT_GOUGE, urand(12000, 15000), 0, PHASE_ONE);
             events.ScheduleEvent(EVENT_SUMMON_PROWLERS, 6000, 0, PHASE_ALL);
             events.ScheduleEvent(EVENT_MARK_OF_ARLOKK, urand(9000, 11000), 0, PHASE_ALL);
             events.ScheduleEvent(EVENT_TRANSFORM, urand(15000, 20000), 0, PHASE_ONE);
             Talk(SAY_AGGRO);
             // Sets up list of Panther spawners to cast on
             std::list<Creature*> triggerList;
             GetCreatureListWithEntryInGrid(triggerList, me, NPC_PANTHER_TRIGGER, 100.0f);
             if (!triggerList.empty())
             {
                 uint8 sideA = 0;
                 uint8 sideB = 0;
                 for (std::list<Creature*>::const_iterator itr = triggerList.begin(); itr != triggerList.end(); ++itr)
                 {
                     if (Creature* trigger = *itr)
                     {
                         if (trigger->GetPositionY() < -1625.0f)
{
                             _triggersSideAGUID[sideA] = trigger->GetGUID();
                             ++sideA;
                         }
                         else
{
                             _triggersSideBGUID[sideB] = trigger->GetGUID();
                             ++sideB;
                         }
                     }
                 }
             }
         }
References BossAI::_EnterCombat(), _triggersSideAGUID, _triggersSideBGUID, EVENT_GOUGE, EVENT_MARK_OF_ARLOKK, EVENT_SHADOW_WORD_PAIN, EVENT_SUMMON_PROWLERS, EVENT_TRANSFORM, GetCreatureListWithEntryInGrid(), ScriptedAI::me, NPC_PANTHER_TRIGGER, PHASE_ALL, PHASE_ONE, SAY_AGGRO, CreatureAI::Talk(), and urand().
EnterEvadeMode()
void boss_arlokk::boss_arlokkAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 153 of file boss_arlokk.cpp.
         {
             BossAI::EnterEvadeMode();
             if (GameObject* object = ObjectAccessor::GetGameObject(*me, instance->GetGuidData(GO_GONG_OF_BETHEKK)))
                 object->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_NOT_SELECTABLE);
             me->DespawnOrUnsummon(4000);
         }
References Creature::DespawnOrUnsummon(), CreatureAI::EnterEvadeMode(), GAMEOBJECT_FLAGS, ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), GO_FLAG_NOT_SELECTABLE, GO_GONG_OF_BETHEKK, BossAI::instance, and ScriptedAI::me.
JustDied()
void boss_arlokk::boss_arlokkAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 111 of file boss_arlokk.cpp.
         {
             _JustDied();
             Talk(SAY_DEATH);
         }
References BossAI::_JustDied(), SAY_DEATH, and CreatureAI::Talk().
Reset()
void boss_arlokk::boss_arlokkAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 98 of file boss_arlokk.cpp.
         {
             if (events.IsInPhase(PHASE_TWO))
                 me->HandleStatModifier(UNIT_MOD_DAMAGE_MAINHAND, TOTAL_PCT, 35.0f, false); // hack
             _Reset();
             _summonCountA = 0;
             _summonCountB = 0;
             me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 0, uint32(WEAPON_DAGGER));
             me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 1, uint32(WEAPON_DAGGER));
             me->SetWalk(false);
             me->GetMotionMaster()->MovePoint(0, PosMoveOnSpawn[0]);
         }
References BossAI::_Reset(), _summonCountA, _summonCountB, Unit::GetMotionMaster(), Unit::HandleStatModifier(), ScriptedAI::me, MotionMaster::MovePoint(), PHASE_TWO, PosMoveOnSpawn, Object::SetUInt32Value(), Creature::SetWalk(), TOTAL_PCT, UNIT_MOD_DAMAGE_MAINHAND, UNIT_VIRTUAL_ITEM_SLOT_ID, and WEAPON_DAGGER.
SetData()
void boss_arlokk::boss_arlokkAI::SetData (uint32 id, uint32) inline override virtual
Reimplemented from UnitAI.
Definition at line 161 of file boss_arlokk.cpp.
         {
             if (id == 1)
                 --_summonCountA;
             else if (id == 2)
                 --_summonCountB;
         }
References _summonCountA, and _summonCountB.
UpdateAI()
void boss_arlokk::boss_arlokkAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 169 of file boss_arlokk.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             while (uint32 eventId = events.ExecuteEvent())
             {
                 switch (eventId)
                 {
                     case EVENT_SHADOW_WORD_PAIN:
                         DoCastVictim(SPELL_SHADOW_WORD_PAIN, true);
                         events.ScheduleEvent(EVENT_SHADOW_WORD_PAIN, urand(5000, 7000), 0, PHASE_ONE);
                         break;
                     case EVENT_GOUGE:
                         DoCastVictim(SPELL_GOUGE, true);
                         break;
                     case EVENT_SUMMON_PROWLERS:
                         if (_summonCountA < MAX_PROWLERS_PER_SIDE)
{
                             if (Unit* trigger = ObjectAccessor::GetUnit(*me, _triggersSideAGUID[urand(0, 4)]))
{
                                 trigger->CastSpell(trigger, SPELL_SUMMON_PROWLER);
                                 ++_summonCountA;
                             }
                         }
                         if (_summonCountB < MAX_PROWLERS_PER_SIDE)
{
                             if (Unit* trigger = ObjectAccessor::GetUnit(*me, _triggersSideBGUID[urand(0, 4)]))
{
                                 trigger->CastSpell(trigger, SPELL_SUMMON_PROWLER);
                                 ++_summonCountB;
                             }
                         }
                         events.ScheduleEvent(EVENT_SUMMON_PROWLERS, 6000, 0, PHASE_ALL);
                         break;
                     case EVENT_MARK_OF_ARLOKK:
{
                             Unit* target = SelectTarget(SELECT_TARGET_TOPAGGRO, urand(1, 3), 0.0f, false, -SPELL_MARK_OF_ARLOKK);
                             if (!target)
                                 target = me->GetVictim();
                             if (target)
{
                                 DoCast(target, SPELL_MARK_OF_ARLOKK, true);
                                 Talk(SAY_FEAST_PROWLER, target);
                             }
                             events.ScheduleEvent(EVENT_MARK_OF_ARLOKK, urand(120000, 130000));
                             break;
                         }
                     case EVENT_TRANSFORM:
{
                             DoCast(me, SPELL_PANTHER_TRANSFORM); // SPELL_AURA_TRANSFORM
                             me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 0, uint32(EQUIP_UNEQUIP));
                             me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 1, uint32(EQUIP_UNEQUIP));
                             /*
                             const CreatureTemplate* cinfo = me->GetCreatureTemplate();
                             me->SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, (cinfo->mindmg +((cinfo->mindmg/100) * 35)));
                             me->SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, (cinfo->maxdmg +((cinfo->maxdmg/100) * 35)));
                             me->UpdateDamagePhysical(BASE_ATTACK);
                             */
                             me->AttackStop();
                             DoResetThreat();
                             me->SetReactState(REACT_PASSIVE);
                             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE);
                             DoCast(me, SPELL_VANISH_VISUAL);
                             DoCast(me, SPELL_VANISH);
                             events.ScheduleEvent(EVENT_VANISH, 1000, 0, PHASE_ONE);
                             break;
                         }
                     case EVENT_VANISH:
                         DoCast(me, SPELL_SUPER_INVIS);
                         me->SetWalk(false);
                         me->GetMotionMaster()->MovePoint(0, frand(-11551.0f, -11508.0f), frand(-1638.0f, -1617.0f), me->GetPositionZ());
                         events.ScheduleEvent(EVENT_VANISH_2, 9000, 0, PHASE_ONE);
                         break;
                     case EVENT_VANISH_2:
                         DoCast(me, SPELL_VANISH);
                         DoCast(me, SPELL_SUPER_INVIS);
                         events.ScheduleEvent(EVENT_VISIBLE, urand(7000, 10000), 0, PHASE_ONE);
                         break;
                     case EVENT_VISIBLE:
                         me->SetReactState(REACT_AGGRESSIVE);
                         me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE);
                         if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
                             AttackStart(target);
                         me->RemoveAura(SPELL_SUPER_INVIS);
                         me->RemoveAura(SPELL_VANISH);
                         events.ScheduleEvent(EVENT_RAVAGE, urand(10000, 14000), 0, PHASE_TWO);
                         events.ScheduleEvent(EVENT_TRANSFORM_BACK, urand(15000, 18000), 0, PHASE_TWO);
                         events.SetPhase(PHASE_TWO);
                         me->HandleStatModifier(UNIT_MOD_DAMAGE_MAINHAND, TOTAL_PCT, 35.0f, true); // hack
                         break;
                     case EVENT_RAVAGE:
                         DoCastVictim(SPELL_RAVAGE, true);
                         events.ScheduleEvent(EVENT_RAVAGE, urand(10000, 14000), 0, PHASE_TWO);
                         break;
                     case EVENT_TRANSFORM_BACK:
{
                             me->RemoveAura(SPELL_PANTHER_TRANSFORM); // SPELL_AURA_TRANSFORM
                             DoCast(me, SPELL_VANISH_VISUAL);
                             me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 0, uint32(WEAPON_DAGGER));
                             me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 1, uint32(WEAPON_DAGGER));
                             /*
                             const CreatureTemplate* cinfo = me->GetCreatureTemplate();
                             me->SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, (cinfo->mindmg));
                             me->SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, (cinfo->maxdmg));
                             me->UpdateDamagePhysical(BASE_ATTACK);
                             */
                             me->HandleStatModifier(UNIT_MOD_DAMAGE_MAINHAND, TOTAL_PCT, 35.0f, false); // hack
                             events.ScheduleEvent(EVENT_SHADOW_WORD_PAIN, urand(4000, 7000), 0, PHASE_ONE);
                             events.ScheduleEvent(EVENT_GOUGE, urand(12000, 15000), 0, PHASE_ONE);
                             events.ScheduleEvent(EVENT_TRANSFORM, urand(16000, 20000), 0, PHASE_ONE);
                             events.SetPhase(PHASE_ONE);
                             break;
                         }
                     default:
                         break;
                 }
             }
             DoMeleeAttackIfReady();
         }
References _summonCountA, _summonCountB, _triggersSideAGUID, _triggersSideBGUID, ScriptedAI::AttackStart(), Unit::AttackStop(), UnitAI::DoCast(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DoResetThreat(), EQUIP_UNEQUIP, EVENT_GOUGE, EVENT_MARK_OF_ARLOKK, EVENT_RAVAGE, EVENT_SHADOW_WORD_PAIN, EVENT_SUMMON_PROWLERS, EVENT_TRANSFORM, EVENT_TRANSFORM_BACK, EVENT_VANISH, EVENT_VANISH_2, EVENT_VISIBLE, frand(), Unit::GetMotionMaster(), Position::GetPositionZ(), ObjectAccessor::GetUnit(), Unit::GetVictim(), Unit::HandleStatModifier(), Unit::HasUnitState(), MAX_PROWLERS_PER_SIDE, ScriptedAI::me, MotionMaster::MovePoint(), PHASE_ALL, PHASE_ONE, PHASE_TWO, REACT_AGGRESSIVE, REACT_PASSIVE, Unit::RemoveAura(), Object::RemoveFlag(), SAY_FEAST_PROWLER, SELECT_TARGET_RANDOM, SELECT_TARGET_TOPAGGRO, UnitAI::SelectTarget(), Object::SetFlag(), Creature::SetReactState(), Object::SetUInt32Value(), Creature::SetWalk(), SPELL_GOUGE, SPELL_MARK_OF_ARLOKK, SPELL_PANTHER_TRANSFORM, SPELL_RAVAGE, SPELL_SHADOW_WORD_PAIN, SPELL_SUMMON_PROWLER, SPELL_SUPER_INVIS, SPELL_VANISH, SPELL_VANISH_VISUAL, CreatureAI::Talk(), TOTAL_PCT, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, UNIT_FLAG_NOT_SELECTABLE, UNIT_MOD_DAMAGE_MAINHAND, UNIT_STATE_CASTING, UNIT_VIRTUAL_ITEM_SLOT_ID, CreatureAI::UpdateVictim(), urand(), and WEAPON_DAGGER.
Member Data Documentation
_summonCountA
uint8 boss_arlokk::boss_arlokkAI::_summonCountA private
Definition at line 297 of file boss_arlokk.cpp.
Referenced by Reset(), SetData(), and UpdateAI().
_summonCountB
uint8 boss_arlokk::boss_arlokkAI::_summonCountB private
Definition at line 298 of file boss_arlokk.cpp.
Referenced by Reset(), SetData(), and UpdateAI().
_triggersSideAGUID
ObjectGuid boss_arlokk::boss_arlokkAI::_triggersSideAGUID[5] private
Definition at line 299 of file boss_arlokk.cpp.
Referenced by EnterCombat(), and UpdateAI().
_triggersSideBGUID
ObjectGuid boss_arlokk::boss_arlokkAI::_triggersSideBGUID[5] private
Definition at line 300 of file boss_arlokk.cpp.
Referenced by EnterCombat(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/ZulGurub/boss_arlokk.cpp