Azerotcore-wotlk: src/common/Utilities/Random.h File Reference
Random.h File Reference
#include "Define.h"
#include "Duration.h"
#include <limits>
Classes
class RandomEngine
Functions
AC_COMMON_API int32 irand (int32 min, int32 max)
AC_COMMON_API uint32 urand (uint32 min, uint32 max)
AC_COMMON_API uint32 urandms (uint32 min, uint32 max)
AC_COMMON_API uint32 rand32 ()
AC_COMMON_API Milliseconds randtime (Milliseconds min, Milliseconds max)
AC_COMMON_API float frand (float min, float max)
AC_COMMON_API double rand_norm ()
AC_COMMON_API double rand_chance ()
AC_COMMON_API uint32 urandweighted (size_t count, double const *chances)
bool roll_chance_f (float chance)
bool roll_chance_i (int chance)
Function Documentation
frand()
AC_COMMON_API float frand (float min, float max)
Definition at line 57 of file Random.cpp.
 {
     ASSERT(max >= min);
     std::uniform_real_distribution<float> urd(min, max);
     return urd(engine);
 }
References ASSERT, and engine.
Referenced by npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::DoAction(), npc_time_rift::npc_time_riftAI::DoSummonAtRift(), Unit::GetMeleeAttackPoint(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::GoSiphon(), go_tadpole_cage::go_tadpole_cageAI::GossipHello(), spell_item_unusual_compass::HandleDummy(), spell_entropius_black_hole_effect::spell_entropius_black_hole_effect_SpellScript::HandlePull(), spell_boss_magus_telestra_gravity_well::spell_boss_magus_telestra_gravity_well_SpellScript::HandlePull(), npc_eris_hevenfire::npc_eris_hevenfireAI::JustSummoned(), npc_akama_shade::npc_akamaAI::JustSummoned(), spell_gen_random_target32::ModDest(), spell_q12308_escape_from_silverbrook_summon_worgen::ModDest(), spell_random_lightning_visual_effect::spell_random_lightning_visual_effect_SpellScript::ModDestHeight(), npc_gunship_boarding_addAI::MovementInform(), SmartScript::ProcessAction(), npc_lake_frog::npc_lake_frogAI::ReceiveEmote(), spell_quest_dragonmaw_race_generic::RelocateDest(), npc_firework::npc_fireworkAI::Reset(), PassengerController::SelectSpawnPoint(), spell_q10898_skywing::spell_q10898_skywing_SpellScript::SetDest(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonBroodling(), boss_malchezaar::boss_malchezaarAI::SummonInfernal(), npc_eris_hevenfire::npc_eris_hevenfireAI::SummonPeasants(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::Update(), npc_scarlet_ghoul::npc_scarlet_ghoulAI::UpdateAI(), boss_arlokk::boss_arlokkAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::UpdateAI(), boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI::UpdateAI(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::UpdateAI(), and npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI().
irand()
AC_COMMON_API int32 irand (int32 min, int32 max)
Definition at line 37 of file Random.cpp.
 {
     ASSERT(max >= min);
     std::uniform_int_distribution<int32> uid(min, max);
     return uid(engine);
 }
References ASSERT, and engine.
Referenced by spell_shadowfang_keep_haunting_spirits::spell_shadowfang_keep_haunting_spirits_AuraScript::CalcPeriodic(), SpellEffectInfo::CalcValue(), Spell::CheckCast(), hyjalAI::DoOverrun(), Spell::EffectSchoolDMG(), Spell::EffectTeleportUnits(), GetItemEnchantMod(), spell_gen_gadgetzan_transporter_backfire::HandleDummy(), spell_item_flask_of_the_north::HandleDummy(), Unit::HandleDummyAuraProc(), spell_winter_veil_racer_slam_hit::spell_winter_veil_racer_slam_hit_SpellScript::HandleScriptEffect(), spell_dk_bloodworms::HandleSummon(), boss_kologarn_arms::boss_kologarn_armsAI::JustDied(), Unit::MagicSpellHitResult(), spell_gen_flurry_of_claws::OnPeriodic(), roll_chance_i(), npc_minigob_manabonk::npc_minigob_manabonkAI::SendMailToPlayer(), boss_janalai::boss_janalaiAI::SpawnBombs(), npc_xt002_heart::npc_xt002_heartAI::SpellHitTarget(), boss_general_angerforge::boss_general_angerforgeAI::SummonAdds(), hyjalAI::SummonCreature(), boss_general_angerforge::boss_general_angerforgeAI::SummonMedics(), Spell::TakePower(), npc_scarlet_cannon::npc_scarlet_cannonAI::UpdateAI(), boss_akilzon::boss_akilzonAI::UpdateAI(), npc_akilzon_eagle::npc_akilzon_eagleAI::UpdateAI(), npc_giant_infernal::npc_giant_infernalAI::UpdateAI(), npc_abomination::npc_abominationAI::UpdateAI(), npc_ghoul::npc_ghoulAI::UpdateAI(), npc_necromancer::npc_necromancerAI::UpdateAI(), npc_banshee::npc_bansheeAI::UpdateAI(), npc_crypt_fiend::npc_crypt_fiendAI::UpdateAI(), npc_fel_stalker::npc_fel_stalkerAI::UpdateAI(), npc_frost_wyrm::npc_frost_wyrmAI::UpdateAI(), npc_gargoyle::npc_gargoyleAI::UpdateAI(), hyjal_trashAI::UpdateAI(), npc_murkdeep::npc_murkdeepAI::UpdateAI(), npc_pos_after_first_boss::npc_pos_after_first_bossAI::UpdateAI(), boss_grobbulus::boss_grobbulusAI::UpdateAI(), boss_thorim_sif::boss_thorim_sifAI::UpdateAI(), violet_hold_trashAI::UpdateAI(), npc_llod_generic::npc_llod_genericAI::UpdateAI(), Player::UpdateSkillPro(), GameObject::Use(), and hyjalAI::WaypointReached().
rand32()
AC_COMMON_API uint32 rand32 ()
Definition at line 72 of file Random.cpp.
 {
     return GetRng()->RandomUInt32();
 }
References GetRng(), and SFMTRand::RandomUInt32().
Referenced by npc_thrall_bfu::npc_thrall_bfuAI::ActivateValimathrasPortal(), boss_nefarian::boss_nefarianAI::KilledUnit(), boss_vaelastrasz::boss_vaelAI::KilledUnit(), RandomEngine::operator()(), npc_varian_wrynn::npc_varian_wrynnAI::SpawnWave(), and npc_thrall_bfu::npc_thrall_bfuAI::SpawnWave().
rand_chance()
AC_COMMON_API double rand_chance ()
Definition at line 83 of file Random.cpp.
 {
     std::uniform_real_distribution<double> urd(0.0, 100.0);
     return urd(engine);
 }
References engine.
Referenced by Spell::EffectInebriate(), GetExplicitDiscoverySpell(), GetItemEnchantMod(), WorldSession::HandleGMResponseResolve(), LootTemplate::LootGroup::Roll(), roll_chance_f(), and PoolGroup< T >::SpawnObject().
rand_norm()
AC_COMMON_API double rand_norm ()
Definition at line 77 of file Random.cpp.
 {
     std::uniform_real_distribution<double> urd;
     return urd(engine);
 }
References engine.
Referenced by FleeingMovementGenerator< T >::_setMoveData(), RandomMovementGenerator< T >::_setRandomLocation(), Unit::CalcAbsorbResist(), SpellImplicitTargetInfo::CalcDirectionAngle(), boss_headless_horseman::boss_headless_horsemanAI::DamageTaken(), RandomMovementGenerator< T >::DoInitialize(), ConfusedMovementGenerator< T >::DoInitialize(), npc_time_rift::npc_time_riftAI::DoSummonAtRift(), Spell::EffectStuck(), Spell::EffectTransmitted(), violet_hold_trashAI::EnterEvadeMode(), Unit::GetRandomContactPoint(), WorldObject::GetRandomNearPosition(), WorldObject::GetRandomPoint(), Position::GetSinCos(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::GoSiphon(), spell_icc_geist_alarm::spell_icc_geist_alarm_SpellScript::HandleEvent(), spell_dreamwalker_summon_portal::spell_dreamwalker_summon_portal_SpellScript::HandleScript(), boss_onyxia::boss_onyxiaAI::HandleWhelpSpam(), spell_q11065_wrangle_some_aether_rays_aura::if(), npc_troll_volunteer::npc_troll_volunteerAI::InitializeAI(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::InitializeAI(), npc_pet_dk_army_of_the_dead::npc_pet_dk_army_of_the_deadAI::InitializeAI(), boss_auriaya::boss_auriayaAI::JustSummoned(), spell_the_lich_king_teleport_to_frostmourne_hc::spell_the_lich_king_teleport_to_frostmourne_hc_SpellScript::ModDest(), npc_ulduar_snow_mound::npc_ulduar_snow_moundAI::MoveInLineOfSight(), npc_concentrated_ball::npc_concentrated_ballAI::MoveToNextPoint(), npc_mechanolift::npc_mechanoliftAI::npc_mechanoliftAI(), Unit::PetSpellFail(), npc_oculus_unstable_sphere::npc_oculus_unstable_sphereAI::PickNewLocation(), Weather::ReGenerate(), boss_anubarak_trial::boss_anubarak_trialAI::Reset(), boss_bjarngrim::boss_bjarngrimAI::Reset(), spell_sindragosa_s_fury::spell_sindragosa_s_fury_SpellScript::SelectDest(), Spell::SelectImplicitCasterDestTargets(), Spell::SelectImplicitDestDestTargets(), Spell::SelectImplicitTargetDestTargets(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::SpawnTentacle(), npc_pos_leader_second::npc_pos_leader_secondAI::SpellHitTarget(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonBroodling(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::SummonDeathOrbs(), boss_yoggsaron::boss_yoggsaronAI::SummonImmortalGuardian(), instance_the_black_morass::instance_the_black_morass_InstanceMapScript::SummonPortalKeeper(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::Update(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::Update(), npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::UpdateAI(), boss_onyxia::boss_onyxiaAI::UpdateAI(), npc_shay_leafrunner::npc_shay_leafrunnerAI::UpdateAI(), boss_icehowl::boss_icehowlAI::UpdateAI(), boss_twin_valkyrAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), boss_sindragosa::boss_sindragosaAI::UpdateAI(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), boss_ormorok::boss_ormorokAI::UpdateAI(), boss_drakos::boss_drakosAI::UpdateAI(), boss_eregos::boss_eregosAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::UpdateAI(), npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::UpdateAI(), boss_keleseth::boss_kelesethAI::UpdateAI(), boss_ymiron::boss_ymironAI::UpdateAI(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::UpdateAI(), boss_ahune::boss_ahuneAI::UpdateAI(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::UpdateAI(), and boss_ichoron::boss_ichoronAI::UpdateAI().
randtime()
AC_COMMON_API Milliseconds randtime (Milliseconds min, Milliseconds max)
Definition at line 64 of file Random.cpp.
 {
     long long diff = max.count() - min.count();
     ASSERT(diff >= 0);
     ASSERT(diff <= (uint32) - 1);
     return min + Milliseconds(urand(0, diff));
 }
References ASSERT, and urand().
roll_chance_f()
bool roll_chance_f (float chance) inline
Definition at line 53 of file Random.h.
 {
     return chance > rand_chance();
 }
References rand_chance().
Referenced by spell_dk_spell_deflection::Absorb(), Player::CastItemCombatSpell(), spell_dk_wandering_plague_aura::CheckProc(), spell_gen_proc_reduced_above_60::CheckProc(), Unit::DealDamage(), Unit::DealMeleeDamage(), Spell::DoAllEffectOnLaunchTarget(), Spell::DoCreateItem(), GetSkillDiscoverySpell(), Unit::HandleDummyAuraProc(), AuraEffect::HandlePeriodicDamageAurasTick(), AuraEffect::HandlePeriodicHealAurasTick(), AuraEffect::HandlePeriodicHealthLeechAuraTick(), Aura::IsProcTriggeredOnEvent(), Unit::isSpellBlocked(), Unit::IsTriggeredAtSpellProcEvent(), item_generic_limit_chance_above_60::OnCastItemCombatSpell(), spell_gen_mounted_charge::PrepareSpellScript(), spell_dk_rune_of_the_fallen_crusader::RecalculateDamage(), LootStoreItem::Roll(), boss_elder_nadox::boss_elder_nadoxAI::SummonHelpers(), and Player::UpdateCombatSkills().
roll_chance_i()
bool roll_chance_i (int chance) inline
Definition at line 59 of file Random.h.
 {
     return chance > irand(0, 99);
 }
References irand().
Referenced by RandomMovementGenerator< T >::_setRandomLocation(), spell_rog_cheat_death::Absorb(), spell_mage_fire_frost_ward::Absorb(), spell_sha_earthbind_totem::Apply(), spell_dru_brambles_treant::CheckProc(), spell_hun_improved_mend_pet::CheckProc(), spell_mage_molten_armor::CheckProc(), spell_sha_earthliving_weapon::CheckProc(), boss_illidari_council::boss_illidari_councilAI::DoAction(), npc_forest_frog::npc_forest_frogAI::DoSpawnRandom(), Spell::DoTriggersOnSpellHit(), Spell::EffectDispel(), Spell::EffectDispelMechanic(), Spell::EffectSchoolDMG(), Spell::EffectScriptEffect(), Spell::EffectStealBeneficialBuff(), Spell::EffectTeleportUnits(), Spell::EffectWeaponDmg(), npc_crusade_persuaded::npc_crusade_persuadedAI::EnterCombat(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::EnterCombat(), Unit::GetMeleeHitRedirectTarget(), Player::GetResurrectionSpellId(), spell_q9452_cast_net::HandleActiveObject(), spell_dk_scourge_strike::HandleAfterHit(), AuraEffect::HandleAuraDummy(), Aura::HandleAuraSpecificMods(), spell_thaddius_polarity_shift::spell_thaddius_polarity_shift_SpellScript::HandleDummy(), spell_capacitus_polarity_shift::spell_capacitus_polarity_shift_SpellScript::HandleDummy(), spell_gen_gnomish_transporter::HandleDummy(), spell_item_purify_helboar_meat::HandleDummy(), spell_item_nigh_invulnerability::HandleDummy(), spell_item_poultryizer::HandleDummy(), spell_item_nitro_boots::HandleDummy(), spell_item_teach_language::HandleDummy(), spell_item_pygmy_oil::HandleDummy(), spell_q5206_test_fetid_skull::HandleDummy(), spell_q12634_despawn_fruit_tosser::HandleDummy(), spell_q9452_cast_net::HandleDummy(), Unit::HandleDummyAuraProc(), spell_item_rocket_chicken::HandleDummyTick(), spell_sha_earthbind_totem::HandleEffectPeriodic(), spell_item_crazy_alchemists_potion::HandleHeal(), Unit::HandleOverrideClassScriptAuraProc(), spell_kaelthas_remote_toy::spell_kaelthas_remote_toy_AuraScript::HandlePeriodic(), spell_dk_blood_caked_blade::HandleProc(), spell_hun_lock_and_load::HandleProcs(), Unit::HandleProcTriggerSpell(), spell_gen_netherbloom::HandleScript(), spell_gen_nightmare_vine::HandleScript(), spell_item_defibrillate::HandleScript(), spell_hallows_end_trick_or_treat::spell_hallows_end_trick_or_treat_SpellScript::HandleScript(), spell_hallows_end_tricky_treat::spell_hallows_end_tricky_treat_SpellScript::HandleScript(), spell_item_eggnog::HandleScript(), spell_leotheras_whirlwind::spell_leotheras_whirlwind_SpellScript::HandleScriptEffect(), spell_hun_invigoration::HandleScriptEffect(), spell_zulfarrak_summon_zulfarrak_zombies::spell_zulfarrak_summon_zulfarrak_zombies_SpellScript::HandleSummon(), spell_item_draenic_pale_ale::HandleSummon(), spell_warl_drain_soul::HandleTick(), spell_gnomeregan_radiation_bolt::spell_gnomeregan_radiation_bolt_SpellScript::HandleTriggerSpell(), spell_valkyr_essence::spell_valkyr_essence_auraAuraScript::if(), Unit::isBlockCritical(), boss_halion::boss_halionAI::JustSummoned(), boss_majordomo::boss_majordomoAI::KilledUnit(), boss_ragnaros::boss_ragnarosAI::KilledUnit(), boss_brutallus::boss_brutallusAI::KilledUnit(), boss_felmyst::boss_felmystAI::KilledUnit(), boss_kalecgos::boss_kalecgosAI::KilledUnit(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::KilledUnit(), boss_void_reaver::boss_void_reaverAI::KilledUnit(), boss_razuvious::boss_razuviousAI::KilledUnit(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::MovementInform(), spell_item_magic_dust::OnApply(), spell_item_linken_boomerang::OnEffectLaunchTargetDisarm(), spell_item_linken_boomerang::OnEffectLaunchTargetStun(), go_noblegarden_colored_egg::OnGossipHello(), go_strange_pool::OnGossipHello(), npc_innkeeper::OnGossipSelect(), spell_black_temple_dementia::spell_black_temple_dementia_AuraScript::OnPeriodic(), spell_item_goblin_weather_machine_aura::OnRemove(), Acore::RandomCheck::operator()(), spell_midsummer_ribbon_pole::spell_midsummer_ribbon_pole_AuraScript::PrepareAuraScript(), spell_item_mind_amplify_dish::PrepareSpellScript(), spell_q11653_youre_not_so_big_now::PrepareSpellScript(), Player::RemoveSpellMods(), npc_time_lost_proto_drake::npc_time_lost_proto_drakeAI::RollPath(), boss_gathios_the_shatterer::boss_gathios_the_shattererAI::SelectCouncilMember(), spell_mother_shahraz_fatal_attraction::spell_mother_shahraz_fatal_attraction_SpellScript::SetDest(), npc_balance_of_light_and_shadow::npc_balance_of_light_and_shadowAI::SpellHit(), npc_wild_wyrm::npc_wild_wyrmAI::SpellHit(), npc_forest_frog::npc_forest_frogAI::SpellHit(), Unit::SpellHitResult(), boss_amanitar::boss_amanitarAI::SummonMushroom(), npc_eris_hevenfire::npc_eris_hevenfireAI::SummonPeasants(), spell_karazhan_brittle_bones::spell_karazhan_brittle_bones_AuraScript::Update(), spell_black_temple_curse_of_the_bleakheart::spell_black_temple_curse_of_the_bleakheart_AuraScript::Update(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::Update(), boss_curator::boss_curatorAI::UpdateAI(), boss_sathrovarr::boss_sathrovarrAI::UpdateAI(), boss_captain_skarloc::boss_captain_skarlocAI::UpdateAI(), boss_epoch_hunter::boss_epoch_hunterAI::UpdateAI(), boss_lieutenant_drake::boss_lieutenant_drakeAI::UpdateAI(), boss_moorabi::boss_moorabiAI::UpdateAI(), npc_llod_generic::npc_llod_genericAI::UpdateAI(), boss_essence_of_desire::boss_essence_of_desireAI::UpdateAI(), boss_essence_of_anger::boss_essence_of_angerAI::UpdateAI(), boss_teron_gorefiend::boss_teron_gorefiendAI::UpdateAI(), boss_gathios_the_shatterer::boss_gathios_the_shattererAI::UpdateAI(), boss_high_nethermancer_zerevor::boss_high_nethermancer_zerevorAI::UpdateAI(), boss_lady_malande::boss_lady_malandeAI::UpdateAI(), boss_veras_darkshadow::boss_veras_darkshadowAI::UpdateAI(), boss_lady_vashj::boss_lady_vashjAI::UpdateAI(), boss_omor_the_unscarred::boss_omor_the_unscarredAI::UpdateAI(), boss_zereketh_the_unbound::boss_zereketh_the_unboundAI::UpdateAI(), boss_commander_sarannis::boss_commander_sarannisAI::UpdateAI(), boss_high_botanist_freywinn::boss_high_botanist_freywinnAI::UpdateAI(), boss_thorngrin_the_tender::boss_thorngrin_the_tenderAI::UpdateAI(), boss_alar::boss_alarAI::UpdateAI(), boss_kaelthas::boss_kaelthasAI::UpdateAI(), boss_nethermancer_sepethrea::boss_nethermancer_sepethreaAI::UpdateAI(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::UpdateAI(), and npc_dragonmaw_peon::npc_dragonmaw_peonAI::UpdateAI().
urand()
AC_COMMON_API uint32 urand (uint32 min, uint32 max)
Definition at line 44 of file Random.cpp.
 {
     ASSERT(max >= min);
     std::uniform_int_distribution<uint32> uid(min, max);
     return uid(engine);
 }
References ASSERT, and engine.
Referenced by FleeingMovementGenerator< T >::_getPoint(), FleeingMovementGenerator< T >::_setMoveData(), RandomMovementGenerator< T >::_setRandomLocation(), ObjectMgr::AddCreData(), Loot::AddItem(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::AddWave1(), BattlegroundQueue::BattlegroundQueueUpdate(), boss_victor_nefarius::boss_victor_nefariusAI::BeginEvent(), boss_chromaggus::boss_chromaggusAI::boss_chromaggusAI(), boss_grand_champion::boss_grand_championAI::boss_grand_championAI(), boss_twin_valkyrAI::boss_twin_valkyrAI(), spell_gen_allergies::spell_gen_allergies_AuraScript::CalcPeriodic(), spell_item_goblin_gumbo_kettle::CalcPeriodic(), Unit::CalculateDamage(), BattlegroundAV::ChangeMineOwner(), boss_professor_putricide::boss_professor_putricideAI::ChangePhase(), npc_still_at_it_trigger::npc_still_at_it_triggerAI::CheckAction(), lfg::LFGQueue::CheckCompatibility(), Group::CountTheRoll(), GameObject::Create(), boss_bronjahm::boss_bronjahmAI::DamageTaken(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::DamageTaken(), npc_infra_green_bomber_generic::npc_infra_green_bomber_genericAI::DamageTaken(), Unit::DealDamage(), boss_razorgore::boss_razorgoreAI::DoAction(), boss_ossirian::boss_ossirianAI::DoAction(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::DoAction(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::DoAction(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::DoAction(), boss_black_knight::boss_black_knightAI::DoAction(), boss_tyrannus::boss_tyrannusAI::DoAction(), RandomMovementGenerator< T >::DoInitialize(), ConfusedMovementGenerator< T >::DoInitialize(), instance_stratholme::instance_stratholme_InstanceMapScript::DoSpawnPlaguedCritters(), npc_forest_frog::npc_forest_frogAI::DoSpawnRandom(), ConfusedMovementGenerator< T >::DoUpdate(), Spell::EffectDispel(), Spell::EffectDummy(), Spell::EffectForceDeselect(), Spell::EffectScriptEffect(), Spell::EffectStealBeneficialBuff(), Spell::EffectTeleportUnits(), Spell::EffectTransmitted(), chromatic_elite_guard::chromatic_elite_guardAI::EnterCombat(), boss_gyth::boss_gythAI::EnterCombat(), boss_halycon::boss_halyconAI::EnterCombat(), boss_lord_valthalak::boss_lord_valthalakAI::EnterCombat(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::EnterCombat(), boss_rend_blackhand::boss_rend_blackhandAI::EnterCombat(), boss_solakar_flamewreath::boss_solakar_flamewreathAI::EnterCombat(), boss_urok_doomhowl::boss_urok_doomhowlAI::EnterCombat(), boss_nefarian::boss_nefarianAI::EnterCombat(), boss_baron_geddon::boss_baron_geddonAI::EnterCombat(), boss_gehennas::boss_gehennasAI::EnterCombat(), boss_lucifron::boss_lucifronAI::EnterCombat(), boss_shazzrah::boss_shazzrahAI::EnterCombat(), boss_sulfuron::boss_sulfuronAI::EnterCombat(), npc_flamewaker_priest::npc_flamewaker_priestAI::EnterCombat(), boss_attumen::boss_attumenAI::EnterCombat(), boss_attumen_midnight::boss_attumen_midnightAI::EnterCombat(), npc_mograine::npc_mograineAI::EnterCombat(), boss_high_inquisitor_whitemane::boss_high_inquisitor_whitemaneAI::EnterCombat(), npc_scholomance_occultist::npc_scholomance_occultistAI::EnterCombat(), boss_akilzon::boss_akilzonAI::EnterCombat(), boss_arlokk::boss_arlokkAI::EnterCombat(), boss_grilek::boss_grilekAI::EnterCombat(), boss_hazzarah::boss_hazzarahAI::EnterCombat(), boss_mandokir::boss_mandokirAI::EnterCombat(), boss_wushoolay::boss_wushoolayAI::EnterCombat(), boss_archimonde::boss_archimondeAI::EnterCombat(), boss_skeram::boss_skeramAI::EnterCombat(), npc_muglash::npc_muglashAI::EnterCombat(), npc_omen::npc_omenAI::EnterCombat(), boss_amanitar::boss_amanitarAI::EnterCombat(), boss_elder_nadox::boss_elder_nadoxAI::EnterCombat(), npc_baltharus_the_warborn_clone::npc_baltharus_the_warborn_cloneAI::EnterCombat(), npc_onyx_flamecaller::npc_onyx_flamecallerAI::EnterCombat(), boss_twilight_halion::boss_twilight_halionAI::EnterCombat(), boss_paletress::boss_paletressAI::EnterCombat(), npc_argent_soldier::npc_argent_soldierAI::EnterCombat(), npc_black_knight_ghoul::npc_black_knight_ghoulAI::EnterCombat(), npc_toc5_grand_champion_minion::npc_toc5_grand_champion_minionAI::EnterCombat(), boss_anubarak_trial::boss_anubarak_trialAI::EnterCombat(), boss_jaraxxus::boss_jaraxxusAI::EnterCombat(), boss_gormok::boss_gormokAI::EnterCombat(), boss_icehowl::boss_icehowlAI::EnterCombat(), boss_bronjahm::boss_bronjahmAI::EnterCombat(), boss_devourer_of_souls::boss_devourer_of_soulsAI::EnterCombat(), npc_hor_spiritual_reflection::npc_hor_spiritual_reflectionAI::EnterCombat(), boss_garfrost::boss_garfrostAI::EnterCombat(), boss_ick::boss_ickAI::EnterCombat(), npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI::EnterCombat(), npc_stinky_icc::npc_stinky_iccAI::EnterCombat(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::EnterCombat(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::EnterCombat(), npc_gunship_boarding_leader::npc_gunship_boarding_leaderAI::EnterCombat(), npc_precious_icc::npc_precious_iccAI::EnterCombat(), boss_sister_svalna::boss_sister_svalnaAI::EnterCombat(), npc_icc_skybreaker_hierophant::npc_icc_skybreaker_hierophantAI::EnterCombat(), npc_icc_skybreaker_marksman::npc_icc_skybreaker_marksmanAI::EnterCombat(), npc_icc_skybreaker_vicar::npc_icc_skybreaker_vicarAI::EnterCombat(), npc_icc_skybreaker_luminary::npc_icc_skybreaker_luminaryAI::EnterCombat(), npc_boss_gothik_minion::npc_boss_gothik_minionAI::EnterCombat(), npc_nexus_lord::npc_nexus_lordAI::EnterCombat(), boss_drakos::boss_drakosAI::EnterCombat(), boss_urom::boss_uromAI::EnterCombat(), boss_varos::boss_varosAI::EnterCombat(), boss_hodir::boss_hodirAI::EnterCombat(), npc_ulduar_storm_tempered_keeper::npc_ulduar_storm_tempered_keeperAI::EnterCombat(), boss_cyanigosa::boss_cyanigosaAI::EnterCombat(), boss_ichoron::boss_ichoronAI::EnterCombat(), boss_moragg::boss_moraggAI::EnterCombat(), boss_xevozz::boss_xevozzAI::EnterCombat(), boss_zuramat::boss_zuramatAI::EnterCombat(), npc_yor::npc_yorAI::EnterCombat(), boss_pandemonius::boss_pandemoniusAI::EnterCombat(), boss_talon_king_ikiss::boss_talon_king_ikissAI::EnterCombat(), boss_ambassador_hellmaw::boss_ambassador_hellmawAI::EnterCombat(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::EnterCombat(), boss_murmur::boss_murmurAI::EnterCombat(), boss_warlord_kalithresh::boss_warlord_kalithreshAI::EnterCombat(), boss_the_black_stalker::boss_the_black_stalkerAI::EnterCombat(), npc_shadowmoon_channeler::npc_shadowmoon_channelerAI::EnterCombat(), boss_warbringer_omrogg::boss_warbringer_omroggAI::EnterCombat(), boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI::EnterCombat(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::EnterCombat(), npc_ragin_flames::npc_ragin_flamesAI::EnterCombat(), exarch_orelis::exarch_orelisAI::EnterCombat(), npc_dragonmaw_peon::npc_dragonmaw_peonAI::EnterCombat(), npc_pet_shaman_fire_elemental::EnterCombat(), boss_ayamiss::boss_ayamissAI::EnterCombat(), boss_the_lich_king::boss_the_lich_kingAI::EnterCombat(), boss_sindragosa::boss_sindragosaAI::EnterCombat(), npc_artorius::npc_artoriusAI::EnterCombat(), npc_simone::npc_simoneAI::EnterCombat(), npc_nelson::npc_nelsonAI::EnterCombat(), npc_franklin::npc_franklinAI::EnterCombat(), boss_priestess_lackey_commonAI::EnterCombat(), npc_belnistrasz::npc_belnistraszAI::EnterCombat(), npc_prospector_remtravel::npc_prospector_remtravelAI::EnterCombat(), boss_halion::boss_halionAI::EnterCombat(), boss_dred::boss_dredAI::EnterCombat(), boss_tharon_ja::boss_tharon_jaAI::EnterCombat(), boss_trollgore::boss_trollgoreAI::EnterCombat(), boss_eck::boss_eckAI::EnterCombat(), boss_prince_keleseth_icc::boss_prince_kelesethAI::EnterCombat(), boss_prince_taldaram_icc::boss_prince_taldaramAI::EnterCombat(), boss_prince_valanar_icc::boss_prince_valanarAI::EnterCombat(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::EnterCombat(), boss_festergut::boss_festergutAI::EnterCombat(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::EnterCombat(), boss_professor_putricide::boss_professor_putricideAI::EnterCombat(), boss_rotface::boss_rotfaceAI::EnterCombat(), boss_anubrekhan::boss_anubrekhanAI::EnterCombat(), boss_faerlina::boss_faerlinaAI::EnterCombat(), boss_steelbreaker::boss_steelbreakerAI::EnterCombat(), boss_erekem::boss_erekemAI::EnterCombat(), npc_erekem_guard::npc_erekem_guardAI::EnterCombat(), npc_torturer_lecraft::npc_torturer_lecraftAI::EnterCombat(), boss_najentus::boss_najentusAI::EnterCombat(), npc_earthmender_wilda::npc_earthmender_wildaAI::EnterCombat(), boss_solakar_flamewreath::boss_solakar_flamewreathAI::ExecuteEvent(), boss_baron_geddon::boss_baron_geddonAI::ExecuteEvent(), boss_gehennas::boss_gehennasAI::ExecuteEvent(), boss_magmadar::boss_magmadarAI::ExecuteEvent(), boss_shazzrah::boss_shazzrahAI::ExecuteEvent(), boss_sulfuron::boss_sulfuronAI::ExecuteEvent(), boss_amanitar::boss_amanitarAI::ExecuteEvent(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), emerald_dragonAI::ExecuteEvent(), boss_ysondre::boss_ysondreAI::ExecuteEvent(), boss_lethon::boss_lethonAI::ExecuteEvent(), boss_taerar::boss_taerarAI::ExecuteEvent(), spell_deathbringer_blood_nova_targeting::spell_deathbringer_blood_nova_targeting_SpellScript::FilterTargetsInitial(), spell_ulduar_stone_grip_cast_target::spell_ulduar_stone_grip_cast_target_SpellScript::FilterTargetsInitial(), npc_dark_iron_guzzler::npc_dark_iron_guzzlerAI::FindNextKeg(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::FindRoom(), boss_archimonde::boss_archimondeAI::GainSoulCharge(), Loot::generateMoneyLoot(), ObjectMgr::GeneratePetName(), npc_jaina_proudmoore::GetAI(), npc_thrall::GetAI(), ObjectMgr::GetCreatureModelRandomGender(), ObjectMgr::GetEquipmentInfo(), npc_firework::npc_fireworkAI::GetFireworkGameObjectId(), Unit::GetMeleeAttackPoint(), Player::GetNextRandomRaidMember(), Unit::GetNextRandomRaidMemberOrPet(), npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::GetRandomBartender(), CreatureTemplate::GetRandomValidModelId(), npc_brewfest_bark_trigger::npc_brewfest_bark_triggerAI::GetTextFor(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::getValidRandomPosition(), go_tadpole_cage::go_tadpole_cageAI::GossipHello(), spell_brewfest_fill_keg::spell_brewfest_fill_keg_SpellScript::HandleAfterHit(), spell_gen_baby_murloc_passive::HandleApply(), AuraEffect::HandleAuraModShapeshift(), boss_janalai::boss_janalaiAI::HandleBombSequence(), boss_twinemperorsAI::HandleBugs(), Player::HandleDrowning(), spell_gen_focused_bursts::HandleDummy(), spell_item_mingos_fortune_generator::HandleDummy(), spell_hallows_end_candy::spell_hallows_end_candy_SpellScript::HandleDummy(), spell_q12589_shoot_rjr::spell_q12589_shoot_rjr_SpellScript::HandleDummy(), spell_item_gnomish_universal_remote::HandleDummy(), spell_item_gnomish_shrink_ray::HandleDummy(), spell_item_deviate_fish::HandleDummy(), spell_item_make_a_wish::HandleDummy(), spell_item_net_o_matic::HandleDummy(), spell_item_noggenfogger_elixir::HandleDummy(), spell_item_savory_deviate_delight::HandleDummy(), spell_item_six_demon_bag::HandleDummy(), spell_item_underbelly_elixir::HandleDummy(), spell_mage_polymorph_cast_visual::HandleDummy(), spell_q12634_despawn_fruit_tosser::HandleDummy(), Unit::HandleDummyAuraProc(), spell_shadowfang_keep_forsaken_skills::spell_shadowfang_keep_forsaken_skills_AuraScript::HandleDummyTick(), spell_gen_haunted_aura::HandleEffectCalcPeriodic(), spell_gen_haunted_aura::HandleEffectPeriodic(), spell_item_crazy_alchemists_potion::HandleHeal(), boss_malygos::boss_malygosAI::HandleIntroSpeech(), spell_yogg_saron_brain_link::spell_yogg_saron_brain_link_AuraScript::HandleOnEffectApply(), spell_gen_haunted::HandleOnEffectHit(), spell_gen_baby_murloc_passive::HandlePeriodicTimer(), WorldSession::HandlePetActionHelper(), WorldSession::HandlePetCastSpellOpcode(), WorldSession::HandleRandomRollOpcode(), spell_kormok_summon_bone_mages::spell_kormok_summon_bone_magesSpellScript::HandleScript(), spell_item_create_heart_candy::spell_item_create_heart_candy_SpellScript::HandleScript(), spell_gen_netherbloom::HandleScript(), spell_gen_upper_deck_create_foam_sword::HandleScript(), spell_item_scroll_of_recall::HandleScript(), spell_hallows_end_trick::spell_hallows_end_trick_SpellScript::HandleScript(), spell_putricide_choking_gas_bomb::spell_putricide_choking_gas_bomb_SpellScript::HandleScript(), spell_gen_elune_candle::HandleScript(), spell_q12698_the_gift_that_keeps_on_giving::spell_q12698_the_gift_that_keeps_on_giving_SpellScript::HandleScriptEffect(), spell_winter_veil_shoot_air_rifle::spell_winter_veil_shoot_air_rifle_SpellScript::HandleScriptEffect(), spell_item_goblin_weather_machine::HandleScriptEffect(), spell_item_draenic_pale_ale::HandleSummon(), Battleground::HandleTriggerBuff(), spell_magic_eater_food::HandleTriggerSpell(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::InformCloud(), BattlegroundSA::Init(), boss_malchezaar::boss_malchezaarAI::Initialize(), npc_troll_volunteer::npc_troll_volunteerAI::InitializeAI(), npc_pet_gen_imp_in_a_bottle::InitializeAI(), npc_wormhole::npc_wormholeAI::InitializeAI(), boss_viscidus::boss_viscidusAI::InitSpells(), npc_scarlet_miner::npc_scarlet_minerAI::InitWaypoint(), instance_karazhan::instance_karazhan_InstanceMapScript::instance_karazhan_InstanceMapScript(), boss_volazj::boss_volazjAI::JustDied(), npc_webbed_creature::npc_webbed_creatureAI::JustDied(), npc_nerubar_victim::npc_nerubar_victimAI::JustDied(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::JustSummoned(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::JustSummoned(), npc_frosthound::npc_frosthoundAI::JustSummoned(), boss_skeram::boss_skeramAI::JustSummoned(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::KilledUnit(), boss_nalorakk::boss_nalorakkAI::KilledUnit(), npc_necromancer::npc_necromancerAI::KilledUnit(), boss_epoch::boss_epochAI::KilledUnit(), boss_mal_ganis::boss_mal_ganisAI::KilledUnit(), boss_meathook::boss_meathookAI::KilledUnit(), boss_salramm::boss_salrammAI::KilledUnit(), boss_maiden_of_grief::boss_maiden_of_griefAI::KilledUnit(), boss_sjonnir::boss_sjonnirAI::KilledUnit(), boss_auriaya::boss_auriayaAI::KilledUnit(), boss_freya_elder_stonebark::boss_freya_elder_stonebarkAI::KilledUnit(), boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI::KilledUnit(), boss_freya_elder_ironbranch::boss_freya_elder_ironbranchAI::KilledUnit(), boss_kologarn::boss_kologarnAI::KilledUnit(), boss_thorim::boss_thorimAI::KilledUnit(), boss_skadi::boss_skadiAI::KilledUnit(), boss_ymiron::boss_ymironAI::KilledUnit(), boss_exarch_maladaar::boss_exarch_maladaarAI::KilledUnit(), boss_talon_king_ikiss::boss_talon_king_ikissAI::KilledUnit(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::KilledUnit(), boss_warbringer_omrogg::boss_warbringer_omroggAI::KilledUnit(), boss_sartharion::boss_sartharionAI::KilledUnit(), boss_sartharion_dragonAI::KilledUnit(), boss_sacrolash::boss_sacrolashAI::KilledUnit(), boss_alythess::boss_alythessAI::KilledUnit(), boss_volazj::boss_volazjAI::KilledUnit(), boss_black_knight::boss_black_knightAI::KilledUnit(), boss_algalon_the_observer::boss_algalon_the_observerAI::KilledUnit(), boss_freya::boss_freyaAI::KilledUnit(), boss_xt002::boss_xt002AI::KilledUnit(), boss_ambassador_hellmaw::boss_ambassador_hellmawAI::KilledUnit(), boss_blackheart_the_inciter::boss_blackheart_the_inciterAI::KilledUnit(), boss_doomwalker::boss_doomwalkerAI::KilledUnit(), boss_the_maker::boss_the_makerAI::KilledUnit(), boss_eadric::boss_eadricAI::KilledUnit(), boss_paletress::boss_paletressAI::KilledUnit(), boss_twin_valkyrAI::KilledUnit(), boss_faerlina::boss_faerlinaAI::KilledUnit(), boss_patchwerk::boss_patchwerkAI::KilledUnit(), boss_thaddius_summon::boss_thaddius_summonAI::KilledUnit(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::KilledUnit(), boss_vezax::boss_vezaxAI::KilledUnit(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::KilledUnit(), spell_wailing_souls_periodic::spell_wailing_souls_periodic_AuraScript::Load(), spell_igb_explosion_main::spell_igb_explosion_main_AuraScript::Load(), Player::LoadFromDB(), Unit::MeleeSpellHitResult(), npc_cw_area_trigger::npc_cw_area_triggerAI::MoveInLineOfSight(), npc_love_in_air_supply_sentry::npc_love_in_air_supply_sentryAI::MoveInLineOfSight(), boss_grand_champion::boss_grand_championAI::MovementInform(), npc_concentrated_ball::npc_concentrated_ballAI::MovementInform(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::MovementInform(), npc_xt002_scrapbot::npc_xt002_scrapbotAI::MovementInform(), boss_icehowl::boss_icehowlAI::MovementInform(), npc_akilzon_eagle::npc_akilzon_eagleAI::MovementInform(), npc_hol_monument::npc_hol_monumentAI::npc_hol_monumentAI(), npc_pos_icicle_trigger::npc_pos_icicle_triggerAI::npc_pos_icicle_triggerAI(), npc_q24545_vegard::npc_q24545_vegardAI::npc_q24545_vegardAI(), npc_scion_of_eternity::npc_scion_of_eternityAI::npc_scion_of_eternityAI(), npc_toc_boomkin::npc_toc_boomkinAI::npc_toc_boomkinAI(), npc_toc_dk::npc_toc_dkAI::npc_toc_dkAI(), npc_toc_druid::npc_toc_druidAI::npc_toc_druidAI(), npc_toc_enh_shaman::npc_toc_enh_shamanAI::npc_toc_enh_shamanAI(), npc_toc_hunter::npc_toc_hunterAI::npc_toc_hunterAI(), npc_toc_mage::npc_toc_mageAI::npc_toc_mageAI(), npc_toc_paladin::npc_toc_paladinAI::npc_toc_paladinAI(), npc_toc_pet_hunter::npc_toc_pet_hunterAI::npc_toc_pet_hunterAI(), npc_toc_pet_warlock::npc_toc_pet_warlockAI::npc_toc_pet_warlockAI(), npc_toc_priest::npc_toc_priestAI::npc_toc_priestAI(), npc_toc_retro_paladin::npc_toc_retro_paladinAI::npc_toc_retro_paladinAI(), npc_toc_rogue::npc_toc_rogueAI::npc_toc_rogueAI(), npc_toc_shadow_priest::npc_toc_shadow_priestAI::npc_toc_shadow_priestAI(), npc_toc_shaman::npc_toc_shamanAI::npc_toc_shamanAI(), npc_toc_warlock::npc_toc_warlockAI::npc_toc_warlockAI(), npc_toc_warrior::npc_toc_warriorAI::npc_toc_warriorAI(), npc_vortex_ride::npc_vortex_rideAI::npc_vortex_rideAI(), spell_shadowfang_keep_forsaken_skills::spell_shadowfang_keep_forsaken_skills_AuraScript::OnApply(), spell_item_magic_dust::OnApply(), WaypointMovementGenerator< Creature >::OnArrived(), spell_item_ashbringer::OnDummyEffect(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectCreate(), npc_barnes::OnGossipSelect(), spell_item_goblin_weather_machine_aura::OnRemove(), instance_karazhan::instance_karazhan_InstanceMapScript::OnUnitDeath(), boss_malchezaar::boss_malchezaarAI::Phase2(), boss_malchezaar::boss_malchezaarAI::Phase3(), boss_thorim::boss_thorimAI::PlaySpecial(), BattlegroundAV::PostUpdateImpl(), BattlegroundDS::PostUpdateImpl(), spell_hor_gunship_cannon_fire::spell_hor_gunship_cannon_fireAuraScript::PrepareAuraScript(), spell_pos_empowered_blizzard::spell_pos_empowered_blizzardAuraScript::PrepareAuraScript(), spell_valkyr_touch::spell_valkyr_touchAuraScript::PrepareAuraScript(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::PrepareChamberIllusion(), Player::PrepareCharmAISpells(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::PrepareIceCrownIllusion(), spell_fight_fire_bomber::spell_fight_fire_bomber_SpellScript::PrepareSpellScript(), spell_gen_spectator_cheer_trigger::PrepareSpellScript(), spell_item_titanium_seal_of_dalaran::PrepareSpellScript(), spell_q11653_youre_not_so_big_now::PrepareSpellScript(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::PrepareStormwindIllusion(), SmartScript::ProcessAction(), RAND(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::randEntry(), TaskScheduler::RandomDurationBetween(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::RandomizeCompositionsAndShow(), Acore::Containers::RandomResize(), npc_hourglass_of_eternity::npc_hourglass_of_eternityAI::randomWhisper(), randtime(), SmartScript::RecalcTimer(), Weather::ReGenerate(), npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI::Reset(), boss_balinda::boss_balindaAI::Reset(), boss_drekthar::boss_drektharAI::Reset(), boss_galvangar::boss_galvangarAI::Reset(), boss_vanndar::boss_vanndarAI::Reset(), boss_golemagg::boss_golemaggAI::Reset(), boss_bigbadwolf::boss_bigbadwolfAI::Reset(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::Reset(), npc_akilzon_eagle::npc_akilzon_eagleAI::Reset(), npc_halazzi_lynx::npc_halazzi_lynxAI::Reset(), boss_nalorakk::boss_nalorakkAI::Reset(), npc_vilebranch_speaker::npc_vilebranch_speakerAI::Reset(), boss_renataki::boss_renatakiAI::Reset(), boss_azuregos::boss_azuregosAI::Reset(), boss_kurinnaxx::boss_kurinnaxxAI::Reset(), boss_kri::boss_kriAI::Reset(), boss_vem::boss_vemAI::Reset(), boss_yauj::boss_yaujAI::Reset(), boss_fankriss::boss_fankrissAI::Reset(), boss_huhuran::boss_huhuranAI::Reset(), boss_ouro::boss_ouroAI::Reset(), boss_sartura::boss_sarturaAI::Reset(), npc_sartura_royal_guard::npc_sartura_royal_guardAI::Reset(), boss_veknilash::boss_veknilashAI::Reset(), boss_veklor::boss_veklorAI::Reset(), npc_injured_draenei::npc_injured_draeneiAI::Reset(), npc_kerlonian::npc_kerlonianAI::Reset(), npc_ringo::npc_ringoAI::Reset(), npc_shadowpriest_sezziz::npc_shadowpriest_sezzizAI::Reset(), npc_twilight_summon::npc_twilight_summonAI::Reset(), npc_swarm_scarab::npc_swarm_scarabAI::Reset(), npc_nerubian_burrower::npc_nerubian_burrowerAI::Reset(), npc_fel_infernal::npc_fel_infernalAI::Reset(), npc_mistress_of_pain::npc_mistress_of_painAI::Reset(), npc_snobold_vassal::npc_snobold_vassalAI::Reset(), npc_cult_fanatic::npc_cult_fanaticAI::Reset(), npc_cult_adherent::npc_cult_adherentAI::Reset(), npc_darnavan::npc_darnavanAI::Reset(), boss_lord_marrowgar::Reset(), npc_spinestalker::npc_spinestalkerAI::Reset(), npc_rimefang::npc_rimefangAI::Reset(), npc_sindragosa_trash::npc_sindragosa_trashAI::Reset(), npc_shambling_horror_icc::npc_shambling_horror_iccAI::Reset(), npc_raging_spirit::npc_raging_spiritAI::Reset(), npc_spirit_warden::npc_spirit_wardenAI::Reset(), npc_risen_archmage::npc_risen_archmageAI::Reset(), npc_blazing_skeleton::npc_blazing_skeletonAI::Reset(), npc_gluttonous_abomination::npc_gluttonous_abominationAI::Reset(), npc_rotting_frost_giant::npc_rotting_frost_giantAI::Reset(), npc_crok_scourgebane::npc_crok_scourgebaneAI::Reset(), npc_captain_arnath::npc_captain_arnathAI::Reset(), npc_captain_brandon::npc_captain_brandonAI::Reset(), npc_captain_grondel::npc_captain_grondelAI::Reset(), npc_captain_rupert::npc_captain_rupertAI::Reset(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::Reset(), npc_arthas_teleport_visual::npc_arthas_teleport_visualAI::Reset(), npc_icc_spire_frostwyrm::npc_icc_spire_frostwyrmAI::Reset(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::Reset(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::Reset(), boss_bjarngrim::boss_bjarngrimAI::Reset(), npc_algalon_worm_hole::npc_algalon_worm_holeAI::Reset(), boss_auriaya::boss_auriayaAI::Reset(), npc_mechanolift::npc_mechanoliftAI::Reset(), boss_freya::boss_freyaAI::Reset(), npc_ulduar_dark_rune_sentinel::npc_ulduar_dark_rune_sentinelAI::Reset(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::Reset(), npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI::Reset(), npc_vrykul_skeleton::npc_vrykul_skeletonAI::Reset(), npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI::Reset(), boss_palehoof::boss_palehoofAI::Reset(), boss_ymiron::boss_ymironAI::Reset(), boss_ichoron::boss_ichoronAI::Reset(), npc_valiance_keep_cannoneer::npc_valiance_keep_cannoneerAI::Reset(), npc_injured_7th_legion_soldier::npc_injured_7th_legion_soldierAI::Reset(), boss_illidan_stormrage::boss_illidan_stormrageAI::Reset(), boss_doomlord_kazzak::boss_doomlordkazzakAI::Reset(), boss_doomwalker::boss_doomwalkerAI::Reset(), npc_invis_infernal_caster::npc_invis_infernal_casterAI::Reset(), npc_pet_hunter_snake_trap::Reset(), emerald_dragonAI::Reset(), npc_firework::npc_fireworkAI::Reset(), npc_spring_rabbit::npc_spring_rabbitAI::Reset(), BattlegroundAV::ResetBGSubclass(), Unit::RollMeleeOutcomeAgainst(), npc_time_lost_proto_drake::npc_time_lost_proto_drakeAI::RollPath(), boss_bjarngrim::boss_bjarngrimAI::RollStance(), npc_shandy_dalaran::npc_shandy_dalaranAI::RollTask(), npc_dark_iron_guzzler::npc_dark_iron_guzzlerAI::SayText(), npc_ulduar_hodir_priest::npc_ulduar_hodir_priestAI::ScheduleAbilities(), boss_grand_champion::boss_grand_championAI::ScheduleAbilitiesEvents(), boss_jormungarAI::ScheduleEvents(), boss_yoggsaron_constrictor_tentacle::boss_yoggsaron_constrictor_tentacleAI::SelectConstrictTarget(), boss_yoggsaron_corruptor_tentacle::boss_yoggsaron_corruptor_tentacleAI::SelectCorruptionTarget(), Creature::SelectLevel(), boss_skadi_grauf::boss_skadi_graufAI::SelectNextPos(), npc_midsummer_torch_target::npc_midsummer_torch_targetAI::SelectPosition(), npc_finklestein::npc_finklesteinAI::SelectRandomCode(), Acore::Containers::SelectRandomContainerElement(), ScriptedAI::SelectSpell(), boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::SelectT(), UnitAI::SelectTarget(), ScriptedAI::SelectTargetFromPlayerList(), World::SendAutoBroadcast(), CreatureTextMgr::SendChat(), npc_xt002_heart::npc_xt002_heartAI::SendEnergyToCorner(), Player::SendLoot(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::SetData(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::SetData(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::SetData(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::SetData(), boss_onyxia::boss_onyxiaAI::SetPhase(), BattlefieldWG::SetupBattlefield(), boss_thorim::boss_thorimAI::SpawnArenaNPCs(), boss_skadi_grauf::boss_skadi_graufAI::SpawnHelpers(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::SpawnTentacle(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::spawnVoidTraveler(), boss_freya::boss_freyaAI::SpawnWave(), npc_varian_wrynn::npc_varian_wrynnAI::SpawnWave(), npc_thrall_bfu::npc_thrall_bfuAI::SpawnWave(), npc_omen::npc_omenAI::SpellHit(), boss_gothik::boss_gothikAI::SpellHit(), boss_black_knight::boss_black_knightAI::SpellHitTarget(), npc_pos_leader_second::npc_pos_leader_secondAI::SpellHitTarget(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::SpellSounds(), npc_shay_leafrunner::npc_shay_leafrunnerAI::sQuestAccept(), npc_still_at_it_trigger::npc_still_at_it_triggerAI::Start(), boss_heigan::boss_heiganAI::StartFightPhase(), BattlegroundAB::StartingEventOpenDoors(), BattlegroundDS::StartingEventOpenDoors(), BattlegroundEY::StartingEventOpenDoors(), npc_grimstone::npc_grimstoneAI::SummonBoss(), brann_bronzebeard::brann_bronzebeardAI::SummonCreatures(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::SummonDeathOrbs(), boss_sjonnir::boss_sjonnirAI::SummonDwarfes(), boss_kelthuzad::boss_kelthuzadAI::SummonHelper(), boss_noth::boss_nothAI::SummonHelper(), boss_yoggsaron::boss_yoggsaronAI::SummonImmortalGuardian(), boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI::SummonMechanics(), boss_paletress::boss_paletressAI::SummonMemory(), npc_medivh_bm::npc_medivh_bmAI::SummonOrcs(), boss_ambassador_flamelash::boss_ambassador_flamelashAI::SummonSpirits(), go_tadpole_cage::go_tadpole_cageAI::SummonTadpoles(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::SummonWaveP1(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::SummonWaveP2(), boss_nightbane::boss_nightbaneAI::TakeOff(), BattlegroundSA::TeleportToEntrancePosition(), spell_midsummer_fling_torch::spell_midsummer_fling_torch_SpellScript::ThrowNextTorch(), TriggerBurningPitch(), boss_twinemperorsAI::TwinReset(), boss_archimonde::boss_archimondeAI::UnleashSoulCharge(), spell_item_goblin_gumbo_kettle::Update(), spell_illidari_council_deadly_strike::spell_illidari_council_deadly_strike_AuraScript::Update(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::Update(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::Update(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::Update(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::Update(), instance_naxxramas::instance_naxxramas_InstanceMapScript::Update(), instance_violet_hold::instance_violet_hold_InstanceMapScript::Update(), GameObject::Update(), Creature::Update(), npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI::UpdateAI(), boss_balinda::boss_balindaAI::UpdateAI(), boss_drekthar::boss_drektharAI::UpdateAI(), boss_galvangar::boss_galvangarAI::UpdateAI(), boss_vanndar::boss_vanndarAI::UpdateAI(), chromatic_elite_guard::chromatic_elite_guardAI::UpdateAI(), boss_gyth::boss_gythAI::UpdateAI(), boss_halycon::boss_halyconAI::UpdateAI(), boss_lord_valthalak::boss_lord_valthalakAI::UpdateAI(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::UpdateAI(), boss_rend_blackhand::boss_rend_blackhandAI::UpdateAI(), npc_rookery_hatcher::npc_rookery_hatcherAI::UpdateAI(), boss_urok_doomhowl::boss_urok_doomhowlAI::UpdateAI(), boss_victor_nefarius::boss_victor_nefariusAI::UpdateAI(), boss_nefarian::boss_nefarianAI::UpdateAI(), boss_razorgore::boss_razorgoreAI::UpdateAI(), boss_ragnaros::boss_ragnarosAI::UpdateAI(), npc_flamewaker_priest::npc_flamewaker_priestAI::UpdateAI(), npc_mc_core_hound::npc_mc_core_houndAI::UpdateAI(), boss_curator::boss_curatorAI::UpdateAI(), boss_maiden_of_virtue::boss_maiden_of_virtueAI::UpdateAI(), boss_attumen::boss_attumenAI::UpdateAI(), boss_attumen_midnight::boss_attumen_midnightAI::UpdateAI(), boss_moroes::boss_moroesAI::UpdateAI(), boss_netherspite::boss_netherspiteAI::UpdateAI(), boss_nightbane::boss_nightbaneAI::UpdateAI(), boss_malchezaar::boss_malchezaarAI::UpdateAI(), prince_axes::prince_axesAI::UpdateAI(), boss_servant_quarters::boss_servant_quartersAI::UpdateAI(), boss_shade_of_aran::boss_aranAI::UpdateAI(), npc_aran_elemental::water_elementalAI::UpdateAI(), npc_kilrek::npc_kilrekAI::UpdateAI(), boss_terestian_illhoof::boss_terestianAI::UpdateAI(), boss_roar::boss_roarAI::UpdateAI(), boss_crone::boss_croneAI::UpdateAI(), npc_cyclone::npc_cycloneAI::UpdateAI(), boss_bigbadwolf::boss_bigbadwolfAI::UpdateAI(), boss_julianne::boss_julianneAI::UpdateAI(), boss_romulo::boss_romuloAI::UpdateAI(), boss_felblood_kaelthas::boss_felblood_kaelthasAI::UpdateAI(), boss_priestess_delrissa::boss_priestess_delrissaAI::UpdateAI(), boss_priestess_lackey_commonAI::UpdateAI(), npc_high_inquisitor_valroth::npc_high_inquisitor_valrothAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), npc_mograine::npc_mograineAI::UpdateAI(), boss_darkmaster_gandling::boss_darkmaster_gandlingAI::UpdateAI(), boss_kirtonos_the_herald::boss_kirtonos_the_heraldAI::UpdateAI(), npc_scholomance_occultist::npc_scholomance_occultistAI::UpdateAI(), boss_sacrolash::boss_sacrolashAI::UpdateAI(), boss_alythess::boss_alythessAI::UpdateAI(), boss_felmyst::boss_felmystAI::UpdateAI(), boss_kalecgos::boss_kalecgosAI::UpdateAI(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::UpdateAI(), boss_kiljaeden::boss_kiljaedenAI::UpdateAI(), npc_balance_of_light_and_shadow::npc_balance_of_light_and_shadowAI::UpdateAI(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::UpdateAI(), npc_varian_wrynn::npc_varian_wrynnAI::UpdateAI(), npc_thrall_bfu::npc_thrall_bfuAI::UpdateAI(), npc_lady_sylvanas_windrunner_bfu::npc_lady_sylvanas_windrunner_bfuAI::UpdateAI(), boss_akilzon::boss_akilzonAI::UpdateAI(), npc_akilzon_eagle::npc_akilzon_eagleAI::UpdateAI(), boss_halazzi::boss_halazziAI::UpdateAI(), npc_halazzi_lynx::npc_halazzi_lynxAI::UpdateAI(), boss_hexlord_malacrass::boss_hex_lord_malacrassAI::UpdateAI(), boss_alyson_antille::boss_alyson_antilleAI::UpdateAI(), boss_nalorakk::boss_nalorakkAI::UpdateAI(), boss_zuljin::boss_zuljinAI::UpdateAI(), npc_forest_frog::npc_forest_frogAI::UpdateAI(), boss_arlokk::boss_arlokkAI::UpdateAI(), boss_gahzranka::boss_gahzrankaAI::UpdateAI(), boss_grilek::boss_grilekAI::UpdateAI(), boss_hakkar::boss_hakkarAI::UpdateAI(), boss_hazzarah::boss_hazzarahAI::UpdateAI(), boss_jeklik::boss_jeklikAI::UpdateAI(), boss_jindo::boss_jindoAI::UpdateAI(), boss_mandokir::boss_mandokirAI::UpdateAI(), npc_ohgan::npc_ohganAI::UpdateAI(), npc_vilebranch_speaker::npc_vilebranch_speakerAI::UpdateAI(), boss_marli::boss_marliAI::UpdateAI(), boss_renataki::boss_renatakiAI::UpdateAI(), boss_thekal::boss_thekalAI::UpdateAI(), npc_zealot_lorkhan::npc_zealot_lorkhanAI::UpdateAI(), boss_venoxis::boss_venoxisAI::UpdateAI(), boss_wushoolay::boss_wushoolayAI::UpdateAI(), npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::UpdateAI(), boss_headless_horseman_head::boss_headless_horseman_headAI::UpdateAI(), boss_azuregos::boss_azuregosAI::UpdateAI(), boss_anetheron::boss_anetheronAI::UpdateAI(), boss_archimonde::boss_archimondeAI::UpdateAI(), boss_salramm::boss_salrammAI::UpdateAI(), boss_onyxia::boss_onyxiaAI::UpdateAI(), npc_onyxian_lair_guard::npc_onyxian_lair_guardAI::UpdateAI(), npc_belnistrasz::npc_belnistraszAI::UpdateAI(), boss_ayamiss::boss_ayamissAI::UpdateAI(), boss_kurinnaxx::boss_kurinnaxxAI::UpdateAI(), boss_moam::boss_moamAI::UpdateAI(), boss_ossirian::boss_ossirianAI::UpdateAI(), boss_kri::boss_kriAI::UpdateAI(), boss_vem::boss_vemAI::UpdateAI(), boss_yauj::boss_yaujAI::UpdateAI(), boss_cthun::cthunAI::UpdateAI(), boss_fankriss::boss_fankrissAI::UpdateAI(), boss_huhuran::boss_huhuranAI::UpdateAI(), boss_ouro::boss_ouroAI::UpdateAI(), boss_sartura::boss_sarturaAI::UpdateAI(), npc_sartura_royal_guard::npc_sartura_royal_guardAI::UpdateAI(), boss_skeram::boss_skeramAI::UpdateAI(), boss_viscidus::boss_viscidusAI::UpdateAI(), npc_shay_leafrunner::npc_shay_leafrunnerAI::UpdateAI(), npc_omen::npc_omenAI::UpdateAI(), npc_qiraj_war_spawn::npc_qiraj_war_spawnAI::UpdateAI(), npc_shadowpriest_sezziz::npc_shadowpriest_sezzizAI::UpdateAI(), boss_elder_nadox::boss_elder_nadoxAI::UpdateAI(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::UpdateAI(), boss_sartharion::boss_sartharionAI::UpdateAI(), boss_halion::boss_halionAI::UpdateAI(), boss_twilight_halion::boss_twilight_halionAI::UpdateAI(), boss_saviana_ragefire::boss_saviana_ragefireAI::UpdateAI(), boss_paletress::boss_paletressAI::UpdateAI(), npc_memory::npc_memoryAI::UpdateAI(), npc_argent_soldier::npc_argent_soldierAI::UpdateAI(), boss_black_knight::boss_black_knightAI::UpdateAI(), npc_black_knight_ghoul::npc_black_knight_ghoulAI::UpdateAI(), npc_toc5_grand_champion_minion::npc_toc5_grand_champion_minionAI::UpdateAI(), boss_grand_champion::boss_grand_championAI::UpdateAI(), boss_anubarak_trial::boss_anubarak_trialAI::UpdateAI(), npc_swarm_scarab::npc_swarm_scarabAI::UpdateAI(), npc_nerubian_burrower::npc_nerubian_burrowerAI::UpdateAI(), boss_faction_championsAI::UpdateAI(), npc_toc_druid::npc_toc_druidAI::UpdateAI(), npc_toc_shaman::npc_toc_shamanAI::UpdateAI(), npc_toc_paladin::npc_toc_paladinAI::UpdateAI(), npc_toc_priest::npc_toc_priestAI::UpdateAI(), npc_toc_shadow_priest::npc_toc_shadow_priestAI::UpdateAI(), npc_toc_warlock::npc_toc_warlockAI::UpdateAI(), npc_toc_mage::npc_toc_mageAI::UpdateAI(), npc_toc_hunter::npc_toc_hunterAI::UpdateAI(), npc_toc_boomkin::npc_toc_boomkinAI::UpdateAI(), npc_toc_warrior::npc_toc_warriorAI::UpdateAI(), npc_toc_dk::npc_toc_dkAI::UpdateAI(), npc_toc_rogue::npc_toc_rogueAI::UpdateAI(), npc_toc_enh_shaman::npc_toc_enh_shamanAI::UpdateAI(), npc_toc_retro_paladin::npc_toc_retro_paladinAI::UpdateAI(), npc_toc_pet_warlock::npc_toc_pet_warlockAI::UpdateAI(), npc_toc_pet_hunter::npc_toc_pet_hunterAI::UpdateAI(), boss_jaraxxus::boss_jaraxxusAI::UpdateAI(), npc_mistress_of_pain::npc_mistress_of_painAI::UpdateAI(), npc_snobold_vassal::npc_snobold_vassalAI::UpdateAI(), boss_gormok::boss_gormokAI::UpdateAI(), boss_jormungarAI::UpdateAI(), boss_icehowl::boss_icehowlAI::UpdateAI(), boss_twin_valkyrAI::UpdateAI(), boss_tharon_ja::boss_tharon_jaAI::UpdateAI(), boss_trollgore::boss_trollgoreAI::UpdateAI(), boss_bronjahm::boss_bronjahmAI::UpdateAI(), boss_devourer_of_souls::boss_devourer_of_soulsAI::UpdateAI(), npc_hor_spiritual_reflection::npc_hor_spiritual_reflectionAI::UpdateAI(), boss_garfrost::boss_garfrostAI::UpdateAI(), boss_ick::boss_ickAI::UpdateAI(), boss_tyrannus::boss_tyrannusAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI::UpdateAI(), npc_pos_icicle_trigger::npc_pos_icicle_triggerAI::UpdateAI(), boss_eck::boss_eckAI::UpdateAI(), boss_moorabi::boss_moorabiAI::UpdateAI(), boss_slad_ran::boss_slad_ranAI::UpdateAI(), boss_prince_keleseth_icc::boss_prince_kelesethAI::UpdateAI(), boss_prince_taldaram_icc::boss_prince_taldaramAI::UpdateAI(), boss_prince_valanar_icc::boss_prince_valanarAI::UpdateAI(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::UpdateAI(), boss_deathbringer_saurfang::boss_deathbringer_saurfangAI::UpdateAI(), boss_festergut::boss_festergutAI::UpdateAI(), npc_stinky_icc::npc_stinky_iccAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), npc_gunship_boarding_leader::npc_gunship_boarding_leaderAI::UpdateAI(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::UpdateAI(), npc_cult_fanatic::npc_cult_fanaticAI::UpdateAI(), npc_cult_adherent::npc_cult_adherentAI::UpdateAI(), npc_darnavan::npc_darnavanAI::UpdateAI(), boss_lord_marrowgar::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), boss_rotface::boss_rotfaceAI::UpdateAI(), npc_precious_icc::npc_precious_iccAI::UpdateAI(), boss_sindragosa::boss_sindragosaAI::UpdateAI(), npc_spinestalker::npc_spinestalkerAI::UpdateAI(), npc_rimefang::npc_rimefangAI::UpdateAI(), npc_sindragosa_trash::npc_sindragosa_trashAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), npc_shambling_horror_icc::npc_shambling_horror_iccAI::UpdateAI(), npc_raging_spirit::npc_raging_spiritAI::UpdateAI(), npc_spirit_warden::npc_spirit_wardenAI::UpdateAI(), boss_valithria_dreamwalker::boss_valithria_dreamwalkerAI::UpdateAI(), npc_risen_archmage::npc_risen_archmageAI::UpdateAI(), npc_blazing_skeleton::npc_blazing_skeletonAI::UpdateAI(), npc_gluttonous_abomination::npc_gluttonous_abominationAI::UpdateAI(), npc_rotting_frost_giant::npc_rotting_frost_giantAI::UpdateAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI(), boss_sister_svalna::boss_sister_svalnaAI::UpdateAI(), npc_captain_arnath::npc_captain_arnathAI::UpdateAI(), npc_captain_brandon::npc_captain_brandonAI::UpdateAI(), npc_captain_grondel::npc_captain_grondelAI::UpdateAI(), npc_captain_rupert::npc_captain_rupertAI::UpdateAI(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::UpdateAI(), npc_arthas_teleport_visual::npc_arthas_teleport_visualAI::UpdateAI(), npc_icc_skybreaker_hierophant::npc_icc_skybreaker_hierophantAI::UpdateAI(), npc_icc_skybreaker_marksman::npc_icc_skybreaker_marksmanAI::UpdateAI(), npc_icc_skybreaker_vicar::npc_icc_skybreaker_vicarAI::UpdateAI(), npc_icc_skybreaker_luminary::npc_icc_skybreaker_luminaryAI::UpdateAI(), npc_icc_spire_frostwyrm::npc_icc_spire_frostwyrmAI::UpdateAI(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::UpdateAI(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::UpdateAI(), boss_faerlina::boss_faerlinaAI::UpdateAI(), boss_gluth::boss_gluthAI::UpdateAI(), boss_gothik::boss_gothikAI::UpdateAI(), npc_boss_gothik_minion::npc_boss_gothik_minionAI::UpdateAI(), boss_heigan::boss_heiganAI::UpdateAI(), boss_kelthuzad::boss_kelthuzadAI::UpdateAI(), boss_maexxna::boss_maexxnaAI::UpdateAI(), boss_sapphiron::boss_sapphironAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_nexus_lord::npc_nexus_lordAI::UpdateAI(), npc_scion_of_eternity::npc_scion_of_eternityAI::UpdateAI(), boss_commander_stoutbeard::boss_commander_stoutbeardAI::UpdateAI(), boss_drakos::boss_drakosAI::UpdateAI(), boss_eregos::boss_eregosAI::UpdateAI(), boss_urom::boss_uromAI::UpdateAI(), boss_varos::boss_varosAI::UpdateAI(), boss_algalon_the_observer::boss_algalon_the_observerAI::UpdateAI(), boss_steelbreaker::boss_steelbreakerAI::UpdateAI(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::UpdateAI(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI(), npc_mechanolift::npc_mechanoliftAI::UpdateAI(), boss_freya::boss_freyaAI::UpdateAI(), boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI::UpdateAI(), boss_vezax::boss_vezaxAI::UpdateAI(), boss_hodir::boss_hodirAI::UpdateAI(), npc_ulduar_hodir_priest::npc_ulduar_hodir_priestAI::UpdateAI(), boss_ignis::boss_ignisAI::UpdateAI(), boss_kologarn::boss_kologarnAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_ulduar_leviathan_mkii::npc_ulduar_leviathan_mkiiAI::UpdateAI(), boss_razorscale::boss_razorscaleAI::UpdateAI(), npc_ulduar_dark_rune_guardian::npc_ulduar_dark_rune_guardianAI::UpdateAI(), npc_ulduar_dark_rune_watcher::npc_ulduar_dark_rune_watcherAI::UpdateAI(), npc_ulduar_dark_rune_sentinel::npc_ulduar_dark_rune_sentinelAI::UpdateAI(), boss_thorim_sif::boss_thorim_sifAI::UpdateAI(), boss_thorim_runic_colossus::boss_thorim_runic_colossusAI::UpdateAI(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateAI(), npc_ulduar_storm_tempered_keeper::npc_ulduar_storm_tempered_keeperAI::UpdateAI(), npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI::UpdateAI(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::UpdateAI(), boss_keleseth::boss_kelesethAI::UpdateAI(), npc_vrykul_skeleton::npc_vrykul_skeletonAI::UpdateAI(), boss_skarvald_the_constructor::boss_skarvald_the_constructorAI::UpdateAI(), boss_dalronn_the_controller::boss_dalronn_the_controllerAI::UpdateAI(), npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI::UpdateAI(), boss_svala::boss_svalaAI::UpdateAI(), boss_emalon::boss_emalonAI::UpdateAI(), boss_cyanigosa::boss_cyanigosaAI::UpdateAI(), boss_erekem::boss_erekemAI::UpdateAI(), npc_erekem_guard::npc_erekem_guardAI::UpdateAI(), boss_lavanthor::boss_lavanthorAI::UpdateAI(), boss_moragg::boss_moraggAI::UpdateAI(), boss_zuramat::boss_zuramatAI::UpdateAI(), violet_hold_trashAI::UpdateAI(), npc_azure_invader::npc_azure_invaderAI::UpdateAI(), npc_azure_raider::npc_azure_raiderAI::UpdateAI(), npc_azure_sorceror::npc_azure_sorcerorAI::UpdateAI(), npc_valiance_keep_cannoneer::npc_valiance_keep_cannoneerAI::UpdateAI(), npc_minigob_manabonk::npc_minigob_manabonkAI::UpdateAI(), npc_dalaran_mage::npc_dalaran_mageAI::UpdateAI(), npc_dalaran_warrior::npc_dalaran_warriorAI::UpdateAI(), npc_q24545_vegard::npc_q24545_vegardAI::UpdateAI(), npc_commander_eligor_dawnbringer::npc_commander_eligor_dawnbringerAI::UpdateAI(), npc_torturer_lecraft::npc_torturer_lecraftAI::UpdateAI(), npc_blessed_banner::npc_blessed_bannerAI::UpdateAI(), npc_still_at_it_trigger::npc_still_at_it_triggerAI::UpdateAI(), npc_wild_wyrm::npc_wild_wyrmAI::UpdateAI(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::UpdateAI(), boss_exarch_maladaar::boss_exarch_maladaarAI::UpdateAI(), boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI::UpdateAI(), boss_nexusprince_shaffar::boss_nexusprince_shaffarAI::UpdateAI(), npc_yor::npc_yorAI::UpdateAI(), boss_pandemonius::boss_pandemoniusAI::UpdateAI(), boss_talon_king_ikiss::boss_talon_king_ikissAI::UpdateAI(), boss_anzu::boss_anzuAI::UpdateAI(), boss_ambassador_hellmaw::boss_ambassador_hellmawAI::UpdateAI(), boss_blackheart_the_inciter::boss_blackheart_the_inciterAI::UpdateAI(), boss_grandmaster_vorpil::boss_grandmaster_vorpilAI::UpdateAI(), boss_murmur::boss_murmurAI::UpdateAI(), boss_illidan_stormrage::boss_illidan_stormrageAI::UpdateAI(), boss_mother_shahraz::boss_shahrazAI::UpdateAI(), npc_akama_shade::npc_akamaAI::UpdateAI(), boss_supremus::boss_supremusAI::UpdateAI(), boss_najentus::boss_najentusAI::UpdateAI(), boss_doomlord_kazzak::boss_doomlordkazzakAI::UpdateAI(), boss_doomwalker::boss_doomwalkerAI::UpdateAI(), boss_fathomlord_karathress::boss_fathomlord_karathressAI::UpdateAI(), boss_lady_vashj::boss_lady_vashjAI::UpdateAI(), boss_morogrim_tidewalker::boss_morogrim_tidewalkerAI::UpdateAI(), boss_ahune::boss_ahuneAI::UpdateAI(), boss_hydromancer_thespia::boss_thespiaAI::UpdateAI(), boss_warlord_kalithresh::boss_warlord_kalithreshAI::UpdateAI(), boss_the_black_stalker::boss_the_black_stalkerAI::UpdateAI(), boss_broggok::boss_broggokAI::UpdateAI(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::UpdateAI(), npc_shadowmoon_channeler::npc_shadowmoon_channelerAI::UpdateAI(), boss_the_maker::boss_the_makerAI::UpdateAI(), boss_omor_the_unscarred::boss_omor_the_unscarredAI::UpdateAI(), boss_nazan::boss_nazanAI::UpdateAI(), boss_grand_warlock_nethekurse::boss_grand_warlock_nethekurseAI::UpdateAI(), boss_warbringer_omrogg::boss_warbringer_omroggAI::UpdateAI(), boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI::UpdateAI(), boss_dalliah_the_doomsayer::boss_dalliah_the_doomsayerAI::UpdateAI(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::UpdateAI(), boss_gatewatcher_gyrokill::boss_gatewatcher_gyrokillAI::UpdateAI(), boss_pathaleon_the_calculator::boss_pathaleon_the_calculatorAI::UpdateAI(), npc_maghar_captive::npc_maghar_captiveAI::UpdateAI(), adyen_the_lightbringer::adyen_the_lightbringerAI::UpdateAI(), exarch_orelis::exarch_orelisAI::UpdateAI(), npc_dragonmaw_peon::npc_dragonmaw_peonAI::UpdateAI(), npc_pet_hunter_snake_trap::UpdateAI(), npc_pet_shaman_earth_elemental::UpdateAI(), npc_pet_shaman_fire_elemental::UpdateAI(), npc_dream_fog::npc_dream_fogAI::UpdateAI(), go_flames::go_flamesAI::UpdateAI(), go_heat::go_heatAI::UpdateAI(), go_brewfest_music::go_brewfest_musicAI::UpdateAI(), npc_artorius::npc_artoriusAI::UpdateAI(), npc_simone::npc_simoneAI::UpdateAI(), npc_nelson::npc_nelsonAI::UpdateAI(), npc_franklin::npc_franklinAI::UpdateAI(), npc_spring_rabbit::npc_spring_rabbitAI::UpdateAI(), boss_ichoron::boss_ichoronAI::UpdateAI(), npc_warmage_coldarra::npc_warmage_coldarraAI::UpdateAI(), PetAI::UpdateAI(), Player::UpdateCharmedAI(), npc_onyx_flamecaller::npc_onyx_flamecallerAI::UpdateEscortAI(), brann_bronzebeard::brann_bronzebeardAI::UpdateEscortAI(), npc_akama_illidan::npc_akama_illidanAI::UpdateEscortAI(), npc_kurenai_captive::npc_kurenai_captiveAI::UpdateEscortAI(), npc_kerlonian::npc_kerlonianAI::UpdateFollowerAI(), npc_tooga::npc_toogaAI::UpdateFollowerAI(), npc_ringo::npc_ringoAI::UpdateFollowerAI(), boss_runemaster_molgeim::boss_runemaster_molgeimAI::UpdatePhase(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdatePhase(), urandms(), and boss_hexlord_malacrass::boss_hex_lord_malacrassAI::UseAbility().
urandms()
AC_COMMON_API uint32 urandms (uint32 min, uint32 max)
Definition at line 51 of file Random.cpp.
 {
     ASSERT(std::numeric_limits<uint32>::max() / Milliseconds::period::den >= max);
     return urand(min * Milliseconds::period::den, max * Milliseconds::period::den);
 }
References ASSERT, and urand().
urandweighted()
AC_COMMON_API uint32 urandweighted (size_t count, double const * chances)
Definition at line 89 of file Random.cpp.
 {
     std::discrete_distribution<uint32> dd(chances, chances + count);
     return dd(engine);
 }
References engine.
Referenced by Acore::Containers::SelectRandomWeightedContainerElement().