Azerotcore-wotlk: UpdateFetcher::AppliedFileEntry Struct Reference
UpdateFetcher::AppliedFileEntry Struct Reference
Public Member Functions
AppliedFileEntry (std::string const &name_, std::string const &hash_, State state_, uint64 timestamp_)
std::string GetStateAsString () const
Static Public Member Functions
static State StateConvert (std::string const &state)
static std::string StateConvert (State const state)
Public Attributes
std::string const name
std::string const hash
State const state
uint64 const timestamp
Detailed Description
Definition at line 71 of file UpdateFetcher.h.
Constructor & Destructor Documentation
AppliedFileEntry()
UpdateFetcher::AppliedFileEntry::AppliedFileEntry (std::string const & name_, std::string const & hash_, State state_, uint64 timestamp_) inline
Definition at line 73 of file UpdateFetcher.h.
             : name(name_), hash(hash_), state(state_), timestamp(timestamp_) { }
Member Function Documentation
GetStateAsString()
std::string UpdateFetcher::AppliedFileEntry::GetStateAsString () const inline
Definition at line 110 of file UpdateFetcher.h.
         {
             return StateConvert(state);
         }
Referenced by UpdateFetcher::UpdateEntry().
StateConvert() [1/2]
static std::string UpdateFetcher::AppliedFileEntry::StateConvert (State const state) inline static
Definition at line 93 of file UpdateFetcher.h.
         {
             switch (state)
             {
                 case RELEASED:
                     return "RELEASED";
                 case CUSTOM:
                     return "CUSTOM";
                 case MODULE:
                     return "MODULE";
                 case ARCHIVED:
                     return "ARCHIVED";
                 default:
                     return "";
             }
         }
StateConvert() [2/2]
static State UpdateFetcher::AppliedFileEntry::StateConvert (std::string const & state) inline static
Definition at line 81 of file UpdateFetcher.h.
         {
             if (state == "RELEASED")
                 return RELEASED;
             else if (state == "CUSTOM")
                 return CUSTOM;
             else if (state == "MODULE")
                 return MODULE;
             return ARCHIVED;
         }
Referenced by UpdateFetcher::FillFileListRecursively(), UpdateFetcher::ReceiveAppliedFiles(), UpdateFetcher::ReceiveIncludedDirectories(), UpdateFetcher::Update(), and UpdateFetcher::UpdateState().
Member Data Documentation
hash
std::string const UpdateFetcher::AppliedFileEntry::hash
Definition at line 77 of file UpdateFetcher.h.
Referenced by UpdateFetcher::UpdateEntry().
name
std::string const UpdateFetcher::AppliedFileEntry::name
Definition at line 76 of file UpdateFetcher.h.
Referenced by UpdateFetcher::ReceiveAppliedFiles(), and UpdateFetcher::UpdateEntry().
state
State const UpdateFetcher::AppliedFileEntry::state
Definition at line 78 of file UpdateFetcher.h.
timestamp
uint64 const UpdateFetcher::AppliedFileEntry::timestamp
Definition at line 79 of file UpdateFetcher.h.
The documentation for this struct was generated from the following file:
src/server/database/Updater/UpdateFetcher.h