Azerotcore-wotlk: Acore::AnyPlayerExactPositionInGameObjectRangeCheck Class Reference
Acore::AnyPlayerExactPositionInGameObjectRangeCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
AnyPlayerExactPositionInGameObjectRangeCheck (GameObject const *go, float range)
bool operator() (Player *u)
Private Attributes
GameObject const * _go
float _range
Detailed Description
Definition at line 1267 of file GridNotifiers.h.
Constructor & Destructor Documentation
AnyPlayerExactPositionInGameObjectRangeCheck()
Acore::AnyPlayerExactPositionInGameObjectRangeCheck::AnyPlayerExactPositionInGameObjectRangeCheck (GameObject const * go, float range) inline
Definition at line 1270 of file GridNotifiers.h.
 : _go(go), _range(range) {}
Member Function Documentation
operator()()
bool Acore::AnyPlayerExactPositionInGameObjectRangeCheck::operator() (Player * u) inline
Definition at line 1271 of file GridNotifiers.h.
         {
             if (!_go->IsInRange(u->GetPositionX(), u->GetPositionY(), u->GetPositionZ(), _range))
                 return false;
             return true;
         }
References _go, _range, Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), and GameObject::IsInRange().
Member Data Documentation
_go
GameObject const* Acore::AnyPlayerExactPositionInGameObjectRangeCheck::_go private
Definition at line 1280 of file GridNotifiers.h.
Referenced by operator()().
_range
float Acore::AnyPlayerExactPositionInGameObjectRangeCheck::_range private
Definition at line 1281 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/game/Grids/Notifiers/GridNotifiers.h