Azerotcore-wotlk: Acore::VisibleChangesNotifier Struct Reference
Acore::VisibleChangesNotifier Struct Reference
#include <GridNotifiers.h>
Public Member Functions
VisibleChangesNotifier (WorldObject &object)
template<class T >
void Visit (GridRefMgr< T > &)
void Visit (PlayerMapType &)
void Visit (CreatureMapType &)
void Visit (DynamicObjectMapType &)
Public Attributes
WorldObject & i_object
Detailed Description
Definition at line 61 of file GridNotifiers.h.
Constructor & Destructor Documentation
VisibleChangesNotifier()
Acore::VisibleChangesNotifier::VisibleChangesNotifier (WorldObject & object) inline explicit
Definition at line 65 of file GridNotifiers.h.
 : i_object(object) {}
Member Function Documentation
Visit() [1/4]
void VisibleChangesNotifier::Visit (CreatureMapType & m)
Definition at line 131 of file GridNotifiers.cpp.
 {
     for (CreatureMapType::iterator iter = m.begin(); iter != m.end(); ++iter)
         if (iter->GetSource()->HasSharedVision())
             for (SharedVisionList::const_iterator i = iter->GetSource()->GetSharedVisionList().begin(); i != iter->GetSource()->GetSharedVisionList().end(); ++i)
                 if ((*i)->m_seer == iter->GetSource())
                     (*i)->UpdateVisibilityOf(&i_object);
 }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), and i_object.
Visit() [2/4]
void VisibleChangesNotifier::Visit (DynamicObjectMapType & m)
Definition at line 140 of file GridNotifiers.cpp.
 {
     for (DynamicObjectMapType::iterator iter = m.begin(); iter != m.end(); ++iter)
         if (iter->GetSource()->GetCasterGUID().IsPlayer())
             if (Unit* caster = iter->GetSource()->GetCaster())
                 if (Player* player = caster->ToPlayer())
                     if (player->m_seer == iter->GetSource())
                         player->UpdateVisibilityOf(&i_object);
 }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), i_object, and Object::ToPlayer().
Visit() [3/4]
template<class T > void Acore::VisibleChangesNotifier::Visit (GridRefMgr< T > &) inline
Definition at line 66 of file GridNotifiers.h.
 {}
Visit() [4/4]
void VisibleChangesNotifier::Visit (PlayerMapType & m)
Definition at line 115 of file GridNotifiers.cpp.
 {
     for (PlayerMapType::iterator iter = m.begin(); iter != m.end(); ++iter)
     {
         if (iter->GetSource() == &i_object)
             continue;
         iter->GetSource()->UpdateVisibilityOf(&i_object);
         if (iter->GetSource()->HasSharedVision())
             for (SharedVisionList::const_iterator i = iter->GetSource()->GetSharedVisionList().begin(); i != iter->GetSource()->GetSharedVisionList().end(); ++i)
                 if ((*i)->m_seer == iter->GetSource())
                     (*i)->UpdateVisibilityOf(&i_object);
     }
 }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), and i_object.
Member Data Documentation
i_object
WorldObject& Acore::VisibleChangesNotifier::i_object
Definition at line 63 of file GridNotifiers.h.
Referenced by Visit().
The documentation for this struct was generated from the following files:
src/server/game/Grids/Notifiers/GridNotifiers.h
src/server/game/Grids/Notifiers/GridNotifiers.cpp