Azerotcore-wotlk: npc_announcer_toc5::npc_announcer_toc5AI Struct Reference
npc_announcer_toc5::npc_announcer_toc5AI Struct Reference
Public Member Functions
npc_announcer_toc5AI (Creature *creature)
void Reset () override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void MovementInform (uint32 type, uint32) override
void UpdateAI (uint32) override
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void EnterCombat (Unit *)
virtual void JustDied (Unit *)
virtual void KilledUnit (Unit *)
virtual void JustSummoned (Creature *)
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDespawn (Creature *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void SpellHit (Unit *, SpellInfo const *)
virtual void SpellHitTarget (Unit *, SpellInfo const *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void AttackStart (Unit *)
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Additional Inherited Members
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 101 of file trial_of_the_champion.cpp.
Constructor & Destructor Documentation
npc_announcer_toc5AI()
npc_announcer_toc5::npc_announcer_toc5AI::npc_announcer_toc5AI (Creature * creature) inline
Definition at line 103 of file trial_of_the_champion.cpp.
 : CreatureAI(creature) {}
Member Function Documentation
DamageTaken()
void npc_announcer_toc5::npc_announcer_toc5AI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from UnitAI.
Definition at line 115 of file trial_of_the_champion.cpp.
         {
             if (damage >= me->GetHealth()) // for bk scene so strangulate doesn't kill him
                 damage = me->GetHealth() - 1;
         }
References Unit::GetHealth(), and CreatureAI::me.
MovementInform()
void npc_announcer_toc5::npc_announcer_toc5AI::MovementInform (uint32 type, uint32) inline override virtual
Reimplemented from CreatureAI.
Definition at line 121 of file trial_of_the_champion.cpp.
         {
             if (type != EFFECT_MOTION_TYPE)
                 return;
             InstanceScript* pInstance = me->GetInstanceScript();
             if( !pInstance )
                 return;
             if (pInstance->GetData(DATA_INSTANCE_PROGRESS) < INSTANCE_PROGRESS_ARGENT_CHALLENGE_DIED)
                 return;
             Unit::Kill(me, me); // for bk scene, die after knockback
         }
References DATA_INSTANCE_PROGRESS, EFFECT_MOTION_TYPE, ZoneScript::GetData(), WorldObject::GetInstanceScript(), INSTANCE_PROGRESS_ARGENT_CHALLENGE_DIED, Unit::Kill(), and CreatureAI::me.
Reset()
void npc_announcer_toc5::npc_announcer_toc5AI::Reset () inline override virtual
Reimplemented from UnitAI.
Definition at line 105 of file trial_of_the_champion.cpp.
         {
             InstanceScript* pInstance = me->GetInstanceScript();
             if( !pInstance )
                 return;
             if( pInstance->GetData(DATA_TEAMID_IN_INSTANCE) == TEAM_ALLIANCE )
                 me->UpdateEntry(NPC_ARELAS);
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE); // removed during black knight scene
         }
References DATA_TEAMID_IN_INSTANCE, ZoneScript::GetData(), WorldObject::GetInstanceScript(), CreatureAI::me, NPC_ARELAS, Object::SetFlag(), TEAM_ALLIANCE, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and Creature::UpdateEntry().
UpdateAI()
void npc_announcer_toc5::npc_announcer_toc5AI::UpdateAI (uint32) inline override virtual
Implements UnitAI.
Definition at line 134 of file trial_of_the_champion.cpp.
 { }
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/CrusadersColiseum/TrialOfTheChampion/trial_of_the_champion.cpp