Azerotcore-wotlk: DatabaseLoader Class Reference
DatabaseLoader Class Reference
#include <DatabaseLoader.h>
Public Types
enum DatabaseTypeFlags {
DATABASE_NONE = 0 , DATABASE_LOGIN = 1 , DATABASE_CHARACTER = 2 , DATABASE_WORLD = 4 ,
DATABASE_MASK_ALL = DATABASE_LOGIN | DATABASE_CHARACTER | DATABASE_WORLD
}
Public Member Functions
DatabaseLoader (std::string const &logger, uint32 const defaultUpdateMask=0)
template<class T >
DatabaseLoader & AddDatabase (DatabaseWorkerPool< T > &pool, std::string const &name)
bool Load ()
uint32 GetUpdateFlags () const
Private Types
using Predicate = std::function< bool()>
using Closer = std::function< void()>
Private Member Functions
bool OpenDatabases ()
bool PopulateDatabases ()
bool UpdateDatabases ()
bool PrepareStatements ()
bool Process (std::queue< Predicate > &queue)
Private Attributes
std::string const _logger
bool const _autoSetup
uint32 const _updateFlags
std::queue< Predicate > _open
std::queue< Predicate > _populate
std::queue< Predicate > _update
std::queue< Predicate > _prepare
std::stack< Closer > _close
Detailed Description
Definition at line 32 of file DatabaseLoader.h.
Member Typedef Documentation
Closer
using DatabaseLoader::Closer = std::function<void()> private
Definition at line 67 of file DatabaseLoader.h.
Predicate
using DatabaseLoader::Predicate = std::function<bool()> private
Definition at line 66 of file DatabaseLoader.h.
Member Enumeration Documentation
DatabaseTypeFlags
enum DatabaseLoader::DatabaseTypeFlags
Enumerator
DATABASE_NONE
DATABASE_LOGIN
DATABASE_CHARACTER
DATABASE_WORLD
DATABASE_MASK_ALL
Definition at line 44 of file DatabaseLoader.h.
     {
         DATABASE_NONE       = 0,
         DATABASE_LOGIN      = 1,
         DATABASE_CHARACTER  = 2,
         DATABASE_WORLD      = 4,
         DATABASE_MASK_ALL   = DATABASE_LOGIN | DATABASE_CHARACTER | DATABASE_WORLD
     };
Constructor & Destructor Documentation
DatabaseLoader()
DatabaseLoader::DatabaseLoader (std::string const & logger, uint32 const defaultUpdateMask = 0)
Definition at line 28 of file DatabaseLoader.cpp.
     : _logger(logger), _autoSetup(sConfigMgr->GetOption<bool>("Updates.AutoSetup", true)),
     _updateFlags(sConfigMgr->GetOption<uint32>("Updates.EnableDatabases", defaultUpdateMask))
 {
 }
Member Function Documentation
AddDatabase()
template<class T > template AC_DATABASE_API DatabaseLoader & DatabaseLoader::AddDatabase< WorldDatabaseConnection > (DatabaseWorkerPool< T > & pool, std::string const & name)
Definition at line 35 of file DatabaseLoader.cpp.
 {
     bool const updatesEnabledForThis = DBUpdater<T>::IsEnabled(_updateFlags);
     _open.push([this, name, updatesEnabledForThis, &pool]() -> bool
     {
         std::string const dbString = sConfigMgr->GetOption<std::string>(name + "DatabaseInfo", "");
         if (dbString.empty())
         {
             LOG_ERROR(_logger, "Database %s not specified in configuration file!", name.c_str());
             return false;
         }
         uint8 const asyncThreads = sConfigMgr->GetOption<uint8>(name + "Database.WorkerThreads", 1);
         if (asyncThreads < 1 || asyncThreads > 32)
         {
             LOG_ERROR(_logger, "%s database: invalid number of worker threads specified. "
                       "Please pick a value between 1 and 32.", name.c_str());
             return false;
         }
         uint8 const synchThreads = sConfigMgr->GetOption<uint8>(name + "Database.SynchThreads", 1);
         pool.SetConnectionInfo(dbString, asyncThreads, synchThreads);
         if (uint32 error = pool.Open())
         {
             // Try reconnect
             if (error == CR_CONNECTION_ERROR)
             {
                 uint8 const attempts = sConfigMgr->GetOption<uint8>("Database.Reconnect.Attempts", 20);
                 Seconds reconnectSeconds = Seconds(sConfigMgr->GetOption<uint8>("Database.Reconnect.Seconds", 15));
                 uint8 reconnectCount = 0;
                 while (reconnectCount < attempts)
                 {
                     LOG_INFO(_logger, "> Retrying after %u seconds", static_cast<uint32>(reconnectSeconds.count()));
                     std::this_thread::sleep_for(reconnectSeconds);
                     error = pool.Open();
                     if (error == CR_CONNECTION_ERROR)
                     {
                         reconnectCount++;
                     }
                     else
                     {
                         break;
                     }
                 }
             }
             // Database does not exist
             if ((error == ER_BAD_DB_ERROR) && updatesEnabledForThis && _autoSetup && !sConfigMgr->isDryRun())
             {
                 // Try to create the database and connect again if auto setup is enabled
                 if (DBUpdater<T>::Create(pool) && (!pool.Open()))
                 {
                     error = 0;
                 }
             }
             // If the error wasn't handled quit
             if (error)
             {
                 LOG_ERROR(_logger, "DatabasePool %s NOT opened. There were errors opening the MySQL connections. "
                           "Check your log file for specific errors", name.c_str());
                 return false;
             }
         }
         // Add the close operation
         _close.push([&pool]
         {
             pool.Close();
         });
         return true;
     });
     // Populate and update only if updates are enabled for this pool
     if (updatesEnabledForThis && !sConfigMgr->isDryRun())
     {
         _populate.push([this, name, &pool]() -> bool
         {
             if (!DBUpdater<T>::Populate(pool))
             {
                 LOG_ERROR(_logger, "Could not populate the %s database, see log for details.", name.c_str());
                 return false;
             }
             return true;
         });
         _update.push([this, name, &pool]() -> bool
         {
             if (!DBUpdater<T>::Update(pool))
             {
                 LOG_ERROR(_logger, "Could not update the %s database, see log for details.", name.c_str());
                 return false;
             }
             return true;
         });
     }
     _prepare.push([this, name, &pool]() -> bool
     {
         if (!pool.PrepareStatements())
         {
             LOG_ERROR(_logger, "Could not prepare statements of the %s database, see log for details.", name.c_str());
             return false;
         }
         return true;
     });
     return *this;
 }
References _autoSetup, _close, _logger, _open, _populate, _prepare, _update, _updateFlags, DatabaseWorkerPool< T >::Close(), CR_CONNECTION_ERROR, ER_BAD_DB_ERROR, error(), DBUpdater< T >::IsEnabled(), LOG_ERROR, LOG_INFO, name, DatabaseWorkerPool< T >::Open(), DatabaseWorkerPool< T >::PrepareStatements(), sConfigMgr, and DatabaseWorkerPool< T >::SetConnectionInfo().
Referenced by StartDB().
GetUpdateFlags()
uint32 DatabaseLoader::GetUpdateFlags () const inline
Definition at line 55 of file DatabaseLoader.h.
     {
         return _updateFlags;
     }
Referenced by StartDB().
Load()
bool DatabaseLoader::Load ()
Definition at line 154 of file DatabaseLoader.cpp.
 {
     return OpenDatabases() && PopulateDatabases() && UpdateDatabases() && PrepareStatements();
 }
References OpenDatabases(), PopulateDatabases(), PrepareStatements(), and UpdateDatabases().
Referenced by StartDB().
OpenDatabases()
bool DatabaseLoader::OpenDatabases () private
Definition at line 159 of file DatabaseLoader.cpp.
 {
     return Process(_open);
 }
References _open, and Process().
Referenced by Load().
PopulateDatabases()
bool DatabaseLoader::PopulateDatabases () private
Definition at line 164 of file DatabaseLoader.cpp.
 {
     return Process(_populate);
 }
References _populate, and Process().
Referenced by Load().
PrepareStatements()
bool DatabaseLoader::PrepareStatements () private
Definition at line 174 of file DatabaseLoader.cpp.
 {
     return Process(_prepare);
 }
References _prepare, and Process().
Referenced by Load().
Process()
bool DatabaseLoader::Process (std::queue< Predicate > & queue) private
Definition at line 179 of file DatabaseLoader.cpp.
 {
     while (!queue.empty())
     {
         if (!queue.front()())
         {
             // Close all open databases which have a registered close operation
             while (!_close.empty())
             {
                 _close.top()();
                 _close.pop();
             }
             return false;
         }
         queue.pop();
     }
     return true;
 }
References _close.
Referenced by OpenDatabases(), PopulateDatabases(), PrepareStatements(), and UpdateDatabases().
UpdateDatabases()
bool DatabaseLoader::UpdateDatabases () private
Definition at line 169 of file DatabaseLoader.cpp.
 {
     return Process(_update);
 }
References _update, and Process().
Referenced by Load().
Member Data Documentation
_autoSetup
bool const DatabaseLoader::_autoSetup private
Definition at line 74 of file DatabaseLoader.h.
Referenced by AddDatabase().
_close
std::stack<Closer> DatabaseLoader::_close private
Definition at line 78 of file DatabaseLoader.h.
Referenced by AddDatabase(), and Process().
_logger
std::string const DatabaseLoader::_logger private
Definition at line 73 of file DatabaseLoader.h.
Referenced by AddDatabase().
_open
std::queue<Predicate> DatabaseLoader::_open private
Definition at line 77 of file DatabaseLoader.h.
Referenced by AddDatabase(), and OpenDatabases().
_populate
std::queue<Predicate> DatabaseLoader::_populate private
Definition at line 77 of file DatabaseLoader.h.
Referenced by AddDatabase(), and PopulateDatabases().
_prepare
std::queue<Predicate> DatabaseLoader::_prepare private
Definition at line 77 of file DatabaseLoader.h.
Referenced by AddDatabase(), and PrepareStatements().
_update
std::queue<Predicate> DatabaseLoader::_update private
Definition at line 77 of file DatabaseLoader.h.
Referenced by AddDatabase(), and UpdateDatabases().
_updateFlags
uint32 const DatabaseLoader::_updateFlags private
Definition at line 75 of file DatabaseLoader.h.
Referenced by AddDatabase().
The documentation for this class was generated from the following files:
src/server/database/Database/DatabaseLoader.h
src/server/database/Database/DatabaseLoader.cpp