Azerotcore-wotlk: ObjectDataHandler Class Reference
ObjectDataHandler Class Reference abstract
#include <ObjectDataHandler.h>
Public Member Functions
ObjectDataHandler (ADT *_adt)
void ProcessMapChunk (MapChunk *chunk)
virtual void ProcessInternal (MapChunk *data)=0
Public Attributes
ADT * Source
Detailed Description
Definition at line 23 of file ObjectDataHandler.h.
Constructor & Destructor Documentation
ObjectDataHandler()
ObjectDataHandler::ObjectDataHandler (ADT * _adt) inline
Definition at line 26 of file ObjectDataHandler.h.
 : Source(_adt) {}
Member Function Documentation
ProcessInternal()
virtual void ObjectDataHandler::ProcessInternal (MapChunk * data) pure virtual
Implemented in WorldModelHandler, and DoodadHandler.
Referenced by ProcessMapChunk().
ProcessMapChunk()
void ObjectDataHandler::ProcessMapChunk (MapChunk * chunk)
Definition at line 23 of file ObjectDataHandler.cpp.
 {
     ProcessInternal(chunk);
 }
References ProcessInternal().
Referenced by ADT::Read().
Member Data Documentation
Source
ADT* ObjectDataHandler::Source
Definition at line 30 of file ObjectDataHandler.h.
Referenced by WorldModelHandler::ReadDefinitions(), and WorldModelHandler::ReadModelPaths().
The documentation for this class was generated from the following files:
src/tools/mesh_extractor/ObjectDataHandler.h
src/tools/mesh_extractor/ObjectDataHandler.cpp