Azerotcore-wotlk: deps/fmt/include/fmt/color.h File Reference
color.h File Reference
#include "format.h"
Classes
struct rgb
struct color_type
union color_type::color_union
class text_style
struct ansi_color_escape< Char >
Macros
#define FMT_DEPRECATED_NONMSVC FMT_DEPRECATED
Enumerations
enum class color : uint32_t {
alice_blue = 0xF0F8FF , antique_white = 0xFAEBD7 , aqua = 0x00FFFF , aquamarine = 0x7FFFD4 ,
azure = 0xF0FFFF , beige = 0xF5F5DC , bisque = 0xFFE4C4 , black = 0x000000 ,
blanched_almond = 0xFFEBCD , blue = 0x0000FF , blue_violet = 0x8A2BE2 , brown = 0xA52A2A ,
burly_wood = 0xDEB887 , cadet_blue = 0x5F9EA0 , chartreuse = 0x7FFF00 , chocolate = 0xD2691E ,
coral = 0xFF7F50 , cornflower_blue = 0x6495ED , cornsilk = 0xFFF8DC , crimson = 0xDC143C ,
cyan = 0x00FFFF , dark_blue = 0x00008B , dark_cyan = 0x008B8B , dark_golden_rod = 0xB8860B ,
dark_gray = 0xA9A9A9 , dark_green = 0x006400 , dark_khaki = 0xBDB76B , dark_magenta = 0x8B008B ,
dark_olive_green = 0x556B2F , dark_orange = 0xFF8C00 , dark_orchid = 0x9932CC , dark_red = 0x8B0000 ,
dark_salmon = 0xE9967A , dark_sea_green = 0x8FBC8F , dark_slate_blue = 0x483D8B , dark_slate_gray = 0x2F4F4F ,
dark_turquoise = 0x00CED1 , dark_violet = 0x9400D3 , deep_pink = 0xFF1493 , deep_sky_blue = 0x00BFFF ,
dim_gray = 0x696969 , dodger_blue = 0x1E90FF , fire_brick = 0xB22222 , floral_white = 0xFFFAF0 ,
forest_green = 0x228B22 , fuchsia = 0xFF00FF , gainsboro = 0xDCDCDC , ghost_white = 0xF8F8FF ,
gold = 0xFFD700 , golden_rod = 0xDAA520 , gray = 0x808080 , green = 0x008000 ,
green_yellow = 0xADFF2F , honey_dew = 0xF0FFF0 , hot_pink = 0xFF69B4 , indian_red = 0xCD5C5C ,
indigo = 0x4B0082 , ivory = 0xFFFFF0 , khaki = 0xF0E68C , lavender = 0xE6E6FA ,
lavender_blush = 0xFFF0F5 , lawn_green = 0x7CFC00 , lemon_chiffon = 0xFFFACD , light_blue = 0xADD8E6 ,
light_coral = 0xF08080 , light_cyan = 0xE0FFFF , light_golden_rod_yellow = 0xFAFAD2 , light_gray = 0xD3D3D3 ,
light_green = 0x90EE90 , light_pink = 0xFFB6C1 , light_salmon = 0xFFA07A , light_sea_green = 0x20B2AA ,
light_sky_blue = 0x87CEFA , light_slate_gray = 0x778899 , light_steel_blue = 0xB0C4DE , light_yellow = 0xFFFFE0 ,
lime = 0x00FF00 , lime_green = 0x32CD32 , linen = 0xFAF0E6 , magenta = 0xFF00FF ,
maroon = 0x800000 , medium_aquamarine = 0x66CDAA , medium_blue = 0x0000CD , medium_orchid = 0xBA55D3 ,
medium_purple = 0x9370DB , medium_sea_green = 0x3CB371 , medium_slate_blue = 0x7B68EE , medium_spring_green = 0x00FA9A ,
medium_turquoise = 0x48D1CC , medium_violet_red = 0xC71585 , midnight_blue = 0x191970 , mint_cream = 0xF5FFFA ,
misty_rose = 0xFFE4E1 , moccasin = 0xFFE4B5 , navajo_white = 0xFFDEAD , navy = 0x000080 ,
old_lace = 0xFDF5E6 , olive = 0x808000 , olive_drab = 0x6B8E23 , orange = 0xFFA500 ,
orange_red = 0xFF4500 , orchid = 0xDA70D6 , pale_golden_rod = 0xEEE8AA , pale_green = 0x98FB98 ,
pale_turquoise = 0xAFEEEE , pale_violet_red = 0xDB7093 , papaya_whip = 0xFFEFD5 , peach_puff = 0xFFDAB9 ,
peru = 0xCD853F , pink = 0xFFC0CB , plum = 0xDDA0DD , powder_blue = 0xB0E0E6 ,
purple = 0x800080 , rebecca_purple = 0x663399 , red = 0xFF0000 , rosy_brown = 0xBC8F8F ,
royal_blue = 0x4169E1 , saddle_brown = 0x8B4513 , salmon = 0xFA8072 , sandy_brown = 0xF4A460 ,
sea_green = 0x2E8B57 , sea_shell = 0xFFF5EE , sienna = 0xA0522D , silver = 0xC0C0C0 ,
sky_blue = 0x87CEEB , slate_blue = 0x6A5ACD , slate_gray = 0x708090 , snow = 0xFFFAFA ,
spring_green = 0x00FF7F , steel_blue = 0x4682B4 , tan = 0xD2B48C , teal = 0x008080 ,
thistle = 0xD8BFD8 , tomato = 0xFF6347 , turquoise = 0x40E0D0 , violet = 0xEE82EE ,
wheat = 0xF5DEB3 , white = 0xFFFFFF , white_smoke = 0xF5F5F5 , yellow = 0xFFFF00 ,
yellow_green = 0x9ACD32
}
enum class terminal_color : uint8_t {
black = 30 , red , green , yellow ,
blue , magenta , cyan , white ,
bright_black = 90 , bright_red , bright_green , bright_yellow ,
bright_blue , bright_magenta , bright_cyan , bright_white
}
enum class emphasis : uint8_t { bold = 1 , italic = 1 << 1 , underline = 1 << 2 , strikethrough = 1 << 3 }
Functions
FMT_CONSTEXPR text_style fg (detail::color_type foreground) FMT_NOEXCEPT
FMT_CONSTEXPR text_style bg (detail::color_type background) FMT_NOEXCEPT
FMT_CONSTEXPR text_style operator| (emphasis lhs, emphasis rhs) FMT_NOEXCEPT
template<typename Char >
FMT_CONSTEXPR ansi_color_escape< Char > make_foreground_color (detail::color_type foreground) FMT_NOEXCEPT
template<typename Char >
FMT_CONSTEXPR ansi_color_escape< Char > make_background_color (detail::color_type background) FMT_NOEXCEPT
template<typename Char >
FMT_CONSTEXPR ansi_color_escape< Char > make_emphasis (emphasis em) FMT_NOEXCEPT
template<typename Char >
void fputs (const Char *chars, FILE *stream) FMT_NOEXCEPT
template<>
void fputs< wchar_t > (const wchar_t *chars, FILE *stream) FMT_NOEXCEPT
template<typename Char >
void reset_color (FILE *stream) FMT_NOEXCEPT
template<>
void reset_color< wchar_t > (FILE *stream) FMT_NOEXCEPT
template<typename Char >
void reset_color (buffer< Char > &buffer) FMT_NOEXCEPT
template<typename Char >
void vformat_to (buffer< Char > &buf, const text_style &ts, basic_string_view< Char > format_str, basic_format_args< buffer_context< type_identity_t< Char >>> args)
template<typename S , typename Char = char_t<S>>
FMT_END_DETAIL_NAMESPACE void vprint (std::FILE *f, const text_style &ts, const S &format, basic_format_args< buffer_context< type_identity_t< Char >>> args)
template<typename S , typename... Args, FMT_ENABLE_IF(detail::is_string< S >::value) >
void print (std::FILE *f, const text_style &ts, const S &format_str, const Args &... args)
template<typename S , typename... Args, FMT_ENABLE_IF(detail::is_string< S >::value) >
void print (const text_style &ts, const S &format_str, const Args &... args)
template<typename S , typename Char = char_t<S>>
std::basic_string< Char > vformat (const text_style &ts, const S &format_str, basic_format_args< buffer_context< type_identity_t< Char >>> args)
template<typename S , typename... Args, typename Char = char_t<S>>
std::basic_string< Char > format (const text_style &ts, const S &format_str, const Args &... args)
template<typename OutputIt , typename Char , FMT_ENABLE_IF(detail::is_output_iterator< OutputIt, Char >::value) >
OutputIt vformat_to (OutputIt out, const text_style &ts, basic_string_view< Char > format_str, basic_format_args< buffer_context< type_identity_t< Char >>> args)
template<typename OutputIt , typename S , typename... Args, bool enable = detail::is_output_iterator<OutputIt, char_t<S>>::value&& detail::is_string<S>::value>
auto format_to (OutputIt out, const text_style &ts, const S &format_str, Args &&... args) -> typename std::enable_if< enable, OutputIt >::type
Macro Definition Documentation
FMT_DEPRECATED_NONMSVC
#define FMT_DEPRECATED_NONMSVC FMT_DEPRECATED
Definition at line 17 of file color.h.
Enumeration Type Documentation
color
enum color : uint32_t strong
Enumerator
alice_blue
antique_white
aqua
aquamarine
azure
beige
bisque
black
blanched_almond
blue
blue_violet
brown
burly_wood
cadet_blue
chartreuse
chocolate
coral
cornflower_blue
cornsilk
crimson
cyan
dark_blue
dark_cyan
dark_golden_rod
dark_gray
dark_green
dark_khaki
dark_magenta
dark_olive_green
dark_orange
dark_orchid
dark_red
dark_salmon
dark_sea_green
dark_slate_blue
dark_slate_gray
dark_turquoise
dark_violet
deep_pink
deep_sky_blue
dim_gray
dodger_blue
fire_brick
floral_white
forest_green
fuchsia
gainsboro
ghost_white
gold
golden_rod
gray
green
green_yellow
honey_dew
hot_pink
indian_red
indigo
ivory
khaki
lavender
lavender_blush
lawn_green
lemon_chiffon
light_blue
light_coral
light_cyan
light_golden_rod_yellow
light_gray
light_green
light_pink
light_salmon
light_sea_green
light_sky_blue
light_slate_gray
light_steel_blue
light_yellow
lime
lime_green
linen
magenta
maroon
medium_aquamarine
medium_blue
medium_orchid
medium_purple
medium_sea_green
medium_slate_blue
medium_spring_green
medium_turquoise
medium_violet_red
midnight_blue
mint_cream
misty_rose
moccasin
navajo_white
navy
old_lace
olive
olive_drab
orange
orange_red
orchid
pale_golden_rod
pale_green
pale_turquoise
pale_violet_red
papaya_whip
peach_puff
peru
pink
plum
powder_blue
purple
rebecca_purple
red
rosy_brown
royal_blue
saddle_brown
salmon
sandy_brown
sea_green
sea_shell
sienna
silver
sky_blue
slate_blue
slate_gray
snow
spring_green
steel_blue
tan
teal
thistle
tomato
turquoise
violet
wheat
white
white_smoke
yellow
yellow_green
Definition at line 23 of file color.h.
                  : uint32_t {
   alice_blue = 0xF0F8FF,               // rgb(240,248,255)
   antique_white = 0xFAEBD7,            // rgb(250,235,215)
   aqua = 0x00FFFF,                     // rgb(0,255,255)
   aquamarine = 0x7FFFD4,               // rgb(127,255,212)
   azure = 0xF0FFFF,                    // rgb(240,255,255)
   beige = 0xF5F5DC,                    // rgb(245,245,220)
   bisque = 0xFFE4C4,                   // rgb(255,228,196)
   black = 0x000000,                    // rgb(0,0,0)
   blanched_almond = 0xFFEBCD,          // rgb(255,235,205)
   blue = 0x0000FF,                     // rgb(0,0,255)
   blue_violet = 0x8A2BE2,              // rgb(138,43,226)
   brown = 0xA52A2A,                    // rgb(165,42,42)
   burly_wood = 0xDEB887,               // rgb(222,184,135)
   cadet_blue = 0x5F9EA0,               // rgb(95,158,160)
   chartreuse = 0x7FFF00,               // rgb(127,255,0)
   chocolate = 0xD2691E,                // rgb(210,105,30)
   coral = 0xFF7F50,                    // rgb(255,127,80)
   cornflower_blue = 0x6495ED,          // rgb(100,149,237)
   cornsilk = 0xFFF8DC,                 // rgb(255,248,220)
   crimson = 0xDC143C,                  // rgb(220,20,60)
   cyan = 0x00FFFF,                     // rgb(0,255,255)
   dark_blue = 0x00008B,                // rgb(0,0,139)
   dark_cyan = 0x008B8B,                // rgb(0,139,139)
   dark_golden_rod = 0xB8860B,          // rgb(184,134,11)
   dark_gray = 0xA9A9A9,                // rgb(169,169,169)
   dark_green = 0x006400,               // rgb(0,100,0)
   dark_khaki = 0xBDB76B,               // rgb(189,183,107)
   dark_magenta = 0x8B008B,             // rgb(139,0,139)
   dark_olive_green = 0x556B2F,         // rgb(85,107,47)
   dark_orange = 0xFF8C00,              // rgb(255,140,0)
   dark_orchid = 0x9932CC,              // rgb(153,50,204)
   dark_red = 0x8B0000,                 // rgb(139,0,0)
   dark_salmon = 0xE9967A,              // rgb(233,150,122)
   dark_sea_green = 0x8FBC8F,           // rgb(143,188,143)
   dark_slate_blue = 0x483D8B,          // rgb(72,61,139)
   dark_slate_gray = 0x2F4F4F,          // rgb(47,79,79)
   dark_turquoise = 0x00CED1,           // rgb(0,206,209)
   dark_violet = 0x9400D3,              // rgb(148,0,211)
   deep_pink = 0xFF1493,                // rgb(255,20,147)
   deep_sky_blue = 0x00BFFF,            // rgb(0,191,255)
   dim_gray = 0x696969,                 // rgb(105,105,105)
   dodger_blue = 0x1E90FF,              // rgb(30,144,255)
   fire_brick = 0xB22222,               // rgb(178,34,34)
   floral_white = 0xFFFAF0,             // rgb(255,250,240)
   forest_green = 0x228B22,             // rgb(34,139,34)
   fuchsia = 0xFF00FF,                  // rgb(255,0,255)
   gainsboro = 0xDCDCDC,                // rgb(220,220,220)
   ghost_white = 0xF8F8FF,              // rgb(248,248,255)
   gold = 0xFFD700,                     // rgb(255,215,0)
   golden_rod = 0xDAA520,               // rgb(218,165,32)
   gray = 0x808080,                     // rgb(128,128,128)
   green = 0x008000,                    // rgb(0,128,0)
   green_yellow = 0xADFF2F,             // rgb(173,255,47)
   honey_dew = 0xF0FFF0,                // rgb(240,255,240)
   hot_pink = 0xFF69B4,                 // rgb(255,105,180)
   indian_red = 0xCD5C5C,               // rgb(205,92,92)
   indigo = 0x4B0082,                   // rgb(75,0,130)
   ivory = 0xFFFFF0,                    // rgb(255,255,240)
   khaki = 0xF0E68C,                    // rgb(240,230,140)
   lavender = 0xE6E6FA,                 // rgb(230,230,250)
   lavender_blush = 0xFFF0F5,           // rgb(255,240,245)
   lawn_green = 0x7CFC00,               // rgb(124,252,0)
   lemon_chiffon = 0xFFFACD,            // rgb(255,250,205)
   light_blue = 0xADD8E6,               // rgb(173,216,230)
   light_coral = 0xF08080,              // rgb(240,128,128)
   light_cyan = 0xE0FFFF,               // rgb(224,255,255)
   light_golden_rod_yellow = 0xFAFAD2,  // rgb(250,250,210)
   light_gray = 0xD3D3D3,               // rgb(211,211,211)
   light_green = 0x90EE90,              // rgb(144,238,144)
   light_pink = 0xFFB6C1,               // rgb(255,182,193)
   light_salmon = 0xFFA07A,             // rgb(255,160,122)
   light_sea_green = 0x20B2AA,          // rgb(32,178,170)
   light_sky_blue = 0x87CEFA,           // rgb(135,206,250)
   light_slate_gray = 0x778899,         // rgb(119,136,153)
   light_steel_blue = 0xB0C4DE,         // rgb(176,196,222)
   light_yellow = 0xFFFFE0,             // rgb(255,255,224)
   lime = 0x00FF00,                     // rgb(0,255,0)
   lime_green = 0x32CD32,               // rgb(50,205,50)
   linen = 0xFAF0E6,                    // rgb(250,240,230)
   magenta = 0xFF00FF,                  // rgb(255,0,255)
   maroon = 0x800000,                   // rgb(128,0,0)
   medium_aquamarine = 0x66CDAA,        // rgb(102,205,170)
   medium_blue = 0x0000CD,              // rgb(0,0,205)
   medium_orchid = 0xBA55D3,            // rgb(186,85,211)
   medium_purple = 0x9370DB,            // rgb(147,112,219)
   medium_sea_green = 0x3CB371,         // rgb(60,179,113)
   medium_slate_blue = 0x7B68EE,        // rgb(123,104,238)
   medium_spring_green = 0x00FA9A,      // rgb(0,250,154)
   medium_turquoise = 0x48D1CC,         // rgb(72,209,204)
   medium_violet_red = 0xC71585,        // rgb(199,21,133)
   midnight_blue = 0x191970,            // rgb(25,25,112)
   mint_cream = 0xF5FFFA,               // rgb(245,255,250)
   misty_rose = 0xFFE4E1,               // rgb(255,228,225)
   moccasin = 0xFFE4B5,                 // rgb(255,228,181)
   navajo_white = 0xFFDEAD,             // rgb(255,222,173)
   navy = 0x000080,                     // rgb(0,0,128)
   old_lace = 0xFDF5E6,                 // rgb(253,245,230)
   olive = 0x808000,                    // rgb(128,128,0)
   olive_drab = 0x6B8E23,               // rgb(107,142,35)
   orange = 0xFFA500,                   // rgb(255,165,0)
   orange_red = 0xFF4500,               // rgb(255,69,0)
   orchid = 0xDA70D6,                   // rgb(218,112,214)
   pale_golden_rod = 0xEEE8AA,          // rgb(238,232,170)
   pale_green = 0x98FB98,               // rgb(152,251,152)
   pale_turquoise = 0xAFEEEE,           // rgb(175,238,238)
   pale_violet_red = 0xDB7093,          // rgb(219,112,147)
   papaya_whip = 0xFFEFD5,              // rgb(255,239,213)
   peach_puff = 0xFFDAB9,               // rgb(255,218,185)
   peru = 0xCD853F,                     // rgb(205,133,63)
   pink = 0xFFC0CB,                     // rgb(255,192,203)
   plum = 0xDDA0DD,                     // rgb(221,160,221)
   powder_blue = 0xB0E0E6,              // rgb(176,224,230)
   purple = 0x800080,                   // rgb(128,0,128)
   rebecca_purple = 0x663399,           // rgb(102,51,153)
   red = 0xFF0000,                      // rgb(255,0,0)
   rosy_brown = 0xBC8F8F,               // rgb(188,143,143)
   royal_blue = 0x4169E1,               // rgb(65,105,225)
   saddle_brown = 0x8B4513,             // rgb(139,69,19)
   salmon = 0xFA8072,                   // rgb(250,128,114)
   sandy_brown = 0xF4A460,              // rgb(244,164,96)
   sea_green = 0x2E8B57,                // rgb(46,139,87)
   sea_shell = 0xFFF5EE,                // rgb(255,245,238)
   sienna = 0xA0522D,                   // rgb(160,82,45)
   silver = 0xC0C0C0,                   // rgb(192,192,192)
   sky_blue = 0x87CEEB,                 // rgb(135,206,235)
   slate_blue = 0x6A5ACD,               // rgb(106,90,205)
   slate_gray = 0x708090,               // rgb(112,128,144)
   snow = 0xFFFAFA,                     // rgb(255,250,250)
   spring_green = 0x00FF7F,             // rgb(0,255,127)
   steel_blue = 0x4682B4,               // rgb(70,130,180)
   tan = 0xD2B48C,                      // rgb(210,180,140)
   teal = 0x008080,                     // rgb(0,128,128)
   thistle = 0xD8BFD8,                  // rgb(216,191,216)
   tomato = 0xFF6347,                   // rgb(255,99,71)
   turquoise = 0x40E0D0,                // rgb(64,224,208)
   violet = 0xEE82EE,                   // rgb(238,130,238)
   wheat = 0xF5DEB3,                    // rgb(245,222,179)
   white = 0xFFFFFF,                    // rgb(255,255,255)
   white_smoke = 0xF5F5F5,              // rgb(245,245,245)
   yellow = 0xFFFF00,                   // rgb(255,255,0)
   yellow_green = 0x9ACD32              // rgb(154,205,50)
 };                                     // enum class color
emphasis
enum emphasis : uint8_t strong
Enumerator
bold
italic
underline
strikethrough
Definition at line 186 of file color.h.
                     : uint8_t {
   bold = 1,
   italic = 1 << 1,
   underline = 1 << 2,
   strikethrough = 1 << 3
 };
terminal_color
enum terminal_color : uint8_t strong
Enumerator
black
red
green
yellow
blue
magenta
cyan
white
bright_black
bright_red
bright_green
bright_yellow
bright_blue
bright_magenta
bright_cyan
bright_white
Definition at line 167 of file color.h.
                           : uint8_t {
   black = 30,
   red,
   green,
   yellow,
   blue,
   magenta,
   cyan,
   white,
   bright_black = 90,
   bright_red,
   bright_green,
   bright_yellow,
   bright_blue,
   bright_magenta,
   bright_cyan,
   bright_white
 };
Function Documentation
bg()
FMT_CONSTEXPR text_style bg (detail::color_type background) inline
Creates a text style from the background color.
Definition at line 363 of file color.h.
{
   return text_style(false, background);
 }
Referenced by Unit::_EnterVehicle(), GameObject::ActivateToQuest(), BattlegroundMgr::AddBattleground(), BattlegroundQueue::AddGroup(), BattlegroundQueue::BattlegroundQueueUpdate(), BattlegroundMgr::BuildBattlegroundStatusPacket(), BattlegroundMgr::BuildPvpLogDataPacket(), BGSpamProtect::CanAnnounce(), Player::CanEquipItem(), ScriptMgr::CanFillPlayersToBG(), ScriptMgr::CanFillPlayersToBGWithSpecific(), WorldObject::CanSeeOrDetect(), ScriptMgr::CanSendMessageBGQueue(), Player::CanUnequipItem(), Spell::CheckCast(), BattlegroundMgr::CreateBattleground(), MapInstanced::CreateBattleground(), MapInstanced::CreateInstanceForPlayer(), BattlegroundMgr::CreateNewBattleground(), Unit::DealDamage(), Unit::DealHeal(), Object::DestroyForPlayer(), Spell::EffectOpenLock(), Spell::EffectScriptEffect(), Spell::EffectSummonObjectWild(), BGQueueInviteEvent::Execute(), BGQueueRemoveEvent::Execute(), BattlegroundQueue::FillPlayersToBG(), BattlegroundQueue::FillPlayersToBGWithSpecific(), Player::GetBattleground(), MapMgr::GetNumPlayersInInstances(), BattlegroundMgr::GetRandomBG(), WorldSession::HandleAreaSpiritHealerQueryOpcode(), WorldSession::HandleAreaSpiritHealerQueueOpcode(), WorldSession::HandleAreaTriggerOpcode(), Pet::HandleAsynchLoadSucceed(), AuraEffect::HandleAuraDummy(), AuraEffect::HandleAuraModEffectImmunity(), WorldSession::HandleBattlefieldLeaveOpcode(), WorldSession::HandleBattleFieldPortOpcode(), WorldSession::HandleBattlefieldStatusOpcode(), WorldSession::HandleBattlegroundPlayerPositionsOpcode(), spell_item_rocket_boots::HandleDummy(), WorldSession::HandleGossipHelloOpcode(), WorldSession::HandleMoveWorldportAck(), WorldSession::HandlePVPLogDataOpcode(), WorldSession::HandleQuestgiverCompleteQuest(), ArenaSpectator::HandleResetCommand(), spell_ioc_gunship_portal::spell_ioc_gunship_portal_SpellScript::HandleScript2(), misc_commandscript::HandleSkirmishCommand(), ArenaSpectator::HandleSpectatorWatchCommand(), Player::InArena(), BattlegroundMgr::InviteGroupToBG(), SpellArea::IsFitToRequirements(), Unit::isInAccessiblePlaceFor(), Unit::Kill(), Player::LeaveBattleground(), AchievementCriteriaData::Meets(), Unit::Mount(), Player::NeedSendSpectatorData(), ScriptMgr::OnAfterArenaRatingCalculation(), ScriptMgr::OnBattlegroundAddPlayer(), ScriptMgr::OnBattlegroundBeforeAddPlayer(), ScriptMgr::OnBattlegroundEndReward(), ScriptMgr::OnBattlegroundRemovePlayerAtLeave(), ScriptMgr::OnBattlegroundStart(), ScriptMgr::OnBattlegroundUpdate(), achievement_resilient_victory::OnCheck(), achievement_bg_control_all_nodes::OnCheck(), achievement_bg_ic_resource_glut::OnCheck(), achievement_everything_counts::OnCheck(), achievement_bg_av_perfection::OnCheck(), achievement_sa_defense_of_the_ancients::OnCheck(), achievement_save_the_day::OnCheck(), go_arena_ready_marker::OnGossipHello(), ScriptMgr::OnPlayerAddToBattleground(), ScriptMgr::OnPlayerRemoveFromBattleground(), BattlegroundQueue::RemovePlayer(), BattlegroundMap::RemovePlayerFromMap(), Player::RepopAtGraveyard(), Player::ReportedAfkBy(), Player::ResurrectPlayer(), Player::RewardHonor(), BattlegroundMgr::SendAreaSpiritHealerQueryOpcode(), Player::SendInitWorldStates(), BattlegroundQueue::SendJoinMessageArenaQueue(), Player::SendLoot(), BattlegroundQueue::SendMessageBGQueue(), BattlegroundMgr::SendToBattleground(), Group::SetBattlefieldGroup(), Group::SetBattlegroundGroup(), Player::SetBattlegroundId(), BattlegroundMap::SetBG(), GameObject::SetDestructibleState(), Player::SummonIfPossible(), spell_gen_bg_preparation::Update(), BattlegroundMgr::Update(), GameObject::Update(), AchievementMgr::UpdateAchievementCriteria(), and GameObject::Use().
fg()
FMT_CONSTEXPR text_style fg (detail::color_type foreground) inline
Creates a text style from the foreground (text) color.
Definition at line 358 of file color.h.
{
   return text_style(true, foreground);
 }
Referenced by instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::SetData().
format()
template<typename S , typename... Args, typename Char = char_t<S>> std::basic_string<Char> format (const text_style & ts, const S & format_str, const Args &... args) inline
\rst Formats arguments and returns the result as a string using ANSI escape sequences to specify text formatting.
Example**::
include <fmt/color.h> std::string message = fmt::format(fmt::emphasis::bold | fg(fmt::color::red), "The answer is {}", 42); \endrst
Definition at line 583 of file color.h.
{
   return fmt::vformat(ts, to_string_view(format_str),
                       fmt::make_args_checked<Args...>(format_str, args...));
 }
References to_string_view(), and vformat().
Referenced by _db_doprnt_(), Acore::Assert(), DBCFileLoader::AutoProduceData(), DBCFileLoader::AutoProduceStrings(), DbugVfprintf(), default_reporter(), detail::do_write(), InstanceScript::DoSendNotifyToInstance(), emitter_printf(), emitter_table_printf(), detail::fallback_formatter< T, Char, enable_if_t< is_streamable< T, Char >::value > >::format(), formatter< tuple_join_view< Char, T... >, Char >::format(), formatter< std::chrono::time_point< std::chrono::system_clock, Duration >, Char >::format(), detail::format_float(), chrono_formatter< FormatContext, OutputIt, Rep, Period >::format_localized(), anonymous_namespace{Errors.cpp}::FormatAssertionMessage(), DBCFileLoader::GetFormatRecordSize(), gzprintf(), WheatyExceptionReport::HeapLog(), inline_mysql_file_fprintf(), inline_mysql_file_vfprintf(), DBCStorage< T >::LoadFromDB(), DBCStorageBase::LoadFromDB(), rcContext::log(), WheatyExceptionReport::Log(), log_impl_varargs(), malloc_cprintf(), malloc_printf(), malloc_snprintf(), malloc_vcprintf(), malloc_vsnprintf(), my_error(), my_printf_error(), my_printv_error(), Log::outMessageFmt(), prof_dump_printf(), prof_open_maps(), safety_check_fail(), WorldSession::SendNotification(), Battleground::SendWarningToAll(), set_mysql_extended_error(), detail::snprintf_float(), WheatyExceptionReport::StackLog(), strftime(), Acore::StringFormatFmt(), mpq::File::this(), G3D::Sphere::toString(), PreparedStatementData::ToString(), vprint(), vprintf(), and detail::write().
format_to()
template<typename OutputIt , typename S , typename... Args, bool enable = detail::is_output_iterator<OutputIt, char_t<S>>::value&& detail::is_string<S>::value> auto format_to (OutputIt out, const text_style & ts, const S & format_str, Args &&... args) -> typename std::enable_if<enable, OutputIt>::type inline
\rst Formats arguments with the given text_style, writes the result to the output iterator out and returns the iterator past the end of the output range.
Example**::
std::vector<char> out; fmt::format_to(std::back_inserter(out), fmt::emphasis::bold | fg(fmt::color::red), "{}", 42); \endrst
Definition at line 617 of file color.h.
{
   return vformat_to(out, ts, to_string_view(format_str),
                     fmt::make_args_checked<Args...>(format_str, args...));
 }
References to_string_view(), and vformat_to().
Referenced by formatter< detail::bigint >::format(), and detail::format_error_code().
fputs()
template<typename Char > void fputs (const Char * chars, FILE * stream) inline
Definition at line 467 of file color.h.
{
   std::fputs(chars, stream);
 }
Referenced by get_password(), get_tty_password(), inline_mysql_file_fputs(), main(), my_message_stderr(), my_print_default_files(), print_defaults(), reset_color(), reset_color< wchar_t >(), and vprint().
fputs< wchar_t >()
template<> void fputs< wchar_t > (const wchar_t * chars, FILE * stream) inline
Definition at line 472 of file color.h.
{
   std::fputws(chars, stream);
 }
make_background_color()
template<typename Char > FMT_CONSTEXPR ansi_color_escape<Char> make_background_color (detail::color_type background)
Definition at line 456 of file color.h.
{
   return ansi_color_escape<Char>(background, "\x1b[48;2;");
 }
make_emphasis()
template<typename Char > FMT_CONSTEXPR ansi_color_escape<Char> make_emphasis (emphasis em)
Definition at line 462 of file color.h.
{
   return ansi_color_escape<Char>(em);
 }
make_foreground_color()
template<typename Char > FMT_CONSTEXPR ansi_color_escape<Char> make_foreground_color (detail::color_type foreground)
Definition at line 450 of file color.h.
{
   return ansi_color_escape<Char>(foreground, "\x1b[38;2;");
 }
operator|()
FMT_CONSTEXPR text_style operator| (emphasis lhs, emphasis rhs) inline
Definition at line 367 of file color.h.
{
   return text_style(lhs) | rhs;
 }
print() [1/2]
template<typename S , typename... Args, FMT_ENABLE_IF(detail::is_string< S >::value) > void print (const text_style & ts, const S & format_str, const Args &... args)
\rst Formats a string and prints it to stdout using ANSI escape sequences to specify text formatting.
Example**::
fmt::print(fmt::emphasis::bold | fg(fmt::color::red), "Elapsed time: {0:.2f} seconds", 1.23); \endrst
Definition at line 557 of file color.h.
{
   return print(stdout, ts, format_str, args...);
 }
References print().
print() [2/2]
template<typename S , typename... Args, FMT_ENABLE_IF(detail::is_string< S >::value) > void print (std::FILE * f, const text_style & ts, const S & format_str, const Args &... args)
\rst Formats a string and prints it to the specified file stream using ANSI escape sequences to specify text formatting.
Example**::
fmt::print(fmt::emphasis::bold | fg(fmt::color::red), "Elapsed time: {0:.2f} seconds", 1.23); \endrst
Definition at line 538 of file color.h.
{
   vprint(f, ts, format_str,
          fmt::make_args_checked<Args...>(format_str, args...));
 }
References f(), and vprint().
Referenced by print(), and enumutils_describe::processFile().
reset_color() [1/2]
template<typename Char > void reset_color (buffer< Char > & buffer) inline
Definition at line 485 of file color.h.
{
   auto reset_color = string_view("\x1b[0m");
   buffer.append(reset_color.begin(), reset_color.end());
 }
References buffer< T >::append(), and reset_color().
reset_color() [2/2]
template<typename Char > void reset_color (FILE * stream) inline
Definition at line 476 of file color.h.
{
   fputs("\x1b[0m", stream);
 }
References fputs().
Referenced by reset_color().
reset_color< wchar_t >()
template<> void reset_color< wchar_t > (FILE * stream) inline
Definition at line 480 of file color.h.
{
   fputs(L"\x1b[0m", stream);
 }
References fputs().
vformat()
template<typename S , typename Char = char_t<S>> std::basic_string<Char> vformat (const text_style & ts, const S & format_str, basic_format_args< buffer_context< type_identity_t< Char >>> args) inline
Definition at line 562 of file color.h.
{
   basic_memory_buffer<Char> buf;
   detail::vformat_to(buf, ts, to_string_view(format_str), args);
   return fmt::to_string(buf);
 }
References to_string(), to_string_view(), and vformat_to().
Referenced by format().
vformat_to() [1/2]
template<typename Char > void vformat_to (buffer< Char > & buf, const text_style & ts, basic_string_view< Char > format_str, basic_format_args< buffer_context< type_identity_t< Char >>> args)
Definition at line 491 of file color.h.
{
   bool has_style = false;
   if (ts.has_emphasis()) {
     has_style = true;
     auto emphasis = detail::make_emphasis<Char>(ts.get_emphasis());
     buf.append(emphasis.begin(), emphasis.end());
   }
   if (ts.has_foreground()) {
     has_style = true;
     auto foreground = detail::make_foreground_color<Char>(ts.get_foreground());
     buf.append(foreground.begin(), foreground.end());
   }
   if (ts.has_background()) {
     has_style = true;
     auto background = detail::make_background_color<Char>(ts.get_background());
     buf.append(background.begin(), background.end());
   }
   detail::vformat_to(buf, format_str, args, {});
   if (has_style) detail::reset_color<Char>(buf);
 }
References buffer< T >::append(), text_style::get_background(), text_style::get_emphasis(), text_style::get_foreground(), text_style::has_background(), text_style::has_emphasis(), and text_style::has_foreground().
Referenced by format_to(), vformat(), vformat_to(), and vprint().
vformat_to() [2/2]
template<typename OutputIt , typename Char , FMT_ENABLE_IF(detail::is_output_iterator< OutputIt, Char >::value) > OutputIt vformat_to (OutputIt out, const text_style & ts, basic_string_view< Char > format_str, basic_format_args< buffer_context< type_identity_t< Char >>> args)
Formats a string with the given text_style and writes the output to out.
Definition at line 594 of file color.h.
{
   auto&& buf = detail::get_buffer<Char>(out);
   detail::vformat_to(buf, ts, format_str, args);
   return detail::get_iterator(buf);
 }
References get_iterator(), and vformat_to().
vprint()
template<typename S , typename Char = char_t<S>> FMT_END_DETAIL_NAMESPACE void vprint (std::FILE * f, const text_style & ts, const S & format, basic_format_args< buffer_context< type_identity_t< Char >>> args)
Definition at line 517 of file color.h.
{
   basic_memory_buffer<Char> buf;
   detail::vformat_to(buf, ts, to_string_view(format), args);
   buf.push_back(Char(0));
   detail::fputs(buf.data(), f);
 }
References f(), format(), fputs(), to_string_view(), and vformat_to().
Referenced by print(), and buffered_file::vprint().