Azerotcore-wotlk: npc_wg_quest_giver Class Reference
npc_wg_quest_giver Class Reference
Public Member Functions
npc_wg_quest_giver ()
bool OnGossipHello (Player *player, Creature *creature) override
uint32 GetDialogStatus (Player *player, Creature *creature) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelect (Player *, Creature *, uint32, uint32)
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual CreatureAI * GetAI (Creature *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 391 of file zone_wintergrasp.cpp.
Constructor & Destructor Documentation
npc_wg_quest_giver()
npc_wg_quest_giver::npc_wg_quest_giver () inline
Definition at line 394 of file zone_wintergrasp.cpp.
 : CreatureScript("npc_wg_quest_giver") { }
Member Function Documentation
GetDialogStatus()
uint32 npc_wg_quest_giver::GetDialogStatus (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 573 of file zone_wintergrasp.cpp.
     {
         QuestRelationBounds qr = sObjectMgr->GetCreatureQuestRelationBounds(creature->GetEntry());
         QuestRelationBounds qir = sObjectMgr->GetCreatureQuestInvolvedRelationBounds(creature->GetEntry());
         QuestGiverStatus result = DIALOG_STATUS_NONE;
         for (QuestRelations::const_iterator i = qir.first; i != qir.second; ++i)
         {
             QuestGiverStatus result2 = DIALOG_STATUS_NONE;
             uint32 questId = i->second;
             Quest const* quest = sObjectMgr->GetQuestTemplate(questId);
             if (!quest)
                 continue;
             ConditionList conditions = sConditionMgr->GetConditionsForNotGroupedEntry(CONDITION_SOURCE_TYPE_QUEST_AVAILABLE, quest->GetQuestId());
             if (!sConditionMgr->IsObjectMeetToConditions(player, conditions))
                 continue;
             QuestStatus status = player->GetQuestStatus(questId);
             if ((status == QUEST_STATUS_COMPLETE && !player->GetQuestRewardStatus(questId)) ||
                     (quest->IsAutoComplete() && player->CanTakeQuest(quest, false)))
             {
                 if (quest->IsAutoComplete() && quest->IsRepeatable() && !quest->IsDailyOrWeekly())
                     result2 = DIALOG_STATUS_REWARD_REP;
                 else
                     result2 = DIALOG_STATUS_REWARD;
             }
             else if (status == QUEST_STATUS_INCOMPLETE)
                 result2 = DIALOG_STATUS_INCOMPLETE;
             if (result2 > result)
                 result = result2;
         }
         for (QuestRelations::const_iterator i = qr.first; i != qr.second; ++i)
         {
             QuestGiverStatus result2 = DIALOG_STATUS_NONE;
             uint32 questId = i->second;
             Quest const* quest = sObjectMgr->GetQuestTemplate(questId);
             if (!quest)
                 continue;
             ConditionList conditions = sConditionMgr->GetConditionsForNotGroupedEntry(CONDITION_SOURCE_TYPE_QUEST_AVAILABLE, quest->GetQuestId());
             if (!sConditionMgr->IsObjectMeetToConditions(player, conditions))
                 continue;
             switch (questId)
             {
                 case QUEST_BONES_AND_ARROWS_ALLIANCE_ATT:
                     if (!sPoolMgr->IsSpawnedObject<Quest>(QUEST_BONES_AND_ARROWS_ALLIANCE_DEF))
                         continue;
                     break;
                 case QUEST_WARDING_THE_WARRIORS_ALLIANCE_ATT:
                     if (!sPoolMgr->IsSpawnedObject<Quest>(QUEST_WARDING_THE_WARRIORS_ALLIANCE_DEF))
                         continue;
                     break;
                 case QUEST_A_RARE_HERB_ALLIANCE_ATT:
                     if (!sPoolMgr->IsSpawnedObject<Quest>(QUEST_A_RARE_HERB_ALLIANCE_DEF))
                         continue;
                     break;
                 case QUEST_FUELING_THE_DEMOLISHERS_ALLIANCE_ATT:
                     if (!sPoolMgr->IsSpawnedObject<Quest>(QUEST_FUELING_THE_DEMOLISHERS_ALLIANCE_DEF))
                         continue;
                     break;
                 case QUEST_BONES_AND_ARROWS_HORDE_ATT:
                     if (!sPoolMgr->IsSpawnedObject<Quest>(QUEST_BONES_AND_ARROWS_HORDE_DEF))
                         continue;
                     break;
                 case QUEST_JINXING_THE_WALLS_HORDE_ATT:
                     if (!sPoolMgr->IsSpawnedObject<Quest>(QUEST_WARDING_THE_WALLS_HORDE_DEF))
                         continue;
                     break;
                 case QUEST_FUELING_THE_DEMOLISHERS_HORDE_ATT:
                     if (!sPoolMgr->IsSpawnedObject<Quest>(QUEST_FUELING_THE_DEMOLISHERS_HORDE_DEF))
                         continue;
                     break;
                 case QUEST_HEALING_WITH_ROSES_HORDE_ATT:
                     if (!sPoolMgr->IsSpawnedObject<Quest>(QUEST_HEALING_WITH_ROSES_HORDE_DEF))
                         continue;
                     break;
             }
             QuestStatus status = player->GetQuestStatus(questId);
             if (status == QUEST_STATUS_NONE)
             {
                 if (player->CanSeeStartQuest(quest))
                 {
                     if (player->SatisfyQuestLevel(quest, false))
                     {
                         if (quest->IsAutoComplete())
                             result2 = DIALOG_STATUS_REWARD_REP;
                         else if (player->getLevel() <= (player->GetQuestLevel(quest) + sWorld->getIntConfig(CONFIG_QUEST_LOW_LEVEL_HIDE_DIFF)))
{
                             if (quest->IsDaily())
                                 result2 = DIALOG_STATUS_AVAILABLE_REP;
                             else
                                 result2 = DIALOG_STATUS_AVAILABLE;
                         }
                         else
                             result2 = DIALOG_STATUS_LOW_LEVEL_AVAILABLE;
                     }
                     else
                         result2 = DIALOG_STATUS_UNAVAILABLE;
                 }
             }
             if (result2 > result)
                 result = result2;
         }
         return result;
     }
References Player::CanSeeStartQuest(), Player::CanTakeQuest(), CONDITION_SOURCE_TYPE_QUEST_AVAILABLE, CONFIG_QUEST_LOW_LEVEL_HIDE_DIFF, DIALOG_STATUS_AVAILABLE, DIALOG_STATUS_AVAILABLE_REP, DIALOG_STATUS_INCOMPLETE, DIALOG_STATUS_LOW_LEVEL_AVAILABLE, DIALOG_STATUS_NONE, DIALOG_STATUS_REWARD, DIALOG_STATUS_REWARD_REP, DIALOG_STATUS_UNAVAILABLE, Object::GetEntry(), Unit::getLevel(), Quest::GetQuestId(), Player::GetQuestLevel(), Player::GetQuestRewardStatus(), Player::GetQuestStatus(), Quest::IsAutoComplete(), Quest::IsDaily(), Quest::IsDailyOrWeekly(), Quest::IsRepeatable(), QUEST_A_RARE_HERB_ALLIANCE_ATT, QUEST_A_RARE_HERB_ALLIANCE_DEF, QUEST_BONES_AND_ARROWS_ALLIANCE_ATT, QUEST_BONES_AND_ARROWS_ALLIANCE_DEF, QUEST_BONES_AND_ARROWS_HORDE_ATT, QUEST_BONES_AND_ARROWS_HORDE_DEF, QUEST_FUELING_THE_DEMOLISHERS_ALLIANCE_ATT, QUEST_FUELING_THE_DEMOLISHERS_ALLIANCE_DEF, QUEST_FUELING_THE_DEMOLISHERS_HORDE_ATT, QUEST_FUELING_THE_DEMOLISHERS_HORDE_DEF, QUEST_HEALING_WITH_ROSES_HORDE_ATT, QUEST_HEALING_WITH_ROSES_HORDE_DEF, QUEST_JINXING_THE_WALLS_HORDE_ATT, QUEST_STATUS_COMPLETE, QUEST_STATUS_INCOMPLETE, QUEST_STATUS_NONE, QUEST_WARDING_THE_WALLS_HORDE_DEF, QUEST_WARDING_THE_WARRIORS_ALLIANCE_ATT, QUEST_WARDING_THE_WARRIORS_ALLIANCE_DEF, Player::SatisfyQuestLevel(), sConditionMgr, sObjectMgr, sPoolMgr, and sWorld.
OnGossipHello()
bool npc_wg_quest_giver::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 396 of file zone_wintergrasp.cpp.
     {
         if (creature->IsQuestGiver())
             player->PrepareQuestMenu(creature->GetGUID());
         Battlefield* wintergrasp = sBattlefieldMgr->GetBattlefieldByBattleId(BATTLEFIELD_BATTLEID_WG);
         if (!wintergrasp)
             return true;
         if (creature->IsQuestGiver())
         {
             QuestRelationBounds objectQR = sObjectMgr->GetCreatureQuestRelationBounds(creature->GetEntry());
             QuestRelationBounds objectQIR = sObjectMgr->GetCreatureQuestInvolvedRelationBounds(creature->GetEntry());
             QuestMenu& qm = player->PlayerTalkClass->GetQuestMenu();
             qm.ClearMenu();
             for (QuestRelations::const_iterator i = objectQIR.first; i != objectQIR.second; ++i)
             {
                 uint32 quest_id = i->second;
                 QuestStatus status = player->GetQuestStatus(quest_id);
                 if (status == QUEST_STATUS_COMPLETE)
                     qm.AddMenuItem(quest_id, 4);
                 else if (status == QUEST_STATUS_INCOMPLETE)
                     qm.AddMenuItem(quest_id, 4);
                 //else if (status == QUEST_STATUS_AVAILABLE)
                 //    qm.AddMenuItem(quest_id, 2);
             }
             // xinef: add att/def doubles if this quest is spawned
             std::vector<uint32> questRelationVector;
             for (QuestRelations::const_iterator i = objectQR.first; i != objectQR.second; ++i)
             {
                 uint32 questId = i->second;
                 Quest const* quest = sObjectMgr->GetQuestTemplate(questId);
                 if (!quest)
                     continue;
                 switch (questId)
                 {
                     case QUEST_BONES_AND_ARROWS_ALLIANCE_ATT:
                         if (!sPoolMgr->IsSpawnedObject<Quest>(QUEST_BONES_AND_ARROWS_ALLIANCE_DEF))
                             continue;
                         questRelationVector.push_back(QUEST_BONES_AND_ARROWS_ALLIANCE_ATT);
                         break;
                     case QUEST_WARDING_THE_WARRIORS_ALLIANCE_ATT:
                         if (!sPoolMgr->IsSpawnedObject<Quest>(QUEST_WARDING_THE_WARRIORS_ALLIANCE_DEF))
                             continue;
                         questRelationVector.push_back(QUEST_WARDING_THE_WARRIORS_ALLIANCE_ATT);
                         break;
                     case QUEST_A_RARE_HERB_ALLIANCE_ATT:
                         if (!sPoolMgr->IsSpawnedObject<Quest>(QUEST_A_RARE_HERB_ALLIANCE_DEF))
                             continue;
                         questRelationVector.push_back(QUEST_A_RARE_HERB_ALLIANCE_ATT);
                         break;
                     case QUEST_FUELING_THE_DEMOLISHERS_ALLIANCE_ATT:
                         if (!sPoolMgr->IsSpawnedObject<Quest>(QUEST_FUELING_THE_DEMOLISHERS_ALLIANCE_DEF))
                             continue;
                         questRelationVector.push_back(QUEST_FUELING_THE_DEMOLISHERS_ALLIANCE_ATT);
                         break;
                     case QUEST_BONES_AND_ARROWS_HORDE_ATT:
                         if (!sPoolMgr->IsSpawnedObject<Quest>(QUEST_BONES_AND_ARROWS_HORDE_DEF))
                             continue;
                         questRelationVector.push_back(QUEST_BONES_AND_ARROWS_HORDE_ATT);
                         break;
                     case QUEST_JINXING_THE_WALLS_HORDE_ATT:
                         if (!sPoolMgr->IsSpawnedObject<Quest>(QUEST_WARDING_THE_WALLS_HORDE_DEF))
                             continue;
                         questRelationVector.push_back(QUEST_JINXING_THE_WALLS_HORDE_ATT);
                         break;
                     case QUEST_FUELING_THE_DEMOLISHERS_HORDE_ATT:
                         if (!sPoolMgr->IsSpawnedObject<Quest>(QUEST_FUELING_THE_DEMOLISHERS_HORDE_DEF))
                             continue;
                         questRelationVector.push_back(QUEST_FUELING_THE_DEMOLISHERS_HORDE_ATT);
                         break;
                     case QUEST_HEALING_WITH_ROSES_HORDE_ATT:
                         if (!sPoolMgr->IsSpawnedObject<Quest>(QUEST_HEALING_WITH_ROSES_HORDE_DEF))
                             continue;
                         questRelationVector.push_back(QUEST_HEALING_WITH_ROSES_HORDE_ATT);
                         break;
                     default:
                         questRelationVector.push_back(questId);
                         break;
                 }
             }
             for (std::vector<uint32>::const_iterator i = questRelationVector.begin(); i != questRelationVector.end(); ++i)
             {
                 uint32 questId = *i;
                 Quest const* quest = sObjectMgr->GetQuestTemplate(questId);
                 switch (questId)
                 {
                     // Horde attacker
                     case QUEST_BONES_AND_ARROWS_HORDE_ATT:
                     case QUEST_JINXING_THE_WALLS_HORDE_ATT:
                     case QUEST_SLAY_THEM_ALL_HORDE_ATT:
                     case QUEST_FUELING_THE_DEMOLISHERS_HORDE_ATT:
                     case QUEST_HEALING_WITH_ROSES_HORDE_ATT:
                     case QUEST_DEFEND_THE_SIEGE_HORDE_ATT:
                         if (wintergrasp->GetAttackerTeam() == TEAM_HORDE)
{
                             QuestStatus status = player->GetQuestStatus(questId);
                             if (quest->IsAutoComplete() && player->CanTakeQuest(quest, false))
                                 qm.AddMenuItem(questId, 4);
                             else if (status == QUEST_STATUS_NONE && player->CanTakeQuest(quest, false))
                                 qm.AddMenuItem(questId, 2);
                         }
                         break;
                     // Horde defender
                     case QUEST_BONES_AND_ARROWS_HORDE_DEF:
                     case QUEST_WARDING_THE_WALLS_HORDE_DEF:
                     case QUEST_SLAY_THEM_ALL_HORDE_DEF:
                     case QUEST_FUELING_THE_DEMOLISHERS_HORDE_DEF:
                     case QUEST_HEALING_WITH_ROSES_HORDE_DEF:
                     case QUEST_TOPPLING_THE_TOWERS_HORDE_DEF:
                     case QUEST_STOP_THE_SIEGE_HORDE_DEF:
                         if (wintergrasp->GetDefenderTeam() == TEAM_HORDE)
{
                             QuestStatus status = player->GetQuestStatus(questId);
                             if (quest->IsAutoComplete() && player->CanTakeQuest(quest, false))
                                 qm.AddMenuItem(questId, 4);
                             else if (status == QUEST_STATUS_NONE && player->CanTakeQuest(quest, false))
                                 qm.AddMenuItem(questId, 2);
                         }
                         break;
                     // Alliance attacker
                     case QUEST_BONES_AND_ARROWS_ALLIANCE_ATT:
                     case QUEST_WARDING_THE_WARRIORS_ALLIANCE_ATT:
                     case QUEST_NO_MERCY_FOR_THE_MERCILESS_ALLIANCE_ATT:
                     case QUEST_DEFEND_THE_SIEGE_ALLIANCE_ATT:
                     case QUEST_A_RARE_HERB_ALLIANCE_ATT:
                     case QUEST_FUELING_THE_DEMOLISHERS_ALLIANCE_ATT:
                         if (wintergrasp->GetAttackerTeam() == TEAM_ALLIANCE)
{
                             QuestStatus status = player->GetQuestStatus(questId);
                             if (quest->IsAutoComplete() && player->CanTakeQuest(quest, false))
                                 qm.AddMenuItem(questId, 4);
                             else if (status == QUEST_STATUS_NONE && player->CanTakeQuest(quest, false))
                                 qm.AddMenuItem(questId, 2);
                         }
                         break;
                     // Alliance defender
                     case QUEST_BONES_AND_ARROWS_ALLIANCE_DEF:
                     case QUEST_WARDING_THE_WARRIORS_ALLIANCE_DEF:
                     case QUEST_NO_MERCY_FOR_THE_MERCILESS_ALLIANCE_DEF:
                     case QUEST_SHOUTHERN_SABOTAGE_ALLIANCE_DEF:
                     case QUEST_STOP_THE_SIEGE_ALLIANCE_DEF:
                     case QUEST_A_RARE_HERB_ALLIANCE_DEF:
                     case QUEST_FUELING_THE_DEMOLISHERS_ALLIANCE_DEF:
                         if (wintergrasp->GetDefenderTeam() == TEAM_ALLIANCE)
{
                             QuestStatus status = player->GetQuestStatus(questId);
                             if (quest->IsAutoComplete() && player->CanTakeQuest(quest, false))
                                 qm.AddMenuItem(questId, 4);
                             else if (status == QUEST_STATUS_NONE && player->CanTakeQuest(quest, false))
                                 qm.AddMenuItem(questId, 2);
                         }
                         break;
                     default:
                         QuestStatus status = player->GetQuestStatus(questId);
                         if (quest->IsAutoComplete() && player->CanTakeQuest(quest, false))
                             qm.AddMenuItem(questId, 4);
                         else if (status == QUEST_STATUS_NONE && player->CanTakeQuest(quest, false))
                             qm.AddMenuItem(questId, 2);
                         break;
                 }
             }
         }
         SendGossipMenuFor(player, player->GetGossipTextId(creature), creature->GetGUID());
         return true;
     }
References QuestMenu::AddMenuItem(), BATTLEFIELD_BATTLEID_WG, Player::CanTakeQuest(), QuestMenu::ClearMenu(), Battlefield::GetAttackerTeam(), Battlefield::GetDefenderTeam(), Object::GetEntry(), Player::GetGossipTextId(), Object::GetGUID(), PlayerMenu::GetQuestMenu(), Player::GetQuestStatus(), Quest::IsAutoComplete(), Unit::IsQuestGiver(), Player::PlayerTalkClass, Player::PrepareQuestMenu(), QUEST_A_RARE_HERB_ALLIANCE_ATT, QUEST_A_RARE_HERB_ALLIANCE_DEF, QUEST_BONES_AND_ARROWS_ALLIANCE_ATT, QUEST_BONES_AND_ARROWS_ALLIANCE_DEF, QUEST_BONES_AND_ARROWS_HORDE_ATT, QUEST_BONES_AND_ARROWS_HORDE_DEF, QUEST_DEFEND_THE_SIEGE_ALLIANCE_ATT, QUEST_DEFEND_THE_SIEGE_HORDE_ATT, QUEST_FUELING_THE_DEMOLISHERS_ALLIANCE_ATT, QUEST_FUELING_THE_DEMOLISHERS_ALLIANCE_DEF, QUEST_FUELING_THE_DEMOLISHERS_HORDE_ATT, QUEST_FUELING_THE_DEMOLISHERS_HORDE_DEF, QUEST_HEALING_WITH_ROSES_HORDE_ATT, QUEST_HEALING_WITH_ROSES_HORDE_DEF, QUEST_JINXING_THE_WALLS_HORDE_ATT, QUEST_NO_MERCY_FOR_THE_MERCILESS_ALLIANCE_ATT, QUEST_NO_MERCY_FOR_THE_MERCILESS_ALLIANCE_DEF, QUEST_SHOUTHERN_SABOTAGE_ALLIANCE_DEF, QUEST_SLAY_THEM_ALL_HORDE_ATT, QUEST_SLAY_THEM_ALL_HORDE_DEF, QUEST_STATUS_COMPLETE, QUEST_STATUS_INCOMPLETE, QUEST_STATUS_NONE, QUEST_STOP_THE_SIEGE_ALLIANCE_DEF, QUEST_STOP_THE_SIEGE_HORDE_DEF, QUEST_TOPPLING_THE_TOWERS_HORDE_DEF, QUEST_WARDING_THE_WALLS_HORDE_DEF, QUEST_WARDING_THE_WARRIORS_ALLIANCE_ATT, QUEST_WARDING_THE_WARRIORS_ALLIANCE_DEF, sBattlefieldMgr, SendGossipMenuFor(), sObjectMgr, sPoolMgr, TEAM_ALLIANCE, and TEAM_HORDE.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/zone_wintergrasp.cpp