Azerotcore-wotlk: MPQFile Class Reference
MPQFile Class Reference
#include <mpq_libmpq04.h>
Public Member Functions
MPQFile (const char *filename)
~MPQFile ()
size_t read (void *dest, size_t bytes)
size_t getSize ()
size_t getPos ()
char * getBuffer ()
char * getPointer ()
bool isEof ()
void seek (int offset)
void seekRelative (int offset)
void close ()
MPQFile (const char *filename)
~MPQFile ()
size_t Read (void *dest, size_t bytes)
FILE * GetFileStream ()
size_t getSize ()
size_t getPos ()
char * getBuffer ()
char * getPointer ()
bool isEof ()
void seek (int offset)
void seekRelative (int offset)
void close ()
MPQFile (const char *filename)
~MPQFile ()
size_t read (void *dest, size_t bytes)
size_t getSize ()
size_t getPos ()
char * getBuffer ()
char * getPointer ()
bool isEof ()
void seek (int offset)
void seekRelative (int offset)
void close ()
Private Member Functions
MPQFile (const MPQFile &)
void operator= (const MPQFile &)
MPQFile (const MPQFile &)
void operator= (const MPQFile &)
MPQFile (const MPQFile &)
void operator= (const MPQFile &)
Private Attributes
bool eof
char * buffer
libmpq__off_t pointer
libmpq__off_t size
Detailed Description
Definition at line 72 of file mpq_libmpq04.h.
Constructor & Destructor Documentation
MPQFile() [1/6]
MPQFile::MPQFile (const MPQFile &) inline private
Definition at line 80 of file mpq_libmpq04.h.
 {}
MPQFile() [2/6]
MPQFile::MPQFile (const char * filename)
Definition at line 62 of file mpq_libmpq.cpp.
                                     :
     eof(false),
     buffer(nullptr),
     pointer(0),
     size(0)
 {
     for (auto & gOpenArchive : gOpenArchives)
     {
         mpq_archive* mpq_a = gOpenArchive->mpq_a;
         uint32_t filenum;
         if (libmpq__file_number(mpq_a, filename, &filenum)) continue;
         libmpq__off_t transferred;
         libmpq__file_unpacked_size(mpq_a, filenum, &size);
         // HACK: in patch.mpq some files don't want to open and give 1 for filesize
         if (size <= 1)
         {
             //            printf("warning: file %s has size %d; cannot read.\n", filename, size);
             eof = true;
             buffer = nullptr;
             return;
         }
         buffer = new char[size];
         //libmpq_file_getdata
         libmpq__file_read(mpq_a, filenum, (unsigned char*)buffer, size, &transferred);
         /*libmpq_file_getdata(&mpq_a, hash, fileno, (unsigned char*)buffer);*/
         return;
     }
     eof = true;
     buffer = nullptr;
 }
References eof, gOpenArchives, libmpq__file_number(), libmpq__file_read(), libmpq__file_unpacked_size(), and size.
~MPQFile() [1/3]
MPQFile::~MPQFile () inline
Definition at line 85 of file mpq_libmpq04.h.
 { close(); }
References close.
MPQFile() [3/6]
MPQFile::MPQFile (const MPQFile &) inline private
Definition at line 79 of file MPQ.h.
 {}
MPQFile() [4/6]
MPQFile::MPQFile (const char * filename)
~MPQFile() [2/3]
MPQFile::~MPQFile () inline
Definition at line 84 of file MPQ.h.
 { close(); }
References close().
MPQFile() [5/6]
MPQFile::MPQFile (const MPQFile &) inline private
Definition at line 79 of file mpq_libmpq04.h.
 {}
MPQFile() [6/6]
MPQFile::MPQFile (const char * filename)
~MPQFile() [3/3]
MPQFile::~MPQFile () inline
Definition at line 84 of file mpq_libmpq04.h.
 { close(); }
References close.
Member Function Documentation
close() [1/3]
void MPQFile::close ()
Definition at line 126 of file mpq_libmpq.cpp.
 {
     delete[] buffer;
     buffer = nullptr;
     eof = true;
 }
References buffer, and eof.
Referenced by ADTFile::init(), WDTFile::init(), FileLoader::loadFile(), ReadBuild(), ADTFile::~ADTFile(), ~MPQFile(), and WDTFile::~WDTFile().
close() [2/3]
void MPQFile::close ()
close() [3/3]
void MPQFile::close ()
getBuffer() [1/3]
char* MPQFile::getBuffer () inline
Definition at line 89 of file mpq_libmpq04.h.
 { return buffer; }
References buffer.
getBuffer() [2/3]
char* MPQFile::getBuffer () inline
Definition at line 89 of file MPQ.h.
 { return buffer; }
References buffer.
getBuffer() [3/3]
char* MPQFile::getBuffer () inline
Definition at line 88 of file mpq_libmpq04.h.
 { return buffer; }
References buffer.
GetFileStream()
FILE * MPQFile::GetFileStream ()
Definition at line 129 of file MPQ.cpp.
 {
     FILE* file = tmpfile();
     if (!file)
     {
         printf("Could not create temporary file. Please run as Administrator or root\n");
         exit(1);
     }
     fwrite(buffer, sizeof(char), size, file);
     fseek(file, 0, SEEK_SET);
     return file;
 }
References mpq::file, printf(), SEEK_SET, and size.
getPointer() [1/3]
char* MPQFile::getPointer () inline
Definition at line 90 of file mpq_libmpq04.h.
 { return buffer + pointer; }
Referenced by ExtractFile(), and ReadBuild().
getPointer() [2/3]
char* MPQFile::getPointer () inline
Definition at line 90 of file MPQ.h.
 { return buffer + pointer; }
References pointer.
getPointer() [3/3]
char* MPQFile::getPointer () inline
Definition at line 89 of file mpq_libmpq04.h.
 { return buffer + pointer; }
getPos() [1/3]
size_t MPQFile::getPos () inline
Definition at line 88 of file mpq_libmpq04.h.
 { return pointer; }
Referenced by ADTFile::init(), and WDTFile::init().
getPos() [2/3]
size_t MPQFile::getPos () inline
Definition at line 88 of file MPQ.h.
 { return pointer; }
References pointer.
getPos() [3/3]
size_t MPQFile::getPos () inline
Definition at line 87 of file mpq_libmpq04.h.
 { return pointer; }
getSize() [1/3]
size_t MPQFile::getSize () inline
Definition at line 87 of file mpq_libmpq04.h.
 { return size; }
Referenced by ExtractFile(), FileLoader::loadFile(), and ReadBuild().
getSize() [2/3]
size_t MPQFile::getSize () inline
Definition at line 87 of file MPQ.h.
 { return size; }
References size.
getSize() [3/3]
size_t MPQFile::getSize () inline
Definition at line 86 of file mpq_libmpq04.h.
 { return size; }
isEof() [1/3]
bool MPQFile::isEof () inline
Definition at line 91 of file mpq_libmpq04.h.
 { return eof; }
Referenced by ExtractFile(), ADTFile::init(), WDTFile::init(), FileLoader::loadFile(), and ReadBuild().
isEof() [2/3]
bool MPQFile::isEof () inline
Definition at line 91 of file MPQ.h.
 { return eof; }
References eof.
isEof() [3/3]
bool MPQFile::isEof () inline
Definition at line 90 of file mpq_libmpq04.h.
 { return eof; }
operator=() [1/3]
void MPQFile::operator= (const MPQFile &) inline private
Definition at line 81 of file mpq_libmpq04.h.
 {}
operator=() [2/3]
void MPQFile::operator= (const MPQFile &) inline private
Definition at line 80 of file MPQ.h.
 {}
operator=() [3/3]
void MPQFile::operator= (const MPQFile &) inline private
Definition at line 80 of file mpq_libmpq04.h.
 {}
read() [1/2]
size_t MPQFile::read (void * dest, size_t bytes)
Definition at line 96 of file mpq_libmpq.cpp.
 {
     if (eof) return 0;
     size_t rpos = pointer + bytes;
     if (rpos > size_t(size))
     {
         bytes = size - pointer;
         eof = true;
     }
     memcpy(dest, &(buffer[pointer]), bytes);
     pointer = rpos;
     return bytes;
 }
References eof, memcpy, pointer, and size.
Referenced by ADTFile::init(), WDTFile::init(), FileLoader::loadFile(), mpq.Reader::readline(), and mpq.Reader::seek().
Read()
size_t MPQFile::Read (void * dest, size_t bytes)
Definition at line 91 of file MPQ.cpp.
 {
     if (eof)
         return 0;
     size_t rpos = pointer + bytes;
     if (rpos > size_t(size))
     {
         bytes = size - pointer;
         eof = true;
     }
     memcpy(dest, &(buffer[pointer]), bytes);
     pointer = rpos;
     return bytes;
 }
References eof, memcpy, pointer, and size.
read() [2/2]
size_t MPQFile::read (void * dest, size_t bytes)
Referenced by mpq.Reader::readline(), and mpq.Reader::seek().
seek() [1/3]
void MPQFile::seek (int offset)
Definition at line 114 of file mpq_libmpq.cpp.
 {
     pointer = offset;
     eof = (pointer >= size);
 }
References eof, pointer, and size.
Referenced by ADTFile::init(), WDTFile::init(), and mpq.Reader::readline().
seek() [2/3]
void MPQFile::seek (int offset)
Referenced by mpq.Reader::readline().
seek() [3/3]
void MPQFile::seek (int offset)
Referenced by mpq.Reader::readline().
seekRelative() [1/3]
void MPQFile::seekRelative (int offset)
Definition at line 120 of file mpq_libmpq.cpp.
 {
     pointer += offset;
     eof = (pointer >= size);
 }
References eof, pointer, and size.
seekRelative() [2/3]
void MPQFile::seekRelative (int offset)
seekRelative() [3/3]
void MPQFile::seekRelative (int offset)
Member Data Documentation
buffer
char * MPQFile::buffer private
Definition at line 76 of file mpq_libmpq04.h.
Referenced by close(), and getBuffer().
eof
bool MPQFile::eof private
Definition at line 75 of file mpq_libmpq04.h.
Referenced by close(), isEof(), MPQFile(), read(), Read(), seek(), and seekRelative().
pointer
libmpq__off_t MPQFile::pointer private
Definition at line 77 of file mpq_libmpq04.h.
Referenced by getPointer(), getPos(), read(), Read(), seek(), and seekRelative().
size
libmpq__off_t MPQFile::size private
Definition at line 77 of file mpq_libmpq04.h.
Referenced by GetFileStream(), getSize(), MPQFile(), read(), Read(), seek(), and seekRelative().
The documentation for this class was generated from the following files:
src/tools/map_extractor/mpq_libmpq04.h
src/tools/mesh_extractor/MPQ.h
src/tools/map_extractor/mpq_libmpq.cpp
src/tools/mesh_extractor/MPQ.cpp