Azerotcore-wotlk: deps/mysqllite/mysys/mf_getdate.c File Reference
mf_getdate.c File Reference
#include "mysys_priv.h"
#include <m_string.h>
Functions
void get_date (register char *to, int flag, time_t date)
Function Documentation
get_date()
void get_date (register char * to, int flag, time_t date)
Definition at line 37 of file mf_getdate.c.
 {
    reg2 struct tm *start_time;
    time_t skr;
 #if defined(HAVE_LOCALTIME_R) && defined(_REENTRANT)
   struct tm tm_tmp;
 #endif
    skr=date ? (time_t) date : my_time(0);
 #if defined(HAVE_LOCALTIME_R) && defined(_REENTRANT)
    if (flag & GETDATE_GMT)
      gmtime_r(&skr,&tm_tmp);
    else
      localtime_r(&skr,&tm_tmp);
    start_time= &tm_tmp;
 #else
    if (flag & GETDATE_GMT)
      start_time= gmtime(&skr);
    else
      start_time= localtime(&skr);
 #endif
    if (flag & GETDATE_SHORT_DATE)
      sprintf(to,"%02d%02d%02d",
          start_time->tm_year % 100,
          start_time->tm_mon+1,
          start_time->tm_mday);
    else
      sprintf(to, ((flag & GETDATE_FIXEDLENGTH) ?
           "%4d-%02d-%02d" : "%d-%02d-%02d"),
          start_time->tm_year+1900,
          start_time->tm_mon+1,
          start_time->tm_mday);
    if (flag & GETDATE_DATE_TIME)
      sprintf(strend(to),
          ((flag & GETDATE_FIXEDLENGTH) ?
           " %02d:%02d:%02d" : " %2d:%02d:%02d"),
          start_time->tm_hour,
          start_time->tm_min,
          start_time->tm_sec);
    else if (flag & GETDATE_HHMMSSTIME)
      sprintf(strend(to),"%02d%02d%02d",
          start_time->tm_hour,
          start_time->tm_min,
          start_time->tm_sec);
 } /* get_date */
References GETDATE_DATE_TIME, GETDATE_FIXEDLENGTH, GETDATE_GMT, GETDATE_HHMMSSTIME, GETDATE_SHORT_DATE, gmtime(), detail::gmtime_r(), localtime(), localtime_r(), my_time(), reg2, sprintf(), and strend().