Azerotcore-wotlk: AuctionHouseObject Class Reference
AuctionHouseObject Class Reference
#include <AuctionHouseMgr.h>
Public Types
typedef std::map< uint32, AuctionEntry * > AuctionEntryMap
Public Member Functions
AuctionHouseObject ()
~AuctionHouseObject ()
uint32 Getcount () const
AuctionEntryMap::iterator GetAuctionsBegin ()
AuctionEntryMap::iterator GetAuctionsEnd ()
AuctionEntryMap const & GetAuctions ()
AuctionEntry * GetAuction (uint32 id) const
void AddAuction (AuctionEntry *auction)
bool RemoveAuction (AuctionEntry *auction)
void Update ()
void BuildListBidderItems (WorldPacket &data, Player *player, uint32 &count, uint32 &totalcount)
void BuildListOwnerItems (WorldPacket &data, Player *player, uint32 &count, uint32 &totalcount)
bool BuildListAuctionItems (WorldPacket &data, Player *player, std::wstring const &searchedname, uint32 listfrom, uint8 levelmin, uint8 levelmax, uint8 usable, uint32 inventoryType, uint32 itemClass, uint32 itemSubClass, uint32 quality, uint32 &count, uint32 &totalcount, uint8 getAll, AuctionSortOrderVector const &sortOrder)
Private Attributes
AuctionEntryMap AuctionsMap
AuctionEntryMap::const_iterator next
Detailed Description
Definition at line 129 of file AuctionHouseMgr.h.
Member Typedef Documentation
AuctionEntryMap
typedef std::map<uint32, AuctionEntry*> AuctionHouseObject::AuctionEntryMap
Definition at line 140 of file AuctionHouseMgr.h.
Constructor & Destructor Documentation
AuctionHouseObject()
AuctionHouseObject::AuctionHouseObject () inline
Definition at line 133 of file AuctionHouseMgr.h.
 { next = AuctionsMap.begin(); }
References AuctionsMap, and next.
~AuctionHouseObject()
AuctionHouseObject::~AuctionHouseObject () inline
Definition at line 134 of file AuctionHouseMgr.h.
     {
         for (auto & itr : AuctionsMap)
             delete itr.second;
     }
References AuctionsMap.
Member Function Documentation
AddAuction()
void AuctionHouseObject::AddAuction (AuctionEntry * auction)
Definition at line 625 of file AuctionHouseMgr.cpp.
 {
     ASSERT(auction);
     AuctionsMap[auction->Id] = auction;
     sScriptMgr->OnAuctionAdd(this, auction);
 }
References ASSERT, AuctionsMap, AuctionEntry::Id, and sScriptMgr.
Referenced by WorldSession::HandleAuctionSellItem(), and AuctionHouseMgr::LoadAuctions().
BuildListAuctionItems()
bool AuctionHouseObject::BuildListAuctionItems (WorldPacket & data, Player * player, std::wstring const & searchedname, uint32 listfrom, uint8 levelmin, uint8 levelmax, uint8 usable, uint32 inventoryType, uint32 itemClass, uint32 itemSubClass, uint32 quality, uint32 & count, uint32 & totalcount, uint8 getAll, AuctionSortOrderVector const & sortOrder)
Definition at line 721 of file AuctionHouseMgr.cpp.
 {
     uint32 itrcounter = 0;
     std::vector<AuctionEntry*> auctionShortlist;
     // pussywizard: optimization, this is a simplified case
     if (itemClass == 0xffffffff && itemSubClass == 0xffffffff && inventoryType == 0xffffffff && quality == 0xffffffff && levelmin == 0x00 && levelmax == 0x00 && usable == 0x00 && wsearchedname.empty())
     {
         auto itr = GetAuctionsBegin();
         for (; itr != GetAuctionsEnd(); ++itr)
         {
             auctionShortlist.push_back(itr->second);
         }
     }
     else
     {
         time_t curTime = sWorld->GetGameTime();
         int loc_idx = player->GetSession()->GetSessionDbLocaleIndex();
         int locdbc_idx = player->GetSession()->GetSessionDbcLocale();
         for (AuctionEntryMap::const_iterator itr = AuctionsMap.begin(); itr != AuctionsMap.end(); ++itr)
         {
             if (!AsyncAuctionListingMgr::IsAuctionListingAllowed())                                                    // pussywizard: World::Update is waiting for us...
             {
                 if ((itrcounter++) % 100 == 0) // check condition every 100 iterations
                 {
                     if (avgDiffTracker.getAverage() >= 30 || getMSTimeDiff(World::GetGameTimeMS(), getMSTime()) >= 10) // pussywizard: stop immediately if diff is high or waiting too long
                     {
                         return false;
                     }
                 }
             }
             AuctionEntry* Aentry = itr->second;
             // Skip expired auctions
             if (Aentry->expire_time < curTime)
             {
                 continue;
             }
             Item* item = sAuctionMgr->GetAItem(Aentry->item_guid);
             if (!item)
             {
                 continue;
             }
             ItemTemplate const* proto = item->GetTemplate();
             if (itemClass != 0xffffffff && proto->Class != itemClass)
             {
                 continue;
             }
             if (itemSubClass != 0xffffffff && proto->SubClass != itemSubClass)
             {
                 continue;
             }
             if (inventoryType != 0xffffffff && proto->InventoryType != inventoryType)
             {
                 // xinef: exception, robes are counted as chests
                 if (inventoryType != INVTYPE_CHEST || proto->InventoryType != INVTYPE_ROBE)
                 {
                     continue;
                 }
             }
             if (quality != 0xffffffff && proto->Quality < quality)
             {
                 continue;
             }
             if (levelmin != 0x00 && (proto->RequiredLevel < levelmin || (levelmax != 0x00 && proto->RequiredLevel > levelmax)))
             {
                 continue;
             }
             if (usable != 0x00)
             {
                 if (player->CanUseItem(item) != EQUIP_ERR_OK)
                 {
                     continue;
                 }
                 // xinef: check already learded recipes and pets
                 if (proto->Spells[1].SpellTrigger == ITEM_SPELLTRIGGER_LEARN_SPELL_ID && player->HasSpell(proto->Spells[1].SpellId))
                 {
                     continue;
                 }
             }
             // Allow search by suffix (ie: of the Monkey) or partial name (ie: Monkey)
             // No need to do any of this if no search term was entered
             if (!wsearchedname.empty())
             {
                 std::string name = proto->Name1;
                 if (name.empty())
                 {
                     continue;
                 }
                 // local name
                 if (loc_idx >= 0)
                     if (ItemLocale const* il = sObjectMgr->GetItemLocale(proto->ItemId))
                         ObjectMgr::GetLocaleString(il->Name, loc_idx, name);
                 // DO NOT use GetItemEnchantMod(proto->RandomProperty) as it may return a result
                 //  that matches the search but it may not equal item->GetItemRandomPropertyId()
                 //  used in BuildAuctionInfo() which then causes wrong items to be listed
                 int32 propRefID = item->GetItemRandomPropertyId();
                 if (propRefID)
                 {
                     // Append the suffix to the name (ie: of the Monkey) if one exists
                     // These are found in ItemRandomSuffix.dbc and ItemRandomProperties.dbc
                     // even though the DBC name seems misleading
                     std::array<char const*, 16> const* suffix = nullptr;
                     if (propRefID < 0)
                     {
                         const ItemRandomSuffixEntry* itemRandEntry = sItemRandomSuffixStore.LookupEntry(-item->GetItemRandomPropertyId());
                         if (itemRandEntry)
                             suffix = &itemRandEntry->Name;
                     }
                     else
                     {
                         const ItemRandomPropertiesEntry* itemRandEntry = sItemRandomPropertiesStore.LookupEntry(item->GetItemRandomPropertyId());
                         if (itemRandEntry)
                             suffix = &itemRandEntry->Name;
                     }
                     // dbc local name
                     if (suffix)
                     {
                         // Append the suffix (ie: of the Monkey) to the name using localization
                         // or default enUS if localization is invalid
                         name += ' ';
                         name += (*suffix)[locdbc_idx >= 0 ? locdbc_idx : LOCALE_enUS];
                     }
                 }
                 // Perform the search (with or without suffix)
                 if (!Utf8FitTo(name, wsearchedname))
                 {
                     continue;
                 }
             }
             auctionShortlist.push_back(Aentry);
         }
     }
     // Check if sort enabled, and first sort column is valid, if not don't sort
     if (sortOrder.size() > 0)
     {
         AuctionSortInfo const& sortInfo = *sortOrder.begin();
         if (sortInfo.sortOrder >= AUCTION_SORT_MINLEVEL && sortInfo.sortOrder < AUCTION_SORT_MAX && sortInfo.sortOrder != AUCTION_SORT_UNK4)
         {
             // Partial sort to improve performance a bit, but the last pages will burn
             if (listfrom + 50 <= auctionShortlist.size())
             {
                 std::partial_sort(auctionShortlist.begin(), auctionShortlist.begin() + listfrom + 50, auctionShortlist.end(),
                     std::bind(SortAuction, std::placeholders::_1, std::placeholders::_2, sortOrder, player, sortInfo.sortOrder == AUCTION_SORT_BID));
             }
             else
             {
                 std::sort(auctionShortlist.begin(), auctionShortlist.end(), std::bind(SortAuction, std::placeholders::_1, std::placeholders::_2, sortOrder,
                     player, sortInfo.sortOrder == AUCTION_SORT_BID));
             }
         }
     }
     for (auto auction : auctionShortlist)
     {
         // Add the item if no search term or if entered search term was found
         if (count < 50 && totalcount >= listfrom)
         {
             Item* item = sAuctionMgr->GetAItem(auction->item_guid);
             if (!item)
             {
                 continue;
             }
             ++count;
             auction->BuildAuctionInfo(data);
         }
         ++totalcount;
     }
     return true;
 }
References AUCTION_SORT_BID, AUCTION_SORT_MAX, AUCTION_SORT_MINLEVEL, AUCTION_SORT_UNK4, AuctionsMap, avgDiffTracker, Player::CanUseItem(), ItemTemplate::Class, count(), EQUIP_ERR_OK, AuctionEntry::expire_time, GetAuctionsBegin(), GetAuctionsEnd(), AvgDiffTracker::getAverage(), World::GetGameTimeMS(), Item::GetItemRandomPropertyId(), ObjectMgr::GetLocaleString(), getMSTime(), getMSTimeDiff(), Player::GetSession(), WorldSession::GetSessionDbcLocale(), WorldSession::GetSessionDbLocaleIndex(), Item::GetTemplate(), Player::HasSpell(), ItemTemplate::InventoryType, INVTYPE_CHEST, INVTYPE_ROBE, AsyncAuctionListingMgr::IsAuctionListingAllowed(), AuctionEntry::item_guid, ITEM_SPELLTRIGGER_LEARN_SPELL_ID, ItemTemplate::ItemId, LOCALE_enUS, name, ItemRandomPropertiesEntry::Name, ItemRandomSuffixEntry::Name, ItemTemplate::Name1, ItemTemplate::Quality, ItemTemplate::RequiredLevel, sAuctionMgr, sItemRandomPropertiesStore, sItemRandomSuffixStore, sObjectMgr, SortAuction(), AuctionSortInfo::sortOrder, _Spell::SpellId, ItemTemplate::Spells, _Spell::SpellTrigger, ItemTemplate::SubClass, sWorld, and Utf8FitTo().
Referenced by AuctionListItemsDelayEvent::Execute().
BuildListBidderItems()
void AuctionHouseObject::BuildListBidderItems (WorldPacket & data, Player * player, uint32 & count, uint32 & totalcount)
Definition at line 691 of file AuctionHouseMgr.cpp.
 {
     for (AuctionEntryMap::const_iterator itr = AuctionsMap.begin(); itr != AuctionsMap.end(); ++itr)
     {
         AuctionEntry* Aentry = itr->second;
         if (Aentry && Aentry->bidder == player->GetGUID())
         {
             if (itr->second->BuildAuctionInfo(data))
                 ++count;
             ++totalcount;
         }
     }
 }
References AuctionsMap, AuctionEntry::bidder, count(), and Object::GetGUID().
Referenced by WorldSession::HandleAuctionListBidderItems().
BuildListOwnerItems()
void AuctionHouseObject::BuildListOwnerItems (WorldPacket & data, Player * player, uint32 & count, uint32 & totalcount)
Definition at line 706 of file AuctionHouseMgr.cpp.
 {
     for (AuctionEntryMap::const_iterator itr = AuctionsMap.begin(); itr != AuctionsMap.end(); ++itr)
     {
         AuctionEntry* Aentry = itr->second;
         if (Aentry && Aentry->owner == player->GetGUID())
         {
             if (Aentry->BuildAuctionInfo(data))
                 ++count;
             ++totalcount;
         }
     }
 }
References AuctionsMap, AuctionEntry::BuildAuctionInfo(), count(), Object::GetGUID(), and AuctionEntry::owner.
Referenced by WorldSession::HandleAuctionListOwnerItemsEvent().
GetAuction()
AuctionEntry* AuctionHouseObject::GetAuction (uint32 id) const inline
Definition at line 148 of file AuctionHouseMgr.h.
     {
         AuctionEntryMap::const_iterator itr = AuctionsMap.find(id);
         return itr != AuctionsMap.end() ? itr->second : nullptr;
     }
References AuctionsMap.
Referenced by WorldSession::HandleAuctionListBidderItems(), WorldSession::HandleAuctionPlaceBid(), and WorldSession::HandleAuctionRemoveItem().
GetAuctions()
AuctionEntryMap const& AuctionHouseObject::GetAuctions () inline
Definition at line 146 of file AuctionHouseMgr.h.
 { return AuctionsMap; }
References AuctionsMap.
Referenced by WorldSession::HandleCharFactionOrRaceChangeCallback().
GetAuctionsBegin()
AuctionEntryMap::iterator AuctionHouseObject::GetAuctionsBegin () inline
Definition at line 144 of file AuctionHouseMgr.h.
 { return AuctionsMap.begin(); }
References AuctionsMap.
Referenced by BuildListAuctionItems().
GetAuctionsEnd()
AuctionEntryMap::iterator AuctionHouseObject::GetAuctionsEnd () inline
Definition at line 145 of file AuctionHouseMgr.h.
 { return AuctionsMap.end(); }
References AuctionsMap.
Referenced by BuildListAuctionItems().
Getcount()
uint32 AuctionHouseObject::Getcount () const inline
Definition at line 142 of file AuctionHouseMgr.h.
 { return AuctionsMap.size(); }
References AuctionsMap.
RemoveAuction()
bool AuctionHouseObject::RemoveAuction (AuctionEntry * auction)
Definition at line 633 of file AuctionHouseMgr.cpp.
 {
     bool wasInMap = !!AuctionsMap.erase(auction->Id);
     sScriptMgr->OnAuctionRemove(this, auction);
     // we need to delete the entry, it is not referenced any more
     delete auction;
     auction = nullptr;
     return wasInMap;
 }
References AuctionsMap, AuctionEntry::Id, and sScriptMgr.
Referenced by WorldSession::HandleAuctionPlaceBid(), WorldSession::HandleAuctionRemoveItem(), and Update().
Update()
void AuctionHouseObject::Update ()
Handle expired auctions
Either cancel the auction if there was no bidder
Or perform the transaction
In any case clear the auction
Definition at line 646 of file AuctionHouseMgr.cpp.
 {
     time_t checkTime = sWorld->GetGameTime() + 60;
     // If storage is empty, no need to update. next == nullptr in this case.
     if (AuctionsMap.empty())
         return;
     CharacterDatabaseTransaction trans = CharacterDatabase.BeginTransaction();
     for (AuctionEntryMap::iterator itr, iter = AuctionsMap.begin(); iter != AuctionsMap.end(); )
     {
         itr = iter++;
         AuctionEntry* auction = (*itr).second;
         if (auction->expire_time > checkTime)
             continue;
         if (!auction->bidder)
         {
             sAuctionMgr->SendAuctionExpiredMail(auction, trans);
             sScriptMgr->OnAuctionExpire(this, auction);
         }
         else
         {
             //we should send an "item sold" message if the seller is online
             //we send the item to the winner
             //we send the money to the seller
             sAuctionMgr->SendAuctionSuccessfulMail(auction, trans);
             sAuctionMgr->SendAuctionWonMail(auction, trans);
             sScriptMgr->OnAuctionSuccessful(this, auction);
         }
         auction->DeleteFromDB(trans);
         sAuctionMgr->RemoveAItem(auction->item_guid);
         RemoveAuction(auction);
     }
     CharacterDatabase.CommitTransaction(trans);
 }
References AuctionsMap, AuctionEntry::bidder, CharacterDatabase, AuctionEntry::DeleteFromDB(), AuctionEntry::expire_time, AuctionEntry::item_guid, RemoveAuction(), sAuctionMgr, sScriptMgr, and sWorld.
Referenced by AuctionHouseMgr::Update().
Member Data Documentation
AuctionsMap
AuctionEntryMap AuctionHouseObject::AuctionsMap private
Definition at line 168 of file AuctionHouseMgr.h.
Referenced by AddAuction(), AuctionHouseObject(), BuildListAuctionItems(), BuildListBidderItems(), BuildListOwnerItems(), GetAuction(), GetAuctions(), GetAuctionsBegin(), GetAuctionsEnd(), Getcount(), RemoveAuction(), Update(), and ~AuctionHouseObject().
next
AuctionEntryMap::const_iterator AuctionHouseObject::next private
Definition at line 171 of file AuctionHouseMgr.h.
Referenced by AuctionHouseObject().
The documentation for this class was generated from the following files:
src/server/game/AuctionHouse/AuctionHouseMgr.h
src/server/game/AuctionHouse/AuctionHouseMgr.cpp