Azerotcore-wotlk: boss_curator::boss_curatorAI Struct Reference
boss_curator::boss_curatorAI Struct Reference
Public Member Functions
boss_curatorAI (Creature *creature)
void Reset () override
void KilledUnit (Unit *) override
void JustDied (Unit *killer) override
void EnterCombat (Unit *who) override
void JustSummoned (Creature *summon) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 54 of file boss_curator.cpp.
Constructor & Destructor Documentation
boss_curatorAI()
boss_curator::boss_curatorAI::boss_curatorAI (Creature * creature) inline
Definition at line 56 of file boss_curator.cpp.
 : BossAI(creature, DATA_CURATOR) { }
Member Function Documentation
EnterCombat()
void boss_curator::boss_curatorAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from BossAI.
Definition at line 82 of file boss_curator.cpp.
         {
             BossAI::EnterCombat(who);
             Talk(SAY_AGGRO);
             events.ScheduleEvent(EVENT_SPELL_HATEFUL_BOLT, 10000);
             events.ScheduleEvent(EVENT_SPELL_ASTRAL_FLARE, 6000);
             events.ScheduleEvent(EVENT_SPELL_BERSERK, 600000);
             events.ScheduleEvent(EVENT_CHECK_HEALTH, 1000);
             DoZoneInCombat();
         }
References CreatureAI::DoZoneInCombat(), BossAI::EnterCombat(), EVENT_CHECK_HEALTH, EVENT_SPELL_ASTRAL_FLARE, EVENT_SPELL_BERSERK, EVENT_SPELL_HATEFUL_BOLT, SAY_AGGRO, and CreatureAI::Talk().
JustDied()
void boss_curator::boss_curatorAI::JustDied (Unit * killer) inline override virtual
Reimplemented from BossAI.
Definition at line 76 of file boss_curator.cpp.
         {
             BossAI::JustDied(killer);
             Talk(SAY_DEATH);
         }
References BossAI::JustDied(), SAY_DEATH, and CreatureAI::Talk().
JustSummoned()
void boss_curator::boss_curatorAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
Definition at line 94 of file boss_curator.cpp.
         {
             summons.Summon(summon);
             if (Unit* target = summon->SelectNearbyTarget(nullptr, 40.0f))
             {
                 summon->AI()->AttackStart(target);
                 summon->AddThreat(target, 1000.0f);
             }
             summon->SetInCombatWithZone();
         }
References Unit::AddThreat(), Creature::AI(), UnitAI::AttackStart(), Unit::SelectNearbyTarget(), Creature::SetInCombatWithZone(), SummonList::Summon(), and BossAI::summons.
KilledUnit()
void boss_curator::boss_curatorAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 67 of file boss_curator.cpp.
         {
             if (events.GetNextEventTime(EVENT_KILL_TALK) == 0)
             {
                 Talk(SAY_KILL);
                 events.ScheduleEvent(EVENT_KILL_TALK, 5000);
             }
         }
References EVENT_KILL_TALK, SAY_KILL, and CreatureAI::Talk().
Reset()
void boss_curator::boss_curatorAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 58 of file boss_curator.cpp.
         {
             BossAI::Reset();
             me->ApplySpellImmune(0, IMMUNITY_DAMAGE, SPELL_SCHOOL_MASK_ARCANE, true);
             me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_PERIODIC_MANA_LEECH, true);
             me->ApplySpellImmune(0, IMMUNITY_STATE, SPELL_AURA_POWER_BURN, true);
             me->ApplySpellImmune(0, IMMUNITY_EFFECT, SPELL_EFFECT_POWER_BURN, true);
         }
References Unit::ApplySpellImmune(), IMMUNITY_DAMAGE, IMMUNITY_EFFECT, IMMUNITY_STATE, ScriptedAI::me, BossAI::Reset(), SPELL_AURA_PERIODIC_MANA_LEECH, SPELL_AURA_POWER_BURN, SPELL_EFFECT_POWER_BURN, and SPELL_SCHOOL_MASK_ARCANE.
UpdateAI()
void boss_curator::boss_curatorAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 106 of file boss_curator.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_CHECK_HEALTH:
                     if (me->HealthBelowPct(16))
                     {
                         events.CancelEvent(EVENT_SPELL_ASTRAL_FLARE);
                         me->CastSpell(me, SPELL_ARCANE_INFUSION, true);
                         Talk(SAY_ENRAGE);
                         break;
                     }
                     events.ScheduleEvent(EVENT_CHECK_HEALTH, 1000);
                     break;
                 case EVENT_SPELL_BERSERK:
                     Talk(SAY_ENRAGE);
                     me->InterruptNonMeleeSpells(true);
                     me->CastSpell(me, SPELL_ASTRAL_DECONSTRUCTION, true);
                     break;
                 case EVENT_SPELL_HATEFUL_BOLT:
                     if (Unit* target = SelectTarget(SELECT_TARGET_TOPAGGRO, urand(1, 2), 40.0f))
                         me->CastSpell(target, SPELL_HATEFUL_BOLT, false);
                     events.ScheduleEvent(EVENT_SPELL_HATEFUL_BOLT, urand(5000, 7500) * (events.GetNextEventTime(EVENT_SPELL_BERSERK) == 0 ? 1 : 2));
                     break;
                 case EVENT_SPELL_ASTRAL_FLARE:
                     {
                         me->CastSpell(me, RAND(SPELL_SUMMON_ASTRAL_FLARE1, SPELL_SUMMON_ASTRAL_FLARE2, SPELL_SUMMON_ASTRAL_FLARE3, SPELL_SUMMON_ASTRAL_FLARE4), false);
                         int32 mana = CalculatePct(me->GetMaxPower(POWER_MANA), 10);
                         me->ModifyPower(POWER_MANA, -mana);
                         if (me->GetPowerPct(POWER_MANA) < 10.0f)
{
                             Talk(SAY_EVOCATE);
                             me->CastSpell(me, SPELL_EVOCATION, false);
                             events.DelayEvents(20000);
                             events.ScheduleEvent(EVENT_SPELL_ASTRAL_FLARE, 20000);
                         }
                         else
{
                             if (roll_chance_i(50))
                                 Talk(SAY_SUMMON);
                             events.ScheduleEvent(EVENT_SPELL_ASTRAL_FLARE, 10000);
                         }
                         break;
                     }
             }
             DoMeleeAttackIfReady();
         }
References CalculatePct(), Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), EVENT_CHECK_HEALTH, EVENT_SPELL_ASTRAL_FLARE, EVENT_SPELL_BERSERK, EVENT_SPELL_HATEFUL_BOLT, Unit::GetMaxPower(), Unit::GetPowerPct(), Unit::HasUnitState(), Unit::HealthBelowPct(), Unit::InterruptNonMeleeSpells(), ScriptedAI::me, Unit::ModifyPower(), POWER_MANA, RAND(), roll_chance_i(), SAY_ENRAGE, SAY_EVOCATE, SAY_SUMMON, SELECT_TARGET_TOPAGGRO, UnitAI::SelectTarget(), SPELL_ARCANE_INFUSION, SPELL_ASTRAL_DECONSTRUCTION, SPELL_EVOCATION, SPELL_HATEFUL_BOLT, SPELL_SUMMON_ASTRAL_FLARE1, SPELL_SUMMON_ASTRAL_FLARE2, SPELL_SUMMON_ASTRAL_FLARE3, SPELL_SUMMON_ASTRAL_FLARE4, CreatureAI::Talk(), UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
The documentation for this struct was generated from the following file:
src/server/scripts/EasternKingdoms/Karazhan/boss_curator.cpp