Azerotcore-wotlk: VMAP::IVMapMgr Class Reference
VMAP::IVMapMgr Class Reference abstract
#include <IVMapMgr.h>
Public Member Functions
IVMapMgr ()
virtual ~IVMapMgr ()=default
virtual int loadMap (const char *pBasePath, unsigned int pMapId, int x, int y)=0
virtual bool existsMap (const char *pBasePath, unsigned int pMapId, int x, int y)=0
virtual void unloadMap (unsigned int pMapId, int x, int y)=0
virtual void unloadMap (unsigned int pMapId)=0
virtual bool isInLineOfSight (unsigned int pMapId, float x1, float y1, float z1, float x2, float y2, float z2)=0
virtual float getHeight (unsigned int pMapId, float x, float y, float z, float maxSearchDist)=0
virtual bool GetObjectHitPos (unsigned int pMapId, float x1, float y1, float z1, float x2, float y2, float z2, float &rx, float &ry, float &rz, float pModifyDist)=0
virtual bool processCommand (char *pCommand)=0
void setEnableLineOfSightCalc (bool pVal)
void setEnableHeightCalc (bool pVal)
bool isLineOfSightCalcEnabled () const
bool isHeightCalcEnabled () const
bool isMapLoadingEnabled () const
virtual std::string getDirFileName (unsigned int pMapId, int x, int y) const =0
virtual bool GetAreaInfo (uint32 pMapId, float x, float y, float &z, uint32 &flags, int32 &adtId, int32 &rootId, int32 &groupId) const =0
virtual bool GetLiquidLevel (uint32 pMapId, float x, float y, float z, uint8 ReqLiquidType, float &level, float &floor, uint32 &type, uint32 &mogpFlags) const =0
virtual void GetAreaAndLiquidData (uint32 mapId, float x, float y, float z, uint8 reqLiquidType, AreaAndLiquidData &data) const =0
Private Attributes
bool iEnableLineOfSightCalc {true}
bool iEnableHeightCalc {true}
Detailed Description
Definition at line 69 of file IVMapMgr.h.
Constructor & Destructor Documentation
IVMapMgr()
VMAP::IVMapMgr::IVMapMgr () inline
Definition at line 76 of file IVMapMgr.h.
 { }
~IVMapMgr()
virtual VMAP::IVMapMgr::~IVMapMgr () virtual default
Member Function Documentation
existsMap()
virtual bool VMAP::IVMapMgr::existsMap (const char * pBasePath, unsigned int pMapId, int x, int y) pure virtual
Implemented in VMAP::VMapMgr2.
GetAreaAndLiquidData()
virtual void VMAP::IVMapMgr::GetAreaAndLiquidData (uint32 mapId, float x, float y, float z, uint8 reqLiquidType, AreaAndLiquidData & data) const pure virtual
Implemented in VMAP::VMapMgr2.
Referenced by Map::GetFullTerrainStatusForPosition().
GetAreaInfo()
virtual bool VMAP::IVMapMgr::GetAreaInfo (uint32 pMapId, float x, float y, float & z, uint32 & flags, int32 & adtId, int32 & rootId, int32 & groupId) const pure virtual
Query world model area info.
Parameters
z gets adjusted to the ground height for which this are info is valid
Implemented in VMAP::VMapMgr2.
Referenced by Map::GetAreaInfo().
getDirFileName()
virtual std::string VMAP::IVMapMgr::getDirFileName (unsigned int pMapId, int x, int y) const pure virtual
Implemented in VMAP::VMapMgr2.
getHeight()
virtual float VMAP::IVMapMgr::getHeight (unsigned int pMapId, float x, float y, float z, float maxSearchDist) pure virtual
Implemented in VMAP::VMapMgr2.
Referenced by Map::GetHeight().
GetLiquidLevel()
virtual bool VMAP::IVMapMgr::GetLiquidLevel (uint32 pMapId, float x, float y, float z, uint8 ReqLiquidType, float & level, float & floor, uint32 & type, uint32 & mogpFlags) const pure virtual
Implemented in VMAP::VMapMgr2.
Referenced by Map::GetLiquidData().
GetObjectHitPos()
virtual bool VMAP::IVMapMgr::GetObjectHitPos (unsigned int pMapId, float x1, float y1, float z1, float x2, float y2, float z2, float & rx, float & ry, float & rz, float pModifyDist) pure virtual
test if we hit an object. return true if we hit one. rx, ry, rz will hold the hit position or the dest position, if no intersection was found return a position, that is pReduceDist closer to the origin
Implemented in VMAP::VMapMgr2.
isHeightCalcEnabled()
bool VMAP::IVMapMgr::isHeightCalcEnabled () const inline
Definition at line 111 of file IVMapMgr.h.
 { return (iEnableHeightCalc); }
References iEnableHeightCalc.
Referenced by VMAP::VMapMgr2::getHeight(), and server_commandscript::HandleServerDebugCommand().
isInLineOfSight()
virtual bool VMAP::IVMapMgr::isInLineOfSight (unsigned int pMapId, float x1, float y1, float z1, float x2, float y2, float z2) pure virtual
Implemented in VMAP::VMapMgr2.
isLineOfSightCalcEnabled()
bool VMAP::IVMapMgr::isLineOfSightCalcEnabled () const inline
Definition at line 110 of file IVMapMgr.h.
 { return (iEnableLineOfSightCalc); }
References iEnableLineOfSightCalc.
Referenced by VMAP::VMapMgr2::GetObjectHitPos(), server_commandscript::HandleServerDebugCommand(), and VMAP::VMapMgr2::isInLineOfSight().
isMapLoadingEnabled()
bool VMAP::IVMapMgr::isMapLoadingEnabled () const inline
Definition at line 112 of file IVMapMgr.h.
 { return (iEnableLineOfSightCalc || iEnableHeightCalc  ); }
References iEnableHeightCalc, and iEnableLineOfSightCalc.
Referenced by VMAP::VMapMgr2::loadMap().
loadMap()
virtual int VMAP::IVMapMgr::loadMap (const char * pBasePath, unsigned int pMapId, int x, int y) pure virtual
Implemented in VMAP::VMapMgr2.
Referenced by MMAP::TerrainBuilder::loadVMap().
processCommand()
virtual bool VMAP::IVMapMgr::processCommand (char * pCommand) pure virtual
send debug commands
Implemented in VMAP::VMapMgr2.
setEnableHeightCalc()
void VMAP::IVMapMgr::setEnableHeightCalc (bool pVal) inline
Enable/disable model height calculation It is enabled by default. If it is enabled in mid game the maps have to loaded manualy
Definition at line 108 of file IVMapMgr.h.
 { iEnableHeightCalc = pVal; }
References iEnableHeightCalc.
Referenced by World::LoadConfigSettings().
setEnableLineOfSightCalc()
void VMAP::IVMapMgr::setEnableLineOfSightCalc (bool pVal) inline
Enable/disable LOS calculation It is enabled by default. If it is enabled in mid game the maps have to loaded manualy
Definition at line 103 of file IVMapMgr.h.
 { iEnableLineOfSightCalc = pVal; }
References iEnableLineOfSightCalc.
Referenced by World::LoadConfigSettings().
unloadMap() [1/2]
virtual void VMAP::IVMapMgr::unloadMap (unsigned int pMapId) pure virtual
Implemented in VMAP::VMapMgr2.
unloadMap() [2/2]
virtual void VMAP::IVMapMgr::unloadMap (unsigned int pMapId, int x, int y) pure virtual
Implemented in VMAP::VMapMgr2.
Referenced by MMAP::TerrainBuilder::loadVMap().
Member Data Documentation
iEnableHeightCalc
bool VMAP::IVMapMgr::iEnableHeightCalc {true} private
Definition at line 73 of file IVMapMgr.h.
Referenced by isHeightCalcEnabled(), isMapLoadingEnabled(), and setEnableHeightCalc().
iEnableLineOfSightCalc
bool VMAP::IVMapMgr::iEnableLineOfSightCalc {true} private
Definition at line 72 of file IVMapMgr.h.
Referenced by isLineOfSightCalcEnabled(), isMapLoadingEnabled(), and setEnableLineOfSightCalc().
The documentation for this class was generated from the following file:
src/common/Collision/Management/IVMapMgr.h