Azerotcore-wotlk: deps/fmt/include/fmt/ranges.h File Reference
ranges.h File Reference
#include <initializer_list>
#include <type_traits>
#include "format.h"
Classes
struct formatting_range< Char, Enable >
struct formatting_tuple< Char, Enable >
class detail::is_std_string_like< T >
Return true value if T has std::string interface, like std::string_view.
struct detail::is_std_string_like< fmt::basic_string_view< Char > >
struct detail::conditional_helper< Ts >
struct detail::is_range_< T, _ >
struct detail::has_member_fn_begin_end_t< T, Enable >
struct detail::has_member_fn_begin_end_t< T, void_t< decltype(std::declval< T >().begin()), decltype(std::declval< T >().end())> >
struct detail::has_const_begin_end< T, Enable >
struct detail::has_mutable_begin_end< T, Enable >
struct detail::has_const_begin_end< T, void_t< decltype(detail::range_begin(std::declval< const remove_cvref_t< T > & >())), decltype(detail::range_begin(std::declval< const remove_cvref_t< T > & >()))> >
struct detail::has_mutable_begin_end< T, void_t< decltype(detail::range_begin(std::declval< T >())), decltype(detail::range_begin(std::declval< T >())), enable_if_t< std::is_copy_constructible< T >::value > > >
struct detail::is_range_< T, void >
struct detail::range_to_view< T, enable_if_t< has_const_begin_end< T >::value > >
struct detail::range_to_view< T, enable_if_t< has_const_begin_end< T >::value > >::view_t
struct detail::range_to_view< T, enable_if_t<!has_const_begin_end< T >::value &&has_mutable_begin_end< T >::value > >
struct detail::range_to_view< T, enable_if_t<!has_const_begin_end< T >::value &&has_mutable_begin_end< T >::value > >::view_t
class detail::is_tuple_like_< T >
tuple_size and tuple_element check.
struct detail::integer_sequence< T, N >
struct detail::make_integer_sequence< T, N, Ns >
struct detail::make_integer_sequence< T, 0, Ns... >
struct is_tuple_like< T >
struct formatter< TupleT, Char, enable_if_t< fmt::is_tuple_like< TupleT >::value > >
struct formatter< TupleT, Char, enable_if_t< fmt::is_tuple_like< TupleT >::value > >::format_each< FormatContext >
struct is_range< T, Char >
struct formatter< T, Char, enable_if_t< fmt::is_range< T, Char >::value &&(has_formatter< detail::value_type< T >, format_context >::value||detail::has_fallback_formatter< detail::value_type< T >, Char >::value) > >
struct tuple_join_view< Char, T >
struct formatter< tuple_join_view< Char, T... >, Char >
Namespaces
detail
Macros
#define FMT_DECLTYPE_RETURN(val)
Typedefs
template<size_t... N>
using detail::index_sequence = integer_sequence< size_t, N... >
template<size_t N>
using detail::make_index_sequence = make_integer_sequence< size_t, N >
template<typename Range >
using detail::value_type = remove_cvref_t< decltype(*detail::range_begin(std::declval< Range >()))>
template<typename Char , typename... T>
using tuple_arg_join = tuple_join_view< Char, T... >
Functions
template<typename RangeT , typename OutputIterator >
OutputIterator detail::copy (const RangeT &range, OutputIterator out)
template<typename OutputIterator >
OutputIterator detail::copy (const char *str, OutputIterator out)
template<typename OutputIterator >
OutputIterator detail::copy (char ch, OutputIterator out)
template<typename OutputIterator >
OutputIterator detail::copy (wchar_t ch, OutputIterator out)
template<typename T , std::size_t N>
auto detail::range_begin (const T(&arr)[N]) -> const T *
template<typename T , std::size_t N>
auto detail::range_end (const T(&arr)[N]) -> const T *
template<typename T >
auto detail::range_begin (T &&rng) FMT_DECLTYPE_RETURN(static_cast< T && >(rng).begin())
template<typename T >
auto detail::range_end (T &&rng) FMT_DECLTYPE_RETURN(static_cast< T && >(rng).end())
template<typename T >
auto detail::range_begin (T &&rng) -> enable_if_t<!has_member_fn_begin_end_t< T && >::value, decltype(begin(static_cast< T && >(rng)))>
template<typename T >
auto detail::range_end (T &&rng) -> enable_if_t<!has_member_fn_begin_end_t< T && >::value, decltype(end(static_cast< T && >(rng)))>
template<class Tuple , class F , size_t... Is>
void detail::for_each (index_sequence< Is... >, Tuple &&tup, F &&f) FMT_NOEXCEPT
template<class T >
FMT_CONSTEXPR make_index_sequence< std::tuple_size< T >::value > detail::get_indexes (T const &)
template<class Tuple , class F >
void detail::for_each (Tuple &&tup, F &&f)
template<typename OutputIt >
OutputIt detail::write_delimiter (OutputIt out)
template<typename Char , typename OutputIt , typename Arg , FMT_ENABLE_IF(is_std_string_like< typename std::decay< Arg >::type >::value) >
OutputIt detail::write_range_entry (OutputIt out, const Arg &v)
template<typename Char , typename OutputIt , typename Arg , FMT_ENABLE_IF(std::is_same< Arg, Char >::value) >
OutputIt detail::write_range_entry (OutputIt out, const Arg v)
template<typename... T>
FMT_MODULE_EXPORT_BEGIN FMT_CONSTEXPR auto join (const std::tuple< T... > &tuple, string_view sep) -> tuple_join_view< char, T... >
template<typename... T>
FMT_CONSTEXPR auto join (const std::tuple< T... > &tuple, basic_string_view< wchar_t > sep) -> tuple_join_view< wchar_t, T... >
template<typename T >
auto join (std::initializer_list< T > list, string_view sep) -> join_view< const T *, const T * >
Macro Definition Documentation
FMT_DECLTYPE_RETURN
#define FMT_DECLTYPE_RETURN (val)
Value:
    ->decltype(val) { return val; } \
    static_assert(                  \
        true, "")
Definition at line 95 of file ranges.h.
Typedef Documentation
tuple_arg_join
template<typename Char , typename... T> using tuple_arg_join = tuple_join_view<Char, T...>
Definition at line 375 of file ranges.h.
Function Documentation
join() [1/3]
template<typename... T> FMT_CONSTEXPR auto join (const std::tuple< T... > & tuple, basic_string_view< wchar_t > sep) -> tuple_join_view<wchar_t, T...>
Definition at line 442 of file ranges.h.
{
   return {tuple, sep};
 }
join() [2/3]
template<typename... T> FMT_MODULE_EXPORT_BEGIN FMT_CONSTEXPR auto join (const std::tuple< T... > & tuple, string_view sep) -> tuple_join_view<char, T...>
\rst Returns an object that formats tuple with elements separated by sep.
Example**::
std::tuple<int, char> t = {1, 'a'}; fmt::print("{}", fmt::join(t, ", ")); Output: "1, a" \endrst
Definition at line 436 of file ranges.h.
{
   return {tuple, sep};
 }
Referenced by join().
join() [3/3]
template<typename T > auto join (std::initializer_list< T > list, string_view sep) -> join_view<const T*, const T*>
\rst Returns an object that formats initializer_list with elements separated by sep.
Example**::
fmt::print("{}", fmt::join({1, 2, 3}, ", ")); Output: "1, 2, 3" \endrst
Definition at line 460 of file ranges.h.
{
   return join(std::begin(list), std::end(list), sep);
 }
References join(), and list().