Azerotcore-wotlk: npc_elder_kuruti Class Reference
npc_elder_kuruti Class Reference
Public Member Functions
npc_elder_kuruti ()
bool OnGossipHello (Player *player, Creature *creature) override
bool OnGossipSelect (Player *player, Creature *creature, uint32, uint32 action) override
Public Member Functions inherited from CreatureScript
bool IsDatabaseBound () const override
virtual bool OnGossipSelectCode (Player *, Creature *, uint32, uint32, const char *)
virtual bool OnQuestAccept (Player *, Creature *, Quest const *)
virtual bool OnQuestSelect (Player *, Creature *, Quest const *)
virtual bool OnQuestComplete (Player *, Creature *, Quest const *)
virtual bool OnQuestReward (Player *, Creature *, Quest const *, uint32)
virtual uint32 GetDialogStatus (Player *, Creature *)
virtual CreatureAI * GetAI (Creature *) const
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Public Member Functions inherited from UpdatableScript< Creature >
virtual void OnUpdate (Creature *, uint32)
Additional Inherited Members
Protected Member Functions inherited from CreatureScript
CreatureScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Protected Member Functions inherited from UpdatableScript< Creature >
UpdatableScript ()=default
Detailed Description
Definition at line 331 of file zone_zangarmarsh.cpp.
Constructor & Destructor Documentation
npc_elder_kuruti()
npc_elder_kuruti::npc_elder_kuruti () inline
Definition at line 334 of file zone_zangarmarsh.cpp.
 : CreatureScript("npc_elder_kuruti") { }
Member Function Documentation
OnGossipHello()
bool npc_elder_kuruti::OnGossipHello (Player * player, Creature * creature) inline override virtual
Reimplemented from CreatureScript.
Definition at line 336 of file zone_zangarmarsh.cpp.
     {
         if (player->GetQuestStatus(9803) == QUEST_STATUS_INCOMPLETE)
             AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ITEM_KUR1, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF);
         SendGossipMenuFor(player, 9226, creature->GetGUID());
         return true;
     }
References AddGossipItemFor(), Object::GetGUID(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_KUR1, GOSSIP_SENDER_MAIN, QUEST_STATUS_INCOMPLETE, and SendGossipMenuFor().
OnGossipSelect()
bool npc_elder_kuruti::OnGossipSelect (Player * player, Creature * creature, uint32 , uint32 action) inline override virtual
Reimplemented from CreatureScript.
Definition at line 346 of file zone_zangarmarsh.cpp.
     {
         ClearGossipMenuFor(player);
         switch (action)
         {
             case GOSSIP_ACTION_INFO_DEF:
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ITEM_KUR2, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 1);
                 SendGossipMenuFor(player, 9227, creature->GetGUID());
                 break;
             case GOSSIP_ACTION_INFO_DEF + 1:
                 AddGossipItemFor(player, GOSSIP_ICON_CHAT, GOSSIP_ITEM_KUR3, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF + 2);
                 SendGossipMenuFor(player, 9229, creature->GetGUID());
                 break;
             case GOSSIP_ACTION_INFO_DEF + 2:
                 {
                     if (!player->HasItemCount(24573))
                     {
                         ItemPosCountVec dest;
                         uint32 itemId = 24573;
                         InventoryResult msg = player->CanStoreNewItem(NULL_BAG, NULL_SLOT, dest, itemId, 1, nullptr);
                         if (msg == EQUIP_ERR_OK)
{
                             player->StoreNewItem(dest, itemId, true);
                         }
                         else
                             player->SendEquipError(msg, nullptr, nullptr, itemId);
                     }
                     SendGossipMenuFor(player, 9231, creature->GetGUID());
                     break;
                 }
         }
         return true;
     }
References AddGossipItemFor(), Player::CanStoreNewItem(), ClearGossipMenuFor(), EQUIP_ERR_OK, Object::GetGUID(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_KUR2, GOSSIP_ITEM_KUR3, GOSSIP_SENDER_MAIN, Player::HasItemCount(), NULL_BAG, NULL_SLOT, Player::SendEquipError(), SendGossipMenuFor(), and Player::StoreNewItem().
The documentation for this class was generated from the following file:
src/server/scripts/Outland/zone_zangarmarsh.cpp