Azerotcore-wotlk: PreparedStatementBase Class Reference
PreparedStatementBase Class Reference
#include <PreparedStatement.h>
Public Member Functions
PreparedStatementBase (uint32 index, uint8 capacity)
virtual ~PreparedStatementBase ()
void setNull (const uint8 index)
void setBool (const uint8 index, const bool value)
void setUInt8 (const uint8 index, const uint8 value)
void setUInt16 (const uint8 index, const uint16 value)
void setUInt32 (const uint8 index, const uint32 value)
void setUInt64 (const uint8 index, const uint64 value)
void setInt8 (const uint8 index, const int8 value)
void setInt16 (const uint8 index, const int16 value)
void setInt32 (const uint8 index, const int32 value)
void setInt64 (const uint8 index, const int64 value)
void setFloat (const uint8 index, const float value)
void setDouble (const uint8 index, const double value)
void setString (const uint8 index, const std::string &value)
void setStringView (const uint8 index, const std::string_view value)
void setBinary (const uint8 index, const std::vector< uint8 > &value)
template<size_t Size>
void setBinary (const uint8 index, std::array< uint8, Size > const &value)
uint32 GetIndex () const
std::vector< PreparedStatementData > const & GetParameters () const
Protected Member Functions
PreparedStatementBase (PreparedStatementBase const &right)=delete
PreparedStatementBase & operator= (PreparedStatementBase const &right)=delete
Protected Attributes
uint32 m_index
std::vector< PreparedStatementData > statement_data
Friends
class PreparedStatementTask
Detailed Description
Definition at line 58 of file PreparedStatement.h.
Constructor & Destructor Documentation
PreparedStatementBase() [1/2]
PreparedStatementBase::PreparedStatementBase (uint32 index, uint8 capacity) explicit
Definition at line 26 of file PreparedStatement.cpp.
                                                                          :
 m_index(index), statement_data(capacity) { }
~PreparedStatementBase()
PreparedStatementBase::~PreparedStatementBase () virtual
Definition at line 29 of file PreparedStatement.cpp.
 { }
PreparedStatementBase() [2/2]
PreparedStatementBase::PreparedStatementBase (PreparedStatementBase const & right) protected delete
Member Function Documentation
GetIndex()
uint32 PreparedStatementBase::GetIndex () const inline
Definition at line 88 of file PreparedStatement.h.
 { return m_index; }
Referenced by MySQLConnection::_Query(), MySQLPreparedStatement::AssertValidIndex(), MySQLPreparedStatement::BindParameters(), and MySQLConnection::Execute().
GetParameters()
std::vector<PreparedStatementData> const& PreparedStatementBase::GetParameters () const inline
Definition at line 89 of file PreparedStatement.h.
 { return statement_data; }
Referenced by MySQLPreparedStatement::BindParameters(), and MySQLPreparedStatement::getQueryString().
operator=()
PreparedStatementBase& PreparedStatementBase::operator= (PreparedStatementBase const & right) protected delete
setBinary() [1/2]
void PreparedStatementBase::setBinary (const uint8 index, const std::vector< uint8 > & value)
Definition at line 110 of file PreparedStatement.cpp.
 {
     ASSERT(index < statement_data.size());
     statement_data[index].data = value;
 }
References ASSERT, and statement_data.
Referenced by AccountMgr::ChangePassword(), AccountMgr::ChangeUsername(), AccountMgr::CreateAccount(), and AuthSession::HandleLogonProof().
setBinary() [2/2]
template<size_t Size> void PreparedStatementBase::setBinary (const uint8 index, std::array< uint8, Size > const & value) inline
Definition at line 82 of file PreparedStatement.h.
     {
         std::vector<uint8> vec(value.begin(), value.end());
         setBinary(index, vec);
     }
setBool()
void PreparedStatementBase::setBool (const uint8 index, const bool value)
Definition at line 32 of file PreparedStatement.cpp.
 {
     ASSERT(index < statement_data.size());
     statement_data[index].data = value;
 }
References ASSERT, and statement_data.
Referenced by Player::_SaveQuestStatus(), LootItemStorage::AddNewStoredLoot(), Battleground::EndBattleground(), account_commandscript::HandleAccountLockIpCommand(), InstanceSaveMgr::PlayerBindToInstance(), GmTicket::SaveToDB(), MailDraft::SendMailTo(), and Channel::UpdateChannelInDB().
setDouble()
void PreparedStatementBase::setDouble (const uint8 index, const double value)
Definition at line 92 of file PreparedStatement.cpp.
 {
     ASSERT(index < statement_data.size());
     statement_data[index].data = value;
 }
References ASSERT, and statement_data.
setFloat()
void PreparedStatementBase::setFloat (const uint8 index, const float value)
Definition at line 86 of file PreparedStatement.cpp.
 {
     ASSERT(index < statement_data.size());
     statement_data[index].data = value;
 }
References ASSERT, and statement_data.
Referenced by Player::_LoadHomeBind(), Player::_SaveCharacter(), Player::_SaveEntryPoint(), Player::_SaveStats(), ObjectMgr::AddGameTele(), WorldSession::HandleCharFactionOrRaceChangeCallback(), gobject_commandscript::HandleGameObjectNearCommand(), npc_commandscript::HandleNpcAddFormationCommand(), npc_commandscript::HandleNpcMoveCommand(), npc_commandscript::HandleNpcNearCommand(), npc_commandscript::HandleNpcSetWanderDistanceCommand(), GameEventMgr::HandleQuestComplete(), WorldSession::HandleReportLag(), wp_commandscript::HandleWpAddCommand(), wp_commandscript::HandleWpEventCommand(), wp_commandscript::HandleWpModifyCommand(), Player::SavePositionInDB(), Corpse::SaveToDB(), GmTicket::SaveToDB(), Creature::SaveToDB(), GameObject::SaveToDB(), and Player::SetHomebind().
setInt16()
void PreparedStatementBase::setInt16 (const uint8 index, const int16 value)
Definition at line 68 of file PreparedStatement.cpp.
 {
     ASSERT(index < statement_data.size());
     statement_data[index].data = value;
 }
References ASSERT, and statement_data.
Referenced by Battleground::EndBattleground(), and Item::SaveToDB().
setInt32()
void PreparedStatementBase::setInt32 (const uint8 index, const int32 value)
Definition at line 74 of file PreparedStatement.cpp.
 {
     ASSERT(index < statement_data.size());
     statement_data[index].data = value;
 }
References ASSERT, and statement_data.
Referenced by Pet::_SaveAuras(), Player::_SaveAuras(), Player::_SaveCharacter(), LootItemStorage::AddNewStoredLoot(), AccountMgr::GetSecurity(), account_commandscript::HandleAccountSetGmLevelCommand(), WorldSocket::HandleAuthSession(), WorldSession::HandleCharFactionOrRaceChangeCallback(), gm_commandscript::HandleGMListFullCommand(), misc_commandscript::HandleMuteCommand(), misc_commandscript::HandlePInfoCommand(), wp_commandscript::HandleWpShowCommand(), World::LoadDBAllowedSecurityLevel(), ReputationMgr::SaveToDB(), GmTicket::SaveToDB(), Creature::SaveToDB(), GameObject::SaveToDB(), MailDraft::SendMailTo(), and CalendarMgr::UpdateEvent().
setInt64()
void PreparedStatementBase::setInt64 (const uint8 index, const int64 value)
Definition at line 80 of file PreparedStatement.cpp.
 {
     ASSERT(index < statement_data.size());
     statement_data[index].data = value;
 }
References ASSERT, and statement_data.
Referenced by WorldSocket::HandleAuthSessionCallback(), misc_commandscript::HandleMuteCommand(), misc_commandscript::HandleUnmuteCommand(), and Player::Update().
setInt8()
void PreparedStatementBase::setInt8 (const uint8 index, const int8 value)
Definition at line 62 of file PreparedStatement.cpp.
 {
     ASSERT(index < statement_data.size());
     statement_data[index].data = value;
 }
References ASSERT, and statement_data.
Referenced by AccountMgr::CreateAccount(), and MailDraft::SendMailTo().
setNull()
void PreparedStatementBase::setNull (const uint8 index)
Definition at line 116 of file PreparedStatement.cpp.
 {
     ASSERT(index < statement_data.size());
     statement_data[index].data = nullptr;
 }
References ASSERT, and statement_data.
setString()
void PreparedStatementBase::setString (const uint8 index, const std::string & value)
Definition at line 98 of file PreparedStatement.cpp.
 {
     ASSERT(index < statement_data.size());
     statement_data[index].data = value;
 }
References ASSERT, and statement_data.
Referenced by Player::_SaveCharacter(), Player::_SaveEntryPoint(), Player::_SaveEquipmentSets(), AppenderDB::_write(), AccountActionIpLogger::AccountIPLogAction(), ObjectMgr::AddGameTele(), ObjectMgr::AddReservedPlayerName(), BanMgr::BanAccount(), BanMgr::BanAccountByPlayerName(), BanMgr::BanCharacter(), BanMgr::BanIP(), AccountMgr::ChangeUsername(), Channel::Channel(), CharacterActionIpLogger::CharacterIPLogAction(), ArenaTeam::Create(), Guild::Create(), AccountMgr::CreateAccount(), ObjectMgr::DeleteGameTele(), CharacterDeleteActionIpLogger::DeleteIPLogAction(), Battleground::EndBattleground(), character_commandscript::GetDeletedCharacterInfoList(), World::GetGlobalPlayerGUID(), AccountMgr::GetId(), disable_commandscript::HandleAddDisables(), misc_commandscript::HandleAddItemCommand(), WorldSocket::HandleAuthSession(), WorldSocket::HandleAuthSessionCallback(), ban_commandscript::HandleBanListAccountCommand(), ban_commandscript::HandleBanListCharacterCommand(), ban_commandscript::HandleBanListIPCommand(), WorldSession::HandleBugOpcode(), character_commandscript::HandleCharacterRenameCommand(), WorldSession::HandleCharCreateOpcode(), WorldSession::HandleCharCustomizeCallback(), WorldSession::HandleCharFactionOrRaceChangeCallback(), WorldSession::HandleCharRenameCallBack(), WorldSession::HandleCharRenameOpcode(), WorldSession::HandleGMSurveySubmit(), AuthSession::HandleLogonProof(), lookup_commandscript::HandleLookupPlayerAccountCommand(), lookup_commandscript::HandleLookupPlayerEmailCommand(), misc_commandscript::HandleMuteCommand(), WorldSession::HandlePetitionBuyOpcode(), WorldSession::HandlePetitionRenameOpcode(), WorldSession::HandlePetRename(), Guild::HandleSetInfo(), Guild::HandleSetMOTD(), WorldSession::HandleSetPlayerDeclinedNames(), misc_commandscript::HandleUnmuteCommand(), wp_commandscript::HandleWpModifyCommand(), InstanceSave::InsertToDB(), ChannelMgr::LoadChannels(), PlayerDumpReader::LoadDump(), BanMgr::RemoveBanIP(), AddonMgr::SaveAddon(), Pet::SavePetToDB(), Corpse::SaveToDB(), InstanceScript::SaveToDB(), Item::SaveToDB(), Guild::Member::SaveToDB(), Guild::RankInfo::SaveToDB(), GmTicket::SaveToDB(), MailDraft::SendMailTo(), WorldSession::SetAccountData(), PlayerSocial::SetFriendNote(), Guild::BankTab::SetInfo(), ArenaTeam::SetName(), Guild::RankInfo::SetName(), Guild::Member::SetOfficerNote(), Guild::Member::SetPublicNote(), Guild::BankTab::SetText(), AuthSession::Start(), WorldSocket::Start(), Player::StoreNewItem(), Player::Update(), Channel::UpdateChannelInDB(), CalendarMgr::UpdateEvent(), and CalendarMgr::UpdateInvite().
setStringView()
void PreparedStatementBase::setStringView (const uint8 index, const std::string_view value)
Definition at line 104 of file PreparedStatement.cpp.
 {
     ASSERT(index < statement_data.size());
     statement_data[index].data.emplace<std::string>(value);
 }
References ASSERT, and statement_data.
Referenced by lookup_commandscript::HandleLookupPlayerIpCommand().
setUInt16()
void PreparedStatementBase::setUInt16 (const uint8 index, const uint16 value)
Definition at line 44 of file PreparedStatement.cpp.
 {
     ASSERT(index < statement_data.size());
     statement_data[index].data = value;
 }
References ASSERT, and statement_data.
Referenced by Player::_LoadHomeBind(), Player::_LoadSkills(), InstanceSaveMgr::_ResetOrWarnAll(), Player::_SaveCharacter(), Player::_SaveGlyphs(), Player::_SaveQuestStatus(), Player::_SaveSkills(), Pet::_SaveSpellCooldowns(), ObjectMgr::AddGameTele(), Graveyard::AddGraveyardLink(), ArenaTeam::Create(), OPvPCapturePoint::DelCreature(), Map::DeleteRespawnTimesInDB(), Battleground::EndBattleground(), Player::GetZoneIdFromDB(), disable_commandscript::HandleAddDisables(), character_commandscript::HandleCharacterChangeFactionCommand(), character_commandscript::HandleCharacterChangeRaceCommand(), character_commandscript::HandleCharacterCustomizeCommand(), character_commandscript::HandleCharacterRenameCommand(), WorldSession::HandleCharCustomizeCallback(), WorldSession::HandleCharFactionOrRaceChangeCallback(), WorldSession::HandleCharRenameCallBack(), misc_commandscript::HandleMuteInfoHelper(), npc_commandscript::HandleNpcSetFactionIdCommand(), WorldSession::HandleReportLag(), reset_commandscript::HandleResetAllCommand(), reset_commandscript::HandleResetSpellsCommand(), reset_commandscript::HandleResetTalentsCommand(), InstanceSave::InsertToDB(), AchievementGlobalMgr::LoadCompletedAchievements(), Player::LoadFromDB(), AchievementMgr::LoadFromDB(), Map::LoadRespawnTimes(), Player::OfflineResurrect(), Player::RemoveAtLoginFlag(), Map::RemoveCreatureRespawnTime(), Map::RemoveGORespawnTime(), Graveyard::RemoveGraveyardLink(), World::ResetEventSeasonalQuests(), Map::SaveCreatureRespawnTime(), Map::SaveGORespawnTime(), Player::SavePositionInDB(), Item::SaveRefundDataToDB(), ArenaTeam::SaveToDB(), Corpse::SaveToDB(), AchievementMgr::SaveToDB(), Item::SaveToDB(), ReputationMgr::SaveToDB(), GmTicket::SaveToDB(), Guild::BankEventLogEntry::SaveToDB(), Creature::SaveToDB(), GameObject::SaveToDB(), MailDraft::SendMailTo(), Player::SetHomebind(), and World::Update().
setUInt32()
void PreparedStatementBase::setUInt32 (const uint8 index, const uint32 value)
Definition at line 50 of file PreparedStatement.cpp.
 {
     ASSERT(index < statement_data.size());
     statement_data[index].data = value;
 }
References ASSERT, and statement_data.
Referenced by Guild::_CreateDefaultGuildRanks(), Guild::_CreateNewBankTab(), Guild::_DeleteMemberFromDB(), Player::_LoadBrewOfTheMonth(), Player::_LoadHomeBind(), Player::_LoadItem(), Player::_LoadMail(), Player::_LoadMailedItem(), Player::_LoadSkills(), Guild::_ModifyBankMoney(), InstanceSaveMgr::_ResetOrWarnAll(), InstanceSaveMgr::_ResetSave(), Player::_SaveActions(), Pet::_SaveAuras(), Player::_SaveAuras(), Player::_SaveCharacter(), Player::_SaveDailyQuestStatus(), Player::_SaveEntryPoint(), Player::_SaveEquipmentSets(), Player::_SaveGlyphs(), Player::_SaveInstanceTimeRestrictions(), Player::_SaveInventory(), Player::_SaveMail(), Player::_SaveMonthlyQuestStatus(), Player::_SaveQuestStatus(), Player::_SaveSeasonalQuestStatus(), Player::_SaveSkills(), Pet::_SaveSpellCooldowns(), Player::_SaveSpellCooldowns(), Pet::_SaveSpells(), Player::_SaveSpells(), Player::_SaveStats(), Player::_SaveTalents(), lfg::LFGMgr::_SaveToDB(), Player::_SaveWeeklyQuestStatus(), Guild::_SetLeaderGUID(), World::_UpdateRealmCharCount(), AppenderDB::_write(), AccountActionIpLogger::AccountIPLogAction(), Player::ActivateSpec(), Channel::AddChannelBanToDB(), ObjectMgr::AddGameTele(), Graveyard::AddGraveyardLink(), Guild::AddMember(), ArenaTeam::AddMember(), Group::AddMember(), LootItemStorage::AddNewStoredLoot(), Pet::addSpell(), PlayerSocial::AddToSocialList(), ObjectMgr::AddVendorItem(), BanMgr::BanAccount(), BanMgr::BanAccountByPlayerName(), BanMgr::BanCharacter(), BanMgr::BanIP(), Group::ChangeLeader(), Group::ChangeMembersGroup(), AccountMgr::ChangePassword(), Guild::Member::ChangeRank(), AccountMgr::ChangeUsername(), Channel::Channel(), CharacterActionIpLogger::CharacterIPLogAction(), AccountMgr::CheckPassword(), Channel::CleanOldChannelsInDB(), Item::ClearSoulboundTradeable(), Group::ConvertToLFG(), Group::ConvertToRaid(), ArenaTeam::Create(), Group::Create(), Guild::Create(), Guild::RankInfo::CreateMissingTabsIfNeeded(), Player::Customize(), OPvPCapturePoint::DelCreature(), AccountMgr::DeleteAccount(), Map::DeleteCorpseData(), Creature::DeleteFromDB(), GameObject::DeleteFromDB(), GmTicket::DeleteFromDB(), AuctionEntry::DeleteFromDB(), Item::DeleteFromDB(), Corpse::DeleteFromDB(), Pet::DeleteFromDB(), AchievementMgr::DeleteFromDB(), Player::DeleteFromDB(), Item::DeleteFromInventoryDB(), MailDraft::deleteIncludedItems(), InstanceSaveMgr::DeleteInstanceSaveIfNeeded(), CharacterDeleteActionIpLogger::DeleteIPLogAction(), Player::DeleteOldCharacters(), Item::DeleteRefundDataFromDB(), Map::DeleteRespawnTimesInDB(), DeleteSpellFromAllPlayers(), ArenaTeam::DelMember(), Player::DestroyItem(), Guild::Disband(), Group::Disband(), ArenaTeam::Disband(), ArenaTeamMgr::DistributeArenaPoints(), Battleground::EndBattleground(), BGQueueRemoveEvent::Execute(), Player::GetArenaTeamIdFromDB(), AccountMgr::GetCharactersCount(), character_commandscript::GetDeletedCharacterInfoList(), World::GetGlobalPlayerData(), AccountMgr::GetName(), AccountMgr::GetSecurity(), Player::GetZoneIdFromDB(), account_commandscript::HandleAccountAddonCommand(), account_commandscript::HandleAccountLockIpCommand(), account_commandscript::HandleAccountOnlineListCommand(), account_commandscript::HandleAccountSetAddonCommand(), account_commandscript::HandleAccountSetGmLevelCommand(), disable_commandscript::HandleAddDisables(), WorldSession::HandleAuctionPlaceBid(), WorldSocket::HandleAuthSessionCallback(), ban_commandscript::HandleBanInfoCharacterCommand(), ban_commandscript::HandleBanListCharacterCommand(), WorldSession::HandleBattleFieldPortOpcode(), WorldSession::HandleBuybackItem(), character_commandscript::HandleCharacterChangeFactionCommand(), character_commandscript::HandleCharacterChangeRaceCommand(), character_commandscript::HandleCharacterCustomizeCommand(), character_commandscript::HandleCharacterRenameCommand(), WorldSession::HandleCharCreateOpcode(), WorldSession::HandleCharCustomize(), WorldSession::HandleCharCustomizeCallback(), WorldSession::HandleCharEnumOpcode(), WorldSession::HandleCharFactionOrRaceChange(), WorldSession::HandleCharFactionOrRaceChangeCallback(), WorldSession::HandleCharRenameCallBack(), WorldSession::HandleCharRenameOpcode(), gobject_commandscript::HandleGameObjectNearCommand(), misc_commandscript::HandleGearStatsCommand(), WorldSession::HandleGMSurveySubmit(), list_commandscript::HandleListItemCommand(), WorldSession::HandleLoadPetFromDBFirstCallback(), AuthSession::HandleLogonProof(), WorldSession::HandleMailReturnToSender(), misc_commandscript::HandleMuteCommand(), npc_commandscript::HandleNpcAddFormationCommand(), npc_commandscript::HandleNpcAddMoveCommand(), npc_commandscript::HandleNpcMoveCommand(), npc_commandscript::HandleNpcNearCommand(), npc_commandscript::HandleNpcSetFactionIdCommand(), npc_commandscript::HandleNpcSetFlagCommand(), npc_commandscript::HandleNpcSetSpawnTimeCommand(), npc_commandscript::HandleNpcSetWanderDistanceCommand(), WorldSession::HandleOpenItemOpcode(), WorldSession::HandleOpenWrappedItemCallback(), WorldSession::HandlePetitionBuyOpcode(), WorldSession::HandlePetitionRenameOpcode(), WorldSession::HandlePetitionSignOpcode(), WorldSession::HandlePetRename(), misc_commandscript::HandlePInfoCommand(), WorldSession::HandlePlayerLoginFromDB(), GameEventMgr::HandleQuestComplete(), AuthSession::HandleRealmList(), reload_commandscript::HandleReloadCreatureTemplateCommand(), disable_commandscript::HandleRemoveDisables(), Guild::HandleRemoveRank(), WorldSession::HandleReportLag(), reset_commandscript::HandleResetSpellsCommand(), reset_commandscript::HandleResetTalentsCommand(), Guild::HandleSetInfo(), Guild::HandleSetMOTD(), WorldSession::HandleSetPlayerDeclinedNames(), WorldSession::HandleSetSavedInstanceExtend(), WorldSession::HandleStablePet(), WorldSession::HandleStablePetCallback(), WorldSession::HandleStableSwapPet(), WorldSession::HandleStableSwapPetCallback(), tele_commandscript::HandleTeleNameCommand(), WorldSession::HandleTurnInPetitionOpcode(), misc_commandscript::HandleUnFreezeCommand(), misc_commandscript::HandleUnmuteCommand(), WorldSession::HandleUnstablePet(), WorldSession::HandleUnstablePetCallback(), WorldSession::HandleWhoisOpcode(), wp_commandscript::HandleWpAddCommand(), wp_commandscript::HandleWpEventCommand(), wp_commandscript::HandleWpLoadCommand(), wp_commandscript::HandleWpModifyCommand(), wp_commandscript::HandleWpShowCommand(), wp_commandscript::HandleWpUnLoadCommand(), WorldSession::HandleWrapItemOpcode(), LoginQueryHolder::Initialize(), LoadPetFromDBQueryHolder::Initialize(), InstanceSave::InsertToDB(), Player::IsPetDismissed(), Player::LeaveAllArenaTeams(), Player::LeaveBattleground(), ChannelMgr::LoadChannels(), InstanceSaveMgr::LoadCharacterBinds(), Map::LoadCorpseData(), ObjectMgr::LoadCreatures(), PlayerDumpReader::LoadDump(), Player::LoadFromDB(), Item::LoadFromDB(), ObjectMgr::LoadGameobjects(), WorldSession::LoadGlobalAccountData(), Group::LoadGroupFromDB(), Guild::BankTab::LoadItemFromDB(), Group::LoadMemberFromDB(), Pet::LoadPetFromDB(), Player::LoadPositionFromDB(), ObjectMgr::LoadReferenceVendor(), Map::LoadRespawnTimes(), WorldSession::LoadTutorialsData(), WorldSession::LogoutPlayer(), lookup_commandscript::LookupPlayerSearchCommand(), Player::ModifyArenaPoints(), Player::ModifyHonorPoints(), InstanceSaveMgr::PlayerBindToInstance(), InstanceSaveMgr::PlayerUnbindInstance(), WorldSession::recoveryItem(), WaypointMgr::ReloadPath(), Player::RemoveAtLoginFlag(), BanMgr::RemoveBanAccount(), BanMgr::RemoveBanAccountByPlayerName(), BanMgr::RemoveBanCharacter(), Channel::RemoveChannelBanFromDB(), Map::RemoveCreatureRespawnTime(), LootItemStorage::RemoveEntryFromDB(), PlayerSocial::RemoveFromSocialList(), Map::RemoveGORespawnTime(), Graveyard::RemoveGraveyardLink(), Group::RemoveMember(), Player::RemovePetitionsAndSigns(), LootItemStorage::RemoveStoredLoot(), ObjectMgr::RemoveVendorItem(), Pet::resetTalentsForAllPetsOf(), ObjectMgr::ReturnOrDeleteOldMails(), AddonMgr::SaveAddon(), Map::SaveCreatureRespawnTime(), Player::SaveGoldToDB(), Map::SaveGORespawnTime(), Pet::SavePetToDB(), Player::SavePositionInDB(), PoolMgr::SaveQuestsToDB(), Item::SaveRefundDataToDB(), ArenaTeam::SaveToDB(), Corpse::SaveToDB(), InstanceScript::SaveToDB(), AchievementMgr::SaveToDB(), Item::SaveToDB(), ReputationMgr::SaveToDB(), AuctionEntry::SaveToDB(), Guild::Member::SaveToDB(), Guild::RankInfo::SaveToDB(), GmTicket::SaveToDB(), Guild::EventLogEntry::SaveToDB(), Guild::BankEventLogEntry::SaveToDB(), EmblemInfo::SaveToDB(), Creature::SaveToDB(), GameObject::SaveToDB(), WorldSession::SaveTutorialsData(), GameEventMgr::SaveWorldEventStateToDB(), AuctionHouseMgr::SendAuctionWonMail(), MailDraft::SendMailTo(), MailDraft::SendReturnToSender(), WorldSession::SendStablePet(), WorldSession::SendStablePetCallback(), WorldSession::SetAccountData(), Guild::RankInfo::SetBankMoneyPerDay(), Guild::RankInfo::SetBankTabSlotsAndRights(), ArenaTeam::SetCaptain(), InstanceScript::SetCompletedEncountersMask(), ObjectMgr::SetCreatureLinkedRespawn(), Group::SetDungeonDifficulty(), PlayerSocial::SetFriendNote(), Group::SetGroupMemberFlag(), Player::SetHomebind(), Guild::BankTab::SetInfo(), Guild::BankTab::SetItem(), ArenaTeam::SetName(), Guild::RankInfo::SetName(), Guild::Member::SetOfficerNote(), Guild::Member::SetPublicNote(), Group::SetRaidDifficulty(), Player::SetRandomWinner(), Guild::RankInfo::SetRights(), Guild::BankTab::SetText(), World::setWorldState(), Player::SpawnCorpseBones(), PoolGroup< T >::SpawnObject(), Player::StoreNewItem(), Pet::TryLoadFromDB(), World::Update(), Player::Update(), Guild::Member::UpdateBankWithdrawValue(), Channel::UpdateChannelInDB(), Channel::UpdateChannelUseageInDB(), CalendarMgr::UpdateEvent(), CalendarMgr::UpdateInvite(), Player::UpdateNextMailTimeAndUnreads(), World::UpdateRealmCharCount(), and Player::UpdateSpecCount().
setUInt64()
void PreparedStatementBase::setUInt64 (const uint8 index, const uint64 value)
Definition at line 56 of file PreparedStatement.cpp.
 {
     ASSERT(index < statement_data.size());
     statement_data[index].data = value;
 }
References ASSERT, and statement_data.
Referenced by Guild::_ModifyBankMoney(), Pet::_SaveAuras(), Player::_SaveAuras(), Player::_SaveCharacter(), Player::_SaveDailyQuestStatus(), Player::_SaveEquipmentSets(), Player::_SaveInstanceTimeRestrictions(), AppenderDB::_write(), Group::Create(), Guild::Create(), Battleground::EndBattleground(), LoginQueryHolder::Initialize(), Player::OfflineResurrect(), CalendarMgr::RemoveEvent(), CalendarMgr::RemoveInvite(), Guild::EventLogEntry::SaveToDB(), Guild::BankEventLogEntry::SaveToDB(), CalendarMgr::UpdateEvent(), and CalendarMgr::UpdateInvite().
setUInt8()
void PreparedStatementBase::setUInt8 (const uint8 index, const uint8 value)
Definition at line 38 of file PreparedStatement.cpp.
 {
     ASSERT(index < statement_data.size());
     statement_data[index].data = value;
 }
References ASSERT, and statement_data.
Referenced by Guild::_CreateNewBankTab(), InstanceSaveMgr::_ResetOrWarnAll(), Player::_SaveActions(), Pet::_SaveAuras(), Player::_SaveAuras(), Player::_SaveCharacter(), Player::_SaveGlyphs(), Player::_SaveInventory(), Player::_SaveMail(), Player::_SaveQuestStatus(), Pet::_SaveSpells(), Player::_SaveSpells(), Player::_SaveTalents(), World::_UpdateRealmCharCount(), AppenderDB::_write(), AccountActionIpLogger::AccountIPLogAction(), Player::ActivateSpec(), ArenaTeam::AddMember(), Group::AddMember(), PlayerSocial::AddToSocialList(), ObjectMgr::AddVendorItem(), Group::ChangeMembersGroup(), Guild::Member::ChangeRank(), Channel::Channel(), CharacterActionIpLogger::CharacterIPLogAction(), Group::ConvertToLFG(), Group::ConvertToRaid(), ArenaTeam::Create(), Group::Create(), Guild::RankInfo::CreateMissingTabsIfNeeded(), Player::Customize(), CharacterDeleteActionIpLogger::DeleteIPLogAction(), Battleground::EndBattleground(), BGQueueRemoveEvent::Execute(), Player::GetArenaTeamIdFromDB(), account_commandscript::HandleAccountAddonCommand(), account_commandscript::HandleAccountSetAddonCommand(), account_commandscript::HandleAccountSetGmLevelCommand(), disable_commandscript::HandleAddDisables(), WorldSession::HandleBattleFieldPortOpcode(), WorldSession::HandleCharEnumOpcode(), WorldSession::HandleCharFactionOrRaceChangeCallback(), gm_commandscript::HandleGMListFullCommand(), WorldSession::HandleLoadPetFromDBFirstCallback(), npc_commandscript::HandleNpcAddMoveCommand(), npc_commandscript::HandleNpcSetWanderDistanceCommand(), WorldSession::HandlePetitionBuyOpcode(), misc_commandscript::HandlePInfoCommand(), GameEventMgr::HandleQuestComplete(), disable_commandscript::HandleRemoveDisables(), Guild::HandleRemoveRank(), WorldSession::HandleReportLag(), WorldSession::HandleSetSavedInstanceExtend(), WorldSession::HandleStablePet(), WorldSession::HandleStablePetCallback(), WorldSession::HandleStableSwapPetCallback(), WorldSession::HandleUnstablePet(), WorldSession::HandleUnstablePetCallback(), wp_commandscript::HandleWpLoadCommand(), wp_commandscript::HandleWpUnLoadCommand(), InstanceSave::InsertToDB(), Player::IsPetDismissed(), Player::LeaveBattleground(), Guild::BankTab::LoadItemFromDB(), Pet::LoadPetFromDB(), WorldSession::LogoutPlayer(), PlayerSocial::RemoveFromSocialList(), Player::RemovePetitionsAndSigns(), ObjectMgr::ReturnOrDeleteOldMails(), Pet::SavePetToDB(), ArenaTeam::SaveToDB(), Corpse::SaveToDB(), AuctionEntry::SaveToDB(), Guild::Member::SaveToDB(), Guild::RankInfo::SaveToDB(), GmTicket::SaveToDB(), Guild::EventLogEntry::SaveToDB(), Guild::BankEventLogEntry::SaveToDB(), Creature::SaveToDB(), GameObject::SaveToDB(), GameEventMgr::SaveWorldEventStateToDB(), MailDraft::SendMailTo(), WorldSession::SendStablePet(), WorldSession::SendStablePetCallback(), WorldSession::SetAccountData(), Guild::RankInfo::SetBankMoneyPerDay(), Guild::RankInfo::SetBankTabSlotsAndRights(), Group::SetDungeonDifficulty(), Group::SetGroupMemberFlag(), Guild::BankTab::SetInfo(), Guild::BankTab::SetItem(), Guild::RankInfo::SetName(), Group::SetRaidDifficulty(), Guild::RankInfo::SetRights(), Guild::BankTab::SetText(), GameEventMgr::StopEvent(), Pet::TryLoadFromDB(), CalendarMgr::UpdateEvent(), CalendarMgr::UpdateInvite(), and Player::UpdateSpecCount().
Friends And Related Function Documentation
PreparedStatementTask
friend class PreparedStatementTask friend
Definition at line 60 of file PreparedStatement.h.
Member Data Documentation
m_index
uint32 PreparedStatementBase::m_index protected
Definition at line 92 of file PreparedStatement.h.
statement_data
std::vector<PreparedStatementData> PreparedStatementBase::statement_data protected
Definition at line 95 of file PreparedStatement.h.
Referenced by setBinary(), setBool(), setDouble(), setFloat(), setInt16(), setInt32(), setInt64(), setInt8(), setNull(), setString(), setStringView(), setUInt16(), setUInt32(), setUInt64(), and setUInt8().
The documentation for this class was generated from the following files:
src/server/database/Database/PreparedStatement.h
src/server/database/Database/PreparedStatement.cpp