Azerotcore-wotlk: UnitActionBarEntry Struct Reference
UnitActionBarEntry Struct Reference
#include <Unit.h>
Public Member Functions
UnitActionBarEntry ()
ActiveStates GetType () const
uint32 GetAction () const
bool IsActionBarForSpell () const
void SetActionAndType (uint32 action, ActiveStates type)
void SetType (ActiveStates type)
void SetAction (uint32 action)
Public Attributes
uint32 packedData
Detailed Description
Definition at line 1168 of file Unit.h.
Constructor & Destructor Documentation
UnitActionBarEntry()
UnitActionBarEntry::UnitActionBarEntry () inline
Definition at line 1170 of file Unit.h.
 : packedData(uint32(ACT_DISABLED) << 24) {}
Member Function Documentation
GetAction()
uint32 UnitActionBarEntry::GetAction () const inline
Definition at line 1176 of file Unit.h.
 { return UNIT_ACTION_BUTTON_ACTION(packedData); }
References packedData, and UNIT_ACTION_BUTTON_ACTION.
Referenced by Player::CharmSpellInitialize(), Creature::GetPetAutoSpellOnPos(), WorldSession::HandlePetSetAction(), Pet::SavePetToDB(), CharmInfo::SetSpellAutocast(), and CharmInfo::ToggleCreatureAutocast().
GetType()
ActiveStates UnitActionBarEntry::GetType () const inline
Definition at line 1175 of file Unit.h.
 { return ActiveStates(UNIT_ACTION_BUTTON_TYPE(packedData)); }
References packedData, and UNIT_ACTION_BUTTON_TYPE.
Referenced by Creature::GetPetAutoSpellOnPos(), WorldSession::HandlePetSetAction(), IsActionBarForSpell(), and Pet::SavePetToDB().
IsActionBarForSpell()
bool UnitActionBarEntry::IsActionBarForSpell () const inline
Definition at line 1177 of file Unit.h.
     {
         ActiveStates Type = GetType();
         return Type == ACT_DISABLED || Type == ACT_ENABLED || Type == ACT_PASSIVE;
     }
References ACT_DISABLED, ACT_ENABLED, ACT_PASSIVE, and GetType().
Referenced by CharmInfo::SetSpellAutocast().
SetAction()
void UnitActionBarEntry::SetAction (uint32 action) inline
Definition at line 1193 of file Unit.h.
     {
         packedData = (packedData & 0xFF000000) | UNIT_ACTION_BUTTON_ACTION(action);
     }
References packedData, and UNIT_ACTION_BUTTON_ACTION.
Referenced by CharmInfo::AddSpellToActionBar().
SetActionAndType()
void UnitActionBarEntry::SetActionAndType (uint32 action, ActiveStates type) inline
Definition at line 1183 of file Unit.h.
     {
         packedData = MAKE_UNIT_ACTION_BUTTON(action, type);
     }
References MAKE_UNIT_ACTION_BUTTON, and packedData.
Referenced by CharmInfo::InitCharmCreateSpells(), CharmInfo::LoadPetActionBar(), and CharmInfo::SetActionBar().
SetType()
void UnitActionBarEntry::SetType (ActiveStates type) inline
Definition at line 1188 of file Unit.h.
     {
         packedData = MAKE_UNIT_ACTION_BUTTON(UNIT_ACTION_BUTTON_ACTION(packedData), type);
     }
References MAKE_UNIT_ACTION_BUTTON, packedData, and UNIT_ACTION_BUTTON_ACTION.
Referenced by CharmInfo::SetSpellAutocast(), and CharmInfo::ToggleCreatureAutocast().
Member Data Documentation
packedData
uint32 UnitActionBarEntry::packedData
Definition at line 1172 of file Unit.h.
Referenced by Player::CharmSpellInitialize(), GetAction(), GetType(), SetAction(), SetActionAndType(), and SetType().
The documentation for this struct was generated from the following file:
src/server/game/Entities/Unit/Unit.h