Azerotcore-wotlk: boss_viscidus::boss_viscidusAI Struct Reference
boss_viscidus::boss_viscidusAI Struct Reference
Public Member Functions
boss_viscidusAI (Creature *creature)
void Reset () override
void DamageTaken (Unit *attacker, uint32 &, DamageEffectType, SpellSchoolMask) override
void SpellHit (Unit *, SpellInfo const *spell) override
void EnterCombat (Unit *) override
void InitSpells ()
void EnterEvadeMode () override
void JustDied (Unit *) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void JustSummoned (Creature *summon) override
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void KilledUnit (Unit *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Attributes
uint8 _hitcounter
Phases _phase
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 92 of file boss_viscidus.cpp.
Constructor & Destructor Documentation
boss_viscidusAI()
boss_viscidus::boss_viscidusAI::boss_viscidusAI (Creature * creature) inline
Definition at line 94 of file boss_viscidus.cpp.
 : BossAI(creature, DATA_VISCIDUS) { }
Member Function Documentation
DamageTaken()
void boss_viscidus::boss_viscidusAI::DamageTaken (Unit * attacker, uint32 & , DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 103 of file boss_viscidus.cpp.
         {
             if (!attacker || _phase != PHASE_MELEE)
                 return;
             ++_hitcounter;
             if (attacker->HasUnitState(UNIT_STATE_MELEE_ATTACKING) && _hitcounter >= HITCOUNTER_EXPLODE)
             {
                 Talk(EMOTE_EXPLODE);
                 events.Reset();
                 _phase = PHASE_GLOB;
                 DoCast(me, SPELL_VISCIDUS_EXPLODE);
                 me->SetVisible(false);
                 me->RemoveAura(SPELL_TOXIN);
                 me->RemoveAura(SPELL_VISCIDUS_FREEZE);
                 uint8 NumGlobes = me->GetHealthPct() / 5.0f;
                 for (uint8 i = 0; i < NumGlobes; ++i)
                 {
                     float Angle = i * 2 * M_PI / NumGlobes;
                     float X = ViscidusCoord.GetPositionX() + std::cos(Angle) * RoomRadius;
                     float Y = ViscidusCoord.GetPositionY() + std::sin(Angle) * RoomRadius;
                     float Z = -35.0f;
                     if (TempSummon* Glob = me->SummonCreature(NPC_GLOB_OF_VISCIDUS, X, Y, Z))
                     {
                         Glob->UpdateAllowedPositionZ(X, Y, Z);
                         Glob->NearTeleportTo(X, Y, Z, 0.0f);
                         Glob->GetMotionMaster()->MovePoint(ROOM_CENTER, ViscidusCoord);
                     }
                 }
             }
             else if (_hitcounter == HITCOUNTER_SHATTER)
                 Talk(EMOTE_SHATTER);
             else if (_hitcounter == HITCOUNTER_CRACK)
                 Talk(EMOTE_CRACK);
         }
References _hitcounter, _phase, UnitAI::DoCast(), EMOTE_CRACK, EMOTE_EXPLODE, EMOTE_SHATTER, Unit::GetHealthPct(), Position::GetPositionX(), Position::GetPositionY(), Unit::HasUnitState(), HITCOUNTER_CRACK, HITCOUNTER_EXPLODE, HITCOUNTER_SHATTER, ScriptedAI::me, NPC_GLOB_OF_VISCIDUS, PHASE_GLOB, PHASE_MELEE, Unit::RemoveAura(), ROOM_CENTER, RoomRadius, Unit::SetVisible(), SPELL_TOXIN, SPELL_VISCIDUS_EXPLODE, SPELL_VISCIDUS_FREEZE, WorldObject::SummonCreature(), CreatureAI::Talk(), UNIT_STATE_MELEE_ATTACKING, and ViscidusCoord.
EnterCombat()
void boss_viscidus::boss_viscidusAI::EnterCombat (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 171 of file boss_viscidus.cpp.
         {
             _EnterCombat();
             events.Reset();
             InitSpells();
         }
References BossAI::_EnterCombat(), and InitSpells().
EnterEvadeMode()
void boss_viscidus::boss_viscidusAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 185 of file boss_viscidus.cpp.
         {
             summons.DespawnAll();
             ScriptedAI::EnterEvadeMode();
         }
References SummonList::DespawnAll(), CreatureAI::EnterEvadeMode(), and BossAI::summons.
InitSpells()
void boss_viscidus::boss_viscidusAI::InitSpells () inline
Definition at line 178 of file boss_viscidus.cpp.
         {
             DoCast(me, SPELL_TOXIN);
             events.ScheduleEvent(EVENT_POISONBOLT_VOLLEY, urand(10000, 15000));
             events.ScheduleEvent(EVENT_POISON_SHOCK, urand(7000, 12000));
         }
References UnitAI::DoCast(), EVENT_POISON_SHOCK, EVENT_POISONBOLT_VOLLEY, ScriptedAI::me, SPELL_TOXIN, and urand().
Referenced by EnterCombat(), and UpdateAI().
JustDied()
void boss_viscidus::boss_viscidusAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 191 of file boss_viscidus.cpp.
         {
             DoCast(me, SPELL_VISCIDUS_SUICIDE);
             summons.DespawnAll();
         }
References SummonList::DespawnAll(), UnitAI::DoCast(), ScriptedAI::me, SPELL_VISCIDUS_SUICIDE, and BossAI::summons.
Reset()
void boss_viscidus::boss_viscidusAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 96 of file boss_viscidus.cpp.
         {
             _Reset();
             _hitcounter = 0;
             _phase = PHASE_FROST;
         }
References _hitcounter, _phase, BossAI::_Reset(), and PHASE_FROST.
SpellHit()
void boss_viscidus::boss_viscidusAI::SpellHit (Unit * , SpellInfo const * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 142 of file boss_viscidus.cpp.
         {
             if ((spell->GetSchoolMask() & SPELL_SCHOOL_MASK_FROST) && _phase == PHASE_FROST && me->GetHealthPct() > 5.0f)
             {
                 ++_hitcounter;
                 if (_hitcounter >= HITCOUNTER_FREEZE)
                 {
                     _hitcounter = 0;
                     Talk(EMOTE_FROZEN);
                     _phase = PHASE_MELEE;
                     DoCast(me, SPELL_VISCIDUS_FREEZE);
                     me->RemoveAura(SPELL_VISCIDUS_SLOWED_MORE);
                     events.ScheduleEvent(EVENT_RESET_PHASE, 15000);
                 }
                 else if (_hitcounter >= HITCOUNTER_SLOW_MORE)
                 {
                     Talk(EMOTE_FREEZE);
                     me->RemoveAura(SPELL_VISCIDUS_SLOWED);
                     DoCast(me, SPELL_VISCIDUS_SLOWED_MORE);
                 }
                 else if (_hitcounter >= HITCOUNTER_SLOW)
                 {
                     Talk(EMOTE_SLOW);
                     DoCast(me, SPELL_VISCIDUS_SLOWED);
                 }
             }
         }
References _hitcounter, _phase, UnitAI::DoCast(), EMOTE_FREEZE, EMOTE_FROZEN, EMOTE_SLOW, EVENT_RESET_PHASE, Unit::GetHealthPct(), SpellInfo::GetSchoolMask(), HITCOUNTER_FREEZE, HITCOUNTER_SLOW, HITCOUNTER_SLOW_MORE, ScriptedAI::me, PHASE_FROST, PHASE_MELEE, Unit::RemoveAura(), SPELL_SCHOOL_MASK_FROST, SPELL_VISCIDUS_FREEZE, SPELL_VISCIDUS_SLOWED, SPELL_VISCIDUS_SLOWED_MORE, and CreatureAI::Talk().
UpdateAI()
void boss_viscidus::boss_viscidusAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 197 of file boss_viscidus.cpp.
         {
             if (!UpdateVictim())
                 return;
             if (_phase == PHASE_GLOB && summons.empty())
             {
                 DoResetThreat();
                 me->NearTeleportTo(ViscidusCoord.GetPositionX(),
                                    ViscidusCoord.GetPositionY(),
                                    ViscidusCoord.GetPositionZ(),
                                    ViscidusCoord.GetOrientation());
                 _hitcounter = 0;
                 _phase = PHASE_FROST;
                 InitSpells();
                 me->SetVisible(true);
             }
             events.Update(diff);
             while (uint32 eventId = events.ExecuteEvent())
             {
                 switch (eventId)
                 {
                     case EVENT_POISONBOLT_VOLLEY:
                         DoCast(me, SPELL_POISONBOLT_VOLLEY);
                         events.ScheduleEvent(EVENT_POISONBOLT_VOLLEY, urand(10000, 15000));
                         break;
                     case EVENT_POISON_SHOCK:
                         DoCast(me, SPELL_POISON_SHOCK);
                         events.ScheduleEvent(EVENT_POISON_SHOCK, urand(7000, 12000));
                         break;
                     case EVENT_RESET_PHASE:
                         _hitcounter = 0;
                         _phase = PHASE_FROST;
                         break;
                     default:
                         break;
                 }
             }
             if (_phase != PHASE_GLOB)
                 DoMeleeAttackIfReady();
         }
References _hitcounter, _phase, UnitAI::DoCast(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DoResetThreat(), SummonList::empty(), EVENT_POISON_SHOCK, EVENT_POISONBOLT_VOLLEY, EVENT_RESET_PHASE, Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), InitSpells(), ScriptedAI::me, Unit::NearTeleportTo(), PHASE_FROST, PHASE_GLOB, Unit::SetVisible(), SPELL_POISON_SHOCK, SPELL_POISONBOLT_VOLLEY, BossAI::summons, CreatureAI::UpdateVictim(), urand(), and ViscidusCoord.
Member Data Documentation
_hitcounter
uint8 boss_viscidus::boss_viscidusAI::_hitcounter private
Definition at line 244 of file boss_viscidus.cpp.
Referenced by DamageTaken(), Reset(), SpellHit(), and UpdateAI().
_phase
Phases boss_viscidus::boss_viscidusAI::_phase private
Definition at line 245 of file boss_viscidus.cpp.
Referenced by DamageTaken(), Reset(), SpellHit(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_viscidus.cpp