Azerotcore-wotlk: ObjectGuid Class Reference
ObjectGuid Class Reference
#include <ObjectGuid.h>
Public Types
typedef uint32 LowType
Public Member Functions
ObjectGuid ()
ObjectGuid (uint64 guid)
ObjectGuid (HighGuid hi, uint32 entry, LowType counter)
ObjectGuid (HighGuid hi, LowType counter)
PackedGuidReader ReadAsPacked ()
void Set (uint64 guid)
void Clear ()
PackedGuid WriteAsPacked () const
uint64 GetRawValue () const
HighGuid GetHigh () const
uint32 GetEntry () const
LowType GetCounter () const
ObjectGuid::LowType GetMaxCounter () const
bool IsEmpty () const
bool IsCreature () const
bool IsPet () const
bool IsVehicle () const
bool IsCreatureOrPet () const
bool IsCreatureOrVehicle () const
bool IsAnyTypeCreature () const
bool IsPlayer () const
bool IsUnit () const
bool IsItem () const
bool IsGameObject () const
bool IsDynamicObject () const
bool IsCorpse () const
bool IsTransport () const
bool IsMOTransport () const
bool IsAnyTypeGameObject () const
bool IsInstance () const
bool IsGroup () const
TypeID GetTypeId () const
operator bool () const
bool operator! () const
bool operator== (ObjectGuid const &guid) const
bool operator!= (ObjectGuid const &guid) const
bool operator< (ObjectGuid const &guid) const
bool operator<= (ObjectGuid const &guid) const
char const * GetTypeName () const
std::string ToString () const
Static Public Member Functions
template<HighGuid type>
static std::enable_if< ObjectGuidTraits< type >::Global, ObjectGuid >::type Create (LowType counter)
template<HighGuid type>
static std::enable_if< ObjectGuidTraits< type >::MapSpecific, ObjectGuid >::type Create (uint32 entry, LowType counter)
static LowType GetMaxCounter (HighGuid high)
static TypeID GetTypeId (HighGuid high)
static char const * GetTypeName (HighGuid high)
Static Public Attributes
static ObjectGuid const Empty = ObjectGuid()
Private Member Functions
bool HasEntry () const
ObjectGuid (uint32 const &)=delete
ObjectGuid (HighGuid, uint32, uint64 counter)=delete
ObjectGuid (HighGuid, uint64 counter)=delete
operator int64 () const =delete
Static Private Member Functions
static bool HasEntry (HighGuid high)
static ObjectGuid Global (HighGuid type, LowType counter)
static ObjectGuid MapSpecific (HighGuid type, uint32 entry, LowType counter)
Private Attributes
uint64 _guid
Detailed Description
Definition at line 119 of file ObjectGuid.h.
Member Typedef Documentation
LowType
typedef uint32 ObjectGuid::LowType
Definition at line 124 of file ObjectGuid.h.
Constructor & Destructor Documentation
ObjectGuid() [1/7]
ObjectGuid::ObjectGuid () inline
Definition at line 132 of file ObjectGuid.h.
 : _guid(0) { }
Referenced by Global(), and MapSpecific().
ObjectGuid() [2/7]
ObjectGuid::ObjectGuid (uint64 guid) inline explicit
Definition at line 133 of file ObjectGuid.h.
 : _guid(guid) { }
ObjectGuid() [3/7]
ObjectGuid::ObjectGuid (HighGuid hi, uint32 entry, LowType counter) inline
Definition at line 134 of file ObjectGuid.h.
 : _guid(counter ? uint64(counter) | (uint64(entry) << 24) | (uint64(hi) << 48) : 0) { }
ObjectGuid() [4/7]
ObjectGuid::ObjectGuid (HighGuid hi, LowType counter) inline
Definition at line 135 of file ObjectGuid.h.
 : _guid(counter ? uint64(counter) | (uint64(hi) << 48) : 0) { }
ObjectGuid() [5/7]
ObjectGuid::ObjectGuid (uint32 const &) explicit private delete
ObjectGuid() [6/7]
ObjectGuid::ObjectGuid (HighGuid , uint32 , uint64 counter) private delete
ObjectGuid() [7/7]
ObjectGuid::ObjectGuid (HighGuid , uint64 counter) private delete
Member Function Documentation
Clear()
void ObjectGuid::Clear () inline
Definition at line 140 of file ObjectGuid.h.
 { _guid = 0; }
References _guid.
Referenced by boss_ahune::boss_ahuneAI::boss_ahuneAI(), boss_festergut::boss_festergutAI::boss_festergutAI(), boss_freya_nature_bomb::boss_freya_nature_bombAI::boss_freya_nature_bombAI(), boss_grand_champion::boss_grand_championAI::boss_grand_championAI(), boss_svala::boss_svalaAI::boss_svalaAI(), boss_yoggsaron_constrictor_tentacle::boss_yoggsaron_constrictor_tentacleAI::boss_yoggsaron_constrictor_tentacleAI(), lfg::LFGQueue::CheckCompatibility(), npc_cork_gizelton::npc_cork_gizeltonAI::CheckPlayer(), Loot::clear(), Player::ClearComboPoints(), PassengerController::ClearSlot(), Group::Create(), boss_taldaram::boss_taldaramAI::DamageTaken(), npc_death_knight_initiate::npc_death_knight_initiateAI::DamageTaken(), BfCapturePoint::DelCapturePoint(), boss_zuljin::boss_zuljinAI::DespawnAdds(), boss_netherspite::boss_netherspiteAI::DestroyPortals(), npc_icc_ice_sphere::npc_icc_ice_sphereAI::DoAction(), instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::DoAction(), boss_paletress::boss_paletressAI::DoAction(), boss_grand_champion::boss_grand_championAI::DoAction(), npc_anubarak_spike::npc_anubarak_spikeAI::DoAction(), WorldSession::DoLootRelease(), Spell::EffectSummonChangeItem(), Spell::EffectSummonObject(), boss_malchezaar::boss_malchezaarAI::EnfeebleResetHealth(), spell_brewfest_fill_keg::spell_brewfest_fill_keg_SpellScript::HandleAfterHit(), spell_brewfest_unfill_keg::spell_brewfest_unfill_keg_SpellScript::HandleAfterHit(), OPvPCapturePointZM_GraveYard::HandleDropFlag(), WorldSession::HandleEquipmentSetSave(), boss_akilzon::boss_akilzonAI::HandleStormSequence(), BattlegroundEY::Init(), BattlegroundWS::Init(), boss_vaelastrasz::boss_vaelAI::Initialize(), npc_beryl_sorcerer::npc_beryl_sorcererAI::Initialize(), npc_hidden_cultist::npc_hidden_cultistAI::Initialize(), npc_thassarian2::npc_thassarian2AI::Initialize(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::Initialize(), npc_shay_leafrunner::npc_shay_leafrunnerAI::InitializeAI(), npc_lord_arete::npc_lord_areteAI::InitializeAI(), npc_pet_mage_mirror_image::InitializeAI(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::InstanceCleanup(), instance_violet_hold::instance_violet_hold_InstanceMapScript::InstanceCleanup(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::InstanceCleanup(), npc_pet_gen_fetch_ball::IsSummonedBy(), boss_terestian_illhoof::boss_terestianAI::JustDied(), npc_clintar_spirit::npc_clintar_spiritAI::JustDied(), npc_ice_tomb::npc_ice_tombAI::JustDied(), SmartAI::JustRespawned(), boss_archimonde::boss_archimondeAI::JustSummoned(), boss_taldaram::boss_taldaramAI::KilledUnit(), lfg::LFGMgr::LeaveAllLfgQueues(), spell_dk_scourge_strike::Load(), spell_rog_blade_flurry::Load(), npc_air_force_bots::npc_air_force_botsAI::MoveInLineOfSight(), boss_grand_champion::boss_grand_championAI::MovementInform(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::MovementInform(), npc_akilzon_eagle::npc_akilzon_eagleAI::MovementInform(), npc_pet_mage_mirror_image::MySelectNextTarget(), npc_air_force_bots::npc_air_force_botsAI::npc_air_force_botsAI(), npc_ancient_wisp::npc_ancient_wispAI::npc_ancient_wispAI(), npc_archmage_landalock::npc_archmage_landalockAI::npc_archmage_landalockAI(), npc_balance_of_light_and_shadow::npc_balance_of_light_and_shadowAI::npc_balance_of_light_and_shadowAI(), npc_clintar_spirit::npc_clintar_spiritAI::npc_clintar_spiritAI(), npc_drakuru_shackles::npc_drakuru_shacklesAI::npc_drakuru_shacklesAI(), npc_enslaved_netherwing_drake::npc_enslaved_netherwing_drakeAI::npc_enslaved_netherwing_drakeAI(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::npc_grand_magister_rommathAI(), npc_hol_monument::npc_hol_monumentAI::npc_hol_monumentAI(), npc_icc_ice_sphere::npc_icc_ice_sphereAI::npc_icc_ice_sphereAI(), npc_midsummer_bonfire::npc_midsummer_bonfireAI::npc_midsummer_bonfireAI(), npc_midsummer_torch_target::npc_midsummer_torch_targetAI::npc_midsummer_torch_targetAI(), npc_oscillating_frequency_scanner_master_bunny::npc_oscillating_frequency_scanner_master_bunnyAI::npc_oscillating_frequency_scanner_master_bunnyAI(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::npc_pet_dk_ebon_gargoyleAI(), npc_pet_gen_imp_in_a_bottle::npc_pet_gen_imp_in_a_bottle(), npc_pet_gen_plump_turkey::npc_pet_gen_plump_turkey(), npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::npc_pilgrims_bounty_chairAI(), npc_pos_leader_second::npc_pos_leader_secondAI::npc_pos_leader_secondAI(), npc_snobold_vassal::npc_snobold_vassalAI::npc_snobold_vassalAI(), npc_torturer_lecraft::npc_torturer_lecraftAI::npc_torturer_lecraftAI(), npc_ulduar_storm_tempered_keeper::npc_ulduar_storm_tempered_keeperAI::npc_ulduar_storm_tempered_keeperAI(), npc_vengeful_shade::npc_vengeful_shadeAI::npc_vengeful_shadeAI(), npc_vh_void_sentry::npc_vh_void_sentryAI::npc_vh_void_sentryAI(), BattlefieldWG::OnBattleEnd(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureRemove(), instance_ulduar::instance_ulduar_InstanceMapScript::OnCreatureRemove(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectRemove(), SmartScript::OnReset(), OPvPCapturePointZM_GraveYard::OPvPCapturePointZM_GraveYard(), boss_kologarn::boss_kologarnAI::PassengerBoarded(), spell_midsummer_torch_quest::spell_midsummer_torch_quest_AuraScript::PrepareAuraScript(), Unit::RemoveGameObject(), SpellCastTargets::RemoveObjectTarget(), MotionTransport::RemovePassenger(), StaticTransport::RemovePassenger(), npc_cork_gizelton::npc_cork_gizeltonAI::RemoveSummons(), boss_sartharion_dragonAI::RemoveTwilightPortal(), MovementInfo::TransportInfo::Reset(), PassengerInfo::Reset(), npc_water_elemental::npc_water_elementalAI::Reset(), boss_rend_blackhand::boss_rend_blackhandAI::Reset(), npc_kilrek::npc_kilrekAI::Reset(), npc_demon_chain::npc_demon_chainAI::Reset(), boss_terestian_illhoof::boss_terestianAI::Reset(), npc_tito::npc_titoAI::Reset(), boss_bigbadwolf::boss_bigbadwolfAI::Reset(), boss_julianne::boss_julianneAI::Reset(), boss_romulo::boss_romuloAI::Reset(), npc_barnes::npc_barnesAI::Reset(), npc_image_of_medivh::npc_image_of_medivhAI::Reset(), boss_selin_fireheart::boss_selin_fireheartAI::Reset(), npc_death_knight_initiate::npc_death_knight_initiateAI::Reset(), npc_unworthy_initiate::npc_unworthy_initiateAI::Reset(), npc_scarlet_miner::npc_scarlet_minerAI::Reset(), npc_crusade_persuaded::npc_crusade_persuadedAI::Reset(), npc_koltira_deathweaver::npc_koltira_deathweaverAI::Reset(), npc_a_special_surprise::npc_a_special_surpriseAI::Reset(), boss_baroness_anastari::boss_baroness_anastariAI::Reset(), npc_eris_hevenfire::npc_eris_hevenfireAI::Reset(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::Reset(), pyrewood_ambush::pyrewood_ambushAI::Reset(), npc_lord_gregor_lescovar::npc_lord_gregor_lescovarAI::Reset(), npc_calvin_montague::npc_calvin_montagueAI::Reset(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::Reset(), npc_varian_wrynn::npc_varian_wrynnAI::Reset(), npc_thrall_bfu::npc_thrall_bfuAI::Reset(), boss_akilzon::boss_akilzonAI::Reset(), npc_akilzon_eagle::npc_akilzon_eagleAI::Reset(), boss_halazzi::boss_halazziAI::Reset(), boss_zuljin::boss_zuljinAI::Reset(), npc_harrison_jones::npc_harrison_jonesAI::Reset(), npc_dark_iron_guzzler::npc_dark_iron_guzzlerAI::Reset(), npc_winterfin_playmate::npc_winterfin_playmateAI::Reset(), npc_snowfall_glade_playmate::npc_snowfall_glade_playmateAI::Reset(), npc_the_biggest_tree::npc_the_biggest_treeAI::Reset(), npc_high_oracle_soo_roo::npc_high_oracle_soo_rooAI::Reset(), npc_elder_kekek::npc_elder_kekekAI::Reset(), npc_the_etymidian::npc_the_etymidianAI::Reset(), npc_alexstraza_the_lifebinder::npc_alexstraza_the_lifebinderAI::Reset(), npc_costumed_orphan_matron::npc_costumed_orphan_matronAI::Reset(), boss_headless_horseman::boss_headless_horsemanAI::Reset(), npc_doomfire_targetting::npc_doomfire_targettingAI::Reset(), boss_archimonde::boss_archimondeAI::Reset(), hyjalAI::Reset(), boss_ossirian::boss_ossirianAI::Reset(), boss_cthun::cthunAI::Reset(), npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI::Reset(), npc_draenei_survivor::npc_draenei_survivorAI::Reset(), npc_stillpine_capitive::npc_stillpine_capitiveAI::Reset(), npc_clintar_spirit::npc_clintar_spiritAI::Reset(), npc_shenthul::npc_shenthulAI::Reset(), npc_anachronos_the_ancient::npc_anachronos_the_ancientAI::Reset(), npc_qiraj_war_spawn::npc_qiraj_war_spawnAI::Reset(), npc_anachronos_quest_trigger::npc_anachronos_quest_triggerAI::Reset(), npc_tooga::npc_toogaAI::Reset(), npc_twiggy_flathead::npc_twiggy_flatheadAI::Reset(), npc_ringo::npc_ringoAI::Reset(), boss_elder_nadox::boss_elder_nadoxAI::Reset(), boss_jedoga_shadowseeker::boss_jedoga_shadowseekerAI::Reset(), boss_taldaram::boss_taldaramAI::Reset(), boss_sartharion_dragonAI::Reset(), boss_paletress::boss_paletressAI::Reset(), boss_gormok::boss_gormokAI::Reset(), boss_novos::boss_novosAI::Reset(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::Reset(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::Reset(), npc_highlord_tirion_fordring_lh::npc_highlord_tirion_fordringAI::Reset(), boss_sapphiron::boss_sapphironAI::Reset(), npc_stormforged_lieutenant::npc_stormforged_lieutenantAI::Reset(), boss_freya::boss_freyaAI::Reset(), boss_razorscale::boss_razorscaleAI::Reset(), npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::Reset(), boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::Reset(), boss_yoggsaron_llane::boss_yoggsaron_llaneAI::Reset(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::Reset(), boss_palehoof::boss_palehoofAI::Reset(), npc_sinkhole_kill_credit::npc_sinkhole_kill_creditAI::Reset(), npc_bloodmage_laurith::npc_bloodmage_laurithAI::Reset(), npc_warmage_violetstand::npc_warmage_violetstandAI::Reset(), npc_shandy_dalaran::npc_shandy_dalaranAI::Reset(), npc_conversing_with_the_depths_trigger::npc_conversing_with_the_depths_triggerAI::Reset(), npc_q24545_lich_king::npc_q24545_lich_kingAI::Reset(), npc_torturer_lecraft::npc_torturer_lecraftAI::Reset(), npc_emily::npc_emilyAI::Reset(), npc_wounded_skirmisher::npc_wounded_skirmisherAI::Reset(), npc_venture_co_straggler::npc_venture_co_stragglerAI::Reset(), npc_still_at_it_trigger::npc_still_at_it_triggerAI::Reset(), npc_jungle_punch_target::npc_jungle_punch_targetAI::Reset(), npc_wild_wyrm::npc_wild_wyrmAI::Reset(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::Reset(), boss_shirrak_the_dead_watcher::boss_shirrak_the_dead_watcherAI::Reset(), boss_essence_of_anger::boss_essence_of_angerAI::Reset(), npc_steamrigger_mechanic::npc_steamrigger_mechanicAI::Reset(), boss_the_black_stalker::boss_the_black_stalkerAI::Reset(), boss_omor_the_unscarred::boss_omor_the_unscarredAI::Reset(), npc_fel_guard_hound::npc_fel_guard_houndAI::Reset(), npc_commander_dawnforge::npc_commander_dawnforgeAI::Reset(), npc_phase_hunter::npc_phase_hunterAI::Reset(), npc_mature_netherwing_drake::npc_mature_netherwing_drakeAI::Reset(), npc_dragonmaw_peon::npc_dragonmaw_peonAI::Reset(), npc_torloth_the_magnificent::npc_torloth_the_magnificentAI::Reset(), npc_lord_illidan_stormrage::npc_lord_illidan_stormrageAI::Reset(), npc_illidari_spawn::npc_illidari_spawnAI::Reset(), npc_pet_gen_mojo::Reset(), guard_shattrath_scryer::guard_shattrath_scryerAI::Reset(), guard_shattrath_aldor::guard_shattrath_aldorAI::Reset(), npc_doctor::npc_doctorAI::Reset(), npc_injured_patient::npc_injured_patientAI::Reset(), npc_garments_of_quests::npc_garments_of_questsAI::Reset(), npc_spring_rabbit::npc_spring_rabbitAI::Reset(), SmartScript::ResetBaseObject(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::ResetData(), PassengerController::ResetSlots(), NPCStaveQuestAI::ResetState(), Player::RewardHonor(), boss_taldaram::boss_taldaramAI::ScheduleCombatEvents(), boss_selin_fireheart::boss_selin_fireheartAI::SelectNearestCrystal(), npc_putricide_oozeAI::SelectNewTarget(), npc_icc_ice_sphere::npc_icc_ice_sphereAI::SelectNewTarget(), npc_anubarak_spike::npc_anubarak_spikeAI::SelectNewTarget(), OPvPCapturePointZM_GraveYard::SetBeaconState(), npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::SetData(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::SetData(), instance_ulduar::instance_ulduar_InstanceMapScript::SetData(), instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::SetData(), npc_q24545_lich_king::npc_q24545_lich_kingAI::SetData(), GameObject::SetLootRecipient(), Creature::SetLootRecipient(), GmTicket::SetUnassigned(), BattlefieldWG::SetupBattlefield(), SmartAI::StopFollow(), npc_cork_gizelton::npc_cork_gizeltonAI::SummonedCreatureDespawn(), npc_cork_gizelton::npc_cork_gizeltonAI::SummonedCreatureDies(), Spell::TakeCastItem(), Spell::TakeReagents(), npc_drakuru_shackles::npc_drakuru_shacklesAI::UnlockRageclaw(), Totem::UnSummon(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::Update(), TotemAI::UpdateAI(), boss_shade_of_aran::boss_aranAI::UpdateAI(), boss_bigbadwolf::boss_bigbadwolfAI::UpdateAI(), boss_zuljin::boss_zuljinAI::UpdateAI(), npc_doomfire_targetting::npc_doomfire_targettingAI::UpdateAI(), hyjalAI::UpdateAI(), boss_cthun::cthunAI::UpdateAI(), npc_clintar_spirit::npc_clintar_spiritAI::UpdateAI(), boss_grand_champion::boss_grand_championAI::UpdateAI(), npc_snobold_vassal::npc_snobold_vassalAI::UpdateAI(), boss_gormok::boss_gormokAI::UpdateAI(), npc_pos_leader_second::npc_pos_leader_secondAI::UpdateAI(), boss_blood_queen_lana_thel::boss_blood_queen_lana_thelAI::UpdateAI(), boss_sapphiron::boss_sapphironAI::UpdateAI(), npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::UpdateAI(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::UpdateAI(), npc_bloodmage_laurith::npc_bloodmage_laurithAI::UpdateAI(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::UpdateAI(), boss_the_black_stalker::boss_the_black_stalkerAI::UpdateAI(), boss_omor_the_unscarred::boss_omor_the_unscarredAI::UpdateAI(), guard_shattrath_scryer::guard_shattrath_scryerAI::UpdateAI(), guard_shattrath_aldor::guard_shattrath_aldorAI::UpdateAI(), boss_netherspite::boss_netherspiteAI::UpdatePortals(), lfg::LFGMgr::UpdateRaidBrowser(), and npc_cork_gizelton::npc_cork_gizeltonAI::WaypointReached().
Create() [1/2]
template<HighGuid type> static std::enable_if<ObjectGuidTraits<type>::Global, ObjectGuid>::type ObjectGuid::Create (LowType counter) inline static
Definition at line 127 of file ObjectGuid.h.
 { return Global(type, counter); }
References Global().
Create() [2/2]
template<HighGuid type> static std::enable_if<ObjectGuidTraits<type>::MapSpecific, ObjectGuid>::type ObjectGuid::Create (uint32 entry, LowType counter) inline static
Definition at line 130 of file ObjectGuid.h.
 { return MapSpecific(type, entry, counter); }
References MapSpecific().
GetCounter()
LowType ObjectGuid::GetCounter () const inline
Definition at line 147 of file ObjectGuid.h.
         {
             return HasEntry()
                    ? LowType(_guid & UI64LIT(0x0000000000FFFFFF))
                    : LowType(_guid & UI64LIT(0x00000000FFFFFFFF));
         }
References _guid, HasEntry(), and UI64LIT.
Referenced by Player::_LoadItem(), Guild::_LogBankEvent(), Guild::_LogEvent(), Player::_SaveCharacter(), Player::_SaveEquipmentSets(), Player::_SaveInventory(), Player::_SaveQuestStatus(), Player::_SaveSpellCooldowns(), lfg::LFGMgr::_SaveToDB(), Guild::_SetLeaderGUID(), Channel::AddChannelBanToDB(), GroupMgr::AddGroup(), Guild::AddMember(), ArenaTeam::AddMember(), Group::AddMember(), Player::AddMItem(), LootItemStorage::AddNewStoredLoot(), PlayerSocial::AddToSocialList(), BanMgr::BanCharacter(), OPvPCapturePointZM_GraveYard::CanTalkTo(), Group::ChangeLeader(), Group::ChangeMembersGroup(), CharacterActionIpLogger::CharacterIPLogAction(), instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::CheckAchievementCriteriaMeet(), Map::ConvertCorpseToBones(), ArenaTeam::Create(), Group::Create(), Guild::Create(), Player::Customize(), AccountMgr::DeleteAccount(), Corpse::DeleteFromDB(), MailDraft::deleteIncludedItems(), CharacterDeleteActionIpLogger::DeleteIPLogAction(), Guild::DeleteMember(), ArenaTeam::DelMember(), Player::DestroyItem(), Battleground::EndBattleground(), BGQueueRemoveEvent::Execute(), GmTicket::FormatMessageString(), Player::GetArenaTeamIdFromDB(), GmTicket::GetAssignedToName(), WorldSession::GetGuidLow(), Map::GetLinkedRespawnTime(), Player::GetZoneIdFromDB(), Group::GroupLoot(), WorldSession::HandleAcceptTradeOpcode(), WorldSession::HandleAddFriendOpcode(), misc_commandscript::HandleAppearCommand(), arena_commandscript::HandleArenaCaptainCommand(), arena_commandscript::HandleArenaCreateCommand(), WorldSession::HandleArenaTeamAcceptOpcode(), WorldSession::HandleAuctionPlaceBid(), ban_commandscript::HandleBanInfoCharacterCommand(), WorldSession::HandleBattleFieldPortOpcode(), WorldSession::HandleBuybackItem(), WorldSession::HandleCalendarEventInvite(), character_commandscript::HandleCharacterEraseCommand(), character_commandscript::HandleCharacterLevel(), WorldSession::HandleCharDeleteOpcode(), debug_commandscript::HandleDebugGetItemStateCommand(), debug_commandscript::HandleDebugGetLootRecipientCommand(), debug_commandscript::HandleDebugGetValueCommand(), debug_commandscript::HandleDebugMod32ValueCommand(), debug_commandscript::HandleDebugSetValueCommand(), debug_commandscript::HandleDebugUpdateCommand(), gobject_commandscript::HandleGameObjectDeleteCommand(), misc_commandscript::HandleGearStatsCommand(), WorldSession::HandleGetMailList(), ticket_commandscript::HandleGMTicketAssignToCommand(), ticket_commandscript::HandleGMTicketUnAssignCommand(), misc_commandscript::HandleGroupListCommand(), WorldSession::HandleGroupUninviteGuidOpcode(), guild_commandscript::HandleGuildInfoCommand(), guild_commandscript::HandleGuildUninviteCommand(), WorldSession::HandleLoadPetFromDBFirstCallback(), WorldSession::HandleMailDelete(), WorldSession::HandleMailReturnToSender(), WorldSession::HandleMailTakeItem(), Guild::HandleMemberDepositMoney(), Guild::HandleMemberWithdrawMoney(), modify_commandscript::HandleModifyFactionCommand(), misc_commandscript::HandleMovegensCommand(), npc_commandscript::HandleNpcInfoCommand(), npc_commandscript::HandleNpcSetDataCommand(), npc_commandscript::HandleNpcSetLinkCommand(), WorldSession::HandleOfferPetitionOpcode(), WorldSession::HandleOpenItemOpcode(), WorldSession::HandleOpenWrappedItemCallback(), character_commandscript::HandlePDumpWriteCommand(), WorldSession::HandlePetitionBuyOpcode(), WorldSession::HandlePetitionRenameOpcode(), WorldSession::HandlePetitionShowSignOpcode(), WorldSession::HandlePetitionSignOpcode(), WorldSession::HandlePetRename(), misc_commandscript::HandlePInfoCommand(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandlePlayerLoginOpcode(), quest_commandscript::HandleQuestComplete(), WorldSession::HandleQuestLogRemoveQuest(), reset_commandscript::HandleResetAchievementsCommand(), reset_commandscript::HandleResetSpellsCommand(), reset_commandscript::HandleResetTalentsCommand(), PetAI::HandleReturnMovement(), misc_commandscript::HandleSendItemsCommand(), WorldSession::HandleSendMail(), misc_commandscript::HandleSendMailCommand(), misc_commandscript::HandleSendMoneyCommand(), WorldSession::HandleSetPlayerDeclinedNames(), WorldSession::HandleSetSavedInstanceExtend(), WorldSession::HandleStablePet(), WorldSession::HandleStablePetCallback(), WorldSession::HandleStableSwapPet(), WorldSession::HandleStableSwapPetCallback(), WorldSession::HandleTurnInPetitionOpcode(), misc_commandscript::HandleUnmuteCommand(), WorldSession::HandleUnstablePet(), WorldSession::HandleUnstablePetCallback(), WorldSession::HandleWrapItemOpcode(), ChatHandler::HasLowerSecurity(), LoginQueryHolder::Initialize(), BattlegroundMgr::InviteGroupToBG(), Player::LeaveAllArenaTeams(), lfg::LFGMgr::LeaveLfg(), list_commandscript::ListAurasCommand(), InstanceSaveMgr::LoadCharacterBinds(), CalendarMgr::LoadFromDB(), Player::LoadFromDB(), GroupMgr::LoadGroups(), Guild::LoadMemberFromDB(), Group::LoadMemberFromDB(), ArenaTeam::LoadMembersFromDB(), Pet::LoadPetFromDB(), WorldSession::LogoutPlayer(), MailReceiver::MailReceiver(), MailSender::MailSender(), Channel::MakeChannelOwner(), lfg::LFGMgr::MakeNewGroup(), Guild::MassInviteToEvent(), PetAI::MovementInform(), npc_spirit_shade::npc_spirit_shadeAI::MovementInform(), Group::NeedBeforeGreed(), Player::OfflineResurrect(), achievement_intense_cold::OnCheck(), OutdoorPvP::OnCreatureCreate(), OutdoorPvP::OnCreatureRemove(), OutdoorPvP::OnGameObjectCreate(), OutdoorPvP::OnGameObjectRemove(), npc_death_knight_initiate::OnGossipHello(), ScriptMgr::OnPlayerDelete(), InstanceSaveMgr::PlayerBindToInstance(), InstanceSaveMgr::PlayerUnbindInstance(), WorldSession::recoveryItem(), BanMgr::RemoveBanCharacter(), Channel::RemoveChannelBanFromDB(), LootItemStorage::RemoveEntryFromDB(), CalendarMgr::RemoveEvent(), PlayerSocial::RemoveFromSocialList(), GroupMgr::RemoveGroup(), Group::RemoveMember(), Player::RemovePetitionsAndSigns(), LootItemStorage::RemoveStoredLoot(), AchievementMgr::Reset(), Pet::resetTalentsForAllPetsOf(), Pet::SavePetToDB(), Player::SavePositionInDB(), Item::SaveToDB(), ReputationMgr::SaveToDB(), AuctionEntry::SaveToDB(), GmTicket::SaveToDB(), AuctionHouseMgr::SendAuctionCancelledToBidderMail(), AuctionHouseMgr::SendAuctionExpiredMail(), AuctionHouseMgr::SendAuctionOutbiddedMail(), AuctionHouseMgr::SendAuctionSalePendingMail(), AuctionHouseMgr::SendAuctionSuccessfulMail(), AuctionHouseMgr::SendAuctionWonMail(), CalendarMgr::SendCalendarEvent(), CalendarMgr::SendCalendarEventInvite(), MailDraft::SendMailTo(), WorldSession::SendNameQueryOpcode(), WorldSession::SendPetitionQueryOpcode(), MailDraft::SendReturnToSender(), WorldSession::SendStablePet(), WorldSession::SendStablePetCallback(), ArenaTeam::SetCaptain(), PlayerSocial::SetFriendNote(), Group::SetGroupMemberFlag(), Guild::BankTab::SetItem(), GameObject::SetLootRecipient(), WorldSession::SetPlayer(), SortAuction(), npc_death_knight_initiate::npc_death_knight_initiateAI::SpellHit(), Player::StoreNewItem(), ToString(), Pet::TryLoadFromDB(), lfg::LFGMgr::UpdateBoot(), CalendarMgr::UpdateEvent(), and CalendarMgr::UpdateInvite().
GetEntry()
uint32 ObjectGuid::GetEntry () const inline
Definition at line 146 of file ObjectGuid.h.
 { return HasEntry() ? uint32((_guid >> 24) & UI64LIT(0x0000000000FFFFFF)) : 0; }
References _guid, HasEntry(), and UI64LIT.
Referenced by WorldSession::HandlePetSetAction(), WorldSession::HandlePetSpellAutocastOpcode(), EntryCheckPredicate::operator()(), ToString(), and npc_archmage_landalock::npc_archmage_landalockAI::UpdateAI().
GetHigh()
HighGuid ObjectGuid::GetHigh () const inline
Definition at line 145 of file ObjectGuid.h.
 { return HighGuid((_guid >> 48) & 0x0000FFFF); }
References _guid.
Referenced by SpellCastTargets::GetCorpseTargetGUID(), SpellCastTargets::GetGOTargetGUID(), Map::GetLinkedRespawnTime(), GetMaxCounter(), ObjectAccessor::GetObjectByTypeMask(), Map::GetTransport(), GetTypeId(), GetTypeName(), SpellCastTargets::GetUnitTargetGUID(), ObjectAccessor::GetWorldObject(), WorldSession::HandleLootMoneyOpcode(), HasEntry(), IsCorpse(), IsCreature(), IsDynamicObject(), IsGameObject(), IsGroup(), IsInstance(), IsItem(), IsMOTransport(), IsPet(), IsPlayer(), IsTransport(), IsVehicle(), and Map::ScriptsProcess().
GetMaxCounter() [1/2]
ObjectGuid::LowType ObjectGuid::GetMaxCounter () const inline
Definition at line 161 of file ObjectGuid.h.
 { return GetMaxCounter(GetHigh()); }
References GetHigh(), and GetMaxCounter().
Referenced by ObjectGuidGenerator< high >::Generate(), and GetMaxCounter().
GetMaxCounter() [2/2]
static LowType ObjectGuid::GetMaxCounter (HighGuid high) inline static
Definition at line 154 of file ObjectGuid.h.
         {
             return HasEntry(high)
                    ? LowType(0x00FFFFFF)
                    : LowType(0xFFFFFFFF);
         }
References HasEntry().
GetRawValue()
uint64 ObjectGuid::GetRawValue () const inline
Definition at line 144 of file ObjectGuid.h.
 { return _guid; }
References _guid.
Referenced by Pet::_SaveAuras(), AuctionEntry::BuildAuctionMailBody(), Spell::CheckCast(), Pet::HandleAsynchLoadFailed(), WorldSession::HandleCharDeleteOpcode(), WorldSession::HandleEquipmentSetSave(), WorldSession::HandleEquipmentSetUse(), Guild::MassInviteToEvent(), operator!=(), std::hash< ObjectGuid >::operator()(), CreatureTextLocalizer< Builder >::operator()(), operator<(), operator<<(), operator<=(), operator==(), PackedGuid::PackedGuid(), ArenaSpectator::SendCommand_Aura(), ArenaSpectator::SendCommand_Cooldown(), ArenaSpectator::SendCommand_GUID(), ArenaSpectator::SendCommand_Spell(), ArenaSpectator::SendCommand_String(), ArenaSpectator::SendCommand_UInt32Value(), PackedGuid::Set(), Movement::MoveSplineInit::SetFacing(), NPCStaveQuestAI::StoreAttackerGuidValue(), and SpellCastTargets::Update().
GetTypeId() [1/2]
TypeID ObjectGuid::GetTypeId () const inline
Definition at line 203 of file ObjectGuid.h.
 { return GetTypeId(GetHigh()); }
References GetHigh(), and GetTypeId().
Referenced by GetTypeId().
GetTypeId() [2/2]
static TypeID ObjectGuid::GetTypeId (HighGuid high) inline static
Definition at line 182 of file ObjectGuid.h.
         {
             switch (high)
             {
                 case HighGuid::Item:         return TYPEID_ITEM;
                 //case HighGuid::Container:    return TYPEID_CONTAINER; HighGuid::Container == HighGuid::Item currently
                 case HighGuid::Unit:         return TYPEID_UNIT;
                 case HighGuid::Pet:          return TYPEID_UNIT;
                 case HighGuid::Player:       return TYPEID_PLAYER;
                 case HighGuid::GameObject:   return TYPEID_GAMEOBJECT;
                 case HighGuid::DynamicObject: return TYPEID_DYNAMICOBJECT;
                 case HighGuid::Corpse:       return TYPEID_CORPSE;
                 case HighGuid::Mo_Transport: return TYPEID_GAMEOBJECT;
                 case HighGuid::Vehicle:      return TYPEID_UNIT;
                 // unknown
                 case HighGuid::Instance:
                 case HighGuid::Group:
                 default:                    return TYPEID_OBJECT;
             }
         }
References Corpse, DynamicObject, GameObject, Group, Instance, Item, Mo_Transport, Pet, Player, TYPEID_CORPSE, TYPEID_DYNAMICOBJECT, TYPEID_GAMEOBJECT, TYPEID_ITEM, TYPEID_OBJECT, TYPEID_PLAYER, TYPEID_UNIT, Unit, and Vehicle.
Referenced by Guardian::InitStats(), and Guardian::InitSummon().
GetTypeName() [1/2]
char const* ObjectGuid::GetTypeName () const inline
Definition at line 213 of file ObjectGuid.h.
 { return !IsEmpty() ? GetTypeName(GetHigh()) : "None"; }
References GetHigh(), GetTypeName(), and IsEmpty().
Referenced by GetTypeName(), ObjectGuidGeneratorBase::HandleCounterOverflow(), and ToString().
GetTypeName() [2/2]
char const * ObjectGuid::GetTypeName (HighGuid high) static
Definition at line 26 of file ObjectGuid.cpp.
 {
     switch (high)
     {
         case HighGuid::Item:         return "Item";
         case HighGuid::Player:       return "Player";
         case HighGuid::GameObject:   return "Gameobject";
         case HighGuid::Transport:    return "Transport";
         case HighGuid::Unit:         return "Creature";
         case HighGuid::Pet:          return "Pet";
         case HighGuid::Vehicle:      return "Vehicle";
         case HighGuid::DynamicObject: return "DynObject";
         case HighGuid::Corpse:       return "Corpse";
         case HighGuid::Mo_Transport: return "MoTransport";
         case HighGuid::Instance:     return "InstanceID";
         case HighGuid::Group:        return "Group";
         default:
             return "<unknown>";
     }
 }
References Corpse, DynamicObject, GameObject, Group, Instance, Item, Mo_Transport, Pet, Player, Transport, Unit, and Vehicle.
Global()
ObjectGuid ObjectGuid::Global (HighGuid type, LowType counter) static private
Definition at line 59 of file ObjectGuid.cpp.
 {
     return ObjectGuid(type, counter);
 }
References ObjectGuid().
Referenced by Create().
HasEntry() [1/2]
bool ObjectGuid::HasEntry () const inline private
Definition at line 239 of file ObjectGuid.h.
 { return HasEntry(GetHigh()); }
References GetHigh(), and HasEntry().
Referenced by GetCounter(), GetEntry(), GetMaxCounter(), HasEntry(), and ToString().
HasEntry() [2/2]
static bool ObjectGuid::HasEntry (HighGuid high) inline static private
Definition at line 217 of file ObjectGuid.h.
         {
             switch (high)
             {
                 case HighGuid::Item:
                 case HighGuid::Player:
                 case HighGuid::DynamicObject:
                 case HighGuid::Corpse:
                 case HighGuid::Mo_Transport:
                 case HighGuid::Instance:
                 case HighGuid::Group:
                     return false;
                 case HighGuid::GameObject:
                 case HighGuid::Transport:
                 case HighGuid::Unit:
                 case HighGuid::Pet:
                 case HighGuid::Vehicle:
                 default:
                     return true;
             }
         }
References Corpse, DynamicObject, GameObject, Group, Instance, Item, Mo_Transport, Pet, Player, Transport, Unit, and Vehicle.
IsAnyTypeCreature()
bool ObjectGuid::IsAnyTypeCreature () const inline
Definition at line 169 of file ObjectGuid.h.
 { return IsCreature() || IsPet() || IsVehicle(); }
References IsCreature(), IsPet(), and IsVehicle().
Referenced by WorldSession::CanOpenMailBox(), and IsUnit().
IsAnyTypeGameObject()
bool ObjectGuid::IsAnyTypeGameObject () const inline
Definition at line 178 of file ObjectGuid.h.
 { return IsGameObject() || IsTransport() || IsMOTransport(); }
References IsGameObject(), IsMOTransport(), and IsTransport().
IsCorpse()
bool ObjectGuid::IsCorpse () const inline
Definition at line 175 of file ObjectGuid.h.
 { return GetHigh() == HighGuid::Corpse; }
References Corpse, and GetHigh().
Referenced by WorldSession::DoLootRelease(), WorldSession::HandleAutostoreLootItemOpcode(), and Player::SendLoot().
IsCreature()
bool ObjectGuid::IsCreature () const inline
Definition at line 164 of file ObjectGuid.h.
 { return GetHigh() == HighGuid::Unit; }
References GetHigh(), and Unit.
Referenced by WorldSession::HandleEjectPassenger(), IsAnyTypeCreature(), IsCreatureOrPet(), and IsCreatureOrVehicle().
IsCreatureOrPet()
bool ObjectGuid::IsCreatureOrPet () const inline
Definition at line 167 of file ObjectGuid.h.
 { return IsCreature() || IsPet(); }
References IsCreature(), and IsPet().
IsCreatureOrVehicle()
bool ObjectGuid::IsCreatureOrVehicle () const inline
Definition at line 168 of file ObjectGuid.h.
 { return IsCreature() || IsVehicle(); }
References IsCreature(), and IsVehicle().
Referenced by ObjectAccessor::GetCreatureOrPetOrVehicle(), WorldSession::HandleGossipSelectOptionOpcode(), and WorldSession::HandleLootOpcode().
IsDynamicObject()
bool ObjectGuid::IsDynamicObject () const inline
Definition at line 174 of file ObjectGuid.h.
 { return GetHigh() == HighGuid::DynamicObject; }
References DynamicObject, and GetHigh().
IsEmpty()
bool ObjectGuid::IsEmpty () const inline
Definition at line 163 of file ObjectGuid.h.
 { return _guid == 0; }
References _guid.
Referenced by NPCStaveQuestAI::AttackStart(), Aura::CanStackWith(), GetTypeName(), IsPlayer(), operator bool(), npc_simone::npc_simoneAI::Precious(), NPCStaveQuestAI::StorePlayerGUID(), NPCStaveQuestAI::UnitIsUnfair(), and lfg::LFGMgr::UpdateRaidBrowser().
IsGameObject()
bool ObjectGuid::IsGameObject () const inline
Definition at line 173 of file ObjectGuid.h.
 { return GetHigh() == HighGuid::GameObject; }
References GameObject, and GetHigh().
Referenced by WorldSession::CanOpenMailBox(), Spell::CheckEffectTarget(), WorldSession::DoLootRelease(), WorldSession::HandleAutostoreLootItemOpcode(), WorldSession::HandleGossipSelectOptionOpcode(), IsAnyTypeGameObject(), and Player::SendLoot().
IsGroup()
bool ObjectGuid::IsGroup () const inline
Definition at line 180 of file ObjectGuid.h.
 { return GetHigh() == HighGuid::Group; }
References GetHigh(), and Group.
Referenced by lfg::LFGMgr::_LoadFromDB(), lfg::LFGMgr::_SaveToDB(), lfg::LFGMgr::GetOldState(), lfg::LFGMgr::GetQueue(), lfg::LFGMgr::GetState(), lfg::LFGMgr::inLfgDungeonMap(), lfg::LFGMgr::IsLfgGroup(), lfg::LFGMgr::JoinLfg(), lfg::LFGMgr::LeaveAllLfgQueues(), lfg::LFGMgr::LeaveLfg(), lfg::LFGMgr::RestoreState(), and lfg::LFGMgr::SetState().
IsInstance()
bool ObjectGuid::IsInstance () const inline
Definition at line 179 of file ObjectGuid.h.
 { return GetHigh() == HighGuid::Instance; }
References GetHigh(), and Instance.
IsItem()
bool ObjectGuid::IsItem () const inline
Definition at line 172 of file ObjectGuid.h.
 { return GetHigh() == HighGuid::Item; }
References GetHigh(), and Item.
Referenced by WorldSession::DoLootRelease(), WorldSession::HandleAutostoreLootItemOpcode(), WorldSession::HandleGossipSelectOptionOpcode(), WorldSession::HandleLootMoneyOpcode(), and Player::SendLoot().
IsMOTransport()
bool ObjectGuid::IsMOTransport () const inline
Definition at line 177 of file ObjectGuid.h.
 { return GetHigh() == HighGuid::Mo_Transport; }
References GetHigh(), and Mo_Transport.
Referenced by IsAnyTypeGameObject(), and Player::SetClientControl().
IsPet()
bool ObjectGuid::IsPet () const inline
Definition at line 165 of file ObjectGuid.h.
 { return GetHigh() == HighGuid::Pet; }
References GetHigh(), and Pet.
Referenced by ObjectAccessor::GetCreatureOrPetOrVehicle(), ObjectAccessor::GetUnit(), IsAnyTypeCreature(), IsCreatureOrPet(), and ToString().
IsPlayer()
bool ObjectGuid::IsPlayer () const inline
Definition at line 170 of file ObjectGuid.h.
 { return !IsEmpty() && GetHigh() == HighGuid::Player; }
References GetHigh(), IsEmpty(), and Player.
Referenced by SmartAI::AssistPlayerInCombat(), npc_living_mojo::npc_living_mojoAI::AttackStart(), npc_warden_mellichar::npc_warden_mellicharAI::DamageTaken(), boss_thorim_start_npcs::boss_thorim_start_npcsAI::DamageTaken(), Unit::DealDamage(), Spell::DoAllEffectOnTarget(), SmartAI::EnterEvadeMode(), Unit::GetCharmerOrOwnerPlayerOrPlayerItself(), ObjectAccessor::GetUnit(), WorldSession::HandleEjectPassenger(), gobject_commandscript::HandleGameObjectDeleteCommand(), WorldSession::HandleGossipSelectOptionOpcode(), AuraEffect::HandleModInvisibility(), AuraEffect::HandleModInvisibilityDetect(), AuraEffect::HandleModStealth(), AuraEffect::HandleModStealthDetect(), AuraEffect::HandleModStealthLevel(), WorldSession::HandlePetSpellAutocastOpcode(), WorldSession::HandlePlayerLoginOpcode(), WorldSession::HandleRaidTargetUpdateOpcode(), Creature::HasMechanicTemplateImmunity(), Unit::IsCharmedOwnedByPlayerOrPlayer(), Unit::isInAccessiblePlaceFor(), Unit::isPossessedByPlayer(), IsUnit(), Unit::Kill(), KillRewarder::KillRewarder(), list_commandscript::ListAurasCommand(), instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::OnCreatureCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), PlayerOrPetCheck::operator()(), Puppet::Puppet(), ArenaSpectator::SendCommand_Aura(), ArenaSpectator::SendCommand_Cooldown(), ArenaSpectator::SendCommand_GUID(), ArenaSpectator::SendCommand_Spell(), ArenaSpectator::SendCommand_String(), ArenaSpectator::SendCommand_UInt32Value(), Unit::SetOwnerGUID(), Map::SummonCreature(), Acore::MessageDistDeliverer::Visit(), and Acore::MessageDistDelivererToHostile::Visit().
IsTransport()
bool ObjectGuid::IsTransport () const inline
Definition at line 176 of file ObjectGuid.h.
 { return GetHigh() == HighGuid::Transport; }
References GetHigh(), and Transport.
Referenced by IsAnyTypeGameObject().
IsUnit()
bool ObjectGuid::IsUnit () const inline
Definition at line 171 of file ObjectGuid.h.
 { return IsAnyTypeCreature() || IsPlayer(); }
References IsAnyTypeCreature(), and IsPlayer().
IsVehicle()
bool ObjectGuid::IsVehicle () const inline
Definition at line 166 of file ObjectGuid.h.
 { return GetHigh() == HighGuid::Vehicle; }
References GetHigh(), and Vehicle.
Referenced by IsAnyTypeCreature(), and IsCreatureOrVehicle().
MapSpecific()
ObjectGuid ObjectGuid::MapSpecific (HighGuid type, uint32 entry, LowType counter) static private
Definition at line 64 of file ObjectGuid.cpp.
 {
     return ObjectGuid(type, entry, counter);
 }
References ObjectGuid().
Referenced by Create().
operator bool()
ObjectGuid::operator bool () const inline
Definition at line 205 of file ObjectGuid.h.
 { return !IsEmpty(); }
References IsEmpty().
operator int64()
ObjectGuid::operator int64 () const private delete
operator!()
bool ObjectGuid::operator! () const inline
Definition at line 206 of file ObjectGuid.h.
 { return !(bool(*this)); }
operator!=()
bool ObjectGuid::operator!= (ObjectGuid const & guid) const inline
Definition at line 208 of file ObjectGuid.h.
 { return GetRawValue() != guid.GetRawValue(); }
References GetRawValue().
operator<()
bool ObjectGuid::operator< (ObjectGuid const & guid) const inline
Definition at line 209 of file ObjectGuid.h.
 { return GetRawValue() < guid.GetRawValue(); }
References GetRawValue().
operator<=()
bool ObjectGuid::operator<= (ObjectGuid const & guid) const inline
Definition at line 210 of file ObjectGuid.h.
 { return GetRawValue() <= guid.GetRawValue(); }
References GetRawValue().
operator==()
bool ObjectGuid::operator== (ObjectGuid const & guid) const inline
Definition at line 207 of file ObjectGuid.h.
 { return GetRawValue() == guid.GetRawValue(); }
References GetRawValue().
ReadAsPacked()
PackedGuidReader ObjectGuid::ReadAsPacked () inline
Definition at line 137 of file ObjectGuid.h.
 { return PackedGuidReader(*this); }
Referenced by WorldSession::HandleAcceptGrantLevel(), WorldSession::HandleCalendarAddEvent(), WorldSession::HandleCalendarEventModeratorStatus(), WorldSession::HandleCalendarEventRemoveInvite(), WorldSession::HandleCalendarEventStatus(), WorldSession::HandleChangeSeatsOnControlledVehicle(), WorldSession::HandleDismissControlledVehicle(), WorldSession::HandleEquipmentSetSave(), WorldSession::HandleEquipmentSetUse(), WorldSession::HandleForceSpeedChangeAck(), WorldSession::HandleGrantLevel(), WorldSession::HandleMoveHoverAck(), WorldSession::HandleMoveKnockBackAck(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveNotActiveMover(), WorldSession::HandleMoveRootAck(), WorldSession::HandleMoveSetCanFlyAckOpcode(), WorldSession::HandleMoveSplineDoneOpcode(), WorldSession::HandleMoveTeleportAck(), WorldSession::HandleMoveTimeSkippedOpcode(), WorldSession::HandleMoveUnRootAck(), WorldSession::HandleMoveWaterWalkAck(), WorldSession::HandleQueryInspectAchievements(), SpellCastTargets::Read(), and WorldSession::ReadMovementInfo().
Set()
void ObjectGuid::Set (uint64 guid) inline
Definition at line 139 of file ObjectGuid.h.
 { _guid = guid; }
References _guid.
Referenced by operator>>(), SpellCastTargets::SetTradeItemTarget(), and Acore::Hyperlinks::LinkTags::base_tag::StoreTo().
ToString()
std::string ObjectGuid::ToString () const
Definition at line 47 of file ObjectGuid.cpp.
 {
     std::ostringstream str;
     str << "GUID Full: 0x" << std::hex << std::setw(16) << std::setfill('0') << _guid << std::dec;
     str << " Type: " << GetTypeName();
     if (HasEntry())
         str << (IsPet() ? " Pet number: " : " Entry: ") << GetEntry() << " ";
     str << " Low: " << GetCounter();
     return str.str();
 }
References _guid, GetCounter(), GetEntry(), GetTypeName(), HasEntry(), and IsPet().
Referenced by Player::_ApplyItemMods(), Map::_GetScriptCreature(), Map::_GetScriptCreatureSourceOrTarget(), Map::_GetScriptPlayer(), Map::_GetScriptPlayerSourceOrTarget(), Map::_GetScriptUnit(), Map::_GetScriptWorldObject(), Player::_LoadItem(), Player::_LoadMailedItem(), Player::_SaveInventory(), Map::_ScriptProcessDoor(), PetAI::_stopAttack(), Player::_StoreItem(), Aura::_UnapplyForTarget(), FormationMgr::AddCreatureToGroup(), CreatureGroup::AddMember(), ArenaTeam::AddMember(), LootItemStorage::AddNewStoredLoot(), Vehicle::AddPassenger(), Map::AddPlayerToMap(), InstanceMap::AddPlayerToMap(), lfg::LFGQueue::AddQueueData(), Map::AddToMap(), lfg::LFGQueue::AddToNewQueue(), lfg::LFGQueue::AddToQueue(), Item::AddToUpdateQueueOf(), Unit::AttackerStateUpdate(), AuctionEntry::BuildAuctionInfo(), CalendarEvent::BuildCalendarMailSubject(), Player::BuildEnumData(), PathGenerator::BuildPointPath(), PathGenerator::BuildPolyPath(), Player::BuyItemFromVendorSlot(), PetAI::CanAttack(), Player::CanBankItem(), InstanceMap::CannotEnter(), BattlegroundMap::CannotEnter(), Player::CharmSpellInitialize(), lfg::LFGQueue::CheckCompatibility(), WorldSession::CheckStableMaster(), Guild::Create(), MotionTransport::CreateGOPassenger(), MotionTransport::CreateNPCPassenger(), lfg::LFGMgr::DecreaseKicksLeft(), Player::DestroyItemCount(), Vehicle::Dismiss(), ScriptedAI::DoPlaySoundToSet(), ScriptedAI::DoTeleportPlayer(), FlightPathMovementGenerator::DoUpdate(), Spell::EffectAddHonor(), Spell::EffectHeal(), Spell::EffectLearnSpell(), Spell::EffectUnlearnSpecialization(), lfg::LFGQueue::FindGroups(), lfg::LFGQueue::FindNewGroups(), PathGenerator::FindSmoothPath(), Spell::finish(), lfg::LFGMgr::FinishDungeon(), CreatureGroup::FormationReset(), lfg::LFGMgr::GetComment(), lfg::LFGMgr::GetDungeon(), lfg::LFGMgr::GetDungeonMapId(), lfg::LFGMgr::GetKicksLeft(), lfg::LFGMgr::GetLockedDungeons(), Battleground::GetObjectType(), lfg::LFGMgr::GetOldState(), WorldSession::GetPlayerInfo(), lfg::LFGMgr::GetRoles(), lfg::LFGMgr::GetSelectedDungeons(), lfg::LFGMgr::GetState(), account_commandscript::HandleAccountCreateCommand(), WorldSession::HandleActivateTaxiExpressOpcode(), WorldSession::HandleActivateTaxiOpcode(), spell_rog_deadly_poison::HandleAfterHit(), WorldSession::HandleAreaTriggerOpcode(), WorldSession::HandleAttackSwingOpcode(), WorldSession::HandleAuctionHelloOpcode(), WorldSession::HandleAuctionListBidderItems(), WorldSession::HandleAuctionListOwnerItemsEvent(), WorldSession::HandleAuctionPlaceBid(), WorldSession::HandleAuctionRemoveItem(), WorldSession::HandleAuctionSellItem(), WorldSession::HandleBankerActivateOpcode(), WorldSession::HandleBattlemasterHelloOpcode(), WorldSession::HandleBinderActivateOpcode(), WorldSession::HandleBusyTradeOpcode(), WorldSession::HandleBuybackItem(), WorldSession::HandleCalendarArenaTeam(), WorldSession::HandleCalendarComplain(), WorldSession::HandleCalendarCopyEvent(), WorldSession::HandleCalendarEventModeratorStatus(), WorldSession::HandleCalendarEventRemoveInvite(), WorldSession::HandleCalendarEventRsvp(), WorldSession::HandleCalendarEventSignup(), WorldSession::HandleCalendarEventStatus(), WorldSession::HandleCalendarGetCalendar(), WorldSession::HandleCalendarGetEvent(), WorldSession::HandleCalendarGetNumPending(), WorldSession::HandleCalendarGuildFilter(), WorldSession::HandleCalendarUpdateEvent(), WorldSession::HandleCharDeleteOpcode(), WorldSession::HandleCharEnum(), WorldSession::HandleComplainOpcode(), WorldSession::HandleCreatureQueryOpcode(), debug_commandscript::HandleDebugGetItemStateCommand(), debug_commandscript::HandleDebugHostileRefListCommand(), debug_commandscript::HandleDebugThreatListCommand(), WorldSession::HandleDismissCritter(), WorldSession::HandleDuelAcceptedOpcode(), WorldSession::HandleEjectPassenger(), WorldSession::HandleEquipmentSetUse(), WorldSession::HandleFarSightOpcode(), WorldSession::HandleGameObjectQueryOpcode(), WorldSession::HandleGameobjectReportUse(), WorldSession::HandleGameObjectUseOpcode(), WorldSession::HandleGossipHelloOpcode(), WorldSession::HandleGossipSelectOptionOpcode(), misc_commandscript::HandleGUIDCommand(), WorldSession::HandleGuildBankBuyTab(), WorldSession::HandleGuildBankDepositMoney(), WorldSession::HandleGuildBankerActivate(), WorldSession::HandleGuildBankQueryTab(), WorldSession::HandleGuildBankUpdateTab(), WorldSession::HandleGuildBankWithdrawMoney(), WorldSession::HandleIgnoreTradeOpcode(), WorldSession::HandleInspectArenaTeamsOpcode(), WorldSession::HandleInspectHonorStatsOpcode(), WorldSession::HandleInspectOpcode(), WorldSession::HandleInstanceLockResponse(), WorldSession::HandleItemTextQuery(), WorldSession::HandleLfgLeaveOpcode(), WorldSession::HandleLfgPartyLockInfoRequestOpcode(), WorldSession::HandleLfgPlayerLockInfoRequestOpcode(), WorldSession::HandleLfgSetBootVoteOpcode(), WorldSession::HandleLfgSetCommentOpcode(), WorldSession::HandleLfgSetRolesOpcode(), WorldSession::HandleMoveTeleportAck(), AuraEffect::HandleObsModPowerAuraTick(), WorldSession::HandleOpenItemOpcode(), WorldSession::HandleOpenWrappedItemCallback(), AuraEffect::HandlePeriodicDamageAurasTick(), AuraEffect::HandlePeriodicEnergizeAuraTick(), AuraEffect::HandlePeriodicHealAurasTick(), AuraEffect::HandlePeriodicHealthLeechAuraTick(), AuraEffect::HandlePeriodicManaLeechAuraTick(), WorldSession::HandlePetAbandon(), WorldSession::HandlePetAction(), WorldSession::HandlePetActionHelper(), WorldSession::HandlePetCancelAuraOpcode(), WorldSession::HandlePetCastSpellOpcode(), WorldSession::HandlePetitionBuyOpcode(), WorldSession::HandlePetitionDeclineOpcode(), WorldSession::HandlePetitionQueryOpcode(), WorldSession::HandlePetitionRenameOpcode(), WorldSession::HandlePetitionShowSignOpcode(), WorldSession::HandlePetitionSignOpcode(), WorldSession::HandlePetSetAction(), WorldSession::HandlePetSpellAutocastOpcode(), WorldSession::HandlePetStopAttack(), BattlefieldMgr::HandlePlayerEnterZone(), OutdoorPvPMgr::HandlePlayerEnterZone(), BattlefieldMgr::HandlePlayerLeaveZone(), OutdoorPvPMgr::HandlePlayerLeaveZone(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandlePlayerLoginOpcode(), WorldSession::HandleQuestgiverAcceptQuestOpcode(), WorldSession::HandleQuestgiverChooseRewardOpcode(), WorldSession::HandleQuestgiverCompleteQuest(), WorldSession::HandleQuestgiverHelloOpcode(), WorldSession::HandleQuestgiverQueryQuestOpcode(), WorldSession::HandleQuestgiverRequestRewardOpcode(), WorldSession::HandleQuestgiverStatusQueryOpcode(), WorldSession::HandleQuestLogRemoveQuest(), WorldSession::HandleRepairItemOpcode(), WorldSession::HandleSaveGuildEmblemOpcode(), WorldSession::HandleSellItemOpcode(), WorldSession::HandleSendMail(), WorldSession::HandleSetActionButtonOpcode(), WorldSession::HandleSetActiveMoverOpcode(), WorldSession::HandleSpiritHealerActivateOpcode(), WorldSession::HandleTabardVendorActivateOpcode(), WorldSession::HandleTalentWipeConfirmOpcode(), WorldSession::HandleTaxiQueryAvailableNodes(), WorldSession::HandleTrainerBuySpellOpcode(), WorldSession::HandleTurnInPetitionOpcode(), Vehicle::InstallAccessory(), lfg::LFGMgr::JoinLfg(), WorldSession::KickPlayer(), lfg::LFGMgr::LeaveLfg(), AuctionEntry::LoadFromDB(), Player::LoadFromDB(), ArenaTeam::LoadMembersFromDB(), WaypointMovementGenerator< Creature >::LoadPath(), LogCommandUsage(), WorldSession::LogoutPlayer(), MotionMaster::MoveCharge(), MotionMaster::MoveChase(), MotionMaster::MoveConfused(), MotionMaster::MoveFleeing(), MotionMaster::MoveFollow(), MotionMaster::MoveJump(), MotionMaster::MovePath(), MotionMaster::MovePoint(), MotionMaster::MoveRandom(), MotionMaster::MoveSeekAssistance(), MotionMaster::MoveSeekAssistanceDistract(), MotionMaster::MoveTargetedHome(), MotionMaster::MoveTaxiFlight(), lfg::LFGGroupScript::OnAddMember(), WaypointMovementGenerator< Creature >::OnArrived(), lfg::LFGGroupScript::OnChangeLeader(), lfg::LFGGroupScript::OnDisband(), lfg::LFGGroupScript::OnInviteMember(), lfg::LFGPlayerScript::OnMapChanged(), lfg::LFGGroupScript::OnRemoveMember(), MovementInfo::OutDebug(), SpellCastTargets::OutDebug(), Player::PossessSpellInitialize(), Player::PrettyPrintRequirementsAchievementsList(), SmartScript::ProcessAction(), Map::RemoveAllObjectsInRemoveList(), Vehicle::RemoveAllPassengers(), lfg::LFGQueue::RemoveFromCompatibles(), lfg::LFGQueue::RemoveFromNewQueue(), GameObject::RemoveFromOwner(), lfg::LFGQueue::RemoveFromQueue(), Item::RemoveFromUpdateQueueOf(), lfg::LFGMgr::RemoveGroupData(), Vehicle::RemovePassenger(), lfg::LFGMgr::RemoveProposal(), lfg::LFGQueue::RemoveQueueData(), Vehicle::Reset(), Player::ResetPetTalents(), Map::ScriptsProcess(), FactorySelector::selectAI(), FactorySelector::SelectGameObjectAI(), CreatureTextMgr::SendChat(), Map::SendInitSelf(), WorldSession::SendLfgBootProposalUpdate(), WorldSession::SendLfgRoleChosen(), WorldSession::SendLfgUpdateProposal(), WorldSession::SendListInventory(), Spell::SendLoot(), Unit::SendMeleeAttackStop(), WorldSession::SendPetitionQueryOpcode(), WorldSession::SendPetitionShowList(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), PlayerMenu::SendQuestGiverQuestList(), PlayerMenu::SendQuestGiverRequestItems(), PlayerMenu::SendQuestGiverStatus(), WorldSession::SendTaxiStatus(), WorldSession::SendTrainerList(), Unit::SetCharm(), Unit::SetCharmedBy(), lfg::LFGMgr::SetComment(), AchievementMgr::SetCriteriaProgress(), lfg::LFGMgr::SetDungeon(), lfg::LFGMgr::SetLockedDungeons(), Player::SetMover(), CreatureTextMgr::SetRepeatId(), lfg::LFGMgr::SetRoles(), lfg::LFGMgr::SetSelectedDungeons(), lfg::LFGMgr::SetState(), npc_escortAI::Start(), FollowerAI::StartFollow(), Player::StopCastingCharm(), Map::SwitchGridContainers(), Spell::TakeCastItem(), Channel::UnBan(), Vehicle::Uninstall(), PetAI::UpdateAI(), lfg::LFGMgr::UpdateProposal(), GameObject::Use(), validUtf8String(), and SpellEvent::~SpellEvent().
WriteAsPacked()
PackedGuid ObjectGuid::WriteAsPacked () const inline
Definition at line 318 of file ObjectGuid.h.
 { return PackedGuid(*this); }
Referenced by Player::BuildEnchantmentsInfoData(), AuraApplication::BuildUpdatePacket(), WorldSession::HandleCalendarGetCalendar(), WorldSession::HandleMoveKnockBackAck(), WorldSession::HandleMoveTimeSkippedOpcode(), WorldSession::HandleRequestPartyMemberStatsOpcode(), Movement::MoveSplineInit::Launch(), CalendarMgr::SendCalendarEvent(), CalendarMgr::SendCalendarEventInvite(), CalendarMgr::SendCalendarEventInviteAlert(), CalendarMgr::SendCalendarEventInviteRemove(), CalendarMgr::SendCalendarEventModeratorStatusAlert(), CalendarMgr::SendCalendarEventStatus(), Unit::SendChangeCurrentVictimOpcode(), WorldSession::SendEnchantmentLog(), Group::SendLooter(), WorldSession::SendNameQueryOpcode(), Unit::SendPeriodicAuraLog(), Unit::SendRemoveFromThreatListOpcode(), Movement::MoveSplineInit::Stop(), SpellCastTargets::Write(), and WorldSession::WriteMovementInfo().
Member Data Documentation
_guid
uint64 ObjectGuid::_guid private
Definition at line 251 of file ObjectGuid.h.
Referenced by Clear(), GetCounter(), GetEntry(), GetHigh(), GetRawValue(), IsEmpty(), Set(), and ToString().
Empty
ObjectGuid const ObjectGuid::Empty = ObjectGuid() static
Definition at line 122 of file ObjectGuid.h.
Referenced by Player::_LoadMailedItem(), Pet::_SaveAuras(), Unit::_TryStackingOrRefreshingExistingAura(), Unit::_UpdateSpells(), Unit::AttackStop(), spell_halion_marks::spell_halion_marks_AuraScript::BeforeDispel(), boss_bjarngrim::boss_bjarngrimAI::boss_bjarngrimAI(), boss_freya_summons::boss_freya_summonsAI::boss_freya_summonsAI(), boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::boss_yoggsaron_cloudAI(), GameObject::CastSpell(), lfg::LFGQueue::CheckCompatibility(), modify_commandscript::CheckModifySpeed(), lfg::Lfg5Guids::clear(), Player::clearResurrectRequestData(), Map::ConvertCorpseToBones(), Group::CountRollVote(), Group::CountTheRoll(), Item::Create(), Bag::Create(), Guild::DeleteMember(), CalendarMgr::DeleteOldEvents(), Player::DestroyItem(), ArenaTeam::Disband(), npc_ulduar_toasty_fire::npc_ulduar_toasty_fireAI::DoAction(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction(), brann_bronzebeard::brann_bronzebeardAI::DoAction(), boss_ambassador_hellmaw::boss_ambassador_hellmawAI::DoAction(), WorldSession::DoLootRelease(), tele_commandscript::DoNameTeleport(), Spell::DoSpellHitOnUnit(), instance_blackrock_spire::instance_blackrock_spireMapScript::Dragonspireroomcheck(), Player::DuelComplete(), Spell::EffectCharge(), lfg::Lfg5Guids::empty(), boss_novos::boss_novosAI::EnterCombat(), boss_illidari_council_memberAI::EnterEvadeMode(), BattlegroundWS::EventPlayerCapturedFlag(), BattlegroundEY::EventPlayerCapturedFlag(), BattlegroundEY::EventPlayerClickedOnFlag(), BattlegroundWS::EventPlayerClickedOnFlag(), BattlegroundEY::EventPlayerDroppedFlag(), BattlegroundWS::EventPlayerDroppedFlag(), ChatHandler::extractPlayerTarget(), Creature::FocusTarget(), Unit::GetCharm(), SpellCastTargets::GetCorpseTargetGUID(), Unit::GetFirstMinion(), Battleground::GetFlagPickerGUID(), World::GetGlobalPlayerGUID(), SpellCastTargets::GetGOTargetGUID(), Unit::GetGuardianPet(), npc_coren_direbrew_sisters::npc_coren_direbrew_sistersAI::GetGUID(), boss_lord_marrowgar::GetGUID(), SmartAI::GetGUID(), GameObjectAI::GetGUID(), UnitAI::GetGUID(), Object::GetGUID(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::GetGuidData(), instance_karazhan::instance_karazhan_InstanceMapScript::GetGuidData(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::GetGuidData(), instance_the_black_morass::instance_the_black_morass_InstanceMapScript::GetGuidData(), instance_zulfarrak::instance_zulfarrak_InstanceMapScript::GetGuidData(), instance_ulduar::instance_ulduar_InstanceMapScript::GetGuidData(), instance_steam_vault::instance_steam_vault_InstanceMapScript::GetGuidData(), instance_blood_furnace::instance_blood_furnace_InstanceMapScript::GetGuidData(), instance_shattered_halls::instance_shattered_halls_InstanceMapScript::GetGuidData(), instance_arcatraz::instance_arcatraz_InstanceMapScript::GetGuidData(), instance_sunwell_plateau::instance_sunwell_plateau_InstanceMapScript::GetGuidData(), instance_naxxramas::instance_naxxramas_InstanceMapScript::GetGuidData(), instance_halls_of_stone::instance_halls_of_stone_InstanceMapScript::GetGuidData(), instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::GetGuidData(), instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::GetGuidData(), instance_hyjal::instance_mount_hyjal_InstanceMapScript::GetGuidData(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::GetGuidData(), instance_temple_of_ahnqiraj::instance_temple_of_ahnqiraj_InstanceMapScript::GetGuidData(), instance_oculus::instance_oculus_InstanceMapScript::GetGuidData(), instance_utgarde_pinnacle::instance_utgarde_pinnacle_InstanceMapScript::GetGuidData(), instance_vault_of_archavon::instance_vault_of_archavon_InstanceMapScript::GetGuidData(), instance_violet_hold::instance_violet_hold_InstanceMapScript::GetGuidData(), instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::GetGuidData(), instance_the_eye::instance_the_eye_InstanceMapScript::GetGuidData(), instance_blackrock_spire::instance_blackrock_spireMapScript::GetGuidData(), instance_blackwing_lair::instance_blackwing_lair_InstanceMapScript::GetGuidData(), instance_molten_core::instance_molten_core_InstanceMapScript::GetGuidData(), instance_scarlet_monastery::instance_scarlet_monastery_InstanceMapScript::GetGuidData(), instance_scholomance::instance_scholomance_InstanceMapScript::GetGuidData(), instance_zulaman::instance_zulaman_InstanceMapScript::GetGuidData(), instance_ruins_of_ahnqiraj::instance_ruins_of_ahnqiraj_InstanceMapScript::GetGuidData(), instance_ahnkahet::instance_ahnkahet_InstanceScript::GetGuidData(), instance_ruby_sanctum::instance_ruby_sanctum_InstanceMapScript::GetGuidData(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::GetGuidData(), instance_forge_of_souls::instance_forge_of_souls_InstanceScript::GetGuidData(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::GetGuidData(), instance_pit_of_saron::instance_pit_of_saron_InstanceScript::GetGuidData(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::GetGuidData(), instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::GetGuidData(), instance_black_temple::instance_black_temple_InstanceMapScript::GetGuidData(), instance_the_slave_pens::instance_the_slave_pens_InstanceMapScript::GetGuidData(), instance_zulgurub::instance_zulgurub_InstanceMapScript::GetGuidData(), instance_onyxias_lair::instance_onyxias_lair_InstanceMapScript::GetGuidData(), instance_obsidian_sanctum::instance_obsidian_sanctum_InstanceMapScript::GetGuidData(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::GetGuidData(), instance_halls_of_lightning::instance_halls_of_lightning_InstanceMapScript::GetGuidData(), ZoneScript::GetGuidData(), ObjectMgr::GetLinkedRespawnGuid(), Group::GetMemberGUID(), InstanceScript::GetObjectGuid(), getOrphanGUID(), ChatHandler::GetPlayerGroupAndGUIDByName(), ObjectMgr::GetPlayerGUIDByName(), lfg::LFGMgr::GetQueue(), WorldObject::GetTransGUID(), Unit::GetTransGUID(), SpellCastTargets::GetUnitTargetGUID(), Guild::HandleAddNewRank(), WorldSession::HandleArenaTeamLeaderOpcode(), WorldSession::HandleArenaTeamRemoveOpcode(), WorldSession::HandleAuctionRemoveItem(), WorldSession::HandleAuctionSellItem(), spell_warl_seduction::HandleAuraApply(), spell_warl_demonic_aegis::HandleAuraApply(), AuraEffect::HandleAuraModShapeshift(), AuraEffect::HandleAuraModStateImmunity(), Aura::HandleAuraSpecificMods(), WorldSession::HandleBattlefieldListOpcode(), WorldSession::HandleBuybackItem(), WorldSession::HandleCalendarAddEvent(), WorldSession::HandleCancelAuraOpcode(), WorldSession::HandleCastSpellOpcode(), debug_commandscript::HandleDebugSendSellErrorCommand(), Unit::HandleDummyAuraProc(), ticket_commandscript::HandleGMTicketCloseByIdCommand(), ticket_commandscript::HandleGMTicketCompleteCommand(), WorldSession::HandleGroupSwapSubGroupOpcode(), honor_commandscript::HandleHonorAddCommand(), honor_commandscript::HandleHonorAddKillCommand(), honor_commandscript::HandleHonorUpdateCommand(), WorldSession::HandleLfgLeaveOpcode(), Guild::HandleMemberDepositMoney(), Guild::HandleMemberWithdrawMoney(), modify_commandscript::HandleModifyMountCommand(), spell_gen_mount::HandleMount(), npc_commandscript::HandleNpcWhisperCommand(), WorldSession::HandleOpenWrappedItemCallback(), WorldSession::HandlePetCancelAuraOpcode(), WorldSession::HandleQueryNextMailTime(), quest_commandscript::HandleQuestComplete(), Guild::HandleRemoveMember(), WorldSession::HandleRequestAccountData(), Guild::HandleSetBankTabInfo(), Guild::HandleSetLeader(), Guild::HandleSetMOTD(), Guild::HandleSetRankInfo(), cheat_commandscript::HandleTaxiCheatCommand(), tele_commandscript::HandleTeleGroupCommand(), titles_commandscript::HandleTitlesAddCommand(), titles_commandscript::HandleTitlesCurrentCommand(), titles_commandscript::HandleTitlesRemoveCommand(), titles_commandscript::HandleTitlesSetMaskCommand(), Guild::HandleUpdateMemberRank(), instance_violet_hold::instance_violet_hold_InstanceMapScript::InstanceCleanup(), TriggerAI::IsSummonedBy(), npc_bone_spike::npc_bone_spikeAI::IsSummonedBy(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::IsSummonedBy(), npc_risen_archmage::npc_risen_archmageAI::JustSummoned(), Channel::KickOrBan(), Channel::LeaveChannel(), lfg::Lfg5Guids::Lfg5Guids(), AuctionHouseMgr::LoadAuctionItems(), Player::LoadFromDB(), Bag::LoadFromDB(), Guild::BankTab::LoadItemFromDB(), LootItemStorage::LoadStoredLoot(), WorldSession::LogoutPlayer(), LootItem::LootItem(), spell_halion_twilight_realm::spell_halion_twilight_realm_AuraScript::OnApply(), spell_halion_leave_twilight_realm::spell_halion_leave_twilight_realm_AuraScript::OnApply(), spell_gen_animal_blood::OnApply(), spell_contagion_of_rot::OnApply(), spell_blood_queen_vampiric_bite::spell_blood_queen_vampiric_bite_SpellScript::OnCast(), instance_deadmines::instance_deadmines_InstanceMapScript::OnGameObjectCreate(), instance_shadowfang_keep::instance_shadowfang_keep_InstanceMapScript::OnGameObjectCreate(), instance_uldaman::instance_uldaman_InstanceMapScript::OnGameObjectCreate(), instance_blackfathom_deeps::instance_blackfathom_deeps_InstanceMapScript::OnGameObjectCreate(), instance_maraudon::instance_maraudon_InstanceMapScript::OnGameObjectCreate(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::OnGameObjectCreate(), instance_blackrock_spire::instance_blackrock_spireMapScript::OnGameObjectCreate(), instance_magisters_terrace::instance_magisters_terrace_InstanceMapScript::OnGameObjectCreate(), instance_hyjal::instance_mount_hyjal_InstanceMapScript::OnGameObjectCreate(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::OnGameObjectCreate(), instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::OnGameObjectCreate(), instance_violet_hold::instance_violet_hold_InstanceMapScript::OnGameObjectCreate(), instance_steam_vault::instance_steam_vault_InstanceMapScript::OnGameObjectCreate(), instance_shattered_halls::instance_shattered_halls_InstanceMapScript::OnGameObjectCreate(), instance_ahnkahet::instance_ahnkahet_InstanceScript::OnGameObjectCreate(), instance_utgarde_pinnacle::instance_utgarde_pinnacle_InstanceMapScript::OnGameObjectCreate(), go_palehoof_sphere::OnGossipHello(), go_chromaggus_lever::go_chromaggus_leverAI::OnGossipHello(), npc_aged_dying_ancient_kodo::OnGossipHello(), lfg::LFGPlayerScript::OnLogout(), spell_assembly_rune_of_summoning::spell_assembly_rune_of_summoning_AuraScript::OnPeriodic(), spell_halion_combustion_consumption::spell_halion_combustion_consumption_AuraScript::OnRemove(), lfg::LFGGroupScript::OnRemoveMember(), npc_vortex_ride::npc_vortex_rideAI::PassengerBoarded(), spell_love_in_air_periodic_perfumes::spell_love_in_air_periodic_perfumes_AuraScript::PeriodicTick(), Unit::PetSpellFail(), Spell::prepare(), Creature::ReleaseFocus(), Unit::RemoveAllGameObjects(), CalendarMgr::RemoveAllPlayerEventsAndInvites(), GameObject::RemoveFromOwner(), Unit::RemoveGameObject(), lfg::LFGMgr::RemoveGroupData(), Player::RemoveItem(), Bag::RemoveItem(), Player::RemoveItemFromBuyBackSlot(), BattlefieldWG::RemoveUpdateTenacity(), npc_black_knight_skeletal_gryphon::npc_black_knight_skeletal_gryphonAI::Reset(), boss_tyrannus::boss_tyrannusAI::Reset(), npc_mimirons_inferno::npc_mimirons_infernoAI::Reset(), boss_ambassador_hellmaw::boss_ambassador_hellmawAI::Reset(), Unit::ResetRedirectThreat(), BattlegroundEY::RespawnFlagAfterDrop(), BattlegroundWS::RespawnFlagAfterDrop(), Player::RewardPlayerAndGroupAtEvent(), npc_time_lost_proto_drake::npc_time_lost_proto_drakeAI::RollPath(), Channel::Say(), Map::ScriptCommandStart(), Map::ScriptsStart(), AuctionHouseMgr::SendAuctionExpiredMail(), Player::SendBuyError(), Spell::SendChannelUpdate(), Player::SendEquipError(), WorldSession::SendListInventory(), Player::SendLogXPGain(), Player::SendSellError(), Item::SetEnchantment(), Guild::BankTab::SetItem(), TradeData::SetItem(), Unit::SetMinion(), Channel::SetMode(), Channel::SetOwner(), TradeData::SetSpell(), Group::SetTargetIcon(), boss_ossirian::boss_ossirianAI::SpawnNextCrystal(), boss_devourer_of_souls::boss_devourer_of_soulsAI::SpellHitTarget(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::SummonChannelers(), Map::SummonCreature(), Player::TeleportTo(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::Update(), instance_violet_hold::instance_violet_hold_InstanceMapScript::Update(), boss_icehowl::boss_icehowlAI::UpdateAI(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI(), boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::UpdateAI(), boss_yoggsaron_llane::boss_yoggsaron_llaneAI::UpdateAI(), boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI::UpdateAI(), npc_grimstone::npc_grimstoneAI::UpdateEscortAI(), npc_cork_gizelton::npc_cork_gizeltonAI::UpdateEscortAI(), Group::UpdateLooterGuid(), and lfg::LFGMgr::UpdateRaidBrowser().
The documentation for this class was generated from the following files:
src/server/game/Entities/Object/ObjectGuid.h
src/server/game/Entities/Object/ObjectGuid.cpp