Azerotcore-wotlk: boss_eye_of_cthun::eye_of_cthunAI Struct Reference
boss_eye_of_cthun::eye_of_cthunAI Struct Reference
Public Member Functions
eye_of_cthunAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *) override
void SpawnEyeTentacle (float x, float y)
void UpdateAI (uint32 diff) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * instance
uint32 PhaseTimer
uint32 BeamTimer
uint32 EyeTentacleTimer
uint32 ClawTentacleTimer
uint32 DarkGlareTick
uint32 DarkGlareTickTimer
float DarkGlareAngle
bool ClockWise
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 158 of file boss_cthun.cpp.
Constructor & Destructor Documentation
eye_of_cthunAI()
boss_eye_of_cthun::eye_of_cthunAI::eye_of_cthunAI (Creature * creature) inline
Definition at line 160 of file boss_cthun.cpp.
                                            : ScriptedAI(creature)
         {
             instance = creature->GetInstanceScript();
             SetCombatMovement(false);
         }
References WorldObject::GetInstanceScript(), instance, and ScriptedAI::SetCombatMovement().
Member Function Documentation
DamageTaken()
void boss_eye_of_cthun::eye_of_cthunAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 409 of file boss_cthun.cpp.
         {
             switch (instance->GetData(DATA_CTHUN_PHASE))
             {
                 case PHASE_EYE_GREEN_BEAM:
                 case PHASE_EYE_RED_BEAM:
                     //Only if it will kill
                     if (damage < me->GetHealth())
                         return;
                     //Fake death in phase 0 or 1 (green beam or dark glare phase)
                     me->InterruptNonMeleeSpells(false);
                     //Remove Red coloration from c'thun
                     me->RemoveAurasDueToSpell(SPELL_RED_COLORATION);
                     //Reset to normal emote state and prevent select and attack
                     me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
                     //Remove Target field
                     me->SetTarget();
                     //Death animation/respawning;
                     instance->SetData(DATA_CTHUN_PHASE, PHASE_CTHUN_TRANSITION);
                     me->SetHealth(0);
                     damage = 0;
                     me->InterruptNonMeleeSpells(true);
                     me->RemoveAllAuras();
                     break;
                 case PHASE_CTHUN_DONE:
                     //Allow death here
                     return;
                 default:
                     //Prevent death in these phases
                     damage = 0;
                     return;
             }
         }
References DATA_CTHUN_PHASE, ZoneScript::GetData(), instance, Unit::InterruptNonMeleeSpells(), ScriptedAI::me, PHASE_CTHUN_DONE, PHASE_CTHUN_TRANSITION, PHASE_EYE_GREEN_BEAM, PHASE_EYE_RED_BEAM, Unit::RemoveAllAuras(), Unit::RemoveAurasDueToSpell(), ZoneScript::SetData(), Object::SetFlag(), Unit::SetHealth(), Creature::SetTarget(), SPELL_RED_COLORATION, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
EnterCombat()
void boss_eye_of_cthun::eye_of_cthunAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 214 of file boss_cthun.cpp.
         {
             DoZoneInCombat();
             instance->SetData(DATA_CTHUN_PHASE, PHASE_EYE_GREEN_BEAM);
         }
References DATA_CTHUN_PHASE, CreatureAI::DoZoneInCombat(), instance, PHASE_EYE_GREEN_BEAM, and ZoneScript::SetData().
Reset()
void boss_eye_of_cthun::eye_of_cthunAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 183 of file boss_cthun.cpp.
         {
             //Phase information
             PhaseTimer = 50000;                                 //First dark glare in 50 seconds
             //Eye beam phase 50 seconds
             BeamTimer = 3000;
             EyeTentacleTimer = 45000;                           //Always spawns 5 seconds before Dark Beam
             ClawTentacleTimer = 12500;                          //4 per Eye beam phase (unsure if they spawn during Dark beam)
             //Dark Beam phase 35 seconds (each tick = 1 second, 35 ticks)
             DarkGlareTick = 0;
             DarkGlareTickTimer = 1000;
             DarkGlareAngle = 0;
             ClockWise = false;
             //Reset flags
             me->RemoveAurasDueToSpell(SPELL_RED_COLORATION);
             me->RemoveAurasDueToSpell(SPELL_FREEZE_ANIM);
             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE | UNIT_FLAG_NON_ATTACKABLE);
             me->SetVisible(true);
             //Reset Phase
             instance->SetData(DATA_CTHUN_PHASE, PHASE_NOT_STARTED);
             //to avoid having a following void zone
             Creature* pPortal = me->FindNearestCreature(NPC_CTHUN_PORTAL, 10);
             if (pPortal)
                 pPortal->SetReactState(REACT_PASSIVE);
         }
References BeamTimer, ClawTentacleTimer, ClockWise, DarkGlareAngle, DarkGlareTick, DarkGlareTickTimer, DATA_CTHUN_PHASE, EyeTentacleTimer, WorldObject::FindNearestCreature(), instance, ScriptedAI::me, NPC_CTHUN_PORTAL, PHASE_NOT_STARTED, PhaseTimer, REACT_PASSIVE, Unit::RemoveAurasDueToSpell(), Object::RemoveFlag(), ZoneScript::SetData(), Creature::SetReactState(), Unit::SetVisible(), SPELL_FREEZE_ANIM, SPELL_RED_COLORATION, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
SpawnEyeTentacle()
void boss_eye_of_cthun::eye_of_cthunAI::SpawnEyeTentacle (float x, float y) inline
Definition at line 220 of file boss_cthun.cpp.
         {
             if (Creature* Spawned = DoSpawnCreature(NPC_EYE_TENTACLE, x, y, 0, 0, TEMPSUMMON_CORPSE_DESPAWN, 500))
                 if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
                     if (Spawned->AI())
                         Spawned->AI()->AttackStart(target);
         }
References ScriptedAI::DoSpawnCreature(), NPC_EYE_TENTACLE, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), and TEMPSUMMON_CORPSE_DESPAWN.
Referenced by UpdateAI().
UpdateAI()
void boss_eye_of_cthun::eye_of_cthunAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 228 of file boss_cthun.cpp.
         {
             //Check if we have a target
             if (!UpdateVictim())
                 return;
             uint32 currentPhase = instance->GetData(DATA_CTHUN_PHASE);
             if (currentPhase == PHASE_EYE_GREEN_BEAM || currentPhase == PHASE_EYE_RED_BEAM)
             {
                 // EyeTentacleTimer
                 if (EyeTentacleTimer <= diff)
                 {
                     //Spawn the 8 Eye Tentacles in the corret spots
                     SpawnEyeTentacle(0, 20);                //south
                     SpawnEyeTentacle(10, 10);               //south west
                     SpawnEyeTentacle(20, 0);                //west
                     SpawnEyeTentacle(10, -10);              //north west
                     SpawnEyeTentacle(0, -20);               //north
                     SpawnEyeTentacle(-10, -10);             //north east
                     SpawnEyeTentacle(-20, 0);               // east
                     SpawnEyeTentacle(-10, 10);              // south east
                     EyeTentacleTimer = 45000;
                 }
                 else EyeTentacleTimer -= diff;
             }
             switch (currentPhase)
             {
                 case PHASE_EYE_GREEN_BEAM:
                     //BeamTimer
                     if (BeamTimer <= diff)
                     {
                         //SPELL_GREEN_BEAM
                         if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
{
                             me->InterruptNonMeleeSpells(false);
                             DoCast(target, SPELL_GREEN_BEAM);
                             //Correctly update our target
                             me->SetTarget(target->GetGUID());
                         }
                         //Beam every 3 seconds
                         BeamTimer = 3000;
                     }
                     else BeamTimer -= diff;
                     //ClawTentacleTimer
                     if (ClawTentacleTimer <= diff)
                     {
                         if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
{
                             //Spawn claw tentacle on the random target
                             Creature* spawned = me->SummonCreature(NPC_CLAW_TENTACLE, *target, TEMPSUMMON_CORPSE_DESPAWN, 500);
                             if (spawned && spawned->AI())
{
                                 spawned->AI()->AttackStart(target);
                             }
                         }
                         //One claw tentacle every 12.5 seconds
                         ClawTentacleTimer = 12500;
                     }
                     else ClawTentacleTimer -= diff;
                     //PhaseTimer
                     if (PhaseTimer <= diff)
                     {
                         //Switch to Dark Beam
                         instance->SetData(DATA_CTHUN_PHASE, PHASE_EYE_RED_BEAM);
                         me->InterruptNonMeleeSpells(false);
                         me->SetReactState(REACT_PASSIVE);
                         //Remove any target
                         me->SetTarget();
                         //Select random target for dark beam to start on
                         if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
{
                             //Face our target
                             DarkGlareAngle = me->GetAngle(target);
                             DarkGlareTickTimer = 4000;
                             DarkGlareTick = 0;
                             ClockWise = RAND(true, false);
                         }
                         //Add red coloration to C'thun
                         DoCast(me, SPELL_RED_COLORATION, true);
                         //Freeze animation
                         DoCast(me, SPELL_FREEZE_ANIM);
                         me->StopMoving();
                         me->SetFacingTo(DarkGlareAngle);
                         me->SetOrientation(DarkGlareAngle);
                         //Darkbeam for 35 seconds
                         PhaseTimer = 35000;
                     }
                     else PhaseTimer -= diff;
                     break;
                 case PHASE_EYE_RED_BEAM:
                     if (DarkGlareTick < 35)
                     {
                         if (DarkGlareTickTimer <= diff)
{
                             me->StopMoving();
                             //Set angle and cast
                             if (ClockWise)
{
                                 me->SetFacingTo(DarkGlareAngle + DarkGlareTick * M_PI / 35);
                                 me->SetOrientation(DarkGlareAngle + DarkGlareTick * M_PI / 35);
                             }
                             else
{
                                 me->SetFacingTo(DarkGlareAngle - DarkGlareTick * M_PI / 35);
                                 me->SetOrientation(DarkGlareAngle - DarkGlareTick * M_PI / 35);
                             }
                             //Actual dark glare cast, maybe something missing here?
                             DoCast(me, SPELL_DARK_GLARE, false);
                             //Increase tick
                             ++DarkGlareTick;
                             //1 second per tick
                             DarkGlareTickTimer = 1000;
                         }
                         else DarkGlareTickTimer -= diff;
                     }
                     //PhaseTimer
                     if (PhaseTimer <= diff)
                     {
                         //Switch to Eye Beam
                         instance->SetData(DATA_CTHUN_PHASE, PHASE_EYE_GREEN_BEAM);
                         BeamTimer = 3000;
                         ClawTentacleTimer = 12500;              //4 per Eye beam phase (unsure if they spawn during Dark beam)
                         me->InterruptNonMeleeSpells(false);
                         //Remove Red coloration from c'thun
                         me->RemoveAurasDueToSpell(SPELL_RED_COLORATION);
                         me->RemoveAurasDueToSpell(SPELL_FREEZE_ANIM);
                         //set it back to aggressive
                         me->SetReactState(REACT_AGGRESSIVE);
                         //Eye Beam for 50 seconds
                         PhaseTimer = 50000;
                     }
                     else PhaseTimer -= diff;
                     break;
                 //Transition phase
                 case PHASE_CTHUN_TRANSITION:
                     //Remove any target
                     me->SetTarget();
                     me->SetHealth(0);
                     me->SetVisible(false);
                     break;
                 //Dead phase
                 case PHASE_CTHUN_DONE:
                     Creature* pPortal = me->FindNearestCreature(NPC_CTHUN_PORTAL, 10);
                     if (pPortal)
                         pPortal->DespawnOrUnsummon();
                     me->DespawnOrUnsummon();
                     break;
             }
         }
References Creature::AI(), UnitAI::AttackStart(), BeamTimer, ClawTentacleTimer, ClockWise, DarkGlareAngle, DarkGlareTick, DarkGlareTickTimer, DATA_CTHUN_PHASE, Creature::DespawnOrUnsummon(), UnitAI::DoCast(), EyeTentacleTimer, WorldObject::FindNearestCreature(), Position::GetAngle(), ZoneScript::GetData(), instance, Unit::InterruptNonMeleeSpells(), ScriptedAI::me, NPC_CLAW_TENTACLE, NPC_CTHUN_PORTAL, PHASE_CTHUN_DONE, PHASE_CTHUN_TRANSITION, PHASE_EYE_GREEN_BEAM, PHASE_EYE_RED_BEAM, PhaseTimer, RAND(), REACT_AGGRESSIVE, REACT_PASSIVE, Unit::RemoveAurasDueToSpell(), SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), ZoneScript::SetData(), Unit::SetFacingTo(), Unit::SetHealth(), Position::SetOrientation(), Creature::SetReactState(), Creature::SetTarget(), Unit::SetVisible(), SpawnEyeTentacle(), SPELL_DARK_GLARE, SPELL_FREEZE_ANIM, SPELL_GREEN_BEAM, SPELL_RED_COLORATION, Unit::StopMoving(), WorldObject::SummonCreature(), TEMPSUMMON_CORPSE_DESPAWN, and CreatureAI::UpdateVictim().
Member Data Documentation
BeamTimer
uint32 boss_eye_of_cthun::eye_of_cthunAI::BeamTimer
Definition at line 173 of file boss_cthun.cpp.
Referenced by Reset(), and UpdateAI().
ClawTentacleTimer
uint32 boss_eye_of_cthun::eye_of_cthunAI::ClawTentacleTimer
Definition at line 175 of file boss_cthun.cpp.
Referenced by Reset(), and UpdateAI().
ClockWise
bool boss_eye_of_cthun::eye_of_cthunAI::ClockWise
Definition at line 181 of file boss_cthun.cpp.
Referenced by Reset(), and UpdateAI().
DarkGlareAngle
float boss_eye_of_cthun::eye_of_cthunAI::DarkGlareAngle
Definition at line 180 of file boss_cthun.cpp.
Referenced by Reset(), and UpdateAI().
DarkGlareTick
uint32 boss_eye_of_cthun::eye_of_cthunAI::DarkGlareTick
Definition at line 178 of file boss_cthun.cpp.
Referenced by Reset(), and UpdateAI().
DarkGlareTickTimer
uint32 boss_eye_of_cthun::eye_of_cthunAI::DarkGlareTickTimer
Definition at line 179 of file boss_cthun.cpp.
Referenced by Reset(), and UpdateAI().
EyeTentacleTimer
uint32 boss_eye_of_cthun::eye_of_cthunAI::EyeTentacleTimer
Definition at line 174 of file boss_cthun.cpp.
Referenced by Reset(), and UpdateAI().
instance
InstanceScript* boss_eye_of_cthun::eye_of_cthunAI::instance
Definition at line 167 of file boss_cthun.cpp.
Referenced by DamageTaken(), EnterCombat(), eye_of_cthunAI(), Reset(), and UpdateAI().
PhaseTimer
uint32 boss_eye_of_cthun::eye_of_cthunAI::PhaseTimer
Definition at line 170 of file boss_cthun.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Kalimdor/TempleOfAhnQiraj/boss_cthun.cpp