Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/spin.h File Reference
spin.h File Reference
Classes
struct spin_t
Macros
#define SPIN_INITIALIZER {0U}
Functions
static void spin_cpu_spinwait ()
static void spin_adaptive (spin_t *spin)
Macro Definition Documentation
SPIN_INITIALIZER
#define SPIN_INITIALIZER {0U}
Definition at line 4 of file spin.h.
Function Documentation
spin_adaptive()
static void spin_adaptive (spin_t * spin) inline static
Definition at line 21 of file spin.h.
{
     volatile uint32_t i;
     if (spin->iteration < 5) {
         for (i = 0; i < (1U << spin->iteration); i++) {
             spin_cpu_spinwait();
         }
         spin->iteration++;
     } else {
 #ifdef _WIN32
         SwitchToThread();
 #else
         sched_yield();
 #endif
     }
 }
References spin_t::iteration, and spin_cpu_spinwait().
Referenced by extent_dss_extending_start(), and malloc_init_hard_needed().
spin_cpu_spinwait()
static void spin_cpu_spinwait () inline static
Definition at line 11 of file spin.h.
                     {
 #  if HAVE_CPU_SPINWAIT
     CPU_SPINWAIT;
 #  else
     volatile int x = 0;
     x = x;
 #  endif
 }
References G3D::x.
Referenced by malloc_mutex_lock_slow(), and spin_adaptive().