Azerotcore-wotlk: boss_stormcaller_brundir::boss_stormcaller_brundirAI Struct Reference
boss_stormcaller_brundir::boss_stormcaller_brundirAI Struct Reference
Public Member Functions
boss_stormcaller_brundirAI (Creature *c)
void Reset () override
void JustReachedHome () override
void EnterCombat (Unit *who) override
void UpdatePhase ()
void JustDied (Unit *) override
void KilledUnit (Unit *who) override
void SpellHit (Unit *, const SpellInfo *spellInfo) override
void SpellHitTarget (Unit *, const SpellInfo *spellInfo) override
uint32 GetData (uint32 param) const override
void MovementInform (uint32 type, uint32 point) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
InstanceScript * pInstance
uint32 _phase
bool _flyPhase
Unit * _flyTarget
uint32 _channelTimer
bool _stunnedAchievement
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 604 of file boss_assembly_of_iron.cpp.
Constructor & Destructor Documentation
boss_stormcaller_brundirAI()
boss_stormcaller_brundir::boss_stormcaller_brundirAI::boss_stormcaller_brundirAI (Creature * c) inline
Definition at line 606 of file boss_assembly_of_iron.cpp.
                                                 : ScriptedAI(c)
         {
             pInstance = c->GetInstanceScript();
         }
References mpq::c, and pInstance.
Member Function Documentation
EnterCombat()
void boss_stormcaller_brundir::boss_stormcaller_brundirAI::EnterCombat (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 646 of file boss_assembly_of_iron.cpp.
         {
             me->InterruptNonMeleeSpells(false);
             me->setActive(true);
             me->SetInCombatWithZone();
             events.ScheduleEvent(EVENT_ENRAGE, 900000);
             UpdatePhase();
             if (!pInstance)
                 return;
             for (uint8 i = 0; i < 3; ++i)
                 if (Creature* boss = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(DATA_STEELBREAKER + i)))
                     if (!boss->IsInCombat())
                         boss->AI()->AttackStart(who);
         }
References DATA_STEELBREAKER, EVENT_ENRAGE, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Unit::InterruptNonMeleeSpells(), ScriptedAI::me, pInstance, WorldObject::setActive(), Creature::SetInCombatWithZone(), and UpdatePhase().
GetData()
uint32 boss_stormcaller_brundir::boss_stormcaller_brundirAI::GetData (uint32 param) const inline override virtual
Reimplemented from UnitAI.
Definition at line 726 of file boss_assembly_of_iron.cpp.
         {
             if (param == DATA_BRUNDIR)
                 return _stunnedAchievement;
             return 0;
         }
References _stunnedAchievement, and DATA_BRUNDIR.
JustDied()
void boss_stormcaller_brundir::boss_stormcaller_brundirAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 687 of file boss_assembly_of_iron.cpp.
         {
             if (!pInstance)
                 return;
             me->NearTeleportTo(me->GetPositionX(), me->GetPositionY(), 427.5, me->GetOrientation());
             if (IsEncounterComplete(pInstance, me))
             {
                 pInstance->SetData(TYPE_ASSEMBLY, DONE);
                 me->CastSpell(me, 65195, true); // credit
                 Talk(SAY_BRUNDIR_ENCOUNTER_DEFEATED);
             }
             else
             {
                 RestoreAssemblyHealth(pInstance->GetGuidData(DATA_STEELBREAKER), pInstance->GetGuidData(DATA_MOLGEIM), me);
                 me->CastSpell(me, SPELL_SUPERCHARGE, true);
                 Talk(SAY_BRUNDIR_DEATH);
             }
         }
References Unit::CastSpell(), DATA_MOLGEIM, DATA_STEELBREAKER, DONE, InstanceScript::GetGuidData(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), IsEncounterComplete(), ScriptedAI::me, Unit::NearTeleportTo(), pInstance, RestoreAssemblyHealth(), SAY_BRUNDIR_DEATH, SAY_BRUNDIR_ENCOUNTER_DEFEATED, ZoneScript::SetData(), SPELL_SUPERCHARGE, CreatureAI::Talk(), and TYPE_ASSEMBLY.
JustReachedHome()
void boss_stormcaller_brundir::boss_stormcaller_brundirAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 640 of file boss_assembly_of_iron.cpp.
         {
             me->setActive(false);
             me->RemoveAllAuras();
         }
References ScriptedAI::me, Unit::RemoveAllAuras(), and WorldObject::setActive().
KilledUnit()
void boss_stormcaller_brundir::boss_stormcaller_brundirAI::KilledUnit (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 706 of file boss_assembly_of_iron.cpp.
         {
             if (who->GetTypeId() != TYPEID_PLAYER || urand(0, 2))
                 return;
             Talk(SAY_BRUNDIR_SLAY);
         }
References Object::GetTypeId(), SAY_BRUNDIR_SLAY, CreatureAI::Talk(), TYPEID_PLAYER, and urand().
MovementInform()
void boss_stormcaller_brundir::boss_stormcaller_brundirAI::MovementInform (uint32 type, uint32 point) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 734 of file boss_assembly_of_iron.cpp.
         {
             if (type == POINT_MOTION_TYPE && point == POINT_CHANNEL_STEELBREAKER)
                 me->CastSpell(me, SPELL_LIGHTNING_CHANNEL_PRE, true);
         }
References Unit::CastSpell(), ScriptedAI::me, POINT_CHANNEL_STEELBREAKER, POINT_MOTION_TYPE, and SPELL_LIGHTNING_CHANNEL_PRE.
Reset()
void boss_stormcaller_brundir::boss_stormcaller_brundirAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 620 of file boss_assembly_of_iron.cpp.
         {
             me->SetLootMode(0);
             RespawnAssemblyOfIron(pInstance, me);
             _channelTimer = 0;
             _phase = 0;
             _flyPhase = false;
             _flyTarget = nullptr;
             _stunnedAchievement = true;
             events.Reset();
             me->SetDisableGravity(false);
             me->SetRegeneratingHealth(true);
             me->SetReactState(REACT_AGGRESSIVE);
             if (pInstance)
                 pInstance->SetData(TYPE_ASSEMBLY, NOT_STARTED);
         }
References _channelTimer, _flyPhase, _flyTarget, _phase, _stunnedAchievement, ScriptedAI::me, NOT_STARTED, pInstance, REACT_AGGRESSIVE, RespawnAssemblyOfIron(), ZoneScript::SetData(), Creature::SetDisableGravity(), Creature::SetLootMode(), Creature::SetReactState(), Creature::SetRegeneratingHealth(), and TYPE_ASSEMBLY.
SpellHit()
void boss_stormcaller_brundir::boss_stormcaller_brundirAI::SpellHit (Unit * , const SpellInfo * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 714 of file boss_assembly_of_iron.cpp.
         {
             if (spellInfo->Id == SPELL_SUPERCHARGE)
                 UpdatePhase();
         }
References SpellInfo::Id, SPELL_SUPERCHARGE, and UpdatePhase().
SpellHitTarget()
void boss_stormcaller_brundir::boss_stormcaller_brundirAI::SpellHitTarget (Unit * , const SpellInfo * spellInfo) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 720 of file boss_assembly_of_iron.cpp.
         {
             if (spellInfo->Id == SPELL_CHAIN_LIGHTNING || spellInfo->Id == uint32(RAID_MODE(61916, 63482))) // Lightning Whirl triggered
                 _stunnedAchievement = false;
         }
References _stunnedAchievement, SpellInfo::Id, ScriptedAI::RAID_MODE(), and SPELL_CHAIN_LIGHTNING.
UpdateAI()
void boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 740 of file boss_assembly_of_iron.cpp.
         {
             if (!me->IsInCombat() && me->GetReactState() == REACT_AGGRESSIVE)
             {
                 _channelTimer += diff;
                 if (_channelTimer >= 10000)
                 {
                     _channelTimer = 0;
                     float o = urand(0, 5) * M_PI / 3.0f;
                     me->InterruptNonMeleeSpells(false);
                     me->GetMotionMaster()->MovePoint(POINT_CHANNEL_STEELBREAKER, 1587.18f + 10.0f * cos(o), 121.02f + 10.0f * sin(o), 427.3f);
                 }
             }
             if (!UpdateVictim())
                 return;
             if (_flyPhase)
             {
                 if (_flyTarget && me->GetDistance2d(_flyTarget) >= 6 )
                 {
                     //float speed = me->GetDistance(_flyTarget->GetPositionX(), _flyTarget->GetPositionY(), _flyTarget->GetPositionZ()+15) / (1500.0f * 0.001f);
                     me->SendMonsterMove(_flyTarget->GetPositionX(), _flyTarget->GetPositionY(), _flyTarget->GetPositionZ() + 15, 1500, SPLINEFLAG_FLYING);
                     me->SetPosition(_flyTarget->GetPositionX(), _flyTarget->GetPositionY(), _flyTarget->GetPositionZ(), _flyTarget->GetOrientation());
                 }
             }
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_CHAIN_LIGHTNING:
                     if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0))
                         me->CastSpell(target, SPELL_CHAIN_LIGHTNING, false);
                     events.RepeatEvent(urand(9000, 17000));
                     break;
                 case EVENT_OVERLOAD:
                     Talk(EMOTE_BRUNDIR_OVERLOAD);
                     me->CastSpell(me, SPELL_OVERLOAD, true);
                     events.RescheduleEvent(EVENT_OVERLOAD, urand(25000, 40000));
                     break;
                 case EVENT_LIGHTNING_WHIRL:
                     Talk(SAY_BRUNDIR_SPECIAL);
                     me->CastSpell(me, SPELL_LIGHTNING_WHIRL, true);
                     events.RepeatEvent(urand(10000, 25000));
                     break;
                 case EVENT_LIGHTNING_TENDRILS:
                     {
                         // Reschedule old
                         events.RepeatEvent(35000);
                         events.DelayEvents(18000);
                         Talk(SAY_BRUNDIR_FLIGHT);
                         _flyPhase = true;
                         _flyTarget = me->GetVictim();
                         me->SetRegeneratingHealth(false);
                         me->SetDisableGravity(true);
                         me->CombatStop();
                         me->StopMoving();
                         me->SetReactState(REACT_PASSIVE);
                         me->SetGuidValue(UNIT_FIELD_TARGET, ObjectGuid::Empty);
                         me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_STUNNED);
                         me->SendMonsterMove(_flyTarget->GetPositionX(), _flyTarget->GetPositionY(), _flyTarget->GetPositionZ() + 15, 1500, SPLINEFLAG_FLYING);
                         me->CastSpell(me, SPELL_LIGHTNING_TENDRILS, true);
                         me->CastSpell(me, 61883, true);
                         events.ScheduleEvent(EVENT_LIGHTNING_LAND, 16000);
                         break;
                     }
                 case EVENT_LIGHTNING_LAND:
                     {
                         float speed = me->GetDistance(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ()) / (1000.0f * 0.001f);
                         me->MonsterMoveWithSpeed(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), speed);
                         _flyPhase = false;
                         events.ScheduleEvent(EVENT_LAND_LAND, 1000);
                         break;
                     }
                 case EVENT_LAND_LAND:
                     me->SetCanFly(false);
                     me->SetReactState(REACT_AGGRESSIVE);
                     me->SetDisableGravity(false);
                     if (_flyTarget)
                         me->Attack(_flyTarget, false);
                     me->SetRegeneratingHealth(true);
                     _flyTarget = nullptr;
                     me->RemoveAura(SPELL_LIGHTNING_TENDRILS);
                     me->RemoveAura(61883);
                     DoResetThreat();
                     break;
                 case EVENT_ENRAGE:
                     Talk(SAY_BRUNDIR_BERSERK);
                     me->CastSpell(me, SPELL_BERSERK, true);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References _channelTimer, _flyPhase, _flyTarget, Unit::Attack(), Unit::CastSpell(), Unit::CombatStop(), diff(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DoResetThreat(), EMOTE_BRUNDIR_OVERLOAD, ObjectGuid::Empty, EVENT_CHAIN_LIGHTNING, EVENT_ENRAGE, EVENT_LAND_LAND, EVENT_LIGHTNING_LAND, EVENT_LIGHTNING_TENDRILS, EVENT_LIGHTNING_WHIRL, EVENT_OVERLOAD, WorldObject::GetDistance(), WorldObject::GetDistance2d(), Unit::GetMotionMaster(), Position::GetOrientation(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Creature::GetReactState(), Unit::GetVictim(), Unit::HasUnitState(), Unit::InterruptNonMeleeSpells(), Unit::IsInCombat(), M_PI, ScriptedAI::me, Unit::MonsterMoveWithSpeed(), MotionMaster::MovePoint(), POINT_CHANNEL_STEELBREAKER, REACT_AGGRESSIVE, REACT_PASSIVE, Unit::RemoveAura(), SAY_BRUNDIR_BERSERK, SAY_BRUNDIR_FLIGHT, SAY_BRUNDIR_SPECIAL, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), Unit::SendMonsterMove(), Creature::SetCanFly(), Creature::SetDisableGravity(), Object::SetFlag(), Object::SetGuidValue(), Creature::SetPosition(), Creature::SetReactState(), Creature::SetRegeneratingHealth(), SPELL_BERSERK, SPELL_CHAIN_LIGHTNING, SPELL_LIGHTNING_TENDRILS, SPELL_LIGHTNING_WHIRL, SPELL_OVERLOAD, SPLINEFLAG_FLYING, Unit::StopMoving(), CreatureAI::Talk(), UNIT_FIELD_FLAGS, UNIT_FIELD_TARGET, UNIT_FLAG_STUNNED, UNIT_STATE_CASTING, CreatureAI::UpdateVictim(), and urand().
UpdatePhase()
void boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdatePhase () inline
Definition at line 663 of file boss_assembly_of_iron.cpp.
         {
             if (_phase >= 3)
                 return;
             ++_phase;
             switch (_phase)
             {
                 case 1:
                     events.RescheduleEvent(EVENT_CHAIN_LIGHTNING, urand(9000, 17000));
                     events.RescheduleEvent(EVENT_OVERLOAD, urand(25000, 40000));
                     break;
                 case 2:
                     events.RescheduleEvent(EVENT_LIGHTNING_WHIRL, urand(20000, 40000));
                     break;
                 case 3:
                     me->ResetLootMode();
                     me->CastSpell(me, SPELL_STORMSHIELD, true);
                     events.RescheduleEvent(EVENT_LIGHTNING_TENDRILS, urand(15000, 16000));
                     break;
             }
         }
References _phase, Unit::CastSpell(), EVENT_CHAIN_LIGHTNING, EVENT_LIGHTNING_TENDRILS, EVENT_LIGHTNING_WHIRL, EVENT_OVERLOAD, ScriptedAI::me, Creature::ResetLootMode(), SPELL_STORMSHIELD, and urand().
Referenced by EnterCombat(), and SpellHit().
Member Data Documentation
_channelTimer
uint32 boss_stormcaller_brundir::boss_stormcaller_brundirAI::_channelTimer
Definition at line 616 of file boss_assembly_of_iron.cpp.
Referenced by Reset(), and UpdateAI().
_flyPhase
bool boss_stormcaller_brundir::boss_stormcaller_brundirAI::_flyPhase
Definition at line 614 of file boss_assembly_of_iron.cpp.
Referenced by Reset(), and UpdateAI().
_flyTarget
Unit* boss_stormcaller_brundir::boss_stormcaller_brundirAI::_flyTarget
Definition at line 615 of file boss_assembly_of_iron.cpp.
Referenced by Reset(), and UpdateAI().
_phase
uint32 boss_stormcaller_brundir::boss_stormcaller_brundirAI::_phase
Definition at line 613 of file boss_assembly_of_iron.cpp.
Referenced by Reset(), and UpdatePhase().
_stunnedAchievement
bool boss_stormcaller_brundir::boss_stormcaller_brundirAI::_stunnedAchievement
Definition at line 618 of file boss_assembly_of_iron.cpp.
Referenced by GetData(), Reset(), and SpellHitTarget().
events
EventMap boss_stormcaller_brundir::boss_stormcaller_brundirAI::events
Definition at line 611 of file boss_assembly_of_iron.cpp.
pInstance
InstanceScript* boss_stormcaller_brundir::boss_stormcaller_brundirAI::pInstance
Definition at line 612 of file boss_assembly_of_iron.cpp.
Referenced by boss_stormcaller_brundirAI(), EnterCombat(), JustDied(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_assembly_of_iron.cpp