Azerotcore-wotlk: VMAP::WorldModel Class Reference
VMAP::WorldModel Class Reference
#include <WorldModel.h>
Public Member Functions
WorldModel ()
void setGroupModels (std::vector< GroupModel > &models)
pass group models to WorldModel and create BIH. Passed vector is swapped with old geometry!
void setRootWmoID (uint32 id)
bool IntersectRay (const G3D::Ray &ray, float &distance, bool stopAtFirstHit) const
bool IntersectPoint (const G3D::Vector3 &p, const G3D::Vector3 &down, float &dist, AreaInfo &info) const
bool GetLocationInfo (const G3D::Vector3 &p, const G3D::Vector3 &down, float &dist, LocationInfo &info) const
bool writeFile (const std::string &filename)
bool readFile (const std::string &filename)
void GetGroupModels (std::vector< GroupModel > &outGroupModels)
Protected Attributes
uint32 RootWMOID {0}
std::vector< GroupModel > groupModels
BIH groupTree
Detailed Description
Holds a model (converted M2 or WMO) in its original coordinate space
Definition at line 103 of file WorldModel.h.
Constructor & Destructor Documentation
WorldModel()
VMAP::WorldModel::WorldModel () inline
Definition at line 106 of file WorldModel.h.
 { }
Member Function Documentation
GetGroupModels()
void VMAP::WorldModel::GetGroupModels (std::vector< GroupModel > & outGroupModels)
Definition at line 657 of file WorldModel.cpp.
     {
         outGroupModels = groupModels;
     }
References groupModels.
Referenced by MMAP::TerrainBuilder::loadVMap().
GetLocationInfo()
bool VMAP::WorldModel::GetLocationInfo (const G3D::Vector3 & p, const G3D::Vector3 & down, float & dist, LocationInfo & info) const
Definition at line 561 of file WorldModel.cpp.
     {
         if (groupModels.empty())
         {
             return false;
         }
         WModelAreaCallback callback(groupModels, down);
         groupTree.intersectPoint(p, callback);
         if (callback.hit != groupModels.end())
         {
             info.rootId   = RootWMOID;
             info.hitModel = &(*callback.hit);
             dist = callback.zDist;
             return true;
         }
         return false;
     }
References groupModels, groupTree, VMAP::WModelAreaCallback::hit, VMAP::LocationInfo::hitModel, BIH::intersectPoint(), VMAP::LocationInfo::rootId, RootWMOID, and VMAP::WModelAreaCallback::zDist.
Referenced by VMAP::ModelInstance::GetLocationInfo(), and GameObjectModel::GetLocationInfo().
IntersectPoint()
bool VMAP::WorldModel::IntersectPoint (const G3D::Vector3 & p, const G3D::Vector3 & down, float & dist, AreaInfo & info) const
Definition at line 540 of file WorldModel.cpp.
     {
         if (groupModels.empty())
         {
             return false;
         }
         WModelAreaCallback callback(groupModels, down);
         groupTree.intersectPoint(p, callback);
         if (callback.hit != groupModels.end())
         {
             info.rootId = RootWMOID;
             info.groupId = callback.hit->GetWmoID();
             info.flags = callback.hit->GetMogpFlags();
             info.result = true;
             dist = callback.zDist;
             return true;
         }
         return false;
     }
References VMAP::AreaInfo::flags, VMAP::AreaInfo::groupId, groupModels, groupTree, VMAP::WModelAreaCallback::hit, BIH::intersectPoint(), VMAP::AreaInfo::result, VMAP::AreaInfo::rootId, RootWMOID, and VMAP::WModelAreaCallback::zDist.
Referenced by VMAP::ModelInstance::intersectPoint(), and GameObjectModel::IntersectPoint().
IntersectRay()
bool VMAP::WorldModel::IntersectRay (const G3D::Ray & ray, float & distance, bool stopAtFirstHit) const
Definition at line 488 of file WorldModel.cpp.
     {
         // small M2 workaround, maybe better make separate class with virtual intersection funcs
         // in any case, there's no need to use a bound tree if we only have one submodel
         if (groupModels.size() == 1)
         {
             return groupModels[0].IntersectRay(ray, distance, stopAtFirstHit);
         }
         WModelRayCallBack isc(groupModels);
         groupTree.intersectRay(ray, isc, distance, stopAtFirstHit);
         return isc.hit;
     }
References G3D::distance(), groupModels, groupTree, VMAP::WModelRayCallBack::hit, and BIH::intersectRay().
Referenced by VMAP::ModelInstance::intersectRay(), and GameObjectModel::intersectRay().
readFile()
bool VMAP::WorldModel::readFile (const std::string & filename)
Definition at line 617 of file WorldModel.cpp.
     {
         FILE* rf = fopen(filename.c_str(), "rb");
         if (!rf)
         {
             return false;
         }
         bool result = true;
         uint32 chunkSize = 0;
         uint32 count = 0;
         char chunk[8];                          // Ignore the added magic header
         if (!readChunk(rf, chunk, VMAP_MAGIC, 8)) { result = false; }
         if (result && !readChunk(rf, chunk, "WMOD", 4)) { result = false; }
         if (result && fread(&chunkSize, sizeof(uint32), 1, rf) != 1) { result = false; }
         if (result && fread(&RootWMOID, sizeof(uint32), 1, rf) != 1) { result = false; }
         // read group models
         if (result && readChunk(rf, chunk, "GMOD", 4))
         {
             //if (fread(&chunkSize, sizeof(uint32), 1, rf) != 1) result = false;
             if (fread(&count, sizeof(uint32), 1, rf) != 1) { result = false; }
             if (result) { groupModels.resize(count); }
             //if (result && fread(&groupModels[0], sizeof(GroupModel), count, rf) != count) result = false;
             for (uint32 i = 0; i < count && result; ++i)
             {
                 result = groupModels[i].readFromFile(rf);
             }
             // read group BIH
             if (result && !readChunk(rf, chunk, "GBIH", 4)) { result = false; }
             if (result) { result = groupTree.readFromFile(rf); }
         }
         fclose(rf);
         return result;
     }
References count(), groupModels, groupTree, VMAP::readChunk(), BIH::readFromFile(), RootWMOID, and VMAP::VMAP_MAGIC.
Referenced by VMAP::VMapMgr2::acquireModelInstance().
setGroupModels()
void VMAP::WorldModel::setGroupModels (std::vector< GroupModel > & models)
pass group models to WorldModel and create BIH. Passed vector is swapped with old geometry!
Definition at line 469 of file WorldModel.cpp.
     {
         groupModels.swap(models);
         groupTree.build(groupModels, BoundsTrait<GroupModel>::GetBounds, 1);
     }
References BIH::build(), groupModels, and groupTree.
Referenced by VMAP::TileAssembler::convertRawFile().
setRootWmoID()
void VMAP::WorldModel::setRootWmoID (uint32 id) inline
Definition at line 110 of file WorldModel.h.
 { RootWMOID = id; }
References RootWMOID.
Referenced by VMAP::TileAssembler::convertRawFile().
writeFile()
bool VMAP::WorldModel::writeFile (const std::string & filename)
Definition at line 580 of file WorldModel.cpp.
     {
         FILE* wf = fopen(filename.c_str(), "wb");
         if (!wf)
         {
             return false;
         }
         uint32 chunkSize, count;
         bool result = fwrite(VMAP_MAGIC, 1, 8, wf) == 8;
         if (result && fwrite("WMOD", 1, 4, wf) != 4) { result = false; }
         chunkSize = sizeof(uint32) + sizeof(uint32);
         if (result && fwrite(&chunkSize, sizeof(uint32), 1, wf) != 1) { result = false; }
         if (result && fwrite(&RootWMOID, sizeof(uint32), 1, wf) != 1) { result = false; }
         // write group models
         count = groupModels.size();
         if (count)
         {
             if (result && fwrite("GMOD", 1, 4, wf) != 4) { result = false; }
             //chunkSize = sizeof(uint32)+ sizeof(GroupModel)*count;
             //if (result && fwrite(&chunkSize, sizeof(uint32), 1, wf) != 1) result = false;
             if (result && fwrite(&count, sizeof(uint32), 1, wf) != 1) { result = false; }
             for (uint32 i = 0; i < groupModels.size() && result; ++i)
             {
                 result = groupModels[i].writeToFile(wf);
             }
             // write group BIH
             if (result && fwrite("GBIH", 1, 4, wf) != 4) { result = false; }
             if (result) { result = groupTree.writeToFile(wf); }
         }
         fclose(wf);
         return result;
     }
References count(), groupModels, groupTree, RootWMOID, VMAP::VMAP_MAGIC, and BIH::writeToFile().
Referenced by VMAP::TileAssembler::convertRawFile().
Member Data Documentation
groupModels
std::vector<GroupModel> VMAP::WorldModel::groupModels protected
Definition at line 119 of file WorldModel.h.
Referenced by GetGroupModels(), GetLocationInfo(), IntersectPoint(), IntersectRay(), readFile(), setGroupModels(), and writeFile().
groupTree
BIH VMAP::WorldModel::groupTree protected
Definition at line 120 of file WorldModel.h.
Referenced by GetLocationInfo(), IntersectPoint(), IntersectRay(), readFile(), setGroupModels(), and writeFile().
RootWMOID
uint32 VMAP::WorldModel::RootWMOID {0} protected
Definition at line 118 of file WorldModel.h.
Referenced by GetLocationInfo(), IntersectPoint(), readFile(), setRootWmoID(), and writeFile().
The documentation for this class was generated from the following files:
src/common/Collision/Models/WorldModel.h
src/common/Collision/Models/WorldModel.cpp