Azerotcore-wotlk: PointMovementGenerator< T > Class Template Reference
PointMovementGenerator< T > Class Template Reference
#include <PointMovementGenerator.h>
Public Member Functions
PointMovementGenerator (uint32 _id, float _x, float _y, float _z, float _speed=0.0f, float orientation=0.0f, const Movement::PointsArray *_path=nullptr, bool generatePath=false, bool forceDestination=false, ObjectGuid chargeTargetGUID=ObjectGuid::Empty)
void DoInitialize (T *)
void DoFinalize (T *)
void DoReset (T *)
bool DoUpdate (T *, uint32)
void MovementInform (T *)
void unitSpeedChanged ()
MovementGeneratorType GetMovementGeneratorType ()
bool GetDestination (float &x, float &y, float &z) const
Public Member Functions inherited from MovementGeneratorMedium< T, PointMovementGenerator< T > >
void Initialize (Unit *u) override
void Finalize (Unit *u) override
void Reset (Unit *u) override
bool Update (Unit *u, uint32 time_diff) override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual uint32 GetSplineId () const
virtual bool GetResetPosition (float &, float &, float &)
Private Attributes
uint32 id
float i_x
float i_y
float i_z
float speed
float i_orientation
bool i_recalculateSpeed
Movement::PointsArray m_precomputedPath
bool _generatePath
bool _forceDestination
ObjectGuid _chargeTargetGUID
Detailed Description
template<class T>
class PointMovementGenerator< T >
Definition at line 25 of file PointMovementGenerator.h.
Constructor & Destructor Documentation
PointMovementGenerator()
template<class T > PointMovementGenerator< T >::PointMovementGenerator (uint32 _id, float _x, float _y, float _z, float _speed = 0.0f, float orientation = 0.0f, const Movement::PointsArray * _path = nullptr, bool generatePath = false, bool forceDestination = false, ObjectGuid chargeTargetGUID = ObjectGuid::Empty) inline
Definition at line 28 of file PointMovementGenerator.h.
         : id(_id), i_x(_x), i_y(_y), i_z(_z), speed(_speed), i_orientation(orientation), _generatePath(generatePath), _forceDestination(forceDestination),
         _chargeTargetGUID(chargeTargetGUID)
     {
         if (_path)
             m_precomputedPath = *_path;
     }
References PointMovementGenerator< T >::m_precomputedPath.
Member Function Documentation
DoFinalize()
template<class T > template void PointMovementGenerator< T >::DoFinalize (T *)
Definition at line 147 of file PointMovementGenerator.cpp.
 {
     unit->ClearUnitState(UNIT_STATE_ROAMING | UNIT_STATE_ROAMING_MOVE);
     if (id == EVENT_CHARGE)
     {
         unit->ClearUnitState(UNIT_STATE_CHARGING);
         if (Unit* target = ObjectAccessor::GetUnit(*unit, _chargeTargetGUID))
         {
             unit->Attack(target, true);
         }
     }
     if (unit->movespline->Finalized())
         MovementInform(unit);
 }
References EVENT_CHARGE, ObjectAccessor::GetUnit(), UNIT_STATE_CHARGING, UNIT_STATE_ROAMING, and UNIT_STATE_ROAMING_MOVE.
DoInitialize()
template<class T > template void PointMovementGenerator< T >::DoInitialize (T *)
Definition at line 29 of file PointMovementGenerator.cpp.
 {
     if (unit->HasUnitState(UNIT_STATE_NOT_MOVE) || unit->IsMovementPreventedByCasting())
     {
         // the next line is to ensure that a new spline is created in DoUpdate() once the unit is no longer rooted/stunned
         // todo: rename this flag to something more appropriate since it is set to true even without speed change now.
         i_recalculateSpeed = true;
         return;
     }
     if (!unit->IsStopped())
         unit->StopMoving();
     unit->AddUnitState(UNIT_STATE_ROAMING | UNIT_STATE_ROAMING_MOVE);
     if (id == EVENT_CHARGE)
     {
         unit->AddUnitState(UNIT_STATE_CHARGING);
     }
     i_recalculateSpeed = false;
     Movement::MoveSplineInit init(unit);
     if (m_precomputedPath.size() > 2) // pussywizard: for charge
         init.MovebyPath(m_precomputedPath);
     else if (_generatePath)
     {
         PathGenerator path(unit);
         bool result = path.CalculatePath(i_x, i_y, i_z, _forceDestination);
         if (result && !(path.GetPathType() & PATHFIND_NOPATH) && path.GetPath().size() > 2)
         {
             m_precomputedPath = path.GetPath();
             init.MovebyPath(m_precomputedPath);
         }
         else
         {
             // Xinef: fix strange client visual bug, moving on z coordinate only switches orientation by 180 degrees (visual only)
             if (G3D::fuzzyEq(unit->GetPositionX(), i_x) && G3D::fuzzyEq(unit->GetPositionY(), i_y))
             {
                 i_x += 0.2f * cos(unit->GetOrientation());
                 i_y += 0.2f * sin(unit->GetOrientation());
             }
             init.MoveTo(i_x, i_y, i_z, true);
         }
     }
     else
     {
         // Xinef: fix strange client visual bug, moving on z coordinate only switches orientation by 180 degrees (visual only)
         if (G3D::fuzzyEq(unit->GetPositionX(), i_x) && G3D::fuzzyEq(unit->GetPositionY(), i_y))
         {
             i_x += 0.2f * cos(unit->GetOrientation());
             i_y += 0.2f * sin(unit->GetOrientation());
         }
         init.MoveTo(i_x, i_y, i_z, true);
     }
     if (speed > 0.0f)
         init.SetVelocity(speed);
     if (i_orientation > 0.0f)
     {
         init.SetFacing(i_orientation);
     }
     init.Launch();
 }
References UNIT_STATE_NOT_MOVE.
DoReset()
template<class T > template void PointMovementGenerator< T >::DoReset (T *)
Definition at line 165 of file PointMovementGenerator.cpp.
 {
     if (!unit->IsStopped())
         unit->StopMoving();
     unit->AddUnitState(UNIT_STATE_ROAMING | UNIT_STATE_ROAMING_MOVE);
     if (id == EVENT_CHARGE)
     {
         unit->AddUnitState(UNIT_STATE_CHARGING);
     }
 }
References EVENT_CHARGE, UNIT_STATE_CHARGING, UNIT_STATE_ROAMING, and UNIT_STATE_ROAMING_MOVE.
DoUpdate()
template<class T > template bool PointMovementGenerator< T >::DoUpdate (T * , uint32)
Definition at line 96 of file PointMovementGenerator.cpp.
 {
     if (!unit)
         return false;
     if (unit->HasUnitState(UNIT_STATE_NOT_MOVE) || unit->IsMovementPreventedByCasting())
     {
         unit->StopMoving();
         return true;
     }
     unit->AddUnitState(UNIT_STATE_ROAMING_MOVE);
     if (i_recalculateSpeed && !unit->movespline->Finalized())
     {
         i_recalculateSpeed = false;
         Movement::MoveSplineInit init(unit);
         // xinef: speed changed during path execution, calculate remaining path and launch it once more
         if (m_precomputedPath.size())
         {
             uint32 offset = std::min(uint32(unit->movespline->_currentSplineIdx()), uint32(m_precomputedPath.size()));
             Movement::PointsArray::iterator offsetItr = m_precomputedPath.begin();
             std::advance(offsetItr, offset);
             m_precomputedPath.erase(m_precomputedPath.begin(), offsetItr);
             // restore 0 element (current position)
             m_precomputedPath.insert(m_precomputedPath.begin(), G3D::Vector3(unit->GetPositionX(), unit->GetPositionY(), unit->GetPositionZ()));
             if (m_precomputedPath.size() > 2)
                 init.MovebyPath(m_precomputedPath);
             else if (m_precomputedPath.size() == 2)
                 init.MoveTo(m_precomputedPath[1].x, m_precomputedPath[1].y, m_precomputedPath[1].z, true);
         }
         else
             init.MoveTo(i_x, i_y, i_z, true);
         if (speed > 0.0f) // Default value for point motion type is 0.0, if 0.0 spline will use GetSpeed on unit
             init.SetVelocity(speed);
         if (i_orientation > 0.0f)
         {
             init.SetFacing(i_orientation);
         }
         init.Launch();
     }
     return !unit->movespline->Finalized();
 }
References Movement::MoveSplineInit::Launch(), Movement::MoveSplineInit::MovebyPath(), Movement::MoveSplineInit::MoveTo(), Movement::MoveSplineInit::SetFacing(), Movement::MoveSplineInit::SetVelocity(), UNIT_STATE_NOT_MOVE, and UNIT_STATE_ROAMING_MOVE.
GetDestination()
template<class T > bool PointMovementGenerator< T >::GetDestination (float & x, float & y, float & z) const inline
Definition at line 48 of file PointMovementGenerator.h.
 { x = i_x; y = i_y; z = i_z; return true; }
References PointMovementGenerator< T >::i_x, PointMovementGenerator< T >::i_y, and PointMovementGenerator< T >::i_z.
GetMovementGeneratorType()
template<class T > MovementGeneratorType PointMovementGenerator< T >::GetMovementGeneratorType () inline virtual
Implements MovementGenerator.
Definition at line 46 of file PointMovementGenerator.h.
 { return POINT_MOTION_TYPE; }
References POINT_MOTION_TYPE.
MovementInform()
template<class T > void PointMovementGenerator< T >::MovementInform (T *)
Definition at line 178 of file PointMovementGenerator.cpp.
 {
 }
unitSpeedChanged()
template<class T > void PointMovementGenerator< T >::unitSpeedChanged () inline virtual
Reimplemented from MovementGenerator.
Definition at line 44 of file PointMovementGenerator.h.
 { i_recalculateSpeed = true; }
References PointMovementGenerator< T >::i_recalculateSpeed.
Member Data Documentation
_chargeTargetGUID
template<class T > ObjectGuid PointMovementGenerator< T >::_chargeTargetGUID private
Definition at line 58 of file PointMovementGenerator.h.
_forceDestination
template<class T > bool PointMovementGenerator< T >::_forceDestination private
Definition at line 57 of file PointMovementGenerator.h.
_generatePath
template<class T > bool PointMovementGenerator< T >::_generatePath private
Definition at line 56 of file PointMovementGenerator.h.
i_orientation
template<class T > float PointMovementGenerator< T >::i_orientation private
Definition at line 53 of file PointMovementGenerator.h.
i_recalculateSpeed
template<class T > bool PointMovementGenerator< T >::i_recalculateSpeed private
Definition at line 54 of file PointMovementGenerator.h.
Referenced by PointMovementGenerator< T >::unitSpeedChanged().
i_x
template<class T > float PointMovementGenerator< T >::i_x private
Definition at line 51 of file PointMovementGenerator.h.
Referenced by PointMovementGenerator< T >::GetDestination().
i_y
template<class T > float PointMovementGenerator< T >::i_y private
Definition at line 51 of file PointMovementGenerator.h.
Referenced by PointMovementGenerator< T >::GetDestination().
i_z
template<class T > float PointMovementGenerator< T >::i_z private
Definition at line 51 of file PointMovementGenerator.h.
Referenced by PointMovementGenerator< T >::GetDestination().
id
template<class T > uint32 PointMovementGenerator< T >::id private
Definition at line 50 of file PointMovementGenerator.h.
m_precomputedPath
template<class T > Movement::PointsArray PointMovementGenerator< T >::m_precomputedPath private
Definition at line 55 of file PointMovementGenerator.h.
Referenced by PointMovementGenerator< T >::PointMovementGenerator().
speed
template<class T > float PointMovementGenerator< T >::speed private
Definition at line 52 of file PointMovementGenerator.h.
The documentation for this class was generated from the following files:
src/server/game/Movement/MovementGenerators/PointMovementGenerator.h
src/server/game/Movement/MovementGenerators/PointMovementGenerator.cpp