Azerotcore-wotlk: boss_sjonnir::boss_sjonnirAI Struct Reference
boss_sjonnir::boss_sjonnirAI Struct Reference
Public Member Functions
boss_sjonnirAI (Creature *c)
void Reset () override
void EnterCombat (Unit *) override
void DoAction (int32 param) override
void UpdateAI (uint32 diff) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void ActivatePipe (uint8 side)
void SummonDwarfes (bool friendly)
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
EventMap events
SummonList summons
uint8 SummonPhase
uint8 SlugeCount
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 117 of file boss_sjonnir.cpp.
Constructor & Destructor Documentation
boss_sjonnirAI()
boss_sjonnir::boss_sjonnirAI::boss_sjonnirAI (Creature * c) inline
Definition at line 119 of file boss_sjonnir.cpp.
                                     : ScriptedAI(c), summons(me)
         {
             pInstance = c->GetInstanceScript();
         }
References WorldObject::GetInstanceScript(), and pInstance.
Member Function Documentation
ActivatePipe()
void boss_sjonnir::boss_sjonnirAI::ActivatePipe (uint8 side) inline
Definition at line 346 of file boss_sjonnir.cpp.
         {
             if (pInstance)
                 if (GameObject* pipe = me->GetMap()->GetGameObject(pInstance->GetGuidData(side == POS_GEN_RIGHT ? GO_RIGHT_PIPE : GO_LEFT_PIPE)))
                     pipe->SendCustomAnim(0);
         }
References Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), GO_LEFT_PIPE, GO_RIGHT_PIPE, ScriptedAI::me, pInstance, and POS_GEN_RIGHT.
Referenced by SummonDwarfes(), and UpdateAI().
DoAction()
void boss_sjonnir::boss_sjonnirAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 190 of file boss_sjonnir.cpp.
         {
             if (param == ACTION_SLUG_KILLED)
             {
                 SlugeCount++;
                 if (SlugeCount >= 5 && pInstance)
                     pInstance->SetData(DATA_SJONNIR_ACHIEVEMENT, true);
             }
         }
References ACTION_SLUG_KILLED, DATA_SJONNIR_ACHIEVEMENT, pInstance, ZoneScript::SetData(), and SlugeCount.
EnterCombat()
void boss_sjonnir::boss_sjonnirAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 164 of file boss_sjonnir.cpp.
         {
             Talk(SAY_AGGRO);
             events.ScheduleEvent(EVENT_CHECK_HEALTH, 1000);
             events.ScheduleEvent(EVENT_SHIELD, 14000 + rand() % 5000);
             events.ScheduleEvent(EVENT_CHAIN_LIGHTNING, 6000 + rand() % 6000);
             events.ScheduleEvent(EVENT_STATIC_CHARGE, 24000);
             events.ScheduleEvent(EVENT_LIGHTNING_RING, 25000 + rand() % 6000);
             events.ScheduleEvent(EVENT_SUMMON, 20000);
             events.ScheduleEvent(EVENT_SUMMON, 21500);
             events.ScheduleEvent(EVENT_SUMMON_SPEACH, 20000);
             if (pInstance)
             {
                 pInstance->SetData(BOSS_SJONNIR, IN_PROGRESS);
                 if (GameObject* doors = me->GetMap()->GetGameObject(pInstance->GetGuidData(GO_SJONNIR_DOOR)))
                     doors->SetGoState(GO_STATE_READY);
                 if (pInstance->GetData(BOSS_TRIBUNAL_OF_AGES) == DONE)
                     if (Creature* brann = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_BRANN)))
                         brann->AI()->DoAction(3);
             }
         }
References BOSS_SJONNIR, BOSS_TRIBUNAL_OF_AGES, DONE, EVENT_CHAIN_LIGHTNING, EVENT_CHECK_HEALTH, EVENT_LIGHTNING_RING, EVENT_SHIELD, EVENT_STATIC_CHARGE, EVENT_SUMMON, EVENT_SUMMON_SPEACH, ObjectAccessor::GetCreature(), ZoneScript::GetData(), Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), GO_SJONNIR_DOOR, GO_STATE_READY, IN_PROGRESS, ScriptedAI::me, NPC_BRANN, pInstance, SAY_AGGRO, ZoneScript::SetData(), and CreatureAI::Talk().
JustDied()
void boss_sjonnir::boss_sjonnirAI::JustDied (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 322 of file boss_sjonnir.cpp.
         {
             Talk(SAY_DEATH);
             summons.DespawnAll();
             if (pInstance)
             {
                 pInstance->SetData(BOSS_SJONNIR, DONE);
                 if (GameObject* sd = me->GetMap()->GetGameObject(pInstance->GetGuidData(GO_SJONNIR_DOOR)))
                     sd->SetGoState(GO_STATE_ACTIVE);
                 if (Creature* brann = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_BRANN)))
                     brann->AI()->DoAction(4);
             }
         }
References BOSS_SJONNIR, SummonList::DespawnAll(), DONE, ObjectAccessor::GetCreature(), Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), GO_SJONNIR_DOOR, GO_STATE_ACTIVE, ScriptedAI::me, NPC_BRANN, pInstance, SAY_DEATH, ZoneScript::SetData(), summons, and CreatureAI::Talk().
KilledUnit()
void boss_sjonnir::boss_sjonnirAI::KilledUnit (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 338 of file boss_sjonnir.cpp.
         {
             if (urand(0, 1))
                 return;
             Talk(SAY_SLAY);
         }
References SAY_SLAY, CreatureAI::Talk(), and urand().
Reset()
void boss_sjonnir::boss_sjonnirAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 131 of file boss_sjonnir.cpp.
         {
             events.Reset();
             summons.DespawnAll();
             SlugeCount = 0;
             SummonPhase = PHASE_SUMMON_UNFRIENDLY_DWARFES;
             if (pInstance)
             {
                 pInstance->SetData(BOSS_SJONNIR, NOT_STARTED);
                 pInstance->SetData(DATA_SJONNIR_ACHIEVEMENT, false);
                 me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                 if (pInstance->GetData(BOSS_TRIBUNAL_OF_AGES) == DONE)
                 {
                     me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
                     if (GameObject* doors = me->GetMap()->GetGameObject(pInstance->GetGuidData(GO_SJONNIR_DOOR)))
                         doors->SetGoState(GO_STATE_ACTIVE);
                     if (GameObject* console = me->GetMap()->GetGameObject( pInstance->GetGuidData(GO_SJONNIR_CONSOLE)))
                         console->SetGoState(GO_STATE_READY);
                     if (Creature* brann = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_BRANN)))
                     {
                         brann->setDeathState(JUST_DIED);
                         brann->Respawn();
                         brann->AI()->DoAction(5);
                     }
                 }
             }
         }
References BOSS_SJONNIR, BOSS_TRIBUNAL_OF_AGES, DATA_SJONNIR_ACHIEVEMENT, SummonList::DespawnAll(), DONE, ObjectAccessor::GetCreature(), ZoneScript::GetData(), Map::GetGameObject(), InstanceScript::GetGuidData(), WorldObject::GetMap(), GO_SJONNIR_CONSOLE, GO_SJONNIR_DOOR, GO_STATE_ACTIVE, GO_STATE_READY, JUST_DIED, ScriptedAI::me, NOT_STARTED, NPC_BRANN, PHASE_SUMMON_UNFRIENDLY_DWARFES, pInstance, Object::RemoveFlag(), ZoneScript::SetData(), Object::SetFlag(), SlugeCount, SummonPhase, summons, UNIT_FIELD_FLAGS, and UNIT_FLAG_NOT_SELECTABLE.
SummonDwarfes()
void boss_sjonnir::boss_sjonnirAI::SummonDwarfes (bool friendly) inline
Definition at line 353 of file boss_sjonnir.cpp.
         {
             if (friendly)
             {
                 for (int i = 0; i < 3; i++)
                 {
                     uint8 Pos = urand(POS_GEN_RIGHT, POS_GEN_LEFT);
                     if (Creature* dwarf = me->SummonCreature(NPC_DWARFES_FRIENDLY, RoomPosition[Pos].GetPositionX(), RoomPosition[Pos].GetPositionY(), RoomPosition[Pos].GetPositionZ(), 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 20000))
                     {
                         if (Player* plr = SelectTargetFromPlayerList(100.0f))
                             dwarf->SetFaction(plr->GetFaction());
                         ActivatePipe(Pos);
                         dwarf->AI()->AttackStart(me);
                         summons.Summon(dwarf);
                     }
                 }
             }
             else
             {
                 for (int i = 0; i < 2; i++)
                 {
                     uint8 Pos = urand(POS_GEN_RIGHT, POS_GEN_LEFT);
                     if (Creature* dwarf = me->SummonCreature(urand(0, 1) ? NPC_FORGED_IRON_TROGG : NPC_FORGED_IRON_DWARF, RoomPosition[Pos].GetPositionX(), RoomPosition[Pos].GetPositionY(), RoomPosition[Pos].GetPositionZ(), 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 20000))
                     {
                         ActivatePipe(Pos);
                         dwarf->SetInCombatWithZone();
                         summons.Summon(dwarf);
                     }
                 }
             }
         }
References ActivatePipe(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ScriptedAI::me, NPC_DWARFES_FRIENDLY, NPC_FORGED_IRON_DWARF, NPC_FORGED_IRON_TROGG, POS_GEN_LEFT, POS_GEN_RIGHT, RoomPosition, ScriptedAI::SelectTargetFromPlayerList(), SummonList::Summon(), WorldObject::SummonCreature(), summons, TEMPSUMMON_CORPSE_TIMED_DESPAWN, and urand().
Referenced by UpdateAI().
UpdateAI()
void boss_sjonnir::boss_sjonnirAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 200 of file boss_sjonnir.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case EVENT_CHECK_HEALTH:
                     {
                         if (SummonPhase == PHASE_SUMMON_UNFRIENDLY_DWARFES && HealthBelowPct(50))
{
                             SummonPhase = PHASE_SUMMON_OOZE;
                             events.CancelEvent(EVENT_SUMMON);
                             events.ScheduleEvent(EVENT_SUMMON, 0);
                             events.ScheduleEvent(EVENT_SUMMON, 1500);
                             if (pInstance)
                                 if (Creature* brann = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_BRANN)))
{
                                     brann->Yell("What in the name o' Madoran did THAT do? Oh! Wait: I just about got it...", LANG_UNIVERSAL);
                                     brann->PlayDirectSound(14276);
                                 }
                         }
                         if (HealthBelowPct(20))
{
                             if (Creature* brann = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_BRANN)))
{
                                 brann->Yell("Ha, that did it! Help's a-comin'! Take this, ya glowin' iron brute!", LANG_UNIVERSAL);
                                 brann->PlayDirectSound(14277);
                             }
                             SummonPhase = PHASE_SUMMON_FRIENDLY_DWARFES;
                             me->CastSpell(me, SPELL_FRENZY, false);
                             events.CancelEvent(EVENT_SUMMON);
                             events.ScheduleEvent(EVENT_SUMMON, 0);
                             break;
                         }
                         events.RepeatEvent(1000);
                         break;
                     }
                 case EVENT_SHIELD:
                     {
                         me->CastSpell(me, DUNGEON_MODE(SPELL_LIGHTNING_SHIELD, SPELL_LIGHTNING_SHIELD_H), false);
                         events.RepeatEvent(14000 + rand() % 5000);
                         break;
                     }
                 case EVENT_CHAIN_LIGHTNING:
                     {
                         if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 50.0f, true, 0))
                             me->CastSpell(target, DUNGEON_MODE(SPELL_CHAIN_LIGHTNING, SPELL_CHAIN_LIGHTNING_H), false);
                         events.RepeatEvent(6000 + rand() % 6000);
                         break;
                     }
                 case EVENT_STATIC_CHARGE:
                     {
                         if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 50.0f, true, 0))
                             me->CastSpell(target, DUNGEON_MODE(SPELL_STATIC_CHARGE, SPELL_STATIC_CHARGE_H), false);
                         events.RepeatEvent(20000);
                         break;
                     }
                 case EVENT_LIGHTNING_RING:
                     {
                         me->CastSpell(me, DUNGEON_MODE(SPELL_LIGHTNING_RING, SPELL_LIGHTNING_RING_H), false);
                         events.RepeatEvent(25000 + rand() % 6000);
                         events.DelayEvents(10000); // Channel duration
                         break;
                     }
                 case EVENT_SUMMON_SPEACH:
                     {
                         if (Creature* brann = ObjectAccessor::GetCreature(*me, pInstance->GetGuidData(NPC_BRANN)))
{
                             brann->Yell("This is a wee bit trickier that before... Oh, bloody--incomin'!", LANG_UNIVERSAL);
                             brann->PlayDirectSound(14275);
                         }
                         break;
                     }
                 case EVENT_SUMMON:
                     {
                         switch (SummonPhase)
{
                             case PHASE_SUMMON_UNFRIENDLY_DWARFES:
{
                                     SummonDwarfes(false);
                                     events.RepeatEvent(20000);
                                     break;
                                 }
                             case PHASE_SUMMON_OOZE:
{
                                     for (uint8 i = POS_GEN_RIGHT; i <= POS_GEN_LEFT; i++)
{
                                         if (Creature* ooze = me->SummonCreature(NPC_OOZE, RoomPosition[i].GetPositionX(), RoomPosition[i].GetPositionY(), RoomPosition[i].GetPositionZ(), 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 20000))
{
                                             ActivatePipe(i);
                                             ooze->GetMotionMaster()->MovePoint(0, RoomPosition[POS_ROOM_CENTER].GetPositionX(), RoomPosition[POS_ROOM_CENTER].GetPositionY(), RoomPosition[POS_ROOM_CENTER].GetPositionZ());
                                             summons.Summon(ooze);
                                         }
                                     }
                                     events.RepeatEvent(10000);
                                     break;
                                 }
                             case PHASE_SUMMON_FRIENDLY_DWARFES:
{
                                     SummonDwarfes(true);
                                     break;
                                 }
                         }
                         break;
                     }
             }
             DoMeleeAttackIfReady();
         }
References ActivatePipe(), Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), ScriptedAI::DUNGEON_MODE(), EVENT_CHAIN_LIGHTNING, EVENT_CHECK_HEALTH, EVENT_LIGHTNING_RING, EVENT_SHIELD, EVENT_STATIC_CHARGE, EVENT_SUMMON, EVENT_SUMMON_SPEACH, ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Unit::HasUnitState(), ScriptedAI::HealthBelowPct(), LANG_UNIVERSAL, ScriptedAI::me, NPC_BRANN, NPC_OOZE, PHASE_SUMMON_FRIENDLY_DWARFES, PHASE_SUMMON_OOZE, PHASE_SUMMON_UNFRIENDLY_DWARFES, pInstance, POS_GEN_LEFT, POS_GEN_RIGHT, POS_ROOM_CENTER, RoomPosition, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), SPELL_CHAIN_LIGHTNING, SPELL_CHAIN_LIGHTNING_H, SPELL_FRENZY, SPELL_LIGHTNING_RING, SPELL_LIGHTNING_RING_H, SPELL_LIGHTNING_SHIELD, SPELL_LIGHTNING_SHIELD_H, SPELL_STATIC_CHARGE, SPELL_STATIC_CHARGE_H, SummonList::Summon(), WorldObject::SummonCreature(), SummonDwarfes(), SummonPhase, summons, TEMPSUMMON_CORPSE_TIMED_DESPAWN, UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
events
EventMap boss_sjonnir::boss_sjonnirAI::events
Definition at line 125 of file boss_sjonnir.cpp.
pInstance
InstanceScript* boss_sjonnir::boss_sjonnirAI::pInstance
Definition at line 124 of file boss_sjonnir.cpp.
Referenced by ActivatePipe(), boss_sjonnirAI(), DoAction(), EnterCombat(), JustDied(), Reset(), and UpdateAI().
SlugeCount
uint8 boss_sjonnir::boss_sjonnirAI::SlugeCount
Definition at line 129 of file boss_sjonnir.cpp.
Referenced by DoAction(), and Reset().
SummonPhase
uint8 boss_sjonnir::boss_sjonnirAI::SummonPhase
Definition at line 128 of file boss_sjonnir.cpp.
Referenced by Reset(), and UpdateAI().
summons
SummonList boss_sjonnir::boss_sjonnirAI::summons
Definition at line 126 of file boss_sjonnir.cpp.
Referenced by JustDied(), Reset(), SummonDwarfes(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/HallsOfStone/boss_sjonnir.cpp