Azerotcore-wotlk: deps/mysqllite/mysys/default.c File Reference
default.c File Reference
#include "mysys_priv.h"
#include "m_string.h"
#include "m_ctype.h"
#include <my_dir.h>
Classes
struct handle_option_ctx
Macros
#define MAX_DEFAULT_DIRS 6
#define DEFAULT_DIRS_SIZE (MAX_DEFAULT_DIRS + 1) /* Terminate with NULL */
#define NEWLINE "\n"
Functions
static int handle_default_option (void *in_ctx, const char *group_name, const char *option)
static int search_default_file (Process_option_func func, void *func_ctx, const char *dir, const char *config_file)
static int search_default_file_with_ext (Process_option_func func, void *func_ctx, const char *dir, const char *ext, const char *config_file, int recursion_level)
static const char ** init_default_directories (MEM_ROOT *alloc)
static char * remove_end_comment (char *ptr)
static int fn_expand (const char *filename, char *result_buf)
int my_search_option_files (const char *conf_file, int *argc, char ***argv, uint *args_used, Process_option_func func, void *func_ctx, const char **default_directories)
int get_defaults_options (int argc, char **argv, char **defaults, char **extra_defaults, char **group_suffix)
int load_defaults (const char *conf_file, const char **groups, int *argc, char ***argv)
int my_load_defaults (const char *conf_file, const char **groups, int *argc, char ***argv, const char ***default_directories)
void free_defaults (char **argv)
static char * get_argument (const char *keyword, size_t kwlen, char *ptr, char *name, uint line)
void my_print_default_files (const char *conf_file)
void print_defaults (const char *conf_file, const char **groups)
static int add_directory (MEM_ROOT *alloc, const char *dir, const char **dirs)
Variables
const char * args_separator = "----args-separator----"
const char * my_defaults_file =0
const char * my_defaults_group_suffix =0
const char * my_defaults_extra_file =0
static char my_defaults_file_buffer [FN_REFLEN]
static char my_defaults_extra_file_buffer [FN_REFLEN]
static my_bool defaults_already_read = FALSE
static const char ** default_directories = NULL
static const char * f_extensions [] = { ".cnf", 0 }
Macro Definition Documentation
DEFAULT_DIRS_SIZE
#define DEFAULT_DIRS_SIZE (MAX_DEFAULT_DIRS + 1) /* Terminate with NULL */
Definition at line 79 of file default.c.
MAX_DEFAULT_DIRS
#define MAX_DEFAULT_DIRS 6
Definition at line 78 of file default.c.
NEWLINE
#define NEWLINE "\n"
Definition at line 87 of file default.c.
Function Documentation
add_directory()
static int add_directory (MEM_ROOT * alloc, const char * dir, const char ** dirs) static
Definition at line 1081 of file default.c.
 {
   char buf[FN_REFLEN];
   size_t len;
   char *p;
   my_bool err __attribute__((unused));
   len= normalize_dirname(buf, dir);
   if (!(p= strmake_root(alloc, buf, len)))
     return 1;  /* Failure */
   /* Should never fail if DEFAULT_DIRS_SIZE is correct size */
   err= array_append_string_unique(p, dirs, DEFAULT_DIRS_SIZE);
   DBUG_ASSERT(err == FALSE);
   return 0;
 }
References __attribute__, handle_option_ctx::alloc, array_append_string_unique(), DBUG_ASSERT, DEFAULT_DIRS_SIZE, FALSE, FN_REFLEN, normalize_dirname(), and strmake_root().
Referenced by init_default_directories().
fn_expand()
static int fn_expand (const char * filename, char * result_buf) static
Definition at line 158 of file default.c.
 {
   char dir[FN_REFLEN];
   const int flags= MY_UNPACK_FILENAME | MY_SAFE_PATH | MY_RELATIVE_PATH;
   DBUG_ENTER("fn_expand");
   DBUG_PRINT("enter", ("filename: %s, result_buf: 0x%lx",
                        filename, (unsigned long) result_buf));
   if (my_getwd(dir, sizeof(dir), MYF(0)))
     DBUG_RETURN(3);
   DBUG_PRINT("debug", ("dir: %s", dir));
   if (fn_format(result_buf, filename, dir, NULL, flags) == NULL)
     DBUG_RETURN(2);
   DBUG_PRINT("return", ("result: %s", result_buf));
   DBUG_RETURN(0);
 }
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, fn_format(), FN_REFLEN, my_getwd(), MY_RELATIVE_PATH, MY_SAFE_PATH, MY_UNPACK_FILENAME, MYF, and NULL.
Referenced by my_search_option_files().
free_defaults()
void free_defaults (char ** argv)
Definition at line 620 of file default.c.
 {
   MEM_ROOT ptr;
   memcpy(&ptr, ((char *) argv) - sizeof(ptr), sizeof(ptr));
   free_root(&ptr,MYF(0));
 }
References free_root(), memcpy, MYF, and ptr().
Referenced by mysql_read_default_options().
get_argument()
static char* get_argument (const char * keyword, size_t kwlen, char * ptr, char * name, uint line) static
Definition at line 665 of file default.c.
 {
   char *end;
   /* Skip over "include / includedir keyword" and following whitespace */
   for (ptr+= kwlen - 1;
        my_isspace(&my_charset_latin1, ptr[0]);
        ptr++)
   {}
   /*
     Trim trailing whitespace from directory name
     The -1 below is for the newline added by fgets()
     Note that my_isspace() is true for \r and \n
   */
   for (end= ptr + strlen(ptr) - 1;
        my_isspace(&my_charset_latin1, *(end - 1));
        end--)
   {}
   end[0]= 0;                                    /* Cut off end space */
   /* Print error msg if there is nothing after !include* directive */
   if (end <= ptr)
   {
     fprintf(stderr,
         "error: Wrong '!%s' directive in config file: %s at line %d\n",
         keyword, name, line);
     return 0;
   }
   return ptr;
 }
References fprintf(), my_charset_latin1, my_isspace, name, and ptr().
Referenced by search_default_file_with_ext().
get_defaults_options()
int get_defaults_options (int argc, char ** argv, char ** defaults, char ** extra_defaults, char ** group_suffix)
Definition at line 394 of file default.c.
 {
   int org_argc= argc, prev_argc= 0;
   *defaults= *extra_defaults= *group_suffix= 0;
   while (argc >= 2 && argc != prev_argc)
   {
     /* Skip program name or previously handled argument */
     argv++;
     prev_argc= argc;                            /* To check if we found */
     if (!*defaults && is_prefix(*argv,"--defaults-file="))
     {
       *defaults= *argv + sizeof("--defaults-file=")-1;
        argc--;
        continue;
     }
     if (!*extra_defaults && is_prefix(*argv,"--defaults-extra-file="))
     {
       *extra_defaults= *argv + sizeof("--defaults-extra-file=")-1;
       argc--;
       continue;
     }
     if (!*group_suffix && is_prefix(*argv, "--defaults-group-suffix="))
     {
       *group_suffix= *argv + sizeof("--defaults-group-suffix=")-1;
       argc--;
       continue;
     }
   }
   return org_argc - argc;
 }
References is_prefix().
Referenced by my_search_option_files().
handle_default_option()
static int handle_default_option (void * in_ctx, const char * group_name, const char * option) static
Definition at line 356 of file default.c.
 {
   char *tmp;
   struct handle_option_ctx *ctx= (struct handle_option_ctx *) in_ctx;
   if (!option)
     return 0;
   if (find_type((char *)group_name, ctx->group, 3))
   {
     if (!(tmp= alloc_root(ctx->alloc, strlen(option) + 1)))
       return 1;
     if (insert_dynamic(ctx->args, (uchar*) &tmp))
       return 1;
     strmov(tmp, option);
   }
   return 0;
 }
References handle_option_ctx::alloc, alloc_root(), handle_option_ctx::args, find_type(), handle_option_ctx::group, insert_dynamic(), and strmov().
Referenced by my_load_defaults(), and my_search_option_files().
init_default_directories()
static const char ** init_default_directories (MEM_ROOT * alloc) static
Create the list of default directories.
Parameters
alloc MEM_ROOT where the list of directories is stored
The directories searched, in order, are:
Windows: GetSystemWindowsDirectory()
Windows: GetWindowsDirectory()
Windows: C:/
Windows: Directory above where the executable is located
Unix: /etc/
Unix: /etc/mysql/
Unix: –sysconfdir=<path> (compile-time option)
ALL: getenv(DEFAULT_HOME_ENV)
ALL: –defaults-extra-file=<path> (run-time option)
Unix: ~/
On all systems, if a directory is already in the list, it will be moved to the end of the list. This avoids reading defaults files multiple times, while ensuring the correct precedence.
Return values
NULL Failure (out of memory, probably)
other Pointer to NULL-terminated array of default directories
Definition at line 1167 of file default.c.
 {
   const char **dirs;
   char *env;
   int errors= 0;
   dirs= (const char **)alloc_root(alloc, DEFAULT_DIRS_SIZE * sizeof(char *));
   if (dirs == NULL)
     return NULL;
   bzero((char *) dirs, DEFAULT_DIRS_SIZE * sizeof(char *));
 #ifdef __WIN__
   {
     char fname_buffer[FN_REFLEN];
     if (my_get_system_windows_directory(fname_buffer, sizeof(fname_buffer)))
       errors += add_directory(alloc, fname_buffer, dirs);
     if (GetWindowsDirectory(fname_buffer, sizeof(fname_buffer)))
       errors += add_directory(alloc, fname_buffer, dirs);
     errors += add_directory(alloc, "C:/", dirs);
     if (my_get_module_parent(fname_buffer, sizeof(fname_buffer)) != NULL)
       errors += add_directory(alloc, fname_buffer, dirs);
   }
 #else
   errors += add_directory(alloc, "/etc/", dirs);
   errors += add_directory(alloc, "/etc/mysql/", dirs);
 #if defined(DEFAULT_SYSCONFDIR)
   if (DEFAULT_SYSCONFDIR[0])
     errors += add_directory(alloc, DEFAULT_SYSCONFDIR, dirs);
 #endif /* DEFAULT_SYSCONFDIR */
 #endif
   if ((env= getenv(STRINGIFY_ARG(DEFAULT_HOME_ENV))))
     errors += add_directory(alloc, env, dirs);
   /* Placeholder for --defaults-extra-file=<path> */
   errors += add_directory(alloc, "", dirs);
 #if !defined(__WIN__)
   errors += add_directory(alloc, "~/", dirs);
 #endif
   return (errors > 0 ? NULL : dirs);
 }
References add_directory(), handle_option_ctx::alloc, alloc_root(), bzero, DEFAULT_DIRS_SIZE, mpq::errors, FN_REFLEN, NULL, and STRINGIFY_ARG.
Referenced by my_load_defaults(), and my_print_default_files().
load_defaults()
int load_defaults (const char * conf_file, const char ** groups, int * argc, char *** argv)
Definition at line 450 of file default.c.
 {
   return my_load_defaults(conf_file, groups, argc, argv, &default_directories);
 }
References default_directories, and my_load_defaults().
my_load_defaults()
int my_load_defaults (const char * conf_file, const char ** groups, int * argc, char *** argv, const char *** default_directories)
Definition at line 494 of file default.c.
 {
   DYNAMIC_ARRAY args;
   TYPELIB group;
   my_bool found_print_defaults= 0;
   uint args_used= 0;
   int error= 0;
   MEM_ROOT alloc;
   char *ptr,**res;
   struct handle_option_ctx ctx;
   const char **dirs;
   DBUG_ENTER("load_defaults");
   init_alloc_root(&alloc,512,0);
   if ((dirs= init_default_directories(&alloc)) == NULL)
     goto err;
   /*
     Check if the user doesn't want any default option processing
     --no-defaults is always the first option
   */
   if (*argc >= 2 && !strcmp(argv[0][1],"--no-defaults"))
   {
     /* remove the --no-defaults argument and return only the other arguments */
     uint i;
     if (!(ptr=(char*) alloc_root(&alloc,sizeof(alloc)+
                  (*argc + 1)*sizeof(char*))))
       goto err;
     res= (char**) (ptr+sizeof(alloc));
     res[0]= **argv;             /* Copy program name */
     /* set arguments separator */
     res[1]= (char *)args_separator;
     for (i=2 ; i < (uint) *argc ; i++)
       res[i]=argv[0][i];
     res[i]=0;                   /* End pointer */
     *argv=res;
     *(MEM_ROOT*) ptr= alloc;            /* Save alloc root for free */
     if (default_directories)
       *default_directories= dirs;
     DBUG_RETURN(0);
   }
   group.count=0;
   group.name= "defaults";
   group.type_names= groups;
   for (; *groups ; groups++)
     group.count++;
   if (my_init_dynamic_array(&args, sizeof(char*),*argc, 32))
     goto err;
   ctx.alloc= &alloc;
   ctx.args= &args;
   ctx.group= &group;
   if ((error= my_search_option_files(conf_file, argc, argv, &args_used,
                                      handle_default_option, (void *) &ctx,
                                      dirs)))
   {
     free_root(&alloc,MYF(0));
     DBUG_RETURN(error);
   }
   /*
     Here error contains <> 0 only if we have a fully specified conf_file
     or a forced default file
   */
   if (!(ptr=(char*) alloc_root(&alloc,sizeof(alloc)+
                    (args.elements + *argc + 1 + 1) *sizeof(char*))))
     goto err;
   res= (char**) (ptr+sizeof(alloc));
   /* copy name + found arguments + command line arguments to new array */
   res[0]= argv[0][0];  /* Name MUST be set, even by embedded library */
   memcpy((uchar*) (res+1), args.buffer, args.elements*sizeof(char*));
   /* Skip --defaults-xxx options */
   (*argc)-= args_used;
   (*argv)+= args_used;
   /*
     Check if we wan't to see the new argument list
     This options must always be the last of the default options
   */
   if (*argc >= 2 && !strcmp(argv[0][1],"--print-defaults"))
   {
     found_print_defaults=1;
     --*argc; ++*argv;               /* skip argument */
   }
   /* set arguments separator for arguments from config file and
      command line */
   res[args.elements+1]= (char *)args_separator;
   if (*argc)
     memcpy((uchar*) (res+1+args.elements+1), (char*) ((*argv)+1),
        (*argc-1)*sizeof(char*));
   res[args.elements+ *argc+1]=0;                /* last null */
   (*argc)+=args.elements+1;
   *argv= (char**) res;
   *(MEM_ROOT*) ptr= alloc;          /* Save alloc root for free */
   delete_dynamic(&args);
   if (found_print_defaults)
   {
     int i;
     printf("%s would have been started with the following arguments:\n",
        **argv);
     for (i=1 ; i < *argc ; i++)
       if ((*argv)[i] != args_separator) /* skip arguments separator */
         printf("%s ", (*argv)[i]);
     puts("");
     exit(0);
   }
   if (default_directories)
     *default_directories= dirs;
   DBUG_RETURN(0);
  err:
   fprintf(stderr,"Fatal error in defaults handling. Program aborted\n");
   exit(1);
   return 0;                 /* Keep compiler happy */
 }
References handle_option_ctx::alloc, alloc_root(), handle_option_ctx::args, args_separator, st_dynamic_array::buffer, st_typelib::count, DBUG_ENTER, DBUG_RETURN, default_directories, delete_dynamic(), st_dynamic_array::elements, error(), fprintf(), free_root(), handle_option_ctx::group, handle_default_option(), if(), init_alloc_root(), init_default_directories(), memcpy, my_init_dynamic_array, my_search_option_files(), MYF, st_typelib::name, NULL, printf(), ptr(), and st_typelib::type_names.
Referenced by load_defaults(), and mysql_read_default_options().
my_print_default_files()
void my_print_default_files (const char * conf_file)
Definition at line 1002 of file default.c.
 {
   const char *empty_list[]= { "", 0 };
   my_bool have_ext= fn_ext(conf_file)[0] != 0;
   const char **exts_to_use= have_ext ? empty_list : f_extensions;
   char name[FN_REFLEN], **ext;
   puts("\nDefault options are read from the following files in the given order:");
   if (dirname_length(conf_file))
     fputs(conf_file,stdout);
   else
   {
     const char **dirs;
     MEM_ROOT alloc;
     init_alloc_root(&alloc,512,0);
     if ((dirs= init_default_directories(&alloc)) == NULL)
     {
       fputs("Internal error initializing default directories list", stdout);
     }
     else
     {
       for ( ; *dirs; dirs++)
       {
         for (ext= (char**) exts_to_use; *ext; ext++)
         {
           const char *pos;
           char *end;
           if (**dirs)
             pos= *dirs;
           else if (my_defaults_extra_file)
             pos= my_defaults_extra_file;
           else
             continue;
           end= convert_dirname(name, pos, NullS);
           if (name[0] == FN_HOMELIB)    /* Add . to filenames in home */
             *end++= '.';
           strxmov(end, conf_file, *ext, " ", NullS);
           fputs(name, stdout);
         }
       }
     }
     free_root(&alloc, MYF(0));
   }
   puts("");
 }
References handle_option_ctx::alloc, convert_dirname(), dirname_length(), f_extensions, fn_ext(), FN_HOMELIB, FN_REFLEN, fputs(), free_root(), init_alloc_root(), init_default_directories(), my_defaults_extra_file, MYF, name, NULL, NullS, pos(), and strxmov().
Referenced by print_defaults().
my_search_option_files()
int my_search_option_files (const char * conf_file, int * argc, char *** argv, uint * args_used, Process_option_func func, void * func_ctx, const char ** default_directories)
copy group
Construct new group
Definition at line 208 of file default.c.
 {
   const char **dirs, *forced_default_file, *forced_extra_defaults;
   int error= 0;
   DBUG_ENTER("my_search_option_files");
   /* Check if we want to force the use a specific default file */
   *args_used+= get_defaults_options(*argc - *args_used, *argv + *args_used,
                                     (char **) &forced_default_file,
                                     (char **) &forced_extra_defaults,
                                     (char **) &my_defaults_group_suffix);
   if (! my_defaults_group_suffix)
     my_defaults_group_suffix= getenv(STRINGIFY_ARG(DEFAULT_GROUP_SUFFIX_ENV));
   if (forced_extra_defaults && !defaults_already_read)
   {
     int error= fn_expand(forced_extra_defaults, my_defaults_extra_file_buffer);
     if (error)
       DBUG_RETURN(error);
     my_defaults_extra_file= my_defaults_extra_file_buffer;
   }
   if (forced_default_file && !defaults_already_read)
   {
     int error= fn_expand(forced_default_file, my_defaults_file_buffer);
     if (error)
       DBUG_RETURN(error);
     my_defaults_file= my_defaults_file_buffer;
   }
   defaults_already_read= TRUE;
   /*
     We can only handle 'defaults-group-suffix' if we are called from
     load_defaults() as otherwise we can't know the type of 'func_ctx'
   */
   if (my_defaults_group_suffix && func == handle_default_option)
   {
     /* Handle --defaults-group-suffix= */
     uint i;
     const char **extra_groups;
     const size_t instance_len= strlen(my_defaults_group_suffix);
     struct handle_option_ctx *ctx= (struct handle_option_ctx*) func_ctx;
     char *ptr;
     TYPELIB *group= ctx->group;
     if (!(extra_groups=
       (const char**)alloc_root(ctx->alloc,
                                    (2*group->count+1)*sizeof(char*))))
       DBUG_RETURN(2);
     for (i= 0; i < group->count; i++)
     {
       size_t len;
       extra_groups[i]= group->type_names[i];
       len= strlen(extra_groups[i]);
       if (!(ptr= alloc_root(ctx->alloc, (uint) (len+instance_len+1))))
        DBUG_RETURN(2);
       extra_groups[i+group->count]= ptr;
       memcpy(ptr, extra_groups[i], len);
       memcpy(ptr+len, my_defaults_group_suffix, instance_len+1);
     }
     group->count*= 2;
     group->type_names= extra_groups;
     group->type_names[group->count]= 0;
   }
   if (my_defaults_file)
   {
     if ((error= search_default_file_with_ext(func, func_ctx, "", "",
                                              my_defaults_file, 0)) < 0)
       goto err;
     if (error > 0)
     {
       fprintf(stderr, "Could not open required defaults file: %s\n",
               my_defaults_file);
       goto err;
     }
   }
   else if (dirname_length(conf_file))
   {
     if ((error= search_default_file(func, func_ctx, NullS, conf_file)) < 0)
       goto err;
   }
   else
   {
     for (dirs= default_directories ; *dirs; dirs++)
     {
       if (**dirs)
       {
     if (search_default_file(func, func_ctx, *dirs, conf_file) < 0)
       goto err;
       }
       else if (my_defaults_extra_file)
       {
         if ((error= search_default_file_with_ext(func, func_ctx, "", "",
                                                 my_defaults_extra_file, 0)) < 0)
       goto err;             /* Fatal error */
         if (error > 0)
         {
           fprintf(stderr, "Could not open required defaults file: %s\n",
                   my_defaults_extra_file);
           goto err;
         }
       }
     }
   }
   DBUG_RETURN(0);
 err:
   fprintf(stderr,"Fatal error in defaults handling. Program aborted\n");
   DBUG_RETURN(1);
 }
References handle_option_ctx::alloc, alloc_root(), st_typelib::count, DBUG_ENTER, DBUG_RETURN, default_directories, defaults_already_read, dirname_length(), error(), fn_expand(), fprintf(), get_defaults_options(), handle_option_ctx::group, handle_default_option(), memcpy, my_defaults_extra_file, my_defaults_extra_file_buffer, my_defaults_file, my_defaults_file_buffer, my_defaults_group_suffix, NullS, ptr(), search_default_file(), search_default_file_with_ext(), STRINGIFY_ARG, TRUE, and st_typelib::type_names.
Referenced by my_load_defaults().
print_defaults()
void print_defaults (const char * conf_file, const char ** groups)
Definition at line 1051 of file default.c.
 {
   const char **groups_save= groups;
   my_print_default_files(conf_file);
   fputs("The following groups are read:",stdout);
   for ( ; *groups ; groups++)
   {
     fputc(' ',stdout);
     fputs(*groups,stdout);
   }
   if (my_defaults_group_suffix)
   {
     groups= groups_save;
     for ( ; *groups ; groups++)
     {
       fputc(' ',stdout);
       fputs(*groups,stdout);
       fputs(my_defaults_group_suffix,stdout);
     }
   }
   puts("\nThe following options may be given as the first argument:\n\
 --print-defaults        Print the program argument list and exit.\n\
 --no-defaults           Don't read default options from any option file.\n\
 --defaults-file=#       Only read default options from the given file #.\n\
 --defaults-extra-file=# Read this file after the global files are read.");
 }
References fputs(), my_defaults_group_suffix, and my_print_default_files().
remove_end_comment()
static char * remove_end_comment (char * ptr) static
Definition at line 976 of file default.c.
 {
   char quote= 0;    /* we are inside quote marks */
   char escape= 0;   /* symbol is protected by escape chagacter */
   for (; *ptr; ptr++)
   {
     if ((*ptr == '\'' || *ptr == '\"') && !escape)
     {
       if (!quote)
     quote= *ptr;
       else if (quote == *ptr)
     quote= 0;
     }
     /* We are not inside a string */
     if (!quote && *ptr == '#')
     {
       *ptr= 0;
       return ptr;
     }
     escape= (quote && *ptr == '\\' && !escape);
   }
   return ptr;
 }
References G3D::escape(), and ptr().
Referenced by search_default_file_with_ext().
search_default_file()
static int search_default_file (Process_option_func func, void * func_ctx, const char * dir, const char * config_file) static
Definition at line 628 of file default.c.
 {
   char **ext;
   const char *empty_list[]= { "", 0 };
   my_bool have_ext= fn_ext(config_file)[0] != 0;
   const char **exts_to_use= have_ext ? empty_list : f_extensions;
   for (ext= (char**) exts_to_use; *ext; ext++)
   {
     int error;
     if ((error= search_default_file_with_ext(opt_handler, handler_ctx,
                                              dir, *ext,
                          config_file, 0)) < 0)
       return error;
   }
   return 0;
 }
References error(), f_extensions, fn_ext(), and search_default_file_with_ext().
Referenced by my_search_option_files().
search_default_file_with_ext()
static int search_default_file_with_ext (Process_option_func func, void * func_ctx, const char * dir, const char * ext, const char * config_file, int recursion_level) static
Definition at line 722 of file default.c.
 {
   char name[FN_REFLEN + 10], buff[4096], curr_gr[4096], *ptr, *end, **tmp_ext;
   char *value, option[4096+2], tmp[FN_REFLEN];
   static const char includedir_keyword[]= "includedir";
   static const char include_keyword[]= "include";
   const int max_recursion_level= 10;
   MYSQL_FILE *fp;
   uint line=0;
   my_bool found_group=0;
   uint i;
   MY_DIR *search_dir;
   FILEINFO *search_file;
   if ((dir ? strlen(dir) : 0 )+strlen(config_file) >= FN_REFLEN-3)
     return 0;                   /* Ignore wrong paths */
   if (dir)
   {
     end=convert_dirname(name, dir, NullS);
     if (dir[0] == FN_HOMELIB)       /* Add . to filenames in home */
       *end++='.';
     strxmov(end,config_file,ext,NullS);
   }
   else
   {
     strmov(name,config_file);
   }
   fn_format(name,name,"","",4);
 #if !defined(__WIN__)
   {
     MY_STAT stat_info;
     if (!my_stat(name,&stat_info,MYF(0)))
       return 1;
     /*
       Ignore world-writable regular files.
       This is mainly done to protect us to not read a file created by
       the mysqld server, but the check is still valid in most context.
     */
     if ((stat_info.st_mode & S_IWOTH) &&
     (stat_info.st_mode & S_IFMT) == S_IFREG)
     {
       fprintf(stderr, "Warning: World-writable config file '%s' is ignored\n",
               name);
       return 0;
     }
   }
 #endif
   if (!(fp= mysql_file_fopen(key_file_cnf, name, O_RDONLY, MYF(0))))
     return 1;                   /* Ignore wrong files */
   while (mysql_file_fgets(buff, sizeof(buff) - 1, fp))
   {
     line++;
     /* Ignore comment and empty lines */
     for (ptr= buff; my_isspace(&my_charset_latin1, *ptr); ptr++)
     {}
     if (*ptr == '#' || *ptr == ';' || !*ptr)
       continue;
     /* Configuration File Directives */
     if ((*ptr == '!'))
     {
       if (recursion_level >= max_recursion_level)
       {
         for (end= ptr + strlen(ptr) - 1;
              my_isspace(&my_charset_latin1, *(end - 1));
              end--)
         {}
         end[0]= 0;
         fprintf(stderr,
                 "Warning: skipping '%s' directive as maximum include"
                 "recursion level was reached in file %s at line %d\n",
                 ptr, name, line);
         continue;
       }
       /* skip over `!' and following whitespace */
       for (++ptr; my_isspace(&my_charset_latin1, ptr[0]); ptr++)
       {}
       if ((!strncmp(ptr, includedir_keyword,
                     sizeof(includedir_keyword) - 1)) &&
           my_isspace(&my_charset_latin1, ptr[sizeof(includedir_keyword) - 1]))
       {
     if (!(ptr= get_argument(includedir_keyword,
                                 sizeof(includedir_keyword),
                                 ptr, name, line)))
       goto err;
         if (!(search_dir= my_dir(ptr, MYF(MY_WME))))
           goto err;
         for (i= 0; i < (uint) search_dir->number_off_files; i++)
         {
           search_file= search_dir->dir_entry + i;
           ext= fn_ext(search_file->name);
           /* check extension */
           for (tmp_ext= (char**) f_extensions; *tmp_ext; tmp_ext++)
           {
             if (!strcmp(ext, *tmp_ext))
               break;
           }
           if (*tmp_ext)
           {
             fn_format(tmp, search_file->name, ptr, "",
                       MY_UNPACK_FILENAME | MY_SAFE_PATH);
             search_default_file_with_ext(opt_handler, handler_ctx, "", "", tmp,
                                          recursion_level + 1);
           }
         }
         my_dirend(search_dir);
       }
       else if ((!strncmp(ptr, include_keyword, sizeof(include_keyword) - 1)) &&
                my_isspace(&my_charset_latin1, ptr[sizeof(include_keyword)-1]))
       {
     if (!(ptr= get_argument(include_keyword,
                                 sizeof(include_keyword), ptr,
                                 name, line)))
       goto err;
         search_default_file_with_ext(opt_handler, handler_ctx, "", "", ptr,
                                      recursion_level + 1);
       }
       continue;
     }
     if (*ptr == '[')                /* Group name */
     {
       found_group=1;
       if (!(end=(char *) strchr(++ptr,']')))
       {
     fprintf(stderr,
         "error: Wrong group definition in config file: %s at line %d\n",
         name,line);
     goto err;
       }
       /* Remove end space */
       for ( ; my_isspace(&my_charset_latin1,end[-1]) ; end--) ;
       end[0]=0;
       strmake(curr_gr, ptr, min((size_t) (end-ptr)+1, sizeof(curr_gr)-1));
       /* signal that a new group is found */
       opt_handler(handler_ctx, curr_gr, NULL);
       continue;
     }
     if (!found_group)
     {
       fprintf(stderr,
           "error: Found option without preceding group in config file: %s at line: %d\n",
           name,line);
       goto err;
     }
     end= remove_end_comment(ptr);
     if ((value= strchr(ptr, '=')))
       end= value;               /* Option without argument */
     for ( ; my_isspace(&my_charset_latin1,end[-1]) ; end--) ;
     if (!value)
     {
       strmake(strmov(option,"--"),ptr, (size_t) (end-ptr));
       if (opt_handler(handler_ctx, curr_gr, option))
         goto err;
     }
     else
     {
       /* Remove pre- and end space */
       char *value_end;
       for (value++ ; my_isspace(&my_charset_latin1,*value); value++) ;
       value_end=strend(value);
       /*
     We don't have to test for value_end >= value as we know there is
     an '=' before
       */
       for ( ; my_isspace(&my_charset_latin1,value_end[-1]) ; value_end--) ;
       if (value_end < value)            /* Empty string */
     value_end=value;
       /* remove quotes around argument */
       if ((*value == '\"' || *value == '\'') && /* First char is quote */
           (value + 1 < value_end ) && /* String is longer than 1 */
           *value == value_end[-1] ) /* First char is equal to last char */
       {
     value++;
     value_end--;
       }
       ptr=strnmov(strmov(option,"--"),ptr,(size_t) (end-ptr));
       *ptr++= '=';
       for ( ; value != value_end; value++)
       {
     if (*value == '\\' && value != value_end-1)
     {
       switch(*++value) {
       case 'n':
         *ptr++='\n';
         break;
       case 't':
         *ptr++= '\t';
         break;
       case 'r':
         *ptr++ = '\r';
         break;
       case 'b':
         *ptr++ = '\b';
         break;
       case 's':
         *ptr++= ' ';            /* space */
         break;
       case '\"':
         *ptr++= '\"';
         break;
       case '\'':
         *ptr++= '\'';
         break;
       case '\\':
         *ptr++= '\\';
         break;
       default:              /* Unknown; Keep '\' */
         *ptr++= '\\';
         *ptr++= *value;
         break;
       }
     }
     else
       *ptr++= *value;
       }
       *ptr=0;
       if (opt_handler(handler_ctx, curr_gr, option))
         goto err;
     }
   }
   mysql_file_fclose(fp, MYF(0));
   return(0);
  err:
   mysql_file_fclose(fp, MYF(0));
   return -1;                    /* Fatal error */
 }
References convert_dirname(), st_my_dir::dir_entry, f_extensions, fn_ext(), fn_format(), FN_HOMELIB, FN_REFLEN, fprintf(), get_argument(), min, my_charset_latin1, my_dir(), my_dirend(), my_isspace, MY_SAFE_PATH, MY_STAT, my_stat(), MY_UNPACK_FILENAME, MY_WME, MYF, mysql_file_fclose, mysql_file_fgets, mysql_file_fopen, name, fileinfo::name, NULL, NullS, st_my_dir::number_off_files, ptr(), remove_end_comment(), strend(), strmake(), strmov(), strnmov(), and strxmov().
Referenced by my_search_option_files(), and search_default_file().
Variable Documentation
args_separator
const char* args_separator = "----args-separator----"
arguments separator
load_defaults() loads arguments from config file and put them before the arguments from command line, this separator is used to separate the arguments loaded from config file and arguments user provided on command line.
Options with value loaded from config file are always in the form '–option=value', while for command line options, the value can be given as the next argument. Thus we used a separator so that handle_options() can distinguish them.
Note: any other places that does not need to distinguish them should skip the separator.
The content of arguments separator does not matter, one should only check the pointer, use "----args-separator----" here to ease debug if someone misused it.
See BUG#25192
Definition at line 66 of file default.c.
Referenced by handle_options(), my_load_defaults(), and mysql_read_default_options().
default_directories
const char** default_directories = NULL static
Definition at line 80 of file default.c.
Referenced by load_defaults(), my_load_defaults(), and my_search_option_files().
defaults_already_read
my_bool defaults_already_read = FALSE static
Definition at line 74 of file default.c.
Referenced by my_search_option_files().
f_extensions
const char* f_extensions[] = { ".cnf", 0 } static
Definition at line 86 of file default.c.
Referenced by my_print_default_files(), search_default_file(), and search_default_file_with_ext().
my_defaults_extra_file
const char* my_defaults_extra_file =0
Definition at line 69 of file default.c.
Referenced by my_print_default_files(), and my_search_option_files().
my_defaults_extra_file_buffer
char my_defaults_extra_file_buffer[FN_REFLEN] static
Definition at line 72 of file default.c.
Referenced by my_search_option_files().
my_defaults_file
const char* my_defaults_file =0
Definition at line 67 of file default.c.
Referenced by my_search_option_files().
my_defaults_file_buffer
char my_defaults_file_buffer[FN_REFLEN] static
Definition at line 71 of file default.c.
Referenced by my_search_option_files().
my_defaults_group_suffix
const char* my_defaults_group_suffix =0
Definition at line 68 of file default.c.
Referenced by my_search_option_files(), and print_defaults().