Azerotcore-wotlk: Position Struct Reference
Position Struct Reference
#include <Object.h>
Classes
struct PositionXYStreamer
struct PositionXYZOStreamer
struct PositionXYZStreamer
Public Member Functions
Position (float x=0, float y=0, float z=0, float o=0)
Position (Position const &loc)
bool operator== (Position const &a) const
bool operator!= (Position const &a)
operator G3D::Vector3 () const
void Relocate (float x, float y)
void Relocate (float x, float y, float z)
void Relocate (float x, float y, float z, float orientation)
void Relocate (const Position &pos)
void Relocate (const Position *pos)
void RelocatePolarOffset (float angle, float dist, float z=0.0f)
void RelocateOffset (const Position &offset)
void SetOrientation (float orientation)
float GetPositionX () const
float GetPositionY () const
float GetPositionZ () const
float GetOrientation () const
void GetPosition (float &x, float &y) const
void GetPosition (float &x, float &y, float &z) const
void GetPosition (float &x, float &y, float &z, float &o) const
Position GetPosition () const
Position::PositionXYZStreamer PositionXYZStream ()
Position::PositionXYZOStreamer PositionXYZOStream ()
bool IsPositionValid () const
float GetExactDist2dSq (const float x, const float y) const
float GetExactDist2dSq (Position const &pos) const
float GetExactDist2dSq (Position const *pos) const
float GetExactDist2d (const float x, const float y) const
float GetExactDist2d (Position const &pos) const
float GetExactDist2d (Position const *pos) const
float GetExactDistSq (float x, float y, float z) const
float GetExactDistSq (Position const &pos) const
float GetExactDistSq (Position const *pos) const
float GetExactDist (float x, float y, float z) const
float GetExactDist (Position const &pos) const
float GetExactDist (Position const *pos) const
void GetPositionOffsetTo (const Position &endPos, Position &retOffset) const
Position GetPositionWithOffset (Position const &offset) const
float GetAngle (const Position *pos) const
float GetAngle (float x, float y) const
float GetAbsoluteAngle (float x, float y) const
float GetAbsoluteAngle (Position const &pos) const
float GetAbsoluteAngle (Position const *pos) const
float GetRelativeAngle (const Position *pos) const
float GetRelativeAngle (float x, float y) const
float ToAbsoluteAngle (float relAngle) const
void GetSinCos (float x, float y, float &vsin, float &vcos) const
bool IsInDist2d (float x, float y, float dist) const
bool IsInDist2d (const Position *pos, float dist) const
bool IsInDist (float x, float y, float z, float dist) const
bool IsInDist (const Position *pos, float dist) const
bool IsWithinBox (const Position &center, float xradius, float yradius, float zradius) const
bool HasInArc (float arcangle, const Position *pos, float targetRadius=0.0f) const
bool HasInLine (WorldObject const *target, float width) const
std::string ToString () const
Static Public Member Functions
static float NormalizeOrientation (float o)
Public Attributes
float m_positionX = 0
float m_positionY = 0
float m_positionZ = 0
float m_orientation = 0
Detailed Description
Definition at line 247 of file Object.h.
Constructor & Destructor Documentation
Position() [1/2]
Position::Position (float x = 0, float y = 0, float z = 0, float o = 0) inline
Definition at line 249 of file Object.h.
         : m_positionX(x), m_positionY(y), m_positionZ(z), m_orientation(NormalizeOrientation(o)) { }
Referenced by WorldObject::GetFirstCollisionPosition(), WorldObject::GetHitSpherePointFor(), WorldObject::GetRandomPoint(), Player::Player(), and Player::UpdateCinematicLocation().
Position() [2/2]
Position::Position (Position const & loc) inline
Definition at line 252 of file Object.h.
 { Relocate(loc); }
References Relocate().
Member Function Documentation
GetAbsoluteAngle() [1/3]
float Position::GetAbsoluteAngle (float x, float y) const inline
Definition at line 401 of file Object.h.
     {
         return NormalizeOrientation(std::atan2(
             static_cast<float>(y - m_positionY),
             static_cast<float>(x - m_positionX))
             );
     }
References m_positionX, m_positionY, NormalizeOrientation(), G3D::x, and G3D::y.
Referenced by Spell::EffectTeleUnitsFaceCaster(), and Spell::SummonGuardian().
GetAbsoluteAngle() [2/3]
float Position::GetAbsoluteAngle (Position const & pos) const inline
Definition at line 408 of file Object.h.
 { return GetAbsoluteAngle(pos.m_positionX, pos.m_positionY); }
References GetAbsoluteAngle(), and pos().
Referenced by GetAbsoluteAngle().
GetAbsoluteAngle() [3/3]
float Position::GetAbsoluteAngle (Position const * pos) const inline
Definition at line 409 of file Object.h.
 { return GetAbsoluteAngle(*pos); }
References GetAbsoluteAngle(), and pos().
Referenced by GetAbsoluteAngle().
GetAngle() [1/2]
float Position::GetAngle (const Position * pos) const
Definition at line 1537 of file Object.cpp.
 {
     if (!obj)
         return 0;
     return GetAngle(obj->GetPositionX(), obj->GetPositionY());
 }
References GetPositionX(), and GetPositionY().
Referenced by Vehicle::AddPassenger(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::AttackStart(), npc_argent_captainAI::DoAction(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::DoAction(), npc_hover_disk::npc_hover_diskAI::DoAction(), npc_time_rift::npc_time_riftAI::DoSummonAtRift(), ChaseMovementGenerator< T >::DoUpdate(), Spell::EffectDistract(), WorldObject::GetChargeContactPoint(), WorldObject::GetContactPoint(), WorldObject::GetHitSpherePointFor(), Unit::GetMeleeAttackPoint(), Unit::GetRandomContactPoint(), GetRelativeAngle(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::GoSiphon(), npc_commandscript::HandleNpcAddFormationCommand(), spell_dk_dancing_rune_weapon::HandleProc(), spell_marrowgar_coldflame::spell_marrowgar_coldflame_SpellScript::HandleScriptEffect(), HasInArc(), boss_aeonus::boss_aeonusAI::InitializeAI(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::JustSummoned(), MotionMaster::MoveBackwards(), npc_twilight_volunteer::npc_twilight_volunteerAI::MovementInform(), boss_illidan_stormrage::boss_illidan_stormrageAI::MovementInform(), boss_icehowl::boss_icehowlAI::MovementInform(), npc_vortex_ride::npc_vortex_rideAI::npc_vortex_rideAI(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::OnCreatureCreate(), go_ethereum_prison::OnGossipHello(), go_ethereum_stasis::OnGossipHello(), go_hive_pod::OnGossipHello(), spell_blood_council_summon_shadow_resonance::spell_blood_council_summon_shadow_resonance_SpellScript::SetDest(), Unit::SetFacingToObject(), Unit::SetInFront(), boss_thorim::boss_thorimAI::SpawnArenaNPCs(), boss_thorim::boss_thorimAI::SpellHit(), boss_devourer_of_souls::boss_devourer_of_soulsAI::SpellHitTarget(), boss_attumen::boss_attumenAI::SpellHitTarget(), CreatureAI::TriggerAlert(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), boss_eye_of_cthun::eye_of_cthunAI::UpdateAI(), npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::UpdateAI(), boss_jormungarAI::UpdateAI(), boss_icehowl::boss_icehowlAI::UpdateAI(), boss_krick::boss_krickAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), boss_rotface::boss_rotfaceAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_vortex_ride::npc_vortex_rideAI::UpdateAI(), npc_nexus_lord::npc_nexus_lordAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_ulduar_vx001::npc_ulduar_vx001AI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::UpdateAI(), npc_ulduar_emergency_fire_bot::npc_ulduar_emergency_fire_botAI::UpdateAI(), npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::UpdateAI(), boss_thorim_sif::boss_thorim_sifAI::UpdateAI(), npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::UpdateAI(), npc_feedin_da_goolz::npc_feedin_da_goolzAI::UpdateAI(), boss_the_lurker_below::boss_the_lurker_belowAI::UpdateAI(), npc_pet_gen_plump_turkey::UpdateAI(), Spell::UpdateChanneledTargetList(), Player::UpdateCinematicLocation(), and hyjalAI::WaypointReached().
GetAngle() [2/2]
float Position::GetAngle (float x, float y) const
Definition at line 1546 of file Object.cpp.
 {
     return getAngle(GetPositionX(), GetPositionY(), x, y);
 }
References getAngle(), GetPositionX(), GetPositionY(), G3D::x, and G3D::y.
GetExactDist() [1/3]
float Position::GetExactDist (float x, float y, float z) const inline
Definition at line 392 of file Object.h.
 { return std::sqrt(GetExactDistSq(x, y, z)); }
References GetExactDistSq(), G3D::x, G3D::y, and G3D::z.
Referenced by PetAI::_needToStop(), Spell::CalculateDelayMomentForDst(), npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::CanAIAttack(), npc_icc_severed_essence::npc_icc_severed_essenceAI::CanAIAttack(), WorldObject::CanDetectStealthOf(), spell_dk_death_grip::CheckCast(), boss_sindragosa::boss_sindragosaAI::DoAction(), npc_spinestalker::npc_spinestalkerAI::DoAction(), npc_rimefang::npc_rimefangAI::DoAction(), Spell::EffectTeleportUnits(), WorldObject::GetDistance(), WorldObject::GetHitSpherePointFor(), misc_commandscript::HandleGetDistanceCommand(), SpellCastTargets::HasDstChannel(), boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::InitWaypoint(), GameObject::IsAtInteractDistance(), boss_four_horsemen::boss_four_horsemenAI::IsInRoom(), boss_loatheb::boss_loathebAI::IsInRoom(), boss_maexxna::boss_maexxnaAI::IsInRoom(), boss_noth::boss_nothAI::IsInRoom(), boss_sapphiron::boss_sapphironAI::IsInRoom(), boss_lady_deathwhisper::boss_lady_deathwhisperAI::JustSummoned(), CreatureGroup::LeaderMoveTo(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::MovementInform(), BoneStormMoveTargetSelector::operator()(), LastPhaseIceTombTargetSelector::operator()(), ShadowTrapLKTargetSelector::operator()(), NonTankLKTargetSelector::operator()(), DefileTargetSelector::operator()(), UnboundPlagueTargetSelector::operator()(), boss_faction_championsAI::SelectEnemyCaster(), Spell::SelectImplicitTrajTargets(), boss_gluth::boss_gluthAI::SelectPlayerInRoom(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::SetData(), npc_your_inner_turmoil::npc_your_inner_turmoilAI::setphase(), npc_toc5_grand_champion_minion::npc_toc5_grand_champion_minionAI::UpdateAI(), boss_grand_champion::boss_grand_championAI::UpdateAI(), boss_frostsworn_general::boss_frostsworn_generalAI::UpdateAI(), boss_ick::boss_ickAI::UpdateAI(), boss_tyrannus::boss_tyrannusAI::UpdateAI(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::UpdateAI(), npc_green_dragon_combat_trigger::npc_green_dragon_combat_triggerAI::UpdateAI(), npc_crok_scourgebane::npc_crok_scourgebaneAI::UpdateAI(), boss_sapphiron::boss_sapphironAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), and CreatureAI::UpdateVictim().
GetExactDist() [2/3]
float Position::GetExactDist (Position const & pos) const inline
Definition at line 393 of file Object.h.
 { return GetExactDist(pos.m_positionX, pos.m_positionY, pos.m_positionZ); }
References GetExactDist(), and pos().
Referenced by GetExactDist().
GetExactDist() [3/3]
float Position::GetExactDist (Position const * pos) const inline
Definition at line 394 of file Object.h.
 { return GetExactDist(*pos); }
References GetExactDist(), and pos().
Referenced by GetExactDist().
GetExactDist2d() [1/3]
float Position::GetExactDist2d (const float x, const float y) const inline
Definition at line 380 of file Object.h.
 { return std::sqrt(GetExactDist2dSq(x, y)); }
References GetExactDist2dSq(), G3D::x, and G3D::y.
Referenced by Spell::EffectJump(), Spell::EffectJumpDest(), boss_professor_putricide::boss_professor_putricideAI::EnterCombat(), boss_professor_putricide::boss_professor_putricideAI::EnterEvadeMode(), CorruptTriggers::Execute(), npc_arthas_teleport_visual::GetAI(), SpellCastTargets::GetDist2d(), WorldObject::GetDistance2d(), Unit::GetMeleeAttackPoint(), BattlegroundRV::GetPillarIdForPos(), misc_commandscript::HandleGetDistanceCommand(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveTeleportAck(), spell_sindragosa_icy_grip_jump::spell_sindragosa_icy_grip_jump_SpellScript::HandleSpecial(), HasInLine(), boss_algalon_the_observer::boss_algalon_the_observerAI::IsInRoom(), Unit::JumpTo(), spell_ioc_launch::spell_ioc_launch_SpellScript::Launch(), npc_blood_queen_lana_thel::npc_blood_queen_lana_thelAI::MoveInLineOfSight(), npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::MoveInLineOfSight(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::MoveInLineOfSight(), boss_kologarn::boss_kologarnAI::MoveInLineOfSight(), npc_ulduar_expedition_commander::npc_ulduar_expedition_commanderAI::MoveInLineOfSight(), npc_ulduar_snow_mound::npc_ulduar_snow_moundAI::MoveInLineOfSight(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath(), Acore::AllWorldObjectsInExactRange::operator()(), spell_marrowgar_bone_storm::spell_marrowgar_bone_storm_SpellScript::RecalculateDamage(), Spell::SelectImplicitTrajTargets(), spell_blood_council_summon_shadow_resonance::spell_blood_council_summon_shadow_resonance_SpellScript::SetDest(), npc_toc_shadow_priest::npc_toc_shadow_priestAI::UpdateAI(), npc_fos_corrupted_soul_fragment::npc_fos_corrupted_soul_fragmentAI::UpdateAI(), npc_hor_lich_king::npc_hor_lich_kingAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), boss_ignis::boss_ignisAI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::UpdateAI(), npc_ulduar_emergency_fire_bot::npc_ulduar_emergency_fire_botAI::UpdateAI(), and npc_ulduar_storm_tempered_keeper::npc_ulduar_storm_tempered_keeperAI::UpdateAI().
GetExactDist2d() [2/3]
float Position::GetExactDist2d (Position const & pos) const inline
Definition at line 381 of file Object.h.
 { return GetExactDist2d(pos.m_positionX, pos.m_positionY); }
References GetExactDist2d(), and pos().
Referenced by GetExactDist2d().
GetExactDist2d() [3/3]
float Position::GetExactDist2d (Position const * pos) const inline
Definition at line 382 of file Object.h.
 { return GetExactDist2d(*pos); }
References GetExactDist2d(), and pos().
Referenced by GetExactDist2d().
GetExactDist2dSq() [1/3]
float Position::GetExactDist2dSq (const float x, const float y) const inline
Definition at line 371 of file Object.h.
     {
         float dx = x - m_positionX;
         float dy = y - m_positionY;
         return dx*dx + dy*dy;
     }
References m_positionX, m_positionY, G3D::x, and G3D::y.
Referenced by boss_professor_putricide::boss_professor_putricideAI::CanAIAttack(), HostileRefMgr::deleteReferencesOutOfRange(), SlaveRunEvent::Execute(), GetExactDist2d(), GetExactDistSq(), HasInArc(), WorldObject::IsInBetween(), IsInDist2d(), IsValidPlatformTarget(), boss_lord_marrowgar::MoveInLineOfSight(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::MoveInLineOfSight(), npc_putricide_oozeAI::UpdateAI(), npc_icc_ice_sphere::npc_icc_ice_sphereAI::UpdateAI(), npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::UpdateAI(), npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI::UpdateAI(), Acore::MessageDistDeliverer::Visit(), and Acore::MessageDistDelivererToHostile::Visit().
GetExactDist2dSq() [2/3]
float Position::GetExactDist2dSq (Position const & pos) const inline
Definition at line 378 of file Object.h.
 { return GetExactDist2dSq(pos.m_positionX, pos.m_positionY); }
References GetExactDist2dSq(), and pos().
Referenced by GetExactDist2dSq().
GetExactDist2dSq() [3/3]
float Position::GetExactDist2dSq (Position const * pos) const inline
Definition at line 379 of file Object.h.
 { return GetExactDist2dSq(*pos); }
References GetExactDist2dSq(), and pos().
Referenced by GetExactDist2dSq().
GetExactDistSq() [1/3]
float Position::GetExactDistSq (float x, float y, float z) const inline
Definition at line 384 of file Object.h.
     {
         float dz = z - m_positionZ;
         return GetExactDist2dSq(x, y) + dz*dz;
     }
References GetExactDist2dSq(), m_positionZ, G3D::x, G3D::y, and G3D::z.
Referenced by RandomMovementGenerator< T >::_setRandomLocation(), npc_q24545_wretched_ghoul::npc_q24545_wretched_ghoulAI::CanAIAttack(), npc_lk_wicked_spirit::npc_lk_wicked_spiritAI::CanAIAttack(), Spell::CheckCast(), boss_the_lich_king::boss_the_lich_kingAI::DamageTaken(), WorldObject::GetClosePoint(), GetExactDist(), WorldObject::GetFirstCollisionPosition(), Unit::GetRandomContactPoint(), spell_vehicle_throw_passenger::spell_vehicle_throw_passenger_SpellScript::HandleScript(), GameObject::IsAtInteractDistance(), IsInDist(), boss_anubarak_trial::boss_anubarak_trialAI::MoveInLineOfSight(), MMapTargetData::PosChanged(), and FollowMovementGenerator< T >::PositionOkay().
GetExactDistSq() [2/3]
float Position::GetExactDistSq (Position const & pos) const inline
Definition at line 390 of file Object.h.
 { return GetExactDistSq(pos.m_positionX, pos.m_positionY, pos.m_positionZ); }
References GetExactDistSq(), and pos().
Referenced by GetExactDistSq().
GetExactDistSq() [3/3]
float Position::GetExactDistSq (Position const * pos) const inline
Definition at line 391 of file Object.h.
 { return GetExactDistSq(*pos); }
References GetExactDistSq(), and pos().
Referenced by GetExactDistSq().
GetOrientation()
float Position::GetOrientation () const inline
Definition at line 337 of file Object.h.
 { return m_orientation; }
References m_orientation.
Referenced by Unit::_ExitVehicle(), Player::_SaveCharacter(), Player::_SaveEntryPoint(), Player::ActivateTaxiPathTo(), boss_loatheb::boss_loathebAI::boss_loathebAI(), Unit::BuildMovementPacket(), Object::BuildMovementUpdate(), Transport::CalculatePassengerOffset(), Transport::CalculatePassengerPosition(), BattlegroundSA::CaptureGraveyard(), Unit::CastSpell(), Map::ConvertCorpseToBones(), Corpse::Create(), GameObject::Create(), StaticTransport::Create(), Pet::CreateBaseAtCreature(), Pet::CreateBaseAtCreatureInfo(), MotionTransport::CreateNPCPassenger(), boss_ick::boss_ickAI::DamageTaken(), npc_power_spark::npc_power_sparkAI::DamageTaken(), npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI::DamageTaken(), npc_icc_spire_frostwyrm::npc_icc_spire_frostwyrmAI::DoAction(), boss_taldaram::boss_taldaramAI::DoAction(), npc_bone_spike::npc_bone_spikeAI::DoAction(), npc_argent_captainAI::DoAction(), BattlegroundIC::DoAction(), instance_stratholme::instance_stratholme_InstanceMapScript::DoSpawnPlaguedCritters(), FlightPathMovementGenerator::DoUpdate(), FollowMovementGenerator< T >::DoUpdate(), Spell::EffectDuel(), Spell::EffectLeap(), Spell::EffectPullTowards(), Spell::EffectResurrectPet(), Spell::EffectStuck(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectSummonPet(), Spell::EffectTeleportUnits(), Spell::EffectTransmitted(), boss_mandokir::boss_mandokirAI::EnterCombat(), boss_zuljin::boss_zuljinAI::EnterPhase(), BattlegroundIC::EventPlayerClickedOnFlag(), FixOrientation::Execute(), UtherBatteredHiltEvent::Execute(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::FlyAway(), Creature::FocusTarget(), WorldObject::GetClosePoint(), GameObjectModelOwnerImpl::GetOrientation(), GetPositionOffsetTo(), WorldObject::GetRandomPoint(), GameObject::GetRespawnPosition(), Creature::GetRespawnPosition(), WorldObject::GetStationaryO(), GameObject::GetStationaryO(), WorldObject::GetTransOffsetO(), WorldObject::GetVoidClosePoint(), misc_commandscript::HandleAppearCommand(), BattlegroundBE::HandleAreaTrigger(), BattlegroundDS::HandleAreaTrigger(), BattlegroundNA::HandleAreaTrigger(), BattlegroundRL::HandleAreaTrigger(), BattlegroundRV::HandleAreaTrigger(), BattlegroundIC::HandleCapturedNodes(), debug_commandscript::HandleDebugSpawnVehicleCommand(), OutdoorPvPSI::HandleDropFlag(), spell_q12014_steady_as_a_rock::HandleFinish(), gobject_commandscript::HandleGameObjectAddCommand(), gobject_commandscript::HandleGameObjectAddTempCommand(), gobject_commandscript::HandleGameObjectMoveCommand(), gobject_commandscript::HandleGameObjectTurnCommand(), go_commandscript::HandleGoGraveyardCommand(), go_commandscript::HandleGoGridCommand(), go_commandscript::HandleGoZoneXYCommand(), misc_commandscript::HandleGPSCommand(), misc_commandscript::HandleGroupSummonCommand(), WorldSession::HandleHearthAndResurrect(), WorldSession::HandleLoadPetFromDBFirstCallback(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveWorldportAck(), npc_commandscript::HandleNpcAddCommand(), npc_commandscript::HandleNpcAddFormationCommand(), npc_commandscript::HandleNpcMoveCommand(), npc_commandscript::HandleNpcTameCommand(), AuraEffect::HandlePeriodicTriggerSpellAuraTick(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandlePlayerLoginToCharInWorld(), BattlegroundBE::HandlePlayerUnderMap(), BattlegroundNA::HandlePlayerUnderMap(), BattlegroundRL::HandlePlayerUnderMap(), ArenaSpectator::HandleSpectatorSpectateCommand(), misc_commandscript::HandleSummonCommand(), tele_commandscript::HandleTeleAddCommand(), spell_winter_veil_racer_rocket_slam::spell_winter_veil_racer_rocket_slam_SpellScript::HandleTriggerSpell(), misc_commandscript::HandleUnstuckCommand(), wp_commandscript::HandleWpModifyCommand(), wp_commandscript::HandleWpShowCommand(), spell_q11065_wrangle_some_aether_rays_aura::if(), npc_pet_mage_mirror_image::InitializeAI(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::InstanceCleanup(), GameObject::IsInRange(), MapMgr::IsValidMapCoord(), go_wg_vehicle_teleporter::go_wg_vehicle_teleporterAI::IsValidVehicle(), Unit::JumpTo(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::JustDied(), boss_cyanigosa::boss_cyanigosaAI::JustDied(), npc_webbed_creature::npc_webbed_creatureAI::JustDied(), boss_noth::boss_nothAI::JustDied(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::JustReachedHome(), boss_kelthuzad::boss_kelthuzadAI::JustSummoned(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::JustSummoned(), boss_the_lich_king::boss_the_lich_kingAI::JustSummoned(), boss_algalon_the_observer::boss_algalon_the_observerAI::JustSummoned(), npc_akama_shade::npc_akamaAI::JustSummoned(), Movement::MoveSplineInit::Launch(), CreatureGroup::LeaderMoveTo(), Player::LoadFromDB(), npc_aged_dying_ancient_kodo::npc_aged_dying_ancient_kodoAI::MoveInLineOfSight(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::MoveInLineOfSight(), boss_captain_skarloc::boss_captain_skarlocAI::MovementInform(), boss_professor_putricide::boss_professor_putricideAI::MovementInform(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::MovementInform(), boss_malygos::boss_malygosAI::MovementInform(), npc_spinestalker::npc_spinestalkerAI::MovementInform(), npc_rimefang::npc_rimefangAI::MovementInform(), npc_omen::npc_omenAI::MovementInform(), gunship_npc_AI::MovementInform(), npc_gunship_boarding_addAI::MovementInform(), npc_gunship_mage::npc_gunship_mageAI::MovementInform(), npc_zelfrax::npc_zelfraxAI::MovementInform(), npc_escortAI::MovementInform(), SmartAI::MovepointReached(), WorldObject::MovePositionToFirstCollision(), npc_ball_of_flame::npc_ball_of_flameAI::npc_ball_of_flameAI(), npc_midsummer_bonfire::npc_midsummer_bonfireAI::npc_midsummer_bonfireAI(), npc_ulduar_magnetic_core::npc_ulduar_magnetic_coreAI::npc_ulduar_magnetic_coreAI(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectCreate(), go_inconspicuous_mine_car::OnGossipHello(), npc_vh_sinclari::OnGossipSelect(), npc_cos_chromie_start::OnGossipSelect(), at_icc_saurfang_portal::OnTrigger(), npc_hover_disk::npc_hover_diskAI::PassengerBoarded(), BattlegroundIC::PostUpdateImpl(), PredictPosition(), npc_jungle_punch_target::npc_jungle_punch_targetAI::proceedCwEvent(), SmartScript::ProcessAction(), BfGraveyard::RelocateDeadPlayers(), Battleground::RelocateDeadPlayers(), spell_quest_dragonmaw_race_generic::RelocateDest(), RelocateOffset(), RelocatePolarOffset(), npc_cork_gizelton::npc_cork_gizeltonAI::RelocateSummons(), Map::RemoveAllPlayers(), npc_thrall_old_hillsbrad::npc_thrall_old_hillsbradAI::ReorderInstance(), Player::RepopAtGraveyard(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::Reposition(), npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI::Reset(), npc_crusade_recruit::npc_crusade_recruitAI::Reset(), npc_oscillating_frequency_scanner_master_bunny::npc_oscillating_frequency_scanner_master_bunnyAI::Reset(), Player::ResurectUsingRequestData(), Player::SavePositionInDB(), Player::SaveRecallPosition(), Corpse::SaveToDB(), Creature::SaveToDB(), GameObject::SaveToDB(), Map::ScriptsProcess(), Spell::SelectImplicitCasterDestTargets(), Spell::SelectImplicitTrajTargets(), PassengerController::SelectSpawnPoint(), WorldSession::SendSpiritResurrect(), Unit::SendTeleportPacket(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::SetData(), npc_idol_room_spawner::npc_idol_room_spawnerAI::SetData(), Player::SetEntryPoint(), Unit::SetInCombatState(), GameObject::SetLocalRotation(), npc_escortAI::SetNextWaypoint(), boss_kelthuzad::boss_kelthuzadAI::SpawnHelpers(), instance_ulduar::instance_ulduar_InstanceMapScript::SpawnHodirChests(), boss_majordomo::boss_majordomoAI::SpellHit(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::SpellHitTarget(), npc_nerubian_burrower::npc_nerubian_burrowerAI::SpellHitTarget(), npc_pos_leader_second::npc_pos_leader_secondAI::SpellHitTarget(), boss_cyanigosa::boss_cyanigosaAI::SpellHitTarget(), WaypointMovementGenerator< Creature >::StartMove(), Movement::MoveSplineInit::Stop(), Unit::StopMovingOnCurrentPos(), WorldObject::SummonCreature(), Player::SummonIfPossible(), go_wind_stone::go_wind_stoneAI::SummonNPC(), go_tadpole_cage::go_tadpole_cageAI::SummonTadpoles(), Player::TeleportTo(), Player::TeleportToEntryPoint(), BattlegroundRV::TeleportUnitToNewZ(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::Update(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::Update(), RotateMovementGenerator::Update(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), boss_sacrolash::boss_sacrolashAI::UpdateAI(), npc_highborne_lamenter::npc_highborne_lamenterAI::UpdateAI(), boss_janalai::boss_janalaiAI::UpdateAI(), boss_renataki::boss_renatakiAI::UpdateAI(), npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::UpdateAI(), npc_winterfin_playmate::npc_winterfin_playmateAI::UpdateAI(), npc_snowfall_glade_playmate::npc_snowfall_glade_playmateAI::UpdateAI(), npc_the_biggest_tree::npc_the_biggest_treeAI::UpdateAI(), npc_high_oracle_soo_roo::npc_high_oracle_soo_rooAI::UpdateAI(), npc_elder_kekek::npc_elder_kekekAI::UpdateAI(), npc_the_etymidian::npc_the_etymidianAI::UpdateAI(), npc_alexstraza_the_lifebinder::npc_alexstraza_the_lifebinderAI::UpdateAI(), boss_azuregos::boss_azuregosAI::UpdateAI(), npc_giant_infernal::npc_giant_infernalAI::UpdateAI(), boss_ouro::boss_ouroAI::UpdateAI(), boss_viscidus::boss_viscidusAI::UpdateAI(), npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI::UpdateAI(), npc_frost_sphere::npc_frost_sphereAI::UpdateAI(), boss_jormungarAI::UpdateAI(), npc_hor_leader_second::npc_hor_leader_secondAI::UpdateAI(), npc_pos_after_first_boss::npc_pos_after_first_bossAI::UpdateAI(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::UpdateAI(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::UpdateAI(), npc_coldflame::npc_coldflameAI::UpdateAI(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::UpdateAI(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::UpdateAI(), boss_maexxna::boss_maexxnaAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI(), boss_flame_leviathan::boss_flame_leviathanAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_ulduar_vx001::npc_ulduar_vx001AI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), npc_ulduar_emergency_fire_bot::npc_ulduar_emergency_fire_botAI::UpdateAI(), npc_ulduar_expedition_engineer::npc_ulduar_expedition_engineerAI::UpdateAI(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::UpdateAI(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::UpdateAI(), Player::UpdateCinematicLocation(), Unit::UpdatePosition(), and GameObject::Use().
GetPosition() [1/4]
Position Position::GetPosition () const inline
Definition at line 358 of file Object.h.
 { return *this; }
Referenced by WorldObject::GetFirstCollisionPosition(), WorldObject::GetNearPosition(), WorldObject::GetRandomNearPosition(), WorldObject::IsWithinLOS(), WorldObject::IsWithinLOSInMap(), and Player::TeleportTo().
GetPosition() [2/4]
void Position::GetPosition (float & x, float & y) const inline
Definition at line 339 of file Object.h.
     {
         x = m_positionX;
         y = m_positionY;
     }
References m_positionX, m_positionY, G3D::x, and G3D::y.
Referenced by Unit::_ExitVehicle(), MotionTransport::AddPassenger(), StaticTransport::AddPassenger(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::AttackStart(), boss_janalai::boss_janalaiAI::Boom(), spell_igb_incinerating_blast::spell_igb_incinerating_blast_SpellScript::CalculateDamage(), PathGenerator::CalculatePath(), Spell::CheckCast(), spell_rotface_unstable_ooze_explosion::spell_rotface_unstable_ooze_explosion_SpellScript::CheckTarget(), MotionTransport::DelayedTeleportTransport(), ChaseMovementGenerator< T >::DoUpdate(), FollowMovementGenerator< T >::DoUpdate(), Spell::EffectChargeDest(), Spell::EffectJumpDest(), Spell::EffectKnockBack(), Spell::EffectLeap(), Spell::EffectResurrectPet(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectSummonPlayer(), Spell::EffectSummonRaFFriend(), Spell::EffectTeleportUnits(), Spell::EffectTransmitted(), FollowerAI::EnterEvadeMode(), DelayedMovementEvent::Execute(), IceTombSummonEvent::Execute(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), BattlegroundAV::GetClosestGraveyard(), BattlegroundSA::GetClosestGraveyard(), Creature::GetHomePosition(), Creature::GetTransportHomePosition(), spell_rotface_unstable_ooze_explosion_init::spell_rotface_unstable_ooze_explosion_init_SpellScript::HandleCast(), spell_herald_volzaj_insanity::spell_herald_volzaj_insanity_SpellScript::HandleDummyEffect(), gobject_commandscript::HandleGameObjectMoveCommand(), mmaps_commandscript::HandleMmapLocCommand(), mmaps_commandscript::HandleMmapPathCommand(), spell_vehicle_throw_passenger::spell_vehicle_throw_passenger_SpellScript::HandleScript(), WorldSession::HandleSetRaidDifficultyOpcode(), spell_halion_damage_aoe_summon::spell_halion_damage_aoe_summon_SpellScript::HandleSummon(), spell_putricide_mutated_transformation::spell_putricide_mutated_transformation_SpellScript::HandleSummon(), boss_janalai::boss_janalaiAI::HatchAllEggs(), npc_janalai_hatcher::npc_janalai_hatcherAI::HatchEggs(), BfWGGameObjectBuilding::Init(), npc_lk_spirit_bomb::npc_lk_spirit_bombAI::IsSummonedBy(), npc_oculus_drake::npc_oculus_drakeAI::IsSummonedBy(), WorldObject::IsWithinLOSInMap(), npc_frost_wyrm::npc_frost_wyrmAI::JustDied(), npc_gargoyle::npc_gargoyleAI::JustDied(), npc_shay_leafrunner::npc_shay_leafrunnerAI::JustRespawned(), exarch_orelis::exarch_orelisAI::JustSummoned(), MotionMaster::MoveBackwards(), MotionMaster::MoveKnockbackFrom(), adyen_the_lightbringer::adyen_the_lightbringerAI::MovementInform(), anchorite_karja::anchorite_karjaAI::MovementInform(), exarch_orelis::exarch_orelisAI::MovementInform(), kaylaan_the_lost::kaylaan_the_lostAI::MovementInform(), npc_gunship_boarding_addAI::MovementInform(), npc_zulaman_hostage::OnGossipSelect(), at_icc_saurfang_portal::OnTrigger(), MysticBuffetTargetFilter::operator()(), operator<<(), npc_oculus_drake::npc_oculus_drakeAI::PassengerBoarded(), PredictPosition(), SmartScript::ProcessAction(), spell_igb_teleport_to_enemy_ship::spell_igb_teleport_to_enemy_ship_SpellScript::RelocateTransportOffset(), npc_valkyr_battle_maiden::npc_valkyr_battle_maidenAI::Reset(), npc_kinetic_bomb::npc_kinetic_bombAI::Reset(), boss_nalorakk::boss_nalorakkAI::ResetMobs(), boss_nalorakk::boss_nalorakkAI::SendAttacker(), gunship_npc_AI::SetData(), Player::SetHomebind(), NPCStaveQuestAI::SetHomePosition(), BattlefieldWG::SetupBattlefield(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::SpellHitTarget(), boss_lethon::boss_lethonAI::SpellHitTarget(), boss_amanitar::boss_amanitarAI::SummonedCreatureDies(), npc_coren_direbrew::npc_coren_direbrewAI::SummonSister(), BossAI::TeleportCheaters(), npc_rookery_hatcher::npc_rookery_hatcherAI::UpdateAI(), boss_akilzon::boss_akilzonAI::UpdateAI(), npc_giant_infernal::npc_giant_infernalAI::UpdateAI(), npc_gargoyle::npc_gargoyleAI::UpdateAI(), boss_ayamiss::boss_ayamissAI::UpdateAI(), npc_shay_leafrunner::npc_shay_leafrunnerAI::UpdateAI(), npc_twiggy_flathead::npc_twiggy_flatheadAI::UpdateAI(), boss_garfrost::boss_garfrostAI::UpdateAI(), boss_ick::boss_ickAI::UpdateAI(), boss_tyrannus::boss_tyrannusAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), npc_oculus_drake::npc_oculus_drakeAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_ulduar_vx001::npc_ulduar_vx001AI::UpdateAI(), npc_massive_jormungar::npc_massive_jormungarAI::UpdateAI(), socrethar::socretharAI::UpdateAI(), StaticTransport::UpdatePassengerPositions(), and MotionTransport::UpdatePassengerPositions().
GetPosition() [3/4]
void Position::GetPosition (float & x, float & y, float & z) const inline
Definition at line 344 of file Object.h.
     {
         x = m_positionX;
         y = m_positionY;
         z = m_positionZ;
     }
References m_positionX, m_positionY, m_positionZ, G3D::x, G3D::y, and G3D::z.
GetPosition() [4/4]
void Position::GetPosition (float & x, float & y, float & z, float & o) const inline
Definition at line 350 of file Object.h.
     {
         x = m_positionX;
         y = m_positionY;
         z = m_positionZ;
         o = m_orientation;
     }
References m_orientation, m_positionX, m_positionY, m_positionZ, G3D::x, G3D::y, and G3D::z.
GetPositionOffsetTo()
void Position::GetPositionOffsetTo (const Position & endPos, Position & retOffset) const
Definition at line 1526 of file Object.cpp.
 {
     float dx = endPos.GetPositionX() - GetPositionX();
     float dy = endPos.GetPositionY() - GetPositionY();
     retOffset.m_positionX = dx * cos(GetOrientation()) + dy * sin(GetOrientation());
     retOffset.m_positionY = dy * cos(GetOrientation()) - dx * sin(GetOrientation());
     retOffset.m_positionZ = endPos.GetPositionZ() - GetPositionZ();
     retOffset.m_orientation = endPos.GetOrientation() - GetOrientation();
 }
References GetOrientation(), GetPositionX(), GetPositionY(), GetPositionZ(), m_orientation, m_positionX, m_positionY, and m_positionZ.
Referenced by SpellDestination::Relocate().
GetPositionWithOffset()
Position Position::GetPositionWithOffset (Position const & offset) const
GetPositionX()
float Position::GetPositionX () const inline
Definition at line 334 of file Object.h.
 { return m_positionX; }
References m_positionX.
Referenced by WorldObject::_IsWithinDist(), GameObject::_IsWithinDist(), Player::_SaveCharacter(), Player::_SaveEntryPoint(), RandomMovementGenerator< T >::_setRandomLocation(), Player::ActivateTaxiPathTo(), InstanceScript::AddDoor(), Spell::AddGOTarget(), Map::AddPlayerToMap(), Map::AddToMap(), WorldObject::AddToWorld(), Spell::AddUnitTarget(), TotemAI::AttackStart(), boss_lieutenant_drake::boss_lieutenant_drakeAI::boss_lieutenant_drakeAI(), boss_loatheb::boss_loathebAI::boss_loathebAI(), Unit::BuildMovementPacket(), WorldSession::BuildPartyMemberStatsChangedPacket(), Transport::CalculatePassengerOffset(), Transport::CalculatePassengerPosition(), boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::CanAIAttack(), boss_selin_fireheart::boss_selin_fireheartAI::CanAIAttack(), boss_lord_marrowgar::CanAIAttack(), Map::CanReachPositionAndGetValidCoords(), GameObject::CastSpell(), boss_professor_putricide::boss_professor_putricideAI::ChangePhase(), Player::CheckAreaExploreAndOutdoor(), BossAI::CheckBoundary(), Spell::CheckCast(), Spell::CheckEffectTarget(), boss_general_zarithrian::boss_general_zarithrianAI::CheckEvadeIfOutOfCombatArea(), boss_freya::boss_freyaAI::CheckEvadeIfOutOfCombatArea(), boss_supremus::boss_supremusAI::CheckEvadeIfOutOfCombatArea(), boss_gothik::boss_gothikAI::CheckGroupSplitted(), BattlegroundRV::CheckPositionForUnit(), Spell::CheckSpellFocus(), Player::ContinueTaxiFlight(), Map::ConvertCorpseToBones(), Creature::Create(), Corpse::Create(), Pet::CreateBaseAtCreature(), Pet::CreateBaseAtCreatureInfo(), DynamicObject::CreateDynamicObject(), MotionTransport::CreateGOPassenger(), MotionTransport::CreateNPCPassenger(), npc_frost_sphere::npc_frost_sphereAI::DamageTaken(), boss_ick::boss_ickAI::DamageTaken(), npc_power_spark::npc_power_sparkAI::DamageTaken(), npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI::DamageTaken(), boss_viscidus::boss_viscidusAI::DamageTaken(), boss_the_lich_king::boss_the_lich_kingAI::DamageTaken(), boss_thorim::boss_thorimAI::DamageTaken(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::DamageTaken(), BattlegroundSA::DefendersPortalTeleport(), npc_icc_spire_frostwyrm::npc_icc_spire_frostwyrmAI::DoAction(), boss_taldaram::boss_taldaramAI::DoAction(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::DoAction(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::DoAction(), npc_bone_spike::npc_bone_spikeAI::DoAction(), boss_professor_putricide::boss_professor_putricideAI::DoAction(), boss_algalon_the_observer::boss_algalon_the_observerAI::DoAction(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::DoAction(), npc_power_spark::npc_power_sparkAI::DoAction(), npc_hover_disk::npc_hover_diskAI::DoAction(), BattlegroundIC::DoAction(), Creature::DoFleeToGetAssistance(), ScriptedAI::DoSpawnCreature(), instance_stratholme::instance_stratholme_InstanceMapScript::DoSpawnPlaguedCritters(), ChaseMovementGenerator< T >::DoUpdate(), Spell::EffectBind(), Spell::EffectDuel(), Spell::EffectLeap(), Spell::EffectPullTowards(), Spell::EffectResurrect(), Spell::EffectResurrectNew(), Spell::EffectTeleUnitsFaceCaster(), Spell::EffectTransmitted(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::EnsureGridLoaded(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::EnsureGridLoaded(), boss_mandokir::boss_mandokirAI::EnterCombat(), boss_professor_putricide::boss_professor_putricideAI::EnterEvadeMode(), BattlegroundIC::EventPlayerClickedOnFlag(), CastArmageddon::Execute(), UtherBatteredHiltEvent::Execute(), Unit::ExecuteDelayedUnitRelocationEvent(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::FlyAway(), npc_escortAI::GenerateWaypointArray(), SmartAI::GenerateWayPointArray(), GetAngle(), WorldObject::GetChargeContactPoint(), WorldObject::GetClosePoint(), BattlegroundAB::GetClosestGraveyard(), BattlegroundEY::GetClosestGraveyard(), BattlegroundIC::GetClosestGraveyard(), Graveyard::GetClosestGraveyard(), WorldObject::GetContactPoint(), WorldObject::GetCreaturesWithEntryInRange(), WorldObject::GetDistanceOrder(), WorldObject::GetFloorZ(), WorldObject::GetHitSpherePointFor(), WorldObject::GetNearPoint(), WorldObject::GetNearPoint2D(), boss_volkhan::boss_volkhanAI::GetNextPos(), GameObjectModelOwnerImpl::GetPosition(), GetPositionOffsetTo(), Unit::GetRandomContactPoint(), GameObject::GetRespawnPosition(), Creature::GetRespawnPosition(), GetSinCos(), WorldObject::GetStationaryX(), GameObject::GetStationaryX(), WorldObject::GetTransOffsetX(), npc_simon_bunny::npc_simon_bunnyAI::GivePunishment(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::GoSiphon(), misc_commandscript::HandleAppearCommand(), WorldSession::HandleBattlegroundPlayerPositionsOpcode(), BattlegroundIC::HandleCapturedNodes(), WorldSession::HandleCharFactionOrRaceChangeCallback(), misc_commandscript::HandleComeToMeCommand(), WorldSession::HandleCorpseQueryOpcode(), debug_commandscript::HandleDebugSendOpcodeCommand(), OutdoorPvPSI::HandleDropFlag(), spell_warhead_detonate::spell_warhead_detonate_SpellScript::HandleDummy(), spell_q12589_shoot_rjr::spell_q12589_shoot_rjr_SpellScript::HandleDummy(), spell_dk_death_grip::HandleDummy(), spell_midsummer_torch_quest::spell_midsummer_torch_quest_AuraScript::HandleEffectApply(), spell_q12014_steady_as_a_rock::HandleFinish(), gobject_commandscript::HandleGameObjectAddCommand(), gobject_commandscript::HandleGameObjectAddTempCommand(), gobject_commandscript::HandleGameObjectNearCommand(), gobject_commandscript::HandleGameObjectTargetCommand(), gobject_commandscript::HandleGameObjectTurnCommand(), misc_commandscript::HandleGPSCommand(), list_commandscript::HandleListCreatureCommand(), list_commandscript::HandleListObjectCommand(), mmaps_commandscript::HandleMmapLocCommand(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveTeleportAck(), WorldSession::HandleMoveWorldportAck(), npc_commandscript::HandleNpcAddCommand(), npc_commandscript::HandleNpcAddFormationCommand(), npc_commandscript::HandleNpcInfoCommand(), npc_commandscript::HandleNpcMoveCommand(), npc_commandscript::HandleNpcNearCommand(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandlePlayerLoginToCharInWorld(), WorldSession::HandleRequestPartyMemberStatsOpcode(), misc_commandscript::HandleRespawnCommand(), spell_dreamwalker_summon_portal::spell_dreamwalker_summon_portal_SpellScript::HandleScript(), spell_marrowgar_coldflame_bonestorm::spell_marrowgar_coldflame_SpellScript::HandleScriptEffect(), spell_winter_veil_racer_slam_hit::spell_winter_veil_racer_slam_hit_SpellScript::HandleScriptEffect(), spell_marrowgar_coldflame::spell_marrowgar_coldflame_SpellScript::HandleScriptEffect(), spell_q10612_10613_the_fel_and_the_furious::spell_q10612_10613_the_fel_and_the_furious_SpellScript::HandleScriptEffect(), spell_sindragosa_icy_grip_jump::spell_sindragosa_icy_grip_jump_SpellScript::HandleSpecial(), ArenaSpectator::HandleSpectatorSpectateCommand(), misc_commandscript::HandleSummonCommand(), tele_commandscript::HandleTeleAddCommand(), spell_winter_veil_racer_rocket_slam::spell_winter_veil_racer_rocket_slam_SpellScript::HandleTriggerSpell(), wp_commandscript::HandleWpAddCommand(), debug_commandscript::HandleWPGPSCommand(), wp_commandscript::HandleWpModifyCommand(), HasInLine(), spell_q11065_wrangle_some_aether_rays_aura::if(), boss_captain_skarloc::boss_captain_skarlocAI::InitializeAI(), npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI::InitializeAI(), boss_sapphiron::boss_sapphironAI::InitializeAI(), npc_preparations_for_war_vehicle::npc_preparations_for_war_vehicleAI::InitializeAI(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::InitializeAI(), npc_pet_mage_mirror_image::InitializeAI(), boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::InitWaypoint(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::InstanceCleanup(), GameObject::IsAtInteractDistance(), boss_netherspite::boss_netherspiteAI::IsBetween(), WorldObject::IsInBetween(), GameObject::IsInRange(), WorldObject::IsInRange(), WorldObject::IsInRange2d(), WorldObject::IsInRange3d(), boss_gothik::boss_gothikAI::IsInRoom(), ScriptedAI::IsInRoom(), boss_heigan::boss_heiganAI::IsInRoom(), WorldObject::IsInWintergrasp(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::IsSummonedBy(), npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::IsSummonedBy(), boss_sartharion::boss_sartharionAI::IsTargetInBounds(), MapMgr::IsValidMapCoord(), go_wg_vehicle_teleporter::go_wg_vehicle_teleporterAI::IsValidVehicle(), IsWithinBox(), Unit::IsWithinCombatRange(), WorldObject::IsWithinLOSInMap(), Unit::IsWithinMeleeRange(), Unit::IsWithinRange(), boss_yauj::boss_yaujAI::JustDied(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::JustDied(), npc_auriaya_feral_defender::npc_auriaya_feral_defenderAI::JustDied(), boss_cyanigosa::boss_cyanigosaAI::JustDied(), npc_artruis_the_hearthless::npc_artruis_the_hearthlessAI::JustDied(), boss_ahune::boss_ahuneAI::JustDied(), npc_enraged_spirit::npc_enraged_spiritAI::JustDied(), boss_noth::boss_nothAI::JustDied(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::JustReachedHome(), boss_kelthuzad::boss_kelthuzadAI::JustSummoned(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::JustSummoned(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::JustSummoned(), npc_daphne_stilwell::npc_daphne_stilwellAI::JustSummoned(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::JustSummoned(), boss_kiljaeden::boss_kiljaedenAI::JustSummoned(), npc_kalecgos_kj::npc_kalecgos_kjAI::JustSummoned(), boss_the_lich_king::boss_the_lich_kingAI::JustSummoned(), boss_algalon_the_observer::boss_algalon_the_observerAI::JustSummoned(), npc_akama_shade::npc_akamaAI::JustSummoned(), boss_lady_vashj::boss_lady_vashjAI::JustSummoned(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::JustSummoned(), npc_maghar_captive::npc_maghar_captiveAI::JustSummoned(), spell_ioc_launch::spell_ioc_launch_SpellScript::Launch(), CreatureGroup::LeaderMoveTo(), Corpse::LoadCorpseFromDB(), Player::LoadFromDB(), LogCommandUsage(), Map::MoveAllDynamicObjectsInMoveList(), Map::MoveAllGameObjectsInMoveList(), MotionMaster::MoveFall(), npc_aged_dying_ancient_kodo::npc_aged_dying_ancient_kodoAI::MoveInLineOfSight(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::MoveInLineOfSight(), npc_hol_monument::npc_hol_monumentAI::MoveInLineOfSight(), npc_brann_radio::npc_brann_radioAI::MoveInLineOfSight(), npc_ulduar_snow_mound::npc_ulduar_snow_moundAI::MoveInLineOfSight(), MotionMaster::MoveKnockbackFrom(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::MovementInform(), boss_malygos::boss_malygosAI::MovementInform(), npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI::MovementInform(), boss_vazruden_the_herald::boss_vazruden_the_heraldAI::MovementInform(), npc_ishanah::ishanahAI::MovementInform(), npc_omen::npc_omenAI::MovementInform(), npc_zelfrax::npc_zelfraxAI::MovementInform(), npc_escortAI::MovementInform(), SmartAI::MovepointReached(), npc_hor_leader_second::npc_hor_leader_secondAI::MoveToNextStopPoint(), npc_ball_of_flame::npc_ball_of_flameAI::npc_ball_of_flameAI(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::npc_icc_vengeful_fleshreaperAI(), npc_medivh_bm::npc_medivh_bmAI::npc_medivh_bmAI(), npc_midsummer_bonfire::npc_midsummer_bonfireAI::npc_midsummer_bonfireAI(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::npc_ulduar_flames_initialAI(), npc_vortex_ride::npc_vortex_rideAI::npc_vortex_rideAI(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::OnCreatureCreate(), instance_ulduar::instance_ulduar_InstanceMapScript::OnCreatureCreate(), instance_utgarde_keep::instance_utgarde_keep_InstanceMapScript::OnCreatureCreate(), instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::OnCreatureCreate(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::OnGameObjectCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectCreate(), instance_naxxramas::instance_naxxramas_InstanceMapScript::OnGameObjectCreate(), instance_naxxramas::instance_naxxramas_InstanceMapScript::OnGameObjectRemove(), go_corkis_prison::OnGossipHello(), go_ethereum_prison::OnGossipHello(), go_ethereum_stasis::OnGossipHello(), go_hive_pod::OnGossipHello(), go_veil_skith_cage::OnGossipHello(), npc_vekjik::OnGossipSelect(), npc_vh_sinclari::OnGossipSelect(), npc_cos_chromie_start::OnGossipSelect(), go_ahune_ice_stone::OnGossipSelect(), go_apexis_relic::OnGossipSelect(), instance_pit_of_saron::instance_pit_of_saron_InstanceScript::OnPlayerEnter(), instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::OnPlayerEnter(), BattlefieldWG::OnPlayerEnterZone(), at_sindragosa_lair::OnTrigger(), at_icc_saurfang_portal::OnTrigger(), AreaTrigger_at_scent_larkorwi::OnTrigger(), at_malfurion_stormrage::OnTrigger(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath(), item_nether_wraith_beacon::OnUse(), Acore::AnyPlayerExactPositionInGameObjectRangeCheck::operator()(), BoneStormMoveTargetSelector::operator()(), Acore::WorldObjectSpellAreaTargetCheck::operator()(), IgbArtilleryCheck::operator()(), MysticBuffetTargetFilter::operator()(), npc_vortex_ride::npc_vortex_rideAI::PassengerBoarded(), npc_vics_flying_machine::npc_vics_flying_machineAI::PassengerBoarded(), npc_hover_disk::npc_hover_diskAI::PassengerBoarded(), spell_halion_twilight_phasing::spell_halion_twilight_phasing_SpellScript::Phase(), Map::PlayerRelocation(), BattlegroundIC::PostUpdateImpl(), spell_hodir_flash_freeze::spell_hodir_flash_freeze_AuraScript::PrepareAuraScript(), spell_midsummer_ribbon_pole::spell_midsummer_ribbon_pole_AuraScript::PrepareAuraScript(), npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::PrepareEvent(), spell_anti_air_rocket_bomber::spell_anti_air_rocket_bomber_SpellScript::PrepareSpellScript(), npc_jungle_punch_target::npc_jungle_punch_targetAI::proceedCwEvent(), SmartScript::ProcessAction(), npc_dancing_flames::npc_dancing_flamesAI::ReceiveEmote(), spell_quest_dragonmaw_race_generic::RelocateDest(), RelocateOffset(), RelocatePolarOffset(), npc_cork_gizelton::npc_cork_gizeltonAI::RelocateSummons(), Player::RepopAtGraveyard(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::Reset(), npc_brewfest_super_brew_trigger::npc_brewfest_super_brew_triggerAI::Reset(), boss_anubarak_trial::boss_anubarak_trialAI::Reset(), boss_drakkari_colossus::boss_drakkari_colossusAI::Reset(), npc_crystal_spike::npc_crystal_spikeAI::Reset(), boss_bjarngrim::boss_bjarngrimAI::Reset(), boss_auriaya::boss_auriayaAI::Reset(), boss_freya_nature_bomb::boss_freya_nature_bombAI::Reset(), npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI::Reset(), npc_oscillating_frequency_scanner_master_bunny::npc_oscillating_frequency_scanner_master_bunnyAI::Reset(), npc_invis_infernal_caster::npc_invis_infernal_casterAI::Reset(), npc_firework::npc_fireworkAI::Reset(), Player::SavePositionInDB(), Player::SaveRecallPosition(), CharmInfo::SaveStayPosition(), Corpse::SaveToDB(), Creature::SaveToDB(), GameObject::SaveToDB(), boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::Say(), boss_yoggsaron_llane::boss_yoggsaron_llaneAI::Say(), boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI::Say(), PassengerController::SelectSpawnPoint(), boss_sartharion::boss_sartharionAI::SendLavaWaves(), WorldSession::SendLearnNewTaxiNode(), Unit::SendMonsterMove(), WorldSession::SendTaxiMenu(), WorldSession::SendTaxiStatus(), Unit::SendTeleportPacket(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SetBossState(), npc_ulduar_harpoonfirestate::npc_ulduar_harpoonfirestateAI::SetData(), instance_hyjal::instance_mount_hyjal_InstanceMapScript::SetData(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::SetData(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::SetData(), npc_argent_soldier::npc_argent_soldierAI::SetData(), npc_idol_room_spawner::npc_idol_room_spawnerAI::SetData(), npc_ulduar_mimiron_rocket::npc_ulduar_mimiron_rocketAI::SetData(), spell_blood_council_summon_shadow_resonance::spell_blood_council_summon_shadow_resonance_SpellScript::SetDest(), spell_dk_summon_gargoyle::SetDest(), Player::SetEntryPoint(), Unit::SetFacingTo(), Unit::SetFacingToObject(), Unit::SetHover(), Unit::SetInCombatState(), npc_your_inner_turmoil::npc_your_inner_turmoilAI::setphase(), PathGenerator::ShortenPathUntilDist(), boss_thorim::boss_thorimAI::SpawnArenaNPCs(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::SpawnClouds(), boss_skadi_grauf::boss_skadi_graufAI::SpawnHelpers(), instance_ulduar::instance_ulduar_InstanceMapScript::SpawnHodirChests(), boss_ossirian::boss_ossirianAI::SpawnNextCrystal(), instance_zulfarrak::instance_zulfarrak_InstanceMapScript::SpawnPyramidWave(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::SpawnTentacle(), boss_freya::boss_freyaAI::SpawnWave(), npc_varian_wrynn::npc_varian_wrynnAI::SpawnWave(), boss_headless_horseman_pumpkin::boss_headless_horseman_pumpkinAI::SpellHit(), boss_majordomo::boss_majordomoAI::SpellHit(), npc_wounded_skirmisher::npc_wounded_skirmisherAI::SpellHit(), npc_wild_wyrm::npc_wild_wyrmAI::SpellHit(), npc_forest_frog::npc_forest_frogAI::SpellHit(), npc_troll_volunteer::npc_troll_volunteerAI::SpellHit(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::SpellHit(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::SpellHitTarget(), npc_nerubian_burrower::npc_nerubian_burrowerAI::SpellHitTarget(), npc_pos_leader_second::npc_pos_leader_secondAI::SpellHitTarget(), boss_freya::boss_freyaAI::SpellHitTarget(), boss_cyanigosa::boss_cyanigosaAI::SpellHitTarget(), boss_attumen::boss_attumenAI::SpellHitTarget(), boss_grobbulus::boss_grobbulusAI::SpellHitTarget(), npc_xt002_heart::npc_xt002_heartAI::SpellHitTarget(), boss_ionar::boss_ionarAI::Split(), Unit::StopMovingOnCurrentPos(), instance_blood_furnace::instance_blood_furnace_InstanceMapScript::StorePrisoner(), boss_malchezaar::boss_malchezaarAI::SummonAxes(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonBroodling(), boss_anzu::boss_anzuAI::SummonBroods(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::SummonDeathOrbs(), boss_archimonde::boss_archimondeAI::SummonDoomfire(), boss_sjonnir::boss_sjonnirAI::SummonDwarfes(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::SummonedCreatureDies(), boss_yoggsaron::boss_yoggsaronAI::SummonImmortalGuardian(), npc_invis_infernal_caster::npc_invis_infernal_casterAI::SummonInfernal(), boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI::SummonMechanics(), go_wind_stone::go_wind_stoneAI::SummonNPC(), go_tadpole_cage::go_tadpole_cageAI::SummonTadpoles(), Map::SwitchGridContainers(), Player::TeleportTo(), BattlegroundRV::TeleportUnitToNewZ(), CreatureAI::TriggerAlert(), MotionTransport::Update(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::Update(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::Update(), instance_violet_hold::instance_violet_hold_InstanceMapScript::Update(), Creature::Update(), Player::Update(), npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI::UpdateAI(), npc_blackhand_incarcerator::npc_blackhand_incarceratorAI::UpdateAI(), npc_eye_of_acherus::npc_eye_of_acherusAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), boss_sacrolash::boss_sacrolashAI::UpdateAI(), boss_felmyst::boss_felmystAI::UpdateAI(), boss_kiljaeden::boss_kiljaedenAI::UpdateAI(), npc_highborne_lamenter::npc_highborne_lamenterAI::UpdateAI(), boss_jindo::boss_jindoAI::UpdateAI(), boss_renataki::boss_renatakiAI::UpdateAI(), npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::UpdateAI(), npc_dark_iron_attack_mole_machine::npc_dark_iron_attack_mole_machineAI::UpdateAI(), npc_winterfin_playmate::npc_winterfin_playmateAI::UpdateAI(), npc_snowfall_glade_playmate::npc_snowfall_glade_playmateAI::UpdateAI(), npc_the_biggest_tree::npc_the_biggest_treeAI::UpdateAI(), npc_high_oracle_soo_roo::npc_high_oracle_soo_rooAI::UpdateAI(), npc_elder_kekek::npc_elder_kekekAI::UpdateAI(), npc_the_etymidian::npc_the_etymidianAI::UpdateAI(), npc_alexstraza_the_lifebinder::npc_alexstraza_the_lifebinderAI::UpdateAI(), npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::UpdateAI(), boss_azuregos::boss_azuregosAI::UpdateAI(), hyjalAI::UpdateAI(), npc_medivh_bm::npc_medivh_bmAI::UpdateAI(), boss_cthun::cthunAI::UpdateAI(), npc_claw_tentacle::claw_tentacleAI::UpdateAI(), npc_giant_claw_tentacle::giant_claw_tentacleAI::UpdateAI(), boss_ouro::boss_ouroAI::UpdateAI(), boss_viscidus::boss_viscidusAI::UpdateAI(), npc_rizzle_sprysprocket::npc_rizzle_sprysprocketAI::UpdateAI(), npc_murkdeep::npc_murkdeepAI::UpdateAI(), boss_elder_nadox::boss_elder_nadoxAI::UpdateAI(), npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::UpdateAI(), boss_saviana_ragefire::boss_saviana_ragefireAI::UpdateAI(), npc_frost_sphere::npc_frost_sphereAI::UpdateAI(), boss_icehowl::boss_icehowlAI::UpdateAI(), boss_twin_valkyrAI::UpdateAI(), npc_hor_lich_king::npc_hor_lich_kingAI::UpdateAI(), boss_garfrost::boss_garfrostAI::UpdateAI(), boss_krick::boss_krickAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), npc_pos_after_first_boss::npc_pos_after_first_bossAI::UpdateAI(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::UpdateAI(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::UpdateAI(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::UpdateAI(), boss_lord_marrowgar::UpdateAI(), npc_coldflame::npc_coldflameAI::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), boss_sindragosa::boss_sindragosaAI::UpdateAI(), npc_rimefang::npc_rimefangAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::UpdateAI(), boss_maexxna::boss_maexxnaAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_vortex_ride::npc_vortex_rideAI::UpdateAI(), boss_ormorok::boss_ormorokAI::UpdateAI(), boss_drakos::boss_drakosAI::UpdateAI(), boss_eregos::boss_eregosAI::UpdateAI(), boss_urom::boss_uromAI::UpdateAI(), boss_sjonnir::boss_sjonnirAI::UpdateAI(), boss_sjonnir_malformed_ooze::boss_sjonnir_malformed_oozeAI::UpdateAI(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI(), boss_flame_leviathan::boss_flame_leviathanAI::UpdateAI(), boss_freya::boss_freyaAI::UpdateAI(), boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI::UpdateAI(), boss_vezax::boss_vezaxAI::UpdateAI(), boss_ignis::boss_ignisAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_ulduar_vx001::npc_ulduar_vx001AI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::UpdateAI(), npc_ulduar_emergency_fire_bot::npc_ulduar_emergency_fire_botAI::UpdateAI(), boss_razorscale::boss_razorscaleAI::UpdateAI(), boss_thorim::boss_thorimAI::UpdateAI(), boss_thorim_ancient_rune_giant::boss_thorim_ancient_rune_giantAI::UpdateAI(), boss_xt002::boss_xt002AI::UpdateAI(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateAI(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::UpdateAI(), boss_ymiron::boss_ymironAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_q24545_lich_king::npc_q24545_lich_kingAI::UpdateAI(), npc_venture_co_straggler::npc_venture_co_stragglerAI::UpdateAI(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::UpdateAI(), npc_llod_generic::npc_llod_genericAI::UpdateAI(), npc_infra_green_bomber_generic::npc_infra_green_bomber_genericAI::UpdateAI(), npc_wild_wyrm::npc_wild_wyrmAI::UpdateAI(), npc_freed_protodrake::npc_freed_protodrakeAI::UpdateAI(), npc_feedin_da_goolz::npc_feedin_da_goolzAI::UpdateAI(), npc_crusade_recruit::npc_crusade_recruitAI::UpdateAI(), boss_the_lurker_below::boss_the_lurker_belowAI::UpdateAI(), boss_ahune::boss_ahuneAI::UpdateAI(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::UpdateAI(), boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI::UpdateAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::UpdateAI(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::UpdateAI(), boss_alar::boss_alarAI::UpdateAI(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::UpdateAI(), boss_kaelthas::boss_kaelthasAI::UpdateAI(), npc_nether_drake::npc_nether_drakeAI::UpdateAI(), Player::UpdateAreaDependentAuras(), brann_bronzebeard::brann_bronzebeardAI::UpdateEscortAI(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI(), npc_akama_illidan::npc_akama_illidanAI::UpdateEscortAI(), PathGenerator::UpdateFilter(), Unit::UpdateHeight(), Unit::UpdatePosition(), WorldObject::UpdatePositionData(), GameObject::Use(), Cell::Visit(), Cell::VisitAllObjects(), Cell::VisitGridObjects(), Map::VisitNearbyCellsOf(), Map::VisitNearbyCellsOfPlayer(), Cell::VisitWorldObjects(), npc_barnes::npc_barnesAI::WaypointReached(), npc_cork_gizelton::npc_cork_gizeltonAI::WaypointReached(), and npc_emily::npc_emilyAI::WaypointReached().
GetPositionY()
float Position::GetPositionY () const inline
Definition at line 335 of file Object.h.
 { return m_positionY; }
References m_positionY.
Referenced by WorldObject::_IsWithinDist(), GameObject::_IsWithinDist(), Player::_SaveCharacter(), Player::_SaveEntryPoint(), RandomMovementGenerator< T >::_setRandomLocation(), Player::ActivateTaxiPathTo(), InstanceScript::AddDoor(), Spell::AddGOTarget(), Map::AddPlayerToMap(), Map::AddToMap(), WorldObject::AddToWorld(), Spell::AddUnitTarget(), npc_onyx_flamecaller::npc_onyx_flamecallerAI::AddWaypoints(), TotemAI::AttackStart(), boss_lieutenant_drake::boss_lieutenant_drakeAI::boss_lieutenant_drakeAI(), boss_loatheb::boss_loathebAI::boss_loathebAI(), Unit::BuildMovementPacket(), WorldSession::BuildPartyMemberStatsChangedPacket(), Transport::CalculatePassengerOffset(), Transport::CalculatePassengerPosition(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::CanAIAttack(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::CanAIAttack(), npc_igb_ship_crew::npc_igb_ship_crewAI::CanAIAttack(), npc_gunship_boarding_addAI::CanAIAttack(), boss_professor_putricide::boss_professor_putricideAI::CanAIAttack(), npc_crok_scourgebane::npc_crok_scourgebaneAI::CanAIAttack(), npc_argent_captainAI::CanAIAttack(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::CanAIAttack(), Map::CanReachPositionAndGetValidCoords(), GameObject::CastSpell(), boss_professor_putricide::boss_professor_putricideAI::ChangePhase(), Player::CheckAreaExploreAndOutdoor(), BossAI::CheckBoundary(), Spell::CheckEffectTarget(), boss_supremus::boss_supremusAI::CheckEvadeIfOutOfCombatArea(), boss_gothik::boss_gothikAI::CheckGroupSplitted(), BattlegroundRV::CheckPositionForUnit(), Spell::CheckSpellFocus(), Player::ContinueTaxiFlight(), Map::ConvertCorpseToBones(), Creature::Create(), Corpse::Create(), Pet::CreateBaseAtCreature(), Pet::CreateBaseAtCreatureInfo(), DynamicObject::CreateDynamicObject(), MotionTransport::CreateGOPassenger(), MotionTransport::CreateNPCPassenger(), npc_frost_sphere::npc_frost_sphereAI::DamageTaken(), boss_ick::boss_ickAI::DamageTaken(), npc_power_spark::npc_power_sparkAI::DamageTaken(), npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI::DamageTaken(), boss_viscidus::boss_viscidusAI::DamageTaken(), boss_the_lich_king::boss_the_lich_kingAI::DamageTaken(), boss_thorim::boss_thorimAI::DamageTaken(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::DamageTaken(), npc_icc_spire_frostwyrm::npc_icc_spire_frostwyrmAI::DoAction(), boss_taldaram::boss_taldaramAI::DoAction(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::DoAction(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::DoAction(), npc_bone_spike::npc_bone_spikeAI::DoAction(), boss_professor_putricide::boss_professor_putricideAI::DoAction(), boss_algalon_the_observer::boss_algalon_the_observerAI::DoAction(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::DoAction(), npc_power_spark::npc_power_sparkAI::DoAction(), npc_hover_disk::npc_hover_diskAI::DoAction(), BattlegroundIC::DoAction(), Creature::DoFleeToGetAssistance(), ScriptedAI::DoSpawnCreature(), instance_stratholme::instance_stratholme_InstanceMapScript::DoSpawnPlaguedCritters(), ChaseMovementGenerator< T >::DoUpdate(), Spell::EffectBind(), Spell::EffectDuel(), Spell::EffectLeap(), Spell::EffectPullTowards(), Spell::EffectResurrect(), Spell::EffectResurrectNew(), Spell::EffectTeleUnitsFaceCaster(), Spell::EffectTransmitted(), instance_culling_of_stratholme::instance_culling_of_stratholme_InstanceMapScript::EnsureGridLoaded(), instance_old_hillsbrad::instance_old_hillsbrad_InstanceMapScript::EnsureGridLoaded(), boss_mandokir::boss_mandokirAI::EnterCombat(), boss_professor_putricide::boss_professor_putricideAI::EnterEvadeMode(), BattlegroundIC::EventPlayerClickedOnFlag(), CastArmageddon::Execute(), UtherBatteredHiltEvent::Execute(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::FlyAway(), npc_escortAI::GenerateWaypointArray(), SmartAI::GenerateWayPointArray(), GetAngle(), WorldObject::GetChargeContactPoint(), WorldObject::GetClosePoint(), BattlegroundAB::GetClosestGraveyard(), BattlegroundEY::GetClosestGraveyard(), BattlegroundIC::GetClosestGraveyard(), Graveyard::GetClosestGraveyard(), WorldObject::GetContactPoint(), WorldObject::GetCreaturesWithEntryInRange(), WorldObject::GetDistanceOrder(), WorldObject::GetFloorZ(), WorldObject::GetHitSpherePointFor(), WorldObject::GetNearPoint(), WorldObject::GetNearPoint2D(), boss_volkhan::boss_volkhanAI::GetNextPos(), GameObjectModelOwnerImpl::GetPosition(), GetPositionOffsetTo(), Unit::GetRandomContactPoint(), GameObject::GetRespawnPosition(), Creature::GetRespawnPosition(), GetSinCos(), WorldObject::GetStationaryY(), GameObject::GetStationaryY(), WorldObject::GetTransOffsetY(), npc_simon_bunny::npc_simon_bunnyAI::GivePunishment(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::GoSiphon(), misc_commandscript::HandleAppearCommand(), WorldSession::HandleBattlegroundPlayerPositionsOpcode(), BattlegroundIC::HandleCapturedNodes(), WorldSession::HandleCharFactionOrRaceChangeCallback(), misc_commandscript::HandleComeToMeCommand(), WorldSession::HandleCorpseQueryOpcode(), debug_commandscript::HandleDebugSendOpcodeCommand(), OutdoorPvPSI::HandleDropFlag(), spell_warhead_detonate::spell_warhead_detonate_SpellScript::HandleDummy(), spell_q12589_shoot_rjr::spell_q12589_shoot_rjr_SpellScript::HandleDummy(), spell_dk_death_grip::HandleDummy(), spell_midsummer_torch_quest::spell_midsummer_torch_quest_AuraScript::HandleEffectApply(), spell_q12014_steady_as_a_rock::HandleFinish(), gobject_commandscript::HandleGameObjectAddCommand(), gobject_commandscript::HandleGameObjectAddTempCommand(), gobject_commandscript::HandleGameObjectNearCommand(), gobject_commandscript::HandleGameObjectTargetCommand(), gobject_commandscript::HandleGameObjectTurnCommand(), misc_commandscript::HandleGPSCommand(), list_commandscript::HandleListCreatureCommand(), list_commandscript::HandleListObjectCommand(), mmaps_commandscript::HandleMmapLocCommand(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveTeleportAck(), WorldSession::HandleMoveWorldportAck(), npc_commandscript::HandleNpcAddCommand(), npc_commandscript::HandleNpcAddFormationCommand(), npc_commandscript::HandleNpcInfoCommand(), npc_commandscript::HandleNpcMoveCommand(), npc_commandscript::HandleNpcNearCommand(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandlePlayerLoginToCharInWorld(), WorldSession::HandleRequestPartyMemberStatsOpcode(), misc_commandscript::HandleRespawnCommand(), spell_dreamwalker_summon_portal::spell_dreamwalker_summon_portal_SpellScript::HandleScript(), spell_marrowgar_coldflame_bonestorm::spell_marrowgar_coldflame_SpellScript::HandleScriptEffect(), spell_winter_veil_racer_slam_hit::spell_winter_veil_racer_slam_hit_SpellScript::HandleScriptEffect(), spell_marrowgar_coldflame::spell_marrowgar_coldflame_SpellScript::HandleScriptEffect(), spell_q10612_10613_the_fel_and_the_furious::spell_q10612_10613_the_fel_and_the_furious_SpellScript::HandleScriptEffect(), spell_sindragosa_icy_grip_jump::spell_sindragosa_icy_grip_jump_SpellScript::HandleSpecial(), ArenaSpectator::HandleSpectatorSpectateCommand(), misc_commandscript::HandleSummonCommand(), tele_commandscript::HandleTeleAddCommand(), spell_winter_veil_racer_rocket_slam::spell_winter_veil_racer_rocket_slam_SpellScript::HandleTriggerSpell(), wp_commandscript::HandleWpAddCommand(), debug_commandscript::HandleWPGPSCommand(), wp_commandscript::HandleWpModifyCommand(), HasInLine(), spell_q11065_wrangle_some_aether_rays_aura::if(), boss_captain_skarloc::boss_captain_skarlocAI::InitializeAI(), npc_pos_deathwhisper_necrolyte::npc_pos_deathwhisper_necrolyteAI::InitializeAI(), boss_sapphiron::boss_sapphironAI::InitializeAI(), npc_preparations_for_war_vehicle::npc_preparations_for_war_vehicleAI::InitializeAI(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::InitializeAI(), npc_pet_mage_mirror_image::InitializeAI(), boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::InitWaypoint(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::InstanceCleanup(), GameObject::IsAtInteractDistance(), boss_netherspite::boss_netherspiteAI::IsBetween(), Unit::isInAccessiblePlaceFor(), WorldObject::IsInBetween(), GameObject::IsInRange(), WorldObject::IsInRange(), WorldObject::IsInRange2d(), WorldObject::IsInRange3d(), boss_gothik::boss_gothikAI::IsInRoom(), ScriptedAI::IsInRoom(), boss_heigan::boss_heiganAI::IsInRoom(), WorldObject::IsInWintergrasp(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::IsSummonedBy(), npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::IsSummonedBy(), boss_sartharion::boss_sartharionAI::IsTargetInBounds(), MapMgr::IsValidMapCoord(), go_wg_vehicle_teleporter::go_wg_vehicle_teleporterAI::IsValidVehicle(), IsWithinBox(), Unit::IsWithinCombatRange(), WorldObject::IsWithinLOSInMap(), Unit::IsWithinMeleeRange(), Unit::IsWithinRange(), boss_yauj::boss_yaujAI::JustDied(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::JustDied(), npc_auriaya_feral_defender::npc_auriaya_feral_defenderAI::JustDied(), boss_cyanigosa::boss_cyanigosaAI::JustDied(), npc_artruis_the_hearthless::npc_artruis_the_hearthlessAI::JustDied(), boss_ahune::boss_ahuneAI::JustDied(), npc_enraged_spirit::npc_enraged_spiritAI::JustDied(), boss_noth::boss_nothAI::JustDied(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::JustReachedHome(), boss_kelthuzad::boss_kelthuzadAI::JustSummoned(), boss_yoggsaron_brain::boss_yoggsaron_brainAI::JustSummoned(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::JustSummoned(), npc_daphne_stilwell::npc_daphne_stilwellAI::JustSummoned(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::JustSummoned(), boss_kiljaeden::boss_kiljaedenAI::JustSummoned(), npc_kalecgos_kj::npc_kalecgos_kjAI::JustSummoned(), boss_the_lich_king::boss_the_lich_kingAI::JustSummoned(), boss_algalon_the_observer::boss_algalon_the_observerAI::JustSummoned(), npc_akama_shade::npc_akamaAI::JustSummoned(), boss_lady_vashj::boss_lady_vashjAI::JustSummoned(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::JustSummoned(), npc_maghar_captive::npc_maghar_captiveAI::JustSummoned(), spell_ioc_launch::spell_ioc_launch_SpellScript::Launch(), CreatureGroup::LeaderMoveTo(), Corpse::LoadCorpseFromDB(), Player::LoadFromDB(), LogCommandUsage(), Map::MoveAllDynamicObjectsInMoveList(), Map::MoveAllGameObjectsInMoveList(), MotionMaster::MoveFall(), npc_aged_dying_ancient_kodo::npc_aged_dying_ancient_kodoAI::MoveInLineOfSight(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::MoveInLineOfSight(), npc_hol_monument::npc_hol_monumentAI::MoveInLineOfSight(), npc_ulduar_snow_mound::npc_ulduar_snow_moundAI::MoveInLineOfSight(), MotionMaster::MoveKnockbackFrom(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::MovementInform(), boss_malygos::boss_malygosAI::MovementInform(), npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI::MovementInform(), boss_vazruden_the_herald::boss_vazruden_the_heraldAI::MovementInform(), npc_omen::npc_omenAI::MovementInform(), npc_zelfrax::npc_zelfraxAI::MovementInform(), npc_escortAI::MovementInform(), SmartAI::MovepointReached(), npc_hor_leader_second::npc_hor_leader_secondAI::MoveToNextStopPoint(), npc_ball_of_flame::npc_ball_of_flameAI::npc_ball_of_flameAI(), npc_medivh_bm::npc_medivh_bmAI::npc_medivh_bmAI(), npc_midsummer_bonfire::npc_midsummer_bonfireAI::npc_midsummer_bonfireAI(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::npc_ulduar_flames_initialAI(), npc_vortex_ride::npc_vortex_rideAI::npc_vortex_rideAI(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), instance_naxxramas::instance_naxxramas_InstanceMapScript::OnCreatureCreate(), instance_serpent_shrine::instance_serpentshrine_cavern_InstanceMapScript::OnCreatureCreate(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::OnGameObjectCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectCreate(), instance_naxxramas::instance_naxxramas_InstanceMapScript::OnGameObjectCreate(), instance_naxxramas::instance_naxxramas_InstanceMapScript::OnGameObjectRemove(), go_corkis_prison::OnGossipHello(), go_ethereum_prison::OnGossipHello(), go_ethereum_stasis::OnGossipHello(), go_hive_pod::OnGossipHello(), go_veil_skith_cage::OnGossipHello(), npc_vekjik::OnGossipSelect(), npc_vh_sinclari::OnGossipSelect(), npc_cos_chromie_start::OnGossipSelect(), go_ahune_ice_stone::OnGossipSelect(), go_apexis_relic::OnGossipSelect(), instance_pit_of_saron::instance_pit_of_saron_InstanceScript::OnPlayerEnter(), instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::OnPlayerEnter(), BattlefieldWG::OnPlayerEnterZone(), at_sindragosa_lair::OnTrigger(), at_icc_saurfang_portal::OnTrigger(), AreaTrigger_at_scent_larkorwi::OnTrigger(), at_malfurion_stormrage::OnTrigger(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath(), item_nether_wraith_beacon::OnUse(), Acore::AnyPlayerExactPositionInGameObjectRangeCheck::operator()(), Acore::WorldObjectSpellAreaTargetCheck::operator()(), IgbArtilleryCheck::operator()(), MysticBuffetTargetFilter::operator()(), npc_vortex_ride::npc_vortex_rideAI::PassengerBoarded(), npc_vics_flying_machine::npc_vics_flying_machineAI::PassengerBoarded(), npc_hover_disk::npc_hover_diskAI::PassengerBoarded(), spell_halion_twilight_phasing::spell_halion_twilight_phasing_SpellScript::Phase(), Map::PlayerRelocation(), BattlegroundIC::PostUpdateImpl(), spell_hodir_flash_freeze::spell_hodir_flash_freeze_AuraScript::PrepareAuraScript(), spell_midsummer_ribbon_pole::spell_midsummer_ribbon_pole_AuraScript::PrepareAuraScript(), npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::PrepareEvent(), spell_anti_air_rocket_bomber::spell_anti_air_rocket_bomber_SpellScript::PrepareSpellScript(), npc_jungle_punch_target::npc_jungle_punch_targetAI::proceedCwEvent(), SmartScript::ProcessAction(), npc_dancing_flames::npc_dancing_flamesAI::ReceiveEmote(), spell_quest_dragonmaw_race_generic::RelocateDest(), RelocateOffset(), RelocatePolarOffset(), npc_cork_gizelton::npc_cork_gizeltonAI::RelocateSummons(), Player::RepopAtGraveyard(), boss_kalec::boss_kalecAI::Reset(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::Reset(), npc_janalai_hatcher::npc_janalai_hatcherAI::Reset(), npc_janalai_hatchling::npc_janalai_hatchlingAI::Reset(), npc_zulian_prowler::npc_zulian_prowlerAI::Reset(), npc_brewfest_super_brew_trigger::npc_brewfest_super_brew_triggerAI::Reset(), boss_drakkari_colossus::boss_drakkari_colossusAI::Reset(), npc_crystal_spike::npc_crystal_spikeAI::Reset(), boss_bjarngrim::boss_bjarngrimAI::Reset(), boss_auriaya::boss_auriayaAI::Reset(), boss_freya_nature_bomb::boss_freya_nature_bombAI::Reset(), npc_imprisoned_beryl_sorcerer::npc_imprisoned_beryl_sorcererAI::Reset(), npc_injured_7th_legion_soldier::npc_injured_7th_legion_soldierAI::Reset(), npc_oscillating_frequency_scanner_master_bunny::npc_oscillating_frequency_scanner_master_bunnyAI::Reset(), npc_invis_infernal_caster::npc_invis_infernal_casterAI::Reset(), npc_firework::npc_fireworkAI::Reset(), Player::SavePositionInDB(), Player::SaveRecallPosition(), CharmInfo::SaveStayPosition(), Corpse::SaveToDB(), Creature::SaveToDB(), GameObject::SaveToDB(), boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::Say(), boss_yoggsaron_llane::boss_yoggsaron_llaneAI::Say(), boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI::Say(), boss_skadi_grauf::boss_skadi_graufAI::SelectNextPos(), PassengerController::SelectSpawnPoint(), boss_sartharion::boss_sartharionAI::SendLavaWaves(), WorldSession::SendLearnNewTaxiNode(), Unit::SendMonsterMove(), WorldSession::SendTaxiMenu(), WorldSession::SendTaxiStatus(), Unit::SendTeleportPacket(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SetBossState(), npc_ulduar_harpoonfirestate::npc_ulduar_harpoonfirestateAI::SetData(), instance_hyjal::instance_mount_hyjal_InstanceMapScript::SetData(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::SetData(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::SetData(), npc_idol_room_spawner::npc_idol_room_spawnerAI::SetData(), npc_ulduar_mimiron_rocket::npc_ulduar_mimiron_rocketAI::SetData(), spell_blood_council_summon_shadow_resonance::spell_blood_council_summon_shadow_resonance_SpellScript::SetDest(), spell_dk_summon_gargoyle::SetDest(), Player::SetEntryPoint(), Unit::SetFacingTo(), Unit::SetFacingToObject(), Unit::SetHover(), Unit::SetInCombatState(), npc_your_inner_turmoil::npc_your_inner_turmoilAI::setphase(), PathGenerator::ShortenPathUntilDist(), boss_thorim::boss_thorimAI::SpawnArenaNPCs(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::SpawnClouds(), instance_ulduar::instance_ulduar_InstanceMapScript::SpawnHodirChests(), boss_ossirian::boss_ossirianAI::SpawnNextCrystal(), instance_zulfarrak::instance_zulfarrak_InstanceMapScript::SpawnPyramidWave(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::SpawnTentacle(), boss_freya::boss_freyaAI::SpawnWave(), npc_varian_wrynn::npc_varian_wrynnAI::SpawnWave(), boss_headless_horseman_pumpkin::boss_headless_horseman_pumpkinAI::SpellHit(), boss_majordomo::boss_majordomoAI::SpellHit(), npc_wounded_skirmisher::npc_wounded_skirmisherAI::SpellHit(), npc_wild_wyrm::npc_wild_wyrmAI::SpellHit(), npc_forest_frog::npc_forest_frogAI::SpellHit(), npc_troll_volunteer::npc_troll_volunteerAI::SpellHit(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::SpellHit(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::SpellHitTarget(), npc_nerubian_burrower::npc_nerubian_burrowerAI::SpellHitTarget(), npc_pos_leader_second::npc_pos_leader_secondAI::SpellHitTarget(), boss_freya::boss_freyaAI::SpellHitTarget(), boss_cyanigosa::boss_cyanigosaAI::SpellHitTarget(), boss_attumen::boss_attumenAI::SpellHitTarget(), boss_grobbulus::boss_grobbulusAI::SpellHitTarget(), npc_xt002_heart::npc_xt002_heartAI::SpellHitTarget(), boss_ionar::boss_ionarAI::Split(), Unit::StopMovingOnCurrentPos(), instance_blood_furnace::instance_blood_furnace_InstanceMapScript::StorePrisoner(), boss_malchezaar::boss_malchezaarAI::SummonAxes(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonBroodling(), boss_anzu::boss_anzuAI::SummonBroods(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::SummonDeathOrbs(), boss_archimonde::boss_archimondeAI::SummonDoomfire(), boss_sjonnir::boss_sjonnirAI::SummonDwarfes(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::SummonedCreatureDies(), boss_yoggsaron::boss_yoggsaronAI::SummonImmortalGuardian(), npc_invis_infernal_caster::npc_invis_infernal_casterAI::SummonInfernal(), boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI::SummonMechanics(), go_wind_stone::go_wind_stoneAI::SummonNPC(), go_tadpole_cage::go_tadpole_cageAI::SummonTadpoles(), Map::SwitchGridContainers(), Player::TeleportTo(), BattlegroundRV::TeleportUnitToNewZ(), CreatureAI::TriggerAlert(), MotionTransport::Update(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::Update(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::Update(), instance_violet_hold::instance_violet_hold_InstanceMapScript::Update(), Creature::Update(), Player::Update(), npc_av_marshal_or_warmaster::npc_av_marshal_or_warmasterAI::UpdateAI(), npc_eye_of_acherus::npc_eye_of_acherusAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), boss_sacrolash::boss_sacrolashAI::UpdateAI(), boss_felmyst::boss_felmystAI::UpdateAI(), boss_kiljaeden::boss_kiljaedenAI::UpdateAI(), npc_highborne_lamenter::npc_highborne_lamenterAI::UpdateAI(), npc_forest_frog::npc_forest_frogAI::UpdateAI(), boss_jindo::boss_jindoAI::UpdateAI(), boss_renataki::boss_renatakiAI::UpdateAI(), npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::UpdateAI(), npc_dark_iron_attack_mole_machine::npc_dark_iron_attack_mole_machineAI::UpdateAI(), npc_winterfin_playmate::npc_winterfin_playmateAI::UpdateAI(), npc_snowfall_glade_playmate::npc_snowfall_glade_playmateAI::UpdateAI(), npc_the_biggest_tree::npc_the_biggest_treeAI::UpdateAI(), npc_high_oracle_soo_roo::npc_high_oracle_soo_rooAI::UpdateAI(), npc_elder_kekek::npc_elder_kekekAI::UpdateAI(), npc_the_etymidian::npc_the_etymidianAI::UpdateAI(), npc_alexstraza_the_lifebinder::npc_alexstraza_the_lifebinderAI::UpdateAI(), npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::UpdateAI(), boss_azuregos::boss_azuregosAI::UpdateAI(), hyjalAI::UpdateAI(), npc_medivh_bm::npc_medivh_bmAI::UpdateAI(), boss_cthun::cthunAI::UpdateAI(), npc_claw_tentacle::claw_tentacleAI::UpdateAI(), npc_giant_claw_tentacle::giant_claw_tentacleAI::UpdateAI(), boss_ouro::boss_ouroAI::UpdateAI(), boss_viscidus::boss_viscidusAI::UpdateAI(), npc_murkdeep::npc_murkdeepAI::UpdateAI(), boss_elder_nadox::boss_elder_nadoxAI::UpdateAI(), npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::UpdateAI(), boss_saviana_ragefire::boss_saviana_ragefireAI::UpdateAI(), npc_frost_sphere::npc_frost_sphereAI::UpdateAI(), boss_icehowl::boss_icehowlAI::UpdateAI(), npc_hor_lich_king::npc_hor_lich_kingAI::UpdateAI(), boss_garfrost::boss_garfrostAI::UpdateAI(), boss_krick::boss_krickAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), npc_pos_after_first_boss::npc_pos_after_first_bossAI::UpdateAI(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::UpdateAI(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::UpdateAI(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::UpdateAI(), boss_lord_marrowgar::UpdateAI(), npc_coldflame::npc_coldflameAI::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), boss_sindragosa::boss_sindragosaAI::UpdateAI(), npc_rimefang::npc_rimefangAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::UpdateAI(), boss_maexxna::boss_maexxnaAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_vortex_ride::npc_vortex_rideAI::UpdateAI(), boss_ormorok::boss_ormorokAI::UpdateAI(), boss_drakos::boss_drakosAI::UpdateAI(), boss_eregos::boss_eregosAI::UpdateAI(), boss_urom::boss_uromAI::UpdateAI(), boss_sjonnir::boss_sjonnirAI::UpdateAI(), boss_sjonnir_malformed_ooze::boss_sjonnir_malformed_oozeAI::UpdateAI(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI(), boss_freya::boss_freyaAI::UpdateAI(), boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI::UpdateAI(), boss_vezax::boss_vezaxAI::UpdateAI(), boss_hodir::boss_hodirAI::UpdateAI(), boss_ignis::boss_ignisAI::UpdateAI(), boss_mimiron::boss_mimironAI::UpdateAI(), npc_ulduar_vx001::npc_ulduar_vx001AI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), npc_ulduar_flames_initial::npc_ulduar_flames_initialAI::UpdateAI(), npc_ulduar_emergency_fire_bot::npc_ulduar_emergency_fire_botAI::UpdateAI(), boss_razorscale::boss_razorscaleAI::UpdateAI(), boss_thorim::boss_thorimAI::UpdateAI(), boss_thorim_ancient_rune_giant::boss_thorim_ancient_rune_giantAI::UpdateAI(), boss_xt002::boss_xt002AI::UpdateAI(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateAI(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::UpdateAI(), boss_ymiron::boss_ymironAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_q24545_lich_king::npc_q24545_lich_kingAI::UpdateAI(), npc_venture_co_straggler::npc_venture_co_stragglerAI::UpdateAI(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::UpdateAI(), npc_llod_generic::npc_llod_genericAI::UpdateAI(), npc_infra_green_bomber_generic::npc_infra_green_bomber_genericAI::UpdateAI(), npc_wild_wyrm::npc_wild_wyrmAI::UpdateAI(), npc_freed_protodrake::npc_freed_protodrakeAI::UpdateAI(), npc_feedin_da_goolz::npc_feedin_da_goolzAI::UpdateAI(), npc_crusade_recruit::npc_crusade_recruitAI::UpdateAI(), boss_the_lurker_below::boss_the_lurker_belowAI::UpdateAI(), boss_ahune::boss_ahuneAI::UpdateAI(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::UpdateAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::UpdateAI(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::UpdateAI(), boss_alar::boss_alarAI::UpdateAI(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::UpdateAI(), boss_kaelthas::boss_kaelthasAI::UpdateAI(), npc_nether_drake::npc_nether_drakeAI::UpdateAI(), brann_bronzebeard::brann_bronzebeardAI::UpdateEscortAI(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI(), npc_akama_illidan::npc_akama_illidanAI::UpdateEscortAI(), PathGenerator::UpdateFilter(), Unit::UpdateHeight(), Unit::UpdatePosition(), WorldObject::UpdatePositionData(), GameObject::Use(), Cell::Visit(), Cell::VisitAllObjects(), Cell::VisitGridObjects(), Map::VisitNearbyCellsOf(), Map::VisitNearbyCellsOfPlayer(), Cell::VisitWorldObjects(), npc_barnes::npc_barnesAI::WaypointReached(), npc_cork_gizelton::npc_cork_gizeltonAI::WaypointReached(), and npc_emily::npc_emilyAI::WaypointReached().
GetPositionZ()
float Position::GetPositionZ () const inline
Definition at line 336 of file Object.h.
 { return m_positionZ; }
References m_positionZ.
Referenced by Unit::_ExitVehicle(), WorldObject::_IsWithinDist(), GameObject::_IsWithinDist(), Player::_SaveCharacter(), Player::_SaveEntryPoint(), RandomMovementGenerator< T >::_setRandomLocation(), Player::ActivateTaxiPathTo(), Spell::AddGOTarget(), WorldObject::AddToWorld(), Spell::AddUnitTarget(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::AttackStart(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::AttackStart(), boss_lieutenant_drake::boss_lieutenant_drakeAI::boss_lieutenant_drakeAI(), boss_loatheb::boss_loathebAI::boss_loathebAI(), Unit::BuildMovementPacket(), PathGenerator::BuildPointPath(), Transport::CalculatePassengerOffset(), Transport::CalculatePassengerPosition(), boss_devourer_of_souls::boss_devourer_of_soulsAI::CanAIAttack(), npc_igb_ship_crew::npc_igb_ship_crewAI::CanAIAttack(), npc_gunship_boarding_addAI::CanAIAttack(), boss_professor_putricide::boss_professor_putricideAI::CanAIAttack(), boss_thorim_arena_npcs::boss_thorim_arena_npcsAI::CanAIAttack(), boss_kalecgos::boss_kalecgosAI::CanAIAttack(), boss_sathrovarr::boss_sathrovarrAI::CanAIAttack(), npc_icc_spire_frostwyrm::npc_icc_spire_frostwyrmAI::CanAIAttack(), Map::CanReachPositionAndGetValidCoords(), GameObject::CastSpell(), boss_professor_putricide::boss_professor_putricideAI::ChangePhase(), Player::CheckAreaExploreAndOutdoor(), Spell::CheckCast(), Spell::CheckEffectTarget(), boss_midnight::boss_midnightAI::CheckEvadeIfOutOfCombatArea(), boss_janalai::boss_janalaiAI::CheckEvadeIfOutOfCombatArea(), BattlegroundRV::CheckPositionForUnit(), boss_isle_of_conquest::boss_isle_of_conquestAI::CheckRageBuff(), Player::ContinueTaxiFlight(), Map::ConvertCorpseToBones(), Creature::Create(), Corpse::Create(), Pet::CreateBaseAtCreature(), Pet::CreateBaseAtCreatureInfo(), MotionTransport::CreateNPCPassenger(), boss_ick::boss_ickAI::DamageTaken(), npc_power_spark::npc_power_sparkAI::DamageTaken(), boss_razorscale::boss_razorscaleAI::DamageTaken(), npc_ulduar_arachnopod_destroyer::npc_ulduar_arachnopod_destroyerAI::DamageTaken(), npc_ice_tomb::npc_ice_tombAI::DamageTaken(), boss_thorim::boss_thorimAI::DamageTaken(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::DamageTaken(), npc_kinetic_bomb::npc_kinetic_bombAI::DoAction(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::DoAction(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::DoAction(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::DoAction(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::DoAction(), npc_bone_spike::npc_bone_spikeAI::DoAction(), boss_professor_putricide::boss_professor_putricideAI::DoAction(), boss_algalon_the_observer::boss_algalon_the_observerAI::DoAction(), npc_power_spark::npc_power_sparkAI::DoAction(), npc_hover_disk::npc_hover_diskAI::DoAction(), BattlegroundIC::DoAction(), FlightPathMovementGenerator::DoFinalize(), Creature::DoFleeToGetAssistance(), ScriptedAI::DoSpawnCreature(), instance_stratholme::instance_stratholme_InstanceMapScript::DoSpawnPlaguedCritters(), FlightPathMovementGenerator::DoUpdate(), ChaseMovementGenerator< T >::DoUpdate(), Spell::EffectBind(), Spell::EffectCharge(), Spell::EffectDuel(), Spell::EffectLeap(), Spell::EffectLeapBack(), Spell::EffectPullTowards(), Spell::EffectResurrect(), Spell::EffectResurrectNew(), Spell::EffectSummonType(), Spell::EffectTeleUnitsFaceCaster(), Spell::EffectTransmitted(), boss_mandokir::boss_mandokirAI::EnterCombat(), boss_professor_putricide::boss_professor_putricideAI::EnterEvadeMode(), BattlegroundIC::EventPlayerClickedOnFlag(), CastArmageddon::Execute(), UtherBatteredHiltEvent::Execute(), boss_sartharion_tenebron::boss_sartharion_tenebronAI::ExecuteEvent(), boss_sartharion_shadron::boss_sartharion_shadronAI::ExecuteEvent(), boss_sartharion_vesperon::boss_sartharion_vesperonAI::ExecuteEvent(), DynObjAura::FillTargetMap(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::FlyAway(), npc_escortAI::GenerateWaypointArray(), SmartAI::GenerateWayPointArray(), WorldObject::GetChargeContactPoint(), WorldObject::GetClosePoint(), BattlegroundEY::GetClosestGraveyard(), Graveyard::GetClosestGraveyard(), WorldObject::GetContactPoint(), WorldObject::GetDistanceOrder(), WorldObject::GetDistanceZ(), WorldObject::GetFloorZ(), WorldObject::GetHitSpherePointFor(), WorldObject::GetNearPoint(), GameObjectModelOwnerImpl::GetPosition(), GetPositionOffsetTo(), Unit::GetRandomContactPoint(), GameObject::GetRespawnPosition(), Creature::GetRespawnPosition(), WorldObject::GetStationaryZ(), GameObject::GetStationaryZ(), WorldObject::GetTransOffsetZ(), npc_simon_bunny::npc_simon_bunnyAI::GivePunishment(), misc_commandscript::HandleAppearCommand(), AuraEffect::HandleAuraFeatherFall(), BattlegroundIC::HandleCapturedNodes(), WorldSession::HandleCharFactionOrRaceChangeCallback(), misc_commandscript::HandleComeToMeCommand(), WorldSession::HandleCorpseQueryOpcode(), debug_commandscript::HandleDebugSendOpcodeCommand(), OutdoorPvPSI::HandleDropFlag(), spell_q12589_shoot_rjr::spell_q12589_shoot_rjr_SpellScript::HandleDummy(), spell_dk_death_grip::HandleDummy(), spell_item_underbelly_elixir::HandleDummy(), spell_midsummer_torch_quest::spell_midsummer_torch_quest_AuraScript::HandleEffectApply(), spell_z_check::spell_z_check_AuraScript::HandleEffectApply(), Player::HandleFall(), spell_q12014_steady_as_a_rock::HandleFinish(), gobject_commandscript::HandleGameObjectAddCommand(), gobject_commandscript::HandleGameObjectAddTempCommand(), gobject_commandscript::HandleGameObjectNearCommand(), gobject_commandscript::HandleGameObjectTargetCommand(), gobject_commandscript::HandleGameObjectTurnCommand(), misc_commandscript::HandleGPSCommand(), list_commandscript::HandleListCreatureCommand(), list_commandscript::HandleListObjectCommand(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveTeleportAck(), WorldSession::HandleMoveWorldportAck(), npc_commandscript::HandleNpcAddCommand(), npc_commandscript::HandleNpcInfoCommand(), npc_commandscript::HandleNpcMoveCommand(), npc_commandscript::HandleNpcNearCommand(), WorldSession::HandlePlayerLoginFromDB(), WorldSession::HandlePlayerLoginToCharInWorld(), spell_dreamwalker_summon_portal::spell_dreamwalker_summon_portal_SpellScript::HandleScript(), spell_marrowgar_coldflame_bonestorm::spell_marrowgar_coldflame_SpellScript::HandleScriptEffect(), spell_yogg_saron_sanity_reduce::spell_yogg_saron_sanity_reduce_SpellScript::HandleScriptEffect(), spell_winter_veil_racer_slam_hit::spell_winter_veil_racer_slam_hit_SpellScript::HandleScriptEffect(), spell_marrowgar_coldflame::spell_marrowgar_coldflame_SpellScript::HandleScriptEffect(), spell_q10612_10613_the_fel_and_the_furious::spell_q10612_10613_the_fel_and_the_furious_SpellScript::HandleScriptEffect(), spell_sindragosa_icy_grip_jump::spell_sindragosa_icy_grip_jump_SpellScript::HandleSpecial(), ArenaSpectator::HandleSpectatorSpectateCommand(), boss_akilzon::boss_akilzonAI::HandleStormSequence(), misc_commandscript::HandleSummonCommand(), tele_commandscript::HandleTeleAddCommand(), wp_commandscript::HandleWpAddCommand(), debug_commandscript::HandleWPGPSCommand(), wp_commandscript::HandleWpModifyCommand(), spell_q11065_wrangle_some_aether_rays_aura::if(), boss_captain_skarloc::boss_captain_skarlocAI::InitializeAI(), boss_sapphiron::boss_sapphironAI::InitializeAI(), npc_preparations_for_war_vehicle::npc_preparations_for_war_vehicleAI::InitializeAI(), npc_pet_dk_ebon_gargoyle::npc_pet_dk_ebon_gargoyleAI::InitializeAI(), npc_pet_mage_mirror_image::InitializeAI(), boss_yoggsaron_cloud::boss_yoggsaron_cloudAI::InitWaypoint(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::InstanceCleanup(), GameObject::IsAtInteractDistance(), Player::IsFalling(), SpellArea::IsFitToRequirements(), Unit::isInAccessiblePlaceFor(), GameObject::IsInRange(), WorldObject::IsInRange(), WorldObject::IsInRange3d(), boss_algalon_the_observer::boss_algalon_the_observerAI::IsInRoom(), PathGenerator::IsInvalidDestinationZ(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::IsSummonedBy(), npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::IsSummonedBy(), MapMgr::IsValidMapCoord(), IsValidPlatformTarget(), go_wg_vehicle_teleporter::go_wg_vehicle_teleporterAI::IsValidVehicle(), IsWithinBox(), Unit::IsWithinCombatRange(), WorldObject::IsWithinLOSInMap(), Unit::IsWithinMeleeRange(), Unit::IsWithinRange(), boss_yauj::boss_yaujAI::JustDied(), npc_auriaya_feral_defender::npc_auriaya_feral_defenderAI::JustDied(), boss_cyanigosa::boss_cyanigosaAI::JustDied(), npc_artruis_the_hearthless::npc_artruis_the_hearthlessAI::JustDied(), boss_ahune::boss_ahuneAI::JustDied(), npc_enraged_spirit::npc_enraged_spiritAI::JustDied(), boss_noth::boss_nothAI::JustDied(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::JustReachedHome(), boss_kelthuzad::boss_kelthuzadAI::JustSummoned(), npc_overlord_drakuru_betrayal::npc_overlord_drakuru_betrayalAI::JustSummoned(), npc_daphne_stilwell::npc_daphne_stilwellAI::JustSummoned(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::JustSummoned(), boss_kiljaeden::boss_kiljaedenAI::JustSummoned(), npc_kalecgos_kj::npc_kalecgos_kjAI::JustSummoned(), boss_the_lich_king::boss_the_lich_kingAI::JustSummoned(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::JustSummoned(), boss_algalon_the_observer::boss_algalon_the_observerAI::JustSummoned(), npc_akama_shade::npc_akamaAI::JustSummoned(), boss_lady_vashj::boss_lady_vashjAI::JustSummoned(), npc_lady_sylvanas_windrunner::npc_lady_sylvanas_windrunnerAI::JustSummoned(), npc_maghar_captive::npc_maghar_captiveAI::JustSummoned(), spell_svalna_revive_champion::spell_svalna_revive_champion_SpellScript::Land(), spell_ioc_launch::spell_ioc_launch_SpellScript::Launch(), Player::LoadFromDB(), LogCommandUsage(), MotionMaster::MoveFall(), npc_grand_magister_rommath::npc_grand_magister_rommathAI::MoveInLineOfSight(), npc_aged_dying_ancient_kodo::npc_aged_dying_ancient_kodoAI::MoveInLineOfSight(), boss_krik_thir::boss_krik_thirAI::MoveInLineOfSight(), npc_brann_radio::npc_brann_radioAI::MoveInLineOfSight(), npc_ulduar_snow_mound::npc_ulduar_snow_moundAI::MoveInLineOfSight(), npc_mageguard_dalaran::npc_mageguard_dalaranAI::MoveInLineOfSight(), MotionMaster::MoveKnockbackFrom(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::MovementInform(), boss_malygos::boss_malygosAI::MovementInform(), npc_hover_disk::npc_hover_diskAI::MovementInform(), npc_enslaved_proto_drake::npc_enslaved_proto_drakeAI::MovementInform(), boss_vazruden_the_herald::boss_vazruden_the_heraldAI::MovementInform(), npc_omen::npc_omenAI::MovementInform(), npc_zelfrax::npc_zelfraxAI::MovementInform(), npc_escortAI::MovementInform(), SmartAI::MovepointReached(), npc_concentrated_ball::npc_concentrated_ballAI::MoveToNextPoint(), npc_hor_leader_second::npc_hor_leader_secondAI::MoveToNextStopPoint(), npc_ball_of_flame::npc_ball_of_flameAI::npc_ball_of_flameAI(), npc_icc_vengeful_fleshreaper::npc_icc_vengeful_fleshreaperAI::npc_icc_vengeful_fleshreaperAI(), npc_medivh_bm::npc_medivh_bmAI::npc_medivh_bmAI(), npc_midsummer_bonfire::npc_midsummer_bonfireAI::npc_midsummer_bonfireAI(), npc_vortex_ride::npc_vortex_rideAI::npc_vortex_rideAI(), instance_blackrock_depths::instance_blackrock_depths_InstanceMapScript::OnCreatureCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnCreatureCreate(), instance_sunken_temple::instance_sunken_temple_InstanceMapScript::OnGameObjectCreate(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnGameObjectCreate(), go_corkis_prison::OnGossipHello(), go_ethereum_prison::OnGossipHello(), go_ethereum_stasis::OnGossipHello(), go_hive_pod::OnGossipHello(), go_veil_skith_cage::OnGossipHello(), npc_vh_sinclari::OnGossipSelect(), npc_cos_chromie_start::OnGossipSelect(), go_apexis_relic::OnGossipSelect(), spell_yogg_saron_brain_link::spell_yogg_saron_brain_link_AuraScript::OnPeriodic(), instance_eye_of_eternity::instance_eye_of_eternity_InstanceMapScript::OnPlayerEnter(), at_icc_saurfang_portal::OnTrigger(), AreaTrigger_at_scent_larkorwi::OnTrigger(), at_malfurion_stormrage::OnTrigger(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::OnUnitDeath(), item_nether_wraith_beacon::OnUse(), RotfaceHeightCheck::operator()(), Acore::AnyPlayerExactPositionInGameObjectRangeCheck::operator()(), Acore::WorldObjectSpellAreaTargetCheck::operator()(), SpectralBlastCheck::operator()(), IgbArtilleryCheck::operator()(), MysticBuffetTargetFilter::operator()(), HeightDifferenceCheck::operator()(), npc_vortex_ride::npc_vortex_rideAI::PassengerBoarded(), npc_vics_flying_machine::npc_vics_flying_machineAI::PassengerBoarded(), spell_halion_twilight_phasing::spell_halion_twilight_phasing_SpellScript::Phase(), BattlegroundIC::PostUpdateImpl(), spell_hodir_flash_freeze::spell_hodir_flash_freeze_AuraScript::PrepareAuraScript(), spell_midsummer_ribbon_pole::spell_midsummer_ribbon_pole_AuraScript::PrepareAuraScript(), npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::PrepareEvent(), spell_anti_air_rocket_bomber::spell_anti_air_rocket_bomber_SpellScript::PrepareSpellScript(), npc_jungle_punch_target::npc_jungle_punch_targetAI::proceedCwEvent(), SmartScript::ProcessAction(), npc_dancing_flames::npc_dancing_flamesAI::ReceiveEmote(), spell_quest_dragonmaw_race_generic::RelocateDest(), RelocateOffset(), RelocatePolarOffset(), npc_cork_gizelton::npc_cork_gizeltonAI::RelocateSummons(), Player::RepopAtGraveyard(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::Reset(), boss_mandokir::boss_mandokirAI::Reset(), npc_brewfest_super_brew_trigger::npc_brewfest_super_brew_triggerAI::Reset(), boss_drakkari_colossus::boss_drakkari_colossusAI::Reset(), npc_crystal_spike::npc_crystal_spikeAI::Reset(), boss_bjarngrim::boss_bjarngrimAI::Reset(), boss_auriaya::boss_auriayaAI::Reset(), boss_freya_nature_bomb::boss_freya_nature_bombAI::Reset(), boss_thorim_runic_colossus::boss_thorim_runic_colossusAI::Reset(), npc_oscillating_frequency_scanner_master_bunny::npc_oscillating_frequency_scanner_master_bunnyAI::Reset(), npc_invis_infernal_caster::npc_invis_infernal_casterAI::Reset(), npc_dancing_flames::npc_dancing_flamesAI::Reset(), Player::SavePositionInDB(), Player::SaveRecallPosition(), CharmInfo::SaveStayPosition(), Corpse::SaveToDB(), Creature::SaveToDB(), GameObject::SaveToDB(), boss_yoggsaron_lich_king::boss_yoggsaron_lich_kingAI::Say(), boss_yoggsaron_llane::boss_yoggsaron_llaneAI::Say(), boss_yoggsaron_neltharion::boss_yoggsaron_neltharionAI::Say(), boss_gluth::boss_gluthAI::SelectPlayerInRoom(), PassengerController::SelectSpawnPoint(), boss_sartharion::boss_sartharionAI::SendLavaWaves(), WorldSession::SendLearnNewTaxiNode(), Unit::SendMonsterMove(), WorldSession::SendTaxiMenu(), WorldSession::SendTaxiStatus(), Unit::SendTeleportPacket(), Player::SetCanFly(), Creature::SetCanFly(), npc_ulduar_harpoonfirestate::npc_ulduar_harpoonfirestateAI::SetData(), instance_hyjal::instance_mount_hyjal_InstanceMapScript::SetData(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::SetData(), npc_idol_room_spawner::npc_idol_room_spawnerAI::SetData(), npc_ulduar_mimiron_rocket::npc_ulduar_mimiron_rocketAI::SetData(), spell_blood_council_summon_shadow_resonance::spell_blood_council_summon_shadow_resonance_SpellScript::SetDest(), spell_dk_summon_gargoyle::SetDest(), Player::SetEntryPoint(), Unit::SetFacingTo(), Unit::SetFacingToObject(), Unit::SetHover(), Unit::SetInCombatState(), npc_your_inner_turmoil::npc_your_inner_turmoilAI::setphase(), PathGenerator::ShortenPathUntilDist(), boss_thorim::boss_thorimAI::SpawnArenaNPCs(), instance_ulduar::instance_ulduar_InstanceMapScript::SpawnHodirChests(), boss_ossirian::boss_ossirianAI::SpawnNextCrystal(), boss_freya::boss_freyaAI::SpawnWave(), npc_varian_wrynn::npc_varian_wrynnAI::SpawnWave(), boss_headless_horseman_pumpkin::boss_headless_horseman_pumpkinAI::SpellHit(), boss_majordomo::boss_majordomoAI::SpellHit(), npc_wounded_skirmisher::npc_wounded_skirmisherAI::SpellHit(), npc_wild_wyrm::npc_wild_wyrmAI::SpellHit(), npc_forest_frog::npc_forest_frogAI::SpellHit(), npc_troll_volunteer::npc_troll_volunteerAI::SpellHit(), npc_deaths_door_fell_cannon_target_bunny::npc_deaths_door_fell_cannon_target_bunnyAI::SpellHit(), npc_frostwing_vrykul::npc_frostwing_vrykulAI::SpellHitTarget(), npc_nerubian_burrower::npc_nerubian_burrowerAI::SpellHitTarget(), npc_pos_leader_second::npc_pos_leader_secondAI::SpellHitTarget(), boss_freya::boss_freyaAI::SpellHitTarget(), boss_cyanigosa::boss_cyanigosaAI::SpellHitTarget(), boss_attumen::boss_attumenAI::SpellHitTarget(), boss_grobbulus::boss_grobbulusAI::SpellHitTarget(), npc_xt002_heart::npc_xt002_heartAI::SpellHitTarget(), boss_ionar::boss_ionarAI::Split(), Unit::StopMovingOnCurrentPos(), boss_malchezaar::boss_malchezaarAI::SummonAxes(), boss_anzu::boss_anzuAI::SummonBroods(), SummonCroneIfReady(), boss_archimonde::boss_archimondeAI::SummonDoomfire(), boss_sjonnir::boss_sjonnirAI::SummonDwarfes(), npc_kiljaeden_controller::npc_kiljaeden_controllerAI::SummonedCreatureDies(), boss_mekgineer_steamrigger::boss_mekgineer_steamriggerAI::SummonMechanics(), go_wind_stone::go_wind_stoneAI::SummonNPC(), go_tadpole_cage::go_tadpole_cageAI::SummonTadpoles(), Player::TeleportTo(), instance_trial_of_the_crusader::instance_trial_of_the_crusader_InstanceMapScript::Update(), instance_halls_of_reflection::instance_halls_of_reflection_InstanceMapScript::Update(), instance_violet_hold::instance_violet_hold_InstanceMapScript::Update(), Creature::Update(), Player::Update(), npc_eye_of_acherus::npc_eye_of_acherusAI::UpdateAI(), npc_unworthy_initiate::npc_unworthy_initiateAI::UpdateAI(), npc_highlord_darion_mograine::npc_highlord_darion_mograineAI::UpdateAI(), boss_sacrolash::boss_sacrolashAI::UpdateAI(), boss_felmyst::boss_felmystAI::UpdateAI(), boss_akilzon::boss_akilzonAI::UpdateAI(), boss_arlokk::boss_arlokkAI::UpdateAI(), boss_jindo::boss_jindoAI::UpdateAI(), boss_renataki::boss_renatakiAI::UpdateAI(), npc_dark_iron_attack_generator::npc_dark_iron_attack_generatorAI::UpdateAI(), npc_dark_iron_attack_mole_machine::npc_dark_iron_attack_mole_machineAI::UpdateAI(), npc_winterfin_playmate::npc_winterfin_playmateAI::UpdateAI(), npc_snowfall_glade_playmate::npc_snowfall_glade_playmateAI::UpdateAI(), npc_the_biggest_tree::npc_the_biggest_treeAI::UpdateAI(), npc_high_oracle_soo_roo::npc_high_oracle_soo_rooAI::UpdateAI(), npc_elder_kekek::npc_elder_kekekAI::UpdateAI(), npc_the_etymidian::npc_the_etymidianAI::UpdateAI(), npc_alexstraza_the_lifebinder::npc_alexstraza_the_lifebinderAI::UpdateAI(), npc_pilgrims_bounty_chair::npc_pilgrims_bounty_chairAI::UpdateAI(), boss_azuregos::boss_azuregosAI::UpdateAI(), npc_medivh_bm::npc_medivh_bmAI::UpdateAI(), boss_cthun::cthunAI::UpdateAI(), npc_claw_tentacle::claw_tentacleAI::UpdateAI(), npc_giant_claw_tentacle::giant_claw_tentacleAI::UpdateAI(), boss_ouro::boss_ouroAI::UpdateAI(), boss_viscidus::boss_viscidusAI::UpdateAI(), npc_murkdeep::npc_murkdeepAI::UpdateAI(), boss_elder_nadox::boss_elder_nadoxAI::UpdateAI(), npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::UpdateAI(), boss_saviana_ragefire::boss_saviana_ragefireAI::UpdateAI(), boss_jormungarAI::UpdateAI(), boss_icehowl::boss_icehowlAI::UpdateAI(), npc_hor_lich_king::npc_hor_lich_kingAI::UpdateAI(), boss_garfrost::boss_garfrostAI::UpdateAI(), boss_ick::boss_ickAI::UpdateAI(), boss_krick::boss_krickAI::UpdateAI(), boss_tyrannus::boss_tyrannusAI::UpdateAI(), npc_pos_leader::npc_pos_leaderAI::UpdateAI(), npc_pos_after_first_boss::npc_pos_after_first_bossAI::UpdateAI(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::UpdateAI(), npc_high_overlord_saurfang_icc::npc_high_overlord_saurfangAI::UpdateAI(), npc_muradin_bronzebeard_icc::npc_muradin_bronzebeard_iccAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), boss_lord_marrowgar::UpdateAI(), boss_professor_putricide::boss_professor_putricideAI::UpdateAI(), npc_putricide_oozeAI::UpdateAI(), boss_sindragosa::boss_sindragosaAI::UpdateAI(), npc_rimefang::npc_rimefangAI::UpdateAI(), boss_the_lich_king::boss_the_lich_kingAI::UpdateAI(), npc_tirion_fordring_tft::npc_tirion_fordringAI::UpdateAI(), npc_icc_ice_sphere::npc_icc_ice_sphereAI::UpdateAI(), npc_strangulate_vehicle::npc_strangulate_vehicleAI::UpdateAI(), boss_maexxna::boss_maexxnaAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_vortex_ride::npc_vortex_rideAI::UpdateAI(), boss_ormorok::boss_ormorokAI::UpdateAI(), boss_drakos::boss_drakosAI::UpdateAI(), boss_eregos::boss_eregosAI::UpdateAI(), boss_urom::boss_uromAI::UpdateAI(), boss_sjonnir::boss_sjonnirAI::UpdateAI(), boss_sjonnir_malformed_ooze::boss_sjonnir_malformed_oozeAI::UpdateAI(), boss_stormcaller_brundir::boss_stormcaller_brundirAI::UpdateAI(), boss_freya::boss_freyaAI::UpdateAI(), boss_freya_elder_brightleaf::boss_freya_elder_brightleafAI::UpdateAI(), npc_ulduar_hodir_druid::npc_ulduar_hodir_druidAI::UpdateAI(), npc_ulduar_vx001::npc_ulduar_vx001AI::UpdateAI(), boss_razorscale::boss_razorscaleAI::UpdateAI(), boss_thorim::boss_thorimAI::UpdateAI(), boss_thorim_ancient_rune_giant::boss_thorim_ancient_rune_giantAI::UpdateAI(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateAI(), boss_ingvar_the_plunderer::boss_ingvar_the_plundererAI::UpdateAI(), boss_ymiron::boss_ymironAI::UpdateAI(), npc_thassarian2::npc_thassarian2AI::UpdateAI(), npc_q24545_lich_king::npc_q24545_lich_kingAI::UpdateAI(), npc_venture_co_straggler::npc_venture_co_stragglerAI::UpdateAI(), npc_battle_at_valhalas::npc_battle_at_valhalasAI::UpdateAI(), npc_llod_generic::npc_llod_genericAI::UpdateAI(), npc_infra_green_bomber_generic::npc_infra_green_bomber_genericAI::UpdateAI(), npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::UpdateAI(), npc_wild_wyrm::npc_wild_wyrmAI::UpdateAI(), npc_freed_protodrake::npc_freed_protodrakeAI::UpdateAI(), npc_feedin_da_goolz::npc_feedin_da_goolzAI::UpdateAI(), npc_crusade_recruit::npc_crusade_recruitAI::UpdateAI(), boss_the_lurker_below::boss_the_lurker_belowAI::UpdateAI(), boss_ahune::boss_ahuneAI::UpdateAI(), boss_kelidan_the_breaker::boss_kelidan_the_breakerAI::UpdateAI(), boss_warchief_kargath_bladefist::boss_warchief_kargath_bladefistAI::UpdateAI(), npc_millhouse_manastorm::npc_millhouse_manastormAI::UpdateAI(), boss_wrath_scryer_soccothrates::boss_wrath_scryer_soccothratesAI::UpdateAI(), boss_alar::boss_alarAI::UpdateAI(), boss_high_astromancer_solarian::boss_high_astromancer_solarianAI::UpdateAI(), boss_kaelthas::boss_kaelthasAI::UpdateAI(), npc_nether_drake::npc_nether_drakeAI::UpdateAI(), brann_bronzebeard::brann_bronzebeardAI::UpdateEscortAI(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::UpdateEscortAI(), npc_akama_illidan::npc_akama_illidanAI::UpdateEscortAI(), Player::UpdateFallInformationIfNeed(), PathGenerator::UpdateFilter(), Creature::UpdateMovementFlags(), Unit::UpdatePosition(), WorldObject::UpdatePositionData(), GameObject::Use(), npc_barnes::npc_barnesAI::WaypointReached(), npc_scarlet_miner::npc_scarlet_minerAI::WaypointReached(), hyjalAI::WaypointReached(), and npc_emily::npc_emilyAI::WaypointReached().
GetRelativeAngle() [1/2]
float Position::GetRelativeAngle (const Position * pos) const inline
Definition at line 411 of file Object.h.
     {
         return GetAngle(pos) - m_orientation;
     }
References GetAngle(), m_orientation, and pos().
Referenced by Spell::EffectCharge(), Spell::EffectChargeDest(), HasInLine(), MotionMaster::MoveKnockbackFrom(), ChaseMovementGenerator< T >::PositionOkay(), and Spell::SelectImplicitTrajTargets().
GetRelativeAngle() [2/2]
float Position::GetRelativeAngle (float x, float y) const inline
Definition at line 415 of file Object.h.
 { return GetAngle(x, y) - m_orientation; }
References GetAngle(), m_orientation, G3D::x, and G3D::y.
GetSinCos()
void Position::GetSinCos (float x, float y, float & vsin, float & vcos) const
Definition at line 1551 of file Object.cpp.
 {
     float dx = GetPositionX() - x;
     float dy = GetPositionY() - y;
     if (fabs(dx) < 0.001f && fabs(dy) < 0.001f)
     {
         float angle = (float)rand_norm() * static_cast<float>(2 * M_PI);
         vcos = cos(angle);
         vsin = sin(angle);
     }
     else
     {
         float dist = sqrt((dx * dx) + (dy * dy));
         vcos = dx / dist;
         vsin = dy / dist;
     }
 }
References GetPositionX(), GetPositionY(), M_PI, rand_norm(), G3D::x, and G3D::y.
Referenced by Unit::KnockbackFrom().
HasInArc()
bool Position::HasInArc (float arcangle, const Position * pos, float targetRadius = 0.0f) const
Definition at line 1599 of file Object.cpp.
 {
     // always have self in arc
     if (obj == this)
         return true;
     // move arc to range 0.. 2*pi
     arc = Position::NormalizeOrientation(arc);
     float angle = GetAngle(obj);
     angle -= m_orientation;
     // move angle to range -pi ... +pi
     angle = Position::NormalizeOrientation(angle);
     if (angle > M_PI)
         angle -= 2.0f * M_PI;
     float lborder = -1 * (arc / 2.0f);                      // in range -pi..0
     float rborder = (arc / 2.0f);                           // in range 0..pi
     // pussywizard: take into consideration target size
     if (targetRadius > 0.0f)
     {
         float distSq = GetExactDist2dSq(obj);
         // pussywizard: at least a part of target's model is in every direction
         if (distSq < targetRadius * targetRadius)
             return true;
         float angularRadius = 2.0f * atan(targetRadius / (2.0f * sqrt(distSq)));
         lborder -= angularRadius;
         rborder += angularRadius;
     }
     return ((angle >= lborder) && (angle <= rborder));
 }
References GetAngle(), GetExactDist2dSq(), m_orientation, M_PI, and NormalizeOrientation().
Referenced by WorldObject::CanDetectStealthOf(), Spell::CheckRange(), boss_janalai::boss_janalaiAI::DamageDealt(), Unit::DealMeleeDamage(), Unit::HandleDummyAuraProc(), HasInLine(), WorldObject::isInBack(), Unit::isInBackInMap(), WorldObject::isInFront(), Unit::isInFrontInMap(), Unit::isSpellBlocked(), Unit::MagicSpellHitResult(), Unit::MeleeSpellHitResult(), Unit::RollMeleeOutcomeAgainst(), Spell::SearchChainTargets(), Player::Update(), boss_nightbane::boss_nightbaneAI::UpdateAI(), boss_romulo::boss_romuloAI::UpdateAI(), boss_kagani_nightstrike::boss_kagani_nightstrikeAI::UpdateAI(), npc_azure_stalker::npc_azure_stalkerAI::UpdateAI(), and PetAI::UpdateAI().
HasInLine()
bool Position::HasInLine (WorldObject const * target, float width) const
Definition at line 1017 of file Object.cpp.
 {
     if (!HasInArc(M_PI, target))
         return false;
     width += target->GetObjectSize();
     float angle = GetRelativeAngle(target);
     return fabs(sin(angle)) * GetExactDist2d(target->GetPositionX(), target->GetPositionY()) < width;
 }
References GetExactDist2d(), WorldObject::GetObjectSize(), GetPositionX(), GetPositionY(), GetRelativeAngle(), HasInArc(), M_PI, and width.
Referenced by spell_brewfest_toss_mug::spell_brewfest_toss_mug_SpellScript::FilterTargets(), spell_winter_veil_racer_rocket_slam::spell_winter_veil_racer_rocket_slam_SpellScript::HandleTriggerSpell(), Acore::WorldObjectSpellConeTargetCheck::operator()(), Acore::WorldObjectSpellTrajTargetCheck::operator()(), and HasInLineCheck::operator()().
IsInDist() [1/2]
bool Position::IsInDist (const Position * pos, float dist) const inline
Definition at line 432 of file Object.h.
     {
         return GetExactDistSq(pos) < dist * dist;
     }
References GetExactDistSq(), and pos().
IsInDist() [2/2]
bool Position::IsInDist (float x, float y, float z, float dist) const inline
Definition at line 428 of file Object.h.
     {
         return GetExactDistSq(x, y, z) < dist * dist;
     }
References GetExactDistSq(), G3D::x, G3D::y, and G3D::z.
Referenced by Creature::CanCreatureAttack(), Spell::CheckCast(), WorldObject::IsWithinDist3d(), and Creature::Update().
IsInDist2d() [1/2]
bool Position::IsInDist2d (const Position * pos, float dist) const inline
Definition at line 424 of file Object.h.
     {
         return GetExactDist2dSq(pos) < dist * dist;
     }
References GetExactDist2dSq(), and pos().
IsInDist2d() [2/2]
bool Position::IsInDist2d (float x, float y, float dist) const inline
Definition at line 420 of file Object.h.
     {
         return GetExactDist2dSq(x, y) < dist * dist;
     }
References GetExactDist2dSq(), G3D::x, and G3D::y.
Referenced by Creature::CanCreatureAttack(), and WorldObject::IsWithinDist2d().
IsPositionValid()
bool Position::IsPositionValid () const
Definition at line 1787 of file Object.cpp.
 {
     return Acore::IsValidMapCoord(m_positionX, m_positionY, m_positionZ, m_orientation);
 }
References Acore::IsValidMapCoord(), m_orientation, m_positionX, m_positionY, and m_positionZ.
Referenced by Creature::Create(), Corpse::Create(), GameObject::Create(), StaticTransport::Create(), Pet::CreateBaseAtCreature(), DynamicObject::CreateDynamicObject(), MotionTransport::CreateGOPassenger(), MotionTransport::CreateMoTrans(), MotionTransport::CreateNPCPassenger(), Unit::ExecuteDelayedUnitRelocationEvent(), WorldSession::HandleMovementOpcodes(), npc_simone::npc_simoneAI::JustDied(), Corpse::LoadCorpseFromDB(), Player::LoadFromDB(), NPCStaveQuestAI::SetHomePosition(), Player::Update(), Player::UpdateCinematicLocation(), Map::VisitNearbyCellsOf(), and Map::VisitNearbyCellsOfPlayer().
IsWithinBox()
bool Position::IsWithinBox (const Position & center, float xradius, float yradius, float zradius) const
Definition at line 1570 of file Object.cpp.
 {
     // rotate the WorldObject position instead of rotating the whole cube, that way we can make a simplified
     // is-in-cube check and we have to calculate only one point instead of 4
     // 2PI = 360*, keep in mind that ingame orientation is counter-clockwise
     double rotation = 2 * M_PI - center.GetOrientation();
     double sinVal = std::sin(rotation);
     double cosVal = std::cos(rotation);
     float BoxDistX = GetPositionX() - center.GetPositionX();
     float BoxDistY = GetPositionY() - center.GetPositionY();
     float rotX = float(center.GetPositionX() + BoxDistX * cosVal - BoxDistY * sinVal);
     float rotY = float(center.GetPositionY() + BoxDistY * cosVal + BoxDistX * sinVal);
     // box edges are parallel to coordiante axis, so we can treat every dimension independently :D
     float dz = GetPositionZ() - center.GetPositionZ();
     float dx = rotX - center.GetPositionX();
     float dy = rotY - center.GetPositionY();
     if ((std::fabs(dx) > xradius) ||
         (std::fabs(dy) > yradius) ||
         (std::fabs(dz) > zradius))
     {
         return false;
     }
     return true;
 }
References align::center, GetPositionX(), GetPositionY(), GetPositionZ(), and M_PI.
Referenced by Player::IsInAreaTriggerRadius().
NormalizeOrientation()
static float Position::NormalizeOrientation (float o) inline static
Definition at line 443 of file Object.h.
     {
         // fmod only supports positive numbers. Thus we have
         // to emulate negative numbers
         if (o < 0)
         {
             float mod = o * -1;
             mod = fmod(mod, 2.0f * static_cast<float>(M_PI));
             mod = -mod + 2.0f * static_cast<float>(M_PI);
             return mod;
         }
         return fmod(o, 2.0f * static_cast<float>(M_PI));
     }
References M_PI, and mod().
Referenced by TransportBase::CalculatePassengerOffset(), TransportBase::CalculatePassengerPosition(), GameObject::Create(), StaticTransport::Create(), npc_tirions_gambit_tirion::npc_tirions_gambit_tirionAI::DoAction(), TransportMgr::GeneratePath(), GetAbsoluteAngle(), spell_mimiron_p3wx2_laser_barrage::spell_mimiron_p3wx2_laser_barrage_AuraScript::HandleEffectPeriodic(), HasInArc(), CreatureGroup::LeaderMoveTo(), ChaseAngle::LowerBound(), spell_lurker_below_spout::spell_lurker_below_spout_AuraScript::OnPeriodic(), spell_quest_dragonmaw_race_generic::RelocateDest(), StaticTransport::RelocateToProgress(), npc_icc_gauntlet_controller::npc_icc_gauntlet_controllerAI::SummonBroodling(), ToAbsoluteAngle(), MotionTransport::Update(), npc_pos_tyrannus_events::npc_pos_tyrannus_eventsAI::UpdateAI(), and ChaseAngle::UpperBound().
operator G3D::Vector3()
Position::operator G3D::Vector3 () const inline
Definition at line 290 of file Object.h.
     {
         return { m_positionX, m_positionY, m_positionZ };
     }
References m_positionX, m_positionY, and m_positionZ.
operator!=()
bool Position::operator!= (Position const & a) inline
Definition at line 285 of file Object.h.
     {
         return !(operator==(a));
     }
References mpq::a, and operator==().
operator==()
bool Position::operator== (Position const & a) const
Definition at line 1000 of file Object.cpp.
 {
     return (G3D::fuzzyEq(a.m_positionX, m_positionX) &&
         G3D::fuzzyEq(a.m_positionY, m_positionY) &&
         G3D::fuzzyEq(a.m_positionZ, m_positionZ) &&
         G3D::fuzzyEq(a.m_orientation, m_orientation));
 }
References mpq::a, G3D::fuzzyEq(), m_orientation, m_positionX, m_positionY, and m_positionZ.
Referenced by operator!=().
PositionXYZOStream()
Position::PositionXYZOStreamer Position::PositionXYZOStream () inline
Definition at line 364 of file Object.h.
     {
         return PositionXYZOStreamer(*this);
     }
Referenced by WorldSession::ReadMovementInfo(), Player::TeleportTo(), and WorldSession::WriteMovementInfo().
PositionXYZStream()
Position::PositionXYZStreamer Position::PositionXYZStream () inline
Definition at line 360 of file Object.h.
     {
         return PositionXYZStreamer(*this);
     }
Referenced by SpellCastTargets::Read(), and SpellCastTargets::Write().
Relocate() [1/5]
void Position::Relocate (const Position & pos) inline
Definition at line 313 of file Object.h.
     {
         m_positionX = pos.m_positionX;
         m_positionY = pos.m_positionY;
         m_positionZ = pos.m_positionZ;
         m_orientation = pos.m_orientation;
     }
References m_orientation, m_positionX, m_positionY, m_positionZ, and pos().
Relocate() [2/5]
void Position::Relocate (const Position * pos) inline
Definition at line 320 of file Object.h.
     {
         m_positionX = pos->m_positionX;
         m_positionY = pos->m_positionY;
         m_positionZ = pos->m_positionZ;
         m_orientation = pos->m_orientation;
     }
References m_orientation, m_positionX, m_positionY, m_positionZ, and pos().
Relocate() [3/5]
void Position::Relocate (float x, float y) inline
Definition at line 295 of file Object.h.
     {
         m_positionX = x;
         m_positionY = y;
     }
References m_positionX, m_positionY, G3D::x, and G3D::y.
Referenced by Vehicle::AddPassenger(), MotionTransport::AddPassenger(), StaticTransport::AddPassenger(), Map::ConvertCorpseToBones(), Player::Create(), Creature::Create(), Corpse::Create(), GameObject::Create(), StaticTransport::Create(), Pet::CreateBaseAtCreature(), Pet::CreateBaseAtCreatureInfo(), DynamicObject::CreateDynamicObject(), MotionTransport::CreateGOPassenger(), MotionTransport::CreateMoTrans(), MotionTransport::CreateNPCPassenger(), Map::CreatureRelocation(), boss_ick::boss_ickAI::DamageTaken(), MotionTransport::DelayedTeleportTransport(), instance_trial_of_the_champion::instance_trial_of_the_champion_InstanceMapScript::DoSummonGrandChampion(), Map::DynamicObjectRelocation(), GameObject::GameObject(), Map::GameObjectRelocation(), WorldLocation::GetWorldLocation(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::GoSiphon(), Pet::HandleAsynchLoadFailed(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveWorldportAck(), npc_commandscript::HandleNpcTameCommand(), AuraEffect::HandlePhase(), WorldSession::HandleSetRaidDifficultyOpcode(), Corpse::LoadCorpseFromDB(), Creature::LoadCreatureFromDB(), Player::LoadFromDB(), MMapTargetData::MMapTargetData(), MovementInfo::MovementInfo(), npc_valkyr_shadowguard::npc_valkyr_shadowguardAI::MovementInform(), spell_alar_ember_blast_death::spell_alar_ember_blast_death_AuraScript::OnApply(), operator>>(), Map::PlayerRelocation(), Position(), spell_midsummer_ribbon_pole::spell_midsummer_ribbon_pole_AuraScript::PrepareAuraScript(), RandomMovementGenerator< T >::RandomMovementGenerator(), SpellCastTargets::Read(), SpellDestination::Relocate(), spell_igb_teleport_to_enemy_ship::spell_igb_teleport_to_enemy_ship_SpellScript::RelocateTransportOffset(), Creature::RemoveCorpse(), MotionTransport::RemovePassenger(), StaticTransport::RemovePassenger(), MovementInfo::TransportInfo::Reset(), Creature::Respawn(), Spell::SelectImplicitTrajTargets(), npc_midsummer_torch_target::npc_midsummer_torch_targetAI::SelectPosition(), Unit::SendTeleportPacket(), spell_blood_council_summon_shadow_resonance::spell_blood_council_summon_shadow_resonance_SpellScript::SetDest(), Creature::SetHomePosition(), instance_icecrown_citadel::instance_icecrown_citadel_InstanceMapScript::SetPositionTraps(), Creature::SetTransportHomePosition(), BattlefieldWG::SetupBattlefield(), npc_taldaram_flamesphere::npc_taldaram_flamesphereAI::SetVictimPos(), SpellDestination::SpellDestination(), Player::TeleportTo(), boss_twinemperorsAI::TeleportToMyBrother(), Unit::Unit(), SpellCastTargets::Update(), npc_love_in_air_hummel_helper::npc_love_in_air_hummel_helperAI::UpdateAI(), npc_vortex_ride::npc_vortex_rideAI::UpdateAI(), Unit::UpdateHeight(), Spell::UpdatePointers(), MotionTransport::UpdatePosition(), Player::UpdateVisibilityForPlayer(), and WorldLocation::WorldRelocate().
Relocate() [4/5]
void Position::Relocate (float x, float y, float z) inline
Definition at line 300 of file Object.h.
     {
         m_positionX = x;
         m_positionY = y;
         m_positionZ = z;
     }
References m_positionX, m_positionY, m_positionZ, G3D::x, G3D::y, and G3D::z.
Relocate() [5/5]
void Position::Relocate (float x, float y, float z, float orientation) inline
Definition at line 306 of file Object.h.
     {
         m_positionX = x;
         m_positionY = y;
         m_positionZ = z;
         m_orientation = orientation;
     }
References m_orientation, m_positionX, m_positionY, m_positionZ, G3D::x, G3D::y, and G3D::z.
RelocateOffset()
void Position::RelocateOffset (const Position & offset)
Definition at line 1518 of file Object.cpp.
 {
     m_positionX = GetPositionX() + (offset.GetPositionX() * cos(GetOrientation()) + offset.GetPositionY() * sin(GetOrientation() + M_PI));
     m_positionY = GetPositionY() + (offset.GetPositionY() * cos(GetOrientation()) + offset.GetPositionX() * sin(GetOrientation()));
     m_positionZ = GetPositionZ() + offset.GetPositionZ();
     m_orientation = GetOrientation() + offset.GetOrientation();
 }
References GetOrientation(), GetPositionX(), GetPositionY(), GetPositionZ(), m_orientation, M_PI, m_positionX, m_positionY, and m_positionZ.
Referenced by spell_valanar_kinetic_bomb::spell_valanar_kinetic_bomb_SpellScript::ChangeSummonPos(), spell_onslaught_or_call_bone_gryphon::spell_onslaught_or_call_bone_gryphon_SpellScript::ChangeSummonPos(), spell_the_lich_king_teleport_to_frostmourne_hc::spell_the_lich_king_teleport_to_frostmourne_hc_SpellScript::ModDest(), spell_the_lich_king_summon_into_air::spell_the_lich_king_summon_into_air_SpellScript::ModDestHeight(), spell_halion_summon_exit_portals::spell_halion_summon_exit_portals_SpellScript::OnSummon(), SpellDestination::Relocate(), spell_igb_gunship_fall_teleport::spell_igb_gunship_fall_teleport_SpellScript::RelocateDest(), SpellDestination::RelocateOffset(), spell_valanar_kinetic_bomb_summon::spell_valanar_kinetic_bomb_summon_SpellScript::SelectDest(), SpellCastTargets::Update(), and Spell::UpdatePointers().
RelocatePolarOffset()
void Position::RelocatePolarOffset (float angle, float dist, float z = 0.0f)
Definition at line 1008 of file Object.cpp.
 {
     SetOrientation(GetOrientation() + angle);
     m_positionX = GetPositionX() + dist * std::cos(GetOrientation());
     m_positionY = GetPositionY() + dist * std::sin(GetOrientation());
     m_positionZ = GetPositionZ() + z;
 }
References GetOrientation(), GetPositionX(), GetPositionY(), GetPositionZ(), m_positionX, m_positionY, m_positionZ, SetOrientation(), and G3D::z.
SetOrientation()
void Position::SetOrientation (float orientation) inline
Definition at line 329 of file Object.h.
     {
         m_orientation = orientation;
     }
References m_orientation.
Referenced by boss_the_lich_king::boss_the_lich_kingAI::DamageTaken(), WorldSession::HandleMovementOpcodes(), spell_dk_dancing_rune_weapon::HandleProc(), boss_halion::boss_halionAI::JustSummoned(), npc_mageguard_dalaran::npc_mageguard_dalaranAI::MoveInLineOfSight(), boss_nalorakk::boss_nalorakkAI::MovementInform(), npc_icc_nerubar_broodkeeper::npc_icc_nerubar_broodkeeperAI::MovementInform(), boss_volkhan::boss_volkhanAI::MovementInform(), boss_razorscale::boss_razorscaleAI::MovementInform(), kaylaan_the_lost::kaylaan_the_lostAI::MovementInform(), npc_hor_lich_king::npc_hor_lich_kingAI::MovementInform(), npc_frostbite_invisible_stalker::npc_frostbite_invisible_stalkerAI::npc_frostbite_invisible_stalkerAI(), npc_oculus_drake::npc_oculus_drakeAI::PassengerBoarded(), SmartScript::ProcessAction(), RelocatePolarOffset(), PassengerController::SelectSpawnPoint(), Player::SetClientControl(), npc_alexstraza_the_lifebinder::npc_alexstraza_the_lifebinderAI::SetData(), Unit::SetInFront(), boss_thorim::boss_thorimAI::SpellHit(), boss_devourer_of_souls::boss_devourer_of_soulsAI::SpellHitTarget(), npc_alexstraza_the_lifebinder::npc_alexstraza_the_lifebinderAI::UpdateAI(), boss_onyxia::boss_onyxiaAI::UpdateAI(), boss_eye_of_cthun::eye_of_cthunAI::UpdateAI(), npc_pos_martin_or_gorkun_second::npc_pos_martin_or_gorkun_secondAI::UpdateAI(), npc_high_overlord_saurfang_igb::npc_high_overlord_saurfang_igbAI::UpdateAI(), npc_muradin_bronzebeard_igb::npc_muradin_bronzebeard_igbAI::UpdateAI(), boss_rotface::boss_rotfaceAI::UpdateAI(), boss_varos::boss_varosAI::UpdateAI(), npc_oculus_drake::npc_oculus_drakeAI::UpdateAI(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::UpdateAI(), boss_yoggsaron_sara::boss_yoggsaron_saraAI::UpdateAI(), boss_alar::boss_alarAI::UpdateAI(), Unit::UpdateOrientation(), and npc_black_knight_skeletal_gryphon::npc_black_knight_skeletal_gryphonAI::WaypointReached().
ToAbsoluteAngle()
float Position::ToAbsoluteAngle (float relAngle) const inline
Definition at line 416 of file Object.h.
 { return NormalizeOrientation(relAngle + m_orientation); }
References m_orientation, and NormalizeOrientation().
Referenced by ChaseMovementGenerator< T >::DoUpdate(), and FollowMovementGenerator< T >::DoUpdate().
ToString()
std::string Position::ToString () const
Definition at line 1026 of file Object.cpp.
 {
     std::stringstream sstr;
     sstr << "X: " << m_positionX << " Y: " << m_positionY << " Z: " << m_positionZ << " O: " << m_orientation;
     return sstr.str();
 }
References m_orientation, m_positionX, m_positionY, and m_positionZ.
Referenced by Player::_addSpell(), Pet::_LoadAuras(), Player::_LoadAuras(), Player::_LoadDailyQuestStatus(), Player::_LoadInventory(), Player::_LoadItem(), Player::_LoadMonthlyQuestStatus(), Player::_LoadQuestStatus(), Player::_LoadSeasonalQuestStatus(), Player::_LoadSkills(), Player::_LoadSpellCooldowns(), Player::_LoadWeeklyQuestStatus(), Player::_SaveInventory(), Player::addActionButton(), WorldObject::AddObjectToRemoveList(), Unit::AttackerStateUpdate(), Player::BuildPlayerRepop(), Player::CanBankItem(), Unit::CastCustomSpell(), Player::CastItemCombatSpell(), Unit::CastSpell(), Player::CheckAreaExploreAndOutdoor(), Player::ContinueTaxiFlight(), Pet::CreateBaseAtCreature(), Unit::DelayOwnedAuras(), Creature::DeleteFromDB(), Player::GetGameObjectIfCanInteractWith(), Player::InitDisplayIds(), Player::LearnCustomSpells(), Player::learnSpell(), Corpse::LoadCorpseFromDB(), Creature::LoadCreaturesAddon(), Player::LoadFromDB(), Player::OnGossipSelect(), MovementInfo::OutDebug(), SpellCastTargets::OutDebug(), Unit::OutDebugInfo(), Player::removeActionButton(), Unit::RemoveCharmedBy(), GameObject::RemoveFromOwner(), Creature::Respawn(), Player::SendActionButtons(), Player::SendItemRetrievalMail(), Unit::SendMeleeAttackStop(), Unit::SetCharm(), Unit::SetCharmedBy(), Player::setDeathState(), Player::SetMover(), Player::StopCastingCharm(), Player::TeleportTo(), Creature::Update(), Player::Update(), Player::UpdateHomebindTime(), GameObject::Use(), and WorldObject::~WorldObject().
Member Data Documentation
m_orientation
float Position::m_orientation = 0
Definition at line 281 of file Object.h.
Referenced by npc_ranshalla::npc_ranshallaAI::DoSummonPriestess(), GetOrientation(), GetPosition(), GetPositionOffsetTo(), GetRelativeAngle(), WorldLocation::GetWorldLocation(), spell_marrowgar_coldflame_bonestorm::spell_marrowgar_coldflame_SpellScript::HandleScriptEffect(), spell_marrowgar_coldflame::spell_marrowgar_coldflame_SpellScript::HandleScriptEffect(), HasInArc(), IsPositionValid(), npc_ranshalla::npc_ranshallaAI::JustDidDialogueStep(), WorldObject::MovePosition(), operator==(), Relocate(), RelocateOffset(), PassengerController::SelectSpawnPoint(), SetOrientation(), ToAbsoluteAngle(), ToString(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), boss_jindo::boss_jindoAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), and npc_ulduar_emergency_fire_bot::npc_ulduar_emergency_fire_botAI::UpdateAI().
m_positionX
float Position::m_positionX = 0
Definition at line 278 of file Object.h.
Referenced by WorldObject::_IsWithinDist(), npc_ranshalla::npc_ranshallaAI::DoSummonPriestess(), GetAbsoluteAngle(), GetExactDist2dSq(), GetPosition(), GetPositionOffsetTo(), GetPositionX(), WorldLocation::GetWorldLocation(), IsPositionValid(), npc_ranshalla::npc_ranshallaAI::JustDidDialogueStep(), spell_halion_summon_exit_portals::spell_halion_summon_exit_portals_SpellScript::OnSummon(), operator G3D::Vector3(), operator==(), SmartScript::ProcessAction(), Relocate(), RelocateOffset(), RelocatePolarOffset(), Spell::SelectImplicitTrajTargets(), PassengerController::SelectSpawnPoint(), ToString(), instance_stratholme::instance_stratholme_InstanceMapScript::Update(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), boss_jindo::boss_jindoAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_ulduar_vx001::npc_ulduar_vx001AI::UpdateAI(), npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::UpdateAI(), boss_ichoron::boss_ichoronAI::UpdateAI(), and Player::UpdateCinematicLocation().
m_positionY
float Position::m_positionY = 0
Definition at line 279 of file Object.h.
Referenced by WorldObject::_IsWithinDist(), npc_ranshalla::npc_ranshallaAI::DoSummonPriestess(), GetAbsoluteAngle(), GetExactDist2dSq(), GetPosition(), GetPositionOffsetTo(), GetPositionY(), WorldLocation::GetWorldLocation(), IsPositionValid(), npc_ranshalla::npc_ranshallaAI::JustDidDialogueStep(), spell_halion_summon_exit_portals::spell_halion_summon_exit_portals_SpellScript::OnSummon(), operator G3D::Vector3(), operator==(), SmartScript::ProcessAction(), Relocate(), RelocateOffset(), RelocatePolarOffset(), Spell::SelectImplicitTrajTargets(), PassengerController::SelectSpawnPoint(), ToString(), instance_stratholme::instance_stratholme_InstanceMapScript::Update(), npc_bh_thalorien_dawnseeker::npc_bh_thalorien_dawnseekerAI::UpdateAI(), boss_jindo::boss_jindoAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_ulduar_vx001::npc_ulduar_vx001AI::UpdateAI(), npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::UpdateAI(), boss_ichoron::boss_ichoronAI::UpdateAI(), and Player::UpdateCinematicLocation().
m_positionZ
float Position::m_positionZ = 0
Definition at line 280 of file Object.h.
Referenced by WorldObject::_IsWithinDist(), Creature::Create(), boss_ick::boss_ickAI::DamageTaken(), npc_ice_tomb::npc_ice_tombAI::DamageTaken(), boss_the_lich_king::boss_the_lich_kingAI::DamageTaken(), npc_bone_spike::npc_bone_spikeAI::DoAction(), npc_ranshalla::npc_ranshallaAI::DoSummonPriestess(), Spell::EffectSummonType(), GetExactDistSq(), GetPosition(), GetPositionOffsetTo(), GetPositionZ(), WorldLocation::GetWorldLocation(), spell_dk_death_grip::HandleDummy(), IsPositionValid(), npc_coldflame::npc_coldflameAI::IsSummonedBy(), npc_ranshalla::npc_ranshallaAI::JustDidDialogueStep(), npc_ulduar_aerial_command_unit::npc_ulduar_aerial_command_unitAI::JustSummoned(), boss_the_lich_king::boss_the_lich_kingAI::JustSummoned(), operator G3D::Vector3(), operator==(), SmartScript::ProcessAction(), Relocate(), spell_igb_gunship_fall_teleport::spell_igb_gunship_fall_teleport_SpellScript::RelocateDest(), RelocateOffset(), RelocatePolarOffset(), Spell::SelectImplicitTrajTargets(), PassengerController::SelectSpawnPoint(), spell_prince_taldaram_flame_sphere_summon::spell_prince_taldaram_flame_sphere_summon_SpellScript::SetDest(), spell_azjol_nerub_impale_summon::spell_azjol_nerub_impale_summon_SpellScript::SetDest(), spell_dk_summon_gargoyle::SetDest(), BattlegroundRV::TeleportUnitToNewZ(), ToString(), boss_jindo::boss_jindoAI::UpdateAI(), npc_coldflame::npc_coldflameAI::UpdateAI(), boss_malygos::boss_malygosAI::UpdateAI(), npc_ulduar_vx001::npc_ulduar_vx001AI::UpdateAI(), npc_frostbrood_skytalon::npc_frostbrood_skytalonAI::UpdateAI(), and Player::UpdateCinematicLocation().
The documentation for this struct was generated from the following files:
src/server/game/Entities/Object/Object.h
src/server/game/Entities/Object/Object.cpp