Azerotcore-wotlk: MailReceiver Class Reference
MailReceiver Class Reference
#include <Mail.h>
Public Member Functions
MailReceiver (ObjectGuid::LowType receiver_lowguid)
MailReceiver (Player *receiver)
MailReceiver (Player *receiver, ObjectGuid::LowType receiver_lowguid)
Player * GetPlayer () const
ObjectGuid::LowType GetPlayerGUIDLow () const
Private Attributes
Player * m_receiver
ObjectGuid::LowType m_receiver_lowguid
Detailed Description
Definition at line 103 of file Mail.h.
Constructor & Destructor Documentation
MailReceiver() [1/3]
MailReceiver::MailReceiver (ObjectGuid::LowType receiver_lowguid) inline explicit
Definition at line 106 of file Mail.h.
 : m_receiver(nullptr), m_receiver_lowguid(receiver_lowguid) {}
MailReceiver() [2/3]
MailReceiver::MailReceiver (Player * receiver)
Definition at line 83 of file Mail.cpp.
                                            : m_receiver(receiver), m_receiver_lowguid(receiver->GetGUID().GetCounter())
 {
 }
MailReceiver() [3/3]
MailReceiver::MailReceiver (Player * receiver, ObjectGuid::LowType receiver_lowguid)
Definition at line 87 of file Mail.cpp.
                                                                                : m_receiver(receiver), m_receiver_lowguid(receiver_lowguid)
 {
     ASSERT(!receiver || receiver->GetGUID().GetCounter() == receiver_lowguid);
 }
References ASSERT, ObjectGuid::GetCounter(), and Object::GetGUID().
Member Function Documentation
GetPlayer()
Player* MailReceiver::GetPlayer () const inline
Definition at line 110 of file Mail.h.
 { return m_receiver; }
References m_receiver.
Referenced by MailDraft::SendMailTo().
GetPlayerGUIDLow()
ObjectGuid::LowType MailReceiver::GetPlayerGUIDLow () const inline
Definition at line 111 of file Mail.h.
 { return m_receiver_lowguid; }
References m_receiver_lowguid.
Referenced by MailDraft::SendMailTo().
Member Data Documentation
m_receiver
Player* MailReceiver::m_receiver private
Definition at line 113 of file Mail.h.
Referenced by GetPlayer().
m_receiver_lowguid
ObjectGuid::LowType MailReceiver::m_receiver_lowguid private
Definition at line 114 of file Mail.h.
Referenced by GetPlayerGUIDLow().
The documentation for this class was generated from the following files:
src/server/game/Mails/Mail.h
src/server/game/Mails/Mail.cpp