Azerotcore-wotlk: boss_sartharion::boss_sartharionAI Struct Reference
boss_sartharion::boss_sartharionAI Struct Reference
Public Member Functions
boss_sartharionAI (Creature *pCreature)
void Reset () override
void DoAction (int32 param) override
void EnterCombat (Unit *pWho) override
void JustDied (Unit *) override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 dataOrGuid) const override
void KilledUnit (Unit *pVictim) override
void JustSummoned (Creature *summon) override
void DamageTaken (Unit *, uint32 &damage, DamageEffectType, SpellSchoolMask) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from BossAI
BossAI (Creature *creature, uint32 bossId)
~BossAI () override
BossBoundaryMap const * GetBoundary () const
void SummonedCreatureDespawn (Creature *summon) override
void SummonedCreatureDespawnAll () override
virtual void ExecuteEvent (uint32)
void JustReachedHome () override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Private Member Functions
void SummonStartingTriggers ()
void SummonLavaWaves ()
void SendLavaWaves (bool start)
void RespawnDragons (bool checkCombat)
bool IsTargetInBounds (Unit const *victim) const
Private Attributes
EventMap extraEvents
std::list< uint32 > volcanoBlows
uint8 dragonsCount
uint8 lastLavaSide
bool usedBerserk
bool below11PctReached
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Public Attributes inherited from BossAI
InstanceScript *const instance
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from BossAI
void _Reset ()
void _EnterCombat ()
void _JustDied ()
void _JustReachedHome ()
bool CheckInRoom ()
bool CheckBoundary (Unit *who)
void TeleportCheaters ()
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from BossAI
EventMap events
SummonList summons
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 250 of file boss_sartharion.cpp.
Constructor & Destructor Documentation
boss_sartharionAI()
boss_sartharion::boss_sartharionAI::boss_sartharionAI (Creature * pCreature) inline
Definition at line 252 of file boss_sartharion.cpp.
                                                : BossAI(pCreature, DATA_SARTHARION),
             dragonsCount(0),
             lastLavaSide(LAVA_RIGHT_SIDE),
             usedBerserk(false),
             below11PctReached(false)
         {
         }
Member Function Documentation
DamageTaken()
void boss_sartharion::boss_sartharionAI::DamageTaken (Unit * , uint32 & damage, DamageEffectType , SpellSchoolMask) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 414 of file boss_sartharion.cpp.
         {
             // Temporal hack, by some case some melee spells can bypass this aura damage reduction
             if (me->HasAura(SPELL_GIFT_OF_TWILIGHT_FIRE))
             {
                 damage = 0;
                 return;
             }
             if (!usedBerserk && me->HealthBelowPctDamaged(30, damage))
             {
                 DoCastSelf(SPELL_SARTHARION_BERSERK, true);
                 usedBerserk = true;
                 return;
             }
             // Soft enrage
             if (!below11PctReached && me->HealthBelowPctDamaged(10, damage))
             {
                 summons.RemoveNotExisting();
                 if (!summons.empty())
                 {
                     for (ObjectGuid const& summonGuid : summons)
                     {
                         Creature* summon = ObjectAccessor::GetCreature(*me, summonGuid);
                         if (summon && summon->GetEntry() == NPC_FIRE_CYCLONE)
{
                             summon->CastSpell(summon, SPELL_CYCLONE_AURA_PERIODIC, true);
                         }
                     }
                 }
                 Talk(SAY_SARTHARION_BERSERK);
                 below11PctReached = true;
             }
         }
References below11PctReached, Unit::CastSpell(), UnitAI::DoCastSelf(), SummonList::empty(), ObjectAccessor::GetCreature(), Object::GetEntry(), Unit::HasAura(), Unit::HealthBelowPctDamaged(), ScriptedAI::me, NPC_FIRE_CYCLONE, SummonList::RemoveNotExisting(), SAY_SARTHARION_BERSERK, SPELL_CYCLONE_AURA_PERIODIC, SPELL_GIFT_OF_TWILIGHT_FIRE, SPELL_SARTHARION_BERSERK, BossAI::summons, CreatureAI::Talk(), and usedBerserk.
DoAction()
void boss_sartharion::boss_sartharionAI::DoAction (int32 param) inline override virtual
Reimplemented from UnitAI.
Definition at line 273 of file boss_sartharion.cpp.
         {
             if (param == ACTION_DRAKE_DIED)
             {
                 DoCastSelf(SPELL_SARTHARION_TWILIGHT_REVENGE, true);
             }
         }
References ACTION_DRAKE_DIED, UnitAI::DoCastSelf(), and SPELL_SARTHARION_TWILIGHT_REVENGE.
EnterCombat()
void boss_sartharion::boss_sartharionAI::EnterCombat (Unit * pWho) inline override virtual
Reimplemented from BossAI.
Definition at line 281 of file boss_sartharion.cpp.
         {
             if (pWho && !IsTargetInBounds(pWho))
             {
                 EnterEvadeMode();
                 return;
             }
             _EnterCombat();
             DoCastSelf(SPELL_SARTHARION_PYROBUFFET, true);
             Talk(SAY_SARTHARION_AGGRO);
             // Combat events
             events.ScheduleEvent(EVENT_SARTHARION_CAST_CLEAVE, 7000);
             events.ScheduleEvent(EVENT_SARTHARION_CAST_FLAME_BREATH, 15000);
             events.ScheduleEvent(EVENT_SARTHARION_CAST_TAIL_LASH, 11000);
             // Extra events
             extraEvents.ScheduleEvent(EVENT_SARTHARION_SUMMON_LAVA, 20000);
             extraEvents.ScheduleEvent(EVENT_SARTHARION_LAVA_STRIKE, 5000);
             extraEvents.ScheduleEvent(EVENT_SARTHARION_BERSERK, 900000);
             extraEvents.ScheduleEvent(EVENT_SARTHARION_BOUNDARY, 250);
             // Store dragons
             for (uint8 i = 0; i < MAX_DRAGONS; ++i)
             {
                 Creature* dragon = ObjectAccessor::GetCreature(*me, instance->GetGuidData(dragons[i]));
                 if (!dragon || !dragon->IsAlive() || instance->GetBossState(dragons[i]) == DONE)
                 {
                     continue;
                 }
                 dragon->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC);
                 dragon->SetFullHealth();
                 ++dragonsCount;
                 me->AddLootMode(1 << dragonsCount);
                 switch (dragons[i])
                 {
                     case DATA_TENEBRON:
                     {
                         dragon->CastSpell(dragon, SPELL_POWER_OF_TENEBRON, true);
                         extraEvents.ScheduleEvent(EVENT_SARTHARION_CALL_TENEBRON, 10000);
                         break;
                     }
                     case DATA_SHADRON:
                     {
                         dragon->CastSpell(dragon, SPELL_POWER_OF_SHADRON, true);
                         extraEvents.ScheduleEvent(EVENT_SARTHARION_CALL_SHADRON, 65000);
                         break;
                     }
                     case DATA_VESPERON:
                     {
                         dragon->CastSpell(dragon, SPELL_POWER_OF_VESPERON, true);
                         extraEvents.ScheduleEvent(EVENT_SARTHARION_CALL_VESPERON, 115000);
                         break;
                     }
                 }
             }
             if (dragonsCount)
             {
                 DoCastSelf(SPELL_WILL_OF_SARTHARION, true);
             }
             me->CallForHelp(500.0f);
         }
References BossAI::_EnterCombat(), Creature::AddLootMode(), Creature::CallForHelp(), Unit::CastSpell(), DATA_SHADRON, DATA_TENEBRON, DATA_VESPERON, UnitAI::DoCastSelf(), DONE, dragons, dragonsCount, CreatureAI::EnterEvadeMode(), EVENT_SARTHARION_BERSERK, EVENT_SARTHARION_BOUNDARY, EVENT_SARTHARION_CALL_SHADRON, EVENT_SARTHARION_CALL_TENEBRON, EVENT_SARTHARION_CALL_VESPERON, EVENT_SARTHARION_CAST_CLEAVE, EVENT_SARTHARION_CAST_FLAME_BREATH, EVENT_SARTHARION_CAST_TAIL_LASH, EVENT_SARTHARION_LAVA_STRIKE, EVENT_SARTHARION_SUMMON_LAVA, extraEvents, InstanceScript::GetBossState(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), BossAI::instance, Unit::IsAlive(), IsTargetInBounds(), MAX_DRAGONS, ScriptedAI::me, SAY_SARTHARION_AGGRO, EventMap::ScheduleEvent(), Object::SetFlag(), Unit::SetFullHealth(), SPELL_POWER_OF_SHADRON, SPELL_POWER_OF_TENEBRON, SPELL_POWER_OF_VESPERON, SPELL_SARTHARION_PYROBUFFET, SPELL_WILL_OF_SARTHARION, CreatureAI::Talk(), UNIT_FIELD_FLAGS, and UNIT_FLAG_IMMUNE_TO_NPC.
GetData()
uint32 boss_sartharion::boss_sartharionAI::GetData (uint32 dataOrGuid) const inline override virtual
Reimplemented from UnitAI.
Definition at line 370 of file boss_sartharion.cpp.
         {
             // it means we want dragons count
             if (dataOrGuid == DATA_ACHIEVEMENT_DRAGONS_COUNT)
             {
                 return dragonsCount;
             }
             // otherwise it is guid to check if player was hit by lava strike :)
             if (!volcanoBlows.empty() && std::find(volcanoBlows.begin(), volcanoBlows.end(), dataOrGuid) != volcanoBlows.end())
             {
                 return 1;
             }
             return 0;
         }
References DATA_ACHIEVEMENT_DRAGONS_COUNT, dragonsCount, and volcanoBlows.
IsTargetInBounds()
bool boss_sartharion::boss_sartharionAI::IsTargetInBounds (Unit const * victim) const inline private
Definition at line 695 of file boss_sartharion.cpp.
         {
             if (!victim || victim->GetPositionX() < SartharionBoundary[0] || victim->GetPositionX() > SartharionBoundary[1] || victim->GetPositionY() > SartharionBoundary[3])
             {
                 return false;
             }
             // Big island handling
             if (victim->GetPositionY() < SartharionBoundary[2])
             {
                 return victim->GetDistance(bigIslandMiddlePos) <= 6.0f;
             }
             return true;
         }
References bigIslandMiddlePos, WorldObject::GetDistance(), Position::GetPositionX(), Position::GetPositionY(), and SartharionBoundary.
Referenced by EnterCombat(), and UpdateAI().
JustDied()
void boss_sartharion::boss_sartharionAI::JustDied (Unit *) inline override virtual
Reimplemented from BossAI.
Definition at line 350 of file boss_sartharion.cpp.
         {
             RespawnDragons(true);
             _JustDied();
             Talk(SAY_SARTHARION_DEATH);
         }
References BossAI::_JustDied(), RespawnDragons(), SAY_SARTHARION_DEATH, and CreatureAI::Talk().
JustSummoned()
void boss_sartharion::boss_sartharionAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from BossAI.
Definition at line 395 of file boss_sartharion.cpp.
         {
             switch (summon->GetEntry())
             {
                 case NPC_FLAME_TSUNAMI:
                 {
                     summon->SetSpeed(MOVE_FLIGHT, 1.5f);
                     break;
                 }
                 case NPC_FIRE_CYCLONE:
                 {
                     summon->GetMotionMaster()->MoveRandom(5.0f);
                     break;
                 }
             }
             summons.Summon(summon);
         }
References Object::GetEntry(), Unit::GetMotionMaster(), MOVE_FLIGHT, MotionMaster::MoveRandom(), NPC_FIRE_CYCLONE, NPC_FLAME_TSUNAMI, Unit::SetSpeed(), SummonList::Summon(), and BossAI::summons.
KilledUnit()
void boss_sartharion::boss_sartharionAI::KilledUnit (Unit * pVictim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 387 of file boss_sartharion.cpp.
         {
             if (!urand(0, 2) && pVictim->GetTypeId() == TYPEID_PLAYER)
             {
                 Talk(SAY_SARTHARION_SLAY);
             }
         }
References Object::GetTypeId(), SAY_SARTHARION_SLAY, CreatureAI::Talk(), TYPEID_PLAYER, and urand().
Reset()
void boss_sartharion::boss_sartharionAI::Reset () inline override virtual
Reimplemented from BossAI.
Definition at line 260 of file boss_sartharion.cpp.
         {
             _Reset();
             extraEvents.Reset();
             RespawnDragons(false);
             SummonStartingTriggers();
             usedBerserk = false;
             below11PctReached = false;
             dragonsCount = 0;
             volcanoBlows.clear();
             instance->DoRemoveAurasDueToSpellOnPlayers(SPELL_TWILIGHT_SHIFT);
         }
References BossAI::_Reset(), below11PctReached, InstanceScript::DoRemoveAurasDueToSpellOnPlayers(), dragonsCount, extraEvents, BossAI::instance, EventMap::Reset(), RespawnDragons(), SPELL_TWILIGHT_SHIFT, SummonStartingTriggers(), usedBerserk, and volcanoBlows.
RespawnDragons()
void boss_sartharion::boss_sartharionAI::RespawnDragons (bool checkCombat) inline private
Definition at line 671 of file boss_sartharion.cpp.
         {
             for (uint8 i = 0; i < MAX_DRAGONS; ++i)
             {
                 if (instance->GetBossState(dragons[i]) == DONE)
                 {
                     continue;
                 }
                 if (Creature* dragon = ObjectAccessor::GetCreature(*me, instance->GetGuidData(dragons[i])))
                 {
                     if (checkCombat && dragon->IsInCombat())
                     {
                         continue;
                     }
                     dragon->DespawnOrUnsummon();
                     dragon->SetRespawnTime(5);
                 }
             }
             dragonsCount = 0;
         }
References DONE, dragons, dragonsCount, InstanceScript::GetBossState(), ObjectAccessor::GetCreature(), InstanceScript::GetGuidData(), BossAI::instance, MAX_DRAGONS, and ScriptedAI::me.
Referenced by JustDied(), and Reset().
SendLavaWaves()
void boss_sartharion::boss_sartharionAI::SendLavaWaves (bool start) inline private
Definition at line 645 of file boss_sartharion.cpp.
         {
             if (summons.empty())
             {
                 return;
             }
             for (ObjectGuid const& guid : summons)
             {
                 Creature* tsunami = ObjectAccessor::GetCreature(*me, guid);
                 if (!tsunami || tsunami->GetEntry() != NPC_FLAME_TSUNAMI)
                 {
                     continue;
                 }
                 if (start)
                 {
                     tsunami->GetMotionMaster()->MovePoint(0, ((tsunami->GetPositionX() < 3250.0f) ? 3283.44f : 3208.44f), tsunami->GetPositionY(), tsunami->GetPositionZ());
                 }
                 else
                 {
                     tsunami->SetObjectScale(0.1f);
                 }
             }
         }
References SummonList::empty(), ObjectAccessor::GetCreature(), Object::GetEntry(), Unit::GetMotionMaster(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ScriptedAI::me, MotionMaster::MovePoint(), NPC_FLAME_TSUNAMI, Creature::SetObjectScale(), and BossAI::summons.
Referenced by UpdateAI().
SetData()
void boss_sartharion::boss_sartharionAI::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from UnitAI.
Definition at line 357 of file boss_sartharion.cpp.
         {
             if (type == DATA_VOLCANO_BLOWS && data)
             {
                 if (!volcanoBlows.empty() && std::find(volcanoBlows.begin(), volcanoBlows.end(), data) != volcanoBlows.end())
                 {
                     return;
                 }
                 volcanoBlows.push_back(data);
             }
         }
References DATA_VOLCANO_BLOWS, and volcanoBlows.
SummonLavaWaves()
void boss_sartharion::boss_sartharionAI::SummonLavaWaves () inline private
Definition at line 616 of file boss_sartharion.cpp.
         {
             summons.RemoveNotExisting();
             Talk(WHISPER_LAVA_CHURN);
             extraEvents.ScheduleEvent(EVENT_SARTHARION_START_LAVA, 2000);
             extraEvents.ScheduleEvent(EVENT_SARTHARION_FINISH_LAVA, 9000);
             // Send wave from left
             if (lastLavaSide == LAVA_RIGHT_SIDE)
             {
                 for (uint8 i = 0; i < MAX_LEFT_LAVA_TSUNAMIS; ++i)
                 {
                     me->SummonCreature(NPC_FLAME_TSUNAMI, 3208.44f, 580.0f - (i * 50.0f), 55.8f, 0.0f, TEMPSUMMON_TIMED_DESPAWN, 12000);
                 }
                 lastLavaSide = LAVA_LEFT_SIDE;
             }
             // from right
             else
             {
                 for (uint8 i = 0; i < MAX_RIGHT_LAVA_TSUNAMIS; ++i)
                 {
                     me->SummonCreature(NPC_FLAME_TSUNAMI, 3283.44f, 555.0f - (i * 50.0f), 55.8f, 3.14f, TEMPSUMMON_TIMED_DESPAWN, 12000);
                 }
                 lastLavaSide = LAVA_RIGHT_SIDE;
             }
         }
References EVENT_SARTHARION_FINISH_LAVA, EVENT_SARTHARION_START_LAVA, extraEvents, lastLavaSide, LAVA_LEFT_SIDE, LAVA_RIGHT_SIDE, MAX_LEFT_LAVA_TSUNAMIS, MAX_RIGHT_LAVA_TSUNAMIS, ScriptedAI::me, NPC_FLAME_TSUNAMI, SummonList::RemoveNotExisting(), EventMap::ScheduleEvent(), WorldObject::SummonCreature(), BossAI::summons, CreatureAI::Talk(), TEMPSUMMON_TIMED_DESPAWN, and WHISPER_LAVA_CHURN.
Referenced by UpdateAI().
SummonStartingTriggers()
void boss_sartharion::boss_sartharionAI::SummonStartingTriggers () inline private
Definition at line 603 of file boss_sartharion.cpp.
         {
             for (uint8 i = 0; i < MAX_CYCLONE_COUNT; ++i)
             {
                 me->SummonCreature(NPC_FIRE_CYCLONE, CycloneSummonPos[i]);
             }
             for (uint8 i = 0; i < MAX_AREA_TRIGGER_COUNT; ++i)
             {
                 me->SummonCreature(NPC_SAFE_AREA_TRIGGER, AreaTriggerSummonPos[i]);
             }
         }
References AreaTriggerSummonPos, CycloneSummonPos, MAX_AREA_TRIGGER_COUNT, MAX_CYCLONE_COUNT, ScriptedAI::me, NPC_FIRE_CYCLONE, NPC_SAFE_AREA_TRIGGER, and WorldObject::SummonCreature().
Referenced by Reset().
UpdateAI()
void boss_sartharion::boss_sartharionAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from BossAI.
Definition at line 450 of file boss_sartharion.cpp.
         {
             if (!UpdateVictim())
             {
                 return;
             }
             extraEvents.Update(diff);
             // Special events which needs to be fired immidiately
             while (uint32 const eventId = extraEvents.ExecuteEvent())
             {
                 switch (eventId)
                 {
                     case EVENT_SARTHARION_BOUNDARY:
                     {
                         if (!IsTargetInBounds(me->GetVictim()))
{
                             EnterEvadeMode();
                         }
                         else
{
                             extraEvents.RepeatEvent(250);
                         }
                         break;
                     }
                     case EVENT_SARTHARION_SUMMON_LAVA:
                     {
                         if (!urand(0, 3))
{
                             Talk(SAY_SARTHARION_SPECIAL);
                         }
                         SummonLavaWaves();
                         extraEvents.RepeatEvent(25000);
                         return;
                     }
                     case EVENT_SARTHARION_START_LAVA:
                     {
                         SendLavaWaves(true);
                         return;
                     }
                     case EVENT_SARTHARION_FINISH_LAVA:
                     {
                         SendLavaWaves(false);
                         return;
                     }
                     // Handling of Drakes Events
                     // Dragon Calls
                     case EVENT_SARTHARION_CALL_TENEBRON:
                     {
                         Talk(SAY_SARTHARION_CALL_TENEBRON);
                         if (Creature* tenebron = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_TENEBRON)))
{
                             tenebron->AI()->DoAction(ACTION_CALL_DRAGON);
                         }
                         break;
                     }
                     case EVENT_SARTHARION_CALL_SHADRON:
                     {
                         Talk(SAY_SARTHARION_CALL_SHADRON);
                         if (Creature* shadron = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_SHADRON)))
{
                             shadron->AI()->DoAction(ACTION_CALL_DRAGON);
                         }
                         break;
                     }
                     case EVENT_SARTHARION_CALL_VESPERON:
                     {
                         Talk(SAY_SARTHARION_CALL_VESPERON);
                         if (Creature* vesperon = ObjectAccessor::GetCreature(*me, instance->GetGuidData(DATA_VESPERON)))
{
                             vesperon->AI()->DoAction(ACTION_CALL_DRAGON);
                         }
                         break;
                     }
                 }
             }
             // Handle Sartharion combat abbilities
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
             {
                 return;
             }
             while (uint32 const eventId = events.ExecuteEvent())
             {
                 switch (eventId)
                 {
                     case EVENT_SARTHARION_CAST_CLEAVE:
                     {
                         DoCastVictim(SPELL_SARTHARION_CLEAVE, false);
                         events.RepeatEvent(10000);
                         break;
                     }
                     case EVENT_SARTHARION_CAST_FLAME_BREATH:
                     {
                         DoCastVictim(SPELL_SARTHARION_FLAME_BREATH, false);
                         events.RepeatEvent(20000);
                         break;
                     }
                     case EVENT_SARTHARION_CAST_TAIL_LASH:
                     {
                         DoCastSelf(SPELL_SARTHARION_TAIL_LASH, false);
                         events.RepeatEvent(18000);
                         break;
                     }
                     case EVENT_SARTHARION_LAVA_STRIKE:
                     {
                         if (!urand(0, 2))
{
                             Talk(SAY_SARTHARION_SPECIAL_4);
                         }
                         summons.RemoveNotExisting();
                         uint8 rand = urand(0, MAX_CYCLONE_COUNT - 1); // 5 - numer of cyclones
                         uint8 iter = 0;
                         if (!summons.empty())
{
                             for (ObjectGuid const& summonGuid : summons)
{
                                 Creature* summon = ObjectAccessor::GetCreature(*me, summonGuid);
                                 if (summon && summon->GetEntry() == NPC_FIRE_CYCLONE && iter == rand)
{
                                     summon->CastSpell(summon, SPELL_CYCLONE_AURA_PERIODIC, true);
                                     ++iter;
                                 }
                             }
                         }
                         events.RepeatEvent((below11PctReached ? urand(1400, 2000) : urand(5000, 20000)));
                         break;
                     }
                     case EVENT_SARTHARION_BERSERK:
                     {
                         summons.DespawnEntry(NPC_SAFE_AREA_TRIGGER);
                         break;
                     }
                 }
                 if (me->HasUnitState(UNIT_STATE_CASTING))
                 {
                     return;
                 }
             }
             DoMeleeAttackIfReady();
         }
References ACTION_CALL_DRAGON, below11PctReached, Unit::CastSpell(), DATA_SHADRON, DATA_TENEBRON, DATA_VESPERON, SummonList::DespawnEntry(), UnitAI::DoCastSelf(), UnitAI::DoCastVictim(), UnitAI::DoMeleeAttackIfReady(), SummonList::empty(), CreatureAI::EnterEvadeMode(), EVENT_SARTHARION_BERSERK, EVENT_SARTHARION_BOUNDARY, EVENT_SARTHARION_CALL_SHADRON, EVENT_SARTHARION_CALL_TENEBRON, EVENT_SARTHARION_CALL_VESPERON, EVENT_SARTHARION_CAST_CLEAVE, EVENT_SARTHARION_CAST_FLAME_BREATH, EVENT_SARTHARION_CAST_TAIL_LASH, EVENT_SARTHARION_FINISH_LAVA, EVENT_SARTHARION_LAVA_STRIKE, EVENT_SARTHARION_START_LAVA, EVENT_SARTHARION_SUMMON_LAVA, EventMap::ExecuteEvent(), extraEvents, ObjectAccessor::GetCreature(), Object::GetEntry(), InstanceScript::GetGuidData(), Unit::GetVictim(), Unit::HasUnitState(), BossAI::instance, IsTargetInBounds(), MAX_CYCLONE_COUNT, ScriptedAI::me, NPC_FIRE_CYCLONE, NPC_SAFE_AREA_TRIGGER, SummonList::RemoveNotExisting(), EventMap::RepeatEvent(), SAY_SARTHARION_CALL_SHADRON, SAY_SARTHARION_CALL_TENEBRON, SAY_SARTHARION_CALL_VESPERON, SAY_SARTHARION_SPECIAL, SAY_SARTHARION_SPECIAL_4, SendLavaWaves(), SPELL_CYCLONE_AURA_PERIODIC, SPELL_SARTHARION_CLEAVE, SPELL_SARTHARION_FLAME_BREATH, SPELL_SARTHARION_TAIL_LASH, SummonLavaWaves(), BossAI::summons, CreatureAI::Talk(), UNIT_STATE_CASTING, EventMap::Update(), CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
below11PctReached
bool boss_sartharion::boss_sartharionAI::below11PctReached private
Definition at line 716 of file boss_sartharion.cpp.
Referenced by DamageTaken(), Reset(), and UpdateAI().
dragonsCount
uint8 boss_sartharion::boss_sartharionAI::dragonsCount private
Definition at line 713 of file boss_sartharion.cpp.
Referenced by EnterCombat(), GetData(), Reset(), and RespawnDragons().
extraEvents
EventMap boss_sartharion::boss_sartharionAI::extraEvents private
Definition at line 711 of file boss_sartharion.cpp.
Referenced by EnterCombat(), Reset(), SummonLavaWaves(), and UpdateAI().
lastLavaSide
uint8 boss_sartharion::boss_sartharionAI::lastLavaSide private
Definition at line 714 of file boss_sartharion.cpp.
Referenced by SummonLavaWaves().
usedBerserk
bool boss_sartharion::boss_sartharionAI::usedBerserk private
Definition at line 715 of file boss_sartharion.cpp.
Referenced by DamageTaken(), and Reset().
volcanoBlows
std::list<uint32> boss_sartharion::boss_sartharionAI::volcanoBlows private
Definition at line 712 of file boss_sartharion.cpp.
Referenced by GetData(), Reset(), and SetData().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp