Azerotcore-wotlk: deps/argon2/argon2/core.h File Reference
core.h File Reference
#include "argon2.h"
Classes
struct block_
struct Argon2_instance_t
struct Argon2_position_t
struct Argon2_thread_data
Macros
#define CONST_CAST(x) (x)(uintptr_t)
Typedefs
typedef struct block_ block
typedef struct Argon2_instance_t argon2_instance_t
typedef struct Argon2_position_t argon2_position_t
typedef struct Argon2_thread_data argon2_thread_data
Enumerations
enum argon2_core_constants {
ARGON2_BLOCK_SIZE = 1024 , ARGON2_QWORDS_IN_BLOCK = ARGON2_BLOCK_SIZE / 8 , ARGON2_OWORDS_IN_BLOCK = ARGON2_BLOCK_SIZE / 16 , ARGON2_HWORDS_IN_BLOCK = ARGON2_BLOCK_SIZE / 32 ,
ARGON2_512BIT_WORDS_IN_BLOCK = ARGON2_BLOCK_SIZE / 64 , ARGON2_ADDRESSES_IN_BLOCK = 128 , ARGON2_PREHASH_DIGEST_LENGTH = 64 , ARGON2_PREHASH_SEED_LENGTH = 72
}
Functions
void init_block_value (block *b, uint8_t in)
void copy_block (block *dst, const block *src)
void xor_block (block *dst, const block *src)
int allocate_memory (const argon2_context *context, uint8_t **memory, size_t num, size_t size)
void free_memory (const argon2_context *context, uint8_t *memory, size_t num, size_t size)
void secure_wipe_memory (void *v, size_t n)
void clear_internal_memory (void *v, size_t n)
uint32_t index_alpha (const argon2_instance_t *instance, const argon2_position_t *position, uint32_t pseudo_rand, int same_lane)
int validate_inputs (const argon2_context *context)
void initial_hash (uint8_t *blockhash, argon2_context *context, argon2_type type)
void fill_first_blocks (uint8_t *blockhash, const argon2_instance_t *instance)
int initialize (argon2_instance_t *instance, argon2_context *context)
void finalize (const argon2_context *context, argon2_instance_t *instance)
void fill_segment (const argon2_instance_t *instance, argon2_position_t position)
int fill_memory_blocks (argon2_instance_t *instance)
Macro Definition Documentation
CONST_CAST
#define CONST_CAST (x) (x)(uintptr_t)
Definition at line 23 of file core.h.
Typedef Documentation
argon2_instance_t
typedef struct Argon2_instance_t argon2_instance_t
argon2_position_t
typedef struct Argon2_position_t argon2_position_t
argon2_thread_data
typedef struct Argon2_thread_data argon2_thread_data
block
typedef struct block_ block
Enumeration Type Documentation
argon2_core_constants
enum argon2_core_constants
Enumerator
ARGON2_BLOCK_SIZE
ARGON2_QWORDS_IN_BLOCK
ARGON2_OWORDS_IN_BLOCK
ARGON2_HWORDS_IN_BLOCK
ARGON2_512BIT_WORDS_IN_BLOCK
ARGON2_ADDRESSES_IN_BLOCK
ARGON2_PREHASH_DIGEST_LENGTH
ARGON2_PREHASH_SEED_LENGTH
Definition at line 27 of file core.h.
{
     /* Memory block size in bytes */
     ARGON2_BLOCK_SIZE = 1024,
     ARGON2_QWORDS_IN_BLOCK = ARGON2_BLOCK_SIZE / 8,
     ARGON2_OWORDS_IN_BLOCK = ARGON2_BLOCK_SIZE / 16,
     ARGON2_HWORDS_IN_BLOCK = ARGON2_BLOCK_SIZE / 32,
     ARGON2_512BIT_WORDS_IN_BLOCK = ARGON2_BLOCK_SIZE / 64,
     /* Number of pseudo-random values generated by one call to Blake in Argon2i
        to
        generate reference block positions */
     ARGON2_ADDRESSES_IN_BLOCK = 128,
     /* Pre-hashing digest length and its extension*/
     ARGON2_PREHASH_DIGEST_LENGTH = 64,
     ARGON2_PREHASH_SEED_LENGTH = 72
 };
Function Documentation
allocate_memory()
int allocate_memory (const argon2_context * context, uint8_t ** memory, size_t num, size_t size)
Definition at line 89 of file core.c.
{
     size_t memory_size = num*size;
     if (memory == NULL) {
         return ARGON2_MEMORY_ALLOCATION_ERROR;
     }
     /* 1. Check for multiplication overflow */
     if (size != 0 && memory_size / size != num) {
         return ARGON2_MEMORY_ALLOCATION_ERROR;
     }
     /* 2. Try to allocate with appropriate allocator */
     if (context->allocate_cbk) {
         (context->allocate_cbk)(memory, memory_size);
     } else {
         *memory = malloc(memory_size);
     }
     if (*memory == NULL) {
         return ARGON2_MEMORY_ALLOCATION_ERROR;
     }
     return ARGON2_OK;
 }
References Argon2_Context::allocate_cbk, ARGON2_MEMORY_ALLOCATION_ERROR, ARGON2_OK, and NULL.
Referenced by initialize().
clear_internal_memory()
void clear_internal_memory (void * v, size_t n)
Definition at line 149 of file core.c.
{
   if (FLAG_clear_internal_memory && v) {
     secure_wipe_memory(v, n);
   }
 }
Referenced by fill_first_blocks(), finalize(), free_memory(), and initialize().
copy_block()
void copy_block (block * dst, const block * src)
Definition at line 62 of file core.c.
{
     memcpy(dst->v, src->v, sizeof(uint64_t) * ARGON2_QWORDS_IN_BLOCK);
 }
References ARGON2_QWORDS_IN_BLOCK, memcpy, and block_::v.
Referenced by fill_block(), and finalize().
fill_first_blocks()
void fill_first_blocks (uint8_t * blockhash, const argon2_instance_t * instance)
Definition at line 515 of file core.c.
{
     uint32_t l;
     /* Make the first and second block in each lane as G(H0||0||i) or
        G(H0||1||i) */
     uint8_t blockhash_bytes[ARGON2_BLOCK_SIZE];
     for (l = 0; l < instance->lanes; ++l) {
         store32(blockhash + ARGON2_PREHASH_DIGEST_LENGTH, 0);
         store32(blockhash + ARGON2_PREHASH_DIGEST_LENGTH + 4, l);
         blake2b_long(blockhash_bytes, ARGON2_BLOCK_SIZE, blockhash,
                      ARGON2_PREHASH_SEED_LENGTH);
         load_block(&instance->memory[l * instance->lane_length + 0],
                    blockhash_bytes);
         store32(blockhash + ARGON2_PREHASH_DIGEST_LENGTH, 1);
         blake2b_long(blockhash_bytes, ARGON2_BLOCK_SIZE, blockhash,
                      ARGON2_PREHASH_SEED_LENGTH);
         load_block(&instance->memory[l * instance->lane_length + 1],
                    blockhash_bytes);
     }
     clear_internal_memory(blockhash_bytes, ARGON2_BLOCK_SIZE);
 }
References ARGON2_BLOCK_SIZE, ARGON2_PREHASH_DIGEST_LENGTH, ARGON2_PREHASH_SEED_LENGTH, blake2b_long(), clear_internal_memory(), mpq::l, Argon2_instance_t::lane_length, Argon2_instance_t::lanes, load_block(), Argon2_instance_t::memory, and store32().
Referenced by initialize().
fill_memory_blocks()
int fill_memory_blocks (argon2_instance_t * instance)
Definition at line 376 of file core.c.
{
     if (instance == NULL || instance->lanes == 0) {
         return ARGON2_INCORRECT_PARAMETER;
     }
 #if defined(ARGON2_NO_THREADS)
     return fill_memory_blocks_st(instance);
 #else
     return instance->threads == 1 ?
             fill_memory_blocks_st(instance) : fill_memory_blocks_mt(instance);
 #endif
 }
References ARGON2_INCORRECT_PARAMETER, fill_memory_blocks_mt(), fill_memory_blocks_st(), Argon2_instance_t::lanes, NULL, and Argon2_instance_t::threads.
Referenced by argon2_ctx().
fill_segment()
void fill_segment (const argon2_instance_t * instance, argon2_position_t position)
Definition at line 174 of file opt.c.
{
     block *ref_block = NULL, *curr_block = NULL;
     block address_block, input_block;
     uint64_t pseudo_rand, ref_index, ref_lane;
     uint32_t prev_offset, curr_offset;
     uint32_t starting_index, i;
 #if defined(__AVX512F__)
     __m512i state[ARGON2_512BIT_WORDS_IN_BLOCK];
 #elif defined(__AVX2__)
     __m256i state[ARGON2_HWORDS_IN_BLOCK];
 #else
     __m128i state[ARGON2_OWORDS_IN_BLOCK];
 #endif
     int data_independent_addressing;
     if (instance == NULL) {
         return;
     }
     data_independent_addressing =
         (instance->type == Argon2_i) ||
         (instance->type == Argon2_id && (position.pass == 0) &&
          (position.slice < ARGON2_SYNC_POINTS / 2));
     if (data_independent_addressing) {
         init_block_value(&input_block, 0);
         input_block.v[0] = position.pass;
         input_block.v[1] = position.lane;
         input_block.v[2] = position.slice;
         input_block.v[3] = instance->memory_blocks;
         input_block.v[4] = instance->passes;
         input_block.v[5] = instance->type;
     }
     starting_index = 0;
     if ((0 == position.pass) && (0 == position.slice)) {
         starting_index = 2; /* we have already generated the first two blocks */
         /* Don't forget to generate the first block of addresses: */
         if (data_independent_addressing) {
             next_addresses(&address_block, &input_block);
         }
     }
     /* Offset of the current block */
     curr_offset = position.lane * instance->lane_length +
                   position.slice * instance->segment_length + starting_index;
     if (0 == curr_offset % instance->lane_length) {
         /* Last block in this lane */
         prev_offset = curr_offset + instance->lane_length - 1;
     } else {
         /* Previous block */
         prev_offset = curr_offset - 1;
     }
     memcpy(state, ((instance->memory + prev_offset)->v), ARGON2_BLOCK_SIZE);
     for (i = starting_index; i < instance->segment_length;
          ++i, ++curr_offset, ++prev_offset) {
         /*1.1 Rotating prev_offset if needed */
         if (curr_offset % instance->lane_length == 1) {
             prev_offset = curr_offset - 1;
         }
         /* 1.2 Computing the index of the reference block */
         /* 1.2.1 Taking pseudo-random value from the previous block */
         if (data_independent_addressing) {
             if (i % ARGON2_ADDRESSES_IN_BLOCK == 0) {
                 next_addresses(&address_block, &input_block);
             }
             pseudo_rand = address_block.v[i % ARGON2_ADDRESSES_IN_BLOCK];
         } else {
             pseudo_rand = instance->memory[prev_offset].v[0];
         }
         /* 1.2.2 Computing the lane of the reference block */
         ref_lane = ((pseudo_rand >> 32)) % instance->lanes;
         if ((position.pass == 0) && (position.slice == 0)) {
             /* Can not reference other lanes yet */
             ref_lane = position.lane;
         }
         /* 1.2.3 Computing the number of possible reference block within the
          * lane.
          */
         position.index = i;
         ref_index = index_alpha(instance, &position, pseudo_rand & 0xFFFFFFFF,
                                 ref_lane == position.lane);
         /* 2 Creating a new block */
         ref_block =
             instance->memory + instance->lane_length * ref_lane + ref_index;
         curr_block = instance->memory + curr_offset;
         if (ARGON2_VERSION_10 == instance->version) {
             /* version 1.2.1 and earlier: overwrite, not XOR */
             fill_block(state, ref_block, curr_block, 0);
         } else {
             if(0 == position.pass) {
                 fill_block(state, ref_block, curr_block, 0);
             } else {
                 fill_block(state, ref_block, curr_block, 1);
             }
         }
     }
 }
References ARGON2_512BIT_WORDS_IN_BLOCK, ARGON2_ADDRESSES_IN_BLOCK, ARGON2_BLOCK_SIZE, ARGON2_HWORDS_IN_BLOCK, Argon2_i, Argon2_id, ARGON2_OWORDS_IN_BLOCK, ARGON2_SYNC_POINTS, ARGON2_VERSION_10, fill_block(), Argon2_position_t::index, index_alpha(), init_block_value(), Argon2_position_t::lane, Argon2_instance_t::lane_length, Argon2_instance_t::lanes, memcpy, Argon2_instance_t::memory, Argon2_instance_t::memory_blocks, next_addresses(), NULL, Argon2_position_t::pass, Argon2_instance_t::passes, Argon2_instance_t::segment_length, Argon2_position_t::slice, Argon2_instance_t::type, block_::v, and Argon2_instance_t::version.
Referenced by fill_memory_blocks_st(), and fill_segment_thr().
finalize()
void finalize (const argon2_context * context, argon2_instance_t * instance)
Definition at line 155 of file core.c.
{
     if (context != NULL && instance != NULL) {
         block blockhash;
         uint32_t l;
         copy_block(&blockhash, instance->memory + instance->lane_length - 1);
         /* XOR the last blocks */
         for (l = 1; l < instance->lanes; ++l) {
             uint32_t last_block_in_lane =
                 l * instance->lane_length + (instance->lane_length - 1);
             xor_block(&blockhash, instance->memory + last_block_in_lane);
         }
         /* Hash the result */
         {
             uint8_t blockhash_bytes[ARGON2_BLOCK_SIZE];
             store_block(blockhash_bytes, &blockhash);
             blake2b_long(context->out, context->outlen, blockhash_bytes,
                          ARGON2_BLOCK_SIZE);
             /* clear blockhash and blockhash_bytes */
             clear_internal_memory(blockhash.v, ARGON2_BLOCK_SIZE);
             clear_internal_memory(blockhash_bytes, ARGON2_BLOCK_SIZE);
         }
 #ifdef GENKAT
         print_tag(context->out, context->outlen);
 #endif
         free_memory(context, (uint8_t *)instance->memory,
                     instance->memory_blocks, sizeof(block));
     }
 }
References ARGON2_BLOCK_SIZE, blake2b_long(), clear_internal_memory(), copy_block(), free_memory(), mpq::l, Argon2_instance_t::lane_length, Argon2_instance_t::lanes, Argon2_instance_t::memory, Argon2_instance_t::memory_blocks, NULL, Argon2_Context::out, Argon2_Context::outlen, store_block(), block_::v, and xor_block().
Referenced by argon2_ctx().
free_memory()
void free_memory (const argon2_context * context, uint8_t * memory, size_t num, size_t size)
Definition at line 115 of file core.c.
{
     size_t memory_size = num*size;
     clear_internal_memory(memory, memory_size);
     if (context->free_cbk) {
         (context->free_cbk)(memory, memory_size);
     } else {
         free(memory);
     }
 }
References clear_internal_memory(), and Argon2_Context::free_cbk.
Referenced by finalize().
index_alpha()
uint32_t index_alpha (const argon2_instance_t * instance, const argon2_position_t * position, uint32_t pseudo_rand, int same_lane)
Definition at line 189 of file core.c.
{
     /*
      * Pass 0:
      *      This lane : all already finished segments plus already constructed
      * blocks in this segment
      *      Other lanes : all already finished segments
      * Pass 1+:
      *      This lane : (SYNC_POINTS - 1) last segments plus already constructed
      * blocks in this segment
      *      Other lanes : (SYNC_POINTS - 1) last segments
      */
     uint32_t reference_area_size;
     uint64_t relative_position;
     uint32_t start_position, absolute_position;
     if (0 == position->pass) {
         /* First pass */
         if (0 == position->slice) {
             /* First slice */
             reference_area_size =
                 position->index - 1; /* all but the previous */
         } else {
             if (same_lane) {
                 /* The same lane => add current segment */
                 reference_area_size =
                     position->slice * instance->segment_length +
                     position->index - 1;
             } else {
                 reference_area_size =
                     position->slice * instance->segment_length +
                     ((position->index == 0) ? (-1) : 0);
             }
         }
     } else {
         /* Second pass */
         if (same_lane) {
             reference_area_size = instance->lane_length -
                                   instance->segment_length + position->index -
                                   1;
         } else {
             reference_area_size = instance->lane_length -
                                   instance->segment_length +
                                   ((position->index == 0) ? (-1) : 0);
         }
     }
     /* 1.2.4. Mapping pseudo_rand to 0..<reference_area_size-1> and produce
      * relative position */
     relative_position = pseudo_rand;
     relative_position = relative_position * relative_position >> 32;
     relative_position = reference_area_size - 1 -
                         (reference_area_size * relative_position >> 32);
     /* 1.2.5 Computing starting position */
     start_position = 0;
     if (0 != position->pass) {
         start_position = (position->slice == ARGON2_SYNC_POINTS - 1)
                              ? 0
                              : (position->slice + 1) * instance->segment_length;
     }
     /* 1.2.6. Computing absolute position */
     absolute_position = (start_position + relative_position) %
                         instance->lane_length; /* absolute position */
     return absolute_position;
 }
References ARGON2_SYNC_POINTS, Argon2_position_t::index, Argon2_instance_t::lane_length, Argon2_position_t::pass, Argon2_instance_t::segment_length, and Argon2_position_t::slice.
Referenced by fill_segment().
init_block_value()
void init_block_value (block * b, uint8_t in)
Definition at line 60 of file core.c.
 { memset(b->v, in, sizeof(b->v)); }
References b, and memset.
Referenced by fill_segment().
initial_hash()
void initial_hash (uint8_t * blockhash, argon2_context * context, argon2_type type)
Definition at line 538 of file core.c.
{
     blake2b_state BlakeHash;
     uint8_t value[sizeof(uint32_t)];
     if (NULL == context || NULL == blockhash) {
         return;
     }
     blake2b_init(&BlakeHash, ARGON2_PREHASH_DIGEST_LENGTH);
     store32(&value, context->lanes);
     blake2b_update(&BlakeHash, (const uint8_t *)&value, sizeof(value));
     store32(&value, context->outlen);
     blake2b_update(&BlakeHash, (const uint8_t *)&value, sizeof(value));
     store32(&value, context->m_cost);
     blake2b_update(&BlakeHash, (const uint8_t *)&value, sizeof(value));
     store32(&value, context->t_cost);
     blake2b_update(&BlakeHash, (const uint8_t *)&value, sizeof(value));
     store32(&value, context->version);
     blake2b_update(&BlakeHash, (const uint8_t *)&value, sizeof(value));
     store32(&value, (uint32_t)type);
     blake2b_update(&BlakeHash, (const uint8_t *)&value, sizeof(value));
     store32(&value, context->pwdlen);
     blake2b_update(&BlakeHash, (const uint8_t *)&value, sizeof(value));
     if (context->pwd != NULL) {
         blake2b_update(&BlakeHash, (const uint8_t *)context->pwd,
                        context->pwdlen);
         if (context->flags & ARGON2_FLAG_CLEAR_PASSWORD) {
             secure_wipe_memory(context->pwd, context->pwdlen);
             context->pwdlen = 0;
         }
     }
     store32(&value, context->saltlen);
     blake2b_update(&BlakeHash, (const uint8_t *)&value, sizeof(value));
     if (context->salt != NULL) {
         blake2b_update(&BlakeHash, (const uint8_t *)context->salt,
                        context->saltlen);
     }
     store32(&value, context->secretlen);
     blake2b_update(&BlakeHash, (const uint8_t *)&value, sizeof(value));
     if (context->secret != NULL) {
         blake2b_update(&BlakeHash, (const uint8_t *)context->secret,
                        context->secretlen);
         if (context->flags & ARGON2_FLAG_CLEAR_SECRET) {
             secure_wipe_memory(context->secret, context->secretlen);
             context->secretlen = 0;
         }
     }
     store32(&value, context->adlen);
     blake2b_update(&BlakeHash, (const uint8_t *)&value, sizeof(value));
     if (context->ad != NULL) {
         blake2b_update(&BlakeHash, (const uint8_t *)context->ad,
                        context->adlen);
     }
     blake2b_final(&BlakeHash, blockhash, ARGON2_PREHASH_DIGEST_LENGTH);
 }
References Argon2_Context::ad, Argon2_Context::adlen, ARGON2_FLAG_CLEAR_PASSWORD, ARGON2_FLAG_CLEAR_SECRET, ARGON2_PREHASH_DIGEST_LENGTH, blake2b_final(), blake2b_init(), blake2b_update(), Argon2_Context::flags, Argon2_Context::lanes, Argon2_Context::m_cost, NULL, Argon2_Context::outlen, Argon2_Context::pwd, Argon2_Context::pwdlen, Argon2_Context::salt, Argon2_Context::saltlen, Argon2_Context::secret, Argon2_Context::secretlen, secure_wipe_memory(), store32(), Argon2_Context::t_cost, and Argon2_Context::version.
Referenced by initialize().
initialize()
int initialize (argon2_instance_t * instance, argon2_context * context)
Definition at line 612 of file core.c.
{
     uint8_t blockhash[ARGON2_PREHASH_SEED_LENGTH];
     int result = ARGON2_OK;
     if (instance == NULL || context == NULL)
         return ARGON2_INCORRECT_PARAMETER;
     instance->context_ptr = context;
     /* 1. Memory allocation */
     result = allocate_memory(context, (uint8_t **)&(instance->memory),
                              instance->memory_blocks, sizeof(block));
     if (result != ARGON2_OK) {
         return result;
     }
     /* 2. Initial hashing */
     /* H_0 + 8 extra bytes to produce the first blocks */
     /* uint8_t blockhash[ARGON2_PREHASH_SEED_LENGTH]; */
     /* Hashing all inputs */
     initial_hash(blockhash, context, instance->type);
     /* Zeroing 8 extra bytes */
     clear_internal_memory(blockhash + ARGON2_PREHASH_DIGEST_LENGTH,
                           ARGON2_PREHASH_SEED_LENGTH -
                               ARGON2_PREHASH_DIGEST_LENGTH);
 #ifdef GENKAT
     initial_kat(blockhash, context, instance->type);
 #endif
     /* 3. Creating first blocks, we always have at least two blocks in a slice
      */
     fill_first_blocks(blockhash, instance);
     /* Clearing the hash */
     clear_internal_memory(blockhash, ARGON2_PREHASH_SEED_LENGTH);
     return ARGON2_OK;
 }
References allocate_memory(), ARGON2_INCORRECT_PARAMETER, ARGON2_OK, ARGON2_PREHASH_DIGEST_LENGTH, ARGON2_PREHASH_SEED_LENGTH, clear_internal_memory(), Argon2_instance_t::context_ptr, fill_first_blocks(), initial_hash(), Argon2_instance_t::memory, Argon2_instance_t::memory_blocks, NULL, and Argon2_instance_t::type.
Referenced by argon2_ctx(), misc_commandscript::HandleBagsClearCommand(), and misc_commandscript::HandleInventoryCountCommand().
secure_wipe_memory()
void secure_wipe_memory (void * v, size_t n)
Definition at line 134 of file core.c.
{
 #if defined(_MSC_VER) && VC_GE_2005(_MSC_VER)
     SecureZeroMemory(v, n);
 #elif defined memset_s
     memset_s(v, n, 0, n);
 #elif defined(HAVE_EXPLICIT_BZERO)
     explicit_bzero(v, n);
 #else
     static void *(*const volatile memset_sec)(void *, int, size_t) = &memset;
     memset_sec(v, 0, n);
 #endif
 }
References memset.
Referenced by clear_internal_memory(), and initial_hash().
validate_inputs()
int validate_inputs (const argon2_context * context)
Definition at line 388 of file core.c.
{
     if (NULL == context) {
         return ARGON2_INCORRECT_PARAMETER;
     }
     if (NULL == context->out) {
         return ARGON2_OUTPUT_PTR_NULL;
     }
     /* Validate output length */
     if (ARGON2_MIN_OUTLEN > context->outlen) {
         return ARGON2_OUTPUT_TOO_SHORT;
     }
     if (ARGON2_MAX_OUTLEN < context->outlen) {
         return ARGON2_OUTPUT_TOO_LONG;
     }
     /* Validate password (required param) */
     if (NULL == context->pwd) {
         if (0 != context->pwdlen) {
             return ARGON2_PWD_PTR_MISMATCH;
         }
     }
     if (ARGON2_MIN_PWD_LENGTH > context->pwdlen) {
       return ARGON2_PWD_TOO_SHORT;
     }
     if (ARGON2_MAX_PWD_LENGTH < context->pwdlen) {
         return ARGON2_PWD_TOO_LONG;
     }
     /* Validate salt (required param) */
     if (NULL == context->salt) {
         if (0 != context->saltlen) {
             return ARGON2_SALT_PTR_MISMATCH;
         }
     }
     if (ARGON2_MIN_SALT_LENGTH > context->saltlen) {
         return ARGON2_SALT_TOO_SHORT;
     }
     if (ARGON2_MAX_SALT_LENGTH < context->saltlen) {
         return ARGON2_SALT_TOO_LONG;
     }
     /* Validate secret (optional param) */
     if (NULL == context->secret) {
         if (0 != context->secretlen) {
             return ARGON2_SECRET_PTR_MISMATCH;
         }
     } else {
         if (ARGON2_MIN_SECRET > context->secretlen) {
             return ARGON2_SECRET_TOO_SHORT;
         }
         if (ARGON2_MAX_SECRET < context->secretlen) {
             return ARGON2_SECRET_TOO_LONG;
         }
     }
     /* Validate associated data (optional param) */
     if (NULL == context->ad) {
         if (0 != context->adlen) {
             return ARGON2_AD_PTR_MISMATCH;
         }
     } else {
         if (ARGON2_MIN_AD_LENGTH > context->adlen) {
             return ARGON2_AD_TOO_SHORT;
         }
         if (ARGON2_MAX_AD_LENGTH < context->adlen) {
             return ARGON2_AD_TOO_LONG;
         }
     }
     /* Validate memory cost */
     if (ARGON2_MIN_MEMORY > context->m_cost) {
         return ARGON2_MEMORY_TOO_LITTLE;
     }
     if (ARGON2_MAX_MEMORY < context->m_cost) {
         return ARGON2_MEMORY_TOO_MUCH;
     }
     if (context->m_cost < 8 * context->lanes) {
         return ARGON2_MEMORY_TOO_LITTLE;
     }
     /* Validate time cost */
     if (ARGON2_MIN_TIME > context->t_cost) {
         return ARGON2_TIME_TOO_SMALL;
     }
     if (ARGON2_MAX_TIME < context->t_cost) {
         return ARGON2_TIME_TOO_LARGE;
     }
     /* Validate lanes */
     if (ARGON2_MIN_LANES > context->lanes) {
         return ARGON2_LANES_TOO_FEW;
     }
     if (ARGON2_MAX_LANES < context->lanes) {
         return ARGON2_LANES_TOO_MANY;
     }
     /* Validate threads */
     if (ARGON2_MIN_THREADS > context->threads) {
         return ARGON2_THREADS_TOO_FEW;
     }
     if (ARGON2_MAX_THREADS < context->threads) {
         return ARGON2_THREADS_TOO_MANY;
     }
     if (NULL != context->allocate_cbk && NULL == context->free_cbk) {
         return ARGON2_FREE_MEMORY_CBK_NULL;
     }
     if (NULL == context->allocate_cbk && NULL != context->free_cbk) {
         return ARGON2_ALLOCATE_MEMORY_CBK_NULL;
     }
     return ARGON2_OK;
 }
References Argon2_Context::ad, Argon2_Context::adlen, Argon2_Context::allocate_cbk, ARGON2_AD_PTR_MISMATCH, ARGON2_AD_TOO_LONG, ARGON2_AD_TOO_SHORT, ARGON2_ALLOCATE_MEMORY_CBK_NULL, ARGON2_FREE_MEMORY_CBK_NULL, ARGON2_INCORRECT_PARAMETER, ARGON2_LANES_TOO_FEW, ARGON2_LANES_TOO_MANY, ARGON2_MEMORY_TOO_LITTLE, ARGON2_MEMORY_TOO_MUCH, ARGON2_MIN_AD_LENGTH, ARGON2_MIN_LANES, ARGON2_MIN_MEMORY, ARGON2_MIN_OUTLEN, ARGON2_MIN_PWD_LENGTH, ARGON2_MIN_SALT_LENGTH, ARGON2_MIN_SECRET, ARGON2_MIN_THREADS, ARGON2_MIN_TIME, ARGON2_OK, ARGON2_OUTPUT_PTR_NULL, ARGON2_OUTPUT_TOO_LONG, ARGON2_OUTPUT_TOO_SHORT, ARGON2_PWD_PTR_MISMATCH, ARGON2_PWD_TOO_LONG, ARGON2_PWD_TOO_SHORT, ARGON2_SALT_PTR_MISMATCH, ARGON2_SALT_TOO_LONG, ARGON2_SALT_TOO_SHORT, ARGON2_SECRET_PTR_MISMATCH, ARGON2_SECRET_TOO_LONG, ARGON2_SECRET_TOO_SHORT, ARGON2_THREADS_TOO_FEW, ARGON2_THREADS_TOO_MANY, ARGON2_TIME_TOO_LARGE, ARGON2_TIME_TOO_SMALL, Argon2_Context::free_cbk, Argon2_Context::lanes, Argon2_Context::m_cost, NULL, Argon2_Context::out, Argon2_Context::outlen, Argon2_Context::pwd, Argon2_Context::pwdlen, Argon2_Context::salt, Argon2_Context::saltlen, Argon2_Context::secret, Argon2_Context::secretlen, Argon2_Context::t_cost, and Argon2_Context::threads.
Referenced by argon2_ctx(), decode_string(), and encode_string().
xor_block()
void xor_block (block * dst, const block * src)
Definition at line 66 of file core.c.
{
     int i;
     for (i = 0; i < ARGON2_QWORDS_IN_BLOCK; ++i) {
         dst->v[i] ^= src->v[i];
     }
 }
References ARGON2_QWORDS_IN_BLOCK, and block_::v.
Referenced by fill_block(), and finalize().