Azerotcore-wotlk: deps/mysqllite/mysys/mf_iocache.c File Reference
mf_iocache.c File Reference
#include "mysys_priv.h"
#include <m_string.h>
#include <errno.h>
Macros
#define lock_append_buffer(info) mysql_mutex_lock(&(info)->append_buffer_lock)
#define unlock_append_buffer(info) mysql_mutex_unlock(&(info)->append_buffer_lock)
#define IO_ROUND_UP(X) (((X)+IO_SIZE-1) & ~(IO_SIZE-1))
#define IO_ROUND_DN(X) ((X) & ~(IO_SIZE-1))
#define LOCK_APPEND_BUFFER
#define UNLOCK_APPEND_BUFFER
Functions
void setup_io_cache (IO_CACHE *info)
static void init_functions (IO_CACHE *info)
int init_io_cache (IO_CACHE *info, File file, size_t cachesize, enum cache_type type, my_off_t seek_offset, pbool use_async_io, myf cache_myflags)
my_bool reinit_io_cache (IO_CACHE *info, enum cache_type type, my_off_t seek_offset, pbool use_async_io __attribute__((unused)), pbool clear_cache)
int _my_b_read (register IO_CACHE *info, uchar *Buffer, size_t Count)
void init_io_cache_share (IO_CACHE *read_cache, IO_CACHE_SHARE *cshare, IO_CACHE *write_cache, uint num_threads)
void remove_io_thread (IO_CACHE *cache)
static int lock_io_cache (IO_CACHE *cache, my_off_t pos)
static void unlock_io_cache (IO_CACHE *cache)
int _my_b_read_r (register IO_CACHE *cache, uchar *Buffer, size_t Count)
static void copy_to_read_buffer (IO_CACHE *write_cache, const uchar *write_buffer, size_t write_length)
int _my_b_seq_read (register IO_CACHE *info, uchar *Buffer, size_t Count)
int _my_b_get (IO_CACHE *info)
int _my_b_write (register IO_CACHE *info, const uchar *Buffer, size_t Count)
int my_b_append (register IO_CACHE *info, const uchar *Buffer, size_t Count)
int my_b_safe_write (IO_CACHE *info, const uchar *Buffer, size_t Count)
int my_block_write (register IO_CACHE *info, const uchar *Buffer, size_t Count, my_off_t pos)
int my_b_flush_io_cache (IO_CACHE *info, int need_append_buffer_lock __attribute__((unused)))
int end_io_cache (IO_CACHE *info)
Macro Definition Documentation
IO_ROUND_DN
#define IO_ROUND_DN (X) ((X) & ~(IO_SIZE-1))
Definition at line 64 of file mf_iocache.c.
IO_ROUND_UP
#define IO_ROUND_UP (X) (((X)+IO_SIZE-1) & ~(IO_SIZE-1))
Definition at line 63 of file mf_iocache.c.
lock_append_buffer
#define lock_append_buffer (info) mysql_mutex_lock(&(info)->append_buffer_lock)
Definition at line 58 of file mf_iocache.c.
LOCK_APPEND_BUFFER
#define LOCK_APPEND_BUFFER
Value:
  if (need_append_buffer_lock) \
  lock_append_buffer(info);
Definition at line 1717 of file mf_iocache.c.
unlock_append_buffer
#define unlock_append_buffer (info) mysql_mutex_unlock(&(info)->append_buffer_lock)
Definition at line 60 of file mf_iocache.c.
UNLOCK_APPEND_BUFFER
#define UNLOCK_APPEND_BUFFER
Value:
  if (need_append_buffer_lock) \
  unlock_append_buffer(info);
Definition at line 1719 of file mf_iocache.c.
Function Documentation
_my_b_get()
int _my_b_get (IO_CACHE * info)
Definition at line 1505 of file mf_iocache.c.
 {
   uchar buff;
   IO_CACHE_CALLBACK pre_read,post_read;
   if ((pre_read = info->pre_read))
     (*pre_read)(info);
   if ((*(info)->read_function)(info,&buff,1))
     return my_b_EOF;
   if ((post_read = info->post_read))
     (*post_read)(info);
   return (int) (uchar) buff;
 }
References my_b_EOF, st_io_cache::post_read, and st_io_cache::pre_read.
_my_b_read()
int _my_b_read (register IO_CACHE * info, uchar * Buffer, size_t Count)
Definition at line 449 of file mf_iocache.c.
 {
   size_t length,diff_length,left_length, max_length;
   my_off_t pos_in_file;
   DBUG_ENTER("_my_b_read");
   /* If the buffer is not empty yet, copy what is available. */
   if ((left_length= (size_t) (info->read_end-info->read_pos)))
   {
     DBUG_ASSERT(Count >= left_length);  /* User is not using my_b_read() */
     memcpy(Buffer,info->read_pos, left_length);
     Buffer+=left_length;
     Count-=left_length;
   }
   /* pos_in_file always point on where info->buffer was read */
   pos_in_file=info->pos_in_file+ (size_t) (info->read_end - info->buffer);
   /*
     Whenever a function which operates on IO_CACHE flushes/writes
     some part of the IO_CACHE to disk it will set the property
     "seek_not_done" to indicate this to other functions operating
     on the IO_CACHE.
   */
   if (info->seek_not_done)
   {
     if ((mysql_file_seek(info->file, pos_in_file, MY_SEEK_SET, MYF(0))
         != MY_FILEPOS_ERROR))
     {
       /* No error, reset seek_not_done flag. */
       info->seek_not_done= 0;
     }
     else
     {
       /*
         If the seek failed and the error number is ESPIPE, it is because
         info->file is a pipe or socket or FIFO.  We never should have tried
         to seek on that.  See Bugs#25807 and #22828 for more info.
       */
       DBUG_ASSERT(my_errno != ESPIPE);
       info->error= -1;
       DBUG_RETURN(1);
     }
   }
   /*
     Calculate, how much we are within a IO_SIZE block. Ideally this
     should be zero.
   */
   diff_length= (size_t) (pos_in_file & (IO_SIZE-1));
   /*
     If more than a block plus the rest of the current block is wanted,
     we do read directly, without filling the buffer.
   */
   if (Count >= (size_t) (IO_SIZE+(IO_SIZE-diff_length)))
   {                 /* Fill first intern buffer */
     size_t read_length;
     if (info->end_of_file <= pos_in_file)
     {
       /* End of file. Return, what we did copy from the buffer. */
       info->error= (int) left_length;
       DBUG_RETURN(1);
     }
     /*
       Crop the wanted count to a multiple of IO_SIZE and subtract,
       what we did already read from a block. That way, the read will
       end aligned with a block.
     */
     length=(Count & (size_t) ~(IO_SIZE-1))-diff_length;
     if ((read_length= mysql_file_read(info->file,Buffer, length, info->myflags))
     != length)
     {
       /*
         If we didn't get, what we wanted, we either return -1 for a read
         error, or (it's end of file), how much we got in total.
       */
       info->error= (read_length == (size_t) -1 ? -1 :
             (int) (read_length+left_length));
       DBUG_RETURN(1);
     }
     Count-=length;
     Buffer+=length;
     pos_in_file+=length;
     left_length+=length;
     diff_length=0;
   }
   /*
     At this point, we want less than one and a partial block.
     We will read a full cache, minus the number of bytes, we are
     within a block already. So we will reach new alignment.
   */
   max_length= info->read_length-diff_length;
   /* We will not read past end of file. */
   if (info->type != READ_FIFO &&
       max_length > (info->end_of_file - pos_in_file))
     max_length= (size_t) (info->end_of_file - pos_in_file);
   /*
     If there is nothing left to read,
       we either are done, or we failed to fulfill the request.
     Otherwise, we read max_length into the cache.
   */
   if (!max_length)
   {
     if (Count)
     {
       /* We couldn't fulfil the request. Return, how much we got. */
       info->error= left_length;
       DBUG_RETURN(1);
     }
     length=0;               /* Didn't read any chars */
   }
   else if ((length= mysql_file_read(info->file,info->buffer, max_length,
                             info->myflags)) < Count ||
        length == (size_t) -1)
   {
     /*
       We got an read error, or less than requested (end of file).
       If not a read error, copy, what we got.
     */
     if (length != (size_t) -1)
       memcpy(Buffer, info->buffer, length);
     info->pos_in_file= pos_in_file;
     /* For a read error, return -1, otherwise, what we got in total. */
     info->error= length == (size_t) -1 ? -1 : (int) (length+left_length);
     info->read_pos=info->read_end=info->buffer;
     DBUG_RETURN(1);
   }
   /*
     Count is the remaining number of bytes requested.
     length is the amount of data in the cache.
     Read Count bytes from the cache.
   */
   info->read_pos=info->buffer+Count;
   info->read_end=info->buffer+length;
   info->pos_in_file=pos_in_file;
   memcpy(Buffer, info->buffer, Count);
   DBUG_RETURN(0);
 }
References st_io_cache::buffer, Acore::Count(), DBUG_ASSERT, DBUG_ENTER, DBUG_RETURN, st_io_cache::end_of_file, st_io_cache::error, st_io_cache::file, IO_SIZE, G3D::length(), memcpy, my_errno, MY_FILEPOS_ERROR, MY_SEEK_SET, MYF, st_io_cache::myflags, mysql_file_read, mysql_file_seek, st_io_cache::pos_in_file, st_io_cache::read_end, READ_FIFO, st_io_cache::read_length, st_io_cache::read_pos, st_io_cache::seek_not_done, and st_io_cache::type.
Referenced by init_functions().
_my_b_read_r()
int _my_b_read_r (register IO_CACHE * cache, uchar * Buffer, size_t Count)
Definition at line 992 of file mf_iocache.c.
 {
   my_off_t pos_in_file;
   size_t length, diff_length, left_length;
   IO_CACHE_SHARE *cshare= cache->share;
   DBUG_ENTER("_my_b_read_r");
   if ((left_length= (size_t) (cache->read_end - cache->read_pos)))
   {
     DBUG_ASSERT(Count >= left_length);  /* User is not using my_b_read() */
     memcpy(Buffer, cache->read_pos, left_length);
     Buffer+= left_length;
     Count-= left_length;
   }
   while (Count)
   {
     size_t cnt, len;
     pos_in_file= cache->pos_in_file + (cache->read_end - cache->buffer);
     diff_length= (size_t) (pos_in_file & (IO_SIZE-1));
     length=IO_ROUND_UP(Count+diff_length)-diff_length;
     length= ((length <= cache->read_length) ?
              length + IO_ROUND_DN(cache->read_length - length) :
              length - IO_ROUND_UP(length - cache->read_length));
     if (cache->type != READ_FIFO &&
     (length > (cache->end_of_file - pos_in_file)))
       length= (size_t) (cache->end_of_file - pos_in_file);
     if (length == 0)
     {
       cache->error= (int) left_length;
       DBUG_RETURN(1);
     }
     if (lock_io_cache(cache, pos_in_file))
     {
       /* With a synchronized write/read cache we won't come here... */
       DBUG_ASSERT(!cshare->source_cache);
       /*
         ... unless the writer has gone before this thread entered the
         lock. Simulate EOF in this case. It can be distinguished by
         cache->file.
       */
       if (cache->file < 0)
         len= 0;
       else
       {
         /*
           Whenever a function which operates on IO_CACHE flushes/writes
           some part of the IO_CACHE to disk it will set the property
           "seek_not_done" to indicate this to other functions operating
           on the IO_CACHE.
         */
         if (cache->seek_not_done)
         {
           if (mysql_file_seek(cache->file, pos_in_file, MY_SEEK_SET, MYF(0))
               == MY_FILEPOS_ERROR)
           {
             cache->error= -1;
             unlock_io_cache(cache);
             DBUG_RETURN(1);
           }
         }
         len= mysql_file_read(cache->file, cache->buffer, length, cache->myflags);
       }
       DBUG_PRINT("io_cache_share", ("read %lu bytes", (ulong) len));
       cache->read_end=    cache->buffer + (len == (size_t) -1 ? 0 : len);
       cache->error=       (len == length ? 0 : (int) len);
       cache->pos_in_file= pos_in_file;
       /* Copy important values to the share. */
       cshare->error=       cache->error;
       cshare->read_end=    cache->read_end;
       cshare->pos_in_file= pos_in_file;
       /* Mark all threads as running and wake them. */
       unlock_io_cache(cache);
     }
     else
     {
       /*
         With a synchronized write/read cache readers always come here.
         Copy important values from the share.
       */
       cache->error=       cshare->error;
       cache->read_end=    cshare->read_end;
       cache->pos_in_file= cshare->pos_in_file;
       len= ((cache->error == -1) ? (size_t) -1 :
             (size_t) (cache->read_end - cache->buffer));
     }
     cache->read_pos=      cache->buffer;
     cache->seek_not_done= 0;
     if (len == 0 || len == (size_t) -1)
     {
       DBUG_PRINT("io_cache_share", ("reader error. len %lu  left %lu",
                                     (ulong) len, (ulong) left_length));
       cache->error= (int) left_length;
       DBUG_RETURN(1);
     }
     cnt= (len > Count) ? Count : len;
     memcpy(Buffer, cache->read_pos, cnt);
     Count -= cnt;
     Buffer+= cnt;
     left_length+= cnt;
     cache->read_pos+= cnt;
   }
   DBUG_RETURN(0);
 }
References st_io_cache::buffer, Acore::Count(), DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, st_io_cache::end_of_file, st_io_cache_share::error, st_io_cache::error, st_io_cache::file, IO_ROUND_DN, IO_ROUND_UP, IO_SIZE, G3D::length(), lock_io_cache(), memcpy, MY_FILEPOS_ERROR, MY_SEEK_SET, MYF, st_io_cache::myflags, mysql_file_read, mysql_file_seek, st_io_cache_share::pos_in_file, st_io_cache::pos_in_file, st_io_cache_share::read_end, st_io_cache::read_end, READ_FIFO, st_io_cache::read_length, st_io_cache::read_pos, st_io_cache::seek_not_done, st_io_cache::share, st_io_cache_share::source_cache, st_io_cache::type, and unlock_io_cache().
Referenced by init_functions(), and init_io_cache_share().
_my_b_seq_read()
int _my_b_seq_read (register IO_CACHE * info, uchar * Buffer, size_t Count)
Definition at line 1166 of file mf_iocache.c.
 {
   size_t length, diff_length, left_length, save_count, max_length;
   my_off_t pos_in_file;
   save_count=Count;
   /* first, read the regular buffer */
   if ((left_length=(size_t) (info->read_end-info->read_pos)))
   {
     DBUG_ASSERT(Count > left_length);   /* User is not using my_b_read() */
     memcpy(Buffer,info->read_pos, left_length);
     Buffer+=left_length;
     Count-=left_length;
   }
   lock_append_buffer(info);
   /* pos_in_file always point on where info->buffer was read */
   if ((pos_in_file=info->pos_in_file +
        (size_t) (info->read_end - info->buffer)) >= info->end_of_file)
     goto read_append_buffer;
   /*
     With read-append cache we must always do a seek before we read,
     because the write could have moved the file pointer astray
   */
   if (mysql_file_seek(info->file, pos_in_file, MY_SEEK_SET, MYF(0)) == MY_FILEPOS_ERROR)
   {
    info->error= -1;
    unlock_append_buffer(info);
    return (1);
   }
   info->seek_not_done=0;
   diff_length= (size_t) (pos_in_file & (IO_SIZE-1));
   /* now the second stage begins - read from file descriptor */
   if (Count >= (size_t) (IO_SIZE+(IO_SIZE-diff_length)))
   {
     /* Fill first intern buffer */
     size_t read_length;
     length=(Count & (size_t) ~(IO_SIZE-1))-diff_length;
     if ((read_length= mysql_file_read(info->file,Buffer, length,
                                       info->myflags)) == (size_t) -1)
     {
       info->error= -1;
       unlock_append_buffer(info);
       return 1;
     }
     Count-=read_length;
     Buffer+=read_length;
     pos_in_file+=read_length;
     if (read_length != length)
     {
       /*
     We only got part of data;  Read the rest of the data from the
     write buffer
       */
       goto read_append_buffer;
     }
     left_length+=length;
     diff_length=0;
   }
   max_length= info->read_length-diff_length;
   if (max_length > (info->end_of_file - pos_in_file))
     max_length= (size_t) (info->end_of_file - pos_in_file);
   if (!max_length)
   {
     if (Count)
       goto read_append_buffer;
     length=0;               /* Didn't read any more chars */
   }
   else
   {
     length= mysql_file_read(info->file,info->buffer, max_length, info->myflags);
     if (length == (size_t) -1)
     {
       info->error= -1;
       unlock_append_buffer(info);
       return 1;
     }
     if (length < Count)
     {
       memcpy(Buffer, info->buffer, length);
       Count -= length;
       Buffer += length;
       /*
      added the line below to make
      DBUG_ASSERT(pos_in_file==info->end_of_file) pass.
      otherwise this does not appear to be needed
       */
       pos_in_file += length;
       goto read_append_buffer;
     }
   }
   unlock_append_buffer(info);
   info->read_pos=info->buffer+Count;
   info->read_end=info->buffer+length;
   info->pos_in_file=pos_in_file;
   memcpy(Buffer,info->buffer,(size_t) Count);
   return 0;
 read_append_buffer:
   /*
      Read data from the current write buffer.
      Count should never be == 0 here (The code will work even if count is 0)
   */
   {
     /* First copy the data to Count */
     size_t len_in_buff = (size_t) (info->write_pos - info->append_read_pos);
     size_t copy_len;
     size_t transfer_len;
     DBUG_ASSERT(info->append_read_pos <= info->write_pos);
     /*
       TODO: figure out if the assert below is needed or correct.
     */
     DBUG_ASSERT(pos_in_file == info->end_of_file);
     copy_len=min(Count, len_in_buff);
     memcpy(Buffer, info->append_read_pos, copy_len);
     info->append_read_pos += copy_len;
     Count -= copy_len;
     if (Count)
       info->error = save_count - Count;
     /* Fill read buffer with data from write buffer */
     memcpy(info->buffer, info->append_read_pos,
        (size_t) (transfer_len=len_in_buff - copy_len));
     info->read_pos= info->buffer;
     info->read_end= info->buffer+transfer_len;
     info->append_read_pos=info->write_pos;
     info->pos_in_file=pos_in_file+copy_len;
     info->end_of_file+=len_in_buff;
   }
   unlock_append_buffer(info);
   return Count ? 1 : 0;
 }
References st_io_cache::append_read_pos, st_io_cache::buffer, Acore::Count(), DBUG_ASSERT, st_io_cache::end_of_file, st_io_cache::error, st_io_cache::file, IO_SIZE, G3D::length(), lock_append_buffer, memcpy, min, MY_FILEPOS_ERROR, MY_SEEK_SET, MYF, st_io_cache::myflags, mysql_file_read, mysql_file_seek, st_io_cache::pos_in_file, st_io_cache::read_end, st_io_cache::read_length, st_io_cache::read_pos, st_io_cache::seek_not_done, unlock_append_buffer, and st_io_cache::write_pos.
Referenced by init_functions().
_my_b_write()
int _my_b_write (register IO_CACHE * info, const uchar * Buffer, size_t Count)
Definition at line 1528 of file mf_iocache.c.
 {
   size_t rest_length,length;
   if (info->pos_in_file+info->buffer_length > info->end_of_file)
   {
     my_errno=errno=EFBIG;
     return info->error = -1;
   }
   rest_length= (size_t) (info->write_end - info->write_pos);
   memcpy(info->write_pos,Buffer,(size_t) rest_length);
   Buffer+=rest_length;
   Count-=rest_length;
   info->write_pos+=rest_length;
   if (my_b_flush_io_cache(info,1))
     return 1;
   if (Count >= IO_SIZE)
   {                 /* Fill first intern buffer */
     length=Count & (size_t) ~(IO_SIZE-1);
     if (info->seek_not_done)
     {
       /*
         Whenever a function which operates on IO_CACHE flushes/writes
         some part of the IO_CACHE to disk it will set the property
         "seek_not_done" to indicate this to other functions operating
         on the IO_CACHE.
       */
       if (mysql_file_seek(info->file, info->pos_in_file, MY_SEEK_SET, MYF(0)))
       {
         info->error= -1;
         return (1);
       }
       info->seek_not_done=0;
     }
     if (mysql_file_write(info->file, Buffer, length, info->myflags | MY_NABP))
       return info->error= -1;
     /*
       In case of a shared I/O cache with a writer we normally do direct
       write cache to read cache copy. Simulate this here by direct
       caller buffer to read cache copy. Do it after the write so that
       the cache readers actions on the flushed part can go in parallel
       with the write of the extra stuff. copy_to_read_buffer()
       synchronizes writer and readers so that after this call the
       readers can act on the extra stuff while the writer can go ahead
       and prepare the next output. copy_to_read_buffer() relies on
       info->pos_in_file.
     */
     if (info->share)
       copy_to_read_buffer(info, Buffer, length);
     Count-=length;
     Buffer+=length;
     info->pos_in_file+=length;
   }
   memcpy(info->write_pos,Buffer,(size_t) Count);
   info->write_pos+=Count;
   return 0;
 }
References st_io_cache::buffer_length, copy_to_read_buffer(), Acore::Count(), st_io_cache::end_of_file, errno, st_io_cache::error, st_io_cache::file, IO_SIZE, G3D::length(), memcpy, my_b_flush_io_cache(), my_errno, MY_NABP, MY_SEEK_SET, MYF, st_io_cache::myflags, mysql_file_seek, mysql_file_write, st_io_cache::pos_in_file, st_io_cache::seek_not_done, st_io_cache::share, st_io_cache::write_end, and st_io_cache::write_pos.
Referenced by init_functions(), and my_block_write().
copy_to_read_buffer()
static void copy_to_read_buffer (IO_CACHE * write_cache, const uchar * write_buffer, size_t write_length) static
Definition at line 1119 of file mf_iocache.c.
 {
   IO_CACHE_SHARE *cshare= write_cache->share;
   DBUG_ASSERT(cshare->source_cache == write_cache);
   /*
     write_length is usually less or equal to buffer_length.
     It can be bigger if _my_b_write() is called with a big length.
   */
   while (write_length)
   {
     size_t copy_length= min(write_length, write_cache->buffer_length);
     int  __attribute__((unused)) rc;
     rc= lock_io_cache(write_cache, write_cache->pos_in_file);
     /* The writing thread does always have the lock when it awakes. */
     DBUG_ASSERT(rc);
     memcpy(cshare->buffer, write_buffer, copy_length);
     cshare->error=       0;
     cshare->read_end=    cshare->buffer + copy_length;
     cshare->pos_in_file= write_cache->pos_in_file;
     /* Mark all threads as running and wake them. */
     unlock_io_cache(write_cache);
     write_buffer+= copy_length;
     write_length-= copy_length;
   }
 }
References __attribute__, st_io_cache_share::buffer, st_io_cache::buffer_length, DBUG_ASSERT, st_io_cache_share::error, lock_io_cache(), memcpy, min, st_io_cache_share::pos_in_file, st_io_cache::pos_in_file, st_io_cache_share::read_end, st_io_cache::share, st_io_cache_share::source_cache, unlock_io_cache(), and detail::write_buffer().
Referenced by _my_b_write(), and my_b_flush_io_cache().
end_io_cache()
int end_io_cache (IO_CACHE * info)
Definition at line 1824 of file mf_iocache.c.
 {
   int error=0;
   IO_CACHE_CALLBACK pre_close;
   DBUG_ENTER("end_io_cache");
   DBUG_PRINT("enter",("cache: 0x%lx", (ulong) info));
   /*
     Every thread must call remove_io_thread(). The last one destroys
     the share elements.
   */
   DBUG_ASSERT(!info->share || !info->share->total_threads);
   if ((pre_close=info->pre_close))
   {
     (*pre_close)(info);
     info->pre_close= 0;
   }
   if (info->alloced_buffer)
   {
     info->alloced_buffer=0;
     if (info->file != -1)           /* File doesn't exist */
       error= my_b_flush_io_cache(info,1);
     my_free(info->buffer);
     info->buffer=info->read_pos=(uchar*) 0;
   }
   if (info->type == SEQ_READ_APPEND)
   {
     /* Destroy allocated mutex */
     info->type= TYPE_NOT_SET;
     mysql_mutex_destroy(&info->append_buffer_lock);
   }
   DBUG_RETURN(error);
 } /* end_io_cache */
References st_io_cache::alloced_buffer, st_io_cache::append_buffer_lock, st_io_cache::buffer, DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, error(), st_io_cache::file, my_b_flush_io_cache(), my_free(), mysql_mutex_destroy, st_io_cache::pre_close, st_io_cache::read_pos, SEQ_READ_APPEND, st_io_cache::share, st_io_cache_share::total_threads, st_io_cache::type, and TYPE_NOT_SET.
Referenced by close_cached_file().
init_functions()
static void init_functions (IO_CACHE * info) static
Definition at line 96 of file mf_iocache.c.
 {
   enum cache_type type= info->type;
   switch (type) {
   case READ_NET:
     /*
       Must be initialized by the caller. The problem is that
       _my_b_net_read has to be defined in sql directory because of
       the dependency on THD, and therefore cannot be visible to
       programs that link against mysys but know nothing about THD, such
       as myisamchk
     */
     break;
   case SEQ_READ_APPEND:
     info->read_function = _my_b_seq_read;
     info->write_function = 0;           /* Force a core if used */
     break;
   default:
     info->read_function = info->share ? _my_b_read_r : _my_b_read;
     info->write_function = _my_b_write;
   }
   setup_io_cache(info);
 }
References _my_b_read(), _my_b_read_r(), _my_b_seq_read(), _my_b_write(), st_io_cache::read_function, READ_NET, SEQ_READ_APPEND, setup_io_cache(), st_io_cache::share, st_io_cache::type, and st_io_cache::write_function.
Referenced by init_io_cache(), and reinit_io_cache().
init_io_cache()
int init_io_cache (IO_CACHE * info, File file, size_t cachesize, enum cache_type type, my_off_t seek_offset, pbool use_async_io, myf cache_myflags)
Definition at line 145 of file mf_iocache.c.
 {
   size_t min_cache;
   my_off_t pos;
   my_off_t end_of_file= ~(my_off_t) 0;
   DBUG_ENTER("init_io_cache");
   DBUG_PRINT("enter",("cache: 0x%lx  type: %d  pos: %ld",
               (ulong) info, (int) type, (ulong) seek_offset));
   info->file= file;
   info->type= TYPE_NOT_SET;     /* Don't set it until mutex are created */
   info->pos_in_file= seek_offset;
   info->pre_close = info->pre_read = info->post_read = 0;
   info->arg = 0;
   info->alloced_buffer = 0;
   info->buffer=0;
   info->seek_not_done= 0;
   if (file >= 0)
   {
     pos= mysql_file_tell(file, MYF(0));
     if ((pos == (my_off_t) -1) && (my_errno == ESPIPE))
     {
       /*
          This kind of object doesn't support seek() or tell(). Don't set a
          flag that will make us again try to seek() later and fail.
       */
       info->seek_not_done= 0;
       /*
         Additionally, if we're supposed to start somewhere other than the
         the beginning of whatever this file is, then somebody made a bad
         assumption.
       */
       DBUG_ASSERT(seek_offset == 0);
     }
     else
       info->seek_not_done= test(seek_offset != pos);
   }
   info->disk_writes= 0;
   info->share=0;
   if (!cachesize && !(cachesize= my_default_record_cache_size))
     DBUG_RETURN(1);             /* No cache requested */
   min_cache=use_async_io ? IO_SIZE*4 : IO_SIZE*2;
   if (type == READ_CACHE || type == SEQ_READ_APPEND)
   {                     /* Assume file isn't growing */
     if (!(cache_myflags & MY_DONT_CHECK_FILESIZE))
     {
       /* Calculate end of file to avoid allocating oversized buffers */
       end_of_file= mysql_file_seek(file, 0L, MY_SEEK_END, MYF(0));
       /* Need to reset seek_not_done now that we just did a seek. */
       info->seek_not_done= end_of_file == seek_offset ? 0 : 1;
       if (end_of_file < seek_offset)
     end_of_file=seek_offset;
       /* Trim cache size if the file is very small */
       if ((my_off_t) cachesize > end_of_file-seek_offset+IO_SIZE*2-1)
       {
     cachesize= (size_t) (end_of_file-seek_offset)+IO_SIZE*2-1;
     use_async_io=0;             /* No need to use async */
       }
     }
   }
   cache_myflags &= ~MY_DONT_CHECK_FILESIZE;
   if (type != READ_NET && type != WRITE_NET)
   {
     /* Retry allocating memory in smaller blocks until we get one */
     cachesize= ((cachesize + min_cache-1) & ~(min_cache-1));
     for (;;)
     {
       size_t buffer_block;
       /*
         Unset MY_WAIT_IF_FULL bit if it is set, to prevent conflict with
         MY_ZEROFILL.
       */
       myf flags= (myf) (cache_myflags & ~(MY_WME | MY_WAIT_IF_FULL));
       if (cachesize < min_cache)
     cachesize = min_cache;
       buffer_block= cachesize;
       if (type == SEQ_READ_APPEND)
     buffer_block *= 2;
       if (cachesize == min_cache)
         flags|= (myf) MY_WME;
       if ((info->buffer= (uchar*) my_malloc(buffer_block, flags)) != 0)
       {
     info->write_buffer=info->buffer;
     if (type == SEQ_READ_APPEND)
       info->write_buffer = info->buffer + cachesize;
     info->alloced_buffer=1;
     break;                  /* Enough memory found */
       }
       if (cachesize == min_cache)
     DBUG_RETURN(2);             /* Can't alloc cache */
       /* Try with less memory */
       cachesize= (cachesize*3/4 & ~(min_cache-1));
     }
   }
   DBUG_PRINT("info",("init_io_cache: cachesize = %lu", (ulong) cachesize));
   info->read_length=info->buffer_length=cachesize;
   info->myflags=cache_myflags & ~(MY_NABP | MY_FNABP);
   info->request_pos= info->read_pos= info->write_pos = info->buffer;
   if (type == SEQ_READ_APPEND)
   {
     info->append_read_pos = info->write_pos = info->write_buffer;
     info->write_end = info->write_buffer + info->buffer_length;
     mysql_mutex_init(key_IO_CACHE_append_buffer_lock,
                      &info->append_buffer_lock, MY_MUTEX_INIT_FAST);
   }
 #if defined(SAFE_MUTEX)
   else
   {
     /* Clear mutex so that safe_mutex will notice that it's not initialized */
     bzero((char*) &info->append_buffer_lock, sizeof(info));
   }
 #endif
   if (type == WRITE_CACHE)
     info->write_end=
       info->buffer+info->buffer_length- (seek_offset & (IO_SIZE-1));
   else
     info->read_end=info->buffer;        /* Nothing in cache */
   /* End_of_file may be changed by user later */
   info->end_of_file= end_of_file;
   info->error=0;
   info->type= type;
   init_functions(info);
 #ifdef HAVE_AIOWAIT
   if (use_async_io && ! my_disable_async_io)
   {
     DBUG_PRINT("info",("Using async io"));
     info->read_length/=2;
     info->read_function=_my_b_async_read;
   }
   info->inited=info->aio_result.pending=0;
 #endif
   DBUG_RETURN(0);
 }                       /* init_io_cache */
References _my_b_async_read(), st_io_cache::alloced_buffer, st_io_cache::append_buffer_lock, st_io_cache::append_read_pos, st_io_cache::arg, st_io_cache::buffer, st_io_cache::buffer_length, bzero, DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, st_io_cache::disk_writes, st_io_cache::end_of_file, st_io_cache::error, mpq::file, st_io_cache::file, init_functions(), IO_SIZE, my_default_record_cache_size, my_disable_async_io, MY_DONT_CHECK_FILESIZE, my_errno, MY_FNABP, my_malloc(), MY_MUTEX_INIT_FAST, MY_NABP, MY_SEEK_END, MY_WAIT_IF_FULL, MY_WME, MYF, st_io_cache::myflags, mysql_file_seek, mysql_file_tell, mysql_mutex_init, pos(), st_io_cache::pos_in_file, st_io_cache::post_read, st_io_cache::pre_close, st_io_cache::pre_read, READ_CACHE, st_io_cache::read_end, st_io_cache::read_function, st_io_cache::read_length, READ_NET, st_io_cache::read_pos, st_io_cache::request_pos, st_io_cache::seek_not_done, SEQ_READ_APPEND, st_io_cache::share, test, st_io_cache::type, TYPE_NOT_SET, st_io_cache::write_buffer, WRITE_CACHE, st_io_cache::write_end, WRITE_NET, and st_io_cache::write_pos.
Referenced by open_cached_file().
init_io_cache_share()
void init_io_cache_share (IO_CACHE * read_cache, IO_CACHE_SHARE * cshare, IO_CACHE * write_cache, uint num_threads)
Definition at line 659 of file mf_iocache.c.
 {
   DBUG_ENTER("init_io_cache_share");
   DBUG_PRINT("io_cache_share", ("read_cache: 0x%lx  share: 0x%lx  "
                                 "write_cache: 0x%lx  threads: %u",
                                 (long) read_cache, (long) cshare,
                                 (long) write_cache, num_threads));
   DBUG_ASSERT(num_threads > 1);
   DBUG_ASSERT(read_cache->type == READ_CACHE);
   DBUG_ASSERT(!write_cache || (write_cache->type == WRITE_CACHE));
   mysql_mutex_init(key_IO_CACHE_SHARE_mutex,
                    &cshare->mutex, MY_MUTEX_INIT_FAST);
   mysql_cond_init(key_IO_CACHE_SHARE_cond, &cshare->cond, 0);
   mysql_cond_init(key_IO_CACHE_SHARE_cond_writer, &cshare->cond_writer, 0);
   cshare->running_threads= num_threads;
   cshare->total_threads=   num_threads;
   cshare->error=           0;    /* Initialize. */
   cshare->buffer=          read_cache->buffer;
   cshare->read_end=        NULL; /* See function comment of lock_io_cache(). */
   cshare->pos_in_file=     0;    /* See function comment of lock_io_cache(). */
   cshare->source_cache=    write_cache; /* Can be NULL. */
   read_cache->share=         cshare;
   read_cache->read_function= _my_b_read_r;
   read_cache->current_pos=   NULL;
   read_cache->current_end=   NULL;
   if (write_cache)
     write_cache->share= cshare;
   DBUG_VOID_RETURN;
 }
References _my_b_read_r(), st_io_cache_share::buffer, st_io_cache::buffer, st_io_cache_share::cond, st_io_cache_share::cond_writer, st_io_cache::current_end, st_io_cache::current_pos, DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, st_io_cache_share::error, st_io_cache_share::mutex, MY_MUTEX_INIT_FAST, mysql_cond_init, mysql_mutex_init, NULL, st_io_cache_share::pos_in_file, READ_CACHE, st_io_cache_share::read_end, st_io_cache::read_function, st_io_cache_share::running_threads, st_io_cache::share, st_io_cache_share::source_cache, st_io_cache_share::total_threads, st_io_cache::type, and WRITE_CACHE.
lock_io_cache()
static int lock_io_cache (IO_CACHE * cache, my_off_t pos) static
Definition at line 795 of file mf_iocache.c.
 {
   IO_CACHE_SHARE *cshare= cache->share;
   DBUG_ENTER("lock_io_cache");
   /* Enter the lock. */
   mysql_mutex_lock(&cshare->mutex);
   cshare->running_threads--;
   DBUG_PRINT("io_cache_share", ("%s: 0x%lx  pos: %lu  running: %u",
                                 (cache == cshare->source_cache) ?
                                 "writer" : "reader", (long) cache, (ulong) pos,
                                 cshare->running_threads));
   if (cshare->source_cache)
   {
     /* A write cache is synchronized to the read caches. */
     if (cache == cshare->source_cache)
     {
       /* The writer waits until all readers are here. */
       while (cshare->running_threads)
       {
         DBUG_PRINT("io_cache_share", ("writer waits in lock"));
         mysql_cond_wait(&cshare->cond_writer, &cshare->mutex);
       }
       DBUG_PRINT("io_cache_share", ("writer awoke, going to copy"));
       /* Stay locked. Leave the lock later by unlock_io_cache(). */
       DBUG_RETURN(1);
     }
     /* The last thread wakes the writer. */
     if (!cshare->running_threads)
     {
       DBUG_PRINT("io_cache_share", ("waking writer"));
       mysql_cond_signal(&cshare->cond_writer);
     }
     /*
       Readers wait until the data is copied from the writer. Another
       reason to stop waiting is the removal of the write thread. If this
       happens, we leave the lock with old data in the buffer.
     */
     while ((!cshare->read_end || (cshare->pos_in_file < pos)) &&
            cshare->source_cache)
     {
       DBUG_PRINT("io_cache_share", ("reader waits in lock"));
       mysql_cond_wait(&cshare->cond, &cshare->mutex);
     }
     /*
       If the writer was removed from the share while this thread was
       asleep, we need to simulate an EOF condition. The writer cannot
       reset the share variables as they might still be in use by readers
       of the last block. When we awake here then because the last
       joining thread signalled us. If the writer is not the last, it
       will not signal. So it is safe to clear the buffer here.
     */
     if (!cshare->read_end || (cshare->pos_in_file < pos))
     {
       DBUG_PRINT("io_cache_share", ("reader found writer removed. EOF"));
       cshare->read_end= cshare->buffer; /* Empty buffer. */
       cshare->error= 0; /* EOF is not an error. */
     }
   }
   else
   {
     /*
       There are read caches only. The last thread arriving in
       lock_io_cache() continues with a locked cache and reads the block.
     */
     if (!cshare->running_threads)
     {
       DBUG_PRINT("io_cache_share", ("last thread joined, going to read"));
       /* Stay locked. Leave the lock later by unlock_io_cache(). */
       DBUG_RETURN(1);
     }
     /*
       All other threads wait until the requested block is read by the
       last thread arriving. Another reason to stop waiting is the
       removal of a thread. If this leads to all threads being in the
       lock, we have to continue also. The first of the awaken threads
       will then do the read.
     */
     while ((!cshare->read_end || (cshare->pos_in_file < pos)) &&
            cshare->running_threads)
     {
       DBUG_PRINT("io_cache_share", ("reader waits in lock"));
       mysql_cond_wait(&cshare->cond, &cshare->mutex);
     }
     /* If the block is not yet read, continue with a locked cache and read. */
     if (!cshare->read_end || (cshare->pos_in_file < pos))
     {
       DBUG_PRINT("io_cache_share", ("reader awoke, going to read"));
       /* Stay locked. Leave the lock later by unlock_io_cache(). */
       DBUG_RETURN(1);
     }
     /* Another thread did read the block already. */
   }
   DBUG_PRINT("io_cache_share", ("reader awoke, going to process %u bytes",
                                 (uint) (cshare->read_end ? (size_t)
                                         (cshare->read_end - cshare->buffer) :
                                         0)));
   /*
     Leave the lock. Do not call unlock_io_cache() later. The thread that
     filled the buffer did this and marked all threads as running.
   */
   mysql_mutex_unlock(&cshare->mutex);
   DBUG_RETURN(0);
 }
References st_io_cache_share::buffer, st_io_cache_share::cond, st_io_cache_share::cond_writer, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, st_io_cache_share::error, st_io_cache_share::mutex, mysql_cond_signal, mysql_cond_wait, mysql_mutex_lock, mysql_mutex_unlock, pos(), st_io_cache_share::pos_in_file, st_io_cache_share::read_end, st_io_cache_share::running_threads, st_io_cache::share, and st_io_cache_share::source_cache.
Referenced by _my_b_read_r(), and copy_to_read_buffer().
my_b_append()
int my_b_append (register IO_CACHE * info, const uchar * Buffer, size_t Count)
Definition at line 1597 of file mf_iocache.c.
 {
   size_t rest_length,length;
   /*
     Assert that we cannot come here with a shared cache. If we do one
     day, we might need to add a call to copy_to_read_buffer().
   */
   DBUG_ASSERT(!info->share);
   lock_append_buffer(info);
   rest_length= (size_t) (info->write_end - info->write_pos);
   if (Count <= rest_length)
     goto end;
   memcpy(info->write_pos, Buffer, rest_length);
   Buffer+=rest_length;
   Count-=rest_length;
   info->write_pos+=rest_length;
   if (my_b_flush_io_cache(info,0))
   {
     unlock_append_buffer(info);
     return 1;
   }
   if (Count >= IO_SIZE)
   {                 /* Fill first intern buffer */
     length=Count & (size_t) ~(IO_SIZE-1);
     if (mysql_file_write(info->file,Buffer, length, info->myflags | MY_NABP))
     {
       unlock_append_buffer(info);
       return info->error= -1;
     }
     Count-=length;
     Buffer+=length;
     info->end_of_file+=length;
   }
 end:
   memcpy(info->write_pos,Buffer,(size_t) Count);
   info->write_pos+=Count;
   unlock_append_buffer(info);
   return 0;
 }
References Acore::Count(), DBUG_ASSERT, st_io_cache::end_of_file, st_io_cache::error, st_io_cache::file, IO_SIZE, G3D::length(), lock_append_buffer, memcpy, my_b_flush_io_cache(), MY_NABP, st_io_cache::myflags, mysql_file_write, st_io_cache::share, unlock_append_buffer, st_io_cache::write_end, and st_io_cache::write_pos.
Referenced by my_b_safe_write().
my_b_flush_io_cache()
int my_b_flush_io_cache (IO_CACHE * info, int need_append_buffer_lock __attribute__(unused))
Definition at line 1722 of file mf_iocache.c.
 {
   size_t length;
   my_off_t pos_in_file;
   my_bool append_cache= (info->type == SEQ_READ_APPEND);
   DBUG_ENTER("my_b_flush_io_cache");
   DBUG_PRINT("enter", ("cache: 0x%lx", (long) info));
   if (!append_cache)
     need_append_buffer_lock= 0;
   if (info->type == WRITE_CACHE || append_cache)
   {
     if (info->file == -1)
     {
       if (real_open_cached_file(info))
     DBUG_RETURN((info->error= -1));
     }
     LOCK_APPEND_BUFFER;
     if ((length=(size_t) (info->write_pos - info->write_buffer)))
     {
       /*
         In case of a shared I/O cache with a writer we do direct write
         cache to read cache copy. Do it before the write here so that
         the readers can work in parallel with the write.
         copy_to_read_buffer() relies on info->pos_in_file.
       */
       if (info->share)
         copy_to_read_buffer(info, info->write_buffer, length);
       pos_in_file=info->pos_in_file;
       /*
     If we have append cache, we always open the file with
     O_APPEND which moves the pos to EOF automatically on every write
       */
       if (!append_cache && info->seek_not_done)
       {                 /* File touched, do seek */
     if (mysql_file_seek(info->file, pos_in_file, MY_SEEK_SET, MYF(0)) ==
         MY_FILEPOS_ERROR)
     {
       UNLOCK_APPEND_BUFFER;
       DBUG_RETURN((info->error= -1));
     }
     if (!append_cache)
       info->seek_not_done=0;
       }
       if (!append_cache)
     info->pos_in_file+=length;
       info->write_end= (info->write_buffer+info->buffer_length-
             ((pos_in_file+length) & (IO_SIZE-1)));
       if (mysql_file_write(info->file,info->write_buffer,length,
            info->myflags | MY_NABP))
     info->error= -1;
       else
     info->error= 0;
       if (!append_cache)
       {
         set_if_bigger(info->end_of_file,(pos_in_file+length));
       }
       else
       {
     info->end_of_file+=(info->write_pos-info->append_read_pos);
     DBUG_ASSERT(info->end_of_file == mysql_file_tell(info->file, MYF(0)));
       }
       info->append_read_pos=info->write_pos=info->write_buffer;
       ++info->disk_writes;
       UNLOCK_APPEND_BUFFER;
       DBUG_RETURN(info->error);
     }
   }
 #ifdef HAVE_AIOWAIT
   else if (info->type != READ_NET)
   {
     my_aiowait(&info->aio_result);      /* Wait for outstanding req */
     info->inited=0;
   }
 #endif
   UNLOCK_APPEND_BUFFER;
   DBUG_RETURN(0);
 }
References copy_to_read_buffer(), DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, if(), IO_SIZE, G3D::length(), LOCK_APPEND_BUFFER, MY_FILEPOS_ERROR, MY_NABP, MY_SEEK_SET, MYF, mysql_file_seek, mysql_file_tell, mysql_file_write, READ_NET, real_open_cached_file(), SEQ_READ_APPEND, set_if_bigger, st_io_cache::type, UNLOCK_APPEND_BUFFER, and WRITE_CACHE.
Referenced by _my_b_write(), end_io_cache(), my_b_append(), and reinit_io_cache().
my_b_safe_write()
int my_b_safe_write (IO_CACHE * info, const uchar * Buffer, size_t Count)
Definition at line 1641 of file mf_iocache.c.
 {
   /*
     Sasha: We are not writing this with the ? operator to avoid hitting
     a possible compiler bug. At least gcc 2.95 cannot deal with
     several layers of ternary operators that evaluated comma(,) operator
     expressions inside - I do have a test case if somebody wants it
   */
   if (info->type == SEQ_READ_APPEND)
     return my_b_append(info, Buffer, Count);
   return my_b_write(info, Buffer, Count);
 }
References Acore::Count(), my_b_append(), my_b_write, SEQ_READ_APPEND, and st_io_cache::type.
my_block_write()
int my_block_write (register IO_CACHE * info, const uchar * Buffer, size_t Count, my_off_t pos)
Definition at line 1661 of file mf_iocache.c.
 {
   size_t length;
   int error=0;
   /*
     Assert that we cannot come here with a shared cache. If we do one
     day, we might need to add a call to copy_to_read_buffer().
   */
   DBUG_ASSERT(!info->share);
   if (pos < info->pos_in_file)
   {
     /* Of no overlap, write everything without buffering */
     if (pos + Count <= info->pos_in_file)
       return mysql_file_pwrite(info->file, Buffer, Count, pos,
                        info->myflags | MY_NABP);
     /* Write the part of the block that is before buffer */
     length= (uint) (info->pos_in_file - pos);
     if (mysql_file_pwrite(info->file, Buffer, length, pos, info->myflags | MY_NABP))
       info->error= error= -1;
     Buffer+=length;
     pos+=  length;
     Count-= length;
 #ifndef HAVE_PREAD
     info->seek_not_done=1;
 #endif
   }
   /* Check if we want to write inside the used part of the buffer.*/
   length= (size_t) (info->write_end - info->buffer);
   if (pos < info->pos_in_file + length)
   {
     size_t offset= (size_t) (pos - info->pos_in_file);
     length-=offset;
     if (length > Count)
       length=Count;
     memcpy(info->buffer+offset, Buffer, length);
     Buffer+=length;
     Count-= length;
     /* Fix length of buffer if the new data was larger */
     if (info->buffer+length > info->write_pos)
       info->write_pos=info->buffer+length;
     if (!Count)
       return (error);
   }
   /* Write at the end of the current buffer; This is the normal case */
   if (_my_b_write(info, Buffer, Count))
     error= -1;
   return error;
 }
References _my_b_write(), st_io_cache::buffer, Acore::Count(), DBUG_ASSERT, endif(), st_io_cache::error, error(), st_io_cache::file, G3D::length(), memcpy, MY_NABP, st_io_cache::myflags, mysql_file_pwrite, pos(), st_io_cache::pos_in_file, st_io_cache::seek_not_done, st_io_cache::share, st_io_cache::write_end, and st_io_cache::write_pos.
reinit_io_cache()
my_bool reinit_io_cache (IO_CACHE * info, enum cache_type type, my_off_t seek_offset, pbool use_async_io __attribute__(unused), pbool clear_cache)
Definition at line 324 of file mf_iocache.c.
 {
   DBUG_ENTER("reinit_io_cache");
   DBUG_PRINT("enter",("cache: 0x%lx type: %d  seek_offset: %lu  clear_cache: %d",
               (ulong) info, type, (ulong) seek_offset,
               (int) clear_cache));
   /* One can't do reinit with the following types */
   DBUG_ASSERT(type != READ_NET && info->type != READ_NET &&
           type != WRITE_NET && info->type != WRITE_NET &&
           type != SEQ_READ_APPEND && info->type != SEQ_READ_APPEND);
   /* If the whole file is in memory, avoid flushing to disk */
   if (! clear_cache &&
       seek_offset >= info->pos_in_file &&
       seek_offset <= my_b_tell(info))
   {
     /* Reuse current buffer without flushing it to disk */
     uchar *pos;
     if (info->type == WRITE_CACHE && type == READ_CACHE)
     {
       info->read_end=info->write_pos;
       info->end_of_file=my_b_tell(info);
       /*
         Trigger a new seek only if we have a valid
         file handle.
       */
       info->seek_not_done= (info->file != -1);
     }
     else if (type == WRITE_CACHE)
     {
       if (info->type == READ_CACHE)
       {
     info->write_end=info->write_buffer+info->buffer_length;
     info->seek_not_done=1;
       }
       info->end_of_file = ~(my_off_t) 0;
     }
     pos=info->request_pos+(seek_offset-info->pos_in_file);
     if (type == WRITE_CACHE)
       info->write_pos=pos;
     else
       info->read_pos= pos;
 #ifdef HAVE_AIOWAIT
     my_aiowait(&info->aio_result);      /* Wait for outstanding req */
 #endif
   }
   else
   {
     /*
       If we change from WRITE_CACHE to READ_CACHE, assume that everything
       after the current positions should be ignored
     */
     if (info->type == WRITE_CACHE && type == READ_CACHE)
       info->end_of_file=my_b_tell(info);
     /* flush cache if we want to reuse it */
     if (!clear_cache && my_b_flush_io_cache(info,1))
       DBUG_RETURN(1);
     info->pos_in_file=seek_offset;
     /* Better to do always do a seek */
     info->seek_not_done=1;
     info->request_pos=info->read_pos=info->write_pos=info->buffer;
     if (type == READ_CACHE)
     {
       info->read_end=info->buffer;      /* Nothing in cache */
     }
     else
     {
       info->write_end=(info->buffer + info->buffer_length -
                (seek_offset & (IO_SIZE-1)));
       info->end_of_file= ~(my_off_t) 0;
     }
   }
   info->type=type;
   info->error=0;
   init_functions(info);
 #ifdef HAVE_AIOWAIT
   if (use_async_io && ! my_disable_async_io &&
       ((ulong) info->buffer_length <
        (ulong) (info->end_of_file - seek_offset)))
   {
     info->read_length=info->buffer_length/2;
     info->read_function=_my_b_async_read;
   }
   info->inited=0;
 #endif
   DBUG_RETURN(0);
 } /* reinit_io_cache */
References _my_b_async_read(), DBUG_ASSERT, DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, init_functions(), IO_SIZE, my_b_flush_io_cache(), my_b_tell, my_disable_async_io, pos(), READ_CACHE, READ_NET, SEQ_READ_APPEND, WRITE_CACHE, and WRITE_NET.
remove_io_thread()
void remove_io_thread (IO_CACHE * cache)
Definition at line 716 of file mf_iocache.c.
 {
   IO_CACHE_SHARE *cshare= cache->share;
   uint total;
   DBUG_ENTER("remove_io_thread");
   /* If the writer goes, it needs to flush the write cache. */
   if (cache == cshare->source_cache)
     flush_io_cache(cache);
   mysql_mutex_lock(&cshare->mutex);
   DBUG_PRINT("io_cache_share", ("%s: 0x%lx",
                                 (cache == cshare->source_cache) ?
                                 "writer" : "reader", (long) cache));
   /* Remove from share. */
   total= --cshare->total_threads;
   DBUG_PRINT("io_cache_share", ("remaining threads: %u", total));
   /* Detach from share. */
   cache->share= NULL;
   /* If the writer goes, let the readers know. */
   if (cache == cshare->source_cache)
   {
     DBUG_PRINT("io_cache_share", ("writer leaves"));
     cshare->source_cache= NULL;
   }
   /* If all threads are waiting for me to join the lock, wake them. */
   if (!--cshare->running_threads)
   {
     DBUG_PRINT("io_cache_share", ("the last running thread leaves, wake all"));
     mysql_cond_signal(&cshare->cond_writer);
     mysql_cond_broadcast(&cshare->cond);
   }
   mysql_mutex_unlock(&cshare->mutex);
   if (!total)
   {
     DBUG_PRINT("io_cache_share", ("last thread removed, destroy share"));
     mysql_cond_destroy (&cshare->cond_writer);
     mysql_cond_destroy (&cshare->cond);
     mysql_mutex_destroy(&cshare->mutex);
   }
   DBUG_VOID_RETURN;
 }
References st_io_cache_share::cond, st_io_cache_share::cond_writer, DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, flush_io_cache, st_io_cache_share::mutex, mysql_cond_broadcast, mysql_cond_destroy, mysql_cond_signal, mysql_mutex_destroy, mysql_mutex_lock, mysql_mutex_unlock, NULL, st_io_cache_share::running_threads, st_io_cache::share, st_io_cache_share::source_cache, and st_io_cache_share::total_threads.
setup_io_cache()
void setup_io_cache (IO_CACHE * info)
Definition at line 79 of file mf_iocache.c.
 {
   /* Ensure that my_b_tell() and my_b_bytes_in_cache works */
   if (info->type == WRITE_CACHE)
   {
     info->current_pos= &info->write_pos;
     info->current_end= &info->write_end;
   }
   else
   {
     info->current_pos= &info->read_pos;
     info->current_end= &info->read_end;
   }
 }
References st_io_cache::current_end, st_io_cache::current_pos, st_io_cache::read_end, st_io_cache::read_pos, st_io_cache::type, WRITE_CACHE, st_io_cache::write_end, and st_io_cache::write_pos.
Referenced by init_functions().
unlock_io_cache()
static void unlock_io_cache (IO_CACHE * cache) static
Definition at line 938 of file mf_iocache.c.
 {
   IO_CACHE_SHARE *cshare= cache->share;
   DBUG_ENTER("unlock_io_cache");
   DBUG_PRINT("io_cache_share", ("%s: 0x%lx  pos: %lu  running: %u",
                                 (cache == cshare->source_cache) ?
                                 "writer" : "reader",
                                 (long) cache, (ulong) cshare->pos_in_file,
                                 cshare->total_threads));
   cshare->running_threads= cshare->total_threads;
   mysql_cond_broadcast(&cshare->cond);
   mysql_mutex_unlock(&cshare->mutex);
   DBUG_VOID_RETURN;
 }
References st_io_cache_share::cond, DBUG_ENTER, DBUG_PRINT, DBUG_VOID_RETURN, st_io_cache_share::mutex, mysql_cond_broadcast, mysql_mutex_unlock, st_io_cache_share::pos_in_file, st_io_cache_share::running_threads, st_io_cache::share, st_io_cache_share::source_cache, and st_io_cache_share::total_threads.
Referenced by _my_b_read_r(), and copy_to_read_buffer().