Azerotcore-wotlk: Acore::HealthPctOrderPred Class Reference
Acore::HealthPctOrderPred Class Reference
#include <Unit.h>
Public Member Functions
HealthPctOrderPred (bool ascending=true)
bool operator() (WorldObject const *objA, WorldObject const *objB) const
bool operator() (Unit const *a, Unit const *b) const
Private Attributes
bool const _ascending
Detailed Description
Definition at line 2688 of file Unit.h.
Constructor & Destructor Documentation
HealthPctOrderPred()
Acore::HealthPctOrderPred::HealthPctOrderPred (bool ascending = true) inline
Definition at line 2691 of file Unit.h.
 : _ascending(ascending) { }
Member Function Documentation
operator()() [1/2]
bool Acore::HealthPctOrderPred::operator() (Unit const * a, Unit const * b) const inline
Definition at line 2702 of file Unit.h.
         {
             float rA = a->GetMaxHealth() ? float(a->GetHealth()) / float(a->GetMaxHealth()) : 0.0f;
             float rB = b->GetMaxHealth() ? float(b->GetHealth()) / float(b->GetMaxHealth()) : 0.0f;
             return _ascending ? rA < rB : rA > rB;
         }
References _ascending, Unit::GetHealth(), and Unit::GetMaxHealth().
operator()() [2/2]
bool Acore::HealthPctOrderPred::operator() (WorldObject const * objA, WorldObject const * objB) const inline
Definition at line 2693 of file Unit.h.
         {
             Unit const* a = objA->ToUnit();
             Unit const* b = objB->ToUnit();
             float rA = (a && a->GetMaxHealth()) ? float(a->GetHealth()) / float(a->GetMaxHealth()) : 0.0f;
             float rB = (b && b->GetMaxHealth()) ? float(b->GetHealth()) / float(b->GetMaxHealth()) : 0.0f;
             return _ascending ? rA < rB : rA > rB;
         }
References _ascending, Unit::GetHealth(), Unit::GetMaxHealth(), and Object::ToUnit().
Member Data Documentation
_ascending
bool const Acore::HealthPctOrderPred::_ascending private
Definition at line 2710 of file Unit.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/game/Entities/Unit/Unit.h