Azerotcore-wotlk: G3D::GImage Class Reference
G3D::GImage Class Reference
#include <GImage.h>
Classes
class Error
Public Types
enum Format {
JPEG , BMP , TGA , PCX ,
ICO , PNG , PPM_BINARY , PGM_BINARY = PPM_BINARY ,
PPM_ASCII , PGM_ASCII = PPM_ASCII , AUTODETECT , UNKNOWN
}
Public Member Functions
int channels () const
int width () const
int height () const
const uint8 * byte () const
template<typename Type >
const Type * rawData () const
template<typename Type >
Type * rawData ()
const Color1uint8 * pixel1 () const
Color1uint8 * pixel1 ()
const Color4uint8 * pixel4 () const
Color4uint8 * pixel4 ()
const Color3uint8 * pixel3 () const
Color3uint8 * pixel3 ()
const Color1uint8 & pixel1 (int x, int y) const
Color1uint8 & pixel1 (int x, int y)
const Color3uint8 & pixel3 (int x, int y) const
Color3uint8 & pixel3 (int x, int y)
const Color4uint8 & pixel4 (int x, int y) const
Color4uint8 & pixel4 (int x, int y)
uint8 * byte ()
void flipHorizontal ()
void flipVertical ()
void rotate90CW (int numTimes=1)
GImage (int width=0, int height=0, int channels=3, const MemoryManager::Ref &m=MemoryManager::create())
GImage (const std::string &filename, Format format=AUTODETECT, const MemoryManager::Ref &m=MemoryManager::create())
GImage (const unsigned char *data, int length, Format format=AUTODETECT, const MemoryManager::Ref &m=MemoryManager::create())
GImage (const GImage &other, const MemoryManager::Ref &m=MemoryManager::create())
GImage & operator= (const GImage &other)
void insertRedAsAlpha (const GImage &alpha, GImage &output) const
void stripAlpha (GImage &output) const
void load (const std::string &filename, Format format=AUTODETECT)
void clear ()
virtual ~GImage ()
void resize (int width, int height, int channels, bool zero=true)
void convertToRGBA ()
void convertToRGB ()
void convertToL8 ()
void save (const std::string &filename, Format format=AUTODETECT) const
void encode (Format format, uint8 *&outData, int &outLength) const
void encode (Format format, BinaryOutput &out) const
void decode (BinaryInput &input, Format format)
int sizeInMemory () const
Static Public Member Functions
static Format resolveFormat (const std::string &filename)
static bool pasteSubImage (GImage &dest, const GImage &src, int destX, int destY, int srcX, int srcY, int srcWidth, int srcHeight)
static bool copySubImage (GImage &dest, const GImage &src, int srcX, int srcY, int srcWidth, int srcHeight)
static bool supportedFormat (const std::string &format)
static Format stringToFormat (const std::string &format)
static void R8G8B8_to_Y8U8V8 (int width, int height, const uint8 *in, uint8 *out)
static void Y8U8V8_to_R8G8B8 (int width, int height, const uint8 *in, uint8 *out)
static void RGBtoRGBA (const uint8 *in, uint8 *out, int numPixels)
static void RGBtoARGB (const uint8 *in, uint8 *out, int numPixels)
static void LtoRGB (const uint8 *in, uint8 *out, int numPixels)
static void LtoRGBA (const uint8 *in, uint8 *out, int numPixels)
static void RGBtoBGR (const uint8 *in, uint8 *out, int numPixels)
static void RGBtoBGRA (const uint8 *in, uint8 *out, int numPixels)
static void RGBAtoRGB (const uint8 *in, uint8 *out, int numPixels)
static void RGBxRGBtoRGBA (const uint8 *colorRGB, const uint8 *alphaRGB, uint8 *out, int numPixels)
static void flipRGBVertical (const uint8 *in, uint8 *out, int width, int height)
static void flipRGBAVertical (const uint8 *in, uint8 *out, int width, int height)
static void computeNormalMap (const class GImage &bump, class GImage &normal, const BumpMapPreprocess &preprocess=BumpMapPreprocess())
static void computeNormalMap (int width, int height, int channels, const uint8 *src, GImage &normal, const BumpMapPreprocess &preprocess=BumpMapPreprocess())
static void BAYER_G8B8_R8G8_to_R8G8B8_MHC (int w, int h, const uint8 *in, uint8 *_out)
static void BAYER_G8R8_B8G8_to_R8G8B8_MHC (int w, int h, const uint8 *in, uint8 *_out)
static void BAYER_R8G8_G8B8_to_R8G8B8_MHC (int w, int h, const uint8 *in, uint8 *_out)
static void BAYER_B8G8_G8R8_to_R8G8B8_MHC (int w, int h, const uint8 *in, uint8 *_out)
static void BAYER_G8B8_R8G8_to_Quarter_R8G8B8 (int inWidth, int inHeight, const uint8 *in, uint8 *out)
static void Quarter_R8G8B8_to_BAYER_G8B8_R8G8 (int inWidth, int inHeight, const uint8 *in, uint8 *out)
static void makeCheckerboard (GImage &im, int checkerSize=1, const Color4uint8 &color1=Color4uint8(255, 255, 255, 255), const Color4uint8 &color2=Color4uint8(0, 0, 0, 255))
Private Member Functions
void encodeBMP (BinaryOutput &out) const
void encodeTGA (BinaryOutput &out) const
void encodeJPEG (BinaryOutput &out) const
void encodePNG (BinaryOutput &out) const
void encodePPM (BinaryOutput &out) const
void encodePPMASCII (BinaryOutput &out) const
void decodeTGA (BinaryInput &input)
void decodeBMP (BinaryInput &input)
void decodeJPEG (BinaryInput &input)
void decodePCX (BinaryInput &input)
void decodeICO (BinaryInput &input)
void decodePNG (BinaryInput &input)
void decodePPM (BinaryInput &input)
void decodePPMASCII (BinaryInput &input)
void _copy (const GImage &other)
Static Private Member Functions
static Format resolveFormat (const std::string &filename, const uint8 *data, int dataLen, Format maybeFormat)
Private Attributes
MemoryManager::Ref m_memMan
uint8 * m_byte
int m_channels
int m_width
int m_height
Detailed Description
Interface to image compression & file formats.
Supported formats (decode and encode): Color JPEG, PNG, (Uncompressed) TGA 24, (Uncompressed) TGA 32, BMP 1, BMP 4, BMP 8, BMP 24, PPM (P6), and PPM ASCII (P1, P2, P3), which includes PPM, PGM, and PBM. (Compressed) TGA 24, (Compressed) TGA 32, 8-bit paletted PCX, 24-bit PCX, and ICO are supported for decoding only.
Sample usage:
  // Loading from disk:
  G3D::GImage im1("test.jpg");
  // Loading from memory:
  G3D::GImage im2(data, length);
  // im.pixel is a pointer to RGB color data.  If you want
  // an alpha channel, call RGBtoRGBA or RGBtoARGB for
  // conversion.
  // Saving to memory:
  G3D::GImage im3(width, height);
  // (Set the pixels of im3...)
  uint8* data2;
  int    len2;
  im3.encode(G3D::GImage::JPEG, data2, len2);
  // Saving to disk
  im3.save("out.jpg");
The free Image Magick Magick Wand API (http://www.imagemagick.org/www/api/magick_wand.html) provides a more powerful API for image manipulation and wider set of image load/save formats. It is recommended over GImage (we don't include it directly in G3D because their license is more restrictive than the BSD one).
[http://tfcduke.developpez.com/tutoriel/format/tga/fichiers/tga_specs.pdf]
See also
Image3, Image3uint8, Image4, Image4uint8, Image1, Image1uint8, Texture, Map2D
Definition at line 86 of file GImage.h.
Member Enumeration Documentation
Format
enum G3D::GImage::Format
PGM, PPM, and PBM all come in two versions and are classified as PPM_* files
Enumerator
JPEG
BMP
TGA
PCX
ICO
PNG
PPM_BINARY
PGM_BINARY
PPM_ASCII
PGM_ASCII
AUTODETECT
UNKNOWN
Definition at line 112 of file GImage.h.
                 {JPEG, BMP, TGA, PCX, ICO, PNG,
         PPM_BINARY, PGM_BINARY = PPM_BINARY,
         PPM_ASCII, PGM_ASCII = PPM_ASCII,
         AUTODETECT, UNKNOWN};
Constructor & Destructor Documentation
GImage() [1/4]
G3D::GImage::GImage (int width = 0, int height = 0, int channels = 3, const MemoryManager::Ref & m = MemoryManager::create())
Create an empty image of the given size.
See also
load()
Definition at line 546 of file GImage.cpp.
                                  :
     m_memMan(mem),
     m_byte(0),
     m_channels(0),
     m_width(0),
     m_height(0) {
     resize(width, height, channels);
 }
References channels(), height(), resize(), and width().
Referenced by sizeInMemory().
GImage() [2/4]
G3D::GImage::GImage (const std::string & filename, Format format = AUTODETECT, const MemoryManager::Ref & m = MemoryManager::create())
Load an encoded image from disk and decode it. Throws GImage::Error if something goes wrong.
Definition at line 493 of file GImage.cpp.
                                :
     m_memMan(m),
     m_byte(NULL),
     m_channels(0),
     m_width(0),
     m_height(0) {
     load(filename, format);
 }
References G3D::format(), and load().
GImage() [3/4]
G3D::GImage::GImage (const unsigned char * data, int length, Format format = AUTODETECT, const MemoryManager::Ref & m = MemoryManager::create())
Decodes an image stored in a buffer.
Definition at line 527 of file GImage.cpp.
                                :
     m_memMan(m),
     m_byte(NULL),
     m_channels(0),
     m_width(0),
     m_height(0) {
     BinaryInput b(data, length, G3D_LITTLE_ENDIAN);
     // It is safe to cast away the const because we
     // know we don't corrupt the data.
     decode(b, resolveFormat("", data, length, format));
 }
References b, decode(), G3D::format(), G3D::G3D_LITTLE_ENDIAN, G3D::length(), and resolveFormat().
GImage() [4/4]
G3D::GImage::GImage (const GImage & other, const MemoryManager::Ref & m = MemoryManager::create())
Definition at line 666 of file GImage.cpp.
                                : m_memMan(m), m_byte(NULL) {
     _copy(other);
 }
References _copy().
~GImage()
G3D::GImage::~GImage () virtual
Deallocates the pixels.
Definition at line 674 of file GImage.cpp.
                 {
     clear();
 }
References clear().
Member Function Documentation
_copy()
void G3D::GImage::_copy (const GImage & other) private
Definition at line 588 of file GImage.cpp.
{
     clear();
     m_width  = other.m_width;
     m_height = other.m_height;
     m_channels = other.m_channels;
     int s  = m_width * m_height * m_channels * sizeof(uint8);
     m_byte  = (uint8*)m_memMan->alloc(s);
     debugAssert(isValidHeapPointer(m_byte));
     memcpy(m_byte, other.m_byte, s);
 }
References clear(), debugAssert, G3D::isValidHeapPointer(), m_byte, m_channels, m_height, m_memMan, m_width, and memcpy.
Referenced by GImage(), and operator=().
BAYER_B8G8_G8R8_to_R8G8B8_MHC()
void G3D::GImage::BAYER_B8G8_G8R8_to_R8G8B8_MHC (int w, int h, const uint8 * in, uint8 * _out) static
Definition at line 232 of file GImage_bayer.cpp.
{
     // Run the equivalent function for red
     BAYER_R8G8_G8B8_to_R8G8B8_MHC(w, h, in, _out);
     // Now swap red and blue
     swapRedAndBlue(w * h, (Color3uint8*)_out);
 }
References BAYER_R8G8_G8B8_to_R8G8B8_MHC(), and G3D::swapRedAndBlue().
BAYER_G8B8_R8G8_to_Quarter_R8G8B8()
void G3D::GImage::BAYER_G8B8_R8G8_to_Quarter_R8G8B8 (int inWidth, int inHeight, const uint8 * in, uint8 * out) static
Fast conversion; the output has 1/2 the size of the input in each direction. Assumes in != out. See G3D::BAYER_G8B8_R8G8_to_R8G8B8_MHC for a much better result.
Definition at line 12 of file GImage_bayer.cpp.
{
     debugAssert(in != out);
     int halfHeight = height / 2;
     int halfWidth  = width / 2;
     int dst_off = 0;
     for (int y = 0; y < halfHeight; ++y) {
         for (int x = 0; x < halfWidth; ++x) {
             // GBRG
             int src_off = x*2 + y*2*width;
             out[dst_off] = in[src_off+width]; // red
             out[dst_off+1] = ((int)in[src_off] + (int)in[src_off+width+1])/2; // green
             out[dst_off+2] = in[src_off+1]; // blue
             dst_off = dst_off + 3;
         }
     }
 }
References debugAssert, height(), width(), G3D::x, and G3D::y.
BAYER_G8B8_R8G8_to_R8G8B8_MHC()
void G3D::GImage::BAYER_G8B8_R8G8_to_R8G8B8_MHC (int w, int h, const uint8 * in, uint8 * _out) static
Bayer demosaicing using the filter proposed in
HIGH-QUALITY LINEAR INTERPOLATION FOR DEMOSAICING OF BAYER-PATTERNED COLOR IMAGES Henrique S. Malvar, Li-wei He, and Ross Cutler
The filter wraps at the image boundaries.
Assumes in != out.
Definition at line 241 of file GImage_bayer.cpp.
{
     debugAssert(in != _out);
     Color3uint8* out = (Color3uint8*)_out;
     for (int y = 0; y < h; ++y) {
         // Row beginning in the input array.
         int offset = y * w;
         // GB row
         for (int x = 0; x < w; ++x, ++out) {
             // G pixel
             {
                 out->r = applyFilter(in, x, y, w, h, R_BGG);
                 out->g = in[x + offset];
                 out->b = applyFilter(in, x, y, w, h, B_BGG);
             }
             ++x; ++out;
             // B pixel
             {
                 out->r = applyFilter(in, x, y, w, h, R_BGB);
                 out->g = applyFilter(in, x, y, w, h, G_BGB);
                 out->b = in[x + offset];
             }
         }
         ++y;
         offset += w;
         // RG row
         for (int x = 0; x < w; ++x, ++out) {
             // R pixel
             {
                 out->r = in[x + offset];
                 out->g = applyFilter(in, x, y, w, h, G_GRR);
                 out->b = applyFilter(in, x, y, w, h, B_GRR);
             }
             ++x; ++out;
             // G pixel
             {
                 out->r = applyFilter(in, x, y, w, h, R_GRG);
                 out->g = in[x + offset];
                 out->b = applyFilter(in, x, y, w, h, B_GRG);
             }
         }
     }
 }
References G3D::applyFilter(), G3D::Color3uint8::b, B_BGG, B_GRG, B_GRR, debugAssert, G3D::Color3uint8::g, G3D::G_BGB, G3D::G_GRR, G3D::Color3uint8::r, G3D::R_BGB, G3D::R_BGG, G3D::R_GRG, G3D::x, and G3D::y.
Referenced by BAYER_G8R8_B8G8_to_R8G8B8_MHC().
BAYER_G8R8_B8G8_to_R8G8B8_MHC()
void G3D::GImage::BAYER_G8R8_B8G8_to_R8G8B8_MHC (int w, int h, const uint8 * in, uint8 * _out) static
Definition at line 223 of file GImage_bayer.cpp.
{
     // Run the equivalent function for red
     BAYER_G8B8_R8G8_to_R8G8B8_MHC(w, h, in, _out);
     // Now swap red and blue
     swapRedAndBlue(w * h, (Color3uint8*)_out);
 }
References BAYER_G8B8_R8G8_to_R8G8B8_MHC(), and G3D::swapRedAndBlue().
BAYER_R8G8_G8B8_to_R8G8B8_MHC()
void G3D::GImage::BAYER_R8G8_G8B8_to_R8G8B8_MHC (int w, int h, const uint8 * in, uint8 * _out) static
Definition at line 164 of file GImage_bayer.cpp.
{
     debugAssert(in != _out);
     Color3uint8* out = (Color3uint8*)_out;
     for (int y = 0; y < h; ++y) {
         // Row beginning in the input array.
         int offset = y * w;
         // RG row
         for (int x = 0; x < w; ++x, ++out) {
             // R pixel
             {
                 out->r = in[x + offset];
                 out->g = applyFilter(in, x, y, w, h, G_GRR);
                 out->b = applyFilter(in, x, y, w, h, B_GRR);
             }
             ++x; ++out;
             // G pixel
             {
                 out->r = applyFilter(in, x, y, w, h, R_GRG);
                 out->g = in[x + offset];
                 out->b = applyFilter(in, x, y, w, h, B_GRG);
             }
         }
         ++y;
         offset += w;
         // GB row
         for (int x = 0; x < w; ++x, ++out) {
             // G pixel
             {
                 out->r = applyFilter(in, x, y, w, h, R_BGG);
                 out->g = in[x + offset];
                 out->b = applyFilter(in, x, y, w, h, B_BGG);
             }
             ++x; ++out;
             // B pixel
             {
                 out->r = applyFilter(in, x, y, w, h, R_BGB);
                 out->g = applyFilter(in, x, y, w, h, G_BGB);
                 out->b = in[x + offset];
             }
         }
     }
 }
References G3D::applyFilter(), G3D::Color3uint8::b, B_BGG, B_GRG, B_GRR, debugAssert, G3D::Color3uint8::g, G3D::G_BGB, G3D::G_GRR, G3D::Color3uint8::r, G3D::R_BGB, G3D::R_BGG, G3D::R_GRG, G3D::x, and G3D::y.
Referenced by BAYER_B8G8_G8R8_to_R8G8B8_MHC().
byte() [1/2]
uint8* G3D::GImage::byte () inline
Definition at line 228 of file GImage.h.
{
         return m_byte;
     }
References m_byte.
byte() [2/2]
const uint8* G3D::GImage::byte () const inline
Definition at line 133 of file GImage.h.
{
         return m_byte;
     }
References m_byte.
Referenced by insertRedAsAlpha(), makeCheckerboard(), pasteSubImage(), G3D::Image1uint8::save(), G3D::Image3uint8::save(), G3D::Image4uint8::save(), and stripAlpha().
channels()
int G3D::GImage::channels () const inline
The number of channels; either 3 (RGB) or 4 (RGBA)
Definition at line 121 of file GImage.h.
{
         return m_channels;
     }
References m_channels.
Referenced by computeNormalMap(), G3D::Image1uint8::copyGImage(), G3D::Image3uint8::copyGImage(), G3D::Image4uint8::copyGImage(), G3D::Image1uint8::fromGImage(), G3D::Image3uint8::fromGImage(), G3D::Image4uint8::fromGImage(), GImage(), insertRedAsAlpha(), pasteSubImage(), and resize().
clear()
void G3D::GImage::clear ()
Frees memory and resets to a 0x0 image.
Definition at line 679 of file GImage.cpp.
                    {
     m_width = 0;
     m_height = 0;
     m_memMan->free(m_byte);
     m_byte = NULL;
 }
References m_byte, m_height, m_memMan, m_width, and NULL.
Referenced by _copy(), load(), resize(), and ~GImage().
computeNormalMap() [1/2]
static void G3D::GImage::computeNormalMap (const class GImage & bump, class GImage & normal, const BumpMapPreprocess & preprocess = BumpMapPreprocess()) static
Given a tangent space bump map, computes a new image where the RGB channels are a tangent space normal map and the alpha channel is the original bump map. Assumes the input image is tileable.
In the resulting image, x = red = tangent, y = green = binormal, and z = blue = normal.
Particularly useful as part of the idiom:
    GImage normal;
    computeNormalMap(GImage(filename), normal);
    return Texture::fromGImage(filename, normal);
computeNormalMap() [2/2]
void G3D::GImage::computeNormalMap (int width, int height, int channels, const uint8 * src, GImage & normal, const BumpMapPreprocess & preprocess = BumpMapPreprocess()) static
Definition at line 884 of file GImage.cpp.
{
     float whiteHeightInPixels = preprocess.zExtentPixels;
     bool lowPassBump          = preprocess.lowPassFilter;
     bool scaleHeightByNz      = preprocess.scaleZByNz;
     if (whiteHeightInPixels < 0.0f) {
         // Default setting scales so that a gradient ramp
         // over the whole image becomes a 45-degree angle
         // Account for potentially non-square aspect ratios
         whiteHeightInPixels = max(width, height) * -whiteHeightInPixels;
     }
     debugAssert(whiteHeightInPixels >= 0);
     const int w = width;
     const int h = height;
     const int stride = channels;
     normal.resize(w, h, 4);
     const uint8* const B = src;
     Color4uint8* const N = normal.pixel4();
     // 1/s for the scale factor that each ELEVATION should be multiplied by.
     // We avoid actually multiplying by this and instead just divide it out of z.
     float elevationInvScale = 255.0f / whiteHeightInPixels;
     for (int y = 0; y < h; ++y) {
         for (int x = 0; x < w; ++x) {
             // Index into normal map pixel
             int i = x + y * w;
             // Index into bump map *byte*
             int j = stride * i;
             Vector3 delta;
             // Get a value from B (with wrapping lookup) relative to (x, y)
             // and divide by 255
             #define ELEVATION(DX, DY)  ((int)B[(((DX + x + w) % w) + \
                                                 ((DY + y + h) % h) * w) * stride])
             // Sobel filter to compute the normal.
             //
             // Y Filter (X filter is the transpose)
             //  [ -1 -2 -1 ]
             //  [  0  0  0 ]
             //  [  1  2  1 ]
             // Write the Y value directly into the x-component so we don't have
             // to explicitly compute a cross product at the end.  Does not
             // go out of bounds because the above is computed mod (width, height)
             delta.y = -( ELEVATION(-1, -1) * 1 +  ELEVATION( 0, -1) * 2 +  ELEVATION( 1, -1) * 1 +
                         -ELEVATION(-1,  1) * 1 + -ELEVATION( 0,  1) * 2 + -ELEVATION( 1,  1) * 1);
             delta.x = -(-ELEVATION(-1, -1) * 1 + ELEVATION( 1, -1) * 1 +
                         -ELEVATION(-1,  0) * 2 + ELEVATION( 1,  0) * 2 +
                         -ELEVATION(-1,  1) * 1 + ELEVATION( 1,  1) * 1);
             // The scale of each filter row is 4, the filter width is two pixels,
             // and the "normal" range is 0-255.
             delta.z = 4 * 2 * elevationInvScale;
             // Delta is now scaled in pixels; normalize
             delta = delta.direction();
             // Copy over the bump value into the alpha channel.
             float H = B[j] / 255.0f;
             if (lowPassBump) {
                 H = (ELEVATION(-1, -1) + ELEVATION( 0, -1) + ELEVATION(1, -1) +
                      ELEVATION(-1,  0) + ELEVATION( 0,  0) + ELEVATION(1,  0) +
                      ELEVATION(-1,  1) + ELEVATION( 0,  1) + ELEVATION(1,  1)) / (255.0f * 9.0f);
             }
 #           undef ELEVATION
             if (scaleHeightByNz) {
                 // delta.z can't possibly be negative, so we avoid actually
                 // computing the absolute value.
                 H *= delta.z;
             }
             N[i].a = iRound(H * 255.0f);
             // Pack into byte range
             delta = delta * 127.5f + Vector3(127.5f, 127.5f, 127.5f);
             N[i].r = iClamp(iRound(delta.x), 0, 255);
             N[i].g = iClamp(iRound(delta.y), 0, 255);
             N[i].b = iClamp(iRound(delta.z), 0, 255);
         }
     }
 }
References G3D::Color4uint8::a, G3D::Color4uint8::b, channels(), debugAssert, G3D::Vector3::direction(), ELEVATION, G3D::Color4uint8::g, H, height(), G3D::iClamp(), G3D::iRound(), G3D::BumpMapPreprocess::lowPassFilter, G3D::max(), pixel4(), G3D::Color4uint8::r, resize(), G3D::BumpMapPreprocess::scaleZByNz, width(), G3D::x, G3D::Vector3::x, G3D::y, G3D::Vector3::y, G3D::Vector3::z, and G3D::BumpMapPreprocess::zExtentPixels.
convertToL8()
void G3D::GImage::convertToL8 ()
Averages color channels if they exist
Definition at line 989 of file GImage.cpp.
{
     switch (m_channels) {
     case 1:
         return;
     case 3:
         {
             // Average
             Color3uint8* src = (Color3uint8*)m_byte;
             m_byte = NULL;
             resize(m_width, m_height, 1);
             for (int i = m_width * m_height - 1; i >= 0; --i) {
                 const Color3uint8   s = src[i];
                 uint8&              d = m_byte[i];
                 d = ((int)s.r + (int)s.g + (int)s.b) / 3;
             }
             m_memMan->free(src);
         }
         break;
     case 4:
         {
             // Average
             Color4uint8* src = (Color4uint8*)m_byte;
             m_byte = NULL;
             resize(m_width, m_height, 1);
             for (int i = m_width * m_height - 1; i >= 0; --i) {
                 const Color4uint8   s = src[i];
                 uint8&              d = m_byte[i];
                 d = ((int)s.r + (int)s.g + (int)s.b) / 3;
             }
             m_memMan->free(src);
         }
         return;
     default:
         alwaysAssertM(false, "Bad number of channels in input image");
     }
 }
References alwaysAssertM, G3D::Color3uint8::b, G3D::Color4uint8::b, mpq::d, G3D::Color3uint8::g, G3D::Color4uint8::g, m_byte, m_channels, m_height, m_memMan, m_width, NULL, G3D::Color3uint8::r, G3D::Color4uint8::r, and resize().
convertToRGB()
void G3D::GImage::convertToRGB ()
Definition at line 1076 of file GImage.cpp.
{
     switch (m_channels) {
     case 1:
         {
             // Spread
             uint8* old = m_byte;
             m_byte = NULL;
             resize(m_width, m_height, 3);
             for (int i = m_width * m_height - 1; i >= 0; --i) {
                 const uint8  s = old[i];
                 Color3uint8& d = ((Color3uint8*)m_byte)[i];
                 d.r = d.g = d.b = s;
             }
             m_memMan->free(old);
         }
         break;
     case 3:
         return;
     case 4:
         // Strip alpha
         {
             Color4uint8* old = (Color4uint8*)m_byte;
             m_byte = NULL;
             resize(m_width, m_height, 3);
             for (int i = m_width * m_height - 1; i >= 0; --i) {
                 const Color4uint8   s = old[i];
                 Color3uint8&        d = ((Color3uint8*)m_byte)[i];
                 d.r = s.r;
                 d.g = s.g;
                 d.b = s.b;
             }
             m_memMan->free(old);
         }
         break;
     default:
         alwaysAssertM(false, "Bad number of channels in input image");
     }
 }
References alwaysAssertM, G3D::Color4uint8::b, mpq::d, G3D::Color4uint8::g, m_byte, m_channels, m_height, m_memMan, m_width, NULL, G3D::Color4uint8::r, and resize().
Referenced by encodeJPEG().
convertToRGBA()
void G3D::GImage::convertToRGBA ()
Definition at line 1030 of file GImage.cpp.
{
     switch (m_channels) {
     case 1:
         {
             // Spread
             uint8* old = m_byte;
             m_byte = NULL;
             resize(m_width, m_height, 4);
             for (int i = m_width * m_height - 1; i >= 0; --i) {
                 const uint8  s = old[i];
                 Color4uint8& d = ((Color4uint8*)m_byte)[i];
                 d.r = d.g = d.b = s;
                 d.a = 255;
             }
             m_memMan->free(m_byte);
         }
         break;
     case 3:
         {
             // Add alpha
             Color3uint8* old = (Color3uint8*)m_byte;
             m_byte = NULL;
             resize(m_width, m_height, 4);
             for (int i = m_width * m_height - 1; i >= 0; --i) {
                 const Color3uint8   s = old[i];
                 Color4uint8&        d = ((Color4uint8*)m_byte)[i];
                 d.r = s.r;
                 d.g = s.g;
                 d.b = s.b;
                 d.a = 255;
             }
             m_memMan->free(old);
         }
         break;
     case 4:
         // Already RGBA
         return;
     default:
         alwaysAssertM(false, "Bad number of channels in input image");
     }
 }
References alwaysAssertM, G3D::Color3uint8::b, mpq::d, G3D::Color3uint8::g, m_byte, m_channels, m_height, m_memMan, m_width, NULL, G3D::Color3uint8::r, and resize().
copySubImage()
bool G3D::GImage::copySubImage (GImage & dest, const GImage & src, int srcX, int srcY, int srcWidth, int srcHeight) static
creates dest from src sub-image data.
Returns true on success and false if the src sub-image is not within src.
Definition at line 693 of file GImage.cpp.
{
     if ((src.m_width < srcX + srcWidth) ||
         (src.m_height < srcY + srcHeight) ||
         (srcY < 0) ||
         (srcX < 0)) {
         return false;
     }
     dest.resize(srcWidth, srcHeight, src.m_channels);
     bool ret;
     ret = pasteSubImage(dest, src, 0, 0, srcX, srcY, srcWidth, srcHeight);
     debugAssert(ret);
     return true;
 }
References debugAssert, m_channels, m_height, m_width, pasteSubImage(), resize(), and ret.
decode()
void G3D::GImage::decode (BinaryInput & input, Format format)
Decodes the buffer into this image.
Parameters
format Must be the correct format.
Definition at line 228 of file GImage.cpp.
{
     switch (format) {
     case PPM_ASCII:
         decodePPMASCII(input);
         break;
     case PPM_BINARY:
         decodePPM(input);
         break;
     case PNG:
         decodePNG(input);
         break;
     case JPEG:
         decodeJPEG(input);
         break;
     case TGA:
         decodeTGA(input);
         break;
     case BMP:
         decodeBMP(input);
         break;
     case ICO:
         decodeICO(input);
         break;
     case PCX:
         decodePCX(input);
         break;
     default:
         debugAssert(false);
     }
     debugAssert(m_width >= 0);
     debugAssert(m_height >= 0);
     debugAssert(m_channels == 1 || m_channels == 3 || m_channels == 4);
     debugAssert(m_byte != NULL);
 }
References BMP, debugAssert, decodeBMP(), decodeICO(), decodeJPEG(), decodePCX(), decodePNG(), decodePPM(), decodePPMASCII(), decodeTGA(), G3D::format(), ICO, JPEG, m_byte, m_channels, m_height, m_width, NULL, PCX, PNG, PPM_ASCII, PPM_BINARY, and TGA.
Referenced by GImage(), and load().
decodeBMP()
void G3D::GImage::decodeBMP (BinaryInput & input) private
Definition at line 144 of file GImage_bmp.cpp.
{
     // The BMP decoding uses these flags.
     static const uint16 PICTURE_NONE               = 0x0000;
     static const uint16 PICTURE_BITMAP             = 0x1000;
     // Compression Flags
     static const uint16 PICTURE_UNCOMPRESSED       = 0x0100;
     static const uint16 PICTURE_MONOCHROME         = 0x0001;
     static const uint16 PICTURE_4BIT               = 0x0002;
     static const uint16 PICTURE_8BIT               = 0x0004;
     static const uint16 PICTURE_16BIT              = 0x0008;
     static const uint16 PICTURE_24BIT              = 0x0010;
     static const uint16 PICTURE_32BIT              = 0x0020;
     (void)PICTURE_16BIT;
     (void)PICTURE_32BIT;
     // This is a simple BMP loader that can handle uncompressed BMP files.
     // Verify this is a BMP file by looking for the BM tag.
     input.reset();
     std::string tag = input.readString(2);
     if (tag != "BM") {
         throw Error("Not a BMP file", input.getFilename());
     }
     m_channels = 3;
     // Skip to the BITMAPINFOHEADER's width and height
     input.skip(16);
     m_width  = input.readUInt32();
     m_height = input.readUInt32();
     // Skip to the bit count and compression type
     input.skip(2);
     uint16 bitCount        = input.readUInt16();
     uint32 compressionType = input.readUInt32();
     uint8 red;
     uint8 green;
     uint8 blue;
     uint8 blank;
     // Only uncompressed bitmaps are supported by this code
     if ((int32)compressionType != BI_RGB) {
         throw Error("BMP images must be uncompressed", input.getFilename());
     }
     uint8* palette = NULL;
     // Create the palette if needed
     if (bitCount <= 8) {
         // Skip to the palette color count in the header
         input.skip(12);
         int numColors = input.readUInt32();
         palette = (uint8*)System::malloc(numColors * 3);
         debugAssert(palette);
         // Skip past the end of the header to the palette info
         input.skip(4);
         int c;
         for(c = 0; c < numColors * 3; c += 3) {
             // Palette information in bitmaps is stored in BGR_ format.
             // That means it's blue-green-red-blank, for each entry.
             blue  = input.readUInt8();
             green = input.readUInt8();
             red   = input.readUInt8();
             blank = input.readUInt8();
             palette[c]     = red;
             palette[c + 1] = green;
             palette[c + 2] = blue;
         }
     }
     int hStart = 0;
     int hEnd   = 0;
     int hDir   = 0;
     if (m_height < 0) {
         m_height = -m_height;
         hStart = 0;
         hEnd   = m_height;
         hDir   = 1;
     } else {
         //height = height;
         hStart = m_height - 1;
         hEnd   = -1;
         hDir   = -1;
     }
     m_byte = (uint8*)m_memMan->alloc(m_width * m_height * 3);
     debugAssert(m_byte);
     int BMScanWidth;
     int BMPadding;
     uint8 BMGroup;
     uint8 BMPixel8;
     int currPixel;
     int dest;
     int flags = PICTURE_NONE;
     if (bitCount == 1) {
         // Note that this file is not necessarily grayscale, since it's possible
         // the palette is blue-and-white, or whatever. But of course most image
         // programs only write 1-bit images if they're black-and-white.
         flags = PICTURE_BITMAP | PICTURE_UNCOMPRESSED | PICTURE_MONOCHROME;
         // For bitmaps, each scanline is dword-aligned.
         BMScanWidth = (m_width + 7) >> 3;
         if (BMScanWidth & 3) {
             BMScanWidth += 4 - (BMScanWidth & 3);
         }
         // Powers of 2
         int pow2[8] = {0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80};
         for (int h = hStart; h != hEnd; h += hDir) {
             currPixel = 0;
             dest = 3 * h * m_width;
             for (int w = 0; w < BMScanWidth; ++w) {
                 BMGroup = input.readUInt8();
                 // Now we read the pixels. Usually there are eight pixels per byte,
                 // since each pixel is represented by one bit, but if the width
                 // is not a multiple of eight, the last byte will have some bits
                 // set, with the others just being extra. Plus there's the
                 // dword-alignment padding. So we keep checking to see if we've
                 // already read "width" number of pixels.
                 for (int i = 7; i >= 0; --i) {
                     if (currPixel < m_width) {
                         int src  = 3 * ((BMGroup & pow2[i]) >> i);
                         m_byte[dest]     = palette[src];
                         m_byte[dest + 1] = palette[src + 1];
                         m_byte[dest + 2] = palette[src + 2];
                         ++currPixel;
                         dest += 3;
                     }
                 }
             }
         }
     } else if (bitCount == 4) {
         flags = PICTURE_BITMAP | PICTURE_UNCOMPRESSED | PICTURE_4BIT;
         // For bitmaps, each scanline is dword-aligned.
         int BMScanWidth = (m_width + 1) >> 1;
         if (BMScanWidth & 3) {
             BMScanWidth += 4 - (BMScanWidth & 3);
         }
         for (int h = hStart; h != hEnd; h += hDir) {
             currPixel = 0;
             dest = 3 * h * m_width;
             for (int w = 0; w < BMScanWidth; w++) {
                 BMGroup = input.readUInt8();
                 int src[2];
                 src[0] = 3 * ((BMGroup & 0xF0) >> 4);
                 src[1] = 3 * (BMGroup & 0x0F);
                 // Now we read the pixels. Usually there are two pixels per byte,
                 // since each pixel is represented by four bits, but if the width
                 // is not a multiple of two, the last byte will have only four bits
                 // set, with the others just being extra. Plus there's the
                 // dword-alignment padding. So we keep checking to see if we've
                 // already read "Width" number of pixels.
                 for (int i = 0; i < 2; ++i) {
                     if (currPixel < m_width) {
                         int tsrc  = src[i];
                         m_byte[dest]     = palette[tsrc];
                         m_byte[dest + 1] = palette[tsrc + 1];
                         m_byte[dest + 2] = palette[tsrc + 2];
                         ++currPixel;
                         dest += 3;
                     }
                 }
             }
         }
     } else if (bitCount == 8) {
         flags = PICTURE_BITMAP | PICTURE_UNCOMPRESSED | PICTURE_8BIT;
         // For bitmaps, each scanline is dword-aligned.
         BMScanWidth = m_width;
         if (BMScanWidth & 3) {
             BMScanWidth += 4 - (BMScanWidth & 3);
         }
         for (int h = hStart; h != hEnd; h += hDir) {
             currPixel = 0;
             for (int w = 0; w < BMScanWidth; ++w) {
                 BMPixel8 = input.readUInt8();
                 if (currPixel < m_width) {
                     dest = 3 * ((h * m_width) + currPixel);
                     int src  = 3 * BMPixel8;
                     m_byte[dest]     = palette[src];
                     m_byte[dest + 1] = palette[src + 1];
                     m_byte[dest + 2] = palette[src + 2];
                     ++currPixel;
                 }
             }
         }
     } else if (bitCount == 16) {
         m_memMan->free(m_byte);
         m_byte = NULL;
         System::free(palette);
         palette = NULL;
         throw Error("16-bit bitmaps not supported", input.getFilename());
     } else if (bitCount == 24) {
         input.skip(20);
         flags = PICTURE_BITMAP | PICTURE_UNCOMPRESSED | PICTURE_24BIT;
         // For bitmaps, each scanline is dword-aligned.
         BMScanWidth = m_width * 3;
         if (BMScanWidth & 3) {
             BMPadding = 4 - (BMScanWidth & 3);
         } else {
             BMPadding = 0;
         }
         for (int h = hStart; h != hEnd; h += hDir) {
             dest = 3 * h * m_width;
             for (int w = 0; w < m_width; ++w) {
                 blue  = input.readUInt8();
                 green = input.readUInt8();
                 red   = input.readUInt8();
                 m_byte[dest]     = red;
                 m_byte[dest + 1] = green;
                 m_byte[dest + 2] = blue;
                 dest += 3;
             }
             if (BMPadding) {
                 input.skip(2);
             }
         }
     } else if (bitCount == 32) {
         m_memMan->free(m_byte);
         m_byte = NULL;
         System::free(palette);
         palette = NULL;
         throw Error("32 bit bitmaps not supported", input.getFilename());
     } else {
         // We support all possible bit depths, so if the
         //     code gets here, it's not even a real bitmap.
         m_memMan->free(m_byte);
         m_byte = NULL;
         throw Error("Not a bitmap!", input.getFilename());
     }
     System::free(palette);
     palette = NULL;
 }
References G3D::BI_RGB, blue, mpq::c, debugAssert, Acore::Error(), G3D::System::free(), G3D::BinaryInput::getFilename(), green, m_byte, m_channels, m_height, m_memMan, m_width, G3D::System::malloc(), NULL, G3D::pow2(), G3D::BinaryInput::readString(), G3D::BinaryInput::readUInt16(), G3D::BinaryInput::readUInt32(), G3D::BinaryInput::readUInt8(), red, G3D::BinaryInput::reset(), and G3D::BinaryInput::skip().
Referenced by decode().
decodeICO()
void G3D::GImage::decodeICO (BinaryInput & input) private
Definition at line 435 of file GImage_bmp.cpp.
{
     // Header
     uint16 r = input.readUInt16();
     debugAssert(r == 0);
     r = input.readUInt16();
     debugAssert(r == 1);
     // Read the number of icons, although we'll only load the
     // first one.
     int count = input.readUInt16();
     m_channels = 4;
     debugAssert(count > 0);
     const uint8* headerBuffer = input.getCArray() + input.getPosition();
     int maxWidth = 0, maxHeight = 0;
     int maxHeaderNum = 0;
     for (int currentHeader = 0; currentHeader < count; ++currentHeader) {
         const uint8* curHeaderBuffer = headerBuffer + (currentHeader * 16);
         int tmpWidth = curHeaderBuffer[0];
         int tmpHeight = curHeaderBuffer[1];
         // Just in case there is a non-square icon, checking area
         if ((tmpWidth * tmpHeight) > (maxWidth * maxHeight)) {
             maxWidth = tmpWidth;
             maxHeight = tmpHeight;
             maxHeaderNum = currentHeader;
         }
     }
     input.skip(maxHeaderNum * 16);
     m_width = input.readUInt8();
     m_height = input.readUInt8();
     int numColors = input.readUInt8();
     m_byte = (uint8*)m_memMan->alloc(m_width * m_height * m_channels);
     debugAssert(m_byte);
     // Bit mask for packed bits
     int mask = 0;
     int bitsPerPixel = 8;
     switch (numColors) {
     case 2:
         mask      = 0x01;
         bitsPerPixel = 1;
         break;
     case 16:
         mask      = 0x0F;
         bitsPerPixel = 4;
         break;
     case 0:
         numColors = 256;
         mask      = 0xFF;
         bitsPerPixel = 8;
         break;
     default:
         throw Error("Unsupported ICO color count.", input.getFilename());
     }
     input.skip(5);
     // Skip 'size' unused
     input.skip(4);
     int offset = input.readUInt32();
     // Skip over any other icon descriptions
     input.setPosition(offset);
     // Skip over bitmap header; it is redundant
     input.skip(40);
     Array<Color4uint8> palette;
     palette.resize(numColors, true);
     for (int c = 0; c < numColors; ++c) {
         palette[c].b = input.readUInt8();
         palette[c].g = input.readUInt8();
         palette[c].r = input.readUInt8();
         palette[c].a = input.readUInt8();
     }
     // The actual image and mask follow
     // The XOR Bitmap is stored as 1-bit, 4-bit or 8-bit uncompressed Bitmap
     // using the same encoding as BMP files. The AND Bitmap is stored in as
     // 1-bit uncompressed Bitmap.
     //
     // Pixels are stored bottom-up, left-to-right. Pixel lines are padded
     // with zeros to end on a 32bit (4byte) boundary. Every line will have the
     // same number of bytes. Color indices are zero based, meaning a pixel color
     // of 0 represents the first color table entry, a pixel color of 255 (if there
     // are that many) represents the 256th entry.
 /*
     int bitsPerRow  = width * bitsPerPixel;
     int bytesPerRow = iCeil((double)bitsPerRow / 8);
     // Rows are padded to 32-bit boundaries
     bytesPerRow += bytesPerRow % 4;
     // Read the XOR values into the color channel
     for (int y = height - 1; y >= 0; --y) {
         int x = 0;
         // Read the row
         for (int i = 0; i < bytesPerRow; ++i) {
             uint8 byte = input.readUInt8();
             for (int j = 0; (j < 8) && (x < width); ++x, j += bitsPerPixel) {
                 int bit = ((byte << j) >> (8 - bitsPerPixel)) & mask;
                 pixel4(x, y) = colorTable[bit];
             }
         }
     }
 */
     int hStart = 0;
     int hEnd   = 0;
     int hDir   = 0;
     if (m_height < 0) {
         m_height = -m_height;
         hStart = 0;
         hEnd   = m_height;
         hDir   = 1;
     } else {
         //height = height;
         hStart = m_height - 1;
         hEnd   = -1;
         hDir   = -1;
     }
     int BMScanWidth;
     uint8 BMGroup;
     uint8 BMPixel8;
     int currPixel;
     int dest;
     if (bitsPerPixel == 1) {
         // Note that this file is not necessarily grayscale, since it's possible
         // the palette is blue-and-white, or whatever. But of course most image
         // programs only write 1-bit images if they're black-and-white.
         // For bitmaps, each scanline is dword-aligned.
         BMScanWidth = (m_width + 7) >> 3;
         if (BMScanWidth & 3) {
             BMScanWidth += 4 - (BMScanWidth & 3);
         }
         // Powers of 2
         int pow2[8] = {0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80};
         for (int h = hStart; h != hEnd; h += hDir) {
             currPixel = 0;
             dest = 3 * h * m_width;
             for (int w = 0; w < BMScanWidth; ++w) {
                 BMGroup = input.readUInt8();
                 // Now we read the pixels. Usually there are eight pixels per byte,
                 // since each pixel is represented by one bit, but if the width
                 // is not a multiple of eight, the last byte will have some bits
                 // set, with the others just being extra. Plus there's the
                 // dword-alignment padding. So we keep checking to see if we've
                 // already read "width" number of pixels.
                 for (int i = 7; i >= 0; --i) {
                     if (currPixel < m_width) {
                         int src  = ((BMGroup & pow2[i]) >> i);
                         m_byte[dest]     = palette[src].r;
                         m_byte[dest + 1] = palette[src].g;
                         m_byte[dest + 2] = palette[src].b;
                         ++currPixel;
                         dest += 4;
                     }
                 }
             }
         }
     } else if (bitsPerPixel == 4) {
         // For bitmaps, each scanline is dword-aligned.
         int BMScanWidth = (m_width + 1) >> 1;
         if (BMScanWidth & 3) {
             BMScanWidth += 4 - (BMScanWidth & 3);
         }
         for (int h = hStart; h != hEnd; h += hDir) {
             currPixel = 0;
             dest = 4 * h * m_width;
             for (int w = 0; w < BMScanWidth; w++) {
                 BMGroup = input.readUInt8();
                 int src[2];
                 src[0] = ((BMGroup & 0xF0) >> 4);
                 src[1] = (BMGroup & 0x0F);
                 // Now we read the pixels. Usually there are two pixels per byte,
                 // since each pixel is represented by four bits, but if the width
                 // is not a multiple of two, the last byte will have only four bits
                 // set, with the others just being extra. Plus there's the
                 // dword-alignment padding. So we keep checking to see if we've
                 // already read "Width" number of pixels.
                 for (int i = 0; i < 2; ++i) {
                     if (currPixel < m_width) {
                         int tsrc  = src[i];
                         m_byte[dest]     = palette[tsrc].r;
                         m_byte[dest + 1] = palette[tsrc].g;
                         m_byte[dest + 2] = palette[tsrc].b;
                         ++currPixel;
                         dest += 4;
                     }
                 }
             }
         }
     } else if (bitsPerPixel == 8) {
         // For bitmaps, each scanline is dword-aligned.
         BMScanWidth = m_width;
         if (BMScanWidth & 3) {
             BMScanWidth += 4 - (BMScanWidth & 3);
         }
         for (int h = hStart; h != hEnd; h += hDir) {
             currPixel = 0;
             for (int w = 0; w < BMScanWidth; ++w) {
                 BMPixel8 = input.readUInt8();
                 if (currPixel < m_width) {
                     dest = 4 * ((h * m_width) + currPixel);
                     int src  = BMPixel8;
                     m_byte[dest]     = palette[src].r;
                     m_byte[dest + 1] = palette[src].g;
                     m_byte[dest + 2] = palette[src].b;
                     ++currPixel;
                 }
             }
         }
     }
     // Read the mask into the alpha channel
     int bitsPerRow  = m_width;
     int bytesPerRow = iCeil((double)bitsPerRow / 8);
     // For bitmaps, each scanline is dword-aligned.
     //BMScanWidth = (width + 1) >> 1;
     if (bytesPerRow & 3) {
         bytesPerRow += 4 - (bytesPerRow & 3);
     }
     for (int y = m_height - 1; y >= 0; --y) {
         int x = 0;
         // Read the row
         for (int i = 0; i < bytesPerRow; ++i) {
             uint8 byte = input.readUInt8();
             for (int j = 0; (j < 8) && (x < m_width); ++x, ++j) {
                 int bit = (byte >> (7 - j)) & 0x01;
                 pixel4(x, y).a = (1 - bit) * 0xFF;
             }
         }
     }
 }
References G3D::Color4uint8::a, mpq::c, count(), debugAssert, Acore::Error(), G3D::BinaryInput::getCArray(), G3D::BinaryInput::getFilename(), G3D::BinaryInput::getPosition(), G3D::iCeil(), m_byte, m_channels, m_height, m_memMan, m_width, pixel4(), G3D::pow2(), G3D::BinaryInput::readUInt16(), G3D::BinaryInput::readUInt32(), G3D::BinaryInput::readUInt8(), G3D::Array< T, MIN_ELEMENTS >::resize(), G3D::BinaryInput::setPosition(), G3D::BinaryInput::skip(), G3D::x, and G3D::y.
Referenced by decode().
decodeJPEG()
void G3D::GImage::decodeJPEG (BinaryInput & input) private
Definition at line 328 of file GImage_jpeg.cpp.
{
     struct jpeg_decompress_struct   cinfo;
     struct jpeg_error_mgr           jerr;
     int                             loc = 0;
     m_channels = 3;
     // We have to set up the error handler, in case initialization fails.
     cinfo.err = jpeg_std_error(&jerr);
     // Initialize the JPEG decompression object.
     jpeg_create_decompress(&cinfo);
     // Specify data source (eg, a file, for us, memory)
     jpeg_memory_src(&cinfo, const_cast<uint8*>(input.getCArray()), input.size());
     // Read the parameters with jpeg_read_header()
     jpeg_read_header(&cinfo, TRUE);
     // Set parameters for decompression
     // (We do nothing here since the defaults are fine)
     // Start decompressor
     jpeg_start_decompress(&cinfo);
     // Get and set the values of interest to this object
     m_width     = cinfo.output_width;
     m_height    = cinfo.output_height;
     // Prepare the pointer object for the pixel data
     m_byte = (uint8*)m_memMan->alloc(m_width * m_height * 3);
     // JSAMPLEs per row in output buffer
     int bpp         = cinfo.output_components;
     int row_stride  = cinfo.output_width * bpp;
     // Make a one-row-high sample array that will go away when done with image
     JSAMPARRAY temp = (*cinfo.mem->alloc_sarray)
         ((j_common_ptr) &cinfo, JPOOL_IMAGE, row_stride, 1);
     // Read data on a scanline by scanline basis
     while (cinfo.output_scanline < cinfo.output_height) {
         // We may need to adjust the output based on the
         // number of channels it has.
         switch (bpp) {
         case 1:
             // Grayscale; decompress to temp.
             jpeg_read_scanlines(&cinfo, temp, 1);
             // Expand to three channels
             {
                 uint8* scan     = &(m_byte[loc * 3]);
                 uint8* endScan  = scan + (m_width * 3);
                 uint8* t        = *temp;
                 while (scan < endScan) {
                     uint8 value = t[0];
                     // Spread the value 3x.
                     scan[0] = value;
                     scan[1] = value;
                     scan[2] = value;
                     scan    += 3;
                     t       += 1;
                 }
             }
             break;
         case 3:
             // Read directly into the array
             {
                 // Need one extra level of indirection.
                 uint8*     scan = m_byte + loc;
                 JSAMPARRAY ptr  = &scan;
                 jpeg_read_scanlines(&cinfo, ptr, 1);
             }
             break;
         case 4:
             // RGBA; decompress to temp.
             jpeg_read_scanlines(&cinfo, temp, 1);
             // Drop the 3rd channel
             {
                 uint8* scan     = &(m_byte[loc * 3]);
                 uint8* endScan  = scan + m_width * 3;
                 uint8* t        = *temp;
                 while (scan < endScan) {
                     scan[0] = t[0];
                     scan[1] = t[1];
                     scan[2] = t[2];
                     scan    += 3;
                     t       += 4;
                 }
             }
             break;
         default:
             throw Error("Unexpected number of channels.", input.getFilename());
         }
         loc += row_stride;
     }
     // Finish decompression
     jpeg_finish_decompress(&cinfo);
     alwaysAssertM(this, "Corrupt GImage");
     // Release JPEG decompression object
     jpeg_destroy_decompress(&cinfo);
 }
References alwaysAssertM, Acore::Error(), G3D::BinaryInput::getCArray(), G3D::BinaryInput::getFilename(), G3D::jpeg_memory_src(), m_byte, m_channels, m_height, m_memMan, m_width, ptr(), G3D::BinaryInput::size(), and TRUE.
Referenced by decode().
decodePCX()
void G3D::GImage::decodePCX (BinaryInput & input) private
Definition at line 276 of file GImage.cpp.
{
     uint8  manufacturer = input.readUInt8();
     uint8  version      = input.readUInt8();
     uint8  encoding     = input.readUInt8();
     uint8  bitsPerPixel = input.readUInt8();
     uint16 xmin         = input.readUInt16();
     uint16 ymin         = input.readUInt16();
     uint16 xmax         = input.readUInt16();
     uint16 ymax         = input.readUInt16();
     uint16 horizDPI     = input.readUInt16();
     uint16 vertDPI      = input.readUInt16();
     Color3uint8 colorMap[16];
     input.readBytes(colorMap, 48);
     input.skip(1);
     uint8  planes       = input.readUInt8();
     uint16 bytesPerLine = input.readUInt16();
     uint16 paletteType  = input.readUInt16();
     input.skip(4 + 54);
     (void)bytesPerLine;
     m_width  = xmax - xmin + 1;
     m_height = ymax - ymin + 1;
     m_channels = 3;
     if ((manufacturer != 0x0A) || (encoding != 0x01)) {
         throw GImage::Error("PCX file is corrupted", input.getFilename());
     }
     (void)version;
     (void)vertDPI;
     (void)horizDPI;
     if ((bitsPerPixel != 8) || ((planes != 1) && (planes != 3))) {
         throw GImage::Error("Only 8-bit paletted and 24-bit PCX files supported.", input.getFilename());
     }
     // Prepare the pointer object for the pixel data
     m_byte = (uint8*)m_memMan->alloc(m_width * m_height * 3);
     if ((paletteType == 1) && (planes == 3)) {
         Color3uint8* pixel = pixel3();
         // Iterate over each scan line
         for (int row = 0; row < m_height; ++row) {
             // Read each scan line once per plane
             for (int plane = 0; plane < planes; ++plane) {
                 int p = row * m_width;
                 int p1 = p + m_width;
                 while (p < p1) {
                     uint8 value = input.readUInt8();
                     int length = 1;
                     if (value >= 192) {
                         // This is the length, not the value.  Mask off
                         // the two high bits and read the true index.
                         length = value & 0x3F;
                         value = input.readUInt8();
                     }
                     // Set the whole run
                     for (int i = length - 1; i >= 0; --i, ++p) {
                         debugAssert(p < m_width * m_height);
                         pixel[p][plane] = value;
                     }
                 }
             }
         }
     } else if (planes == 1) {
         Color3uint8 palette[256];
         int imageBeginning   = input.getPosition();
         int paletteBeginning = input.getLength() - 769;
         input.setPosition(paletteBeginning);
         uint8 dummy = input.readUInt8();
         if (dummy != 12) {
             Log::common()->println("\n*********************");
             Log::common()->printf("Warning: Corrupted PCX file (palette marker byte was missing) \"%s\"\nLoading anyway\n\n", input.getFilename().c_str());
         }
         input.readBytes(palette, sizeof(palette));
         input.setPosition(imageBeginning);
         Color3uint8* pixel = pixel3();
         // The palette indices are run length encoded.
         int p = 0;
         while (p < m_width * m_height) {
             uint8 index  = input.readUInt8();
             uint8 length = 1;
             if (index >= 192) {
                 // This is the length, not the index.  Mask off
                 // the two high bits and read the true index.
                 length = index & 0x3F;
                 index  = input.readUInt8();
             }
             Color3uint8 color = palette[index];
             // Set the whole run
             for (int i = length - 1; i >= 0; --i, ++p) {
                 if (p > m_width * m_height) {
                     break;
                 }
                 pixel[p] = color;
             }
         }
     } else {
         throw GImage::Error("Unsupported PCX file type.", input.getFilename());
     }
 }
References G3D::Log::common(), debugAssert, Acore::Error(), G3D::BinaryInput::getFilename(), G3D::BinaryInput::getLength(), G3D::BinaryInput::getPosition(), index, G3D::length(), m_byte, m_channels, m_height, m_memMan, m_width, pixel3(), G3D::Log::printf(), G3D::Log::println(), G3D::BinaryInput::readBytes(), G3D::BinaryInput::readUInt16(), G3D::BinaryInput::readUInt8(), G3D::BinaryInput::setPosition(), G3D::BinaryInput::skip(), and setup::version.
Referenced by decode().
decodePNG()
void G3D::GImage::decodePNG (BinaryInput & input) private
Definition at line 165 of file GImage_png.cpp.
{
     png_structp png_ptr = png_create_read_struct(PNG_LIBPNG_VER_STRING, NULL, png_error, png_warning);
     if (png_ptr == NULL) {
         throw GImage::Error("Unable to initialize PNG decoder.", input.getFilename());
     }
     png_infop info_ptr = png_create_info_struct(png_ptr);
     if (info_ptr == NULL) {
         png_destroy_read_struct(&png_ptr, (png_infopp)NULL, (png_infopp)NULL);
         throw GImage::Error("Unable to initialize PNG decoder.", input.getFilename());
     }
     png_infop end_info = png_create_info_struct(png_ptr);
     if (end_info == NULL) {
         png_destroy_read_struct(&png_ptr, &info_ptr, (png_infopp)NULL);
         throw GImage::Error("Unable to initialize PNG decoder.", input.getFilename());
     }
     // now that the libpng structures are setup, change the error handlers and read routines
     // to use G3D functions so that BinaryInput can be used.
     png_set_read_fn(png_ptr, (png_voidp)&input, png_read_data);
     // read in sequentially so that three copies of the file are not in memory at once
     png_read_info(png_ptr, info_ptr);
     png_uint_32 png_width, png_height;
     int bit_depth, color_type, interlace_type;
     // this will validate the data it extracts from info_ptr
     png_get_IHDR(png_ptr, info_ptr, &png_width, &png_height, &bit_depth, &color_type,
        &interlace_type, NULL, NULL);
     if (color_type == PNG_COLOR_TYPE_GRAY_ALPHA) {
         png_destroy_read_struct(&png_ptr, &info_ptr, &end_info);
         throw GImage::Error("Unsupported PNG color type - PNG_COLOR_TYPE_GRAY_ALPHA.", input.getFilename());
     }
     m_width  = static_cast<uint32>(png_width);
     m_height = static_cast<uint32>(png_height);
     //swap bytes of 16 bit files to least significant byte first
     png_set_swap(png_ptr);
     png_set_strip_16(png_ptr);
     //Expand paletted colors into true RGB triplets
     if (color_type == PNG_COLOR_TYPE_PALETTE) {
         png_set_palette_to_rgb(png_ptr);
     }
     //Expand grayscale images to the full 8 bits from 1, 2, or 4 bits/pixel
     if (color_type == PNG_COLOR_TYPE_GRAY && bit_depth < 8) {
         png_set_expand(png_ptr);
     }
     //Expand paletted or RGB images with transparency to full alpha channels
     //so the data will be available as RGBA quartets.
     if (png_get_valid(png_ptr, info_ptr, PNG_INFO_tRNS)) {
         png_set_tRNS_to_alpha(png_ptr);
     }
     // Fix sub-8 bit_depth to 8bit
     if (bit_depth < 8) {
         png_set_packing(png_ptr);
     }
     if ((color_type == PNG_COLOR_TYPE_RGBA) ||
         ((color_type == PNG_COLOR_TYPE_PALETTE) && (png_ptr->num_trans > 0)) ) {
         m_channels = 4;
         m_byte = (uint8*)m_memMan->alloc(m_width * m_height * 4);
     } else if ((color_type == PNG_COLOR_TYPE_RGB) ||
                (color_type == PNG_COLOR_TYPE_PALETTE)) {
         m_channels = 3;
         m_byte = (uint8*)System::malloc(m_width * m_height * 3);
     } else if (color_type == PNG_COLOR_TYPE_GRAY) {
         m_channels = 1;
         // Round up to the nearest 8 rows to avoid a bug in the PNG decoder
         int h = iCeil(m_height / 8) * 8;
         int sz = m_width * h;
         m_byte = (uint8*)m_memMan->alloc(sz);
     } else {
         throw GImage::Error("Unsupported PNG bit-depth or type.", input.getFilename());
     }
     //since we are reading row by row, required to handle interlacing
     uint32 number_passes = png_set_interlace_handling(png_ptr);
     png_read_update_info(png_ptr, info_ptr);
     for (uint32 pass = 0; pass < number_passes; ++pass) {
         for (uint32 y = 0; y < (uint32)m_height; ++y) {
             png_bytep rowPointer = &m_byte[m_width * m_channels * y];
             png_read_rows(png_ptr, &rowPointer, NULL, 1);
         }
     }
 //    png_read_image(png_ptr, &_byte);
     png_read_end(png_ptr, info_ptr);
     png_destroy_read_struct(&png_ptr, &info_ptr, &end_info);
 }
References Acore::Error(), G3D::BinaryInput::getFilename(), G3D::iCeil(), m_byte, m_channels, m_height, m_memMan, m_width, G3D::System::malloc(), NULL, G3D::png_error(), G3D::png_read_data(), G3D::png_warning(), and G3D::y.
Referenced by decode().
decodePPM()
void G3D::GImage::decodePPM (BinaryInput & input) private
Definition at line 179 of file GImage_ppm.cpp.
{
     char head[2];
     int w, h;
     input.readBytes(head, 2);
     if (head[0] != 'P' || ((head[1] != '6') && (head[1] != '5'))) {
         throw GImage::Error("Invalid PPM Header.", input.getFilename());
     }
     w = scanUInt(input);
     h = scanUInt(input);
     // Skip the max color specifier
     scanUInt(input);
     if ((w < 0) ||
         (h < 0) ||
         (w > 100000) ||
         (h > 100000)) {
         throw GImage::Error("Invalid PPM size in header.", input.getFilename());
     }
     // Trailing whitespace
     input.readUInt8();
     if (head[1] == '6') {
         // 3 channel
         resize(w, h, 3);
         input.readBytes(m_byte, m_width * m_height * 3);
     } else if (head[1] == '5') {
         // 1 channel
         resize(w, h, 1);
         input.readBytes(m_byte, m_width * m_height);
     }
 }
References Acore::Error(), G3D::BinaryInput::getFilename(), m_byte, m_height, m_width, G3D::BinaryInput::readBytes(), G3D::BinaryInput::readUInt8(), resize(), and G3D::scanUInt().
Referenced by decode().
decodePPMASCII()
void G3D::GImage::decodePPMASCII (BinaryInput & input) private
Definition at line 79 of file GImage_ppm.cpp.
{
     int ppmWidth;
     int ppmHeight;
     double maxColor;
     // Create a TextInput object to parse ascii format
     // Mixed binary/ascii formats will require more
     const std::string inputStr = input.readString();
     TextInput::Settings ppmOptions;
     ppmOptions.cppLineComments = false;
     ppmOptions.otherCommentCharacter = '#';
     ppmOptions.signedNumbers = true;
     ppmOptions.singleQuotedStrings = false;
     TextInput ppmInput(TextInput::FROM_STRING, inputStr, ppmOptions);
     //Skip first line in header P#
     std::string ppmType = ppmInput.readSymbol();
     ppmWidth = (int)ppmInput.readNumber();
     ppmHeight = (int)ppmInput.readNumber();
     // Everything but a PBM will have a max color value
     if (ppmType != "P2") {
         maxColor = ppmInput.readNumber();
     } else {
         maxColor = 255;
     }
     if ((ppmWidth < 0) ||
         (ppmHeight < 0) ||
         (maxColor <= 0)) {
         throw GImage::Error("Invalid PPM Header.", input.getFilename());
     }
     // I don't think it's proper to scale values less than 255
     if (maxColor <= 255.0) {
         maxColor = 255.0;
     }
     m_width = ppmWidth;
     m_height = ppmHeight;
     m_channels = 3;
     // always scale down to 1 byte per channel
     m_byte = (uint8*)m_memMan->alloc(m_width * m_height * 3);
     // Read in the image data.  I am not validating if the values match the maxColor
     // requirements.  I only scale if needed to fit within the byte available.
     for (uint32 i = 0; i < (uint32)(m_width * m_height); ++i) {
         // read in color and scale to max pixel defined in header
         // A max color less than 255 might need to be left alone and not scaled.
         Color3uint8& curPixel = *(pixel3() + i);
         if (ppmType == "P3") {
             curPixel.r = (uint8)(ppmInput.readNumber() * (255.0 / maxColor));
             curPixel.g = (uint8)(ppmInput.readNumber() * (255.0 / maxColor));
             curPixel.b = (uint8)(ppmInput.readNumber() * (255.0 / maxColor));
         } else if (ppmType == "P2") {
             uint8 pixel = (uint8)(ppmInput.readNumber() * (255.0 / maxColor));
             curPixel.r = pixel;
             curPixel.g = pixel;
             curPixel.b = pixel;
         } else if (ppmType == "P1") {
             int pixel = (uint8)(ppmInput.readNumber() * maxColor);
             curPixel.r = pixel;
             curPixel.g = pixel;
             curPixel.b = pixel;
         }
     }
 }
References G3D::Color3uint8::b, G3D::TextInput::Settings::cppLineComments, Acore::Error(), G3D::TextInput::FROM_STRING, G3D::Color3uint8::g, G3D::BinaryInput::getFilename(), m_byte, m_channels, m_height, m_memMan, m_width, G3D::TextInput::Settings::otherCommentCharacter, pixel3(), G3D::Color3uint8::r, G3D::TextInput::readNumber(), G3D::BinaryInput::readString(), G3D::TextInput::readSymbol(), G3D::TextInput::Settings::signedNumbers, and G3D::TextInput::Settings::singleQuotedStrings.
Referenced by decode().
decodeTGA()
void G3D::GImage::decodeTGA (BinaryInput & input) private
Definition at line 112 of file GImage_tga.cpp.
{
     // This is a simple TGA loader that can handle uncompressed
     // truecolor TGA files (TGA type 2).
     // Verify this is a TGA file by looking for the TRUEVISION tag.
     int pos = input.getPosition();
     input.setPosition(input.size() - 18);
     std::string tag = input.readString(16);
     if (tag != "TRUEVISION-XFILE") {
         throw Error("Not a TGA file", input.getFilename());
     }
     input.setPosition(pos);
     int IDLength     = input.readUInt8();
     int colorMapType = input.readUInt8();
     int imageType    = input.readUInt8();
     (void)colorMapType;
     // 2 is the type supported by this routine.
     if (imageType != 2 && imageType != 10) {
         throw Error("TGA images must be type 2 (Uncompressed truecolor) or 10 (Run-length truecolor)", input.getFilename());
     }
     // Color map specification
     input.skip(5);
     // Image specification
     // Skip x and y offsets
     input.skip(4);
     m_width  = input.readInt16();
     m_height = input.readInt16();
     int colorDepth = input.readUInt8();
     if ((colorDepth != 24) && (colorDepth != 32)) {
         throw Error("TGA files must be 24 or 32 bit.", input.getFilename());
     }
     if (colorDepth == 32) {
         m_channels = 4;
     } else {
         m_channels = 3;
     }
     // Image descriptor contains overlay data as well
     // as data indicating where the origin is
     int imageDescriptor = input.readUInt8();
     (void)imageDescriptor;
     // Image ID
     input.skip(IDLength);
     m_byte = (uint8*)m_memMan->alloc(m_width * m_height * m_channels);
     debugAssert(m_byte);
     // Pixel data
     int x;
     int y;
     if (imageType == 2) {
         // Uncompressed
         if (m_channels == 3) {
             for (y = m_height - 1; y >= 0; --y) {
               for (x = 0; x < m_width; ++x) {
                 int i = (x + y * m_width) * 3;
                 readBGR(m_byte + i, input);
               }
             }
         } else {
             for (y = m_height - 1; y >= 0; --y) {
               for (x = 0; x < m_width; ++x) {
                  int i = (x + y * m_width) * 4;
                  readBGRA(m_byte + i, input);
               }
             }
         }
     } else if (imageType == 10) {
         // Run-length encoded
         for (y = m_height - 1; y >= 0; --y) {
             for (int x = 0; x < m_width; /* intentionally no x increment */) {
                 // The specification guarantees that no packet will wrap past the end of a row
                 const uint8 repetitionCount = input.readUInt8();
                 const uint8 numValues = (repetitionCount & (~128)) + 1;
                 int byteOffset = (x + y * m_width) * 3;
                 if (repetitionCount & 128) {
                     // When the high bit is 1, this is a run-length packet
                     if (m_channels == 3) {
                         Color3uint8 value;
                         readBGR((uint8*)(&value), input);
                         for (int i = 0; i < numValues; ++i, ++x) {
                             for (int b = 0; b < 3; ++b, ++byteOffset) {
                                 m_byte[byteOffset] = value[b];
                             }
                         }
                     } else {
                         Color4uint8 value;
                         readBGRA((uint8*)(&value), input);
                         for (int i = 0; i < numValues; ++i, ++x) {
                             for (int b = 0; b < 3; ++b, ++byteOffset) {
                                 m_byte[byteOffset] = value[b];
                             }
                         }
                     }
                 } else {
                     // When the high bit is 0, this is a raw packet
                     for (int i = 0; i < numValues; ++i, ++x, byteOffset += m_channels) {
                         readBGR(m_byte + byteOffset, input);
                     }
                 }
             }
         }
     } else {
         alwaysAssertM(false, "Unsupported type");
     }
 }
References alwaysAssertM, b, debugAssert, Acore::Error(), G3D::BinaryInput::getFilename(), G3D::BinaryInput::getPosition(), m_byte, m_channels, m_height, m_memMan, m_width, pos(), G3D::readBGR(), G3D::readBGRA(), G3D::BinaryInput::readInt16(), G3D::BinaryInput::readString(), G3D::BinaryInput::readUInt8(), G3D::BinaryInput::setPosition(), G3D::BinaryInput::size(), G3D::BinaryInput::skip(), G3D::x, and G3D::y.
Referenced by decode().
encode() [1/2]
void G3D::GImage::encode (Format format, BinaryOutput & out) const
Does not commit the BinaryOutput when done.
Definition at line 802 of file GImage.cpp.
{
     switch (format) {
     case PPM_ASCII:
         encodePPMASCII(out);
         break;
     case PPM_BINARY:
         encodePPM(out);
         break;
     case PNG:
         encodePNG(out);
         break;
     case JPEG:
         encodeJPEG(out);
         break;
     case BMP:
         encodeBMP(out);
         break;
     case TGA:
         encodeTGA(out);
         break;
     default:
         debugAssert(false);
     }
 }
References BMP, debugAssert, encodeBMP(), encodeJPEG(), encodePNG(), encodePPM(), encodePPMASCII(), encodeTGA(), G3D::format(), JPEG, PNG, PPM_ASCII, PPM_BINARY, and TGA.
encode() [2/2]
void G3D::GImage::encode (Format format, uint8 *& outData, int & outLength) const
The caller must delete the returned buffer. TODO: provide a memory manager
Definition at line 785 of file GImage.cpp.
{
     BinaryOutput out;
     encode(format, out);
     outData = (uint8*)System::malloc(out.size());
     debugAssert(outData);
     outLength = out.size();
     out.commit(outData);
 }
References G3D::BinaryOutput::commit(), debugAssert, G3D::format(), G3D::System::malloc(), and G3D::BinaryOutput::size().
Referenced by save().
encodeBMP()
void G3D::GImage::encodeBMP (BinaryOutput & out) const private
Definition at line 22 of file GImage_bmp.cpp.
{
     debugAssert(m_channels == 1 || m_channels == 3);
     out.setEndian(G3D_LITTLE_ENDIAN);
     uint8 red;
     uint8 green;
     uint8 blue;
     int pixelBufferSize = m_width * m_height * 3;
     int fileHeaderSize = 14;
     int infoHeaderSize = 40;
     int BMScanWidth;
     int BMPadding;
     // First write the BITMAPFILEHEADER
     //
     //  WORD    bfType;
     //  DWORD   bfSize;
     //  WORD    bfReserved1;
     //  WORD    bfReserved2;
     //  DWORD   bfOffBits;
     // Type
     out.writeUInt8('B');
     out.writeUInt8('M');
     // File size
     out.writeUInt32(fileHeaderSize + infoHeaderSize + pixelBufferSize);
     // Two reserved fields set to zero
     out.writeUInt16(0);
     out.writeUInt16(0);
     // The offset, in bytes, from the BITMAPFILEHEADER structure
     // to the bitmap bits.
     out.writeUInt32(infoHeaderSize + fileHeaderSize);
     // Now the BITMAPINFOHEADER
     //
     //  DWORD  biSize;
     //  LONG   biWidth;
     //  LONG   biHeight;
     //  WORD   biPlanes;
     //  WORD   biBitCount
     //  DWORD  biCompression;
     //  DWORD  biSizeImage;
     //  LONG   biXPelsPerMeter;
     //  LONG   biYPelsPerMeter;
     //  DWORD  biClrUsed;
     //  DWORD  biClrImportant;
     // Size of the info header
     out.writeUInt32(infoHeaderSize);
     // Width and height of the image
     out.writeUInt32(m_width);
     out.writeUInt32(m_height);
     // Planes ("must be set to 1")
     out.writeUInt16(1);
     // BitCount and CompressionType
     out.writeUInt16(24);
     out.writeUInt32(BI_RGB);
     // Image size ("may be zero for BI_RGB bitmaps")
     out.writeUInt32(0);
     // biXPelsPerMeter
     out.writeUInt32(0);
     // biYPelsPerMeter
     out.writeUInt32(0);
     // biClrUsed
     out.writeUInt32(0);
     // biClrImportant
     out.writeUInt32(0);
     BMScanWidth = m_width * 3;
     if (BMScanWidth & 3) {
         BMPadding = 4 - (BMScanWidth & 3);
     } else {
         BMPadding = 0;
     }
     int hStart = m_height - 1;
     int hEnd   = -1;
     int hDir   = -1;
     int dest;
     // Write the pixel data
     for (int h = hStart; h != hEnd; h += hDir) {
         dest = m_channels * h * m_width;
         for (int w = 0; w < m_width; ++w) {
             if (m_channels == 3) {
                 red   = m_byte[dest];
                 green = m_byte[dest + 1];
                 blue  = m_byte[dest + 2];
             } else {
                 red   = m_byte[dest];
                 green = m_byte[dest];
                 blue  = m_byte[dest];
             }
             out.writeUInt8(blue);
             out.writeUInt8(green);
             out.writeUInt8(red);
             dest += m_channels;
         }
         if (BMPadding > 0) {
             out.skip(BMPadding);
         }
     }
 }
References G3D::BI_RGB, blue, debugAssert, G3D::G3D_LITTLE_ENDIAN, green, m_byte, m_channels, m_height, m_width, red, G3D::BinaryOutput::setEndian(), G3D::BinaryOutput::skip(), G3D::BinaryOutput::writeUInt16(), G3D::BinaryOutput::writeUInt32(), and G3D::BinaryOutput::writeUInt8().
Referenced by encode().
encodeJPEG()
void G3D::GImage::encodeJPEG (BinaryOutput & out) const private
Converts this image into a JPEG
Definition at line 249 of file GImage_jpeg.cpp.
{
     if (m_channels != 3) {
         // Convert to three channel
         GImage tmp = *this;
         tmp.convertToRGB();
         tmp.encodeJPEG(out);
         return;
     }
     debugAssert(m_channels == 3);
     out.setEndian(G3D_LITTLE_ENDIAN);
     // Allocate and initialize a compression object
     jpeg_compress_struct    cinfo;
     jpeg_error_mgr          jerr;
     cinfo.err = jpeg_std_error(&jerr);
     jpeg_create_compress(&cinfo);
     // Specify the destination for the compressed data.
     // (Overestimate the size)
     int buffer_size = m_width * m_height * 3 + 200;
     JOCTET* compressed_data = (JOCTET*)System::malloc(buffer_size);
     jpeg_memory_dest(&cinfo, compressed_data, buffer_size);
     cinfo.image_width       = m_width;
     cinfo.image_height      = m_height;
     // # of color components per pixel
     cinfo.input_components  = 3;
     // colorspace of input image
     cinfo.in_color_space    = JCS_RGB;
     cinfo.input_gamma       = 1.0;
     // Set parameters for compression, including image size & colorspace
     jpeg_set_defaults(&cinfo);
     jpeg_set_quality(&cinfo, jpegQuality, false);
     cinfo.smoothing_factor = 0;
     cinfo.optimize_coding = TRUE;
 //    cinfo.dct_method = JDCT_FLOAT;
     cinfo.dct_method = JDCT_ISLOW;
     cinfo.jpeg_color_space = JCS_YCbCr;
     // Initialize the compressor
     jpeg_start_compress(&cinfo, TRUE);
     // Iterate over all scanlines from top to bottom
     // pointer to a single row
     JSAMPROW row_pointer[1];
     // JSAMPLEs per row in image_buffer
     int row_stride = cinfo.image_width * 3;
     while (cinfo.next_scanline < cinfo.image_height) {
         row_pointer[0] = &(m_byte[cinfo.next_scanline * row_stride]);
         jpeg_write_scanlines(&cinfo, row_pointer, 1);
     }
     // Shut down the compressor
     jpeg_finish_compress(&cinfo);
     // Figure out how big the result was.
     int outLength = ((mem_dest_ptr)cinfo.dest)->count;
     //  Release the JPEG compression object
     jpeg_destroy_compress(&cinfo);
     // Copy into an appropriately sized output buffer.
     out.writeBytes(compressed_data, outLength);
     // Free the conservative buffer.
     System::free(compressed_data);
     compressed_data = NULL;
 }
References convertToRGB(), debugAssert, encodeJPEG(), G3D::System::free(), G3D::G3D_LITTLE_ENDIAN, G3D::jpeg_memory_dest(), G3D::jpegQuality, m_byte, m_channels, m_height, m_width, G3D::System::malloc(), NULL, G3D::BinaryOutput::setEndian(), TRUE, and G3D::BinaryOutput::writeBytes().
Referenced by encode(), and encodeJPEG().
encodePNG()
void G3D::GImage::encodePNG (BinaryOutput & out) const private
Converts this image into a JPEG
Definition at line 71 of file GImage_png.cpp.
{
     if (! (m_channels == 1 || m_channels == 3 || m_channels == 4)) {
         throw GImage::Error(format("Illegal channels for PNG: %d", m_channels), out.getFilename());
     }
     if (m_width <= 0) {
         throw GImage::Error(format("Illegal width for PNG: %d", m_width), out.getFilename());
     }
     if (m_height <= 0) {
         throw GImage::Error(format("Illegal height for PNG: %d", m_height), out.getFilename());
     }
     // PNG library requires that the height * pointer size fit within an int
     if (png_uint_32(m_height) * png_sizeof(png_bytep) > PNG_UINT_32_MAX) {
         throw GImage::Error("Unsupported PNG height.", out.getFilename());
     }
     out.setEndian(G3D_LITTLE_ENDIAN);
     png_structp png_ptr = png_create_write_struct(PNG_LIBPNG_VER_STRING, NULL, png_error, png_warning);
     if (! png_ptr) {
         throw GImage::Error("Unable to initialize PNG encoder.", out.getFilename());
     }
     png_infop info_ptr = png_create_info_struct(png_ptr);
     if (! info_ptr) {
         png_destroy_write_struct(&png_ptr, &info_ptr);
         throw GImage::Error("Unable to initialize PNG encoder.", out.getFilename());
     }
     //setup libpng write handler so can use BinaryOutput
     png_set_write_fn(png_ptr, (void*)&out, png_write_data, png_flush_data);
     png_color_8_struct sig_bit;
     switch (m_channels) {
     case 1:
         png_set_IHDR(png_ptr, info_ptr, m_width, m_height, 8, PNG_COLOR_TYPE_GRAY,
             PNG_INTERLACE_NONE, PNG_COMPRESSION_TYPE_BASE, PNG_FILTER_TYPE_BASE);
         sig_bit.red = 0;
         sig_bit.green = 0;
         sig_bit.blue = 0;
         sig_bit.alpha = 0;
         sig_bit.gray = 8;
         break;
     case 3:
         png_set_IHDR(png_ptr, info_ptr, m_width, m_height, 8, PNG_COLOR_TYPE_RGB,
             PNG_INTERLACE_NONE, PNG_COMPRESSION_TYPE_BASE, PNG_FILTER_TYPE_BASE);
         sig_bit.red = 8;
         sig_bit.green = 8;
         sig_bit.blue = 8;
         sig_bit.alpha = 0;
         sig_bit.gray = 0;
         break;
     case 4:
         png_set_IHDR(png_ptr, info_ptr, m_width, m_height, 8, PNG_COLOR_TYPE_RGBA,
             PNG_INTERLACE_NONE, PNG_COMPRESSION_TYPE_BASE, PNG_FILTER_TYPE_BASE);
         sig_bit.red = 8;
         sig_bit.green = 8;
         sig_bit.blue = 8;
         sig_bit.alpha = 8;
         sig_bit.gray = 0;
         break;
     default:
         png_destroy_write_struct(&png_ptr, &info_ptr);
         throw GImage::Error("Unsupported number of channels for PNG.", out.getFilename());
     }
     png_set_sBIT(png_ptr, info_ptr, &sig_bit);
     //write the png header
     png_write_info(png_ptr, info_ptr);
     png_bytepp row_pointers = new png_bytep[m_height];
     for (int i=0; i < m_height; ++i) {
         row_pointers[i] = (png_bytep)&m_byte[m_width * m_channels * i];
     }
     png_write_image(png_ptr, row_pointers);
     png_write_end(png_ptr, info_ptr);
     delete[] row_pointers;
     png_destroy_write_struct(&png_ptr, &info_ptr);
 }
References Acore::Error(), G3D::format(), G3D::G3D_LITTLE_ENDIAN, G3D::BinaryOutput::getFilename(), m_byte, m_channels, m_height, m_width, NULL, G3D::png_error(), G3D::png_flush_data(), G3D::png_warning(), G3D::png_write_data(), and G3D::BinaryOutput::setEndian().
Referenced by encode().
encodePPM()
void G3D::GImage::encodePPM (BinaryOutput & out) const private
Definition at line 61 of file GImage_ppm.cpp.
{
     // http://netpbm.sourceforge.net/doc/ppm.html
     if (m_channels == 3) {
         std::string header = format("P6 %d %d 255 ", m_width, m_height);
         out.writeBytes(header.c_str(), header.size());
         out.writeBytes(this->pixel3(), m_width * m_height * 3);
     } else if (m_channels == 1) {
         std::string header = format("P5 %d %d 255 ", m_width, m_height);
         out.writeBytes(header.c_str(), header.size());
         out.writeBytes(this->pixel1(), m_width * m_height);
     } else {
         alwaysAssertM(false, "PPM requires either 1 or 3 channels exactly.");
     }
 }
References alwaysAssertM, G3D::format(), m_channels, m_height, m_width, pixel1(), pixel3(), and G3D::BinaryOutput::writeBytes().
Referenced by encode().
encodePPMASCII()
void G3D::GImage::encodePPMASCII (BinaryOutput & out) const private
Definition at line 17 of file GImage_ppm.cpp.
{
     TextOutput::Settings ppmOptions;
     ppmOptions.convertNewlines = false;
     ppmOptions.numColumns = 70;
     ppmOptions.wordWrap = TextOutput::Settings::WRAP_WITHOUT_BREAKING;
     TextOutput ppm(ppmOptions);
     switch (m_channels) {
     case 1:
         {
             ppm.printf("P2\n%d %d\n255\n", m_width, m_height);
             const Color1uint8* c = this->pixel1();
             // Insert newlines every 70 characters max
             for (uint32 i = 0; i < (uint32)(m_width * m_height); ++i) {
                 ppm.printf("%d%c", c[i].value, (i % (70/4) == 0) ? '\n' : ' ');
             }
         }
         break;
     case 3:
         {
             ppm.printf("P3\n%d %d\n255\n", m_width, m_height);
             const Color3uint8* c = this->pixel3();
             // Insert newlines every 70 characters max
             for (uint32 i = 0; i < (uint32)(m_width * m_height); ++i) {
                 ppm.printf("%d %d %d%c", c[i].r, c[i].g, c[i].b,
                     (i % (70/12) == 0) ?
                     '\n' : ' ');
             }
         }
         break;
     default:
         alwaysAssertM(false, "PPM requires either 1 or 3 channels exactly.");
     }
     const std::string& s = ppm.commitString();
     out.writeBytes(s.c_str(), s.length());
 }
References alwaysAssertM, b, mpq::c, G3D::TextOutput::commitString(), G3D::TextOutput::Settings::convertNewlines, m_channels, m_height, m_width, G3D::TextOutput::Settings::numColumns, pixel1(), pixel3(), G3D::TextOutput::printf(), G3D::TextOutput::Settings::wordWrap, G3D::TextOutput::Settings::WRAP_WITHOUT_BREAKING, and G3D::BinaryOutput::writeBytes().
Referenced by encode().
encodeTGA()
void G3D::GImage::encodeTGA (BinaryOutput & out) const private
The TGA file will be either 24- or 32-bit depending on the number of channels.
Definition at line 15 of file GImage_tga.cpp.
{
     out.setEndian(G3D_LITTLE_ENDIAN);
     // ID length
     out.writeUInt8(0);
     // Color map Type
     out.writeUInt8(0);
     // Type
     out.writeUInt8(2);
     // Color map
     out.skip(5);
     // x, y offsets
     out.writeUInt16(0);
     out.writeUInt16(0);
     // Width & height
     out.writeUInt16(m_width);
     out.writeUInt16(m_height);
     // Color depth
     if (m_channels == 1) {
         // Force RGB mode
         out.writeUInt8(8 * 3);
     } else {
         out.writeUInt8(8 * m_channels);
     }
     // Image descriptor
     if (m_channels < 4) {
         // 0 alpha bits
         out.writeUInt8(0);
     } else {
         // 8 alpha bits
         out.writeUInt8(8);
     }
     // Image ID (zero length)
     if (m_channels == 1) {
         // Pixels are upside down in BGR format.
         for (int y = m_height - 1; y >= 0; --y) {
             for (int x = 0; x < m_width; ++x) {
                 uint8 p = (m_byte[(y * m_width + x)]);
                 out.writeUInt8(p);
                 out.writeUInt8(p);
                 out.writeUInt8(p);
             }
         }
     } else if (m_channels == 3) {
         // Pixels are upside down in BGR format.
         for (int y = m_height - 1; y >= 0; --y) {
             for (int x = 0; x < m_width; ++x) {
                 uint8* p = &(m_byte[3 * (y * m_width + x)]);
                 out.writeUInt8(p[2]);
                 out.writeUInt8(p[1]);
                 out.writeUInt8(p[0]);
             }
         }
     } else {
         // Pixels are upside down in BGRA format.
         for (int y = m_height - 1; y >= 0; --y) {
             for (int x = 0; x < m_width; ++x) {
                 uint8* p = &(m_byte[4 * (y * m_width + x)]);
                 out.writeUInt8(p[2]);
                 out.writeUInt8(p[1]);
                 out.writeUInt8(p[0]);
                 out.writeUInt8(p[3]);
             }
         }
     }
     // Write "TRUEVISION-XFILE " 18 bytes from the end
     // (with null termination)
     out.writeString("TRUEVISION-XFILE ");
 }
References G3D::G3D_LITTLE_ENDIAN, m_byte, m_channels, m_height, m_width, G3D::BinaryOutput::setEndian(), G3D::BinaryOutput::skip(), G3D::BinaryOutput::writeString(), G3D::BinaryOutput::writeUInt16(), G3D::BinaryOutput::writeUInt8(), G3D::x, and G3D::y.
Referenced by encode().
flipHorizontal()
void G3D::GImage::flipHorizontal ()
Definition at line 603 of file GImage.cpp.
{
     uint8 temp[4];
     int rowBytes = m_width * m_channels;
     for (int y = 0; y < m_height; ++y) {
         uint8* row = m_byte + y * rowBytes;
         for (int x = 0; x < m_width / 2; ++x) {
             System::memcpy(temp, row + x * m_channels, m_channels);
             System::memcpy(row + x * m_channels, row + (m_width - x - 1) * m_channels, m_channels);
             System::memcpy(row + (m_width - x - 1) * m_channels, temp, m_channels);
         }
     }
 }
References m_byte, m_channels, m_height, m_width, G3D::System::memcpy(), G3D::x, and G3D::y.
flipRGBAVertical()
void G3D::GImage::flipRGBAVertical (const uint8 * in, uint8 * out, int width, int height) static
Definition at line 200 of file GImage.cpp.
{
     // Allocate a temp row so the operation
     // is still safe if in == out
     uint8* temp = (uint8*)System::malloc(width * 4);
     alwaysAssertM(temp != NULL, "Out of memory");
     int oneRow = width * 4;
     // if height is an odd value, don't swap odd middle row
     for (int i = 0; i < height / 2; ++i) {
         int topOff = i * oneRow;
         int botOff = (height - i - 1) * oneRow;
         System::memcpy(temp,         in + topOff, oneRow);
         System::memcpy(out + topOff, in + botOff, oneRow);
         System::memcpy(out + botOff, temp,        oneRow);
     }
     System::free(temp);
 }
References alwaysAssertM, G3D::System::free(), height(), G3D::System::malloc(), G3D::System::memcpy(), NULL, and width().
flipRGBVertical()
void G3D::GImage::flipRGBVertical (const uint8 * in, uint8 * out, int width, int height) static
Flips the image along the vertical axis. Safe for in == out.
Definition at line 172 of file GImage.cpp.
{
     // Allocate a temp row so the operation
     // is still safe if in == out
     uint8* temp = (uint8*)System::malloc(width * 3);
     alwaysAssertM(temp != NULL, "Out of memory");
     int oneRow = width * 3;
     int N = height / 2;
     // if height is an odd value, don't swap odd middle row
     for (int i = 0; i < N; ++i) {
         int topOff = i * oneRow;
         int botOff = (height - i - 1) * oneRow;
         System::memcpy(temp,         in + topOff, oneRow);
         System::memcpy(out + topOff, in + botOff, oneRow);
         System::memcpy(out + botOff, temp,        oneRow);
     }
     System::free(temp);
 }
References alwaysAssertM, G3D::System::free(), height(), G3D::System::malloc(), G3D::System::memcpy(), NULL, and width().
flipVertical()
void G3D::GImage::flipVertical ()
Definition at line 617 of file GImage.cpp.
{
     uint8* old = m_byte;
     m_byte = (uint8*)m_memMan->alloc(m_width * m_height * m_channels);
     // We could do this with only a single-row temp buffer, but then
     // we'd have to copy twice as much data.
     int rowBytes = m_width * m_channels;
     for (int y = 0; y < m_height; ++y) {
         System::memcpy(m_byte + y * rowBytes, old + (m_height - y - 1) * rowBytes, rowBytes);
     }
     m_memMan->free(old);
 }
References m_byte, m_channels, m_height, m_memMan, m_width, G3D::System::memcpy(), and G3D::y.
height()
int G3D::GImage::height () const inline
Definition at line 129 of file GImage.h.
{
         return m_height;
     }
References m_height.
Referenced by BAYER_G8B8_R8G8_to_Quarter_R8G8B8(), computeNormalMap(), G3D::Image1uint8::copyGImage(), G3D::Image3uint8::copyGImage(), G3D::Image4uint8::copyGImage(), flipRGBAVertical(), flipRGBVertical(), G3D::Image1uint8::fromGImage(), G3D::Image3uint8::fromGImage(), G3D::Image4uint8::fromGImage(), GImage(), insertRedAsAlpha(), R8G8B8_to_Y8U8V8(), resize(), and Y8U8V8_to_R8G8B8().
insertRedAsAlpha()
void G3D::GImage::insertRedAsAlpha (const GImage & alpha, GImage & output) const
Returns a new GImage that has 4 channels. RGB is taken from this GImage and the alpha from the red channel of the supplied image. The new GImage is passed as a reference parameter for speed.
Definition at line 837 of file GImage.cpp.
{
     debugAssert(alpha.width() == width());
     debugAssert(alpha.height() == height());
     // make sure output GImage is valid
     if (output.width() != width() || output.height() != height() || output.channels() != 4) {
         output.resize(width(), height(), 4);
     }
     int N = m_width * m_height;
     for (int i = 0; i < N; ++i) {
         output.byte()[i * 4 + 0] = byte()[i * m_channels + 0];
         output.byte()[i * 4 + 1] = byte()[i * m_channels + 1];
         output.byte()[i * 4 + 2] = byte()[i * m_channels + 2];
         output.byte()[i * 4 + 3] = alpha.byte()[i * alpha.m_channels];
     }
 }
References byte(), channels(), debugAssert, height(), m_channels, m_height, m_width, resize(), and width().
load()
void G3D::GImage::load (const std::string & filename, Format format = AUTODETECT)
Loads an image from disk (clearing the old one first), using the existing memory manager.
Definition at line 507 of file GImage.cpp.
{
     clear();
     try {
         BinaryInput b(filename, G3D_LITTLE_ENDIAN);
         if (b.size() <= 0) {
             throw Error("File not found.", filename);
         }
         alwaysAssertM(this != NULL, "Corrupt GImage");
         decode(b, resolveFormat(filename, b.getCArray(), b.size(), format));
     } catch (const std::string& error) {
         throw Error(error, filename);
     }
 }
References alwaysAssertM, b, clear(), decode(), error(), Acore::Error(), G3D::format(), G3D::G3D_LITTLE_ENDIAN, NULL, and resolveFormat().
Referenced by GImage().
LtoRGB()
void G3D::GImage::LtoRGB (const uint8 * in, uint8 * out, int numPixels) static
Definition at line 51 of file GImage.cpp.
{
     for (int i = 0; i < numPixels; ++i) {
         int v = in[i];
         int i3 = i * 3;
         out[i3 + 0] = v;
         out[i3 + 1] = v;
         out[i3 + 2] = v;
     }
 }
LtoRGBA()
void G3D::GImage::LtoRGBA (const uint8 * in, uint8 * out, int numPixels) static
Definition at line 34 of file GImage.cpp.
{
     for (int i = 0; i < numPixels; ++i) {
         int v = in[i];
         int i4 = i * 4;
         out[i4 + 0] = v;
         out[i4 + 1] = v;
         out[i4 + 2] = v;
         out[i4 + 3] = 255;
     }
 }
makeCheckerboard()
void G3D::GImage::makeCheckerboard (GImage & im, int checkerSize = 1, const Color4uint8 & color1 = Color4uint8(255,255,255,255), const Color4uint8 & color2 = Color4uint8(0,0,0,255)) static
Overwrites every pixel with one of the two colors in a checkerboard pattern. The fields used from the two colors depend on the current number of channels in im.
Definition at line 1152 of file GImage.cpp.
{
     for (int y = 0; y < im.m_height; ++y) {
         for (int x = 0; x < im.m_width; ++x) {
             bool checker = isOdd((x / checkerSize) + (y / checkerSize));
             const Color4uint8& color = checker ? A : B;
             for (int c = 0; c < im.m_channels; ++c) {
                 uint8* v = im.byte() + (x + y * im.m_width) * im.m_channels + c;
                 *v = color[c];
             }
         }
     }
 }
References byte(), mpq::c, G3D::isOdd(), m_channels, m_height, m_width, G3D::x, and G3D::y.
operator=()
GImage & G3D::GImage::operator= (const GImage & other)
Definition at line 687 of file GImage.cpp.
{
     _copy(other);
     return *this;
 }
References _copy().
pasteSubImage()
bool G3D::GImage::pasteSubImage (GImage & dest, const GImage & src, int destX, int destY, int srcX, int srcY, int srcWidth, int srcHeight) static
Copies src sub-image data into dest at a certain offset.
The dest variable must already contain an image that is large enough to contain the src sub-image at the specified offset. Returns true on success and false if the src sub-image cannot completely fit within dest at the specified offset. Both src and dest must have the same number of channels.
Definition at line 714 of file GImage.cpp.
{
     if ((src.m_width < srcX + srcWidth) ||
         (src.m_height < srcY + srcHeight) ||
         (dest.m_width < destX + srcWidth) ||
         (dest.m_height < destY + srcHeight) ||
         (srcY < 0) ||
         (srcX < 0) ||
         (destY < 0) ||
         (destX < 0) ||
         (src.channels() != dest.channels())) {
         return false;
     }
     for (int i = 0; i < srcHeight; i++) {
         const uint8* srcRow = src.byte() +
             ((i + srcY) * src.m_width + srcX) * src.channels();
         uint8* destRow = dest.byte() +
             ((i + destY) * dest.width() + destX) * dest.channels();
         memcpy(destRow, srcRow, srcWidth * src.m_channels);
     }
     return true;
 }
References byte(), channels(), m_channels, m_height, m_width, memcpy, and width().
Referenced by copySubImage().
pixel1() [1/4]
Color1uint8* G3D::GImage::pixel1 () inline
Definition at line 157 of file GImage.h.
{
         debugAssertM(m_channels == 1, format("Tried to call GImage::pixel1 on an image with %d channels", m_channels));
         return (Color1uint8*)m_byte;
     }
References debugAssertM, G3D::format(), m_byte, and m_channels.
pixel1() [2/4]
const Color1uint8* G3D::GImage::pixel1 () const inline
Definition at line 152 of file GImage.h.
{
         debugAssertM(m_channels == 1, format("Tried to call GImage::pixel1 on an image with %d channels", m_channels));
         return (Color1uint8*)m_byte;
     }
References debugAssertM, G3D::format(), m_byte, and m_channels.
Referenced by G3D::Image1uint8::copyGImage(), G3D::Image3uint8::copyGImage(), G3D::Image4uint8::copyGImage(), encodePPM(), encodePPMASCII(), G3D::Image1uint8::fromGImage(), G3D::Image3uint8::fromGImage(), G3D::Image4uint8::fromGImage(), and pixel1().
pixel1() [3/4]
Color1uint8& G3D::GImage::pixel1 (int x, int y) inline
Returns the pixel at (x, y), where (0,0) is the upper left.
Definition at line 196 of file GImage.h.
{
         debugAssert(x >= 0 && x < m_width);
         debugAssert(y >= 0 && y < m_height);
         return pixel1()[x + y * m_width];
     }
References debugAssert, m_height, m_width, pixel1(), G3D::x, and G3D::y.
pixel1() [4/4]
const Color1uint8& G3D::GImage::pixel1 (int x, int y) const inline
Returns the pixel at (x, y), where (0,0) is the upper left.
Definition at line 189 of file GImage.h.
{
         debugAssert(x >= 0 && x < m_width);
         debugAssert(y >= 0 && y < m_height);
         return pixel1()[x + y * m_width];
     }
References debugAssert, m_height, m_width, pixel1(), G3D::x, and G3D::y.
pixel3() [1/4]
Color3uint8* G3D::GImage::pixel3 () inline
Definition at line 183 of file GImage.h.
{
         debugAssert(m_channels == 3);
         return (Color3uint8*)m_byte;
     }
References debugAssert, m_byte, and m_channels.
pixel3() [2/4]
const Color3uint8* G3D::GImage::pixel3 () const inline
Returns a pointer to the upper left pixel as Color3uint8.
Definition at line 178 of file GImage.h.
{
          debugAssertM(m_channels == 3, format("Tried to call GImage::pixel3 on an image with %d channels", m_channels));
          return (Color3uint8*)m_byte;
     }
References debugAssertM, G3D::format(), m_byte, and m_channels.
Referenced by G3D::Image1uint8::copyGImage(), G3D::Image3uint8::copyGImage(), G3D::Image4uint8::copyGImage(), decodePCX(), decodePPMASCII(), encodePPM(), encodePPMASCII(), G3D::Image1uint8::fromGImage(), G3D::Image3uint8::fromGImage(), G3D::Image4uint8::fromGImage(), and pixel3().
pixel3() [3/4]
Color3uint8& G3D::GImage::pixel3 (int x, int y) inline
Definition at line 209 of file GImage.h.
{
         debugAssert(x >= 0 && x < m_width);
         debugAssert(y >= 0 && y < m_height);
         return pixel3()[x + y * m_width];
     }
References debugAssert, m_height, m_width, pixel3(), G3D::x, and G3D::y.
pixel3() [4/4]
const Color3uint8& G3D::GImage::pixel3 (int x, int y) const inline
Returns the pixel at (x, y), where (0,0) is the upper left.
Definition at line 203 of file GImage.h.
{
         debugAssert(x >= 0 && x < m_width);
         debugAssert(y >= 0 && y < m_height);
         return pixel3()[x + y * m_width];
     }
References debugAssert, m_height, m_width, pixel3(), G3D::x, and G3D::y.
pixel4() [1/4]
Color4uint8* G3D::GImage::pixel4 () inline
Definition at line 170 of file GImage.h.
{
         debugAssert(m_channels == 4);
         return (Color4uint8*)m_byte;
     }
References debugAssert, m_byte, and m_channels.
pixel4() [2/4]
const Color4uint8* G3D::GImage::pixel4 () const inline
Returns a pointer to the upper left pixel as Color4uint8.
Definition at line 165 of file GImage.h.
{
         debugAssertM(m_channels == 4, format("Tried to call GImage::pixel4 on an image with %d channels", m_channels));
         return (Color4uint8*)m_byte;
     }
References debugAssertM, G3D::format(), m_byte, and m_channels.
Referenced by computeNormalMap(), G3D::Image1uint8::copyGImage(), G3D::Image3uint8::copyGImage(), G3D::Image4uint8::copyGImage(), decodeICO(), G3D::Image1uint8::fromGImage(), G3D::Image3uint8::fromGImage(), G3D::Image4uint8::fromGImage(), and pixel4().
pixel4() [3/4]
Color4uint8& G3D::GImage::pixel4 (int x, int y) inline
Definition at line 222 of file GImage.h.
{
         debugAssert(x >= 0 && x < m_width);
         debugAssert(y >= 0 && y < m_height);
         return pixel4()[x + y * m_width];
     }
References debugAssert, m_height, m_width, pixel4(), G3D::x, and G3D::y.
pixel4() [4/4]
const Color4uint8& G3D::GImage::pixel4 (int x, int y) const inline
Returns the pixel at (x, y), where (0,0) is the upper left.
Definition at line 216 of file GImage.h.
{
         debugAssert(x >= 0 && x < m_width);
         debugAssert(y >= 0 && y < m_height);
         return pixel4()[x + y * m_width];
     }
References debugAssert, m_height, m_width, pixel4(), G3D::x, and G3D::y.
Quarter_R8G8B8_to_BAYER_G8B8_R8G8()
void G3D::GImage::Quarter_R8G8B8_to_BAYER_G8B8_R8G8 (int inWidth, int inHeight, const uint8 * in, uint8 * out) static
Attempt to undo fast conversion of G3D::BAYER_G8B8_R8G8_to_Quarter_R8G8B8; the green channel will lose data. Assumes in != out The input should have size 3 * inWidth * inHeight. The output should have size 2 * inWidth * 2 * inHeight.
Definition at line 33 of file GImage_bayer.cpp.
{
     // Undo quarter-size Bayer as best we can.  This code isn't very efficient, but it
     // also isn't used very frequently.
     debugAssert(out != in);
     int outWidth  = 2 * inWidth;
     int outHeight = 2 * inHeight;
     for (int y = 0; y < outHeight; ++y) {
         for (int x = 0; x < outWidth; ++x) {
             const Color3uint8* inp = ((const Color3uint8*)in) + ((x/2) + (y/2)* inWidth);
             uint8* outp = out + x + y * outWidth;
             if (isEven(y)) {
                 // GB row
                 if (isEven(x)) {
                     // Green
                     *outp = inp->g;
                 } else {
                     // Blue
                     *outp = inp->b;
                 }
             } else {
                 // RG row
                 if (isEven(x)) {
                     // Red
                     *outp = inp->r;
                 } else {
                     // Green
                     *outp = inp->g;
                 }
             }
         }
     }
 }
References G3D::Color3uint8::b, debugAssert, G3D::Color3uint8::g, G3D::isEven(), G3D::Color3uint8::r, G3D::x, and G3D::y.
R8G8B8_to_Y8U8V8()
void G3D::GImage::R8G8B8_to_Y8U8V8 (int width, int height, const uint8 * in, uint8 * out) static
Ok for in == out
Definition at line 1119 of file GImage.cpp.
{
     const Color3uint8* in = reinterpret_cast<const Color3uint8*>(_in);
     Color3uint8* out = reinterpret_cast<Color3uint8*>(_out);
     Color3uint8 p;
     for (int i = width * height - 1; i >= 0; --i) {
         p.r = iClamp(iRound(in->r *  0.229 + in->g *  0.587 + in->b *  0.114), 0, 255);
         p.g = iClamp(iRound(in->r * -0.147 + in->g * -0.289 + in->b *  0.436) + 127, 0, 255);
         p.b = iClamp(iRound(in->r *  0.615 + in->g * -0.515 + in->b * -0.100) + 127, 0, 255);
         *out = p;
         ++in;
         ++out;
     }
 }
References G3D::Color3uint8::b, G3D::Color3uint8::g, height(), G3D::iClamp(), G3D::iRound(), G3D::Color3uint8::r, and width().
rawData() [1/2]
template<typename Type > Type* G3D::GImage::rawData () inline
Definition at line 148 of file GImage.h.
{
         return (Type*)m_byte;
     }
References m_byte.
rawData() [2/2]
template<typename Type > const Type* G3D::GImage::rawData () const inline
Returns a pointer to the underlying data, which is stored in row-major order without row padding. e.g., uint8* ptr = image.rawData<uint8>();
Definition at line 142 of file GImage.h.
{
         return (Type*)m_byte;
     }
References m_byte.
resize()
void G3D::GImage::resize (int width, int height, int channels, bool zero = true)
Resizes the internal buffer to (width x height) with the number of channels specified.
Parameters
zero If true, all data is set to 0 (black).
Definition at line 561 of file GImage.cpp.
{
     debugAssert(width >= 0);
     debugAssert(height >= 0);
     debugAssert(channels >= 1);
     clear();
     m_width = width;
     m_height = height;
     m_channels = channels;
     size_t sz = width * height * channels;
     if (sz > 0) {
         m_byte = (uint8*)m_memMan->alloc(sz);
         if (zero) {
             System::memset(m_byte, 0, sz);
         }
         debugAssert(isValidHeapPointer(m_byte));
     }
 }
References channels(), clear(), debugAssert, height(), G3D::isValidHeapPointer(), m_byte, m_channels, m_height, m_memMan, m_width, G3D::System::memset(), width(), and G3D::zero().
Referenced by computeNormalMap(), convertToL8(), convertToRGB(), convertToRGBA(), copySubImage(), decodePPM(), GImage(), insertRedAsAlpha(), and stripAlpha().
resolveFormat() [1/2]
GImage::Format G3D::GImage::resolveFormat (const std::string & filename) static
Predicts the image file format of filename
Definition at line 405 of file GImage.cpp.
{
     BinaryInput b(filename, G3D_LITTLE_ENDIAN);
     if (b.size() <= 0) {
         throw Error("File not found.", filename);
     }
     return resolveFormat(filename, b.getCArray(), b.size(), AUTODETECT);
 }
References AUTODETECT, b, Acore::Error(), G3D::G3D_LITTLE_ENDIAN, and resolveFormat().
resolveFormat() [2/2]
GImage::Format G3D::GImage::resolveFormat (const std::string & filename, const uint8 * data, int dataLen, Format maybeFormat) static private
Given [maybe] a filename, memory buffer, and [maybe] a format, returns the most likely format of this file.
Definition at line 415 of file GImage.cpp.
{
     // Return the provided format if it is specified.
     if (maybeFormat != AUTODETECT) {
         return maybeFormat;
     }
     std::string extension = toUpper(filenameExt(filename));
     if ((extension == "PPM") || (extension == "PGM") || (extension == "PBM")) {
         // There are two PPM formats (binary and ASCII); we handle them differently
         if (dataLen > 3) {
             if (!memcmp(data, "P6", 2) || !memcmp(data, "P5", 2)) {
                 return PPM_BINARY;
             } else {
                 return PPM_ASCII;
             }
         }
     }
     Format tmp = stringToFormat(extension);
     if ((tmp != AUTODETECT) && (tmp != UNKNOWN)) {
         return tmp;
     }
     // Try and autodetect from the file itself by looking at the first
     // character.
     // We can't look at the character if it is null.
     debugAssert(data != NULL);
     if ((dataLen > 3) && (! memcmp(data, "P3", 2) || (! memcmp(data, "P2", 2)) || (! memcmp(data, "P1", 2)))) {
         return PPM_ASCII;
     }
     if ((dataLen > 3) && (!memcmp(data, "P6", 2) ||!memcmp(data, "P5", 2))) {
         return PPM_BINARY;
     }
     if (dataLen > 8) {
         if (!png_sig_cmp((png_bytep)data, 0, 8)) {
             return PNG;
         }
     }
     if ((dataLen > 0) && (data[0] == 'B')) {
         return BMP;
     }
     if (dataLen > 10) {
         if ((dataLen > 11) && (data[0] == 0xFF) &&
             (memcmp(&data[6], "JFIF", 4) == 0)) {
             return JPEG;
         }
     }
     if (dataLen > 40) {
         if (memcmp(&data[dataLen - 18], "TRUEVISION-XFILE", 16) == 0) {
             return TGA;
         }
     }
     if ((dataLen > 4) && (data[0] == 0) && (data[1] == 0) && (data[2] == 0) && (data[3] == 1)) {
         return ICO;
     }
     if ((dataLen > 0) && (data[0] == 10)) {
         return PCX;
     }
     return UNKNOWN;
 }
References AUTODETECT, BMP, debugAssert, G3D::filenameExt(), ICO, JPEG, NULL, PCX, PNG, PPM_ASCII, PPM_BINARY, stringToFormat(), TGA, G3D::toUpper(), and UNKNOWN.
Referenced by GImage(), load(), resolveFormat(), and save().
RGBAtoRGB()
void G3D::GImage::RGBAtoRGB (const uint8 * in, uint8 * out, int numPixels) static
Definition at line 84 of file GImage.cpp.
{
     for (int i = 0; i < numPixels; ++i) {
         int i3 = i * 3;
         int i4 = i3 + i;
         out[i3 + 0] = in[i4 + 0];
         out[i3 + 1] = in[i4 + 1];
         out[i3 + 2] = in[i4 + 2];
     }
 }
Referenced by G3D::Image3uint8::copyArray().
RGBtoARGB()
void G3D::GImage::RGBtoARGB (const uint8 * in, uint8 * out, int numPixels) static
Definition at line 155 of file GImage.cpp.
{
     for (int i = 0; i < numPixels; ++i) {
         int i3 = i * 3;
         int i4 = i3 + i;
         out[i4 + 0] = 255;
         out[i4 + 1] = in[i3 + 0];
         out[i4 + 2] = in[i3 + 1];
         out[i4 + 3] = in[i3 + 2];
     }
 }
RGBtoBGR()
void G3D::GImage::RGBtoBGR (const uint8 * in, uint8 * out, int numPixels) static
Safe for in == out
Definition at line 118 of file GImage.cpp.
{
     for (int i = 0; i < numPixels; ++i) {
         int i3 = i * 3;
         int r = in[i3 + 0];
         int g = in[i3 + 1];
         int b = in[i3 + 2];
         out[i3 + 2] = r;
         out[i3 + 1] = g;
         out[i3 + 0] = b;
     }
 }
References b.
RGBtoBGRA()
void G3D::GImage::RGBtoBGRA (const uint8 * in, uint8 * out, int numPixels) static
Win32 32-bit HDC format.
Definition at line 100 of file GImage.cpp.
{
     for (int i = 0; i < numPixels; ++i) {
         int i3 = i * 3;
         int i4 = i3 + i;
         out[i4 + 2] = in[i3 + 0];
         out[i4 + 1] = in[i3 + 1];
         out[i4 + 0] = in[i3 + 2];
         out[i4 + 3] = 255;
     }
 }
RGBtoRGBA()
void G3D::GImage::RGBtoRGBA (const uint8 * in, uint8 * out, int numPixels) static
Parameters
in RGB buffer of numPixels * 3 bytes
out Buffer of numPixels * 4 bytes
numPixels Number of RGB pixels to convert
Definition at line 67 of file GImage.cpp.
{
     for (int i = 0; i < numPixels; ++i) {
         int i3 = i * 3;
         int i4 = i3 + i;
         out[i4 + 0] = in[i3 + 0];
         out[i4 + 1] = in[i3 + 1];
         out[i4 + 2] = in[i3 + 2];
         out[i4 + 3] = 255;
     }
 }
Referenced by G3D::Image4uint8::copyArray().
RGBxRGBtoRGBA()
void G3D::GImage::RGBxRGBtoRGBA (const uint8 * colorRGB, const uint8 * alphaRGB, uint8 * out, int numPixels) static
Uses the red channel of the second image as an alpha channel.
Definition at line 137 of file GImage.cpp.
{
     for (int i = numPixels - 1; i >= 0; --i) {
         int i3 = i * 3;
         int i4 = i3 + i;
         out[i4 + 0] = colorRGB[i3 + 0];
         out[i4 + 1] = colorRGB[i3 + 1];
         out[i4 + 2] = colorRGB[i3 + 2];
         out[i4 + 3] = alphaRGB[i3 + 0];
     }
 }
rotate90CW()
void G3D::GImage::rotate90CW (int numTimes = 1)
Definition at line 632 of file GImage.cpp.
{
     uint8* old = NULL;
     numTimes = iWrap(numTimes, 4);
     if (numTimes > 0) {
         (uint8*)m_memMan->alloc(m_width * m_height * m_channels);
     }
     for (int j = 0; j < numTimes; ++j) {
         {
             uint8* temp = old;
             old = m_byte;
             m_byte = temp;
         }
         {
             int temp = m_width;
             m_width = m_height;
             m_height = temp;
         }
         int rowBytes = m_width * m_channels;
         for (int y = 0; y < m_height; ++y) {
             for (int x = 0; x < m_width; ++x) {
                 uint8* dst = m_byte + x + y * rowBytes;
                 uint8* src = old + y + (m_height - x - 1) * rowBytes;
                 System::memcpy(dst, src, m_channels);
             }
         }
     }
     m_memMan->free(old);
 }
References G3D::iWrap(), m_byte, m_channels, m_height, m_memMan, m_width, G3D::System::memcpy(), NULL, G3D::x, and G3D::y.
save()
void G3D::GImage::save (const std::string & filename, Format format = AUTODETECT) const
Encode and save to disk.
Definition at line 775 of file GImage.cpp.
{
     BinaryOutput b(filename, G3D_LITTLE_ENDIAN);
     encode(resolveFormat(filename, NULL, 0, format), b);
     b.commit(false);
 }
References b, encode(), G3D::format(), G3D::G3D_LITTLE_ENDIAN, NULL, and resolveFormat().
Referenced by G3D::Image1uint8::save(), G3D::Image3uint8::save(), and G3D::Image4uint8::save().
sizeInMemory()
int G3D::GImage::sizeInMemory () const
Returns the size of this object in bytes
Definition at line 871 of file GImage.cpp.
{
     return sizeof(GImage) + m_width * m_height * m_channels;
 }
References GImage(), m_channels, m_height, and m_width.
stringToFormat()
GImage::Format G3D::GImage::stringToFormat (const std::string & format) static
Converts a string to an enum, returns UNKNOWN if not recognized.
Definition at line 751 of file GImage.cpp.
{
     std::string extension = toUpper(format);
     if ((extension == "JPG") || (extension == "JPEG")) {
         return JPEG;
     } else if (extension == "TGA") {
         return TGA;
     } else if (extension == "BMP") {
         return BMP;
     } else if (extension == "PCX") {
         return PCX;
     } else if (extension == "ICO") {
         return ICO;
     } else if (extension == "PNG") {
         return PNG;
     } else {
         return UNKNOWN;
     }
     // Don't put PPM here, since it has two versions
 }
References BMP, G3D::format(), ICO, JPEG, PCX, PNG, TGA, G3D::toUpper(), and UNKNOWN.
Referenced by resolveFormat(), and supportedFormat().
stripAlpha()
void G3D::GImage::stripAlpha (GImage & output) const
Returns a new GImage with 3 channels, removing the alpha channel if there is one. The new GImage is passed as a reference parameter for speed.
Definition at line 856 of file GImage.cpp.
{
     if (output.m_width != m_width || output.m_height != m_height || output.m_channels != 3) {
         output.resize(m_width, m_height, 3);
     }
     int N = m_width * m_height;
     for (int i = 0; i < N; ++i) {
         output.byte()[i * 3 + 0] = byte()[i * m_channels + 0];
         output.byte()[i * 3 + 1] = byte()[i * m_channels + 1];
         output.byte()[i * 3 + 2] = byte()[i * m_channels + 2];
     }
 }
References byte(), m_channels, m_height, m_width, and resize().
supportedFormat()
bool G3D::GImage::supportedFormat (const std::string & format) static
Returns true if format is supported. Format should be an extension string (e.g. "BMP").
Definition at line 744 of file GImage.cpp.
{
     return (stringToFormat(format) != UNKNOWN);
 }
References G3D::format(), stringToFormat(), and UNKNOWN.
width()
int G3D::GImage::width () const inline
Definition at line 125 of file GImage.h.
{
         return m_width;
     }
References m_width.
Referenced by BAYER_G8B8_R8G8_to_Quarter_R8G8B8(), computeNormalMap(), G3D::Image1uint8::copyGImage(), G3D::Image3uint8::copyGImage(), G3D::Image4uint8::copyGImage(), flipRGBAVertical(), flipRGBVertical(), G3D::Image1uint8::fromGImage(), G3D::Image3uint8::fromGImage(), G3D::Image4uint8::fromGImage(), GImage(), insertRedAsAlpha(), pasteSubImage(), R8G8B8_to_Y8U8V8(), resize(), and Y8U8V8_to_R8G8B8().
Y8U8V8_to_R8G8B8()
void G3D::GImage::Y8U8V8_to_R8G8B8 (int width, int height, const uint8 * in, uint8 * out) static
Ok for in == out
Definition at line 1136 of file GImage.cpp.
{
     const Color3uint8* in = reinterpret_cast<const Color3uint8*>(_in);
     Color3uint8* out = reinterpret_cast<Color3uint8*>(_out);
     Color3uint8 p;
     for (int i = width * height - 1; i >= 0; --i) {
         p.r = iClamp(iRound(in->r *  1.0753 +                   (in->b - 127) *  1.2256), 0, 255);
         p.g = iClamp(iRound(in->r *  1.0753 + (in->g - 127) * -0.3946 + (in->b - 127) * -0.4947), 0, 255);
         p.b = iClamp(iRound(in->r *  1.0753 + (in->g - 127) *  2.0320 + (in->b - 127) *  0.0853), 0, 255);
         *out = p;
         ++in;
         ++out;
     }
 }
References G3D::Color3uint8::b, G3D::Color3uint8::g, height(), G3D::iClamp(), G3D::iRound(), G3D::Color3uint8::r, and width().
Member Data Documentation
m_byte
uint8* G3D::GImage::m_byte private
Definition at line 92 of file GImage.h.
Referenced by _copy(), byte(), clear(), convertToL8(), convertToRGB(), convertToRGBA(), decode(), decodeBMP(), decodeICO(), decodeJPEG(), decodePCX(), decodePNG(), decodePPM(), decodePPMASCII(), decodeTGA(), encodeBMP(), encodeJPEG(), encodePNG(), encodeTGA(), flipHorizontal(), flipVertical(), pixel1(), pixel3(), pixel4(), rawData(), resize(), and rotate90CW().
m_channels
int G3D::GImage::m_channels private
Definition at line 94 of file GImage.h.
Referenced by _copy(), channels(), convertToL8(), convertToRGB(), convertToRGBA(), copySubImage(), decode(), decodeBMP(), decodeICO(), decodeJPEG(), decodePCX(), decodePNG(), decodePPMASCII(), decodeTGA(), encodeBMP(), encodeJPEG(), encodePNG(), encodePPM(), encodePPMASCII(), encodeTGA(), flipHorizontal(), flipVertical(), insertRedAsAlpha(), makeCheckerboard(), pasteSubImage(), pixel1(), pixel3(), pixel4(), resize(), rotate90CW(), sizeInMemory(), and stripAlpha().
m_height
int G3D::GImage::m_height private
Definition at line 96 of file GImage.h.
Referenced by _copy(), clear(), convertToL8(), convertToRGB(), convertToRGBA(), copySubImage(), decode(), decodeBMP(), decodeICO(), decodeJPEG(), decodePCX(), decodePNG(), decodePPM(), decodePPMASCII(), decodeTGA(), encodeBMP(), encodeJPEG(), encodePNG(), encodePPM(), encodePPMASCII(), encodeTGA(), flipHorizontal(), flipVertical(), height(), insertRedAsAlpha(), makeCheckerboard(), pasteSubImage(), pixel1(), pixel3(), pixel4(), resize(), rotate90CW(), sizeInMemory(), and stripAlpha().
m_memMan
MemoryManager::Ref G3D::GImage::m_memMan private
Used exclusively for allocating m_byte; this may be an implementation that allocates directly on a GPU.
Definition at line 91 of file GImage.h.
Referenced by _copy(), clear(), convertToL8(), convertToRGB(), convertToRGBA(), decodeBMP(), decodeICO(), decodeJPEG(), decodePCX(), decodePNG(), decodePPMASCII(), decodeTGA(), flipVertical(), resize(), and rotate90CW().
m_width
int G3D::GImage::m_width private
Definition at line 95 of file GImage.h.
Referenced by _copy(), clear(), convertToL8(), convertToRGB(), convertToRGBA(), copySubImage(), decode(), decodeBMP(), decodeICO(), decodeJPEG(), decodePCX(), decodePNG(), decodePPM(), decodePPMASCII(), decodeTGA(), encodeBMP(), encodeJPEG(), encodePNG(), encodePPM(), encodePPMASCII(), encodeTGA(), flipHorizontal(), flipVertical(), insertRedAsAlpha(), makeCheckerboard(), pasteSubImage(), pixel1(), pixel3(), pixel4(), resize(), rotate90CW(), sizeInMemory(), stripAlpha(), and width().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/GImage.h
deps/g3dlite/source/GImage.cpp
deps/g3dlite/source/GImage_bayer.cpp
deps/g3dlite/source/GImage_bmp.cpp
deps/g3dlite/source/GImage_jpeg.cpp
deps/g3dlite/source/GImage_png.cpp
deps/g3dlite/source/GImage_ppm.cpp
deps/g3dlite/source/GImage_tga.cpp