Azerotcore-wotlk: TransactionTask Class Reference
TransactionTask Class Reference
#include <Transaction.h>
Public Member Functions
TransactionTask (std::shared_ptr< TransactionBase > trans)
~TransactionTask ()
Public Member Functions inherited from SQLOperation
SQLOperation ()
virtual ~SQLOperation ()
virtual int call ()
virtual void SetConnection (MySQLConnection *con)
Protected Member Functions
bool Execute () override
int TryExecute ()
void CleanupOnFailure ()
Protected Attributes
std::shared_ptr< TransactionBase > m_trans
Static Protected Attributes
static std::mutex _deadlockLock
Friends
template<class T >
class DatabaseWorkerPool
class DatabaseWorker
class TransactionCallback
Additional Inherited Members
Public Attributes inherited from SQLOperation
MySQLConnection * m_conn
Detailed Description
Low level class
Definition at line 72 of file Transaction.h.
Constructor & Destructor Documentation
TransactionTask()
TransactionTask::TransactionTask (std::shared_ptr< TransactionBase > trans) inline
Definition at line 79 of file Transaction.h.
 : m_trans(trans) { }
~TransactionTask()
TransactionTask::~TransactionTask () inline
Definition at line 80 of file Transaction.h.
 { }
Member Function Documentation
CleanupOnFailure()
void TransactionTask::CleanupOnFailure () protected
Definition at line 109 of file Transaction.cpp.
 {
     m_trans->Cleanup();
 }
References m_trans.
Referenced by Execute(), and TransactionWithResultTask::Execute().
Execute()
bool TransactionTask::Execute () override protected virtual
Implements SQLOperation.
Reimplemented in TransactionWithResultTask.
Definition at line 72 of file Transaction.cpp.
 {
     int errorCode = TryExecute();
     if (!errorCode)
         return true;
     if (errorCode == ER_LOCK_DEADLOCK)
     {
         std::ostringstream threadIdStream;
         threadIdStream << std::this_thread::get_id();
         std::string threadId = threadIdStream.str();
         // Make sure only 1 async thread retries a transaction so they don't keep dead-locking each other
         std::lock_guard<std::mutex> lock(_deadlockLock);
         for (uint32 loopDuration = 0, startMSTime = getMSTime(); loopDuration <= DEADLOCK_MAX_RETRY_TIME_MS; loopDuration = GetMSTimeDiffToNow(startMSTime))
         {
             if (!TryExecute())
                 return true;
             LOG_WARN("sql.sql", "Deadlocked SQL Transaction, retrying. Loop timer: %u ms, Thread Id: %s", loopDuration, threadId.c_str());
         }
         LOG_ERROR("sql.sql", "Fatal deadlocked SQL Transaction, it will not be retried anymore. Thread Id: %s", threadId.c_str());
     }
     // Clean up now.
     CleanupOnFailure();
     return false;
 }
References _deadlockLock, CleanupOnFailure(), DEADLOCK_MAX_RETRY_TIME_MS, getMSTime(), GetMSTimeDiffToNow(), LOG_ERROR, LOG_WARN, and TryExecute().
TryExecute()
int TransactionTask::TryExecute () protected
Definition at line 104 of file Transaction.cpp.
 {
     return m_conn->ExecuteTransaction(m_trans);
 }
References MySQLConnection::ExecuteTransaction(), SQLOperation::m_conn, and m_trans.
Referenced by Execute(), and TransactionWithResultTask::Execute().
Friends And Related Function Documentation
DatabaseWorker
friend class DatabaseWorker friend
Definition at line 75 of file Transaction.h.
DatabaseWorkerPool
template<class T > friend class DatabaseWorkerPool friend
Definition at line 74 of file Transaction.h.
TransactionCallback
friend class TransactionCallback friend
Definition at line 76 of file Transaction.h.
Member Data Documentation
_deadlockLock
std::mutex TransactionTask::_deadlockLock static protected
Definition at line 88 of file Transaction.h.
Referenced by Execute(), and TransactionWithResultTask::Execute().
m_trans
std::shared_ptr<TransactionBase> TransactionTask::m_trans protected
Definition at line 87 of file Transaction.h.
Referenced by CleanupOnFailure(), and TryExecute().
The documentation for this class was generated from the following files:
src/server/database/Database/Transaction.h
src/server/database/Database/Transaction.cpp