Azerotcore-wotlk: Acore::AnyAttackableUnitExceptForOriginalCasterInObjectRangeCheck Class Reference
Acore::AnyAttackableUnitExceptForOriginalCasterInObjectRangeCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
AnyAttackableUnitExceptForOriginalCasterInObjectRangeCheck (WorldObject const *obj, Unit const *funit, float range)
bool operator() (Unit *u)
Private Attributes
WorldObject const * i_obj
Unit const * i_funit
float i_range
Detailed Description
Definition at line 1001 of file GridNotifiers.h.
Constructor & Destructor Documentation
AnyAttackableUnitExceptForOriginalCasterInObjectRangeCheck()
Acore::AnyAttackableUnitExceptForOriginalCasterInObjectRangeCheck::AnyAttackableUnitExceptForOriginalCasterInObjectRangeCheck (WorldObject const * obj, Unit const * funit, float range) inline
Definition at line 1004 of file GridNotifiers.h.
             : i_obj(obj), i_funit(funit), i_range(range)
         {}
Member Function Documentation
operator()()
bool Acore::AnyAttackableUnitExceptForOriginalCasterInObjectRangeCheck::operator() (Unit * u) inline
Definition at line 1007 of file GridNotifiers.h.
         {
             if (!u->IsAlive() || u->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE | UNIT_FLAG_NOT_SELECTABLE) || (u->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC) && !u->IsInCombat()))
                 return false;
             if (u->GetGUID() == i_funit->GetGUID())
                 return false;
             if (i_obj->IsWithinDistInMap(u, i_range))
                 return true;
             return false;
         }
References Object::GetGUID(), Object::HasFlag(), i_funit, i_obj, i_range, Unit::IsAlive(), Unit::IsInCombat(), WorldObject::IsWithinDistInMap(), UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PC, UNIT_FLAG_NON_ATTACKABLE, and UNIT_FLAG_NOT_SELECTABLE.
Member Data Documentation
i_funit
Unit const* Acore::AnyAttackableUnitExceptForOriginalCasterInObjectRangeCheck::i_funit private
Definition at line 1021 of file GridNotifiers.h.
Referenced by operator()().
i_obj
WorldObject const* Acore::AnyAttackableUnitExceptForOriginalCasterInObjectRangeCheck::i_obj private
Definition at line 1020 of file GridNotifiers.h.
Referenced by operator()().
i_range
float Acore::AnyAttackableUnitExceptForOriginalCasterInObjectRangeCheck::i_range private
Definition at line 1022 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/game/Grids/Notifiers/GridNotifiers.h