Azerotcore-wotlk: achievement_all_you_can_eat Class Reference
achievement_all_you_can_eat Class Reference
Public Member Functions
achievement_all_you_can_eat ()
bool OnCheck (Player *, Unit *target, uint32) override
Public Member Functions inherited from AchievementCriteriaScript
bool IsDatabaseBound () const override
Public Member Functions inherited from ScriptObject
virtual bool isAfterLoadScript () const
virtual void checkValidity ()
const std::string & GetName () const
Additional Inherited Members
Protected Member Functions inherited from AchievementCriteriaScript
AchievementCriteriaScript (const char *name)
Protected Member Functions inherited from ScriptObject
ScriptObject (const char *name)
virtual ~ScriptObject ()=default
Detailed Description
Definition at line 1354 of file boss_sindragosa.cpp.
Constructor & Destructor Documentation
achievement_all_you_can_eat()
achievement_all_you_can_eat::achievement_all_you_can_eat () inline
Definition at line 1357 of file boss_sindragosa.cpp.
 : AchievementCriteriaScript("achievement_all_you_can_eat") { }
Member Function Documentation
OnCheck()
bool achievement_all_you_can_eat::OnCheck (Player * , Unit * target, uint32) inline override virtual
Reimplemented from AchievementCriteriaScript.
Definition at line 1359 of file boss_sindragosa.cpp.
     {
         if (!target || target->GetEntry() != NPC_SINDRAGOSA)
             return false;
         return target->GetAI()->GetData(DATA_MYSTIC_BUFFET_STACK) <= 5;
     }
References DATA_MYSTIC_BUFFET_STACK, Unit::GetAI(), UnitAI::GetData(), Object::GetEntry(), and NPC_SINDRAGOSA.
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_sindragosa.cpp