Azerotcore-wotlk: npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI Struct Reference
npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI Struct Reference
Public Member Functions
npc_icc_valkyr_heraldAI (Creature *creature)
void Reset () override
void EnterCombat (Unit *) override
void JustReachedHome () override
void JustSummoned (Creature *s) override
void MoveInLineOfSight (Unit *who) override
void SummonedCreatureDespawn (Creature *s) override
bool CanAIAttack (Unit const *target) const override
void SpellHitTarget (Unit *target, const SpellInfo *spell) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void SpellHit (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void AttackStart (Unit *) override
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
SummonList summons
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 2816 of file icecrown_citadel.cpp.
Constructor & Destructor Documentation
npc_icc_valkyr_heraldAI()
npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::npc_icc_valkyr_heraldAI (Creature * creature) inline
Definition at line 2818 of file icecrown_citadel.cpp.
 : ScriptedAI(creature), summons(me) {}
Member Function Documentation
CanAIAttack()
bool npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::CanAIAttack (Unit const * target) const inline override virtual
Reimplemented from UnitAI.
Definition at line 2854 of file icecrown_citadel.cpp.
         {
             return target->GetExactDist(4357.0f, 2769.0f, 356.0f) < 170.0f;
         }
References Position::GetExactDist().
EnterCombat()
void npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 2824 of file icecrown_citadel.cpp.
         {
             events.Reset();
             summons.DespawnAll();
             me->setActive(true);
             events.ScheduleEvent(1, 10000);
             me->SetInCombatWithZone();
         }
References SummonList::DespawnAll(), ScriptedAI::me, WorldObject::setActive(), Creature::SetInCombatWithZone(), and summons.
JustReachedHome()
void npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 2833 of file icecrown_citadel.cpp.
         {
             me->setActive(false);
         }
References ScriptedAI::me, and WorldObject::setActive().
JustSummoned()
void npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::JustSummoned (Creature * s) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 2838 of file icecrown_citadel.cpp.
         {
             summons.Summon(s);
         }
References SummonList::Summon(), and summons.
MoveInLineOfSight()
void npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
Definition at line 2843 of file icecrown_citadel.cpp.
         {
             if (me->IsAlive() && !me->IsInCombat() && who->GetTypeId() == TYPEID_PLAYER && who->GetExactDist2d(me) < 35.0f)
                 AttackStart(who);
         }
References ScriptedAI::AttackStart(), Position::GetExactDist2d(), Object::GetTypeId(), Unit::IsAlive(), Unit::IsInCombat(), ScriptedAI::me, and TYPEID_PLAYER.
Reset()
void npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 2822 of file icecrown_citadel.cpp.
 { events.Reset(); summons.DespawnAll(); }
References SummonList::DespawnAll(), and summons.
SpellHitTarget()
void npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::SpellHitTarget (Unit * target, const SpellInfo * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 2859 of file icecrown_citadel.cpp.
         {
             if (spell->Id == 71906 || spell->Id == 71942)
             {
                 if (Creature* c = me->SummonCreature(38410, *target, TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, 30000))
                 {
                     c->AI()->AttackStart(target);
                     DoZoneInCombat(c);
                     uint8 Class = target->getClass();
                     if (Class != CLASS_DRUID)
                         if (Player* p = target->ToPlayer())
{
                             if (Item* i = p->GetWeaponForAttack(BASE_ATTACK))
                                 me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 0, i->GetEntry());
                             if (Item* i = p->GetWeaponForAttack(OFF_ATTACK))
                                 me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 1, i->GetEntry());
                             if (Item* i = p->GetWeaponForAttack(RANGED_ATTACK))
                                 me->SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID + 2, i->GetEntry());
                             target->CastSpell(c, 60352, true); // Mirror Image, clone visual appearance
                         }
                     c->AI()->DoAction(Class);
                 }
             }
         }
References BASE_ATTACK, Unit::CastSpell(), CLASS_DRUID, CreatureAI::DoZoneInCombat(), Unit::getClass(), SpellInfo::Id, ScriptedAI::me, OFF_ATTACK, RANGED_ATTACK, Object::SetUInt32Value(), WorldObject::SummonCreature(), TEMPSUMMON_TIMED_DESPAWN_OUT_OF_COMBAT, Object::ToPlayer(), and UNIT_VIRTUAL_ITEM_SLOT_ID.
SummonedCreatureDespawn()
void npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::SummonedCreatureDespawn (Creature * s) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 2849 of file icecrown_citadel.cpp.
         {
             summons.Despawn(s);
         }
References SummonList::Despawn(), and summons.
UpdateAI()
void npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 2885 of file icecrown_citadel.cpp.
         {
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (events.ExecuteEvent())
             {
                 case 0:
                     break;
                 case 1:
                     {
                         uint8 count = me->GetMap()->Is25ManRaid() ? 4 : 2;
                         bool casted = false;
                         for (uint8 i = 0; i < count; ++i)
                             if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 37.5f, true))
{
                                 casted = true;
                                 me->CastSpell(target, 71906, true); // Severed Essence
                             }
                         events.RepeatEvent(casted ? 25000 : 5000);
                     }
                     break;
             }
             DoMeleeAttackIfReady();
         }
References Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), WorldObject::GetMap(), Unit::HasUnitState(), Map::Is25ManRaid(), ScriptedAI::me, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
events
EventMap npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::events
Definition at line 2819 of file icecrown_citadel.cpp.
summons
SummonList npc_icc_valkyr_herald::npc_icc_valkyr_heraldAI::summons
Definition at line 2820 of file icecrown_citadel.cpp.
Referenced by EnterCombat(), JustSummoned(), Reset(), and SummonedCreatureDespawn().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp