Azerotcore-wotlk: npc_hol_monument::npc_hol_monumentAI Struct Reference
npc_hol_monument::npc_hol_monumentAI Struct Reference
Public Member Functions
npc_hol_monumentAI (Creature *creature)
void Reset () override
void MoveInLineOfSight (Unit *who) override
void EnterCombat (Unit *) override
void AttackStart (Unit *who) override
void UpdateAI (uint32 diff) override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void JustSummoned (Creature *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
bool _isActive
ObjectGuid _attackGUID
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 456 of file boss_volkhan.cpp.
Constructor & Destructor Documentation
npc_hol_monumentAI()
npc_hol_monument::npc_hol_monumentAI::npc_hol_monumentAI (Creature * creature) inline
Definition at line 458 of file boss_volkhan.cpp.
                                                : ScriptedAI(creature)
         {
             _attackGUID.Clear();
             _isActive = urand(0, 1);
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
             me->CastSpell(me, SPELL_FREEZE_ANIM, true);
         }
References _attackGUID, _isActive, Unit::CastSpell(), ObjectGuid::Clear(), ScriptedAI::me, Object::SetFlag(), SPELL_FREEZE_ANIM, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, and urand().
Member Function Documentation
AttackStart()
void npc_hol_monument::npc_hol_monumentAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 508 of file boss_volkhan.cpp.
         {
             if (!_attackGUID || !_isActive)
                 return;
             ScriptedAI::AttackStart(who);
         }
References _attackGUID, _isActive, and ScriptedAI::AttackStart().
Referenced by UpdateAI().
EnterCombat()
void npc_hol_monument::npc_hol_monumentAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 490 of file boss_volkhan.cpp.
         {
             events.Reset();
             if (me->GetEntry() == 28961) // NPC_TITANIUM_SIEGEBREAKER
             {
                 events.ScheduleEvent(EVENT_PIERCING_HOWL, 10000 + rand() % 15000);
                 events.ScheduleEvent(EVENT_PENETRATING_STRIKE, 5000 + rand() % 5000);
                 events.ScheduleEvent(EVENT_FRIGHTENING_SHOUT, 20000 + rand() % 8000);
                 events.ScheduleEvent(EVENT_BLADE_TURNING, 12000);
             }
             else
             {
                 events.ScheduleEvent(EVENT_THROW, 10000 + rand() % 15000);
                 events.ScheduleEvent(EVENT_DEADLY_THROW, 15000 + rand() % 15000);
                 events.ScheduleEvent(EVENT_DEFLECTION, 15000);
             }
         }
References EVENT_BLADE_TURNING, EVENT_DEADLY_THROW, EVENT_DEFLECTION, EVENT_FRIGHTENING_SHOUT, EVENT_PENETRATING_STRIKE, EVENT_PIERCING_HOWL, EVENT_THROW, Object::GetEntry(), and ScriptedAI::me.
MoveInLineOfSight()
void npc_hol_monument::npc_hol_monumentAI::MoveInLineOfSight (Unit * who) inline override virtual
Reimplemented from CreatureAI.
Definition at line 474 of file boss_volkhan.cpp.
         {
             if (_attackGUID)
                 ScriptedAI::MoveInLineOfSight(who);
             else if (_isActive && who->GetTypeId() == TYPEID_PLAYER)
             {
                 if ((who->GetPositionX() < me->GetPositionX() || who->GetPositionY() < -220.0f) && me->GetDistance2d(who) < 40)
                 {
                     _isActive = false;
                     _attackGUID = who->GetGUID();
                     events.Reset();
                     events.RescheduleEvent(EVENT_UNFREEZE, 5000);
                 }
             }
         }
References _attackGUID, _isActive, EVENT_UNFREEZE, WorldObject::GetDistance2d(), Object::GetGUID(), Position::GetPositionX(), Position::GetPositionY(), Object::GetTypeId(), ScriptedAI::me, CreatureAI::MoveInLineOfSight(), and TYPEID_PLAYER.
Reset()
void npc_hol_monument::npc_hol_monumentAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 470 of file boss_volkhan.cpp.
         {
         }
UpdateAI()
void npc_hol_monument::npc_hol_monumentAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 515 of file boss_volkhan.cpp.
         {
             if (!_isActive && !_attackGUID)
                 return;
             events.Update(diff);
             uint32 eventId = events.ExecuteEvent();
             if (eventId == EVENT_UNFREEZE)
             {
                 me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE);
                 me->CastSpell(me, SPELL_AWAKEN, true);
                 me->RemoveAllAuras();
                 _isActive = true;
                 if (Unit* target = ObjectAccessor::GetUnit(*me, _attackGUID))
                     AttackStart(target);
                 return;
             }
             //Return since we have no target or if we are disabled from fight
             if (!UpdateVictim())
                 return;
             if (me->HasUnitState(UNIT_STATE_CASTING))
                 return;
             switch (eventId)
             {
                 case EVENT_PIERCING_HOWL:
                     me->CastSpell(me->GetVictim(), SPELL_PIERCING_HOWL, false);
                     events.RepeatEvent(10000 + rand() % 1500);
                     break;
                 case EVENT_PENETRATING_STRIKE:
                     me->CastSpell(me->GetVictim(), SPELL_PENETRATING_STRIKE, false);
                     events.RepeatEvent(5000 + rand() % 5000);
                     break;
                 case EVENT_FRIGHTENING_SHOUT:
                     me->CastSpell(me->GetVictim(), SPELL_FRIGHTENING_SHOUT, false);
                     events.RepeatEvent(20000 + rand() % 8000);
                     break;
                 case EVENT_BLADE_TURNING:
                     me->CastSpell(me->GetVictim(), me->GetMap()->IsHeroic() ? SPELL_BLADE_TURNING_H : SPELL_BLADE_TURNING_N, false);
                     events.RepeatEvent(12000);
                     break;
                 case EVENT_THROW:
                     me->CastSpell(SelectTarget(SELECT_TARGET_RANDOM, 0, 50.0f, true, 0), me->GetMap()->IsHeroic() ? SPELL_THROW_H : SPELL_THROW_N, true);
                     events.RepeatEvent(10000 + rand() % 15000);
                     break;
                 case EVENT_DEADLY_THROW:
                     me->CastSpell(SelectTarget(SELECT_TARGET_RANDOM, 0, 50.0f, true, 0), me->GetMap()->IsHeroic() ? SPELL_DEADLY_THROW_H : SPELL_DEADLY_THROW_N, true);
                     events.RepeatEvent(15000 + rand() % 15000);
                     break;
                 case EVENT_DEFLECTION:
                     me->CastSpell(me, me->GetMap()->IsHeroic() ? SPELL_DEFLECTION_H : SPELL_DEFLECTION_N, false);
                     events.RepeatEvent(15000);
                     break;
             }
             DoMeleeAttackIfReady();
         }
References _attackGUID, _isActive, AttackStart(), Unit::CastSpell(), diff(), UnitAI::DoMeleeAttackIfReady(), EVENT_BLADE_TURNING, EVENT_DEADLY_THROW, EVENT_DEFLECTION, EVENT_FRIGHTENING_SHOUT, EVENT_PENETRATING_STRIKE, EVENT_PIERCING_HOWL, EVENT_THROW, EVENT_UNFREEZE, WorldObject::GetMap(), ObjectAccessor::GetUnit(), Unit::GetVictim(), Unit::HasUnitState(), Map::IsHeroic(), ScriptedAI::me, Unit::RemoveAllAuras(), Object::RemoveFlag(), SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), SPELL_AWAKEN, SPELL_BLADE_TURNING_H, SPELL_BLADE_TURNING_N, SPELL_DEADLY_THROW_H, SPELL_DEADLY_THROW_N, SPELL_DEFLECTION_H, SPELL_DEFLECTION_N, SPELL_FRIGHTENING_SHOUT, SPELL_PENETRATING_STRIKE, SPELL_PIERCING_HOWL, SPELL_THROW_H, SPELL_THROW_N, UNIT_FIELD_FLAGS, UNIT_FLAG_NON_ATTACKABLE, UNIT_STATE_CASTING, and CreatureAI::UpdateVictim().
Member Data Documentation
_attackGUID
ObjectGuid npc_hol_monument::npc_hol_monumentAI::_attackGUID
Definition at line 468 of file boss_volkhan.cpp.
Referenced by AttackStart(), MoveInLineOfSight(), npc_hol_monumentAI(), and UpdateAI().
_isActive
bool npc_hol_monument::npc_hol_monumentAI::_isActive
Definition at line 467 of file boss_volkhan.cpp.
Referenced by AttackStart(), MoveInLineOfSight(), npc_hol_monumentAI(), and UpdateAI().
events
EventMap npc_hol_monument::npc_hol_monumentAI::events
Definition at line 466 of file boss_volkhan.cpp.
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/HallsOfLightning/boss_volkhan.cpp