Azerotcore-wotlk: deps/mysqllite/include/internal/my_aes.h File Reference
my_aes.h File Reference
#include "rijndael.h"
Macros
#define AES_KEY_LENGTH 128 /* Must be 128 192 or 256 */
Functions
int my_aes_encrypt (const char *source, int source_length, char *dest, const char *key, int key_length)
int my_aes_decrypt (const char *source, int source_length, char *dest, const char *key, int key_length)
int my_aes_get_size (int source_length)
Macro Definition Documentation
AES_KEY_LENGTH
#define AES_KEY_LENGTH 128 /* Must be 128 192 or 256 */
Definition at line 27 of file my_aes.h.
Function Documentation
my_aes_decrypt()
int my_aes_decrypt (const char * source, int source_length, char * dest, const char * key, int key_length)
Definition at line 174 of file my_aes.c.
 {
   KEYINSTANCE aes_key;
   uint8 block[AES_BLOCK_SIZE];  /* 128 bit block used for padding */
   int rc;           /* Result codes */
   int num_blocks;       /* Number of complete blocks */
   uint pad_len;         /* Pad size for the last block */
   int i;
   if ((rc=my_aes_create_key(&aes_key,AES_DECRYPT,key,key_length)))
     return rc;
   num_blocks = source_length/AES_BLOCK_SIZE;
   if ((source_length != num_blocks*AES_BLOCK_SIZE) || num_blocks ==0 )
     return AES_BAD_DATA; /* Input size has to be even and at least one block */
   for (i = num_blocks-1; i > 0; i--)   /* Decode all but last blocks */
   {
     rijndaelDecrypt(aes_key.rk, aes_key.nr, (const uint8*) source,
             (uint8*) dest);
     source+= AES_BLOCK_SIZE;
     dest+= AES_BLOCK_SIZE;
   }
   rijndaelDecrypt(aes_key.rk, aes_key.nr, (const uint8*) source, block);
   /* Use last char in the block as size */
   pad_len = (uint) (uchar) block[AES_BLOCK_SIZE-1];
   if (pad_len > AES_BLOCK_SIZE)
     return AES_BAD_DATA;
   /* We could also check whole padding but we do not really need this */
   memcpy(dest, block, AES_BLOCK_SIZE - pad_len);
   return AES_BLOCK_SIZE*num_blocks - pad_len;
 }
References AES_BAD_DATA, AES_BLOCK_SIZE, AES_DECRYPT, memcpy, my_aes_create_key(), KEYINSTANCE::nr, rijndaelDecrypt(), and KEYINSTANCE::rk.
my_aes_encrypt()
int my_aes_encrypt (const char * source, int source_length, char * dest, const char * key, int key_length)
Definition at line 126 of file my_aes.c.
 {
   KEYINSTANCE aes_key;
   uint8 block[AES_BLOCK_SIZE];  /* 128 bit block used for padding */
   int rc;           /* result codes */
   int num_blocks;       /* number of complete blocks */
   char pad_len;         /* pad size for the last block */
   int i;
   if ((rc= my_aes_create_key(&aes_key,AES_ENCRYPT,key,key_length)))
     return rc;
   num_blocks = source_length/AES_BLOCK_SIZE;
   for (i = num_blocks; i > 0; i--)   /* Encode complete blocks */
   {
     rijndaelEncrypt(aes_key.rk, aes_key.nr, (const uint8*) source,
             (uint8*) dest);
     source+= AES_BLOCK_SIZE;
     dest+= AES_BLOCK_SIZE;
   }
   /* Encode the rest. We always have incomplete block */
   pad_len = AES_BLOCK_SIZE - (source_length - AES_BLOCK_SIZE*num_blocks);
   memcpy(block, source, 16 - pad_len);
   bfill(block + AES_BLOCK_SIZE - pad_len, pad_len, pad_len);
   rijndaelEncrypt(aes_key.rk, aes_key.nr, block, (uint8*) dest);
   return AES_BLOCK_SIZE*(num_blocks + 1);
 }
References AES_BLOCK_SIZE, AES_ENCRYPT, bfill, memcpy, my_aes_create_key(), KEYINSTANCE::nr, rijndaelEncrypt(), and KEYINSTANCE::rk.
my_aes_get_size()
int my_aes_get_size (int source_length)
Definition at line 224 of file my_aes.c.
 {
   return AES_BLOCK_SIZE*(source_length/AES_BLOCK_SIZE)+AES_BLOCK_SIZE;
 }
References AES_BLOCK_SIZE.