Azerotcore-wotlk: npc_frostwing_vrykul::npc_frostwing_vrykulAI Struct Reference
npc_frostwing_vrykul::npc_frostwing_vrykulAI Struct Reference
Public Member Functions
npc_frostwing_vrykulAI (Creature *creature)
void AttackStart (Unit *victim) override
void EnterCombat (Unit *) override
void JustSummoned (Creature *summon) override
void Reset () override
void UpdateAI (uint32 diff) override
void SpellHitTarget (Unit *c, const SpellInfo *spell) override
bool CanAIAttack (Unit const *target) const override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void SummonedCreatureDespawn (Creature *) override
void SpellHit (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void EnterEvadeMode ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
virtual void JustReachedHome ()
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
EventMap events
EventMap events2
SummonList summons
bool isRanged
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
virtual void MoveInLineOfSight (Unit *)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 1603 of file icecrown_citadel.cpp.
Constructor & Destructor Documentation
npc_frostwing_vrykulAI()
npc_frostwing_vrykul::npc_frostwing_vrykulAI::npc_frostwing_vrykulAI (Creature * creature) inline
Definition at line 1605 of file icecrown_citadel.cpp.
                                                    : ScriptedAI(creature), summons(me)
         {
             if (me->GetEntry() == NPC_YMIRJAR_DEATHBRINGER || me->GetEntry() == NPC_YMIRJAR_FROSTBINDER || me->GetEntry() == NPC_YMIRJAR_HUNTRESS)
                 isRanged = true;
             else
                 isRanged = false;
         }
References Object::GetEntry(), isRanged, ScriptedAI::me, NPC_YMIRJAR_DEATHBRINGER, NPC_YMIRJAR_FROSTBINDER, and NPC_YMIRJAR_HUNTRESS.
Member Function Documentation
AttackStart()
void npc_frostwing_vrykul::npc_frostwing_vrykulAI::AttackStart (Unit * victim) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1618 of file icecrown_citadel.cpp.
         {
             if (me->GetEntry() == NPC_YMIRJAR_FROSTBINDER)
                 ScriptedAI::AttackStartNoMove(victim);
             else if (isRanged)
                 ScriptedAI::AttackStartCaster(victim, 16.0f);
             else
                 ScriptedAI::AttackStart(victim);
         }
References ScriptedAI::AttackStart(), UnitAI::AttackStartCaster(), ScriptedAI::AttackStartNoMove(), Object::GetEntry(), isRanged, ScriptedAI::me, and NPC_YMIRJAR_FROSTBINDER.
CanAIAttack()
bool npc_frostwing_vrykul::npc_frostwing_vrykulAI::CanAIAttack (Unit const * target) const inline override virtual
Reimplemented from UnitAI.
Definition at line 1788 of file icecrown_citadel.cpp.
         {
             // do not see targets inside Frostwing Halls when we are not there
             return (me->GetPositionY() > 2660.0f) == (target->GetPositionY() > 2660.0f);
         }
References Position::GetPositionY(), and ScriptedAI::me.
EnterCombat()
void npc_frostwing_vrykul::npc_frostwing_vrykulAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1628 of file icecrown_citadel.cpp.
         {
             me->InterruptNonMeleeSpells(false);
             me->CallForHelp(8.5f);
             if (me->GetEntry() == NPC_YMIRJAR_FROSTBINDER)
                 me->SetHover(true);
         }
References Creature::CallForHelp(), Object::GetEntry(), Unit::InterruptNonMeleeSpells(), ScriptedAI::me, NPC_YMIRJAR_FROSTBINDER, and Creature::SetHover().
JustSummoned()
void npc_frostwing_vrykul::npc_frostwing_vrykulAI::JustSummoned (Creature * summon) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1636 of file icecrown_citadel.cpp.
         {
             summons.Summon(summon);
         }
References SummonList::Summon(), and summons.
Reset()
void npc_frostwing_vrykul::npc_frostwing_vrykulAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1641 of file icecrown_citadel.cpp.
         {
             summons.DespawnAll();
             events.Reset();
             events2.Reset();
             switch (me->GetEntry())
             {
                 case NPC_YMIRJAR_HUNTRESS:
                     events.ScheduleEvent(1, urand(10000, 15000)); // Ice Trap
                     events.ScheduleEvent(2, urand(8000, 12000)); // Rapid Shot
                     events.ScheduleEvent(3, urand(6000, 10000)); // Volley
                     if (me->GetMap()->Is25ManRaid())
                         events.ScheduleEvent(4, 5000); // Summon Warhawk
                     break;
                 case NPC_YMIRJAR_WARLORD:
                     events.ScheduleEvent(11, 6000); // Whirlwind
                     break;
                 case NPC_YMIRJAR_BATTLE_MAIDEN:
                     events.ScheduleEvent(21, 3000); // Barbaric Strike
                     events.ScheduleEvent(22, urand(8000, 12000)); // Adrenaline Rush
                     break;
                 case NPC_YMIRJAR_FROSTBINDER:
                     events.ScheduleEvent(31, 0); // Arctic Chill
                     events.ScheduleEvent(32, urand(15000, 25000)); // Frozen Orb
                     events.ScheduleEvent(33, urand(15000, 30000)); // Twisted Winds
                     events2.ScheduleEvent(100, 0); // Spirit Stream
                     me->SetHover(false);
                     break;
                 case NPC_YMIRJAR_DEATHBRINGER:
                     events.ScheduleEvent(41, 2500); // Empowered Shadow Bolt
                     events.ScheduleEvent(42, 5000); // Summon Undead
                     events2.ScheduleEvent(100, 0); // Spirit Stream
                     break;
             }
         }
References SummonList::DespawnAll(), events2, Object::GetEntry(), WorldObject::GetMap(), Map::Is25ManRaid(), ScriptedAI::me, NPC_YMIRJAR_BATTLE_MAIDEN, NPC_YMIRJAR_DEATHBRINGER, NPC_YMIRJAR_FROSTBINDER, NPC_YMIRJAR_HUNTRESS, NPC_YMIRJAR_WARLORD, EventMap::Reset(), EventMap::ScheduleEvent(), Creature::SetHover(), summons, and urand().
SpellHitTarget()
void npc_frostwing_vrykul::npc_frostwing_vrykulAI::SpellHitTarget (Unit * c, const SpellInfo * spell) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1769 of file icecrown_citadel.cpp.
         {
             if (spell->Id == 71306 && c->GetTypeId() == TYPEID_UNIT) // Twisted Winds
             {
                 Position myPos = me->GetPosition();
                 me->NearTeleportTo(c->GetPositionX(), c->GetPositionY(), c->GetPositionZ(), c->GetOrientation());
                 c->NearTeleportTo(myPos.GetPositionX(), myPos.GetPositionY(), myPos.GetPositionZ(), myPos.GetOrientation());
                 const ThreatContainer::StorageType me_tl = me->getThreatMgr().getThreatList();
                 const ThreatContainer::StorageType target_tl = c->getThreatMgr().getThreatList();
                 DoResetThreat();
                 for (ThreatContainer::StorageType::const_iterator iter = target_tl.begin(); iter != target_tl.end(); ++iter)
                     me->getThreatMgr().addThreat((*iter)->getTarget(), (*iter)->getThreat());
                 c->getThreatMgr().resetAllAggro();
                 for (ThreatContainer::StorageType::const_iterator iter = me_tl.begin(); iter != me_tl.end(); ++iter)
                     c->getThreatMgr().addThreat((*iter)->getTarget(), (*iter)->getThreat());
             }
         }
References ThreatMgr::addThreat(), ScriptedAI::DoResetThreat(), Position::GetOrientation(), Position::GetPosition(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), ThreatMgr::getThreatList(), Unit::getThreatMgr(), Object::GetTypeId(), SpellInfo::Id, ScriptedAI::me, Unit::NearTeleportTo(), ThreatMgr::resetAllAggro(), and TYPEID_UNIT.
UpdateAI()
void npc_frostwing_vrykul::npc_frostwing_vrykulAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 1677 of file icecrown_citadel.cpp.
         {
             if (!me->IsInCombat())
             {
                 events2.Update(diff);
                 switch (events2.ExecuteEvent())
                 {
                     case 100:
                         if (Creature* stalker = me->FindNearestCreature(NPC_INVISIBLE_STALKER_3_0, 50.0f))
                             me->CastSpell(stalker, SPELL_SPIRIT_STREAM, false);
                         events2.ScheduleEvent(100, 33000);
                         break;
                 }
             }
             if (!UpdateVictim())
                 return;
             events.Update(diff);
             if (me->HasUnitState(UNIT_STATE_CASTING) || me->isFeared() || me->isFrozen() || me->HasUnitState(UNIT_STATE_STUNNED) || me->HasUnitState(UNIT_STATE_CONFUSED) || ((me->GetEntry() == NPC_YMIRJAR_DEATHBRINGER || me->GetEntry() == NPC_YMIRJAR_FROSTBINDER) && me->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_SILENCED)))
                 return;
             switch (events.ExecuteEvent())
             {
                 case 0:
                     break;
                 case 1: // Ice Trap
                     me->CastSpell((Unit*)nullptr, 71249, false);
                     events.RepeatEvent(urand(35000, 40000));
                     break;
                 case 2: // Rapid Shot
                     me->CastSpell(me->GetVictim(), 71251, false);
                     events.RepeatEvent(urand(25000, 30000));
                     break;
                 case 3: // Volley
                     {
                         Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 35.0f, true);
                         if (target && me->GetDistance(target) > 10.0f)
{
                             me->CastSpell(target, 71252, false);
                             events.RepeatEvent(urand(25000, 35000));
                         }
                         else
                             events.RepeatEvent(2500);
                     }
                     break;
                 case 4: // Summon Warhawk
                     me->CastSpell(me, 71705, false);
                     break;
                 case 11: // Whirlwind
                     me->CastSpell(me->GetVictim(), 41056, false);
                     events.RepeatEvent(6000);
                     break;
                 case 21: // Barbaric Strike
                     me->CastSpell(me->GetVictim(), 71257, false);
                     events.RepeatEvent(3000);
                     break;
                 case 22: // Adrenaline Rush
                     me->CastSpell(me, 71258, false);
                     events.RepeatEvent(urand(15000, 25000));
                     break;
                 case 31: // Arctic Chill
                     me->CastSpell(me, 71270, true);
                     break;
                 case 32: // Frozen Orb
                     if (Unit* target = SelectTarget(SELECT_TARGET_FARTHEST, 0, 30.0f, true))
                         me->CastSpell(target, 71274, false);
                     events.RepeatEvent(urand(40000, 50000));
                     break;
                 case 33: // Twisted Winds
                     me->CastSpell((Unit*)nullptr, 71306, false);
                     events.RepeatEvent(urand(35000, 50000));
                     break;
                 case 41: // Empowered Shadow Bolt
                     me->CastSpell(me->GetVictim(), 69528, false);
                     events.RepeatEvent(2500);
                     break;
                 case 42: // Summon Undead
                     me->CastSpell(me->GetVictim(), 69516, false);
                     events.RepeatEvent(45000);
                     break;
                 default:
                     break;
             }
             if (me->GetEntry() == NPC_YMIRJAR_HUNTRESS && me->GetVictim() && me->GetDistance(me->GetVictim()) > 5.0f)
                 DoSpellAttackIfReady(71253); // Shoot
             else
                 DoMeleeAttackIfReady();
         }
References Unit::CastSpell(), UnitAI::DoMeleeAttackIfReady(), UnitAI::DoSpellAttackIfReady(), events2, EventMap::ExecuteEvent(), WorldObject::FindNearestCreature(), WorldObject::GetDistance(), Object::GetEntry(), Unit::GetVictim(), Object::HasFlag(), Unit::HasUnitState(), Unit::isFeared(), Unit::isFrozen(), Unit::IsInCombat(), ScriptedAI::me, NPC_INVISIBLE_STALKER_3_0, NPC_YMIRJAR_DEATHBRINGER, NPC_YMIRJAR_FROSTBINDER, NPC_YMIRJAR_HUNTRESS, EventMap::ScheduleEvent(), SELECT_TARGET_FARTHEST, SELECT_TARGET_RANDOM, UnitAI::SelectTarget(), SPELL_SPIRIT_STREAM, UNIT_FIELD_FLAGS, UNIT_FLAG_SILENCED, UNIT_STATE_CASTING, UNIT_STATE_CONFUSED, UNIT_STATE_STUNNED, EventMap::Update(), CreatureAI::UpdateVictim(), and urand().
Member Data Documentation
events
EventMap npc_frostwing_vrykul::npc_frostwing_vrykulAI::events
Definition at line 1613 of file icecrown_citadel.cpp.
events2
EventMap npc_frostwing_vrykul::npc_frostwing_vrykulAI::events2
Definition at line 1614 of file icecrown_citadel.cpp.
Referenced by Reset(), and UpdateAI().
isRanged
bool npc_frostwing_vrykul::npc_frostwing_vrykulAI::isRanged
Definition at line 1616 of file icecrown_citadel.cpp.
Referenced by AttackStart(), and npc_frostwing_vrykulAI().
summons
SummonList npc_frostwing_vrykul::npc_frostwing_vrykulAI::summons
Definition at line 1615 of file icecrown_citadel.cpp.
Referenced by JustSummoned(), and Reset().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/icecrown_citadel.cpp