Azerotcore-wotlk: deps/jemalloc/include/jemalloc/internal/malloc_io.h File Reference
malloc_io.h File Reference
#include <inttypes.h>
Macros
#define FMTd32 PRId32
#define FMTu32 PRIu32
#define FMTx32 PRIx32
#define FMTd64 PRId64
#define FMTu64 PRIu64
#define FMTx64 PRIx64
#define FMTdPTR PRIdPTR
#define FMTuPTR PRIuPTR
#define FMTxPTR PRIxPTR
#define BUFERROR_BUF 64
#define MALLOC_PRINTF_BUFSIZE 4096
Functions
int buferror (int err, char *buf, size_t buflen)
uintmax_t malloc_strtoumax (const char *restrict nptr, char **restrict endptr, int base)
void malloc_write (const char *s)
size_t malloc_vsnprintf (char *str, size_t size, const char *format, va_list ap)
size_t malloc_snprintf (char *str, size_t size, const char *format,...) JEMALLOC_FORMAT_PRINTF(3
size_t void malloc_vcprintf (void(*write_cb)(void *, const char *), void *cbopaque, const char *format, va_list ap)
void malloc_cprintf (void(*write_cb)(void *, const char *), void *cbopaque, const char *format,...) JEMALLOC_FORMAT_PRINTF(3
void void malloc_printf (const char *format,...) JEMALLOC_FORMAT_PRINTF(1
void void static ssize_t malloc_write_fd (int fd, const void *buf, size_t count)
static ssize_t malloc_read_fd (int fd, void *buf, size_t count)
Macro Definition Documentation
BUFERROR_BUF
#define BUFERROR_BUF 64
Definition at line 35 of file malloc_io.h.
FMTd32
#define FMTd32 PRId32
Definition at line 23 of file malloc_io.h.
FMTd64
#define FMTd64 PRId64
Definition at line 26 of file malloc_io.h.
FMTdPTR
#define FMTdPTR PRIdPTR
Definition at line 29 of file malloc_io.h.
FMTu32
#define FMTu32 PRIu32
Definition at line 24 of file malloc_io.h.
FMTu64
#define FMTu64 PRIu64
Definition at line 27 of file malloc_io.h.
FMTuPTR
#define FMTuPTR PRIuPTR
Definition at line 30 of file malloc_io.h.
FMTx32
#define FMTx32 PRIx32
Definition at line 25 of file malloc_io.h.
FMTx64
#define FMTx64 PRIx64
Definition at line 28 of file malloc_io.h.
FMTxPTR
#define FMTxPTR PRIxPTR
Definition at line 31 of file malloc_io.h.
MALLOC_PRINTF_BUFSIZE
#define MALLOC_PRINTF_BUFSIZE 4096
Definition at line 41 of file malloc_io.h.
Function Documentation
buferror()
int buferror (int err, char * buf, size_t buflen)
Definition at line 96 of file malloc_io.c.
{
 #ifdef _WIN32
     FormatMessageA(FORMAT_MESSAGE_FROM_SYSTEM, NULL, err, 0,
         (LPSTR)buf, (DWORD)buflen, NULL);
     return 0;
 #elif defined(JEMALLOC_STRERROR_R_RETURNS_CHAR_WITH_GNU_SOURCE) && defined(_GNU_SOURCE)
     char *b = strerror_r(err, buf, buflen);
     if (b != buf) {
         strncpy(buf, b, buflen);
         buf[buflen-1] = '\0';
     }
     return 0;
 #else
     return strerror_r(err, buf, buflen);
 #endif
 }
References b, and NULL.
malloc_cprintf()
void malloc_cprintf (void(*)(void *, const char *) write_cb, void * cbopaque, const char * format, ...)
malloc_printf()
void void malloc_printf (const char * format, ...)
malloc_read_fd()
static ssize_t malloc_read_fd (int fd, void * buf, size_t count) inline static
Definition at line 89 of file malloc_io.h.
{
 #if defined(JEMALLOC_USE_SYSCALL) && defined(SYS_read)
     long result = syscall(SYS_read, fd, buf, count);
 #else
     ssize_t result = read(fd, buf,
 #ifdef _WIN32
         (unsigned int)
 #endif
         count);
 #endif
     return (ssize_t)result;
 }
References count(), endif(), and read.
Referenced by init_thp_state(), and prof_dump_maps().
malloc_snprintf()
size_t malloc_snprintf (char * str, size_t size, const char * format, ...)
malloc_strtoumax()
uintmax_t malloc_strtoumax (const char *restrict nptr, char **restrict endptr, int base)
Definition at line 114 of file malloc_io.c.
{
     uintmax_t ret, digit;
     unsigned b;
     bool neg;
     const char *p, *ns;
     p = nptr;
     if (base < 0 || base == 1 || base > 36) {
         ns = p;
         set_errno(EINVAL);
         ret = UINTMAX_MAX;
         goto label_return;
     }
     b = base;
     /* Swallow leading whitespace and get sign, if any. */
     neg = false;
     while (true) {
         switch (*p) {
         case '\t': case '\n': case '\v': case '\f': case '\r': case ' ':
             p++;
             break;
         case '-':
             neg = true;
             /* Fall through. */
         case '+':
             p++;
             /* Fall through. */
         default:
             goto label_prefix;
         }
     }
     /* Get prefix, if any. */
     label_prefix:
     /*
      * Note where the first non-whitespace/sign character is so that it is
      * possible to tell whether any digits are consumed (e.g., "  0" vs.
      * "  -x").
      */
     ns = p;
     if (*p == '0') {
         switch (p[1]) {
         case '0': case '1': case '2': case '3': case '4': case '5':
         case '6': case '7':
             if (b == 0) {
                 b = 8;
             }
             if (b == 8) {
                 p++;
             }
             break;
         case 'X': case 'x':
             switch (p[2]) {
             case '0': case '1': case '2': case '3': case '4':
             case '5': case '6': case '7': case '8': case '9':
             case 'A': case 'B': case 'C': case 'D': case 'E':
             case 'F':
             case 'a': case 'b': case 'c': case 'd': case 'e':
             case 'f':
                 if (b == 0) {
                     b = 16;
                 }
                 if (b == 16) {
                     p += 2;
                 }
                 break;
             default:
                 break;
             }
             break;
         default:
             p++;
             ret = 0;
             goto label_return;
         }
     }
     if (b == 0) {
         b = 10;
     }
     /* Convert. */
     ret = 0;
     while ((*p >= '0' && *p <= '9' && (digit = *p - '0') < b)
         || (*p >= 'A' && *p <= 'Z' && (digit = 10 + *p - 'A') < b)
         || (*p >= 'a' && *p <= 'z' && (digit = 10 + *p - 'a') < b)) {
         uintmax_t pret = ret;
         ret *= b;
         ret += digit;
         if (ret < pret) {
             /* Overflow. */
             set_errno(ERANGE);
             ret = UINTMAX_MAX;
             goto label_return;
         }
         p++;
     }
     if (neg) {
         ret = (uintmax_t)(-((intmax_t)ret));
     }
     if (p == ns) {
         /* No conversion performed. */
         set_errno(EINVAL);
         ret = UINTMAX_MAX;
         goto label_return;
     }
 label_return:
     if (endptr != NULL) {
         if (p == ns) {
             /* No characters were converted. */
             *endptr = (char *)nptr;
         } else {
             *endptr = (char *)p;
         }
     }
     return ret;
 }
References b, NULL, ret, set_errno(), and UINTMAX_MAX.
Referenced by malloc_vsnprintf().
malloc_vcprintf()
size_t void malloc_vcprintf (void(*)(void *, const char *) write_cb, void * cbopaque, const char * format, va_list ap)
Definition at line 623 of file malloc_io.c.
{
     char buf[MALLOC_PRINTF_BUFSIZE];
     if (write_cb == NULL) {
         /*
          * The caller did not provide an alternate write_cb callback
          * function, so use the default one.  malloc_write() is an
          * inline function, so use malloc_message() directly here.
          */
         write_cb = (je_malloc_message != NULL) ? je_malloc_message :
             wrtmessage;
     }
     malloc_vsnprintf(buf, sizeof(buf), format, ap);
     write_cb(cbopaque, buf);
 }
References format(), je_malloc_message, MALLOC_PRINTF_BUFSIZE, malloc_vsnprintf(), NULL, and wrtmessage().
Referenced by malloc_cprintf(), and malloc_printf().
malloc_vsnprintf()
size_t malloc_vsnprintf (char * str, size_t size, const char * format, va_list ap)
Definition at line 327 of file malloc_io.c.
{
     size_t i;
     const char *f;
 #define APPEND_C(c) do {                        \
     if (i < size) {                         \
         str[i] = (c);                       \
     }                               \
     i++;                                \
 } while (0)
 #define APPEND_S(s, slen) do {                      \
     if (i < size) {                         \
         size_t cpylen = (slen <= size - i) ? slen : size - i;   \
         memcpy(&str[i], s, cpylen);             \
     }                               \
     i += slen;                          \
 } while (0)
 #define APPEND_PADDED_S(s, slen, width, left_justify) do {      \
     /* Left padding. */                     \
     size_t pad_len = (width == -1) ? 0 : ((slen < (size_t)width) ?  \
         (size_t)width - slen : 0);                  \
     if (!left_justify && pad_len != 0) {                \
         size_t j;                       \
         for (j = 0; j < pad_len; j++) {             \
             APPEND_C(' ');                  \
         }                           \
     }                               \
     /* Value. */                            \
     APPEND_S(s, slen);                      \
     /* Right padding. */                        \
     if (left_justify && pad_len != 0) {             \
         size_t j;                       \
         for (j = 0; j < pad_len; j++) {             \
             APPEND_C(' ');                  \
         }                           \
     }                               \
 } while (0)
 #define GET_ARG_NUMERIC(val, len) do {                  \
     switch ((unsigned char)len) {                   \
     case '?':                           \
         val = va_arg(ap, int);                  \
         break;                          \
     case '?' | 0x80:                        \
         val = va_arg(ap, unsigned int);             \
         break;                          \
     case 'l':                           \
         val = va_arg(ap, long);                 \
         break;                          \
     case 'l' | 0x80:                        \
         val = va_arg(ap, unsigned long);            \
         break;                          \
     case 'q':                           \
         val = va_arg(ap, long long);                \
         break;                          \
     case 'q' | 0x80:                        \
         val = va_arg(ap, unsigned long long);           \
         break;                          \
     case 'j':                           \
         val = va_arg(ap, intmax_t);             \
         break;                          \
     case 'j' | 0x80:                        \
         val = va_arg(ap, uintmax_t);                \
         break;                          \
     case 't':                           \
         val = va_arg(ap, ptrdiff_t);                \
         break;                          \
     case 'z':                           \
         val = va_arg(ap, ssize_t);              \
         break;                          \
     case 'z' | 0x80:                        \
         val = va_arg(ap, size_t);               \
         break;                          \
     case 'p': /* Synthetic; used for %p. */             \
         val = va_arg(ap, uintptr_t);                \
         break;                          \
     default:                            \
         not_reached();                      \
         val = 0;                        \
     }                               \
 } while (0)
     i = 0;
     f = format;
     while (true) {
         switch (*f) {
         case '\0': goto label_out;
         case '%': {
             bool alt_form = false;
             bool left_justify = false;
             bool plus_space = false;
             bool plus_plus = false;
             int prec = -1;
             int width = -1;
             unsigned char len = '?';
             char *s;
             size_t slen;
             f++;
             /* Flags. */
             while (true) {
                 switch (*f) {
                 case '#':
                     assert(!alt_form);
                     alt_form = true;
                     break;
                 case '-':
                     assert(!left_justify);
                     left_justify = true;
                     break;
                 case ' ':
                     assert(!plus_space);
                     plus_space = true;
                     break;
                 case '+':
                     assert(!plus_plus);
                     plus_plus = true;
                     break;
                 default: goto label_width;
                 }
                 f++;
             }
             /* Width. */
             label_width:
             switch (*f) {
             case '*':
                 width = va_arg(ap, int);
                 f++;
                 if (width < 0) {
                     left_justify = true;
                     width = -width;
                 }
                 break;
             case '0': case '1': case '2': case '3': case '4':
             case '5': case '6': case '7': case '8': case '9': {
                 uintmax_t uwidth;
                 set_errno(0);
                 uwidth = malloc_strtoumax(f, (char **)&f, 10);
                 assert(uwidth != UINTMAX_MAX || get_errno() !=
                     ERANGE);
                 width = (int)uwidth;
                 break;
             } default:
                 break;
             }
             /* Width/precision separator. */
             if (*f == '.') {
                 f++;
             } else {
                 goto label_length;
             }
             /* Precision. */
             switch (*f) {
             case '*':
                 prec = va_arg(ap, int);
                 f++;
                 break;
             case '0': case '1': case '2': case '3': case '4':
             case '5': case '6': case '7': case '8': case '9': {
                 uintmax_t uprec;
                 set_errno(0);
                 uprec = malloc_strtoumax(f, (char **)&f, 10);
                 assert(uprec != UINTMAX_MAX || get_errno() !=
                     ERANGE);
                 prec = (int)uprec;
                 break;
             }
             default: break;
             }
             /* Length. */
             label_length:
             switch (*f) {
             case 'l':
                 f++;
                 if (*f == 'l') {
                     len = 'q';
                     f++;
                 } else {
                     len = 'l';
                 }
                 break;
             case 'q': case 'j': case 't': case 'z':
                 len = *f;
                 f++;
                 break;
             default: break;
             }
             /* Conversion specifier. */
             switch (*f) {
             case '%':
                 /* %% */
                 APPEND_C(*f);
                 f++;
                 break;
             case 'd': case 'i': {
                 intmax_t val JEMALLOC_CC_SILENCE_INIT(0);
                 char buf[D2S_BUFSIZE];
                 GET_ARG_NUMERIC(val, len);
                 s = d2s(val, (plus_plus ? '+' : (plus_space ?
                     ' ' : '-')), buf, &slen);
                 APPEND_PADDED_S(s, slen, width, left_justify);
                 f++;
                 break;
             } case 'o': {
                 uintmax_t val JEMALLOC_CC_SILENCE_INIT(0);
                 char buf[O2S_BUFSIZE];
                 GET_ARG_NUMERIC(val, len | 0x80);
                 s = o2s(val, alt_form, buf, &slen);
                 APPEND_PADDED_S(s, slen, width, left_justify);
                 f++;
                 break;
             } case 'u': {
                 uintmax_t val JEMALLOC_CC_SILENCE_INIT(0);
                 char buf[U2S_BUFSIZE];
                 GET_ARG_NUMERIC(val, len | 0x80);
                 s = u2s(val, 10, false, buf, &slen);
                 APPEND_PADDED_S(s, slen, width, left_justify);
                 f++;
                 break;
             } case 'x': case 'X': {
                 uintmax_t val JEMALLOC_CC_SILENCE_INIT(0);
                 char buf[X2S_BUFSIZE];
                 GET_ARG_NUMERIC(val, len | 0x80);
                 s = x2s(val, alt_form, *f == 'X', buf, &slen);
                 APPEND_PADDED_S(s, slen, width, left_justify);
                 f++;
                 break;
             } case 'c': {
                 unsigned char val;
                 char buf[2];
                 assert(len == '?' || len == 'l');
                 assert_not_implemented(len != 'l');
                 val = va_arg(ap, int);
                 buf[0] = val;
                 buf[1] = '\0';
                 APPEND_PADDED_S(buf, 1, width, left_justify);
                 f++;
                 break;
             } case 's':
                 assert(len == '?' || len == 'l');
                 assert_not_implemented(len != 'l');
                 s = va_arg(ap, char *);
                 slen = (prec < 0) ? strlen(s) : (size_t)prec;
                 APPEND_PADDED_S(s, slen, width, left_justify);
                 f++;
                 break;
             case 'p': {
                 uintmax_t val;
                 char buf[X2S_BUFSIZE];
                 GET_ARG_NUMERIC(val, 'p');
                 s = x2s(val, true, false, buf, &slen);
                 APPEND_PADDED_S(s, slen, width, left_justify);
                 f++;
                 break;
             } default: not_reached();
             }
             break;
         } default: {
             APPEND_C(*f);
             f++;
             break;
         }}
     }
     label_out:
     if (i < size) {
         str[i] = '\0';
     } else {
         str[size - 1] = '\0';
     }
 #undef APPEND_C
 #undef APPEND_S
 #undef APPEND_PADDED_S
 #undef GET_ARG_NUMERIC
     return i;
 }
References APPEND_C, APPEND_PADDED_S, assert, assert_not_implemented, d2s(), D2S_BUFSIZE, f(), format(), GET_ARG_NUMERIC, get_errno(), JEMALLOC_CC_SILENCE_INIT, malloc_strtoumax(), not_reached, o2s(), O2S_BUFSIZE, ret, set_errno(), u2s(), U2S_BUFSIZE, UINTMAX_MAX, width, x2s(), and X2S_BUFSIZE.
Referenced by malloc_snprintf(), and malloc_vcprintf().
malloc_write()
void malloc_write (const char * s)
Definition at line 83 of file malloc_io.c.
{
     if (je_malloc_message != NULL) {
         je_malloc_message(NULL, s);
     } else {
         wrtmessage(NULL, s);
     }
 }
References je_malloc_message, NULL, and wrtmessage().
malloc_write_fd()
void void static ssize_t malloc_write_fd (int fd, const void * buf, size_t count) inline static
Definition at line 67 of file malloc_io.h.
{
 #if defined(JEMALLOC_USE_SYSCALL) && defined(SYS_write)
     /*
      * Use syscall(2) rather than write(2) when possible in order to avoid
      * the possibility of memory allocation within libc.  This is necessary
      * on FreeBSD; most operating systems do not have this problem though.
      *
      * syscall() returns long or int, depending on platform, so capture the
      * result in the widest plausible type to avoid compiler warnings.
      */
     long result = syscall(SYS_write, fd, buf, count);
 #else
     ssize_t result = (ssize_t)write(fd, buf,
 #ifdef _WIN32
         (unsigned int)
 #endif
         count);
 #endif
     return (ssize_t)result;
 }
References count(), and write.
Referenced by prof_dump_flush(), and wrtmessage().