Azerotcore-wotlk: InstanceSave Class Reference
InstanceSave Class Reference
#include <InstanceSaveMgr.h>
Public Member Functions
InstanceSave (uint16 MapId, uint32 InstanceId, Difficulty difficulty, time_t resetTime, time_t extendedResetTime)
~InstanceSave ()
uint32 GetInstanceId () const
uint32 GetMapId () const
Difficulty GetDifficulty () const
void InsertToDB ()
std::string GetInstanceData () const
void SetInstanceData (std::string str)
uint32 GetCompletedEncounterMask () const
void SetCompletedEncounterMask (uint32 mask)
time_t GetResetTime () const
time_t GetExtendedResetTime () const
time_t GetResetTimeForDB ()
void SetResetTime (time_t resetTime)
void SetExtendedResetTime (time_t extendedResetTime)
bool CanReset () const
void SetCanReset (bool canReset)
InstanceTemplate const * GetTemplate ()
MapEntry const * GetMapEntry ()
void AddPlayer (ObjectGuid guid)
bool RemovePlayer (ObjectGuid guid, InstanceSaveMgr *ism)
Private Attributes
GuidList m_playerList
time_t m_resetTime
time_t m_extendedResetTime
uint32 m_instanceid
uint32 m_mapid
Difficulty m_difficulty
bool m_canReset
std::string m_instanceData
uint32 m_completedEncounterMask
std::mutex _lock
Friends
class InstanceSaveMgr
Detailed Description
Definition at line 55 of file InstanceSaveMgr.h.
Constructor & Destructor Documentation
InstanceSave()
InstanceSave::InstanceSave (uint16 MapId, uint32 InstanceId, Difficulty difficulty, time_t resetTime, time_t extendedResetTime)
Definition at line 144 of file InstanceSaveMgr.cpp.
     : m_resetTime(resetTime), m_extendedResetTime(extendedResetTime), m_instanceid(InstanceId), m_mapid(MapId), m_difficulty(IsSharedDifficultyMap(MapId) ? Difficulty(difficulty % 2) : difficulty), m_canReset(true), m_instanceData(""), m_completedEncounterMask(0)
 {
     sScriptMgr->OnConstructInstanceSave(this);
 }
References sScriptMgr.
~InstanceSave()
InstanceSave::~InstanceSave ()
Definition at line 150 of file InstanceSaveMgr.cpp.
 {
     ASSERT(m_playerList.empty());
     sScriptMgr->OnDestructInstanceSave(this);
 }
References ASSERT, m_playerList, and sScriptMgr.
Member Function Documentation
AddPlayer()
void InstanceSave::AddPlayer (ObjectGuid guid)
Definition at line 210 of file InstanceSaveMgr.cpp.
 {
     std::lock_guard<std::mutex> guard(_lock);
     m_playerList.push_back(guid);
 }
References _lock, and m_playerList.
Referenced by InstanceSaveMgr::PlayerBindToInstance().
CanReset()
bool InstanceSave::CanReset () const inline
Definition at line 81 of file InstanceSaveMgr.h.
 { return m_canReset; }
References m_canReset.
Referenced by InstanceMap::AddPlayerToMap(), instance_commandscript::HandleInstanceListBindsCommand(), instance_commandscript::HandleInstanceUnbindCommand(), Player::ResetInstances(), and Group::ResetInstances().
GetCompletedEncounterMask()
uint32 InstanceSave::GetCompletedEncounterMask () const inline
Definition at line 71 of file InstanceSaveMgr.h.
 { return m_completedEncounterMask; }
References m_completedEncounterMask.
Referenced by MapInstanced::CreateInstance().
GetDifficulty()
Difficulty InstanceSave::GetDifficulty () const inline
Definition at line 63 of file InstanceSaveMgr.h.
 { return m_difficulty; }
References m_difficulty.
Referenced by InstanceMap::AddPlayerToMap(), GetResetTimeForDB(), WorldSession::HandleCalendarGetCalendar(), instance_commandscript::HandleInstanceListBindsCommand(), instance_commandscript::HandleInstanceUnbindCommand(), InsertToDB(), InstanceMap::PermBindAllPlayers(), InstanceSaveMgr::PlayerBindToInstance(), WorldSession::SendCalendarRaidLockout(), WorldSession::SendCalendarRaidLockoutUpdated(), Player::SendRaidInfo(), and InstanceSaveMgr::UnbindAllFor().
GetExtendedResetTime()
time_t InstanceSave::GetExtendedResetTime () const inline
Definition at line 76 of file InstanceSaveMgr.h.
 { return m_extendedResetTime; }
References m_extendedResetTime.
Referenced by WorldSession::HandleCalendarGetCalendar(), instance_commandscript::HandleInstanceListBindsCommand(), instance_commandscript::HandleInstanceUnbindCommand(), WorldSession::SendCalendarRaidLockoutUpdated(), Player::SendInstanceResetWarning(), and Player::SendRaidInfo().
GetInstanceData()
std::string InstanceSave::GetInstanceData () const inline
Definition at line 69 of file InstanceSaveMgr.h.
 { return m_instanceData; }
References m_instanceData.
Referenced by MapInstanced::CreateInstance().
GetInstanceId()
uint32 InstanceSave::GetInstanceId () const inline
Definition at line 61 of file InstanceSaveMgr.h.
 { return m_instanceid; }
References m_instanceid.
Referenced by Group::_cancelHomebindIfInstance(), InstanceMap::AddPlayerToMap(), InstanceSaveMgr::DeleteInstanceSaveIfNeeded(), WorldSession::HandleCalendarGetCalendar(), instance_commandscript::HandleInstanceListBindsCommand(), instance_commandscript::HandleInstanceUnbindCommand(), WorldSession::HandleSetSavedInstanceExtend(), InstanceSaveMgr::LoadCharacterBinds(), Player::LoadFromDB(), InstanceSaveMgr::PlayerBindToInstance(), InstanceSaveMgr::PlayerGetDestinationInstanceId(), RemovePlayer(), Player::ResetInstances(), Group::ResetInstances(), WorldSession::SendCalendarRaidLockout(), and Player::SendRaidInfo().
GetMapEntry()
MapEntry const * InstanceSave::GetMapEntry ()
Definition at line 205 of file InstanceSaveMgr.cpp.
 {
     return sMapStore.LookupEntry(m_mapid);
 }
References m_mapid, and sMapStore.
GetMapId()
uint32 InstanceSave::GetMapId () const inline
Definition at line 62 of file InstanceSaveMgr.h.
 { return m_mapid; }
References m_mapid.
Referenced by InstanceMap::AddPlayerToMap(), InstanceSaveMgr::DeleteInstanceSaveIfNeeded(), GetResetTimeForDB(), WorldSession::HandleCalendarGetCalendar(), InsertToDB(), InstanceMap::PermBindAllPlayers(), InstanceSaveMgr::PlayerBindToInstance(), Player::ResetInstances(), Group::ResetInstances(), WorldSession::SendCalendarRaidLockout(), WorldSession::SendCalendarRaidLockoutUpdated(), Player::SendRaidInfo(), and InstanceSaveMgr::UnbindAllFor().
GetResetTime()
time_t InstanceSave::GetResetTime () const inline
Definition at line 75 of file InstanceSaveMgr.h.
 { return m_resetTime; }
References m_resetTime.
Referenced by GetResetTimeForDB(), WorldSession::HandleCalendarGetCalendar(), instance_commandscript::HandleInstanceListBindsCommand(), instance_commandscript::HandleInstanceUnbindCommand(), WorldSession::SendCalendarRaidLockout(), WorldSession::SendCalendarRaidLockoutUpdated(), Player::SendInstanceResetWarning(), and Player::SendRaidInfo().
GetResetTimeForDB()
time_t InstanceSave::GetResetTimeForDB ()
Definition at line 189 of file InstanceSaveMgr.cpp.
 {
     // only save the reset time for normal instances
     const MapEntry* entry = sMapStore.LookupEntry(GetMapId());
     if (!entry || entry->map_type == MAP_RAID || GetDifficulty() == DUNGEON_DIFFICULTY_HEROIC)
         return 0;
     else
         return GetResetTime();
 }
References DUNGEON_DIFFICULTY_HEROIC, GetDifficulty(), GetMapId(), GetResetTime(), MAP_RAID, MapEntry::map_type, and sMapStore.
Referenced by InsertToDB().
GetTemplate()
InstanceTemplate const * InstanceSave::GetTemplate ()
Definition at line 200 of file InstanceSaveMgr.cpp.
 {
     return sObjectMgr->GetInstanceTemplate(m_mapid);
 }
References m_mapid, and sObjectMgr.
InsertToDB()
void InstanceSave::InsertToDB ()
Definition at line 157 of file InstanceSaveMgr.cpp.
 {
     std::string data;
     uint32 completedEncounters = 0;
     Map* map = sMapMgr->FindMap(GetMapId(), m_instanceid);
     if (map)
     {
         ASSERT(map->IsDungeon());
         if (InstanceScript* instanceScript = map->ToInstanceMap()->GetInstanceScript())
         {
             data = instanceScript->GetSaveData();
             completedEncounters = instanceScript->GetCompletedEncounterMask();
             // pussywizard:
             SetInstanceData(data);
             SetCompletedEncounterMask(completedEncounters);
         }
     }
     CharacterDatabasePreparedStatement* stmt = CharacterDatabase.GetPreparedStatement(CHAR_INS_INSTANCE_SAVE);
     stmt->setUInt32(0, m_instanceid);
     stmt->setUInt16(1, GetMapId());
     stmt->setUInt32(2, uint32(GetResetTimeForDB()));
     stmt->setUInt8(3, uint8(GetDifficulty()));
     stmt->setUInt32(4, completedEncounters);
     stmt->setString(5, data);
     CharacterDatabase.Execute(stmt);
     sScriptMgr->OnInstanceSave(this);
 }
References ASSERT, CHAR_INS_INSTANCE_SAVE, CharacterDatabase, GetDifficulty(), InstanceMap::GetInstanceScript(), GetMapId(), GetResetTimeForDB(), Map::IsDungeon(), m_instanceid, SetCompletedEncounterMask(), SetInstanceData(), PreparedStatementBase::setString(), PreparedStatementBase::setUInt16(), PreparedStatementBase::setUInt32(), PreparedStatementBase::setUInt8(), sMapMgr, sScriptMgr, and Map::ToInstanceMap().
Referenced by InstanceSaveMgr::AddInstanceSave().
RemovePlayer()
bool InstanceSave::RemovePlayer (ObjectGuid guid, InstanceSaveMgr * ism)
Definition at line 216 of file InstanceSaveMgr.cpp.
 {
     std::lock_guard<std::mutex> guard(_lock);
     m_playerList.remove(guid);
     // ism passed as an argument to avoid calling via singleton (might result in a deadlock)
     return ism->DeleteInstanceSaveIfNeeded(this->GetInstanceId(), false);
 }
References _lock, InstanceSaveMgr::DeleteInstanceSaveIfNeeded(), GetInstanceId(), and m_playerList.
Referenced by InstanceSaveMgr::LoadCharacterBinds(), InstanceSaveMgr::PlayerBindToInstance(), InstanceSaveMgr::PlayerUnbindInstance(), and InstanceSaveMgr::PlayerUnbindInstanceNotExtended().
SetCanReset()
void InstanceSave::SetCanReset (bool canReset) inline
Definition at line 82 of file InstanceSaveMgr.h.
 { m_canReset = canReset; }
References m_canReset.
Referenced by InstanceSaveMgr::PlayerBindToInstance().
SetCompletedEncounterMask()
void InstanceSave::SetCompletedEncounterMask (uint32 mask) inline
Definition at line 72 of file InstanceSaveMgr.h.
 { m_completedEncounterMask = mask; }
References m_completedEncounterMask.
Referenced by InsertToDB(), InstanceSaveMgr::LoadInstanceSaves(), and InstanceScript::SetCompletedEncountersMask().
SetExtendedResetTime()
void InstanceSave::SetExtendedResetTime (time_t extendedResetTime) inline
Definition at line 79 of file InstanceSaveMgr.h.
 { m_extendedResetTime = extendedResetTime; }
References m_extendedResetTime.
SetInstanceData()
void InstanceSave::SetInstanceData (std::string str) inline
Definition at line 70 of file InstanceSaveMgr.h.
 { m_instanceData = str; }
References m_instanceData.
Referenced by InsertToDB(), InstanceSaveMgr::LoadInstanceSaves(), and InstanceScript::SaveToDB().
SetResetTime()
void InstanceSave::SetResetTime (time_t resetTime) inline
Definition at line 78 of file InstanceSaveMgr.h.
 { m_resetTime = resetTime; }
References m_resetTime.
Referenced by InstanceSaveMgr::LoadInstanceSaves().
Friends And Related Function Documentation
InstanceSaveMgr
friend class InstanceSaveMgr friend
Definition at line 57 of file InstanceSaveMgr.h.
Member Data Documentation
_lock
std::mutex InstanceSave::_lock private
Definition at line 101 of file InstanceSaveMgr.h.
Referenced by AddPlayer(), and RemovePlayer().
m_canReset
bool InstanceSave::m_canReset private
Definition at line 97 of file InstanceSaveMgr.h.
Referenced by CanReset(), and SetCanReset().
m_completedEncounterMask
uint32 InstanceSave::m_completedEncounterMask private
Definition at line 99 of file InstanceSaveMgr.h.
Referenced by GetCompletedEncounterMask(), and SetCompletedEncounterMask().
m_difficulty
Difficulty InstanceSave::m_difficulty private
Definition at line 96 of file InstanceSaveMgr.h.
Referenced by GetDifficulty().
m_extendedResetTime
time_t InstanceSave::m_extendedResetTime private
Definition at line 93 of file InstanceSaveMgr.h.
Referenced by GetExtendedResetTime(), and SetExtendedResetTime().
m_instanceData
std::string InstanceSave::m_instanceData private
Definition at line 98 of file InstanceSaveMgr.h.
Referenced by GetInstanceData(), and SetInstanceData().
m_instanceid
uint32 InstanceSave::m_instanceid private
Definition at line 94 of file InstanceSaveMgr.h.
Referenced by GetInstanceId(), and InsertToDB().
m_mapid
uint32 InstanceSave::m_mapid private
Definition at line 95 of file InstanceSaveMgr.h.
Referenced by GetMapEntry(), GetMapId(), and GetTemplate().
m_playerList
GuidList InstanceSave::m_playerList private
Definition at line 91 of file InstanceSaveMgr.h.
Referenced by InstanceSaveMgr::_ResetOrWarnAll(), AddPlayer(), InstanceSaveMgr::DeleteInstanceSaveIfNeeded(), RemovePlayer(), InstanceSaveMgr::UnbindAllFor(), and ~InstanceSave().
m_resetTime
time_t InstanceSave::m_resetTime private
Definition at line 92 of file InstanceSaveMgr.h.
Referenced by GetResetTime(), and SetResetTime().
The documentation for this class was generated from the following files:
src/server/game/Instances/InstanceSaveMgr.h
src/server/game/Instances/InstanceSaveMgr.cpp