Azerotcore-wotlk: deps/mysqllite/sql/password.c File Reference
password.c File Reference
#include <password.h>
#include <my_global.h>
#include <my_sys.h>
#include <m_string.h>
#include <sha1.h>
#include "mysql.h"
Macros
#define PVERSION41_CHAR '*'
Functions
void randominit (struct rand_struct *rand_st, ulong seed1, ulong seed2)
double my_rnd (struct rand_struct *rand_st)
void hash_password (ulong *result, const char *password, uint password_len)
void my_make_scrambled_password_323 (char *to, const char *password, size_t pass_len)
void make_scrambled_password_323 (char *to, const char *password)
void scramble_323 (char *to, const char *message, const char *password)
my_bool check_scramble_323 (const unsigned char *scrambled, const char *message, ulong *hash_pass)
static uint8 char_val (uint8 X)
void get_salt_from_password_323 (ulong *res, const char *password)
void make_password_from_salt_323 (char *to, const ulong *salt)
void create_random_string (char *to, uint length, struct rand_struct *rand_st)
char * octet2hex (char *to, const char *str, uint len)
static void hex2octet (uint8 *to, const char *str, uint len)
static void my_crypt (char *to, const uchar *s1, const uchar *s2, uint len)
void my_make_scrambled_password (char *to, const char *password, size_t pass_len)
void make_scrambled_password (char *to, const char *password)
void scramble (char *to, const char *message, const char *password)
my_bool check_scramble (const uchar *scramble_arg, const char *message, const uint8 *hash_stage2)
void get_salt_from_password (uint8 *hash_stage2, const char *password)
void make_password_from_salt (char *to, const uint8 *hash_stage2)
Macro Definition Documentation
PVERSION41_CHAR
#define PVERSION41_CHAR '*'
Definition at line 328 of file password.c.
Function Documentation
char_val()
static uint8 char_val (uint8 X) inline static
Definition at line 253 of file password.c.
 {
   return (uint) (X >= '0' && X <= '9' ? X-'0' :
       X >= 'A' && X <= 'Z' ? X-'A'+10 : X-'a'+10);
 }
References X.
Referenced by get_salt_from_password_323(), and hex2octet().
check_scramble()
my_bool check_scramble (const uchar * scramble_arg, const char * message, const uint8 * hash_stage2)
Definition at line 513 of file password.c.
 {
   SHA1_CONTEXT sha1_context;
   uint8 buf[SHA1_HASH_SIZE];
   uint8 hash_stage2_reassured[SHA1_HASH_SIZE];
   mysql_sha1_reset(&sha1_context);
   /* create key to encrypt scramble */
   mysql_sha1_input(&sha1_context, (const uint8 *) message, SCRAMBLE_LENGTH);
   mysql_sha1_input(&sha1_context, hash_stage2, SHA1_HASH_SIZE);
   mysql_sha1_result(&sha1_context, buf);
   /* encrypt scramble */
     my_crypt((char *) buf, buf, scramble_arg, SCRAMBLE_LENGTH);
   /* now buf supposedly contains hash_stage1: so we can get hash_stage2 */
   mysql_sha1_reset(&sha1_context);
   mysql_sha1_input(&sha1_context, buf, SHA1_HASH_SIZE);
   mysql_sha1_result(&sha1_context, hash_stage2_reassured);
   return memcmp(hash_stage2, hash_stage2_reassured, SHA1_HASH_SIZE);
 }
References message(), my_crypt(), mysql_sha1_input(), mysql_sha1_reset(), mysql_sha1_result(), SCRAMBLE_LENGTH, and SHA1_HASH_SIZE.
check_scramble_323()
my_bool check_scramble_323 (const unsigned char * scrambled, const char * message, ulong * hash_pass)
Definition at line 226 of file password.c.
 {
   struct rand_struct rand_st;
   ulong hash_message[2];
   uchar buff[16],*to,extra;                     /* Big enough for check */
   const uchar *pos;
   hash_password(hash_message, message, SCRAMBLE_LENGTH_323);
   randominit(&rand_st,hash_pass[0] ^ hash_message[0],
              hash_pass[1] ^ hash_message[1]);
   to=buff;
   DBUG_ASSERT(sizeof(buff) > SCRAMBLE_LENGTH_323);
   for (pos=scrambled ; *pos && to < buff+sizeof(buff) ; pos++)
     *to++=(char) (floor(my_rnd(&rand_st)*31)+64);
   if (pos-scrambled != SCRAMBLE_LENGTH_323)
     return 1;
   extra=(char) (floor(my_rnd(&rand_st)*31));
   to=buff;
   while (*scrambled)
   {
     if (*scrambled++ != (uchar) (*to++ ^ extra))
       return 1;                                 /* Wrong password */
   }
   return 0;
 }
References DBUG_ASSERT, G3D::floor(), hash_password(), message(), my_rnd(), pos(), randominit(), and SCRAMBLE_LENGTH_323.
create_random_string()
void create_random_string (char * to, uint length, struct rand_struct * rand_st)
Definition at line 316 of file password.c.
 {
   char *end= to + length;
   /* Use pointer arithmetics as it is faster way to do so. */
   for (; to < end; to++)
     *to= (char) (my_rnd(rand_st)*94+33);
   *to= '\0';
 }
References G3D::length(), and my_rnd().
get_salt_from_password()
void get_salt_from_password (uint8 * hash_stage2, const char * password)
Definition at line 545 of file password.c.
 {
   hex2octet(hash_stage2, password+1 /* skip '*' */, SHA1_HASH_SIZE * 2);
 }
References hex2octet(), and SHA1_HASH_SIZE.
get_salt_from_password_323()
void get_salt_from_password_323 (ulong * res, const char * password)
Definition at line 271 of file password.c.
 {
   res[0]= res[1]= 0;
   if (password)
   {
     while (*password)
     {
       ulong val=0;
       uint i;
       for (i=0 ; i < 8 ; i++)
         val=(val << 4)+char_val(*password++);
       *res++=val;
     }
   }
 }
References char_val().
hash_password()
void hash_password (ulong * result, const char * password, uint password_len)
Definition at line 118 of file password.c.
 {
   register ulong nr=1345345333L, add=7, nr2=0x12345671L;
   ulong tmp;
   const char *password_end= password + password_len;
   for (; password < password_end; password++)
   {
     if (*password == ' ' || *password == '\t')
       continue;                                 /* skip space in password */
     tmp= (ulong) (uchar) *password;
     nr^= (((nr & 63)+add)*tmp)+ (nr << 8);
     nr2+=(nr2 << 8) ^ nr;
     add+=tmp;
   }
   result[0]=nr & (((ulong) 1L << 31) -1L); /* Don't use sign bit (str2int) */;
   result[1]=nr2 & (((ulong) 1L << 31) -1L);
 }
Referenced by check_scramble_323(), my_make_scrambled_password_323(), and scramble_323().
hex2octet()
static void hex2octet (uint8 * to, const char * str, uint len) static
Definition at line 367 of file password.c.
 {
   const char *str_end= str + len;
   while (str < str_end)
   {
     register char tmp= char_val(*str++);
     *to++= (tmp << 4) | char_val(*str++);
   }
 }
References char_val().
Referenced by get_salt_from_password().
make_password_from_salt()
void make_password_from_salt (char * to, const uint8 * hash_stage2)
Definition at line 558 of file password.c.
 {
   *to++= PVERSION41_CHAR;
   octet2hex(to, (const char*) hash_stage2, SHA1_HASH_SIZE);
 }
References octet2hex(), PVERSION41_CHAR, and SHA1_HASH_SIZE.
make_password_from_salt_323()
void make_password_from_salt_323 (char * to, const ulong * salt)
Definition at line 296 of file password.c.
 {
   sprintf(to,"%08lx%08lx", salt[0], salt[1]);
 }
References sprintf().
make_scrambled_password()
void make_scrambled_password (char * to, const char * password)
Definition at line 444 of file password.c.
 {
   my_make_scrambled_password(to, password, strlen(password));
 }
References my_make_scrambled_password().
make_scrambled_password_323()
void make_scrambled_password_323 (char * to, const char * password)
Definition at line 167 of file password.c.
 {
   my_make_scrambled_password_323(to, password, strlen(password));
 }
References my_make_scrambled_password_323().
my_crypt()
static void my_crypt (char * to, const uchar * s1, const uchar * s2, uint len) static
Definition at line 391 of file password.c.
 {
   const uint8 *s1_end= s1 + len;
   while (s1 < s1_end)
     *to++= *s1++ ^ *s2++;
 }
Referenced by check_scramble(), and scramble().
my_make_scrambled_password()
void my_make_scrambled_password (char * to, const char * password, size_t pass_len)
Definition at line 412 of file password.c.
 {
   SHA1_CONTEXT sha1_context;
   uint8 hash_stage2[SHA1_HASH_SIZE];
   mysql_sha1_reset(&sha1_context);
   /* stage 1: hash password */
   mysql_sha1_input(&sha1_context, (uint8 *) password, (uint) pass_len);
   mysql_sha1_result(&sha1_context, (uint8 *) to);
   /* stage 2: hash stage1 output */
   mysql_sha1_reset(&sha1_context);
   mysql_sha1_input(&sha1_context, (uint8 *) to, SHA1_HASH_SIZE);
   /* separate buffer is used to pass 'to' in octet2hex */
   mysql_sha1_result(&sha1_context, hash_stage2);
   /* convert hash_stage2 to hex string */
   *to++= PVERSION41_CHAR;
   octet2hex(to, (const char*) hash_stage2, SHA1_HASH_SIZE);
 }
References mysql_sha1_input(), mysql_sha1_reset(), mysql_sha1_result(), octet2hex(), PVERSION41_CHAR, and SHA1_HASH_SIZE.
Referenced by make_scrambled_password().
my_make_scrambled_password_323()
void my_make_scrambled_password_323 (char * to, const char * password, size_t pass_len)
Definition at line 147 of file password.c.
 {
   ulong hash_res[2];
   hash_password(hash_res, password, (uint) pass_len);
   sprintf(to, "%08lx%08lx", hash_res[0], hash_res[1]);
 }
References hash_password(), and sprintf().
Referenced by make_scrambled_password_323().
my_rnd()
double my_rnd (struct rand_struct * rand_st)
Definition at line 100 of file password.c.
 {
   rand_st->seed1=(rand_st->seed1*3+rand_st->seed2) % rand_st->max_value;
   rand_st->seed2=(rand_st->seed1+rand_st->seed2+33) % rand_st->max_value;
   return (((double) rand_st->seed1)/rand_st->max_value_dbl);
 }
References rand_struct::max_value, rand_struct::max_value_dbl, rand_struct::seed1, and rand_struct::seed2.
Referenced by check_scramble_323(), create_random_string(), and scramble_323().
octet2hex()
char* octet2hex (char * to, const char * str, uint len)
Definition at line 343 of file password.c.
 {
   const char *str_end= str + len;
   for (; str != str_end; ++str)
   {
     *to++= _dig_vec_upper[((uchar) *str) >> 4];
     *to++= _dig_vec_upper[((uchar) *str) & 0x0F];
   }
   *to= '\0';
   return to;
 }
References _dig_vec_upper.
Referenced by make_password_from_salt(), and my_make_scrambled_password().
randominit()
void randominit (struct rand_struct * rand_st, ulong seed1, ulong seed2)
Definition at line 79 of file password.c.
 {                                               /* For mysql 3.21.# */
 #ifdef HAVE_purify
   bzero((char*) rand_st,sizeof(*rand_st));      /* Avoid UMC varnings */
 #endif
   rand_st->max_value= 0x3FFFFFFFL;
   rand_st->max_value_dbl=(double) rand_st->max_value;
   rand_st->seed1=seed1%rand_st->max_value ;
   rand_st->seed2=seed2%rand_st->max_value;
 }
References bzero, rand_struct::max_value, rand_struct::max_value_dbl, rand_struct::seed1, and rand_struct::seed2.
Referenced by check_scramble_323(), and scramble_323().
scramble()
void scramble (char * to, const char * message, const char * password)
Definition at line 468 of file password.c.
 {
   SHA1_CONTEXT sha1_context;
   uint8 hash_stage1[SHA1_HASH_SIZE];
   uint8 hash_stage2[SHA1_HASH_SIZE];
   mysql_sha1_reset(&sha1_context);
   /* stage 1: hash password */
   mysql_sha1_input(&sha1_context, (uint8 *) password, (uint) strlen(password));
   mysql_sha1_result(&sha1_context, hash_stage1);
   /* stage 2: hash stage 1; note that hash_stage2 is stored in the database */
   mysql_sha1_reset(&sha1_context);
   mysql_sha1_input(&sha1_context, hash_stage1, SHA1_HASH_SIZE);
   mysql_sha1_result(&sha1_context, hash_stage2);
   /* create crypt string as sha1(message, hash_stage2) */;
   mysql_sha1_reset(&sha1_context);
   mysql_sha1_input(&sha1_context, (const uint8 *) message, SCRAMBLE_LENGTH);
   mysql_sha1_input(&sha1_context, hash_stage2, SHA1_HASH_SIZE);
   /* xor allows 'from' and 'to' overlap: lets take advantage of it */
   mysql_sha1_result(&sha1_context, (uint8 *) to);
   my_crypt(to, (const uchar *) to, hash_stage1, SCRAMBLE_LENGTH);
 }
References message(), my_crypt(), mysql_sha1_input(), mysql_sha1_reset(), mysql_sha1_result(), SCRAMBLE_LENGTH, and SHA1_HASH_SIZE.
Referenced by native_password_auth_client().
scramble_323()
void scramble_323 (char * to, const char * message, const char * password)
Definition at line 185 of file password.c.
 {
   struct rand_struct rand_st;
   ulong hash_pass[2], hash_message[2];
   if (password && password[0])
   {
     char extra, *to_start=to;
     const char *message_end= message + SCRAMBLE_LENGTH_323;
     hash_password(hash_pass,password, (uint) strlen(password));
     hash_password(hash_message, message, SCRAMBLE_LENGTH_323);
     randominit(&rand_st,hash_pass[0] ^ hash_message[0],
                hash_pass[1] ^ hash_message[1]);
     for (; message < message_end; message++)
       *to++= (char) (floor(my_rnd(&rand_st)*31)+64);
     extra=(char) (floor(my_rnd(&rand_st)*31));
     while (to_start != to)
       *(to_start++)^=extra;
   }
   *to= 0;
 }
References G3D::floor(), hash_password(), message(), my_rnd(), randominit(), and SCRAMBLE_LENGTH_323.
Referenced by old_password_auth_client().