Azerotcore-wotlk: boss_mimiron::boss_mimironAI Struct Reference
boss_mimiron::boss_mimironAI Struct Reference
Public Member Functions
boss_mimironAI (Creature *pCreature)
void Reset () override
void AttackStart (Unit *who) override
void JustReachedHome () override
void EnterCombat (Unit *) override
void UpdateAI (uint32 diff) override
void MoveInLineOfSight (Unit *) override
void EnterEvadeMode () override
void JustSummoned (Creature *s) override
void SummonedCreatureDespawn (Creature *s) override
void ResetGameObjects ()
void CloseDoorAndButton ()
void SetData (uint32, uint32 value) override
uint32 GetData (uint32 id) const override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature)
~ScriptedAI () override
void AttackStartNoMove (Unit *target)
void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellSchoolMask) override
void JustDied (Unit *) override
void KilledUnit (Unit *) override
void SpellHit (Unit *, SpellInfo const *) override
void SpellHitTarget (Unit *, SpellInfo const *) override
void MovementInform (uint32, uint32) override
void OnPossess (bool)
bool IsInRoom (const Position *pos, Axis axis, bool above)
void DoStartMovement (Unit *target, float distance=0.0f, float angle=0.0f)
void DoStartNoMovement (Unit *target)
void DoStopAttack ()
void DoCastSpell (Unit *target, SpellInfo const *spellInfo, bool triggered=false)
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoPlayMusic (uint32 soundId, bool zone)
void DoResetThreat ()
float DoGetThreat (Unit *unit)
void DoModifyThreatPercent (Unit *unit, int32 pct)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float o)
void DoTeleportAll (float x, float y, float z, float o)
Unit * DoSelectLowestHpFriendly (float range, uint32 minHPDiff=1)
std::list< Creature * > DoFindFriendlyCC (float range)
std::list< Creature * > DoFindFriendlyMissingBuff (float range, uint32 spellId)
Player * GetPlayerAtMinimumRange (float minRange)
Creature * DoSpawnCreature (uint32 entry, float offsetX, float offsetY, float offsetZ, float angle, uint32 type, uint32 despawntime)
bool HealthBelowPct (uint32 pct) const
bool HealthAbovePct (uint32 pct) const
SpellInfo const * SelectSpell (Unit *target, uint32 school, uint32 mechanic, SelectTargetType targets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect effect)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
void SetCombatMovement (bool allowMovement)
bool IsCombatMovementAllowed () const
bool EnterEvadeIfOutOfCombatArea ()
virtual bool CheckEvadeIfOutOfCombatArea () const
bool IsHeroic () const
Difficulty GetDifficulty () const
bool Is25ManRaid () const
template<class T >
const T & DUNGEON_MODE (const T &normal5, const T &heroic10) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25) const
template<class T >
const T & RAID_MODE (const T &normal10, const T &normal25, const T &heroic10, const T &heroic25) const
Player * SelectTargetFromPlayerList (float maxdist, uint32 excludeAura=0, bool mustBeInLOS=false) const
Public Member Functions inherited from CreatureAI
void Talk (uint8 id, WorldObject const *whisperTarget=nullptr)
CreatureAI (Creature *creature)
~CreatureAI () override
void MoveCircleChecks ()
void MoveBackwardsChecks ()
void MoveInLineOfSight_Safe (Unit *who)
== Reactions At =================================
void TriggerAlert (Unit const *who) const
virtual bool CanRespawn ()
virtual void IsSummonedBy (Unit *)
virtual void SummonedCreatureDies (Creature *, Unit *)
virtual void SummonedCreatureDespawnAll ()
virtual void AttackedBy (Unit *)
virtual bool IsEscorted ()
virtual void JustRespawned ()
void OnCharmed (bool apply) override
void DoZoneInCombat (Creature *creature=nullptr, float maxRangeToNearestTarget=250.0f)
virtual void ReceiveEmote (Player *, uint32)
virtual void OwnerAttackedBy (Unit *)
virtual void OwnerAttacked (Unit *)
virtual void CorpseRemoved (uint32 &)
== Triggered Actions Requested ==================
virtual void PassengerBoarded (Unit *, int8, bool)
== Fields =======================================
virtual void OnSpellClick (Unit *, bool &)
virtual bool CanSeeAlways (WorldObject const *)
virtual bool CanBeSeen (Player const *)
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
virtual ~UnitAI ()
virtual bool CanAIAttack (Unit const *) const
virtual void InitializeAI ()
virtual void DoAction (int32)
virtual void SetGUID (ObjectGuid, int32=0)
virtual ObjectGuid GetGUID (int32=0) const
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position=0, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
Unit * SelectTarget (SelectAggroTarget targetType, uint32 position, PREDICATE const &predicate)
void SelectTargetList (std::list< Unit * > &targetList, uint32 num, SelectAggroTarget targetType, float dist=0.0f, bool playerOnly=false, int32 aura=0)
template<class PREDICATE >
void SelectTargetList (std::list< Unit * > &targetList, PREDICATE const &predicate, uint32 maxTargets, SelectAggroTarget targetType)
virtual void DamageDealt (Unit *, uint32 &, DamageEffectType)
virtual void HealReceived (Unit *, uint32 &)
virtual void HealDone (Unit *, uint32 &)
void AttackStartCaster (Unit *victim, float dist)
void DoAddAuraToAllHostilePlayers (uint32 spellid)
void DoCast (uint32 spellId)
void DoCast (Unit *victim, uint32 spellId, bool triggered=false)
void DoCastSelf (uint32 spellId, bool triggered=false)
void DoCastToAllHostilePlayers (uint32 spellid, bool triggered=false)
void DoCastVictim (uint32 spellId, bool triggered=false)
void DoCastAOE (uint32 spellId, bool triggered=false)
void DoCastRandomTarget (uint32 spellId, uint32 threatTablePosition=0, float dist=0.0f, bool playerOnly=true, bool triggered=false)
float DoGetSpellMaxRange (uint32 spellId, bool positive=false)
void DoMeleeAttackIfReady ()
bool DoSpellAttackIfReady (uint32 spell)
virtual void sGossipHello (Player *)
virtual void sGossipSelect (Player *, uint32, uint32)
virtual void sGossipSelectCode (Player *, uint32, uint32, char const *)
virtual void sQuestAccept (Player *, Quest const *)
virtual void sQuestSelect (Player *, Quest const *)
virtual void sQuestComplete (Player *, Quest const *)
virtual void sQuestReward (Player *, Quest const *, uint32)
virtual void sOnGameEvent (bool, uint16)
Public Attributes
InstanceScript * pInstance
EventMap events
SummonList summons
bool bIsEvading
bool hardmode
bool berserk
bool bAchievProximityMine
bool bAchievBombBot
bool bAchievRocketStrike
uint32 allowedFlameSpreadTime
bool changeAllowedFlameSpreadTime
uint8 minutesTalkNum
uint32 outofCombatTimer
Public Attributes inherited from ScriptedAI
Creature * me
bool IsFleeing
Additional Inherited Members
Public Types inherited from ScriptedAI
enum class Axis { AXIS_X , AXIS_Y }
Static Public Member Functions inherited from UnitAI
static void FillAISpellInfo ()
Static Public Attributes inherited from UnitAI
static AISpellInfoType * AISpellInfo
Protected Member Functions inherited from CreatureAI
bool UpdateVictim ()
bool UpdateVictimWithGaze ()
void SetGazeOn (Unit *target)
Creature * DoSummon (uint32 entry, Position const &pos, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummon (uint32 entry, WorldObject *obj, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
Creature * DoSummonFlyer (uint32 entry, WorldObject *obj, float flightZ, float radius=5.0f, uint32 despawnTime=30000, TempSummonType summonType=TEMPSUMMON_CORPSE_TIMED_DESPAWN)
bool _EnterEvadeMode ()
Protected Attributes inherited from CreatureAI
Creature *const me
Protected Attributes inherited from UnitAI
Unit *const me
Detailed Description
Definition at line 299 of file boss_mimiron.cpp.
Constructor & Destructor Documentation
boss_mimironAI()
boss_mimiron::boss_mimironAI::boss_mimironAI (Creature * pCreature) inline
Definition at line 301 of file boss_mimiron.cpp.
                                             : ScriptedAI(pCreature), summons(me)
         {
             pInstance = me->GetInstanceScript();
             if (!me->IsAlive())
                 if (pInstance)
                     pInstance->SetData(TYPE_MIMIRON, DONE);
             bIsEvading = false;
         }
References bIsEvading, DONE, WorldObject::GetInstanceScript(), Unit::IsAlive(), ScriptedAI::me, pInstance, ZoneScript::SetData(), and TYPE_MIMIRON.
Member Function Documentation
AttackStart()
void boss_mimiron::boss_mimironAI::AttackStart (Unit * who) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 343 of file boss_mimiron.cpp.
         {
             if (who)
                 me->Attack(who, true); // skip following
         }
References Unit::Attack(), and ScriptedAI::me.
CloseDoorAndButton()
void boss_mimiron::boss_mimironAI::CloseDoorAndButton () inline
Definition at line 907 of file boss_mimiron.cpp.
         {
             if( pInstance )
                 for( uint16 i = 0; i < 3; ++i )
                     if( ObjectGuid guid = pInstance->GetGuidData(DATA_GO_MIMIRON_DOOR_1 + i) )
                         if( GameObject* door = ObjectAccessor::GetGameObject(*me, guid) )
                             if( door->GetGoState() != GO_STATE_READY )
{
                                 door->SetLootState(GO_READY);
                                 door->UseDoorOrButton(0, false);
                             }
             if( GameObject* button = me->FindNearestGameObject(GO_BUTTON, 200.0f) )
                 if( button->GetGoState() != GO_STATE_ACTIVE )
                 {
                     button->SetLootState(GO_READY);
                     button->UseDoorOrButton(0, false);
                 }
         }
References DATA_GO_MIMIRON_DOOR_1, WorldObject::FindNearestGameObject(), ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), GO_BUTTON, GO_READY, GO_STATE_ACTIVE, GO_STATE_READY, ScriptedAI::me, and pInstance.
Referenced by EnterCombat().
EnterCombat()
void boss_mimiron::boss_mimironAI::EnterCombat (Unit *) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 355 of file boss_mimiron.cpp.
         {
             me->setActive(true);
             DoZoneInCombat();
             me->RemoveAllAuras();
             me->SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
             events.Reset();
             if (Creature* c = GetLMK2())
             {
                 if (c->IsInEvadeMode())
                 {
                     EnterEvadeMode();
                     return;
                 }
                 if (!c->IsAlive())
                     c->Respawn();
                 me->EnterVehicle(c, 1);
             }
             else
             {
                 EnterEvadeMode();
                 return;
             }
             CloseDoorAndButton();
             if (!hardmode)
             {
                 me->Yell(TEXT_LMK2_ACTIVATE, LANG_UNIVERSAL);
                 me->PlayDirectSound(SOUND_TANK_ACTIVE);
                 events.ScheduleEvent(EVENT_SIT_LMK2, 6000);
                 events.ScheduleEvent(EVENT_BERSERK, 900000);
             }
             else
             {
                 events.ScheduleEvent(EVENT_MIMIRON_SAY_HARDMODE, 7000);
                 events.ScheduleEvent(EVENT_BERSERK, Is25ManRaid() ? 10 * MINUTE* IN_MILLISECONDS : 8 * MINUTE * IN_MILLISECONDS);
                 events.ScheduleEvent(EVENT_COMPUTER_SAY_INITIATED, 0);
                 events.ScheduleEvent(EVENT_COMPUTER_SAY_MINUTES, 3000);
                 minutesTalkNum = Is25ManRaid() ? TALK_COMPUTER_TEN : TALK_COMPUTER_EIGHT;
                 for (uint32 i = 0; i < uint32(TALK_COMPUTER_ZERO - minutesTalkNum - 1); ++i)
                     events.ScheduleEvent(EVENT_COMPUTER_SAY_MINUTES, (i + 1)*MINUTE * IN_MILLISECONDS);
                 events.ScheduleEvent(EVENT_COMPUTER_SAY_MINUTES, (TALK_COMPUTER_ZERO - minutesTalkNum)*MINUTE * IN_MILLISECONDS + 6000);
             }
             // ensure LMK2 is at proper position
             if (pInstance)
                 if (Creature* LMK2 = GetLMK2())
                 {
                     LMK2->UpdatePosition(LMK2->GetHomePosition(), true);
                     LMK2->StopMovingOnCurrentPos();
                 }
             if (pInstance && pInstance->GetData(TYPE_MIMIRON) != DONE)
                 pInstance->SetData(TYPE_MIMIRON, IN_PROGRESS);
         }
References mpq::c, CloseDoorAndButton(), DONE, CreatureAI::DoZoneInCombat(), EnterEvadeMode(), Unit::EnterVehicle(), EVENT_BERSERK, EVENT_COMPUTER_SAY_INITIATED, EVENT_COMPUTER_SAY_MINUTES, EVENT_MIMIRON_SAY_HARDMODE, EVENT_SIT_LMK2, ZoneScript::GetData(), GetLMK2, hardmode, IN_MILLISECONDS, IN_PROGRESS, ScriptedAI::Is25ManRaid(), LANG_UNIVERSAL, ScriptedAI::me, MINUTE, minutesTalkNum, pInstance, WorldObject::PlayDirectSound(), Unit::RemoveAllAuras(), WorldObject::setActive(), ZoneScript::SetData(), Object::SetFlag(), SOUND_TANK_ACTIVE, TALK_COMPUTER_EIGHT, TALK_COMPUTER_TEN, TALK_COMPUTER_ZERO, TEXT_LMK2_ACTIVATE, TYPE_MIMIRON, UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE, and Unit::Yell().
EnterEvadeMode()
void boss_mimiron::boss_mimironAI::EnterEvadeMode () inline override virtual
Reimplemented from CreatureAI.
Definition at line 836 of file boss_mimiron.cpp.
         {
             if (bIsEvading)
                 return;
             bIsEvading = true;
             if (Creature* c = GetLMK2())
             {
                 c->AI()->EnterEvadeMode();
             }
             if (Creature* c = GetVX001())
             {
                 c->AI()->EnterEvadeMode();
                 c->DespawnOrUnsummon();
             }
             if (Creature* c = GetACU())
             {
                 c->AI()->EnterEvadeMode();
                 c->DespawnOrUnsummon();
             }
             summons.DoAction(1337); // despawn summons of summons
             me->RemoveAllAuras();
             me->ExitVehicle();
             ScriptedAI::EnterEvadeMode();
             bIsEvading = false;
         }
References bIsEvading, mpq::c, SummonList::DoAction(), CreatureAI::EnterEvadeMode(), Unit::ExitVehicle(), GetACU, GetLMK2, GetVX001, ScriptedAI::me, Unit::RemoveAllAuras(), and summons.
Referenced by EnterCombat(), SetData(), and UpdateAI().
GetData()
uint32 boss_mimiron::boss_mimironAI::GetData (uint32 id) const inline override virtual
Reimplemented from UnitAI.
Definition at line 975 of file boss_mimiron.cpp.
         {
             switch (id)
             {
                 case 1:
                     return (hardmode ? 1 : 0);
                 case 2:
                     return (berserk ? 1 : 0);
                 case 10:
                     return allowedFlameSpreadTime;
                 case 11:
                     return (bAchievProximityMine ? 1 : 0);
                 case 12:
                     return (bAchievBombBot ? 1 : 0);
                 case 13:
                     return (bAchievRocketStrike ? 1 : 0);
             }
             return 0;
         }
References allowedFlameSpreadTime, bAchievBombBot, bAchievProximityMine, bAchievRocketStrike, berserk, and hardmode.
JustReachedHome()
void boss_mimiron::boss_mimironAI::JustReachedHome () inline override virtual
Reimplemented from CreatureAI.
Definition at line 349 of file boss_mimiron.cpp.
         {
             me->setActive(false);
             ScriptedAI::JustReachedHome();
         }
References CreatureAI::JustReachedHome(), ScriptedAI::me, and WorldObject::setActive().
JustSummoned()
void boss_mimiron::boss_mimironAI::JustSummoned (Creature * s) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 866 of file boss_mimiron.cpp.
         {
             summons.Summon(s);
         }
References SummonList::Summon(), and summons.
MoveInLineOfSight()
void boss_mimiron::boss_mimironAI::MoveInLineOfSight (Unit *) inline override virtual
Reimplemented from CreatureAI.
Definition at line 834 of file boss_mimiron.cpp.
 {}
Reset()
void boss_mimiron::boss_mimironAI::Reset () inline override virtual
Reimplemented from ScriptedAI.
Definition at line 324 of file boss_mimiron.cpp.
         {
             hardmode = false;
             berserk = false;
             bAchievProximityMine = false;
             bAchievBombBot = false;
             bAchievRocketStrike = false;
             allowedFlameSpreadTime = 0;
             outofCombatTimer = 0;
             changeAllowedFlameSpreadTime = false;
             ResetGameObjects();
             events.Reset();
             summons.DespawnAll();
             me->RemoveFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_NOT_SELECTABLE);
             if (pInstance && pInstance->GetData(TYPE_MIMIRON) != DONE)
                 pInstance->SetData(TYPE_MIMIRON, NOT_STARTED);
         }
References allowedFlameSpreadTime, bAchievBombBot, bAchievProximityMine, bAchievRocketStrike, berserk, changeAllowedFlameSpreadTime, SummonList::DespawnAll(), DONE, ZoneScript::GetData(), hardmode, ScriptedAI::me, NOT_STARTED, outofCombatTimer, pInstance, Object::RemoveFlag(), ResetGameObjects(), ZoneScript::SetData(), summons, TYPE_MIMIRON, UNIT_FIELD_FLAGS, and UNIT_FLAG_NOT_SELECTABLE.
ResetGameObjects()
void boss_mimiron::boss_mimironAI::ResetGameObjects () inline
Definition at line 876 of file boss_mimiron.cpp.
         {
             if( pInstance )
                 for( uint16 i = 0; i < 3; ++i )
                     if( ObjectGuid guid = pInstance->GetGuidData(DATA_GO_MIMIRON_DOOR_1 + i) )
                         if( GameObject* door = ObjectAccessor::GetGameObject(*me, guid) )
                             if( door->GetGoState() != GO_STATE_ACTIVE )
{
                                 door->SetLootState(GO_READY);
                                 door->UseDoorOrButton(0, false);
                             }
             if( GameObject* elevator = me->FindNearestGameObject(GO_MIMIRON_ELEVATOR, 200.0f) )
             {
                 if( elevator->GetGoState() != GO_STATE_ACTIVE )
                 {
                     elevator->SetLootState(GO_READY);
                     elevator->SetByteValue(GAMEOBJECT_BYTES_1, 0, GO_STATE_ACTIVE);
                 }
                 elevator->EnableCollision(false);
             }
             if( GameObject* button = me->FindNearestGameObject(GO_BUTTON, 200.0f) )
                 if( button->GetGoState() != GO_STATE_READY )
                 {
                     button->SetLootState(GO_READY);
                     button->UseDoorOrButton(0, false);
                     button->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_IN_USE);
                 }
         }
References DATA_GO_MIMIRON_DOOR_1, WorldObject::FindNearestGameObject(), GAMEOBJECT_BYTES_1, GAMEOBJECT_FLAGS, ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), GO_BUTTON, GO_FLAG_IN_USE, GO_MIMIRON_ELEVATOR, GO_READY, GO_STATE_ACTIVE, GO_STATE_READY, ScriptedAI::me, and pInstance.
Referenced by Reset().
SetData()
void boss_mimiron::boss_mimironAI::SetData (uint32 , uint32 value) inline override virtual
Reimplemented from UnitAI.
Definition at line 927 of file boss_mimiron.cpp.
         {
             switch (value) // end of phase 1-3, 4-6 for voltron
             {
                 case 1:
                     events.ScheduleEvent(EVENT_LMK2_RETREAT_INTERVAL, 5000);
                     break;
                 case 2:
                     events.ScheduleEvent(EVENT_VX001_EMOTESTATE_DEATH, 2500);
                     break;
                 case 3:
                     events.ScheduleEvent(EVENT_SAY_ACU_DEAD, 5000);
                     break;
                 case 4:
                 case 5:
                 case 6:
                     {
                         Creature* LMK2 = GetLMK2();
                         Creature* VX001 = GetVX001();
                         Creature* ACU = GetACU();
                         if (!LMK2 || !VX001 || !ACU)
{
                             EnterEvadeMode();
                             return;
                         }
                         Spell* s1 = LMK2->GetCurrentSpell(CURRENT_GENERIC_SPELL);
                         Spell* s2 = VX001->GetCurrentSpell(CURRENT_GENERIC_SPELL);
                         Spell* s3 = ACU->GetCurrentSpell(CURRENT_GENERIC_SPELL);
                         if (s1 && s2 && s3 && s1->GetSpellInfo()->Id == SPELL_SELF_REPAIR && s2->GetSpellInfo()->Id == SPELL_SELF_REPAIR && s3->GetSpellInfo()->Id == SPELL_SELF_REPAIR)
                             events.ScheduleEvent(EVENT_FINISH, 0);
                     }
                     break;
                 case 7:
                     hardmode = true;
                     break;
                 case 11:
                     bAchievProximityMine = true;
                     break;
                 case 12:
                     bAchievBombBot = true;
                     break;
                 case 13:
                     bAchievRocketStrike = true;
                     break;
             }
         }
References bAchievBombBot, bAchievProximityMine, bAchievRocketStrike, CURRENT_GENERIC_SPELL, EnterEvadeMode(), EVENT_FINISH, EVENT_LMK2_RETREAT_INTERVAL, EVENT_SAY_ACU_DEAD, EVENT_VX001_EMOTESTATE_DEATH, GetACU, Unit::GetCurrentSpell(), GetLMK2, Spell::GetSpellInfo(), GetVX001, hardmode, SpellInfo::Id, and SPELL_SELF_REPAIR.
SummonedCreatureDespawn()
void boss_mimiron::boss_mimironAI::SummonedCreatureDespawn (Creature * s) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 871 of file boss_mimiron.cpp.
         {
             summons.Despawn(s);
         }
References SummonList::Despawn(), and summons.
UpdateAI()
void boss_mimiron::boss_mimironAI::UpdateAI (uint32 diff) inline override virtual
Reimplemented from ScriptedAI.
Definition at line 414 of file boss_mimiron.cpp.
         {
             if (!me->IsInCombat())
             {
                 outofCombatTimer += diff;
                 if (outofCombatTimer >= 10000)
                 {
                     outofCombatTimer = 0;
                     if (Creature* c = GetLMK2())
                         me->CastSpell(c, RAND(SPELL_ENTER_VEHICLE_0, SPELL_ENTER_VEHICLE_1, SPELL_ENTER_VEHICLE_2, SPELL_ENTER_VEHICLE_4), true);
                 }
                 return;
             }
             Position p = me->GetHomePosition();
             if (me->GetExactDist(&p) > 80.0f || !SelectTargetFromPlayerList(150.0f))
             {
                 EnterEvadeMode();
                 return;
             }
             events.Update(diff);
             switch( events.ExecuteEvent() )
             {
                 case 0:
                     break;
                 case EVENT_COMPUTER_SAY_INITIATED:
                     if( Creature* computer = me->SummonCreature(NPC_COMPUTER, 2746.7f, 2569.44f, 410.39f, 0.0f, TEMPSUMMON_TIMED_DESPAWN, 1000) )
                         computer->AI()->Talk(TALK_COMPUTER_INITIATED);
                     break;
                 case EVENT_COMPUTER_SAY_MINUTES:
                     if( Creature* computer = me->SummonCreature(NPC_COMPUTER, 2746.7f, 2569.44f, 410.39f, 0.0f, TEMPSUMMON_TIMED_DESPAWN, 1000) )
                         computer->AI()->Talk(minutesTalkNum++);
                     break;
                 case EVENT_MIMIRON_SAY_HARDMODE:
                     me->Yell(TEXT_HARDMODE, LANG_UNIVERSAL);
                     me->PlayDirectSound(SOUND_TANK_HARD_INTRO);
                     events.ScheduleEvent(EVENT_SPAWN_FLAMES_INITIAL, 0);
                     events.ScheduleEvent(EVENT_SIT_LMK2, 4000);
                     break;
                 case EVENT_SPAWN_FLAMES_INITIAL:
                     {
                         if (changeAllowedFlameSpreadTime)
                             allowedFlameSpreadTime = time(nullptr);
                         std::vector<Player*> pg;
                         Map::PlayerList const& pl = me->GetMap()->GetPlayers();
                         for( Map::PlayerList::const_iterator itr = pl.begin(); itr != pl.end(); ++itr )
                             if( Player* plr = itr->GetSource() )
                                 if( plr->IsAlive() && plr->GetExactDist2d(me) < 150.0f && !plr->IsGameMaster() )
                                     pg.push_back(plr);
                         for( uint8 i = 0; i < 3; ++i )
                             if( !pg.empty() )
{
                                 uint8 index = urand(0, pg.size() - 1);
                                 Player* player = pg[index];
                                 float angle = rand_norm() * 2 * M_PI;
                                 float z = 364.35f;
                                 if (!player->IsWithinLOS(player->GetPositionX() + cos(angle) * 5.0f, player->GetPositionY() + sin(angle) * 5.0f, z))
{
                                     angle = player->GetAngle(2744.65f, 2569.46f);
                                 }
                                 me->CastSpell(player->GetPositionX() + cos(angle) * 5.0f, player->GetPositionY() + sin(angle) * 5.0f, z, SPELL_SUMMON_FLAMES_INITIAL, true);
                                 pg.erase(pg.begin() + index);
                             }
                         events.RepeatEvent(30000);
                     }
                     break;
                 case EVENT_BERSERK:
                     berserk = true;
                     me->Yell(TEXT_BERSERK, LANG_UNIVERSAL);
                     me->PlayDirectSound(SOUND_BERSERK);
                     if( hardmode )
                         me->SummonCreature(33576, 2744.78f, 2569.47f, 364.32f, 0.0f, TEMPSUMMON_TIMED_DESPAWN, 120000);
                     events.ScheduleEvent(EVENT_BERSERK_2, 0);
                     break;
                 case EVENT_BERSERK_2:
                     {
                         Creature* VX001 = nullptr;
                         Creature* LMK2 = nullptr;
                         Creature* ACU = nullptr;
                         if ((VX001 = GetVX001()))
                             VX001->CastSpell(VX001, SPELL_BERSERK, true);
                         if ((LMK2 = GetLMK2()))
                             LMK2->CastSpell(LMK2, SPELL_BERSERK, true);
                         if ((ACU = GetACU()))
                             ACU->CastSpell(ACU, SPELL_BERSERK, true);
                         events.RepeatEvent(30000);
                     }
                     break;
                 case EVENT_SIT_LMK2:
                     if(Creature* LMK2 = GetLMK2())
                     {
                         me->EnterVehicle(LMK2, 6);
                         events.ScheduleEvent(EVENT_SIT_LMK2_INTERVAL, 2000);
                         break;
                     }
                     EnterEvadeMode();
                     break;
                 case EVENT_SIT_LMK2_INTERVAL:
                     if (Creature* LMK2 = GetLMK2())
                     {
                         if (hardmode)
{
                             LMK2->CastSpell(LMK2, SPELL_EMERGENCY_MODE, true);
                             if( Vehicle* veh = LMK2->GetVehicleKit() )
                                 if( Unit* cannon = veh->GetPassenger(3) )
                                     cannon->CastSpell(cannon, SPELL_EMERGENCY_MODE, true);
                         }
                         LMK2->AI()->SetData(1, 1);
                         break;
                     }
                     EnterEvadeMode();
                     break;
                 case EVENT_LMK2_RETREAT_INTERVAL:
                     if (Creature* LMK2 = GetLMK2())
                     {
                         me->EnterVehicle(LMK2, 1);
                         me->Yell(TEXT_LMK2_DEATH, LANG_UNIVERSAL);
                         me->PlayDirectSound(SOUND_TANK_DEATH);
                         LMK2->SetFacingTo(3.58f);
                         events.ScheduleEvent(EVENT_ELEVATOR_INTERVAL_0, 6000);
                         break;
                     }
                     EnterEvadeMode();
                     break;
                 case EVENT_ELEVATOR_INTERVAL_0:
                     if( GameObject* elevator = me->FindNearestGameObject(GO_MIMIRON_ELEVATOR, 100.0f) )
                     {
                         elevator->SetLootState(GO_READY);
                         elevator->UseDoorOrButton(0, false);
                         elevator->EnableCollision(false);
                     }
                     events.ScheduleEvent(EVENT_ELEVATOR_INTERVAL_1, 6000);
                     break;
                 case EVENT_ELEVATOR_INTERVAL_1:
                     if(me->SummonCreature(NPC_VX001, 2744.65f, 2569.46f, 364.40f, 3.14f, TEMPSUMMON_MANUAL_DESPAWN))
                     {
                         if( GameObject* elevator = me->FindNearestGameObject(GO_MIMIRON_ELEVATOR, 100.0f) )
{
                             elevator->SetLootState(GO_READY);
                             elevator->UseDoorOrButton(0, true);
                             elevator->EnableCollision(false);
                         }
                         events.ScheduleEvent(EVENT_ELEVATOR_INTERVAL_2, 18000);
                         break;
                     }
                     EnterEvadeMode();
                     break;
                 case EVENT_ELEVATOR_INTERVAL_2:
                     if (Creature* VX001 = GetVX001())
                     {
                         me->EnterVehicle(VX001, 0);
                         events.ScheduleEvent(EVENT_SITTING_ON_VX001, 4000);
                         break;
                     }
                     EnterEvadeMode();
                     break;
                 case EVENT_SITTING_ON_VX001:
                     me->Yell(TEXT_VX001_ACTIVATE, LANG_UNIVERSAL);
                     me->PlayDirectSound(SOUND_TORSO_ACTIVE);
                     events.ScheduleEvent(EVENT_ENTER_VX001, 5000);
                     break;
                 case EVENT_ENTER_VX001:
                     if( Creature* VX001 = GetVX001() )
                     {
                         me->EnterVehicle(VX001, 1);
                         events.ScheduleEvent(EVENT_EMOTE_VX001, 2000);
                         break;
                     }
                     EnterEvadeMode();
                     break;
                 case EVENT_EMOTE_VX001:
                     if( Creature* VX001 = GetVX001() )
                     {
                         VX001->HandleEmoteCommand(EMOTE_ONESHOT_EMERGE);
                         events.ScheduleEvent(EVENT_VX001_START_FIGHT, 1750);
                         break;
                     }
                     EnterEvadeMode();
                     break;
                 case EVENT_VX001_START_FIGHT:
                     if( Creature* VX001 = GetVX001() )
                     {
                         if( hardmode )
                             VX001->CastSpell(VX001, SPELL_EMERGENCY_MODE, true);
                         VX001->AI()->SetData(1, 2);
                         me->SetInCombatWithZone();
                         break;
                     }
                     EnterEvadeMode();
                     break;
                 case EVENT_VX001_EMOTESTATE_DEATH:
                     if( Creature* VX001 = GetVX001() )
                     {
                         VX001->HandleEmoteCommand(EMOTE_STATE_DROWNED);
                         VX001->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_DROWNED);
                         events.ScheduleEvent(EVENT_GET_OUT_VX001, 2500);
                         break;
                     }
                     EnterEvadeMode();
                     break;
                 case EVENT_GET_OUT_VX001:
                     if( Creature* VX001 = GetVX001() )
                         if( Creature* ACU = me->SummonCreature(NPC_AERIAL_COMMAND_UNIT, 2743.91f, 2568.78f, 391.34f, M_PI, TEMPSUMMON_MANUAL_DESPAWN) )
{
                             me->EnterVehicle(VX001, 4);
                             float speed = ACU->GetDistance(2737.75f, 2574.22f, 381.34f) / 2.0f;
                             ACU->MonsterMoveWithSpeed(2737.75f, 2574.22f, 381.34f, speed);
                             ACU->SetPosition(2737.75f, 2574.22f, 381.34f, M_PI);
                             events.ScheduleEvent(EVENT_SAY_VX001_DEAD, 2000);
                             break;
                         }
                     EnterEvadeMode();
                     break;
                 case EVENT_SAY_VX001_DEAD:
                     changeAllowedFlameSpreadTime = true;
                     me->Yell(TEXT_VX001_DEATH, LANG_UNIVERSAL);
                     me->PlayDirectSound(SOUND_TORSO_DEATH);
                     events.ScheduleEvent(EVENT_ENTER_ACU, 7000);
                     break;
                 case EVENT_ENTER_ACU:
                     if( Creature* ACU = GetACU() )
                     {
                         me->EnterVehicle(ACU, 0);
                         events.ScheduleEvent(EVENT_SAY_ACU_ACTIVATE, 6000);
                         break;
                     }
                     EnterEvadeMode();
                     break;
                 case EVENT_SAY_ACU_ACTIVATE:
                     me->Yell(TEXT_ACU_ACTIVATE, LANG_UNIVERSAL);
                     me->PlayDirectSound(SOUND_HEAD_ACTIVE);
                     events.ScheduleEvent(EVENT_ACU_START_ATTACK, 4000);
                     break;
                 case EVENT_ACU_START_ATTACK:
                     if( Creature* ACU = GetACU() )
                     {
                         if( hardmode )
                             ACU->CastSpell(ACU, SPELL_EMERGENCY_MODE, true);
                         ACU->AI()->SetData(1, 3);
                         me->SetInCombatWithZone();
                         break;
                     }
                     EnterEvadeMode();
                     break;
                 case EVENT_SAY_ACU_DEAD:
                     me->Yell(TEXT_ACU_DEATH, LANG_UNIVERSAL);
                     me->PlayDirectSound(SOUND_HEAD_DEATH);
                     events.ScheduleEvent(EVENT_LEVIATHAN_COME_CLOSER, 5000);
                     break;
                 case EVENT_LEVIATHAN_COME_CLOSER:
                     if (Creature* LMK2 = GetLMK2())
                     {
                         LMK2->GetMotionMaster()->MoveCharge(2755.77f, 2574.95f, 364.31f, 21.0f);
                         events.ScheduleEvent(EVENT_VX001_EMOTE_JUMP, 4000);
                         break;
                     }
                     EnterEvadeMode();
                     break;
                 case EVENT_VX001_EMOTE_JUMP:
                     {
                         Creature* LMK2 = GetLMK2();
                         Creature* VX001 = GetVX001();
                         if( !VX001 || !LMK2 )
{
                             EnterEvadeMode();
                             return;
                         }
                         VX001->SendMeleeAttackStop();
                         VX001->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_ONESHOT_CUSTOM_SPELL_02);
                         VX001->HandleEmoteCommand(EMOTE_ONESHOT_CUSTOM_SPELL_02);
                         events.ScheduleEvent(EVENT_LEVIATHAN_RIDE_MIDDLE, 4800);
                     }
                     break;
                 case EVENT_LEVIATHAN_RIDE_MIDDLE:
                     {
                         Creature* VX001 = GetVX001();
                         Creature* LMK2 = GetLMK2();
                         if( !VX001 || !LMK2 )
{
                             EnterEvadeMode();
                             return;
                         }
                         LMK2->GetMotionMaster()->MoveCharge(2744.65f, 2569.46f, 364.31f, 21.0f);
                         VX001->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_CUSTOM_SPELL_01);
                         VX001->HandleEmoteCommand(EMOTE_STATE_CUSTOM_SPELL_01);
                         VX001->EnterVehicle(LMK2, 3);
                         events.ScheduleEvent(EVENT_JOIN_TOGETHER, 3000);
                     }
                     break;
                 case EVENT_JOIN_TOGETHER:
                     {
                         Creature* ACU = GetACU();
                         Creature* VX001 = GetVX001();
                         if( !VX001 || !ACU )
{
                             EnterEvadeMode();
                             return;
                         }
                         ACU->SetDisableGravity(false);
                         ACU->EnterVehicle(VX001, 3);
                         me->EnterVehicle(VX001, 1);
                         me->Yell(TEXT_VOLTRON_ACTIVATE, LANG_UNIVERSAL);
                         me->PlayDirectSound(SOUND_VOLTRON_ACTIVE);
                         events.ScheduleEvent(EVENT_START_PHASE4, 10000);
                     }
                     break;
                 case EVENT_START_PHASE4:
                     {
                         Creature* VX001 = GetVX001();
                         Creature* LMK2 = GetLMK2();
                         Creature* ACU = GetACU();
                         if( !VX001 || !LMK2 || !ACU )
{
                             EnterEvadeMode();
                             return;
                         }
                         LMK2->AI()->SetData(1, 4);
                         VX001->AI()->SetData(1, 4);
                         ACU->AI()->SetData(1, 4);
                         LMK2->CastSpell(LMK2, SPELL_SELF_REPAIR, true); //LMK2->SetHealth( LMK2->GetMaxHealth()/2 );
                         VX001->CastSpell(VX001, SPELL_SELF_REPAIR, true); //VX001->SetHealth( VX001->GetMaxHealth()/2 );
                         ACU->CastSpell(ACU, SPELL_SELF_REPAIR, true); //ACU->SetHealth( ACU->GetMaxHealth()/2 );
                         if( hardmode )
{
                             LMK2->CastSpell(LMK2, SPELL_EMERGENCY_MODE, true);
                             VX001->CastSpell(VX001, SPELL_EMERGENCY_MODE, true);
                             ACU->CastSpell(ACU, SPELL_EMERGENCY_MODE, true);
                         }
                         me->SetInCombatWithZone();
                     }
                     break;
                 case EVENT_FINISH:
                     {
                         Creature* LMK2 = GetLMK2();
                         Creature* VX001 = GetVX001();
                         Creature* ACU = GetACU();
                         if (!VX001 || !LMK2 || !ACU)
                             return;
                         LMK2->GetMotionMaster()->Clear();
                         LMK2->StopMoving();
                         LMK2->InterruptNonMeleeSpells(false);
                         LMK2->AttackStop();
                         LMK2->AI()->SetData(1, 0);
                         LMK2->DespawnOrUnsummon(7000);
                         LMK2->SetReactState(REACT_PASSIVE);
                         VX001->InterruptNonMeleeSpells(false);
                         VX001->AttackStop();
                         VX001->AI()->SetData(1, 0);
                         VX001->DespawnOrUnsummon(7000);
                         VX001->SetReactState(REACT_PASSIVE);
                         ACU->InterruptNonMeleeSpells(false);
                         ACU->AttackStop();
                         ACU->AI()->SetData(1, 0);
                         ACU->DespawnOrUnsummon(7000);
                         ACU->SetReactState(REACT_PASSIVE);
                         Position exitPos = me->GetPosition();
                         me->_ExitVehicle(&exitPos);
                         me->AttackStop();
                         me->SetUInt32Value(UNIT_NPC_EMOTESTATE, EMOTE_STATE_TALK);
                         me->GetMotionMaster()->Clear();
                         summons.DoAction(1337); // despawn summons of summons
                         summons.DespawnEntry(NPC_FLAMES_INITIAL);
                         summons.DespawnEntry(33576);
                         float angle = VX001->GetOrientation();
                         float v_x = me->GetPositionX() + cos(angle) * 10.0f;
                         float v_y = me->GetPositionY() + sin(angle) * 10.0f;
                         me->GetMotionMaster()->MoveJump(v_x, v_y, 364.32f, 7.0f, 7.0f);
                         if( pInstance )
                             for( uint16 i = 0; i < 3; ++i )
                                 if( ObjectGuid guid = pInstance->GetGuidData(DATA_GO_MIMIRON_DOOR_1 + i) )
                                     if( GameObject* door = ObjectAccessor::GetGameObject(*me, guid) )
                                         if( door->GetGoState() != GO_STATE_ACTIVE )
{
                                             door->SetLootState(GO_READY);
                                             door->UseDoorOrButton(0, false);
                                         }
                         if (pInstance)
                             pInstance->DoUpdateAchievementCriteria(ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, NPC_LEVIATHAN_MKII, 1, me);
                         if (hardmode)
                             if( Creature* computer = me->SummonCreature(NPC_COMPUTER, 2746.7f, 2569.44f, 410.39f, 0.0f, TEMPSUMMON_TIMED_DESPAWN, 1000) )
                                 computer->AI()->Talk(TALK_COMPUTER_TERMINATED);
                         events.Reset();
                         events.ScheduleEvent(EVENT_SAY_VOLTRON_DEAD, 6000);
                     }
                     break;
                 case EVENT_SAY_VOLTRON_DEAD:
                     me->Yell(TEXT_VOLTRON_DEATH, LANG_UNIVERSAL);
                     me->PlayDirectSound(SOUND_VOLTRON_DEATH);
                     // spawn chest
                     if( uint32 chestId = (hardmode ? RAID_MODE(GO_MIMIRON_CHEST_HARD, GO_MIMIRON_CHEST_HERO_HARD) : RAID_MODE(GO_MIMIRON_CHEST, GO_MIMIRON_CHEST_HERO)) )
                         if( GameObject* go = me->SummonGameObject(chestId, 2744.65f, 2569.46f, 364.397f, 0, 0, 0, 0, 0, 0) )
                             go->SetUInt32Value(GAMEOBJECT_FLAGS, 0);
                     events.ScheduleEvent(EVENT_DISAPPEAR, 15000);
                     break;
                 case EVENT_DISAPPEAR:
                     if( pInstance )
                         pInstance->SetData(TYPE_MIMIRON, DONE);
                     summons.DespawnAll();
                     me->DespawnOrUnsummon();
                     break;
             }
         }
References Unit::_ExitVehicle(), ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, Creature::AI(), allowedFlameSpreadTime, Unit::AttackStop(), MapRefMgr::begin(), berserk, mpq::c, Unit::CastSpell(), changeAllowedFlameSpreadTime, MotionMaster::Clear(), DATA_GO_MIMIRON_DOOR_1, SummonList::DespawnAll(), SummonList::DespawnEntry(), Creature::DespawnOrUnsummon(), diff(), SummonList::DoAction(), DONE, InstanceScript::DoUpdateAchievementCriteria(), EMOTE_ONESHOT_CUSTOM_SPELL_02, EMOTE_ONESHOT_EMERGE, EMOTE_STATE_CUSTOM_SPELL_01, EMOTE_STATE_DROWNED, EMOTE_STATE_TALK, MapRefMgr::end(), EnterEvadeMode(), Unit::EnterVehicle(), EVENT_ACU_START_ATTACK, EVENT_BERSERK, EVENT_BERSERK_2, EVENT_COMPUTER_SAY_INITIATED, EVENT_COMPUTER_SAY_MINUTES, EVENT_DISAPPEAR, EVENT_ELEVATOR_INTERVAL_0, EVENT_ELEVATOR_INTERVAL_1, EVENT_ELEVATOR_INTERVAL_2, EVENT_EMOTE_VX001, EVENT_ENTER_ACU, EVENT_ENTER_VX001, EVENT_FINISH, EVENT_GET_OUT_VX001, EVENT_JOIN_TOGETHER, EVENT_LEVIATHAN_COME_CLOSER, EVENT_LEVIATHAN_RIDE_MIDDLE, EVENT_LMK2_RETREAT_INTERVAL, EVENT_MIMIRON_SAY_HARDMODE, EVENT_SAY_ACU_ACTIVATE, EVENT_SAY_ACU_DEAD, EVENT_SAY_VOLTRON_DEAD, EVENT_SAY_VX001_DEAD, EVENT_SIT_LMK2, EVENT_SIT_LMK2_INTERVAL, EVENT_SITTING_ON_VX001, EVENT_SPAWN_FLAMES_INITIAL, EVENT_START_PHASE4, EVENT_VX001_EMOTE_JUMP, EVENT_VX001_EMOTESTATE_DEATH, EVENT_VX001_START_FIGHT, WorldObject::FindNearestGameObject(), GAMEOBJECT_FLAGS, GetACU, Position::GetAngle(), Position::GetExactDist(), ObjectAccessor::GetGameObject(), InstanceScript::GetGuidData(), Creature::GetHomePosition(), GetLMK2, WorldObject::GetMap(), Unit::GetMotionMaster(), Position::GetOrientation(), Map::GetPlayers(), Position::GetPosition(), Position::GetPositionX(), Position::GetPositionY(), GetVX001, GO_MIMIRON_CHEST, GO_MIMIRON_CHEST_HARD, GO_MIMIRON_CHEST_HERO, GO_MIMIRON_CHEST_HERO_HARD, GO_MIMIRON_ELEVATOR, GO_READY, GO_STATE_ACTIVE, Unit::HandleEmoteCommand(), hardmode, index, Unit::InterruptNonMeleeSpells(), Unit::IsInCombat(), WorldObject::IsWithinLOS(), LANG_UNIVERSAL, M_PI, ScriptedAI::me, minutesTalkNum, MotionMaster::MoveCharge(), MotionMaster::MoveJump(), NPC_AERIAL_COMMAND_UNIT, NPC_COMPUTER, NPC_FLAMES_INITIAL, NPC_LEVIATHAN_MKII, NPC_VX001, outofCombatTimer, pInstance, WorldObject::PlayDirectSound(), ScriptedAI::RAID_MODE(), RAND(), rand_norm(), REACT_PASSIVE, ScriptedAI::SelectTargetFromPlayerList(), Unit::SendMeleeAttackStop(), UnitAI::SetData(), ZoneScript::SetData(), Creature::SetDisableGravity(), Creature::SetInCombatWithZone(), Creature::SetReactState(), Object::SetUInt32Value(), SOUND_BERSERK, SOUND_HEAD_ACTIVE, SOUND_HEAD_DEATH, SOUND_TANK_DEATH, SOUND_TANK_HARD_INTRO, SOUND_TORSO_ACTIVE, SOUND_TORSO_DEATH, SOUND_VOLTRON_ACTIVE, SOUND_VOLTRON_DEATH, SPELL_BERSERK, SPELL_EMERGENCY_MODE, SPELL_ENTER_VEHICLE_0, SPELL_ENTER_VEHICLE_1, SPELL_ENTER_VEHICLE_2, SPELL_ENTER_VEHICLE_4, SPELL_SELF_REPAIR, SPELL_SUMMON_FLAMES_INITIAL, Unit::StopMoving(), WorldObject::SummonCreature(), WorldObject::SummonGameObject(), summons, TALK_COMPUTER_INITIATED, TALK_COMPUTER_TERMINATED, TEMPSUMMON_MANUAL_DESPAWN, TEMPSUMMON_TIMED_DESPAWN, TEXT_ACU_ACTIVATE, TEXT_ACU_DEATH, TEXT_BERSERK, TEXT_HARDMODE, TEXT_LMK2_DEATH, TEXT_VOLTRON_ACTIVATE, TEXT_VOLTRON_DEATH, TEXT_VX001_ACTIVATE, TEXT_VX001_DEATH, TYPE_MIMIRON, UNIT_NPC_EMOTESTATE, urand(), Unit::Yell(), and G3D::z.
Member Data Documentation
allowedFlameSpreadTime
uint32 boss_mimiron::boss_mimironAI::allowedFlameSpreadTime
Definition at line 319 of file boss_mimiron.cpp.
Referenced by GetData(), Reset(), and UpdateAI().
bAchievBombBot
bool boss_mimiron::boss_mimironAI::bAchievBombBot
Definition at line 317 of file boss_mimiron.cpp.
Referenced by GetData(), Reset(), and SetData().
bAchievProximityMine
bool boss_mimiron::boss_mimironAI::bAchievProximityMine
Definition at line 316 of file boss_mimiron.cpp.
Referenced by GetData(), Reset(), and SetData().
bAchievRocketStrike
bool boss_mimiron::boss_mimironAI::bAchievRocketStrike
Definition at line 318 of file boss_mimiron.cpp.
Referenced by GetData(), Reset(), and SetData().
berserk
bool boss_mimiron::boss_mimironAI::berserk
Definition at line 315 of file boss_mimiron.cpp.
Referenced by GetData(), Reset(), and UpdateAI().
bIsEvading
bool boss_mimiron::boss_mimironAI::bIsEvading
Definition at line 313 of file boss_mimiron.cpp.
Referenced by boss_mimironAI(), and EnterEvadeMode().
changeAllowedFlameSpreadTime
bool boss_mimiron::boss_mimironAI::changeAllowedFlameSpreadTime
Definition at line 320 of file boss_mimiron.cpp.
Referenced by Reset(), and UpdateAI().
events
EventMap boss_mimiron::boss_mimironAI::events
Definition at line 311 of file boss_mimiron.cpp.
hardmode
bool boss_mimiron::boss_mimironAI::hardmode
Definition at line 314 of file boss_mimiron.cpp.
Referenced by EnterCombat(), GetData(), Reset(), SetData(), and UpdateAI().
minutesTalkNum
uint8 boss_mimiron::boss_mimironAI::minutesTalkNum
Definition at line 321 of file boss_mimiron.cpp.
Referenced by EnterCombat(), and UpdateAI().
outofCombatTimer
uint32 boss_mimiron::boss_mimironAI::outofCombatTimer
Definition at line 322 of file boss_mimiron.cpp.
Referenced by Reset(), and UpdateAI().
pInstance
InstanceScript* boss_mimiron::boss_mimironAI::pInstance
Definition at line 310 of file boss_mimiron.cpp.
Referenced by boss_mimironAI(), CloseDoorAndButton(), EnterCombat(), Reset(), ResetGameObjects(), and UpdateAI().
summons
SummonList boss_mimiron::boss_mimironAI::summons
Definition at line 312 of file boss_mimiron.cpp.
Referenced by EnterEvadeMode(), JustSummoned(), Reset(), SummonedCreatureDespawn(), and UpdateAI().
The documentation for this struct was generated from the following file:
src/server/scripts/Northrend/Ulduar/Ulduar/boss_mimiron.cpp