Azerotcore-wotlk: UnitAura Class Reference
UnitAura Class Reference
#include <SpellAuras.h>
Public Member Functions
void _ApplyForTarget (Unit *target, Unit *caster, AuraApplication *aurApp) override
void _UnapplyForTarget (Unit *target, Unit *caster, AuraApplication *aurApp) override
void Remove (AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT) override
void FillTargetMap (std::map< Unit *, uint8 > &targets, Unit *caster) override
void SetDiminishGroup (DiminishingGroup group)
DiminishingGroup GetDiminishGroup () const
Public Member Functions inherited from Aura
Aura (SpellInfo const *spellproto, WorldObject *owner, Unit *caster, Item *castItem, ObjectGuid casterGUID, ObjectGuid itemGUID=ObjectGuid::Empty)
void _InitEffects (uint8 effMask, Unit *caster, int32 *baseAmount)
virtual ~Aura ()
SpellInfo const * GetSpellInfo () const
uint32 GetId () const
ObjectGuid GetCastItemGUID () const
uint32 GetCastItemEntry () const
ObjectGuid GetCasterGUID () const
Unit * GetCaster () const
WorldObject * GetOwner () const
Unit * GetUnitOwner () const
DynamicObject * GetDynobjOwner () const
AuraObjectType GetType () const
void _Remove (AuraRemoveMode removeMode)
void UpdateTargetMap (Unit *caster, bool apply=true)
void _RegisterForTargets ()
void ApplyForTargets ()
void _ApplyEffectForTargets (uint8 effIndex)
void UpdateOwner (uint32 diff, WorldObject *owner)
void Update (uint32 diff, Unit *caster)
time_t GetApplyTime () const
int32 GetMaxDuration () const
void SetMaxDuration (int32 duration)
int32 CalcMaxDuration () const
int32 CalcMaxDuration (Unit *caster) const
int32 GetDuration () const
void SetDuration (int32 duration, bool withMods=false)
void RefreshDuration (bool withMods=false)
void RefreshTimers (bool periodicReset=false)
bool IsExpired () const
bool IsPermanent () const
uint8 GetCharges () const
void SetCharges (uint8 charges)
uint8 CalcMaxCharges (Unit *caster) const
uint8 CalcMaxCharges () const
bool ModCharges (int32 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
bool DropCharge (AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT)
uint8 GetStackAmount () const
void SetStackAmount (uint8 num)
bool ModStackAmount (int32 num, AuraRemoveMode removeMode=AURA_REMOVE_BY_DEFAULT, bool periodicReset=false)
void RefreshSpellMods ()
uint8 GetCasterLevel () const
bool IsArea () const
bool IsPassive () const
bool IsDeathPersistent () const
bool IsRemovedOnShapeLost (Unit *target) const
bool CanBeSaved () const
bool IsRemoved () const
bool CanBeSentToClient () const
bool IsSingleTarget () const
bool IsSingleTargetWith (Aura const *aura) const
void SetIsSingleTarget (bool val)
void UnregisterSingleTarget ()
int32 CalcDispelChance (Unit *auraTarget, bool offensive) const
void SetLoadedState (int32 maxduration, int32 duration, int32 charges, uint8 stackamount, uint8 recalculateMask, int32 *amount)
bool HasEffect (uint8 effIndex) const
bool HasEffectType (AuraType type) const
AuraEffect * GetEffect (uint8 effIndex) const
uint8 GetEffectMask () const
void RecalculateAmountOfEffects ()
void HandleAllEffects (AuraApplication *aurApp, uint8 mode, bool apply)
ApplicationMap const & GetApplicationMap ()
void GetApplicationList (std::list< AuraApplication * > &applicationList) const
const AuraApplication * GetApplicationOfTarget (ObjectGuid guid) const
AuraApplication * GetApplicationOfTarget (ObjectGuid guid)
bool IsAppliedOnTarget (ObjectGuid guid) const
void SetNeedClientUpdateForTargets () const
void HandleAuraSpecificMods (AuraApplication const *aurApp, Unit *caster, bool apply, bool onReapply)
bool CanBeAppliedOn (Unit *target)
bool CheckAreaTarget (Unit *target)
bool CanStackWith (Aura const *checkAura, bool remove) const
bool IsAuraStronger (Aura const *newAura) const
bool IsProcOnCooldown () const
void AddProcCooldown (uint32 msec)
bool IsUsingCharges () const
void SetUsingCharges (bool val)
void PrepareProcToTrigger (AuraApplication *aurApp, ProcEventInfo &eventInfo)
bool IsProcTriggeredOnEvent (AuraApplication *aurApp, ProcEventInfo &eventInfo) const
float CalcProcChance (SpellProcEntry const &procEntry, ProcEventInfo &eventInfo) const
void TriggerProcOnEvent (AuraApplication *aurApp, ProcEventInfo &eventInfo)
void LoadScripts ()
bool CallScriptCheckAreaTargetHandlers (Unit *target)
void CallScriptDispel (DispelInfo *dispelInfo)
void CallScriptAfterDispel (DispelInfo *dispelInfo)
bool CallScriptEffectApplyHandlers (AuraEffect const *aurEff, AuraApplication const *aurApp, AuraEffectHandleModes mode)
bool CallScriptEffectRemoveHandlers (AuraEffect const *aurEff, AuraApplication const *aurApp, AuraEffectHandleModes mode)
void CallScriptAfterEffectApplyHandlers (AuraEffect const *aurEff, AuraApplication const *aurApp, AuraEffectHandleModes mode)
void CallScriptAfterEffectRemoveHandlers (AuraEffect const *aurEff, AuraApplication const *aurApp, AuraEffectHandleModes mode)
bool CallScriptEffectPeriodicHandlers (AuraEffect const *aurEff, AuraApplication const *aurApp)
void CallScriptEffectUpdatePeriodicHandlers (AuraEffect *aurEff)
void CallScriptEffectCalcAmountHandlers (AuraEffect const *aurEff, int32 &amount, bool &canBeRecalculated)
void CallScriptEffectCalcPeriodicHandlers (AuraEffect const *aurEff, bool &isPeriodic, int32 &amplitude)
void CallScriptEffectCalcSpellModHandlers (AuraEffect const *aurEff, SpellModifier *&spellMod)
void CallScriptEffectAbsorbHandlers (AuraEffect *aurEff, AuraApplication const *aurApp, DamageInfo &dmgInfo, uint32 &absorbAmount, bool &defaultPrevented)
void CallScriptEffectAfterAbsorbHandlers (AuraEffect *aurEff, AuraApplication const *aurApp, DamageInfo &dmgInfo, uint32 &absorbAmount)
void CallScriptEffectManaShieldHandlers (AuraEffect *aurEff, AuraApplication const *aurApp, DamageInfo &dmgInfo, uint32 &absorbAmount, bool &defaultPrevented)
void CallScriptEffectAfterManaShieldHandlers (AuraEffect *aurEff, AuraApplication const *aurApp, DamageInfo &dmgInfo, uint32 &absorbAmount)
void CallScriptEffectSplitHandlers (AuraEffect *aurEff, AuraApplication const *aurApp, DamageInfo &dmgInfo, uint32 &splitAmount)
bool CallScriptCheckProcHandlers (AuraApplication const *aurApp, ProcEventInfo &eventInfo)
bool CallScriptPrepareProcHandlers (AuraApplication const *aurApp, ProcEventInfo &eventInfo)
bool CallScriptProcHandlers (AuraApplication const *aurApp, ProcEventInfo &eventInfo)
void CallScriptAfterProcHandlers (AuraApplication const *aurApp, ProcEventInfo &eventInfo)
bool CallScriptEffectProcHandlers (AuraEffect const *aurEff, AuraApplication const *aurApp, ProcEventInfo &eventInfo)
void CallScriptAfterEffectProcHandlers (AuraEffect const *aurEff, AuraApplication const *aurApp, ProcEventInfo &eventInfo)
AuraScript * GetScriptByName (std::string const &scriptName) const
void SetTriggeredByAuraSpellInfo (SpellInfo const *triggeredByAuraSpellInfo)
SpellInfo const * GetTriggeredByAuraSpellInfo () const
Protected Member Functions
UnitAura (SpellInfo const *spellproto, uint8 effMask, WorldObject *owner, Unit *caster, int32 *baseAmount, Item *castItem, ObjectGuid casterGUID, ObjectGuid itemGUID=ObjectGuid::Empty)
Private Attributes
DiminishingGroup m_AuraDRGroup: 8
Friends
Aura * Aura::Create (SpellInfo const *spellproto, uint8 effMask, WorldObject *owner, Unit *caster, int32 *baseAmount, Item *castItem, ObjectGuid casterGUID, ObjectGuid itemGUID)
Additional Inherited Members
Public Types inherited from Aura
typedef std::map< ObjectGuid, AuraApplication * > ApplicationMap
Static Public Member Functions inherited from Aura
static uint8 BuildEffectMaskForOwner (SpellInfo const *spellProto, uint8 avalibleEffectMask, WorldObject *owner)
static Aura * TryRefreshStackOrCreate (SpellInfo const *spellproto, uint8 tryEffMask, WorldObject *owner, Unit *caster, int32 *baseAmount=nullptr, Item *castItem=nullptr, ObjectGuid casterGUID=ObjectGuid::Empty, bool *refresh=nullptr, bool periodicReset=false)
static Aura * TryCreate (SpellInfo const *spellproto, uint8 effMask, WorldObject *owner, Unit *caster, int32 *baseAmount=nullptr, Item *castItem=nullptr, ObjectGuid casterGUID=ObjectGuid::Empty, ObjectGuid itemGUID=ObjectGuid::Empty)
static Aura * Create (SpellInfo const *spellproto, uint8 effMask, WorldObject *owner, Unit *caster, int32 *baseAmount, Item *castItem, ObjectGuid casterGUID, ObjectGuid itemGUID=ObjectGuid::Empty)
Public Attributes inherited from Aura
std::list< AuraScript * > m_loadedScripts
Protected Attributes inherited from Aura
SpellInfo const *const m_spellInfo
ObjectGuid const m_casterGuid
ObjectGuid const m_castItemGuid
uint32 const m_castItemEntry
time_t const m_applyTime
WorldObject *const m_owner
int32 m_maxDuration
int32 m_duration
int32 m_timeCla
int32 m_updateTargetMapInterval
uint8 const m_casterLevel
uint8 m_procCharges
uint8 m_stackAmount
AuraEffect * m_effects [3]
ApplicationMap m_applications
bool m_isRemoved: 1
bool m_isSingleTarget: 1
bool m_isUsingCharges: 1
Detailed Description
Definition at line 274 of file SpellAuras.h.
Constructor & Destructor Documentation
UnitAura()
UnitAura::UnitAura (SpellInfo const * spellproto, uint8 effMask, WorldObject * owner, Unit * caster, int32 * baseAmount, Item * castItem, ObjectGuid casterGUID, ObjectGuid itemGUID = ObjectGuid::Empty) explicit protected
Definition at line 2658 of file SpellAuras.cpp.
     : Aura(spellproto, owner, caster, castItem, casterGUID, itemGUID)
 {
     m_AuraDRGroup = DIMINISHING_NONE;
     LoadScripts();
     _InitEffects(effMask, caster, baseAmount);
     GetUnitOwner()->_AddAura(this, caster);
 }
References Unit::_AddAura(), Aura::_InitEffects(), DIMINISHING_NONE, Aura::GetUnitOwner(), Aura::LoadScripts(), and m_AuraDRGroup.
Member Function Documentation
_ApplyForTarget()
void UnitAura::_ApplyForTarget (Unit * target, Unit * caster, AuraApplication * aurApp) override virtual
Reimplemented from Aura.
Definition at line 2667 of file SpellAuras.cpp.
 {
     Aura::_ApplyForTarget(target, caster, aurApp);
     // register aura diminishing on apply
     if (DiminishingGroup group = GetDiminishGroup())
         target->ApplyDiminishingAura(group, true);
 }
References Aura::_ApplyForTarget(), Unit::ApplyDiminishingAura(), and GetDiminishGroup().
_UnapplyForTarget()
void UnitAura::_UnapplyForTarget (Unit * target, Unit * caster, AuraApplication * aurApp) override virtual
Reimplemented from Aura.
Definition at line 2676 of file SpellAuras.cpp.
 {
     Aura::_UnapplyForTarget(target, caster, aurApp);
     // unregister aura diminishing (and store last time)
     if (DiminishingGroup group = GetDiminishGroup())
         target->ApplyDiminishingAura(group, false);
 }
References Aura::_UnapplyForTarget(), Unit::ApplyDiminishingAura(), and GetDiminishGroup().
FillTargetMap()
void UnitAura::FillTargetMap (std::map< Unit *, uint8 > & targets, Unit * caster) override virtual
Implements Aura.
Definition at line 2692 of file SpellAuras.cpp.
 {
     for (uint8 effIndex = 0; effIndex < MAX_SPELL_EFFECTS; ++effIndex)
     {
         if (!HasEffect(effIndex))
             continue;
         UnitList targetList;
         // non-area aura
         if (GetSpellInfo()->Effects[effIndex].Effect == SPELL_EFFECT_APPLY_AURA)
         {
             targetList.push_back(GetUnitOwner());
         }
         else
         {
             float radius = GetSpellInfo()->Effects[effIndex].CalcRadius(caster);
             if (!GetUnitOwner()->HasUnitState(UNIT_STATE_ISOLATED))
             {
                 switch (GetSpellInfo()->Effects[effIndex].Effect)
                 {
                     case SPELL_EFFECT_APPLY_AREA_AURA_PARTY:
                     case SPELL_EFFECT_APPLY_AREA_AURA_RAID:
{
                             targetList.push_back(GetUnitOwner());
                             Acore::AnyGroupedUnitInObjectRangeCheck u_check(GetUnitOwner(), GetUnitOwner(), radius, GetSpellInfo()->Effects[effIndex].Effect == SPELL_EFFECT_APPLY_AREA_AURA_RAID);
                             Acore::UnitListSearcher<Acore::AnyGroupedUnitInObjectRangeCheck> searcher(GetUnitOwner(), targetList, u_check);
                             Cell::VisitAllObjects(GetUnitOwner(), searcher, radius);
                             break;
                         }
                     case SPELL_EFFECT_APPLY_AREA_AURA_FRIEND:
{
                             targetList.push_back(GetUnitOwner());
                             Acore::AnyFriendlyUnitInObjectRangeCheck u_check(GetUnitOwner(), GetUnitOwner(), radius);
                             Acore::UnitListSearcher<Acore::AnyFriendlyUnitInObjectRangeCheck> searcher(GetUnitOwner(), targetList, u_check);
                             Cell::VisitAllObjects(GetUnitOwner(), searcher, radius);
                             break;
                         }
                     case SPELL_EFFECT_APPLY_AREA_AURA_ENEMY:
{
                             Acore::AnyAoETargetUnitInObjectRangeCheck u_check(GetUnitOwner(), GetUnitOwner(), radius); // No GetCharmer in searcher
                             Acore::UnitListSearcher<Acore::AnyAoETargetUnitInObjectRangeCheck> searcher(GetUnitOwner(), targetList, u_check);
                             Cell::VisitAllObjects(GetUnitOwner(), searcher, radius);
                             break;
                         }
                     case SPELL_EFFECT_APPLY_AREA_AURA_PET:
                         targetList.push_back(GetUnitOwner());
                         [[fallthrough]]; // TODO: Not sure whether the fallthrough was a mistake (forgetting a break) or intended. This should be double-checked.
                     case SPELL_EFFECT_APPLY_AREA_AURA_OWNER:
{
                             if (Unit* owner = GetUnitOwner()->GetCharmerOrOwner())
                                 if (GetUnitOwner()->IsWithinDistInMap(owner, radius))
                                     targetList.push_back(owner);
                             break;
                         }
                 }
             }
         }
         for (UnitList::iterator itr = targetList.begin(); itr != targetList.end(); ++itr)
         {
             std::map<Unit*, uint8>::iterator existing = targets.find(*itr);
             if (existing != targets.end())
                 existing->second |= 1 << effIndex;
             else
                 targets[*itr] = 1 << effIndex;
         }
     }
 }
References SpellInfo::Effects, Aura::GetSpellInfo(), Aura::GetUnitOwner(), Aura::HasEffect(), MAX_SPELL_EFFECTS, SPELL_EFFECT_APPLY_AREA_AURA_ENEMY, SPELL_EFFECT_APPLY_AREA_AURA_FRIEND, SPELL_EFFECT_APPLY_AREA_AURA_OWNER, SPELL_EFFECT_APPLY_AREA_AURA_PARTY, SPELL_EFFECT_APPLY_AREA_AURA_PET, SPELL_EFFECT_APPLY_AREA_AURA_RAID, SPELL_EFFECT_APPLY_AURA, UNIT_STATE_ISOLATED, and Cell::VisitAllObjects().
GetDiminishGroup()
DiminishingGroup UnitAura::GetDiminishGroup () const inline
Definition at line 291 of file SpellAuras.h.
 { return m_AuraDRGroup; }
References m_AuraDRGroup.
Referenced by _ApplyForTarget(), and _UnapplyForTarget().
Remove()
void UnitAura::Remove (AuraRemoveMode removeMode = AURA_REMOVE_BY_DEFAULT) override virtual
Implements Aura.
Definition at line 2685 of file SpellAuras.cpp.
 {
     if (IsRemoved())
         return;
     GetUnitOwner()->RemoveOwnedAura(this, removeMode);
 }
References Aura::GetUnitOwner(), Aura::IsRemoved(), and Unit::RemoveOwnedAura().
SetDiminishGroup()
void UnitAura::SetDiminishGroup (DiminishingGroup group) inline
Definition at line 290 of file SpellAuras.h.
 { m_AuraDRGroup = group; }
References m_AuraDRGroup.
Friends And Related Function Documentation
Aura::Create
Aura* Aura::Create (SpellInfo const * spellproto, uint8 effMask, WorldObject * owner, Unit * caster, int32 * baseAmount, Item * castItem, ObjectGuid casterGUID, ObjectGuid itemGUID) friend
Member Data Documentation
m_AuraDRGroup
DiminishingGroup UnitAura::m_AuraDRGroup private
Definition at line 294 of file SpellAuras.h.
Referenced by GetDiminishGroup(), SetDiminishGroup(), and UnitAura().
The documentation for this class was generated from the following files:
src/server/game/Spells/Auras/SpellAuras.h
src/server/game/Spells/Auras/SpellAuras.cpp