Azerotcore-wotlk: src/server/scripts/Pet/pets_script_loader.cpp File Reference
pets_script_loader.cpp File Reference
Functions
void AddSC_deathknight_pet_scripts ()
void AddSC_generic_pet_scripts ()
void AddSC_hunter_pet_scripts ()
void AddSC_mage_pet_scripts ()
void AddSC_priest_pet_scripts ()
void AddSC_shaman_pet_scripts ()
void AddPetScripts ()
Function Documentation
AddPetScripts()
void AddPetScripts ()
Definition at line 29 of file pets_script_loader.cpp.
 {
     AddSC_deathknight_pet_scripts();
     AddSC_generic_pet_scripts();
     AddSC_hunter_pet_scripts();
     AddSC_mage_pet_scripts();
     AddSC_priest_pet_scripts();
     AddSC_shaman_pet_scripts();
 }
References AddSC_deathknight_pet_scripts(), AddSC_generic_pet_scripts(), AddSC_hunter_pet_scripts(), AddSC_mage_pet_scripts(), AddSC_priest_pet_scripts(), and AddSC_shaman_pet_scripts().
AddSC_deathknight_pet_scripts()
void AddSC_deathknight_pet_scripts ()
Definition at line 303 of file pet_dk.cpp.
 {
     new npc_pet_dk_ebon_gargoyle();
     new npc_pet_dk_ghoul();
     new npc_pet_dk_army_of_the_dead();
     new npc_pet_dk_dancing_rune_weapon();
 }
Referenced by AddPetScripts().
AddSC_generic_pet_scripts()
void AddSC_generic_pet_scripts ()
Definition at line 829 of file pet_generic.cpp.
 {
     RegisterCreatureAI(npc_pet_gen_mojo);
     RegisterCreatureAI(npc_pet_gen_soul_trader_beacon);
     RegisterCreatureAI(npc_pet_gen_argent_pony_bridle);
     RegisterCreatureAI(npc_pet_gen_target_following_bomb);
     RegisterCreatureAI(npc_pet_gen_gnomish_flame_turret);
     RegisterCreatureAI(npc_pet_gen_valkyr_guardian);
     RegisterSpellScript(spell_pet_gen_valkyr_guardian_smite);
     RegisterCreatureAI(npc_pet_gen_imp_in_a_bottle);
     RegisterCreatureAI(npc_pet_gen_wind_rider_cub);
     RegisterCreatureAI(npc_pet_gen_plump_turkey);
     RegisterCreatureAI(npc_pet_gen_toxic_wasteling);
     RegisterCreatureAI(npc_pet_gen_fetch_ball);
     RegisterCreatureAI(npc_pet_gen_moth);
 }
References RegisterCreatureAI, and RegisterSpellScript.
Referenced by AddPetScripts().
AddSC_hunter_pet_scripts()
void AddSC_hunter_pet_scripts ()
Definition at line 141 of file pet_hunter.cpp.
 {
     RegisterCreatureAI(npc_pet_hunter_snake_trap);
 }
References RegisterCreatureAI.
Referenced by AddPetScripts().
AddSC_mage_pet_scripts()
void AddSC_mage_pet_scripts ()
Definition at line 220 of file pet_mage.cpp.
 {
     RegisterCreatureAI(npc_pet_mage_mirror_image);
 }
References RegisterCreatureAI.
Referenced by AddPetScripts().
AddSC_priest_pet_scripts()
void AddSC_priest_pet_scripts ()
Definition at line 79 of file pet_priest.cpp.
 {
     RegisterCreatureAI(npc_pet_pri_lightwell);
     RegisterCreatureAI(npc_pet_pri_shadowfiend);
 }
References RegisterCreatureAI.
Referenced by AddPetScripts().
AddSC_shaman_pet_scripts()
void AddSC_shaman_pet_scripts ()
Definition at line 146 of file pet_shaman.cpp.
 {
     RegisterCreatureAI(npc_pet_shaman_earth_elemental);
     RegisterCreatureAI(npc_pet_shaman_fire_elemental);
 }
References RegisterCreatureAI.
Referenced by AddPetScripts().