Azerotcore-wotlk: AuthCrypt Class Reference
AuthCrypt Class Reference
#include <AuthCrypt.h>
Public Member Functions
AuthCrypt ()
void Init (SessionKey const &K)
void DecryptRecv (uint8 *data, size_t len)
void EncryptSend (uint8 *data, size_t len)
bool IsInitialized () const
Private Attributes
Acore::Crypto::ARC4 _clientDecrypt
Acore::Crypto::ARC4 _serverEncrypt
bool _initialized
Detailed Description
Definition at line 25 of file AuthCrypt.h.
Constructor & Destructor Documentation
AuthCrypt()
AuthCrypt::AuthCrypt ()
Definition at line 23 of file AuthCrypt.cpp.
                      : _initialized(false)
 {
 }
Member Function Documentation
DecryptRecv()
void AuthCrypt::DecryptRecv (uint8 * data, size_t len)
Definition at line 42 of file AuthCrypt.cpp.
 {
     ASSERT(_initialized);
     _clientDecrypt.UpdateData(data, len);
 }
References _clientDecrypt, _initialized, ASSERT, and Acore::Crypto::ARC4::UpdateData().
Referenced by WorldSocket::ReadHeaderHandler().
EncryptSend()
void AuthCrypt::EncryptSend (uint8 * data, size_t len)
Definition at line 48 of file AuthCrypt.cpp.
 {
     ASSERT(_initialized);
     _serverEncrypt.UpdateData(data, len);
 }
References _initialized, _serverEncrypt, ASSERT, and Acore::Crypto::ARC4::UpdateData().
Referenced by WorldSocket::Update().
Init()
void AuthCrypt::Init (SessionKey const & K)
Definition at line 27 of file AuthCrypt.cpp.
 {
     uint8 ServerEncryptionKey[] = { 0xCC, 0x98, 0xAE, 0x04, 0xE8, 0x97, 0xEA, 0xCA, 0x12, 0xDD, 0xC0, 0x93, 0x42, 0x91, 0x53, 0x57 };
     _serverEncrypt.Init(Acore::Crypto::HMAC_SHA1::GetDigestOf(ServerEncryptionKey, K));
     uint8 ServerDecryptionKey[] = { 0xC2, 0xB3, 0x72, 0x3C, 0xC6, 0xAE, 0xD9, 0xB5, 0x34, 0x3C, 0x53, 0xEE, 0x2F, 0x43, 0x67, 0xCE };
     _clientDecrypt.Init(Acore::Crypto::HMAC_SHA1::GetDigestOf(ServerDecryptionKey, K));
     // Drop first 1024 bytes, as WoW uses ARC4-drop1024.
     std::array<uint8, 1024> syncBuf;
     _serverEncrypt.UpdateData(syncBuf);
     _clientDecrypt.UpdateData(syncBuf);
     _initialized = true;
 }
References _clientDecrypt, _initialized, _serverEncrypt, Acore::Impl::GenericHMAC< HashCreator, DigestLength >::GetDigestOf(), Acore::Crypto::ARC4::Init(), and Acore::Crypto::ARC4::UpdateData().
Referenced by WorldSocket::HandleAuthSessionCallback().
IsInitialized()
bool AuthCrypt::IsInitialized () const inline
Definition at line 34 of file AuthCrypt.h.
 { return _initialized; }
References _initialized.
Referenced by WorldSocket::ReadHeaderHandler(), and WorldSocket::SendPacket().
Member Data Documentation
_clientDecrypt
Acore::Crypto::ARC4 AuthCrypt::_clientDecrypt private
Definition at line 37 of file AuthCrypt.h.
Referenced by DecryptRecv(), and Init().
_initialized
bool AuthCrypt::_initialized private
Definition at line 39 of file AuthCrypt.h.
Referenced by DecryptRecv(), EncryptSend(), Init(), and IsInitialized().
_serverEncrypt
Acore::Crypto::ARC4 AuthCrypt::_serverEncrypt private
Definition at line 38 of file AuthCrypt.h.
Referenced by EncryptSend(), and Init().
The documentation for this class was generated from the following files:
src/common/Cryptography/Authentication/AuthCrypt.h
src/common/Cryptography/Authentication/AuthCrypt.cpp