Azerotcore-wotlk: MysticBuffetTargetFilter Class Reference
MysticBuffetTargetFilter Class Reference
Public Member Functions
MysticBuffetTargetFilter (Unit *caster)
bool operator() (WorldObject *unit) const
Private Attributes
Unit * _caster
Detailed Description
Definition at line 1268 of file boss_sindragosa.cpp.
Constructor & Destructor Documentation
MysticBuffetTargetFilter()
MysticBuffetTargetFilter::MysticBuffetTargetFilter (Unit * caster) inline explicit
Definition at line 1271 of file boss_sindragosa.cpp.
 : _caster(caster) { }
Member Function Documentation
operator()()
bool MysticBuffetTargetFilter::operator() (WorldObject * unit) const inline
Definition at line 1273 of file boss_sindragosa.cpp.
     {
         if (!unit->IsInMap(_caster))
             return true;
         // for standard creatures check full LOS
         if (Creature* c = unit->ToCreature())
             if (!c->IsPet() && c->GetSpawnId())
                 return !_caster->IsWithinLOSInMap(unit);
         // for players and pets check only dynamic los (ice block gameobjects)
         float ox, oy, oz;
         _caster->GetPosition(ox, oy, oz);
         DynamicMapTree const& dTree = unit->GetMap()->GetDynamicMapTree();
         return !dTree.isInLineOfSight(unit->GetPositionX(), unit->GetPositionY(), unit->GetPositionZ() + 2.f, ox, oy, oz + 2.f, unit->GetPhaseMask());
     }
References _caster, mpq::c, Map::GetDynamicMapTree(), WorldObject::GetMap(), WorldObject::GetPhaseMask(), Position::GetPosition(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), DynamicMapTree::isInLineOfSight(), WorldObject::IsInMap(), WorldObject::IsWithinLOSInMap(), and Object::ToCreature().
Member Data Documentation
_caster
Unit* MysticBuffetTargetFilter::_caster private
Definition at line 1291 of file boss_sindragosa.cpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
src/server/scripts/Northrend/IcecrownCitadel/boss_sindragosa.cpp