Azerotcore-wotlk: anonymous_namespace{Errors.cpp} Namespace Reference
anonymous_namespace{Errors.cpp} Namespace Reference
Functions
std::string FormatAssertionMessage (char const *format, va_list args)
Function Documentation
FormatAssertionMessage()
std::string anonymous_namespace{Errors.cpp}::FormatAssertionMessage (char const * format, va_list args)
Definition at line 41 of file Errors.cpp.
     {
         std::string formatted;
         va_list len;
         va_copy(len, args);
         int32 length = vsnprintf(nullptr, 0, format, len);
         va_end(len);
         formatted.resize(length);
         vsnprintf(&formatted[0], length + 1, format, args);
         return formatted;
     }
Referenced by Acore::Abort(), Acore::Assert(), and Acore::Fatal().