Azerotcore-wotlk: Acore::MessageDistDeliverer Struct Reference
Acore::MessageDistDeliverer Struct Reference
#include <GridNotifiers.h>
Public Member Functions
MessageDistDeliverer (WorldObject *src, WorldPacket *msg, float dist, bool own_team_only=false, Player const *skipped=nullptr)
void Visit (PlayerMapType &m)
void Visit (CreatureMapType &m)
void Visit (DynamicObjectMapType &m)
template<class SKIP >
void Visit (GridRefMgr< SKIP > &)
void SendPacket (Player *player)
Public Attributes
WorldObject * i_source
WorldPacket * i_message
uint32 i_phaseMask
float i_distSq
TeamId teamId
Player const * skipped_receiver
Detailed Description
Definition at line 97 of file GridNotifiers.h.
Constructor & Destructor Documentation
MessageDistDeliverer()
Acore::MessageDistDeliverer::MessageDistDeliverer (WorldObject * src, WorldPacket * msg, float dist, bool own_team_only = false, Player const * skipped = nullptr) inline
Definition at line 105 of file GridNotifiers.h.
             : i_source(src), i_message(msg), i_phaseMask(src->GetPhaseMask()), i_distSq(dist * dist)
             , teamId((own_team_only && src->GetTypeId() == TYPEID_PLAYER) ? src->ToPlayer()->GetTeamId() : TEAM_NEUTRAL)
             , skipped_receiver(skipped)
         {
         }
Member Function Documentation
SendPacket()
void Acore::MessageDistDeliverer::SendPacket (Player * player) inline
Definition at line 116 of file GridNotifiers.h.
         {
             // never send packet to self
             if (player == i_source || (teamId != TEAM_NEUTRAL && player->GetTeamId() != teamId) || skipped_receiver == player)
                 return;
             if (!player->HaveAtClient(i_source))
                 return;
             player->GetSession()->SendPacket(i_message);
         }
References Player::GetSession(), Player::GetTeamId(), Player::HaveAtClient(), i_message, i_source, WorldSession::SendPacket(), skipped_receiver, TEAM_NEUTRAL, and teamId.
Referenced by Visit().
Visit() [1/4]
void MessageDistDeliverer::Visit (CreatureMapType & m)
Definition at line 238 of file GridNotifiers.cpp.
 {
     for (CreatureMapType::iterator iter = m.begin(); iter != m.end(); ++iter)
     {
         Creature* target = iter->GetSource();
         if (!target->HasSharedVision() || !target->InSamePhase(i_phaseMask))
             continue;
         if (target->GetExactDist2dSq(i_source) > i_distSq)
             continue;
         // Send packet to all who are sharing the creature's vision
         SharedVisionList::const_iterator i = target->GetSharedVisionList().begin();
         for (; i != target->GetSharedVisionList().end(); ++i)
             if ((*i)->m_seer == target)
                 SendPacket(*i);
     }
 }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), Position::GetExactDist2dSq(), Unit::GetSharedVisionList(), Unit::HasSharedVision(), i_distSq, i_phaseMask, i_source, WorldObject::InSamePhase(), and SendPacket().
Visit() [2/4]
void MessageDistDeliverer::Visit (DynamicObjectMapType & m)
Definition at line 257 of file GridNotifiers.cpp.
 {
     for (DynamicObjectMapType::iterator iter = m.begin(); iter != m.end(); ++iter)
     {
         DynamicObject* target = iter->GetSource();
         if (!target->GetCasterGUID().IsPlayer() || !target->InSamePhase(i_phaseMask))
             continue;
         // Xinef: Check whether the dynobject allows to see through it
         if (!target->IsViewpoint())
             continue;
         if (target->GetExactDist2dSq(i_source) > i_distSq)
             continue;
         // Send packet back to the caster if the caster has vision of dynamic object
         Player* caster = (Player*)target->GetCaster();
         if (caster && caster->m_seer == target)
             SendPacket(caster);
     }
 }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), DynamicObject::GetCaster(), DynamicObject::GetCasterGUID(), Position::GetExactDist2dSq(), i_distSq, i_phaseMask, i_source, WorldObject::InSamePhase(), ObjectGuid::IsPlayer(), DynamicObject::IsViewpoint(), Player::m_seer, and SendPacket().
Visit() [3/4]
template<class SKIP > void Acore::MessageDistDeliverer::Visit (GridRefMgr< SKIP > &) inline
Definition at line 114 of file GridNotifiers.h.
 {}
Visit() [4/4]
void MessageDistDeliverer::Visit (PlayerMapType & m)
Definition at line 213 of file GridNotifiers.cpp.
 {
     for (PlayerMapType::iterator iter = m.begin(); iter != m.end(); ++iter)
     {
         Player* target = iter->GetSource();
         if (!target->InSamePhase(i_phaseMask))
             continue;
         if (target->GetExactDist2dSq(i_source) > i_distSq)
             continue;
         // Send packet to all who are sharing the player's vision
         if (target->HasSharedVision())
         {
             SharedVisionList::const_iterator i = target->GetSharedVisionList().begin();
             for (; i != target->GetSharedVisionList().end(); ++i)
                 if ((*i)->m_seer == target)
                     SendPacket(*i);
         }
         if (target->m_seer == target || target->GetVehicle())
             SendPacket(target);
     }
 }
References GridRefMgr< OBJECT >::begin(), GridRefMgr< OBJECT >::end(), Position::GetExactDist2dSq(), Unit::GetSharedVisionList(), Unit::GetVehicle(), Unit::HasSharedVision(), i_distSq, i_phaseMask, i_source, WorldObject::InSamePhase(), Player::m_seer, and SendPacket().
Member Data Documentation
i_distSq
float Acore::MessageDistDeliverer::i_distSq
Definition at line 102 of file GridNotifiers.h.
Referenced by Visit().
i_message
WorldPacket* Acore::MessageDistDeliverer::i_message
Definition at line 100 of file GridNotifiers.h.
Referenced by SendPacket().
i_phaseMask
uint32 Acore::MessageDistDeliverer::i_phaseMask
Definition at line 101 of file GridNotifiers.h.
Referenced by Visit().
i_source
WorldObject* Acore::MessageDistDeliverer::i_source
Definition at line 99 of file GridNotifiers.h.
Referenced by SendPacket(), and Visit().
skipped_receiver
Player const* Acore::MessageDistDeliverer::skipped_receiver
Definition at line 104 of file GridNotifiers.h.
Referenced by SendPacket().
teamId
TeamId Acore::MessageDistDeliverer::teamId
Definition at line 103 of file GridNotifiers.h.
Referenced by SendPacket().
The documentation for this struct was generated from the following files:
src/server/game/Grids/Notifiers/GridNotifiers.h
src/server/game/Grids/Notifiers/GridNotifiers.cpp