Azerotcore-wotlk: G3D::MeshBuilder Class Reference
G3D::MeshBuilder Class Reference
#include <MeshBuilder.h>
Public Types
enum { AUTO_WELD = -100 }
Public Member Functions
MeshBuilder (bool twoSided=false, bool scaleAndCenter=true)
void commit (std::string &name, Array< int > &indexArray, Array< Vector3 > &vertexArray)
void addTriangle (const Vector3 &a, const Vector3 &b, const Vector3 &c)
void addQuad (const Vector3 &a, const Vector3 &b, const Vector3 &c, const Vector3 &d)
void addTriangle (const Triangle &t)
void setName (const std::string &n)
void setWeldRadius (double r)
Private Types
typedef Array< int > List
Private Member Functions
void centerTriList ()
void computeBounds (Vector3 &min, Vector3 &max)
Private Attributes
std::string name
bool scaleAndCenter
Array< Vector3 > triList
bool _twoSided
double close
Detailed Description
Allows creation of optimized watertight meshes from unoptimized polygon soups. See also G3D::MeshAlg for algorithms that operate on the output.
Definition at line 23 of file MeshBuilder.h.
Member Typedef Documentation
List
typedef Array<int> G3D::MeshBuilder::List private
Indices of vertices in or near a grid cell.
Definition at line 34 of file MeshBuilder.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Set setWeldRadius to AUTO_WELD to weld vertices closer than 1/2 the smallest edge length in a model.
Enumerator
AUTO_WELD
Definition at line 30 of file MeshBuilder.h.
 {AUTO_WELD = -100};
Constructor & Destructor Documentation
MeshBuilder()
G3D::MeshBuilder::MeshBuilder (bool twoSided = false, bool scaleAndCenter = true) inline
Definition at line 55 of file MeshBuilder.h.
 : scaleAndCenter(scaleAndCenter), _twoSided(twoSided), close(AUTO_WELD) {}
Member Function Documentation
addQuad()
void G3D::MeshBuilder::addQuad (const Vector3 & a, const Vector3 & b, const Vector3 & c, const Vector3 & d)
Adds two new triangles to the model. (Counter clockwise)
Definition at line 105 of file MeshBuilder.cpp.
{
     addTriangle(a, b, c);
     addTriangle(a, c, d);
 }
References mpq::a, addTriangle(), b, mpq::c, and mpq::d.
addTriangle() [1/2]
void G3D::MeshBuilder::addTriangle (const Triangle & t)
Definition at line 111 of file MeshBuilder.cpp.
{
     addTriangle(t.vertex(0), t.vertex(1), t.vertex(2));
 }
References addTriangle(), and G3D::Triangle::vertex().
addTriangle() [2/2]
void G3D::MeshBuilder::addTriangle (const Vector3 & a, const Vector3 & b, const Vector3 & c)
Adds a new triangle to the model. (Counter clockwise)
Definition at line 96 of file MeshBuilder.cpp.
{
     triList.append(a, b, c);
     if (_twoSided) {
         triList.append(c, b, a);
     }
 }
References _twoSided, mpq::a, b, mpq::c, and triList.
Referenced by addQuad(), and addTriangle().
centerTriList()
void G3D::MeshBuilder::centerTriList () private
Definition at line 59 of file MeshBuilder.cpp.
{
     // Compute the range of the vertices
     Vector3 vmin, vmax;
     computeBounds(vmin, vmax);
     const Vector3 diagonal = vmax - vmin;
     float scale = max(max(diagonal.x, diagonal.y), diagonal.z) / 2.0f;
     debugAssert(scale > 0);
     const Vector3 translation = vmin + diagonal / 2.0f;
     // Center and scale all vertices in the input list
     int v;
     if (scaleAndCenter) {
         //Matrix3 rot90 = Matrix3::fromAxisAngle(Vector3::UNIT_Y, toRadians(180)) * Matrix3::fromAxisAngle(Vector3::UNIT_X, toRadians(90));
         for (v = 0; v < triList.size(); ++v) {
             triList[v] = (triList[v] - translation) / scale;
             //triList[v] = rot90 * triList[v];
         }
     }
 }
References computeBounds(), debugAssert, diagonal(), G3D::max(), scaleAndCenter, and triList.
Referenced by commit().
commit()
void G3D::MeshBuilder::commit (std::string & name, Array< int > & indexArray, Array< Vector3 > & vertexArray)
Writes the model to the arrays, which can then be used with G3D::IFSModel::save and G3D::MeshAlg
Definition at line 20 of file MeshBuilder.cpp.
{
     n = name;
     // Make the data fit in a unit cube
     centerTriList();
     Array<int> toNew, toOld;
     if (close == MeshBuilder::AUTO_WELD) {
         Array<int> index;
         MeshAlg::createIndexArray(triList.size(), index);
         double minEdgeLen, maxEdgeLen, meanEdgeLen, medianEdgeLen;
         double minFaceArea, maxFaceArea, meanFaceArea, medianFaceArea;
         MeshAlg::computeAreaStatistics(triList, index,
             minEdgeLen, meanEdgeLen, medianEdgeLen, maxEdgeLen,
             minFaceArea, meanFaceArea, medianFaceArea, maxFaceArea);
         close = minEdgeLen * 0.1;
     }
     MeshAlg::computeWeld(triList, outvertexArray, toNew, toOld, (float)close);
     // Construct triangles
     for (int t = 0; t < triList.size(); t += 3) {
         int index[3];
         for (int i = 0; i < 3; ++i) {
            index[i] = toNew[t + i];
         }
         // Throw out zero size triangles
         if ((index[0] != index[1]) &&
             (index[1] != index[2]) &&
             (index[2] != index[0])) {
             indexArray.append(index[0], index[1], index[2]);
         }
     }
 }
References G3D::Array< T, MIN_ELEMENTS >::append(), AUTO_WELD, centerTriList(), close, G3D::MeshAlg::computeAreaStatistics(), G3D::MeshAlg::computeWeld(), G3D::MeshAlg::createIndexArray(), index, name, and triList.
computeBounds()
void G3D::MeshBuilder::computeBounds (Vector3 & min, Vector3 & max) private
Definition at line 84 of file MeshBuilder.cpp.
{
     min = Vector3::inf();
     max = -min;
     int v;
     for (v = 0; v < triList.size(); ++v) {
         min = min.min(triList[v]);
         max = max.max(triList[v]);
     }
 }
References G3D::Vector3::inf(), G3D::max(), G3D::min(), and triList.
Referenced by centerTriList().
setName()
void G3D::MeshBuilder::setName (const std::string & n)
Definition at line 15 of file MeshBuilder.cpp.
{
     name = n;
 }
References name.
setWeldRadius()
void G3D::MeshBuilder::setWeldRadius (double r) inline
Vertices within this distance are considered identical.
Use AUTO_WELD (the default) to have the distance be a function of the model size.
Definition at line 77 of file MeshBuilder.h.
{
         close = r;
     }
References close.
Member Data Documentation
_twoSided
bool G3D::MeshBuilder::_twoSided private
Definition at line 48 of file MeshBuilder.h.
Referenced by addTriangle().
close
double G3D::MeshBuilder::close private
Collapse radius
Definition at line 51 of file MeshBuilder.h.
Referenced by commit(), and setWeldRadius().
name
std::string G3D::MeshBuilder::name private
Definition at line 36 of file MeshBuilder.h.
Referenced by commit(), and setName().
scaleAndCenter
bool G3D::MeshBuilder::scaleAndCenter private
Definition at line 38 of file MeshBuilder.h.
Referenced by centerTriList().
triList
Array<Vector3> G3D::MeshBuilder::triList private
All of the triangles, as a long triangle list.
Definition at line 43 of file MeshBuilder.h.
Referenced by addTriangle(), centerTriList(), commit(), and computeBounds().
The documentation for this class was generated from the following files:
deps/g3dlite/include/G3D/MeshBuilder.h
deps/g3dlite/source/MeshBuilder.cpp