Azerotcore-wotlk: spell_illidari_council_empyreal_balance::spell_illidari_council_empyreal_balance_SpellScript Class Reference
spell_illidari_council_empyreal_balance::spell_illidari_council_empyreal_balance_SpellScript Class Reference
Private Member Functions
PrepareSpellScript (spell_illidari_council_empyreal_balance_SpellScript)
bool Load () override
void HandleDummy (SpellEffIndex effIndex)
void HandleAfterCast ()
void Register () override
Private Attributes
float _sharedHealth
float _sharedHealthMax
uint8 _targetCount
Additional Inherited Members
Public Member Functions inherited from SpellScript
bool _Validate (SpellInfo const *entry) override
bool _Load (Spell *spell)
void _InitHit ()
bool _IsEffectPrevented (SpellEffIndex effIndex)
bool _IsDefaultEffectPrevented (SpellEffIndex effIndex)
void _PrepareScriptCall (SpellScriptHookType hookType)
void _FinishScriptCall ()
bool IsInCheckCastHook () const
bool IsInTargetHook () const
bool IsInHitPhase () const
bool IsInEffectHook () const
Unit * GetCaster ()
Unit * GetOriginalCaster ()
SpellInfo const * GetSpellInfo ()
SpellValue const * GetSpellValue ()
WorldLocation const * GetExplTargetDest ()
void SetExplTargetDest (WorldLocation &loc)
WorldObject * GetExplTargetWorldObject ()
Unit * GetExplTargetUnit ()
GameObject * GetExplTargetGObj ()
Item * GetExplTargetItem ()
Unit * GetHitUnit ()
Creature * GetHitCreature ()
Player * GetHitPlayer ()
Item * GetHitItem ()
GameObject * GetHitGObj ()
WorldLocation * GetHitDest ()
int32 GetHitDamage ()
void SetHitDamage (int32 damage)
void PreventHitDamage ()
int32 GetHitHeal ()
void SetHitHeal (int32 heal)
void PreventHitHeal ()
Spell * GetSpell ()
Aura * GetHitAura ()
void PreventHitAura ()
void PreventHitEffect (SpellEffIndex effIndex)
void PreventHitDefaultEffect (SpellEffIndex effIndex)
int32 GetEffectValue () const
void SetEffectValue (int32 value)
Item * GetCastItem ()
void CreateItem (uint32 effIndex, uint32 itemId)
SpellInfo const * GetTriggeringSpell ()
void FinishCast (SpellCastResult result)
void Cancel ()
void SetCustomCastResultMessage (SpellCustomErrors result)
Public Member Functions inherited from _SpellScript
_SpellScript ()
virtual ~_SpellScript ()
virtual void _Register ()
virtual void _Unload ()
virtual void _Init (std::string const *scriptname, uint32 spellId)
std::string const * _GetScriptName () const
virtual bool Validate (SpellInfo const *)
virtual void Unload ()
Static Public Member Functions inherited from _SpellScript
static bool ValidateSpellInfo (std::initializer_list< uint32 > spellIds)
template<class T >
static bool ValidateSpellInfo (T const &spellIds)
Public Attributes inherited from SpellScript
HookList< CastHandler > BeforeCast
HookList< CastHandler > OnCast
HookList< CastHandler > AfterCast
HookList< CheckCastHandler > OnCheckCast
HookList< EffectHandler > OnEffectLaunch
HookList< EffectHandler > OnEffectLaunchTarget
HookList< EffectHandler > OnEffectHit
HookList< EffectHandler > OnEffectHitTarget
HookList< BeforeHitHandler > BeforeHit
HookList< HitHandler > OnHit
HookList< HitHandler > AfterHit
HookList< ObjectAreaTargetSelectHandler > OnObjectAreaTargetSelect
HookList< ObjectTargetSelectHandler > OnObjectTargetSelect
HookList< DestinationTargetSelectHandler > OnDestinationTargetSelect
Protected Attributes inherited from _SpellScript
uint8 m_currentScriptState
std::string const * m_scriptName
uint32 m_scriptSpellId
Detailed Description
Definition at line 596 of file illidari_council.cpp.
Member Function Documentation
HandleAfterCast()
void spell_illidari_council_empyreal_balance::spell_illidari_council_empyreal_balance_SpellScript::HandleAfterCast () inline private
Definition at line 619 of file illidari_council.cpp.
         {
             if (_targetCount != 4)
             {
                 GetCaster()->ToCreature()->AI()->EnterEvadeMode();
                 return;
             }
             float pct = (_sharedHealth / _sharedHealthMax) * 100.0f;
             std::list<TargetInfo> const* targetsInfo = GetSpell()->GetUniqueTargetInfo();
             for (std::list<TargetInfo>::const_iterator ihit = targetsInfo->begin(); ihit != targetsInfo->end(); ++ihit)
                 if (Creature* target = ObjectAccessor::GetCreature(*GetCaster(), ihit->targetGUID))
                 {
                     target->LowerPlayerDamageReq(target->GetMaxHealth());
                     target->SetHealth(CalculatePct(target->GetMaxHealth(), pct));
                 }
         }
References _sharedHealth, _sharedHealthMax, _targetCount, Creature::AI(), CalculatePct(), CreatureAI::EnterEvadeMode(), SpellScript::GetCaster(), ObjectAccessor::GetCreature(), SpellScript::GetSpell(), Spell::GetUniqueTargetInfo(), and Object::ToCreature().
Referenced by Register().
HandleDummy()
void spell_illidari_council_empyreal_balance::spell_illidari_council_empyreal_balance_SpellScript::HandleDummy (SpellEffIndex effIndex) inline private
Definition at line 608 of file illidari_council.cpp.
         {
             PreventHitDefaultEffect(effIndex);
             if (Unit* target = GetHitUnit())
             {
                 _targetCount++;
                 _sharedHealth += target->GetHealth();
                 _sharedHealthMax += target->GetMaxHealth();
             }
         }
References _sharedHealth, _sharedHealthMax, _targetCount, SpellScript::GetHitUnit(), and SpellScript::PreventHitDefaultEffect().
Referenced by Register().
Load()
bool spell_illidari_council_empyreal_balance::spell_illidari_council_empyreal_balance_SpellScript::Load () inline override private virtual
Reimplemented from _SpellScript.
Definition at line 600 of file illidari_council.cpp.
         {
             _sharedHealth = 0;
             _sharedHealthMax = 0;
             _targetCount = 0;
             return GetCaster()->GetTypeId() == TYPEID_UNIT;
         }
References _sharedHealth, _sharedHealthMax, _targetCount, SpellScript::GetCaster(), Object::GetTypeId(), and TYPEID_UNIT.
PrepareSpellScript()
spell_illidari_council_empyreal_balance::spell_illidari_council_empyreal_balance_SpellScript::PrepareSpellScript (spell_illidari_council_empyreal_balance_SpellScript) private
Register()
void spell_illidari_council_empyreal_balance::spell_illidari_council_empyreal_balance_SpellScript::Register () inline override private virtual
Implements _SpellScript.
Definition at line 637 of file illidari_council.cpp.
         {
             OnEffectHitTarget += SpellEffectFn(spell_illidari_council_empyreal_balance_SpellScript::HandleDummy, EFFECT_0, SPELL_EFFECT_DUMMY);
             AfterCast += SpellCastFn(spell_illidari_council_empyreal_balance_SpellScript::HandleAfterCast);
         }
References SpellScript::AfterCast, EFFECT_0, HandleAfterCast(), HandleDummy(), SpellScript::OnEffectHitTarget, SPELL_EFFECT_DUMMY, SpellCastFn, and SpellEffectFn.
Member Data Documentation
_sharedHealth
float spell_illidari_council_empyreal_balance::spell_illidari_council_empyreal_balance_SpellScript::_sharedHealth private
Definition at line 644 of file illidari_council.cpp.
Referenced by HandleAfterCast(), HandleDummy(), and Load().
_sharedHealthMax
float spell_illidari_council_empyreal_balance::spell_illidari_council_empyreal_balance_SpellScript::_sharedHealthMax private
Definition at line 645 of file illidari_council.cpp.
Referenced by HandleAfterCast(), HandleDummy(), and Load().
_targetCount
uint8 spell_illidari_council_empyreal_balance::spell_illidari_council_empyreal_balance_SpellScript::_targetCount private
Definition at line 646 of file illidari_council.cpp.
Referenced by HandleAfterCast(), HandleDummy(), and Load().
The documentation for this class was generated from the following file:
src/server/scripts/Outland/BlackTemple/illidari_council.cpp