Azerotcore-wotlk: deps/mysqllite/mysys/my_delete.c File Reference
my_delete.c File Reference
#include "mysys_priv.h"
#include "mysys_err.h"
#include <my_sys.h>
Functions
int my_delete (const char *name, myf MyFlags)
Function Documentation
my_delete()
int my_delete (const char * name, myf MyFlags)
Definition at line 20 of file my_delete.c.
 {
   int err;
   DBUG_ENTER("my_delete");
   DBUG_PRINT("my",("name %s MyFlags %d", name, MyFlags));
   if ((err = unlink(name)) == -1)
   {
     my_errno=errno;
     if (MyFlags & (MY_FAE+MY_WME))
       my_error(EE_DELETE,MYF(ME_BELL+ME_WAITTANG+(MyFlags & ME_NOINPUT)),
            name,errno);
   }
   else if ((MyFlags & MY_SYNC_DIR) &&
            my_sync_dir_by_file(name, MyFlags))
     err= -1;
   DBUG_RETURN(err);
 } /* my_delete */
References DBUG_ENTER, DBUG_PRINT, DBUG_RETURN, EE_DELETE, errno, ME_BELL, ME_NOINPUT, ME_WAITTANG, my_errno, my_error(), MY_FAE, MY_SYNC_DIR, my_sync_dir_by_file(), MY_WME, and MYF.
Referenced by cache_remove_open_tmp(), close_cached_file(), create_temp_file(), inline_mysql_file_delete(), my_copy(), my_create(), my_create_with_symlink(), my_delete_with_symlink(), my_rename(), and my_rename_with_symlink().